### ISSUE TITLE
Strange behavior with 'nothing' in constructors

### ISSUE THREAD

**Issue by poulson** [JuliaLang/julia#10007]
The following two simple class definitions are essentially identical, but the latter throws a ``convert`` error when instantiating. Is there some strange magic going on behind the scenes with respect to branching based upon ``nothing``?
  
    type Foo
      has_parent::Bool
      parent::Foo

      function Foo(parent=nothing)
        this = new()
        this.has_parent = (parent == nothing)
        if parent != nothing
          this.parent = parent
        end
        this
      end
    end

    type Bar
      has_parent::Bool
      parent::Bar

      function Bar(parent=nothing)
        this = new()
        this.has_parent = (parent == nothing)
        if this.has_parent
          this.parent = parent
        end
        this
      end
    end
    
    f = Foo()
    # This will throw a 'convert' error
    b = Bar()

**Comment by jakebolewski** [comment]
in the first case  you are checking that parent != nothing before assignment, in the second you are assigning `parent = nothing`.  Do you want the parent field in `Bar` to be:

```julia
type Bar
   has_parent::Bool
   parent::Nullable{Bar}
end
```

**Comment by poulson** [comment]
@jakebolewski In neither case will ``parent`` be assigned ``nothing``. The control flow of both ``Foo`` and ``Bar`` is identical, which is why I'm confused.

**Comment by poulson** [comment]
Argh, I should have had a ``!=`` instead of ``==``.
