### ISSUE TITLE
Addition is broken for UniformScaling with AbstractMatrix types that don't define setindex!

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10004]
`UniformScaling` assumes it can mutate a copy of the `AbstractMatrix` argument type [see here](https://github.com/JuliaLang/julia/blob/1eb52e89780a1784473c56543aac3ba5f8eacecf/base/linalg/uniformscaling.jl#L35-37) with `setindex!`.

Ex:
```julia
julia> d = Diagonal(rand(5,5))
5x5 Base.LinAlg.Diagonal{Float64}:
 0.885176  0.0       0.0       0.0       0.0
 0.0       0.553487  0.0       0.0       0.0
 0.0       0.0       0.371698  0.0       0.0
 0.0       0.0       0.0       0.106945  0.0
 0.0       0.0       0.0       0.0       0.150074

julia> d + I
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37

julia> I + d
ERROR: MethodError: `setindex!` has no method matching setindex!(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Int64, ::Int64)
Closest candidates are:
  setindex!(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any, ::Any...)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real)
  setindex!{T}(::Array{T,N}, ::Any, ::Real, ::Real, ::Real)
  ...

 in + at linalg/uniformscaling.jl:37
 in + at linalg/uniformscaling.jl:28
```

**Comment by simonster** [comment]
`UniformScaling` assumes it can mutate the object returned by `similar`. That seems reasonable to me. If an AbstractArray doesn't implement `setindex!`, then `similar` should return an Array, e.g. `similar(::Range)` returns a Vector.

**Comment by JeffBezanson** [comment]
Yes, there is no point in implementing `similar` if the result can't be mutated.

It would also be nice to have a protocol for initializing arrays without mutation.

**Comment by jakebolewski** [comment]
Many abstract matrix types in the linear algebra code are treated as `immutable` arrays for the most part, but then annoyingly define mutating methods where it is convenient (like inplace mutation of the diagonal element for the Diagonal type, but not for the off diagonal).  There is a lot of inconsistency with what methods assume mutating / non-mutating behavior.  I'm trying to poke around to see where these assumptions break.

It would be cleaner if special matrices were defined as immutable arrays and all methods returned a copy of the special matrix type or fell back to calling `full()`.

**Comment by JeffBezanson** [comment]
It looks like the Triangular matrices are the only special ones that have `setindex!` right now. It's not obvious to me that the "partial setindex" behavior is so bad. Might as well extend it to all the special matrix types, and just have them be mutable.

Of course, we should have better support for immutable arrays too, such that making all special matrices immutable would be a workable decision if we wanted to go that way.

**Comment by tkelman** [comment]
> then annoyingly define mutating methods where it is convenient

More like where someone was motivated enough to write the methods. I fail to see how making any array type that isn't the typical dense case immutable helps anything, other than saying the problem of needing to write too many methods for correct mutable behavior is too hard and we give up.

> all methods returned a copy of the special matrix type or fell back to calling `full()`.

No, that would be absolutely awful. Please don't promote to full unless absolutely necessary. We need to remove assumptions that all arrays are full in generic code, not add more of them.

**Comment by andreasnoack** [comment]
This leads back to the discussion of `AbstractMatrix` is about `getindex`/`setindex!` or `*`/`\` where it was decided that it should be the former because it generalizes to higher dimensions and arbitrary element types. However, I don't think that `getindex`/`setindex!` should be allowed to tyrannize the special matrix types too much. The special matrix types are mainly about `*` and `\` or other linear algebra operations.

It might be a solution to drop the sub typing to `AbstractMatrix` for the special matrix types and instead define some other abstraction for them. Then we could worry less about the special matrix types being enough array like.

**Comment by mbauman** [comment]
Any opinion on the solution here?  The fix is very simple in either case: remove the similar definition or add a:

```jl
setindex!(d::Diagonal, v, x::Int, y::Int) = (x == y) ? d.diag[x] = v : assert(v == 0)
```

**Comment by tkelman** [comment]
What's wrong with `Diagonal` being properly mutable here? I still disagree with

> The special matrix types are mainly about `*` and `\` or other linear algebra operations.

this happens to be the case with the current methods that are implemented, but it's not really an inherent property of all structured matrix types.

Your `setindex!` looks like the right idea to me, though I'd want to throw a better error than an assertion failure (e.g. suggesting to convert first to a different type such as general sparse if someone tries to `setindex!` an off-diagonal to a nonzero value).

**Comment by StefanKarpinski** [comment]
I agree with @tkelman's take on this: we should make special matrix types look and behave as much like normal matrices as possible, including allowing mutation where feasible. I also think that we should make the factorization objects look and behave as much like normal matrices as possible – i.e. support extracting elements by indexing, and print them like normal matrices.

**Comment by andreasnoack** [comment]
I think it is fine with the `setindex!` definition for `Diagonal` or whenever it doesn't hurt, but in general I believe the structures matrices is the wrong solution for you if `getindex/setindex!` is important for you.

**Comment by nalimilan** [comment]
@andreasnoack It's sometimes the wrong solution, but it doesn't hurt to support these operations as much as possible. We should let people decide whether and when they want to convert their objects to a standard `Array`, if they really need to.
