### ISSUE TITLE
`rot*` functions are not completely defined

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10002]
`rotl90`, `rotr90` and `rot180` have methods defined for `rot(::AbstractMatrix, k::Integer)` but fail for `AbstractMatrix` subtypes when `k=1` because the fallback `rot(::AbstractMatrix)` method is not defined.

**Comment by JeffBezanson** [comment]
The existence of `rot(::AbstractMatrix, k::Integer)` doesn't hurt --- the only real problem is missing definitions of `rot(m)` for various matrix types. I'm not sure there is an efficient generic implementation.

**Comment by JeffBezanson** [comment]
Should we add fallbacks like `rot(x::AbstractMatrix) = rot(convert(Array,x))`?

**Comment by tkelman** [comment]
Not a fan of implicit conversions here, you throw away a lot of structural information and potentially do a lot of unnecessary work. No-method errors are more honest here.

**Comment by JeffBezanson** [comment]
Yes, I'm fine with that. I think these functions are not super important and can be added as needed. @jakebolewski reopen if I'm wrong.
