### ISSUE TITLE
In-place right multiply by a Triangular Matrix?

### ISSUE THREAD

**Issue by aviks** [JuliaLang/julia#10019]
`A_mul_B!` does not have a method with the third parameter as a `Triangular` . Should this not be possible?

```julia
julia> A
3x3 Array{Float64,2}:
  1.0        -0.0844873  -0.246655
 -0.0844873   1.0        -0.648492
 -0.246655   -0.648492    1.0     

julia> A_mul_B!(similar(A), rand(size(A)), chol(A,:L))
ERROR: `A_mul_B!` has no method matching A_mul_B!(::Array{Float64,2}, ::Array{Float64,2}, ::Triangular{Float64,Array{Float64,2},:L,false})

julia> A_mul_B!(similar(A), chol(A,:L), rand(size(A)))
3x3 Array{Float64,2}:
  0.602234   0.832127   0.964959
  0.788473   0.491243   0.844884
 -0.550021  -0.48907   -0.646176

julia> A_mul_B!(similar(A), rand(size(A)), full(chol(A,:L)))
3x3 Array{Float64,2}:
 0.832313   0.123504   0.0572825
 0.407831  -0.0760749  0.651606 
 0.253726  -0.511957   0.697846 
```

**Comment by jiahao** [comment]
Probably no one has bothered to implement it.

**Comment by andreasnoack** [comment]
I bothered, but we are following BLAS here. Triangular multiplication can be done in place, i.e. `C = A*C` where `A` is triangular. Therefore the bang version only takes two arguments: `A_mul_B!(C,A)`.

This is in contrast to general multiplication that cannot be done in place and therefore has the form `C:=AB+C`.

**Comment by andreasnoack** [comment]
@aviks I didn't read your example carefully enough. I can see the inconsistency in having the three argument version for the case where the triangular matrix is to the left, but not when it is to the right. However, I think the better solution is to remove the three argument versions. It will make the in-place triangular multiplication methods consistent and it will be more transparent.

**Comment by simonster** [comment]
The argument for the three argument version is that some functions might want to accept either an ordinary `Matrix` or a `Triangular` and still do matrix operations without allocating additional memory.

**Comment by timholy** [comment]
Not supporting the 3-argument versions makes generic programming harder.

**Comment by andreasnoack** [comment]
Do you actually use this? If so I'd be fine with supporting it, but in my applications triangular and general matrix multiplications are not used in the same places.

**Comment by timholy** [comment]
I think so, but I can't remember for sure and don't have time to check now. I remember once stumbling across discovering the API difference by accident, which may that I wasn't expecting it.

**Comment by aviks** [comment]
In my case, I had to multiply a 2D slice of a 3D matrix with the result of a Cholesky decomposition, and assign the result into a slice of another 3D matrix. I want to do this without any extra copying, and the 3 arg version of A_mul_B! seemed like the obvious choice.

**Comment by andreasnoack** [comment]
In your use case, would it be awkward copy the data to the new array before the multiplication of the Cholesky? I guess it could be faster to copy the data in a big chunk. Again, if it is really useful, then we could probably support it, but I my own experience is just that it is rarely needed.

**Comment by aviks** [comment]
Yes, the cholesky itself is constant accross the loop. So I am making a copy with `full` and using that. It just seemed inconsistent, and hence the report. But it's not a blocker by any means, and I would be  OK for this to be a _WONTFIX_

**Comment by andreasnoack** [comment]
Just to be sure that we are not misunderstanding each other here. Is you use case like the following example?
```julia
julia> C = chol(randn(3,3) |> t -> t't, :L)
3x3 Base.LinAlg.LowerTriangular{Float64,Array{Float64,2}}:
  1.21231   0.0       0.0    
 -0.157495  1.60136   0.0    
 -1.04009   0.326573  1.79356

julia> A1 = randn(1000, 3, 1000);

julia> A2 = randn(1000, 3, 1000);

julia> copy!(A2, A1);

julia> for i = 1:size(A2, 3); A_mul_B!(sub(A2,:,:,i), C);end
```
and would this way of solving it be less convenient and/or slower than you suggested solution with a three argument `A_mul_B!`?

My point was that `copy!(A2,A1)` is probably faster than copying each slice at a time.

**Comment by aviks** [comment]
> My point was that copy!(A2,A1) is probably faster than copying each slice at a time.

Ok, right, got it now, thanks. That makes sense.. I hadn't thought of that idiom.
