### ISSUE TITLE
libgit2 cross-compile failure

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#10010]
libgit2 doesn't compile correctly for x86 on 64-bit.

here's a start at patching it:
```diff
diff --git a/Make.inc b/Make.inc
index ccf6cbd..a926e7a 100644
--- a/Make.inc
+++ b/Make.inc
@@ -464,9 +464,9 @@ endif
 # Set some ARCH-specific flags
 ifneq ($(USEICC),1)
 ifneq ($(ARCH), arm)
-CC += -m$(BINARY)
-CXX += -m$(BINARY)
-FC += -m$(BINARY)
+CC_ARG += -m$(BINARY)
+CXX_ARG += -m$(BINARY)
+FC_ARG += -m$(BINARY)
 endif
 endif
 
@@ -789,6 +789,10 @@ LDFLAGS += -cxxlib-nostd -static-intel
 endif
 endif
 
+CC += $(CC_ARG)
+CXX += $(CXX_ARG)
+FC += $(FC_ARG)
+
 # Make tricks
 
 define dir_target
diff --git a/README.md b/README.md
index 8fd94fe..2985c32 100644
--- a/README.md
+++ b/README.md
@@ -187,7 +187,7 @@ Julia does not install anything outside the directory it was cloned into. Julia
 
 Julia can be built for a non-generic architecture by configuring the `ARCH` Makefile variable. See the appropriate section of `Make.inc` for additional customization options, such as `MARCH` and `JULIA_CPU_TARGET`.
 
-For example, to build for Pentium 4, set `MARCH=pentium4` and install the necessary system libraries for linking. On Ubuntu, these may include lib32gfortran3 (also manually call `ln -s /usr/lib32/libgfortran3.so.0 /usr/lib32/libgfortran3.so`) and lib32gcc1, lib32stdc++6, among others.
+For example, to build for Pentium 4, set `MARCH=pentium4` and install the necessary system libraries for linking. On Ubuntu, these may include `lib32gfortran3` (also manually call `ln -s /usr/lib32/libgfortran3.so.0 /usr/lib32/libgfortran3.so`) and `lib32gcc1`, `lib32stdc++6`, `lib32z1-dev`, among others.
 
 You can also set `MARCH=native` for a maximum-performance build customized for the current machine CPU.
 
diff --git a/deps/Makefile b/deps/Makefile
index c42036c..e851ac6 100644
--- a/deps/Makefile
+++ b/deps/Makefile
@@ -20,11 +20,11 @@ CMAKE_COMMON += -DCMAKE_VERBOSE_MAKEFILE=ON
 endif
 CMAKE_COMMON += -DCMAKE_C_COMPILER="$(CC_BASE)"
 ifdef CC_ARG
-CMAKE_COMMON += -DCMAKE_C_COMPILER_ARG1="$(CC_ARG)"
+CMAKE_COMMON += -DCMAKE_C_FLAGS="$(CC_ARG)"
 endif
 CMAKE_COMMON += -DCMAKE_CXX_COMPILER="$(CXX_BASE)"
 ifdef CXX_ARG
-CMAKE_COMMON += -DCMAKE_CXX_COMPILER_ARG1="$(CXX_ARG)"
+CMAKE_COMMON += -DCMAKE_CXX_FLAGS="$(CXX_ARG)"
 endif
 
 # If the top-level Makefile is called with environment variables,
```

but cmake seems to get very confused that it isn't using the system libraries/headers/compiler and it ends up computing the dependency locations wrong.

**Comment by tkelman** [comment]
Yeah, cmake is kind of a pain with cross-compiling. You need a whole bunch of flags to tell it to look in a different sysroot, and not check the usual locations. The Linux-to-Windows cross-compile of libgit2 does work, so something similar could possibly be made to work here.

Though note this also might break USE_CCACHE.

**Comment by vtjnash** [comment]
yeah, although it looks like it works mostly because it's heavily hacked into the libgit2 file. it's unfortunate that `autoconf` actually seems to be incredibly good at this, while cmake is so incredibly awful at it.

**Comment by tkelman** [comment]
Right, cross-compiling is probably cmake's biggest weakness as far as I'm concerned. I think what people commonly do is use a toolchain file where they start throwing all the flags they end up needing for cross-compiling. Or on the opensuse build service they've got some convenient `mingw64_cmake` spec macros that expand out to all the flags you need.

**Comment by tkelman** [comment]
(whoops, put this in the wrong place, moved from #11021) looks like Ubuntu has a convenient [`MultiArchCross.cmake` toolchain file](http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/cmake/trusty/view/head:/debian/MultiArchCross.cmake) that we could set a bunch of `DEB_BUILD_GNU_TYPE` etc environment variables to activate and it might fix this, but I can't see any signs of that file having been upstreamed from Ubuntu to Debian or from Debian to cmake. Check `/usr/share/cmake-*/Modules` to see if it's there on Debian.

**Comment by tkelman** [comment]
@garrison I just tried this in a docker container of Ubuntu 15.04 (had to run `dpkg --add-architecture i386`) and it's actually fixed automatically there. That multiarch toolchain file must be getting used automatically by Ubuntu's copy of cmake. I get this output during the configuration step of libgit2:
```
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.1f")
```

Might be worth bothering the Debian maintainer of cmake to adopt the setup that Ubuntu is using, since it works. There might be an open Debian bug about it already, I'd have to look.
