### ISSUE TITLE
`x in ENV` always false 

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#10020]
I'm not sure how, since `in(k::AbstractString, ::KeyIterator{EnvHash}) = _hasenv(k)` is in https://github.com/JuliaLang/julia/blob/a2c3206b4c733648a3c2c4417ffa8b2dc873ddb3/base/env.jl#L101.
```julia
julia> Base._hasenv("SHELL")
true
julia> "SHELL" in ENV
false
julia> in("SHELL", ENV)
false
julia> @which("SHELL" in ENV)
in(x,itr) at reduce.jl:342
```
I checked it on 3.5 and 0.4.0-dev+3052.

**Comment by JeffBezanson** [comment]
That definition is for a `KeyIterator`, so you need `x in keys(ENV)`.

**Comment by jiahao** [comment]
I get tripped up on this Pythonism too. Julia dictionaries support `(key, value) in dict` but not `key in dict`.

```jl
julia> ("SHELL", "/bin/zsh") in ENV
true
```

**Comment by StefanKarpinski** [comment]
This is the way to test if a key is in `ENV`:

```julia
julia> "SHELL" in keys(ENV)
true
```

**Comment by ivarne** [comment]
It feels like testing `in(a::T, b::Dict)` where `T` is not a `Tuple` with 2 fields could be an error with a suggestion?

**Comment by quinnj** [comment]
Don't forget Pairs as well. (i.e. in(a::Pair, b::Dict) should be valid)

**Comment by StefanKarpinski** [comment]
Right, we need to go through and use Pairs consistently everywhere here.

**Comment by ggggggggg** [comment]
Thanks for the correction.
