### ISSUE TITLE
Want `blas_get_num_threads`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#10028]
Since there's a `blas_set_num_threads`, there should also be a `blas_get_num_threads`. I want to know how many threads OpenBLAS is using on my system by default.

**Comment by andreasnoack** [comment]
I'd like the same thing, but I think this is actually a restriction in the OpenBLAS API.

**Comment by jiahao** [comment]
cc @xianyi

**Comment by eschnett** [comment]
There is a global OpenBLAS variable that we could access. (Or submit a patch to OpenBLAS...)

**Comment by ViralBShah** [comment]
Submitting a patch to OpenBLAS seems the best way forward.

**Comment by eschnett** [comment]
See https://github.com/xianyi/OpenBLAS/pull/497.

**Comment by tkelman** [comment]
We're now using a version of openblas that supports this API. Should we add Julia ccall wrappers for it? Does MKL provide an equivalent function?

**Comment by ViralBShah** [comment]
We should certainly support it. I don't know about MKL.

**Comment by KristofferC** [comment]
Regarding the comments in https://github.com/JuliaLang/julia/pull/15008, should this be closed? @eschnett

**Comment by ViralBShah** [comment]
```
➜  Julia@1.5 git:(master) ~/julia/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1722 (2020-12-09)
 _/ |\__'_|_|_|\__'_|  |  Commit 599d3299c9* (7 days old master)
|__/                   |

julia> using LinearAlgebra

julia> BLAS.get_num_threads()
2

```
