### ISSUE TITLE
*fact(::AbstractMatrix, ::AbstractMatrix) currently missing method definitions for most special matrix types

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10026]
`Bidiagonal`, `Diagonal`, `UpperTriangular`, `LowerTriangular`, `SymTridiagonal` and combinations thereof are currently not implemented.

This impacts `bkfact`, `cholfact`, `qrfact`, `schurfact`, etc.

**Comment by andreasnoack** [comment]
I don't think that the `*fact` methods should cover all special matrix types, e.g. Bunch-Kaufman is only defined for Hermitian and symmetric matrices and only `svd`, `eig` and `schur` support two argument versions.

Are no method errors generally unacceptable?

**Comment by jakebolewski** [comment]
The documentation could be updated to say this explicitly.  This might be an instance where we would want to throw a deliberately unimplemented method exception (ref #7512) to give better context why these are undefined.

If these methods are restricted to dense-strided matrices and some subset of the special matrix types perhaps the argument types should be restricted to reflect this.

For instance, `eigfact` is defined as:
```julia
eigfact{TA,TB}(A::AbstractArray{TA,2},B::AbstractArray{TB,2}) at linalg/factorization.jl:566
```
so I would expect it to work for any two arguments `<: AbstractMatrix`, or at least all those defined in Base.LinAlg.

**Comment by andreasnoack** [comment]
I don't think that is a general design rule in base. Many methods have signatures that are way too loose then, e.g. it would hard to accept signatures with `Any`.

The idea in linalg is to restrict the signature as much as necessary and not more, but I don't claim that this has been followed strictly.

The method in line `566` is a promotion method to be used whenever the two arguments don't have the same element type. It is useful because the both the `eigfact(StridedMatrix{T}, StridedMatrix{T})` and `eigfact(Hermitian{T},Hermitian{T})` methods can use the same promotion method.

**Comment by jakebolewski** [comment]
`isposdef` is also undefined for most special matrix types.

**Comment by tkelman** [comment]
> If these methods are restricted to dense-strided matrices and some subset of the special matrix types perhaps the argument types should be restricted to reflect this.

That could get annoying quickly for people trying to extend these types. The special matrix types are already not very cohesively designed or extensible. These particular missing methods are a subset of the larger problem #8001

**Comment by andreasnoack** [comment]
The doc strings seem state when special matrices are supported. I think that is the best way to handle this. If some of the doc strings are not complete, we can open individual issues.

**Comment by tkelman** [comment]
There are unimplemented cases here that could and should be implemented. If not here, we should track those somewhere.

**Comment by tkelman** [comment]
cc @kshyatt who may have similar issues open
