### ISSUE TITLE
Document how to debug Julia with Mozilla's "Record and Reply Framework" (`rr`)

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10021]
It would be great to get Julia working under Mozilla's [Record and Replay Framework](http://rr-project.org/), otherwise known as ``rr``.  This has the potential of being incredibly helpful while debugging intermittent bugs.

As of mozilla/rr@cd502dbf, `rr` `master` supports all system calls used by a basic invocation of `julia` on Linux, except for `shmget` ~~and `mbind`~~, which are actually called by OpenBLAS.  Until `rr` implements these calls (mozilla/rr#1053), OpenBLAS must be compiled in a way that does not use them (but this may limit the extent to which `rr` can be used to debug intermittent bugs that result from OpenBLAS).  The patch to OpenBLAS listed below is a first attempt at this, and enough to get `julia` working under `rr`.  I am not absolutely certain it results in a correct program, and there may even be a better way to build OpenBLAS without using `shmget`, e.g. by passing certain flags to the build.

    openblas-v0.2.13/driver/others/memory.c--- openblas-v0.2.13-orig/driver/others/memory.c	2014-12-03 07:14:21.000000000 -0800
    +++ openblas-v0.2.13/driver/others/memory.c	2015-02-01 22:38:05.792777292 -0800
    @@ -895,20 +895,20 @@
     
       void *map_address;
     
       void *(*memoryalloc[])(void *address) = {
     #ifdef ALLOC_DEVICEDRIVER
         alloc_devicedirver,
     #endif
     #if defined OS_LINUX  || defined OS_AIX  || defined __sun__  || defined OS_WINDOWS
    -    alloc_hugetlb,
    +    //alloc_hugetlb,
     #endif
     #ifdef ALLOC_SHM
    -    alloc_shm,
    +    //alloc_shm,
     #endif
     #ifdef ALLOC_MMAP
         alloc_mmap,
     #endif
     #ifdef ALLOC_QALLOC
         alloc_qalloc,
     #endif
     #ifdef ALLOC_WINDOWS

In any event, once this is all figured out, we should add instructions for running `julia` under `rr` to the Julia developer documentation.

**Comment by ViralBShah** [comment]
Could you file a PR in OpenBLAS? 

Cc: @xianyi

**Comment by garrison** [comment]
To clarify, this patch is not actually meant to be applied to OpenBLAS in a permanent way.  But it would be great if there were a documented way to build OpenBLAS on Linux (or if possible, a runtime flag) so that it will work without using ``shmget`` and ``mbind``.  Once ``rr`` supports these syscalls, building/running with this flag will no longer be necessary.

Perhaps I'll file an issue with OpenBLAS, depending on what @xianyi thinks.

**Comment by rocallahan** [comment]
mbind support is trivial, I can add that to rr right now. SysV shmem is more work and probably won't happen right away (unless someone else steps up to work on it).

**Comment by rocallahan** [comment]
I just pushed `mbind` support to rr master --- cd502dbff705d928ed396baf94375b7885bdd18a.

**Comment by garrison** [comment]
Thanks @rocallahan !

**Comment by rocallahan** [comment]
I've just pushed support for SysV shmem to rr master in https://github.com/mozilla/rr/commit/a461eaec24f4dca1cd4819ec37640a0d88c29396.

**Comment by rocallahan** [comment]
A few caveats:

None of my applications (Firefox, principally) make serious use of SysV shmem so this hasn't been much tested yet.

This support only works when all the processes sharing a SysV shmem segment are all part of the same rr recording group. The way rr works, it's impossible to handle the case where a recorded process shares memory read/write with another process not recorded by rr. We don't yet have any code in rr to check for this.

Keep in mind that (by design, again) rr runs all your threads/processes on a single core and schedules them itself. This can make some bugs harder to reproduce under rr. Adjusting the `--num-cpu-ticks` recording parameter may help with this. It would be possible and interesting to use more intelligent heuristics to make scheduling decisions that reveal more bugs, though this isn't something I'm planning to work on for the forseeable future.

**Comment by garrison** [comment]
This is very cool.  I was just able to debug an (intentional) crash using rr without any source code changes to Julia.  Perhaps this could be useful for investigating some outstanding intermittent bugs, such as #9924?

**Comment by ivarne** [comment]
More debugging tools is definitely great, but the actionable parts of this issue seems to be fixed, or belong in the OpenBlas repo.

Please comment if you think we should reopen.

**Comment by garrison** [comment]
There is nothing left to do on OpenBLAS now that `rr` implements all the relevant syscalls.  I had left this bug open as a reminder to document how to use `rr` with `julia`, but there is really nothing special to know anymore -- they will work together out of the box as long as `rr` is recent enough.  So closing this issue is fine by me.

**Comment by ivarne** [comment]
A blog post style article would probably be best. Adding chapters to the manual about things we don't regularly test has caused issues and frustration in the past. A blog post has a date, so people might be more tolerant to outdated info.

**Comment by ihnorton** [comment]
This can be a suggestion in the devdoc -- it really only needs to be a
couple lines. For more detail, link to mozilla's rr documentation.

btw, @garrison, thanks for bringing this up and for roping the mozilla
folks into adding the necessary syscalls (and huge thanks for adding them,
@rocallahan!). I tried it last night (using rr master) and it looks like it
will be extremely useful.

**Comment by rocallahan** [comment]
If you find it useful, please add a testimonial here https://github.com/mozilla/rr/wiki/Testimonials :-)

**Comment by vtjnash** [comment]
> This is very cool. I was just able to debug an (intentional) crash using rr without any source code changes to Julia. Perhaps this could be useful for investigating some outstanding intermittent bugs, such as #9924?

is this something we could enable on travis (preferably without a significant performance hit), and have it upload/save the results whenever we get a failure on the master or release-0.3 branch?

**Comment by rocallahan** [comment]
> is this something we could enable on travis (preferably without a significant performance hit)

Unfortunately that probably won't work, because I don't know of any cloud hosting service that enables virtualization of the hardware performance counters that rr needs. Xen, KVM and VMWare support it, but providers don't enable it. If you have any contacts, please complain about this :-).

**Comment by vtjnash** [comment]
seems like it would be a great promotional feature for them, although perhaps a bit of work to set up?

do containers allow access to the necessary hardware performance counters? it seems that travis will allow choosing that over a traditional vm:
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by tkelman** [comment]
I did just get invited to Travis' "#embassy" Slack channel by `@rkh`, but I have no idea what that means. We could open an issue and inquire about it. Building Julia on a Travis docker worker might be a little tough, since we can't use apt-get. Maybe using dependencies out of our generic linux binaries, like what I do on AppVeyor, could work.

**Comment by vtjnash** [comment]
we can't use apt-get, but it seems we get a cache in return. it seems like an acceptable tradeoff.

**Comment by tkelman** [comment]
I'm not sure we need or want a cache on Travis. We'd probably want to do at least `make cleanall` by default, and probably download the dependencies from the nightly binaries which we know will get kept up-to-date.

**Comment by vtjnash** [comment]
perhaps, but for the few dozen builds per day average, it would be nice to clone those out of the cache rather than hitting their network every time

**Comment by tkelman** [comment]
We could probably save the etag of the most recent download to avoid re-downloading the same file multiple times. Though it would be easier to just try to do a source build using
```
language: julia
julia: nightly
sudo: false
```

And see how far you can get without anything from apt-get. We would need to cache the static libraries of LLVM.

**Comment by rocallahan** [comment]
Running rr inside a Linux container should work just as well as in the container's host.

**Comment by xianyi** [comment]
Sorry for the delay.

For OpenBLAS, we plan to provide a compiling flag to avoid calling SysV IPC (shmget) since Android doesn't support SysV IPC.

**Comment by garrison** [comment]
@rocallahan FYI, I managed to successfully run and replay julia using `rr` on a DigitalOcean droplet.  (more discussion in #10952)

**Comment by rocallahan** [comment]
Cool!

Keep in mind that rr forces everything to run on a single core, so it might hide bugs, thus switching all CI tests to run on rr is probably not something anyone should do at this point :-).

**Comment by garrison** [comment]
@rocallahan Thanks for the note.  Quick question (following discussion [here](https://github.com/JuliaLang/julia/pull/10952#issuecomment-97110697)): we have "generic linux binaries" of julia that are built using a lowest-common-denominator version of `glibc`.  If one person runs `rr record` on one Linux distribution (with one version of `glibc`) and another runs `rr replay` of the trace on another distribution (using, perhaps, a different `glibc`), should we expect it to work?

**Comment by rocallahan** [comment]
I would not expect that to work. We haven't done any work on trace portability, because Mozilla currently doesn't need it. I've made a brain-dump of the current known issues around trace portability: https://github.com/mozilla/rr/wiki/Trace-Portability

The biggest issue for porting traces between hetereogenous machines is probably CPUID :-(.

**Comment by vtjnash** [comment]
Would it be possible to use something like Intel's SDE/Pin tool (https://software.intel.com/en-us/articles/intel-software-development-emulator) or would that add too much overhead on top of rr's own attempts at dynamic recompilation?

**Comment by rocallahan** [comment]
rr doesn't do any kind of dynamic recompilation. That's why it's relatively simple, robust and fast :-).

For CPUID, the best fix would be to patch the Linux kernel to support ptrace traps on CPUID instructions (hardware support for that exists, but it's only accessible to the kernel). That's just work no-one's gotten around to (assuming such a patch would be amenable to kernel devs).
