### ISSUE TITLE
blas_set_num_threads(4) doesn't appear to work in 0.4 on my quad-core i7

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10039]
See https://groups.google.com/forum/#!topic/julia-users/tdHfn89qCg0 for the gory details, but in short:

```julia
julia> blas_set_num_threads(4)

julia> peakflops()
1.672556102225802e9

julia> versioninfo()
Julia Version 0.4.0-dev+2529
Commit 322cf26* (2015-01-06 17:18 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Activity monitor pegs the CPU at 99% during `peakflops()`.

Using 0.3.4:
```julia

julia> blas_set_num_threads(4)

julia> peakflops()
8.82650087599987e10

julia> versioninfo()
Julia Version 0.3.4
Commit 3392026* (2014-12-26 10:42 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
CPU here hits 396% (this is a quad core machine).

Note that this appears to be specific to this particular hardware/build; on my dual-core Mac Mini, I don't have this problem on either 0.4 or 0.3.4.

**Comment by tkelman** [comment]
I think you can try setting the environment variable `OPENBLAS_CORETYPE` to different settings like `Nehalem` or `Westmere` to get openblas to use different kernels, see if that makes any difference. I think we're using the same openblas version between 0.3 and 0.4 right now, so this is odd.

**Comment by eschnett** [comment]
The two performance numbers differ by a factor of 40, not just a factor of 4. Something else is fishy.

Was libopenblas maybe inadvertently built without optimization?

Is the working Mac Mini version of Julia the same version, or a different checkout?

**Comment by sbromberger** [comment]
They're slightly different: 0.4.0-dev+2529 on the i7 vs 0.4.0-dev+2481 on the i5.

I'll try rebuilding julia on the i7.

**Comment by sbromberger** [comment]
Rebuilt from scratch:

```
julia> peakflops()
7.547427741103699e10
```

Closing out because it's not reproducible with the latest build, even though 3.4 gives about 30% improved performance.
