### ISSUE TITLE
Upgrading BigNum operators

### ISSUE THREAD

**Issue by skariel** [JuliaLang/julia#10030]
a simple benchmark shows a 10X performance improvement if using a pool of BigInts to be reused in arithmetic operations. A further 2X performance improvement is possible when using in-place operations. See benchmark code below, as run on latest Julia (with the new GC)

This issue is a placeholder for discussions as I intend to open a PR (which I already started working on) to make operators use a pool and add in-place methods for both BigInts and BigFloats.

```Julia
function add!(x::BigInt, y::BigInt)
	ccall((:__gmpz_add, :libgmp), Void, (Ptr{BigInt}, Ptr{BigInt}, Ptr{BigInt}), &x, &x, &y)
	return x
end

type BigIntPool
	pool::Array{BigInt, 1}
	ix::Int64
	BigIntPool(n::Int64) = new([BigInt(0) for i in 1:n], 1)
end

function pooledadd(pool::BigIntPool, x::BigInt, y::BigInt)
	@inbounds const z = pool.pool[pool.ix]
	pool.ix += 1
	if pool.ix > length(pool.pool)
		pool.ix = 1
	end
	ccall((:__gmpz_add, :libgmp), Void, (Ptr{BigInt}, Ptr{BigInt}, Ptr{BigInt}), &z, &x, &y)
	return z
end

function inplace_add(x,y)
	x+=1; y+=1
	for i in 1:100000000
		add!(x,y)
	end
	x
end

function current_add(x,y)
	x+=1; y+=1
	for i in 1:100000000
		x+=y
	end
	x
end

function pooled_add(pool,x,y)
	x+=1; y+=1
	for i in 1:100000000
		x = pooledadd(pool, x, y)
	end
	x
end


a=BigInt(typemax(Int64))
b=BigInt(typemax(Int64))
pool=BigIntPool(100000)

println("---------------------------------------")
inplace_add(deepcopy(a), deepcopy(b))
@show @time inplace_add(deepcopy(a), deepcopy(b))
println("---------------------------------------")
current_add(deepcopy(a), deepcopy(b))
@show @time current_add(deepcopy(a), deepcopy(b))
println("---------------------------------------")
pooled_add(pool, deepcopy(a), deepcopy(b))
@show @time pooled_add(pool, deepcopy(a), deepcopy(b))
```

and the results:

```
julia bench.jl
---------------------------------------
elapsed time: 0.791322316 seconds (29 kB allocated)
@time inplace_add(deepcopy(a),deepcopy(b)) = 922337212908849617654775808
---------------------------------------
elapsed time: 18.817435834 seconds (6103 MB allocated, 12.71% gc time in 279 pauses with 0 full sweep)
@time current_add(deepcopy(a),deepcopy(b)) = 922337212908849617654775808
---------------------------------------
elapsed time: 1.357274903 seconds (1 kB allocated)
@time pooled_add(pool,deepcopy(a),deepcopy(b)) = 9223372036854775808
```

EDIT: fixed typo in code, returning `z` instead of `x` in pooled version

**Comment by JeffBezanson** [comment]
Yes, faster BigInts are badly needed.

We should see if we can get speedup by having finalizers add BigInts to a free pool. Obviously the GC needs to be involved, since otherwise we will overwrite random BigInts.

I think having mutable numbers is just not semantically acceptable.

**Comment by skariel** [comment]
I'll make tomorrow a new benchmark testing such pool filled by finalizers.

any scenario in which the pool isn't completely emptied should result in a nice performance boost. In cases where it is completely emptied new BigInts will get produced until a steady state in which the pool is non-empty is reached.

So seems to me this must work :)

I don't completely agree with you regarding mutable numbers as I'm more on the performance side of the trade-of. Also when BigInts get really big the performance hit may grow. Imagine having a distributed BigInt...

**Comment by JeffBezanson** [comment]
see also #4176

**Comment by kmsquire** [comment]
Cc: @wbhart

**Comment by wbhart** [comment]
Making numbers immutable changes the complexity of some algorithms. Consider adding 1 to a very large bignum. The operation can become O(n) instead of average O(1). This will definitely bite someone. 

On the other hand, I see that making them mutable can also bite people, as Jeff says.

**Comment by StefanKarpinski** [comment]
I think it's acceptable to have some numbers be mutable. The caveats are almost identical to those that come with any other mutable type – don't mutate a value that you don't "own". As long as the mutating operations don't work on immutable values, it seems acceptable to me. Jeff, what kind of thing are you worried about? Do you have some example that I'm just not thinking of that makes this a disaster?

**Comment by JeffBezanson** [comment]
Actually the fact that `+=` is not a mutating operator (or even worse, a mutating operator for some types but not for others) helps us quite a bit here. With that, it is indeed hard to imagine accidentally mutating somebody else's BigInt.

But do we really want `add!` et. al. in Base? It's just so ugly. It might be a good thing to put in a package, like NumericExtensions. We really need to be able to get this optimization for `a + b + c + d`.

**Comment by simonbyrne** [comment]
I'd be happy to incorporate this into [InplaceOps.jl](https://github.com/simonbyrne/InplaceOps.jl)

**Comment by skariel** [comment]
here is my attempt at a gc-pool, it is somewhat disappointing with just a ~2X improvement over un-pooled solution. I'm sure this can be improved, any ideas? (this is a quick draft but nevertheless good for performance measurement)

```Julia
const POOLSIZE = 1000000

type MyBigInt <: Integer
	alloc::Cint
	size::Cint
	d::Ptr{UInt64}
	function MyBigInt()
		b = new(zero(Cint), zero(Cint), C_NULL)
		ccall((:__gmpz_init,:libgmp), Void, (Ptr{MyBigInt},), &b)
		finalizer(b, pooledfinalizer)
		return b
	end
end

function pooledfinalizer(b::MyBigInt)
	if length(pool.pool) < POOLSIZE
		push!(pool.pool, b)
	else
		ccall((:__gmpz_clear,:libgmp), Void, (Ptr{MyBigInt},), &b)
	end
end


function MyBigInt(x::Union(Clong,Int32))
	z = MyBigInt()
	ccall((:__gmpz_set_si, :libgmp), Void, (Ptr{MyBigInt}, Clong), &z, x)
	return z
end

type BigIntPool
	pool::Array{MyBigInt, 1}
	BigIntPool(n::Int64) = new([MyBigInt(0) for i in 1:n])
end

function pooledadd(pool::BigIntPool, x::MyBigInt, y::MyBigInt)
	if length(pool.pool) > 0
		z = pop!(pool.pool)	
		ccall((:__gmpz_add, :libgmp), Void, (Ptr{MyBigInt}, Ptr{MyBigInt}, Ptr{MyBigInt}), &z, &x, &y)
		return z
	end
	z = MyBigInt()
	ccall((:__gmpz_add, :libgmp), Void, (Ptr{MyBigInt}, Ptr{MyBigInt}, Ptr{MyBigInt}), &z, &x, &y)
	return z
end

function pooled_add(pool,x,y)
	for i in 1:100000000
		x = pooledadd(pool, x, y)
	end
	x
end


a=MyBigInt(convert(Clong, typemax(Int64)))
b=MyBigInt(convert(Clong, typemax(Int64)))
const pool=BigIntPool(POOLSIZE)

println("---------------------------------------")
pooled_add(pool, a, b)
a=MyBigInt(convert(Clong, typemax(Int64)))
b=MyBigInt(convert(Clong, typemax(Int64)))
@show length(pool.pool)
@show @time pooled_add(pool, a, b)
```

**Comment by JeffBezanson** [comment]
2x is nothing to sneeze at!

**Comment by skariel** [comment]
The first version is a perfect pool for this specific benchmark, it never gets empty as used numbers are immediately returned to the pool. The downside is that it can work only for very specific cases. For a general solution where most of the time numbers cannot be put back in the pool, like the second pooled version, the pool gets empty and in these instances is not efficient

**Comment by JeffBezanson** [comment]
closing as a dup of #4176
