### ISSUE TITLE
ishermitian(::Diagonal) is wrong for non-real matrices

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10036]
Currently `ishermitian(::Diagonal)` is defined to be `true` always, but this is wrong when the entries have nonzero nonreal components.

```jl
julia> D=Diagonal([Complex(0.0,1.0)])
1x1 Base.LinAlg.Diagonal{Complex{Float64}}:
 0.0+1.0im

julia> ishermitian(D)
true

julia> D'
1x1 Base.LinAlg.Diagonal{Complex{Float64}}:
 0.0-1.0im

julia> D'==D
false
```

**Comment by andreasnoack** [comment]
Why not just fix this?

**Comment by jiahao** [comment]
I'm trying to fix this as part of the Banded matrix branch

**Comment by StefanKarpinski** [comment]
Unless the fix is somehow related to banded matrices (seems unlikely?) it would be better to get this as a separate fix.

**Comment by andreasnoack** [comment]
@JuliaBackports

**Comment by tkelman** [comment]
backported in c0329cb83ab88ea09232f8631ae9032aa635f084
