### ISSUE TITLE
`inv` is broken for `Bidiagonal`

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10034]
This fails in `factorize`:

Ex
```julia
julia> BD
5x5 Base.LinAlg.Bidiagonal{Float64}:
 -2.33818   0.0160447  0.0        0.0        0.0
  0.0      -1.86915    0.106191   0.0        0.0
  0.0       0.0        1.65496   -0.849353   0.0
  0.0       0.0        0.0        0.246264  -0.00214547
  0.0       0.0        0.0        0.0       -1.19128

julia> inv(BD)
ERROR: MethodError: `factorize` has no method matching factorize(::Base.LinAlg.Bidiagonal{Float64})
 in inv at linalg/generic.jl:237
```

**Comment by tkelman** [comment]
Would be resolved by #8240

**Comment by andreasnoack** [comment]
@tkelman I don't think #8240 is enough here. Bidiagonal matrices in LAPACK's band layout doesn't cover our present `Bidiagonal` layout so we would't be able to use a LAPACK routine here.

However, an `inv(Bidiagonal)` but the routine wouldn't be hard to write. But again, I'm not really sure we want `inv(Bidiagonal)`. It really depends on the interpretation of the special matrices.

**Comment by tkelman** [comment]
Using lapack for bidiagonal is pretty pointless and should not be held sacred here. I'd rather have a generic system than go out of our way to support an "optimized" path that doesn't actually matter for performance.

**Comment by andreasnoack** [comment]
I think that such a system would be great, but I also think that it is bit more than what #8240 proposes.

**Comment by jiahao** [comment]
Note that the inverse of Bidiagonal will be in general Triangular.

**Comment by tkelman** [comment]
Oh right, duh, no need to convert to Tridiagonal. Just define `factorize(A::Bidiagonal) = A` and this should work.

**Comment by tkelman** [comment]
Also not implemented: multiplying Bidiagonal and a dense matrix
