### ISSUE TITLE
Inconsistency in operator parsing

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#10046]
I found an inconsistency in how operators is parsed, even operators with the same [operator precedence](http://julia.readthedocs.org/en/latest/manual/mathematical-operations/#operator-precedence)

First of I expected that `:(+ in [+, -])` would be parsed to `:($(Expr(:in, :+, :([+,-]))))` but it got parsed to `:(+(in[+,-]))`, I know this can be obtained by `:((+) in [+, -])`. Then I found `+.` did not get parsed to the same as `+`. The other operators in the same category of operator precedence do also have different ways to get parsed, see the following:
```julia
julia> :(+ in [+, -])
:(+(in[+,-]))

julia> :(- in [+, -])
:(-(in[+,-]))

julia> :($ in [+, -])
:(($(Expr(:$, :in)))[+,-])

julia> :(| in [+, -])
:($(Expr(:in, :|, :([+,-]))))

julia> :(.+ in [+, -])
:($(Expr(:in, :.+, :([+,-]))))

julia> :(.- in [+, -])
:($(Expr(:in, :.-, :([+,-]))))

julia> :(* in [+, -])
:($(Expr(:in, :*, :([+,-]))))
```
I know this is not easy but it could be nice if they at least where parsed to the same expression to add some consistency.

**Comment by JeffBezanson** [comment]
Maybe we should disallow spaces in unary operators, like `-  x`.

**Comment by eschnett** [comment]
Ambiguous parses could be rejected, and could require parentheses for clarification: `(+) in [+,-]`

Isn't this here a problem with how `in` is parsed? If `in` is interpreted as generic identifier, then it's parsed correctly. But we expect it to be parsed as infix operator instead.

**Comment by dhoegh** [comment]
Julia now throw syntax error for the following: `*`,`.-`,`.+`,`|`.

**Comment by dhoegh** [comment]
Just to follow up on this issue `+`,`-`,`$` is now lowered to getindex of `in` which is obviously wrong. Couldn't those cases be disallow as `*`,`.-`,`.+`,`|`. see:
```
julia> :(+ in [+, -])

WARNING: deprecated syntax "in [".
Use "in[" instead.
:(+(in[+,-]))

julia> :(- in [+, -])

WARNING: deprecated syntax "in [".
Use "in[" instead.
:(-(in[+,-]))

julia> :($ in [+, -])

WARNING: deprecated syntax "$in [".
Use "$in[" instead.
:((in)[+,-])
```

**Comment by dhoegh** [comment]
Julia now throws syntax error for all of the above and this can hence be closed.

**Comment by tkelman** [comment]
are all these examples tested as such?

**Comment by dhoegh** [comment]
I have added test in #17683
