### ISSUE TITLE
HDF5 reading  in parallel loop : WARNING: Module HDF5 not defined on process 4, fatal error ...

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/julia#10056]
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2847 (2015-01-21 18:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fc61385 (12 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using HDF5

julia> addprocs(5)
5-element Array{Any,1}:
 2
 3
 4
 5
 6

julia> using HDF5,JLD

julia> fil=h5open("labels_F.h5");obj=fil["F"];k,l=size(obj);close(fil);

julia> procs()
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> ranking=@parallel (sum) for i=-l:-1
       vec(h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1)))
       if mod(i,40)==0 println(i); end;
       end
WARNING: Module HDF5 not defined on process 4
WARNING: Module HDF5 not defined on process 2
fatal error on 4: fatal error on 2: WARNING: Module HDF5 not defined on process 3
WARNING: Module HDF5 not defined on process 6
fatal error on 3: fatal error on 6: WARNING: Module HDF5 not defined on process 5
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
fatal error on 5: ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
Worker 4 terminated.
Worker 5 terminated.Worker 6 terminated.Worker 3 terminated.Worker 2 terminated.



ERROR: ProcessExitedException()
 in wait at task.jl:288
 in wait at task.jl:198
 in wait_full at multi.jl:586
 in remotecall_fetch at multi.jl:686
 in call_on_owner at multi.jl:733
 in fetch at multi.jl:741
 in _mapreduce at reduce.jl:135
 in preduce at multi.jl:1667
```

**Comment by amitmurthy** [comment]
Related https://github.com/JuliaLang/julia/issues/3674

Can you remove the first `using HDF5` and try?

**Comment by paulanalyst** [comment]
now:               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2847 (2015-01-21 18:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fc61385 (13 days old master)
|__/                   |  x86_64-w64-mingw32

julia> addprocs(5)
5-element Array{Any,1}:
 2
 3
 4
 5
 6

julia>  using HDF5,JLD

julia> fil=h5open("labels_F.h5");obj=fil["F"];k,l=size(obj);close(fil);

julia>  procs()
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> ranking=@parallel (sum) for i=-l:-1
       vec(h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1)))
       if mod(i,40)==0 println(i); end;
       end
exception on exception on exception on 54: : exception on 2exception on : 6: 3: ERROR: MethodError: `sum` has no m
ethod matching sum(::Void, ::Void)
Closest candidates are:
  sum(!Matched::BitArray{N}, ::Any)
  sum(!Matched::Union(Func{1},DataType,Function), ::Any)
  sum{T}(!Matched::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in anonymous at no file:3
 in anonymous at multi.jl:1528
 in anonymous at multi.jl:844
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:612
 in anonymous at task.jl:6
ERROR: MethodError: `sum` has no method matching sum(::Void, ::Void)
Closest candidates are:
  sum(!Matched::BitArray{N}, ::Any)
  sum(!Matched::Union(Func{1},DataType,Function), ::Any)
  sum{T}(!Matched::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in anonymous at no file:3
 in anonymous at multi.jl:1528
 in anonymous at multi.jl:844
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:612
 in anonymous at task.jl:6
ERROR: MethodError: `sum` has no method matching sum(::Void, ::Void)
Closest candidates are:
  sum(!Matched::BitArray{N}, ::Any)
  sum(!Matched::Union(Func{1},DataType,Function), ::Any)
  sum{T}(!Matched::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in anonymous at no file:3
 in anonymous at multi.jl:1528
 in anonymous at multi.jl:844
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:612
 in anonymous at task.jl:6
ERROR: MethodError: `sum` has no method matching sum(::Void, ::Void)
Closest candidates are:
  sum(!Matched::BitArray{N}, ::Any)
  sum(!Matched::Union(Func{1},DataType,Function), ::Any)
  sum{T}(!Matched::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in anonymous at no file:3
 in anonymous at multi.jl:1528
 in anonymous at multi.jl:844
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:612
 in anonymous at task.jl:6
ERROR: MethodError: `sum` has no method matching sum(::Void, ::Void)
Closest candidates are:
  sum(!Matched::BitArray{N}, ::Any)
  sum(!Matched::Union(Func{1},DataType,Function), ::Any)
  sum{T}(!Matched::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in anonymous at no file:3
 in anonymous at multi.jl:1528
 in anonymous at multi.jl:844
 in run_work_thunk at multi.jl:603
 in run_work_thunk at multi.jl:612
 in anonymous at task.jl:6
ERROR: MethodError: `sum` has no method matching sum(::MethodError, ::MethodError)
Closest candidates are:
  sum(::BitArray{N}, ::Any)
  sum(::Union(Func{1},DataType,Function), ::Any)
  sum{T}(::Base.SparseMatrix.SparseMatrixCSC{T,Ti<:Integer}, ::Any)
  ...

 in _mapreduce at reduce.jl:137
 in preduce at multi.jl:1667

Paul

**Comment by amitmurthy** [comment]
The return value of the `@parallel` block, which is a `Void` is being reduced via the `sum` and hence the error. You meant to return `vec`?

**Comment by paulanalyst** [comment]
but for "hcat" instead "sum" id a little better:


julia> ranking=@parallel (hcat) for i=-l:-1
       vec(h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1)))
       if mod(i,40)==0 println(i); end;
       end
        From worker 2:  -160
        From worker 3:  -120
        From worker 4:  -80
        From worker 5:  -40
Worker 2 terminated.ERROR: ProcessExitedException()
 in wait at task.jl:288
 in wait at task.jl:198
 in wait_full at multi.jl:586
 in remotecall_fetch at multi.jl:686
 in call_on_owner at multi.jl:733
 in fetch at multi.jl:741
 in _mapreduce at reduce.jl:135
 in preduce at multi.jl:1667

Paul

**Comment by amitmurthy** [comment]
Because this works: 
```
julia> hcat(nothing, nothing)
1x2 Array{Void,2}:
 nothing  nothing
```

**Comment by paulanalyst** [comment]
without "vec"

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2847 (2015-01-21 18:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fc61385 (13 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using HDF5,JLD

julia>  addprocs(5)
5-element Array{Any,1}:
 2
 3
 4
 5
 6

julia> fil=h5open("labels_F.h5");obj=fil["F"];k,l=size(obj);close(fil);

julia>  procs()
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> ranking=@parallel (sum) for i=-l:-1
       h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1))
       if mod(i,40)==0 println(i); end;
       end
WARNING: Module HDF5 not defined on process 2
WARNING: Module HDF5 not defined on process 3
fatal error on fatal error on 2: 3: WARNING: Module HDF5 not defined on process 5
fatal error on WARNING: Module HDF5 not defined on process 4
5: fatal error on 4: ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
WARNING: Module HDF5 not defined on process 6
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
fatal error on 6: ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
ERROR: UndefVarError: HDF5 not defined
 in deserialize at serialize.jl:377
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:395
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in deserialize at serialize.jl:335
 in anonymous at serialize.jl:355
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:355
 in handle_deserialize at serialize.jl:347
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:352
 in anonymous at task.jl:839
Worker 3 terminated.
Worker 5 terminated.Worker 4 terminated.Worker 2 terminated.


Worker 6 terminated.ERROR: ProcessExitedException()
 in wait at task.jl:288
 in wait at task.jl:198
 in wait_full at multi.jl:586
 in remotecall_fetch at multi.jl:686
 in call_on_owner at multi.jl:733
 in fetch at multi.jl:741
 in _mapreduce at reduce.jl:135
 in preduce at multi.jl:1667


julia>

**Comment by paulanalyst** [comment]
hint:

julia> i=183*-1
-183
julia> h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1))
5932868x1 Array{Float64,2}:
 6.66644e-5
 0.0
 0.0
 0.0
 0.0

**Comment by amitmurthy** [comment]
`using` after `addprocs`. And it will not solve your problem since the return value of the `@parallel for` block needs to be `sum`able.

**Comment by paulanalyst** [comment]
5932868x1 Array{Float64,2}: is not sumable to similar ?

**Comment by amitmurthy** [comment]
This `if mod(i,40)==0 println(i); end;` is the last statement in the `for` loop, and its return type is `Void`

**Comment by paulanalyst** [comment]
Thx, is ok but: 
Is slower then with normal loop;) Propably problem is in acces to the same dataset :"mygroup/punkty". Dou You thing if use another dataset for any column will be beter? 
somthing like mygroup/dset1, mygroup/dset2, mygroup/dset3 utc. 


julia> ranking=@parallel (sum) for i=-l:-1
       h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1))
       end
 Array{Float64,2}:
 6.66644e-5
 0.0
 0.0

**Comment by amitmurthy** [comment]
No idea. I am not familiar with HDF5 and it would also be good to know your computing environment for other folks who may be able to help.

Also, these kind of questions are best answered on the julia-users - https://groups.google.com/forum/#!forum/julia-users

**Comment by paulanalyst** [comment]
Big thx. 
But :/
julia> ranking=@parallel (sum) for i=-l:-1
h5read("labels_punkty.h5","mygroup/punkty",(:,i*-1))
end
work, BUT does NOT ADD /; 
In "ranking" is only result of last loop!
Why ?
Paul
P.

**Comment by paulanalyst** [comment]
Why  does NOT ADD ?
julia> A=@parallel (sum) for i=1:10
       rand(5)
       end;A
5-element Array{Float64,1}:
 0.168759
 0.121823
 0.311739
 0.341128
 0.91723

**Comment by amitmurthy** [comment]
I don't know why but `sum` on two arrays returns the first array.
```
julia> a=[1,2]
2-element Array{Int64,1}:
 1
 2

julia> b=[3,4]
2-element Array{Int64,1}:
 3
 4

julia> sum(a, b)
2-element Array{Int64,1}:
 1
 2
```

`rand(5)` returns a five element array of floats. Try with `@parallel (+) for .....`

**Comment by paulanalyst** [comment]
|@parallel (+) for ...
work
P,
|
