### ISSUE TITLE
cell {} related code in base.jl vestigial?

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#10067]
If the base.jl lines 187-203 were needed for {} syntax, perhaps they can go?
```
# used by { } syntax
function cell_1d(xs::ANY...)
    n = length(xs)
    a = Array(Any,n)
    for i=1:n
        arrayset(a,xs[i],i)
    end
    a
end

function cell_2d(nr, nc, xs::ANY...)
    a = Array(Any,nr,nc)
    for i=1:(nr*nc)
        arrayset(a,xs[i],i)
    end
    a
end
```

**Comment by hayd** [comment]
Note: They're not covered https://coveralls.io/builds/1852938/source?filename=base%2Fbase.jl#L187

But perhaps they should be moved to deprecated.jl rather than deleted?

**Comment by ivarne** [comment]
They doesn't appear to be called from anywhere anymore, and they are not exported (so deprecation is almost out of the question).

Please submit a PR with the relevant lines removed.

**Comment by ivarne** [comment]
@catawbasam If you had written `fixes #10067` in the PR, this would have been closed automatically.

**Comment by hayd** [comment]
@ivarne IIRC that's only true for collaborators (but it's always a good idea to do anyway).

**Comment by ivarne** [comment]
@catawbasam can close this manually anyway, so I think it should work (pretty sure it did work before I became a collaborator). I'm not sure what happens if it it wasn't his issue.

**Comment by hayd** [comment]
@ivarne ah yes, it may work if it's your own issue :)
