### ISSUE TITLE
Type and inner ctor static parameters clash

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#10072]
Consider the following minimal example (that represents one of the common pitfalls someone with the superficial knowledge of julia might fall into):
```julia
type A{T}
    x::T
    A{T}() = new(0)
    A{T}(y::T) = new(y)
end
```
recent `0.4dev` generates a warning for the first ctor
```
Warning: static parameter T does not occur in signature for call at none:3.
The method will not be callable.
```
and the methods for e.g. `A{Int64}` are
```
3-element Array{Any,1}:
 call{#s1,T}(::Type{A{#s1}}) at none:3     
 call{#s4,T}(::Type{A{#s4}},y::T) at none:4
 call{T}(::Type{T},args...) at base.jl:36
```
So actually, there are 2 type parameters for the ctor and the name of the first one was substituted by some autogenerated id, but this is not obvious from the warning shown upon type declaration.
Maybe the better alternative would be to warn or even to generate an error if the names of the type parameters gets redefined by its inner constructors?

**Comment by JeffBezanson** [comment]
I don't fully understand the problem. It's actually OK for ctors to use the same static parameter names as the type; inside the ctor `T` will refer to the method's static parameter (the `T` in `A{T}(y::T)`). The warning is the same one we always give for methods with an un-matchable static parameter:

```
julia> A{T}() = 0
Warning: static parameter T does not occur in signature for A at none:1.
The method will not be callable.
A (generic function with 1 method)
```

**Comment by JeffBezanson** [comment]
You can think of the `A{T}() = ...` syntax as introducing a new variable `T`, just like `x->( ... )` introduces a new variable `x` inside the parens. So this `T` shadows the type's `T`, like any other nested scope.

**Comment by alyst** [comment]
@JeffBezanson Yes that's clear. I've just meant that internal ctors are different from the other methods in that they [implicitly] also have the static parameters of the type they construct. So if the method parameter happens to have the same name as the type parameter, it might be reasonable to warn the user, because that might be something unintended.
Inner variables shadow the variables from the outer scope, but in case of the static parameters the outer scope parameter remains in the resulting signature (albeit with a cryptic name).

**Comment by StefanKarpinski** [comment]
This is one of the more confusing corners of the language, imo.

**Comment by JeffBezanson** [comment]
Ok, I understand the idea of giving a warning for shadowing type parameters this way. The user might think they are defining a ctor for `A{T}`. We can consider that.

> but in case of the static parameters the outer scope parameter remains in the resulting signature (albeit with a cryptic name)

I don't see how this matters. With nested scope in general, a compiler will rename variables to fix conflicts. Here the renaming is part of the proper transformation to `call` methods.

**Comment by alyst** [comment]
> I don't see how this matters. With nested scope in general, a compiler will rename variables to fix conflicts. Here the renaming is part of the proper transformation to call methods.

Well, I don't see there's a problem with the language semantics. It matters from the user's perspective. The user has to be aware about the static parameters every time he constructs an object, whereas he can forget about local variables as soon as he's out of the local scope. And also the concept of parametric constructors of parametric types is slightly more sophisticated then variables scope. So IMHO static parameters name clash is worth a warning.

**Comment by JeffBezanson** [comment]
> The user has to be aware about the static parameters every time he constructs an object

But this transformation does not add parameters to the type, only to the method. And indeed you do *not* need to know how many static parameters a method has in order to call it.

It also possible to ignore type parameters via outer constructors, e.g. `A(x)`.

**Comment by tonyhffong** [comment]
Have you used https://github.com/tonyhffong/Lint.jl?

```julia
using Lint
s = """
type MyType{T}
    b::T
    MyType{T}(x::T) = new( T )
end
"""
msgs = lintstr(s)

2-element Array{Lint.LintMessage,1}:
 none:3 [               ] ERROR  Parametric constructors (with curly brackets) should not be inner constructors. Define them outside type definition.
 none:3 [MyType         ] INFO   Argument declared but not used: x
```

**Comment by JeffBezanson** [comment]
It's great that you have cases for things like this in Lint.jl.
Is that warning only given if the parameter name is the same as the type's? Otherwise I don't really agree with it; there is nothing wrong with inner constructors having static parameters. Curly brackets in method definitions always mean the same thing; there is no inner/outer difference there. The inner/outer difference is only in what the name `MyType` refers to.

**Comment by tonyhffong** [comment]
Er no, and that's a good point. It's easy to fix, though.

**Comment by tonyhffong** [comment]
Done. https://github.com/tonyhffong/Lint.jl/commit/00f12dbf406667074a8d7b2570fbc5810bcc4b07
Only colliding symbols will generate an error.

**Comment by JeffBezanson** [comment]
See the discussion in #10146 for ideas on how to make constructors less confusing. I think that plus the case in Lint.jl handles this.
