### ISSUE TITLE
angle() returns only two values - is this correct?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaLang/julia#10079]
I was writing a test for the angle function, which is found here:

https://github.com/JuliaLang/julia/blob/master/base/number.jl#l33

```julia
julia> for x in 1:1:20
          println(angle(x))
       end
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

for x in -1:-1:-20
          println(angle(x))
       end
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
3.141592653589793
```

Admittedly, I don't use this function so my understanding is shallow, but is it intentional to have a function only return `0.0` or `pi`, depending on only the sign of the number passed?

**Comment by jakebolewski** [comment]
`angle` returns the phase angle on the [complex plane](http://en.wikipedia.org/wiki/Complex_plane), so for `Real` numbers this is correct.
