### ISSUE TITLE
Major performance regression in test timing on Travis and AppVeyor

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#10094]
We've been getting a lot of timeouts on both Win64 AppVeyor (https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.2272/job/99mu224bfvhrsd90 and several other cases) and OSX Travis (https://travis-ci.org/JuliaLang/julia/jobs/49532073, and https://travis-ci.org/JuliaLang/julia/jobs/49631764, and others) that appear to just be due to the tests taking much longer than usual. This isn't happening on every build, but this failure mode seems recent to me.

**Comment by mschauer** [comment]
When I ran into this, I thought it hangs rather than being continuously slow.

**Comment by tkelman** [comment]
I'm pretty sure the plain hang is something different, that has happened intermittently all along. Possibly related to #7942. This newer timeout is actually trying to run the tests, they're just taking a very long time.

**Comment by tkelman** [comment]
No idea what the issue was here, but I haven't seen this type of timeout, where the tests don't hang but take over half an hour to run, for several days. If there was a bug maybe someone fixed it. Or maybe it was a temporary performance problem unrelated to Julia that somehow caused intermittent problems on both Travis and AppVeyor.

We still have the occasional Win64 timeout on AppVeyor where either the system image build or the first test freezes, but that's been the case for much longer and no one know what the problem might be there yet. So I'll close this issue until I see this specific type of failure again.
