### ISSUE TITLE
Logical indexing with vectors isn't implemented for sparse matrices

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10113]
See http://stackoverflow.com/questions/28373980/bad-results-in-sparse-matrix-assignment-with-logical-indexing

**Comment by timholy** [comment]
Related: #9917

**Comment by carlobaldassi** [comment]
This isn't limited to BitArrays, logical indexing simply isn't implemented for sparse matrices. I'll change the title accordingly.

**Comment by carlobaldassi** [comment]
Actually, only logical indexing by vectors isn't implemented.

**Comment by IainNZ** [comment]
Is it implemented for full matrices? Following that same code snippet from the question:

```julia
# v0.3.3
julia> A = [.1;.2;.3;.4;.11;.13;.14;.01;.04;.09];

julia> B = zeros(10,1);

julia> C = A .< .12;

julia> B[C] = 1;
ERROR: BoundsError()
 in assign_bool_scalar_1d! at array.jl:355
 in setindex! at array.jl:381
```

**Comment by carlobaldassi** [comment]
@IainNZ  you're right, logical indexing is only accepted when the shape of the mask matches that of the array.

The correct fix here seems to be throwing an error, as in the dense case.
