### ISSUE TITLE
julia-debug.exe segfaults during spawn test ever since #9266

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#10111]
cc @vtjnash see logs, and bisect results from win32 and win64 here: https://gist.github.com/tkelman/7e6aa9bf14d382ba5b65
(skips were build failures)

**Comment by tkelman** [comment]
Works fine without sys.dll, so maybe not too big an issue. Does make #10045 harder to debug locally.

**Comment by vtjnash** [comment]
that seems to be a non-sequitur. the debug build is supposed to ignore sys.dll, since loading it would cause errors. although, i do keep seeing warnings that seem to result from it having gotten loaded?

**Comment by ihnorton** [comment]
![ss1](https://cloud.githubusercontent.com/assets/327706/6315237/8d80d8e6-b9c9-11e4-8571-4a7944e13892.png)
oops...

**Comment by tkelman** [comment]
Thanks for the fix here @ihnorton. I'm guessing it would look a fair bit different on release-0.3. It might be okay as a wontfix there though, since I highly doubt we'll be shipping sys.dll with any 0.3 release.
