### ISSUE TITLE
Cannot use parameterized types in boot.jl

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#10114]
For #9297, I wanted to add a simple parameterized type to boot.jl:
```julia
immutable StringIndex{S}
    i::Int
end
```

It needs to live there because it's used in ascii.jl (though maybe we could find a workaround).

This leads to a segfault when calling `make`:
```
    JULIA usr/lib/julia/sys0.o
/bin/sh : ligne 1 : 12804 Erreur de segmentation  (core dumped)/home/milan/Dev/julia/usr/bin/julia -C native --build /home/milan/Dev/julia/usr/lib/julia/sys0 sysimg.jl
Makefile:151: recipe for target '/home/milan/Dev/julia/usr/lib/julia/sys0.o' failed
make[1]: *** [/home/milan/Dev/julia/usr/lib/julia/sys0.o] Error 139
Makefile:50: recipe for target 'release' failed
make: *** [release] Error 2
```

If I remove `{S}` then it works fine. Is that expected?

**Comment by vtjnash** [comment]
why does this need to go into `boot.jl`? the set of operations that are valid at that stage in bootstrapping is extremely limited. we also intentionally prevent some optimizations and method specializations done on types created that early, for a related reason

**Comment by nalimilan** [comment]
Indeed, looks like it isn't needed after all. I don't remember the details, but I think I had tried that and it failed. I must have been confused with another error.
