### ISSUE TITLE
length of unicode arrays on ARM is incorrectly computed

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10125]
This test should return true, but returns false on ARM.

````
julia> u8 = "\U1d565\U1d7f6\U00066\U2008a"
"𝕥𝟶f𠂊"

julia> collect(u8) == collect(utf16(u8))
false
````

**Comment by ViralBShah** [comment]
This seems to be the issue:

````
julia> collect(u8) 
13-element Array{Char,1}:
 '𝕥'      
 '𝟶'      
 'f'         
 '𠂊'      
 '\U96ad5240'
 '\U96ad5270'
 '\U96ad5280'
 '\U96a55320'
 '\U96ad5290'
 '\U96ad52a0'
 '\U94e50338'
 '\U96a55368'
 '\U96ad52b0'
````

**Comment by JeffBezanson** [comment]
I think I know what this is. `u8_strlen` in `src/support/utf8.c` assumes `char` is signed. It should just check the top bit instead. Is `char` unsigned in your arm compiler?

**Comment by ViralBShah** [comment]
`CHAR_MIN` is 0 - so I am guessing it is unsigned. `SCHAR_MIN` is -128.

I can make the default `char` be signed with the gcc option `-fsigned-char`.

**Comment by ViralBShah** [comment]
If I build with `-fsigned-char`, the unicode tests pass. I will see if this affects anything else (should not), and close when I commit a fix to ARM.inc.
