### ISSUE TITLE
Build SuiteSparse with CUDA support

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10122]
SuiteSparse has some CUDA accelerated solvers that work quite well. I am not sure how feasible it would be for us to build it with CUDA support for our default distributions. If so, I would love to have some way in the solvers to then dispatch to the CUDA version.

**Comment by ViralBShah** [comment]
Closing as dup of #8800.

**Comment by ViralBShah** [comment]
Even if the build issue is sorted out, I am not sure if the licensing of CUDA is compatible for us.

**Comment by andreasnoack** [comment]
I tried to build a CUDA library yesterday and it appears that they lack behind XCode so supporting this will probably be a huge pain.

**Comment by ViralBShah** [comment]
Presumably most CUDA users are on Linux or Windows.

**Comment by starrynight** [comment]
For what it is worth, I tried to manually edit the makefiles of Suitesparse and was able to generate dynamic linked libraries with CUDA solvers. Clumsy as it is, I'm not going to send pull requests. Those revised makefiles on in my github repository. Maybe it could help someone. The solvers can at least survive julia 0.4.1 `make test `

**Comment by ViralBShah** [comment]
Could you post the URL here?

**Comment by starrynight** [comment]
It can be found [here](https://github.com/starrynight/SuiteSparse). 

Prof. Davis has mentioned that the latest package will have built-in support to generate dynamic linked libraries. So everything should be fine now.
