### ISSUE TITLE
Allow to reduce over a dimension in sumabs2!

### ISSUE THREAD

**Issue by SuperFluffy** [JuliaLang/julia#10137]
`Base.sumabs2(A,d)` allows to reduce the matrix `A` over the specified dimension `d`. I want to reduce `A` in-place using `Base.sumabs2!(r,A)` into the `r` array/vector, but I cannot specifiy along which dimension I want to reduce.

For example, if `r` is `3x1`, and I want to reduce the `5x3` matrix `A`, I need to first transpose it before I can do so, because it looks like julia reduces along the major dimension.

Please change `Base.sumabs2!(r,A)` to `Base.sumabs2!(r,A,d)`, where `d` gives the dimension along which to reduce.

**Comment by andreasnoack** [comment]
The dimension is automatically inferred from the output arrays, e.g.
```julia
julia> sumabs2!(zeros(5), A) - sum(A.^2, 2)
5x1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0

julia> sumabs2!(zeros(1,4), A) - sum(A.^2, 1)
1x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
```

**Comment by SuperFluffy** [comment]
Not as far as I can see. In the example below, the arrays is clearly not reduces along columns.

````julia
julia> sumabs2!(zeros(3), rand(5,3))
ERROR: DimensionMismatch("Reduction on array of size (5,3) with output of size (3,)")
 in check_reducdims at reducedim.jl:151
 in _mapreducedim! at reducedim.jl:160
 in sum! at reducedim.jl:220
````

On the other hand:
````julia
julia> sumabs2!(zeros(3), transpose(rand(5,3)))
3-element Array{Float64,1}:
 0.682867
 1.52195 
 1.56914 
````

**Comment by andreasnoack** [comment]
When you reduce over columns, the result has size `(1,n)` so try
```julia
julia> sumabs2!(zeros(1,3), rand(5,3))
1x3 Array{Float64,2}:
 1.50468  1.84735  1.28677
```
