### ISSUE TITLE
Build fails on Ubuntu with BUILD_LLVM_CLANG=1 

### ISSUE THREAD

**Issue by jgoldfar** [JuliaLang/julia#10138]
BUILD_LLVM_CLANG is necessary (AFAIK) to use Clang.jl, which is super useful... But running `make` on the current master branch with
```
BUILD_LLVM_CLANG=1
```
in Make.user gives 
```
COMPILE:   clang_linux/msan-x86_64/x86_64: <snip>julia/deps/llvm-3.3/projects/compiler-rt/lib/msan/msan_linux.cc
<snip>julia/deps/llvm-3.3/projects/compiler-rt/lib/msan/msan_linux.cc:20:10: fatal error: 
      'algorithm' file not found
#include <algorithm>
```
Definitely looks like a LLVM issue, but the build from source in the 0.3 release branch work(ed) fine recently.

**Comment by ViralBShah** [comment]
Cc: @ihnorton

**Comment by ihnorton** [comment]
What is your gcc version?

**Comment by jgoldfar** [comment]
`gcc --version`: `gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2`

**Comment by tkelman** [comment]
Is this ubuntu 14.04? I have the exact same gcc version and `BUILD_LLVM_CLANG = 1` works for me.  It looks like you're missing some standard C++ headers, maybe reinstall `build-essential` just to be sure?

**Comment by jgoldfar** [comment]
Well, not a julia build issue at all; that fixes it. What a bizarre thing to go missing between building 0.3 and master. Thanks for your help!
