### ISSUE TITLE
Hashing SparseMatrixCSC is slow

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10160]
```julia
julia> @time hash(spzeros(50000, 5000))
elapsed time: 2.504496532 seconds (39 kB allocated)
```

We could hash SparseMatrixCSCs by colptr/rowval/nzval, but that would have implications for equality. @StefanKarpinski, is there anything we can do here? Ref #5778

**Comment by StefanKarpinski** [comment]
One option would be to arrange hash arrays by sequentially hashing their `(i,j,v)` tuples for non-zero entries. That would make sparse array hashing `O(nz)`; you'd want to skip over tuples where `v` is zero.

**Comment by StefanKarpinski** [comment]
You'd want to hash the dimensions in there too somehow, maybe by starting with `hash(size(a))`.

**Comment by simonster** [comment]
Hashing `(i,j,v)` tuples for dense arrays would presumably require doing ~3x as much work per element. Maybe we could first call `countnz` to determine density, and then either hash as we do now if density is >~1/3 or hash `(i,j,v)` tuples otherwise? It looks like `countnz` takes ~15% as long as `hash`, so the performance impact for dense arrays shouldn't be too bad.

**Comment by StefanKarpinski** [comment]
Yeah, it's not great, but it's the first thing that occured to me to solve this problem. Another option would be to hash `(i - j) $ v` for non-zero `v` or something like that, but it's awfully easy to force collisions.

**Comment by simonster** [comment]
I guess we wouldn't actually have to count all the zeros to pick whether to use dense or sparse hashing. If we fix the density tradeoff at say 1/10 and the array is completely non-zero, we only need to check the first 1/10 elements, so the performance impact should only be a little over 1%.

We could also potentially handle runs of zeros (or any element?) by hashing the value and the length of the run instead of hashing each value.

**Comment by StefanKarpinski** [comment]
Oh, that's a pretty good solution. Maybe hashing the run-length-encoding of the array in linear indexing order is the way to go. I like how general that is...

**Comment by StefanKarpinski** [comment]
Of course the down side of hashing the run-length-encoding is that if there are no repeats ever then you do twice as much work as just hashing values.
