### ISSUE TITLE
Remove `Collections` from Base?

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#10166]
Following on from the removal of the Graphics module from Base, the Collections module doesn't seem to belong there either, and (as far as I can tell) is not used elsewhere in Base. I propose that the (nice) functionality be moved to the DataStructures package.

On a related note, in PriorityQueue, I suggest that enqueue! and dequeue! be renamed to push! and pop! for consistency, and that pop! should return not only the value associated with the first key, but also the key itself, in a tuple. (Currently, if the key is needed, it must currently be duplicated inside the value!)

**Comment by timholy** [comment]
If it's not used elsewhere in base, moving it to a package seems reasonable. But I'd personally vote to wait for more code-ejections until package precompilation has arrived.

> Currently, if the key is needed, it must currently be duplicated inside the value!

Or you can use `peek`.

**Comment by kmsquire** [comment]
> ...but also the key itself, in a tuple.

How about as a `Pair`?

**Comment by jakebolewski** [comment]
Collections is not really used anywhere in base so +1 on removing it.  It is used in only a few packages so I feel the impact of this change won't be very big.

**Comment by ViralBShah** [comment]
Perhaps the ejections will speed the work on precompilation. :-)

**Comment by jakebolewski** [comment]
The binary heap methods for `AbstractArray`'s defined in the `Collections` module are used in `quadgk.jl`.  The only piece of functionality not used in `Base` is the `PriorityQueue` type and associated methods.

**Comment by garborg** [comment]
Saw [this question](https://github.com/JuliaLang/Graphs.jl/pull/169#issuecomment-74267437) about supporting both 0.3 and 0.4 PriorityQueue constructor syntax in Graphs.jl, and am curious whether to add something to Compat, or if there are other thoughts.

**Comment by timholy** [comment]
Adding something to Compat seems best to me.

**Comment by lobingera** [comment]
Could it be this leaves combinations of Winston+Gtk in an undefined state?

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7-pre+1 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d15f183* (3 days old release-0.3)
|__/                   |  x86_64-linux-gnu

julia> using Winston

** (julia:5323): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-oH4HPTdUFc: Connection refused

julia> plot(rand(10,1),rand(10,1))

julia> ERROR: `getgc` has no method matching getgc(::GtkCanvas)
 in anonymous at /home/lobi/.julia/v0.3/Winston/src/gtk.jl:16
 in draw at /home/lobi/.julia/v0.3/Gtk/src/cairo.jl:65
 in notify_resize at /home/lobi/.julia/v0.3/Gtk/src/cairo.jl:43

julia> ^C

lobi@orange4:~/.julia/v0.3/Gtk$ git status
HEAD detached at v0.7.10
lobi@orange4:~/.julia/v0.3/Winston$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/Winston.ini

```

```

**Comment by timholy** [comment]
Can you explain why you think that bug is related to the issue here?

**Comment by lobingera** [comment]
afair getgc was in Base.graphics, and now i see a getgc missing?

**Comment by timholy** [comment]
Ah, this issue is actually about Base.Collections, not Base.Graphics. But yes, the issues you're seeing are due to the removal of Base.Graphics.

**Comment by lobingera** [comment]
note to myself: learn to operate the search function in github correctly...

**Comment by timholy** [comment]
It's harder to search these issues than it seems like it should be.

**Comment by tknopp** [comment]
@lobingera your error is from 0.3 julia. `Base.graphics` was removed from master (0.4). I hope that this has not been backported...

**Comment by lobingera** [comment]
@tknopp unfortunately this seems to be the case, i'm back at a 0.3.6 julia and some local changes.
@timholy i searched for 'graphics' and this is one of the first words here, i expected the search to be limited in the first place to title

**Comment by tknopp** [comment]
@lobingera: No I have checked and `Base.graphics` has not been removed from the `0.3` branch. However, if you are on master of Gtk.jl it could be the following line: 

https://github.com/JuliaLang/Gtk.jl/commit/9692314cd8fcab4aea9c03292ff23103f3da0f39#diff-04c6e90faac2675aa89e2176d2eec7d8R353

But I am not 100% sure.

**Comment by tkelman** [comment]
Most of the packages were immediately transitioned to depending on the new Graphics.jl package, which isn't properly working as a no-op stub for 0.3 yet last I checked.

**Comment by jakebolewski** [comment]
The Graphics package needs to be split up.  Having the same name as the 0.3 module was a mistake.

**Comment by dpsanders** [comment]
Apparently `PriorityQueue` has now been copied over to `DataStructures.jl`, but not yet removed from Base. cc @ararslan

**Comment by ararslan** [comment]
It's removed but not _removed_ removed.
```
julia> Collections.PriorityQueue(1)
ERROR: Base.Collections.PriorityQueue(1,) has been moved to the package DataStructures.jl.
Run Pkg.add("DataStructures") to install DataStructures on Julia v0.6 and later, and then run `using DataStructures`.
Stacktrace:
 [1] #PriorityQueue#1(::Array{Any,1}, ::Function, ::Int64, ::Vararg{Int64,N} where N) at ./deprecated.jl:699
 [2] PriorityQueue(::Int64, ::Vararg{Int64,N} where N) at ./deprecated.jl:699
```
We can probably delete the deprecation now in the 0.7 cycle.

**Comment by StefanKarpinski** [comment]
> We can probably delete the deprecation now in the 0.7 cycle.

Yes, plz!
