### ISSUE TITLE
Indexing and assigning at once

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#10186]
The following code shouldn't work?

```julia
julia> a=[3,2,1]
3-element Array{Int64,1}:
 3
 2
 1

julia> a[a]=[4:6]
WARNING: [a] concatenation is deprecated; use [a;] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
 in vect at abstractarray.jl:29
ERROR: BoundsError: attempt to access 3-element Array{Int64,1}:
 3
 5
 4
  at index [4]
 in setindex! at array.jl:377
```

**Comment by tkelman** [comment]
Maybe `setindex!` could do a sanity check that you aren't trying to use the same array for both the indices and the values to write into? `a[copy(a)] = [4,5,6]` works just fine, but I'd rather either error for `setindex!(A, X, inds)` when `A === inds`, or mark this as wontfix if that check would be too expensive.

**Comment by JeffBezanson** [comment]
At array.jl:382 this was already fixed if A === the RHS, but not for A === inds. I guess we should check that too.
