### ISSUE TITLE
Change to IO between 0.3.3 and 0.3.5/master causing failures

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#10182]
The following code from @Keno's GnuTLS.jl has stopped working between 0.3.3 and 0.3.5:

```julia
using GnuTLS

sess = GnuTLS.Session()
set_priority_string!(sess)
set_credentials!(sess,GnuTLS.CertificateStore())
associate_stream(sess,connect("github.com",443))
handshake!(sess)
write(sess,"GET / HTTP/1.1\r\n\r\n")
print(readall(sess))
```

and I don't understand why it would have. Does anyone know what changed that might have affected this? There is possibility that this is coincidence, and that the change is actually at GitHub's end.

CC: @sbromberger

**Comment by sbromberger** [comment]
If a TLS stream is just shut down, my guess is that we get something other than `EOFError`. In fact:

```
julia> associate_stream(sess,connect("www.github.com",443))

julia> isopen(sess)
true

julia> write(sess,"GET / HTTP/1.1\r\n\r\n")
18

julia> z = readall(sess)
ERROR: GnuTLS Exception: GNUTLS_E_PREMATURE_TERMINATION(-110): The TLS connection was non-properly terminated.
 in readtobuf at /Users/seth/.julia/v0.4/GnuTLS/src/GnuTLS.jl:376
 in readall at /Users/seth/.julia/v0.4/GnuTLS/src/GnuTLS.jl:389

julia> isopen(sess)
false
```

**Comment by IainNZ** [comment]
I just compiled 0.3.3, and it works:

```julia
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-unknown-linux-gnu

julia> using Requests

julia> Requests.get("https://api.github.com/users/octocat/orgs")
Response(200 OK, 27 Headers, 2 Bytes in Body)
```

```julia
  | | |_| | | | (_| |  |  Version 0.3.5 (2015-01-08 22:33 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-unknown-linux-gnu

julia> using Requests

julia> Requests.get("https://api.github.com/users/octocat/orgs")
ERROR: stream is closed or unusable
 in check_open at stream.jl:294
 in write at stream.jl:730
```

**Comment by sbromberger** [comment]
Possibly related: https://github.com/JuliaWeb/Requests.jl/issues/30

**Comment by sbromberger** [comment]
Also, I think this may involve the version of the  installed, as on my linux dev box (Julia 0.3.5), I get

```
julia> associate_stream(sess,connect("github.com",443))

julia> write(sess,"GET / HTTP/1.1\r\n\r\n")
18

julia> z = readall(sess)
ERROR: GnuTLS Exception: GNUTLS_E_UNEXPECTED_PACKET_LENGTH(-9): A TLS packet with unexpected length was received.
 in readtobuf at /home/seth/.julia/v0.3/GnuTLS/src/GnuTLS.jl:376
 in readall at /home/seth/.julia/v0.3/GnuTLS/src/GnuTLS.jl:389
```

See https://github.com/JuliaWeb/GnuTLS.jl/blob/e236cf30901e330b4644b69235011e67182018be/src/GnuTLS.jl#l51-62 for my reasoning.

**Comment by IainNZ** [comment]
I did a `git bisect

**Comment by IainNZ** [comment]
Seems to happen ~50% of time (I got failures 28/50 times)

```julia
using GnuTLS

fails = 0
tries = 50
for i in 1:tries
    println("> Creating session")
    sess = GnuTLS.Session()
    println("> Setting priority string")
    set_priority_string!(sess)
    println("> Setting set_credentials")
    set_credentials!(sess,GnuTLS.CertificateStore())
    println("> Creating socket")
    sock = connect("github.com",443)
    println("> Assocating session with socket")
    associate_stream(sess,sock)
    println("> Perfoming handshake")
    handshake!(sess)
    println("> Writing to session")
    write(sess,"GET / HTTP/1.1\r\n\r\n")
    try
        println("> Reading response")
        print(readall(sess))
    catch
        fails += 1
    end
    sleep(1)
end
@show fails
@show fails/tries*100
```

**Comment by vtjnash** [comment]
@keno I don't think reads are supposed to check if the stream is open. They
should throw an EOF error if there is no more data

**Comment by IainNZ** [comment]
If I put a `@show e` in GnuTLS.jl after the `catch` in close, I get
`e => ErrorException("stream is closed or unusable")`
before, #8050, maybe this would have thrown an `EOFError`?

**Comment by IainNZ** [comment]
Ah thats not right, it doesn't throw any error at 0.3.3

**Comment by IainNZ** [comment]
i.e.
`if !isa(e,EOFError) && !(isa(e,ErrorException) && e.msg=="stream is closed or unusable")`

**Comment by IainNZ** [comment]
Adding that allowed me to run PkgEval, so until someone figures out a better solution I'm going to tag GnuTLS.jl with it.

**Comment by sbromberger** [comment]
Thanks @IainNZ - we'll definitely want a better solution, though. Checking a error string to determine what to do seems pretty fragile.

**Comment by sbromberger** [comment]
Ignore my previous tests - I forgot the handshake!().

**Comment by sbromberger** [comment]
I think we may have fixed this in the ird/tempfix branch of GnuTLS. Needs more eyes.

**Comment by sbromberger** [comment]
Pretty sure we've fixed this. On 0.4:
```
julia> @show fails
fails = 0
0
```

On 0.3:
```
julia> @show fails
fails => 0
0
```

**Comment by IainNZ** [comment]
Yes indeed
