### ISSUE TITLE
Julia Users report of segfault with HTTPServer.jl

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#10192]
https://groups.google.com/forum/?fromgroups=#!topic/julia-users/2a26Fwu3Fwc

I have posted an issue at the HTTPServer.jl repo, but figured a segfault would be of interest here too.

**Comment by ihnorton** [comment]
Can't reproduce with either 0.3.4 or master.

cc @nalimilan

**Comment by ihnorton** [comment]
https://github.com/JuliaWeb/Morsel.jl/issues/33
https://github.com/JuliaWeb/HttpServer.jl/issues/46

**Comment by ihnorton** [comment]
Reported as fixed, was caused by library issue.
