### ISSUE TITLE
Debian Install of Julia Results in LinAlg Error

### ISSUE THREAD

**Issue by Carthalo** [JuliaLang/julia#10190]
Hello,

My OS is Debian Wheezy. I installed Julia from unstable distribution sid. Install did not result in anything obviously wrong.

Expected Behavior:

Type in the command 'julia' to the gnome terminal resulting in invoking the julia interactive session without any errors or warnings.

What happened:
```bash
$ julia
Warning: error initializing module LinAlg:
ErrorException("ccall: could not find function openblas_get_config in library libblas")
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.2
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  i586-linux-gnu


>julia
```
-----
information on the julia install:
```bash
$ apt-cache showpkg julia
Package: julia
Versions: 
0.3.2-1 (/var/lib/apt/lists/ftp.us.debian.org_debian_dists_sid_main_binary-i386_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ftp.us.debian.org_debian_dists_sid_main_binary-i386_Packages
                  MD5: 7dde6bdfecf283488c90d2886fb982c1
 Description Language: en
                 File: /var/lib/apt/lists/ftp.us.debian.org_debian_dists_sid_main_i18n_Translation-en
                  MD5: 7dde6bdfecf283488c90d2886fb982c1


Reverse Depends: 
  julia-factcheck,julia
  julia-doc,julia
  julia-dbg,julia 0.3.2-1
  science-numericalcomputation,julia
  science-mathematics,julia
  science-economics,julia
Dependencies: 
0.3.2-1 - libamd2.3.1 (0 (null)) libc6 (2 2.11) libcamd2.3.1 (0 (null)) libcholmod2.1.2 (0 (null)) libcolamd2.8.0 (0 (null)) libdouble-conversion1 (0 (null)) libgcc1 (2 1:4.1.1) libllvm3.5 (0 (null)) libspqr1.3.1 (0 (null)) libstdc++6 (2 4.9) libumfpack5.6.2 (0 (null)) libunwind8 (0 (null)) libopenblas-base (16 (null)) libblas.so.3 (0 (null)) libopenblas-base (18 0.2.10-1~) liblapack.so.3 (0 (null)) libpcre3 (0 (null)) libfftw3-double3 (0 (null)) libfftw3-single3 (0 (null)) libgmp10 (0 (null)) libarpack2 (0 (null)) libmpfr4 (0 (null)) libopenlibm1 (0 (null)) libopenspecfun1 (0 (null)) multiarch-support (0 (null)) julia-doc (0 (null)) ess (2 12.09-1~) git (0 (null)) libopenblas-base (0 (null)) 
Provides: 
0.3.2-1 - 
Reverse Provides: 
```
and system information:

```bash
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
```
-----
So, I did get into the interactive session but those errors appear every time.Question:
A. What will those errors do to my ability to code using Julia?
B. Does anyone know how to fix this error?
C. Do you need any more information to prescribe a fix?

Any help would be greatly appreciated, thank you for your time.

--  Carthalo

**Comment by tkelman** [comment]
You should install the openblas package. What does `versioninfo()` say?

I suspect this is a packaging bug. If the Debian package for Julia was built using openblas at build time, then it needs a hard dependency on openblas at runtime. We could maybe handle having alternatives switching blas implementations on us (or building with openblas, but using reference blas at runtime like in your case) but it would require at least rebuilding the system image, to fix `blas_vendor` and other things.

**Comment by Carthalo** [comment]
Hi tkelman,

This is the output of versioninfo():
```julia
julia> versioninfo()
Julia Version 0.3.2
Platform Info:
  System: Linux (i586-linux-gnu)
  CPU: Intel(R) Atom(TM) CPU N455   @ 1.66GHz
  WORD_SIZE: 32
ERROR: ccall: could not find function openblas_get_config in library libblas
 in versioninfo at ./interactiveutil.jl:177
 in versioninfo at ./interactiveutil.jl:147

```

**Comment by tkelman** [comment]
Oh, right, that's not so useful. Nevermind then.

It looks like the debian package has dependencies on both `libopenblas-base` and `libblas.so.3`. I'm not sure which package you need to install to get update-alternatives to make libblas a symlink to openblas instead of reference blas. Who maintains the debian package?

With this error happening, a lot of linear algebra functionality won't be hooked up properly, since Julia was configured to expect a different library than it's currently using on your machine.

**Comment by sjkelly** [comment]
cc @sebastien-villemot

**Comment by Carthalo** [comment]
Maybe that's the issue...I have both installed. Julia on sid is found: https://packages.debian.org/sid/julia

According to the page regarding openblas dependencies:

> dep: libopenblas-base
> Optimized BLAS (linear algebra) library based on GotoBLAS2
>
> or libblas.so.3
> virtual package provided by libatlas3-base, libblas3, libopenblas-base
>
> dep: libopenblas-base (>= 0.2.10-1~)
> Optimized BLAS (linear algebra) library based on GotoBLAS2
>
> or liblapack.so.3
> virtual package provided by libatlas3-base, liblapack3, libopenblas-base

They also listed as recommended:

> rec: libopenblas-base
> Optimized BLAS (linear algebra) library based on GotoBLAS2

Should I try removing one or the other?

**Comment by Carthalo** [comment]
Just this one possible clue perhaps can help:
```bash
$ apt-cache depends julia
julia
  Depends: libamd2.3.1
  Depends: libc6
  Depends: libcamd2.3.1
  Depends: libcholmod2.1.2
  Depends: libcolamd2.8.0
  Depends: libdouble-conversion1
  Depends: libgcc1
  Depends: libllvm3.5
  Depends: libspqr1.3.1
  Depends: libstdc++6
  Depends: libumfpack5.6.2
  Depends: libunwind8
 |Depends: libopenblas-base
  Depends: <libblas.so.3>
    libatlas3-base
    libblas3
    libopenblas-base
 |Depends: libopenblas-base
  Depends: <liblapack.so.3>
    libatlas3-base
    liblapack3
    libopenblas-base
  Depends: libpcre3
  Depends: libfftw3-double3
  Depends: libfftw3-single3
  Depends: libgmp10
  Depends: libarpack2
  Depends: libmpfr4
  Depends: libopenlibm1
  Depends: libopenspecfun1
  PreDepends: multiarch-support
  Suggests: julia-doc
  Suggests: ess
  Recommends: git
  Recommends: libopenblas-base
```

Why does it list libopenblas-base twice?

**Comment by tkelman** [comment]
Probably once for libblas, and once for liblapack. I'm really not sure how openblas or Julia are packaged in Debian, we'll need the maintainer to chime in. I think there's also a `libopenblas-dev` package which might do something here? What does `ls -al /etc/alternatives/libblas*` say?

**Comment by sebastien-villemot** [comment]
@Carthalo Mixing packages from Debian Wheezy and Sid is not supported. I suggest that you upgrade to Debian Jessie (the upcoming release, which includes Julia 0.3.2). If you still have issues with the Debian package, then please file a bug in the Debian Bug Tracking System (see https://www.debian.org/Bugs/Reporting)

**Comment by sebastien-villemot** [comment]
@Carthalo I forgot to say that, if you do not want to upgrade to Debian Jessie and want to stay under Debian Wheezy, then I recommend you to compile Julia from source instead of trying to use a package from another release.

**Comment by tkelman** [comment]
Or if you're in a hurry you can use the generic linux binaries from http://julialang.org/downloads/ which should work on virtually any distribution and don't need to interact with the system package manager at all.

**Comment by tkelman** [comment]
@sebastien-villemot thanks for your input here. Would it be disruptive to make the dependency on openblas more explicit for the Debian package? There's nothing sacred about the libblas name for us, what's more important is that we know which blas implementation we're using and it doesn't change out from under a compiled system image. And given the lead time it'll take before any potential new open-source blas implementations may make their way into Debian and have people start wanting to use them with Julia, I think the predictability would be good.

**Comment by sebastien-villemot** [comment]
@tkelman I'm sorry but I don't understand your request. The Julia package works with the 3 BLAS implementations (OpenBLAS, ATLAS, Netlib BLAS). The OpenBLAS one is the recommended one, but is not required by any means. See https://wiki.debian.org/DebianScience/LinearAlgebraLibraries for more on BLAS/LAPACK implementations on Debian.

**Comment by tkelman** [comment]
> The Julia package works with the 3 BLAS implementations (OpenBLAS, ATLAS, Netlib BLAS).

Are you sure about that? I believe, if the package is compiled with one implementation at build-time, then a user tries to change the blas implementation via update-alternatives, the Julia package will no longer function correctly. Aspects of how we bind to blas and lapack functions, especially controlling multithreading which differs significantly between different implementations, gets hard-coded into the Julia system image at build time. While it might be possible to regenerate the system image to re-bind some of these, that's time-consuming and not straightforward.

**Comment by sebastien-villemot** [comment]
@tkelman I admit I haven't tested since Julia 0.1 or 0.2 that the package works with the 3 BLAS implementations. I will check with Julia 0.3 and the new system image. If needed, I will add a hard dependency on OpenBLAS.

**Comment by sebastien-villemot** [comment]
@tkelman I made a few tests after switching the BLAS implementaiton with `update-alternatives`, and Julia seems to work fine. At least I was able to do some linear algebra without problems. If you know about a specific functionality that you think should break, just let me know.

**Comment by tkelman** [comment]
Hm, thanks for checking. Good to hear, but I'm a bit surprised. How about `Base.runtests(["linalg", "blas"])` ?

**Comment by sebastien-villemot** [comment]
The result is mixed: as long as the OpenBLAS package is on the system, all tests pass when I change the BLAS implementation. But if I remove the OpenBLAS package, then the `linalg` tests pass but the `blas` test fails.

So essentially I think you are right, but the mecanism is still a bit obscure to me. I guess that I will simply hardcode the OpenBLAS dependency, even though I dislike it because it means less freedom of choice for the users…

**Comment by tkelman** [comment]
If the choices are between Netlib, Atlas, and OpenBLAS at the moment, it makes everyone's life a little easier to just say OpenBLAS is the officially endorsed choice right now. We can support others implementations for compilation from source, but making things hot-swappable in a binary installation is more complicated. We have some issues open for it I believe.

**Comment by Carthalo** [comment]
Thank you tkelman and sebastian for your help. I will look into either upgrading to Jessie or compile from source using generic linux binaries. Excellent work gentlemen.
