### ISSUE TITLE
sparse matrix printing as dense

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10197]
I don't know when this happened, but show on sparse matrices gives the dense output. The sparse `showarray` is not getting called.

````
julia> speye(5)
5x5 Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0
````

**Comment by tkelman** [comment]
Could bisect if necessary, but I have a sneaky feeling it was from the module move.
