### ISSUE TITLE
cat-error in constructing Array-of-Arrays

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10204]
```julia
julia> Array{Int,1}[[1] [3];
                    [2] [4]]
ERROR: MethodError: `convert` has no method matching convert(::Type{Array{Int64,1}}, ::Int64)
This may have arisen from a call to the constructor Array{Int64,1}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{Array{T,1}}, ::Range{T})
  convert{S,T,N}(::Type{Array{S,N}}, ::SubArray{T,N,D<:DArray{T,N,A},I<:(Union(Colon,Range{Int64},Array{Int64,1},Int64)...,),LD})
  convert{T,S,N}(::Type{Array{T,N}}, ::SubArray{S,N,P<:AbstractArray{T,N},I<:(Union(Colon,Range{Int64},Array{Int64,1},Int64)...,),LD})
  ...

 in anonymous at multidimensional.jl:269
 in cat_t at abstractarray.jl:737
 in typed_vcat at abstractarray.jl:758
 in typed_hvcat at abstractarray.jl:891
```

**Comment by timholy** [comment]
CC @Jutho

**Comment by Jutho** [comment]
That's indeed good to take into account in the cat redesign. I think I know how I can easily deal with this. However, I have not yet been able to fix the test error.

**Comment by JeffBezanson** [comment]
This is the expected new behavior. Spaces and semicolons always concatenate, and the type in front specifies the element type:

```
julia> Float32[[1] [3];
               [2] [4]]
2x2 Array{Float32,2}:
 1.0  3.0
 2.0  4.0
```

**Comment by timholy** [comment]
OK, so if you want to create an array of arrays, just stuff them in manually?

**Comment by Jutho** [comment]
@JeffBezanson , did you notice that in the example of @timholy the elementtype was specified as `Array{Int,1}`. Does this mean that you can specify any element type, except for members of the `AbstractArray` hierarchy? So indeed, like Tim was asking, if you want to create an Array of Arrays, you cannot use cat? I am certainly ok with that, as it makes the `(h)(v)cat` code easier, but it would also be possible otherwise.

**Comment by JeffBezanson** [comment]
That's right. It is a bit odd though. Maybe better to get rid of the typed
cat syntax.

**Comment by StefanKarpinski** [comment]
> Maybe better to get rid of the typed cat syntax.

+1 – I've always been a little uncomfortable with this, although I did start it all by adding methods for indexing into types that produce arrays of that element type.
