### ISSUE TITLE
Linux tarball name change

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#10202]
The linux 32-bit distribution tarball has recently changed names from linux-i386 to linux-i686.  I'm not against this, but it does mean we'll have to update travis auto download links and such.  Thoughts?  @tkelman

**Comment by tkelman** [comment]
What's with the passive tense? https://github.com/staticfloat/julia-buildbot/commit/cf3167ff4cf3d1a0d6a14b6cd31b1935168ad24a

Have you or are you planning on changing any of the status.julialang.org links? Travis doesn't use the 32 bit binaries.

Might just need to make sure the link to julia-0.3-latest-linux-i386.tar.gz is updated when we upload the next release.

**Comment by tkelman** [comment]
If the status.julialang.org links are going to change with this, then I think the only thing that needs updating is https://github.com/JuliaLang/julialang.github.com/blob/master/install-julia.sh - which might still be used on Travis by a handful of packages that haven't switched over to `language: julia` yet, but again 32 bit is not tested on Travis.

**Comment by staticfloat** [comment]
That commit on julia-buildbot was because I noticed the 32-bit builder was failing due to there no longer being a `julia-*i386.tar.gz` file after running `make dist` anymore.  That commit was in reaction to something else that happened 13 days ago, but I haven't been able to find what exactly caused it.  I'm a little stumped, because you can clearly see the buildbot's logs change:

[Building an `-i386.tar.gz` file](http://buildbot.e.ip.saba.us:8010/builders/package_tarball32/builds/278/steps/make/logs/stdio)

[Building an `-i686.tar.gz` file](http://buildbot.e.ip.saba.us:8010/builders/package_tarball32/builds/280/steps/make/logs/stdio)

Unfortunately, I had the buildbots off for a while while we were investigating the 32-bit complex test failures, but going through [the diff between those two commits](https://github.com/JuliaLang/julia/compare/820aabeec6369a4d40a1b0c6cb5278b4b89503ce...2738d12639c) didn't bring up anything suspicious to me.

Whatever, I'm not going to worry too much about it.  It's also possible something changed in the buildbot itself, although I'm not sure what it could have been.

**Comment by staticfloat** [comment]
Okay, immediately after posting that, I remembered that I changed compilers recently to using my own self-built gcc.  I feel like a giant noob now.

**Comment by tkelman** [comment]
Whoa, okay, interesting consequences from `gcc -dumpmachine` being different. My own fault then.

**Comment by tkelman** [comment]
So we've potentially traded the problem of not working on systems with really old software for not working on systems with really old hardware... but considering how many other issues we have with pre-SSE2 32-bit instruction sets I'll say this might not be a big deal.

**Comment by staticfloat** [comment]
In conclusion, let's just call it `-i686` and change `install-julia.sh`.

**Comment by staticfloat** [comment]
I don't think our "i386" builds have actually been i386 for a while now.  They've all included SSE2 instructions since summer, I believe.

**Comment by tkelman** [comment]
yeah that too

**Comment by staticfloat** [comment]
Okay, I think I've finished renaming everything.  status.julialang.org
links and julialang.org/download links should be consistent with everything
now.
-E
