### ISSUE TITLE
CXXFLAGS not used in src/ and ui/

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#10212]
I noticed that `CXXFLAGS` has no effect when building C++ files under `src/` and `ui/` (at least). For example in the following log, the Fedora standard `CXXFLAGS` that are set when calling `make` are not used at all for the last calls to `g++` that fail (at the bottom of the file):

https://gist.github.com/nalimilan/4cf029bcfec741015019

(Noticed when trying to add `std=c++11` for https://github.com/JuliaLang/julia/issues/10201)

**Comment by nalimilan** [comment]
Got it, these are the cases where `g++` is used as the C++ linker. I'm not sure what kind of flags we should pass: is `LDFLAGS` appropriate? Also, I wonder whether `-O3` has any effect for the linker (I'm supposed to override it with the Fedora default I use for `CFLAGS`, which is typically `-O2`).

**Comment by stevengj** [comment]
Normally, if you use `$(CXX)` for the linker, you should pass `$(CXX) $(CPPFLAGS) $(CXXFLAGS) ...objects... $(LDFLAGS) $(LIBS)`.  That is what e.g. automake does.

**Comment by nalimilan** [comment]
@stevengj Something like this? https://github.com/JuliaLang/julia/pull/10758

**Comment by stevengj** [comment]
Looks good.
