### ISSUE TITLE
Invalid read in `sgemm_kernel_SANDYBRIDGE` under valgrind

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10217]
I'm getting an `Invalid read of size 16` in `sgemm_kernel_SANDYBRIDGE` when I do a matrix-matrix multiplication on `Float32` matrices.  All other data types seem to be fine.  (This may turn out to be an OpenBLAS issue, but I'll start by filing it here.)

The minimal test script:

```
a = rand(Float32, 10, 10)
a * a
```

invoked as follows:

```
valgrind --smc-check=all-non-file --suppressions=$PWD/contrib/valgrind-julia.supp ./julia sgemm_minimal.jl
```

My `versioninfo()`:

```
Julia Version 0.4.0-dev+3387
Commit 20a2369* (2015-02-16 23:40 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by garrison** [comment]
I should also mention: I compiled with memory pools disabled (`-DMEMDEBUG -DMEMDEBUG2`), so that may be necessary to get the `Invalid read` warning to appear.

**Comment by ViralBShah** [comment]
Cc: @xianyi

**Comment by xianyi** [comment]
@garrison , Thank you for the report.

Because your CPU is haswell, I think OpenBLAS should call sgemm_kernel_HASWELL kernel.

**Comment by pao** [comment]
Could that happen if OpenBLAS is built with dynamic CPU detection running under a version of Valgrind which doesn't support Haswell instructions (pre-3.9.0, it looks like)?

**Comment by garrison** [comment]
I am using Valgrind 3.10.0, but I expected the same thing as @pao mentioned -- that the CPU is being detected wrong under Valgrind.

**Comment by xianyi** [comment]
@garrison , I need to check the source code. In general, the OpenBLAS kernel uses the loop as following.

```
//setup the pipeline
load 0 iteration data;

//main loop
//usually unrolled
for (...) {
compute current (n);
load next (n+1) iteration data;     // <--- May read the invalid data
}

//handle the tail for unrolled main loop
...
```

**Comment by garrison** [comment]
@xianyi If it turns out there is no simple way to prevent it from reading the invalid data (assuming the read is harmless), we can always suppress this specific error by adding an entry to `contrib/valgrind-julia.supp`.

**Comment by tkelman** [comment]
I just started getting a segfault in the linalg1 test in this same function - win64, i7-2630QM

**Comment by garrison** [comment]
In case anyone else is interested, here is a suppression that works:

    {
       sgemm_kernel_SANDYBRIDGE invalid read
       Memcheck:Addr16
       fun:sgemm_kernel_SANDYBRIDGE
    }

**Comment by ViralBShah** [comment]
@xianyi should we file this as an openblas issue?

**Comment by xianyi** [comment]
@ViralBShah ， dose it cause segfault?

**Comment by garrison** [comment]
In *practice*, I know of no actual segfaults related to this warning, other than potentially the one @tkelman mentioned (do you have any more information on that, Tony?).  In *principle*, however, I would (naively) think that an invalid read always has the potential to cause a segfault (and when it does not, then it is due to the specific layout of the process in memory).  But my thinking here should be taken with a huge grain of salt, as it is based on a very incomplete mental model of how these things work.  So if we do think this might be worth "fixing" with anything other than a suppression, it would be best to ask somebody with more knowledge first.

**Comment by tkelman** [comment]
Must've been rare or intermittent, I'll see if I can reproduce it. We've upgraded openblas versions since then.

**Comment by KristofferC** [comment]
Please comment if this can still be reproduced.
