### ISSUE TITLE
Optimize closure and newvar storage

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#10224]
As nobody found a good reason why let blocks generate non optimal code, I consider this as a bug.
Excerpt from julia-users:

> I was trying to find out, what the best way is to have some local, constant storage for a function, which is only accessible from inside the function. I was quite surprised, that you can't do this efficiently.
> Or at least I didn't find a way, or tested it incorrectly.
> Here are the different combinations I tried and the emitted native code:
> https://gist.github.com/SimonDanisch/e4bed0a16bdd847a8c2b#file-local_function_storage-jl
> test11 && test12 seems to be what julia does internally for test1-test4 (and the example here)
> It's especially odd, as a global const seems to be faster than a local const, even though that the local version is more restricted. Is this because there has been more time spend on making globals fast?

thread: [Julia-Users](https://groups.google.com/forum/#!searchin/julia-users/local$20function/julia-users/_vy-9bhgH2g/isAQSWM3HX8J)

Tested on:

``` Julia
Julia Version 0.4.0-dev+3227
Commit 242c357* (2015-02-09 11:34 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

And

``` Julia
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by simonster** [comment]
Related to #7953

**Comment by vtjnash** [comment]
it looks like #13412 made this worse (by splicing a lot of unnecessary `Box` variables into the AST)?

**Comment by JeffBezanson** [comment]
I believe this particular code pattern is fixed.

**Comment by JeffBezanson** [comment]
See also #15276
