### ISSUE TITLE
remove separate _mstr macro feature?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#10228]
There are now several `_str` macros with corresponding `_mstr` versions, which are identical except that they call `Base.triplequoted` first. I think this equivalence should be built in: for triple quoted strings, do the unindenting, then call the plain `_str` macro.

Needing to write two identical versions of every string macro is annoying. Even worse, the two versions might be utterly different, including not doing the expected unindenting, which seems to be a mere obfuscation-enabler.

**Comment by ivarne** [comment]
+:100: I've been meaning to suggest this for a long time, but wanted to understand the reasoning behind the current behaviour first.

**Comment by StefanKarpinski** [comment]
Yes.

**Comment by stevengj** [comment]
+1
