### ISSUE TITLE
Standardized Array tests/benchmarks

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#10223]
While working on [AbstractGPUArrays](https://github.com/JuliaGPU/AbstractGPUArray), I had the idea, that we should standardize all array test code and make it work for all different kind of arrays.
This probably means, that the test code should live in its own repository.
From AbstractGPUArrays:

> This could greatly improve stability of every array like construct. While we're at it, we might as well couple it with a benchmark of all the different array types, which can be used for clarifying which array should be used in which scenario.

**Comment by KristofferC** [comment]
Is this actionable? What are concrete steps to implement this?

**Comment by SimonDanisch** [comment]
Lets close this...
Over time I noticed, that it'd be quite a lot of work to get this going, because of the variance in operations, set up code and small differences in details.
Probably the best way forward is to create fragmented small benchmark suites and at some point have a hero come along, who picks those up and makes sure, that they're comparable!
