### ISSUE TITLE
Unrecognized input on insert key after arrow-up

### ISSUE THREAD

**Issue by flpf** [JuliaLang/julia#10222]
This is just a small bug i stumbled upon by accident. 
Going through the REPL history with the arrow-up key and pressing the insert key 
results in
```julia 
julia> 1
1
(#--- pressing arrow-up once followed by the insert key---#)
julia> 1ERROR: Unrecognized input
 in error at error.jl:19
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1565
 in run_interface at ./LineEdit.jl:1538
 in run_frontend at ./REPL.jl:828
 in run_repl at ./REPL.jl:157
 in _start at ./client.jl:445
```
and being send back to the shell.

My julia version is:
```julia 
julia> versioninfo()
Julia Version 0.4.0-dev+3164
Commit d615d3e (2015-02-06 16:44 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I tried this in zsh and bash.

**Comment by blakejohnson** [comment]
Could you please tell me the result of `ctrl+v` followed by `insert` at your shell?

**Comment by flpf** [comment]
This combination seems to work fine in zsh and bash. The terminal emulaters I use are 
st and gnome-terminal.

**Comment by blakejohnson** [comment]
@flpf Your terminal should spit out some characters representing its escape sequence for representing `insert`. That's what I am looking for.

**Comment by flpf** [comment]
Ok, sorry, the  characters are ```[4h``` on my laptop and ```[~2``` on my desktop computer.

**Comment by blakejohnson** [comment]
It looks like we don't appropriately capture `[*h` or `[**h` escape codes anywhere. What happens when you just hit `insert` in st before arrrow-up? I would expect that to also give an error.

**Comment by flpf** [comment]
No, that seems to work just fine. 
On a clean julia REPL hitting insert once doesn't do a thing, the second time the 
char sequence ```[4h``` is printed. 
The error only occurs if I step through the history and hit insert after the respective 
expression.  Writing ```sin(2*pi)``` and hitting insert does nothing. Getting the same 
expression from the command history by pressing the up arrow leads to the error.

**Comment by blakejohnson** [comment]
@flpf ok, that actually makes sense. We have something that will match `\e[4**`. So, if you press `insert` twice, it will match `\e[4h\e` the first time leaving the second `insert` to be interpreted as `[4h`. So, it is broken in both cases, but only creates an error in prefix search mode. I'll have a fix ready in a day or two.

**Comment by flpf** [comment]
Ok. Even though its only a minor issue which is not very likely to come up in _normal_ usage scenarios, its good to have it fixed. Thank you.
