### ISSUE TITLE
ARGS regression: options should not end up in ARGS

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10227]
This used to behave correctly and I'm not sure when it broke. When `julia` is invoked and options are parsed, only the arguments to the script should end up in `ARGS`, not all of the literal arguments to `julia` which is what's happening now. This will undoubtedly break people's code, unfortunately, since they have certainly had to work around the current broken behavior. We should also have some tests of this to make sure that it doesn't break again in the future.

**Comment by JeffBezanson** [comment]
Is this the same as #9384?

**Comment by StefanKarpinski** [comment]
Not as far as I can tell, although that might be the underlying reason why this is broken – because we've split option parsing into two separate phases (C and Julia) that can't communicate easily.

**Comment by jakebolewski** [comment]
This should be fixed in #9482.

**Comment by StefanKarpinski** [comment]
Ok, then we can close this as a dup.
