### ISSUE TITLE
norm([Inf],2) = NaN

### ISSUE THREAD

**Issue by kyle-pena-nlp** [JuliaLang/julia#10234]
Which doesn't sound too unreasonable, until you consider that in Julia:

norm([Inf],1) = Inf
norm(Inf,2) = Inf

If the above is currently the case, then maybe norm([Inf],2) should equal Inf as well?

**Comment by stevengj** [comment]
I'll submit a PR shortly to fix this.

**Comment by kyle-pena-nlp** [comment]
Cool, thanks so much @stevengj
