### ISSUE TITLE
strange parsing

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#10239]
```julia
julia> Meta.show_sexpr(:( if x == != 4
       foo
       end))
(:if, (:comparison, :x, :(==), :!=), (:block,
    :( # line 1:),
    4,
    :( # line 2:),
    :foo
  ))
```
Should this be a syntax error?

**Comment by JeffBezanson** [comment]
I think it's very hard to make this a syntax error, since we allow `!=` by itself as a valid expression. We also allow `if x == y foo end`, even though I recommend semicolons.

**Comment by JeffBezanson** [comment]
This could also be handled by #6993.

**Comment by mlubin** [comment]
Makes sense, I'll close this.
