### ISSUE TITLE
missing randn(T, ...) method

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#10237]
I just noticed that you can't do e.g. `randn(Float32, 100)`, analogous to `rand(Float32, 100)`.  This seems like an obvious omission.

**Comment by jiahao** [comment]
+1
especially `randn(Complex128, 100)`

**Comment by simonster** [comment]
Related: #9836

**Comment by ivarne** [comment]
CC @rfourquet

**Comment by ViralBShah** [comment]
Closing as a dup of #9836, which I have updated to include the general case of `randn(T,...)`.
