### ISSUE TITLE
ARM build failing during bootstrap on Raspberry Pi 2

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10235]
```
...
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
combinatorics.jl
version.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 170: LoadError(at "version.jl" line 102: BoundsError(a=Array{Union, 1}[], i=(1,))))

Makefile:162: recipe for target '/home/seth/dev/julia/julia/usr/lib/julia/sys0.o' failed
make[1]: *** [/home/seth/dev/julia/julia/usr/lib/julia/sys0.o] Error 1
Makefile:76: recipe for target 'julia-sysimg-release' failed
make: *** [julia-sysimg-release] Error 2
```

ARM.inc:

```
BFORCE_ARMV7=1

override LLVM_ASSERTIONS=1
LLVM_FLAGS+="--with-cpu=cortex-a9 --with-float=hard --with-abi=aapcs-vfp --with-fpu=neon --enable-targets=arm --enable-optimized --enable-assertions --disable-compiler-version-checks"

override OPENBLAS_DYNAMIC_ARCH=0
override OPENBLAS_TARGET_ARCH=ARMV7
override USE_BLAS64=0

override LLVM_VER=3.5.1

override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1

JCFLAGS += -fsigned-char
```

Make.user:
```
include /home/seth/dev/julia/julia/ARM.inc
override USE_SYSTEM_LIBM=1
```

**Comment by sbromberger** [comment]
ccing @ViralBShah for advice and the proper tag :)

**Comment by sbromberger** [comment]
As an additional data point: I did a completely clean build on the RPi2 and got the exact same error in the exact same place, so it's at least reproducible.

**Comment by ViralBShah** [comment]
There is a typo in the first line of ARM.inc. A `B` has snuck into the first line, as the first character. If you fix that, does that change anything? You may have to do a complete build from scratch.

**Comment by sbromberger** [comment]
Gah. Thanks, @ViralBShah - I don't know how I missed that. Rebuilding now.

**Comment by ViralBShah** [comment]
Turns out that line was not used anywhere, which is why nothing ever barfed. I have removed it now. Sorry about that.

**Comment by sbromberger** [comment]
So - that seems to indicate that fixing it will NOT fix this error? :(

**Comment by sbromberger** [comment]
...and indeed it has no discernible effect. Same error.

**Comment by sbromberger** [comment]
@ViralBShah @StefanKarpinski - can you help me understand why defining a method dispatch would result in a BoundsError on its parameters, as is apparently happening here? The offending line (102) of version.jl is as follows:

```
typemax(::Type{VersionNumber}) = VersionNumber(typemax(Int),typemax(Int),typemax(Int),(),("",))
```

**Comment by sbromberger** [comment]
OK, so line 102 in the error message isn't really line 102. I added some debugging statements in base/version.jl that moved the method dispatch down a line, and it's still complaining about 102:

`LoadError(at "sysimg.jl" line 170: LoadError(at "version.jl" line 102: BoundsError(a=Array{Union, 1}[], i=(1,))))`

What `version.jl` is being used here?

**Comment by ihnorton** [comment]
I pulled the latest everything and left it building earlier today (Samsung ARM Chromebook). Built fine, but this is with llvm-svn.

**Comment by sbromberger** [comment]
@ihnorton do you think the issue I'm seeing is llvm-related?

**Comment by ihnorton** [comment]
No idea. I'm building  w 3.5 to see. Was about 1/2 through sysimg last time
I checked. Can't access right now.

**Comment by ihnorton** [comment]
Worked fine.
```
LINK usr/lib/julia/sys.so
real    80m50.502s
```

**Comment by ViralBShah** [comment]
I am using llvm 3.5 just fine on my ARM chromebook. It is quite possible there is some memory corruption elsewhere, or that it is running out of memory. But if it was running out, I would have expected some other error.

**Comment by sbromberger** [comment]
Doubtful its OOM. I've got a gig of ram and configured a gig of swap. I was
also monitoring and didn't see any usage above 800 megs or so.




On Feb 19, 2015, at 19:49, Viral B. Shah <notifications@github.com> wrote:

I am using llvm 3.5 just fine on my ARM chromebook. It is quite possible
there is some memory corruption elsewhere, or that it is running out of
memory. But if it was running out, I would have expected some other error.

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaLang/julia/issues/10235#issuecomment-75185570>.

**Comment by ViralBShah** [comment]
Try valgrind to see if something comes up?

**Comment by sbromberger** [comment]
I don't suppose the sys.so is interchangeable?


On Feb 19, 2015, at 19:43, Isaiah <notifications@github.com> wrote:

Worked fine.

LINK usr/lib/julia/sys.so
real    80m50.502s

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaLang/julia/issues/10235#issuecomment-75185227>.

**Comment by ViralBShah** [comment]
No harm trying!

**Comment by sbromberger** [comment]
I don't know how to use valgrind.


On Feb 19, 2015, at 19:53, Viral B. Shah <notifications@github.com> wrote:

Try valgrind to see if something comes up?

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaLang/julia/issues/10235#issuecomment-75185844>.

**Comment by sbromberger** [comment]
I tried changing ARM.inc to have `--with-cpu=cortex-a7` in the `LLVM_FLAGS` but that didn't help.

**Comment by sbromberger** [comment]
PS: I'm happy to give access to my rpi (via ssh) if anyone here would like to take a shot at getting this build working...

**Comment by ermueller2000** [comment]
I'm experiencing the same error trying to build on an oDroid:

version.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 171: LoadError(at "version.jl" line 102: BoundsError(a=Array{Union, 1}[], i=(1,))))

make[1]: *** [/home/odroid/julia/usr/lib/julia/sys0.o] Error 1
make: *** [julia-sysimg-release] Error 2

**Comment by sbromberger** [comment]
I upgraded from wheezy to jessie, and now the build fails at a different point:

```
    CC src/debuginfo.o
debuginfo.cpp: In function ‘int jl_get_llvmf_info(uint64_t, uint64_t*, uint64_t*, const llvm::object::ObjectFile**)’:
debuginfo.cpp:812:30: error: ‘struct ObjectInfo’ has no member named ‘slide’
         *slide = fit->second.slide;
                              ^
Makefile:62: recipe for target 'debuginfo.o' failed
make[1]: *** [debuginfo.o] Error 1
Makefile:73: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```

**Comment by tkelman** [comment]
@sbromberger that one's actually not an ARM-specific problem, see #10376

**Comment by sbromberger** [comment]
@tkelman ah, cool - I guess I have to wait for that PR to be merged before I can retry?

**Comment by tkelman** [comment]
Yeah, unless you want to try building 3.6 on your rpi, or there's a deb/ppa for 3.6 on arm somewhere.

**Comment by sbromberger** [comment]
Thanks. 3.6 doesn't appear in an `apt-cache search` so I guess I'll wait.

**Comment by ViralBShah** [comment]
You could try changing the LLVM_VER in ARM.inc and leaving the build for a couple of days. :-)

**Comment by sbromberger** [comment]
Hah. The bug might well be fixed before the compile finishes :)

**Comment by sbromberger** [comment]
But wouldn't this be biting everyone else who's trying to build 0.4 on LLVM 3.5 right now? That is, is Julia building broken right now for a bunch of people?

**Comment by tkelman** [comment]
Yup. Don't know whether #10368 is the right fix tho. As I added in an edit, you can try checking out the parent commit right before https://github.com/JuliaLang/julia/commit/1d0b067cf30a2dded54891ad6f468b8ab7b918e9 and llvm 3.5 should work

**Comment by sbromberger** [comment]
A new error from a pull an hour ago:

```
fftw.jl
dsp.jl
sysinfo.jl
constants.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 269: LoadError(at "constants.jl" line 92: Base.AssertionError(msg="Float64(π) == Float64(big(π))")))
```

**Comment by ViralBShah** [comment]
I am guessing that there is some corruption somewhere earlier, and it manifests as different errors as stuff changes.

**Comment by sbromberger** [comment]
I left a build running overnight and it errored in exactly the same place:

```
error during bootstrap:
LoadError(at "sysimg.jl" line 269: LoadError(at "constants.jl" line 92: Base.AssertionError(msg="Float64(π) == Float64(big(π))")))

Makefile:168: recipe for target '/home/seth/dev/julia/julia/usr/lib/julia/sys0.o' failed
make[1]: *** [/home/seth/dev/julia/julia/usr/lib/julia/sys0.o] Error 1
Makefile:82: recipe for target 'julia-sysimg-release' failed
```

**Comment by vtjnash** [comment]
i vaguely recall from the jn/ccall3 (ccall with struct) work that I just completed, that you can get that error in the event of a calling convention mismatch in how we emit that call.

you might be able to get much further by removing that assertion from the code, and then experimenting in the REPL prompt to see what values are being recorded for `π` and `big(π)` (I almost wrote that as `∏`)

**Comment by sbromberger** [comment]
i commented it out and now get

```
constants.jl
fatal: error thrown and no exception handler available.
UndefVarError(var=:STDERR)
```

I wonder if `#` is not tolerated inside macros / quotes?

**Comment by sbromberger** [comment]
I got past constants.jl by just removing all three asserts. It builds, but then I get this when I run it:

```
seth@raspberrypi ~/dev/julia $ usr/bin/julia
ERROR: InexactError()
```

**Comment by sbromberger** [comment]
More weirdness:

```
seth@raspberrypi ~/dev/julia $ usr/bin/julia -e 'println("$pi")'
ERROR: BoundsError: attempt to access 11-element Array{Int32,1}:
          0
          1
         10
        100
       1000
      10000
     100000
    1000000
   10000000
  100000000
 1000000000
  at index [14]
```

**Comment by sbromberger** [comment]
Turns out that getting rid of the entire `quote` section beginning at line 86 was probably a mistake. Removing JUST the assert statements.

**Comment by vishnusuganth** [comment]
@sbromberger @ViralBShah  Hi...I tried building julia on Raspberry Pi 1. I had same issue in `constants.jl` during bootstrap process.I got past `constants.jl` by just removing all three asserts as you did.
But it breaks at `precompile.jl` with `segmentation fault`.

>REPL.jl
client.jl
markdown/Markdown.jl
docs.jl
util.jl
linalg.jl
broadcast.jl
statistics.jl
sparse.jl
fftw.jl
dsp.jl
sysinfo.jl
constants.jl
quadgk.jl
fastmath.jl
pkg.jl
profile.jl
Dates.jl
Enums.jl
deprecated.jl
basedocs.jl
precompile.jl 
Segmentation fault [signal 11]

**Comment by tkelman** [comment]
Can you try compiling a debug version and running in gdb? Do `make debug VERBOSE=1` to see the exact command that gets executed there to build the system image, then prepend `gdb --args` before the same command manually.

**Comment by vishnusuganth** [comment]
@tkelman Sure. I am trying with that right now. 
@vtjnash FYI, I enable MEMDEBUG in options.h and did `make debug VERBOSE=1`. Any insight about this ?
> gcc  "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.ji\"" -DJULIA_TARGET_ARCH=native -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -fsigned-char -DCOPY_STACKS -O0 -ggdb3 -DJL_DEBUG_BUILD -fstack-protector-all -D_GNU_SOURCE -Iflisp -Isupport -I/home/pi/julia_rpi/usr/include -I/home/pi/julia_rpi/deps/libuv/include -I/home/pi/julia_rpi/usr/include -DLIBRARY_EXPORTS -I. -I/home/pi/julia_rpi/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -c alloc.c -o alloc.dbg.obj
alloc.c: 
In function 'mk_symbol':
alloc.c:505:5: 
error: cannot convert to a pointer type
sym = (jl_sym_t*)((jl_taggedvalue_t*)malloc(nb))->value;
^
Makefile:60: recipe for target 'alloc.dbg.obj' failed
make[1]: *** [alloc.dbg.obj] Error 1
make[1]: Leaving directory '/home/pi/julia_rpi/src'
Makefile:76: recipe for target 'julia-src-debug' failed
make: *** [julia-src-debug] Error 2

**Comment by tkelman** [comment]
Looks like fe3fea50ca11aebdc298b6a96868540f4df5e8fe missed some lines for the MEMDEBUG case

**Comment by vishnusuganth** [comment]
@tkelman  I ran with `gdb --args`,but it been in this stage for almost a day.No progress at all.

>pi@raspberrypi ~/julia_rpi/base $ gdb --args /home/pi/julia_rpi/usr/bin/julia-debug -C native --build /home/pi/julia_rpi/usr/lib/julia/sys0 sysimg.jlGNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/pi/julia_rpi/usr/bin/julia-debug...done.
(gdb) ...

**Comment by tkelman** [comment]
Sorry, you have to type `r` to start it running, then it should stop at the segfault where you can type `bt` to hopefully get a backtrace

**Comment by sbromberger** [comment]
I'm still at

```
constants.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 273: LoadError(at "constants.jl" line 92: Base.AssertionError(msg="Float64(π) == Float64(big(π))")))

make[1]: *** [/home/seth/dev/julia/usr/lib/julia/sys0.o] Error 1
```

on the RPi2. Same issue as above when I comment out the assert (pi gives an array, not a const).

**Comment by sbromberger** [comment]
@vishnusuganth I don't think you're going to be successful on the RPi version 1, since it uses ARM6, and I seem to recall @ViralBShah saying that v6 was a nonstarter.

**Comment by vtjnash** [comment]
there's a few debugging tricks on http://docs.julialang.org/en/latest/devdocs/debuggingtips/. I often find it's best to drop a breakpoint in `jl_throw`, and then inspect the stack at that point to find out where it went wrong. fwiw, the array above is part of the grisu algorithm for printing floating point numbers (grisu/fastshortest.jl) and for some reason it is coming up with the wrong answer along the way to printing π.

i will also restate my above assertion, that this sort of error is likely to show up if the calling convention isn't being mapped correctly to the target hardware, per the information that gets passed as the llvm target.

**Comment by sbromberger** [comment]
@vtjnash:
>  ...this sort of error is likely to show up if the calling convention isn't being mapped correctly to the target hardware, per the information that gets passed as the llvm target.

I don't quite know what this means. I installed LLVM via `apt-get` and did an override on `USE_SYSTEM_LLVM=1` in Make.user. It still fails. I don't know enough to proceed, but I'm happy to provide a shell account for anyone who wants to try their hand in getting this built on an RPi2.

**Comment by vishnusuganth** [comment]
@sbromberger SInce LLVM supports armv6 I suppose its just a matter of tweaking Julia source and trying it. Also I have a successfully built LLVM/CLang on RPI and it works smoothly.

**Comment by sbromberger** [comment]
@vishnusuganth ok, but seeing as you have an issue open in #10488 already and this issue is for Raspberry Pi 2 / ARM7 with different errors, perhaps we should keep them separate?

**Comment by vishnusuganth** [comment]
@sbromberger Cool.I thought cross-building for ARM would be like asking too much at this point of time as native build itself is failing for most of the ARM devices.( The errors in #10488 are not related to RPi 1. I tried it on an embedded ARMv6 device)
So I just gave a try with RPi 1 / ARMv6 by following your steps to check if at least a native build works.I suppose errors which I got in RPi 1 (the ones I posted above ) are similar to yours as it failed only in bootstrap process.

**Comment by baruchel** [comment]
Thank you to all for your attempts; as a lurker I come everyday on this thread in order to see if something new has come. My message obviously doesn't help much, but I wanted to say that I appreciate what you are doing. If you succeed in compiling Julia for the new raspberry 2, I will immediately use your binaries.

**Comment by vishnusuganth** [comment]
@sbromberger Other than the `const error`,is everything else working fine for you ?

**Comment by sbromberger** [comment]
@vishnusuganth no. The repl segfaults, though I can execute basic command-line julia expressions.

**Comment by armgong** [comment]
maybe this will help someone ?

build julia on samsung chromebook2 13.3 (armv7 and 4G memory)  ok , os is archlinuxarm

override LLVM_ASSERTIONS=1
LLVM_FLAGS+="--with-cpu=cortex-a9 --with-float=hard --with-abi=aapcs-vfp --with-fpu=neon --enable-targets=arm --enable-optimized --enable-assertions"

override OPENBLAS_DYNAMIC_ARCH=0
override OPENBLAS_TARGET_ARCH=ARMV7
override USE_BLAS64=0

override LLVM_VER=3.6.0

override USE_SYSTEM_LIBM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1
override USE_SYSTEM_LAPACK=1

JCFLAGS += -fsigned-char

override USE_SYSTEM_LLVM=1
override USE_SYSTEM_PCRE=1
override USE_SYSTEM_SUITESPARSE=1
override USE_SYSTEM_BLAS=1

**Comment by sbromberger** [comment]
I tried that in `Make.arm` (except for USE_SYSTEM_SUITESPARSE=1 since I don't have suitesparse available) and got

```
error during bootstrap:
LoadError(at "sysimg.jl" line 94: LoadError(at "regex.jl" line 3: LoadError(at "pcre.jl" line 19: UndefVarError(var=:ANCHORED))))

Makefile:161: recipe for target '/home/seth/dev/julia/usr/lib/julia/sys0.o' failed
make[1]: *** [/home/seth/dev/julia/usr/lib/julia/sys0.o] Error 1
```

**Comment by physicsd00d** [comment]
Well something changed!  We're using an odroid and julia now compiles without commenting out any assertions and pi gives the correct value.  I pulled the latest version of julia and compiled with override USE_SYSTEM_BLAS=1 but it did not work.  Then I downloaded the arm binaries for llvm 3.6, installed them, and compiled using the new system llvm and not enforcing the llvm version number.

```
override LLVM_ASSERTIONS=1
LLVM_FLAGS+="--with-cpu=cortex-a9 --with-float=hard --with-abi=aapcs-vfp --with-fpu=neon --enable-targets=arm --enable-optimized --enable-assertions"

override OPENBLAS_DYNAMIC_ARCH=0
override OPENBLAS_TARGET_ARCH=ARMV7
override USE_BLAS64=0

override USE_SYSTEM_LIBM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1
override USE_SYSTEM_LAPACK=1

JCFLAGS += -fsigned-char

override USE_SYSTEM_LLVM=1
override USE_SYSTEM_BLAS=1
```
This is a big step forward for us :)  Thanks for all the help!

**Comment by ViralBShah** [comment]
Now for `make testall`. :-)

**Comment by ViralBShah** [comment]
What version of `gcc` are you using, and what OS?

**Comment by sbromberger** [comment]
I can confirm (FINALLY) that it works on the Raspberry Pi 2 using @physicsd00d's [Make.arm](https://github.com/JuliaLang/julia/issues/10235#issuecomment-94998470). \pi even works :)

Big thanks to @physicsd00d for the guidance here. Manually installing llvm 3.6.0 was the key. (I downloaded the binaries, unpacked in my home directory, and then created symlinks to the contents in `/usr/local/bin`, `/usr/local/include`, `/usr/local/share`, and `/usr/local/lib`).

```
julia> versioninfo()
Julia Version 0.4.0-dev+4444
Commit d30d286* (2015-04-22 02:34 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 5 (v7l)
  WORD_SIZE: 32
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.6.0
```

**Comment by sbromberger** [comment]
@ViralBShah is there a way to limit the number of julia processes spawned during `make testall`?

**Comment by tkelman** [comment]
`make testall1` or `JULIA_CPU_CORES=3 make testall`

**Comment by sbromberger** [comment]
@tkelman thanks. The RPi2 ran out of memory (and swap) with normal `testall`.

**Comment by baruchel** [comment]
Hi, could you give a link for downloading these Julia binaries for RPI2? I would ne happy to have a test. Thank you again, regards.

**Comment by sbromberger** [comment]
So close with `testall`:

```
seth@raspberrypi ~/dev/julia $ tail -f ~/testall.out
    JULIA test/all
     * linalg1              in 906.94 seconds
     * linalg2              in 800.58 seconds
     * linalg3              in 349.31 seconds
     * linalg4              in 120.78 seconds
     * linalg/lapack        in  57.05 seconds
     * linalg/triangular    in 5821.59 seconds
     * linalg/tridiag       in 244.85 seconds
     * linalg/bidiag        in 430.95 seconds
     * linalg/diagonal      in 258.59 seconds
     * linalg/pinv         exception on 1: ERROR: LoadError: assertion failed: |vecnorm(a * x - b) / vecnorm(b) - 0| <= 0.01
  vecnorm(a * x - b) / vecnorm(b) = 0.012504161841088008
  0 = 0
  difference = 0.012504161841088008 > 0.01
while loading linalg/pinv.jl, in expression starting on line 115
ERROR: LoadError: LoadError: assertion failed: |vecnorm(a * x - b) / vecnorm(b) - 0| <= 0.01
  vecnorm(a * x - b) / vecnorm(b) = 0.012504161841088008
  0 = 0
  difference = 0.012504161841088008 > 0.01
while loading linalg/pinv.jl, in expression starting on line 115
while loading /home/seth/dev/julia/test/runtests.jl, in expression starting on line 3

Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:492: recipe for target 'testall1' failed
make: *** [testall1] Error 2
```

**Comment by ihnorton** [comment]
Something is probably still not set correctly for OpenBLAS.

**Comment by sbromberger** [comment]
@baruchel - https://www.dropbox.com/s/6cuvzv2z1knbxah/julia-0.4-rpi2.tgz?dl=0 is the fill (350+MB) build dir, and https://www.dropbox.com/s/l97tv8zm97vxcag/julia?dl=0 is the julia binary by itself (though I can't imagine it would work without supporting libs).

**Comment by physicsd00d** [comment]
@baruchel 
If you'd like to try to replicate this (in case the julia binaries don't work),  I got the llvm binaries from here: http://llvm.org/releases/download.html
Copy all of the contents into your /usr/local directory or, like me, make a new directory and point your PATH and LD_LIBRARY_PATH to them.  So for instance, I made a new directory /sw, copied the extracted contents of the llvm tarball to /sw and then added this to my .bashrc
```
export PATH=/sw/bin/:$PATH
export LD_LIBRARY_PATH=/sw/lib/:$LD_LIBRARY_PATH
```

@ViralBShah 
This odroid XU3 is running Lubuntu.
```
odroid@odroid:~/tcolvin/julia$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty


odroid@odroid:~/tcolvin/julia$ clang -v
clang version 3.6.0 (tags/RELEASE_360/final)
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.7
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.7.3
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.8
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.8.2
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.9
Found candidate GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.9.0
Selected GCC installation: /usr/lib/gcc/arm-linux-gnueabihf/4.8
Candidate multilib: .;@m32
Selected multilib: .;@m32


julia> versioninfo()
Julia Version 0.4.0-dev+4434
Commit 86ba78f* (2015-04-21 22:08 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 3 (v7l)
  WORD_SIZE: 32
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.6.0
```

And unfortunately my testall failed as well but different from @sbromberger's error.  Mine is due to a missing module?  
```
    JULIA test/all
exception on 6: ERROR: LoadError: error compiling naupd: could not load module libarpack: no error
while loading linalg/arnoldi.jl, in expression starting on line 6
error in running finalizer: InterruptException()
error in running finalizer: InterruptException()
error in running finalizer: InterruptException()
error in running finalizer: InterruptException()
error in running finalizer: InterruptException()
ERROR: LoadError: LoadError: error compiling naupd: could not load module libarpack: no error
while loading linalg/arnoldi.jl, in expression starting on line 6
while loading /home/odroid/tcolvin/julia/test/runtests.jl, in expression starting on line 3
WARNING: Forcibly interrupting busy workers
WARNING: Unable to terminate all workers
	From worker 8:	     * linalg/tridiag       in  83.74 seconds
	From worker 6:	     * linalg/lapack        in 130.61 seconds
	From worker 5:	     * linalg4              in 143.60 seconds
	From worker 5:	     * linalg/givens        in  49.48 seconds
	From worker 9:	     * linalg/bidiag        in 285.58 seconds
	From worker 4:	     * linalg3              in 342.58 seconds
	From worker 6:	     * linalg/pinv          in 248.57 seconds
	From worker 8:	     * linalg/diagonal      in 340.89 seconds
	From worker 4:	     * linalg/symmetric     in 227.28 seconds
	From worker 9:	     * linalg/lu            in 370.00 seconds
	From worker 5:	     * linalg/cholesky      in 683.52 seconds
	From worker 3:	     * linalg2              in 891.26 seconds
	From worker 8:	     * core                 in 602.30 seconds
	From worker 2:	     * linalg1              in 1046.53 seconds
	From worker 7:	     * linalg/triangular    in 4483.00 seconds

	From worker 6:	     * linalg/arnoldi      make[1]: *** [all] Error 1
make: *** [testall] Error 2
exception on 7: ERROR: InterruptException:
```

@sbromberger 
It looks like my pinv test passed where yours had failed?

Since those tests took so long -- only to fail -- is it possible for me to comment out the ones that I think worked without messing up any other tests to be run downstream?  I'd like to speed up subsequent testalls.  I'll try to mess with it later tonight.

**Comment by ViralBShah** [comment]
Can someone submit a patch to `Make.arm`? We need to figure out what LLVM build flags are used with 3.6.0 and update those in Make.arm.

On tests, I usually run the tests all one at a time. See various arm tagged issues, and file a new one if required. IIRC, on my setup, all linear algebra tests passed.

**Comment by ihnorton** [comment]
I updated the build on my chromebook yesterday. The current Make.arm works
fine, modulo known test failures, with LLVM 3.6 *on the intended
architecture*. If changes are made, please make them conditional on the
architecture.

**Comment by ViralBShah** [comment]
Should we update Make.arm to use llvm 3.6.0?

**Comment by sbromberger** [comment]
It didn't work. I had to use the precompiled bins from llvm.org.

On Apr 22, 2015, at 11:57, Viral B. Shah <notifications@github.com> wrote:

Should we update Make.arm to use llvm 3.6.0?

—
Reply to this email directly or view it on GitHub
<https://github.com/JuliaLang/julia/issues/10235#issuecomment-95302263>.

**Comment by ViralBShah** [comment]
@sbromberger Can you provide a PR to README.arm.md providing these alternate steps? I am building on a scaleway.com arm machine, and can't get sys.ji to build. I have built LLVM 3.6.0 from source. BTW, scaleway arm machines are free until May 1.

````
error during bootstrap:
LoadError(at "sysimg.jl" line 145: LoadError(at "primes.jl" line 76: InexactError()))
````

**Comment by vtjnash** [comment]
that seems to be due to an autodetection issue with llvm. the build passes with the following patch:
```
JULIA_CPU_TARGET=cortex-a8
```
```diff
diff --git a/src/codegen.cpp b/src/codegen.cpp
index 3883359..4f7378d 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -5419,7 +5419,7 @@ extern "C" void jl_init_codegen(void)
 #ifdef USE_MCJIT
     jl_mcjmm = new SectionMemoryManager();
 #endif
-    const char *mattr[] = {
+    const char *mattr[] = { "-neon",
 #ifndef USE_MCJIT
         // Temporarily disable Haswell BMI2 features due to LLVM bug.
         "-bmi2", "-avx2",
```

**Comment by sbromberger** [comment]
@ViralBShah will propose a PR this morning. Stand by.

**Comment by daanhb** [comment]
I have succesfully built Julia on a RPi2 using the instructions above. For completeness, ``make testall1`` fails in the exact same way for me as for @sbromberger above, with a failed assertion on ``vecnorm`` in ``linalg/pinv.jl``.

**Comment by daanhb** [comment]
I did some more tests. As for existing issues, I can reproduce #10124 and #10127. I do not see #10260 in my build. I am now trying something similar to #8402 to get a complete picture.

In the next few weeks we will be building a small cluster of Raspberry Pi's, for demonstration purposes. It is a poor man's supercomputer... It would be cool to have julia working for some demos - that is my interest here.

**Comment by ViralBShah** [comment]
This is probably the same issue as #10917

@vtjnash Should we use the same architecture on RPi2 as RPi1?

**Comment by ihnorton** [comment]
RPi1 is ARMv6, RPi2 is ARMv7.

**Comment by vtjnash** [comment]
true, but Viral is probably correct that it would work (as I understand it, the RPi2 system was designed to be highly compatible with the RPi1 system)

/proc/cpuinfo says RPi2 is a 0xc07
https://www.reddit.com/r/raspberry_pi/comments/2ulbv3/proccpuinfo_for_the_raspberry_pi_2/

llvm lib/Support/Host.cpp does not list this, so it gets detected as "generic"

llvm lib/Target/ARM/ARM.td reveals that "generic" does not have a vfp, which make the calling convention incorrect (and the processor feature set selection suboptimal)

**Comment by daanhb** [comment]
For completeness, I did run a lot of tests two weeks ago on a Pi 2. The output was similar to #8402, but slightly better. I found more errors by uncommenting tests that failed. In addition to errors that have been reported, I encountered at least the following: two segmentation faults (strings.jl and readdlm.jl), an LLVM error (bitarray.jl), various issues with rationalize() (numbers.jl), and a 'mismatch of non-finite elements' error (pinv.jl).
I did not want to start a flood of issues and I haven't had time since to do a debug build, but I did keep output of tests and can provide them if anybody is interested (if so, where?).
Btw, our Pi cluster has been assembled in the meantime, and with 17 nodes and 68 cores it is still cheaper than my laptop. (Not sure yet whether it is actually also faster.)

**Comment by ViralBShah** [comment]
Many of these are already filed as separate issues, with the `arm` tag. Anything else not already captured should probably be filed as a separate bug.

**Comment by baruchel** [comment]
I am aware that you already, all of you, did a great job! Since Julia seems to be already usable for some simple tasks on the RPI2, do you think that some "release" package could be made available? Either some statically-linked binary or some archive containing only the binary with the necessary libraries (in some directory ready to be uncompressed into /opt/julia for instance)? That would be really useful. Thank you again to all, best regards, b.

**Comment by ViralBShah** [comment]
It is certainly on my TODO. However, the distribution package was crashing (even though the source was working). Will try again. Once I have something working, I will put it out.

I guess we can announce alpha support for `arm` in 0.4 as well.

**Comment by ViralBShah** [comment]
I suspect that the build should be a lot smoother now. It would be nice to see if `make` just works for RPi2, or if LLVM binaries are still required to get this to work.

**Comment by daanhb** [comment]
Just to confirm: a regular make just works on my Raspberry Pi 2 and leads to a functional REPL. LLVM 3.6.1 was built in the process.
