### ISSUE TITLE
`print()` for tuple should use `print()` to stringify its contents

### ISSUE THREAD

**Issue by mkyt** [JuliaLang/julia#10233]
When `print`ing tuple, its contents are currently stringified by `show()` instead of `print()`.

```julia
julia> a::Uint16 = 0x4321
0x4321
julia> print(a)
17185
julia> print((a, ))
(0x4321,)
```

I think it is preferable to use `print` for displaying its contents when `print`ing tuple
as `print` and `show` give different results for some types, as in the example above.

**Comment by JeffBezanson** [comment]
The reason we do this is that numbers have canonical printed representations, but tuples do not. As soon as we're printing `(   ,)`, we're using julia syntax and might as well stick with it. If we printed `(17185,)`, that would be a representation of a julia object, but of a *different* julia object, which seems like a strange thing to do.

**Comment by kmsquire** [comment]
This suggests (again) a python-like distinction between `repr` and `string`.

**Comment by StefanKarpinski** [comment]
It's is a bit messier than ideal right now, but there is a somewhat consistent distinction made already.

**Comment by mkyt** [comment]
I cannot grasp what "canonical" means in this context, but as I read the discussion in #3450,
I thought `show`/`repr` and `print`/`string` in julia roughly correspond to python's `repr` (unambiguous) and `str` (human-friendly) and so it is more natural and consistent that these distinction propagate to their contents when `show`ing or `print`ing container objects (like tuples).

**Comment by JeffBezanson** [comment]
By "canonical" I mean not julia-specific. I don't really see the value of printing `(17185,)` here. Who/what is the consumer for that output?

**Comment by mkyt** [comment]
Hex notation is quite annoying when debugging codes dealing with tuples containing unsigned ints.
```julia
julia> ui, ui_t = uint(123), tuple(uint(456), uint(789))
(0x000000000000007b,(0x00000000000001c8,0x0000000000000315))
julia> show(ui)
0x000000000000007b
julia> print(ui)
123
julia> show(ui_t)
(0x00000000000001c8,0x0000000000000315)
julia> print(ui_t)
(0x00000000000001c8,0x0000000000000315) # (456,789) is much more comprehensible
```

**Comment by jiahao** [comment]
Relevant: #7959

**Comment by nalimilan** [comment]
Even if Julia syntax is used for `print`ing tuples, it doesn't mean the output should be parseable to the same Julia object, if the goal is to offer a short/readable representation (the intended consumer of `print` is a human).

**Comment by johnmyleswhite** [comment]
-1 to printing unsigned ints as integers rather than hex

**Comment by nalimilan** [comment]
@johnmyleswhite I think the debate here is: why would `print((0x1,))` use hex while `print(0x1)` wouldn't, and vice-versa? I.e. a consistency issue.

**Comment by StefanKarpinski** [comment]
Let's just print everything in hex – consistency problem solved.

**Comment by JeffBezanson** [comment]
I can totally understand not wanting to see hex in many cases, but I think that's the only real issue here. Consider another example of the general proposal described by the issue title:

```
julia> print("hello, world.")
hello, world.
julia> print(("hello, world.",))
("hello, world.",)
```

With the proposed change, the second output would be `(hello, world.,)`. Is that what you want?

**Comment by mkyt** [comment]
@JeffBezanson, thanks for pointing this out. I wasn't aware of the pitfall.

On second thought, I realized the current behavior of `print` is "consistent" in that
it uses canonical notation if any, uses `repr` otherwise, as @StefanKarpinski stated
and it would be better to leave it as it is.

Nevertheless, I think its' very handy to have a easy way of controlling over the level
of detail in `print`ing julia objects out in the planned clean-up of output functions (#7959).
