### ISSUE TITLE
reduce.jl opinionated about what types support ordering

### ISSUE THREAD

**Issue by kyle-pena-nlp** [JuliaLang/julia#10236]
There's a series of validation checks in operators.jl that go like this:

scalarmin(x::AbstractArray, y::AbstractArray) = error("ordering is not well-defined for arrays")
scalarmin(x , y::AbstractArray) = error("ordering is not well-defined for arrays")
scalarmin(x::AbstractArray, y ) = error("ordering is not well-defined for arrays")

I *totally* agree that for a function called scalarmin, arrays are 'out of bounds'.

But here's the rub: For my program, I defined an ordering over Vector{Float64} that goes like this:

<(x::Vector{Float64}, y::Vector{Float64}) = norm(x,2) < norm(x,2)

However, when I call minimum([1.], [1.]) I'm told that "ordering is not well-defined for arrays".

Agreed with the message under ordinary circumstances, but I *defined* what ordering means for arrays.

I'm not sure how reduce.jl ended up invoking scalarmin, but my thought is that core frameworks shouldn't be opinionated about which types make sense for what operators, since Julia allows me to overload operators.

**Comment by StefanKarpinski** [comment]
Among other issues, that's not an ordering on vectors, it's a partial order, so you can't, e.g. sort using it. Redefining built-in operators for built-in types, while possible, is probably not a good idea – as you're seeing. You can do all order-requiring operations using a custom ordering function (or type for performance), which is what I would suggest.

**Comment by kyle-pena-nlp** [comment]
@StefanKarpinski  - thanks for the feedback.

It *could* be a total order if I defined ==(... ,..) to be norm(x,2) == norm(y,2), but then I'm getting into even more dangerous territory as =='s behavior would be pretty unexpected there on out.

However, your point on overloading operators is well taken.

**Comment by StefanKarpinski** [comment]
It's still not a total order – it's a [total pre-order](http://en.wikipedia.org/wiki/Weak_ordering#Total_preorders) since any pair of vectors with the same 2-norm are equivalent, yet not identical. Can you use a custom ordering function for the application you have? Something like `sort(v,by=norm)`?

**Comment by kyle-pena-nlp** [comment]
Oops, you're right.  I can totally use a custom ordering function.

**Comment by StefanKarpinski** [comment]
Ok, cool. Glad to hear that. Closing.
