### ISSUE TITLE
Make cleanall should remove config.status files from deps

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10240]
Or, more appropriately, a "distclean" target should be implemented in the Makefile.

**Comment by tkelman** [comment]
we have `distclean-all` which will blow away all the deps completely

**Comment by sbromberger** [comment]
```
seth@redshift ~/dev/julia/julia $ make distclean-all
make: *** No rule to make target 'distclean-all'.  Stop.
```

**Comment by andreasnoack** [comment]
It's in the makefile for reps, so it is make -C deps distcleanall

2015-02-19 10:28 GMT-05:00 Seth Bromberger <notifications@github.com>:
