### ISSUE TITLE
building 0.3.6 with system libraries in chroot fails

### ISSUE THREAD

**Issue by rekado** [JuliaLang/julia#10246]
I'm trying to package Julia 0.3.6 for GNU Guix and stumbled upon a problem:

~~~
...
a - spqr_append.o
a - spqr_type.o
a - spqr_tol.o
ar: creating librbio.a
a - RBio.o
Warning: git information unavailable; versioning information limited
make[2]: *** No rule to make target 'jltypes.o', needed by '/buildtmp/nix-build-julia-0.3.6.drv-1/julia-0.3/usr/lib/libjulia.so'.  Stop.
Makefile:89: recipe for target 'julia-release' failed
make[1]: *** [julia-release] Error 2
Makefile:37: recipe for target 'release' failed
make: *** [release] Error 2
~~~

Up to this point there are only two unrelated warnings and no other errors.

I'm passing these flags to GNU Make:

~~~
"CONFIG_SHELL=bash"
"SHELL=bash"
"USE_SYSTEM_LLVM=1"
"USE_LLVM_SHLIB=1"
"USE_SYSTEM_LIBUNWIND=1"
"USE_SYSTEM_PCRE=1"
"USE_SYSTEM_LIBM=1"
"USE_SYSTEM_BLAS=1"
"USE_SYSTEM_LAPACK=1"
"USE_SYSTEM_FFTW=1"
"USE_SYSTEM_GMP=1"
"USE_SYSTEM_MPFR=1"
"USE_SYSTEM_ARPACK=1"
"USE_SYSTEM_LIBUV=1"
"USE_SYSTEM_LIBGIT2=1"
~~~

Building Julia with the included dependencies and without using any system libraries results in no errors, but for obvious reasons I'd like to use as many system libraries as possible for the Julia package.

(With GNU Guix the package is built in a chroot where only explicitly declared dependencies (in addition to the GNU toolchain) are available.)

I'm using the latest tarball: https://github.com/JuliaLang/julia/releases/download/v0.3.6/julia-0.3.6_0c24dca65c.tar.gz

**Comment by tkelman** [comment]
Is it trying to build from somewhere other than the source checkout? We don't properly support out-of-tree builds yet. `jltypes.o` should be covered in https://github.com/JuliaLang/julia/blob/release-0.3/src/Makefile

Also note that `USE_SYSTEM_LIBUV=1` is highly unlikely to work properly at this point.

**Comment by rekado** [comment]
I'm building from the source checkout.

> Also note that USE_SYSTEM_LIBUV=1 is highly unlikely to work properly at this point.

I will try again without this flag.

**Comment by tkelman** [comment]
I doubt that's the cause of this particular problem. You may need to explicitly specify `LLVM_CONFIG` ? See https://github.com/JuliaLang/julia/blob/master/.travis.yml for how we use mostly system libraries on Travis. It's not running in a chroot, but it might be setting some flags that you aren't. Some of the flags in there might also be obsolete, I don't think we need `LLVM_LLC` any more for example.

Do you have a simple set of steps we could use to reproduce your build environment?

**Comment by rekado** [comment]
Without USE_SYSTEM_LIBUV=1 I'm getting quite a bit farther in the build process; notably, I no longer run into this particular error and jltypes.o is built as expected.

It's now failing with this error instead:

~~~
    LINK usr/lib/libjulia.so
ld: cannot find -lLLVM-3.5.0svn
collect2: error: ld returned 1 exit status
~~~

But I'm sure I can convince it somehow not to misunderstand my LLVM as an svn version.

> Do you have a simple set of steps we could use to reproduce your build environment?

Not really, short of letting you use Guix, which probably doesn't count as "simple" in this context :)

**Comment by rekado** [comment]
I suspect this LLVM linking issue to be a problem with Guix, actually.

**Comment by tkelman** [comment]
Interesting, maybe it was `LIBUV_INC` or something else not working correctly in `src/Makefile` when trying to use system libuv. LLVM linking should be fixable by specifying the right name for `LLVM_CONFIG`.

> Not really, short of letting you use Guix, which probably doesn't count as "simple" in this context :)

Try me? I was actually looking into Guix not that long ago, didn't get much further than "that looks cool, I should try it sometime" though.

**Comment by rekado** [comment]
I avoid the LLVM problem by not passing `"USE_LLVM_SHLIB=1"` to make.  Our LLVM package does not seem to provide a shared LLVM library.

A bigger issue that I ran into is the use of shared libraries.  `./src/ccall.cpp` explicitly builds a map of sonames by calling `/sbin/ldconfig -p`.  `ldconfig` does not exist on Guix (nor on Nix) because no system-wide ld.so cache is used.

Replacing `/sbin/ldconfig -p` with a noop like `true` fixes the symptom but we're left with an empty map, causing the build of pcre.jl to fail because libpcre cannot be found in the map.

~~~
...
string.jl
utf8proc.jl
regex.jl
pcre.jl
error during bootstrap: LoadError(at "sysimg.jl" line 84: LoadError(at "regex.jl" line 3: LoadError(at "pcre.jl" line 7: ErrorException("error compiling anonymous: could not load module libpcre: libpcre: cannot open shared object file: No such file or directory"))))

signal (11): Segmentation fault
unknown function (ip: -1570947658)
unknown function (ip: -1576628437)
unknown function (ip: -1576698030)
unknown function (ip: -1576693790)
unknown function (ip: -1576792167)
unknown function (ip: -1571001198)
unknown function (ip: -1570957390)
jl_dump_objfile at /buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/src/codegen.cpp:427
julia_trampoline at /buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/src/init.c:1043
unknown function (ip: 4200269)
__libc_start_main at /gnu/store/q2mm1wv4a3g0b29yv0rjybfjh8kr07qi-glibc-2.20/lib/libc.so.6 (unknown line)
unknown function (ip: 4200325)
unknown function (ip: 0)
bash: line 1:  8381 Segmentation fault      (core dumped) /buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/usr/bin/julia -C native --build /buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/usr/lib/julia/sys0 sysimg.jl
Makefile:126: recipe for target '/buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/usr/lib/julia/sys0.o' failed
make[1]: *** [/buildtmp/nix-build-julia-0.3.6.drv-3/julia-0.3/usr/lib/julia/sys0.o] Error 139
Makefile:37: recipe for target 'release' failed
make: *** [release] Error 2
~~~

**Comment by tkelman** [comment]
> `ldconfig` does not exist on Guix (nor on Nix) because no system-wide ld.so cache is used.

That sounds more fatal. I don't know how to work around that, it might end up being necessary to hard-code explicit paths to the shared-library dependencies?

**Comment by rekado** [comment]
I'm making progress patching ./src/ccall.cpp at build time to contain an explicit map from library names to so-paths.  This seems to work.

**Comment by tkelman** [comment]
Yeah, Julia's ccall is very flexible and one of the most user-friendly FFI's I've ever seen. But porting it to an environment where finding shared library locations works differently might be tough. Let us know if you have a link to the discussion, if it's on a public mailing list. Curious to see what the resolution would be. How does Guix handle say Python's ctypes, which might work somewhat similarly?

**Comment by tkelman** [comment]
I have a thought. If every shared library in Guix exists in some non-default location and you have some other mechanism for locating them, could you populate the Julia variable `DL_LOAD_PATH` with their locations? That should by dynamically modifiable by users, Julia packages, etc to allow `ccall` into additional libraries, but for your Guix build purposes you can hardcode the non-standard locations of default dependencies like pcre, gmp, etc as the initial value for `DL_LOAD_PATH`.

**Comment by rekado** [comment]
I had a similar thought, but didn't know `DL_LOAD_PATH` existed.  Is this variable currently respected by the `ccall` mechanism?

BTW: here's the discussion on the mailing list: https://lists.gnu.org/archive/html/guix-devel/2015-03/msg00199.html

**Comment by tkelman** [comment]
Should be. According to the docs https://raw.githubusercontent.com/JuliaLang/julia/master/doc/stdlib/c.rst it works for `dlopen`, but I believe `ccall` does a `dlopen` internally (unless it gets handed a handle instead of a library path/name).

It sounds like Guile has a similar mechanism, but IIUC it uses an environment variable rather than a language-level variable?

**Comment by tkelman** [comment]
@rekado are there still any action items here or should we close this?

**Comment by rekado** [comment]
Everything appears to work fine, so I think this can be closed.  Thanks for the support!
