### ISSUE TITLE
Showing sparse arrays in dictionaries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10257]
This is probably more general than sparse, but at least for the sparse matrix case, I would love to show something better than `...`. Something like `m x n sparse matrix with nnz nonzeros`.

````
julia> a = Dict()
Dict{Any,Any} with 0 entries

julia> a["sparse"] = speye(5)
5x5 sparse matrix with 5 Float64 entries:
	[1, 1]  =  1.0
	[2, 2]  =  1.0
	[3, 3]  =  1.0
	[4, 4]  =  1.0
	[5, 5]  =  1.0

julia> a
Dict{Any,Any} with 1 entry:
  "sparse" => …
````

**Comment by jakebolewski** [comment]
Related performance issue with current implementation

```julia
julia> @time a = sprandn(50_000, 100_000, 0.01);
elapsed time: 3.249520351 seconds (1474 MB allocated, 7.23% gc time in 5 pauses with 3 full sweep)

julia> D = Dict("a"=>a);

julia> @time display(D)
Dict{ASCIIString,Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}} with 1 entry:
  "a" => …
elapsed time: 72.493628928 seconds (29965 MB allocated, 4.88% gc time in 1291 pauses with 1 full sweep)
```

**Comment by mbauman** [comment]
Hah, yes, that's unfortunate.  It's happening because sparse matrices print with a leading '\n'.  It'd make sense for `showdict` to trim leading newlines, but it'd also probably be sensible to get rid of that newline for in the sparse print method.

**Comment by mbauman** [comment]
This is significantly better now, but still not ideal:

```julia
julia> a
Dict{Any,Any} with 1 entry:
  "sparse" => 5x5 sparse matrix with 5 Float64 entries:…
```

**Comment by mbauman** [comment]
Actually, it now matches dense matrices.  Is there more you want done here?  If so, either the title should change or it should be closed in favor of a more general printing issue.

```julia
julia> a
Dict{Any,Any} with 2 entries:
  "dense"  => 5x5 Array{Float64,2}:…
  "sparse" => 5x5 sparse matrix with 5 Float64 entries:…
```

**Comment by ViralBShah** [comment]
This is completely fine. I think we can close this specific issue.
