### ISSUE TITLE
confusing types of Complex arrays

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#10255]
This seems confusing:
```
julia> ca=[0+0im, 0+0im, 0+0im]
3-element Array{Complex{Int64},1}:
 0+0im
 0+0im
 0+0im

julia> ca2=Complex[0+0im, 0+0im, 0+0im]
3-element Array{Complex{T<:Real},1}:
 0+0im
 0+0im
 0+0im
```
Commit 4e68cb4* (0 days old master)

**Comment by jiahao** [comment]
This is not a bug, but the result of parametric invariance. `ca2` is defined to have elements of type `Complex` .

If this issue is about the name `Complex` being confusing, I had proposed renaming `Complex` in #8142 , but didn't seem to garner more support.

**Comment by catawbasam** [comment]
But why should ca get typed as Array{Complex{Int64},1} ?  
I didn't (intentionally) do anything to narrow the type in the assignment.

**Comment by jiahao** [comment]
Why shouldn't it? How is it different from typing `[1, 2]` to be `Array{Int}` or `[1, "2"]` to be `Array{Any}`?

**Comment by JeffBezanson** [comment]
If you don't specify an element type, we pick for you. We prefer a narrow type by default because homogeneous arrays are extremely common and essential for performance.

**Comment by catawbasam** [comment]
Ok, then why not prefer a narrow type for `ca2=Complex[0+0im, 0+0im, 0+0im]` ?
Aren't those elements also homogenous?

**Comment by nalimilan** [comment]
I guess that's because `Complex` is equivalent to `Complex{T<:Real}`, so it's equivalent to asking explicitly for an array that can hold any `Complex{T<:Real}` value. Sometimes you may need this, if you don't plan to store only `Complex{Int64}` values in the array.

**Comment by JeffBezanson** [comment]
Yes, that syntax is for requesting an element type. You're right that we could have decided to have `T[...]` *convert* its arguments to type `T`, followed by doing what `[ ... ]` does. However then it would be very hard to get a heterogeneous array, and wanting `Any[ ... ]` is common enough.
