### ISSUE TITLE
tests: change == to === where possible

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10251]
See discussion here: https://github.com/JuliaLang/julia/commit/2af73dd7723c91b0e9fcf5af7662b40c8fb97067. Where possible, we should test the identify of the return value, not just its value. This would catch more changes that could possibly break packages and other external code.

**Comment by sbromberger** [comment]
This should also probably be referenced in/by #9493 as well.

**Comment by catawbasam** [comment]
Thoughts re #10261? (testing type / identity of mutables)

**Comment by musm** [comment]
Is this something that can be closed now?

**Comment by vtjnash** [comment]
Yep, don't think there's anything actionable here
