### ISSUE TITLE
Unexpected type in expression involving arrays

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10258]
I would expect the following two lines of code to create the same type, but they do not:

    julia> typeof([[5.,6.,7.] .* exp(-im * [1.0,2.0,3]) for t in 1:2])
    Array{Any,1}

    julia> typeof([[5.,6.,7.] .* exp(-im * [1.0,2.0,3.0]) for t in 1:2])
    Array{Array{Complex{Float64},1},1}

**Comment by JeffBezanson** [comment]
This is #7258. There is also a performance problem in handling array literals with mixed types, like `[1.0,2.0,3]`. With mixed types, there are n^m cases, and a fairly detailed process is needed to work out the result type. Issue #4467.

**Comment by garrison** [comment]
Thanks @JeffBezanson; I'll close in favor of #7258.
