### ISSUE TITLE
FIXME's in test/numbers.jl

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10265]
There are three tests in `test/numbers.jl` that are commented out and marked `FIXME!`.  Is there something about them that can be fixed, or should they simply be removed?  Two of the three have been there without explanation since 51ba735784397d9, and a third was added in d887aba7a45.

CC: @StefanKarpinski

**Comment by JeffBezanson** [comment]
Those cases now (correctly) throw DivideErrors.

**Comment by garrison** [comment]
Cool, looks like my changes in #10259 take care of this then.  I'll remove the `FIXME` lines as part of that PR.

**Comment by tkelman** [comment]
Shouldn't these be `@test_throws DivideError` instead of just taking them out then?

**Comment by garrison** [comment]
They are, see c8d8bb3.

**Comment by tkelman** [comment]
cool, my bad, I only looked at https://github.com/garrison/julia/commit/cf991b51ca71d8ed1c2aa84aacb73665d37fb3a2
