### ISSUE TITLE
Unused variable in abstract cholesky decomposition

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#10262]
https://github.com/JuliaLang/julia/blob/master/base/linalg/cholesky.jl#L38
and
https://github.com/JuliaLang/julia/blob/master/base/linalg/cholesky.jl#L72
define
``AkkInv = inv(A[k,k])``
which is not used subsequentially (and might be expensive).

**Comment by andreasnoack** [comment]
Thanks for reporting this.
