### ISSUE TITLE
reducedim incorrect output for arrays larger than 16 elements

### ISSUE THREAD

**Issue by Cody-G** [JuliaLang/julia#10264]
```
#define a reduction operator
notnanplus(a, b) = isnan(b) ? a : a+b

a = rand(16)
a[1] = NaN
#this works:
reducedim(notnanplus, a, 1, 0.0)

b = rand(17)
b[1] = NaN
#this incorrectly returns 0
reducedim(notnanplus, b, 1, 0.0)
```

This only happens when the input is larger than 16 elements long _and_ there is a NaN in the first position of the array.

It seems that in the problem cases reduction stops after only considering the initial value and the first element of the reduction target.

This is also an issue in 0.3

Related to (but not caused by) #9702

**Comment by JeffBezanson** [comment]
I think this is because the order of operations is not defined for `reduce` and `reducedim`. `notnanplus` is not associative.

**Comment by rickhg12hs** [comment]
To work around `reducedim`'s ordering ambiguity, you could change `notnanplus` to something like:
```julia
notnanplus(a, b) = isnan(b) ? a : ( isnan(a) ? b : a+b )
```

**Comment by Cody-G** [comment]
I suppose notnanplus as I wrote it is technically not associative, but the reductions can be made in any order as long as "a" is not a NaN in the first reduction (it is the initial value, 0.0).  And that still doesn't explain why it should only work for arrays less than 16 elements long.

It does work fine if I redefine notnanplus as rick suggested, but I still don't understand why it shouldn't work with my definition.

**Comment by JeffBezanson** [comment]
I don't recognize a difference between "not associative" and "technically not associative".

The 16 elements is exposing implementation-dependent behavior due to violating the function's assumptions.

**Comment by StefanKarpinski** [comment]
I mean, I think it's fine to reduce with a non-associative reducer – you just have to be happy with any order that the elements are passed to the reducer.

**Comment by JeffBezanson** [comment]
True.

**Comment by StefanKarpinski** [comment]
In this case, you can see what the associativity is like this:

```julia
julia> reducedim((x,y)->Any[x,y], a, 1, Any[])
1-element Array{Array{Any,1},1}:
 Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[],NaN],0.0852803932744477],0.10069169830771885],0.37410056466396924],0.0580842509636561],0.9316377938399898],0.014649519527098587],0.8545179453086362],0.4765892688372859],0.09140770251768404],0.1229487241042011],0.6199503580234409],0.44337678958019766],0.4996042186576626],0.7035901520951864],0.646630264634384]

julia> reducedim((x,y)->Any[x,y], b, 1, Any[])
1-element Array{Array{Any,1},1}:
 Any[Any[],Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[Any[NaN,0.4191697682968478],0.7853103975475597],0.2799740187827551],0.09285592149085331],0.1997312396874671],0.8147599955094287],0.027028379718246454],0.7895815670181261],0.20392199961717994],0.45383078940196264],0.39197170918679647],0.6066740275086933],0.8453603562247265],0.9180844084573521],0.09788509992280958],0.04867654104089536]]
```

**Comment by Cody-G** [comment]
This makes sense now.  I was acting on the assumption that the first reduction always included the provided initial value, so the function would only need to be associative for the remaining reductions.  But Stefan's example shows that this isn't the case.  Thanks for your responses!
