### ISSUE TITLE
Search for package names in help mode?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10272]
Currently `?Images` doesn't reveal the existence of `Images.jl`:

``` jl
help?> Images
search:

Couldn't find Images
Perhaps you meant imag, Dates, names, Ranges or primes
```

It would be nice if the help search could also match the names of registered or installed packages. Perhaps something like this for registered but not installed packages:

``` jl
help?> Images
search: Images

Images is a registered package but is not installed. To install it, run

    Pkg.add("Images")
```

and for installed packages (not necessarily registered):

```
Images is an installed package. To load it, run

    using Images
```

Thoughts?

**Comment by timholy** [comment]
+1. If it's installed, perhaps `?Images` should display the README even if you haven't yet said `using Images`.

**Comment by dpsanders** [comment]
+1

**Comment by dpsanders** [comment]
I wonder if it would be possible to go further and have e.g. `?testimage` tell you that that is a function that lives in the `TestImage` package?  (This is what Ubuntu does when you try to run a command from the command line for which you need a package that is not yet installed, for example.)

**Comment by IainNZ** [comment]
Definitely possible, would take some thinking. Could build a cache of exported functions from installed packages, for example, that updates on Pkg.update/add. I think that'd be firmly in the PR-if-you-even-want-to-see-it category of features though :D

**Comment by ivarne** [comment]
Or we could have a script that creates an index of all functions in METADATA packages,  and commits it to METADATA. I don't think there is huge value in being able to search your own unregistered unloaded packages.

**Comment by IainNZ** [comment]
Very good point! I volunteer myself to look at making that index

**Comment by jiahao** [comment]
Creating that index sounds like an excellent use case for `JuliaParser.jl`

**Comment by ivarne** [comment]
Or just write the result of 
`names(PackageName)`

After the `using PackageName` test in PkgEvaluator.

**Comment by one-more-minute** [comment]
Happy to look at integrating an index into help if we have a sane way to build it

**Comment by IainNZ** [comment]
So a couple of things have happened over the past 24 hours:
* I've reengineered PackageEvaluator to use Vagrant VMs
  * Now we can test more packages by installing binary packages
  * Reproducible build environment!
  * I'm using the PPAs for both release and nightly right now, nightly might change back to source builds.
* I'm collecting `names(PackageName)`, which I just remembered I actually did in the past. But now its back

```json
"expnames":["AffineTransforms.rotation2","AffineTransforms.tformscale","AffineTransforms.AffineTransform","AffineTransforms.rotation3","AffineTransforms.rotationmatrix","AffineTransforms.tformrotate","AffineTransforms.rotationparameters","AffineTransforms.tformfwd3rd","AffineTransforms.tformeye","AffineTransforms.tformfwd!","AffineTransforms.tforminv","AffineTransforms.tformfwd","AffineTransforms.tformtranslate","AffineTransforms.tformrigid","AffineTransforms.tforminv!","AffineTransforms.AffineTransforms"],
```

I can mash this into any format.

I'm still getting kinks out of this new setup, so I don't have the full set, but if you want to experiment.

**Comment by one-more-minute** [comment]
Nice, the PackageEval work looks great as always. Maybe we could commit an index like that to METADATA, so that it's kept up to date with `Pkg.update()`? Then it just has to be read in and used by the doc system.

**Comment by dpsanders** [comment]
Very nice. 
Maybe a useful data structure would be a dictionary which associates to each function name an array of the packages which define that function. This could then be output to a JSON file stored in METADATA, as suggested by @one-more-minute?

**Comment by IainNZ** [comment]
Or maybe a serialized Julia dictionary

**Comment by dpsanders** [comment]
Could be, but: [OT: Is serialization even documented? I can't find it.]

**Comment by jiahao** [comment]
The serialization format is not guaranteed to be stable across builds.

**Comment by IainNZ** [comment]
Boom:
https://gist.github.com/IainNZ/3962083cc5ceb667fab4
Full lists for 0.3 and 0.4, of every package I could successfully do a `using` on.

**Comment by IainNZ** [comment]
I have no idea where to take this next. Note those files are around ~400k, although I imagine compress fantastically

**Comment by one-more-minute** [comment]
Ok, nice, and easy enough to parse aside from a couple of embedded error messages ;)

One idea I had for a slightly more compact / easy to parse format would be
```julia
Pkg1
name1
name2

Pkg2
name1
name2
```
if that makes sense.

What I'll do next is add some bits to the doc system to do nice things with this file if it exists in the local `METADATA`. Then other people can play around with it just by downloading that file.

**Comment by IainNZ** [comment]
Sure, I can do that too if you'd like.  I wonder where those error messages are coming from?!

How about I post the raw data on e.g.  `http://pkg.julialang.org/nightlynames.txt` for now and we can go from there?

**Comment by one-more-minute** [comment]
Sure, that'd be perfect – then I can even just add an option to download it.

**Comment by one-more-minute** [comment]
@IainNZ did you get a chance to put that data up? I can have a go at the package name search regardless but it would be good to give that a shot too, while I have some time.

**Comment by IainNZ** [comment]
Ah shoot I didn't. Travelling this week, will see if this airport wifi will allow it.

**Comment by IainNZ** [comment]
http://pkg.julialang.org/script/releasenames.txt
http://pkg.julialang.org/script/nightlynames.txt
Should be clean. Still in PkgName.ExportName format, but will shift to that format you proposed next week.

**Comment by KristofferC** [comment]
Kind of a dup of https://github.com/JuliaLang/Pkg.jl/issues/1397.
