### ISSUE TITLE
Julia 3.6 OSX application not signed correctly?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10276]
I just downloaded the latest stable release, double clicking the icon gives “Julia-0.3.6” can’t be opened because it is from an unidentified developer.

CC @staticfloat

**Comment by staticfloat** [comment]
I checked the RC build was doing this properly, but the actual 0.3.6-final app that I built mere hours later failed.  This happens every so often, the `codesign` tool will just refuse to use the Keychain to pull out the proper certificates.  I don't know why it starts happening and I don't know what fixes it other than logging in and unlocking the keychain manually.  In any case, this is fixed now, and I'll make doubly certain to verify the signing next release.
