### ISSUE TITLE
behavior of `all` with multiple arguments

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10271]
`all` taking a predicate and more than one additional argument is not documented but currently allowed but has a really weird behavior which seems like a bug:

```julia
julia> all(i->(4<=i<=6), [4,5,6], [0,1,2])
1-element Array{Bool,1}:
 true

julia> all(i->(4<=i<=6), [4,5,6], [0,2,3])
3-element Array{Bool,1}:
 true
 true
 true

julia> all(i->(4<=i<=6), [4,5,6], [1])
1-element Array{Bool,1}:
 true

julia> all(i->(4<=i<=6), [4,5,6], [2])
3-element Array{Bool,1}:
 true
 true
 true

julia> all(i->(4<=i<=6), [4,5,6], 1)
1-element Array{Bool,1}:
 true

julia> all(i->(4<=i<=6), [4,5,6], 2)
3-element Array{Bool,1}:
 true
 true
 true
```

Shouldn't `all` behave similarly to map (additional arguments are passed to the predicate function)?

**Comment by JeffBezanson** [comment]
I think that's one of those confusing "dimension" arguments, as in issues #4906 and #9439.
