### ISSUE TITLE
Memory utilization in complex arithmetic expressions

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10278]
The memory usage balloons once expression involving complex arithmetic becomes big:

````
julia> g(a0,a1,a2,a3,a4,x) = for i=1:10^6; f = a0 + a1*x +a2*x^2 + a3*x^3; end
g (generic function with 3 methods)

julia> @time g(1.0,1.0,1.0,1.0,1.0,1+im)
elapsed time: 0.011524283 seconds (104 bytes allocated)
````
As soon as I introduce the x^4 term, I get:
````
julia> g(a0,a1,a2,a3,a4,x) = for i=1:10^6; f = a0 + a1*x +a2*x^2 + a3*x^3 + a4*x^4; end
g (generic function with 3 methods)

julia> @time g(1.0,1.0,1.0,1.0,1.0,1+im)
elapsed time: 0.081671568 seconds (129 MB allocated, 10.74% gc time in 6 pauses with 0 full sweep)
````

**Comment by ViralBShah** [comment]
https://groups.google.com/forum/#!topic/julia-users/4GSW7C8vl1c

**Comment by timholy** [comment]
I'm having trouble finding the relevant issues, but this has been reported at least twice before. It has to do with our various limits on optimization, e.g., with tuples longer than 8 or something. Add parentheses and see if it fixes it.

This should be evaluated by Horner's method anyway, which will automatically add the parentheses and be much faster.

**Comment by ViralBShah** [comment]
Yes, I tried looking and couldn't find the relevant issue too.

**Comment by simonster** [comment]
https://github.com/JuliaLang/julia/pull/7075#issuecomment-45548446 https://github.com/JuliaLang/julia/pull/6193#issuecomment-56130501 #5011

**Comment by JeffBezanson** [comment]
Closing as dup.
