### ISSUE TITLE
Another approach for fast closures

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10288]
Similar goal to #10269, with a very different approach. I've just rewritten FastAnonymous to take advantage of stagedfunctions and call overloading: see the [calloverload branch](https://github.com/timholy/FastAnonymous.jl/tree/teh/calloverload). In brief, the strategy here is:
- encode the function/expression to be executed as a tuple and use it as a type parameter;
- a stagedfunction overloaded `call` generates an inlinable expression.

A simplified version of the strategy can be illustrated like this:
```julia
module Simple

export Fun, mymap!

immutable Fun{ext,argnames} end  # ext is the expression encoded as a tuple

Fun(ex, argnames::(Symbol...)) = Fun{expr2tuple(ex), argnames}()

stagedfunction call{ext,argnames}(f::Fun{ext,argnames}, __X__...)
    n = length(__X__)
    ex = tuple2expr(ext)   # convert back to an expression
    # unpack the entries in __X__ into the named variables, and plug them into the expression
    Expr(:block, [:($(argnames[i]) = __X__[$i]) for i = 1:n]..., ex)
end

# Some utility functions
function expr2tuple(ex::Expr)
    args = [expr2tuple(a) for a in ex.args]
    tuple(ex.head, args...)
end
expr2tuple(s) = s

function tuple2expr(t::Tuple)
    args = [tuple2expr(t[i]) for i = 2:length(t)]
    Expr(t[1], args...)
end
tuple2expr(s) = s

# And a demo function
function mymap!{ext,argnames}(f::Simple.Fun{ext,argnames}, dest, src)
    for i = 1:length(src)
        dest[i] = f(src[i])
    end
    dest
end

end
```
with the following results:
```julia
julia> using Simple

julia> f = Fun(:(x+sin(x)), (:x,))   # equivalent to f = x -> x+sin(x)
Simple.Fun{(:call,:+,:x,(:call,:sin,:x)),(:x,)}()

julia> a = rand(10);

julia> b = similar(a);

julia> mymap!(f, b, a);

julia> @time 1
elapsed time: 0.004268577 seconds (30 kB allocated)
1

julia> @time mymap!(f, b, a)
elapsed time: 1.1382e-5 seconds (80 bytes allocated)
10-element Array{Float64,1}:
 1.19225 
 1.29765 
 0.593436
 0.843164
 1.82338 
 1.55407 
 0.605003
 0.268219
 1.51561 
 0.625991

julia> x = a[1]
0.6151588925104088

julia> x+sin(x)
1.192247186695486
```
In particular, note the lack of significant allocation. Using larger inputs, you can easily convince yourself that `mymap!` runs as fast as a hand-written version where you've hard-coded in `x+sin(x)`.

The code in FastAnonymous takes this one step further: when necessary, it creates "stagedtypes" that encode an environment storing any variables not supplied as arguments. For example:
```julia
julia> using FastAnonymous   # must be on the calloverload branch

julia> a = 4.2
4.2

julia> f = @anon (x,y) -> x+a*y
(x,y) -> quote  # none, line 1:
    Main.+(x,Main.*(a,y))
end
with:
  a: 4.2

julia> f(1,2)
9.4

julia> f.a = -7
-7.0

julia> f(1,2)
-13.0

julia> f
(x,y) -> quote  # none, line 1:
    Main.+(x,Main.*(a,y))
end
with:
  a: -7.0

julia> a = -7
-7

julia> f = @anon (x,y) -> x+a*y
(x,y) -> quote  # none, line 1:
    Main.+(x,Main.*(a,y))
end
with:
  a: -7                 # <- note this is an Int, not a Float64

julia> f(1,2)
-13                     # an Int
```

Compared to the old approach taken by FastAnonymous, I think this is much closer to what we'd really want from a closure:
- For a given set of environment variable _types_, it only creates one new type (it reuses previously-generated types if you use `@anon` again).
- Consequently much-reduced construction time for `@anon` objects
- There's no negative consequence for garbage collection
- You can update an `anon` object by altering the values stored in its fields

There's one showstopper bug, however: currently the return type is not inferred correctly. Obviously this is different from the `Simple` module up above, and the reason comes down to those `Main.+` scoped calls above. I've spelled out the problem in #10287. If the user has defined a function (like the `to_gray` example in the tests for FastAnonymous), then I found I needed to add explicit module scoping---the `call` overloading is not in a macro scope anymore, obviously, so `esc` doesn't solve the problem.

**Comment by JeffBezanson** [comment]
Very clever hack. Clearly we need a good approach built in; the discussion in #10269 covers the design options.

**Comment by timholy** [comment]
I guess what I thought was most interesting about this is that you don't need to give each function its own separate type, it all comes down to parameters.

**Comment by timholy** [comment]
If you ever wondered whether we've given ourselves enough rope to hang ourselves with, the answer appears to be "yes." :smile: The final version seems to work really nicely, and has only 141 lines of "real" code; however, the implementation is [positively terrifying](https://github.com/timholy/FastAnonymous.jl/commit/b745d3e57e149d37c7fdde8f98a717514cba4ede). So much for the barriers between types and values...
