### ISSUE TITLE
Add header option to writedlm() and related

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#10284]
Sometimes we need to attach extra information to the data we're dumping:

``` julia
writecsv("foo.dat", data, header="This is the data...\nMeta info: ...")
```

Currently this is not possible.

**Comment by simonster** [comment]
You can do this with:

```julia
f = open("foo.dat", "w")
write(f, "This is the data...\nMeta info: ...\n")
writecsv(f, data)
close(f)
```

**Comment by juliohm** [comment]
@simonster, that is a workaround, but you agree such header option would be useful?

**Comment by JeffBezanson** [comment]
Adding a keyword argument for this when it can easily be done by composing existing functions seems pretty "featurey" to me.

**Comment by juliohm** [comment]
I think it's much more comfortable to the user and a very common task too.

-Júlio

**Comment by JeffBezanson** [comment]
I guess I have a different philosophy here. Yes it's a bit easier when you know about the option, but adding options eventually has a complexity cost.

**Comment by juliohm** [comment]
@JeffBezanson, I opened the issue because I'm used to [numpy.savetxt()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html), maybe there is another function in Julia with the same purpose?

**Comment by JeffBezanson** [comment]
Ok, well if people feel this is a reasonable and standard option then I don't object too strongly.

**Comment by nalimilan** [comment]
Yes, since it's supported by Numpy I think it's good to have to make the transition easier and not let people think "Julia is less practical than $X". Also the code required to support this quite simple.

**Comment by ViralBShah** [comment]
I think this is quite reasonable and a feature I would expect too.

**Comment by juliohm** [comment]
What is the status of this issue?

**Comment by tkelman** [comment]
Not yet implemented by anyone. Sounds like Jeff's objection isn't too strong, so a pull request would be considered.

**Comment by juliohm** [comment]
I started hacking the code, there are two redundant options called header and has_header? Is that correct?

https://github.com/JuliaLang/julia/blob/master/base/datafmt.jl#L284

Can we use `header` for the string and `has_header` for the boolean?

**Comment by tanmaykm** [comment]
`has_header` is deprecated in favor of `header` (https://github.com/JuliaLang/julia/blob/20786d285211955f506664c851c79b8208439d53/base/datafmt.jl#L286).

Will a boolean be necessary when the header strings are specified?

**Comment by juliohm** [comment]
Thank you @tanmaykm.

What is a good name for an option that holds the header string? header_stringr?

**Comment by juliohm** [comment]
Could you please review this pull request? https://github.com/JuliaLang/julia/pull/13887

**Comment by juliohm** [comment]
Anything that needs to be improved in the code?

**Comment by tanmaykm** [comment]
Thanks. The option name `header_string` seems a bit long to me.
How about calling it `names` instead, in-line with what `DataFrames` has.

**Comment by nalimilan** [comment]
`names` doesn't sound ideal, as the header can be used for anything, not just names. Wouldn't it be possible to call it simply `header`, since there's no ambiguity with `readdlm`?

**Comment by juliohm** [comment]
@tanmaykm, I agree with @nalimilan and think that  `names` is not adequate here. I also agree with his observation on ambiguity and would like to ask if others are okay with having `header` as a string option for `writedlm` and boolean for `readdlm`.

Can I change `header_string` to `header` in `writedlm`?

I'll add docs and tests immediately after it is done.

**Comment by juliohm** [comment]
Can someone add the tag `up for grabs` on this issue?

**Comment by wookay** [comment]
How about `writecsv` with `Tuple` type.

something like that
```Julia
function Base.writecsv(io, t::Tuple{Array,Array}; opts...)
    (data_cells, header_cells) = t
    f = open(io, "w")
    writecsv(f, header_cells; opts...)
    writecsv(f, data_cells; opts...)
    close(f)
end
```

it gives more consistent ways with header.
```julia
(a, header) = readcsv("foo.csv", header=true)
writecsv("bar.csv", (a, header), header=true)
(a, header) == readcsv("bar.csv", header=true)
```

thanks.

**Comment by juliohm** [comment]
Rethinking about this issue, I believe there is no much gain in adding a header option to writecsv. The code @simonster showed is clean and we can easily wrap it in a function if we need a one-liner. I am closing this issue, please feel free to reopen if necessary.
