### ISSUE TITLE
Inference problem across module boundaries?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10287]
I'm trying to scope a call to a function defined in a different module, and I'm seeing a failure of type inference. Here's a demo:

```julia
module Broken

import Base.call

export F, G

immutable F end
immutable G end

stagedfunction call(::F, X...)
    ex = :(x^2)
    @show ex
    Base.Meta.show_sexpr(ex)
    Expr(:block, :(x = X[1]), ex)
end

stagedfunction call(::G, X...)
    ex = Expr(:call, Expr(:., :Main, QuoteNode(:^)), :x, 2)
    @show ex
    Base.Meta.show_sexpr(ex)
    Expr(:block, :(x = X[1]), ex)
end

end
```
with results
```julia
julia> using Broken

julia> f = F()
Broken.F()

julia> f(3.2)
ex = :(x ^ 2)
(:call, :^, :x, 2)10.240000000000002

julia> Base.return_types(f, (Float64,))
ex = :(x ^ 2)
(:call, :^, :x, 2)1-element Array{Any,1}:
 Float64

julia> g = G()
Broken.G()

julia> g(3.2)
ex = :(Main.^(x,2))
(:call, (:., :Main, (:quote, #QuoteNode
      :^
    )), :x, 2)10.240000000000002

julia> Base.return_types(g, (Float64,))
ex = :(Main.^(x,2))
(:call, (:., :Main, (:quote, #QuoteNode
      :^
    )), :x, 2)1-element Array{Any,1}:
 Any
```
Is this an inference bug, or some problem with my code?

**Comment by JeffBezanson** [comment]
The `Main` identifier exported by `Core` is actually not a constant, since the Main module can be changed. You probably want to use `Base` instead.

**Comment by JeffBezanson** [comment]
One solution is to plug in the exact module you want, i.e. `Main` instead of `:Main`.

**Comment by timholy** [comment]
Can't use modules in type parameters, which is the main point of this (#10288).

I'll have to think about this a bit more, but I'm not sure I see a resolution without some other kind of change. Presumably any user-loaded module would have the same non-const issue as `Main` does.

**Comment by JeffBezanson** [comment]
No, modules get const bindings by default.

**Comment by JeffBezanson** [comment]
There are certainly forces working against you when you try to process source expressions from a staged function. They just aren't designed for that.

**Comment by timholy** [comment]
I realized that I probably don't really need to put the entire AST into the parameters: just put in a UUID so each one dispatches differently. Store the AST in an `.ast` field.

AFAICT this is then basically an implementation of your `Closure` type in https://github.com/JuliaLang/julia/pull/10269#issuecomment-75389370. Right?
