### ISSUE TITLE
Ternary operator in multiple lines

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#10291]
The parser fails with the ternary operator in two lines:

```julia
foo = 1 > 0 ? 1
            : 0
```
>ERROR: syntax: colon expected in "?" expression

**Comment by sjkelly** [comment]
You just need to put the colon on the same line:
```
julia> foo = 1 > 0 ? 1 :
       0
1
```

**Comment by jiahao** [comment]
Alternatively, you can use parentheses:

```
julia> foo = (1 > 0 ? 1
      : 0)
1
```

**Comment by juliohm** [comment]
I mean, this is intended behavior? We really need the parenthesis there?

**Comment by IainNZ** [comment]
Maybe you could argue that the the parser, having seen a `?`, but not a `:`, should keep looking until it finds one I suppose. I think the current behavior is the C behaviour (but my memory might be shakey)

**Comment by juliohm** [comment]
@IainNZ C allows the break before the semicolon:

```C
int main()
{
    int foo = 1 > 0 ? 1
                    : 0;
}
```

**Comment by jiahao** [comment]
I think the current behavior is simply what the parser currently gives us.

Related: #6823 #9180

**Comment by StefanKarpinski** [comment]
There's also been some discussion of allowing just the `?` without the `:` to mean something (forget the issue), although I didn't really care for it myself.

**Comment by quinnj** [comment]
Yeah, I was a bigger fan of allowing single line if-then statements, so you
could do

if x then y

instead of

if x; y; end

**Comment by JeffBezanson** [comment]
Yes, that is #6823. Even if we don't adopt the `x ? y` syntax, it's good that we erred on the side of leaving it open instead of allowing every combination of whitespace. I don't see the value of putting the `:` on the next line.
