### ISSUE TITLE
OpenBLAS v0.2.13 checksum mismatch

### ISSUE THREAD

**Issue by ozancaglayan** [JuliaLang/julia#10295]
Hi,
When I try to build Julia for the release-0.3 branch, the downloaded OpenBLAS tarball has different checksums from what is written in deps/checksums/openblas-*. I also manually downloaded the tarball from OpenBLAS github and they are different too. The tarballs downloaded are not corrupted, they can be extracted correctly so I think the checksums are either wrongly written in Julia repository or OpenBLAS released another tarball just after 0.2.13 without bumping their version.

**Comment by nalimilan** [comment]
That's weird. I just downloaded https://github.com/xianyi/OpenBLAS/tarball/v0.2.13, and the checksum matches:
```
$ sha512sum deps/openblas-v0.2.13.tar.gz 
e3c8d3f7c7f9593a863cba2679f3cf5872138b0aa0f2a61cac15901364489c9a6bff0c166813d154bc0d91118302585ac1340eaaeb7dc11c8aad92757bbf86ba  deps/openblas-v0.2.13.tar.gz
```

Maybe the NSA is spying on you... :-)

How do you download the tarball?

**Comment by ozancaglayan** [comment]
hmm that's interesting. I downloaded using the following link which is also used by `deps/Makefile` but you mention about `tarball/v0.2.13` above which has apparently different checksum:
 https://github.com/xianyi/OpenBLAS/archive/v0.2.13.tar.gz

**Comment by nalimilan** [comment]
Ah, funny. OpenBLAS gives two different URLs with different tarballs. I've filed an issue against OpenBLAS here: https://github.com/xianyi/OpenBLAS/issues/506

Out of curiosity, why did you need to download the tarball manually? Is there something wrong with Julia's build process?

**Comment by ozancaglayan** [comment]
Well Julia didn't build OpenBLAS because of this checksum mismatch :))

**Comment by nalimilan** [comment]
You mean that it downloaded the wrong tarball on its own?

**Comment by ozancaglayan** [comment]
The checksums written in the repository are computed against the tarball downloaded using `/tarball/` URL but the Makefile downloads tarball with `/archive/` URL so they mismatch.

**Comment by tkelman** [comment]
This was caused by https://github.com/JuliaLang/julia/commit/526429db4f27c863358be38ca1201edc9ab53a5b - I would not expect we'd need to change the checksums due to that change, but apparently we do.

**Comment by nalimilan** [comment]
Ah, @staticfloat just changed the URL to `/archive/` in https://github.com/JuliaLang/julia/commit/526429db4f27c863358be38ca1201edc9ab53a5b . I've updated the checksums.

But that's only on master, not on `release-0.3`. A backport would limit the problems when switching branches.

**Comment by nalimilan** [comment]
@tkelman Should we backport both commits?

**Comment by tkelman** [comment]
we could but I don't think we need to?

**Comment by nalimilan** [comment]
Apparently, @ozancaglayan observed the bug in release-0.3 even if the change wasn't present there: that' can happen if the tarball was downloaded from master, but OpenBLAS was only built on release-0.3. Looks quite unlikely, though -- not sure how it happened.

**Comment by tkelman** [comment]
It would depend on whether we download and checksum in the same step, or do them separately - I don't remember exactly which we do, but easy enough to look and see.

**Comment by nalimilan** [comment]
We do them separately, that's the problem. We could check right after downloading, but then what should be done if the check fails? Removing the tarball would prevent inspection to understand what went wrong.

We can also leave it as-is and hope not too many people end up in that situation.

**Comment by staticfloat** [comment]
I think we should backport it.  I did not imagine this would cause a checksumming issue, but apparently it does.  This was done in anticipation of my using the caching infrastructure for `jldownload`, and I think that'll be extra useful on release branches, where the tarballs are older and might disappear off of the interwebs.

**Comment by tkelman** [comment]
backported in a767b22ac3f50923c4b69b81aac12615f76e8d99 and 50e94fdadeacfb3de23f026ae99178e769551068
