### ISSUE TITLE
don't invoke user-level callbacks directly from libuv callbacks

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10293]
While trying to write a `tail -f`, came across the following issue:
In one terminal, start a process that appends to a file

```
io = open("/tmp/a.txt", "w+")
while true
    for i in 0:9
        write(io, "$i\n")
        sleep(0.1)
        flush(io)
    end
    write(io, "\n")
    sleep(5)
end
```

In another, the tail -f 

```
type TailF
    f::IO
    pos::Int
end

function cb(tf)
    nsize = stat(tf.f).size
    if nsize > tf.pos
        try
            b = read(tf.f, UInt8, nsize - tf.pos)
            s = bytestring(b)
            print("<<$(current_task())>> $s")
            tf.pos = nsize
        catch e
            print("<<$(current_task())>> $e $(tf.pos) $nsize \n")
        end
    end
end

tf = TailF(open("/tmp/a.txt"), 0)
watch_file((fname, event, status)->cb(tf), "/tmp/a.txt")
```

This results in an error the first time around - and from the looks of it, the callback `cb` is called again (in the same task) due to the `print` command. 

If the print statement is moved after we update state, like this, 

```
            tf.pos = nsize
            print("<<$(current_task())>> $s")
```

it works fine.

Can we ensure that `watch_file` does not execute the callback again till a previous one has returned?

**Comment by vtjnash** [comment]
we should probably document/enforce that direct callbacks (from libuv) may not themselves block or yield

**Comment by amitmurthy** [comment]
Is it not possible to queue callbacks so that the above problem does not occur? Quite a few times I have come across situations where a problem goes away in the presence of a "debug" println statement. 

We could implement the queuing support external to libuv via a "callback wrapper" which does the queuing.

**Comment by vtjnash** [comment]
well, that's what the whole Task infrastructure does. the direct callback exposed here is really just a lower-level hook to implement that

**Comment by amitmurthy** [comment]
No, I meant providing support for something like this in Base
 
```
real_cb(x,y,z) = ......
locked_cb(x,y,z) = begin
  get_lock(some_obj)
  real_cb(x,y,z)
  release_lock(some_obj)
end
```

We need to provide the ability to lock/unlock any object, so that users can easily create anonymous wrappers that result in queued execution of callbacks.

**Comment by amitmurthy** [comment]
And not yielding from a callback may be a straightforward  option every time. In the "tail -f" example above, the requirement was for reading file changes and writing it to stdout or another socket.

Better to provide a means for users to do this in a safe manner.

**Comment by vtjnash** [comment]
yes, i agree. but Tasks already are that thing. the callback just needs to add the appropriate Tasks back to the scheduler's workqueue and return. most libuv objects exposed by julia already handle this.

i do something like that to mess with the stack in Gtk to try to keep some of it's stack-allocations safe in case the user does a recursive call to gtk_run: https://github.com/JuliaLang/Gtk.jl/blob/master/src/GLib/signals.jl#L124-L278

**Comment by amitmurthy** [comment]
Just so I understand correctly - the correct method of doing IO from a callback is by executing the IO in a separate task? For example,  a `@schedule` block?

**Comment by JeffBezanson** [comment]
We should not use user functions as direct libuv callbacks. Libuv callbacks should only exist internally, and generally should just cause tasks to be restarted. For something like polling with a callback interface, we should start a Task that looks like

```
@task begin
    while true
        wait(event)
        user_callback(...)
    end
end
```

**Comment by JeffBezanson** [comment]
@amitmurthy yes.

**Comment by vtjnash** [comment]
> We should not use user functions as direct libuv callbacks. Libuv callbacks should only exist internally, and generally should just cause tasks to be restarted. For something like polling with a callback interface, we should start a Task that looks like

as we move towards a threaded interface, i think that this makes increasing sense.

in most cases, methods like `watch_file` should be returning an object that the user can `wait` on, with the function form available mostly as an internal detail, or if the user really needs to do something faster and wants to plug into that internal interface. i think the whole file polling infrastructure has been waiting for a complete review to fix a few deeper API bugs

**Comment by JeffBezanson** [comment]
> needs to do something faster and wants to plug into that internal interface

Not recommended!!!

**Comment by vtjnash** [comment]
fixed
