### ISSUE TITLE
`checked_mul` has no method matching checked_mul(::Int64, ::Base.GMP.BigInt)

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julia#10311]
Julia **0.3.6**:

```julia
julia> n//n + n//big(n)*im
1//1 + 1//1*im

julia> typeof(ans)
Complex{Rational{BigInt}} (constructor with 1 method)
```

Julia **0.4.0-dev+**:

```julia
julia> n//n + n//big(n)*im
ERROR: MethodError: `checked_mul` has no method matching checked_mul(::Int64, ::Base.GMP.BigInt)
Closest candidates are:
  checked_mul(::Int64, ::Int64)
  checked_mul(::Base.GMP.BigInt, ::Base.GMP.BigInt)

 in + at rational.jl:166
 in + at complex.jl:118
```

* Test logs:

    * [Linux 64 bits 0.3.6](https://travis-ci.org/Ismael-VC/AHN.jl/jobs/52009177) (this one passes)
    * [Linux 64 bits 0.4.0-dev+3577](https://travis-ci.org/Ismael-VC/AHN.jl/jobs/51998218)
    * [Windows 32 bits 0.4.0-dev+3578](https://ci.appveyor.com/project/Ismael-VC/ahn-jl/build/job/j6thki13rxyyn2x2)
    * [Windows 64 bits 0.4.0-dev+3578](https://ci.appveyor.com/project/Ismael-VC/ahn-jl/build/job/0k1pqjth94qya4fh)

**Comment by JeffBezanson** [comment]
We should add promotion to `checked_mul`.
