### ISSUE TITLE
standalone numbers test fails under Linux 64-bit

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10322]
```
amitm@amitm-laptop:~/julia/julia/test$ julia runtests.jl numbers
     * numbers             LLVM ERROR: Do not know how to split the result of this operator!
```

Under a multi environment, it works
```
amitm@amitm-laptop:~/julia/julia/test$ julia runtests.jl numbers keywordargs
        From worker 3:       * keywordargs          in   1.73 seconds
        From worker 2:       * numbers              in  23.26 seconds
    SUCCESS
```

build:
```
julia> versioninfo()
Julia Version 0.4.0-dev+3596
Commit f8e7783 (2015-02-25 10:35 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
Odd, works for me on Ubuntu 14.04. Anything strange in your `Make.user`? Or it could be something specific to a newer cpu type than I have.

**Comment by amitmurthy** [comment]
Make.user is empty. A `make cleanall` didn't help either. This system is Ubuntu 14.04 too, Ubuntu 14.04.2 LTS to be exact.

**Comment by rickhg12hs** [comment]
Any extra info executing the test from the REPL?

```julia
julia> using Base.Test

julia> include("test/numbers.jl")
```

**Comment by amitmurthy** [comment]
I just realized that the SSD (with Ubuntu installed) in this machine (Core-i5) came from a machine that had a Core-i7

I'll rebuild llvm and try it again.

**Comment by amitmurthy** [comment]
@rickhg12hs no extra info. Rebuilding llvm didn't help either. Closing this for now - seems to be a problem only on this particular local environment.
