### ISSUE TITLE
Rename `names` to `fields` or `fieldnames`?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10325]
It has been brought up in a couple of discussions that it would be useful to overload the meaning of `names` for user defined types, but it's current meaning in `Base` (return a array of symbols for field names of a given type) kind of prevents this (you would assume `getfield(T, fieldnames(T)[1])` works).

Possible suggestions were to rename `names` to `fields` or `fieldnames`.

**Comment by ivarne** [comment]
+1

**Comment by JeffBezanson** [comment]
+1 `fieldnames` is good; we already have `fieldoffsets`.
