### ISSUE TITLE
nested ifelse not giving computed gotos

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#10320]
From #5410: LLVM should be able optimise certain chains of `ifelse` statements into computed gotos. However the examples mentioned in that issue no longer work, e.g. 

``` julia
function foo(x)
    if x == 1
        x * 7
    elseif x == 2
        x * 8
    elseif x == 3
        x * 9
    elseif x == 4
        x * 10
    elseif x == 5
        x * 11
    elseif x == 6
        x * 12
    elseif x == 7
        x * 13
    elseif x == 8
        x * 14
    elseif x == 9
        x * 15
    elseif x == 10
        x * 16
    elseif x == 11
        x * 17
    else
        x * 0
    end
end
code_native(foo, (Int,))
```

gives a sequence of `cmp`/`jne` instructions.

**Comment by yuyichao** [comment]
It's an LLVM issue. LLVM is smart enough to generate switches (i.e. jump tables) for a few cases I've tested (even triggering a bug that needs to be [workarounded](https://github.com/JuliaLang/julia/pull/22451)). For the code shown above, llvm is smart enough to optimize it as

```julia
if x - 1 < 11
    return statically_computed_results[x]
else
    return 0
end
```

**Comment by ihnorton** [comment]
I think @simonbyrne's code was mostly for demonstration purposes...

**Comment by yuyichao** [comment]
That's why I first addressed the general case.

**Comment by simonbyrne** [comment]
Which version of LLVM is it fixed in?

**Comment by yuyichao** [comment]
Not sure, I'm using 4.0.

**Comment by StefanKarpinski** [comment]
Julia 0.6 and 0.7-DEV both produce native code using LLVM 3.9.1:

```asm
	.section	__TEXT,__text,regular,pure_instructions
Filename: REPL[111]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 2
	leaq	-1(%rdi), %rax
	cmpq	$10, %rax
	ja	L31
	movabsq	$4745995008, %rax       ## imm = 0x11AE22300
	movq	-8(%rax,%rdi,8), %rax
	popq	%rbp
	retq
Source line: 3
L31:
	xorl	%eax, %eax
	popq	%rbp
	retq
	nopw	%cs:(%rax,%rax)
```
