### ISSUE TITLE
svds does not support specifying initial guess vector v0 

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10330]
v0 is used as the initial value for seeding the eigs computations and is supported by `eigs()`

**Comment by ViralBShah** [comment]
The v0 has to be transformed so that it can be passed to the augmented system that is being solved.

**Comment by jiahao** [comment]
`svds` calls `eigs` on `[0 T; T' 0]`, so `v0` can be
- a specified vector of size `(m+n)` (for `T` of size `(m, n)`, which a starting guess for both the left vector and the right vector (the current default),
- a specified vector of size `m` being the starting guess for the left vector - the underlying `eigs` routine should get `[v0; zeros(n)]`.
- a specified vector of size `n` being the starting guess for the right vector - the underlying `eigs` routine should get `[zeros(m); v0]`.

The `m==n` case is ambiguous, so it might be best to specify each case (specified left vector only, specified right vector only, or both) with its own keyword.

**Comment by andreasnoack** [comment]
Fixed by #16283
