### ISSUE TITLE
Offset calculation in suitesparse_wrapper

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#10347]
I think that the way we are calculating the offsets in suitesparse_wrapper.c is broken because the offsets are calculated for the machine where `suitesparse_wrapper.c` is compiled. These offsets need not be the same when Julia is from a repository because the version of SuiteSparse can be different from the machine where the package was build.

This can be seen on Julia release on Ubuntu where CHOLMOD objects are printed wrongly because the print level is set in specific location in a vector and this location has changed over time because the cholmod_common_struct has changed over time.

**Comment by andreasnoack** [comment]
@staticfloat I tend to think that this is mainly a packaging issue. The suitesparse_wrapper shim is correct when build together with the linked SuiteSparse, but not when the library is substituted. Do you know how we can handle this?

**Comment by dmbates** [comment]
If the `libcholmod` is sufficiently recent to have a `cholmod_version` function then you can pass version_arrayi to calls to functions defined in `SuiteSparse_wrapper.c` and compare the three integers to CHOLMOD_MAIN_VERSION, CHOLMOD_SUB_VERSION and CHOLMOD_SUBSUB_VERSION.  If they don't match then all bets are off.  Also, if the version of cholmod in the shared library is too old to have a `cholmod_version` function then all bets are off.

**Comment by andreasnoack** [comment]
We should check this when Julia is launched, and, as mentioned in the other issue, not (only) when the system image is build, but I don't how to do that.

**Comment by ivarne** [comment]
See https://github.com/JuliaLang/julia/blob/32aee08d0b833233cd22b7b1de01ae769395b3b8/base/gmp.jl#L54, for a partially working solution. The only problem is that the `error` is misleading,  as it won't terminate the program, but just print a warning.

**Comment by andreasnoack** [comment]
@ivarne Thanks. That was exactly what I was looking for.

**Comment by andreasnoack** [comment]
I think the best we can do here is #10362, so I'll close.
