### ISSUE TITLE
overloads for combinatorics.jl methods that accept rng's as parameters

### ISSUE THREAD

**Issue by kyle-pena-nlp** [JuliaLang/julia#10345]
It would be cool if we had some overloads for functions in combinatorics.jl (like randperm and shuffle) that accept an rng as an argument.

Using the global rng works fine 99% of the time, but that 1%!  Gah!

Here's a contrived example:

`# seed the global rng`
`srand(42)`

` # do something random a non-deterministic number of times` 
`for line in lines_in_a_file shuffle(collect(1:10)) end`

`# later, do a shuffle on something unrelated`
`shuffle(collect(1:10))`

Global seeding is great, but if you invoke rand() a non-deterministic number of times... well the global rng is a non-deterministic state there on out, so you can't really get deterministic behaviour out of it  unless you reinitialize it like so: `srand(42)`.

I guess that's fine, but doesn't that approach break down when you get into distributed computation?

Anywho, I'm trying to make a case for always including overloads that accept an rng, in any method, not sure how successful the point is coming across.

I'm happy to pick it up as an issue unless someone else would rather give it a shot.

**Comment by simonbyrne** [comment]
Yes, I would like to see all methods which use `rand` accept an RNG as an argument: see #8786.
