### ISSUE TITLE
resize! and reinterpret

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#10354]
hi,

first, apologies in advance.  there's been some discussion on this issue and i seem to be the only one not understanding the explanations, so i may just be being dumb.

but the probem is this:

```
julia> a = b"1234"
4-element Array{UInt8,1}:
 0x31
 0x32
 0x33
 0x34

julia> resize!(a, 2)
2-element Array{UInt8,1}:
 0x31
 0x32

julia> resize!(a, 4)
4-element Array{UInt8,1}:
 0x31
 0x32
 0x00
 0x34

julia> reinterpret(UInt32, a);


julia> resize!(a, 2)
ERROR: cannot resize array with shared data
 in resize! at ./array.jl:545
```

which was raised in a bug report for my crc lib https://github.com/andrewcooke/CRC.jl/issues/4 and then discussed at https://groups.google.com/forum/#!topic/julia-users/AQMw0-8SUU4

i guess my problems are:

 1 - i don't understand why this error happens.  surely if some idiot goes and resizes an array they should know that previous references could be broken.  the system shouldn't protect them from it.

 2 - if i'm wrong and the system should protetct them from it, then there should also be some way to say that the problematic reference is now out of scope.  how can my library (which had the temerity to call reinterpret on an argument) say "ok, i no longer care about this array, you can resize it if you want"?

 3 - i don't understand the comments about pointers that appear in the links i gave.  do pointers exist in julia or is this some low level c stuff?  if the latter, why on earth should i need to know about that?

 4 - whatever the answer is, could it be documented somewhere?

thanks,
andrew

**Comment by stevengj** [comment]
@andrewcooke, in general Julia intends to be memory-safe except for functions like `unsafe_load` and other manipulations of raw pointers.  (Raw pointers exist in Julia and can be manipulated, mainly for C interop.   The mentions of "pointers" in the linked threads were just informal descriptions of object references, though, I think, not of raw pointers.)   So, yes, Julia can and should protect against people breaking one reference to data by resizing another reference.

In this particular case, as you say, the problematic reference is out of scope, so in principle there should be some way to ignore it, but I don't think that is currently possible (without resorting to low-level pointer manipulation).

**Comment by andrewcooke** [comment]
thanks for the reply (i re-read my question and it seems oddly aggressive which wasn't intentional).

it seems there's something more to "having a reference" than simply having a name that points to a value.  because

```
julia> a = b"1234"
4-element Array{UInt8,1}:
 0x31
 0x32                                                                           
 0x33                                                                           
 0x34                                                                           
                                                                                
julia> b = a
4-element Array{UInt8,1}:                                                       
 0x31                                                                           
 0x32                                                                           
 0x33                                                                           
 0x34                                                                           
                                                                                
julia> b[3]
0x33                                                                            
                                                                                
julia> resize!(a, 2)
2-element Array{UInt8,1}:
 0x31
 0x32

julia> b[3]
ERROR: BoundsError: attempt to access 2-element Array{UInt8,1}:
 0x31
 0x32
  at index [3]
```

"works" how i would expect having "a reference" to a resized array to "work".

anyway, i agree a way to mark out-of-scope would be nice.

also, in https://github.com/andrewcooke/CRC.jl/issues/4 there's talk of working around the problem by "passing a pointer".  do you know what that would mean?

**Comment by stevengj** [comment]
In your second example, `b` and `a` are just names for the same `Array` object in memory, so resizing `a` changes `b`.  In contrast, if you use `reinterpret`, you create a second `Array` object (of a different type), with a pointer to the same memory as the first array.

**Comment by andrewcooke** [comment]
OK, so maybe the docs could say something like:

> Julia arrays associate an area of memory with some metadata (containing information on array size, contents, etc).  For efficiency, some operations (like `reinterpret`) create a new array, with new metadata, that shares the same memory area.

> Using `resize!` changes both memory and metadata.  Since this would cause unpredictable errors when the shared memory is accessed from another array Julia arrays keep track of whether or not they have shared memory areas.  The `resize!` operation is then only possible if the memory is unshared.  Trying to resize an array with shared memory gives `ERROR: cannot resize array with shared data`.

> Unfortunately there is no mechanism for tracking the lifetime of arrays, so once memory has been shared, it can never be resized (even when the array that shares the memory area no longer exists).

where I've tried to avoid using "pointer" since that requries clarifying the difference between Julia and C levels (imho).

**Comment by KristofferC** [comment]
Seems to work now:

```
julia> a = b"1234"
4-element Array{UInt8,1}:
 0x31
 0x32
 0x33
 0x34

julia> resize!(a, 2)
2-element Array{UInt8,1}:
 0x31
 0x32

julia> resize!(a, 4)
4-element Array{UInt8,1}:
 0x31
 0x32
 0x00
 0x34

julia> reinterpret(UInt32, a);

julia> resize!(a, 2)
2-element Array{UInt8,1}:
 0x31
 0x32
```

**Comment by yuyichao** [comment]
It's an artifact of the `StringVector` since the data owner is not the array anymore. Note that the use in CRC.jl is invalid and we will not allow what the original report want to do. We can allow explicit in-scope unshare (so the caller of `reinterpret`/`reshape` can explicitly state that the point won't be shared anymore) or remove this function from `Array` altogether but that's a separate issue.

**Comment by ChrisRackauckas** [comment]
Looks like this happens with other arrays still, and it happens when the `reinterpret`ed array is out of scope.

```julia
function ff()
  a = [1,2,3,4]
  resize!(a, 2)
  resize!(a, 4)
  b = reinterpret(UInt32, a);
  a
end
function g(a)
  resize!(a, 2)
end
a = ff()
g(a)
```
