### ISSUE TITLE
make `workspace()` reload `.juliarc.jl`

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#10351]
In the manual/FAQ/discussions, `workspace()` is the recommended way of getting a "clean slate", that should be equivalent to restarting Julia (except for `LastMain` etc).

Arguably, `workspace()` then should also reload `.juliarc.jl` in certain cases.

For example, having an optional `reload-startup` argument would make sense, with the following options:
1. `:auto`, which is the default. Reload unless the process was started with `--startup-file=no`, or `-f`.
2. `false`: never reload.
3. `true`: reload unconditionally.

**Comment by tpapp** [comment]
In fact, it would be even nicer if there was a more general mechanism to reload code after a call to `workspace()`. For example, [ESS](https://github.com/emacs-ess/ESS) defines a module `ESS` it uses for interacting with the inferior Julia process, which gets wiped out after `workspace()`.

A solution could be defining a variable `workspace-hook`, which would be a vector of functions (possibly anonymous) that would be called by `workspace()`. ESS-like interfaces would just add to this hook (possibly with an API).

**Comment by ihnorton** [comment]
Related: https://github.com/malmaud/Autoreload.jl

**Comment by ihnorton** [comment]
crossref #6445

**Comment by tlycken** [comment]
crossref #12314
