### ISSUE TITLE
how to lookup  deprecated functions ?

### ISSUE THREAD

**Issue by songroom** [JuliaLang/julia#10359]
julia has a function to lookup  deprecated functions ? it will help sb to fix it .
thank you!

**Comment by stevengj** [comment]
If you mean that you want a list of deprecated functions, you can look in [base/deprecated.jl](https://github.com/JuliaLang/julia/blob/master/base/deprecated.jl).

However, note that Github issues are not for asking general questions, they are for filing bug reports or feature requests; if you have general questions you should ask them on the julia-users mailing list.

**Comment by songroom** [comment]
thank you

**Comment by kmsquire** [comment]
This could be considered a request for such a function for people who are not used to digging through the Julia source.  I could imagine such a function being useful interactively.

**Comment by stevengj** [comment]
What is the use of a function that returns a list of deprecated functions, if I understand @kmsquire's interpretation correctly?

**Comment by kmsquire** [comment]
Might be useful if one is attempting to find and fix all such deprecations in code where not all code paths are commonly used or well tested.
