### ISSUE TITLE
Did something change with `ceil` on Julia 0.3.6?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#10363]
PackageEvaluator has been dead for a while, so I'm not sure if this is a false alarm. I've noticed a couple of packages failing due to things related to `ceil`:

* `ERROR: `ceil` has no method matching ceil(::Type{Integer}, ::Float64)` (http://pkg.julialang.org/?pkg=SortingAlgorithms&ver=release)
* ``` `iceil` has no method matching iceil(::Type{Integer}, ::Array{Float64,2})``` (http://pkg.julialang.org/?pkg=FunctionalData&ver=release)

Any reason to be worried?

**Comment by jiahao** [comment]
Looks like `ceil(Int, 3.8)` works on release-0.3 but not 0.3.6.

`iceil` is deprecated in 0.4 but I don't think that method signature was ever defined in base.

**Comment by tknopp** [comment]
```
julia> iceil(3.8)
4
```

(julia 3.4). I wonder why `iceil` and more importantly `ifloor` should be deprecated. Do they hurt?

**Comment by simonster** [comment]
`ceil(Int, x)` was added and `iceil(x)` was deprecated in #9133. `ceil(Int, x)` for Julia 0.3 is implemented in Compat. (It doesn't work for me on either 0.3.6 or release-0.3 without Compat loaded.)

As far as I can tell, nothing changed in Julia 0.3.6. Rather, there was a new release of SortingAlgorithms that looks like it needs to use Compat, and the FunctionalData issue should be resolved by JuliaLang/Compat.jl#45.

**Comment by IainNZ** [comment]
Sounds good, thats what I thought it might be but wanted to be sure
