### ISSUE TITLE
Parsing inconsistencies between single line and multiline versions of a same expression

### ISSUE THREAD

**Issue by dg2** [JuliaLang/julia#10366]
Hi, I was trying to use the [KUnet](https://github.com/denizyuret/KUnet.jl) library in Julia Version 0.3.6 (2015-02-17 22:12 UTC) in OS X. The following function
```
adagrad!(eps, dw2, dw)=(for i=1:length(dw) (dw2[i] += dw[i] * dw[i]; dw[i] /=  (eps + sqrt(dw2[i]))) end)
```
fails with: ERROR: syntax: invalid keyword argument syntax "dw[i]/=+(eps,sqrt(dw2[i]))" (expected assignment)

I can make it work by rewriting it across several lines
```
adagrad!(eps, dw2, dw) = for i=1:length(dw) 
    dw2[i] += dw[i] * dw[i] 
    dw[i] /=  (eps + sqrt(dw2[i])) 
end
```

I was wondering if that is expected behaviour or might be some bug in the parsing code. The original version of the function seems to work with older versions of Julia.

Thx,
D.

**Comment by tkelman** [comment]
This should probably be considered a vote for #7232. Here's how that right hand side parses:
```
julia> rhs = :(for i=1:length(dw) (dw2[i] += dw[i] * dw[i]; dw[i] /=  (eps + sqrt(dw2[i]))) end);

julia> rhs.head
:for

julia> rhs.args[1]
:(i = 1:(length(dw))(dw2[i] += dw[i] * dw[i]; dw[i] /= eps + sqrt(dw2[i])))

julia> rhs.args[2]
quote
end

julia> rhs.args[1].head
:(=)

julia> rhs.args[1].args
2-element Array{Any,1}:
 :i
 :(1:(length(dw))(dw2[i] += dw[i] * dw[i]; dw[i] /= eps + sqrt(dw2[i])))

julia> rhs.args[1].args[2].head
:(:)

julia> rhs.args[1].args[2].args
2-element Array{Any,1}:
 1
  :((length(dw))(dw2[i] += dw[i] * dw[i]; dw[i] /= eps + sqrt(dw2[i])))

julia> rhs.args[1].args[2].args[2].head
:call

julia> rhs.args[1].args[2].args[2].args
3-element Array{Any,1}:
 :(length(dw))
 :($(Expr(:parameters, :(dw[i] /= eps + sqrt(dw2[i])))))
 :(dw2[i] += dw[i] * dw[i])
```

So it's actually trying to call `(length(dw))` as if it's a function, with keyword parameters `dw[i] /= eps + sqrt(dw2[i])`.

To make that parse less surprisingly, add a semicolon after `length(dw)`.

**Comment by dg2** [comment]
Thanks! That was really helpful.
