### ISSUE TITLE
Document (better) how to switch LLVM versions

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#10378]
The current [documentation](http://julia.readthedocs.org/en/latest/devdocs/llvm/#building-julia-with-a-different-version-of-llvm) states to use a different version of LLVM, a `Make.user` file is created (presumably in `julia/deps`). There are tar files for LLVM in that directory, as well as the associated directory. 

A couple of stumbling blocks ...

*  tar files that come with Julia have the `source.tar.gz` extension, while files from llvm.org come with the `source.tar.xz` extension. (this doesn't appear that big of a deal, not sure why they're different though)

* when invoking `$ tar xvfJ llvm-3.6.0.src.tar.xz` a directory is created, but it has a different name and some different content.

````bash
[deps (master)] 
✈  ls llvm-3.6.0.src
CMakeLists.txt     LLVMBuild.txt      Makefile.rules     cmake              include            test
CODE_OWNERS.TXT    Makefile           README.txt         configure          lib                tools
CREDITS.TXT        Makefile.common    autoconf           docs               llvm.spec.in       unittests
LICENSE.TXT        Makefile.config.in bindings           examples           projects           utils

[deps (master)] 
✈  ls llvm-3.3/
CMakeLists.txt     LLVMBuild.txt      Makefile.rules     build_Release      examples           projects           tools
CODE_OWNERS.TXT    Makefile           README.txt         cmake              include            python2_path       unittests
CREDITS.TXT        Makefile.common    autoconf           configure          lib                runtime            utils
LICENSE.TXT        Makefile.config.in bindings           docs               llvm.spec.in       test
````
So the process of how to put the contents of `llvm-3.6.0/` into a new directory `llvm-3.6/` is unclear.

**Comment by tkelman** [comment]
> a Make.user file is created (presumably in julia/deps).

No, it should be in the top-level julia folder. Then just run `make cleanall && make` and all the downloading, untarring, etc should happen automatically.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/julia/pull/10379

**Comment by milktrader** [comment]
Yay

````julia
julia> versioninfo()
Julia Version 0.4.0-dev+3639
Commit 7f7e9ae* (2015-03-01 22:49 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0
````
