### ISSUE TITLE
LLVM 3.6 giving incorrectly signed zeros

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#10377]
Using LLVM 3.6, branches involving comparison to zero can sometimes return the incorrect sign.

This has come up in https://github.com/JuliaLang/julia/issues/9336#issuecomment-76627292 and https://github.com/JuliaLang/julia/pull/9880#issuecomment-72192137.

Here is a minimal example:
```julia
julia> versioninfo()
Julia Version 0.4.0-dev+3639
Commit 7f7e9ae (2015-03-01 22:49 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7- 8850  @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0

julia> function foo(x,y)
           if x==y==0
               return y
           end
           y+1
       end
foo (generic function with 1 method)

julia> foo(0.0,-0.0)
0.0
```

And the `@code_llvm foo(0.0,-0.0)`:
```
define double @julia_foo_42667(double, double) {
top:
  call void @llvm.dbg.value(metadata double %0, i64 0, metadata !10, metadata !16)
  call void @llvm.dbg.value(metadata double %1, i64 0, metadata !17, metadata !16)
  %2 = fcmp une double %0, %1, !dbg !18
  br i1 %2, label %L3, label %L1, !dbg !18

L1:                                               ; preds = %top
  call void @llvm.dbg.value(metadata double 0.000000e+00, i64 0, metadata !20, metadata !16)
  %phitmp = fcmp une double %0, 0.000000e+00, !dbg !18
  br i1 %phitmp, label %L3, label %if2, !dbg !18

if2:                                              ; preds = %L1
  ret double %0, !dbg !21

L3:                                               ; preds = %top, %L1
  %3 = fadd double %1, 1.000000e+00, !dbg !22
  ret double %3, !dbg !22
}
```
The problem here is that the `if2` label it is returning `%0` instead of `%1`.

**Comment by ViralBShah** [comment]
Should we have a label for llvm bugs?

**Comment by tkelman** [comment]
We can probably rename the "fixed in LLVM 3.5" label to be a general "LLVM issue" instead... or just keep using "upstream" where it's usually pretty clear which upstream is being referred to.

**Comment by simonbyrne** [comment]
BTW, I haven't filed an upstream issue, as I wasn't really sure where the problem lay. Could someone who understands more about the internals help me out?

**Comment by JeffBezanson** [comment]
"fixed in LLVM 3.5" is actually a pretty useful label since we'll know exactly which issues to confirm and close when we upgrade LLVM.

**Comment by tkelman** [comment]
> "fixed in LLVM 3.5" is actually a pretty useful label since we'll know exactly which issues to confirm and close when we upgrade LLVM

True, but we can re-appropriate it after that's done. Either "fixed in LLVM 3.7" or something else.

**Comment by kmsquire** [comment]
Or just add a new label.

**Comment by tkelman** [comment]
> BTW, I haven't filed an upstream issue, as I wasn't really sure where the problem lay. Could someone who understands more about the internals help me out?

I don't really understand the internals very well, but I think the way to communicate these things upstream would be to try to create a standalone `.ll` file with IR that returns incorrect results on 3.6.0 but correct on 3.5.1?

**Comment by simonbyrne** [comment]
The problem is that the generated LLVM IR is incorrect (see above), so I'm not sure where the actual problem lies.

**Comment by tkelman** [comment]
Hm, then the upstream label is probably wrong.

**Comment by mbauman** [comment]
Isn't it just likely to be an optimization pass bug? Perhaps try disabling all the optimizations and see if it persists.

**Comment by simonbyrne** [comment]
Looking at the debug info, here's the two optimisation passes between which the wrong value gets returned:
```
*** IR Dump After Combine redundant instructions ***
; Function Attrs: sspreq
define double @julia_foo_64477(double, double) #0 {
top:
  call void @llvm.dbg.value(metadata double %0, i64 0, metadata !10, metadata !16)
  call void @llvm.dbg.value(metadata double %1, i64 0, metadata !17, metadata !16)
  %2 = fcmp une double %0, %1, !dbg !18
  br i1 %2, label %L3, label %L1, !dbg !18

L1:                                               ; preds = %top
  call void @llvm.dbg.value(metadata double 0.000000e+00, i64 0, metadata !20, metadata !16)
  %phitmp = fcmp une double %1, 0.000000e+00, !dbg !18
  br i1 %phitmp, label %L3, label %if2, !dbg !18

if2:                                              ; preds = %L1
  ret double %1, !dbg !21

L3:                                               ; preds = %top, %L1
  %3 = fadd double %1, 1.000000e+00, !dbg !22
  ret double %3, !dbg !22
}
*** IR Dump After Global Value Numbering ***
; Function Attrs: sspreq
define double @julia_foo_64477(double, double) #0 {
top:
  call void @llvm.dbg.value(metadata double %0, i64 0, metadata !10, metadata !16)
  call void @llvm.dbg.value(metadata double %1, i64 0, metadata !17, metadata !16)
  %2 = fcmp une double %0, %1, !dbg !18
  br i1 %2, label %L3, label %L1, !dbg !18

L1:                                               ; preds = %top
  call void @llvm.dbg.value(metadata double 0.000000e+00, i64 0, metadata !20, metadata !16)
  %phitmp = fcmp une double %0, 0.000000e+00, !dbg !18
  br i1 %phitmp, label %L3, label %if2, !dbg !18

if2:                                              ; preds = %L1
  ret double %0, !dbg !21

L3:                                               ; preds = %top, %L1
  %3 = fadd double %1, 1.000000e+00, !dbg !22
  ret double %3, !dbg !22
}
```

**Comment by simonbyrne** [comment]
See [LLVM #22823](http://llvm.org/bugs/show_bug.cgi?id=22823).

**Comment by simonbyrne** [comment]
So it looks like it has been patched in svn (http://reviews.llvm.org/rL230564), but it just missed out on 3.6. Does this mean we need  a "fixed in LLVM 3.7" tag?

**Comment by nalimilan** [comment]
Or hopefully "to be fixed in LLVM 3.6.1"?

**Comment by tkelman** [comment]
Ask in the bug thread / mailing list if the fix can be a candidate for backporting for 3.6.1.

**Comment by StefanKarpinski** [comment]
LLVM doesn't do point releases.

**Comment by simonster** [comment]
Don't they? There are point releases (3.4.1, 3.4.2, and 3.5.1) on the [download page](http://llvm.org/releases/download.html).

**Comment by StefanKarpinski** [comment]
Oh, I guess they started doing point releases in the 3.4 cycle. Nevermind, I hadn't noticed that.

**Comment by eschnett** [comment]
3.6.1 is scheduled for March (this month), so backporting would need to happen soon.

**Comment by tkelman** [comment]
@eschnett see http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-March/082945.html, 3.5.2 is scheduled for March, 3.6.1 is scheduled for May. I just tested fixing this as a local patch and it seems to work, I'll open a PR.

**Comment by simonbyrne** [comment]
This patch made the 3.6.1 release:
https://github.com/llvm-mirror/llvm/commit/0ee768621b2f5c1ece736c42a9a32e29083f35ee

**Comment by tkelman** [comment]
Awesome, thanks for keeping an eye on that one.
