### ISSUE TITLE
Segment Fault when using svds with OpenBLAS on Nehalem kernels

### ISSUE THREAD

**Issue by toddleo** [JuliaLang/julia#10387]
I am running julia nightlies in a virtual machine in the cloud, which seems not support AVX, and OpenBLAS fallbacks to Nehalem kernels. But when I tried to apply svds on a sparse matrix(considerably large, around 6,000,000 x 2,600), Segment fault returned in seconds:

> signal (11): Segmentation fault
> dgemv_t_NEHALEM at /usr/lib/libopenblas.so.0 (unknown line)
> Segmentation fault

and sadly, this error raises every time. However, svds runs successfully on smaller sparse matrices(500x500). Is my previous matrix too large for svds/OpenBLAS?

Should I also CC @xianyi ?

**Comment by xianyi** [comment]
Is it single precision or double precision? What's OpenBLAS version?

**Comment by ViralBShah** [comment]
Could you provide a test case that I can use to reproduce the problem?

**Comment by JeffBezanson** [comment]
The output of `versioninfo()` would be helpful.

**Comment by toddleo** [comment]
My original matrix is double precision(SparseMatrixCSC{Float64,Int64}), and yes I can reproduce this error using `sprand`:

> julia> mx = sprand(5758983, 2600, 0.05)
> 5758983x2600 sparse matrix with 748634422 Float64 entries:
> julia> svds(mx)
> 
> signal (11): Segmentation fault
> dgemv_t_NEHALEM at /usr/lib/libopenblas.so.0 (unknown line)
> Segmentation fault

Output from `versioninfo()` :

> Julia Version 0.4.0-dev+3637
> Commit 74c71fb* (2015-03-01 18:30 UTC)
> Platform Info:
>   System: Linux (x86_64-linux-gnu)
>   CPU: Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
>   LAPACK: liblapack.so.3
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.3

I'd also printed `versioninfo` in verbose mode, but OpenBLAS version is still not shown. Any hints how to check its version?

P.S. I installed julia from @staticfloat 's [ubuntu PPA](https://launchpad.net/~staticfloat/+archive/ubuntu/julianightlies), since I have troubles when compiling julia on this particular machine.

**Comment by toddleo** [comment]
sorry I accidentally closed this issue...

**Comment by tkelman** [comment]
What version of Ubuntu?

**Comment by toddleo** [comment]
@tkelman Ubuntu 12.04 LTS Server version

**Comment by staticfloat** [comment]
@toddleo Does this happen reliably?  E.g. is it every time you run the above code?  Does it require such a large matrix?  I'm having a hard time reproducing because the matrix is so large, and my test machine doesn't have much RAM.

**Comment by staticfloat** [comment]
Ah, I just read your initial report more closely.  What is the smallest matrix that causes these crashes for you?

**Comment by toddleo** [comment]
@staticfloat : 

> Does this happen reliably? E.g. is it every time you run the above code?

Yes it happens every time.

> Does it require such a large matrix?

It can be scaled down by using a much smaller density *p* on `sprand`, which generates a much sparser matrix while allocating much less memory, and still triggers the bug:

> julia> @time mx = sprand(5758983, 2600, 0.0000005)
> elapsed time: 0.00094965 seconds (237 kB allocated)
> 5758983x2600 sparse matrix with 7411 Float64 entries
> 
> julia> svds(mx)
> 
> signal (11): Segmentation fault
> dgemv_t_NEHALEM at /usr/lib/libopenblas.so.0 (unknown line)
> Segmentation fault

**Comment by tkelman** [comment]
It doesn't look like there's such a thing as `openblas_get_version()`... that might be good to add, don't you think @xianyi?

**Comment by ViralBShah** [comment]
Doesn't crash on my mac with 0.4-dev.

**Comment by toddleo** [comment]
@ViralBShah : 

> Doesn't crash on my mac with 0.4-dev.

Yes, it works fine on my laptop too, so I presume it is Nehalem kernels related.

**Comment by vtjnash** [comment]
What does `cat /proc/cpuinfo` return? I'm also having trouble reproducing, sadly.

**Comment by vtjnash** [comment]
the reported processor is http://ark.intel.com/products/64591/Intel-Xeon-Processor-E5-2640-15M-Cache-2_50-GHz-7_20-GTs-Intel-QPI, which should support AVX (and is in the Sandybridge family)

**Comment by tkelman** [comment]
Can you try again with latest openblas versions? Leave a comment or open a new issue if you still see this.
