### ISSUE TITLE
100:10 constructs a range with start == 100 and stop == 99

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#10388]
Just stumbled across this:

```jl
julia> a = 100:10
100:99
julia> first(a)
100
julia> last(a)
99
julia> length(a)
0
```

Present in v0.3.6 and master

**Comment by Mike43110** [comment]
That's because the range constructor is forward only.

Try `a = 100:-1:10` instead for the behavior desired.

**Comment by quinnj** [comment]
This is correct behavior and represents an "empty range". If you don't supply a `step` argument, then it is assumed to be `1`, so your range is actually `100:1:99` which is clearly empty.

**Comment by rened** [comment]
Thanks, I'm aware of that. I guess this issue did not get caught before because you can't iterator over it and `length==0` - but code that relies on the `start` and `stop` fields (or `first` and `last`) will trip over this. Why not keep the original limits?

**Comment by mbauman** [comment]
It's definitely intentional, but I was curious about the rationale here, too.  Here's what [the code says](https://github.com/JuliaLang/julia/blob/f7732f7d420c9de0e1abac0a317ae0d7499be6c3/base/range.jl#L33-L36):

            # empty range has a special representation where stop = start-1
            # this is needed to avoid the wrap-around that can happen computing
            # start - step, which leads to a range that looks very large instead
            # of empty.

**Comment by rened** [comment]
Ah, ic. This is of course a corner case and I am not very knowledgeable about the rationale behind the type system, but perhaps an EmpytRange might be an option. 
Every time I use similar special values / conventions in my own code it feels a little hacky to me.

**Comment by mbauman** [comment]
Is this causing you trouble when using Base julia methods? This was a problem with `deleteat!` before https://github.com/JuliaLang/julia/commit/b67025bd73e164d23b35d30e92d0c6570221b3f2.  There may be other similar cases that should also be fixed.

**Comment by rened** [comment]
Didn't case any problem, no. I just stumbled upon it by mistyping `100/10` as `100:10`

**Comment by JeffBezanson** [comment]
see also #2537

**Comment by johnmyleswhite** [comment]
@rened: Figuring out why `EmptyRange` could be bad for performance is a really good chance to learn something generally useful about designing for Julia's type inference system.
