### ISSUE TITLE
Ctrl-Up/Down breaks the REPL

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#10397]
Similar to #10222.
Pressing Ctrl-Up or Ctrl-Down results in unrecognized input error:

```
julia-0.4> ERROR: Unrecognized input
 in error at error.jl:19
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at ./LineEdit.jl:1576
 in run_interface at ./LineEdit.jl:1549
 in run_frontend at ./REPL.jl:828
 in run_repl at ./REPL.jl:157
 in _start at ./client.jl:455
```

I'm on latest master. In my terminal, these combinations correspond to `^[[B` and `^[[A` (at least that's the result of Ctrl-V followed by the combination).

**Comment by JeffBezanson** [comment]
I thought by now we'd added a catch-all to avoid crashing out in these cases.

**Comment by blakejohnson** [comment]
We did, but it looks like @Keno's recent work to introduce `KeyAlias`s seems to have broken it.

**Comment by Keno** [comment]
We can just put a catchall ignore in the escape map.

**Comment by StefanKarpinski** [comment]
I'd rather have a catch-all that's not in the key map so that someone messing with the keymap can't accidentally cause their REPL to quit.

**Comment by blakejohnson** [comment]
It is curious that is broken. If you look, we do explicitly try to ignore inputs that we can't match to something in the keymap:
https://github.com/JuliaLang/julia/blob/31c12afc4b53beee20a30e823203036d104e6ead/base/LineEdit.jl#L754

**Comment by Keno** [comment]
> I'd rather have a catch-all that's not in the key map so that someone messing with the keymap can't accidentally cause their REPL to quit.

In that case, we should actually put the try/catch around it, so that people putting things in their keymap that happen to error don't quit either.

**Comment by StefanKarpinski** [comment]
Yes – that's exactly it.

**Comment by sbromberger** [comment]
For the record: shift-up/down also crashes the REPL under OSX under certain circumstances. I'm trying to get a reproducible test case but it's inconsistent right now. Here's an example:

```
help?> asdERROR: Unrecognized input  # I hit shift-up after asd
 in error at error.jl:19
 in anonymous at LineEdit.jl:860
 in anonymous at LineEdit.jl:760
 in prompt! at /usr/local/julia-latest/lib/julia/sys.dylib
 in run_interface at /usr/local/julia-latest/lib/julia/sys.dylib
 in run_frontend at /usr/local/julia-latest/lib/julia/sys.dylib
 in run_repl at /usr/local/julia-latest/lib/julia/sys.dylib
 in _start at /usr/local/julia-latest/lib/julia/sys.dylib
```

```
julia> versioninfo()
Julia Version 0.4.0-dev+3631
Commit 949f202* (2015-02-28 19:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by blakejohnson** [comment]
@Keno, the reason we no longer ignore input on unrecognized characters is this line:
https://github.com/JuliaLang/julia/blob/1915c50e0cc0560e391decd5b76ab955b902fded/base/LineEdit.jl#L860

Should we drop the else branch of that if-else or replace it with a `warn`?
