### ISSUE TITLE
Error when using if false statement in global scope

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaLang/julia#10399]
I wanted to quickly disable some code in a script so putted a `if false` around it, but I was surprised it threw an error. 

This works:

    if 0 == 1        
        for i=1:3  
            println(i)
        end    
    end

But this gives a compilation error:

    if false
        for i=1:3  
            println(i)
        end    
    end

>ERROR: error compiling anonymous: cannot convert type to a julia type

Is that a bug ?

>Julia Version 0.4.0-dev+3052
Commit a2c3206 (2015-02-02 15:11 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by simonster** [comment]
Dup of #10281, which is already fixed. Should work for you if you update Julia.

**Comment by jonathanBieler** [comment]
Ups sorry, I searched for "if false" but that was a bit too unspecific.
