### ISSUE TITLE
Spatting of tuples of arrays concatenates arrays

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#10401]
Examples:

```julia
julia> a = ([1,2,3], [4,5,6])
([1,2,3],[4,5,6])

julia> [a...]
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at ./deprecated.jl:40
 in oldstyle_vcat_warning at ./abstractarray.jl:26
 in vect at abstractarray.jl:29
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

julia> data_in = ("hello", 23, 2.7, (), [], (1,8))
("hello",23,2.7,(),None[],(1,8))

julia> [data_in...]  #missing [] from output
5-element Array{Any,1}:
   "hello"
 23
  2.7
   ()
   (1,8)
```

The deprecation warning is for v0.4, but v0.3 has the same behavior (minus the deprecation warning).

In hindsight, this could probably have been predicted from the current behavior... I just find it surprising.

Related: #10338 (and possibly can be absorbed there?)

Cc: @Jutho

**Comment by simonster** [comment]
Presumably when `[a, b]` ceases to concatenate after the deprecation period (#8599), this won't concatenate either.

**Comment by kmsquire** [comment]
Presumably, yes.  I'll close this then--it doesn't seem like it's affected anyone until now, and should be handled properly in 0.5 (or whenever).
