### ISSUE TITLE
inconsistency with sparse matrices and isempty?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10409]
Tangentially related to #10407, consider:

```
help?> spzeros
search: spzeros

Base.spzeros(m, n)

   Create an empty sparse matrix of size "m x n".

julia> a = spzeros(Int,5,5)
5x5 sparse matrix with 0 Int64 entries:

julia> isempty(a)
false
```

**Comment by ViralBShah** [comment]
This is not inconsistent with the dense case:

````
julia> isempty(zeros(5,5))
false
````

**Comment by sbromberger** [comment]
The inconsistency is in the docstring describing `spzeros` in which the term "empty" is used. What does "empty" mean in the context of a sparse matrix and (per #10407) what does it mean to take the maximum of an "empty" matrix?

**Comment by ViralBShah** [comment]
Ah - I see what you mean. We need some disambiguation. The matrix is not empty - it is full of zeros.

**Comment by sbromberger** [comment]
Exactly :) It's almost like a defaultdict, in my mind. Is an empty defaultdict really empty?

**Comment by StefanKarpinski** [comment]
That's an interesting perspective on default dicts. Maybe good that we don't have default dicts in base ;-)

**Comment by tkelman** [comment]
The internal fields `nzval` and `rowval` are empty arrays in this case, but the structural representation details are not immediately obvious to anyone who isn't familiar with CSC format.

**Comment by nalimilan** [comment]
Maybe change to `Create a sparse matrix with only missing entries`?
