### ISSUE TITLE
Confused about parametrization type

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#10408]
If I am making a function or composite type that involves floating point numbers, should I enforce those numbers to be Float64 or FloatingPoint? 

I thought it should be FloatingPoint so that the function/type will work with any kind of floating point number. 

However, several julia packages enforce Float64 (e.g. Distributions package Multinomial distribution) and so I run into problems and have to put in a lot of converts in my code to Float64. 

Am I doing this wrong? I'm quite new to julia

**Comment by johnmyleswhite** [comment]
This seems like a better question for julia-users since it's not really a bug report.

Arguably Distributions should use a lot weaker type constraints. On the flip side, why are you using floating point numbers that aren't 64-bit?

**Comment by bdeonovic** [comment]
Sorry for posting in the wrong place, I'll check out julia-users in the future. 

I don't have any intention to use non Float64 floatingpoints numbers, I'm just trying to write good code. 

I saw a lot of examples where people recommended to to use Integer rather than Int64 or String rather than ASCIIString, etc. I'm just trying to be consistent. I'm fine just using Float64 if that is the appropriate approach here.

**Comment by johnmyleswhite** [comment]
Let's have this discussion elsewhere. The design issues involved are a little subtle.

**Comment by bdeonovic** [comment]
Made a post on julia-users https://groups.google.com/forum/#!topic/julia-users/dmO6vx6icmo. Go ahead and close this.
