### ISSUE TITLE
There is no method for real(A) and imag(A) when A is a sparse matrix.

### ISSUE THREAD

**Issue by prezaei85** [JuliaLang/julia#10412]
I thought It would make sense to add this to the base. 
`real` has no method matching real(::SparseMatrixCSC{Complex{Float64},Int64})

**Comment by ViralBShah** [comment]
@tanmaykm Perhaps you can roll this into your other open PR on sparse fixes?

**Comment by tkelman** [comment]
Which open PR are you referring to? This shouldn't be too difficult to add (follow the examples of round etc, where the Tv of the result is different than Tv of the input), but unless it would conflict with the same lines of code touched by the open PR, better to do separately.
