### ISSUE TITLE
-p option regression

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10414]
Two issues:

1. `julia -p 1` does not launch an additional worker
2. Plain `julia -p` or even `julia -p auto` should launch as many workers as the number of cores

**Comment by MillCheck** [comment]
Should julia -p 1 launch an additional worker?

**Comment by amitmurthy** [comment]
Yes, `-p` specifies the number of additional processes.

**Comment by MillCheck** [comment]
Well, then the julia --help output
 -p <n>                   Run n local processes
seems confusing to me, should probably be fixed along with this issues

**Comment by amitmurthy** [comment]
In the referenced PR above, I have changed the text to 

```
 -p, --procs {N|auto}      Integer value N launches N additional local worker processes
                           'auto' launches as many workers as the number of local cores
```
