### ISSUE TITLE
differentiation of lowered AST from typed AST, and interface function from internal function

### ISSUE THREAD

**Issue by hongborong** [JuliaLang/julia#10413]
In writing a package that analyzing and transforming an AST, our biggest worry is around its completeness. We worry that (1) the package cannot cover all kinds of AST nodes, and (2) the package cannot cover all functions.

I would suggest the following: 
1.	Clearly differentiate lowered AST nodes from typed AST nodes.
Basically, there are two different levels of IR. Lowered AST (with or without types) is higher than typed AST. Each level defines its own set of nodes. Higher level nodes can be lowered into lower level nodes. This is a common practice in compilers.

The current Julia has two different ASTs, but it does not seem to have a clear definition of what kinds of nodes are allowed in which AST. 

2.	Clearly differentiate Julia interface functions from internal functions.
We care only about interface functions. Internal functions are detailed implementation, which we do not care.

With these two requirements satisfied, we can build meta-data for the interface functions only, and analyze lowered AST nodes only. In this way, we can ensure that our analyses completely cover one level of IR and all interface functions, and thus it is complete (handles any applications).  I believe this can benefit not only our package, but also all other packages doing analyses.

Thanks for consideration.
Hongbo

**Comment by toivoh** [comment]
A clear specification on the AST format would be great. I guess that Jeff
would be reluctant to tie down the format though. Still, it would be good
to get some idea of if and when the AST format will be considered to be
part of Julia's public interface, as I think it should, at least eventually.

I know exactly what you mean about wondering if you have covered all
possible ASTs, and, even more so, wondering if there has been a change to
the format afterwards (thankfully, that doesn't seem to be too frequent).

**Comment by garrison** [comment]
I too would really love to see some documentation of the AST.  Whether or not the AST format is tied down, it would be incredibly helpful (for all macro authors) to have documentation of the status quo.

**Comment by JeffBezanson** [comment]
AST docs added by fc31ef9c9b1973feac189058c9fcb5fb302924b4

**Comment by hongborong** [comment]
The document reads nice. Thank you for the great work, Jeff. That will provide a basis for many packages working on ASTs.

On the other hand, it could be better if you add information about the "surface syntax AST". It is less important to the internal compiler of Julia, like you said. But to AST-based compilers, like we are doing in packages, it is more important. The reason is that at this level, the AST is much closer to source level, and much cleaner to analyze (There are not many internal nodes Julia introduces). Staying at this higher level makes analyses easier.

You might describe the nodes unique to surface syntax AST with necessary details, and just mention the names of the nodes shared by the surface syntax and lowered AST. 

Thanks.
