### ISSUE TITLE
missing bounds checking for GenSym

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#10426]
This reliably segfaults:
```
julia> eval(:($(GenSym(-1000000000)) = 1))

signal (11): Segmentation fault
unknown function (ip: -2072084214)
unknown function (ip: -2072083467)
unknown function (ip: -2072083060)
jl_expand at /mnt/hdd/mlubin/julia-0.4/usr/bin/../lib/libjulia.so (unknown line)
```

**Comment by tkelman** [comment]
Could 32-bit integer overflow in GenSym construction be the root cause of #10045? a0266d4c1a4eec85ec0d14baafbd8bce6924d46a is way too long for me to figure out what to do about it though. @vtjnash

**Comment by JeffBezanson** [comment]
Yes the gensym boxing function is declared with UIBOX_FUNC but the argument type is ssize_t. I have a patch.

**Comment by vtjnash** [comment]
> Could 32-bit integer overflow in GenSym construction be the root cause of #10045

no, that would imply the creation of 2^32 gensym objects, which would require more memory than a 32-bit processor can address

**Comment by tkelman** [comment]
Would you be convinced otherwise if I run the tests repeatedly overnight on my local machine and they all pass now? ff9718eb7e35b0eb235e94b9e9a92bb8622ad827 failed the first time, but at cb09d285e0f8dcfc1d34e963bf8ddb35c2b5679c I'm at 5 (and counting) successes in a row now.

**Comment by vtjnash** [comment]
i would be very confused: a function with 2^31 variables would be quite impressive

**Comment by tkelman** [comment]
Nevermind. Damnit. Run number 8 failed.
