### ISSUE TITLE
WARNING: convert(::Type{Ptr}, ::CUDArt.CudaPtr{Float32}) methods should be converted to be methods of unsafe_convert

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#10437]
The latest snapshot of Julia makes CUDArt unusable because of nonstop warnings of the type given above.  The warnings are generated by ccall instructions, and I suspect something needs to be fixed with ccall?

**Comment by denizyuret** [comment]
Part of the issue seems to be that I can't seem to turn warnings off on worker processes.  Even if I start julia with --depwarn=no, the workers do not inherit this.  Maybe inheriting JLOptions() by children should be another issue?

**Comment by JeffBezanson** [comment]
This recent change deprecates conversion to `Ptr` since it's considered dangerous. The warning is telling all libraries that define conversions to Ptr to define `unsafe_convert` instead.

@vtjnash The following might be a problem, since it refers to a definition in Base:

```
julia> ccall(:jl_value_ptr, Ptr{Void}, (Ptr{Void},), 1)
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at ./deprecated.jl:40
 in anonymous at no file
Ptr{Void} @0x0000000000000001
```

**Comment by vtjnash** [comment]
i might want to improve the text of that message, but that conversion is an error in C too.

we should probably add `eval(Base, :(const unsafe_convert = cconvert))` to Compat.jl for v0.3

**Comment by JeffBezanson** [comment]
I think it might be more user-friendly for the fallbacks to be

```
cconvert(T::Type, x) = x
unsafe_convert(T::Type, x) = convert(T, x)
```

Those are easier to reason about. Then you have the option of just defining methods for `convert`, and they will be used, but if you want more safety you can choose to define Ptr conversions only for `unsafe_convert`.
