### ISSUE TITLE
change Enum to a bitstype

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#10439]
since one of the primary usages of enum is to provide c-compatibility, it would be nice to be able to use the names of Enum's directly in the ccall signature, rather than converting them to Cint values. However, this requires changing Enum to be a bitstype, for compatibility with some platform ABI's.

**Comment by JeffBezanson** [comment]
I guess it would also have to be 32 bits? Maybe the way to do this is if the representation type is Int32 then make a bitstype, otherwise keep doing what we do now.

**Comment by vtjnash** [comment]
that does sound vaguely annoying to implement. perhaps "easier" is to have a table of standard integers for each size so you can emit the appropriate primary conversion

**Comment by JeffBezanson** [comment]
What do you mean by "primary conversion"?

Maybe we just have to say enums in ccall are `Cint`.

**Comment by vtjnash** [comment]
> Maybe we just have to say enums in ccall are Cint.

i guess since you can force an enum in C to be a non-int size, it's not completely insane to allow it in julia also

> What do you mean by "primary conversion"?

i mean the type used for `box(IntN, unbox(EnumTy, myenum))` as a base case, from which the enum can get cast to any other integer type you want

**Comment by JeffBezanson** [comment]
The manual does currently tell people to use Cint for enums, so this is not necessarily urgent.

**Comment by vtjnash** [comment]
Well, yes -- I believe I wrote this feature enhancement at the same time as that documentation

**Comment by SimonDanisch** [comment]
Just stumbling upon this while wrapping C-Enums with Julia 0.4.
It needs to be Cint, in order to be used in structs/immutables for the right padding. So just converting it in ccall is not enough, I'd argue.
Why not have an argument to enum to specify the size?
```Julia
@enum MyCEnum{Cint} A B C D
```

**Comment by JeffBezanson** [comment]
Ok, maybe we should make `Cint` the default. I'm in favor of being able to request a representation type, but I'd prefer different syntax. `MyCEnum{Cint}` collides with syntax for defining an enum with a type parameter.

**Comment by StefanKarpinski** [comment]
+1 to making `Cint` the default. I'm not sure that we really need to be able to specify the implementation type aside from just using the same as C/C++. How about waiting to see if that's actually necessary?

**Comment by quinnj** [comment]
Is there no way to define a non-Int32 Enum now? I think I kind of missed this discussion, but it's pretty annoying when trying to interop with libraries that define enums to be less than `int` size.
