### ISSUE TITLE
Resurrecting bcast (and maybe split) from ppeval for use in pmap

### ISSUE THREAD

**Issue by AndyGreenwell** [JuliaLang/julia#10438]
For those of us who remember using [Star-P](http://www-math.mit.edu/~edelman/publications/star-p.pdf), ppeval provided some similar capability to pmap in that it was a functional form of executing a parallel loop over (ideally) computationally expensive iterations and complex code paths.  

The bcast function (as documented within the link above) provided the capability for broadcasting data from the master process to all worker processes, where the broadcast data were then input arguments that lived within the scope of the function to be executed on each worker.

In recently porting a Matlab code to Julia, I came across a situation where the code flow consisted of a number of distinct variables loaded from a MAT file on the master process, where a large number of the loaded variables are then distinct input arguments to a single function that could ideally be passed as the function argument to pmap for parallel execution.  Only one or two input arguments to my function vary with each iteration of the parallel loop, while the remaining arguments take unchanging values for each iteration. 

While pmap accepts arguments that are in a collection, where each of the items in a collection can be the same, the bcast function used along with ppeval provided a compact syntax that made the intent to broadcast the argument to each worker explicit within the scope of the function called on each worker.

This issue requests consideration for resurrecting bcast (and possibly its sibling split) within the context of the pmap function.

**Comment by jiahao** [comment]
cc @alanedelman: "We had this in Star-P 10 years ago!"

**Comment by ViralBShah** [comment]
You can achieve broadcasting by passing a closure to pmap.

**Comment by micahjsmith** [comment]
@ViralBShah could you elaborate on your suggestion?

Considering the case
```
function foo(a,b)
    a+b
end

A = 1*ones(3)
B = 2*ones(3)

map(foo,A,B)
broadcast(foo,A,2) # okay

pmap(foo,A,B)
pmap(i -> foo(A[i], 2), 1:length(A)) # is this what you mean?
```

If I understand the approach correctly, it requires the workers to each have a copy of the entirety of `A`.

**Comment by ViralBShah** [comment]
cc @amitmurthy

**Comment by amitmurthy** [comment]
@AndyGreenwell / @micahjsmith  see https://github.com/JuliaLang/julia/pull/16808#issuecomment-228581684
