### ISSUE TITLE
Array inline initialization and use

### ISSUE THREAD

**Issue by terraqout** [JuliaLang/julia#10432]
Hello.
Is there any trouble or misconception with implementing such shorthand syntax:
```
println([12,3][2])
> 3
```
It's common use in javascript:
```
if [LOCAL_CONSTANT1,LOCAL_CONSTANT_2...LOCAL_CONSTANT_N][value]
  do something
end
```

I can implement this by myself, so this is discussion issue

**Comment by mbauman** [comment]
No trouble at all! It already works for me in both 0.3 and 0.4.  If this isn't working for you, could you post what you tried and the result?

**Comment by ivarne** [comment]
It works for me too.
```julia
julia> println([12,3][2])
3
```
Do you have an example that doesn't work?

**Comment by terraqout** [comment]
Sorry, but I can't even reproduce. Thanks everybody for your answers
