### ISSUE TITLE
Cannot refer to type parameters from helper function defined inside type anymore

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#10445]
The following works in Julia 0.3

    type Test{T}
        x
        modify!(t) = (t.x = T; t)
        Test() = modify!(new())
    end

    Test{Int}()

but with 0.4 I get
    
    ERROR: UndefVarError: T not defined
     in modify! at none:3
     in call at none:4

It still seems to be fine to refer to the type parameter from within the constructor itself.
This seems to be causing https://github.com/toivoh/Debug.jl/issues/65, at [this line](https://github.com/toivoh/Debug.jl/blob/2bb1f10e0d10837252b04ad5ad93d5d192eb8e2e/src/AST.jl#L74). Is it intentional? I could work around it if it is.

**Comment by toivoh** [comment]
Thinking about it a bit more closely, the new behavior actually makes more sense to me. So I hope it is intentional?

**Comment by JeffBezanson** [comment]
Yes, it's intentional. The parameters now only exist in the constructors.

**Comment by toivoh** [comment]
Ok, thanks for the clarification!
