### ISSUE TITLE
Feature request: allow TimePeriod constructors of the form 25*Millisecond

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10449]
Currently one has to construct a `TimePeriod` using the constructor syntax `Dates.Millisecond(25)`. In contrast, it is much more natural to use `Millisecond` as a unary postfix unit (like what `SIUnits.jl` does), and have `25*Dates.Millisecond` produce the same result.

**Comment by milktrader** [comment]
+1

**Comment by quinnj** [comment]
We could define lowercase as a unit `millisecond = Millisecond(1)` or overload `*(x,::Type{Millisecond}) = x*Millisecond(1)`. Honestly I kind of prefer how it is though; personally I find `Millisecond(25)` to be more natural.

**Comment by milktrader** [comment]
We could have both, no?

**Comment by jiahao** [comment]
Consider the use cases involving time arithmetic:

`Minute(30)/Second(1)` vs `(30*Minute)/(1*Second)`

or

`6Hour + 28Minute + 3Second` vs `Hour(6) + Minute(28) + Second(3)`

**Comment by nalimilan** [comment]
+1, but it feels more natural in lowercase.

**Comment by jiahao** [comment]
I'm sure the Germans would disagree ;)

I thought lowercase constructors were going away in #1470?

**Comment by quinnj** [comment]
Technically `millisecond` wouldn't be a constructor, just a "unit".

**Comment by quinnj** [comment]
I think `Millisecond(25)` is simple enough; we can re-open if people want to further discuss or voice more support for this now-3.5-year-old issue.
