### ISSUE TITLE
UInt not defined

### ISSUE THREAD

**Issue by rekado** [JuliaLang/julia#10454]
I just built Julia from the latest release tarball `julia-0.3.6_0c24dca65c.tar.gz` on Fedora 21.  According to the [documentation](http://julia.readthedocs.org/en/latest/manual/integers-and-floating-point-numbers/) there should be a type `UInt` or `UInt8`, but I just get an error:

~~~
[rekado@workstation:~/code/julia-0.3] (643) $ ./julia 
/home/rekado/code/julia-0.3/usr/bin/../lib/julia/sys.ji

  _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> UInt8
ERROR: UInt8 not defined

julia> UInt
ERROR: UInt not defined
~~~

I do not get this error for `Int`, `Int64`, `Int8`, and so on.

I built Julia without passing any `USE_SYSTEM_*` flags to `make`, just plain `make`.

**Comment by nalimilan** [comment]
The URL to the manual you give is about 0.4, not 0.3. Use `Uint8` there.

**Comment by mbauman** [comment]
See: http://julia.readthedocs.org/en/release-0.3/manual/integers-and-floating-point-numbers/

If you want to start using some of the new syntaxes and names from 0.4 in 0.3, you can take a look at the [Compat.jl package](https://github.com/JuliaLang/Compat.jl).

**Comment by timholy** [comment]
@rekado, when you're looking at the manual, notice the little popup at the bottom right. You want to be set to `release-0.3`, not `latest`.

**Comment by rekado** [comment]
Ouch!  Sorry about this.  Thanks for pointing me at the correct version.
