### ISSUE TITLE
zeros(::StepRange{<:Dates.TimeType,<:Dates.Period}} doesn't work

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10450]
```julia
julia> zeros(Dates.DateTime(2015,1,1,0,0,0.0):Dates.DateTime(2015,3,31,0,0,0.0))
ERROR: MethodError: `zero` has no method matching zero(::Type{Base.Dates.DateTime})
 in zeros at array.jl:227
```

Note that `zeros(1:51)` works, and does the same thing as `zeros([1:51])`.

**Comment by quinnj** [comment]
Are you suggesting we should define `zero(::Date)` and `zero(::DateTime)`? I purposely didn't because it doesn't seem meaningful; on the contrary, I thought it would be a subtle source of bugs if `TimeType`s are inadvertently used in places where `zero` and `one` are expected and no error was thrown. What's the use case?
In general, I feel like we've taken the approach of defining datetime functionality to be very much it's own ballgame, with careful interaction between numerical operations; this is opposed to other languages/frameworks where working with dates/times is more number-y.

**Comment by jiahao** [comment]
No, I do agree that `zero(::Date)` and `zero(::DateTime)` shouldn't be defined.

I'm trying to use `Dates` functionality to work with time series, and it is natural to want to derive a different time series from an existing one, hence wanting to initialize an array to hold this new time series using these time intervals with `zeros` (not `zero`, which happens to be called from within `zeros`). I'm not really sure what the right thing to do here. Is this a logic bug in `zeros`, or does `zeros(::StepRange{<:Dates.TimeType,<:Dates.Period}})` require its own constructor? 

The current workaround is to simply do `zeros(length(mydatetimerange))`, but it would be nice to resolve the inconsistency.

**Comment by jiahao** [comment]
> No, I do agree that `zero(::Date)` and `zero(::DateTime)` shouldn't be defined.

Actually, if `int(::DateTime)` works, why can't we have `zero(::DateTime)` return the reference time point? I don't understand why we can have the former but not the latter. Maybe neither should be defined?

**Comment by quinnj** [comment]
I think the difference is that calling `int(::DateTime)` you explicitly asking for the integer representation of that `DateTime` whereas `zero(::DateTime)` is used the majority of the time within other algorithms/functions to work generically on numeric types. As I said, I think there's greater danger of subtle bugs by defining `zero(::DateTime)` than defining `int(::DateTime)`.

In your case, why don't you just use `similar`; isn't that the function for doing exactly what you're trying to do?
```julia
In  [7]: D2 = Dates.DateTime(2015,1,1,0,0,0):Dates.DateTime(2015,3,31,0,0,0)

Out [7]: 2015-01-01T00:00:00:1 day:2015-03-31T00:00:00

In  [8]: similar(D2)

Out [8]: 90-element Array{Base.Dates.DateTime,1}:
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 ⋮                      
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-24T20:32:29.184
 0001-01-25T07:06:07.968
 0000-12-31T00:00:00
```

**Comment by jiahao** [comment]
Oh, actually I wanted a zeroed-out `Vector{Float64}` with the same length as `datetimerange`. The data for the time series are `Float64`s. The `datetimerange` is the "x-axis" and is stored separately.

**Comment by quinnj** [comment]
Ah, so it looks like the method being called is
```julia
zeros{T}(A::AbstractArray{T}) = fill!(similar(A), zero(T))
```
which seems a little non-intuitive to me. The general use of `zeros` is that if you don't specify a type, then `Float64` is the default; but in this case, calling `zeros` on any `AbstractArray` returns a zeroed out array of the same type. Is this right?

**Comment by jiahao** [comment]
Yeah, I had forgotten about that. Perhaps this issue really is one of those subtle bugs that you were trying to avoid. I'll close this for now.
