### ISSUE TITLE
release-0.3:  [1, 2, 3, 4;] == [3, 2, 1, 4]

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#10464]
This doesn't parse in 0.3.0, and I'm not sure it's entirely-documented syntax on release-0.3 at the moment. There was a backport somewhere to make it parse, but it looks like there's a bug.

```
  | | |_| | | | (_| |  |  Version 0.3.7-pre+15 (2015-03-02 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0f0b136* (7 days old release-0.3)
|__/                   |  x86_64-linux-gnu

julia> [1, 2, 3, 4;] == [3, 2, 1, 4]
true
```

**Comment by tkelman** [comment]
sorry, duplicate of #8615 - @JeffBezanson is backporting 6ae205ea7d5a7242bc1d2966ff84c9e942a7b705 okay if it passes tests?

**Comment by JeffBezanson** [comment]
Yes we should backport that. What a weird and awful bug.

**Comment by tkelman** [comment]
done in https://github.com/JuliaLang/julia/commit/bf78596be4483f75d8d5a7d0328a2cb9190b116c, thanks
