### ISSUE TITLE
Stream is closed error upon exiting Parallel Code

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10468]
Rarely I get this error when terminating a parallel processing run.  A race condition or deadlock in the distributed gc / teardown logic? 

```julia
ERROR (unhandled task failure): ArgumentError: stream is closed or unusable
 in check_open at stream.jl:299
 in uv_write at stream.jl:736
 in flush at stream.jl:790
 in anonymous at multi.jl:179
 in lock at stream.jl:812
 in send_msg_ at ./multi.jl:170
 in remote_do at multi.jl:702
 in flush_gc_msgs at ./multi.jl:163
 in flush_gc_msgs at ./multi.jl:189
 in anonymous at task.jl:478
```

cc @amitmurthy

**Comment by andreasnoack** [comment]
I'm seeing these `unhandled task failure`s frequently now, e.g.

https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.3101/job/ys7is66pksb5qipr

**Comment by amitmurthy** [comment]
Dup of https://github.com/JuliaLang/julia/issues/10431

Is there a way to know that the process is shutting down? In normal circumstances, I would like the task failure to be printed, just needs to be ignored during exit.

**Comment by amitmurthy** [comment]
@andreasnoack , yes, now that we are printing unhandled errors in tasks, they will show up in logs now and will need to be handled. I think it is better to create separate issues for each different error. Since

**Comment by pao** [comment]
Closing as dup per @amitmurthy's comment above; reopen if I misunderstood.
