### ISSUE TITLE
Array{Int} <: Array{Real} vs Int <: Real

### ISSUE THREAD

**Issue by RyanCarey** [JuliaLang/julia#10475]
I imagine that even though this feels like a bug, it probably has some explanation, but:

Int <: Real returns false
while Array{Int} <: Array{Real} returns true.

What's going on with that?

**Comment by johnmyleswhite** [comment]
Julia's types are invariant. Definitely not a bug.

**Comment by johnmyleswhite** [comment]
Very clear exposition of design issues involved: http://en.wikipedia.org/wiki/Covariance_and_contravariance_%28computer_science%29

**Comment by andreasnoack** [comment]
It is explained in the manual here

http://julia.readthedocs.org/en/latest/manual/types/#parametric-composite-types

**Comment by IainNZ** [comment]
For posterities sake, I wanted to note that the OP booleans are flipped, i.e.
```julia
julia> Int <: Real
true

julia> Array{Int} <: Array{Real}
false
```

**Comment by IainNZ** [comment]
Oh and I'm guessing this came up in a situation like this
```
function foo(x::Array{Real})
```
but what you probably wanted was
```
function foo{T<:Real}(x::Array{T})
```

**Comment by RyanCarey** [comment]
Thanks all, and yes, Iain, that's where it came up, and so I will now use
that structure insetad.

Ryan Carey | M Sc Bioinformatics Student, Imperial College | Medical
Resident
