### ISSUE TITLE
How to re-stage a method?

### ISSUE THREAD

**Issue by DrTodd13** [JuliaLang/julia#10478]
I am trying to take the output of code_lowered, modify the ast in some way, push that ast back into the method, and then do the equivalent of code_typed.  I can write the modified ast back to func.code.ast but then Base.func_for_method essentially does nothing because the method isn't staged and so just returns the cached func.  The obvious thing to try was to set staged to true and then try Base.func_for_method.  In the example below, this gives this error.  What would be the best way to force lowered AST back into the method and then have all dependent information be re-calculated?

```
ERROR: LoadError: MethodError: `*` has no method matching *(::Type{Int64}, ::Type{Int64})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any)
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)

 in cg at /mnt/home/taanders/pse-hpc/SparseAccelerator/test/optframework-test.jl:2
 in func_for_method at ./inference.jl:625
```

---

``` julia
function cg(x, A)
    A * x
end

type_tuple = (Int64, Int64)
ast = code_lowered(cg, type_tuple)
ast = ast[1]
# Modify ast in some way here.
method = Base._methods(cg, type_tuple, -1)
assert(length(method) == 1)
method = method[1]

method[3].isstaged = true
method[3].func.code.ast = ast
linfo = Base.func_for_method(method[3], type_tuple, method[2])
(cur_ast, ty) = Base.typeinf(linfo, method[1], method[2])

if !isa(cur_ast,Expr)
    cur_ast = ccall(:jl_uncompress_ast, Any, (Any,Any), linfo, cur_ast)
end
```

**Comment by ivarne** [comment]
Please use triple backtics to quote code snippets. It makes them much more readable. (I fixed it for you now)

**Comment by DrTodd13** [comment]
Something else that would probably work is to generate a new function based on the returned, lowered AST and then to request the typed AST of the new function.  I tried something like:
```code3 = Expr(:function, Expr(:tuple, ast2.args[1]...), Expr(:block, ast2.args[3].args...))
    eval_new_code = code1.module.eval(code3)```
However, code_typed fails on eval_new_code because that isn't a generic function.

**Comment by DrTodd13** [comment]
```new_func = Expr(:function, Expr(:call, :new_func_name, ast.args[1]...), Expr(:block, ast.args[3].args...))```
Found out I could do this and generate a non-anonymous function that I can call code_typed on.  It is a roundabout solution but it works.  You guys might want to consider adding some convenience functions to enable AST manipulation.  It isn't super common but from reading it seems we're not the only ones doing it.

**Comment by timholy** [comment]
@DrTodd13, it's hard for us to guess which convenience functions you mean. It might be best to just submit a pull request.

**Comment by DrTodd13** [comment]
Well, I don't know the best interface either.  Just off the top of my head, a few things 1) create a copy of a function with a new name, 2) take modified AST from code_lowered and put it back into the function, 3) same as 2 but for code_typed.  Here's my attempt at 1.  It seems to rename the labels that occur in the AST to be in ascending order but doesn't change the corresponding labels in the goto and gotoifnot nodes.  
```
function copyFunctionNewName(old_func, new_func_name :: String, arg_tuple)
  lambda = code_lowered(old_func, arg_tuple)[1]
  nfsym = symbol(new_func_name)
  println("copying old_func = \n", lambda)
  new_func = Expr(:function, Expr(:call, nfsym, lambda.args[1]...), Expr(:block, lambda.args[3].args...))
  eval_new_func = eval(new_func)
  lambda = code_lowered(eval_new_func, arg_tuple)[1]
  println("new copied func = \n", lambda)
  return eval_new_func
end
```
Here is the output:
```
copying old_func =
$(Expr(:lambda, Any[:x,:A,:b,:tol,:maxiter], Any[Any[:r,:rel_err,:p,:rz,:normr0,:k,:old_rz,:Ap,:alpha,:beta],Any[Any[:x,:Any,18],Any[:A,:Any,0],Any[:b,:Any,0],Any[:tol,:Any,0],Any[:maxiter,:Any,0],Any[:r,:Any,2],Any[:rel_err,:Any,2],Any[:p,:Any,2],Any[:rz,:Any,2],Any[:normr0,:Any,18],Any[:k,:Any,2],Any[:old_rz,:Any,18],Any[:Ap,:Any,18],Any[:alpha,:Any,18],Any[:beta,:Any,18]],Any[]], :(begin  # /mnt/home/taanders/pse-hpc/SparseAccelerator/test/testing-stub.jl, line 62:
        r = b - A * x::ANY::ANY # line 63:
        rel_err = 1 # line 64:
        p = copy(r)::ANY # line 65:
        rz = dot(r,r)::ANY # line 66:
        normr0 = sqrt(rz)::ANY # line 67:
        k = 1 # line 68:
        unless k <= maxiter::ANY goto 1
        2:  # line 69:
        old_rz = rz::ANY # line 70:
        Ap = A * p::ANY # line 71:
        alpha = old_rz / dot(p,Ap)::ANY::ANY # line 72:
        x = x + alpha * p::ANY::ANY # line 73:
        r = r - alpha * Ap::ANY::ANY # line 74:
        rz = dot(r,r)::ANY # line 75:
        rel_err = sqrt(rz)::ANY / normr0::ANY # line 77:
        unless rel_err < tol::ANY goto 4 # line 78:
        goto 0
        4:  # line 80:
        beta = rz / old_rz::ANY # line 81:
        p = r + beta * p::ANY::ANY # line 82:
        k = k + 1::ANY
        3:
        unless (top(!))(k <= maxiter::ANY)::ANY goto 2
        1:
        0:  # line 84:
        return (top(tuple))(x,k,rel_err)::ANY
    end::ANY)))
new copied func =
$(Expr(:lambda, Any[:x,:A,:b,:tol,:maxiter], Any[Any[:normr0,:old_rz,:Ap,:alpha,:r,:rz,:rel_err,:beta,:p,:k],Any[Any[:x,:Any,18],Any[:A,:Any,0],Any[:b,:Any,0],Any[:tol,:Any,0],Any[:maxiter,:Any,0],Any[:normr0,:Any,18],Any[:old_rz,:Any,18],Any[:Ap,:Any,18],Any[:alpha,:Any,18],Any[:r,:Any,2],Any[:rz,:Any,2],Any[:rel_err,:Any,2],Any[:beta,:Any,18],Any[:p,:Any,2],Any[:k,:Any,2]],Any[]], :(begin  # /mnt/home/taanders/pse-hpc/SparseAccelerator/test/testing-stub.jl, line 62:
        r = b - A * x::ANY::ANY # line 63:
        rel_err = 1 # line 64:
        p = copy(r)::ANY # line 65:
        rz = dot(r,r)::ANY # line 66:
        normr0 = sqrt(rz)::ANY # line 67:
        k = 1 # line 68:
        unless k <= maxiter::ANY goto 1
        0:  # line 69:
        old_rz = rz::ANY # line 70:
        Ap = A * p::ANY # line 71:
        alpha = old_rz / dot(p,Ap)::ANY::ANY # line 72:
        x = x + alpha * p::ANY::ANY # line 73:
        r = r - alpha * Ap::ANY::ANY # line 74:
        rz = dot(r,r)::ANY # line 75:
        rel_err = sqrt(rz)::ANY / normr0::ANY # line 77:
        unless rel_err < tol::ANY goto 4 # line 78:
        goto 0
        1:  # line 80:
        beta = rz / old_rz::ANY # line 81:
        p = r + beta * p::ANY::ANY # line 82:
        k = k + 1::ANY
        2:
        unless (top(!))(k <= maxiter::ANY)::ANY goto 2
        3:  # line 84:
        return (top(tuple))(x,k,rel_err)::ANY
    end::ANY)))
```

**Comment by Keno** [comment]
Using the staged method mechanism doesn't really seem like the right thing to do here since all you're doing is an AST optimization. One possible way to resolve this is to add hooks to the compiler that allow you to call your own optimization routine at various places, perhaps on functions guarded by a macro (does that seem reasonable @JeffBezanson)? Other than that I feel like providing a helper method to create a callable function from an AST also seems like a possible interface. Also cc @vtjnash

**Comment by DrTodd13** [comment]
A separate helper method to create a callable function would be fine.  I'd also be happy if "new_func = Expr(:function, Expr(:call, nfsym, lambda.args[1]...), Expr(:block, lambda.args[3].args...))" (from above) worked as you might expect.  I was able to get this approach to work by reordering the AST's labels to be sequential (and the gotos to those labels updated appropriately, of course) and to eliminate consecutive labels in the AST.

I've developed a framework similar to your second suggestion of which this question I'm asking is a part.  There's a good chance we'll submit a paper on this to JuliaCon so maybe that can start the discussion.

**Comment by JeffBezanson** [comment]
I believe the label problem happens because this is taking a back-end tree and feeding it into the front end with `eval`. The front end does a label renaming pass to handle `@goto`, but it doesn't know about the back-end goto nodes. I think I can come up with something that will work.

**Comment by KristofferC** [comment]
Is this still relevant?

**Comment by DrTodd13** [comment]
I think this is supplanted by #21146.
