### ISSUE TITLE
Intel C Compiler fails to compile test/ccalltest.c due to the presence of complex integer literals

### ISSUE THREAD

**Issue by psanan** [JuliaLang/julia#10471]
During a (re)build, I encountered a ["1909: complex integral types are not supported" error](https://software.intel.com/en-us/articles/cdiag1909) when using the intel C compiler (icc 14.0.2 20140120 ).

The build proceeds normally if the following changes are made (from b299179)
````
diff --git a/test/ccalltest.c b/test/ccalltest.c
index 0b6155f..0972aeb 100644
--- a/test/ccalltest.c
+++ b/test/ccalltest.c
@@ -118,28 +118,28 @@ complex_t ctest(complex_t a) {
 complex double cgtest(complex double a) {
     //Unpack a ComplexPair{Float64} struct
     if (verbose) fprintf(stderr,"%g + %g i\n", creal(a), cimag(a));
-    a += 1 - 2i;
+    a += 1 - (2.0*I);
     return a;
 }
 
 complex double* cgptest(complex double *a) {
     //Unpack a ComplexPair{Float64} struct
     if (verbose) fprintf(stderr,"%g + %g i\n", creal(*a), cimag(*a));
-    *a += 1 - 2i;
+    *a += 1 - (2.0*I);
     return a;
 }
 
 complex float cftest(complex float a) {
     //Unpack a ComplexPair{Float32} struct
     if (verbose) fprintf(stderr,"%g + %g i\n", creal(a), cimag(a));
-    a += 1 - 2i;
+    a += 1 - (2.0*I);
     return a;
 }
 
 complex float* cfptest(complex float *a) {
     //Unpack a ComplexPair{Float64} struct
     if (verbose) fprintf(stderr,"%g + %g i\n", creal(*a), cimag(*a));
-    *a += 1 - 2i;
+    *a += 1 - (2.0*I);
     return a;
 }
````

**Comment by jakebolewski** [comment]
Fixed in a more recent version of the compiler?

https://software.intel.com/en-us/articles/error-1909-complex-integral-types-are-not-supported

**Comment by psanan** [comment]
That is likely true (I am using the compiler on a remote system I do not control, but I will submit a ticket to the admins there so feel free to close this).

**Comment by psanan** [comment]
I seem to have version 14.0.2 which is later than the purported fix in that link (10.1.301).

**Comment by psanan** [comment]
I have also left a note on the commit which closes this issue, but one instance of `2i` remains in `ccalltest.c`, which I needed to convert to `(2.0)*I` to build with the intel compiler mentioned above.

**Comment by ivarne** [comment]
I think https://github.com/JuliaLang/julia/commit/03da3a3035519dcbb5cdc744704b7ee076dd3e7e should fix the issue. @psanan Can you confirm?
