### ISSUE TITLE
move darray from base affect @parallel on master branch

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#10485]
julia> @everywhere using DistributedArrays

julia> x= @parallel [sqrt(i) for i = 1:1e5]
ERROR: UndefVarError: DArray not defined

**Comment by amitmurthy** [comment]
This was another way of creating DArrays (via a comprehension). It should be removed from Base and implemented in DistributedArrays.

**Comment by armgong** [comment]
thanks, and julia/base/linalg/distributed.jl maybe also remove

**Comment by amitmurthy** [comment]
Yes, you are right. Have updated the PR.

**Comment by jakebolewski** [comment]
This has been added to the DistributedArray's package.  The syntax is now `x = @DArray [sqrt(i) for i=1:5]`.  Thanks @armgong for highlighting this omission in removing `DArray`'s from Base.
