### ISSUE TITLE
eigs returns garbage when eigenvalues don't converge without warning

### ISSUE THREAD

**Issue by restrin** [JuliaLang/julia#10495]
Consider the matrix A taken from the UF sparse matrix collection found at http://www.cise.ufl.edu/research/sparse/matrices/GHS_indef/laser.html (imported via importSparseMatrix as a .csv file).

If eigs is called on A, for 10 eigenvalues as follows,

```
D, V = eigs(A, nev = 10, ncv = 30, which=:LM, maxiter=300)
```

the eigenvalues don't converge, but D will contain garbage values without warning the user, which in this case is:

```
D = [1.5e-322,1.43e-322,1.4e-322,1.33e-322,1.3e-322,1.24e-322,1.2e-322,1.14e-322,1.1e-322,1.04e-322]
```

Although the user can instead call

```
D, V, nconv = eigs(A, nev = 10, ncv = 30, which=:LM, maxiter=300)
```
and check if nconv > 0, it seems improper to return garbage for D without alerting the user, especially if the user didn't ask for nconv to be returned. Matlab when run on the same matrix with eigs will throw a warning that none of the eigenvalues have converged and just returns a zero vector. Julia should also raise a warning to alert the user, at least if the user didn't request nconv to let them know that some of the output is useless.

**Comment by jiahao** [comment]
>  it seems improper to return garbage for D without alerting the user, especially if the user didn't ask for nconv to be returned.

Just to clarify, Julia functions do _not_ change their behaviors based on the number of output arguments, unlike MATLAB. If you don't specify enough variable names, the remainder just gets thrown away:

```jl
julia> a, b = 1,2,3,4,5
(1,2,3,4,5)

julia> a
1

julia> b
2
```

But yes, warning if `eigs` (and by extension `svds`) didn't converge would be a good default thing to do.
