### ISSUE TITLE
Deprecation for int(::Vector{Any}) is broken

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10499]
`int(Any[1, 2, 3])` worked previously, but the deprecation from #10452 doesn't. It tries to call `round(Int, Any[1, 2, 3])`, but the vectorized form of `round` is constrained to Real arrays. Either we should get rid of that type restriction on `round` (maybe just for the methods that take a type first), or we should add a deprecation that works for this case.

**Comment by IainNZ** [comment]
Just got PkgEval running again after a multiple-day hiatus, this took out quite a few (~10) packages on 0.4
