### ISSUE TITLE
`getindex` defined for zero arguments?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10493]
Is there a reason for this behavior?  Otherwise I think the base case should be to require at least one argument.

```julia
julia> A = randn(5,5);

julia> A[]
-0.7217807985957185

julia> A[()...]
-0.7217807985957185
```

**Comment by timholy** [comment]
If you have a zero-dimensional array, you should definitely be able to index it with zero arguments.

**Comment by jakebolewski** [comment]
But the definition is to get the first element, which would throw a `BoundsError` in that case?

**Comment by iamed2** [comment]
```
julia> a = fill(0, 0, 0)
0x0 Array{Int64,2}

julia> a[]
ERROR: BoundsError: attempt to access 0x0 Array{Int64,2}
  at index [1]
 in getindex at array.jl:279

julia> a[:]
0-element Array{Int64,1}
```

Colon knows what's up

**Comment by mbauman** [comment]
There's a difference between an empty 0x0 matrix and a 0-dimensional array:

```julia
julia> b = fill(0)
0-dimensional Array{Int64,0}:
0

julia> b[] = 1
1

julia> b
0-dimensional Array{Int64,0}:
1

julia> size(b)
()

julia> length(b)
1
```

I think this is all fairly consistent.

**Comment by iamed2** [comment]
Well I made a mistake and then learned something new! So this 0-d array having a value is consistent with some mathematical concept?

**Comment by timholy** [comment]
Plane for 2d, line for 1d, point for 0d. A 0d array is like a point.

**Comment by nalimilan** [comment]
But why should one be able to index a non-zero dimensional array with a zero-dimensional index? Is that really useful?

**Comment by timholy** [comment]
I agree that's less convincing.

**Comment by timholy** [comment]
Still, we allow indexing arrays of any dimensionality with indexes of any dimensionality. So it's reasonable, just probably not very useful.

**Comment by jakebolewski** [comment]
Ok, I see the justification now (tensor of rank 0).  I was confused why this was defined for rank > 0 but I guess why not.

**Comment by andreasnoack** [comment]
@timholy How should I think of 2-d array as a plane? I don't see the analogue.

**Comment by nalimilan** [comment]
If there's no real use case for that I'd rather remove it. This kind of result is particularly confusing (especially for R users who may forget the `:` after the comma):

```julia
julia> x = [1 2 3; 4 5 6]
2x3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> x[1,]
1
```

**Comment by mbauman** [comment]
Indexing a two (or higher) dimensional array with only one index (often called a linear index) is essential to how arrays work.  Perhaps there should be more in the manual on linear indexing.  There's some about it in the [devdocs for SubArray](http://docs.julialang.org/en/latest/devdocs/subarrays/), but I think it should definitely be discussed in the [indexing](http://docs.julialang.org/en/latest/manual/arrays/#indexing) section of the manual.

**Comment by nalimilan** [comment]
Right, linear indexing is required. But I don't see why `x[]` and `x[1,]` should be supported for e.g. matrices in addition to linear indexing.

**Comment by StefanKarpinski** [comment]
Consistency.

**Comment by mbauman** [comment]
Ah, of course you mean the trailing comma.  They're allowed in functions, too.

As for `x[]`, defining `getindex(::Array)` is needed in any case to handle ambiguities between `getindex(::Array, ::Int…)` and `getindex(::Array, ::Foo…)`.  And the parser doesn't know the dimensionality of `x`, so it can't disallow zero-element indexing selectively.

**Comment by nalimilan** [comment]
Well, the function could raise an error. As for consistency with functions, I'm not sure it's very obvious. Personally I hadn't thought about it at all -- probably the influence of the R syntax...
