### ISSUE TITLE
sortperm! does not allow index vector to be a SubArray

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#10491]
As far as I can tell there is no reason for this:
```
function sortperm!{I<:Integer}(x::Vector{I}, v::AbstractVector; alg::Algorithm=DEFAULT_UNSTABLE,
```
and changing the type of the first argument to AbstractVector fixes it.

Use case: allocate x and v once, and keep using their SubArrays in an algorithm where the array size changes every iteration.

**Comment by jakebolewski** [comment]
closed by #10496.  Thanks @denizyuret!
