### ISSUE TITLE
ERROR: cp()  when subdir contains symbolic linked dirs

### ISSUE THREAD

**Issue by julia-user1000** [JuliaLang/julia#10506]
### ERROR: cp()  when subdir contains symbolic linked dirs

The documentation says: http://julia.readthedocs.org/en/latest/stdlib/file/?highlight=cp#Base.cp
```
cp(src::AbstractString, dst::AbstractString; recursive=false)

    Copy a file from src to dest. Passing recursive=true will enable recursive copying of directories.
```

For an example: I have such file structure which contains *one absolute* and *one relative sympolic* link to the directory `src`

```
root_src
├── src
│   └── src_text.txt
└── test
    ├── absolute_link_to_src -> /home/test/root_src/src
    └── relative_link_to_src -> ../src
```

#### Python just does it fine: also keeps the absolute link as it should be.
```python

Python 3.4.3 (default, Feb 26 2015, 23:01:07) 
[GCC 4.9.2 20150204 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.copytree("root_src", "copied_src", symlinks=True, ignore=None)

```

```
copied_src
├── src
│   └── src_text.txt
└── test
    ├── absolute_link_to_src -> /home/test/root_src/src
    └── relative_link_to_src -> ../src
```

#### Julia: ERROR
Version 0.4.0-dev+3806 (2015-03-13 01:02 UTC)
Commit 5195cc8 (0 days old master)
x86_64-unknown-linux-gnu

Arch Linux

```julia

julia> cp("root_src", "copied_src", recursive=true)
ERROR: sendfile: illegal operation on a directory (EISDIR)
 in sendfile at fs.jl:143
 in cp at file.jl:75
 in cp at file.jl:79 (repeats 2 times)

julia> 

```

#### Possible missing: readlink

I'm very new to julia so I might miss something and **I'm not much of a C person - the reason I hope julia will fit my needs.**

python has: [readlink](https://docs.python.org/3.4/library/os.html#os.readlink) which is used in the [shutil.copytree code](https://hg.python.org/cpython/file/3.4/Lib/shutil.py#l261)

##### libuv supports readlink

[uv_fs_readlink](http://docs.libuv.org/en/v1.x/fs.html?highlight=readlink#c.uv_fs_readlink)

But it seems to be missing from: julia: [jl_uv.c](https://github.com/JuliaLang/julia/blob/master/src/jl_uv.c)

I'm not 100% sure how to implement `readlink` myself.

Thanks

**Comment by jiahao** [comment]
cc @ninjin

**Comment by ninjin** [comment]
Thank you for the poke @jiahao, I was lagging behind a little bit on the mailing list.  I will be setting this as my next target and have a look at a couple of other implementations in order to get things right.

**Comment by julia-user1000** [comment]
cc @ninjin 
In the process of fixing this error would it be possibleto add: [uv_fs_readlink](http://docs.libuv.org/en/v1.x/fs.html?highlight=readlink#c.uv_fs_readlink) to [ jl_uv.c](https://github.com/JuliaLang/julia/blob/master/src/jl_uv.c)

readlink is useful in other cases too
Thanks

**Comment by peter1000** [comment]
**Question:** 
julia 0.3 has: `cp(src::String, dst::String)`
julia 0.4dev has: `cp(src::AbstractString, dst::AbstractString; recursive::Bool=false)`

Would it make sense to split this into something like:

`cp(src::AbstractString, dst::AbstractString)`
`cptree(src::AbstractString, dst::AbstractString; keepsym::Bool=false)`

e.g. python uses `shutil.copytree` for Recursively copy an entire directory tree.

**Comment by tkelman** [comment]
I don't think having two separate function names is a very Julian approach for this.

**Comment by peter1000** [comment]
I will start on this issue now where readlink is merged

**Comment by peter1000** [comment]
Can be closed!
