### ISSUE TITLE
curl utf8proc error while running make 

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#10500]
Just got a curl error for utf8proc while trying to make julia release-0.3 on 64-bit RHEL 64-bit against a freshly cloned julia:

```
git rev-parse HEAD
b55539a0fb6c39e9001f34b45f059700982754a6

git status
# On branch release-0.3
nothing to commit (working directory clean)
```

The error from make was:
```
curl: (22) The requested URL returned error: 403 Proxy Unacknowledged
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Proxy Unacknowledged
make[2]: *** [utf8proc-v1.1.6.tar.gz] Error 22
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

Normally I would take that to indicate a proxy configuration problem my system, but make had already downloaded several other files without difficulty.

**Comment by ivarne** [comment]
It downloads nicely for me now. Can you try again?

**Comment by catawbasam** [comment]
Thank you for checking.  I still see it on my end, but will treat it as a local issue for now, so closing.
