### ISSUE TITLE
Dense and sparse cholfact handles deviations from symmetry differently

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#10520]
Right now sparse Cholesky factorization checks for symmetry in contrast to dense Cholesky.
```julia
julia> A = speye(4);A[1,2] = eps();

julia> cholfact(A)
ERROR: ArgumentError: sparse matrix is not symmetric/Hermitian
 in cholfact at sparse/cholmod.jl:980
 in cholfact at sparse/cholmod.jl:1055

julia> cholfact(full(A))
Base.LinAlg.Cholesky{Float64,Array{Float64,2},:U} with factor:
4x4 Base.LinAlg.UpperTriangular{Float64,Array{Float64,2}}:
 1.0  2.22045e-16  0.0  0.0
 0.0  1.0          0.0  0.0
 0.0  0.0          1.0  0.0
 0.0  0.0          0.0  1.0
```
It is an easy fix to make this consistent, but which solution is preferred. Right now I lean towards the sparse solution where the matrix is checked for symmetry. If the user wants to bypass the check, there should be `cholfact(Symmetric)` method defined which is already the case for `cholfact(Sparse)`.

**Comment by tkelman** [comment]
Did this get changed with any of the recent cholmod refactorings, or is there still work to do here?

**Comment by andreasnoack** [comment]
There is still work to do here.

**Comment by tkelman** [comment]
Will any of it happen before 0.5 or should this be pushed to a later milestone?

**Comment by andreasnoack** [comment]
It's a reltive small fix but can break some code so let me fix it in this cycle.
