### ISSUE TITLE
Unbalanced spacing in indexed assignment throws an error

### ISSUE THREAD

**Issue by JayKickliter** [JuliaLang/julia#10530]
I found this error by accident. I don't normally have unbalanced spacing in the index, but it probably shouldn't throw an error.

```julia
julia> bitsMap[idx +1] = decode( Gray, idx )
ERROR: syntax: invalid spacing in left side of indexed assignment

julia> bitsMap[idx + 1] = decode( Gray, idx )
1

julia> versioninfo()
Julia Version 0.3.7-pre+22
Commit b55539a* (2015-03-11 07:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
This is actually ambiguous parsing because of the typed concatenation syntax. `bitsMap` might be a type, so you might mean `Int[4 +1]` which parses differently than `Int[4 + 1]`. This whitespace ambiguity will hopefully go away soon? See #7128

**Comment by ivarne** [comment]
Closing this as a dup of #7128 (and linked issues). 
This is just another vote against the current whitespace sensitive parsing. Next person searching for `ERROR: syntax: invalid spacing in left side of indexed assignment` will get a useful result. Thanks @JayKickliter!
