### ISSUE TITLE
Wrongly parsed String expression

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#10532]
I wasn't able to build a minimal example (like always with parsing errors?! )
But Julia insisted that there is an `ERROR: syntax: unexpected end`
The place was consistently at that one end of some method, even though that I moved the code around and un-commented stuff.
The real error was this though:
```Julia

#same file, at the beginning (probably never moved the "end method" before this)
let shader_cache = Dict{(GLenum, Vector{Uint8}), GLuint}() 
	function test()
		get(shader_cache, "s") do 
			error("shader $shadername didn't compile. \n$(getinfolog(shaderid)") # <- one bracket missing
		end
	end
end
```

Tested: Windows: 0 day master, 0.3.5, Ubuntu: 0.4 some days old.

Best,
Simon

**Comment by JeffBezanson** [comment]
$ parses until it has a full expression, so this looks like an interpolated expression with a " in it. There is no way to know that the " is intended to close the string, unless we disallow quotes inside interpolated expressions. String interpolation just sucks; nothing new there.

**Comment by SimonDanisch** [comment]
Ah yeah, this makes sense, as the "end method" was the first to use strings.
Still can't build a minimal example though!
I always get `ERROR: LoadError: syntax: incomplete: invalid string syntax` with the correct line number (at least to the correct function), which is way better!
