### ISSUE TITLE
[ASK] Julia arithmatic operations not fast?

### ISSUE THREAD

**Issue by kokizzu** [JuliaLang/julia#10539]
I'm trying to make a program that print every 100K-th odd prime number until 10M for benchmark reasons.

```
res = [last=3]
while true
   last += 2
   prime = true
   for v in res
     if v*v > last 
       break
     end
     if last % v == 0 
       prime = false 
       break
     end
   end
   if prime
     push!(res,last)
     if length(res) % 100000 == 0 
       println(last)
     end 
     if last > 9999999 
       break
     end
   end
end
```

But Julia `0.3.6` didn't perform as fast as any other JIT/compiled language [implementations](http://kokizzu.blogspot.com/2015/03/prime-number-generator-benchmark.html).

**Comment by tkelman** [comment]
Put it in a function - `function main()` before the first line, `end; main()` after the last line. Please see the first thing in the performance tips section of the manual http://docs.julialang.org/en/release-0.3/manual/performance-tips/, and use the mailing list for questions like this. The issue tracker is for bug reports and pull requests. Thanks.

**Comment by tkelman** [comment]
This is an interesting benchmark though, putting this in a function we're still about 5x slower than clang here. Looks like almost all of the time is spent in `last % v`, anyone have any ideas why our rem is slow? Doing all operations in `UInt32` speeds things up by roughly 25%, but there's still quite a gap to clang.

**Comment by pao** [comment]
Are we calling out to libm vs. directly using a processor instruction?

**Comment by andreasnoack** [comment]
No. We are using an [intrinsic](https://github.com/JuliaLang/julia/blob/master/base/int.jl#L75)

**Comment by tkelman** [comment]
(good to hit y to canonicalize the [link](https://github.com/JuliaLang/julia/blob/288ea08b555439694780e9e7673eb0885fc95f54/base/int.jl#L75) with a sha)

**Comment by andreasnoack** [comment]
I didn't know that trick. Then it will stay the same even when the source changes?

**Comment by tkelman** [comment]
Yeah, that's the idea, very handy to have links still make sense when browsing through old issues

**Comment by tkelman** [comment]
I must've done something wrong the first time around, changing the first few lines to
```
res = [last=Int32(3)]
while true
   last += Int32(2)
```
and using 0.4, and only counting execution time, we're actually within about 25% of `clang -O2`. That's not bad at all, so nevermind.

**Comment by pao** [comment]
Thanks for the source pointer, @andreasnoack.
