### ISSUE TITLE
`map` recommendations in deprecation warnings and NEWS harmful?

### ISSUE THREAD

**Issue by garborg** [JuliaLang/julia#10537]
For the deprecated lowercase `int`, `bool`, etc.

Timings (where vector is sized so `map` takes ~1 second):
Int -> Bool: `map` 20x slower than `Vector{Bool}` which is 25% slower than `round`
Bool -> Int: `map` 20x slower than `Vector{Int}` or `round`
Int8 -> Int: `map` 15x slower than `Vector{Int}` or `round`
Int -> Float: `map` 10x slower than `Vector{Float64}` or `float`
Float64 -> Float32: `map` 50x slower than `Vector{Float32}`

(Aside: I'm also unsure why `Bool(200)` works when `Int8(200)` doesn't, if anyone wants to point me to the right discussion.)

**Comment by simonster** [comment]
Looks like there is a regression that can explain part (but not all) of the speed gap. On 0.3.6:

```julia
julia> immutable A; x::Int; end

julia> x = rand(Int, 100000000);

julia> @time map(A, x);
elapsed time: 0.8371671 seconds (800000128 bytes allocated)
```

On master:
```julia
julia> immutable A; x::Int; end

julia> x = rand(Int, 100000000);

julia> @time map(A, x);
elapsed time: 4.653523433 seconds (3814 MB allocated, 5.85% gc time in 140 pauses with 1 full sweep)
```

It doesn't look like `map_to!

**Comment by JeffBezanson** [comment]
Oh drat. This used to work, but removing the type from the first argument to `map` and `map_to!` causes us not to specialize it for every type. This is one of those heuristics.

**Comment by timholy** [comment]
Thanks for catching and plugging this.
