### ISSUE TITLE
make testall fails at markdown

### ISSUE THREAD

**Issue by Fedster** [JuliaLang/julia#10540]
Hi, 

I am on OS X 10.10.2, fortran gcc version 4.9.2 (Homebrew gcc49 4.9.2_1 --enable-fortran), julia Version 0.4.0-dev+3862 (2015-03-17 07:32 UTC) Commit b201312* (0 days old master) x86_64-apple-darwin14.1.0.

On the very latest git pul I make testall and it fails:

[lots of useless stuff before]
LINK usr/lib/julia/sys.dylib
    CC test/libccalltest.dylib
cp /usr/local/julia/usr/lib/julia/sys.ji local.ji && /usr/local/julia/usr/bin/julia -J local.ji -e 'true' && rm local.ji
    JULIA test/all
	From worker 6:	     * linalg/lapack        in  11.80 seconds
	From worker 8:	     * linalg/tridiag       in  15.30 seconds
	From worker 6:	     * linalg/givens        in   4.40 seconds
	From worker 6:	     * linalg/lu            in   0.96 seconds
	From worker 9:	     * linalg/pinv          in  20.32 seconds
	From worker 6:	     * linalg/arnoldi       in   7.79 seconds
	From worker 6:	     * keywordargs          in   1.63 seconds
	From worker 4:	     * linalg3              in  36.57 seconds
	From worker 9:	     * core                 in  16.68 seconds
	From worker 5:	     * linalg4              in  45.82 seconds
	From worker 4:	     * strings              in  17.71 seconds
	From worker 5:	     * dict                 in  10.41 seconds
	From worker 5:	     * remote               in   0.45 seconds
	From worker 5:	     * iobuffer             in   0.89 seconds
	From worker 5:	     * staged               in   0.60 seconds
	From worker 4:	     * hashing              in   6.15 seconds
	From worker 8:	     * linalg/cholesky      in  48.12 seconds
	From worker 8:	     * reduce               in   4.69 seconds
	From worker 6:	     * numbers              in  44.89 seconds
	From worker 9:	     * dates                in  44.17 seconds
	From worker 8:	     * reducedim            in  14.01 seconds
	From worker 9:	     * intfuncs             in   1.01 seconds
	From worker 6:	     * random               in  11.61 seconds
	From worker 8:	     * simdloop             in   1.92 seconds
	From worker 9:	     * blas                 in   3.21 seconds
	From worker 6:	     * fft                  in   4.18 seconds
	From worker 2:	     * linalg1              in  89.29 seconds
	From worker 8:	     * dsp                  in   5.43 seconds
	From worker 2:	     * copy                 in   2.29 seconds
	From worker 5:	     * arrayops             in  33.95 seconds
	From worker 5:	     * functional           in   1.16 seconds
	From worker 5:	     * operators            in   0.17 seconds
	From worker 5:	     * path                 in   0.05 seconds
	From worker 2:	     * fastmath             in   3.50 seconds
	From worker 5:	     * ccall                in   2.28 seconds
	From worker 2:	     * bigint               in   2.87 seconds
	From worker 8:	     * math                 in  11.84 seconds
	From worker 8:	     * spawn                      [stdio passthrough ok]
	From worker 3:	     * linalg2              in 106.14 seconds
	From worker 3:	     * backtrace            in   0.14 seconds
	From worker 3:	     * priorityqueue        in   1.18 seconds
	From worker 8:	 in   7.28 seconds
	From worker 2:	     * statistics           in  12.08 seconds
	From worker 2:	     * version              in   1.33 seconds
	From worker 2:	     * resolve              in   4.79 seconds
	From worker 8:	     * file                 in   9.13 seconds
	From worker 3:	     * arpack               in  11.44 seconds
	From worker 2:	     * pollfd               in   2.87 seconds
	From worker 2:	     * complex              in   3.99 seconds
	From worker 8:	     * mpfr                 in   5.31 seconds
	From worker 8:	     * floatapprox          in   0.34 seconds
	From worker 2:	     * socket               in   1.65 seconds
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
	From worker 7:	     * linalg/triangular    in 125.43 seconds
	From worker 2:	     * reflection           in   0.99 seconds
	From worker 7:	     * regex                in   0.58 seconds
	From worker 5:	     * sorting              in  30.62 seconds
	From worker 2:	     * float16              in   1.45 seconds
	From worker 5:	     * sysinfo              in   1.50 seconds
	From worker 2:	     * rounding             in   1.00 seconds
	From worker 2:	     * mod2pi               in   0.24 seconds
	From worker 7:	     * combinatorics        in   3.17 seconds
	From worker 2:	     * euler                in   1.44 seconds
	From worker 7:	     * show                 in   3.24 seconds
	From worker 8:	     * readdlm              in   9.05 seconds
	From worker 3:	     * broadcast            in  13.94 seconds
	From worker 2:	     * lineedit             in   3.83 seconds
	From worker 3:	     * replutil             in   0.89 seconds
	From worker 3:	     * test                 in   0.35 seconds
	From worker 3:	     * goto                 in   0.05 seconds
	From worker 3:	     * llvmcall             in   0.09 seconds
	From worker 7:	     * replcompletions      in   3.01 seconds
	From worker 2:	     * sets                 in   2.77 seconds
	From worker 2:	     * meta                 in   0.25 seconds
	From worker 8:	     * repl                 in   5.09 seconds
	From worker 8:	     * libgit2              in   0.02 seconds
	From worker 8:	     * docs                 in   0.07 seconds
	From worker 7:	     * nullable             in   2.50 seconds
	From worker 7:	     * base64               in   0.30 seconds
	From worker 7:	     * parser               in   0.19 seconds
exception on 8: ERROR: LoadError: BoundsError: attempt to access ()
  at index [1]
 in runtests at /usr/local/julia/test/testdefs.jl:77
 in anonymous at multi.jl:833
 in run_work_thunk at multi.jl:584
 in anonymous at task.jl:833
while loading markdown.jl, in expression starting on line 83
	From worker 2:	     * profile              in   3.34 seconds
	From worker 3:	     * grisu                in   5.84 seconds
	From worker 7:	     * serialize            in   2.74 seconds
	From worker 9:	     * sparse               in  57.08 seconds
	From worker 5:	     * ranges               in  21.07 seconds
	From worker 4:	     * subarray             in 101.89 seconds
	From worker 6:	     * bitarray             in  84.00 seconds
ERROR: LoadError: LoadError: BoundsError: attempt to access ()
  at index [1]
 in anonymous at task.jl:1384
while loading markdown.jl, in expression starting on line 83
while loading /usr/local/julia/test/runtests.jl, in expression starting on line 3

	From worker 8:	     * markdown            make[1]: *** [all] Error 1
make: *** [testall] Error 2

**Comment by tkelman** [comment]
worker 8 was the one that exited, and it was running docs - this appears to have been caused by 66e1cbed3bf1784b9a7b4c08b76e956345ae2773 ?

cc @one-more-minute @ahayd

**Comment by peter1000** [comment]
Me too: Arch Linux: I just checkout from git 

Version 0.4.0-dev+3862 (2015-03-17 07:32 UTC)
Commit b201312 (0 days old master)
x86_64-unknown-linux-gnu


```
    JULIA test/all
	From worker 4:	     * linalg3              in  54.18 seconds
	From worker 4:	     * linalg/lapack        in   6.41 seconds
	From worker 5:	     * linalg4              in  68.40 seconds
	From worker 5:	     * linalg/tridiag       in   8.29 seconds
	From worker 5:	     * linalg/pinv          in  15.02 seconds
	From worker 5:	     * linalg/givens        in   3.71 seconds
	From worker 2:	     * linalg1              in 131.35 seconds
	From worker 2:	     * linalg/lu            in   0.61 seconds
	From worker 5:	     * linalg/cholesky      in  45.88 seconds
	From worker 2:	     * linalg/arnoldi       in  10.66 seconds
	From worker 2:	     * keywordargs          in   2.57 seconds
	From worker 3:	     * linalg2              in 149.49 seconds
	From worker 5:	     * core                 in  23.71 seconds
	From worker 3:	     * strings              in  28.40 seconds
	From worker 3:	     * dict                 in  15.46 seconds
	From worker 3:	     * hashing              in   8.50 seconds
	From worker 3:	     * remote               in   0.54 seconds
	From worker 3:	     * iobuffer             in   1.38 seconds
	From worker 3:	     * staged               in   0.95 seconds
	From worker 2:	     * numbers              in  66.28 seconds
	From worker 4:	     * linalg/triangular    in 161.45 seconds
	From worker 4:	     * reduce               in   6.40 seconds
	From worker 5:	     * dates                in  71.95 seconds
	From worker 4:	     * reducedim            in  20.74 seconds
	From worker 4:	     * intfuncs             in   1.81 seconds
	From worker 4:	     * simdloop             in   2.62 seconds
	From worker 3:	     * arrayops             in  50.80 seconds
	From worker 5:	     * random               in  20.17 seconds
	From worker 4:	     * blas                 in   3.78 seconds
	From worker 3:	     * fft                  in   5.50 seconds
	From worker 5:	     * dsp                  in   8.63 seconds
	From worker 5:	     * copy                 in   4.07 seconds
	From worker 5:	     * math                 in  18.60 seconds
	From worker 5:	     * fastmath             in   5.67 seconds
	From worker 5:	     * functional           in   2.34 seconds
	From worker 5:	     * operators            in   0.35 seconds
	From worker 5:	     * path                 in   0.08 seconds
	From worker 5:	     * ccall                in   4.08 seconds
	From worker 5:	     * bigint               in   5.22 seconds
	From worker 4:	     * sparse               in  80.45 seconds
	From worker 4:	     * statistics           in  16.30 seconds
	From worker 5:	     * sorting              in  50.05 seconds
	From worker 5:	     * backtrace            in   0.25 seconds
	From worker 4:	     * spawn                      [stdio passthrough ok]
	From worker 5:	     * priorityqueue        in   1.90 seconds
	From worker 4:	 in  11.33 seconds
	From worker 5:	     * arpack               in  16.22 seconds
	From worker 4:	     * file                 in  10.12 seconds
	From worker 5:	     * version              in   2.50 seconds
	From worker 5:	     * pollfd               in   3.22 seconds
	From worker 4:	     * resolve              in   8.17 seconds
	From worker 5:	     * mpfr                 in   7.96 seconds
	From worker 5:	     * complex              in   5.81 seconds
	From worker 5:	     * socket               in   2.55 seconds
	From worker 5:	     * floatapprox          in   0.60 seconds
	From worker 4:	     * broadcast            in  19.49 seconds
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
	From worker 4:	     * reflection           in   1.90 seconds
	From worker 4:	     * regex                in   0.86 seconds
	From worker 4:	     * float16              in   2.22 seconds
	From worker 5:	     * readdlm              in  14.28 seconds
	From worker 4:	     * combinatorics        in   4.15 seconds
	From worker 5:	     * sysinfo              in   1.98 seconds
	From worker 4:	     * rounding             in   1.61 seconds
	From worker 4:	     * mod2pi               in   0.26 seconds
	From worker 4:	     * euler                in   1.77 seconds
	From worker 2:	     * subarray             in 208.93 seconds
	From worker 4:	     * show                 in   4.45 seconds
	From worker 4:	     * replcompletions      in   4.97 seconds
	From worker 2:	     * lineedit             in   5.88 seconds
	From worker 2:	     * replutil             in   1.85 seconds
	From worker 4:	     * repl                 in   8.09 seconds
	From worker 2:	     * sets                 in   5.71 seconds
	From worker 2:	     * goto                 in   0.09 seconds
	From worker 3:	     * bitarray             in 172.97 seconds
	From worker 2:	     * llvmcall             in   0.20 seconds
	From worker 4:	     * test                 in   0.58 seconds
	From worker 4:	     * meta                 in   0.39 seconds
	From worker 2:	     * nullable             in   4.29 seconds
	From worker 2:	     * libgit2              in   0.12 seconds
	From worker 2:	     * docs                 in   0.11 seconds
	From worker 4:	     * profile              in   5.21 seconds
	From worker 4:	     * base64               in   0.51 seconds
	From worker 4:	     * parser               in   0.34 seconds
exception on 2: ERROR: LoadError: BoundsError: attempt to access ()
  at index [1]
 in runtests at /git_julia/test/testdefs.jl:77
 in anonymous at multi.jl:833
 in run_work_thunk at multi.jl:584
 in anonymous at task.jl:833
while loading markdown.jl, in expression starting on line 83
	From worker 3:	     * grisu                in  10.36 seconds
	From worker 4:	     * serialize            in   4.58 seconds
	From worker 5:	     * ranges               in  43.06 seconds
ERROR: LoadError: LoadError: BoundsError: attempt to access ()
  at index [1]
 in anonymous at task.jl:1384
while loading markdown.jl, in expression starting on line 83
while loading /git_julia/test/runtests.jl, in expression starting on line 3

	From worker 2:	     * markdown            Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
Makefile:496: recipe for target 'testall' failed
make: *** [testall] Error 2

```

**Comment by peter1000** [comment]
Re-compiled

JULIA test/all
    SUCCESS


@tkelman Thanks
