### ISSUE TITLE
PyCall throws shlib_ext missing error

### ISSUE THREAD

**Issue by ibell** [JuliaLang/julia#10549]
I think this is a bug with Julia, not PyCall, but I'm not sure...  I see the same error on windows and linux.  See also https://github.com/stevengj/PyCall.jl/issues/125

```
ian@ian-VirtualBox:~/Desktop$ julia
OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3864 (2015-03-17 19:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 09604d6 (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using PyCall
ERROR: LoadError: LoadError: UndefVarError: shlib_ext not defined
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/ian/.julia/v0.4/PyCall/src/pyinit.jl, in expression starting on line 13
while loading /home/ian/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 133
```

**Comment by ihnorton** [comment]
Need to do `Pkg.checkout("PyCall")` until a new version is tagged. See #10328 and https://github.com/stevengj/PyCall.jl/issues/119

**Comment by ibell** [comment]
Evidently I am up-to-date and no love
```
julia> Pkg.checkout("PyCall")
INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: No packages to install, update or remove
```

**Comment by ihnorton** [comment]
I guess that one wasn't fixed yet. Not a julia bug, just caught on the bleeding edge of API cleanup (#10328). Fix inbound but probably won't get merged until tomorrow.

**Comment by ibell** [comment]
okiedokie, thanks anyway

**Comment by sax25** [comment]
i get the same error (shlib_ext not defined).
tried to checkout newer version of PyCall(and PyPlot), but also seem to have the latest version already. 
"PyCall"            => v"0.7.3+"
"PyPlot"            => v"1.5.1+"  

my Julia-Version: 0.4.0-dev+3981 (2015-03-25 02:18 UTC)

**Comment by ihnorton** [comment]
see https://github.com/JuliaLang/METADATA.jl/pull/2348
