### ISSUE TITLE
move blas_ functions into BLAS?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#10548]
We have Base.blas_vendor and Base.blas_set_num_threads (which is exported). Could these be moved into the BLAS module instead?

**Comment by tkelman** [comment]
This seems like it should be fine to me. A handful of packages do need to check blas_vendor during their bindeps setup, but referring to the function from a different module depending on VERSION should be simple enough to deal with.

**Comment by andreasnoack** [comment]
Yes. I think this is fine.

**Comment by ViralBShah** [comment]
Yeah - should be ok. When we wrap other BLAS libraries, those modules should provide the same interfaces as well.
