### ISSUE TITLE
BigInt in loops: Very slow / memory allocated

### ISSUE THREAD

**Issue by peter1000** [JuliaLang/julia#10553]
Just played around and saw this.

#### example code
```
# test1: Int128
function test1()
    for i in 1:Int128(17000000)
    end
end

# test2: BigInt
function test2()
    for i in 1:BigInt(17000000)
    end
end

test1()
test2()

println("\n>>>>>>>>>>>>>>test1:Int128")
@time test1()
@time test1()
@time test1()

println("\n>>>>>>>>>>>>>>test2:BigInt")
@time test2()
@time test2()
@time test2()
```

#### RESUTL:

**test1:Int128**

* elapsed time: **0.002589673 seconds** (**30 kB** allocated)
* elapsed time: 4.766e-6 seconds (80 bytes allocated)
* elapsed time: 3.005e-6 seconds (80 bytes allocated)

**test2:BigInt**

* elapsed time: **12.609860677 seconds** (**1815 MB** allocated, 18.62% gc time in 83 pauses with 0 full sweep)
* elapsed time: 12.971541848 seconds (1815 MB allocated, 18.77% gc time in 83 pauses with 0 full sweep)
* elapsed time: 12.701018697 seconds (1815 MB allocated, 19.60% gc time in 83 pauses with 0 full sweep)

Cheers
P

do some of the other issues relate to this: https://groups.google.com/forum/#!searchin/julia-users/BigInt/julia-users/6iKRmdIptJk/3W0MR2FE7TkJ

**Comment by timholy** [comment]
See #10084 (closing in favor of that, since it's a potential fix).

**Comment by JeffBezanson** [comment]
Dup of #4176 

Also, the reason the times are so small in the first case is that the loop does nothing and so is removed completely. With all the extra code needed for BigInt, the compiler can't figure out that it's safe to remove (it calls a C library).
