### ISSUE TITLE
Strange Performance: while i < function_arg  in combination with print

### ISSUE THREAD

**Issue by peter1000** [JuliaLang/julia#10557]
#### I'm not usre if this is a bug or a mistake on my side.

I came across a strange performance problem:
*e.g. if `i` is an Int128 and compared to an function argument it is extreme slow - if at the end the value of i is printed
For loops seem ok

#### example code:

```
#const repeatloop_global = Int128(170141183460469231731687303715884105727)

const repeatloop_global = Int128(9999999999)

# for loop: repeatloop_global
function test1()
    i::Int128=0
    for i in 1:repeatloop_global
    end
    println("*test1* for loop: repeatloop_global finished: end i: $i")
end

# for loop: argument: repeatloop_arg
function test2(repeatloop_arg)
    i::Int128=0
    for i in 1:repeatloop_arg
    end
    println("*test2* for loop: argument: repeatloop_arg finished: end i: $i")
end

# while loop: repeatloop_global
function test3()
    i::Int128=0
    while i < repeatloop_global
        i += 1
    end
    println("*test3* while loop: repeatloop_global finished: end i: $i")
end

# while loop: argument: repeatloop_arg
function test4(repeatloop_arg)
    i::Int128=0
    while i < repeatloop_arg
        i += 1
    end
    println("*test4* while loop: argument: repeatloop_arg finished: end i: $i")
end


const repeatloop_arg = Int128(9999999999)


test1()
test2(repeatloop_arg)
test3()
test4(repeatloop_arg)

println("\n**test1**")
@time test1()
@time test1()
@time test1()

println("\n**test2**")
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)

println("\n**test3**")
@time test3()
@time test3()
@time test3()

println("\n**test4**")
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)

```
#### RESULTS

**test1**
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: 0.00338743 seconds (30 kB allocated)
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: **4.5806e-5 seconds** (776 bytes allocated)
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: 3.4806e-5 seconds (776 bytes allocated)

**test2**
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 7.405e-5 seconds (808 bytes allocated)
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: **3.6838e-5 seconds** (808 bytes allocated)
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 4.4026e-5 seconds (808 bytes allocated)

**test3**
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 6.3252e-5 seconds (792 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: **3.39e-5 seconds** (792 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 3.2055e-5 seconds (792 bytes allocated)

**test4**
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 13.465803199 seconds (808 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: **13.457124327 seconds** (808 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 13.47339729 seconds (808 bytes allocated)

IF one comments the `println` it runs ok.

Is that some kind of bug or a mistake on my side?

Cheers
P

**Comment by andreasnoack** [comment]
I don't think `test4` is extremely slow. It is a quite long loop you are running so it is just the time it takes to loop from one to `10^10`. I think the difference is that in `test1` and `test3` the compiler can completely eliminate the loop and just calculate the result once and in `test2` the compiler is able to optimize the for loop away and calculate the result as a function of the argument. For some reason the same is not possible for the while loop in `test4`. When you comment out the `print` statement, the function doesn't use `i` for anything and can therefore optimize the loop away. You could try to return `i` instead of printing it. It will also be "slow". I don't think that `Int128` has anything to do with the story.

**Comment by peter1000** [comment]
@andreasnoack  > I don't think that Int128 has anything to do with the story.

**I think there are a couple of strange things:**

1. why does the `while loop` with a global variable work fine but not with the argument
- for loop works with both just fine

2. why is the combination of Int128 make such huge difference in the one case

3. Slow is maybe not for the many loops - but slow is test4 in comparison to test 1-3

#### Removing Int128 works ok 

```
const repeatloop_global = 9999999999

# for loop: repeatloop_global
function test1()
    i=0
    for i in 1:repeatloop_global
    end
    println("*test1* for loop: repeatloop_global finished: end i: $i")
end

# for loop: argument: repeatloop_arg
function test2(repeatloop_arg)
    i=0
    for i in 1:repeatloop_arg
    end
    println("*test2* for loop: argument: repeatloop_arg finished: end i: $i")
end

# while loop: repeatloop_global
function test3()
    i=0
    while i < repeatloop_global
        i += 1
    end
    println("*test3* while loop: repeatloop_global finished: end i: $i")
end

# while loop: argument: repeatloop_arg
function test4(repeatloop_arg)
    i=0
    while i < repeatloop_arg
        i += 1
    end
    println("*test4* while loop: argument: repeatloop_arg finished: end i: $i")
end

const repeatloop_arg = 9999999999

test1()
test2(repeatloop_arg)
test3()
test4(repeatloop_arg)

println("\n**test1**")
@time test1()
@time test1()
@time test1()

println("\n**test2**")
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)

println("\n**test3**")
@time test3()
@time test3()
@time test3()

println("\n**test4**")
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)

```
##### Result for 3, 4

**test3**
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 6.8697e-5 seconds (784 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: **5.4434e-5 seconds** (784 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 5.19e-5 seconds (784 bytes allocated)

**test4**
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 5.4076e-5 seconds (800 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: **3.8428e-5 seconds** (800 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 4.8516e-5 seconds (800 bytes allocated)


#### Removing print and return i: not ok
```
const repeatloop_global = Int128(9999999999)

# for loop: repeatloop_global
function test1()
    i::Int128=0
    for i in 1:repeatloop_global
    end
    return i
end

# for loop: argument: repeatloop_arg
function test2(repeatloop_arg)
    i::Int128=0
    for i in 1:repeatloop_arg
    end
    return i
end

# while loop: repeatloop_global
function test3()
    i::Int128=0
    while i < repeatloop_global
        i += 1
    end
    return i
end

# while loop: argument: repeatloop_arg
function test4(repeatloop_arg)
    i::Int128=0
    while i < repeatloop_arg
        i += 1
    end
    return i
end

const repeatloop_arg = Int128(9999999999)

result1 = test1()
println("result1: $result1")

result2 = test2(repeatloop_arg)
println("result2: $result2")

result3 = test3()
println("result3: $result3")

result4 = test4(repeatloop_arg)
println("result4: $result4")

println("\n**test1**")
@time test1()
@time test1()
@time test1()

println("\n**test2**")
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)
@time test2(repeatloop_arg)

println("\n**test3**")
@time test3()
@time test3()
@time test3()

println("\n**test4**")
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)
@time test4(repeatloop_arg)

```

##### Result

**test3**
elapsed time: 3.835e-6 seconds (72 bytes allocated)
elapsed time: **3.463e-6 seconds** (72 bytes allocated)
elapsed time: 3.752e-6 seconds (72 bytes allocated)

**test4**
elapsed time: 13.526696832 seconds (72 bytes allocated)
elapsed time: **13.537451125 seconds** (72 bytes allocated)
elapsed time: 13.510820868 seconds (72 bytes allocated)

**Comment by andreasnoack** [comment]
1. The global variable is `const` so the results of `test1` and `test3` are always the same and can be precomputed.
2. Apparently, LLVM 3.3 can optimize the for loop but not the while loop. I can see that @simonster has added a `fixed in LLVM 3.5` flag so this might be fixed in LLVM which the next release of Julia will be based on.
3. You might be right that it is the use of `Int128` that prevents LLVM from optimizing the while loop.
4. `test1-3` are not running any loops so the question is if Julia should be able to optimize away the while loop in `test4`.

In most use cases, a loop is actually doing something useful, so these kinds of tests are not indicative for the speed of real use cases.

@simonster Can you give some details?

**Comment by simonster** [comment]
Output for the code from the first post with Julia 6d68792/LLVM 3.6:

```
*test1* for loop: repeatloop_global finished: end i: 9999999999
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
*test3* while loop: repeatloop_global finished: end i: 9999999999
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999

**test1**
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: 0.003555868 seconds (30 kB allocated)
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: 2.8392e-5 seconds (776 bytes allocated)
*test1* for loop: repeatloop_global finished: end i: 9999999999
elapsed time: 2.0001e-5 seconds (776 bytes allocated)

**test2**
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 2.0418e-5 seconds (808 bytes allocated)
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 1.9365e-5 seconds (808 bytes allocated)
*test2* for loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 3.5641e-5 seconds (808 bytes allocated)

**test3**
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 3.1465e-5 seconds (792 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 2.023e-5 seconds (792 bytes allocated)
*test3* while loop: repeatloop_global finished: end i: 9999999999
elapsed time: 1.8899e-5 seconds (792 bytes allocated)

**test4**
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 1.8498e-5 seconds (808 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 4.106e-5 seconds (808 bytes allocated)
*test4* while loop: argument: repeatloop_arg finished: end i: 9999999999
elapsed time: 2.8565e-5 seconds (808 bytes allocated)
```

**Comment by JeffBezanson** [comment]
@peter1000 What you're seeing here is that the optimization that can remove an entire loop is a bit fragile; change the surrounding code a bit and it might not work. Apparently with LLVM 3.5+ it's less fragile. This is not a problem in practice because people don't generally need to run empty loops.
