### ISSUE TITLE
Deprecation warnings are numerous, backtrace not useful

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#10563]
The main issue here is that most deprecation warnings I'm seeing only point to `./deprecated.jl:40`, which makes it hard to determine what needs to change:

```julia
julia> using BinDeps
WARNING: parseint(s,base) is deprecated, use parse(Int,s,base) instead.
 in depwarn at ./deprecated.jl:40
WARNING: uint8(r::UnitRange) is deprecated, use map(UInt8,r) instead.
 in depwarn at ./deprecated.jl:40
WARNING: parseint(s,base) is deprecated, use parse(Int,s,base) instead.
 in depwarn at ./deprecated.jl:40
WARNING: parseint(s,base) is deprecated, use parse(Int,s,base) instead.
 in depwarn at ./deprecated.jl:40
WARNING: uint8(r::UnitRange) is deprecated, use map(UInt8,r) instead.
 in depwarn at ./deprecated.jl:40
```

As a consequence, there are times when I see dozens of copies the same warning.  The code for `depwarn` seems to think these are coming from different callers, but seemingly doesn't want to pass on that information.  E.g., when attempting to build

```julia
julia> Pkg.build("VideoIO")
... <snip - pages of various deprecation warnings like those below >
WARNING: c_malloc is deprecated, use Libc.malloc instead.
 in depwarn at ./deprecated.jl:40
WARNING: c_malloc is deprecated, use Libc.malloc instead.
 in depwarn at ./deprecated.jl:40
WARNING: c_malloc is deprecated, use Libc.malloc instead.
 in depwarn at ./deprecated.jl:40
... <snip - repeated about 40 more times, plus others>
```

The amount of useless output is rather ridiculous.

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+3882
Commit 76b40df* (2015-03-18 14:13 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by kmsquire** [comment]
Actually, I think this is probably related to line numbers not being available for precompiled functions.  Anyone know which issue that is?

**Comment by kmsquire** [comment]
FWIW, `julia --inline=no` (from #1334) does not help.

**Comment by timholy** [comment]
It will if you delete `sys.so`.

**Comment by ivarne** [comment]
IIUC sys.jl shouldn't matter unless the deprecated functions isn't still in precompile.jl

**Comment by vtjnash** [comment]
@kmsquire line number information should be read fine on llvm33. Only in later llvm versions is it broken on Dwarf (Mac)

**Comment by kmsquire** [comment]
Recompiling from a fresh checkout restored normal behavior, so I must have had some older libraries lying around.  Probably could have been fixed by something simpler, but this was easy enough.

Thanks all, and sorry for the noise.  Cheers!

**Comment by SimonDanisch** [comment]
This seems to happen also on a complete fresh build. 
When I run runtests.jl from GLPlot this shows up:
```Julia
WARNING: float32(x) is deprecated, use Float32(x) instead.
 in float32 at deprecated.jl:29
 in anonymous at no file:161
 in include_from_node1 at loading.jl:129
```
This is:
```
Julia Version 0.4.0-dev+3952
Commit 5587ca3 (2015-03-21 00:37 UTC)
Platform Info:
  System: Windows 10 (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

I remember that it was sometimes even just `WARNING: float32(x) is deprecated, use Float32(x) instead.`

I'll try a complete rebuild on windows 8.1 as well.
