### ISSUE TITLE
No error message when attempting to build a non-existent package

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#10564]
It would probably be good to let the user knew he did something wrong:

```julia
julia> Pkg.build("HomeBrew")

julia> Pkg.build("Homebrew")
INFO: Building Homebrew
```

**Comment by kmsquire** [comment]
Thanks!

**Comment by tkelman** [comment]
could be a little more descriptive here, suggest running `Pkg.add("foo")`

**Comment by pao** [comment]
That's only sensible if the package is in METADATA.

**Comment by tkelman** [comment]
Good point. Not everyone will know what "registered" means though. And I don't think `Pkg.build` differentiates in any way between registered and unregistered packages, so probably best to just say the package is not installed.
