### ISSUE TITLE
Parsing anonymous function does not find function argument

### ISSUE THREAD

**Issue by thorstendahmen** [JuliaLang/julia#10573]
Hi,

I am trying to construct an anonymous function with metaprogramming but it does not work and from the example below I got the feeling that something in Julia does not work as it should. The example in test1 just works fine, but when I am trying to do exactly the same in test2 and just create the anonymous function with a string, I get the error "f not defined". Is this a bug or does Julia have another feature for this purpose?
Thanks, Thorsten

    function test1(f::Function)
        x->f(x)+2
    end

    function test2(f::Function)
        eval(parse("x->f(x)+2"))
    end

    x = x->3.*x

    a = test1(x)
    b = test2(x)

    println(a(2))
    println(b(2))

**Comment by dhoegh** [comment]
The reason for this is `eval` evaluates in global scope see the http://stackoverflow.com/questions/28882241/eval-in-function-scope-accessing-function-args
