### ISSUE TITLE
Test results printed in red are confusing.

### ISSUE THREAD

**Issue by tobig** [JuliaLang/julia#10574]
When running 'make test' the test results are printed in red, which is confusing as red is commonly used to indicate failure. I propose to use neither red nor green in case the color for cases where the color does not indicate the result of the test.

**Comment by ViralBShah** [comment]
I don't know - it is a valid point, but people are used to the red. You could submit a PR and we can see how it goes.

**Comment by tkelman** [comment]
See #7673 - didn't stick last time.

**Comment by tkelman** [comment]
We could add a green checkmark or something right before the `in  x.xx seconds`

**Comment by nalimilan** [comment]
Better find another color. The fact that two people considered it worth filing a bug/PR is the sign that red is problematic. Is it such a big deal to choose a color that's already been used in the make process? Shouldn't be a big issue.

Anyway, the blue suggested by https://github.com/JuliaLang/julia/pull/7673 is quite legible even on dark terminals when a bold font is used:
`echo -e "Default \e[1;34mBlue"`

**Comment by tkelman** [comment]
Or just get rid of the color code for this and have it use the default.
