### ISSUE TITLE
make parse() handle comments and optionally not add line numbers

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#10578]
Currently (version 0.3.2) `parse()` always introduces a few line numbers (not sure why it starts at line #2 here): 

```
julia> jt = """for i in 1:10 
               println(i) 
           end 
   """ 
"for i in 1:10\n            println(i)\n        end\n" 

julia> parse(jt) 
:(for i = 1:10 # line 2:               <-------------------- ?
    println(i) 
end) 

julia> 
```

but doesn't retain existing comments: 

```
julia> jt = """for i in 1:10 
             # printing now           <--------------------- ?
             println(i) 
           end 
   """ 
 julia> parse(jt)
:(for i = 1:10 # line 3:
    println(i)
end)
```

It would be useful if line numbers could be switched off, and if existing comments could be preserved.

**Comment by mbauman** [comment]
It took me a little while to understand the line numbers, myself.  They're not annotating the line they are on, but rather, the *following* line.  It's not really "adding comments" - we simply choose to display them as comments to make things human-readable. It's a lot easier to display them that way, as opposed to worrying about alignment and spacing with a prefixed `#= Line 3: =# println(i)`.  Take a look at `Meta.show_sexpr(parse(jt))` for an alternative way to display this information.

What's your use-case for wanting them to be turned off?

As far as retaining existing comments, I don't think there's an existing issue for that, but I'd like to see that, too. But it's a very low priority.  The main reason I think it'd be cool is because then Julia would basically have a complete code-formatting tool built into itself.  Again, I'm curious what your use-case is here.

**Comment by mbauman** [comment]
See https://github.com/jakebolewski/JuliaParser.jl/issues/4

**Comment by jakebolewski** [comment]
Comments can be passed through using the `Expr(:meta, ...)` functionality we have now.

**Comment by cormullion** [comment]
@mbauman " code-formatting tool " was what I had in mind, too.

**Comment by jakebolewski** [comment]
@cormullion this is something best developed outside of Base.  All the tools are there, someone just needs to do the work.

**Comment by StefanKarpinski** [comment]
Right, the only thing missing for to allow code formatting is retaining comments in the highest-level AST. I would welcome a PR adding that; @JeffBezanson might object, but I think that as long as it's not too expensive and the first lowering pass strips the comments out, it should be acceptable.

**Comment by peter1000** [comment]
> @mbauman It took me a little while to understand the line number annotations, myself. They're not annotating the line they are on, but rather, the following line.

Maybe to specify this a bit more: `line number annotations` is not the next line but the next `code line`.

1. this makes it a bit less useful as documentation tool.
2. (Maybe because of that) the last `code part` has never a line number annotations which is also not very useful for documentation.

Example:

```
txt ="""begin          
                        #line 1
a=1                     #line 2
                        #line 4
                        #line 5
                        #line 6
function tests()        #line 7
                        #line 8
                        #line 9
                        #line 10
    a=f                 #line 11
                        #line 12
                        #line 13
end                     #line 14
                        #line 15
                        #line 16
const gg = 5            #line 17
                        #line 18
end 
"""
println(parse(txt))


```

OUTPUT

```
begin  # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3:
    a = 1 # line 7:
    function tests() # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11:
        a = f
    end # line 17:
    const gg = 5
end

```

NOTE: 

1. function tests() has `line 11` eventhough it is on line 7

2. const gg = 5* has no line annotaion

I think it would be really helpful if at least the last part gets also a line number and if possible the start line is also returned.

**Comment by peter1000** [comment]
> @mbauman It took me a little while to understand the line number annotations, myself. They're not annotating the line they are on, but rather, the following line.

Maybe to specify this a bit more: `line number annotations` is not the next line but the next `code line`.


* the last `code part` has never a line number annotations which makes it less useful for documentation.

Example:

```
txt ="""begin          
                        #line 1
a=1                     #line 2
                        #line 4
                        #line 5
                        #line 6
function tests()        #line 7
                        #line 8
                        #line 9
                        #line 10
    a=f                 #line 11
                        #line 12
                        #line 13
end                     #line 14
                        #line 15
                        #line 16
const gg = 5            #line 17
                        #line 18
end 
"""
println(parse(txt))


```

OUTPUT

```
begin  # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3:
    a = 1 # line 7:
    function tests() # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11:
        a = f
    end # line 17:
    const gg = 5
end

```

NOTE: 

1. function tests() has `line 11` eventhough it is on line 7

2. const gg = 5* has no line annotaion

I think it would be really helpful if at least the last part gets also a line number and if possible the start line is returned.

**Comment by toivoh** [comment]
It days `#line 7` just above the function and `#line 17` just above the constant in your example. The only parts of the original source which are missing line numbers are `begin` and `end`. Is your issue about which line number info is present,  or how it is used/presented? 

I wrote the code that prints those `#line 7:` comments. The AST format mixes expressions and line number annotations in sequence, where a line number annotation applies to the expression(s) that follows is. This is a very reasonable format, I think. But the way it's printed was the only reasonable way I could come up with. Suggestions for improvements are of course welcome!

**Comment by peter1000** [comment]
**toivoh** thanks for the explanation: now it is clearer for me. Yes I think the way it's printed is a bit confusing.

Instead of this grouping
```
begin  # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3:
    a = 1 # line 7:
    function tests() # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11:
        a = f
    end # line 17:
    const gg = 5
end
```

like this but than one gets the comment lines

```
begin 
    # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 3::  a = 1 
    # line 7:  function tests() 
    # /home/workerm/0__DATA__0/TEST_LEXICON/testing.jl, line 11: a = f
    # line 17: const gg = 5
end
```

Maybe in the documentation this could be mentioned or so ? not sure though.

**Comment by KristofferC** [comment]
For a "concrete syntax tree" we have https://github.com/ZacLN/CSTParser.jl. I don't think this issue has anything really actionable.

**Comment by chakravala** [comment]
It's fairly easy to write your own recursive function that can filter out `:line` blocks, Reduce.jl now ships with one too that can be accessed with [`Reduce.linefilter(::Expr)`](https://github.com/chakravala/Reduce.jl/blob/master/src/parser.jl#L292-L313):

```Julia
"""
    linefilter(::Expr)
Recursively filters out :line blocks from Expr objects
"""
function linefilter(e::Expr)
    total = length(e.args)
    i = 0
    while i < total
        i += 1
        if e.args[i] |> typeof == Expr
            if e.args[i].head == :line
                deleteat!(e.args,i)
                total -= 1
                i -= 1
            else
                e.args[i] = linefilter(e.args[i])
            end
        end
    end
    return e
end
```
