### ISSUE TITLE
mod1 is missing a bunch of methods that exist on mod

### ISSUE THREAD

**Issue by tomasaschan** [JuliaLang/julia#10585]
After some discussion in the #julia irc today and yesterday, it was brought to my attention that `mod` has a number of methods that `mod1` is missing. This is easiest illustrated by the following:

``` julia
julia> methods(mod1)
#2 methods for generic function "mod1":
mod1{T<:Real}(x::T<:Real,y::T<:Real) at operators.jl:134
mod1(x::Real,y::Real) at promotion.jl:180
julia> methods(mod)
#30 methods for generic function "mod":
mod(x::Bool,y::Bool) at bool.jl:59
mod(x::Signed,y::Unsigned) at int.jl:61
mod(x::Unsigned,y::Signed) at int.jl:62
# ... the list goes on for a while longer...
```

Now, a lot of the difference in _number of methods_ is by the fact that `mod1` is implemented for two same-type `Real`s in terms of `mod`, and for different type `Real`s as a call to `mod1(promote(x,y)...)`, so a lot of the special cases of `mod` are already covered.

However, there are also a bunch of methods of `mod` that apply to arrays and ranges, as well as a few for `Base.Dates.Period`, and the user I chatted with in the irc channel had to use `mod` for his/her problem although `mod1` was more appropriate for the problem, because he/she needed support for arrays.

Is there a good argument for this? Are there any methods of `mod` where it _doesn't_ make sense to have a corresponding method of `mod1`?

**Comment by mschauer** [comment]
``mod1`` is used three times in base, so there is no strong demand for completeness of ``mod1`` from the point of advancing julia itself, so it depends on what users need. But more important imho is fixing #5570 if you are interested.

**Comment by tlycken** [comment]
@mschauer Interesting. I might take a look at that if I have the time.

FWIW, here's a complete list of methods of `mod` with arguments that are not both `Real`s:

```julia
mod{S,T}(A::Range{S},B::Range{T}) at array.jl:784
mod{S,T}(A::AbstractArray{S,N},B::Range{T}) at array.jl:793
mod{S,T}(A::Range{S},B::AbstractArray{T,N}) at array.jl:802
mod(A::BitArray{N},B::BitArray{N}) at bitarray.jl:985
mod(A::BitArray{N},B::Array{Bool,N}) at bitarray.jl:989
mod(A::Array{Bool,N},B::BitArray{N}) at bitarray.jl:990
mod{S,T}(A::AbstractArray{S,N},B::AbstractArray{T,N}) at array.jl:811
mod(x::Bool,B::BitArray{N}) at bitarray.jl:995
mod(x::Number,B::BitArray{N}) at bitarray.jl:999
mod{T}(A::Number,B::AbstractArray{T,N}) at array.jl:822
mod(B::BitArray{N},x::Bool) at bitarray.jl:992
mod(B::BitArray{N},x::Number) at bitarray.jl:1008
mod{P<:Base.Dates.Period}(X::Union(DenseArray{P<:Base.Dates.Period,N},SubArray{P<:Base.Dates.Period,N,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}),y::Integer) at dates/periods.jl:71
mod{T}(A::AbstractArray{T,N},B::Number) at array.jl:829
mod{P<:Base.Dates.Period}(x::P<:Base.Dates.Period,y::P<:Base.Dates.Period) at dates/periods.jl:53
mod{P<:Base.Dates.Period}(x::P<:Base.Dates.Period,y::Real) at dates/periods.jl:54
mod{P<:Base.Dates.Period}(X::Union(DenseArray{P<:Base.Dates.Period,N},SubArray{P<:Base.Dates.Period,N,A<:DenseArray{T,N},I<:(Union(Range{Int64},Int64,Colon)...,),LD}),y::P<:Base.Dates.Period) at dates/periods.jl:71
```

I guess `mod1` is entirely uninteresting for dates and periods, so that leaves a bunch of combinations of arrays and ranges.

**Comment by laborg** [comment]
Broadcasting now allows to use `mod1` for arrays. And as already stated for Date.Periods `mod1` isn't in a striking need.
