### ISSUE TITLE
ERROR: LoadError: UndefVarError: DL_LOAD_PATH not defined

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#10598]
That's the error I get now with a local build on Windows

`
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3955 (2015-03-21 16:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0d8cec3* (0 days old master)
|__/                   |  x86_64-w64-mingw32

ERROR: LoadError: UndefVarError: DL_LOAD_PATH not defined
while loading C:\j\.juliarc.jl, in expression starting on line 1`

**Comment by Keno** [comment]
Can you post your `.juliarc.jl`?

**Comment by joa-quim** [comment]
Here it is. It worked till this problem arised

push!(Base.DL_LOAD_PATH, "C:/programs/ImageMagick-6.8.8")
push!(Base.LOAD_PATH, "C:/progs_cygw/GMTdev/GMT.jl/src")
#push!(Base.LOAD_PATH, "C:/progs_cygw/GMTdev/gmt-julia/GMT.jl/src")
push!(Base.LOAD_PATH, "C:/programs/Gits/IUP.jl/src")
push!(Base.LOAD_PATH, "C:/programs/Gits/IUP.jl/examples")
push!(Base.LOAD_PATH, "C:/progs_cygw/GMTdev/gmt-julia/ML.jl/src")

**Comment by Keno** [comment]
I believe it was moved to Base.Libdl

**Comment by joa-quim** [comment]
Ah, ok. Don't know why I had the name qualifier. It works well without it.
