### ISSUE TITLE
searchindex: Error / unclear results with empty str

### ISSUE THREAD

**Issue by peter1000** [JuliaLang/julia#10592]
@dcjones @StefanKarpinski

 might be related to this: **RFC: A faster string search algorithm, and an "index" function.** #3797 

I think `searchindex` gives back some quite confusing results with empty str.

#### example
```
julia> searchindex("", "t")     # What one expect: OK
0

julia> searchindex("", "")        
1

# PROBLEM: One would also expect here index 0 because there is no index 1 
julia> ""[1]
ERROR: BoundsError: attempt to access 0-element Array{UInt8,1}
  at index [1]
```

```
julia> searchindex("teststring", "t")      # What one expect: OK
1

julia> searchindex("teststring", "")
1

# PROBLEM: One would also expect here index 0 because at  index 1 is t
julia> "teststring"[1]
't'
```

probably `rsearchindex` will be similar.

see also: searchindex not accepting input `chars` https://github.com/JuliaLang/julia/pull/10587#issuecomment-84096712

**Comment by JeffBezanson** [comment]
It looks like the idea is to return 0 only if the substring is not found, and the empty string is always found.

**Comment by peter1000** [comment]
Yes I understand the idea.

But: I would suggest changing this: returning an none existing index as a valid searchindex result is probably not the best, wouldn.t you agree?
Why not return -1, or better 0 as there is no valid index to access it.

**Comment by dcjones** [comment]
I don't know, since the following is true,
```julia
""[1:0] == ""
```
I would argue that it *is* a valid match. It obeys the property that there is a match at `i` if `haystack[i:i+length(needle)-1] == needle`.

**Comment by peter1000** [comment]
@dcjones

but there is a significant difference:

* accessing `""[1:0]` works without any errors
```
julia> ""[1:0]
""
```

* accessing `""[1]` gives an error
```
julia> ""[1]
ERROR: BoundsError: attempt to access 0-element Array{UInt8,1}
  at index [1]

julia> 
```

**Comment by peter1000** [comment]
An additional confusing result is that it can find 2 things at the same index - at least it is not very clear.



```
julia> searchindex("teststring", "")
1

julia> searchindex("teststring", "t")
1
```

What will I get back if I access index 1 in the second case?

Anyway, I just wanted to point this things out ....

**Comment by JeffBezanson** [comment]
I don't think `""[1]` giving an error is relevant, since you're searching for a substring, not a character.

The property @dcjones mentions, `haystack[i:i+length(needle)-1] == needle`, is the relevant thing. It also seems to be the most concise specification for how such a function should work. If we returned 0 we'd have to say something crazy like "the result is 0 if the substring isn't found or if it is empty", and then code that wanted to test for existence of a match would have to say `if i != 0 || isempty(substr)` instead of just `if i != 0`. This is not an improvement. To design these things you have to look past first impressions and think about how they will be used.

**Comment by nalimilan** [comment]
At least Python works the same (with 0-based indexing):
```python
>>> "azerty".find("b")
-1
>>> "azerty".find("a")
0
>>> "azerty".find("")
0
>>> "azerty"[0]
'a'
```

Anyway, using `search` is probably clearer if you don't absolutely care about performance.

**Comment by peter1000** [comment]
@JeffBezanson  you have to look past first impressions and think about how they will be used.

That's right that this function want be usually used with any empty strings as arguments.
