### ISSUE TITLE
parsefloat/parseint as call

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#10594]
The `BigInt` and `BigFloat` constructors both accept string arguments:
```julia
BigInt("12")
BigFloat("1.2")
```
However for bitstypes (`Int`, `Float64`, etc), we require `parsefloat` and `parseint` for the same functionality. What about overloading `call` instead?

**Comment by StefanKarpinski** [comment]
+1

**Comment by ViralBShah** [comment]
:+1:

**Comment by dpsanders** [comment]
:+1:

**Comment by JeffBezanson** [comment]
See https://github.com/JuliaLang/julia/pull/10599#issuecomment-86662129. I may have to :-1: this.

**Comment by StefanKarpinski** [comment]
I think we could have a `big"1.2"` macro instead of this and scrap the string constructors for big ints and floats.
