### ISSUE TITLE
PC Freezes on make testall

### ISSUE THREAD

**Issue by julia-user1000** [JuliaLang/julia#10604]
I have a 4 Core_CPU notebook.

I tried limiting the test run like this: `make -j 2 testall` but it still uses all 4cpu and freezes most often.

I noticed that: [runtests.jl](https://github.com/JuliaLang/julia/blob/master/test/runtests.jl#L6)
has such a line `n = min(8, CPU_CORES, length(tests))`

Is there an otherway to limit the usuage of Core_CPU so that one can define that on the commandine.

**Comment by nalimilan** [comment]
You can simply do `make JULIA_CPU_CORES=1 testall`.

(Please use the mailing list in the future, and GitHub issues only for bug reports.)

**Comment by nalimilan** [comment]
Oh, and when you say it freezes, is it because you don't have enough RAM for all processes? Else it would be a bug.

**Comment by julia-user1000** [comment]
Thanks @nalimilan
I did add also additional swap space and set `JULIA_CPU_CORES` and could succesfully finish the tests.
