### ISSUE TITLE
Shell commands pick up different PATH when run via semicolon or run(cmd)

### ISSUE THREAD

**Issue by swt30** [JuliaLang/julia#10619]
My Python installation is in a virtualenv, which has ipython installed, but ipython is not installed to the base system. 

Starting julia from within the virtualenv and using the semicolon to change to a shell prompt:
```jl
shell> which ipython
ipython not found
```

Using a Cmd object instead:
```jl
cmd = `which ipython`
run(cmd)
~/.virtualenvs/py2/bin/ipython
```

Is this the expected behaviour? Looks like the two methods have different notions of what the PATH is.

I ask because I'm concerned about having the right version of Python available for when I use PyCall.

**Comment by StefanKarpinski** [comment]
`which` is both a command and a shell builtin in some shells (e.g. zsh):

```zsh
zsh $ which -a which
which: shell built-in command
/usr/bin/which
```

If this is the case for your shell, then it's possible that they behave differently – especially if the shell overwrites your environment upon startup (which they often do).

**Comment by swt30** [comment]
That'll be it - I'm using zsh. Anyway it looks like PyCall picks up the current virtualenv anyway, which is what I was worrying about, so no problem here.

**Comment by StefanKarpinski** [comment]
Cool. Glad that resolved it.
