### ISSUE TITLE
Segfault during package precompilation (via userimg.jl)

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#10613]
I've been tracking the latest master and I believe this issue was introduced relatively recently (< 2 weeks ago).

```julia
module TestPackage

const TpRecord = 25

const type2enum = Dict{Type,Int}()
#const type2enum = ObjectIdDict()

@doc """
text
""" ->
type Record
end

type2enum[Record] = TpRecord

end
```

On the latest master, with the above package (and `using TestPackage` in my `userimg.jl`) I get the following build error:
```
$ make
...
Enums.jl
deprecated.jl
basedocs.jl
precompile.jl
    LINK usr/lib/julia/sys0.so
    JULIA usr/lib/julia/sys.o
/bin/sh: line 1: 56758 Segmentation fault      (core dumped) /export/home/mweastwood/software/julia/usr/bin/julia -C native --build /export/home/mweastwood/software/julia/usr/lib/julia/sys -J/export/home/mweastwood/software/julia/usr/lib/julia/$([ -e /export/home/mweastwood/software/julia/usr/lib/julia/sys.ji ] && echo sys.ji || echo sys0.ji) -f sysimg.jl
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/export/home/mweastwood/software/julia/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2
```

`make clean` and `make cleanall` don't help, but changing the Dict to be an ObjectIdDict appears to fix the issue. Now I am aware that Dicts of types will not work correctly when precompiled, but you used to be able to rehash them in the module's `__init__` method.

While I was trying to find a reduced test case, I saw some evidence that commenting out the documentation string might make the problem go away as well, but I don't have time to confirm that at this very second. I will post an update later this evening.

**Comment by mweastwood** [comment]
Update: I have confirmed that the `@doc "..."` macro is necessary to trigger the segfault. However, I tested builds from well into February and I couldn't find one that passed (I was hoping to bisect).

On the one hand, it looks like this may be an issue that has existed for a while. On the other hand, this issue will never come up if you don't use Dicts of types while precompiling. So maybe this issue should just be closed?

**Comment by timholy** [comment]
HDF5 uses Dicts of types, but not (yet) `@doc`. If you change it to
```julia
const type2enum = Dict{Any,Int}()
```
do you still get the segfault?

In any event, I don't recommend closing this now; it may have to wait until someone has time to dig into it, but it's the kind of thing that should be fixed. If you have interest in helping to debug it further, you might want to see http://docs.julialang.org/en/latest/devdocs/backtraces/

**Comment by mweastwood** [comment]
Yes the segfault persists with `Dict{Any,Int}()`.

I couldn't reproduce the segfault with `gdb -x ../contrib/debug_bootstrap.gdb` or simply running make under gdb. I'm going to drop this for now in light of the fact that I don't seem to be making any forward progress on debugging this.

**Comment by carnaval** [comment]
Is this fixed ? Could not reproduce on latest master + linux/64

**Comment by mweastwood** [comment]
I also cannot reproduce this anymore.
