### ISSUE TITLE
Have an INCLUDE_PATH

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10627]
It would be useful to have `INCLUDE_PATH`, which users can have in their .juliarc.jl. This makes it convenient and not requiring `cd(...)` to the project directory every time, especially when starting on Windows or Mac by double-clicking the Julia icon. People also often want files in different directories, and a search path would be nice.

This was discussed a bit in #2283

**Comment by JeffBezanson** [comment]
`LOAD_PATH` ?

**Comment by ViralBShah** [comment]
I thought `LOAD_PATH` was only for packages. I guess we can have `include` look in `LOAD_PATH` too.

**Comment by StefanKarpinski** [comment]
That's a bad idea – we need to further conceptually separate including files and loading modules, not confuse them more. I'm not sure if `~/.juliarc.jl` really fits into that since it's not something that you include anyway.

**Comment by ViralBShah** [comment]
Given that this hasn't really come up much, and currently double clicking starts you off in your home directory, I am going to say nothing much needs to be done here.
