### ISSUE TITLE
More user-friendly methods not found error messages

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10620]
I am helping someone port their code to julia and found myself wanting better error messages for methods not found. The codebase I am working on is not long, but it is a bit involved, with lots of functions that take 10-20 arguments. It is easy to pass a wrong type for one or more arguments or pass a different number of arguments. It would be nice if the method not found error message could be improved further.

Currently, we already do this. For example:
````
julia> sin(5,5)
ERROR: MethodError: `sin` has no method matching sin(::Int64, ::Int64)
Closest candidates are:
  sin(::Real)
````

What would be nice is to also print the number of arguments in the error message and the closest candidate, if the number of arguments is greater than 5 or something.

**Comment by tkelman** [comment]
> lots of functions that take 10-20 arguments

Code smell much? In Matlab I would refactor that into taking one or a handful of structs pronto, in Julia would either a Dict or a composite type make sense for that interface?

Not to say the error couldn't be made fancier and count commas for you, but if you're having to count commas that's not a good sign...

**Comment by StefanKarpinski** [comment]
I'm not entirely sure how much clearer we could make such error messages, but @ViralBShah, if you've got ideas on how to display the more clearly, why not make it easier?

**Comment by ivarne** [comment]
An example suggestion of the output you want to get would be great! It's easier to discuss the details when we have something to look at.

**Comment by ViralBShah** [comment]
Of course, such code needs refactoring. Even during such refactoring, it would be useful to have better messages. We already took a step towards this in 0.4 with the "closest candidates", which is not present in 0.3. I can think of two things that could be useful:

1. If the number of arguments are not matching, print the number of arguments. 
2. Point out which argument is mismatched, if many arguments are of the right type. It turns out we already do this by printing the mismatched arguments in red. For anything more than a handful of arguments, it would be great to have numbers on each of the arguments

For example:
````
julia> foo(a::Int,b::Int,c::Int,d::Int,e::Int) = 1
julia> foo(1,2,3,"hello",5,6)
ERROR: MethodError: `foo` has no method matching foo(::Int64, ::Int64, ::Int64, ::ASCIIString, ::Int64, ::Int64) with 6 arguments
Closest candidates are:
  foo(::Int64, ::Int64, ::Int64, <red>::Int64</red>, ::Int64) with 5 arguments
````

**Comment by ivarne** [comment]
I think that is a good starting point for a up for grabs issue

The relevant code is in [base/replutil.jl](https://github.com/JuliaLang/julia/blob/cd85555bb5a5a1e740b1e34d8026bc14c5b5a5a8/base/replutil.jl#L124)

**Comment by jakebolewski** [comment]
I don't see how you can do this generally.  How do you distinguish arguments with default parameters / keyword arguments?   The no method error messages would become very verbose.
