### ISSUE TITLE
Writing the profile to a file

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10629]
We already allow `Profile.print()` to take an IO object. It would be very convenient if it could take a string representing the filename to write to, and save the profile to a file. Otherwise, one has to do:
````
f = open(filename, "w")
Profile.print(f)
close(f)
````

Instead, just doing this would be much more convenient, and user-friendly:
````
Profile.print(filename)
````

**Comment by StefanKarpinski** [comment]
I don't disagree but you can just do `open(Profile.print, filename)`.

**Comment by ViralBShah** [comment]
Yeah that works - but it has to be `open(Profile.print, filename, "w")`.

**Comment by StefanKarpinski** [comment]
Sure.

**Comment by ivarne** [comment]
So this is about adding:

```julia
function print{T<:Unsigned}(filename::AbstractString, data::Vector{T} = fetch(), lidict::Dict = getdict(data); kwargs...)
    open(filename) do io
        print(io, data, lidict; kwargs...)
    end
end
```
about [here](https://github.com/JuliaLang/julia/blob/cd85555bb5a5a1e740b1e34d8026bc14c5b5a5a8/base/profile.jl#L58), and testing to see that I didn't make a typo?

**Comment by timholy** [comment]
Yes, these types of fixes are usually easier to just make than they are to file an issue about :smile:.

**Comment by ivarne** [comment]
At least the code is clearer than the written description, but tests and docs are also required, so still work to do,

**Comment by ViralBShah** [comment]
I mainly filed it as a reminder for myself to get to it next week- but I was pretty sure it was a simple fix. Tests, docs etc. are usually why I try not to do things in a hurry...

**Comment by JeffBezanson** [comment]
I dislike having lots of functions that accept either an I/O stream or a file name. In the long run it's easier to keep things orthogonal, learn how to write to a file once, and use that everywhere, rather than looking up which options every function supports.

**Comment by mbauman** [comment]
For accepting a file name, eventually I'd love to try to implement the proposal in https://github.com/JuliaLang/julia/issues/7299… probably as a package first.  If that were implemented, you would say: `write("profile.txt", Profile.fetch())`.
