### ISSUE TITLE
Profiling user code

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10628]
Our profiler currently gives a bunch of output that goes deep into the base library. Often, users are just profiling their own code, and just want to look at which of their lines are consuming time. It is daunting to see the profiling information for all the internals.

I believe it should be easy enough for us to just provide profiling info on user code, avoid printing the lines that are in Base or other modules, and have an optional argument to include that information.

Ideally, I would love to see profiling information for my own code, and my own modules, and not Pkg installed modules and Base. I don't know if we can easily implement that, unless we scan METADATA.

**Comment by timholy** [comment]
I agree that massive text output is an impediment, but doesn't having a graphical output (ProfileView) eliminate this concern?

**Comment by StefanKarpinski** [comment]
Getting ProfileView to work on Windows is a non-trivial (possibly unsolved?) problem. It would be nice to make the bare-bones thing that everyone can guaranteed use as usable as possible.

**Comment by timholy** [comment]
Didn't realize that it doesn't work on Windows. Why doesn't it? It basically needs backtraces (which used to be bad, but I think @vtjnash improved them?) and Tk.

**Comment by timholy** [comment]
(or if you're using Juno, doesn't even need Tk)

**Comment by StefanKarpinski** [comment]
I've never gotten Tk working on Windows, although it may well be possible.

**Comment by timholy** [comment]
At one point long ago (probably 0.3) it worked. I haven't used julia with Windows since then, however.

I plan to update ProfileView to Gtk someyear, perhaps that would help.

**Comment by timholy** [comment]
Anyway, with regards to text output: presumably it's just a question of parsing the path. Try this and see if it looks promising:
```julia
@profile somecode
bt, lidict = Profile.retrieve()
for (k,v) in lidict
    println(v)
end
```
One of the fields in `lidict` corresponds to the file: if you can use the path to reliably distinguish Base, then this is achievable.

**Comment by tkelman** [comment]
ProfileView works on Windows...
![image](https://cloud.githubusercontent.com/assets/5934628/6822948/d634c8d2-d2a0-11e4-8095-e58d1242cd6f.png)

Last time I checked Tk fails one of its tests due to some silly path-separator escaping, but otherwise seems fine.

**Comment by StefanKarpinski** [comment]
Ok, that's good. Nevertheless, simplified profile printing wouldn't hurt; marking as up for grabs.

**Comment by timholy** [comment]
I don't mind doing it, but we really need to migrate to a graphical world :-).

ATM the task switch away from https://github.com/JuliaLang/julia/pull/10525#issuecomment-85783671 is too expensive.

**Comment by StefanKarpinski** [comment]
Don't let this distract, @timholy – I think this is a good up for grabs issue.

**Comment by one-more-minute** [comment]
For what it's worth, I just finished making the Juno profiler (complete with fancy file views etc.) work as a standalone package, which might be useful if ProfileView.jl has platform issues. It'll be easy enough to fade out lines from base/packages a little, although I think that's less necessary when you can see the results inline in the code anyway.

I actually don't think it's such a bad idea to expose users to Base a little – the whole idea is that there's no difference between their code and ours, and it's good for gradually onboarding developers ;)

To anyone looking to implement this, it should be fairly easy to do. Files from base are stored as relative paths (e.g. `abstractarray.jl` or sometimes `./abstractarray.jl` on Linux) and everything else is absolute. Files from packages will of course be prefixed by `Pkg.dir()`. So it's just a case of pruning those branches from the tree.

**Comment by ViralBShah** [comment]
Oh yeah, exposing Base is completely fine - but often at times you write a 20 line algorithm, and it becomes difficult to see where the code is spending time. I would love a default that hides, but have a button that shows all the details.

Can you prepare Juno binaries with the integrated profiler?

**Comment by one-more-minute** [comment]
Juno does come with an integrated profiler already, if that's what you mean? The new one is essentially the same idea but can be added with `Pkg.add()` and used from the REPL.

**Comment by ViralBShah** [comment]
I see that I can access it with Profile.profile(). Next step - can we print the percentages in the editor on every line of the user's code? This is not the place to have this discussion though, so perhaps I should file an issue elsewhere.

**Comment by jakebolewski** [comment]
This issue seems a bit generic and the situation seems to have improved on Windows.  Closing in favor of more specific / detailed issues.
