### ISSUE TITLE
Issue with eigs?

### ISSUE THREAD

**Issue by prezaei85** [JuliaLang/julia#10631]
I am not sure why this happens, but I guess there should be a problem with eigs:
```
In  [2]: a = [1 2;3 4]

Out [2]: 2x2 Array{Int64,2}:
 1  2
 3  4

In  [3]: eig(a)

Out [3]: ([-0.372281,5.37228],
2x2 Array{Float64,2}:
 -0.824565  -0.415974
  0.565767  -0.909377)

In  [4]: eigs(a)
WARNING: nev should be at most 0

Out [4]: ERROR: ArgumentError("nev must be at least one")
while loading In[4], in expression starting on line 1

 in eigs at linalg/arnoldi.jl:23
 in eigs at linalg/arnoldi.jl:5
```

**Comment by ViralBShah** [comment]
I believe there are some ARPACK constraints on calling its routines that make it difficult for small matrices. We should probably just call `eig` transparently for anything under 10x10.

**Comment by tkelman** [comment]
> We should probably just call `eig` transparently for anything under 10x10.

Yikes. This only makes sense for types of arrays for which dense `eig` is fast via lapack.

**Comment by andreasnoack** [comment]
We could specialcase `n=1,2`.

**Comment by acroy** [comment]
In the case reported above, we actually set the number of requested eigenvalues to zero because of
```
    nevmax=sym ? n-1 : n-2
```
(`n` is the size of the matrix, `sym ` is true if the matrix is symmetric). Shouldn't it be `n` instead of `n-2`? But maybe I am missing something.

**Comment by ViralBShah** [comment]
Those are set as per the ARPACK documentation. I am pretty sure it can't be n.

**Comment by acroy** [comment]
I see. In that case n=1,2 is pretty much excluded. Either we improve the error message or special case them.
