### ISSUE TITLE
Profiler segfaults on windows

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#10638]
This code makes the profiler segfault on windows
```
function test_func()
    points_1= Vector{Float64}[[0.1, 0.,-0.4],[-0.1, 0., -0.4 ], 	
                 [0.1, 0.325, 0.117],  [-0.1,0.325, 0.117 ],		
                 [ 0.1, 7., -0.9], [ -0.1, 7., -0.9]] 
    rot = [cos(1) -sin(1) 0
           sin(1) cos(1) 0
           0 0 1]
    line_crash = [(rot * vec) + [0,1.97,0] for vec in points_1] #If this lines is commented out it don't segfault
end

function test(n)
    tic()
    for i=1:n
        test_func()
    end
    toc()
end
test(10)
Profile.clear()
@profile test(100000) # If this number is reduced then it stops segfaulting
Profile.print()
```
The output is:
```
julia> @profile test(100000) # If this number is reduced then it stops segfaulting

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c525aee -- rec_backtrace_ctx at C:\Users\Hoegh\Julia-0.4.0-dev_26_03\bin\libjulia-debu
g.dll (unknown line)
rec_backtrace_ctx at C:\Users\Hoegh\Julia-0.4.0-dev_26_03\bin\libjulia-debug.dll (unknown line)
jl_typeof at C:\Users\Hoegh\Julia-0.4.0-dev_26_03\bin\libjulia-debug.dll (unknown line)
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
```
My version info is:
```
C:\Users\Hoegh>Julia-0.4.0-dev_26_03\bin\julia-debug.exe
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3981 (2015-03-25 02:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 237b811* (1 day old master)
|__/                   |  x86_64-w64-mingw32

julia> versioninfo()
Julia Version 0.4.0-dev+3981
Commit 237b811* (2015-03-25 02:18 UTC)
DEBUG build
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>
```

**Comment by KristofferC** [comment]
Does a simple `gc()` also segfault it?

**Comment by dhoegh** [comment]
Running `gc()` in new Julia terminal do not crash julia.

**Comment by ihnorton** [comment]
bt:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 3592.0x10d0]
rec_backtrace_ctx (data=0x1385fa40, maxsize=2003053152,
    Context=Context@entry=0x1385fa40) at task.c:606
606                 Context->Rbp = *(DWORD64*)Context->Rsp;      // POP RBP
(gdb) r
```

Repeated runs with an added `println(i)` in the `test` parent function shows the crash doesn't happen in a consistent place.

25558
8904
1934
1266 -- this one printed [New Thread ...] and hung.
3971
9960
5198

**Comment by ihnorton** [comment]
`Context.Rsp` and `Context.Rbp` are usually equal to 0, but twice I've seen 63473.

One possible solution: compile LAPACK with `-frecursive` in order to have LAPACK do local array allocations on the stack. See:

http://stackoverflow.com/questions/18216314/shouldnt-lapacks-dsyevr-function-for-eigenvalues-and-eigenvectors-be-thread-s

https://github.com/xianyi/OpenBLAS/issues/477#issuecomment-67488804

However, that is tricky because it requires a sufficiently large stack:
https://github.com/xianyi/OpenBLAS/issues/161#issuecomment-10868371

**Comment by Keno** [comment]
Can Windows catch segfaults? On OS X if the profiler code crashes, we just reset and pretend nothing happened (this is important, because sometimes the unwind info will be wrong in C libraries causing us to step on invalid memory).

**Comment by dhoegh** [comment]
Thank you for looking into the issue. I have some bonus info I forgot to mention this only happens on 0.4.

**Comment by ihnorton** [comment]
@Keno thanks for the pointer, that's ~~evil~~ awesome. And [yes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680634%28v=vs.85%29.aspx) (`SetUnhandledExceptionFilter`), which we use already. I just wrote some code to do the same on Windows, which does fix the problem (although I'm not sure if it is entirely legal).
