### ISSUE TITLE
map(Integer, ::Vector{Any}) throws

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10633]
```julia
julia> map(Integer, Any[1, 2])
ERROR: MethodError: `one` has no method matching one(::Type{Any})
 in map at abstractarray.jl:379
```

**Comment by hayd** [comment]
Should this return `Integer[1, 2]`? If so, I have a fix (not the above commit).

**Comment by JeffBezanson** [comment]
Ideally no; it should return `Int[1, 2]`. However for empty arrays it could use the trick in your commit.

**Comment by hayd** [comment]
The example I was testing in my branch was `Any[1, 2, Int8(3), UInt8(4)]`, though perhaps this is an unreasonable example. (map in abstractarray gets the eltype from the first element.)

**Comment by simonster** [comment]
Are [these methods](https://github.com/JuliaLang/julia/blob/176f9bcdc7e745560107038c6fd7333e85bb4c57/base/abstractarray.jl#L379-L381) actually necessary? On my system, they don't actually seem any faster than the general `map` method:

```julia
julia> x = map(Float64, rand(Int, 100000000));

julia> @time for i = 1:10; map(Integer, x); end
elapsed time: 2.734174725 seconds (7629 MB allocated, 1.92% gc time in 9 pauses with 1 full sweep)

julia> @time for i = 1:10; invoke(map, (Any, Vector), Integer, x); end
elapsed time: 2.658263088 seconds (7629 MB allocated, 0.67% gc time in 9 pauses with 0 full sweep)

julia> @time for i = 1:10; map(Integer, x); end
elapsed time: 2.73453461 seconds (7629 MB allocated, 0.66% gc time in 9 pauses with 0 full sweep)

julia> @time for i = 1:10; invoke(map, (Any, Vector), Integer, x); end
elapsed time: 2.633010239 seconds (7629 MB allocated, 0.67% gc time in 9 pauses with 0 full sweep
```

**Comment by JeffBezanson** [comment]
Yes, it's definitely arguable that these definitions just complicate things and should use the same `map` as everything else. I think they originate from trying to get a better type for the empty array case.

**Comment by simonster** [comment]
We could use a comprehension, but that's just kicking the can down the road on #7258.

**Comment by vtjnash** [comment]
@JeffBezanson can we fix this now?
