### ISSUE TITLE
REPL displays zeros for some trailing items items in some int and float tuples

### ISSUE THREAD

**Issue by stillyslalom** [JuliaLang/julia#10635]
I ran into some odd behavior where, when short numeric tuples are entered in the REPL, they're displayed with one or more of their trailing elements equal to zero. When these same elements are examined (via `a[3]` or `println(a)`), the assigned values are correctly displayed.
```               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.7 (2015-03-23 21:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> a = (1,2,3)
(1,2,0)

julia> a[3]
3

julia> a=(1,2,3,4)
(1,2,0,0)

julia> a=(1,2,3,4,5)
(1,2,3,4,5)

julia> a=(1.,2.,3.,)
(1.0,2.0,0.0)

julia> a=(1.,2.,3.,4.,)
(1.0,2.0,3.0,4.0)
```

**Comment by simonster** [comment]
This is the infamous Windows tuple bug, #7434. Unfortunately it's a bug in LLVM, not Julia, so we're stuck with it until we can bump the LLVM version.
