### ISSUE TITLE
Weird behaviors of pmap across version of julia

### ISSUE THREAD

**Issue by rszoh** [JuliaLang/julia#10640]
When I run a piece of code in Julia 0.3.5 it runs perfectly but in other version like0 .3.6 and 0.3.7 it does not. I get this error: 
`convert` has no method matching convert(::Type{Int64...}, ::Int64), which makes not sense to me, since convert has a method like that!

**Comment by kmsquire** [comment]
@rszoh, thanks for the issue.  However, without some code demonstrating your problem, it's impossible to debug.  Can you post a code snippet and the exact output that it produces?  A small example would be appreciated.  Thanks!

**Comment by rszoh** [comment]
I made a post before reporting the issue and here is the link https://groups.google.com/forum/#!topic/julia-users/bWvsJqCCEEk

when it works I get:
Warning: could not import Base.add! into NumericExtensions
Done!
Start here ... 
Warning: could not import Base.add! into NumericExtensions
Warning: could not import Base.add! into NumericExtensions
	From worker 2:	Done!
	From worker 3:	Done!
Done!!
2x12 DataFrame
| Row | n1   | n2   | p     | k   | m    | kap0 | pct | mu  | Log_bay  | pos | stron | ver_strg |
|-----|------|------|-------|-----|------|------|-----|-----|----------|-----|-------|----------|
| 1   | 50.0 | 50.0 | 200.0 | 0.0 | 24.0 | 0.1  | 1.0 | 1.0 | -58.6029 | 0.0 | 0.0   | 0.0      |
| 2   | 50.0 | 50.0 | 200.0 | 1.0 | 24.0 | 0.1  | 1.0 | 1.0 | -58.4965 | 0.0 | 0.0   | 0.0      |

julia> versioninfo()
Julia Version 0.3.5
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.4.2

However, when it fails on Julia 0.3.6 and 0.3.7 I get the following error:

fatal error on fatal error on 2: 3: ERROR: `convert` has no method matching conv
ert(::Type{Int64...}, ::Int64)
 in convert at base.jl:13
 in convert at base.jl:21
 in deserialize at serialize.jl:447
 in handle_deserialize at serialize.jl:351
 in deserialize at serialize.jl:334
 in anonymous at serialize.jl:354
 in ntuple at tuple.jl:30
 in deserialize_tuple at serialize.jl:354
 in handle_deserialize at serialize.jl:346
 in anonymous at task.jl:853

I hope that's not too much,

Many thanks!

**Comment by ihnorton** [comment]
Is this still an issue on 0.3.8 with the latest updates to Devectorize and NumericExtensions?

Reduced case (from that email thread, thanks to @binarybana)

test.jl:
```
using Devectorize
function myfun(pam) 
  println("Entering myfun")
  foo = ones(5)
    @devec x = sum(foo)
  println("exiting myfun")
  return x
end
```

test with:
```
parm = rand(10,10)
M = { parm[i,:] for i in 1:2} # size(parm,1)}
require("test.jl")
pmap(myfun,M)
```

**Comment by malmaud** [comment]
I can't reproduce this problem on the current Julia master (b6c0d95) and Devectorize (754cc06), so I'll close for now. @rszoh, please reopen if this is still an issue for you.
