### ISSUE TITLE
improve quadgk documentation

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10649]
I feel like `quadgk` is this one fairly limited bit of integration functionality stranded in Julia's standard library. This leads people to mistakenly expect more complete integration functionality in the standard library and [be confused](http://stackoverflow.com/questions/29292614/how-to-do-two-variable-numeric-integration-in-julia) when they can't find it. I propose removing `quadgk` and just directing people to more comprehensive integration solutions like [Cubature](https://github.com/stevengj/Cubature.jl).

**Comment by ViralBShah** [comment]
It would be nice to hear @stevengj 's thoughts on the topic, given that he is the author of both. I am not sure I fully like the idea, as it is possibly commonly used, is handy for teaching, and removing it will only cause more inconvenience. As the SO thread notes, the documentation for `quadgk` could be better so that people can easily find more sophisticated packages.

This is a different case than ODEs that we removed early on, or DistributedArrays that did not have wide usage, or Graphics that caused a lot of trouble for developers, but not for users.

**Comment by StefanKarpinski** [comment]
My experience with `quadgk` has been that the time between using it and wanting something that you need a package for is approx ten minutes. Mileage may vary, of course.

**Comment by carlobaldassi** [comment]
> Mileage may vary, of course

Indeed, my experience is diametrically opposed: I've been using it quite a lot lately, and when I looked into `Cubature` I found out I didn't really need it.

Short explanation: I do multidimensional integrals (up to 4 dimensions) by nesting single integrals and using anonymous functions. It works just fine, `Cubature` did not prove to be better for my use case, anonymous functions are not a big deal from the performance point of view (well, almost). I used to do the same in Mathematica with `NIntegrate` and Julia's `quadgk` provided a 300-fold speed-up.

**Comment by stevengj** [comment]
For me, 1d numerical integration is

* such a basic task that I would expect to see it in any "batteries included" environment like Julia

* extremely well understood, to the point where most users are fine with a black-box adaptive algorithm like `quadgk`.  (In contrast to multidimensional cubature, where there are a large number of algorithms and their selection tends to be problem dependent.)  Like numerical linear algebra, this makes it a good candidate for standard libraries.

(I would say the same thing about an adaptive runge-kutta 4/5 algorithm, by the way: this is what 99% of people solving ODEs need, it is simple, and I still think it should be in base.  Everything else can go in a package.)

I don't understand the "the time between using it and wanting something that you need a package for is approx ten minutes" comment, unless you are referring to multi-dimensional integrals.  There is a universe of difference between 1d and multi-dimensional integration.  It's like saying that we shouldn't bother to have linear algebra in base if we're not going to support multilinear algebra.

**Comment by ViralBShah** [comment]
I have really been thinking about having RK45 ODEs in Base also. In most cases of people using ODEs, I have found that it suffices. When it does not, it usually means a more involved exploration into various things.

**Comment by StefanKarpinski** [comment]
Changing this to a documentation issue.

**Comment by StefanKarpinski** [comment]
The help entry for `quadgk` should include pointers to other resources for doing more complex integration problems.
