### ISSUE TITLE
option to set processor affinity in addprocs

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10645]
The ability to lock julia workers to specific cores results in substantial gains for certain workloads. See https://github.com/JuliaLang/julia/issues/10427#issuecomment-86371729 for some test results. `addprocs` should provide a means for the same.

**Comment by ViralBShah** [comment]
I don't fully recollect, but there was some issue with openblas and affinity - we disable it by default. Do see the openblas build options, and the earlier discussion - I will try to find the relevant links.

**Comment by amitmurthy** [comment]
With threaded openblas it may not make much sense. But in a parallel run, openblas threads are set to 1.

**Comment by jakebolewski** [comment]
Wouldn't this be best handled by the cluster manager.  SGE, Slurm, MPI, etc. all have options to do this.

**Comment by amitmurthy** [comment]
What about folks running on largish machines like julia.mit.edu? I think
the built in managers, LocalManager and SSHManager should support it.

**Comment by ViralBShah** [comment]
That is probably the most common use case.

**Comment by amitmurthy** [comment]
Another example - https://groups.google.com/d/msg/julia-dev/BYVCyUlNR8c/_9XGgjolNNIJ - a 192 core system.

**Comment by amitmurthy** [comment]
Have added this feature to ClusterManagers.jl - https://github.com/JuliaParallel/ClusterManagers.jl/commit/9afe2520d2fdc34ea7a8829a338cce543e727770
