### ISSUE TITLE
performance regression in println

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#10650]
I just tried the code from #2050 again to see how we're doing. The good news is, we're faster than 0.3 on the original code.

0.3:

```
jeff@gurren:~/src/julia$ time ~/src/julia-0.3/julia/julia i2050.jl

real	0m29.973s
user	0m26.618s
sys	0m1.860s
```

0.4:

```
jeff@gurren:~/src/julia$ time ./julia i2050.jl

real	0m24.495s
user	0m21.923s
sys	0m1.312s
```

Then I tried using `println` instead of `write` and got this:

0.3:

```
jeff@gurren:~/src/julia$ time ~/src/julia-0.3/julia/julia i2050.jl

real	0m47.285s
user	0m45.708s
sys	0m1.664s
```

0.4:

```
jeff@gurren:~/src/julia$ time ./julia i2050.jl

real	1m22.889s
user	1m20.935s
sys	0m1.877s
```

Pretty massive regression. If I take out the new `lock(io) do io` I get

```
jeff@gurren:~/src/julia$ time ./julia i2050.jl

real	0m39.443s
user	0m37.710s
sys	0m1.688s
```

again faster than 0.3, so very promising. We might need some manual inlining and hacked-in fast paths for this.

cc @amitmurthy

**Comment by amitmurthy** [comment]
Closed by #10679
