### ISSUE TITLE
fullname(Base) changes after workspace

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10653]
Not sure if there's anything to be done here, but this is a bit weird:

```
julia> fullname(Base)
(:Base,)

julia> workspace()

julia> fullname(Base)
(:LastMain,:Base)
```

**Comment by JeffBezanson** [comment]
I decided it was best to just hack this in, since `Base` is one of three modules known to be imported into the new `Main` (the others being Core and LastMain).
