### ISSUE TITLE
Markdown.readme throws MethodError

### ISSUE THREAD

**Issue by sawcordwell** [JuliaLang/julia#10663]
If I try `Markdown.readme("Gadfly")` then I get the error

    ERROR: MethodError: `parse` has no method matching parse(::IOBuffer, ::Base.Markdown.MD, ::Function)

It seems that `github_paragraph` in GitHub.jl is passing the `config` function to `parse` rather than calling `config` to instantiate a `Config` instance. I'm not sure how the parsers argument is supposed to work so I can't fix this by myself.

**Comment by sawcordwell** [comment]
@one-more-minute from Git blame

**Comment by hayd** [comment]
This is fixed if you [drop the config](https://github.com/JuliaLang/julia/blob/7e97b7090e13f80809d2985440fc628e671aa09b/base/markdown/GitHub/GitHub.jl#L42) (which references the global config function rather than a ::Config)
```
julia> Markdown.readme("Gadfly")
  !["Alice looked up at the Rocking-horse-fly with great interest, and made up her
  mind that it must have been just repainted, it looked so bright and sticky."](http://dcjones.github.com/Gadfly.jl/rockinghorsefly.png)

  Julia 0.3 (Image: Gadfly)

  Julia 0.4 (Image: Gadfly)

  ...
```

What's interesting is this parses/renders different to the help (which spots the first image):
```
help?> Gadfly
search: Gadfly

  (Image: "Alice looked up at the Rocking-horse-fly with great interest, and made up her mind that it must have been just repainted, it looked so bright and sticky.")

  Julia 0.3 (Image: Gadfly)

  Julia 0.4 (Image: Gadfly)

  ...
```
(Strangely `help?>` always worked.)

**Comment by hayd** [comment]
@one-more-minute any thoughts on the above discrepancy?

**Comment by one-more-minute** [comment]
The image parser seems to have ended up in the `julia` flavour but not in `common` or `github`. Really github should be used to parse the readmes anyway, but either way it should be very easy to fix that.

**Comment by hayd** [comment]
@one-more-minute it's only the first image which isn't parsed.

**Comment by one-more-minute** [comment]
That's very weird. If you replace `github_paragraph` with `paragraph` everything works fine, but when the former calls `parseinline` it just doesn't get the image. I can't spot the difference between the two...
