### ISSUE TITLE
`immutable type` syntax causes julia-mode.jl wonkiness

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10668]
In addition to the standard syntax for immutable types

    immutable TypeName
        x::Int
    end

Julia seems to support a second syntax where both words `immutable type` are given:

    immutable type TypeName
        x::Int
    end

Although this second syntax is undocumented and unused throughout the Julia source tree (as can be verified using `git grep`), it is correctly parsed by Julia 0.3, Julia 0.4, and JuliaParser.jl.  From looking at `julia-parser.scm`, [this seems to be no accident](https://github.com/JuliaLang/julia/blob/8ec12d0ba47fb16df08f99213eb4575145539f29/src/julia-parser.scm#L1138-L1141).

However, if one uses it in emacs `julia-mode`, it always wants to indent lines after such a type definition by an extra indent level.  To reproduce, open emacs in `julia-mode` and enter the following:

    immutable type TypeName
    end
        # This line will be indented to here automatically.

**Comment by JeffBezanson** [comment]
I suspect it would be best to remove this "feature" from the parser. As you observe, it's not used in practice and would be a source of spurious syntax variation if it were.

**Comment by StefanKarpinski** [comment]
+1 for removal
