### ISSUE TITLE
applicable does not work for anonymous functions

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#10664]
This seems wrong:

f(x)=x^2
applicable(f,1) #true
g=x->x^2
applicable(g,1) #ERROR: applicable: not a generic function

**Comment by jakebolewski** [comment]
An anonymous function is not a method, so I don't see how applicable is relevant (do these argument types have a corresponding matching method definition in the method table?).

**Comment by dlfivefifty** [comment]
It's relevant because it tells you whether you can call a function with the given arguments.  In the case of anonymous functions, it would return true provided the number of arguments is correct.
