### ISSUE TITLE
REPL integrated readline

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#10667]
I feel that this has been discussed before, but I couldn't find an issue. Anyway, now that #6270 has had the chance to simmer for quite a bit, it would be nice if also user code could make use of the readline functionality provided by the new REPL.

I'm not sure if this should be special cased on calling `readline(STDIN)` (or just `readline()`), or if there should be a new function (with more options?). Also, not sure how this should work with eg IJulia.

This would e.g. be really useful to improve the debugging experience with [Debug.jl](https://github.com/toivoh/Debug.jl). I'm sure there's others who would benefit as well.

**Comment by KristofferC** [comment]
`readline()` now seems to wait for STDIN. Ok to close?

**Comment by tkelman** [comment]
Isn't this referring to tab completion etc in user input?

**Comment by KristofferC** [comment]
I don't know.

**Comment by rfourquet** [comment]
I don't understand the issue here, could someone clarify what is requested here?

**Comment by timholy** [comment]
```julia
julia> readline()
Once upp^A
"Once upp\x01"
```
That `^A` was me trying to go back to the beginning of the line using readline commands. The issue is requesting documentation about how one might turn that on.

**Comment by KristofferC** [comment]
The "correct" way to do this seems to me to be to implement a new REPL mode (like Debugger and Pkg does) and not call `readline` explicitly. So I don't think there is much to do here.
