### ISSUE TITLE
Bug with Hermitian() and ishermitian()

### ISSUE THREAD

**Issue by jeremy-y12** [JuliaLang/julia#10671]
Hello,
It seems that the methods Hermitian() and ishermitian() are not working properly.

```
test = Hermitian(rand(4,4)+im*rand(4,4))
```

generates a matrix that is not hermitian: the diagonal elements are complex.

Also, trying

```
ishermitian(test)
```

returns true.

**Comment by jiahao** [comment]
Yes, we should check the diagonals.
