### ISSUE TITLE
Unknown or incorrect option bit(s) set

### ISSUE THREAD

**Issue by astrieanna** [JuliaLang/julia#10678]
I just cloned from master, and successfully built. It works when I run it in the local directory. When I add a symlink to /usr/bin/, and run it from there, it immediately crashes. Did I do something wrong?

How I added the symlink:

```
sudo ln -s /Users/leah/src/julia/julia /usr/bin/julia
```

The results of running Julia from the ~/src/julia directory:

```
$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4066 (2015-03-29 22:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 951a0c2 (0 days old master)
|__/                   |  x86_64-apple-darwin14.0.0

julia> 
```

The results of running Julia from the symlink:

```
$ julia
Warning: error initializing module Base:
ErrorException("unknown or incorrect option bit(s) set")
Warning: error initializing module LinAlg:
ErrorException("unknown or incorrect option bit(s) set")
Warning: error initializing module GMP:
ErrorException("unknown or incorrect option bit(s) set")
Warning: error initializing module PCRE:
ErrorException("symbol could not be found pcre_jit_stack_alloc: dlsym(0x7f83c501fae0, pcre_jit_stack_alloc): symbol not found
")
ERROR: unknown or incorrect option bit(s) set
 in error at error.jl:19
 in study at ./pcre.jl:112
 in compile at ./regex.jl:47
 in ismatch at ./regex.jl:105
 in call at ./version.jl:28
 in print at ./version.jl:42
 in print_to_string at ./string.jl:27
 in string at string.jl:36
 in banner at ./version.jl:232
 in _start at ./client.jl:415
```

**Comment by nalimilan** [comment]
Adding symlinks to `/usr/bin` is not a good idea, you'd better put it in `~/.local/bin`. That's what I'm doing and it works fine.

That said, it's weird that it doesn't work with `/usr/bin`. It might be that Julia is looking for libraries from the symlink location, instead of the location of the binary, but AFAICT libuv's `uv_exepath` returns the latter, not the former. Could it be `ld`'s fault?

**Comment by JeffBezanson** [comment]
It does look like it's picking up the wrong versions of some libraries somehow.

**Comment by KristofferC** [comment]
Comment if this is still happening.
