### ISSUE TITLE
Should setindex! allow indexing with multiple multidimensional arrays?

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#10686]
Currently, `setindex!` kinda-sorta allows indexing certain dimensions by multidimensional arrays, but it's not fully supported by logical indexing.  (`getindex` allows this only when the multidimensional array is the only index provided). Neither capability is documented. Should the `boundscheck` be fixed (it's an easy fix) or should this be entirely deprecated?  Given that it's asymmetric from `getindex` and multidimensional logical indexing has been broken like this since at least 0.3 with nobody noticing, I'd favor deprecation.

```julia
julia> A = reshape(1:15, 3, 5)
3x5 Array{Int64,2}:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

julia> A[1, [1 2; 4 5]] = 0; A
3x5 Array{Int64,2}:
 0  0  7   0   0
 2  5  8  11  14
 3  6  9  12  15

julia> A[1, [1 2; 4 5]]
ERROR: MethodError: `getindex` has no method matching getindex(::Array{Int64,2}, ::Int64, ::Array{Int64,2})
Closest candidates are:
  getindex(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any...)
  getindex{N}(::Array{T,N}, ::Integer, ::Base.IteratorsMD.CartesianIndex{N})
  getindex(::Array{T,N}, ::Real)
  ...

julia> A[2, [true true false true true]] = -1; A
ERROR: BoundsError
 in checkbounds at abstractarray.jl:118
 in checkbounds at abstractarray.jl:126
 in anonymous at multidimensional.jl:299

julia> A[2, [true true true true true]] = -1; A
3x5 Array{Int64,2}:
  0   0   7   0   0
 -1  -1  -1  -1  -1
  3   6   9  12  15

julia> A[2, [true true true true true]]
ERROR: `getindex` has no method matching getindex(::Array{Int64,2}, ::Int64, ::Array{Bool,2})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
```

**Comment by toivoh** [comment]
I believe this will change of and when we implement APL indexing, but I
agree that we should have symmetry between getindex and setindex!
Has anyone been relying on this?

**Comment by timholy** [comment]
I too agree that symmetry is the way to go. IIUC, APL would argue that
```
A = reshape(1:18, 3, 3, 2)
A[[1 2; 3 4], 2] = 0
```
would refer to elements `10, 11, 12, 13` of `A`, meaning `[1 2; 3 4]` gets interpreted as a linear index into the first two dimensions, and the trailing `2` refers to the 3rd dimension of `A`.

**Comment by mbauman** [comment]
Based on this and comments in #10525, the answer was no.  I deprecated it in #10525.
