### ISSUE TITLE
Segmentation fault when using Compat

### ISSUE THREAD

**Issue by sawcordwell** [JuliaLang/julia#10689]
Something strange has happened the last few times I have compiled Julia. Using the latest master whenever I load a package that is using Compat I get a segmentation fault. I have not been able to figure out what is going on other than that the version does not look right. I'm sure that the value after the + in the version was in the 3000s before?

Julia Version 0.4.0-dev+485
Commit de362f6* (2015-03-30 22:50 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by jiahao** [comment]
I am not able to reproduce the version number you have for that commit. On OSX and 64-bit Ubuntu I get the version `0.4.0-dev+4089 `. 

`*` indicates building from a dirty source directory. Can you verify that you get the same version number if you build from a clean working directory? `git reset --hard` should work, or in an extreme situation you may need to run `git clean -xfd` to nuke all changes to the working directory.

**Comment by tkelman** [comment]
The `+485` may indicate you made a local tag, which will confuse the `VERSION` counting, and hence Compat won't be applying as many changes as it should be.

**Comment by sawcordwell** [comment]
Ah right yes, I accidentally made a tag called 'list'. I must have got confused with stash. Everything is back to normal now. Thanks a lot.
