### ISSUE TITLE
Base.runtests() fail: linalg/cholmd

### ISSUE THREAD

**Issue by floringogianu** [JuliaLang/julia#10683]
**With the Head version of OpenBlas**
Julia Version 0.3.6
Commit 0c24dca* (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY HASWELL)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at error.jl:21
 in runtests at interactiveutil.jl:370
 in runtests at interactiveutil.jl:359
 in process_options at /usr/local/Cellar/julia/0.3.6_1/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.3.6_1/lib/julia/sys.dylib 

**And the error:**

exception on 4: ERROR: test error during speye(2) \ speye(2) == eye(2)
error compiling \: error compiling factorize: error compiling cholfact: error compiling cmn: could not load module libcholmod: dlopen(libcholmod.dylib, 1): Library not loaded: /usr/local/opt/openblas-julia/lib/libopenblasp-r0.2.12.dylib
  Referenced from: /usr/local/Cellar/julia/0.3.6_1/lib/julia//libcholmod.dylib
  Reason: image not found
 in anonymous at test.jl:62
 in do_test at test.jl:37
 in runtests at /usr/local/Cellar/julia/0.3.6_1/share/julia/test/testdefs.jl:5
 in anonymous at multi.jl:855
 in run_work_thunk at multi.jl:621
 in anonymous at task.jl:855
while loading linalg/cholmod.jl, in expression starting on line 38
ERROR: test error during speye(2) \ speye(2) == eye(2)
error compiling \: error compiling factorize: error compiling cholfact: error compiling cmn: could not load module libcholmod: dlopen(libcholmod.dylib, 1): Library not loaded: /usr/local/opt/openblas-julia/lib/libopenblasp-r0.2.12.dylib
  Referenced from: /usr/local/Cellar/julia/0.3.6_1/lib/julia//libcholmod.dylib
  Reason: image not found
while loading linalg/cholmod.jl, in expression starting on line 38
while loading /usr/local/Cellar/julia/0.3.6_1/share/julia/test/runtests.jl, in expression starting on line 39

**Comment by tkelman** [comment]
Please provide as much information as you possibly can about exactly what you did in order to build Julia "With the Head version of OpenBlas." I'm going to guess from the `Cellar` paths that you are using Homebrew in some way, but that's only partly useful. If you want to change which BLAS implementation is being used, you generally need to recompile SuiteSparse and Arpack as well - unless you were using symlinks via update-alternatives, but I think that only works in Linux.

**Comment by ViralBShah** [comment]
Cc: @staticfloat In case this is a brew path thing.

**Comment by staticfloat** [comment]
This does look like a brew thing; @floringogianu I don't think you can use the bottled versions of Julia, arpack or suitesparse with the HEAD version of OpenBLAS, so can you try the following:

```
$ brew rm julia suite-sparse42-julia arpack-julia
$ brew install -s arpack-julia
$ brew install -s suite-sparse42-julia
$ brew install -s julia
```

The `-s` flag forces a from-source build, which should hopefully clear things up for you.

**Comment by floringogianu** [comment]
Thank you for your quick replies, much appreciated! Yes, it should have been obvious that I need to force the build. So I did just that, however it fails to build. Not sure if this is still brew related, so I am pasting the details here.

Here is the log file: https://gist.github.com/floringogianu/0987e295d37cb6210a98

```
==> ENV
CC: /usr/bin/clang
CXX: /usr/bin/clang++
OBJC: /usr/bin/clang
OBJCXX: /usr/bin/clang++
CFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CXXFLAGS: -Os -w -pipe -march=native -mmacosx-version-min=10.10
CPPFLAGS: -I/usr/local/opt/cloog018-julia/include -I/usr/local/opt/isl011-julia/include -I/usr/local/opt/gmp4-julia/include -I/usr/local/opt/suite-sparse42-julia/include -I/usr/local/opt/openblas-julia/include -F/usr/local/Frameworks
LDFLAGS: -L/usr/local/opt/arpack-julia/lib -L/usr/local/opt/llvm33-julia/lib -L/usr/local/opt/libffi/lib -L/usr/local/opt/cloog018-julia/lib -L/usr/local/opt/isl011-julia/lib -L/usr/local/opt/gmp4-julia/lib -L/usr/local/opt/suite-sparse42-julia/lib -L/usr/local/opt/openblas-julia/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -headerpad_max_install_names
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/arpack-julia:/usr/local/opt/llvm33-julia:/usr/local/opt/libffi:/usr/local/opt/cloog018-julia:/usr/local/opt/isl011-julia:/usr/local/opt/gmp4-julia:/usr/local/opt/suite-sparse42-julia:/usr/local/opt/openblas-julia
CMAKE_FRAMEWORK_PATH: /usr/local/Frameworks
MACOSX_DEPLOYMENT_TARGET: 10.10
PKG_CONFIG_PATH: /usr/local/opt/arpack-julia/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/cloog018-julia/lib/pkgconfig:/usr/local/opt/isl011-julia/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/local/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:/usr/lib/pkgconfig
PATH: /usr/local/opt/arpack-julia/bin:/usr/local/opt/llvm33-julia/bin:/usr/local/opt/cloog018-julia/bin:/Users/florin/.rvm/gems/ruby-2.2.0/bin:/Users/florin/.rvm/gems/ruby-2.2.0@global/bin:/Users/florin/.rvm/rubies/ruby-2.2.0/bin:/Users/florin/.nvm/v0.10.34/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/florin/.rvm/bin:/usr/local/Library/ENV/scm
CPATH: /usr/local/include
```

```
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: db58425b62c48ed8e787a9f39f9cfb58d4057bda
Last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.2-x86_64


Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/florin/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_31
```

**Comment by staticfloat** [comment]
Hrm.... looks like the error being run into here is:
```
cp: symlink: libopenlibm.dylib.1.0: File exists
```

Is this perhaps a makefile race condition that we're hitting?  When you install, can you pass the verbose (`-v`) flag so we can see everything?

**Comment by floringogianu** [comment]
Hmm, I thought I did so. I updated the gist.

**Comment by staticfloat** [comment]
`openlibm`'s `install` target is getting invoked twice, simultaneously.  My best guess is that this is due to https://github.com/JuliaLang/julia/commit/67e55d6c4c3330a6c15569cab7c305c4fdae1816, because the `OPENLIBM_FAKE_TARGET` thing is defeating `make`'s dependency resolution logic somehow.

The easy fix is to run `make` with no parallelization.  This is doable by adding `ENV.deparallelize` to the Julia formula, say, [on line 100](https://github.com/staticfloat/homebrew-julia/blob/d1c7c5c0d2b36c7532ec9c51435693f8dab8340f/julia.rb#L100).  You can see an example of this in a [simpler formula here](https://github.com/Homebrew/homebrew/blob/3c6951ca3072c76af19d096e1332c31de07426c6/Library/Formula/hqx.rb#L11).  To make the local modification to your Julia formula, you can either open `/usr/local/Library/Formula/julia.rb` in a text editor, or just type `brew edit julia`.  Make the change, then try rebuilding and see if things are cleared up.

**Comment by tkelman** [comment]
@floringogianu were you able to fix this?

**Comment by jakebolewski** [comment]
@floringogianu please reply if this is still an error.

**Comment by floringogianu** [comment]
@jakebolewski @tanmaykm I apologise for not getting back. I upgraded in the meantime and can't follow-up on this anymore.
