### ISSUE TITLE
Redefining `call` should be an error

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#10696]
Since `call` was introduced to allow overloading of call signatures, using it as a variable is problematic.  It should probably be an error to do so.

```julia
julia> call = 1
Warning: imported binding for call overwritten in module Main
1

julia> type TT
          x::Int
       end
ERROR: cannot define function call; it already has a value
```

**Comment by JeffBezanson** [comment]
It's the same as other operators. Locally, such special cases might seem desirable, but they will pile up...

**Comment by mbauman** [comment]
Shouldn't the generated constructors always use top call?  This is similar to other operators, yes, but it's not a user-written syntax.

**Comment by JeffBezanson** [comment]
I would rather not. We would be taking modules that much less seriously. If you wanted your own `call` you could still have it, but would have to remember to define all constructors manually instead of using default constructors. That seems odd.

In most cases compiler-inserted identifiers deliberately ("un-hygienically") use the containing scope. For example `a[i]` will use a local `getindex` if one exists. This is because `getindex` is not an implementation detail of `a[i]`, but rather the documented translation of that syntax. `call` is the same.

**Comment by toivoh** [comment]
+1 to Jeffs line of thought. It's not very often that you want your own
definition of + or call, but suddenly there comes along something like Nemo
where it could be really useful.

**Comment by kmsquire** [comment]
I ran across in `Match.jl` because I was using `call` as a variable (holding a function call), and at first had no clue as to why my code was failing.  Should this be closed, then?

At the minimum, it would be good to check for this in Lint.jl.  

Cc: @tonyhffong

**Comment by mbauman** [comment]
Generated constructors feel different to me than getindex (which I agree should be module-local), but I can see how it's part of the same design principle.

@kmsquire Isn't the warning already in base?  Perhaps we could make it a little scarier for core functionalities like `call` and `getindex`.

**Comment by kmsquire** [comment]
Actually, going back to @JeffBezanson's first statement: is there a good reason why `call` should be treated like an operator and not just like another function call?  Maybe I just don't expect to be used frequently, but I would be okay with requiring someone to import call before extending it.

@mbauman, yeah, assuming `call` remains operator-like, as it is, I would think a scarier warning would be useful.

**Comment by JeffBezanson** [comment]
I would agree, except that defining a new type also extends `call`, so for now having `call` in `Operators` seems to be the right default.

**Comment by tkelman** [comment]
@kmsquire sounds like you may have missed https://github.com/tonyhffong/Lint.jl/issues/87 and the associated mailing list post

**Comment by tonyhffong** [comment]
`Lint.jl` already catches `call = ...` construction. See `Lint/src/test/badvars.jl`
