### ISSUE TITLE
enumerate sometimes enumerates the wrong Enum

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10693]
This works:

```julia
julia> @enum Fruit apple

julia> @enum Animal turtle

julia> collect(enumerate(Fruit))
1-element Array{(Int64,Any),1}:
 (1,apple::Fruit)

julia> collect(enumerate(Animal))
1-element Array{(Int64,Any),1}:
 (1,turtle::Animal)
```

This doesn't:

```julia
julia> @enum Fruit apple

julia> collect(enumerate(Fruit))
1-element Array{(Int64,Any),1}:
 (1,apple::Fruit)

julia> @enum Animal turtle

julia> collect(enumerate(Animal))
1-element Array{(Int64,Any),1}:
 (1,apple::Fruit)
```

I suspect this is a special case of #265. In the second case, functions got specialized and compiled for `Enumerate{DataType}` when there was only one applicable `next(::DataType, x)`, but now there are two.

**Comment by JeffBezanson** [comment]
This is not #265. This is a dispatch bug. Although it is little appreciated in the face of #265, we do (usually!) properly invalidate method caches. For example

```
julia> foo(::Integer) = 0
foo (generic function with 1 method)

julia> foo(1)
0

julia> foo(::Int) = 2
foo (generic function with 2 methods)

julia> foo(1)
2
```

I don't know what's going wrong in this case.

**Comment by JeffBezanson** [comment]
Ok, you're probably right that this is #265. Defining methods for Type has additional hazards there.

**Comment by JeffBezanson** [comment]
This now works for me.

**Comment by simonster** [comment]
It's kind of fixed because there's now an Enum defined in Base, but the underlying issue still seems to be there:

```julia
julia> collect(enumerate(Base.WorkerState))
3-element Array{Tuple{Int64,Any},1}:
 (1,W_RUNNING::Base.WorkerState)    
 (2,W_TERMINATING::Base.WorkerState)
 (3,W_TERMINATED::Base.WorkerState) 

julia> @enum Fruit apple

julia> collect(enumerate(Fruit))
1-element Array{Tuple{Int64,Any},1}:
 (1,W_RUNNING::Base.WorkerState)
```
