### ISSUE TITLE
"not all Ritz pairs are converged" in tests

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#10701]
I just saw this running the tests:

```
WARNING: not all Ritz pairs are converged. Requested: 2, converged: 3
```

It seems to me (naively) that if more converge than you asked for, everything is fine.

Also want to double-check that it's ok to get these warnings during the test suite.

**Comment by jiahao** [comment]
Warning was introduced recently in #10688; looks like it exposed an existing problem in the test suite for one test:

> WARNING: not all Ritz pairs are converged. Requested: 4, converged: 1

I didn't consider the possibility that we get more converged values than requested. I'll fix that.

**Comment by jiahao** [comment]
Actually, it appears that ARPACK is using a definition for calculating converged Ritz values which I don't understand. In [the test responsible](https://github.com/JuliaLang/julia/blob/3d37c866fe9f7590684e4348d3ce853f4b7a5be2/test/linalg/arnoldi.jl#L156) for emitting the warning, the reported number of converged eigenvalues is 1 but the residual is the 0 vector exactly. There's no reason to consider this calculation as anything other than fully converged.

I will amend the criterion for emitting the warning accordingly.
