### ISSUE TITLE
Travis CI failing on OSX

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10702]
https://travis-ci.org/JuliaLang/julia/builds/56608667

"The job exceeded the maxmimum time limit for jobs, and has been terminated."

The linux builds ran for approx 25 and 28 minutes; OSX timed out after 47m31s.

**Comment by JeffBezanson** [comment]
This has been happening for quite a while. The OSX builds take predictably ~2x longer, and often time out. I wonder if it is related to travis' OSX setup, or is a more general OSX issue.

**Comment by sbromberger** [comment]
@JeffBezanson do the OSX build checks add any value? That is, are there cases where OSX travis testing has highlighted a problem that linux building has missed?

If not, is there a significant value to having the OSX build checks when they appear to error out for non-critical reasons?

**Comment by JeffBezanson** [comment]
Well, clearly what we'd most like is to have CI just work on OSX and finish in a reasonable amount of time.

**Comment by sbromberger** [comment]
Well, as long as TPTB know about it, I'll close it out :)

**Comment by tkelman** [comment]
Most of the problem is that the Travis OSX builds run on 5-year-old, probably oversubscribed hardware.

**Comment by sbromberger** [comment]
If it's out of our control, then does it make sense to continue to have most PRs fail as a result of the lack of performant hardware?

**Comment by tkelman** [comment]
No, if we can add an OS to `allowed_failures` we may as well do that until we find some other better option

**Comment by stevengj** [comment]
Seems like this issue should still be open, possibly marked "upstream".

**Comment by tkelman** [comment]
there's a newer issue with more specific information relevant to the failure we're hitting now. not upstream, it's because we're testing compile-all which doesn't output anything for 10 mins.

**Comment by stevengj** [comment]
Thanks for the clarification, @tkelman.   Is there an issue for the newer problem?   It would be good to have an issue to reference in failing PRs.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/15808 the latest issue with a `mac` tag.
