### ISSUE TITLE
Build failure on Travis OSX 

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10717]
Not very frequent, but frequent enough.

![image](https://cloud.githubusercontent.com/assets/117461/6957478/1ceceb96-d919-11e4-98bb-066583b8461d.png)

Gist of log : https://gist.github.com/amitmurthy/2dc1b6d7091ac930c4d6

**Comment by sbromberger** [comment]
See also https://github.com/JuliaLang/julia/issues/10702

**Comment by tkelman** [comment]
This is a specific assertion failure, and would appear to be unrelated to the timeouts from #10702

**Comment by JeffBezanson** [comment]
Has anybody ever seen this locally?

**Comment by vtjnash** [comment]
i've seen it if i had a partial or old sys.ji image. but that doesn't really apply to the travis osx build

**Comment by jakebolewski** [comment]
please re-open if this is still a problem
