### ISSUE TITLE
Constructor with type parameters behaves different from methods

### ISSUE THREAD

**Issue by malbarbo** [JuliaLang/julia#10711]
```julia
julia> type Example{T}
           value::T
           Example(v::T) = new(v)
       end

julia> Example(20)
ERROR: `Example{T}` has no method matching Example{T}(::Int64)

julia> Example{T}(a::T) = Example{T}(a)
Example{T} (constructor with 1 method)

julia> Example(20)
Example{Int64}(20)
```

Maybe I'm missing something, but a I think the type parameter T in the constructor should be inferred as in the method.

**Comment by StefanKarpinski** [comment]
When you define an inner constructor, no default constructors are given. The outer constructor one you defined is exactly the one that would be provided by default if no inner constructors were given. This is all documented in http://docs.julialang.org/en/release-0.3/manual/constructors/#inner-constructor-methods. If you find any of the documentation is unclear, please feel free to make documentation enhancements.

**Comment by JeffBezanson** [comment]
See for discussion about possible ways to reduce confusion here: #10146, #8135
