### ISSUE TITLE
Syntax error when defining method Base.==

### ISSUE THREAD

**Issue by malbarbo** [JuliaLang/julia#10710]
```julia
julia> type Wrap value end

julia> Base.hash(a::Wrap) = hash(a.value)
hash (generic function with 32 methods)

julia> Base.==(a::Wrap, b::Wrap) = a.value == b.value
ERROR: syntax: invalid assignment location
```

The workaround is to not use Base prefix. In non-interactive mode we have to import == first, which is inconvenient

```julia
import Base: ==
==(a::Wrap, b::Wrap) = a.value == b.value
```

**Comment by carlobaldassi** [comment]
To avoid using `import` you need to quote the `==` symbol:

```julia
Base.(:(==))(a::Wrap, b::Wrap) = a.value == b.value
```

**Comment by malbarbo** [comment]
I didn't known that. Thanks.

But I think that ` Base.==`  is more interesting!

**Comment by carlobaldassi** [comment]
It's ambiguous with the `.==` function. The parser thinks you're trying to element-wise-compare `Base` with a tuple (and then finds the `=` and throws an error).

**Comment by malbarbo** [comment]
Thats seems a good reason. Thanks.
