### ISSUE TITLE
Conversion to Bool

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#10712]
Converting a `Real` to `Bool` currently just checks if it's nonzero:
```julia
convert(::Type{Bool}, x::Real) = (x!=0)
```

But this is odd in light of our behaviour for other integer types
```julia
julia> convert(Int,0.5)
ERROR: InexactError()
 in convert at int.jl:194

julia> convert(Bool,0.5)
true
```

**Comment by simonster** [comment]
A bit of previous discussion: https://github.com/JuliaLang/julia/issues/5844#issuecomment-45358869

**Comment by StefanKarpinski** [comment]
I agree that this is broken. Related: http://stackoverflow.com/questions/29389597/why-are-non-boolean-values-not-implicitly-converted-in-boolean-expressions. Quoting my comment there:

> The bool function should just be deprecated and then deleted. The conversion to Bool should be fixed. There's unfortunately, no way to do that without potentially breakings some code.

**Comment by StefanKarpinski** [comment]
Actually, it's not that bad since any usage that converts from a non-0/1 value will raise an error and allow people to fix it instead of doing something broken or unexpected. So the to-dos here are:

1. fix conversion to `Bool` to raise an `InexactError` for any value not equal to zero or one;
2. deprecate the `bool` function entirely – there's really no need for this to exist.

**Comment by simonbyrne** [comment]
+1

**Comment by stevengj** [comment]
`bool` is already deprecated...

**Comment by quinnj** [comment]
What about including
```julia
5.4 % Bool
true
```
to mirror the other "forceful"/truncating conversions?

**Comment by StefanKarpinski** [comment]
Unlike the other methods, that's not a modulus operation at all. I think that `x != 0` is just fine for this sort of thing and more explicit.

**Comment by garborg** [comment]
I was confused by this and questioned it in the postscript of another old issue. Another +1 (on both counts).

**Comment by nalimilan** [comment]
+1 too. Being explicit it much better.
