### ISSUE TITLE
Segfaults in multi-threaded code blocks 

### ISSUE THREAD

**Issue by kpamnany** [JuliaLang/julia#10718]
In the ``threading`` branch, the following code segfaults:

```
using Base.Threading
A = Array(BigInt, nthreads())
@threads all begin
  A[threadid()] = 1
end
```

Replace ``BigInt`` with ``Int`` and no segfault. Wrap the code in a function and it also works fine:

```
using Base.Threading
function foo(A)
  @threads all begin
    A[threadid()] = 1
  end
end
A = Array(BigInt, nthreads())
foo(A)
```

This happens with ``MersenneTwister`` as well as ``BigInt`` (see @ViralBShah's comment in https://github.com/JuliaLang/julia/issues/10421).

**Comment by ViralBShah** [comment]
@keno Will your TLS patch help here. How can I try it out?

**Comment by Keno** [comment]
Unlikely, I presume the problem might in the C libraries's allocators.

**Comment by ViralBShah** [comment]
Wouldn't that fail even when the code is stuck into a Julia function then? Note that I was using per thread `MersenneTwister` objects, and I am quite sure that no memory is allocated in the RNG.

**Comment by kpamnany** [comment]
On further experimentation, it looks like accessing any variables created in the immediate environment from threads can cause segfaults. Accessing function parameters is fine though. We've had no troubles with crashes if we put threaded code into its own function (nothing else in the function but the ``@threads`` block).

**Comment by JeffBezanson** [comment]
I get

```
*** Error in `./julia': double free or corruption (!prev): 0x000000000165ce30 ***

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f1e71c6a394)
unknown function (ip: 0x7f1e71c7666e)
unknown function (ip: 0x7f1e71c78890)
realloc at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
arraylist_grow at /home/jeff/src/julia/src/support/arraylist.c:55
jl_gc_add_finalizer at /home/jeff/src/julia/src/gc.c:413
finalizer at ./base.jl:75
unknown function (ip: 0x7f1e6f109c20)
jl_apply_generic at /home/jeff/src/julia/src/gf.c:1702
convert at ./gmp.jl:112
setindex! at ./array.jl:303
unknown function (ip: 0x7f1c6cc830c1)
##_threadsblock#6638 at ./threading.jl:2
```

Need to synchronize finalizers.
