### ISSUE TITLE
Better error message when module is not at toplevel

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10720]
I'm getting a weird error in https://github.com/JuliaLang/Tk.jl/pull/93 that only happens on Travis, not my own machine:
```
ERROR: LoadError: cannot define function eval; it already has a value
 in include at ./boot.jl:250
 in include_from_node1 at loading.jl:129
 in process_options at ./client.jl:317
 in _start at ./client.jl:401
while loading /home/travis/.julia/v0.4/Tk/test/runtests.jl, in expression starting on line 291
```
For Travis, this happens on both 0.3 and 0.4. The relevant line is [here](https://github.com/JuliaLang/Tk.jl/blob/4207c491a17f9c721868ef9e125a365921e6b704/test/runtests.jl#L291), and all it does is create a new module. I'm aware that modules define their own `eval`, but I'm puzzled about what's happening and why this crops up only on Travis. Anyone have any ideas?

**Comment by timholy** [comment]
Ah, should have figured that out myself. Diagnosis:
- `module` must be at toplevel
- the difference between my machine and Travis is just that I have Winston installed, and Travis doesn't.

I'm going to leave this open because it might be nice to improve the quality of the error message.

**Comment by JeffBezanson** [comment]
We now give `ERROR: syntax: module expression not at top level`, so I think this is fixed.
