### ISSUE TITLE
Pkg: can't tag without commit privileges

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#10723]
I noticed that now one needs commit privileges to submit a request to tag a new release:

```
julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing GnuTLS permanent tags: v0.0.4
ERROR: Permission to JuliaWeb/GnuTLS.jl.git denied to timholy.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git --work-tree=/home/tim/.julia/v0.4/GnuTLS --git-dir=/home/tim/.julia/v0.4/GnuTLS/.git push -q origin refs/tags/v0.0.4:refs/tags/v0.0.4`, ProcessExited(128)) [128]
 in wait at ./task.jl:305
 in wait at ./task.jl:221
 in wait at task.jl:54
 in sync_end at ./task.jl:332
 in publish at pkg/entry.jl:340
 in anonymous at pkg/dir.jl:29
 in cd at file.jl:20
 in cd at pkg/dir.jl:29
 in publish at pkg.jl:59
```

Is that intended? If we allow it, then the tag won't exist in the repo; on the other hand, I thought it was once one of the design goals to allow this. Of course you can circumvent this manually (see https://github.com/JuliaLang/METADATA.jl/pull/2395).

**Comment by jakebolewski** [comment]
You need commit access to push the tags to the remote repo, otherwise the tagged versions in METADATA, your local copy, and the remote github repo will diverge and require human intervention to patch up.

It would be nice to check that the tags exist on the remote repo before being pushed to METADATA (as a test for a METADATA PR), which would keep things consistent.

**Comment by kshyatt** [comment]
I'm bumping this - should this still be open? Is this still a problem?

**Comment by StefanKarpinski** [comment]
This will be superseded by Pkg3, so maybe not.

**Comment by tkelman** [comment]
The process of tagging will be superseded? This is still relevant but for the existing metadata versions on 0.4 and 0.5 would be best solved by an automatic check that the git tag has been pushed and corresponds to the metadata tag.

**Comment by simonbyrne** [comment]
If this is still an issue, please open on https://github.com/JuliaLang/Pkg.jl
