### ISSUE TITLE
change openblas to a git submodule

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#10730]
switching the openblas dependency to a git repository would make it easier to fix issues in openblas and contribute them back upstream. i'm opening this as an issue to get feedback on it before I go about making it into a pull request

**Comment by tkelman** [comment]
-1, this has been opened and shot down before. Would rather have fewer submodules rather than more. Git, and Github, just handles them messily.

**Comment by StefanKarpinski** [comment]
As long as we support submodule updating through make, I find them more convenient than tarballs.

**Comment by tkelman** [comment]
Packaging Julia and its dependencies into a git-less tarball, or interacting with distribution buildbots are the major places where submodules are just completely the wrong way to do things and cause more pain than any minor benefits they provide.

**Comment by ViralBShah** [comment]
git submodules in my opinion make sense if we need to ship non-release versions of libraries, which should generally be avoided. For submitting patches and such, it is easy enough to maintain a separate repo.

So long as we have even one git submodule, we are already paying the price for all that complexity @tkelman refers to. My personal preference is to have none, but adding one more at this stage doesn't seem like it should matter.

**Comment by ViralBShah** [comment]
I would still prefer that we stay on released/tagged versions of libraries, even if we use git submodules.

**Comment by tkelman** [comment]
The more of them we have, the more frequently we'll change any of them. Part of the messiness of submodules comes from strange-looking state after a change.

I was planning on doing a PR for turning utf8proc back from a submodule into a tarball. Doing the reverse with openblas seems like going in the wrong direction for very little benefit.

**Comment by ViralBShah** [comment]
+1 to getting rid of submodules altogether. If we tag a release for own version of libuv, we can pull this off.

**Comment by vtjnash** [comment]
i'll try to put together a PR in the next few days

**Comment by tkelman** [comment]
See #10177 for a little bit more work that would need to be done in the case of openlibm, and a vote not to change the name of our libuv fork - we can certainly make a tag there if needed though.

**Comment by tkelman** [comment]
flisp also has some libuv-related hardcoding https://github.com/JuliaLang/julia/blob/b9e165b90a7057697d1062024f5c329465a52cf9/src/flisp/flisp.h#L9

**Comment by tkelman** [comment]
more or less done by #10743
