### ISSUE TITLE
Inference/inlining issue?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#10746]
I'm running into a really weird situation and I'm having trouble reducing.

Take the code [here](https://gist.github.com/quinnj/2054b2018a5fb32ee983)

The usage is:
```julia
reload("/Users/jacobquinn/.julia/v0.4/Domo/src/CSV.jl")

file = CSV.File("/Users/jacobquinn/domo/piston/dfa/Bare_Weekly.csv") # CSV file with 1.1M rows or so
Profile.clear()
@profile CSV.validate(file,IOBuffer(256);checktypes=false)
Profile.print()
```
Run as is, it takes 5.8 seconds on my machine to validate the 1,162,332 rows. Profiling, however, shows that a *huge* amount of time is spent on line 170, which is crazy since it's doing nothing different than lines 158, 162, 164, or 168.

Now the weird part: if I change line 170 to
```julia
        elseif c.x == '\n' # hard code the newline character
```
it runs in 1.7 seconds!

As I said, trying to reduce the case has been tricky, but if anyone is willing to check this out, I'd appreciate any insight and if this is really a bug or not. (I can share the exact CSV file privately if needed)

**Comment by nalimilan** [comment]
Well, `n` is defined as `newline::Union(Char,Chars)`, so it introduces type-instability here, which is not the case on other lines. You'd better always make it of type `Chars`, putting the character in the first field, and `'\0'` in the second field.

Maybe you could also hardcode `newline` and just skip any `'\r'` that appears right before a `'\n'`. Not sure what's the recommended way of dealing with this.

**Comment by quinnj** [comment]
Ah.....yes, that's the root of it. Interestingly, I was some-what aware of this, because my original code for line 170 was
```julia
elseif checknewline(f,c,n)
```
which dispatched based on `n`. My ultimate problem though was that I was pulling `n` out of the `File` struct within the `validateline!` function, so when the method was compiled, it wasn't sure what `n` was going to be. I just put `n` as an argument to `validateline!` and everything's solved. I think I'll probably tweak the code though because the `Chars` case is still not optimal. I think we're probably better off detecting `'\r'` and ignoring or something.

Sorry for the noise, mais merci pour l'aide @nalimilan!
