### ISSUE TITLE
Cannot extend empty matrices of composite types

### ISSUE THREAD

**Issue by ericjang** [JuliaLang/julia#10740]
In Julia v0.3, I can't seem to create an empty matrix of a composite type and then extend it by size 1 in each of its dimensions. Strangely enough, the operation works fine for numeric arrays.

``` julia
type MyType
    x
end

type MyContainer
    foo::MyType
end

# constructor
function MyContainer()
    MyContainer(MyType(3))      
end

# this works...
x = Array(Float64,(0,0))
x = hcat(x,Array(Float64,(0,1)))
x = vcat(x,Array(Float64,(1,1)))

# this does not
# empty matrix of containers
x = Array(MyContainer,(0,0))
x = hcat(x,Array(MyContainer,(0,1)))
x = vcat(x,Array(MyContainer,(1,1)))
```

```
Output Error:
ERROR: access to undefined reference
 in setindex! at multidimensional.jl:76
 in vcat at abstractarray.jl:605
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading test.jl, in expression starting on line 23
```

(This corresponds to the vcat call)

**Comment by tkelman** [comment]
Right, so what's happening here is `Array(MyContainer,(1,1))` starts out with an `#undef` element, which you can't copy over into the result of `vcat`. If you assign it a value first then it should work.
```
x = Array(MyContainer,(0,0))
x = hcat(x,Array(MyContainer,(0,1)))
y = Array(MyContainer,(1,1))
y[1] = MyContainer(MyType(:whatever))
vcat(x,y)
```

**Comment by ericjang** [comment]
This behavior seems a bit odd - consider the use case where a user wants to store a matrix of some composite type, i.e. edge data in a graph data structure. Adding a vertex means the adjacency matrix needs to be re-sized, but the user doesn't have anything to put in the matrix yet.

**Comment by tkelman** [comment]
In order for a new element to be referenced on the rhs of any expression, it has to be defined. You should pick some default or "zero" state, or maybe use a Nullable type, for newly created elements if you want to put them into arrays. `vcat(x,y)` needs to be able to reference the elements to copy them into the new output array.

**Comment by JeffBezanson** [comment]
I've sometimes wondered if we should allow copying arrays with undefined elements in more cases. For example `copy(a)` allows it.
