### ISSUE TITLE
Build failure with SuiteSparse 4.0.2

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#10750]
RPM nightlies fail on RHEL 7 and Fedora 20, where SuiteSparse is only 4.0.2 (it works where it is 4.2.1):
```
 g++ -m64 -shared -fPIC -L/builddir/build/BUILD/julia/build/usr/lib64/julia -L/builddir/build/BUILD/julia/build/usr/lib64 -L/builddir/build/BUILD/julia/build/usr/lib64 -o /builddir/build/BUILD/julia/build/usr/lib64/julia/sys0.so /builddir/build/BUILD/julia/build/usr/lib64/julia/sys0.o $([ Linux = Darwin ] && echo '' -Wl,-undefined,dynamic_lookup || echo '' -Wl,--unresolved-symbols,ignore-all ) $([ Linux = WINNT ] && echo '' -ljulia -lssp)
true -ignore /builddir/build/BUILD/julia/build/usr/lib64/julia/sys0.so
 cd base && /builddir/build/BUILD/julia/build/usr/bin/julia -C generic --build /builddir/build/BUILD/julia/build/usr/lib64/julia/sys -J/builddir/build/BUILD/julia/build/usr/lib64/julia/$([ -e /builddir/build/BUILD/julia/build/usr/lib64/julia/sys.ji ] && echo sys.ji || echo sys0.ji) -f sysimg.jl || { echo '*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***' && false; } 
symbol could not be found cholmod_version (-1): /lib64/libcholmod.so: undefined symbol: cholmod_version
WARNING: 
    CHOLMOD version incompatibility
    Julia was compiled with CHOLMOD version 2.0.1, but is currently linked with a
    version older than 2.1.0. This might cause Julia to terminate when working with
    sparse matrices for operations involving factorization of a matrix, e.g. solving
    systems of equations with \.
    It is recommended that you either upgrade the package that provides CHOLMOD or
    download the OS X or generic Linux binary from www.julialang.org, which is
    shipped with the correct versions of all dependencies.Warning: error initializing module CHOLMOD:
OutOfMemoryError()
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-20-x86_64/julia-0.4.0-0.20150404.fc21/build.log

The `symbol could not be found` warnings have been present for a very long time, and yet the tests passed fine. Is the version mismatch detection too strict, or is something wrong with the way the library is loaded? I'm passing `USE_SYSTEM_SUITESPARSE=1`.

**Comment by ViralBShah** [comment]
cc @andreasnoack

**Comment by andreasnoack** [comment]
Please don't use old versions of SuiteSparse. In general they won't work correctly with Julia even if the tests pass. If the distro is not providing a recent version, we'll have to bundle our own.

**Comment by jiahao** [comment]
I don't see how we can make this error message more explicit. Closing unless @nalimilan wants to track this as a packaging issue.

**Comment by nalimilan** [comment]
Well, I see at least two things to improve:
- README.md does not mention any minimum requirement for SuiteSparse (easy -- will fix that if you tell me what's the minimum expected version)
- The error message `Julia was compiled with CHOLMOD version 2.0.1, but is currently linked with a version older than 2.1.0.` is quite misleading as it seems to imply that a different version was used for compilation, while we're precisely compiling. Is `2.0.1` a typo for `2.1.0`?

**Comment by andreasnoack** [comment]
Ok. I can see that the error is confusing in this case, but it is not a typo. I'll see if I can come up with a better message.

I think we should require at least version 2.1.0 because this is the first version where we can actually detect if the compile time and run time versions of CHOLMOD match.

**Comment by nalimilan** [comment]
Thanks. I just pushed https://github.com/JuliaLang/julia/commit/2435f29ff3e1627c552a96db326512025189817b to update README.md.

**Comment by jiahao** [comment]
Looks like we are good now?

**Comment by nalimilan** [comment]
No, I don't think we're done. @andreasnoack said he would try to improve the error message.
