### ISSUE TITLE
Unclear error message when julia trying to access home folder on unavailable network drive.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#10757]
At work, I usually have my HOME folder on a network drive and when I try to start julia on another network I get the following error message (after about 30 seconds of waiting):

``` julia
D:\Users\kricarl.NET\AppData\Local\Julia-0.4.0-dev\bin>julia
ERROR: stat: unknown error (UNKNOWN)
 in stat at stat.jl:40
 in try_include at client.jl:184
 in load_juliarc at client.jl:340
 in process_options at client.jl:262
 in _start at client.jl:389
```

Maybe it is possible to improve this message.

Edit: Adding versioninfo:

```
Julia Version 0.4.0-dev+4159
Commit 444c60e (2015-04-05 04:39 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
Anyone have any reasons against making `try_include` use an actual try-catch? Maybe only on Windows, if `isfile` can never fail anywhere else?

**Comment by vtjnash** [comment]
I think we now include the file name, and since #38261 it won't crash
