### ISSUE TITLE
Excess memory allocation while invoking threads

### ISSUE THREAD

**Issue by abhijithch** [JuliaLang/julia#10752]
While trying out threading, using `@threads all for i=1:N` I realized too much of memory being allocated. Further investigating the function using `@code_typed` I am seeing a lot of `::Any` types as seen in the below attachment, 
![thread](https://cloud.githubusercontent.com/assets/2932535/6998110/6d927c82-dbf3-11e4-9ae2-5bbdc3a07adb.jpg)
I would like to know if I am doing anything wrong here.

**Comment by carnaval** [comment]
It probably wouldn't hurt to tighten those type bounds, however unless I'm mistaken I'm pretty sure we don't have multithread support in the GC. I'm not sure what the threads branch does right now but it is very much possible that GC is disabled entirely so I wouldn't worry too much about memory usage for now.

**Comment by carnaval** [comment]
Strike that, it says "memory allocation" not "memory usage", my bad.

**Comment by timholy** [comment]
It would be much better if you provide the code itself. In particular, are you running this at the REPL? If so, you should put your code in a function.

**Comment by kpamnany** [comment]
@carnaval: The ``threading`` branch is frozen right before the new GC went in (it's using the old GC, which is very unfortunate for performance we're finding).

**Comment by abhi123link** [comment]
The code I was trying is the nbody.jl at test/perf/shootout, I have only added the `@threads all` in the for loops, in the function `advance()`,
```
#
# The Computer Language Benchmarks Game
# nbody benchmark
# http://shootout.alioth.debian.org/u32/performance.php?test=nbody
#
# A straight port from the Java version
#

#module NBody

using Base.Threading

# Constants
const solar_mass = 4 * pi * pi
const days_per_year = 365.24

# A heavenly body in the system
type Body
    x::Float64
    y::Float64
    z::Float64
    vx::Float64
    vy::Float64
    vz::Float64
    mass::Float64
end

function offset_momentum(b::Body, px, py, pz)
    b.vx = -px / solar_mass
    b.vy = -py / solar_mass
    b.vz = -pz / solar_mass
end

function init_sun(bodies)
    local px::Float64 = 0.0
    local py::Float64 = 0.0
    local pz::Float64 = 0.0
    for b in bodies
        px += b.vx * b.mass
        py += b.vy * b.mass
        pz += b.vz * b.mass
    end
    offset_momentum(bodies[1], px, py, pz)
end

function advance(bodies::Vector{Body}, dt::Float64)
    @threads all for i = 1:length(bodies)
        bi = bodies[i]
        for j = i+1:length(bodies)
            bj = bodies[j]
            dx = bi.x - bj.x
            dy = bi.y - bj.y
            dz = bi.z - bj.z
            dsq = dx^2 + dy^2 + dz^2
            distance::Float64 = sqrt(dsq)
            mag = dt / (dsq * distance)

            bi.vx -= dx * bj.mass * mag
            bi.vy -= dy * bj.mass * mag
            bi.vz -= dz * bj.mass * mag

            bj.vx += dx * bi.mass * mag
            bj.vy += dy * bi.mass * mag
            bj.vz += dz * bi.mass * mag
        end
    end

    for i = 1:length(bodies)
        b=bodies[i]
        b.x += dt * b.vx
        b.y += dt * b.vy
        b.z += dt * b.vz
    end
end

function energy(bodies)
    local e::Float64 = 0.0
    for i = 1:length(bodies)
        e += 0.5 * bodies[i].mass *
             (bodies[i].vx^2 + bodies[i].vy^2 + bodies[i].vz^2)
        for j = i+1:length(bodies)
            dx = bodies[i].x - bodies[j].x
            dy = bodies[i].y - bodies[j].y
            dz = bodies[i].z - bodies[j].z
            distance = sqrt(dx^2 + dy^2 + dz^2)
            e -= (bodies[i].mass * bodies[j].mass) / distance
        end
    end
    e
end


function nbody(N::Int=1000)
    jupiter = Body( 4.84143144246472090e+00,                   # x
                   -1.16032004402742839e+00,                   # y
                   -1.03622044471123109e-01,                   # z
                   1.66007664274403694e-03 * days_per_year,   # vx
                   7.69901118419740425e-03 * days_per_year,   # vy
                   -6.90460016972063023e-05 * days_per_year,   # vz
                   9.54791938424326609e-04 * solar_mass)      # mass

    saturn = Body( 8.34336671824457987e+00,
                  4.12479856412430479e+00,
                  -4.03523417114321381e-01,
                  -2.76742510726862411e-03 * days_per_year,
                  4.99852801234917238e-03 * days_per_year,
                  2.30417297573763929e-05 * days_per_year,
                  2.85885980666130812e-04 * solar_mass)

    uranus = Body( 1.28943695621391310e+01,
                  -1.51111514016986312e+01,
                  -2.23307578892655734e-01,
                  2.96460137564761618e-03 * days_per_year,
                  2.37847173959480950e-03 * days_per_year,
                  -2.96589568540237556e-05 * days_per_year,
                  4.36624404335156298e-05 * solar_mass)

    neptune = Body( 1.53796971148509165e+01,
                   -2.59193146099879641e+01,
                   1.79258772950371181e-01,
                   2.68067772490389322e-03 * days_per_year,
                   1.62824170038242295e-03 * days_per_year,
                   -9.51592254519715870e-05 * days_per_year,
                   5.15138902046611451e-05 * solar_mass)

    sun = Body(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, solar_mass)

    bodies = Body[sun, jupiter, saturn, uranus, neptune]

    init_sun(bodies)
    @printf("%.9f\n", energy(bodies))
    for i = 1:N
        advance(bodies, 0.01)
    end
    @printf("%.9f\n", energy(bodies))
end

# end # module

 nbody(1000)
 @time gc()
 @time nbody(1000)
```

**Comment by ViralBShah** [comment]
@abhi123link and I were looking at this code the other day. When using `threading` branch, but without `@threads`, all the type inference is fine and there is no unnecessary allocation. With `@threads`, the type inference seems to go for a toss, and a lot of memory gets allocated.

**Comment by ViralBShah** [comment]
@JeffBezanson @keno If you guys can review this and if it has a quick fix, it would greatly help.

**Comment by JeffBezanson** [comment]
I am seeing about a 4x slowdown when `@threads` is added, and 9 allocations per call to `advance`.

```
# N = 1000000
# baseline
jeff@gurren:~/src/julia$ JULIA_NUM_THREADS=1 ./julia test/perf/shootout/nbody.jl 
  0.239370 seconds (159 allocations: 10.902 KB)

# with @threads
jeff@gurren:~/src/julia$ JULIA_NUM_THREADS=1 ./julia test/perf/shootout/nbody.jl 
  0.918974 seconds (9.00 M allocations: 366.222 MB, 4.87% gc time)
```

Since there are exactly 9 allocations per call to `advance`, that means there are no allocations inside the loops inside `advance`. So type inference is fine and there is some other reason for the slowdown. Probably extra indirection from accessing things through the closure environment.

**Comment by JeffBezanson** [comment]
Further breakdown. Time when the loops are enclosed in an inner function, but none of the rest of the thread-related overhead is present:

```
jeff@gurren:~/src/julia$ JULIA_NUM_THREADS=1 ./julia test/perf/shootout/nbody.jl 
  0.686352 seconds (9.00 M allocations: 366.222 MB, 6.54% gc time)
```

So 25% of the time is thread infrastructure overhead. This includes calling `jl_threading_run`, which calls `jl_get_specialization`, then `ti_threadgroup_fork`, then `ti_run_fun`.

This is a good time to point out that the `bodies` array has only 5 elements, so putting `@threads` in `advance` puts threading in the almost-inner loop. So this particular benchmark mostly measures thread overhead. Worthwhile to measure, but we should be aware of that.

**Comment by yuyichao** [comment]
A lot (all?) of the comment here doesn't apply anymore. The allocation should be minimum now (unless you hit https://github.com/JuliaLang/julia/issues/15276 which is possible to workaround) and the infrastructure overhead should also be lower now. Feel free to open new issues if any of them are still not fixed.
