### ISSUE TITLE
--inline=base option?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10774]
If we're going to be stuck needing `--inline=no` for accurate code coverage for a while, it might be nice to have an option that inlines only functions included with Julia. Currently tests that involve any non-trivial amount of computation run very slowly with `--inline=no`, since even things like `+` can't be inlined, which can sometimes be so expensive that tests that would otherwise take a minute to run instead cause Travis to time out. Admittedly, `--inline=base` is a bit of a misnomer, since the option would ideally not inline new methods of functions in Base defined that are defined in packages.

**Comment by StefanKarpinski** [comment]
If you think of `base` as describing methods rather than functions, then it's still accurate so I think that's ok. This seems like the right thing to do.

**Comment by ssfrr** [comment]
I hear that since #18196 we no longer need to turn off inlining for coverage. Does that mean this issue can be closed?

**Comment by simonster** [comment]
Yes
