### ISSUE TITLE
Help sought on updating `threading` branch -- LLVM issues

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#10772]
I've been trying to update the `threading` branch to get it on par with `master`, and running into a problem that I need help with.  The symptom is during a build, I get:
```
    LINK usr/bin/julia
    JULIA usr/lib/julia/sys0.o
LLVM ERROR: Cannot select: 0x212a650: i64 = X86ISD::WrapperRIP 0x212a548 [ORD=6] [ID=76] dbg:boot.jl:277
  0x212a548: i64 = TargetGlobalTLSAddress<%jl_value_t*** @jl_pgcstack> 0 [TF=10] [ORD=6] [ID=45] dbg:boot.jl:277
In function: julia__new_0
make[1]: *** [/localdisk/adrobiso/tmp/julia/usr/lib/julia/sys0.o] Error 1
make: *** [julia-sysimg-release] Error 2
```
@keno mentioned a while back that the problem might be that the right options are not being passed to LLVM.  But the options appear to be the same as the working `threading` branch, as far as I can tell from poking around with gdb.  Alas the call chain goes through a pattern-matching interpreter that I don't understand.

I've put a copy of my current work in branch `adr/theading`.  It's a merge of two branches:
* `threading`
* `adr/snapshot`, which is a snapshot of `master` that I took yesterday.
The number of threads defaults to `1`, so the problem is likely not a race condition.  (indeed, I still have work to do on `gc.c` to make it thread-safe.)  Any suggestions on how to fix or debug the LLVM error would be appreciated.

**Comment by Keno** [comment]
I suspect you need to set the code model to small as well as the relocation model to `PIC_`.

**Comment by ArchRobison** [comment]
Thanks!  I had missed a spot where the merge had brought in new logic for setting the relocation and code models.  Now I'm happily crashing elsewhere.

**Comment by ArchRobison** [comment]
I generalized the title so I can continue the discussion to the next problem.  I'm getting assertion failures while [building `sys0.0`](https://gist.github.com/ArchRobison/e695fcb9d6361914b1e7#file-gistfile1-txt).   The failure is during symbol relocation, specifically [this assertion](https://github.com/JuliaLang/llvm/blob/jl/thread-local-storage/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L322).  The failing offset is on the order of 8.7E9, a little over two bits beyond a 32-bit offset, so it seems to not be total trash.  How do I avoid generating 32-bit relocations?  I tried setting the CodeModel to Large, but that didn't seem to help.  Turning off the assertion just got me to a failure of a [similar assertion](https://github.com/JuliaLang/llvm/blob/jl/thread-local-storage/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp#L309) with a offset of  also about 8.7E9.

Or is there some hack (to avoid long offsets) in the `threading` branch  that I've accidentally disabled?  I'm not clear on how to go about tracking why the large offsets are being generated.  

@keno or @kpamnany, do you have suggestions?

**Comment by Keno** [comment]
Yes, this is a known problem with that version of the patch. I have a new one up for review which fixes this (see kf/tlsrebase3 at JuliaLang/llvm).

**Comment by Keno** [comment]
(Though hold on for a couple of minutes while I push the latest updates to that branch).

**Comment by ViralBShah** [comment]
How do I use the new TLS updates on the threading branch?

**Comment by Keno** [comment]
The latest branch is up at `kf/tlsrebase5`. You should be able to update the branch name in `Make.inc`, but you may have to rebase the threading branch for some julia codegen changes as the new branch is against LLVM 3.7.

**Comment by ArchRobison** [comment]
With `kf/tlsrebase5` for LLVM and a recent snapshot of `master` of Julia, I'm still getting a [relocation failure](https://gist.github.com/ArchRobison/9310cb019b4974219bf7) similar to what I was seeing before.  To replicate, checkout my branch [`adr/threading`](https://github.com/JuliaLang/julia/tree/adr/threading) and build..

**Comment by Keno** [comment]
That shouldn't be possible anymore, but I'll take a look.

**Comment by Keno** [comment]
@ArchRobison Your branch has a few leftover merge markers in base/inference.jl

**Comment by Keno** [comment]
I think I see what's going on. Since LLVM now requires the small code model for PIC_, we're getting problems with the regular symbols, even though the problems with thread-local symbols are resolved *sigh*. I guess I'll look at that next.

**Comment by ArchRobison** [comment]
Thanks for looking at this.  I've resolved the merge of `base/inference.jl`.

**Comment by vtjnash** [comment]
@Keno can you give a quick update on the state of the llvm patches? the kf/tlsrebase3 branch didn't build for me (although i have not looked into why).

**Comment by Keno** [comment]
I'll put up a branch with the most up to date rebase I have.

**Comment by Keno** [comment]
Up at kf/tlsrebaseagain

**Comment by vtjnash** [comment]
i'm still getting a build error, just typing make from the `jn/threading` branch:
```
/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/lib/ExecutionEngine/RuntimeDyld/TLSSymbolResolverELF.cpp:106:12: error: no matching constructor for
      initialization of 'RuntimeDyldELF::TLSSymbolInfoELF'
    return RuntimeDyldELF::TLSSymbolInfoELF(Descriptor->key, Descriptor->offset, SI.getFlags()).getOpaque();
           ^                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h:36:5: note: candidate constructor not viable: no known
      conversion from 'unsigned long' to 'llvm::RuntimeDyldELF::TLSSymbolInfoELF::ModuleInfo' for 1st argument
    TLSSymbolInfoELF(ModuleInfo Mod, uint64_t Offset, JITSymbolFlags Flags = JITSymbolFlags::None) :
    ^
/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h:38:5: note: candidate constructor not viable: requires
      single argument 'Data', but 3 arguments were provided
    TLSSymbolInfoELF(RuntimeDyld::TLSSymbolInfo Data) : Data(Data) {};
    ^
/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h:27:9: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
  class TLSSymbolInfoELF {
        ^
/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.h:27:9: note: candidate constructor
      (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
1 error generated.
make[4]: *** [/Volumes/Lion/Users/jameson/Documents/julia3/deps/llvm-svn/build_Debug+Asserts/lib/ExecutionEngine/RuntimeDyld/Debug+Asserts/TLSSymbolResolverELF.o] Error 1
```
```
$ git status
On branch kf/tlsrebaseagain
Your branch is up-to-date with 'origin/kf/tlsrebaseagain'.
```

**Comment by Keno** [comment]
Ah, you're on OS X?

**Comment by Keno** [comment]
It's been a while since I looked at this code, but try `TLSSymbolInfoELF(ModuleInfo(Descriptor->key,0),...)`
