### ISSUE TITLE
rationalize in versions 0.3.7 and 0.4.0-dev behave differently

### ISSUE THREAD

**Issue by lbenet** [JuliaLang/julia#10781]
In version 0.3.7 and 0.4.0-dev `convert{T<:Integer}(::Type{Rational{T}}, x::FloatingPoint)`  calls `rationalize` with `tol=0`. The actual implementation of `rationalize` differs though. The point of this issue is that the results may be different.

For example, in version 0.3.7, I get:
```julia
julia> a = 1/factorial(5)
0.008333333333333333

julia> rationalize(a) ## Ok
1//120

julia> convert(Rational{Int},a) ## this is OK
1//120
```

However, version 0.4.0-dev+4195 yields:
```julia
julia> a = 1/factorial(5)
0.008333333333333333

julia> rationalize(a)  ## Ok
1//120

julia> convert(Rational{Int},a)  ## ???
4803839602528529//576460752303423488
```
Probably related with changes implemented in #8216, https://github.com/JuliaLang/julia/commit/f765ad8040c58c7305d3ddcedd8ca556c2ae1d39 and/or https://github.com/JuliaLang/julia/commit/f1eca727264cb5837ba44eaaf6a42e2016983a1f

CC: @nolta @simonbyrne

**Comment by simonbyrne** [comment]
Yes, we changed `convert` so that it should be exact whenever possible. `1/120` is rounded to the nearest `Float64` value, the exact value of which is 4803839602528529 &times; 2<sup>-59</sup>.

**Comment by simonbyrne** [comment]
Actually, you're right, `convert` didn't change, but I fixed `rationalize` such that the tolerance is in terms of exact numeric values, and not rounded, see #8611.

**Comment by lbenet** [comment]
Thanks for clarifying this; I see now the point.

Should #8611 be also back ported to version 0.3 for consistency?

**Comment by pao** [comment]
> Should #8611 be also back ported to version 0.3 for consistency?

Then it would be inconsistent with previous versions on the 0.3 branch. I believe this is a behavior change that would not be suitable for backporting.

**Comment by mbauman** [comment]
Since `1//120` isn't exactly `1/120`, should `convert(Rational{Int8}, 1/120)` throw an InexactError?  It currently returns `1//120`.

**Comment by simonbyrne** [comment]
I tried to explain it in the help text to `convert`:

>    If "T" is a "FloatingPoint" or "Rational" type, then it will return the closest value to "x" representable by "T".

**Comment by mbauman** [comment]
Ah, yes, I can see how those exceptions to the exact conversion rule make sense.  Should have read the new help myself.
