### ISSUE TITLE
Use OpenBLAS "develop" branch for Julia nightly builds

### ISSUE THREAD

**Issue by hiccup7** [JuliaLang/julia#10788]
I propose that the Julia project use the "develop" branch of OpenBLAS for nightly builds, while continuing to use an OpenBLAS release for a Julia release.

Benefits:
1. Quicker introduction of OpenBLAS fixes and enhancements into Julia
2. More developers testing OpenBLAS changes before an OpenBLAS release
3. Reduces probability of bugs in OpenBLAS releases
4. Using Julia nightlies is more convenient than building Julia+OpenBLAS from source
5. Users who can't or don't have time to build from source are enabled to test OpenBLAS changes
6. Encourages more involvement by new and trial Julia users
7. Helps alleviate the problem that there is no OpenBLAS package for Julia users to update.
8. Improves cooperation with OpenBLAS project, which is a key component of Julia.

An example of an OpenBLAS enhancement waiting to be tested: https://github.com/xianyi/OpenBLAS/issues/530

**Comment by pao** [comment]
Sounds fun, but taking an unstable upstream by default sounds scary: it's another dependency to regularly compile (and not a small one), and makes isolating failures more difficult.

We currently make it easy to select this (set `OPENBLAS_VER=develop` in Make.user); I'm not sure anything more aggressive is warranted.

**Comment by StefanKarpinski** [comment]
I agree with @pao here.

**Comment by pao** [comment]
If someone had the resources to run tests in this configuration, that could be useful.

**Comment by ViralBShah** [comment]
This is not a good idea. As @pao says, if someone has the resources to set up a test environment, and monitor it, nothing like it. This is easy to do yourself by setting the openblas version to `develop`, and I often do that.

**Comment by ViralBShah** [comment]
We also already co-operate closely with the openblas project testing out things before major releases, and reporting bugs, getting bugfixes, etc.

**Comment by tkelman** [comment]
It's not particularly hard for us to leverage our buildbot infrastructure to make one-off binaries for testing purposes, especially if there's a specific bugfix or performance improvement that someone would like to evaluate. But like everyone else here said, git master of Julia should depend on a specific version of each dependency, otherwise build results can be very unpredictable.
