### ISSUE TITLE
hex2num fails on sufficiently large values

### ISSUE THREAD

**Issue by sqweek** [JuliaLang/julia#10797]
eg.

```
julia> hex2num("fc024318")
ERROR: OverflowError()
 in parseint_nocheck at string.jl:1558
 in parseint_nocheck at string.jl:1569
 in parseint at string.jl:1572
 in hex2num at floatfuncs.jl:33
```

The problem appears to be that hex2num attempts to parse the hex string into a signed integer - see base/floatfuncs.jl:

```
function hex2num(s::AbstractString)
    if length(s) <= 8
        return box(Float32,unbox(Int32,parse(Int32,s,16)))
    end
    return box(Float64,unbox(Int64,parse(Int64,s,16)))
end
```

Changing Int32 to Uint32 fixes the issue:
```
julia> box(Float32,unbox(Uint32,parseint(Uint32,"fc024318",16)))
-2.7054377f36
```

Presumably the 64-bit case needs similar treatment.

**Comment by ihnorton** [comment]
Thanks, do you want to submit a pull request with the changes? (note that `Uint32` should be `UInt32` on master)

**Comment by sqweek** [comment]
Done. I realised it has nothing to do with the size of the hex-float, it just overflows when the sign bit is on. Eg `hex2num("bf800000")`, which correctly gives -1.0f0 after the patch.
