### ISSUE TITLE
`isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))` test failure on with LLVM 3.6

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#10795]
I see this failure on both i686 and x86_64 Fedora rawhide nightlies with LLVM 3.6 (with `USE_SYSTEM_LLVM=1` and `-D_GLIBCXX_USE_CXX11_ABI=1`). I had never tested it before, so the bug may have been present for a long time.
```
	From worker 4:	     * sorting              in  69.50 seconds
exception on 4: ERROR: LoadError: test failed: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in expression: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in error at ./error.jl:19
 in default_handler at ./test.jl:27
 in do_test at ./test.jl:50
 in runtests at /builddir/build/BUILD/julia/test/testdefs.jl:78
 in anonymous at ./multi.jl:836
 in run_work_thunk at ./multi.jl:587
 in anonymous at ./multi.jl:836
while loading complex.jl, in expression starting on line 7
	From worker 3:	     * mpfr                 in  21.30 seconds
	From worker 2:	     * broadcast            in  23.25 seconds
ERROR: LoadError: LoadError: test failed: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in expression: isequal(sqrt(complex(0.0,-0.0)),complex(0.0,-0.0))
 in anonymous at ./task.jl:1383
while loading complex.jl, in expression starting on line 7
while loading /builddir/build/BUILD/julia/test/runtests.jl, in expression starting on line 3
	From worker 4:	     * complex             Makefile:9: recipe for target 'all' failed
make[1]: Leaving directory '/builddir/build/BUILD/julia/test'
make[1]: *** [all] Error 1
make: *** [test] Error 2
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-rawhide-x86_64/julia-0.4.0-0.20150411.fc21/build.log

**Comment by simonbyrne** [comment]
I think this is due to #10377.

**Comment by tkelman** [comment]
We have a local patch for this when we build LLVM 3.6.0 from source. I think we got it on the list of backports for 3.6.1? You could try asking the Fedora LLVM maintainer to apply the same patch in the meantime.

**Comment by nalimilan** [comment]
Ah, good. If the patch is going to be shipped with LLVM 3.6.1, maybe I'll just wait or disable the test for now. I don't think many people are willing to use Julia on Fedora rawhide so early in the cycle.

Can somebody confirm it was accepted for 3.6.1?

**Comment by tkelman** [comment]
I don't see it backported yet? https://github.com/llvm-mirror/llvm/commits/release_36

Was nominated last month, can't find any followup though. http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20150309/265701.html

**Comment by simonbyrne** [comment]
Is there a convention on the llvm lists? Should I bump the nomination?

**Comment by tkelman** [comment]
Sounds like pinging the thread would be okay? http://article.gmane.org/gmane.comp.compilers.llvm.devel/84363

**Comment by ihnorton** [comment]
I've looked unsuccessfully for documentation as the LLVM backport process is unclear to me also. I would be happy to submit patches against release_36 on phabricator to give someone a button to click, if that was the convention (but it does not seem to be).

**Comment by ihnorton** [comment]
I guess maybe I should just give it a try :)

**Comment by JeffBezanson** [comment]
Closing as this is fixed on our end.

**Comment by tkelman** [comment]
@ihnorton did you ever try opening backport patches on phabricator? Still no sign of this or the win64 patches (I just replied again to that email) on https://github.com/llvm-mirror/llvm/commits/release_36

**Comment by ihnorton** [comment]
No, I read the phabricator instructions and AFAICT it is not any simpler than doing a cherry-pick. Still needs a command-line tool to integrate changes.
