### ISSUE TITLE
Unify parsing/conversion from string to `Float64` and `BigFloat`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#10790]
There currently seems to be no unified way of parsing/converting from a string to a `Float64` or `BigFloat`:
```
julia> parse(Float64, "3.5")
3.5

julia> parse(BigFloat, "3.5")
ERROR: MethodError: `parse` has no method matching parse(::Type{Base.MPFR.BigFloat}, ::ASCIIString)

julia> float("3.5")
3.5

julia> BigFloat("3.5")
3.5e+00 with 256 bits of precision

julia> Float64("3.5")
ERROR: MethodError: `convert` has no method matching convert(::Type{Float64}, ::ASCIIString)
```

So far, `int("3")` has been deprecated in favour of `parse(Int, "3")`.
Should `float("3.5")` not be deprecated too?

Actually, can't we remove `parse(Int, "3")` and `parse(Float64, "3.5")` in favour of
`Int("3")` and `Float64("3.5")`, in analogy to `BigFloat("3.5")` (which has been around for a long time)?

**Comment by simonster** [comment]
Perhaps a dup of #10594/#10599?

**Comment by dpsanders** [comment]
Yes, sorry, dup of #10594 , thanks.
