### ISSUE TITLE
Errors in Integer Multiply

### ISSUE THREAD

**Issue by jfdsac** [JuliaLang/julia#10802]
Am new to both Julia and GitHub so forgive me if I am posting this in the wrong spot.  I've tried to see if this bug has already been reported and I see some that may have similar causes, but not one that exactly matches.  
 
I believe there is a bug in the Integer Multiply function for some sets of large integers.  I came across this by accident doing some BigInt calculations, so I thought it was a BigInt bug, but then found it was simply (?) a problem with Integer Multiply. I have run these on both Julia 0.3.7 and 0.4.0 and on both 32 bit and 64 bit Windows systems (on three different computers) and all consistently give the same errors.  However, the corresponding Integer Divide (div) function on the same set of numbers seems to work correctly.   Floating point multiply and divide also seem OK.  Double checked that this error occurs not only in REPL but within a function (just to make sure that REPL wasn’t doing something strange).
 
On a 32-bit Windows system in Julia 0.3.7:
```
julia> y = 10000*12000
120000000
julia> y = 10000*120000
1200000000
julia> y = 10000*1200000
-884901888                                    <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000
-259084288                                    <<<<<<<<<<<<<<<<<<<
julia> y = 10000*120000000
1704124416                                    <<<<<<<<<<<<<<<<<<<
julia> y = 10000*1200000000
-138625024                                    <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000000
120000000000000
julia> y = 10000*120000000000
1200000000000000
julia> y = 10000*1200000000000
12000000000000000
julia> y = 10000*12000000000000
120000000000000000
julia> y = 10000*120000000000000
1200000000000000000
julia> y = 10000*1200000000000000
-6446744073709551616          <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000000000000
-9127208515966861312          <<<<<<<<<<<<<<<<<<<
julia> y = 10000*120000000000000000
961635208879144960             <<<<<<<<<<<<<<<<<<<
julia> y = 10000*1200000000000000000
-8830391984918102016          <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000000000000000
120000000000000000000000
 ```

 
On a 64-bit Windows system in Julia 0.4.0:
```
julia> y = 10000*12000
120000000
julia> y = 10000*120000
1200000000
julia> y = 10000*1200000
12000000000
julia> y = 10000*12000000
120000000000
julia> y = 10000*120000000
1200000000000
julia> y = 10000*1200000000
12000000000000
julia> y = 10000*12000000000
120000000000000
julia> y = 10000*120000000000
1200000000000000
julia> y = 10000*1200000000000
12000000000000000
julia> y = 10000*12000000000000
120000000000000000
julia> y = 10000*120000000000000
1200000000000000000
julia> y = 10000*1200000000000000
-6446744073709551616          <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000000000000
-9127208515966861312          <<<<<<<<<<<<<<<<<<<
julia> y = 10000*120000000000000000
961635208879144960              <<<<<<<<<<<<<<<<<<<
julia> y = 10000*1200000000000000000
-8830391984918102016           <<<<<<<<<<<<<<<<<<<
julia> y = 10000*12000000000000000000
120000000000000000000000
```

Enjoy!

[ihn: edit - code boxes]

**Comment by johnmyleswhite** [comment]
Are you sure this isn't how machine precision numbers work?

I'm guessing the places where you have italics are really multiplications?

**Comment by jiahao** [comment]
Please see the FAQ:

http://julia.readthedocs.org/en/latest/manual/faq/?highlight=machine%20integer#why-does-julia-use-native-machine-integer-arithmetic

**Comment by jfdsac** [comment]
Sorry about that - cut and paste into GitHub removed the '*'

These are all Integer Muliplies...


julia> y = 10000*12000
 120000000
 julia> y = 10000*120000
 1200000000
 julia> y = 10000*1200000
 -884901888 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000
 -259084288 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*120000000
 1704124416 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*1200000000
 -138625024 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000000
 120000000000000
 julia> y = 10000*120000000000
 1200000000000000
 julia> y = 10000*1200000000000
 12000000000000000
 julia> y = 10000*12000000000000
 120000000000000000
 julia> y = 10000*120000000000000
 1200000000000000000
 julia> y = 10000*1200000000000000
 -6446744073709551616 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000000000000
 -9127208515966861312 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*120000000000000000
 961635208879144960 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*1200000000000000000
 -8830391984918102016 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000000000000000
 120000000000000000000000

On a 64-bit Windows system in Julia 0.4.0:

julia> y = 10000*12000
 120000000
 julia> y = 10000*120000
 1200000000
 julia> y = 10000*1200000
 12000000000
 julia> y = 10000*12000000
 120000000000
 julia> y = 10000*120000000
 1200000000000
 julia> y = 10000*1200000000
 12000000000000
 julia> y = 10000*12000000000
 120000000000000
 julia> y = 10000*120000000000
 1200000000000000
 julia> y = 10000*1200000000000
 12000000000000000
 julia> y = 10000*12000000000000
 120000000000000000
 julia> y = 10000*120000000000000
 1200000000000000000
 julia> y = 10000*1200000000000000
 -6446744073709551616 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000000000000
 -9127208515966861312 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*120000000000000000
 961635208879144960 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*1200000000000000000
 -8830391984918102016 <<<<<<<<<<<<<<<<<<<
 julia> y = 10000*12000000000000000000
 120000000000000000000000

**Comment by nalimilan** [comment]
If you tried `BigInt(10000*20000000000000000)`, try `BigInt(10000)*BigInt(120000000000000000)` instead: you need to convert to `BigInt` *before* doing the multiplication.

**Comment by jfdsac** [comment]
I see GitHub does not let me enter a '*'

Please do an Integer Multiply with 10000 and 12000000000000000 and see what you get...........

**Comment by jfdsac** [comment]
GitHub seems to not like my '*'

Please do an Integer Multiply of 10000  times 12000000000000000  and higher numbers.

Don't think BigInt is the problem, since large Integers in my example come out correctly...

**Comment by ihnorton** [comment]
> Please do an Integer Multiply of 10000 times 12000000000000000 and higher numbers.

Julia does not automatically promote to BigInt so this exceeds the maximum value for a 64-bit integer and thus wraps around. Please see the linked discussion.

**Comment by jfdsac** [comment]
Got it.  Thanks all, and thanks Milan for the tip. Since I was using 10000 as one of the factors, I generated four wraps (as I saw as errors) before the next higher size of Integers kicked in.
