### ISSUE TITLE
Cant make gc() clear unreferenced variables

### ISSUE THREAD

**Issue by TCMiranda** [JuliaLang/julia#10807]
Hello,

I have a task of reading one really large csv file, which it's not possible to load completely on memory. That's why i am trying to process sequentially, but my memory is growing uncontrolled.

I would appreciate any help to realise where am I letting it grows, and why isn't gc() removing each line from the memory as i'm not keeping some reference to it.

Here it is (inside a function that recieves "data" and "sock"):

```julia
function storeLine(line)
    @async write(sock, "\\c3a:store|" * line)
    parsed += 1
end

function parseLine(line)
    @async Parser.parseLine(line, storeLine)
    (!eof(data) ? (@async readLine()) : (finish())
end

function readLine()
    @async LoadCsv.readLine(data, parseLine)
end
 
@async readLine()
 ```

Best regards,
Tiago

**Comment by JeffBezanson** [comment]
Thanks for the report. Could you come up with a runnable example that exhibits the problem? For example, substitute generating random data for reading actual data. It will be much easier to address this if we have a script we can simply run with `julia script.jl` and see the memory growth.

**Comment by TCMiranda** [comment]
No problem!

Actually, i'm using public data, so i added pushed a small example of the actual code which i'm having trouble, with a small chunk of the data file.

https://github.com/TCMiranda/JuliaMemExample

Thanks in advance.
Tiago

**Comment by TCMiranda** [comment]
@JeffBezanson sorry for bothering! But, could you help me understand if there is a problem with garbage collector indeed, or with my code? And maybe give some way to try fixing it?

Thank you!

**Comment by JeffBezanson** [comment]
Apologies; we're very busy and can't always get to every issue quickly. If this is urgent (e.g. a production issue) please email me.

**Comment by TCMiranda** [comment]
No problem! Thanks for the answer.
This is for a college project, no rush.. Thanks!
