### ISSUE TITLE
binary_minheap breaks system

### ISSUE THREAD

**Issue by DenisKolodin** [JuliaLang/julia#10812]
Julia, JUNO and OS breaks every when I tried to call:

    using DataStructures
    heap = binary_minheap(Array{Int, Any})

**Comment by tkelman** [comment]
Appears to be a memory leak in the show method for that type, and only on 0.3 - the constructor works okay if you add a semicolon to suppress output.

**Comment by DenisKolodin** [comment]
Without show it works. Thank you!

**Comment by tkelman** [comment]
Looks like it's certainly a bug though, not sure exactly where, or what specific change between 0.3 and 0.4 was responsible for fixing it.

**Comment by JeffBezanson** [comment]
Turns out this was triggering a codegen assertion failure (when run in debug mode) due to the unorthodox array type `Array{Int, Any}`. The second parameter should be an integer or left unspecialized normally.
