### ISSUE TITLE
String containing dollar sign throws inexplicable error

### ISSUE THREAD

**Issue by gideonite** [JuliaLang/julia#10816]
From the julia REPL:

```julia
julia> "$"
ERROR: syntax: invalid interpolation syntax: """
```

but if I do this:

```julia
julia> "\$"
```

No problem.

I think that this is because of Julia's nifty string syntax but it'd be nice to have a better error. This came up for me while I was using Julia to work on some suffix trees.

**Comment by mbauman** [comment]
Would simply inserting a `$` symbol into the error message fix this issue?

For example:

```
julia> "123 $"
ERROR: syntax: invalid interpolation syntax: "$""

julia> "$) abc"
ERROR: syntax: invalid interpolation syntax: "$)"

julia> "qwer $1 asdf"
ERROR: syntax: invalid interpolation syntax: "$1"
```

**Comment by stevengj** [comment]
How about `ERROR: syntax: $ in strings must be escaped as \$ or used for interpolation`

**Comment by gideonite** [comment]
I would up going with @mbauman's suggestion.

**Comment by ptoche** [comment]
This improvement in the error message is very useful!
