### ISSUE TITLE
Better Dates format string documentation needed

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10819]
It's really hard to figure out how to parse dates. For example:

- It's not possible to read the user manual and deduce that `eee uuu dd HH:MM:ss zzzzz yyyy` can be used as a format string to parse a date string like "Tue Apr 01 01:56:23 +0000 2014".
  - The various magic characters are incompletely documented.
  - The documentation does not state explicitly that unmatched magic characters are ignored.

cc: @quinnj

**Comment by elextr** [comment]
The characters are documented here http://docs.julialang.org/en/latest/stdlib/dates/ (well a ways down that page, hint, paragraph links would be good :)

Is it intended that unmatched format chars are ignored?  C's `strptime()` for example stops on a match failure.
