### ISSUE TITLE
`Base.squeeze`: bug for sparse matrix

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#10813]
```julia
julia> squeeze(sparse([1],[1],[1],1,3),1)
3x3 sparse matrix with 1 Int64 entries:
	[1, 1]  =  1
```
Note dimensions. Cf
```julia
julia> squeeze(convert(Matrix,sparse([1],[1],[1],1,3)),1)
3-element Array{Int64,1}:
 1
 0
 0
```
Version `v"0.4.0-dev+4234"`.

**Comment by pao** [comment]
I suppose the last dimension needs to be special cased for sparse (since it can't be eliminated--we don't have sparse vectors yet, right?)

**Comment by tkelman** [comment]
Not really, but I think we should. #8718

**Comment by tpapp** [comment]
In the meantime, until sparse vectors are available, either 

1. converting to `Vector` or 
2. throwing an error

would be preferable to returning a nonsensical result (like above). I would prefer a `Vector`.

**Comment by ViralBShah** [comment]
I'll make it throw an error.

**Comment by ViralBShah** [comment]
Backported as well.

**Comment by tkelman** [comment]
I don't think that needed to be backported, especially not instantly and with zero discussion. It looks like the problem is actually in reshape anyway.

**Comment by tkelman** [comment]
What's the official policy on timeline for removal of deprecated definitions? I think the `spzeros(m)` and `spzeros(Tv, m)` fallbacks from c3e33297890ae101ca67860c8b0c684b2715de2b will need to be removed soonish. Either when we get proper sparse vectors, or maybe before?

**Comment by ViralBShah** [comment]
Why not just deprecate them along with everything else?

**Comment by tkelman** [comment]
They already are deprecated. I'm asking when can they be removed.

**Comment by ViralBShah** [comment]
Sorry, I did mean why not follow removal policy during release, just as with other deprecations? IIRC, If something is deprecated in the current release cycle, say 0.4-dev it gets removed at the next release, the 0.5 release.

**Comment by tkelman** [comment]
I think they were deprecated during 0.3-pre.

Whatever the resolution here is, I really dislike backporting anything before it's at least had a chance to run through PkgEvaluator on master.

**Comment by tkelman** [comment]
Since the `spzeros(m)` deprecation was removed this could probably be fixed on master now.
