### ISSUE TITLE
Error using "dlopen" for MATLAB.jl (v 0.4 vs. 0.3 issue?)

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLang/julia#10823]
Hi all, 

I am new Julia user and I was trying to load the `MATLAB.jl` module and got the following error:

```
ERROR: LoadError: LoadError: UndefVarError: RTLD_GLOBAL not defined
 in load_libmx at /Users/arora/.julia/v0.4/MATLAB/src/mxbase.jl:76
 in include at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include_from_node1 at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in include_from_node1 at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in reload_path at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in _require at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
 in require at /Users/arora/CODES/Julia_source/julia/usr/lib/julia/sys.dylib
while loading /Users/arora/.julia/v0.4/MATLAB/src/mxbase.jl, in expression starting on line 84
while loading /Users/arora/.julia/v0.4/MATLAB/src/MATLAB.jl, in expression starting on line 34
```

I was able to track this problem down to RTLD_GLOBAL | RTLD_LAZY parameters in calls to the `dlopen` function which loads Matlab's libraries.  The following call fails (with the above error):

`libmx = dlopen(path_to_matlab_library, RTLD_GLOBAL | RTLD_LAZY)`

and I had to remove and `RTLD_GLOBAL | RTLD_LAZY` replace this command by

`libmx = dlopen(path_to_matlab_library)` (which defaults to `RTLD_GLOBAL` and `RTLD_LAZY`)

...similarly for other `dlopen` function calls in `mxbase.jl` . After I did that, the module seems to load fine. 

So I was wondering, as I am using Juli 0.4 .. .has something changed since v 0.3 which lead to this issue ?

thanks.

**Comment by simonster** [comment]
Fixed in JuliaLang/MATLAB.jl@5e673eeef9941a8cde0e2aa092077e23e00278c9
