### ISSUE TITLE
Build failing on OSX 10.10.3?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10822]
Latest julia (pulled as of 10 mins ago) yields this:

```
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
In file included from src/libuwind.cxx:33:
In file included from /Users/seth/dev/julia/julia/deps/libosxunwind-0.0.1/src/UnwindCursor.hpp:41:
In file included from /Users/seth/dev/julia/julia/deps/libosxunwind-0.0.1/src/DwarfInstructions.hpp:36:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
make[2]: *** [src/libuwind.cxx.o] Error 1
make[1]: *** [libosxunwind-0.0.1/libosxunwind.dylib] Error 2
make: *** [julia-deps] Error 2
```

Any ideas?

**Comment by tkelman** [comment]
Do you need to run `xcode-select --install` after upgrading osx?

**Comment by sbromberger** [comment]
Nope - just for kicks, I tried it:

```
seth@schroeder:~/dev/julia/julia$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

Nothing listed in software updates.

**Comment by sbromberger** [comment]
Going to reinstall commandline tools per http://stackoverflow.com/questions/29552326/eclipse-cdt-could-not-find-include-debug

**Comment by sbromberger** [comment]
Not a problem specific to Julia: http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by sbromberger** [comment]
This appears to fix it (from that SO link above):

`echo '#define _LIBCPP_ASSERT(x, m) ((void)0)' | sudo tee -a /Library/Developer/CommandLineTools/usr/include/c++/v1/__debug > /dev/null`

**Comment by tkelman** [comment]
Apple sure likes testing their stuff before releasing it, don't they... /s

**Comment by sbromberger** [comment]
Interestingly enough, I got a software update notification for command line tools today - but after I installed it things still looked the same.

**Comment by lindahua** [comment]
I encountered the same problem yesterday and fixed it by downgrading the Xcode command line tools to 10.2 ...

**Comment by adamstac** [comment]
Thanks for that fix @sbromberger, worked for me.

**Comment by eschulz2** [comment]
Thanks @sbromberger

**Comment by delafont** [comment]
When you update the OS you need to reopen once some programs that got updated to "allow" them (a popup window comes the first time you open it). If you do it with Xcode then suddenly command-line tools work fine again. At least that fixed all command-line tools related issues for me.

**Comment by sbromberger** [comment]
@delafont check to see whether you have `/Library/Developer/CommandLineTools/usr/include/c++/v1/__debug` on your system?

**Comment by delafont** [comment]
I don't have it. I wasn't trying to build Julia though, just lost command-line tools just after the update.

**Comment by bmishkin** [comment]
another package which had been failing (rubygem eventmachine) build was fixed by the latest command line tools update (6.3.1). might be the same case here.

**Comment by malcolmgreaves** [comment]
Thanks @sbromberger ! Same problem in a completely unrelated project. I appreciate you posting this information.
