### ISSUE TITLE
Docs search broken

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#10831]
Just in case somebody is wondering why this is, the reason seems to be with readthedocs: https://github.com/rtfd/readthedocs.org/issues/1222

**Comment by jiahao** [comment]
Is this different from #7134?

**Comment by rened** [comment]
I am sorry, I should have been more specific - the search does not work at all, just sits there saying "Searching...". I tried a few other sites relying on readthedocs, there the search doesn't work either.

**Comment by rened** [comment]
https://github.com/rtfd/readthedocs.org/issues/1222#issuecomment-94021912 says the a fix was deployed - I guess the Julia docs need to be rebuilt / published for this to take effect?

**Comment by rened** [comment]
works again - if it doesn't make sure to reload the page, some old code seems be being cached
