### ISSUE TITLE
disasm compilation error against llvm-svn

### ISSUE THREAD

**Issue by sebastiang** [JuliaLang/julia#10830]
CC src/disasm.o
    disasm.cpp:370:54: error: non-const lvalue reference to type 'llvm::formatted_raw_ostream' cannot bind to a
          temporary of type 'typename remove_reference<unique_ptr<formatted_raw_ostream,
          default_delete<formatted_raw_ostream> > &>::type' (aka 'std::__1::unique_ptr<llvm::formatted_raw_ostream,
          std::__1::default_delete<llvm::formatted_raw_ostream> >')
        Streamer.reset(TheTarget->createAsmStreamer(Ctx, std::move(ustream), /*asmverbose*/true,
                                                         ^~~~~~~~~~~~~~~~~~
    julia/usr/include/llvm/Support/TargetRegistry.h:472:74: note: passing argument to
          parameter 'OS' here
        MCStreamer *createAsmStreamer(MCContext &Ctx, formatted_raw_ostream &OS,
                                                                             ^
    1 error generated.
    make[1]: *** [disasm.o] Error 1
    make: *** [julia-src-release] Error 2

**Comment by ihnorton** [comment]
Need to update your llvm build.

**Comment by ihnorton** [comment]
see https://github.com/JuliaLang/julia/pull/10796

**Comment by sebastiang** [comment]
Might be missing something, but after `make -C deps update-llvm` (to `ea604d92efcbf53fd0909da562d3db7860ff6199`) and `git pull` on the julia branch (to `041f223`), I still get it.

**Comment by ihnorton** [comment]
`update-llvm` doesn't always trigger a rebuild. try running `make` in `deps/llvm-svn/build_Release+Asserts` (or whatever you've set).

**Comment by ihnorton** [comment]
You might also need to run `make install`.

**Comment by ihnorton** [comment]
(we should rework the targets a little bit to make `update-llvm` more useful. pull requests welcome)

**Comment by sebastiang** [comment]
You learn something new every day. Thanks for your patience. I'll see what works.

**Comment by sebastiang** [comment]
`make` LLVM sure takes a while! Anyway, did that, then a `make install`, then back up to my julia root where a `make cleanall` followed by a `make` fails on a different error. I feel like I'm chasing my tail. Is there a guide to managing dependencies while building Julia from source?

    codegen.cpp:475:37: error: non-const lvalue reference to type 'llvm::raw_pwrite_stream' cannot bind to a value of
          unrelated type 'llvm::formatted_raw_ostream'
        if (TM->addPassesToEmitFile(PM, FOS, TargetMachine::CGFT_ObjectFile, false)) {
                                        ^~~
    /Users/sebastian/dev/julia-cxx/usr/include/llvm/Target/TargetMachine.h:211:74: note: passing argument to parameter
          here
      virtual bool addPassesToEmitFile(PassManagerBase &, raw_pwrite_stream &,
                                                                             ^
    1 error generated.
    make[1]: *** [codegen.o] Error 1

**Comment by ihnorton** [comment]
> I feel like I'm chasing my tail. Is there a guide to managing dependencies while building Julia from source?

Not really, unfortunately. I think there are only a few people who build against llvm-svn on a regular basis (Keno, me, and a few other folks like you who are testing Cxx). The Makefiles could still use some improvement, obviously. I guess the issue is that the headers have not been updated properly. You could also try:
- removing `usr/lib/libLLVM-3.7svn.so` (or dylib) which should force a reinstall driven by Julia's Makefile (might make a difference).
- `touch deps/llvm-svn/configure`. This will probably force a reconfigure and full rebuild.

**Comment by sebastiang** [comment]
Well, I nixed the whole source tree, `git pull`ed it completely fresh, and `make` still gives me this error. I think it's real.

    CC src/codegen.o
    codegen.cpp:475:37: error: non-const lvalue reference to type 'llvm::raw_pwrite_stream' cannot bind to a value of unrelated type 'llvm::formatted_raw_ostream'
        if (TM->addPassesToEmitFile(PM, FOS, TargetMachine::CGFT_ObjectFile, false)) {
                                        ^~~
    /Users/sebastian/dev/julia-cxx/usr/include/llvm/Target/TargetMachine.h:211:74: note: passing argument to parameter here
      virtual bool addPassesToEmitFile(PassManagerBase &, raw_pwrite_stream &,
                                                                             ^
    1 error generated.
    make[1]: *** [codegen.o] Error 1

**Comment by ihnorton** [comment]
Yes that is real. PR welcome or I can fix it in a few hours.

**Comment by sebastiang** [comment]
LLVM internals are little beyond my ken, I'm afraid. I tried just using the `raw_fd_ostream` instead of the `formatted_raw_ostream` that it didn't like, and it compiled, but it failed several tests during `make test`. Perhaps that's the state of the LLVM support at the moment anyway at the moment. I notice that most of the tests are substantially slower than in the mainline v0.4 build, so I suppose there's lots more LLVM tweaking to do!

**Comment by ihnorton** [comment]
Your fix might actually be correct -- haven't looked at how the API changed
yet. I'm working on making the `update-llvm` target better to save time in
the future.

I would not expect all of the tests to pass (see the headaches in 10394 as
we try to get 3.6.0 going).

**Comment by sebastiang** [comment]
Shall I send in the PR?
On April 15, 2015 at 10:11:11 PM, Isaiah (notifications@github.com) wrote:

Your fix might actually be correct -- haven't looked at how the API changed
yet. I'm working on making the `update-llvm` target better to save time in
the future.

I would not expect all of the tests to pass (see the headaches in 10394 as
we try to get 3.6.0 going).

**Comment by sebastiang** [comment]
I think it is the right fix: see https://github.com/llvm-mirror/llvm/commit/427c073035b4c64742f3b784a1b6b6ecb41cd601

**Comment by ihnorton** [comment]
PR it up! If I understand right, you changed FOS->OS? That looks correct.
But note that it should be inside `ifdef LLVM37` and keep the old signature
in the else block.

**Comment by sebastiang** [comment]
take a look.
