### ISSUE TITLE
export Base.with_env?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#10836]
There is a `Base.with_env` function to temporarily set an environment variable.  This is a useful thing to do when running one or more shell commands; any reason not to export it?

**Comment by ihnorton** [comment]
https://github.com/JuliaLang/julia/issues/4531#issuecomment-26394192

**Comment by stevengj** [comment]
@JeffBezanson, in #4531 you voted "no" on exporting `with_env` because it was "just a new feature".  Could you elaborate?

I just used `Base.with_env` in stevengj/PyCall.jl@1b591790074e5435942ea8b8649a8c45169b4b01, for example; I dislike relying on unexported functions, but I dislike rewriting code even more.

**Comment by IainNZ** [comment]
Oh man I wish I'd known about this

**Comment by StefanKarpinski** [comment]
I think we should finalize the interface and then export it.

**Comment by tkelman** [comment]
That does look useful, and like it could be cleaner than the `ENV2 = copy(ENV); ENV2[key] = val; run(setenv(`foo`, ENV2))` pattern I find myself doing fairly often. Would need to be documented obviously.

**Comment by stevengj** [comment]
How about making the interface `withenv("FOO"=>"bar", "BAZ"=>"bing", ...)`, i.e. `Pair{String,String}...` args.  This way they are as convenient as keywords for setting multiple vars, but can be dynamically generated.

**Comment by StefanKarpinski** [comment]
Seems reasonable, @stevengj. Let's make it that.

**Comment by stevengj** [comment]
This almost works, except for the abovementioned bug:
```julia
function with_env{T<:AbstractString}(f::Function, keyvals::Pair{T}...)
    old = Dict{AbstractString,Any}()
    for (key,val) in keyvals
        k = string(key)
        old[k] = get(ENV,k,nothing)
        val != nothing ? (ENV[k]=val) : _unsetenv(k)
    end
    try f()
    finally
        for (key,val) in old
            val != nothing ? (ENV[key]=val) : _unsetenv(key)
        end
    catch
        rethrow()
    end
end
```

**Comment by JeffBezanson** [comment]
Ok.

I think `catch rethrow()` is redundant.
