### ISSUE TITLE
make install does not support USE_LLVM_SHLIB=1

### ISSUE THREAD

**Issue by sebastiang** [JuliaLang/julia#10849]
Against LLVM latest, after a `make`, `julia` executes fine where it was built, but after an apparently successful `make install`, it does not launch from its target directory

    dyld: Library not loaded: @rpath/libLLVM-3.7svn.dylib
      Referenced from: /Users/sebastian/dev/julia-v0.4-cxx/bin/julia
      Reason: image not found
    Trace/BPT trap: 5

Interestingly, the relevant libraries are only in the build directory, never copied to the install directory. However this seems to be the way it works in the mainline build as well. I'm not sure how to debug this particular error.

Note, doing this in aid of trying to work with Cxx.jl, so am using all the `Make.user` settings recommended there. Could be an interplay with other build options.

    override LLDB_VER=master
    override LLVM_VER=svn
    override LLVM_ASSERTIONS=1
    override BUILD_LLVM_CLANG=1
    override BUILD_LLDB=1
    override USE_LLVM_SHLIB=1
    override LLDB_DISABLE_PYTHON=1

**Comment by ihnorton** [comment]
I don't know much about OS X, but I think `otool` is your friend here. See for example http://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-loaded.

**Comment by vtjnash** [comment]
the `make install` target does not support `USE_LLVM_SHLIB=1`

**Comment by tkelman** [comment]
Is that a new problem since the usr-staging change, or has it always been that way?

**Comment by vtjnash** [comment]
it's always been that way – we don't install files that aren't used

the usr-staging change didn't actually change much of anything. sometime in the future I'll go back and do more interesting (and breaking) stuff with that.

**Comment by tkelman** [comment]
> we don't install files that aren't used

The llvm shared library is used and should be installed when `USE_LLVM_SHLIB = 1`. Would that be enough to fix this?

**Comment by vtjnash** [comment]
yes, that's a valid case and should  fix this

**Comment by tkelman** [comment]
closed by #12004
