### ISSUE TITLE
OSX Build Failure on Rmath

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#10846]
Am I missing an update or something? For context, I *haven't* updated Xcode or anything else lately.
OSX Yosemite

```julia
ERROR: sha512 checksum failure on Rmath-julia-0.1.tar.gz, should be:
      1dd94eca05bc06c3f33e8be5087d3b1742d01c8b38588e0fa79b8f6b9998760b
      ca21bee1b65873825c4dde2d994a8271166bc21f670a34810fa9db598473a887
  But `shasum -a 512 Rmath-julia-0.1.tar.gz | awk '{ print $1; }'` results in:
      faae008bf12afa4426329a122887846eacc3ec7436fe04192b5a24b64d43246d
      cdd4fd62676a5c998a5f9d1645c9933716ac50d3a1398afae09ce2c895064d9e
  This can happen due to bad downloads or network proxies, please check your
  network proxy/firewall settings and delete deps/Rmath-julia-0.1.tar.gz
  to force a redownload when you are ready
===============================================================================
make[1]: *** [Rmath-julia-0.1/src/libRmath-julia.dylib] Error 2
make: *** [julia-deps] Error 2
jq-mbp:julia jacobquinn$ 

```

**Comment by ihnorton** [comment]
I saw this, and moved past it by removing the .tar.gz file. Something to do with the usr-staging change.

**Comment by quinnj** [comment]
Cool. That seemed to solve it. Anything else to do here?

**Comment by tkelman** [comment]
`make -C deps distclean-Rmath-julia` is another quick way of fixing this. It's actually that @vtjnash changed from `/archive/` links to `/tarball/` which have different checksums. Someone should diff the contents of the old file vs the new one, hopefully the only difference is the folder name it extracts to.

**Comment by quinnj** [comment]
Cool. Well I'll close for now since there's a good bread crumb if people have similar problems. I think @jiahao had a script once that automatically did `make -C deps distclean` for all the deps in a `make clean_really_all` or something.

**Comment by tkelman** [comment]
That's already in the makefiles `make -C deps distcleanall`, or `make distcleanall` at the top level which also cleans out `doc` and `usr`. LLVM and openblas can be kind of painful to distclean for problems that come from other smaller deps though...

**Comment by quinnj** [comment]
Ah, good to know, thanks @tkelman
