### ISSUE TITLE
inconsistent handling of empty varargs

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#10853]
If I define
```julia
foo{T<:Integer}(args::Pair{T}...) = length(args)
bar(args::Pair...) = length(args)
```
then `bar()` returns `0` but `foo()` throws `MethodError: foo has no method matching foo()`.  (Same in both 0.4 and 0.3, once I define `Pair` in the latter.)

Seems like a bug?

(I noticed this when trying to implement #10836.)

**Comment by JeffBezanson** [comment]
There is an extra dispatch rule that says it must be possible to determine a value of the static parameter `T`. #8974 could potentially help with this, by allowing dispatch on `UnionAll` types without necessarily introducing static parameters.

**Comment by stevengj** [comment]
That's reasonable, I suppose, since the function body may depend on `T` I guess there's no way in general to allow empty args.
