### ISSUE TITLE
Julia Licensing question

### ISSUE THREAD

**Issue by iceblue25** [JuliaLang/julia#10852]
I read that Julia has MIT license however some modules like the standard lib fft function uses GPL license. Does that mean any commercial project developed in Julia which uses such functions need to be released as GPL?

Does Julia compile by default the standard library and all GPL related code?

**Comment by StefanKarpinski** [comment]
Please use mailing lists for questions. There is an ongoing discussion of this very issue on julia-users:

https://groups.google.com/forum/#!topic/julia-users/v4OjEK7azBs

**Comment by tkelman** [comment]
The short answers to your questions are 1. yes (I think) and 2. yes, but it doesn't always have to be that way.
