### ISSUE TITLE
Undefvar error for "..." inside a quote block

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10857]
After the recent tuple changes, we need to specify
    `:( DArray((I::$(esc(Tuple{UnitRange{Int}, ...})))->($ex), .....`

in a macro definition instead of just

`:( DArray((I::Tuple{UnitRange{Int}, ...})->($ex), .....`

as would be expected.

**Comment by JeffBezanson** [comment]
Can you give a more complete example? I don't see what the problem is.

**Comment by amitmurthy** [comment]
Code in DistributedArrays.jl prior to tuple changes:

https://github.com/JuliaParallel/DistributedArrays.jl/blob/2aad0cac9986a02aba49b9bae6b0f92cf7a7ed91/src/DistributedArrays.jl#L94-L95

Current code that works after tuple changes:

https://github.com/JuliaParallel/DistributedArrays.jl/blob/cf7702a19c9cf1001145301dc89f41257d1b8e3f/src/DistributedArrays.jl#L94-L95

I would have expected just

```
 return :( DArray((I::Tuple{UnitRange{Int}, ...})->($ex),
                tuple($(map(r->:(length($r)), ranges)...))) )
```

to work, but `...` was resulting in an UndefVarError if not escaped.

**Comment by yuyichao** [comment]
Shouldn't it be `Tuple{Vararg{UnitRange{Int}}}` as mentioned in the [julia-dev email](https://groups.google.com/forum/#!topic/julia-dev/uQ1DsGGSrD0)?

**Comment by amitmurthy** [comment]
Yes, that works. I just followed the syntax used in other places in Base.
