### ISSUE TITLE
Unexport thin wrapper functions around libuv?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10854]
The functions

- `start_timer`
- `stop_timer`
- `start_reading`
- `stop_reading`
- `start_watching`

are essentially thin wrappers around libuv functions of similar names and probably should be unexported.

1.  The last three have no documentation.
2. The counterpart to `start_watching`, `stop_watching`, is unexported.
3. `start_timer` is only called by `sleep` and `timedwait`.
4. `stop_timer` is only called by `timedwait`.
5. Neither `start_timer` nor `stop_timer` validate their arguments, leading to possible weird errors like in #10847

**Comment by JeffBezanson** [comment]
Yes please. See #1925

**Comment by tkelman** [comment]
+1, not worth exporting these

**Comment by jiahao** [comment]
Closed by #10885
