### ISSUE TITLE
Exponentials to a fraction not defined over negative numbers. 

### ISSUE THREAD

**Issue by npfrazier** [JuliaLang/julia#10879]
e.g. (-4)^(1/3) --> ERROR: DomainError

I checked with v0.3.5 and v0.4.0. Appear to be defined from [0,\infty) just not over (-\infty,0).

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
Version 0.3.5 (2015-01-08 22:33 UTC)
x86_64-w64-mingw32

In  [2]: (-4)^(1/3)

Out [2]: ERROR: DomainError
while loading In[2], in expression starting on line 1

 in ^ at promotion.jl:162 (repeats 2 times)

In  [3]: (-4)^(1//3)

Out [3]: ERROR: DomainError
while loading In[3], in expression starting on line 1

 in ^ at rational.jl:177 (repeats 2 times)

**Comment by mbauman** [comment]
That's the correct and expected behavior. See the [Frequently asked Questions](http://docs.julialang.org/en/latest/manual/faq/#why-does-julia-give-a-domainerror-for-certain-seemingly-sensible-operations) about Domain Errors.

You must "opt-in" to a complex result by using a complex base:

```julia
julia> complex(-4)^(1/3)
0.7937005259840999 + 1.3747296369986024im
```
