### ISSUE TITLE
Document/consistent handling of macro and escape (unescape?)

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10887]
From the document, it is probably clear enough why are macros and `esc` useful. However, IMHO, it is not quite clear when it is necessary to use `esc`. It's true that most of the cases it's quite intuitive but I could not find anywhere a short summary of the rules that cover all cases.

There also doesn't seem to be a way to "unescape".

The script that shows my confusion (and why I think "unescape" is necessary) is here,
```julia
module A
macro test_mac()
    quote
        function f(v::T1)
            v::T1
        end
        function Module.func1(v::T1)
            v::T1
        end
        @inline function Module.func2(v::T1)
            v::T1
        end
        function f{T2}(v::T2)
            v::T2
        end
        function Module.func1{T2}(v::T2)
            v::T2
        end
        @inline function Module.func2{T2}(v::T2)
            v::T2
        end
    end
end
end

println(macroexpand(:(A.@test_mac)))
```

The output is
```julia
begin  # /home/yuyichao/tmp/macro_escape.jl, line 6:
    function #1#f(#2#v::A.T1) # /home/yuyichao/tmp/macro_escape.jl, line 7:
        #2#v::A.T1
    end # line 9:
    function A.Module.func1(#3#v::A.T1) # /home/yuyichao/tmp/macro_escape.jl, line 10:
        #3#v::A.T1
    end # line 12:
    function A.Module.func2(A.v::A.T1)
        $(Expr(:meta, :inline)) # /home/yuyichao/tmp/macro_escape.jl, line 13:
        A.v::A.T1
    end # line 15:
    function #1#f{#5#T2}(#4#v::#5#T2) # /home/yuyichao/tmp/macro_escape.jl, line 16:
        #4#v::#5#T2
    end # line 18:
    function A.Module.func1{#7#T2}(#6#v::#7#T2) # /home/yuyichao/tmp/macro_escape.jl, line 19:
        #6#v::#7#T2
    end # line 21:
    function A.Module.func2{A.T2}(A.v::A.T2)
        $(Expr(:meta, :inline)) # /home/yuyichao/tmp/macro_escape.jl, line 22:
        A.v::A.T2
    end
end
```

It would be nice to document why are `f`, `v`, `T2` mangled but not `T1` and `Module.func1`. Also, is there a way to make the inline function definition works as expected (unescape?)?

**Comment by vtjnash** [comment]
related: https://github.com/JuliaLang/julia/pull/6910

**Comment by toivoh** [comment]
As it says in the manual under hygiene in the metaprogramming section, symbols found in the AST returned from a macro are classified into two categories: local and global. Local ones are those that are assigned in some way in the AST, and are replaced by gensyms. Others are considered global and are (set to be) looked up in the module that defines the macro. This explains the difference that you see. 

The case with `@online

**Comment by toivoh** [comment]
The case with `@inline` seems like a hygiene bug, or more probably a shortcoming of the current hygiene system. Since Hygiene has to run before `@inline` is expanded, it cannot see how the symbols inside it should be classified. Here #6910 should hopefully help.

The manual way to unescape is to create gensyms yourself and interpolate into the AST.

**Comment by toivoh** [comment]
Forgot to say, `Module.func1` can't be turned into a gensym because it's not a symbol. `Module` itself is not assigned so it is regarded as global, and `func1` is not a freestanding identifier but the argument of the dot operator (it's always looked up in the left argument and not in the local scope), so it's not eligible for hygiene at all.

**Comment by yuyichao** [comment]
I guess I understand the difference now after testing for a few more examples.

The "manual way" to unescape should work when I want to avoid name clashing. However, what if what I want to do is to extend a function in current scope. E.g.

```julia
julia> module A
       macro B()
       expr = quote
       function C()
       end
       end
       return esc(expr)
       end
       end

julia> macroexpand(:(@A.B))
quote  # none, line 4:
    function C()
    end
end
```

Should I replace `C` by `A.C` and assume `A` is always available in the module the macro is called? (Is this a grantee)

**Comment by toivoh** [comment]
I'm not sure that I understand. Do you always want to extend function `C` in the module `A` above, or do you want to extend the function `C` in the scope of the caller of `@B`? As you have written it, it seems like it will do the latter.

**Comment by yuyichao** [comment]
I actually would like to do the former.

The `esc` is meant to come from some other necessary logic that require escape and I use `C` instead of `A.C` because I'm not sure if `A.C` is the correct way to do this either.

**Comment by toivoh** [comment]
And if you change `C` to `A.C` I think it should do the former.

**Comment by yuyichao** [comment]
Does it mean that `A` is always available in the scope `@B` might be called?

**Comment by toivoh** [comment]
Btw the other way to manually escape something is to interpolate the quoted value of whatever you want to put there. This is how the hygenization works for symbols deemed to be global.

**Comment by toivoh** [comment]
All that said, maybe it could be explained better in the manual. Now that you understand it a bit better, do you have an idea of what could be changed?

**Comment by yuyichao** [comment]
I hope you are not asking for a PR to the document since I'm certainly not qualified for that =P.

IMHO, here's something that could have helped me to understand this better.
1. It was not so clear to me why defining a function `A` is local but "defining" a function `B.C` is global, especially since defining another macro in the macro returned value seems to follow yet a different rule. I cannot really tell why now because as long as I understand that, it is indeed hard to imagine how I could get it wrong before....
2. A few other examples for local vs global might be helpful too.
3. The document mentioned "global variables are resolved within the macro definition environment" but didn't mention how. (Now I remember that when I checked the expanded AST last time, I saw the module object itself is inserted in the AST.) This might not be very useful for writing a macro but can make it less mysterious, especially since the macro itself is mysterious enough for anyone that doesn't have a lisp background....
The printing from `macroexpand` here is also confusing since it cannot show the difference between a symbol and a module. (Maybe color code non-symbol/symbol when printing a AST?)
4. Maybe mention how to deal with nested macros (`@inline`, or whatever....)
5. An unrelated stuff. When I was working on #9642, I saw that inserting values (functions?) into AST can cause compile error. However, this seems to be how the macro system works (inserting modules) to resolve values in the correct scope. This probably doesn't matter for current modules since they are compiles for a single session only but would this be OK to do (either automatically by the macro system or manually in order to "unescape" sth) when static module compilation is added? (I thought it was one of the 0.4 milestone a few month ago but couldn't find it anymore.) What about inserting other kind of values into AST?

**Comment by toivoh** [comment]
Sorry, just realized that the `A.C` thing only works if you don't escape that part of the AST. `A` can not be expected to be available by name in any caller of `@B`, but hygenization would take `A` and look it up as a global. 

In general, you should be able to interpolate any kind of value into the AST, provided that you quote by putting it in a `QuoteNode`, but there may still be a few syntactic positions where a quoted value is not handled correctly. 

I don't know enough about static compilation to say how this would interact with it, @vtjnash?

You can see the difference between symbols and interpolated values if you print the AST using other methods, eg `Base.Meta.show_sexpr`.

I'm not asking for a PR unless you want to make one :) just wanted to bring attention back to the topic of improving the docs.

**Comment by yuyichao** [comment]
> In general, you should be able to interpolate any kind of value into the AST, provided that you quote by putting it in a QuoteNode, but there may still be a few syntactic positions where a quoted value is not handled correctly.

Do you mean I should use `$(QuoteNode(A))` (or `$(QuoteNode(:A))` ?) instead of `$A`?

Actually this reminds me that `QuoteNode` (and maybe what kinds of values are safe/recommanded to be interpolated in the AST) is also not documented very well (and I still don't feel like understand it). From searching the doc, it is mentioned only once `Note that this form introduces QuoteNode elements to the expression tree, which must be considered when directly manipulating an expression tree generated from quote blocks.`

Or is this intentional because it is considered part of the "unstable" AST?

**Comment by vtjnash** [comment]
a QuoteNode allows putting a literal Symbol into the AST (rather than a variable). It can also be used to put literal Expr nodes into the AST. It's safe to put anything in the AST. The internal passes will only put in simple objects, such as Symbols, Exprs, numbers, Strings, and QuoteNodes. But macros can put in anything, and those objects will be treated as literal values.

static compilation doesn't really care what you put in the AST any differently from regular usage.

**Comment by toivoh** [comment]
So if you put a quoted value into the AST it will be serialized for the
static compilation, and then deserialized when the code precompiled code is
loaded?

**Comment by yuyichao** [comment]
So what is the difference between the following cases and which one should I use for "unescape" a symbol (or to make a escaped symbol resolve in the module where the macro is defined (`A`)?)

```
julia> module A
       macro B()
       expr = :($A, $(:A), $(QuoteNode(:A)), $(QuoteNode(A)))
       :(($expr, $(esc(expr))))
       end
       end

julia> A.@B
((A,A,:A,A),(A,A,:A,A))

julia> macroexpand(:(@A.B))
:(((A,A.A,:A,$(QuoteNode(A))),(A,A,:A,$(QuoteNode(A)))))

julia> Meta.show_sexpr(macroexpand(:(@A.B)))
(:tuple, (:tuple, A, (:., A, (:quote, #QuoteNode
        :A
      )), (:quote, #QuoteNode
      :A
    ), (:quote, #QuoteNode
      A
    )), (:tuple, A, :A, (:quote, #QuoteNode
      :A
    ), (:quote, #QuoteNode
      A
    )))
```

I guess this discussion might fit better on the mailing list and I can post it there (julia-users?) if you prefer.

**Comment by yuyichao** [comment]
@vtjnash So is your comment [here](https://github.com/JuliaLang/julia/pull/9642#discussion_r22565104) only valid for bootstraping but is not a problem for the (yet to come?) static module compilation.

**Comment by vtjnash** [comment]
> So if you put a quoted value into the AST it will be serialized for the
static compilation, and then deserialized when the code precompiled code is
loaded?

the serialization should be relatively transparent to the user.

> So is your comment here only valid for bootstraping but is not a problem for the (yet to come?) static module compilation

bootstrapping != compilation. they are related (because they often happen at the same time), but the user should never need to care about or create `TopNode`s, unless they are modifying the parser or inference code.

**Comment by JeffBezanson** [comment]
The case with `@inline` is fixed now. Plz reopen if I'm missing something else here.
