### ISSUE TITLE
Need better instructions for setting up ssh-agent for contrubuting 

### ISSUE THREAD

**Issue by amellnik** [JuliaLang/julia#10892]
At [the Packages help page](http://julia.readthedocs.org/en/latest/manual/packages/#man-pkg-dev-setup) it says "If you encounter an error, make sure you’ve set up your SSH keys" and "You should ... set up an SSH agent on your development machine so that you can push changes with minimal hassle" and links only to [http://linux.die.net/man/1/ssh-agent](this man page).  This is far from trivial on a windows machine, and after several hours of trying I still can't get Pkg.submit() to work.

**Comment by tkelman** [comment]
Yes, SSH keys are kind of a mess, especially on Windows. I think there's a decent set of instructions from github that we could link to. I personally push all changes for PR's via https remotes, and only use SSH keys for `Pkg.tag` and `Pkg.publish`, and only ever do the latter from a Linux machine. You can work in git-bash directly, or set up additional remotes while you're in shell mode.

**Comment by amellnik** [comment]
Do you mean [https://help.github.com/articles/working-with-ssh-key-passphrases/](these) or some other ones?  If the former, I'm afraid that despite adding the code to julia's copy of git .profile, but I'm sure there's several other steps I'm missing.

**Comment by tkelman** [comment]
Note that you're getting your markdown links backwards.

Unfortunately I don't think the ssh-agent approach works well with Windows at all, since you're unlikely to have a persistent posix shell running in the background. We could translate that ssh-agent script from bash into Julia and add it to juliarc.jl, but then it's only good for as long as you keep Julia open, since processes spawned by Julia will (I think) be closed when you close Julia. So I believe that would mean you'd need to re-enter your key passphrase every time you start Julia, which really isn't much better than just entering your github password every time you push over https.

**Comment by tkelman** [comment]
What might work would be adding the ssh-agent code to the .profile or .bashrc that git-bash uses, and always starting Julia from within that git-bash. This is a pretty roundabout way to do things though, relative to normal Windows usage.

**Comment by amellnik** [comment]
Whoops, thanks!  Even a kludged-together method that works explained in detail would be a good first step.

**Comment by tkelman** [comment]
Well I don't use SSH keys on Windows, so if you can try experimenting with things and come up with something that works, we'd welcome a contribution to the documentation.

**Comment by amellnik** [comment]
I'm afraid I've spent several hours trying to get it to work at this point, which is why I posted here (I also opened a thread on stack exchange in case anyone there was able to get it working).  I'm not a particularly savvy git user though, so maybe there's an easy solution I missed.

**Comment by tkelman** [comment]
Understandable. I'd recommend you use https remotes then, unless someone has other suggestions.

**Comment by pao** [comment]
Use HTTPS remotes and the credentials helper: https://gitcredentialstore.codeplex.com/

If you insist on not doing that and using SSH instead, there's Pageant/Plink, from the PuTTY suite: http://devjar.me/post/22705088626/use-putty-pageant-with-git-on-windows

**Comment by jakebolewski** [comment]
We won't be using SSH on 0.5 so this seems to be no longer an issue.  Please reopen if we need better docs for the https remotes and credential helpers.
