### ISSUE TITLE
Include systemwise installed module in dependency resolution

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10894]
Currently julia accept packages installed systemwise under `/usr/share/julia/site/v${ver}/`. However, it seems that these packages are not included when resolving dependencies (e.g. in `Pkg.add`). Would be nice to take that into account.

**Comment by IainNZ** [comment]
I'm not sure when that was added, but I'm not entirely sure that is still wanted behaviour (looking there).

**Comment by yuyichao** [comment]
@IainNZ  What do you mean by "that"? Systemwise package?

I really hope it can be kept and also improve the support in packages.

**Comment by IainNZ** [comment]
Actually, this is a essentially a dupe of https://github.com/JuliaLang/julia/issues/8679 so probably best to continue it there. Some of my concerns are there - theres some fundamental design issues there.
