### ISSUE TITLE
Confusing deprecation warning

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10896]
See below. Are `{a,b, ...}` or `Any[a,b, ...]` valid syntax ever?

```julia
julia> {1, (1, 2)...}
WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
julia> {1, (1, 2)...}

WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
3-element Array{Any,1}:
 1
 1
 2

julia> {1, (1, 2), ...}
WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
julia> {1, (1, 2), ...}

WARNING: deprecated syntax "{a,b, ...}".
Use "Any[a,b, ...]" instead.
ERROR: UndefVarError: ... not defined

julia> Any[1, (1, 2), ...]
ERROR: UndefVarError: ... not defined
```

**Comment by kmsquire** [comment]
The splat (`...`) is applied before the deprecation warning, so it's not actually part of the input (and therefore, the warning has nothing to do with the fact that you were splatting `(1, 2)`.  Try:

```julia
julia> Any[1, (1,2)...]
3-element Array{Any,1}:
 1
 1
 2

julia> [1, (1,2)...]
3-element Array{Int64,1}:
 1
 1
 2
```

**Comment by yuyichao** [comment]
Oh, I see.

So the `...` is actually not a operator and is just a place holder for any number of elements......

I guess I'm just unlucky to hit it with just the right form of input and confused about what it is talking about.....

**Comment by kmsquire** [comment]
You got it!

**Comment by jiahao** [comment]
#8593

**Comment by yuyichao** [comment]
= = ..... Glad to see that I'm not the only one who is confused by the usage of `...` in the document.......
