### ISSUE TITLE
`http://julia-cn.readthedocs.org/en/latest/` points to Chinese document

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10903]
This (http://julia-cn.readthedocs.org/en/latest/) is the link to "en" document from "zh_CN" document but the returned page is still in Chinese. I had to manually delete the `-cn` to see the English document.

**Comment by yuyichao** [comment]
(Tested on a "C" locale machine so I guess this is not really locale dependent)

**Comment by yuyichao** [comment]
Also, why are all non-English translation under `julia-cn.readthedocs.org` ?......

**Comment by Gnimuc** [comment]
they import non-English docs to Read-the-Docs with the same URL, I guess.  This could be fixed in Read-the-Docs's dashboard, I think. ref:(http://julia-doc-ja.readthedocs.org/ja/latest/)

**Comment by yuyichao** [comment]
The original issue described here is not there anymore (i.e. `en` links to `zh` doc). However, it disappears because the link between the translated and the English version is removed (both ways) so I guess I won't call it fixed....

Also the translated documents are still under `julia-cn.readthedocs.org` (which is totally fine with me but feels wierd .....)

Where/how are these settings managed and how can I help with it?

**Comment by jiahao** [comment]
@yuyichao I've invited you to join @JuliaCN, which is responsible for the Chinese material.

**Comment by yuyichao** [comment]
@jiahao Thanks.
I was mainly talking about making links works but I can certainly help translating.

**Comment by jakebolewski** [comment]
@yuyichao please reopen if this is still an issue.

**Comment by yuyichao** [comment]
There isn't a link from the Chinese doc to the English doc anymore but the title of this issue is still valid in that the link is still pointing to Chinese doc.

It's currently arguably worse since there isn't a link from the original doc to the translated doc anymore.

I'd prefer to keep this open for figuring out where should we put these documents. (Not top priority and would probably wait until there's a better way to translate the document @Ismael-VC and of course after we figure out how do document things in general.)
