### ISSUE TITLE
"in" operator for arrays is hard to find in docs

### ISSUE THREAD

**Issue by canadaduane** [JuliaLang/julia#10904]
I spent a good 15 minutes trying to find some function that would say whether or not an element exists in an array/vector. I was unable to find it in the docs. I eventually went to the julia REPL and tried python-like syntax and found "in":

```
julia> a = [1, 2, 3]
3-element Array{Int64,1}:
in 1
 2
 3

julia> 1 in a
true

julia> 4 in a
false
```

Could this be prominently added to the documentation (i.e. near the top)? I expected it  in http://julia.readthedocs.org/en/latest/stdlib/arrays/ and I was searching for "element exists" or "element of".

**Comment by elextr** [comment]
In and friends are not array functions, they are actually defined for any iterable collection and are documented [here in collections](http://julia.readthedocs.org/en/latest/stdlib/collections/#Base.in) although it doesn't mention that they can be used as infix operators.

**Comment by canadaduane** [comment]
I googled and did not find that page. Do with this as you will. Just trying
to make Julia easier for newcomers :)

**Comment by elextr** [comment]
For some reason my emailed reply didn't show up here?

It would probably be good to make a PR with a pointer from the arrays section to the collections section, though that wouldn't solve searching.  But I'm sure nobody wants to repeat stuff in the docs.

**Comment by mschauer** [comment]
On a side note "?in" in the REPL works and gives the general answer which uses "collection" language.

**Comment by canadaduane** [comment]
Yes, a pointer to collections from array docs would be excellent--and maybe
add some more search-engine findable words to the "in" docs, since "in" is
such a difficult term to find via web search.

**Comment by mschauer** [comment]
``?in`` works, on the other hand ;-) (sorry for deleting and restoring this marginal comment)

**Comment by timholy** [comment]
@canadaduane, it's really easy to edit the documentation yourself, see https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation
