### ISSUE TITLE
using not allowed in `:()`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10910]
Is there a reason to not allow `:(using Module)` but allow `quote; using Module; end`?

Especially since `Expr(:using, :Module)` prints `:(using Module)`

**Comment by mlubin** [comment]
Same with ``import``. This has been a bit annoying on occasion.

**Comment by yuyichao** [comment]
Err, hmmm...... So basically the parser doesn't like a parenthesis after a `using`/`import`?

```julia
julia> :(using Module)
ERROR: syntax: invalid "using" statement

julia> :(
       using Module)
ERROR: syntax: invalid "using" statement

julia> :(using Module
       )
:(using Module)

julia> :(
       using Module
       )
:(using Module)
```

**Comment by yuyichao** [comment]
I hope that julia is not this white space sensitive......

**Comment by JeffBezanson** [comment]
The reserved words sometimes have little special behaviors hacked into them. It looks like we are explicitly requiring a newline after a `using` statement. That could easily be relaxed.

In cases where we're whitespace sensitive, we're whitespace sensitive. In cases where we're not, we're not.

**Comment by yuyichao** [comment]
And I guess another workaround before this is fixed would be

```julia
julia> :(using Module;)
quote 
    using Module
end
```

**Comment by yuyichao** [comment]
Maybe somewhat related

```
julia> a = :b
:b

julia> @eval export a

julia> @eval export $a
ERROR: unsupported or misplaced expression export
```

This one has [real usecase](https://github.com/staticfloat/Nettle.jl/pull/43/files)

**Comment by yuyichao** [comment]
`@eval` issue reported separately #11332.
