### ISSUE TITLE
`1.+im` returns a `Complex{Int}`

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#10920]
```
julia> typeof(1.+im)
Complex{Int64}

julia> typeof(1.)
Float64

julia> typeof(1+1.im)
Complex{Float64}
```
should be a Float64

**Comment by StefanKarpinski** [comment]
This is parsed as `1 .+ im` rather than `1. + im`. So the title a bit misleading.

**Comment by mauro3** [comment]
I see the problem.  Feel free to close if it cannot be resolved.

**Comment by StefanKarpinski** [comment]
I wouldn't mind this being a warning or something.

**Comment by mbauman** [comment]
Dup of https://github.com/JuliaLang/julia/issues/5246, which is nearly impossible to search for.  But I'll leave this open for now.

Parser warnings are annoying since the REPL parses your statements twice, so they print twice.  But maybe that can be fixed, too.

**Comment by JeffBezanson** [comment]
I don't really like giving a warning for this. It means you have to change your code if you want to remove the annoying message, so it might as well be an error if anything.

**Comment by kmsquire** [comment]
Is it easy for the parser to error and give both possible parses for
situations like this?

**Comment by JeffBezanson** [comment]
Yes I think it would be pretty easy to give an error.

**Comment by jiahao** [comment]
+1 to parser error

Old crufty me is used to writing `2./x` in C and Fortran to mean `2.0e0/x` and this occasionally trips me up.

**Comment by stevengj** [comment]
+1 for parser error

**Comment by jakebolewski** [comment]
See comments in #11529.
