### ISSUE TITLE
DigitalOcean virtual server BLAS word size mismatch

### ISSUE THREAD

**Issue by jhlq** [JuliaLang/julia#10921]
Made a default clone + make which worked for a while before exiting with the advice to ``` make OPENBLAS_USE_THREAD=0 ```, this ran until 

```
osutils.jl
Killed
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/home/citron/js/julia/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2
```
Cleaning doesn't help.

```
Platform Info:
  System: Linux (x86_64-linux-gnu)
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Prescot)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 2
Stepping:              3
CPU MHz:               2299.998
BogoMIPS:              4599.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1

Linux version 3.11.0-12-generic (buildd@allspice) (gcc version 4.8.1 (Ubuntu/Linaro 4.8.1-10ubuntu7) ) #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013
```

Have done a distro upgrade and recloned to no avail.

**Comment by pao** [comment]
"Killed" is often the kernel telling you you've used up all your memory, and the OOM killer has chosen your application to be sacrificed. How much memory does this system have?

**Comment by jhlq** [comment]
It has 2gb but no swap, rezizing is easy, what is an appropriate amount?

**Comment by ihnorton** [comment]
LLVM recommends minimum 4GB. (I've built on a chromebook with 2GB, and I
think another 2GB swap)

**Comment by jhlq** [comment]
Running at 8 now, picking up the previous make didn't work so have recloned again

**Comment by JeffBezanson** [comment]
I didn't think the sysimg build requires 2GB, but I agree this behavior is consistent with running out of memory.

**Comment by jhlq** [comment]
Build completed but...

```
~/js/julia$ ./julia
ERROR: OpenBLAS was not built with 64bit integer support.Warning: error initializing module LinAlg:
OutOfMemoryError()
ERROR: AssertionError: 
 in test_success at ./process.jl:480
 in hascolor at ./Terminals.jl:199
 in _start at ./client.jl:410

~/js/julia$ free -m
             total       used       free     shared    buffers     cached
Mem:          7985       1850       6134          5         33       1561
-/+ buffers/cache:        255       7729
Swap:            0          0          0
```
Built from scratch with 8 fresh GB so...?

**Comment by JeffBezanson** [comment]
I would take that error seriously. It means there's a word size mismatch calling BLAS, so we might be passing invalid array sizes.

**Comment by jhlq** [comment]
Let it be for a moment, SSH dc'd, relogged and actually managed to access the repl for a millisecond!

```
artai:~$ js/julia/julia
ERROR: OpenBLAS was not built with 64bit integer support.Warning: error initializing module LinAlg:
OutOfMemoryError()
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4396 (2015-04-21 10:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2e3c72b (0 days old master)
|__/                   |  x86_64-linux-gnu


signal (11): Segmentation fault
unknown function (ip: -192532393)
jl_apply_generic at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
showerror at replutil.jl:70
showerror at replutil.jl:81
jlcall_showerror_44064 at  (unknown line)
jl_apply_generic at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at client.jl:86
jl_f_apply at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
with_output_color at util.jl:208
jl_apply_generic at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
display_error at client.jl:84
jl_apply_generic at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
_start at ./client.jl:445
unknown function (ip: -218428167)
jl_apply_generic at /home/citron/js/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 4200411)
unknown function (ip: 4199311)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199386)
unknown function (ip: 0)
Segmentation fault (core dumped)
```

**Comment by jhlq** [comment]
This is a droplet at digitalocean

**Comment by tkelman** [comment]
You don't have anything else in your `Make.user` ? When we build from source we should be building openblas including lapack, not trying to mix our own openblas with system lapack.

**Comment by tkelman** [comment]
Prescott is also a decade-old Pentium 4 microarchitecture, so I suspect the virtualization is interfering with OpenBLAS' ability to detect the actual processor family here.

**Comment by jhlq** [comment]
Internet is finally trickling back after a 24h blackout. Tried finding the
Make.user information however no correct command could be guessed, google
was less than helpful ("no dont modify the expression in quotes") and no
result turned up from searching on makes homepage. Am in the  process of
deploying a new droplet in interest of providing more information instead
of just installing a binary, which should work, atleast it did for 0.2.

**Comment by tkelman** [comment]
Sorry, `Make.user` is a very-poorly-documented feature we use in Julia's build system. If you create a file with that name at the base of a Julia source checkout, you can set various make options in there instead of at the command line. Check whether you've created such a file, but I'm going to guess not. It would be helpful if you could save the entire output of a default clone and make to a log file and upload that to gist.github.com.

**Comment by jhlq** [comment]
Building succeeds on a droplet in their most recent regional center,
in contrast the other one was in one of their oldest (and no extra
files created in the folder). Currently making the log with make
OPENBLAS_USE_THREAD=0

**Comment by tkelman** [comment]
If everything succeeds then a log isn't much good. A log file would be useful from the failed build though, in case there are significant warnings or errors from somewhere.

**Comment by jhlq** [comment]
Clearly, this is the log from the failing droplet:
http://artai.co/julia/makelog.txt

**Comment by pao** [comment]
```
make -C openblas CC=gcc -m64 FC=gfortran -m64 RANLIB=ranlib FFLAGS= -O2 -fPIC LDFLAGS= TARGET= BINARY=64 USE_THREAD=0 NO_AFFINITY=1 DYNAMIC_ARCH=1 INTERFACE64=1 SYMBOLSUFFIX=64_
```

**Comment by tkelman** [comment]
Can you run `./julia -e 'versioninfo()'` ? The problem might be that the string `USE64BITINT` is not ending up in the output from `openblas_get_config()`

**Comment by jhlq** [comment]
artai:~/js/julia$ ./julia -e 'versioninfo()'
System image file "/home/citron/js/julia/usr/bin/../lib/julia/sys.ji" not found

**Comment by tkelman** [comment]
Right. Looks like you'll need to find a way to run `openblas_get_config()` or `openblas_get_config64_()` from a C test program. I keep getting undefined references when I try this...

**Comment by tkelman** [comment]
Nevermind, gcc was being picky when compiling from stdin for some reason. Try running the following.
```
echo '#include <stdio.h>
extern char* openblas_get_config64_();
int main() {printf("%s\n", openblas_get_config64_()); return 0;}' > linktest.c
gcc -o linktest linktest.c -Wl,--rpath,deps/openblas-v0.2.14 deps/openblas-v0.2.14/libopenblas.so
./linktest
```

**Comment by jhlq** [comment]
```
artai:~/js/julia$ echo '#include <stdio.h>
> extern char* openblas_get_config64_();
> int main() {printf("%s\n", openblas_get_config64_()); return 0;}' > linktest.c
artai:~/js/julia$ gcc -o linktest linktest.c -Wl,--rpath,deps/openblas-v0.2.14 deps/openblas-v0.2.14/libopenblas.so
gcc: error: deps/openblas-v0.2.14/libopenblas.so: No such file or directory


artai:~/js/julia$ gcc -o linktest linktest.c -Wl,--rpath,deps/openblas deps/openblas/libopenblas.so
artai:~/js/julia$ ./linktest
DYNAMIC_ARCH NO_AFFINITY Prescott
```

**Comment by tkelman** [comment]
Whoops, the folder name has changed recently.

Okay, so the Julia error was correct - `USE64BITINT` is not appearing in the openblas configuration. There's some build bug with openblas then.

**Comment by pao** [comment]
cc @xianyi

**Comment by xianyi** [comment]
@jhlq ， could you try just compiling OpenBLAS?

**Comment by jhlq** [comment]
../common_param.h:942:23: error: �GEMM_DEFAULT_OFFSET_B� undeclared (first use in this function)
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
                       ^
gemm.c:397:103: note: in expansion of macro �GEMM_OFFSET_B
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                                                       ^
make[1]: *** [sgemm.o] Error 1
make[1]: Leaving directory `/home/citron/OpenBLAS/interface'
make: *** [libs] Error 1

**Comment by tkelman** [comment]
@jhlq does this still happen with latest openblas?

**Comment by jhlq** [comment]
Haven't checked and when the time comes around to updating the website platform the whole VM will be replaced, so since it seems unlikely anyone will encounter this issue again it can be closed.

**Comment by tkelman** [comment]
Thanks for the update. Please do report any other future issues, I'm not entirely sure what happened here.
