### ISSUE TITLE
Optimising repeated calls to log

### ISSUE THREAD

**Issue by js947** [JuliaLang/julia#10922]
with

```
f(x) = log(x) + log(x)
@code_native f(1.0)
```

it seems that `log(%0)` is being called twice.

**Comment by simonster** [comment]
Related: #9942, #414

**Comment by vtjnash** [comment]
@StefanKarpinski this is a really gratuitous feature (fairly expensive for the compiler and but generally something that the author could have avoided in the first place), why is it point-release critical?

**Comment by StefanKarpinski** [comment]
It's not – it's an optimization which means that it *could* be done for 0.5.x. If it doesn't that's also fine.

**Comment by KristofferC** [comment]
This looks like a pure dup of https://github.com/JuliaLang/julia/issues/9942.
