### ISSUE TITLE
zero(Type::MathConst) not defined

### ISSUE THREAD

**Issue by caryan** [JuliaLang/julia#10926]
This shows up when trying to subtract a complex from a MathConst.

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4311 (2015-04-17 03:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 58cef56 (4 days old master)
|__/                   |  x86_64-linux-gnu

julia> π - 1im
ERROR: MethodError: `convert` has no method matching convert(::Type{MathConst{:π}}, ::Int64)
This may have arisen from a call to the constructor MathConst{:π}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T<:Real}(::Type{T<:Real}, ::Complex{T<:Real})
  convert{T<:Number}(::Type{T<:Number}, ::Base.Dates.Period)
  convert{R<:Real}(::Type{R<:Real}, ::Base.Dates.DateTime)
  ...
 in - at complex.jl:106

julia> 
```

The issues stems from [this line](https://github.com/JuliaLang/julia/blob/master/base/complex.jl#L106) in complex.jl which looks for ``zero(MathConst)``.  

I don't see a clean way around this besides adding a specialization of -(x::MathConst, y::Complex{T}) to constants.jl.  The other option is the always popular "let's just chuck MathConst out of base."

**Comment by JeffBezanson** [comment]
I think it would be easy to avoid using `zero` in that definition. We could instead compute `x - real(z)` and `-imag(z)` and promote them.

**Comment by simonster** [comment]
We used to do that, before I changed it in e81d98009493706badac37d01bdc1ad5ff89d3de for the reasons described in that commit message. Maybe the right thing to do is:

```julia
re = x - real(z)
Complex(re, oftype(re, -imag(z))
```

**Comment by JeffBezanson** [comment]
Int8 is now closed under negation, so I think it might work. Your suggestion here also looks good.

**Comment by simonster** [comment]
The problem is that `-true === -1::Int64`, which is relevant because `Int8(1) - im::Complex{Bool}` would yield `Complex(Int8(1), Int64(-1))::Complex{Int64}` after promotion rather than a `Complex{Int8}`. But my code above would handle that appropriately.

**Comment by JeffBezanson** [comment]
I see, yes your version is good.
