### ISSUE TITLE
Segfault with the Vararg datatype

### ISSUE THREAD

**Issue by phobon** [JuliaLang/julia#10925]
I was playing around with the new tuple syntax and came across this crash. Is the method definition itself nonsensical here?

```
julia> f(x::Vararg{Int}) = length(x)
f (generic function with 1 method)

julia> f()
ERROR: AssertionError: la == 0
 in typeinf_uncached at ./inference.jl:1664
 in typeinf at ./inference.jl:1304
 in typeinf_ext at ./inference.jl:1248

julia> f(1)

signal (11): Segmentation fault
unknown function (ip: -924344832)
unknown function (ip: -924134164)
unknown function (ip: -924133876)
jl_trampoline at /home/jdlangs/Documents/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /home/jdlangs/Documents/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: -924032813)
unknown function (ip: -924035646)
unknown function (ip: -923959389)
jl_toplevel_eval_in at /home/jdlangs/Documents/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
eval_user_input at REPL.jl:60
jlcall_eval_user_input_43978 at �% (unknown line)
jl_apply_generic at /home/jdlangs/Documents/Projects/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at task.jl:89
unknown function (ip: -924008416)
unknown function (ip: 0)
Segmentation fault (core dumped)
```

**Comment by mbauman** [comment]
There's a little magic the parser does to prepare methods with the `...` syntax that's not yet incorporated into the Vararg type.  It'll be fixed with #10911.

**Comment by phobon** [comment]
Cool, I'll look forward to trying that out once it's merged.

**Comment by StefanKarpinski** [comment]
I feel like a segfault on master is still a bug, no?

**Comment by pao** [comment]
Yes.

**Comment by mbauman** [comment]
I think @timholy's commit https://github.com/JuliaLang/julia/commit/76b2b26966c9d55be97c4c954d2d62f645d84a3a in #10911 will stand on its own and can be committed before the rest of that PR.  This is also an issue on 0.3, but I don't think anyone ever tried using `Vararg` before the tuple overhaul.

**Comment by phobon** [comment]
I wasn't sure, so thanks for clarifying the issue policy there.

**Comment by timholy** [comment]
Yes, 76b2b26966c9d55be97c4c954d2d62f645d84a3a probably would stand on its own. If people are in a rush I can cherry-pick it.

**Comment by JeffBezanson** [comment]
Sounds like a good idea to me. Fixing segfaults is always good!
