### ISSUE TITLE
Pair() has no type conversion?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10936]
```
julia> a = [1,2,3];
julia> round(Int32,a)
3-element Array{Int32,1}:
 1
 2
 3

julia> p = Pair(1,2);

julia> round(Int32,p)
ERROR: MethodError: `round` has no method matching round(::Type{Int32}, ::Pair{Int64,Int64})
```

Would it be acceptable to introduce `round{T<:Integer}(::Type{T}, p::Pair) = Pair(round(T, p.first), round(T, p.second))`?

**Comment by nalimilan** [comment]
The problem is, in the end, you may want to apply any operation on a `Pair`, not only `round` -- basically, any operation that is supported on an array. This raises again the issue of vectorized functions. Cf. https://github.com/JuliaLang/julia/issues/8450

**Comment by JeffBezanson** [comment]
Well, clearly `round` is not special here, so we'd have to add the full set of "vectorized" operations to Pairs. I'm against such definitions in general, and arrays get them only because everybody is so accustomed to vectorized operations on arrays. However ideally I'd like to remove even those (#8450).

**Comment by quinnj** [comment]
`map`, `map`, `map`!

**Comment by sbromberger** [comment]
@quinnj is that a proposed alternative? How can I use it?

In any case, this looks strange to me:
```
julia> map(x->Int32(x),p)
2-element Array{Any,1}:
 1
 2
```

**Comment by JeffBezanson** [comment]
It must be using a fallback for any iterable that returns an array. I wish such definitions didn't exist.

Also you can do `map(Int32, p)`.

**Comment by sbromberger** [comment]
In any case, I gather that this proposal hasn't received a favorable response, so I'll just close it out :)

**Comment by mbauman** [comment]
This issue could become a request for a specialized `map` for Pair.   Is there any reason against:

```julia
map(f, p::Pair) = f(p.first) => f(p.second)
```

**Comment by sbromberger** [comment]
@mbauman I really like that, actually. :) Thanks for suggesting it.

**Comment by JeffBezanson** [comment]
`map` on pairs might be ok, but it does seem a bit odd. Often the first and second elements of a Pair have very different semantics, e.g. key and value. It's a bit unusual to want to apply the same function to both.

**Comment by toivoh** [comment]
I agree with Jeff. What was the use case in the first place?

**Comment by sbromberger** [comment]
@toivoh came from https://groups.google.com/d/msg/julia-users/zkcWU-o-b98/8zgBeY1b2GAJ.
