### ISSUE TITLE
InexactError() in readdlm

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#10941]
On Julia v0.4:

```
julia> readdlm(open("20140202-r-00053"), '\t')

LoadError: at row 933674, column 43 : InexactError())

 in error at error.jl:19
 in dlm_parse at datafmt.jl:524
 in dlm_parse at datafmt.jl:371
 in readdlm_string at datafmt.jl:263
 in readdlm_auto at datafmt.jl:57
 in readdlm at datafmt.jl:47
 in readdlm at datafmt.jl:45
```

cc: @tanmaykm the file is at `julia:~/projects/xdata`.

**Comment by tanmaykm** [comment]
@jiahao I don't seem to have read permissions on it. Ok to change permissions on it?

**Comment by tanmaykm** [comment]
@jiahao Nevermind, made a local copy. Sorry for the noise.

**Comment by tanmaykm** [comment]
There may be an issue here: https://github.com/JuliaLang/julia/blob/feee48f7bf1ef79b912a27775d5165a2f10a00f7/base/datafmt.jl#L101

I was able to load the file successfully on julia.mit.edu, but this may get triggered on a machine with less memory.

Will push a fix changing `Int` to `round(Int, ...)`

**Comment by jiahao** [comment]
Thanks @tanmaykm
