### ISSUE TITLE
Function rand w/ sampling weights

### ISSUE THREAD

**Issue by kaslusimoes** [JuliaLang/julia#10949]
I'm porting some Python code to Julia but got stuck trying to find an alternative to this function on Numpy [numpy.random.choice](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html).

I'd expect something like:
```julia
rand(1:5 , p=[0.1, 0, 0.3, 0.6, 0])
```

**Comment by timholy** [comment]
I think this is better for Distributions.jl. If it's not in Distributions already and you want to implement it and contribute it to that package, it's a simple few-liner involving `cumsum` and `findfirst`.

**Comment by pao** [comment]
Link to Distributions repository: https://github.com/JuliaStats/Distributions.jl

**Comment by johnmyleswhite** [comment]
This is in StatsBase: http://statsbasejl.readthedocs.org/en/latest/sampling.html?highlight=sample
