### ISSUE TITLE
flisp segfaults on 32 bits when `MEMDEBUG2` is defined

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10942]
When `MEMDEBUG2` is defined, `flisp` segfaults for me when compiled for 32 bits.

My `Make.user`:

    ARCH = i686
    CFLAGS = -DMEMDEBUG -DMEMDEBUG2

I am running 64-bit (multiarch) Debian jessie.  The 32-bit build works fine unless I provide `MEMDEBUG2` as a `#define`.

Here is a [log of the build and valgrind's output](https://gist.github.com/garrison/a282ca079ea4a4e81fbc).

**Comment by JeffBezanson** [comment]
My guess is that this is because flisp requires 8-aligned addresses. This is no problem either (1) with flisp's normal allocator, or (2) on a 64-bit system. With MEMDEBUG2 I use malloc for everything, and it's probably not always 8-aligned on 32-bit. There should be more assertions for this.
