### ISSUE TITLE
Generic LDL' factorization

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#10953]
It would be nice to have a the semidefinite Cholesky or LDL' decomposition, which allows semidefinite matrices, is more stable and avoids computation of square roots. This makes most sense as generic julia algorithm, because for BLAS floats pivoted Cholesky does the trick. I remember that pivoting was difficult for abstract matrices.
cc @andreasnoack

**Comment by andreasnoack** [comment]
I plan to add this when time allows. The algorithms are not demanding, but the auxiliary methods and tests will take some time.

**Comment by ohinder** [comment]
this would be very very useful. especially since it is one of the best ways to factorize sparse symmetric matrices.

**Comment by akssri** [comment]
BTW, the MATLAB interface to (sy/he)trf has a bug related to the permutation.

**Comment by Sacha0** [comment]
Unlikely to receive attention prior to 0.6. Best!

**Comment by Nosferican** [comment]
As a clarification, the feature request is a Cholesky LDLt decomposition for abstract matrices including dense matrices?

**Comment by mschauer** [comment]
Yes, exactly.

**Comment by mfalt** [comment]
I've been hitting the problem of factorizing quasi-definite matrices several times. It is supported for sparse matrices through CHOLMOD, but not for dense.
I am ready to take a stab at this, does anyone have a good reference for implementing LDLt for definite and quasidefinite matrices?

**Comment by andreasnoack** [comment]
Can't you use `bunchkaufman`? (Not that I'm against a Julia implementation.)

**Comment by mfalt** [comment]
@andreasnoack Yes, that is usually a good alternative, but it is slightly annoying to have to dispatch and handle different types of factorizations to have efficient code for sparse and dense matrices.

**Comment by chriscoey** [comment]
is there a generic dense symmetric indefinite factorization available? (for eg BigFloat dense symmetric indefinite matrices)

**Comment by mschauer** [comment]
I have to admit, I never really missed this since opening the issue, because it might be useful for symmetric indefinite matrices, but doesn't really help with semidefinite matrices unlike I thought then.

**Comment by ViralBShah** [comment]
Migrated this to GenericLinearAlgebra.jl in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/87
