### ISSUE TITLE
Associate keywords or tags with packages when registering

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#10956]
The increasingly-common discussions over "allowed" names for registered packages (see e.g. https://github.com/JuliaLang/METADATA.jl/pull/2493) could be reduced by associating keywords or tags, or longer descriptions, with registered packages.

**Comment by kmsquire** [comment]
:+100:

**Comment by dpsanders** [comment]
That should read: obligatory keywords / tags AND longer descriptions

**Comment by dpsanders** [comment]
For example, each registered package has a `metadata.md` (or YAML) file containing the description and a bullet list of keywords.

**Comment by IainNZ** [comment]
See: https://github.com/JuliaLang/julia/issues/6807

Also see: https://github.com/IainNZ/Coverage.jl/pull/55

**Comment by timholy** [comment]
Closing in preference to #6807. I don't think the general idea is controversial, so what someone needs to do is just implement it.

**Comment by IainNZ** [comment]
Indeed, plus bikeshedding about file formats. I'm hopeful that I can do some work on this in the summer...

**Comment by dpsanders** [comment]
Great, sorry for the noise!

**Comment by StefanKarpinski** [comment]
> Indeed, plus bikeshedding about file formats.

I was about to propose what I think is the best file format for keywords, but then saw that past me had already taken care of it: https://github.com/JuliaLang/julia/issues/6807#issuecomment-42863654. Past me knows what's up.
