### ISSUE TITLE
finalizer is not being called for some REPL objects 

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#10960]
```
type Foo
    a
    function Foo(a)
        foo=new(a)
        finalizer(foo, x->@schedule print("FINALIZED!!!\n"))
        foo
    end
end
```

If executed in a single line, the finalizer is called.

```
julia> f=Foo(1);f=1;gc()
FINALIZED!!!
```

On separate lines, it is not.
```
julia> f=Foo(1)
Foo(1)

julia> f=1
1

julia> gc()

julia> gc()

julia> gc()
```

Came across this while debugging "leaks" in some parallel computation scenarios - turns out that the finalizer on `RemoteRef` objects is not being called in a consistent manner.

**Comment by amitmurthy** [comment]
```
julia> versioninfo()
Julia Version 0.4.0-dev+4464
Commit 7e63e6a* (2015-04-23 00:49 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by simonster** [comment]
I can reproduce the issue above on 0.4, but the finalizer appears to be called correctly on 0.3:

```julia
julia> f=Foo(1)
Foo(1)

julia> f=1
1

julia> gc()
FINALIZED!!!
```

**Comment by carnaval** [comment]
Not a GC problem. The object is staying in the task local "SHOWN_SET", whatever this is used for.

**Comment by amitmurthy** [comment]
Hmm, you are right. `:SHOWNSET` is used in `show(::IO, ::Any)` and `show(::IO, ::Associative)`. 

Defining a `show(::IO, ::Foo)` makes the problem go away.

I added 
```
    ss = get(task_local_storage(), :SHOWNSET, [])
    if ss == nothing
        print("\n SHOWNSET not found")
    else
        print("\n num entries : $(length(ss))")
    end
```

to the end of https://github.com/JuliaLang/julia/blob/e9fa25b1a1edb3c3ab3437aae88c27ab4f3ee94b/base/show.jl#L7-L54 and it shows 0 entries in the dict. Also `:SHOWNSET` is an `ObjectIdDict` .

How did you figure that the object is staying in the task local SHOWNSET?

**Comment by carnaval** [comment]
ha this is a funny one. Turns out our eqtable implementation on which OIDict relies does not clear the pointer to the key when you delete an item. Looks like a one line fix, I'll push that.

To answer your question : unfortunately it's not very user friendly. I went into gdb and watched the type tag of the object when it is gced. At the point it is being marked the stack trace is essentially a "ground truth" explanation of why it is being kept alive.

We could have an actual tool for this but I won't have time to work on it any time soon.

**Comment by carnaval** [comment]
Hum. It seems that nulling the key pointer leads to some pretty deep corruption. Someone somewhere must be relying on the bug.

**Comment by carnaval** [comment]
Nevermind it was my bad. This should fix it.

**Comment by amitmurthy** [comment]
Thanks.

**Comment by timholy** [comment]
Nice, @carnaval!

**Comment by ViralBShah** [comment]
This is a nice fix!

**Comment by samuela** [comment]
Is there any way to test this? Can REPL sessions be tested somehow?

**Comment by carnaval** [comment]
No need for repl session. Just put something with a finalizer as an ObjectIdDict key and delete! the entry.

**Comment by StefanKarpinski** [comment]
Should this be backported to 0.3?

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/10960#issuecomment-95631783 seems to indicate it's not a problem there?

**Comment by StefanKarpinski** [comment]
Yeah, I'm trying to track down a memory leak in ```readall(`echo hello`)``` on release-0.3, and thought this might be the culprit, but cherry-picking this doesn't help so I suspect it doesn't need backporting.
