### ISSUE TITLE
Issues building Julia 0.4 on Scientific Linux 6.4

### ISSUE THREAD

**Issue by gvdr** [JuliaLang/julia#10977]
Dear all,

So, I'm trying to build the last github version of Julia on my machine. I sit on a server, and I have only user privilege, no admin. I built a local version of gcc (4.9.2) and aliased it in bashrc. Hence, the compiler should be ok now. I am also aware of the architecture issues, hence I wrote my own Make.user, that goes as follows:

    prefix=/scratch-local/gvd16/julia-v0.4
    OPENBLAS_DYNAMIC_ARCH = 0

Anyhow, the building failed. I get the following error message:

    /scratch-local/gvd16/installers/julia/usr/include/openlibm_fenv_amd64.h:199: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
    In file included from Faddeeva/Faddeeva.c:3:
    Faddeeva/Faddeeva.cc: In function ‘cpolar’:
    Faddeeva/Faddeeva.cc:276: warning: implicit declaration of function ‘cpack’
    make[2]: *** [Faddeeva/Faddeeva.c.o] Error 1
    make[1]: *** [openspecfun/libopenspecfun.so] Error 2
    make: *** [julia-deps] Error 2

I tried to include `OPENBLAS_TARGET_ARCH=NEHALEM` in Make.user. Nothing changed.
I tried to use `OPENBLAS_NO_AVX2 = 1` instead of `OPENBLAS_DYNAMIC_ARCH = 0`. Nothing changed.

What should I do?

Best,

Giulio

P.S. system info:

    Architecture:          x86_64
    CPU op-mode(s):        32-bit, 64-bit
    CPU(s):                24
    model name	: Intel(R) Xeon(R) CPU E5-2667 0 @ 2.90GHz (for each cpus)
    Vendor ID:             GenuineIntel
    Scientific Linux release 6.4 (Carbon)
    Linux version 2.6.32-358.6.2.el6.x86_64 (mockbuild@sl6.fnal.gov) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Thu May 16 11:21:38 CDT 2013
    LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch

P.P.S. the aliased version of gcc is 4.9.2. Let me know if you'll need more information.

**Comment by vtjnash** [comment]
it seems like it might be getting a C compiler where it expected a C++ compiler? what is openlibm_fenv_amd64.h on your system? that file does not seem to exist anywhere on my current v0.4 build (according to `git grep openlibm_fenv_amd64.h`)

**Comment by gvdr** [comment]
Thanks, how can I check that?

**Comment by gvdr** [comment]
So, I could find that file in this locations:
./julia/usr/include/openlibm_fenv_amd64.h
./julia/usr-staging/openlibm/scratch-local/gvd16/installers/julia/usr/include/openlibm_fenv_amd64.h
./julia/deps/openlibm/include/openlibm_fenv_amd64.h

`cat ./julia/deps/openlibm/include/openlibm_fenv_amd64.h` returns

```
/*-
 * Copyright (c) 2004-2005 David Schultz <das@FreeBSD.ORG>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $FreeBSD: src/lib/msun/amd64/fenv.h,v 1.8 2011/10/10 15:43:09 das Exp $
 */

#ifndef	_FENV_H_
#define	_FENV_H_

#include "cdefs-compat.h"
#include "types-compat.h"

#include "math_private.h"

#ifndef	__fenv_static
#define	__fenv_static	static
#endif

typedef struct {
	struct {
		uint32_t	__control;
		uint32_t	__status;
		uint32_t	__tag;
		char		__other[16];
	} __x87;
	uint32_t		__mxcsr;
} fenv_t;

typedef	uint16_t	fexcept_t;

/* Exception flags */
#define	FE_INVALID	0x01
#define	FE_DENORMAL	0x02
#define	FE_DIVBYZERO	0x04
#define	FE_OVERFLOW	0x08
#define	FE_UNDERFLOW	0x10
#define	FE_INEXACT	0x20
#define	FE_ALL_EXCEPT	(FE_DIVBYZERO | FE_DENORMAL | FE_INEXACT | \
			 FE_INVALID | FE_OVERFLOW | FE_UNDERFLOW)

/* Rounding modes */
#define	FE_TONEAREST	0x0000
#define	FE_DOWNWARD	0x0400
#define	FE_UPWARD	0x0800
#define	FE_TOWARDZERO	0x0c00
#define	_ROUND_MASK	(FE_TONEAREST | FE_DOWNWARD | \
			 FE_UPWARD | FE_TOWARDZERO)

/*
 * As compared to the x87 control word, the SSE unit's control word
 * has the rounding control bits offset by 3 and the exception mask
 * bits offset by 7.
 */
#define	_SSE_ROUND_SHIFT	3
#define	_SSE_EMASK_SHIFT	7

__BEGIN_DECLS

/* Default floating-point environment */
extern const fenv_t	__fe_dfl_env;
#define	FE_DFL_ENV	(&__fe_dfl_env)

#define	__fldcw(__cw)		__asm __volatile("fldcw %0" : : "m" (__cw))
#define	__fldenv(__env)		__asm __volatile("fldenv %0" : : "m" (__env))
#define	__fldenvx(__env)	__asm __volatile("fldenv %0" : : "m" (__env)  \
				: "st", "st(1)", "st(2)", "st(3)", "st(4)",   \
				"st(5)", "st(6)", "st(7)")
#define	__fnclex()		__asm __volatile("fnclex")
#define	__fnstenv(__env)	__asm __volatile("fnstenv %0" : "=m" (*(__env)))
#define	__fnstcw(__cw)		__asm __volatile("fnstcw %0" : "=m" (*(__cw)))
#define	__fnstsw(__sw)		__asm __volatile("fnstsw %0" : "=am" (*(__sw)))
#define	__fwait()		__asm __volatile("fwait")
#define	__ldmxcsr(__csr)	__asm __volatile("ldmxcsr %0" : : "m" (__csr))
#define	__stmxcsr(__csr)	__asm __volatile("stmxcsr %0" : "=m" (*(__csr)))

__fenv_static __attribute__((always_inline)) DLLEXPORT inline int
feclearexcept(int __excepts)
{
	fenv_t __env;

	if (__excepts == FE_ALL_EXCEPT) {
		__fnclex();
	} else {
		__fnstenv(&__env.__x87);
		__env.__x87.__status &= ~__excepts;
		__fldenv(__env.__x87);
	}
	__stmxcsr(&__env.__mxcsr);
	__env.__mxcsr &= ~__excepts;
	__ldmxcsr(__env.__mxcsr);
	return (0);
}

__fenv_static DLLEXPORT inline int
fegetexceptflag(fexcept_t *__flagp, int __excepts)
{
	uint32_t __mxcsr;
	uint16_t __status;

	__stmxcsr(&__mxcsr);
	__fnstsw(&__status);
	*__flagp = (__mxcsr | __status) & __excepts;
	return (0);
}

DLLEXPORT int fesetexceptflag(const fexcept_t *__flagp, int __excepts);
DLLEXPORT int feraiseexcept(int __excepts);

__fenv_static __attribute__((always_inline)) DLLEXPORT inline int
fetestexcept(int __excepts)
{
	uint32_t __mxcsr;
	uint16_t __status;

	__stmxcsr(&__mxcsr);
	__fnstsw(&__status);
	return ((__status | __mxcsr) & __excepts);
}

__fenv_static DLLEXPORT inline int
fegetround(void)
{
	uint16_t __control;

	/*
	 * We assume that the x87 and the SSE unit agree on the
	 * rounding mode.  Reading the control word on the x87 turns
	 * out to be about 5 times faster than reading it on the SSE
	 * unit on an Opteron 244.
	 */
	__fnstcw(&__control);
	return (__control & _ROUND_MASK);
}

__fenv_static DLLEXPORT inline int
fesetround(int __round)
{
	uint32_t __mxcsr;
	uint16_t __control;

	if (__round & ~_ROUND_MASK)
		return (-1);

	__fnstcw(&__control);
	__control &= ~_ROUND_MASK;
	__control |= __round;
	__fldcw(__control);

	__stmxcsr(&__mxcsr);
	__mxcsr &= ~(_ROUND_MASK << _SSE_ROUND_SHIFT);
	__mxcsr |= __round << _SSE_ROUND_SHIFT;
	__ldmxcsr(__mxcsr);

	return (0);
}

DLLEXPORT int fegetenv(fenv_t *__envp);
DLLEXPORT int feholdexcept(fenv_t *__envp);

__fenv_static DLLEXPORT inline int
fesetenv(const fenv_t *__envp)
{

	/*
	 * XXX Using fldenvx() instead of fldenv() tells the compiler that this
	 * instruction clobbers the i387 register stack.  This happens because
	 * we restore the tag word from the saved environment.  Normally, this
	 * would happen anyway and we wouldn't care, because the ABI allows
	 * function calls to clobber the i387 regs.  However, fesetenv() is
	 * inlined, so we need to be more careful.
	 */
	__fldenvx(__envp->__x87);
	__ldmxcsr(__envp->__mxcsr);
	return (0);
}

DLLEXPORT int feupdateenv(const fenv_t *__envp);

#if __BSD_VISIBLE

DLLEXPORT int feenableexcept(int __mask);
DLLEXPORT int fedisableexcept(int __mask);

/* We currently provide no external definition of fegetexcept(). */
static inline DLLEXPORT int
fegetexcept(void)
{
	uint16_t __control;

	/*
	 * We assume that the masks for the x87 and the SSE unit are
	 * the same.
	 */
	__fnstcw(&__control);
	return (~__control & FE_ALL_EXCEPT);
}

#endif /* __BSD_VISIBLE */

__END_DECLS

#endif	/* !_FENV_H_ */
```

**Comment by gvdr** [comment]
Moreover, as I said I aliased the `gcc` to refer to my local install of it: my `~/.bashrc` contain the lines:
```
alias gcc='/scratch-local/gvd16/gcc-4.9.2/bin/gcc'
alias g++='/scratch-local/gvd16/gcc-4.9.2/bin/g++'
alias gfortran='/scratch-local/gvd16/gcc-4.9.2/bin/gfortran'
```

So, `g++` should be mapped to the 4.9.2 version of `g++`. Have I done something wrong there?

best,

Giulio

**Comment by vtjnash** [comment]
ah, i see you are on the `master` branch rather than the expected released tag v0.4.1(`cat deps/openlibm.version`)

there's an error in the ordering of the attributes in that file. clang notes this:
```
amd64/fenv.c:51:15: warning: attribute declaration must precede definition [-Wignored-attributes]
extern inline DLLEXPORT int feclearexcept(int __excepts);
```
other compilers are sometimes simply confused by having DLLEXPORT in the wrong place. perhaps that is the case here?

if we diff the expected file to the new file (`git diff v0.4.1:amd64/fenv.h master:include/openlibm_fenv_amd64.h`), the addition of the DLLEXPORT (in the wrong position) shows up as the only change to that file.

**Comment by gvdr** [comment]
Ook, so should I just clone that version instead of the master branch?

**Comment by vtjnash** [comment]
why are you cloning anything? it'll download dependencies automatically unless you manually intervene (for example, if you are working on developing them).

**Comment by gvdr** [comment]
Well' to be earnest, i just followed the Readme and run a `git clone git://github.com/JuliaLang/julia.git` as per instructions...

**Comment by tkelman** [comment]
What is `git --version` ? The git-external stuff might not work entirely right on old git versions for some reason?

**Comment by gvdr** [comment]
```
> git --version
git version 1.7.1
```

**Comment by tkelman** [comment]
I don't know exactly which features determine the minimum version requirement for building julia from source vs using the package manager in julia, but at least for the latter we have a set minimum version of 1.7.3. Can you try to get a more recent version?

**Comment by vtjnash** [comment]
i thought the only semi-recent git feature i used was `--depth`, but i didn't have an older git around to experiment with.

**Comment by gvdr** [comment]
Ok, so, I built my git 2.3.6 on local, and aliased it as usual. I think you spotted the right issue there. Or, at least, I now have different error messages.
I completely removed the old julia clone (`rm -rf julia/`) and run a `git clone git://github.com/JuliaLang/julia.git` afresh.
First time I run `make` I get
```
error: unknown option `detach'
usage: git checkout [options] <branch>
   or: git checkout [options] [<branch>] -- <file>...

    -q, --quiet           be quiet
    -b <new branch>       branch
    -l                    log for new branch
    -t, --track           track
    -2, --ours            stage
    -3, --theirs          stage
    -f, --force           force
    -m, --merge           merge
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively

make[1]: *** [libuv/configure] Error 129
make: *** [julia-deps] Error 2
```
If I run `make` again, ignoring the error message, I get
```
Making all in src
Making all in tests
Making install in src
 /bin/mkdir -p '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/bin'
  /usr/bin/install -c patchelf '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/bin'
Making install in tests
 /bin/mkdir -p '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/share/doc/patchelf'
 /usr/bin/install -c -m 644 README '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/share/doc/patchelf'
 /bin/mkdir -p '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/share/man/man1'
 /usr/bin/install -c -m 644 patchelf.1 '/scratch-local/gvd16/installers/julia/usr-staging/patchelf-0.8/scratch-local/gvd16/installers/julia/usr/share/man/man1'
warning: Remote branch v0.4.1 not found in upstream origin, using HEAD instead
fatal: Couldn't find remote ref v0.4.1
make[1]: *** [openlibm/Makefile] Error 128
make: *** [julia-deps] Error 2
```
And finally, at the third instance of `make`, the usual error regarding `openlibm_fenv_amd64.h`.

So, git is updated (I think... `git --version` returns the correct `git version 2.3.6`) and gcc is updated. So, what's going on?

**Comment by gvdr** [comment]
P.S. if I checkout the release version 0.3 the build seems to work...

**Comment by vtjnash** [comment]
that warning is fatal on my system if I change v0.4.1 to an invalid tag:
```
$ make
cd openlibm && git fetch -q git://github.com/JuliaLang/openlibm.git v0.4.2:remotes/origin/v0.4.2
fatal: Couldn't find remote ref v0.4.2
make: *** [openlibm/Makefile] Error 128
$ rm -r openlibm
$ make
git clone -q --depth=50 --branch v0.4.2 git://github.com/JuliaLang/openlibm.git openlibm
warning: Could not find remote branch v0.4.2 to clone.
fatal: Remote branch v0.4.2 not found in upstream origin
make: *** [openlibm] Error 128
```

something about your git installation (perhaps your ~/.gitconfig file?) seems to be badly corrupted.

`checkout --detached` has been available for as long as the git documentation is available (v1.7.10.3), and similarly for `clone --depth`
http://git-scm.com/docs/git-checkout

**Comment by gvdr** [comment]
Gosh, so, here's my ~/.gitconfig
```
[user]
        name = gvdr
        email = gvd16@uclive.ac.nz
[core]
        excludesfile = /users/math/gvd16/.gitignore
[url "https://"]
        insteadOf = git://

```

In fact, `git checkout --detach` works fine (should it be `--detach` instead of `--detached` maybe?)...

As said, the git install is fresh. I am a bit discouraged... After all, I was just trying to use those juicy distributed arrays... :-1: (

**Comment by tkelman** [comment]
Hopefully we'll figure this out. It might be that we aren't honoring bash aliases correctly?

**Comment by gvdr** [comment]
That may well be the case. I do suspect that aliasing in bash is not enough (see the fact that `--detach` is a known option if I just run `git checkout --detach`, yet gives an error whenever I run `make`). May it be possible to checkout *before* the make so to avoid it?

Anyhow, for reference, here's my complete bash profile:
```
bash-4.1$ cat ~/.bashrc
alias ruby-1.8.7='/usr/bin/ruby'
alias gem-1.3.7='/usr/bin/gem'
alias ruby='/scratch-local/gvd16/rubies/bin/ruby'
alias gem='/scratch-local/gvd16/rubies/bin/gem'
alias jeckjeck='jekyll build; jekyll serve --watch'
alias vim='/scratch-local/gvd16/vim7/usr/local/bin/vim'
alias gcc='/scratch-local/gvd16/gcc-4.9.2/bin/gcc'
alias g++='/scratch-local/gvd16/gcc-4.9.2/bin/g++'
alias gfortran='/scratch-local/gvd16/gcc-4.9.2/bin/gfortran'
alias git='/scratch-local/gvd16/git/bin/git'

export PATH=$PATH:/scratch-local/gvd16/rubies/bin/
export PATH=$PATH:/scratch-local/gvd16/vim7/usr/local/bin/
export VIMRUNTIME=/scratch-local/gvd16/vim7/usr/local/share/vim/vim74/
```

**Comment by gvdr** [comment]
Shame on me. Spotted one possible source of error: I just aliased the git, but the PATH variable had the local git bin folder after the system one, hence `which git` returned the old one. I switched the order, and now `--detach` is back in the make world. Build still compiling, hopefully will work.

**Comment by gvdr** [comment]
Yeah. Julia's running. Thanks to everybody.

**Comment by crayxt** [comment]
@gvdr Please close the ticket. Thanks.

**Comment by gvdr** [comment]
Updating and correctly setting the PATH variable for git fixes #10977

**Comment by gvdr** [comment]
Me is dumb. I don't have nothing to push (no change in any part of the code). How do I close the ticket?

**Comment by crayxt** [comment]
@gvdr Comment and close button below?

**Comment by gvdr** [comment]
duh. Sorry, couldn't even see it.

**Comment by tkelman** [comment]
Everyone seems to subconsciously think of that button as "cancel comment" due to its positioning.
