### ISSUE TITLE
Could not load module libarpack on ARMv7

### ISSUE THREAD

**Issue by physicsd00d** [JuliaLang/julia#10972]
Using LLVM 3.6 I compile julia on an armv7, I compile with

```
override LLVM_ASSERTIONS=1
LLVM_FLAGS+="--with-cpu=cortex-a9 --with-float=hard --with-abi=aapcs-vfp --with-fpu=neon --enable-targets=arm --enable-optimized --enable-assertions"

override OPENBLAS_DYNAMIC_ARCH=0
override OPENBLAS_TARGET_ARCH=ARMV7
override USE_BLAS64=0

override USE_SYSTEM_LIBM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1
override USE_SYSTEM_LAPACK=1

JCFLAGS += -fsigned-char

override USE_SYSTEM_LLVM=1
override USE_SYSTEM_BLAS=1
```
But when running make testall, I hit this error
```
exception on 6: ERROR: LoadError: error compiling naupd: could not load module libarpack: no error
while loading linalg/arnoldi.jl, in expression starting on line 6
```

I notice that julia ships with arpack-nm in deps, but for some reason it doesn't seem to be getting linked.  I had to get around this by downloading, compiling, and installing https://github.com/pv/arpack-ng.  Then recompiling julia with ```override USE_SYSTEM_ARPACK=1```.

So that works, but it doesn't seem to be the expected behavior.  Is anyone else having this issue?  Is there a way to check how julia was trying to link to the arpack that it ships with?  This seems pretty low-priority, but just wanted to throw it out there.

**Comment by tkelman** [comment]
Do you see anything from
```
ls deps/arpack-ng*
ls usr-staging/arpack-ng*
ls usr/lib/libarpack*
```
?

**Comment by vtjnash** [comment]
try `dlopen` with an absolute path to see a better error message from the system when it tried to load the library

**Comment by tkelman** [comment]
Problem with patchelf / rpath maybe?

**Comment by nalimilan** [comment]
AFAIK patchelf does not work on ARM: https://github.com/NixOS/patchelf/issues/8

**Comment by ViralBShah** [comment]
If `patchelf` does not work, we probably cannot provide generic linux binaries. That also explains why my efforts at `make dist` have not been very successful, even though I can run things just fine in the source directory. Should we be adding paths to `LD_LIBRARY_PATH` in that case on startup?

**Comment by ViralBShah** [comment]
Otherwise, the arpack tests pass for me.

@physicsd00d Also, if you could start from a clean clone, the build has been greatly simplified now, and may solve some of the issues.

**Comment by ViralBShah** [comment]
The arnoldi tests are passing for me. I am closing this one for now, and we can reopen if still an issue, and can be reproduced.
