### ISSUE TITLE
typed anonymous `VarArg`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10985]
It seems that typed `VarArg` has to have a name

```julia
julia> f(::Any...) = 1
ERROR: syntax: malformed expression

julia> f(a::Any...) = 1
f (generic function with 1 method)
```

Is there any ambiguity if the first case is allowed that I'm missing?

**Comment by pao** [comment]
I'm not sure if there's ambiguity, but I'm also unsure what such a signature could accomplish. Do you have a use case for this?

**Comment by yuyichao** [comment]
I discovered this when I was testing #10984 and found it to be a little unexpected.
I guess I can't think of a very good example for it, but I imagine, e.g., it can be used to make a method no-op for a certain set of input types?

**Comment by JeffBezanson** [comment]
I would accept a pull request fixing this but otherwise is very low priority.

**Comment by yuyichao** [comment]
@JeffBezanson Here's the promissed pull request #11345 .
