### ISSUE TITLE
Type{TypeVar(:T)} and Type are isequal and print the same but hash differently

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#10998]
```julia
julia> hash(Type{TypeVar(:T)})
0x06a6c4361224ac53

julia> hash(Type)
0x01cebc076594df80

julia> isequal(Type{TypeVar(:T)}, Type)
true
```

**Comment by JeffBezanson** [comment]
A simple case like this can maybe be patched up, but in general I'm not aware of any way to hash types. In the future, `hash` and `===` will refer only to the structure of a type, and not its meaning. `==` can still refer to type equality, but I don't think `hash` can be made consistent with it. If that's undesirable, then we might have to remove `==` for types and use a name like `typeequal` instead.
