### ISSUE TITLE
Ubuntu PPA contains no packages for new release ‘vivid’

### ISSUE THREAD

**Issue by mfsch** [JuliaLang/julia#10996]
The [PPA with Julia packages for Ubuntu](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases) does not yet contain packages for the new version of Ubuntu 15.04 ‘Vivid Vervet’ that was released yesterday. I don’t know whether they will be added automatically or whether some action from the maintainers of the repository is needed.

**Comment by pao** [comment]
cc @staticfloat

**Comment by staticfloat** [comment]
I've enabled `vivid` builds, but the ubuntu builds have been failing ever since the removal of git submodules.  We'll see if my recent changes fix it, but it could be a few days before builds show up.

**Comment by vaidhy** [comment]
Looks like it is still not there.. Are the scripts to build .debs part of the git repo?

**Comment by staticfloat** [comment]
The nightlies have `vivid` binaries, see [this PPA](https://launchpad.net/~staticfloat/+archive/ubuntu/julianightlies/+packages).  The new binaries of the latest stable version `v0.3.8` are still pending, but should be available in the next few days.

**Comment by staticfloat** [comment]
And to answer your question, the `debian/` directory (which contains all the scripts used to build the `.deb` file) are maintained [here](https://github.com/staticfloat/julia-debian/).

**Comment by vaidhy** [comment]
Thanks.. Will try to build the debs directly on my box..

**Comment by staticfloat** [comment]
Note that you can also, from within launchpad, download the original source
tarball and debian directory tarball for any package published on it.  You
need to click "view package details" on the PPA website, but you can then
replicate exactly whatever's going on inside the PPA perfectly.
-E

On Sun, May 3, 2015 at 1:44 PM, Vaidhy Mayilrangam <notifications@github.com

**Comment by mfsch** [comment]
It looks like the repository contains packages for vivid now, but they have unmet dependencies:

    The following packages have unmet dependencies:
     julia : Depends: librmath-julia-dev but it is not installable

**Comment by staticfloat** [comment]
Can you `apt-get update` and try again?

**Comment by mfsch** [comment]
Seems to work now. Thanks!

**Comment by tkelman** [comment]
should we close this then?
