### ISSUE TITLE
AppVeyor build is unhappy

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#11001]
It looks like f2e3d33273430190d4fbe8a0688871e48445755b, which has been an unqualified success on travis, has not gone over so well on appveyor.

There seem to be 2 main failure modes:

`LoadError: SystemError: rmdir: Directory not empty` in the file test, https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.4126/job/uwjkhm4f3hv7pg05

and a crash with an odd stack trace,
https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.4125/job/6sqj2r4t1581klb8

**Comment by tkelman** [comment]
And currently when I try to view anything on AppVeyor I get "Server Error in '/' Application."

Hopefully that's temporary.

**Comment by tkelman** [comment]
opened https://github.com/appveyor/ci/issues/247

**Comment by tkelman** [comment]
I can't get this to happen locally, and it seems to have gone away now: https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.4130/job/yv5jbkgrykw09mcj

For some reason the buildbots may have needed to rebuild some dependency and gotten that into the nightlies before it could work on appveyor. Not sure how that would result in an issue with starting without sys.dll though.

**Comment by tkelman** [comment]
there might still be a filesystem race in some newly-added test? https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.4135/job/u356dj2obeu9529n

**Comment by tkelman** [comment]
whoops, from a local build on that branch the `rmdir: Directory not empty` is a PR-specific problem with https://github.com/JuliaLang/julia/pull/10994
