### ISSUE TITLE
32bit memory error (uncovered with FixedPointNumbers)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#11026]
I'm just parroting @tkelman here (https://github.com/timholy/Images.jl/issues/284), but using FixedPointNumbers one can uncover some 32bit specific bugs. On 64bit, one gets this:
```jl
julia> using FixedPointNumbers

julia> Ufixed12[0.6 0.2; 1.4 0.8]
2x2 Array{FixedPointNumbers.UfixedBase{UInt16,12},2}:
 0.6  0.2
 1.4  0.8
```
On 32bit this either gives an `InexactError` or nonsense. However, scalars like `Ufixed12(1.4)` work fine.

**Comment by timholy** [comment]
Perhaps also related, however: https://github.com/JeffBezanson/FixedPointNumbers.jl/issues/15

**Comment by timholy** [comment]
The bug is not present on 0.3

**Comment by tkelman** [comment]
Based on the AppVeyor history for Images.jl https://ci.appveyor.com/project/timholy/images-jl/history it looks like it started a little less than 2 weeks ago? Am bisecting on 32-bit linux, should have more specifics soon.

**Comment by tkelman** [comment]
Unsurprisingly, caused by #10380 
```
tkelman@ygdesk:~/Julia/julia-linux32$ git bisect log
git bisect start
# bad: [982c60a71b02d30add6b983dbec88d09371494c4] Merge pull request #10974 from garrison/isdiag
git bisect bad 982c60a71b02d30add6b983dbec88d09371494c4
# good: [65ddb083c9a510b213f96397413c5f6d7732570b] Merge pull request #9468 from samoconnor/doc_notes_branch
git bisect good 65ddb083c9a510b213f96397413c5f6d7732570b
# good: [01a32160282917c389f3bd5a6e0ebc10d53989c6] Merge branch 'hayd-c2'
git bisect good 01a32160282917c389f3bd5a6e0ebc10d53989c6
# good: [ada46544e3016a247eff895f3ba66be91b9189bb] Fix #10829
git bisect good ada46544e3016a247eff895f3ba66be91b9189bb
# bad: [242b3d94d25ad36a1fbda07129869b9d92dbc4c7] Merge pull request #10923 from PalladiumConsulting/sg/codegen_warning
git bisect bad 242b3d94d25ad36a1fbda07129869b9d92dbc4c7
# bad: [2c9633e196bf2e3a40d91733f377ac13ed2d8f93] Merge pull request #10874 from JuliaLang/tk/raise-debugger-warning
git bisect bad 2c9633e196bf2e3a40d91733f377ac13ed2d8f93
# bad: [fb78bdb41ab2efaac32e87b85336e6871a6be8a8] fix a missing GC root
git bisect bad fb78bdb41ab2efaac32e87b85336e6871a6be8a8
# good: [bd748b973904fd23d43c7adf485cc2926f130dad] Merge branch 'amartgon-issues_#9664_#8416'
git bisect good bd748b973904fd23d43c7adf485cc2926f130dad
# good: [ba2b079523da4209fea7ada8572e4648c23f049d] NEWS updates and organization
git bisect good ba2b079523da4209fea7ada8572e4648c23f049d
# good: [d483948e5660f4e1bd84a2acb41ac7a8b4466f74] remove 2-argument `assert` performance trap
git bisect good d483948e5660f4e1bd84a2acb41ac7a8b4466f74
# bad: [4d1a4bfe153b9e072b49c445218c53ecec1ffb37] fix a missed jl_tuple_t in last rebase
git bisect bad 4d1a4bfe153b9e072b49c445218c53ecec1ffb37
# skip: [afd4eb038dcd9fa3e512509f4c332a9e7763ba59] redesign tuple types
git bisect skip afd4eb038dcd9fa3e512509f4c332a9e7763ba59
# only skipped commits left to test
# possible first bad commit: [4d1a4bfe153b9e072b49c445218c53ecec1ffb37] fix a missed jl_tuple_t in last rebase
# possible first bad commit: [afd4eb038dcd9fa3e512509f4c332a9e7763ba59] redesign tuple types
```

**Comment by JeffBezanson** [comment]
Maybe related to #11003

**Comment by tkelman** [comment]
This seems to have stopped happening on Linux recently, but it still happens on win32.

**Comment by tkelman** [comment]
I can't seem to reproduce this any more on current master, but it may be obscured by a few other unresolved issues.

**Comment by tkelman** [comment]
From a reverse-bisect, 5cb2835387a8614f884b41e049d1329c20449da4 caused this to stop happening. @mbauman does that make sense to you? We may just be avoiding the problematic code path now but that doesn't mean the underlying issue is necessarily solved.

At least reverting ebfebfdc48919b767124a62958b9b6455552f3c9 doesn't cause this one to come back, so it's unrelated to the other 32 bit problem from #10525.

**Comment by mbauman** [comment]
Very strange. It doesn't really, besides the fact that these seem to be perturbation-sensitive LLVM codegen issues. It's not very surprising that a refactoring would change things. It

**Comment by timholy** [comment]
This smells a bit like a dispatch/method priority problem. Don't know why it would manifest only on 32bit, however.

**Comment by timholy** [comment]
Nice!
