### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11023]
We have discussed adding license headers to files in the past, and the uniform sentiment seemed to be that they're ugly and don't have too much value. However, I think for clarity, esp. on files that may be useful outside of julia, we should mark files with a simple one or two line header, declaring the MIT license and specifying that people should look in LICENSE.md before copying the file outside of julia. See #11004 for more context.

**Comment by JeffBezanson** [comment]
Yes, seems reasonable.

**Comment by elextr** [comment]
(Usual disclaimer IANAL)

Yes, its best to be explicit that the files are subject to the license, note the license applies both inside and outside Julia, so I'd be just referring to the LICENSE file and not mentioning copying outside Julia.

(Aside: I am pleased to see the license file list all copyright holders (by reference to github), not just the original one or two devs that many projects do :)

**Comment by sjkelly** [comment]
What about signing off with http://developercertificate.org/ as well?

**Comment by StefanKarpinski** [comment]
-1

When I asked him, Bradley Kuhn said file copyright headers were legally useless and derived from old cargocult misunderstandings of copyright law. What are we trying to prevent? Copyright violations? The MIT license is allows people to copy code and include it into other open source and proprietary bodies of code, so most things people would do with the code wouldn't be a copyright violation anyway.

**Comment by Keno** [comment]
Reminding people that there is a license on the code that has to be followed, especially if files are copied outside of julia.

**Comment by ScottPJones** [comment]
Personally, I think the attribution part of the MIT license is important... the one or two extra lines to make that clear don't seem like a big deal.

**Comment by StefanKarpinski** [comment]
> Reminding people that there is a license on the code that has to be followed, especially if files are copied outside of julia.

This would be more compelling if the license were GPL or Apache, but it's MIT – there are almost no obligations that go along with using the code. "Don't sue me" + "keep this license in the code or substantial portions of it". It's arguable that using a single file might not even qualify as "substantial".

**Comment by Keno** [comment]
Fair enough, but the MIT license does require copying the copyright and license text. I'm advocating for making it easier for people to comply with the license by giving instructions in LICENSE.md and adding a small reference to it as a header.

**Comment by StefanKarpinski** [comment]
I could live with a one-line link to the LICENSE file at the top of every file and instructions there.

**Comment by Keno** [comment]
Yes, that was my thinking as well.

**Comment by JeffBezanson** [comment]
Yes, I like the 1- or 2- line version. When a random source file gets passed around, I want to know "where did this come from and what is the license?" Providing that information will help people out.

**Comment by peter1000** [comment]
I can start on this and add a first line with content. which takes 91 chars

```
@license This file is part of Julia and is released under the MIT license. (see LICENSE.md)
```

**Comment by tkelman** [comment]
That's not bad. Presumably you'll be writing a script to do this, so the actual text that gets added should be easier to modify than the list of files to add it to - and needing a different comment character for the C files vs the jl/sh files. Probably best to do a quick scan through the handful of existing files which come from external non-MIT-licensed sources, which should already be marked as such.

**Comment by StefanKarpinski** [comment]
I think the comment should literally just be a link to the LICENSE.md file on GitHub. The concern seems to be a file "wandering off" in which case referencing a file that it's unlikely to still be with is useless (if it hasn't wandered off, what's the problem?).

**Comment by peter1000** [comment]
so just
```
https://github.com/JuliaLang/julia/blob/master/LICENSE.md
```
Is that correct?
For files with shebang I put it just in the second line
No empty line before or after?

**Comment by StefanKarpinski** [comment]
I would have no empty line before and an empty line after.

**Comment by pao** [comment]
Terse? Good. But too terse. A couple words won't hurt. I would leave "This file is a part of Julia," just to provide some context.

**Comment by peter1000** [comment]
Still want to keep it at one line.

Current common option will be:
```
# This file is a part of Julia: https://github.com/JuliaLang/julia/blob/master/LICENSE.md
```
This fits in about 90 chars and I think is a fair compromise

Anyway: I will add the script to `contrib` than every one can do there own version ;)

**Comment by johnmyleswhite** [comment]
Please don't use more than 80 chars per line. You'll make every Julia file raise lints errors at companies where that limit is strictly enforced.

**Comment by peter1000** [comment]
I though I read somewhere 92 chars is the limit?

Anyway cut it down to
```
// Part of Julia. https://github.com/JuliaLang/julia/blob/master/LICENSE.md
```
with 75 chars

**Comment by StefanKarpinski** [comment]
That seems like a reasonable header message.

**Comment by mbauman** [comment]
Would it make sense to setup a redirect at julialang.org/license to the GitHub page?  That would have the advantage of being both shorter and more permanent (ok, I doubt GitHub will change its link structure anytime soon, but that `blob` part isn't very canonical).

**Comment by johnmyleswhite** [comment]
+1 to @mbauman's idea. That would be much better.

**Comment by nalimilan** [comment]
+1 It would be good to use the saved characters to mention `MIT license`. Something like:
```
# This file is a part of Julia. License is MIT: https://julialang.org/license
```

**Comment by peter1000** [comment]
Who is doing the ` redirect at julialang.org/license`?

I think as long it fits in th suggested 80 chars even with `//` all should be fine. Personally I like @nalimilan suggesten most.

**Comment by tkelman** [comment]
I'm not sure how to make it a redirect, that may require Stefan to fiddle with the dns? https://github.com/JuliaLang/julialang.github.com is the repo for the website, you'll notice http://julialang.org/LICENSE.md already shows you the website's own license.

**Comment by peter1000** [comment]
Would it not be better to use this one instead of redirect to github?
In case julia team decides to change the github license file the other one is anyway supposed to be updated too.

**Comment by tkelman** [comment]
This issue is discussing license headers for the Julia codebase, the existing license file in the website repository is the license for the website content. They both happen to be MIT, but the Julia codebase's license file has some exceptions and dependency information in it that is worth linking to.

**Comment by peter1000** [comment]
Thanks for your clarification.

**Comment by StefanKarpinski** [comment]
http://julialang.org/license now redirects to LICENSE.md on GitHub, so let's use that URL. If the location of the LICENSE.md file changes in the future, we can update that redirect without needing to touch any of the links in any of the source files.

**Comment by peter1000** [comment]
I hope this is what you expected.

Anyway if it is ok and gets merged I send a second PR with the script to be included into contrib.

Added some options so maybe it's useful for a longer time.

```
# Adds the julia license line `new_license` to configured file extensions in `rootpaths`.
#
# Option `old_license` to remove an existing license first in case one wants to change the
# license text in the future.
#
# Checks also if somewhere else in the file the license text is found (`copy/past error`)
# and if possible deletes such lines - if other text is on the same line it raises an error.

### CONFIG HERE

const print_result = true  # prints files which where not processed.

const rootpaths = [
    "../base",
    "../contrib",
    "../examples",
    "../src",
    "../test",
]

const skipfiles = [
    "../contrib/add_license_to_files.jl",
]

const ext_prefix = Dict([
(".jl", "# "),
(".sh", "# "),
(".h", "\/\/ "),
(".c", "\/\/ "),
(".cpp", "\/\/ "),
])

const new_license = "This file is a part of Julia. License is MIT: https://julialang.org/license"

# Old License text if such should be first removed - or empty string
const old_license = ""

### END CONFIG HERE
```

**Comment by tkelman** [comment]
I think we need more entries in skipfiles - do a (case-insensitive) git grep for files that already contain "license" or "copyright"

**Comment by peter1000** [comment]
So you want to skip all file which contain somewhere "license" or "copyright"?
I could add that to the script itself instead of adding all files to skipfiles?

**Comment by tkelman** [comment]
There should be few enough files with existing mentions of license or copyright that I think they deserve a manual one-by-one listing and individual decisions on them.

**Comment by peter1000** [comment]
I think this finishes my contribution to the issue: If there are anything else needed anyone can use the included script to adjust most things.

JuliaLang#11079
JuliaLang#11084
JuliaLang#11073

**Comment by tkelman** [comment]
Future work parts of this: flisp needs a different header, and license headers haven't been added yet to any files that don't end in .jl, .c, .cpp, .h, or .sh
