### ISSUE TITLE
git status after build shows that mode of files has changed

### ISSUE THREAD

**Issue by crayxt** [JuliaLang/julia#11042]
Building a fresh copy with LLVM_SVN on Centos 7 64-bit, when build stopped I made some changes and run `git diff` to see them, but it turns out, files mode has changed, see example output

```
diff --git a/.gitignore b/.gitignore
old mode 100644
new mode 100755
diff --git a/.mailmap b/.mailmap
old mode 100644
new mode 100755
diff --git a/.travis.yml b/.travis.yml
old mode 100644
new mode 100755
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
old mode 100644
new mode 100755
diff --git a/DISTRIBUTING.md b/DISTRIBUTING.md
old mode 100644
new mode 100755
```

Suggestions on improving this are highly appreciated.

**Comment by JeffBezanson** [comment]
Does this still happen?

**Comment by crayxt** [comment]
Sorry for late response, I will check it

**Comment by KristofferC** [comment]
Comment if this still happens.
