### ISSUE TITLE
Build fails due to libunwind checksum failure

### ISSUE THREAD

**Issue by sddhrthrt** [JuliaLang/julia#11045]
I'm trying to build julia on my arch box. Downloaded repo freshly and checked out `release-0.3`. But i'm facing this problem:

```
~/bin/julia [release-0.3|✚1] 
00:55 $ make
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   356  100   356    0     0    310      0  0:00:01  0:00:01 --:--:--   311
100   340  100   340    0     0    236      0  0:00:01  0:00:01 --:--:--   236
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
100  1969  100  1969    0     0    208      0  0:00:09  0:00:09 --:--:--   208
===============================================================================
  ERROR: sha512 checksum failure on libunwind-1.1.tar.gz, should be:
      bfe04f2bfac9f9e47c37f0b23ed2f264d8d3d3d6f1392fe9d794ee13cad216b3
      740979e922e4276fb65c1ccdc836fce48812cb5459ecdd2a89a621036a35d7c1
  But `sha512sum libunwind-1.1.tar.gz | awk '{ print $1; }'` results in:
      f9bd51aafbd1ebd77c1a0163cc7c7b6c567b4e0b8379aaa20505e4fb4407a05b
      668ae91c01133b79878e1cfc9fed27eda386d3717a57e1b964ac154a00382518
  This can happen due to bad downloads or network proxies, please check your
  network proxy/firewall settings and delete deps/libunwind-1.1.tar.gz
  to force a redownload when you are ready
===============================================================================
Makefile:1424: recipe for target 'libunwind-1.1/configure' failed
make[2]: *** [libunwind-1.1/configure] Error 2
Makefile:89: recipe for target 'julia-release' failed
make[1]: *** [julia-release] Error 2
Makefile:37: recipe for target 'release' failed
make: *** [release] Error 2
```

I can confirm that my internet has no problems. I may be behind a firewall, but I dont think my firewall blocks these downloads. I could test if I had the URL for the tar.gz it is trying to download.

**Comment by pao** [comment]
I just grabbed the tarball from savannah.nongnu.org and checked and I get the expected checksum.

```
vagrant@aspndev:~$ sha512sum /vagrant/libunwind-1.1.tar.gz
bfe04f2bfac9f9e47c37f0b23ed2f264d8d3d3d6f1392fe9d794ee13cad216b3740979e922e4276fb65c1ccdc836fce48812cb5459ecdd2a89a621036a35d7c1  /vagrant/libunwind-1.1.tar.gz
```

So something is up with your network or system.

http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz

(You can also find this URL, and that of our other downloaded dependencies, in `deps/Makefile`: https://github.com/JuliaLang/julia/blob/7b0871ed35d1ae3c27aec076818492203a8cccad/deps/Makefile#L1576

**Comment by sddhrthrt** [comment]
Thanks! Somehow my work internet thinks the URL is malicious.

**Comment by pao** [comment]
No problem. Work internet can be the worst.

You can manually satisfy the dependency if you hadn't already figured that out; find a suitable mirror and drop the tarball where the build system expects it and you should be fine.

Do we not cache this dependency on S3, @staticfloat? Or is that not backported to `release-0.3`?

**Comment by staticfloat** [comment]
`libunwind-1.1.tar.gz` is [definitely cached](https://cache.e.ip.saba.us) on both `master` and `release-0.3`, so that shouldn't be the problem.  What happened here is likely that @sddhrthrt got bit by the caching server freaking out today.  @tkelman [noticed this](https://github.com/JuliaLang/julia/commit/69e04da61f0137ae1294ba401ac4ba3a11b20451#commitcomment-10960010) earlier as well, and so the download fell back to the original server, which caused problems (Which is why we tried to cache these things in the first place).
