### ISSUE TITLE
Write `::Type{Rational{T}}` as `Rational{T}` in function argument lists

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#11047]
Having been playing with conversion and promotion rules, there seems to be clumsy extra typing due to having to write `Type` constantly, e.g.

```
promote_rule{T<:Integer,S<:FloatingPoint}(::Type{Rational{T}}, ::Type{S}) = promote_type(T,S)
```
Would it be possible to write this as 
```
promote_rule{T<:Integer,S<:FloatingPoint}(Rational{T}, S) = promote_type(T,S)
```

instead? From my (completely uninformed about parser niceties) point of view, it seems like this should be relatively easy to implement at the parser level, and would make such code both more readable and more writeable.

**Comment by mbauman** [comment]
I agree that `::Type{…}` can sometimes be clumsy, but this syntax unfortunately clashes with untyped arguments.  It looks a little crazy, but you can actually define a function with an argument whose name is the same as a type (and then shadows that type):

```jl
julia> f(Int) = Int*2
f (generic function with 1 method)

julia> f(2.5)
5.0
```

**Comment by yuyichao** [comment]
I guess the point was

```julia
f(Int) = 1
```

is different from
```julia
f{T}(T) = 1
```

The latter raises a syntax error right now.

**Comment by JeffBezanson** [comment]
Maybe we could do this by requiring curly braces?

```
f(Int{}) = ...
f(Rational{Int}) = ... 
```

**Comment by StefanKarpinski** [comment]
I used to worry about this, but these days I feel like adding methods that dispatch on singleton types is rare enough that it's just not worth adding syntactic sugar and complexity. How often does one really add promote rules? I feel like you write a few when you define a new numeric type and then you're done.

**Comment by carnaval** [comment]
Well, apart from the syntax issue, I think we should aim to remove `Type{}` from the type lattice and keep it only for dispatch. That way `typeof` is always giving the most precise answer, and the `Type{}` stuff is only a syntax to dispatch on a constant.

Then we keep the door open for dispatch on arbitrary constants (which would need a new syntax of course).

**Comment by JeffBezanson** [comment]
I don't really think you can have type-like things that are only for dispatch. `Type{x}` and `Constant{x}` *are* types; you can't claim they're not without fighting reality every step of the way.

**Comment by carnaval** [comment]
They are types indeed, in the sense that a type is a set of value satisfying some property. The problem is `typeof(x)` answering `Constant{x}` every time is not very useful.

What I'm saying is that I don't think user code should be exposed to anything other than "tag-level" types (i.e., everything `<:DataType`, which `Type{}` is not a part of), and dispatch is the only place we need to use more general types (and we can expand the set of supported such types as we get the compiler, the inference, and the dispatch logic to be smarter).

**Comment by StefanKarpinski** [comment]
@carnaval – am I correct that you're arguing for eliminating singleton types in favor of singleton dispatch? I.e. keep the dispatch feature but without the type that currently allows one to express it. I'm trying to think of anywhere else that we use singleton types? They are one of the harder things to explain when talking about the type system – and basically the only way to explain them is to give a dispatch example.

**Comment by carnaval** [comment]
To be honest I'm not sure what I'm arguing for. The problem is probably using those as type parameters where e.g. a `getindex(Vector{Type{Int}},::Int)` is inferred to be the constant `Int`.

What I don't like is having `T` such that we have `isa(x,T)` and `T <: typeof(x)` but not `T == typeof(x)` (for `x=Int` and `T=Type{Int}`).

**Comment by JeffBezanson** [comment]
`T <: typeof(x)` not equaling `T == typeof(x)` is definitely annoying, but to me it appears to be a fundamental issue with introducing more refined types. If `Type{}` or `Constant{}` exists, I don't think we'll be able to hide them very effectively.

When you want to know how a value `x` is dispatched, you need `Constant{x}`, *not* `typeof(x)`. This could certainly come up when using `invoke` or doing reflection.

**Comment by carnaval** [comment]
You're right we probably can't sweep them under the rug. So, now that everything is under `DataType`, is "the lower bound of subtypes `T` of `DataType` such that `isa(x,T)`" a correct definition for `typeof(x)` ?

**Comment by JeffBezanson** [comment]
My impression is we don't have any viable syntax sugar for this; reopen if I'm missing something.
