### ISSUE TITLE
Minor warning about missing metis directory during suitesparse build

### ISSUE THREAD

**Issue by crayxt** [JuliaLang/julia#11051]
Hi,

Just noticed from logs, that during the build of suitesparse, following message appears
```
ar: creating libcerbla.a
a - xerbla.o
ar: creating libsuitesparseconfig.a
a - SuiteSparse_config.o
/bin/sh: line 0: cd: metis-4.0: No such file or directory
ar: creating libamd.a
a - amd_i_aat.o
```
Doesn't seem to hurt anything
PS: Building on Centos Linux 7 64-bit platform.

**Comment by tkelman** [comment]
Metis is an optional dependency of SuiteSparse, it can be used for matrix ordering and partitioning. Metis 4.0 has a non-open-source license, and Metis 5 is Apache licensed which is incompatible with GPLv2. I don't know whether SuiteSparse has an option to use Metis 5, or if there's a way to silence this warning. If anyone wants to look into SuiteSparse's makefiles to find out be my guest, but I think there are better things to work on than upstream projects' build warnings.

**Comment by crayxt** [comment]
Understood.

**Comment by tkelman** [comment]
See also: https://github.com/JuliaSparse/Metis.jl
