### ISSUE TITLE
type instability in sqrt?

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/julia#11054]
Consider the following:

```
julia> function tester()
       x = 10.0
       sqrt(x)
       end
tester (generic function with 1 method)

julia> @code_typed tester()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[:x],Any[Any[:x,Float64,18]],Any[],Any[]], :(begin  # none, line 2:
        x = 10.0 # line 3:
        return (GlobalRef(Base.Math,:box))(Float64,(GlobalRef(Base.Math,:sqrt_llvm))(x::Float64)::Any)::Float64
    end::Float64))))
```

Is there  a reason for the `Any` above? Given that we have a `DomainError` for negative floating point arguments to `sqrt`,  and we know that `x::Float64`, shouldn't we know that this `Any` should really be `Float64`?

**Comment by jiahao** [comment]
You are not reading the output correctly. The entire expression does evaluate to a `Float64` (see the line `end::Float64`).

**Comment by spencerlyon2** [comment]
Ok thanks. I saw that, but what does the `::Any` just before that mean?

**Comment by jiahao** [comment]
The output is hard to read, but it is a nested expression. the `Any` quite unambiguously refers to the subexpression

`(GlobalRef(Base.Math,:sqrt_llvm))(x::Float64)::Any`

I'm not sure I can tell you more.
