### ISSUE TITLE
Deprecation warning for global scope does not have filename/lineno info

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11050]
When a deprecated syntax/function is used in global scope, the printed warning is not very helpful to find where the usage is.

Script
```julia
int32(1)

function f()
    int64(1)
end

f()

error()
```

Printed:
```
WARNING: int32(x) is deprecated, use Int32(x) instead.
 in int32 at ./deprecated.jl:31
 in include_from_node1 at ./loading.jl:129
WARNING: int64(x) is deprecated, use Int64(x) instead.
 in int64 at ./deprecated.jl:31
 in f at /home/yuyichao/tmp/test_deprecated.jl:6
 in include_from_node1 at ./loading.jl:129
ERROR: LoadError: 
 in error at ./error.jl:20
 in include_from_node1 at ./loading.jl:129
while loading /home/yuyichao/tmp/test_deprecated.jl, in expression starting on line 11
```

As shown above, the `error()` in global scope prints a similar backgrace but the "while loading" message can be used to figure out where the error is generated.

Also, the `loading.jl` in the backtrace printed is quite useless and would be nice it it can be suppressed when printing the backtrace...

**Comment by vtjnash** [comment]
this shouldn't be too hard to fix actually (relative to all of the other backtrace issues that are open)

there's already a global variable in C called `jl_lineno`. i'm not sure that the current filename is located in any globals, but that's not too hard to fix. this doesn't handle the recursive load case as well as LoadError, but it would at least provide a more useful line number to check those variables while creating the output for a call to warn and appending them to the printout.
