### ISSUE TITLE
VersionNumber: prerelease/build fields are incorrect for Julia's special version numbers

### ISSUE THREAD

**Issue by nyuszika7h** [JuliaLang/julia#11057]
The `prerelease` and `build` fields are set incorrectly in Julia's special version numbers:

```
julia> v"1.2.3-".prerelease
("",)

julia> v"1.2.3+".build
("",)
```

Those should be `()`, because the `-` and `+` are not actually an indicator of pre-release / build metadata in this case. Such versions would be invalid in semver.

**Comment by pao** [comment]
@nyuszika7h, care to try a patch? It looks like this is the relevant code: https://github.com/JuliaLang/julia/blob/5f3bd18c79f24e660303ff44134c1e52ce565acf/base/version.jl#L92

cc @StefanKarpinski since I think he understands SemVer the best of us...

**Comment by carlobaldassi** [comment]
If they were `()`, they would be indistinguishable from `v"1.2.3"`, while they are in fact distinct. These version numbers with trailing `-`/`+` are not part of SemVer proper, but are used to denote interval limits. See [the documentation](http://docs.julialang.org/en/release-0.3/manual/strings/#man-version-number-literals).

**Comment by nyuszika7h** [comment]
I know what they're used for, but I didn't realize that.

**Comment by pao** [comment]
D'oh, right. Thanks @carlobaldassi.
