### ISSUE TITLE
Array{Type, 1} misbehaves after loading Gadfly

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11059]
```
julia> Dict{Type, Int}()
ERROR: TypeError: call: in new, expected Array{Type{T},1}, got Array{Type{T},1}
```

This used to work on 0.3

**Comment by Keno** [comment]
Simpler test case:
```
julia> type Foo
       x::Array{Type,1}
       end

julia> Foo(Array(Type,16))
ERROR: TypeError: call: in new, expected Array{Type{T},1}, got Array{Type{T},1}
```

**Comment by Keno** [comment]
Or even simpler:
```
julia> typeof(Array(Type,16)) == Array{Type,1}
false
```

**Comment by Keno** [comment]
@JeffBezanson Any insights?

**Comment by simonster** [comment]
All of these examples work for me on 39d640e

**Comment by pao** [comment]
Are you still on LLVM-svn, @Keno?

**Comment by JeffBezanson** [comment]
Also works for me.

**Comment by Keno** [comment]
I am indeed on llvm-svn, but I do believe I have seen the same problem on 3.3.

**Comment by Keno** [comment]
Interestingly, the fault from which I was reducing this still exists on 3.3, but the reduction does not apply. I'll see if I can fix this on LLVM svn, since I have a concrete reduction. Maybe that'll fix my original test case on 3.3 too.

**Comment by Keno** [comment]
Hmm, turns out this only happens after loading Gadfly and plotting something. I'll check for memory corruption.

**Comment by Keno** [comment]
Ignore, this memory corruption caused by Cairo.jl which hasn't been updated for the cfunction syntax change yet.

**Comment by Keno** [comment]
Actually, never mind. Fixed the memory corruption, but this is still happening.

**Comment by Keno** [comment]
This is most curious. Consider
```
using Gadfly
x = plot(sin,0,2);
m = MIME"image/png"()
buf = IOBuffer()
pipe = Base64Pipe(buf)
writemime2(pipe, x) = draw(PNG(pipe, Compose.default_graphic_width, Compose.default_graphic_height), x)
function writemime4(pipe, x)
    png = PNG(pipe, Compose.default_graphic_width, Compose.default_graphic_height)
    draw(png,x)
end
writemime3(pipe, x) = PNG(pipe, Compose.default_graphic_width, Compose.default_graphic_height)
```
`writemime2`/`writemime4` fail inside the call to PNG, `writemime3` passes.

**Comment by Keno** [comment]
Some more inconsistencies. After loading gadfly:
```
julia> typeof(Array(Type,0)) <: Array{Type,1}

Breakpoint 1, jl_f_subtype (F=0x759230, args=0x7fffffffdeb8, nargs=2)
    at builtins.c:347
347	    JL_NARGS(subtype, 2, 2);
(gdb) p jl_(args[0])
Array{Type{T<:Any}, 1}
```

Before:
```
Breakpoint 1, jl_f_subtype (F=0x759230, args=0x7fffffffdeb8, nargs=2)
    at builtins.c:347
347	    JL_NARGS(subtype, 2, 2);
(gdb) p jl_(args[0])
Array{Type, 1}
```

There seems to be an extra `<:Any` in the first case. Not sure it's significant.

**Comment by JeffBezanson** [comment]
Only the exact object originally created to define `Type` will print as `Type`, otherwise the typevar inside is shown.

**Comment by Keno** [comment]
Should they still compare the same?

**Comment by JeffBezanson** [comment]
They should definitely be ==, and I think they might be === as well.

**Comment by Keno** [comment]
How would I construct one, I tried:
```
julia> Type{TypeVar(:T,Any,true)} == Type
true

julia> Type{TypeVar(:T,Any,true)} === Type
false

julia> Array{Type{TypeVar(:T,Any,false)},1} == Array{Type,1}
false
```

**Comment by Keno** [comment]
Ok, so after loading Gadfly, we have:
```
julia> typeof(Array(Type,1)) == Array{Type{TypeVar(:T,Any,false)},1}
true
```
while before we have
```
julia> typeof(Array(Type,1)) == Array{Type{TypeVar(:T,Any,false)},1}
false
```
Does that mean I should look at the typeof code instead?

**Comment by JeffBezanson** [comment]
Looks like a type cache issue.

**Comment by Keno** [comment]
Can you explain what the expected behavior should be?

**Comment by Keno** [comment]
@JeffBezanson, I'd be happy to try to fix this as it is blocking me on something else. If you have a hunch what the problem is, I can try to debug.

**Comment by vtjnash** [comment]
was this resolved by Jeff's commit to fixed sorting of the type cache?

**Comment by ihnorton** [comment]
I can't reproduce - `typeof(Array(Type,1)) == Array{Type{TypeVar(:T,Any,false)},1}` gives `false` both before and after `using Gadfly`.

**Comment by Keno** [comment]
Try the full reproducer above:
```
julia> using Gadfly
Warning: Method definition take(Any, Int64) in module Base at iterator.jl:134 overwritten in module Iterators at /Users/kfischer/.julia/Iterators/src/Iterators.jl:52.

julia> x = plot(sin,0,2);

julia> m = MIME"image/png"()
MIME type image/png

julia> buf = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> pipe = Base64Pipe(buf)
Base.Base64.Base64EncodePipe(IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1),0x00,0x00,0x00)

julia> writemime2(pipe, x) = draw(PNG(pipe, Compose.default_graphic_width, Compose.default_graphic_height), x)
writemime2 (generic function with 1 method)

julia> writemime2(pipe, x)
ERROR: TypeError: call: in new, expected Array{Type{T},1}, got Array{Type{T},1}

julia> typeof(Array(Type,1)) == Array{Type{TypeVar(:T,Any,false)},1}
true
```

**Comment by ihnorton** [comment]
Ok, missed that. Same behavior.

**Comment by JeffBezanson** [comment]
I think there is a chance a85357a2cad8ac9cd0bc0a5cf2d5e7277fadbe3a fixed this.

**Comment by carnaval** [comment]
tried on latest master of julia + Gadfly, could not reproduce with the latest test script
