### ISSUE TITLE
UndefVarError when a local variable is previously referenced in an `@async` block.

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#11062]
```
julia> function test2()
           @async x=1
           x = 2
       end
test2 (generic function with 1 method)

julia> test2()
ERROR: UndefVarError: x not defined
 in test2 at none:2

```

I guess what is happening here is that `x` in the `@async` block refers to the yet-to-be-defined `x` in `test2` ?

**Comment by samtkaplan** [comment]
For the record, here is a corresponding thread on the Julia users mailing list:
https://groups.google.com/forum/?fromgroups=#!topic/julia-users/Q5QVpry4lBI

**Comment by ihnorton** [comment]
Nominate to close, seems to be fixed on 0.5:
```
julia> function test2()
                 @async x=1
                 x = 2
          end
test2 (generic function with 1 method)
julia> test2()
2
```

The following fails (probably #13450?):
```
function test2()
                  @async x=1
                  println(x)
                  x = 2
end
```

**Comment by tkelman** [comment]
if we're going to close, should add a test

**Comment by vtjnash** [comment]
> The following fails (probably #13450?):

which is as to be expected, since it has an UndefVar usage in that `println` (although incorrectly printed as `UndefRefError`, since lowering boxed it)

**Comment by amitmurthy** [comment]
Test added in #15164 

Probably closed by @JeffBezanson's work on anonymous functions.
