### ISSUE TITLE
Sysimg error with multi-core start

### ISSUE THREAD

**Issue by multidis** [JuliaLang/julia#11063]
I am building a custom Julia image (v0.3) using [build_sysimg.jl](https://github.com/JuliaLang/JuliaBox/blob/master/docker/build_sysimg.jl) by calling
    build_sysimg(joinpath(dirname(Sys.dlpath("libjulia")),"sys"), "native", "/home/juser/jimg.jl", force=true)

A number of modules are listed in jimg.jl as `using Package` for pre-compilation.

The image builds without errors and starts fine, and package load time is much shorter after pre-compilation as expected. However, when Julia is **started with more than one CPU core/worker**, e.g. `julia -p 2`, the following **error** appears at startup:
```
ERROR: `convert` has no method matching convert(::Type{Dict{K,V}}, ::Parameters)
 in create_worker at multi.jl:1067
 in start_cluster_workers at multi.jl:1028
 in addprocs at multi.jl:1237
 in process_options at ./client.jl:236
 in _start at ./client.jl:354

    versioninfo()

Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Piledriver)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by pao** [comment]
> A number of modules are listed in jimg.jl as using Package for pre-compilation.

What packages are you adding to the image? Can you post your `jimg.jl` file, please?

**Comment by multidis** [comment]
Using quite a few packages but after some trial-error it turns out there is one particular package causing this problem, [BlackBoxOptim.jl](https://github.com/robertfeldt/BlackBoxOptim.jl).

In fact, the error

    ERROR: `convert` has no method matching convert(::Type{Dict{K,V}}, ::Parameters)

could be related to the `parameters`-type [defined](https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/src/parameters.jl#L3) in that package.

What I am not sure is how this type gets into the worker configuration variable. Is this **some kind of Base vs package name clash conflict?**

My debugging chain so far:

ERROR: `convert` has no method matching convert(::Type{Dict{K,V}}, ::Parameters)
 in create_worker at multi.jl:1067
 in start_cluster_workers at multi.jl:1028
 in addprocs_internal at multi.jl:1234
 in addprocs at multi.jl:1237

error generated at:
w.config = config
config is 5th input argument to create_worker function
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L1067


config::Dict
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L101


ws[i] = create_worker(bind_addr, port, pubhost, io, wconfig, cman.manage)
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L1028
(io, bind_addr, port, pubhost, wconfig) = read_cb_response(instances[i])
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L1027

inst[2] [3] [4] depending on insttype
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L1006

inst = instances[i]
https://github.com/JuliaLang/julia/blob/release-0.3/base/multi.jl#L1004
(insttype, instances) = cman.launch(cman, np, config)


NOTE: start_cluster_workers enforces config-input as Dict

cman.launch
 function launch_local_workers(cman::LocalManager, np::Integer, config::Dict)
instances-output:
collect(zip(io_objs, configs))

**Comment by multidis** [comment]
Resolved in `BlackBoxOptim.jl` by avoiding `Base.merge` dispatch conflict.
https://github.com/robertfeldt/BlackBoxOptim.jl/pull/8
