### ISSUE TITLE
Nested function introduces a variable scoping bug

### ISSUE THREAD

**Issue by Sisyphuss** [JuliaLang/julia#11065]
This is a bug related to the discussion in [https://groups.google.com/forum/?fromgroups=#!topic/julia-users/ddsrBhXFJsc]:

I modified the code and tested it (v0.3.6):
Normal code:
```Julia
for i = 1:2
    if i == 1
        z = "z is defined" 
        println("Iteration $i: $z") 
    elseif i == 2
        try
            println("Iteration $i: $z")
        catch
            println("Iteration $i: z is undefined")
        end 
    end
end 
```
Iteration 1: z is defined
Iteration 2: z is defined

Now I define a function `g()` inside and get a bug:
```Julia
for i = 1:2
    g() = z
    if i == 1
        z = "z is defined"  
        println("Iteration $i: $z") 
    elseif i == 2
        try
            println("Iteration $i: $z")
        catch
            println("Iteration $i: z is undefined")
        end 
    end
end 
```
Iteration 1: z is defined
Iteration 2: z is undefined

[pao: syntax highlighting]

**Comment by JeffBezanson** [comment]
Arguably the second behavior is the correct one, and the first one is the bug. Variables only used within a loop are supposed to be newly allocated on each iteration.

**Comment by Sisyphuss** [comment]
> Variables only used within a loop are supposed to be newly allocated on each iteration.

This remark is inaccurate. I rewrite the above examples with `while` loop: 
```Julia
i = 1
while i <= 2
    if i == 1
        z = "z is defined" 
        println("Iteration $i: $z") 
    elseif i == 2
        try
            println("Iteration $i: $z")
        catch
            println("Iteration $i: z is undefined")
        end 
    end
    i += 1
end 
```
Iteration 1: z is defined
Iteration 2: z is defined

```Julia
i = 1
while i <= 2
    g() = z
    if i == 1
        z = "z is defined" 
        println("Iteration $i: $z") 
    elseif i == 2
        try
            println("Iteration $i: $z")
        catch
            println("Iteration $i: z is undefined")
        end 
    end
    i += 1
end 
```
Iteration 1: z is defined
Iteration 2: z is defined

Now in the second example, `z` is still defined.

**Comment by JeffBezanson** [comment]
Turns out this issue was described in this comment: https://github.com/JuliaLang/julia/issues/1571#issuecomment-22351198

**Comment by JeffBezanson** [comment]
Also, I should have said "for loop" instead of "loop". `for` loops create a new scope on each iteration; `while` loops do not. The idea is that `while` is more of an imperative construct, and `for` is "parallel".

**Comment by johnmyleswhite** [comment]
Are there performance implications to having `while` create a new scope on each iteration? It seems to me that making `while` and `for` as similar as possible would be desirable, all else being equal.
