### ISSUE TITLE
det(A::Matrix{T}) not type stable (and maybe that's a good thing!)

### ISSUE THREAD

**Issue by gajomi** [JuliaLang/julia#11069]
I have been writing some code involving determinants of matrices with Integer eltype, where in the context of my application it is natural to expect that the determinants will also be integral. However, the following code illustrates that may not always be the case

```julia
A = [[1 0];[0 4]]
B = [[1 2];[0 4]]
C = [[1 2];[3 4]]
[eltype(det(M)) for M in (A,B,C)]

>>>3-element Array{Any,1}:
   Int64  
   Int64  
   Float64
```
A trip to the [implementation]( https://github.com/JuliaLang/julia/tree/cb9bcae93a32b42cec02585c387396ff11836aed/base/linalg/generic.jl#L421) makes the reason obvious: the methods checks for triangular structure, converting to Triangular type when detected (Triangular implements type stable determinants), with a general fallback being converting to LU decomposition and calling det on result. Now LU decomposition seems to also have type stable determinants, but is quite eager to promote the eltype of the original matrix in the conversion (since 1/1 == 1.0). 

So this all seems quite reasonable and actually the type instability doesn't actually affect the performance of my application, but I still would like to have Integer determinants for Integer matrices. For now, I just convert manually to the correct type. I'm not sure though about correctness of the result for large matrices though...

Suggestions on how (or if) to fix?

**Comment by pao** [comment]
cc @andreasnoack

**Comment by jiahao** [comment]
Linear algebra over integer fields is _extremely_ prone to integer overflow, so I do not think it is sensible to enforce the result that `det(::Matrix{Integer})` produces an `Integer`.

```jl
julia> det(rand(1:2, 40, 40))
2.7079863751382944e12

julia> det(rand(1:1000, 8, 8))
-1.2015198166341353e22
```

**Comment by gajomi** [comment]
@jiahao - You bring up a very good point. I guess that, in contrast to my wishes as of an hour ago, I think the current behavior is the right idea (my application not being the most common, and with an alternative implementation at any rate). 

In fact, I'll add to your examples the following, which are not concerned with Matrix types but still have the overflow/underflow problem:

```julia
#not desirable
det(Diagonal([1:20])),det(Diagonal([1:21]))
>>>(2432902008176640000,-4249290049419214848)
#not wrong
det(Diagonal(1.0*[1:20])),det(Diagonal(1.0*[1:21]))
>>>(2.43290200817664e18,5.109094217170944e19)
```
As I mentioned in the original post, there seem to be other AbstractMatrix subtypes in addition to Diagonal that implement type stable determinants. Perhaps it makes sense to promote to floating point types in the context of det to prevent the overflow behavior in these cases?

**Comment by andreasnoack** [comment]
I've fixed the type instability by converting the result from the `det(XTriangular)` to what the LU factorization based solution would have produced. If you call the methods for `Diagonal` or `Triangular` directly there is no promotion to floating point. In these cases there are not type instabilities and there is no way of ensuring reasonable calculation of a determinant in general so people will always have to be aware when calculating a determinant. The overflow happens later for floating point values, but instead you just get a large error.

**Comment by gajomi** [comment]
@andreasnoack - Makes sense. Thanks!
