### ISSUE TITLE
Matrix multiplication not defined generally enough?

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#11088]
I would have thought this would work, since ``T`` has the operations needed to form a vector space: 

```
typedef T
end

+(::T, ::T) = T()
*(::Float64, ::T) = T()
Base.zero(::T) = T()

randn(2,2) * [T(); T()]
```

but it results in ``LoadError: MethodError: `zero` has no method matching zero(::Type{Any})``.

**Comment by pao** [comment]
I think this might be because of a missing `promote_type` definition for `T`: https://github.com/JuliaLang/julia/blob/9fea76a18119af7e4e7f1a909f9eafae00285791/base/linalg/matmul.jl#L358

**Comment by simonster** [comment]
(But per [the manual](http://julia.readthedocs.org/en/latest/manual/conversion-and-promotion/#defining-promotion-rules), you should define `promote_rule`, and `promote_type` should work.)

**Comment by malmaud** [comment]
That works. Thanks guys.
