### ISSUE TITLE
windows cross-compile error in symlink function definition

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#11108]
the windowsxp-only test should be at runtime, not compile-time. otherwise a wine-cross compile doesn't work on my windows 8 test machine:
```
     * file                exception on 1: ERROR: LoadError: WindowsXP does not support soft symlinks
 in symlink at fs.jl:168
 in runtests at J:\julia32\test\testdefs.jl:77
 in anonymous at multi.jl:626
 in run_work_thunk at multi.jl:587
 in remotecall_fetch at multi.jl:675
 in anonymous at task.jl:1390
while loading J:\julia32\test\file.jl, in expression starting on line 17
```

**Comment by tkelman** [comment]
Ref #11018. I'm surprised your version of Wine thinks it's XP. Must be a configuration difference between different distros. How do we go about making that macro give runtime-dependent results?

**Comment by vtjnash** [comment]
you can't, but the XP test should be a runtime function, not a macro.

**Comment by vtjnash** [comment]
it's quite possible I modified the version manually in winecfg, or winetricks had done so for whatever reason. i thought it defaulted to XP several years ago, but perhaps that isn't true anymore.

**Comment by tkelman** [comment]
I checked on Ubuntu and `Base.windows_version()` was returning `(0x00000005,0x00000002)` which is Vista.

**Comment by vtjnash** [comment]
sure, but it's trivial to reconfigure it, so i don't really think about it (until something gives the wrong result and I have to play with versions to figure out which one has the right combination of bugs/features/fixes to match windows)

**Comment by tkelman** [comment]
Should be fine to change the few occurrences of this in base and the tests to `@windows_only (Base.windows_version() > Base.WINDOWS_XP_VER) && ...`

**Comment by vtjnash** [comment]
yes, exactly. although in this particular case, the test also needs to be moved inside the function definition rather than defining a different function depending on the result of that test
