### ISSUE TITLE
Typo in post-tupocolypse warning

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11106]
The following code

    f(::Int, ::Any) = 1
    f(::Any, ::Int) = 2

leads to the following warning

    Warning: New definition 
        fTuple{Any,Int64} at /tmp/testcase.jl:2
    is ambiguous with: 
        fTuple{Int64,Any} at /tmp/testcase.jl:1.
    To fix, define 
        fTuple{Int64,Int64}
    before the new definition.

Where it says `fTuple` it should really say `f`.

The relevant code in julia is [here](https://github.com/JuliaLang/julia/blob/803193eaa603e303be602a4a41fcbbff0c541675/src/gf.c#L1202-L1213), but I am not sure how to fix it.

**Comment by vtjnash** [comment]
dup of https://github.com/JuliaLang/julia/pull/10984

**Comment by garrison** [comment]
Thanks!  There was no issue for this so I filed one.  I hadn't noticed the outstanding pull request.
