### ISSUE TITLE
Inconsistent\Nonintuitive block introduction in (f(x) = y) expressions

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#11115]
If I write `:(f(x) = x)`, I get `:(f(x) = x)`.

However, if I write `:(@m f(x) = x)`, I get:
```julia
(@m f(x) = begin # none, line 1:
               x
           end
```

Which introduces the following odd behavior:

```julia
macro m(ex)
    m(ex)
end

m(ex) = ex

m(:(f(x) = x)) != macroexpand(:(@m f(x) = x)) # true
```

Minor thing, but it messed up my debugging, so I thought I should at least point it out.

**Comment by jakebolewski** [comment]
@fcard you the bottom test will never be true because the expanded ast will have gensymed symbols due to hygiene.

BTW, it seems like the two forms introduce a begin block on 0.4.
```julia
julia> Meta.show_sexpr(:(f(x) = x))
(:(=), (:call, :f, :x), (:block,
    (:line, 1, :none),
    :x
  ))
julia> Meta.show_sexpr(:(@m f(x) = x))
(:macrocall, symbol("@m"), (:(=), (:call, :f, :x), (:block,
      (:line, 1, :none),
      :x
    )))
```

**Comment by fcard** [comment]
You're right, it does introduce a block on 0.4. Weird, I was sure I had checked it there too. I will have to pay more attention next time.

About the gensymed symbols, you're correct, again, I should've paid more attention. I guess a better example would be:

```julia
macro m(ex)
    m(ex)
end

m(ex) = @assert ex.args[1] == ex.args[2]

@m f(x) = f(x)    # throws an error
m(:(f(x) = f(x))) # does not throw an error
```

Well, either way, it seems my problem has been fixed already. Thank you very much, and sorry for wasting your time :P

**Comment by jakebolewski** [comment]
no worries, if you want to escape the hygiene pass you can do so with a slight modification of your original example.

```julia
julia> macro m(ex)
           m(esc(ex))
       end

julia> Meta.show_sexpr(:(@m f(x) = x))
(:macrocall, symbol("@m"), (:(=), (:call, :f, :x), (:block,
      (:line, 1, :none),
      :x
    )))
```
