### ISSUE TITLE
Constructor documentation error

### ISSUE THREAD

**Issue by dpo** [JuliaLang/julia#11113]
````JULIA
$ cat test_doc.jl
@doc doc"Some type." ->
type Something
  x :: Float64;
end

@doc doc"Simple constructor." ->
Something() = Something(1.0);
````

At the REPL:
````JULIA
julia> VERSION
v"0.4.0-dev+4572"

julia> include("test_doc.jl")
ERROR: LoadError: MethodError: `doc` has no method matching doc(::Type{Something}, ::Method, ::Base.Markdown.MD, ::Expr)
Closest candidates are:
  doc(::Function, ::Method, ::Any, ::Any)
  doc(::Any, ::Any)
  doc(::Function, ::Method)
  ...
 in anonymous at docs.jl:43
 in include at /Applications/Julia-0.4.0-dev-dea3d0e420.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0-dev-dea3d0e420.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /private/tmp/test_doc.jl, in expression starting on line 6
````

**Comment by jiahao** [comment]
cc @one-more-minute 

```jl
julia> @doc "Simple constructor."
       Something() = Something(1.0);
```

works for me, as does

```jl
julia> @doc doc"Simple constructor."
       Something() = Something(1.0);
```

However, it does not seem possible to access the docstring from the REPL.

```jl
help?> Something
search: Something

  Some type.

help?> Something()
call(::Type{Something}) at none:2
```

**Comment by dpo** [comment]
@jiahao Yes that works, but it doesn't associate the doc string with the constructor.

**Comment by ScottPJones** [comment]
@dpo doesn't the 1 argument form of @doc just display the documentation?
I think that might be what is happening...

**Comment by one-more-minute** [comment]
Unfortunately, this has been broken since types stopped being generic functions. `@doc` used to associate docs with methods of the type itself, whereas it should now associate them with methods of `call`, probably via some intermediate structure similar to `FuncDoc`.

Hopefully attaching the docs to the type itself, rather than to outer constructors, isn't too painful as a workaround.

**Comment by dpo** [comment]
@ScottPJones I'm not sure what the 1-arg form of `@doc` is. If you mean `@doc doc "..."` without the final `->`, that doesn't result in an error, but the constructor doc isn't available via `help()` or `?`.

@one-more-minute The case I'm actually interested in is where there are multiple constructors. Note that using the same code as above in Julia 0.3 and Docile, I get something sensible:

````JULIA
julia> VERSION
v"0.3.6"

julia> using Docile

julia> using Lexicon

julia> include("test_doc.jl")
Something (constructor with 3 methods)

help?> Something
DataType   : Something (constructor with 3 methods)
  supertype: Any
  fields   : (:x,)

  1: .Something
  2: .Something()
````

**Comment by ScottPJones** [comment]
@dpo Try doing ?@doc at the >julia prompt...
```julia
   Retrieving Documentation
    ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  You can retrieve docs for functions, macros and other objects as follows:

  @doc foo
  @doc @time
  @doc md""
```

As you can see, it will just fetch the documentation (which it can't find) and not set anything... which is exactly what you are seeing...
Only the 2-argument form will set the doc string for what it finds after the ->

**Comment by one-more-minute** [comment]
@dpo Sure, the breaking change to the way types work was introduced in 0.4, so 0.3 still works fine via Docile. Your syntax is fine, it's just that the internal machinery has a kink.

I realise it's not ideal when you're working with multiple constructors, but you can still write:

```jl
@doc doc"""
  Some type.
  
  `Something()`: Simple constructor
  """ ->
type Something
  x :: Float64;
end

Something() = Something(1.0)
```

or similar, and it should work fine. Unless someone is willing to dive into the doc code themselves (which you're more than welcome to, of course), I won't be able to fix this myself for a month or two.

**Comment by dpo** [comment]
Ok, thanks. I'll find a workaround.

**Comment by spencerlyon2** [comment]
Any progress on this?

**Comment by one-more-minute** [comment]
This should be fixed now.
