### ISSUE TITLE
`@fastmath` introduced `::Any` annotations

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11122]
```
julia> foo(x) = @fastmath x-1.0
foo (generic function with 1 method)

julia> @code_typed foo(1.0)
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:x], Any[Any[],Any[Any[:x,Float64,0]],Any[],Any[]], :(begin  # none, line 1:
        return (GlobalRef(Base.FastMath,:box))(Float64,(GlobalRef(Base.FastMath,:sub_float_fast))(x::Float64,1.0)::Any)::Float64
    end::Float64))))
```
It doesn't seem to actually affect the generated code in this case, but it's something we should at the very least avoid printing for people (since it gets printed in red).

**Comment by timholy** [comment]
Off-topic: `@code_typed` shouldn't print red at all, only `@code_warntype`. Must be a bug in the printing code (probably one I introduced).

**Comment by vtjnash** [comment]
it probably doesn't affect the generated code since the output is immediately boxed

**Comment by Keno** [comment]
I agree, but if we're telling people to look out for bad type information, we should only display it if there's actually bad type information. I'd also like to know why this happens in the first place, since other intrinsics don't behave this way. Something to do with going through the macro expander?

**Comment by vtjnash** [comment]
i don't believe that intrinsics (other than Intrinsics.box) have type information, since their return type is actually undefined (until they get boxed)

**Comment by Keno** [comment]
Sure, but the annotation also doesn't get printed:
```
return (top(box))(Float64,(top(sub_float))(x::Float64,1.0))
```

**Comment by vtjnash** [comment]
ah. maybe the GlobalRef (instead of top) is throwing off some heuristic in the printing logic? perhaps we should introduce a new type `Unboxed` for tagging these nodes during inference (or perhaps use `ANY`)?

**Comment by yuyichao** [comment]
I think this is fixed now. Especially since `@code_typed` doesn't print `::Any` anymore....
