### ISSUE TITLE
svdvals for Diagonal matrices is wrong

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#11120]
If I have a complex diagonal matrix `A`, such as:
```
julia> A = diagm(rand(Complex128,5))
5x5 Array{Complex{Float64},2}:
 0.680111+0.994161im       0.0+0.0im            0.0+0.0im            0.0+0.0im            0.0+0.0im
      0.0+0.0im       0.726701+0.652338im       0.0+0.0im            0.0+0.0im            0.0+0.0im
      0.0+0.0im            0.0+0.0im       0.156787+0.374442im       0.0+0.0im            0.0+0.0im
      0.0+0.0im            0.0+0.0im            0.0+0.0im       0.210987+0.506129im       0.0+0.0im
      0.0+0.0im            0.0+0.0im            0.0+0.0im            0.0+0.0im       0.422898+0.39665im

julia> svdvals(A)
5-element Array{Float64,1}:
 1.20454
 0.976545
 0.579805
 0.548344
 0.405942
```
Perfect. If I then try:
```
julia> B = Diagonal(A)
5x5 Base.LinAlg.Diagonal{Complex{Float64}}:
 0.680111+0.994161im       0.0+0.0im            0.0+0.0im            0.0+0.0im            0.0+0.0im
      0.0+0.0im       0.726701+0.652338im       0.0+0.0im            0.0+0.0im            0.0+0.0im
      0.0+0.0im            0.0+0.0im       0.156787+0.374442im       0.0+0.0im            0.0+0.0im
      0.0+0.0im            0.0+0.0im            0.0+0.0im       0.210987+0.506129im       0.0+0.0im
      0.0+0.0im            0.0+0.0im            0.0+0.0im            0.0+0.0im       0.422898+0.39665im

julia> svdvals(B)
ERROR: MethodError: `isless` has no method matching isless(::Complex{Float64}, ::Complex{Float64})
 in sort! at sort.jl:265
 in sort! at sort.jl:279
 in sort! at sort.jl:359
 in sort at sort.jl:370
 in svdvals at linalg/diagonal.jl:157
```
Because in `base/linalg/diagonal.jl`,
`svdvals(D::Diagonal) = sort(D.diag, rev = true)`
which is wrong for both `Complex` matrices and block-diagonal matrices, which `Diagonal` is ostensibly supposed to support, right? ~~Also, I seem to have lost numerical precision when I convert to `B` using `Diagonal()`~~ (e: nevermind, I'm silly).

This is on `Version 0.4.0-dev+4629 (2015-05-04 00:27 UTC)`.

**Comment by jiahao** [comment]
Yes, in the complex case, it should be sorted by the magnitudes. The block diagonal case, `Matrix{Matrix}`, is a little more complicated, but it should also be a global sort of the singular values of each subblock.

**Comment by Jutho** [comment]
Even in the real case it should take absolute values; singular values should not be negative.

**Comment by kshyatt** [comment]
There is an open PR for this & other stuff, but this is not a hard fix. This bug is embarrassing. Can we take another look at @andreasnoack's PR or can someone make one dedicated to this?

**Comment by kshyatt** [comment]
Break out your box wine, everyone. It's time to party, Chateau de Carton style.
