### ISSUE TITLE
Color package does not seem to be available

### ISSUE THREAD

**Issue by rvaj** [JuliaLang/julia#11139]
I tried to Pkg.add("Jewel") on a 64-bit Windows 7 installation of Juno/Julia.  I get the following message:

julia> Pkg.add("Jewel")
fatal: Not a git repository: 'P:\.julia\v0.3\Color\.git'
ERROR: failed process: Process(`git '--work-tree=P:\.julia\v0.3\Color' '--git-di
r=P:\.julia\v0.3\Color\.git' rev-parse HEAD`, ProcessExited(128)) [128]
 in wait at task.jl:51
 in sync_end at task.jl:311
 in add at pkg/entry.jl:319
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:30
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20

**Comment by tkelman** [comment]
Same basic issue as https://github.com/JuliaLang/julia/issues/9091 - what are the values of `ENV["HOMEDRIVE"]` and `ENV["HOMEPATH"]` ?

**Comment by JeffBezanson** [comment]
See resolution in #9091; if that doesn't work please reopen.

**Comment by rvaj** [comment]
All set.



-----Original Message-----
