### ISSUE TITLE
Function in class in DLL

### ISSUE THREAD

**Issue by easleykg** [JuliaLang/julia#11138]
I am using a DLL in Excel VBA that opens with the statement below. The function I call is Start(0).

Set MyObj = NEW DLLName.CLASS

I have found examples of ccall as in:

ccall((:GetKeyState,"User32"), stdcall, Uint16, (Ptr{Uint16},), 20)

but NOTHING that hints how to reference MyObj.Start(0) using Julia. It'll probably be stupid simple when I see it...

Thanks!

**Comment by vtjnash** [comment]
a better place for this question would be SO or the julia-users mailing list.

I can help there, but please include what DLL you are trying to load. I expect this is a COM library, but it's a little hard to tell from your question.

**Comment by easleykg** [comment]
Thank you for your offer.

I believe this to be COM. I didn’t create it. I am trying to call Start. I will be working with other functions too, but I expect the answer to apply generally to all; is this a correct assumption?

easleykg

[cid:image001.png@01D08735.E70D0130]

**Comment by easleykg** [comment]
I just re-read this and you said “I can help *there*”. Sorry.
