### ISSUE TITLE
Wrong result for kwsorter-for-`call`-like function

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11149]
I was porting a version of invoke that support both keyword arguments and non-functions and came up with this problem for invoke.

Minimum working example

```julia
abstract F

call_kw(kws, ::Type{F}, args...) = (args, kws)

k() = invoke(call_kw, (Array, Type{F}, Int64), [], F, 1)

println(@code_typed k())
println(k())
println(call_kw([], F, 1))
```

Output on master
```julia
Any[:($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[Int64]], :(begin  # /home/yuyichao/tmp/julia/invoke-kw.jl, line 7:
        return invoke(call_kw,(top(apply_type))(Tuple,Array,Type{F},Int64)::Type{Tuple{Array{T,N},Type{F},Int64}},(top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1)),$(Expr(:call1, :(top(svec)), :Any, :Int)),Array{Any,1},0,0,0)::Array{Any,1},F,1)::Tuple{Tuple{Int64},Array{Any,1}}
    end::Tuple{Tuple{Int64},Array{Any,1}}))))]
((),Any[])
((1,),Any[])
```

Notice that the return value of the `k()` is wrong and it doesn't even agree with the type inference.

**Comment by yuyichao** [comment]
P.S. this does not appear on `0.3`

**Comment by yuyichao** [comment]
Actually since if I remove the `kws` in the return value of `call_kw`, i.e.
```julia
call_kw(kws, ::Type{F}, args...) = (args,)
```

The output I get is
```julia
Any[:($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[Int64]], :(begin  # /home/yuyichao/tmp/julia/invoke-kw.jl, line 7:
        return invoke(call_kw,(top(apply_type))(Tuple,Array,Type{F},Int64)::Type{Tuple{Array{T,N},Type{F},Int64}},(top(ccall))(:jl_alloc_array_1d,$(Expr(:call1, :(top(apply_type)), :Array, Any, 1)),$(Expr(:call1, :(top(svec)), :Any, :Int)),Array{Any,1},0,0,0)::Array{Any,1},F,1)::Tuple{Tuple{Int64}}
    end::Tuple{Tuple{Int64}}))))]
((140016900599538,),)
((1,),)
```

Maybe this is a gc bug?

**Comment by carnaval** [comment]
Could you have a look if #11151 fixes all your use cases ? I don't have time for real testing now, gotta get some sleep. I'm not even sure the tests run but well.

cc @JeffBezanson maybe you'd prefer if this goes through jl_method_table_insert ?

**Comment by carnaval** [comment]
(by the way good job with the "gc bug" bait ;) )

**Comment by yuyichao** [comment]
@carnaval Thanks for the fast fix. This seems to fix my example code indeed.

Still find it strange because the problem disappears if I change the number of required arguments.....

**Comment by carnaval** [comment]
The problem was that we were truncating the specialized signature to Tuple{Any,Vararg{Any}}. The vararg position doesn't match the declaration so pretty much anything can happen : you can't trust the generated code.

I'm not sure what you are wondering ? I think the bug persists with a greater number of arg. It will only trigger if the vararg is at least in position 3 though.

**Comment by yuyichao** [comment]
> It will only trigger if the vararg is at least in position 3 though.

I think this is what I was confused about. I had two test functions, one is just `f(args...; kws...)` one is `F(args...; kws...)` where `F` is a type. and the bug only happens when calling `F` with keyword arguments.

**Comment by yuyichao** [comment]
And thanks for the explaination..

**Comment by carnaval** [comment]
No problem, thanks for stress testing invoke. It's so underused that you're bound to find  some problems here :-)

**Comment by StefanKarpinski** [comment]
Maybe some more tests of `invoke` would be in order?
