### ISSUE TITLE
Missing functions to create ascii or utf8 given pointer with optional length

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11142]
There are functions for both utf16 and utf32 available:
`utf16(::Union(Ptr{Uint16}, Ptr{Int16})[, length])`
and
`utf32(::Union(Ptr{Char}, Ptr{Uint32}, Ptr{Int32})[, length])`
but there are no corresponding functions for `ascii` and `utf8`.

**Comment by stevengj** [comment]
For ASCII and UTF8, you do `bytestring(ptr, len)`

**Comment by ScottPJones** [comment]
OK, I still think it's worthwhile to provide an alias, so that people don't stub their toe looking for the versions for `ascii` and `utf8` corresponding to the `utf16`/`utf32` functions.  The name "bytestring" is confusing, because Java, Haskell, Python and other languages use that to mean just a sequence of bytes... a binary string.

**Comment by StefanKarpinski** [comment]
Yeah, it's not a great name. It would be good to reclaim it once the pervasive need to talk about things that are ASCII or UTF-8 is eliminated (after deprecation, etc.).

**Comment by ScottPJones** [comment]
I have no idea how frequently `bytestring(ptr, len)` is used by people... would you recommend I deprecate it at the same time as adding `ascii(ptr, len)` and `utf8(ptr,len)`, or add those, and leave `bytestring` until 0.5?  Thanks!

**Comment by stevengj** [comment]
The point of calling it `bytestring`, rather than `ascii` or `utf8`, is that it autodetects at runtime whether the string is ASCII.  (Of course, this means that it is not type-stable.)

**Comment by ScottPJones** [comment]
@stevengj `ASCIIString` is very important for two reasons... it performs *much* better than `UTF8String` (being a `DirectIndexedString` instead of simply `AbstractString`) in certain operations, also, in practice, I believe it is the much more frequent case than having `UTF8String`. (also, aren't we not supposed to drag in other string issues to a very specific topic ;-) ) "My inclination..."
`bytestring` in other languages just gets you the equivalent of a `Vector{UInt8}`, no particular encoding implied... (could be binary, ANSI Latin1, CP1252, UTF-8...)  I think that's what this needs...
`ascii()`, because it implies 7-bit, could actually do a validation, which `bytestring` currently doesn't do,
same with `utf8()`, and both would be type-stable, something lacking now.
