### ISSUE TITLE
calling julia from C

### ISSUE THREAD

**Issue by iceblue25** [JuliaLang/julia#11153]
Hi, I have a question about calling julia from C.

I want to call julia from  a multithreaded C program.

jl_init seems to be using some global variables which is a big problem for my design .Any alternatives where I can use a local julia object for each C thread? 

 Is there a special reason for choosing to keep the julia variables global in C?

**Comment by tkelman** [comment]
This might be a more appropriate question for julia-users. I don't think the runtime is thread-safe yet, see https://github.com/JuliaLang/julia/issues/10421. The threading branch might be in a better state for that? Not sure.

**Comment by stevengj** [comment]
No, it's not thread-safe yet.  Closing as a dup of 10421.

**Comment by iceblue25** [comment]
@stevengj I am not sure if this is a dup of 10421 since I tracked some global variables my programs call and dont seem to be the same as the ones listed in 10421.

**Comment by stevengj** [comment]
If there are globals missing from 10421, they should probably be added there.

**Comment by iceblue25** [comment]
@stevengj I am not sure if the issue refers to the same issue I have. I want to lunch independent threads running separate julia objects.

From my understanding, jl_init(NULL) initializes a global julia object. I want a local and separate julia object for each thread. That means jl_init needs to return a local object rather than initializing a global variable. I dont understand how 10421 works towards that direction. 

Maybe I misunderstand 10421.
