### ISSUE TITLE
Functions that produce results in pre-defined outputs

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#1115]
Operations like matrix multiplication, ``C = A*B``, have historically been implemented as ``C = mult(A,B)``, and this seems very natural. Below, I argue that there are numerous benefits to habitually writing our core algorithms as ``mult(C, A, B)``, where ``C`` is a pre-allocated output. Note that this issue goes far beyond matrix multiplication: taken to the extreme, one might say that the majority of function that produce any kind of "nontrivial" output (especially ones that allocate storage for that output) might be candidates for refactoring under this proposal. Of course, many areas of Julia already follow this paradigm, e.g., the I/O functions take as first input "io", which is a stream representing the output.

Here are reasons that I think we need to consider doing things this way a matter of habit:

1. Flexibility #1: first, note that ``C = mult(A, B)`` can be trivially written in terms of ``mult(C, A, B)``:

```
function mult(A, B)
    C = Array(T, size(A, 1), size(B, 2))
    mult(C, A, B)
end
```

The converse is not true: you can't write ``mult(C, A, B)`` in terms of ``mult(A, B)``, because ``mult(A, B)`` allocates the storage for its output. Putting the actual core code into the three-argument version is therefore an increase in API flexibility.

The only disadvantage is lots of little "stub" functions when we also want the two-argument version to be available. But in general we have a lot of those anyway, and they are a strength of Julia.

2. Flexibility #2: Better control over output type. For example, for handling big data, I might want the output to be a memory-mapped array. But how is a matrix-multiplication routine supposed to know that? It happens automagically for me if the output is one of the inputs.* Likewise, consider a case where an algorithm might produce results in one of two formats, say a string or a number representation of a date: if I don't want to have to re-format, I might as well have the output be an input to the function that figures out what day it is.

3. Performance: often one has to do the same computation a ridiculous number of times. Consider a case where you have to do ``det(A_i * B_i)`` for millions of small matrices ``A_i`` and ``B_i`` (applications where this arises: simulations, calculations on a grid, etc.). With the two-argument form of matrix multiplication, malloc has to be called for each intermediate value. One might imagine speed improvements using a single preallocated temporary for each intermediate result. In a test of 2x2 matrix multiplication, this trivially gets you a 3-fold speed improvement. (The fact that it's not larger is a triumph of Julia's memory management.)

4. Extensibility: there is more than a little interest in using Julia for GPU computing and in SMP multithreading. In such cases, you want to avoid calls from a thread to Julia's allocator functions. Presumably it will be easier to build kernels for such applications if more of our core computations already follow this paradigm.

Aside from encouraging this as a matter of programming style, let me bring up some of the issues worthy of discussion. We use the ``!`` convention to indicate a function that mutates its inputs, such as ``sort!``. However, this is not exactly what's happening here: in a matrix multiplication routine, ``A`` and ``B`` are not being mutated. There are also subtleties: for ``plus(C, A, B)`` it's perfectly safe to call this as ``plus(A, A, B)``, meaning the matrix version of ``A += B``. However, you can't safely do matrix multiplication in-place: the output storage has to be independent of the inputs.

In other words, we might need more conventions or notation. I'm not good at naming, but to get the discussion started, let me make a few proposals.

A. We could reserve ``!`` for its "purest" current meaning, things like in-place ``sort!``.

B. We might not need special notation for a version that allows you to supply outputs, e.g., we could have both ``C = plus(A, B)`` and ``plus(C, A, B)``, where the distinction is handled by multiple dispatch. Alternatively, would it be desirable/feasible to use function names like ``mult=(C, A, B)``, where the ``=`` indicates that the first (or first several) arguments are outputs?

C. When functions need their output storage to be independent of their inputs, they could be given names like ``mult_noalias`` (following notation used in Eigen and Boost) to indicate to the user that it's a bug to call such functions like this: ``mult_noalias(A, B, A)``.

D. Finally, there has been a proposal for operator versions like ``C .= A*B``. This kind of thing is clearly a good idea. But by now it should be clear that operators are only the tip of the iceberg---this issue permeates the entire function API.

References to previous related discussions:
https://github.com/JuliaLang/julia/issues/249
https://groups.google.com/d/topic/julia-dev/bWGWeIdhsnI/discussion
https://groups.google.com/d/topic/julia-dev/NaPxnrHtut8/discussion
Commit fc14052afa, which began the process for some of the linear algebra routines, but was horribly inconsistent in its naming scheme and needs fixing.

*Currently the calling function couldn't determine whether an array is in-memory or mapped to a file. This could potentially lead to problems from too much automagical behavior, when, for example, the best algorithm might depend upon the storage representation. But it should be clear that in general Julia's type system usually allows you to resolve such things very cleanly via multiple dispatch; memory-mapped arrays are a bit of an exception in this regard.

**Comment by simonster** [comment]
This is a very old issue. We have settled on the `!`/first argument convention. Perhaps this can be closed?
