### ISSUE TITLE
return is not an expression

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#11169]
Simple (and useless) examples:

```jl
julia> function f()
           identity(return)
       end
ERROR: syntax: misplaced return statement

julia> function f()
           x = return
       end
ERROR: syntax: misplaced return statement
```

So far, entirely pointless usages – just don't do that. But I just came across a situation where it would actually be useful to allow `return` in r-value position:

```jl
julia> function f()
           x = try something_that_might_fail()
           catch err
               warn(err)
               return
           end
           do_something_with(x)
           return
       end
ERROR: syntax: misplaced return statement
```

At first I thought this was a try-catch bug, but it's actually because `return` isn't a valid expression.

**Comment by ScottPJones** [comment]
@StefanKarpinski If `return` is not a valid expression, does that mean the part of the Noteworthy C/C++ differences section should be updated (where I’d put ‘statements’), and it was changed to ‘expressions’?

**Comment by pao** [comment]
That's the exception, rather than the rule, and this proposes changing it to not be the exception anymore.

**Comment by ScottPJones** [comment]
That's good, because many times I want to do exactly @Stefan try-catch example does...

**Comment by ScottPJones** [comment]
1) Are there any other exceptions? 2) If the Noteworthy C/C++ document is backported (for 0.3.9), should the exception(s) be mentioned?

**Comment by mbauman** [comment]
I think the only other statements in the language are `import` and `using`.

**Comment by JeffBezanson** [comment]
So should we allow `x = return`?

**Comment by yurivish** [comment]
Maybe someday that could be syntax for coroutines?

**Comment by StefanKarpinski** [comment]
Why not?

**Comment by toivoh** [comment]
So the problem here is that `return` does not return (sorry couldn't resist).

I also think that it would be OK to allow it as an expression, for consistency. Btw, wasn't that the thing holding back `@inbounds` from returning a value?

**Comment by ScottPJones** [comment]
Would this work?
```julia
@inbounds return d[i]
```
I had a number of cases where what I really needed was an `@inbounds` on an expression, that returned the expression... i.e. something like:
```julia
if @inbounds(is_valid_char(d[i]))
```
or
```julia
return @inbounds(Char(d[i])+0x0800)
```

**Comment by quinnj** [comment]
Scott,

You should be able to:

@inbounds if expr

end

or

@inbounds for i = 1:len

end

etc.

For return values, I think you need to stick with my original example

**Comment by ScottPJones** [comment]
Ok, thanks... Is there any way of wrapping a whole block of code, including returns, in `@inbounds`?

**Comment by quinnj** [comment]
Sure.
```julia
@inbounds begin
#...
end
```

**Comment by tkelman** [comment]
I wonder whether this was the cause of the problem with ProgressMeter.jl that @davidanthoff saw today? (return is maybe a weird thing to want to do at the end of a progress-metered for loop, but the failure mode was pretty strange looking and not immediately obvious)

**Comment by ScottPJones** [comment]
@quinnj Duhhh!  Where is that Unicode dunce cap emoji for me to put on?  (why they left that one out, when they added middle finger extended and Spock's `\U1f596`, I don't know!)

**Comment by simonbyrne** [comment]
One useful case for `x=return`: I wanted to replace
```julia
n = '0' <= c <= '9' ? c - '0' :
    'a' <= c <= 'f' ? c - 'a' + 10 :
    'A' <= c <= 'F' ? c - 'A' + 10 :
    break
```
with
```julia
n = '0' <= c <= '9' ? c - '0' :
    'a' <= c <= 'f' ? c - 'a' + 10 :
    'A' <= c <= 'F' ? c - 'A' + 10 :
    return Nullable{T}()
```

**Comment by samoconnor** [comment]
I have run into this problem with a macro that wraps `try`.
The macro [currently has to check if the `try` expression might return](https://github.com/samoconnor/Retry.jl/blob/master/src/repeat_try.jl#L193) and handle that case separately.

**Comment by eschnett** [comment]
There seems to be a consensus that parsing `return` as function would be beneficial.

**Comment by Ichoran** [comment]
Aside from a few parsing oddities, you can always replace `return foo` with `(return foo; Union{})`.

I guess the proposal is to make `return foo` mean the latter?  That would probably be more convenient.  But in the meantime one can use the above as a workaround.

**Comment by eschnett** [comment]
Thanks for the pointer.

`Union{}` probably doesn't do what you think it does. `Union{}` is a type, not a non-existent value. Maybe you mean `Union{}()`? You could also write `error("unreachable code") instead`.

**Comment by Ichoran** [comment]
@eschnett - Yes, sorry, typoed that.  I meant `Union{}()`.  Editing to avoid future confusion.  (Also: it's more evidence that `return` should just have bottom type.)

**Comment by mbauman** [comment]
I want to echo @toivoh's [comment](https://github.com/JuliaLang/julia/issues/11169#issuecomment-99970322): macros like `@inbounds` are a great reason to do this.  `@inbounds` currently discards its wrapped expression's value, but it'd be wonderful if we could write things like `f() = @inbounds g()`. It's an easy change to the macro:

```jl
macro inbounds(blk)
    :($(Expr(:inbounds,true));
      local val = $(esc(blk));
      $(Expr(:inbounds,:pop));
      val)
end
```

But that ends up creating a `val = return` kind of expression in some cases (e.g., [BitArray's `any`](https://github.com/JuliaLang/julia/blob/325642138749533b130576959b5177538557b62b/base/bitarray.jl#L1494-L1498)).

**Comment by eschnett** [comment]
It used to be (0.4.4):
```Julia
julia> x=return
ERROR: syntax: misplaced return statement
```

but it is now:
```Julia
julia> x=return
```

So has this been changed? Can this issue be closed?

**Comment by simonbyrne** [comment]
Maybe add a test? (so those whom giveth don't taketh away)

**Comment by mbauman** [comment]
Hooray.  Looks like it was #14997 that did this.
