### ISSUE TITLE
Range comparisons don't generate optimal code in some cases

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11174]
A common C trick to see if something is within a range is to subtract the base of the range, and use an unsigned comparison.
Julia has the nice syntax where you can say something like `0xd000 <= ch <= 0xdffff`, however,
that generates branches, instead of a simple subtraction and single comparison.

**Comment by StefanKarpinski** [comment]
This is largely an LLVM issue – the question is why LLVM doesn't transform this from branching to branch-free. It's possible that it's failing to do the transformation because it's predicting (apparently correctly) that the version with the branch is faster. It would be interesting to see if there's a situation where it would obviously be costly to have the branches and if that tips the balance. Maybe a loop that would otherwise be vectorizable?

**Comment by carnaval** [comment]
Yes, we absolutely have to get the branched version to LLVM, in case someone overloaded `<=` and the comparison is actually costly. I'm also wondering whether it will switch to a branchless version if inside a vectorizable loop.

**Comment by simonster** [comment]
LLVM does indeed appear to optimize this in the vectorized branch of the following function:

```julia
function f(x)
    z = 0
    for i = 1:length(x)
        @inbounds z += 0xd000 <= x[i] <= 0xdffff
    end
    z
end
```

(IR omitted here, but you can get it with `code_llvm(f, (Vector{UInt},))`.)

**Comment by ScottPJones** [comment]
@StefanKarpinski It's not predicting correctly as far as I can tell... and it really just depends on your inputs... if the inputs are skewed heavily, of course modern processor's branch prediction circuitry may make that faster than the subtract/compare approach... but how could Julia know that the input is going to be skewed or random?  Maybe it needs to be told?  Like `@inbounds` made my code way faster?

**Comment by StefanKarpinski** [comment]
I'm not sure what levers we have to force LLVM to change the way it chooses to optimize this. I'm also not sure we want to get into the game of micromanaging LLVM optimizations.

**Comment by mbauman** [comment]
There's been some discussion of an `@unlikely` macro  (https://github.com/JuliaLang/julia/issues/9077#issuecomment-63908815) previously.  That doesn't quite cover this case though… what you really want is an `@unpredictable` notation.

**Comment by ScottPJones** [comment]
For Unicode, it may even be (as long as you're not in Japan!) that branch if ch < 0xd800 first, and *then* doing the trick to see if it's in the range 0xe000 to 0x10ffff, might be the fastest for most input...
It seems though that I still need to use my old C tricks for best performance (esp.  where I know in advance something about the input data)...

**Comment by pao** [comment]
`ifelse(0xd000 <= ch, ch <= 0xdffff, false)`?

**Comment by simonster** [comment]
@pao That works, but `(0xd000 <= ch) & (ch <= 0xdffff)` seems a bit clearer.

If we wanted to do this by default, I think we could lower `a <= x <= b` etc. to calls to `<=(a, x, b)` and then define branchless methods for Ints etc. and a fallback method that does `(a <= x) && (x <= b)`, but I do kind of wonder why LLVM doesn't eliminate the branch.

**Comment by carnaval** [comment]
Well if the backend figures it out for the vectorized case then I think we can trust it. The branchy version is more general because I think llvm will never do the reverse transformation. (e.g. if some place is very ALU bound the branch may very well make a lot of sense)

If you happen to know that the frequency of the data makes the branchless version faster, it is easy enough to write explicitly. I'm gonna close this.

**Comment by pao** [comment]
> That works, but (0xd000 <= ch) & (ch <= 0xdffff) seems a bit clearer.

Good point. I mentally have associated `ifelse` with "avoid branches" but I should keep in mind that `&` would have the same effect.

**Comment by mbauman** [comment]
I have a hunch that @ScottPJones' original optimization may be faster than either of the options y'all have been discussing:

```julia
inrange(lo, x, hi) = (x % UInt) - (lo % UInt) <= (hi % UInt) - (lo % UInt)
```

```llvm
julia> @code_llvm inrange(1,2,3)

define i1 @julia_inrange_136707(i64, i64, i64) {
top:
  %3 = sub i64 %1, %0
  %4 = sub i64 %2, %0
  %5 = icmp ule i64 %3, %4
  ret i1 %5
}
```

Two subtractions (but it inlines, so it could possibly constant fold the one) and a comparison.

**Comment by simonster** [comment]
Isn't @ScottPJones's original optimization what LLVM does for this:

```julia
julia> f(ch) = (0xd000 <= ch) & (ch <= 0xdffff);

julia> code_llvm(f, (UInt,))

define i1 @julia_f_227903(i64) {
top:
  %.off = add i64 %0, -53248
  %1 = icmp ult i64 %.off, 864256
  ret i1 %1
}
```

**Comment by carnaval** [comment]
Definitely. LLVM is usually really good at this kind of peephole optimizations.

**Comment by quinnj** [comment]
OT:
Can I just say how cool it is that we can all throw LLVM IR and assembly around comparing various compiler optimizations/passes in the blink of an eye? Maybe I don't hang around "technical" enough software forums, but find me another "high-level dynamic" language forum where this kind of insight and analysis is as trivial or common! It's still one of my favorite things about Julia.

**Comment by mbauman** [comment]
Oh, interesting.  In my tests I wasn't using constants:

```julia
julia> inrange2(lo, x, hi) = (lo <= x) & (x <= hi);

julia> @code_llvm inrange2(1, 2, 3)

define i1 @julia_inrange2_136725(i64, i64, i64) {
top:
  %3 = icmp sle i64 %0, %1
  %4 = icmp sle i64 %1, %2
  %5 = and i1 %3, %4
  ret i1 %5
}
```

**Comment by ScottPJones** [comment]
@carnaval Isn't it a bit premature to close?  Should the default be to assume that the input will be skewed, and the branch predictor will be able to make some cases with branching faster?  Maybe look at benchmarking before closing?  If Julia can't do better than me, then I'm going to feel obligated to go through all of the code in `char.jl`, `string.jl`, and `utf*.jl`) where it is using these range comparisons and try to fix them up! :wink: (after benchmarking, of course!)

**Comment by ScottPJones** [comment]
OT: @quinnj This discussion just makes me think of the Heinlein short story... http://en.wikipedia.org/wiki/Time_Enough_for_Love#The_Tale_of_the_Man_Who_Was_Too_Lazy_to_Fail
I'm completely convinced that all of the Julia contributors are incredibly lazy!  (before yelling at me, please follow the link, if you haven't already read the story!)

**Comment by carnaval** [comment]
My reason for closing is that LLVM demonstrated that it is perfectly capable of doing the transformation branch => branchless when it is obvious that it is needed (i.e., to vectorize a loop). I'm almost certain that there is no pass which introduce branches in branchless code so, given that : 
- either can be good depending on the input
- you can express the more specific version quite easily
- LLVM will do the right thing for the clearly better case
- it has access to more information than us poor humans on the CPU's scheduling and the decision could depend a lot on the surrounding code

I think the best way is just to let LLVM pick for us in all cases, with of course the option to manually benchmark and explicitly turn to the branchless version in cases where the codegen got it wrong.

For example, if one of your bound is loaded from memory, the branch cost is negligible compared to the gain of not hitting a possible cache miss. Defaulting to the branchless version makes you load memory everytime.

**Comment by ScottPJones** [comment]
@carnaval Good points!  Thanks, I guess... :grin: now you've made me want to test and rewrite the char/string cases that will do better branchless...
