### ISSUE TITLE
Setting, accessing empty environmental variables causes an error

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#11170]
```
julia> ENV["R_DOC_DIR"] = ""
""

julia> ENV["R_DOC_DIR"]
ERROR: system error getenv: R_DOC_DIR 1-1 != 0: The wait operation timed out.
 in error at error.jl:21 (repeats 2 times)

julia> versioninfo()
Julia Version 0.3.8
Commit 79599ad (2015-04-30 23:40 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by StefanKarpinski** [comment]
Seems to be Windows-only (as indicated).

**Comment by tkelman** [comment]
This ccall https://github.com/JuliaLang/julia/blob/de6e41fae8a71fd94f06d1462ad1bf2d4a9b31c0/base/env.jl#L33 returns 0 for an environment variable set to empty, but `len` there is 1 (only counting the terminating null). Ref https://msdn.microsoft.com/en-us/library/windows/desktop/ms683188%28v=vs.85%29.aspx

Maybe we change the error condition there to something like `if (ret==0 && len!=1) || ret != len-1 || val[end] != 0` ?
