### ISSUE TITLE
It's too easy to pass large tuples by value

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11187]
Passing large tuples around in julia 0.4 will try to pass them by value which makes LLVM unhappy. We should pass them by pointer before LLVM gets to them. @vtjnash @JeffBezanson

**Comment by oxinabox** [comment]
With this now closed, does that mean *all* tuples are passed by reference now? Or just large ones?

**Comment by ArchRobison** [comment]
Appears to be all tuples.  Even tiny ones.
```
julia> foo(x) = x
foo (generic function with 1 method)

julia> code_llvm(foo,(Tuple{Int8},))

define [1 x i8] @julia_foo_21494([1 x i8]*) {
top:
  %1 = load [1 x i8]* %0, align 1
  ret [1 x i8] %1
}
```
See also #11899.  My impression is that we should pass small homogeneous tuples by value and as LLVM vectors instead of LLVM arrays.

**Comment by ScottPJones** [comment]
If all tuples are passed by reference, won't that have a serious performance effect? (badly, for small tuples)

**Comment by vtjnash** [comment]
> If all tuples are passed by reference, won't that have a serious performance effect? (badly, for small tuples)

empirically, no, since that is what it is doing now. the inliner should take care of any place where the overhead would significantly matter, and it can improve performance by reducing register pressure near call sites (as stated in the motivation for #11899)

**Comment by ArchRobison** [comment]
On the register pressure issue, I suspect it's dependent on the tuple's type and target architecture.  If the tuple fits in a vector register, then passing it by value uses one register, and passing it by reference uses one register.  Of course empirical evidence gets last say on performance.

**Comment by ScottPJones** [comment]
Yes, and passing a small immutable tuple by reference means you just have to fetch it from memory later on, which can affect what you've got in caches.  A single AVX-512 register == 1 64 byte cache-line.
Right now, the memory allocation in julia lets small things straddle cache-line boundaries, so being able to keep small <= 64 byte things in registers could save two memory accesses (and using up 2 L1/L2 cache "slots")

**Comment by carnaval** [comment]
LLVM is well aware of this so I'd rather leave the decision to the backend where possible. Anyway, this kind of calls would rather be made on a per-tuple basis instead of for the whole type so we need Jameson's rewrite anyway.
