### ISSUE TITLE
base/fs.jl: function sendfile broken

### ISSUE THREAD

**Issue by thraen** [JuliaLang/julia#11191]
Hi!

In version 0.4.0-dev+4706 there seems to be an issue with the function sendfile in base/fs.jl:
You can reproduce this with:
```mv("dir", "dir_on_other_mountpoint")``` where dirs are on different mountpoints 

this results to:

ERROR: sendfile: illegal operation on a directory (EISDIR)
 in sendfile at fs.jl:149
 in rename at fs.jl:123
 in mv at file.jl:118

In this case the rename-ccall in mv (or FS.rename) fails, because of the different mount points which seems to be normal. Rename then falls back to sendfile+unlink, but the ccall to sendfile also fails with EISDIR.
This is strange since EISDIR is not a valid errno for sendfile according to man.

**Comment by thraen** [comment]
julia> versioninfo()
Julia Version 0.4.0-dev+4706
Commit 0aa5cd3* (2015-05-07 13:51 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7- 8837  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tkelman** [comment]
I think this will be fixed by #11172, right @peter1000?

**Comment by peter1000** [comment]
I hope so - the current `mv` method falls back to sendfile if `rename` failed -  #11172 calls in such case the new `cp` methods which should work proper on directories too. 

https://github.com/JuliaLang/julia/pull/11172/files#diff-ddd5b269fd4dc0426fb08e3fe9b4b65fR121

**Comment by thraen** [comment]
This actually breaks Pkg.init() for fresh installations

**Comment by jakebolewski** [comment]
Closing this as fixed? @thraen please comment if this is not true.
