### ISSUE TITLE
need mechanism to deprecate bindings

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#11200]
While we can deprecate functions, our current mechanism to deprecate types is to define the equivalent of
```jl
export Range1
const Range1 = UnitRange
```
This does not trigger any deprecation warning for using the type itself. #11046 was therefore more disruptive than one might have ideally wished (see https://github.com/JuliaLang/Tk.jl/pull/98 and cascading breakages in any package that depends on it, plus at least https://github.com/timholy/ProfileView.jl/pull/32), in that it caused actual package breakages. If we'd had a deprecation system in place, the appropriate changes could have been made any time in the past year.

I presume this is something that needs to be handled at the parser level?

(Off-topic: should we have a "wishlist" label as distinct from bug reports?)

**Comment by jakebolewski** [comment]
You can't really do this at the parser level because it is perfectly valid to use the name of a Type as a local variable.

```julia
julia> type MyType
       x::Int
       end

julia> let MyType = 1
       @show MyType
       end
MyType = 1
1

julia> MyType(10)
MyType(10)
```

**Comment by timholy** [comment]
Good point. Thanks for taking that label off.

**Comment by jakebolewski** [comment]
But I agree this is big problem that will trigger all sorts of compatibility issues going forward.

It makes it impossible to implement improvements such as https://github.com/JuliaLang/julia/issues/8240 because the result will be backwards incompatible with no clear deprecation path.

**Comment by StefanKarpinski** [comment]
This has come up before, what's really needed it seems, is to have a deprecated export mechanism, where a name can be made available, but using it triggers a warning in the other module.

**Comment by StefanKarpinski** [comment]
That distinction would be more broadly useful: e.g. if two module both export names but one of the exports is deprecated, maybe the non-deprecated name should win? It would also be nice not to tab complete deprecated names and methods.

**Comment by ScottPJones** [comment]
:+1: @StefanKarpinski Any how hard to implement deprecated export mechanism, allowing non-deprecated name to win, and no tab completion?

**Comment by StefanKarpinski** [comment]
It would be a fair amount of work that not very many people could do.

**Comment by ScottPJones** [comment]
@StefanKarpinski Be careful about making challenges like that! :grinning:

**Comment by StefanKarpinski** [comment]
Well, I'd be happy for anyone to do it, but it just involves a whole lot of Julia blood and guts.

**Comment by ScottPJones** [comment]
Julia blood and guts?  But, that's the most fun part, for an old language design / compiler guy like me! :grinning:  Seriously, if you already know approximately what areas would need to be dug into, and could point them out, then that's something else where I might be able to take a crack at it...

**Comment by jiahao** [comment]
#9830 is a special case of this problem, I think.

**Comment by StefanKarpinski** [comment]
Changed title to reflect that what's mostly needed is a mechanism to deprecate bindings.

**Comment by tkelman** [comment]
backported in #13107
