### ISSUE TITLE
Running on 64bit system with virtual memory constraint.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11201]
I was trying to compile and test the current master on `x.dialup.mit.edu` and noticed that it fails to run because of what looks like hittng a limit in virtual memory when allocating the pool. Changing `REGION_PG_COUNT` to the value for 32bits fixes the issue.

It would be nice if this value can be either specified as an option at compile time or, even better, being able to fallback to a smaller value at runtime when mmap fails.

**Comment by simonster** [comment]
Dup of #10390?

**Comment by yuyichao** [comment]
Yes.
