### ISSUE TITLE
Improve memory debugging docs

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11214]
Currently we have a section in the docs about running Julia under Valgrind.  Following discussion [here](https://github.com/JuliaLang/julia/pull/11205#issuecomment-100410437), I'd like to see these docs expanded into a section on memory debugging more generally.  I think the subsections should include:
1. Brief intro (including `MEMDEBUG` and `MEMDEBUG2` flags)
2. Using Valgrind with Julia
3. Using AddressSanitizer/MemorySanitizer with Julia
4. `GC_VERIFY` (including information on how it acts with the tools above)

**Comment by garrison** [comment]
The [comments here](https://github.com/JuliaLang/julia/blob/220801bb22e257ab2af1fd379ae015d37c1fe064/src/gc.c#L1919-L1937) by @carnaval can form the start of the `GC_VERIFY` docs.  I think it also makes sense to include some of the information from [this thread](https://github.com/JuliaLang/julia/pull/11151#issuecomment-99855557) (and perhaps we should make it more straightforward to configure the GC in these more rigorous ways).  Is there anything else that should go in a preliminary version of the `GC_VERIFY` docs?

**Comment by garrison** [comment]
CC @yuyichao

**Comment by vtjnash** [comment]
I don't think we need to track this in an issue, as I think we have (independent of the issue) improved this.
