### ISSUE TITLE
Strange <BLANKLINE> output in backtrace

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#11225]
This doctest in control-flow.rst now produces:

```jl
    julia> f(x) = x>=0 ? exp(-x) : throw(DomainError())
    f (generic function with 1 method)

    julia> f(1)
    0.36787944117144233

    julia> f(-1)
    ERROR: DomainError
    <BLANKLINE>
     in f at none:1
```

the `<BLANKLINE>` is new is 0.4.

**Comment by MurrayT** [comment]
I think it may be with the way that the printing of the traceback works.
`showerror(io::IO, ex::DomainError, bt)` in `replutil.jl` (line 96) calls `println(io, "DomainError:")` as the first line. This obviously adds a newline character to the IO stream. If the error has further details the last line is printed using only a `print` call. If not the newline character is hanging around at the end of the stream. 
`show_backtrace(bt)` is called at the end of the `showerror` function, this calls `show_trace_entry` for every trace entry back to the desired point.

If we look at `function show_trace_entry(io, fname, file, line, n)` in `replutil.jl` (line 314) the first thing printed in this function is a newline (`\n`) character. This means that if the `DomainError` has no additional info the IO stream has two consecutive newline characters, leading to the observed behaviour.

One potential resolution path is to modify the `showerror(io::IO, ex::DomainError, bt)` as follows

```julia
function showerror(io::IO, ex::DomainError, bt)
    print(io, "DomainError:")
    for b in bt
        code = ccall(:jl_lookup_code_address, Any, (Ptr{Void}, Cint), b, true)
        if length(code) == 5 && !code[4]  # code[4] == fromC
            if code[1] in (:log, :log2, :log10, :sqrt) # TODO add :besselj, :besseli, :bessely, :besselk
                println(io,"\n$(code[1]) will only return a complex result if called with a complex argument.")
                print(io, "try $(code[1]) (complex(x))")
            elseif (code[1] == :^ && code[2] == symbol("intfuncs.jl")) || code[1] == :power_by_squaring
                println(io, "\nCannot raise an integer x to a negative power -n. Make x a float by adding")
                print(io, "a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n")
            end
            break
        end
    end
    show_backtrace(io, bt)
end
```

Moving the newline character from the end of the first print call should resolve the issue without causing any new errors elsewhere.
