### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by mAch17** [JuliaLang/julia#11221]
I get an UndefVarError here, which I feel is not very informative.
julia> for i in 1..2
       println(i)
       end
ERROR: UndefVarError: .. not defined
 in anonymous at no file

Using Version 0.4.0-dev+4248 on windows

**Comment by kmsquire** [comment]
@mAch17, can you provide a suggestion for a more informative error here?  The problem is that, while `..` parses, it isn't actually defined.

**Comment by ScottPJones** [comment]
I would have expected more some sort of "Undefined operator" error (since .. is in the table of operators).

**Comment by toivoh** [comment]
By the time it's time to look up the definition for `..`, it's no different to any other identifier, so I'm not sure that calling it an undefined operator would always be less confusing. But couldn't we at least have some kind of quoting, eg

    ERROR: UndefVarError: `..` not defined

I'm getting some kind of deja vu feeling here, haven't we gone through error messages to make that kind of change some (long?) time ago?

**Comment by ScottPJones** [comment]
Since this is just an error message, and not performance critical, couldn't it just check to see if the string were in the operator table, and give a somewhat more understandable error message?

**Comment by mAch17** [comment]
If we can somehow catch it with the standard  error as we do in Unary Operator, `ERROR: syntax: ".." is not a binary operator`, it would be the best from what I can think.

**Comment by JeffBezanson** [comment]
`..` *is* a binary operator, it's just not defined.

**Comment by ScottPJones** [comment]
Right, but the message "UndefVarError", while technically correct, is confusing.
Any "UndefVarErrors", where the symbol is in the operator table, should give instead an error like:
`ERROR: Operator `..` not defined`.  That's what I meant.

**Comment by fcard** [comment]
@mAch17's problem here seems like that he came from some other language that uses `..` as special syntax for ranges (ruby?). Couldn't Julia just warn about it like it does with `**`? At least when `..` isn't defined, on top of the `undefined` error.

@ScottPJones Not sure if it would be super useful for other operators. Is there any other undefined common binary operator that newcomers could stumble into? What would be another example of someone seeing an `UndefVarError` and not having any sort of clue of what to do next?

**Comment by ScottPJones** [comment]
I think there are potentially lots of them... for example, `++` for people coming from Haskell, where it means string concatenation... I don't know if that's been added to the operator table yet, but people are thinking about it...

**Comment by fcard** [comment]
I see. Well, warning about every operator individually would be impractical and not really Julia's obligation, so... (I get that it warns about `**` because it targets people from python, it's that, if it was just *one* more...)

I think the confusion comes from the fact that people expect operators to be special forms when they're just variables, so when they get `UndefVarError`, they don't make the connection that they need to define the operator first, as it's not a possibility elsewhere. If the error just says `operator not defined`, they may still not realize that. Yeah, I think this may be a job for the docs, rather than the errors.

(Also, in the case of haskell, don't they already get similar error messages anyway?

```haskell
Prelude> 10 ++++ 20

<interactive>:2:4: Not in scope: `++++`
```
)

**Comment by jakebolewski** [comment]
`..` is an operator, but also a valid identifier: 

```julia
julia> .. = 1
1
julia> ..
1
``` 
so I don't think our error message can really be more detailed here.
