### ISSUE TITLE
parsing issue?

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#11222]
Discovered by  Bernie Wang:

The ```for``` syntax ending in a comma is invalid syntax
but the first code below yields the scalar 5.0 while the 
second correctly gives invalid syntax

```
a = zeros(2)
for i=1:5,
    a  +=  [1,1]
end
a
```
```
a = zeros(2)
for i=1:5,
    a  = a + [1,1]
end
a

**Comment by JeffBezanson** [comment]
This is because you can write multiple ranges in a `for` loop, as in `for i = 1:n, j = 1:m`. If it sees a comma, it keeps looking until it finds the next range specification. So this is actually doing `for i in 1:5, a in a+[1,1]`. The other one is a syntax error because a for loop range has to match `x in y` or `x = y`, not `x += y`.

**Comment by ViralBShah** [comment]
Do we give a reasonable error here?

**Comment by lostanlen** [comment]
It's the opposite actually: the first one (a += [1,1]) is an error whereas the second one (a = a + [1,1]) silently returns 5.0.
The error raised is 
"ERROR: syntax: invalid iteration specification"
(triggered at https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L1368),
which looks reasonable.

**Comment by ScottPJones** [comment]
Ah... I was looking for something like this, however, I was trying `for i = 0:0xd7ff, 0xe000:0xffff` which didn’t work...  is there any reason the parser couldn’t handle variable = ...list of values or ranges...
also?

**Comment by StefanKarpinski** [comment]
This seems like a busywork issue. If you enter something that's syntactically valid but not what you intended to input, what can the parser possibly do about it?

**Comment by jakebolewski** [comment]
Nothing.
