### ISSUE TITLE
Vectorized code performance

### ISSUE THREAD

**Issue by floriandevuyst** [JuliaLang/julia#11220]
Hi,

I have developed a structured 2D hydrocode in Julia. The code has been array-vectorized.
Performance is not so bad, but below Matlab. Typical instruction lines for such computational codes are : 

 const LEFT = [1, 1:N];
 const RIGT = [1:N, N];
...
up = max(u_intx, 0.0);
phix_rho   = rho_lag[LEFT, :] .* up + rho_lag[RIGT, :] .* (u_intx-up);
 ...
 U.rho    = U.rho - (dt/h) * (phix_rho[2:N+1, :] - phix_rho[1:N, :]) - (dt/h) * (phiy_rho[:, 2:N+1] - phiy_rho[:, 1:N]);

How to improve performance ? Is it scheduled in the next releases to improve array-based vector code ?

Best regards, florian

**Comment by floriandevuyst** [comment]
NB : I can let the code to Julia core developers as a miniapp for performance assessment and LLVM improvement in you want,

Regards, florian

**Comment by timholy** [comment]
This is better posted as a question on julia-users. See the many existing pull requests on arrays, and #7941.

**Comment by JeffBezanson** [comment]
See also #1168

**Comment by floriandevuyst** [comment]
Thank you for the link,

Regards, florian
