### ISSUE TITLE
Weird printing of `BoundsError()``

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11245]
```julia
julia> throw(BoundsError(linspace(1, 2, 3), 0))
2.03ERROR: BoundsError: attempt to access linspace(1.0,,)
  at index [0]
```

~~Note the extra "2.03" before "ERROR"~~

Edit: Seems that `2.0` and `3` are printed to the wrong place

**Comment by yuyichao** [comment]
Noticed when testing #11244

**Comment by vtjnash** [comment]
fixed by 35cdca9669dbb5b46f086954eedaa50cba1fe26a

**Comment by yuyichao** [comment]
I'm surprised that mentioning in the commit message doesn't close the issue automatically....

**Comment by jakebolewski** [comment]
@yuyichao you have to write "fixes #<issue number>" or "closes #<issue number>"

**Comment by yuyichao** [comment]
= = Got it. I just didn't feel like repeating "Fix" twice just now .....

**Comment by vtjnash** [comment]
sometimes it requires creative writing to get the word "fix" or "close" in just the right position in the sentence :)
