### ISSUE TITLE
Markdown lists do not interrupt paragraphs

### ISSUE THREAD

**Issue by jayschwa** [JuliaLang/julia#11249]
In most Markdown implementations I've used
```
My List:
* Item 1
* Item 2
```
renders as

> My List:
> * Item 1
> * Item 2

However, doing that in a `@doc` string displays as
> My List: * Item 1 * Item 2

The [CommonMark spec](http://spec.commonmark.org/0.18/#example-206) says that no blank lines should be required between a paragraph and list.

Blockquotes do seem to interrupt paragraphs, so maybe that's a lead on how to do the same for lists.

**Comment by IainNZ** [comment]
Definitely a nice detail - StackOverflow requires a blank line, and its quite annoying.

**Comment by jakebolewski** [comment]
CrossRef  #12936

**Comment by StefanKarpinski** [comment]
@MichaelHatherly: is this fixed?

**Comment by MichaelHatherly** [comment]
> is this fixed?

[Yes](https://github.com/JuliaLang/julia/pull/18229) :)

**Comment by KristofferC** [comment]
Not merged yet. Will be auto closed when the PR is merged.
