### ISSUE TITLE
`a * n == a / n` For `UnitLowerTriangular` and `UnitUpperTriangular`?

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11256]
Come across this when checking the code for #11253. See [code here](https://github.com/JuliaLang/julia/blob/e2dbab5188b2219f4036cd076b23363000deed9b/base/linalg/triangular.jl#L302-L317), which seems wierd to me in many ways (it compute a invx but never used and it calculate the product instead of the quotient)

Is this expected (I hope not?) @andreasnoack 
```julia
julia> a = LinAlg.UnitUpperTriangular([1 2; 3 4])
2x2 Base.LinAlg.UnitUpperTriangular{Int64,Array{Int64,2}}:                        
 1  2                                                                             
 0  1                                                                             
                                                                                  
julia> a * 0.5
2x2 Base.LinAlg.UpperTriangular{Float64,Array{Float64,2}}:                        
 0.5  1.0                                                                         
 0.0  0.5                                                                         
                                                                                  
julia> a / 0.5
2x2 Base.LinAlg.UpperTriangular{Float64,Array{Float64,2}}:                        
 0.5  1.0                                                                         
 0.0  0.5                                                                        
```

**Comment by StefanKarpinski** [comment]
Seems pretty clearly to be a bug. I also think that multiplying by the inverse is not a good idea since that's generally not computationally equivalent to division. If that optimization is acceptable, it's easy enough for the user to write `A * inv(x)` instead of `A / x`.

**Comment by yuyichao** [comment]
I think the `invx` is supposed to be used only for filling the diagonal elements and the multiply should be replaced with division.

**Comment by andreasnoack** [comment]
Yes. It is a bug. It should be `invx` and @yuyichao is is right, the use of `inv` is necessary for filling the diagonal elements because the unit elements in the diagonal are only implicitly defined by the type.

**Comment by yuyichao** [comment]
@andreasnoack Just curious. Will it be faster to only loop through the uppler/lower elements instead of using `A.data * x` (also for many other functions in this file)?

**Comment by andreasnoack** [comment]
Tests are only useful when they are correct. I was pretty sure this was tested, but a closer look at

https://github.com/JuliaLang/julia/blob/e2dbab5188b2219f4036cd076b23363000deed9b/test/linalg/triangular.jl#L103

reveals the uselessness of the test.

**Comment by andreasnoack** [comment]
@yuyichao I haven't timed it carefully, but the reason I'm scaling all elements is that it can be done with linear indexing and no branches. Therefore, I expected the operation to be vectorized by LLVM.

**Comment by yuyichao** [comment]
I see.

**Comment by andreasnoack** [comment]
@yuyichao Thanks for catching this.

**Comment by yuyichao** [comment]
=)
