### ISSUE TITLE
julia uses an absolute path

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#11270]
when you build julia from git, it seems that the julia command in the top level is linked to an absolute path that is equivalent to ./usr/bin/julia.

please don't do that (use an absolute path), because if someone is dumb enough to move the directory, and then build a new julia version, in a directory with the same name, all kinds of confusion can break out.  yes, i  am that dumb person, but i cannot see why a relative path wouldn't have sufficed.

thanks!

**Comment by staticfloat** [comment]
@andrewcooke would https://github.com/JuliaLang/julia/pull/11272 fix it for you?

**Comment by vtjnash** [comment]
build directories are non-relocatable and can do all sorts of a bad things if you try. for example, any autoconf or cmake driven dependency will use the absolute path to the original location and may discard anything that it finds there.

**Comment by staticfloat** [comment]
For the record, while I agree with Jameson, I also agree that it's a very simple thing to fix, and there's no good reason in my mind why we shouldn't make it a relative path.

**Comment by andrewcooke** [comment]
it does, but tbh i'd rather it breaks in an obvious way rather than have some weird problem as described by vjnash.

although i am a little surprised - i use autoconf quite a bit and thought it used relative paths.

anyway, seems like a bad idea.  sorry/thanks.  andrew

**Comment by staticfloat** [comment]
For others reading this, things that won't work are moving the directory tree, and then expecting a `git pull && make` to work; `./configure` scripts generate makefiles that have full paths hardcoded into them which makes this kind of relocation very difficult in general.

Things that should work are moving the `usr` directory generated by building Julia.  We work pretty hard to make that relocatable, and even provide an official method of moving it into whatever directory you want, with a very flexible directory structure.  See [these lines](https://github.com/JuliaLang/julia/blob/master/Make.inc#L96-L107) for an example of the parameters you can set.  You'd install julia into your own directory structure via something like:

```
$ make prefix=/my/own/prefix libdir=/oh/but/libraries/go/here install
```

99% of the time, `prefix` is the only thing you care about.  I'd say the next most often tweaked thing is `datarootdir`, but I don't have hard data for that.

**Comment by andrewcooke** [comment]
fwiw, it seems to be the handwritten Makefile in deps that is the source of the absolute paths.
