### ISSUE TITLE
Make enum values comparable to integers (or in general to underlying value type)

### ISSUE THREAD

**Issue by wildart** [JuliaLang/julia#11275]
Enums are generated based on integer sequence, but these values cannot be compared with integers.
```julia
julia> @enum ABC a b c=4
julia> c == 4
false
julia> c.val == 4
true
julia> Int(c) == 4
true
```
It would be more natural for enum values to have this comparison without an additional conversion to integer.

**Comment by vtjnash** [comment]
enum's are not integers

https://docs.python.org/3/library/enum.html
http://docs.oracle.com/javase/6/docs/api/java/lang/Enum.html#ordinal()
https://msdn.microsoft.com/en-us/library/2dzy4k6e.aspx (if i'm reading this correctly, C++11 is trying to break with the C legacy of enum values not having their own types?)

---

related, pointers are not integers:
```
julia> 0 == C_NULL
false
```
so why are characters integers:
```
julia> 0 == '\0'
true
```

**Comment by wildart** [comment]
I am not saying that enums are integers. My question about comparisons to integers.

https://docs.python.org/3/library/enum.html#intenum
http://stackoverflow.com/questions/301622/c-enum-to-unsigned-int-comparison

in MSDN link you gave, under "Casting rules":
> Unscoped enum constants can be implicitly converted to **int**.

I think it would be natural to compare enum values to integers.

**Comment by quinnj** [comment]
I'm not sure I have a strong opinion here, but I could also see an argument the other way; perhaps you *don't want* enums comparable to integers because it may lead to subtle situations where allowing it causes unexpected behavior.

Particularly in light of some recent discussions on automatically trying to convert keyword arguments to their declared type.

**Comment by vtjnash** [comment]
> https://docs.python.org/3/library/enum.html#intenum

the python docs for intenum spend almost as much text telling you to never use them as they do telling you how they work

> http://stackoverflow.com/questions/301622/c-enum-to-unsigned-int-comparison

C++ has typically been restricted by compatibility with C. so most of the time they are stuck with the existing behavior

**Comment by wildart** [comment]
I think I put a strong condition, comparable to integers. How about to underlying value type?

I looked up at how enums created. Each enum type object, has `val` field with a type identified during enum declaration. Can enum values be comparable to that type?  How about to add following to enum type declaration?
```julia
isequal(e::Enum, i::$enumT) = e.val == i
isequal( i::$enumT, e::Enum) = e.val == i
```

**Comment by JeffBezanson** [comment]
I'm going to say no, enums are not integers.

**Comment by mauriciogracia** [comment]
using `IntEnum `allows python enums to be compared to ints, thanks for that answer @vtjnash
