### ISSUE TITLE
Printing of BigFloat's and Complex{BigFloat}'s

### ISSUE THREAD

**Issue by pabloferz** [JuliaLang/julia#11276]
Currently the printing of `Complex{BigFloat}`'s is like this
```julia
julia> big(1.) + 2im
1e+00 with 256 bits of precision + 2e+00 with 256 bits of precisionim
```
which is bad.

I have some proposals to improve this.

(1) Make `Complex{BigFloat}` print like
```julia
julia> big(1.) + 2im
1e+00 with 256 bits of precision + 2e+00im with 256 bits of precision
```
(2) Make `BigFloat`'s print the precision info inside parenthesis as
```julia
julia> big(1.)
1e+00 (with 256 bits of precision)
```

and then display `Complex{BigFloat}` as one of the following

(a)
```julia
julia> big(1.) + 2im
1e+00 (with 256 bits of precision) + 2e+00 (with 256 bits of precision) * im
```
(b)
```julia
julia> big(1.) + 2im
1e+00 (with 256 bits of precision) + 2e+00im (with 256 bits of precision)
```

Personally, I find better options (2) and (b). If there is an agreement I can submit a PR based on that decision

**Comment by jakebolewski** [comment]
i think you should just print out the precision once in the complex case.  I don't think the two should (can?) be divergent.

**Comment by pabloferz** [comment]
You are right, I believe they even cannot be different. So a better option would be

```julia
julia> big(1.) + 2im
1e+00 + 2e+00im (with 256 bits of precision)
```

**Comment by jiahao** [comment]
```jl
julia> Complex{Real}(1//3, big(2.0))
1//3 + 2e+00 with 256 bits of precisionim
```

**Comment by pabloferz** [comment]
So, it would only make sense un the case both are `BigFloat`, ti supress the redundancy then.

**Comment by StefanKarpinski** [comment]
How about we just stop printing out the precision altogether?

**Comment by pabloferz** [comment]
:+1:

That would make the displaying of BigFloat's cleaner.

**Comment by ScottPJones** [comment]
Is there a function that returns the precision?  (that would be useful for a "BigDecimal" as well...)

**Comment by pabloferz** [comment]
@ScottPJones Something like `precision` and `get_bigfloat_precision`?

```julia
julia> precision(big(1.0))
256
```

```julia
julia> get_bigfloat_precision()
256
```

**Comment by ScottPJones** [comment]
Perfect, then I'd agree with @StefanKarpinski, and just get rid of the extra print out...

**Comment by tkelman** [comment]
Should we at least print BigFloats as `BigFloat(2.0)` so it's visually apparent that the value is a different type?

**Comment by ScottPJones** [comment]
Well, you might want it to be BigFloat("2.0"), so that you can cut & paste...

**Comment by tkelman** [comment]
Yeah, I'm not sure whether the Julia version of grisu can determine the needed number of digits for BigFloats. cc @quinnj ?

**Comment by quinnj** [comment]
Hmmm...I'm not really sure. BigFloats have always used their own `print`ing functionality from MPFR, so I'm not sure how grisu would help here.

**Comment by pabloferz** [comment]
In my opinion the format used by MPFR makes it usually easy to distinguish between Float64 and BigFloat.

```julia
julia> print(2.0)
2.0
julia> print(big(2.0))
2e+00
julia> print(1.0*pi)
3.141592653589793
julia> print(big(pi))
3.141592653589793238462643383279502884197169399375105820974944592307816406286198e+00
julia> print(0.1)
0.1
julia> print(big(0.1))
1.000000000000000055511151231257827021181583404541015625e-01
julia> print(2.1e-10)
2.1e-10
julia> print(big(2.1e-10))
2.0999999999999999860347348645578553771873231426070560701191425323486328125e-10
```

Anyway one could add something like a `b` at the beginning or a `b0` at the end of the number (the last one might look really bad, but I'm just throwing some ideas into the discussion).

**Comment by ScottPJones** [comment]
@pabloferz You are getting the strange numbers there because you are not doing big"2.1e-10”, which would give you “2.1e-10 with 256 bits of precision”, but rather passing a Float64 (because Julia converts everything that looks like it is floating point to a Float64)

**Comment by quinnj** [comment]
I still want to bug @JeffBezanson about allowing `x::T` at the repl, then we could solve all these printing issues (Float16, various Integer types, BigFloat, etc.) by just printing them like `x::T` which you could copy and paste. I forget what the hangup was on that.

**Comment by pabloferz** [comment]
My bad. Then just consider my last idea, here are some more

```julia
julia> big"2.1e-10"
```
```
2.1e-10_b0
2.1e-10_b256
2.1e-10_p256
```

Although a more general solution as @quinnj suggested might be the way to go too.

**Comment by ScottPJones** [comment]
:+1: for @quinnj ’s suggestion... that is a much more general approach...
For example, it could be used for:  `2.1e-10::Decimal128`  (the parser would need to be fixed
to not convert things to Float64 too early though for that example :grinning: )

**Comment by StefanKarpinski** [comment]
Printing BigFloats as `big"1.23"` seems good.

`2.1e-10::Decimal128` is a false assertion, so that expression would just throw an error.

**Comment by ScottPJones** [comment]
Well, if the parser held off converting things to Float64, and left it till macro time, then couldn’t you have some syntax:
```julia
@DecimalFloats begin
     x = 2.1e-10
     println($x)
end
```
where that would *not* be a false assertion?

**Comment by StefanKarpinski** [comment]
That seems like a pretty awkward output syntax.

**Comment by pabloferz** [comment]
I guess `big"1.2e10" + big"2.1e-10"im` or `big"1.2e10" + big"2.1e-10"*im` is better than we have right now, but it stills seems kind of cluttered to me.

**Comment by StefanKarpinski** [comment]
How about just printing BigFloats with lots of digits. This isn't the only place where our output format isn't a valid input syntax, which seems fine to people most of the time.

**Comment by pabloferz** [comment]
That might also work. What is the maximum number of digits that gets printed when displaying a `Float64`?

**Comment by dpsanders** [comment]
An alternative possibility that I quite like is to print the precision at the end in subscripts, e.g.

    1.2000000000000000000000000000006e+00₁₀₀

or better

    1.2000000000000000000000000000006₁₀₀

(without the `e+00` -- how easy is this? I find this more readable).

We implemented subscripts [here](https://github.com/dpsanders/ValidatedNumerics.jl/blob/master/src/intervals/interval_definition.jl) for intervals (the function `subscriptify` at the end of the file).

**Comment by ScottPJones** [comment]
:+1:  I think that's very good, but it looks shouldn't that precision be 256, not 100?
It is especially useful so that you can tell if something is 1.5₂₅₆ vs a Float64 1.5, or Float32 1.5f0,
or Float16(1.5) (maybe that could be 1.5₁₆)

**Comment by dpsanders** [comment]
@ScottPJones The function `set_bigfloat_precision()` changes the precision:
```
julia> big"0.1"
1.000000000000000000000000000000000000000000000000000000000000000000000000000002e-01 with 256 bits of precision

julia> set_bigfloat_precision(100)
100

julia> big"0.1"
1.0000000000000000000000000000002e-01 with 100 bits of precision
```

**Comment by ScottPJones** [comment]
Ah... I'd never seen anybody use 100 bits for binary floating point before... and since I think frequently in hex... :grinning:
I agree about `set_precision(T, precision)`, shouldn't that be: `set_precision!(T, precision)` though?

**Comment by dpsanders** [comment]
Yes, I guess you're right that 100 bits is strange in that sense, but the MPFR library allows it.
And yes, you're right that strictly it should be `set_precision!(T, precision)`.

**Comment by pabloferz** [comment]
@dpsanders :+1: I hadn't thought of that, I really like it.

(and dropping the e+00 isn't much of a problem)

**Comment by pabloferz** [comment]
@StefanKarpinski @tkelman What do you think about @dpsanders proposal of displaying the precision as a subscript at the end?

**Comment by tkelman** [comment]
That doesn't seem like especially standard notation, and subscripts might not display properly depending on terminal and font settings.
