### ISSUE TITLE
Cxx.jl support in official distributions (LLVM target for 0.4?)

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/julia#11283]
Is it likely that in the near future (e.g. 0.4) the build options used for the binary distributions will enable the use of @Keno's Cxx.jl package without recompilation?

No doubt Julia will target LLVM 3.7 at some point in the future, so I suppose my question is if the other build options required for the package are in some way undesirable for the official distributions?

**Comment by ViralBShah** [comment]
0.4 will most likely be shipping with LLVM 3.3.

**Comment by lobingera** [comment]
But still, can CXX be supported without the compilation step in the Pkg.build?

**Comment by tkelman** [comment]
> can CXX be supported

Not at all, with LLVM 3.3.

I think this is an 0.5 target.

**Comment by ViralBShah** [comment]
We can explore providing Julia+Cxx binaries at some point, once 0.4 is released.

**Comment by tkelman** [comment]
An LLVM upgrade seems like a pretty disruptive change to make on a release branch. We can easily make unofficial binaries in various experimental configurations though, just a matter of making commits to some temporary branch and clicking a few buttons on the buildbots.

**Comment by lobingera** [comment]
@ViralBShah 
While i can understand the caution not change too many things at the same time going from release to release, i'm somehow worried that this move puts a working debugger/lldb still into the (far) future...

**Comment by ScottPJones** [comment]
Is there something in LLVM 3.7 in particular that is not in LLVM 3.6 (the release version) that is needed for Cxx.jl?   (I'm interested because there are some C++ libraries we'd like to use directly).

**Comment by simonster** [comment]
If we release 0.4 with LLVM 3.3 initially but we later get to the point where we can upgrade to LLVM 3.6 or 3.7 on the release branch, then I think we should seriously consider doing it. I've seen many cases where LLVM 3.6 gives a substantial (sometimes 50%+) speed up over LLVM 3.3.

**Comment by tkelman** [comment]
Runtime performance is often better, however codegen is noticeably slower. See #9336 for outstanding blockers.

**Comment by Luthaf** [comment]
If I understand everything, Cxx.jl uses clang under the hood to compile C++. Does this issue means that there we will be a fully capable C/C++ compiler within the standard julia distribution ? If so, it will make installing binary dependencies a piece of cake (just use pre-compiled binary, or compile your own on Pkg.build). 

Is this correct ?

**Comment by Keno** [comment]
Well, the question is really if we want to ship Clang in the standard distribution. It's quite big, so that's not an easy decision.

**Comment by tkelman** [comment]
Not sure on that one yet, or if we need to make that decision just yet. Not everyone will really need C++ FFI (unless some indispensable package comes around and becomes heavily depended on?), so maybe making sure it's easy to install, providing compatible binaries, etc is the way to go initially.

**Comment by JeffBezanson** [comment]
Dup of #9336.

**Comment by kmsquire** [comment]
Not saying this shouldn't be closed, but I think this question goes beyond #9336, which doesn't seem to have anything (directly) to do with Cxx.jl.

**Comment by samuelpowell** [comment]
Thank you for your comments. 

@ViralBShah, I suppose it would be sensible to consider making Cxx.jl/debug compatible 0.4 builds available once LLVM 3.7 is released.
