### ISSUE TITLE
Constructing a SubArray with an empty index vector fails

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#11289]
```julia
julia> x = randn(5, 5)
5x5 Array{Float64,2}:
 -1.54875    0.736746   0.288464   -0.575672  -0.327747
 -1.53463    1.51122    0.0859705  -0.528929  -0.139893
 -0.382731  -0.244694  -1.55047     0.290429   0.377545
 -0.30907    0.840815   1.58206    -0.546569  -0.930888
 -0.76166   -0.736894  -0.971411    0.565943  -0.736462

julia> sub(x, Int[], :)
ERROR: BoundsError: attempt to access 0-element Array{Int64,1}
  at index [1]
 in sub at ./subarray.jl:85
```

**Comment by geekoala** [comment]
Hi @simonster, I believe you want to set particular indexes in sub function, what do you want by set Int[] in sub(A, inds...)?

**Comment by tkelman** [comment]
`Int[]` is an empty array of element type `Int`, so you probably want the equivalent of
```
julia> x[Int[], :]
0x5 Array{Float64,2}
```
?

Though is there any meaningful way to make that actually return a subarray? I do use 0-by-n and n-by-0 arrays somewhat often for concatenation purposes, but whether that can extend to subarrays is an interesting question.

**Comment by timholy** [comment]
In such situations, `julia --inline=no` is your best friend---if you like useful backtraces, that is.
