### ISSUE TITLE
`inv` not working for Rational

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#11298]
The following works on
```
julia> versioninfo()
Julia Version 0.4.0-dev+3639
Commit 7f7e9ae* (2015-03-01 22:49 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
but not on current master:
```jl
julia> A = [1//2 0; 0 2]
2x2 Array{Rational{Int64},2}:
 1//2  0//1
 0//1  2//1

julia> inv(A)
ERROR: MethodError: `inv!` has no method matching inv!(::Base.LinAlg.UpperTriangular{Rational{Int64},Array{Rational{Int64},2}})
 in inv! at linalg/dense.jl:298
 in inv at linalg/dense.jl:308
```

CC @andreasnoack.

**Comment by carnaval** [comment]
@andreasnoack how can you consider this closed when there is no hand written x86 implementation ?

**Comment by andreasnoack** [comment]
I thought that this fix would be easier when taking into account that the type is `UpperTriangular{Rational{Int}}`.

**Comment by carnaval** [comment]
that's only an excuse. AVX does vector integer instructions just fine :)

**Comment by andreasnoack** [comment]
We can look into writing an integer kernel next week. They don't seem to be widely available.

**Comment by carnaval** [comment]
looking forward to this. some nightstand reading : https://software.intel.com/sites/landingpage/IntrinsicsGuide/

**Comment by timholy** [comment]
I especially loved the part about the kayaking misadventures. Thanks for a gripping recommendation!

**Comment by timholy** [comment]
(Oh, and thanks @andreasnoack!)
