### ISSUE TITLE
"UndefVarError: call not defined" when doing `call = Expr(x...)`

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#11295]
I bumped into this weird bug when trying to make DataFramesMeta.jl pass its tests on 0.4 (FWIW, that happens in the `thread_left()` function.) 
I've simplified the test case to this:

```julia
julia> function f(x...)
           call = Expr(x...)
       end
f (generic function with 1 method)

julia> f(:a, :b)
ERROR: UndefVarError: call not defined
 in f at none:2
```

The problem disappears if:
- `call` is renamed to something else
- another function than `Expr` is called
- varargs are replaced with a fixed number of arguments

CC: @tshort

**Comment by vtjnash** [comment]
looks like this is potentially an issue with lowering. #10403 would likely fix this.
```julia
julia> code_lowered(f,(Symbol,Symbol))
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:(x::Any...)], Any[Any[:call],Any[Any[:x,:Any,0],Any[:call,:Any,18]],Any[],1], :(begin  # none, line 2:
        GenSym(0) = (top(_apply))(call,Expr,x)
        call = GenSym(0)
        return GenSym(0)
    end))))
```
