### ISSUE TITLE
Subscript "s" character not accepted (eg eₛ)

### ISSUE THREAD

**Issue by GlenHertz** [JuliaLang/julia#11290]
I'm enjoying writing math like it is in textbooks but I ran into an issue with subscript `s`:

```Juilia
eₒ(T) = 0.6108*exp(17.27*(T)/(T+237.3))
eₛ(Tmin, Tmax) = (eₒ(Tmax) + eₒ(Tmin))/2
```
`ERROR: syntax: invalid character "ₛ"`

I'm typing the characters like `e\_s<tab>`.   Any reason why subscript "s" isn't supported?

**Comment by stevengj** [comment]
This works in Julia 0.4.   In Julia 0.3, the problem was that the Unicode tables were out of date.
