### ISSUE TITLE
Nested ternary operator syntax error

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#11309]
Consider the useful pattern:
```jl
foo ? : 1 :
bar ? 2 :
3
```
This works as expected in 0.3, but fails with
```jl
ERROR: syntax: space not allowed after ":" used for quoting
```
on master. It doesn't seem to be newline-sensitive but removing the space before `1` suppresses the error.

**Comment by ScottPJones** [comment]
Doesn't that have an extra : in it?  It works perfectly fine for me on master:
```julia
julia> foo = true
true

julia> bar = false
false

julia> foo ? 1 :
       bar ? 2 :
       3
1
```

**Comment by one-more-minute** [comment]
You're right. Geez, too little sleep and too much coffee for me today.

0.3 must have parsed :(0) and ignored it.
