### ISSUE TITLE
promote(Int64(-1), Uint64(1)) yields an InexactError on v0.4 but not v0.3

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#11303]
A test for a package of mine that passes on 0.3 fails on 0.4. I've narrowed it down to the following problem:

```julia
julia> promote(Int64(-1), Uint64(1))
ERROR: InexactError()
 in promote at promotion.jl:132
```

The problem occurs in the context of a [branch-free saturating arithmetic function](http://locklessinc.com/articles/sat_arithmetic/) for subtraction that uses some bitwise tricks for speed:

```julia
function satsub{T <: Unsigned}(x::T, y::Unsigned)
	res::T = x - y
	convert(T, res & -(res <= x))
end
```
The `&` call internally uses `promote`, which throws the InexactError. You can call `satsub(Uint64(6), Uint64(5))` to produce the error in context.

On v0.3.7, here's the result of the equivalent call to `promote`:

```julia
julia> promote(int64(-1), uint64(1))
(0xffffffffffffffff,0x0000000000000001)
```

I am not sure what the expected behavior is and the [current release notes for v0.4](https://github.com/JuliaLang/julia/blob/1b2f4fa9d75c604978920153388bc9bd62e3dc6c/NEWS.md) don't mention anything regarding this change to `promote`. Is this a desired undocumented change or a bug?

If is a desired change, what should I be doing instead?

I'm running on OS X Yosemite with julia-0.4.0-c260ea92f4-osx.

**Comment by yurivish** [comment]
Also, on 0.3:

```julia
julia> uint(-1)
0xffffffffffffffff
```

On 0.4:

```julia
julia> Uint(-1)
ERROR: InexactError()
 in call at /Applications/Julia-0.4.0-dev.app/Contents/Resources/julia/lib/julia/sys.dylib

julia> convert(Uint, -1)
ERROR: InexactError()
 in convert at int.jl:180
```

Should I use `reinterpret`?

**Comment by tkelman** [comment]
At least the latter parts are intended, see #8420 - kinda buried in NEWS but it's there. You might want to try `reinterpret(UInt64, -1)`

**Comment by yurivish** [comment]
Oh, right – I'd forgotten about those. I'm now working on fixing up the saturating multiplication functions, which relied on conversions to extract the high 64 and low 64 bits from a Uint128. Reinterpret won't work here, since they're not the same size. Do you know what will?

**Comment by tkelman** [comment]
shift and convert for high bits, mask and convert for low bits maybe?

**Comment by yurivish** [comment]
Oh yeah! I had forgotten that it's still valid to convert a higher-precision type into a lower-precision type if the value is within range.

**Comment by yurivish** [comment]
So `reinterpret(UInt64, -1)` works, but `reinterpret(UInt32, -1)` fails with "ERROR: box: argument is of incorrect size". This is understandable, since `reinterpret` is about changing the type-interpretation while leaving the actual bits unchanged.

I wonder if there's a built-in function for saying something like "the signed integer type of the same size as the unsigned integer type T".

**Comment by simonbyrne** [comment]
> So `reinterpret(UInt64, -1)` works, but `reinterpret(UInt32, -1)` fails with "ERROR: box: argument is of incorrect size". This is understandable, since `reinterpret` is about changing the type-interpretation while leaving the actual bits unchanged.

You can also use `mod` (or `%`), for "modulo reinterpret"

```julia
julia> mod(-1,UInt32)
0xffffffff
```

> I wonder if there's a built-in function for saying something like "the signed integer type of the same size as the unsigned integer type T".

Try `signed`/`unsigned`:

```julia
julia> unsigned(-1)
0xffffffffffffffff

julia> signed(typemax(UInt64))
-1
```

**Comment by tkelman** [comment]
Good suggestions. Is there any action item on docs or a real bug here, or should we close this out?
