### ISSUE TITLE
File name conventions for modules in Base?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#11302]
It seems like we have a number of different conventions for naming files that contain modules in Base. As far as single-file modules go, Enums, LineEdit, REPL, and REPLCompletions are in files that begin with a capital letter first, but all the other modules are in files that begin with lowercase letters. We're also not totally consistent about how we organize multiple file modules. In most cases, the module itself is in the base directory and the supporting files are in separate directories, but this is not true of the Markdown module. And while I could imagine an argument for distinguishing modules whose exported bindings are exported from Base and modules whose exported bindings are not, I don't think that can explain the current inconsistency.

This may be a pedantic request, but I think we should settle on a single convention and stick with it. While I think basically any rule is better than no rule, my first thought is that all modules should be named with capital letters first and multiple file modules should live in the same directory as their supporting files. I'm happy to do the work here if we can decide what we want.

**Comment by tkelman** [comment]
+1 for just picking something and being uniform about it

**Comment by ScottPJones** [comment]
:+1: also!

**Comment by RaviMohan** [comment]
+1

**Comment by Mike43110** [comment]
+1

**Comment by dpsanders** [comment]
+1

**Comment by hayd** [comment]
I like the structure of markdown (file is in the directory), that way there's fewer files/repetition in base and it's more inline with external packages.

IMO we should consider pulling out some other related files into directories e.g. repl. I had tried doing this in the past (as an exercise in understanding the codebase) but sysimg was *very* sensitive to ordering changes.

Does  #11274 make this a little easier? (Is ordering in sysimg less finicky now?)

**Comment by vtjnash** [comment]
> Does #11274 make this a little easier? (Is ordering in sysimg less finicky now?)

Probably not, but it should be much faster to try various changes now.

**Comment by fredrikekre** [comment]
So, are all the +1's for renaming files to the corresponding module name? eg `/base/broadcast.jl` -> `/base/Broadcast.jl`
Can submit a PR.

**Comment by Moelf** [comment]
looks obsolete: https://github.com/JuliaLang/julia/pull/19173#issuecomment-416154009
