### ISSUE TITLE
RFC: rewrite functions used from utf8proc.c in Julia 

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11315]
I've been looking at the functions in utf8proc.c, and believe that the operations used by Julia could be done much more efficiently in Julia, and that the data file could be reorganized so that the common use cases would be much faster.
Currently, the part of the table that seems most heavily used is the category fields, really just 5 bits out of a structure that is 40 (32-bit platforms) or 48 (64-bit platforms) bytes long...
The way this is written IMO does very poorly with locality of reference, I think there are much better structures that could be used to figure out the category of a Unicode field... also, the functions like
islower(), isupper() are probably *mostly* used on plain old ASCII characters, so I think it would greatly improve performance to not even call into the C library just to figure something so simple out for characters < 128...

Any comments as to my doing this, and eliminating utf8proc.c (I also would like to eliminte utf8.c, but that's for another PR)?

**Comment by quinnj** [comment]
I can't remember where, but I believe it was mentioned somewhere that utf8proc has external significance since the Public Software group asked JuliaLang to maintain it going forward (after we forked it from the original project).

Here's an interesting idea, however. Rewrite utf8proc in Julia and distribute it with instructions on compiling a shared library that other languages/C projects could use. I'm sure there are gotchas or things that would complicate that process, but it might be interesting to push in that direction.

**Comment by tkelman** [comment]
utf8proc is used by the flisp front-end for parsing, so we can't rely on a pre-existing copy of Julia or libjulia for the parts of utf8proc that get used there. If we can make a standalone C-ABI library that's as small and has as few dependencies as libutf8proc.a from Julia code, then maybe. Pretty sure we're still a long way from there.

For the parts that get used from Julia code, we could consider replacing them with pure-Julia implementations, if the performance benefit is worth the additional code.

**Comment by ScottPJones** [comment]
@quinnj I'm not saying that the JuliaLang/utf8proc code should be deleted, rather that Julia should not use it anymore.  I'm not sure I understand your idea... I didn't know you could make a shared library written in Julia that could be used from C... what about all the GC infrastructure, etc.?
For C programmers, a better approach would be for somebody to take my Julia code and data structures,
and write a C version that could be used to effectively replace utf8proc... although I personally wouldn't do that... (I think it would mostly be a waste of time)... I think most people doing this sort of thing would rather just use the ICU libraries...

@tkelman Yes, I was aware of the depency in flisp, but it is quite small (and would be much faster and cleaner if I changed it :grinning:)
For example, there should just be a simple start id char and id char bit arrays (but using an two stage approach like UTF8Proc does, but better, so that very little space is taken... and less space means less problems with the L1/L2 caches...)  That array can be in C, but accessible also to Julia (and the array
should probably be skipped entirely for ASCII characters).
The other dependency is a normalize function, which is pretty bad... it ends up allocating space for a UTF-32 copy of the string, performing the NFC normalization, then reencoding it in UTF-8, with some extra mallocs and frees.
I'm absolutely sure I can handle that better!
The thing is, what I'd like to do will take substantially *less* space than what is there currently, and I believe will also be simpler, easier to maintain code.

**Comment by ScottPJones** [comment]
For example, I did a simple test, and got a 3x speedup for islower... There is a LOT of improvement that can be made in string/character handling... (all while removing dependencies on C code)

**Comment by tkelman** [comment]
> I didn't know you could make a shared library written in Julia that could be used from C... what about all the GC infrastructure, etc.?

Today it's certainly not self-contained or easy to do this, but making this kind of thing possible is a long-term goal.

utf8proc does have a handful of users outside of Julia, so at least for the data arrays part that you're proposing doing in C to make the flisp bootstrapping issue less of a problem, these changes might still make sense to do as additions there. I believe any improvements you make to normalization would also need to be done in C for flisp to make use of them.

**Comment by ScottPJones** [comment]
@tkelman That might be a lot harder (to try to make things still work for any users outside of Julia), because if they are directly using the structures, which I would be changing).  Also, some of the tables are really Julia specific (i.e. the start id character and other id character bit tables), and wouldn't help
utf8proc users at all.
Finally, I wouldn't be using the code from utf8proc at all for normalization, even it I write it in C (and the PTB didn't complain about me trying to get C code into base!), so it really shouldn't be put in with utf8proc (and their copyright).

**Comment by tkelman** [comment]
Okay, fair enough. So it sounds like you basically want to rewrite a new library in place of everything that we currently use utf8proc for, with pieces in C for bootstrapping and the rest in Julia? I guess that sounds fine to me, have at it if you think the performance benefits will be worth the effort. But as far as getting it merged goes, that'll need @stevengj and @jiahao and a few others to be on board with the idea and capable of maintaining whatever code you come up with if you happen to disappear (work commitments, emergency, lose interest, whatever).

**Comment by ScottPJones** [comment]
The thing is, it doesn't *need* a new library to speed up the parsing and reducing memory need for the data... just a few couple line functions, for the is start id character and is id character functions...
Right now, I don't see the utf8proc code as being very maintainable... it is buggy, and doesn't perform nearly as well as it could... as far as my code being maintainable... well, you'll just have to see... (I did have a pretty good reputation over decades of not introducing bugs, and having code that didn't need to be changed...)

**Comment by jakebolewski** [comment]
As long as we utf8proc is needed by the scheme frontend, I think we are going to stick to utf8proc for the immediate future.
