### ISSUE TITLE
dlopen RTLD_LOCAL default not respected on OSX

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#11322]
the documentation and code state that dlopen in julia defaults to RTLD_LOCAL, but on mac, it seems that the defaults is RTLD_GLOBAL per https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/dlopen.3.html

implemented by @stevengj in 27fab368 and noted while doing code review on #11307

**Comment by stevengj** [comment]
Good catch; `RTLD_LOCAL` is the [default on Linux](http://linux.die.net/man/3/dlopen).

**Comment by stevengj** [comment]
Maybe just change `JL_RTLD(flags, GLOBAL) | JL_RTLD(flags, LOCAL)` to `(flags & JL_RTLD_GLOBAL ? RTLD_GLOBAL : RTLD_LOCAL)`?

**Comment by vtjnash** [comment]
sounds good to me
