### ISSUE TITLE
Parameterized type with super long tuple

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11321]
Minimum working example
```julia
Enumerate((Int, 1:1000...))
```

It takes forever to finish. (Update: It overflows the stack after 10 mins)

It spends a lot of time in typeinf with a call stack thousands of levels deep. Same with #11320 , this is generated by `show(::IO, ::MethodError)`.

Would be nice to have a non-specialized fullback or sth similar.

Related #10380 , #11320 
Mailing list link: https://groups.google.com/forum/#!topic/julia-dev/BLvIjoiJtaI
@ScottPJones

**Comment by yuyichao** [comment]
@JeffBezanson (if you've done with your thesis)

**Comment by JeffBezanson** [comment]
Closing as dup.
