### ISSUE TITLE
Error while documenting macro

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#11348]
I noticed an inconsistency between the two versions of `@doc` when documenting macros.
Without the `->` it seems to document the macro directly:
```julia
julia> macro m(x) x end

julia> @doc "some macro" @m
(anonymous function)

julia> @doc @m
  some macro
```

But with the `->`, it tries to evaluate the macro as an expression first.
```julia
julia> macro n(x) x end

julia> @doc "another macro" -> @n
ERROR: wrong number of arguments

julia> @doc @n

```

**Comment by fcard** [comment]
Hi, I tracked the error to the line 193 of *docs.jl* (function docm(meta, def)).
```julia
    isexpr(def, :macrocall) && (def = namify(def))
```
Should be:
```julia
    isexpr(def´, :macrocall) && (def = namify(def´))
```
Notice the little `´` missing. The function is testing\namifying `quote @m end` instead of the unblocked `@m`.
(Should I've done a pull request for this? Sorry, new to this whole contributing business.)

**Comment by tkelman** [comment]
I'd want @one-more-minute to look at the suggested fix, either here or in a pull request.

**Comment by one-more-minute** [comment]
@fcard Please do, it would be great to see a PR for this.

**Comment by fcard** [comment]
Sigh... Pull request are more complicated than I thought. I mean, not a lot, but all that to add 2 characters to a line :P

Well, at least I think I get it now. But I need to be a collaborator to create a branch/make a pull request here, right?

**Comment by tkelman** [comment]
> But I need to be a collaborator to create a branch/make a pull request here, right?

Nope. You can click the little "edit" button when you have the file open on github and it'll automatically make a pull request for you.

**Comment by fcard** [comment]
Really? I was really unlucky when looking for tutorials, then. Thanks for the clarification, I will do that.

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#submitting-your-contributions
http://docs.julialang.org/en/latest/manual/packages/#making-changes-to-an-existing-package

**Comment by fcard** [comment]
Yeah, I read that, but misinterpreted a few bits. Sigh!
I did forget to add the tests however... I will do that.

**Comment by fcard** [comment]
Well, that was an experience.
Thanks everybody for your patience.

**Comment by one-more-minute** [comment]
Thanks for the fix! Hopefully the experience will be valuable if you want to make future contributions :)
