### ISSUE TITLE
expression printing precedence bug

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#11346]
```jl
julia> :((a:b)+c)
:(a:b + c)

julia> :((a:b)+c) |> dump
Expr
  head: Symbol call
  args: Array(Any,(3,))
    1: Symbol +
    2: Expr
      head: Symbol :
      args: Array(Any,(2,))
        1: Symbol a
        2: Symbol b
      typ: Any
    3: Symbol c
  typ: Any
```

**Comment by tkelman** [comment]
The bug is colon Expr's should have parentheses around them?

**Comment by mbauman** [comment]
Was this on 0.3?  It seems to work fine on master:

```jl
julia> :((a:b)+c)
:((a:b) + c)

julia> VERSION
v"0.4.0-dev+4888"
```

**Comment by StefanKarpinski** [comment]
Ah, yes, sorry, it must have been on 0.3. I wonder if this would be backport-safe.

**Comment by tkelman** [comment]
Can you bisect or otherwise find the responsible commit?

**Comment by fcard** [comment]
This is also true for the '=>' operator, by the by.
What do both of them have in common? I know that both of them are in the expr_infix Set that is defined in string.jl (in 0.3, at least). Maybe the responsible commit did something with it.

**Comment by fcard** [comment]
I think this one did it:

https://github.com/JuliaLang/julia/commit/52193154ec1abc60f2bf6736d38665aab286b306

I replicated it on the REPL and it fixed the issue.

**Comment by tkelman** [comment]
Good find. Since that appears to be display-only, I'll mark it as backport pending for now, unless anyone objects. Will check if it cherry-picks cleanly next time I do a round of backports.

**Comment by fcard** [comment]
Okay! If you want any help, just say the word :)

**Comment by tkelman** [comment]
backported in d296fc6d8235e78a30f6d363b199e81dff6e74b5
