### ISSUE TITLE
-i command line option should cause the REPL to be run

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#11347]
Keith Mason, in PR #10692, proposed making -I (uppercase) run the REPL.
The PR was closed by ihnorton, saying "It would be best to fix the existing options rather than add a new one."
and furthermore
"Right now -i just means "make isinteractive() return true" (see #6765). I think -i should mean "run-to-REPL" by default, like Python and bash. I don't believe this would conflict with IJulia or Gtk.jl/Julietta usage because they take over the event loop, but if it is a problem we could probably check whether isatty to decide."

**Comment by stevengj** [comment]
Seems reasonable to me.

**Comment by garrison** [comment]
+1

**Comment by tkelman** [comment]
This sounds way more useful to me than just changing the output of one function.
