### ISSUE TITLE
Adding ``@fprintf`` to the ``@printf`` familiy

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#11342]
I noticed that we no macro printing to a file. Is this something worth to expose as ``@fprintf``? The functionality is of course already there there with ``_printf`` in base/printf.jl#L999 .

**Comment by simonster** [comment]
`@printf` can take an IO as its first argument. Is there something else you're looking for here?

**Comment by mschauer** [comment]
Sorry, you are right. C convention got me.
