### ISSUE TITLE
Unexpected `NaN` returned by `round(::Float64,::Int)`

### ISSUE THREAD

**Issue by mrtzh** [JuliaLang/julia#11356]
Running julia version 0.3.8:
```
julia> round(0.01,308)
0.01
julia> round(0.01,309)
NaN
```
Is this intended?  It's rather inconvenient to deal with.

**Comment by StefanKarpinski** [comment]
Nope, that's a bug.

**Comment by sbromberger** [comment]
Is this related?

```
julia> round(pi,307)
3.1415926535897936

julia> round(pi,308)
Inf

julia> round(pi,309)
NaN
```

**Comment by Triiistan** [comment]
Hello, what do you think about https://github.com/JuliaLang/julia/pull/11405 for a fix?

**Comment by hayd** [comment]
So this is rounding to 308 decimal places? When would you want to do this? To me it seems like this should raise an InexactError (though NaN doesn't feel wrong either)... ?

@Triiistan you should add some tests, specifically for the behaviour you are fixing (above) but potentially also for the other cases/functions in this family/loop. :)

**Comment by mrtzh** [comment]
That's why I asked if it's intended. I have some code where the second argument to `round` is not a fixed constant, but comes from some different subroutine. I just want the code to work for all positive integer arguments without having to worry about it. So, semantically, it'd cleaner if `round` didn't just break at some point. 

That said, `NaN` isn't crazy. For example, `numpy.round` will produce `nan` as well, whereas Python's built-in `round` will preserve the number.

**Comment by sbromberger** [comment]
How does this help

```
julia> round(pi,308)
Inf
```
though? I could see arguments for `NaN`, but `Inf` is definitely incorrect.

**Comment by mrtzh** [comment]
Agreed.

**Comment by sbromberger** [comment]
(Also, I think it's perfectly reasonable to use round with large decimal places for irrational numbers. Getting pi to 308 decimal places doesn't seem so farfetched, if only as an academic exercise.)

**Comment by hayd** [comment]
@sbromberger However, round returns a Float64 so it's not anywhere near 308 decimal places!

**Comment by sbromberger** [comment]
@hayd yup, good point. Arbitrary precision bigfloat is probably the right datatype for this, but it would require a different function to keep `round` type-stable.

**Comment by sbromberger** [comment]
I think this broke things: https://groups.google.com/d/msg/julia-users/ThJZOienK2Y/wpJeseD6_lsJ .
