### ISSUE TITLE
Dispatch error with bound `TypeVar` argument on a second call to a "recursive" function.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11355]
Repro:
```julia
function f{T<:Tuple}(sig::Type{T})
    println(1)
    f(sig.parameters[1])
end
function f(arg::DataType)
    println(2)
    if arg <: Tuple
        error("Dispatch error!")
    end
end

t = Tuple{Type{Dict{TypeVar(:K, true)}}}

println("First time")
f(t)
println("Second time")
f(t)
```

[Mailing list thread](https://groups.google.com/forum/#!topic/julia-dev/Ue0V1mRcSR0)
@mauro3

**Comment by yuyichao** [comment]
Output:
```
yuyichao% JULIA_LOAD_PATH=${PWD}/.. julia -f runtests.jl
First time
1
2
Second time
2
ERROR: LoadError: Dispatch error!
 in f at /home/yuyichao/projects/mirrors/Traits.jl/runtests.jl:10
 in include_from_node1 at ./loading.jl:134
while loading /home/yuyichao/projects/mirrors/Traits.jl/runtests.jl, in expression starting on line 19
```

Changes that can make the problem disappear:

1. Do not call `f(::DataType)` in `f{T<:Tuple}(::Type{T})`
2. Make the `TypeVar` not bound
3. Call `f` only once

Maybe some caching issue??

**Comment by mauro3** [comment]
Leaving away `::DataType` in `function f(arg::DataType)` makes the problem disappear too.

**Comment by yuyichao** [comment]
Yeah you are right. Forgot to check that.

**Comment by mauro3** [comment]
Although, in Traits.jl that trick doesn't seem to work (a shame, I thought I had a work-around).

**Comment by yuyichao** [comment]
You have another definition below that rigth?

**Comment by mauro3** [comment]
Yes, but adding that other definition doesn't change the behavior of your example.  It doesn't matter though, there are other workarounds.

**Comment by mauro3** [comment]
This test case still errors in the last line:
```julia
function f{T<:Tuple}(sig::Type{T})
    println(1)
    f(sig.parameters[1])
end
function f(arg::DataType)
    println(2)
    if arg <: Tuple
        error("Dispatch error!")
    end
end

t = Tuple{Type{Array{Int,1}}}
f(t)
t = Tuple{Type{Dict{TypeVar(:K, true)}}}
f(t)
```
with
```
2
ERROR: Dispatch error!
 in f at none:4
```

Please re-open.
