### ISSUE TITLE
ERROR: ccall: could not find function dgeqrt_ in library liblapack

### ISSUE THREAD

**Issue by madjestic** [JuliaLang/julia#11360]
http://lpaste.net/132957

julia> using Gadfly

julia> plot(x = 1:100, y = cumsum(rand(100)-0.5), Geom.point, Geom.smooth)
Error showing value of type Plot:
ERROR: ccall: could not find function dgeqrt_ in library liblapack
 in run_interface at /usr/bin/../lib/julia/sys.so (repeats 2 times)
 in run_frontend at /usr/bin/../lib/julia/sys.so
 in run_repl at /usr/bin/../lib/julia/sys.so
 in _start at /usr/bin/../lib/julia/sys.so (repeats 2 times)

**Comment by jiahao** [comment]
This should not have happened - DGEQRT is a standard function in the LAPACK library. How did you install Julia? Which LAPACK library are you using?

**Comment by andreasnoack** [comment]
You probably have an old version of LAPACK. DGEQRT was added in 3.4.0 which is more than three years old. If you use the OpenBLAS shipped with Julia, the error should go away.

**Comment by ViralBShah** [comment]
@madjestic Are you using some distro packages?

**Comment by madjestic** [comment]
Thanks, guys.  I used old gentoo packages.  I am trying to get an updated version from gentoo-science repository now.  Please close the issue.
