### ISSUE TITLE
Named subpatterns in regex

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#11362]
Unless I'm missing something, RegexMatch objects don't provide a way to access named captures by name, but only by position; eg

```julia
match(r"(?P<hour>\d\d):(?P<minute>\d\d)", "Time is 12:45")
RegexMatch("12:45", 1="12", 2="45")
```

**Comment by kmsquire** [comment]
Related: #1448 (somewhat related: #1820, #1289)

Regex's could use some love if someone wants to put in the time.

**Comment by stevengj** [comment]
Basically, this would involve wrapping the [pcre2_substring_copy_byname](http://www.pcre.org/current/doc/html/pcre2_substring_copy_byname.html) function in PCRE.   Couldn't we just implement a `getindex(::RegexMatch, key::String)` method that calls this, so you could do `m = match(...); `m["hour"]`?

**Comment by tkelman** [comment]
We aren't binding PCRE2 yet, we're still on 8.36. We might need to upgrade to get some newer functionality. Regexes should probably be updated to return Nullables if someone wants to dig into that code.

**Comment by malmaud** [comment]
Implemented by https://github.com/JuliaLang/julia/pull/11566
