### ISSUE TITLE
Spurious Ambiguity Warning

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11367]
```
julia> abstract foo

julia> Base.convert{T<:foo}(::Type{BigInt},x::T) = x.val
Warning: New definition
    convert(Type{Base.GMP.BigInt}, T<:foo) at none:1
is ambiguous with:
    convert(Type{T}, T) at base.jl:43.
To fix, define
    convert(Type{Base.GMP.BigInt}, Base.GMP.BigInt)
before the new definition.
```

This shouldn't be an ambiguity because `!(BigInt <: foo)`.

**Comment by timholy** [comment]
This is probably #11136, and will probably be fixed by #11194. I didn't want to hit merge before Jeff gets a chance to look, but you could certainly test it.

**Comment by Keno** [comment]
I merged #11194 locally, but the problem persists.

**Comment by timholy** [comment]
Rats. OK, I'll dig into it later (if no one beats me).

**Comment by yuyichao** [comment]
I should add that #11136 is a overly simplified version (removing parametrized type) of the example on the [mailing list](https://groups.google.com/forum/#!topic/julia-users/x-2XlNWwh2I) and the mailing list example looks much more similar to your case here.
