### ISSUE TITLE
Should code_warntype integrate with the writemime system?

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#11364]
Right now the output of code_warntype won't have red highlighting in IJulia (https://github.com/JuliaLang/IJulia.jl/issues/310), rendering it fairly pointless. Maybe we could change it so it outputs HTML/markdown.

**Comment by timholy** [comment]
I'm fine with that idea. I think there may be some relevant discussion also in #9485.

**Comment by KristofferC** [comment]
![image](https://cloud.githubusercontent.com/assets/1282691/26512683/f2edaae6-4267-11e7-957b-bc689151c441.png)

I think this is OK?
