### ISSUE TITLE
deprecate utf32(Integer...) method?

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11379]
utf32 has the following method:
```julia
function utf32(c::Integer...)
```
However, neither utf8 nor utf16 have that functionality...
(also, the utf32 version does no validity checking, which it probably should).

Either the method for utf32 (and the test in strings.jl) should be deprecated and then removed,
or utf8 and utf16 should be make to act consistently (and add validity checking).

**Comment by stevengj** [comment]
Deprecating it seems reasonable.

**Comment by ScottPJones** [comment]
:+1: or :-1: on `utf32(Integer...)`? Just like the Romans...
What is the best thing to put for the replacement?
I imagine something like `utf32([...])`, but I don't know how to convert the `c::Integer...` into a `Vector{Integer}[c...]`.

**Comment by StefanKarpinski** [comment]
:-1: on `utf32(Integer...)`. Not sure why we have that. Probably my fault.

**Comment by stevengj** [comment]
`@deprecate utf32(c::Integer...) utf32([c...])` should do it, no?

**Comment by ScottPJones** [comment]
OK, that *almost* worked... got an error because of no method:
```julia
ERROR: MethodError: `convert` has no method matching convert(::Type{UTF32String}, ::Array{Int64,1})
```
however `utf32(UInt32[c...])` works fine... I can go ahead and make a PR...
`utf32([c...])` might have worked on a 32-bit system...

**Comment by stevengj** [comment]
No, you're right, I was missing the type specifier; I forgot that `UTF32String` didn't have a constructor for arbitrary integer arrays..   `Integer` could be any integer type (`Int8`, `BigInt`, whatever), so we need to convert it to `UInt32`.
