### ISSUE TITLE
slow performance with ^ for pi constant

### ISSUE THREAD

**Issue by espintos** [JuliaLang/julia#11383]
Doing pi^4 inside a big loop generates an allocation problem.

More info:
http://stackoverflow.com/questions/30360370/powering-a-math-constant-in-julia-is-slow

**Comment by stevengj** [comment]
Happens on latest 0.4:
```
julia> function test1(N)
            for i = 1:N
                x = pi^4
            end
       end
test2 (generic function with 1 method)

julia> @time test1(10000000)
 182.805 milliseconds (20002 k allocations: 305 MB, 7.97% gc time)
```
Somehow the conversion of `pi` to `Float64` is allocating an object on the heap?

**Comment by JeffBezanson** [comment]
It's using `power_by_squaring`.

**Comment by stevengj** [comment]
Why would `power_by_squaring` allocate so much memory?  The first thing it does is `to_power_type(x)`, which converts to `Float64`.

**Comment by simonster** [comment]
The problem is that it does `x = to_power_type(x)`. The change in type doesn't actually introduce type instability, but it does cause the codegen to box `x`.

**Comment by stevengj** [comment]
@simonster, good catch.  A workaround is to change `power_by_squaring` to
```jl
function power_by_squaring(x_, p::Integer)
    x = to_power_type(x_)
    ...
end
```
at which point I get `69.061 milliseconds (4 allocations: 144 bytes)`.

**Comment by stevengj** [comment]
Since `function foo(x); x = fixtype(x); ...` seems to be a common pattern, though, it would be good to eliminate the boxing in that case.
