### ISSUE TITLE
USE_SYSTEM_SUITESPARSE=1 sets wrong include path for suitesparse on FreeBSD

### ISSUE THREAD

**Issue by cookiemon** [JuliaLang/julia#11380]
In deps/Makefile the include path for suitesparse is set as `SUITESPARSE_INC = -I /usr/include/suitesparse` (Line 1555).
Which fails in FreeBSD as packages are installed into /usr/local (hence includes in /usr/local/includes) per default and possibly somewhere else. Also on Linux e.g. if you manually install suitesparse from tarball.

For completeness, the error message:
    root@101amd64-system:/wrkdirs/julia # gmake CC=gcc46 CXX=g++46 FC=gfortran46
    SuiteSparse_wrapper.c:2:21: fatal error: cholmod.h: No such file or directory
compilation terminated.
    Makefile:1564: recipe for target
'/wrkdirs/julia/usr/lib/libsuitesparse_wrapper.so' failed
    gmake[1]: **\* [/wrkdirs/julia/usr/lib/libsuitesparse_wrapper.so] Error 1
    Makefile:49: recipe for target 'julia-deps' failed
    gmake: **\* [julia-deps] Error 2

**Comment by ViralBShah** [comment]
Ping @nolta 

These paths are probably set up the way they are based on Debian/Ubuntu. I don't know of a good solution, except to provide more flags, and some FreeBSD defaults.

**Comment by cookiemon** [comment]
I don't really have a solution either except for maybe searching some known locations (/usr/include/suitesparse and /usr/local/include/suitesparse) and if it isn't there have the user set it via `CFLAGS = -I somethingsomething` (as is needed with LDFLAGS for the shared libs).

Note that this problem also exists for USE_SYSTEM_GRISU in v0.3.8 and may happen again in the future for other libs.

**Comment by tkelman** [comment]
You'll probably need to set your own `SUITESPARSE_INC` manually in `Make.user`.

**Comment by iblis17** [comment]
Please checkout this patch:  https://svnweb.freebsd.org/ports/head/lang/julia/files/patch-deps_suitesparse.mk?revision=428982&view=markup

**Comment by tkelman** [comment]
Hm, is `LOCALBASE` a FreeBSD-specific thing?

**Comment by iblis17** [comment]
Yes, FreeBSD's ports framework will define this variable.
FYR: https://svnweb.freebsd.org/ports/head/Mk/bsd.port.mk?revision=432405&view=markup#l457

**Comment by tkelman** [comment]
But someone building from source manually from a git clone outside of the ports framework won't have it defined, so that patch isn't really suitable for upstreaming, right?

**Comment by iblis17** [comment]
> so that patch isn't really suitable for upstreaming, right?

yes.
I just want to provide more info for who ran into this issue. 

If we want to integrate julia with ports framework, I guess simply `.include <bsd.port.mk>` will do the trick.
