### ISSUE TITLE
Documentation of `utf32` incorrectly states that an `Array` of `UInt32` is not copied by `UTF32String`

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11389]
While it is true that an `Array` of `Char` is not copied, the same as an `Array` of `UInt8` for `UTF8String`, or of `UInt16` for `UTF16String`, `UTF32String` copies the array, if it is an `Array` of `UInt32`.
Either the documentation should point out this inconsistency, or else the code needs to change to have a constructor that does a `reinterpret(Char, array)` so as not to copy (which is my vote).
Either way, the documentation should be changed (to say that `Array` of `UInt32` is copied, and `Char` not, or with the code changed, that both are not copied...)
See https://groups.google.com/forum/#!topic/julia-dev/ZBSelpTlw58

**Comment by stevengj** [comment]
We should just add the missing constructor that does not do the copy:
```
UTF32String(data::Vector{UInt32}) = UTF32String(reinterpret(Char, data))
```
(The `convert` functions should continue to make a copy.)

**Comment by ScottPJones** [comment]
That's what I had thought... but I am thinking that this is rather dangerous... you basically have mutable strings, whether you like it or not... It might be nicer if there were some way of having an "unsafe" constructor, that could be used by the internals (or where people felt sure they knew what they are doing).  For now I'll just add the missing constructor.
