### ISSUE TITLE
isless versus < bug with method_exists

### ISSUE THREAD

**Issue by colintbowers** [JuliaLang/julia#11385]
Define a new type:

    type MyType; end

Then:

    method_exists(<, (MyType, MyType))

returns `true`, while:

    method_exists(isless, (MyType, MyType))

returns `false`. Shouldn't both be returning `false`?

I'm on v0.3.x but the issue is confirmed by @rickhg12hs on StackOverflow who is running the latest build of v0.4. Link to the corresponding StackOverflow question below:

http://stackoverflow.com/questions/30362889/how-do-i-check-if-a-method-exists-for-a-particular-type?noredirect=1#comment48834646_30362889

Cheers,

Colin

**Comment by phobon** [comment]
The `<` operator has a fallback method that applies to all types

```
julia> type X
       end

julia> @which <(X(),X())
<(x,y) at operators.jl:32
```
If there is no more specific `<` method defined, the fallback one tries passing it off to `isless`, at which point you see the error. So I think you are seeing correct behavior.

**Comment by StefanKarpinski** [comment]
This is why `method_exists` and `applicable` are not very satisfying.

**Comment by JeffBezanson** [comment]
Yes, I see why this is confusing but nothing here is doing the wrong thing.
