### ISSUE TITLE
strange number promotion regression

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#11381]
Enter the following on the REPL gives the correct result:
```julia
immutable Zero <: Integer
end
Base.promote_rule{T<:Number}(::Type{Zero}, ::Type{T}) = T
const _zero = Zero()
promote_type(Zero,Int64) # => Int64
```
The following trivial interchange of statement 2 and 3 breaks the last line:
```julia
immutable Zero <: Integer
end
const _zero = Zero()
Base.promote_rule{T<:Number}(::Type{Zero}, ::Type{T}) = T
promote_type(Zero,Int64) # no promotion exists for ...
```
Both seem to work fine in v0.3, as far as I can tell from Juno.
Versioninfo:
Julia Version 0.4.0-dev+4913
Commit d6a8167* (2015-05-20 21:55 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)

**Comment by yuyichao** [comment]
The issue seems to be method caching and REPL somehow calling the `promote_type`

I overwrite `promote_type` in my startup file
```julia
Base.promote_type{T,S}(::Type{T}, ::Type{S}) = begin
    println((T, S))
    Base.promote_result(T, S, Base.promote_rule(T,S), Base.promote_rule(S,T))
end
```

And here's what it prints
```julia
julia> const _zero = Zero()
(Zero,Int64)
(Zero,Int64)
(Int64,Zero)
(Int64,Zero)
(Zero,UInt32)
(Zero,UInt32)
(Zero,UInt64)
(Zero,UInt64)
Zero()
```

The following code triggers the same issue in a more obvioius way
```
immutable Zero <: Integer
end
# const _zero = Zero()
try
    promote_type(Zero, Int64)
end
Base.promote_rule{T<:Number}(::Type{Zero}, ::Type{T}) = T

promote_type(Zero, Int64)
```

**Comment by yuyichao** [comment]
To reproduce without REPL

```julia
immutable Zero <: Integer
end
const _zero = Zero()
println(_zero)
# try
#     promote_type(Zero, Int64)
# end
Base.promote_rule{T<:Number}(::Type{Zero}, ::Type{T}) = T

println(@code_typed promote_type(Zero, Int64))
promote_type(Zero, Int64)
```

**Comment by yuyichao** [comment]
Basically `display` uses the promotion rules to figure out how to print it (probably because it's a Number?) and then the result got cached and mess up the code after that...

Apart from fixing https://github.com/JuliaLang/julia/issues/265, I'm not sure what to blame/how to workaround .....

**Comment by Jutho** [comment]
Ok, if it is just a manifestation of #265 then this can be closed I guess. I did not think of that because it seemed to work in v0.3, and #265 has been around from the beginning. But I guess there have been some REPL changes which could explain this behavior.
