### ISSUE TITLE
MSYS2 build of 0.4 hangs on a "infinite loop"

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#11384]
Hi,

The MSYS2 build now hangs when compiling bitarray.jl
Apparently that started to happen after the "move inference out of Base into Core.Inference" commit (I build Julia some days before and it worked) .

I know that we've been told by @tkelman that the MSYS2 build has problems and recommend to cross-compile with Cygwin like the nightlies. But the MSYS2 build is way faster to load (instantaneous) than the nightly build (2~3 seconds) and has served me well so far. Quite likely a Cygwin inheritance but one that had me drop Cygwin usage long time ago.

**Comment by tkelman** [comment]
No, the nightlies start slower because we delete sys.dll from them, since it will cause backtrace problems until we upgrade LLVM. You should be able to link your own sys.dll from a nightly though, check build_sysimg.jl.

Related discussion is in #10490 and #11285 - if you're willing to try other compiler versions we might be able to find one that works.

**Comment by joa-quim** [comment]
Something funny (well, not funny at all) was playing in my computer. Also had problems with dlls not being found by Visual Studio. After reinstalling VS and rebooting the problem disappeared. Also, I was not bitten again by #10490. On the other hand, another trouble I had recently was that Pkg.update() was not working because BinDeps complained about libexpat-1 not being found (or invalid module, not sure anymore). Had to do the update with the nightly.

What I would like to help (if I was able to) is with the build with VS but the problems you have reported a are a bit (or two) outside of my capacity to help.

**Comment by tkelman** [comment]
libexpat-1 comes from `make win-extras` and is needed by WinRPM.

Yeah, I don't know yet how to fix the segfaults that I've mentioned in #11263. How are you with build systems, can you help with #9422?

**Comment by joa-quim** [comment]
To be honest, I don't know enough to start a build system from scratch but I've managed to make tweaks to allow adding new features and solve some problems in a Cmake build of a project that am I developer too. So, in summary yes I would like to help but the trouble, I'm afraid starts in Git. How can I try the cmake build referred in #9422?

**Comment by tkelman** [comment]
Since that PR strictly adds files, you can actually start pretty easily, no conflicts to resolve or anything. Try downloading https://patch-diff.githubusercontent.com/raw/JuliaLang/julia/pull/9422.patch then doing `git apply 9422.patch` in your local clone.

**Comment by joa-quim** [comment]
OK,

My first attempt

...
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBMOJIBAKE_LIBRARY
    linked by target "libflisp" in directory C:/programs/julia64/src/flisp
    linked by target "libjulia" in directory C:/programs/julia64/src
LIBUV_LIBRARY
    linked by target "support" in directory C:/programs/julia64/src/support
-- Configuring incomplete, errors occurred!
See also "V:/bJ/CMakeFiles/CMakeOutput.log".

Now, I did this with VS2013 but it broke even before generating the Makefile. I guess than that I should try with Mingw gcc to see what comes up.

**Comment by tkelman** [comment]
Right, we got rid of the submodules and they're now managed by gnu make in the makefiles, so would need to use `ExternalProject` for them now in cmake.
