### ISSUE TITLE
optimize dynamic struct field lookup

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#11386]
This is a bit of a blue sky issue. Currently, doing dynamic field lookup is slow – about 2x slower than a Dict lookup. We could, however, compute a [minimal perfect hash function](http://en.wikipedia.org/wiki/Perfect_hash_function) for the field names to make this fast. The hash function would be associated with the type object.

**Comment by ScottPJones** [comment]
:+1:

**Comment by JeffBezanson** [comment]
Does this involve lookup by name or by index or both? Is the 2x slower number from an object with a large number of fields, or any object?

**Comment by StefanKarpinski** [comment]
Was seeing even for a small number of fields. It was lookup by symbol. Not sure about index.

**Comment by ScottPJones** [comment]
Do you have a code snippet that shows this?  Sounds similar to stuff I've dealt with before, and I'm concerned that my field lookups for my project might end up dynamic instead of compile time...

**Comment by mlubin** [comment]
Sounds like a possible JSoC project

**Comment by carnaval** [comment]
I think the largest performance hit comes from : 
- going through the builtin getfield with jlcall convention which implies boxing the result even if type inference was able to guess a tight type for the field (if all fields have the same concrete type).
- reloading the field names every time although we could inline them into the code if there is a small number of them

both would be solved with custom codegen in emit_known_call that go through the field names directly and even inline the symbol pointers for nfield < thresold

**Comment by KristofferC** [comment]
Here is a benchmark

```jl
struct SS
  a::Int
  b::Int
  c::Int
  d::Int
  e::Int
  f::Int
  g::Int
end

const S = SS(1, 2, 4, 8, 16, 32, 64)
const D = Dict(:a => 1, :b => 2, :c => 4, :d => 8,
           :e=> 16, :f=> 32, :g => 64)

const syms = [rand([:a, :b, :c, :d, :e, :f, :g]) for i in 1:10_000]

function sumS(S, syms)
  s = 0
  for sym in syms
    s += getfield(S, sym)
  end
  return s
end

function sumD(D, syms)
  s = 0
  for sym in syms
    s += D[sym]
  end
  return s
end

using BenchmarkTools
```

```
julia> @btime sumS(S, syms)
  316.356 μs (10000 allocations: 625.00 KiB)
178622

julia> @btime sumD(D, syms)
  106.071 μs (0 allocations: 0 bytes)
178622
```

**Comment by StefanKarpinski** [comment]
I feel like if this is a real issue for people, it will come up again.
