### ISSUE TITLE
Installing Julia behind Firewall. Can't change git:// to https://

### ISSUE THREAD

**Issue by dworkg** [JuliaLang/julia#11392]
Currently I am trying to install Julia on a Windows system. Because I am behind a firewall, it seems I have to change git:// to https://. However I feel like whenever I change git:// to https://, it doesn't switch when I run Julia.exe. Can anyone help with this?
![git](https://cloud.githubusercontent.com/assets/12548343/7754150/36d7ca56-ffb8-11e4-959b-0abb0542ba8d.png)
![git2](https://cloud.githubusercontent.com/assets/12548343/7754163/4f7a92c8-ffb8-11e4-9bb9-d6875b9de78a.PNG)

**Comment by Keno** [comment]
The change from git to https is going fine, but it seems like https is failing as well.

**Comment by dworkg** [comment]
I was able to fix the error by adding a proxy.
I didn't realized that even https wasn't getting through because the blue INFO message was still showing git://.
