### ISSUE TITLE
@time / @allocated output mismatch

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#11400]
Given the docs I would assume that the allocation values reported by `@time` and `@allocated` are the same, ("total number of bytes allocated during evaluation of the expression"). This is not the case though - on 0.3:

```jl
julia> f() = return; f(); @time f(); print("@allocated: "); @allocated f()
elapsed time: 2.217e-6 seconds (80 bytes allocated)
@allocated: 0
```
on master (Version 0.4.0-dev+4939, Commit ed61f1e*, x86_64-apple-darwin13.4.0):
```jl
julia> f() = return; f(); @time f(); print("@allocated: "); @allocated f()
   1.319 microseconds (4 allocations: 144 bytes)
@allocated: 0
```

**Comment by ScottPJones** [comment]
This is because `@allocated` uses a trick with a `let` and defining a local function, but `@time` and `@timed` do not... this is in `base/util.jl`.
I am testing a fix for this right now.

**Comment by simonster** [comment]
Differences documented by @ScottPJones in #11401
