### ISSUE TITLE
Do not include unbound `TypeVar` when showing methods

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11409]
Guess which one is which

```julia
julia> type A{T, V} end

julia> f{T, V}(::A{T, V}, ::A{T, V}) = 1
f (generic function with 1 method)

julia> f{T, V}(::A, ::A{T, V}) = 1
f (generic function with 2 methods)

julia> methods(f)
# 2 methods for generic function "f":
f{T,V}(::A{T,V},::A{T,V}) at none:1
f{T,V}(::A{T,V},::A{T,V}) at none:1
```

IMHO, it would be nice to print the second definition as
```julia
f{T, V}(::A, ::A{T, V})
```

And just omit the unbounded `TypeVar` parameters of `A`

Actually I would almost argue that printing the parameter name of a parametrized type in general is quite confusing. I still can't stop copying sth like `Array{T, N}` into the code and get a `UndefVarError` = = ...

**Comment by simonster** [comment]
Dup of #10794?

**Comment by yuyichao** [comment]
Yes.
