### ISSUE TITLE
qrfact should work for sparse matrices

### ISSUE THREAD

**Issue by gwhowell** [JuliaLang/julia#11404]
Hi, 
matlab and octave call Tim Davis sparse qr routine (for the sparse case).   I guess
that is the intention for  julia also, but does not exist on the versions of julia I've 
succeeded in downloading or compiling.  (I looked through the dev site and didn't 
see that this question has been raised) 

The following example is from 0.3.7 
julia> a = sprand(10,7,.3)
10x7 sparse matrix with 24 Float64 entries:
	[3 ,  1]  =  0.163518
	[4 ,  1]  =  0.125214
	[7 ,  1]  =  0.381684
	[8 ,  1]  =  0.512385
	[3 ,  2]  =  0.939042
	[5 ,  2]  =  0.853235
	[10,  2]  =  0.170734
	⋮
	[1 ,  6]  =  0.991984
	[2 ,  6]  =  0.158999
	[3 ,  6]  =  0.972338
	[4 ,  6]  =  0.0681683
	[7 ,  6]  =  0.24211
	[9 ,  6]  =  0.031277
	[1 ,  7]  =  0.389883
	[8 ,  7]  =  0.31854

julia> lufact(a)
UMFPACK LU Factorization of a 10-by-7 sparse matrix
Ptr{Void} @0x00000000048dd9d0

julia> qrfact(a)
ERROR: `qrfact` has no method matching qrfact(::SparseMatrixCSC{Float64,Int64})

(the bit of code I'm translating from octave happens to use spase LU and QR factorizations) 

Thanks, 
Gary Howell

**Comment by andreasnoack** [comment]
It has been added some months ago
```jl
julia> A = sprandn(100,10,0.2);

julia> qrfact(A)
Base.SparseMatrix.SPQR.Factorization{Float64,Int64}(100,10,Ptr{Base.SparseMatrix.SPQR.C_Factorization{Float64,Int64}} @0x00007f96fd796910)
```
You'll have to use the master version of Julia to use this functionality.

**Comment by gwhowell** [comment]
Thanks,
Gary

**Comment by gwhowell** [comment]
Hi Andreas,

My compile failed when I downloaded the dev version of julia (for centos7).


And my laptop would no longer update (fedora 19) so upgraded to fedora 20.
(yum install julia tells me I have the newest version)
 [root@gary2 howell]# julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.8
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-redhat-linux



Alas, same error

julia> a = sprand(20,6,.2)
20x6 sparse matrix with 17 Float64 entries:
    [1 ,  1]  =  0.925683
    [11,  1]  =  0.858121
    [19,  1]  =  0.0576215
    [1 ,  2]  =  0.102168
    [3 ,  2]  =  0.970211
    [7 ,  2]  =  0.19921
    [10,  2]  =  0.0727224
    ⋮
    [2 ,  3]  =  0.483305
    [4 ,  3]  =  0.786242
    [13,  3]  =  0.562719
    [14,  4]  =  0.761544
    [4 ,  5]  =  0.113032
    [17,  5]  =  0.0661711
    [4 ,  6]  =  0.260797
    [5 ,  6]  =  0.476904

julia> f = qrfact(a)
ERROR: `qrfact` has no method matching
qrfact(::SparseMatrixCSC{Float64,Int64})

julia> f = lufact(a)
UMFPACK LU Factorization of a 20-by-6 sparse matrix
Ptr{Void} @0x00000000067d5410

So I'd need to get to 0.4.0 ?

Regards,
Gary Howell

**Comment by andreasnoack** [comment]
Yes you'd need 0.4 and right now you have 0.3.8. @nalimilan is maintaining the Fedora packages, but I believe you should use this one

https://copr.fedoraproject.org/coprs/nalimilan/julia-nightlies/

Alternatively, you could use the generic linux binaries

https://status.julialang.org/download/linux-x86_64

**Comment by gwhowell** [comment]
The generic linux binary unpacked without incident (and let me use
qrfact)

Thanks,
Gary Howell
