### ISSUE TITLE
Scalar multiplication\Infix syntax interferes with "curly" syntax

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#11413]
```julia
julia> :(*{1, x})
:(1x)
```

**Comment by simonster** [comment]
This is parsed correctly:

```julia
julia> xdump(:(*{1, x}))
Expr 
  head: Symbol curly
  args: Array(Any,(3,))
    1: Symbol *
    2: Int64 1
    3: Symbol x
  typ: Any::DataType  <: Any
```

It looks like the bug is in `show`.

**Comment by fcard** [comment]
Yeah, I actually found the bug while looking for something else in the show functions. I already know how to solve it, but then I found that operator infix syntax also interferes with curly expressions.

```julia
julia> :(*{1,x}) # after the fix
:(1 * x)

julia> :(-{x,y})
:(x - y)
```

May as well solve both...
