### ISSUE TITLE
bundle libopenlibm.lib on windows for embedding with julia-config.jl

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#11419]
This scenario grew out of my investigation of why **Base.Dates.unix2datetime** was crashing, turns out it's not that function but **round**, I know, weird, rite?  Better to simply show an example

    #include <julia.h>

    int main(int argc, char *argv[])
    {

        jl_init(JULIA_INIT_DIR);

        jl_eval_string("println(sqrt(2.0))");
        jl_eval_string("println(round(1.0))");

        return 0;
    }

and built using the following Makefile in an msys2 env

    JL_SHARE = $(shell julia -e 'print(joinpath(JULIA_HOME,Base.DATAROOTDIR,"julia"))')
    CFLAGS   += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    CXXFLAGS += $(shell $(JL_SHARE)/julia-config.jl --cflags)
    LDFLAGS  += $(shell $(JL_SHARE)/julia-config.jl --ldflags)
    LDLIBS   += $(shell $(JL_SHARE)/julia-config.jl --ldlibs)
    CC = gcc

    all: embed_example

Results in the following

    $ make
    gcc -DJULIA_INIT_DIR=\"C:\\\\Julia\\\\julia-04051e9699\\\\lib\" -IC:\\Julia\\julia-04051e9699\\include\\julia  -LC:\\Julia\\julia-04051e9699\\bin  embed_example.c  -ljulia -o embed_example

    jeffw@xun MINGW64 ~/src/julia-embed-test
    $ ./embed_example
    1.4142135623730951

    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
    Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0)
    unknown function (ip: 0)

The call to **sqrt** is not necessary to cause the error, just to give some context that the Julia engine is functioning.  It's not just **round** either, it's at least **trunc** as well and I suspect all of the *llvm* macros.  I have not managed to debug this more fully because it's not easy to know where to begin.  This does not happen on OS/X or Linux nor in a non-embedding scenario as can be seen when using the REPL of the same Julia install.

    $ julia
                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "help()" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.0-dev+9597 (2015-05-23 02:32 UTC)
     _/ |\__'_|_|_|\__'_|  |  Commit 04051e9* (0 days old master)
    |__/                   |  x86_64-w64-mingw32

    julia> round(2.0)
    2.0

**Comment by nalimilan** [comment]
My two cents: probably worth checking that the flags returned by `julia-config.jl` are indeed the same as those used when building Julia. There could be a discrepancy on Windows for some obscure reason.

**Comment by waTeim** [comment]
Indeed this problem feels kind of obscure, but in this case, I think that's unlikely, as julia-config only returns what Julia itself returns, also those flags are only used to determine the location of include files and libraries. Also, they look ok -- 04051e9699 is the correct revision.

**Comment by vtjnash** [comment]
It's probable that julia-config.jl is missing some of the more esoteric flags that are needed to link Julia on windows, specifically those activated by the UNTRUSTED_SYSTEM_LIBM flag in this case.

**Comment by waTeim** [comment]
Ok **UNTRUSTED_SYSTEM_LIBM** you say?  That one is definitely missed.  Is there a visual studio equivalent to this flag? Any more come to mind?  I can read the Makefile if necessary.

**Comment by nalimilan** [comment]
That's not a compilation flag, rather a Makefile variable that enables static linking of openlibm AFAICT:
https://github.com/JuliaLang/julia/blob/96cc97065ef07a741e21dce3d47768d632ae131a/examples/Makefile#L13

**Comment by waTeim** [comment]
Hmm if this is happening then it appears to be a problem then because `libopenlibm.a` can't be used by the Microsoft linker and also doesn't exist.  However there is an `libopenlibm.dll`  But shouldn't this be automatically dlopened by libjulia? or if not that then the symbols should at least be there?  I have a feeling that what is happening is that the symbol is actually resolved in the julia binary and is inaccessible to a program that embeds julia thus the error message.  Is there a reason for linking statically?

**Comment by vtjnash** [comment]
> Is there a reason for linking statically?

yes, if you don't link it statically, llvm gets confused and segfaults because it trusts that libm will provide a wide variety of math functions that MSVC doesn't actually provide.

**Comment by waTeim** [comment]
Ok, so when the julia binary is created, it's not linked -lm, but rather -lopenlibm?  But what I don't get is why bother with that as opposed to on init, just dlopen openlibm.dll instead and set up the symbols that way before llvm even has a chance to start?  What's the static magic that prevents llvm confusion?

**Comment by vtjnash** [comment]
Windows doesn't have dlopen and doesn't provide anything equivalent to RTLD_GLOBAL in its equivalent API of LoadLibraryEx, so that just leaves static linking. 

Why isn't it possible for you to link to libopenlibm.a? We should be able to make that work.

**Comment by waTeim** [comment]
Ok, static linking is fine just need the *.a* (and a *.lib*)?

if `libopenlibm.a` was added to the distribution and if the embedding program compiled and linked in MSYS2 using gcc this would work, but I think that the Microsoft linker is not going to be able to handle that as it's not going to be able to deal with a *.a* (wrong format?); unless it's just a *.lib* with a different extension.

Also, maybe [this package](https://github.com/alainfrisch/flexdll) could be used?  That page says that official symbol ordering is not respected, so lack of RTLD_GLOBAL may still be a problem.

**Comment by tkelman** [comment]
I think we used to ship the static libopenlibm.a in the binaries (or maybe it was just libuv.a?) but there was some resistance to static libraries. The MSVC linker can probably understand libopenlibm.a if you rename it to .lib, it's worth trying.

**Comment by waTeim** [comment]
Hmm, do you remember what the problem with including static libraries was?  But static libraries are better than nothing, in fact, apparently they are the only thing that work in this case.

I'd like to be able to support both binary generation within MSYS2 and and also outside MSYS2 **julia-config.jl** could return something different depending on how it's being invoked -- assuming there is a test to determine this. If we are talking about simply using **.LIB** after the fact, I think [this script](https://github.com/waTeim/node-julia/blob/master/tools/create_libjulia_lib.py) can be modified to do that.

**Comment by tkelman** [comment]
ref #6711

**Comment by waTeim** [comment]
I don't think that's quite the same.  The object code in libuv is pulled into libjulia.{so,dll,dylib}, so libuv is not necessary.  In this case openlibm object code is part of julia.exe but not libjulia.dll.

**Comment by waTeim** [comment]
After hacking the above mentioned script, I was able to create libopenlibm.lib and link to it using the Microsoft linker, which fixed the error.  So yep, that's the cause.

The next question is are there other libraries like this and also can the build save libopenlibm.a?

**Comment by tkelman** [comment]
I think we could put libopenlibm.a into the installed binaries, it's not like it's all that large (around 400 kb). Maybe just on Windows if we don't actually need it anywhere else? The other libraries that get statically linked into libjulia are utf8proc, libuv, and libsupport, but I don't think any of those are statically linked into julia.exe.

**Comment by waTeim** [comment]
It's only needed on Windows.  I think as long as libjulia.dll has the symbols, that's sufficient, so access to those other libraries is not necessary.

**Comment by tkelman** [comment]
@vtjnash do you mean the .a or a .dll.a, or both? I don't think we're creating the latter yet for this library but we could.

**Comment by vtjnash** [comment]
`.lib` might be more general purpose here, but the `.a` would be pretty much the same

**Comment by tkelman** [comment]
MSVC confusingly uses `.lib` for both full static libraries and stub dll import libs. MinGW at least uses separate filenames, `.a` vs `.dll.a`.

**Comment by Keno** [comment]
I don't understand why this is an issue at all. Why are we looking for those symbols in the executable? All symbols the JIT needs should be provided by libjulia.

**Comment by vtjnash** [comment]
All symbols, except for these, are provided by libjulia.

**Comment by Keno** [comment]
Yes, but that's problematic for people who want to embed and don't necessarily have control over the embedding application.

**Comment by spinorkit** [comment]
Based on my limited experience compiling examples/embedding.c with VS2012, it would be very useful if libopenlibm.dll.a was distributed in the julia/lib folder along side libjulia.dll.a and libjulia-debug.dll.a.
The VC++ linker is happy to link against libjulia.dll.a, but jl_init() crashes unless you also link against libopenlibm.dll.a. 
It is inconvenient to have to make libopenlibm.dll.a manually from the libopenlibm.dll, so distributing the built version of libopenlibm.dll.a would be very helpful for people embedding julia into VC++ apps.

**Comment by tkelman** [comment]
I don't think we're currently generating that file, it might need to be added to the makefiles in openlibm (https://github.com/JuliaLang/openlibm), but there's no reason we couldn't. If you'd like to take a crack at a pull request, that would probably be the quickest way to make it happen.

**Comment by twadleigh** [comment]
@spinorkit, @ttkelman, I just got bitten by this yesterday, myself. I might have sufficient motivation and momentum to put together a pull request against this.

**Comment by twadleigh** [comment]
Once https://github.com/JuliaLang/openlibm/pull/145 is merged and a new version tagged, I'll start work on a PR to finish this up.

**Comment by twadleigh** [comment]
I think I'll supplement the fix for this with a simple cross-platform embedding test in the test suite. That done, we can probably close this.
