### ISSUE TITLE
how to set the color scheme

### ISSUE THREAD

**Issue by yorkerlin** [JuliaLang/julia#11414]
Hi all,
If the background color of the console is `black`, I cannot see anything I typed since julia displays in `black`
How to configure the output so that julia displays in `white`?

**Comment by JeffBezanson** [comment]
There are environment variables JULIA_INPUT_COLOR and JULIA_ANSWER_COLOR, but other than that this is terminal-specific. For example I use gnome-terminal on linux, and its default background is black and julia text is white. What terminal are you using?

**Comment by yorkerlin** [comment]
@JeffBezanson 
Fedora 18, gnome-terminal
If  the build-in scheme `Tango`  and `Grey in Black` are used in gnome-terminal, Julia uses `black` as the default color. Do you know how to set Julia's color scheme?

**Comment by yorkerlin** [comment]
@JeffBezanson 
The issue is solved by checking the `Same as text color` in gnome-terminal.
Thanks.
