### ISSUE TITLE
 compilation bug in cholfact

### ISSUE THREAD

**Issue by yorkerlin** [JuliaLang/julia#11417]
Hi all,
I run the following code, the error appears randomly.

```
julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: ArgumentError("invalid argument #4294967296 to LAPACK call")
 in potrf! at linalg/lapack.jl:1743
 in cholfact! at linalg/factorization.jl:37
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: PosDefException(4294967296)
 in cholfact! at linalg/factorization.jl:38
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end
ERROR: PosDefException(139689516335104)
 in cholfact! at linalg/factorization.jl:38
 in cholfact at linalg/factorization.jl:41 (repeats 2 times)
 in anonymous at no file:2

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

julia> for k in 1:10
       cholfact(eye(2)/4)
       end

```

**Comment by yorkerlin** [comment]
my enrichment are: 
Fedora 18, GCC4.4.6
blas-devel-3.4.2-2.fc18.x86_64
blas-3.4.2-2.fc18.x86_64

cat `Make.user`
```
USE_SYSTEM_BLAS=1
```

**Comment by yorkerlin** [comment]
It seems the bug is related to  compilation. 
Maybe adding some tests may be good for users. 
I use the `julia-0.3.2-linux-x86_64.tar.gz` and there is not such error.

**Comment by simonster** [comment]
The similarity between this and #5121 makes it sound like Julia is expecting 64-bit BLAS but getting 32-bit BLAS. Maybe adding `USE_BLAS64=0` to `Make.user` would help, but it may be worth waiting for someone who knows more about the build to comment here. OTOH, you're probably better off compiling OpenBLAS or using the binary distribution (which includes OpenBLAS), since it is substantially faster than the reference BLAS.

**Comment by tkelman** [comment]
ref #10457 which I haven't gone and fixed yet - will do if no one beats me to it
