### ISSUE TITLE
OverflowError with large NTuple type

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11449]
In the spirit of #11340, here's another regression:

    julia> NTuple{20000,Int}
    ERROR: OverflowError()

This seems to be intermittent; I can often get it to work a moment later until I go to an even larger value.

**Comment by JeffBezanson** [comment]
The OverflowError itself is intentional, added by #11330. However that change was not effective, since it just throws an exception at a random point and doesn't actually prevent you from constructing the type.

**Comment by JeffBezanson** [comment]
Also #11321 #11320

**Comment by JeffBezanson** [comment]
Closing as dup.
