### ISSUE TITLE
provide cryptographic hashes and signatures for binaries

### ISSUE THREAD

**Issue by hushfrog** [JuliaLang/julia#11445]

**Comment by StefanKarpinski** [comment]
Probably a good idea. cc: @staticfloat

**Comment by staticfloat** [comment]
Yes, this is a good idea.  For the 0.3 releases, we will now provide these through checksum files, starting from 0.3.8.  We'll provide checksums in [md5 format](https://s3.amazonaws.com/julialang/bin/checksums/julia-0.3.8.md5) and [sha256 format](https://s3.amazonaws.com/julialang/bin/checksums/julia-0.3.8.sha256) and will link to them from [downloads page]().

**Comment by tkelman** [comment]
Are those for sources or binaries? Binaries would need different checksums for each platform, no?

**Comment by staticfloat** [comment]
Those files contain the checksums for all the sources and binaries directly downloadable from julialang.org.  Things like the Ubuntu PPA and the Fedora copr repository I didn't bother adding, since they have their own checksumming and verification methodology.

**Comment by tkelman** [comment]
Right, should've actually looked at the files first (to be fair, my browser is dumb and didn't know what to do with them).

Probably don't need to take the checksum of the checksum file

> `227ba767dadc53798f9cf5b79c99af00 julia-0.3.8.sha256`

Otherwise I'm guessing you'll do this in a script every time I (or whoever else tags the release and orchestrates the buildbots) that a new set of release binaries are ready for moving around on S3?

**Comment by staticfloat** [comment]
Heh, yeah.  Removed that line, thanks.

I've added a note in the release checklist make target.

**Comment by nalimilan** [comment]
How can you include the checksum of the checksum file in the checksum file itself? Have you found a breach in SHA256? ;-)

(I guess/hope that was the checksum of the previous version of the file...)

**Comment by hushfrog** [comment]
Great, thanks.

**Comment by staticfloat** [comment]
Just for posterity's sake, the way I'm generating these files is to download basically everything linked to directly by [this page](http://julialang.org/downloads/) into a folder then running:

```
$ md5 -r * | grep -v sha256 | grep -v md5 > julia-0.3.9.md5
$ shasum -a 256 * | grep -v sha256 | grep -v md5 > julia-0.3.9.sha256
```

**Comment by snow8gaia** [comment]
Current stable release (v1.1.0)could use some Checksums.
Long-term support release (v1.0.3) has them. So, good job.

Reasons- https://github.com/portapps/portapps/issues/11#issue-407007733

**Comment by StefanKarpinski** [comment]
Yup, we've been doing this for years. Works great. Occasionally upstream dependencies silently replace a published version with something different, which causes builds to break, but that's their fault.
