### ISSUE TITLE
build_executable.jl : sys0 -> inference0 ?

### ISSUE THREAD

**Issue by mszlosser** [JuliaLang/julia#11442]
line 52 :     buildfile0 = joinpath(buildpath, "inference0")

**Comment by tkelman** [comment]
If you've tested that change and it works, mind submitting a pull request? You can even click the little edit button in the Github web interface and propose the change from there.

**Comment by vtjnash** [comment]
i think the correct change is `buildfile0 = [joinpath(buildpath, "inference0"), joinpath(buildpath, "inference")]`. can you test if that works?

**Comment by mszlosser** [comment]
Yes, "inference.o" and "inference.ji" should be also deleted from "~/julia/usr/lib" directory.
 
buildfile0 = [joinpath(buildpath, "inference0"), joinpath(buildpath, "inference")] is not correct.

line 52 : buildfile0 = joinpath(buildpath, "inference")

line 132 : println("running: rm -rf $(tmpdir) $(sys.buildfile).o $(sys.buildfile0)0.o $(sys.buildfile0)0.ji $(sys.buildfile0).o $(sys.buildfile0).ji")

line 133 : map(f-> rm(f, recursive=true), [tmpdir, sys.buildfile".o", sys.buildfile0"0.o", sys.buildfile0"0.ji", sys.buildfile0".o", sys.buildfile0".ji"])

Test :
$ julia ../../julia/contrib/build_executable.jl test_exe test_exe.jl targetdir --force
...
running: rm -rf /tmp/tmpoQuIuI /home/ms/julia/usr/lib/libtest_exe.o /home/ms/julia/usr/lib/inference0.o /home/ms/julia/usr/lib/inference0.ji /home/ms/julia/usr/lib/inference.o /home/ms/julia/usr/lib/inference.ji

**Comment by vtjnash** [comment]
fixed / migrated to https://github.com/dhoegh/BuildExecutable.jl
