### ISSUE TITLE
annoyingly missing orange dot in widely viewed  benchmarks page

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#11446]
http://julialang.org/benchmarks/
lacks an orange dot in the legend for rand_mat_stat
kind of sticks out like a sore thumb

Note last line of
![image](https://cloud.githubusercontent.com/assets/862530/7825201/f33d50b2-03d7-11e5-80c8-88404e7d6fec.png)

**Comment by JeffBezanson** [comment]
Issue moved to website repo.
