### ISSUE TITLE
Calling convention thwarts Loop Invariant Code Motion

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#11459]
This is a code generation issue discovered while investigating #1143.  Symptom is failure to vectorize.  Root cause is that lowering of `SubArray` access is generating a load that LLVM cannot certify has hoistable because it's not clear that the pointer is always safe to dereference.  LLVM 3.7 has a facility to let us tell it that the pointer is always dereferenceable (and LLVM 3.5.1 has a weaker facility that might cover many cases of interest). 

Some questions:
- In the Julia calling convention, is it the caller or callee that is responsible for checking that an argument is non-null?
- How much do we care about fixing this issue before we get off of LLVM 3.3?

Details follow, for lovers of LLVM internals.

```
function foo(F, A)
    for j = 1:size(A,2)
        @simd for i = 1:size(A,1)
            @inbounds F[i,j] += A[i,j]
        end
    end
end

code_llvm(foo, (Array{Float32,2}, SubArray{Float32,2,Array{Float32,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}))
```

Resulting LLVM code just before LICM (Loop Invariant Code Motion) runs is shown [here](https://gist.github.com/ArchRobison/da1f26b658f8afd91699).  The problematic load `%39` uses a pointer derived from parameter `%1`.  LLVM 3.5.1 gives us a way to say "this pointer parameter is safe to dereference" and LLVM 3.7 generalizes this annotation any pointer.

**Comment by carnaval** [comment]
I'm pretty sure argument pointer are always safe to speculatively load. In fact every jl_value_t* should be except for the small time between a getfield (or arrayref) and it's nullcheck (if any). Even then we could maybe use the loadable_or_null thing I saw discussed on llvm-weekly one day.

If there is an easy way to tell this to llvm it would make hoisting passes job a lot easier indeed.

**Comment by JeffBezanson** [comment]
Yes, jl_value_t* arguments passed to julia functions are always non-NULL.

**Comment by KristofferC** [comment]
This now vectorizes so presumably fixed.
