### ISSUE TITLE
figure out how to test `ismount` function

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#11454]
See https://github.com/JuliaLang/julia/pull/11279. It's unclear how to reasonably test this, especially cross-platform.

**Comment by garrison** [comment]
Of possible interest: [`test_macpath.py`](https://github.com/python/cpython/blob/3c0681e3b9a553e7a7d832ec814dc6575b37452e/Lib/test/test_macpath.py#L105-L117), [`test_ntpath.py`](https://github.com/python/cpython/blob/3c0681e3b9a553e7a7d832ec814dc6575b37452e/Lib/test/test_ntpath.py#L415-L448), and [`test_posixpath.py`](https://github.com/python/cpython/blob/3c0681e3b9a553e7a7d832ec814dc6575b37452e/Lib/test/test_posixpath.py#L173-L214)

**Comment by lobingera** [comment]
@StefanKarpinski: Do you mean, how to create a known mounted filesystem? I have not tested this, but it should be possible to put a gzipped iso filesystem into a few hundered bytes. And many linux systems have -ro, user options for /media/cd or similar. 
At least the test could be build isaw that automatic regression testing is completing (for UNIX-oid systems).

**Comment by nbaum** [comment]
Does it help that / will always be a mount point? (On filesystems which have a /, at least.)

**Comment by simonster** [comment]
On Linux I'm not sure we can do better than finding a mounted file system (if there is one) and testing against that, since it may not be possible to mount anything new without root access. On OS X we could create a disk image. No idea about Windows.

**Comment by malmaud** [comment]
@nbaum / will indeed always be a mountpoint and ``ismount`` will return ``true`` on it.

**Comment by yuyichao** [comment]
FWIW

1. The root directory is a special case and you are not really testing all the cases.
2. The logic is actually wrong in some cases since `/` might not be a mount point in a `chroot` environment.

Not sure how much does any of these matters....

**Comment by yuyichao** [comment]
And it turns out that `ismount` also doesn't handle bind mount... The device can be the same for a bind mount...

**Comment by yuyichao** [comment]
P.S. Git is probably using a similar logic..

**Comment by yuyichao** [comment]
> since it may not be possible to mount anything new without root access

I think fuse doesn't need root access. (But it does require external tools...)
