### ISSUE TITLE
uppercase/lowercase on a UTF16String returns a UTF8String

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11460]
This is not consistent with uppercase/lowercase on ASCIIString, UTF8String, and UTF32String.
This adds type instability into programs trying to use uppercase/lowercase, and I believe
it should be fixed.

**Comment by IainNZ** [comment]
:+1:, seems odd to have unnecessary encoding changes. I wonder if its because the algorithms to perform the case switch are all UTF8 based so it switches to UTF8 first? Quick PR would be just to fix the type stability by converting back (although I know you won't be happy with that long-term!)

**Comment by JeffBezanson** [comment]
It's to slap you on the wrist for using anything other than UTF-8 :P

**Comment by ScottPJones** [comment]
Actually, I've already determined where the problem is... But it's part 3am here... `UTF32String` has a specific version of `map`, but `UTF16String` goes to a generic one, that returns `UTF8String` for all types of `AbstractString`

**Comment by ScottPJones** [comment]
Hehe :grinning:
