### ISSUE TITLE
map on an AbstractString, if no more specific map method found, returns UTF8String always

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11464]
This affects map on UTF16String, in particular, showing up in #11460, as currently uppercase/lowercase both use map for UTF16String, and that can be solved by making more specific (and much faster) uppercase/lowercase methods for UTF16String (as is done for ASCIIString), however, the general case also needs to be fixed... map on an AbstractString should always return the same type.

**Comment by JeffBezanson** [comment]
`map` on an AbstractString can't *always* return the same type, if you map an ASCIIString to a result that has non-ASCII characters.

**Comment by ScottPJones** [comment]
OK, that makes sense, but where it is just different *encodings* of Unicode (as opposed to a subset, like
ASCII or Latin1), wouldn't you agree that it should stay in the same encoding (and type)?

**Comment by JeffBezanson** [comment]
Yes.
