### ISSUE TITLE
Add clip function to Julia Base

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#11479]
It would be great to have a function like [numpy.clip()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html) in Julia.

**Comment by johnmyleswhite** [comment]
`clamp`?

**Comment by juliohm** [comment]
I missed this one, thanks John.

Could you please close the issue?

-Júlio

**Comment by johnmyleswhite** [comment]
No problem.
