### ISSUE TITLE
`\` with sparse and full matrix gives different answers: Inf vs NaN

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#11483]
```
julia> s=[-5.06956e288   1.24662e288   0.0        
        1.24662e288  -2.49324e288   1.24662e288
        0.0           1.24662e288  -5.06956e288]
3x3 Array{Float64,2}:
 -5.06956e288   1.24662e288   0.0        
  1.24662e288  -2.49324e288   1.24662e288
  0.0           1.24662e288  -5.06956e288

julia> force
3x1 Array{Float64,2}:
 Inf      
   0.14007
 Inf      

julia> s\force
3x1 Array{Float64,2}:
 NaN
 NaN
 NaN

julia> sparse(s)\force
3x1 Array{Float64,2}:
 -Inf
 -Inf
 -Inf
```

**Comment by jiahao** [comment]
I honestly don't see why these should give the same answer or how this is at all a priority to fix.

**Comment by mauro3** [comment]
I thought that the result should be the same irrespective of whether the matrix is full or sparse, but I guess there is no reason for that.  Also, I just checked in Matlab and that gives the same answers.  Irrespective of whether this should be fixed or not, I fully agree that it is not a priority. Closing.

**Comment by tkelman** [comment]
Do you mean "same answers" as in same as Julia, or same between dense and sparse? On win32 R2011a I see the same output as Julia for these. Interestingly octave (3.8.2, x86_64-unknown-cygwin) does its own thing in the sparse case
```
octave:1> s=[-5.06956e288   1.24662e288   0.0
>         1.24662e288  -2.49324e288   1.24662e288
>         0.0           1.24662e288  -5.06956e288]
s =

  -5.0696e+288   1.2466e+288    0.0000e+00
   1.2466e+288  -2.4932e+288   1.2466e+288
    0.0000e+00   1.2466e+288  -5.0696e+288

octave:2> force=[Inf;0.14007;Inf]
force =

       Inf
   0.14007
       Inf

octave:3> s\force
ans =

   NaN
   NaN
   NaN

octave:4> sparse(s)\force
ans =

   NaN
  -Inf
  -Inf
```

**Comment by mauro3** [comment]
Sorry, same as Julia.  On linux matlab 8.4.0.150421 (R2014b)
