### ISSUE TITLE
Type inference for functions with default argument of parametrized type with floating number argument

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11492]
OK. I'm just trying to be accurate about what I've seen in the title but it seems to make it hard to understand. Here's an example I came up with when replying to [this mailing list post](https://groups.google.com/forum/?fromgroups=#!topic/julia-users/K-RJznFeHHM)

```julia
julia> type Dummy{N}
       end

julia> @inline f{N}(::Dummy{N}, args...) = N
f (generic function with 1 method)

julia> g(a=Dummy{1}()) = f(a, 1, 2)
g (generic function with 2 methods)

julia> @code_typed g()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[]], :(begin  # none, line 1:
        return 1
    end::Int64))))

julia> k(a=Dummy{1.0}()) = f(a, 1, 2)
k (generic function with 2 methods)

julia> @code_typed k()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[Dummy{N}]], :(begin  # none, line 1:
        GenSym(0) = ((top(apply_type))(Dummy,1.0)::Type{_<:Dummy{N}})()::Dummy{N}
        return f(GenSym(0),1,2)
    end))))

julia> @code_typed k(Dummy{1.0}())
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:a], Any[Any[],Any[Any[:a,Dummy{1.0},0]],Any[],Any[]], :(begin  # none, line 1:
        return 1.0
    end::Float64))))

julia> @code_typed g(Dummy{1.0}())
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:a], Any[Any[],Any[Any[:a,Dummy{1.0},0]],Any[],Any[]], :(begin  # none, line 1:
        return 1.0
    end::Float64))))
```

Note that if type inference failed with `k()` but works when passing the same default value as argument or when the type parameter is an integer.

Does the type inference refuses to construct it because types parametrized with floating number are non cachable or does it need a update after floating point number (and other types) are allowed as type parameters? (Or sth else?)

**Comment by yuyichao** [comment]
OK apparently it is a [5-year-old](https://github.com/JuliaLang/julia/commit/d0e455644fdb0de197e7df1959afbc506e9eeb59#diff-aa969e67a2da8072f75926eb14f4ecccR85) [TODO](https://github.com/JuliaLang/julia/blob/6b4c275b339c34ca938f4232c37672c7219d23d0/base/inference.jl#L376)

**Comment by JeffBezanson** [comment]
Looks like a simple oversight. Easy fix.
