### ISSUE TITLE
Segfault in Pkg.build("Cairo")

### ISSUE THREAD

**Issue by nbaum** [JuliaLang/julia#11504]
Happens every time. Tested with Cairo v0.2.26, v0.2.27, and v0.2.1.

I have Cairo 1.14.2.

I'm not sure the backtrace is of much use in this case, but hopefully I'm wrong about that: https://gist.github.com/nbaum/ae4386a0a8d5d7f5e70e

**Comment by tkelman** [comment]
What linux distribution is this? Can you try the Linux nightly binaries, or a few different 0.3.x versions (use the same download link as the latest release, just changing the version number) to see if anything changes?

**Comment by JeffBezanson** [comment]
What julia version?

**Comment by JeffBezanson** [comment]
Nvm, I see it in the gist.

**Comment by nbaum** [comment]
The distribution is an up-to-date Arch. Their Julia package is at v0.3.8.

The nightly does the same thing, as do v0.3.9, v0.3.7, and v0.3.2.

**Comment by nbaum** [comment]
I've narrowed it down to this example:

    using BinDeps
    @BinDeps.setup
    @show library_dependency("cairo", aliases = ["libcairo-2", "libcairo","libcairo.so.2"])

Interestingly, *not* specifying aliases - or having *only* `"libcairo-2"` for an alias - doesn't crash the above code. However, that fix doesn't stop the real build crashing.

**Comment by nbaum** [comment]
I've tracked the segfault down to `Libdl.dlclose(handle)` in `BinDeps.check_path!`. Nearly there. :)

**Comment by yuyichao** [comment]
@nbaum What Graphic card and driver are you using. I've seen nvidia driver doing something bad when dynamically opened. (And at the time it was triggered precisely because Arch's cairo enabled egl.)

**Comment by nbaum** [comment]
@yuyichao That sounds like it could be relevant! I'm using Nvidia GTX 660 with the proprietary driver.

**Comment by yuyichao** [comment]
Can you try setting `__GL_NO_DSO_FINALIZER` env to 1?

I'm trying to dig out my old debugging log (from gtalk...).

**Comment by yuyichao** [comment]
Some info that might be useful.

```
 o Interaction with pthreads
        Single threaded applications that dlopen() NVIDIA's libGL
        library, and then dlopen() any other library that is linked
        against pthreads will crash in NVIDIA's libGL library.  This does
        not happen in NVIDIA's new ELF TLS OpenGL libraries (please see
        (app-c)  APPENDIX C: INSTALLED COMPONENTS for a description of
        the ELF TLS OpenGL libraries).  Possible work arounds for this
        problem are:

            1) Load the library that is linked with pthreads before
               loading libGL.so.
            2) Link the application with pthreads.
```

```
o libGL DSO finalizer and pthreads
        When a multithreaded OpenGL application exits, it is possible for
        libGL's DSO finalizer (also known as the destructor, or "_fini")
        to be called while other threads are executing OpenGL code.  The
        finalizer needs to free resources allocated by libGL.  This can
        cause problems for threads that are still using these resources.
        Setting the environment variable "__GL_NO_DSO_FINALIZER" to
        "1" will work around this problem by forcing libGL's finalizer
        to leave its resources in place.  These resources will still
        be reclaimed by the operating system when the process exits.
        Note that the finalizer is also executed as part of dlclose(3),
        so if you have an application that dlopens(3) and dlcloses(3)
        libGL repeatedly, "__GL_NO_DSO_FINALIZER" will cause libGL to
        leak resources until the process exits.  Using this option can
        improve stability in some multithreaded applications, including
        Java3D applications.
```

https://devtalk.nvidia.com/default/topic/534221/linux/using-dlopen-against-a-nvidia-libgl-library-cause-werid-crash-in-another-unrelated-place-in-pthread/

@csslayer (If you still remember the solution/workaround....)

**Comment by nbaum** [comment]
No luck with the environmental variable, I'm afraid. :(

**Comment by nbaum** [comment]
I've discovered that anything that links to EGL segfaults at exit. Doesn't even need to call any EGL functions. Definitely points at this not being an issue with Julia. Sadly, I don't think Nvidia will be as helpful.

I'm still in the market for a workaround, though. Best I can think of is just to make BinDep not close libegl.

**Comment by yuyichao** [comment]
@nbaum It might be a regression for nvidia though. I'm also using ArchLinux and I haven't updated to nvidia 352 yet. I'm trying to upgrade and see if I can see the same problem (not that I would be able to fix it though).

**Comment by JeffBezanson** [comment]
@nbaum thanks for looking into this so deeply!

**Comment by nbaum** [comment]
I tried downgrading to 349 and it still does the same here. :)

**Comment by nbaum** [comment]
I quickly hacked in a noclose option for library dependencies and now I can build Cairo: the segfault is deferred until the Julia process terminates.

Not a nice solution, but it does mean I can use Tk now, so I'm pretty happy.
