### ISSUE TITLE
Problems with convert from AbstractArray{UInt8} to UTF32String

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11502]
1) It tries to look for a big-endian or little-endian 32-bit BOM, but doesn't check to see if a
little-endian BOM could instead be a little-endian 16-bit BOM.
2) It also doesn't check against a UTF-8 BOM, which would be a very common possibility.
3) This function doesn't do any validity checking except checking the length is a multiple of 4.

I believe this should at the very least be able to detect UTF-8, UTF-8 BOM, UTF-16 both LE and BE, with and without a BOM, and UTF-32 LE/BE with/without BOM).

**Comment by jakebolewski** [comment]
@ScottPJones is this still a problem now that your unicode fixes have been merged?

**Comment by ScottPJones** [comment]
These are still very much a problem.
I still have a laundry list of string related issues to deal with as time permits.
(these were a bit lower priority for me, as we are not dealing with strings with BOMs for my work, but I hope to have these fixed sometime in the next month or so)
