### ISSUE TITLE
convert function for UTF-16 from an AbstractArray{UInt8} problems

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11501]
The `convert` function for `UTF-16` from an `AbstractArray{UInt8}` has a few problems.
1) It tries to look for a big-endian or little-endian 16-bit BOM, but doesn't check to see if a
    little-endian BOM could instead be a little-endian 32-bit BOM.
2) It also doesn't check against a `UTF-8` BOM, which would be a very common possibility.
3) It calls `isvalid(UTF16String, data)`, (after doing any possible byte swapping based on BOM),
    and this possibly could be overly strict.

I believe this should at the very least be able to detect `UTF-8`, `UTF-8 BOM`, `UTF-16` both LE and BE, with and without a BOM, and `UTF-32 LE/BE` with/without BOM).

**Comment by stevengj** [comment]
Yes, the conversion routine right now is not very paranoid: it is documented to assume that the data is UTF-16 (not UTF-32 or UTF-8).

If we want to implement online detection of the UTF-xx encoding, maybe we should have a more generic function `utf(bytes::Vector{UInt8})` that detects xx and returns a string of the correct `UTFxxString` type.

**Comment by ScottPJones** [comment]
Since they are all just different encodings of Unicode, I'd rather have 3 methods (one function), that does the detection, validation (with options as far as replacement/error strategy and replacement string), that returns the string in the type you want to work with (to avoid an extra conversion step), and another form, like you described above, that is not type-stable, that just returns one of the 3 `UTFxxString` types.
