### ISSUE TITLE
Bessel and Airy functions should not silently convert BigFloat to Float64

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaLang/julia#11512]
Hi,

Super huge fan of the Julia language. I'm a developer at ApproxFun.jl and have been implementing some function approximation routines in extended precision. It looks like the Bessel and Airy functions don't have mpfr routines for `Complex{BigFloat}`, yet Julia gives results from `float64`ed values. Until an algorithm is implemented/wrapped, maybe an error/warning message is more appropriate?

```julia
julia> besselj0(1.0)
0.7651976865579666

julia> besselj0(big(1.0))
7.65197686557966551449717526102663220909274289755325241861547549119278912215269e-01 with 256 bits of precision

julia> besselj0(1.0im)
1.2660658777520082 + 0.0im

julia> besselj0(big(1.0im))
1.2660658777520082 + 0.0im
```

**Comment by stevengj** [comment]
Yes, I was planning to file an issue for this.   I think the current behavior (in `base/special/bessel.jl`) of silently truncating arbitrary `FloatingPoint` types to 64-bit precision is a mistake, and we should just throw a no-method-error.

Possibly this code dates from the days when the only fp types were Float32 and Float64.  For Float32, of course, it is perfectly appropriate to convert to Float64, compute the special function, and then round back to Float64.

**Comment by stevengj** [comment]
Similarly for some of the other special functions.

**Comment by simonbyrne** [comment]
+1
