### ISSUE TITLE
  julia-mode.el: triple quoted strings and `@doc`

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#11510]
Triple quoted stings don't work properly in emacs mode.  Now that we have the `@doc` documentation, I stumble over this one every other method I write.  Indentation never works. Highlighting is a erratic.

Example:
```julia
@doc """
     Sets the topography related functions:
     B -- bed eleveation
     """ ->
function settopo!(pa::GlaDSPara, B, H, ub)
    ...
end
```

This issue seems to be known: https://github.com/JuliaLang/julia/issues/9025#issuecomment-63552658 but I wanted to bump it.

**Comment by Wilfred** [comment]
Thanks for filing this, I shouldn't have just left a comment in another issue. Would you mind filing a separate bug for indentation, with an example of where we do the wrong thing?

For reference, here's an example of a triple-quoted string that we currently highlight incorrectly:

```julia
"""foo " bar"""
```

**Comment by yuyichao** [comment]
@Wilfred That triple quote mixed with single quote seems to be a problem in python-mode as well, which is why I didn't bother too much....

**Comment by yuyichao** [comment]
Actually what exactly is this report about? I do remember some indent problems a few month ago but this is what I'm getting now in my emacs.

```julia
@doc """
Sets the topography related functions:
B -- bed eleveation
""" ->
function settopo!(pa::GlaDSPara, B, H, ub)
    ...
end
```

Both this and the one in the original report looks OK for me. (My standard may be wrong so I just want to understand the problem)

IMHO, the tripple quote and single quote issue is probably a different one, as @Wilfred said.

**Comment by cortner** [comment]
I definitely still have problems with triple-quoted strings; see screenshot

![screen shot 2015-06-15 at 14 44 31](https://cloud.githubusercontent.com/assets/7688515/8161225/67f185be-136d-11e5-835e-ac5f779ef834.png)

**Comment by yuyichao** [comment]
Ah so indent works but not highlghting? Forgot to check that.

**Comment by cortner** [comment]
I think I used to have problems with indent, but haven't noticed anything since I switched back to julia-mode from ESS, but it has only been a few hours. I will report back here if I find something.

**Comment by yuyichao** [comment]
@cortner that's the same with what I remember. Please di report back if it stops working again.

**Comment by mauro3** [comment]
Indent doesn't work for me if it is indented (haha...).  For instance this I need to do by hand, every line:
```
function f()
    a = """
        Hello
        """
end
```

**Comment by yuyichao** [comment]
I see. What I remember not working before is that the function gets an extra indent after the `->` in `@doc`

**Comment by cortner** [comment]
I don't have that problem. If I indent the first line after """ then the following lines will be indented correctly. But I think the first line not being indented is the correct behaviour (at least how I use it). E.g.

```julia
@doc doc"""some documentation for
a new function; blah blah
"""->
mynewfunction() = nothing
```

**Comment by mauro3** [comment]
I think my usage above is correct and it produces the correct string. See #2305

**Comment by cortner** [comment]
I see. 

For what it's worth, that convention seems reasonable inside a function etc, but for documentation I want the entire width of the editor window.

**Comment by mauro3** [comment]
Yes, I agree with that.

**Comment by yuyichao** [comment]
Remaining issue moved to https://github.com/JuliaLang/julia/issues/11510
