### ISSUE TITLE
Dict of tuple to Int does not work

### ISSUE THREAD

**Issue by mAch17** [JuliaLang/julia#11511]
Hi,
In a previous version of Julia 0.4 (2015-04-14) I could do 
julia> a = Dict{(Int64,Int64),Int64}()
Dict{(Int64,Int64),Int64} with 0 entries

julia> a[(1,1)] = 4
4

julia> a[(1,2)] = 6
6

julia> a
Dict{(Int64,Int64),Int64} with 2 entries:
  (1,2) => 6
  (1,1) => 4

However in the new version (2015-05-30)
julia> a = Dict{(Int64,Int64),Int64}()
ERROR: TypeError: apply_type: in Dict, expected Type{T}, got Tuple{DataType,DataType}

Has the syntax changed for this ? If yes, please suggest the new syntax. If no, we might want to fix this.

**Comment by KristofferC** [comment]
You need Tuple{Int, Int} instead of (Int, Int).

**Comment by mAch17** [comment]
Thanks. This works.
