### ISSUE TITLE
New build error with LLVM svn & MSYS2

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#11524]
CC src/disasm.o
    disasm.cpp: In member function 'void {anonymous}::SymbolTable::createSymbols()':
    disasm.cpp:169:32: error: 'create' is not a member of 'llvm::MCConstantExpr'
         symb->setVariableValue(MCConstantExpr::create(addr, Ctx));

if I (blindly) replace ``create`` by ``Create`` than it compiles ``disasm`` but errors quickly after in

    CC src/debuginfo.o
    debuginfo.cpp: In member function 'virtual void JuliaJITEventListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&)':
    debuginfo.cpp:299:37: error: no matching function for call to 'llvm::object::SymbolRef::getSize() const'
             Size = sym_iter.getSize();

**Comment by Keno** [comment]
Update your llvm svn.

**Comment by joa-quim** [comment]
Sorry, have to this too. How do I update the llvm svn? I see no .svn dir so I guess that the solution is not to do an ``svn up`` inside deps/llvm-svn

**Comment by Keno** [comment]
You can either use `make -C deps update-llvm` or `git pull` in `deps/llvm-svn`

**Comment by joa-quim** [comment]
Thanks,

but now ...

    llvm[3]: Linking Release+Asserts Shared Library LLVM-3.7svn.dll
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMMC.a(MCWinEH.o):MCWinEH.cpp:(.text+0x233): undefined reference to `llvm::MCExpr::FindAssociatedSection() const'
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMMCParser.a(DarwinAsmParser.o):DarwinAsmParser.cpp:(.text+0x2e53): undefined reference to `llvm::MCExpr::FindAssociatedSection() const'
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMMCParser.a(DarwinAsmParser.o):DarwinAsmParser.cpp:(.text+0x33ad): undefined reference to `llvm::MCExpr::FindAssociatedSection() const'
    C:/MinGW64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.1/../../../../x86_64-w64-mingw32/bin/ld.exe: V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMMCParser.a(DarwinAsmParser.o): bad reloc address 0x1090 in section `.rdata'

**Comment by Keno** [comment]
Those functions were renamed. Try deleting those archives and object files.

**Comment by joa-quim** [comment]
the story repeats with other functions. Shell I delete them as well?

    llvm[3]: Linking Release+Asserts Shared Library LLVM-3.7svn.dll
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMObject.a(ELFObjectFile.o):ELFObjectFile.cpp:(.rdata$_ZTVN4llvm6object17ELFObjectFileBaseE[_ZTVN4llvm6object17ELFObjectFileBaseE]+0x60): undefined reference to `llvm::object::ObjectFile::getSymbolAlignment(llvm::object::DataRefImpl, unsigned int&) const'
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMX86Desc.a(X86ELFObjectWriter.o):X86ELFObjectWriter.cpp:(.rdata+0x228): undefined reference to `llvm::MCELFObjectTargetWriter::needsRelocateWithSymbol(llvm::MCSymbolData const&, unsigned int) const'

**Comment by Keno** [comment]
yes, seems like MSYS2's make did not catch the updated dependencies.

**Comment by joa-quim** [comment]
The deleting strategy turned out to be a never ending story. So I had to restart from a clean checkout and now it builds again.
Unfortunately the failing tests (starts by linalg3) and mostly (for me) the Cxx error is still alive.

    julia> using Cxx
    Warning: error initializing module Cxx:
    BoundsError(a=Array{Cxx.ClangCompiler, 1}[], i=(1,))
