### ISSUE TITLE
Cannot define &

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#11521]
It's possible to add new functions to the method `|`, but not to `&`.  This seems odd to me.

```
julia> &(a,b) = 42
ERROR: syntax: invalid assignment location

julia> |(a,b) = 42
| (generic function with 34 methods)
```

(obviously in practice this would be for specific types, but adding type specs doesn't change the error).

I see this with both 0.3 and 0.4 (trunk).

**Comment by StefanKarpinski** [comment]
There's a parser ambiguity that forces you to put parens around the operator in this case:

```jl
(&)(a,b) = 42
```

(I felt dirty writing that and restarted my REPL immediately after evaluating it.)

**Comment by andrewcooke** [comment]
ah!  ok, thanks.

**Comment by StefanKarpinski** [comment]
@JeffBezanson – since `&` isn't used as a unary operator anymore, could we change this?

**Comment by JeffBezanson** [comment]
Yes, but `$` still has the same issue.

**Comment by ScottPJones** [comment]
I noticed something very strange... `&` has a method, at `operators.jl:75`, but if you try to use it, you get:
```julia
julia> x = &(55)
ERROR: unsupported or misplaced expression &
```

**Comment by mbauman** [comment]
It's the same parsing issue as above.  Wrap the `&` in parentheses: `(&)(55)`.

**Comment by ScottPJones** [comment]
OK, I'd thought I'd tried all the possibilities, I'd tried `&55`, `&(55)`, `(&)55`, and forgot `(&)(55)`... yechh!

**Comment by JeffBezanson** [comment]
It would be pretty weird if `(f)x` were syntax for calling f on x. Come on.

**Comment by andrewcooke** [comment]
```
Prelude> let inc x = x + 1
Prelude> (inc) 4
5
```

i know, i know.  but i couldn't resist.

**Comment by ScottPJones** [comment]
:grinning: yes, but -55 works, but &55 doesn't, so I was just flaying around trying to find some way to access that method, which it turns out, does absolutely nothing.
@andrewcooke just got you there!
BTW, why are `*`, `|`, and `$` also defined as unary operators on Integer, that do nothing?  Could those be removed?

**Comment by JeffBezanson** [comment]
We allow those to be called with any number of arguments. See also #7368. I agree they're not necessary though. I'd be just as happy to remove the special parsing and N-ary methods for +, *, &, |, $ (though only + and * have the special parsing).

**Comment by ScottPJones** [comment]
Don't you need the special parsing and the 3 arg and 3+ arg forms for `*` to work efficiently? (what am I missing?).   I'd like to go ahead and remove the unary `*`, `&`, `|`, and `$`, if you don't mind... (don't want to put in a PR though to be immediate rejected)

**Comment by JeffBezanson** [comment]
Ok, but why? Especially if the functions are going to support any number of arguments, it makes sense to support one argument. For + and * I think that's fine. For bitwise operators it doesn't matter so much.

**Comment by ScottPJones** [comment]
Does `* 1` by itself make any sense, or `| foo`?
I think these methods should simply be "2 or more arguments", not any number of arguments.
Also, 3 of them are only defined for Integer, not Number... so you'd get strange no method errors if you really did have a single argument that wasn't an Integer.

**Comment by mbauman** [comment]
Not terribly, but what does make a whole lot of sense is `*(xs...)` and `|(ys...)`.  The answer for N=1 is well-defined in both cases, so why not support it?

**Comment by ScottPJones** [comment]
Here's why:
```julia
julia> (&)(55.0)
ERROR: MethodError: `&` has no method matching &(::Float64)
Closest candidates are:
  &(::Number, ::BitArray{N})
  &{T}(::Number, ::AbstractArray{T,N})
  &(::Any, ::Any, ::Any)
  ...
```

**Comment by ScottPJones** [comment]
They are not even defined correctly for the N=1 case currently... I recommend just removing them instead of wasting time trying to "fix" them.

**Comment by JeffBezanson** [comment]
Actually the fact that `(*)()` (* with zero arguments) currently returns `""` is another argument in favor of a dedicated string concatenation operator.

@ScottPJones I think I agree with you overall, but `&` doesn't work on floats in any case so I don't see why the `(&)(55.0)` example is interesting.

**Comment by mbauman** [comment]
`(&)(55.0)` is consistent with what I wrote above:

```jl
julia> 1.0 & 2.0
ERROR: MethodError: `&` has no method matching &(::Float64, ::Float64)
```

**Comment by ScottPJones** [comment]
OK... maybe a float was a bad example... Try these examples, which shows the inconsistencies:
```julia
julia> z = BitArray(1)
1-element BitArray{1}:
 false

julia> z & 1
1-element Array{Int64,1}:
 0

julia> z & 0
1-element Array{Int64,1}:
 0

julia> (&)(z)
ERROR: MethodError: `&` has no method matching &(::BitArray{1})
Closest candidates are:
  &{S,T}(::AbstractArray{S,N}, ::Range{T})
  &(::BitArray{N}, ::BitArray{N})
  &(::DenseArray{Bool,N}, ::BitArray{N})
  ...

julia> *z
ERROR: syntax: "*" is not a unary operator

julia> *(z)
ERROR: MethodError: `*` has no method matching *(::BitArray{1})
Closest candidates are:
  *{TA,TB}(::Union(DenseArray{TA,1},DenseArray{TA,2},SubArray{TA,1,A<:DenseArray{T,N},I<:Tuple{Vararg{Union(Range{Int64},Int64,Colon)}},LD},SubArray{TA,2,A<:DenseArray{T,N},I<:Tuple{Vararg{Union(Range{Int64},Int64,Colon)}},LD}), ::Base.LinAlg.AbstractTriangular{TB,S<:AbstractArray{T,2}})
  *{TA,TQ,N}(::Union(DenseArray{TA,N},SubArray{TA,N,A<:DenseArray{T,N},I<:Tuple{Vararg{Union(Range{Int64},Int64,Colon)}},LD}), ::Union(Base.LinAlg.QRPackedQ{TQ,S<:AbstractArray{T,2}},Base.LinAlg.QRCompactWYQ{TQ,M<:AbstractArray{T,2}}))
  *(::BitArray{1}, ::Base.SparseMatrix.SparseMatrixCSC{Tv,Ti<:Integer})
  ...

julia> *1
ERROR: syntax: "*" is not a unary operator

julia> *(1)
1

julia> 1 * z
1-element Array{Int64,1}:
 0
```

**Comment by ScottPJones** [comment]
I think all of these logically should be something like: `*(x,y...)`, not `*(x...)`

**Comment by nbaum** [comment]
Not *entirely* seriously: What about `*() = 1`?

I'd say `*{T}() = one(T)`, if it was possible to call it. Having *() be the multiplicative identity feels nice, useless though it may be.

Maybe we should have `one(String) = ""`!

**Comment by StefanKarpinski** [comment]
If it were to be anything, it should be `+() = false` and `*() = true`. The behavior of the booleans is actually specifically designed to "yield" to other types when promoted.

**Comment by ScottPJones** [comment]
@nbaum As a string guy, I'd think `zero(String) == ""`... is there some mathematical reason that `one(String)` fits better? (Not that I'd ever want either of those!)
@StefanKarpinski Right now, they're just wrong... which is why I say they should be removed... if at some later date, people come to some consensus on what the behavior of a binary operator with 0 or 1 arguments should be, then that could be added then.

**Comment by andrewcooke** [comment]
the suggestion for one(string) being "" is because the string concatenation operator (for reasons i don't claim to understand - perhaps it is in matlab?) is "*".

and to understand that, you need to understand some maths.  there's a general idea that "one" is a special value connected with multiplication (because "one times x" is x) and so traditionally if you're going to define a multiply with a single argument, or no arguments, one is the "missing value" you use.  so that things come out as normal as you can hope for.

similarly, for addition, the equivalent is "zero", because "zero plus x" is x.

and so there's some kind of relationship between `zero()`, `one()`, `+()`, `*()`, `sum()` and `prod()`.  but to what extent this should exist in the language, and to what extent it's just an implicit idea is unclear to me (and what people are discussing here, partly).

part of the problem, i think, is that types aren't always available.  so when `*()` or `prod()` doesn't have any arguments, it's not clear what type to pass to `one()`.  this is easier in a strongly typed language.  and maybe this issue won't really be resolved until (if) Julia gets more type inference.

**Comment by pao** [comment]
> perhaps it is in matlab

It is not. (MATLAB's string concatenation technique is array concatenation: `['hello' ' world']`.)
