### ISSUE TITLE
dispatch error on union

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#11537]
On 0.4 this errors
```
di = Dict(:a=>4)
tu = ((:a,1), (:b,2))

# This works:
g(x::Vararg{Tuple{Symbol,Any}}) = x
g(x::Associative) = x
g(tu...)
g(di)

# This should be equivalent:
f(x::Union(Associative,Vararg{Tuple{Symbol,Any}})) = x
f(di)
f(tu...) # errors
```
The error is:
```
ERROR: LoadError: MethodError: `f` has no method matching f(::Tuple{Symbol,Int64}, ::Tuple{Symbol,Int64})
 in include at ./boot.jl:252
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:320
 in _start at ./client.jl:412
while loading .../iss1.jl, in expression starting on line 12
```

**Comment by jakebolewski** [comment]
You can't use `Vararg` this way, it only makes sense as the *last* parameter of a tuple type (`Vararg` is not a type).

This gets to @carnaval's opinion that allowing users to construct `Vararg`'s as standalone types is difficult to prohibit without the vararg being a property (field) of a Tuple type.

**Comment by mauro3** [comment]
Ok, sorry, so how do I do the 0.4 equivalent of this:
```
Union(Associative, ((Symbol,Any)...))
```

**Comment by jakebolewski** [comment]
arg, I didn't mean to close this

**Comment by yuyichao** [comment]
`Union(Associative, Tuple{Vararg{Tuple{Symbol, Any}}})`?

**Comment by mbauman** [comment]
That works if you pass a tuple:

```jl
julia> f(x::Union(Associative,Tuple{Vararg{Tuple{Symbol,Any}}})) = x
julia> f((tu...)) # Note the extra parens to create a tuple
((:a,1),(:b,2))
```

You can't have a `Union` encompass both a single argument and a vararg, and I think that's a sensible restriction.

**Comment by JeffBezanson** [comment]
I think we could easily add more errors here, for using `Vararg` as a union type element and as a type parameter, for example.
