### ISSUE TITLE
`any` and `all` are bitwise?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#11540]
I didn't expect this, and I suspect it's unintentional:

```
julia> all([1,3,5,7])
1

julia> all([9,12,14,15])
8
```

**Comment by ScottPJones** [comment]
The code (in `reduce.jl`, 333/334), and in `functors.jl`, looks intentional... `AndFun()` = `x & y`, `OrFun()` = `x | y`

**Comment by JeffBezanson** [comment]
Eh, I wouldn't put much stock in that. The author might have meant

```
call(::AndFun, x::Bool, y::Bool) = x & y
```

or meant to use `&&`.

**Comment by ScottPJones** [comment]
From the functors around them, it didn't look that way, but of course, I could be mistaken...

**Comment by ScottPJones** [comment]
I'm not saying either that it was correct, just that it looks intentional!

**Comment by PythonNut** [comment]
Are `any` and `all` meant for the same uses as Python's `any` and `all`?

**Comment by hayd** [comment]
I hope not, julia doesn't covert to Bool as fast and loose as python. You should explicitly write:

```
all(a .!= 0)  # or
all([x != 0 for x in a]) # better perf when julia gets generators and can drop the [] ?
```
to get the python behaviour.

**Comment by StefanKarpinski** [comment]
Similar to https://github.com/JuliaLang/julia/issues/10838

**Comment by fcard** [comment]
Bitwise `any`/`all` have been deprecated by #11774.
