### ISSUE TITLE
Very odd behavior, possibly a parsing bug?

### ISSUE THREAD

**Issue by phobon** [JuliaLang/julia#11541]
This very specific anonymous function does not work:
```
julia> f = N -> (x = 0; for i=1:N (x += i) end; x)
(anonymous function)

julia> f(5)
ERROR: UndefVarError: i not defined
 in anonymous at none:1
```

However, these very slight variations do:
```
julia> f = N -> (x = 0; for i=1:N x += i end; x)  #no interior parens!
(anonymous function)

julia> f(5)
15

julia> f = () -> (x = 0; for i=1:5 (x += i) end; x) #no function argument
(anonymous function)

julia> f()
15
```

**Comment by jakebolewski** [comment]
It is interpreting `N (x += i) as a function call`, another vote for https://github.com/JuliaLang/julia/issues/7232?

**Comment by jakebolewski** [comment]
It is safer to use `;` to manually delimit blocks in single line statements rather than relying on whitespace.

**Comment by phobon** [comment]
Thanks for explaining that, I was totally baffled.

**Comment by tkelman** [comment]
Very very similar to #10366 - sometimes it helps in confusing parsing situations to quote the expression in question and actually look at the parsed `Expr` structure directly.
