### ISSUE TITLE
julia-mode: indentation after multiline expression without initial indentation

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11549]
Hard to exlain by word but here's the repro. Notice `c = 1` and the `end` after it should not be indented.

```julia
module A
f() =
    begin
    end
    c = 1
    end

let
    f() =
        begin
        end
    a = 1
end
```

**Comment by yuyichao** [comment]
The `module` appears to be not important and it applies for multiline expression in general.

**Comment by dfannius** [comment]
Another example of this bug can be found in the conversation at https://groups.google.com/forum/#!topic/julia-users/2ot-Y_WVnSY, with the following code:

```julia
y1 = f(x,
       z)
       y2 = g(x)
```
Note that this works fine when we're in a function:
```julia
function func()
    y1 = f(x,
           z)
    y2 = g(x)
end
```

What's happening is that when we're at the top level, the call to `julia-last-open-block` inside `julia-indent-line` returns nil, so the normal "indent according to the current block level" code fails and we fall through to the next case, which just indents the current line the same way as the previous one.

My intuition is that that final case shouldn't exist at all, and that we should just always indent to 0 if we're not in a block, but presumably this code was put there for a reason.

**Comment by yuyichao** [comment]
@dfannius Is the final case necessary to make sure real multi-line expressions can be indented correctly? E.g.

```julia
f(a,
  b,
  c)
```

Or is this covered by other path already?

**Comment by yuyichao** [comment]
Although I guess even if it is necessary for true multiline code, it doesn't feel like the right way to do that.

**Comment by dfannius** [comment]
No, that case is already covered by `julia-paren-indent`.

**Comment by yuyichao** [comment]
Go ahead then? Just make sure to test it on some script to make sure there isn't any obvious regression.

We can always fix it later. Ref https://github.com/JuliaLang/julia/pull/11831#issuecomment-114693806

**Comment by yuyichao** [comment]
I guess it can be used to support a different indentation in file/module scope as long as the first line is indented? I doubt it is important/should be supported though.

I also doubt it would be worse than what it is now. (It has been forcing me to have a new line after `f() = <newline>...` kind of function definitions and is quite annoy...)

**Comment by dfannius** [comment]
Yeah, the only use case I can easily think of for the old behavior is if you really want some interesting indentation at the outermost level and want all your statements after that to match it. But that would only have worked at the outermost level anyway, so it seems like a weird special case anyway.
