### ISSUE TITLE
Inference for convert(Type{FloatX},Something)

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#11542]
As discussed [on the list](https://groups.google.com/forum/#!topic/julia-users/Ct7ClwjL_yg), `convert` can have problems inferring the return type for some inputs. This mainly happens when the converted type is abstract, but can happen for some concrete types, e.g.

``` jl
julia> @code_warntype convert(Float64, Complex{Real}(1,0))
Variables:
  #s59::Type{Float64}
  z::Complex{Real}

Body:
  begin  # complex.jl, line 18:
      unless (top(getfield))(z::Complex{Real},:im)::Real == 0::Any goto 0
      return convert(T,(top(getfield))(z::Complex{Real},:re)::Real)::Any
      0: 
      return throw($(Expr(:new, :((top(getfield))(Core,:InexactError)::Type{InexactError}))))
  end::Any
```

The conversion from `Rational` and `Dates.Period` also have problems, but here I've only seen it for non-leaf types. It seems that all concrete subtypes in base fine. For `Rational`

``` jl
julia> code_warntype(convert, (Type{Float64}, Rational))
Variables:
  #s59::Type{Float64}
  x::Rational{T<:Integer}
  P::Type{T}

Body:
  begin  # rational.jl, line 71:
      P = promote_type(T,S)::Type{T} # line 72:
      return convert(T,convert(P::Type{T},(top(getfield))(x::Rational{T<:Integer},:num)::Integer)::Any / convert(P::Type{T},(top(getfield))(x::Rational{T<:Integer},:den)::Integer)::Any::Any)::Any
  end::Any
```

and for `Period`

``` jl
julia> code_warntype(convert, (Type{Float64}, Dates.Period))
Variables:
  #s301::Type{Float64}
  x::Base.Dates.Period

Body:
  begin  # dates/periods.jl, line 21:
      return convert(T,(top(getfield))(x::Base.Dates.Period,:value)::Any)::Any
  end::Any
```

In the last case, the cause is probably the `value` method [here](https://github.com/JuliaLang/julia/blob/c1e1993ebf6cecaefccc502cfd64385de6fb9b2e/base/dates/periods.jl#L4) because it accesses the field of an abstract type. For all the subtypes of `Period` in base the field exists and is always `Int64`, but maybe the methods should be defined for each leaf type.

@StefanKarpinski asked how I found these. My method is to call something like `Base.return_types(convert, (Type{Float64}, Any))` and then `methods(convert, (Type{Float64},Any))` and match the lines. You can also simply do something like `code_warntype(convert, (Type{Float64}, Any))`, but that is more output to read through.

cc: @ArchRobison

**Comment by JeffBezanson** [comment]
The problem is that there are just so many definitions for `convert(Float64, x)`. `methods(convert, (Type{Float64},Real))` gives 22 matches. In such a case we bail out and return `Any`, because looking at so many methods for every abstractly-typed call site just takes too long.

**Comment by andreasnoack** [comment]
@JeffBezanson Is there any reason to track this behavior with an issue or are things as we want them to be such that this issue should be closed?

**Comment by vtjnash** [comment]
The first now infers (there's only 2 methods now, not 22). For the second one, there's too many promote rules (between Float64 and Integer), so it's not determinable which will apply. The third doesn't exist anymore.
