### ISSUE TITLE
global finalize order

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11545]
If the finalizer of a global is using a nother global with finalizer, the order they are finalized seems undefined right now.

I believe this is causing `PyCall.jl` to SegFault on exit right now. AFAICT, what happens is:
1. `PyCall` initialize global handle, which is a `DLHandle` now.
2. On exit, it `dlsym` the python decref function to free python object in the finalizer
3. If the global handle was freed before the object, the program will segfault because of invalid handle.

This particular issue might be able to fix in `PyCall.jl` by making sure the `decref` function is always `dlsym`'d (or by reverting https://github.com/JuliaLang/julia/pull/11293) but I think this may be a more general GC issue.

@stevengj 
@carnaval

**Comment by pao** [comment]
I believe this was just rejected: https://github.com/JuliaLang/julia/issues/3067#issuecomment-107742053

**Comment by yuyichao** [comment]
Maybe the finalizer should at least be run in reverse order? (I would be a little surprised if they are not though)

**Comment by yuyichao** [comment]
I see.

Well, at least I've already worked around the `PyCall.jl` crash and I can see that it is probably pretty hard to handle this with GC so I'm happy enough now.
I still feel like a SegFault is a little bit too much and this might be a more general issue after #11293 (i.e. it might affect other packages as well, especially the ones that use lazy dlsym like PyCall). I'll just close this and let others decide if anything needs to be done on the julia side....
