### ISSUE TITLE
Pkg.status() ArgParse not found

### ISSUE THREAD

**Issue by kjowens** [JuliaLang/julia#11580]
```
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+5194 (2015-06-04 00:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 585fef0 (1 day old master)
|__/                   |  arm-linux-gnueabihf

julia> versioninfo()
Julia Version 0.4.0-dev+5194
Commit 585fef0 (2015-06-04 00:18 UTC)
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 3 (v7l)
  WORD_SIZE: 32
  BLAS: libopenblas (NO_AFFINITY CORTEXA15)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.1

julia> Pkg.status()
6 required packages:
ERROR: KeyError: ArgParse not found

julia> quit()
```

**Comment by IainNZ** [comment]
Is this on a clean install? Is there anything in your `.julia` folder?

**Comment by vtjnash** [comment]
to reproduce locally, manually add a junk line to your ~/.julia/v0.x/REQUIRE file

**Comment by wildart** [comment]
Manually deleted packages are a big headache for package dependency resolution. `Pkg.rm` would not remove packages which were deleted manually. You could edit ~/.julia/v0.x/REQUIRE file and remove packages which are not installed.

**Comment by kjowens** [comment]
Everything in the Julia build folder is clean, but I do have stuff from a previous install in ~/.julia. Here's the contents of my ~/.julia/v0.4/REQUIRE

```
Distributions
DataFrames
SQLite
CUDA
splines
ArgParse
```

**Comment by wildart** [comment]
Do you have `ArgParse` in ~/.julia/v0.4 folder? Check if listed packages are in ~/.julia/v0.4 folder and remove any which are not from ~/.julia/v0.4/REQUIRE.

**Comment by kjowens** [comment]
I'll just delete everything from REQUIRE, I thought if a package was required but wasn't installed it would automatically be installed.

I'm not sure if it would be better to make a new issue about the idea to fix it, but I think what would work is:

1. Try to load the packages in order
2. If a package is found to not exist (or not the right version) go through the rest of the packages only to check if they are installed, then return a list of the missing packages.

It could get tedious installing, running, getting an error, installing the next one, etc.

**Comment by wildart** [comment]
Data from ~/.julia/v0.4/REQUIRE is list of installed packages, an internal state of the package management system. If you mess with it, you can break down everything. Without it, the package management system does not know which packages are installed, so it will remove all dependencies which aren't required, ones you do automatic dependency resolution by calling `Pkg.update`, `Pkg.add` or `Pkg.rm`. Thus, I would not recommend removing everything, if you done some development dependency packages. Or look at .trash after.

**Comment by jakebolewski** [comment]
Its unclear what exactly is left to address here.  Please re-open a more detailed issue with the remaining items that have not been addressed.
