### ISSUE TITLE
LLVM_SVN build broken due to LoadedObjectInfo changes

### ISSUE THREAD

**Issue by crayxt** [JuliaLang/julia#11588]
cc @Keno 

I see the following error
```
    CC src/debuginfo.dbg.obj
debuginfo.cpp: In member function ‘virtual void JuliaJITEventListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&)’:
debuginfo.cpp:366:13: error: cannot convert ‘std::unique_ptr<llvm::LoadedObjectInfo>’ to ‘const llvm::LoadedObjectInfo*’ in initialization
             };
             ^
make[1]: *** [debuginfo.dbg.obj] Error 1
make: *** [julia-src-debug] Error 2
```

I believe it is due to this change https://github.com/llvm-mirror/llvm/commit/a520577e7ec22eb512f52cc8798648a4b0aee69d which mentions Julia

Regards,

**Comment by aviks** [comment]
I believe this is the change: https://github.com/JuliaLang/julia/commit/e51672a46da2d3492b4e0d6a9a12e09c85d56e91#diff-d4b80bf89e46982070f234dd7cc344a9L359

cc: @Keno 

Please re-open if it still does not work after that commit.

**Comment by tkelman** [comment]
(or leave a comment requesting someone reopen this, as people without commit access typically can't reopen issues)

**Comment by crayxt** [comment]
@aviks My build just finished successfully. I can confirm the issue is fixed. Thanks for your help.
