### ISSUE TITLE
Feature request method for spzeros(N)

### ISSUE THREAD

**Issue by ZacCranko** [JuliaLang/julia#11583]
Please let me know if I'm missing something, but there doesn't appear to be a method for ``spzeros``to generate a sparse `Array(T,1)` like there is with `zeros`. It'd be nice to be able to do things like `spzeros(N)`.

**Comment by nalimilan** [comment]
This will probably be fixed soon after adding `SparseVector`. See https://github.com/JuliaLang/julia/issues/11324

**Comment by tkelman** [comment]
We don't have a true 1-d sparse array type in base right now, but there's a WIP PR open for them, and a package SparseVectors.jl that implements the functionality.

**Comment by ZacCranko** [comment]
Good to know, thanks.

**Comment by ViralBShah** [comment]
Keeping this open so that we don't forget to do it.

**Comment by tkelman** [comment]
closed by #13440
