### ISSUE TITLE
Possible `Regex` method incompabilities

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#11593]
Due to the PCRE2 upgrade (#11447), one of the constructor methods of Regex no longer exists¹. This already causes the `apropos` function to throw a `MethodError`². Are there any other usages of the old method? Or instead of hunting down every instance of it, isn't there a way to reinterpret the old method to mean one of the new ones³?

-

¹ `Regex(::AbstractString, ::Integer)` became `Regex(::AbstractString, ::Integer, ::Integer)`
² I already fixed `apropos` in #11538 by swapping methods, as it was interfering with testing.
³ I made a suggestion in #11538 but I don't understand the regex code enough to know if its entirely   correct and compatible.

**Comment by tkelman** [comment]
Thanks for opening this separately. @malmaud and/or @stefankarpinski, would it make sense to add
```
Regex(pattern::AbstractString, compiler_options::Integer) =
    Regex(pattern, compiler_options, DEFAULT_MATCH_OPTS)
```
as @fcard suggested?

**Comment by malmaud** [comment]
Ya, that would make sense. The reason the options have been split into ``compiler`` and ``match`` in my PR  is that in PCRE2, the same constant has different meanings in the compiler and match contexts. 

It's probably a good idea for Regex clients to not pass PCRE flags directly anyway, but instead rely on the Julia-provided options (eg, ``i``).

**Comment by fcard** [comment]
I see. If we are not sure that nobody is using it, would it be a good idea to redefine that method, but deprecate it, so people know to switch to the proper one?

**Comment by malmaud** [comment]
Makes sense to me.
