### ISSUE TITLE
Weird error reporting for misplaced type parameter

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#11596]
```julia
julia> f(x{:y}) = 3
ERROR: syntax: "x{(inert y)}" is not a valid function argument name

julia> versioninfo()
Julia Version 0.4.0-dev+5106
Commit 3464f3d* (2015-05-29 17:17 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I'm not sure what the asterisk beside the commit number means, but I think I downloaded the latest nightly earlier today.

**Comment by tkelman** [comment]
> I'm not sure what the asterisk beside the commit number means

That just means your local copy isn't completely pristine according to git, you've got some uncommitted local files or something. Check `git status`, but it's likely nothing substantial.

**Comment by yurivish** [comment]
In which directory? I have some packages with local differences, but haven't made any changes to core Julia as far as I remember.

**Comment by tkelman** [comment]
The `Commit` line beneath `Julia Version 0.4.0-dev` from `versioninfo()` is about core julia, but it's probably nothing major.
