### ISSUE TITLE
julia-mode: comment-region and uncomment-region doesn't work well for multiline string literal

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11591]
Run `comment-region` and then `uncomment-region` does not work for multiline string literals.

Before `comment-region`

```julia
"""
a
b
c
"""
```

After `comment-region` (as expected)

```julia
# """
# a
# b
# c
# """
```

After `uncomment-region`

```julia
"""
# a
# b
# c
# """
```

(`python-mode` handles this so I think this is a bug of `julia-mode`)

**Comment by mauro3** [comment]
related: #11510

**Comment by ViralBShah** [comment]
Cc: @Wilfred

**Comment by Wilfred** [comment]
I can reproduce this. I'll take a look.

**Comment by yuyichao** [comment]
@Wilfred Thanks!

**Comment by Wilfred** [comment]
It looks like `comment-forward` is doing the wrong thing here. It's called from `uncomment-region-default`.

**Comment by Wilfred** [comment]
Sorry for the delay on this.

`forward-comment` uses the syntax table. However, we're changing all characters inside triple-quoted strings to be treated as `.`, punctuation. As a result, the end-of-line isn't being treated as a comment ender, so we jump over all the other comments.

It's slightly more obvious when you comment a region that isn't just a triple-quoted string:

```julia
"""a
 b
 c"""
x = 1
y = 2
```

to:

```julia
"""a
#  b
#  c"""
x = 1
y = 2
```

I think the proper solution here is to use `syntax-propertize-function`, which is what `python-mode` does.
