### ISSUE TITLE
Tuple's problem

### ISSUE THREAD

**Issue by icecubez** [JuliaLang/julia#11609]
I don't think the way a tuple echoes itself is right as it does below.
![image](https://cloud.githubusercontent.com/assets/12785265/8024391/4202a298-0d64-11e5-8eca-7f2fdea04cdf.png)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7434

**Comment by tkelman** [comment]
It's display only and we're not sure where exactly the bug is, but we know that once we upgrade LLVM it'll go away. Unfortunately upgrading LLVM likely won't happen until 0.5-dev. If you're willing to look into the source code via `@which` and start trying to track this down, that would be useful.
