### ISSUE TITLE
Julia 0.3.9 windows self-extract 64-bit doesn't run

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#11612]
I downloaded Julia 0.3.9 Windows self-extracting archive latest release (2015-05-30 11:24UTC) onto my Windows 8.1 64-bit Lenovo Thinkpad, and it didn't run.  It gave me the splash screen and then hung for 5 minutes (no prompt) until I killed it.  Can anyone replicate this?

**Comment by tkelman** [comment]
Evidently it has worked fine for other people, #11609 for example. Which splash screen are you referring to, the installer or the Julia repl?

**Comment by tkelman** [comment]
If the repl, does it happen every time? If not, then this is a duplicate of #9242

**Comment by tkelman** [comment]
If the installer, try opening and extracting it manually in 7zip - you don't absolutely need to run the installer, you can just manually extract its contents. You may have a corrupted or incomplete download, if you have access to `md5sum` or `sha256sum` I would recommend checking your download against the checksums at https://s3.amazonaws.com/julialang/bin/checksums/julia-0.3.9.md5 or https://s3.amazonaws.com/julialang/bin/checksums/julia-0.3.9.sha256, although I'm currently seeing an access denied error for those checksum files.

**Comment by StephenVavasis** [comment]
Julia was hanging was in the REPL splash screen (the Julia version was displayed, but then no prompt appeared).  It failed to start 4/4 times I tried.  However, after reinstalling (from the same downloaded .exe file!), it worked fine, and I am now unable to reproduce the problem. So I'm closing the issue -- sorry to bother everyone.
