### ISSUE TITLE
sum() doesn't preserve signed zero

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#11618]
```
julia> sum([-0])
0

julia> prod([-0])
0
```

this may seem silly, but it was the source of a bug in a evaluator for numerical expressions i wrote, since it means that IEEE handling of signed zero (and so signed infinity, once you add 1/x) isn't observed when you evaluate a product of (one or more) factors using prod().

**Comment by simonbyrne** [comment]
`-0` is the (unsigned) integer zero: you need to use `-0.0` for signed floating point zero.

Once you do that, `prod` seems correct, though `sum` is still wrong.

**Comment by andrewcooke** [comment]
ah yes, sorry - sloppy example.  it's the sum that caused the actual bug (i wrote the description in terms of prod because i couldn't remember what you call the things you add in a sum - the equivalent of "factor" for addition!).

**Comment by simonbyrne** [comment]
I believe it is usually termed a summand.

**Comment by simonbyrne** [comment]
[This line](https://github.com/JuliaLang/julia/blob/bc58740ea18cde597b42ba3a8c389f096c4fcf14/base/reduce.jl#L23) appears to be the problem.

One solution would be to define a different method for floating point types?

**Comment by andrewcooke** [comment]
oh i thought up "term" in the shower just now.

that seems a reasonable idea (a new method) to me.

until a few minutes ago i thought the zero()/one() approach was cool.  now i'm wondering just how often the source assumes that IEEE floats have an identity element for addition.

**Comment by andrewcooke** [comment]
what function would you add?  is it going to be a big performance hit?  addition is going to be in the middle of many people's tight loops.

**Comment by simonbyrne** [comment]
If we define an additional method
```
r_promote(::AddFun, x::FloatingPoint) = x
```
we should be able to avoid any performance hit.

There might be something better we can do though.

**Comment by stevengj** [comment]
@simonbyrne, that suggestion wouldn't fix the issue for `Complex{<:FloatingPoint}` and other composite types.

**Comment by andrewcooke** [comment]
would changing `x + zero(x)` to `x - zero(x)` work?  it seems like it would work for floats.

(+0) - (+0) = (+0) and (-0) - (-0) = (-0)

**Comment by jiahao** [comment]
> would changing `x + zero(x)` to `x - zero(x)` work? it seems like it would work for floats.

Ooh, devious.

I think we'd have to check the result in all possible rounding modes to be sure of a correct fix, since the result of ±0.0 ± 0.0 depends on which mode is set.

Here is a table of all the possibilities:

![screen shot 2015-06-09 at 11 06 18 am](https://cloud.githubusercontent.com/assets/1732/8049876/a1f3fba0-0e97-11e5-88c4-4a8d06d546ac.png)

Citation: page 247 of Muller, Jean-Michel, Nicolas Brisebarre, Florent De Dinechin, Claude-Pierre Jeannerod, Vincent Lefèvre, Guillaume Melquoind, Nathalie Revol, Damien Stehlé, and Serge Torres. 2010. Handbook of Floating-Point Arithmetic. Birkhäuser. http://link.springer.com/content/pdf/10.1007/978-0-8176-4705-6.pdf.

**Comment by andrewcooke** [comment]
ah, ok.  so can we detect the rounding mode?  because according to that table, for RN, RZ and RU we can use `- zero()` (lines 5+7), but for RD we need to use `+zero()` (lines 1+3).

**Comment by jiahao** [comment]
Maybe the better thing to do is initialize the accumulator with the first element rather than futzing with `±0.0` as the initial value.

**Comment by andrewcooke** [comment]
i don't understand the code completely, but it seems to me that the promotion code is there to do *something*.  skipping it, and simply using the value directly, would remove that.

perhaps we know exactly what methods to write where it is ok to skip promotion.  in that case, fine.  but that seems like it's assuming that no-one will ever have a (user-defined) numeric type that needs to be promoted while correctly handling signed zero.  and i am not sure that is true.

**Comment by StefanKarpinski** [comment]
How about making those definitions `oftype(x + zero(x), x)`? The addition of zero is there in case `x` is of a type where addition yields a different type. That used to be the case for e.g. `Int8` but now the only type I can think of in Base with this property is `Bool`:

```jl
julia> x = true
true

julia> x + zero(x)
1

julia> oftype(x + zero(x), x)
1
```

**Comment by andrewcooke** [comment]
cute.  seems like the best of both worlds.
