### ISSUE TITLE
Unexpected behavior when quoting a destructuring assignment using :()

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#11611]
```julia
julia> :(begin x, y = 1, 2 end)
quote  # none, line 1:
    (x,y) = (1,2)
end

julia> quote x, y = 1, 2 end
quote  # none, line 1:
    (x,y) = (1,2)
end

julia> :(x, y = 1, 2)
:((x,y = 1,2))
```

The final variation generates a syntax error when evaluated, though typing it in at the REPL is fine:

```julia
julia> x, y = 1, 2
(1,2)

julia> eval(:((x,y = 1,2)))
ERROR: syntax: assignment not allowed inside tuple
```

It's tempting to assume that the colon-quoted version of some code would parse the same when written in other contexts. Is there a reason for the current way things work?

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+5218
Commit 2817084* (2015-06-05 17:11 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by yuyichao** [comment]
`@eval` is used incorrectly. It should be

```julia
julia> @eval x, y = 1, 2
(1,2)
```

`:(x, y = 1, 2)` is parsed as `(x, (y = 1), 2)`

```julia
julia> Meta.show_sexpr(:(x, y = 1, 2))
(:tuple, :x, (:(=), :y, 1), 2)
```

Many expressions are parsed differently when quoted in parenthesis and I'm not sure if this is an error.

**Comment by yuyichao** [comment]
You can also use `quote`

```julia
julia> eval(quote x, y = 1, 2 end)
(1,2)
```

**Comment by yurivish** [comment]
Hey, yeah – I just updated the issue since there were a couple of mistakes there. The `@eval` was spurious.

As a somewhat naïve user I find it weird that `quote x, y = 1, 2 end` parses differently from :(x, y = 1, 2) especially since the [manual](http://julia.readthedocs.org/en/latest/manual/metaprogramming/) seems to imply that `quote` and `:` would both work the same when used on single expressions.

**Comment by yuyichao** [comment]
> the manual seems to imply that quote and : would both work the same when used on single expressions.

In some sense, that is never true.

```julia
julia> Meta.show_sexpr(quote x = 1 end)
(:block,
  (:line, 1, :none),
  (:(=), :x, 1)
)
julia> Meta.show_sexpr(:(x = 1))
(:(=), :x, 1)
```

**Comment by yuyichao** [comment]
Also note that it doesn't have to be assigning to multiple values.

```julia
julia> Meta.show_sexpr(:(x = 1, 2))
(:tuple, (:(=), :x, 1), 2)
```

**Comment by JeffBezanson** [comment]
`:( )` is actually a quoted parenthesized expression. Only the `:` part is quote syntax; for example `:x` is valid. Therefore it parses like a parenthesized expression. `(x, y)` and `:(x, y)` parse the same, the only difference is quoting.

**Comment by JeffBezanson** [comment]
See also #10209
