### ISSUE TITLE
Modules can export themselves

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#11637]
Today I realized that 

```julia
module Foo
  export Foo
end
```

works perfectly fine. Then you can do absurd things like:

```julia
julia> using Foo
julia> using Foo.Foo
julia> using Foo.Foo.Foo
julia> using Foo.Foo.Foo.Foo
julia> using Foo.Foo.Foo.Foo.Foo
...
```

It seems to me that such a counterintuitive behavior should not be allowed. I was quite surprised. Is there a reason why this is allowed? Should it be disallowed?

**Comment by samuela** [comment]
The first "concrete" objection that comes to mind is that it is probably desirable to have the module hierarchy be acyclic. That said, currently you can do things like

```julia
module Bar end

module Foo
  using Bar
end

module Bar
  using Foo
end
```

**Comment by JeffBezanson** [comment]
The idea is that `Foo` refers to the module, even inside the module itself. Therefore the identifier `Foo.Foo` exists, therefore so does `Foo.Foo.Foo`, etc. It would be possible to turn this off, and require you to write `using ..Foo` to get back the current behavior, but I don't really see the point. One place this commonly comes up is when a sub-module and its parent refer to each other.
