### ISSUE TITLE
findin does not work for strings?

### ISSUE THREAD

**Issue by weijianzhang** [JuliaLang/julia#11630]
I am using Julia Version 0.4.0-dev+5149 (2015-06-01 18:58 UTC).
Suppose I have a list `l`
```julia
 julia> l = ["a", "a", "b", "c"]
 4-element Array{ASCIIString,1}:
 "a"
 "a"
 "b"
 "c"
```
then `findfirst` and `findlast` can find the correct index.
```julia
julia> findfirst(l, "a")
1
julia> findlast(l, "a")
2
```
But `findin(l, "a")` returns nothing
```julia
julia> findin(l, "a")
0-element Array{Int64,1}

```
Is this a bug or I misunderstand something? 

Thanks,

Weijian

**Comment by KristofferC** [comment]
This is my interpretation from looking at the documentation:
```
findin(a, b)
Returns the indices of elements in collection a that appear in collection b
```

```julia
julia> findin(l, "a")
0-element Array{Int64,1}

julia> findin(l, ["a"])
2-element Array{Int64,1}:
 1
 2
```

**Comment by weijianzhang** [comment]
I see. Thanks @KristofferC , I think I misuse it. But it does return the correct result for integers.
```julia
julia> findin([1,2,3,3,4], 3)
2-element Array{Int64,1}:
 3
 4
```

**Comment by KristofferC** [comment]
Ok so this is the definition of `findin`

```julia
function findin(a, b)
    ind = Array(Int, 0)
    bset = Set(b)
    @inbounds for i = 1:length(a)
        a[i] in bset && push!(ind, i)
    end
    ind
end
```

The problem is that for a string `b`, the command `Set(b)` produces:

```julia
julia> Set("a")
Set(['a'])

julia> typeof(Set("a"))
Set{Char}
```

and thus later in the function this fails:

```julia
julia> "a" in Set("a")
false
```

On the other hand, this is true
```julia
julia> "a" in Set(["a"])
true
```

I am a bit surprised that `Set(::ASCIIString)` returns a set of `Char`

**Comment by nalimilan** [comment]
`String` is indeed a collection of `Char`s, since that's what you get when indexing a string. What's confusing here is that `findin` takes a collection as second argument. If `String` wasn't a collection but a scalar, you would get an error.

If you want to look for strings in a string (as opposed to `Chars`s in a string, as here), you can use `search` instead. See https://github.com/JuliaLang/julia/issues/10593 about attempts at making this more obivous.

**Comment by KristofferC** [comment]
@nalimilan: "If String wasn't a collection but a scalar, you would get an error."

This doesn't seem to be the case.

```julia
julia> findin([1,2,3,3,4], 3)
2-element Array{Int64,1}:
 3
 4
```

Because set of a scalar promotes it to a container with the scalar as the only item?

**Comment by nalimilan** [comment]
No, that's because numbers are considered as collections at the moment:
```julia
julia> 2[1]
2
```

I find it a bit confusing, for people have advocated that it was often useful.

**Comment by KristofferC** [comment]
Oh, I see. Thanks.

**Comment by weijianzhang** [comment]
Thanks @nalimilan  and @KristofferC for clarifying this.
