### ISSUE TITLE
Support eachindex on strings?

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#11649]
Might it make sense to define ``eachindex`` on strings to be the set of valid indices into the string? That would allow some code to be generic with regards to being passed abstract arrays or strings.

**Comment by nalimilan** [comment]
Makes sense API-wise. Do you have concrete examples of where this would be useful?

Though I'm a bit worried about performance: basically, to know the next index you need to do most of the work you would do to extract the next character. Since `eachindex` will likely be used to call `getindex` right after, you will end up doing the work twice. But LLVM may be able to eliminate the duplicate work thanks to inlining, so it's worth exploring.

To implement this, you could return an iterable object from `eachindex(::AbstractString)`, which would call `next` on the string and return the index. That way, you make it more likely that LLVM will notice duplicate calls to `next`.

**Comment by tkelman** [comment]
If #9297 were implemented then it would make sense for `eachindex` to return the `StringIndex` type.

**Comment by nalimilan** [comment]
> If #9297 were implemented then it would make sense for eachindex to return instances of the StringIndex type.

Right. But I don't think this makes a real difference fo this issue: `eachindex` would return any type of index `next` returns.

**Comment by timholy** [comment]
If one thinks about a string as a container of characters, this makes sense. Not having worked much with strings, I can't comment on whether that's a good way to think about them.

And @nalimilan's design is the right one (it matches how `eachindex` is implemented for arrays).

**Comment by malmaud** [comment]
I didn't really have a use case in mind. It just seemed natural that since a string supports indexing and already behaves like an immutable array for most purposes, it should support ``eachindex``. 

It also seems much more elegant to iterate over the indices of strings like

```julia
for i in eachindex(s)
  ....
end
```

then 
```julia
i=1
while i<length(s)
  ...
  i=nextind(s,i)
end
```

**Comment by StefanKarpinski** [comment]
+1 for `eachindex` for strings.

**Comment by ScottPJones** [comment]
I certainly hope nobody has anything like the second loop, it would be incorrect, as well as being `O(n^2)`
for things like `UTF8String`.

You need:
```julia
pos = start(s)
end = endof(s)
while pos <= end
   ...
   pos = nextind(s, pos)
end
```

I'm not sure about the benefit of `eachindex(s)`, and would that have to create a potentially large array to hold all of the indices into s? (I'm not sure how it would be implemented...)

**Comment by nalimilan** [comment]
> I'm not sure about the benefit of eachindex(s), and would that have to create a potentially large array to hold all of the indices into s? (I'm not sure how it would be implemented...)

As I said, it would return an simple object (a wrapper around an `Int`) implementing the iteration protocol and calling `next` or `nextind` on the fly.

**Comment by ScottPJones** [comment]
@nalimilan Actually, you didn't say that (which makes it clear), you said:
>To implement this, you could return an iterable object from eachindex(::AbstractString)

That could have meant returning a vector of the index values... (wouldn't a vector be an iterable object?)

**Comment by kmsquire** [comment]
Scott, to anyone using Julia for a while, what @nalimilan said was pretty clear, since it's a pretty common pattern in Julia.  But it's good to be reminded that people who haven't used the language for as long might not understand those things as quickly.

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/julia/pull/11708 implements the solution I suggested, not only for strings but for any iterable. See the details there.
