### ISSUE TITLE
invalid mmap write causes segfault on osx & windows

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#11646]
I figured I'd create a separate issue since this was discovered in #11351, and discussed a little in #11491.

To recreate, put the following in a `segfault.jl` file:
```julia
t = tempname()
open(t,"w") do f
    write(f,"Hello World")
end
a = mmap_array(UInt8, (12,), open(t))
a[5] = 3
```
Then open up the REPL and run `include("segfault.jl")`. 

When the contents of `segfault.jl` are pasted into the REPL and run, the last line throws `OutOfMemoryError`.

This has at least been confirmed on OSX and Windows.

**Comment by vtjnash** [comment]
this can be reproduced at the repl by running the last two commands at the same time (eg with begin/end or a `;`)

**Comment by vtjnash** [comment]
it can be "fixed" by reading any element of the array between the point where it is opened and where it is written (e.g. `a[4]` before `a[5] = 3`)

**Comment by quinnj** [comment]
Interesting. So has to do with the mmapping maybe? Since the data isn't "loaded" until read? Would that change the signal?

**Comment by quinnj** [comment]
Confirmed fixed on OSX and windows.
