### ISSUE TITLE
julia segfaults when MongoClient is given a bad string

### ISSUE THREAD

**Issue by farzonl** [JuliaLang/julia#11651]
This may need to be filed against github.com/pzion/Mongo.jl, but  I have a gut feeling even if a a library is not handling a string or the mongoClient correctly, it should not be causing code in julia to segfault. 
 
test code:
function getCollection(client, collectionName, dbName)
	print(client);
	return MongoCollection(client, dbName, collectionName);
end
getCollection(MongoClient("localhost:27017"),"blah","blah");

stack trace:
MongoClient(localhost:27017)
signal (11): Segmentation fault: 11
mongoc_client_get_collection at /Users/farzon/.julia/v0.3/Homebrew/deps/usr/lib/libmongoc-1.0.dylib (unknown line)
getCollection at /Users/farzon/Desktop/juliaMongoTest.jl:9
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1418
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:59
eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:207
eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:215
eval_body at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:543
jl_interpret_toplevel_thunk_with at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/interpreter.c:571
jl_toplevel_eval_flex at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:511
jl_toplevel_eval_flex at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:443
jl_parse_eval_all at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:544
jl_load at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/toplevel.c:581
include at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
include_from_node1 at loading.jl:128
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/gf.c:1418
process_options at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
_start at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jlcall__start_17448 at /Applications/Julia-0.3.9.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
true_main at /usr/local/bin/julia (unknown line)
julia_trampoline at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/init.c:1053
Segmentation fault: 11

**Comment by aviks** [comment]
While pure Julia code causing a segfault is always a Julia bug, when a third party C library is involved, that guarantee cannot be given by base Julia. In this case, Mongo.jl must validate all input before passing it on to the Mongo C driver. So yes, this should be filed against Mongo.jl. cc: @pzion
