### ISSUE TITLE
BigInt/BigInt = BigFloat

### ISSUE THREAD

**Issue by Bradan** [JuliaLang/julia#11653]
A BigInt operation shouldn't ever come up with a BigFloat as result, as BigFloats do not have the same precision as BigInts:

    BigInt(1) / BigInt(3)

I want it to be a BigInt(0) then, not a BigFloat with 0.33333... as value. How can I get an BigInt only result at the end without loosing precision of an integer? I'm really stuck now as this was intended as a university project and now I can't go on without reimplementing BigInt division.

Kind regards,
Daniel

**Comment by nalimilan** [comment]
Looks like what you want is integer division then. Have a look at `div`:
```
julia> div(BigInt(1), BigInt(3))
0
```

Please use the mailing list for support requests in the future. GitHub is more for bug reports.

**Comment by Bradan** [comment]
Well, isn't this a bug then? Because normally one would never expect automatic conversion of this kind, not even python has this kind of conversion.

**Comment by nalimilan** [comment]
No, because division of two integers is not generally equal to an integer. Thus, most of the time, you want a float. Would you like `1/2` to return `0` too? Python 3 changed this to return `0.5`, as in Julia.

**Comment by nalimilan** [comment]
The PEP is worth a read. The reasoning applies to Julia too: https://www.python.org/dev/peps/pep-0238/

**Comment by Bradan** [comment]
Hmm well then, thanks for clarifying and sorry.

I'm a bit shocked about python3 now. +, -, * are all integer based operations when two integers are used, but / is now a floating point operation. The reasoning seems clear, but once someone needs an integer division (e.g. for fixed point arithmetic) he/she will think it is impossible.

Maybe julia should also support fixed point arithmetic in this case. Not only binary, but also decimal (e.g. for money values and so on). Nevertheless, I'll discuss this further on a julia mailinglist.

**Comment by nalimilan** [comment]
Decimal arithmetic has been discussed recently on the mailing list. See
https://github.com/stevengj/DecFP.jl
https://github.com/tinybike/Decimals.jl
