### ISSUE TITLE
Bus error, when calling from c

### ISSUE THREAD

**Issue by kzahedi** [JuliaLang/julia#11657]
Hi,

I have a strange situation. On my MBP, I run julia from within a C++ Code, which works fine (Mac OS X 10.10.3, Julia 0.3.8). I have now set-up an old MP with a cleanly installed Mac OS X 10.10.3 and with Julia 0.3.8 and want to run the very same code on that machine. But now I get:

signal (10): Bus error: 10
unknown function (ip: <some number>)
bus error 

I have no idea what the reason could be.

Cheers,
Keyan

**Comment by yuyichao** [comment]
I'm not an expert on embedding julia but I think it would be useful if you can at least provide some of your code.

**Comment by kzahedi** [comment]
Sure!

This is a general Julia-Importer for my simulator. It get the filename of some julia-source file and loads it. 

void Julia::init()
{
  string filename;
  string juliaDir;
  string logFileName;
  parameter.set("debug",         _debug,       false);
  parameter.set("file name",      filename,    "");
  parameter.set("log file name",  logFileName, "julia-controller.log");
  parameter.set("julia dir",      juliaDir,    ((string)JULIA_DIR) + ((string)"/bin"));

  if(filename == "")
  {
    cout << "Please give a julia file name." << endl;
    exit(-1);
  }

  if(_debug) cout << "Julia dir    " << juliaDir << endl;
  if(_debug) cout << "Reading file " << filename << endl;

  ifstream t(filename.c_str());
  string str((istreambuf_iterator<char>(t)), istreambuf_iterator<char>());

  if(_debug) _log.open(logFileName.c_str());

  if(_debug) cout << "Initialising julia." << endl;

  jl_init((char*)juliaDir.c_str());
  if(_debug) cout << "Initialising stack base." << endl;
  JL_SET_STACK_BASE;
  if(_debug) cout << "Reading julia file." << endl;
  void *ans = jl_eval_string(&str[0]);
  if(_debug) cout << "Done reading julia file." << endl;

  if (NULL == ans) {
    std::cerr << "Julia controller: error parsing julia source file" << std::endl;
    exit (1);
  }

  if(_debug) cout << "Getting update function." << endl;
  _update = (FuncPtr)jl_unbox_voidpointer((jl_value_t*)ans);

  int i = 1;
  stringstream oss;
  oss << "evaluation line " << i;
  vector<string> strs;
  while(parameter.exists(oss.str()))
  {
    strs.push_back(parameter.stringValue(oss.str()));
    i++;
    oss.str("");
    oss << "evaluation line " << i;
  }

  for(vector<string>::iterator s = strs.begin(); s != strs.end(); s++)
  {
    cout << *s << endl;
    ans = jl_eval_string((char*)(*s).c_str());
    if (NULL == ans) {
      std::cerr << "Julia controller: error parsing " << *s << std::endl;
      exit (1);
    }

  }
}


The julia code is of this form

function start_server(port)
  found  = false
  server = nothing
  while found == false
    try
      s = listen(port)
      println("waiting on port $port")
      server = accept(s)
      found = true
    catch
      port = port + 1
    end
  end
  return server
end

global rnn               = nothing
global t                 = 0
global server            = start_server(9500)

function update(n_::Ptr{Csize_t}, in_::Ptr{Cdouble},
                m_::Ptr{Csize_t}, out_::Ptr{Cdouble},
                l_::Ptr{Csize_t}, str_::Ptr{Uint8})
  command                 = ""
  str                     = ""
  n::Int64                = unsafe_load(n_)
  m::Int64                = unsafe_load(m_)
  l::Int64                = unsafe_load(l_)
  input::Vector{Float64}  = pointer_to_array(in_,  (n,))
  output::Vector{Float64} = pointer_to_array(out_, (m,))
  message::Vector{Uint8}  = pointer_to_array(str_, (l,))

  # some robot code

  unsafe_copy!(pointer(output),  pointer(o),   m)
  unsafe_copy!(pointer(message), pointer(str), l)

  return convert(Cint, status)
end

cfunction(update, Cint, (Ptr{Csize_t}, Ptr{Cdouble}, Ptr{Csize_t}, Ptr{Cdouble}, Ptr{Csize_t}, Ptr{Uint8}))


I should find the line "waiting on port 9500" on the console, but I get the error message instead.

**Comment by kzahedi** [comment]
I create a minimal example that works on both machines. I can't see the difference. Any help is highly appreciated:

```c++
#include <iostream>
#include <string>
#include <fstream>
#include <streambuf>
#include <julia.h>

using namespace std;

typedef int (*FuncPtr)(int, int);

#define JULIA_DIR (string)"/Applications/Julia.app/Contents/Resources/julia/"

int main()
{
  string filename = "test.jl";
  string juliaDir = ((string)JULIA_DIR) + ((string)"/bin");

  ifstream t(filename.c_str());
  string str((istreambuf_iterator<char>(t)), istreambuf_iterator<char>());

  cout << str << endl;

  jl_init((char*)juliaDir.c_str());
  JL_SET_STACK_BASE;
  void *ans = jl_eval_string(&str[0]);
  if (NULL == ans) {
    std::cerr << "Julia controller: error parsing julia source file" << std::endl;
    exit (1);
  }

  FuncPtr _run = (FuncPtr)jl_unbox_voidpointer((jl_value_t*)ans);

  cout << "Result from test.jl = " << _run(1,2) << endl;
}

```

Julia file

```jl

function update(a::Cint, b::Cint)

  c = a + b
  return convert(Cint, c)

end

cfunction(update, Cint, (Cint, Cint))

```

Makefile

```
all:
	c++ -g -o test test.cpp -I/Applications/Julia.app/Contents/Resources/julia/include/julia -L/Applications/Julia.app/Contents/Resources/julia/lib/julia -ljulia 
```

Output of ./test

```
> ./test                                                            ~/projects/mpi/julia/embedding.test
function update(a::Cint, b::Cint)

  c = a + b
  return convert(Cint, c)

end

cfunction(update, Cint, (Cint, Cint))

Result from test.jl = 3
```

**Comment by kzahedi** [comment]
Can be closed. I worked my way through it. The problem was not related to julia.

**Comment by vtjnash** [comment]
what was the solution?

**Comment by kzahedi** [comment]
Quite embarrassing. I gave a path to a non-existing julia file to load :)
