### ISSUE TITLE
Module exports that don't exist

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#11662]
Consider the following snippet:

```julia
julia> module Foo
       export x
       end

julia> using Foo

julia> x
ERROR: x not defined
```

I understand that it cannot be statically determined what names will be in scope to be exported from a module. However, I don't see why the error is raised when we specifically attempt to use `x` and not when `using Foo` is run. Shouldn't `using Foo` produce an error?

**Comment by StefanKarpinski** [comment]
Consider this:

```jl
julia> module Foo
           export x
           function define_x(val)
               global x = val
           end
       end

julia> using Foo

julia> Foo.define_x("this")
"this"

julia> x
"this"
```

There are cases where this kind of late binding is very useful.

**Comment by samuela** [comment]
Well, now that raises the question: why in the world can we introduce globals from inside functions? We no longer have lexical scope!

**Comment by johnmyleswhite** [comment]
This still seems to me like lexical scope: you can determine that the function defines a global using textual clues alone and don't need to know anything about the scope in which `define_x` is called at run-time.

**Comment by yuyichao** [comment]
1. It has the same effect with `eval`
2. It is necessary for runtime initialization of modules (inside `__init__`).

**Comment by samuela** [comment]
@johnmyleswhite I agree that it's lexical scope in the sense that scope is not defined at runtime. However, in a stricter sense I don't consider this to be lexical scope at all, since scope is no longer nested in the same way:

```julia
module Foo # scope A
  function define_x(val) # scope A u B
    global x = val
  end
  # At this point scope A should be unchanged.
end
```

So, `global x` here explicitly refers to `x` in scope A not in B, but no such identifier exists. We have one lexically enclosed block of code -- `function define_x(val) ... end` -- that *mutates* its surrounding scope! In Scheme terms this would be essentially equivalent to the following (broken) code

```scheme
(let []
  (define (f v) (define x v))
  (f 1)
  x)
```

which gives an unbound identifier error as expected.

On a related note, what exactly does "globality" mean? I read through the docs but they do not offer any specific definition. The best I can figure is that `global` is used to refer to the most immediate enclosing module scope. For example,

```julia
julia> module Foo
         function foo()
           global x = "foo"
         end
       end

julia> Foo.foo()
"foo"

julia> x
ERROR: x not defined
```

**Comment by samuela** [comment]
@yuyichao 

1. Right, but eval does not introduce a new lexical scope. In addition whenever eval/metaprogramming stuff is happening there is an understanding that program structure is being affected. In this case, the semantics (arguably) do not match the program structure.
2. I'm not really familiar with standard model design and initialization, so I can't really say anything here.

**Comment by yuyichao** [comment]
What I meant by `eval` is, `@eval a = 1` is the same with `global a = 1`.

**Comment by StefanKarpinski** [comment]
Export works on globals so arguments about lexical scope aren't really relevant.

**Comment by vtjnash** [comment]
the code for this is already written from when Stefan asked for this: see https://github.com/JuliaLang/julia/blob/debb22e5880d33a92c81a464954304fe948e58c0/src/toplevel.c#L184-L189 added by https://github.com/JuliaLang/julia/commit/006f2514523f667e1637042f27854e836cb7811b for #1127

**Comment by samuela** [comment]
So it looks like there are two issues here:

1. Globals can be introduced in functions, which essentially boils down to questions about scoping semantics. Still confused about this...
2. Module export behavior. As far as I can tell, the only reason for not throwing an error/warning in this case is if delayed initialization is necessary. However, I don't see the benefit of delayed initialization here. It introduces confusion and in any case where one might need it, a function could simply be used. For example,

```julia
julia> Base.LOAD_PATH # before it is initialized
ERROR: x not defined
```

is a really terrible error message to give the user. After all, isn't Base.LOAD_PATH exported and, furthermore, guaranteed by the documentation? etc.. Whereas,

```julia
julia> Base.LOAD_PATH()
<Base.LOAD_PATH() must handle initialization issues>
```

More importantly, in the former construction the burden of understanding the complicated and internal delayed initialized structure of the Base module is placed on the user of the module. In the latter case, the burden of handling internal initialization issues is rightly placed on the module itself.

**Comment by JeffBezanson** [comment]
The comparison to scheme is flawed. `(define x v)` actually corresponds to `x = v` or `local x = v` in julia, *not* `global x = v`. The `global` keyword makes all the difference, and has been lost in translation. `global x = v` is closer to a form like `set-top-level-value!` found in some scheme implementations (e.g. chez).

You are right that using a function instead of a variable may well be better API design. However in `LOAD_PATH()` there are two steps: get the value of the variable, then call it. This issue is only about the first of those steps.

**Comment by StefanKarpinski** [comment]
Regardless of comparisons to Scheme, what are the uses where we need binding done this late? May be worth putting them down here for the next time this comes up.

**Comment by JeffBezanson** [comment]
The big one is STDOUT, where lots of code refers to it, but it can't actually be set until we start up and have a real output stream.

**Comment by yuyichao** [comment]
Does `dlopen`'d handle in many packages count?

**Comment by samuela** [comment]
Still, what exactly does `global` mean? Global to the module? Global to all code at runtime?

**Comment by yuyichao** [comment]
Global to current module. (For REPL it's `Main`)
