### ISSUE TITLE
Printing of (empty) sparse matrix

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11661]
AFAICT it prints nothing right now and different matrixes are only separate by newlines even when they are not empty.

This is really confusing sometimes.

Ref #11658

**Comment by tkelman** [comment]
Ref https://github.com/JuliaLang/julia/blob/29d8c650010b5ee2a491ff6a56ae66a65d8d8788/base/sparse/sparsematrix.jl#L35-L61 - when printing the header is enabled, you should get `mxn sparse matrix with 0 Float64 entries:`. Since there are no nonzeros to then print, I think this bug just has to do with the decision of whether or not to print the header. Maybe it should always be enabled for `SparseMatrixCSC`? Or enabled no matter what when `nnz == 0`?

**Comment by yuyichao** [comment]
So why does it not always print the header to begin with? For printing as part of another matrixes? In that case, it feels similar to a quoting issue...

**Comment by jakebolewski** [comment]
The sparse behavior seems consistent with dense here.

```julia
print(zeros(0,0))
```

Prints no output.

**Comment by ViralBShah** [comment]
I am closing this unless we want to change both behaviours.

**Comment by carnaval** [comment]
Is it consistent though ? The sparse matrix is not 0 dimensional, only full of zeros.

**Comment by ViralBShah** [comment]
That is true, but what should we do?

**Comment by yuyichao** [comment]
FWIW, pylab print `zeros([0, 0])` as `[]` and empty sparse matrix as nothing ...

**Comment by tkelman** [comment]
We could add a special case for `nnz == 0`, printing some message like `< all zeros >` but that's a bit redundant with the header. Can anyone answer @yuyichao's question https://github.com/JuliaLang/julia/issues/11661#issuecomment-110956456 about what determines when the header is vs isn't printed?

> Is it consistent though ? The sparse matrix is not 0 dimensional, only full of zeros.

Depends what information you care about. If printing should only show the stored data, then yes it is consistent.

I'd prefer keeping the sparse matrix printing to only the (stored) nonzeros, as opposed to doing something like the way we currently print `Diagonal` where it takes a bunch of extra space printing zeros that you know are always there by the definition of the type. Would rather change the `Diagonal` printing to a nonzeros-only format like how `SparseMatrixCSC` prints, but that's a separate issue.

**Comment by JeffBezanson** [comment]
Please provide an example of the suboptimal output, and what you'd prefer it to look like.

**Comment by carnaval** [comment]
` `

**Comment by KristofferC** [comment]
Haha! :))

**Comment by yuyichao** [comment]
Example as @JeffBezanson

```jl
julia> show(sprand(5, 5, 0.0))

julia> print(sprand(5, 5, 0.0))

julia> print(sprandbool(5, 5, 0.0))

julia> show(sprandbool(5, 5, 0.0))
```

**Comment by Sacha0** [comment]
Close with #16945?

**Comment by tkelman** [comment]
Yep, thanks much! Good to have you around, what is it summer or something?

**Comment by Sacha0** [comment]
> Yep, thanks much! Good to have you around

A pleasure!

> what is it summer or something?

I can only spend so much time on thesis-related tasks before the drive to work on something that actually matters overwhelms me.
