### ISSUE TITLE
Julia installation with Juno and Light Table

### ISSUE THREAD

**Issue by Apocalypso18** [JuliaLang/julia#11666]
I am new to github and to programming as well. Hearing about open source Julia with its efficient use numeric computation, I wish to try Julia.
I went through download manuals and instructions and downloaded Julia 0.3.9 

, Juno and Light Table.
However, None of them can connect.I am working behind a public network proxy and i also tried "insteadOf" to use https but unexpected errors shows up
![untitled](https://cloud.githubusercontent.com/assets/12834282/8100980/325cf356-1030-11e5-880e-c1bd93346890.png)

Additionally Light Table cannot find "available plugins" in the plugin manager
![untitled1](https://cloud.githubusercontent.com/assets/12834282/8101026/9d66f1d8-1030-11e5-82f3-ca7abfc57163.png)

I am unfamiliar with metadata and dont know what the error means. 
If someone could help me install julia with Juno IDE from scratch and make it working, if its not too much to ask, It'd be of great help in evaluating Julia as a substitute for MATLAB in my work.

**Comment by Jutho** [comment]
May I refer you to the Julia users forum for such questions, where there will be many more people that can help you: https://groups.google.com/forum/#!forum/julia-users

The Github issues are reserved for actual issues with the julia language or standard library, and is mainly used and read by the developers.

**Comment by ScottPJones** [comment]
You need to issue the `git config`... command at the shell, not in Julia (or else use backtics etc. to run it from Julia)
