### ISSUE TITLE
Go performance code bottleneck in string formatting

### ISSUE THREAD

**Issue by akcom** [JuliaLang/julia#11674]
Line 191 of /test/perf/micro/perf.go
`s := fmt.Sprintf("%x", n)`
should be
`s := strconv.FormatUint(uint64(n),16)`

Results in a 2x speedup

**Comment by pao** [comment]
Care to make a pull request?

**Comment by ViralBShah** [comment]
Fixed by @kortschak in 7d19b52d3bb
