### ISSUE TITLE
Refs for BLAS calls causes performance hit for small matrices.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#11681]
With this benchmark:

```julia
function mmult(N, n)
    A = rand(n,n)
    B = similar(A)
    @time for i = 1:N
        A_mul_B!(B, A, A)
    end
end
```

I get the following on master:

```julia
julia> mmult(10^6, 6)
 621.537 milliseconds (10000 k allocations: 153 MB, 0.90% gc time)
```

With https://github.com/JuliaLang/julia/commit/62e5942c4d5b280d816e60bf364dc54284bd6e3a reverted:

```julia
julia> mmult(10^6, 6)
 208.683 milliseconds
```

Sort of dup of https://github.com/JuliaLang/julia/issues/11531 except this is in Base.  Imho it is not acceptable to double the time for matrix multiplication for smallish matrices.

**Comment by pao** [comment]
cc @simonbyrne

**Comment by andreasnoack** [comment]
@vtjnash Is this expected?

**Comment by jakebolewski** [comment]
I would think that this is due mostly to `Array` construction being special cased in the system.  I noticed a similar performance regression when the special casing of `Expr` object construction was removed.

**Comment by JeffBezanson** [comment]
Doesn't it have to do with `Ref`s being constructed, not Arrays?

**Comment by vtjnash** [comment]
it has to do with `Ref` objects being actually constructed rather than going through the painfully complex `&` handling (which does stack allocation).

this should be fixed by cleaning up https://github.com/JuliaLang/julia/pull/8134 so it can be merged

**Comment by simonbyrne** [comment]
We should probably revert the changes until #8134 is fixed

**Comment by ViralBShah** [comment]
+1 to reverting.
