### ISSUE TITLE
Deprecate sprandbool

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#11688]
Just like we deprecated `randbool`, we should probably deprecate `sprandbool`. While doing so, it would be nice to extend the `sprand` API to generate sparse matrices with all the element types the RNG supports, similar to the dense `rand`.

**Comment by tkelman** [comment]
related - #11557

**Comment by ViralBShah** [comment]
@KristofferC Would it be possible for you to address this in your recently opened `sprand` PR?

**Comment by KristofferC** [comment]
I would rather do that in a new PR. Easier in my opinion if the PRs are small and focus on one thing.

**Comment by ViralBShah** [comment]
Fair enough.
