### ISSUE TITLE
laplace equation benchmark performance

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#1168]
Track performance of the laplace equation benchmark. Discussion here:

https://groups.google.com/d/topic/julia-dev/VDlr3_6Szos/discussion

**Comment by ViralBShah** [comment]
I added a subarray version here, and it is significantly slower. I guess we have to wait for tuple overhaul. In any case, I was wondering if we can characterize why the vectorized version is so much slower (subarrays or otherwise), compared to the devectorized version. I was kind of hoping  that @carnaval 's GC work would help here, and I wonder if a better GC will help (perhaps tune some knobs in the new GC), or if the gains need to come from elsewhere.
````
julia> @time laplace_vec_sub();
elapsed time: 4.229344435 seconds (1028 MB allocated, 3.58% gc time in 47 pauses with 0 full sweep)

julia> @time laplace_vec();
elapsed time: 1.707854514 seconds (1715 MB allocated, 13.36% gc time in 78 pauses with 0 full sweep)

julia> @time laplace_devec();
elapsed time: 0.162232645 seconds (1 MB allocated)
````

**Comment by JeffBezanson** [comment]
I thought the new gc already helped here significantly. Though of course it does not close the whole gap. We should work on subarrays.

**Comment by ViralBShah** [comment]
If you see my older comment and the new results, the difference went from 13x to 10x. The new GC helped significantly on `bench_eu`, but not much on `laplace`.

**Comment by timholy** [comment]
I tried a subarray version a while ago, and it was a little faster. Can you link to your code?

**Comment by ViralBShah** [comment]
I have checked in the subarray version into laplace.jl. With tuple overhaul now, there are significant gains, but still too much memory allocation.

````
julia> @time laplace_vec_sub();
elapsed time: 2.958093484 seconds (1027 MB allocated, 3.30% gc time in 47 pauses with 0 full sweep)
````

**Comment by timholy** [comment]
It was an indexing problem, not a subarray problem. Fixed in #10858. Will be improved further if #9080 can be fixed.

Almost all of the remaining memory allocation comes from `A+B`, `c*A`, etc.

**Comment by timholy** [comment]
I should add: technically, with the new GC the performance problems are presumably more an issue of cache efficiency than memory allocation per se. When you allocate a temporary `C = A+B`, you traverse `A`, `B`, and `C`; then in `D = 2*C`, you traverse `C` again. In contrast, the devectorized version traverses everything once.

**Comment by carnaval** [comment]
Cache behavior is especially bad if you are allocating temps in a loop because you will get fresh (read: not cached) memory at each iteration up until collection, and start all over again.
With preallocation you get very good temporal coherency of course.
We may have a good solution for this kind of things at the end of the semester if all goes well :-)

**Comment by timholy** [comment]
> We may have a good solution for this kind of things at the end of the semester if all goes well :-)

Sounds like something to look forward to!

**Comment by ViralBShah** [comment]
I am really looking forward to it too!

**Comment by stevengj** [comment]
Hopefully the performance of the vectorized version will be fixed by #17623, assuming we change the code to use `.+` etcetera.

**Comment by StefanKarpinski** [comment]
Syntactic fusion seems like a completely fair solution to this performance issue.

**Comment by stevengj** [comment]
Even with loop fusion, this is still taking a lot more allocations than I would have expected:
```jl
julia> function laplace!(u, Niter, dx2, dy2)
           c = 1 / (2*(dx2+dy2))
           u0 = @view u[2:N-1, 2:N-1]
           u1 = @view u[1:N-2, 2:N-1]
           u2 = @view u[3:N, 2:N-1]
           u3 = @view u[2:N-1,1:N-2]
           u4 = @view u[2:N-1, 3:N]
           for i = 1:Niter
             u0 .= ((u1 .+ u2) .* dy2 .+ (u3 .+ u4) .* dx2) .* c
           end
           return u0
       end
laplace! (generic function with 1 method)

julia> u = zeros(150,150); u[1,:] = 1
1

julia> @time laplace!(u, 2^15, 0.01, 0.01);
  8.359097 seconds (6.66 M allocations: 188.045 MB, 0.36% gc time)

julia> @time laplace!(u, 2^15, 0.01, 0.01);
  8.051608 seconds (6.03 M allocations: 158.005 MB, 0.24% gc time)
```
@yuyichao, @pabloferz, any ideas?

**Comment by stevengj** [comment]
In comparison, an unrolled version does slightly better, which is not too unexpected — there is some overhead (less than a factor of 2) to using all of those views and generic broadcasting iteration:
```jl
julia> function laplace_iter!(u, Niter, dx2, dy2)
                  Ny, Nx = size(u)
                  c = 1 / (2*(dx2+dy2))
                  for iter = 1:Niter
                    for i = 2:size(u,1)-1, j = 2:size(u,2)-1 
                      u[i,j] = ((u[i-1,j]+u[i+1,j])*dx2 + (u[i,j-1]+u[i,j+1])*dy2)*c 
                    end 
                  end
                  return u
              end
laplace_iter! (generic function with 1 method)

julia> @time laplace_iter!(u, 2^15, 0.01, 0.01);
  4.281638 seconds (7.69 k allocations: 327.032 KB)

julia> @time laplace_iter!(u, 2^15, 0.01, 0.01);
  4.221090 seconds (5 allocations: 176 bytes)
```
But I think the vectorized version is fast enough that we can now close this?
