### ISSUE TITLE
Use opensuse toolchain to build windows binaries for WinRPM package compatibility

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#11682]
Compilation on windows+cygwin hangs at inference for an infinite amount of time (so far it hasn't stopped)
Maybe connected to a9915ff649befef665b3db83d9ee41d9014f37be ?

Compiler log: https://gist.github.com/SimonDanisch/df154b87b932f3b865db#file-compilationlog

Best,
Simon

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/julia/pull/10331#issuecomment-111451982 and https://github.com/JuliaLang/julia/pull/11678

**Comment by tkelman** [comment]
pull and try again

**Comment by SimonDanisch** [comment]
hmm... "julia.exe stopped working" when i start the binary dist. `make cleanall && make && make win-extras && make binary-dist` and then installed it without and with copying `julia/usr/lib/julia`

**Comment by SimonDanisch** [comment]
Interesting, from inside cygwin `make test` seems to work.
I wonder if I'm doing anything wrong while installing it. But I would not know what. I removed the old installation and installed the new one, like always. There is not that much to do wrong here, right?

**Comment by tkelman** [comment]
Had you done `make win-extras` a while ago and are you re-using the same build? You might need to update the win-extras files via `rm -rf dist-extras && make win-extras`

**Comment by SimonDanisch** [comment]
this does not seem to fix the issue :(

**Comment by tkelman** [comment]
I think this is at the root of the issues on appveyor right now, there was a change in upstream opensuse that may have broken our binaries.

**Comment by tkelman** [comment]
While I'm testing things out, if someone on Windows wants to just try downloading the latest nightly https://status.julialang.org/download/win64 and see whether it works properly, let me know. I think it might be broken but am busy working on fixing appveyor right now.

**Comment by SimonDanisch** [comment]
jupp its broken!

**Comment by tkelman** [comment]
Thanks. I think the short-term "rescue appveyor" fix is to stop pulling in the gcc dll's from opensuse in the nightly binaries, I'll do that shortly. This may however break IJulia due to zmq depending on libstdc++.

**Comment by tkelman** [comment]
Keep an eye on http://buildbot.e.ip.saba.us:8010/builders/package_win8.1-x64/builds/841, and when it's finished I hope we'll have things working again. But any C++ WinRPM packages like zmq, cbc, etc may be broken for a little while.

If anyone wants to help fix this permanently, we'll need to adapt `contrib/windows/winrpm.sh` to preserve paths from the extracted cpio download, and try to get a build working using the winrpm-downloaded mingw-w64 gcc, g++, and gfortran.

**Comment by tkelman** [comment]
The nightly and appveyor are fixed now. If someone wants to try installing the latest nightly and checking if, from a clean package directory, packages like zmq and cbc can work correctly, would be good to know. I'm working on trying to get the mingw-w64 toolchain from opensuse to work. MSYS2 might be easier to bring back support for than cygwin, will see.

**Comment by tkelman** [comment]
Closing in favor of #11705, please help review, test, and suggest additions to that.
