### ISSUE TITLE
Problems with local scope

### ISSUE THREAD

**Issue by krychu** [JuliaLang/julia#11696]
Hello,

Consider two examples:

```julia
x = 1
for i = 1:10
    x = 10
end
println( x )

out: 10
```

```julia
x = 1
function a()
    x = 10
end
a()
println( x )

out: 1
```

According to the docs both the ```for``` loop and the ```function``` definition should introduce a new scope with an inner variable ```x```. But this doesn't seem to be the case for the ```for``` loop. I'm sure I'm missing something (?)

Here's the relevant snippet from the docs:

"As a consequence, the only way to assign to a global variable inside a non-top-level scope is to explicitly declare the variable as global within some scope, since otherwise the assignment would introduce a new local rather than assigning to the global."

Mac OS, Julia 0.3.9

**Comment by yuyichao** [comment]
This is the documented correct behavior.

See http://julia.readthedocs.org/en/release-0.3/manual/variables-and-scoping/

In particular, the following text and the example below it.

> An assignment x = y introduces a new local variable x only if x is neither declared global nor introduced as local by any enclosing scope before or after the current line of code.

**Comment by yuyichao** [comment]
Actually when I read the document on the variable scope just now, it isn't very clear on what's the difference between a `let` block and a `function` in terms of scope. Maybe it can be improved?

@krychu also note that you didn't call the function in your second example (although it doesn't make a difference)

**Comment by krychu** [comment]
Sorry I forgot to add ```a()``` above (I've added it now). I've read the docs multiple times and it is not clear. Both ```for``` and ```function``` are listed in the docs as constructs introducing new scopes. So all further scope rules described in the docs should apply to them equally.

The docs says:
>When a variable is introduced into a scope, it is also inherited by all inner scopes unless one of those inner scopes explicitly overrides it.

and this:
> An assignment x = y introduces a new local variable x only if x is neither declared global nor introduced as local by any enclosing scope before or after the current line of code.

which would suggest ```for``` and ```function``` will inherit the outer ```x```.

Then the docs says:
>  ... the only way to assign to a global variable inside a non-top-level scope is to explicitly declare the variable as global within some scope, since otherwise the assignment would introduce a new local rather than assigning to the global.

which would suggest that ```for``` and ```function``` will introduce a new local variable ```x```.

**Comment by krychu** [comment]
Also this part is confusing

> [...] Due to the special identification of the prompt’s scope block with the global scope, it is not necessary to declare global y inside the loop. However, in code not entered into the interactive prompt this declaration would be necessary in order to modify a global variable.

which doesn't seem to be true as this script (run from outside the interactive prompt):

```julia
y = 0
for i = 1:1; y = 10; end
println( y )
```

modifies the global ```y``` without using ```global``` declaration within the loop.

I'm pointing these out so that the docs can be made clearer for newcomers (like me).

**Comment by mauro3** [comment]
This is soft vs hard scope of functions which is not described in the docs, its issue is #9955.  And also have a look at  #10559.  And if anyone improves the scope docs, the meaning of global should be defined: i.e. that a global is a module-wide global.  There are no truly global globals (which is different from Matlab).

**Comment by krychu** [comment]
Thanks!

**Comment by JeffBezanson** [comment]
Closing as dup of #9955.
