### ISSUE TITLE
Tuple gets Vararg parameters on function call

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#11712]
Consider:
```
julia> f{T}(t::Type{T}) = @show t,T
f (generic function with 1 method)

julia> f(Int)
(t,T) = (Int64,Int64)
(Int64,Int64)

julia> f(Tuple)
(t,T) = (Tuple,Tuple{Vararg{Any}})
(Tuple,Tuple{Vararg{Any}}) # is this correct? Would expect (Tuple,Tuple)
```
If this is not a bug, then why is this behavior?

**Comment by JeffBezanson** [comment]
They're the same, it's just a printing thing.

**Comment by mauro3** [comment]
Ok, I need to look through where I encountered this.  But I'm pretty sure it made a difference.

**Comment by mauro3** [comment]
Thanks, so the bug I had is over in #11715.  This just confused me hunting it down.
