### ISSUE TITLE
TypeVar parameter gets stuck on repated function calls

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#11725]
Running this:
```julia
abstract A{T,TT}

f{T}(sig::Type{T}) = @show T, sig

I = TypeVar(:I, Integer, true)
UI = A{I,I}

J = TypeVar(:J, Integer, true)
UJ = A{J,J}

f(UI)
f(UJ)

g{T}(sig::Type{T}) = @show T===sig
g(UI)
g(UJ)
```
produces:
```
## 0.3.9:
(T,sig) => (A{I<:Integer,I<:Integer},A{I<:Integer,I<:Integer})
(T,sig) => (A{I<:Integer,I<:Integer},A{J<:Integer,J<:Integer})
T === sig => true
T === sig => false

## 0.4.0-dev+5399
(T,sig) = (A{I<:Integer,I<:Integer},A{I<:Integer,I<:Integer})
(T,sig) = (A{I<:Integer,I<:Integer},A{J<:Integer,J<:Integer})
T === sig = false
T === sig = false
```

I'm not sure any of this is a bug, although the first `true` in 0.3 is certainly inconsistent.  Also, I think `g` returns true for all non typevar types, but I seem to recall that typevars have some problems with equality (but cannot find the issue where I read that).

**Comment by JeffBezanson** [comment]
`===` and `==` are not equivalent for types. What are you trying to do here?

TypeVars are not types and `===` simply compares them by identity.

**Comment by mauro3** [comment]
I stumbled across this when dissecting method signatures: finding in which arguments a parametric constraint occurs. Now this also features in [TupleTypes.jl](https://github.com/mauro3/TupleTypes.jl/blob/m3/changes/src/TupleTypes.jl#L10): it is necessary to to define a getter for type parameters like `getpara` and not like `getpara2`:
```julia
getpara{TT}(T::Type{TT}, i) = T.parameters[i]
getpara2{TT}(::Type{TT}, i) = TT.parameters[i]

f{T<:Integer}(::T) = 1
fm = first(methods(f))
g{I<:Integer}(::I) = 1
gm = first(methods(g))
@show getpara(fm.sig, 1)==fm.sig.parameters[1]
@show getpara(gm.sig, 1)==gm.sig.parameters[1]
@show getpara2(fm.sig, 1)==fm.sig.parameters[1]
@show getpara2(gm.sig, 1)==gm.sig.parameters[1]
```
outputs:
```
getpara(fm.sig,1) == fm.sig.parameters[1] = true
getpara(gm.sig,1) == gm.sig.parameters[1] = true
getpara2(fm.sig,1) == fm.sig.parameters[1] = true
getpara2(gm.sig,1) == gm.sig.parameters[1] = false
```

**Comment by JeffBezanson** [comment]
I think even just stylistically this makes sense; you want to access the representation of the argument, so in `T::Type{TT}` you definitely want to access `T`. We can't be required to make `T` and `TT` the exact same object.

**Comment by mauro3** [comment]
But that `T` and `TT` are not `===` can only happen with typevars, right?

You're right about dropping the method parameter, but originally it was `getpara{TT<:Tuple}(T::Type{TT}, i) = T.parameters[i]` where it is needed. 

Style-wise, I think it is usual to have a signature `f{T<:...}(::Type{T}, i) = ...`, thus that is what I first tried. Feel free to close.

**Comment by JeffBezanson** [comment]
I don't think it's wise to depend on `T === TT`.
