### ISSUE TITLE
New failure when building on Windows + LLVM SVN

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#11726]
Hi, 
I tried the 2 in 1 of rebuilding the Win LLVM3.7 version and using the @tkelman  tk/winbuild branch but I'm getting this error now. I suspect it has nothing to do with the winbuild branch but I'm mentioning it in case it does

    codegen.cpp: In function 'void jl_setup_module(llvm::Module*, bool)':
    codegen.cpp:708:63: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
         m->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                               ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    codegen.cpp: In function 'void jl_init_codegen()':
    codegen.cpp:5771:59: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
     m->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                           ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    codegen.cpp:5772:71: error: no matching function for call to 'llvm::Module::setTargetTriple(const llvm::Triple&)'
     engine_module->setTargetTriple(jl_TargetMachine->getTargetTriple());
                                                                       ^
    In file included from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22:0,
                 from codegen.cpp:12:
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note: candidate: void llvm::Module::setTargetTriple(llvm::StringRef)
    void setTargetTriple(StringRef T) { TargetTriple = T; }
        ^
    V:/julia/usr/include/llvm/IR/Module.h:294:8: note:   no known conversion for argument 1 from 'const llvm::Triple' to 'llvm::StringRef'
    Makefile:72: recipe for target 'codegen.o' failed

**Comment by tkelman** [comment]
what sha of my branch are you building from?

**Comment by joa-quim** [comment]
Don't know how to know that. Here's what I did
- A clean checkout of Julia `git clone https://github.com/JuliaLang/julia.git`
- followed by `git checkout tk/winbuild`
- than followed the instructions in you PR

**Comment by tkelman** [comment]
I've rebased that branch a few times, so it depends when you ran the checkout. What is the string of 20 hex characters when you do `git log -1` ?

**Comment by joa-quim** [comment]
I did it this afternoon. The commit is:
709b8f4dd374d50c1f523d325fd9276b43d4c23b

**Comment by tkelman** [comment]
Thanks, okay, I wanted to check whether or not the copy you built from contains the latest LLVM-svn fix that I've seen on master, 34d947e0bbfaeaac7dd8ab547a41e275c37dfa84. Looks like it does, so either this is new or it's Windows-specific.

**Comment by tkelman** [comment]
Looks like this also happens on Linux http://buildbot.e.ip.saba.us:8010/builders/build_llvmsvn_nightly-x64/builds/482/steps/make/logs/stdio, so it's not Windows-specific.

**Comment by joa-quim** [comment]
I still can build with the tk/wuinbuild branch. It now errors with

    LINK usr/bin/julia.exe
    JULIA usr/lib/julia/inference0.o

    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.
    Assertion failed!

    Program: V:\julia\usr\bin\julia.exe
    File: V:/julia/deps/llvm-svn/lib/IR/Instructions.cpp, Line 2267

    Expression: castIsValid(op, S, Ty) && "Invalid cast!"
    Makefile:176: recipe for target '/v/julia/usr/lib/julia/inference0.o' failed

**Comment by Keno** [comment]
+1 something is borked
```
julia: /home/kfischer/julia/deps/llvm-svn/lib/IR/Instructions.cpp:2378: static llvm::CastInst *llvm::CastInst::CreatePointerCast(llvm::Value *, llvm::Type *, const llvm::Twine &, llvm::Instruction *): Assertion `S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"' failed.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: -183762883)
unknown function (ip: -183762702)
_ZN4llvm8CastInst17CreatePointerCastEPNS_5ValueEPNS_4TypeERKNS_5TwineEPNS_11InstructionE at /home/kfischer/julia/usr/bin/../lib/libLLVM-3.7svn.so (unknown line)
CreatePointerCast at /home/kfischer/julia/usr/include/llvm/IR/IRBuilder.h:1315
emit_llvmcall at /home/kfischer/julia/src/./ccall.cpp:726
emit_call at /home/kfischer/julia/src/codegen.cpp:2631
emit_function at /home/kfischer/julia/src/codegen.cpp:4830
jl_eh_restore_state at /home/kfischer/julia/src/./julia.h:1389
jl_compile at /home/kfischer/julia/src/codegen.cpp:827
jl_trampoline_compile_function at /home/kfischer/julia/src/builtins.c:952
jl_apply at /home/kfischer/julia/src/./julia.h:1299
jl_apply_generic at /home/kfischer/julia/src/gf.c:1632
debugger at /home/kfischer/.julia/Gallium/src/Gallium.jl:45
do_call at /home/kfischer/julia/src/interpreter.c:55
eval at /home/kfischer/julia/src/interpreter.c:212
eval at /home/kfischer/julia/src/interpreter.c:218
eval_body at /home/kfischer/julia/src/interpreter.c:592
jl_toplevel_eval_body at /home/kfischer/julia/src/interpreter.c:527
jl_toplevel_eval_flex at /home/kfischer/julia/src/toplevel.c:517
jl_parse_eval_all at /home/kfischer/julia/src/toplevel.c:573
jl_load at /home/kfischer/julia/src/toplevel.c:616
include at ./boot.jl:254
include_from_node1 at ./loading.jl:133
do_call at /home/kfischer/julia/src/interpreter.c:55
eval at /home/kfischer/julia/src/interpreter.c:212
jl_toplevel_eval_flex at /home/kfischer/julia/src/toplevel.c:523
jl_toplevel_eval_in at /home/kfischer/julia/src/builtins.c:539
eval_user_input at ./REPL.jl:62
unknown function (ip: -176865936)
Aborted
```

**Comment by ihnorton** [comment]
https://github.com/JuliaLang/julia/pull/11743#discussion_r32698619

**Comment by tkelman** [comment]
@joq-quim you'll also need to rebase that branch since it isn't merged yet, I need to adjust the python-related parts of the instructions there.

**Comment by joa-quim** [comment]
Well, I returned to master I git a message that I was so 32 commits behind but that I could catch up wit git pull, which I did before running make again. Is this not enough?

**Comment by tkelman** [comment]
Sorry, I realized after posting and added in an edit that of course if you were able to compile against llvm-svn, you must've been on master. So if you run the `get_toolchain.sh` script while my branch is checked out, then switch to master and pull and build, you're fine.

**Comment by joa-quim** [comment]
Hi, 
I see several commits to deal with building with LLVM SVN but for me (on Windows) I still get (fresh checkout)

        CC src/debuginfo.o
    In file included from C:/MinGW64/mingw64/x86_64-w64-mingw32/include/c++/cassert:43:0,
                     from debuginfo.cpp:49:
    debuginfo.cpp: In member function 'virtual void JuliaJITEventListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&)':
    debuginfo.cpp:333:13: error: cannot convert 'llvm::object::Binary::isELF' from type 'bool (llvm::object::Binary::)() const' to type 'bool'
                 assert(obj.isELF)
                 ^
    debuginfo.cpp:333:13: error: in argument to unary !
    debuginfo.cpp: In function 'DWORD64 jl_getUnwindInfo(ULONG64)':
    debuginfo.cpp:922:68: error: 'struct ObjectInfo' has no member named 'size'
         if (it != objmap.end() && (intptr_t)(*it).first + (*it).second.size > dwAddr) {

**Comment by Keno** [comment]
Sorry about that, I do not generally test on windows. Try `isELF()` for the first and `second.SectionSize` for the second.

**Comment by joa-quim** [comment]
Sorry, don't understand your first change. If I do ``assert(obj.isELF())`` than it compains

    debuginfo.cpp:334:13: error: expected ';' before 'Size'
                 Size = obj.getSymbolSize(sym_iter);

Ii simply comment the assert line than

    debuginfo.cpp:334:24: error: 'const class llvm::object::ObjectFile' has no member named 'getSymbolSize'
                 Size = obj.getSymbolSize(sym_iter);

**Comment by ihnorton** [comment]
fixed by https://github.com/JuliaLang/julia/commit/937894c28e3af7070400f9f60312aca1575673d0
(there is a codegen failure but I will open a separate issue for that)

**Comment by joa-quim** [comment]
There is still a debuginfo

        CC src/debuginfo.o
    debuginfo.cpp: In member function 'virtual void JuliaJITEventListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&)':
    debuginfo.cpp:295:43: error: no matching function for call to 'llvm::object::SymbolRef::getType() const'
                 SymbolType = sym_iter.getType();
                                               ^
    debuginfo.cpp:295:43: note: candidate is:
    In file included from V:/julia/usr/include/llvm/DebugInfo/DIContext.h:20:0,
                     from V:/julia/usr/include/llvm/ExecutionEngine/RuntimeDyld.h:21,
                     from V:/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:18,
                     from debuginfo.cpp:6:
    V:/julia/usr/include/llvm/Object/ObjectFile.h:342:24: note: std::error_code llvm::object::SymbolRef::getType(llvm::object::SymbolRef::Type&) const
     inline std::error_code SymbolRef::getType(SymbolRef::Type &Result) const {

**Comment by Keno** [comment]
Your version of LLVM is probably outdated.

**Comment by joa-quim** [comment]
It was 11 days old. Updated, made ``make cleanall`` and ...

    llvm[3]: Linking Release+Asserts Shared Library LLVM-3.7svn.dll
    V:/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMBitReader.a(BitcodeReader.o):BitcodeReader.cpp:(.rdata+0x2608): undefined reference to `llvm::ConstantExpr::replaceUsesOfWithOnConstant(llvm::Value*, llvm::Value*, llvm::Use*)'
    collect2.exe: error: ld returned 1 exit status
    /v/julia/deps/llvm-svn/Makefile.rules:1206: recipe for target '/v/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/bin/LLVM-3.7svn.dll' failed
    make[3]: *** [/v/julia/deps/llvm-svn/build_Release+Asserts/Release+Asserts/bin/LLVM-3.7svn.dll] Error 1

**Comment by ihnorton** [comment]
Did you do `make -C deps update-llvm`? I'm able to fully build and bootstrap at https://github.com/JuliaLang/julia/commit/b2e69d0d871b65e70175ae088c77cb39b1e9a020.

**Comment by joa-quim** [comment]
I had done ``git pull`` inside deps/llvm-svn but now I did the ``make -C deps update-llvm`` deleted all .a and .o and now

        PERL base/version_git.jl.phony
        JULIA usr/lib/julia/inference0.o

    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.
    Assertion failed!

    Program: V:\julia\usr\bin\julia.exe
    File: V:/julia/deps/llvm-svn/lib/Object/COFFObjectFile.cpp, Line 944

    Expression: (Sec->Characteristics & COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA) == 0 && "BSS sections don't have contents!"
    Makefile:176: recipe for target '/v/julia/usr/lib/julia/inference0.o' failed
    make[1]: *** [/v/julia/usr/lib/julia/inference0.o] Error 3

**Comment by ihnorton** [comment]
Yes, I was seeing that before. It should be fixed by this change to re-enable ELF on Windows (vtjnash said he accidentally changed it), and my build now works fine: 

https://github.com/JuliaLang/julia/commit/b2e69d0d871b65e70175ae088c77cb39b1e9a020#diff-6d4d21428a67320600faf5a1a9f3a16aL6

**Comment by vtjnash** [comment]
yep, thanks!

**Comment by joa-quim** [comment]
OK, built here too (meanwhile I had made a clean restart) but now Julia very slow. It takes longer than 0.3 to start, the tests crash but before they crash

        From worker 5:       * linalg4              in  36.28 seconds
        From worker 5:       * linalg/lapack       Worker 5 terminated.Segmentation fault

whilst with LLVM3

        From worker 5:       * linalg4              in   7.86 seconds

Note however that LLVM versions are not the only difference. To build the LLVM SVN I use the new gcc as per @tkelman change mentioned in the beginning of this issue.

Oh, to finish this non related issues, Cxx (the main goal of these attempts of mine) fails
    
    julia> using Cxx
    dlerror loading 'libcxxffi': The specified procedure could not be found.

    ERROR: LoadError: LoadError: could not load library libcxxffi
    in init_libcxxffi at C:\j\.julia\v0.4\Cxx\src\initialization.jl:20
    while loading C:\j\.julia\v0.4\Cxx\src\initialization.jl, in expression starting on line 22
    while loading C:\j\.julia\v0.4\Cxx\src\Cxx.jl, in expression starting on line 154

**Comment by ihnorton** [comment]
That is probably worse than expected, but yes, there are still a number of known issues on llvm-3.6/svn, which is why those are not the default yet... https://github.com/JuliaLang/julia/issues/9336
