### ISSUE TITLE
Defining Julia version requirements in a package REQUIRE has no local consequence

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11734]
A package named `Foo` stored in the `.julia/v0.3` directory can only be used in REPL with Julia `v0.3.x`. So if you're on `v0.4-dev` the package will not load. This is expected behavior.

But if you locally change the Julia version requirements in package `Foo` from `v0.3` to `v0.4` in the `REQUIRE` file, the package will still load without warning or error. 
 
I'm guessing that once this change is made locally and then pushed to METADATA, the new commit will only update `Foo` that lives under `.julia/v0.4` and not the Foo that lives under `v0.3` but I'm not sure if this is true.

Scenarios:

1. Suppose I have `Foo` under both `.julia/v0.3` and `.julia/v0.4` with a `REQUIRE` of `julia 0.3` that is then changed to `julia 0.4-`. Will `Pkg.update()` touch the `Foo` that lives under `.julia/v0.3` when I execute it under a `0.3.x` session?

2. Now suppose I change the `REQUIRE` to `julia 0.5`. Will `Pkg.update()` simply ignore this commit in `0.3.x` and `0.4-dev` sessions?

3. If I'm new to `Foo` and I'm running Julia `v0.3.9` but want to check it out, will I be able to do so if the latest `REQUIRE` stipulates `v0.5`?

**Comment by wildart** [comment]
REQUIRE file is only used during a package dependency resolution procedure which happens when you update & (un)install packages. All version checks and decisions whether to install or not package happen on this step. Thus, if some package is already in `.julia/v0.x` folder, it is formally treated as installed but it will not be included in the dependency resolution procedure. Only properly installed packages (added with `Pkg.add`) will have dependencies automatically resolved.
Currently, if you change Julia version in REQUIRE file of the properly installed package you'll get a warning during the dependency resolution.

**Comment by milktrader** [comment]
So if the REQUIRE goes to `julia 0.y`, will properly installed packages in `.julia/v0.x` get the update _with_ the warning message?

It would seem better to _not_ update package `Foo` in `.julia/v0.x` once the package's REQUIRE goes to `.julia/v0.y`, no?

**Comment by tkelman** [comment]
Are you asking about changes of REQUIRE that come from local modification, or that come from updating METADATA?

**Comment by milktrader** [comment]
I guess at this point it's clear that nothing happens with changes to REQUIRE unless a `Pkg*` method looks at it. 

Modifying a local copy of REQUIRE without running `Pkg.update()` for example will not do anything, and it's designed to not do anything. 

I can experiment to answer the other scenarios I think without actually touching METADATA.

**Comment by wildart** [comment]
You can run `Pkg.resolve` and see what will happen.

**Comment by milktrader** [comment]
I have a package named `Three` in `.julia/v0.3`. It exports one `const three` and has only `julia 0.3` in its REQUIRE. 

````julia 
julia> using Three
julia> three
0.3
````
Then I change the require to `julia 0.4-` and add a `const four` to its exports.

````julia
julia> Pkg.update()

<bunch of messages>
WARNING: julia is fixed at 0.3.9 conflicting with requirement for Three: [0.4.0-,∞)
````
Then restart Julia `0.3.9`
````julia
julia> using Three

julia> three
0.3

julia> four
0.4
````
Which means that a warning was provided, but `0.4` crept into the package anyway.

**Comment by milktrader** [comment]
The only problem with this experiment is I don't know if METADATA will restrict putting code in `.julia/v0.x` if it has `julia 0.y-` in its REQUIRE. I didn't test that, I just simply changed the file that lives in `.julia/v0.3` without giving it a chance to suppress this.

**Comment by milktrader** [comment]
Yeah, the more I think about it I just hacked the system so all I've learned is that a warning message is generated, which is a good start.

Not sure how to test this otherwise without messing with METADATA unless I use a different METADATA, which iirc can also be done.

**Comment by milktrader** [comment]
I'm going to close this and make a more specific PR/issue concerning what happens to packages in `.julia/0.x` when the host package bumps its REQUIRE to `julia 0.y`.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/julia/issues/11752
