### ISSUE TITLE
read(STDIN,Char), 2 bugs

### ISSUE THREAD

**Issue by paulanalyst** [JuliaLang/julia#11746]
A. Why  I can`t to paste  to win console this code:
println("Write   't'  or  'n'   and press ENTER");var1=read(STDIN,Char);
if var1=='t' println("OK") else println("Error"); wait(); end;

from "if" disappears "i"

B. after run by include 3 lines are empty . File run.jl is coding UTF-8 without BOM

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

(paste 2 lines form Notepad++)
julia> println("Write   't'  or  'n'   and press ENTER");var1=read(STDIN,Char);
Write   't'  or  'n'   and press ENTER

julia> f var1=='t' println("OK") else println("Error"); wait(); end;
ERROR: syntax: extra token "var1" after end of expression

julia>

julia> include("run.jl")
Write   't'  or  'n'   and press ENTER
t
OK

julia>

julia>

julia>

Paul

**Comment by catawbasam** [comment]
I would recommend you update to 0.3.9, and then check whether you still see the problem.

**Comment by vtjnash** [comment]
> A. Why I can`t to paste to win console this code:

atomic paste this is a feature of most unix and mac terminals, but is not implemented in DOS. the result is that `i` is getting read into the `var1` variable by the call to read.

> B. after run by include 3 lines are empty . File run.jl is coding UTF-8 without BOM

you've read one Char out of the STDIN stream, but left the subsequent `\r` and `\n` characters in the stream, those get read (and "executed") by the next two prompt lines (leaving behind their empty prompts).

**Comment by JeffBezanson** [comment]
If you wrap the code in `begin ... end` it will force the whole thing to be read before it executes, and the `read` call shouldn't interfere with parsing.

**Comment by paulanalyst** [comment]
unfortunatly , is the same problem .  (In loop always 2 loops are going without control , only 1 for 3 waiting for choose. )
julia> begin
       println("Wpisz 't' lub 'n'");read(STDIN,Char);
       end
Wpisz 't' lub 'n'
t
't'

julia>

julia>

julia>

**Comment by paulanalyst** [comment]
for i=1:10
println(i)
println("if number is ok pres 'y'")
read(STDIN,Char);
end

I nead to vave control  the code in any steps on while . This while jump   1 > 4  > 7  >10 :/ 
How do it ?
Paul

**Comment by vtjnash** [comment]
> you've read one Char out of the STDIN stream, but left the subsequent \r and \n characters in the stream, those get read (and "executed") by the next two prompt lines (leaving behind their empty prompts).

...or in this case, the next two iterations of the for loop

**Comment by paulanalyst** [comment]
How to do it corectly , i must use win :/
