### ISSUE TITLE
merge() doc incomplete

### ISSUE THREAD

**Issue by nilsollers** [JuliaLang/julia#11748]
The docs do not specify the behavior of merge() when two collections contain the same key.  I haven't examined the source, but the value associated to such a key in the merged collection seems to be the value it has in the last collection listed.

**Comment by nalimilan** [comment]
Thanks. Would you prepare a pull request to document this? You can edit it online from the manual, by clicking on "Edit on GitHub" at the top of this page (and then on the small pen): http://docs.julialang.org/en/latest/stdlib/collections/?highlight=merge#Base.merge
