### ISSUE TITLE
bug in converting CHOLMOD factors to sparse matrix

### ISSUE THREAD

**Issue by joachimdahl** [JuliaLang/julia#11745]
The following code occasionally crashes under latest version of Julia 0.4

  A = sparse(Float64[ 10 1 1 1; 1 10 0 0; 1 0 10 0; 1 0 0 10])
  F = cholfact(A)
  sparse(F)

and when the code is executed in a Julia notebook, then the extracted factor is ordered differently from when the code is executed from a Julia shell; the underlying CHOLMOD factors are identical in both cases.

Furthermore, according to the documentation factors can be extracted as
<code>
F[:L]
</code>
but that results in the error:

LoadError: MethodError: `getindex` has no method matching     getindex(::Base.SparseMatrix.CHOLMOD.Factor{Float64,Int64}, ::Symbol)

**Comment by KristofferC** [comment]
Are you sure you are on the latest master? Support for extraction of factors was only added 12 daya ago: https://github.com/JuliaLang/julia/pull/10402

```julia
A = sparse(Float64[ 10 1 1 1; 1 10 0 0; 1 0 10 0; 1 0 0 10])
F = cholfact(A)
b = rand(4)
F[:L] \ b
```

Works for me. However, I am sometimes getting some scary segfaults.

See: https://gist.github.com/KristofferC/226785e7eb2db2db7726

**Comment by joachimdahl** [comment]
I think my Julia is up-to-date, I made a git pull && make before submitting this report.

What doesn't work seems to displaying F[:L]:
julia> F[:L]
Error showing value of type Base.SparseMatrix.CHOLMOD.FactorComponent{Float64,Int64,:L}:
ERROR: MethodError: `size` has no method matching size(::Base.SparseMatrix.CHOLMOD.Factor{Float64,Int64})
Closest candidates are:
  size(::Base.SparseMatrix.CHOLMOD.Factor{Tv,Ti}, ::Integer)
  size(::Any, ::Integer, ::Integer, ::Integer...)

For converting factors I resorted
<code>
L = sparse(CHOLMOD.Sparse(F))
</code>

which works as expected both in a Julia shell and when executed from a Julia notebook.

**Comment by KristofferC** [comment]
Yeah I noticed that show is not working, just opened an issue on it: https://github.com/JuliaLang/julia/issues/11747

However, computations with `F[:L]` works now, right? It is only the `show` that is not working.

Btw, are you getting any segfaults at all? Basically as soon as I do anything after running `sparse(F)` Julia will segfault.

**Comment by KristofferC** [comment]
This segfaults for me 100%:

```julia
A = sparse(Float64[ 10 1 1 1; 1 10 0 0; 1 0 10 0; 1 0 0 10])
typeof(sparse(cholfact(A)))
```

**Comment by joachimdahl** [comment]
I do not always get segfaults. If I execute some code before the call to sparse(), then sometimes I don't get segfaults.  Computation with F[:L] seems to work.

**Comment by andreasnoack** [comment]
There is something wrong in the indexing code for `SparseMatrixCSC`
```jl
Andreass-MacBook-Pro-2:julia-dev andreasnoack$ ./julia --check-bounds=yes
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+5437 (2015-06-18 02:27 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0bd3554* (0 days old master)
|__/                   |  x86_64-apple-darwin14.3.0

julia> A = sparse(Float64[ 10 1 1 1; 1 10 0 0; 1 0 10 0; 1 0 0 10]);

julia> sparse(cholfact(A))
ERROR: BoundsError: attempt to access 8-element Array{Int64,1}:
 1
 4
 2
 3
 3
 4
 2
 4
  at index [9]
 in getindex_I_sorted_linear at sparse/sparsematrix.jl:1467
 in getindex_I_sorted at sparse/sparsematrix.jl:1373
 in getindex_general at sparse/sparsematrix.jl:1600
 in getindex at sparse/sparsematrix.jl:1622
 in sparse at sparse/cholmod.jl:934
```
cc: @tanmaykm

**Comment by andreasnoack** [comment]
The row and columns pointers were not sorted when returned from CHOLMOD. I'll push a fix.
