### ISSUE TITLE
Names of types in core julia C code use `_t` which is reserved by Posix.

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11758]
Posix has the following rules for naming:
>Some additional classes of identifier names are reserved for future extensions to the C language or the POSIX.1 environment. While using these names for your own purposes right now might not cause a problem, they do raise the possibility of conflict with future versions of the C or POSIX standards, so you should avoid these names.
* Names beginning with a capital ‘E’ followed a digit or uppercase letter may be used for additional error code names. See Error Reporting.
* Names that begin with either ‘is’ or ‘to’ followed by a lowercase letter may be used for additional character testing and conversion functions. See Character Handling.
* Names that begin with ‘LC_’ followed by an uppercase letter may be used for additional macros specifying locale attributes. See Locales.
* Names of all existing mathematics functions (see Mathematics) suffixed with ‘f’ or ‘l’ are reserved for corresponding functions that operate on float and long double arguments, respectively.
* Names that begin with ‘SIG’ followed by an uppercase letter are reserved for additional signal names. See Standard Signals.
* Names that begin with ‘SIG_’ followed by an uppercase letter are reserved for additional signal actions. See Basic Signal Handling.
* Names beginning with ‘str’, ‘mem’, or ‘wcs’ followed by a lowercase letter are reserved for additional string and array functions. See String and Array Utilities.
* Names that end with ‘_t’ are reserved for additional type names.

Currently, esp. with regards to the last rule, the C/C++ code in julia does not conform to the Posix rules.
@StefanKarpinski had a suggestion (in #11751) of simply prefixing the types with `jl_`, which I believe to be the easiest way of making the julia internal type names not conflict with any future Posix/C additions,
while keeping the mnemonic usefulness of the `_t` suffix to mean type (even if it is still *technically* a violation).

I would like feedback on going ahead with doing a quick regex query/replace and fixing the type names so that they all are prefixed with `jl_` (most of them are already, just some like `arraylist_t` are not).

**Comment by StefanKarpinski** [comment]
I'd be in favor of this option.

**Comment by JeffBezanson** [comment]
Ha, maybe in 20 years POSIX will add three more functions. Laughable.

**Comment by ScottPJones** [comment]
You may laugh, but I've seen people be bit hard by this before... they added `char16_t`, `char32_t` not that long ago, and those also were names that people frequently come up with on their own.
They've added a *lot* more than 3 types in the last 20 years, and the C / C++ standards keep coming...

**Comment by carnaval** [comment]
probably not worth the trouble. if POSIX introduces lambda_info_t we'll reconsider.

**Comment by ScottPJones** [comment]
Adding `jl_` instead of removing the `_t`, as I suggested above, would deal with the potential problem, and has the benefit of making it clearer that the types are all part of julia, instead of possibly being system types (on some system).   Trouble would be very minor, and it would help future readers of the julia C code.
