### ISSUE TITLE
A_mul_B! with aliased source and destination

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#11756]
It seems there is a bug in A_mul_B! when both matrices have dimension (1, 1) 

```julia
a = fill(1.0, (1,1)) ;  b = fill(1.0, (1,1)) ; A_mul_B!(a, a, b)
#> 1x1 Array{Float64,2}:
#> 0.0
```
I expected the results to return 1 but it returns 0. This happens both in 0.3.9 and 0.4.0-dev+5446

**Comment by tkelman** [comment]
You need the source and destination to be separate arrays, and we need to document that requirement better.

**Comment by matthieugomez** [comment]
Does not it work when the matrices have higher dimension? My algorithm only failed when the matrices had dimension 1.

```
A = randn(2, 2) ;  B = randn(2, 2)
 A * B
#2x2 Array{Float64,2}:
# -2.11506   1.01405 
#  1.45091  -0.536067

A_mul_B!(A, A, B)
#2x2 Array{Float64,2}:
# -2.11506   1.01405 
#  1.45091  -0.536067
```

**Comment by andreasnoack** [comment]
Sizes `2x2` and `3x3` are handled separately. All other sizes are handled by BLAS, e.g.
```jl
julia> A, B = ones(4,4), ones(4,4);

julia> A_mul_B!(A,A,B)
4x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
```

**Comment by matthieugomez** [comment]
Thanks for renaming the issue & these great answers.

**Comment by andreasnoack** [comment]
This is now documented.

**Comment by simonster** [comment]
Might still make sense to make `A_mul_B!` throw an error when there's aliasing? Although this may be a bit hard to handle properly for SubArrays with non-unit strides that overlap but are not pointer-equal.
