### ISSUE TITLE
`cd` followed by `include` doesn't always work

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#11755]
So, this issue is fairly tricky for me to track down because it doesn't seem to happen all of the time and it only occurs on machines that I don't manage. Still, I have a particular script that writes a small Julia script to /tmp and runs it. The beginning of the Julia script looks something like

```julia
cd("$rootdir")
println(pwd())
include("relative/path/from/rootdir.jl")
...
```

Even though it cd's into $rootdir and prints $rootdir properly, the includes fail.

```
ERROR: could not open file /tmp/particlemethods/src/particlefilter.jl
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354
while loading /tmp/run_ex_particle_MAP_script_1596267_1.jl, in expression starting on line 2
```

**Comment by yuyichao** [comment]
IIRC `include` works with relative directory to the current file, not the current working directory

**Comment by Keno** [comment]
That's correct. Though the REPL's file path is implicitly the current working directory.

**Comment by samuela** [comment]
Hmm, so maybe in the cases where it worked I had accidentally changed something else.

**Comment by yuyichao** [comment]
Ahh. Right. Didn't noticed that it's REPL.

It's actually working here....

**Comment by yuyichao** [comment]
Sorry, the test you post is actually not the REPL. I would guess it works if you paste it into REPL and won't if you execute it as a script as what you have above.

**Comment by Keno** [comment]
`using`, `import` and (I believe) `require` also take the current working account.

**Comment by samuela** [comment]
Yeah, it always works in the REPL which is part of what made this so confusing for me.

**Comment by JeffBezanson** [comment]
Seems better to use `include(joinpath(pwd(), "path/file.jl"))` in this case, since it makes clear that the include needs to be relative to the working directory.
