### ISSUE TITLE
What happens to packages in .julia/v0.x when host package upgrades to julia 0.y

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11752]
So far, it appears only a warning message is provided.

````julia
WARNING: julia is fixed at 0.x.x conflicting with requirement for Foo: [0.y.0-,∞)
````
It's unclear if the package code in `.julia/v0.x` is upgraded with potentially breaking code when the author upgrades their REQUIRE to `julia 0.y`.

What _should_ happen is a message similar to the current one but maybe a little softer than a WARNING, something along the lines of 

````julia
PSA: The package Foo now requires version 0.y of Julia. Your copy in .julia/v0.x will no longer update. 
You may consider adding the package whilst in a Julia 0.y session to get the latest code.
````
And, as the new message states, `Pkg.update()` will not introduce `julia 0.y` code into a package located in a `.julia/v0.x` directory.

**Comment by tkelman** [comment]
It depends whether this happens via a new version of the package getting tagged that has an increased lower bound in require, or METADATA was modified to increase the lower bound in require for all past tagged versions of the package (I don't think this has ever happened yet), or you're getting the package in some way that isn't from a tagged version via clone, checkout, local modification, etc.

A notification that "the latest registered version of this package does not support the version of Julia you are using, you will not receive any future updates past the version you're currently using" might be worth doing, but there's always the possibility of a package continuing to tag separate releases from different branches, where the question of what version is the latest might be non-trivial to answer definitively.

**Comment by milktrader** [comment]
Now that you mention it, I do actually prefer the "nothing to see here just move along" approach to updates in `.julia/v0.x` when the package goes `julia 0.y`. A silent pass by where things just work.

**Comment by wildart** [comment]
Package will not be updated.

**Comment by milktrader** [comment]
Ok @wildart I'll add that to the doc section I'm working on, and close this issue.
