### ISSUE TITLE
--track-allocation=user misattributes allocation

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#11753]
The allocation profiler seems to misattribute allocations from a top-level call site to the callee.  Here is an example:

```
$ julia --track-allocation=user alloc-bug.jl
$ cat alloc-bug.jl.mem
        - function foo()
      224    s = 0
        0    s
        - end
        -
        - foo()
        - Profile.clear_malloc_data()
        - foo()
        -
```

The 224 allocations are not coming from inside `foo()`.  I suspect that they are coming from compilation of the second call site.  It would be good to have the allocations attributed to that call site.

P.S. A work around is to do something like:

```
for trial=1:2
    Profile.clear_malloc_data()
    foo()
end
```

so that the second time around, everything is compiled.

**Comment by rened** [comment]
FWIW, it is recommended to do it like this (call twice with `clear_malloc_data` in between) in the docs ([[1]](http://docs.julialang.org/en/latest/stdlib/profile/?highlight=clear_malloc_data#Base.Profile.clear_malloc_data)
 and [[2]](http://docs.julialang.org/en/latest/manual/profile/?highlight=clear_malloc_data#memory-allocation-analysis)). 

But of course it would be great to have this working with just 1 call.

**Comment by ArchRobison** [comment]
The recommended practice from the docs avoids seeing allocations arising from compilation.  But this seems to be a different problem: allocations being attributed to the wrong place.    I played around and found that even my work-around does not always dodge the problem.  Here is an example:
```
        - function foo{T}(a::Vector{T})
     8112     s = zero(T)
        0     for i=1:length(a)
        0         s += a[i]
        -     end
        0     s
        - end
        -
        - for trial=1:2
        -     Profile.clear_malloc_data()
        -     x = rand(1000)
        -     println(foo(x))
        - end
```
Despite calling `foo` twice and clearing the profile data in between, the profile generated from `--track-allocation=user` still shows fictitious allocations for the initialization of `s`.

**Comment by KristofferC** [comment]
I have seen this too. I remember I had a report of a huge allocation on the first line in a recursive function. I believe the reason  was that one of the arguments I passed was not "type stable" and needed unboxing.

**Comment by timholy** [comment]
The relevant line in the docs is

> the first line of any function directly called from the REPL will exhibit allocation due to events that happen in the REPL code itself.

This behavior follows from how this works: it asks "how much memory has been allocated since I last asked this same question?" and then assigns that to the current line. This only happens in code that is compiled, not in code that gets run from `interpreter.c`.

Presumably we could avoid this by using a macro that wraps your workload in a function call.

**Comment by ArchRobison** [comment]
Thanks for pointing out the "first line" notice.  Is the following a good practice to recommend for allocation profiling?
```
function foo{T}(a::Vector{T})
    s = zero(T)
    for i=1:length(a)
        s += a[i]
    end
    s
end

function wrap()         # Wrapper for workload
    x = rand(1000)
    println(foo(x))     # For compilation of workload
    Profile.clear_malloc_data()
    println(foo(x))     # Rerun workload
end

wrap()
```

**Comment by ArchRobison** [comment]
Back to the "how this works" item.  This seems like a fundamental bug, not something to cover up with a macro.  Can't the REPL ask the "how much memory has been allocated" question just before transfer of control to the function?

**Comment by timholy** [comment]
That sounds like a good plan to me. You should be able to `ccall` `sync_gc_total_bytes()` just before handing off?

**Comment by robsmith11** [comment]
Has there been a progress on this or new workarounds?  I'm still seeing misattributions with Julia 1.1.
