### ISSUE TITLE
Crash during tests in sub_fast with LLVM 3.4

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#11761]
I see this failure with Fedora nightlies with LLVM 3.4. It has been introduced over the last two or three weeks. See also https://github.com/JuliaLang/julia/issues/11760 : I'm not sure when one or the other happens, but these are on two different distro versions.

```
 /builddir/build/BUILD/julia/build/usr/bin/julia --check-bounds=yes --startup-file=no ./runtests.jl all
	From worker 3:	     * linalg2              in  85.89 seconds
	From worker 3:	     * linalg3              in  41.05 seconds
	From worker 2:	     * linalg1              in 143.13 seconds
	From worker 3:	     * linalg4              in  22.66 seconds
	From worker 2:	     * linalg/lapack        in  37.76 seconds
	From worker 2:	     * linalg/tridiag       in  22.18 seconds
	From worker 2:	     * linalg/bidiag        in  28.83 seconds
	From worker 2:	     * linalg/diagonal      in  32.03 seconds
	From worker 2:	     * linalg/pinv          in  13.75 seconds
	From worker 2:	     * linalg/givens        in   2.80 seconds
	From worker 2:	     * linalg/cholesky      in  23.20 seconds
	From worker 2:	     * linalg/lu            in  34.96 seconds
	From worker 2:	     * linalg/symmetric     in  45.59 seconds
	From worker 2:	     * linalg/arnoldi       in  37.17 seconds
	From worker 2:	     * core                 in 101.81 seconds
	From worker 2:	     * keywordargs          in  18.00 seconds
	From worker 3:	     * linalg/triangular    in 782.28 seconds
	From worker 2:	     * numbers              in 562.26 seconds
	From worker 3:	     * strings              in 334.97 seconds
	From worker 3:	     * dict                 in 101.83 seconds
	From worker 3:	     * hashing              in 250.45 seconds
	From worker 3:	     * remote               in   3.56 seconds
	From worker 3:	     * iobuffer             in  23.88 seconds
	From worker 3:	     * staged               in  24.35 seconds
	From worker 2:	     * dates                in 571.13 seconds
	From worker 2:	     * tuple                in  39.55 seconds
	From worker 3:	     * arrayops             in 601.16 seconds
	From worker 3:	     * reduce               in  78.05 seconds
	From worker 3:	     * reducedim            in 190.54 seconds
	From worker 3:	     * random               in 328.46 seconds
	From worker 3:	     * intfuncs             in  36.57 seconds
	From worker 3:	     * simdloop             in  23.35 seconds
	From worker 3:	     * blas                 in  95.02 seconds
	From worker 3:	     * sparse               in 642.17 seconds
	From worker 2:	     * subarray             in 2389.31 seconds
	From worker 2:	     * copy                 in  36.57 seconds
	From worker 2:	     * math                 in 236.53 seconds
	From worker 3:	     * bitarray             in 744.55 seconds
	From worker 3:	     * functional           in  27.87 seconds
	From worker 3:	     * operators            in   7.31 seconds
	From worker 3:	     * path                 in  18.64 seconds
signal (11): Segmentation fault
sub_fast at ./fastmath.jl:214
jl_apply at /builddir/build/BUILD/julia/src/julia.h:1298
do_call at /builddir/build/BUILD/julia/src/interpreter.c:66
eval at /builddir/build/BUILD/julia/src/interpreter.c:212
jl_interpret_toplevel_expr at /builddir/build/BUILD/julia/src/interpreter.c:28
jl_toplevel_eval_flex at /builddir/build/BUILD/julia/src/toplevel.c:525
jl_eh_restore_state at /builddir/build/BUILD/julia/src/julia.h:1388
jl_f_top_eval at /builddir/build/BUILD/julia/src/builtins.c:569
anonymous at ./test.jl:91
do_test at ./test.jl:49
anonymous at ./no file:156
jl_trampoline at /builddir/build/BUILD/julia/src/builtins.c:965
jl_toplevel_eval_flex at /builddir/build/BUILD/julia/src/toplevel.c:540
jl_toplevel_eval_flex at /builddir/build/BUILD/julia/src/toplevel.c:569
jl_load at /builddir/build/BUILD/julia/src/toplevel.c:616
jl_load_ at /builddir/build/BUILD/julia/src/toplevel.c:622
include at ./boot.jl:254
jl_apply at /builddir/build/BUILD/julia/src/julia.h:1298
runtests at /builddir/build/BUILD/julia/test/testdefs.jl:198
unknown function (ip: -816032829)
jl_apply at /builddir/build/BUILD/julia/src/julia.h:1298
jl_f_apply at /builddir/build/BUILD/julia/src/builtins.c:473
anonymous at ./multi.jl:822
run_work_thunk at ./multi.jl:575
jl_apply at /builddir/build/BUILD/julia/src/julia.h:1298
anonymous at ./multi.jl:822
start_task at /builddir/build/BUILD/julia/src/task.c:234
	From worker 2:	     * fastmath            Worker 2 terminated.
ERROR (unhandled task failure): EOFError: read end of file
 in yieldto at ./task.jl:21
 in wait at ./task.jl:309
 in wait at ./task.jl:225
 in wait_full at ./multi.jl:558
 in remotecall_fetch at ./multi.jl:658
 in remotecall_fetch at ./multi.jl:663
 in anonymous at ./task.jl:1372
	From worker 3:	     * ccall                in  76.12 seconds
ERROR: LoadError: ProcessExitedException()
 in yieldto at ./task.jl:21
 in wait at ./task.jl:309
 in wait at ./task.jl:225
 in wait_full at ./multi.jl:558
 in remotecall_fetch at ./multi.jl:658
 in remotecall_fetch at ./multi.jl:663
 in anonymous at ./task.jl:1372
while loading /builddir/build/BUILD/julia/test/runtests.jl, in expression starting on line 5
WARNING: Forcibly interrupting busy workers
WARNING: Unable to terminate all workers
Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/julia/test'
Makefile:508: recipe for target 'test' failed
make: *** [test] Error 2
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-21-i386/julia-0.4.0-0.20150618.fc21/build.log.gz

**Comment by JeffBezanson** [comment]
Haven't we been over this before? We don't support LLVM 3.4.

**Comment by StefanKarpinski** [comment]
Yeah, we really need to stop trying to support a large range of LLVM versions. There should be one and only one LLVM version that we support and any given time and we should have our own forked repo that includes any patches we need to make various things like Cxx and the debugger work. We'll continue to work to upstream those patches, but the current situation where we try to make things work with lots of different LLVM versions is totally crazy.

**Comment by nalimilan** [comment]
Well, every time I found a bug in LLVM 3.4 it got fixed relatively quickly until now. ;-)

I can't tell how much work it will require, but if that's reasonable (as it's apparently been until now), fixing this kind of crash is helpful for Fedora/RHEL packaging. At least, as long as LLVM 3.3 is the default and people are working to keep LLVM SVN working, it can make sense to support intermediate versions. Of course, when we switch to 3.7, I won't object to dropping older releases if that's too much of a burden.

Anyway, do what you think is reasonable, but please do not rely on local forks of LLVM. That would be a showstopper for packagers, as no distro will accept bundling a custom LLVM build inside of the Julia package.

**Comment by JeffBezanson** [comment]
The real problem is that when we switch to LLVM 3.7, fedora might very well switch to LLVM 3.6 or 3.8, and we'll be in the same situation again.

**Comment by nalimilan** [comment]
To be precise, LLVM 3.4 is in Fedora 20 and 21, and in RHEL 7. Fedora 22 (most recent) is using 3.5. Your're right there's no great solution to this at the moment. I think I said elsewhere that I may be able to ship a versioned, parallel-installable LLVM if that's really needed to keep Julia in the official repos.

But my request about LLVM 3.4 was just for the custom RPM repository offering backports/nightlies, where I find it easier to use the official LLVM. I can ship a custom version if that's really needed.

**Comment by JeffBezanson** [comment]
> ship a versioned, parallel-installable LLVM

That's really the only thing that can work in general. For example, all distros have packages for both python 2 and python 3, because they're incompatible. And I believe a python install is much bigger than an LLVM install.

**Comment by nalimilan** [comment]
> That's really the only thing that can work in general. For example, all distros have packages for both python 2 and python 3, because they're incompatible. And I believe a python install is much bigger than an LLVM install.

Yeah, but Python 2 and Python 3 are backward-compatible, while LLVM breaks API every six months. Distros don't like too much creating new packages and removing them in the next one. They are also afraid that e.g. if Rust wanted yet another version, we would end up with three LLVM packages in Fedora. (Though I hope I can convince them...)

**Comment by StefanKarpinski** [comment]
> Python 2 and Python 3 are backward-compatible

Huh? Python 3 notoriously breaks compatibility with Python 2.

If distros don't wan't to have different packages for the different *wildly* incompatible versions of LLVM, that's fine, but I think that the Julia packages for distros should simply include LLVM as part of the build for Julia. It's not really an external library dependency – it's part of Julia's runtime. The fact that it's build as a shared library is kind of a red herring.

**Comment by nalimilan** [comment]
> Huh? Python 3 notoriously breaks compatibility with Python 2.

Ah, I knew I had to make it explicit. ;-) I meant that once you have packaged both, you can update the two packages without breaking applications relying on them.

I don't think anybody will win the fight of bundling LLVM into Julia. I would already be happy enough if it we obtained the version we want as a separate package. Hell, there's a whole wiki page just to explain that you should avoid bundling: https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries

**Comment by StefanKarpinski** [comment]
I guess we all just have to accept that distro policies imply that they will always end up with second-class, borderline-broken versions of many kinds of software.

**Comment by IainNZ** [comment]
I just skimmed that wiki page, and it blows my mind that they could simultaneously have those policies but not package multiple LLVM versions, it just seems irreconcilable.

**Comment by nalimilan** [comment]
@IainNZ As I said, packaging several LLVM versions should be possible, if I was to argue that Julia wouldn't work at all without that. What's really discouraged is bundling programs within packages, at it makes it very hard to handle bugfix and security updates and generally creates unnecessary duplication.

**Comment by JeffBezanson** [comment]
I'm perfectly fine with not bundling LLVM, and not using a custom version of LLVM. All I want is an ordinary released version of LLVM that we actually test against and support. Providing packages for 2 or 3 LLVM versions ought to be acceptable.

**Comment by tkelman** [comment]
Yell, kick, and scream at LLVM distro maintainers and LLVM upstream developers until we can figure out a way to package multiple LLVM versions from upstream at the same time. The maintainers are lazy and want to delete old versions, their excuse is "upstream says this is no longer maintained." With the current situation where LLVM is actually making backport point releases these days, maybe we can change that situation. Don't a bunch of distributions have multiple gcc versions all still packaged back to 4.4 that you can install and use as `gcc-4.4` if you want to?

Rust isn't in Fedora or Debian yet (the dangers of self-hosting), but when they are, along with Haskell's LLVM backend and other things we should all be using unpatched LLVM sources from upstream, ideally. If we (or other out-of-tree LLVM users) end up needing patches, we should figure out how to make sure those patches get tested against all LLVM reverse-deps.

For now we have an ifdef-soup to keep maintaining LLVM 3.3 support alongside best-effort support for LLVM svn plus as many other versions in between as we can stand. Until LLVM stops changing API's I don't think there's much we can do to change this situation.

**Comment by tkelman** [comment]
> It's not really an external library dependency – it's part of Julia's runtime.

That doesn't have to be the case forever. What ever happened to the plan to split out the codegen parts into a separate library from the runtime? libjulia is a bit on the large size and has a few too many miscellaneous things statically linked into it right now that likely won't always need to be.

**Comment by StefanKarpinski** [comment]
> That doesn't have to be the case forever.

Sure, but I don't think that's particularly feasible until the LLVM API settles down. Until then, we're quite closely tied to a specific version of LLVM.

**Comment by tkelman** [comment]
That's not what I meant, I was referring to some discussion (wasn't a whole lot, and it was a while ago) to split out codegen into a different library from the rest of libjulia.

**Comment by nalimilan** [comment]
I'm going to use a parallel-installable LLVM 3.3, so closing.

**Comment by tkelman** [comment]
Did Fedora finally change their minds on this?

**Comment by nalimilan** [comment]
I think I noted this elsewhere on a similar issue, but basically yes. The LLVM maintainer has already packaged LLVM 3.4 for the Haskell compiler, and we exchanged reviews to package 3.3 (for Julia) and 3.5 (for Haskell). So it should work in the end (for now, I'm using 3.6, which is more or less OK except for one test).

See https://bugzilla.redhat.com/show_bug.cgi?id=1109390

**Comment by nalimilan** [comment]
For reference, Fedora now ships with a parallel-installable LLVM 3.3 package for a few months.
