### ISSUE TITLE
can't quote using and import statements

### ISSUE THREAD

**Issue by swadey** [JuliaLang/julia#11785]
I can't seem to quote these expressions either using `quote` or via `:()`.  I can explicitly construct an `Expr` object which `eval()`s properly.  Perhaps I'm misunderstanding something here.  The transcript below is from `Version 0.3.10-pre+33 (2015-06-19 02:17 UTC)`.  The specific commit is: `Commit 2c2e696* (1 day old release-0.3)`

```julia
julia> :(using ZMQ)
ERROR: syntax: invalid "using" statement

julia> :(import ZMQ)
ERROR: syntax: invalid "import" statement

julia> quote using ZMQ end
ERROR: syntax: invalid "using" statement

julia> quote import ZMQ end
ERROR: syntax: invalid "import" statement

julia> Expr(:using, :ZMQ)
:($(Expr(:using, :ZMQ)))

julia> Expr(:import, :ZMQ)
:($(Expr(:import, :ZMQ)))
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/10910 fixed in master. Probably not worth backporting.

**Comment by yuyichao** [comment]
See the comment of #10910 for workaround on 0.3. You can construct the `Expr` directly if necessary, or you can add a semicolon if it's good enough for you.

**Comment by swadey** [comment]
@yuyichao thx!
