### ISSUE TITLE
cmd line mode

### ISSUE THREAD

**Issue by 0x75** [JuliaLang/julia#11784]
Hello,

it would be cool to have a 'command line mode' in the interactive shell that could be called on demand (to not pose a security risk or iJulia environments). 

having shell commands written in julia would be cool but maybe too much work an to slow. So
making it possible to access and easily process shell commands  would be cool. 

auto_parsing and thus piping of cmd output to datatypes would be very helpful.
2dimArray << dtrace(some insane script to catch all short-lived processes).

So you could instantly generate advanced system statistics, as well as
develope a personal library of cods/julia code. 

Acessing system internals and sysapis and their stats will be very beneficial for detailed
visualization of system use. Think of a visualized dtrace just as example.

**Comment by simleb** [comment]
It is already there. Just type `;` at the REPL.

**Comment by jiahao** [comment]
Please reopen if the `;` mode of the REPL does not already do what you want.
