### ISSUE TITLE
atsign-doc forces functions to be imported/extended

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#11798]
This works:
```jl
module Doc

@doc "read" ->
Base.read(filename) = 1

end
```
but if you take away the `Base.` (to require folks to call `read` as `Doc.read`) then you get
```jl
julia> using Doc
ERROR: LoadError: error in method definition: function Base.read must be explicitly imported to be extended
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /tmp/Doc.jl, in expression starting on line 3
```
Naturally, a function that does not have a name-conflict with Base does not have this problem.

**Comment by MichaelHatherly** [comment]
@one-more-minute I've got a *possible* fix for this. Unless you've been working on this already I'll PR it in a bit.

**Comment by one-more-minute** [comment]
Sure, would be great to see what you got.
