### ISSUE TITLE
Segfault in close callback at the end of `make testall1`

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#11807]
This will make win64 appveyor fail on a bunch of PR's (should look roughly like https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.5928/job/90vkkfxd8kh8td0l) until someone either fixes it or reverts 1e081b79ed6d24864cec1216a9b7bbe3c8a329e6.

Running tests in parallel concealed this bug, a bisect identified 176ca4f8e1de4998023818ab43dc038e4e535c3a as the first bad commit that introduced it. I've gotten it to happen on win64 and linux 64, but much more consistently on win64. I'll try to get a backtrace before I have to get on a plane.

**Comment by tkelman** [comment]
Running julia-debug under gdb on linux, I get this assertion failure: https://gist.github.com/tkelman/f0a7debc2fb6234eefcc

**Comment by pao** [comment]
> Running tests in parallel concealed this bug

This comment is inherently troubling. Do we understand the interaction between not seeing this bug and running tests in parallel?

**Comment by JeffBezanson** [comment]
@Keno and I found that running just the `file` test reliably caused this problem, and this patch made it go away. However we don't fully understand why.
