### ISSUE TITLE
Equal immutables are stochastically unequal

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#11813]
```julia
julia> immutable PaddingTest
           x::Int64
           y::Int8
       end

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
true

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
true

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
false

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
false

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
false

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
true

julia> PaddingTest(1, 1) == PaddingTest(1, 1)
true
```

The problem is that we're emitting a `memcmp` call that tries to check the equality of all 16 bytes, but we should really only be checking the first 9. This also fails if the order of `x` and `y` in `PaddingTest` are reversed, which is a slightly more complicated case, because we only want to compare the first byte and the last 8 bytes and not the 7 in between.

I believe #11644 is the culprit (cc @vtjnash). I suspect that `memcmp` is also inefficient. LLVM doesn't appear to eliminate the call to `memcmp`, which is probably much more costly than the equivalent handful of assembly instructions.

**Comment by StefanKarpinski** [comment]
Zeroed memory would fix it too.

**Comment by Keno** [comment]
No, it wouldn't. LLVM aggressively optimizes here.

**Comment by yuyichao** [comment]
Nice collaboration....
