### ISSUE TITLE
Appveyor freezing during cmdlineargs test

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#11818]
The first build against master where this happened is https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.5994/job/l01nwf0rwaedju0o, for 6ec7c21ff66bb5ec31e674134976d4c5beac7322

I can reproduce locally, will try to see whether it's repeatable or intermittent (once I walk over to stata)

**Comment by tkelman** [comment]
While this might be #7942, something caused this to get much more frequent, starting last night.

Might be related to https://github.com/JuliaLang/julia/blob/5651bba4f1bcf860202e320aecd3d8e7bad3c0d8/test/cmdlineargs.jl#L88 which was not updated with #11420, and whatever caused https://github.com/JuliaLang/julia/issues/7174#issuecomment-110985417 may be related.

**Comment by carnaval** [comment]
> (once I walk over to stata)

yay !

**Comment by tkelman** [comment]
This may not be entirely accurate if the problem is intermittent, I'll try re-running the cmdlineargs test multiple times at the "good" entries below and see if it's consistent.
```
$ git bisect log
git bisect start
# bad: [bca9e80d42f84b29743a42e201fc11bf9f8f2085] Merge pull request #11600 from yuyichao/code_typed-fix
git bisect bad bca9e80d42f84b29743a42e201fc11bf9f8f2085
# bad: [fc604d1c0558d81943815c48167a895fe43b5868] Merge branch 'docs-refactor'
git bisect bad fc604d1c0558d81943815c48167a895fe43b5868
# good: [62a113abeb442d7f019d8a9e14d42c0d771d53f2] Update control-flow.rst
git bisect good 62a113abeb442d7f019d8a9e14d42c0d771d53f2
# good: [fcebf798fc3d8b548dca810cf62017049b5f5964] Merge pull request #11775 from JuliaLang/ksh/linalgtest
git bisect good fcebf798fc3d8b548dca810cf62017049b5f5964
# good: [8faa579986335b5f6b752768b8fa198bbdc935c4] Merge pull request #11806 from mbauman/mb/test10525
git bisect good 8faa579986335b5f6b752768b8fa198bbdc935c4
# bad: [67ab54b477d6cd93f06a1849585ac85118b3471a] Merge pull request #11640 from JuliaLang/jb/outputoptions
git bisect bad 67ab54b477d6cd93f06a1849585ac85118b3471a
# good: [f1b7b6267b35cc3c4f99ca5acd3d3c9ccba5f151] Add informative comment.
git bisect good f1b7b6267b35cc3c4f99ca5acd3d3c9ccba5f151
# good: [d99c23758ca8a20f9b5b1f969e41cd5e0bd32bd5] Merge pull request #11799 from Ismael-VC/sort-coverage
git bisect good d99c23758ca8a20f9b5b1f969e41cd5e0bd32bd5
# good: [a703799d8827c9a7a14fb9a070be909e625afea0] simplify build and output options to --output-o, --output-ji, and --output-bc with filenames.
git bisect good a703799d8827c9a7a14fb9a070be909e625afea0
# first bad commit: [67ab54b477d6cd93f06a1849585ac85118b3471a] Merge pull request #11640 from JuliaLang/jb/outputoptions
```

**Comment by tkelman** [comment]
a703799d8827c9a7a14fb9a070be909e625afea0 froze on a second attempt, but 1e081b79ed6d24864cec1216a9b7bbe3c8a329e6 passed 8 times in a row. So this is caused by #11640

**Comment by JeffBezanson** [comment]
@vtjnash points out that the cmdlineargs test consists of starting julia many times, and #11640 makes windows build a .ji and not a .dll by default, making startup take much longer. So we could maybe fix it by telling the appveyor build to build sys.dll. Or make sys.dll the default, and only change it when building release packages. Either way.

**Comment by tkelman** [comment]
Yes, I would expect that change to make cmdlineargs slower - compare after https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.5999/job/kdn69hwhfqbv3vx8 (231 s) vs before https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.5959/job/t6gleq8mpnp123oo (41 s).

It's freezing, not just slow.

**Comment by tkelman** [comment]
Unrelated, but PSA: because a day is not allowed to go by without julia breaking on appveyor in new and exciting ways, the new failure mode today as in https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.6008/job/0u8vmb335kfyc0bx was short rather than a timeout - at least it works through the backlog quicker than a timeout.

The reason for today's new failure to compile was what happens when `llvm-config.exe` does not run correctly, we get an empty cflags and none of the llvm includes can be found. The reason `llvm-config.exe` stopped running is because we got new nightly binaries built after a cygwin mingw-w64 cross-compiler update, as discussed here https://github.com/staticfloat/julia-buildbot/issues/20#issuecomment-113966130. I prepared ahead for this over the weekend and pre-built LLVM and packaged the opensuse toolchain and put it up on sourceforge, and just pushed 47b62b7f6db85993d56f83a83c1cabfe7e73fa3a so that appveyor will use them.

**Comment by tkelman** [comment]
Oh, for crying out loud, that's broken too (╯°□°）╯︵ ┻━┻

**Comment by tkelman** [comment]
Sometimes this has also been freezing in `spawn` or `repl`

**Comment by JeffBezanson** [comment]
So is the conclusion that `--precompiled=yes` doesn't fix the problem? It seems to help a bit maybe?

**Comment by tkelman** [comment]
It makes the cmdlineargs test not take quite as long. I'm willing to close this as effectively a duplicate of #7942 though since I suspect it's the same problem.
