### ISSUE TITLE
Have a script to fix whitespace and run it periodically.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julia#11830]
Refs: 
- https://github.com/JuliaLang/julia/pull/11766#issuecomment-113635343
- https://github.com/JuliaLang/julia/pull/11770#issuecomment-113664843

I leave this here as a reminder, because I suspect I'll be causing more troubles while using the online editor, and while I'll be paying a lot more of attention, it seems that we agree about this.

**Comment by tkelman** [comment]
+1.

A neat trick is if you take a commit or `/pull/####/files` url from github and add `?w=1` to the end, it doesn't show any whitespace changes in the diff. So commits/PR's for automated removal of whitespace once every week or so would be trivial to review for correctness - the whitespace-free diff should be completely empty.

**Comment by Ismael-VC** [comment]
My bash foo is close to nil, but @mbauman suggested something like this:

```bash
# If not on master and there are only doc changes, only check whitespace
    - if [ `git rev-parse --abbrev-ref HEAD` != "master" ] && git diff --name-only origin/master | grep -v '^doc/'
        make check-whitespace || exit 1
        exit 0
      fi
```

Related comment: https://github.com/JuliaLang/julia/pull/11770#issuecomment-113664843

What else would we need to take into account?

**Comment by simonbyrne** [comment]
Another approach would be to have a default `pre-commit` hook, which contributors are suggested to use. I've just been using the sample one (`.git/hooks/pre-commit.sample`) and found it avoids a lot of problems.

**Comment by StefanKarpinski** [comment]
+1 to standard pre-commit hooks / pre-push hooks for less annoyance.

**Comment by tkelman** [comment]
People use git in a lot of ways. Last time the hook question came up as a pr for contrib we decided against it. First needs a fix script that doesn't involve rebasing if we're going to tweak this.

**Comment by simonbyrne** [comment]
Why would it need rebasing? The point of a pre-commit check is that it won't let you commit anything with whitespace.

**Comment by tkelman** [comment]
The current whitefix checker script suggests rebasing as the way to fix whitespace errors, which is bad if we change to allowing whitespace errors on master but fixing them periodically via script.

hooks are fine if you want to use them yourself, but I don't think we can rely on them universally, for commits through the web interface, or people who use many different machines, different git clients, etc.

**Comment by Ismael-VC** [comment]
Couldn't we add `make check-whitespace` at TravisCI and AppVeyour config files, and then periodically run this to fix them in master, we wouldn't need to design a script, `make check-whitespace` or `git rebase --whitespace=fix master` already does the job.

**Comment by tkelman** [comment]
The checking is already there on travis and appveyor. Rebasing master after pushing is a no no.

**Comment by Ismael-VC** [comment]
Then make periodic commits with just white space fix, using make?

**Comment by tkelman** [comment]
That's the idea, but "make" what? There is not a "make fix-whitespace" currently, only a "make check-whitespace"

**Comment by Ismael-VC** [comment]
Oh I see, I swear I thought that check-whitespace checked and fixed the issue, that's for not reading the source.

**Comment by eschnett** [comment]
I quite like `clang-format` to automatically format C++ code. If you don't know it -- it's superior to `indent`, and since Julia uses LLVM anyway, it's a natural tool to use.

I created a `.clang-format` configuration file for Julia's style of C and C++ formatting, and ran `clang-format`. Unfortunately (?), there are a lot of cases where Julia's style convention leaves freedom, and there is thus much code that would be reformatted by `clang-format`.

Thus using `clang-format` to automatically format all C and C++ code would require a hard switch-over. This is not as bad as it sounds, since people would be able to switch over all current development branches at the same time (which is much simpler than re-formatting patches). However, this is probably not be worth the effort and disruption.

**Comment by StefanKarpinski** [comment]
I would be in favor of trying clang-format on for size. Can you configure it to mostly match Julia's C/C++ style?

**Comment by Keno** [comment]
LLVM has a policy for requiring `git clang-format` to be run over all new patches, but does not reformat the existing code base. Of course our code base is smaller, so a one-off formatting patch may be fine.
