### ISSUE TITLE
Foreign/interface types

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#11835]
What could be pretty neat would be a set of foreign/interface types. There could be one set for file types (.csv, .RData, .sas7bdat, various database types, etc.) and another set for expressions (various other languages like R, SAS, SQL, etc.). Then there could be a set of convert function overloads to convert various file-types to each other, and various code types back and forth. These various types could all get their own overload over base functions (so, for example, when subsetting one table into another table in a database, [ ] syntax would simply make an SQL call without data ever entering or leaving Julia). Of course, I'm biased towards stats examples, but this kind of thing could work with more scientific/matrix applications as well. Of course, the coding for all of this stuff would fall to package developers, but encouraging overloading over base functions as much as possible for package developers, as well as laying a framework for a base system of file types and foreign expression types, would be helpful. As a side note, would there be a way to overload functions based on desired output type (like a version of read for text, matrices, and DataFrames)?

**Comment by ihnorton** [comment]
See https://github.com/JuliaIO
This is too speculative for the base issue tracker. Packages are strongly preferred for most new development, and not at any disadvantage compared to base code -- in particular, there is no difference with respect to performance.
