### ISSUE TITLE
Have `squeeze(A)` remove all singleton dimensions 

### ISSUE THREAD

**Issue by lstagner** [JuliaLang/julia#11838]
It seems like the most common use of ```squeeze``` is to remove all of the singleton dimensions. I would be nice to have ```squeeze``` called without the ```dims``` argument do this. Perhaps something like this.

```
function squeeze(A::AbstractArray)
    s = size(A)
    dims = tuple(find([dim == 1 for dim in s])...)
    return squeeze(A,dims)
end
```

**Comment by timholy** [comment]
Among other places, see
https://groups.google.com/forum/#!searchin/julia-users/squeeze/julia-users/QQqVbyTiiPg/_VE3HgKIGu0J
https://groups.google.com/d/msg/julia-users/wfEEvYIHVGs/m27IWrpjajoJ

**Comment by StefanKarpinski** [comment]
Maybe we could just have this. Using it isn't always advisable since the result type isn't predictable and your code will therefore have corner cases when dimensions are accidentally singletons, but that could just be stated in the documentation for the `squeeze` function.

**Comment by lstagner** [comment]
I am not sure I agree with the argument against it because it would sometimes remove wanted singleton dimensions. If a user complains about a function doing the thing it was designed to do whose fault is it really? So long there is proper documentation I don't think its a problem. 

But perhaps we should distinguish it from ```squeeze``` to help protect users from themselves. How about calling it ```collapse``` or more controversially calling it ```squeeze``` and renaming the current version to something else, say ```unsplice```

**Comment by ivarne** [comment]
A separate function would just make things harder to learn. It seems easier to remember a performance tip to specify squeezed dimensions, than to also have to remember to use a different function. Documentation also read better without cross references.

**Comment by tknopp** [comment]
+1 for adding the squeeze function that removes all singleton dimensions. I use this quite often in plotting code where I do not care in which direction a 3D dataset is sliced. One should aware of the issues but for REPL usage its handy

**Comment by timholy** [comment]
Given that the more careful version is available, given adequate documentation of the dangers I can be persuaded.
