### ISSUE TITLE
Segfault when calling passed function in threads

### ISSUE THREAD

**Issue by kpamnany** [JuliaLang/julia#11857]
In the ``threading`` branch, the following code segfaults:

```
using Base.Threading
function f1(a, b, c)
  a+b+c
end
function f2(f, rest...)
  f(rest...)
end
@threads all f2(f1, 1, 2, 3)
```

I think this is a reentrancy problem in the code generator, because if you add ``precompile(f1, (Int64, Int64, Int64))`` before the multithreading call, it works fine.

**Comment by yuyichao** [comment]
Is this still an issue? I can't reproduce this on either the current master or #14190

**Comment by kpamnany** [comment]
Can't reproduce it either.
