### ISSUE TITLE
Excessive memory allocation in replace

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#11856]
```julia
s=readall("CONTRIBUTING.md")
replace(s,"a","b")
@time replace(s,"a","b")
504.130 microseconds (5537 allocations: 218 KB)
length(s)
14550
```

ie, ``replace`` is allocating 20x the memory of the source string and is taking about 10x longer than PCRE's substitute function in my testing. Would there be interest in a PR to improve its performance?

**Comment by ScottPJones** [comment]
Definitely!!! (I hope the core team agrees!)

**Comment by yuyichao** [comment]
@malmaud Is this fixed by your PR?

**Comment by malmaud** [comment]
Yes, this can be closed.
