### ISSUE TITLE
Build: Undefined Symbol 

### ISSUE THREAD

**Issue by psanan** [JuliaLang/julia#11855]
An issue that I encountered before with release-0.3 has resurfaced with the choice of a new compiler (gcc). This old discussion is here:
https://groups.google.com/forum/#!topic/julia-users/LUVVEfydAso

To recap, the problem manifests this way during the build process:
````
CC src/flisp/flmain.o
    LINK src/flisp/libflisp.a
    LINK src/flisp/flisp
/users/psanan/julia-gnu/usr/lib/libuv.a(libuv_la-core.o):(.note.stapsdt+0x24): undefined reference to `uv_tick__start_semaphore'
/users/psanan/julia-gnu/usr/lib/libuv.a(libuv_la-core.o):(.note.stapsdt+0x70): undefined reference to `uv_tick__stop_semaphore'
````

The origin of these undefined symbols seems to be `deps/libuv/include/uv-dtrace.h`.

I am able to build by making this change to `deps/makefile`:
````
diff --git a/deps/Makefile b/deps/Makefile
index 58ce023..0a0df72 100644
--- a/deps/Makefile
+++ b/deps/Makefile
@@ -703,7 +703,7 @@ $(LIBUV_SRC_DIR)/config.status: $(LIBUV_SRC_DIR)/configure
        touch -c $(LIBUV_SRC_DIR)/Makefile.in
        touch -c $(LIBUV_SRC_DIR)/configure
        cd $(LIBUV_SRC_DIR) && \
-       ./configure --with-pic $(CONFIGURE_COMMON) $(UV_FLAGS)
+       ./configure --with-pic --disable-dtrace $(CONFIGURE_COMMON) $(UV_FLAGS)
        touch -c $@
 $(UV_SRC_TARGET): $(LIBUV_SRC_DIR)/config.status
        $(MAKE) -C $(LIBUV_SRC_DIR) $(UV_MFLAGS)
````

With this change, and a clean rebuild (including deleting `deps/libuv` ; `git delete -x -f -d` was not a nuclear-enough option here!), `make testall` succeeds.

I believe that dtrace has been removed from libuv (https://github.com/joyent/libuv/commit/cb5140023b109aa9bb6b97d1bebc9f251b8195ac)

**Comment by tkelman** [comment]
What Linux distribution and compiler versions?

**Comment by psanan** [comment]
````
$ lsb_release -a
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	SUSE LINUX
Description:	SUSE Linux Enterprise Server 11 (x86_64)
Release:	11
Codename:	n/a
````

````
$ gcc --version
gcc (GCC) 4.9.2 20141030 (Cray Inc.)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by tkelman** [comment]
Our fork of libuv (https://github.com/JuliaLang/libuv) is quite a ways delayed from upstream. We did make some modifications in our fork a while back that were related to dtrace problems, ref https://github.com/JuliaLang/julia/issues/9058. I'm not sure if the dtrace support is all that useful for us (or what it does exactly), might be harmless enough to shut it off by default?

**Comment by kpamnany** [comment]
I'm seeing the same error on the following system:
```
$ lsb_release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a
$ icc --version
icc (ICC) 16.0.0 20150815
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.
```
Adding ``--disable-dtrace`` worked for me too.

**Comment by tkelman** [comment]
This issue should be no longer relevant given we've rebased to a more recent libuv version that no longer tries to use dtrace.

But I would like to ask @kpamnany and @psanan, are you still regularly using Julia on these systems and are they still on SUSE Linux Enterprise Server 11? If so, what does running `/lib/libc.so.6` return?

Our current binaries are build on CentOS 5 (glibc 2.5), but that's quickly approaching its end of support. We'll need to switch to something newer, and the most obvious choice will be CentOS 6 which uses glibc 2.12. It looks like SLES 11 uses glibc 2.11 and will still be supported for a while longer, so if we switch to building binaries on CentOS 6 they may no longer run on SLES 11. Unlike CentOS, there's no open extended-support version of SLES that we could use to easily build binaries (openSUSE 11 ended support some time ago).

Is this going to be an issue? You should be able to build from source on these systems, but if we don't regularly test on that kind of old system then things are likely to regress.

**Comment by kpamnany** [comment]
We have SLES 11 systems around, sadly. What do you mean "running ``/lib/libc.so.6``"?

**Comment by tkelman** [comment]
Just do `/lib/libc.so.6` at a shell (or `/lib/x86_64-linux-gnu/libc.so.6` on debian), apparently that's how you ask for glibc to dump version info. (No rush here and I know you're really busy right this second, so it can wait a week or two.)
