### ISSUE TITLE
Bounds checking in matrix multiplication for small matrices

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#11851]
For *2x2* and *3x3* matrix multiplication, we currently avoid the call to BLAS and instead call our own method, see [here](https://github.com/JuliaLang/julia/blob/d05a5790b6b06c05562295c155f69f736b2469eb/base/linalg/matmul.jl#L304) for example. This avoids significant overhead in the BLAS calls for small matrices. 

Currently, these methods perform bounds checking. The difference in performance using this benchmark is:

```julia
C2 = zeros(2,2)
A2 = rand(2,2)

C3 = zeros(3,3)
A3 = rand(3,3)

@time for i = 1:10^7
    Base.LinAlg.matmul3x3!(C3, "N", "N", A3, A3)
end

@time for i = 1:10^7
    Base.LinAlg.matmul2x2!(C2, "N", "N", A2, A2)
end
```

#### Master
```
349 ms
242 ms
```

#### Bounds check off
```
288 ms
218 ms
```

So ~10% for 2x2 and ~20% for 3x3. Since the 2x2 and 3x3 mmult methods are there for performance gain only, would it make sense to sprinkle some `@inbounds` on these? The fix is of course trivial so someone basically has to make a decision if it is worth it to turn off bounds checking for these methods.

**Comment by JeffBezanson** [comment]
Good idea.
