### ISSUE TITLE
Parser ignores docstrings ending with a semicolon.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaLang/julia#11864]
I noticed the following behaviour for docstrings ending with a semicolon after https://github.com/JuliaLang/julia/pull/11836 was merged:

```
julia> parse("""
       module M

       "...";
       f(x) = x

       "..."
       g(x) = x

       end
       """)
:(module M
    eval(x) = top(Core).eval(M,x)
    eval(m,x) = top(Core).eval(m,x) # line 3:
    "..." # line 4:
    f(x) = begin  # none, line 4:
            x
        end # line 6:
    Base.@doc "..." g(x) = begin  # none, line 7:
                x
            end
    end)
```

Note that ``f(x)`` isn't being ``@doc``ed. It *might* be nice to keep that behaviour as an escape hatch from the doc system, but could also just be a bit too subtle.

**Comment by JeffBezanson** [comment]
That was intentional. I just assumed the thing to document would be the very next thing. It doesn't seem so great to have a whole list of rules about what can occur between the string and the function for doc strings to work.

**Comment by MichaelHatherly** [comment]
Great, thanks for clarifying that Jeff.

> It doesn't seem so great to have a whole list of rules

Definitely.

Since there's nothing really needing to be done here then I'll close this.
