### ISSUE TITLE
ARM segfault in sysimg generation

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#11878]
after commit 7c1140f86e15d8f0cd7806dcce504f8281b97c7a ,build on ARM fail:

```
precompile.jl

signal (11): Segmentation fault
/bin/sh: line 1: 26066 Segmentation fault      (core dumped) /var/host/media/removable/data/netfs/julia/usr/bin/julia -C native --output-o /var/host/media/removable/data/netfs/julia/usr/lib/julia/sys.o -f -J /var/host/media/removable/data/netfs/julia/usr/lib/julia/inference.so sysimg.jl
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
Makefile:192: recipe for target '/var/host/media/removable/data/netfs/julia/usr/lib/julia/sys.o' failed
make[1]: *** [/var/host/media/removable/data/netfs/julia/usr/lib/julia/sys.o] Error 1
Makefile:64: recipe for target 'julia-sysimg' failed
make: *** [julia-sysimg] Error 2
```

**Comment by armgong** [comment]
after revert this commit  ui/repl.c , build on ARM on trunk is  OK, may be we can use ifdef to solve this problem?

**Comment by pao** [comment]
cc @JeffBezanson

**Comment by torrange** [comment]
Same issue being experienced here, too.

**Comment by ViralBShah** [comment]
Cc @vtjnash too.

**Comment by ihnorton** [comment]
On my system we are asserting out while compiling `Base._atexit`.
[backtrace](https://gist.github.com/ihnorton/7d3ed99197589676b11d#file-gistfile1-txt)

The REPL still does start though, even after the build bails out. It looks like we might be using the wrong ABI in imaging mode (I get the "ccall is using the llvm ABI" warning message while building, as expected).

[dump of function after assert in gdb](https://gist.github.com/ihnorton/7d3ed99197589676b11d#file-dumping-function-after-assert-in-gdb)

[dump of same function from running REPL](https://gist.github.com/ihnorton/7d3ed99197589676b11d#file-code_llvm-in-repl)

**Comment by vtjnash** [comment]
thanks. i'll push a fix shortly

**Comment by vtjnash** [comment]
I experimented with doing a screen-capture while debugging / fixing this. if anyone's bored enough to listen to me rambling for an hour, it's now available at https://youtu.be/oX0Hl5FL7IM.

**Comment by yuyichao** [comment]
@vtjnash So somehow you didn't hit https://github.com/JuliaLang/julia/issues/12082 ?

**Comment by vtjnash** [comment]
I did, but thought it was an unrelated bug since the same fix was working on x86_64

**Comment by yuyichao** [comment]
I see. (Apparently I'm only 5min into the video ....)

**Comment by torrange** [comment]
Cheers Jameson - I will endeavour to listen to your ramblings! ;)

**Comment by malmaud** [comment]
@vtjnash Can we have a 24/7 livecam?

**Comment by torrange** [comment]
Haha. So, there is a market for that.  Albeit a niche one, I'm sure.
