### ISSUE TITLE
The Push for 90% Test Coverage

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#11885]
# The testing situation right now

The latest [Codecov run](https://codecov.io/github/JuliaLang/julia) shows a test coverage percentage of 83.24%. This is amazing work by all, but now let's push for that beautiful green badge, following the great work at #9493. @ViralBShah asked us to open new issues rather than keep accumulating comments over there. There are many files in Julia which are poorly covered, but some are more target-rich than others. In particular, the files / folders with the most lines missed are:
- [ ] `base/multi.jl` - 348 lines missed
- [ ] `base/pkg/entry.jl` - 284 lines missed
- [ ] `base/linalg/lapack.jl` - ~~293~~ 52 lines missed
- [ ] `base/inference.jl` - 229 lines missed
- [ ] `base/printf.jl` - 234 lines missed
- [ ] `base/show.jl` - 170 lines missed
- [ ] `base/LineEdit.jl` - 199 lines missed
- [x] `base/abstractarray.jl` - ~~196~~ **19** lines missed - claimed by @davidagold 
- [ ] `base/REPL.jl` - 184 lines missed
- [ ] `base/stream.jl` - 169 lines missed
- [x] `base/interactiveutil.jl` - 163 lines missed - claimed by @Rory-Finnegan 
- [x] `base/string.jl` - 139 lines missed - claimed by @ScottPJones 
- [ ] `base/int.jl` - ~~127~~ 81 lines missed
- [ ] `libgit2 folder` - 400 lines missed

To get to 90% coverage, we need to cover **3580** lines. If we focus on the above files, we can drastically improve their coverage and Julia's at once. I also like this set because there's a good spread across Julia functionality - linear algebra, strings, parallel processing, the REPL, etc. 
# Isn't That a Lot of Lines?

Yeah, it is. Luckily, we've already made great progress (we passed 80%!) thanks to a great group of new contributors. Spread out across a bunch of people, it's not so much work. 
# File specifics

`lapack.jl` is the file I know best. There are many functions wrapped in there that "can't" be tested right now because they require matrix storage formats that Julia doesn't support, like banded or RFP. But there are also functions that do complicated factorizations that can be difficult to test without a lot of domain expertise. Linear algebra experts welcome!

`multi.jl`, the file in the worst state, has many methods for starting/stopping/talking to workers that have not been tested at all. Maybe this is an issue with the buildbots that @tkelman or @staticfloat can clarify more?

In general the state of the REPL testing is quite poor. If someone would like to familiarize themselves with the REPL internals writing these tests would be a wonderful way to do so.
# How you can help

If there's an area in the above list you have some expertise in or want to learn more about, feel free to "claim" the file and start testing the heck out of it! That's how I got involved in the linear algebra testing and it worked out pretty well :wink:. The first set of tests was the hardest to write, but following the instructions in the OP of #9493 will get you most of the way there. You absolutely do not need to read the following 150+ comments! Following the [Coveralls repo](https://coveralls.io/r/JuliaLang/julia) or the [Codecov repo](https://codecov.io/github/JuliaLang/julia) is a good way to track our progress, and you will be able to see your numbers go up.

If someone claims a file as their testing baby, I will check it off in the list above. If there's no checkbox, that file is up for grabs and in need of some awesome Julians, newbies or experienced, to write some tests for it!

We now have a Gitter chat-room: https://gitter.im/kshyatt/julia-coverage
# "Help! I'm a first time contributor and I have no idea how to use Coveralls!"

Here's a step-by-step image guide to how I find things to test using Coveralls.
1. Click on the latest build on the JuliaLang julia repo on Coveralls
   ![step1](https://cloud.githubusercontent.com/assets/828643/8471763/4775e592-2050-11e5-9c3f-ceab030153cb.png)
2. Coveralls by default doesn't show us a lot of files. Let's change that.
   ![step2](https://cloud.githubusercontent.com/assets/828643/8471870/27b0fa16-2051-11e5-9d9a-3b3435ba575d.png)
3. Let's view 100 files per page. Since Julia base has about 220 files, we can capture all the ones in the worst state this way
   ![step3](https://cloud.githubusercontent.com/assets/828643/8471878/3ac5a35e-2051-11e5-829e-61a1b006fc84.png)
4. Now let's look at all the files in Julia, rather than just the ones changed in the latest merge
   ![step4](https://cloud.githubusercontent.com/assets/828643/8471885/496cd4d6-2051-11e5-9885-faaea1279308.png)
5. `lapack.jl` here is in a bad state. Look at all those missed lines! Let's click on it and find something to test.
   ![step5](https://cloud.githubusercontent.com/assets/828643/8471892/5d3ab776-2051-11e5-8266-a77cb6567894.png)
6. Here's a line in red that's not tested. It's an error throw, which are often missed. Writing a test for this functionality should be pretty simple. 
   ![step6](https://cloud.githubusercontent.com/assets/828643/8471898/6ce7bb7e-2051-11e5-9f10-2b39439d63d7.png)

**Comment by tkelman** [comment]
There was a question elsewhere that I don't think has been answered yet about what happens when parallel workers try to write coverage data to the same cov file - I'm not sure whether or not this is happening on the buildbots. Setting the environment variable `JULIA_CPU_CORES=1` may help.

Also #11802 may make these numbers more honest (worse) when it gets merged.

**Comment by ScottPJones** [comment]
I'd be happy to try to handle the lines in `string.jl`, if nobody else wants it.
Would people mind me combining that with splitting up `string.jl` into a number of independent files,
and then splitting up `test/strings.jl` (my nemesis, because I keep having to rebase when somebody changes it) as well as `test/unicode.jl` into files matching the split up `string.jl` (and the ones that are already separate, i.e. `utf8.jl`, `utf16.jl`, and `utf32.jl`)?

**Comment by ScottPJones** [comment]
@tkelman That was me asking, and I have a very strong suspicion that it *isn't* being handled, and that maybe the coverage is actually higher, because esp. heavily used things like `abstractarray.jl.cov` may be getting overwritten by the different processes.

**Comment by Ismael-VC** [comment]
I'll keep helping the best I can! :+1: for 100%

**Comment by tkelman** [comment]
Maybe dumb possibility: write files to `".jl.$(getpid()).cov"` then merge them in a post-processing step?

**Comment by ViralBShah** [comment]
That may be the simplest thing to do.

**Comment by ViralBShah** [comment]
@ScottPJones It would be best IMO to not mix up the testing with other PRs. That way we can fast track merging things that are focussed.

**Comment by ScottPJones** [comment]
Sounds like a good first step to me, as long as the same worker processes are used during the runtests (just in case the os could reuse the pid if the workers are forked during the testing)

**Comment by timholy** [comment]
I haven't dug into how the buildbots are running things, but AFAIK we've always been measuring coverage of base with `JULIA_CPU_CORES=1`. Indeed, the current lack of info back from workers may be the major factor behind `multi.jl`'s apparently-poor coverage.

**Comment by ScottPJones** [comment]
@timholy That's good, I'd been trying to run coverage tests on my laptop, and was getting things overwritten.  It would be good to solve this though, so that we can speed up coverage testing.
@ViralBShah Whatever people feel best, I was thinking of splitting things up by 3-4 commits in one PR,
but I can also do it as separate PRs for splitting up string.jl, splitting up test/strings.jl test/unicode.jl, and adding any tests that are not covered

**Comment by davidagold** [comment]
Happy to jump on `base/abstractarray.jl`, will work around pending changes from https://github.com/JuliaLang/julia/pull/11895.

**Comment by kshyatt** [comment]
Wonderful! Thanks so much, @davidagold. I have a weak commitment to `lapack.jl` since there are a few functions in there that need better error messages anyway.

**Comment by davidagold** [comment]
My pleasure!

To make things interesting, I will bet anybody a beverage of their choice (and some semblance of bragging rights) that I submit a PR with full coverage of `abstractarrays.jl` before they submit a PR with an equivalent coverage increase in their file.

**Comment by ScottPJones** [comment]
Has @carnaval's change to use the min() for the coverage of several statements on one line made it in to  master yet?  If not, I think there will be a number of places that look covered, but are not really.
(except in @kshyatt's changes, since she rewrote stuff as `if/end` instead of `&&` or `||`)

**Comment by kshyatt** [comment]
Coverage has not run since June 22, and someone told me that this is because the nightly builds are failing - @staticfloat, is that true? I am pretty sure @carnaval's change hadn't made it in by that date.

**Comment by staticfloat** [comment]
Yes it's true.  I pushed out a change that will hopefully fix the nightly breakage today.  We'll see I suppose.  :)

**Comment by kshyatt** [comment]
Someday @staticfloat will become so tired of my tedious "Hello, yes, it's me again, so about the coverage runs..." emails he will simply force ME to curate the buildbot!

**Comment by ScottPJones** [comment]
I've been running coverage tests manually (but haven't totally succeeded yet, because of lots of breakage with various unit tests if `CPU_CORES == 1`.  I'm preparing a simple fix to not call "spawn",but now it is dying on the "reflection" test for some reason).
This coverage testing would be a lot easier if
  * `Base.runtests()` worked with `CPU_CORES == 1`
  * Or the .cov files from different processes didn't overwrite each other
  * We had a command line flag to ignore `sys.dylib`s object code, and act like you just had `sys.ji`

**Comment by staticfloat** [comment]
> Someday @staticfloat will become so tired of my tedious "Hello, yes, it's me again, so about the coverage runs..." emails he will simply force ME to curate the buildbot!

And thus, the cycle continues.  :)

> * We had a command line flag to ignore sys.dylibs object code, and act like you just had sys.ji

This actually reminds me; the lack of this command line flag is ALSO holding up the coverage stats, since our song and dance so far has been to download the nightly generic linux tarballs (which rightly contain only `sys.dylib` now, no `sys.ji` anymore), delete `sys.dylib` and try to run coverage.  Unfortunately, this causes Julia to not startup anymore, since there is no `sys.ji` to fall back to.

**Comment by dpsanders** [comment]
I would like to try number 11, `int.jl`.  There doesn't seem to be an `int.jl` file in the `test` directory. Can I add this?

**Comment by kshyatt** [comment]
I think many of the `int.jl` methods are "implicitly" tested when we run the linalg and math tests. But looking at `int.jl` it appears much of the type conversion between `int` types isn't tested at all. Personally, I don't have a problem with adding an `int.jl` test file. I will add you to the OP.

**Comment by StefanKarpinski** [comment]
Testing integer conversions makes sense and would be a great addition, especially various tricky corner cases – i.e. making sure that converting a value equal to the largest/smallest representable number in the target type works while converting values just one more extreme raises an `InexactError`.

**Comment by kshyatt** [comment]
My latest [codecov](https://codecov.io/github/kshyatt/julia) results show us at **79.17%** coverage. Keep up the great work, everyone! @dpsanders, I can't wait to see that number go up once your PR is merged.

**Comment by dpsanders** [comment]
My PR is ready. I added some tests like those proposed by @stefankarpinski. I may be off the radar for the next 10 days.

**Comment by dpsanders** [comment]
One problem is that there is quote a lot of code in int.jl for 32 bit machines. Is there some way to test that?

**Comment by StefanKarpinski** [comment]
Not on a 64-bit machine. If we could somehow indicate that those don't count, it would be good but I'm not sure how to go about doing that.

**Comment by dpsanders** [comment]
Jameson suggested to split out the 32 bit stuff into a separate file and conditionally include it.

**Comment by StefanKarpinski** [comment]
Good idea!

**Comment by tkelman** [comment]
That sounds like rearranging code unnecessarily for the sake of bad tools again. We can run 32 bit Julia on 64 bit Linux. Or add a separate 32 bit coverage buildbot. Need to do similar for platform-dependent code eventually.

**Comment by StefanKarpinski** [comment]
Separating platform-specific code out into separate files seems pretty ok to me.

**Comment by tkelman** [comment]
If we do it everywhere and consolidate all platform-dependent code into a handful of files okay, but moving code around piecemeal for no good reason would make the job of maintaining that code more difficult. I personally prefer having code organized as we have it now by functionality, with platform dependencies accounted for locally.

**Comment by ScottPJones** [comment]
Dealing with 32-bit vs. 64-bit is very pervasive.  It would make the code very difficult to maintain.
It isn't the same as dealing with platform-dependent code, like Windows vs. AIX vs. Linux vs. OS X vs. ...

**Comment by ScottPJones** [comment]
Solving this could be done in a way similar to being able to do the coverage tests in parallel, which would require separate output files for each worker, and separate output files for 32-bit vs. 64-bit, and then parsing the files and adding up the coverage information for each line, and outputting a merged version.
That technique could also handle coverage of platform dependent code.

**Comment by randyzwitch** [comment]
`printf` doesn't appear to have its own testing file; `printf.jl` appears to just be using Base.Grisu. Does it make sense to append `printf.jl` tests just to the `Grisu` file or make a `printf.jl` test file?

I'm not sure I want to fully claim this file yet, but I could knock out some string formatting tests way easier than linear algebra ones :)

**Comment by ScottPJones** [comment]
I have a PR (#11925) already that makes a separate printf.jl test file (and splits up the troublesome string.jl and unicode.jl test files to match files in Base).

**Comment by randyzwitch** [comment]
@ScottPJones, in that case, I'll leave it alone and find fresh area to work on.

**Comment by ScottPJones** [comment]
No, no!
I just meant that, if that PR were to be merged (I'll have to check if it needs any updating, it's been almost a week since I did it), it would make life easier for us to be adding more string coverage tests, without stepping on each others toes.
I'd love to see more coverage testing anywhere in strings.   If I have to update things then in my PR, no problem!

**Comment by randyzwitch** [comment]
Right, I can always come back later and write tests after the PR is merged. Trying to compare between Coveralls, your PR and then what's remaining is more effort than just waiting.

**Comment by ScottPJones** [comment]
Well, there's just the matter of getting somebody to merge it.  I'll update it now, and maybe beg @kshyatt to look at it!

**Comment by kshyatt** [comment]
I have a lot of work to do today since my collaborator is back in town and I have my `.cov` PR to get to pass. Sorry, @ScottPJones!

**Comment by ScottPJones** [comment]
Ha! No problem at all! I realize you are super busy! Maybe somebody else will, it will make life a lot easier for @randyzwitch,@ninjin, and myself.

**Comment by KristofferC** [comment]
I believe reaching 80% coverage would go faster if we didn't confuse potential contributors by discussing and begging for merging unrelated PRs. Also, this new trend of back and forth chatting about un/semi-related stuff has made issues and PRs much more noisy than they used to be. This is not a chat room.

**Comment by kshyatt** [comment]
Sorry, @KristofferC. I think I should make a Gitter chatroom about coverage issues and direct all chatting about it there. I'll commit to only posting relevant stuff here - sorry!

**Comment by ScottPJones** [comment]
Note: @KristofferC, the PR in question was specifically done in order to make it *easier* to do add coverage testing for strings, so it was totally relevant to this coverage PR.

**Comment by Rory-Finnegan** [comment]
FWIW, I could work on testing interactiveutil.jl if that is still useful.

**Comment by kshyatt** [comment]
More tests are always useful and appreciated! You're added to the OP :)

**Comment by davidagold** [comment]
Question: should I include a test for a deprecation warning?

**Comment by ScottPJones** [comment]
Check out my PR #11976, where I added tests for deprecated functions.
It was a bit tricky, because you need to handle the fact that when `Base.runtests()` does tests using workers, they have `depwarn == 2`, but if you do `Base.runtests("deprecated")` from the REPL, `depwarn` is whatever you have set (normally 1).

**Comment by davidagold** [comment]
Thank you, Scott. I wonder, though, if I just X-Y problem'd y'all (or just
asked an unfortunately imprecise question). My particular issue is dealing
with this line:
https://coveralls.io/builds/2976082/source?filename=base%2Fabstractarray.jl#L17.
Maybe I'm missing it (I'm unfamiliar with the internals of deprecation),
but this doesn't seem to hook into the same deprecation interface that you
were treating -- right?

**Comment by ScottPJones** [comment]
It does, I was also using `depwarn()`.
Note: I've also got a PR improving the error messages for abstractarray.jl, #11797

**Comment by davidagold** [comment]
Ah, so the key is `depwarn()`. I'd better look that up... Thanks, Scott =)

**Comment by davidagold** [comment]
Okay, I think my tests are ready to go. PR here: https://github.com/JuliaLang/julia/pull/12086.

Suggestions are of course welcome -- my working assumption is that my PR might need some iteration...

**Comment by ScottPJones** [comment]
@randyzwitch Now that my split up of `string.jl` has been merged, please go ahead and tackle `printf` coverage! (Unless you are too busy making interesting tweets! :grinning:)

**Comment by ScottPJones** [comment]
I've mostly finished with `unicode/*.jl`, so now I'm going to claim `string/*.jl`.

**Comment by hayd** [comment]
Coverage has dropped to 64% for some reason https://codecov.io/github/JuliaLang/julia/base?ref=6aa15b859e1b114061439fa6640173d2978fed3d

**Comment by kshyatt** [comment]
The reason is shown [here](http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64/builds/25/steps/Run%20non-inlined%20tests/logs/stdio), a failing test introduced by https://github.com/JuliaLang/julia/pull/13491.

**Comment by hayd** [comment]
Seems to have dropped to 11% in the last day or so! https://codecov.io/github/JuliaLang/julia/commits

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/issues/16501
The most recent coverage run timed out https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/281/steps/Run%20non-inlined%20tests/logs/stdio, not sure why there are ASCIIString/UTF8String deprecation warnings when running the base tests.

**Comment by omus** [comment]
I've been looking into #17990 and I was hoping to add some tests dealing with credentials and LibGit2. My current plan is to make a [GitHub machine user](https://developer.github.com/guides/managing-deploy-keys/#machine-users) associated with the JuliaLang org and utilize [deploy keys](https://developer.github.com/guides/managing-deploy-keys) (SSH access) and [personal access tokens](https://github.com/blog/1509-personal-api-tokens) (HTTP access) which would have read-only access to a private JuliaLang repo.

The issues I see with this plan is that it would require access to a private GitHub repo (which costs money) and that repo would be accessible by anyone with a copy to the Julia code base. Does this sound like a good plan or are there better ideas for testing credentials and LibGit2?

**Comment by ViralBShah** [comment]
I think we have free private repos in the JuliaCon org. I will verify that.

**Comment by JaredCrean2** [comment]
Not sure if this the right place to report this, but code coverage [dropped to 4%. ](https://codecov.io/gh/JuliaLang/julia/commits) 15 days ago. Something strange is going on?

**Comment by StefanKarpinski** [comment]
There's a chronic build failure going on that's probably related. I do wish that failing builds would report that coverage metrics are unavailable instead of reporting nonsense metrics.

**Comment by tkelman** [comment]
ref https://build.julialang.org/builders/coverage_ubuntu14.04-x64

**Comment by prasad-marne** [comment]
I'd be happy to try to handle the lines in printf.jl, if nobody else wants it.

**Comment by waldyrious** [comment]
Looks like this issue should be closed, or perhaps renamed to "The Push for 95% Test Coverage" :)

**Comment by vtjnash** [comment]
We also need to update the script to upload stdlib/*/src reports

**Comment by ViralBShah** [comment]
I think we should close this one.

**Comment by KristofferC** [comment]
Agreed.
