### ISSUE TITLE
OverflowError when splatting array of arrays

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#11884]
The test vector is from `Metis.jl`. The bug can be seen from the sequence
```jl
julia> using Metis

julia> copter2 = Metis.testgraph("copter2")
Undirected Graph (55476 vertices, 352238 edges)

julia> typeof(copter2.adjlist)
Array{Array{Int32,1},1}

julia> vcat(copter2.adjlist...);
ERROR: OverflowError()

julia> vcat(copter2.adjlist[1:100]...);

julia> vcat(copter2.adjlist...); # works!
```

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/11320  https://github.com/JuliaLang/julia/pull/11330

**Comment by ScottPJones** [comment]
Yes, much better behavior than before @yuyichao fixed it so quickly!  (Thanks again!)

**Comment by ScottPJones** [comment]
Is it something strange in the GC that it can work the 2nd time?  Before the fixes, the first call would have hung julia.

**Comment by yuyichao** [comment]
And just to give a example that doesn't depend on external packages.

```julia
julia> ary = [[1, 2] for i in 1:100000];

julia> vcat(ary...);
ERROR: OverflowError()

julia> vcat(ary[1:100]...);

julia> vcat(ary...);
```

**Comment by andreasnoack** [comment]
@JeffBezanson suggests avoiding the splatting when doing this in favor of doing something like https://github.com/JuliaSparse/Metis.jl/blob/b675ea7adfb8d5230814757d8f08bfce63a42e02/src/util.jl#L1-L8
