### ISSUE TITLE
iobuffer test segfaulting on travis

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#11917]
https://travis-ci.org/JuliaLang/julia/jobs/68639785
https://travis-ci.org/JuliaLang/julia/jobs/68665838
https://travis-ci.org/JuliaLang/julia/jobs/68669790
https://travis-ci.org/JuliaLang/julia/jobs/68681458
https://travis-ci.org/JuliaLang/julia/jobs/68681461
https://travis-ci.org/JuliaLang/julia/jobs/68702049
https://travis-ci.org/JuliaLang/julia/jobs/68702323
https://travis-ci.org/JuliaLang/julia/jobs/68702326
https://travis-ci.org/JuliaLang/julia/jobs/68706816
https://travis-ci.org/JuliaLang/julia/jobs/68706818

gc is showing up in the traces, but might not be @carnaval's fault, I don't think anyone has touched gc recently? can anyone reproduce? happening on both osx and linux travis.

maybe related failures in math and tuple
https://travis-ci.org/JuliaLang/julia/jobs/68669791
https://travis-ci.org/JuliaLang/julia/jobs/68700051

**Comment by ScottPJones** [comment]
Good, I'm not the only person this is happening to.  I've had a lot of weird errors and segfaults running the unittests.

**Comment by tkelman** [comment]
If you can reproduce locally, the most useful thing you can do would be help narrow down the problem - does running just iobuffer by itself reproduce the problem? then how about running each line in iobuffer chunk by chunk, to narrow it down to the exact failure (if it's consistent)

**Comment by ScottPJones** [comment]
It wasn't consistent, every time it failed in a different place.  All I had to do is `Base.runtests()`.
I had an error in `squeeze`, an error in `iobuffer`, some errors showing the gc.

**Comment by tkelman** [comment]
equal-opportunity bug, even happens on windows: https://gist.github.com/tkelman/e076b767c581257e23e2

**Comment by andreasnoack** [comment]
I see this locally on my Mac now.

2015-06-28 14:41 GMT-04:00 Tony Kelman <notifications@github.com>:

**Comment by malmaud** [comment]
Sorry guys, my fault with the replace pr. Simon is patching it imminently.
