### ISSUE TITLE
Rewrite Pkg.add to include repo argument

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11914]
This could eliminate the need for a `Pkg.clone` method too.

``` julia
Pkg.add(pkg::AbstractString, vers::VersionNumber... ;
        repos="https://github.com/JuliaLang/METADATA.jl")
```

You can go to the METADATA for curated packages and you can skip it and pass the actual url for where the package lives. We could also make a METADATA.jl-like free-for-all repository

**Comment by milktrader** [comment]
Not sure how this would go over, but what about changing METADATA.jl to CuratedPackages.jl and having a separate one for non-curated packages. Curated doesn't have a good antonym so I'm at a bit of a loss for what you'd call this _other_ repository of repositories.

**Comment by tkelman** [comment]
METADATA is not the best of names for a package registry...

**Comment by milktrader** [comment]
Yeah, it was named at a time when we just wanted to get something up and give it a go.

**Comment by ScottPJones** [comment]
:+1: for CuratedPackages.jl, and having a non-curated one.

**Comment by milktrader** [comment]
The more I think about, I'm wondering if Julia just lets someone else do the non-curated one. It's not like we don't have enough on our plate as it is.

**Comment by ScottPJones** [comment]
Right, no reason it *has* to be even officially supported by JuliaLang

**Comment by dpsanders** [comment]
+1 for CuratedPackages.jl

**Comment by milktrader** [comment]
Alright I'll file a separate issue for it since it's buried in this one.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/julia/issues/11930

**Comment by KristofferC** [comment]
This is obsolete in terms of the pkg3 discussion https://github.com/JuliaLang/Juleps/issues. Most of the discussion is about the METADATA name for which an issue has been opened.
