### ISSUE TITLE
arnoldi tests failing with MKL blas on recent master

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#11921]
Using
```
julia> versioninfo()
Julia Version 0.4.0-dev+5679
Commit 7c65815 (2015-06-28 19:05 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.6.1
```
I get a segfault in `test/linalg/arnoldi.jl` 
```
signal (11): Segmentation fault
mkl_blas_avx2_zdotc at /opt/intel/composer_xe_2015.3.187/mkl/lib/intel64/libmkl_avx2.so (unknown line)
zneupd_ at /home/bates/git/julia4/usr/bin/../lib/libarpack.so (unknown line)
```

**Comment by ViralBShah** [comment]
I believe it has always failed - due to differences in the Fortran calling conventions.

**Comment by ViralBShah** [comment]
See the resolution in #7547. The real solution though is #2167.

**Comment by tkelman** [comment]
I think @dmbates answered this question earlier today but he was on the other side of the room and I didn't entirely hear him, is this copy of Julia built with all-Intel compilers along with MKL? I think that's the main configuration we attempt to support, rather than mixing MKL and gfortran.

**Comment by ViralBShah** [comment]
I am closing this one, since the two other issues I refer to cover this.

**Comment by StefanKarpinski** [comment]
@ViralBShah, could you provide an answer to @tkelman's question for future reference? Maybe document it if that's the case?

**Comment by ViralBShah** [comment]
@tkelman 's question is answered in #7547, but that may not be immediately obvious from my comments. Basically - build everything with intel compilers if you want to use MKL.

**Comment by kshyatt** [comment]
Hasn't building Julia with `icc` on Windows been broken for over a year? I don't know if MKL is even supposed to work on Windows, but if it is, that kind of sucks.

**Comment by jiahao** [comment]
ICC v15 works, but not v14

**Comment by kshyatt** [comment]
Awesome, thanks for the info!

**Comment by jiahao** [comment]
Not sure about Windoze, sorry

**Comment by tkelman** [comment]
On Windows, icc and ifort are visual-studio-style, so they might sort of work but no one has tried AFAIK. Windows ifort also does not use trailing underscores, so lots of patches would be required (or a dedicated `fcall`).

**Comment by ViralBShah** [comment]
Won't there be some command line option to turn on the right number of underscores?

**Comment by tkelman** [comment]
I don't think that is available on the Windows version of ifort.
