### ISSUE TITLE
Moving the manual to Markdown

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#11920]
As the last part of the docapocalypse / docapocalopalypse I'd like to move the manual to the much nicer Markdown format and into its own repo. Right now that work is over at [JuliaManual.jl](http://github.com/one-more-minute/JuliaManual.jl) (happy to move to JuliaLang and bikeshed the name as appropriate\*), and the markdown manual is auto-generated into the `/doc` directory.

Now that we have a shiny new markdown manual it's just a case of figuring out how to host it. How important are things like versioning and search? Can we live without versioning, and forward search to google? If so, it's a simple case of generating HTML for github pages. If not, things are more complicated and we need to figure out a sane route forward.

<sup>\* *JuliaMAN.jl* might be complementary to our recent package additions</sup>

**Comment by StefanKarpinski** [comment]
Docnarok?

**Comment by tkelman** [comment]
> How important are things like versioning and search?

Very

> Can we live without versioning

No

> forward search to google

Maybe

> simple case of generating HTML for github pages. If not, things are more complicated 

Does mkdocs do versioning?

**Comment by ivarne** [comment]
Search is essential

**Comment by IainNZ** [comment]
By versioning do you mean 0.3 vs 0.4 docs? Because definitely need that. Search via Google could work, not sure though.

**Comment by one-more-minute** [comment]
Ok, it should be easy enough to do different minor versions of the docs. re searching,

https://encrypted.google.com/search?hl=en&q=site%3Adocs.julialang.org%2Fen%2Flatest%20iobuffer#hl=en&q=site:docs.julialang.org%2Fen%2Frelease-0.3+iobuffer

Just having a search box that redirects to that doesn't seem too awful. Other suggestions are welcome, of course.

**Comment by one-more-minute** [comment]
@shashi How about Escher-backed interactive docs?

**Comment by StefanKarpinski** [comment]
https://cse.google.com/cse/ ?

**Comment by shashi** [comment]
I'm all for using Escher for this, since this is a good real world use case it means to address. Escher can compile to HTML as of now, though a couple of features need to be figured out for this purpose e.g. a table of contents tree explorer. If run using a Julia server it can indeed be interactive. @one-more-minute @tkelman @IainNZ We can discuss this tomorrow if you guys are around.

**Comment by ViralBShah** [comment]
We can deploy the rich interactive documentation on JuliaBox. Heck, if we combine with Homework.jl, it can also become a Julia certification system!

**Comment by tkelman** [comment]
I'm around tomorrow, but I'm pretty sure the last web page I made was in FrontPage 97 (https://web.archive.org/web/19991008201503/http://www.kelman.net/homeweb/pond.htm) so I doubt I'll be of much use here.

**Comment by jiahao** [comment]
What's the story with equations and references now? We have some in the manual and standard library reference and I would hate to lose them in the Markdown transition.

**Comment by tkelman** [comment]
@jiahao a lot of them were lost last night in the from-rst to to-rst transition

**Comment by jiahao** [comment]
That's really not the answer I was hoping to hear. I spent quite a lot of time writing those docs, and I had warned repeatedly about the lossy format transition. I'm really not pleased about losing them.

**Comment by one-more-minute** [comment]
@tkelman I haven't seen any missing equations and most references have formats like `f()` which are really easy to recognise and turn into links. Can you give more specific examples?

**Comment by tkelman** [comment]
By references you mean cross-references between different functions right? I think the hope was to possibly make them automatic somehow? Don't shoot the messenger.

There are some bibliographic citations which weren't lost, but the formatting was a bit disrupted. See https://github.com/JuliaLang/julia/pull/11906 for things that @hayd and I noticed while skimming through the super long diff. Most or all of the tables have been fixed already, code quoting and lists and citation formatting and x-refs are still to-be-fixed I believe.

**Comment by one-more-minute** [comment]
Either way, I understand that a lot of work went into things like cross-references and will do my best to make sure we lose as little as possible in the transition. I can pull them out of the old RST files reasonably easily.

**Comment by jiahao** [comment]
@tkelman that wasn't my intention.

@one-more-minute look for cross-references of the form

`:xxx: func(examplevar) <func>`

ReST supports arbitrary text in the link to some other function `:func:` or object `:obj:` or module `:mod:` etc, and I had found it necessary to use this form of cross-referencing.

I had also inserted many cross-references of the form `:obj:SomeType` which are crossreferences to `SomeType` and do _not_ render as `SomeType()`.

**Comment by mauro3** [comment]
Off topic: @tkelman that pond sure made my evening!  Presumably the "living koi" are by now also "deceased koi", I wonder what their cause of death was...

**Comment by hayd** [comment]
Could we use https://github.com/MichaelHatherly/Lexicon.jl cc @MichaelHatherly

Some discussion: https://github.com/MichaelHatherly/Lexicon.jl/issues/6

*(xlink to [my previous comment](https://github.com/JuliaLang/julia/pull/11828#issuecomment-114945454) about alternative way to get help jl files)*

**Comment by MichaelHatherly** [comment]
> Could we use https://github.com/MichaelHatherly/Lexicon.jl

Lexicon won't be able to help with a rst->md conversion much. Also, I still hadn't gotten to sorting out how xrefs would work, so it's unlikely it would be that useful for what we need here. From the looks of it @one-more-minute's JuliaManual.jl is progressing quite rapidly already.

**Comment by lobingera** [comment]
I'm confused. Is this part of freezing v0.4?

**Comment by cormullion** [comment]
Can you write definition lists (`<dd><dl>`) in Markdown? I was writing some Markdown the other day and couldn't work out is to do it. (I think the manual uses them extensively.)

**Comment by mauro3** [comment]
Does closing this issue mean that the manual stays in RST?
