### ISSUE TITLE
build_sysimg broken after #11640

### ISSUE THREAD

**Issue by sebastiang** [JuliaLang/julia#11933]
Building recently from master (5444813fb8997b22cfa7ac78438d2f4798341152) produces a `sys.so` but no `sys.ji`. While the resulting binary will run from the command prompt, curiously it doesn't run properly when loaded via `node-julia`, which complains 

    System image file "/usr/local/lib/julia/sys.ji" not found

Attempting to build it manually fails also

    julia> build_sysimg(default_sysimg_path, "x86-64", force=true)
    INFO: Building inference0.o...
    /usr/local/bin/julia -C x86-64 --build /usr/local/bin/../lib/julia/inference0 coreimg.jl
    julia: unknown option `--build`
    ERROR: failed process: Process(`/usr/local/bin/julia -C x86-64 --build /usr/local/bin/../lib/julia/inference0 coreimg.jl`, ProcessExited(1)) [1]
     in run at ./process.jl:490
     in anonymous at /usr/local/share/julia/build_sysimg.jl:55
     in cd at ./file.jl:22
     in build_sysimg at /usr/local/share/julia/build_sysimg.jl:27
     in build_sysimg at /usr/local/share/julia/build_sysimg.jl:12

**Comment by pao** [comment]
See #11640. But the `build_sysimg` thing is a bug--that wasn't updated in that patchset.

**Comment by tkelman** [comment]
same issue as https://github.com/JuliaLang/julia/issues/11816

**Comment by pao** [comment]
I'm not sure it is? First `julia: unknown option ``--build`` ` is definitely unrelated; second, this is just building the standard sysimg, without any user code.

**Comment by generaltso** [comment]
hi, stumbled across this issue when google searching for why contrib/build_executable.jl was failing

current master branch fails standalone compiling  with error message "julia: unknown option --build". 

asked in the freenode irc channel and was told that nightlies haven't been able to be built for almost a week now?

I git reset to commit https://github.com/JuliaLang/julia/tree/861f02712eb4b41c08fed3f21c5a4206b8d669bc and using contrib/build_executable.jl works now. (this was last commit that touched said file, even though it only adds license info ;) )

A lot has happened between May 3 and today however, so this probably isn't a good fix, but I hope it's helpful? =)

**Comment by axsk** [comment]
I don't know if this is related, but trying to ```make``` Julia fails for me with
``` >make
 JULIA usr/lib/julia/inference0.o
/bin/sh: line 1: 998 Illegal instruction (core dumped) /home/.../julia/usr/bin/julia -C native --output-o /home/.../julia/usr/lib/julia/inference0.o -f coreimg.jl
Makefile:176: recipe for target ´/home/.../julia/usr/lib/julia/inference0.o´ failed
make[1]: *** [/home/.../julia/usr/ib/julia/inference0.o] Error 132
Makefile:64: recipe for target ´julia-sysimg´ failed
make: *** [julia-sysimg] Error 2
```

Any ideas on how to fix this? Should the above PR help?

**Comment by tkelman** [comment]
If you're just calling `make`, this is something different. Illegal instructions usually come from LLVM getting your processor type wrong, or running in a VM that doesn't enable all instructions or something like that.

**Comment by axsk** [comment]
Oh, I indeed am running on VirtualBox... I also use the Make.user from https://github.com/Keno/Cxx.jl as I wanted to try out the new debugger, might this be involved?

I will check how to force LLVM to get the right processor type, thank you so far.
Any further suggestions are very welcome :)

**Comment by tkelman** [comment]
32 bit or 64 bit? For 64 bit you can set `override MARCH=x86-64` in `Make.user` and hopefully virtualbox will handle it better

**Comment by axsk** [comment]
It compiled and runs with that additional line, thank you a lot!
