### ISSUE TITLE
Move `getindex` on RemoteRef back into Base.

### ISSUE THREAD

**Issue by bermanmaxim** [JuliaLang/julia#11934]
While reproducing the first commands in [documentation on parallel computing](https://github.com/JuliaLang/julia/blob/master/doc/manual/parallel-computing.rst), I noticed a mistake: on julia master branch, the commands

```
r = remotecall(1, rand, 2, 2)
remotecall_fetch(1, getindex, r, 1, 1)
```
(following L.89) yield an error because `getindex` does not operate on RemoteRefs. I believe the correct syntax is
```
remotecall_fetch(1, r->getindex(fetch(r), 1, 1), r)
```
but maybe there is another way of letting a process fetch a reference that we know is already attached to this process ?

**Comment by lostanlen** [comment]
Welcome to the party @bermanmaxim. There is a mistake in the doc indeed.
The solution would either be

1. what you suggested:
   ```remotecall_fetch(1, r->getindex(fetch(r), 1, 1), r)```

2. using the ```@spawn``` macro:
   ```
   r11 = @spawn getindex(fetch(r),1,1)
   fetch(r11)
   ```
(my variable name ```r11``` is certainly suboptimal).

There is a short discussion about this a few lines later in the doc you're reading.


> Note that we used 1 .+ fetch(r) instead of 1 .+ r. This is because we do not know where the code will run, so in general a :func:`fetch` might be required to move r to the process doing the addition. In this case, :obj:`@spawn` is smart enough to perform the computation on the process that owns r, so the :func:`fetch` will be a no-op.

**Comment by amitmurthy** [comment]
The documentation is correct. This is one of the unintended consequences when we moved DArrays out of base.

See https://github.com/JuliaParallel/DistributedArrays.jl/blob/d0fa5a4d096215ba3844d4de1e367c396e29181b/src/DistributedArrays.jl#L403-L408

Will fix and add a test.

**Comment by bermanmaxim** [comment]
Thanks @lostanlen, I noticed the documentation was mentioning these lines later, and supposed this paragraph would have to be restructured a bit... But if @amitmurthy adds `getindex(r::RemoteRef, ...)`  back into base, all is well ;)
