### ISSUE TITLE
Pkg.generate() should provide a REQUIRE file

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11931]
We are recommending that every package includes a REQUIRE file with a minimum Julia version that the package supports.

**Comment by jiahao** [comment]
+1

**Comment by dpsanders** [comment]
+1. 

Perhaps change the issue title to "Pkg.generate() should automatically provide a REQUIRE file". 
This REQUIRE file should perhaps contain by default the Julia version that the Pkg.generate() command is being run on.

**Comment by WestleyArgentum** [comment]
+1

**Comment by tkelman** [comment]
+1. When `VERSION.patch` is 0 and `VERSION.prerelease` is nonempty, should we use `VERSION.minor - 1` ?

**Comment by tkelman** [comment]
See #12215 for implementation.
