### ISSUE TITLE
Rename METADATA.jl to CuratedPackages.jl

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/julia#11930]
This will make the curated repository of repositories more descriptive, thereby complying with its own naming guidelines :smile:

**Comment by milktrader** [comment]
Sorry, this is probably better in METADATA.jl. Closing this.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/METADATA.jl/issues/2800

**Comment by tkelman** [comment]
Presumably [this line](https://github.com/JuliaLang/julia/blob/dcc45968643e9756866a43c3c2155457c85634a5/base/pkg.jl#L10) would need to change.
