### ISSUE TITLE
A\b DimensionMismatch for underdetermined system with A::Matrix{Int64}

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#11949]
I just encountered the following oddity when A is 2x3 and b is 2x1 - I get a DimensionMismatch error which is dependent on the input *numerical values*, not only the shape of A and b:

```julia
julia> [1 0 0; 0 1 0] \ [1;1]
ERROR: DimensionMismatch("matrix is not square")
 in chksquare at ./linalg.jl:176
 in call at linalg/triangular.jl:14
 in A_ldiv_B! at linalg/qr.jl:317
 in \ at linalg/qr.jl:421
 in \ at linalg/dense.jl:402

julia> [1 0 0.1; 0 1 0] \ [1;1]
3-element Array{Float64,1}:
 0.990099 
 1.0      
 0.0990099
```

According to the docs, "For rectangular "A" the result is the minimum-norm least squares solution computed by a pivoted QR factorization of "A" and a rank estimate of A based on the R factor."  The correct solution for the first problem should be `[1,1,0]` in that case.

**Comment by c42f** [comment]
Ah, I've just realized that this isn't a problem with the numerical values, it's a type problem - with the first version above, the matrix is a `Array{Int64,2}` and goes through a different code path.  On the other hand, forcing the matrix to be Float64:

```julia
julia> [1.0 0 0; 0 1 0] \ [1;1]
3-element Array{Float64,1}:
 1.0
 1.0
 0.0
```

as expected.

**Comment by andreasnoack** [comment]
Confirmed. There is a promotions problem here. I'll take a look.

**Comment by c42f** [comment]
great, thanks :)
