### ISSUE TITLE
@printf's differences from C should be resolved or documented

### ISSUE THREAD

**Issue by dfannius** [JuliaLang/julia#11942]
See the discussion in issue #11599. When attempting to add support for `%g` to `@printf`, I noticed that the behavior of the `%e`, `%E`, `%f` and `%F` flags differs from that of the standard C library in the case of `NaN` and `Inf`. C prints them as all uppercase or all lowercase depending on the flag, while Julia always prints them as `NaN` and `Inf`.

Everyone with an opinion in the original discussion (including me) seems to think that Julia's behavior is fine, but if it differs from the C behavior, the difference should probably be documented.

**Comment by ScottPJones** [comment]
I'd recommend definitely document, and implement `%g` compatible with the Julia way (`Inf`/`NaN`).

**Comment by bjarthur** [comment]
https://github.com/JuliaLang/julia/issues/14908 is related

**Comment by eulerkochy** [comment]
Is this issue resolved or still open?

**Comment by StefanKarpinski** [comment]
Still open, I believe. Would be a great documentation contribution.

**Comment by quinnj** [comment]
It seems the original ask was implemented in https://github.com/JuliaLang/julia/pull/18967
