### ISSUE TITLE
Bug in handling EAGAIN?

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#11953]
Seeing a bunch of 

```
.....
ERROR (unhandled task failure): accept: resource temporarily unavailable (EAGAIN)
 in accept_nonblock at socket.jl:723
 in accept_handler at multi.jl:792
 in uv_connectioncb at stream.jl:407
ERROR (unhandled task failure): accept: resource temporarily unavailable (EAGAIN)
 in accept_nonblock at socket.jl:723
 in accept_handler at multi.jl:792
 in uv_connectioncb at stream.jl:407
ERROR (unhandled task failure): accept: resource temporarily unavailable (EAGAIN)
 in accept_nonblock at socket.jl:723
 in accept_handler at multi.jl:792
 in uv_connectioncb at stream.jl:407
......
```

on one of the workers on a SLURM cluster. The worker just keeps printing this in runaway loop indefinitely. Looks like we are trying again on a EAGAIN, but not in the right way?

**Comment by amitmurthy** [comment]
@vtjnash 

I changed the accept handler from
```
    client = accept_nonblock(server)
    process_messages(client, client)
```

to 

```
    client = accept_nonblock(server)
    yield()
    isa(client, TCPSocket) && process_messages(client, client)
```

and now I see

```
julia: src/unix/async.c:158: uv__async_io: Assertion `n == sizeof(val)' failed.

signal (6): Aborted
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x2aaaacb5d74e)
__assert_perror_fail at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x2aaaaae3775b)
uv__io_poll at /scratch/users/amitm/computenode/julia/usr/bin/../lib/libjulia.so (unknown line)
uv_run at /scratch/users/amitm/computenode/julia/usr/bin/../lib/libjulia.so (unknown line)
process_events at ./stream.jl:639
wait at ./task.jl:312
accept_handler at multi.jl:793
jlcall_accept_handler_21496 at  (unknown line)
jl_apply_generic at /scratch/users/amitm/computenode/julia/usr/bin/../lib/libjulia.so (unknown line)
uv_connectioncb at stream.jl:407
jlcapi_uv_connectioncb_21454 at  (unknown line)
uv__server_io at /scratch/users/amitm/computenode/julia/usr/bin/../lib/libjulia.so (unknown line)
jlcapi_uv_connectioncb_21454 at  (unknown line)
```

I think EAGAIN ought to be handled by libuv itself. Any ideas?

**Comment by amitmurthy** [comment]
This issue is showing on the SLURM cluster when we try to launch 1024 workers, with 64 workers per machine. What I suspect is happening is that some of the machines are running out of local port numbers due to our all-to-all connection setup. Machines with higher pid workers would need 64*1024 unique client port numbers and hence we see the EAGAIN.

A fix for the SLURM environment would be to set SO_REUSEPORT on the client sockets. I'll try and confirm if the fix works, but, for this issue, it would be nice to prevent such runaway looping if possible.

**Comment by brenhinkeller** [comment]
Seems like the original bug here was fixed in the linked PR (https://github.com/JuliaLang/julia/pull/12168) but the issue was never closed. I'll close this in the interest of housekeeping, but feel free to reopen if that's a mistake!
