### ISSUE TITLE
Delay finalizers until after codegen is done

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11956]
On the mailing lists @vtjnash noted that we have the potential for recursive codegen if the GC tries to run finalizers during codegen. @carnaval Can we delay running finalizers while in codegen?

**Comment by carnaval** [comment]
would probably be fine, put the run_finalizers() in gc.c under a global flag, then maybe do the call when you reenable them (and probably need to put it under a jl_in_gc = 1 to avoid running gc while doing the backlog)

**Comment by tkelman** [comment]
See a backtrace that might be relevant at https://github.com/JuliaLang/julia/pull/11937#issuecomment-117368868.

@vtjnash has a sneaky feeling that this may be behind at least part of #7942 / #11818

**Comment by ihnorton** [comment]
Semi-related: #5502

**Comment by tkelman** [comment]
Can someone propose a patch for this? I can easily check whether any change will make #7942 / #11818 any better.

**Comment by ihnorton** [comment]
I don't really understand the parenthetical of @carnaval's comment, but for the first part I think it could be as simple as a counter in `to_function` (there's actually a commented-out counter variable there already):

https://github.com/JuliaLang/julia/blob/b824dc9dba77237a88c76a3f620f5bfa36928ba6/src/codegen.cpp#L730-L793

Then pop the counter on the other side (be sure to reset it in the `JL_TRY` block too).

Then check if the counter is non-zero in `run_finalizers`:

https://github.com/JuliaLang/julia/blob/d2f065e91627e30f6ea4957ecfe3c1947c5a8803/src/gc.c#L149-L159

**Comment by tkelman** [comment]
Thanks, @ihnorton. What's more problematic here, emit or compile?
