### ISSUE TITLE
Deprecate `Uint`, `Uint32` etc?

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#11964]
I thought that with #8905 and #8907 the names `Uint`, `Uint32` etc. would be deprecated, but that is not the case on latest master:

```julia
julia> Uint
UInt64

julia> Uint32
UInt32

julia> versioninfo()
Julia Version 0.4.0-dev+5710
Commit af6f214* (2015-06-30 17:38 UTC)
  System: Darwin (x86_64-apple-darwin14.3.0)
```

**Comment by yuyichao** [comment]
The issue is that we [do not currently have a way to deprecate types](https://github.com/JuliaLang/julia/issues/11200)

**Comment by dpsanders** [comment]
Ah yes, thanks. But can we at least deprecate the constructor-type `call`s, `Uint(3)` etc.?

**Comment by JeffBezanson** [comment]
dup of #11200 
`Uint` has to be an alias for `UInt`, so we can't separately deprecate the constructor.

**Comment by StefanKarpinski** [comment]
What we really need is a mechanism for deprecated exports – i.e. exports that continue to be available, but when someone uses such a binding, a warning is emitted.
