### ISSUE TITLE
REPL behaves strangely when pasting multiline strings

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11968]
```
julia> macro foo_str(x)
       @show x
       end

julia> foo"""
       a
       """

       foo"""
       b
       """
x = "a\n"
(anonymous function)
```

**Comment by Keno** [comment]
This has to do with doc translation:
```
julia> parse("""
       foo\"\"\"
       a
       \"\"\"

       foo\"\"\"
       b
       \"\"\"
       """)
:(Base.@doc @foo_str("a\n") @foo_str("b\n"))
```
@JeffBezanson Maybe this should only apply to plain strings?

**Comment by Keno** [comment]
It seems like having custom string literals be possible was intentional, however, that just seems way to crazy if those string literals actually have meaning (say for Cxx or an SQL parser, etc.). May I suggest limiting this do say strings that start with `doc`, e.g. `@docmd_str`.

**Comment by ScottPJones** [comment]
Shouldn't the doc system leave any string alone, unless it is a "void" string? (not used or returned or anything?)  This can break things seriously if it is modifying strings that were say, going to be returned from a function.
