### ISSUE TITLE
Performance regression; likely push!(v::Vector{Int}, i::Int)

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#11960]
Following up on 

https://groups.google.com/d/msg/julia-users/9fCcUvZ6V2Y/S3KQsVGoY6EJ

I think I've found the issue.

Line 72 in dijkstra.jl is
```
push!(preds[v], u)
```
`preds[v]` is a `Vector{Int}` and `u` is an `Int`.

In dev+5712, this line represents 10575 of 49024 total samples, or 21.5% of the time.

In dev+5008, the line represents 1580 of 11066 total samples, or ~14.3% of the time.

(same graph).

Did something change with `push!()` lately?

This is further broken down into:

```
      10575 ....julia/v0.4/LightGraphs/src/dijkstra.jl; dijkstra_shortest_paths; line: 72
       140  ./array.jl; push!; line: 0
       164  ./array.jl; push!; line: 441
       8236 ./array.jl; push!; line: 442
       600  ./array.jl; push!; line: 443
```

**Comment by sbromberger** [comment]
Doing a bisect now.... so far +5624 is good.

**Comment by KristofferC** [comment]
I think it is easier if you give the specific commit SHA.

**Comment by sbromberger** [comment]
@KristofferC I will - this is just for me to keep track during the bisect.

**Comment by yuyichao** [comment]
@sbromberger In the off chance that you didn't know about it, there's `git bisect` command that can keep track of it for you. You can also record the SHA's of the commit range and restart the bisect if necessary.

**Comment by sbromberger** [comment]
@yuyichao that's what I'm using. I'm just being extra-careful here since my machine wants to restart due to software updates.

**Comment by yuyichao** [comment]
I see. That's why I mentioned restarting with recorded SHA, which is what I usually do if I want to do sth unsafe during bisect.

Anyway, please do whatever works for you. Looking forward to know the result.

**Comment by sbromberger** [comment]
Thanks. I hope the updates to https://github.com/JuliaLang/julia/issues/11960#issuecomment-117370489 aren't resulting in multiple emails.

**Comment by yuyichao** [comment]
> I hope the updates to #11960 (comment) aren't resulting in multiple emails.

Editing comment does not generate new email notifications (not for now at least). Which is sometimes useful and sometimes annoy....

**Comment by sbromberger** [comment]
This is weird: my bisects went like this:

5.  +5689: good
6.  +5700: BAD
7.  +5694: good
8: +5696: good
9: +5698: good
10: +5646: good <----- why did it go back to 5646?

**Comment by yuyichao** [comment]
If I have to guess, the commit number report can be weird when there's branches (merges), which is another advantage of using SHA to record the progess.

**Comment by sbromberger** [comment]
Yeah. I can't reproduce this now. I've been bisecting for 2 hours. My process has been

```
git bisect <good | bad>
make
usr/bin/julia
<test here and exit>
<repeat>
```

I'm now back at master (`d092dd0`) and it's not giving me the same times it was... they're much faster.

**Comment by KristofferC** [comment]
Did you have the very latest master when you tested originally? There has been some regressions fixed for performance in arrays quite recently.

**Comment by sbromberger** [comment]
@KristofferC I had dev+5712 from today (`d092dd0`). That was what was giving me the poor performance initially. 

I've just wiped out my entire julia build directory and will start over.

**Comment by sbromberger** [comment]
I can't reproduce this reliably so closing it out. The regression was there but after a rebuild and move to dev+5726 (`eecbe9f`) I can't get it.
