### ISSUE TITLE
NTuple does not like unsigned integers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11967]
This was the cause of a rather frustrating bug I had today:
```
Ref{NTuple{0x0000000000000004,UInt8}}()
Base.RefValue{NTuple{0x0000000000000004,UInt8}}(#undef)
```

**Comment by yuyichao** [comment]
We should really have a warning or error if the first parameter is not an `Int` (or whatever not recognized....)

**Comment by yuyichao** [comment]
In fact, it doesn't like anything other than `Int`.

```julia
julia> NTuple{1, Int} == Tuple{Int}
true

julia> NTuple{Int32(1), Int} == Tuple{Int}
false
```

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/9233

**Comment by ScottPJones** [comment]
Why can't `NTuple` be made to accept any `Unsigned` as well as `Integer`?
`Unsigned` even makes more sense, conceptually, than `Integer`, for a length parameter.
