### ISSUE TITLE
Redundant definition of `<<` in `int.jl`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#11963]
While writing #11962, I noticed that the definitions of the bit-shift operators `<<` etc. on line 99-105 of https://coveralls.io/builds/2869755/source?filename=base%2Fint.jl#L99, which show up as being untested, seem to be redundant, as confirmed by the output of `methods(<<)`, which shows only the version defined on line 110 of `int.jl`.

Should I prepare a PR to remove these lines, or is there something I'm missing?

**Comment by StefanKarpinski** [comment]
Sure, but do beware different platforms – I'm not sure it's the case here but sometimes things get overwritten on one platform but not another.

**Comment by StefanKarpinski** [comment]
I.e. 32-bit vs 64-bit.

**Comment by JeffBezanson** [comment]
Those really do look redundant to me.
