### ISSUE TITLE
Mat Vec Multiplication fails when the elements of Vec are arrays

### ISSUE THREAD

**Issue by rajaths589** [JuliaLang/julia#11978]
fails at /base/linalg/matmul.jl at line 356.
zero(R) does not work in this case. 

[ Discussed on julia-dev ]

**Comment by jiahao** [comment]
Yes , A=zero(R) currently does not work on R types that are Arrays of Arrays because it doesn't have enough information to initialize the inner arrays, and therefore A can't be initialized.

**Comment by rajaths589** [comment]
I proposed a solution on the group and @timholy proposed a different one and a better one.
we can change A = zero(C[1]) to make it work.

**Comment by rajaths589** [comment]
Although, i think it requires a change to the similar function.

**Comment by jiahao** [comment]
Could you link to the discussion?

**Comment by rajaths589** [comment]
https://groups.google.com/forum/#!topic/julia-dev/4X7R8Y-lods

**Comment by rajaths589** [comment]
A = zero(C[1]) does not work because on line 68 matmul.jl ,
similar(x,TS,size(A,1)) returns an array of #undef. Therefore, C[1] becomes an access to undefined reference.

**Comment by rajaths589** [comment]
i guess the easiest way to fix it is
z = zero(A[1]*B[1]). although, i have not been able to fix this for genmatmatmul. Any suggestions?
