### ISSUE TITLE
Can't name globals "META" in documented modules.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaLang/julia#11974]
CC: @one-more-minute, @hayd.
Ref: https://github.com/one-more-minute/Markdown.jl/issues/24

A module's docstrings are stored in a constant called ``META``. This throws confusing errors when a user tries to name something the same:

```jl
module M

const META = "thing"

"1"
f() = 1

end
```

results in

```
ERROR: LoadError: MethodError: `get!` has no method matching get!(::ASCIIString,::Base.Doc
Closest candidates are:
  get!(!Matched::ObjectIdDict, ::Any, ::Any)
  get!{K,V}(!Matched::Dict{K,V}, ::Any, ::Any)
  get!{K}(!Matched::WeakKeyDict{K,V}, ::Any, ::Any)
```

and

```jl
module M

"1"
f() = 1

const META = "thing"

end
```

results in

```
ERROR: LoadError: invalid redefinition of constant META
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:305
 in _start at ./client.jl:405
```

Do we want to leave the naming as is and document where the docstrings are stored or rename ``META`` to something else?

**Comment by tkelman** [comment]
I vote for renaming, I dislike magic constants like this. Which PR was this originally introduced in?

**Comment by MichaelHatherly** [comment]
> Which PR was this originally introduced in?

5fbedc75cfecfcf42e01f288f0e2d96d4fc0ee4b

**Comment by ScottPJones** [comment]
Shouldn't special names like this be in the form __<name>__?

**Comment by JeffBezanson** [comment]
Yes, I suppose we should double-underscore this.

**Comment by vtjnash** [comment]
wouldn't it be more straightforward to use a WeakKeyDict inside Base.Docs? Or is the concern there that #8745 doesn't really support that?

**Comment by MichaelHatherly** [comment]
> Or is the concern there that #8745 doesn't really support that?

@vtjnash I believe that that was the concern, though @one-more-minute might have had other reasons perhaps? Is there a way around that or is it a limitation of static compilation?
