### ISSUE TITLE
generated function caching incorrect for types

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11982]
```
julia> @generated function foobar(T)
       s = string(T.parameters[1])
       :( $s )
       end
foobar (generic function with 1 method)

julia> foobar(Float32)
"Float32"

julia> foobar(Int32)
"Float32"

julia> foobar(Int)
"Float32"
```

**Comment by mauro3** [comment]
Here is another issue with generated function cache problems:  #10178. Maybe related?

**Comment by yuyichao** [comment]
Actually what is the expected behavior in this case?

The same with normal functions any only specialize on `::DataType` unless explicitly specify `::Type{T}` as parameter?

**Comment by Keno** [comment]
If they only specialize on DataType, then `T` should be DataType.
