### ISSUE TITLE
At_mul_B! no longer works for sparse matrices in Julia v0.4

### ISSUE THREAD

**Issue by weijianzhang** [JuliaLang/julia#11980]
Suppose I have 
```julia
julia> A = spzeros(Float64, 3, 3)
3x3 sparse matrix with 0 Float64 entries:

julia> v = Array(Float64, 3)
3-element Array{Float64,1}:
 0.0
 0.0
 0.0

julia> b = ones(Float64, 3)
3-element Array{Float64,1}:
 1.0
 1.0
 1.0
```
Then ``At_mul_B!(v, A, b)`` will return a MethodError in Julia v0.4

```julia
julia> At_mul_B!(v, A, b)
ERROR: MethodError: `At_mul_B!` has no method matching At_mul_B!(::Array{Float64,1}, ::Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1})
```

**Comment by tkelman** [comment]
please provide `versioninfo()` - this was tweaked recently

**Comment by weijianzhang** [comment]
Here it is. 
```julia 
julia> versioninfo()
Julia Version 0.4.0-dev+5721
Commit 81b5064* (2015-06-30 21:50 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by KristofferC** [comment]
I read somewhere that it doesn't work when A is a vector anymore.

**Comment by andreasnoack** [comment]
Eventually, the in-place API now allows for scaling of `AB` and `C` which is the reason you got a no method error here. Instead this could be computed with `At_mul_B!(1.0,A,b,0.0,v)`. However, the dense in-place matrix multiplication API hasn't changed yet so I've added compatibility methods in 126b5d41947b96fe1db4a1450fc5c5d4beae5187 such that `At_mul_B!(b,A,b)` works again.
