### ISSUE TITLE
Return the exception thrown in `@test_throws`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11981]
I find it useful sometimes to make sure certain useful information are in the exception thrown and the return value was `nothing` anyway.

Example: https://github.com/JuliaLang/julia/commit/2010a26762660ecfa1c83d998e2fc0d1704e69f5#diff-75b23cc61d190dd99feab17b8e297ee3R3064

**Comment by tkelman** [comment]
makes sense to me, could be useful

**Comment by ScottPJones** [comment]
I like that very much! I'll have to start using that testing style for Unicode errors.
