### ISSUE TITLE
@doc hides functions with @everywhere

### ISSUE THREAD

**Issue by jltmtz** [JuliaLang/julia#11995]
```julia
@doc "foos" ->
@everywhere function foo(a)
  a[:] = rand( length(a) )
end

b = zeros(b);
foo(b)
```

Gives the ugly error

```julia
ERROR: LoadError: UndefVarError: foo not defined
```

The problem does not happen if there is not an `@everywhere` macro in the function.

I'm using version 0.4.0-dev+5464.

**Comment by yuyichao** [comment]
Dup of #11993 ?

**Comment by jltmtz** [comment]
Ah, a special case of. #11993 beat me by an hour :)
