### ISSUE TITLE
Doc string syntax does not mesh well with macros

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11993]
```julia
macro id(f)
esc(f)
end
```
```julia
julia> """
       """
       @id immutable bar
       x::Int
       end
(anonymous function)

julia> bar
ERROR: UndefVarError: bar not defined
```

**Comment by yuyichao** [comment]
I've got this case working with the simple patch attached. However,

1. I'm not sure if using `macroexpand` in a macro is allowed or is a good idea. (Main reason this is not a PR)

2. It still does not work for macros without an argument because it conflicts with `@doc`'s syntax to document a macro with

```julia
@doc "<doc>" @macro_to_be_doc
```

Maybe we can disallow this syntax to be used with auto `@doc` in the parser.

```diff
diff --git a/base/docs/Docs.jl b/base/docs/Docs.jl
index 11eade7..45e296d 100644
--- a/base/docs/Docs.jl
+++ b/base/docs/Docs.jl
@@ -283,6 +283,9 @@ end
 fexpr(ex) = isexpr(ex, :function, :(=)) && isexpr(ex.args[1], :call)
 
 function docm(meta, def)
+    if isexpr(def, :macrocall) && length(def.args) > 1
+        def = macroexpand(def)
+    end
     def′ = unblock(def)
     isexpr(def′, :macro) && return namedoc(meta, def, symbol("@", namify(def′)))
     isexpr(def′, :type, :bitstype) && return typedoc(meta, def, namify(def′.args[2]))
@@ -294,6 +297,9 @@ function docm(meta, def)
 end
 
 function docm(ex)
+    if isexpr(ex, :macrocall) && length(ex.args) > 1
+        ex = macroexpand(ex)
+    end
     isa(ex,Symbol) && haskey(keywords, ex) && return keywords[ex]
     isexpr(ex, :->) && return docm(ex.args...)
     isexpr(ex, :call) && return :(doc($(esc(ex.args[1])), @which $(esc(ex))))
```

```julia
julia> macro id(f)
       esc(f)
       end

julia> """
       """
       @id immutable bar
       x::Int
       end

julia> bar
bar

julia> bar(1)
bar(1)
```

**Comment by Keno** [comment]
I think we should also consider the case where the macro might want to generate multiple things, (say a type an it's constructor). I think the easiest thing would be to make the doc macro document the first thing in a block. Alternatively, we could do the same for `toplevel` exprs, to still disallow manually writing a docstring for a `begin; end` block. Thoughts?

**Comment by MichaelHatherly** [comment]
> I think we should also consider the case where the macro might want to generate multiple things

@Keno, see https://github.com/JuliaLang/julia/pull/13006 for the current proposal to support this.
