### ISSUE TITLE
DOI badge in README and downloads

### ISSUE THREAD

**Issue by cranmer** [JuliaLang/julia#11990]
I'd suggest adding the zenodo DOI link to the README and downloads pages. 

```
[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.18914.svg)](http://dx.doi.org/10.5281/zenodo.18914)
```

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.18914.svg)](http://dx.doi.org/10.5281/zenodo.18914)

Difficulty is that there is a DOI for each release. 

Suggestion:
- Julia team decides on canonical citation for README 
- [downloads page ](http://julialang.org/downloads/) links to DOI corresponding to release.

**Comment by IainNZ** [comment]
I think the preference is to have a paper about Julia be the primary citable thing, but I'm not sure what the preferred option is (right now its maybe http://arxiv.org/abs/1411.1607)

**Comment by cranmer** [comment]
Yes, there is a transition going on in terms of norms and practices. Many are trying to encourage that the software itself is cited. Citing the arxive paper for the language has advantages, but it also doesn't reward the additional contributors for the newest releases.  There is a hybrid that one cites the arxiv paper for the language and the DOI for the specific version that they used (which has more contributors). 

Another option, which technically seems nicer, is to have people cite the DOI for the version they use and edit the metadata of the zenodo entry so that it is a "SupplementTo" the original arxiv paper. Then the citation chain is machine readable.

**Comment by jakebolewski** [comment]
@jiahao didn't you have a suggestion for this at some point?

**Comment by jiahao** [comment]
Yes, I had submitted #7964. The problem with Zenodo is that it is associated with a specific release tag which has to be created via GitHub's web api. This creates a catch-22 where the release tagged by Zenodo creates a badge that you'd want to insert into the README, but that requires a new commit, so the release tag has to be manually updated to point to the new commit. Last I tried (a year ago), Zenodo was not happy about changing the commit associated with a release tag. Maybe this is fixed now, but I'm not sure. Also, I think an owner of the julia repo has to make sure that Zenodo integration is still on. (It got turned off at some point)

**Comment by Keno** [comment]
Have you contacted them about this concern? Maybe they can come up with a solution.

**Comment by tkelman** [comment]
The Zenodo webhook is still enabled and has been firing for every 0.3 release so far.

**Comment by jakebolewski** [comment]
What is left to do here? Add a link to the README / website?

**Comment by cranmer** [comment]
I think the issue is that you have a DOI for each version, so you need to decide if you want to update the badge for each release.  

Zenodo does have a way to reserve a DOI before it is minted, so one could solve @jiahao 's catch-22 problem, but I don't think that is integrated with GitHub - Zenodo release hook.

I asked Arfon and Lars to weigh in here:
https://twitter.com/KyleCranmer/status/631161356927041536

**Comment by gdkrmr** [comment]
There should also be something like `Pkg.cite("base"; format=:bibtex)` for packages.

**Comment by dhimmel** [comment]
If you go to https://zenodo.org/account/settings/github/ and click on one of the DOI badges, you get a badge that auto-updates. You can use that badge in your `README.md`. For my repository, this looks like:

```
[![DOI](https://zenodo.org/badge/14475/dhimmel/lincs.svg)](https://zenodo.org/badge/latestdoi/14475/dhimmel/lincs)
```

And then you can use the DOI-versioned badges on the [release descriptions](https://github.com/JuliaLang/julia/releases). For my repository, this looks like:

```
[![DOI: 10.5281/zenodo.47223](https://zenodo.org/badge/doi/10.5281/zenodo.47223.svg)](https://doi.org/10.5281/zenodo.47223)
```

**Comment by KristofferC** [comment]
Reopen/comment if https://julialang.org/publications/ is not good enough.
