### ISSUE TITLE
replcompletions test fails with mkdir: File exists

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#11992]
This happens in a Cygwin cross-compile, 100% repeatable. It's a strange one though because if I remove any single test from the list below it passes fine:
```
$ usr/bin/julia -e 'versioninfo()' && JULIA_CPU_CORES=1 usr/bin/julia test/runtests.jl sorting statistics spawn priorityqueue file broadcast socket readdlm combinatorics replcompletions
Julia Version 0.4.0-dev+5764
Commit afc6308* (2015-07-02 21:21 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
     * sorting              in  31.58 seconds
     * statistics           in  14.16 seconds
     * spawn                      [stdio passthrough ok]
 in  16.75 seconds
     * priorityqueue        in   1.22 seconds
     * file                 in  10.85 seconds
     * broadcast            in  10.65 seconds
     * socket               in   7.50 seconds
     * readdlm              in  15.74 seconds
     * combinatorics        in   2.83 seconds
     * replcompletions     exception on 1: ERROR: LoadError: SystemError: mkdir: File exists
 in mkdir at file.jl:42
while loading D:\cygwin64\home\Tony\julia\test\replcompletions.jl, in expression starting on line 395
ERROR: LoadError: LoadError: SystemError: mkdir: File exists
 in mkdir at file.jl:42
while loading D:\cygwin64\home\Tony\julia\test\replcompletions.jl, in expression starting on line 395
while loading D:\cygwin64\home\Tony\julia\test\runtests.jl, in expression starting on line 5
```

**Comment by blakejohnson** [comment]
Some of the file completions stuff might be a little brittle because there are a few tests that don't clean up after themselves if they fail.

**Comment by tkelman** [comment]
c2a28eeb97dd2d8d918c30ff7da9e9d07685ba6c is the first bad commit

$ git bisect log
git bisect start
\# bad: [afc63084b41f3e0f102d6c4327a69bb1368b7d3b] fix `#11982`
git bisect bad afc63084b41f3e0f102d6c4327a69bb1368b7d3b
\# good: [84ed5f3ec380f845450c10aa7e4bbfdffbfe8cf5] restore functionality of pure-minimalistic repl for when Base._start is not defined
git bisect good 84ed5f3ec380f845450c10aa7e4bbfdffbfe8cf5
\# bad: [bee46ee9fbbcd258e360d774ebbd8b67ae3c52d7] Merge pull request `#11629` from JuliaLang/sk/shifts
git bisect bad bee46ee9fbbcd258e360d774ebbd8b67ae3c52d7
\# bad: [0cebd59668e21dd3875ecf186abfa33cf98c6089] Merge pull request `#11411` from JuliaLang/nalimilan/targets
git bisect bad 0cebd59668e21dd3875ecf186abfa33cf98c6089
\# bad: [9bc158a6afdc11f6442c3560b1ed6ad2347f142e] Merge pull request `#11293` from garrison/dlopen_finalizer
git bisect bad 9bc158a6afdc11f6442c3560b1ed6ad2347f142e
\# bad: [f043f862eaf7736beeff1bbe2fa344d5b108bbdd] Test list is now in test/choosestests.jl
git bisect bad f043f862eaf7736beeff1bbe2fa344d5b108bbdd
\# bad: [9a47c3b833758c1170ffc428eb6162fdae887111] Merge pull request `#11192` from ScottPJones/spj/asciiutf8
git bisect bad 9a47c3b833758c1170ffc428eb6162fdae887111
\# good: [e2dbab5188b2219f4036cd076b23363000deed9b] Merge pull request `#11255` from JuliaLang/ksh/arraytests
git bisect good e2dbab5188b2219f4036cd076b23363000deed9b
\# bad: [c2a28eeb97dd2d8d918c30ff7da9e9d07685ba6c] Merge pull request `#11172` from peter1000/adds_kw_remove_destination_to__mv
git bisect bad c2a28eeb97dd2d8d918c30ff7da9e9d07685ba6c
\# good: [c790369543dfdb3c9663de54641b78c12e275191] Merge pull request `#11253` from JuliaLang/ob/fixsawb
git bisect good c790369543dfdb3c9663de54641b78c12e275191
\# skip: [fec7ef16b3312f3b2eddbd4f0ff006181fbc1c64] Samefile: return false if a path does not exist.
git bisect skip fec7ef16b3312f3b2eddbd4f0ff006181fbc1c64
\# good: [43eb785b3dfc2854246f27fc9ceae30c04ec1202] Adds tests for: `mv` function `#11172`
git bisect good 43eb785b3dfc2854246f27fc9ceae30c04ec1202
\# first bad commit: [c2a28eeb97dd2d8d918c30ff7da9e9d07685ba6c] Merge pull request #11172 from peter1000/adds_kw_remove_destination_to__mv

the skip was a different error message, ` ArgumentError: 'src' and 'dst' refer to the same file/dir.This is not supported.` during the file test. cc @peter1000 I forget, you don't use Windows do you?

**Comment by peter1000** [comment]
No, I don't use any windows.

**Comment by tkelman** [comment]
This actually went away when I cleared out my `/tmp`, so I think it's only an issue that these leave around temporary files when one of the tests fails. The specific list of tests is probably just a consequence of various `srand` calls leading to the same set of file names being used.
