### ISSUE TITLE
Test coverage is really bad on OSX

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#12002]
Running codecov on Ubuntu gets us coverage of 79%. Running on OSX gets 66%. It's unclear to me why this is happening - `multi.jl` is seeing 100 more lines missed, for instance. `string.jl` is seeing 50 more missed. `pkg/entry.jl` isn't getting tested at all. Could this be something weird with Julia's internal coverage metrics on OSX?

**Comment by tkelman** [comment]
What LLVM version are you using? Some of the parallel tests of cluster managers are linux-only I think.

**Comment by kshyatt** [comment]
I'm using LLVM 3.6 I think.

**Comment by tkelman** [comment]
That might be #7910 which is only properly fixed in LLVM svn.

**Comment by Keno** [comment]
Correct :).

**Comment by kshyatt** [comment]
There's no fixed in LLVM-svn tag, darn it. Thanks for the info!

**Comment by yuyichao** [comment]
> There's no fixed in LLVM-svn tag, darn it. Thanks for the info!

There shouldn't be one (since it is not a fixed version) but there probably could be a `fixed in LLVM-3.7`?

**Comment by kshyatt** [comment]
Indeed. Sorry, I was making a bad joke :)

**Comment by yuyichao** [comment]
> Indeed. Sorry, I was making a bad joke :)

Apologize if I had a bad reply to an obvious joke.

Anyway, I'm not exactly sure how the labels should work but I think we could have a llvm-3.7 if there are enough issues that is fixed there.

**Comment by kshyatt** [comment]
Just in case anyone else is running the base coverage tests on OSX: I managed to dramatically close the gap by applying https://github.com/JuliaLang/julia/pull/11954 and using `--precompiled=no` when I run the tests.
