### ISSUE TITLE
mmap_array holds file open

### ISSUE THREAD

**Issue by awf** [JuliaLang/julia#12011]
The following pattern (found in JSON/JSON.jl) appears to leave the filehandle open.   

    filename = "/tmp/t.txt"
    sz = filesize(filename)
    open(filename) do io
        a = mmap_array(Uint8, (sz,), io)
    end

This is evidenced by the fact that a subsequent 
    open(filename, "w") do io
        write(io, "stuff")
    end
Produces `LoadError: SystemError: opening file /tmp/t.txt: Invalid argument` 

Various attempted fixes have not eradicated this behavior.
 - Assigning `a = nothing`
 - `msync(a)`

Tested platform julia 0.4, Windows 8, running in julia.exe

**Comment by tkelman** [comment]
If you're on Windows, then `"/tmp/t.txt"` is not a valid path. The `do` notation is designed to close the filehandle on exit.

**Comment by tkelman** [comment]
Ah but I think you're right, the mmap does hold the handle open on its own, independent of the `open`. Try `finalize(a)` if you're on master.

**Comment by ScottPJones** [comment]
What's invalid about it?
It looks in the tmp directory on the current drive.

**Comment by tkelman** [comment]
Huh. So it does. TIL, here I always thought posix-style absolute paths were only meaningful inside cygwin or msys.

The mostly likely culprit here is the finalizer for `a` hasn't run yet, so either `finalize(a)` or calling `gc()` a few times should result in closing the handle. I think manually running finalizers can be on the slow side so doing it automatically when things go out of scope would not be practical.

**Comment by ScottPJones** [comment]
Back to the days of IBM PC-DOS 1.0, both Unix / and CPM \ have been accepted.

**Comment by quinnj** [comment]
With the new `Mmap.mmap` functionality in 0.4, the correct usage in the case of needing to subsequently re-use/re-mmap the same file on windows is to call `finalize(m)` where `m` is the mmapped `Vector{UInt8}`. 
Alternatively, you can set `m = nothing; gc(); gc()` that will also cleanup the open file mapping.
