### ISSUE TITLE
Typo in DomainError message

### ISSUE THREAD

**Issue by oversky** [JuliaLang/julia#12015]
Julia Version 0.3.10 x86_64-w64-mingw32

How to reproduce:
```julia
julia> 3^-2
ERROR: DomainError
Cannot raise an integer x to a negative power -n. Make x a float by adding
a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n
 in power_by_squaring at intfuncs.jl:60 (repeats 2 times)
```

I believe `(x//1)^-n` should be `(x/1)^-n.`

```julia
julia> (3/1)^-2
0.1111111111111111
```
It took me half hour to figure out that `//` is a type instead of an operator.

**Comment by yuyichao** [comment]
Just to be clear, `//` is an operator, it's an operator that constructs the type.

I think you are right that the error message should be fixed.

**Comment by ivarne** [comment]
Cross reference: https://github.com/JuliaLang/julia/pull/8784, where this wording where added. 

Doesn't `(3//1)^-2` give a reasonable result?

**Comment by oversky** [comment]
OK, I see. It is a "Rational" operator.
There is nothing wrong with the error message.

I am reading through the chapter "Mathematical Operations and Elementary Functions" in the Docs. Rational numbers will be in the next chapter.
Therefore, "//" is strange to me. 
And (3/1)^-2 just happens to be a more reasonable guest.

But why do we make julia deal this negative power in this way?
Excel, matlab, R and python, 
and even my old CASIO calculator can deal this directly.
Is it something about speed?
