### ISSUE TITLE
RFC: string literal prefix registration instead of appending macro names with `_str`

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#12018]
Currently we have special handling of macros based on a naming convention (the `_str` suffix). If someone isn't familiar with this rule and they're reading through Julia code that defines a string macro it's not obvious where the magic is happening that allows someone to define `macro caps_str` and start writing `caps"this is too quiet"`.
```julia
julia> macro caps_str(s)
    uppercase(s)
end

julia> caps"too quiet"
"TOO QUIET"
```

What if we had some sort of `@registerprefix` (name TBD) macro that registered the given symbol with the parser's string literal prefix table. Creating a string literal prefix would then be a 2-step process of defining the macro and then registering it with the parser. This would make it clear to the reader that something special is going on.

This also could be a way to address #11968 because the registration function could take an optional `docstring=true` option which would enable the automatic handling as a docstring. If I understand correctly we currently handle all raw strings or macro'ed strings preceding a declaration as docstrings, and there seems to be interest (#11970) in dividing string macros into those that are promoted to docstring and those that aren't.

```julia
julia> macro cxx(s)
    fancy stuff happens here
end
julia> @registerprefix cxx_str :cxx
julia> cxx"#include <iostream>"
```
```julia
julia> macro caps_str(s)
    uppercase(s)
end
julia> @registerprefix caps_str :caps docstring=true

julia> caps"too quiet"
"TOO QUIET"

julia> caps"don't accidentally run this"
function launch(n::Nuke)
    ...
end
```

**Comment by yuyichao** [comment]
I just feel like this will be more verbose and will make the parser even more context dependent...

**Comment by ssfrr** [comment]
Agreed it's more verbose, but is it adding additional context dependence to the parser? As far as I know this is doing the same thing the parser is already doing (i.e. adding entries to a table of string literal prefixes) but just making it explicit.

**Comment by yuyichao** [comment]
Well the parser parse `doc"<...>"` as `@doc_str("<...>")` now. There isn't a table of string literal prefixes.

```julia
julia> parse("doc\"<...>\"")
:(@doc_str "<...>")
```

**Comment by ssfrr** [comment]
ah, I see. Thanks for the clarification. With that in mind this definitely feels like a bigger change to the underlying infrastructure than I originally thought. Probably not worth it.
