### ISSUE TITLE
make const a toplevel expr or error

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12010]
`const` can cause serious, subtle bugs when combined with precompilation. it is valid to use from the `:toplevel` scope, but it can cause problems if used at runtime (and it's already ignored when specified at the local scope. this could be fixed by warning for and ignoring the const declaration outside of the toplevel scope. or this could be fixed by internally distinguishing between `const` (as it is currently defined) and a new `assigned once` attribute (that provides none of the inference speed benefits of const, but just doesn't allow reassignment).

the following is fine:

``` julia
module Fine
const binding = value
end
```

the following can confuse precompilation (and isn't great for type inference either):

```
module Bad
__init__() = (global const binding = value)
end
```

the following currently is ignored by parsing, so is neither bad nor good:

``` julia
module Either
f() = (const localb = localv)
end
```

**Comment by yuyichao** [comment]
> the following can confuse precompilation (and isn't great for type inference either):

> ```julia
> module Bad
> __init__() = (global const binding = value)
> end
> ```

I think this is still really useful for some packages that load shared libraries.

**Comment by yuyichao** [comment]
IIRC, the plan in https://github.com/JuliaLang/julia/pull/11456 (or a related one) is that the compiler should look inside the function and see if there's a global const defined inside and reserve a slot for it. (Looking for the specific comment now)

**Comment by vtjnash** [comment]
#11456 is about making global variable bindings resolved early, this thread is about disallowing the addition of new global const bindings. https://github.com/JuliaLang/julia/pull/11456#issuecomment-106131253 is exactly the subtle but serious issue that can happen if global const is allowed (since ccall will precompile a call to a static pointer, rather than a runtime lookup)

**Comment by timholy** [comment]
Interesting. What if we define an `__init_pre__()` and `__init_post__()`, and require that any global const assignments happen in `post`? Would that solve the problem?

**Comment by yuyichao** [comment]
> (since ccall will precompile a call to a static pointer, rather than a runtime lookup)

Is this an issue if the pointer is used in the same module and `__init__` (or `__init_post__`) is not run when the module is pre-compiled?

**Comment by vtjnash** [comment]
@timholy that's just:

```julia
module MyModule
__init_pre__() = "here1"
__init_post__() = "there2"

__init__() = __init_post__()
__init_pre__()
end
```

@yuyichao less so, but only because we don't run `__init__` before precompiling the module, so it becomes actually just becomes undefined behavior at runtime due to invalidating type inference.

**Comment by yuyichao** [comment]
> so it becomes actually just becomes undefined behavior at runtime due to invalidating type inference.

Sorry I forgot to mention that this should also be combined with letting typeinf/precompile look into functions (especially `__init__`) to see that the const global will be assigned at runtime.

**Comment by timholy** [comment]
I think I get it now. Presumably "only" affects functions that get JITted before the cache is written?

**Comment by timholy** [comment]
From an inference perspective, I'm guessing that much of the benefit of what we now use `global const ...` for would be obtained if we had an `of_const_type` declaration.

**Comment by vtjnash** [comment]
> Sorry I forgot to mention that this should also be combined with letting typeinf/precompile look into functions (especially __init__) to see that the const global will be assigned at runtime.

@carnaval is that something typeinference could handle?

> I think I get it now. Presumably "only" affects functions that get JITted before the cache is written?

JIT isn't really the right term, since this is AOT compiling. But since this is AOT, it's generally beneficial to do as much work as possible to build a good / complete cache.

**Comment by vtjnash** [comment]
> for would be obtained if we had an of_const_type declaration...

```julia
module OfConstType
const binding = Ref{T}()

binding[] = 1
Base.Test.@test binding[] === 1
end
```

**Comment by timholy** [comment]
Sorry, I don't understand your example.

**Comment by yuyichao** [comment]
> ```julia
> module OfConstType
> const binding = Ref{T}()
>
> binding[] = 1
> Base.Test.@test binding[] === 1
> end
> ```

I guess I wouldn't mind only allow real const in global scope if we can making `var::Type` a syntax sugar for this.

**Comment by vtjnash** [comment]
that seems to be Jeff's plan https://github.com/JuliaLang/julia/pull/11456#issuecomment-106154891

**Comment by yuyichao** [comment]
@timholy 

> Sorry, I don't understand your example.

`binding` is a global const so it will always bind to the same object (type) and therefore `binding[]` always has the same type.

**Comment by yuyichao** [comment]
> that seems to be Jeff's plan https://github.com/JuliaLang/julia/pull/11456#issuecomment-106154891

Would still be nice if accessing them doesn't require adding `[]` though :).

**Comment by timholy** [comment]
Got it. Yes, that's a workable strategy.

**Comment by toivoh** [comment]
I'm still hoping that const will some day be respected in local scope,
please don't make that an error (though I understand it might be considered
a different feature than const at the top level).

**Comment by yuyichao** [comment]
Hmm, even for typed global, it still won't cover this

```julia
__init__() = global const lib_path = find_library(...)

ccall((:sym, lib_path), ...)
```

**Comment by StefanKarpinski** [comment]
This doesn't seem like a high priority given the lack of comment since July 2015.

**Comment by JeffBezanson** [comment]
Might also be helped by #18933 ?

**Comment by StefanKarpinski** [comment]
Resolved: we should do this.
