### ISSUE TITLE
Relocations in libjulia make SELinux mad?

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#12019]
First time I've seen this one:
```
make[3]: Entering directory `/home/centos/buildbot/slave/package_tarball32/build'
 cd base && /home/centos/buildbot/slave/package_tarball32/build/usr/bin/julia -C pentium4 --output-o /home/centos/buildbot/slave/package_tarball32/build/usr/lib/julia/inference0.o -f coreimg.jl
/home/centos/buildbot/slave/package_tarball32/build/usr/bin/julia: error while loading shared libraries: /home/centos/buildbot/slave/package_tarball32/build/usr/bin/../lib/libjulia.so: cannot restore segment prot after reloc: Permission denied
make[3]: *** [/home/centos/buildbot/slave/package_tarball32/build/usr/lib/julia/inference0.o] Error 127
make[3]: Leaving directory `/home/centos/buildbot/slave/package_tarball32/build'
make[2]: *** [julia-sysimg] Error 2
```

This is on our generic Linux binary buildbot, at http://buildbot.e.ip.saba.us:8010/builders/package_tarball32/builds/1001/steps/make%20binary-dist/logs/stdio

Not sure why it hasn't happened before. According to a comment at http://www.cubrid.org/wiki_tutorials/entry/cannot-restore-segment-prot-after-reloc-permission-denied#comment-1981129905, we might need to do something with `chcon -t texrel_shlib_t libjulia.so` ?

**Comment by vtjnash** [comment]
according to http://akkadia.org/drepper/textrelocs.html, there's nothing to do on my machine?
```
jameson@jamesonnash:~/julia/usr/lib$ eu-findtextrel libjulia.so 
eu-findtextrel: no text relocations reported in 'libjulia.so'
jameson@jamesonnash:~/julia/usr/lib$ uname -a
Linux jamesonnash 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:56:26 UTC 2014 i686 i686 i686 GNU/Linux
```

**Comment by tkelman** [comment]
Hm, this might be some specific misconfiguration on the buildbots then. It also looks like `-U_FORTIFY_SOURCE -fPIC` aren't getting applied when building libunwind, which might be related.
