### ISSUE TITLE
Julia 0.3.10 fails to build on openSUSE (i586 and x86_64)

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#12028]
Hi guys,

I'm trying to build julia 0.3.10 in openSUSE and I am having a problem with an undefined function (```addComdat```). The relevant part of the build log is:

```
[   43s] clang -march=core2 -m64 -DJL_SYSTEM_IMAGE_PATH="../lib/julia/sys.ji" -DJULIA_TARGET_ARCH=core2 -DSYSTEM_LLVM -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -g -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.3.10/deps/libuv/include -I/home/abuild/rpmbuild/BUILD/julia-0.3.10/usr/include -DLIBRARY_EXPORTS -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -DNDEBUG -c jl_uv.c -o jl_uv.o
[   43s] In file included from codegen.cpp:531:
[   43s] ./cgutils.cpp:65:5: error: use of undeclared identifier 'addComdat'
[   43s]     addComdat(gv);
```

Fedora Project proposed a patch to fix this issue by removing the call to that function, as can be seen in:

http://pkgs.fedoraproject.org/cgit/julia.git/diff/julia_Fix-building-with-MCJIT-LLVM.patch?h=f22&id=36ea07f630c5fa34d88394859da000ab8732a81d

Can anyone tell me if this patch is the correct way to fix this issue or it is just a temporary fix for the problem?

Regards,
Ronan

**Comment by tkelman** [comment]
The fedora patch from @nalimilan is fine, we merged that into release-0.3 in https://github.com/JuliaLang/julia/pull/11886 and it'll be in 0.3.11. What version of LLVM are you building against on opensuse?

**Comment by ronisbr** [comment]
@tkelman,

Thanks for the prompt reply. I'm building against llvm-3.5.0-4.1.
I will add the patch and try to build it again.

**Comment by ronisbr** [comment]
Everything worked fine with the patch. Now, we have julia 0.3.10 package for openSUSE 13.2 :+1: 
I just need to wait now for official support of LLVM 3.6 to build it for Factory and Tumbleweed.

Thanks @tkelman

**Comment by tkelman** [comment]
Cool, no problem, will have to check out your spec file one of these days when I buy a new machine and put opensuse on it. Is the package in Science, or still your personal repo?

**Comment by ronisbr** [comment]
The package is already in Science, but I also have it in my personal repo to test every new version before committing it to Science.

**Comment by nalimilan** [comment]
Cool to hear that the package has been included in OpenSUSE.

FWIW, I'm going to use a versioned LLVM 3.3 package in Fedora, using whatever version the distro was shipping turned out being very difficult with 0.4. Julia developers no longer want to support 3.3, 3.4, 3.5, 3.6 and 3.7 at the same time. I hope knowing this might spare you some pain...

**Comment by ronisbr** [comment]
Thanks @nalimilan 
I am right now trying to build julia package with LLVM 3.3 an ship it together with the package. Hopefully, I will be able to finally build julia-0.3.10 on Tumbleweed and Factory.
