### ISSUE TITLE
Unable to import PyPlot in julia v0.3.10 Mac OSX

### ISSUE THREAD

**Issue by pmota0** [JuliaLang/julia#12048]
On may Mac running OS X Yosemite (v.10.10.4), typing "using PyPlot" gives the following error in Julia version 0.3.10:

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6

I'm almost sure that this did not occur in v.0.3.9.

**Comment by kshyatt** [comment]
I'm having trouble reproducing this on my Mac (same OSX, same Julia version). Do you happen to know which version of PyPlot & PyCall you're using? This issue might be more appropriate at the [PyPlot.jl](https://github.com/stevengj/PyPlot.jl) repo.
