### ISSUE TITLE
Inconsistent order between FloatingPoints and Rationals

### ISSUE THREAD

**Issue by blkqi** [JuliaLang/julia#12041]
See the "Note" section of the online documentation for `round()`:
http://julia.readthedocs.org/en/latest/stdlib/math/#Base.round

When trying this on julia v0.3.10 I discovered the following inconsistency which seems to break the trichotomy law. 

```
julia> x = 1.15
1.15

julia> @sprintf "%.20f" x
"1.14999999999999991118"

julia> x < 115//100
false

julia> x > 115//100
false

julia> x == 115//100
false
```

**Comment by tkelman** [comment]
Can you try this on an 0.4-dev nightly? I think @simonbyrne fixed this a few months ago on master.

**Comment by blkqi** [comment]
No problem. This is not an issue using the latest nightly: `julia-6eb9133679`.

**Comment by yuyichao** [comment]
Should the fix be backported?

**Comment by tkelman** [comment]
Would have to dig up which PR it was ("fix comparisons between floating point and rationals" or something like that), but at this point I'd rather not make substantial behavioral changes on release-0.3.

**Comment by yuyichao** [comment]
Wasn't too hard given the author and the keywords. https://github.com/JuliaLang/julia/pull/9198.

Indeed looks a little too big (changes and lines) to be backported for me....
