### ISSUE TITLE
Enhancement: would it be possible to add lock() (and possibly other methods) to DevNullStream?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#12050]
```
julia> println(DevNull,"foo")
ERROR: type DevNullStream has no field lock
 in println at stream.jl:226
```

(I'm looking for a system-independent way to throw away `println` output. Am I doing it the right way?)

**Comment by vtjnash** [comment]
sgtm

**Comment by hayd** [comment]
+1.

FWIW I've also seen `ERROR: LoadError: type DevNullStream has no field handle`. From comments elsewhere (not sure where!) I used plain `redirect_stdout`:

```
old_stdout = STDOUT
redirect_stdout()
try
    do_stuff
finally
   redirect_stdout(old_stdout)
end
```
Similar functions are available for stderr and stdin.

For anyone arriving here from google... or github search.

**Comment by JeffBezanson** [comment]
@vtjnash close?

**Comment by vtjnash** [comment]
I don't think I added enough of the methods to get this complete. someone should be able to clone the complete set of methods added to `AbstractPipe` over to `DevNullStream` to get full coverage and close this issue.

**Comment by tkelman** [comment]
fixed by #12839, right?

**Comment by vtjnash** [comment]
mostly, although perhaps not entirely

**Comment by sbromberger** [comment]
Actually, I'm just getting back to this and it's not doing what I had hoped:
```
julia> redirect_stdout(DevNull)
ERROR: MethodError: no method matching redirect_stdout(::Base.DevNullStream)
Closest candidates are:
  redirect_stdout() at stream.jl:1034
  redirect_stdout(::Union{Base.LibuvStream, IOStream}) at stream.jl:1028
  redirect_stdout(::Function, ::Any) at stream.jl:1082
```

Time for a new issue/request?

**Comment by StefanKarpinski** [comment]
Yes, please – seems like a more specific issue.
