### ISSUE TITLE
The Google Compute Engine section of README.md is >1 year old

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#12055]
>Google Compute Engine is evolving rapidly, as is Julia. This section is current as of March 2014 and assumes working knowledge of Google Cloud Services.

>These notes apply to the Debian 7 image currently available on Google Compute Engine and Julia pre-0.3. 

Has someone tested a newer version of Julia on GCE? Can we update this datestamp to be more current? Should we keep this section if no one can confirm this is still working? [The relevant section](https://github.com/JuliaLang/julia#google-compute-engine).

**Comment by ViralBShah** [comment]
I don't think this is required in the README, unless we want to mention how to get Julia running on every cloud service.

**Comment by kshyatt** [comment]
I agree. This seems like the kind of thing that someone could write a Gist about and then it's googleable and updateable as they please.

**Comment by tkelman** [comment]
ref #6301
