### ISSUE TITLE
pointer(x) returns Ptr{T} when x is an Array{T} of non-isbits elements

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12053]
At the moment, `x = pointer([BigFloat(5)])` returns a `Ptr{BigFloat}`, but since that's actually a pointer to an array of pointers, it seems like either the type should be `Ptr{Ptr{BigFloat}}` or this should just be an error.

**Comment by vtjnash** [comment]
i think this is just one of the general flaws in the whole `pointer` method. I attempted to create `Ref` as a fully general replacement that actually handles these sorts of edge-cases with some amount of generality.

**Comment by JeffBezanson** [comment]
In this case `Ref` correctly yields a pointer to the data of a BigFloat element when it returns a `Ptr{BigFloat}`, however the BigFloats are not contiguous so it still doesn't really act like a C array.

**Comment by kshyatt** [comment]
This behaviour hasn't changed on latest master. Do we want to keep it?

**Comment by tkelman** [comment]
Are we planning on fully deprecating `pointer`, or are there use cases that `Ref` doesn't handle?

**Comment by NHDaly** [comment]
So i tried to open this PR  #31978 to fix this, but it's more complex than I had thought. If the answer is that users shouldn't use `pointer`, can we more heavily deprecate it? Maybe even print a warning whenever it's called by users?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/30276. This one is earlier but closing here since the other issue has more discussion.
