### ISSUE TITLE
error: use of undeclared identifier 'globalvars'

### ISSUE THREAD

**Issue by Fedster** [JuliaLang/julia#12061]
Hi,

very latest git pull fails to make:

git fetch && git merge origin
remote: Counting objects: 206, done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 206 (delta 116), reused 77 (delta 77), pack-reused 30
Receiving objects: 100% (206/206), 364.09 KiB | 602.00 KiB/s, done.
Resolving deltas: 100% (122/122), completed with 52 local objects.
From git://github.com/JuliaLang/julia
   4aae6f3..378ab7c  master     -> origin/master
 + bfecea1...2e55431 amitm/channels -> origin/amitm/channels  (forced update)
 * [new branch]      amitm/slurm1000 -> origin/amitm/slurm1000
 + 7927829...73cfb40 dh/spvec   -> origin/dh/spvec  (forced update)
 + 04e3a42...f8eafc2 mn/powtypes -> origin/mn/powtypes  (forced update)
 + 66a5b0f...c742260 omm/doc-transition-2 -> origin/omm/doc-transition-2  (forced update)
 + c8a6b62...09034b2 yyc/cmake  -> origin/yyc/cmake  (forced update)
 + 39cd0c8...672b14a yyc/doc-macro -> origin/yyc/doc-macro  (forced update)
 * [new branch]      yyc/ntuple-intersect -> origin/yyc/ntuple-intersect
 + 74f8a8c...adeae1e yyc/segv-test -> origin/yyc/segv-test  (forced update)
Updating 4aae6f3..378ab7c
Fast-forward
 README.arm.md             |  11 +-
 README.md                 |  12 ---
 base/datafmt.jl           |   2 +-
 base/deprecated.jl        |  86 ++++++++++++++++
 base/exports.jl           |   4 +-
 base/libc.jl              |  63 +-----------
 base/linalg/blas.jl       |   2 +-
 base/mmap.jl              | 312 ++++++++++++++++++++++++++++++++-------------------------
 base/sharedarray.jl       |   6 +-
 base/sysimg.jl            |   3 +-
 contrib/julia-mode.el     |  34 ++++---
 deps/Makefile             |   3 +-
 deps/libgit2_oldssl.patch |  14 +++
 doc/stdlib/io-network.rst |  33 ++++--
 src/cgutils.cpp           |  73 ++++++--------
 src/codegen.cpp           |  57 +++++------
 src/debuginfo.cpp         |  36 +++++--
 src/disasm.cpp            |   4 +-
 test/choosetests.jl       |   2 +-
 test/file.jl              |  78 ---------------
 test/mmap.jl              | 284 +++++++++++++++++++++++++++++++++++++++++++++++++++
 21 files changed, 707 insertions(+), 412 deletions(-)
 create mode 100644 deps/libgit2_oldssl.patch
 create mode 100644 test/mmap.jl

make testall
    CC src/jltypes.o
    CC src/gf.o
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/codegen.o
codegen.cpp:422:35: error: use of undeclared identifier 'globalvars'
    jl_gen_llvm_gv_array(bitcode, globalvars);
                                  ^
1 error generated.
make[1]: *** [codegen.o] Error 1
make: *** [julia-src-release] Error 2

(On OSX but I doubt it matters).

**Comment by Fedster** [comment]
Still there:

git fetch && git merge origin
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From git://github.com/JuliaLang/julia
   2e55431..1aae3ec  amitm/channels -> origin/amitm/channels
Already up-to-date.

make testall
    CC src/jltypes.o
    CC src/gf.o
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/codegen.o
codegen.cpp:422:35: error: use of undeclared identifier 'globalvars'
    jl_gen_llvm_gv_array(bitcode, globalvars);
                                  ^
1 error generated.
make[1]: *** [codegen.o] Error 1
make: *** [julia-src-release] Error 2

**Comment by one-more-minute** [comment]
Resetting to 584308d fixes this temporarily.

**Comment by tkelman** [comment]
try again at 918ee650539fbe3b50ea5e1efb915ebe7cbdfe31 - new problems though, `is not a recognized processor for this target (ignoring processor)` warnings on all platforms and a 32 bit linux test failure https://travis-ci.org/JuliaLang/julia/jobs/70041689

```
exception on 3: ERROR: LoadError: mismatch of non-finite elements: 
  a = Inf
  0.0 = 0.0
 in test_approx_eq at test.jl:132
 in test_approx_eq at test.jl:150
 in anonymous at no file:298
 in include at ./boot.jl:254
 in runtests at /tmp/julia/share/julia/test/testdefs.jl:197
 in anonymous at multi.jl:837
 in run_work_thunk at multi.jl:590
 in anonymous at task.jl:837
while loading /tmp/julia/share/julia/test/linalg/pinv.jl, in expression starting on line 294
	From worker 2:	     * linalg1              in 104.76 seconds
	From worker 5:	     * linalg/cholesky      in  35.35 seconds
	From worker 4:	     * linalg/triangular    in 110.26 seconds
ERROR: LoadError: LoadError: mismatch of non-finite elements: 
  a = Inf
  0.0 = 0.0
 in anonymous at task.jl:1403
while loading /tmp/julia/share/julia/test/linalg/pinv.jl, in expression starting on line 294
while loading /tmp/julia/share/julia/test/runtests.jl, in expression starting on line 5
	From worker 3:	     * linalg/pinv         
```

**Comment by Fedster** [comment]
918ee65 works for me on OSX 10.10.4, 64bit CPU:

git fetch && git merge origin
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From git://github.com/JuliaLang/julia
   378ab7c..918ee65  master     -> origin/master
 * [new branch]      omm/meta-gensym -> origin/omm/meta-gensym
Updating 378ab7c..918ee65
Fast-forward
 src/codegen.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

make testall
    CC src/jltypes.o
    CC src/gf.o
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/codegen.o
    CC src/disasm.o
    CC src/debuginfo.o
    CC src/interpreter.o
    CC src/alloc.o
    CC src/dlload.o
    CC src/sys.o
    CC src/init.o
    CC src/task.o
    CC src/array.o
    CC src/dump.o
    CC src/toplevel.o
    CC src/jl_uv.o
    CC src/jlapi.o
    CC src/profile.o
    CC src/llvm-simdloop.o
    CC src/simplevector.o
    CC src/gc.o
    LINK usr/lib/libjulia.dylib
    CC ui/repl.o
    LINK usr/bin/julia
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/fenv_constants.jl
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
    JULIA usr/lib/julia/inference0.o
essentials.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
abstractarray.jl
array.jl
hashing.jl
nofloat_hashing.jl
functors.jl
reduce.jl
intset.jl
dict.jl
iterator.jl
inference.jl
    LINK usr/lib/julia/inference0.dylib
    JULIA usr/lib/julia/inference.o
essentials.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
abstractarray.jl
array.jl
hashing.jl
nofloat_hashing.jl
functors.jl
reduce.jl
intset.jl
dict.jl
iterator.jl
inference.jl
    LINK usr/lib/julia/inference.dylib
    JULIA usr/lib/julia/sys.o
exports.jl
essentials.jl
base.jl
reflection.jl
build_h.jl
version_git.jl
c.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
refpointer.jl
functors.jl
abstractarray.jl
subarray.jl
array.jl
docs/bootstrap.jl
hashing.jl
rounding.jl
float.jl
complex.jl
rational.jl
abstractarraymath.jl
arraymath.jl
simdloop.jl
reduce.jl
bitarray.jl
intset.jl
dict.jl
set.jl
iterator.jl
osutils.jl
utferror.jl
utftypes.jl
utfcheck.jl
char.jl
ascii.jl
utf8.jl
utf16.jl
utf32.jl
iobuffer.jl
string.jl
utf8proc.jl
regex.jl
pcre.jl
base64.jl
io.jl
iostream.jl
libc.jl
libdl.jl
env.jl
path.jl
intfuncs.jl
nullable.jl
task.jl
lock.jl
show.jl
stream.jl
uv_constants.jl
socket.jl
stat.jl
fs.jl
process.jl
multimedia.jl
grisu.jl
file.jl
methodshow.jl
floatfuncs.jl
math.jl
float16.jl
cartesian.jl
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
version.jl
gmp.jl
mpfr.jl
combinatorics.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
meta.jl
Enums.jl
serialize.jl
multi.jl
managers.jl
loading.jl
poll.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
i18n.jl
help.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
markdown/Markdown.jl
docs/Docs.jl
util.jl
linalg.jl
broadcast.jl
statistics.jl
sparse.jl
fftw.jl
dsp.jl
sysinfo.jl
irrationals.jl
quadgk.jl
fastmath.jl
pkg.jl
profile.jl
Dates.jl
deprecated.jl
docs/basedocs.jl
precompile.jl
    LINK usr/lib/julia/sys.dylib
    CC test/libccalltest.dylib
cp /usr/local/julia/usr/lib/julia/sys.dylib local.dylib && /usr/local/julia/usr/bin/julia -J local.dylib -e 'true' && rm local.dylib
    JULIA test/all
	From worker 5:	     * linalg4              in  14.28 seconds
	From worker 8:	     * linalg/tridiag       in  18.20 seconds
	From worker 8:	     * linalg/dense         in   4.09 seconds
	From worker 9:	     * linalg/bidiag        in  34.55 seconds
	From worker 8:	     * linalg/pinv          in  14.07 seconds
	From worker 6:	     * linalg/lapack        in  37.17 seconds
	From worker 9:	     * linalg/givens        in   2.69 seconds
	From worker 4:	     * linalg3              in  37.33 seconds
	From worker 4:	     * linalg/generic       in   3.24 seconds
	From worker 5:	     * linalg/diagonal      in  32.98 seconds
	From worker 3:	     * linalg2              in  51.58 seconds
	From worker 3:	     * keywordargs          in   1.77 seconds
	From worker 9:	     * linalg/symmetric     in  18.41 seconds
	From worker 4:	     * linalg/arnoldi       in  18.31 seconds
	From worker 5:	     * core                 in  18.48 seconds
	From worker 5:	     * dict                 in  12.40 seconds
	From worker 9:	     * strings              in  23.37 seconds
	From worker 9:	     * remote               in   0.52 seconds
	From worker 6:	     * linalg/lu            in  42.50 seconds
	From worker 6:	     * staged               in   0.87 seconds
	From worker 9:	     * iobuffer             in   1.56 seconds
	From worker 8:	     * linalg/cholesky      in  44.98 seconds
	From worker 9:	     * tuple                in   1.32 seconds
	From worker 5:	     * hashing              in   6.29 seconds
	From worker 9:	     * reduce               in   4.32 seconds
	From worker 9:	     * random               in  14.12 seconds
	From worker 5:	     * reducedim            in  19.38 seconds
	From worker 5:	     * intfuncs             in   1.08 seconds
	From worker 5:	     * simdloop             in   1.46 seconds
	From worker 2:	     * linalg1              in 109.09 seconds
	From worker 5:	     * blas                 in   3.82 seconds
	From worker 9:	     * abstractarray        in  13.98 seconds
	From worker 9:	     * copy                 in   1.45 seconds
	From worker 4:	     * dates                in  59.63 seconds
	From worker 6:	     * arrayops             in  38.51 seconds
	From worker 6:	     * functional           in   1.30 seconds
	From worker 6:	     * operators            in   0.21 seconds
	From worker 4:	     * fastmath             in   4.02 seconds
	From worker 6:	     * path                 in   2.36 seconds
	From worker 3:	     * numbers              in  70.15 seconds
	From worker 4:	     * ccall                in   1.84 seconds
	From worker 3:	     * bigint               in   3.17 seconds
	From worker 7:	     * linalg/triangular    in 127.53 seconds
	From worker 6:	     * unicode              in   5.33 seconds
	From worker 6:	     * backtrace            in   0.06 seconds
	From worker 9:	     * math                 in  13.16 seconds
	From worker 7:	     * spawn                      [stdio passthrough ok]
	From worker 6:	     * priorityqueue        in   1.51 seconds
	From worker 6:	     * mmap                 in   5.02 seconds
	From worker 7:	 in   8.03 seconds
	From worker 6:	     * version              in   1.85 seconds
	From worker 6:	     * pollfd               in   2.80 seconds
	From worker 3:	     * statistics           in  12.87 seconds
	From worker 9:	     * file                 in  10.40 seconds
	From worker 7:	     * resolve              in   5.61 seconds
	From worker 7:	     * socket               in   1.79 seconds
	From worker 7:	     * floatapprox          in   0.45 seconds
	From worker 9:	     * complex              in   3.50 seconds
The following 'Returned code...' warnings indicate normal behavior:
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
Warning: Returned code may not match what actually runs.
	From worker 6:	     * mpfr                 in   5.57 seconds
	From worker 9:	     * reflection           in   1.69 seconds
	From worker 6:	     * regex                in   0.79 seconds
	From worker 9:	     * float16              in   1.35 seconds
	From worker 9:	     * sysinfo              in   1.74 seconds
	From worker 6:	     * combinatorics        in   3.07 seconds
	From worker 9:	     * rounding             in   0.97 seconds
	From worker 9:	     * mod2pi               in   0.17 seconds
	From worker 9:	     * euler                in   1.85 seconds
	From worker 3:	     * broadcast            in  12.22 seconds
	From worker 9:	     * show                 in   2.97 seconds
	From worker 4:	     * sorting              in  31.51 seconds
	From worker 3:	     * lineedit             in   4.19 seconds
	From worker 9:	     * replcompletions      in   3.70 seconds
	From worker 9:	     * sets                 in   3.19 seconds
	From worker 9:	     * test                 in   0.32 seconds
	From worker 9:	     * goto                 in   0.05 seconds
	From worker 9:	     * llvmcall             in   0.08 seconds
	From worker 7:	     * readdlm              in  18.33 seconds
	From worker 7:	     * nullable             in   2.49 seconds
	From worker 4:	     * repl                 in   8.47 seconds
	From worker 7:	     * meta                 in   0.27 seconds
	From worker 7:	     * libgit2              in   0.03 seconds
	From worker 3:	     * replutil             in  10.44 seconds
	From worker 9:	     * grisu                in   6.52 seconds
	From worker 9:	     * base64               in   0.36 seconds
	From worker 4:	     * profile              in   4.59 seconds
	From worker 9:	     * parser               in   0.59 seconds
	From worker 7:	     * docs                 in   4.67 seconds
	From worker 9:	     * functors             in   0.62 seconds
	From worker 7:	     * char                 in   0.96 seconds
	From worker 3:	     * markdown             in   4.88 seconds
	From worker 4:	     * serialize            in   5.23 seconds
	From worker 4:	     * i18n                 in   0.04 seconds
	From worker 4:	     * workspace            in   1.46 seconds
	From worker 4:	     * libdl                in   2.28 seconds
	From worker 7:	     * enums                in   8.61 seconds
	From worker 2:	     * sparse               in  72.86 seconds
	From worker 4:	     * fft                  in   5.34 seconds
	From worker 7:	     * dsp                  in   7.73 seconds
	From worker 9:	     * misc                 in  23.33 seconds
	From worker 5:	     * bitarray             in  84.26 seconds
	From worker 6:	     * ranges               in  52.64 seconds
	From worker 2:	     * examples             in  25.36 seconds
	From worker 3:	     * cmdlineargs          in  41.75 seconds
	From worker 8:	     * subarray             in 149.58 seconds
	From worker 4:	     * parallel             in  61.68 seconds
    SUCCESS

**Comment by tkelman** [comment]
huh, no warnings on osx apparently. the 64 bit linux travis build fails because of the `not a recognized processor` warnings on startup

**Comment by ScottPJones** [comment]
OS X has been fine for me since you fixed the `globalvars` problem.

**Comment by vtjnash** [comment]
fixed now. i'm not really sure why the problem didn't show up on OS X, could be a clang vs gcc difference. i tried testing on both platforms, but apparently picked the wrong combination of versions to find this locally initially.
