### ISSUE TITLE
error 4 in libjulia.so

### ISSUE THREAD

**Issue by afadli** [JuliaLang/julia#12067]
M machine keep crashing, I checked the syslog and found : 
17:06:58 julia kernel: [24186.322519] julia-release[105511]: segfault at 18 ip 00007fd24b55c920 sp 00007ffc1891b260 error 4 in libjulia.so[7fd24b0f8000+c5a000]

any idea?

**Comment by ihnorton** [comment]
![image](https://cloud.githubusercontent.com/assets/327706/8573526/0887316e-2560-11e5-9d99-7ed35935abad.png)


versioninfo? machine info?
(is this julia.mit.edu?)

**Comment by afadli** [comment]
![scared](https://cloud.githubusercontent.com/assets/10465452/8574054/aa62c050-2562-11e5-8597-76d06e30767e.jpg)

Julia Version 0.4.0-dev+5779
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7- 8850  @ 2.00GHz
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by ihnorton** [comment]
Looks like julia.mit to me. It's a known issue and there are ongoing discussions with IT.
