### ISSUE TITLE
record GenSym nodes' types into lambda

### ISSUE THREAD

**Issue by hongborong** [JuliaLang/julia#12073]
In the latest Julia, there are often GenSym nodes. They seem to be local vars generated during type inference. However, their types are not entered into lambda's local var list. I have to scan the whole AST once to find their definitions in order to know their types. This is in contrast with other local vars. It would be great if their types are directly recorded in lambda after type inference. Thanks.

**Comment by vtjnash** [comment]
it's already there, they just got their own array. since they are known (a priori) to be locals, they didn't need nearly as much metadata (just the list of types)

**Comment by hongborong** [comment]
Thanks! You are right. lambda args[2][4] contains GenSym's types.
