### ISSUE TITLE
Wrong assertion about negative size

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12089]
```julia
type A{K, N1}
    sz::NTuple{N1, Int}
    A(sz::NTuple{N1, Int}) = new(sz)
end
A{-1, 1}((1,))
```

Now raise an error.

Introduced by https://github.com/JuliaLang/julia/pull/11996

**Comment by stevengj** [comment]
Yup, it gives `ERROR: size or dimension is negative: -1`, which makes no sense here.

cc: @ScottPJones

**Comment by ScottPJones** [comment]
Ugh!  My first bug introduced :sad:  I'll start looking at it.

**Comment by ScottPJones** [comment]
The bug isn't really mine after all, the parameter array is incorrect at that point.
To demonstrate, try A{"foobar",1}((1,))

**Comment by ScottPJones** [comment]
Or maybe that's another bug in type handling?

**Comment by mbauman** [comment]
Strings can't be used as type parameters, since they're not `isbits`.

**Comment by stevengj** [comment]
Maybe should have a regression test?
