### ISSUE TITLE
Problem compiling on ARM

### ISSUE THREAD

**Issue by skoranne** [JuliaLang/julia#12082]
```
/usr/bin/ld: /wv/skoranne/OSS_DOWNLOADS/julia/usr/lib/julia/inference0.so: No symbol version section for versioned symbol `jl_sym#@boundscheck66'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by pao** [comment]
@skoranne, could you please tell us more about the particular ARM platform you are using?

**Comment by yuyichao** [comment]
I got the same error while cross compiling with `arm-linux-gnueabihf` `4.9.2` and `qemu-arm`. 

`JULIA_CPU_TARGET=cortex-a9`
`CFLAGS="-march=armv7-a -mtune=cortex-a9 -mfloat-abi=hard -mfpu=neon -O2 -pipe -fstack-protector --param=ssp-buffer-size=4"`

LLVM version `3.6.2`

**Comment by yuyichao** [comment]
I actually got a segfault after adding `--output-bc` to the command line ...

**Comment by yuyichao** [comment]
Not sure why but it appears that non of the global symbols appears in the `*.o` file

**Comment by skoranne** [comment]
I am trying to compile Julia on an nVidia Jetson board. It was compiling file few days back, but I did an update and now am unable to build.

I tried removing the -fvisibility option from Makefile, but does not help.

**Comment by yuyichao** [comment]
@skoranne What was the commit you successfully compiled last time?

**Comment by skoranne** [comment]
I dont know exactly, but it was last week.

Now I am trying to compile 'release-0.3',

**Comment by yuyichao** [comment]
Bisect result

```
yyc2:~/projects/julia/arm-build
yuyichao% git bisect bad 
050eedb5ff0a072cb05e91ac6e827e8322ba2c2b is the first bad commit
commit 050eedb5ff0a072cb05e91ac6e827e8322ba2c2b
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Wed Jul 8 02:40:11 2015 +0000

    copy module before running llvm codegen output passes (fix #11878)
    
    llvm may modify the Module during codegen output (as was observed to happen on ARM), so it is better to run the code emission passes on a copy rather than the actual shadow module

:040000 040000 bd2f19c80d24200cfa6e2ea6d4016cbcf0370fb5 bac98b71dddc211eac93d68802ced2aec3817059 M        src
yyc2:~/projects/julia/arm-build
yuyichao% git bisect log 
git bisect start
# bad: [9c2a138617854e7f492e5fd61fe1611ce0e69c8f] Test the field of the exceptions again.
git bisect bad 9c2a138617854e7f492e5fd61fe1611ce0e69c8f
# good: [8eaf17706842610fae81f4a9f9723725cb707b2f] Merge pull request #11969 from JuliaLang/yyc/ntuple-inst
git bisect good 8eaf17706842610fae81f4a9f9723725cb707b2f
# good: [1801a4133cce5e092c85ca7ee9054fb52b54b3ee] Merge pull request #12036 from julian-gehring/test-mean
git bisect good 1801a4133cce5e092c85ca7ee9054fb52b54b3ee
# bad: [896cadf4555efcc42478780bf30fcc1376d879fa] use std::string instead of StringRef to avoid C++ auto-finalizer on llvm3.3 getHostCPUName() result
git bisect bad 896cadf4555efcc42478780bf30fcc1376d879fa
# good: [f0b2c17d9ce4f7565bc3864e5ad0d1cdc20d750f] Merge pull request #11280 from JuliaLang/jq/mmap
git bisect good f0b2c17d9ce4f7565bc3864e5ad0d1cdc20d750f
# good: [584308d93d6398c2c3c24e1b160039cca8e61b0e] Remove section on GCE.
git bisect good 584308d93d6398c2c3c24e1b160039cca8e61b0e
# bad: [050eedb5ff0a072cb05e91ac6e827e8322ba2c2b] copy module before running llvm codegen output passes (fix #11878)
git bisect bad 050eedb5ff0a072cb05e91ac6e827e8322ba2c2b
# first bad commit: [050eedb5ff0a072cb05e91ac6e827e8322ba2c2b] copy module before running llvm codegen output passes (fix #11878)
```

And the commit does look suspicious. @vtjnash

**Comment by ViralBShah** [comment]
Do see the discussion in https://github.com/JuliaLang/julia/commit/378ab7ce3d627cdb1b44ac61220079113df57192

**Comment by yuyichao** [comment]
@ViralBShah Yes I knew about that. However, I think that breakage is more about LLVM 3.3 (which AFAICT doesn't support JIT on ARM) and the symptom is also very different. For all of the bad commit I've got, the errors are exactly the same (missing symbols during linking) and the error is still there on master.

**Comment by skoranne** [comment]
g++  -shared -fPIC -L/wv/skoranne/OSS_DOWNLOADS/julia/usr/lib/julia -L/wv/skoranne/OSS_DOWNLOADS/julia/usr/lib -L/wv/skoranne/OSS_DOWNLOADS/julia/usr/lib -o /wv/skoranne/OSS_DOWNLOADS/julia/usr/lib/julia/inference0.so /wv/skoranne/OSS_DOWNLOADS/julia/usr/lib/julia/inference0.o $([ Linux = Darwin ] && echo '' -Wl,-undefined,dynamic_lookup || echo '' -Wl,--unresolved-symbols,ignore-all ) $([ Linux = WINNT ] && echo '' -ljulia -lssp)
/usr/bin/ld: /wv/skoranne/OSS_DOWNLOADS/julia/usr/lib/julia/inference0.so: No symbol version section for versioned symbol `jl_sym#@boundscheck66'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status

**Comment by ihnorton** [comment]
With llvm assertions, passing `--output-bc` leads to:

```
inference.jl
@"+Bool17" = internal global %jl_value_t* null
Unknown constant!
UNREACHABLE executed at /home/user/dev/julia/deps/llvm-3.6.1/lib/Bitcode/Writer/BitcodeWriter.cpp:1227!
```

My guess is that there is some fixup required that our FunctionMover does but CloneFunction does not. I don't understand why this would be ARM-specific though, unless the linking rules are different.

(I thought maybe this was just an LLVM 3.6 issue, but my 3.6 build works fine on x86_64/linux)

**Comment by ihnorton** [comment]
correction: CloneModule, which we are now using since 050eedb5 (as identified by @yuyichao... the parent commit works fine for me too).

**Comment by yuyichao** [comment]
@ihnorton Thanks. (With `qemu-arm` it's very hard to debug a segfault....)

**Comment by yuyichao** [comment]
The following patch as suggested by @Keno solves the linking issue of `inference0.so` for me.

```diff
From 971762de1380199a688586ed5273a205e815b359 Mon Sep 17 00:00:00 2001
From: Yichao Yu <yyc1992@gmail.com>
Date: Sun, 12 Jul 2015 07:57:55 -0400
Subject: [PATCH] llvm-gv-array

---
 src/codegen.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/codegen.cpp b/src/codegen.cpp
index 82e914a..04c114f 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -414,8 +414,8 @@ void jl_dump_bitcode(char *fname)
     raw_fd_ostream OS(fname, err);
 #endif
 #ifdef USE_MCJIT
+    jl_gen_llvm_gv_array(shadow_module);
     Module *bitcode = CloneModule(shadow_module);
-    jl_gen_llvm_gv_array(bitcode);
     WriteBitcodeToFile(bitcode, OS);
 #else
     Module *bitcode = CloneModule(jl_Module);
@@ -508,10 +508,10 @@ void jl_dump_objfile(char *fname, int jit_model, const char *sysimg_data, size_t
     shadow_module->setTargetTriple(TM->getTargetTriple().str());
     shadow_module->setDataLayout(TM->getDataLayout()->getStringRepresentation());
     #endif
+    jl_gen_llvm_gv_array(shadow_module);
     Module *objfile = CloneModule(shadow_module);
     if (sysimg_data)
         jl_sysimg_to_llvm(objfile, sysimg_data, sysimg_len);
-    jl_gen_llvm_gv_array(objfile);
     PM.run(*objfile);
 #else
     Module *objfile = CloneModule(jl_Module);
-- 
2.4.5
```

**Comment by yuyichao** [comment]
Submitted as PR https://github.com/JuliaLang/julia/pull/12125
