### ISSUE TITLE
Can't load PyPlot in Julia  0.4.0-dev+5851 

### ISSUE THREAD

**Issue by dbrowne** [JuliaLang/julia#12081]
julia> using PyPlot
Warning: New definition 
    call(Type{PyCall.PyDict}, Base.Associative{#K<:Any, Any}) at /apps/infrafs1/dbrowne/.julia/v0.4/PyCall/src/conversions.jl:464
is ambiguous with: 
    call(Type{PyCall.PyDict}, Base.Associative{Any, #V<:Any}) at /apps/infrafs1/dbrowne/.julia/v0.4/PyCall/src/conversions.jl:463.
To fix, define 
    call(Type{PyCall.PyDict}, Base.Associative{Any, Any})
before the new definition.
ERROR: LoadError: LoadError: TypeError: apply_type: in first parameter of NTuple, expected Int64, got Type{Type{T}}
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /apps/infrafs1/dbrowne/.julia/v0.4/PyCall/src/PyCall.jl, in expression starting on line 381
while loading /apps/infrafs1/dbrowne/.julia/v0.4/PyPlot/src/PyPlot.jl, in expression starting on line 3

Any Suggestions?

**Comment by yuyichao** [comment]
It's a bug in `PyCall.jl`.

Already fixed by https://github.com/stevengj/PyCall.jl/pull/157
