### ISSUE TITLE
Module documentation

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#12106]
```julia
julia> begin
       module Foo
       end
       end
ERROR: syntax: module expression not at top level
```
The error message has improved, but this still prevents us from documenting modules:
```julia
julia> "foo"
       module Foo end
ERROR: syntax: module expression not at top level
```

**Comment by one-more-minute** [comment]
Actually, thinking about it – we might be able to do that by emitting

```julia
"foo"
module Foo end
```
to 
```julia
module Foo
"foo"
Foo
end
```
in which case it's fixable from within the doc system.

**Comment by MichaelHatherly** [comment]
This is probably it eca6d16fde3b88a33392ac0e772bb2db723fd4de.

Solved by wrapping the module in a ``Expr(:toplevel)``?

**Comment by MichaelHatherly** [comment]
Also, rewriting as an internal docstring seems best, otherwise toplevel modules will add their docs to ``Main.__META__`` won't they?

**Comment by one-more-minute** [comment]
Yeah that's right – it doesn't make a functional difference right now, but I'm assuming that once we have static compilation it'll make sense to have modules contain their own docs.

**Comment by timholy** [comment]
I'm settling into a pattern of writing an expansive README, but then wanting a quick API summary when I type `?MyModule`. The following pattern works:
```jl
module MyModule

# stuff

end

@doc """
The exported API of MyModule is:

- `foo`: does great stuff
- `bar`: even more awesome

Each of these has its own help available, e.g., `?foo`.
""" -> MyModule
```
However, if I precompile MyModule, then it goes back to showing the README when I type `?MyModule`.

I'm going to add a "precompile" tag to this issue, since it works if you don't precompile.

**Comment by MichaelHatherly** [comment]
Putting the ``@doc`` after the module will add it to the ``.__META__`` of ``MyModule``'s parent module. Placing the doc above the module expression or inside will add it to ``MyModule.__META__`` and does work fine with precompilation:

```julia
"..."
module MyModule

end
```

and

```julia
module MyModule

"..."
MyModule

end
```

**Comment by timholy** [comment]
But if you want to support 0.3, the `@doc "..." -> module MyModule ...` version doesn't work.

I think I have a version that should work, but I'm struggling with some Docile/Lexicon issues. I'll post there.

**Comment by jakebolewski** [comment]
Is this fixed?

**Comment by MichaelHatherly** [comment]
Modules and baremodules are documentable, so this can be closed now I think.
