### ISSUE TITLE
max() on sparse matrices

### ISSUE THREAD

**Issue by nassarhuda** [JuliaLang/julia#12118]
max() on 2 sparse matrices returns an Array{Float64,Int64}, can this be changed to return a sparse matrix as well?
```
julia> A = sprand(5,5,1/5)
5x5 sparse matrix with 2 Float64 entries:
	[4, 2]  =  0.502774
	[5, 2]  =  0.224851

julia> B = sprand(5,5,1/5)
5x5 sparse matrix with 6 Float64 entries:
	[1, 1]  =  0.359682
	[5, 1]  =  0.608841
	[4, 2]  =  0.989943
	[2, 3]  =  0.671907
	[5, 4]  =  0.34389
	[4, 5]  =  0.0793254

julia> C = max(A,B)
5x5 Array{Float64,2}:
 0.359682  0.0       0.0       0.0      0.0      
 0.0       0.0       0.671907  0.0      0.0      
 0.0       0.0       0.0       0.0      0.0      
 0.0       0.989943  0.0       0.0      0.0793254
 0.608841  0.224851  0.0       0.34389  0.0    
```

**Comment by tkelman** [comment]
Makes sense to me. Best to post a cross-reference link when you post both an issue and a related mailing list thread, here https://groups.google.com/forum/#!topic/julia-users/Qh-7q0U5etA

Looks like `@which max(A,B)` is falling back to the [`AbstractArray` definition](https://github.com/JuliaLang/julia/blob/17bebe5f6ada25dfae894a73cabd3e618ac5b9e8/base/operators.jl#L379-L382) from [`@vectorize_2arg`](https://github.com/JuliaLang/julia/blob/17bebe5f6ada25dfae894a73cabd3e618ac5b9e8/base/math.jl#L176). Could probably get away with adding `max` and `min` to the specialized sparse broadcast loop [here](https://github.com/JuliaLang/julia/blob/17bebe5f6ada25dfae894a73cabd3e618ac5b9e8/base/sparse/sparsematrix.jl#L869-L883).
