### ISSUE TITLE
Mac Os X Yosemite 10.10.4 build problem: julia/deps/libgit2/build/clang: No such file or directory

### ISSUE THREAD

**Issue by dbrowne** [JuliaLang/julia#12123]
Julia 0.4.0.-dev
hard1:julia djb$ make
[  0%] Building C object CMakeFiles/git2.dir/src/annotated_commit.c.o
make[4]: /Users/djb/GRepository/julia/deps/libgit2/build/clang: No such file or directory
make[4]: *** [CMakeFiles/git2.dir/src/annotated_commit.c.o] Error 1
make[3]: *** [CMakeFiles/git2.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [libgit2/build/libgit2.dylib] Error 2
make: *** [julia-deps] Error 2

Any Suggestions?

**Comment by vtjnash** [comment]
deleting deps/libgit2/build folder and restarting the build has worked for me.

also, fwiw, if you have a macports-installed pkg-config at `/opt/local/bin/pkg-config` or fink-installed pkg-config at `/sw/bin/pkg-config`, cmake will find it (even if it is not on your PATH) and will mis-configure the build and cause it to fail. (if you have a homebrew-installed pkg-config in `/usr/local/bin/pkg-config`), then your build should work, but the resulting binaries will not be redistributable and will potentially need to be `make distclean` wiped and rebuilt any time you run `brew upgrade`, just like after any OS upgrade).

**Comment by dbrowne** [comment]
Problem resolved. Thank you!
