### ISSUE TITLE
disallow generated functions in local scope

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12135]
for example, the following currently returns undefined answers (sometimes even correct ones):
```julia
julia> function f()
         @generated function g{T}(x::T)
           quote $T end
         end
       end
f (generic function with 1 method)
```

**Comment by JeffBezanson** [comment]
Example (run immediately after defining `f`):

```
julia> f()
g (generic function with 1 method)

julia> f()(1)
ERROR: UndefVarError: T not defined
 in g at none:3
```

**Comment by vtjnash** [comment]
this particular error if you run `f()` twice before running (and thus compiling, `g()`). it is the same as https://github.com/JuliaLang/julia/pull/12117#issuecomment-120741679

**Comment by yuyichao** [comment]
Is this a similar issue with https://github.com/JuliaLang/julia/pull/11883 ?

**Comment by JeffBezanson** [comment]
I think this actually works now, though it's not recommended. Please reopen if more failing cases are found.
