### ISSUE TITLE
mpfr does not build on OS X

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12142]
I'm building the current master branch on OS X 10.10.4 (Darwin 14.4.0). Building `mpfr` fails with the error message
```
install_name_tool -id @rpath/libmpfr.dylib /Users/eschnett/src/julia/usr/lib/libmpfr.dylib
error: install_name_tool: can't open file: /Users/eschnett/src/julia/usr/lib/libmpfr.dylib (No such file or directory)
```
Indeed there is no file `mpfr.dylib`; instead, a file `mpfr.a` was created. This looks wrong, because mpfr's configure log indicates it was called with
```
./configure --prefix=/Users/eschnett/src/julia/usr --build=x86_64-apple-darwin14.4.0 --libdir=/Users/eschnett/src/julia/usr/lib F77=gfortran -mmacosx-version-min=10.7 -m64 CC=clang -stdlib=libc++ -mmacosx-version-min=10.7 -m64  CXX=clang++ -stdlib=libc++ -mmacosx-version-min=10.7 -m64  --with-gmp-include=/Users/eschnett/src/julia/usr/include --with-gmp-lib=/Users/eschnett/src/julia/usr/lib --host=none-unknown-linux F77= --enable-shared --disable-static
```
so that there should be a shared but no static library.

I'm using MacPorts, so that `clang` and `clang++` are provided by Macports and have version 3.6.1.

**Comment by tkelman** [comment]
`--host=none-unknown-linux` doesn't look right, I think that gets guessed based on `$(CC) -dumpmachine` somewhere in `Make.inc`

**Comment by eschnett** [comment]
Haha, yes, that may be it (still testing). I'm setting `SANITIZE=0` in `Make.user` (so that I can easily change the line to `SANITIZE=1`). This triggers these lines in `deps/Makefile`:
```
ifneq ($(SANITIZE),)
# Force generic C build
MPFR_OPTS += --host=none-unknown-linux
endif
```
I think the condition should be `ifeq ($(SANITIZE),1)` instead.

GMP seems is similarly misconfigured.

**Comment by Keno** [comment]
We're a little bit inconsistent about between variables about whether any value enables it or just `1`. For that reason I usually just comment out the lines I don't use.

**Comment by eschnett** [comment]
The makefiles contain several suggestions of the kind `Try setting SANITIZE=0`...

**Comment by Keno** [comment]
Fair enough!
