### ISSUE TITLE
Build failing with LLVM 3.6.1

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12155]
After the recent ARM fix, I ran into this one. Is it an LLVM version issue? We use LLVM 3.6.1 by default on ARM.

````
In file included from codegen.cpp:517:0:
cgutils.cpp: In function 'void jl_dump_shadow(char*, int, const char*, size_t, bool)':
cgutils.cpp:495:30: error: 'class llvm::TargetMachine' has no member named 'getDataLayout'
     clone->setDataLayout(TM->getDataLayout()->getStringRepresentation());
                              ^
codegen.cpp: At global scope:
codegen.cpp:353:18: warning: 'show_execution_point_func' defined but not used [-Wunused-variable]
 static Function *show_execution_point_func;
                  ^
````

**Comment by yuyichao** [comment]
Which version is this? I built bbe8dfc yesterday with no problem.

**Comment by ViralBShah** [comment]
I am using master as of right now.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/commit/0b6dc692ed27e3653a027a474260f1a4743b56f9 @vtjnash ?

**Comment by yuyichao** [comment]
I think it's not ARM specific. I see the same error on LLVM 3.6.1 on x86_64 as well.

**Comment by vtjnash** [comment]
ah, i see a lost a `#ifdef LLVM37` around that code in the code movement
