### ISSUE TITLE
`Pkg.init` fails for a package directory on a network drive.

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#12166]
I downloaded a Win64 nightly this morning and installed it. I was getting complaints during `Pkg.update` so I deleted my `.julia/v0.4` directory. I then tried `Pkg.add("SomePackage")` and got:

```
WARNING: Note: on Windows, creating file symlinks requires Administrator privileges.
ERROR (unhandled task failure): symlink: operation not permitted (EPERM)
 in symlink at fs.jl:167
 in mkcachedir at pkg/cache.jl:17
 in prefetch at pkg/cache.jl:33
 in resolve at pkg/entry.jl:427
 in edit at pkg/entry.jl:26
 in anonymous at task.jl:365
ERROR: symlink: operation not permitted (EPERM)
 in wait at task.jl:61
 in sync_end at task.jl:336
 in add at pkg/entry.jl:344
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
```

Has anyone else seen this? Since I couldn't find a relevant issue already filed, I'm hopeful that this is due to some local borkage on my machine.

**Comment by tkelman** [comment]
what version of windows?

**Comment by twadleigh** [comment]
Windows 7 Professional SP1

**Comment by tkelman** [comment]
and latest win64 nightly of Julia, so b2528a6e66 ?

**Comment by tkelman** [comment]
Do you have a `.julia/.cache` directory present? I forget which direction the symlink (should be a directory junction here) goes in.

**Comment by twadleigh** [comment]
b2528a6 is correct. There was no .cache directory before, but after and initial `Pkg.update`, there is now.

**Comment by tkelman** [comment]
Can you make this happen with a repeatable set of steps after moving `.julia` completely out of the way and starting over again from `Pkg.init` (which should get called automatically if you call `Pkg.add` or something else first)

**Comment by twadleigh** [comment]
For me, to recreate it is as simple as:
- delete `.julia` directory in home directory
- `julia> Pkg.add("Images") # or any other package`

It occurred to me today why my situation may be different than others: my home directory lives on a network drive.

**Comment by tkelman** [comment]
Aha, I think that explains it. It might not be possible to create NTFS junctions on some types of network drive. We should harden the fallback behavior for creating `.cache` then.

**Comment by twadleigh** [comment]
Setting `JULIA_PKGDIR` to some place local got me past this issue.

**Comment by tkelman** [comment]
Are you able to rebuild the system image to test things out? How about putting these two lines https://github.com/JuliaLang/julia/blob/e63f8a58ea07314e59daa2e0104b7129f3069464/base/pkg/cache.jl#L25-L26
inside a `try`?
```
    if Dir.isversioned(pwd())
        rootcache = joinpath(realpath(".."), ".cache")
        if !isdir(rootcache)
            mkdir(rootcache)
        end
        try
            symlink(rootcache, cache)
            return
        end
    end
    mkdir(cache)
```

I'm not sure whether failed `symlink` will ever create anything at the desired source location.

**Comment by twadleigh** [comment]
I was able to wrap those lines in a `try` and rebuild the system image. I'm now getting different errors:

```
C:\>julia -J C:/Julia-0.4.0-dev/lib/julia/new_sys.ji
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6093 (2015-07-20 07:55 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4ebdea0 (9 days old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("FixedPointNumbers")
INFO: Initializing package repository U:\.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
WARNING: Note: on Windows, creating file symlinks requires Administrator privileges.
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of FixedPointNumbers from git://github.com/JeffBezanson/FixedPointNumbers.jl.git
INFO: Installing Compat v0.4.10
error: internal error: refs/remotes/origin/OutOfMemoryError is not a valid packed reference!
error: internal error: refs/remotes/origin/cb/bitrand is not a valid packed reference!
error: internal error: refs/remotes/origin/fma is not a valid packed reference!
error: internal error: refs/remotes/origin/jq/dates is not a valid packed reference!
error: internal error: refs/remotes/origin/jq/tryparse is not a valid packed reference!
error: internal error: refs/remotes/origin/jq/tryparse2 is not a valid packed reference!
error: internal error: refs/remotes/origin/kms/eltype is not a valid packed reference!
error: internal error: refs/remotes/origin/master is not a valid packed reference!
error: internal error: refs/remotes/origin/sk/version.sh is not a valid packed reference!
error: internal error: refs/remotes/origin/yyc/doc-macro is not a valid packed reference!
error: internal error: refs/tags/v0.0.1 is not a valid packed reference!
error: internal error: refs/tags/v0.1.0 is not a valid packed reference!
error: internal error: refs/tags/v0.2.0 is not a valid packed reference!
error: internal error: refs/tags/v0.2.1 is not a valid packed reference!
error: internal error: refs/tags/v0.2.10 is not a valid packed reference!
error: internal error: refs/tags/v0.2.11 is not a valid packed reference!
error: internal error: refs/tags/v0.2.12 is not a valid packed reference!
error: internal error: refs/tags/v0.2.3 is not a valid packed reference!
error: internal error: refs/tags/v0.2.7 is not a valid packed reference!
error: internal error: refs/tags/v0.2.8 is not a valid packed reference!
error: internal error: refs/tags/v0.3.0 is not a valid packed reference!
error: internal error: refs/tags/v0.3.1 is not a valid packed reference!
error: internal error: refs/tags/v0.3.2 is not a valid packed reference!
error: internal error: refs/tags/v0.3.4 is not a valid packed reference!
error: internal error: refs/tags/v0.3.5 is not a valid packed reference!
error: internal error: refs/tags/v0.3.6 is not a valid packed reference!
error: internal error: refs/tags/v0.3.7 is not a valid packed reference!
error: internal error: refs/tags/v0.3.8 is not a valid packed reference!
error: internal error: refs/tags/v0.4.0 is not a valid packed reference!
error: internal error: refs/tags/v0.4.1 is not a valid packed reference!
error: internal error: refs/tags/v0.4.10 is not a valid packed reference!
error: internal error: refs/tags/v0.4.2 is not a valid packed reference!
error: internal error: refs/tags/v0.4.3 is not a valid packed reference!
error: internal error: refs/tags/v0.4.4 is not a valid packed reference!
error: internal error: refs/tags/v0.4.5 is not a valid packed reference!
error: internal error: refs/tags/v0.4.6 is not a valid packed reference!
error: internal error: refs/tags/v0.4.7 is not a valid packed reference!
error: internal error: refs/tags/v0.4.8 is not a valid packed reference!
error: internal error: refs/tags/v0.4.9 is not a valid packed reference!
error: internal error: refs/tags/v0.5.0 is not a valid packed reference!
error: Trying to write ref refs/heads/master with nonexistent object 2458d81963e14e44433f73bacdda50c5e3435f25
fatal: Cannot update the ref 'HEAD'.
fatal: The remote end hung up unexpectedly
ERROR: failed process: Process(`git clone -q 'U:\.julia\v0.4\.cache\Compat' Compat`, ProcessExited(128)) [128]
 in yieldto at task.jl:21
 in wait at task.jl:309
 in wait at task.jl:225
 in wait at task.jl:58
 in sync_end at task.jl:336
 in add at pkg/entry.jl:344
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

julia>
```

**Comment by tkelman** [comment]
Oh dear, git itself might just be borked on network drives then. I don't know anywhere near enough about the internals of git to recognize what that error means (@wildart any ideas?), but maybe we just need to document and/or do a better job of detecting when home folders are on a network drive and suggest the local-`JULIA_PKGDIR` workaround somewhere more obvious.

**Comment by twadleigh** [comment]
I gave it a try with 0.3.11. It had similar behavior to the `try`-patched version: `init` succeeds but then git pukes. So this issue is not really a regession.

Personally, the networked home directory thing is rare enough, and the workaround simple enough, that I would consider issuing a more helpful warning/error message sufficient resolution.

A couple questions occur to me:
 1. Might this git issue go away with the move to `libgit2`?
 2. Has there been any thought given to a `julia` config file? Environment variables feel kludgy.

**Comment by tkelman** [comment]
I don't think you're the first person to hit this, but it gets reported once every few months or so. Dunno whether libgit2 is better at handling network drives. Maybe?

> Has there been any thought given to a julia config file? Environment variables feel kludgy.

There's a `juliarc.jl` under `etc/julia` in your Julia installation, is that good enough? There's #2716 but not sure whether we'll be able to standardize on something.

**Comment by twadleigh** [comment]
Yeah, setting the environment variable in `[.]juliarc.jl` is a clean enough solution, I'd say, and #2716 looks like any even cleaner one for down the road.

I'm looking into suggesting a little patch now.

**Comment by twadleigh** [comment]
@tkelman In trying to follow the thread to the neatest, cleanest fix to this problem, I eventually made my way to looking for `statfs` functionality, and bumped into this thread:

https://groups.google.com/forum/#!topic/libuv/p9Ok8Z3qWR8

Has that gone anywhere?

**Comment by wildart** [comment]
Windows link support sucks. So, I guess we could consider a common `.cache` folder for every version of Julia (which is already in place), do not try make cache links inside version package spaces, and reference related to `.julia` directory.

**Comment by tkelman** [comment]
Hah, good hunting. I'm actually not all that deeply familiar with how statfs works, but it was a blocker that I hit when I was trying to build one of the open-source MPI implementations (I forget which one, either openmpi or mpich) with MinGW-w64. I didn't get too far, so I don't have a branch or PR anywhere, no.

**Comment by tkelman** [comment]
Should be fixed by https://github.com/JuliaLang/julia/pull/14026. Leave a comment or open a new issue if not.
