### ISSUE TITLE
pyplot problems in 0.4.0-dev+5990 (2015-07-15 09:08 UTC)

### ISSUE THREAD

**Issue by dbrowne** [JuliaLang/julia#12164]
rebuilt and updated everything and getting the following error:
julia> using PyPlot

Warning: error initializing module PyPlot:
PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x00007f7e34827e60), val=PyCall.PyObject(o=0x0000000004ecba70), traceback=PyCall.PyObject(o=0x0000000000000000))
LoadError: UndefVarError: pltm not defined
while loading In[6], in expression starting on line 4

 in plot at /apps/infrafs1/dbrowne/.julia/v0.4/PyPlot/src/PyPlot.jl:368

**Comment by jiahao** [comment]
This is unlikely to be a Julia problem. Please report it at the [PyPlot.jl](https://github.com/stevengj/PyPlot.jl) repo.

**Comment by yuyichao** [comment]
Also just to be sure, you have matplotlib installed for the python version you are using right?

**Comment by dbrowne** [comment]
My issue. was using the wrong python env. Closing the ticket
