### ISSUE TITLE
Multiple Julia installs confuses the package Manager

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#12175]
First I'm like huh?, them I'm like oh oh.  I think the issue is that for various reasons the Julia package manager executes shell commands, and it can happen that if one Julia is set in a shell temporarily using `export PATH=`*something not the default*, then the *env* **PATH** variable is not carried over to forked-exec'd shells in which the package manager executes commands, What results is (see below) Julia version X (in this case 0.3.8) Pkg using Julia otherwise default version Y (in this case 0.4) which leads to horrible errors. 

In my case, I use Julia dev (compiled from source) and installed in /usr/local/bin by default, and only occasionally use packaged Julia in /Applications.  This is a little bit out of the ordinary, but not completely unexpected.

    bizarro% julia
                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "help()" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.3.8 (2015-04-30 23:40 UTC)
     _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
    |__/                   |  x86_64-apple-darwin13.4.0

    julia> import Mocha;
    ^CERROR: interrupt
    while loading /Users/jeffw/.julia/v0.4/Mocha/src/Logging.jl, in expression starting on line 1
    while loading /Users/jeffw/.julia/v0.4/Mocha/src/logging.jl, in expression starting on line 1
    while loading /Users/jeffw/.julia/v0.4/Mocha/src/Mocha.jl, in expression starting on line 3

    julia> 

    bizarro% which julia
    /Applications/Julia-0.3.8.app/Contents/Resources/julia/bin/julia

**Comment by waTeim** [comment]
NVM  Rechecked apparently fixed by version 0.3.10

**Comment by tkelman** [comment]
Huh. I'm surprised by this, since I wouldn't think 0.3.8 and 0.3.10 would be substantially different here.

**Comment by waTeim** [comment]
Me neither so kinda tested 3.10 as an after thought.  Was surprised.  May was a side effect of another change.  Might do to put in  a 3.10 (or 3.9??) list of fixes.

**Comment by tkelman** [comment]
Would have to figure out what was actually responsible out of https://github.com/JuliaLang/julia/commits/release-0.3 - are you sure you didn't have some customization in your juliarc for 0.3.8 or something?

**Comment by waTeim** [comment]
hmm... here's the contents of my juliarc

    macro q() quit() end

kinda minimal and I use ctrl-D anyway
