### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#12170]
I often write
```julia
for i in length(x)
```
when really I want to write
```julia
for i in 1:length(x)
```
This typo is surprisingly easy to do and hard to spot. Would it be possible to return a warning or an error in the first case?

**Comment by ScottPJones** [comment]
Does Lint.jl catch that?

**Comment by yuyichao** [comment]
See https://github.com/JuliaLang/julia/issues/11769

**Comment by jakebolewski** [comment]
Unfortunately no, numbers are iterable so `for i=length(x)` is perfectly valid.  Lint.jl can't catch it because all Lint can do is look at the AST, and it can't infer the type that length will return.

**Comment by Ken-B** [comment]
For your information, the NEWS section for v0.4 says "Array iteration should generally be written as `for i in eachindex(A) ... end` rather than `for i = 1:length(A) ... end`. (#8432)"

I would think this will fix your typo issue.
