### ISSUE TITLE
conflicts caused by implicit `using Base` and `importall Base.Operators`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#12183]
If a module `M` exports a name that's also exported by `Base`, `using M` leads to the new warning `Warning: both M and Base export "sin"; uses of it in module Main must be qualified`. This makes it very hard to make packages that override Base functions.

One workaround is to use `import M.sin` instead of `using`, however that fails for operators because of the implicit `importall Base.Operators`. You get for example `Warning: ignoring conflicting import of M.+ into Main`.

These warnings are great for usings and imports that are written explicitly, e.g. if you write `import A.x; import B.x`, but they're annoying in the case of the default imports.

Some mitigation ideas:

* Remove the implicit `importall Base.Operators`
* Allow other modules to silently override names brought in by the implicit `using Base`

**Comment by vtjnash** [comment]
ref https://github.com/JuliaLang/julia/issues/8113

**Comment by mauro3** [comment]
Shouldn't it be the case that functions of Base should almost never be overridden? Overriding them silently seems bad.  My vote goes to option one of the mitigation ideas.

**Comment by Sisyphuss** [comment]
3 questions:
1) We made using the same functions drops both. Why we want to override the Base.function now?
2) How does the import M.sin walk around?
3) If Module A imports Module S, Module B imports Module S and Module A, what will happen?

**Comment by mauro3** [comment]
Not sure about answers to you questions. But this issue was resolved by  #12235, I think.

**Comment by Sisyphuss** [comment]
These questions go beyond this issue. Knowing the answers to these questions will help the development in other situations.
