### ISSUE TITLE
BUG: arithmetic with linspace incorrect

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/julia#12195]
Consider:

```
julia> x = linspace(0.01, 0.99, 12)
linspace(0.01,0.99,12)

julia> collect(1 - x)
12-element Array{Float64,1}:
  0.0
 -0.0890909
 -0.178182
 -0.267273
 -0.356364
 -0.445455
 -0.534545
 -0.623636
 -0.712727
 -0.801818
 -0.890909
 -0.98

julia> 1 - collect(x)
12-element Array{Float64,1}:
 0.99
 0.900909
 0.811818
 0.722727
 0.633636
 0.544545
 0.455455
 0.366364
 0.277273
 0.188182
 0.0990909
 0.01
```

**Comment by yuyichao** [comment]
Likely my fault: https://github.com/JuliaLang/julia/pull/11233 although I though I have added tests for all operators I added... Will investigate after a meeting if no one beats me.

**Comment by spencerlyon2** [comment]
I know this conversation has happened already, but I can't seem to find it: why do we have both `LinSpace` and `FloatRange`?

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/pull/9666
