### ISSUE TITLE
add writemime(::IO, ::MIME"text/markdown", x::Markdown.MD) method

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12193]
The latest IJulia master version is capable of sending "text/markdown" output directly to the front-end (which supports displaying it directly).  However, somewhat perversely, the `Markdown.MD` type does not support rendering (via `writemime`) to text/markdown.

(More generally, it would be nice to be able to get Markdown output back from markdown inputs.)

cc: @one-more-minute

**Comment by stevengj** [comment]
Note that this also supports rendering of Markdown with embedded LaTeX equations.

**Comment by MichaelHatherly** [comment]
Getting plain markdown back out can be done with the the ``text/plain`` method of ``writemime``, https://github.com/JuliaLang/julia/blob/7f4c2de4ee7ac6403386b8d67c78826a4db36859/base/markdown/render/plain.jl#L85. Probably would be better to have it be ``text/markdown``, or perhaps have both ``text/markdown`` and ``text/plain`` do the same thing?

**Comment by stevengj** [comment]
`text/markdown` should just call the `text/plain` method for now.  We can make them different if we ever decide to strip out some of the markdown formatting from `text/plain`.
