### ISSUE TITLE
Wrong location for mpfr source

### ISSUE THREAD

**Issue by blaiseli** [JuliaLang/julia#12190]
It seems that available mpfr version has changed in <http://www.mpfr.org/mpfr-current/>
`deps/Versions.make` says version 3.1.2 is wanted, but only 3.1.3 is available, resulting in a failure to build julia from git as of today:
```
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make[2]: *** [mpfr-3.1.2.tar.bz2] Error 22
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

Setting the url to `http://www.mpfr.org/mpfr-$(MPFR_VER)` in `deps/Makefile`seems to solve the problem.

**Comment by tkelman** [comment]
Thanks. We have a mirroring server but it appears to have timed out in the initial try for you. We could probably upgrade MPFR to 3.1.3 painlessly enough, worth testing. For trivial little changes like this, a pull request would be as easy as opening an issue.
