### ISSUE TITLE
missing comma in example given in README.md for rpath

### ISSUE THREAD

**Issue by blaiseli** [JuliaLang/julia#12191]
My build fails with the following error:
```
libtool: link: gfortran -march=native -m64 -shared  -fPIC  -Wl,--whole-archive ./SRC/.libs/libarpacksrc.a ./UTIL/.libs/libarpackutil.a -Wl,--no-whole-archive  -L/home/bli/src/julia/usr/lib -lopenblas  -march=native -m64 -O2 -Wl,-rpath -Wl,-rpath -Wl,/home/bli/src/julia/usr/lib   -Wl,-soname -Wl,libarpack.so.2 -o .libs/libarpack.so.2.0.0
/usr/bin/ld: cannot find /home/bli/src/julia/usr/lib: File format not recognized
collect2: error: ld returned 1 exit status
make[4]: *** [libarpack.la] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [arpack-ng-3.1.5/.libs/libarpack.so] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

I have no idea what this means. `/home/bli/src/julia/usr/lib` does exist.

**Comment by tkelman** [comment]
Please provide more information about your system, what distribution, compiler versions, etc. What commit of julia are you building?

**Comment by blaiseli** [comment]
I'm building commit aab50d54f779056658eecddb24f041d6f6c99277
I'm on Ubuntu 14.04, with gcc version 4.8.4 and the following lines in `Make.user`:
```
USE_SYSTEM_ZLIB=1
LDFLAGS=-Wl,-rpath /home/bli/lib
MARCH=native
```

I was later able to manually install arpack-ng version 3.1.5 (taken here: <http://forge.scilab.org/index.php/p/arpack-ng/downloads/get/arpack-ng_3.1.5.tar.gz>) with
```
LDFLAGS="-L${HOME}/lib -Wl,-rpath,${HOME}/lib"
CFLAGS="-O3 -march=native -fomit-frame-pointer"
CPPFLAGS="-I${HOME}/include"
./configure  --prefix=${HOME}
```

Adding `USE_SYSTEM_ARPACK=1` to `Make.user` then enabled me to compile julia.

**Comment by tkelman** [comment]
I think you're missing a comma in `LDFLAGS=-Wl,-rpath,/home/bli/lib` - we don't build zlib from source, why are you putting that in Make.user?

**Comment by blaiseli** [comment]
Concerning the absence of comma, I simply copied the example given in `README.md`:
```
* To use external shared libraries not in the system library search path, set `USE_SYSTEM_XXX=1` and `LDFLAGS=-Wl,-rpath /path/to/dir/contains/libXXX.so` in `Make.user`.
```

I built zlib from source for other reasons and wanted to use the locally built version that I hope is more optimized than the system-wide one.

**Comment by tkelman** [comment]
That documentation snippet may be out of date / misleading / wrong, I'm not positive. As I mentioned, Julia doesn't link to zlib directly, only through Julia packages. We bundle a binary of zlib in the Windows binaries of Julia for the purposes of bootstrapping the WinRPM package, but that's of no concern to you on Linux.
