### ISSUE TITLE
Subarray Indexing: Unable to use `end`

### ISSUE THREAD

**Issue by cc7768** [JuliaLang/julia#12204]
Consider the following example:

```
julia> x = randn(5, 2)
5x2 Array{Float64,2}:
 -0.147727  -0.532639
 -2.14838    0.241858
 -2.40407   -0.246935
  0.404095   1.10136 
  0.540395  -0.555922

julia> sub(x, 1:4, :)
4x2 SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},Colon},1}:
 -0.147727  -0.532639
 -2.14838    0.241858
 -2.40407   -0.246935
  0.404095   1.10136 

julia> sub(x, 1:end-1, :)
ERROR: syntax: missing last argument in "1:" range expression 
```

I don't know whether this would be thought of as a bug or feature request, but it seems like the indexing from `sub` should act the same as standard array indexing.

**Comment by jakebolewski** [comment]
`end` without context does not have any meaning. When the keyword `end` is used in some special syntactic construct such as getindex, `foo[end]`, the compiler is able to rewrite this expression to  `foo[length(foo)]`. For a function call, the evaluation of the arguments should all be able to lifted out of the context of the expression and still have meaning (as long as you preserve ordering), ie:
```julia
tmp1 = x
tmp2 = 1:end-1 
tmp3 = : 
foo(tmp1, tmp2, tmp3)
```
as you see this lifted form does not really make sense.

**Comment by cc7768** [comment]
Makes sense -- I hadn't thought of that (obviously). Thanks.
