### ISSUE TITLE
Inlining calls without concrete types can slow things down a lot

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12219]
In situations where a function is inlined without concrete type information, we can end up with multiple dynamic (`jl_apply_generic`) function calls when we only needed one before inlining, which can slow things down a lot. Consider:

``` julia
g(x) = x + x + x + x + x + x + x + x

function h()
    x = Any[1][1]
    for i = 1:1000000
        g(x)
    end
end

julia> @time h()
 350.321 milliseconds (2000 k allocations: 62500 KB, 2.18% gc time)
```

After adding `@noinline` to `g(x)`:

``` julia
julia> @time h()
  17.324 milliseconds (5 allocations: 224 bytes)
```

**Comment by yuyichao** [comment]
Should be type inference not codegen?

**Comment by ArchRobison** [comment]
Looks like I ran into this [too](https://mail.google.com/mail/u/0/#inbox/155374f675a274bb).  

It seems like `jl_apply_generic` should be split into two parts: one that does the lookup and one that does the call.  Then the lookup portion could be subjected to CSE or [PRE](https://en.wikipedia.org/wiki/Partial_redundancy_elimination).

**Comment by KristofferC** [comment]
FWIW, `g` doesn't get automatically inlined anymore.

**Comment by vtjnash** [comment]
Confirmed—nothing to do here anymore
