### ISSUE TITLE
Regression in task switching performance?

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#12223]
Current:

```
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6093 (2015-07-20 07:55 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4ebdea0 (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> function foo(t::Task)
                  while true
                      consume(t)
                  end
              end
foo (generic function with 1 method)

julia> function foon(n)
                  self = current_task()
                  @schedule foo(self)
                  for i in 1:10^n
                      produce(i)
                  end
              end
foon (generic function with 1 method)

julia> foon(1)

julia> @time foon(6)
   6.566 seconds      (2005 k allocations: 31484 KB, 0.11% gc time)
```

The same test here https://github.com/JuliaLang/julia/pull/12042#issuecomment-120815164
took 2.291 seconds on my machine. Granted that was on a different branch rebased around 7 days ago, but that branch did not touch any of the task code either.

**Comment by JeffBezanson** [comment]
The regression appears to be in produce/consume. If you just use `yieldto` instead, I get on 0.3:

```
julia> function foo(t::Task)
                         while true
                             yieldto(t)
                         end
                     end

julia> function foon(n)
                         self = current_task()
                         tt = @schedule foo(self)
                         for i in 1:10^n
                             yieldto(tt)
                         end
                     end

julia> @time foon(6)
elapsed time: 0.544151055 seconds (1136 bytes allocated)
```

and on 0.4:

```
julia> @time foon(6)
 445.107 milliseconds (0 allocations: 1488 bytes)
```

It is actually a bit faster. But I see the same regression in produce/consume.

**Comment by amitmurthy** [comment]
OK. Here is a funny thing.

Rebooting my machine got back the previous performance on master.  I don't know if it is a Linux issue or a Julia thing. I noticed that Julia startup also seemed slow and rebooted.

**Comment by amitmurthy** [comment]
Found the cause. After a couple of `make` it had slowed down again. A `make clean; make` fixed it. I don't know how rebooting improved Julia's startup time and the above timings.

**Comment by JeffBezanson** [comment]
Wow that's weird, the same thing happened to me. Rebuilt and the performance went back to 0.3 levels. Maybe we were running debug builds?

**Comment by amitmurthy** [comment]
Could that explain the performance boost after a reboot also ? Don't know how...
