### ISSUE TITLE
Line number incorrectly identified when incorrectly referring to symbol in imported module

### ISSUE THREAD

**Issue by 315234** [JuliaLang/julia#12222]
Example module file:

    module BugModule
        X = 10
    end

Example calling file:

    import BugModule
    function bug()
        println(1:BugModule.X) # there is no problem here (line 3)
        println(1:X) # error is here (line 4), but report indicates line 3
    end
    bug()

`println(1:X)` is an error, since X must be prefixed by the module name. However, the line number for the error points to the first usage of BugModule.X in the function:

    $ julia bug.jl
    1:10
    ERROR: X not defined
     in bug at /Users/Me/Desktop/bug.jl:3
     in include at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in include_from_node1 at loading.jl:128
     in process_options at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
     in _start at /usr/local/Cellar/julia/0.3.10/lib/julia/sys.dylib
    while loading /Users/Me/Desktop/bug.jl, in expression starting on line 7

The backtrace points to line 3; it should point to line 4.

This is on OS X 10.10.4, Julia 0.3.10 installed via homebrew.

**Comment by JeffBezanson** [comment]
I get the correct line number on master:

```
ERROR: LoadError: UndefVarError: X not defined
 in bug at /home/jeff/src/julia-0.4/julia/i12222.jl:4
 in include at ./boot.jl:254
```
