### ISSUE TITLE
Pkg.publish uses `require`

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#12233]
https://github.com/JuliaLang/julia/blob/700a3f8910c1f92c5403001891285b757d5e3949/base/pkg/github.jl#L27-L34

**Comment by IainNZ** [comment]
I'm not sure if this is a valid fix:
```
function json()
    isdefined(:JSON) || try 
        eval(:(import JSON))
    catch err
        warn(err)
        error("using the GitHub API requires having the JSON package installed ")
    end
    Main.JSON
end
```
I'm at a loss for other methods.

**Comment by yuyichao** [comment]
I think `@eval import JSON` should work on master and looks nicer.

**Comment by IainNZ** [comment]
Can confirm it does work, and does look nicer.

**Comment by JeffBezanson** [comment]
Probably `eval(Main, :(import JSON))` just for good measure.
