### ISSUE TITLE
EPIPE on WIndows during spawn test.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12232]
This first appears with https://github.com/JuliaLang/julia/pull/12144#issuecomment-122535519 .

@Keno

**Comment by Keno** [comment]
@vtjnash is on it.

**Comment by yuyichao** [comment]
Thx. Good to know.

Just want to post it here before I forgot about it since I didn't get a reply to my comment in 2 days.

**Comment by tkelman** [comment]
closed by #12180
