### ISSUE TITLE
sparse(...) + I is slow

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#12249]
This is caught by the function 
+{TA,TJ}(A::AbstractArray{TA,2}, J::Base.LinAlg.UniformScaling{TJ}) at linalg/uniformscaling.jl:35
A specialized handler is missing.

```
julia> @elapsed(speye(10000) + I)/@elapsed(speye(10000) + speye(10000))
6586.4175359600595
```

**Comment by andreasnoack** [comment]
This was fixed in https://github.com/JuliaLang/julia/pull/12030. Still not as fast as `Sparse+Sparse`, but not 6586 times slower.

**Comment by mschauer** [comment]
Great, appreciated.
