### ISSUE TITLE
REPL gets mode transitions confused

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#12254]
To Reproduce
```
println("foo")
;ls
^D
- run julia again
<UP> <ENTER> <DOWN>
```
The REPL now shows a shell mode even though the current base mode is julia. Furthermore, that mode seems bugged. I have seen similar glitches in other scenarios, but this is the most easily reproducible.

**Comment by blakejohnson** [comment]
I'll try to look at this later this week.

**Comment by blakejohnson** [comment]
Gah, this one is tricky. I haven't nailed it down yet but my guess is that your re-write of `transition` causes the passed function to be run twice. So, in this block [here](https://github.com/JuliaLang/julia/blob/bbd37455af07006da496040712942ad979911897/base/LineEdit.jl#L1186) the successive calls to `state(s, p)` will actually return different states. Somehow the changes to the REPL init have blocked my usual means of debugging the REPL, so this is slow going.

**Comment by blakejohnson** [comment]
Well, I was wrong about the source. Still haven't tracked it down, though.

**Comment by blakejohnson** [comment]
I think I found it. @Keno would you mind giving the branch a try to see if it also catches some of the other failure modes you have seen?
