### ISSUE TITLE
`full` on an AbstractArray should not be a no-op

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#12251]
The current fallback definition for `full` [is a no-op for AbstractArray subtypes](https://github.com/JuliaLang/julia/blob/fe62c2efc2b96020ef066c60176892f29e6cd571/base/abstractarray.jl#L419).  @andreasnoack and I feel that  this should be `convert(Array, a)` instead as the implicit contract for `full` is to return a dense array.

Another common subtype that does not densify the result are `Range` types:

``` julia
julia> full(reverse(1:10))
10:-1:1
```

**Comment by JeffBezanson** [comment]
Unless `full` also promises a mutable array, leaving ranges alone might be ok.

Or, we could remove the fallback and only define `full(a::Array)`.

**Comment by mbauman** [comment]
I think `full` is a pretty crummy name, but I suppose it is the standard vocabulary for sparse arrays.  `convert(Array, x)` seems to describe the operation quite well.

Alternatively, we could use `dense = convert(DenseArray, x)`, which may be a little more flexible but yet better defined.

**Comment by StefanKarpinski** [comment]
Can we just call this operation `convert(Array, x)` since that's what it does? Then if you want something less specific, we don't have to invent a name for it – just write `convert(DenseArray, x)`, etc.

**Comment by tkelman** [comment]
Agreed, ref #12153 for the other meaning we've semi-arbitrarily given to `full`. Maybe we just call this a matlab-ism and aim to get rid of it.

**Comment by StefanKarpinski** [comment]
Yes, I think it's badly and unintuitively named and not all that common an operation.

**Comment by jakebolewski** [comment]
I would be happy to get rid of it.  That decision falls in line with "having the user think about types" complaint that we get from time to time but honestly we are not Matlab and thinking about types is unavoidable.

**Comment by jakebolewski** [comment]
Removing `full` causes a lot of excess allocation in the AbstractArray code for Range types.

**Comment by tkelman** [comment]
Is this still 0.5 material? @andreasnoack?

**Comment by andreasnoack** [comment]
I don't think this should block 0.5.

Many of the `full(x)`s could probably be changed to `convert(Array, x) but we need to come up with a function for returning non-view version of a view, i.e. what `copy` does for `SubArray` but it should work for e.g. `XTriangular` and `Symmetric` and maybe also the factorizations. In these cases, we cannot use explicit conversion with a type because the "view" is parametric on the array type.

**Comment by tkelman** [comment]
`parent` ?

**Comment by andreasnoack** [comment]
I thought so too for a while but it doesn't do the right thing for `SubArray`s.

**Comment by tkelman** [comment]
What are the use cases where you need a generic version of that operation that works over multiple views-of-AbstractArray types? You want a copy that includes the hidden parts of the backing data array?

**Comment by timholy** [comment]
We already have a [generic method](https://github.com/JuliaLang/julia/blob/master/base/array.jl#L201) for `convert(Array, ::AbstractArray)`. So I don't think we're missing anything.

**Comment by tkelman** [comment]
I think what Andreas is saying he wants is a generic way of making a copy of the underlying backing array. convert to Array on something like Triangular or Symmetric would have values that match what you would get from getindex, but the backing array will contain extra hidden values.

**Comment by tkelman** [comment]
Or no, nevermind, scratch that. The method we don't have is using the type parameter of Symmetric or Triangular to determine the type of array to convert to.

**Comment by andreasnoack** [comment]
The functions I had in mind were `*` and `\` where we want a `setindex!`able version of one of the arguments. However, I cannot really come up with an example right now so maybe it's not that important. It will probably be a useful but potentially time-consuming effort to go through base and try to eliminate `full`.

**Comment by Sacha0** [comment]
Closed by #24250 and the series of preceding pull requests. Best!
