### ISSUE TITLE
Regex in substrings

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#12262]
This is an attempt to summarize the issues in the messy thread [here](https://groups.google.com/forum/#!topic/julia-users/GK9hMQ8ymY4).  It's quite possible I've misunderstood something (the whole thread is full of "learning moments") or missed part of the API, so apologies in advance.

When parsing data it's quite common to want to match a regex from some point in a string onwards (because you've parsed up to that point and are now looking to parse the following text). Unfortunately, Julia's regex support doesn't seem to provide an efficient way of doing this.  Here are the options I see:

1. Use match(regex, string, offset).  Unfortunately, the regex will match from offset *onwards* (in Python's terms, it will "search", not "match").  If you try to anchor it with `^`, the regex is anchored to the *start* of the text, not the offset.  The only way I can see to make this work is to use the "s" flag (single string mode), and prefix the regex with `^(?:.{offset})` (hoping i am remember the correct syntax for non-capturing group).  Which means recompiling the regex for each query and forcing the "s" flag.

2. Use match(regex, string[offset:end]).  This makes a copy of the string, explicitly, and passes it to match.  Which is expensive for large strings.  Furthermore, any returned match is a `SubString()` based on the copy.  So if the matched data is used by the caller (eg a parser) then the (large) backing copy is not garbage collected.  This can result in huge memory leaks for unsuspecting users (like me).  The work-around is to make an explicit copy of the returned match with `utf8()` or `string(bytestring(...))` (but this still does not avoid the cost of the initial copy).

3. Use match(regex, SubString(string, offset)).  Currently the match() implementation makes a copy and so this suffers from the same issues as (2).  However, I suspect that with some care, you could check whether the substring continues to the end of the backing string and, if so, avoid the copy (taking the C string from a pointer at the given offset into the backing string).  This would be as efficient as (1), but bind `^` to the current offset, which would be ideal for the parser use case.

So, if I have understood, then (3) seems like a useful enhancement.  Thanks.

**Comment by StefanKarpinski** [comment]
Short term, I think that (3) is the way to go. Long term, making substrings cheap is the solution. I thought that someone *had* already made (3) not copy, but perhaps I'm misremembering or that was some other operation with regexes that was optimized.

**Comment by malmaud** [comment]
3 should be easy to implement. Even if it doesn't go the end of the backing string, it still isn't necessary to make a copy.

**Comment by ScottPJones** [comment]
I think the only reason that things currently make a copy is due to the issue of always wanting to have the trailing `\0` byte for strings, but PCRE doesn't need the trailing `\0` anyway, so it should be able to do (3) no matter where the substring points.

**Comment by andrewcooke** [comment]
wow - thanks for moving so fast on this!

**Comment by malmaud** [comment]
No problem. It might make it more likely to get merged sooner if you could try it out and see if it helps your situation (and it if doesn't, I'd like to improve things until it does).

**Comment by andrewcooke** [comment]
good news: it certainly makes it possible to use the regexp with large strings without a memory leak, which was my initial issue.

bad news: i don't understand the scaling in memory use and time use here.  it's not linear.  am i (still) misunderstanding how this works?  (when the code below runs total memory use by the process remains more or less constant and low)

```
julia> r = r"^\w"
r"^\w"

julia> l = Any[]
0-element Array{Any,1}

jjulia> a = repeat("a", 10000);

julia> l = Any[]
0-element Array{Any,1}

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i))
         if m != nothing
           push!(l, m.match)
         end
       end
  62.368 milliseconds (133 k allocations: 101 MB, 26.17% gc time)

julia> a = repeat("a", 100000);  # 10x the size above

julia> l = Any[]
0-element Array{Any,1}

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i))
         if m != nothing
           push!(l, m.match)
         end
       end
   4.079 seconds      (1637 k allocations: 9591 MB, 11.35% gc time)
```

Using SubString(a, i, 1) gets the time back to linear.  So my guess is that either the regexp search is being dumb and doing a full scan (which seems odd), or there's still some copying going on.  But if that's the case, why doesn't memory use go up?  I can run with a string of 1,000,000 elements, which takes minutes, and memory use continues to be flat.

**Comment by andrewcooke** [comment]
incidentally, making the string explicitly utf8 doesn't change anything.

**Comment by ScottPJones** [comment]
What do you mean by using `SubString(a, i, 1)`?  That would just return `""`, unless `i == 1`

**Comment by andrewcooke** [comment]
it was a mistake.  but using SubString(a, i, i) runs faster and uses less memory than SubString(a, i).  i was also concerned that maybe the array allocation isn't amortized, so ran the following:

```
julia> l = Array(Any, 1_000_000);

julia> length(l)
1000000

julia> a = utf8(repeat("a", 100_000));

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i))
         l[i] = m.match
       end
   4.319 seconds      (1437 k allocations: 9585 MB, 17.82% gc time)

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i,i))
         l[i] = m.match
       end
 128.106 milliseconds (1299 k allocations: 49984 KB, 7.06% gc time)

julia> a = utf8(repeat("a", 10_000));

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i))
         l[i] = m.match
       end
  69.210 milliseconds (113 k allocations: 101 MB, 28.43% gc time)

julia> @time for i in 1:length(a)
         m = match(r, SubString(a,i,i))
         l[i] = m.match
       end
  17.617 milliseconds (129 k allocations: 4984 KB)
```
the difference in behaviour for SubString(a, i) and SubString(a, i, i) is clear.  my understanding was using SubString would avoid copying strings.  so i am confused why things change.

**Comment by ScottPJones** [comment]
`SubString(a,i,i)` just returns a single character, while `SubString(a,i)` returns from i to the end of the string, so of course the first will be much faster.

**Comment by andrewcooke** [comment]
ok, so maybe i have misunderstood the whole issue here.  in which case, my apologies.  but i thought SubString was just a "window" onto a backing string - that it didn't allocate memory itself.  if that is incorrect then this whole thread needs re-evaluating.

at first glance, the code in base/strings/types.jl seems to confirm this.

**Comment by ScottPJones** [comment]
It is just a window, but your test is showing the difference in time to do a match operation on a substring that is from 1 to 10,000 characters long (`SubString(a,i)`, vs. 1 character long (`SubString(a,i,i)`, vs. 0 characters long (`SubString(a,i,1)`)

**Comment by ScottPJones** [comment]
Also, remember you need to run all tests twice in Julia, because the first time will usually capture JIT compilation time of Julia.
The thing to do is to compare the speed of match with a substring of length x to match with a normal string of length x.  (and do it first with 1 repetition, and then with thousands)

**Comment by johnmyleswhite** [comment]
```jl
julia> isbits(SubString)
false
```

Since `SubString` isn't a bitstype, it probably gets boxed, which produces a new heap allocation on every substring object creation event. This is being worked on, but I think you should assume `SubString` allocates a lot of memory right now inside a tight loop.

**Comment by andrewcooke** [comment]
scott - the regexp is for a single character. why would it scan the entire string?

john - the point isn't that it allocates data.  the point is that the scaling is not as expected.  there's some n^2 scaling that suggests that the string itself is being copied.  the idea behind this request was to avoid that by using pointers into the existing data.

**Comment by ScottPJones** [comment]
OK, I hadn't looked at the regexp (it wasn't shown in the last bit of code you copied).
I get this difference between using a `SubString` of 100 characters, and a normal string of the same 100 characters:
```julia
julia> ugh(100000)
  38.575 milliseconds (1000 k allocations: 62500 KB)
  19.201 milliseconds (500 k allocations: 21875 KB)
```
and so I think John is right, it's getting another allocation from boxing every time (10 allocations per loop as opposed to 5 allocations per loop),
but this isn't testing with @malmaud's change, because that's not merged yet.

**Comment by andrewcooke** [comment]
here is the code with pre-compiled:

```
julia> function f(n)
         a = utf8(repeat("a", n))
         l = Array(Any, n)
         r = r"^."
         for i = 1:n
           l[i] = match(r, SubString(a, i)).match
         end
       end
f (generic function with 1 method)

julia> f(1_000)

julia> @time f(1_000)
   3.904 milliseconds (10154 allocations: 1479 KB)

julia> @time f(10_000)
  87.399 milliseconds (83942 allocations: 100 MB, 12.27% gc time)

julia> @time f(100_000)
   3.745 seconds      (1138 k allocations: 9580 MB, 9.10% gc time)

julia> function g(n)
         a = utf8(repeat("a", n))
         l = Array(Any, n)
         r = r"^."
         for i = 1:n
           l[i] = match(r, SubString(a, i, i)).match
         end
       end
g (generic function with 1 method)

julia> g(1_000)

julia> @time g(1_000)
   1.141 milliseconds (10007 allocations: 447 KB)

julia> @time g(10_000)
  11.341 milliseconds (100 k allocations: 4463 KB)

julia> @time g(100_000)
  91.445 milliseconds (1000 k allocations: 44629 KB, 11.76% gc time)
```

there is a clear difference between SubString of length 1, and length n.  the length 1 is O(n), the length n is O(n).

maybe i am being really dumb (believe me, this is frustrating), but if SubString doesn't copy the string, and the regex does't scan the string, and the patch avoids copying the string, why is there a difference?

**Comment by ScottPJones** [comment]
I get this:
```julia
julia> ugh(1)
   8.530 microseconds (10 allocations: 640 bytes)
   1.066 microseconds (5 allocations: 224 bytes)

julia> ugh(1000)
 592.416 microseconds (10000 allocations: 625 KB)
 176.914 microseconds (5000 allocations: 219 KB)

julia> ugh(1000000)
 714.956 milliseconds (10000 k allocations: 610 MB, 30.78% gc time)
 204.311 milliseconds (5000 k allocations: 214 MB)
```

**Comment by andrewcooke** [comment]
i have no idea what ugh is, so it's hard to understand anything there.

**Comment by andrewcooke** [comment]
also, i am using malmaud's branch.  i was initially responding to him.  he asked me to test his code.

**Comment by ScottPJones** [comment]
OK, I'm building with that now.  Sorry, I forgot to cut and paste my code, here it is:
```julia
julia> function dotest(n,r,l,a)
           @time for i = 1:n ; m = match(r, SubString(a,101,200)) ; l[i] = m.match ; end
       end
dotest (generic function with 1 method)

julia> function dotest2(n,r,l,a)
           @time for i = 1:n ; m = match(r, a) ; l[i] = m.match ; end
       end
dotest2 (generic function with 1 method)

julia> function ugh(n)
           pat = r"^\w"
           arr = Array(Any, 1_000_000)
           str = utf8(repeat("a", 1000))
           dotest(n, pat, arr, str) ; s2 = utf8(repeat("a", 100)) ; dotest2(n, pat, arr, s2)
       end
ugh (generic function with 1 method)

julia> ugh(1)
  36.404 microseconds (17 allocations: 960 bytes)
   3.920 microseconds (5 allocations: 224 bytes)

julia> ugh(1)
   8.771 microseconds (10 allocations: 640 bytes)
   1.208 microseconds (5 allocations: 224 bytes)

julia> ugh(1000)
 573.125 microseconds (10000 allocations: 625 KB)
 167.768 microseconds (5000 allocations: 219 KB)

julia> ugh(1000000)
 547.260 milliseconds (10000 k allocations: 610 MB, 29.79% gc time)
 297.629 milliseconds (5000 k allocations: 214 MB, 39.43% gc time)
```
I'm not seeing any O(n^2) issues at all, this is using malmaud's branch now.

**Comment by andrewcooke** [comment]
you appear to be testing something different to me.

in my test the size of the string being matched is proportional to the string size, which is my "n".  in your test, "n" is just the number of matches.

my problem is that there appears to be a scaling that depends on string length.  that implies that a string is being copied somewhere, which is what the patch was meant to correct for.

in more detail:  as i increase string length, i expect things to be slower because there are more matches.  but that is only a factor of O(n).  instead, with SubString(a, i), i am seeing a scaling of O(n^2), which indicates that there is an extra cost of O(n).  which seems likely to be a string copy.

my understanding was that this patch removed the need to copy strings.

**Comment by andrewcooke** [comment]
maybe this code makes it clearer:

```
julia> function f(n)
         a = utf8(repeat("a", n))
         l = Array(Any, n)
         r = r"^."
         for i = 1:n
           l[i] = match(r, SubString(a, 1)).match
         end
       end
f (generic function with 1 method)

julia> f(1_000)

julia> @time f(1_000)
 926.658 microseconds (10154 allocations: 2426 KB)

julia> @time f(10_000)
 130.336 milliseconds (80008 allocations: 195 MB, 10.88% gc time)

julia> @time f(100_000)
   7.690 seconds      (1200 k allocations: 19117 MB, 8.84% gc time)
```

note that hear the SubString is always from the first character.  it makes no difference to the argument, but may have confused you in the earlier code.

**Comment by andrewcooke** [comment]
here's an even clearer version:

```
julia> function f(n)
         a = utf8(repeat("a", n))
         l = Array(Any, 1000)
         r = r"^."
         for i = 1:1000
           l[i] = match(r, SubString(a, 1)).match
         end
       end
f (generic function with 1 method)

julia> f(1_000)

julia> @time f(1_000)
   2.310 milliseconds (10007 allocations: 2415 KB)

julia> @time f(10_000)
  20.551 milliseconds (8006 allocations: 20018 KB, 9.85% gc time)

julia> @time f(100_000)
  81.587 milliseconds (12008 allocations: 191 MB, 5.34% gc time)
```

in this code, the number of matches is constant.  the matches are all single character.  but time increases as the string gets larger.

**Comment by andrewcooke** [comment]
there is no similar scaling without SubString:
```
julia> a = utf8(repeat("a", 1_000));

julia> function f(a)
         l = Array(Any, 1000)
         r = r"^."
         for i = 1:1000
           l[i] = match(r, a).match
         end
       end
f (generic function with 2 methods)

julia> f(a)

julia> @time f(a)
 680.526 microseconds (5004 allocations: 227 KB)

julia> a = utf8(repeat("a", 10_000));

julia> @time f(a)
 608.570 microseconds (5004 allocations: 227 KB)

julia> a = utf8(repeat("a", 100_000));

julia> @time f(a)
 553.756 microseconds (5004 allocations: 227 KB)

julia> a = utf8(repeat("a", 1000_000));

julia> @time f(a)
 154.700 microseconds (5004 allocations: 227 KB)
```

**Comment by andrewcooke** [comment]
just to be completely clear, here's exactly the same code as above, with SubString, showing the changed behaviour:
```
julia> function f(a)
         l = Array(Any, 1000)
         r = r"^."
         for i = 1:1000
           l[i] = match(r, SubString(a, 1)).match
         end
       end
f (generic function with 1 method)

julia> a = utf8(repeat("a", 1_000));

julia> f(a)

julia> @time f(a)
   2.030 milliseconds (10151 allocations: 2425 KB)

julia> a = utf8(repeat("a", 10_000));

julia> @time f(a)
  29.572 milliseconds (8004 allocations: 20008 KB, 16.97% gc time)

julia> a = utf8(repeat("a", 100_000));

julia> @time f(a)
  79.193 milliseconds (12004 allocations: 191 MB, 6.93% gc time)

julia> a = utf8(repeat("a", 1000_000));

julia> @time f(a)
 796.264 milliseconds (12004 allocations: 1908 MB, 3.44% gc time)
```

**Comment by andrewcooke** [comment]
@malmaud - all my problems are described in the two posts immediately above.  sorry for the noise here - i could have picked my examples better.  your patch appears to fix one issue i had, but still seems to be copying data when SubString is used.  maybe this is expected, but it surprised me.

**Comment by malmaud** [comment]
Let me look into it later today.

**Comment by malmaud** [comment]
@andrewcooke Thanks for the careful detective work. I've found the problem - Julia unnecessarily converts substrings to full strings (thereby causing a copy) when passing a substring to a C function (in this case, to PCRE). I'll submit a patch to fix it.

**Comment by andrewcooke** [comment]
great!  thanks again!

**Comment by malmaud** [comment]
I believe the PR fixes this now:

```julia
function f(a)
    l = Array(Any, 1000)
    r = r"^."
    for i = 1:1000
        l[i] = match(r, a).match
    end
end

function g(a)
    l = Array(Any, 1000)
    r = r"^."
    s=SubString(a,1)
    for i = 1:1000
        l[i] = match(r, s,1).match
    end
end

for N in (10^3, 10^4, 10^5)
    @show N
    a = utf8(repeat("a", N))
    @time f(a)
    @time g(a)
    println("")
end


N = 1000
 305.876 microseconds (5001 allocations: 227 KB)
 311.832 microseconds (5002 allocations: 227 KB)

N = 10000
 305.806 microseconds (5001 allocations: 227 KB)
 273.758 microseconds (5002 allocations: 227 KB)

N = 100000
 280.886 microseconds (5001 allocations: 227 KB)
 277.868 microseconds (5002 allocations: 227 KB)
```

**Comment by andrewcooke** [comment]
looks good to me too.  thanks again.

**Comment by ScottPJones** [comment]
Very nice, @malmaud!

**Comment by andrewcooke** [comment]
as an example of how much this matters, it's cut the time needed to parse the file i am testing with (and which originally triggered this issue) by almost exactly half.  and i plan to squeeze more speed out of regexps now that they have a lower cost....

**Comment by malmaud** [comment]
Sweet. There is another gaping inefficiency that could be fixed on the julia side - each call to `match` allocates several new objects on the heap, which is wasting time and memory. The API should be adjusted to allow a match object to just be allocated once at the top of loop and then reused.

**Comment by andrewcooke** [comment]
That might help too, but for me the priority would be getting this into trunk.  It's working perfectly for me.  Is there anything else I can do to encourage it's adoption?

**Comment by malmaud** [comment]
I think it will be merged within a day. It is not controversial.

**Comment by ivarne** [comment]
Even if it doesn't make 0.4.0, there will be 0.4.1 and 0.4.2, within a few months that we can backport performance fixes to (as long as it doesn't break previously working code). 

@malmaud's time estimate seems correct though.
