### ISSUE TITLE
Should iteration over Associatives return Pairs

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#12261]
Right now we have
```
julia> first(Dict(1=>2))
(1,2)
```
I'm proposing this be changed to
```
julia> first(Dict(1=>2))
1 => 2
```
i.e. treating dicts as a list of key value pairs for the purposes of iteration. Making them a pair makes clear what the return value means. I think this is a fairly non-breaking change as `Pair` essentially behaves as a 2-element tuple anyway.

**Comment by StefanKarpinski** [comment]
+10, I feel like this was just a possible oversight in the Pair change, or maybe there was some compatibility reason for it.

**Comment by stevengj** [comment]
Seems reasonable to me; `for (k,v) in dict` and similar should still work, as @Keno says.

**Comment by lindahua** [comment]
+1

**Comment by ivarne** [comment]
+1

Ref https://github.com/JuliaLang/julia/pull/9905 for previous discussion and oversight.

**Comment by JeffBezanson** [comment]
This is fine but there's an interesting point here regarding covariance. If the eltype of a `Dict{Any,Any}` is `Tuple{Any,Any}`, it can return more specific tuples like `Tuple{Int,Int}` for particular elements. With Pairs, every item iterated will have to be a `Pair{Any,Any}` exactly.

**Comment by JeffBezanson** [comment]
To be a bit more concrete, returning `k=>v` as an element of a Dict might be wrong. One needs to be careful to return a `Pair{K,V}(k,v)`.

**Comment by StefanKarpinski** [comment]
I'm not sure what the practical consequences of that would be...

**Comment by JeffBezanson** [comment]
Not many, but for example `1=>2` is `===` to an element of `Dict(1=>2)`, but not to an element of `Dict{Any,Any}(1=>2)`.

**Comment by ivarne** [comment]
Ref https://github.com/JuliaLang/julia/issues/12319. 

We should consider making this change universal for all functions that return key => value pairs.
