### ISSUE TITLE
test_equals

### ISSUE THREAD

**Issue by irving0p0rabin** [JuliaLang/julia#12272]
Currently we have only a clause `@test <expression> == <value>`. However it is not expressive enough. For example, if I want to check that function returns 5, I need to say

```jl
@test foo() == 5
```

If result is not 5 but 7, I have no idea what the result is. It simply says that boolean value `foo() == 5` is false. I will have to put extra control prints to figure out what is going on. 

What would be great to have is something like this (similar to Junit and other platforms):

```jl
@test_equals(5, foo())
```
with a message - `foo()` - expected 5, actual 7.

[jiahao - edit for code block formatting]

**Comment by jiahao** [comment]
Please use code formatting syntax as described in the GitHub docs. It is easier to read and avoids pinging users.

Also, this particular reporting issue seems to be better on 0.4:

```jl
julia> foo()=7; Base.Test.@test foo()==5
ERROR: test failed: 7 == 5
 in expression: foo() == 5
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
```

On v0.3, the `in expression:...` line is not printed.

**Comment by yuyichao** [comment]
I think `@test` actually recognize `==`. On master

```julia
julia> Base.Test.@test (() -> 5)() == 7
ERROR: test failed: 5 == 7
 in expression: ((()->begin  # none, line 1:
            5
        end))() == 7
 in default_handler at ./test.jl:30
 in do_test at ./test.jl:53
```

**Comment by jiahao** [comment]
Also rather ugly, but you can also do:

```jl
julia> foo()=7; Base.Test.@test_approx_eq_eps foo() 5 0.0 #approximate equality with tolerance 0
ERROR: assertion failed: |foo() - 5| <= 0.0
  foo() = 7
  5 = 5
  difference = 2 > 0.0
 in error at error.jl:22
 in test_approx_eq at test.jl:109
```

**Comment by irving0p0rabin** [comment]
julia> foo() = 7
foo (generic function with 1 method)

julia> Base.Test.@test foo()==5
ERROR: test failed: foo() == 5
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39

**Comment by yuyichao** [comment]
The output we give about is on `0.4`. The `0.3` printing will not be changed anymore. IMHO, the message on 0.4 is generic and also informative enough.

**Comment by jiahao** [comment]
@irving0p0rabin you need to use [this syntax](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) for code.

**Comment by ivarne** [comment]
> The 0.3 printing will not be changed anymore.

Unless someone prepares a PR against the `release-0.3` branch that includes the relevant change and tests, and someone  else bothers to review so that it can be merged.
