### ISSUE TITLE
static compilation loses docstrings

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12284]
Statically compiling a module seems to confict with the `@doc` mechanism: the documentation is no longer available after precompiling.

For example, create a `Foo.jl` file containing:
```jl
module Foo
export foo
@doc "foo function" foo(x) = x + 1
end
```
Then `using Foo` followed by `?foo` prints `foo function` as expected.  However, if you do `Base.compile(:Foo)`, then the help for `foo` is just `foo (generic function with 1 method)`.

This needs to be fixed before 0.4, I think; it is not acceptable to have two of the most important new features of 0.4 conflict with one another.

cc: @vtjnash, @one-more-minute

**Comment by one-more-minute** [comment]
Does
```julia
push!(Foo, Base.Docs.modules)
```
fix this? If so it should be fairly simple to resolve – just do that automatically when loading a precompiled module.

**Comment by stevengj** [comment]
Thanks, `push!(Base.Docs.modules, Foo)` indeed restores the documentation.

**Comment by stevengj** [comment]
@vtjnash, would
```
--- a/base/loading.jl
+++ b/base/loading.jl
@@ -123,6 +123,7 @@ function require(mod::Symbol)
     try
         toplevel_load = false
         if _require_from_serialized(1, mod, last)
+            eval(Main, :(push!(Base.Docs.modules, $mod)))
             return true
         end
         if JLOptions().incremental != 0
```
do it?

**Comment by vtjnash** [comment]
there's no need to eval that in Main,
```
push!(Base.Docs.modules, Main.(mod))
```
should work there.

**Comment by stevengj** [comment]
@one-more-minute, is there some `Dict` in the module that needs a `rehash!`?

**Comment by JeffBezanson** [comment]
Could the doc system do this automatically? I.e. if you ask for help on a function that comes from a module it doesn't know about, `push!` the module at that point.

**Comment by one-more-minute** [comment]
The docs are actually stored in `Mod.__META__` – it's an `ObjectIdDict` so I think it should survive the caching without a rehash, but I'm not totally sure. Probably a good idea to check `__META__` exists before pushing it into the doc system.

@JeffBezanson In general, a method and its documentation might be defined outside of the original function's module – you can't know for sure where a given object's meta will come from.

**Comment by stevengj** [comment]
Why would `__META__` not exist?

**Comment by one-more-minute** [comment]
Yeah, ideally we should initialise `__META__` in all modules when they're created. I'm not sure of the best way to do that, though.
