### ISSUE TITLE
ArgumentError: invalid argument #3 to LAPACK call in gebal!

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#12294]
Happening occasionally on the buildbots and Travis, I think only since #12217 was merged.

http://buildbot.e.ip.saba.us:8010/builders/build_ubuntu12.04-x64/builds/2074/steps/shell_2/logs/stdio
```
exception on 4: ERROR: LoadError: ArgumentError: invalid argument #3 to LAPACK call
 in gebal! at linalg/lapack.jl:134
 in expm! at linalg/dense.jl:193
 in expm at linalg/dense.jl:184
 in anonymous at no file:178
 in include_string at loading.jl:158
 in include_from_node1 at ./loading.jl:200
 in runtests at /home/ubuntu/buildbot/slave/build_ubuntu12_04-x64/build/test/testdefs.jl:197
 in anonymous at /home/ubuntu/buildbot/slave/build_ubuntu12_04-x64/build/test/runtests.jl:14
 in anonymous at multi.jl:822
 in run_work_thunk at multi.jl:584
 in anonymous at task.jl:822
while loading /home/ubuntu/buildbot/slave/build_ubuntu12_04-x64/build/test/linalg3.jl, in expression starting on line 164
	From worker 5:	     * linalg/lapack         in  28.57 seconds
	From worker 3:	     * linalg2               in  40.70 seconds
	From worker 2:	     * linalg1               in  79.40 seconds
ERROR: LoadError: LoadError: ArgumentError: invalid argument #3 to LAPACK call
 in anonymous at task.jl:1394
while loading /home/ubuntu/buildbot/slave/build_ubuntu12_04-x64/build/test/linalg3.jl, in expression starting on line 164
while loading /home/ubuntu/buildbot/slave/build_ubuntu12_04-x64/build/test/runtests.jl, in expression starting on line 5
	From worker 4:	     * linalg3               ** On entry to DGEBAL parameter number  3 had an illegal value
make[1]: *** [all] Error 1
```

**Comment by mfasi** [comment]
@tkelman Thank you for pointing it out, it looks like `logm` fails in one of the tests. My guess is that `logm` produces a matrix containing some `NaN`s, I'll have a look and try to understand what happens.

**Comment by rieser** [comment]
I'm getting a similar error, after a call to expm in Julia 4.1:

** On entry to DGEBAL parameter number  3 had an illegal value
ERROR: LoadError: ArgumentError: invalid argument #3 to LAPACK call
 in gebal! at linalg/lapack.jl:158
 in expm! at linalg/dense.jl:197
 in expm at linalg/dense.jl:186
 [inlined code] from 
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading ...
