### ISSUE TITLE
Documentation for SPQR qrfact()

### ISSUE THREAD

**Issue by kersulis** [JuliaLang/julia#12298]
I'm happy that [SPQR functionality is wrapped in Julia][1], but I don't know what to do with the pointer returned by qrfact(). The [linear algebra documentation][2] says 

> The function calls the C library SPQR and a few additional functions from the library are wrapped but not exported.

I studied [SPQR.jl][4] and couldn't find any method that would interpret something like
```julia
Base.SparseMatrix.SPQR.Factorization{Float64}(558,450,Ptr{Base.SparseMatrix.SPQR.C_Factorization{Float64}} @0x00000000061d1970)
```
in terms of Q and R. As someone who hasn't worked with SPQR before, I got hung up here as I tried to figure out what to do with the pointer.

I read the [documentation on calling C code][3] but that was too general -- it didn't tell me how to extract Q and R. I also couldn't find anything helpful [here][6] or [here][5]. Can someone explain what to do with a `C_Factorization` object and perhaps include the description in the linear algebra or sparse matrix documentation?

[1]: https://github.com/JuliaLang/julia/blob/master/base/sparse/spqr.jl#L139
[2]: http://julia.readthedocs.org/en/latest/stdlib/linalg/
[3]: http://julia.readthedocs.org/en/latest/manual/calling-c-and-fortran-code/
[4]: https://github.com/JuliaLang/julia/blob/master/base/sparse/spqr.jl
[5]: http://faculty.cse.tamu.edu/davis/suitesparse.html
[6]: http://julia-demo.readthedocs.org/en/latest/stdlib/sparse.html

**Comment by andreasnoack** [comment]
Right before the sentence you cited, the documention tells that
>  The main application of this type is to solve least squares problems with "\".

and indeed, `SPQR.Factorization` is the underlying factorization for sparse least squares.

```jl
julia> A,b  = sprandn(10,3, 0.4), randn(10); 

julia> qrfact(A)\b == A\b 
true                      
```

If you have any ideas to improve the documentation then please open a pull request with them. It would be highly appreciated.

**Comment by kersulis** [comment]
Oh, okay. So `qrfact(A)` is used to extend `backslash` to cases where A is sparse, not to return explicit Q and R. Thank you for the explanation.

What I'm really trying to do here is find a basis for the null space of a sparse matrix. I was hoping to extract Q from `qrfact(A')` and use its columns for that purpose (`nullspace()` doesn't take advantage of sparsity). Is there a way to do this already, or should I work on adding this functionality to `nullspace()`?

**Comment by andreasnoack** [comment]
Yes and no. `qrfact` is also used when computed least squares for dense matrices (although you'll have to explicitly ask for pivoting)
```jl
julia> A, b = randn(10,3), randn(10);

julia> A\b == qrfact(A, Val{true})\b
true
```
In `spqr.jl` the function for multiplying with `Q` and `Q'` is actually wrapped in `qmult`. Maybe that is enough for your problem.
```jl
                                                                                             
julia> A, b = sprandn(10,3, 0.5), randn(10);                                                 

julia> F = qrfact(A);
                                                                                            
julia> SparseMatrix.SPQR.qmult(SparseMatrix.SPQR.QTX, F, SparseMatrix.CHOLMOD.Dense(b))      
10x1 Base.SparseMatrix.CHOLMOD.Dense{Float64}:                                               
  0.280707                                                                                   
  0.731387                                                                                   
 -0.050665                                                                                   
 -0.490562                                                                                   
  0.0116658                                                                                  
 -0.491805                                                                                   
 -1.20339                                                                                    
 -1.96395                                                                                    
 -1.04466                                                                                    
  0.980378                                                                                   
```

We'd have to think a bit about how to represent the null space for a sparse matrix, because it could easily become a large dense matrix.

**Comment by kersulis** [comment]
`qmult` is just what I needed. The following block produces the same result whether `spqr` is true or false, as desired:

```julia
    if spqr
        F = qrfact(sparse(A'))
        # B selects last dim_N cols of Q:
        B = [zeros(size(A,2)-dim_N,dim_N); eye(dim_N)]
        N = convert(Array,SparseMatrix.SPQR.qmult(SparseMatrix.SPQR.QX, F, SparseMatrix.CHOLMOD.Dense(B)))
        return N
    else
        q = qr(A'; thin=false)[1]
        return q[:,end-dim_N+1:end]
    end
```

Thank you for explaining the SPQR functionality, you were very helpful.

**Comment by mohamed82008** [comment]
How can I access qmult from Base in v0.6? Base.SparseMatrix returns an error.

**Comment by fredrikekre** [comment]
`SparseArrays.SPQR.qmult`

**Comment by mohamed82008** [comment]
Perfect thanks!

**Comment by mohamed82008** [comment]
It seems that it doesn't support a sparse vector `b` in this form: `SparseMatrix.SPQR.qmult(SparseMatrix.SPQR.QTX, F, SparseMatrix.CHOLMOD.Sparse(b))`. Am I missing something?

**Comment by mohamed82008** [comment]
Hi again, so 2 points are still not clear to me after reading the above discussion. Firstly how can I get the R matrix from a sparse QR pointer? And how can I transpose the Q matrix in qmult before multiplying it? I would appreciate an answer, thanks!

**Comment by mohamed82008** [comment]
I think I found my answer in spqr.jl, don't bother!

**Comment by andreasnoack** [comment]
@mohamed82008 1) Please ask usage questions on discourse.julialang.org 2) Notice that the SPQR functionality will be completely new in Julia 0.7 where you'll be able to extract `R` directly and `Q`s similarly to how you extract them for dense QR.
