### ISSUE TITLE
peek() returns a tuple instead of a key

### ISSUE THREAD

**Issue by vixsomnis** [JuliaLang/julia#12319]
Arch Linux Julia package:
Julia Version 0.3.10
Commit c8ceeef (2015-06-24 13:54 UTC)

(I believe this issue is also present in the latest commit and docs.)

Instead of returning only the [key](http://docs.julialang.org/en/latest/stdlib/collections/#Base.Collections.peek), `peek()` returns a tuple consisting of a `(k,v)` tuple.

Is the documentation wrong or is the behavior wrong?

**Comment by ivarne** [comment]
The return type was just changed from Tuple to Pair in https://github.com/JuliaLang/julia/pull/12327, so I assume this should be considered a documentation issue.

**Comment by vixsomnis** [comment]
A pair is still essentially two values, however -- which is the conflict I am referencing. Should peek() return a single value in the same way as dequeue!()?

**Comment by JeffBezanson** [comment]
@dcjones @kmsquire Was the intent to return just the key or the pair?

**Comment by kmsquire** [comment]
When @dcjones created it in https://github.com/JuliaLang/julia/commit/39b5c3d90b15877d4f62140f583ab8c67d3af290#diff-10b4d49367d18d7903690d5b40f848fcR184, it only returned a key.

@timholy changed it (back?) to a pair in #8011, and that seems to be the intent.  I also believe he uses this code, so he should probably chime in.

(I don't think I ever touched this code.)

**Comment by timholy** [comment]
Small correction: it always returned the `(K,V)` tuple. In @dcjones version, `xs` was an array of tuples, so returning the first element returned a `(K,V)` pair. For performance reasons (back before tuples were really fast), I changed `xs` to an array of pairs, and rewrote `peek` return a tuple for backwards compatibility.

**Comment by vixsomnis** [comment]
This is really more about whether ```peek``` should return a single value (like how ```dequeue!``` returns just the key) or both the key and the value associated with it.

As it stands right now, ```peek``` has no real mutating alternative. ```dequeue!``` only returns the key, but you can't get the value for that after dequeuing since the priority queue no longer contains the key.

````
k = dequeue!(pq)
v = pq[k] # doesn't work
dostuff
````
We can work around this with peek.
````
kv = peek(pq)
dostuff
dequeue!(pq) # but we don't need the return value anymore
````
The intent of the second example is obscured by the use of ```peek``` (non-mutating) and throwing away the return value of ```dequeue!```. 

Should ```peek``` return only ````K```? Should ```dequeue!``` return ```(K,V)```?

Another possibility is to give ```pop!``` a method to handle priority queues that returns a ```(K,V)``` the same way peek does, thus keeping ```dequeue!``` consistent with ```enqueue!```.

**Comment by KristofferC** [comment]
I think this can be closed since `peek` and corresponding data structure has been moved to https://github.com/JuliaCollections/DataStructures.jl?
