### ISSUE TITLE
1 < 2 |> foo gives a syntax error

### ISSUE THREAD

**Issue by shashi** [JuliaLang/julia#12324]
```julia
foo(x) = x
1 < 2 |> foo
```
Returns `true` on 0.3.8, but results in `ERROR: syntax: extra token "|>" after end of expression` on v0.3.10 and on master.

However
```julia
1 + 2 |> foo
```
works everywhere (returns 3). My impulse is to classify 1 + 2 and 1 < 2 both as  "binary operations" and assume they both work the same way when pit against a pipe operator. I'd like to fix my understanding if that's the problem.

the precedence rule for this seems to have existed ever since 432780b70a58928454dabf01f5a06d430367e1dc but I could not track down where the behavior changed.

what's fishy is that `git diff v0.3.8..v0.3.10 -- src/julia-parser.scm` shows nothing.

**Comment by tkelman** [comment]
I'm seeing this the other way around, `1 < 2 |> foo` gives an error on 0.3 but works on master.

**Comment by shashi** [comment]
Oops, you're right. My bad. I got confused with which prompt I typed things in.
