### ISSUE TITLE
profile tests failing on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12346]
```
     * profile              WARNING: There were no samples collected. Run your program longer (perhaps by
running it multiple times), or adjust the delay between samples with
Profile.init().
exception on 1: ERROR: LoadError: test failed: !(isempty(str))
 in expression: !(isempty(str))
while loading /home/viral/julia/test/profile.jl, in expression starting on line 14
ERROR: LoadError: LoadError: test failed: !(isempty(str))
 in expression: !(isempty(str))
while loading /home/viral/julia/test/profile.jl, in expression starting on line 14
while loading /home/viral/julia/test/runtests.jl, in expression starting on line 5
```

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6253 (2015-07-26 15:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a97b24b* (1 day old master)
|__/                   |  arm-linux-gnueabihf
```

**Comment by vtjnash** [comment]
i suspect this can be fixed once https://github.com/JuliaLang/julia/pull/12380 is merged

**Comment by yuyichao** [comment]
I think this is because we disable libunwind on ARM. The `meta` and `backtrace` tests fails for similar reasons.

**Comment by vtjnash** [comment]
yes. in particular, we disable libunwind backtraces because it segfaults when it encounters a frame that is not from a file with unwind info (e.g. our JIT functions)

**Comment by yuyichao** [comment]
Unfortunately even with libunwind master and JIT frame registration there's still segfault when re-enabling backtrace on ARM.....

**Comment by jgonzal13** [comment]
hi all, has there been any progress on this issue? 
i'm using Julia on an ARM device, currently trying to identify bottleneck parts of some code
it'd be great to use the profile tool for this

**Comment by ViralBShah** [comment]
Is it possible to use @keno's Gallium unwinder for the profiler?

**Comment by yuyichao** [comment]
FWIW, I don't think ARM has dwarf unwind info.

**Comment by yuyichao** [comment]
With https://github.com/JuliaLang/julia/pull/18761 unwinding (and sometimes profiling) should be working on ARM. The profiling segfault isn't fixed yet though.

**Comment by KristofferC** [comment]
This seems stale. Closing.
