### ISSUE TITLE
mkdir permission issues

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#12341]
```julia
mkdir("test")
```
gives the same file permissions as
```julia
mkdir("test",0o777)
```
less permissions are always possible
```julia
mkdir("test", 0o700)
```
and a posterior change of permissions behaves as expected:
```julia
chmod("test", 0o777)
```
I tested this on several Linux computers with Julia 0.3.x

**Comment by JeffBezanson** [comment]
This is probably due to the default umask of `0o022`. I don't think we should change it.

**Comment by yuyichao** [comment]
Python's `os.mkdir` behaves the same.

**Comment by gdkrmr** [comment]
Well, I found it very strange to find that ```mkdir("test", 0o777)``` does not create a directory with the corresponding permissions. 
Also code might not be portable between environments with different ```umask``` defaults.

**Comment by JeffBezanson** [comment]
Well, that's unix's horrible process-global state behavior for you.

**Comment by StefanKarpinski** [comment]
We could potentially work around the way UNIX does this and do something better, but the current behavior is intentional and how most other languages do it.

**Comment by JeffBezanson** [comment]
The main problem is that changing the default umask to 0 would not look good from a security perspective.

**Comment by gdkrmr** [comment]
```julia
function mkdir2(path::String, mode::Unsigned)
    mkdir(path)
    chmod(path,mode)
end
```
works for me

**Comment by StefanKarpinski** [comment]
Agreed. I think this is not our fight to fight.
