### ISSUE TITLE
triangular test hangs on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12345]
The triangular test was hanging on arm, and I had to ctrl-c it. Perhaps it just takes a long time to run, and I will try running it for a much longer time next time around. For now, I am just capturing all failures I come across.

````
(precise)viral@localhost:~/julia/test$ ../julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6253 (2015-07-26 15:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a97b24b* (1 day old master)
|__/                   |  arm-linux-gnueabihf

julia> VERSION
v"0.4.0-dev+6253"
````

**Comment by andreasnoack** [comment]
The triangular tests are quite compilation intensive and the size of the binary grows 280Mb during the execution of the tests. This can also be seen from timings
```jl
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6292 (2015-07-27 21:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  master/9e6db61* (fork: 1 commits, 0 days)
|__/                   |  x86_64-apple-darwin14.4.0

julia> @time include("test/linalg/triangular.jl");
  57.022 seconds      (85522 k allocations: 6924 MB, 3.49% gc time)

julia> @time include("test/linalg/triangular.jl");
   3.887 seconds      (18123 k allocations: 3603 MB, 23.73% gc time)
```
I guess compilation is much slower on ARM, but are you monitoring the memory usage on the machine during the tests?

**Comment by tkelman** [comment]
And codegen is quite a bit slower on MCJIT vs LLVM 3.3.

**Comment by ViralBShah** [comment]
This is good to know. I will rerun those tests and monitor how the system is doing. I do have 4G RAM on this machine, so that should be sufficient. We now have lots more tests than the last time I did this, and it is taking hours to complete.

I would love to have a way to run the entire test suite in such a way that all tests are run and failures reported, rather than the whole thing exiting on first failure.

**Comment by ihnorton** [comment]
I'll rebase #10835.

**Comment by tkelman** [comment]
In the meantime there's `include("test/choosetests.jl"); testlist, net_on = choosetests(); for i in testlist; try Base.runtests(i, 1); catch; end; end`

**Comment by ViralBShah** [comment]
I was doing the for loop on the shell, but this is better. Do we have anything that will kill a test in 10 minutes, if it hasn't succeeded or failed by then?

**Comment by tkelman** [comment]
coreutils `timeout` is probably the easiest way, we might have the equivalent in Julia but I don't know off the top of my head

**Comment by andreasnoack** [comment]
To quantify @tkelman's very correct statement I've just timed with LLVM svn
```jl
Andreass-MacBook-Pro:julia-llvm-dev andreasnoack$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6396 (2015-07-29 22:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1f7a481* (0 days old master)
|__/                   |  x86_64-apple-darwin14.4.0

julia> @time include("test/linalg/triangular.jl");
 144.674 seconds      (87071 k allocations: 7096 MB, 1.50% gc time)

julia> @time include("test/linalg/triangular.jl");
   5.297 seconds      (18276 k allocations: 3696 MB, 18.79% gc time)
```
which is really sad: 2.5x slower in compile time and 1.36x slower in execution.

**Comment by ViralBShah** [comment]
This test did run to completion. 4800 seconds!

**Comment by tkelman** [comment]
On my win64 laptop it's nearly 1700 seconds for that test with LLVM 3.6.1. numbers and arrayops are about that long too. dates is 2300 seconds.

**Comment by yuyichao** [comment]
> On my win64 laptop it's nearly 1700 seconds for that test with LLVM 3.6.1.

Is it better for LLVM 3.3? (LLVM 3.6 isn't this bad on linux)

**Comment by tkelman** [comment]
Yes, much. Comparable timings to appveyor on my laptop with LLVM 3.3.
