### ISSUE TITLE
Pkg.test hangs after test on Windows

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#12348]
Hi,
the title says it all...After waiting for a while, this happens when you force it to quit:

``` Julia
julia> Pkg.test("Quaternions")
INFO: Testing Quaternions
INFO: Quaternions tests passed
ERROR: InterruptException:
 in _jl_spawn at process.jl:217
 in spawn at process.jl:360
 in open at process.jl:412
 in readbytes at process.jl:475
 in installed_version at pkg/read.jl:85
 in installed at pkg/read.jl:143
 in test! at pkg/entry.jl:733
 in test at pkg/entry.jl:740
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

``` Julia
julia> versioninfo()
Julia Version 0.4.0-dev+6226
Commit 2294863 (2015-07-25 11:34 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
Is this from a nightly? Running Julia from cmd, or msys2, or cygwin? `Pkg.test` does dependency resolution after it's finished (maybe it should be taught to skip that step when there's no `test/REQUIRE` file), so it's getting stuck calling git here.

**Comment by tkelman** [comment]
Okay now master won't be calling git any more for packages that don't have a `test/REQUIRE`, but still would be good to know what was happening here for those packages that do.

**Comment by tkelman** [comment]
reopen or leave a comment if this still happens - assuming no longer relevant with libgit2-based pkg?
