### ISSUE TITLE
using X loads a file called X

### ISSUE THREAD

**Issue by shashi** [JuliaLang/julia#12340]
file X (note: not X.jl):
```julia
println("foo")
```

Inside a repl in the same directory

```julia
julia> using X
foo
Warning: requiring "X" did not define a corresponding module.
```

This means that we cannot have an executable named `foo` for a module named `Foo` which does `using Foo` inside it. Worse on case insensitive file systems.

**Comment by SimonDanisch** [comment]
Also: #9007 #9079 #7256
