### ISSUE TITLE
Add new options for convert to allow/disallow accepting different input and invalids with replacement strings

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#12358]
Currently, there is a single `convert` method that allows conversion to `UTF8String` with a argument for a replacement string, but that is only defined for an input of `Vector{UInt8}`, and not from the very many different possible arguments to `convert(UTF8String, data)`.
There are other places in the code where a fixed replacement, `0xfffd`, is hard-coded.
1. There needs to be consistent handling for converting strings from vectors of code units (`UInt8`, `UInt16`, and `UInt32`) to the (current) 4 types of strings `ASCIIString`,`UTF8String`,`UTF16String`,`UTF32String`, that allows specifying the handling of `Modified UTF-8`, `CESU-8`, overly long encodings, and also whether invalid sequences should cause an exception, be replaced by a default replacement character (`0xfffd` for Unicode, `0x1a` [SUB] for ASCII), or replaced by a user supplied string.
2. This also needs to work with fixes for #11501 and #11502
3. As laid out in #11558, make sure only valid strings are produced (for security reasons and in the future performance reasons)

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaArchive/LegacyStrings.jl/issues/12.
