### ISSUE TITLE
RFC: New functor system using symbol-based specialization

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#12357]
This is partly inspired by the discussions in #12292 and #12322.

The `@generated` macro makes it much easier to generate specialized functions. Hence, I think it might be time for us to upgrade our functor system. So I wrote a small program for concept proof:

```julia
# functors specialized based on symbol
immutable SFunc{N,Sym} <: Base.Func{N} end

@generated function call{S}(f::SFunc{1,S}, x)
    :($(S)(x))
end

# a map function that takes advantage of specialized fun
function mymap(f::Function, x)
    if isgeneric(f) && is(f.env.module, Base)
        map(SFunc{1,f.env.name}(), x)
    else
        map(f, x)
    end
end

# Benchmark
function benchmark(X::Array, ntimes::Int)
    # warming
    map(abs2, X)
    mymap(abs2, X)
    abs2(X)

    # measuring
    gc()
    gc_enable(false)
    @time for i = 1:ntimes map(abs2, X) end
    @time for i = 1:ntimes mymap(abs2, X) end
    @time for i = 1:ntimes abs2(X) end
    gc_enable(true)
end
benchmark(randn(1_000_000), 10)
```
Result:
```
 444.635 milliseconds (20000 k allocations: 381 MB)
  46.907 milliseconds (20 allocations: 78126 KB)
  49.847 milliseconds (20 allocations: 78126 KB)
```

So, it looks like it can dramatically improve the performance of many higher-level functions (e.g. `map`, `reduce`, `broadcast`, etc), making their performance on par with manually specialized ones, without even changing the external interface. Also, a big advantage of this as opposed to the current system is that it allows arbitrary named function to be used (instead of just a prescribed list of functions).

I am proposing:
- Introduce the new functor system with a PR (I can do this).
- Have the operation-dependent promotion (#12292) depend on the new functor. 

I think the utility of this specialized functor system is far beyond better type promotion. 

By keeping `Func{N}` as an abstract type, and define a bunch of type alias like below, most of the client codes that depend on old functors would still be working as expected. 
```julia
typealias AddFun SFunc{2, :+}
typealias AbsFun SFunc{1, :abs} 
# ...
```

cc: @timholy

**Comment by malmaud** [comment]
I'm not advocating one way or the other, but is there a discussion somewhere about the relative merits of this approach vs something like [FastAnonymous](https://github.com/timholy/FastAnonymous.jl)?

**Comment by yuyichao** [comment]
Would this basically put all functors in the same namespace? How would functions in different modules be separate from each other?

**Comment by lindahua** [comment]
I think both ways can co-exist, and they have respective merits in different cases. 

An important advantage of functors is that they can be passed around. Like:
```julia
function foo(f::Func)
    # ...
    bar(f)
    # ...
end
```

While the macro in `FastAnonymous` is good for anonymous functions, e.g. `(x, y) -> f(x) + g(y)`, etc, which cannot be easily specialized as functors.

**Comment by lindahua** [comment]
@yuyichao It is mainly targeting the generic functions in Base (or use within the same module). This already increases the flexibility & convenience a lot.

For more complicated situation, one can still define a sub-type of `Func{N}` (I think we should keep `Func` as an abstract type).

**Comment by yuyichao** [comment]
IMHO, this would be a very confusing API and similar thing could be implemented within a module without too much effort if someone really need it.

I think it would be better to just property finish https://github.com/JuliaLang/julia/pull/10269 instead of introducing something temporary.

**Comment by yuyichao** [comment]
Or more general what Jeff mentioned in the JuliaCon talk, which is basically this https://github.com/JuliaLang/julia/pull/10269#issuecomment-75389370

**Comment by lindahua** [comment]
@yuyichao This is not something new. We already have a bunch of functors like `AddFun` in Base (see `base/functors.jl` also)

This should be considered as improvement of existing things instead of introducing new things.

The compiler optimization to support specialised lambda is fundamental, but it takes time to work out. In the meantime, having a more flexible functor system should not hurt.

**Comment by yuyichao** [comment]
I don't necessarily disagree with making functor wrappers for Base functiors if people find it necessary. What I don't like is a way to wrap functions that looks generic but is really not. This will confuse a lot of people.

I think something like the following would be fine to have in a package if it is not already there.

```julia
macro wrap_func(fname)
    @gensym ftype
    quote
        type $ftype
        end
        Base.call(::$ftype, args...) = $fname(args...)
        $ftype()
    end
end
```

And then people can basically do

```julia
f(...) = ...

const functor_f = @wrap_func f
```

and use `functor_f` whereever a callable is expected

**Comment by andreasnoack** [comment]
Some of it might not be so far away. I don't understand the deepper complications in all this, but you can already now do
```jl
julia> immutable ⊕ end

julia> call(::Type{⊕}, x, y) = x + y  

julia> 2 ⊕ 2
4

julia> let
       x = randn(10^8)
       @time map(+, x, x)
       @time map(⊕, x, x)
       @time map(Base.AddFun(), x, x)
       end;
   3.927 seconds      (300 M allocations: 5341 MB, 18.55% gc time)
 452.272 milliseconds (8 allocations: 763 MB, 0.43% gc time)
 459.672 milliseconds (8 allocations: 763 MB, 0.15% gc time)
```
Unfortunately my choice of unicode operator https://en.wikipedia.org/wiki/%E2%8A%95 is not getting rendered correctly here

**Comment by yuyichao** [comment]
So in another word, if you just want to make it easier to write such a functor wrapper, I think a `macro` would be equally good.

If you want to make it easier for users to wrap their own functions, something that respect the scope would be better.

**Comment by timholy** [comment]
@yuyichao, that's basically how FastAnonymous works. (FA also analyzes the expression for any out-of-scope variables and creates fields in the type for them.)

Since expressions can't be parameters, unfortunately `SFunc{1,MyModule.foo}` doesn't work. For various devious reasons, FA uses a pointer to the function's AST; here one could use `pointer_from_objref(MyModule.foo)` (and convert it back with `unsafe_pointer_to_objref` within the generated function), although this wouldn't generalize to multiple processes.

Probably a better hack :smile: would be to use the serializer:
```
SFunc(N, f::Function) = SFunc{N, tuple(takebuf_array(serialize(IOBuffer(), f))...)}()
```
and use `deserialize` in the `@generated` function.

Having said all this, I think that there are two key issues:
- is the Functor system only an internal interface? If so, portability across modules may not be crucial.
- some folks wish to avoid having too many `@generated` functions in Base.

The latter may be a reason to avoid doing this, since it's possible we'll have an even better system in the not-too-distant future.

**Comment by lindahua** [comment]
I understand the concern about the namespace. A less confusing way might be to make it clear that it is only for wrapping base functions. 

```julia
# wrapper type to encapsulate a function in Julia base as a typed functor
immutable SBaseFunc{N, Sym} end

@generated function call{S}(f::SBaseFunc{1,S}, x)
    :(Base.$(S)(x))
end
```

**Comment by lindahua** [comment]
@timholy I think the `SFunc{N, Sym}` here is more or less the same as the `GenericNFunc` you introduce in #12292.

I don't mind just having a predefined list of common functors and waiting for #10269 to sort out. However, we should not introduce duplicated functor types, each for a different purpose.

**Comment by StefanKarpinski** [comment]
For what it's worth, I'm pretty sure that @JeffBezanson's plan for making higher order functions faster is to make them something like functors, so I have to wonder if it's worth doing this or better to wait for that.

**Comment by lindahua** [comment]
Ok, let's just stay with a small list of predefined functors for now, and wait for the genuine support of specialized functions.

**Comment by JeffBezanson** [comment]
Yes, I've been thinking hard about this, and this can clearly be generalized and made part of the language. Will post something soon...

**Comment by JeffBezanson** [comment]
Posted here: https://github.com/JuliaLang/julia/issues/11452#issuecomment-125843759
