### ISSUE TITLE
LLVM error on quitting the REPL on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12361]
Upon quitting the repl, I get this llvm error on arm.

````
julia> <ctrl-d>
julia: /home/viral/julia/deps/llvm-3.6.1/lib/IR/Verifier.cpp:2853: bool llvm::verifyFunction(const llvm::Function&, llvm::raw_ostream*): Assertion `!F.isDeclaration() && "Cannot verify external functions"' failed.

signal (6): Aborted
Aborted (core dumped)
````

**Comment by vtjnash** [comment]
fix in https://github.com/JuliaLang/julia/commit/8a1a21f90af194d10cfd33569872c8eb57a1dc49 needs to be moved to master

**Comment by ihnorton** [comment]
I'm seeing this on x86_64/linux when started with `julia -p4`. Cherry-picked in #12562
