### ISSUE TITLE
What reason is different result, when I change R code to julia code? Thank you

### ISSUE THREAD

**Issue by meibujun** [JuliaLang/julia#12362]
#####R code
f=c(0.5,0.5)
n.al <- length(f)
P.1 <- P.2 <- array(0,dim=rep(n.al,4))
    for(a2 in 1:n.al) for(a1 in 1:n.al)
    for(a3 in 1:n.al) for(a4 in 1:n.al)
    {
        if (a1==a3 & a2==a4)
        {
            P.2[a1,a2,a3,a4] <- f[a1]*f[a2]
            P.1[a1,a2,a3,a4] <- f[a1]*f[a2]*(f[a1]+f[a2])/2
        }
        if (a1==a3 & a2!=a4)
        {
            P.1[a1,a2,a3,a4] <- f[a1]*f[a2]*f[a4]/2
        }
        if (a1!=a3 & a2==a4)
        {
            P.1[a1,a2,a3,a4] <- f[a1]*f[a3]*f[a2]/2
        }
    }
#####julia code 	
f=Array(Float64,1,2)
f[:,:]=0.5
p1=Array(Float64,nal,nal,nal,nal)
p2=Array(Float64,nal,nal,nal,nal)
p1[:,:,:,:]=0.0
p2[:,:,:,:]=0.0
    for (a2 = 1:nal)  for (a1 = 1:nal)
	for (a3 = 1:nal)  for (a4 = 1:nal)
	   if (a1==a3 & a2==a4)
	      p2[a1,a2,a3,a4] = f[a1]*f[a2]
		  p1[a1,a2,a3,a4] = f[a1]*f[a2]*(f[a1]+f[a2])/2.0
	   end
	   
	   if (a1==a3 & a2!=a4)
	      p1[a1,a2,a3,a4] = f[a1]*f[a2]*f[a4]/2.0
	   end
	   
	   if (a1!=a3 & a2==a4)
	      p1[a1,a2,a3,a4] = f[a1]*f[a3]*f[a2]/2.0
	   end
	end end
	end end

**Comment by meibujun** [comment]
#####julia code 	
f=Array(Float64,1,2)
f[:,:]=0.5
p1=Array(Float64,nal,nal,nal,nal)
p2=Array(Float64,nal,nal,nal,nal)
p1[:,:,:,:]=0.0
p2[:,:,:,:]=0.0
    for (a2 = 1:nal)  for (a1 = 1:nal)
	for (a3 = 1:nal)  for (a4 = 1:nal)
	   if (a1==a3 & a2==a4)
	      p2[a1,a2,a3,a4] = f[a1]*f[a2]
		  p1[a1,a2,a3,a4] = f[a1]*f[a2]*(f[a1]+f[a2])/2.0
	   end
	   
	   if (a1==a3 & a2!=a4)
	      p1[a1,a2,a3,a4] = f[a1]*f[a2]*f[a4]/2.0
	   end
	   
	   if (a1!=a3 & a2==a4)
	      p1[a1,a2,a3,a4] = f[a1]*f[a3]*f[a2]/2.0
	   end
	end end
	end end

**Comment by meibujun** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13168353/8949724/9361979e-357c-11e5-97e6-ec609f7899ba.png)

**Comment by ihnorton** [comment]
This is not the right place for a question like this. Please use julia-users mailing list or Stackoverflow.

**Comment by tkelman** [comment]
x-ref https://groups.google.com/forum/#!topic/julia-users/p7KSa8-m5ng
