### ISSUE TITLE
isapprox broken on large numbers

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#12375]
I was writing some tests for isapprox and made the following horrible discovery:

```
isapprox(1e17, 1)
true
```

The issue lies in the default tolerances:
```
import Base.rtoldefault
rtoldefault(1e17, 1)
2.5198420997897464
```
More generally numbers larger then 5e16 are close to everything by default, since 
```
rtoldefault(5e16, 1)
2.0
```

Julia Version 0.4.0-dev+5491
Commit cb77503 (2015-06-21 09:45 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by stevengj** [comment]
I wish this function defaulted just to something like `isapprox{T<:FloatingPoint}(x::T,y::T) = abs(x - y) <=(abs(x) + abs(y)) * sqrt(eps(T))`.

**Comment by stevengj** [comment]
cc @jiahao, @alanedelman

**Comment by stevengj** [comment]
My basic problem with the current implementation is that `rtoldefault` and `atoldefault` seem wrong (they are dimensionally incorrect, i.e. they have the wrong units):

* `rtoldefault` is a *relative* tolerance, so it should be dimensionless.  The current definition, `cbrt(max(eps(x), eps(y)))`, has the cube root of the dimensions of `x` or `y`, which is wrong.  It should be `cbrt(max(eps(typeof(x)), eps(typeof(y))))`, assuming you want 1/3 of the digits.

* `atoldefault` is currently `sqrt(max(eps(x), eps(y)))`.  This is also dimensionally incorrect, because it has the units of the square root of `x` or `y`.   I think the only meaningful *default* absolute tolerance we can use is *zero*, since a nonzero absolute tolerance needs to come from information *outside* of `x` or `y`.

**Comment by jiahao** [comment]
I'd be happy to get rid of `isapprox` entirely. The use cases are really application specific and don't generalize well.

FWIW Knuth defines two approximate floating point comparisons  based on a (unspecified) threshold ϵ relative to the fr-exponent: ~ for "approximately equal to" and ≈ for "essentially equal to".

![screen shot 2015-07-29 at 5 06 07 pm](https://cloud.githubusercontent.com/assets/1732/8969906/4af837c2-3614-11e5-9b50-b3bfb265942c.png)

Ref: TAoCP 2/e, Vol. 2, p. 218

GSL implements ~ in [gsl_fcmp](https://www.gnu.org/software/gsl/manual/html_node/Approximate-Comparison-of-Floating-Point-Numbers.html).

**Comment by jiahao** [comment]
I should have read on, for on the next page, Knuth recommends an ϵ based on wanting the associativity of floating point multiplication to hold under ≈:

![screen shot 2015-07-29 at 5 12 38 pm](https://cloud.githubusercontent.com/assets/1732/8970033/3716882a-3615-11e5-812a-b778e4e1fccc.png)

**Comment by jiahao** [comment]
If we use Knuth's definition, then we get `rtoldefault = 64.00000000000001` (modulo possible sloppiness with factors of 2), which is not too far from

```jl
julia> Base.atoldefault(1e17,1)
4.0
```

**Comment by pao** [comment]
The original default tolerances discussion (for background, though probably not too enlightening) is in https://github.com/JuliaLang/julia/pull/652.

**Comment by stevengj** [comment]
@pao, the current tolerances are dimensionally incorrect (they scale incorrectly with `x` and `y`), so they are just unacceptable.

@jiahao, it seems to me Knuth's tolerance is too strict to be commonly useful as defaults for `isapprox`; I don't think he's recommending it for general usage, just for analyzing associativity.

My feeling is that sqrt or cbrt is about right as a default: if you've lost more than 1/2 or 2/3 of your digits, then you probably need to go to higher precision.   Whereas losing 1/3 of your digits is often acceptable.

**Comment by jiahao** [comment]
I like the idea of setting `atol = 0.0` and `rtol = √eps(promote_type(typeof(a), typeof(b))` as defaults.

**Comment by stevengj** [comment]
(And probably `≈` should be a synonym for `isapprox`.)

**Comment by simonbyrne** [comment]
Only problems I can see are the boundaries (subnormals or Infs). Other than that, +1.

**Comment by pao** [comment]
> the current tolerances are dimensionally incorrect (they scale incorrectly with x and y), so they are just unacceptable

I made no claim to the contrary.

**Comment by stevengj** [comment]
See also #12472 for further developments.
