### ISSUE TITLE
problems with cumsum!

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/julia#12384]
`cumsum!` does not do what the documentation says:
```julia
x=[1:5]
y=zeros(x)
cumsum!(y,x)
```
gives the following error message:
```
ERROR: `cumsum!` has no method matching cumsum!(::Array{Int64,1}, ::Array{Int64,1})
```
even though the [documentation](http://julia.readthedocs.org/en/release-0.3/stdlib/arrays/#Base.cumsum!) for julia 0.3 says this should be possible.

It looks like the right `cumsum!` is not exported:
```julia
methods(cumsum!)
```
shows
```
# 5 methods for generic function "cumsum!":
cumsum!{T}(B,A::AbstractArray{T,1},axis::Integer) at multidimensional.jl:144
cumsum!{T}(B,A::AbstractArray{T,2},axis::Integer) at multidimensional.jl:144
cumsum!{T}(B,A::AbstractArray{T,3},axis::Integer) at multidimensional.jl:144
cumsum!{T}(B,A::AbstractArray{T,4},axis::Integer) at multidimensional.jl:144
cumsum!{T,N}(B,A::AbstractArray{T,N},axis::Integer) at cartesian.jl:100
```
I'm using julia 0.3.11:
```
Julia Version 0.3.11
Commit 483dbf5 (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by KristofferC** [comment]
Just to point out, the failing example works on master.

**Comment by tkelman** [comment]
If anyone can do a bisect (or github search) and identify the commit that fixed this, we could have a look at possibly backporting it, if it's small and non-breaking. We may be too close to 0.4 for another release of 0.3 to be worth the trouble though. Depends whether or not a substantial number of good backporting candidates get identified.

**Comment by StefanKarpinski** [comment]
I do think we should continue doing 0.3 maintenance releases for a while, if we can.

**Comment by tkelman** [comment]
That's fair. It's pretty low-effort, but if we're going to keep maintaining 0.3, then once we branch for release-0.4 we should split the "backport pending" labels to "backport pending 0.3" and "backport pending 0.4." In fact I'll change it to "backport pending 0.3" right now.

**Comment by StefanKarpinski** [comment]
Good thought, @tkelman.
