### ISSUE TITLE
sparse constructor misbehaving on master

### ISSUE THREAD

**Issue by gragusa** [JuliaLang/julia#12397]
In v.0.3.10

```
julia> sparse([], [], [1], 0, 0, vcat)
0x0 sparse matrix with 0 Int64 entries:
```

In 0.4.0-dev+6402

```
julia> sparse([], [], [1], 0, 0, vcat)
ERROR: MethodError: `sparse` has no method matching sparse(::Array{Any,1}, ::Array{Any,1}, ::Array{Int64,1}, ::Int64, ::Int64, ::Function)
Closest candidates are:
  sparse(::Any, ::Any, ::AbstractArray{T,1}, ::Any, ::Any)
  sparse(::Any, ::Any, ::Number, ::Any, ::Any, ::Union{Base.Func{N},Function})
  sparse(::Any, ::Any, ::AbstractArray{Bool,1}, ::Any, ::Any)
  ...

**Comment by jiahao** [comment]
This is yet another manifestation of `[]` being `None[]` on 0.3 and `Any[]` on 0.4, similar to #12271

**Comment by gragusa** [comment]
Yes, indeed:

On  0.4.0-dev+6402
```
julia> sparse(Int[], Int[], [1], 0, 0, vcat)
0x0 sparse matrix with 0 Int64 entries:```

**Comment by jakebolewski** [comment]
This is because `Vector{None} <: Vector{Integer}`.  The `<: Integer` requirement will likely be relaxed in v0.5.

See also #12567

**Comment by Sacha0** [comment]
What should happen here?

That `sparse([], [], [1], 0, 0, vcat)` returns a `MethodError` seems appropriate, `Any` not being a subtype of `Integer`. Additionally, were the `Any[]`s passed in promoted to `T[]` where `T<:Integer`, shouldn't that call still fail as `sparse`'s first three arguments (`I`,`J`,`V`) must have equal length when they are vectors? Best!

**Comment by tkelman** [comment]
Yeah I think 0.3's `sparse` may have been a bit too permissive here. Closing, don't think there's a bug here.
