### ISSUE TITLE
Support FFT of split complex representation

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12398]
As shown by @simonster (https://github.com/simonster/StructsOfArrays.jl), Structure of Array is much easier to vectorize. Using `StructOfArrays(Complex64)` and `@simd` I can see a speed up of `>2x`. However, it seems that this is not very well supported by our fft API.

As @simonster suggested, I tried to implement FFT on `StructOfArrays` using `fftw_plan_gure64_split_dft`. The non-plan version works greet. However, I get SegFault when trying to use the plan interface. It seems that fftw assumes that the relative address between the real and complex part is fixed and therefore is not accessing the right address when I pass in a different array.

Is there a fftw interface that can be used to implement this?

@stevengj

**Comment by stevengj** [comment]
No, the split interface requires the relative address to be fixed.  Maybe `StructOfArrays` could convert a `Complex` array (internally) into a single real array of twice the length (the real parts followed by the imaginary parts), so that the relative address is fixed?

**Comment by yuyichao** [comment]
So why does `fftw_execute_split_dft` take 4 addresses instead of 2 then? Seems that two of them are redundant.

> Maybe `StructOfArrays` could convert a `Complex` array (internally) into a single real array of twice the length

It's possible but the interface would be much less flexible. (e.g. it won't be possible to push to the array)

**Comment by simonster** [comment]
I thought about making one big allocation and using that for all of the arrays in StructsOfArrays, which would give a fixed relative address. The problem is making sure that the big allocated buffer is only freed when no references to the individual arrays remain. Julia can do this in principle (arrays can handle sharing/ownership for `reshape`) but I don't think this is actually exposed outside of C.

If the field types are homogeneous, you can represent all the data in a single array and just add an offset. But I kind of like the generality of the current approach.

**Comment by stevengj** [comment]
@yuyichao, the offsets between the real and imaginary parts can be different for the input and output.  So four addresses (or two addresses and two offsets) are required.

**Comment by yuyichao** [comment]
Well, IIUC, four addresses are required for the plan function but then since the execute function assume a fixed offset between the real and imaginary part, it should only need two pointers. Maybe the execute function takes four pointers in order to be consistent with the plan function?

This is probably not a julia issue but it would be nice to mention this limitation in the fftw doc.

Anyway, while it is really nice to support independent split dft, when I tested it on my code, it does not perform as well as what it is now since the FFT seems slower this way and the left over SIMD enabled by this is not significant enough in my case.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaMath/FFTW.jl/issues/37
