### ISSUE TITLE
Move printing of "unhandled task errors" to a finalizer

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#12403]
Once a `task` has been waited upon, or its results fetched, it should be marked as handled even if there were no waiters at the time of task exit.

I'll submit a PR for this. Just adding it here so it doesn't get missed.

**Comment by JeffBezanson** [comment]
This might be better than the current situation, but my worry is that people who dislike the error will still be annoyed by it, and people who want the error will be upset that it depends on GC timing. The GC might not decide to collect a task until half an hour later.

**Comment by amitmurthy** [comment]
There are two separate issues here:

1. Printing of "unhandled task errors" - this can (possibly) be controlled by an environment variable.
2. The more important one is detecting when a task in error is unhandled. In the current model, if there are no waiters on a task at the time of failure it is deemed unhandled, irrespective of the fact that the task reference may still be held elsewhere and a `wait` called on it in the future.

**Comment by vtjnash** [comment]
Closed by https://github.com/JuliaLang/julia/pull/39518
