### ISSUE TITLE
fill(Foo(), dim)

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#12411]
When creating an array with `fill(Foot(),  dim)`, all elements refer to the same object (as mentioned in the documentation). For example, 

```julia
a = fill(Set{Int}(), 2)
push!(a[1], 1)
a
#2-element Array{Set{Int64},1}:
# Set{Int64}({1})
# Set{Int64}({1})
```

I find this behavior quite confusing. Unless there are strong reasons for the current behavior (I could not find any discussion on github), it seems to be `fill` should create an array of distinct elements.

**Comment by nalimilan** [comment]
See the discussion which prompted adding this mention in the docs: https://github.com/JuliaLang/julia/pull/8759

**Comment by matthieugomez** [comment]
Thanks
