### ISSUE TITLE
ARGS parsing regression

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#12410]
In current master, the following happens:
```bash
julia -e "@show ARGS" -x
# ARGS = UTF8String["-x"]
```
```bash
julia -e "@show ARGS" -xx
# ARGS = UTF8String["@show ARGS","-xx"]
```
In the second case I am surprised why `@show ARGS` shows up in `ARGS`. In 0.3, the behaviour is correct, containing `-x` and `-xx`, respectively.

---

Edit: In 0.4 there is `--` to separate args to the script from args to Julia, although `--` is not mentioned in the `julia -h` command line definition. What is the status of `--`?

**Comment by tkelman** [comment]
> What is the status of `--`?

Implemented but undocumented. #10726

**Comment by rened** [comment]
@tkelman ic, thanks. should it remain undocumented for 0.4? i could add it to the docs.

**Comment by tkelman** [comment]
No, it should definitely be documented. A PR would be welcome.

**Comment by jakebolewski** [comment]
Added some documentation in dae8094198cc1b6c75661e2
