### ISSUE TITLE
julia-mode: Keyword being recognized and affect indentation inside strings.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12419]
I think this is the wrong indentation I mentioned in https://github.com/JuliaLang/julia/issues/11510#issuecomment-109760684 that I saw before.

```julia
"""
for
    """

"
for
    "

"""
    for
    end
end
"""

"
    for
    end
end
"

"""
for
end
"""

"
for
end
"
```

**Comment by justbur** [comment]
Not sure if you agree, but I'd like it if indentation were "manual" in strings with newlines in them, meaning TAB always added four spaces and S-TAB always subtracted. What do you think?

**Comment by yuyichao** [comment]
I agree. It's too easy to accidentally write a keyword in a comment or doc string...

**Comment by justbur** [comment]
Also if you indent the whole buffer it shouldn't affect the indentation in multi-line strings at all in my opinion, because you may lose your intended layout. Anyway I added a commit for this.
