### ISSUE TITLE
Deprecation warnings consume crazy amounts of time and memory

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#12427]
Would be nice to mitigate this somehow. Example case - run `make -C test/perf sort`<sup>[1]</sup>, which compares a variety of algorithms including some from the SortingAlgorithms.jl package. That package has a few `int()` deprecation warnings when doing RadixSort (fixed in https://github.com/JuliaLang/SortingAlgorithms.jl/pull/13, so be sure to use tag v0.0.5 to reproduce this), and the perf tests run them enough times that my machine ends up swapping and hanging.

My understanding is that deprecation warnings collect a backtrace to avoid being thrown repeatedly, but is there some missing GC here that is causing them to be held onto indefinitely?

----

[1] which has apparently been broken since the new GC was merged, ref https://github.com/JuliaLang/julia/commit/7c8acce9fb73c3edb71bdd509b8f265c95ae7484#commitcomment-12482788, but I just fixed it so that's beside the point

**Comment by yuyichao** [comment]
The backtrace collection is very slow and I doubt there's much we can do about it now.

jl_lookup_code_address has a memory leak. I'll try to fix it.

**Comment by tkelman** [comment]
I think we already have at least one other "backtraces are slow" issue, so with #12433 I think we may as well close this?

**Comment by yuyichao** [comment]
The backtrace collection is actually not the step that's taking most of the time. Getting the debug info takes longer. Not sure if we can do much about retrieving the debug info (maybe caching the `DIContext` can help?). And maybe we can figure out whether this is the first caller without getting the symbol names?
