### ISSUE TITLE
Starting Julia on Windows fails if JULIA_HOME is set

### ISSUE THREAD

**Issue by veita** [JuliaLang/julia#12428]
OS: Windows 7
Install Julia 0.3.11. Set `JULIA_HOME=C:\devel\julia-0.3.11` as system environment variable.
Try to start Julia with the desktop link created by the setup.

-> Julia does not start.

The error message was `System image file "C:\devel\julia-0.3.11\../lib/julia/sys.ji" not found`.

**Comment by tkelman** [comment]
That variable is significant. If you're going to set it, it needs to be set to the location of the `julia.exe` executable, or things are going to break. That's also true on other platforms.

**Comment by tkelman** [comment]
We could still maybe use some docs on this and other significant environment variables.

**Comment by veita** [comment]
OK, this seems to be quite uncommon. Normally the home variables reference the installation directory, and the executables reside in a bin directory below (see e.g. `JAVA_HOME`, `GROOVY_HOME`, `SCALA_HOME`, `ERLANG_HOME`, or `R_HOME`).

**Comment by tkelman** [comment]
ref #9981
