### ISSUE TITLE
Pkg.build("Images") fails on Windows 10

### ISSUE THREAD

**Issue by stejin** [JuliaLang/julia#12430]
Julia version 0.3.11 on Windows 10 64bit

Pkg.build("Images") fails with below error messages

julia> Pkg.build("Images")
INFO: Building Images
At line:1 char:3
+ --help
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --help
+   ~~~~
Unexpected token 'help' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

INFO: Installing ImageMagick library
INFO: Attempting to Create directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads already created
INFO: Attempting to Create directory C:\Users\steffen\.julia\v0.3\Images\deps\usr\lib\x64
INFO: Directory C:\Users\steffen\.julia\v0.3\Images\deps\usr\lib\x64 already created
INFO: Attempting to Create directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads already created
INFO: Downloading file http://www.imagemagick.org/download/binaries/ImageMagick-6.9.1-10-Q16-x64-dll.exe
INFO: Done downloading file http://www.imagemagick.org/download/binaries/ImageMagick-6.9.1-10-Q16-x64-dll.exe
INFO: Attempting to Create directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads
INFO: Directory C:\Users\steffen\.julia\v0.3\Images\deps\downloads already created
INFO: Downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/innounp.exe
INFO: Done downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/innounp.exe
INFO: Changing Directory to C:\Users\steffen\.julia\v0.3\Images\deps\downloads
Signature detected: Inno Setup Setup Data (5.5.6) (u)
This is not directly supported, but i'll try to unpack it as version 5500
; Version detected: 5506 (Unicode)
Unpacking failed. This version is not supported.
===================================================[ ERROR: Images ]====================================================

failed process: Process(`innounp.exe -q -y -b -e -x '-dC:\Users\steffen\.julia\v0.3\Images\deps\usr\lib\x64' ImageMagick
-6.9.1-10-Q16-x64-dll.exe`, ProcessExited(1)) [1]
while loading C:\Users\steffen\.julia\v0.3\Images\deps\build.jl, in expression starting on line 82

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: Images had build errors.

 - packages with build errors remain installed in C:\Users\steffen\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("Images")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

**Comment by tkelman** [comment]
Please file issues for packages at the packages' repository, not base Julia. This is known and we could use some help in fixing it, see https://github.com/timholy/Images.jl/issues/316.
