### ISSUE TITLE
Define / for factorizations

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#12436]
For a factorization `c` and a matrix `x`,  `c \ x` works but `x / c` returns an error:

``` julia
x = rand(10, 10)
c = cholesky!(x'x)
x / c
#> ERROR: `/` has no method matching /(::Array{Float64,2}, ::Cholesky{Float64})
```

Updated by andreasnoack: This is a general issue for `Factorization`. The status is
- Dense
  - [x] LU
  - [x] Cholesky
  - [ ] QRCompactWY
  - [ ] QRPivoted
  - [ ] BunchKaufman
- Sparse
  - [ ] CHOLMOD.Factor
  - [ ] UmfpackLU
  - [ ] SPQR.Factorization

For most of the dense factorizations except `BunchKaufman`, it should be fairly easy to add `A_rdiv_B!` methods. The sparse factorizations migh be slightly more complicated and/inefficient.

**Comment by jakebolewski** [comment]
@andreasnoack isn't this just adding` A_rdiv_B*` methods to the Cholesky type?

**Comment by andreasnoack** [comment]
This would be great but is not required for 0.5.

**Comment by ViralBShah** [comment]
Of course, if we get PRs, we will take them for 0.5.

**Comment by Sacha0** [comment]
Unlikely to receive attention prior to 0.6. Best!

**Comment by ViralBShah** [comment]
Note the Cholesky example in OP works, but the others still need more work.

**Comment by ViralBShah** [comment]
Closing as old.
