### ISSUE TITLE
Feature request: operator `.===` and `.!==`

### ISSUE THREAD

**Issue by Sisyphuss** [JuliaLang/julia#12446]
These two operators could be used with arrays containing `NaN`.

They provide a uniform interface for both Integer comparison and FloatingPoint comparison.

**Comment by jiahao** [comment]
It is still possible for `[NaN] .!== [NaN]` to be true because `NaN .!== NaN` in general. There are multiple floating point representations of `NaN` which can be distinguished by their bits, and therefore cannot be `===` in the _egal_ sense of having no program be able to tell the difference.

**Comment by ihnorton** [comment]
(@Sisyphuss I'll let someone else comment on the issue itself, but just to let you know I re-titled as "request" because "demanding" is too strong here)

**Comment by Sisyphuss** [comment]
@ihnorton "request" is the exact word I was looking for but couldn't find. Thank you for your correction!

**Comment by Sisyphuss** [comment]
@jiahao You are right. I didn't know that.

I tried the following codes:
```Julia
> NaN === NaN
true

> 0/0 === NaN
false

> bits(NaN)
"0111111111111000000000000000000000000000000000000000000000000000"

> bits(0/0)
"1111111111111000000000000000000000000000000000000000000000000000"
```

I expected to use `NaN` as a missing value. Although it worked for my purpose, it may still contain potential risk. It seems to me that `Nullable` is the only "correct" way to handle missing values. And we should warn people not to use `===` with `NaN`.

**Comment by simonster** [comment]
At least for now, `isequal` is true for different NaNs, so you can also use that.

The inequality by `===` of different NaNs is sometimes a feature, if you want to distinguish missing values from NaN results from intermediate computations.

**Comment by Sisyphuss** [comment]
Thanks @simonster, your point of view is very helpful. 

By the way, do you also approve the use of `.===` and `.!==`. And I think these operators are not hard to implement.

**Comment by nalimilan** [comment]
@Sisyphuss Could you provide an example where they would be useful? Usually, I think one would only use `===` for single objects. This is a very specific operator, as can be seen from the fact that it doesn't really suit your needs with `NaN`.

**Comment by Sisyphuss** [comment]
@nalimilan the `.===` in the following code cannot be replaced by `.==`.

```julia
function countMissing(x, miss)
  return sum(x.===miss)
end

countMissing([1,0,2], 0)
countMissing([1,1, NaN, 2,2])
```

**Comment by nalimilan** [comment]
@Sisyphuss Yes, but as you noted above this code isn't great as it won't catch all kinds of `NaN`. Better use `DataArrays`/`NullableArrays` for that.

**Comment by Sisyphuss** [comment]
I just found there are only two `NaN` representations: one is positive, the other is negative.

Is it right?

**Comment by simonster** [comment]
No, there are 2^53-2 different NaNs for a Float64.

**Comment by Sisyphuss** [comment]
Ah, yes, should count the mantissa and minus the two `Inf`s. Thanks @simonster !

**Comment by J-Sarnoff** [comment]
for clarification

NaNs come in two flavors, signaling and quiet (SNaNs and QNaNs).
For each of Float64, Float32, Float16 there are corresponding NaNs.
When there is Float128, there will be corresponding NaNs.

Julia uses names: NaN64 (or NaN), NaN32, NaN16 for SNaNs and QNaNs.
Given a NaN, the most significant (explicit) bit of the significand
is set to 1 for a QNaN and cleared to 0 for a SNaN [±Inf is not SNaN].

A NaN has all bits of the biased exponent set to 1. A QNaN also has
the msb of the significand set to 1.  A SNaN has that least one other
bit (not the msb) of the significand set to 1 [so not ±Inf{16,32,64}].

isnan(x) is true iff an AbstractFloat x is a NaN (any SNaN or QNaN).
isnan(x) works with NaNs given various payloads.

paraphrasing IEEE 754-2008

All floating-point ops shall support SNaNs and QNaNs. While the standard
does not mandate specific uses for SNaNs or QNaNs, SNaNs may be used to
mean an uninitialized variable or for enhancements like representing
"complex-affine infinities." The use of QNaNs use is to be determined at
"the implementer's discretion" and may offer "retrospective diagnostic
information .." from missing or invalid values.

SNaNs are for use when signaling an invalid operation.  Operations on
QNaNs should preserve QNaN payload information as much as possible.
So QNaN op Float, Float op QNaN propogate the QNaN. 

from IEEE 754 mail archives

QNaN1 op QNaN2 --> QNaN
                   QNaN might be determined by:
always choosing QNaN1 or always choosing QNaN2  (fastest, least informative)
logical or of the two payloads (set-like, fast, somewhat informative)
max() or min() of the two signed payloads (slower, more informative)

**Comment by Sisyphuss** [comment]
@J-Sarnoff thanks! It's clearer now.

**Comment by KristofferC** [comment]
Think this works with dot fusion now.
