### ISSUE TITLE
using a submodule within a module hangs Julia

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12443]
```jl
module Foo
module Bar
end
using Bar
end
```
I realize that if you are going to do `using Bar`, you might arguably not want a module for `Bar` at all, but at the same time this is not a completely crazy thing to do (e.g. to hide some functions of Bar inside Bar).  Hanging Julia does not seem like a great behavior.

~~(Reproduced in both `master` and Julia 0.3.x.)~~  Hold on, it just disappeared for me in `master`, though I can still reproduce it in Julia 0.3.8...

**Comment by stevengj** [comment]
Oh, never mind, I had a file `bar.jl` in my directory.  Damn case-insensitive filesystem.

Now it just gives an error.

**Comment by ScottPJones** [comment]
Using windows?  If Mac, I minimized this sort of problem by making a case-sensitive Julia sparse bundle, added it to my log-in items, and then symlinked /j to /Volumes/Julia.  It's also nicer for my Vagrant VMs.
