### ISSUE TITLE
Enable execution of ccall in different threads

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#12455]
libuv provides a thread pool and a simple way to execute your requests in different threads from that pool.

This feature will be quite useful if we could have a a `ccall` like interface, say `ccall_spawnwait` that behaves exactly like `ccall` but runs in a different thread.

Implementing concurrent ODBC calls then becomes trivial. Based on information in  http://nikhilm.github.io/uvbook/threads.html#id1 and http://docs.libuv.org/en/latest/threadpool.html and the below modifications 

```

typedef void (* queue_cb_t)(int);
struct work_baton {
    uv_work_t req;
    queue_cb_t work_func;
    queue_cb_t notify_func;
    int idx;
};

#include <sys/syscall.h>
void jl_work_wrapper(uv_work_t *req) {
    printf("tid %d\n", syscall(SYS_gettid));
    struct work_baton *baton = (struct work_baton*) req->data;
    baton->work_func(baton->idx);
}

void jl_work_notifier(uv_work_t *req, int status) {
    printf("Finished %d\n", status);
    struct work_baton *baton = (struct work_baton*) req->data;
    baton->notify_func(baton->idx);
    free(baton);
}

DLLEXPORT int jl_queue_work(void * work_func, void * notify_func, int idx)
{
    struct work_baton *baton = (struct work_baton*) malloc(sizeof(struct work_baton));
    baton->req.data = (void*) baton;
    baton->work_func = work_func;
    baton->notify_func = notify_func;
    baton->idx = idx;

    uv_queue_work(jl_io_loop, &baton->req, jl_work_wrapper, jl_work_notifier);

    return 0;
}
```

the below code block runs fine.

```
max_threads=128
cond_list = [Nullable{Condition}() for i in 1:max_threads]
s=Base.Semaphore(max_threads)

foo(x) = (ccall(:sleep, Void, (Cint,), x%10); return)

function notify_fun(idx)
    global cond_list
    notify(get(cond_list[idx]))
    return
end

function exec_work_fun(work_cf)
    global cond_list
    global s

    Base.acquire(s)
    idx = findfirst(x->isnull(x), cond_list)
    cond_list[idx] = Nullable{Condition}(Condition())

    ccall(:jl_queue_work, Void, (Ptr{Void}, Ptr{Void}, Cint), work_cf, cfunction(notify_fun, Void, (Cint,)), idx)

    wait(get(cond_list[idx]))
    cond_list[idx] = Nullable{Condition}()
    Base.release(s)
end

for x in 1:10
    @async exec_work_fun(cfunction(foo, Void, (Cint,)))
end
```

An effective interface, I believe would be a `ccall_spawnwait` that
- runs the ccall in a different libuv managed thread
- waits for the call to finish before returning, but does not block the main libuv event loop.

If that is a non-trivial implementation, then a safe way of calling a thunk that just wraps the actual `ccall` from another thread will be enough for designing a workable solution (I think).

Exposing this kind of functionality (along with libuv's synchronization primitives) will also enable a better integration with libraries that otherwise will not integrate will with libuv's event loop, for example MPI.

I can explore this further. Any pointers would be helpful.

**Comment by StefanKarpinski** [comment]
+1. I did a hacky version of this that used ZMQ because I couldn't get the `libuv` async send business working correctly and it wasn't a pressing issue at the time, but this would be very helpful for interacting with blocking C APIs.

**Comment by StefanKarpinski** [comment]
Relevant code from that experiment [here](https://gist.github.com/StefanKarpinski/839b236b173855605c4b). The stuff with ZMQ should not be used, but this part could be:

```jl
immutable CFunction{n}
    pointer::Ptr{Void}
    rettype::Type
    argtypes::NTuple{n,Type}
end

macro wrapper(f, rettype, argtypes...)
    f = isa(f,Symbol) ? Meta.quot(f) : f
    wrap = :(function wrapper(ptr::Ptr{Void}) p = ptr end)
    body = wrap.args[2].args
    args = Symbol[]
    for (i,T) in enumerate(argtypes)
        arg = symbol("arg$i")
        push!(body, :($arg = unsafe_load(convert(Ptr{$T}, p))))
        push!(body, :(p += sizeof($T)))
        push!(args, arg)
    end
    push!(body, :(ret = ccall($f, $rettype, ($(argtypes...),), $(args...))))
    push!(body, :(unsafe_store!(convert(Ptr{$rettype}, ptr), ret)))
    push!(body, :(return sizeof($rettype)))
    :(let
        $wrap
        f = cfunction(wrapper, Int, (Ptr{Void},))
        CFunction(f, $rettype, ($(argtypes...),))
    end)
end
```

It takes a C function name (or pointer) and its signature and generates a C-callable Julia wrapper with signature `void* --> int` that will invoke that function on arguments encoded via pointers to arguments in a buffer, loading the C values from their pointers and setting them up for the C call. This deals with the fact that C had different calling conventions for different functions – this essentially makes that calling convention uniform on the calling side, making it easy to invoke any C function: just fill the buffer with a pointer to the function you want to call and pointers to its arguments.

**Comment by yuyichao** [comment]
Do we need to be more careful since we cannot touch any julia runtime in a different thread?

**Comment by StefanKarpinski** [comment]
The idea is that you can call C functions in another thread, not Julia functions. I made sure that my wrapper generator emits nothing that might cause code generation or garbage collection.

**Comment by ScottPJones** [comment]
Any way of blocking C threads from trying to call back into Julia?

**Comment by yuyichao** [comment]
@StefanKarpinski I see. So this is just the part that generate a function for calling from C, seems fine then.

I was more thinking about doing the `cconvert` and `unsafe_convert` on the julia arguments and keep them alive long enough so that the c function can use them.

**Comment by StefanKarpinski** [comment]
> Any way of blocking C threads from trying to call back into Julia?

There's no way to do that in general – just don't call code that calls back into Julia.

**Comment by ScottPJones** [comment]
Ok, seems like a nice step forward, until the day Julia can really do threads, just need docs on limitations.
