### ISSUE TITLE
Tighter constructor definition for Dict

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#12451]
On current master the following throws unhelpful errors:
```jl
julia> Dict(1)
ERROR: BoundsError
 in call at ./dict.jl:389
 in call at dict.jl:435

julia> Dict([1,2,3])
ERROR: BoundsError
 in call at dict.jl:389
 in call at dict.jl:435
```
The solution is to make the type of `kv` in `dict.jl:435`:
```jl
Dict(kv) = dict_with_eltype(kv, eltype(kv))
```
tighter. Don't know enough about what parameter values are acceptable for a Dict constructor to do it myself...

**Comment by simonster** [comment]
I don't think the constructor can be tightened if we still want it to accept any iterator that yields pairs, but it could throw a better error message.
