### ISSUE TITLE
Subsume put! into push!?

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#12469]
Now that `RemoteRef`s can store an array of values, it might sense to just eliminate `put!` and instead `push!` values into RemoteRefs and Channels.

**Comment by jakebolewski** [comment]
@amitmurthy I think we want to retain `put!` for `RemoteRef`'s but adding `push!` to channels seems like a good idea.

**Comment by amitmurthy** [comment]
The `Channels` API mirrors the `RemoteRef` API. Also RemoteRef's point to `AbstractChannels`. Any concrete implementation of an `AbstractChannels` must implement `put!`, `take!`, `fetch`, `isready` and `wait`. We can look at renaming `put!`, `take!` and `fetch`, but we should continue to keep the `Channel` API in sync with `RemoteRef`.

**Comment by jakebolewski** [comment]
is there any way to push an iterable to a channel without having to splat it?

**Comment by amitmurthy** [comment]
No.

I think I misunderstood your comment. Yes, we can add `push!` while retaining `put!`.

**Comment by malmaud** [comment]
I think it would make sense to do so, since from the user's point of view a channel is just a deque with special blocking semantics.

**Comment by malmaud** [comment]
Closed by https://github.com/JuliaLang/julia/pull/13538
