### ISSUE TITLE
sum(f, itr) over empty collection

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#12461]
Currently it fails:
```julia
sum(isnan,Float64[])
#ERROR: ArgumentError: reducing over an empty collection is not allowed
# in _mapreduce at ./reduce.jl:137
# in sum at ./reduce.jl:242
```

Probably it would be more consistent to return zero (that is what `sum(Float64[])` does).
The same applies to `prod(f, ...)`.

**Comment by yuyichao** [comment]
It is very hard (if not impossible) to do this for a general function because there's no way to know what type it should return.

**Comment by alyst** [comment]
Oh, I see. So you would recommend using `mapreduce(f, +, 0, itr)` instead?
Or maybe it is possible to introduce the neutral element `z0` param to `sum(f,..)` like `mapreduce()` does (constrained to being zero and defaults to `0` (Int))?

**Comment by yuyichao** [comment]
That should work. I'm not familiar with the pattern so I don't have any specific suggestions.

> (constrained to being zero and defaults to 0 (Int))?

This would introduce a huge type instability for anything other than integer so it should fallback to what we have now if the parameter is not provided. (although only for callable type since the type inference will fail on it otherwise anyway...)

**Comment by JeffBezanson** [comment]
The error here is intentional.

For the specific example given, try `count(isnan, Float64[])` instead.

**Comment by ForceBru** [comment]
The error message "reducing over an empty collection is not allowed" seems misleading: reducing over empty collections is very much allowed:

```julia
julia> sum(identity, Float64[])
0.0
julia> sum(identity, Int64[])
0
julia> sum(isnan,Float64[], init=false)
false
julia> sum(isnan,Float64[], init=true)
true
julia> reduce(*, [], init=1)
1
```
