### ISSUE TITLE
jl_typename_str return undefined when argument is not a datatype

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#12464]
The api function [jl_typename_str](https://github.com/JuliaLang/julia/blob/master/src/jlapi.c#L81) is pretty simplistic and I believe this is probably now incorrect after the svec for unions change, and is at least part of the cause of waTeim/node-julia#17 In any event apparently calling this function crashes with a  segmentation violation when the type of the argument is a union.  This does not occur in 0.3.

**Comment by waTeim** [comment]
Update here.  The function itself doesn't crash, but name->name->name returns a value that causes a segfault when read.

**Comment by vtjnash** [comment]
what is the expected return value? only DataType's have a typename field, so calling it with some other type of object should arguably be an assertion failure.

**Comment by waTeim** [comment]
Hmm, here are a few possibilities if a union
1. "Union"
2.  null
3.  some variant similar to what's done [here](https://github.com/JuliaLang/julia/blob/master/src/builtins.c#L1424)

    jl_show_svec(out, ((jl_uniontype_t*)v)->types, "Union", "{", "}");

I don't like an assertion failure because in my mind that carries with it some assumption that the process has reached some wrong state (and can't proceed).

**Comment by yuyichao** [comment]
> Plus in julia.h unions are data types are they not?

No. It's a header for julia types and nothing except datatype is datatype. Notice that it is included for all other julia values as well.

**Comment by vtjnash** [comment]
note that in original issue, it was calling `jl_typename_str(jl_tparam0(jl_typeof(array)))`, but the parameters of types are not necessarily types at all, so doing comparison by name won't necessarily work.

the proper & robust way to compare objects is to do the same as you would in julia, using `jl_egal` (equivalent to `===`)
if you want to test their base types for equality (for example, `Array` in `Array{Any,1}`), then you can compare `type->name == type->name` (equivalent to `type.name == type.name`)
