### ISSUE TITLE
Should show of a Union be sorted on its types?

### ISSUE THREAD

**Issue by hayd** [JuliaLang/julia#12477]
*This came up when generating LightGraphs' documentation https://github.com/JuliaGraphs/LightGraphs.jl/commit/b47a60df4df3b371e3c958b028ddfa87a9274ac3#diff-147038b09e8f32dca070bcef5c502d68L9 (when I run `julia doc/build.jl` the Unions are in the other order to @sbromberger's machine).*

Note: that [show of Union uses `show_delim_array`](https://github.com/JuliaLang/julia/blob/a398bd817592d56f44814f44a92d76c05288ad34/base/show.jl#L73) which deals with circular references, so I guess it's not as simple/possible as using

```
sort!(map(string, x.types))
```
? (Although that works in my naive cases.)

**Comment by vtjnash** [comment]
not all types have a total canonical ordering (see sorted cache vs. linear cache in https://github.com/JuliaLang/julia/blob/master/doc/images/jltypes.svg), although I guess alphabetical order isn't too awful for the purposes of displaying them.

**Comment by JeffBezanson** [comment]
I think we'd rather keep the order undefined than allow code to rely on a particular order.

I don't think it's possible for a Union type to form a reference cycle. I guess we could consider sorting on display.

**Comment by hayd** [comment]
@jakebolewski any reason for the close?

> I guess we could consider sorting on display.

If sorting on display seems reasonable, I can put a PR together. (Not sorting the underlying types array, but the show-order.)

**Comment by jakebolewski** [comment]
It would be better to put together a PR

**Comment by hayd** [comment]
sure thing, see #12549.
