### ISSUE TITLE
Merge ipermute into permute?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#12470]
It looks like adding an argument `rev=false` to `permute` would be better than having a separate function. This would reduce namespace pollution, make `ipermute` easier to discover, and improve consistency with `sort`.

**Comment by StefanKarpinski** [comment]
I don't think `rev` is quite the right name, maybe `inv`? I like this approach better.

**Comment by StefanKarpinski** [comment]
Note that it is the implementation that is intro / up for grabs, not the decision.

**Comment by ViralBShah** [comment]
I personally like having `ipermute`, rather than stuffing it into `permute`.

**Comment by StefanKarpinski** [comment]
To play devil's advocate: both `permute!` and `ipermute!` just permute something, so should be implemented by the same function.

**Comment by kmsquire** [comment]
Yes, but the logic is different enough that the core needs to be written twice anyway.

**Comment by JeffBezanson** [comment]
I don't see what the big win is here. But I did come across `ipermutedims`, which looks like it should be deprecated to `permutedims(A, invperm(p))`.

**Comment by StefanKarpinski** [comment]
I kind of feel the same. It seems like a bit of a code/api smell that this is implemented internally as two separate functions which this selects between using a boolean argument.

**Comment by nalimilan** [comment]
Doesn't look like we're going to do this.
