### ISSUE TITLE
Race condition with timer signaling

### ISSUE THREAD

**Issue by prcamp** [JuliaLang/julia#12473]
On the nightly 0.4.0-dev+5612, Timer() was working as intended, but since 0.4.0-dev+6210 it is broken. 

Example:
Timer(x->println("hi"), 1, 0)

**Comment by vtjnash** [comment]
the problem is in the following code:

```julia
>  620 function Timer(cb::Function, timeout::Real, repeat::Real=0.0)
 621     t = Timer(timeout, repeat)
 622     @schedule begin
 623         while isopen(t)
 624             wait(t)
 625             isopen(t) && cb(t)
 626         end
 627     end
 628     t
 629 end
```

since the timer is non-repeating, the `isopen` test fails and the callback is never called

**Comment by lobingera** [comment]
May be the header could be changed to 'non-repeating timers are broken'.

**Comment by vtjnash** [comment]
> May be the header could be changed to 'non-repeating timers are broken'.

perhaps. the larger issue however is that having a conditional at https://github.com/JuliaLang/julia/commit/fe62c2efc2b96020ef066c60176892f29e6cd571#diff-ac5d350530574f3f82c860d1b963bc0aR624 incurs a race condition between the time that the timer is signaled, the time it is closed, and the time that this watcher got scheduled for execution. it's possible to create the same issues with repeating timers, the window of opportunity for failure is just much more obvious for single-shot timers.

**Comment by JeffBezanson** [comment]
I think the best fix for now is to remove that extra condition, and call `notify_error` in `close` instead of `notify`. For example this is also how sockets notify readers when `close` is called.
