### ISSUE TITLE
BoundsError when String is indexed by an BitArray{1}

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/julia#12495]
I found this `BoundsError` trying to index an `ASCIIString` using a `BitArray{1}`:

```
julia> a = "ABC"
"ABC"

julia> b = [1,2,3].!=2
3-element BitArray{1}:
  true
 false
  true

julia> a[b]
ERROR: BoundsError: attempt to access 3-element Array{UInt8,1}:
 0x41
 0x42
 0x43
  at index [0]
 in anonymous at strings/basic.jl:43
 in sprint at ./iostream.jl:206
 in getindex at strings/basic.jl:42

julia> @which a[b]
getindex(s::AbstractString, v::AbstractArray{T,1}) at strings/basic.jl:42
```

...but using a `Vector{Bool}` is fine:

```
julia> a[[true, false, true]]
"AC"

julia> @which a[[true, false, true]]
getindex(s::ASCIIString, r::Array{T,1}) at ascii.jl:19
```

**Comment by StefanKarpinski** [comment]
Hmm. I'm not sure if logical indexing of strings is a good idea. Although it can actually be done efficiently.

**Comment by ivarne** [comment]
Ref https://github.com/JuliaLang/julia/issues/4763, where the same issue was raised for `SubArray`

**Comment by kshyatt** [comment]
Still happens on master.

**Comment by nalimilan** [comment]
Actually, no: now `a[[true, false, true]]` gives the same error, which at least is consistent. I'm not persuaded we need logical indexing of strings either, so what we could do is restrict the signature of `getindex` to `::AbstractVector{<:Integer}` to make it a `MethodError`.
