### ISSUE TITLE
Build error on mac osx (Julia 0.4 latest)

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLang/julia#12514]
Hi all, 

I am trying to get the latest julia build for my mac but I can't seem to compile it. Near the end of the compilation I get the following errors
```
[ 22%] Building C object CMakeFiles/git2.dir/src/unix/map.c.o
[ 22%] Building C object CMakeFiles/git2.dir/src/unix/realpath.c.o
[ 22%] Building C object CMakeFiles/git2.dir/deps/http-parser/http_parser.c.o
Linking C shared library libgit2.dylib
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in path.c.o
  "_libiconv_close", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_clear in path.c.o
      _git_path_diriter_free in path.c.o
      _git_path_dirload in path.c.o
  "_libiconv_open", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_init_precompose in path.c.o
      _git_path_diriter_init in path.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libgit2.0.23.1.dylib] Error 1
make[3]: *** [CMakeFiles/git2.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [libgit2/build/libgit2.dylib] Error 2
make: *** [julia-deps] Error 2
```
Looks like a linker error. But am not sure what is causing this. I am just running the default make command. I am on OSX Yosemite.

Any clues?

thanks,

**Comment by tkelman** [comment]
See #12026 and #8937. Do you use fink?

**Comment by tkelman** [comment]
Also https://github.com/libgit2/libgit2/issues/3296 - a workaround might be to temporarily take fink off your path, or maybe just fink's pkg-config.



This wasn't the error you had, but I suspect someone else is going to hit it and get confused. If anyone reading this hits an error that looks like
```
error: Your local changes to the following files would be overwritten by checkout:
    CMakeLists.txt
    src/openssl_stream.c
Please, commit your changes or stash them before you can switch branches.
Aborting
make[1]: *** [libgit2/CMakeLists.txt] Error 1
make: *** [julia-deps] Error 2
```
then you just need to run `make -C deps distclean-libgit2` and you should be all set. That won't quite help @GravityAssisted until he fiddles with his fink / pkg-config path though.

**Comment by GravityAssisted** [comment]
I don't know what fink is (relatively new to Mac) but I do have mac ports installed. I tried removing the macports /opt path from my .bash_profile and I am rebuilding julia now. My new path looks like the following.
```
/Users/arora/anaconda/bin:/Users/arora/src/julia/usr/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

**Comment by tkelman** [comment]
Might help if you post the full output of what cmake says, the initial "Looking for ..." and "Performing Test ..." to a [gist](https://gist.github.com) and leave a link here. Maybe macports, or maybe conda could be doing something strange with openssl/iconv. Though I suspect if it were an issue with conda then more people would have noticed by now.

**Comment by GravityAssisted** [comment]
Here you go: link to the gist

https://gist.github.com/b3404b8f81642c6b84b6.git

**Comment by ViralBShah** [comment]
I ran into this, and deleting `deps/libgit2` did the trick.

**Comment by tkelman** [comment]
@GravityAssisted could you try temporarily moving `/opt/local/bin/pkg-config` to a different name, and see if `make -C deps distclean-libgit2 && make VERBOSE=1 -C deps install-libgit2` does anything different? That'll give more output including the entire link line that's causing trouble.

**Comment by felipenoris** [comment]
I ran into this yesterday, but I would say that this is not an issue.
Is you clone a brand new repository and run ```make```, no error occurs.
If you have an existing repository, you may run ```make cleanall && make distcleanall```. That will *brute-force-clean* stuff. After that, if you run ```make``` it will compile without errors.
The *readme* file suggests running ```git reset --hard && git clean -x -f -d``` on extreme cases, but in this case it's not sufficient. Maybe you could update the *readme* file suggesting users to run ```make cleanall && make distcleanall``` on even more extreme cases.

**Comment by felipenoris** [comment]
What I just wrote worked for me (I'm running *Yosemite*). If one can confirm that this is a catch-all solution, maybe this issue should be closed.

**Comment by tkelman** [comment]
@felipenoris unless you hit a linker error having to do with `_libiconv`, then what you saw was not this issue. I just mentioned the need to distclean because I anticipate others would see that separate issue.

**Comment by felipenoris** [comment]
@tkelman You're right. I'm sorry.

**Comment by vtjnash** [comment]
what do people think about "solving" this issue by calling `libgit2/configure` with `PKG_CONFIG_LIBDIR=$(JULIAHOME)/foo/bar` on Mac, Windows, and cross-compile?

**Comment by tkelman** [comment]
Might work. I think pkg-config causes more trouble with libgit2 than it's worth, even on Linux I think the built-in `find_*` methods that cmake will use if it can't find pkg-config do a better job in multilib and a few other cases.

**Comment by GravityAssisted** [comment]
@vtjnash @tkelman @felipenoris
I apologize for not responding earlier, I am currently (for past one week) on international conference travel and have limited internet access. I also presented a paper on applications of Julia at one of our conferences this week, it was received very well. I plan to try the above the stated solutions on Sunday (when I get back to the US) and will report back here.

thanks for all the support!
