### ISSUE TITLE
Poor performance in `pop!` for large sets

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#12512]
Here's a program that creates a `Set` with `n` values, and `pop!`'s each item until the `Set` is empty.  (One could imagine a more complex program that also occasionally adds additional values to the set within the `while` loop, but the program below is enough for demonstration.)

```julia
function f(n)
    s = Set{Int}()
    for i in 1:n
        push!(s, i)
    end
    println(n)
    @time while !isempty(s)
        pop!(s)
    end
    nothing
end

f(1)
for i in 10000:10000:100000
    f(i)
end
```

I'd expect execution time to scale roughly linearly with the system size, but there seem to be some odd jumps in performance.  Here's the output:

```
1
   1.384 microseconds
10000
 206.463 milliseconds
20000
   1.662 seconds     
30000
   2.368 seconds     
40000
   3.139 seconds     
50000
  15.501 seconds     
60000
  19.208 seconds     
70000
  21.814 seconds     
80000
  24.905 seconds     
90000
  29.277 seconds     
100000
  31.856 seconds     
```

And here's the output on julia 0.3 (which is similar):

```
1
elapsed time: 2.681e-6 seconds (0 bytes allocated)
10000
elapsed time: 0.208272536 seconds (0 bytes allocated)
20000
elapsed time: 1.553197704 seconds (0 bytes allocated)
30000
elapsed time: 2.480638971 seconds (0 bytes allocated)
40000
elapsed time: 3.310038833 seconds (0 bytes allocated)
50000
elapsed time: 16.065064869 seconds (0 bytes allocated)
60000
elapsed time: 19.645900665 seconds (0 bytes allocated)
70000
elapsed time: 23.032582856 seconds (0 bytes allocated)
80000
elapsed time: 26.509956115 seconds (0 bytes allocated)
90000
elapsed time: 29.787230555 seconds (0 bytes allocated)
100000
elapsed time: 32.477262489 seconds (0 bytes allocated)
```

Going from 40000 to 50000 is the biggest jump, but the one from 10000 to 20000 is significant as well.

**Comment by KristofferC** [comment]
Interesting:

```julia
julia> f(43690)
43690
  0.674981 seconds

julia> f(43691)
43691
  2.412829 seconds
```

Is the exact breakpoint at the same place for you.

**Comment by timholy** [comment]
I bet we're seeing jumps for the size of the underlying arrays, and `O(N^2)` behavior here because of https://github.com/JuliaLang/julia/blob/87a956bfb268172eee30ba737ef47cf839563c4d/base/dict.jl#L761 and https://github.com/JuliaLang/julia/blob/87a956bfb268172eee30ba737ef47cf839563c4d/base/set.jl#L3. Solving this might require caching the first non-deleted index in the Dict.

**Comment by JeffBezanson** [comment]
That sounds like a good idea.

**Comment by timholy** [comment]
Nice, Jeff.
