### ISSUE TITLE
REPL history becomes unusable after hitting Ctrl+C during `@less`

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#12524]
With master as of today, hitting Ctrl+C after calling `@less` (for example, `@less sin(1)`) and before hitting `q` makes the history unusable. The error is:

```
ERROR: InterruptException:
 in process_events at ./stream.jl:642
 in wait at ./task.jl:360
 in wait at ./task.jl:286
 in stream_wait at ./stream.jl:289
 in wait at ./process.jl:617
 in run at ./process.jl:493
 in less at interactiveutil.jl:64
 in less at interactiveutil.jl:69
```

**Comment by blakejohnson** [comment]
On my machine, after Ctrl+C I get that error and then bizarre behavior when pressing up and down arrow. However, if I subsequently press `q` I get back to a normal REPL. Do you see the same?

**Comment by nalimilan** [comment]
Indeed, under very specific circumstances it can go back to normal. But for it to happen I need to clean the prompt line, which shows things like ``julia> BOB`` depending on how many times I pressed the arrows.

**Comment by nalimilan** [comment]
I can't reproduce on current master.
