### ISSUE TITLE
julia-mode: Non repeatable indent with open parenthesis.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12528]
The following code flip-flop between the two indentations when indenting the whole file. Note that the second screenshot has a leading space while the first one doesn't.

```julia
(1)
```

![no space](https://cloud.githubusercontent.com/assets/712232/9156618/68cca358-3eae-11e5-98af-1321dc754eb0.png)
![with space](https://cloud.githubusercontent.com/assets/712232/9156620/73ee8396-3eae-11e5-93e0-d2deb36541e6.png)

**Comment by dfannius** [comment]
As with issue #12527, I can't duplicate this on Emacs 24.5.1 (OS X) with the latest julia-mode (2015-07-15). What are you doing to indent the whole file (which I assume contains only those three characters and a line feed)?

**Comment by yuyichao** [comment]
This is ArchLinux. Emacs 24.5.

I notice that this one does not happen if it is the first line. can you try to have an empty line before it (and I usually have `#!/usr/bin/julia -f` before it) and see if you can reproduce this?

**Comment by dfannius** [comment]
Indeed, it reproduces for me if the the file is a blank line followed by a line with `(1)`. Every time I hit Tab on that line, it toggles between zero and one space of indentation.

**Comment by dfannius** [comment]
In fact this will reproduce any time you have a line (other than the first line of the file) starting with a `(` or `[` with no indentation before it.

The solution is to add a `(backward-char)` call as the first thing inside the `save-excursion` in `julia-paren-indent`. This will move point onto the previous line and prevent it from getting confused by any parenthesis or bracket that begins the current line.

I'll submit a pull request with tests shortly.
