### ISSUE TITLE
julia-mode: incorrect indent with unicode

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#12527]
Seems that the width of a unicode character is not calculated correctly. See below.

```julia
α(1,
   1)
```

![indent](https://cloud.githubusercontent.com/assets/712232/9156587/8ffa887e-3ead-11e5-9432-6e0fe00e1f8d.png)

**Comment by dfannius** [comment]
I can't duplicate this on Emacs 24.5.1 (OS X) with the latest julia-mode (2015-07-15). The two `1`s are both aligned with each other when I hit Tab on the second line to indent it. I'm not sure what else might be different in our two environments.

**Comment by yuyichao** [comment]
Thanks for the data point. As mentioned in #12528, this is ArchLinux Emacs 24.5. I'll check this one with a clean setup later.

**Comment by stevengj** [comment]
Note that there is a lot of variation in charwidth calculations between systems (see #3721).

**Comment by yuyichao** [comment]
Yeah, I checked with other modes (c++, python) and it seems that both of them have the same issue so I guess it is not a julia-mode issue rather an issue for emacs (or whatever other settings I have).

**Comment by tkelman** [comment]
glibc's charwidth tables, probably. Unless you want to try patching emacs to use utf8proc instead :)
