### ISSUE TITLE
NEWS still has `Base.compile(modulename)`...

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#12522]
... but this doesn't seem to work anymore. I've lost track of what is the right command.

**Comment by tkelman** [comment]
`Base.compilecache` for the manual version, I think

**Comment by IainNZ** [comment]
Yes it does seem to be that @tkelman

**Comment by IainNZ** [comment]
Closed in favor of https://github.com/JuliaLang/julia/pull/12526
