### ISSUE TITLE
crash on constructing array of Rationals

### ISSUE THREAD

**Issue by michele-zaffalon** [JuliaLang/julia#12534]
On Windows7 64 bit, attempt to constructing the array `[1:10//3]` crashes Julia 0.3.11. `[1:10//2]` works fine.

```
C:\Users\michele>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> [1:10//2]
5-element Array{Rational{Int64},1}:
 1//1
 2//1
 3//1
 4//1
 5//1

julia> [1:10//3]

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1c5c885b --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77243290 --
```

**Comment by nalimilan** [comment]
The crash also happens on Linux. But it's fixed in 0.4. If somebody is able to identify the commit that fixed it, it could be backported; else, 0.4 should be released soon.

**Comment by michele-zaffalon** [comment]
I follow the instructions [here](http://docs.julialang.org/en/latest/devdocs/backtraces/#segfaults-when-running-a-script). The gist is [here](https://gist.github.com/michele-zaffalon/3a0e58a3eeecd1054adc). Is the backtrace so terse or am I doing something wrong?

This is on 0.3.12-pre+2, commit 7709f2e. 0.3.11 gives similar results.

**Comment by tkelman** [comment]
What version of LLVM was that? Looks like a debian gdb build there? Quality of debug info has changed a fair amount from 0.3 to 0.4.

I think what you'll need to do to identify what fixed this issue would be "git bisect" back along the history of master to find the most recent commit where this fails, and the commit that fixed it. Once that's identified we can look at how large of a change that commit was and decide whether or not it's possible to backport to the release-0.3 branch.

**Comment by michele-zaffalon** [comment]
Sorry, yes, it is Debian 64bit that I have at home (Windows at work). LLVM is 3.3.

You mean git bisect and `git clean -fdx` and `make`? It may take a while: compiling the whole thing takes an hour on my computer.

**Comment by tkelman** [comment]
Between steps of bisect you can usually get away with just `make cleanall`. You probably won't need to rebuild LLVM or OpenBLAS or FFTW at all. You might need a `make -C deps distclean-libgit2` or `make -C deps distclean-pcre` if you go back far enough and get any errors related to those, but they're small and pretty fast to rebuild.

**Comment by nalimilan** [comment]
Don't we have archives of binary nightlies somewhere to speed up this process?

**Comment by tkelman** [comment]
Only going back about a month. https://s3.amazonaws.com/julianightlies/

**Comment by michele-zaffalon** [comment]
No luck there: the oldest generic linux 64 bit is from 2015-07-19 and it doesn't crash.

**Comment by michele-zaffalon** [comment]
It looks like commit 768401c76dcd7138fc9cb18d60c77562d61c529f is the last one that crashes and commit 700abd2bf9a2e9d7905e7270388b53ec6ae76986 the first one that does not. I cannot seem to be able to compile the commit between the two...

**Comment by tkelman** [comment]
Huh. That's strange. So one of the lower-case conversions that were removed and replaced in that PR is apparently what was causing the issue. Unfortunately removing the lower-case conversions depends on call overloading, which is one of the bigger changes in 0.4 and can't be backported. So thanks for running the bisect and identifying the fix, but I think we're going to have to close this as won't fix on 0.3. Sorry!

Can anyone suggest a workaround for 0.3?

**Comment by michele-zaffalon** [comment]
Thank you for the explanation and the support.

What is exactly strange? Calling `[1:10//3]` in the commit 768401c76dcd7138fc9cb18d60c77562d61c529f hangs the REPL, somewhere at `intfuns.jl` inside the function `gdc` according to gdb: I get a segfault after pressing `Ctrl-C` (this is on Debian). Is there something else I could try? Unfortunately my skills at debugging with gdb are less than rudimentary.

**Comment by tkelman** [comment]
What's strange is I wouldn't have expected or guessed that #10452 was responsible for fixing this. It might be related to `tryparse` or one of the other internal functions that may have been tweaked there. I'm not sure if trying to figure things out in gdb is the right approach, since any fix would likely need to be custom for release-0.3. Probably better to look for alternate syntax workarounds at this point, maybe using `collect` or one of the `Range` type constructors directly.

**Comment by michele-zaffalon** [comment]
`collect(1:10//3)` crashes it too. As for `range`, the error depends on the length:
```
julia> collect(range(1, 1//3, 3))
ERROR: InexactError()
 in range at range.jl:94

julia> collect(range(1, 1//3, 4))
ERROR: InexactError()
 in vcat at range.jl:511
 in collect at range.jl:519
```

**Comment by nalimilan** [comment]
Any reason you need to stay on 0.3? At this point, 0.4 might well be released before a potential 0.3.12, so it might not be worth the pain of backporting a fix. You should be able to start using 0.4-pre now, it should be more or less stable until the release (of course, not all packages work yet...).

**Comment by michele-zaffalon** [comment]
Yes, there is nothing that prevents me from changing.

But agains, sorry for being such a pain. On 0.3.11 I see
```
julia> I=1:10//3
1//1:10//3

julia> I.stop
10//3
```
and `done` is always `false` because it (checks for equality)[https://github.com/JuliaLang/julia/blob/v0.3.11/base/range.jl#L252]. (In 0.4, `I.stop` is correctly computed to be 3//3).

Back to 0.3.11: `collect(1:10//3)` complains with an out of bounds error. [This is here](https://github.com/JuliaLang/julia/blob/v0.3.11/base/array.jl#L229).

As for [1:10//3] instead, [I see here](https://github.com/JuliaLang/julia/blob/v0.3.11/base/range.jl#L504) that there is an `@inbounds` for the array. Does this mean that Julia allocates an array of length 3, but then since `done(itr, state)` is always false, it keeps iterating and trying to fill the array outside its bounds? Does this explain the crash? The manual seems to indicate so about the macro inbounds.

**Comment by nalimilan** [comment]
@michele-zaffalon No problem. But I don't think the equality check is the problem here:
```julia
julia> I=1:10//3
1//1:10//3

julia> done(I, 13//3)
true
```

It looks like there's a deeper bug here:
```julia
julia> [x for x in I] # OK
3-element Array{Any,1}:
 1//1
 2//1
 3//1

julia> for x in I # Wrong
           println(x)
       end
1//1
2//1
3//1
4//1
5//1
6//1
7//1
8//1
9//1
10//1
[...]

```

**Comment by nalimilan** [comment]
In my last post, the difference is probably that the first `for` form looks at `length(I)`, while the other relies on `done()`. 

The fix on 0.4 seems to come from the fact that the upper bound of `1:10//3` is computed as `3//1` directly on construction, which makes the equality test work in `done`. If you look at `@less UnitRange{Rational{Int}}(1//1, 10//3)`, you'll notice that 0.4 calls `unitrange_last` to compute `stop`. This could probably be backported.

@michele-zaffalon Do you feel like trying to make a PR to use `unitrange_last` in 0.3?

**Comment by michele-zaffalon** [comment]
@nalimilan Correct, this is what I wanted to say, but you said it better.

I can give it a try: is the branch for the PR release-0.3?

**Comment by nalimilan** [comment]
@michele-zaffalon Yes, that's the right one.

**Comment by tkelman** [comment]
You'd want to make the change off of release-0.3 as well. So something like `git checkout release-0.3; git pull; git checkout -b mz/fix12534` to start with, then when you've pushed the branch to your fork and open the pull request, be sure to select in the drop-down box to open the pull request against the release-0.3 branch instead of master. Also good to mention in the PR title or description that it's against release-0.3 just so reviewers don't miss that.

**Comment by michele-zaffalon** [comment]
@tkelman always very pedagogical, but thank you for the clear instructions. (You are probably afraid that a newbie like me is going to screw it up and you'll end up having to do double work!)

Sorry for the delay.

**Comment by nalimilan** [comment]
> (You are probably afraid that a newbie like me is going to screw it up and you'll end up having to do double work!)

I think @tkelman is more concerned that you find the process of making a PR too painful and stop from contributing to Julia in the future.

**Comment by tkelman** [comment]
Yeah, accidentally opening a PR with hundreds of unrelated commits in it is not a fun experience for anyone.

**Comment by michele-zaffalon** [comment]
@nalimilan @tkelman Thanks both for the patience.
