### ISSUE TITLE
examples do not get reinstalled when they change

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#12539]
When code in `examples/` changes and you run `make testall`, the tests still pick up old versions of the files installed in `usr/share/doc/julia/examples`. This has caused the tests to needlessly error out on me more times than I can count. What's worse, (1) it happens near the end of the tests so you have to rerun everything, (2) it's not obvious what to run to fix this. TBH I've been copying the changed files manually.

**Comment by timholy** [comment]
This bit me recently, too.

**Comment by vtjnash** [comment]
fix at https://github.com/JuliaLang/julia/commit/d50b704a9bf3ee4cffe5fe02c9800a16c8178157

**Comment by JeffBezanson** [comment]
Looks straightforward enough. Any reason not to put that commit on master?

**Comment by vtjnash** [comment]
just merge the PR (#12463) :smile:

**Comment by StefanKarpinski** [comment]
No, please fix the bug in a separate PR.

**Comment by vtjnash** [comment]
That can only be done by doing the work twice, since it conflicts with #12463. So regardless of whether someone wants to merge it in a separate PR, I still needed to cherry-pick it on top of #12463.

**Comment by StefanKarpinski** [comment]
That's fine. That PR should have had the bug fixes split out of it anyway.
