### ISSUE TITLE
Manual replace example is failing

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/julia#12533]
There is a missing `"` in the regex and `@s_str` is not defined.
```
julia> replace("first second", r"(\w+) (?P<agroup>\w+), s"\g<agroup> \1")
ERROR: syntax: "\" is not a unary operator

julia> s"\g<agroup> \1"
ERROR: UndefVarError: @s_str not defined

julia> versioninfo()
Julia Version 0.4.0-dev+6095
Commit c75f4d4* (2015-07-20 14:38 UTC)
```

**Comment by nalimilan** [comment]
Cc: @malmaud

**Comment by JeffBezanson** [comment]
`@s_str` might have been added to exports right after the version you're using. It's in the exports list now.

**Comment by jakebolewski** [comment]
this works on master, you are missing a closing `"` for the regex in your first example

**Comment by diegozea** [comment]
@jakebolewski The `"` is still missing in the manual example:

> julia> replace("first second", r"(\w+) (?P<agroup>\w+), s"\g<agroup> \1")
julia> "second first"

**Comment by jakebolewski** [comment]
thanks I'll fix it

**Comment by malmaud** [comment]
thanks jake
