### ISSUE TITLE
FloatRange floating point error

### ISSUE THREAD

**Issue by joshkarges** [JuliaLang/julia#12547]
I came across a weird bug with a FloatRange of mine where the last element was larger than the `stop` value.

```
julia> total_range = 0.0 : 0.152828 : 15.282799999999998
0.0:0.152828:15.2828

julia> total_range[end] > 15.282799999999998
true
```

I tested using v0.3.7 and v0.3.9, so I'm not sure if this is fixed in a later version or not, but I couldn't find any resolved issues related to this.
I found PR #5636 and issue #2333, which discussed a similar but different issue.  In fact from the discussion it doesn't look like this bug will be easily solved since the `FloatRange` last value is `total_range.start + total_range.step * (total_range.len-1)` which tweaks out the smaller floating point difference in the original `stop` value.

A simple example is 

```
julia> total_range = 0.0 : 0.1 : 0.30000000000000002
0.0:0.1:0.30000000000000004
```

**Comment by yuyichao** [comment]
Seems that the length should be 100 instead of 101?

**Comment by StefanKarpinski** [comment]
Since

```jl
100*0.152828 == 15.2828 < 15.282799999999998 < 15.435628 == 101*0.152828
```

this behavior seems correct. In the second example, there is no tweaking – `0.30000000000000002 == 0.30000000000000004` in `Float64`.

**Comment by StefanKarpinski** [comment]
Although arguably since `15.282799999999998/100 == 0.152828` it should be possible to figure this out.

**Comment by yuyichao** [comment]
Hmmm. Did I miss something?

```julia
julia> 15.2828 < 15.282799999999998
false

julia> 100 * 0.152828 == 15.2828
true
```

**Comment by StefanKarpinski** [comment]
Oh, no, I missed that. Definitely a bug then.

**Comment by StefanKarpinski** [comment]
I think fallback case in the `colon` function is subtly wrong:

> FloatRange{T}(start, step, floor(r)+1, one(step))

where `r = (stop-start)/step`. Whether the lifting logic could be generalized to handle this is a different issue.

**Comment by RitwikGopi** [comment]
julia> 15.2828 > 15.2827
true

**Comment by KristofferC** [comment]
This is fixed (likely by Tim Holys range work that included a bunch of tests).. 

```
julia> total_range = 0.0 : 0.152828 : 15.282799999999998
0.0:0.152828:15.129971999999999

julia> total_range[end] > 15.282799999999998
false
```
