### ISSUE TITLE
norm(Float64[0,NaN]) == 0

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12552]
`norm(Float64[0,NaN]) == norm(Float64[0,NaN],2) == norm(Float64[0,NaN],Inf) == 0`, whereas I would expect NaN in this case.  The L1 norm gives NaN.

Seems to affect both Julia 0.3 and 0.4-dev.

**Comment by stevengj** [comment]
The basic problem is that `max(0.0, NaN) == 0`, when it should probably give NaN.

**Comment by StefanKarpinski** [comment]
I would strongly encourage making `max` and `min` over `NaN` produce `NaN`.

**Comment by simonster** [comment]
See also #7866

**Comment by StefanKarpinski** [comment]
In fact, this very example is a pretty strong argument for why it should be `NaN` rather than `0.0`.

**Comment by lbenet** [comment]
@stevengj Indeed, in #10736 `max(0.0, NaN) == 0` was intentionally coded to mimic the results obtained in v0.3.
(I think this discussion is continuing in #7866).
