### ISSUE TITLE
Pkg & Gist: `using` is looking for a `src` folder

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/julia#12557]
*Gist* doesn't allow you to use folders, so it's impossible to `using MyGistSmallPackage` since `using` needs a *src* folder.

Is posible to make `using` use a *.jl* file in a folder without subfolders?

**Comment by jakebolewski** [comment]
can you describe what you want to in more detail? (with reproducible example)

**Comment by diegozea** [comment]
Yes, I have this [Gist](https://gist.github.com/diegozea/e689e59f4ed7da1ddf78)
I'm able to do a clone using ```Pkg.clone``` but I'm not able to use it as a Julia package since there isn't a `src`folder:

```
julia> Pkg.clone("https://gist.github.com/e689e59f4ed7da1ddf78.git", "PerlishMatch")
INFO: Cloning PerlishMatch from https://gist.github.com/e689e59f4ed7da1ddf78.git
INFO: Computing changes...

julia> using PerlishMatch
ERROR: ArgumentError: PerlishMatch not found in path
 in require at ./loading.jl:134

```

**Comment by jakebolewski** [comment]
Packages assume a certain directory structure, I don't this that requirement is going away. Why not just host it in a git repo?

**Comment by diegozea** [comment]
I'm just curious about Julia working with *Gist* for very small things. But it's fine if package always need a directory structure... However would be cool to have some facility for working with smalls files on *Gist*.

**Comment by jverzani** [comment]
There are likely much better ways to do this, but here is one:

```
using JSON
function reload_gist(id)
    reload_content(cnt) = begin f = tempname() * ".jl"; io = open(f, "w"); print(io, cnt); close(io); reload(f); rm(f) end
    gist = (open(download("https://api.github.com/gists/$id")) |> readlines |> join |> JSON.parse)
    [reload_content(gist["files"][k]["content"]) for (k, v) in gist["files"] ]; nothing
end
```

**Comment by diegozea** [comment]
¡Great! This one avoids the error for trying to parse the *README.md* as a Julia file:

```
using JSON
function reload_gist(id)
    reload_content(cnt) = begin 
    	f = tempname() * ".jl"; 
    	io = open(f, "w"); 
    	print(io, cnt); 
    	close(io); 
    	reload(f); 
    	rm(f) 
    end
    gist = (open(download("https://api.github.com/gists/$id")) |> readlines |> join |> JSON.parse)
    for (k, v) in gist["files"]
    	if ismatch(r"\.jl$", k) # This avoids read README.md
    		reload_content(gist["files"][k]["content"])
    	end
    end
    nothing
end
```
