### ISSUE TITLE
LLVM error in factor(::Int128)

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12566]
The numbers tests presently fail on my system. The culprit is the test at https://github.com/JuliaLang/julia/blob/66f336d37e123482c9fe5201750564537c420cbe/test/numbers.jl#L2140. Minimum reproducer:

```
julia> versioninfo()
Julia Version 0.4.0-dev+6620
Commit 66f336d* (2015-08-11 15:49 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> factor(Int128(1))
LLVM ERROR: Do not know how to split the result of this operator!
```

On this system, this appears to fail on 0.3 as well, although with a better message:

```
julia> versioninfo()
Julia Version 0.3.12-pre+2
Commit 7709f2e (2015-07-28 06:05 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> factor(Int128(1))
ERROR: type cannot be constructed
```

This works fine on another system. Not sure what's going on here...

**Comment by vtjnash** [comment]
i think you're missing a patch to llvm, try deleting it from deps and rebuliding (one of the goals that https://github.com/JuliaLang/julia/pull/12463 accomplished is to add build targets for them so that manual intervention is not necessary)

**Comment by simonster** [comment]
Yes, that seems to fix it. Sorry for not trying first.

**Comment by vtjnash** [comment]
np, it's not an intuitive thing to try (i've just seen the error message pop up on a few machines now so i've started to recognize it)
