### ISSUE TITLE
Interesting build path display for precompile.jl

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#12572]
I noticed this when building Julia yesterday and today:

```
seth@schroeder:~/dev/julia/julia$ make
...
pkg.jl
profile.jl
Dates.jl
deprecated.jl
docs/helpdb.jl
docs/basedocs.jl
/Users/seth/dev/julia/julia/base/precompile.jl
    LINK usr/lib/julia/sys.dylib
```

Why is `precompile.jl` displaying the full path, and does it represent something significant?

**Comment by jakebolewski** [comment]
I'm trying to close these :-).  Not the best use of an issue, seems more appropriate for Julia-Dev.

**Comment by sbromberger** [comment]
Sorry, @jakebolewski - will ask on -dev.
