### ISSUE TITLE
`using` should check case of file name

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12586]
I accidentally typed `using hDF5`, and Julia accepted this. This should not have worked; the proper module name is `HDF5` (with all upper case letters).

I am using OS X with a case-insensitive file system. That is, while the case of the file name is ignored when looking for a file, the file name still has a particular case that can be checked.

I would have expected Julia to reject the command `using hDF5` by noting that yes, there is a file that can be opened under the name `hDF5.jl`, but this file's name is actually `HDF5.jl`, so it doesn't match.

**Comment by StefanKarpinski** [comment]
Yes, this would be a very good thing to change. When searching for filenames with `using`, we should additionally check that that the canonical name of the found file matches the expected case of it and not consider it to be a match if it doesn't, and thus continue to search. We may want to do the same for `include`, although that's less clear since that's more of a "load this file and eval it".

**Comment by ScottPJones** [comment]
This would be very good, I think it should also be done for `include`, to help prevent case typos from silently working on Windows and OS X case-insensitive file systems, and then code failing when moved to Unix/Linux or an OS X case-sensitive file system (like I normally use now).

**Comment by stevengj** [comment]
See also #9007 and Python [PEP 235](https://www.python.org/dev/peps/pep-0235/).

**Comment by Sisyphuss** [comment]
I don't think that worth the work. Making it case sensitive is only a burden to the brain: 'TimeIt', "Timeit", or "timeit"? In addition, it will encourage people to use the same name with different cases to name different packages.

**Comment by stevengj** [comment]
@Sisyphuss, even if we wanted to allow case insensitivity (which would be inconsistent with the rest of Julia), the problem is that the behavior is inconsistent between platforms.

**Comment by malmaud** [comment]
Dup of https://github.com/JuliaLang/julia/issues/5789. Would be nice to get this fixed.
