### ISSUE TITLE
inconsistent sign(0)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12599]
```
julia> sign(0)
0

julia> sign(0.0)
0.0

julia> sign(0+0im)
NaN + NaN*im
```
Also, note that `sign(z) == z/abs(z)` is undocumented.

**Comment by jakebolewski** [comment]
@marcusps raised the issue for `@fast_sign` also.

**Comment by stevengj** [comment]
@jakebolewski, what is `@fast_sign`?  I don't see this macro.

**Comment by jakebolewski** [comment]
sorry `fast_sign()` in `FastMath`

**Comment by stevengj** [comment]
@jakebolewski, I see; I think it's called `sign_fast` there?
