### ISSUE TITLE
A keepzeros option for sparse(I, J, V)

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#12605]
`sparse` currently consider zeros element in V as structural zeros

```julia
I = [1, 2]
J = [1,2]
V = [0, 1]
M = sparse(I, J, V)
# 2x2 sparse matrix with 1 Int64 entries:
# [2, 2]  =  1
```
This means the sparsity structure of M depends on the values of V, and not only of the pair (I, J). So there is no way to initialize a sparse matrix with the "correct" sparsity structure, independently of its values V. This is problematic since it's inefficient to modify the structure of a sparse matrix.

Why can't `sparse` consider zeros element in V as non structural zeros? I'm not sure how other programming languages handle this situation so I'm looking for some feedback before making a pull request.

**Comment by KristofferC** [comment]
Related issues: https://github.com/JuliaLang/julia/issues/9906 and https://github.com/JuliaLang/julia/issues/9928

What I do (for Finite Elements) is just to put 1.0 or something in `V` and then you can `fill!(A.nzval, 0.0)` to just have the sparse structure with 0.0 values.

**Comment by jakebolewski** [comment]
Thanks for raising this issue @matthieugomez, please continue the discussion at #9906 and #9928.

**Comment by ViralBShah** [comment]
We could have an option to `sparse` to do this.

**Comment by matthieugomez** [comment]
Why could not zeros always be retained? This is the current behavior for `sparsevec`

```julia
I = [1, 2]
V = [0, 1]
M = sparsevec(I, V)
#2x1 sparse matrix with 2 Int64 entries:
#	[1, 1]  =  0
#	[2, 1]  =  1
```
 
The other solution, as you say, is to add an option like `keepzeros`. Should I change the default behavior for `sparsevec` so that `keepzeros = true` by default?

**Comment by ViralBShah** [comment]
The `SparseMatrixCSC` data structure and its operations have been currently designed to squeeze out zeros. This is being debated in the other issues. The `sparsevec` thing you reported is a bug, and that whole implementation is being revisited with a real `SparseVector` type in 0.5. For now, in 0.5, I would just introduce a `keepzeros` option.

**Comment by ViralBShah** [comment]
I am reopening this issue to track the `keepzeros` option, which is different enough than the other related sparse issues.

**Comment by tkelman** [comment]
> The `SparseMatrixCSC` data structure and its operations have been currently designed to squeeze out zeros.

This is not an accurate description of the data structure. Many of the operations remove zeros, but not all, and there are corner cases as with `sparse`.

**Comment by ViralBShah** [comment]
Like I clearly said, the cases where the zeros don't get squeezed out are bugs - that is not the design. The data structure does not care what you store in it, but the operations are all designed to squeeze out zeros.

**Comment by tkelman** [comment]
And the conclusion in #9928 from pretty much all heavy users of sparse matrices is that we want better support for stored zeros, not to work harder to remove them. The design should shift away from Matlab and closer to SciPy, but with adjustments anywhere we think SciPy's behavior is inconsistent and we could do better.

It's a little bit like type stability actually - whether an entry has storage allocated for it in the sparse matrix output from many mathematical routines really shouldn't depend on the numerical values, it should depend primarily on the nonzero structures of its inputs. This is far more amenable to inner-loop performance-critical calculations since it's much more predictable than allocating a differently-sized array when certain numerical elements happen to exactly equal zero.

**Comment by timholy** [comment]
Agreed with @tkelman. It would be much easier to ignore stored zeros in most routines, and provide a `purge_zeros` for those cases where you needed to get rid of them.

**Comment by KristofferC** [comment]
We have an unexported function called `dropzeros!` that does that.

**Comment by ViralBShah** [comment]
I am fine with the proposal - I just don't want to do it piecemea. In 0.5, we can update the whole implementation in one shot.

**Comment by StefanKarpinski** [comment]
> In 0.5, we can update the whole implementation in one shot.

+1

**Comment by tkelman** [comment]
Sounds like a plan.

**Comment by KristofferC** [comment]
This can be closed now?

**Comment by matthieugomez** [comment]
#14798
