### ISSUE TITLE
Still variable scoping bug

### ISSUE THREAD

**Issue by Sisyphuss** [JuliaLang/julia#12600]
The following code is a slight modification of 5th piece of code in the http://docs.julialang.org/en/latest/manual/variables-and-scoping/
```julia
x = 0
function foo(n)
  for i = 1:n
    x = i
    println(x)
  end
  x
end
foo(3)
```
The output is 
```
0

2
3
```
The return value is `1`.

This bug has something to do with #11065?

**Comment by tkelman** [comment]
@jakebolewski could you leave a few words at least when closing an issue, even an invalid one?

At the REPL when `x` is a global, the above prints 1, 2, and 3, and returns 0 for me. Seems intended and I don't think this is an issue, and this kind of question should go to julia-users first.

**Comment by Sisyphuss** [comment]
ADD: I had some misunderstanding about the new output format of JuliaBox kernel v0.4.0-dev.
Here is the updated code:

```julia
x = 0
function foo(n)
  for i = 1:n
    x = i
    println("x:$x")
  end
  x
end
foo(3)
```
The output of JuliaBox looks like
```
            x:1

Out[2]: 0
           
            x:2
            x:3
```
The remaining thing is whether the returning value 0 is intended.
