### ISSUE TITLE
Fatal error in type inference adding a GC frame

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#12603]
Version: 0.4.0-dev+6494 e66175b

Minimal example:

```jl
@inline function f(A::AbstractArray, I1, I2, I3)
    (size(A,1) >= I1 && size(A,2) >= I2) && size(A,3) >= I3
end
h(A) = f(A, 1, 2, 3)

code_typed(f, (Array{Int, 3}, Int, Int, Int)) # is ok
code_typed(h, (Array{Int, 3},)) # has an unreachable error("fatal error in type inference")
code_llvm(f, (Array{Int, 3}, Int, Int, Int)) # no gc frame
code_llvm(h, (Array{Int, 3},)) # gc frame (with nothing put into it, I think)
```

Full output: https://gist.github.com/mbauman/a4e9fb36f67e2287a8f6

**Comment by mbauman** [comment]
It's not that big of a deal to have assertion checks like that, especially when LLVM can verify that things were ok and drop the dead code.  But perhaps we could make it a non-allocating error type instead to prevent GC frames?

**Comment by yuyichao** [comment]
I would still prefer not having to worry about gc frames when an error is thrown. I think my throw local gcframe branch can already handle this and I believe when the codegen rewrite is merged there's even more we can do about it.

Any idea why type inference decide to add an assertion?

**Comment by mbauman** [comment]
Agreed completely, but this is blocking #11895.  No clue as to what's going on, but this is about as simple of an example as it gets, so hopefully one of you inference gurus can figure it out.

**Comment by yuyichao** [comment]
Hmmm `throw(ErrorException("...."))` should not create a gc frame and code_llvm agrees. However, there's something wrong with the codegen of `error(...)`. It seems that type inference could not infer that `Main.Base` is statically known?

**Comment by yuyichao** [comment]
Maybe you can try to have different definitions of `error` for base and inference?

There also seems to be a missing `Main.Base.` for `systemerror` (although I'm not sure if it is used in inference)...

**Comment by yuyichao** [comment]
Or replace `Expr(:call,:error,"fatal error in type inference")` with `Expr(:call, :throw, Expr(:new, :ErrorException, "fatal error in type inference"))` just for testing.

**Comment by mbauman** [comment]
Thanks for the quick hack!

Inference can't figure it out because `Main` isn't a constant binding.  Why is error.jl different from all the other tools inference uses (which get copied)?

**Comment by yuyichao** [comment]
Other tools?

**Comment by mbauman** [comment]
All the other stuff in `coreimg.jl`.  My knowledge here is rudimentary, but aren't all those functions and types duplicated and frozen into `Core.Inference`?  They don't reach out and try to grab the current methods and types from `Main`.

**Comment by yuyichao** [comment]
I won't claim I know the bootstrap very well but it does seems a little bit strange that we pull `error()` but not `ErrorException` into `Core.Inference`....

**Comment by JeffBezanson** [comment]
We should just remove that. Internal compiler errors shouldn't be emitted into generated code.

**Comment by carnaval** [comment]
yep. maybe emit it in debug mode and only have it be an `unreachable` llvm op in release.

**Comment by mbauman** [comment]
The original testcase here now passes… and the `fatal error` line has changed to use TopNode/GlobalRef in https://github.com/JuliaLang/julia/commit/fba99fdbb3730fa4bfc3e3da2d518d473139e60c which I think solves the root issue.

**Comment by tkelman** [comment]
Do we have test cases that capture this?
