### ISSUE TITLE
Building 0.4 on windows doesn't add the Git directory

### ISSUE THREAD

**Issue by amellnik** [JuliaLang/julia#12614]
I just built live 0.4 under 64 bit Windows.  The build ended successfully, but the result in /usr didn't contain the Git folder as in the windows 0.3 version from the installer.  I don't have git on my path and doing things like ```Pkg.status``` or ```readall(`git --version`)``` would throw an error.  I copied over the Git folder from 0.3.10 and it's now working fine.  

Is this intentional or was something left out?  If the former, perhaps we should mention this in the build instructions [here](https://github.com/JuliaLang/julia/blob/master/README.windows.md#compiling-with-mingwmsys2).

**Comment by tkelman** [comment]
You need to do `make win-extras` and move things around, or build and run an installer from `make dist`. I haven't bothered fixing this because we're planning on getting rid of command-line git for 0.5, ref #11196.

**Comment by vtjnash** [comment]
`make win-extras` doesn't install it either. the assumption was somewhat just that having built julia implies the user had started with git installed. however, since you can now build with the cygwin git, instead of installing msysgit as expected, i guess that's less simple now.

**Comment by tkelman** [comment]
Yeah there's still some manual moving of files required. Something like `cp -r dist-extras/Git usr`, or `make install && cp dist-extras/Git julia-*` should do it. Probably also need to move `7z.exe` and `7z.dll`.

Pkg doesn't really work properly with either cygwin's git or msys2's git, and I've never bothered fixing it. It might be easy to do, I haven't tried.

**Comment by amellnik** [comment]
Is there anything else that might be missing other than Git?  If so, maybe just telling people to build the installer and use that is simplest.  Otherwise, this sounds good -- I'll double-check that it works this afternoon.  Thanks for the head's up about @ mentions in diffs, I'll avoid it in the future.

**Comment by tkelman** [comment]
There are also a few dll's that we get from opensuse to make WinRPM work, I'd have to double-check the makefiles to see whether those get copied during `make install` or only in `make binary-dist`. Building and using the installer is the most reliable option if you want to use the resulting copy of Julia as if it came from an official installer. That is a bit more time-consuming if you're trying to do something like bisect on a bug though.

**Comment by amellnik** [comment]
I've taken another stab at better instructions that don't duplicate between sections.  Still trying to get things to squash though...

**Comment by amellnik** [comment]
I'm running out of the time I have to work on this, so I cheated and redid it from scratch as a single commit.

**Comment by tkelman** [comment]
Okay that works too. Squashing isn't strictly necessary for doc changes, though it is a good idea if any of the intermediate commits would fail the whitespace checker or other tests. And it's a good thing to learn how to do if you'll be using git much. Thanks for contributing!

**Comment by StefanKarpinski** [comment]
> I'm running out of the time I have to work on this, so I cheated and redid it from scratch as a single commit.

This is often the easiest way to squash things. You can steal the commit message of another commit using `git commit -C <sha1>` or with `-c` if you want to edit the message.

**Comment by amellnik** [comment]
I appreciate the tip.  Closing this now unless someone has further suggestions for this section of the docs.
