### ISSUE TITLE
Documenting multiple entities at once 

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#12615]
Often it is convenient to write a single doc entry for multiple functions, types, constants etc.
IIUC `Docs` module doesn't support such functionality yet.

Actually, this came up in JuliaStats/DataFrames.jl#852, because 61f85ad prohibited documenting vectors of symbols, a `DataFrames`' way to document multiple objects.

Personally, I have no strong opinion on the subject, but maybe using tuples, i.e.
```julia
"""Doc for both"""
(head, tail)
````
would be a way to go?

cc @one-more-minute

**Comment by one-more-minute** [comment]
`(head, tail)` or `[head, tail]` both seem like reasonable syntaxes – I don't see any reason to prefer one over the other. @MichaelHatherly uses the vector syntax in Docile, I believe.

**Comment by StefanKarpinski** [comment]
An argument for favoring `(head, tail)` over `[head, tail]` is that the array form has object identity, whereas the tuple form does not.

**Comment by StefanKarpinski** [comment]
In other words, one could document a particular array object, but it's not really meaningful to document a particular tuple since all tuples with the same contents are programmatically indistinguishable (i.e. egal).

**Comment by MichaelHatherly** [comment]
I'd added tuple syntax for documenting ``Method``s prior to adding the vector syntax for ``Function``s later, hence not using tuples for that. If I was able to redo that would have probably gone with a tuple.

Does it really need it's own syntax though? A macro would do fine too:

```jl
@docs "..." head tail
```

that generates

```jl
@doc "..." head
@doc (@doc head) tail
```

or something similar.

**Comment by MichaelHatherly** [comment]
It shouldn't be too much trouble to deprecate the current meanings of ``(...)`` and ``[...]`` in Docile if the consensus reached here is to add tuple syntax for this.

**Comment by mbauman** [comment]
Another option might be:

```jl
"documention for head and tail"
head tail
```

Looks like the parser right now just grabs the first expression, but I think it could keep adding arguments to the `@doc` macro until it hits a new line.

**Comment by yuyichao** [comment]
> ```jl
"documention for head and tail"
head tail
```

I guess this won't work for macros. (not sure how much it matters...)

**Comment by one-more-minute** [comment]
I don't think the value/object distinction is important here since this is only happening at the syntax level, not at the value level. If you want to document an array or tuple, you can still do so (and still have to do so) via

```julia
"foo"
const foo = (1,2,3)
# or
"bar"
foo
```

Tuples are nice in that they allow the following syntax:
```julia
"foo"
foo, foo!
```
