### ISSUE TITLE
Cloning coroutines

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#12625]
A colleague recently requested the ability to clone coroutines. Is this something we can or want to support?

cc: @StefanKarpinski @vtjnash @yuyichao @one-more-minute @malmaud

**Comment by jakebolewski** [comment]
Can you outline your colleagues use case?

**Comment by simonbyrne** [comment]
From what I understand, they want to do something similar to this
http://arxiv.org/pdf/1403.0504.pdf

**Comment by jakebolewski** [comment]
Using `fork` to lazy evaluate infinite tree's is a bit crazy.

**Comment by StefanKarpinski** [comment]
Which is probably why they want to clone coroutines instead.

**Comment by vtjnash** [comment]
cloning a coroutine is fork. why aren't they just using a simple work queue with explicit state?

**Comment by simonbyrne** [comment]
@vtjnash They want to apply this to arbitrary programs, so were using coroutines to capture the state. But then they want to be able to fork at certain points in time and let both branches develop independently from then on (corresponding to the resampling step in SMC). 

BTW If anyone wants to collaborate on this, I can put you in touch.

**Comment by vtjnash** [comment]
That sounds like they want a full implementation of process fork, not just the task state.

**Comment by StefanKarpinski** [comment]
The use case is somewhat irrelevant here. Is there any reason we can't have this feature? Cloning a coroutine strikes me as a useful operation, eg for implementing a backtracking algorithm. While there may be more efficient ways to do that on a case by case basis, why not allow this? The implementation seems to be as simple as copying a stack.

**Comment by vtjnash** [comment]
> The use case is somewhat irrelevant here

au contraire, without a use case, it is a lot of work to add and maintain a feature that will always be suboptimal relative to using a closure or explicit work queue. I suspect this feature may interfere with stack-allocating objects, gc-frame elision, and other allocation-scope optimizations since it destroys the assumption that a stack frame is non re-entrant. Also, this does not strike me as a good way to implement backtracking, except as an academic exercise or toy demo.

**Comment by StefanKarpinski** [comment]
> I suspect this feature may interfere with stack-allocating objects, gc-frame elision, and other allocation-scope optimizations since it destroys the assumption that a stack frame is non re-entrant.

Those are legitimate reasons not to implement this – the first ones presented so far.

**Comment by JeffBezanson** [comment]
dup of #4085

**Comment by yebai** [comment]
Greetings, as @simonbyrne mentioned, a small number of researchers at Cambridge University are working a probabilistic programming language embedded in Julia. we are interested in this feature as coroutines seem to provide a significant more efficient mechanism for implementing current probabilistic programming inference algorithms. For this purpose, we need the ability to `clone' suspended coroutines. From the discussion in #4085, it seems this feature is doable in Julia. However, the documentation on implementation of memory management and coroutines seems sparse. After looking at the code (task.c), we have the following questions

1) is the Julia coroutine implementation based on stack copying?
2) If coroutine clone interfere stack-allocating objects, gc-frame elision, and other allocation-scope optimisations, could you give us some details when this may happen? We are happy to investigate this throughly.

**Comment by malmaud** [comment]
@yebai It's better if you post in the open issue for this https://github.com/JuliaLang/julia/issues/4085 instead of commenting on closed issues. 

For what it's worth though, I'm in Tenenbaum's lab and there are students here also interested in having this functionality for prob prog.

**Comment by yebai** [comment]
@malmaud 

thanks! I will post related questions to #4085 in the future. 

ps. we might have seen if you visited Cambridge last year. can you put me in touch with people interested in this functionality? maybe we can work together.
