### ISSUE TITLE
Can no longer copy and paste code into the REPL with __precompile__

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#12623]
I feel this is a basic tenet of Julia (the semantics are the same if you copy/paste into the REPL or include() the file directly).  Although I dislike #pragma's I felt that was one of the advantages for that proposal.  Thoughts?

cc @stevengj

**Comment by stevengj** [comment]
It would be easy to make `__precompile__` only throw an exception if it is called via `require`, just by checking for `toplevel_load::Bool == false` before throwing.

**Comment by jakebolewski** [comment]
closed by #12661

**Comment by stevengj** [comment]
(You shouldn't have had to close it manually, since #12661 had `(fixes #12623)` in the commit message.)
