### ISSUE TITLE
Parsing of x .÷= 1 is broken

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#12626]
```julia
julia> parse("a .÷= 1")

WARNING: deprecated syntax "a .".
Use "a." instead.
ERROR: ParseError("invalid identifier name \"÷=\"")
 in parse at parse.jl:180
 in parse at parse.jl:190
```

**Comment by vtjnash** [comment]
has this ever worked? i thought `.+` and `+` are the same for arrays

**Comment by ninjin** [comment]
> has this ever worked? i thought .+ and + are the same for arrays

v0.3.10 gives a hint in regards to how the expression is parsed:

    julia> v = rand(Int, 4711); v .÷= 17
    ERROR: syntax: invalid identifier name "÷="

So, yes, I am inclined to guess that this has never worked.

**Comment by jakebolewski** [comment]
This was introduced in 0.4 but `.÷` operator has never worked correctly.  Looks like a simple oversight.
