### ISSUE TITLE
Provide MSVC-compatible .lib file in windows bundles

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#12628]
MSVC is still some way off from being a supported build platform, but I don't believe there should be an obstacle to it being a supported platform for embedding (right?). The only wrinkle is that MSVC, unlike, _e.g._, the mingw toolchain, can't link against a bare DLL. It needs a corresponding LIB file. 

Generating a LIB file is pretty straightforward. I've made my own by hand using `dlltool` to both automate the generation of the list of exports for the DEF file and to produce the LIB file from it. The process should be fairly easy to automate, as well.

However, someone seeking to use MSVC for an embedding application would need `dlltool` to get the LIB file they need, since there is nothing in the MSVC toolset for automating a DEF file. That would generally require having cygwin or msys2, which seems unnecessarily burdensome for this use case.

I would like to recommend that we generate and bundle LIB files (or at least DEF files) for `libjulia.dll` and `libjulia-debug.dll` (if the latter makes sense) in our windows downloads.

I'm certainly willing to do the heavy lifting for this, but may require some guidance in getting the details right.

Caveat: I am myself still in the process of determining if I can successfully use MSVC for my embedding application--I'm trying once again to resuscitate my julia-from-a-mex-function embedding, which I had working for a very short window of time, but not for a while now. My success or failure in that will likely influence the degree of motivation I have to carry through with this.

**Comment by twadleigh** [comment]
_Blurg_. I just noticed the `DLLEXPORT`s on all the stuff relevant to embedding in `julia.h`. I'll close this issue as soon as I can verify that I can link without the need for a LIB file.

Sorry for the noise.

**Comment by vtjnash** [comment]
The lib file should be in `usr/lib` on v0.4

**Comment by twadleigh** [comment]
@vtjnash: Ah, I see. So it would just be a matter of making sure those files made their way into the bundle.

**Comment by vtjnash** [comment]
yes, i think it would be OK to add that to the installation

**Comment by tkelman** [comment]
We should be generating a `.dll.a` now which should be equivalent to a `.lib` and usable by either mingw or msvc.

**Comment by twadleigh** [comment]
Closed by d706e62.
