### ISSUE TITLE
Supoptimal inference with recursive-super involving TypeVars

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#12636]
Continuing with my joyful explorations of the corners of the type system.
```jl
module MyColors

abstract Paint{T, N}
abstract AbstractRGB{T}      <: Paint{T, 3}

immutable RGB{T<:FloatingPoint} <: AbstractRGB{T}
    r::T # Red [0,1]
    g::T # Green [0,1]
    b::T # Blue [0,1]
end

myeltype{T}(  ::Type{Paint{T}})   = T
myeltype{T,N}(::Type{Paint{T,N}}) = T
myeltype(::Type{Any}) = Char  # something different from Any so we know it worked
myeltype{P<:Paint}(::Type{P}) = myeltype(super(P))

end
```

Results:
```jl
julia> include("/tmp/super2.jl")
MyColors

julia> MyColors.myeltype(MyColors.RGB{Float16})
Float16

julia> MyColors.myeltype(MyColors.RGB)
Char

julia> @code_warntype MyColors.myeltype(MyColors.RGB{Float16})
Variables:
  #s1::Type{MyColors.RGB{Float16}}

Body:
  begin  # /tmp/super2.jl, line 15:
      return Float16
  end::Type{Float16}

julia> @code_warntype MyColors.myeltype(MyColors.RGB)
Variables:
  #s1::Type{MyColors.RGB{T<:AbstractFloat}}

Body:
  begin  # /tmp/super2.jl, line 15:
      return (MyColors.myeltype)((top(getfield))(P::Type{MyColors.RGB{T<:AbstractFloat}},:super)::Type{T})::Any
  end::Any

julia> @which MyColors.myeltype(MyColors.RGB{Float16})
myeltype{P<:MyColors.Paint{T,N}}(::Type{P<:MyColors.Paint{T,N}}) at /tmp/super2.jl:15

julia> @which MyColors.myeltype(MyColors.RGB)
myeltype{P<:MyColors.Paint{T,N}}(::Type{P<:MyColors.Paint{T,N}}) at /tmp/super2.jl:15
```
So the funny part is that it's using `super` in both cases, but if the call chain reaches `Any` then inference fails.

**Comment by ScottPJones** [comment]
Do you think any of these fun corner cases would be fixed with the new type system that @JeffBezanson showed at JuliaCon?

**Comment by timholy** [comment]
Seems likely---if nothing else, overhauling the type system is a good opportunity to fix bugs. Moreover, what I'm basically trying to do is come up with a traits system that makes it easier to work around the lack of triangular dispatch; since #8974 (I haven't yet watched the JuliaCon video) proposes to add triangular dispatch, it may give me new opportunities.

**Comment by ScottPJones** [comment]
I really do want traits integrated into the language, not just as macros, in particular, for use in representing encodings better (part of https://github.com/quinnj/Strings.jl).

**Comment by timholy** [comment]
`eltype` should basically be thought of as a trait-function, so we do have some traits already; but we could make traits easier to dispatch on.

(To clarify my remark above, I'm not trying to come up with a general traits system; I'm trying to come up with one that's useful specifically for working with Colors, which heretofore have required [scary amounts of code specialization](https://github.com/timholy/Images.jl/blob/d42633363f702c944826bcbf07562e34a79c39ba/src/map.jl#L243-L328).)

**Comment by ScottPJones** [comment]
I think the issues with Colors is very similar to the issues of really dealing well with string encodings, even just dealing with Unicode and subsets thereof, so I hope you get that figured out!

**Comment by timholy** [comment]
You can replace that `myeltype(::Type{Any}) = Char` with `mytype{N}(::Type{Paint{TypeVar(:T),N}}) = Char`. The dispatch works (see #12596), but inference doesn't. Consequently, my suspicion is that this is happening because inference is just punting once it realizes the type is a non-leaf type.
