### ISSUE TITLE
More informative dispatch errors after a module has been reloaded 

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#12651]
After the module `A` is reloaded, all the objects that have types from the previous version of `A` would fail for the new module methods dispatch. That is logical and expected behaviour. However, the error messages `MethodError: '<func>' has no matching <func>(<args>)` will be somewhat confusing, because the `args` they list have absolutely valid types.
It would be nice, if stale module types will be somehow distinct from the current ones on print, i.e. `::A#id.<typename>`.

**Comment by KristofferC** [comment]
`reload` is gone
