### ISSUE TITLE
Matrix p-norm definition in docs is ambiguous

### ISSUE THREAD

**Issue by marcusps** [JuliaLang/julia#12653]
In the docs, the matrix norms defined in base are described simply as `p` norms.  Unfortunately, the nomeclature and the notation is ambiguous. It is unclear if Julia implements Holder p-norms (matrix norm induced by the vector p-norm) or Schatten p-norms (the vector p-norm of the singular values of the matrix).  Which p-norm one expects depends on their field of study (I myself was expecting Schatten p-norms).  It turns out Julia implements Holder p-norms.

I don't think the default needs to change, but clarifying the docs would be nice, at least where matrix norms are mentioned explicitly.

**Comment by timholy** [comment]
Would you be willing to edit the section in `base/docs/helpdb.jl`? See https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation

**Comment by jiahao** [comment]
Related: #4767

**Comment by marcusps** [comment]
Yep, I'll submit a pull request.
