### ISSUE TITLE
at-enum and precompilation

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#12665]
```julia
__precompile__()
module TestModule
@enum MyEnum foo=1
end
```
```
julia> using TestModule
WARNING: eval from module Enums to TestModule:    
1
  ** incremental compilation may be broken for this module **
```
Loading this module generates a scary warning message. However `Int(TestModule.foo) == 1` even after loading the module from the cache. Therefore I am inclined to disregard this warning. Is that safe? Can it be silenced?

**Comment by vtjnash** [comment]
It's actually a bug in the Enum code: it is calling `eval` in the scope of `Enum` rather than in the scope of `current_module()` (although for the trivial case where the expression isn't an Expr or Symbol (like the `1` above), calling eval was unnecessary anyways).
