### ISSUE TITLE
Dates' CompoundPeriod forces Week periods, makes easy stuff not

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#12674]
Many calendar (date+time) operations involve getting a multi-unit displacement, cleaning it up (61 minutes -> 1 hour + 1 minute) and using it with other displacements aor date+time values.  In most uses, date+time values are not written to include explicit week numbers (it happens, not enough to be controlling).  So, for most applications, the cleaned up displacements work best without week units.  Currently, CompoundPeriod(s) spill to and borrow from Weeks always.

``` julia
julia> print(Day(8)," but ", Day(8)+Second(0))
8 days but 1 week, 1 day
julia> print(Second(-1)," but ", Day(0)+Second(-1))
-1 second but -1 week, 6 days, 23 hours, 59 minutes, 59 seconds
```

This makes it hugely difficult to use Date's periods cleanly, and precludes augmenting CompoundPeriod handling without power tools, that is a shame.
We should stop the spill/borrow at Day and allow spill/borrow to Week rather than disallowing Days as the largest unit resolved in this manner.

Here is question that brought this to light [Ian's problem](https://groups.google.com/forum/#!topic/julia-users/3fcObKgFOBY)

**Comment by JeffreySarnoff** [comment]
If you just stop the spill/borrow at days, I will solve [Ian's problem](https://groups.google.com/forum/#!topic/julia-users/3fcObKgFOBY).

**Comment by stevengj** [comment]
So if you have `Week(1) + Day(1)` you would want it canonicalized to `Day(8)` in the `CompoundPeriod` constructor?

(#12282 might help somewhat here by shortening the negative periods.)

**Comment by stevengj** [comment]
Ian's problem from the mailing list seems independent of this: he just wants more conversion routines, e.g. into hours.

**Comment by JeffreySarnoff** [comment]
He does, but the difficulty he had belies the more fundamental issue.
The CompoundPeriods do not roll themselves up when applied as selectors, so doing what seems sensible looses information, unless the rolling up is done by hand.  And when it is done by hand using CompoundPeriods, then the issue about spilliing into/borrowing from Week arises.  Ian is not using Week information.  He needs to store # of minutes and # of hours (maybe days sometimes, that is not clear) and cannot do that without additional correcting for the system behavior. 

The spill to/borrow from Week is implicit in the way CompoundPeriods are coded (which is nifty).  I did not see an easy hook to modifying the behavior.  After spending a day trying to use CompoundPeriods and do what Ian asked, albiet more generally -- I let go of CompoundPeriods and did some old timey stuff that should be auto-available from Dates, somehow.

It seems the CompoundPeriods Week thing would not be an obsticle -- and that is how I approached it.  There is something that really wants to be there, something that would have let Ian run his solution first or second try.

**Comment by JeffreySarnoff** [comment]
```julia
julia> Week(compound::Base.Dates.CompoundPeriod) = compound.periods[1]

julia> compound = Day(0) - Minute(15)
-1 week, 6 days, 23 hours, 45 minutes

julia> weeksCompounded = Week(compound)
-1 week

# at minimum, imo, we need the following to work, giving
# -1 days, 23 hours, 45 minutes

julia> compound - weeksCompounded + convert(Day, weeksCompounded)
-1 week, 6 days, 23 hours, 45 minutes  # I don't want to store weeks
                                       # But they will not go away

# better still would be
compound = convert(Day, compound)
-1 days, 23 hours, 45 minutes

**Comment by stevengj** [comment]
@JeffreySarnoff, I don't agree with your proposed semantics.   `DatePeriod` types should basically act like arithmetic units, so `Week(compound)` should follow the semantics of other conversions: it should throw an `InexactError` if the compound cannot be exactly converted into weeks.  `round(Week, compound)` can round to the nearest week.

**Comment by StefanKarpinski** [comment]
I agree: `round`, `floor` and `ceil` all seem applicable here.

**Comment by JeffreySarnoff** [comment]
I welcome the disagreement.  I fully agree that that Week(compound) should
follow the semantics of the other conversions.
My position on the semantics of these PeriodTypes is (a) non-compound
Period types and compound Period types are intensional cousins, they should
co-mingle and separate without calling attention to their differentness.
 (b) the illustration with Week is intended as a methodological carrier; I
have written and used similar to that, applying the semantic intent and
operational character equally fully to all expressions of Period types.  It
is no small assist when adding adds, subtraction subtracts and instanced
zero-objects are considerate enough to take their own leave rather than
continually assert their presence irrespective the needs of a designer and
the overarching theme:  "It just works."


On Tue, Aug 18, 2015 at 8:09 PM, Steven G. Johnson <notifications@github.com

**Comment by oscardssmith** [comment]
This has been fixed.
