### ISSUE TITLE
Embedding Julia in C/C++

### ISSUE THREAD

**Issue by wcalhoun516** [JuliaLang/julia#12673]
Hello,

I am currently on a OSX 10.10.4 with the latest version of Julia (0.3.11) and the latest version of G++ compiler and Xcode. I have tried following the simple instructions on how to compile and run a basic C program calling Julia. But I cannot get passed certain errors.

> High-Level Embedding
> We start with a simple C program that initializes Julia and calls some Julia code:

> ```c++
#include <julia.h>
int main(int argc, char *argv[])
{
    /* required: setup the julia context */
    jl_init(NULL);
    /* run julia commands */
    jl_eval_string("print(sqrt(2.0))");
    /* strongly recommended: notify julia that the
         program is about to terminate. this allows
         julia time to cleanup pending write requests
         and run all finalizers
    */
    jl_atexit_hook();
    return 0;
}
```
> In order to build this program you have to put the path to the Julia header into the include path and link against libjulia. For instance, when Julia is installed to `$JULIA_DIR`, one can compile the above test program `test.c` with gcc using:

> `gcc -o test -I$JULIA_DIR/include/julia -L$JULIA_DIR/usr/lib -ljulia test.c`

I find and link the libjulia.so library. I find and include the julia.h. But I get the following:
![screen shot 2015-08-17 at 6 10 52 pm](https://cloud.githubusercontent.com/assets/13322558/9317691/62f20bf4-450b-11e5-9244-5a9a1b10d4e8.png): Which says that uv-darwin.h cannot be found. Looking at my include directory that file isn't in the Julia binary. Any help would be much appreciated. All I want to do is run simple commands from Julia in a simple C/C++ file.


Thank you!

**Comment by tkelman** [comment]
Hm, strange. #9330 means this should be included in the binaries? You can try copying the file manually from https://github.com/JuliaLang/libuv/tree/julia-uv0.11.26/include and see if that helps.

**Comment by StefanKarpinski** [comment]
(Cross-posted: http://stackoverflow.com/questions/32060843/embedding-julia-in-c-c-on-osx)

**Comment by ihnorton** [comment]
Answered on StackOverflow. (questions like this should go to either StackOverflow or julia-users in the future -- please don't double-post).
