### ISSUE TITLE
can't start julia from non-directory

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12671]
```sh
$ mkdir nonexist
$ cd nonexist
$ rmdir ../nonexist
$ ~/julia/julia
julia: /home/jameson/julia/deps/llvm-3.3/lib/Support/Unix/Path.inc:256: static llvm::sys::Path llvm::sys::Path::GetCurrentDirectory(): Assertion `false && "Could not query current working directory."' failed.
Aborted
```

**Comment by JeffBezanson** [comment]
What do you suggest? Should we check for this and give a better error?

**Comment by StefanKarpinski** [comment]
Can we avoid having LLVM throw this exception? Why does LLVM need the path? Perhaps this could be fixed upstream.

**Comment by vtjnash** [comment]
there's no need to block startup. just error if you try to access it:
```
shell> rmdir ../nonexist

julia> pwd()
ERROR: getcwd: no such file or directory (ENOENT)
 in uv_error at ./stream.jl:946
 in pwd at ./file.jl:8
```

**Comment by JeffBezanson** [comment]
Agreed. Does this still happen when llvm assertions are disabled?

**Comment by ihnorton** [comment]
> Does this still happen when llvm assertions are disabled?

Just tested with an old nightly: no.

(for reference: https://github.com/groue/llvm/blob/2b4f4910458f9bfd15315444ed47b4f41473a93d/lib/Support/Unix/Path.inc#L251)

**Comment by ihnorton** [comment]
Looks like this may have been fixed in recent LLVM versions. `GetCurrentDirectory` was removed, and the (apparent) replacement `current_path` [does not appear to assert?](https://github.com/llvm-mirror/llvm/blob/5931147ea2ab70361256c1a8a261b3021d6fbd5b/lib/Support/Unix/Path.inc#L187-L220), as of at least LLVM 3.5.

**Comment by timholy** [comment]
This may have regressed, see #17998.
