### ISSUE TITLE
Pkg.available lists un-installable packages

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#12680]
On current master:
```jl
julia> "Bebop" in Pkg.available()
true

julia> Pkg.add("Bebop")
ERROR: ErrorException("Bebop can't be installed because it has no versions that support 0.4.0-dev+6807 of julia. You may need to update METADATA by running `Pkg.update()`")
```

"Bebop" only runs on 0.2 and 0.3: https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/Bebop/versions/0.0.1/requires

(Similary, "AxisAlgorithms" is in Pkg.available() on 0.3, but requires 0.4-. But probably a backport is overkill here.)

**Comment by kshyatt** [comment]
The problem is specifically here: https://github.com/JuliaLang/julia/blob/master/base/pkg/read.jl#L23. `Read.available()` doesn't check to make sure the `"requires"` there actually allows the current Julia version. I'm unsure of the most elegant way to fix this.

**Comment by IainNZ** [comment]
It could be even worse, e.g. package A allegedly works on any Julia version but depends on package B which is <= 0.3, so you'd need to walk the whole dependency tree.

**Comment by wildart** [comment]
@kshyatt `Read.available` works fine. Fix needed to be done in [Entry.available](https://github.com/JuliaLang/julia/blob/77bef6e5ecdadc4f41f70b7a63209b8c6e212cd7/base/pkg/entry.jl#L82) - filter out all package by Julia version.

**Comment by kshyatt** [comment]
@wildart Ah ok, when I was looking at it it seemed like it was only calling `Read.available()` and not `Entry.available()`.

**Comment by wildart** [comment]
`Read` module reads METADATA directory. `Entry` module contains all `Pkg` calls which wrap all functionality. I'll make a PR that'll fix this problem.

**Comment by kshyatt** [comment]
Cool, thanks for the explanation!

**Comment by jakebolewski** [comment]
Seems like you just need
```julia
haskey(reqs,"julia") && VERSION ∉ reqs["julia"] && continue
```
in Entry
