### ISSUE TITLE
dates/adjusters.jl omits lastdayofyear(dt::DateTime)

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#12690]
just an oversight -- following the pattern, one would add
```julia
lastdayofyear(dt::DateTime) = DateTime(lastdayofyear(Date(dt)))
```

**Comment by ivarne** [comment]
cc: @quinnj

**Comment by rawls238** [comment]
it looks like this method has been added, we should be able to close this issue?

**Comment by quinnj** [comment]
Indeed, it resides [here](https://github.com/JuliaLang/julia/blob/7315f52a4cae5014da8f0c9a044816e773483de3/base/dates/adjusters.jl#L95)
