### ISSUE TITLE
using and include changes

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#12695]
See https://github.com/JuliaLang/julia/issues/9079 and https://github.com/JuliaLang/julia/issues/4600. The first half should be done for 0.4:

- make `using` and `import` look in current directory only when in REPL or top-level script
- while loading other code, only look in `Pkg.dir()` and `LOAD_PATH`

The second half should be explored in the next release cycle:

- implement #4600 to allow relative using and import

**Comment by kmsquire** [comment]
I know this is trying to solve #9079, but I don't love the idea of things running differently between the command line and the REPL.

**Comment by tkelman** [comment]
We lived fine with the behavior prior to #9079, and changing it caused way more issues than it fixed. I think avoiding loading from the current directory would be fine for now.

**Comment by StefanKarpinski** [comment]
I would be ok with not looking in the current directory even in the REPL or top-level of a script. With #4600 one would be able to write `using .Foo` to load `Foo.jl` from the current directory in the REPL.

**Comment by nalimilan** [comment]
+1 to not looking in the current directory and not introducing a different behaviour at the REPL.

**Comment by JeffBezanson** [comment]
Fine with me.

**Comment by aviks** [comment]
`include` continues to be relative to the file, right? 

Happy with this, thanks!

**Comment by JeffBezanson** [comment]
> include continues to be relative to the file, right?

Correct.
