### ISSUE TITLE
Issue documenting splat methods

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#12701]
```julia
julia> "foo"
       f() = 1
f (generic function with 1 method)

julia> "bar"
       f(x...) = 1
f (generic function with 2 methods)

help?> f
search: f fd for fma fld fft full find filt fill fft! fdio frexp foldr foldl

  bar
```
@MichaelHatherly you changed this recently so you might have some ideas. `which` is working correctly:

```julia
julia> which(f, ())
f() at none:2

julia> which(f, (Vararg{Any},))
f(x...) at none:2
```

**Comment by one-more-minute** [comment]
Ok, looks like this is due to documenting the first element of this array:

```julia
julia> methods(f, (Vararg{Any},))
2-element Array{Any,1}:
 f() at none:2    
 f(x...) at none:2
```

**Comment by MichaelHatherly** [comment]
It's due to [this line](https://github.com/JuliaLang/julia/blob/bbb30510098d3962cd12893aec105610b2043d5a/base/docs/Docs.jl#L320) where the first method from ``methods`` is taken as the correct one.

```
julia> methods(f, Tuple{})
1-element Array{Any,1}:
 f() at none:2

julia> methods(f, Tuple{Vararg{Any}})
2-element Array{Any,1}:
 f() at none:2    
 f(x...) at none:2
```

**Comment by one-more-minute** [comment]
Is it safe to change that to `which`?

**Comment by MichaelHatherly** [comment]
Related: https://github.com/JuliaLang/julia/pull/12518

**Comment by MichaelHatherly** [comment]
> Is it safe to change that to which?

The issue linked there gives an example where it isn't.

**Comment by one-more-minute** [comment]
Using `end` instead of `1` fixes this case and doesn't break the tests. I'm going to go with that for now we'll leave this open as well, just in case it crops up again.

**Comment by MichaelHatherly** [comment]
:+1:, sounds fine to me.
