### ISSUE TITLE
Can't call "keys" on an empty dict

### ISSUE THREAD

**Issue by philipithomas** [JuliaLang/julia#12709]
```
keys(Dict{"foo"=>"bar"}) # Succeeds
keys(Dict{Any,Any}) # Error
```

Expected behavior is returning a null `Array[Any]`. I'm using v0.3.3.

**Comment by philipithomas** [comment]
Can fix with `Dict()` as an empty dict instead of `Dict{Any,Any}`

**Comment by IainNZ** [comment]
I'm confused, `keys(Dict{Any,Any})` is asking for the keys of the type `Dict{Any,Any}`, and the first thing isn't valid syntax.
