### ISSUE TITLE
Want space in complex function call expressions

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12714]
This expression
```
((x,y,z) -> x*y+z) (1.0,2.0,3.0)
```
leads to a warning with current 0.4 Julia:
```
WARNING: deprecated syntax "(x,y,z)->(block (line 1 none) (call + (call * x y) z)) (".
Use "(x,y,z)->(block (line 1 none) (call + (call * x y) z))(" instead.
```
(The warning message looks strange, but that's not my main issue here... For example, the warning should say something like "you cannot have a space before a function call arguments parenthesis. It shouldn't remove the spaces around `->` if it is try to tell me something about where to put spaces. It shouldn't change function calls to `call` if it tries to tell me something about function calls. It shouldn't omit the second half of the expression, leaving a hanging opening parenthesis.)

I understand why the space before a function call arguments parenthesis. However, the function that is called is here not a simple identifier but a more complex expression. I think in this case the space before the parenthesis makes perfect sense. At the very least, removing the space here doesn't improve readability in any way.

Can we change the rule about no space before function call parentheses to only apply if preceded by an identifier (as in `f(x)`), and not if the expression is more complex (as in `(f ○ g) (x)`)?

**Comment by JeffBezanson** [comment]
I would be against this; it seems too complex and fiddly.

**Comment by simonster** [comment]
Me too. But yeah the warning could be worded better.

**Comment by vtjnash** [comment]
this is where @carnaval's goal of having the parser track source code expression character regions would be a big improvement, to be able to print the user string (with `~~~^^~` notation) on error instead of a de-parsed version
