### ISSUE TITLE
Elementwise operators not rendering properly in ReadTheDocs

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#12718]
In the [ReadTheDocs](https://julia.readthedocs.org/en/latest/manual/mathematical-operations/#chaining-comparisons) I see the following rendering:

![image](https://cloud.githubusercontent.com/assets/734386/9392377/475de502-474a-11e5-907e-e0d7834f6334.png)

and

![image](https://cloud.githubusercontent.com/assets/734386/9392387/5668d610-474a-11e5-986a-ca3b2eca718d.png)

But looking at the source:

```
The operator :obj:`.<` is intended for array objects; the operation
``A .< B`` is valid only if ``A`` and ``B`` have the same dimensions.  The
operator returns an array with boolean entries and with the same dimensions
as ``A`` and ``B``.  Such operators are called *elementwise*; Julia offers a
suite of elementwise operators: :obj:`.*`, :obj:`.+`, etc.
```

Looks like something isn't happy about the RST rendering names starting with periods?

**Comment by pao** [comment]
This isn't new (the release-0.3 documentation shows the same thing) so marking as `doc` rather than `docsystem`.

**Comment by kshyatt** [comment]
This looks like it's rendering properly now?
