### ISSUE TITLE
race condition in creating Timers

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12719]
there is a race condition in creating a Timer: if the `@schedule` block is delayed, the timer may fire and trigger the condition variable before `task` is watching for the event. one possible workaround might be to use `@task` and then directly place `task` into the waitq for `t.notify` and call the callback immediately upon entry to the task. another option would be to use a `Channel` instead of a Condition as the basic operator @JeffBezanson 

```julia
function Timer(cb::Function, timeout::Real, repeat::Real=0.0)
    # stream.jl:625
    t = Timer(timeout, repeat)
    task = @schedule begin
        while isopen(t)
            success = try
                wait(t)
                true
            catch # ignore possible exception on close()
                false
            end
            success && cb(t)
        end
    end
    t
end
```

(this has shown up sporadically on travis as a failure of the pollfd test)

**Comment by JeffBezanson** [comment]
Edge-triggering feels like the right thing for a Timer.

Directly modifying `t.notify` is not ok. We could add a call for having a specified task wait for an event, which should be ok as long as it's in the `:runnable` state. That seems like the best option. I guess a 2-argument form of `wait`? An alternative is to create the timer un-started, and start it directly inside the `@schedule` block, but that's not as good --- the timer start is delayed, and it breaks the normal model of how timers are created.
