### ISSUE TITLE
throw correct LoadError from compilecache

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12724]
Since `Base.compilecache` runs in a subprocess, any exception that is thrown is printed to stderr but is not rethrown in the parent process, which just throws an `ErrorException`.

This is annoying in the case of a module `Foo` that has a syntax error or something else that would ordinarily throw a `LoadError` on `import`.   All of the nice formatting etcetera (e.g. coloring in the terminal, or special handling in IJulia/Jupyter) is lost and the `LoadError` gets printed as plain text, and then an `ErrorException` is thrown in addition.

Is there some way to serialize the `LoadError` and backtrace from the child process so that they get rethrown in the parent process?

**Comment by bermanmaxim** [comment]
I hit this same issue today, by trying to catch the absence of a file loaded using `JLD`:
```
using JLD
try
    a = load("test.jld", "w0")
catch y
    if isa(y, LoadError)
        a = rand(1000);
        save("test.jls", "a", a);
    else
        rethrow()
    end
end

LoadError: File test.jld cannot be found
while loading In[45], in expression starting on line 9

 in jldopen at /home/.julia/v0.4/JLD/src/JLD.jl:142
 in jldopen at /home/.julia/v0.4/JLD/src/JLD.jl:209
 in jldopen at /home/.julia/v0.4/JLD/src/JLD.jl:219
 in load at /home/.julia/v0.4/JLD/src/JLD.jl:1111
```
the `catch` sees `y` as a general `ErrorException` instead of a `LoadError`, despite this name being printed on screen.

**Comment by timholy** [comment]
LoadError changed quite drastically in #29901, #30900, and perhaps others. I suggest we close this as the test case is no longer reproducible and the OP doesn't contain a test case.
