### ISSUE TITLE
*.ji file unchanged after re-precompilation failed  

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#12720]
For example, when testing packages with `Pkg.test()`, julia tries to precompile the package, and that fails with a syntax error, but the old `.ji` file is not deleted, neither exception is thrown and `Pkg.test()` proceeds with the old precompiled version of the package.

**Comment by stevengj** [comment]
Hmm, a side effect #12699.  It should probably begin by deleting any existing `.ji` file before trying to generate a new one.

**Comment by stevengj** [comment]
(Although even before #12699 it seems like a similar problem would occur if the `.ji` file were locked.)

**Comment by IainNZ** [comment]
I guess I'm :+1: on this, fortunately I was paying attention at the start of the tests, but its easy to miss

**Comment by stevengj** [comment]
The deeper problem here is that `init.c` is ignoring the return value of `jl_save_incremental`: https://github.com/JuliaLang/julia/blob/e0b45100a64ffb1b250b8b6f8f0d8dfbf320f583/src/init.c#L629

**Comment by alyst** [comment]
@stevengj Thanks!
