### ISSUE TITLE
inconsistent search path for compilecache (still looks in .)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12722]
After #12695 and 75ab3602fcaf224dfcc550dad684125936e4bc44, `require` no longer looks in the current directory. However, `Base.compilecache` [uses include](https://github.com/JuliaLang/julia/blob/e0b45100a64ffb1b250b8b6f8f0d8dfbf320f583/base/loading.jl#L317) and so it still looks in the current directory.

This inconsistency needs to be fixed by 0.4, I think.

**Comment by JeffBezanson** [comment]
Actually I think the real problem is https://github.com/JuliaLang/julia/blob/e0b45100a64ffb1b250b8b6f8f0d8dfbf320f583/base/loading.jl#L331

`compilecache` uses `include`, but it passes it an absolute path. However it should pass `nothing` as the working directory to `find_in_path` the way `require` does.

**Comment by stevengj** [comment]
Right, that should do it.

**Comment by stevengj** [comment]
Note that recompiling a stale cache file still works even if the module is no longer in the path, because the cache file embeds the absolute path of the module it came from.  This leads to the odd situation where `using Foo` works if Foo was *ever* in the path and was compiled, but ceases to work if the cache file is deleted.

This would be solved by making the `LOAD_PATH` part of the `.ji` file header, but I think it would be annoying to have to recompile all your packages whenever you change the load path.   A nicer alternative:  when loading `Foo.ji`, consider it stale if the stored path of `Foo.jl` does not match what `find_in_path(Foo.jl)` returns.

**Comment by stevengj** [comment]
(I should have a PR shortly.)
