### ISSUE TITLE
Jupyter doesn't recognize Latex

### ISSUE THREAD

**Issue by konsbn** [JuliaLang/julia#12738]
On writing this `\alpha = 2.0` it gives this 
`
syntax: extra token "alpha" after end of expression
while loading In[4], in expression starting on line 1
` 
What should I do?

**Comment by pao** [comment]
Press <key>tab</key> after typing `\alpha`.

This is the wrong place for this--questions about Julia should go to the julia-users mailing list at https://groups.google.com/forum/#!forum/julia-users, and bugs in IJulia should be filed at the IJulia repository at https://github.com/JuliaLang/IJulia.jl/issues.
