### ISSUE TITLE
Cross package dependency testing

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/julia#12730]
Somehow there should be a facility -maybe by proper travis configuration- to test sets of dependent packages. 

My current example is Colors.jl (https://github.com/dcjones/Gadfly.jl/pull/664#issuecomment-133379524) where the developers can test local changes, but there isn't automatic testing of the set of influenced packages (for those not folling the development Colors.jl is replacing Color.jl which is used almost everywhere in graphics and plotting).

**Comment by yuyichao** [comment]
Pkgeval?

**Comment by lobingera** [comment]
with proper configuration, maybe. Pkgeval looked like it's testing Package A in the current/latest version and using latest versions of dependencies. 

This here is more on testing branches of Packages together.

**Comment by rsrock** [comment]
I do this locally with a dummy package that just calls the relevant tests for sets of other packages.  Not fully automatic, but it works in practice.

**Comment by tkelman** [comment]
If the `REQUIRE` format supported url's, branches, and/or git shas then this could possible fall out of using `test/REQUIRE`. For now I don't think there's anything specifically to do on this issue in base. An easy workaround is adding a few `Pkg.checkout` lines in your travis test script.

**Comment by timholy** [comment]
Good suggestion, @rsrock!

**Comment by rsrock** [comment]
Pretty sure I learned that one from you!

**Comment by timholy** [comment]
I've forgotten more than I ever learned. Thanks for reminding me about that trick!
