### ISSUE TITLE
Second of two consecutive strings is ignored

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12737]
With Julia 0.4.0-dev, the input `"a" "b"` in the REPL leads to the output `"a"` instead of a string concatenation or an error. The second string `"b"` is silently discarded.

**Comment by JeffBezanson** [comment]
Possibly related:

```
julia> "docs"
       global xx = 10
  docs
```

The doc string seems to be printed.

**Comment by mbauman** [comment]
Hah, you just documented `"b"` with the docstring `"a"`.  I agree it's pretty surprising, but I guess the only strange thing here is that it returned the docstring instead of the object being documented (or maybe both, displayed with `@doc` syntax?)

**Comment by JeffBezanson** [comment]
I'm not sure we need to allow documenting strings. It seems like in every case you'd want to document a string-valued variable instead of the string itself.

**Comment by eschnett** [comment]
It seems that one can document functions, variable definitions, and simple values (e.g. strings, integers). Expressions and function calls cannot be documented; this leads to a method error.

**Comment by artkuo** [comment]
I've traced the problem down to operators.jl, which is compiled after about a dozen other .jl files by sysimg.jl. Docstrings in files earlier than that (e.g. range.jl) can get the error. Also docstrings in operators.jl up to line 11: `==(x,y) = x === y`. After that, docstrings seem to be okay. This would appear to be addressed by #13602, although I haven't tested it.

**Comment by MichaelHatherly** [comment]
> This would appear to be addressed by #13602

This isn't addressed by #13602. The reference in https://github.com/JuliaLang/julia/pull/13534#issuecomment-147946880 to this issue was regarding duplicating the docstring appearing to fix the issue, not the `==` to `===` change I've made in #13602.

**Comment by artkuo** [comment]
Doesn't #13602 now allow early docstrings? My interpretation is that if you had a docstring earlier than that line 11, the original code was using == before it was defined as such, and caused errors, as was the case in #13534. Not by fixing that line 11, but allowing docstrings to be defined without relying on it. I hope I'm not misunderstanding. In any case, #13602 was a nice fix and certainly cleared up the problem I was seeing.
