### ISSUE TITLE
getindex(::Factorization) not type stable

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12748]
The current idiom for accessing components of a matrix `Factorization` object is by indexing. For example, `eigfact(M)[:values]` returns the eigenvalues of `M` after computing its spectral factorization, which is stored in an `Eigen` type. However, `eigfact(M)[:values]` returns a vector while `eigfact(M)[:vectors]` returns a matrix. The result is that `getindex(::Eigen)` is not type stable and static analysis cannot infer a concrete return type.

Consequently, linear algebra code building upon computed matrix factors must either make special effort to avoid the type instability, or break the abstraction of the `Factorization` object by directly accessing its fields, or else risk degraded performance if the lack of a concrete return type pollutes type inference downstream.

See

- #10863 where code in Base was rewritten to use direct field access instead of `getindex`
- #12747, where a type assertion was necessary to guarantee a concrete return type

and also this simple code illustrating the problem, annotated with the inferred types given by `code_warntype`:

```jl
function svdvals_in_ascending_order(A::Matrix{Float64})
    S = svdfact(A) #SVD{Float64,Float64,Matrix{Float64}}
    Σ = S[:S] #Union{Array{Float64,1},Array{Float64,2}}
    sort!(Σ, rev=false) #Any; method with kwarg is hard for Julia to analyze
end
```

It seems like we should think more about whether the `getindex` idiom makes sense when the `Factorization` object consists of heterogeneous fields. I vaguely recall this issue being raised before, but I couldn't find it on GitHub.

**Comment by andreasnoack** [comment]
Dup of #3021
