### ISSUE TITLE
Markdown code refactor

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#12740]
Currently a lot of things in the markdown code use vectors of functions. This is a bit of a code smell and makes debugging very difficult. It would be much clearer if different flavors of markdown were represented as subtypes and the lists of functions were just function calls inside of generic methods.

cc @one-more-minute, @MichaelHatherly

**Comment by MichaelHatherly** [comment]
Also cc @hayd since you've got an [open PR](https://github.com/JuliaLang/julia/pull/11421) for refactoring some of the stuff in ``Base.Markdown``.

@StefanKarpinski, were you thinking of 0.4 or 0.5 for this?

**Comment by StefanKarpinski** [comment]
Definitely post-0.4 although it could be backported, so 0.4.x/0.5. This is a nice-to-have, not essential at all. I was just trying to track down [a bug](https://github.com/JuliaLang/julia/commit/7676a6abd189d6904a38d1a0972c060591917fcf) that was happening deep in the markdown code and it was unusually tricky because of the "lists of functions" design.

**Comment by jakebolewski** [comment]
:+1:
