### ISSUE TITLE
`?'` does not work in the REPL (cannot look at documentation of transpose operator)

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12756]
It is not possible to look at the documentation of the transpose operator `'` by typing `?'` in the REPL:
```
LoadError: syntax: incomplete: invalid character literal
```

**Comment by MichaelHatherly** [comment]
Dup of https://github.com/JuliaLang/julia/issues/12438?

Search terms that aren't complete expressions just need to be added to the ``Base.Docs.keywords`` dict to make them available:

```
help?> '
ERROR: syntax: incomplete: invalid character literal

julia> Base.Docs.keywords[symbol("'")] = doc"Transpose operator."
  Transpose operator.

help?> '
search:

  Transpose operator.
```

They're all defined in [basedocs.jl](https://github.com/JuliaLang/julia/blob/5fc444fc59315ebc5ce3a3af080d2764e37dceea/base/docs/basedocs.jl).

**Comment by mbauman** [comment]
It is a dupe now.  :)
