### ISSUE TITLE
[C 05:11:05.325 NotebookApp] Bad config encountered during initialization:

### ISSUE THREAD

**Issue by vikohtb** [JuliaLang/julia#12751]
When I try to run IJulia send me this 
[C 05:11:05.325 NotebookApp] Bad config encountered during initialization:
[C 05:11:05.325 NotebookApp] Unrecognized flag: '--profile'
ERROR: failed process: Process(`ipython notebook --profile julia`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:502
 in notebook at /home/vikohtb/.julia/v0.3/IJulia/src/IJulia.jl:177
 in notebook at /home/vikohtb/.julia/v0.3/IJulia/src/IJulia.jl:176
And the directory src does not exist.

**Comment by tkelman** [comment]
Did you update ipython versions recently? You probably need to re-run `Pkg.build("IJulia")` if it was working before but doesn't any more. If that doesn't fix it, the proper place to file IJulia issues is at https://github.com/JuliaLang/IJulia.jl/issues
