### ISSUE TITLE
Make info and warn colors configurable.

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#12753]
My personal preference is that warnings not look like errors. The current behavior is that both are red. Also, the current choice for `info` color (blue) hurts my eyes in the windows REPL.

It would be nice if the color choice for both `info` and `warn` were configurable, say, through `ENV` like input and answer colors are.

I'll submit a PR for comment shortly.

**Comment by stevengj** [comment]
Although this is not documented, it's already configurable, as [described on the mailing list](https://groups.google.com/forum/?fromgroups=#!searchin/julia-users/repl$20colors$20steven/julia-users/FQn_FkFtUFY/tN7dZ4z8fRMJ).

**Comment by twadleigh** [comment]
Only prompt colors and input and output text are configurable via `LineEditREPL`, no?

**Comment by stevengj** [comment]
Oh, right.  Carry on.

**Comment by ViralBShah** [comment]
Closed in #12754
