### ISSUE TITLE
unary operators eat function call parentheses when argument is a tuple

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12755]
This is Julia 0.4-dev in the Jupyter REPL.

This calls `f` with two arguments: `f(1,2)`
This calls `f` with one argument: `f((1,2))` (the argument is a tuple).
This calls `+` with two arguments: `+(1,2)`
But this doesn't work: `+((1,2))` -- it still calls `+` with two arguments instead of a tuple. This is very counter-intuitive, and I argue it is wrong.

Work-arounds are this: `(+)((1,2))` (put operator into parenthesis) or this: `+((1,2),)` (enforce a single-argument function call via a trailing comma).

(This trailing-comma syntax is documented for tuples; is it also intended and/or documented for function calls?)

The same issue exists for `-`, `!`, and `~`.

**Comment by eschnett** [comment]
Here is a test case: Compare the values of
```
:( (+)((1,2)) ) |> string
```
and
```
:( (+)((1,2)) ) |> string |> parse |> string
```
which differ, i.e. `string` and `parse` disagree about the meaning of this construct.

**Comment by JeffBezanson** [comment]
Yes, I think this can/should be fixed.

**Comment by mschauer** [comment]
@timholy What was the intention of the revert, should this be reopened?

**Comment by KristofferC** [comment]
@mschauer  https://github.com/JuliaLang/julia/issues/12771

**Comment by mschauer** [comment]
Thanks.

**Comment by stevengj** [comment]
Seems be fixed nowadays:
```jl
julia> +((1,2))
ERROR: MethodError: no method matching +(::Tuple{Int64,Int64})
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  +(::Pkg.Resolve.FieldValue, ::Pkg.Resolve.FieldValue) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Resolve/fieldvalues.jl:43
  +(::Float32, ::Float32) at float.jl:400
  ...
Stacktrace:
 [1] top-level scope at REPL[13]:1
```

**Comment by mschauer** [comment]
Reference: #26154
