### ISSUE TITLE
readall doesn't 

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/julia#12764]
according to https://github.com/dcjones/Gadfly.jl/issues/288#issuecomment-70868905
readall might be used to read an image/png to string (Uint8). However, it doesn't.
```

lobi@orange4:~/juliarepo$ ../julia04/julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6738 (2015-08-15 04:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 181c19f* (8 days old master)
|__/                   |  x86_64-linux-gnu

julia> r = readall("a22.png")
"Error showing value of type UTF8String:
ERROR: UnicodeError: invalid character index
 in next at ./unicode/utf8.jl:69
 in print_escaped at strings/io.jl:97
 in print_quoted at strings/io.jl:114
 in show at strings/io.jl:31
 in anonymous at show.jl:1280
 in with_output_limit at ./show.jl:1257
 in showlimited at show.jl:1279
 in writemime at replutil.jl:4
 in display at REPL.jl:114
 in display at REPL.jl:117
 in display at multimedia.jl:151
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:622
 in run_interface at ./LineEdit.jl:1601
 in run_frontend at ./REPL.jl:857
 in run_repl at ./REPL.jl:166
 in _start at ./client.jl:453
```

**Comment by Keno** [comment]
Try `readbytes` instead.

**Comment by lobingera** [comment]
Well, actually i did. I was wondering, if readall should be read any file into a string, as presented in the doc

readall(filename::AbstractString)

    Read the entire contents of an I/O stream as a string.

    Open filename, read the entire contents as a string, then close the file. Equivalent to open(readall, filename).

**Comment by Keno** [comment]
It does, the problem is that your image is binary and thus not a valid UTF8String.

**Comment by timholy** [comment]
Also note the reported error is during `show`, suggesting the file itself probably got read. You can try looking at the `data` field.

**Comment by lobingera** [comment]
I'm confused now? 
a) readall reads all (regardless of content) to a string. But displaying assumes UTF-8.
b) documentation should inclued: But your content need to be UTF-8.

**Comment by ScottPJones** [comment]
This is where Julia needs a real binary string type (@quinnj's WIP https://github.com/quinnj/Strings.jl would handle that neatly).
@lobingera It's not that the content needs to be UTF-8, it's that it needs to be *text*.  Your variable r was set, it just caused an error because Julia always tries to display the last answer (ans), and since there is no binary string type, `readall` has returned it incorrectly as a `UTF8String`, and `show` chokes on it.
A binary string type could have a special `show` method, that maybe displayed the bytes in hex.

**Comment by ScottPJones** [comment]
To work around those problems, you could make a wrapper for `readall`, `readallbytes`, that simply returned the `.data` part of the returned string.

**Comment by lobingera** [comment]
@ScottPJones 
I think it would be entertaining to find a  differentiation between a *UTF-8 string* and *text* ...

**Comment by ScottPJones** [comment]
@lobingera Of course there is a differentiation.  A Unicode string would always be text, but not all text strings are in Unicode.  An AbstractString may be lots of things besides the specific `UTF8String` type.
The display code only assumes that it is text, which could be any of `ASCIIString`, `UTF8String`, `UTF16String` or `UTF32String`, saying "But your content need to be UTF-8." would be incorrect.

**Comment by JeffBezanson** [comment]
`readallbytes` => `readbytes`

**Comment by ScottPJones** [comment]
Much better solution, hadn't seen that yet.
