### ISSUE TITLE
Optionally warn when methods specialize on concrete types

### ISSUE THREAD

**Issue by jballanc** [JuliaLang/julia#12774]
Since Julia only allows sub-typing abstract types, if a library author wants their code to be usable with custom concrete types then their functions should only specialize on abstract types. For type hierarchies such as `Int` --> `Int32`, `Int64`, etc. it's relatively clear which is abstract and which is concrete. However in the case of `Dict`, a library author could be forgiven for not realizing that `Dict` is *not* abstract (and that they should have used `Associative` instead).

It would be nice if there was an optional warning that could be enabled when writing/testing library code that would alert when a method signature used a non-abstract type.

**Comment by johnmyleswhite** [comment]
How would the warning work? It seems like you'd need a declaration like `@is_fully_concrete` at the method definition site to make it easy to distinguish between intentionally non-concrete type signatures and accidentally non-concrete type signatures.

**Comment by jballanc** [comment]
In my mind I was imagining something akin to Clojure's `*warn-on-reflection*`, which library authors will usually turn on during development but developers typically leave off in production apps. I'm also assuming that for the vast majority of library methods, it would be desirable to only ever specify the abstract type.

The exceptions I can think of would be numeric libraries that need to be concerned with the width of concrete types, but I would guess that such libraries would not turn on this warning in the first place. The other exception I can think of would be concrete types defined by the library. Perhaps the warning should only alert to the use of imported concrete types?

**Comment by jakebolewski** [comment]
I feel that is issue is mislabeled, you *want* methods to specialize on concrete types (or leaf types) for performance.  What you are really asking for is a dynamic dispatch warning.

As a note, issues like these don't really move things forward.  Everyone agrees that better performance tooling would be fantastic  We can debate concrete implementations of these ideas, but their debating vague notions of their existence is not really helpful.

**Comment by IainNZ** [comment]
As an aside, 
> For type hierarchies such as Int --> Int32, Int64, etc. it's relatively clear which is abstract and which is concrete

`Int`, `Int32`, and `Int64` are all "concrete", `Int` is just a type alias for one. `Integer` is the abstract type.

**Comment by JeffBezanson** [comment]
I think it's way too common, and reasonable, to specialize methods on concrete types to do anything about this.

**Comment by jballanc** [comment]
Understand completely, thank you all for the comments regardless!
