### ISSUE TITLE
Macros and docstrings

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#12782]
I have some macros that generate types and a few constructors for it. Right now this fails because the doc macro expects a single structure and I don't see a good way to document the type generated by the macro. Would it be reasonable to have docstrings on a block document the first thing in the block. Extremely simplified example:
```
julia> macro createStruct()
       quote
       type foo
       end
       foo(x::Int) = foo()
       end
       end

julia> """
       Some documentation
       """
       @createStruct
ERROR: Invalid doc expression begin  # none, line 3:
    type #4#foo
    end # line 5:
    #4#foo(#5#x::Int) = begin  # none, line 5:
            #4#foo()
        end
end
```

**Comment by mauro3** [comment]
Dup of #12705.

**Comment by yuyichao** [comment]
I think for types, making the type as the return value of the expression should work (at least it used to). Otherwise dup of the other issue.

**Comment by mauro3** [comment]
No, that doesn't work anymore:
```
julia> macro m()
       quote 
       type A; end
       5
       A
       end
       end

julia> "doc" @m
ERROR: Invalid doc expression begin  # none, line 3:
    type A
    end # line 4:
    5 # line 5:
    A
end
```

**Comment by yuyichao** [comment]
> No, that doesn't work anymore:

OK. Yeah I haven't been following the discussion there and haven't update my julia for two weeks now ;-p...
