### ISSUE TITLE
Tuple{} vs tuple() in Generated Function Vararg type

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12783]
Consider:

``` julia
julia> @generated function f(x...)
           println("x in generated function: ", x)
           :(println("typeof(x) in function that is run: ", typeof(x)))
       end;

julia> f(1, 2)
x in generated function: (Int64,Int64)
typeof(x) in function that is run: Tuple{Int64,Int64}
```

As you can see, `x` in the generated function is not actually the type of `x` in the method that is run. I would have expected that both would be `Tuple{Int64,Int64}`.

**Comment by mbauman** [comment]
See comments at https://github.com/JuliaLang/julia/pull/10380#issuecomment-96801830 and following.  In order to change this, I think we need a `Tuple` API first.

**Comment by JeffBezanson** [comment]
Yeah, on further reflection I think this is actually better. If tuple types are easier to access it makes even more sense.

**Comment by quinnj** [comment]
Giving a bump here as I recently ran into wanting tuple types being easier to work w/.

**Comment by JeffBezanson** [comment]
Here's one problem. Given

```
@generated f(x...) = # something
```

For the call `f(Int, Int)` you currently get `x = (Type{Int}, Type{Int})` when the generator is called. However, at run time `typeof(x)` is going to be `Tuple{DataType, DataType}`, so binding `x` to that at code generation time loses information.

**Comment by StefanKarpinski** [comment]
We may want to consider generated functions to be an unstable feature even post 1.0.

**Comment by JeffBezanson** [comment]
I propose closing this.

**Comment by JeffBezanson** [comment]
Passing a tuple here doesn't bother us enough to be worth changing.
