### ISSUE TITLE
profile: Document how to save and load profile data

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#12796]
Being able to save profile data on one machine and analyze / visualize it on another would be useful.

**Comment by timholy** [comment]
It's already done: see `Profile.retreive()` and JLD.

**Comment by StefanKarpinski** [comment]
Thanks, Tim. I'm a little unclear on how to use if from the documentation. Should I use JLD to serialize the output of `Profile.retrieve` and then load it on another system?

**Comment by timholy** [comment]
> Should I use JLD to serialize the output of Profile.retrieve and then load it on another system?

Yep.

Someone else will have to write the doc improvement; I'm too close to it, so it all seems obvious to me. (I'm not doubting that it isn't obvious, I'm just saying I'm not the right person to see where the sticking points are.)

**Comment by StefanKarpinski** [comment]
Ok. I also think it would be good to be able to export the information in some kind of standard data format like CSV so that it can be loaded into a DataFrame or Excel (gasp!) for data analysis.

**Comment by johnmyleswhite** [comment]
I started working on generating JSON since we'd want something like that for Atom integration.

**Comment by timholy** [comment]
Since it's a tree structure, it won't be entirely trivial for DataFrames or Excel to handle it. Unless all you care about is "flattened" profile data.

**Comment by johnmyleswhite** [comment]
I think you can often get rid of the tree structure with some reasonable "conditioning" and "marginalization" to borrow terms from probability theory.

**Comment by StefanKarpinski** [comment]
Right, I was thinking of the flattened form of the data, although I think one may want to have the option of recording the function executing, stack depth, and line number. From that, you can project and aggregate to get a lot of the useful information. Of course, the full tree is the most detailed information, but as you said, that doesn't fit well into a tabular data model.

**Comment by StefanKarpinski** [comment]
Just to be clear, @timholy, I'm absolutely not expecting you to implement this – that's why I tagged it as "up for grabs". You've got more than enough on your plate already and this is a good intro project.

**Comment by timholy** [comment]
Might be unnecessary now with https://github.com/timholy/ProfileView.jl/pull/47.
