### ISSUE TITLE
clarify when field type declaration expressions are evaluated

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12793]
as can be seen in the following code snippet, type field declarations get re-executed during calls to `new`, where the parser perhaps should have instead stuck calls to `fieldtype`:

```
julia> type Z
         a::(println("HI"); Int)
       end
HI
HI

julia> Z
Z

julia> Z(1)
HI
Z(1)

julia> Z(2)
HI
Z(2)
```

alternatively, I would like to propose using `static_eval` instead of `jl_eval_toplevel`, so that only sufficiently simple expressions are valid there. i think the resulting behavior is more intuitive than say, calling `eltype(T)` there (for a type parameterized by {T}`) and silently getting`Any`(because`eltype(::TypeVar)` returns Any). I have not seen code that relies on this ability to use arbitrary expressions and, as shown above, the actual semantics of it are a bit wonky.

**Comment by JeffBezanson** [comment]
I think there is a difference between `eltype(T)` (which should maybe be an error on a TypeVar) and side effects. Right now the behavior is "undefined" w.r.t. side effects. However the behavior of `static_eval` is *also* undefined.

**Comment by Jutho** [comment]
Particularly confusing because: 
```julia
immutable Y{A}
  a::A
  b::(@show eltype(A);eltype(A))
end
y = Y([1,2],3);   # -> prints eltype(A) = Int64
fieldtype(typeof(y),:b) # -> shows the truth: Any
```

**Comment by vtjnash** [comment]
> However the behavior of static_eval is also undefined.

I think it should be possible to define a minimum behavior, for example, that it can handle global constants, syntactic apply_type, and syntactic tuples, and that that it can do so recursively. this is significantly less powerful than the current behavior, but i think that it would cover everything that is actually used about this feature and help the user avoid foolish mistakes:

```julia
julia> T = Float64
Float64

julia> type Z; a::T; end

julia> T = Int32
Int32

julia> Z(1)
ERROR: TypeError: call: in new, expected Float64, got Int32
 in call at none:1
```
