### ISSUE TITLE
getindex broken for Diagonal{Matrix}

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12803]
Iterating over Diagonal{Matrix} is an error right now because of the requirement for `zero{T}` to be defined. We probably would have to define a method like `getindex{T<:AbstractMatrix}(A::Diagonal{T}, i::Int, j::Int) = i == j ? A.diag[i] : zeros(promote_type(eltype(A.diag[i]),eltype(A.diag[j])), size(A.diag[i], 1), size(A.diag[j], 2))` but then I think it should work.

**Comment by kshyatt** [comment]
This is still broken on `master`.
