### ISSUE TITLE
Infinite precompile loop

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/julia#12800]
This one is amusing.  After a `Pkg.update()` followed by `Pkg.test("Images")`, I get

```
< a bunch of the usual Pkg.update and precompile stuff> 
WARNING: Color is deprecated, please use Colors instead. See https://github.com/JuliaGraphics/Colors.jl
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Graphics.ji for module Graphics.
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Images.ji for module Images.
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Color.ji for module Color.
WARNING: Color is deprecated, please use Colors instead. See https://github.com/JuliaGraphics/Colors.jl
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Graphics.ji for module Graphics.
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Images.ji for module Images.
INFO: Recompiling stale cache file /Users/rrock/.julia/lib/v0.4/Color.ji for module Color.
WARNING: Color is deprecated, please use Colors instead. See https://github.com/JuliaGraphics/Colors.jl
```

The fun part is that it continues after I mash on ctrl-C and then ctrl-D to exit Julia.  The messages are still popping up in my shell. And now, after killing that shell, I still have a julia process running at 100%.

**Comment by timholy** [comment]
Your immediate problem likely is due to some dirty package not updating---that `WARNING: Color is deprecated, please use Colors instead` is a sign that something is wrong. (Something is still using `Color` rather than `Colors`.)

But obviously the infinite loop should be fixed.

**Comment by rsrock** [comment]
Indeed, it looks like Images was dirty.  All is well after a reboot and an Images cleanup.

**Comment by mattcbro** [comment]
I am getting WARNING: Color is deprecated, please use Colors instead,  whenever I try to load PyPlot.
Is this related?
I am using Julia 0.3.11 on a 64 bit linux mint platform.

**Comment by timholy** [comment]
Use `Pkg.status()` to figure out which packages are pinned or dirty. Then either discard your local modifications or commit them to a branch (or contribute them upstream).

**Comment by timholy** [comment]
Oh, wait: PyPlot seems not to have been tagged since the switch. CC @stevengj.

**Comment by stevengj** [comment]
Tagged a new PyPlot version.

**Comment by mattcbro** [comment]
OK thanks guys Pyplot is no longer complaining, unlike the rest of my handwritten code.

**Comment by timholy** [comment]
@mattcbro, I'd encourage you to do a little digging around on your own. This issue was advertised on julia-users, and both there and on https://github.com/JuliaGraphics/Colors.jl#migrating-from-colorjl I posted a script to help you convert.

**Comment by kshyatt** [comment]
It seems like everyone's issue was resolved here, right? Reopen if that's not the case.

**Comment by stevengj** [comment]
The problem was worked around by updating the packages, but I don't think the underlying problem was identified (why was there an infinite loop?) or fixed.

**Comment by KristofferC** [comment]
I don't think this is applicable anymore.
