### ISSUE TITLE
rad2deg should use oftype(...,pi)

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12817]
`rad2deg` and `deg2rad` should use `oftype(...,pi)` instead of hard-coded `Float64` values.

**Comment by stevengj** [comment]
Yes, they could use `rad2deg(z::Real) = oftype(z, 180*(z/pi))`, but to save a division it would make sense to keep the current definition for `z::Union(Float16,Float32,Float64)`.

**Comment by eschnett** [comment]
I'm thinking `z * (180 / oftype(z, pi))`, which should be constant folded.

**Comment by stevengj** [comment]
Ah, right.

**Comment by jakebolewski** [comment]
Could you submit a PR?

**Comment by stevengj** [comment]
Will have one in a few mins.
