### ISSUE TITLE
pollfd test fails for small intervals

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#12824]
I've seen this failure on two builds at about the same time when creating RPM nightlies for Fedora. Now the tests pass.

This looks like an indication that the build machine was too busy or something similar, but I wonder whether the tolerance should be increased? Having tests fail depending on the workload of builders adds more noise to the test suite results.

If that really indicates a pathological state of the build machine, feel free to close of course.

```
    From worker 3:       * resolve               in   3.85 seconds
    From worker 2:       * file                  in  18.04 seconds
ERROR: LoadError: On worker 3:
LoadError("/builddir/build/BUILD/julia/test/pollfd.jl",65,ErrorException("test failed: 0.002 <= 0.001800923\n in expression: intvl <= t_elapsed")
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 in pfd_tst_timeout at /builddir/build/BUILD/julia/test/pollfd.jl:59
 in anonymous at task.jl:447)
 in sync_end at ./task.jl:413
 in anonymous at no file:422
 in include_string at loading.jl:233
 in include_from_node1 at ./loading.jl:274
 in runtests at /builddir/build/BUILD/julia/test/testdefs.jl:179
 in anonymous at multi.jl:889
 in run_work_thunk at multi.jl:642
 in anonymous at task.jl:889
while loading /builddir/build/BUILD/julia/test/runtests.jl, in expression starting on line 13
    From worker 3:       * pollfd               Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/julia/test'
Makefile:516: recipe for target 'test' failed
make: *** [test] Error 2
```

https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-rawhide-x86_64/00111484-julia/build.log.gz

**Comment by carlobaldassi** [comment]
From the log, the failure seems to be in pollfd, not resolve.

**Comment by tkelman** [comment]
has been happening intermittently since https://github.com/JuliaLang/julia/pull/12237#issuecomment-130019909

**Comment by nalimilan** [comment]
Seen it again when building official Fedora RPM package:
https://kojipkgs.fedoraproject.org//work/tasks/6543/10866543/build.log

**Comment by nalimilan** [comment]
Could something be done about this? It's annoying when a test rebuild in the Fedora build farms is marked as failing just because of this random bug.

**Comment by nalimilan** [comment]
#14001 increased the smallest interval from `0.002` to `0.005`, as it seems to get rid of the failure on Fedora build VMs. Interestingly, the error message was generally similar to the description above, with an actual time measured of `0.0018`. Looks like elapsed time is not measured correctly.

**Comment by KristofferC** [comment]
Seems obsoleted by #14001
