### ISSUE TITLE
`reinterpret(Float64,Complex(1))` kills Julia

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12832]
````
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6880 (2015-08-21 18:32 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 482aa20 (6 days old master)
|__/                   |  x86_64-apple-darwin14.4.0

julia> reinterpret(Float64,Complex(1))
LLVM ERROR: Cannot select: 0x7fc0518a5a10: f64 = truncate 0x7fc05198c210 [ORD=8705] [ID=4] dbg:essentials.jl:116:1
  0x7fc05198c210: i64 = FrameIndex<0> [ORD=8705] [ID=1]
In function: julia_reinterpret_21170
````

**Comment by vtjnash** [comment]
with llvm assertions:
```
julia> reinterpret(Float64, Complex(3))
Assertion failed: (castIsValid(op, S, Ty) && "Invalid cast!"), function Create, file /Volumes/Lion/Users/jameson/Documents/julia/deps/llvm-3.3/lib/IR/Instructions.cpp, line 2290.
```

I started work on fixing this on my jn/codegen_rewrite branch. The main problem here is that reinterpret is abusing Intrinsics in ways that they were not designed to handle gracefully.

**Comment by StefanKarpinski** [comment]
It's a bit unclear how to better implement this. Maybe a `reinterpret` intrinsic for scalar reinterpret?

**Comment by vtjnash** [comment]
In the codegen_rewrite branch, I removed the `box` and `unbox` intrinsic and replaced them with a `reinterpret` intrinsic. I also wrote some of the error handling to detect this case, but writing a codegen version of some of the tests (such as `isbitstype(T)`) is fairly difficult, so some of those cases can still cause failures.

**Comment by timholy** [comment]
@vtjnash, I'm a bit vague here on the significance of the difference between `isbits` and `is_bitstype`. On master, the reason https://github.com/JuliaGraphics/ColorTypes.jl/issues/31#issuecomment-191392231 failed is that in `jl_is_bitstype`, the `jl_datatype_nfields(v) == 0` part is evaluated as false when `v` is an `NTuple`. I wasn't sure why this was an important part of the criterion, so I tried this:
```diff
$ git diff
diff --git a/src/runtime_intrinsics.c b/src/runtime_intrinsics.c
index e6d7678..f026bd4 100644
--- a/src/runtime_intrinsics.c
+++ b/src/runtime_intrinsics.c
@@ -17,9 +17,9 @@ const unsigned int host_char_bit = 8;
 JL_DLLEXPORT jl_value_t *jl_reinterpret(jl_value_t *ty, jl_value_t *v)
 {
     JL_TYPECHK(reinterpret, datatype, ty);
-    if (!jl_is_leaf_type(ty) || !jl_is_bitstype(ty))
+    if (!jl_is_leaf_type(ty) || !jl_isbits(ty))
         jl_error("reinterpret: target type not a leaf bitstype");
-    if (!jl_is_bitstype(jl_typeof(v)))
+    if (!jl_isbits(jl_typeof(v)))
         jl_error("reinterpret: value not a bitstype");
     if (jl_datatype_size(jl_typeof(v)) != jl_datatype_size(ty))
         jl_error("reinterpret: argument size does not match size of target typ
diff --git a/test/core.jl b/test/core.jl
index 4a9910c..6523389 100644
--- a/test/core.jl
+++ b/test/core.jl
@@ -3870,3 +3870,14 @@ let
 end
 @test j15283 == 1
 @test !isdefined(:k15283)
+
+module ReinterpretBitsType
+    using Base.Test
+    immutable RGB
+        r::UInt8
+        g::UInt8
+        b::UInt8
+    end
+    c = RGB(0x01,0x05,0xff)
+    @test reinterpret(NTuple{3,UInt8}, c) == (0x01, 0x05, 0xff)
+end
```
The new test passes, as does the rest of the test suite except for [this line](https://github.com/JuliaLang/julia/blob/9f697b023950af0f26840cbe2546bb06c75702ff/test/numbers.jl#L2523), for which that statement returns `0.0 + 1.875im`. `reinterpret(Float64, [Complex64(0,1.875)])` suggests that's the correct answer.

Is that failure guarding against something important that I'm missing?

CC @lobingera.

**Comment by vtjnash** [comment]
This change would allow you to bypass the constructor for these types and construct potentially invalid immutable objects directly. It also exposes padding somewhat incorrectly. It's just not really clear that this should be allowed.

@carnaval wants to remove the `jl_isbits` distinction since it should really be seen as an implementation detail of the gc, not a language property (the language features here are `bitstype` and `immutable`).

**Comment by timholy** [comment]
> This change would allow you to bypass the constructor for these types and construct potentially invalid immutable objects directly.

You can already do that, using `reinterpret(T, [x])`.

> It also exposes padding somewhat incorrectly.

That sounds more serious. Is it clear that `nfields(v) == 0` is the right test for that? I'm thinking of
```jl
julia> reinterpret(Tuple{Int}, 3)
ERROR: reinterpret: expected bits type as first argument
```

**Comment by timholy** [comment]
And, am I wrong in presuming that the padding issues would be the same for `reinterpret(T, [x])`?
