### ISSUE TITLE
mysterious pointer printed during tests

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#12837]
See https://travis-ci.org/JuliaLang/julia/jobs/77620430 for example.

```
	From worker 2:	     * libdl                 in   0.32 seconds
	From worker 3:	     * misc                 Ptr{Void} @0x0000000017595bf0
	From worker 2:	     * int                   in   0.85 seconds
```

From what I can tell, first appeared with 366e2d5329a009e4096d1a2477181e3c4b8a6fda, but I don't see how.

**Comment by vtjnash** [comment]
is it from `misc`? maybe some show method is forgetting to forward the `io` argument?

**Comment by kshyatt** [comment]
I ran all the tests individually after it appears and none show it. If I run `make test-misc` locally nothing out of the ordinary happens.

**Comment by kshyatt** [comment]
In recent builds (e.g. [this](https://travis-ci.org/JuliaLang/julia/builds/77721928)) it seems not to be present either.

**Comment by KristofferC** [comment]
I got it while running only sparse tests on a 14 days old build. And then there was many pointers printed, not just one. Haven't tried any on new builds though.

**Comment by JeffBezanson** [comment]
I still see this locally, but like @kshyatt not when running test-misc by itself.

**Comment by tkelman** [comment]
backported in #13182
