### ISSUE TITLE
Loop unrolling

### ISSUE THREAD

**Issue by AlexanderKUA** [JuliaLang/julia#12845]
I'm new to Julia. I wonder why the loop in the following code isn't unrolled.
The operator '*' here is pure and have no side effects. I've checked @code_native for the same code with native types and it's looks it's unrolled correctly.

    function test(n::Int, count::Int)
               A = rand(n, n)
               x = rand(n)
               y = zeros(n)
               tic()
               for i = 1 : count
                   y = A * x
               end
               toq()
           return y
           end

lang: Julia v3.11
OS: Windows/Linux

**Comment by StefanKarpinski** [comment]
Why would the loop be unrolled? The count is a variable.

**Comment by Keno** [comment]
You would get <= 0 speedup by doing that since the blas call is expensive.

**Comment by AlexanderKUA** [comment]
Please take into account that the loop body doesn't changed through loop iterations.

**Comment by mbauman** [comment]
In that case, you're asking for the loop to be constant-folded, not unrolled.  This is a duplicate of other issues which cover this.
