### ISSUE TITLE
MEMPROFILE is broken

### ISSUE THREAD

**Issue by MaheshWaidande** [JuliaLang/julia#12840]
Hi All,

I am working on building/porting Julia on ppc64le architecture. I am using Ubuntu 14.10 on top of ppc64le hardware, while compiling Julia code (master branch) I was getting segmentation fault, I am able to resolve this segmentation fault by turning on `MEMDEBUG` flag from `src/options.h` file.

I decided to work more this issue and try to find out root cause of segmentation fault, so I started studying/understanding memory management scheme of Julia. 

To understanding GC and de-allocation mechanism I turn on profiling options `MEMPROFILE`, `GC_TIME` from `options.h`  file (by default they are commented out I uncomment those) but when I try to compile code with these profiling flags on julia compilation (make debug) gets failed.

Below compilation errors I observed after enabling, 
1. `GC_TIME` flag 
   
   ```
   gc.c:237:26: error: current_heap undeclared (first use in this function)
    #define HEAP(x) (*((void)current_heap,&(x)))
   ```
2. `MEMPROFILE` flag
   
   ```
   gc.c:2414:21: error: pool_t has no member named pages
   ```

My Machine details are: 
`Linux 3.16.0-30-generic #40-Ubuntu SMP ppc64le ppc64le ppc64le GNU/Linux`

-Mahesh

**Comment by carnaval** [comment]
MEMPROFILE has been broken for some time IIRC. Feel free to make it work again once you've figured out the allocator :-)
The output always was a bit unreadable anyway.

**Comment by pao** [comment]
Corresponding post to mailing list: https://groups.google.com/d/msg/julia-users/fHS1G_ryDRU/vPUjBcTcBwAJ
