### ISSUE TITLE
deprecated int method fails for non-concrete arrays of strings

### ISSUE THREAD

**Issue by peeterjoot** [JuliaLang/julia#12847]
I asked a question like the following on stackoverflow and Matt B asked me to report this as an issue, stating "The deprecated method should work and the warning message should print a valid suggestion"

I'm unable to convert integer regular expression captures values to an array of integers in Julia 0.4.  

In Julia 0.3 I could do this with int(), basically like:

    c = ["1", "2"] ;
    int(c)

But in Julia 0.4, this works for regular strings:

    julia> c = ["1", "2"] ;
    
    julia> int(c)
    2-element Array{Int64,1}:
     1
     2

but doesn't work with substrings (i.e. regex captures):

    re_dcIV = r"^
    ([IV])(\S+)\s+
    (\d+)\s+
    (\d+)\s+
    DC\s+
    (\S+)\s*$"x ;

    line = "V1 1 2 DC 1" ;

    m = match( re_dcIV, line ) ;

    c = m.captures ;
    println( "$c\n" ) ;

    nodes = int(c[3:4]) ;

which produces:

    julia> nodes = int(c[3:4]) ;
    WARNING: int(x::AbstractArray) is deprecated, use round(Int64,x) instead.
     in depwarn at deprecated.jl:63
     in int at deprecated.jl:49
    while loading no file, in expression starting on line 0
    ERROR: MethodError: `round` has no method matching round(::Type{Int64}, ::SubString{UTF8String})
    Closest candidates are:
      round{T<:Integer}(::Type{T<:Integer}, ::Integer)
      round{T<:Integer}(::Type{T<:Integer}, ::Float16)
      round{T<:Union{Signed,Unsigned}}(::Type{T<:Union{Signed,Unsigned}}, ::Base.MPFR.BigFloat)
      ...
     in round at floatfuncs.jl:72
     in int at deprecated.jl:51

The type of the capture array is:

    Union{SubString{UTF8String},Void}["V","1","1","2","1"]

and I'm not able to execute int(c[3:4]) on a subset of that beastie.

**Comment by yuyichao** [comment]
`int` is deprecated. Use

```
julia> map(x->parse(Int, x), c[3:4])
2-element Array{Int64,1}:
 1
 2
```

The deprecated isue is wrong though.

**Comment by mbauman** [comment]
Thanks!

**Comment by tkelman** [comment]
backported in #13107
