### ISSUE TITLE
CHOLMOD version warning is invisible due to undefined STDERR

### ISSUE THREAD

**Issue by fweimer** [JuliaLang/julia#12841]
The warning added in #10362 is not visible with julia-0.4.0-0.1.20150823git.fc23.x86_64 because the `STDERR` variable (referenced from `warn`) is not yet available. This results in a cryptic backtrace:

    fatal: error thrown and no exception handler available.
    Base.InitError(mod=:CHOLMOD, error=UndefVarError(var=:STDERR))
    rec_backtrace at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    jl_throw at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    jl_undefined_var_error at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    unknown function (ip: 0x7f5cc56d586d)
    unknown function (ip: 0x7f5cd1d940a1)
    jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    unknown function (ip: 0x7f5cc575fa30)
    unknown function (ip: 0x7f5cc5760279)
    jl_apply_generic at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    jl_module_run_initializer at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    unknown function (ip: 0x7f5cd181c921)
    unknown function (ip: 0x7f5cd1814f5c)
    julia_init at /usr/bin/../lib64/julia/libjulia.so (unknown line)
    unknown function (ip: 0x401763)
    __libc_start_main at /usr/bin/../lib64/libc.so.6 (unknown line)
    unknown function (ip: 0x4017b9)
    unknown function (ip: (nil))

**Comment by phobon** [comment]
Since #12742 has been merged, this will no longer crash on master, but it will display that `UndefVarError` instead of the intended warning message. The simplest fix would be to just make those warnings errors. Then they'll be caught and displayed and still not break the initialization.

A more proper solution down the road should be to introduce primitive `STDOUT`/`STDERR` objects early that will work in `__init__` functions.

**Comment by fweimer** [comment]
I'm not sure if making those warnings errors would be a good thing for distributions like Fedora. They would need to have an exact run-time dependency on the suitesparse version which was used to compile Julia, and that would complicate package updates.

**Comment by KristofferC** [comment]
I interpret @phobon saying "Then they'll be caught and displayed and **still not break the initialization**." as that making it an error would be fine, since errors inside `__init__` for CHOLMOD are now being caught.

**Comment by nalimilan** [comment]
Indeed, the warning wouldn't be good either for distributions. If a new SuiteSparse version isn't backward-compatible, it should upgrade the SOVERSION, so that packagers know they need to rebuild all dependencies. Let's discuss this in #10362, and keep the present issue for fixing the segfault.

**Comment by nalimilan** [comment]
#13000 changes the check to be only about the major version.
