### ISSUE TITLE
isdefined does not work for subarray

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#12862]
```
julia> a=Array(Any,3,5)
a=Array(Any,3,5)
3x5 Array{Any,2}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

julia> isdefined(a,1)
isdefined(a,1)
false

julia> isdefined(a,1,1)
isdefined(a,1,1)
false

julia> b=sub(a,1:3,1:3)
b=sub(a,1:3,1:3)
3x3 SubArray{Any,2,Array{Any,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}:
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef

julia> isdefined(b,1)
isdefined(b,1)
true

julia> isdefined(b,1,1)
isdefined(b,1,1)
ERROR: ArgumentError: isdefined: too many arguments (expected 1)
```

**Comment by JeffBezanson** [comment]
`isassigned` should work. I'm surprised to see it's not documented; I don't know how that happened.

**Comment by denizyuret** [comment]
Thank you, `isassigned` indeed works for subarrays and gives sensible answers to test cases above.

One potential issue: if you use isassigned on a subarray using an index out-of-bounds for the subarray but in-bounds for the parent array, you can get true.  However I realized getindex and setindex do not complain in this situation either, so maybe this is by design...

**Comment by bkamins** [comment]
@JeffBezanson: could you please explain what does the word *defined* in documentation of `isdefined` exactly mean if we use an indexable object as an argument? Or maybe `isdefined` function should be used only on `Array` objects when index is provided (this would be implied if we strictly read documentation). If this is the case why does it allow subarray (or other array-like type) as a first argument and not throw an error in such case? In particular I do not understand these cases (in addition to what @denizyuret provided):
```
x = [1,2,3]
z = sub(x, :)
isdefined(x, 4) # returns false
isdefined(z, 4) # returns true
z[4] # bounds error

using DataArrays
y = DataArray(x)
isdefined(x, 3) # returns true
isdefined(y, 3) # returns false
y[3] # works and gives 3
```

**Comment by JeffBezanson** [comment]
`isdefined` is not generic and is only really supposed to work for object fields; we should probably remove its behavior on Arrays. For arrays there is `isassigned`, which can be overloaded.

**Comment by bkamins** [comment]
Thank you. Now I get it, for subarrays etc. `isdefined` checks if `i`-th field of the object is defined.
