### ISSUE TITLE
2e2 parses as 2.0*10^2

### ISSUE THREAD

**Issue by my-little-repository** [JuliaLang/julia#12878]
I am using julia Version 0.4.0-dev+6093 (2015-07-20 07:55 UTC) Commit 4ebdea0* (39 days old master) x86_64-linux-gnu    

      julia> [1+e1+2*e2 for e1 = 0:1, e2 = 0:1]
     2x2 Array{Int64,2}:
       1  3
       2  4

Fine. Now if I omit the multiplication symbol, I get

      julia> [1+e1+2e2 for e1 = 0:1, e2 = 0:1]
      2x2 Array{Float64,2}:
       201.0  201.0
       202.0  202.0

2e2 is not parsed as 2*e2. Is it expected?

**Comment by jiahao** [comment]
Yes. Parsed as a floating point literal takes precedence over juxtaposed multiplication.

**Comment by my-little-repository** [comment]
I see. Maybe a note in the manual advising against the use of variables named e2, f0 etc would be welcome.

**Comment by bicycle1885** [comment]
@my-little-repository I thinks it's already mentioned in the manual: http://julia.readthedocs.org/en/latest/manual/integers-and-floating-point-numbers/#syntax-conflicts
