### ISSUE TITLE
Pkg.update() command is slow. Julia 0.3.2

### ISSUE THREAD

**Issue by ccsv** [JuliaLang/julia#12874]
Not sure if this was fixed but. I am running a  Windows 8 running intel Core i7-4770 CPU @ 3.40GHz.  Running Julia version 0.3.2+2 and I have 13 required packages 48 additional packages.

Running `@time Pkg.status()` takes 29.551148236 seconds (78478756 bytes allocated, 0.18% gc time)

**Comment by tkelman** [comment]
This is well-known. #11196 should help for 0.5.
