### ISSUE TITLE
Can `=>` be put even lower in operator precedence?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#12875]
Just got caught out by combining `=>` with `? :`, e.g.

```
julia> Dict(1 => true ? println("foo") : println("bar"))
ERROR: TypeError: non-boolean (Pair{Int64,Bool}) used in boolean context
```

Except the situation I was in was

```
julia> x = Dict(:foo => 2)
Dict{Symbol,Int64} with 1 entry:
  :foo => 2

julia> Dict(:fizz => 1 == 1 ? x[:foo] : x[:bar])
ERROR: KeyError: bar not found
 in getindex at dict.jl:718
```

Which was very confusing, as I was wondering why would it be evaluating `x[:bar]`

**Comment by rened** [comment]
The precedence was recently increased (#12285), actually. See also Jeff's comment: https://github.com/JuliaLang/julia/pull/12285#issuecomment-127685902

I'd also like to see it more on the level of `=`, that's what the `=>` feels most like for me.

**Comment by IainNZ** [comment]
Ah I see, essentially the same as what you said! Agreed that it feels like it should be at the level of `=`, its got almost the same semantics except I guess in that one case that @JeffBezanson was showing with the `in` thing. I guess this is a wont-fix then :(

**Comment by rened** [comment]
@IainNZ - just to make sure you see the ongoing discussion on https://github.com/JuliaLang/julia/pull/12285#issuecomment-137757692, perhaps this is not a "won't fix" any more

**Comment by IainNZ** [comment]
:+1:
