### ISSUE TITLE
istext("I am text") returns false - rename to `istextmime`

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#12872]
In multimedia.jl, `istext()` is intended to assess MIME types.   But since the `istext()` is exported, it can be taken out of context and generate counter-intuitive results.  Maybe a more descriptive name would be warranted?

From multimedia.jl --
```
# it is convenient to accept strings instead of ::MIME
istext(m::AbstractString) = istext(MIME(m))
```

**Comment by stevengj** [comment]
Probably `istextmime` would be better.

**Comment by ccsv** [comment]
@stevengj  Agreed users can easily confuse MIME types with strings

**Comment by nalimilan** [comment]
Or just remove the convenience version accepting strings. `MIME"some/type"` isn't that long.

**Comment by stevengj** [comment]
@nalimilan, that would work, but you would need to add a method `istext{T}(::Type{MIME{T})`

**Comment by ScottPJones** [comment]
`istext` seems like it would be used to distinguish between binary and text string types.
`ismimetext` instead of `istextmime` I think might be a bit better.

**Comment by JeffBezanson** [comment]
+1 for renaming to something involving `mime`.
