### ISSUE TITLE
Test take too long

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12888]
I notice that the self-tests recently started to take much longer to run than usually. For example, here are some timings from my 4-core MacBook Pro (unloaded, on external power):
```
	From worker 5:	     * sparse                in 154.40 seconds
	From worker 4:	     * bitarray              in 152.85 seconds
        From worker 9:	     * subarray              in 504.07 seconds
	From worker 3:	     * parallel              in 280.17 seconds
```
That's more than eight minutes of testing subarrays -- that doesn't seem right. I somehow don't think it's the subarrays that are to blame; maybe something generic became slower? Or am I imagining this?

**Comment by tkelman** [comment]
Did you recompile with LLVM newer than 3.3? If not, a bisect would be useful.

**Comment by eschnett** [comment]
Yes, I'm using LLVM 3.6.1. Are you saying this is a known issue with more modern LLVMs?

**Comment by tkelman** [comment]
Yep. The biggest remaining issue with #9336.
