### ISSUE TITLE
split() and keyword arguments

### ISSUE THREAD

**Issue by tcovert** [JuliaLang/julia#12892]
The function "split" in utils seems to have an option to limit the length of the returned array using the "limit" keyword, but it does not seem to work.

For example:

julia> split("a, b, c", ','; limit=1)
ERROR: function split does not accept keyword arguments

This seems strange, since there are tests for almost exactly this code in test/strings/util.jl

Am I doing it wrong?

If it helps, here is my versioninfo():

julia> versioninfo()
Julia Version 0.3.11
Commit 483dbf5* (2015-07-27 06:18 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tcovert** [comment]
Nevermind, it seems that the keyworded version of split() is 0.4 only.

**Comment by nalimilan** [comment]
Where did you find the docs mentioning it?

**Comment by tcovert** [comment]
http://julia.readthedocs.org/en/latest/manual/strings/

which I now see is clearly not the documentation for 0.3...

**Comment by nalimilan** [comment]
> which I now see is clearly not the documentation for 0.3...

Yeah, often people get confused about that. The version could be made more visible, I think this was discussed somewhere.
