### ISSUE TITLE
Surprising fallback method for `.*` in `sparse/sparsematrix.jl`

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#12894]
https://github.com/JuliaLang/julia/blob/092bcf46044a43060e0e251db5ad5a5f224547c4/base/sparse/sparsematrix.jl#L906

`(.*)(A::AbstractArray, B::AbstractArray) = broadcast_zpreserving(*, A, B)`

That can't be right, can it?

**Comment by IainNZ** [comment]
I hit this by `.*` two matrices of custom types, where it threw an error because it couldn't cram the result of multiplying two of the elements into the resulting container.

**Comment by tkelman** [comment]
Why not? `broadcast_zpreserving` falls back to `broadcast`, and otherwise it would go to https://github.com/JuliaLang/julia/blob/092bcf46044a43060e0e251db5ad5a5f224547c4/base/broadcast.jl#L289

**Comment by IainNZ** [comment]
It just seemed almost surely unintentional that this method should be living in sparsematrix, despite having nothing to do with sparsematrices in particular, but if you think thats normal then I'm fine with that, its not my area of expertise.

**Comment by IainNZ** [comment]
Also the method being broken kind of sucks, but I guess thats a different issue.

**Comment by tkelman** [comment]
It's probably only there for bootstrap-order reasons. ref #10106
