### ISSUE TITLE
svds does not accept v0 keyword

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12890]
`svds` lacks the ability to specify the starting vector, whereas the underlying `eigs` function it calls does. It would be nice to have the user be able to specify the starting vector, to be consistent with all the other iterative methods.

**Comment by ViralBShah** [comment]
+1 and should be easy to do also.

**Comment by tkelman** [comment]
duplicate of #10330

**Comment by jiahao** [comment]
Derp.
