### ISSUE TITLE
atanh doesnt agree with Wolfram alpha

### ISSUE THREAD

**Issue by skariel** [JuliaLang/julia#12916]
see attached image below. It seems Julia implements the conjugate of the inverse hyperbolic tangent?

![screenshot from 2015-09-02 15 45 23](https://cloud.githubusercontent.com/assets/2347816/9631521/31ce04ca-518a-11e5-83f9-d0bab8c56714.png)

**Comment by yuyichao** [comment]
I think this is correct.

```
julia> atanh(2. + 0.im)
0.5493061443340549 + 1.5707963267948966im

julia> atanh(2. - 0.im)
0.5493061443340549 - 1.5707963267948966im
```

**Comment by yuyichao** [comment]
Just checked some points away from the branch cut and it looks correct and agrees with Wolfram Alpha

```julia
julia> atanh(2. + 0.001im)
0.5493059221119561 + 1.570462993622057im

julia> atanh(2. - 0.001im)
0.5493059221119561 - 1.570462993622057im
```

**Comment by eschnett** [comment]
If you check Wolfram Alpha, you'll see that it doesn't distinguish between `2+0im` and `2-0im`, i.e. it doesn't handle the branch cut correctly. It looks as if it didn't understand signed zeros.
