### ISSUE TITLE
DateTime parsing issues

### ISSUE THREAD

**Issue by GordStephen** [JuliaLang/julia#12928]
As far as I can tell, previously-valid timestrings are now causing parse errors - haven't looked at this too closely but I'd guess it's probably related to some of the recent parsing changes (cc @omus )?

```julia
julia> DateTime("1961-12-31 00:00:00")
ERROR: ArgumentError: Non-digit character encountered
 in getslot at dates/io.jl:143
 in parse at dates/io.jl:158
 in call at dates/io.jl:202
```

**Comment by omus** [comment]
I'll definitely take a look.

**Comment by omus** [comment]
Alright I reverted my revision of Julia to before #12799 was introduced (`099dfd1`) and found that the line you provided does work without throwing an error but isn't what you want:

```
julia> DateTime("1961-12-31 00:00:00")
1961-12-01T00:00:00
```

I would suggest you update your code to include a format like this:

```
julia> DateTime("1961-12-31 00:00:00", "yyyy-mm-dd HH:MM:SS")
1961-12-31T00:00:00
```

**Comment by omus** [comment]
@GordStephen do you have anything to add or can I close this issue?

**Comment by GordStephen** [comment]
So is `yyyy-mm-ddTHH:MM:SS` the only datetime format that can be parsed without a supplied format key now? I can live with that (although `yyyy-mm-dd HH:MM:SS` *is* fairly common), but it might be nice to have some kind of deprication warning / transition period if existing functionality is going to be removed.

**Comment by nalimilan** [comment]
@GordStephen Looks like that's the standard ISO format: https://en.wikipedia.org/wiki/ISO_8601

I don't think we need a deprecation, as the example you give returned incorrect results on 0.3 with Dates.jl:
```julia
# Wrong format
julia> DateTime("1961-12-31 00:00:00")
1961-12-01T00:00:00

# Correct
julia> DateTime("1961-12-31T00:00:00")
1961-12-31T00:00:00
``` 

So it's actually an improvement to get an error here.

**Comment by GordStephen** [comment]
Heh, fair enough!

**Comment by mbauman** [comment]
Perhaps there could eventually be something akin to [python-dateutil's parser](https://dateutil.readthedocs.org/en/latest/parser.html) that automagically reads everything, but that could be a package.
