### ISSUE TITLE
Segfault with an innocent-looking script

### ISSUE THREAD

**Issue by abbradar** [JuliaLang/julia#12927]
https://gist.github.com/abbradar/ee0d0523486ffcc92e6d produces a segfault with Julia 0.3.11, Linux. I've minified this as far as I could but the thing is somewhat a heisenbug -- trying to minify this further or add debugging output results in no error! It's fully reproducible for me, though.

EDIT: Linux abbradarbook 4.2.0 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux

**Comment by abbradar** [comment]
Valgrind output: https://gist.github.com/abbradar/4eb66a7821785f983a6c

**Comment by JeffBezanson** [comment]
Thanks for reporting this.

I'm running into package-related errors before the crash happens:

```
Initialized empty Git repository in /home/jeff/src/julia-0.3/julia/updatedb/Bebop/.git/
fatal: remote error: 
  Repository not found.
ERROR: failed process: Process(`git fetch -t origin`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:502
```

Does this depend on the set of installed packages?

**Comment by abbradar** [comment]
Shouldn't, but bug of that kind would probably manifest randomly depending on compiler version etc. I'll fix it to complete its work, maybe that would increase reproducibility.

3 сентября 2015 г. 19:29:13 GMT+03:00, Jeff Bezanson <notifications@github.com> пишет:
>Thanks for reporting this.
>
>I'm running into package-related errors before the crash happens:
>
>```
>Initialized empty Git repository in
>/home/jeff/src/julia-0.3/julia/updatedb/Bebop/.git/
>fatal: remote error: 
>  Repository not found.
>ERROR: failed process: Process(`git fetch -t origin`,
>ProcessExited(128)) [128]
> in pipeline_error at process.jl:502
>```
>
>Does this depend on the set of installed packages?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/JuliaLang/julia/issues/12927#issuecomment-137503673

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by abbradar** [comment]
Here's the complete script: https://gist.github.com/abbradar/ee0d0523486ffcc92e6d#file-regenerate-packages-jl (actually I'm trying to make Julia infrastructure for Nix package manager, this is one part of it). It segfaults reliably for me; additionally, uncommenting `println("rainbows")` hangs the script at the same place it usually segfaults for me.

**Comment by abbradar** [comment]
I've recompiled Julia by myself using bundled libraries instead of system ones. It seems to work, so the problem is likely in some incompatibility with a system library (I suspect LLVM). I'll investigate this further and reopen if I it looks like a Julia bug after all. Closing for now, sorry for a false call!
