### ISSUE TITLE
Makefile:51: recipe for target 'julia-deps' failed

### ISSUE THREAD

**Issue by adrianor** [JuliaLang/julia#12920]
I don't know why obtain this error while compiling julia on Debian 3.16.0-4-amd64 (I checked all the additional dependencies needed and I think I have them all. I have seen a similar post here from February, perhaps could be the same http://comments.gmane.org/gmane.comp.lang.julia.user/29270. Still I cannot see what is wrong. I do:

```
~/julia$ make
...
make[6]: *** No rule to make target 'install'.  Stop.
...
Makefile:51: recipe for target 'julia-deps' failed
make[1]: *** [julia-deps] Error 2
Makefile:282: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by yuyichao** [comment]
Please include at least a few lines before the error line in the output. It is impossible to tell which dependency is having trouble from your report.

**Comment by adrianor** [comment]
For sure:
llvm[5]: Installing Release Archive Library /home/usr/julia/usr-staging/llvm-3.3/build_Release/home/usr/julia/usr/lib/libLLVMAnalysis.a
make[6]: *** No rule to make target 'install'.  Stop.
/home/usr/julia/deps/llvm-3.3/Makefile.rules:866: recipe for target 'install' failed
make[5]: *** [install] Error 1
/home/usr/julia/deps/llvm-3.3/Makefile.rules:925: recipe for target 'Analysis/.makeinstall' failed
make[4]: *** [Analysis/.makeinstall] Error 2
/home/usr/julia/deps/llvm-3.3/Makefile.rules:866: recipe for target 'install' failed
make[3]: *** [install] Error 1
Makefile:692: recipe for target '/home/usr/julia/usr/lib/libLLVMCodeGen.a' failed
make[2]: *** [/home/usr/julia/usr/lib/libLLVMCodeGen.a] Error 2
Makefile:51: recipe for target 'julia-deps' failed
make[1]: *** [julia-deps] Error 2
Makefile:282: recipe for target 'install' failed
make: *** [install] Error 2

if you need more lines, please let me know

**Comment by nalimilan** [comment]
Please copy the whole output, or at least a few dozen lines before the error. You can put them on a GitHub gist if you want.

**Comment by adrianor** [comment]
This is the whole output:


llvm[2]: Installing include files
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm-c
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm-c/Transforms
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/Assembly
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/Support
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/ExecutionEngine
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/Target
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/Option
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/DebugInfo
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/Object
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Re
lease/home/user/julia/usr/include/./llvm/TableGen
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/IRReader
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/ADT
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/IR
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/MC
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/MC/MCParser
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Bitcode
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Analysis
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/CodeGen
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/CodeGen/PBQP/Heuristics
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Transforms
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Transforms/IPO
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Transforms/Utils
llvm[2]: Making install directory /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/./llvm/Config
llvm[3]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMSupport.a
llvm[3]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMTableGen.a
llvm[4]: Install circumvented with NO_INSTALL
llvm[4]: Install circumvented with NO_INSTALL
llvm[4]: Installing Release /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/bin/llvm-tblgen
llvm[4]: Install circumvented with NO_INSTALL
llvm[4]: Install circumvented with NO_INSTALL
llvm[4]: Install circumvented with NO_INSTALL
llvm[4]: Install circumvented with NO_INSTALL
llvm[5]: Install circumvented with NO_INSTALL
llvm[5]: Install circumvented with NO_INSTALL
llvm[3]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMCore.a
llvm[3]: Installing /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/llvm/IR/Intrinsics.gen
llvm[4]: Installing /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/include/llvm/IR/Intrinsics.gen
llvm[4]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMAsmParser.a
llvm[5]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMBitReader.a
llvm[5]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMBitWriter.a
llvm[4]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMArchive.a
llvm[4]: Installing Release Archive Library /home/user/julia/usr-staging/llvm-3.3/build_Release/home/user/julia/usr/lib/libLLVMAnalysis.a
/home/user/julia/deps/llvm-3.3/Makefile.rules:866: recipe for target 'install' failed
/home/user/julia/deps/llvm-3.3/Makefile.rules:925: recipe for target 'Analysis/.makeinstall' failed
/home/user/julia/deps/llvm-3.3/Makefile.rules:866: recipe for target 'install' failed
Makefile:692: recipe for target '/home/user/julia/usr/lib/libLLVMCodeGen.a' failed
Makefile:51: recipe for target 'julia-deps' failed

**Comment by vtjnash** [comment]
is this a fresh checkout? it looks like your configuration of llvm-3.3 is corrupted -- I suggest deleting deps/llvm-3.3 and running `make` again.

**Comment by adrianor** [comment]
It still complains, this is the last tail:
-----------
okd4o11x13o00*27 3.67026e-16 1.05651e-15 4.21213e-16
ikd4o11x13o00*27 4.20521e-16 1.1739e-15 3.27199e-16
obr84v140 3.66879e-16 5.85602e-16 3.32975e-16
ibr84v140 3.62658e-16 5.85602e-16 4.14876e-16
Executing "/home/jivifair/julia/deps/fftw-3.3.4-double/tests/bench -o nthreads=2 --verbose=1   --verify 'ok25e00v49' --verify 'ik25e00v49' --verify 'obrd5x7x2x7v2' --verify 'ibrd5x7x2x7v2'"
ok25e00v49 3.03745e-16 1.30281e-15 2.53e-16
ik25e00v49 2.85361e-16 1.35946e-15 2.59586e-16
obrd5x7x2x7v2 3.89528e-16 7.22229e-16 3.89585e-16
ibrd5x7x2x7v2 3.70559e-16 7.22229e-16 3.95727e-16
--------------------------------------------------------------
         FFTW threaded transforms passed basic tests!
--------------------------------------------------------------
Making check in mpi
Making check in doc
Making check in FAQ
Making check in tools
Making check in m4
Makefile:51: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

**Comment by tkelman** [comment]
That wasn't the relevant error message, it was something earlier obscured by parallel make. Either scroll up, or rerun make a few times to see the actual error.

**Comment by adrianor** [comment]
Well, that worked: at last I could see the troubleshooting that is here:

*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***

Thanks so much!

**Comment by tkelman** [comment]
Leave another comment if there's anything to leave this issue open for.
