### ISSUE TITLE
Inconsistencies between Array and Dict type inference

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#12932]
`["a", "b"]` gives a `Vector{ASCIIString}`
`["á", "b"]` gives a `Vector{UTF8String}`
but
`Dict(1=>"a",2=>"b")` gives a `Dict{Int64,ASCIIString}`
`Dict(1=>"á",2=>"b")` gives a `Dict{Int64,Any}`
`Dict("a"=>1,"b"=>2)` gives a `Dict{ASCIIString,Int64}`
`Dict("á"=>1,"b"=>2)` gives a `Dict{Any,Int64}`

`[1, [2, 3]]` gives a deprecation warning, and returns `[1,2,3]`, but
`Any[1,[2,3]]` returns a `Vector{Any}` with 2 elements.

There are also examples with mixing integers and floats that are not consistent.

**Comment by JeffBezanson** [comment]
There is a firmly established tradition of numeric arrays, where you expect `[1, 2.0]` to promote the integer. I don't think the same behavior necessarily applies to dictionaries.

The deprecation warning is exactly for the purpose of making `[1, [2, 3]]` return a 2-element vector in the next version.

**Comment by eschnett** [comment]
This is about keys, not values in dictionaries. Since `"a"` and `UTF8String("a")` are not even visually distinguishable in their default output, I would have expected this to be a `Dict{AbstractString, ...}`.

**Comment by ScottPJones** [comment]
About numeric arrays, I think the way that is handled is dangerous, and think it should be consistent with dictionaries, not the other way around.
If you want to say that [ integer, float ] "promotes" the integer when it infers the type of the array, then it should use a convert that gives an InexactError if the integer can not be exactly represented by the float.
`[ 0x1234567890abcdef, 1, 2, 3., 4]`, should that silently truncate the first 64-bit integer, just because somebody may have accidentally added a period?  IMO, it should either promote to `Real`, `BigFloat`, or give `InexactError` when trying to convert to `Float64`.
`Float64[...]` can convert without warning, as that is explicit.

**Comment by StefanKarpinski** [comment]
I think it would be better if dicts followed the same promotion behavior as arrays. What's the justification for the other behavior?

**Comment by ScottPJones** [comment]
The "promotion" by arrays in not good, it can silently lose information.  Much better to have arrays act more like dicts instead, or at least get an `InexactError` rather than data corruption.

**Comment by StefanKarpinski** [comment]
That's not going to happen and we've gone over it before.  Given that all the people who spend all their time working with numerical computations don't have a problem with the current behavior, it's hard to find it credible that it's such a big problem. If you want to make the conversion less lossy, you can take a crack at making `convert(::Type{Float64}, ::Int)` check for exactness, but it may cause a lot of wailing.

**Comment by ScottPJones** [comment]
I've never said that `convert(::Type{Float64}, ::Int)` should check for exactness, just that there should be a `safe_convert` that does check, just as Julia has `checked_*` math functions, and that in cases where the type is *inferred*, instead of explicitly given, then that `safe_convert` should be used, or it should always promote to a type that won't lose information.
I frankly doubt that would cause wailing, it would probably go unnoticed by most people, but people who care that their data doesn't get munged without warning would probably be a lot happier.

You seem to be looking at this only from the perspective of people who put values into data structures only to do numerical computations on them, as opposed to storage, retrieval, and searching.

**Comment by StefanKarpinski** [comment]
That's just too many functions that do similar but slightly different things. Either it matters or it doesn't.

Please don't tell me what perspective I'm looking at problems from.

**Comment by ScottPJones** [comment]
>What's the justification for the other behavior?
>Given that all the people who spend all their time working with numerical computations don't have a problem with the current behavior, it's hard to find it credible that it's such a big problem

That's why it *seems* to me that you are only concerned about one perspective.
You've simply discounted other people's views, saying that they are not even credible.

**Comment by JeffBezanson** [comment]
As things are, it is perfectly possible to accurately store and retrieve values of different types in a single array, for example with an `Any` array.

I understand wanting to give an error for a lossy conversion. However it's very strange give an error when a float result is rounded; that's what they're all about.

**Comment by ScottPJones** [comment]
Using `Any` wouldn't be as efficient as using `BigFloat`, would it?
If somebody really wants everything to be converted (rounded) to a `Float64` or whatever, they can do
`Float64[a, b, c]`.
It's a general problem, not just with integers to floats, should *inferred* conversions ever silently lose data?
Nor would it be as efficient simply having the promotion give an error if not lossless.

Also, on 32-bit machines, all `Int` values *can* be stored without loss in a `Float64`
(because they are really Int32).
If I were calling `round`, then that's what I'd expect, but not `convert`.

**Comment by mbauman** [comment]
`[ 0x1234567890abcdef, 1, 2, 3., 4]` is not inferring the type of the array.  It's promoting the values, just like `0x1234567890abcdef*2.0` promotes to Float64 and subsequently loses precision.  I'd argue that `[1, 2.0]` is just as explicit as `Float64[1, 2.0]`.  And `[0x1234567890abcdef,x]` is just as explicit as `0x1234567890abcdef*x`.  If you're dealing with floating point numbers, inaccuracy is part of the ball game.  But this discussion should really be happening in https://github.com/JuliaLang/julia/issues/12187.

**Comment by JeffBezanson** [comment]
@ScottPJones I understand that, in theory, one wants to avoid data loss. However the fact remains that there is tons of code that assumes you can write `[1, x]` and get something efficient.

As it happens, we also have a fair amount of code that does systemsy kinds of things, like in multi.jl, where we need to handle arbitrary lists of values without any loss. In these cases, you can't lose any value *or* type information. There we tend to use tuples or `Any[]` and I don't think it's been a problem. 

I don't think there are many cases where it's ok to promote various values to Float64, but only if they can all be represented losslessly. Applications that mix ints and floats are fine with rounding the ints, in my experience, because they already accept that the results are only accurate to so many digits.

**Comment by ScottPJones** [comment]
>However the fact remains that there is tons of code that assumes you can write [1, x] and get something efficient.

That's fine - that's why I'd suggested having a way to do that *AND* avoid data loss.
I don't even think it would take more than a few lines of code - I'll try to make a PR this week.

It's statements like this that concern me greatly:
>I think it would be better if dicts followed the same promotion behavior as arrays.

**Comment by ScottPJones** [comment]
Counterpoint, in Python:
```python
>>> x = [0x1234567890123456789, 3.0]
>>> x
[5373003641998677469065, 3.0]
>>> x[0]
5373003641998677469065
>>> hex(x[0])
'0x1234567890123456789'
```

**Comment by johnmyleswhite** [comment]
Python arrays aren't like Julia arrays, so that's a meaningless comparison.

**Comment by ScottPJones** [comment]
Just meant to point out that *silent* data loss is not the only way to handle things in a language.
Somebody just brought up elsewhere problems with rounding modes and early conversions in the parser to Float64.

**Comment by StefanKarpinski** [comment]
Genius. We'll just make Julia numeric arrays dirt slow and take three times the memory. Problem solved.

**Comment by StefanKarpinski** [comment]
It's not entirely clear to me how problematic it would be if we made conversion from Int to Float64 throw an InexactError when the conversion isn't exact – I suspect that when people mix int and float literals the int literals are usually exactly convertible to floating point. On the other hand, `[1.5, pi]` is always going to be inexact and we can't reasonably have that be an error so there is a line to be drawn somewhere.

**Comment by JeffBezanson** [comment]
> Just meant to point out that silent data loss is not the only way to handle things in a language.

This comment is absurd. I think we're done here.
