### ISSUE TITLE
Deprecate scale

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#12945]
When 0.4 has been tagged. I think we should deprecate the `scale` functions (without exclamation marks) in favor of just using multiplication. At least for scaling with a scalar, but I also would prefer `A*Diagonal(x)` over `scale(A,x)` for scaling with a vector `x`.

**Comment by tkelman** [comment]
Would multiplication by a scalar get dispatched to blas, or have the same level of simd?

**Comment by stevengj** [comment]
@tkelman, I don't see why not.   I agree that `scale!` is useful but `scale` is redundant with `*`.

**Comment by Jutho** [comment]
I also think it doesn't matter much whether this is handled by BLAS or by a pure Julia implementation. The dominating factor is probably memory access (and simd), but all the fancy multithreading won't help that much. At least that's the experience I had from some simple comparison a while ago, but I might certainly be misremembering.
