### ISSUE TITLE
Char vs char, and Int vs int

### ISSUE THREAD

**Issue by xxfelixxx** [JuliaLang/julia#12946]
Hi, According to the documentation for Strings ( Doc >>> Strings ), the following should work:

julia> typeof('a')
Char

julia> Char(123)
'{'

However, I get 'ERROR: type cannot be constructed'

It works if I change 'Char' to 'char', i.e. char(123) # '{'

Similarly for 'Int' vs 'int'.

I am running Julia 0.3.0 (2014-08-20  20:43 UTC)

Is the documentation incorrect, or did the language change?

**Comment by quinnj** [comment]
You must be looking at the docs for 0.4 somehow. In 0.4, bitstypes can now be constructed by a call to their type name (or rather, any type can overload `call` with a default fallback of `T(x) = convert(T,x)`). The difference in the docs url should be something like `release0-3` vs. `latest`

**Comment by xxfelixxx** [comment]
Great, thanks!
