### ISSUE TITLE
Expose packages' dependencies

### ISSUE THREAD

**Issue by abbradar** [JuliaLang/julia#12940]
I'm working at packaging entire Julia packages repository for the Nix package manager. One of things that might help me very much is packages' dependencies information. Right now I'm parsing `REQUIRES` files by myself to make Nix packages -- that's an unfortunate code duplication given that somewhere inside `pkg` we already have code which does exactly the thing. I imagine this as some function `dependencies(pkg :: String) -> Requirement[]`.

**Comment by kshyatt** [comment]
Would https://github.com/JuliaLang/julia/blob/master/base/pkg/query.jl#L8 work for you? You can address that with `Pkg.Query.requirements` in your code.

**Comment by abbradar** [comment]
@kshyatt Thank you very much! I haven't known that I can call those functions from my code (I thought they were "hidden" in some way since they weren't mentioned in documentation).

**Comment by IainNZ** [comment]
They are "hidden" in the sense they are not for public consumption. You could also check out https://github.com/IainNZ/MetadataTools.jl

**Comment by StefanKarpinski** [comment]
The file format is also designed to be so simple that a Perl one-liner can parse them.
