### ISSUE TITLE
Generalized SVD intermittent test failure on intel build

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12959]
Current test failures building with the Intel stack:

- [ ] `linalg/svd`
```sh
        From worker 10:      * linalg/svd           
        From worker 10: Intel MKL ERROR: Parameter 5 was incorrect on entry to SORMQR.
        From worker 10: Intel MKL ERROR: Parameter 5 was incorrect on entry to DORMQR.
        From worker 10: Intel MKL ERROR: Parameter 5 was incorrect on entry to CUNMQR.
        From worker 10: Intel MKL ERROR: Parameter 5 was incorrect on entry to ZUNMQR.
        From worker 10: Intel MKL ERROR: Parameter 5 was incorrect on entry to DORMQR.
```
- [x] `cmdlineargs`
```sh
ERROR: LoadError: On worker 105:
LoadError("/home/jiahao/julia-dev-intel/test/cmdlineargs.jl",3,ErrorException("test failed: \"0.4.0-pre\" == \"0.4.0-dev\"\n in expression: Base.VERSION_STRING == chomp(v)"))
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 [inlined code] from /home/jiahao/julia-dev-intel/test/cmdlineargs.jl:6
 in anonymous at no file:0
 in include_string at loading.jl:233
 in include_from_node1 at ./loading.jl:274
 [inlined code] from util.jl:179
 in runtests at /home/jiahao/julia-dev-intel/test/testdefs.jl:6
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:68
while loading /home/jiahao/julia-dev-intel/test/runtests.jl, in expression starting on line 13
        From worker 105:             * cmdlineargs          Makefile:9: recipe for target 'all' failed
```

```sh
ᐅ  icc -v
icc version 15.0.3 (gcc version 4.9.0 compatibility)
```

`Make.user`:

```sh
USEICC = 1
USEIFC = 1
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 1
```

**Comment by tkelman** [comment]
what does `cat src/julia_version.h` say?

**Comment by jiahao** [comment]
The `cmdlineargs` failure went away with `make cleanall && make`, so that was probably because of the stale local cache.

**Comment by jiahao** [comment]
The test failure is coming from deep within MKL's LAPACK API in the generalized SVD `svd(A, B)`. It only happens when
-  running the test with `make -C test linalg/svd`. `./julia test/linalg/svd.jl` does not trigger the error.
- `ggsvd!` is called with `(jobu,jobv,jobq) = ('U','V','Q')` (all generalized singular vectors requested). `(jobu,jobv,jobq) = ('N','N','N')` (no generalized singular vectors requested) does not trigger this error. The call to `xORMQR/xUNMQR` happens within `xGGSVD`, presumably when the generalized singular vectors are being constructed.

**Comment by andreasnoack** [comment]
I also get the error when I don't ask for any vectors or multiplication with `Q`.
```jl
julia> LAPACK.ggsvd!('N', 'N', 'N', copy(b), copy(c));

Intel MKL ERROR: Parameter 5 was incorrect on entry to DORMQR.
```
and I'm wondering if this is a bug in MKL because according to the official LAPACK documentation DORMQR is not even called from DGGESVD. See
http://www.netlib.org/lapack/explore-html/dd/db4/dggsvd_8f.html#af81db37b433882a26f692aeff19f002e

**Comment by jiahao** [comment]
That is puzzling. I wonder if MKL has their own custom implementation of the generalized svd algorithm. It seems unlikely that someone mistyped `DORMQR` for `DORM2R` (which the reference implementation uses), otherwise the `gsvd` would always be wrong.

@kpamnany @ArchRobison can we refer this issue to someone in the MKL group to look at?

**Comment by tkelman** [comment]
I think the MKL group is based out of Moscow, last time I interacted with them. The Intel support forum works pretty well for getting an answer from someone who knows about the details within a reasonable time frame.

**Comment by andreasnoack** [comment]
I should add here that it only happens with `blas_set_num_threads(1)`.

I've asked about this in

https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/591977

**Comment by andreasnoack** [comment]
This is fixed in the MKL of Intel Parallel Studio version 16.0.3.210
