### ISSUE TITLE
`repeat` should allow tuples to specify the counts

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12953]
It seems that the function
```
repeat(A, inner = Int[], outer = Int[])
```
expects arrays to specify the repeat counts. It should also accept tuples, which is presumably more efficient (and which I find more natural in this case).

**Comment by simonster** [comment]
+1. I'd also suggesting making `inner` and `outer` positional arguments, which would make it possible for type inference to infer the result type (although that would still require some work).

**Comment by jakebolewski** [comment]
+1 feel free to submit PR's for these.

**Comment by johnmyleswhite** [comment]
Yeah, I agree on all counts with these suggestions

**Comment by nalimilan** [comment]
This has annoyed me several times too. It looks like it could also accept any `AbstractArray` as first argument.

@simonster If you make `inner` and `outer` positional, you won't be able to specify the latter without the former, will you?

**Comment by ScottPJones** [comment]
@nalimilan could you define a method `repeat(arr::AbstractArray; outer = ...)` for that case?

**Comment by nalimilan** [comment]
That would probably work, but it would a bit weird to have two different ways of specifying an argument. Not sure we want to start this pattern.

**Comment by ScottPJones** [comment]
What about a method that takes Void() as the second argument, to indicate just specifying outer?

**Comment by nalimilan** [comment]
Indeed, that's the best option (though writing it `nothing` is more common, I think).

**Comment by ScottPJones** [comment]
Yes, @JeffBezanson just merged in Void() = nothing, which is why I thought of it that way!

**Comment by tkelman** [comment]
@ScottPJones please stop frivolously notifying people who aren't even involved in a discussion. We're all busy and get too many emails.

**Comment by nalimilan** [comment]
So, shall we add a version using positional arguments and deprecate that with keyword arguments? I guess the loosening of the signature could be backported to 0.4 without risks.

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/julia/pull/14082 implements the move to positional arguments.
