### ISSUE TITLE
MKL needs custom error handler

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12968]
Issues like #12959 which trigger errors from within Intel MKL's LAPACK interface do not throw Julia exceptions, because MKL's [default error handler](https://software.intel.com/en-us/node/529174) simply prints the error to the console and attempt to call the system `exit()` function. Julia appears to intercept the `exit()` call (the calling Julia process does not die), but it does not raise a corresponding `ErrorException`.

It looks like MKL's default error handling can be overridden by [mkl_set_exit_handler](https://software.intel.com/en-us/node/529175) and [mkl_set_xerbla](https://software.intel.com/en-us/node/522149), but we don't do so currently.

**Comment by andreasnoack** [comment]
I think the idea is that the wrappers should check the inputs such that LAPACK never returns an error. In very rare situations error can happen when there are bugs in LAPACK therefore, even though it would be an improvement to handle errors from LAPACK correctly, I don't think it is that important either.

**Comment by tkelman** [comment]
Wouldn't some error conditions be impractically expensive to check prior to the lapack call? Anything cheap to check we probably should, but that won't cover everything.

**Comment by andreasnoack** [comment]
I don't think so. The fatal errors are typically when the inputs take illegal values which is cheap to test for. They can also happen if there is a convergence problem in an algorithm, but I'm pretty sure that is always considered a bug. Expensive problems with the input matrices that are only discovered as part of the algorithm don't cause a fatal error but is instead signaled by a non-zero info value.

**Comment by kshyatt** [comment]
Re @andreasnoack's comments, is this still something we need to do?

**Comment by tkelman** [comment]
It would be an improvement, and situations like IJulia would require intercepting the error condition printing, so yes it should be done but no it's not critical enough that it's worth putting a must-do deadline on it.

**Comment by ViralBShah** [comment]
This should be done in MKL.jl, if something needs to be done.
