### ISSUE TITLE
Fix segfaults due to ANY

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#12967]
See ab6e83c2e9f344c47e4421c6be530a46ffa17248

**Comment by JeffBezanson** [comment]
Reference https://github.com/JuliaLang/JLD.jl/issues/19

**Comment by vtjnash** [comment]
reduction:
```julia
julia> foo(x, ::ANY) = 1
foo (generic function with 1 method)

julia> typealias TupleType{T<:Tuple} Type{T}
Type{T<:Tuple}

julia> foo(x, ::TupleType) = 2
foo (generic function with 2 methods)

julia> foo(1, Int)
1

julia> foo(1, Tuple{})
1
```

**Comment by JeffBezanson** [comment]
Plz confirm whether this fixes the JLD problem.

**Comment by timholy** [comment]
On current master I can run the JLD tests without a segfault; I can also run the Gtk tests and some of my other graphics code without having applied https://github.com/JuliaLang/Gtk.jl/commit/06d49cd91edafb869e5afb66c128b0e79b8f8a74. I agree that this is fixed. Nice work, @JeffBezanson and @vtjnash!

0.4 ho!
