### ISSUE TITLE
Pkg.add("JuMP")

### ISSUE THREAD

**Issue by ghazalj** [JuliaLang/julia#12974]
hello all 
this is my first time using julia as im trying to add JuMP the following happens

```julia
Pkg.add("JuMP")
fatal: bad default revision 'HEAD'
ERROR: failed process: Process(`git '--git-dir=C:\Users\ghazal\.julia\v0.3\.cache\Calculus' log --all --format=%H`, ProcessExited(128)) [128]
 in wait at task.jl:284
 in wait at task.jl:194
 in wait at task.jl:48
 in sync_end at task.jl:311
 in add at pkg/entry.jl:319
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:30
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20
```

did i do anything wrong in running the software?
what should i do?

**Comment by tkelman** [comment]
Try deleting `C:\Users\ghazal\.julia` and trying `Pkg.add("JuMP")` again.

**Comment by ViralBShah** [comment]
Is there something we can do here to give a better error?

**Comment by tkelman** [comment]
Stop using command-line git. No idea what went wrong here, but at least with libgit2 we should be able to get better error information back.

**Comment by ghazalj** [comment]
In julia website there are 3 step of downloading julia
First is julia itself then its juni and the next is something else that I don't remember
I skipped the third one
Butniw i download it and it is working

Also the first time that you are adding the package is important no interruption be connected to internet 

I might be weong but now mine is working

**Comment by tkelman** [comment]
Those aren't steps, those are 3 different ways in which you can use Julia.

Yes, git and Pkg are not especially robust against flaky internet connections when you install or update packages, and you can get your packages into corrupted states that way. I think there have been past issues on this.
