### ISSUE TITLE
Linenumber info regression.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaLang/julia#12977]
For methods with keyword arguments linenumber info isn't being recorded anymore:

```
julia> f(; args...) = ()
f (generic function with 1 method)

julia> functionloc(f)
ERROR: could not determine location of method definition
 in functionloc at reflection.jl:322
 in functionloc at reflection.jl:334
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68
```

Prior to https://github.com/JuliaLang/julia/pull/12544 ``functionloc(f)`` would return ``(nothing,1)``. This applies to definitions at the REPL and in files, as well as both long- and short-style method definitions with or without positional arguments.

**Comment by Keno** [comment]
There's a number of other regressions too. I've seen `finalizer` and `convert(::Array,...)` miss line number information.

**Comment by ihnorton** [comment]
Fix inbound.
