### ISSUE TITLE
Coverage is broken

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#12971]
Since https://github.com/JuliaLang/julia/commit/a07d5ee2654e5c6b43113a5ec7f94f81da1f5d7d coverage has been down to 78%. Functions which are explicitly called in [linalg](https://codecov.io/github/JuliaLang/julia/base/linalg/arnoldi.jl?ref=4ec02cfd253668640dbfe886ad7387e4e31c5ec1), for instance, are reported as not covered. According to @IainNZ this might be affecting packages too.

**Comment by IainNZ** [comment]
@Keno this is a stretch, but is the mistake in https://github.com/JuliaLang/julia/pull/12972 in any way possibly connected to this?
