### ISSUE TITLE
Unicode char \u8 not represented...

### ISSUE THREAD

**Issue by mcprentiss** [JuliaLang/julia#12988]
! Package inputenc Error: Unicode char \u8:≈ not set up for use with LaTeX.
l.25116 The binary operator \code{≈}
                                       is equivalent to \code{isapprox} with...

Unicode char .ALMOST EQUAL TO' is not represented in LaTex.

It prevents `make latexpdf` compilation of the documentation.
This character affects math.rst and test.rst in doc/stdlib.
There have been others like this, and I think requires a hard coded hack.

**Comment by IainNZ** [comment]
Yeah you probably can't build the docs with LaTeX now, and no one has probably even tried. XeTeX or LuaTeX should work.

**Comment by jiahao** [comment]
See #8479 #9012 for what to do

**Comment by jiahao** [comment]
A PR would be very much appreciated!

**Comment by mcprentiss** [comment]
thx.
The good news is
\DeclareUnicodeCharacter{2248}{\ensuremath{\approx}}
fixes the above problem in conf.py. But...
\DeclareUnicodeCharacter{2249}{\ensuremath{\napprox}}
does not fix the same problem ?!?!.
I am working on it.

**Comment by jiahao** [comment]
`\napprox` is not define in the standard LaTeX or `amsmath` environment. You need `\not\approx` to get the negated operator.

**Comment by mcprentiss** [comment]
Well done.  I was using \napprox  and \usepackage{mathabx}.  This created an avalanche of 
latex conflicts.  

Are any of the docs tested upon new pull requests? It is troubling that `make latexpdf` had been broken and committed.

**Comment by jiahao** [comment]
No; see #7691 #7753

**Comment by mcprentiss** [comment]
got it. thx.
