### ISSUE TITLE
Avoid libuv dependency in julia.h

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#12987]
`julia.h` currently depends on `uv.h` through `support/ios.h`. It also declares a number of functions that take uv pointers as parameters. It would be good to decouple this, so we don't include uv.h by default, since it pulls in a number of system headers that may not be compatible with other libraries (e.g. it pulls in some mach headers that can confuse LLVM on OS X).

**Comment by tkelman** [comment]
ref #8880 #8690 #8754 #9221

**Comment by mbauman** [comment]
This seems to have been addressed at some point; `julia.h` no longer includes `support/ios.h` (nor any header that includes it to my eyes).

**Comment by vtjnash** [comment]
It is in libsupport.h now
