### ISSUE TITLE
Parallelize `Pkg.update`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12983]
`Pkg.update()` is often quite slow for me. I don't think my CPU is busy; this rather seem to be disk I/O and networking latencies. Thus, parallelizing this (even when running on a single core) should speed this up, in the same way a `make -j2` helps even on single-core systems.

**Comment by ihnorton** [comment]
see #11196

**Comment by jiahao** [comment]
and #11152. Almost all the overhead is in spawning `git `repeatedly.
