### ISSUE TITLE
Reflection type similar to Givens

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#12980]
Currently reflectors have no associated type and can only be left multiplied with a matrix. A reflection https://github.com/JuliaLang/julia/blob/master/base/linalg/generic.jl#L466  could naturally modeled along the lines of Givens, https://github.com/JuliaLang/julia/blob/c53f8bd90cf94fc0ab8b88c5c9554b7f75392766/base/linalg/givens.jl

**Comment by jiahao** [comment]
> Currently reflectors have no associated type

This is not strictly true; we have a small zoo of fancy `QR` types like `QRCompactWY` that LAPACK can generate which are special representations of reflectors (and collections of reflectors). But I do agree that there could be more organization of this menagerie.

**Comment by mschauer** [comment]
Ah great, then this is not urgent, but of course "nice to have".

**Comment by jiahao** [comment]
@mschauer I've thought about this issue a bit and I can't really find a good motivating use case for this proposed Reflector type that would be the new supertype of the special QR types.

1. Are there are situations in which one would want to dispatch on all reflectors?

2. Would you be willing to do the work to reorganize the existing collection of orthogonal reflector types?

If the answer to both questions is "no" then I would not leave this issue open.

**Comment by mschauer** [comment]
Reading between the lines...
