### ISSUE TITLE
0.4: calling promote_type while creating new type no longer works

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#13003]
The following line code works in 0.3 and not 0.4.  Not sure if this a regression,  or an intentional change.  (I got no responses on julia-users.)

abstract AbstractFoo{T}

immutable Foo{T,V} <: AbstractFoo{promote_type(T,V)} end

**Comment by JeffBezanson** [comment]
This did not work in 0.3; `promote_type(T,V)` returned `V`, making the code equivalent to

```
immutable Foo{T,V} <: AbstractFoo{V} end
```

so getting an error is an improvement.
