### ISSUE TITLE
Fun and games with types and functions

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#13005]
Two things surprised me today:

1) `=` as an equivalent of `typealias`?
```
julia> type A{T}
       x::T
       end

julia> B = A
A{T}

julia> b = B(5)
A{Int64}(5)

julia> typeof(b) == B{Int}
true
```

2) `typealias` as an equivalent of `=`?
```
julia> foo(x::Int) = 4
foo (generic function with 1 method)

julia> typealias bar foo
foo (generic function with 1 method)

julia> bar(6)
4
```

cc: @IainNZ

**Comment by yuyichao** [comment]
The first one should not be very surprising. Types are objects so you can assign them to any variables. You would want a `const` in order to benefit from type inference and it won't support type parameters.

**Comment by JeffBezanson** [comment]
Yes. We should probably deprecate `typealias`.

**Comment by yuyichao** [comment]
But how can we specify type parameters otherwise?

**Comment by sbromberger** [comment]
@yuyichao not sure what you mean:

```
julia> type A{T}
              x::T
              end

julia>

julia> B = A{Float64}
A{Float64}

julia> b = B(5)
A{Float64}(5.0)
```

**Comment by yuyichao** [comment]
```julia
julia> typealias NotNTuple{T,N} NTuple{N,T}
NTuple{N,T}

julia> NotNTuple{Int,10}
Tuple{Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64,Int64}
```

**Comment by JeffBezanson** [comment]
See #8974. There will have to be a more general form that can be written as an assignment, e.g. `const NotNTuple = @UnionAll T,N NTuple{N,T}`. We could keep the `typealias` syntax I guess; not a big deal.
