### ISSUE TITLE
Raise better error when IJV inputs to sparse don't agree with explicit dims

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#13008]
Right now,
```
julia> i = [1:100;]; j = [1:100;]; v = fill(5,100); m = 5; n = 5
5

julia> sparse(i,j,v,m,n)
ERROR: BoundsError: attempt to access 6-element Array{Int64,1}:
 1
 1
 1
 1
 1
 1
  at index [7]
 in sparse at sparse/csparse.jl:35
 in sparse at sparse/sparsematrix.jl:320
```

Much better would be to create
```
5x5 sparse matrix with 5 Int64 entries:
	[1, 1]  =  5
	[2, 2]  =  5
	[3, 3]  =  5
	[4, 4]  =  5
	[5, 5]  =  5
```

**Comment by jiahao** [comment]
The current design requires the user to ensure that the IJV triplets you feed to `sparse` conforms to the requested dimensions when the latter are specified. The suggested alternative silently throws away data, which doesn't seem like a good idea for a base library function.

**Comment by jiahao** [comment]
At the very least, we could throw a better error message.

**Comment by sbromberger** [comment]
Is it throwing away data if you're explicitly setting `m` and `n`? Presumably if you wanted the whole thing you'd just omit them as arguments.

**Comment by jiahao** [comment]
> Is it throwing away data if you're explicitly setting m and n?

Clearly it is a lossy construction if there are IJV triplets with i>m or j>n.

> Presumably if you wanted the whole thing you'd just omit them as arguments.

Or maybe you mistyped something.

> Also,
>> The current design requires the user to ensure that the IJV triplets fed to sparse conforms to the requested dimensions when the latter are specified.
> isn't true

What I wrote was correct. The data "conforms" to the requested in the dimensions in exactly the sense you described, namely that `maximum(I) <= m` and `maximum(J) <= n` (as opposed to requiring exact equality).

What is the use case you have in mind?

**Comment by jpfairbanks** [comment]
"padding" is probably the wrong word because a fundamental property of sparse matrices is that any entry not explicitly included is 0. So saying that an 5 by 6 sparse matrix with entries [(1,2, 17),(1,3 19), (4,5. -1)]  should have lots of zeros in it, including the entire 3rd row and 6th column.

**Comment by jpfairbanks** [comment]
I use the m,n arguments when I need to ensure that the matrix is square even if maximum(I) != maximum(J). Or if I know that in the future, I will be adding entries to those rows and column that might are might not be included in I,J,V. To me the error fast and error loud approach is better than guessing at my intentions.

**Comment by sbromberger** [comment]
> What is the use case you have in mind?

I have a graph that's represented by a sparse matrix of Bools. I want to add edges to the graph and silently fail. I create I and J from the source and destination vertices of the vector of edges, and then I create a matrix `addmx` of I, J, fill(trues,...), nv(g), nv(g) and then use `|=` to "add" the edges to the graph's sparse matrix.

The issue is that if there are edges in the vector that fall outside my vertices (that is, say, an edge from vx 1000 to vx 1001 when my graph only has 999 vertices), creation of `addmx` fails. In order to have t not fail, I need to test each value in I and J to make sure it's less than nv(g). This pretty much eliminates the performance gains I get by using sparse matrices in the first place.

**Comment by jiahao** [comment]
> The issue is that if there are edges in the vector that fall outside my vertices

I don't understand. Are you growing a graph? How can this be possible if you pick from an edge and vertex set that define a graph?

**Comment by sbromberger** [comment]
I create a 20-vertex graph:

`g = SparseGraph(20)`

I then add a lot of edges to it (say, from a file) as a vector. If any of these edges have a source vertex or a destination vertex > 20, the add_edges!(g::SparseGraph, es::Vector{Edge}) fails with an error similar to the one in the original post.

**Comment by jiahao** [comment]
Well, I would think that throwing an error in this case is the correct behavior since it is not possible to define a 20-vertex graph with an edge connecting vertices 20 and 21. If you want to include the edge you have to add a vertex, otherwise you cannot define such a graph and so it should throw an error and have your code otherwise handle it. So why is this `sparse`'s responsibility to fix?

**Comment by jpfairbanks** [comment]
Yeah you are growing the graph, so you need to increase the size for the m,n to be the maximum of all the values you have seen. This is similar to adding a 6x6 matrix to a 8x8 matrix. In this case what you want is an 8x8 result where you treat the 6x6 input as having 2 extra rows and columns of all zeros.

**Comment by sbromberger** [comment]
You asked for my use case, and I gave it. It's not sparse's responsibility to fix my use case. The request is to either correct the documentation that says sparse (I,J,K,m,n) produces an `m`x`n` matrix, when it clearly doesn't in at least one case, or to reconsider that perhaps folks who do specify `m` and `n` know what they're doing.

**Comment by jiahao** [comment]
>  sparse (I,J,K,m,n) produces an mxn matrix, when it clearly doesn't in at least one case,

Which case? The case you give that throws an error? Or the "padded" case?

**Comment by sbromberger** [comment]
The one that throws an error.

**Comment by jiahao** [comment]
> reconsider that perhaps folks who do specify m and n know what they're doing.

Deciding that users who specify inconsistent inputs "know what they're doing" is a judgement call that most constructors should not make. Signaling an error is preferable to silently throwing out data.

I'm changing this to an error reporting issue.

**Comment by sbromberger** [comment]
I appreciate the discussion, but I disagree with your characterization that having m and n less than the maximum of I and J is inconsistent when we allow m and n to be greater than the maximum of I and J. This seems a fairly arbitrary distinction to me, which is the definition of inconsistency.

**Comment by jiahao** [comment]
There is no inconsistency and it is not at all arbitrary to allow `maximum(I) < m` and `maximum(J) < n`. Since all nonstored entries are considered to be zero, so there is no conceptual error in allowing IJV triples with `maximum(I) == 5` and `maximum(J) == 5` to define a 100x100 matrix. It is however inconsistent to say that a 5x5 sparse matrix can have, say, `M[10,10] = 1`, because no such 5 x 5 sparse matrix can exist.

**Comment by sbromberger** [comment]
I understand your point even though I disagree with it. I don't view sparse() as a constructor which must have arguments that are internally rational (that is, without the "inconsistency" you describe), but rather a function that transforms three vectors (and two optional ints and a function, perhaps) into a sparse matrix. As such it might have more flexibility in what meaning it assigns to its parameters.

In any case, a better error message and, perhaps, an update to the documentation is warranted – I accept that my original proposal will remain unimplemented. Thanks again for your time and for the discussion.

**Comment by IainNZ** [comment]
Opening again so the error message gets added.

**Comment by tkelman** [comment]
Last time I checked the documentation for `sparse` was a bit inconsistent and said `max(I)` where it meant `maximum(I)` but that should be easy enough to fix.

Also, given
> In order to have it not fail, I need to test each value in I and J to make sure it's `<= nv(g)`. This pretty much eliminates the performance gains I get by using sparse matrices in the first place.

adding an error message for this particular kind of invalid input data may be more expensive than it's worth.

Pruning out-of-bounds input data should be done by the user here. It is actually pretty easy to add empty rows or columns to a sparse matrix in-place by modifying the fields of the `SparseMatrixCSC` directly: `A.m += 1` for rows, `A.n += 1; push!(A.colptr, A.colptr[end])` for columns.

**Comment by sbromberger** [comment]
> Pruning out-of-bounds input data should be done by the user here. It is actually pretty easy to add empty rows or columns to a sparse matrix in-place by modifying the fields of the SparseMatrixCSC directly: A.m += 1 for rows, A.n += 1; push!(A.colptr, A.colptr[end]) for columns.

@tkelman that only works after the sparse matrix has been created. The issue is that I can't even get a sparse matrix if `max(I) > m` or `max(J) > m`, and in any case the error message thrown is a bit wonky and the docs are ambiguous as to whether this should be allowed in the first place. 

It's a case of forcing the user to pass parameters to `sparse()` that have been arbitrarily* limited, and then not displaying a cogent error when he doesn't do so.

* after having slept on it, I'm still of the opinion that `sparse()` should do what it says and create an mxn matrix, padding or truncating the data as required.

**Comment by jiahao** [comment]
@sbromberger please need to stop saying that the limits are arbitrary. As I've said a few times, they are _not_ arbitrary and I've yet to hear a good design reason why silently truncating data is preferable to raising an error.

**Comment by tkelman** [comment]
> whether this should be allowed in the first place.

It shouldn't. Your input data is invalid.

**Comment by jpfairbanks** [comment]
I looked at the source to see about adding a more useful  message and it looks like the more useful message is in there just not being used. [csparse.jl#L57-758](https://github.com/JuliaLang/julia/blob/master/base/sparse/csparse.jl#L57)

The fact that the error occurs on Line 35 doesn't make sense because that line is `Rnz[1] = 1` which shouldn't be able to throw a BoundsError

**Comment by tkelman** [comment]
Line numbers must be off, it's happening at https://github.com/JuliaLang/julia/blob/6ef451c73e6a5ccb41f67096c8c761837cbe6528/base/sparse/csparse.jl#L39 (when you link to lines of code, hit `y` so github adds a sha and the link will remain relevant). We could maybe move that error check to within the earlier preallocation loop then.

**Comment by sbromberger** [comment]
@jiahao I'm apparently not going to be able to convince you that, as a user, if I explicitly provide dimensional parameters to a function that doesn't require them, they should be honored instead of erroring. I think the difference is that you're treating sparse as a (lower-case) constructor that requires consistency in parameters, and I'm treating it as a function that takes COO data and outputs a sparse matrix. In the latter interpretation perhaps it's more reasonable to expect a function to do what the user wants it to do, even when it truncates data (much like `getindex(a, 1:3)` truncates data because the user has explicitly asked for it - there are probably even better examples out there).

In any case, this has turned into a docs / error issue, so I'll let it go.

**Comment by jiahao** [comment]
Good.

**Comment by KristofferC** [comment]
For me, it feels like you are doing something equivalent to `A = rand(5,5); A[6,6] = 1.0` and want the latter to silently not do anything.

**Comment by tkelman** [comment]
The problem is that data truncation is not the single unambiguously obvious thing that's being asked for here with `sparse`. Rather than try to read the user's mind I'd rather just fix the mistake where the strict data validity check wasn't happening early enough in `sparse`, and more clearly document the requirements for valid input data. PR incoming that does both.

**Comment by jiahao** [comment]
Let me be explicitly clear: the only further productive conversation about this topic is 

a. *solid, logical reasons or examples* demonstrating why sparse should be a projective constructor over a lossless one, and

b. How to improve the error handling in the event possible data loss is encountered.

**Comment by sbromberger** [comment]
I concede: numpy throws an error under similar conditions.

**Comment by jpfairbanks** [comment]
Good this PR also gives an informative error if the user supplies 0 indexed data that they might have read out of a file. https://github.com/JuliaLang/julia/commit/f12b093399d0fefbef74cff02e6fd464b5f35707 two birds with one PR

**Comment by sbromberger** [comment]
While we're making changes, can we also change https://github.com/JuliaLang/julia/blob/d49e1bc32228eacbbc5ced730fce9edf10a10309/base/sparse/csparse.jl#L21-L23
so that this throws the appropriate error?

```
julia> i = Int[]; j=[1:5;]; v=[1:5;];

julia> sparse(i,j,v)
0x5 sparse matrix with 0 Int64 entries:
```

All that's required is to move these lines below the check below: https://github.com/JuliaLang/julia/blob/6ef451c73e6a5ccb41f67096c8c761837cbe6528/base/sparse/csparse.jl#L25-L27

**Comment by tkelman** [comment]
Okay, added that to #13016 in fc2064c5362156b8bdaa74e2b7483de183bca442
