### ISSUE TITLE
More regressions in line number coverage

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13012]
I'm still seeing regression in line number coverage. I've seen this in a number of instances. Below is a partial list:
- `convert(::Type{BigInt},::Int64)`
- `finalizer(::Any,::Ptr{Void})`

**Comment by Keno** [comment]
cc @ihnorton @JeffBezanson

**Comment by ihnorton** [comment]
Do you have an example?

(I've tried various `convert(BigInt,...)` invocations that throw `InexactError`s, and the line info is the same as what I get after reverting the recent commits, modulo the extra `[inlined code ...]` lines)

**Comment by ihnorton** [comment]
I guess you must mean, well, *line number coverage* rather than backtraces :smile_cat:. The line info is lowered fine for `convert` anyway... Will investigate.

**Comment by ihnorton** [comment]
Ok, I could use some more info here, or a link to coveralls. When I run the bigint test locally with `--code-coverage=all --inline=no` I get:

```
        - function convert(::Type{BigInt}, x::Union{Clong,Int32})
        1     z = BigInt()
        1     ccall((:__gmpz_set_si, :libgmp), Void, (Ptr{BigInt}, Clong), &z, x)
        1     return z
        - end
```

**Comment by Keno** [comment]
I noticed in the debugger. Coverage is a separate feature. Maybe the line number information is no longer given to LLVM?

**Comment by ihnorton** [comment]
So, on llvm-svn then? Maybe I missed something that needs duplication from a 3.3 ifdef. It would be helpful to have a slightly more complete example of how to reproduce this. Is `convert(BigInt, 0.1)` with a breakpoint in `jl_throw` sufficient?

(I haven't looked at llvm-svn lately ... lldb Makefile regressions again when I last tried updating :angry:)

**Comment by Keno** [comment]
I'm having trouble coming up with a minimal reproducing example. Will investigate myself. Sorry for the bad bug report.

**Comment by ihnorton** [comment]
I just noticed you fixed the lldb Makefile; will update my build and have a look. (thanks!)

**Comment by Keno** [comment]
Nevermind, I must have some stale state. This works fine on a fresh copy of julia.

**Comment by Keno** [comment]
Turns out the problem was using `llvm-dsymutil` which must have some sort of bug.
