### ISSUE TITLE
ISO8601 Dates missing 'Z' or '[+-]HH:MM' functionality

### ISSUE THREAD

**Issue by JonathanAnderson** [JuliaLang/julia#13020]
I was trying to parse the timestamps from `reddit.com/r/julia` to see how the arrival rates of posts has changed over time and I discovered I couldn't import the ISO8601 time format stored on each record.

For example

```
julia> Dates.DateTime("2015-08-06T22:25:31-07:00")
ERROR: ArgumentError: Non-digit character encountered
 in getslot at dates/io.jl:143
 in parse at dates/io.jl:158
 in call at dates/io.jl:202
```

It looks like it is expecting a space or an end of line after the milliseconds.

```
julia> Base.Dates.ISODateTimeFormat.slots
7-element Array{Base.Dates.Slot{T},1}:
 Base.Dates.DelimitedSlot{Base.Dates.Year}(Base.Dates.Year,'y',4,"-")
 Base.Dates.DelimitedSlot{Base.Dates.Month}(Base.Dates.Month,'m',2,"-")
 Base.Dates.DelimitedSlot{Base.Dates.Day}(Base.Dates.Day,'d',2,"T")
 Base.Dates.DelimitedSlot{Base.Dates.Hour}(Base.Dates.Hour,'H',2,":")
 Base.Dates.DelimitedSlot{Base.Dates.Minute}(Base.Dates.Minute,'M',2,":")
 Base.Dates.DelimitedSlot{Base.Dates.Second}(Base.Dates.Second,'S',2,".")
 Base.Dates.DelimitedSlot{Base.Dates.Millisecond}(Base.Dates.Millisecond,'s',1,r"(?=\s|$)")
```

I also tested how shorter strings match and noticed that they just seem to work by default

```
julia> Dates.DateTime("2015-08-06T2:1:")
2015-08-06T02:01:00
```

Perhaps another slot is needed for a `Z` or a `[+-]HH:MM`

Tested with:
```
Version 0.4.0-pre+7396 (2015-09-08 17:39 UTC)
Commit 7f73781 (0 days old master)
x86_64-linux-gnu
```

**Comment by mbauman** [comment]
`DateTime` in Base is an intentionally timezone-unaware data structure; see the second paragraph at http://docs.julialang.org/en/latest/manual/dates/.  This means that the default DateFormat doesn't include the capability to parse timezones.

Timezone functionality is added through the [TimeZones.jl](https://github.com/quinnj/TimeZones.jl/) package.  There's been lots of work recently, so I'm not sure where things stand on parsing… but if it doesn't do what you need, you can open an issue there.
