### ISSUE TITLE
Need for additional SubString conversion rules?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#13023]
Consider

``` julia
function x_killer{T<:String}(inputs::Vector{T})
  outputs = T[]
  for input in inputs
    push!(outputs, replace(input, "x", ""))
  end
  return outputs
end
```

```
julia> x_killer(ASCIIString["fox","box"])
2-element Array{ASCIIString,1}:
 "fo"
 "bo"
```

OK

```
julia> x_killer(split("fox box"," "))
2-element Array{SubString{ASCIIString},1}:
 "fo"
 "bo"
```

`replace` actually made an `ASCIIString`, but there is a conversion rule for `T<:String` to `SubString{T}`.

```
julia> x_killer(UTF8String["fox","box"])
julia> x_killer(UTF8String["fox","box"])
2-element Array{UTF8String,1}:
 "fo"
 "bo"
```

Also fine, despite `replace` making an `ASCIIString` (#13022), there is promotion rule.

```
julia> x_killer(split(utf8("fox box")," "))
ERROR: MethodError: `convert` has no method matching convert(::Type{SubString{UTF8String}}, ::ASCIIString)
```

Ouch. Is there any problem with adding a `convert{T<:AbstractString,S<:AbstractString}(::Type{SubString{T<:AbstractString}}, ::S<:AbstractString)` method?

(Real-world motivation: https://github.com/JuliaWeb/HttpCommon.jl/pull/30)

**Comment by stevengj** [comment]
I've run into this annoyance before, from accidentally trying to modify a list of substrings produced by `split` or similar.

I suppose we could add:
```jl
function convert{T<:AbstractString}(::Type{SubString{T}}, s::AbstractString)
    sT = convert(T, S)
    return SubString(sT, start(sT), endof(sT))
end
convert{T<:AbstractString}(::Type{SubString}, x::T) = convert(SubString{T}, x)
```

**Comment by mikhail-j** [comment]
@IainNZ Something I was able to do was use a comprehension to generate a usable UTF8String array such as:
```Julia
x_killer([utf8(ss) for ss in split("fox box"," "])
```

`[utf8(ss) for ss in split("fox box"," "]` applies the utf8(s) function on each element in the returned Array{SubString}, resulting in a 1 dimensional array of UTF8Strings. Maybe you can try that?

**Comment by IainNZ** [comment]
Tidying up old issues/PRs.
