### ISSUE TITLE
`replace` return types are not obvious

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#13022]
```
x = utf8("foo")
@show typeof(x)  # UTF8String
@show typeof(replace(x,"o","x"))  # ASCIIString
@show typeof(replace(x, "o", "🍕"))  # UTF8String
@show typeof(replace(x, "o", utf16("🍕")))  # UTF8String
y = "foo"
@show typeof(y)  # ASCIIString
@show typeof(replace(y,"o","x"))  # ASCIIString
@show typeof(replace(y, "o", "🍕"))  # UTF8String
@show typeof(replace(y, "o", utf16("🍕")))  # UTF8String
```

I guess in some sense its returning the most-ASCII like thing it can - so if not ASCII, its UTF8. Is it worth trying to preserve the input type if at all possible? e.g. all ASCII -> ASCII, same UTF -> same UTF, mixed with at least one UTF -> UTF8?

**Comment by johnmyleswhite** [comment]
I wonder if these things sometimes come with performance costs that outweigh the performance costs of improved indexing into ASCIIString objects.

**Comment by ScottPJones** [comment]
For replace, I think it is the type of the first argument that should be the deciding factor, when dealing with mixed types, except when the first type cannot represent all values of third argument.
@johnmyleswhite I don't think there are really any big extra performance costs here, when dealing with mixed ASCII / UTF8 strings, and it's no big deal to convert the 2nd and 3rd arguments to match the first (with the exception of ASCII, of course, in which case the 2nd and 3rd arguments could be converted to UTF8 - i.e. keeping with an 8-bit code unit, and result returned as `UTF8String`).
That means that the first example, `replace(x,"o","x")` should really return a `UTF8String`, for type stability, but the 5th and 6th examples are about as good as you can do when combining ASCIIString with UTF strings.

**Comment by nalimilan** [comment]
We could rely on `promote` for this. A `UTF8String` should be returned every time it is mixed with another type, and `ASCIIString` should only be returned when both inputs are of that type. What to do when `UTF16String`/`UTF32String` are mixed with other types is a bit less clear, but I'd be inclined to preserve them, just like is currently done for non-standard numeric types. If you passed that kind of string, you probably want to keep using it.

**Comment by ScottPJones** [comment]
I'll submit a PR later to make this type-stable (as long as the 1st argument isn't `ASCIIString` and the 3rd isn't).
There are also major performance issues with the current code, even with a `ByteString` first argument, because it always makes a copy using `IOBuffer`, even if the "from" string is not found.

**Comment by KristofferC** [comment]
These all return `String` now.
