### ISSUE TITLE
readdlm() throws exception reading empty files

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#13028]
For a space delimited text file with header but no data, `readdlm()` throws a `BoundsError`.  For example:

```julia
julia> VERSION
v"0.4.0-pre+7380"

shell> cat foo.txt
A B C

julia> readdlm("foo.txt", header=true)
ERROR: at row 1, column 3 : BoundsError(,(0,1))
 in error at ./error.jl:21
 in dlm_fill at datafmt.jl:312
 in dlm_fill at datafmt.jl:311
 in readdlm_string at datafmt.jl:269
 in readdlm_auto at datafmt.jl:46
 in readdlm at datafmt.jl:36
 in readdlm at datafmt.jl:33
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68
```

In the case that there's no data and the header is removed, `readdlm()` throws an `ArgumentError`.

For consistency, I'd expect a 0x3 array from the example above with header.  Without header, it's not quite so clear what the correct return is.  0x0?

**Comment by tkelman** [comment]
Worked in 0.3.

**Comment by JeffBezanson** [comment]
cc @tanmaykm

**Comment by tkelman** [comment]
Backport pending label is at #13164 now
