### ISSUE TITLE
Some docstrings still have poor formatting

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#13039]
Unless I'm doing something wrong, the following functions still have strange formatting when I view their docs (with ?) from the repl:

* count_ones
* count_zeros
* wait
* cholfact!
* println
* rand
* randstring
* randcycle
* exp
* sqrt

**Comment by malmaud** [comment]
More:

* sinpi
* sinc
* cospi
* cosc
* append!
* push!
* isimmutable
* map
* map!
* ifft
* fieldoffsets
* SymTridiagonal 
* lgamma
* mapreduce

**Comment by jakebolewski** [comment]
That is because these are just RST code blocks not Markdown.  Until we transition the manual this the rendering of these docstrings will look like raw RST in the Terminal.  We could write a pretty printer for RST, but I think effort is better spent to complete the transition.

**Comment by malmaud** [comment]
That's fair, but is .4 really going to be released with the docs for functions like map and push! just printing raw RST?

**Comment by jakebolewski** [comment]
Yes, unless someone wants to write a pretty printer.  Also, we use RST comments to match the signature so the pretty printer would have to be written specifically for the non-standard RST formatting we are using.

**Comment by mbauman** [comment]
What's barring their transition to Markdown?  Is it possible to work on supporting the unsupported?  We'll want to have these things anyways:

* doc-tests (could be fenced codeblocks, e.g., ```` ```jldoctest ````)
* manual cross-links (maybe `[link text](_rst_anchor)` or some other special way of designating an rst anchor)
* function and object cross-references (maybe splice in `$(link(f))`?)

Are there other unsupported syntaxes?

**Comment by jakebolewski** [comment]
See #12573 and linked issues

**Comment by jiahao** [comment]
Equations and cross-references are my two big concerns. Citations are distinct third. [Scholarly Markdown](http://scholarlymarkdown.com/Scholarly-Markdown-Guide.html)  is the closest attempt I've seen to address these in an extended Markdown format.
