### ISSUE TITLE
ERROR: `convert` has no method matching convert(::Type{VarNode}, ::Type{VarNode})

### ISSUE THREAD

**Issue by outlace** [JuliaLang/julia#13033]
I got this error
ERROR: `convert` has no method matching convert(::Type{VarNode}, ::Type{VarNode})

When I tried to assign a variable of type VarNode to the type VarNode itself. 
e.g.
some_var::VarNode
some_var = VarNode
of course I meant to assign some_var to an initialized instance of VarNode
(VarNode is just some complex type I wrote myself).  Obviously the problem is I tried to assign a variable to a type, but the error you get is not informative at all.

**Comment by kshyatt** [comment]
Anyone want to try making this error more informative?
