### ISSUE TITLE
Test error related to version bump

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/julia#13044]
On release-0.4 d523dde, I'm getting this test failure:

```
LoadError("/Users/rrock/Documents/Code/julia/test/cmdlineargs.jl",3,ErrorException("test failed: \"0.4.0-rc1\" == \"0.4.0-dev\"\n in expression: Base.VERSION_STRING == chomp(v)"))
```

Sure enough, `julia -v` returns `julia version 0.4.0-dev`, while `Base.VERSION_STRING` is "0.4.0-rc1"

It looks like a make target somewhere should depend upon `src/julia_version.h` (which contains the correct "rc1" string), but I couldn't figure out which one.

**Comment by JeffBezanson** [comment]
Dup of #13035?

**Comment by jiahao** [comment]
Yes, dupe.

**Comment by mbauman** [comment]
There is a Makefile rule for this, but I suppose it doesn't get run unless something else in the src directory is dirty?

**Comment by tkelman** [comment]
Is it really doing us a lot of good having `ui` separate from `src`? Should we combine the two?

**Comment by JeffBezanson** [comment]
I feel it's important, since src contains everything that's part of libjulia, while ui adds a `main` wrapper.
