### ISSUE TITLE
Add a Makefile option to disable FFTW tests

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13040]
They take too long and never fail.

**Comment by tkelman** [comment]
They're far from the slowest set of tests. You can do `--skip fft` https://github.com/JuliaLang/julia/blob/7cd05db5e4188b905e976de5283db9d05159f014/test/choosetests.jl#L53

**Comment by yuyichao** [comment]
I think what @Keno means is to disable the FFTW test suite at compile time.

**Comment by tkelman** [comment]
Oh right, in deps. Just `touch deps/fftw-3.3.4-double/checked && touch deps/fftw-3.3.4-single/checked`

**Comment by ViralBShah** [comment]
I would love this to be the default.

**Comment by ViralBShah** [comment]
FWIW, they did fail on ARM. But they never do on Intel. In any case, this is the kind of thing that 99% of the people building Julia are unlikely to worry about.

https://github.com/FFTW/fftw3/issues/30

**Comment by Keno** [comment]
`touch` works fine, but only after fftw is already unpacked. There isn't really a good way to do this when building from scratch.

**Comment by KristofferC** [comment]
+1 for making this default. They take a disproportionate long time IMHO.

**Comment by tkelman** [comment]
We should maybe do this in a uniform way across all deps to enable/disable all the `check-*` targets

**Comment by ViralBShah** [comment]
+1 to disbaling them all by default.

**Comment by StefanKarpinski** [comment]
Bump. These tests kill my poor laptop.

**Comment by KristofferC** [comment]
Bump. Sitting through a looong session of FFTW tests for the nth time.

**Comment by ViralBShah** [comment]
I am submitting a PR soon. I am getting a bit tired of deps tests.
