### ISSUE TITLE
Converting the standard library to 100% Markdown

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#13047]
There are currently ~~332~~ ~~282~~ ~~223~~ ~~218~~ 200 docstrings that haven't made the conversion to Markdown.  While they still display nicely in the online manual, they are simply output as plaintext with RST markup at the terminal.  Since the end goal is to have the entire manual as markdown (#12573), we will need to figure out ways of spelling the features we want in Markdown sooner or later.  Here are the syntaxes that are currently used, roughly sorted by frequency of use:

* [ ] Function references (``:func:`foo` `` and sometimes ``:ref:`~ operator <~>` `` or ``:func:`f(x+y) <f>` ``)
* [ ] Object references (`` :obj:`Bar` `` and sometimes `` :class:`Quux` `` or ``:const:`BAZ` ``)
* [ ] Error references (`` :exc:`ErrorException` ``)
* [ ] Links to sections in the manual (``:ref:`Link name <man-link-anchor>` `` or auto-populated with anchor title by ``:ref:`man-link-anchor` ``)
* [x] Doctests (~~#13045~~)
* [x] Inline latex ``:math:`\latex` `` (~~#13058~~) — Just need to teach Markdown how to export ``inline $x^2$`` to RST (72 uses, very few blocked by other syntaxes).
* [x] Superscripts ``:sup:`T` `` (~~#13108~~) — could use unicode since its use is limited to `Aᵀ` and `Bᴴ` (18 uses, none blocked by other syntaxes).
* [x] Bullet lists (~~#13046~~)
* [x] `**Example**`s (~~#13102~~)
* [ ] Notes (`.. note::`) (example: [gcdx](http://docs.julialang.org/en/release-0.3/stdlib/math/#Base.gcdx))
* [ ] Citations, sometimes with inline references to things cited elsewhere (`logm`, `pinv`, `sqrtm`, `expm`, `bkfact`, `qrfact`, `full`)
* [ ] Tables ~~(MultiMarkdown has a possible solution)~~ Markdown just needs to be taught how to export them to RST.
* [ ] Literal inline code blocks (`` :literal:`has\` in it` ``)?

We probably don't really need to preserve all of Python's different ways of referencing functions/objects/classes/constants/exceptions/etc.  But that is far and away the biggest reason why most RST blocks haven't been converted.  If we can figure out a way to do references, we'll be 90% of the way there.

Note that if one method's docstring failed to auto-convert to markdown, none of the functions methods were converted to markdown.  So when addressing one of the items above, search to see if addressing the docstring of one method frees all the other methods, too.

**Comment by jakebolewski** [comment]
This is a great list.  The complexity of implementing any solution wrt to crosslinking will be dramatically reduced if the rest of the manual is converted to Markdown.  Most of the reasons why so many features are used in that they link back into the manual and vice versa.

**Comment by mbauman** [comment]
Yeah, but I think that, regardless of the manual solution, we'll want some shorthand way to specify manual anchors that aren't necessarily on the same page.

Perhaps we could just use regular anchor syntax, and then the RST/mythical-new-manual output will reinterpret them as manual/stdlib cross references?  E.g., `[foo](#foo)` or `[bar()](#bar)` or `[the baz operator](#baz)` or `[random numbers section](#man-random-numbers)`.

**Comment by mbauman** [comment]
Perhaps the solution for function references is to use `$(link(foo))`.  For now, it could just splice in `[foo()](#foo)`, which would become ``:ref:`foo() <foo>` ``, but it would allow us to use multiple dispatch to format functions/objects/types/etc differently in the future without mucking with the docs again.

**Comment by hayd** [comment]
- inline latex should just work, it just needs to be rendered to rst. (This is another case where refactor would help (to make it clearer what methods are missing). #11421 #12740.)

- @MichaelHatherly and I were hashing out in Docile a possible syntax for notes and citations etc...

- What's wrong with using the current (github) table syntax? Is it just we need the julia markdown -> rst?

- Note for literals you can use the [`` syntax](http://spec.commonmark.org/0.12/#code-span):

```jl
julia> Markdown.parse("``has` in it``")
  has` in it
```

- For references could a syntax like:

        """text with $(Ref("`f(x+y)`", f))"""

(Perhaps would need a trick to work with `doc"""..."""`.) I'm *sure* @one-more-minute had a solution for this in the past...

**Comment by mbauman** [comment]
> inline latex should just work, it just needs to be rendered to rst.

Yup, I got that working last night and should have a PR for those guys this evening.

> What's wrong with using the current (github) table syntax

I wasn't aware it was supported.  If it is: awesome! :cake:  There's only about four or five tables, so it's not high on the priority list right now.

> Note for literals you can use the `` syntax

Yeah, there's literally one use of the `:literal:` directive.  The question mark was more for its purpose in RST.  It's an easy fix.

> references

Splicing always inserts a string, even into string macros, no?  So we'll have to figure out what the Markdown surface syntax is first.

**Comment by hayd** [comment]
The `ref` I was thinking of is [in the markdown tests](https://github.com/JuliaLang/julia/blob/360c537a96fe3888aab099ccb2c5e520b4d1fd67/test/markdown.jl#L210-L229). I don't see any reason we'd need the type func/obj/class/const, that can be grokked from the type. This would also solve ALL the links as we'd do:

    :ref:`Link name <man-link-anchor>`
    [Link name]($(url(ref(f)))  # or something similar but nicer

Is there a method to get the docs url from the type/func/const etc. ?

**Comment by dancinglightning** [comment]
Hi
I'm spending my time reading at the moment, so if there is some clear cut work on these lines, i could help.
Torsten

**Comment by MichaelHatherly** [comment]
Just an update on this: I'm currently translating the rest of the rst docstrings to markdown, tidying up and reformatting others, adding @StefanKarpinski's suggestion (https://github.com/JuliaLang/julia/pull/14310#issuecomment-162967681) for inline LaTeX using double backticks, and removing all usage of `@doc_str` from `Base`. I'll probably have something worth submitting either tomorrow or Saturday.

(The diff is currently quite large, ~13000 lines, but spread over quite a few small commits to hopefully make reviewing easier.)

**Comment by hayd** [comment]
+1. Do you have a plan for refs etc.?

**Comment by StefanKarpinski** [comment]
Please see https://github.com/JuliaLang/julia/pull/13308 for my work on converting RST to a variation of Markdown that I had to cobble together from conventions in GitHub Markdown, Scholarly Markdown and Pandoc Markdown. Definitely not final and I still need to modify our Markdown parser to understand the conventions and be able to render them to usable HTML. Could certainly use help. I was planning on posting a summary of what I'd decided on for conventions for things to get discussion going.

**Comment by MichaelHatherly** [comment]
> +1. Do you have a plan for refs etc.?

For `:func:`, `:ref:`, `:obj:` I'm just translating

    :func:`foobar` to [`foobar`](:func:`foobar`)

and special casing the rst rendering for any url that matches `:func:`, etc. If people like @mbauman's suggestion in https://github.com/JuliaLang/julia/issues/13047#issuecomment-139237709 then I can change it to that and just output `:ref:` rather than the assortment of different ones we have now. @StefanKarpinski, do you have a particular syntax in that branch for refs? I couldn't find anything.

**Comment by StefanKarpinski** [comment]
My plan for refs was to leverage the fact that we're Julia code referring to objects in the current scope of the doc string. Unlike most documentation systems, we know what `foobar` is and we can know that it's a function and where it's defined. Therefore, we can automatically provide a cross reference to it. That way people don't have to mark up most references at all.

**Comment by MichaelHatherly** [comment]
Closed by https://github.com/JuliaLang/julia/pull/14378? There may be some further discussion needed for what our final ref syntax will be and perhaps some better formatting conventions in places, particularly `.. note::` sections, but for the most part this issue is resolved.
