### ISSUE TITLE
Deprecated methods / types being used on the v0.4-rc branch

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13052]
Filing this to make sure they are removed before the release.

**Comment by jakebolewski** [comment]
Actually, if you remove the deprecated methods (not types) from v0.4, the tests no longer pass.

**Comment by ssfrr** [comment]
Does the use of `require` by `reload` count for this?

```
julia> using FactCheck

julia> reload("FactCheck")
WARNING: `require` is deprecated, use `using` or `import` instead
 in depwarn at ./deprecated.jl:73
 in require at deprecated.jl:663
while loading no file, in expression starting on line 0
WARNING: replacing module FactCheck

julia> 
```

**Comment by JeffBezanson** [comment]
Oh dear. It looks like the intent might have been to deprecate `reload` as well, but I wasn't aware of that. @vtjnash is that the case, or should we just remove the warning if `reload` is called?

**Comment by JeffBezanson** [comment]
I also have a feeling some users will want to see an IncludeOnce.jl package providing a drop-in replacement for the old `require`.

**Comment by ivarne** [comment]
Would it be reasonable to add a conditional on [`include("deprecated.jl")`](https://github.com/JuliaLang/julia/blob/2ef6c3dbb357b1372e4333a59877af5f69053651/base/sysimg.jl#L295) to enable travis to not include the deprecations in the system image when running tests?

**Comment by vtjnash** [comment]
> Oh dear. It looks like the intent might have been to deprecate reload as well, but I wasn't aware of that. @vtjnash is that the case, or should we just remove the warning if reload is called?

no, this wasn't really the intention. however, it was intended to deprecate passing a filepath (as the example above shows), and only allow passing a module name (as a symbol). the warning above could be more exact here however.
