### ISSUE TITLE
Vector{String} .* String

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#13053]
if one can multiply a vector of numbers by a scalar number:

```
julia> [1,2].*3
2-element Array{Int64,1}:
 3
 6
```

shouldn't one also be able to do so for strings?

```
julia> ["1","2"].*"bar"
ERROR: `.*` has no method matching .*(::Array{ASCIIString,1}, ::ASCIIString)
```

the work around is to make the scalar a vector, and that's easy, but i don't see why it's necessary.

```
julia> ["1","2"].*["bar"]
2-element Array{ASCIIString,1}:
 "1bar"
 "2bar"
```

**Comment by jakebolewski** [comment]
Why not `map(join, xs)`?

This looks to be an oversight, but `*` string concatenation is generally frowned upon.

**Comment by ScottPJones** [comment]
Yep, some of us would love to see `*` for string concatenation disappear totally :grinning:
I do like @jakebolewski's `map(join, xs)` solution.
