### ISSUE TITLE
wait(condition) while running an @async task can not be interrupted by ctrl-c

### ISSUE THREAD

**Issue by tehrengruber** [JuliaLang/julia#13075]
Consider the following 2 scenarios

Scenario 1
```julia
cond = Condition()
wait(cond)

# press ctrl-c
#^CERROR: InterruptException:
```

Scenario 2
```julia
cond = Condition()

@async begin
	while true
		sleep(1)
		println(1)
	end
end

wait(cond)

# press ctrl-c
#^CERROR (unhandled task failure): InterruptException:
#^CERROR (unhandled task failure): InterruptException:
# ...
```

Now in scenario 1 pressing ctrl-c just interrupts the wait call und you get back to the prompt and everthings fine

But in scenario 2 pressing ctrl-c actually interrupts the task and not the wait call. Which is not correct I guess and even worse after the task was interrupted you are stuck and you won't  get back to the prompt.

**Comment by JeffBezanson** [comment]
I believe I fixed this in #10416, and it regressed.

**Comment by tkelman** [comment]
any reasonable way of testing for this?

**Comment by tkelman** [comment]
backported in #13107
