### ISSUE TITLE
bit shift operator precedence

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13079]
Scrutinizing the operator precedence table, it struck me as a bit odd that bit shift operators have their own precedence level, strictly _lower_ than multiplication. `a*b>>c*d` is an ugly expression to be sure, but it's parsed as `(a*b)>>(c*d)`, which doesn't make a whole lot of sense.

Since `a<<b` means `a*2^b`, `<<` should perhaps have the same precedence as `*`, or maybe even the same precedence as `^`. Or maybe it should be moved to one notch higher than `*`, instead of one notch lower (putting it between `*` and `//`).

**Comment by sbromberger** [comment]
Reference table here: https://en.wikipedia.org/wiki/Order_of_operations#Special_cases

Bitwise shift left and right is level 5, above + / -.

See also http://www.knosof.co.uk/cbook/accu06a.pdf

**Comment by JeffBezanson** [comment]
Giving `<<` lower precedence than `+` is widely regarded as a mistake.

The linked study looks interesting but I didn't manage to extract a concrete recommendation at a glance. Do you have a strong take-away from it?

**Comment by sbromberger** [comment]
> Do you have a strong take-away from it?

None at all. I knew Ritchie never liked the precedence of bitwise operators in C; I wasn't suggesting that we emulate them. I was just providing a couple of reference points for the decision :)

**Comment by StefanKarpinski** [comment]
I wonder if we could do better with precedence in general by borrowing the idea from Fortress of making precedence a partial ordering and having it be an error not to parenthesize ambiguous cases.

**Comment by jakebolewski** [comment]
Wouldn't you still have to define a relative ordering of operators?  I don't see how that proposal is that much better than having fixed rules with a couple ambiguous cases in terms of precedence level.

**Comment by Mike43110** [comment]
I do feel while erroring or at least warning on potentially ambiguous statements would be nice. It seems though like something a linter could deal with instead.

**Comment by JeffreySarnoff** [comment]
I prefer bit ops binding more tightly than arith ops, and, subordinately, unary ops binding more tightly than binary ops.

**Comment by JeffreySarnoff** [comment]
Clarification:

       unary ops  before binary ops of the same nature
       bitwise logical ops { &, |, $, ↑  }  before arith ops { +, -, *, /, \, %, ^}
       arith ops before wordwise ops { >>, <<. >>>, ror, rol }
       wordwise ops before  comparatives { < .. == .. > } 
       comparatives before truth functional connectives { &&, ||, $$, ↑↑ }

**Comment by JeffBezanson** [comment]
Proposal: move bit shifts one notch higher than `//`, so `x//1<<n` is parsed as `x//(1<<n)`. Triage feels it's better for shifts to be either strictly higher or strictly lower than arithmetic operators, instead of in the middle. It also seems weird to shift the result of a division; more useful to divide the result of a shift.

It's also possible shifts should be merged into the `^` level, since it behaves similarly.

**Comment by JeffBezanson** [comment]
One issue: `^` is parsed right to left, but `<<` is parsed left to right. So we can also decide whether we want to change that.

**Comment by JeffreySarnoff** [comment]
I concur:  arith < shift < power

There does not appear any explicit advantage to 
arith < shift, power.  And while thier purposes intersect, the do mot coincide: Shifting does mach powers of 2  ... power does not help with bit field masking.

**Comment by JeffBezanson** [comment]
Done.

**Comment by PallHaraldsson** [comment]
This seems important to document (and not just in NEWS).

I'm not sure if Compat can handle this or is wanted there.

**Comment by JeffBezanson** [comment]
The precedence has not actually been changed yet; I just required parentheses. Adding parens is easier than typing `@compat`.

**Comment by saolof** [comment]
This is a pretty big change.

While I can see that this actually does work substantially better for most arithmetic expressions where you want to use bitshifts, it is a different convention from what every other language uses. It may especially surprise a lot of people coming from C++ where the bitshift operator is a notoriously common target for overloading because of its convenient place in the precedence table and the fact that the >> notation suggests chaining.

Julia Libraries that overloaded >> to denote monadic bind or some other operation will be shafted by this change if it goes live.

**Comment by StefanKarpinski** [comment]
The point about principle of least surprise is valid, however – it's concerning to have different precedence from other mainstream languages, evn if that precedence is a bit unfortunate.

**Comment by JeffreySarnoff** [comment]
afaik the principle of least surprise was developed to encourage cognitive consonance rather than conform to alternative practice (translation: we have the opportunity to do it better, and we should -- it takes little effort to learn this specific distinction, and overcoming Julia promulgating a worse practice takes enormous effort)
