### ISSUE TITLE
Socket test failure (EADDRNOTAVAIL) with release-0.4

### ISSUE THREAD

**Issue by rjagerman** [JuliaLang/julia#13076]
I have successfully build (using `make`) the `release-0.4` branch on Red Hat Enterprise Linux 7. I can run Julia, but it seems to fail on a test related to sockets:

```
julia> Base.runtests("socket")
     * socket               ERROR: LoadError: LoadError("/local/julia/usr/share/julia/test/socket.jl",176,bind: address not available (EADDRNOTAVAIL))
 in bind at socket.jl:447
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 [inlined code] from util.jl:179
 in runtests at /local/julia/usr/share/julia/test/testdefs.jl:6
 in anonymous at multi.jl:684
 in run_work_thunk at multi.jl:645
 in remotecall_fetch at multi.jl:718
 in remotecall_fetch at multi.jl:734
 [inlined code] from multi.jl:1430
 in anonymous at task.jl:448
while loading /local/julia/usr/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.4.0-rc1+7
Commit 39e2493 (2015-09-10 20:01 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at ./error.jl:21
 in runtests at interactiveutil.jl:408
 in runtests at interactiveutil.jl:397
```

I get the same error message at the socket test when attempting to run `make test`. Running it on the `release-0.3` branch however works fine.

**Comment by nalimilan** [comment]
As a data point, the tests work fine when building the RPM packages on RHEL7.

Anything unusual with your network configuration or user privileges?

**Comment by rjagerman** [comment]
I ran as root to check if it has to do with user privileges, but it runs into the same problem. It might indeed be a network configuration issue since it's a university computer. Any idea what I should check?

**Comment by rjagerman** [comment]
The problem has to do with IPv6 connectivity. The machine I am on does not have IPv6 enabled:

    $ ping6 ::1
    connect: Network is unreachable

The test that fails is one related to binding a socket to an IPv6 localhost. All other tests run fine. This looks more like a configuration issue on my end, so I think it's safe to close this issue.

**Comment by ihnorton** [comment]
see https://github.com/JuliaLang/julia/issues/9892 ... Reminding me to rebase my PR and try to get someone to review it.

**Comment by dgleich** [comment]
I just wanted to mention that I ran into this same issue with Julia 0.5 tonight. The default check for ipv6 only excludes windows versions before Vista, but it might be useful to have a functional test for linux users too.
