### ISSUE TITLE
Void() does not work

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13083]
`Void()` returns an error:
```Julia
Void()
LoadError: MethodError: `convert` has no method matching convert(::Type{Void})
```

This is
```
Julia Version 0.4.0-rc1+7
```

**Comment by yuyichao** [comment]
Isn't it supposed to be fixed by #12962 ?

**Comment by yuyichao** [comment]
I see, so #12962 addes the method to `Core.call` instead of `Base.call`

```
julia> Core.call(Void)

julia> Base.call(Void)
ERROR: MethodError: `convert` has no method matching convert(::Type{Void})
This may have arisen from a call to the constructor Void(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, ::T)
  call{T}(::Type{T}, ::Any)
 in call at ./essentials.jl:57
```

**Comment by eschnett** [comment]
I found this when I tried to add a test case... should have done that earlier.

Do you know how to fix this?

**Comment by yuyichao** [comment]
Unless you want to use that **VERY** early in bootstrap or in inference, adding it in `essential.jl` or anything sourced by `sysimg.jl` that seems fit should work.

**Comment by tkelman** [comment]
backported in #13107
