### ISSUE TITLE
Current working directory on remote machines

### ISSUE THREAD

**Issue by fedorn** [JuliaLang/julia#13085]
Hello. Is it possible for julia that run on machines from machinefile to have same working directory as on current machine?

``` bash
~ $ julia -p 4 --machinefile ~/machinefile-stable
```

``` julia
julia> pwd()
"/wsu/home/ft/ft33/ft3354"

julia> remotecall_fetch(2, pwd)
"/wsu/home/ft/ft33/ft3354"

julia> remotecall_fetch(3, pwd)
"/wsu/home/ft/ft33/ft3354"

julia> remotecall_fetch(8, pwd)
"/wsu/home/ft/ft33/ft3354/src/julia-483dbf5279/bin"
```

As you see here on remote worker pwd return different result and I am forced to cd to correct directory to fix it.

**Comment by vtjnash** [comment]
on master it should be setting the cwd on all machines (https://github.com/JuliaLang/julia/blob/324a21c4baf404beb409475dc29190de44aa9821/base/managers.jl#L104) to the result of `pwd()` on the local machine (https://github.com/JuliaLang/julia/blob/324a21c4baf404beb409475dc29190de44aa9821/base/multi.jl#L1142).

As of your commit (483dbf5279, aka v0.3.11), however, this had not been fixed.
