### ISSUE TITLE
Weak type inference in a special case

### ISSUE THREAD

**Issue by cdsousa** [JuliaLang/julia#13082]
Sorry for the not so good title. I'm not sure about the right words to describe this issue.
Hence I'll put it as an auto-explainable (I hope) example. I found this issue due to https://github.com/timholy/Images.jl/issues/356.

Let's begin with the following definitions
```julia
type A{N}; end
type B{N}; end

getN{N}(::A{N}) = N

f(a) = B{getN(a)}()
```

In case we call `f` with a variable whose type has a Datatype as parameter,
```julia
@code_warntype f(A{Int}())
```
```
Variables:
  a::A{Int64}

Body:
  begin  # In[2], line 3:
      return $(Expr(:new, B{Int64}))
  end::B{Int64}
```
the final type is correctly inferred.

However, I we call `f` with a variable whose type has an integer value as parameter,
```julia
@code_warntype f(A{123}())
```
```
Variables:
  a::A{123}

Body:
  begin  # In[2], line 3:
      return call((top(apply_type))(Main.B,123)::TYPE{_<:B{N}})::B{N}
  end::B{N}
```
the return type cannot be correctly inferred (`end::B{N}`).
Can this be considered a bug, or is there any technical difficulty with this?

Moreover, something stranger occurs. If we wrap the integer value within a parametric type, e.g. a `Tuple`, the inference works:
```julia
@code_warntype f(A{Tuple{123}}())
```
```
Variables:
  a::A{Tuple{123}}

Body:
  begin  # In[2], line 3:
      return $(Expr(:new, B{Tuple{123}}))
  end::B{Tuple{123}}
```

**Comment by johnmyleswhite** [comment]
What is `a` in your first codeblock?

**Comment by yuyichao** [comment]
I think this is just because julia is not doing any local constant propagation except for types right now. Dup of https://github.com/JuliaLang/julia/issues/11159 and covered by https://github.com/JuliaLang/julia/issues/3440

**Comment by cdsousa** [comment]
Thanks @yuyichao.
(@johnmyleswhite, `a` was meant as a variable of type `A`.)

**Comment by cdsousa** [comment]
So this resumes to
```Julia
t() = Val{123}
n() = 456
f_t() = Val{t()}
f_n() = Val{n()}
@code_warntype f_t()  # --->   end::Type{Val{Val{123}}}  type inferred
@code_warntype f_n()  # --->   end::TYPE{_<:VAL{T}}      type not inferred
```

@yuyichao, are you sure this is the same issue of #11159? If so, which line of #3440 covers it?

**Comment by yuyichao** [comment]
> are you sure this is the same issue of #11159?

Yes. At least almost.

> If so, which line of #3440 covers it?

See Jameson's comment https://github.com/JuliaLang/julia/issues/11159#issuecomment-99626529 .
