### ISSUE TITLE
cor, cov: remove mean keyword arg

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#13081]
https://groups.google.com/forum/#!topic/julia-users/KHfhB-VOVdU

**Comment by johnmyleswhite** [comment]
Sounds like a good idea

**Comment by simonster** [comment]
Or we could just fix the type instability...

**Comment by nalimilan** [comment]
I'm not against removing these arguments, but we need this pattern of special default values to work in many cases. There have been discussions about using `Nullable`, and automatically converting keyword arguments to their expected type (https://github.com/JuliaLang/julia/issues/7357#issuecomment-93830828, https://github.com/JuliaLang/julia/issues/10561#issuecomment-84213401).

**Comment by mdcfrancis** [comment]
Thanks
