### ISSUE TITLE
Extra newlines on JuliaLang downloads

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#13091]
There seem to be newlines after and before the parenthesis in front of the GPG links:

Here is one example:

![image](https://cloud.githubusercontent.com/assets/1282691/9832633/a88731fa-5981-11e5-8687-93436c6e42a7.png)

There is another one further down. It should probably be changed so it is all on one line which would make the table take a lot less space.

**Comment by tkelman** [comment]
Wrong repo. If you have any suggestions, see https://github.com/JuliaLang/julialang.github.com/pull/264 and a PR would be great.

**Comment by KristofferC** [comment]
Didn't know about that repo. I would love to do a PR but I know absolutely nothing about web coding...

**Comment by nalimilan** [comment]
Those are just Markdown files, they are easy to modify.

**Comment by KristofferC** [comment]
Ok, I will try.

**Comment by tkelman** [comment]
Though there are some annoying differences in how github renders the markdown vs the generated html...

**Comment by KristofferC** [comment]
The markdown files look fine on: https://stackedit.io/editor
