### ISSUE TITLE
Broken backtrace test on OS X + LLVM 3.6.2 with release-0.4 branch

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13103]
I am trying to use LLVM 3.6.2 with the release-0.4 branch on OS X. This builds fine, but fails the self tests:
```
$ ./usr/bin/julia --check-bounds=yes --startup-file=no ./test/runtests.jl backtrace
     * backtrace            ERROR: LoadError: LoadError("/Users/eschnett/src/julia-36/test/backtrace.jl",40,ErrorException("test failed: endswith(string(inlinedfile),\"backtrace.jl\")\n in expression: endswith(string(inlinedfile),\"backtrace.jl\")"))
```

 This works fine with LLVM 3.3.

**Comment by ihnorton** [comment]
Would you mind to print `inlinedfile` variable in that test? I don't have an OS X system to debug this.
Works fine on Linux with LLVM 3.6.1.

**Comment by tkelman** [comment]
Ref #7910 #11515, i think this is expected pre 3.7

**Comment by Keno** [comment]
correct
