### ISSUE TITLE
Error while using threading branch

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#13101]
I built the new threading branch (jn/threading) on my laptop. Once I compiled it, and fired up Julia, I tried this. 

```
export JULIA_ENABLE_THREADING=1
./julia
using Base.Threading
@threads all for i = 1:100
10*10
end
```
I got the following error
```
ERROR: ccall: could not find function jl_threading_run
 in anonymous at ./threading.jl:70
```

**Comment by vtjnash** [comment]
you need to build julia with the `JULIA_ENABLE_THREADING` flag, it is not a runtime option

**Comment by ranjanan** [comment]
Oh alright. Will a ```make cleanall``` and ```make``` fix that? Also, can I change ```$JULIA_NUM_THREADS``` and control the number of threads, as before?

**Comment by vtjnash** [comment]
It's probably easiest to modify `src/julia.h` to add `#define JULIA_ENABLE_THREADING`

yes, you can control the number of threads at runtime
