### ISSUE TITLE
Documentation for A_ldiv_B!

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#13110]
Documentation for `A_ldiv_B!` and company is missing. 
Is it correct that it does in-place replacement of `A` by `A / B` ?  If so, I'll add docs for these functions.

**Comment by KristofferC** [comment]
Not always. See #10787.

**Comment by dpsanders** [comment]
OK, thanks. What do you suggest? See also https://github.com/JuliaLang/julia/issues/11325

**Comment by jakebolewski** [comment]
I feel an incomplete stub is better than no documentation at all.  All of this can be incrementally improved over time.

**Comment by kshyatt** [comment]
Since #10787 was resolved, can someone add docs for this now?

**Comment by stevengj** [comment]
Done in #16702
