### ISSUE TITLE
deepcopy duplicates arrays

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#13124]
```
a=rand(3,5)
b=(a,a)
b[1]===b[2] => true
c=deepcopy(b)
c[1]===c[2] => false
```
To fix this issue, on line 59 of deepcopy.jl we can replace:
```
        return copy(x)
```
with
```
        return (stackdict[x]=copy(x))
```

**Comment by StefanKarpinski** [comment]
This does seem to be a consistent change with the premise that deepcopy should be equivalent to serialize and deserialize.

**Comment by JeffBezanson** [comment]
Agreed, though currently the serializer does not accurately record shared references to bits arrays. I found it impossible to get acceptable performance with strings when doing that.

**Comment by StefanKarpinski** [comment]
Could we special case strings since they're mutable in implementation but immutable in usage?

**Comment by timholy** [comment]
I use `deepcopy` in Images precisely because it copies arrays: https://github.com/timholy/Images.jl/issues/356#issuecomment-143480113. I guess I've always thought that `deepcopy`'s purpose is to give me a totally-independent version of something, so that if I mutate it the original will be unchanged.

Should `Dict`s instead make copies of all their keys and values? Or should I write a custom copy function?

**Comment by StefanKarpinski** [comment]
Would your use-case really be messed up by not copying strings? That seems pretty benign to me since one shouldn't mutate the storage of strings.

**Comment by timholy** [comment]
It's more the "value" than the "key" I'm worried about. E.g., `"pixelspacing" => [2mm, 2mm]` you don't want to change the original if you set `img["pixelspacing"][2] = 3mm`.

**Comment by denizyuret** [comment]
I am a bit confused: I was not proposing any sharing between the original
and its deepcopy.  It is just that if two things are shared in the source,
they should be independently created but in a shared way in the deepcopy.
For example if a=rand(3,4) and b=(a,a), when we do c=deepcopy(b), there is
no sharing between b and c, just between c[1] and c[2].

best,
deniz

**Comment by timholy** [comment]
I didn't read the test case carefully enough. Yes, that's a problem. Carry on :smile:.
