### ISSUE TITLE
`require()` deprecated in 0.4, but still in documentation. 

### ISSUE THREAD

**Issue by davidavdav** [JuliaLang/julia#13120]
In fact, with the deprecation of `require()` in 0.4, it is not clear to me how you should load a module `MyModule` in a directory `./src/`.  I have a `LOAD_PATH` being `["src", "test", ...]` but my modules in `./src/` are not loaded, instead I get installed modules in `~/.julia/v0.4/`.  (In my workflow, I develop in a separate set of directories, and when I am happy for usage outside the package development area itself, I push to github and then install from github into `~/.julia/`. This may not be the recommended workflow---perhaps the recommended workflow should be included in the documentation---the one under "Workflow tips" seems not to cover a lot).  

I looks like the way to go is:
```julia
include("src/MyModule.jl")
using MyModule
```
this is the only way I can load the stuff in `./src/`, but I see no way or reloading---I keep getting complaints about deprecated requires.

**Comment by yuyichao** [comment]
`require` is not deprecated `require(::AbstractString)` is. The one in the document is `require(::Symbol)` which is not deprecated.

`reload` should have been fixed by https://github.com/JuliaLang/julia/commit/d3bc374d58182aee9763dde168bb1d9ee264e07d .

**Comment by davidavdav** [comment]
In trying to understand the search path, the docs say:

### Relative and absolute module paths

Given the statement `using Foo`, the system looks for `Foo` within `Main`. If the module does not exist, the system attempts to `require("Foo")`, which typically results in loading code from an installed package.

This doesn't really help me much in my workflow---I want to be able to specifically load the module in `./src/`.  The work-around in my previous post (still) works, but I am not sure this is meant to work at all.
