### ISSUE TITLE
`norm` kwarg appears in description of `isapprox`, but not in the signature

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#13132]
Not sure if this is a bug or feature

Attn @stevengj, who `git blame` shows was in the vicinity

**Comment by stevengj** [comment]
I think this was because the `norm` keyword is not supported for scalar args.

**Comment by kshyatt** [comment]
This is still true. Might be nice to incorporate an example into the docstring?

**Comment by tkelman** [comment]
cc @ararslan who was adjusting this recently

**Comment by IainNZ** [comment]
I think still true - up for grabs perhaps?

**Comment by findmyway** [comment]
Just come across this issue. I think this is not true now.

**Comment by stevengj** [comment]
`isapprox` still does not have a `norm` keyword for scalar arguments.

(`abs` or multiples thereof is the only sensible norm for scalars, but I suppose it wouldn't hurt to add a `norm` keyword anyway just for consistency.)

**Comment by sloede** [comment]
I supplied a possible fix for this issue in #35883. Please let me know if there's something that should be changed/improved.
