### ISSUE TITLE
List all possible values when printing an enum

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#13138]
At the moment, when you type the name of an enum at the REPL, you get a useless output:
```julia
julia> @enum FRUIT apple=1 orange=2 kiwi=3

julia> FRUIT
FRUIT
```

Wouldn't it be more useful to show the list of possible values from `instances()`? Something like this:
```julia
julia> FRUIT
Enum with 3 member values:
apple, orange, kiwi
```

(This would especially help since `instances` is hard to find: `methodswith(FRUIT)` does not list it.)

CC: @quinnj

**Comment by KristofferC** [comment]
Pardon my ignorance but `FRUIT` is just a `DataType` so how can you dispatch to print something separate for `FRUIT` that would not apply to all DataTypes?

**Comment by yuyichao** [comment]
`show(io::IO, ::Type{FRUIT}) = ...`

**Comment by KristofferC** [comment]
Ah, well then... :blush:

**Comment by ScottPJones** [comment]
:+1: to this idea
