### ISSUE TITLE
`using PyPlot` in julia 0.4 kills the kernel

### ISSUE THREAD

**Issue by rodrigolece** [JuliaLang/julia#13146]
I just migrated to julia 0.4. I'm trying to use PyPlot but the line `using PyPlot` immediately kills the kernel. In the Jupyter notebook I get the message `**Kernel Restarting**: The kernel appears to have died.` In the REPL I get: 

```
WARNING: could not import Base.help into PyCall
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

I get the same first line if I import `PyCall` but I think the real problem is in the other four lines. I found [this post](http://unix.stackexchange.com/questions/184504/linux-mint-13-problem-no-module-named-site) regarding that same message, and the problem seems to be that the system can't find `
usr/lib/python2.7`, but I seem to have everything in order under that directory. 

I'm running Mac OS 10.9.5, `PyPlot` version 2.0.1 and julia version:

```
julia> versioninfo()
Julia Version 0.4.0-rc1+7
Commit 39e2493* (2015-09-10 20:01 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
Try `Pkg.checkout("PyCall"); Pkg.build("PyCall")` to grab the latest PyCall version.

**Comment by rodrigolece** [comment]
Wow that was easy, but I didn't see it since I disregarded the PyCall message. Thanks!

**Comment by kevinpolisano** [comment]
I have a similar problem on Mac OS 14.0, `using PyPlot` leads to:

```julia
julia> using PyPlot
[1]    13395 killed     /Applications/Julia-1.9.app/Contents/Resources/julia/bin/julia

Saving session...completed.

[Opération terminée]
```

```julia
julia> versioninfo()
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
```
