### ISSUE TITLE
Defining set operators for non-set types?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13154]
I notice that Base defines certain set operators (`∪ ∩ ⊆`) for all types, but others (`⊊ ⊈`) only for `Set`.

I am defining my own set-like type and would like to extend these operators. This inconsistency is slightly annoying. There are two possible solutions:
1. `Set` defines these operators only for `Set`
2. `Set` defines these globally as alternative to ASCII names such as `union`, `intersect`, `issubset`
   I'd be happy with either solution.

Possible names for the currently undefined operator shortcuts could be (taken from their latex names):
  `⊊` = `issubsetneq`
  `⊈` = `isnsubseteq`

At the same time, and similar to the case of `∈` and `∋`, we could define all of these (taken from `latex_symbols.jl`):
    "\subset" => "⊂",
    "\supset" => "⊃",
    "\nsubset" => "⊄",
    "\nsupset" => "⊅",
    "\subseteq" => "⊆",
    "\supseteq" => "⊇",
    "\nsubseteq" => "⊈",
    "\nsupseteq" => "⊉",
    "\subsetneq" => "⊊",
    "\supsetneq" => "⊋",

**Comment by JeffreySarnoff** [comment]
Which of these would you choose as primary, the basis for defining/specifying the others?

**Comment by eschnett** [comment]
For backward compatibility, I would keep `issubset`, and I would add `issubsetneq`. The latter is already implemented (as `<` operator) for `Set`. The others are negations and argument permutations.

**Comment by ScottPJones** [comment]
I noticed that Mathematica, subset means what you have for subseteq, i.e. `⊆`.  Is that going to confuse anybody?

**Comment by ScottPJones** [comment]
```
Deprecated Symbols
Subset, Superset
⊂ is sometimes used to mean "S is a subset of T" in the sense that S is permitted to equal T, that is, for which we have specified as S⊆T.

Similarly, ⊃ is sometimes used to mean S⊇T.

Although many sources use these interpretations, they are emphatically not recommended, as they can be the cause of considerable confusion.
```

**Comment by JeffreySarnoff** [comment]
My preference would be for their operational availability with Set without confining them to Set only.

**Comment by ScottPJones** [comment]
Instead of `issubsetneq`, what about `ispropersubset`?

**Comment by JeffBezanson** [comment]
I'm confused --- having ASCII aliases might be fine, but what is the source of difficulty in extending the operators? The operators can be extended without ASCII aliases.

**Comment by eschnett** [comment]
@JeffBezanson For example, `set.jl` defines this:
```Julia
const ⊆ = issubset
⊊(l::Set, r::Set) = <(l, r)
⊈(l::Set, r::Set) = !⊆(l, r)
```
To extend this, I have to implement `issubset`, `⊊`, and `⊈`; I cannot implement `⊆`. That is not difficult, but it's less consistent than it could be.

One option is to have `set.jl` define `⊆` only for `Set` arguments.
Another option is to define `⊊` and `⊈` (via `const`) to ASCII names that are in turn only defined for `Set` arguments.

**Comment by JeffBezanson** [comment]
Thanks, I see now. I guess we should define `⊈(x,y) = !(x⊆y)` the same way we have `!=(x,y) = !(x==y)` ?

**Comment by eschnett** [comment]
@JeffBezanson Yes, that's one option. In addition, I'd introduce `ispropersubset` and defined `const ⊊ = ispropersubset`.

**Comment by ScottPJones** [comment]
Why is the proper subset function `<` in Julia?
I worry about that, because what if you do have something that is set-like, that you also want to order in some fashion?

**Comment by eschnett** [comment]
@ScottPJones I assume that `Set` provides both `<` and `isless`; the latter should define an order. By default, `isless = <`.

**Comment by oscardssmith** [comment]
Fixed in master.
