### ISSUE TITLE
Weird bug(?) with dispatch(?) in 0.4

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#13156]
I've simplified this as much as possible from my use case:

``` julia
julia> func1{U<:AbstractArray, V}(arg::Union{AbstractArray{U},V}) = typeof(arg)
func1 (generic function with 1 method)

julia> func1(Array{Any}[Array{Any}(1, 1)])
Array{Array{Any,N},1}

julia> func2{U<:AbstractArray, V}(arg::Union{AbstractArray{U},Set{V}}) = typeof(arg)
func2 (generic function with 1 method)

julia> func2(Array{Any}[Array{Any}(1, 1)])
ERROR: MethodError: `func2` has no method matching func2(::Array{Array{Any,N},1})
Closest candidates are:
  func2{U<:AbstractArray{T,N},V}(::Union{AbstractArray{U<:AbstractArray{T,N},N},Set{V}})
```

Surely both of these should work as they're both satisfying one component of the union?

**Comment by JeffBezanson** [comment]
Interesting. Actually it's possible neither should work, since there's a rule that all method static parameters must be matched for the method to match.

Thanks for the nicely reduced test case.

**Comment by iamed2** [comment]
YW. For completeness' sake, here is the signature of the method I'm actually trying to write: 

```julia
function fetchinto!{T<:DatabaseInterface, U<:Union{AbstractArray, Associative}, V<:Any}(
        preallocated::Union{AbstractArray{U}, Associative{V,U}},
        cursor::DatabaseCursor{T}
    )
    # ...
end
```

**Comment by simonster** [comment]
I think you should be able to do:

````julia
typealias AssociativeVK{V,K} Associative{K,V}
function fetchinto!{T<:DatabaseInterface,U<:Union{AbstractArray,Associative}}(
        preallocated::Union{AbstractArray{U},AssociativeVK{U}},
        cursor::DatabaseCursor{T}
    )
    # ...
end
```

**Comment by iamed2** [comment]
Thanks @simonster that does work for my case!

**Comment by tkelman** [comment]
closed as duplicate / subset of type system rewrite?

**Comment by JeffBezanson** [comment]
Closed because (1) there was an accepted workaround, (2) the described behavior is actually correct (all static params must be matched for a method to match).

**Comment by iamed2** [comment]
The real design problem might be solved with the new type system too.
