### ISSUE TITLE
linearindexing docs inconsistent with code

### ISSUE THREAD

**Issue by GlenHertz** [JuliaLang/julia#13161]
If you define your own Array wrapper according to the docs with linearindexing = LinearFast(), the docs say:

> LinearFast() arrays are simple: just define getindex(A::ArrayType, i::Int). When the array is subsequently indexed with a multidimensional set of indices, the fallback getindex(A::AbstractArray, I...)() efficiently converts the indices into one linear index and then calls the above method.

However, when I implement my own array wrapper:

``` Julia
immutable MyArray{T,N} <: AbstractArray{T,N}
    data::Array{T,N}
end
MyArray{T}(::Type{T}, dims::Int...) = MyArray(Array{T}(dims...))
MyArray{T,N}(::Type{T}, dims::NTuple{N,Int}) = MyArray(Array{T}(dims...))

Base.size(A::MyArray) = size(A.data)
Base.similar{T}(A::MyArray, ::Type{T}, dims::Dims) = MyArray(T, dims)

Base.linearindexing(::Type{MyArray}) = Base.LinearFast()
Base.getindex(A::MyArray, i::Int) = A.data[i]
Base.setindex!(A::MyArray, v, i) = A.data[i] = v

t = MyArray(Float64, (3,5))

t[1]
t[2]
t[3]
t[1, 2]
```

I get the error `ERROR: LoadError: indexing not defined for MyArray{Float64,2}` which comes from abstractarray.jl:486.

Any insight as to what the root issues is?

**Comment by simonster** [comment]
Needs to be:

```julia
Base.linearindexing{T<:MyArray}(::Type{T}) = Base.LinearFast()
```
