### ISSUE TITLE
readdlm no longer able to handle unicode without specifying a delimiter

### ISSUE THREAD

**Issue by darwindarak** [JuliaLang/julia#13179]
`readdlm` used to be able to parse this test sample just fine

```
# Rate of rotation: Ω = 2π
1.0, 2.0, 3.0
```

but I think #12688 removed the `rem(::UInt32, ::Type{Char})` function used in [`dlm_parse at datafmt.jl:368`](https://github.com/JuliaLang/julia/blob/5b821988880f9706ddbeb3288ec578b15c9942c7/base/datafmt.jl#L368).

Is it better to add those functions back in `base/char.jl` or modify `dlm_parse` to not use that method at all?

**Comment by tkelman** [comment]
This went unnoticed for longer than it should have, thanks for the report. I don't think `rem` of an integer by a `Char` makes any sense, so would be better to figure out what that line of code is supposed to be accomplishing and do it differently.

**Comment by darwindarak** [comment]
If I'm understanding that line correctly, for each delimiter type `D` there is a single invalid delimiter value:
```
D == UInt8  -> 0xfe
D == UInt16 -> 0xfffe
D == UInt32 -> 0xfffffffe
```
If the user supplied delimiter is invalid, then we use the default set of delimiters instead.  I think we can get the same result with

```julia
is_default_dlm = (dlm == UInt32(invalid_dlm) & UInt32(256^sizeof(D) - 1)
```

where 

```julia
const invalid_dlm = Char(0xfffffffe)
```

is at the beginning of `datafmt.jl`,

**Comment by hayd** [comment]
rem was used to mean convert/call. It's still used [in several places in this file](https://github.com/JuliaLang/julia/blob/5b821988880f9706ddbeb3288ec578b15c9942c7/base/datafmt.jl#L360).

Should this rem usage have been added to deprecate? (to one of `Char(65)` or `convert(Char, 65)`)

```
julia> 65 % Char  # julia 0.3
'A'
```

*This seems a little fishy (for non-ascii).*

**Comment by hayd** [comment]
The above seems like it could better be defined as:
```
invalid_dlm(::UInt8) = 0xfe
invalid_dlm(::UInt16) = 0xfffe
```
and check equality.

**Comment by darwindarak** [comment]
That does seem cleaner.  It looks like we would only need to define `invalid_dim` for int-types up to 32 bits and `Char`.

**Comment by stevengj** [comment]
+1 for @hayd's method.
