### ISSUE TITLE
Infinite recursion in compiler

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#13183]
This hangs in 0.4 and stackoverflows in 0.3:
```julia
g{X}(x::X,y...) = g(X,x,y)
g{X}(::Type{Int},x::X,y...) = y
g(5,6)   # works
g(5.0,5) # hangs in 0.4, stackoverflow in 0.3
# these work:
g(Int,3,4)
g(Int,3)
```
(edit: see test case below)

**Comment by lostanlen** [comment]
What behavior would you expect ? Automatic conversion of Float64 `5.0` to Int `5` ? IIUC, the second method never gets called in your second example `g(5.0, 5)` so the first method keeps being called ad nauseam, thus increasing the number of arguments.

**Comment by mauro3** [comment]
I see.  I expected a no method error but you're right it calls itself.  But why no stackoverflow in 0.4?

**Comment by mauro3** [comment]
Reduced test-case for 0.4 which does not hang:
```
julia> g(x...) = g(x, x)
g (generic function with 1 method)

julia> g(4)
ERROR: OverflowError()
 in g at none:1 (repeats 13 times)
```
vs one which does hang (now also in 0.3):
```
julia> gg{X}(x::X...) = gg(x, x)
gg (generic function with 2 methods)

julia> gg(5)
```

Feel free to close this if this is the expected outcome.

**Comment by mschauer** [comment]
The second example hangs in type inference and does not loop at all.
```
gg{X}(x::X...) = begin println(x); gg(x, x); end
```

 The problem is not that you are  writing down an infinite loop, but that you are causing one in the compiler and as @JeffBezanson says, "No; the compiler should terminate on all programs, at least :)"

**Comment by mauro3** [comment]
Excellent, then this is a bona fide bug! (changed title again)

**Comment by tkelman** [comment]
backported in #13182
