### ISSUE TITLE
Set function to check for intersection?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13189]
When dealing with sets, one often needs to check whether two sets have a non-empty intersection, but the intersection itself is not interesting. This can currently be written as `isempty(a ∩ b)`, but this is likely much less efficient. There should be a function that checks for intersection, returning `Bool`.

What would be a good name for this? Python uses `isdisjoint`.

**Comment by JeffBezanson** [comment]
Seems like a good idea, and a decent name. This seems to be one of those weird cases where the only word for something is negative; you can be "disjoint" or even "nondisjoint" but not "joint".

**Comment by eschnett** [comment]
You can be "intersecting", so `isintersecting` would also work.

However, if you allow three sets as arguments, the meanings differ -- `isdisjoint` implies they are all disjoint, whereas `isintersecting` implies they are all intersecting, thus they are not opposites. (This is relevant since Base has multi-argument methods for `intersect` and `union`.)

**Comment by StefanKarpinski** [comment]
It depends on if you mean pairwise disjointness and pairwise intersection or not.

**Comment by rfourquet** [comment]
Fixed in #34427.
