### ISSUE TITLE
a small inconsistency with eltype/keytype/valtype

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#13194]
Observe the error below (0.5.0 recent master); I would suggest that the appropriate keytype/valtype methods be defined for consistency.

```
julia> D = Dict("a"=>1, "b"=>7)
Dict{ASCIIString,Int64} with 2 entries:
  "b" => 7
  "a" => 1

julia> eltype(D)
Pair{ASCIIString,Int64}

julia> eltype(typeof(D))
Pair{ASCIIString,Int64}

julia> keytype(D)
ASCIIString

julia> keytype(typeof(D))
ERROR: MethodError: `keytype` has no method matching keytype(::Type{Dict{ASCIISt
ring,Int64}})

julia>
```

**Comment by ScottPJones** [comment]
I don't understand, what is the `keytype` of a `DataType` supposed to be?
I'd expect `keytype(D)` to return `ASCIIString`, and `valtype(D)` to return `Int64`, but that's it.

**Comment by nalimilan** [comment]
@ScottPJones `fieldnames(Dict)` returns the fields of the `Dict` type, not those of `DataType`, so it would make sense for `keytype(Dict{ASCIIString,Int})` to return `ASCIIString`. I think the reasoning behind the current behavior of `eltype` is that sometimes you only have the type of a collection, not an instance, and you still want to know what the element type is.
