### ISSUE TITLE
Call to C (ccall) passing Cstring works only if preceded by println()

### ISSUE THREAD

**Issue by andrewcooke** [JuliaLang/julia#13196]
I don't have a short demo for this, and I am on vacation, so I may not be able to provide one for some time.  But since this is in RC1, and is such weird behaviour, I am hoping the description alone may be sufficient for someone to fix the issue or point out what I am doing wrong (it may be a mistake in how ccall is used) (if not, well, I'll try reducing it when I have time).

The problem is seen in the code at https://github.com/andrewcooke/Drawing.jl/tree/0d38df3c8b7e09809b077be34adb6dcbf7b24d91

In particular, I am running this test from the command line - https://github.com/andrewcooke/Drawing.jl/blob/0d38df3c8b7e09809b077be34adb6dcbf7b24d91/test/align.jl - using "julia test/align.jl".

The routine above displays text using pango and cairo.  The critical code is at https://github.com/andrewcooke/Drawing.jl/blob/0d38df3c8b7e09809b077be34adb6dcbf7b24d91/src/Drawing.jl#L574 - if the println() linked above is enabled, then the text is printed correctly.  If the println is commented out (as linked) then only the first two characters ("al") of the first ("align=1") of 9 strings (align=1 to 9) is displayed by cairo / pango.

As far as I can tell (from the size of the pango layout), when nothing is displayed, the code is behaving as if the string passed to set_text is empty (or just two characters).  The set_text call is at https://github.com/andrewcooke/Drawing.jl/blob/0d38df3c8b7e09809b077be34adb6dcbf7b24d91/src/cairo.jl#L171

I am using julia v0.4.0-rc1 built from git.

Bad result:
![align](https://cloud.githubusercontent.com/assets/1429281/9949766/e078e4dc-5d87-11e5-8814-b8b8ac947cab.png)

Good result: 
![align](https://cloud.githubusercontent.com/assets/1429281/9949791/4fd57a16-5d88-11e5-8334-9690efb83ef1.png)

**Comment by yuyichao** [comment]
AFAICT you are missing the `int length` parameter to the [`pango_laout_set_text` function](https://developer.gnome.org/pango/stable/pango-Layout-Objects.html#pango-layout-set-text)

**Comment by andrewcooke** [comment]
oh, you're absolutely right,  that makes a lot of sense.  sorry! / thanks
