### ISSUE TITLE
Reinterpret is not aware that tuples are bitstypes now

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#13209]
```
julia> Tuple{UInt}
Tuple{UInt64}

julia> isbits(Tuple{UInt})
true

julia> isbits((1, 1))
true

julia> reinterpret(Tuple{UInt}, (1, 1))
ERROR: reinterpret: expected bits type as first argument
 in reinterpret at essentials.jl:116
```

The same problem with Complex{Real} for example.

**Comment by yuyichao** [comment]
I think this is probably a dup of https://github.com/JuliaLang/julia/issues/11822

AFAIK, the issue is that `reinterpret` is expecting a `bitstype`, not only `isbits() == true`.

**Comment by vtjnash** [comment]
while, they do qualify as `isbits`, Tuples aren't bitstypes. (I'm pretty sure there is already an issue open about whether the extend reinterpret to cover more types)
