### ISSUE TITLE
`auto_unbox` error due to Uint8 deprecation

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#13204]
Mentioned in https://github.com/JuliaLang/julia/commit/1b6efc7ab297b7b8aea4d7cb0b52fb589392042b and https://github.com/JuliaLang/julia/pull/13107#issuecomment-140874488, but since there's no issue open:

```jl
julia> function bar(lib)
           soname = ccall(:jl_lookup_soname, Ptr{Uint8}, (Ptr{Uint8}, Csize_t), lib, sizeof(lib))
           if soname != C_NULL
               println("not null")
           else
               println("null")
           end
       end
bar (generic function with 1 method)

julia> bar("libfoo")
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
in bar at none:2
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
in bar at none:2
ERROR: auto_unbox: unable to determine argument type
 in bar at none:3
```
but it works fine if you use the uppercase `UInt8` instead.

**Comment by timholy** [comment]
This is quite breaking, so I added the tag.

**Comment by yuyichao** [comment]
Isn't this already fixed by https://github.com/JuliaLang/julia/pull/13180 ?

**Comment by yuyichao** [comment]
IIUC Tony have already confirmed with PkgEval that the fixed the issue so I'm going to close this. Feel free to reopen if it is still a problem.

**Comment by timholy** [comment]
Not in `release-0.4` yet. I can't keep up with all the email, so I'll just ask: already slated, or does something more need to be done?

**Comment by mbauman** [comment]
It's due to be merged in https://github.com/JuliaLang/julia/pull/13182

**Comment by yuyichao** [comment]
It should work on master already and I think it's in Tony's latest queue of 0.4 backport.
