### ISSUE TITLE
anything like python pickle?

### ISSUE THREAD

**Issue by windyrobin** [JuliaLang/julia#13202]
in scala/python , we could send the code to remote worker to execute:

x = 1;
function  addx(y) 
  return x + y
end 

str = pickle(addx(Int))

the remote get 'str' and unpicke adn execute the code

**Comment by timholy** [comment]
JLD supports anonymous functions now, thanks to a very nice contribution by 
"amack315":
https://github.com/JuliaLang/JLD.jl/pull/16

--Tim

**Comment by ViralBShah** [comment]
This really should be a question on julia-users.

**Comment by JeffBezanson** [comment]
Sending functions to remote workers already works automatically.

**Comment by windyrobin** [comment]
```
Sending functions to remote workers already works automatically.
```
@JeffBezanson  but I want the export interface and make sure that it supports clousre

**Comment by JeffBezanson** [comment]
Yes it supports closures. You can pass closures as arguments to `remotecall`, or if you really want to serialize a function manually you can call `serialize(iostream, func)`.
