### ISSUE TITLE
repl.c's dependency on HEADERS is not mentioned in Makefile

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#13201]
`src/Makefile` defines a `HEADERS` variable with all the julia headers each object is likely to depend on, so that the object files in `src` will be recompiled if any julia header changes.  However, `ui/Makefile` should do the same thing for `ui/repl.c`, but it does not -- the headers can change without `repl.o` being recompiled, and one can only compensate for this by running `make clean` explicitly.  I discovered this after pulling from the `release-0.4` branch where the `VERSION` was updated.  After running `make,` `./julia --version` returned the *old* version number, and the test suite failed.  It wasn't until I ran `make clean` and re-ran the build that `julia --version` printed the correct string and the test suite passed.

**Comment by Keno** [comment]
dup of #12973 ;).

**Comment by garrison** [comment]
thanks, searched for `repl Makefile` and didn't find it.
