### ISSUE TITLE
A \ b with rectangular & low rank A

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#13216]
I'm surprised by the result of `qrfact(A) \b` when A has low column rank

```julia
a = ones(100)
b = rand(100)
qrfact([a a]) \ b
#2-element Array{Float64,1}:
# -9.42714e11
#  9.42714e11
```
The documentation of qrfact says "When A is rectangular, \ will return a least squares solution and if the solution is not unique, the one with smallest norm is returned."

Also, one gets
```julia
[a a] \ b
#2-element Array{Float64,1}:
# 0.251787
# 0.251787
```
The result is correct but I expected to get something like `[0.5, 0.0]`.

**Comment by jiahao** [comment]
Recall that the documentation say that `\` will return the solution with the minimum norm. [0.251787, 0.251787] does have a smaller (2-)norm than [0.5, 0.0], so I don't see immediately why this wrong.

For the former, what you are seeing is amplification of roundoff error. The `R` factor computed on my machine is

```jl
julia> qrfact([a a])[:R]
2x2 Array{Float64,2}:
 -10.0  -10.0        
   0.0    4.41863e-15
```

and similarly if you look at the `:Q` basis generated, the vectors are almost linearly dependent. As a result, doing `qrfact([a, a]) \ b` forces Julia to solve the problem using the nearly singular unpivoted QR factorization (`pivot = Val{false}` by default).

The correct resolution is to use a pivoted QR to avoid the numerical instability. Julia provides column pivoting with `pivot = Val{true}`, which is what `[a a] \ b` does underneath. Have a look at `@which [a a] \ b`.

**Comment by jiahao** [comment]
Also, this is not a bug and therefore should have been asked on [julia-users](https://groups.google.com/forum/#!forum/julia-users).
