### ISSUE TITLE
pmap hides errors/warnings

### ISSUE THREAD

**Issue by axsk** [JuliaLang/julia#13224]
Using 
```
pmap(sqrt,[-1]); "some other return val"
``` 
hides the error to be displayed to stdout.

This also partially applied to warnings, but I couldn't find a simple way to reproduce it (```pmap(warn,["warning"])``` actually shows the warning, but nested warnings in my real life code actually don't get displayed).

**Comment by jiahao** [comment]
`pmap` now returns `RemoteException` objects for errors (and I believe nothing for warnings).

Duplicate of #12908

**Comment by axsk** [comment]
True
