### ISSUE TITLE
Nested @time and @profile with closure gives syntax error

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#13229]
```jl
@time @profile for i = 1:5
    function f(x)
        return x + i
    end
    f(i)
end
```
gives

```jl
ERROR: syntax: misplaced return statement
```

Removing the return statement or any of the macros makes it run as expected. Maybe it is wrong to chain macros like this? Reversing the macros also works.

**Comment by ihnorton** [comment]
Dupe of #1784

**Comment by ihnorton** [comment]
This is actually somewhat distinct from #1784. We need to improve the `hasbreak` condition in the `try` expander to exclude function definitions.

**Comment by ihnorton** [comment]
This appears to be fixed (presumably by jb/functions?). Test in #15159.
