### ISSUE TITLE
Linear indexing of sparse matrices is slow

### ISSUE THREAD

**Issue by mb1234** [JuliaLang/julia#13223]
Case 1: this is quite slow for what is just a resize.

```
julia> r=[1;10000]
2-element Array{Int64,1}:
     1
 10000

julia> A=sparse(r,r,r)
10000x10000 sparse matrix with 2 Int64 entries:
	[1    ,     1]  =  1
	[10000, 10000]  =  10000

julia> B=A[:]
100000000x1 sparse matrix with 2 Int64 entries:
	[1        ,         1]  =  1
	[100000000,         1]  =  10000
```

Case 2: This one crashes even tho the 64 bit intsize should be enough to accomodate an index of 1e10.

```
julia> r=[1;100000]
2-element Array{Int64,1}:
      1
 100000

julia> A=sparse(r,r,r)
100000x100000 sparse matrix with 2 Int64 entries:
	[1     ,      1]  =  1
	[100000, 100000]  =  100000

julia> B=A[:]
ERROR: OutOfMemoryError()
 in getindex at sparse/sparsematrix.jl:1709
 in getindex at sparse/sparsematrix.jl:1295
```

**Comment by ViralBShah** [comment]
That is not just a resize. A fair amount of work is happening under the hood with index translation. It could be significantly faster though. In fact there is a comment in the code that says exactly that.

Cc: @tanmaykm

**Comment by ViralBShah** [comment]
Ignore my comment - the work here should be just for the two elements, and the code has a loop that goes over `1:length(A)`. This indexing case needs an O(nnz) implementation.

**Comment by mb1234** [comment]
Thanks Viral. Sorry I don't know the codebase, just getting the hang of julia with the idea of switching from matlab. You have a great community of programmers here! x
