### ISSUE TITLE
new line in Base.Markdown

### ISSUE THREAD

**Issue by nassarhuda** [JuliaLang/julia#13238]
The Markdown parser doesn't seem to recognize 3 spaces followed by a break as a new line (this feature: http://spec.commonmark.org/0.22/#hard-line-breaks)

Discussion here:
https://github.com/MichaelHatherly/Docile.jl/issues/155

**Comment by shashi** [comment]
You can use the `\` syntax for hard line breaks

For example:
```julia
md"""
foo\
bar
"""
```

3 spaces and a new line seems like a misfeature to me: your editor will either not show it, or mark it in a jarring color as bad trailing whitespace. It also does not play well with `make check-whitespace`.

**Comment by jakebolewski** [comment]
I agree, trailing whitespace for hard newlines is crazy.  Best to standardize on one way of doing things.  I also don't think we have to follow every portion of the CommonMark spec as we are developing our own "non-standard" variant anyways.
