### ISSUE TITLE
Name the shortcuts to Julia installations a little more descriptively on Windows?

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/julia#13239]
I'm usually running at least two versions of Julia side by side (the latest release and a nightly build - and currently also the 0.4 rc line), installed from the binary packages since I don't have a working build chain set up on my Windows machine.

All these installations are, by default, just named `julia` in terms of their shortcuts etc, so my first action after installing (or updating) either version is always to rename the shortcuts to something more descriptive, like `julia 0.3.11`, `julia 0.4.0-rc2` or `julia 0.5.0-dev`. It would be really nice if at least the start menu shortcuts could use this naming convention automatically.

**Comment by tkelman** [comment]
Seems reasonable, see `contrib/windows/build-installer.nsi` for where the installer creates the shortcuts. Note that any change there would likely conflict with #12879

**Comment by twadleigh** [comment]
#12879 is currently blocked by a `mintty` bug. If this is issue can be resolved quickly (I see no reason it shouldn't), I can rebase #12879.

**Comment by vtjnash** [comment]
can we version the julia install and separate it by processor architecture also as part of the renaming effort?

**Comment by tlycken** [comment]
@vtjnash Do I understand you correctly if you by that mean that you'd like to have it be e.g. `Julia 0.4.0 rc2+4 x64`, or is there more information you want in there?

**Comment by vtjnash** [comment]
that sounds good

**Comment by tkelman** [comment]
Avoi spaces in the default install path if we can get away without them

**Comment by tlycken** [comment]
@tkelman I only really care about the start menu shortcuts (they're the ones that are frequently searched for, and/or listed next to eachother, at least in Windows 8 and up) so I'm not going to touch the installation paths.

@vtjnash The version number (`0.3.11`, `0.4.0-rc2`) is already available to the script, since it is included in the folder name of the installation path, but neither the `+XXX` (for "commits since") or the architecture seems to be readily available in the same way. Do you know how to get at them?

**Comment by tkelman** [comment]
is this closed by #13253?

**Comment by tlycken** [comment]
@tkelman: For my own needs, I'm quite happy with what's already there, so I don't mind closing this.

However, @vtjnash also wanted the commit number (`+1234` in `0.4.1+1234`) and architecture (`x86`/`x64`) in the names; I wasn't able to get at them, so I didn't do anything about that in 2a2de21.
