### ISSUE TITLE
julia-mode.el: Please don't define tests in the main library

### ISSUE THREAD

**Issue by lunaryorn** [JuliaLang/julia#13237]
I accidentally noticed that julia-mode.el defines its test right in the main library. 

It's very, very bad style, needlessly loads ERT for Julia mode files, and means that `M-x ert` will run Julia Mode tests as soon as Julia Mode was loaded, whether the user wants that or not.

No library should define its test inline.   Please, please don't do that, and move them into a separate test file instead.  Or at the very least, give me a flag to disable the tests.

**Comment by Wilfred** [comment]
Sorry, this is totally my fault. I didn't realise the consequences (we had no tests before) so I appreciate you explaining why this was a problem.

Should be fixed by #15140.
