### ISSUE TITLE
Multiple dispatch for anonymous functions

### ISSUE THREAD

**Issue by jumutc** [JuliaLang/julia#13259]
Is it possible to define multiple dispatched anonymous functions? Or the code snippet below is a bug? Maybe it is possible to introduce such a feature?

```julia
julia> test = (x::Int) -> println("Int")
(anonymous function)

julia> test = (x::Float64) -> println("Float")
(anonymous function)

julia> test(1)
ERROR: TypeError: anonymous: in typeassert, expected Float64, got Int32
 in anonymous at no file
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68

```
P.S. I have quickly searched through issues but couldn't find any related one.

**Comment by vtjnash** [comment]
for better clarity, the code above is equivalent to:
```
julia> ignoreme = something

julia> test = (x::Float64) -> println("Float")

julia> test(1)
```

anonymous functions can't easily use multiple dispatch because there is no syntax to create them. note that you can use named generic functions as closures, so there isn't really a need for this.

**Comment by jumutc** [comment]
Maybe if you consider creating anonymous functions with ```macro```?

**Comment by mauro3** [comment]
I don't think a macro can help.  

As far as I understand it, generic functions are a collection of anonymous functions:
```
julia> h(x::Int) = 1
h (generic function with 1 method)

julia> h(x::Float64) = 2
h (generic function with 2 methods)

julia> h.env.defs.func
(anonymous function)

julia> h.env.defs.func(5) # calls the anonymous function corresponding to the first method
1

julia> h.env.defs.func(5.0) # calls the anonymous function corresponding to the first method
1

julia> h.env.defs.next.func(5.0) # calls the anonymous function corresponding to the 2nd method
2

julia> h.env.defs.next.func(5)
2

julia> h.env.defs.next.next.func(5) # there are only two methods
ERROR: type Void has no field func
```
so making anonymous functions also generic would mean that some "super-anonymous functions" would need to be created to fill the method tables of generic functions and anonymous functions.  Probably not worth the hassle as your example can just be written as:
```
julia> test(x::Int) = println("Int")

julia> test(x::Float64) = println("Float")
```

Where anonymous functions are useful, there is no space anyway to define several methods:
```
map(x->sin(x), 1:10)
```

**Comment by jumutc** [comment]
OK, thanks for replying... closing this issue.
