### ISSUE TITLE
Libunwind compilation error on ARM

### ISSUE THREAD

**Issue by LTGZZ** [JuliaLang/julia#13268]

**Comment by LTGZZ** [comment]
Slackware ARM -current, soft-float.

../src/.libs/libunwind-arm.so: undefined reference to `AO_fetch_and_add'
../src/.libs/libunwind-arm.so: undefined reference to `AO_fetch_and_add1'
collect2: error: ld returned 1 exit status
make[1]: *** [Gperf-simple] Error 1
make[1]: Leaving directory `/tmp/SBo/libunwind-1.1/tests'

Have the same error with julia's libunwind.

**Comment by LTGZZ** [comment]
BTW :
override USE_SYSTEM_LAPACK=1
override USE_SYSTEM_BLAS=1
override USE_SYSTEM_LIBGIT2=1
override USE_SYSTEM_LLVM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1

**Comment by ViralBShah** [comment]
#14774 should probably fix this.

**Comment by yuyichao** [comment]
I don't think so. The patch I add are mainly for aarch64 and the ARM part shouldn't fix any compilation.
