### ISSUE TITLE
`@which` not working with splatting

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#13264]
This used to work in 0.3 but not on 0.4-RC2:
```
julia> h(x...) = x; x=1:5;

julia> @which h(x...)
ERROR: ArgumentError: argument is not a generic function
 in methods at ./reflection.jl:140
 in which at ./reflection.jl:292
```

Macro-expandsion suggests that something changed in 0.4:
```
julia> macroexpand(:(@which h(x...)))
:(Base.which(top(_apply),(Base.typesof)((top(getfield))(Main,:call),h,x)))
```
vs 0.3:
```
julia> macroexpand(:(@which h(x...)))
:(Base.which(h,Base.typesof(x...)))
```

**Comment by mauro3** [comment]
`@code_*` suffer the same affliction.

**Comment by mauro3** [comment]
This bug was introduced in 38e48882c008 by @andreasnoack.

**Comment by vtjnash** [comment]
It looks like that code needs to detect calls to `_apply` and attempt to transform them to regular function calls

**Comment by andreasnoack** [comment]
I have a fix which hopefully isn't breaking anything.
