### ISSUE TITLE
¬∨∧instead of ! || &&

### ISSUE THREAD

**Issue by krux02** [JuliaLang/julia#13266]
Ok, I am rather new to the julia language, but I would like to hear some feedback about what you think about it. so please attack me if my idea sounds Stupid to you. I am not shure weather it is a good idea to post this as an issue or not, but I do not know where to post it otherwise.

So here is an example what already works in the language

    julia> ¬(x) = ! x
    ¬ (generic function with 1 method)

    julia> ∨(x,y) = x || y
    ∨ (generic function with 1 method)

    julia> ∧(x,y) = x && y
    ∧ (generic function with 1 method)

    julia> t(x) = (println(x); true)
    t (generic function with 1 method)

    julia> f(x) = (println(x); false)
    f (generic function with 1 method)

    julia> t(1) ∨ t(2) ∧ f(3)
    1
    2
    3
    true

    julia> t(1) || t(2) && f(3)
    1
    true

So far I am impressed that julia accepts ∨ and ∧ as operators and even does the priorities right. So the result is the same as the same expression with the built in operators || &&, but the side effects aren't. Of course I can write a makro that replaces all occurences of ∨, ∧ and ¬ with their builtin form ||, && and !, but I don't like the idea to put a makro call around every logical expression.

So my suggestion is, that the language itself accepts the operators ¬∨∧ as an alias of ! || &&.

**Comment by johnmyleswhite** [comment]
FWIW, you're hitting the difference between functions and special operators with non-standard evaluation semantics. (There's plenty of explanation of this concept in the SICP book by Abelson and Sussman.)

I'd prefer to minimize the number of special operators, but others may feel differently.

**Comment by jiahao** [comment]
We also have `|` and `&` which do not short-circuit.

**Comment by ScottPJones** [comment]
If anything, I'd rather see `and` and `or` for `&&` and `||` (the latter ones only being "easy" for people who already know C/C++/Java)

**Comment by StefanKarpinski** [comment]
Having aliases for control flow operators seems like a bad idea. These Unicode operators should remain available for expressing lattice operations (or whatever people want to use them for).

**Comment by krux02** [comment]
@StefanKarpinski I think you are right in one point, that having too many alternatives to do the same thing is not really a good thing. And I do also not want to argue here about anything. My point is more, that ¬∨∧ are the operators that I learned in school as logical operators, and I would be really happy to finally have a programming language that supports them properly, instead of those ASCII fallback solutions that were invented in older programming languages (&& ||). But now there is the chance to fully support the real symbols.

@ScottPJones what do you thing about \and and \or for the replacement engine additionally to the latex versions \wedge \vee.

@jiahao having a non short-circuit version is not really the point. But if you refer to "if you want to change && you also have to change & " then you are right we would also need an operator for & and | and ~ (binary not). What do you think about `.¬` ,`.∨` and `.∧` like those operators that go elementwise on vectors?

@johnmyleswhite I know Scala you have the opetion to pass an argument by name. That means that the expression you pass to a function only gets evaluated, if the argument is actually needed by the function. That allowed to write constructs that did semantically the same as && || , but also `for` loops like in C or if statements.

**Comment by tkelman** [comment]
opinion is a bit divided whether elementwise & should be spelled with a dot right now. rather than add more dot operators we'd prefer a more general solution, see #8450

**Comment by StefanKarpinski** [comment]
The logical operators in mathematics aren't control flow operators, so it seems like you should be satisfied to have `const ∨ = |`, etc., which you can currently do.

**Comment by ScottPJones** [comment]
@krux02 If `and` and `or` are used for conditional and & or, then I probably wouldn't want them also used for control flow, I'd agree with Stefan on that.

**Comment by jiahao** [comment]
> My point is more, that ¬∨∧ are the operators that I learned in school as logical operators, 

But they are far from the only notation for these operations, not do these symbols unambiguously mean what they mean in mathematical logic. For this reason it is not a good idea to canonicalize these symbols to mean what you mean them to mean.

Consider that _Principia Mathematica_ (Whitehead and Russell, 1910) uses the following notation instead

<img width="620" alt="screen shot 2015-09-22 at 3 17 02 pm" src="https://cloud.githubusercontent.com/assets/1732/10028962/71a9e434-613d-11e5-9b11-087a1ea1e6cc.png">

and that `∨`/`∧` are also used in lattice theory for operations much more general than logical and/or.

The fact that you can define them at the user level but run into issues with side effects  is directly addressed by @johnmyleswhite's comment about nonstandard evaluation and my comment about the existence of non-short-circuiting variants `&` and `|`.

**Comment by krux02** [comment]
@jiahao yes you are right, that these symbols are not the only symbols, but other symbols are rather rare to find, at least in the subset of work I've done so far. For the lattice, is it a problem if `¬∨∧` are already defined for bool types if you want to use them also more general?

for all the others contributing to my issue, that you for your opinions. I can live very well with && and || because I am used to them already for a very long time, yet I think that `&&`, etc were only introduced, because the set of available symbols did not provide `∧`, etc. Analog to C were `??<` was introduced for systems that do not have the `{` symbol.

**Comment by ScottPJones** [comment]
@krux02 As @StefanKarpinski pointed out, nice thing with julia, is that at least for the non-conditional versions of `and` and `or`, you can easily set up `∨∧` for the bitwise (and lattice etc) operators.

**Comment by toivoh** [comment]
Just to clarify: As long as `∨` and `∧` are functions it's fine to overload them for booleans, lattice types, etc. But if they would be synonyms for `||` and `&&` in the parser then they would be built-in constructs with specific semantics, and not overloadable (just like `||` and `&&` are not overloadable). There is no pass-by-name in Julia, and I doubt there ever will be, since it would interact in really strange ways with multiple dispatch. So I think the consensus here is that you can have all of this (and pretty much already have) except for the short circuit behavior.
When it comes to `¬` I don't see a problem because it has no short circuiting behavior anyway.

**Comment by krux02** [comment]
But you should not forget, that if the symbols `¬∨∧` were used instead of `!|&` then those symbols could be used for other things, things that have nothing to do with boolean logic or lattice. for example `|` is also used in unix system for piping output `cat somefile | sort | uniq`

**Comment by ScottPJones** [comment]
For `A || B` and `A && B`, it seems only A actually needs to evaluate to a boolean (or even an expression!) because frequently people do `A || throw(B)` or `A || return B`.  That really doesn't seem very consistent, so I don't really get the argument that A *must* be a boolean, and can't be overridden.
`A || B` really seems to be exactly equivalent to `(if !A ; B ; end)` and `A && B` to `(if A ; B ; end)`.
It seems that by simple adding a `handle_cond(A)`, with a definition `handle_cond(A::Bool) = A`,
that `if`, `while`, `&&`, and `||` could be totally extensible (and possibly `A ? B : C` as well).
Not allowing that seems to be against the idea that "we are all adults here", and that the language should not stand in your way.

**Comment by StefanKarpinski** [comment]
While freeing up ASCII operators is appealing, we aren't going to require using Unicode to program in Julia.

"Truthiness" is a terrible idea and isn't going to happen.
