### ISSUE TITLE
Libunwind compilation error on ARM

### ISSUE THREAD

**Issue by LTGZZ** [JuliaLang/julia#13270]
Slackware ARM -current, soft-float.

```
../src/.libs/libunwind-arm.so: undefined reference to AO_fetch_and_add' ../src/.libs/libunwind-arm.so: undefined reference toAO_fetch_and_add1'
collect2: error: ld returned 1 exit status
make[1]: *** [Gperf-simple] Error 1
make[1]: Leaving directory `/tmp/SBo/libunwind-1.1/tests'
```

Have the same error with julia's `libunwind`.

My `Make.user`:
```makefile
override USE_SYSTEM_LAPACK=1
override USE_SYSTEM_BLAS=1
override USE_SYSTEM_LIBGIT2=1
override USE_SYSTEM_LLVM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1
```

**Comment by pao** [comment]
(identical to #13268)

**Comment by LTGZZ** [comment]
Yup, I'm sorry it was closed, I don't know why.

**Comment by pao** [comment]
You may have accidentally hit the "Close and comment" button rather than the "Comment" button. Happens all the time because they're right next to one another. You are welcome to reopen when that happens, but this is fine. Thanks.

**Comment by vtjnash** [comment]
use the system libunwind, the upstream project hasn't yet made a release that supports ARM

**Comment by LTGZZ** [comment]
I've tried the latest release and also the upstream git version of libunwind, I have the exact same problem.

**Comment by LTGZZ** [comment]
I took a look at Debian patches, but no one seemed to address the issue.
I wonder how they succeeded to compile it because I also tried under Debian and it failed...

**Comment by yuyichao** [comment]
Have you tried to use the system libunwind? (Or does the distribution you use not have a libunwind package?) Looking at the libunwind source, you could probably try to run `make VERBOSE=1` to see what command `libunwind` uses for linking and add `-latomic_ops` in your `LDFLAGS` to see if it's just missing a library to link (and make sure you have the corresponding package installed.)

Also, I don't think ARM with soft-float is a supported target.

**Comment by yuyichao** [comment]
This seems to be the case https://github.com/archlinuxarm/PKGBUILDs/blob/034cf5528330a04cf61a711ff8175ca6b8c1cefd/extra/libunwind/PKGBUILD#L38

**Comment by tkelman** [comment]
I was fixing up libunwind's build system today and sending them patches, so if there's a good configure probe for this we can probably fix it in a less-hacky way.

**Comment by yuyichao** [comment]
I believe libunwind already have platform detection code so it's just a matter of adding the right flags.

**Comment by tkelman** [comment]
Is there some output during configure on arm that says something to the effect of "checking for atomics library: -latomic_ops" ?

**Comment by yuyichao** [comment]
In particular, it seems that it's a matter of uncommenting [this](https://github.com/tronical/libunwind/blob/8ce4738c30881bb43a5c15d62f905b89d7f00b50/acinclude.m4#L25)

**Comment by yuyichao** [comment]
And from the [archlinuxarm log](https://github.com/archlinuxarm/PKGBUILDs/commit/5a406400beb20ecdfa3665361186674a7d0d12df), it seems that this is only needed with armv5, which actually has the vfp2 instruction set we require as an optional extension.

**Comment by ViralBShah** [comment]
Is this still a problem?

**Comment by yuyichao** [comment]
This is an upstream problem and I don't think it's fixed.
