### ISSUE TITLE
try-wrapped exception not caught in embedded Julia (on windows?).

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#13271]
I think this is probably the same issue as #7315, but I'm hoping to get further along.

I have resuscitated my julia-in-a-mex-function embedding ([mexjulia](https://github.com/twadleigh/mexjulia)). I have a very simple mex file and am trying to bootstrap it up to something useful and general. In my mex function, I can:
 1. initialize the julia runtime (via `jl_init`);
 2. evaluate julia expressions (via `jl_eval_string`);
 3. call julia functions that have a mex-function-like signature (via `jl_call`).

After initialization I load `mexboot.jl` (via `jl_eval_string`):
```
# load user init script
haskey(ENV, "HOME") &&
isfile(ENV["HOME"]*"/.juliarc.jl") &&
include(ENV["HOME"]*"/.juliarc.jl");

using MATLAB
# would be great to redirect STD[IN|OUT|ERR]...

libmex = dlopen("C:/Program Files/MATLAB/R2015a/bin/win64/libmex", Libdl.RTLD_GLOBAL | Libdl.RTLD_LAZY)
mexfunc(fun::Symbol) = dlsym(libmex::Ptr{Void}, fun)
mex_printf(msg) = ccall(mexfunc(:mexPrintf), Int32, (Ptr{Uint8},), ASCIIString(string(msg)))

# test functions
function mexhello(nlhs::Int32, plhs::Ptr{Void}, nrhs::Int32, prhs::Ptr{Void})
  mex_printf(ENV["HOME"]*"\n")
  mex_printf(ENV["JULIA_PKGDIR"]*"\n")
  mex_printf(Pkg.dir()*"\n")
end

function mexlibpath(nlhs::Int32, plhs::Ptr{Void}, nrhs::Int32, prhs::Ptr{Void})
  mex_printf(MATLAB.matlab_library_path*"\n")
end
```
after which I can call `mexhello` via the mex function interface, and I get:
```
U:\
C:/tw
C:\tw\v0.5
```
so it looks like julia should be able to find the packages. Indeed, the `using MATLAB` triggers no errors. However, when I call `mexlibpath`, I get:
```
Error using jl_calld
A julia exception of type UndefVarError occurred: call to 'jl_call' failed
```
which is basically the error I get when I refer to anything from the `MATLAB` module, qualified or unqualified.

BTW, I'm running on Windows 7 64-bit.

**Comment by twadleigh** [comment]
Another issue I had to work around that might be relevant/related: when `jl_init` gets called in the mex function, matlab's current directory must be the julia bin directory, or matlab crashes. Further calls do not need to be made from the bin directory. (And I also verified that staying in the bin directory does not fix this issue.)

**Comment by twadleigh** [comment]
So I set a breakpoint at `builtins.c:125` in `jl_undefined_var_error` just as the error is about to be thrown. The next frame up the stack is a call to `jl_get_binding_or_error` with arguments `m = MATLAB` and `var = :matlab_library_path`. I poked through the bindings in `m` using:
```
(gdb) print ((jl_binding_t *)(m->bindings->table[0]))->name->name
```
with indices from 0 to 31 (m->bindings->size = 32). I got out 18 symbols, none of them particularly relevant to the `MATLAB` module. For the sake of completeness, they were: `digits!`, `stdin`, `Int64`, `sexpr_indent_width`, `Tuple`, `eval`, `let`, `newvar!`, `Complex`, `zscal_`, `significand`, `in_stream`, `Any`, `ninitialized`, `out`, `BitArray`, `call`, and `MATLAB`.

**Comment by twadleigh** [comment]
I checked that the issue is the same on 0.4 rc2 as well as master.

**Comment by ihnorton** [comment]
Please post a backtrace.

**Comment by twadleigh** [comment]
It is mysteriously working for me at this moment, though there were no obvious changes to my environment or the code between my check against 0.4-rc2 and now.

I did decide to circumvent `jl_init` and do my own setting of the paths in `jl_options` before calling `julia_init`. Maybe that did the trick, but I thought I saw the failure immediately after making that change, too.

I'll close this, but will reopen if it appears again.

**Comment by twadleigh** [comment]
OK, I'm having issues again. I also figured out how to get a backtrace: I call `jlbacktrace()` in my mex function error handler while making sure to launch matlab from an msys/cygwin terminal. (When launched from `cmd`, `stderr` is the bitbucket.)

Here is the backtrace (from the invocation of `mexFunction`):
```
jl_unprotect_stack at  (unknown line)
jl_throw at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_error at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
blas_vendor at util.jl:220
__init__ at linalg.jl:241
jlcall___init___87 at  (unknown line)
jl_apply_generic at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_module_run_initializer at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_init_restored_modules at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
jl_get_builtin_hooks at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
julia_init at C:\tw\Julia-0.5.0-dev\bin\libjulia.dll (unknown line)
mexFunction at  (unknown line)
```
So loading the system image fails when trying to reload the blas. I suspect that means it's a DLL conflict between openblas (against which this version of Julia was built) and mkl (which matlab uses and may already have loaded in process).

I don't have time to take this further right now, but, assuming this does come down to DLL conflict, a couple of paths forward include:
1. building Julia against matlab's mkl;
2. patching `Base` so as not to be confused by another kind of blas that may already be loaded in process.

(1) might be the path of least resistance, but (2) is probably the better solution.

**Comment by tkelman** [comment]
Was openblas loadable on the julia load path? Strange that would error in a fatal way, but it might be matlab not liking when you throw exceptions in a mex file. Windows MKL would be a bit tricky to get working, it uses a different fortran naming convention than gfortran.

**Comment by twadleigh** [comment]
@tkelman, whatever is going on, it's fragile. It wasn't working, then was, now it's not. One of the things I do is make sure the julia bin dir is at the front of the path before I call the mex file, so openblas is loadable (and apparently it was loadable and not causing errors for about a 24 hour period).

When it was working, I could throw exceptions and matlab would handle them and print a nice message if the mex file didn't handle them first, so I don't think that's the issue.

> Windows MKL would be a bit tricky to get working, it uses a different fortran naming convention than gfortran.

So maybe (2) is the only way forward. Or, at least (1) isn't quite the easy path.

Hmm, the exception is generated in a `try` block. What could cause julia not to catch the exception? Maybe I didn't clear some previous exception?

**Comment by twadleigh** [comment]
OK, I think the current issue may be a function of my custom version of `jl_init`. The `jlapi.c` version has a `jl_clear_exception` at the end, while mine has an error check (which will then clear the exception).

I'll try that out and close (again) if that fixes this current issue.

**Comment by tkelman** [comment]
Matlab crashing in ways related to exceptions in mex files does not surprise me. Somewhere they have docs that say it's undefined and unsupported.

**Comment by twadleigh** [comment]
That crashiness was due to another bug I introduced when making that change. My mex function is properly handling julia's exceptions again (in the best way it knows how).

I still can't say why the exception thrown as shown at the top of the backtrace is not being caught in julia, as it is wrapped in a `try`. The exception is supposed to be generated, too. It's not some wierdness giving rise to it. It's part of a test for the openblas word size.

**Comment by twadleigh** [comment]
I am consistently getting this backtrace:
```
rec_backtrace at  (unknown line)
rec_backtrace_ctx at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_throw at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_error at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
blas_vendor at util.jl:220
__init__ at linalg.jl:241
jlcall___init___87 at  (unknown line)
jl_local_in_ast at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_trampoline at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_init_types at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_apply_generic at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_breakpoint at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_module_run_initializer at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_init_restored_modules at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
jl_atexit_hook at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
julia_init at C:\tw\Julia-0.5.0-dev\bin\libjulia-debug.dll (unknown line)
mexFunction at  (unknown line)
```
The `blas_vendor` line throws a exception wrapped in a `try` block (with no `rethrow`). What could cause a `try` block to fail to stop the propagation of an exception?

**Comment by ihnorton** [comment]
> What could cause a try block to fail to stop the propagation of an exception?

Regardless of the `try` block, `jl_exception_occurred` is still going to tell you an exception happened:
```
julia> try
       throw("foo")
       end

julia> 
Program received signal SIGINT, Interrupt.
0x00007ffff76fb20b in raise (sig=2) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
37	in ../nptl/sysdeps/unix/sysv/linux/pt-raise.c
(gdb) p jl_(jl_exception_occurred())
"foo"
$5 = void
(gdb) 
```

**Comment by twadleigh** [comment]
@ihnorton, of course, that begs the question, then: how does one determine when an unhandled exception has occurred?

I suppose I might have to wrap my call to `julia_init` in `JL_TRY/JL_CATCH`...

**Comment by twadleigh** [comment]
I worked through a variety of initialization issues. In short, user error.
