### ISSUE TITLE
Multiple dispatch for (private) methods of a class

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#13280]
What do you think about having ability to overload (private) methods **within** a class?

To elaborate on what I mean, let me give a concrete example.
Suppose I have a following definition of a class:

    type Sometype
        prop::String

        setValue::Function
 
        # constructor
        function Sometype()
            this = new ()
     
            this.prop = ""

    ####### v1 #######
            this.setValue = function(v::Real)
                println("Scalar Version was Invoked!")
                # operations on scalar...
                # ...
            end

    ####### v2 #######
            this.setValue = function(v::Vector{Real})
                println("Vector Version was Invoked!")
                # operations on vector...
                # ...
            end

    ####### v3 #######
            this.setValue = function(v::Matrix{Real})
                println("Matrix Version was Invoked!")
                # operations on Matrix...
                # ...
            end
        end
    end

So when I say in my main code:

    st = Sometype()
    st.setValue(val)

depending on whether `val` is a **scalar**, **vector** or **matrix** it would invoke the corresponding version of a `setvalue` method. Right now, I believe, with definition above, it overrides definitions of `setvalue` with the last one (matrix version in this case).

**Comment by johnmyleswhite** [comment]
As far as I understand your proposal (which is not very well), I think you're a little confused about how generic functions and methods work. In particular, you seem to believe that types act like modules and allow scoping of generic functions -- which I believe is not true.

**Comment by quinnj** [comment]
Yes, typically types don't need to have field members of `Function` since functions are generic and are dispatched by type. It's also unclear from your example where exactly `this.data` is coming from or if that's some kind of additional field you're trying to set from within the constructor.

**Comment by simonster** [comment]
You can do this if you want:

```julia
type Sometype
    prop::String

    setValue::Function

    # constructor
    function Sometype()
        this = new ()

        this.prop = ""

####### v1 #######
        function setValue(v::Real)
            println("Scalar Version was Invoked!")
            # operations on scalar...
            # ...
        end

####### v2 #######
        function setValue(v::Vector{Real})
            println("Vector Version was Invoked!")
            # operations on vector...
            # ...
        end

####### v3 #######
        function setValue(v::Matrix{Real})
            println("Matrix Version was Invoked!")
            # operations on Matrix...
            # ...
        end

        this.setValue = setValue
        this
    end
end
```

However, as others have already said, you shouldn't. Your code will be slow and unhappy. The Julian thing to do would be to define `setValue(x::Sometype, y)` outside of the type definition.

Also, you almost never want `Vector{Real}`; see the [parametric types](http://julia.readthedocs.org/en/latest/manual/types/#man-parametric-types) section of the manual.

**Comment by AzamatB** [comment]
@quinnj sorry, updated the `this.data` part.

@simonster "Even though Float64 <: Real we DO NOT have Point{Float64} <: Point{Real}" - is this the reason to avoid Vector{Real} annotation?

Thanks a lot for this clarification! Very helpful!

**Comment by timholy** [comment]
See the FAQ: http://docs.julialang.org/en/latest/manual/faq/#how-do-abstract-or-ambiguous-fields-in-types-interact-with-the-compiler
