### ISSUE TITLE
libblosc compile error on ARM 

### ISSUE THREAD

**Issue by bernizt** [JuliaLang/julia#13298]
I have tried to install the *MAT* package but unfortunately it failed due to an error when compiling one of its dependencies, *Blosc*. It looks like the make command is not using the proper arm flags and instead using the x86.
I am not aware if this is something that happens with all libraries that Julia attempts to compile when installing a package (no ARM-specific make commands exist) or something that only happens with *libblosc*. *Blosc* recently received [official ARM support](http://www.blosc.org/blog/arm-is-becoming-a-first-class-citizen-for-blosc.html) so compiling it in ARM should not be a problem.

**Julia version:** 0.4.0-dev+6443 / Commit f0328c8* / arm-linux-gnueabihf

**Julia output:**
```
Compiling libblosc...
gcc -I. -DSHUFFLE_SSE2_ENABLED -DBLOSC_SHARED_LIBRARY -fPIC -O3 -pthread -msse2 -c -o bitshuffle-sse2.o bitshuffle-sse2.c
gcc: error: unrecognized command line option ‘-msse2’
../../make.blosc:38: recipe for target 'bitshuffle-sse2.o' failed
make: *** [bitshuffle-sse2.o] Error 1
==============================================================[ ERROR: Blosc ]===============================================================

LoadError: failed process: Process(`make -f ../../make.blosc HAVE_AVX=0 LIB=../../libblosc.so`, ProcessExited(2)) [2]
while loading /root/.julia/v0.4/Blosc/deps/build.jl, in expression starting on line 21
```

**Comment by nalimilan** [comment]
AFAICT this happens when building the Blosc.jl package. Please file an issue on the bug tracker for that project.

That said, the mentions of SSE2 are quite suspicious for an ARM build. No wonder why it fails... I think you should try building libblosc separately from sources, without any special variable set, and see whether it gives the same error.

**Comment by bernizt** [comment]
I have just [filed the issue](https://github.com/stevengj/Blosc.jl/issues/13) on their bug tracker, thank you.
