### ISSUE TITLE
Julia hangs on PyObject to Vector{Sym} conversion

### ISSUE THREAD

**Issue by torerudis** [JuliaLang/julia#13296]
Hi! 
Thank you for a very capable and very promising language.
I am using Julia v 0.3.10 with Juno. I am trying to extract the symbols present in a SymPy symbolic expression, but the program hangs on me.

The following lines execute without error:
```
Pkg.add("SymPy")                  # (Ok)
using SymPy                       # (Ok)
x, y, z = Sym("x", "y", "z")      #   x,y,z) 
ex = x + 2y + 10z                 #  x + 2*y + 10z)
symb = free_symbols(ex)           #  PyObject set([x, y, z])
vekt = convert(Vector{Sym}, symb) # Vector Sym,3
```
The following hangs the program, the "working" icon in the lower left shows up and never disappears.
vekt[1]

**Comment by KristofferC** [comment]
It segfaults for me. Not sure this is a julia issue though. Probably, Sympy or maybe PyCall.

**Comment by jverzani** [comment]
True, this is SymPy or PyCall. I'll investigate the SymPy angle to see if there is something to be done there.

**Comment by jverzani** [comment]
Okay, try 

```
veckt = colect(symb)
```

This gives an Any array which can be coerced as you want.

**Comment by stevengj** [comment]
The original poster's code works for me with the latest (`master`) version of SymPy with Julia 0.5, so I assume this has been fixed.

**Comment by stevengj** [comment]
Closing as probably not a Julia issue per se.
