### ISSUE TITLE
Profiler can deadlock on OS X

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13294]
If we happen to stop a thread while it is trying to register a dynamic fde, the profiler thread will dead lock trying to acquire a lock held by the blocked thread.

**Comment by vtjnash** [comment]
I started some work to address this on my threading branch

**Comment by Keno** [comment]
Can we move that work onto master?

**Comment by yuyichao** [comment]
@vtjnash Is this fixed? (Or is this still not due to one of your todo's in `signals-mach.c`?)

**Comment by vtjnash** [comment]
no, i think keno wanted us to add a guard around calls to `__register_frame` that stops us from trying to compute a backtrace then
