### ISSUE TITLE
Windows command-line installer woes

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13304]
I am trying to follow the instructions given as resolution of #13300. This failed:
```
$ make binary-dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-09f248f0f1
Makefile:407: *** prefix must not be set for make binary-dist.  Stop.
```

After disabling `Make.user`, two files are generated, one of them an `exe` file. (Why doesn't the makefile output the name of the "generated installer"?) However:
```
ls -ltr
[...]
-rwxr-xr-x  1 PI+User(18598) PI+Group(513) 40728323 Sep 24 12:40 julia-install-09f248f0f1-x86_64.7z
-rw-r--r--  1 PI+User(18598) PI+Group(513) 40910178 Sep 24 12:40 julia-0.4.0-rc2-x86_64.exe
$ ./julia-0.4.0-rc2-x86_64.exe
-bash: ./julia-0.4.0-rc2-x86_64.exe: Permission denied
```
I needed to manually run `chmod a+x` on it.

Afterwards I was able to start the installer. As I was logged in via ssh (not a typical Windows setup, I assume), nothing happened. I needed to log in to the Windows desktop and run the installer from a Cygwin window there. Finding my Cygwin home directory in the Windows install dialogue required some trial and error (I'm not too familiar with Cygwin), but I managed to install Julia into `~/julia` as intended.

Assuming I'm working from the command line, is there an easier way to achieve this, circumventing the binary installer? Is the Windows installer e.g. a thin shell around `cp -a`, or does it perform additional steps? I tried using `7z x` on the generated `*.7z` file, but this only generated an `exe` file for an installer instead of unpacking a Julia tree.

**Comment by tkelman** [comment]
The command line installer isn't the only way to get this working, but it's the fewest steps, best tested and least error prone. You can also manually move files around from diat-extras into the appropriate structure, but the binary-dist installer generation makefile rule is the canonical reference on that. This is all due for a refactoring after libgit2. You can unpack the installer exe with 7z.

**Comment by ihnorton** [comment]
> this only generated an exe file for an installer instead of unpacking a Julia tree.

I haven't tried this recently, but it was possible to extract the directory (with a slightly odd name) by running 7z twice, see: https://github.com/JuliaLang/julia/issues/10126#issuecomment-74811316

**Comment by ihnorton** [comment]
Actually, you can do a silent install with the current self-extracting binary:

`julia-0.5.0-da085b479c-win64 /S /D=C:\juliatest`

Two caveats:
- this launches a GUI process and returns to `cmd` immediately. I'm not sure how to wait on completion, but `Uninstaller.exe` should be the last thing written, so could wait for that.
- as far as I can tell, the `/D=` parameter *must* be a full path (or I may have a bunch of copies in temp dirs...)

**Comment by ihnorton** [comment]
Reopen if needed.
