### ISSUE TITLE
Load from GC frame preventing vectorization

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#13301]
The following code (`T = Float32`) fails to vectorize on the current master (but vectorizes on 0.4-release)

```jl
function test_scale2{T}(nele, factor::T)
    ary1 = Vector{T}(nele)
    @inbounds @simd for i in 1:nele
        v = ary1[i] + factor
        ary1[i] = v
    end
end
```

The function vectorize successfully if the allocation of the array is moved out of the function.

According to [`code_llvm_raw`](https://github.com/yuyichao/explore/blob/06e6b364a06dd5658f4394f65e25b2303e5831fa/julia/simd_complex/test2-master.ll). There is [a load in the loop](https://github.com/yuyichao/explore/blob/06e6b364a06dd5658f4394f65e25b2303e5831fa/julia/simd_complex/test2-master.ll#L73) that doesn't have a tbaa node attached.

AFAICT, that line is the load of the array from the GC frame. So,

1. We can probably have a tbaa node for the gc frame, which should help this case and probably improve other stuff in general.

2. Do we really ever want to load from the GC frame? They are leaked immediately to the global state so LLVM would never be able to optimize them out but they won't actually be changed by anything not in the current function.

@vtjnash @simonster

**Comment by simonster** [comment]
Conceivably we could bracket stores to the GC frame in `llvm.invariant.end`/`llvm.invariant.start` to tell LLVM that nothing else will ever modify it, even other functions. Not sure if LLVM will really use these though.

**Comment by yuyichao** [comment]
Will that work if we have multiple stores to it? (Allocation in a loop or reuse of slots)

**Comment by simonster** [comment]
I think so. The idea is to tell LLVM that the GC frame stops being invariant before a store and starts being invariant again afterwards. But as I noted in https://github.com/JuliaLang/julia/pull/8867#issuecomment-66361239 it's not clear if LLVM can actually make use of this metadata...

**Comment by JeffBezanson** [comment]
I see vector instructions in this example now. Fixed?
