### ISSUE TITLE
Tuple unpacking after catch: parser issue ?

### ISSUE THREAD

**Issue by bermanmaxim** [JuliaLang/julia#13302]
I have hit the following problem:

```
julia> t = (1,2)
(1,2)

julia> try
           a
       catch
           b, c = t
       end
ERROR: syntax: unexpected ,
```
Adding a semicolon `catch;`  doesn't help; however, catching the exception with `catch y`, or adding parenthesis to the left-hand side of the assignment `(b, c) = t`, works as expected.

For reference:
```
julia> versioninfo()
Julia Version 0.4.0-pre+7105
Commit 349a4e1* (2015-08-30 15:16 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by JeffBezanson** [comment]
Thanks; amazing this has not been caught before. I am filled with shame.

**Comment by StefanKarpinski** [comment]
![i am ashamed finding nemo](https://cloud.githubusercontent.com/assets/153596/10083744/cf8dc32c-62cd-11e5-8253-ab7aa5b03ccb.gif)

**Comment by tkelman** [comment]
backport?

**Comment by JeffBezanson** [comment]
Yes that should be fine.

**Comment by bermanmaxim** [comment]
Glad I could help ;)
