### ISSUE TITLE
Finer granularity in timing macros

### ISSUE THREAD

**Issue by kpamnany** [JuliaLang/julia#13303]
Currently `@time` and friends tell you the total time an expression took to run, and usefully add GC time as a percentage of that time. E.g.:

```
julia> @time foo()
  0.246500 seconds (10.00 M allocations: 152.588 MB, 2.86% gc time)
```

It would be useful to have more detailed profiling information in this macro (or a variant) that additionally separates out other runtime overheads (both one-time and constant) such as compilation time, type inferencing time, etc.

**Comment by tkelman** [comment]
There is a `@timev` that could be expanded on

**Comment by mlubin** [comment]
How easy would it be to also print out a flag to indicate if any JIT compilation took place or not? That could help a lot with the intro issues

**Comment by mbauman** [comment]
Compilation time is now included:

```
julia> x = rand(10,10);

julia> @time x*x
  0.716066 seconds (2.38 M allocations: 128.275 MiB, 3.00% gc time, 99.78% compilation time)
```

Since this issue was created, we also now have far more robust benchmarking and profiling tools (this issue predates BenchmarkTools!)
