### ISSUE TITLE
ImageMagick + Libc.FILE segfault

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#13318]
```Julia
const libwand = "C:\\Program Files\\ImageMagick-6.8.9-Q16\\CORE_RL_wand_.DLL"
io = open("test.png", "r+")
wand = ccall((:NewMagickWand, libwand), Ptr{Void}, ())
ccall((:MagickReadImageFile, libwand), Cint, (Ptr{Void}, Ptr{Void}), wand, Libc.FILE(io).ptr)
```
Tried with Version `0.4.0-pre+7133` and `RC2`.
Seems to be restricted to win 64, but should be reproducable there (also on travis).
Works fine on linux (travis).
On OSX is some other segfault, which I can't reproduce without OSX.

Docs from: http://www.imagemagick.org/api/magick-image.php
```
MagickReadImageFile
MagickReadImageFile() reads an image or image sequence from an open file descriptor.

The format of the MagickReadImageFile method is:

MagickBooleanType MagickReadImageFile(MagickWand *wand,FILE *file)
```
At some point it said this:
```
A s s e r t i o n   f a i l e d !

 P r o g r a m :   C : \ U s e r s \ S i m \ A p p D a t a \ L o c a l \ J u l i a - 0 . 4 . 0 - r c 2 \ b i n \ j u l i a - d e b u g . e x e
 F i l e :   d u m p . c ,   L i n e   1 1 1 6

 E x p r e s s i o n :   m o d e   ! =   M O D E _ M O D U L E _ P O S T W O R K
```
This doesn't happen for the minimal example though.
There it just silently fails, even with `gdb` and `julia-debug`. It says:
```
(gdb) bt
No stack.
```

Any ideas?

Best,
Simon

**Comment by lucasb-eyer** [comment]
You need to call `MagickWandGenesis` first so IM can initialize its globals and libraries. See [example](http://www.imagemagick.org/script/magick-wand.php).

**Comment by SimonDanisch** [comment]
Thanks, I only found an example where that call was missing!
Continue discussion at ImageMagick.
