### ISSUE TITLE
Number of indices in eachindex(A,B) depends upon types of A & B

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#13310]
This is a little strange:

``` jl
julia> length(eachindex(rand(2,2), rand(6,1)))
6

julia> length(eachindex(rand(2,2), sprand(6,1,1.)))
12
```

We could potentially just use `zip(eachindex(A), eachindex(B))`, but unfortunately that incurs a ~40% overhead.  And always using Cartesian indexing can be even worse.  ([benchmarks](https://gist.github.com/mbauman/e8cf3378b1f782b47cf9))

Here's what the documentation currently says: _"If the arrays have different sizes and/or dimensionalities, eachindex returns an iterable that spans the largest range along each dimension."_

Do we want to change `eachindex` for combinations of `LinearFast` arrays to always iterate such that they'd iterate from `1:12` in the above example (the product of the maximum of all dimensions)?  That's a little strange, too — `eachindex(rand(2,2), rand(4,1))` would ~~work as indices for both arrays, but not if one changes to LinearSlow~~ error in at a slightly different place if one changes to LinearSlow.  Or do we just live with the status quo?

cc @timholy

**Comment by timholy** [comment]
Definitely can't live with the status quo.

But this is a nasty consequence of "linear thinking," and embarrassing we didn't discover it earlier. If we want to keep the current design (which supports broadcasting and reduction), perhaps `eachindex(A, B)` should always return a Cartesian index. Conceptually, it could return a linear index when the shapes of `A` and `B` are the same, but that would make it type-unstable.

**Comment by mbauman** [comment]
Is the current extend-to-largest-dimension semantic useful?  Use of multi-arg `eachindex` is pretty limited right now (https://github.com/JuliaLang/julia/compare/JuliaLang:master...mbauman:mb/zipeachindex), mostly used in cases where we've already checked `size` or used `promote_shape`.  We could easily error on mismatched sizes (potentially ignoring trailing ones, like `promote_shape` does, but that's a whole 'nother).

**Comment by timholy** [comment]
Yeah, we could error. However, it's nice for code like this:

```jl
A = rand(3,5,7)
Aaccum = zeros(3,1,7)

Imask = CartesianIndex(size(Aaccum))
for I in eachindex(A, Aaccum)
    Aaccum[min(Imask, I)] += A[I]
end
```
i,e, efficient reduction along arbitrary combinations of dimensions in 4 lines of code.

**Comment by timholy** [comment]
But of course in this case we presumably know `A` is bigger. I probably should have given the corresponding broadcasting example instead. However, you can do it manually by taking `max` on the sizes first. So maybe it's just less surprising to throw an error.

**Comment by mbauman** [comment]
But in both cases `eachindex(A,B)` needs to return Cartesian indices for those operations to work.  

There are some really powerful features tucked away here.  It'd be nice to expose them more (https://github.com/JuliaLang/julia/issues/10906)… I had seen you do that trick before and was amazed, and then totally forgot about it again.  

We've also since extended eachindex to just about every indexable collection.  I suppose it's ok if multi-arg eachindex is limited to AbstractArrays… but it gives me pause, too.

**Comment by nalimilan** [comment]
As noted on #24486, I think it would be better to raise an error when the inputs are of different sizes. Broadcasting indices (#10906) is an interesting idea, but at least when broadcasting is not possible we shouldn't silently extend indices to the largest of the arguments: it's going to trap many people, which can introduce nasty bugs (as happened in StatsBase).

**Comment by StefanKarpinski** [comment]
It seems like something should definitely be done about this. We're trying to understand the top example and the current behavior certainly seems bizarre and bad. @mbauman, do you think you can fix this for 1.0?

**Comment by JeffBezanson** [comment]
I'd be ok with allowing this only if the dimensions are broadcast-compatible, and I'm also ok with giving `CartesianIndex`es.

**Comment by mbauman** [comment]
The key question is what kinds of behaviors @timholy would like to preserve here.  I'd favor throwing an error, in which case this is a simple fix.

**Comment by timholy** [comment]
Error seems fine with me.

**Comment by alexmorley** [comment]
Would you want to make sure the sizes match or just the lengths?
i.e. should this give an error or not (I would have thought not)
`eachindex([1 1], [1; 1])`
