### ISSUE TITLE
--depwarn has no effect in Julia version 0.4-rc2

### ISSUE THREAD

**Issue by r5r3** [JuliaLang/julia#13314]
Using `--depwarn=no` should suppress Warnings about deprecated features, but it don't seems to work in Julia 0.4-rc2:
`julia --depwarn=no --eval 'x=String[]'`
`WARNING: Base.String is deprecated, use AbstractString instead.`

**Comment by tkelman** [comment]
Yep. This was fixed on master by #13269 and will get backported to release-0.4 when #13289 gets merged, prior to rc3.
