### ISSUE TITLE
Pkg.update() and other package updates on windows

### ISSUE THREAD

**Issue by jackChester** [JuliaLang/julia#13319]
I recently installed the 64 bit Windows version of Julia. The program works fine (I've used it before) but I cannot do anything with the packages, i.e. add new packages, update, etc. The attached image shows the problem. I also uninstalled and re-installed Julia to try to resolve this, but without luck. I genuinely appreciate any help.
(I am an economist, not a computer scientist, so strongly appreciate the reply to be as explicit as possible as to how to resolve.)
![julia_error](https://cloud.githubusercontent.com/assets/14843598/10112842/4d95bb68-63a4-11e5-822e-a3882860d045.png)

**Comment by mmoh** [comment]
Did you first try: `Pkg.add("StatsBase") ` ?

**Comment by jackChester** [comment]
Yes, I did, as shown in the image below. Also, I ran Pkg.status() if this helps anyone.
![julia_error_v2](https://cloud.githubusercontent.com/assets/14843598/10113147/316a5d88-63a7-11e5-8cb9-d5a790dbbd30.png)

**Comment by pao** [comment]
> I also uninstalled and re-installed Julia to try to resolve this, but without luck.

That won't remove packages or your local package requirements; they're stored separately, in a `.julia` folder under your user folder.

**Comment by tkelman** [comment]
You very suspiciously don't have any packages installed that start with anything later in the alphabet than M. Did you possibly abort the initial download of Metadata? Try deleting or moving your `.julia` folder (you can get the location of this via `Pkg.dir()`) out of the way and re-running Pkg.init.

**Comment by jackChester** [comment]
Ok, I very appreciate the comments and am trying this now. Regarding the aborting of the initial download, I have been wondering the same thing. Am trying to locate the .julia folder and will update shortly.

**Comment by jackChester** [comment]
The problem is fixed. (The .julia folder was hiding on a network drive, but your suggestion to use Pkg.dir() fixed this.)

Sincere thanks for the help. I will continue to promote Julia among the economists and graduate students at Harvard and Chicago.
