### ISSUE TITLE
Dict doesn't take `=>`

### ISSUE THREAD

**Issue by sheim** [JuliaLang/julia#13311]
I just got Julia, running version 0.3.11 installed via homebrew on OS X 10.10.5
Dicts (at least the way they are described in all the tutorials etc. I've found) don't seem to be working:

    julia> mydict = Dict("a"=>1, "b"=>2, "c"=>3)
    ERROR: unsupported or misplaced expression =>

Tried both in the terminal and in Juno. This seems to not be an isolated case (see [here](https://github.com/floswald/MOpt.jl/issues/4)), but I can find any actual answers to it either. [Other](https://github.com/JuliaLang/julia/issues/8051) issues that could be related, but they aren't talking about Dict, so I'm not sure...

Cheers

**Comment by yuyichao** [comment]
This is the new dict syntax / constructor in 0.4. You can use it on 0.3 with [Compat.jl](https://github.com/JuliaLang/Compat.jl#supported-syntax)
