### ISSUE TITLE
Run `doc/genstdlib.jl` on release branch?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13316]
When I run `doc/genstdlib.jl` on the 0.4 branch, a difference is generated. That's a small difference only -- white space on two lines -- but it makes me wonder where this comes from.

```
$ git diff
diff --git a/doc/stdlib/base.rst b/doc/stdlib/base.rst
index 931f92c..89e9e7c 100644
--- a/doc/stdlib/base.rst
+++ b/doc/stdlib/base.rst
@@ -630,8 +630,8 @@ Generic Functions
 
    .. doctest::
 
-       julia> method_exists(length, Tuple{Array})
-       true
+      julia> method_exists(length, Tuple{Array})
+      true
 
 .. function:: applicable(f, args...) -> Bool
 
```

**Comment by tkelman** [comment]
I didn't backport 4a55d382798038fb353b56c1cb847a1282ddbdd9 yet but it's in my latest backport pr. I removed some tabs from helpdb and didn't rerun genstdlib yet. #13162 would make this more immediately visible.
