### ISSUE TITLE
libjulia.dll.a no longer generated

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#13337]
A consequence of the new out-of-tree-bulids?

**Comment by twadleigh** [comment]
While we're at it, can we change the extension to from `.dll.a` to `.lib`? Otherwise, for instance, the `-ljulia` option doesn't work for MATLAB's `mex`.

**Comment by tkelman** [comment]
.lib would make it look like a full static libraray, where it's just an import lib. The convention is to use .dll.a for these with mingw. Can you add the entire .dll.a file name to the link line?

**Comment by twadleigh** [comment]
When I tried yesterday it didn't work. I'll try again today. Worst case, I'll copy the libs.

**Comment by ihnorton** [comment]
Seems ok based on edit? Please comment/reopen if needed.

**Comment by tkelman** [comment]
My understanding is the file's generated on release-0.4 but the extension wasn't originally working until spelled out in full, but the out-of-tree build PR (or maybe something else) broke the generation of it on master.

**Comment by twadleigh** [comment]
@ihnorton: @tkelman is correct. The edit relates to the renaming sidebar. The core issue remains: the `*.dll.a` are no longer being generated on master. This breaks, for instance, Julia embedding on windows with MSVC (as I use, for instance, in my MATLAB MEX embedding of Julia).

Please reopen.

**Comment by twadleigh** [comment]
:smile:
