### ISSUE TITLE
checkbounds return value

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#13334]
I was a bit surprised to notice that the function `checkbounds(A::AbstractArray{T,N}, I...)` returns `true` if it does not throw a `BoundsError`.

```
julia> checkbounds(1:3, 4)
ERROR: BoundsError: attempt to access 1:3
  at index [4]

julia> checkbounds(1:3, 3)
true
```

I would have expected it to return `nothing`, especially since the documentation makes no mention of return value:

> Throw an error if the specified indexes are not in bounds for the given array. Subtypes of `AbstractArray` should specialize this method if they need to provide custom bounds checking behaviors.

Note that there *is* another version of `checkbounds` that is explicitly asked to return a `Bool`:

```
julia> checkbounds(Bool, 3, 4)
false

julia> checkbounds(Bool, 3, 3)
true
```

Two possible solutions:

1. change `checkbounds(A::AbstractArray{T,N}, I...)` to return `nothing` if it does not throw an error.  This will involve going through existing packages to make sure nobody is relying on the current behavior.
2. decide that returning `true` is actually no accident, and modify the documentation to mention the return value.  If this decision is taken, it's especially important to make this explicit in the documentation, as subtypes of `AbstractArray` will want to also have their `checkbounds` return `true` to be consistent with the original interface (otherwise there can be subtle breakage).

My vote is for the first option, as returning `true` is redundant if no error is thrown.

**Comment by kshyatt** [comment]
Is this still a problem? What would we like to do?

**Comment by timholy** [comment]
:+1: on your proposal. I'm going to strip out the "decision" tag here, and mark "up for grabs."

**Comment by H-225** [comment]
This appears to have been fixed. (Checked on commit 6a1483b31d808acf90828613c793025054300101.)

```julia
julia> checkbounds(1:3, 4)
ERROR: BoundsError: attempt to access 3-element UnitRange{Int64} at index [4]
 in throw_boundserror(::UnitRange{Int64}, ::Tuple{Int64}) at .\abstractarray.jl:326
 in checkbounds(::UnitRange{Int64}, ::Int64) at .\abstractarray.jl:283

julia> checkbounds(1:3, 3)

julia>
```

**Comment by mbauman** [comment]
Yup.  Fixed by the revamp in https://github.com/JuliaLang/julia/pull/17355.
