### ISSUE TITLE
Errors when compiling with LLVM_VER=svn

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#13344]
I'd mentioned this before: https://github.com/JuliaLang/julia/pull/13150#issuecomment-141208689.

The line in `disasm.cpp (316)` uses a function 'InitMCObjectFileInfo' which has been deprecated.

The line in `debuginfo.cpp (229)` was added by @vtjnash  in https://github.com/JuliaLang/julia/commit/8cea71e92ae765872c86c4c5caf1784d12f2eda6
It looks like it is simply that with the new 3.8 LLVM, that variable is defined but never used.

The line in `debuginfo.cpp (969)` was added by @Keno in https://github.com/JuliaLang/julia/commit/47f697b963d3bcd586ee1292ff439a715ad1c951
says that it overrides a member function from: `usr/include/llvm/ExecutionEngine/RTDylMemoryManager.h`

**Comment by vtjnash** [comment]
llvm-svn is not a supported build configuration. PR's are of course accepted, but issues and pings, as a policy, have been closed immediately.

**Comment by ScottPJones** [comment]
OK - I just wanted to make sure that the involved parties were aware of this problem, which shows up if you are trying to use @keno's Cxx and/or Gallium packages (which hopefully will make it into 0.5 fully supported in normal builds)

**Comment by ScottPJones** [comment]
@vtjnash, where is that policy written down?  It doesn't seem to have been applied in the past, or currently, AFAICT. There are a large number of issues currently open about building with svn, and many more that have been closed (mostly from Keno, and some that you have commented on yourself, without saying a word about it being not supported and closing them immediately.
Arbitrarily closing a bug report like this is not appreciated.

**Comment by vtjnash** [comment]
the supported build configuration is what you get with `git pull`. modifications to Make.user are not officially supported, although they exist because some dev needed them, such as to test building for a future llvm release version.

i've closed a handful of issues for llvm-svn build questions, but I don't maintain records of old build numbers. they also probably don't get tagged, so github doesn't do a great job at finding them. The open llvm-svn issues deal with bugs in Julia, not the build.

**Comment by ScottPJones** [comment]
Well, these are pointing out some real issues in Julia - just like other things reported where changes to the API require modifications to the Julia source code, such as dealing with deprecated code, or having to add an override.
