### ISSUE TITLE
Performance of accessing array

### ISSUE THREAD

**Issue by eldadHaber** [JuliaLang/julia#13347]
The following code gives the results

```
A = randn(1000,1000);
@time for i=1:1000;for j=1:1000; A[i,j]+=1.0; end; end
elapsed time: 0.122188212 seconds (105 MB allocated, 4.93% gc time in 4 pauses with 0 full sweep)
```

I was wondering why does so much memory is allocated for this?
Just for comparison

```
@time A = A+1.0;
elapsed time: 0.003335568 seconds (7 MB allocated, 43.04% gc time in 0 pauses with 0 full sweep)
```

[pao: quoting]

**Comment by pao** [comment]
This is an excellent question for the julia-users mailing list, at https://groups.google.com/forum/#!forum/julia-users. Please feel free to ask questions there! Thanks for using Julia!

**Comment by ScottPJones** [comment]
One performance issue here is that the code is accessing things in row-major order, but Julia prefers column-major order.

**Comment by StefanKarpinski** [comment]
As @pao already said, this is an inappropriate place for this conversation.

**Comment by RauliRuohonen** [comment]
This looks more like a gently worded bug report than a question to me, so I think this needs to be said:

It's not a bug and doing as the docs suggest (in "Performance Tips") results in no allocation:

    function f(A)
      for i=1:1000;for j=1:1000; A[i,j]+=1.0; end; end
    end

    A = randn(1000,1000)
    @time f(A) # warmup
    @time f(A) # real timing
    @time 1 # for comparison (@time does a few allocations)

0.017981 seconds (4.19 k allocations: 211.591 KB)
0.010101 seconds (4 allocations: 160 bytes)
0.000001 seconds (4 allocations: 160 bytes)

So the result is fine and the behavior documented => not a bug.
