### ISSUE TITLE
`Cmds` constructor should accept `Vector{T<:ByteString}` as argument

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13369]
When constructing commands from a variable number of strings, the backticks syntax doesn't work, and one has to explicitly call the `Cmds` constructor with an array of strings as argument. This is slightly inconvenient as the constructor requires a `Vector{ByteString}` as argument, while the "naturally" constructed arrays have e.g. type `Vector{ASCIIString}`. This requires an explicit conversion to `Vector{ByteString}`, which is no problem, but less convenient than necessary.

I suggest to add an outer constructor that accepts `Vector{T<:ByteString}` or even `Vector{T<:AbstractString}`.

**Comment by vtjnash** [comment]
does ``` cmd `$([vector])` ``` work?

**Comment by StefanKarpinski** [comment]
Should probably accept any vector of strings.

**Comment by eschnett** [comment]
@vtjnash Yes, interpolating the array in backticks works. Thanks for the pointer.

**Comment by KristofferC** [comment]
I think this is fine with the removal of all the string types.

**Comment by timholy** [comment]
@KristofferC seems to have found a way to squeeze about 96 hours of work into the last 24, how does he do it?

**Comment by martinholters** [comment]
Fika?

**Comment by KristofferC** [comment]
:D
