### ISSUE TITLE
round (and trunc, floor, ceil) not defined from `Float64` or `Float32` to `BigInt`

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#13367]
I didn't see this reported elsewhere, so:

```
julia-0.4> round(BigInt, 2.5)
ERROR: MethodError: `trunc` has no method matching trunc(::Type{BigInt}, ::Float64)
Closest candidates are:
  trunc{T<:Integer}(::Type{T<:Integer}, ::Integer)
  trunc(::Type{Signed}, ::Float64)
  trunc(::Type{Unsigned}, ::Float64)
  ...
 in round at float.jl:177
```

There are definitions going from `BigFloat` to `BigInt`. Maybe we could use those, if implementing a direct route is unfeasible.

```
julia-0.4> round(BigInt, big"2.5")
2
```

**Comment by simonbyrne** [comment]
Ha. I spent a lot of effort getting things [correct the other way](https://github.com/JuliaLang/julia/commit/930f875c9229e92b88f9a7c922f0a7a35cb33163), but it didn't occur to me that we missed these. 

It should be possible to do this directly using `mpz_set_d` without going via `BigFloat`s.
