### ISSUE TITLE
Conflicting declaration of localtime_r between ctime and julia.h on mingw64-x86_64

### ISSUE THREAD

**Issue by oroppas** [JuliaLang/julia#13360]
In file included from `src/codegen.cpp:95:0`:

```
src/julia.h:1502:64: error: conflicting declaration of 'tm* localtime_r(const time_t*, tm*)' with 'C' linkage
 DLLEXPORT struct tm* localtime_r(const time_t *t, struct tm *tm);
                                                                ^
In file included from C:/msys64/mingw64/include/c++/5.2.0/ctime:42:0,
                 from C:/msys64/mingw64/include/llvm/Support/FileSystem.h:36,
                 from C:/msys64/mingw64/include/llvm/Object/Binary.h:19,
                 from C:/msys64/mingw64/include/llvm/Object/SymbolicFile.h:17,
                 from C:/msys64/mingw64/include/llvm/Object/ObjectFile.h:18,
                 from C:/msys64/mingw64/include/llvm/DebugInfo/DIContext.h:20,
                 from C:/msys64/mingw64/include/llvm/ExecutionEngine/RuntimeDyld.h:21,
                 from C:/msys64/mingw64/include/llvm/ExecutionEngine/ExecutionEngine.h:18,
                 from C:/msys64/home/Engineer08/packages/julia/src/julia/src/codegen.cpp:21:
C:/msys64/mingw64/x86_64-w64-mingw32/include/time.h:269:34: note: previous declaration with 'C++' linkage
 __forceinline struct tm *__cdecl localtime_r(const time_t *_Time, struct tm *_Tm) {
                                  ^
```

In `julia.h`,
```
1501:#ifdef _OS_WINDOWS_
1502-DLLEXPORT struct tm* localtime_r(const time_t *t, struct tm *tm);
1503-#endif
```

Since `_OS_WINDOWS_` is 1 on mingw64, this definition collides with the definition from `time.h` which is included in `/mingw64/include/c++/x.x.x/ctime`.

By guarding the definition of `localtime_r`  using `_COMPILER_MINGW_`,
```
#ifdef _OS_WINDOWS_
#if !defined(_COMPILER_MINGW_)
DLLEXPORT struct tm* localtime_r(const time_t *t, struct tm *tm);
#endif
#endif
```

we can avoid the conflict.

**Comment by tkelman** [comment]
What version of LLVM are you trying to build with? We need `localtime_r` to be exported from a dll to use it in the [`TmStruct` constructor](https://github.com/JuliaLang/julia/blob/f71e449f8310ab0202f41ef73e893b6899c26ddd/base/libc.jl#L104). I suspect if you proposed that patch as a pull request, AppVeyor would show a failure in some of the Dates tests.

**Comment by tkelman** [comment]
On second thought I take that back, I don't think we need `localtime_r` to be declared in `julia.h` at all, as long as it's in `jl_uv.c`. It shouldn't be needed for embedding. I'll open a PR.

**Comment by oroppas** [comment]
Thanks. I confirmed I was able to compile and resume the build process.

**Comment by tkelman** [comment]
Just curious, are you building a package of julia against msys2's llvm? (and openblas etc?) I've been wondering if someone would attempt that, keep us posted how it goes.

**Comment by oroppas** [comment]
Yup. I'm building Julia against LLVM from mingw-w64 target under msys2. I
hit the another issue relevant to LLVM so I'll post it ASAP. I keep you
posted.

**Comment by tkelman** [comment]
Note that LLVM newer than 3.3 is not yet officially supported (ref #9336), so we'd prefer patches in the form of pull requests as opposed to issue reports there. But if there are build system issues for building against various other msys2 packages, would be good to know about those. I don't think we support using the dwarf version of the i686-w64-mingw32 toolchain for 32 bit, but maybe with a few patches we could - it's been a while since anyone last tried.

**Comment by oroppas** [comment]
I've managed to build up to the following point on msys2 for mingw-w64-x86_64.
It seems to be related to system libgmp naming convention on mingw-w64, 
  /mingw64/bin/libgmp-10.dll

make[1]: Entering directory '/home/Engineer08/packages/julia/src/julia'
    JULIA usr/lib/julia/sys.o
...
gmp.jl
error during bootstrap:
rec_backtrace_ctx at C:/msys64/home/Engineer08/packages/julia/src/julia/src\task.c:561
jl_throw at C:/msys64/home/Engineer08/packages/julia/src/julia/src\task.c:818
jl_rethrow_with_add at C:/msys64/home/Engineer08/packages/julia/src/julia/src\codegen.cpp:677
to_function at C:/msys64/home/Engineer08/packages/julia/src/julia/src\codegen.cpp:798
jl_compile at C:/msys64/home/Engineer08/packages/julia/src/julia/src\codegen.cpp:962
jl_trampoline_compile_function at C:/msys64/home/Engineer08/packages/julia/src/julia/src\builtins.c:1019
jl_apply_generic at C:/msys64/home/Engineer08/packages/julia/src/julia/src\gf.c:1711
do_call at C:/msys64/home/Engineer08/packages/julia/src/julia/src\interpreter.c:66
eval at C:/msys64/home/Engineer08/packages/julia/src/julia/src\interpreter.c:213
eval at C:/msys64/home/Engineer08/packages/julia/src/julia/src\interpreter.c:219
eval_body at C:/msys64/home/Engineer08/packages/julia/src/julia/src\interpreter.c:595
jl_toplevel_eval_body at C:/msys64/home/Engineer08/packages/julia/src/julia/src\interpreter.c:530
jl_toplevel_eval_flex at C:/msys64/home/Engineer08/packages/julia/src/julia/src\toplevel.c:521
jl_eval_module_expr at C:/msys64/home/Engineer08/packages/julia/src/julia/src\toplevel.c:167
jl_toplevel_eval_flex at C:/msys64/home/Engineer08/packages/julia/src/julia/src\toplevel.c:423
jl_toplevel_eval_flex at C:/msys64/home/Engineer08/packages/julia/src/julia/src\toplevel.c:573
jl_load_ at C:/msys64/home/Engineer08/packages/julia/src/julia/src\toplevel.c:626
unknown function (ip: 000000000751004f)
jl_apply_generic at C:/msys64/home/Engineer08/packages/julia/src/julia/src\gf.c:1686
unknown function (ip: 0000000013f60128)
LoadError(at "sysimg.jl" line 173: LoadError(at "gmp.jl" line 25: ErrorException("error compiling gmp_version: could not load library "libgmp"
The specified module could not be found.
")))

Here's the build script from PKGBUILD

 make -C julia prefix=/$MINGW_PREFIX sysconfdir=/$MINGW_PREFIX/etc \
    MARCH=${CARCH/_/-} \
    BUILD_OS=WINNT \
    USE_SYSTEM_LLVM=1 \
    USE_SYSTEM_LIBUNWIND=0 \
    USE_SYSTEM_READLINE=1 \
    USE_SYSTEM_PCRE=1 \
    USE_SYSTEM_LIBM=0 \
    USE_SYSTEM_OPENLIBM=0 \
    USE_SYSTEM_OPENSPECFUN=1 \
    USE_SYSTEM_DSFMT=0 \
    USE_SYSTEM_BLAS=1 \
    USE_SYSTEM_LAPACK=1 \
    USE_SYSTEM_FFTW=1 \
    USE_SYSTEM_GMP=1 \
    USE_SYSTEM_MPFR=1 \
    USE_SYSTEM_ARPACK=1 \
    USE_SYSTEM_SUITESPARSE=1 \
    USE_SYSTEM_ZLIB=1 \
    USE_SYSTEM_GRISU=0 \
    USE_SYSTEM_RMATH=0 \
    USE_SYSTEM_LIBUV=0 \
    USE_SYSTEM_LIBGIT2=1 \
    USE_SYSTEM_UTF8PROC=0 \
    USE_MKL=0 \
    USE_BLAS64=0 \
    USE_LLVM_SHLIB=0

**Comment by tkelman** [comment]
You'll have to patch base to change every instance of `:libgmp` to `"libgmp-10"`

We would probably accept a pull request that adds a central `const libgmp` variable so your patch only has to touch one line in the future. Could maybe add a `LIBGMP_NAME` makefile variable to make this more configurable at build time, for example if we ever want to try using MPIR in place of GMP.

**Comment by StefanKarpinski** [comment]
+1 to what @tkelman said. That seems like a reasonable way to go.
