### ISSUE TITLE
problems with reading from STDIN using eachline()

### ISSUE THREAD

**Issue by zionline** [JuliaLang/julia#13371]
in the past, it was possible to read and store in an array all input lines,
using the following command: lines = eachline(STDIN)

but now, I get 
EachLine(TTY(open, 0 bytes waiting),(anonymous function))

How can I make lines = eachline(STDIN)
to work again

**Comment by simonster** [comment]
`eachline` returns an iterator and to my knowledge it always has. To get an array you could use `readlines(STDIN)` or `collect(eachline(STDIN))`.
