### ISSUE TITLE
Local Pkg version tags should be reported for Pkg.installed()

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13375]
```julia
julia> Pkg.generate("FooBarBaz", "MIT")
INFO: Initializing FooBarBaz repo: /Users/jacobbolewski/.julia/v0.5/FooBarBaz
INFO: Origin: https://github.com/jakebolewski/FooBarBaz.jl.git
INFO: Generating LICENSE.md
INFO: Generating README.md
INFO: Generating src/FooBarBaz.jl
INFO: Generating test/runtests.jl
INFO: Generating REQUIRE
INFO: Generating .travis.yml
INFO: Generating appveyor.yml
INFO: Generating .gitignore
INFO: Committing FooBarBaz generated files

julia> Pkg.tag("FooBarBaz")
INFO: Tagging FooBarBaz v0.0.1

julia> Pkg.installed("FooBarBaz")
v"0.0.0-"
```

should report the latest tag `v0.0.1`, not `v0.0.0-`

**Comment by Keno** [comment]
This is a actually a pretty big problem, because Compose amongst others uses the version reported by `Pkg.installed` for Cairo support detection. cc @dcjones

**Comment by wildart** [comment]
This is because a package repository head positioned to commit with `master` reference rather then  associated with a tag.

**Comment by Keno** [comment]
Yes, which used to return the last tag with a `+` at the end.

**Comment by wildart** [comment]
I see. But 0.3.11 returns `-` as well.

**Comment by Keno** [comment]
Actual local example:
Before:
```
julia> Pkg.installed("Cairo")
v"0.2.30+"
```
Now:
```
julia> Pkg.installed("Cairo")
v"0.0.0-"
```
(same .julia just had an old build before the change).

**Comment by wildart** [comment]
What is a HEAD commit hash for your copy of this repository?

**Comment by wildart** [comment]
Fresh install reports:
```
julia> Pkg.installed("Cairo")
v"0.2.31"
```

**Comment by Keno** [comment]
```
kfischer$ git show HEAD
commit 8d340a7c3331a344c5d2dc419908a21fb79b7bb4
Merge: 1e6d7c3 42cce90
Author: Tim Holy <tim.holy@gmail.com>
Date:   Sat Sep 19 04:35:21 2015 -0500

    Merge pull request #120 from JuliaLang/yyc/0.4-binding

    Fix 0.4 deprecated bindings
```

**Comment by wildart** [comment]
This commit should be tagged as `v0.2.31`.

**Comment by Keno** [comment]
My Cairo is tracking master however.

**Comment by wildart** [comment]
Well, `master` is reported as `v0.0.0-`.

**Comment by Keno** [comment]
Yes, but it didn't use to be. That's the problem.

**Comment by wildart** [comment]
Found it, its an `Pkg.available` error.

**Comment by Keno** [comment]
Great!

**Comment by wildart** [comment]
I can explain example on top. Why no version for freshly generated package? It is not registered in METADATA, so it is not available. I can understand that, all versions need to be the same everywhere and METADATA keeps every location in sync. Thus, any local tags are not valid until they are published to METADATA.

@Keno your case is more suspicious. I blame METADATA corruption. Do you have any folder under `METADATA/Cairo/versions`?

**Comment by hayd** [comment]
It would be kind of neat to have the reported version of packages match that of julia i.e. `v0.X.Y+N`.
