### ISSUE TITLE
Pkg.tag is now extremely slow

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#13379]
After updating to the latest 0.5 with libgit2, `Pkg.tag` seems to be extremely slow; it took about 30 seconds.  Is it doing something different from before?

**Comment by wildart** [comment]
Which package did you tag?

**Comment by stevengj** [comment]
LaTeXStrings.  But I just tried tagging IJulia, and it took forever as well:
```
julia> @time Pkg.tag("IJulia")
INFO: Tagging IJulia v1.1.2
INFO: Committing METADATA for IJulia
 86.886114 seconds (2.28 M allocations: 142.839 MB, 0.04% gc time)
```

**Comment by stevengj** [comment]
(Seems like an awful lot of allocations: 143MB just to tag a package?)

**Comment by stevengj** [comment]
Thanks!
