### ISSUE TITLE
Pkg doesn't fully understand registered packages with no versions 

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13372]
Just rediscovered [this error](https://github.com/JuliaLang/METADATA.jl/pull/2064), that a registered package with no tagged versions works with `Pkg.clone` and `Pkg.build`, but few other operations work on it:

```jl
julia> Pkg.status("Elemental")

julia> Pkg.installed("Elemental")
ERROR: Elemental is not a package (not registered or installed)
julia> Pkg.available("Elemental")
ERROR: Elemental is not a package (not registered or installed)
julia> Pkg.clone("Elemental")
INFO: Cloning Elemental from git://github.com/JuliaParallel/Elemental.jl.git
INFO: Computing changes...
...
```

**Comment by jiahao** [comment]
There's clearly some logic in `Pkg` that implicitly assumes that all registered packages have at least one tagged version. One solution to this problem is to simply disallow registering a new package with no tagged versions - see https://github.com/JuliaLang/METADATA.jl/pull/2064

**Comment by wildart** [comment]
> solution to this problem is to simply disallow registering a new package with no tagged versions.

I agree.

**Comment by jakebolewski** [comment]
I can't reproduce this with the unregistered :sunglasses::clock1030:'s
