### ISSUE TITLE
libgit2 tests should not permanently alter system global git config

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#13377]
Running `make test-libgit2` results in the global git config getting overwritten with `Test User`, `Test@User.com`. This should be made temporary and local.

edit: apparently it only overrides the global gitconfig if it hasn't been set yet?

**Comment by wildart** [comment]
It happens only when `user.name` or `user.email` is empty. I recall that without these parameters set, `libgit2` calls will segfault.

**Comment by tkelman** [comment]
We should at least detect that situation and put it back to the way it was when we're done.

**Comment by vtjnash** [comment]
or change $HOME to a temporary location?

**Comment by wildart** [comment]
Fixed it in #13417
