### ISSUE TITLE
Developer documentation for calling conventions

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#13383]
I'd like to add a description of the various Julia calling conventions to `julia/doc/devdocs/`.  Below is my understanding.  Suggestions for improvements appreciated.

There are three calling conventions, which are labeled by their wrapper prefixes below:

 - **`julia_`** - Julia's "native" calling convention.  Has specialized signature.   Aggregates passed by reference; everything else by value.

- **`jlcall_`** - "JL call" convention. 
-- F - what's this?
-- array of pointers to boxes.
-- length of array
Used for builtins (see uses of macro JL_CALLABLE)  or and wrappers around `julia_` routines for use in generic dispatch. 

- **`jlcapi_`** - C ABI

**Comment by kshyatt** [comment]
Seems this was just never closed. I even commented on that old PR!
