### ISSUE TITLE
functionloc broken?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#13398]
(also on release-0.4 branch)
```julia
julia> @less(svd)
ERROR: type Array has no field defs
 in functionloc at reflection.jl:336
 in less at interactiveutil.jl:69
```

**Comment by ihnorton** [comment]
`functionloc` is fine. The problem is that `@less(svd)` -> `Base.less(:svd)` -> `which(::Symbol)`, returning the binding module rather than the method itself, so we end up with:
```
julia> m = methods(Base.LinAlg)
0-element Array{Any,1}
julia> m.defs
...
```

I don't think this ever would have worked the way you want it to here.

**Comment by ihnorton** [comment]
#13415
