### ISSUE TITLE
use explicit mmap/munmap on mac

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#1339]
I've noticed that Julia is quite a hungry lady.  :)

She seems to accumulate memory even when I wouldn't expect her to.  Calling `gc()` seems to help stopping julia from increasing her memory usage sometimes, but never does the memory usage decrease, it only ever increases.  This means that if my program had an extremely memory intensive startup phase and then a low memory requirement for the rest of its long lifespan, other processes would not be able to use the memory that is sitting in Julia's "free pool".  (Not sure if I have the implementation details right, but this is what I've been able to ascertain so far)

Is there a way to convince julia to give some of her "free pool" back to the OS?  I'm assuming that `gc()` finds orphaned memory segments and simply tags them as available to be used by further allocations in `julia`, and its not meant to actually free data back to the OS.

Test to reproduce: type `a = randn(10000,1000)` N times into a REPL, and watch the memory usage grow.  After a few times of that, type `gc()`, and then create more `a` matrices. For the first N times the memory usage of `julia` will not grow, but once you exhaust Julia's "free pool", it will begin to expand again.

**Comment by ihnorton** [comment]
Is this still an issue after all of the GC work and other improvements?

**Comment by vtjnash** [comment]
@carnaval am I correct in asserting that your new GC does this?

**Comment by quinnj** [comment]
Closing for now, please reopen if still an issue (@carnaval may have comments here).
