### ISSUE TITLE
Pkg.clone of unregistered package broken on master

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13390]
On a Ubuntu 14.04 machine with a fresh copy of Julia master installed and an existing `~/.julia/v0.5` setup, `Pkg.clone` of an unregistered package throws an error:

```jl
julia> Pkg.clone("https://github.com/JaredCrean2/PETSc.jl.git") #For example
INFO: Cloning PETSc from https://github.com/JaredCrean2/PETSc.jl.git
ERROR: unlink: no such file or directory (ENOENT)
 in cd at pkg/dir.jl:37
 in clone at pkg.jl:38
```

**Comment by jakebolewski** [comment]
`Pkg.clone("https://github.com/JaredCrean2/PETSc.jl")` works.

**Comment by jakebolewski** [comment]
I can't reproduce this.

**Comment by wildart** [comment]
This could relate to #13389

**Comment by jiahao** [comment]
Yes, the problem went away after installing `libssl` and recompiling Julia. Closing as duplicate of #13389

**Comment by yuyichao** [comment]
I think the package system should probably have a better error report in this case. (The one in #13389 is barely acceptable compare to this one...)
