### ISSUE TITLE
ERROR: ccall: could not find function hello in library HelloWorld.dll on Windows

### ISSUE THREAD

**Issue by n-s-k** [JuliaLang/julia#13405]
A simple `hello.f90`, compile as a `HelloWorld.dll` using ifort on Windows:

``` fortran
module hello_module
    use iso_c_binding
    implicit none
contains

    subroutine hello() bind(C,name="hello")
!DEC$ ATTRIBUTES DLLEXPORT :: hello
      write(*,'(A)') "Hello World!!!"
    end subroutine hello    

end module hello_module
```

and `hello.jl`:

``` julia
test = ccall((:hello, "HelloWorld.dll"), Void, () )
```

on julia REPL:

``` julia
julia> include("hello.jl")
ERROR: ccall: could not find function hello in library HelloWorld.dll
 in anonymous at no file
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
while loading D:\xxx\hello.jl, in expression starting on line 1

julia> dlsym(dlopen("HelloWorld.dll"),"hello")
Ptr{Void} @0x000007fefbbb11e7

julia> include("hello.jl")
Hello World!!!
```

Magic?

**Comment by tkelman** [comment]
Works fine with gfortran. What version of Julia are you using? Check the `HelloWorld.dll` in Dependency Walker, it may be that `ccall` and `dlopen` behave differently with respect to the Intel fortran runtime libraries.

**Comment by n-s-k** [comment]
I'm going to check that still... how comes it works the second time?!?

**Comment by n-s-k** [comment]
also Julia 0.3.11.

**Comment by tkelman** [comment]
`dlopen` might pull in dependency dll's in a different way than `ccall`. Could potentially be a bug there, not sure yet.

**Comment by ihnorton** [comment]
Might be a dll initialization issue. You should try some combinations like dlopen and dlsym alone, try ccall twice, etc.

**Comment by ihnorton** [comment]
Please comment with more information if this is still an issue.
