### ISSUE TITLE
PyPlot does not work on 0.4

### ISSUE THREAD

**Issue by allaffa** [JuliaLang/julia#13403]
I am trying to use the package PyPlot on the 0.4 version of the kernel on JuliaBob but it does not seem to work.
I checked on previous conversations about this and what I found was to try to use the following commands:

Pkg.checkout("PyCall")
Pkg.build("PyCall")
using PyCall
using PyPlot

what I get in output as an error is:

LoadError: __precompile__(true) but require failed to create a precompiled cache file
while loading In[102], in expression starting on line 5

 in require at ./loading.jl:252

Does anyone know where I am wrong in uploading the using the package?
Thank you

**Comment by andreasnoack** [comment]
Dup of https://github.com/stevengj/PyPlot.jl/issues/172 and please file issues at the relevant repositories instead of here.
