### ISSUE TITLE
Problem with map and types

### ISSUE THREAD

**Issue by my-little-repository** [JuliaLang/julia#13421]
The function `map` seems to apply some weird type conversion to the values stored in its argument.

    julia> checkint(x) = (typeof(x) == Int64 ? x : "not an Int")
    checkint (generic function with 1 method)
    
    julia> checkint(1), checkint(1.0)
    (1,"not an Int")
    
    julia> map(checkint,[1, 1.0])
    2-element Array{ASCIIString,1}:
     "not an Int"                     # I expected 1 as a result here.
     "not an Int"    

    julia> map(checkint,(1, 1.0))                    
    (1,"not an Int")                  # this is the expected result.
    
    julia> map(typeof, [1,1.0])
    2-element Array{DataType,1}:
     Float64                          # it should be Int64
     Float64

    julia> map(typeof, (1,1.0))  
    (Int64,Float64)                   # this is the expected result.

    julia> map(x->x, [1,1.0])
    2-element Array{Float64,1}:
     1.0                              # 1?
     1.0

Same problem with comprehension (e.g. `[typeof(x) for x in (1,1.0)]`, `[typeof(x) for x in [1,1.0]]`). I am using julia version 0.4rc3.

**Comment by nalimilan** [comment]
This has nothing to do with `map`, the conversion happens when creating the array:
```julia
julia> [1,1.0]
2-element Array{Float64,1}:
 1.0
 1.0

```

**Comment by swt30** [comment]
In case you need an array that doesn't do this automatic promotion to a common type, you can use an Any array, which is written `{1, 1.0}` in v0.3 and `Any[1, 1.0]` in v0.4.
