### ISSUE TITLE
appveyor fails pkg test suspiciously often

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#13436]
example: https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.9756/job/2iqu8xwxflr4225e

```
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: LoadError: LoadError: GitError(Code:ERROR, Class:OS, Failed to receive response: The server returned an invalid or unrecognized response
)
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:95
 in clone at libgit2.jl:303
 in anonymous at pkg/dir.jl:49
 in cd at file.jl:32
 in path at pkg/dir.jl:17
 in temp_pkg_dir at C:\projects\julia\test\pkg.jl:9
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from util.jl:179
 in runtests at C:\projects\julia\test\testdefs.jl:178
 in anonymous at multi.jl:684
 in run_work_thunk at multi.jl:645
 in remotecall_fetch at multi.jl:734
 [inlined code] from multi.jl:1430
 in anonymous at task.jl:1429
while loading C:\projects\julia\test\pkg.jl, in expression starting on line 169
while loading C:\projects\julia\test\runtests.jl, in expression starting on line 13
```

This has been happening a lot, and while it might just be connection issues, the fact that it only seems to happen on 32 bit leads me to believe it might be a bug in integer sizes or something similar.

**Comment by wildart** [comment]
It relates to handling a HTTP requests. It could be just appveyor glitch.

**Comment by tkelman** [comment]
If it happened as often on 64 bit as 32 bit I would agree with you. It feels like there may be a datatype size bug hiding somewhere.

**Comment by wildart** [comment]
It's [WinHttpReceiveResponse](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384105%28v=vs.85%29.aspx) call error.

**Comment by tkelman** [comment]
Ah, interesting. So maybe this falls under the category of "try to reproduce in C, report upstream" if we can get the same issue to show up in a standalone case.

**Comment by wildart** [comment]
It looks like https response decryption failed.

**Comment by tkelman** [comment]
we might be the first users to heavily exercise the winhttp functionality with mingw compiler, it's possible i or the original author had a bug in the pr upstream that first got that working.

**Comment by wildart** [comment]
Not likely, it's WinAPI. It could be solved by proper OS/IIS settings. I could not find any particulars, error message is too vague.

**Comment by tkelman** [comment]
This hasn't happened for a few days, maybe it was a transient network thing. I'll reopen if it starts coming back frequently.
