### ISSUE TITLE
inconsistent result of 'is' None

### ISSUE THREAD

**Issue by fhs** [JuliaLang/julia#13432]
The following program demonstrates the bug:
```
function f()
	offset = None
	for x in [1, 2]
		if ~is(offset, None)
			break
		end
		offset = 1	# not reached!
	end
	print("f: offset is ", offset, "\n")
end

function g()
	offset = None
	if is(offset, None)
		offset = 1
	end
	print("g: offset is ", offset, "\n")
end

f()
g()
```
It prints this (if I ignore all the warnings):
```
f: offset is Union{}
g: offset is 1
```
Both functions should print "offset is 1".

I'm using 0.5.0-dev+586. This bug was discovered in the ZipFile package (see https://github.com/fhs/ZipFile.jl/issues/17 and https://github.com/fhs/ZipFile.jl/pull/20).

**Comment by simonster** [comment]
I can reproduce on master but not 0.4rc3 so I suspect #11973. cc @vtjnash
