### ISSUE TITLE
tests fail in interactiveutil.jl 0.4.0-rc3+46

### ISSUE THREAD

**Issue by sdacek** [JuliaLang/julia#13441]
>LoadError: test failed: "0.4.0-rc3" == "0.4.0-rc1"
 in expression: Base.VERSION_STRING == chomp(v)
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 [inlined code] from /repos/julia/test/cmdlineargs.jl:6
 in anonymous at no file:5
 in include_string at loading.jl:266
 in include_from_node1 at ./loading.jl:307
 [inlined code] from util.jl:179
 in runtests at /repos/julia/test/testdefs.jl:178
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:63
while loading /repos/julia/test/cmdlineargs.jl, in expression starting on line 3
while loading /repos/julia/usr/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.4.0-rc3+46
Commit 53ff5fe* (2015-10-03 19:29 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin12.6.0)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

> in error at ./error.jl:21
 in runtests at interactiveutil.jl:404
 in runtests at interactiveutil.jl:393

**Comment by jiahao** [comment]
Did you build from source? If so, try `make cleanall && make`.

**Comment by sdacek** [comment]
That works. Only did a make clean the first time.

my mistake

**Comment by jiahao** [comment]
Try `make distcleanall && make`. There are several different levels of clean.

**Comment by sdacek** [comment]
After make distcleanall && make, all tests pass. Thank you
