### ISSUE TITLE
Warning in codegen.cpp when assertions are not turned on

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#13442]
The following commit by @vtjnash https://github.com/JuliaLang/julia/commit/2bbdc30448ac3ded06f41a5c9d2ce54bdf2b5c67
causes a warning about the variable `at` being unused, because it is only used in an `assert()` macro.

**Comment by StefanKarpinski** [comment]
Why not just fix it?

**Comment by ScottPJones** [comment]
I can attempt to do so, yes, but since the line in question has a side effect, I'd hoped that @vtjnash would at least comment on what he intended.  I am also quite busy.

**Comment by ScottPJones** [comment]
@StefanKarpinski It's now fixed, if you'd care to review/merge it.
