### ISSUE TITLE
Pkg.build should launch a separate Julia process?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#13458]
I'm wondering if `Pkg.update` should launch a separate Julia process, so that it builds in a "clean" Julia environment, similar to `Base.compilecache`.

Once you `import Foo`, subsequent `import Foo` calls in the same Julia process just load the `Foo` you already imported, *even if Foo has changed* on disk.   This has caused me lots of problems in `Pkg.update`, apparently because something like the following sequence of events occurs:

1. `BinDeps` or `Conda` was already loaded in a Julia session
2.  `Pkg.update` updates `BinDeps` or `Conda`
3. Another package is updated and tries to run `Pkg.build` using the new `BinDeps` or `Conda`
4. This fails, because either (a) precompilation on BinDeps fails because of #12508 or (b) it's not precompiled (`Conda` isn't, currently) but `Pkg.build` expects some feature of the latest version that is not present in the already-imported version

This would be solved by having `Pkg.update` launch a new Julia process.

cc: @wildart, @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Seems like a pretty good idea.

**Comment by wildart** [comment]
I agree with the proposed. I guess we are talking more of `Pkg.build` rather then `Pkg.update`.

**Comment by stevengj** [comment]
That's true, you could do it just on `Pkg.build`.

**Comment by stevengj** [comment]
Of course, if you launch a new process for each `Pkg.build`, as opposed to once per `Pkg.update`, it will slow things down a bit.

**Comment by wildart** [comment]
Process spawning time is negligible in comparison to external build time.
