### ISSUE TITLE
Surprising directory name in rc tarballs

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13456]
The directory name in the rc tarballs used to be `julia`; this is also suggested in the `Makefile` for the `light-source-dist` target. The current rc (`rc4`) now uses `julia-tarball`. (This is the directory into which the tarball unpacks.) Small changes like these are somewhat inconvenient as they break scripts or manual instructions.

It is customary to include the version number in the directory name. Thus, either `julia-0.4.0` or `julia-0.4.0-rc4` would be good choices.

The `Makefile` explicitly chooses the current directory name instead of using e.g. `julia` all the time. This makes it easy to accidentally create a release with an unintended directory name.

**Comment by milktrader** [comment]
Just experienced the same thing and agreed the file should be named `julia-0.4.0-rc4` versus `julia-tarball`. 

Does anyone remember when tar files where stilled called tar files and then someone decided to start calling them balls?

**Comment by stevengj** [comment]
(According to Google ngrams, "tarball" took off around 1999, and that's when the usage examples start being `.tar.gz` files as opposed to petroleum agglomerations.)

**Comment by nalimilan** [comment]
I think the best solution is to use the same name for the tarball and for the directory inside it, and make this name predictable from the version. So, as you said, `julia-$VERSION` is the perfect candidate. (I believe I noted somewhere that adding the commit ID only makes things more painful for everybody, in particular packagers.)

**Comment by tkelman** [comment]
cc @staticfloat I think you've been making these for the rc's

**Comment by staticfloat** [comment]
Good catch guys, I didn't remember that the tarballs take on the name of the directory that I put the Julia source checkout inside of.  :)  This is fixed for `0.4.0` final now, so I'm going to go ahead and close this.  :)
