### ISSUE TITLE
`exret` not defined

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#13464]
I've bumped into a code path not accounted for [here](https://github.com/JuliaLang/julia/blob/360c537a96fe3888aab099ccb2c5e520b4d1fd67/base/interactiveutil.jl#L274), reproduced by this simple example

```julia
julia> t = "hey there sailor"
"hey there sailor"

julia> @which t[1,1] = (1.0,true)
ERROR: UndefVarError: exret not defined
```
My guess is because the `setindex!` syntax rewrite is involved?
Looks like @andreasnoack edited these parts a couple weeks ago?

**Comment by ZacCranko** [comment]
This is happening here also

```julia
julia> @which c = funfitf(basis, f)
ERROR: UndefVarError: exret not defined
```
