### ISSUE TITLE
Inconsistent parameter behaviour/scope in type declaration

### ISSUE THREAD

**Issue by abbaad** [JuliaLang/julia#13466]
First, let me say that I've only started learning Julia for a couple weeks and what I'm doing is probably not very idiomatic/Julian. I'm trying to make a `type` which has the equivalent of C++/Java static member variables (cf. [previous](https://groups.google.com/d/topic/julia-users/w45WVfSM3gc/discussion) [discussions](https://groups.google.com/d/topic/julia-users/GXH8UBFYd0U/discussion) on `julia-users`).

The behaviour within a type declaration was changed per #10146 to make clear that default values can't be set before the inner constructor (f7a4aa3). There is, however, no prohibition on putting arbitrary code there, so that's what we do. It works as expected:

``` julia
julia> type foo
           data::ASCIIString
           id::Int
           begin
               ID::Int = 0
           end 
           function foo(data::ASCIIString)
               ID += 1 
               new(data, ID)
           end 
       end

julia> foo("first")
foo("first",1)

julia> foo("second")
foo("second",2)
```

We then want to parametrize this type so that each family of types has its own ID. This does not go as expected:

``` julia
julia> type bar{N}
           data::ASCIIString
           id::Complex{Int}
           begin
               ID::Int = 0
           end 
           function bar(data::ASCIIString)
               ID += 1 
               new{N}(data, ID + N*im) 
           end 
       end

julia> bar{1}("first")
bar{1}("first",1 + 1im)

julia> bar{1}("second")
bar{1}("second",2 + 1im)

julia> bar{2}("first")
bar{2}("first",3 + 2im)
```

The programmer might expect that any block annotated with a parameter would be repeated with each new value of the parameter. That is, we expect the last line to have id `1 + 2im`. Instead, the code has only been run once (in the scope where it was entered).

That last parenthetical gives us a clue to what's wrong with the following code, which is closer to my originally intended use case:

``` julia
julia> type baz{N}
           data::ASCIIString
           id::Complex{Int}
           begin
               ID::Int = N
           end 
           function baz(data::ASCIIString)
               ID += 1 
               new{N}(data, ID + N*im) 
           end
       end
ERROR: UndefVarError: N not defined
 in anonymous at ./no file:4294967295
```

Again, we expect that a parametrized block has the parameter accessible, which in this case doesn't.

This is also inconsistent since the parameter _can_ be used with the fields (e.g., `data::Array{ASCIIString, N}` is legal and does what's expected) as well as inside the inner constructor. Currently (0.4.0-rc4) we might achieve the desired behaviour by writing a set of macros which emulates a parametric type (losing all benefits of native parametric typing). Or maybe macros with a global `Dict`.

**Comment by ihnorton** [comment]
>  we expect that a parametrized block has the parameter accessible, which in this case doesn't.

The `ID::Int = N` assignment is executed when the type is declared. This is invalid because `N` is only known when the type is instantiated. Note in the first example that `ID` is *not* a field of the type, rather it is a locally-scoped variable captured in the closure (assignment `ID = 0` is obviously fine to execute during declaration).

I think what you are looking for is more than just a static member variable: an equivalent to a C++ template class with a unique static member variable for all instances of a specific template expansion. It might be possible to simulated this by making an `@generated` `call` overload (though again the variable would be captured in a closure over the constructor, not a field of the type itself). Or you could use a dict with a counter for each `N`, and capture the dict (shouldn't require any macros).

**Comment by abbaad** [comment]
> The `ID::Int = N` assignment is executed when the type is declared. This is invalid because `N` is only known when the type is instantiated.

Yes, I understand *why* it behaves this way. I was just pointing out that from a user's perspective you would expect anything within a parametrized block to be executed parametrically.

> It might be possible to simulate this by making an `@generated` `call` overload

I still haven't quite grasped how to use `@generated`, and I don't think overloading `call` would help my use case (which is a little more complicated than above)

> Or you could capture a dict with a counter for each N (shouldn't require any macros).

I've ended up doing something like this. I have a lexically-scoped `Dict` as well as a lexically-scoped parametric constructor. The parametric constructor is called from the beginning of the inner constructor like this:
```julia
static = get!(cached_statics, (N, nmax, E)) do
    static_init(N, nmax, E)
end
```
Here `cached_statics` is the hidden `Dict`, `static_init` is the parametric constructor (which takes a non-trivial amount of time, so is only executed if there's no match for the key consisting of our parameters `N`, `nmax`, and `E`). Then `static` holds a reference to our static member variables, which is passed to each new instance via `new`. Thus, the static variables are instantiated once for every new combination of parameters and all instances share the same copy.

Altogether a pretty round-about solution, but I'm not sure if there's some Julia-sanctioned alternative idiom for static member variables (the way multiple dispatch supplants class methods). If not, it would be nice to have this as part of the language, although I don't really know what it would look like.

**Comment by JeffBezanson** [comment]
One way to associate state with a type is definitions like

```
counter{N}(::Type{baz{N}}) = get(cache, N, ...)
```

Putting `@generated` in front would allow this to be evaluated at compile time. I prefer this (or your solution) to re-running the type definition block for each parameter value. To me this makes it clearer when or why different code is running for each parameter value.
