### ISSUE TITLE
Help broken for r_str macro

### ISSUE THREAD

**Issue by hayd** [JuliaLang/julia#13467]
Haven't tested this on latest master, and I think this works on 0.4 (or at least did on a previous rc):
```
v"0.5.0-dev+592"

help?> @r_str
ERROR: BoundsError: attempt to access 1-element Array{Any,1}:
 symbol("@r_str")
  at index [2]
```

**Comment by MichaelHatherly** [comment]
I'll have it fixed shortly. Looks like it happened because `Docs.isexpr` is not the same as `Meta.isexpr`... not sure why there's two different versions of `isexpr`.
