### ISSUE TITLE
SubString inconsistency

### ISSUE THREAD

**Issue by maartenheremans** [JuliaLang/julia#13469]
When taking a substring of an ASCII string, the returned value is of type ASCII string.
When doing the same on an UTF16String, the returned value is of type SubString{UTF16String}. This is inconsistent and confusing behaviour. It also requires the user to do an explicit convert to an UTF16String if he wants to use the returned substring as an argument to a function that takes an UTF16String.

example:

```
julia> a = "abcdef"
"abcdef"

julia> b = a[2:4]
"bcd"

julia> typeof(b)
ASCIIString

julia> c = UTF16String("abcdef")
"abcdef"

julia> d = c[2:4]
"bcd"

julia> typeof(d)
SubString{UTF16String}
```

**Comment by ScottPJones** [comment]
Actually, I think that's correct behavior, for type stability.

**Comment by hayd** [comment]
I guess the expected typeof b could be `SubString{ASCIIString}`.

**Comment by ScottPJones** [comment]
On the other hand, somebody might expect all of them to return the same type as the input, however the SubString type is returned as an optimization, but it doesn't always make sense, so sometimes you do get the original type back.

**Comment by ScottPJones** [comment]
Basically, I think you should always expect either `T` or `SubString{T}`, but never a different type entirely
(there are a number of problems elsewhere in Julia, esp. with `UTF16String` or `UTF32String`, where you get back either `ASCIIString` or `UTF8String`, from similar operations (such as `replace`)

**Comment by stevengj** [comment]
This has nothing to do with type stability.  The current implementation is type stable.  Always returning a `SubString` would also be type stable.  Always making a copy would also be type-stable.

I'm not sure why the decision was made to return a copy for slicing an `ASCIIString` (or `UTF8String`) but not `UTF16String`.  It does seem inconsistent.

**Comment by StefanKarpinski** [comment]
I suspect it was not a conscious decision. IIRC, all string slice operations returned SubStrings previously. At some point, I think someone (maybe Jeff?) changed ASCII and UTF8 strings to create copies, but that left things in an inconsistent state. So that's where we are now. It's inconsistent, but I'm not sure it's worth changing right now with bigger string changes coming down the line soon.

**Comment by stevengj** [comment]
@StefanKarpinski, you made me curious, and as far as I can tell it was copied from the very beginning, in 2011 when string slicing was added by you in 0f4d25c906d3564b25199a79811b12ba029abe3d

I agree that it's probably safe to defer this until the slicing and string changes land.

**Comment by StefanKarpinski** [comment]
Faulty memory for the win^H^H^H lose.

**Comment by kshyatt** [comment]
Since the `UTF*` types don't exist in base anymore and the string changes happened, I'm going to close.
