### ISSUE TITLE
Values are not copied

### ISSUE THREAD

**Issue by Thuener** [JuliaLang/julia#13473]
I understand the pass-by-sharing ideia but if I want to copy the values? Not even deepcopy works?

julia> f(x) =  (x*deepcopy(n_x) + deepcopy(d))/deepcopy(n_y)
f (generic function with 1 method)

julia> f(2)
10.5

julia> n_x = 20
20

julia> f(2)
20.5

**Comment by johnmyleswhite** [comment]
You should post questions to the mailing list at julia-users rather than open issues.

**Comment by Thuener** [comment]
Sorry. I thought this was a issue.
