### ISSUE TITLE
Command line flag to simply ignore stale cache files

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13474]
It would be useful while developing a package to have a command line flag that simply ignores the fact that a cache file is stale and just loads the package normally. Otherwise one has to wait for precompilation to finish, which takes longer than just loading the package.

**Comment by felipenoris** [comment]
+1.

**Comment by vtjnash** [comment]
My observation was that caching added ~15% to the load time of a package, which isn't quite enough for me to think this warrants adding another command line flag.

**Comment by Keno** [comment]
@timholy knows more about the performance issues, but with precompile directives that can easily go up to 2-3x.

**Comment by timholy** [comment]
To expand on both points, yes, I agree that under typical circumstances it's not a huge deal. As @Keno says, when you have [lines like these](https://github.com/dcjones/Gadfly.jl/blob/cc37528353f3ab6094608bef188835cd9330e419/src/Gadfly.jl#L1109-L1112) that load [files like this one](https://github.com/dcjones/Gadfly.jl/blob/master/src/precompile.jl) (which, you'll note, is basically a no-op unless you're precompiling), then the cost of precompilation is too high to tolerate during development.
