### ISSUE TITLE
Dangerously misleading example in A_mul_B! documentation?

### ISSUE THREAD

**Issue by bjncn** [JuliaLang/julia#13488]
~~~
help?> A_mul_B!
search: A_mul_B! A_mul_Bt! A_mul_Bc! At_mul_B! Ac_mul_B! At_mul_Bt! Ac_mul_Bc!

  ::
  
             A_mul_B!(Y, A, B) -> Y
  
  
  Calculates the matrix-matrix or matrix-vector product *A B* and stores the
  result in *Y*, overwriting the existing value of *Y*.
  
  .. doctest::
  
     julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; A_mul_B!(B, A, B);
  
     julia> B
     2x2 Array{Float64,2}:
      3.0  3.0
      7.0  7.0

~~~

The example tends to suggest that you can do "in-place matrix-multiplication" `A_mul_B!(B, A, B)`. At first I assumed something like `C=similar(A); A_mul_B!(C, A, B);A=C;` would happen under the hood. But I believe this is not the case and `A_mul_B!(B, A, B)` will result in `B[:]=0` as soon as the dimension is bigger than 3. Again in my limited understanding it works in the example because for n=2 or 3 a specialized explicit version is used.

**Comment by simonster** [comment]
Dup of #11756. The docs should definitely be fixed to 1) use an example that's not broken for n > 3 and 2) document that the source and destination are not permitted to alias (really we should check this in `A_mul_B!` too). Would you care to submit a PR?

**Comment by andreasnoack** [comment]
Yes. That is an unfortunate example. It should be `A_mul_B!(similar(A), A, B)`.
