### ISSUE TITLE
Automatically prompt to install package

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#13482]
When trying to use a package that is not installed, instead of the following error:
```
julia> using PyPlot
ERROR: ArgumentError: PyPlot not found in path
 in require at ./loading.jl:233
```
perhaps it could ask you if you want to install the (registered) package and do so automatically?
Or are there security implications with that?

**Comment by mmoh** [comment]
Great idea +1

**Comment by stevengj** [comment]
Prompts are a problem.  Even if `isinteractive()` returns `true`, you can't necessarily assume that you are interacting via the REPL or that terminal stuff works.  `readline()` works to get user input in IJulia, but not much else.

It could certainly print an error message like `run Pkg.add("PyPlot") to install the PyPlot package`, however.

**Comment by SimonDanisch** [comment]
I implemented it in FileIO... I wanted to do some timeout, but couldn't figure out how to interrupt readline() so I reverted to `isinteractive`...
JuliaIO/FileIO.jl#43

**Comment by ihnorton** [comment]
Also -1. I don't think it is a good idea to hook in to the code loading mechanism like this: prompting for a non-existent package wouldn't make sense, but I don't really like the idea of querying Pkg for every `using`.

**Comment by wildart** [comment]
It could be done only for REPL, and pass an exception in non-interactive mode.

**Comment by SimonDanisch** [comment]
I'mplementation wise there are definitely some issues here... But I think we can all agree, that it'd be very convenient to have.
But maybe this should stay an IDE feature instead of a language feature. It'd remove the uncertainties about the available prompt options. The REPL could be seen as some kind of IDE as well. Is there a way to recognize that the code is running in the REPL and not some other interactive IDE?

**Comment by wildart** [comment]
If a specific exception can be introduced for this type error, then it would be trivial to customize REPL for showing more informative message.

**Comment by jakebolewski** [comment]
We should not try to do anything fancy here, making the error message more descriptive would be useful.
