### ISSUE TITLE
Pkg.update("Foo") to update a single package only?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#13487]
It would be very useful to have a `Pkg.update("Foo")` that only updates a single package `Foo` and its dependencies.   It's very common to want to get the latest *tagged* version of a specific package (*not* `master`) but not want to update everything on your system for fear of breaking something (especially user code).

Even better, only update its dependencies if a specific version is `REQUIRE`d, and then only update to the minimum version required.

(Nor should this result in pinned packages; I still want `Pkg.update()` to update everything.)

In an ideal world, no one would ever tag a buggy version of a package, and no one would ever update APIs in ways that break user code, but we don't live in that world   And yes, there is `Pkg.pin`, but that is **opt-out** of updates one package at a time, but this is painful if you want to pin lots of packages—what I want is **opt-in** updating, and I still want to be able to do `Pkg.update()` when I'm ready to update everything (without going back and freeing all the pinned packages).

**Comment by stevengj** [comment]
(It's also a lot faster to update only a single package.  It's frustrating to wait for 50 packages to update if all I wanted was a newer version of IJulia, for example.)

**Comment by lobingera** [comment]
+1

(btw: if you had asked me earlier, i would have been 99% sure, that this already exists...)

**Comment by SimonDanisch** [comment]
:100: 
I only want to update a single package most of the time and every time I'm surprised that it doesn't exist.

**Comment by simonster** [comment]
While this sounds like a good idea, I think either `Pkg.update("X")` should update both X and its dependencies (at least by default; we could have a flag not to do that) or we should have a CI setup to ensure that people actually set appropriate minimum versions for package dependencies before enabling this.

**Comment by IainNZ** [comment]
+1 to @simonster's sentiment - I think this needs to also recursively update dependencies, given how careful people are with their REQUIRE files.

**Comment by SimonDanisch** [comment]
Oh yeah definitely! Anything else wouldn't make much sense.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/pull/17132.
