### ISSUE TITLE
.desktop file not included in PPA .deb package

### ISSUE THREAD

**Issue by jhasse** [JuliaLang/julia#13495]
I've installed Julia using the PPA, but unfortunately [the desktop file](https://github.com/JuliaLang/julia/blob/master/contrib/julia.desktop) seems to be missing.

Would be great if it and the svg icon can be included so that one can easily start julia using the app menu.

**Comment by ihnorton** [comment]
Maybe best to report on the distro packaging issue tracker, but not sure where that is. cc @nalimilan

**Comment by nalimilan** [comment]
Actually, this is not a distro issue, it regards the custom Julia builds.

@staticfloat I have some code to create icons and install a .desktop file in the Fedora package here if you want:
http://pkgs.fedoraproject.org/cgit/julia.git/tree/julia.spec#n204

**Comment by ViralBShah** [comment]
cc: @sebastienvillemot

**Comment by sebastien-villemot** [comment]
I confirm that the .desktop file is included in the official Debian package. So this is an Ubuntu PPA-only issue.

**Comment by tkelman** [comment]
packaging for the PPA is at https://github.com/staticfloat/julia-debian I believe

**Comment by staticfloat** [comment]
Thanks for the report guys, I've committed a fix [following the example of the Debian package](https://github.com/staticfloat/julia-debian/commit/299feb6c28238ed87848b0985d5931d35c248b9a), new binaries are currently [being built in `juliareleases`](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases/+packages), and this change will trickle into `julianightlies` the next time a nightly build makes it through the gauntlet.

**Comment by KristofferC** [comment]
Don't think this is related to the Julia repository.
