### ISSUE TITLE
Broken download link for Windows32/64 nightly build 

### ISSUE THREAD

**Issue by facundoq** [JuliaLang/julia#13497]
Not sure if this is the place to report, but the links:
https://status.julialang.org/download/win32
https://status.julialang.org/download/win64

don't redirect to the download, they output 'No such build target "winXX"'

The builds are being done apparently (https://status.julialang.org/)

**Comment by tkelman** [comment]
These may have changed to win-32? Don't know why it changed. cc @staticfloat

**Comment by staticfloat** [comment]
It was a fix gone the wrong way.  Patched and working its way through the buildbots.
