### ISSUE TITLE
Scope bug in do blocks?

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#13507]
In rc4, I get the following "not defined" error when running this reduced code snippet:

```jl
a = true
open("test.txt") do input
    if false
        a = true
    else
        a && println("hi!")  # ERROR: LoadError: UndefVarError: a not defined
    end
end
```
I would have assumed that the global `a` is visible inside?

If you comment out `a = true` the code runs as expected, printing "hi!".

**Comment by StefanKarpinski** [comment]
Do blocks are simply syntactic sugar for anonymous functions. Does that help clear it up?

**Comment by rened** [comment]
I am aware of that, but now I see that the behavior is actually very sensible and helps avoiding errors.

Guess my matlab-mindedness messed this up for me. ;-)  Thanks!

**Comment by StefanKarpinski** [comment]
Sometimes it's very tempting to make do blocks behave differently from other anonymous functions, but as Ruby has shown, that way leads only to madness.
