### ISSUE TITLE
norm on Integers and Rationals returns the wrong type

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13503]
The output of `norm` on scalar integers and rationals is of the wrong type. For example:

```
julia> norm(1) === 1
true

julia> norm(1) === 1.0
false

julia> norm([1]) === 1.0
true
```

and similarly for `1//1`, ...

This use case is problematic for doing type arithmetic, e.g. for determining the proper return eltype of a normalized vector `AbstractVector{T}` from the type of `one(T)/norm(one(T))`, as opposed to `one(T)/norm([one(T)])`.

**Comment by hayd** [comment]
[vectnorninf returns float](https://github.com/JuliaLang/julia/blob/38299b7af3eaf0cb5be2ed38e4766842e6be890e/base/linalg/generic.jl#L92), [norm of a number doesn't](https://github.com/JuliaLang/julia/blob/38299b7af3eaf0cb5be2ed38e4766842e6be890e/base/linalg/generic.jl#L189), if that line has float applied, it fixes these cases.

    @inline Base.vecnorm(x::Number, p::Real=2) = float(p == 0 ? real(x==0 ? zero(x) : one(x)) : abs(x))

Perhaps there's a nicer way using dispatch...

**Comment by jiahao** [comment]
@hayd That's interesting. Arguably the infinity-norm returning `float`s by default is wrong too.

From the definitions of the vector norms:

- the return type of the 0-norm should be the type of `abs(one(T))^0 + abs(one(T))^0`
- the return type of the 1-norm should be the type of `abs(one(T)) + abs(one(T))`
- the return type of the ∞-norm should be the type of `abs(one(T))`
- the return type of the `0<p<1`, `1<p<∞` norms should be the type of `sqrt(abs(one(T)) + abs(one(T)))` (`sqrt` being a proxy for `x->x^p`)

It's not immediately obvious that the 0- and 1-norms reduce to the type of `abs(one(T))`.

**Comment by jiahao** [comment]
The flip side of my argument yesterday is that `norm(v, p)` will be type-unstable if different `p`s were allowed to return different types.

I wrote a short code to recurse into the type hierachy of `Number` and compute what the type of `norm` produces currently for various `p`s, compared with the naive result from the definitions on a vector of length 1. https://gist.github.com/jiahao/4d7515dfa7a5987f74fe

I also include the type resulting for promoting the results from `p = 0, 1, 2, Inf`, and compared it to `float(real(one(T)))`.

Highlighted in bold are when the actual results differ from the naive formulas:

T | 0-norm | actual | 1-norm | actual | 2-norm | actual | Inf-norm | actual | promoted | float(real(one(T)))
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
Complex{Real} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{AbstractFloat} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{AbstractFloat}** | 
Complex{BigFloat} | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | **BigFloat** | **Complex{BigFloat}** | 
Complex{Float16} | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | **Float16** | **Complex{Float16}** | 
Complex{Float32} | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | **Float32** | **Complex{Float32}** | 
Complex{Float64} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Integer} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{BigInt} | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | **BigFloat** | **Complex{BigFloat}** | 
Complex{Bool} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Signed} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Int128} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Int16} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Int32} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Int64} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Int8} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Unsigned} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{UInt128} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{UInt16} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{UInt32} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{UInt64} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{UInt8} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
Complex{Rational{T<:Integer}} | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | **Float64** | **Complex{Float64}** | 
BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | 
Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | Float16 | 
Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | Float32 | 
Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | Float64 | 
BigInt | **BigInt** | **BigFloat** | **BigInt** | **BigFloat** | BigFloat | BigFloat | **BigInt** | **BigFloat** | BigInt | BigFloat | BigFloat | 
Bool | **Int64** | **Float64** | **Int64** | **Float64** | Float64 | Float64 | **Bool** | **Float64** | Bool | Float64 | Float64 | 
Int128 | **Int128** | **Float64** | **Int128** | **Float64** | Float64 | Float64 | **Int128** | **Float64** | Int128 | Float64 | Float64 | 
Int16 | **Int16** | **Float64** | **Int16** | **Float64** | Float64 | Float64 | **Int16** | **Float64** | Int16 | Float64 | Float64 | 
Int32 | **Int32** | **Float64** | **Int32** | **Float64** | Float64 | Float64 | **Int32** | **Float64** | Int32 | Float64 | Float64 | 
Int64 | **Int64** | **Float64** | **Int64** | **Float64** | Float64 | Float64 | **Int64** | **Float64** | Int64 | Float64 | Float64 | 
Int8 | **Int8** | **Float64** | **Int8** | **Float64** | Float64 | Float64 | **Int8** | **Float64** | Int8 | Float64 | Float64 | 
UInt128 | **UInt128** | **Float64** | **UInt128** | **Float64** | Float64 | Float64 | **UInt128** | **Float64** | UInt128 | Float64 | Float64 | 
UInt16 | **UInt16** | **Float64** | **UInt16** | **Float64** | Float64 | Float64 | **UInt16** | **Float64** | UInt16 | Float64 | Float64 | 
UInt32 | **UInt32** | **Float64** | **UInt32** | **Float64** | Float64 | Float64 | **UInt32** | **Float64** | UInt32 | Float64 | Float64 | 
UInt64 | **UInt64** | **Float64** | **UInt64** | **Float64** | Float64 | Float64 | **UInt64** | **Float64** | UInt64 | Float64 | Float64 | 
UInt8 | **UInt8** | **Float64** | **UInt8** | **Float64** | Float64 | Float64 | **UInt8** | **Float64** | UInt8 | Float64 | Float64 | 
Rational{BigInt} | **Rational{BigInt}** | **BigFloat** | **Rational{BigInt}** | **BigFloat** | BigFloat | BigFloat | **Rational{BigInt}** | **BigFloat** | Rational{BigInt} | BigFloat | BigFloat | 
Rational{Int128} | **Rational{Int128}** | **Float64** | **Rational{Int128}** | **Float64** | Float64 | Float64 | **Rational{Int128}** | **Float64** | Rational{Int128} | Float64 | Float64 | 
Rational{Int16} | **Rational{Int16}** | **Float64** | **Rational{Int16}** | **Float64** | Float64 | Float64 | **Rational{Int16}** | **Float64** | Rational{Int16} | Float64 | Float64 | 
Rational{Int32} | **Rational{Int32}** | **Float64** | **Rational{Int32}** | **Float64** | Float64 | Float64 | **Rational{Int32}** | **Float64** | Rational{Int32} | Float64 | Float64 | 
Rational{Int64} | **Rational{Int64}** | **Float64** | **Rational{Int64}** | **Float64** | Float64 | Float64 | **Rational{Int64}** | **Float64** | Rational{Int64} | Float64 | Float64 | 
Rational{Int8} | **Rational{Int8}** | **Float64** | **Rational{Int8}** | **Float64** | Float64 | Float64 | **Rational{Int8}** | **Float64** | Rational{Int8} | Float64 | Float64 | 

In every single case of `norm(::Vector{<:Number})`, the promote-common return type across the various `p`s is equal to `float(real(one(T)))`, which points to the latter as what the return type of `norm(T<:Number)` should be.

**Comment by jiahao** [comment]
Again by explicit enumeration of all the cases, all the integer and rational cases are wrong, and for `p=0`, complexes of integers are also wrong.

T | `typeof(norm([one(T)], 0))` | `typeof(norm(T), 0)` | `typeof(norm([one(T)]))` | `typeof(norm(T))`
--- | --- | --- | --- | ---
Complex{Real} | **Float64** | **Int64** | Float64 | Float64 | 
Complex{AbstractFloat} | Float64 | Float64 | Float64 | Float64 | 
Complex{BigFloat} | BigFloat | BigFloat | BigFloat | BigFloat | 
Complex{Float16} | Float16 | Float16 | Float16 | Float16 | 
Complex{Float32} | Float32 | Float32 | Float32 | Float32 | 
Complex{Float64} | Float64 | Float64 | Float64 | Float64 | 
Complex{Integer} | **Float64** | **Int64** | Float64 | Float64 | 
Complex{BigInt} | **BigFloat** | **BigInt** | BigFloat | BigFloat | 
Complex{Bool} | **Float64** | **Bool** | Float64 | Float64 | 
Complex{Signed} | **Float64** | **Int64** | Float64 | Float64 | 
Complex{Int128} | **Float64** | **Int128** | Float64 | Float64 | 
Complex{Int16} | **Float64** | **Int16** | Float64 | Float64 | 
Complex{Int32} | **Float64** | **Int32** | Float64 | Float64 | 
Complex{Int64} | **Float64** | **Int64** | Float64 | Float64 | 
Complex{Int8} | **Float64** | **Int8** | Float64 | Float64 | 
Complex{Unsigned} | **Float64** | **UInt64** | Float64 | Float64 | 
Complex{UInt128} | **Float64** | **UInt128** | Float64 | Float64 | 
Complex{UInt16} | **Float64** | **UInt16** | Float64 | Float64 | 
Complex{UInt32} | **Float64** | **UInt32** | Float64 | Float64 | 
Complex{UInt64} | **Float64** | **UInt64** | Float64 | Float64 | 
Complex{UInt8} | **Float64** | **UInt8** | Float64 | Float64 | 
Complex{Rational{T<:Integer}} | **Float64** | **Rational{Int64}** | Float64 | Float64 | 
BigFloat | BigFloat | BigFloat | BigFloat | BigFloat | 
Float16 | Float16 | Float16 | Float16 | Float16 | 
Float32 | Float32 | Float32 | Float32 | Float32 | 
Float64 | Float64 | Float64 | Float64 | Float64 | 
BigInt | **BigFloat** | **BigInt** | **BigFloat** | **BigInt** | 
Bool | **Float64** | **Bool** | **Float64** | **Bool** | 
Int128 | **Float64** | **Int128** | **Float64** | **Int128** | 
Int16 | **Float64** | **Int16** | **Float64** | **Int16** | 
Int32 | **Float64** | **Int32** | **Float64** | **Int32** | 
Int64 | **Float64** | **Int64** | **Float64** | **Int64** | 
Int8 | **Float64** | **Int8** | **Float64** | **Int8** | 
UInt128 | **Float64** | **UInt128** | **Float64** | **UInt128** | 
UInt16 | **Float64** | **UInt16** | **Float64** | **UInt16** | 
UInt32 | **Float64** | **UInt32** | **Float64** | **UInt32** | 
UInt64 | **Float64** | **UInt64** | **Float64** | **UInt64** | 
UInt8 | **Float64** | **UInt8** | **Float64** | **UInt8** | 
Rational{Integer} | **Float64** | **Rational{Integer}** | **Float64** | **Rational{Integer}** | 
Rational{BigInt} | **BigFloat** | **Rational{BigInt}** | **BigFloat** | **Rational{BigInt}** | 
Rational{Bool} | **Float64** | **Rational{Bool}** | **Float64** | **Rational{Bool}** | 
Rational{Int128} | **Float64** | **Rational{Int128}** | **Float64** | **Rational{Int128}** | 
Rational{Int16} | **Float64** | **Rational{Int16}** | **Float64** | **Rational{Int16}** | 
Rational{Int32} | **Float64** | **Rational{Int32}** | **Float64** | **Rational{Int32}** | 
Rational{Int64} | **Float64** | **Rational{Int64}** | **Float64** | **Rational{Int64}** | 
Rational{Int8} | **Float64** | **Rational{Int8}** | **Float64** | **Rational{Int8}** |

**Comment by wsshin** [comment]
If it is really important to solve the type instability that @jiahao mentioned, writing a version of `norm()` that takes `Val{p}` instead of `p` as the second argument could be a solution.  

We had a similar type instability issue in `maximum()`, `minimum()`, `diff()` in `StaticArrays.jl`.  These functions return an output array whose size is different from the input array, and the size of the output array depends on the second argument `dim` describing the dimension along which the functions apply.  Because `StaticArray` is a type with size information, this means that the output `StaticArray` needs to change the type depending on the value of `dim`, leading to type instability.  So, we decided to offer versions of these functions that take `Val{dim}` instead of `dim` to achieve type stability.

See relevant discussions in https://github.com/JuliaArrays/StaticArrays.jl/issues/65 and https://github.com/JuliaArrays/StaticArrays.jl/issues/84.

**Comment by andreasnoack** [comment]
This sounds mostly like an issue with `StaticArrays`. The array types in base don't have a type instability issue. The problem here is that scalars are handled different from vectors.

**Comment by wsshin** [comment]
@andreasnoack Sorry for the confusion, but I was talking about the type instability that @jiahao mentioned in his third posting, not in the original posting.

**Comment by andreasnoack** [comment]
...but that is not a problem in the current implementation where `norm` returns floating point values for all `p`. I still don't see the connection to this issue.

**Comment by wsshin** [comment]
Returning floating point values for all `p` is exactly the problem that @jiahao pointed out, because ideally the output type of `norm()` should change with `p` according to the mathematical definition of norm.  

For example,
- `norm(x::Vector{Int}, 1)` should return `::Int` (because the 1-norm of `x` is the sum of the absolute values of the entries of `x`, which is still always an integer for all `x::Vector{Int}`), whereas 
- `norm(x::Vector{Int}, 2)` should return a floating point value (because the 2-norm of `x` is the square root of the sum of the squares of the entries of `x`, which is a floating point value even if the entries of `x` are `::Int`.)

**Comment by andreasnoack** [comment]
That is not going to happen because of the type stability issue and I don't think `Val` is the right route. I agree that it would be nice to have a one and infinity norm functions that didn't promote but then I think the right solution is to export `norm1` and `normInf` functions.

**Comment by wsshin** [comment]
Now that I think of it, there are only three `p` values (`0`, `1`, `Inf`) for which the output type of `norm()` should differ from floating point, so I agree with @andreasnoack: it will be better to implement `norm0()`, `norm1()`, `normInf()` separately than using `Val{p}`.

The situation was different in the `StaticArrays.jl` example that I explained above.  There, `maximum()`, `minimum()`, `diff()` had to return different output types for all different values of `dim`, so it made perfect sense to use `Val{dim}`.

Thanks for the insight!

**Comment by abulak** [comment]
`vecnorm` has already [four specialised](https://github.com/JuliaLang/julia/blob/6a1e339ac1ca24b0d00c1721a1833fb39106c559/base/linalg/generic.jl#L81) functions.

while for `±Inf` there is just one call to `float` on return line (easy to change, but why is it there in the first place??), `generic_vecnorm1` is more tricky. 

1. Even for small vectors of rationals it is easy to Overflow. Overflowing does make sense and asks user to specify explicitly whether he is interested in rational computations (then use `BigInt`) or just floting point norm (then `norm(float(v),1)') the latter is arguably more common and much slower than the current one.
2. However the current does not follow "keep functions type-stable" rule

**Comment by ViralBShah** [comment]
Seems we are good now.

```
julia> norm(1) === 1
false

julia> norm(1) === 1.0
true

```
