### ISSUE TITLE
redirect_stdout() no longer accepts a Pipe argument

### ISSUE THREAD

**Issue by simonp0420** [JuliaLang/julia#13519]
First mentioned [here](https://groups.google.com/forum/#!topic/julia-users/s3XDhw1_wv8).
The following works under 0.3 but not 0.4:

```
stdout_orig = STDOUT
(tstream, teeproc) = open(`tee -a temp.txt`, "w", stdout_orig)
redirect_stdout(tstream)
```

The error message under Julia 0.4.0 reads: "ERROR: MethodError: `redirect_stdout` has no method matching redirect_stdout(::Pipe)".

**Comment by Keno** [comment]
`Pipe` now refers to both endpoints. What used to be `Pipe` is now `PipeEndpoint`. Try `redirect_stdout(tstream.in)`.

**Comment by vtjnash** [comment]
@Keno, while that workaround should work, it's still a bug since redirect_stdout should be able to figure that out without being pedantic

**Comment by Keno** [comment]
sure

**Comment by simonp0420** [comment]
@Keno , thanks for the workaround--works great.  In light of @vtjnash and your comments, I'll leave the issue open.
