### ISSUE TITLE
Sparse BitArray

### ISSUE THREAD

**Issue by raichu** [JuliaLang/julia#13511]
Making a separate feature request for a sparse version of BitArray, because the original issue #8469 was closed no-questions-asked without actually being resolved

**Comment by jiahao** [comment]
As with most feature requests, the most expedient way to have the feature in base Julia is to submit a pull request with your proposed implementation.

**Comment by johnmyleswhite** [comment]
Yes, it's important to keep in mind that Julia has a finite labor supply, so we can't implement every feature that might be useful to someone.

As such, it's unlikely this functionality will be added unless someone like you steps up and helps to do the work to develop and maintain this feature.

**Comment by raichu** [comment]
Thanks but no thanks.
I already have Mathematica.

**Comment by stevengj** [comment]
Sparse bitarrays seem like a specialized enough feature that maybe they belong in a package?

**Comment by JeffBezanson** [comment]
Given the per-nonzero overhead of sparse representations, is it even worth using a special bitarray representation with sparse? Of course in theory you don't need to store the nonzeros at all in that case (since they're all 1), but it might not matter when you need at least 4 or 8 bytes per entry for the indexes.

**Comment by tkelman** [comment]
Might be neat if we could elide the construction of a non-dereferenceable values array with Void eltype.

You could pack bits into a block-sparse bitarray, but you'd be likely to hit some poorly-supported block array corner cases.

**Comment by StefanKarpinski** [comment]
That would be cute – it's a similar trick to using `Dict{T,Void}` for the implementation of `Set`.

**Comment by KristofferC** [comment]
With push of trying to move things out of Base, this will likely not be implemented here.
