### ISSUE TITLE
julia compiled to bytecode file and later that bytecode file be executed

### ISSUE THREAD

**Issue by zaxebo1** [JuliaLang/julia#13523]
can julia script be compiled to a portable bytecode file(even bytecode of LLVM will do ). 
and then much later that stored bytecode file can be executed
(note: I do not want JIT compilation.)

I tried to search in  docs,but could not find
If it is not possible. Then can it be added to roadmap?

**Comment by johnmyleswhite** [comment]
The GitHub issue tracker is not the best place for posing feature requests. This question would be well suited for julia-users.

**Comment by pao** [comment]
The aforementioned julia-users list is available at https://groups.google.com/forum/#!forum/julia-users.
