### ISSUE TITLE
Module scope and serialization of anonymous functions

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#13548]
[This thread](https://groups.google.com/d/msg/julia-users/jgT47LBBtWk/LCfXAnBiAgAJ) on julia-users prompted me to dig into how one might define anonymous functions that can be used by workers. It turns out there are some unnecessary bumps:

```jl
module MyModule

export foo

foo(x, p) = println("Got ", x, " and parameter ", p)

end
```

```jl
julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> push!(LOAD_PATH, pwd());

julia> using MyModule

julia> @everywhere foo1 = x -> foo(x, "hello")

julia> remotecall_fetch(2, foo1, 3)
ERROR: On worker 2:
UndefVarError: foo not defined
 in anonymous at none:1
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:63
 in remotecall_fetch at multi.jl:731
 in remotecall_fetch at multi.jl:734
```
which is quite confusing because
```jl
julia> remotecall_fetch(2, foo, 3, "world")
        From worker 2:  Got 3 and parameter world
```
works.

There are two workarounds that suggest a possible fix, and I'm not sure which is to be preferred:
- after `using MyModule`, add `@everywhere using Module`. This suggests that the workers are actually `import`ing `MyModule` rather that `using MyModule`. Should we change this behavior?
- define the anonymous function as `@everywhere foo1 = x -> MyModule.foo(x, "hello")`. Perhaps that scoping could be added automatically?

**Comment by simonster** [comment]
Ref #9245

**Comment by JeffBezanson** [comment]
Dup of #9245.
