### ISSUE TITLE
Array{Type{Int64}}([Float32]) works without any errors

### ISSUE THREAD

**Issue by Gnimuc** [JuliaLang/julia#13547]
the original post is [here](https://groups.google.com/forum/#!topic/julia-users/Eft0un3ao1A). as @yuyichao mentioned, this looks like a bug.
```
julia> a = Array{Type{Int64}}([Float32]); @show a
a = [Float32]
1-element Array{Type{Int64},1}:
 Float32
```

**Comment by JeffBezanson** [comment]
Same root cause as #11327.

**Comment by Gnimuc** [comment]
but I find another strange output:

```julia
julia> VERSION
v"0.5.0-dev+926"

julia> S = TypeVar(:S, Union{}, Integer)
S<:Integer

julia> a = Array{Type{S}}([Float64]); @show a
a = Type{T<:Integer}[Float64]
1-element Array{Type{T<:Integer},1}:
 Float64
```

**Comment by Gnimuc** [comment]
the origin issue is fixed, but is not entirely fixed I think.  should we reopen this? @JeffBezanson

**Comment by yuyichao** [comment]
Is `Array{Type{T<:Integer},1}` even allowed to be a concrete type given it has TypeVar in the type parameter?

**Comment by Gnimuc** [comment]
do you mean something like this?

```julia
julia> T = TypeVar(:T, Int, Int)
Int64<:T<:Int64

julia> Array{Type{T},1}([Int])
1-element Array{Type{Int64<:T<:Int64},1}:
 Int64
```

**Comment by JeffBezanson** [comment]
Please do not manually construct `TypeVar`s. You can easily break many things that way.

**Comment by JeffBezanson** [comment]
`Int64<:T<:Int64` means that `Int` is both the lower and upper bound of T. In other words T equals Int.

**Comment by Gnimuc** [comment]
I wasn't aware of the fact that I abused `TypeVal`s. thanks for pointing out, that makes sense now.
