### ISSUE TITLE
32 bit linux binaries failing numbers test

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#13550]
This has apparently been happening on every 32 bit Linux binary built from the buildbots for at least the last month, including every 0.4.0 rc and the release, and latest 0.5.0-dev nightlies as well.

```
julia> Base.runtests("numbers")
     * numbers              Test Failed
  Expression: repr(0.1 + 0.2) != "0.3"
   Evaluated: "0.3" != "0.3"
ERROR: LoadError: LoadError: There was an error during testing
 [inlined code] from error.jl:21
 in record at test.jl:295
 [inlined code] from error.jl:27
 in do_test at test.jl:197
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from util.jl:179
 in runtests at /home/tkelman/Julia/julia-4f9631a55f/share/julia/test/testdefs.jl:7
 in anonymous at multi.jl:684
 in run_work_thunk at multi.jl:645
 in remotecall_fetch at multi.jl:718
 [inlined code] from multi.jl:368
 in remotecall_fetch at multi.jl:734
 [inlined code] from multi.jl:1430
 in anonymous at task.jl:443
while loading /home/tkelman/Julia/julia-4f9631a55f/share/julia/test/numbers.jl, in expression starting on line 401
while loading /home/tkelman/Julia/julia-4f9631a55f/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.0-dev+712
Commit 4f9631a (2015-10-10 23:49 UTC)
Platform Info:
  System: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at ./error.jl:21
 in runtests at interactiveutil.jl:411
 [inlined code] from float.jl:185
 in runtests at interactiveutil.jl:400
```

This is something specific to the buildbot configuration that we're using for generic Linux binaries, since I haven't managed to reproduce this in a local source build yet, and Travis hasn't had any issues. It may be a bad interaction with gmp  or mpfr or rounding modes since in isolation, `repr(0.1 + 0.2)` returns `"0.30000000000000004"`. 0.3.11 is passing tests, but until I can get this to happen in a source build I can't really do a bisect. cc @staticfloat

**Comment by staticfloat** [comment]
After some detective work, it was determined that this is happening due to one of our dependencies (chief candidate here being `libgrisu`) linking against the system libm which, on some platforms, is rather untrustworthy, causing excess precision leakage.  The solution in the short term is to bundle the system `libm.so` file within the 32-bit linux tarball, in the long term we should either automate bundling `libm.so` or coerce our dependencies into linking against `libopenlibm`.

**Comment by staticfloat** [comment]
@tkelman could you verify that [the current binary](https://julialang.s3.amazonaws.com/bin/linux/x86/0.4/julia-0.4.0-linux-i686.tar.gz) passes all tests on your machine?  I have verified it on two 3d-bit VMs, but I'd like to make extra-sure before closing this.  :)

**Comment by Keno** [comment]
I'm confused, aren't we using a julia grisu implementation now?

**Comment by tkelman** [comment]
Sadly that binary has a different test failure in rounding:
```
     * rounding             ERROR: LoadError: LoadError: test failed: 1.0 is 0.9999999999999999
 in expression: a + b === d
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 in anonymous at /home/tkelman/Julia/julia-0ff703b40a/share/julia/test/rounding.jl:22
 in with_rounding at rounding.jl:54
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from util.jl:179
 in runtests at /home/tkelman/Julia/julia-0ff703b40a/share/julia/test/testdefs.jl:178
 in anonymous at multi.jl:684
 in run_work_thunk at multi.jl:645
 in remotecall_fetch at multi.jl:718
 in remotecall_fetch at multi.jl:734
 [inlined code] from multi.jl:1430
 in anonymous at task.jl:1429
while loading /home/tkelman/Julia/julia-0ff703b40a/share/julia/test/rounding.jl, in expression starting on line 21
while loading /home/tkelman/Julia/julia-0ff703b40a/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at ./error.jl:21
 in runtests at interactiveutil.jl:406
 in runtests at interactiveutil.jl:395
```

**Comment by staticfloat** [comment]
Iiiinteresting, I don't see that on any of the machines I am testing on.  Are you doing this test on actual 32-bit hardware, or a VM?

**Comment by staticfloat** [comment]
@Keno we do indeed seem to not be building libgrisu anymore, you're right.  My mental model is out of date!

**Comment by tkelman** [comment]
This is 64 bit hardware running 32 bit binaries, which I would think should work? The 0.3.x binaries pass their tests in the same configuration.

**Comment by tkelman** [comment]
I also don't think this should be closed until we have an automated fix on master and/or in the buildbot configuration so no manual steps are needed on nightlies or the next backport release.

**Comment by tkelman** [comment]
ref #9847

**Comment by tkelman** [comment]
I think I have this partially figured out, the fix from #9925 at https://github.com/JuliaLang/julia/blob/c615d7124284db2b9af3e3f91192ac1d5b5ca96b/base/float.jl#L417-L421 runs at build time. Surprisingly on the buildbots it passes and `fma_llvm` gets used, but when the binaries get copied over to my Ubuntu 14.04 machine, that check fails. If I comment out those lines to always use `fma_libm`, then binaries (of latest release-0.4) built that way pass all tests. I guess I can try moving that check to a runtime `__init__` method.

**Comment by staticfloat** [comment]
So the issue here is that `LLVM` might have an instruction we can use to perform `fma`, but if we don't, then it falls back onto the system `libm`, and that `libm` may or may not be trustworthy; therefore when building on a platform that is trustworthy and then deploying to a platform that is not trustworthy, we run into problems.

It would also be nice to just tell `LLVM` that `openlibm` is our `libm`.  I don't know how hard that would be though.

**Comment by tkelman** [comment]
I'm surprised that the old buildbots are passing this test but recent ubuntu isn't. I tried to move the check to runtime in https://github.com/JuliaLang/julia/commit/f79d42643d83096db2ffc0fa55bd3c7060b6d331 but travis didn't like that. Anyone have any suggestions?

**Comment by nalimilan** [comment]
Isn't this the same issue as https://github.com/JuliaLang/julia/issues/9890? I don't really understand whether a solution was found there or not.

**Comment by tkelman** [comment]
Yes it's the same issue but we somehow never ran the tests with 0.4 nightlies on 32 bit, or something changed about the buildbot to change the result of the build-time check in #9898 / #9925. Maybe we just try making the build-time check simpler, and always use `fma_libm` on 32 bit? Or would that cause 32 bit Fedora binaries built against system libm to fail?

**Comment by nalimilan** [comment]
I wouldn't care too much about performance on i686 (at least for now), if that allows fixing the build issue. The Fedora packages use openlibm (I can check that they would still work if you like).

Your explanation about `-march=pentium4` is plausible. But how did the tests pass before without it? I remember I had to set it to build Julia on i686.

**Comment by tkelman** [comment]
We used to build the binaries with `MARCH=i686 JULIA_CPU_TARGET=pentium4`, now we build with pentium4 for both. Though we really should not have made that change in buildbot configuration immediately before tagging a release...

**Comment by nalimilan** [comment]
Ah, OK, I forgot this combination worked too. For your defence, this sounded like an innocuous enough change that could only bring more stability...
