### ISSUE TITLE
Performance regression with SIMD loops

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#13552]
I just noticed a performance regression between 0.4-rc4 and the latest 0.5 HEAD with `@simd` loops.
In short: the same code vectorizes in 0.4, does not in 0.5, and also incurs larger allocations.

I've extracted the relevant code (all generated code, hence the weird syntax) and run it with the two versions:
https://github.com/damiendr/Stuff/blob/master/PerfProblems-0.4.ipynb
https://github.com/damiendr/Stuff/blob/master/PerfProblems-0.5.ipynb

**Comment by yuyichao** [comment]
Dup of #13551
