### ISSUE TITLE
code_warntype shows ANY for expressions involving UInt32

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#13568]
I'm noticing various surprising `ANY` annotations for some code involving `UInt32` calculations. For example, `@code_warntype typemax(UInt32(3))` produces:
```
Variables:
  x::UInt32

Body:
  begin  # float.jl, line 382:
      return (Base.box)(UInt32,(Base.checked_trunc_uint)(UInt32,4294967295)::ANY)::UInt32
  end::UInt32
```

**Comment by quinnj** [comment]
I believe I heard from someone that this happens when the method is an intrinsic, since they don't need type information. It'd be nice to account for this in `@code_warntype` though.

**Comment by jiahao** [comment]
Related: #13295

**Comment by yuyichao** [comment]
Also https://github.com/JuliaLang/julia/issues/11122 (kind of duplicated).
