### ISSUE TITLE
start-up fails on machine with less than 8GB RAM

### ISSUE THREAD

**Issue by hroptatyr** [JuliaLang/julia#13563]
```
shell> julia-0ff703b40a/bin/julia
could not allocate pools
zsh: abort (core dumped)  julia-0ff703b40a/bin/julia
```
In particular if overcommit is off, or if there's a hard ulimit that restricts the virtual address space to <=8GB.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/10390
