### ISSUE TITLE
Juno download link on website misrepresented as v0.4

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#13562]
The download link on the website makes it sound like the Juno bundle is current (v0.4.0), which is not the case: its v0.3.10.

**Comment by yuyichao** [comment]
This should go to either https://github.com/JuliaLang/julialang.github.com or https://github.com/one-more-minute/Juno-LT .

**Comment by ViralBShah** [comment]
Fixed anyways. https://github.com/JuliaLang/julialang.github.com/commit/3bf1e3c86f36dbaf4a810607e83365cb88794405

**Comment by ViralBShah** [comment]
cc: @one-more-minute
