### ISSUE TITLE
addprocs remote machine

### ISSUE THREAD

**Issue by mtaoraki** [JuliaLang/julia#13564]
Hi, addprocs doesn't seem to work right anymore since release-0.4 (or i can't find the new syntax). Adding local workers is fine, but if i try:

`addprocs(["node-x"], dir=" ~/JULIA_HOME/")`

it gives out the error: `sh: 1: cd: can't cd to  ~/JULIA_HOME/`
`^CERROR: InterruptException:`
` in unpreserve_handle at stream.jl:55`
 `in wait_readbyte at stream.jl:347`
`in readuntil at stream.jl:922`
 `in readuntil at io.jl:168`
 `in read_worker_host_port at multi.jl:1039`
 `in connect at managers.jl:224`
 `in create_worker at multi.jl:1201`
 `in setup_launched_worker at multi.jl:1148`
 `in anonymous at task.jl:447`
 `in sync_end at ./task.jl:413`
 `[inlined code] from task.jl:422`
 `in addprocs at multi.jl:1114`
 `in addprocs at managers.jl:52`

depending if there is a blank after `dir="` or not, it sometimes says `sh: 1: /_LOCAL_HOME_FOLDER_/julia/usr/bin/julia: not found`

I tried many different possible command versions:

`addprocs(["node-x"])`
`addprocs(["node-x"]; dir=" ~/JULIA_HOME/")`
`addprocs(["node-x"]; dir=" ~/JULIA_HOME/")`
`addprocs(["node-x"]; dir=" ~/JULIA_HOME")`
`addprocs(["node-x"]; tunnel=true, dir=" ~/JULIA_HOME/")`
`addprocs(["node-x"], tunnel=true, dir=" ~/JULIA_HOME/")`
`addprocs(["node-x"]; tunnel=true, dir=" ~/JULIA_HOME/usr/bin/")`
etc...

nothing works. 

Thanks for help!

**Comment by simonster** [comment]
Julia doesn't generally expand `~` in paths (#1136), so you may need to provide the full path to the home directory.

**Comment by mtaoraki** [comment]
No that is not the problem. I also tried the absolute paths.

**Comment by malmaud** [comment]
The relevant part of the codebase saw a lot of revisions recently, so it wouldn't be shocking if this is a real bug that creeped in.

**Comment by mtaoraki** [comment]
seems to work with the stable release. 0.4.0 generic linux binaries
