### ISSUE TITLE
1:3 != collect(1:3)

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#13565]
Is the fact that `1:3 != collect(1:3)` intended? I can see in the definition of `==` that comparisons between `Range` and `Array` are explicitly handled to return `false`, but I can't find a good reason for that.

```julia
julia> x = 1:3
1:3

julia> y = collect(x)
3-element Array{Int64,1}:
 1
 2
 3

julia> x == y
false

# And yet:
julia> all(Bool[i == j for (i, j) in zip(x, y)])
true

help?> ==
[...]
  Collections should generally implement == by calling == recursively on all
  contents.
[...]

```

**Comment by simonster** [comment]
Yes, ranges are not equal to non-ranges because otherwise hashing a range would require hashing every element, which could take quite a while.

**Comment by simonster** [comment]
See also https://github.com/JuliaLang/julia/issues/5778#issuecomment-35474593, #6084, #12226

**Comment by nalimilan** [comment]
Ah, thanks, not sure how I forgot these discussions. Looks like the two most recent comments at https://github.com/JuliaLang/julia/issues/12226#issuecomment-122952826 point to a possible solution.
