### ISSUE TITLE
Mmap.mmap throws InexactError for filesize > 2Gb on Windows 

### ISSUE THREAD

**Issue by laborg** [JuliaLang/julia#13560]
Following code on Windows 7 64bit, Julia 0.4.0 shows the error:
```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
julia> Mmap.mmap(open(tempname(),"w+"), Vector{UInt8}, 1024*1024*3048,0)
ERROR: InexactError()
 in mmap at mmap.jl:126
```
I think this origins in the usage of a wrong type `Cint` for a `ccall` in mmap.il:126
```
handle = create ? ccall(:CreateFileMappingW, stdcall, Ptr{Void}, (Cptrdiff_t, Ptr{Void}, Cint, Cint, Cint, Cwstring),
						file_desc, C_NULL, readonly ? PAGE_READONLY : PAGE_READWRITE, szfile >> 32, szfile & typemax(UInt32), name) :
				  ccall(:OpenFileMappingW, stdcall, Ptr{Void}, (Cint, Cint, Cwstring),
					readonly ? FILE_MAP_READ : FILE_MAP_WRITE, true, name)
```
Changing param types from `Cint` to `Cuint` (DWORD as specified for calls `CreateFileMappingW` and `OpenFileMappingW` in https://msdn.microsoft.com/en-us/library/windows/desktop/aa366763%28v=vs.85%29.aspx) lets mmap handle files with a size > 2Gb:
```
handle = create ? ccall(:CreateFileMappingW, stdcall, Ptr{Void}, (Cptrdiff_t, Ptr{Void}, Cuint, Cuint, Cuint, Cwstring),
						file_desc, C_NULL, readonly ? PAGE_READONLY : PAGE_READWRITE, szfile >> 32, szfile & typemax(UInt32), name) :
				  ccall(:OpenFileMappingW, stdcall, Ptr{Void}, (Cuint, Cuint, Cwstring),
					readonly ? FILE_MAP_READ : FILE_MAP_WRITE, true, name)
```

Or did I miss something?

**Comment by timholy** [comment]
@laborg, can you submit this as a pull request? It would allow the test suite to run on it, and give you credit for your investigations.

I guess the one tricky thing is testing it; I'm not certain that creating a >2GB file just for testing purposes can be justified.

**Comment by ivarne** [comment]
There are lots of similar potential issues, and if we can't afford to run such tests on every PR, we have to separate them out to a separate test target that we can run them on powerful hardware (at least) right before tagging releases.

Ref: [test/intset.jl#L59](https://github.com/JuliaLang/julia/blob/673b2d70e84a103696e76bc4d3553cca6143035f/test/intset.jl#L59)

**Comment by quinnj** [comment]
Confirmed the issue and proposed solution. PR #13682

**Comment by Cody-G** [comment]
#13650 was not resolved for me.  On my machine (Windows 7 with julia compiled via cygwin64) Culong is equivalent to UInt32.  Simply changing to Culonglong solves the problem for me, see my PR #13560.

**Comment by vtjnash** [comment]
The convert on line https://github.com/Cody-G/julia/commit/86d67f80ad505ec74356197660917d0d13dadf98#commitcomment-16135635 shouldn't have been modified. That prevents x64 from mapping files larger than DWORD (which was slightly better than before the PR, when files larger than Int32 couldn't be mapped, but still short of the goal)

**Comment by Cody-G** [comment]
@vtjnash's suggestion worked.  I'm able to correctly map a 3TB file on Windows.  I opened PR #15125
