### ISSUE TITLE
Error when running "Base.runtests()"

### ISSUE THREAD

**Issue by SplashDance** [JuliaLang/julia#13576]
I tried running the full run test and received this output:

```
ERROR: LoadError: On worker 2:
LoadError: test error in expression: check_version()
error compiling check_version: could not load library "libgit2"
dlopen(libgit2.dylib, 1): image not found
 in anonymous at test.jl:92
 in do_test at test.jl:50
 in include_string at loading.jl:266
 in include_from_node1 at /usr/local/Cellar/julia/0.4.0/lib/julia/sys.dylib
 [inlined code] from util.jl:179
 in runtests at /usr/local/Cellar/julia/0.4.0/share/julia/test/testdefs.jl:178
 in anonymous at multi.jl:892
 in run_work_thunk at multi.jl:645
 [inlined code] from multi.jl:892
 in anonymous at task.jl:63
while loading /usr/local/Cellar/julia/0.4.0/share/julia/test/libgit2.jl, in expression starting on line 19
while loading /usr/local/Cellar/julia/0.4.0/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by nalimilan** [comment]
Looks like you need to install libgit2. Where did you get Julia from?

**Comment by SplashDance** [comment]
Homebrew

**Comment by tkelman** [comment]
That test is also safe to shut off. We don't actually use libgit2 on release-0.4 except for this test. We might backport some parts of the pkg rewrite eventually, but it needs a lot more stabilization on master first. You could do `brew install libgit2` and it should fix this.

**Comment by SplashDance** [comment]
Ok, great. By the way, what *is* `libgit2` anyway?

**Comment by tkelman** [comment]
https://github.com/libgit2/libgit2 

It's git as a linkable embeddable C library. The package manager should be much faster on nightlies (and the future 0.5 release) because of it

**Comment by SplashDance** [comment]
So you recommend that I install it?

**Comment by tkelman** [comment]
If you want. Either that, or delete "libgit2" from the list of tests in share/julia/test/choosetests.jl to make `Base.runtests()` pass.

**Comment by wildart** [comment]
@SplashDance How did you get libgit2 tests in 0.4? They only supposed to work on `master`.

**Comment by tkelman** [comment]
There's a placeholder minimal test there on release-0.4 https://github.com/JuliaLang/julia/blob/release-0.4/test/libgit2.jl just to check that the build system parts were working

**Comment by KristofferC** [comment]
Since we ship with libgit2 now, this issue seems oboslete. Please repoen if the issue persist.
