### ISSUE TITLE
Documentation for `require()` should be updated

### ISSUE THREAD

**Issue by Gnimuc** [JuliaLang/julia#13579]
currently, the [doc](http://docs.julialang.org/en/latest/stdlib/base/#Base.require) says:
>When searching for files, require first looks in the current working directory, then looks for package code under Pkg.dir(), then tries paths in the global array LOAD_PATH.

Since [this commit](https://github.com/JuliaLang/julia/commit/75ab3602fcaf224dfcc550dad684125936e4bc44) was merged, `require()` hasn't been looking in the current working directory at all.

**Comment by Sisyphuss** [comment]
And I think 

> This function is part of the implementation of using / import

is not accurate.

It should be "This function use `using`/`import` as part of its implementation".

**Comment by stevengj** [comment]
@Sisyphuss, no, `using/import` call `require`.

**Comment by stevengj** [comment]
It should probably also mention #13542 (it is case-sensitive, even on case-insensitive case-preserving filesystems like Mac and Windows).
