### ISSUE TITLE
GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'lib')

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#13586]
I just got this when trying to install PkgDev. Yet I can load it fine. I have also seen it when updating packages, more precisely when updating Jewel.

```julia
julia> Pkg.clone("https://github.com/JuliaLang/PkgDev.jl.git")
INFO: Cloning PkgDev from https://github.com/JuliaLang/PkgDev.jl.git
INFO: Computing changes...
ERROR: GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'lib')
 in call at ./libgit2/repository.jl:11
 in installed at ./pkg/read.jl:181
 in resolve at pkg/entry.jl:472
 [inlined code] from pkg/read.jl:14
 in resolve at pkg/entry.jl:472
 in clone at pkg/entry.jl:206
 in clone at pkg/entry.jl:222
 [inlined code] from promotion.jl:225
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 [inlined code] from pkg/dir.jl:25
 in clone at pkg.jl:38
```

**Comment by tkelman** [comment]
Any chance you're working on a computer that's had packages installed in the same unversioned `.julia` since 0.2?

**Comment by jakebolewski** [comment]
I've tried on a bunch different systems and I can't reproduce this.  Please re-open if this is still an issue.

**Comment by tkelman** [comment]
Did you try via first installing packages from julia 0.2?

**Comment by Datseris** [comment]
I just got a very similar error for my package, but I don't know what exactly may be causing it. I think the git page of the package is fine, because the Travis and AppVeyor tests work fine, as well as the documentation. The package has been registered, but when I do :
```
julia> Pkg.add("DynamicalBilliards")
INFO: Installing DynamicalBilliards v0.5.0
ERROR: GitError(Code:ENOTFOUND, Class:Repository, Could not find repository from 'DynamicalBilliards')
 in Base.LibGit2.GitRepo(::String) at .\libgit2\repository.jl:11
 in install(::String, ::String) at .\pkg\write.jl:38
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:530
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:476
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at .\pkg\entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:360
 in sync_end() at .\task.jl:311
 in macro expansion at .\task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in add(::String) at .\pkg\pkg.jl:100
```
The weird thing is that `using DynamicalBilliards` works fine as well as all the functions of the package.
Also, if I try to do `Pkg.status()`, I get the exact same error I've posted above...

Let me know what more information you may need.

**Comment by tkelman** [comment]
It wasn't registered yet because your PR to METADATA had not been merged yet - https://github.com/JuliaLang/METADATA.jl/pull/7678.

You might have modifications in your local METADATA. Check the git status there, I'd recommend clearing out anything you don't want to keep.

**Comment by Datseris** [comment]
You are absolutely right, I checked the git status there and it was a complete mess. Something like three different versions... 
Since I wasn't really sure what each one of them was I did a clean Julia install. Now everything works perfectly. Thanks very much for the support!
