### ISSUE TITLE
RemoteRef constructor is not type-stable

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#13591]
Maybe add a parameter for the RemoteRef constructor which is the expected return type of the  thunk.

```julia
julia> typeof(RemoteRef(()->Channel{Int}(1)))
RemoteRef{Channel{Int64}}

julia> typeof(RemoteRef(()->Channel{UTF8String}(1)))
RemoteRef{Channel{UTF8String}}
```

**Comment by JeffBezanson** [comment]
This isn't a bug.

**Comment by malmaud** [comment]
I never said it was a bug, but it is a problem if you are explicitly creating a `RemoteRef` and then `take!`ing from it within the same function.

**Comment by malmaud** [comment]
Can we maybe reopen this as a performance issue or if not, assign a wont-fix label?
