### ISSUE TITLE
Puzzling RemoteRef behavior

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#13592]
This is probably a bug.

Here is the expected behavior:
```
julia> r=RemoteRef(1)
RemoteRef{Channel{Any}}(1,1,7)

julia> put!(r,:first)
RemoteRef{Channel{Any}}(1,1,7)

julia> put!(r,:second)
^CERROR: InterruptException:

julia> take!(r)
:first

julia> take!(r) # Blocks
```

Here is strange behavior: 
```
julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> r=RemoteRef(2)
RemoteRef{Channel{Any}}(2,1,2)

julia> put!(r,:first)
RemoteRef{Channel{Any}}(2,1,2)

julia> put!(r,:second)
^CERROR: InterruptException:

julia> take!(r)
:first

julia> take!(r) 
:second
```

**Comment by JeffBezanson** [comment]
I don't think this is a bug. We don't generally try to guarantee exactly what has or hasn't happened at the point when ^C is pressed. The implementation of remote `put!` has 2 steps: ask the remote processor to put the value, then wait for the request to finish. Here the second step gets interrupted. AFAICT changing this would require more round-trips.

**Comment by malmaud** [comment]
Fair. Still a bit disconcerting that a channel created to hold one element somehow ends up holding two elements.

**Comment by malmaud** [comment]
Oh nevermind, I understand what you're saying now: `put!(::RemoteValue,:second)` is still queued on the worker even after `put!(::RemoterRef,:second)` is interrupted on the client, so the first call to `take!(r)` on the client unblocks the remote task. Seems totally reasonable.

**Comment by amitmurthy** [comment]
dup of https://github.com/JuliaLang/julia/issues/12392
