### ISSUE TITLE
Pivot option in QR not functioning

### ISSUE THREAD

**Issue by victorminden** [JuliaLang/julia#13594]
I've tried this in Julia 0.4.0, Julia 0.4.1-pre+8, and Julia 0.5.0-dev.  It is possible that I am doing something wrong, but I cannot seem to appropriately call the ``qr`` function with the pivot option.

For all the variants below, I get the error commented below.  Has pivoting broken recently, or invocation changed fundamentally in a way that is documented somewhere?

Thanks.

```julia
A = rand(10,10);

F = qr(A,pivot=true);          # This works in Julia 0.3.11
(Q,R,p) = qr(A,pivot=true); # This works in Julia 0.3.11
# ERROR: unrecognized keyword argument "pivot"
# in qr at linalg/qr.jl:47

F = qr(A,pivoted=true);
(Q,R,p) = qr(A,pivoted=true);
#ERROR: unrecognized keyword argument "pivoted"
# in qr at linalg/qr.jl:47

F = qr(A,true);
(Q,R,p) = qr(A,true);
#ERROR: MethodError: `qr` has no method matching qr(::Array{Float64,2}, ::Bool)
```

**Comment by andreasnoack** [comment]
This question is better suited for the Julia Users mailing list, but the answer is yes. It has changed in 0.4. If you look at the documentation, you can see that
```julia
help?> qr
search: qr qrfact qrfact! sqrt sqrtm isqrt require QuickSort PartialQuickSort

  qr(A [,pivot=Val{false}][;thin=true]) -> Q, R, [p]

  Compute the (pivoted) QR factorization of A such that either A = Q*R or A[:,p] = Q*R. Also see qrfact. The default
  is to compute a thin factorization. Note that R is not extended with zeros when the full Q is requested.
```
This is also described in https://github.com/JuliaLang/julia/blob/release-0.4/NEWS.md where all changes should be listed.

**Comment by victorminden** [comment]
Thanks for the quick response and sorry for posting to the wrong spot.  I will repost to the mailing list as I am still not understanding, but I appreciate your help.
