### ISSUE TITLE
Pasting with a leading tab overwrites characters in REPL on Ubuntu

### ISSUE THREAD

**Issue by WillRam** [JuliaLang/julia#13601]
Pasting '\t1234567890' into the REPL from a text editor results in 'julia> 890'
Found using Ubuntu 15.04 and /bin/bash, julia v0.4
Does not occur on Windows

**Comment by johnmyleswhite** [comment]
I've seen this on OS X a few times as well.

**Comment by JeffBezanson** [comment]
dup of #13513
