### ISSUE TITLE
`Base.cconvert_gcroot` is documented but does not exist.

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#13605]
A non-existent function, `Base.cconvert_gcroot`, is documented in this section: https://github.com/JuliaLang/julia/blob/ae154d076a6ae75bfdb9a0a377a6a5f9b0e1096f/doc/manual/calling-c-and-fortran-code.rst#auto-conversion

Unfortunately I don't know how to fix it, so let me just file this issue.

**Comment by yuyichao** [comment]
IIRC, we need to replace `cconvert` with `unsafe_convert` and `cconvert_gcroot` with `cconvert`? (and update the fallback method)

Are these the old names?

**Comment by yuyichao** [comment]
Feels like missing doc update from internal update in https://github.com/JuliaLang/julia/pull/7906 although I'm not very familiar with that part of the history....

**Comment by bicycle1885** [comment]
Yes, and lots of deprecated functions are mentioned in this chapter. I think this should be revised entirely.
