### ISSUE TITLE
Building julia in a separate directory

### ISSUE THREAD

**Issue by hsnamkoong** [JuliaLang/julia#13609]
Hi, I want to manage different versions of julia with a single repo but using
`prefix=/temp/dir`
in the Make.user file doesn't seem to work. What would be the appropriate change I can make to Makefile?

**Comment by vtjnash** [comment]
prefix sets the install directory. are you looking for out-of-tree builds (`make O=/temp/dir`)

**Comment by hsnamkoong** [comment]
No, I'm asking because prefix didn't seem to set the install directory...would there be other ways to set it?

**Comment by hsnamkoong** [comment]
make PREFIX=/temp/dir seems to do it, whereas using prefix in the Make.user file doesn't for some reason.

**Comment by tkelman** [comment]
Might need an `override` to work from `Make.user`
