### ISSUE TITLE
Build problem on Mac OSX Yosemite

### ISSUE THREAD

**Issue by hsnamkoong** [JuliaLang/julia#13619]
When I try to build julia on my mac, I get the following error message:

```
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[3]: *** [libopenspecfun.dylib] Error 1
make[2]: *** [build/openspecfun/libopenspecfun.dylib] Error 2
make[1]: *** [julia-deps] Error 2
make: *** [install] Error 2
```

I have XCode 7.0.1 and the suggestions in #6272 does not seem to work. I've only set prefix in Make.user. What would be a good fix for this?

**Comment by vtjnash** [comment]
just to clarify, have you re-installed the command line tools from the XCode menu (or possibly `xcode-select --install`)

**Comment by vtjnash** [comment]
if you have recently upgraded your OS, have you deleted and reinstalled homebrew/macports/fink (or where ever it is that you get gfortran from)?

**Comment by hsnamkoong** [comment]
I suppose I should remove and reinstall XCode itself? I haven't upgraded my OS recently. And no, I haven't updated my OS recently, although I did update XCode. I'll try again with XCode Version 6  after downgrading.

**Comment by andreasnoack** [comment]
First, try `xcode-select --install` and see what you get.

**Comment by hsnamkoong** [comment]
It returns

xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by ScottPJones** [comment]
What does `xcode-select -p` show?

**Comment by hsnamkoong** [comment]
$ xcode-select -p 
/Applications/Xcode.app/Contents/Developer

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by ScottPJones** [comment]
OK, so it's not pointing to an older or beta version.  Not sure what's wrong then :disappointed:

**Comment by tkelman** [comment]
Where did you get gfortran from?

**Comment by hsnamkoong** [comment]
hn$ gfortran --version
GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.

Was this the info you wanted @tkelman ? If not, how can I get it?

**Comment by tkelman** [comment]
If it's from homebrew, then may need to update and/or reinstall homebrew's gcc

**Comment by hsnamkoong** [comment]
Julia built without any problems after downgrading to XCode 6.4. I think there's a bug in the new version. Thanks all!
