### ISSUE TITLE
Document how @goto and @label work

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13617]
Consider this little snippet

``` jl
while true
    @goto stop
    error()
end
@label stop
```

When run in the REPL as is or from an `include()` call, Julia returns an error

```
ERROR: syntax: label "stop" referenced but not defined
```

Putting these lines in a `function` block results in the expected no-op behavior, since it introduces local scope.

However, wrapping these five lines in a `begin... end` block, however, _also_ allows this code to work, even though no new scope is introduced within this block.

It appears that the behavior of this code depends on whether it is being interpreted in one case or compiled in another case?

Discussed with @mbauman

P.S. `@goto` is also not documented in our manual, but that's a separate issue.

**Comment by StefanKarpinski** [comment]
I don't think that has anything to do with global scope but whether the goto and the label are introduced in the same parse.

**Comment by JeffBezanson** [comment]
It seems fine to me that you can't goto a different top-level statement. I would make that a documented restriction.

**Comment by jiahao** [comment]
Ok; I was unsure if the example was supposed to work, since NEWS.md (our only documentation of `@goto`) says only that "local `@goto`" is supported, and I took that to mean local scope only.

**Comment by KristofferC** [comment]
#23656

**Comment by potaslab** [comment]
I find the documentation on the use of @goto and @label a bit brief and unclear for me to understand . It currently says: 

```
@label and @goto cannot create jumps to different top-level statements. Attempts cause an error. To still use @goto, enclose the @label and @goto in a block.
```
As I understand, IF statements should work in the current scope. So for example, can you introduce a @label inside a nested IF statement that sits outside another IF block where the @goto is located, but that is all inside a function? In other words, if the @goto and @label are inside a function, is there any restrictions on where they can go?
