### ISSUE TITLE
eachline(`cmd`) doesn't throw error on command failure

### ISSUE THREAD

**Issue by yesimon** [JuliaLang/julia#13616]
For example:

```
julia> collect(eachline(`cat nonexistent`))
cat: nonexistent: No such file or directory
0-element Array{ByteString,1}
```

I would normally expect an exception to be raised.

**Comment by StefanKarpinski** [comment]
I'm fairly certain this used to work (that is throw an exception), so this seems to be a regression. Thanks for reporting.

**Comment by tkelman** [comment]
Sure this ever worked? I've gone over a year back in the history and have yet to find a build where this throws.

**Comment by StefanKarpinski** [comment]
It's possible I'm just wrong about that.
