### ISSUE TITLE
Incredibly long compile time when calling `Base.Dates.Date(periods::Period...)` with `Month, Day, Year`

### ISSUE THREAD

**Issue by Michael-Klassen** [JuliaLang/julia#13610]
I believe I found an issue with the julia compiler.
I'm currently using Julia Version 0.5.0-dev+558.

When you call `Base.Dates.Date(periods::Period...)` with `Month, Day, Year` (not in YMD order) the compiler seems to gets confused with it and the `Date(y::Year,m::Month=Month(1),d::Day=Day(1))` function.

``` Julia
julia> using Base.Dates

julia> @time Date(Month(10), Day(13), Year(2015))
 68.004381 seconds (96.32 M allocations: 3.530 GB, 0.56% gc time)
2015-10-13
```

I recreated the bug outside of `Base.Dates.Date`:

``` Julia
abstract Foo
immutable Bar1 <: Foo end
immutable Bar2 <: Foo end
immutable Bar3 <: Foo end

function Baz(foos::Foo...)
    x = Bar1(); y = Bar2(); z = Bar3()
    for i in foos
        if typeof(i) <: Bar1
            x = i
        elseif typeof(i) <: Bar2
            y = i
        elseif typeof(i) <: Bar3
            z = i
        end
    end
    return Baz(x, y, z)
end

Baz(x::Bar1, y::Bar2, z::Bar3) = nothing

Baz(Bar1(), Bar3(), Bar2())
```
``` julia
julia> @time Baz(Bar1(), Bar3(), Bar2())
 46.059258 seconds (62.83 M allocations: 2.428 GB, 0.65% gc time)
```

**Comment by iamed2** [comment]
I can confirm it also affects 0.4.0 (on some machines I get what could be an infinite loop as it lasts at least half an hour). 

It's also worth noting that the second time you run the code it's instantaneous; this is definitely an issue during compilation.
