### ISSUE TITLE
Python function in v0.4 docs

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#13625]
I couldn't find another issue with this problem. All functions are labelled as Python functions in the v0.4 docs, but not in the v0.3 docs.

V0.3:
http://docs.julialang.org/en/release-0.3/search/?q=mean&check_keywords=yes&area=default#

V0.4:
http://docs.julialang.org/en/release-0.4/search/?q=mean&check_keywords=yes&area=default#

**Comment by KristofferC** [comment]
Related #11527

**Comment by yuyichao** [comment]
It's an upstream issue https://github.com/rtfd/readthedocs.org/issues/1382
