### ISSUE TITLE
Mutability as a Type Parameter

### ISSUE THREAD

**Issue by Rory-Finnegan** [JuliaLang/julia#13633]
I'm not sure if this has been brought up somewhere and I just couldn't find it, but I've been working at adding Immutable versions of several collection types and it seems like it would be nice if most types just supported a mutability type parameter rather than requiring separate Immutable versions of the types.

Ex)
```
myarray = Array{Pure, Float64, 3}(2, 2, 2)
```
or
```
myarray = Array{Mut, Float64, 3}(2, 2, 2)
```
This would allow having mutating methods that dispatch only on `Mut` versions of the type and other common methods that dispatch on any `Array` in this case. This avoid the issue of needing to either implement a custom `ImmutableDenseArray`, `ImmutableSparseArray`, etc or making an `ImmutableArray` wrapper to any `AbstractArray`.

This follows from a stackoverflow comment [here](http://stackoverflow.com/questions/26966395/why-is-immutability-set-on-types-rather-than-variables-in-julia)

Thoughts?

**Comment by johnmyleswhite** [comment]
I suspect this can't be made to work in Julia given that the language has no external concept of ownership nor does it have any mechanism for flagging and rejecting unsafe code. It's pretty easy to invent examples that break any nominal promise of immutability for any heap allocated object.

Perhaps a deeper question: why not use the immutable tuple formulations others have already invested a lot of time into? Tuples have the benefit that their immutability makes stack allocation possible.

**Comment by Rory-Finnegan** [comment]
I don't really think you need a concept of ownership to make something like that work. Can't we just control modification via the method interface (ie: all mutating methods must take `MyType{Mut}` rather than just any `MyType`)? I think that is a reasonable stance for most applications and we can just say that mutating immutable references outside of the published interface may have undefined behaviour which is how rust for example responds to unsafe C code that could violate its conditions.

Can you clarify what you mean by "immutable tuple formulations"? If you're just asking why I don't want to use Tuples for all immutable types, my reason is that while tuples are a really useful data structure I don't think it makes sense to use them under all conditions where you'd want an immutable type.

**Comment by iamed2** [comment]
I think controlling things as @Rory-Finnegan says through the method interface would be reasonable. Even the immutable Julia constructs like Union types can be mutated with pointers, so the fact that you can circumvent rules and do pointer magic in order to mutate seems acceptable.

**Comment by JeffBezanson** [comment]
> easy to invent examples that break any nominal promise of immutability

Using pointers and unsafe operations I assume?

I think it would be ok for some user-defined type to have a parameter that makes mutating operations fail, but this cannot be done throughout the system. The runtime system allocates objects, and it needs to know at that point whether the object is mutable, which cannot depend on type parameters since they have user-defined semantics.
