### ISSUE TITLE
Date(::String, ::DateFormat) isn't type stable

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#13644]
Placeholder issue so I remember:

``` julia
julia> @code_warntype Date("2015-01-01",Dates.DateFormat("yyyy-mm-dd"))
Variables:
  dt::ASCIIString
  df::Base.Dates.DateFormat

Body:
  begin  # dates/io.jl, line 205:
      return (top(_apply))((top(getfield))(Base.Dates,:call)::F,Base.Dates.Date,(Base.Dates.parse)(dt::ASCIIString,df::Base.Dates.DateFormat)::Array{Any,N})::Any
  end::Any

```

**Comment by amellnik** [comment]
Oh man, I think that the DateTime version of this is the cause of a strange issue I've been seeing related to different number of unique rows in the same DataFrame before and after saving to a csv and reloading.  Good catch.

**Comment by quinnj** [comment]
Umm.....I don't think that should happen. The key issue here is just that type inference isn't able to know that a `Date` will in fact be returned from `Date(::String, ::DateFormat)`. It shouldn't actually return different values at all. Or maybe I'm misunderstanding; do you have a reproducible case you could share?

**Comment by felipenoris** [comment]
After https://github.com/JuliaLang/julia/commit/94b2b20a952bcfa8203fe929a589dfb648465f27, things got a little better:
```julia
julia> @code_warntype Date("2015-01-01",Dates.DateFormat("yyyy-mm-dd"))
Variables:
  dt::ASCIIString
  df::Base.Dates.DateFormat

Body:
  begin  # dates/io.jl, line 205:
      return (top(_apply))((top(getfield))(Base.Dates,:call)::F,Base.Dates.Date,(Base.Dates.parse)(dt::ASCIIString,df::Base.Dates.DateFormat)::Array{Any,1})::Any
  end::Any
```

**Comment by amellnik** [comment]
@quinnj I wasn't able to reproduce this in a simple case, and I recently moved over to using SQLite as a backend, so I don't see it in my actual data anymore.  You're probably right that this was due to something else.  My other theory was that it was related to columns with element type Any containing multiple string types, but it looks like that's not the case either.  Dunno.

**Comment by KristofferC** [comment]
Fixed:
```
julia> @code_warntype Date("2015-01-01",Dates.DateFormat("yyyy-mm-dd"))
Variables:
  #self#::Any
  dt::String
  df::DateFormat{Symbol("yyyy-mm-dd"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'}}}

Body:
  begin 
      return $(Expr(:invoke, MethodInstance for parse(::Type{Date}, ::String, ::DateFormat{Symbol("yyyy-mm-dd"),Tuple{Base.Dates.DatePart{'y'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'m'},Base.Dates.Delim{Char,1},Base.Dates.DatePart{'d'}}}), :(Base.Dates.parse), :(Base.Dates.Date), :(dt), :(df)))
  end::Date
```

I believe the recent work on the Date parsing has sufficient coverage for this.
