### ISSUE TITLE
ENV["HOME"] not correctly set on Windows

### ISSUE THREAD

**Issue by tlycken** [JuliaLang/julia#13643]
I discovered this weird behavior because I noticed `Pkg` not working for anything that required access to remote repositories. If I do anything with `Pkg` that requires access to a git remote repo (e.g. `Pkg.update()`) I get authentication failures because git can't find my public key file. However, if I open git-bash from the Julia installation directory and try the same thin manually, it works.

On my Windows machine, Julia 0.4.0 behaves like this after startup:

```jl
julia> ENV["HOME"]
ERROR: KeyError: HOME not found

julia> homedir()
"C:\\Users\\Tomas\ Lycken"
```

To fix `Pkg`, I have to manually set `ENV["HOME"]` - when I've done that, the key files in `"$(ENV["HOME"])/.ssh"` are found again, and `Pkg` works.

This doesn't just affect git-related commands, though - a `.juliarc` file in that home directory is not run at startup (so I can't fix it by adding `ENV["HOME"] = get(ENV, "HOME", homedir())` to it...).

This was [originally discussed on the julia-users list](https://groups.google.com/forum/?nomobile=true#!topic/julia-users/jq1YRGPgQPk), but since `.juliarc` isn't run I think this is definitely a bug (and quite possibly a regression - I have used the Windows nightlies, although somewhat infrequently updated, for quite a while in the 0.4-pre cycle, without ever seeing this before).

**Comment by tkelman** [comment]
`HOME` isn't an environment variable that gets set by default on Windows (outside of posix environments like Cygwin or MSYS2) and shouldn't be necessary for git to run correctly, I would think. Something may be broken due to the spaces in your path though? Not sure where in either Julia or git that would get treated differently depending whether it's set in `HOME` or not.

**Comment by tlycken** [comment]
Well, `ENV["HOME"]` is certainly relevant *somewhere*, since a lot of things start working as soon as it's set.

User home dirs with spaces aren't an abnormality on Windows, by the way, since a lot of user accounts are simply "Firstname Lastname", and the home dir is set accordingly.

**Comment by tkelman** [comment]
Sure. If this used to work without having to manually set `HOME`, then something broke it and we should fix it. Just have to find what it was.

**Comment by tlycken** [comment]
Hm. My `.juliarc` problem was apparently a user error, since the file is supposed to be named `.juliarc.jl`, i.e. with the ending *`.jl`* which I omitted. Adding that, it works.

So now the only thing not working (that I know of) is when `Pkg` shells out to `git`. Since we're using mysysgit (right?) I assume `git` itself might assume the presence of a `$HOME` variable in its environment?

**Comment by nalimilan** [comment]
@tlycken Even if manually adding a workaround to `~/.juliarc.jl` works, it's still an issue that it doesn't work by default. Going over all occurrences of `HOME` in the code base should allow finding the culprit.

**Comment by tkelman** [comment]
> I assume `git` itself might assume the presence of a `$HOME` variable in its environment?

Not when you call just the git executable outside of msys. `HOME` isn't set by default in Windows, and `git` should usually function without it. Something may now be mismatched between where git looks for things by default and the way in which we're calling it?

**Comment by tlycken** [comment]
@nalimilan I did, and didn't find anything suspicious. The only ones I found where [here](https://github.com/JuliaLang/julia/blob/2d821670d2516cd38b51710b07b3eb18f191cd1b/test/path.jl#L3) (a `@unix only` test) and [here](https://github.com/JuliaLang/julia/blob/b6c0d95726547e4cabb8696d2f823e5a1bea5559/base/path.jl#L12) (the `@unix only` definition of the `homedir()` function).

**Comment by nalimilan** [comment]
Too bad. You could try running the git commands manually from inside Julia and see whether you get the same errors.

**Comment by tlycken** [comment]
@nalimilan Same behavior. [Here's a gist](https://gist.github.com/tlycken/799089848f6089196ee6) with things I've tested.

**Comment by tkelman** [comment]
This might be wierdness and posix assumptions in libssh rather than git proper. I've never managed to get ssh keys working in Julia on windows, this HOME issue might be part of the reason.

**Comment by tlycken** [comment]
The thing that (to me) indicates that Julia is involved somewhere is that if I start a git-bash shell from the Git installation that Julia bundles, it works, as well as if I use any other Git installation I have through Powershell.

At least now that I found the correct way to use `.juliarc.jl`, I can use `ENV["HOME"] = get(ENV, "HOME", homedir())` there as a workaround.

**Comment by tkelman** [comment]
git-bash is an msys posix environment, so sets HOME. Try with git from cmd.

**Comment by vtjnash** [comment]
ENV["HOME"] is not supposed to be set on Windows. we could set it for git commands, but git should still run happily if it is not set.

**Comment by tkelman** [comment]
Would still like to debug what was happening with git, so do let us know what happens with git from cmd w.r.t. finding keys.

**Comment by tlycken** [comment]
@tkelman I tried to run `git` from within `cmd` now; it seems to find the keys fine both if I just do `git pull` from e.g. the METADATA directory, or if I specify the exact path to the git bundled with Julia (i.e. `"C:\Users\Tomas Lycken\AppData\Local\Julia-0.4.0\Git\bin\git.exe" pull`).

Complementary info:

```
> where git
C:\Users\Tomas Lycken\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd\git.exe
C:\Users\Tomas Lycken\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\git.exe
```

**Comment by tkelman** [comment]
We're not recommending people use git or ssh protocol remotes going forward. What is the version number of the git from github for windows? This may apparently be fixed by changing our embedded git from 1.x to 2.x.

**Comment by tlycken** [comment]
Github for Windows bundles version `1.9.5.github.0` - I suspect the ending is because they bundle it with Posh-Git.

**Comment by tkelman** [comment]
I think we bundle a very similar version in 0.4.0, so github for windows might be modifying the gitconfig ot something to search for keys in more places.

**Comment by jayschwa** [comment]
I'm running into the same issue with a clean install of Julia 0.4 and `.julia` wiped away. If it can't work due to the presence of GitHub for Windows, a workaround should be attempted, or it should be documented at the very least. Unless there is a known fix on the horizon, I suggest reopening the issue and renaming it.

**Comment by tkelman** [comment]
Don't put things permanently on your path? Are you sure taking github for windows off your path changes anything? If not, this is likely just a difference in configuration between github for windows and our copy of git.

**Comment by tlycken** [comment]
...in which case we should fix our configuration, rather than banning all others.

"Don't put things permanently on your path" is quite unhelpful, since it would make the git client I installed with the expressed purpose of actually using git, in my terminal, much less useful.

I'll gladly post any configuration files from my laptop, if there are any that would help troubleshoot this, but I have no idea which ones make sense. Point them out, and I'll post gists with them.

**Comment by tkelman** [comment]
I agree, but don't know what github for windows is doing differently yet. Find gitconfig files and see what's in them?

**Comment by tkelman** [comment]
Another thing you might be able to try is setting `GIT_TRACE=1` or 2.
