### ISSUE TITLE
issym on sparse matrices with stored zeros give wrong answer

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#13645]
Don't have a MRE yet but putting it here so I don't forget:

```julia
julia> issym(K*K')
false

julia> issym(Base.SparseMatrix.dropzeros(K*K'))
true

julia> find((K*K').nzval .== 0)
4-element Array{Int64,1}:
  6
 23
 74
 91
```

Removing the line lines  [here](https://github.com/JuliaLang/julia/blob/6e4c9f164832b5743b13c36c58d6bdd63ebbf1b8/base/sparse/sparsematrix.jl#L2490) makes my example works but then it fails when the zeros are stored unsymmetrically, as in:

```jl
julia> A = sparse([1.0 2.0;
                   0.0 1.0])

julia> A.nzval[2] = 0.0

julia> full(A)
2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

julia> issym2(A)
false
```

**Comment by kshyatt** [comment]
HI @KristofferC, no one ever responded :disappointed:. Is this still a problem? Do you want to work on it?

**Comment by andreasnoack** [comment]
It was my impression that @KristofferC would take a look when he had the time.

**Comment by KristofferC** [comment]
I will try to make some time on the weekend for this.
