### ISSUE TITLE
baremodule eval problem

### ISSUE THREAD

**Issue by kuldeepdhaka** [JuliaLang/julia#13658]
````
baremodule TestMe

import Base: call, println, @eval, eval

type Problem
end

println(Problem)
@eval println(Problem)      #im failing

end
```

result in

```
TestMe.Problem
ERROR: LoadError: UndefVarError: Problem not defined
 in eval at ./sysimg.jl:13
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:382
 [inlined code] from ./operators.jl:313
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading /home/kuldeep/Desktop/test.jl, in expression starting on line 9
````

http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=baremodule#Base.eval
there is some difference for "baremodule" but how to make the above code work for "baremodule"?

same for `@eval println(TestMe.Problem)`

version: `julia version 0.5.0-dev`

**Comment by jakebolewski** [comment]
This doesn't fix the problem with the macro:

```julia
julia> baremodule TestMe

       import Base: call, println, eval, eval

       type Problem
       end

       println(Problem)
       eval(TestMe, :(println(Problem)))      #im failing

       end
WARNING: replacing module TestMe
TestMe.Problem
TestMe.Problem
TestMe
```

**Comment by kuldeepdhaka** [comment]
ah ha! adding `eval(expr::Expr) = eval(TestMe, expr)` solved the problem.
@jakebolewski thanks for the tip.

**Comment by jakebolewski** [comment]
@kuldeepdhaka if you look at the AST, you will see that these definitions are added in by default for `modules` but not `baremodules`:

```julia
julia> parse("""
       module TestMe

              type Problem
              end
              @eval println(Problem)
       end""")
:(module TestMe
    eval(x) = begin  # none, line 1:
            top(Core).eval(TestMe,x)
        end
    eval(m,x) = begin  # none, line 1:
            top(Core).eval(m,x)
        end # none, line 3:
    type Problem
    end # none, line 5:
    @eval println(Problem)
    end)
```

If you can point to a specific place where this is not documented or the documentation could be clearer we should fix that.

**Comment by kuldeepdhaka** [comment]
@jakebolewski my bad, at http://julia.readthedocs.org/en/latest/manual/modules/#default-top-level-definitions-and-bare-modules, it has been documented. i just somehow missed it.
