### ISSUE TITLE
Missing warning for method ambiguity with vararg tuples?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#13651]
``` julia
using Base.Dates
extract{T}(::Type{T}, periods::Tuple{T,Vararg{Period}}) = periods[1]
extract{T}(::Type{T}, periods::Tuple{Vararg{Period}}) = extract(T, Base.tail(periods))
extract{T}(::Type{T}, ::Tuple{}) = T(1)

julia> methods(extract)
#3 methods for generic function "extract":
extract{T}(::Type{T}, ::Tuple{}) at none:1
extract{T}(::Type{T}, periods::Tuple{Vararg{Base.Dates.Period}}) at none:1
extract{T}(::Type{T}, periods::Tuple{T,Vararg{Base.Dates.Period}}) at none:1
```

I'd expect `extract{T}(::Type{T}, periods::Tuple{T,Vararg{Period}})` to be more specific than `extract{T}(::Type{T}, periods::Tuple{Vararg{Period}})`

Ref https://github.com/JuliaLang/julia/pull/13611#issuecomment-148501187

**Comment by JeffBezanson** [comment]
This is tricky, since `Period` is more specific than `T`. Do you have a general rule in mind that would make it work the way you want in this case?

**Comment by simonster** [comment]
Yes, you're right. It sorts properly if I make `T<:Period`. Perhaps this should be an ambiguity warning, then?

**Comment by mbauman** [comment]
Slightly simpler example of the ambiguity:

```jl
julia> f(::Tuple{Any, Vararg{Any}}, ::Tuple{Vararg{Any}}) = 1
       f(::Tuple{Vararg{Any}}, ::Tuple{Any, Vararg{Any}}) = 2
       f((1,), (1,))
2

julia> g(::Tuple{Vararg{Any}}, ::Tuple{Any, Vararg{Any}}) = 2
       g(::Tuple{Any, Vararg{Any}}, ::Tuple{Vararg{Any}}) = 1
       g((1,), (1,))
1

julia> methods(f)
# 2 methods for generic function "f":
f(::Tuple, ::Tuple{Any,Vararg{Any}}) at none:2
f(::Tuple{Any,Vararg{Any}}, ::Tuple) at none:1

julia> methods(g)
# 2 methods for generic function "g":
g(::Tuple{Any,Vararg{Any}}, ::Tuple) at none:2
g(::Tuple, ::Tuple{Any,Vararg{Any}}) at none:1

**Comment by JaredCrean2** [comment]
I think I am running into this when implemented `map` for a new type
```julia
type Vec
  a::Array{Float64, 1}
end

import Base.map!

function map!(f, c)
  map!(f, c, c)
end

function map!(f, dest::Vec, src::Vec)
  println("called single src map!")
end

function map!(f, dest::Vec, src::Vec...)
  println("called varags map!")
end

v1 = Vec(rand(3))
map!(sin, v1)
```
says that it called the varargs map, but if that method is commented out, it will call the single src map.  This make me wonder if the implementation of `map!` in `Base` might be behaving in unintended ways because the [n argument method](https://github.com/JuliaLang/julia/blob/master/base/abstractarray.jl#L1156)  is silently ambiguous with the [2 argument method](https://github.com/JuliaLang/julia/blob/master/base/abstractarray.jl#L1136).

**Comment by tkelman** [comment]
Silent ambiguities still make me nervous about that change.

Does it help if you change the n arg version there to only apply for 3+ args?

**Comment by JaredCrean2** [comment]
That only displaces the problem from `map!(sin, v1)` to `map!(sin, v1, v2)`, because varargs implies zero or more arguments rather than one or more.

**Comment by tkelman** [comment]
3+ input arrays, not total arguments, as the comments there are counting.

This would only remove an instance of ambiguity, not fix the inability to detect it.

**Comment by JaredCrean2** [comment]
Do you mean something like this?
```
map!(f, dest::Vec, src1::Vec, src2::Vec, src_rem::Vec...)
  srcs_all = (src1, src2, src_rem...)
 # ... do map ...
```
That should fix it, although it is less neat.

**Comment by KristofferC** [comment]
These (https://github.com/JuliaLang/julia/issues/13651#issuecomment-194615933) both give ambiguity warnings so this looks fixed.
