### ISSUE TITLE
Cannot open .dat file from scilab

### ISSUE THREAD

**Issue by aoblet** [JuliaLang/julia#13657]
After many researches I did not find how open .dat files in Julia saved from scilab as Vector/Matrix. (saved with [scilab save function in binary] (https://help.scilab.org/doc/5.5.2/en_US/save.html))

I've found a temporary solution in scilab:
```
function datToTxt(srcPath, dstPath)
    load(srcPath)
    write(dstPath, x)
endfunction
```

**Comment by stevengj** [comment]
See the HDF5.jl package to read HDF5 files, since it sounds like Scilab uses an HDF5-based format.

In general, these kinds of usage questions are better posted to the julia-users mailing list.

**Comment by aoblet** [comment]
Ok thanks.
