### ISSUE TITLE
`ascii` and `utf8` do not accept `Cstring` or `Ptr{Cchar}` input

### ISSUE THREAD

**Issue by jayschwa** [JuliaLang/julia#13669]
`ascii` and `utf8` do not accept `Cstring` or `Ptr{Cchar}` input, while `bytestring` does. There may be times when using one of the former over the latter is preferable because they are more explicit and type stable.

```
julia> cstr = Cstring(pointer("foo"))
Cstring(0x0000000082929a30)

julia> bytestring(cstr)
"foo"

julia> ascii(cstr)
ERROR: MethodError: `convert` has no method matching convert(::Type{ASCIIString}
, ::Cstring)
This may have arisen from a call to the constructor ASCIIString(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{ASCIIString}, ::ASCIIString)
  convert(::Type{ASCIIString}, ::UTF8String)
  ...
 in ascii at ascii.jl:103

julia> utf8(cstr)
ERROR: MethodError: `convert` has no method matching convert(::Type{UTF8String},
 ::Cstring)
This may have arisen from a call to the constructor UTF8String(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert(::Type{UTF8String}, ::UTF8String)
  convert(::Type{UTF8String}, ::ASCIIString)
  ...
 in utf8 at unicode/utf8.jl:233
```

cc @SimonDanisch

**Comment by ScottPJones** [comment]
Seems good to me.  If you really want to do this, you might want to also accept `Cwstring` and `Ptr{Cwchar}` for arguments to for `ascii`, `utf8`, as well as `utf16` & `utf32`.

**Comment by StefanKarpinski** [comment]
cc @stevengj

**Comment by stevengj** [comment]
Makes sense to me.

**Comment by stevengj** [comment]
`Cstring` was originally only intended for passing things *to* `ccall`, not vice-versa (where it has little or no advantage), but it is easier to understand if it works bidirectionally.

**Comment by KristofferC** [comment]
`ascii` and `utf8` no longer exists, the current way of doing things is with `unsafe_string`.
