### ISSUE TITLE
elemwise-operators of AbstractArray{T} with T?

### ISSUE THREAD

**Issue by lucasb-eyer** [JuliaLang/julia#13663]
I found it surprising that `["a", "b", "c"] .* "1"` and `["a", "b", "c"] .* ["1", "2", "3"]` don't work. I could either add that functionality explicitly for arrays of strings (maybe [here](https://github.com/JuliaLang/julia/blob/989a2f/base/strings/basic.jl#L50)), but I believe the element-wise operators should apply their operator to every element, regardless of type? This might be as simple as changing [these](https://github.com/JuliaLang/julia/blob/99fa59/base/arraymath.jl#L117) two [lines](https://github.com/JuliaLang/julia/blob/99fa59/base/arraymath.jl#L124) from

```
function ($f){T}(A::Number, B::AbstractArray{T})
# ...
function ($f){T}(A::AbstractArray{T}, B::Number)
```

to

```
function ($f){T}(A::Union{T,Number}, B::AbstractArray{T})
# ...
function ($f){T}(A::AbstractArray{T}, B::Union{T,Number})
```

I gave it a quick try and it seems to work, but I'm too inexperienced to know the repercussions this change could have. Is this wanted? If so, is this the right way?

**Comment by tkelman** [comment]
I think this would have ambiguity issues for arrays of arrays.

**Comment by fredrikekre** [comment]
```
julia> ["a", "b", "c"] .* "1"
3-element Array{String,1}:
 "a1"
 "b1"
 "c1"

julia> ["a", "b", "c"] .* ["1", "2", "3"]
3-element Array{String,1}:
 "a1"
 "b2"
 "c3"
```

**Comment by StefanKarpinski** [comment]
Yes, I think we can close this now.
