### ISSUE TITLE
Poor performance of intersect(Vector{Int}, Vector{Int})

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#13675]
```
g = [1:10_000_000;]
m = sample(1:1_000_000, 40_000, replace=false)

@time z = intersect(g,m);
196.291597 seconds (20 allocations: 1.001 MB)
```

Here are two alternate intersections. ~~The latter (isect2) does not preserve~~ neither preserves order.

```
function isect(g,m)
    is = []
    for i in m
        if i in g
            push!(is,i)
        end
    end
    return is
end

@time y = isect(g,m);
 12.880327 seconds (40.00 k allocations: 1.611 MB)


function isect2(g,m)
    is = []
    gset = Set(g)
    for i in m
        if i in gset
            push!(is,i)
        end
    end
    return is
end

@time x = isect2(g,m);
  1.430506 seconds (42.75 k allocations: 145.737 MB)

Set(z) == Set(y) == Set(x)
true
```

**Comment by stevengj** [comment]
Just use `OrderedSet` from https://github.com/JuliaLang/DataStructures.jl?

**Comment by sbromberger** [comment]
Oh, I don't care about order myself, but the notes in `Base/array.jl` indicate that one of the properties of `intersect()` on non-sets is to preserve order. I was just showing that not preserving order yields an even faster result. `isect2()` is fine in my case.

**Comment by stevengj** [comment]
The reason your `isect` function is so much faster than the [one in Base](http://www.smu.edu/Dedman/Academics/Departments/Math/Copy%20of%20Position) is probably because of the order of the loops: if you call `isect(m,g)` I'm guessing it will be about the same speed.

One optimization could be modify the `intersect` function to first sort its arguments in descending order of  `length`.   (Of course, that would require the arguments to define `length`, which is currently not required.)

(But ultimately, if you want fast `intersect`, an array is probably the wrong datastructure.)

**Comment by sbromberger** [comment]
Hmm - yes. Even so, if you're relying on preserving order with respect to g, you're hosed (you'll be getting order with respect to m, which is what `isect()` gives you).

```
julia> @time z = intersect(g,m);
190.305368 seconds (20 allocations: 1.001 MB)

julia> @time z2 = intersect(m,g);
 14.020619 seconds (20 allocations: 1.001 MB)

julia> @time x = isect2(g,m);
  1.425508 seconds (40.01 k allocations: 145.611 MB, 1.30% gc time)

julia> @time x2 = isect2(m,g);
  0.311631 seconds (40.01 k allocations: 2.174 MB)

```

As far as fast intersect, you're absolutely right, of course, but it was a case of "wow, intersect is defined on vectors!" and I used it to create induced subgraphs. Performance turned out to be horrible. Is there no compelling reason to specialize on vectors and convert the larger one to a set (`isect2()`) or check the lengths (which are defined on vectors)?

**Comment by stevengj** [comment]
Arguably, the only case (if any) in which performance of `intersect` on arrays matters is for very small arrays (e.g. < 10 elements).  (If you are doing it with huge arrays and care about performance, you should be using a different data structure.)  For very small arrays, the overhead of copying into a `Set` datastructure probably outweighs the small performance advantage of the lookups.

**Comment by eschnett** [comment]
If you don't care about order, then you may as well sort the arrays first (in-place). If the arrays are small (< 10 elements) then you can also make a copy. In any way, sorting arrays should be faster than using a set type, as sets usually support efficient insertion and deletion which you don't need.

**Comment by mwojnowicz** [comment]
@stevengj what would be a better datastructure for intersect?

**Comment by sbromberger** [comment]
@mwojnowicz I'd assume `Set`, for one.

**Comment by mwojnowicz** [comment]
good point.  thanks

**Comment by tpapp** [comment]
The issue came up recently on [Discourse](https://discourse.julialang.org/t/intersect-is-slow-for-large-arrays/442). Perhaps a docstring like this could clarify the tradeoff:
> Construct the intersection of two or more sets. Maintains order and multiplicity of the first argument for arrays and ranges, at the expense of performance. For faster performance, convert the arguments to `Set`, which does not maintain order.

Perhaps clarifying this point would allow closing the issue?

**Comment by StefanKarpinski** [comment]
@JeffBezanson, didn't you fix this recently?

**Comment by KristofferC** [comment]
```
julia> @time z = intersect(g,m);
  2.383227 seconds (40 allocations: 145.565 MiB, 3.10% gc time)

julia> @time z = intersect(m,g);
  0.908784 seconds (40 allocations: 145.565 MiB, 7.08% gc time)
```

https://github.com/JuliaLang/julia/pull/26198

**Comment by sbromberger** [comment]
Thank you for this fix!

**Comment by andreasnoack** [comment]
Do we have a benchmark for this?

**Comment by KristofferC** [comment]
https://github.com/JuliaCI/BaseBenchmarks.jl/blob/119789fd35880a90395c0c8e1565691afde94ced/src/collection/CollectionBenchmarks.jl#L202-L219 seems good enough?
