### ISSUE TITLE
Reading SharedArray from file yields incorrect result

### ISSUE THREAD

**Issue by klkeys** [JuliaLang/julia#13679]
When I use the (new?) SharedArray constructor that reads from a file, the constructor fails to load the array correctly. Compare arrays `m` and `m2` built from the following code:
```
m = ones(10)
writedlm("m.txt", m)
m2 = SharedArray(abspath(m.txt"), Float64, (10,))
```
For me, `m` is a vector of ones and `m2` contains zeros or numbers that are zero up to machine precision. Is this a bug or is this my failure to use the constructor correctly?

Version info:
````
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
````

**Comment by yuyichao** [comment]
IIUC, `SharedArray(filename)` `mmap` the the file as the (shared) storage of the array and you shouldn't use it to read array stored in arbitrary text format.

**Comment by yuyichao** [comment]
Maybe leave this open as a doc issue? The document doesn't seem to be very clear on this.....

**Comment by klkeys** [comment]
I actually wanted to tag it as a bug issue. However, I am not officially a contributor to Julia base, despite using it for almost two years. Perhaps now is the time to put on the big Julia programmer shoes...

But back to the issue at hand. Are you saying that I should be able to work around the issue by storing the array in a different format?

**Comment by yuyichao** [comment]
It seems that the file is basically a binary dump of the array but I'm not sure we'll want to make this an official interface.

**Comment by klkeys** [comment]
Okay, so for the time being should I avoid loading `SharedArray`s from file? Is there a way to get them from a standard array such that I can explicitly map it to certain processes? For the time being, an arrangement like
```
m = vec(readdlm("m.txt"))
m2 = convert(SharedArray, m)
```
should map a standard `Array` `m` into a `SharedArray` on all available processes. But I would like to choose the processes to which we map `m`, or at least explicitly map it to all processes. Something like
```
### this code doesn't work
m2 = convert(SharedArray, m, pids = procs())
```

**Comment by timholy** [comment]
`SharedArray(filename)` uses `mmap`, so the representation in RAM will be an exact copy of the contents of the file. Consequently, you can't have any formatting (e.g., writing as ASCII).

If you create the file like this:
```jl
# Warning: this creates a 1TB file
open("shared.bin", "w") do io
    for i = 1:10^6
        A = rand(UInt8, 10^6)
        write(io, A)
   end
end
```
then it should work. This feature is designed for BIG DATA (there just aren't enough caps in "Big Data"!), so a key point is that `shared.bin` can be created incrementally

> It seems that the file is basically a binary dump of the array but I'm not sure we'll want to make this an official interface.

That's the whole point. How else do you propose to distribute work on a 4TB array across multiple processes on a machine that has only 64GB RAM?

> Is there a way to get them from a standard array such that I can explicitly map it to certain processes?

@kikeys, you can create an empty SharedArray and `copy!(m2, m)`, or write an `init` function to create it in the first place.

**Comment by klkeys** [comment]
Thank you @timholy for the suggestion! The simple solution usually does the trick, it seems...

As for the original question about loading a `SharedArray` from a file, I think that I will simply avoid using that constructor for now.
