### ISSUE TITLE
Feature: C_NULL for variable type

### ISSUE THREAD

**Issue by kuldeepdhaka** [JuliaLang/julia#13674]
`C_NULL{T}(::Type{T}) = Ptr{T}(0)` 
`C_NULL() = C_NULL(Void)`
could prove more useful instead of current (C_NULL = Ptr{Void}(0))
because C_NULL is useless for Ptr{T} where T != Void

Note: `C_NULL(Void) == C_NULL` is false because C_NULL is a function now (instead of a Base.C_NULL
Note:  `C_NULL(Void) == Base.C_NULL` is true because they show same value

so, this solution is not compatible with older implementation.

side note:
also, when this C_NULL (function) is defined, no warning is shown that C_NULL (const) has been replaced.

**Comment by ihnorton** [comment]
Thanks for the suggestion, but `Ptr{T}(0)` (or `Ptr{T}(C_NULL)`) already work fine.

**Comment by kmsquire** [comment]
I actually like the suggestion (and will probably use it in my own code, at least).  

While the general trend has been to provide a single, consistent way to produce certain constructs, sometimes that results in code that is a bit less clear or more cluttered.  Having written a bit of code interfacing with C, this feels like one of those places (to me).

**Comment by wildart** [comment]
Especially when you try to get a `Cstring` null-pointer: `convert(Cstring, Ptr{UInt8}(C_NULL))`

**Comment by yuyichao** [comment]
`Ptr{UInt8}(0)` is exactly the same length with `C_NULL(UInt8)` and this proposed change makes it more verbose to actually get what is currently a `C_NULL` so that's a net increase in the number of character.

**Comment by kuldeepdhaka** [comment]
`C_NULL(UInt8)` imparting the reader the author is trying to constuct a C NULL UInt8 pointer.
current implementation of `C_NULL` is meant to be equivalent of C's NULL. but in C NULL is of void* so, anyone can assign it to other pointer types without any casting (assuming: excluding compiler extension to detect type problem).
in julia, it is not possible (no automatic casting) so, programmer is force to manually cast it.

**Comment by kuldeepdhaka** [comment]
note: there is nothing such as `NULL` in julia (currently). 
what about `NULL{T}(::Type{T} = Type{Void}) = Ptr{T}(0)`?
(no compatibility issue with `C_NULL` and shorter name :)
