### ISSUE TITLE
Command line flag to ignore __precompile__(true) 

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13693]
When debugging a segfault setting up packages on a heterogeneous cluster, it would have been nice to have a command line flag that would ignore the `__precompile__` function when loading packages instead of having to manually comment all the precompile statements out.

This is easy to do, I'm opening an issue mostly to alleviate the work to rename everything after the inevitable bikeshed.

**Comment by tkelman** [comment]
Makes sense to have this (would help with #13684), though it is getting to be a name soup of flags related to compilation. Maybe `--compilecache` if getopt doesn't have trouble with long option flags that start with the same substring?

**Comment by vtjnash** [comment]
dup of https://github.com/JuliaLang/julia/issues/13474
