### ISSUE TITLE
SSH Cluster Manager is currently not tested with Travis

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13705]
The parallel tests only seem to cover the `LocalManager` cluster manager interface.

**Comment by amitmurthy** [comment]
It is tested under JULIA_TEST_FULL=1

**Comment by amitmurthy** [comment]
The reason it is not in regular is that it requires a passwordless login to localhost. If that can be setup under Travis, we ought to be able to move it up.

**Comment by jakebolewski** [comment]
Ok I edited the issue, @tkelman do you think this is possible?

**Comment by tkelman** [comment]
No idea. Test on your fork.

**Comment by malmaud** [comment]
It could be tested in a Docker image running in Travis.
