### ISSUE TITLE
Dynamic Specification in an Inner Constructor

### ISSUE THREAD

**Issue by SloanLindsey** [JuliaLang/julia#13700]
I'm not sure if this is the correct place to ask, but I just ran into a funny issue.
I'm using an immutable as a pretty storage area for a large number of arrays though at initialization many of the arrays are degenerate so I tried to write an inner constructor that takes the kernel of interesting data and uses that to initialize all of the arrays. The catch is I don't really want to hard code the field assignments as this code may still gain new array types. Here is a sketch:

```jl
immutable ugly_structure
    field1::Array{Float64}
    field2::Array{Int}
    fieldn::BitArray
    function ugly_structure(input::some_less_ugly_structure) #where the names match between the two
        names = [x for x in fieldnames(ugly_structure)]
        declare_list = Array(Any, length(names))
        #magically populate the declare list with arrays and other immutables and many goodies
        return apply(new, declare_list) # but that doesn't work
        #neither does:
        return new(declare_list) #first element doesn't match up
        #neither does the deprecated suggested syntax 
        #WARNING: apply(f, x) is deprecated, use `f(x...)` instead
       return new(declare_list...) #yields: ERROR: LoadError: syntax: ... is not supported inside "new"
   end
end
```
So what is the Julia-correct way to do that?
Or is this an unexpected bug?

**Comment by mauro3** [comment]
Probably more suited to julia-users, if it turns out to be a bug then file here.  Best post a "almost"-runnable minimal example of what you want to achieve.

**Comment by SloanLindsey** [comment]
Will do! Thanks

**Comment by JeffBezanson** [comment]
`new` is basically magical, and not a first-class function. Unfortunately there is no good way to do this right now.

**Comment by SloanLindsey** [comment]
@JeffBezanson is there an elegant way to write a splatting wrapper?

**Comment by yuyichao** [comment]
You could use `@generated`. Not sure if it is elegant....

**Comment by SloanLindsey** [comment]
Hmm, off to RTFM. I came across that macro in the last few days; I'm still not positive of its use.

**Comment by yuyichao** [comment]
(See the link in my updated comment)

**Comment by SloanLindsey** [comment]
You pointed me in that direction, I'm going to try to learn how to generate and evaluate these expressions with metaprogramming (the link looks very useful).

BTW, here is a "compact" failing example.

```jl
#apply new troubles

immutable Vec3
  x::Float64
  y::Float64
  z::Float64
end

immutable Min_Discription
  postion::Array{Vec3}
  valid::Bool
  angry_butter_fly_quotient::Float64
end

immutable Positive_Vec
  position::Array{Vec3}
  positive::BitArray
  valid::BitArray
  angry_butter_fly_quotient::Array{Float64}

  function Positive_Vec(elves::Array{Min_Discription})
    size = length(elves) 
    #automagically initialize all the data!
    defaults=((Type{Array{Vec3}},Vec3,null_pos),
              (Type{Array{Int}},Int, -1),
              (Type{BitArray},Bool,false),
              (Type{Array{Float64}},Float64, -Inf))

      data_types = [fieldtype(Positive_Vec,x) for x in fieldnames(Positive_Vec)]
      declare_list = Array(Any,length(data_types))

      for i in 1:length(data_types)
        for (d_type,primitive, default) in defaults
          if d_type == data_types[i]
            if d_type != Type{BitArray}
              declare_list[i] = Array(primitive, size)
              fill!(declare_list[i], default)
            else
              declare_list[i] = BitArray(size)
              fill!(declare_list[i], default)
            end
          end
        end
      end
      #defaults populated. Now overwrite data passed in
      for entry in fieldnames(Min_Discription)
        for (name,index) in enumerate(fieldnames(Positive_Vec))
          if entry==name
            for (elf,i) in enumerate(elves)
              declare_list[index][i]=elf.(entry)
            end
          end
        end
      end
      #now we worry about a few special cases


      for (symbol, index) in enumerate(fieldnames(Positive_Vec))
        name = string(symbol)
        if name=="positive"       # set the size of the structure
          for i in 1:length(elves)
            declare_list[index][i] = elves[i].position.z>0.0
          end
        end
      end
      return new(declare_list...)#apply(new, declare_list)
    end

end

  a = Min_Discription(Vec3(0.0,0.0,0.0),true,73.27113)
  b = Min_Discription(Vec3(0.0,0.31,1.0),true,892.73165)
  c = Min_Discription(Vec3(0.8364,7.4,500.0),true,4.0)

  elves = Array(Min_Discription,3)
  elves[1],elves[2],elves[3]= a,b,c
  Positive_Vec(ions)

```

julia> include("apply_new_troubles.jl")
ERROR: LoadError: syntax: ... is not supported inside "new"
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304

**Comment by simonster** [comment]
Interpolating `Expr(:new, ...)` into an AST is probably not a great idea. The codegen decides whether or not fields can be undefined based on what the inner constructor does, so if you use `Expr(:new, ...)` to get around having to define the inner constructor in a way the frontend understands, you might end up creating objects with fields that are undefined when the codegen thinks they should always be defined.

In this particular case, it seems like all of the fields are always defined, so you could use an outer constructor instead of an inner constructor.

**Comment by SloanLindsey** [comment]
All the fields are not defined from outside (positive is the example here, but in the code that its based on its closer to 10 variables). Also the goal for me of the structure is to be able to update and replace the whole collection of data by calling a constructor that either takes a Min_Discription, or a Positive_Vec, and be reasonably sure that the data structure is in a valid state after each update.
