### ISSUE TITLE
ARPACKException with eigs

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#13709]
On v0.4 I see the following:
```
julia> for i = 1:100
           A = randn(256,256)
           λ,v = eigs(A,nev=1,which=:LM)
           println(λ)
       end
Complex{Float64}[-5.403315222231397 + 16.446255603922936im]
Complex{Float64}[-16.83827451218431 + 0.0im]
Complex{Float64}[-2.395397568451567 + 16.123526196663914im]
Complex{Float64}[-12.39397801177645 + 11.304084721268927im]
Complex{Float64}[-12.27303495097507 + 11.832055786740451im]
Complex{Float64}[-7.908468037577425 + 14.731418350155243im]
Complex{Float64}[-16.470027322364675 + 0.0im]
Complex{Float64}[-16.99591969718958 + 0.0im]
Complex{Float64}[-8.513801628913438 + 14.190942988032592im]
Complex{Float64}[-14.123131553900631 + 9.55200192151935im]
Complex{Float64}[15.2472765341005 + 7.023088970503387im]
ERROR: Base.LinAlg.ARPACKException(-14)
 in eupd_wrapper at ./linalg/arpack.jl:165
```
I discovered this while investigating a bug where my code hangs while calling `eigs` in this way, so I'm hoping this is related.

**Comment by StefanKarpinski** [comment]
I'm seeing this too.

**Comment by andreasnoack** [comment]
The error is exaplained in the Fortran source https://github.com/opencollab/arpack-ng/blob/master/SRC/dneupd.f#L207-L208. We should probably report the error messages instead of just the numbers.

**Comment by ViralBShah** [comment]
Happens on 0.3 too.

**Comment by ViralBShah** [comment]
BTW, is this an error, or does it need more iterations?

**Comment by andreasnoack** [comment]
The error message is "did not find any eigenvalues to sufficient accuracy" so more iterations might help.

**Comment by andreasnoack** [comment]
It helps to increase the number of iterations, but it only makes the error less frequent. We could consider  an error message where we suggest to try a new stating vector and/or to increase the number of iterations. That would be quite a bit more helpful than `ARPACKException(-14)`.

**Comment by jiahao** [comment]
In such situations it can also help to increase the number of Arnoldi vectors or number of desired eigenpairs. However, there will always be matrices with "bad" spectral properties that Arnoldi will always struggle with and there's really nothing that a user can do about it.

**Comment by ViralBShah** [comment]
I agree that a better error and potential things the user could do would be useful.

**Comment by andreasnoack** [comment]
Like @jiahao proposed, I think the main issue is that, for some matrices, the subspace is not big enough so the recommendation should probably be to make the subspace larger. For what it's worth, Matlab also fails on this and gives the error message cited above.

It's annoying that ARPACK defines an iteration as one traversal through the subspace and that convergence is only checked after such a traversal. I'm increasingly sceptical about the restart business. It's usually much slower than keeping all the vectors so I think many people would like to use the extra memory to get a solution and get it fast. Of course you don't want to swap, so when we roll our own Lanczos implementation it might be more transparent to provide a memory budget than a subspace size.

**Comment by ViralBShah** [comment]
We do allow the user to specify `ncv`. That should do it right, if I am understanding correctly. The error message could suggest the user increase `ncv` and run again.
