### ISSUE TITLE
Rename getaddrinfo, gethostname, getipaddr, getsockname?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13715]
Currently most of the networking code uses a "getter" naming scheme that clashes with the convention most widely used in Base.  I always forget this.

Is there popular support for deprecating these names and renaming them to `addrinfo`, `hostname`, `ipaddr`, `sockname`?

**Comment by tkelman** [comment]
+1. If these aren't in a `Networking` module, should they be?

**Comment by StefanKarpinski** [comment]
Maybe call it `Net` or `Network` instead of `Networking`?

**Comment by vtjnash** [comment]
to play devil's advocate, these are the posix names for them (not that posix will ever be accused of consistency)

**Comment by JeffBezanson** [comment]
Part of #20371
