### ISSUE TITLE
keyword arguments of Pkg.checkout aren't documented

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#13723]
Just ran into this so leaving as a reminder.

**Comment by kshyatt** [comment]
The relevant lines are [here](https://github.com/JuliaLang/julia/blob/6adbbed4eead0f9ba886e847e6baa311f429ad72/base/pkg.jl#L40), I think. This would make a great first time contribution for anyone. Please don't hesitate to ask for help if you want it.

**Comment by rohitvarkey** [comment]
I think this can be closed now?
