### ISSUE TITLE
Feature request: Literal special cases

### ISSUE THREAD

**Issue by Synthetica9** [JuliaLang/julia#13721]
With Julia's overloading, it would be nice to see support for literally declared special cases. It would make for more readable recursive definitions (especially to non-programmers reading) your code. One would go from the following:

``` Julia
function fib(n::Integer)
  if n == 0 || n == 1
    return n
  else
    return fib(n - 1) + fib(n + 1)
  end
end
```

(Or the more compact, but even less readable `fib(n::Integer) = (n == 0 || n == 1) ? n : fib(n - 1) + fib(n - 2)`)
To the following:

``` Julia
fib(0) = 0
fib(1) = 1
fib(n::Integer) = fib(n-1) + fib(n-2)
```

Currently, when one tries this, it is greeted (as expected) with a syntax error:

```
julia> fib(0) = 0
ERROR: syntax: "0" is not a valid function argument name
```

What are your thoughts on this?

**Comment by JeffBezanson** [comment]
See https://github.com/toivoh/PatternDispatch.jl for a good and appropriately general implementation of this.

I don't find this feature all that compelling. I don't think there are that many cases where you want a separate definition for a literal number, plus this creates confusion about what can actually be dispatched on.

**Comment by KristofferC** [comment]
Exist in a package and not likely to happen in Base.
