### ISSUE TITLE
Code with errors does not stop when run in parallel in 0.4.0

### ISSUE THREAD

**Issue by 315234** [JuliaLang/julia#13730]
$ cat bug.jl

```julia
t = 0.0
@sync @parallel for i=1:10
    t.nonexistent # should error out, but dies silently
end
pmap(x->t.nonexistent, [0,1,2]) # also no error
pmap(x->t.nonexistent, [0,1,2]; err_stop=true) # also no error
#t.nonexistent # error if uncommented
```

    $ julia --version
    julia version 0.3.10

    $ julia bug.jl
    exception on 1: ERROR: type Float64 has no field nonexistent
     in anonymous at no file:3
     in anonymous at multi.jl:1279
     in run_work_thunk at multi.jl:621
     in run_work_thunk at multi.jl:630
     in anonymous at task.jl:6
    exception on 1: ERROR: type Float64 has no field nonexistent
     in anonymous at /home/tbm/phd/IntegrateScalars_bugfind/bug.jl:5
     in anonymous at multi.jl:660
     in run_work_thunk at multi.jl:621
     in remotecall_fetch at multi.jl:694
     in remotecall_fetch at multi.jl:709
     in anonymous at task.jl:1361
    exception on 1: ERROR: type Float64 has no field nonexistent
     in anonymous at /home/tbm/phd/IntegrateScalars_bugfind/bug.jl:6
     in anonymous at multi.jl:660
     in run_work_thunk at multi.jl:621
     in remotecall_fetch at multi.jl:694
     in remotecall_fetch at multi.jl:709
     in anonymous at task.jl:1361

    $ ~/opt/julia-0.4/bin/julia --version
    julia version 0.4.0

    $ ~/opt/julia-0.4/bin/julia bug.jl

This last command shows no output. Uncommenting the last line in `bug.jl` results in the following output:

    ERROR: LoadError: type Float64 has no field nonexistent
     in include at ./boot.jl:261
     in include_from_node1 at ./loading.jl:304
     in process_options at ./client.jl:308
     in _start at ./client.jl:411
    while loading /home/tbm/phd/IntegrateScalars_bugfind/julia_bug.jl, in expression starting on line 7

**Comment by JeffBezanson** [comment]
It looks like now `fetch` propagates exceptions, but `wait` doesn't. I think they both should. cc @amitmurthy
