### ISSUE TITLE
confusing code_warntype output on intrinsic calls

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13734]
For example

```
julia> @code_warntype 1.0+1.0
Variables:
  x::Float64
  y::Float64

Body:
  begin  # float.jl, line 204:
      return (Base.box)(Base.Float64,(Base.add_float)(x::Float64,y::Float64)::Any)::Float64
  end::Float64
```

There's an `Any` in there because we don't put types on calls to intrinsics, so you just get the default. There is no performance problem here.

**Comment by yuyichao** [comment]
Isn't this fixed by https://github.com/JuliaLang/julia/pull/13571 ?

**Comment by yuyichao** [comment]
Also seems to be dup of #13568

**Comment by JeffBezanson** [comment]
Yes, I must have been looking at an older commit.
