### ISSUE TITLE
Implement muladd for general types

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#13748]
I would expect the fallback 

```julia
 muladd(a,b,c)=a*b+c
```

to be implemented, but that's not the case:
```julia
julia> type Foo x end
julia> import Base.+;+(f::Foo,g::Foo)=Foo(f.x+g.x)
julia> import Base.*;*(f::Foo,g::Foo)=Foo(f.x*g.x)
julia> muladd(Foo(5),Foo(6),Foo(3))
ERROR: MethodError: `muladd` has no method matching muladd(::Foo, ::Foo, ::Foo)
```

**Comment by yuyichao** [comment]
It is working for `Number`.

```julia
julia> type Foo <: Number
           x
       end

julia> import Base: +, *

julia> +(f::Foo, g::Foo) = Foo(f.x + g.x)
+ (generic function with 175 methods)

julia> *(f::Foo, g::Foo) = Foo(f.x * g.x)
* (generic function with 143 methods)

julia> muladd(Foo(5), Foo(6), Foo(7))
Foo(37)
```

Should we just remove the constraint on it?

**Comment by eschnett** [comment]
Since there are types that implement both `*` and `+` in the sense of an algebra, and these types are not a `Number`, then yes, this constraint should be removed. `Matrix` is an example.

As a follow-on, special cases mapping e.g. `muladd` to `daxpy` and friends could make sense.

**Comment by stevengj** [comment]
+1 for an untyped `muladd(a,b,c)=a*b+c` fallback.

**Comment by JeffreySarnoff** [comment]
+1 for an untyped muladd(a,b,c)=a*b+c fallback.

**Comment by simonster** [comment]
What is the desired behavior if `x`, `y`, and `z` are arrays?

**Comment by dlfivefifty** [comment]
x*y + z?

**Comment by stevengj** [comment]
I think it should be x*y+z. If those operations aren't defined, then it will throw an exception. There is no place for a vectorized (elementwise) variant.
