### ISSUE TITLE
Latex Formula and Interpolation results in Error

### ISSUE THREAD

**Issue by dmoliveira** [JuliaLang/julia#13759]
I don't know if this problem was already solved, but using julia v.4.0.1+pre8 I can't use this call to print my optimization solution:

```
display(md"$x_{1}$ = $(getValue(x1))")
```

I get the following error:

```
LoadError: MethodError: `latexinline` has no method matching latexinline(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Float64)
Closest candidates are:
  latexinline(::IO, !Matched::Base.Markdown.LaTeX)
  latexinline(::IO, !Matched::Base.Markdown.Code)
  latexinline(::IO, !Matched::Array{T,1})
  ...
while loading In[41], in expression starting on line 19

 in latex at markdown/render/latex.jl:50
 in latex at markdown/render/latex.jl:23
 in writemime at markdown/render/latex.jl:139
 in sprint at iostream.jl:206
 in display_dict at /Users/diego/.julia/v0.4/IJulia/src/execute_request.jl:42
 in display at /Users/diego/.julia/v0.4/IJulia/src/inline.jl:35
 in display at multimedia.jl:151
```

I try to escape the $$ from latex but achieved no success. I'm guessing that due to `$` has different semantic at the same line for render latex formula and interpolation it is resulting in compiling error. My polite and more simple solution for this could be implementing the concat method for `md` strings or `md` and `AbstractString`.

e.g.,

```
md"$x_{1}$ " * "$(getValue(x1))"
```

Best,

**Comment by kshyatt** [comment]
This doesn't error anymore, works in the REPL. Feel free to reopen if it's not "fixed" enough.
