### ISSUE TITLE
Move logm warning "Matrix with nonpositive real eigenvalues…" to help documentation?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#13750]
`logm` gives a warning

```julia
julia> logm([1 2;3 4])
WARNING: Matrix with nonpositive real eigenvalues, a nonprincipal matrix logarithm will be returned.
2x2 Array{Complex{Float64},2}:
 -0.35044+2.39112im  0.929351-1.09376im 
  1.39403-1.64064im   1.04359+0.750475im
```

This warning can get annoying.  Since this behaviour is standard and consistent, I think it would make more sense for it to be described in the help documentation for `logm`

**Comment by StefanKarpinski** [comment]
Agree. Runtime warnings are not the way to go here.
