### ISSUE TITLE
llvm.dbg.value missing llvm Verifier pass for SROA

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13754]
Right now on LLVM 3.7, we crash at the end of boostrap with a whole bunch of error message similar to

```
piece covers entire variable
  call void @llvm.dbg.value(metadata i64 1, i64 0, metadata !23687, metadata !23692), !dbg !23688
!23687 = !DILocalVariable(tag: DW_TAG_auto_variable, name: "#s286", scope: !2295, file: !2293, line: 10, type: !9)
!23692 = !DIExpression(DW_OP_bit_piece, 0, 64)
```

This was notes by @yuyichao in https://github.com/JuliaLang/julia/commit/84a0bc0be585aed64a40a9c1f0deab6366b68e3c#commitcomment-13941754.
I have filed this upstream as https://llvm.org/bugs/show_bug.cgi?id=25308 with a reduced test case.

**Comment by Keno** [comment]
Ok, looking at the reduced test case more closely. This seems to just be our sloppiness about emitting debug info for unboxed types catching up with us. I think the action items are two things:
1. Teach the LLVM Verifier to detect this case (to make sure we don't accidentally end up here again as LLVM passes get better)
2. Fix our emitted debug info

**Comment by tkelman** [comment]
Crash is fixed. Close, or rename for remaining todo?

**Comment by Keno** [comment]
Keep open until I get the Verifier fixes upstream

**Comment by Keno** [comment]
Verifier changes are here: http://reviews.llvm.org/D14276

**Comment by Keno** [comment]
https://github.com/llvm-mirror/llvm/commit/621b821be39fd90df9f1e79678444f75c3c6a88a

**Comment by Keno** [comment]
Aannd, I broke Chrome. Reverted pending investigation.

**Comment by tkelman** [comment]
Extra points for style. If you're going to break something, may as well aim big.

**Comment by Keno** [comment]
I'll go for the Linux kernel next.

**Comment by StefanKarpinski** [comment]
Can you compile the kernel with Clang?

**Comment by Keno** [comment]
Ish: http://llvm.linuxfoundation.org/index.php/Main_Page

**Comment by tkelman** [comment]
Did this get re-applied in a way that didn't break Chrome?

**Comment by Keno** [comment]
No, still pending. I'll get back to it when I have a chance.

**Comment by KristofferC** [comment]
Still relevant?
