### ISSUE TITLE
New combination method to generate combinations of all sizes

### ISSUE THREAD

**Issue by gajomi** [JuliaLang/julia#13767]
I's like to suggest that base Julia defines a combination method that generates combinations of all orders. The implementation would have essentially the same behavior as the following:
```julia
using Iterators
Base.combinations(a) = chain([combinations(a,k) for k=1:length(a)]...)
```
which allows for things like
```julia
julia>collect(combinations("abc"))
['a']        
 ['b']        
 ['c']        
 ['a','b']    
 ['a','c']    
 ['b','c']    
 ['a','b','c']
```
This pattern would be analogous to the `partitions(m)`/`partitions(m,n)` behavior that already exists. This is a patterns that I have used in Julia recently and have implemented perhaps half a dozen times in various languages over the years. With the problem of iterating over orders being widespread in both theoretical calculations and experimental design, I suspect I am not the only one to use something like this.

**Comment by tkelman** [comment]
I don't think this needs to be in base, but Iterators.jl might make sense as a home for it.

**Comment by JeffBezanson** [comment]
See #11308 --- I think this should go in Combinatorics,jl.

**Comment by gajomi** [comment]
Sounds good. I'll close issue here and open in Combinatorics.
