### ISSUE TITLE
make full-source-dist excludes LLVM from git

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#13766]
I was trying to create a tarball of a version of julia which uses a custom llvm. Unfortunately, `make full-source-dist` does not include LLVM in that case.

**Comment by Keno** [comment]
Also, the Make.user file. Though it should probably print a big warning if that's present (or maybe we need a separate option for that?).

**Comment by tkelman** [comment]
I think if llvm were using the `git-external` mechanism this would work, but the llvm mirror doesn't seem to have release tags, and I think for normal building a clone of all of llvm is a bit overkill.

**Comment by mbauman** [comment]
Is this still relevant?

**Comment by vtjnash** [comment]
Not really. We do end up defining that full-source-tallball means DEPS_GIT=0, so it is not supported, but also doesn't seem to be needed much
