### ISSUE TITLE
Incorrect docstring with erroneous  `?` in REPL help mode

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#13761]
Accidently typed a `?` when already at help mode and got this strange result

```
help?> ?@parallel
  *(x, y...)

  Multiplication operator. x*y*z*... calls this function with all arguments, i.e. *(x, y, z, ...).
```

**Comment by jiahao** [comment]
It might be a lookup issue. Same thing happens with `?@!` and a bunch of things I tried that start with `?@`.

**Comment by yuyichao** [comment]
It's an multiplication

```jl
julia> :(?@parallel)
:((?) * @parallel())
```

**Comment by jiahao** [comment]
Oh, so it's #1910 #6286 again

**Comment by malmaud** [comment]
Ah yes, now it makes sense.

**Comment by KristofferC** [comment]
This now gives:

```jl
help?> ?@parallel
ERROR: ArgumentError: wrong number of arguments to @parallel
```

Is that good enough to close?

**Comment by martinholters** [comment]
As long as we want to keep the parsing of  `:(?@parallel)` to be the multiplication by juxtaposition, this is probably as good as it gets without any special-casing. Note that if `@parallel` is replaced by a macro takes accepts zero arguments, the error becomes
```
ERROR: UndefVarError: ? not defined
```

**Comment by KristofferC** [comment]
This has not really anything to do with the docsystem then. Also giving an error that points to the `?` is good since the user will then likely find the error.
