### ISSUE TITLE
Suggestion: better explanations of each benchmark

### ISSUE THREAD

**Issue by grinsted** [JuliaLang/julia#13770]
Nevertheless, I just showed Julia to a python guy, and his reaction to one of the perf tests were: *"you'd never do it like that in python"*. I am sure that is a common reaction. So, for that reason i think it would be good for julia to add more explanation somewhere. (I am not complaining about the explanation of the tests which is already there on the front page. - i think that is good) Something along the lines of: 

> ## fib: function calls and recursion
> 
> The Fib test is designed to test how the language performs when it has to make many function calls in a recursive loop. The test is implemented as a straight-forward recursive implementation of the Fibonacci sequence in all languages. The algorithm itself is exceedingly simple, and the primary performance bottleneck being measured is the overhead associated with the function calls themselves.

It would be great if this explanation would be easily accessible from the julialang.org frontpage benchmark table. E.g. a hover box for each row in the performance table (or maybe just add an info link per row). It would also be good to make these explanations visible in the source code for all languages. It could be a link a new markdown file here:
https://github.com/JuliaLang/julia/tree/master/test/perf/micro

**Comment by ViralBShah** [comment]
Closing since this is a well discussed topic on the mailing list and in various issues. PRs to the Julia website with these improvements are certainly welcome.

**Comment by ihnorton** [comment]
Next time, ask this person if they have written a ufunc for NumPy.
