### ISSUE TITLE
`collect(countfrom())` hangs

### ISSUE THREAD

**Issue by my-little-repository** [JuliaLang/julia#13771]
`collect(countfrom())` hangs at the repl. Shouldn't it return an error instead? Countfrom() returns an object of type Base.Count which has a `done` method that always return false. This probably means that collect should fail for all arguments having such a type.

**Comment by JeffBezanson** [comment]
I don't see much value in adding a special case for this.

**Comment by my-little-repository** [comment]
Good error reports seem valuable to me. Especially when they catch a non-terminating clause in a program. It is not just for the `countfrom` method. As far as I understand, the Base.Count type is used for computations that do not return by themselves.

**Comment by StefanKarpinski** [comment]
It's always possible to write non-terminating programs in any Turing complete language? How is this different from someone writing `while true; end`? Should we start special casing lots of non-terminating patterns? Seems like a fool's errand.

**Comment by KristofferC** [comment]
This now gives an error and `countfrom` is deprecated.
