### ISSUE TITLE
Implicit multiplication with an operator symbol does not work

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#13785]
Implicit multiplication
```julia

import Base.*
type DownArrow end

↓ = DownArrow()
*(n, x::DownArrow) = "product of $n and DownArrow"
```
Typing `2*↓` works, and we get
```julia
julia> parse("2*↓")
:(2↓)

julia> dump(parse("2*↓"))
Expr 
  head: Symbol call
  args: Array(Any,(3,))
    1: Symbol *
    2: Int64 2
    3: Symbol ↓
  typ: Any
```
However,  `2↓` is an unfinished expression:
```julia
julia> dump(parse("2↓"))
Expr 
  head: Symbol incomplete
  args: Array(Any,(1,))
    1: ASCIIString "incomplete: premature end of input"
  typ: Any
```
However, `α = DownArrow()` allows `2α` without problems.

[This is not just idle -- we are looking for good syntax for unums with @alanedelman.]

**Comment by jakebolewski** [comment]
Juxtaposed multiplication does not work with any operator defined in `julia-parser.scm`

**Comment by jakebolewski** [comment]
I don't think this can work at all, given that juxtaposed multiplication relies on the identifer not being a operator to disambiguate the parse.

**Comment by JeffBezanson** [comment]
I agree; I don't think we will support implicit multiplication with an operator. I suppose another option is to have `↓` not be an infix operator, but that seems arbitrary given its unicode category.

**Comment by dpsanders** [comment]
I didn't realise that `↓` was parsed as an infix operator. 

I have made a list of available symbols (i.e. those not in `julia-parser.scm`) [here](https://github.com/dpsanders/SimpleUnums.jl/blob/master/Available%20symbols.ipynb).

How can I now reduce this to only those which are also allowed to be names of variables?

**Comment by jakebolewski** [comment]
`↓` can be a valid variable name, just not used in a juxtaposed position.  See `juxtapose?` function in julia-parser.scm to see which tokens (symbols) cannot be used in a juxtaposed position.
