### ISSUE TITLE
Markdown parser doesn't ignore leading whitespace in list items

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#13789]
```
julia> Markdown.parse("""
       * A simple list
         split over
         three lines
       """)
    •  A simple list   split over   three lines
```
As I understand it, indentation matching the initial list item should be ignored, rather than converted into multiple spaces.  e.g. here is how Github renders the same list:

* A simple list
   split over
   three lines

In fact, Github seems to ignore any amount of leading whitespace in the list items.   On the other hand, Jupyter renders a code block if you indent by an extra four spaces beyond the W+1 spaces for a list marker of width W plus one space:
```
* A simple list
  split over
  three lines
  
* A simple list
      with code
```
is rendered as:
![image](https://cloud.githubusercontent.com/assets/2913679/10763263/a96f7d52-7c9f-11e5-8207-a1c99b74b351.png)

As I understand the [commonmark spec](http://spec.commonmark.org/0.22/#list-items), Jupyter's behavior seems the more correct one:

**Comment by stevengj** [comment]
(I noticed this in #13780.)

**Comment by hayd** [comment]
Part of the issue is that html ignores multiple whitespaces. IMO we should do the same when rendering markdown in the repl.

Note: You can compare markdown implementations with [babelmark2](http://johnmacfarlane.net/babelmark2/?text=*+A+simple+list%0A++split+over%0A++three+lines).

[Indentation immediately after a list *never* becomes code in commonmark.](http://johnmacfarlane.net/babelmark2/?text=*+A+simple+list%0A++++++++++++++++with+code), so potentially that's a Jupyter bug.

**Comment by stevengj** [comment]
@hayd, I agree that when rendering non-code cells, we should ignore multiple whitespace.  That would fix this issue.

**Comment by hayd** [comment]
I think this can be patched by regex replacing multiple whitespace [here](https://github.com/JuliaLang/julia/blob/f8a4340548e7d6be31fede13cdc4e0f5f434f33f/base/markdown/render/terminal/render.jl#L96):

```
function terminline(io::IO, md::AbstractString)
    print(io, replace(md, r"[\s\t\n]+", " "))
end
```
This feels a little hacky, so let's ping @one-more-minute :)

**Comment by hayd** [comment]
Pushed a PR to fix as above.

One weird thing (unrelated to my PR, but similar to the example above) is that quote has different behaviour:
```
julia> Markdown.parse("- a\n b")
    •  a b

julia> Markdown.parse("> a\n b")
  |  a

  b
```

i.e. the next line doesn't count as part of the quote ([it should](http://johnmacfarlane.net/babelmark2/?text=%3E+a%0Ab)).

**Comment by hayd** [comment]
I was looking at the quote part the other day, it seems that quote parse needs to know which characters should start a fresh block... I can't see a way around hardcoding what line starts can escape quote. 

Related: I think we ought not allow • instead of - to construct a list, it's not markdown.
