### ISSUE TITLE
A \ b slow for triangular sparse matrix.

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#13792]
Julia 0.4

```{julia}
# Make a lower triangular sparse matrix that is invertible.
A = tril(sprand(1000, 1000, 0.005) + 10.0 * speye(1000, 1000))
p1 = randn(1000)
# lu form
B = lufact(A);
p2 = copy(p1);
# Explicit lower triangular form.
C = LowerTriangular(A);

@time A \ p1   300us   # LU
@time B \ p1   120us   # Already LUed
@time C \ p1   7000us # Slow substitution

p2 = copy(p1)
@time A_ldiv_B!(A, p2)  20us # Fast substitution
p2 = copy(p1)
@time A_ldiv_B!(B, p2)  120us # Already LUed
p2 = copy(p1)
@time A_ldiv_B!(C, p2)  7000us # Slow substitution
```

The fastest version is [`A_ldiv_B!(A, p2)`](https://github.com/JuliaLang/julia/blob/0ff703b40afddf9b705bd6a06d3a59cb4c089ea5/base/sparse/linalg.jl#L169) which checks if triangular `istril` and then uses a direct substitution method. However the wrapper `A \ p1` doesn't make use of it at all, instead it defaults to factorize `A`.

The slowest version is [`A_ldiv_B!(C, p2)`](https://github.com/JuliaLang/julia/blob/0ff703b40afddf9b705bd6a06d3a59cb4c089ea5/base/linalg/bidiag.jl#L206) which also uses a substitution method using `naivesub!`. Unfortunately this version is very slow.

In the current master branch, the fastest direct method is deleted, I am wondering if the slowest version was improved.

**Comment by andreasnoack** [comment]
Thanks for reporting this. I've updated the title such it is clear that the issue is the sparse solve. We should look into why we are slower than UMFPACK for the triangular solve.
