### ISSUE TITLE
add completion-at-point-functions support for completing Julia keywords.

### ISSUE THREAD

**Issue by stardiviner** [JuliaLang/julia#13799]
ESS-Julia part has a mode called `ess-julia-mode`. It is derived from `julia-mode`. This seems from Julia.
ESS-Julia support completing objects with `company-ess-julia-objects` for `company-mode`.
Emacs has default completion support with `completion-at-point-functions`. It can be used by `company-mode` with backend `company-capf`. I hope `julia-mode` can complete Julia keywords with a function which add to `completion-at-point-functions`.
```lisp
(add-hook 'completion-at-point-functions 'julia-complete-keywords-function)
```

**Comment by yuyichao** [comment]
Moved to https://github.com/JuliaLang/julia-emacs/issues/8
