### ISSUE TITLE
Generate package documentation from docstrings

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#13790]
Having recently gone through the updating of several packages for 0.4 and trying out the new doc system, I first have to say, I love it! Much kudos to everyone who put in so much effort to build and make the transition.

As an extension to the wonderful new functionality, I find myself wanting to document the daylight out of my packages, but then find myself in an awkward position when I go to write my package's `README`. Do I duplicate everything? (tedious) Do I just point users to the help system? (not ideal since it's hard to quickly skim over an entire package's contents).

I find myself wishing there was a quick script I could call on my package that would auto-generate a README from the combined docstrings in my package.

I think this would be a great little piece of functionality that would probably be pretty approachable for anyone interested in giving it a go.

I file the issue here, mainly because I'm not exactly sure where this would live. On the one hand, this could obviously go in a package by itself that package developers would then simply install and use. On the other hand, I could see this being something we include with our batteries for new bare packages, a single `generate_docs.jl` script that we maybe build into the package manager itself via `Pkg.docs(pkg)` or something like that. Happy to discuss more and get more concrete, but wanted to get the ball running for now.

**Comment by hayd** [comment]
@MichaelHatherly is building something out for Documentation (and README) generation from docstrings in [Docile's rewrite branch](https://github.com/MichaelHatherly/Docile.jl/tree/rewrite).

**Comment by spencerlyon2** [comment]
@quinnj have you seen [Lexicon.jl](https://github.com/MichaelHatherly/Lexicon.jl)? 

Is this what you had in mind?

**Comment by hayd** [comment]
My understanding is that Lexicon is going to be deprecated and rolled into the new Docile (both projects are by @MichaelHatherly).

**Comment by MichaelHatherly** [comment]
> My understanding is that Lexicon is going to be deprecated and rolled into the new Docile

Yes, that's the plan at the moment.

**Comment by MichaelHatherly** [comment]
(Just dropping a breadcrumb to the current work being done on this by @mortenpi and myself for anyone that comes across this issue: https://github.com/JuliaDocs/Documenter.jl)

**Comment by tkelman** [comment]
I think if you registered that we could call this closed. Is there a minimal skeleton worth setting up as part of `PkgDev.generate` ?

**Comment by MichaelHatherly** [comment]
Morten added https://github.com/JuliaDocs/Documenter.jl/pull/66 last week which could just be ported over to `PkgDev`.

There's a couple of outstanding issue that need closing before registering, but after that I'll close this.

**Comment by MichaelHatherly** [comment]
Closed by https://github.com/JuliaLang/METADATA.jl/pull/5396.
