### ISSUE TITLE
A \ b slow for triangular matrix.

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#13791]
Julia 0.4

```{julia}
# Make a lower triangular sparse matrix that is invertible.
A = tril(sprand(1000, 1000, 0.005) + 10.0 * speye(1000, 1000))
p1 = randn(1000)
# lu form
B = lufact(A);
p2 = copy(p1);
# Explicit lower triangular form.
C = LowerTriangular(A);

@time A \ p1   300us   
@time B \ p1   120us
@time C \ p1   7000us

p2 = copy(p1)
@time A_ldiv_B!(A, p2)  20us
p2 = copy(p1)
@time A_ldiv_B!(B, p2)  120us
p2 = copy(p1)
@time A_ldiv_B!(C, p2)  7000us
```

The fastest version is [`A_ldiv_B!(A, p2)`](https://github.com/JuliaLang/julia/blob/0ff703b40afddf9b705bd6a06d3a59cb4c089ea5/base/sparse/linalg.jl#L169) which checks if triangular `istril` and then uses a direct substitution method. However the wrapper `A \ p1` doesn't make use of it at all as it defaults to factorize `A`.

The slowest version is [`A_ldiv_B!(C, p2)`](https://github.com/JuliaLang/julia/blob/0ff703b40afddf9b705bd6a06d3a59cb4c089ea5/base/linalg/bidiag.jl#L206) which also uses a substitution method using `naivesub!`. Unfortunately this version is very slow.

In the current master branch, the fastest direct method is deleted, I am wondering if the slowest version was improved.

**Comment by StefanKarpinski** [comment]
dup of https://github.com/JuliaLang/julia/issues/13792

**Comment by colinfang** [comment]
Sorry, carelessly hit "create a new issue" while editing.
