### ISSUE TITLE
The HTTPS certificate of https://status.julialang.org/ expired

### ISSUE THREAD

**Issue by Luthaf** [JuliaLang/julia#13801]
And this make all the Travis builds fails: cf https://travis-ci.org/chemfiles/Chemfiles.jl/jobs/87884125

@tkelman @ninjin @staticfloat

**Comment by tkelman** [comment]
@staticfloat given how little time you appear to have for julia lately, could you send all necessary dns administration info to @ViralBShah and @StefanKarpinski so we can get these things transferred to a place where multiple people can fix them?

**Comment by StefanKarpinski** [comment]
I've actually been the bottleneck here – this required coordination between me and Elliot, which was proving elusive. We set things up now so that cert-related emails get automatically forwarded automatically, which removes the coordination problem.

**Comment by staticfloat** [comment]
And here I was, thinking I was all clever getting it done beforehand.
Turns out I mixed up the new/old certificate files, and just reinstalled
the old cert files.  Fixed now.
-E

**Comment by Luthaf** [comment]
I confirm the fix!

**Comment by malmaud** [comment]
Soon https://letsencrypt.org/ will be generally available and might be an attractive low-maintenace solution for certs.

**Comment by staticfloat** [comment]
Yes, I'm definitely going to switch over to that once its available.
-E

**Comment by ViralBShah** [comment]
That is good to know!

**Comment by ViralBShah** [comment]
Cc @tanmaykm
