### ISSUE TITLE
logabsdet for complex matrices

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#13823]
`logabsdet` is a function that returns `(log(abs(det(M))), sign(det(M))` but may provide increased accuracy and/or speed (and is less likely to overflow).  At the moment it [works only for real matrices](https://github.com/JuliaLang/julia/blob/40e16bf249a507e8cc4ab1c900de6e8302d56fba/base/linalg/lu.jl#L167-L190), but I believe it would be great if it were implemented also for complex matrices.

From glancing at the code (and earlier discussion at #3070), I see no reason it cannot work for complex matrices as well.  Note that julia's `sign` function is indeed implemented for complex numbers, so the interface can be exactly equivalent to the current one.

EDIT: ~~on the other hand, I believe `logdet` should only be implemented for real matrices, as is currently the case.~~  OK, apparently `logdet` is implemented for some complex matrices.

Thoughts?

CC @mishmash

**Comment by jiahao** [comment]
Sure, I don't see why not. The only possible complication I foresee is propagating the branch cut of `log` properly.

**Comment by andreasnoack** [comment]
Fine with me. The changes required are minimal: just remove the restriction to real inputs and make the accumulator real by wrapping the `T` in a `real`.
