### ISSUE TITLE
show misapplies parenthesis to `in`

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#13822]
the parenthesis printed below are reversed (on master), as can be seen from the output for show_sexpr. Maybe it should alway have parentheses?

```julia
julia> :(x in (a=>b))
:(x in a => b)

julia> :(x in a=>b)
:((x in a) => b)

julia> Meta.show_sexpr(:(x in a=>b))
(:(=>), (:comparison, :x, :in, :a), :b)
```

**Comment by stevengj** [comment]
I think the problem is that `Base.operator_precedence(:in)` is returning `0` (it is not recognized as an infix operator).

`Base.operator_precedence(:∈)` returns `6`, and the resulting expressions seem to be parenthesized correctly.
