### ISSUE TITLE
InexactError caused by left bit-shift by a BigInt

### ISSUE THREAD

**Issue by AlxG78** [JuliaLang/julia#13832]
This OK

```
julia> BigInt(2) .^ [1:6;]
6-element Array{BigInt,1}:
  2
  4
  8
 16
 32
 64
```

Not if the result is correct, there should be Array type: `Array{BigInt,1}`

```
julia> BigInt(1) .<< [1:6;]
6-element Array{Int64,1}:
  2
  4
  8
 16
 32
 64
```

therefore a large number

```
julia> BigInt(1) .<< [1:70;]
ERROR: InexactError()
 in convert at gmp.jl:188
 in .<< at arraymath.jl:120
```

**Comment by pao** [comment]
cf https://groups.google.com/forum/#!topic/julia-users/WLUlWlhiXt4

**Comment by timholy** [comment]
I don't think this is a bug. I understand why it feels like one, but over time we've moved towards having the array's eltype determine the result's eltype (as I pointed out in that email thread). It's not like always widening doesn't have its own big negatives.

**Comment by JeffBezanson** [comment]
For bit shifts it would probably make sense to always use the type of the first argument.

**Comment by StefanKarpinski** [comment]
> For bit shifts it would probably make sense to always use the type of the first argument.

+1
