### ISSUE TITLE
Unhelpful error with quantile!(x, q)

### ISSUE THREAD

**Issue by JockLawrie** [JuliaLang/julia#13846]
When computing quantiles on DataArrays, if the DataArray contains an NA I get an error that could be more helpful. See example below.

```julia
using DataArrays

x = DataArray(Int64, 3)
x[1] = 1
x[2] = 2
x[3] = 3
quantile!(x, [0.5])    # OK, no problem

x[3] = NA
quantile!(x, [0.5])    # Unhelpful error
```
The error is:
``ERROR: MethodError: `isnan` has no method matching isnan(::DataArrays.NAtype) in quantile! at statistics.jl:528``

The source code of statistics.jl has the message "quantiles are undefined in presence of NaNs", which is more helpful. How can this message be shown rather than the one currently shown?

**Comment by andreasnoack** [comment]
Please file this issue at https://github.com/JuliaStats/DataArrays.jl

**Comment by JockLawrie** [comment]
Done.

**Comment by andreasnoack** [comment]
Great. Thanks.
