### ISSUE TITLE
Assertion failed, process aborted in alloc.c

### ISSUE THREAD

**Issue by claxn** [JuliaLang/julia#13844]
Hey everyone,

I want to briefly summarize whats going wrong. I have written a recursive function to find objects in an array. In some cases it works, but commonly the process gets aborted and an assertion error occurs. I explained my problem on stackoverflow. Please follow the link to get more details. (http://stackoverflow.com/questions/33461722/assertion-failed-process-aborted)
Thanks in advance.

Cheers,
claxn

**Comment by yuyichao** [comment]
I don't think `->type` is how we get the type of a value anymore. Can you check the 0.4 release?

**Comment by JeffBezanson** [comment]
Could you post a complete example that triggers the problem? For example a file such that if I run `julia file.jl` I will see the crash.

**Comment by claxn** [comment]
Thanks for the answers, but i think this is not necessary anymore. I reinstalled julia today and updated the whole code to v 0.4. Now its more obvious what caused the problem. Have look at http://stackoverflow.com/questions/33487832/stackoverflow-with-tuple

**Comment by KristofferC** [comment]
Please comment if this is still happening / relevant.
