### ISSUE TITLE
Dates API: Allow `n * Dates.Minute` etc.

### ISSUE THREAD

**Issue by H-225** [JuliaLang/julia#13840]
In reference to issue #13763, it occurred to me that it might be worth considering borrowing a couple of other features from Go which also relate to `select` statements. Namely:
1. ~~Add something like `after(::Dates.Period)` which yields a `Channel` which provides a single value after that period of time.~~ Already exists in the form of `Timer`s.
2. Add the ability to multiply an `Integer` or `AbstractFloat` by a subtype of `Dates.Period` to get the number of seconds that duration represents, as a number or a `TimePeriod` object.
   e.g: `4 * Dates.Second` => `4`; `1.255 * Dates.Minute` => `75.3`

You would then, for instance, be able to do things like this: `sleep(5 * Dates.Minute)`

**Comment by malmaud** [comment]
I'm not clear on what 1) and 2) are doing that the current `Timer` function and `Dates` function aren't already doing.

**Comment by H-225** [comment]
@malmaud 
I concede that the `Timer` type does already implement the functionality I suggest. My mistake.

RE 2) however, it's a question of readability, and simplicity.
Consider: `Timer(4.5 * Dates.Minutes)` vs. `Timer(Dates.Minutes(4) + Dates.Second(30))`
One is cleaner, and clearer, than the other, and the brackets could be considered noise in code that already has a _lot_ of brackets.

Of course, if you wish to expressing an exact number of minutes and seconds is important, then `4.5` is not as ideal but in those situations you would still be able to use `Dates.Minute(4) + Dates.Second(30)`.

It's really more of a style thing, than functionality.

**Comment by malmaud** [comment]
Alright, maybe you could change the title of this issue to reflect that it's now about the Dates API.
I agree that something like that would be neat. 
cc @quinnj who maintains the Dates code.

**Comment by KristofferC** [comment]
Closing as dup of https://github.com/JuliaLang/julia/issues/10449
