### ISSUE TITLE
Wrong bindings with @spawnat / @async macros

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#13855]
This one caused a bit of trouble at DistributedArrays.jl recently - https://github.com/JuliaParallel/DistributedArrays.jl/issues/46 .

```
addprocs(1)

foo(opt) = @spawnat 2 println(opt)

opt = Base.specialized_binary(+)
foo(opt);
opt = Base.specialized_binary(*)
foo(opt);

```

prints

```
julia> 	From worker 2:	Base.AddFun()
	From worker 2:	Base.AddFun()
julia> 
```

**Comment by amitmurthy** [comment]
This may have something to do with how we localize vars. A simpler example that triggers this:

```
function foo(i, x)
    println("$i : ", x)
    @async (sleep(i);println("async $i : ", x))
end;

opt = Base.specialized_binary(+);
foo(1, opt);
opt = Base.specialized_binary(*);
foo(2, opt);
```

**Comment by amitmurthy** [comment]
@vtjnash any idea on why this is happening?

**Comment by amitmurthy** [comment]
Not an issue on 0.4

**Comment by vtjnash** [comment]
caused by aee6a26310c82f1f7b3c5bdd9f96cad2a0c14645: the copy_ast code now shares inner lambda, to reduce excess code generation. however, inference is later modifying this AST to insert the types of captured arguments, causing the mismatch.

**Comment by amitmurthy** [comment]
@vtjnash it would be great if you could look at a partial revert / modification of the mentioned commit. This bug results in hard-to-detect silent errors with the current master.

**Comment by amitmurthy** [comment]
Thanks!

**Comment by vtjnash** [comment]
it could also be considered a bug with how localize_vars interacts with the rest of the language https://github.com/JuliaLang/julia/issues?utf8=✓&q=is%3Aissue+is%3Aopen+localize
