### ISSUE TITLE
Add support to glob expressions in readdir()

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#13854]
It's very common to read all files with a given extension in a directory, for instance all `*.dat`. I understand that this can be accomplished by a filter later, but it would be handy to just pass the glob expression as a second argument to `readdir()`.

```julia
readdir("foo", "*.dat")
```

What are your thoughts on that feature?

**Comment by vtjnash** [comment]
use Glob.jl

**Comment by juliohm** [comment]
@vtjnash thank you for pointing the package, I was unaware of it.

Would it be interested to have this implemented in Base or there is a good reason not to?

**Comment by hayd** [comment]
There's a very good argument for making things like Glob be available in the default julia install, but base is actively going to be pared down. #5155

*Note: In python you need to import glob to do this kind of stuff.*

**Comment by StefanKarpinski** [comment]
I actually kind of want to move globbing into the backtick syntax. I'd also like to make things like `head -n10 /etc/passwd | sort -r > sorted.txt` construct pipeline objects and file redirects for you. The idea is to make backticks behave like a portable shell syntax.

**Comment by StefanKarpinski** [comment]
But I agree that `readdir` should not support this.

**Comment by cormullion** [comment]
A search ended up here: I was intending to suggest adding something like this to Base:

    function readdir(path::AbstractString, re::Regex)
        filter(f -> ismatch(re, f), readdir())
    end

allowing:

    readdir(".", r"[^.DS_Store]")

- it's those pesky .DS_Store files that litter the Mac and always cause simple scripts to fail (because you forget they're there).

I confess I'd never heard of 'glob' before. (Old-school Unix?)

Oh well, would have been nice.

**Comment by hayd** [comment]
@cormullion https://github.com/vtjnash/Glob.jl

```
Pkg.add("Glob")  # the first time
using Glob
readdir(glob".", r"[^.DS_Store]")
```

**Comment by cormullion** [comment]
@hayd Once you know what "globbing" is, that's a solution... :)
