### ISSUE TITLE
Unable to retrieve instances of user-defined types from remote processes

### ISSUE THREAD

**Issue by mrfrank8176** [JuliaLang/julia#13861]
Here's the code:
julia> addprocs()
4-element Array{Int64,1}:
 2
 3
 4
 5

julia> @everywhere begin
       type Test
           values::Array{Any,1}
           addValue::Function

           function Test()
               this = new()
               this.values = Any[]

               this.addValue = function(v)
                   push!(this.values,v)
               end

               return this
           end
       end
       end

julia> @spawnat 2 whos()
RemoteRef{Channel{Any}}(2,1,9)

julia> 	From worker 2:	                          Base  13039 KB     Module : Base
	From worker 2:	                          Core   1959 KB     Module : Core
	From worker 2:	                          Main  14945 KB     Module : Main
	From worker 2:	                          Test    124 bytes  DataType : Test

julia> @spawnat 2 whos()
RemoteRef{Channel{Any}}(2,1,14)

julia> 	From worker 2:	                          Base  13041 KB     Module : Base
	From worker 2:	                          Core   1959 KB     Module : Core
	From worker 2:	                          Main  14946 KB     Module : Main
	From worker 2:	                          Test    124 bytes  DataType : Test
	From worker 2:	                             t     16 bytes  Test : Test(Any[],(anonymous funct…

julia> @everywhere t.addValue(myid())

julia> @spawnat 2 whos()
RemoteRef{Channel{Any}}(2,1,19)

julia> 	From worker 2:	                          Base  13044 KB     Module : Base
	From worker 2:	                          Core   1959 KB     Module : Core
	From worker 2:	                          Main  14949 KB     Module : Main
	From worker 2:	                          Test    124 bytes  DataType : Test
	From worker 2:	                             t     24 bytes  Test : Test(Any[2],(anonymous func…

julia> r = @spawnat 2 t

and then I get a huge error ending in:

 in serialize at serialize.jl:414 (repeats 2 times)
 in serialize at serialize.jl:127
 in serialize at serialize.jl:298
 in serialize at serialize.jl:414 (repeats 2 times)
 in serialize at serialize.jl:127
 in serialize at serialize.jl:298
 in serialize at serialize.jl:414 (repeats 2 times)
 in serialize at serialize.jl:127
 in serialize at serialize.jl:298
 in serialize at serialize.jl:414
 in serialize at serialize.jl:127
 in serialize at serialize.jl:298
 in serialize at serialize.jl:414
 in send_msg_ at multi.jl:222
 in remotecall at multi.jl:710
 in spawnat at multi.jl:1320
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68
ArgumentError: stream is closed or unusable

ERROR (unhandled task failure): EOFError: read end of file

This leads me to believe there is an issue serializing user-defined types. Any ideas? Thanks.

**Comment by mrfrank8176** [comment]
A related approach also fails:
julia> r = remotecall_fetch(3,()->t)
Worker 3 terminated.ERROR: ProcessExitedException()
 in yieldto at ./task.jl:76
 in wait at ./task.jl:372
 in wait at ./task.jl:287
 in wait at ./channels.jl:93
 in take! at ./channels.jl:82
 in take! at ./multi.jl:792
 in remotecall_fetch at multi.jl:729
 in remotecall_fetch at multi.jl:734
 in eval_user_input at REPL.jl:64
 [inlined code] from REPL.jl:93
 in anonymous at task.jl:68


ERROR (unhandled task failure): StackOverflowError:

**Comment by mrfrank8176** [comment]
@everywhere begin
    type Test
        values::Array{Any,1}
addValue::Function

       function Test()
           this = new()
           this.values = Any[]

           this.addValue = function(v)
               push!(this.values,v)
           end

           return this
       end
   end
   end

**Comment by amitmurthy** [comment]
Which version of Julia are you one?

I tested the above on master and 0.4.1, both work fine on Linux.

**Comment by mrfrank8176** [comment]
This issue was resolved in the most recent release. Also works fine in 0.5.0
