### ISSUE TITLE
Build failure in cpu_sfence() on i386 Fedora nightlies

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#13862]
This build failure has been introduced on master between October 26th and 30th. It happens at least with gcc from 4.9.2 to 5.1.1, only on 32-bit.

I've found this related thread, but it seems like the patch should be included in gcc 5.1.1:
https://gcc.gnu.org/ml/gcc-patches/2014-05/msg02560.html

```
gcc -march=pentium4 -m32  -ftls-model=global-dynamic -DSYSTEM_LLVM -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -I. -I/builddir/build/BUILD/julia/src -I/builddir/build/BUILD/julia/src/flisp -I/builddir/build/BUILD/julia/src/support -I/builddir/build/BUILD/julia/build/usr/include -I/builddir/build/BUILD/julia/build/usr/include -DLIBRARY_EXPORTS -I/builddir/build/BUILD/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -I/usr/include -DLLVM_SHLIB "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.so\"" -DNDEBUG -c /builddir/build/BUILD/julia/src/threadgroup.c -o threadgroup.o
In file included from /usr/lib/gcc/i686-redhat-linux/5.1.1/include/immintrin.h:29:0,
                 from /builddir/build/BUILD/julia/src/threadgroup.c:10:
/builddir/build/BUILD/julia/src/ia_misc.h: In function 'cpu_sfence':
/usr/lib/gcc/i686-redhat-linux/5.1.1/include/xmmintrin.h:1229:1: error: inlining failed in call to always_inline '_mm_sfence': target specific option mismatch
 _mm_sfence (void)
 ^
In file included from /builddir/build/BUILD/julia/src/threadgroup.c:19:0:
/builddir/build/BUILD/julia/src/ia_misc.h:87:5: error: called from here
     _mm_sfence();
     ^
Makefile:94: recipe for target 'threadgroup.o' failed
make[1]: *** [threadgroup.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/build/BUILD/julia/src'
Makefile:87: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-rawhide-i386/00131617-julia/build.log.gz

**Comment by vtjnash** [comment]
i looks like you have `-march=i686` in your build flags that is overriding the `-march=pentium4` flag that is required for building julia

**Comment by nalimilan** [comment]
Indeed, sorry for missing this. Do you think it would be possible to fail loudly in that case? Would a simple `#if defined(__i386__) || defined(__i686__)` associated with an `#error` work? If so, I can make a PR.

**Comment by tkelman** [comment]
It's already in the makefiles https://github.com/JuliaLang/julia/blob/95b7080c13b4ca3c5390e4a3313a5a2af76da9da/Make.inc#L548 but I guess the fedora build environment is appending extra flags there.

**Comment by nalimilan** [comment]
Actually, the problem was that `MARCH=pentium4` was correctly set, but that `march=i686` was also passed directly via `CFLAGS`. This scenario should be relatively rare, but if we can catch it easily, I think it would be worth it.

**Comment by nalimilan** [comment]
In my tests, https://github.com/JuliaLang/julia/pull/13920 detects correctly the situation encountered in this issue and in #13913.
