### ISSUE TITLE
Possible inconsistency with boolean conversions?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#13863]
This is ok:

```
julia> bool(3)
WARNING: bool(x::Number) is deprecated, use x != 0 instead.
 in depwarn at ./deprecated.jl:73
 in bool at ./deprecated.jl:50
while loading no file, in expression starting on line 0
true
```

but it has the consequence of suggesting that the test is `x != 0`. That is, any nonzero value will evaluate to `true`.

However,

```
julia> bool([1,0,1,0])
WARNING: bool(x::AbstractArray) is deprecated, use map(Bool,x) instead.
 in depwarn at ./deprecated.jl:73
 in bool at ./deprecated.jl:50
while loading no file, in expression starting on line 0
4-element Array{Bool,1}:
  true
 false
  true
 false
```

yields consistent results, but

```
julia> bool([1,2])
WARNING: bool(x::AbstractArray) is deprecated, use map(Bool,x) instead.
 in depwarn at ./deprecated.jl:73
 in bool at ./deprecated.jl:50
while loading no file, in expression starting on line 0
ERROR: InexactError()
 in convert at /usr/local/julia/lib/julia/sys.dylib
 in map_to! at ./abstractarray.jl:1275
 in map at ./abstractarray.jl:1297
 in bool at ./deprecated.jl:52
```

Likewise,

```
julia> map(Bool,[1,0,1,0])
4-element Array{Bool,1}:
  true
 false
  true
 false

julia> map(Bool,[1,2])
ERROR: InexactError()
 in convert at /usr/local/julia/lib/julia/sys.dylib
 in map_to! at ./abstractarray.jl:1275
 in map at ./abstractarray.jl:1297
```

which seems to suggest that truth is absolute - that is, _x is true iff x == 1_, which contradicts the very first deprecation warning.

**Comment by quinnj** [comment]
This is just a timing issue. Notice the deprecation warnings. The `bool` method used to be defined as
```
@deprecate bool(x::Number)  x!=0
```
and now conversions to Bool are defined as
```
convert(::Type{Bool}, x::Real) = x==0 ? false : x==1 ? true : throw(InexactError())
```
If you use only deprecated methods, it's consistent, if you use only current methods, it's also consistent.

**Comment by sbromberger** [comment]
Wait... my point is that folks fixing deprecation warnings will see the recommended fix for truth testing to be comparison against 0, which is decidedly NOT what the new conversions will accept.  My recommendation is to change the deprecation warning for bool so that truth tests will work unambiguously when the recommendations are followed. Right now, that's not the case with the suggestion to replace `bool(x)` with `x != 0`.

**Comment by yuyichao** [comment]
For depwarn, you want the new function to behave the same with what it was before. So the inconsistency here is that `bool([1,2])` should work.

**Comment by sbromberger** [comment]
Should fixing the deprecation warning as suggested result in an error message?

**Comment by yuyichao** [comment]
When possible, it shouldn't raise an error when it didn't used to for the same input on the previous version (0.3).

**Comment by sbromberger** [comment]
then my feeling is that the deprecation warning should be changed in 0.4 so that following it won't result in the InexactError.

**Comment by JeffBezanson** [comment]
Yes, looks like it should suggest `x .!= 0` for `bool(array)`.

**Comment by sbromberger** [comment]
Thank you for grokking the underlying issue here.

**Comment by KristofferC** [comment]
This deprecation warning is obsolete on 0.6.

The way to do it now is likely best written as:

```
julia> Bool.([1,0,1,0])
4-element BitArray{1}:
  true
 false
  true
 false
```
