### ISSUE TITLE
Macro expansion causes incorrect line numbers in backtrace

### ISSUE THREAD

**Issue by 315234** [JuliaLang/julia#13875]
Example code:

```julia
@time nonexistent
```

Output:

    $ julia --version
    julia version 0.4.0
    
    $ julia macro_line_numbers.jl
    ERROR: LoadError: UndefVarError: nonexistent not defined
     in include at ./boot.jl:261
     in include_from_node1 at ./loading.jl:304
     in process_options at ./client.jl:308
     in _start at ./client.jl:411
    while loading macro_line_numbers.jl, in expression starting on line 155

There is no line 155 in this file. Removing `@time` gives the correct line number (1).

**Comment by jakebolewski** [comment]
Dup of  https://github.com/JuliaLang/julia/issues/10595, https://github.com/JuliaLang/julia/issues/8701, https://github.com/JuliaLang/julia/issues/13725
