### ISSUE TITLE
Should there be an AbstractFunction?

### ISSUE THREAD

**Issue by SloanLindsey** [JuliaLang/julia#13877]
I've recently been experimenting with the FastAnonymous macro in v0.4. I find it useful to create custom functions with the constants baked in and then stuff these functions into a dictionary. 
When one defines the receiving dictionary to be of
```jl
Dict{Int64,Function}()
``` 
and then tries to add a duck type function from FastAnonymous one gets the expected conversion error.
Clearly the work around is to define:
```jl
Dict{Int64,Any}()
```
and let everything just work out. 

The experience does make me think that it might be desirable to have an AbstractFunction supertype which is referenced by FastAnonymous.
I'd like to hear other people's thoughts.

**Comment by JeffBezanson** [comment]
You will love #13412. On that branch, `Function` is now an abstract type (plus FastAnonymous is no longer needed).

**Comment by SloanLindsey** [comment]
Lovely! I guess I can close this then.
