### ISSUE TITLE
Embedding Julia 0.4 in C is showing a strange behavior

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#13882]
Hi guys!

Due to a problem in pyjulia (https://github.com/JuliaLang/pyjulia/issues/38), it seems that something has changed between 0.3 and 0.4 releases regarding embedding Julia in C apps.
The following code, which is supposed to execute `Int64(1)` is not working properly:
```
#include <julia.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
   /* required: setup the julia context */
   jl_init_with_image("/usr/lib64/julia", "sys.so");

   /* run julia commands */
   jl_value_t *number = jl_eval_string("1");
   jl_value_t *type = jl_eval_string("Int64");

   jl_value_t *ret = jl_call1((void *)type, (void *)number);

   printf("%p\n", ret);

   jl_atexit_hook(0);
   return 0;
 }
```
The output is:
```
(nil)
```
Thus, `ret` variable is `NULL`, which, I think, is an unexpected  behavior. On the other hand, if I execute `int64(1)` everything works except for a warning saying that this function is deprecated:
```
#include <julia.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
   /* required: setup the julia context */
   jl_init_with_image("/usr/lib64/julia", "sys.so");

   /* run julia commands */
   jl_value_t *number = jl_eval_string("1");
   jl_value_t *type = jl_eval_string("int64");

   jl_value_t *ret = jl_call1((void *)type, (void *)number);

   printf("%p\n", ret);

   jl_atexit_hook(0);
   return 0;
 }
```
The output is:
```
WARNING: int64(x) is deprecated, use Int64(x) instead.
 in depwarn at deprecated.jl:73
 in int64 at deprecated.jl:50
while loading no file, in expression starting on line 0
0x7f812a95e080
```
This issue broke pyjulia because it uses this logic to convert the return value of a function to a PyObject (a type defined by PyCall). As a temporary workaround, the `convert` function can be used, but is it the expected behavior of `jl_call` using types like `Int64` or is it a bug?

**Comment by yuyichao** [comment]
No it is not supposed to work. `Int` is not a `jl_function_t` and `jl_call1` is `jl_value_t *jl_call1(jl_function_t *f, jl_value_t *a)`. Calling `Int` is done with the `call` overloading on 0.4.

Also note that you should root `number` and `type`. It is not garenteed that `number` is a static cache.

**Comment by ronisbr** [comment]
Ok, thanks @yuyichao!

Sorry, what did you mean with root `number` and `type`?

**Comment by yuyichao** [comment]
http://julia.readthedocs.org/en/latest/manual/embedding/#memory-management

**Comment by ronisbr** [comment]
Thanks @yuyichao !
