### ISSUE TITLE
indmax on subarrays returns Tuple instead of Integer

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#13888]
julia> `indmax(sub(randn(10,10),1,:))`
(1:10,2)

help?> `indmax`
search: indmax findmax invdigamma

  indmax(itr) -> Integer

  Returns the index of the maximum element in a collection.

`julia> versioninfo()`
Julia Version 0.4.1-pre+16
Commit 2cdef5d (2015-10-24 06:33 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by andreasnoack** [comment]
This broke in 7bcc9471ef1988fabf7b7cb66aef9fd57ac7af1c. @timholy, any idea about how to fix this?

**Comment by timholy** [comment]
Yeah...fix my buggy implementation of `iterstate` for CartesianRange iteration. Gotta run now, though.

**Comment by tkelman** [comment]
if this breaks any user code, should I revert https://github.com/JuliaLang/julia/pull/13235? 0.4.1 needs to go out imminently.

**Comment by timholy** [comment]
No, because it fixes so many more breakages than it causes. Fix coming momentarily.
