### ISSUE TITLE
Add (commented-out) Coveralls script to generated .travis.yml

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13885]
It would be nice to have an (official) and probably commented-out line in the `Pkg.generate`d `.travis.yml` file that submits results to Coveralls.

**Comment by KristofferC** [comment]
Or codecov which is imo better.

**Comment by Jutho** [comment]
I think this is already in place in the new PkgDev.jl repo:
https://github.com/JuliaLang/PkgDev.jl/pull/5
