### ISSUE TITLE
Add ability to set default command line options from environment variable

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#13889]
I've been looking at the source code (C & Julia both), PRs and Issues (such as #9266), but haven't seen anything so far that handles this.
It would be very nice to have an environment variable, such as `JULIA_OPTIONS`, that would be processed first, to set up defaults (which could be overriden by the command line).
For example, if you always wanted to suppress the banner, you'd simply have:
`export JULIA_OPTIONS="-q"`
If people think this would be useful, I can attempt a PR for it.

**Comment by tkelman** [comment]
this is getting into https://github.com/JuliaLang/julia/pull/2716 territory

we already have too many environment variables and too many command line flags, neither is a particularly satisfying way to modify configuration. can't you just set shell aliases or wrapper scripts for this?

**Comment by KristofferC** [comment]
>  can't you just set shell aliases or wrapper scripts for this?

:+1:
