### ISSUE TITLE
Inconsistent results between [n]x1 and [n]-element array in dot product

### ISSUE THREAD

**Issue by FelixGruen** [JuliaLang/julia#13883]
While optimizing code to use column-major ordering I found an inconsistency in the results between the naive and optimized implementation. I tracked it down to a problem when multiplying with a [n]x1 array instead of a [n]-element array:

```Julia
julia> a = [0.9421643044048015 0.8406257513418437]
1x2 Array{Float64,2}:
 0.942164  0.840626

julia> x = [-1.237364939547807,9.314822003963044]
2-element Array{Float64,1}:
 -1.23736
  9.31482

julia> (a*x)[1]
6.664478168133023

julia> (x'*a')[1]
6.664478168133024

julia> (x'*(a')[:,1])[1]
6.664478168133023

julia> a[1]*x[1]+a[2]*x[2]
6.664478168133023

julia> a'
2x1 Array{Float64,2}:
 0.942164
 0.840626

julia> (a')[:,1]
2-element Array{Float64,1}:
 0.942164
 0.840626
```

As you can see the result for `(x'*a')[1]` is different from the rest. At first I thought this might be due to the normal accuracy problems with floating point numbers, but in the minimal example above with only two seperate multiplications and one addition, I don't see how that could have an effect.

For the example above I used Julia Version 0.4.0 x86_64-w64-mingw32 without any flags in a fresh repl session.

**Comment by jiahao** [comment]
> At first I thought this might be due to the normal accuracy problems with floating point numbers, but in the minimal example above with only two seperate multiplications and one addition, I don't see how that could have an effect.

Floating point addition is not associative and you can get roundoff effects with just two additions:

```jl
julia> (0.1 + 0.2) + 0.3
0.6000000000000001

julia> 0.1 + (0.2 + 0.3)
0.6
```

so I don't see why you claim that roundoff should not happen in your example.

`a*x` is a matrix-vector product; `x'*a'` is a matrix-matrix product. The code called is different (try `@which a*x` and `@which x'*a'`) and there is no guarantee that the floating point computations are performed in the same order internally.

**Comment by FelixGruen** [comment]
Ah, my bad. I've never done calculations where I needed the precision, and I guess it's been to long since I've had the theory.
