### ISSUE TITLE
syntactic sugar:   |x|  in addition to norm(x)  

### ISSUE THREAD

**Issue by Mirage10** [JuliaLang/julia#13880]
Hi community,

I would like to see the notation |x| in addition to norm(x) .  |x| looks more mathematical and concise than norm(x):

    x =[3 4]
    if |x| < 6 ...

instead of

    x =[3 4]
    if norm(x) < 6 ...

**Comment by johnmyleswhite** [comment]
Would be good to write a PR that demonstrates you can make this work without breaking the current definition of `|`. In the absence of a formal RFC that shows that you won't break any currently written programs, I think this change is likely to be rejected.

**Comment by jakebolewski** [comment]
`|` (bitwise or) is defined as an infix operator so this won't work.

**Comment by rfourquet** [comment]
What about `if ||x|| < 6 ...`, which I think is a usual notation for norms?

**Comment by johnmyleswhite** [comment]
Also a conflict with the infix special form `||`?

**Comment by nalimilan** [comment]
There's still the possibility of using the Unicode char `‖ ` (U+2016). But it would still need to special handling since AFAIK no other operators appear on both sides of an identifier.

**Comment by StefanKarpinski** [comment]
Using the Unicode double bar character would be nice. If someone wants this
they should submit a PR. Unfortunately not a super easy change.

**Comment by JeffBezanson** [comment]
Yes the unicode character would be fine. The most controversial aspect is probably that it's a bracketing form that doesn't nest, since the open and close characters are the same. It can certainly be parsed, but I don't know if people want something like that in the syntax.

**Comment by jakebolewski** [comment]
Adding extra context sensitivity for one special form of one function does not seem worth it.

**Comment by Mirage10** [comment]
@jakebolewski    code readability is one of the cool things of julia. I appreciate also the \in approach in for loops.
@StefanKarpinski     \mid or \parallel   would be great.  perhaps \parallel better to differentiate better from the binary or operator

**Comment by johnmyleswhite** [comment]
Agreeing with Jake, I'd like to put in another -1 for this change.

**Comment by Mirage10** [comment]
@johnmyleswhite  -1 for your vote  :-)

**Comment by JeffBezanson** [comment]
@jakebolewski If this syntax is specific to the unicode `‖` then I don't think it's context-sensitive. When you see ‖, you parse one production of, say, `parse-eq*`, then expect a closing ‖ or give an error.

**Comment by johnmyleswhite** [comment]
I'm pretty astonished that Unicode normalization doesn't make ‖ equivalent to ||.

Seriously imagine someone writing code like `x[1 < ‖a‖ || ‖b‖ < 2]`

**Comment by toivoh** [comment]
This would definitely be simplified if we went the route to replace `&&` and `||` by `and` and `or `. Still a bit skeptical to a bracketing form that doesn't nest (though using backquotes for quoting would be another, and I'm mildly positive to that one).
