### ISSUE TITLE
Pkg.build() needs a corresponding Pkg.build(clean=true) or Pkg.buildclean() or ...

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13892]
Many packages have implicit state during the build process.  It would be _really_ handy to have a standard way of doing a clean build instead of having to manually go in and delete folders, files from the `deps/` folders.

**Comment by vtjnash** [comment]
`git clean -fdx`? :)

**Comment by jakebolewski** [comment]
haha, that is the current procedure

**Comment by wildart** [comment]
I think developers should be more diligent with build.jl scripts and consider possibility of an error with subsequent cleanup. Not a problem of `Pkg.build`.

**Comment by mlubin** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7054?

**Comment by simonbyrne** [comment]
I don't think we're going to do anything here. If you disagree, please open an issue at https://github.com/JuliaLang/Pkg.jl
