### ISSUE TITLE
pop!(v::Vector) not documented

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaLang/julia#13891]
Also, with 0.5 and arrayviews, will
```julia 
v=v[1:end-1]
```
be equivalent?

**Comment by jiahao** [comment]
Documentation is available in the [standard library](http://docs.julialang.org/en/release-0.4/stdlib/collections/?highlight=pop#Base.push!) section of the manual and is available through online help.

```jl
help?> pop!([9])
  pop!(collection) -> item

  Remove the last item in collection and return it.

  julia> A=[1, 2, 3, 4, 5, 6]
  6-element Array{Int64,1}:
   1
   2
   3
   4
   5
   6
  
  julia> pop!(A)
  6
  
  julia> A
  5-element Array{Int64,1}:
   1
   2
   3
   4
   5
```

So I don't understand what you mean when you say this method is not documented.

**Comment by jakebolewski** [comment]
A Vector is a collection?  Also pop! uses a Vector in the docstring example.

**Comment by CarloLucibello** [comment]
sorry, my bad, searching the online documentation for pop! redirected me to pop!(collection, key[, default]), so I didn't notice that there is also  pop!(collection) in the Dequeues section
