### ISSUE TITLE
GitError when Pkg.update() 

### ISSUE THREAD

**Issue by zhujinxuan** [JuliaLang/julia#13899]
Recently, when I run `Pkg.update()` there is errors about Git.  

```
julia> Pkg.update()
INFO: Updating METADATA...
GitError(Code:ENOTFOUND, Class:Config, Remote 'origin' does not exist.)
INFO: Updating Compose master...
WARNING: fetch: GitError(Code:ERROR, Class:SSH, error authenticating: no auth sock variable)
```

My julia version is `0.5.0-dev+1163`, built with the configure in aur (https://aur.archlinux.org/packages/julia-git/).  I am not sure whether or not there are something missing in my git configure or somewhere else.

Thank you.

**Comment by nalimilan** [comment]
Can you post the contents of `~/.julia/METADATA/.git/config`?

**Comment by zhujinxuan** [comment]
Here is the git config under the METADATA
```
->cat .julia/v0.5/METADATA/.git/config   1
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/JuliaLang/METADATA.jl
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = git@github.com:JuliaLang/METADATA.jl.git
[branch "metadata-v2"]
	remote = origin
	merge = refs/heads/metadata-v2
```

**Comment by zhujinxuan** [comment]
I try to checkout the METADATA and an error occurs
```
julia> Pkg.checkout("METADATA")
INFO: Checking out METADATA master...
ERROR: GitError(Code:ENOTFOUND, Class:Reference, Reference 'refs/remotes/origin/master' not found)
```

**Comment by jakebolewski** [comment]
If you start with a clean ~/.julia/v0.5 folder does everything work?

**Comment by zhujinxuan** [comment]
With a new v0.5, it works with `Pkg.add()`.

But when I am trying to use `Pkg.clone`, the error occurs again.
```
Pkg.clone("git@github.com:JuliaGeo/NetCDF.jl.git")
INFO: Cloning NetCDF from git@github.com:JuliaGeo/NetCDF.jl.git
ERROR: GitError(Code:ERROR, Class:SSH, error authenticating: no auth sock variable)
```

**Comment by jakebolewski** [comment]
what is the output of `ssh-agent`?

**Comment by zhujinxuan** [comment]
Here is the output of `ssh-agent`

```
  ->ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-iuHXPE53KvYt/agent.11592; export SSH_AUTH_SOCK;
SSH_AGENT_PID=11593; export SSH_AGENT_PID;
echo Agent pid 11593;
```

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/PkgDev.jl/issues/16

**Comment by zhujinxuan** [comment]
@yuyichao 
Does that post mean that ,in building julia, we should use the libgit2 provided by the Julia, rather than the libgit2 in the system?

**Comment by yuyichao** [comment]
I'd be a little surprised if additional feature in the system lib break things but that's worth testing. I install all packages in system path so it haven't been bother me enough to test different configurations.

**Comment by wildart** [comment]
@zhujinxuan Did you configure ssh credentials for `github.com` host? Did you register identity key with `ssh-agent`. `ssh-add -l` should give you a list of ssh-agent identities.

**Comment by yuyichao** [comment]
Is this necessary `ssh-agent` setup that seems to be required for many package operations documented somewhere?

**Comment by zhujinxuan** [comment]
@wildart 
yes, that is the problem. Thank you.

**Comment by wildart** [comment]
Usually you need to add identity file with `ssh-add /path/to/identity/file`. 

As for `no auth sock variable`, it looks like env variable SSH_AUTH_SOCK is not set. Here is a solution for of a similar error (https://github.com/nodegit/nodegit/issues/372#issuecomment-72291242).

**Comment by yuyichao** [comment]
The problem though, is that these works perfectly fine with git with absolutely no additional setup.

**Comment by wildart** [comment]
Not true, you need to setup ssh properly before using `git`. I think it is an issue with default ssh credentials which we could add to credential handler (there isn't any at this point).

**Comment by yuyichao** [comment]
The only ssh setup for git to work properly is to drop my private key (or generate one) at `~/.ssh/id_rsa` (well, and maybe add the host to known_hosts, which is prompt by ssh automatically). I don't think I ever need explicit `ssh-agent` setup at any time. Is this (`~/.ssh/id_rsa`) the default ssh credentials you mean?

**Comment by wildart** [comment]
Correct in some way, but naive. What if you already have `id_rsa` file? A proper way would be define configuration in `~/.ssh/config` and register identity file with `ssh-agent`.

**Comment by yuyichao** [comment]
> What if you already have `id_rsa` file?

Use it? `ssh` shouldn't care about who or how the default identity file is created.

> A proper way would be define configuration in ~/.ssh/config and register identity file with ssh-agent.

I don't see what's wrong with using a single identify file per machine and why this additional configuration is necessary for this case.

> Surely, we can go with ~/.ssh/id_rsa as a default location of the identity file for git user.

I think not breaking a simple setup that previously work is important and we should do this if this is what it takes to restore the default git+ssh behavior.

**Comment by wildart** [comment]
>Use it? ssh shouldn't care about who or how the default identity file is created.

Sometimes using the same identity is not an option.

> we should do this if this is what it takes to restore the default git+ssh behavior.

in case if we going to support ssh protocol

**Comment by yuyichao** [comment]
> definitely, in case if we going to support ssh protocol

I'm ok with not supporting it if none of the `Pkg` or `PkgDev` operations introduce `git+ssh` remote. Having to type password is very annoy but I don't do that often and it's much better than errors.
