### ISSUE TITLE
Feature request:  rand to be extended to AbstractString

### ISSUE THREAD

**Issue by Mirage10** [JuliaLang/julia#13918]
alphabet="basfde"
c=rand(alphabet)

of course c=rand(collect(alphabet)) will do the same, but the first version is more concise

**Comment by jiahao** [comment]
Why is this method needed? As you note, `rand(collect(alphabet))` already does what you want.

**Comment by tkelman** [comment]
This is getting a bit too close to conflating strings with their representation (arrays of code points) for my tastes.

**Comment by rfourquet** [comment]
The (straightforward) implementation would need to call `collect` internally (since I think an `AbstractString` does not provide random access to its characters), so it seems wiser for the user to have to call `collect` explicitly (e.g. to avoid the inefficiency of implicitly calling repeatedly `collect` in a loop).

**Comment by nalimilan** [comment]
Except for `ASCIIString`, where a special method would be much more efficient. Not sure this use case deserves a method, though.

**Comment by JeffBezanson** [comment]
Since strings don't necessarily have efficient random access to characters it seems to me providing this method would be misleading.

**Comment by Mirage10** [comment]
one possibility would be:

    rand(str::AbstractString, n::Int) = str[ rand(1:length(str),n) ]

**Comment by JeffBezanson** [comment]
That doesn't work. UTF-8 strings are not indexed by character number.

**Comment by Mirage10** [comment]
@JeffBezanson  ... sure? look here:
    s=UTF8String("ueur") 
    s[2]
'e'

nevertheless, I have an error in my example:
new version:

    rand(alphabet::AbstractString, n::Int) = alphabet[ rand(1:length(alphabet),n) ]

**Comment by StefanKarpinski** [comment]
Try sticking a non-ASCII character in there and see how it goes.

**Comment by Mirage10** [comment]
ASCIIString will suffice. So here ist the next version
    rand(alphabet::ASCIIString, n::Int) = alphabet[ rand(1:end,n) ]

**Comment by StefanKarpinski** [comment]
Having string methods that only work for some string implementations in Base doesn't cut it. It's fine for personal code, but it's not a cheat that we can have in the standard library – anything that works for one string type should work for others too. I can't see why this needs to be in the standard library.

**Comment by jakebolewski** [comment]
I don't see why this needs to be in `Base`.  As the example shows, `Base` provides all functionality you need to implement this yourself.
