### ISSUE TITLE
Function do not accept keywords when Vararg is used.

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#13919]
If `Vararg{T}` is used in a function definition, the function cannot have keywords. It fails due to some lowering issue. If the following is functions are defined.
```
test(x::Vararg{Int}; key=100) = println("x=$x\nkey=$key")
test1(x::Vararg{Int}) = println("x=$x")
test1(1, 2) # print x=(1,2)
test(1, 2)  #Fails with

LoadError: MethodError: `__test#33__` has no method matching __test#33__(::Int64, ::Tuple{Int64,Int64})
Closest candidates are:
  __test#33__(::Any, !Matched::Int64...)
while loading In[59], in expression starting on line 1
```
`test1` function works as intended while `test` fails.
`@code_lowered test(1, 2)` returns
```
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:(x::(top(apply_type))(Vararg,Int))], Any[Any[Any[:x,:Any,0]],Any[],0,Any[]], :(begin 
        $(Expr(:line, 1, symbol("In[52]"), symbol("")))
        return (Main.__test#33__)(100,x)
    end))))
```
It seems to call a function named `__test#33__` which do not exist. If the function is defined without a keyword argument code lowered calls `println`
`@code_lowered test1(1, 2)`
```

1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:(x::(top(apply_type))(Vararg,Int))], Any[Any[Any[:x,:Any,0]],Any[],0,Any[]], :(begin  # In[52], line 2:
        return (Main.println)((top(string))("x=",x))
    end))))

**Comment by dhoegh** [comment]
I have found another way of obtaining the same solution.
```
test(x::Int...;key=100) = println("x=$x\nkey=$key")
```
I do not know if it is supposed to work with `Vararg{Int}`.

**Comment by JeffBezanson** [comment]
This is a strange failure mode, but this is not supposed to work. The `...` syntax is the normal varargs syntax.

**Comment by dhoegh** [comment]
@pwl could you check if your issue in https://github.com/JuliaLang/ODE.jl/pull/49#issuecomment-228242266 is fixed on latest master of Julia, if not fiil a new issue?

**Comment by pwl** [comment]
We have already moved away from that solution so there is no way for me to verify your fix apart from running your tests.
