### ISSUE TITLE
Feature request:   B=powerset(A,min,max)

### ISSUE THREAD

**Issue by Mirage10** [JuliaLang/julia#13917]
would be good to provide in Base a function, that provides the powerset of a Set A.
B is an array.  the elments b of B are a subset of A,
min (optional) denotes the minimum size of b     
max (optional) denotes the maximum size of b

A could be an array of a specific type e.g. [3 2 5] or [3 2 5 2] or ["ds" "rr" "4e"] or "asdf" or Set([1 2 3 4])
A is  to be converted internally to unique, i.e. to a set

**Comment by jiahao** [comment]
The powerset function would make a nice pull request to Combinatorics.jl.

**Comment by JeffBezanson** [comment]
This could be done as a small layer around `combinations(set, n)`.

**Comment by jiahao** [comment]
Feature request has been transferred.
