### ISSUE TITLE
Build failure on threadgroup.o

### ISSUE THREAD

**Issue by Narrat** [JuliaLang/julia#13913]
Building with latest master I'm getting this error

>CC src/threadgroup.o
In file included from /usr/lib/gcc/i686-pc-linux-gnu/5.2.0/include/immintrin.h:29:0,
                 from /home/omnius/Builds/Maint/AUR4/julia-git/src/julia/src/threadgroup.c:10:
/home/omnius/Builds/Maint/AUR4/julia-git/src/julia/src/ia_misc.h: In function 'cpu_sfence':
/usr/lib/gcc/i686-pc-linux-gnu/5.2.0/include/xmmintrin.h:1229:1: error: inlining failed in call to always_inline '_mm_sfence': target specific option mismatch
 _mm_sfence (void)
 ^
In file included from /home/omnius/Builds/Maint/AUR4/julia-git/src/julia/src/threadgroup.c:19:0:
/home/omnius/Builds/Maint/AUR4/julia-git/src/julia/src/ia_misc.h:87:5: error: called from here
     _mm_sfence();
     ^
make[1]: *** [threadgroup.o] Error 1
Makefile:94: recipe for target 'threadgroup.o' failed
make[1]: Leaving directory '/home/omnius/Builds/Maint/AUR4/julia-git/src/julia/src'
make: *** [julia-src-release] Error 2
Makefile:87: recipe for target 'julia-src-release' failed
make: Leaving directory '/home/omnius/Builds/Maint/AUR4/julia-git/src/julia'

Didn't had the time to run a bisect, but can do hopefully later (If it's still necessary then)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13862 . You probably want to remove the `-march=i686` flag that is set by default in `makepkg.conf`.

**Comment by Narrat** [comment]
Oh, I completly missed that. Thanks for pointing to the other issue.

Dunno about removing the option from makepkg.conf. I will try to update the PKGBUILD to set (just for this build process) explicitly the MARCH to pentium4 for i686 builds.

But maybe you can help me again? I saw an approach for 32bit builds which sets JULIA_CPU_TARGET=pentium4 but this failed for me. Got this var removed?

**Comment by nalimilan** [comment]
`JULIA_CPU_TARGET=pentium4` should still work. But if you set `MARCH=pentium4`, the former will automatically be set too.

I'll try to find a way to raise a better error when `-march=i686` is used.

**Comment by nalimilan** [comment]
Oh, and setting `MARCH=pentium4` won't be enough to override `-march=i686` if the package build scripts pass it. You'll need to add `-march=pentium4` to `CFLAGS` and `CXXFLAGS`.

**Comment by yuyichao** [comment]
[This] is what I did. I haven't run it through the build server to make sure it works though.

**Comment by Narrat** [comment]
Thanks for the intel about the flags nalimilan.

yuyichao, I will try your approach to make the build process working again

**Comment by Narrat** [comment]
Adding the *FLAGS like that works great.

Now I just need to find out why the makefile fails on placing the julia.conf file :/

**Comment by nalimilan** [comment]
Please copy the full output of make somewhere and open a new thread, for example in julia-users, and we can look at it.

**Comment by Narrat** [comment]
It got resolved. Fault at my end (If you cannot keep you eyes open you shouldn't look at a text *cough*).

So, thanks for the help and sorry for the noise with the previous post :)
