### ISSUE TITLE
Ubuntu PPA contains no packages for new release ‘wily’ (15.10)

### ISSUE THREAD

**Issue by stochasticwave** [JuliaLang/julia#13916]
```
sudo add-apt-repository ppa:staticfloat/juliareleases
sudo add-apt-repository ppa:staticfloat/julia-deps
sudo apt-get update
```
returns the following errors:
```
Err http://ppa.launchpad.net wily/main amd64 Packages                                              
  404  Not Found
Err http://ppa.launchpad.net wily/main i386 Packages                                               
  404  Not Found
```

```
W: Failed to fetch http://ppa.launchpad.net/staticfloat/julia-deps/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/staticfloat/julia-deps/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by tkelman** [comment]
The maintainer of the PPA hasn't had time to update it. In the meantime we recommend you use the generic linux tarballs instead of the PPA, they work on any glibc distribution and require less effort to build.

**Comment by stochasticwave** [comment]
The PPA was updated a few hours ago.

I was able to install Julia v0.4.1 from the PPA without any problems.

Thanks staticfloat!

One note:  I didn't need the julia-deps PPA (as it still throws the same errors), only the juliareleases PPA was necessary.

**Comment by kshyatt** [comment]
Seems to be resolved so I'm closing. Feel free to leave a comment asking for a reopen if this is still a problem.
