### ISSUE TITLE
"make" switches font to yellow (and doesn't switch back)

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#13926]
I just updated to Julia 0.4.1. When I type `make`, the build aborts with an error. No big deal -- I probably just need to `make clean` or something. I'm using OS X El Capitan.

However, while most of the `make` output is black-on-white (my default colours), the actual error message is yellow-on-white and almost impossible to read. Furthermore, `make` doesn't switch back to black, so that I'm left with a terminal with an unreadable font. I need to type `reset` to fix this.

This isn't a deal breaker, but it's quite annoying. First I question the use of yellow-on-white since it isn't readable. Second, not switching back to the original colour scheme is a bug.

The last lines of the error message are
```
  "_zlatms_", referenced from:
      _LAPACKE_zlatms_work64_ in libopenblas64_p-r0.2.15.a.renamed(lapacke_zlatms_work.o)
     (maybe you meant: _LAPACKE_zlatms_work64_)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libopenblas64_p-r0.2.15.dylib] Error 1
make[2]: *** [shared] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [openblas/libopenblas64_.dylib] Error 1
make: *** [julia-deps] Error 2
```

**Comment by vtjnash** [comment]
do `make -C deps clean-openblas` as mentioned at the last line of the error message.

**Comment by pao** [comment]
...but that wasn't the issue. This is a combination of "hard to read build text" and "fails to send ANSI code if build fails in a normal way."

**Comment by vtjnash** [comment]
it appears to be an openblas failure (so upstream issue). and we don't make any guarantees that a broken build (esp. of a dependency) won't be broken in other ways too. and without steps to reproduce, there's nothing we can do.

**Comment by tkelman** [comment]
The bug is
> Furthermore, make doesn't switch back to black, so that I'm left with a terminal with an unreadable font

which indicates something wrong with `ENDCOLOR`. The openblas build failure is from trying to upgrade 0.2.14 to 0.2.15 in-place in a git external with the build files all present, something about the suffix renaming doesn't work very well in incremental builds of openblas. It's easily reproducible by switching back and forth across the merge commit where I upgraded openblas versions. Would likely need tweaking in upstream's makefiles to fix.

**Comment by eschnett** [comment]
The issue appeared again. Here is the output:
```
collect2: error: ld returned 1 exit status
make[3]: *** [../libopenblas64_p-r0.2.15.so] Error 1
make[3]: Leaving directory `/xfs1/eschnetter/src/julia/deps/openblas/exports'
make[2]: *** [shared] Error 2
make[2]: Leaving directory `/xfs1/eschnetter/src/julia/deps/openblas'
[YELLOW STARTS HERE]
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [openblas/libopenblas64_.so] Error 1
make[1]: Leaving directory `/xfs1/eschnetter/src/julia/deps'
make: *** [julia-deps] Error 2
eschnetter@nvidia:/xfs1/eschnetter/src/julia (14:16:51)
```
Since I can't copy and past yellow, I manually marked the place where the font switches to yellow. This is after OpenBLAS outputs its error message. I think it's Julia switching to yellow, with line 1087 from `deps/Makefile`:
```
        @$(MAKE) -C $(OPENBLAS_SRC_DIR) $(OPENBLAS_BUILD_OPTS) || (echo $(WARNCOLOR)"*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***"$(ENDCOLOR) && false)                                                                ```

The bug may be in line 936 of Julia's `Makefile`, which only defines `ENDCOLOR` if `VERBOSE=0`. I'm using `VERBOSE=1`.

In addition to leaving things yellow, I don't like the colour yellow in the first place, as it's quite unreadable for me. Many terminals use a white or light background, and yellow is then not readable. Unless you control all colours (foreground and background), any explicit colour choice will be wrong in some cases. I suggest to use bold instead, or to choose different colours depending on the existing background colour.

**Comment by nalimilan** [comment]
Tentatively setting the backport label as requested by @eschnett.
