### ISSUE TITLE
Replace atomic_umax with type-sensitive atomic_max?

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#13931]
The current atomic operations in Base distinguish `atomic_max!` vs. `atomic_umax!` as operations, and allow both operations on `Atomic{T}` regardless of whether `T` is signed or not.  This matches LLVM's semantics, but I think it would be more appropriate for Julia if `atomic_max!` did a signed or unsigned comparison based on the signedness of type `T`, and `atomic_umax` was removed as a separate function.  Likewise for the min versions.

I'm happy to do a PR for this issue unless there is strong feeling that unsigned max should be allowed on signed integers or vice-versa.

cc: @kpamnany

**Comment by StefanKarpinski** [comment]
+1

**Comment by kpamnany** [comment]
Makes sense to me. :)

**Comment by vtjnash** [comment]
sgtm

**Comment by ArchRobison** [comment]
Closed by #13932.
