### ISSUE TITLE
stderr no longer captured by readall(cmd) and open(cmd, ...)

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#13938]
Julia 0.4:
```
julia> open(`cat -# -`, "w") do stdin;end
cat: illegal option -- #
usage: cat [-benstuv] [file ...]
ERROR: failed process: Process(`cat -# -`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:555
 in open at process.jl:501
````

Julia 0.5:
```
julia> open(`cat -# -`, "w") do stdin;end
ERROR: failed process: Process(`cat -# -`, ProcessExited(1)) [1]
 [inlined code] from error.jl:22
 in pipeline_error at process.jl:555
 in open at process.jl:501
 in eval at ./boot.jl:264
```

**Comment by tkelman** [comment]
ref cf5f23adafb4f9d1eca2ff0cdea80398ee34f799 and #13829

**Comment by yuyichao** [comment]
@JeffBezanson

**Comment by damiendr** [comment]
Also affects `readall(cmd)`.

**Comment by tkelman** [comment]
we should revert  https://github.com/JuliaLang/julia/commit/cf5f23adafb4f9d1eca2ff0cdea80398ee34f799

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/pull/14047

**Comment by yuyichao** [comment]
Should be fixed by #14047

**Comment by JeffBezanson** [comment]
I don't think we are consistent about this. I believe `spawn` hides stderr by default, which was part of the reason for this change.

**Comment by damiendr** [comment]
I agree that the status and uses of all these I/O functions is a bit unclear, to me as an outsider at least.
Documentation is a bit outdated, eg. no mention of `spawn` with more than one argument, etc.
If you come to a decision on that, it would be great if you could summarize it / link back to it in the issue I opened about the incomplete docs (#14042).

**Comment by StefanKarpinski** [comment]
I don't think that spawn should hide errors by default either.

**Comment by JeffBezanson** [comment]
Ok that's fine, we can simply say the default, in every case, is to pass through stderr.
