### ISSUE TITLE
Very slow JuMP + Knitro for nonlinear problem

### ISSUE THREAD

**Issue by ulneva** [JuliaLang/julia#13941]
I started using Julia with Knitro through Julia's JuMP for mathematical programming. I noticed that a small nonlinear problem with 33 variables and just over 300 non-zeros in Hessian takes quite a lot of time to generate and solve. While slow generation can be attributed to Julia's JuMP, Knitro itself takes as much as 15 minutes to solve the above problem, though it takes only 12 iterations? Would you be able to have a look? I can send you the code.

The analogous problem in AMPL+KNITRO takes a few seconds to generate and solve.

**Comment by IainNZ** [comment]
Hi @ulneva, this is a JuMP-specific issue (probably), so please re-open this issue here: https://github.com/JuliaOpt/JuMP.jl/issues

**Comment by ViralBShah** [comment]
For anyone who stumbles upon this issue, the JuMP issue is:

https://github.com/JuliaOpt/JuMP.jl/issues/614
