### ISSUE TITLE
Document A_ldiv_B!

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#13940]
The docs don't have an entry for `A_ldiv_B!`, but it has (in version 0.4.0-rc3) 37 methods.  Adding a short entry to the docs specifying the order of the arguments would be very helpful.

**Comment by nalimilan** [comment]
Would you make a PR to fix that?

**Comment by JaredCrean2** [comment]
Sure, but I have never done  PR before.  Can you talk me through it?

**Comment by jiahao** [comment]
@JaredCrean2 start with https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation and feel free to ask if you have any questions. (If you have questions, then probably you've found a place to improve the CONTRIBUTING docs too.)

**Comment by jiahao** [comment]
Closing as duplicate of #13110
