### ISSUE TITLE
rand(::BigFloat)

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#13948]
We once had a `rand!` for BigFloats using mpfr_urandom, see #4845.
Apparently this got removed/got lost. As said in #9836 "probably not high priority other than for completeness". I ran into this when calling iterative algorithms parametrized by element-type T which starting from a random vector  rand(T,n).

**Comment by stevengj** [comment]
Apparently it got reverted by @ViralBShah because it broke the build: 1a8885b66012edce3282f1b70c9cd32e3d81c706

**Comment by mschauer** [comment]
I looked at it - oh man - that is bit tricky: mpfr really wants to use the gmp random number generator and does not allow to provide entropy directly.

**Comment by StefanKarpinski** [comment]
We may have to fork it – it wouldn't be the first time :-\. Longer term the MPFR project may be receptive to upstreaming changes that allow using other sources of entropy.

**Comment by mschauer** [comment]
I made a PR with a let's call it economic approach without attempting to circumvent GPM.

**Comment by mschauer** [comment]
cc @andrioni
