### ISSUE TITLE
Unexpected include results

### ISSUE THREAD

**Issue by tkonolige** [JuliaLang/julia#13944]
When importing a file into the repl with `include`, global variables in the repl are added to the scope of the included file. This leads to very unexpected results.

Here is a simple example:
```julia
# This is the source of file test.jl
function f(x)
    z + 1 # accidentally used z when x was intended
end
```

Now in the repl:
```julia
julia> include("test.jl")
f (generic function with 1 method)

julia> f(2) # we expect an error
ERROR: UndefVarError: z not defined
 in f at .../test.jl:2
 in eval at ...

julia> z = 3 # define z now
3

julia> include("test.jl")
f (generic function with 1 method)

julia> f(2) # we expect this call to produce an error too, but it does not
4
```

**Comment by yuyichao** [comment]
`include` doesn't create a new scope (which is why you can call the functions in the included file directly). Create a `module` in the included file if you want to separate the scope.
