### ISSUE TITLE
missing backtrace after task switch

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#13947]
Normal backtrace:

``` julia
# file test.jl
try
    error("test")
catch e
    rethrow(e)
end
```

```
$ julia test.jl
ERROR: LoadError: test
 in test at test.jl:4
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading test.jl, in expression starting on line 10
```

Missing backtrace when using print in the catch block:

``` julia
# file testprint.jl
try
    error("test")
catch e
    println("error")
    rethrow(e)
end
```

```
$ julia testprint.jl
error
ERROR: LoadError: test
while loading testprint.jl, in expression starting on line 5
```

Works fine when run from the REPL:

```
julia> include("testprint.jl")
error
ERROR: LoadError: test
 in error at ./error.jl:21
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in eval at ./boot.jl:264
while loading testprint.jl, in expression starting on line 5
```

Happens both in Julia 0.4 and the latest 0.5-dev.

**Comment by JobJob** [comment]
What OS are you using? I couldn't replicate on OSX

**Comment by damiendr** [comment]
I get this behaviour on the following platforms:
```
OSX 10.9.5
Julia Version 0.5.0-dev+1231
Commit f174d12* (2015-11-10 19:27 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
```
Linux Mint (3.13.0)
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

It seems to be dependent on previous writes: adding `println("hello")` before the `try...catch` block in my example makes the backtrace appear. Conversely I've had backtraces disappear in situations where there were things printed before. Maybe a missing `flush()` or something?

**Comment by damiendr** [comment]
In fact even adding `println("")` at the start makes the backtrace appear.

**Comment by JobJob** [comment]
Ok so I had some printing happening in my .juliarc.jl, when I disabled that I'm able to reproduce (on OSX) using this method above:

    # file testprint.jl
    try
        error("test")
    catch e
        println("error")
        rethrow(e)
    end

but not with a `println` before the `try`

**Comment by damiendr** [comment]
Also happens in cells of the IJulia notebook, one cell counting as one file of the above examples. Which is how I came across this bug, since cells are more likely than whole files to meet the conditions that trigger the bug.

**Comment by KristofferC** [comment]
Closing in favour of https://github.com/JuliaLang/julia/issues/19979.
