### ISSUE TITLE
RFC: Improve svds 

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13957]
- [ ] The first 3 output quantities `(left_sv, s, right_sv)` could be put into an `SVD` object if `ritzvec = true`, so that the number of outputs from `svds` would always be the same, with the type of the first output being a `Vector` of singular values if `ritzvec=false` and a `SVD` if `ritzvec=true`. (In reality the `SVD` is now representative of an incomplete singular value decomposition rather than a full calculation, but I think the chance of confusion is low.)

- [ ] The current docs say that the 6th positional output is `nmult`, but it does not explain what a "mult" is in this context. The documentation should explain that a "mult" is a single evaluation of the `A'A` operator, since it's no longer clear which of A'A*v, A'v or A*v is the product in question.

- [ ] `svds` should accept a `ncv` kwarg, which controls the maximum size of Krylov subspace used, and is passed directly to the underlying call to `eigs` anyway.

- [ ] `svds` should accept a `v0` kwarg to specify the initial Krylov vector; ref #10330

**Comment by ViralBShah** [comment]
+1 to all proposed changes.

**Comment by tkelman** [comment]
If `svds` will need to be used in an inner-loop where its type stability would matter, then the `ritzvec=false` case should possibly be separated to a different method name - `svdsvals` maybe?

**Comment by jiahao** [comment]
Yeah, type stability of the first output is a concern for me. But note the current situation is already type unstable, since you get either a 5-tuple or 7-tuple depending on whether `ritzvec=false` or `true`.

Another possibility is to always return an `SVD` object, and populate only the fields that are asked for. But that seems uglier.

**Comment by StefanKarpinski** [comment]
The idea of having a separate `svdsvals` is appealing – especially given the analogue to `eigvals`.

**Comment by kshyatt** [comment]
big +1 to `svdsvals`. This seems like a big fat target for doc improvements.

**Comment by tkelman** [comment]
I kind of prefer the single object with some undefined fields option as it's a bit cleaner IMO, and more like what we do with factorization objects

**Comment by jiahao** [comment]
The SVD object could simply have n x 0 and m x 0 matrices in the :U and :V fields if they are not asked for, and the singular values can go in :S in either case. That way, an SVD object is always returned and no field is ever uninitialized (it is bound to either an empty array or a nonempty array). svdsvals can be a thin wrapper over svds(... ritzvec=false)[1][:S].

**Comment by tkelman** [comment]
Also seems like a lot of the iteration counts, residuals, optional convergence histories, etc would be nicer as a single "solvestats" return object rather than multiple outputs where you always have to look up what order things get returned in.

**Comment by jiahao** [comment]
Yes, I provide such an object in `IterativeSolvers.ConvergenceHistory`. However, I'm thinking of changing it to a simple Dict, since not all algorithms provide the same diagnostic information.

**Comment by kshyatt** [comment]
Just leaving a little crumb here that the doc improvement for `mult` can still happen.
