### ISSUE TITLE
Proposal: additional `all`/`any` methods for nary predicates

### ISSUE THREAD

**Issue by gajomi** [JuliaLang/julia#13964]
I propose adding methods for `all` and `any` to allow for convenient testing of nary predicates. The behavior would be equivalent to that given by

``` julia
myall(f,itrs...) = all(map(args->f(args...),zip(itrs...)))
```

but with an efficient implementation along the lines of the current `all(f,itr)` method (same thing for `any`). This additional signature is directly analogous to the extant generalization for `map` methods and allows for things like

``` julia
julia> xs,Xs = 1:3,[Set([1,2]),Set([2,5]),Set([3])]
julia> myall(in,xs,Xs)
true
```

which saves one from having to zip and splat for nary functions.

**Comment by mbauman** [comment]
This precedes it, but it's a duplicate with #20181.  Since that has more discussion, closing in favor of it.
