### ISSUE TITLE
Why name `julia`?

### ISSUE THREAD

**Issue by hyiltiz** [JuliaLang/julia#13965]
I cannot seem to find anywhere (maybe did not search enough) why you call her `julia`. Any story behind it? Maybe we should consider putting it in the docs introduction part?

**Comment by nalimilan** [comment]
Please use the mailing list for questions and discussions, and reserve GitHub for bug reports. Thanks!

(Regarding the question itself, I think you'll find a few threads in the mailing list archives, but no official reply is likely to come. :-)
