### ISSUE TITLE
LAPACK-Julia: Invalid argument #3 to LAPACK call 

### ISSUE THREAD

**Issue by rieser** [JuliaLang/julia#13976]
Similar to https://github.com/JuliaLang/julia/issues/12294, which was closed. What does this indicate?

```
** On entry to DGEBAL parameter number  3 had an illegal value
ERROR: LoadError: ArgumentError: invalid argument #3 to LAPACK call
 in gebal! at linalg/lapack.jl:158
 in expm! at linalg/dense.jl:197
 in expm at linalg/dense.jl:186
 [inlined code] from ...
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading ...
```

**Comment by tkelman** [comment]
please post full reproduction code and the output of `versioninfo()`

**Comment by rieser** [comment]
Versioninfo is here. I'll get the code soon.

Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD A10-5800B APU with Radeon(tm) HD Graphics
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Steamroller)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by tkelman** [comment]
Just guessing right now, but it's likely this could be an OpenBLAS bug due to the AMD processor. Is this a source build (with in Make.user?) or a binary (from where)? What distribution?

**Comment by rieser** [comment]
Binary, from the .deb package on the Julia website.

**Comment by tkelman** [comment]
Can you try with the generic Linux tarball binaries? https://julialang.s3.amazonaws.com/bin/linux/x64/0.4/julia-0.4.1-linux-x86_64.tar.gz

**Comment by rieser** [comment]
I get the same error.

**Comment by rieser** [comment]
The matrix it seems to be having trouble with is a 70 x 70 matrix whose entries are -0.0 except for a few which are NaN. I'm having trouble reproducing the error in a minimal working example outside of my program, though. Will keep you updated.

**Comment by ViralBShah** [comment]
How does one reproduce this one? A code snippet and data perhaps would help.

**Comment by rieser** [comment]
Sorry, this took a while to find. Here's a minimal working example from the
REPL:

---------------------------------------------------------------------------------------------------------
julia> A = [NaN 0.0 NaN; 0 0 0; NaN 0 NaN]
3x3 Array{Float64,2}:
 NaN    0.0  NaN
   0.0  0.0    0.0
 NaN    0.0  NaN

julia> expm(A)
 ** On entry to DGEBAL parameter number  3 had an illegal value
ERROR: ArgumentError: invalid argument #3 to LAPACK call
 [inlined code] from strings/io.jl:43
 in gebal! at linalg/lapack.jl:158
 in expm! at linalg/dense.jl:197
 in expm at linalg/dense.jl:186
 in eval at ./boot.jl:263
----------------------------------------------------------------------------------------------------------

BUT

----------------------------------------------------------------------------------------------------------
julia> B = [NaN 0.0 0.0; 0 0 0; NaN 0 NaN]
3x3 Array{Float64,2}:
 NaN    0.0    0.0
   0.0  0.0    0.0
 NaN    0.0  NaN

julia> expm(B)
3x3 Array{Float64,2}:
 NaN  NaN  NaN
 NaN  NaN  NaN
 NaN  NaN  NaN
----------------------------------------------------------------------------------------------------------

appears to work fine. It looks like the symmetry of the matrix is a problem.

**Comment by rieser** [comment]
My current versioninfo() output is:

julia> versioninfo()
Julia Version 0.5.0-dev+1331
Commit 9d6dee5 (2015-11-18 04:38 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD A10-5800B APU with Radeon(tm) HD Graphics
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Steamroller)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by andreasnoack** [comment]
I can reproduce this and if you look at line 336 in the [source](http://www.netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational.html#ga411292dd693c20ff9c27650fb7bddf85), there is a check for `NaN`s during the scaling step, but only a submatrix is checked. The submatrices depend on the permutation step, so `B` will actually fail if you only scale, i.e. `LAPACK.gebal('S', B)`.

Either we should check for `NaN` before entering LAPACK, but it is probably easier just to check if `info==-3`.

Do you want to make a PR? That would be very welcome.
