### ISSUE TITLE
conv is slower than necessary

### ISSUE THREAD

**Issue by sloisel** [JuliaLang/julia#13996]
It seems that `conv` is slower than necessary. By implementing a naive convolution, I am able to outperform `conv` for moderate vector sizes. On my particular machine, naive convolution is better than `conv` if the product of vector sizes is less than 100 000.

Just so everyone sees what the naive solution is, I'm pasting it below.

``` jl
slowconvcost(m,n) = 2e-9*m*n+1e-6
fastconvcost(m,n) = 7e-8*(m+n)*log(m+n)+1e-4
function sebconv{T}(a::Array{T}, b::Array{T})
    m = length(a)
    n = length(b)
    if(fastconvcost(m,n)<slowconvcost(m,n)) return conv(a,b); end
    c = zeros(T,m+n-1)
    @inbound for j=1:m
        for k=1:n
            c[j+k-1] += a[j]*b[k]
        end
    end
    return c
end
```

Here is a performance plot:

![convperf](https://cloud.githubusercontent.com/assets/789084/11166795/213245de-8b3e-11e5-8b05-6c44862c7c3d.png)

Edit: tweaked code for better heuristic as to when slowconv is faster than fastconv.

**Comment by simonster** [comment]
You can also use `filt(y, 1, [x; zeros(length(y)-1)])` to perform convolution, where `x` is the longer of the two vectors and `y` is the shorter one.

DSP.jl has an implementation of `filt` that decides whether or not to use the FFT algorithm based on the vector lengths. The FFT algorithm in DSP.jl should also be a little more efficient than `conv` when one vector is much longer than the other, since it does overlap-save. I guess we could move that here, but that seems contrary to #5155.

**Comment by sloisel** [comment]
`filt` seems to run at the same speed as naive convolution. I've tested that my switching heuristic (between naive and FFT) above seems to be the correct one at all scales.

![convperf](https://cloud.githubusercontent.com/assets/789084/11169985/be314454-8bbe-11e5-8350-c0658f8e6865.png)
![convperf2](https://cloud.githubusercontent.com/assets/789084/11169986/c05a98f2-8bbe-11e5-87c0-0fb2d717539f.png)

**Comment by dehann** [comment]
FYI: recent work at MIT [Accelerated Convolutions for Efficient Multi-Scale Time to Contact Computation in Julia
 (link to pdf on arxiv)](https://arxiv.org/pdf/1612.08825) of which the implementation should be available somewhere. First author repos seem empty though. [aamini/FastConv.jl](https://github.com/aamini/FastConv.jl) and issue aamini/TimeToContact.jl#1.

Maybe you already know about this and have it wrapped in, but I can't find it and then this pointer might be useful to others also.

**Comment by aamini** [comment]
Thanks for the mention. Both packages have been updated. 
Fast convolutions for Julia: [amini/FastConv.jl](https://github.com/aamini/FastConv.jl/)
Time to Contact in Julia: [amini/TimeToContact.jl](https://github.com/aamini/TimeToContact.jl/)

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaDSP/DSP.jl/issues/167
