### ISSUE TITLE
Pkg doesn't create UVError correctly on master

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13991]
```jl
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: type UVError has no field msg
 in update at ./pkg/entry.jl:357
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:47
 in cd at pkg/dir.jl:31
 [inlined code] from ./pkg/dir.jl:25
 in update at ./pkg.jl:48
 in eval at ./boot.jl:264
```

**Comment by tkelman** [comment]
If we're going to do a bad job of trying to turn errors into warnings, we should probably let the error get thrown and skip the try catch.

**Comment by tkelman** [comment]
What does the actual UVError say if you comment out the try-catch?

**Comment by jiahao** [comment]
I actually don't know - it wasn't reproducible. All I know was that my system was really busy at the time.
