### ISSUE TITLE
`findin` wrong for `UnitRange`

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#14004]
`findin` is buggy with unit ranges:
```
julia> findin([5.2, 3.3], 3:20)
2-element Array{Int64,1}:
 1
 2
```
expected would be
```
julia> findin([5.2, 3.3], 3:1:20)
0-element Array{Int64,1}

julia> findin([5.2, 3.3], collect(3:20))
0-element Array{Int64,1}
```
This was discussed on julia-users by @hayd but (I think) it never made it into the issue tracker.
https://groups.google.com/d/msg/julia-users/Qpe7yzPMzjA/qDXQRAA6BgAJ

**Comment by mschauer** [comment]
Closed by #14004 .

**Comment by KristofferC** [comment]
This is #14004

**Comment by mschauer** [comment]
Sorry, #14648

**Comment by ivarne** [comment]
Seems to be fixed anyway :+1:
