### ISSUE TITLE
Unify `@testset` and `@testloop`?

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#14011]
Re-opened from https://github.com/IainNZ/BaseTestNext.jl/issues/6. @IainNZ 

The current `Base.Test` module implements two macros that group tests: `@testset` and `@testloop`. These macros are very similar and I think these can be unified into a single macro like below:

```julia
@testset begin
    @test ...
end

@testset for i in 1:10
    @test ...
end
```

Since macros can detect the type of given expression block, I think rewriting `@testset for ...` to a loop test is not so difficult.

**Comment by tkelman** [comment]
+1

**Comment by StefanKarpinski** [comment]
I like it.

**Comment by IainNZ** [comment]
Pinging @simonbyrne (who implemented `@testloop`), and @ssfrr 
I like this idea too, if there are no technical problems we're overlooking

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/julia/pull/14148 implements this, and is ready for review/sanity check.
