### ISSUE TITLE
problem of conversion from sparse matrix slice to sparse vector

### ISSUE THREAD

**Issue by mingsystemx** [JuliaLang/julia#14013]
hello,

the conversion between sparse matrix line and sparse vecteor is not correct

julia> aa = sparse([10. 0 30.])
1x3 sparse matrix with 2 Float64 entries:
    [1, 1]  =  10.0
    [1, 3]  =  30.0

julia> full(aa[1,:])
3-element Array{Float64,1}:
 10.0
 30.0
  0.0

the zeros coefficient has been misplaced in the sparse vector.

this happens in the development branch
Version 0.5.0-dev+1265 (2015-11-13 08:40 UTC)
Commit f045831 (0 days old master)
x86_64-linux-gnu

...and just a comment about
https://github.com/JuliaLang/julia/pull/13440

the direction taken by sparse arrays (matrix or vector) library is questionable in my opinion. if a line or column slice of a sparse matrix is transformed into a sparse vector, with a different internal implementation, then you will prevent people from passing slices like a[k,:] to libraries. in my opinion, more generally, the implicit conversion of matrix slices like a[k,:] or a[:,k] into vectors will reduce drastically the main quality of Julia : "it's very easy to plug algorithms between them". we will have to write special case for slices every time.

bests,
M.

**Comment by andreasnoack** [comment]
cc: @mbauman 

@mingsystemx Regarding your last point, then notice that you can easily get what you want with e.g. `a[k:k,:]`.

**Comment by mingsystemx** [comment]
hello,
I dont like tricks... if some day, a Julia developper says : OMG, a[k;k,:] is not converted to vector, I'll correct this bug... my code is dead.
I prefer to rely on specifications. currently I have done something like this :
git checkout v0.4.1
actually, I found this bug by mistake :) I forgot to checkout the stable release after cloning julia.git !
bests,
M.

**Comment by nalimilan** [comment]
@mingsystemx `a[k:k,:]` is not a trick, that's the documented behavior.

**Comment by ViralBShah** [comment]
This is a much discussed point, and the behaviour for sparse is now consistent with the dense behaviour.

**Comment by mingsystemx** [comment]
ok, this is the following rule : Trailing dimensions indexed with scalars are dropped
http://docs.julialang.org/en/release-0.4/manual/arrays/

**Comment by nalimilan** [comment]
In 0.5, this rule changes: now *all* dimensions indexed with a scalar are dropped.
