### ISSUE TITLE
Correctness of the Ziggurat method

### ISSUE THREAD

**Issue by jameslao** [JuliaLang/julia#14010]
I'm recently studying the Ziggurat method and see that `julia/test/perf/kernel/ziggurat.jl` is directly ported [http://m.seehuhn.de/data/ziggurat/gauss.c](http://m.seehuhn.de/data/ziggurat/gauss.c). However, when looking at these numbers, starting from `const PARAM_R = 3.44428647676`, I find them not matching what I calculated. These valued are generated from [http://m.seehuhn.de/data/ziggurat/ziggurat.c](http://m.seehuhn.de/data/ziggurat/ziggurat.c)

The problem with this generated value is, in `ziggurat.c`, line 48, when it tries the r value, the formula to calculate the initial v value is 

`v = r*f(r) + exp(-0.5*r*r)/r;`

This is not what *v* should be... the second item on the right should be the integral from *r* to infinity, namely the erfc function.

To further support this claim, in [https://github.com/sarahr/QVMC/blob/master/zignor.c](https://github.com/sarahr/QVMC/blob/master/zignor.c), this improved method from Doornik has `R = 3.442619855899`. The code from the original paper [http://www.jstatsoft.org/article/downloadSuppFile/v005i08/rnorrexp.c](http://www.jstatsoft.org/article/downloadSuppFile/v005i08/rnorrexp.c) also gives `R=3.442620`. I verified with 1-CDF and this is the correct value (error to the order of 1e-12).

Since this R value is wrong all the tables are wrong.

**Comment by andreasnoack** [comment]
First of all, I'd like to point out that the tables in https://github.com/JuliaLang/julia/blob/aa24ee0d0f334e8d9ecbced64bd975a6cc5f240d/test/perf/kernel/ziggurat.jl are only used for performance testing and they are not the tables use in our `randn`. These are in https://github.com/JuliaLang/julia/blob/aa24ee0d0f334e8d9ecbced64bd975a6cc5f240d/base/random.jl#L612

I agree that it Jochen Voss' implementation is slightly different from Massaglia and Tang's, but it doesn't necessarily make it wrong. Voss' implementation is now included in Gnu Scientific Library so it would be quite bad if it was flawed, but [his testing](http://www.seehuhn.de/pages/ziggurat) is not convincing. It is surprising that he is not using [TestU01](https://www.iro.umontreal.ca/~simardr/testu01/tu01.html) for the testing.

I have a [wrapper package](https://github.com/andreasnoack/RNGTest.jl) for TestU01 and I've just started the BigCrush test suite on Voss' implementation so we'll probably know the result in the afternoon. It passes the SmallCrush test suite, but that is also a quite low bar.

**Comment by andreasnoack** [comment]
The tests in BigCrush have finished and none of them fail so I don't think the tables are wrong, only different.

**Comment by tkelman** [comment]
Hm, the license header on that ziggurat.jl file is probably wrong given https://github.com/JuliaLang/julia/issues/8248#issuecomment-54707593 - if it's derived from GPL code we should probably move it to a different repository.
