### ISSUE TITLE
Infinite loop when calling `Pkg.update(); Pkg.add()` from a .juliarc.jl file

### ISSUE THREAD

**Issue by aytekinar** [JuliaLang/julia#14012]
Hey,

I am experiencing a problem when I try to start julia with the following `.juliarc.jl` file:

``` julia
# Change to the default julia directory
const JuliaHome = expanduser( "~/Documents/My_Julia" )
push!( LOAD_PATH, JuliaHome )

if !isdir( JuliaHome )
    info( "Creating the $(JuliaHome) directory ..." )
    mkdir( JuliaHome, 0o700 )
end

info( "Changing directory to $(JuliaHome) ..." )
cd( JuliaHome )

# Update the package repository
info( "Updating the package repository ..." )
Pkg.update()

# Install the Convex package for convex optimization
if typeof( Pkg.installed( "Convex" ) ) == Void
    info( "Installing the Convex package ..." )
    Pkg.add( "Convex" )
end
```

The problem is that julia can find the corresponding `Convex` package and installs the package. However, it restarts (I assume) again with the corresponding `.juliarc.jl` file without updating its local package cache (`Convex` already installed). I assume this behaviour since it removes the `Convex` package and tries reinstalling it, which goes on forever. The same applies when I `julia -f` and run `Pkg.add( "Convex" )` manually. Upon installing, julia restarts again with the `.juliarc.jl` file and the above problem is there again.

If, however, I remove `.juliarc.jl` file and do everything manually, everything is working fine.

I hope you helped me solve the problem.

P.S: `Convex` package is just an example --- the same problem occurs for packages like `Mosek`, `Gurobi`, `PyPlot`, etc.

**Comment by vtjnash** [comment]
Pkg.add runs a subprocess of julia to build and verify the result of Pkg.add before committing the result. However, you've inserted a call to `Pkg.update` in the startup process, which sees that the package state is inconsistent and removes the unused package.

**Comment by aytekinar** [comment]
@vtjnash thanks for the information. I needed to open this issue, because it used to work properly before the latest update(s). Which (automated) way should be the solution in this situation? Putting `Pkg.update()` to the very end, after all the conditional `Pkg.add(...)`s does not work either.

**Comment by simonbyrne** [comment]
This should be largely resolved by the new Pkg (or at least, this workflow is now discouraged). If you find further problems, please open an issue at https://github.com/JuliaLang/Pkg.jl
