### ISSUE TITLE
Build fails with JULIA_THREADS=1

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#14028]
On master, starting at ab9389c.
```
$ make
    JULIA usr/lib/julia/inference0.ji
/home/sachs/src/julia-multithreading/usr/bin/julia: symbol lookup error: /home/sachs/src/julia-multithreading/usr/bin/../lib/libjulia.so: undefined symbol: jl_set_stackbase
make[1]: *** [/home/sachs/src/julia-multithreading/usr/lib/julia/inference0.ji] Error 127
make: *** [julia-inference] Error 2
```

**Comment by ArchRobison** [comment]
I'm looking at it and will attempt a fix.

Looks like b238ac2815a46cc021aa8e2a109f1ba292df69c3  removed `jl_set_stackbase` on Sept. 10, though I thought I had built the multi-threaded version successfully last week.  It must be some aspect of git merging that I don't understand.

**Comment by tkelman** [comment]
If you follow the link to the pull request that commit came from, https://github.com/JuliaLang/julia/pull/13963, it was only merged 2 days ago.

**Comment by ArchRobison** [comment]
Thanks for the enlightenment.  It hadn't registered with me that merging preserves the original date.
