### ISSUE TITLE
UDP socket test failure with egress firewall

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14040]
The following UDP broadcast test in `test/socket.jl` fails on a firewalled system:

```julia
function create_socket()
    s = UDPSocket()
    bind(s, ip"0.0.0.0", 2000, reuseaddr = true, enable_broadcast = true)
    s
end
a, b, c = [create_socket() for i = 1:3]
@sync begin
    recvs = [@async @test bytestring(recv(s)) == "hello" for s in (a, b)]
    send(c, ip"255.255.255.255", 2000, "hello")
    map(wait, recvs)
end
[close(s) for s in [a, b, c]]
```

The `send` from `0.0.0.0` to `255.255.255.255` triggers an `EPERM` due to an egress firewall. Disabling the firewall works, but the packet does really escape to the local network, which might be unwanted in some situations.

I realize this is a minor detail, but due to the test failing it might be better to protect the test against this situation. I did consider wrapping in a `try` and catching `LoadError`, but due to the inner `errno` not being available that would mean string-matching against `EPERM` which isn't terribly neat. Any ideas?

**Comment by maleadt** [comment]
On another system, I've spotted the _ingress_ firewall blocking the package. Worse, because it is configured with `DROP` rather than `REJECT`, the test-suite just hangs.

**Comment by sbromberger** [comment]
> Disabling the firewall works, but the packet does really escape to the local network, which might be unwanted in some situations.

Just curious - why would you expect this not to escape to the local network? This is how DHCP discover works (well, src port 68, dst port 67).

**Comment by maleadt** [comment]
Strictly controlled corporate networks? You're probably right, a single random packet shouldn't matter. But firewalls (either egress or ingress, depending on the configuration both have a say here) are much more common, and the test suite shouldn't error out or hang depending on the user's configuration.

**Comment by sbromberger** [comment]
well, yes - I think having active network traffic as part of a test is probably a bad idea. I misread your objection as a question as to why 0.0.0.0 -> 255.255.255.255 UDP traffic was network-visible in the first place.
