### ISSUE TITLE
OpenBlas Build Error

### ISSUE THREAD

**Issue by QnnLu** [JuliaLang/julia#14054]
I get the following error when trying to compile a fresh checkout of release-0.4:
      ...
  "___trunctfdf2", referenced from:
      _write_float in libgfortran.a(write.o)
      _cbrtq in libquadmath.a(cbrtq.o)
      _sqrtq in libquadmath.a(sqrtq.o)
  "___trunctfxf2", referenced from:
      _cbrtq in libquadmath.a(cbrtq.o)
      _sqrtq in libquadmath.a(sqrtq.o)
  "___unordtf2", referenced from:
      _write_float in libgfortran.a(write.o)
      _expq in libquadmath.a(expq.o)
      _cacoshq in libquadmath.a(cacoshq.o)
      _casinhq in libquadmath.a(casinhq.o)
      _catanhq in libquadmath.a(catanhq.o)
      _catanq in libquadmath.a(catanq.o)
      _fdimq in libquadmath.a(fdimq.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libopenblas64__nehalem-r0.2.15.dylib] Error 1
make[2]: *** [shared] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0 if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [openblas/libopenblas64_.dylib] Error 1
make: *** [julia-deps] Error 2

I followed the cleaning instruction of the webpage and the ones above. I ran make with both options above too.

My OS is OS X Yosemite, version 10.10.5. My Xcode is version 7.1.1.

**Comment by mauro3** [comment]
I've seen those too on Linux.  But on a fresh clone it worked.

**Comment by tkelman** [comment]
Where did you get gfortran? Looks like your libquadmath is broken.

**Comment by nalimilan** [comment]
I think I've seen it too, and worked around it by removing the OpenBLAS directory and/or running a single-threaded `make`.

**Comment by QnnLu** [comment]
I solved the issue, following @tkelman suggestion. It seems that some update I did broke gfortran.
Thank you all for your comments.
