### ISSUE TITLE
Profiling causes EXCEPTION_ACCESS_VIOLATION on Windows (PyCall)

### ISSUE THREAD

**Issue by kafisatz** [JuliaLang/julia#14068]
Hi all

the line 78
    test=write_statistics(xxl,f)
fails (Julia crashed) when it is preceded with `@profile` if the data `xxl` is sufficiently large.
At the bottom of the text file one can find the bug report and my versioninfo.

I tried to make this example as small as possible. I apologize if I should have submitted this under the PyCall package. Given that the code is working without  `@profile` PyCall seems to work fine though.

[test_write_excel_isolated_submit.txt](https://github.com/JuliaLang/julia/files/40024/test_write_excel_isolated_submit.txt)

**Comment by KristofferC** [comment]
Thanks for the detailed bug report. Since a lot of things have changed since this issue is posted I will close it but if you have the opportunity to try it again and it still crashes just post a comment.

**Comment by yuyichao** [comment]
This is still a problem. Though I believe we have other bugs tracking this.
