### ISSUE TITLE
copysign returns incorrect result when its second argument is NaN or Inf

### ISSUE THREAD

**Issue by zygmuntszpak** [JuliaLang/julia#14070]
##These tests pass
`@test isnan(copysign(0/0,1))`
`@test isnan(copysign(0/0,-1))`
`@test isinf(copysign(1/0,1))`
`@test isinf(copysign(1/0,-1)) `

 ##These  tests  fail (Julia 0.4.1)
`@test isnan(copysign(1,0.0)) `
`@test isnan(copysign(-1,0.0))`
`@test isinf(copysign(1,1/0))`
`@test isinf(copysign(-1,1/0))`

I have create a pull-request #14069 for these and other tests of the copysign function
but have commented out the fail cases in the pull-request

```Julia Version 0.4.1
Commit cbe1bee* (2015-11-08 10:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3```

**Comment by StefanKarpinski** [comment]
I'm not sure how those last four tests could be true or convinced that they should be.

**Comment by vtjnash** [comment]
```
julia> copysign(-1,0/0)
-1
julia> copysign(1,-NaN)
-1
julia> copysign(1,NaN)
1
```
So 0/0 is actually `-NaN`?

**Comment by StefanKarpinski** [comment]
That's what `divsd %xmm0, %xmm1` produces when 0.0 is in both registers.

**Comment by StefanKarpinski** [comment]
Integers cannot be NaN or infinite, so it's not possible for `copysign` to preserve NaNness or infiniteness. Also, sign is an independent property from whether a number is NaN or infinite – NaNs have signs, as do Infs. Therefore it's perfectly sound to copy the sign of a NaN or an infinite value.

**Comment by eschnett** [comment]
Let me try to give a slightly more detailed explanation:
- `Inf` and `-Inf` are regular `Float64` numbers. They can be positive or negative, and their sign is extracted by `copysign`. There is no reason that an infinite second argument should lead to an infinite result.
- `copysign` is special in that a `NaN` as second argument is not contagious, and thus the result should not be `NaN` either.
- `NaN`s don't have a sign; instead, they are either "signalling" or "non-signalling". This information happens to be stored in the sign bit. I don't think its worthwhile checking this property.

In view of this, the problem reported here is not actually a problem. Marking this `won't fix` is a bit strange -- I would have marked it `invalid` instead, as `won't fix` sounds like an actual bug that cannot be corrected for some reason (backward compatibility, lack of manpower).

**Comment by zygmuntszpak** [comment]
Thanks for all the clarifications. Upon reading Stefan's comment "...how those last four tests could be true or convinced that they should be." I realised what I had submitted was non-nonsensical and moreover contained typos  `@test isnan(copysign(-1,0.0))` was supposed to have been `@test isnan(copysign(-1,0/0))`. I apologise!

**Comment by StefanKarpinski** [comment]
@zygmuntszpak, please don't apologize – on the contrary, I should apologize for my excessively terse initial comment (I think it was first thing in the morning). Thank you for the tests and for the bug report!
