### ISSUE TITLE
Precision of now()

### ISSUE THREAD

**Issue by JobJob** [JuliaLang/julia#14088]
Currently, `now()` (https://github.com/JuliaLang/julia/blob/master/base/dates/conversions.jl#L22-L25) only provides precision to the second (as in 1000 milliseconds), i.e. `Dates.millisecond(now())` is always zero. IMO it would be good if `now()` was as precise as DateTime allows (currently millisecond precision). Additionally, `now(Dates.UTC)` (https://github.com/JuliaLang/julia/blob/master/base/dates/conversions.jl#L27) does provide millisecond precision (but gives UTC time, not local time).

Something like the following would achieve this simply:

    function now()
        t = time()
        tm = Libc.TmStruct(t)
        ms = floor((t - floor(t))*1000)
        return DateTime(tm.year+1900,tm.month+1,tm.mday,tm.hour,tm.min,tm.sec,ms)
    end

What are people's thoughts? @quinnj @omus @Michael-Klassen

**Comment by omus** [comment]
It is definitely seems inconsistent that `now()` returns second precision and `now(::Type{Dates.UTC})` while provides millisecond precision.

**Comment by stevengj** [comment]
Why can't `now()` return millisecond precision?

**Comment by omus** [comment]
The core of the issue comes from the C call to `localtime_r` that requires a C struct tm which contains only up to second precision.

**Comment by stevengj** [comment]
@omus, can't you call `gettimeofday` on Unix and `GetLocalTime` on Windows?

**Comment by omus** [comment]
Wrote up a millisecond now implementation that works only on Linux currently but is as efficient as the current implementation:
```julia
import Base.Libc: TmStruct

type TimevalStruct
    sec::Int64
    usec::Int64
end

function TimevalStruct()
    tv = TimevalStruct(0.0,0)
    ccall(:gettimeofday, Int, (Ptr{TimevalStruct}, Ptr{Void}), &tv, C_NULL)
    return tv
end

function now()
    tv = TimevalStruct()
    tm = TmStruct(tv.sec)
    DateTime(tm.year+1900,tm.month+1,tm.mday,tm.hour,tm.min,tm.sec,floor(tv.usec/1e3))
end
```

**Comment by omus** [comment]
@stevengj we'll still need to do the call to `localtime_r` (within the call to `TmStruct`). It seems we're thinking along the same lines

**Comment by JobJob** [comment]
Ok so I wrote a modified `clock_now` in timefuncs.c called `clock_local`:

    double clock_local(void)
    {
    #if defined(_OS_WINDOWS_)
        return floattime();
    #else
        struct timeval now;
        struct timezone tz;
        gettimeofday(&now, &tz);
        now.tv_sec -= (tz.tz_minuteswest*60);
        return tv2float(&now);
    #endif
    }

added it to timefuncs.h and created a `localtime()` function in Libc.jl: 

    localtime() = ccall(:clock_local, Float64, ())

then I defined 

    now2() = Dates.unix2datetime(localtime())
    function nowtest(f, N=1e7)
        for i = 1:N
            f()
        end
    end

The results:

    @time nowtest(now)
    3.918670 seconds (20.00 M allocations: 762.940 MB, 1.70% gc time)

    @time nowtest(now2)
     0.662890 seconds (10.00 M allocations: 152.613 MB, 1.41% gc time)

I'd have to write the windows version, but this speed up is nice. Pretty sure it's the use of the TmStruct stuff thats slow:

    nowutc() = Dates.unix2datetime(time())
    @time nowtest(nowutc)
    0.649206 seconds (10.00 M allocations: 152.611 MB, 0.99% gc time)

I'd need to add a windows version but they also provide timezone information in `ftime` (called by `floattime()`).

Aside: localtime() didn't export after adding it to the export list in Libc.jl why might that be?

**Comment by omus** [comment]
I'm worried a

**Comment by omus** [comment]
I'm worried about this implementation as documentation for "gettimeofday" states that [using the timezone struct is deprecated](http://linux.die.net/man/2/gettimeofday)

**Comment by omus** [comment]
I posted my current solution as a PR. Not sure if it's the solution we should use but I just wanted to get it out in the open.

**Comment by JobJob** [comment]
Oh. 
How about if we call `tzset()` somewhere on julia startup. Then this works and is just as fast (~0.66 for the above `nowtest` on the same machine):

    double clock_local(void)
    {
    #if defined(_OS_WINDOWS_)
        return floattime();
    #else
        struct timeval now;
        gettimeofday(&now, NULL);
        // tzset();
        now.tv_sec -= timezone;
        return tv2float(&now);
    #endif
    }

btw on my system (OSX) seems like I don't need to call `tvset()`. 

Is this a portable solution (assuming we make a windows version)?

**Comment by omus** [comment]
@JobJob looks like on Windows [`_tzset()`](https://msdn.microsoft.com/en-us/library/90s5c885.aspx) may be the alternative function to use.

**Comment by JobJob** [comment]
Seems to me like unfortunately we can't rely on `tzset()` setting the `timezone` variable (or even that it will be set by some other mechanism) on all Unix-like environments. The [Linux tzset() docs](http://linux.die.net/man/3/tzset) only specify that `tzname` will be set and that we can only rely on `timezone` (offset in seconds) being set on System-V-like environments (see quote above).

So for a robust solution on Linux, I guess you'd have to do a lookup to get the timezone offset, as TimeZones.jl does.

It does seem likely that most Linuxes would implement a mechanism to get a timezone offset and that mechanism seems likely to be via `tzset()` and the `timezone` variable. It would be nice to have a fast, simple `now()` available - using unix2datetime(gettimeofday() + a tz offset) - and it's a shame that we'd have to degrade performance on linuxes that do provide it (which may well be the vast majority) to accommodate ones that don't.

On the bright side I guess we can make fast implementations for OSX and Windows, but someone more experienced than I with various flavours of Linux should weigh in about the likely compatibility of relying on `timezone`.

Also if the TimeZones.jl stuff related to reliably getting a tz offset was migrated into base then we could have a robust fast implementation of `now()` on all systems.

**Comment by JobJob** [comment]
Actually forget all that :) 
This latest pull request works fine and is fast and portable (just sets the tzoffset on load). 
Oh, one sec, needs a little fix.

**Comment by JobJob** [comment]
Ok it doesn't actually work, don't know how to set the _tzoffset such that it will actually stay set.

**Comment by JobJob** [comment]
Thanks @stevengj @omus !
