### ISSUE TITLE
support unicode whitespace in strip and split?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#14099]
Three of the functions in `util.jl` — `split`, `lstrip`,  and `rstrip` — use

``` jl
const _default_delims = [' ','\t','\n','\v','\f','\r']
```

as their list of "space" characters, which is obviously only the ASCII space characters.  As [discussed on the mailing list](https://groups.google.com/d/msg/julia-users/fFvfIj8WOsk/GnRru9F8CAAJ), this leads to unexpected behavior (contrary to the documentation) when splitting a string that uses other Unicode space characters.

Three options:
- Change the documentation of `split` and `strip` to say that they only handle ASCII spaces by default.
- Change `_default_delims` to `filter(isspace, Char(0):Char(0x10FFFF))` or similar.  Howeve, this will slow down these functions somewhat, because there are currently 23 Unicode space characters vs. only 6 ASCII space characters.  (We could also use a `Set`, but I don't think that is much faster for such a small list.)
- Define a special `immutable _Spaces; end` collection type, and `_default_delims = _Spaces()`, where `in(c::Char, ::_Spaces) = isspace(c)` and we make sure `isspace(c)` is carefully optimized.

I'm inclined to favor the third option at the moment.

**Comment by stevengj** [comment]
I just checked, and `isspace(c)` is already 72% faster than `c in _ascii_default_delims`, which is 70% faster than the `Set` version of `c in _unicode_default_delims` 140% faster than the `Array` version of `c in _ascii_default_delims`.

**Comment by nalimilan** [comment]
I was thinking along the same lines. I have also found two other possibilities:
- Use the regex `r"\s"`, which is very easy with the current code and should work fine. Likely not great for performance.
- Add `split(s, p)` taking a predicate, which would be exported for general use, and make `split(s) = split(s, isspace)`. It should be easy to refactor the existing code so that `split(s, c::Char)` would call `split(s, p)`.

I'd favour either your last solution, or my last solution (which are quite similar). Mine makes sense only if exporting `split(s, p)` would be useful.

**Comment by tkelman** [comment]
Wouldn't a predicate version make more sense with the predicate first? That would allow do notation.

**Comment by nalimilan** [comment]
@tkelman Yeah, probably.

**Comment by stevengj** [comment]
@nalimilan, I agree that we should have `split(predicate::Function, s::AbstractString)`.  However, we should also optimize the common case of splitting on a collection of characters, and especially on spaces, and since `Function` arguments aren't currently inlined etc. I think we should still implement specialized types for those cases.  Maybe specialized callable types, similar to how `reduce` is optimized for `+` etc.

**Comment by nalimilan** [comment]
Making `Spaces` callable and pass it to `split(p, s)` sounds like a good solution indeed.

**Comment by stevengj** [comment]
(The regex test is 50x slower than `isspace`.)

**Comment by i-apellaniz** [comment]
I found that 
```
julia> "\U2297" == "\otimes[TAB]"
true
```
while
```
julia> r"\U2297" == r"\otimes[TAB]"
false
```

Should I open a new issue? Feel free to do that for me if that's the case...

**Comment by stevengj** [comment]
@i-apellaniz, no, it's not a bug (you can't use `\U` escapes in a regex AFAIK) and please don't post questions on a completely unrelated issue.

**Comment by i-apellaniz** [comment]
Sorry, I'll open a new issue, since I think this must be further investigated. Sorry again.

**Comment by laborg** [comment]
This has been fixed in https://github.com/JuliaLang/julia/pull/27309
