### ISSUE TITLE
Access name of Julia executable

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14092]
I want to submit an independent job to the queue of an HPC system from within Julia. To make this work, I need to know the name of the Julia executable. The equivalent of `argv[0]` in C should suffice.

I don't think there is currently a way to do so; `Base.ARGS[1]` is definitely not it, and `ENV["_"]` also doesn't work. I'm currently using `joinpath(JULIA_HOME, "julia")`, but this will fail e.g. if `julia-debug` is used.

**Comment by yuyichao** [comment]
```jl
julia> Base.julia_cmd()
`/usr/bin/julia -Ccore-avx2 -J/usr/lib/julia/sys.so`

julia> Base.julia_exename()
"julia"
```
