### ISSUE TITLE
Race condition in threads initialization.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#14091]
When working on #14083, I'm getting a intermittent initialization SegFault during bootstrap. It seems to be caused by a race condition between setting up the thread states and using it.

The `jl_all_task_states[tid]` is set up inside each threads [here](https://github.com/JuliaLang/julia/blob/1b84ecb747e64b43d9d36578891823b04576b994/src/threading.c#L60). It is used in `init.c` at [here](https://github.com/JuliaLang/julia/blob/1b84ecb747e64b43d9d36578891823b04576b994/src/init.c#L572) and [here](https://github.com/JuliaLang/julia/blob/1b84ecb747e64b43d9d36578891823b04576b994/src/init.c#L615). (The first use in particular is very early and is really easy to trigger for me during compilation of `inference0.ji`)

`sleep`ing for 1 second in `init.c` before the use make the issue disappear and `sleep`ing for 2 second before the setup in addition to that make the issue happen 100% of the time so these appears to be not synchronized.

Report as an issue instead of a PR since I haven't figure out how do we do thread synchronization yet (especially at this early stage).

@vtjnash

**Comment by tkelman** [comment]
We're using libuv for our threads, right? Do we just need a `uv_barrier` http://docs.libuv.org/en/v1.x/threading.html#barriers before the first usage of any thread state to make sure they're ready?

**Comment by carnaval** [comment]
a fix is also in #12904 by the way but I don't know when this branch is intended to be merged
