### ISSUE TITLE
sending data by remotecall slow for composite types

### ISSUE THREAD

**Issue by abieler** [JuliaLang/julia#14106]
Passing an array of composite types to a worker with remotecall() seems slow.
Manual serialize and then sending arrays of floats speeds up things by roughly
two orders of magnitude for arrays with a few ten thousand elements.

Even with the custom serializer, sending the data through remotecall is only
a factor of 2 faster than writing the data to disk and then load it from disk
from the worker.

I posted this as a question in the julia-users group and was asked to open an issue.
https://groups.google.com/forum/#!topic/julia-users/1JAt6IKFJ7g

There is an example script at the end with timings.

Cheers
Andre

**Comment by JeffBezanson** [comment]
see also #7893

**Comment by JeffBezanson** [comment]
Interesting; using 100000 particles I get

```
julia> @time remotecall_fetch(2, get_data, particles);
	From worker 2:	(100000,)
  4.841910 seconds (6.70 M allocations: 475.558 MB, 1.23% gc time)

julia> b=IOBuffer();

julia> @time serialize(b, particles);
  0.487804 seconds (699.52 k allocations: 19.675 MB, 0.69% gc time)
```

So serializing to an IOBuffer is already 10x faster, which is very fishy. I'm sure it should be even faster still, but this part of the slowdown seems especially egregious.

**Comment by JeffBezanson** [comment]
Times on 0.4:

```
julia> @time remotecall_fetch(2, get_data, particles);
	From worker 2:	(100000,)
  1.233992 seconds (6.70 M allocations: 475.012 MB, 1.98% gc time)

julia> b = IOBuffer();

julia> @time serialize(b, particles);
  0.278163 seconds (699.50 k allocations: 18.674 MB, 0.51% gc time)
```

**Comment by JeffBezanson** [comment]
Time on 0.3:

```
julia> @time remotecall_fetch(2, get_data, particles);
	From worker 2:	(100000,)
elapsed time: 0.850154992 seconds (52021236 bytes allocated, 2.48% gc time)
```

However 0.4 is slightly faster for IOBuffer, which is nice.

**Comment by amitmurthy** [comment]
On current master (with https://github.com/JuliaLang/julia/pull/14667) :

`Particle` as an `immutable`
```

fetch_by_file

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
elapsed time: 0.060556448 seconds


custom_fetch

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
elapsed time: 0.025661032 seconds


get_data

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
  0.008269 seconds (139 allocations: 7.359 KB)
```

`Particle` as `type`:
```
fetch_by_file

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
elapsed time: 0.075956357 seconds


custom_fetch

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
elapsed time: 0.019882198 seconds


get_data

	From worker 2:	size(particles) = (300000,)
	From worker 2:	size(particles) = (300000,)
  1.930599 seconds (20.10 M allocations: 1.391 GB, 4.63% gc time)
```

**Comment by vtjnash** [comment]
What's to do here? Can we just encourage opening new issues for any problems observed?
