### ISSUE TITLE
Coveralls/Codecov  reports a line as not covered whilst a test for the line appears to exist.

### ISSUE THREAD

**Issue by zygmuntszpak** [JuliaLang/julia#14105]
I've been perusing the Coveralls/Codecov reports looking for opportunities to write some additional tests.
I was looking at the promote_rule in int.jl and noticed that some `promote_rules` were apparently missing tests. 

See for example:
`promote_rule(::Type{Int64}, ::Type{Int8} ) = Int64`

 [which can found in this file](https://codecov.io/github/JuliaLang/julia/base/int.jl?ref=e6cd2bc8c6ab2444d7750cf42d43b4c45e8f3545)

Apparently, this line is not covered by any test as indicated by the red highlight.

However, the test file for `int.jl`

[which can be found here](https://github.com/JuliaLang/julia/blob/master/test/int.jl)

contains the following tests:

``` jl
UItypes = (UInt8, UInt16, UInt32, UInt64, UInt128)
SItypes = (Int8, Int16, Int32, Int64, Int128)


for T in UItypes, S in UItypes
    @test promote(S(3), T(3)) === (sizeof(T) < sizeof(S) ? (S(3), S(3)) : (T(3), T(3)))
end


for T in SItypes, S in SItypes
    @test promote(S(3), T(3)) === (sizeof(T) < sizeof(S) ? (S(3), S(3)) : (T(3), T(3)))
end


for T in SItypes, S in UItypes
    R = sizeof(S) < sizeof(Int) ? Int : S
    @test promote(R(3), T(3)) === (sizeof(R) < sizeof(T) ? (T(3), T(3)) : (R(3), R(3)))
end
```

Looking deeper at one of these tests using the following code:

``` jl
for  T in SItypes, S in SItypes
    print(eltype(S(3)) )
    print(", ")
    print(eltype(T(3)) )
    print(" -> ")
    print(eltype(promote(S(3), T(3))))
    print(" | ")
    print(@which promote(S(3), T(3)))
    println(" ")
end
```

which yields:

> Int8, Int8 -> Int8 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int16, Int8 -> Int16 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int32, Int8 -> Int32 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> **Int64, Int8 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132** 
> Int128, Int8 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int8, Int16 -> Int16 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int16, Int16 -> Int16 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int32, Int16 -> Int32 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int64, Int16 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int128, Int16 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int8, Int32 -> Int32 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int16, Int32 -> Int32 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int32, Int32 -> Int32 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int64, Int32 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int128, Int32 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int8, Int64 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int16, Int64 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int32, Int64 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int64, Int64 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int128, Int64 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int8, Int128 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int16, Int128 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int32, Int128 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int64, Int128 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132 
> Int128, Int128 -> Int128 | promote{T,S}(x::T, y::S) at promotion.jl:132

it would appear that the bold fourth line above:

> **Int64, Int8 -> Int64 | promote{T,S}(x::T, y::S) at promotion.jl:132** 

is indeed testing:
 `promote_rule(::Type{Int64}, ::Type{Int8} ) = Int64`

contrary to what the Coveralls/Codecov is reporting. I'm not sure how 
to reconcile these results, and would appreciate any insight.

**Comment by KristofferC** [comment]
cc @kshyatt because she has worked a lot with the coverage stuff and might have seen something similar.

**Comment by kshyatt** [comment]
I have been seeing something similar, for instance:

![screen shot 2015-11-24 at 3 54 48 pm](https://cloud.githubusercontent.com/assets/828643/11384343/bee8cc12-92c3-11e5-937e-e0eba395efa2.png)

And I really don't have any insight into what's going on. I suspect it may be a Julia parser issue, rather than anything wrong with `Coverage.jl` or `CoverageBase.jl`. @vtjnash, do you have any ideas?

**Comment by KristofferC** [comment]
There have been many changes to the line info stuff. Please reopen / comment if this is still a problem.

**Comment by NHDaly** [comment]
Just noting that I still see this issue with `promote_rule` methods not counting towards our test coverage in the FixedPointDecimals package:
https://coveralls.io/builds/30177355/source?filename=src%2FFixedPointDecimals.jl#L330

Despite those lines definitely being covered (removing them causes the tests to fail with the expected `promotion of types Int64 and FixedDecimal{Int64,2} failed to change any arguments`).

Perhaps there is something wrong with the `.cov` accounting?

**Comment by vtjnash** [comment]
It's possible that problem may be caused by the inadvisable use of `@pure` on the subsequent functions in that file.

**Comment by NHDaly** [comment]
Very true. I've been meaning to clean that up as well. I have it open in a branch somewhere but never got around to it...
