### ISSUE TITLE
Hitting some memory limit well below physical limit?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#14112]
I'm not sure whether this is a Julia thing or an OS thing, but here's what happened.

I'm on a machine with 512 GB of RAM (yes, GB) and `Version 0.4.2-pre+15 (2015-11-20 12:12 UTC)`:

```
julia> using LightGraphs

julia> @time g = Graph(1_000_000_000, 10_000_000_000)
increase REGION_COUNT or allocate less memory

signal (6): Aborted
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
malloc_page at /g/g17/seth/dev/julia/julia/src/gc.c:701
add_page at /g/g17/seth/dev/julia/julia/src/gc.c:1031
__pool_alloc at /g/g17/seth/dev/julia/julia/src/gc.c:1073
array_resize_buffer at /g/g17/seth/dev/julia/julia/src/array.c:594
push! at ./array.jl:434
unsafe_add_edge! at /g/g17/seth/.julia/v0.4/LightGraphs/src/graph.jl:80
add_edge! at /g/g17/seth/.julia/v0.4/LightGraphs/src/core.jl:108
Aborted (core dumped)

```
At last check the memory allocation for the process was approaching 100 GB.

Any ideas? I don't know what `REGION_COUNT` is. Looks like it's defined here: https://github.com/JuliaLang/julia/blob/master/src/gc.c#L745-L747

**Comment by yuyichao** [comment]
Are you trying to allocate many small objects?

**Comment by sbromberger** [comment]
Yes - each edge has 128 bits in an immutable Edge type, plus there's at least 64 additional bits pushed as an Int to one of many vectors.

**Comment by sbromberger** [comment]
...is there a workaround / solution to this?

**Comment by dpsanders** [comment]
@sbromberger You seem to be trying to create a graph with 10 billion (10^10) edges. If each edge has 192 bits = 24 bytes associated, this will be 240 GB. Since `Set` is implemented using `Dict`, which puts its keys and values into arrays with a size larger than the number of elements, it's perhaps not surprising if you are reaching or exceeding 500 GB?

**Comment by jiahao** [comment]
A simple extrapolation from these measurements:

```jl
julia> for n=4:7
           @time Graph(10^n, 10^(n+1))
       end
  0.083844 seconds (95.54 k allocations: 17.228 MB)
  1.696394 seconds (956.47 k allocations: 181.149 MB, 9.88% gc time)
 24.864401 seconds (9.56 M allocations: 1.661 GB, 9.84% gc time)
329.030462 seconds (95.63 M allocations: 19.822 GB, 15.24% gc time)
```

would estimate that you would need 1.979TiB of memory to generate the object you want. Not only does that easily exceeds the amount of physical memory of 512 GB, but quite likely to exceed the amount of virtual memory on the system.

Julia can't really help you here. All you can do is use a larger system, or redesign `Graph`'s storage requirements.

**Comment by yuyichao** [comment]
Apart from what jiahao said (a breif look at the constructor suggests that the total allocation should be a fairly accurate estimation of the total memory needed since their doesn't seem to be a lot of temporaries that need heap allocate), you are indeed hitting a slightly different limit. You can try https://github.com/JuliaLang/julia/pull/13993 to see if you are hitting the limit because the temporaries you create triggers a GC bug, or you can just increase `REGION_COUNT` and compile julia again to avoid hitting **this** limit. It still won't help you if you are approaching the physical memory limit though.

**Comment by sbromberger** [comment]
Thanks. We are eliminating the edge sets precisely to reduce memory consumption. However - I do not believe the allocated memory S reported by @time is very accurate. I say this because I typically get ~500 GB allocations on betweenness centrality on large graphs on a machine that has 16GB of RAM and there's only ~3 GB swapped. 

I never understood the allocations figure. It appears to calculate all memory allocated regardless of whether it's transient or not.

**Comment by jiahao** [comment]
> I do not believe the allocated memory S reported by `@time` is very accurate.

The allocated memory reported is the total amount of memory touched. In this special case of a constructor that does not generate garbage in extra temporaries, the total amount of memory touched is the total amount of memory allocated. You can verify this for yourself by running `julia --track-allocation`.

**Comment by StefanKarpinski** [comment]
Please remember to quote macros since otherwise the user `time` gets pinged.

**Comment by yuyichao** [comment]
He has probably be ping'd too many times in our comment and commit messages and don't worry about it anymore. =)

**Comment by sbromberger** [comment]
Sorry. I don't understand then how we are figuring >1 TiB of memory required for 10 billion edges at 24 bytes per edge if the total allocation displayed by `@time` (sorry, Stefan) is intended to represent the total amount of memory required for the structure. We should be around 240 GiB plus some overhead for other structures. 

I'm missing something important and probably basic here and appreciate all the feedback.

**Comment by dpsanders** [comment]
Since I don't have a machine with that much memory, let's try an experiment:
``` 
julia> @time s = Set(1:10^7)
  1.352507 seconds (17 allocations: 144.001 MB, 8.34% gc time)
Set([8744729,9796248,8845373,8478450,3115409,323003,8200920,9731340,1369683,3928234  …  4743687,4107359,1457757,1841805,7119840,6364170,1912351,7602621,7778416,8253756])

julia> length(s.dict.keys)
16777216
```
If you look at the internal implementation of `Dict`, it stores the keys in an array, and this array is a power of two, so actually this many edges are allocated, for a total of

```
julia> 16777216 * 24
402653184
```
Still not at your limit, but much closer.

Can you report `sizeof(s.dict.keys)` for different numbers of edges?

**Comment by sbromberger** [comment]
Will do in the next hour or two. Thank you.

**Comment by jiahao** [comment]
The main culprit is the `Vector{Vector{Int}}` structure you have for `badjlist` and `fadjlist`. You're generating `2*nv` `Vector{Int}`s, and each `Vector` is allocated with extra memory padding to facilitate growth by appending. (`sizeof(g.fadjlist[1])` only reports the amount of memory reserved that is actually used, so you'd have to dig into the C API to see the actual amount of memory allocated.)

So in the original example you also have 2 billion arrays' worth of extra memory padding to deal with.

**Comment by sbromberger** [comment]
Graphs only have one `Vector{Vector{Int}}`, though, so it's `nv Vector{Int}s`. `Base.summarysize()` for a variety of `n`-node, 0-edge graphs is as follows:

n=1000: 8368
10_000: 80368
100_000: 800368
1_000_000: 8000368
10_000_000: 80000368

so it stands to reason that the minimum allocation without any edges for 1 billion nodes is
8_000_000_368, or 8 GB. Add 24 bytes per edge and you're still below 500GB.

In any case, given overallocation, here's what I'm seeing for summarysize for a graph with 1m nodes, and a variety of (random) edges:

100_000: 14_056_544 (edges contribute 6_056_176, or ~61 bytes per edge)
1_000_000: 59_651_680 (edges contribute 51_651_312 or ~52 bytes per edge)
10_000_000: 453_212_768 (edges contribute 445_212_400 or ~45 bytes per edge)
100_000_000: 6_171_402_848 (edges contribute 6_163_402_480 or ~62 bytes per edge) - note: most of this is in the edge set (4_563_402_816), not in the fadjlist (1_608_000_000).

so it's more than 2x the raw memory required, and closer in some cases to 3x with up to 2/3 taken by the edge set. This means that 10 billion edges at 62 bytes per edge would allocate ~620 GB of memory, which exceeds our spec.

We're gonna get rid of the edge sets soon once we can figure out how to make performant iterators (help gratefully accepted, btw - see https://github.com/JuliaGraphs/LightGraphs.jl/pull/237 for the current status). This should reduce the amount of memory by a good amount.

**Comment by jiahao** [comment]
`Base.summarysize` does _not_ report the amount of overallocation for padding `Vector`s. 

> Graphs only have one Vector{Vector{Int}}, though, so it's nv Vector{Int}s

Well they have two in 0.4.0, which is the version I'm on. I see that that has changed on master. My point still stands that you should not be using this data structure.

**Comment by sbromberger** [comment]
@jiahao - understood - sorry for not making clear I'm working on master. What data structure would you suggest as an alternative?

**Comment by sbromberger** [comment]
Also, is there merit in suggesting some function (like a reverse "sizehint!") that will deallocate memory when the user is satisfied that the structure won't grow significantly (and when s/he is prepared to deal with an inefficiency if it does need to grow)?

**Comment by jiahao** [comment]
Your edge list is really a representation of a sparse adjacency matrix, so maybe you can try using a `SparseMatrixCSC{Void,Int}`. But any further discussion along this line doesn't belong here.

**Comment by sbromberger** [comment]
Yup, got it. I actually tried a SparseMatrixCSC backend but it had other negative performance issues so I abandoned it. MatrixNetworks.jl is working on something similar (though they're translating into a CSR representation, it looks like). In any case, you're right about this veering off topic. I'd love to continue the discussion over in LightGraphs if you're willing.
