### ISSUE TITLE
Minor error in Arm build instructions

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/julia#14116]
The instructions for building on Arm: https://github.com/JuliaLang/julia/blob/master/README.arm.md for Raspberry pi suggest setting `JULIA_CPU_ARCH=arm1176jzf-s`, but I believe it should instead be `JULIA_CPU_TARGET=arm1176jzf-s` since `JULIA_CPU_ARCH` does not appear anywhere else in the codebase.

**Comment by yuyichao** [comment]
Thanks for finding this. Mind [fix it and submit a PR](https://github.com/JuliaLang/julia/edit/master/README.arm.md) ?

**Comment by rdeits** [comment]
done!
