### ISSUE TITLE
`gc` sometimes needs to be called twice

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#14127]
As reported here: https://groups.google.com/d/msg/julia-users/F49gvZUWhX8/M0xKKH5kCQAJ

```jl
julia> function foo()
           A = rand(3,5)
           B = sub(A, 1:2, 3:4)
           finalizer(A, A->@schedule(println("GCed A")))
           B
       end
foo (generic function with 1 method)

julia> B = foo()
2x2 SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}:
 0.583567  0.719624
 0.60663   0.739911

julia> B = 0
0

julia> gc()

julia> gc()
GCed A
```
CC @carnaval.

**Comment by yuyichao** [comment]
Have you tried https://github.com/JuliaLang/julia/pull/13995 ? The PR is currently broken but should build fine in default configuration.

**Comment by timholy** [comment]
Ah, I should say that here I'm using the finalizer just to report the fact that `A` is being garbage-collected.

But I'll comment over there.
