### ISSUE TITLE
Invalid second UTF8String indices don't cause errors

### ISSUE THREAD

**Issue by JobJob** [JuliaLang/julia#14158]
```
s = "🛀🛀" #a bath codepoint is 4 bytes long
s12 = s[1:2] # "🛀"
s56 = s[5:6] # "?" #the expected behaviour is this should be the same as s12?
sizeof(s12)  # 4
sizeof(s56)  # 2
```

The issue seems to be that:

```
nextind(s, 2) # 5
nextind(s, 6) # 7 (prob should be 9)
```

I tried changing https://github.com/JuliaLang/julia/blob/master/base/strings/basic.jl#L141 to 

```
return sizeof(s)+1
```

and it seems to fix the problem. Additionally `julia5 runtests.jl unicode string strings/basic strings/io strings/search strings/types strings/util` succeeds after making this change and recompiling.

Should I add some tests and submit a PR?

**Comment by nalimilan** [comment]
Also, the docs for `nextind` say "Returns a value greater than endof(str) at or after the end of the string." So they should be adapted to mention `sizeof(str)`.

**Comment by JobJob** [comment]
Done, including doc changes and tests. Cheers.

**Comment by stevengj** [comment]
You really shouldn't be relying on string ranges to work when you supply invalid indices.  (This may not even be possible in the future; #9297.)  See also the discussion in #5446.

**Comment by JobJob** [comment]
Cool. Cheers. Closing.

**Comment by nalimilan** [comment]
Rather than closing, if you want to make a PR to raise an error, it would be great.

**Comment by JobJob** [comment]
So both `s[1:2]` and `s[5:6]` would throw a UnicodeError? I'd need to rename the issue to something like "Invalid string index don't cause errors"?

Plus it would be breaking for people who were doing the wrong thing previously (not right at the end of the string). Is everyone cool with that? Seems like might be better for someone (hint hint) to actually address #9297? 

Happy to do it of course, just want to get the green light first.

**Comment by stevengj** [comment]
I think that throwing an error on an invalid range would be a good warmup for #9297.  If this throws lots of errors, it's an indication that #9297 will be traumatic.

**Comment by JobJob** [comment]
Ha ok, well I'm going to point the finger at you guys when the hordes come baying for blood :)

**Comment by nalimilan** [comment]
Of course, that wouldn't be backported to 0.4, to leave some time for people to adapt. We could also simply print a deprecation warning (see `depwarn`) to ease the transition.

**Comment by JobJob** [comment]
Say a UTF8String `s` is 3 bytes long,  e.g. [this test](https://github.com/JuliaLang/julia/blob/master/test/strings/basic.jl#L112-L115):

    # make sure substrings handle last code unit even if not start of code point
    let s = "x\u0302" 
        #s is "x̂", sizeof(s) == 3, "\u0302" is the (circumflex) diacritic (2 bytes)
        @test s[1:3] == s
    end

Do we want this to throw "UnicodeError: invalid char index" because `isvalid(s,3)` is `false` (as was briefly suggested here: https://github.com/JuliaLang/julia/pull/14160#issuecomment-159995642)? My inclination is no. If the start of the range is at the first byte of a code point and the end of the range is at the last byte of a code point, I think it should be regarded as valid.

However, it does mean that `s[1:3]` is the same as `s[1:2]`, which to me is a little inconsistent, though it is consistent with `s[2]` returning `Char(s[2:3])` (the circumflex in this example).

What are your thoughts? See the WIP which implements this: 

Btw, when you do `julia runtests.jl` the tests in `test/strings/*.jl` and `test/unicode/*.jl` don't seem to be run, is that intentional?

**Comment by tkelman** [comment]
those tests should be getting included by a main strings and/or unicode test

**Comment by JobJob** [comment]
ahh indeed they are

**Comment by JobJob** [comment]
Re `j` being allowed to be the end of a character, it seems weird that since:
a) say `s="🐨🐨"` `s[1:4]` covers all the bytes of the first koala. Shouldn't that be ok? It's not like they have a partially formed code point.
b) `s[i:j]` basically is a shorthand for `s.data[i:j]` at present (with some bounds checks and checking for not fully formed characters), that `s[1:sizeof(s)]` would throw a unicode error and not be equivalent to s seems weird.

Anyway I think these things will hopefully resolved by a more comprehensive changes proposed in #9297   so not 100% sure if it's worth kicking the can down the road with this?

**Comment by stevengj** [comment]
Moving forward, I think the consensus has been that anything you put inside the brackets in `s[...]` should be valid indices.  The indices are not bytes.

You especially shouldn't be using `sizeof(s)` to compute indices, that is just asking for trouble, especially if your code accepts any `AbstractString`.  (Think of what this does for a UTF-32 string.)

**Comment by JobJob** [comment]
But e.g. `s="🐨🐨"` `s[5:5]` is not a byte index? It's definitely not a code point or grapheme index. Currently it's just a little inconsistent IMO, that's why it needs a thorough overhaul. Are you happy with the PR in it's current state (pending the fixes you recommend) as a minor (if fairly inconsequential) fix for this particular case?

**Comment by stevengj** [comment]
String indices are best thought of as an opaque type that happens to be represented by integers.  Technically, it is a *code-unit index*, where a code-unit is 1 byte for UTF-8 but 2-bytes for UTF-16 and 4 bytes for UTF-32.   In the future, the string index type may be even further abstracted.

For example `utf16("🐨🐨")[3:3]`, the `3` is not a byte index, because the code units are 16-bit words.

**Comment by stevengj** [comment]
(Valid indices are always the indices of code units that *begin* a code point.)

**Comment by JobJob** [comment]
ok but say `s[5:5]`for the example above returns code units 5 to 8

**Comment by stevengj** [comment]
@JobJob, yes, because the code-unit index refers to the whole codepoint that follows.  e.g. `s[5]` returns a codepoint, not a code unit.

**Comment by stevengj** [comment]
As explained in the manual, *Conceptually, a string is a partial function from indices to characters — for some index values, no character value is returned, and instead an exception is thrown. This allows for efficient indexing into strings by the byte index of an encoded representation rather than by a character index, which cannot be implemented both efficiently and simply for variable-width encodings of Unicode strings.*

**Comment by JobJob** [comment]
Yeah I read that, it still makes more sense to me that if the indices are indexing code units then if you want code units 1 to 8 you should use `s[1:8]` not `s[1:5]`

**Comment by stevengj** [comment]
No, because `8` is not a valid string index.  You are only allowed to index the code unit that begins a codepoint.   Again, the fact that the indices are actually offsets of code units is an implementation detail that the user is not intended to muck around with.   The string is a *partial* function from integers to codepoints.

**Comment by stevengj** [comment]
As a practical matter, any code that passes an invalid index is likely to be doing so because of a bug, e.g. it is using `sizeof` to compute indices, or is adding/subtracting `1` rather than calling `nextind`/`prevind`.  It is better to throw an exception to catch the bug rather than to try to guess the user's true intention.

**Comment by JobJob** [comment]
Looking into what breaks with `s[1:8]` and `s[1:4]` being invalid (this wasn't the behaviour previously).

**Comment by JobJob** [comment]
btw @nalimilan seemed to be implying with this comment https://github.com/JuliaLang/julia/pull/14160#issuecomment-159992883 that an index at the end of the character might be ok to him (though it's not completely unambiguous what he meant by middle - I assumed not at the start or end).
 
This code breaks: https://github.com/JuliaLang/julia/blob/master/base/strings/util.jl#L48-L59

**Comment by JobJob** [comment]
Oh actually the `chomp!` doesn't break, only the `chomp` for say `s="foø\n"`

**Comment by nalimilan** [comment]
By "middle" I meant "anything not the first byte of a code point". I fully agree with @stevengj here: better be strict, as anyway people should never get indices starting elsewhere except when doing buggy computations.

Why would `chomp` break? It indexes directly `s.data`, so the checks do not apply there.

**Comment by JobJob** [comment]
because https://github.com/JuliaLang/julia/blob/master/base/strings/util.jl#L50 it returns `s[end-1]` which is `s[4]` and invalid. Is this the right change there?

    chomp{T<:ByteString}(s::T) =
           (endof(s) < 1 || s.data[end]   != 0x0a) ? s :
           (endof(s) < 2 || s.data[end-1] != 0x0d) ? T(s.data[1:end-1]) : T(s.data[1:end-2])

**Comment by nalimilan** [comment]
Oh, right, that's trickier than it sounds. Your solution sounds OK to me.

**Comment by stevengj** [comment]
Hmm, this example makes me want to change my mind here; without accessing the internal `s.data`, the "correct" thing here would be `s[1:prevind(s,endof(s))]`, which is awfully awkward.   Maybe we should allow the end of a range to be the last codeunit in a codepoint after all.

**Comment by JobJob** [comment]
Honestly, it's funny you say that because the same thing happened to me :)

I actually started implementing it originally as per your current plan, and wrote the tests in the PR (that chop and chomp fail on) after seeing these potential bugs (if end indices have to pass `isvalid`), and then I saw that it was sort of assumed in a few places that `s[i:j]` is ok if `j` is the last byte of a code point (was focussed on utf8), and I thought you know what, changing this is probably quite a big change, and thus came to the view expressed above :)

**Comment by JobJob** [comment]
Having said that this is all String utility code that should know what it's doing, so there's an argument that these are implementation aware optimisations.

**Comment by JobJob** [comment]
Anyway, if we are continuing down this path, `chop("foø")` fails with the current [`chop(s::AbstractString) = s[1:end-1]`](https://github.com/JuliaLang/julia/blob/master/base/strings/util.jl#L39)

This could change to:

    chop(s::Union{ASCIIString, UTF32String}) = s[1:end-1]
    chop(s::AbstractString) = s[1:prevind(s,endof(s))]

I'm certain there's a faster implementation for UTF16, UTF8.

I'm off to bed now, I've pushed my changes to that same branch in the PR with `!isvalid(j)` throwing, here are the other places I've seen failures:

this test fails: https://github.com/JuliaLang/julia/blob/master/test/dates/io.jl#L192

And I get an issue with the REPL crashing, by doing the following:

    julia> s = "🐨🐨"
    "🐨🐨"
    julia>
press up (to get the previous line), then backspace to delete the end double quote

    julia> s = "🐨🐨"
    "🐨🐨"
    julia> s = "🐨🐨
    
press down, then up and the repl crashes:

    julia> s = "🐨🐨"
    "🐨🐨"
    julia> s = "🐨🐨  WARNING: Caught an exception in the keymap:
    ERROR: UnicodeError: invalid character index
    ERROR: type PrefixSearchState has no field p
     in run_interface at ./LineEdit.jl:1610
     in run_frontend at ./REPL.jl:864
     in run_repl at ./REPL.jl:167
     in _start at ./client.jl:419

Cheers.

**Comment by nalimilan** [comment]
The trouble is that if we allow/encourage `s[1:idx-1]`, people will (quite logically) believe that `s[1:idx+1]` is fine too. All of this calls for the dedicated string index type. In the meantime, we could continue allowing to index the last byte of the code point, but I don't see it as a terrible issue: people need to use `nextind()` anyway.

**Comment by JobJob** [comment]
Ok, as stated earlier, I agree that a string index type is needed to actually fix these problems, and the PR I proposed is just a minor fix for the inconsistency in the OP. Shall I revert the PR back to its original state with second indices at the end of code points allowed (and incorporating the other code improvements made by @stevengj)?

Btw in the discussion above I wasn't familiar with the general usage of `sizeof` and had thought it was only defined for these string types, and since I had only really looked at UTF8 and ASCII implementations up to that point, was mistakenly assuming `sizeof` was effectively equivalent to `lastidx` (i.e. that they were the index of the last code unit in `s.data`). My point was that it seemed strange to me that  `s[1:lastidx(s)]` was not equivalent to `s`.

**Comment by ScottPJones** [comment]
Very good to see somebody else taking an interest in fixing some of the string issues!
If possible, it would be good if for non-`DirectIndexString` types, that only the 1st and last code-units are allowed (and only for the end point), but not any middle code-units, if any (not an issue for `UTF16String`, since will only have 1 or 2 code-units per character).

**Comment by JobJob** [comment]
So essentially only for UTF8? That was the original intent of the PR: https://github.com/JuliaLang/julia/pull/14217 the "original state" I mentioned reverting back to just above was the first commit of that PR, I then added the second commit to give people a look at what happens if you don't allow the second index to be at the end of a code point.

**Comment by ScottPJones** [comment]
At least among the current string types supported in Julia, yes, only `UTF8String` is a problem.

**Comment by stevengj** [comment]
@JobJob, after having slept on this I think we should go forward with disallowing ranges with invalid endpoints.   The `s[end-1]` case is rare enough that I don't think it makes sense for us to contort the semantics to handle this.

**Comment by stevengj** [comment]
(Similarly for `UTF16String`: `utf16("🐨x")[1:end-1]` should be an error.)

**Comment by JobJob** [comment]
Agree that it's more semantically consistent this way, given the way e.g. s[1] works, but not sure if it's more intuitive or user friendly, still thinking about it. In any case it doesn't matter because it's all going to change hopefully for much the better. 

Pushed an initial attempt at `getindex` UTF16. Will only have time to look at this more again perhaps later tomorrow.

**Comment by JobJob** [comment]
PR updated, I'm fine with your decision. I think it's agreed all round that something like a string index type is needed to properly resolve these issues.

Regarding the REPL issue, I wasn't able to resolve it quickly, I note a very similar error was happening before this change, using the steps above but just hitting backspace after the final step in the reproduction above. The main difference is that those steps cause the REPL to crash completely with these changes.

**Comment by JobJob** [comment]
This works consistently now. In the OP's example: `s[1:2] == s[5:6] == "🛀"` and it doesn't error. Closing.
