### ISSUE TITLE
Compilation failure on RPi2

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14152]
`master` currently fails to compile on a Raspberry Pi 2 due to the inline assembly from 5e57bc3 (cc @yuyichao):

```
$ make VERBOSE=1
make[1]: Entering directory '/home/tim/julia/deps'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/tim/julia/deps'
make[1]: Entering directory '/home/tim/julia/src'
 gcc  -ftls-model=global-dynamic -DSYSTEM_LLVM -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -fsigned-char -Wold-style-definition -Wstrict-prototypes -Wc++-compat -O3 -ggdb3 -falign-functions -D_GNU_SOURCE -I. -I/home/tim/julia/src -I/home/tim/julia/src/flisp -I/home/tim/julia/src/support -I/home/tim/julia/usr/include -I/home/tim/julia/usr/include -DLIBRARY_EXPORTS -I/home/tim/julia/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common -Wpointer-arith -Wundef -I/opt/llvm-3.6/include "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.so\"" -DNDEBUG -c /home/tim/julia/src/threadgroup.c -o threadgroup.o
{standard input}: Assembler messages:
{standard input}:689: Error: selected processor does not support ARM mode `dmb'
{standard input}:739: Error: selected processor does not support ARM mode `wfe'
{standard input}:817: Error: selected processor does not support ARM mode `dmb'
{standard input}:924: Error: selected processor does not support ARM mode `wfe'
{standard input}:1062: Error: selected processor does not support ARM mode `wfe'
Makefile:94: recipe for target 'threadgroup.o' failed
```

These modes are only supported on armv7+, which the Raspberry Pi 2 is, but apparently needs a `-march` option Adding `-march=armv7-a` or `-march=native` (through `MARCH` in `Make.user`).

The Pi is running Debian Jessie, using gcc 4.9.2. On another armv7 system, running Linaro Ubuntu 14.04 shipping gcc 4.8, this flag is not required (ie. without any `march` compilation succeeds). So this seems to be somewhat gcc dependent.

**Comment by nalimilan** [comment]
Thanks for the report. Maybe simply add the instruction about `-march=armv7-a` to README.arm? Would you make a PR for that?

**Comment by maleadt** [comment]
Will do. As a result I need to define `JULIA_CPU_TARGET` to `cortex-a7` in order to get rid of the `'armv7-a' is not a recognized processor for this target (ignoring processor)` warnings. Previously, not defining `JULIA_CPU_TARGET` yielded `WARNING: unable to determine host cpu name` (again, only on the RPi2, the other armv7 board works without issue or warnings)...

**Comment by yuyichao** [comment]
I guess we can just replace restrict these to `__ARM_ARCH >= 7`.
