### ISSUE TITLE
Reuse of CHOLMOD.Factor

### ISSUE THREAD

**Issue by PieterjanRobbe** [JuliaLang/julia#14155]
Following [this](https://groups.google.com/forum/#!topic/julia-users/fdFqAffyxIY) issue about the reuse of CHOLMOD.Factor:
```julia
julia> F = cholfact(speye(5))
```
returns a `Base.SparseMatrix.CHOLMOD.Factor{Float64}`, as stated in the [documentation](http://web.mit.edu/julia_v0.3.11/.julia-483dbf5279.amd64_ubuntu1404/share/julia/doc/_build/html/stdlib/linalg.html?#Base.cholfact). However, to reuse the symbolic factorisation in `cholfact!()`, `F` must be a `Cholmodfactor`, so the following terminates with an error:
```julia
julia> cholfact!(F,speye(5))
ERROR: MethodError: `cholfact!` has no method matching cholfact!(::Base.LinAlg.Cholesky{Float64,Array{Float64,2}}, ::SparseMatrixCSC{Float64,Int64})
```
 For reference, I am running
```julia
julia> versioninfo()
```
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)

**Comment by andreasnoack** [comment]
The documentation needs some updates and we should export `update!` which is the new generic function for updating existing factorizations. You can already now do
```jl
julia> SparseMatrix.CHOLMOD.update!(F,speye(5))
Base.SparseMatrix.CHOLMOD.Factor{Float64}
type:          LLt
method: simplicial
maxnnz:          5
nnz:             5
```

**Comment by PieterjanRobbe** [comment]
The following also terminates with an error:

```julia
@parallel for i = 1:10; SparseMatrix.CHOLMOD.update!(F,speye(5)); end
```

gives

```julia
ERROR: cannot serialize a pointer
```

Any ideas?

**Comment by andreasnoack** [comment]
Yes, you cannot move a sparse factorization to another process. This is similar to #14134 and https://github.com/JuliaLang/julia/pull/14149 will give a better error message here.

**Comment by PieterjanRobbe** [comment]
So is there a workaround for this? Could you, for example, define a sparse factorisation at each process and then update that particular factorisation in the parallel for loop?

**Comment by PieterjanRobbe** [comment]
Ok there is a workaround: assume I define a function `par_col_fact` that takes a CHOLMOD.Factor and sparse matrix as input
```julia
function par_chol_fact{T<:Real,S<:Int}(F::Base.SparseMatrix.CHOLMOD.Factor{T},A::Base.SparseMatrixCSC{T,S})
    SparseMatrix.CHOLMOD.update!(F,rand(1,1).*A)
    return "check!"
end
```
then the following code seems to work:

```julia
@everywhere include("par_chol_fact.jl")

@everywhere B = sprand(1000,1000,0.7)
@everywhere A = B*B'
Any[eval(parse(@sprintf("@everywhere F%i = @spawnat %i cholfact(A)",i,i))) for i in eachindex(workers())]

@parallel (+) for i=1:100
  str = par_chol_fact(eval(parse(@sprintf("fetch(F%i)",myid()))),A)
  fetch(str) == "check!" ? 1 : 0
end
```

**Comment by andreasnoack** [comment]
I'm not sure how the real usecase behind your example is supposed to work, but would some like
```jl
julia> @everywhere begin                              
       A = sprandn(1000,1000,0.7)                     
       B = A'A                                        
       F = cholfact(B)                                
       SparseMatrix.CHOLMOD.update!(F, speye(1000))   
       end                                            
```
? Generally, it's not a good idea to use `eval`.

#14149 has been merged and gives informative error messages, so I'll close this.

**Comment by PieterjanRobbe** [comment]
Unfortunately, I can't use @everywhere, since the calculation of B, in this case, depends on some large amount of fixed data, that needs to be available on each processor. SharedArray is also not an option, since it only supports bitstypes. I'd like to use the @parallel for construct, so that the data only needs to be in the global scope.

**Comment by StefanKarpinski** [comment]
Please quote macro names – the GitHub users named "everywhere" and "parallel" are unlikely to be interested in this conversation.
