### ISSUE TITLE
Warning when importing Dates

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#14159]
This is my first time trying to deal with dates in Julia so please forgive my ignorance. Per the 0.4 release documentation,

> You could call `using Dates` to bring all exported functions into `Main` to be used without the `Dates.` prefix.

However, in doing that, I get a warning:

    julia> using Dates
    WARNING: requiring "Dates" in module "Main" did not define a corresponding module.

Is this expected behavior? If so, I would argue that it's a little off-putting for users to get a warning for something explicitly mentioned in the documentation. :stuck_out_tongue_closed_eyes: 

Note that I'm currently using the v0.4.0 release, if that makes a difference.

**Comment by ararslan** [comment]
In case it matters, I just upgraded to the v0.4.1 release and I get the same warning.

**Comment by KristofferC** [comment]
Should it be Base.Dates?

**Comment by ararslan** [comment]
@KristofferC: I was actually wondering that a few minutes ago--it appears to do the trick! Though `using Dates` does work as intended aside from the warning, perhaps the documentation should recommend `using Base.Dates` instead, as it also works but produces no warnings.
