### ISSUE TITLE
".-" is not a unary operator

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14161]
I notice that `.-` is not a unary operator:

```
julia> .-[1]
ERROR: syntax: ".-" is not a unary operator
```

For consistency, I'd expect `.+` and `.-` to be available as unary operators as well.

**Comment by stevengj** [comment]
It's hard to imagine a circumstance in which `.-x != -x`, so on that grounds I'm inclined not to add the former synonym.

**Comment by eschnett** [comment]
It's the same case as as for `x - y` and `x .- y`. If there's an element-wise subtraction operator, I expect an element-wise negation operator as well.

**Comment by stevengj** [comment]
@eschnett, that's not true.  `x - y` is not defined if `x` and `y` do not have the same shape, where `x .- y` is defined.  As a binary operator, therefore, `.-` is a strict generalization.

**Comment by oxinabox** [comment]
Are there any element wise unary operators?
I can't recall if there is an element-wise "not" operator

**Comment by KristofferC** [comment]
Nothing really actionable here.

**Comment by stevengj** [comment]
Now that dot operators are fusing, we should probably reconsider this.  e.g. imagine you want to `log.(.-a)` rather than `log.(-a)`, in order to avoid the temporary array for `a::Array`.

**Comment by yuyichao** [comment]
I think we might still want to parse unary `.-` as broadcast.
