### ISSUE TITLE
svd fails on windows for version 0.5-dev

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#14174]
While investigating #14163, I found that julia 0.5 (Window Build) crashes while attempting to compute svd of a 1000x1000 matrix the 2nd of the 2 files [in this gist](https://gist.github.com/waTeim/f5a107e00c5d62a25c79) illustrates the problem.

**Comment by tkelman** [comment]
most likely the same as https://github.com/xianyi/OpenBLAS/issues/697

**Comment by tkelman** [comment]
Were you using a nightly or a source build? I have a fix (thanks @matzeri) in #14174.

**Comment by waTeim** [comment]
nightly.  currently build from src is broken for me (msys2)

**Comment by tkelman** [comment]
When did you last try? I think Keno fixed that one in #14164 a few days ago.

**Comment by waTeim** [comment]
oh excellent.  i last tried 5 days ago.  will retry and provide results.

**Comment by waTeim** [comment]
Yea that patch fixed gmp dep compile, however there are additional errors following this.  The errors different for windows 7 and windows 10 compilation.  Perhaps these should be separate tickets?

To keep things simple for now, ill just add to the gist.  Here's the [fail on windows 7](https://gist.github.com/waTeim/f5a107e00c5d62a25c79#file-windows7compfail-txt)

**Comment by waTeim** [comment]
And here it is [on Windows 10](https://gist.github.com/waTeim/f5a107e00c5d62a25c79#file-win10fail-txt).  A completely different problem obviously,which could be because there are simply different systems, however, these 2 systems were built at more of less the same time.

**Comment by tkelman** [comment]
Did you recently update windows 10? Check the cygwin mailing list, microsoft broke cygwin in the latest windows 10 update.

**Comment by waTeim** [comment]
Yup, sure did, ironically in preparation to test this and although I'm using MSYS2 rather than Cygwin, I feel confident that the same underlying issue is the cause.

**Comment by tkelman** [comment]
the core posix layer is more or less the same. it'll likely get fixed in cygwin first (possibly via a test release, they like making those available early) then rebased into msys2 at some future point. unless the msys2 guys come up with their own patch, but I suspect they'd want to upstream it anyway.
