### ISSUE TITLE
`code_native` shows labels in wrong places

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14184]
I built Julia, master branch, on OS X, with LLVM 3.7.0 and with threading enabled.

This function:
```Julia
function axpy!(a,x,y)
    @inbounds for i in eachindex(y)
        y[i] += a*x[i]
    end
end
```
leads to this output:
```
julia> code_native(axpy!, (Float64, Vector{Float64}, Vector{Float64}))
L99:L128:L172:L177:L208:	.section	__TEXT,__text,regular,pure_instructions
	pushq	%rbp
	movq	%rsp, %rbp
	movq	8(%rsi), %rax
	cmpq	$1, %rax
	jl	L238
	movl	$1, %r8d
	movq	(%rsi), %rcx
	movq	(%rdi), %rdx
	cmpq	$0, %rax
	je	L177
	movl	$1, %r8d
	leaq	1(%rax), %r9
	movq	%rax, %r10
	andq	$-8, %r10
	orq	$1, %r10
	cmpq	$1, %r10
	je	L172
	leaq	-1(%rax), %rdi
	shlq	$3, %rdi
	leaq	(%rcx,%rdi), %rsi
	leaq	(%rdi,%rdx), %rdi
	cmpq	%rdi, %rcx
	ja	L99
	movl	$1, %r8d
	cmpq	%rsi, %rdx
	jbe	L172
	vbroadcastsd	%xmm0, %ymm1
	leaq	32(%rcx), %rsi
	leaq	32(%rdx), %rdi
	movq	%rax, %r8
	shrq	$3, %r8
	shlq	$3, %r8
	nopl	(%rax,%rax)
	vmulpd	-32(%rdi), %ymm1, %ymm2
	vmulpd	(%rdi), %ymm1, %ymm3
	vaddpd	-32(%rsi), %ymm2, %ymm2
	vaddpd	(%rsi), %ymm3, %ymm3
	vmovupd	%ymm2, -32(%rsi)
	vmovupd	%ymm3, (%rsi)
	addq	$64, %rsi
	addq	$64, %rdi
	addq	$-8, %r8
	jne	L128
	movq	%r10, %r8
	cmpq	%r8, %r9
	je	L238
	addq	$1, %rax
	subq	%r8, %rax
	addq	$-1, %r8
	shlq	$3, %r8
	addq	%r8, %rdx
	addq	%r8, %rcx
	nopw	%cs:(%rax,%rax)
	vmulsd	(%rdx), %xmm0, %xmm1
	vaddsd	(%rcx), %xmm1, %xmL238:m1
	vmovsd	%xmm1, (%rcx)
	addq	$-1, %rax
	addq	$8, %rdx
	addq	$8, %rcx
	cmpq	$0, %rax
	jne	L208
	movabsq	$4436967440, %rax       ## imm = 0x10876C010
	popq	%rbp
	vzeroupper
	retq
```

Note that (a) many labels are wrongly accumulated near the top, and (b) label "L238:m1" is missing a line break before the label.

**Comment by yuyichao** [comment]
This is a known problem on LLVM 3.7. I thought there's an issue open for it or it is mentioned somewhere in another issue but I can't fine it.

**Comment by vtjnash** [comment]
looks like the LLVM IO system may have changed and is flushing incorrectly?

**Comment by eschnett** [comment]
@vtjnash Yes, it seems as if the instructions aren't flushed before labels are written. I don't know whether this is the only issue, or whether there's another issue with labels having the wrong address.

@yuyichao Is this an issue in LLVM (read: needs to be fixed there), or with Julia talking to LLVM (read: needs to be addressed in Julia)?

**Comment by yuyichao** [comment]
I don't know what exactly is the issue but given `clang -S` seems fine and `gdb` `disassemble` is also correct (which is what I use to check the native code these days....) I think it's probably something with printing on our side.

**Comment by eschnett** [comment]
Note: We're outputting other information (e.g. `.section` headers in the same way, and these should probably also be fixed.

**Comment by vtjnash** [comment]
looks like b52d0a56 incorrectly renamed the real output from `stream` to `ustream`

**Comment by eschnett** [comment]
`ustream` is only a temporary and can't be used after setting up the streamer. LLVM will buffer the stream that is passed in, so that `stream` shouldn't be used any more in our code. I don't know whether we can keep a copy of the `formatted_raw_ostream` passed to LLVM; if it expects a unique object we probably cannot.

Having said this: The new way of writing symbols is simpler and cleaner than the old way, so I actually prefer it. The new code is longer than the old one only because it still needs to support LLVM 3.3; without this, it would be shorter.

**Comment by vtjnash** [comment]
yeah, the new code looks better there. but when i looked at your initial PR, you were missing a number of other writes to `stream`

the `ustream` temporary is created by making a copy-by-value clone of `stream`, which was not what this code should have been doing

**Comment by eschnett** [comment]
`createAsmStreamer` requires a `unique_ptr`. The only way to get this is to either make a copy (as the code does), or to not use the stream after this code in Julia... which is probably what we should be doing.

**Comment by vtjnash** [comment]
we could also `.get` the pointer from the `unique_ptr` so that they were looking at the same stream. or we can alter the code so that some parts go to the comment stream and other parts write raw bytes to the Streamer

**Comment by eschnett** [comment]
LLVM expects the formatted stream in a `unique_ptr`, which means it will destruct the stream afterwards. However, we need to keep a copy of the stream. The best solution I could find is to create a raw stream, create a formatted stream as copy of it that LLVM can then delete, and keep the raw stream.

That's what the original code was doing (almost), except it wasn't explained, and a superfluous formatted stream was created that was implicitly converted back to a raw stream. 

I updated the PR.

**Comment by vtjnash** [comment]
thanks

**Comment by yuyichao** [comment]
Accidentally find the issue I reported last time https://github.com/JuliaLang/julia/issues/13257
