### ISSUE TITLE
Linker warning on OSX -- wrong version number used?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14182]
I see this warning when building Julia (0.5 master):

```
ld: warning: object file (/Users/eschnett/src/julia05/usr/lib/julia/sys.o) was built for newer OSX version (15.0) than being linked (10.7)
```

Note that the OSX version of my system is 10.11 (El Capitan), while my kernel version is 15.0. This looks as if some script used the kernel version instead of the OSX version when using the `-macos_version_min` option to `ld`.

PS: There's no "OSX" or "Apple" label for issues. But there's an "MS-DOS" one?

**Comment by Keno** [comment]
There's a `mac` one and the MS-DOS one was a joke ;)

**Comment by eschnett** [comment]
I see these lines in `Make.inc`:
```
$ grep DARWINVER Make.inc 
DARWINVER := $(shell uname -r | cut -b 1-2)
DARWINVER_GTE13 := $(shell expr `uname -r | cut -b 1-2` \>= 13)
ifeq ($(DARWINVER), 10) # Snow Leopard specific configuration
ifeq ($(DARWINVER_GTE13),1)
```
They may confuse "Darwin version" and "OSX version". I doubt that many places in Julia will need to know the kernel version, whereas the OSX version seems relevant in many respects since Apple's toolchain changes.

I suggest switching from `uname` to `sw_vers -productVersion`, which returns e.g. `10.11.1` for me, `10.11` being "El Capitan".

**Comment by ViralBShah** [comment]
Yes, we should probably get rid of DARWINVER and switch to OS X versions. Perhaps worth fixing #6674 too in favour of using OS X versions.

**Comment by vtjnash** [comment]
Probably worth nothing that this is an upstream bug (llvm), not Julia: http://lists.llvm.org/pipermail/llvm-dev/2015-September/090758.html

**Comment by kshyatt** [comment]
This is still happening to me! Is there an (upstream) fix? Should I switch the LLVM version I'm using?
