### ISSUE TITLE
float(X) vs. map(Float64, X) on 64bits

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#14189]
Test case:
```julia
A = ones(10,10)
A[:,5] = NaN
B = float(A)
C = map(Float64, A)

@assert B == C "this assertion fails"
```

Is this expected behavior or a bug?

**Comment by yuyichao** [comment]
This is expected.

```
julia> A == A
false

julia> NaN == NaN
false

julia> isequal(A, A)
true

julia> B == C
false

julia> isequal(B, C)
true
```

**Comment by juliohm** [comment]
That is true! I always forget the weirdness of NaN.

For some reason there is something failing in my package if I replace map() with float in https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L138

```julia
Pkg.test("ImageQuilting")
```

I will try to figure it out later, thanks.
