### ISSUE TITLE
Remove Failed __precompile__() attempts

### ISSUE THREAD

**Issue by JeremyRubin** [JuliaLang/julia#14183]
see https://github.com/JuliaStats/NullableArrays.jl/issues/91

When the module fails to precompile, the garbage .ji is left in the lib directory which can be annoying.

I would recommend having these files be precompiled, and then deleted if there is an error.

**Comment by tkelman** [comment]
Please include the output of `versioninfo()` with future bug reports.

Given https://github.com/JuliaStats/NullableArrays.jl/issues/91#issuecomment-160486187 it sounds like this was fixed between 0.4.0 and 0.4.1, so I'm closing. Leave a comment if you think it should be reopened for any reason.
