### ISSUE TITLE
Inner product should return scalar

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#14197]
Currently `x'y` or `x'A*x` (where `x` and `y` are vectors and `A` is a matrix) returns the result of this inner product as an array with 1 element. This is very inconvenient. One example among others is when I try to store the results of multiple inner products in vector (call it `z`), instead of generating vector of scalars, it generates vector of arrays (each with only a single element), and now I cannot apply inner product to `z`, (i.e. `z'y` will issue conversion error). Workaround I currently have is to scalarize with as `sum(x'y)`, but this is verbose confusing and redundant. As someone with math background I keep getting tripped on this caveat, and not having debugger with UI makes it even more difficult to catch it.
MATALB, as a comparison returns scalar for equivalent comand.

**Comment by jakebolewski** [comment]
#4774
