### ISSUE TITLE
`GIT_EXEC_PATH` in OSX builds

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#14200]
It seems that the OSX builds set `GIT_EXEC_PATH` and `GIT_TEMPLATE_DIR` [here](https://github.com/JuliaLang/julia/blob/2d821670d2516cd38b51710b07b3eb18f191cd1b/contrib/mac/juliarc.jl), however this results in git permission issues for any packages trying to clone dependencies via https.

ex) `
julia> Pkg.build("Homebrew")
INFO: Building Homebrew
INFO: Cloning brew from https://github.com/Homebrew/homebrew.git
Cloning into '.../v0.4/Homebrew/deps/usr'...
fatal: cannot exec 'git-remote-https': Permission denied
==============================[ ERROR: Homebrew ]===============================
​`

For now I'm just removing those environment variables in my `.juliarc.jl`. I'm not sure why it only seems to be happing for https, but I would think that the mac juliarc.jl file should first check if git already exist on the system before setting those variables.

**Comment by tkelman** [comment]
I think we only use that rc file from contrib/mac in the binary dmg builds that come with their own git? Seems like this would have been reported sooner if it was more widespread?

**Comment by Rory-Finnegan** [comment]
That makes sense since I don't get the issue when I build from source.

**Comment by KristofferC** [comment]
Please comment if this is still a problem.
