### ISSUE TITLE
Cannot call non-exported string macro using dot

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#14208]
A simple example:

``` julia
module Foo
    macro bar_str(s)
        s
    end
end
```

Then:

```
julia> Foo.bar"aa"
ERROR: UndefVarError: bar not defined
```

The parser interprets this as implicit multiplication:

```
julia> macroexpand(:(Foo.bar"aa"))
:(Foo.bar * "aa")
```

Is this something we can change, or is it too baked into the parser?

**Comment by Keno** [comment]
+1, this should be changed for consistency with
```
julia> module foo
       macro bar(x)
       println(x)
       end
       end
foo

julia> @foo.bar 1
1
```

**Comment by JeffBezanson** [comment]
This can be changed in the parser, fairly easily I think.

**Comment by JeffBezanson** [comment]
Though one wonders if we really want more ways to call un-exported things. Maybe you should have to write `@Foo.bar_str("x")`?

**Comment by simonbyrne** [comment]
My use case is in RCall. We have a `@rimport` which creates a new module mirroring the R namespace, however R frequently uses dots in names. I have a string macro [`var`](https://github.com/JuliaStats/RCall.jl/blob/ea119a2f7611fc63a1634923eae6c96b14feec87/src/functions.jl#L35-L37) which allows for use of names with dots in them, so I want to write something like:
```julia
@rimport base as rbase
rbase.var"as.data.frame"(x)
```

**Comment by JeffBezanson** [comment]
Dup of #6970.
