### ISSUE TITLE
Integrate StackTraces.jl into Base

### ISSUE THREAD

**Issue by spurll** [JuliaLang/julia#14212]
A few people in the community have been looking for stacktrace/backtrace functionality that is easier to use programmatically than what is currently provided by `Base.backtrace`. [StackTraces.jl](https://github.com/invenia/StackTraces.jl) provides an immutable StackFrame type that simplifies interacting with a stack trace. (It can be used to add stack trace information when logging with [Lumberjack.jl](https://github.com/WestleyArgentum/Lumberjack.jl) for example.)

@jakebolewski and @iamed2 have recommended that this package be included in Base.

**Comment by JeffBezanson** [comment]
+1

This functionality is very reasonable and compact, and might even simplify things in Base.

**Comment by ihnorton** [comment]
:+1:  Though would be good to unify/refactor with the functions and data structures in `Profile` so that we don't have two names for a number of nearly-identical things. (e.g. [LineInfo](https://github.com/JuliaLang/julia/blob/88527facf1b0ebcf0a68b9f39457d476338ff298/base/profile.jl#L98-L106))

**Comment by tkelman** [comment]
Agreed, there's some overlap with profile. This kind of thing will be really useful for tooling, debugger interfaces etc so may as well agree on a data structure for it.

**Comment by StefanKarpinski** [comment]
+1 – @spurll, do you want to make a PR?

**Comment by spurll** [comment]
Will do. I'm heading out for the night, but barring catastrophe I'll do it first thing tomorrow. Thanks for the feedback, folks!

**Comment by spurll** [comment]
Wow, this took longer than I expected. I've done some refactoring to address redundancies with `Profile`. I plan to issue the pull request on Monday.

**Comment by spurll** [comment]
PR is submitted: https://github.com/JuliaLang/julia/pull/14469

**Comment by yuyichao** [comment]
Closed by https://github.com/JuliaLang/julia/pull/14815 ?
