### ISSUE TITLE
LuaJIT / Julia unfair benchmarking

### ISSUE THREAD

**Issue by stepelu** [JuliaLang/julia#14222]
FIrstly, the Julia and the LuaJIT benchmarks are timed differently: [Julia timeit()](https://github.com/JuliaLang/julia/tree/v0.4.1/test/perf/perfutil.jl#L71-L79), [LuaJIT timeit()](https://github.com/JuliaLang/julia/tree/v0.4.1/test/perf/micro/perf.lua#L40-L43).

In the Julia version, each benchmark is repeated until 2 seconds have elapsed (under the constraint of having at least 5 repetitions, which is not binding on any recent hardware).
In the LuaJIT version, each benchmark is repeated exactly 5 times.

As many of the benchmarks take a handful of milliseconds to execute, this means that we are comparing the timings of thousands of Julia executions with the timings of 5 LuaJIT executions.
As the reported performance for each benchmark is the minimum of such timings, Julia has a far greater chance of achieving a good performance.

Indeed, when the LuaJIT `timeit()` function is modified to match the Julia one (2 seconds minimum for each benchmark) the LuaJIT reported performance improves greatly.

Secondly, Julia 0.4, released 3 weeks ago, is benchmarked against LuaJIT 2.0, released 3 years ago.
As already noted [here](https://github.com/JuliaLang/julia/pull/6430#commitcomment-5996981), the more recent LuaJIT 2.1 includes further optimizations and is an order of magnitude faster in the benchmark `parse_int`.

Thirdly, the benchmark `rand_mat_mul` consists of a single memory allocation followed by a single call to a BLAS function (matrix-matrix multiply).
As such, the performance of the benchmark is determined by the BLAS implementation used.

While Julia relies on the heavily tuned OpenBLAS implementation, you have chosen to benchmark against the gsl-shell library which links by default to a way slower reference BLAS implementation.

Again, as already noted [here](https://github.com/JuliaLang/julia/pull/6430#commitcomment-7015373) a fairer comparison would use OpenBLAS for both Julia and LuaJIT.
For instance, the go language doesn't come with OpenBLAS included but you're still using it for benchmarking, so the same should be done with LuaJIT.

If the argument is that [systems are used the way they ship](https://github.com/JuliaLang/julia/issues/5128#issuecomment-30533825), then scientific frameworks for LuaJIT are available that ship with LuaJIT 2.1 and OpenBLAS, such as [Torch7](http://torch.ch/) and [SciLua](http://scilua.org) (of which I am the author).

I have ported the [Lua benchmark](https://github.com/JuliaLang/julia/blob/v0.4.1/test/perf/micro/perf.lua) to use SciLua instead of gsl-shell and to fix the `timeit()` function as explained above: [perf_v1.0.sci.lua](http://scilua.org/download/perf_v1.0.sci.lua).
All results are verified to avoid dead-code-optimizations and, aside from the matrix-matrix BLAS multiply, it's 100% pure LuaJIT code.

The script can be run via:

```
wget http://scilua.org/download/perf_v1.0.sci.lua
wget http://ulua.io/download/ulua~latest.zip
unzip ulua~latest.zip

export BIT=64    # Use LuaJIT for x64
yes | ./ulua/bin/upkg add time    # For timing
yes | ./ulua/bin/upkg add sci-lang    # SciLua

./ulua/bin/scilua perf_v1.0.sci.lua

**Comment by jiahao** [comment]
Thank you for your detailed analysis. The only reason why gsl-shell 2.0 is used is because that's what Ubuntu 15.04 provides and that's what our test machine runs. (I personally don't use Lua myself except as an end user of LuaTeX.)

We'd be happy to take a pull request to improve the benchmarks.

**Comment by jiahao** [comment]
I should also note that the current microbenchmarks on http://julialang.org use gsl-shell 2.3.1, which is the most recent version available through Ubuntu, and that the performance of Lua has improved dramatically in comparison.

**Comment by jiahao** [comment]
For reference, here are the numbers on our test machine (relative to best timings on gcc 5.1.1).

 microbenchmark | julia 0.5.0-dev | gsl-shell 2.3.1 | scilua 1.0
 --------------- | --------- | ---------- | ---------------
        fib      | 1.94      | 1.70  | 1.22
     parse_int   | 1.47      | 5.77  | 0.93
     quicksort   | 1.17      | 2.01  | 1.52
      mandel     | 0.77      | 0.68  | 0.64
      pi_sum     | 1.00      | 1.00  | 1.00
   rand_mat_stat | 1.95      | 3.26  | 1.54
   rand_mat_mul  | 1.01      | 1.16  | 1.07

**Comment by stepelu** [comment]
Thank you for the prompt reply.

Yes, these results are in line with what I have been observing. 
Mandel and fib are sometimes faster but as the JIT trace compiler uses probabilistic heuristics there is variability across benchmark repetitions.

I will work on a pull request as suggested.

**Comment by ViralBShah** [comment]
@stepelu As @jiahao said, thanks for the detailed analysis. We definitely would love to have a PR, and hopefully it will be easy to install scilua in future runs of our benchmark, which uses the right BLAS.

**Comment by stepelu** [comment]
Just made the PR. 

Please notice that the PR-committed `perf.lua` file depends on the latest version of SciLua, use `upkg update` to update.

Let me know if there are any issues.
