### ISSUE TITLE
Unclear error message in failing `@test_throws`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14239]
This is Julia's trunk. I received this error when running tests (with a modified Base):
```
$ ./usr/bin/julia -e 'Base.runtests("int")'
     * int                  INFO: T=Int8
Test Failed
  Expression: checked_add(max2,max21)
    Expected: Any
      Thrown: Void
ERROR: LoadError: LoadError: There was an error during testing
```

`Thrown: Void` reads to me as if an exception of type `Void` was thrown. This is incorrect; what actually happened is that no exception was thrown.

**Comment by yuyichao** [comment]
Can we also make it more obvious that what's printed is the expected type and exception type?

**Comment by JeffBezanson** [comment]
+1

**Comment by IainNZ** [comment]
This shouldn't even be possible - if no error is thrown, it should clearly state that. I'll look at this.

**Comment by IainNZ** [comment]
How did the expected error end up as `Any`...

**Comment by IainNZ** [comment]
I can't find this test, can you link me to where it appears in `test/int.jl`? I only see these: https://github.com/JuliaLang/julia/blob/1b51008291074e490e14ef6306fe23a7d9094b1a/test/int.jl#L155-L157

**Comment by IainNZ** [comment]
I'm seeing:
```
julia> using Base.Test

julia> foo() = 5
foo (generic function with 1 method)

julia> @test_throws OverflowError foo()
Test Failed
  Expression: foo()
    Expected: OverflowError
      Thrown: Void
ERROR: There was an error during testing
 in record at test.jl:290
 in do_test_throws at test.jl:222
 in eval at ./boot.jl:263
```
Which is obviously not ideal due to the `Void`, so I'll improve the message, but I'm more worried about the `Any`

**Comment by mason-bially** [comment]
I would add that it would be nice to see the full error of the received exception, this would make it easier to debug tests.

**Comment by IainNZ** [comment]
Thats a reasonable idea @mason-bially, and shouldn't be too complicated. If you want to take a stab at it, I'd review that PR and try to help you with any issues.

**Comment by mason-bially** [comment]
Yea, no problem, I'll take a crack at it this weekend once I finish another issue I'm working on.

**Comment by IainNZ** [comment]
Was closed by https://github.com/JuliaLang/julia/pull/14242
