### ISSUE TITLE
polyeig function

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#14232]
It would be nice to have a [polyeig](http://www.mathworks.com/help/matlab/ref/polyeig.html) function, either in Base or in a package.   There are straightforward algorithms for solving these by converting to a larger linear eigenvalue problem (see e.g. [this thesis for a nice review](http://www.ma.man.ac.uk/~ftisseur/phd/mberhanu05.pdf)).

Of course, there are also more general classes of nonlinear eigenvalue problems, but `polyeig` is pretty basic, and at least for low-degree polynomials it seems pretty simple to implement unless there are pitfalls in the linearization that I'm not aware of.

**Comment by Mirage10** [comment]
+1

**Comment by KristofferC** [comment]
Seems good to do in a package. Perhaps not needed to have a dedicated issue to the language about it.

**Comment by jarlebring** [comment]
For the record, this package is dedicated to this (nonlinear including polynomial): https://github.com/nep-pack/NonlinearEigenproblems.jl
