### ISSUE TITLE
dlopen and cglobal

### ISSUE THREAD

**Issue by benmoran** [JuliaLang/julia#14238]
If I dlopen() a shared library in a function, then cglobal can't find the imported symbols while I'm still inside the function (although I see in /proc that the process has indeed opened the library).  The symbol is available after the function returns:
```
julia> g() = begin
       Libdl.dlopen("libpython2.7", Libdl.RTLD_GLOBAL)
       cglobal(:Py_GetVersion, Ptr{Void})
end

julia> g()
ERROR: cglobal: could not find symbol Py_GetVersion
 in g at none:3

# but now it is available
julia> cglobal(:Py_GetVersion, Ptr{Void})
Ptr{Ptr{Void}} @0x00007f5b21baa320
```
Is this expected, and is there any workaround? (I'm using Julia 0.4.1 on Ubuntu 14.04.)

**Comment by vtjnash** [comment]
the argument to cglobal should be `(:Py_GetVersion, "libpython2.7")`. the one-argument form is for stuff in libc and libjulia

**Comment by yuyichao** [comment]
Or use `dlsym` on the handle returned from `dlopen`
