### ISSUE TITLE
Where to make suggestions for correction of documentation?

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#14236]
My experience using page http://docs.julialang.org/en/latest/manual/packages/#code-changes leads me to suggest a couple of updates in light of the change from Pkg.submit to PkgDev.submit. Where to file the suggestion?

**Comment by timholy** [comment]
Thanks for the offer to pitch in!

You can edit [this file](https://github.com/JuliaLang/julia/blob/master/doc/manual/packages.rst) in your web browser (click the "pencil" icon), or follow a procedure similar to that described for packages:
```
git checkout master
git pull
git checkout -b my_doc_branch
<edit file>
git commit -a -m "Some commit message"
git push myfork my_doc_branch
```
where you've already set up your own fork of julia.

See also https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation

**Comment by kshyatt** [comment]
@colbec if you need more help, you can pop into #julia on Freenode or the Julia Gitter channel and someone will be happy to walk you through any questions :)

**Comment by stevengj** [comment]
Seems resolved?
