### ISSUE TITLE
combine `withenv` and `setenv`?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14249]
It is quite common to need setting one particular environment variable when running a command,notably `LC_ALL=C` to parse reliably the output (e.g. https://github.com/JuliaLang/BinDeps.jl/issues/188). When looking for the most straightforward way of doing this, one finds `setenv`, and is thus tempted to write ``run(setenv(`mycmd`, "LC_ALL"=>"C"))``.

As the docs clearly say, this runs the command in a completely clean environment. But is this what is most commonly needed? In many cases, one would better preserve `PATH` to find commands in non-standard directories. Code failing to do so will work fine in most setups, but fails on some others, which is always painful for users.

So I wonder whether there should be another one-liner to run a command in a modified environment, so that people are not tempted to use `setenv` because that's the most obvious solution.

**Comment by tkelman** [comment]
see `withenv` ? especially with do block form it's pretty concise and does the job

**Comment by nalimilan** [comment]
It's much less appealing than `setenv()`, which can be written as a one liner like (as in JuliaLang/BinDeps.jl#188) ``for l in eachline(setenv(`mycmd`, "LC_ALL"=>"C"))``. I'm not saying it's terrible (making a copy of `ENV` and modifying it is quite short too), but I wonder whether `setenv()` is not too appealing given that it's not always (often?) the best solution. Do we expect people to need a clean environment more often than not? Or do we prefer them to do so by default to limit security issues?

**Comment by StefanKarpinski** [comment]
One option: a keyword arg for `setenv` indicating whether it starts from a clean slate or not, i.e.

```jl
setenv(`mycmd`, "LC_ALL" => "C", clean = true)  # `mycmd` with only LC_ALL in env
setenv(`mycmd`, "LC_ALL" => "C", clean = false) # `mycmd` with inherited env + LC_ALL=C
```

Alternate approach would be to have an `addenv` function similar to `setenv`:

```jl
setenv(`mycmd`, "LC_ALL" => "C") # `mycmd` with only LC_ALL in env
addenv(`mycmd`, "LC_ALL" => "C") # `mycmd` with inherited env + LC_ALL=C
```

**Comment by tkelman** [comment]
could (or does?) withenv non-ambiguously take a Cmd as the first input instead of Function?

**Comment by Keno** [comment]
Note, you can already do
```
setenv(`mycmd`, merge(ENV,Dict("X"=>"X")))
```
not opposed to having a slightly shorter alias of course (maybe it's sufficient to just remove the requirement for the extra `Dict`?

**Comment by nalimilan** [comment]
Looks like `setenv` and `withenv` have completely unambiguous signatures. I'd vote for merging them, since their purpose is the same, and they only differ in what they run (command vs. function). Then (as Stefan said) we can add a `clean::Bool` keyword argument.

**Comment by tkelman** [comment]
sounds good. allows for a deprecation path for `setenv` via `clean=false`, and a new feature for the do-block `withenv` of supporting `clean=true` which it doesn't now

**Comment by StefanKarpinski** [comment]
Nice. That's a win-win :)

**Comment by nalimilan** [comment]
Cool. But should we merge into `withenv`, into `setenv`, or find another name? `withenv` would sound a bit unusual for a function returning a new command with a modified environment. `setenv` sounds OK even for the `do` block syntax, so I'd rather go with it.

**Comment by tkelman** [comment]
If we use `setenv` then it would be breaking to change the default behavior on `Cmd` objects for `clean`.

**Comment by nalimilan** [comment]
Right.  Yet, I don't like `withenv` in that context. :-)

We could print a deprecation warning when `clean` isn't set, by giving it a special default value. But whatever you think is best.

**Comment by StefanKarpinski** [comment]
I think `withenv` is quite fitting: it's the command but with a specific environment.

**Comment by JeffBezanson** [comment]
Agreed; `setenv` sounds like a mutating operation (which, in a shell, it usually is).

**Comment by stevengj** [comment]
Note that `env` is a field of `Cmd` objects, and it good to provide access to this.  However, as I mentioned in #13780, it might be worthwhile to deprecate `detach`, `ignorestatus`, and `setenv` in favor of `Cmd(cmd; detach=..., ignorestatus=..., env=...)`.

**Comment by nalimilan** [comment]
Doesn't sound like a bad idea. But then, the question of making it easy to modify the existing environment (rather than using a clean one) remains. Should we also add a `cleanenv` keyword argument?

**Comment by stevengj** [comment]
I'm not clear what `cleanenv=false` is supposed to do.  It is it equivalent to doing `setenv` with a `copy(ENV)` and then modifying one or more variables in the copied environment?   This may not be what the user expects since subsequent changes to `ENV` won't affect the `Cmd` object.

**Comment by nalimilan** [comment]
> I'm not clear what cleanenv=false is supposed to do. It is it equivalent to doing setenv with a copy(ENV) and then modifying one or more variables in the copied environment?

Yes, that was the idea.

> This may not be what the user expects since subsequent changes to ENV won't affect the Cmd object.

Right, but I don't expect this to be a big problem (as long as it's documented). I would say the most common scenario is that you want to pick the environment passed to the current process when it was started. Anyway, any other way of doing this would have the same behavior.

**Comment by laborg** [comment]
I think we can close this since `addenv` (since https://github.com/JuliaLang/julia/pull/39100) is able to do this.
