### ISSUE TITLE
`v = []; push!(v, length(v))` produces [1]

### ISSUE THREAD

**Issue by xitology** [JuliaLang/julia#14245]
```
$ julia -E 'f() = (v = []; push!(v, length(v)); v); f()'
Any[1]
```
However, if you disable inlining, you get the correct result.
```
$ julia --inline=no -E 'f() = (v = []; push!(v, length(v)); v); f()'
Any[0]
```

```
$ julia -e 'versioninfo()'
Julia Version 0.5.0-dev+1491
Commit 41fb1ba (2015-11-27 16:54 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by JeffBezanson** [comment]
Seems to work in 0.4.

**Comment by JeffBezanson** [comment]
Also, excellent catch. Thanks for this.

**Comment by StefanKarpinski** [comment]
Should we have a regression test for this somewhere? (Not sure what test file to put it in though.)

**Comment by kshyatt** [comment]
@StefanKarpinski isn't this what `test/misc.jl` is for? :wink:

**Comment by StefanKarpinski** [comment]
Ok, we have a test for this now, but it's failing on 0.5. Since this doesn't fail on 0.4, we can actually backport it safely and then merge on 0.5 once the issue is fixed.
