### ISSUE TITLE
beta(-n,n) should return ±1/n, not NaN

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#14256]
In #14165, @CarloLucibello noticed a bug in our `beta` function: `beta(-n,n)` is returning `NaN` for integers `n`, whereas the correct answer is `(-1)^n / n`, I think.

**Comment by stevengj** [comment]
[scipy.special.beta](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.special.beta.html) gives the correct answer here.

**Comment by stevengj** [comment]
It would be easy to simply check for integer arguments.   However, it is important to make sure that we also correctly handle any arguments *close* to `(-n,n)`.

**Comment by stevengj** [comment]
The scipy beta implementation is [from Cephes](https://github.com/scipy/scipy/blob/0cff7a5fe6226668729fc2551105692ce114c2b3/scipy/special/cephes/beta.c#L61-L133), and includes some special-case code that we are missing:

* It has special handling for negative-integer arguments.
* It has special handling for `|a| >> |b|`.
* For small arguments, it calls `gamma` directly rather than exponentiating `lgamma`.

**Comment by andreasnoack** [comment]
What is the defintion for the beta function negative (integer) first argument? It appears to me that the usual integral definition doesn't converge for e.g. (-2,2). Negative integer arguments for `x` are allowed in Mathematica but I couldn't find any explanation or definition in their documentation. Abramowitz and Stegun as well as Wikipedia require positive real part of both arguments.

**Comment by CarloLucibello** [comment]
It is defined through the gamma functions I think, for negative  `x` and `y` the integral representation doesn't hold anymore.

If you agree on this I could create a PR addressing this bug mimicking the scipy implementation

**Comment by stevengj** [comment]
If you take the limit of the gamma function definition as (z,n) approaches (-n,n), you get a finite and well-defined result.  Besides being unambiguous, this seems to be totally standard; e.g. it is what Mathematica returns.

**Comment by andreasnoack** [comment]
I have no problem with extending the beta function, but

> ...this seems to be totally standard

is not a fair description. Cephes [doesn't support](https://github.com/jeremybarnes/cephes/blob/master/misc/beta.c#L88-L97) negative arguments. Support for that was a [relatively recent modification](https://github.com/scipy/scipy/commit/306eb867773ed7a89dbe65c6f12eceb7fe785c5c). Neither does the Naval Surface Warfare Center library and, as mentioned, Abramowitz and Stegun doesn't define the function for negative arguments.

**Comment by stevengj** [comment]
@andreasnoack, thanks for the clarification, I didn't realize it was a recent modification to Cephes.

[Maple](http://www.maplesoft.com/support/help/maple/view.aspx?path=Beta) also defines beta for negative integers by the limit.

**Comment by andreasnoack** [comment]
Thanks for the link. In contrast to Mathematica, Maple's documentation states the definition for negative integers. It would be great if we included a similar comment about negative integer x in our documentation.

**Comment by simonbyrne** [comment]
I mentioned the `|a| >> |b|` problem [here](https://github.com/JuliaLang/julia/issues/4301#issuecomment-24736245).

I remember looking at the Cephes code before, and was a bit underwhelmed, but there probably are some good ideas there. Also, I never managed to find its licence status (though presumably whomever has copyright presumably doesn't care that much).

**Comment by stevengj** [comment]
@simonbyrne, apparently the Cephes author gave permission to distribute it under 3-clause BSD; see [e.g. here](https://github.com/deepmind/torch-cephes/blob/master/LICENSE.txt).  Also, apparently [Debian inquired about this 10 years ago](https://lists.debian.org/debian-legal/2004/12/msg00295.html) and got 3-clause BSD permission: the `/usr/share/doc/python-scipy/copyright` file on my Debian machine lists:
```
Files: scipy/special/cephes/*
Copyright: 1984, 1987, 1989, 2000 Stephen L. Moshier
License: BSD-3-clause
```

**Comment by simonbyrne** [comment]
Good to know, thanks.

**Comment by Peiffap** [comment]
Perhaps this issue can be closed, as the functionality for the beta function is now in the [SpecialFunctions.jl](https://github.com/JuliaMath/SpecialFunctions.jl) package.

There is also an issue there that seems to be about the very same problem, https://github.com/JuliaMath/SpecialFunctions.jl/issues/149. If this one does get closed, it might be worth mentioning there was was mentioned on this issue.
