### ISSUE TITLE
round(Int,1+0im) throws an error while convert does not (Int,1+0im) in 0.4.1

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#14261]
The following seems inconsistent:

``` julia
julia> convert(Int,-1+0im)
-1

julia> round(Int,-1+0im)
ERROR: MethodError: `round` has no method matching round(::Type{Int64}, ::Complex{Int64})
Closest candidates are:
  round{T<:Integer}(::Type{T<:Integer}, ::Integer)
  round{T<:Integer}(::Type{T<:Integer}, ::Float16)
  round{T<:Union{Signed,Unsigned}}(::Type{T<:Union{Signed,Unsigned}}, ::BigFloat)
  ...
```

**Comment by stevengj** [comment]
What would `round(Int, -1+2im)` return?   Since the `round` function is not sensible for most points on the complex plane, I'm skeptical that we should define it on the real axis.

**Comment by dlfivefifty** [comment]
The same thing as convert: it would through an error

**Comment by stevengj** [comment]
Is there any precedent in any other language for a `round` function that works for complex z?

**Comment by dlfivefifty** [comment]
I'm more just advocating that round and convert are almost the exactly the same thing, and so should behave the same.

So maybe remove convert(Int,1+0im)

**Comment by dlfivefifty** [comment]
Also in Mathematica

Round[1 + 0.1 I]  == 1

**Comment by StefanKarpinski** [comment]
We could define `round(z::Complex) = Complex(round(real(z), round(imag(z)))`.

**Comment by StefanKarpinski** [comment]
Doesn't quite address this issue.

**Comment by jiahao** [comment]
> We could define `round(z::Complex) = Complex(round(real(z), round(imag(z)))`.

@StefanKarpinski we already do: see #8291

**Comment by stevengj** [comment]
Yes, the `Round` function in mathematica is analogous to our current `round(z)`, not the proposed `round(Int, z).  e.g. `Round[1 + 1.1 I]` gives `1+i`.

**Comment by dlfivefifty** [comment]
I suppose it's not clear what the following should return:

round(Int,1+0im)
round(Int,1+eps()im)
round(Int,1+0.1im)
round(Int,1+0.6im)
round(Int,1+2im)


I think if all returned 1 it would make sense, if we think of the definition of round(T,x) as convert to type T, rounding if necessary.

**Comment by laborg** [comment]
Has been addressed in https://github.com/JuliaLang/julia/pull/50812

```
julia> round(Int,-1+0im)
-1
```

**Comment by dlfivefifty** [comment]
I didn't see a unit test added for this case. Can we add a `@test round(Int,-1+0im) === -1`?
