### ISSUE TITLE
RROR: LoadError: MethodError: `setindex!` has no method matching setindex!(::UInt32, ::UInt8, ::Int64)

### ISSUE THREAD

**Issue by sononix** [JuliaLang/julia#14267]
Any reason i should be getting this from the terminal 
RROR: LoadError: MethodError: `setindex!` has no method matching setindex!(::UInt32, ::UInt8, ::Int64)

running bit by bit in the julia environment I cant seem to track down the error 
tks
M

**Comment by yuyichao** [comment]
Please provide more info about how to reproduce your error.

**Comment by JeffBezanson** [comment]
This would happen, for example, if you ran `A[i] = UInt8(0)` but `A` was a `UInt32` instead of some kind of array.

**Comment by sononix** [comment]
here is the stripped down code

function SHIFT(x::UInt8)
  return UInt8(((x)<<2) | ((x)>>6))
end

function WRAP1(a::UInt8,b::UInt8)
  return UInt8(SHIFT(a+b))
end


function WRAP2(a::UInt8,b::UInt8)
  return UInt8(SHIFT(a+b+0x01))
end

# SHIFT(x::Int64) = UInt8(((x)<<2) | ((x)>>6))

function myfunc(inVal::UInt32)
    y = 0x00000000;
    x = hex2bytes(hex(inVal));
    a = x[2]$x[1];
    b = x[3]$x[4];
    y[2]=WRAP2(a,b);
    # // printf("- %02x \n",x[0]);
    y[1]=WRAP1(x[1],y[2]);
    y[3]=WRAP1(y[2],b);
    y[4]=WRAP2(y[3],x[4]);
    # // printf("- %02x \n",y[0]);
    return y
end


barrell = [0xbbaa4b0a,0xaaaaaa2c,0xaaaaaa3d,0xaaaaaa4e,0xaaaaaa5f,0xaaaaaa6a]

left = 0xaabbccff
right=left$0xaabbccdd
#
# L= collect(1:4)
# R= collect(1:4)

for j in 1:4
  temp=right;
  tmpval = right$barrell[j];
  right=left$(myfunc(tmpval));
  left=temp;
  # j==1 ? println(hex(left)) : println(j*10)
end

----
I think my error is here >>
  return UInt8(SHIFT(a+b+0x01))

**Comment by JeffBezanson** [comment]
The error is in `y[2]=WRAP2(a,b);`. `y` is an integer, and integers don't support index assignment.
