### ISSUE TITLE
nb_available (v0.4) returning 0 erroneously

### ISSUE THREAD

**Issue by jkaye2012** [JuliaLang/julia#14269]
Hey all,

Recently, I've made changes to [Redis.jl](https://github.com/jkaye2012/Redis.jl) to transition from v0.3 to v0.4. I'd like to tag the latest version so that users can stop getting deprecation warnings in their v0.4 code. Unfortunately, I've ran into an issue that I can't seem to resolve.

This code was working under v0.3: https://github.com/jkaye2012/Redis.jl/blob/master/src/client.jl#L47

Under v0.4, `nb_available()` seems to always be returning 0. I know that there is data available to the socket; I see it being sent from the Redis server, and if I change the code to use a blocking read, the data is read in as expected (the API can't actually use a blocking read for reasons detailed in that code).

Is this an issue in nb_available, or am I misunderstanding something? Is there another way that I should be trying to accomplish this?

Thanks,
Jordan

**Comment by vtjnash** [comment]
i'm not sure what you are trying to accomplish, but `nb_available` is not going to work. why can't the code just call `getline` and wait for a return value? it looks like that's what the code is doing anyways, but with a busy loop instead of an eventful notification when waiting for the first byte to arrive.

**Comment by jkaye2012** [comment]
Why would nb_available not work?

You can't use a blocking connection for the reasons detailed in the comment. There is a single connection used for subscription in Redis; blocking while waiting to receive a message causes subsequent subscription requests to block until a message is received (obviously this is not okay).

**Comment by vtjnash** [comment]
> blocking while waiting to receive a message causes subsequent subscription requests to block until a message is received

i still don't understand this statement. is this socket being used from multiple places? wouldn't that be a race condition? read in julia is only task-blocking, not thread/process blocking, so i don't understand why you need this task to busy-loop.

> Why would nb_available not work? What is that function supposed to do? 

The function returns the number of bytes that can be read from a stream without a syscall. Your loop doesn't have a subscriber for reading bytes out of the stream, so Julia never executes the syscall to pull data out of the stream. On v0.3, streams were always registered for reading, which defeats the intended throttling benefits of blocking reads (among other issues), so that was fixed in v0.4.

**Comment by jkaye2012** [comment]
That second bit makes a lot of sense and definitely explains the source of this problem, so thanks for that!

On to finding a solution, I'll start with a quick explanation of what I'm doing here. In Redis, the same socket is used in two ways (well, multiple ways really, but two that we're concerned with here). First, you send a subscribe message. This is an outgoing message to the Redis server telling it to send messages back to this socket that match the specified topic. So you can poll from the socket from this point on and receive data from the server.

The difficulty is that you're allowed (and expected) to issue multiple subscribe messages from the same socket. In doing so, all messages matching any subscribed topics will come back through that same socket. So far, so good.

In my testing (the Redis.jl regression tests, linked previously), if the socket is currently blocked on a call (I originally wanted to us `readavailable`) then any subsequent outgoing subscribe messages will block the caller until data is received  by the `readavailable`. I found this functionality very surprising at first, but was told that this was the expected behavior (I haven't been able to find where I was told that, unfortunately).

Given your explanation, I see why nb_available won't work. Do you know why I would be experiencing the aforementioned blocking behavior, or how to get around it?

Thanks,
Jordan

**Comment by vtjnash** [comment]
readavailable is almost never what you want (as observed in https://github.com/jkaye2012/Redis.jl/issues/1, it will return a random, non-zero amount of data, once there is enough data relative to the speed of the channel for the test be non-trivial). the rewrite to use exact newline delimiters shouldn't share those problems.

i'm still not sure i understand the problem you are seeing. it sounds like you are experiencing an issue where you can't transmit on a socket while there is an active reader? i don't understand how that could be, and a quick tests don't seem to indicate any issue:
```julia
julia> x=Base.connect("google.com", 80)
TCPSocket(open, 0 bytes waiting)

julia> @async println(readall(x))
Task (runnable) @0x0000000112544a90

julia> write(x, "GET / HTTP/0.9\n\n")
16
HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=UTF-8
Content-Length: 1555
Date: Sat, 05 Dec 2015 00:09:16 GMT
Server: GFE/2.0

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>


julia> x
TCPSocket(closed, 0 bytes waiting)
```

> the Redis.jl regression tests, linked previously

it helps if you can provide the link to the failures in this thread. i don't follow most issues in other repos, so i don't know what you are referring to here

**Comment by mbaz** [comment]
Should I open an issue about the out-of-date documentation for nb_available()?

**Comment by vtjnash** [comment]
dup of https://github.com/JuliaLang/julia/issues/8762

**Comment by jkaye2012** [comment]
Sorry, I've been on vacation for the past month so was unable to respond to this.

Despite the example that you've given earlier, things do not seem to be working this way for me. Here's a brief snippet of what I'm experiencing. This is not the code that's currently working on V0.3, but my attempt at fixing the issue given what you've told me above. These two functions show that opening a subscription starts an asynchronous processing loop that references a given socket:

```julia
nullcb(err) = nothing
function open_subscription(conn::RedisConnection, err_callback=nullcb)
    s = SubscriptionConnection(conn)
    @async subscription_loop(s, err_callback)
    s
end

function subscription_loop(conn::SubscriptionConnection, err_callback::Function)
    while is_connected(conn)
        try
            l = getline(conn.socket)
            reply = parseline(l, conn.socket)
            message = SubscriptionMessage(reply)
            if message.message_type == SubscriptionMessageType.Message
                conn.callbacks[message.channel](message.message)
            elseif message.message_type == SubscriptionMessageType.Pmessage
                conn.pcallbacks[message.channel](message.message)
            end
        catch err
            err_callback(err)
        end
    end
end
```

There's one other function of interest here, which is `subscribe`. All that `subscribe` does is send an outgoing message on the same connection to the Redis server (this tells Redis to start sending messages back to the socket).

Using the above code, the following works with no problems:

```julia
subs = open_subscription(conn, g)
x = Any[]
f(y) = push!(x, y)
subscribe(subs, "channel", f)
@test publish(conn, "channel", "hello, world!") == 1
```

The following, however, will block until a message is published on "channel" (that is, data is available to be read). Until there is data to read, Julia seems to block the outgoing send:

```julia
subs = open_subscription(conn, g)
x = Any[]
f(y) = push!(x, y)
subscribe(subs, "channel", f)
subscribe(subs, "duplicate", f) # Blocked here until I manually send a publish message to Redis
@test publish(conn, "channel", "hello, world!") == 1
```

I know that the send is not being sent because I've monitored the network traffic. You can see the outgoing message get sent immediately after the incoming message is received (once getline receives data).

Am I just misunderstanding what's going on here? I've tried many permutations, but have been unable to find something that works properly. I'm also open to other solutions to this problem if anyone can think of any.

Thanks,
Jordan

**Comment by jkaye2012** [comment]
I was going to send you this message, but in doing so, I've found my mistake. When sending the subscribe command, I was also waiting for a response back which was blocking - not the socket. I have fixed this. Thanks for the discussion!

The original post, in case anyone cares :)

For completeness (or in case I've messed up somewhere else along the line), here's the remainder of the relevant code:

```julia
function send_command(conn::RedisConnectionBase, command::AbstractString)
    write(conn.socket, command)
end

function pack_command(command)
    packed_command = "*$(length(command))\r\n"
    for token in command
        packed_command = string(packed_command, "\$$(length(token))\r\n", token, "\r\n")
    end
    packed_command
end

function execute_command(conn::RedisConnectionBase, command)
    is_connected(conn) || throw(ConnectionException("Socket is disconnected"))
    send_command(conn, pack_command(command))
    l = getline(conn.socket) ###### Here's my error
    reply = parseline(l, conn.socket)
    return reply
end

function _subscribe(conn::SubscriptionConnection, channels::Array)
    execute_command(conn, unshift!(channels, "subscribe"))
end

function subscribe(conn::SubscriptionConnection, channel::AbstractString, callback::Function)
    conn.callbacks[channel] = callback
    _subscribe(conn, [channel])
end
