### ISSUE TITLE
Some file operations return undocumented `UVError`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14260]
I assumed that failing file operations (`rm`, `'mkdir`, etc.) return a `SystemError` when they fail. However, under certain circumstances they return an undocumented `UVError`. This seems like an unintentional leak of an implementation detail:

```
julia> try rm("a") catch err info(typeof(err)) end
INFO: Base.UVError
julia> try chmod("a", 0) catch err info(typeof(err)) end
INFO: Base.UVError
```

The printed error messages look fine, but e.g. the error codes have different meanings (`SystemError` uses `errno`, `UVError` uses its own set of constants). Having different exception types makes it difficult to handle these errors programmatically.

**Comment by IainNZ** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/7841, I think

**Comment by samoconnor** [comment]
See also #14972
