### ISSUE TITLE
Running powershell messes DPI scaling up

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#14270]
When I open a powershell prompt on my Win10 x64 high DPI laptop (system scaling set to 200%), and then start julia from that powershell prompt, and then run

``` julia
run(`powershell -h`)
```

the whole window of the command prompt seems to lose its scaling, i.e. everything gets very small (small fonts, and the size of the window also decreases). Might also not be related to scaling, but something else, but everything gets small.

This is especially annoying, because any `Pkg.update()` triggers this behavior, given that BinDeps runs `powershell -h` to test whether powershell is installed.

This problem does not occur with other commands, for example running `run(`cmd /C dir`)` works fine. This also doesn't occur if I start julia from a normal command prompt, or if I start julia via the explorer run command.

**Comment by tkelman** [comment]
I'd be surprised if this were a julia bug.

**Comment by davidanthoff** [comment]
Yeah, might well be a windows bug... I don't even know how to start debugging this...

**Comment by tkelman** [comment]
would start by tracing the julia run call down to the equivalent uv_spawn and see if it happens from a standalone C example, either using libuv or calling the same winapi functions they do.

**Comment by ihnorton** [comment]
You could try ccall'ing `SetProcessDPIAware(2)` before shelling out. Also would be good to heck the DPI awareness setting for each of outer-PowerShell/Julia/inner-PS processes in Process Explorer.

My guess is something like this is happening: Julia is detected as a legacy application (?), which defaults to "System" DPI awareness. AFAICT this means that Windows assumes that the process knows about DPI scaling but just doesn't detect scaling changes (e.g. moving between monitors). So then Windows gives unscaled coordinates, but the sub-process thinks it is running in a DPI aware context.

If the above suggestion helps, then we could change the manifest to tell Windows that Julia doesn't know about scaling (for now).

(...this is all guesswork based on a few minutes of reading [here](http://www.drdobbs.com/windows/coding-for-high-dpi-displays-in-windows/240168736) and [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dn280512(v=vs.85).aspx))

**Comment by davidanthoff** [comment]
I think I just observed something similar on a standard DPI system. I'll follow up soon, just wanted to give a heads-up that the DPI angel might be a wrong lead.

**Comment by vtjnash** [comment]
Any update here?

**Comment by davidanthoff** [comment]
I tried this a couple of days ago on my high-res laptop and it still happens. I don't remember what I meant with the standard DPI system comment, and haven't had any problem on a normal DPI system...

**Comment by davidanthoff** [comment]
I have one more bit of info about this: this only occurs when I start julia from a PowerShell prompt. If I start julia via the startmenu, or if I start it from a regular cmd prompt, everything seems ok.

**Comment by musm** [comment]
@davidanthoff are you seeing this still?

**Comment by davidanthoff** [comment]
I think I saw this still a few weeks ago on my laptop. I'm using ConEmu these days, and I didn't see it there, but I would assume it is still present from the normal Windows PowerShell window.

**Comment by musm** [comment]
Oh yeah I'm seeing this too now I think. even on a non hdpi screen it messes up the terminal by making everything bold

**Comment by davidanthoff** [comment]
Hm, I've never seen the bold problem, maybe that is another issue?

**Comment by musm** [comment]
![image](https://cloud.githubusercontent.com/assets/4319522/26018975/40a33784-3740-11e7-93dd-153b3ab3930e.png)

Looks good
then typing in `run(`powershell -h`)`

things get messed up

![image](https://cloud.githubusercontent.com/assets/4319522/26018989/4c5d0758-3740-11e7-8d0b-a30a4f27a8b2.png)

**Comment by KristofferC** [comment]
Unlikely to be a Juila issue.

Reminds me of https://github.com/JuliaLang/Pkg.jl/issues/641 which is fixed in Windows, so maybe this one also is.
