### ISSUE TITLE
BigInt: Cannot write to an IO or base64-encoded

### ISSUE THREAD

**Issue by H-225** [JuliaLang/julia#14274]
Unless I am missing something, `BigInt`s cannot be sent over an `IO`; they get serialized as sixteen bytes regardless of its value.

```julia
N = big(1) * big(10)^25000 # VERY big number!

@assert N |> string |> length == 25001 # true

b = IOBuffer()
write(b, N)

#=
At this point the IOBuffer contains 16 bytes:
julia> b.data
16-element Array{UInt8,1}:
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00
 0x00

=#

# Obviously, from this point, none of this will work as intended.

seekstart(b)
N2 = read(b, BigInt)

@assert N == N2 # nowhere near correct; N2 is zero!
```

**Comment by vtjnash** [comment]
it looks like it is trying to write out the integer with `sizeof(x)` bytes, and BigInt doesn't implement that method (https://github.com/JuliaLang/julia/blob/071390affb0000dfdbcf5837a7814dfd2571ecf6/base/io.jl#L71)

note that in general, is is not expected that you can read/write an arbitrary value and get the same thing back. serialize/deserialize however are expected to be able to do this (and do in fact return the correct value here).

**Comment by JeffBezanson** [comment]
We should try to fix this somehow. Until then, you should be able to work around it by using `print` instead.

**Comment by Keno** [comment]
What would you expect it to do? Just write however many binary bytes happen to represent it?

**Comment by JeffBezanson** [comment]
True, there is no canonical binary representation here, especially for negative numbers! I guess we could throw an error.

**Comment by H-225** [comment]
@vtjnash That seems odd. If I am able to write the object to a stream, then doesn't it imply that it was written losslessly? I was expecting a `MethodError`--or at least __some__ error--if it was not supported.

@JeffBezanson Out of interest, what is the reason for it not being a thing?

**Comment by Keno** [comment]
BigInts can arbitrarily large, so there is no fixed number of bytes you need to write. You could pick a variable size binary representation and write that, but that tends to not be particularly useful, because the receiving side generally has no way to tell where the BigInt ends.

**Comment by H-225** [comment]
@Keno Wouldn't something like this work fine?

```julia
sizeof(n::BigInt) = n.size * 8

function Base.write(io::IO, n::BigInt)
    sz = sizeof(n)
    data = pointer_to_array(Ptr{UInt8}(n.d), sz)
    written = 0
    written += write(io, sz)
    written += write(io, data)
    return written
end

function Base.read(io::IO, ::Type{BigInt})
    N = BigInt()
    sz = read(io, Int32)
    data = read(io, UInt8, sz)
    N.d = Ptr{UInt64}(pointer(data))
    N.size = sz
    return N
end
```
... assuming that the `alloc` field of `BigInt` need not be sent, which in my tinkering, that assumption appears correct.

**Comment by Keno** [comment]
That's a fine serialization format, but `read` and `write` are not serialization functions, but rather intended to read/write the canonical binary representation. As such I think the best thing to do is throw an error.

**Comment by Keno** [comment]
Just to strengthen the point and for general information, there other other big-integer serialization formats such as [LEB128](https://en.wikipedia.org/wiki/LEB128).

**Comment by H-225** [comment]
@Keno Hmmm... Isn't serialization of some form implied though, since it isn't a `BitsType`?
I mean, you'd be writing `write(serialize(n))` every time.
Also, `serialize` has that thing about it [potentially] changing between versions, which you may not want to rely upon.

I understand your sentiment though; `read`/`write` for manipulating `UInt8`s.
I'm not certain that it is beneficial to enforce it here though.

**Comment by Keno** [comment]
Not necessarily, some types imply their representation, e.g. a UTF8String, or arrays of bits types, etc. For things that have a canonical binary representation that's fine, everything else is dangerous.

**Comment by H-225** [comment]
@Keno Hmmm... I take your point.
