### ISSUE TITLE
open(`cmd`) not on stdlib documentation [v0.4]

### ISSUE THREAD

**Issue by mbaz** [JuliaLang/julia#14286]
It is mentioned in http://docs.julialang.org/en/release-0.4/manual/running-external-programs/ that one can `open` a command. However, such use is not documented in the stdlib section on I/O and networking at http://docs.julialang.org/en/release-0.4/stdlib/io-network/#Base.open.

**Comment by mbaz** [comment]
I just found the `open(command)` docs in Essentials. Should't all variations of a command be in a single place?

**Comment by nalimilan** [comment]
I may have missed it when reorganizing these sections. Would you make a pull request to fix this? The relevant files are doc/stdlib/base.rst and doc/stdlib/io-network.rst.

**Comment by mbaz** [comment]
@nalimilan I'm unclear about what to do. Right now, in the stdlib section of the docs, different versions of `open` are documented in "Essentials" and in"I/O and Networking". Should I copy (or move) the text in Essentials into "I/O and Networking"?

**Comment by nalimilan** [comment]
Yes, cut and paste should be fine.
