### ISSUE TITLE
Speed up integer division

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14287]
Integer division needs to check for the `div(typemin(Int), -1)` case to detect overflow. I see that the current implementation first checks for equality to `typemin(Int)`, and then to equality to `-1`. Since comparing to `-1` is cheaper, and since the comparison will fail most of the time, things could likely be sped up slightly by comparing to `-1` first.

This is the currently generated code:

```
julia> @code_native div(1, 1)
    .section    __TEXT,__text,regular,pure_instructions
    pushq   %rbp
    movq    %rsp, %rbp
    cmpq    $0, %rsi
    je  L41
    movabsq $-9223372036854775808, %rax ## imm = 0x8000000000000000
    cmpq    %rax, %rdi
    jne L31
    cmpq    $-1, %rsi
    je  L41
L31:
    movq    %rdi, %rax
    cqto
    idivq   %rsi
    popq    %rbp
    retq
L41:
    movabsq $jl_diverror_exception, %rax
    movq    (%rax), %rdi
    movabsq $jl_throw, %rax
    callq   *%rax
```

**Comment by yuyichao** [comment]
I'm not sure if there's anything we can do here. We generate `(b == -1 | a == typemin(Int)) & b == 0` for `div(a, b)` to LLVM without any branches. I also doubt there will be any noticable performance difference.

```julia
julia> @code_llvm div(1, 1)

define i64 @julia_div_22636(i64, i64) #0 {
top:
  %2 = icmp ne i64 %0, -9223372036854775808
  %3 = icmp ne i64 %1, -1
  %4 = or i1 %2, %3
  %5 = icmp ne i64 %1, 0
  %6 = and i1 %5, %4
  br i1 %6, label %pass, label %fail

fail:                                             ; preds = %top
  %7 = load %jl_value_t*, %jl_value_t** @jl_diverror_exception, align 8
  call void @jl_throw(%jl_value_t* %7)
  unreachable

pass:                                             ; preds = %top
  %8 = sdiv i64 %0, %1
  ret i64 %8
}
```

**Comment by stevengj** [comment]
Why do we check for overflow at all on `/` when we don't check on `*` or `+`?

**Comment by vtjnash** [comment]
I would phrase that question in reverse :P, but the answer is that we are actually really checking for undefined behavior in the llvm intrinsics, not overflow.

**Comment by eschnett** [comment]
I'm currently working on both `unchecked_div` and `checked_div` functions #14279. This will make it easy to switch `div` to whatever people prefer.

**Comment by JeffBezanson** [comment]
Dup of #8188

**Comment by KristofferC** [comment]
Closing as dup of #8188.
