### ISSUE TITLE
segfault in unwind

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#14284]
Ref https://github.com/JuliaOpt/Gurobi.jl/issues/47:

@Keno commented:

> The unwinder can touch invalid memory if it encounters incorrect unwind info. On some platforms we detect this and simply reset. Is this on OS X? I thought we did that there too.
> 
> Ok, taking a look at the code, we only do this while profiling, since that's when we're most likely to encounter incorrect unwind info. We may be able to extend the same to regular unwinding as well.

**Comment by mlubin** [comment]
Bump

**Comment by mlubin** [comment]
Bump again

**Comment by StefanKarpinski** [comment]
Bump the third. @Keno, can you write something brief here?

**Comment by Keno** [comment]
I've actually changed my mind on this a little bit and think that rather than papering over it, we should fix the unwind info that's broken. Of course in this case, it's in a commercial library, so perhaps not to easy to fix. I guess it's still fine to expand the profiler hack to regular unwind as well.

**Comment by mlubin** [comment]
I withdraw my bump, we've worked around this issue in JuMP by avoiding throwing exceptions for signaling when inside a Julia callback called from C code.

**Comment by ViralBShah** [comment]
Is there something we need to do here (and hence leave this open) or is it something that Gurobi needs to do (and hence we can close)?

**Comment by yuyichao** [comment]
There's nothing related to any julia package here. See the first comment, it's a low level issue.
