### ISSUE TITLE
writedlm(), leading zeros and float portability

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14291]
`writedlm()` currently skips leading zeros when writing floats. For example, `0.5` is written as `.5`. This appears to confuse some programs, which interpret the column as strings by default. For maximal portability, I think it would make sense to always write these zeros, even if it takes a bit more space (anyway, the CSV format is highly inefficient in that regard).

This problem was reported about IDL:
https://groups.google.com/d/msg/julia-users/m23ybvKt6-4/rZrDOfZdAAAJ

Implementation-wise, this could be done by modifying `writedlm_cell()`, which currently calls `print_shortest()`. `print_shortest()` already accepts a `dot::Bool = false` argument to force printing an ending dot even for integer-valued floats. It would make sense to add a `zero::Bool = false` argument, which when `true` would force the addition of a zero before leading dots, and after trailing dots (when `dot=true`). `writedlm_cell()` would then pass `dot=false, zero=true`.

**Comment by StefanKarpinski** [comment]
Printing the leading zeros seems like a good idea.

**Comment by sarvjeetsinghghotra** [comment]
I would like to take this bug

**Comment by tkelman** [comment]
@sarvjeetsinghghotra sure, if you can come up with a pull request over the next few weeks or so, go ahead! Be sure to include new tests for any changes. Let us know if you need any guidance.

**Comment by sarvjeetsinghghotra** [comment]
Made a pull request for comments: https://github.com/JuliaLang/julia/pull/14377

**Comment by jakebolewski** [comment]
closed by #14377
