### ISSUE TITLE
Should integer conversions with out-of-range values throw `OverflowError` instead of `InexactError`?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14308]
I see this:

``` Julia
julia> Int(-big(typemin(Int)))
ERROR: InexactError()
```

This doesn't quite make sense since all values involved are exact, and integers can't hold any "rounded" values. I think this should be an `OverflowError` instead.

**Comment by StefanKarpinski** [comment]
It's not an overflow though – it's a large number that can't be converted exactly.

**Comment by JeffBezanson** [comment]
I agree with Stefan here.

**Comment by eschnett** [comment]
I don't understand these definitions of "inexact" and "overflow". For me, "inexact" evokes the notion of rounding, and "overflow" the notion of "out of range". Where do you draw the distinction?

**Comment by JeffBezanson** [comment]
I think our notion of "overflow" refers to the result of an arithmetic operation, and "inexact" refers to a conversion that loses information. I believe we are consistent about this.

**Comment by ScottPJones** [comment]
I agree that Julia is consistent on it's use of overflow vs. inexact, however I do think people used to the IEEE meanings will continue to get confused. (for IEEE, inexact indicates any of overflow, underflow, or rounding, and overflow is when the result won't fit in the result type)

**Comment by KristofferC** [comment]
The previous discussion indicates this is a desired distinction between `OverFlow` and `InexactError`.
