### ISSUE TITLE
Julia shell mode tab completion should mirror terminal tab completion?

### ISSUE THREAD

**Issue by LordZorgoth** [JuliaLang/julia#14306]
I could be wrong, but it seems odd to me that Julia implements its own, not very smart, system for tab completion in shell mode when there is already an excellent smart bash completion system (optionally) used by the terminal.

Comparing behavior of Julia tab completion in shell mode/nightly build on my Ubuntu machine to tab completion in the terminal, there are numerous basic functionality issues. For some examples:

**cd <Tab> <Tab>** yields all directories _and files_ on Julia. In the terminal, it yields only directories.

**python <Tab> <Tab>** yields all directories and _all files_ on Julia. In the terminal, it yields only directories and files with the _.py_ extension.

**apt-get <Tab> <Tab>** yields all directories and files on Julia. In the terminal, it yields only apt-get commands.

All of these issues could be fixed individually, but fixing every issue with Julia's tab-completion in shell mode seems like it would be a lot of work that has already been done.

I would suggest that when using a bash shell, Julia simply request completions in the same way that the terminal does rather than implementing its own tab completion system for shell mode, or that if for some reason that is undesirable, its tab completion follows the same hints that bash smart completion does.

**Comment by StefanKarpinski** [comment]
Does bash have an API that lets you query if for completions? It seems like it might be a bit confusing if you don't use bash but get completions from bash.

**Comment by yuyichao** [comment]
Bash has [completion builtins](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html) but it requires shelling out to bash and parse it's output to get the results.

**Comment by jakebolewski** [comment]
This seems like something a package should provide.   A package could override the default shell mode key `;` and then hook into completions for `Bash`, `Zsh`, etc.

**Comment by LordZorgoth** [comment]
A package sounds like a perfectly acceptable solution for what is a fairly specialized problem -- cd and python seem like plausible use cases where some kind of fix should be made, but there's only a small number of commands that are going to see heavy use in shell mode, and those particular functions should eventually be fixed on all platforms.

Looking at yuyichao's link and the contents of the /usr/share/bash_completion folder, it certainly doesn't seem practical to do anything other than parse the output of the bash completion scripts if you want full bash smart completion (there is one for each of many commands).

Wrt the first comment, certainly you wouldn't want bash completions if you aren't using a bash shell. But I presume that one can test for what the shell is, and further that bash is used by a large percentage of Julia's user base (which may justify putting in effort to make sure that it plays nice).

I can't personally commit to learning how to make a package within the next year (got to make sure I get my PhD first!), but I'd be willing to put up a bounty for it if someone is interested in making one as it would be very useful to me due to the particular way I'm used to working. I'll probably post one sometime this week.

**Comment by tkelman** [comment]
Bounties have generally not been very effective or even remotely close to the actual value of engineering time. Start with Pkg.generate (PkgDev.generate on 0.5) to create a template, and send any questions to the mailing list, you should be able to get up to speed with making a package pretty quickly. It's just writing julia code with a particular main module folder structure.

**Comment by vtjnash** [comment]
Probably better suited for a package (e.g. OhMyRepl)
