### ISSUE TITLE
copy and transpose fail on triangular views

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#14317]
`tranpose` and `ctranspose` fail on triangular views:

```julia
mat = rand(10, 10)
view = sub(mat, 1:5, 1:5)
ltview = LowerTriangular(view)
utview = UpperTriangular(view)
ultview = Base.LinAlg.UnitLowerTriangular(view)
uutview = Base.LinAlg.UnitUpperTriangular(view)

transpose(ltview); transpose(ultview)
transpose(utview); transpose(uutview)
ctranspose(ltview); ctranspose(ultview)
ctranspose(utview); ctranspose(uutview)
```
The latter calls all return the same error:
```julia
ERROR: MethodError: `convert` has no method matching convert(::Type{SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}}, ::Array{Float64,2})
This may have arisen from a call to the constructor SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},1}(...),
since type constructors fall back to convert methods.
```
Explanation: These calls dispatch to f4c8c02b0f52356daa5ca56d8b96114b90b380ab/base/linalg/triangular.jl#L260-L267, archetypically:
```julia
transpose{T,S}(A::LowerTriangular{T,S}) = UpperTriangular{T, S}(transpose(A.data))
```
In the cases above `A.data` is a `SubArray` and `S` the specific `SubArray` type. `transpose(A.data)` works, but it returns an `Array` to `UpperTriangular{T,S}(...)`. `UpperTriangular{T,S}(...)` attempts to convert the `Array` it received to `SubArray` type `S` via `convert` prior to wrapping it in `UpperTriangular`. `convert` seems to lack methods for converting `Array` to `SubArray`, hence the error above.

This issue could be resolved by 
  1. adding appropriate methods to `convert`, as below; 
  2. patching up `transpose` for `SubArrays` such that it returns a trivially `SubArray`-wrapped `Array` instead of a plain `Array`, thereby avoiding surprising easily-spooked callers; or 
  3. patching up `transpose` for `XTriangular` objects such that if the `XTriangular`-wrapped object is a `SubArray`, it manages gracefully.

(1) seems satisfying, whereas (2) and (3) leave something to be desired. One could implement (1) via:
    1. 1 simply returning the `Array`;
    1. 2 checking the `Array` and `SubArray` types are compatible, followed by returning the `Array`; or
    1. 3 checking the `Array` and `SubArray` types are compatible, followed by returning the `Array` trivially wrapped in the specific `SubArray` type.

Or perhaps something else? I wouldn't be surprised to learn that converting `Array` to a trivially `SubArray`-wrapped `Array` is scary somehow. Thoughts? Best!

Edit: Minor clarifications.

**Comment by kshyatt** [comment]
Hi @Sacha0, thanks a lot for the bug report! I edited your OP to make it a little easier to read - I hope that's ok.

**Comment by Sacha0** [comment]
The edited lists look much better, thanks Katharine!

**Comment by andreasnoack** [comment]
Thanks again for a detailed bug report. It is likely that quite a few linear algebra methods have some rough edges with subarrays. We don't test systematically with subarrays yet.

I think the best solution is to return `XTriangular{T,Matrix{T}}`. When `transpose` forces you to copy the array, I think you'd be better off without the `SubArray` wrapper around your array. So something like
```jl
function transpose{T,S}(A::LowerTriangular{T,S})
    At = transpose(A.data)
    return UpperTriangular{T,typeof(At)}(At)
end
```

**Comment by andreasnoack** [comment]
or maybe simply `transpose(A::LowerTriangular) = UpperTriangular(transpose(A))` and let the constructor do the job. I don't see why the parameters are necessary here.

**Comment by tkelman** [comment]
If we ever do a lazy transpose, then it can compose with SubArray in interesting ways. For now since transpose is eager and copying, it can't really easily preserve view-ness of its inputs.

**Comment by Sacha0** [comment]
`copy` fails identically. Try
```julia
mat = rand(10, 10)
view = sub(mat, 1:5, 1:5)
ltview = LowerTriangular(view)
utview = UpperTriangular(view)
ultview = Base.LinAlg.UnitLowerTriangular(view)
uutview = Base.LinAlg.UnitUpperTriangular(view)

copy(ltview); copy(ultview)
copy(utview); copy(uutview)
```

**Comment by andreasnoack** [comment]
Yes. I've started running the tests with `SubMatrix` and just found the same. The fix is the same. Now that I've started on this, I'll probably prepare a PR soon.

**Comment by Sacha0** [comment]
No need, I have one almost complete :).

**Comment by andreasnoack** [comment]
Sounds great.
