### ISSUE TITLE
`@fastmath` prevents accessing fields called `min` or `max`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14318]
This is an example of what is going wrong:
```Julia
type T min::Float64 end
x=T(1)

julia> x.min
1.0

julia> @fastmath x.min
ERROR: TypeError: getfield: expected Symbol, got Expr
```

The `@fastmath` macro replaces the symbol `min` by `fast_min` in the expression. This makes the field `min` inaccessible, as Julia now tries to access something like `x.fast_min`.

The best short-term solution is probably to not perform this replacement in `getfield` and `setfield` calls.

A better solution would be to temporarily (i.e. lexically scoped) search a module `FastMath` before `Base` while resolving function names. Is this possible?

**Comment by JeffBezanson** [comment]
The macro should ignore anything inside `quote` expressions.

**Comment by eschnett** [comment]
The code in `FastMath` only handles `Symbol` and `Expr`; `QuoteNode` should be passed through without changes.

However, I don't understand exactly what is going on:
```Julia
julia> macroexpand(parse("x.min"))
:(x.min)
julia> macroexpand(parse("@fastmath x.min"))
:(x.($(Expr(:copyast, :($(QuoteNode(:(Base.FastMath.min_fast))))))))
```

What is a `copyast`? Who introduces it?

**Comment by JeffBezanson** [comment]
That's introduced by lowering. It's a feature of the low-level IR that greatly speeds up `quote` expressions by copying existing structure, instead of generating code to build a new AST bit-by-bit.

Inside a macro, quoted expressions are `Expr` objects with head `:quote`.
