### ISSUE TITLE
Travis doesn't cancel outdated builds

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14316]
Since a few days ago, Travis doesn't seem to cancel outdated build requests any more. For example, PR #14276 has currently three builds in the queue -- 31888, 31887, 31886. It also seems to be as if Travis ran these oldest-to-newest, without cancelling or aborting older ones when new ones arrive.

**Comment by jakebolewski** [comment]
@tkelman is this due to using a Docker image?

**Comment by yuyichao** [comment]
I don't think that's the case. See https://travis-ci.org/JuliaLang/julia/jobs/95424888 for example for a canceled build. Travis never cancel your build automatically AFAIK (unless there's some settings for that) and we always (since a few month ago) check for new build ourselves.

**Comment by tkelman** [comment]
No. Travis never cancels a build automatically. Superceded builds in branches and PRs have to start and run my script https://github.com/JuliaLang/julia/blob/master/contrib/travis_fastfail.sh to fail quickly. If you see a pending build turn gray and be actually cancelled before it starts, that was a human clicking cancel.
