### ISSUE TITLE
Simple Expr produces segfault

### ISSUE THREAD

**Issue by jmert** [JuliaLang/julia#14323]
While trying to create a complicated macro, I managed to consistently generate segfaults. After a bit of work, I've simplified the error expression all of the way down to

```julia
eval(Expr(:body, :(1)))
```

(where the `:(1)` is arbitrary—I think it's really trying to evaluate a body expression which is the problem) using Julia compiled from [tarball] source with version information

```
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

The backtrace is attached.
[julia_segfault_simple_bt.txt](https://github.com/JuliaLang/julia/files/55793/julia_segfault_simple_bt.txt)

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/13847#issuecomment-152910768 We are not particularly robust against malformed expressions....
