### ISSUE TITLE
Feature request: Pkg.status for abnormal statuses only

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#14320]
When debugging a package dependency problem on an installation with many packages, it can get cumbersome to wade through hundreds of package statuses to find only the packages that are dirty, checked out, pinned, or otherwise not at the most recent tagged release version.

It would be very helpful to be able to issue, say, `Pkg.status(normal=false)`, and return only the list of packages with abnormal statuses.

**Comment by tkelman** [comment]
agreed this would be useful

**Comment by eschnett** [comment]
If `Pkg.status()` returned an array instead of writing to stdout, then running `filter` on the result would be easy.

**Comment by tkelman** [comment]
you can already output to an iobuffer, but maybe defining a special type for the output of status, where what we have now is the show definition, but it would be an easier data structure to do things with.

**Comment by jiahao** [comment]
Right now I'm using `filter(x->x[2].build != (), collect(Pkg.installed()))` to get the list of packages with abnormal version numbers programmatically. Needless to say, it's rather ugly.

**Comment by KristofferC** [comment]
Issue moved to [JuliaLang/Pkg.jl #686](https://github.com/JuliaLang/Pkg.jl/issues/686) via [**ZenHub**](https://www.zenhub.com/)
