### ISSUE TITLE
Julia Windows binaries distributed as a .zip

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#14322]
At the moment, building Juno bundles requires a Windows VM to download the Windows installer and unzip it using 7zip. Being able to download and unzip Windows binaries directly would help to make the whole process more automated.

**Comment by ihnorton** [comment]
https://github.com/JuliaLang/julia/issues/10126#issuecomment-74811316

**Comment by tkelman** [comment]
Use p7zip to extract them.

**Comment by one-more-minute** [comment]
I've tried 7zip on OS X but it results in three folders being created, each with no name. The files are there but I can't access them from a script. I'll see if I can workaround but I still think the .zip would be useful.

**Comment by tkelman** [comment]
The extracted names are a little odd and need some extra escaping, that's NSIS' fault and I'd rather not use anything different right now. The same buildbot code currently creates both nightlies and releases and it would be an enormous waste of s3 space (with the consequence that we can't store nightlies back as far, which is a big impediment to debugging issues) to save a zip of every nightly.

**Comment by ihnorton** [comment]
Depending on the nsis version on the buildbots, we could try adding
`Unicode true` to the nsi script (
http://stackoverflow.com/questions/21433635/nsis-reading-an-unicode-file-name-issue
)

**Comment by tkelman** [comment]
We download nsis in `make win-extras`.
Newer versions or tweaks to the script are fine if it doesn't break anything.
