### ISSUE TITLE
Rename super() to supertype()

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14337]
There's currently a naming inconsistency between `subtypes()` and `super()`. How about renaming the latter to `supertype()`. That would make it more explicit and easier to find.

**Comment by jakebolewski** [comment]
:+1:

**Comment by tkelman** [comment]
+1

**Comment by simonbyrne** [comment]
+1

**Comment by nalimilan** [comment]
I didn't expect such a support. ;-) See PR https://github.com/JuliaLang/julia/pull/14338.

**Comment by J-Sarnoff** [comment]
+1

**Comment by ScottPJones** [comment]
More support here, for what it's worth!
