### ISSUE TITLE
Inference substitutes `Any` for `MethodError`

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#14336]
As reported in #14335:

``` jl
julia> function foo(A::VecOrMat)
           if size(A,1) == 2 && size(A,2) == 2
               return bar(A)
           end
           sum(A)
       end
foo (generic function with 1 method)

julia> bar(A::Matrix) = sum(A)
bar (generic function with 1 method)

julia> using Base.Test

julia> @inferred(foo([1,2]))
ERROR: return type Int64 does not match inferred return type Any
 in error at ./error.jl:21
```

It seems that it could be `Union{}`, as with other errors, and not destroy inference for the rest of the function.

**Comment by andreasnoack** [comment]
I think I was wondering about the exact same issue here https://groups.google.com/forum/#!topic/julia-dev/OWImSfq-cuM

**Comment by JeffBezanson** [comment]
Yes, `Union{}` is more precise but we've found returning this to be unsafe, probably because of #265. Returning Any avoids problems when the needed methods are added later.

**Comment by timholy** [comment]
OK, so should I close this and merge #14335?

**Comment by kshyatt** [comment]
This is still happening on master.

**Comment by vtjnash** [comment]
fixed by https://github.com/JuliaLang/julia/pull/21892
