### ISSUE TITLE
`f{T<:Union{}}(x::T,y::T)` method matched by `f(x, x)` ∀ x

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14339]
I find this (both Julia 0.4 and master):
```
typealias UnsignedInt Union{UInt8,UInt16,UInt32,UInt64,UInt128}
f{T<:UnsignedInt}(x::T,y::T) = 1
f{T<:Union{}}(x::T,y::T) = 0
f(UInt(1), UInt(2))
0
```
Apparently, `UInt` is treated as subtype of `Union{}`.

Of course, a direct inquiry is fine:
```
UInt <: Union{}
false
```

**Comment by vtjnash** [comment]
the method match is technically correct, although unintentional (and should be fixable), since `Union{}` is a subtype of all types it is a stricter match:
```
julia> Union{} <: Int
true
```

**Comment by nalimilan** [comment]
But isn't the revelant test `UInt <: Union{}` rather than `Union{} <: UInt`?

**Comment by eschnett** [comment]
@vtjnash The type I'm passing is `UInt8`, so I need a function that can handle `UInt8`, not just a subset of this type (namely `Union{}`). Yes, it's a stricter match, but it's too strict.

A work-around is to define an unused dummy type, and to use this type instead of `Union{}`.

**Comment by StefanKarpinski** [comment]
In terms of specificity the `Union{}` method is more specific. The part that seems wrong is that there is no `T <: Union{}` sugh that `UInt(1) :: T` and `UInt(2) :: T` so the method should match.

**Comment by JeffBezanson** [comment]
Yeah this is wrong. `T<:Union{}` should not match any values.
