### ISSUE TITLE
Windows Installation looking for libs in wrong place

### ISSUE THREAD

**Issue by sarvex** [JuliaLang/julia#14332]
I installed the latest Julia 0.4.2 using the Windows 64 bit installer from https://s3.amazonaws.com/julialang/bin/winnt/x64/0.4/julia-0.4.2-win64.exe. Julia was installed to C:\Program Files\Julia\Julia-0.4.2

After the vanilla install Julia failed to run. The Desktop Icon would open the terminal and close it. Running julia from command line gave the error for sys.dll. which was present in C:\Program Files\Julia\Julia-0.4.2\lib\julia but the executable was looking it in C:\Program Files\Julia\lib\julia

I have to copy the lib directory from the installation directory to the parent directory in order to run julia

**Comment by tkelman** [comment]
Did you manually set an environment variable `JULIA_HOME` ?

**Comment by H-225** [comment]
+1

I too have experienced a similar, though different problem.
With `JULIA_HOME` __not__ set, packages installed via `Pkg.add` or `Pkg.clone` do not find their libraries correctly.
For reference, adding the following code to `~/.juliarc.jl` fixes the problem.
```julia
for pkg in Pkg.installed()
        pkgname = pkg[1]
        try
                let directory = Pkg.dir(pkgname)
                        push!( Libdl.DL_LOAD_PATH, joinpath( directory, "deps/usr/lib" ) )
                end
        catch e
                error("Error while adding DL load path for package '$pkgname'")
                rethrow(e)
        end
end
```
Presumably a problem with `BinDeps`? _RFC._

**Comment by tkelman** [comment]
Shared libraries on Windows should build to /bin, not /lib.

**Comment by H-225** [comment]
@tkelman 
`Libdl.find_library` does not appear to locate DLLs that are under `<package>/deps/usr/bin` on my Windows machine.

**Comment by H-225** [comment]
@tkelman Done a little more digging.
It also seems that when installing packages in a Cygwin environment, they cannot run basic commands, such as `7z`, despite having `p7zip` installed.

**Comment by tkelman** [comment]
Check how existing packages use BinDeps, they create a deps/deps.jl file that you need to include with the absolute library paths.

Julia is not a Cygwin application. It can be cross compiled from cygwin but that is only as a build environment.

Your issues are not the same as what @sarvex reported. Report them to individual packages, or ask for guidance on setting up bindeps on the mailing list.

**Comment by sarvex** [comment]
@tkelman Thanks for the information and yes I had JULIA_HOME variable set which was causing the problem. I tried installation on another machine and it works fine
