### ISSUE TITLE
Arguments captured in curried functions need to be defined @everywhere

### ISSUE THREAD

**Issue by jnkh** [JuliaLang/julia#14344]
When running a curried function remotely, all additional arguments to that function currently need to be defined ```@everywhere``` in order for this to work. It seems like only the function definition itself should have to be defined everywhere, but not the variables captured in the currying operation. Here is a minimal example:

```julia
addprocs(2)

#no @everywhere required
Nlist = repmat([1000],10)

#define function to execute
#will not work without @everywhere
@everywhere myfun(N,M) = sum(randn(N,M)*randn(M,N)) 

#define some local variable
#will not work without @everywhere. This should not be necessary!
@everywhere M = 1000

#map over curried function: make sure all captured variables are defined @everywhere!
@time pmap(N -> myfun(N,M),Nlist)
```

**Comment by malmaud** [comment]
`M` is a global variable here. Global variable references are never captured by value, but instead remain references.
