### ISSUE TITLE
wrong sign of zero for (x+0im)^(negative real)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#14342]
With Julia 0.5, `(2.0+0im)^-2` correctly gives `0.25 - 0.0im`, but `(2.0+0im)^-2.1` gives `0.23325824788420185 + 0.0im`.  Notice that the sign of the imaginary part is incorrect, in that `(2.0+δ*im)^-2.1` should give a negative imaginary part as `δ ⟶ 0⁺`.

cc: @jiahao

**Comment by jiahao** [comment]
Related to #10000?

**Comment by stevengj** [comment]
@jiahao, I don't think so, because negative-integer powers work.

**Comment by jiahao** [comment]
Negative integer powers use a different method. What gets called for `(2.0+0.0im)^-2` is 

`Base.power_by_squaring(inv(2.0+0.0im), +2)`

whereas `(2.0+0.0im)^-2.1` calls `exp((-2.1+0.0im)*log(2.0+0.0im))`.

The problem appears to be the premature promotion of `(2.0+0.0im)^-2.1` to `(2.0+0.0im)^-(2.1+0.0im)`, as

```
julia> exp((-2.1+0.0im)log(2.0+0.0im))
0.23325824788420185 + 0.0im

julia> exp((-2.1)log(2.0+0.0im))
0.23325824788420185 - 0.0im
```

We can solve this by defining `^(z::Complex, w::Real)` as its own special method, but perhaps there is a cleverer solution.

**Comment by stevengj** [comment]
`^(z::Complex, w::Real)` should probably be its own method anyway, since I would be surprised if you couldn't compute this more efficiently than `Complex^Complex`.
