### ISSUE TITLE
segfault when using sparse cholesky factorization in parallel

### ISSUE THREAD

**Issue by thraen** [JuliaLang/julia#14355]
I encounter segfaults when trying to use sparse cholesky factorizations in parallel:

```
@everywhere const N=100000
@everywhere const T=1000

const L = speye(N, N)

const L_chol    = cholfact(L)

@show typeof(L_chol)

@everywhere function do_slice!(res, L, t)
    b = rand(N)
    res[:,T] = L\b
end

function do_par_chol()
    res = SharedArray(Float64, (N, T), init= S -> S[localindexes(S)] = 0.0) 
    @sync @parallel for t=1:T
        do_slice!(res, L_chol, t)
    end
end

@time do_par_chol()
```
output:

typeof(L_chol) = Base.SparseMatrix.CHOLMOD.Factor{Float64}

signal (11): Segmentation fault
size at sparse/cholmod.jl:1080
solve at sparse/cholmod.jl:743
do_slice! at fact_par_bug.jl:12
jlcall_do_slice!_21302 at  (unknown line)
jl_apply_generic at /julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at fact_par_bug.jl:18
anonymous at multi.jl:1353
jl_f_apply at /julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at multi.jl:904
run_work_thunk at multi.jl:645
run_work_thunk at multi.jl:654
jlcall_run_work_thunk_21209 at  (unknown line)
jl_apply_generic at /julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at task.jl:58
unknown function (ip: 0x7f1c1c0b6f1c)
unknown function (ip: (nil))
Worker 7 terminated.
ERROR: LoadError: ProcessExitedException()
 in yieldto at ./task.jl:71
 in wait at ./task.jl:371
 in wait at ./task.jl:286
 in wait at ./channels.jl:63
 in take! at ./channels.jl:53
 in take! at ./multi.jl:803
 in remotecall_fetch at multi.jl:729
 in remotecall_fetch at multi.jl:734
 in call_on_owner at multi.jl:777
 in wait at multi.jl:792
 in sync_end at ./task.jl:400
 [inlined code] from task.jl:422
 in do_par_chol at fact_par_bug.jl:16
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading fact_par_bug.jl, in expression starting on line 155
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)

versioninfo:
Julia Version 0.4.3-pre+4
Commit 926513f (2015-12-07 23:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7- 8837  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by KristofferC** [comment]
I thought Suitesparse was not thread safe?

**Comment by andreasnoack** [comment]
See #14149. The segfault has been fixed on master, but the fix hasn't been backported yet. However, it will only change the segfault into an error. You cannot more sparse Cholesky factorizations across workers.

**Comment by thraen** [comment]
Ah, I see. So this will probably work in the foreseeable future. Can I work around this by defining the cholfact everywhere and not move it around?

**Comment by andreasnoack** [comment]
> So this probably won't work in the foreseeable future.

No. I think it will require that we implement the sparse Cholesky in Julia. It would be a lot of work to match CHOLMOD.

> Can I work around this by defining the cholfact everywhere instead of moving it around?

Yes. That is how you should do this.

**Comment by thraen** [comment]
Thanks!

**Comment by tkelman** [comment]
Should we close this as fixed on master, or wait until 0.4.3 has the fix backported?

**Comment by andreasnoack** [comment]
I couple of people has hit this lately so let's keep it open for visibility until 0.4.3 is out.

**Comment by andreasnoack** [comment]
This is now backported
