### ISSUE TITLE
Julia and windows user names with ligature letters

### ISSUE THREAD

**Issue by hustf** [JuliaLang/julia#14357]
I have not seen this issue mentioned anywhere, although it has probably been around for all Julia versions.

Letters like æ, ø, å commonly appear in names. In my name, for one, they appear every single time.  This means I can't easily use Julia professionally, as I can't just establish a new user name at work. On personal computers, I have established 'Julia only' user names. There may be other workarounds, but those would not be apparent to other new Julia users.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

ERROR: SystemError: opening file C:\USERS\FRO\;\.julia_history: No such file or directory
 in open at iostream.jl:90
 in setup_interface at REPL.jl:746
 in run_frontend at REPL.jl:858
 in run_repl at REPL.jl:167
 in _start at client.jl:420

INFO: Disabling history file for this session.
julia>
```

If this is fixed within Julia, it may still be an issue when using Python packages?

**Comment by stevengj** [comment]
@hustf, what does `homedir()` return?  What are `ENV["HOME"]`, `ENV["HOMEDRIVE"]`, and `ENV["HOMEPATH"]`?

**Comment by stevengj** [comment]
Maybe we should be using [SHGetFolderPath](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762181.aspx) on Windows.

**Comment by ScottPJones** [comment]
Wouldn't you want the non deprecated function though?

**Comment by hustf** [comment]
````
julia> homedir()
"C:\\USERS\\FRO\\;"

**Comment by hustf** [comment]
Is this actually a Windows issue?

**Comment by hustf** [comment]
Oh, I missed these @stevengj 

julia> ENV["HOME"]
"C:\\USERS\\FRO\\;"

julia> ENV["HOMEDRIVE"]
"C:"

julia> ENV["HOMEPATH"]
"\\Users\\FrøRestofFirstName"

**Comment by stevengj** [comment]
So, it seems like we would be okay if we ignored `ENV["HOME"]`, but it seems like it would be better to call an API function for this.  See also #11331.

**Comment by stevengj** [comment]
Please try:
```jl
immutable GUID
    data1::UInt32
    data2::UInt16
    data3::UInt16
    data4_0::UInt8
    data4_1::UInt8
    data4_2::UInt8
    data4_3::UInt8
    data4_4::UInt8
    data4_5::UInt8
    data4_6::UInt8
    data4_7::UInt8
end
const FOLDERID_Profile = GUID(0x5e6c858f, 0x0e22, 0x4760,
                               0x9a, 0xfe, 0xea, 0x33, 0x17, 0xb6, 0x71, 0x73)
function whomedir()
    p = Ref{Ptr{Cwchar_t}}()
    ok = ccall((:SHGetKnownFolderPath,"shell32"), stdcall, UInt32, (Ref{GUID},UInt32,Ptr{Void},Ref{Ptr{Cwchar_t}}),
               FOLDERID_Profile, 0, C_NULL, p)
    ok != 0 && error("failure $ok calling SHGetKnownFolderPath")
    s = wstring(p[])
    ccall((:CoTaskMemFree,"ole32"), stdcall, Void, (Ptr{Cwchar_t},), p[])
    return bytestring(s)
end

whomedir()
```
This works on a Windows machine I tried, and lets us get the home directory without using `ENV`.

**Comment by vtjnash** [comment]
libuv also has that functionality in the next version http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_homedir

why do you have a HOME variable defined? that is likely to confuse posix-based programs like git and cygwin.

**Comment by hustf** [comment]
stevengj, confirmed:



  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

ERROR: SystemError: opening file C:\USERS\FRO\;\.julia_history: No such file or directory
 in open at iostream.jl:90
 in setup_interface at REPL.jl:746
 in run_frontend at REPL.jl:858
 in run_repl at REPL.jl:167
 in _start at client.jl:420

INFO: Disabling history file for this session.
julia> immutable GUID
           data1::UInt32
           data2::UInt16
           data3::UInt16
           data4_0::UInt8
           data4_1::UInt8
           data4_2::UInt8
           data4_3::UInt8
           data4_4::UInt8
           data4_5::UInt8
           data4_6::UInt8
           data4_7::UInt8
       end

julia> const FOLDERID_Profile = GUID(0x5e6c858f, 0x0e22, 0x4760,
julia> const FOLDERID_Profile = GUID(0x5e6c858f, 0x0e22, 0x4760,
                                      0x9a, 0xfe, 0xea, 0x33, 0x17, 0xb6, 0x71, 0x73)
GUID(0x5e6c858f,0x0e22,0x4760,0x9a,0xfe,0xea,0x33,0x17,0xb6,0x71,0x73)

julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
julia> function whomedir()
           p = Ref{Ptr{Cwchar_t}}()
           ok = ccall((:SHGetKnownFolderPath,"shell32"), stdcall, UInt32, (Ref{GUID},UInt32,Ptr{Void},Ref{Ptr{Cwchar_t}}),
                      FOLDERID_Profile, 0, C_NULL, p)
           ok != 0 && error("failure $ok calling SHGetKnownFolderPath")
           s = wstring(p[])
           ccall((:CoTaskMemFree,"ole32"), stdcall, Void, (Ptr{Cwchar_t},), p[])
           return bytestring(s)
       end
whomedir (generic function with 1 method)

julia>

julia> whomedir()
"C:\\Users\\Frøystein"

julia>

**Comment by stevengj** [comment]
@vtjnash, `uv_os_homedir` seems like the way to go if we are switching to the new libuv before long.

**Comment by hustf** [comment]
vtjnash, I have defined a PATH variable because I want to start Julia from the github command line. I may have a HOME variable because some other licensed software I'm using requires it. I don't know.

**Comment by tkelman** [comment]
@hustf can you try adding `pop!(ENV, "HOME")` to your `etc/julia/juliarc.jl`? Would have to check what order that gets loaded vs the REPL history file.

**Comment by hustf** [comment]
@tkelman - Julia starts with no error messages. And the history file is present on a second start-up.

It is nice to have several independent installations on one machine, so thank you for this! I will proceed to install Anaconda on this user.

**Comment by hustf** [comment]
Deleting this malformed HOME environment variable seems to solve everything. So this issue can be closed I guess. 

The HOME variable is not normally defined in Windows as far as I know, but it is defined by logon scripts at for example my workplace, where it is used by licensing software and for document checkouts. Perhaps using it on Windows system is not the most robust way for Julia.

**Comment by stevengj** [comment]
Arguably, we should close this issue by not preferentially looking at `HOME` on Windows.  This would be fixed by calling `uv_os_homedir`, it sounds like, or by adopting a similar algorithm.

**Comment by hustf** [comment]
Ok. The following is not a Julia issue, I guess, but I can't build IJulia; 
The error messages are quite extensive and I suppose this is not the place for it. 

===============================[ ERROR: IJulia ]================================
LoadError: UnicodeError: invalid character index
while loading C:\Users\FrøRestOfUserName\.julia\v0.4\IJulia\deps\build.jl, in expression starting on line 129

**Comment by stevengj** [comment]
@hustf, please file an IJulia issue.

**Comment by hustf** [comment]
stevengj, the 'IJulia issue' will be fixed when BinDeps is tagged. As per now, many or all Windows users must checkout BinDeps to make it and dependent packages work. 

https://github.com/JuliaLang/BinDeps.jl/pull/191
https://github.com/JuliaLang/BinDeps.jl/commit/a4841d98b2b2e5b9c74c5a829ae26cc055af1044

This calls for further improvements and may be the reason why the BinDeps fix is not tagged:
https://github.com/JuliaLang/julia/issues/14314

**Comment by tkelman** [comment]
I'll tag BinDeps anyway. There are some fixes still needed but it shouldn't hurt to tag more often.

**Comment by vtjnash** [comment]
seems there's no bug here

**Comment by stevengj** [comment]
@vtjnash, I don't think the original issue has been fixed.  (The IJulia business was an unrelated distraction.)   In particular, see #11331.

(Are we using a version of libuv that supplies `uv_os_homedir` yet?)

**Comment by stevengj** [comment]
Yup, we are using `julia-uv1.9.0` and this function I think appeared in libuv 1.6.

**Comment by hustf** [comment]
How should I test this, now? Which version?

**Comment by tkelman** [comment]
If you can try to reproduce the issue with the latest 0.5-dev nightly that would be useful, thanks!

**Comment by hustf** [comment]
Ok, will have to download it first. Any special PATH settings?

**Comment by stevengj** [comment]
@hustf, although even if we are linking a libuv with `uv_os_homedir`, we aren't calling it yet, so I don't think the issue will be fixed.

**Comment by stevengj** [comment]
In particular, our `homedir()` function on Windows [still preferentially uses the HOME environment variable](https://github.com/JuliaLang/julia/blob/3c60d3ebcf58a044b1a27283370186d8494af950/base/path.jl#L41).

**Comment by hustf** [comment]
```javascript
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4990 (2016-06-29 01:07 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 05f2e31* (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> ENV["HOME"]
"C:\\Users\\Æøå"

julia> homedir()
"C:\\Users\\Æøå"
```

I created a new user with administrative rights to do this. The HOME variable is set to %USERPROFILE%. Which is the reasonable value. 

Users without administrative rights can not have their own set of environment variables, but inherits system level environment variables. When setting the system level HOME to %USERPROFILE%, Windows in this case does not parse this variable correctly. Julia will then also create an error similar to that in the first post.

**Comment by vtjnash** [comment]
now uses `uv_os_homedir`

**Comment by tkelman** [comment]
originally reported issue should be tested for

**Comment by vtjnash** [comment]
Original issue was a user configuration error
