### ISSUE TITLE
precompile shouldn't try to overwrite stale read-only cache files

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#14368]
A lot of people are seeing failures on JuliaBox (JuliaLang/JuliaBox#338, stevengj/PyPlot.jl#185, JuliaLang/IJulia.jl#159) because JuliaBox ships precompiled cache files in a read-only directory `/opt/julia_packages/.julia/lib/v0.4/`.   If these cache files are stale, Julia tries to recompile them, but it begins by trying to delete the stale old cache file, which throws an exception, e.g.
```
julia> using Compat                                                                                                                                                
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/Compat.ji for module Compat.                                                                
ERROR: unlink: read-only file system (EROFS)                                                                                                                       
 in unlink at fs.jl:102                                                                                                                                            
 in rm at file.jl:59                                                                                                                                               
 in create_expr_cache at loading.jl:330                                                                                                                            
 in recompile_stale at loading.jl:461                                                                                                                              
 in _require_from_serialized at loading.jl:83                                                                                                                      
 in _require_from_serialized at ./loading.jl:109                                                                                                                   
 in require at ./loading.jl:219 
```

**Comment by stevengj** [comment]
This seems to have been worked around in #14145 by @eschnett.

**Comment by stevengj** [comment]
Probably the `recompile_stale` function should call `create_expr_cache(path, joinpath(Base.LOAD_CACHE_PATH[1], basename(cachefile)))` so that the new cache file is always created in the default location (the head of the path), not where the old cache file was found.

**Comment by tanmaykm** [comment]
Would it be better to just check for write permissions and skip updating the cache file if it is readonly? It seems to fall back to the default location in that case.

I tried with the following change in `loading.jl`.

````
function recompile_stale(mod, cachefile)
    if ((stat(cachefile).mode & 0o222) == 0)
        warn("could not remove stale cache file $cachefile")
        return
    end
...
end
````

**Comment by eschnett** [comment]
Checking file permissions isn't a reliable way to determine whether a file can be deleted. For example, in Unix you need write permissions to the directory, and on a network file system or with access control lists, it's up to the file server anyway. It is usually easier to just try to delete the file, and check the error condition afterwards.

**Comment by tanmaykm** [comment]
Ah yes. So, then may be a `try...catch`?

**Comment by stevengj** [comment]
Even if it is writable, I don't think we should be writing *new* cache files to arbitrary locations in the path.  I think it is better to always write new files to `Base.LOAD_CACHE_PATH[1]`, which will normally be in `~/.julia/lib`.

**Comment by tanmaykm** [comment]
Ok, yes that sounds reasonable.

**Comment by jonasaugust** [comment]
I'm also getting the "read-only file system" error when trying to add PyPlot to my JuliaBox instance with kernel 0.4.2.  Although this issue has been closed in December... I'm guessing it hasn't been installed to the JuliaBox server yet.  How/when does that happen, and how would we come to know it when it does?
(And, of course, thanks for all your work on Julia!)

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/14369 was backported to 0.4.3, so juliabox should just need an upgrade to that.

**Comment by jonasaugust** [comment]
@tkelman  Thanks for making it clearer.
