### ISSUE TITLE
Printf %g behaves strangely with 0 precision.

### ISSUE THREAD

**Issue by mason-bially** [JuliaLang/julia#14360]
Discovered during #14331.

Namely these cases.

```
julia> @sprintf("%#.0g", 42)
"4.200000e+01"
c-> "4.e+01"

julia> @sprintf("%.0g", 42)
"4.2e+01"
c-> "4e+01"

julia> @sprintf("%.0g", 42.3)
"4.23e+01"
c-> "4e+01"
```

I'll be happy to take it.

**Comment by dfannius** [comment]
Please do! I'll act as backstop if you don't get around to it.

**Comment by quinnj** [comment]
These cases are fixed in https://github.com/JuliaLang/julia/pull/32859
