### ISSUE TITLE
Virtual Memory Usage

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#14367]
Building Julia on a workstation in a computer lab at my university, I seem to be having trouble with virtual memory usage:

`julia -p 1`  works fine, but

`julia -p 2` gives the error:

```
could not allocate pools
Master process (id 1) could not connect within 60.0 seconds.
exiting.
```

If I change `REGION_PG_COUNT` to be 8*4096 for 64-bit architectures in src/gc.c and recompile Julia, then it works.  The machine has 16 gigs of memory, so I don't think physical memory is the issue.  I have not had this problem on my laptop, so it is something specific to the machines in the lab.

```julia
julia> versioninfo()
Julia Version 0.4.3-pre+6
Commit adffe19* (2015-12-11 00:38 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD Phenom(tm) II X6 1100T Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/10390
