### ISSUE TITLE
export `Base.LinAlg.chksquare`

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#14388]
Rationale: checking that a matrix is square is a pretty common operation. While `chksquare` is a minor utility function, it is well-designed, useful, and allows standard error reporting. Without a common function, libraries end up implementing their own solutions or explicitly spell out something like
```julia
n, m = size(A)
if n != m
    throw(ArgumentError("matrix is not square"))
```
or one of the countless variations. Standardizing this outside `Base.LinAlg` would be useful.

**Comment by andreasnoack** [comment]
I gree that it would be a useful function to expot, but I don't like the `chk` abbreviation though. Maybe rename to `checksquare`, write documentation and export in a PR would be the way to proceed.

**Comment by tpapp** [comment]
I will try submitting a PR, as I mean to learn the workflow anyway and such a minor change would be a good place to start.

**Comment by tkelman** [comment]
This could be used elsewhere without exporting it, just by qualifying it with the module name. I'd be in favor of renaming and documenting it, but not exporting such a trivial thing.

**Comment by KristofferC** [comment]
If the name is changed it should be deprecated even though it is a non exported function. It is likely used in many places out of Base.

**Comment by StefanKarpinski** [comment]
How about renaming it to `checksqr`? :trollface:

**Comment by tpapp** [comment]
How would I note in the documentation that it is not exported? Is there a convention, eg using the full form `Base.LinAlg.checksquare`?

**Comment by tkelman** [comment]
Or just `LinAlg.checksquare` since the LinAlg module is exported. That's the convention used for Profile and a few other places, yes.

**Comment by andreasnoack** [comment]
See e.g. https://github.com/JuliaLang/julia/blob/10e8b52f40a6ec42217b7c632920d9651b580528/base/linalg/qr.jl#L141-L162

**Comment by ScottPJones** [comment]
`LinAlg.checksquare` seems good to me. @tkelman is right about not wanting to export too much from Base.

**Comment by jiahao** [comment]
To clarify, `chksquare` does more than just check if the matrix is square. If it is square, it also returns the dimension of the matrix, which is an extremely common thing to do. Perhaps we can come up with a name that reflects its return value too.

**Comment by tpapp** [comment]
What about `checked_square_size`? A bit long, but reflects the fact that it returns a dimension, and the argument has been checked to be square.

**Comment by andreasnoack** [comment]
I think `checksquare` is fine if we document the behavior and give an example.

**Comment by StefanKarpinski** [comment]
+1 for `checksquare`.

**Comment by tpapp** [comment]
I just submitted PR https://github.com/JuliaLang/julia/pull/14601, which should close this. Thanks for all the help.
