### ISSUE TITLE
transpose fails on views of sparse matrices

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#14398]
``` julia
transpose(sub(speye(10), 1:5, 1:5))
```

returns a no-method error.

``` julia
transpose{Tv, Ti, N}(A::SubArray{Tv, N, SparseMatrixCSC{Tv, Ti}}) = transpose(copy(A))
```

could serve as a simple fallback till something better comes along? Better ideas? Thanks, and best!

**Comment by andreasnoack** [comment]
I think all linear algebra fails on views on sparse matrices. It will require a lot of index calculations to generally avoiding the copy.

**Comment by ViralBShah** [comment]
Perhaps we should explicitly disable views on sparse matrices?

**Comment by Sacha0** [comment]
Is that to say we should (1) fill in simple if suboptimal methods (such as that above) now and replace them with more efficient methods later; or (2) hold off with building anything for now?

**Comment by ViralBShah** [comment]
Sparse matrix views cannot be done efficiently in all cases, and we should probably only have those that we can do efficiently.

**Comment by tkelman** [comment]
If we're still planning on returning views from indexing, we're going to have to implement these.

**Comment by ViralBShah** [comment]
I was hoping we don't do it for the slow cases - like extracting rows, or perhaps retain the existing behaviour for sparse matrices.

**Comment by tkelman** [comment]
No, anywhere we start returning views from indexing into dense matrices, it's a bug if the same indexing operation on a sparse matrix returns a copy. Otherwise you're not really doing generic programming.

**Comment by jakebolewski** [comment]
Strongly agree with @tkelman here.

**Comment by ViralBShah** [comment]
I agree that some matrix types returning copies and others returning views would be inconsistent and bad. However, almost anyone's codes that do sparse matrix indexing will probably start seeing slowdowns with views on row indices.

**Comment by tkelman** [comment]
Indexing, especially row indexing, is already usually the wrong thing to do perfornance wise on sparse matrices. We should prefer doing the right but slow thing for the sake of generic code - we don't yet have a generic way to iterate over only nonzeros that would make generic *and fast* code work on both sparse and dense, but that's something I've got conceptual mockups of that I need to clean up and flesh out more.

**Comment by ViralBShah** [comment]
It is very common, and not slow, to extract a submatrix from a larger sparse matrix to work on, which is done conveniently as `S[p,q]`. I guess people will have to do `copy(S[p,q])` if the default is to have views?

**Comment by tkelman** [comment]
That is a relatively slow operation on SparseMatrixCSC if the row selection is anything other than `1:size(A,1)`. You have to traverse each column and check all the row indices otherwise.

A sparse view object has to do the same row index checking on getindex or setindex (or on construction?). If getindex starts returning views, we may need an explicit copy syntax to avoid the view creation, as the "old style" replacement for our current `sub`/`slice`.

**Comment by simonster** [comment]
Related to #13438

**Comment by KristofferC** [comment]
This now works:

```
julia> transpose(sub(speye(10), 1:5, 1:5))
5×5 sparse matrix with 5 Float64 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  1.0
  [3, 3]  =  1.0
  [4, 4]  =  1.0
  [5, 5]  =  1.0
```

**Comment by tkelman** [comment]
needs test
