### ISSUE TITLE
jl_eval_string() return type confusion

### ISSUE THREAD

**Issue by AlesTsurko** [JuliaLang/julia#14390]
Hi there!

I've found that in the ```julia.h``` the ```jl_eval_string()``` return type is ```void *``` (https://github.com/JuliaLang/julia/blob/master/src/julia.h#L1252)
That on this line:

```C
jl_value_t *ret = jl_eval_string("sqrt(2.0)");
```
*(from the Julia manual: http://docs.julialang.org/en/release-0.4/manual/embedding/#converting-types)*

causes the next error:

```
Cannot initialize a variable of type 'jl_value_t *' (aka '_jl_value_t *') with an rvalue of type 'void *'
```

I'm not sure if the return type should be ```jl_value_t *```, but If I'd use it as is:

```C
void *ret = jl_eval_string("sqrt(2.0)");
```

I can't use it next:

```C
double ret_unboxed = jl_unbox_float64(ret);
```

**Comment by yuyichao** [comment]
The signature has been like that since a long time ago https://github.com/JuliaLang/julia/commit/b9bc67e1a751d85b601bae042da266d9065a2147#diff-885908120835b66f90958a39baeb2018R640

We could probably change it to `jl_value_t*`. In the mean time, you can always cast it.

**Comment by yuyichao** [comment]
Also I think the manual assumes C and this conversion is only forbidden in C++.

**Comment by JeffBezanson** [comment]
That's strange. The return type should be changed to `jl_value_t*`.
