### ISSUE TITLE
Functions inside pmap call can't see SharedArrays unless preceded by @async

### ISSUE THREAD

**Issue by JohnHBrock** [JuliaLang/julia#14399]
I don't know if this is a feature or a bug. Functions used inside a `pmap` call can only see SharedArrays when the `pmap` call is preceded by `@async`. To replicate, be sure to start Julia with more than one process (e.g., `julia -p 2`):

``` jl
julia> foo = convert(SharedArray, [1,2,3,4]);

julia> @async pmap(i->println(foo), 1:2) 
Task (waiting) @0x000000010cd8f730 

julia> From worker 2: [1,2,3,4] 
       From worker 3: [1,2,3,4] 

julia> pmap(i->println(foo), 1:2) 
2-element Array{Any,1}: 
 RemoteException(2,CapturedException(UndefVarError(:foo),Any[(:anonymous,:none,1,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),907,symbol(""),-1,1),(:run_work_thunk,symbol("multi.jl"),645,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),907,symbol("task.jl"),63,1)])) 
 RemoteException(3,CapturedException(UndefVarError(:foo),Any[(:anonymous,:none,1,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),907,symbol(""),-1,1),(:run_work_thunk,symbol("multi.jl"),645,symbol(""),-1,1),(:anonymous,symbol("multi.jl"),907,symbol("task.jl"),63,1)]))
```

``` jl
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

I can also replicate this on Julia v0.3.9.

**Comment by amitmurthy** [comment]
`@async` localizes the variables which results in the shared array objects being local to the closure and hence serialized to the remote worker. This is another manifestation of the general scoping issue https://github.com/JuliaLang/julia/issues/13649

**Comment by amitmurthy** [comment]
Same as https://github.com/JuliaLang/julia/issues/13756

**Comment by amitmurthy** [comment]
Closed by #19594

**Comment by tkelman** [comment]
is there a test for this?

**Comment by amitmurthy** [comment]
This and the others you reported - https://github.com/JuliaLang/julia/blob/1303dfb96aa4345dca5d225e7ae72348307aef25/test/parallel_exec.jl#L1392-L1422

**Comment by amitmurthy** [comment]
Generally they were all manifestations of the same issue.
