### ISSUE TITLE
Vector computation results in scalar result unless repeated.

### ISSUE THREAD

**Issue by tobenkin** [JuliaLang/julia#14400]
Installed: 0.4.2-trusty2 on an amd64 machine.  

Running:
```
N = 2
centers = zeros(3, N)
normals = zeros(3, N)
function build_matrices(centers, normals)
  A = zeros(N, N)
  for i = 1:N
    for k = 1:N,
        V_ind = centers[:, 1] - centers[:, 1]
        # Uncommenting the next line causes the problem to go away.
        # V_ind = centers[:, 1] - centers[:, 1]
        A[k, i] = dot(normals[:, k], V_ind)
    end
  end
end
A = build_matrices(centers, normals)
```
Results in:

LoadError: MethodError: `dot` has no method matching dot(::Array{Float64,1}, ::Float64)
Closest candidates are:
  dot(!Matched::Number, ::Number)
  dot{T<:Union{Float32,Float64},TI<:Integer}(::Array{T<:Union{Float32,Float64},1}, !Matched::Union{Range{TI<:Integer},UnitRange{TI<:Integer}}, !Matched::Array{T<:Union{Float32,Float64},1}, !Matched::Union{Range{TI<:Integer},UnitRange{TI<:Integer}})
  dot(::AbstractArray{T,1}, !Matched::AbstractArray{T,1})
while loading In[30], in expression starting on line 14

 in build_matrices at In[30]:10

Unless the second line defining V_ind is uncommented.

**Comment by digital-carver** [comment]
Hi @tobenkin !  I'm a newbie to Julia myself, but I believe there's a small syntax error in the code that's causing this error. The second `for` loop has a comma at the end, and that's apparently causing Julia to parse those two lines weirdly, preventing it from seeing the assignment to `V_ind` correctly. 

Removing the comma there lets the code run properly, without a second repetition of the `V_ind` assignment line.

**Comment by nalimilan** [comment]
Thanks for spotting this @digital-carver. Indeed in Julia it is allowed to write `for i = 1:N, k = 1:M`.
