### ISSUE TITLE
Constant numeric expressions should preserve value over type

### ISSUE THREAD

**Issue by H-225** [JuliaLang/julia#14415]
Currently, with integer literals always being `Int64`s, it causes an issue with values that are larger than `Int64` can hold:

`N = 2^64` => `0` - obviously not what we want
`N = BigInt(2^64)` => `18446744073709551616` -  this would make more sense to me
`N = BigInt(2)^64` => `18446744073709551616` - the way it currently is

This can be an annoyance if you are writing things like `2^64-1`, for example.

While `big(2)^64` works, it's a bit clunky IMHO.

I am not personally much of a fan of the `big"..."` usage, since any number that I'd typically write down is--more often that not--quite small, but it is worth noting that you cannot write expressions with it and thus, one cannot use it here; `big"2^64"` throws a parsing error. 
You'd have to pre-calculate it and write it thus: `big"18446744073709551616"` -- which helps no-one.
Indeed, that wouldn't help at all if you were wanting `UInt128`s--rather than BigInts--anyway.

**Comment by StefanKarpinski** [comment]
So what are you proposing?

**Comment by ScottPJones** [comment]
I wonder if for *literals*, they could be calculated always with `BigInt`, and then converted to whatever type that would be chosen now for them, giving an `InexactError` if they don't fit.
I think that might save a lot of grief.

**Comment by xyproto** [comment]
How about making 2^64 return the correct result, and use a cast or language syntax to let Julia know that overflows are fine? Something along the lines of:

    julia> OverflowsAreFine(2^64)
    0
    julia> 2^64
    18446744073709551616

**Comment by tkelman** [comment]
I dislike the BigInt dependency in the parser that we already have and would be against adding more.

The result of non-modulo 2^64 does not fit in an Int64. Exponentiation could return a different type the way division does, but then you'd need more operators to get access to "real" integer exponentiation.

**Comment by JeffBezanson** [comment]
I don't think `2^64` should be considered a "literal". It's far simpler if it parses as a call to `^`, like all similar expressions do.

**Comment by tkelman** [comment]
Someone has posted some examples before of crazy things Go does where you get different results for things like
```
result = {numberA} op {numberB}
```
vs
```
a = {numberA}
result = a op {numberB}
```

Let's avoid that.

**Comment by H-225** [comment]
@JeffBezanson I guess what I meant is "constants" rather than "literals". I agree that `2^64` should parse to `^(2, 64)`.

@tkelman Indeed, I can see the merit in getting rid of BigInt deps. `BigInt` was just the example I found this by.
If `^` was changed, then I would imagine that simply widening both values before doing anything would not be enough. It might be better to look at the exponent and decide what type the result should be based on how large it is.
Alternatively, always use `BigInt` (or the largest type available) for computation and then demote the type to the smallest that can hold the result, or `Int`--whichever is bigger. Although, that has performance problems; obviously, if all you want to do is `2^4`, then......

**Comment by tkelman** [comment]
> look at the exponent and decide what type the result should be based on how large it is

Read into the issue of "type stability." We have a short-ish paragraph on this in the FAQ and in the performance tips, but we probably need a longer writeup somewhere. http://www.johnmyleswhite.com/notebook/2013/12/06/writing-type-stable-code-in-julia/, perhaps? Little old but still looks accurate.

**Comment by JeffBezanson** [comment]
I don't think there is any reasonable way to give a different result for a constant expression than for an equivalent non-constant expression. Would you want `2^64` and `x=2; x^64` to give different results? Or is this really just about wanting `^` not to overflow?

**Comment by H-225** [comment]
@JeffBezanson I agree that while the original problem lies with constant-expressions, it makes more sense to consider the general case instead.
`^` should raise errors for overflow - or better yet, should always return the correct result.
If the current behaviour was needed for any reason, then it could be available via a different function call. e.g: `pow(n,e)`.

**Comment by JeffBezanson** [comment]
Ok, good to have that clarity. Would you extend this to all arithmetic operators, or is `^` special?

I should note there is a lot of history to this decision. As nice as it is to trap overflow, we feel the performance consequences for checking every addition are just too dire.

**Comment by timholy** [comment]
@H-225 and @xyproto, just to make sure you understand what you're suggesting, you might want to play with some benchmarks. This is very easy. For example:
```jl
function pow2a(ns)
    y = Array(Int, length(ns))
    for i = 1:length(ns)
        y[i] = 2^ns[i]
    end
    y
end

function pow2b(ns)
    y = Array(BigInt, length(ns))
    for i = 1:length(ns)
        n = ns[i]
        y[i] = n > 63 ? BigInt(2)^n : 2^n
    end
    y
end

julia> ns = rand(1:100, 10^6);

# warmup (JIT-compile)
julia> pow2a(ns);

julia> pow2b(ns);

# measure performance
julia> @time pow2a(ns);
  0.048428 seconds (6 allocations: 7.630 MB)

julia> @time pow2b(ns);
  0.829813 seconds (6.03 M allocations: 118.524 MB, 48.85% gc time)
```
If you've been attracted to julia for the performance, it's worth asking what impact a 20-fold reduction in the performance of integer operations would have on your interest in using the language. Keep in mind that integers are used for array indexing, so if we took this to its logical conclusion, we'd have to check every `A[i+k,j]` call to see whether `i+k` overflowed. Not all checks would have the same impact, of course, but the key point is that this Does Not Come For Free, and it makes sense to understand the cost.

Stated another way, such problems are very easy to trigger when you're just "playing around" at the REPL, but I've noticed they seem less common in "real work." If in reality you're only concerned about constants, then this seems like a problem for a [Lint](https://github.com/tonyhffong/Lint.jl) rather than the runtime. Since you're interested in this problem, I bet @tonyhffong would consider a pull request that implemented this check.

**Comment by xyproto** [comment]
There is no doubt that checking for overflow reduces the performance. However, should not correctness be the default, with the option to turn on optimizations, rather than having mathematically incorrect (but fast) results as the default?

**Comment by tkelman** [comment]
It is mathematically correct, subject to the machine representation of the type. Multiplying by 2 is equivalent to shifting the bit representation to the left by 1:
```
julia> bits(2^62)
"0100000000000000000000000000000000000000000000000000000000000000"
julia> bits(2^63)
"1000000000000000000000000000000000000000000000000000000000000000"
julia> bits(2^64)
"0000000000000000000000000000000000000000000000000000000000000000"
```

Have you read http://docs.julialang.org/en/latest/manual/faq/#why-does-julia-use-native-machine-integer-arithmetic ?

**Comment by xyproto** [comment]
The same FAQ says: 
> Clearly, this is far from the way mathematical integers behave

The FAQ also discusses a few possible solutions to this, but it does not seem to discuss the alternative of letting the programmer decide when to offer correctness (as in having integers behave the same way mathematical integers behave) and when to offer performance.

**Comment by tkelman** [comment]
The Julia type `Int` is not the same thing as a mathematical integer. If you want arbitrary-precision integers, you can decide to use `BigInt`.

There is some ongoing work recently, largely by `@eschnett`, making more checked integer operations available to Julia. I don't think we have `checked_pow` just yet, but maybe soon.

**Comment by timholy** [comment]
@xyproto, if it's choice you want, you could write a macro `@bigint` that converts all integer-literals into `BigInt`s. E.g.,
```jl
@bigint begin
myconst = 2^100

function foo(x)
    ...
end

function bar(x)
    ...
end
end  # @bigint
```
and all constants and code inside the block would use BigInts.

**Comment by MithrandirMiles** [comment]
Maybe as a start, all of the operations done at *compile-time*, where it doesn't affect performance at all, should be done using checked arithmetic.  That would solve this issue (at least as soon as @eschnett (or somebody else) adds a `checked_pow` function.

**Comment by H-225** [comment]
@JeffBezanson 

> Would you extend this to all arithmetic operators, or is ^ special?

In some respect, `^` is more important to have this functionality since it does not have many values for integer parameters that wouldn't overflow.
`+` and `-` are obviously a much less important case in that sense.

> I should note there is a lot of history to this decision. As nice as it is to trap overflow, we feel the performance consequences for checking every addition are just too dire.

I would agree that performance is an important focus for Julia. I have no desire to remove that.

@timholy

> If you've been attracted to julia for the performance, it's worth asking what impact a 20-fold reduction in the performance of integer operations would have on your interest in using the language

I'm not suggesting that we do it for _all_ integer arithmetic, _unconditionally_. I would agree that we don't want to do that.
However, I am much more in favor of adjusting what the default behavior is, or have a more intuitive way to change it temporarily.

The bottom line is that it doesn't seem like a good idea to be writing this:
`N = big(2)^64 # prevent overflow`
rather than this,
 `N = BigInt(2^64)`.
The latter is obviously more intuitive.

Put simply, here are my best suggestions at the moment:

1.  Have `^` use either numerically-correct arithmetic and then add another function for the silently-overflowing--but very performant--exponentiation (etc.) that we have currently, such as `pow`.
You would then have `2^64` evaluate correctly, but `pow(Int(2), Int(64))` would result in zero.

2. Add a macro to evaluate numerical-constants using numerically-correct arithmetics, such as:
`N = @mathematical 2^64`; or, `@mathematical begin n=typemax(Int)+1; println(n/2); end`.
You would then use this wherever you care more about the values than types.

There is a question of how to address the type-stability though.
If the `^` function cannot always use `BigInt` in order to have the best performance it can, but also cannot choose the smallest type that's reasonable based on its parameters, then I'm entirely sure how you'd implement it.

**Comment by johnmyleswhite** [comment]
> N = BigInt(2^64).
> The latter is obviously more intuitive.

One could argue that you're very effectively demonstrating that lay intuition is a bad guide for design decisions about programming languages.

**Comment by JeffBezanson** [comment]
> N = BigInt(2^64)
> The latter is obviously more intuitive.

Of course I can't argue with what you find more intuitive, but objectively it isn't. To read julia code you simply have to internalize the fact that subexpressions are evaluated first, independent of their context.

**Comment by H-225** [comment]
@JeffBezanson  @johnmyleswhite 

> [...] objectively it isn't. To read julia code you simply have to internalize the fact that subexpressions are evaluated first, independent of their context.

> [...] lay intuition is a bad guide for design decisions about programming languages.

Perhaps "intuitive" is not the right word. But I take your point. What you're saying is not wrong,
but should we need to internalize state in order to write a constant?

This obviously doesn't stop you being able to write such code, or if you remember it at every juncture then it's not going to be a problem. Like me, in fact. I know what's happening in the program, and I know to make one of the parameters a `BigInt` to have it work.
My problem lies with it not being obvious for something that shouldn't be ambiguous.

**Comment by JeffBezanson** [comment]
There's no ambiguity.

**Comment by digital-carver** [comment]
Special-casing `^` feels kinda ugly especially since it's not even clear that's the only operator that needs this. The `@mathematical` suggestion seems better, but it's unclear what "numerically-correct arithmetics" would boil down to in practice: at the least there's `BigInt` and `BigFloat` each with their pros and cons, and what's "numerically correct" depends on the particular expression being evaluated.

But it is understandable that `BigInt(2^64)` is more intuitive to most people, compared to `BigInt(2)^64`. After all, it's the *result* that you want to be BigInt, not the operand. Given that Julia's target audience has a lot of non-professional-programmers, such considerations can have big impacts. 

One possible solution is to have a macro `@bigint(2^64)` (and similarly, `@bigfloat(2.5^64)`, etc.) which checks the operands to find one that can be exactly promoted to `BigInt`, promotes that and *then* performs the computations (and throws an InexactError if none can be exactly promoted). 

The macro could be named `@bigint_expr` or `@bigint_const` or something cleverer to be clearer on its purpose, but having this functionality would probably make the learning curve a little bit smoother, and avoid potentially a lot of future errors by increasing usability.

**Comment by KristofferC** [comment]
This feels non actionable on the julia side and the default parsing of integer literals is likely not to change at this point.
