### ISSUE TITLE
make Void iterable

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaLang/julia#14423]
could this be useful to someone?

use case:
```julia
Base.start(it::Void) = nothing
Base.done(it::Void, state::Void) = true
Base.next(it::Void, state::Void) = (nothing, nothing)
Base.length(v::Void) = 0

"""
Sample `k` element from array `a` without repetition and excluding elements in `exclude`.
Pay attention, it changes the order of the elements in `a`.

sample!(rng, a, k; exclude = nothing)
"""
function sample!(rng::AbstractRNG, a::AbstractArray, k::Integer; exclude = nothing)
    length(a) < k + length(exclude) && error("Array too short.")
    res = Vector{eltype(a)}()
    sizehint!(res, k)
    n = length(a)
    i = 1
    while length(res) < k
        r = rand(rng, 1:n-i+1)
        if !(a[r] in exclude)
            push!(res, a[r])
            a[r], a[n-i+1] = a[n-i+1], a[r]
            i += 1
        end
    end
    res
end
```
here `exclude` could be Void or any Iterable

**Comment by Keno** [comment]
I think this use is already well served. Making things iterable always has the problem of people potentially not noticing an error. Especially with `nothing`, this seems way to easy to do, e.g. in
```
for x in some_call()

end
```
where you could accidentally forget a return statement in some_call, which would have it return `nothing`.

**Comment by nalimilan** [comment]
This looks really similar to the debate around scalars being iterable. The same trade-off between generic/practical programming and safety applies.

But in the example you give, couldn't use set `exclude=Union{}[]` instead?

**Comment by CarloLucibello** [comment]
good points, using `exclude=()` or  `exclude=Union{}[]` would do. Better be safe and not have an iterable Void then, I'm closing this
