### ISSUE TITLE
docs say: Base.promote (Python function, in Essentials)

### ISSUE THREAD

**Issue by J-Sarnoff** [JuliaLang/julia#14435]
see http://docs.julialang.org/en/latest/search/?q=promote&check_keywords=yes&area=default

**Comment by tkelman** [comment]
Ref #13625 #11527 #11539 https://github.com/rtfd/readthedocs.org/issues/1382 https://github.com/JuliaLang/JuliaDoc/issues/16 - that last one looks like it hasn't been resolved on our side? We'd like to replace Sphinx and RTD anyway so this may not be worth spending much effort on.

**Comment by yuyichao** [comment]
Reopen #11527 and close this one since all the discussion were there.
