### ISSUE TITLE
normalize_url not defined in LibGit2

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/julia#14440]
ref https://github.com/JuliaLang/PkgDev.jl/pull/22

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/PkgDev.jl/issues/18

**Comment by tkelman** [comment]
My mistake, sorry, `Pkg.Cache.normalize_url` is the one we want to use in PkgDev. That probably won't need to move anywhere.

**Comment by tkelman** [comment]
I think https://github.com/JuliaLang/PkgDev.jl/commit/eeacc1dba8045a4f6db4424a427b413be9046793 should be enough

**Comment by kshyatt** [comment]
@tkelman did that end up solving this? Can we close?

**Comment by tkelman** [comment]
PkgDev desperately needs tests, but this isn't a base issue
