### ISSUE TITLE
flush() or close() doesn't make writing immediately for BufferedOutputStream

### ISSUE THREAD

**Issue by sfchen** [JuliaLang/julia#14446]
On `Mac OS X`

```julia
using BufferedStreams.BufferedOutputStream
ostream = BufferedOutputStream(open("test.txt", "w"))
write(ostream, "write a new line \n")
flush(ostream)
```
Then
```shell
cat test.txt
```
It's still a null file
```julia
# even we close it
close(ostream)
```
It's still a null file
```julia
exit()
```
Now the content is written

**Comment by StefanKarpinski** [comment]
Possibly related: https://github.com/JuliaLang/julia/issues/14434.

**Comment by ringw** [comment]
The only issue here is with BufferedOutputStream not flushing the wrapped IOStream, and it is fixed in BioJulia/BufferedStreams.jl#4.

**Comment by sfchen** [comment]
Close this issue as it is a `BufferedOutputStream` bug
