### ISSUE TITLE
Allow binary operators at start of line

### ISSUE THREAD

**Issue by jballanc** [JuliaLang/julia#14455]
There are a number of instances when code that spans multiple lines is much clearer with operators opening the line instead of at the end of each. For example:
```
foo(thing) |>
bar |>
baz
```
versus:
```
foo(thing)
|> bar
|> baz
```

Unfortunately, this currently doesn't work in Julia, as the parser attempts to evaluate `|>` as a unary operator of the next token on the line. Even breaking the newlines like so:
```
foo(thing) \
|> bar \
|> baz
```
does not work (but would still be preferable to placing `|>` at the end of each line).

(*Mea culpa*: I have not yet looked at the parser to asses how difficult this would be, but I would be willing to volunteer a patch if there are no strong objections on style.)

**Comment by Keno** [comment]
I think you'll run into the strong objection that you could never tell whether an expression in actually complete. You can really only do this sort of thing if semicolons are mandatory without running into all sorts of trouble.

**Comment by tkelman** [comment]
if you prefer this style, add ( before foo and ) after baz

**Comment by Ismael-VC** [comment]
Like this:

```julia
(foo(thing)
    |> bar
    |> baz
)
```

**Comment by jballanc** [comment]
Re: expression end being unclear - I agree, that is a potential issue with the first form (I think I've only seen this as legal syntax in indentation-aware languages), but I don't see why it should be an issue if the newlines are escaped. For example, the following is legal in both Ruby and Python:
```
foo = 3 \
       + 4
print(foo)
```

Re: adding parens - If that's the compromise, then I won't be heart-broken. However my past experience with adding extraneous parens for formatting is that often language tools (formatting/indenting, highlighting, etc) tend to break.

**Comment by Keno** [comment]
It's also legal in julia, it just means something else:
```
julia> 3 \
       + 4
1.3333333333333333
```

**Comment by jballanc** [comment]
Oh, interesting... I hadn't considered that implication of `\` being a valid operator!

Hmm...ok, I guess parens will have to do for now as there doesn't seem to be any *easy* way to make this work.
