### ISSUE TITLE
Windows nightlies seem to be stale

### ISSUE THREAD

**Issue by mariushoch** [JuliaLang/julia#14454]
The latest were made from b77587362d which has been committed three weeks ago.

**Comment by yuyichao** [comment]
IIUC this is due to https://github.com/JuliaLang/julia/issues/13719#issuecomment-163037940

**Comment by tkelman** [comment]
fixed thanks to @vtjnash's good guess in 5a66fba2169a8f7369f95e41548b1c57c3b458f1

**Comment by mariushoch** [comment]
Thanks! Especially appreciated as I apparently ran into https://www.cygwin.com/ml/cygwin/2015-12/msg00003.html when trying to build Julia myself on Windows 10.

**Comment by tkelman** [comment]
I think they put out a test release with a fix for that.
