### ISSUE TITLE
Error with --track-allocation=all: unresolved external function _bytecnt.2.53

### ISSUE THREAD

**Issue by jtravs** [JuliaLang/julia#14465]
When using ```--track-allocation=all``` on this very simple code:
```julia
a = rand(1)
println("$a")
```
I get the following error:
```LLVM ERROR: Program used external function '_bytecnt.2.53' which could not be resolved!```

My versioninfo is:
```
Julia Version 0.5.0-dev+1784
Commit 62f1481* (2015-12-15 05:34 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libm
  LLVM: libLLVM-3.7.0
```

**Comment by jtravs** [comment]
I tested with LLVM-3.3 and the error goes away, so I guess this is an LLVM-3.7 issue. However, in that case I get no output `.mem` files, which seems wrong to me.

**Comment by jtravs** [comment]
It seems that if I put the code into a function as:
```julia
function doit()
    a = rand(1)
    println("$a")
end

doit()
```
 I do get the `.mem` file. Is this the intended behaviour (i.e. top-level code is not tracked). I'm fine with it, but I don't think that is documented.

**Comment by timholy** [comment]
I'm not sure "intended" is the right word, but I don't think there's a mechanism to track top-level code. Adding docs to that effect would be great.

**Comment by vtjnash** [comment]
this seems to be fixed now (using track allocations doesn't cause an LLVM ERROR). i opened #15631 to track the second part of the issue.
