### ISSUE TITLE
Is it able to make Dict's iteration order as same as input order?

### ISSUE THREAD

**Issue by sfchen** [JuliaLang/julia#14478]
```julia
d=Dict("aaa"=>"AAA", "bbb"=>"BBB", "ccc"=>"CCC")
Dict{ASCIIString,ASCIIString} with 3 entries:
  "bbb" => "BBB"
  "aaa" => "AAA"
  "ccc" => "CCC"

for k in d
   println(k)
end
"bbb"=>"BBB"
"aaa"=>"AAA"
"ccc"=>"CCC"
```
I know that Dict is hash based, so the native iteration is ordered by hash value. But is there any way to iterate items by the input order (aaa, bbb, ccc for this case)?

This feature is useful when you read some data from a file, parse them to a Dict, and then write the Dict into a new file. One should expect the output file is same as the input file, but currently it is not.

**Comment by bicycle1885** [comment]
[OrderedDicts](https://github.com/JuliaLang/DataStructures.jl#ordereddicts-and-orderedsets).

**Comment by sfchen** [comment]
Thanks, this package is great!
