### ISSUE TITLE
repr error in printing 3+ arg forms of `:comparison` operators

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#14481]
for example:
```
julia> :(in(1,2,3))
:(1 in 2 in 3)
```
while that output expression would actually be interpreted as:
```Expr(:comparison, 1, :in, 2, :in, 3)``` and lowered to ```(1 in 2) && (2 in 3)```

**Comment by mooxmirror** [comment]
How should it be represented then? I think the prefix notation fits since the infix notation makes no sense as you said.

**Comment by vtjnash** [comment]
in prefix notation. the infix notation shouldn't be used since it doesn't round-trip correctly
