### ISSUE TITLE
Typo in doc example of map function

### ISSUE THREAD

**Issue by litat** [JuliaLang/julia#14484]
I'm learning Julia recently. And I found the doc of map function has the following example:
```
Use multiple arguments like so:

  map(1:10, 10:20) do x, y
      x + y
  end
```
When I copy & paste this example to eval in Julia, it generate the following error:
```
ERROR: DimensionMismatch("dimensions must match")
 in map at abstractarray.jl:1336
```

I think it should be change to:
```
  map(1:10, 11:20) do x, y
      x + y
  end
```

**Comment by tkelman** [comment]
Yep. That should have been reviewed when initially added, and it should probably also be a doctest. If you click the pencil edit button at https://github.com/JuliaLang/julia/blob/master/base/docs/basedocs.jl you can suggest the fix yourself as a pull request, if you'd like.
