### ISSUE TITLE
Generated code memory leak (real cases)

### ISSUE THREAD

**Issue by tmptrash** [JuliaLang/julia#14499]
Good morning everyone.

Sorry for this reopening. But i have two real cases of `eval()` related memory leaks in my application. I wrote a comment to [closed](https://github.com/JuliaLang/julia/issues/14495) issue, but no answer, so i decided to open another one.

In two words: i have a biology research, where i need to generate a lot of different code. This is something like self modified aplication. So, here are the cases:
- First is code evaluation from AST. I have something like AST modificator module, which changes AST all the time. I have to call `eval(my_ast)` every time, when new/modified AST appears. And this is quite offten action (~ once per 0.5 of a second). The ability to generate and change AST in Julia is a great feature. It was a one of few criterias why i chose this language.
- Second - code evaluation from string. I have a string representation of Julia code. Some special module changes this string all the time. Like a result i have different code to run. I call `eval(parse(code_str))` for every of these strings and run them. This is real time process and i need a lot of this. So, after 20min of working, depending on configuration, my app may eat ~6Gb of memory :)

In both cases memory leaks appears.

Thanks for help.

**Comment by yuflyud** [comment]
I had the same issue. After unsuccessfull tryings to fix it I gave up and restarted the application every time the memory was full. In my case this awful workaround did a job. Any other ideas (or fixes) would be highly appriciated.

**Comment by JeffBezanson** [comment]
Reopened the original issue.
