### ISSUE TITLE
Suggested use for ± in base

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#14498]
I think it would be nice to use `±` (LaTeX `\pm`) as a function defined like so:

```
±(a::Number, b::Number) = (a + b, a - b)
```

For example `2 ± 3` would yield the tuple `(5, -1)`.

It seems to me that this is a powerful construct that would be incredible easy to implement (see above) and would have familiar functionality to anyone used to mathematical notation.

In the interest of providing an ASCII alternative, it could be an infix Unicode synonym for something like `plusminus(a, b)`.

Any thoughts?

**Comment by nalimilan** [comment]
Given how easy it is to define in your own code, I don't think it would be worth including in Base. We would need evidence that this operator is frequently used for that.

**Comment by swt30** [comment]
`2 ± 3` can mean different things in different contexts: is it the tuple `(-1, 5)`, the interval `[-1, 5]`, a normal distribution with mean 2, or something else? @nalimilan is right that it's probably not worth including in Base, but it's nice that the symbol is left clear for packages to define these interpretations as they see fit. If you find yourself using one particular meaning, you could make a simple package for it. For example, I think I have seen an Interval type before which could be constructed using either `±` or ` ..`, so you could write `-1..5` or `2 ± 3` to get `Interval(-1, 5)`.

**Comment by JeffBezanson** [comment]
I think this is too non-standard to put in Base. However I am curious about use cases that might exist for this.

**Comment by ararslan** [comment]
Fair enough. Thanks everyone for your input! :smiley:
