### ISSUE TITLE
Serialize/Deserialize segfault

### ISSUE THREAD

**Issue by iceblue25** [JuliaLang/julia#14497]
Serializing a structure which has a pointer to a function works fine. When trying ot deserialize the structure and use the function, the function is undefined and the program segfaults.

All other "normal" variables of the structure can be used as expected after deserialization.

Is this the expected behavior?

Thanks

**Comment by StefanKarpinski** [comment]
There's no way to automatically serialized pointers.

**Comment by JeffBezanson** [comment]
Do you mean something of type `Ptr`, or a reference to a julia function? If you have a small example that's usually helpful.

**Comment by iceblue25** [comment]
I m trying to save the structure from https://github.com/lepisma/ELM.jl/blob/master/src/base.jl

The constructor returns a type ExtremeLearningMachine

which contains type HiddenLayer

which contains     act_func::Function

Each time i load the ExtremeLearningMachine type I need to reassign act_func::Function

The weird part is that when I save a ExtremeLearningMachine everything seems to work fine without a segfault. (I m not sure if it is problem free though)

If I save an array of ExtremeLearningMachine types then act_func::Function is undefined.

**Comment by JeffBezanson** [comment]
Could you paste an example sequence of commands we could run to see the problem?

**Comment by JeffBezanson** [comment]
Bump. @iceblue25 I'd like to fix this but I need to be able to reproduce the segfault.

**Comment by iceblue25** [comment]
Hi Jeff,

Thanks for the reply.

I could reproduce this bug in ver 0.4.0-pre using an older set of packages. (when I use a different folder with my packages the error does not come up ) Which packages affect serialize/deserialize? I think a package serialize/deserialize are using create the bug.

Anyway for the record, here is what generated this bug for me


First clone ELM from  https://github.com/lepisma/ELM.jl
Then execute the following to serialize and save an ELM structure which includes a sigmoid function:
 
using ELM

X_train = [1 1 1; 1 0 1; 0 0 0; 1 0 0]
Y_train = [1, 1, 0, 0]

elm = ExtremeLearningMachine(100) # number of nodes
fit!(elm, float(X_train), float(Y_train))

X_test = [0 1 1; 0 1 0]
predict(elm, float(X_test))
X_train = [1 1 1; 1 0 1; 0 0 0; 1 0 0]
Y_train = [1, 1, 0, 0]

elm2 = ExtremeLearningMachine(100) # number of nodes
fit!(elm2, float(X_train), float(Y_train))

X_test = [0 1 1; 0 1 0]
predict(elm2, float(X_test))

d=Dict();

d["a"]=elm;
d["b"]=elm2;

println("1st function: $(elm.hidden_layer.act_func)")
println("2st function: $(elm2.hidden_layer.act_func)")


f=open("filename","w");
serialize(f,d);
close(f);


 println should print sigmoid which is the function name before saved in a file

Now exit julia , start again and execute:

f=open("filename","r");
d=deserialize(f);
close(f);


b=d["a"]
c=d["b"]

println("1st function : $(b.hidden_layer.act_func)")
println("2nd function : $(c.hidden_layer.act_func)")


The first println instead of printing sigmoid prints a weird structure. I think the segfault appears when the sigmoid is called but instead there is this structure referenced.

Also,  saving in a dictionary just one elm variable and not two the problem disappears.

Let me know if you can reproduce the error,
Thanks

**Comment by axsk** [comment]
I have a similar problem, but could not find a simple reconstruction yet.

The basic setup that I serialize/deserialize a value containing (kind of nested) an anonymous function, which itself uses a call to a fortran library (not sure if that plays a role here).

When deserializing in the same session as serializing everyhing goes well, but when deserializing from a new julia session, and calling a function on this value I also get a segfault, with [the last line mentioned from my code](https://github.com/axsk/GynC.jl/blob/b430bd5e8f0532ff959df967ad7cb0cafe169edd/src/model.jl#L47) containing that anonymous function.

This actually does not happen every time, sometimes it just works.
I also think that after running everthing directly (w/o serializing/deserializing), I can deserialize the previously saved state and it runs (at least as far as I tested).

**Comment by vtjnash** [comment]
i'm guessing this is https://github.com/JuliaLang/julia/issues/15250

**Comment by axsk** [comment]
Since my Travis tests are passing (yay!) you should be able to reproduce it with
``` julia
Pkg.clone("https://github.com/axsk/GynC.jl")
using GynC
mc = mcmc(ModelConfig(Pfizer(1)), 1)
open(file->serialize(file,mc), "test.jls", "w")
## restart here
using GynC
mc = open(deserialize, "test.jls", "r")
mcmc(mc, 1)
```

**Comment by axsk** [comment]
@iceblue25 I tried your example, but in 4 of 4 cases it just ran through smoothly :/

**Comment by axsk** [comment]
In some rare cases (~1%) it even crashes when just serializing/deserializing, without restarting julia.

**Comment by amitmurthy** [comment]
Since you mentioned nested anonymous functions referencing https://github.com/JuliaLang/julia/issues/15451.

**Comment by KristofferC** [comment]
Please comment if this is still an issue.
