### ISSUE TITLE
hist function help clarifications

### ISSUE THREAD

**Issue by alexranaldi** [JuliaLang/julia#14521]
In Julia 0.4.1, the hist function returns a tuple, however, the documentation states that a vector is returned.  Perhaps the doc should mention that a tuple is returned and describe the contents of the tuple.

**Comment by mbaz** [comment]
Should this issue be closed? The documentation for v4 seems correct now. cc @tkelman

**Comment by tkelman** [comment]
Was there an issue or specific commit that was responsible? Having trouble finding anything that looks relevant.

**Comment by mbaz** [comment]
I can't find anything either (I went back a few months for
doc/stdlib/math.rst). However, current documentation a) looks right and b)
is the same as that of v0.5 ( so no backport is possible).

-- mb

**Comment by tkelman** [comment]
Hm, thanks for checking. Maybe this was a temporary rendering issue on readthedocs or something?

**Comment by mbaz** [comment]
I've no idea, TBH...

**Comment by tkelman** [comment]
@alexranaldi leave another comment and we can reopen if things are still not clear enough
