### ISSUE TITLE
with_output_limit removed at some point?

### ISSUE THREAD

**Issue by jgoldfar** [JuliaLang/julia#14533]
Running Julia (Version 0.5.0-dev+1953 (2016-01-01 23:47 UTC), Commit 03a5b9f), I get the following:
```
dump("TEST")
ERROR: UndefVarError: with_output_limit not defined
 in dump at show.jl:1032
 in eval at ./boot.jl:265
```

Testing on JuliaBox's v0.5 (Version 0.5.0-dev+1526, Commit b775873) gives the expected
```
dump("TEST")
ASCIIString "TEST"
```

**Comment by timholy** [comment]
Also noted in https://github.com/JuliaLang/julia/pull/13825#issuecomment-168384591.
