### ISSUE TITLE
Possible bug with range in v0.5

### ISSUE THREAD

**Issue by scidom** [JuliaLang/julia#14531]
Apologies in advance if this is not a bug. I have initially opened a relevant issue for the Lora package, and decided to open one under julia to ensure that the issue will receive attention and will be resolved, in case it is a bug. The following snippet works under v0.4.2, but fails under v0.5:

```
immutable MyRange{T<:Int} <: Range{T}
  postrange::StepRange{T, T}
  npoststeps::T

  function MyRange(postrange::StepRange{T, T})
    new(postrange, length(postrange))
  end
end

MyRange{T<:Int}(postrange::StepRange{T, T}) = MyRange{T}(postrange)

Base.show(io::IO, r::MyRange) = print(io, "npoststeps = ", repr(r.npoststeps))

MyRange(100:1:1000)
```

When it fails under v0.5, the following error is thrown:

```
Error showing value of type MyRange{Int64}:
ERROR: StackOverflowError:
 in size at range.jl:305 (repeats 80000 times)
```

**Comment by nalimilan** [comment]
Looks like you should override `writemime` instead of `show`:
```julia
julia> writemime(STDOUT, MIME("text/plain"), MyRange(100:1:1000))
ERROR: StackOverflowError:
 in size at range.jl:306 (repeats 257 times)
```

The version which is called is designed to handle ranges and it makes certain assumptions.

The display functions mess is going to be improved soon, @vtjnash can tell you how this will work in 0.5.

**Comment by scidom** [comment]
Great, thanks very much, based on your suggestion, the following now works both on v0.4.2 and v0.5.0:

```
immutable MyRange{T<:Int} <: Range{T}
  postrange::StepRange{T, T}
  npoststeps::T

  function MyRange(postrange::StepRange{T, T})
    new(postrange, length(postrange))
  end
end

MyRange{T<:Int}(postrange::StepRange{T, T}) = MyRange{T}(postrange)

Base.writemime(io::IO, ::MIME"text/plain", r::MyRange) = print(io, "npoststeps = ", repr(r.npoststeps))

MyRange(100:1:1000)
```

Yes, it'd be great to know how display will change in 0.5. For now we may close this issue since it seems to have been sorted. Thanks a lot :+1:
