### ISSUE TITLE
string(nothing) returns "nothing"

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#14540]
I was surprised to find the following behavior for `nothing`:

    julia> nothing  # what I expect

    julia> string(nothing)
    "nothing"

    julia> repr(nothing)
    "nothing"

    julia> show(nothing)
    nothing
    julia> print(nothing)
    nothing

Is this intended functionality? This isn't how I would expect the `Void` type to behave. It would make more sense to me if `string(nothing) == string() == ""`, with similar definitions for the other I/O methods. Would that be desirable?

**Comment by Keno** [comment]
No, that would be undesirable, because those methods are also used to display nothing, when it is contained inside other structures:
```
julia> (nothing,)
(nothing,)

julia> (,)
ERROR: syntax: unexpected ,
 in eval at /Users/kfischer/julia-target/usr/lib/julia/sys.dylib
```

**Comment by ararslan** [comment]
@Keno Okay, didn't know. Thanks!
