### ISSUE TITLE
Pkg.update fails with unhelpful message

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#14548]
I just downloaded the latest master and then trying to do a `Pkg.update()` fails with a very unhelpful message.
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+1968 (2016-01-02 23:28 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e55c22a (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
ERROR: GitError(Code:EMERGECONFLICT, Class:Checkout, 546 conflicts prevent checkout)
 [inlined code] from libgit2/error.jl:98
 in __checkout_tree#337__ at libgit2/repository.jl:148
```
removing the v0.5 package dir and started on a fresh removed the error. I have no clue what caused it.

**Comment by tkelman** [comment]
You had a merge conflict preventing updating metadata. Could use a translation from error code to something more descriptive.

**Comment by dhoegh** [comment]
I started out by deleting the packages which `Pkg.status` deemed dirty, this didn't fix the issue. Didn't 0.4 just update the packages that wasn't dirty, even though some packages were dirty.

**Comment by tkelman** [comment]
The conflict was apparently in metadata itself?
