### ISSUE TITLE
Compilation error on master

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#14558]
I am trying to compile the newest master from a standard fresh `git clone` and get the following error:

```
JULIA usr/lib/julia/inference0.ji
/home/kristoffer/julia/usr/bin/julia: symbol lookup error: /home/kristoffer/julia/usr/bin/julia: undefined symbol: jl_tls_states
make[1]: *** [/home/kristoffer/julia/usr/lib/julia/inference0.ji] Error 127
make: *** [julia-inference] Error 2
```

This is on a Ubuntu system, with gcc.

Since this hasn't been reported yet it must be something strange with my system but to make everything as standard as possible I did a fresh clone and just ran make in it.

Interestingly, if I enable `JULIA_THREADS=1` I get a different symbol lookup error:

```
JULIA usr/lib/julia/inference0.ji
/home/kristoffer/julia/usr/bin/julia: symbol lookup error: /home/kristoffer/julia/usr/bin/julia: undefined symbol: jl_set_ptls_states_getter
make[1]: *** [/home/kristoffer/julia/usr
```

cc @yuyichao

**Comment by yuyichao** [comment]
This is very strange. Can you check `ldd /home/kristoffer/julia/usr/bin/julia` to see if it find the correct `libjulia.so`. If not, check `objdump -p /home/kristoffer/julia/usr/bin/julia` if the `RPATH` is correct and if yes, check `objdump -T /home/kristoffer/julia/usr/lib/libjulia.so | grep tls` to see if the symble is actually exported with the correct name?

**Comment by KristofferC** [comment]
Found the error... I had added the path to another julia folder to `LD_LIBRARY_PATH` and it seems that julia looked there instead. Removing that and it compiles fine.

Sorry for the noise.
