### ISSUE TITLE
remove Coff_t

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#14555]
we should remove `Coff_t` from the base API as it cannot be used correctly. the problem with it is that is is not OS-dependent, but compiler-flag dependent (on glibc) and so any function that tries to use this parameter as an argument (e.g. d000aaef) ends up calling the wrong function (again, possibly just on glibc).

Instead, we should tell people to use Int64 for all file offsets and define c-stubs for resolving any libc lies (e.g. a78e48c0)

**Comment by yuyichao** [comment]
The only remaining use of it in base is libgit2. I guess we just assume it's compiled with the right flag on linux 32bit? I'm wondering how many distributions turn on `_FILE_OFFSET_BITS=64` by default.

**Comment by yuyichao** [comment]
Also ref https://github.com/JuliaLang/julia/commit/a366f32969f70250a7a04e71bcb17a77716f14eb

**Comment by vtjnash** [comment]
libgit2 should be using Int64 (the actual struct is a git_off_t and is typedef'd to int64 in c to avoid conflicting definitions wth the libc off_t).
