### ISSUE TITLE
docs for `showcompact` and array printing

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#14575]
The current docs for `showcompact` say:
```
Show a more compact representation of a value. This is used for printing array elements.
```

In `print_matrix_repr`, compactness is determined by `array_eltype_show_how(X)`, which ends up only being compact if `isleaftype(T) && (T<:Number || T<:AbstractString)`

I wanted to clarify expected behavior. I came across this because I'm defining a non-numeric type that I want to display more compactly when in a vector, and initially thought I could just define `showcompact`.

Given #14052 this may soon become a moot point, so feel free to say so and close if it's not worth worrying about.

EDIT: I just realized that `showcompact` is used by `writemime` when displaying to the REPL, so I'm guessing that's what the note in the docstring is referring to.

**Comment by ssfrr** [comment]
also, I'm happy to either update the docs or the implementation once I know what the right direction is, and if it's not about to be imminently clobbered.

**Comment by JeffBezanson** [comment]
The help for `showcompact` now explains how to deal with it. This is also part of #5709.
