### ISSUE TITLE
Unintentional promotion to `Any` in `+`, `-`

### ISSUE THREAD

**Issue by spurll** [JuliaLang/julia#14573]
Adding integers to (or subtracting integers from) characters results in characters, which is good, great, etc.:

```julia
julia> 'a' + 1
'b'
```

The reverse is also true:

```julia
julia> 1 + 'a'
'b'
```

With `map` one can do the same with arrays of characters and arrays of integers:

```julia
julia> map(x -> x + 1, ['a', 'b', 'c'])
3-element Array{Char,1}:
 'b'
 'c'
 'd'

julia> map(x -> x + 'a', [1, 2, 3])
3-element Array{Char,1}:
 'b'
 'c'
 'd'
```

However, when adding arrays of type `Char` and `Int64` together, we see a potentially problematic promotion to `Any`:

```julia
julia> ['a', 'b', 'c'] + [1, 2, 3]
3-element Array{Any,1}:
 'b'
 'd'
 'f'
```

**Comment by tkelman** [comment]
closed by #14578
