### ISSUE TITLE
copy!(to::IntSet, from::IntSet) fails when to === from

### ISSUE THREAD

**Issue by zsunberg** [JuliaLang/julia#14581]
```julia
a = IntSet([1,2,3])
copy!(a,a)
# a is now IntSet([])
```
I think this is the wrong behavior; `a` should still be `IntSet([1,2,3])` after the copy.

Why would anyone do this? I don't know. I did it by accident ;) but it should probably be corrected. I will submit a pull request with the (3 line) fix and a test soon. 

How should I go about backporting the fix to 0.4 (and 0.3?)

**Comment by tkelman** [comment]
> How should I go about backporting the fix to 0.4 (and 0.3?)

Will label the PR "backport pending 0.4."

**Comment by tkelman** [comment]
closed by #14582, thanks

**Comment by kshyatt** [comment]
I was just about to close this, @tkelman. You're too quick at the draw.
