### ISSUE TITLE
build error/crash using out-of-tree build option

### ISSUE THREAD

**Issue by protogeezer** [JuliaLang/julia#14598]
The files usually installed in JULIA_HOME/../share/julia/base using the default (in-tree?) build are installed in JULIA_HOME/../../base during an out-of-tree build. 

The misplaced base directory results in crashes when julia attempts to access the files:
MichaelHatherly/Docile.jl#165

@MichaelHatherly

**Comment by tkelman** [comment]
Hm. Have you done `make install` into the out of tree build dir?

**Comment by protogeezer** [comment]
@MichaelHatherly

I just tried it. I ended up with 8 files in the expected build/share/julia/base directory. It looks like there should have been dozens or hundreds of files. The crash issue I filed with Docile still happens.

If there is anything else

**Comment by MichaelHatherly** [comment]
@protogeezer, so to summarise from https://github.com/MichaelHatherly/Docile.jl/issues/165, you did

```
git clone git://github.com/JuliaLang/julia.git julia-0.5
cd julia-0.5
mkdir build
make O=build configure
cd build
make -j4
./julia
```

and then `functionloc` fails to return the path? (`make install` didn't help either?)

```julia
julia> functionloc(isgeneric)
(nothing,117)
```

If those are the right steps to build out of tree then `Base.find_source_file` needs to fixed to find the correct paths for base files. If those aren't the correct steps then do the right ones need to be documented somewhere (if they aren't already?).

**Comment by protogeezer** [comment]
Yes, that is correct. For completeness, I suppose I could try defining a prefix in the make.user file to see if that avoids the problem...

**Comment by ederag** [comment]
Indeed, the `make install` works
it is mandatory for `functionloc` to show the correct file instead of `nothing`.

```bash
julia_version=1.4.0

# inside a julia cloned repo
git checkout v${julia_version}

# change /usr/local/build to wherever you want to build and install julia
make O=/usr/local/build/julia-${julia_version}_build configure
# note: find : No such file... are normal

cd /usr/local/build/julia-${julia_version}_build
echo "prefix=/usr/local/build/julia-${julia_version}" > Make.user
make -j $(nproc)
make install
```

[build.md](https://github.com/JuliaLang/julia/blob/9f22a3b4ce9c38bc73d7fc82aa0d61e286162c1a/doc/build/build.md) could warn about that (PR #35482)
Or would a fix be worth the time ?

**Comment by ViralBShah** [comment]
Do we still that note in build.md?

**Comment by vtjnash** [comment]
Yes, we can merge that

**Comment by vtjnash** [comment]
Though I did not actually realize make install was sufficient
