### ISSUE TITLE
Mac build error with BUILD_LLVM_CLANG=1 on v0.4

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/julia#14593]
I'm trying to build `release-0.4` with `BUILD_LLVM_CLANG=1` in my Make.user to get Clang.jl running.  But I'm hitting the following error:

```
  COMPILE:   clang_darwin/asan_osx/i386: /Users/rrock/Documents/Code/julia/deps/llvm-3.3/projects/compiler-rt/lib/asan/asan_mac.cc
/Users/rrock/Documents/Code/julia/deps/llvm-3.3/projects/compiler-rt/lib/asan/asan_mac.cc:26:10: fatal error: 'crt_externs.h' file not found
#include <crt_externs.h>  // for _NSGetArgv
         ^
1 error generated.
```

I'm on OS X 10.11.2. This happens even after a full rebuild (I ran `git clean -xfd` as the nuclear option first).  Any ideas why I'm not picking up this header?

**Comment by tkelman** [comment]
Have you upgraded osx version more recently than reinstalling the xcode command line tools?

**Comment by rsrock** [comment]
Yes, that was it, I forgot that the command line tools are uncoupled from Xcode itself.  An `xcode-select --install` fixed it.
