### ISSUE TITLE
Output JIT type, CPU architecture with versioninfo

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14591]
In the past week there were a few emails on the mailing list describing problems where knowing the poster's JIT type or CPU architecture would have been helpful. This information could be output with `versioninfo`, as part of the LLVM description.

**Comment by tkelman** [comment]
good idea. There's a `Sys.cpu_name` or something that asks llvm what it's using.

**Comment by tlnagy** [comment]
What do you mean by JIT type?

**Comment by eschnett** [comment]
The JIT type can be e.g. MCJIT, ORCJIT, etc. -- LLVM's mechanisms are currently changing, and some problems depend on what JIT API is used. This is selected with `#ifdef` statements in the C++ code.
