### ISSUE TITLE
No documentation for Ref

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14604]
When one tries to find his/her way with calling C functions with pointers, s/he will likely end up reading this:

``` julia
help?> pointer
search: pointer pointer_to_array pointer_to_string pointer_from_objref

  pointer(array [, index])

  Get the native address of an array or string element. Be careful to ensure
  that a julia reference to a exists as long as this pointer will be used.
  This function is "unsafe" like unsafe_convert.

  Calling Ref(array[, index]) is generally preferable to this function.
```

But:
1) The docs do not say why `Ref` is preferable. What's the difference with `pointer`?
2) `?Ref` gives no result (though the manual contains a lot of information).

**Comment by kshyatt** [comment]
`?Ref` at least gives more information now. However, point 1 still isn't addressed.
