### ISSUE TITLE
NTuple{ANY,Int} should be an error

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#14607]
I assume that this is a result of the slightly hachy nature of `ANY`:

```jl
julia> NTuple{Any,Int}
ERROR: TypeError: NTuple: in parameter 1, expected Int64, got Type{Any}
 in eval at ./boot.jl:265

julia> NTuple{ANY,Int}
NTuple{ANY,Int64}
```

See https://groups.google.com/forum/#!topic/julia-users/9H9d-T8aOos.

**Comment by yuyichao** [comment]
Since `ANY` is a `TypeVar` it is allowed to be a type parameter?

**Comment by StefanKarpinski** [comment]
I guess. Maybe there's no avoiding this, in which case we should just close it.

**Comment by johnmyleswhite** [comment]
Maybe we should replace `ANY` with `@nospecialization`?

**Comment by JeffBezanson** [comment]
Yes I think the only reasonable way to "fix" this is to remove `ANY`. But plumbing the information to where it needs to go is likely to be painful (the specialization logic naturally looks at the method signature, so that was a really easy way to pass the data).
