### ISSUE TITLE
fun with Union{}

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#14612]
```julia
julia> eltype(Zip{Union{}, Union{}})
ERROR: type Union has no field parameters
 tuple_type_cons from iterator.jl:62
 in eltype at iterator.jl:64
 in eval at ./boot.jl:267
```

**Comment by JeffBezanson** [comment]
Did this arise in some real code?

**Comment by vtjnash** [comment]
no -- call it fuzz testing

**Comment by JeffBezanson** [comment]
I think I'll call this a dup of #10326. I could imagine a rule that says type vars are simply not allowed to match `Union{}`, which would get rid of all these strange method invocations. Seems a bit too strict though.
