### ISSUE TITLE
No `abstract Iterable{T}` ?

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#14629]
There is `abstract Associative{K,V}` so why is there no `abstract Iterable{T}` ?
i.e. where `eltype{T}(itr::Iterable{T}) = T` ?

**Comment by JeffBezanson** [comment]
Yes, I could imagine an `Iterable` or `Collection` type above AbstractArray and Associative. However to do `Iterable` correctly requires protocols. I think generally we've felt this type would require multiple inheritance or protocols.

**Comment by samoconnor** [comment]
Ok, I'm familiar with protocols form Objetive-C.
And I've now found this: https://github.com/JuliaLang/julia/issues/6975
