### ISSUE TITLE
write(to::IO, from::IO)

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#14628]
I have some code like this:

```julia
    stream = s3(aws, "GET", key)
    open(filename, "w") do file
        while !eof(stream)
            write(file, readavailable(stream))
        end
    end
```

With `write(to::IO, from::IO)` it could be reduced to:

```julia
stream = s3(aws, "GET", key)
open(filename, "w") do f write(f, stream) end

or even just...

write(filename, s3(aws, "GET", key))
```

This is not just about terse code.
The `write(readavailable())` loop is potentially quite memory inefficient. If the task has been suspended for a while, the stream could have many MB available and depending on how stream buffering is implemented large buffers could be duplicated.

It seems like it would be better to have a  `write(to::IO, from::IO)` API so that shortcut implementations can be created to directly connect two streams at a low level where that is more efficient.
e.g. this could map to [`sendfile()`](http://man7.org/linux/man-pages/man2/sendfile.2.html) in some cases.

The default can just be:
```julia
write(to::IO, from::IO) = while !eof(from) write(to, readavailable(from)) end
```

**Comment by vtjnash** [comment]
I agree

**Comment by StefanKarpinski** [comment]
+1

**Comment by samoconnor** [comment]
Included in https://github.com/JuliaLang/julia/pull/14660
closing

**Comment by samoconnor** [comment]
See https://github.com/JuliaLang/julia/blob/master/base/io.jl#L175

**Comment by swt30** [comment]
Ah, thank you - I was thinking about this just last night while writing from one stream to another. It seemed odd to me that this method didn't already exist.
