### ISSUE TITLE
Base.function_module does not work with method-less function

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#14636]
Two things: `function_module` should be renamed `method_module` as it returns the module of a particular method and of a function.

In light of above it is clear that this does not work:
```
julia> module X
       function f end
       end
X

julia> Base.function_module(X.f, Tuple{Any})
ERROR: no matching methods
 in function_module at reflection.jl:342
```

Is it be possible to infer where a method-less generic function was defined?  If yes, should this be added to Base?

**Comment by vtjnash** [comment]
in v0.4, it is stored in `X.f.env.module`. after jb/functions in v0.5, it will be in `typeof(X.f).name.module`

**Comment by mauro3** [comment]
Thanks. I'll wait till after jb/functions and then put a PR together with a method_module function and a function_module function.  If that is not desired, please close this issue.
