### ISSUE TITLE
Enable LLVM -O optimizations by default

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#14632]
Once #14623 is merged, we should consider enabling the basic AA and SLP vectorizer passes without requiring `-O`. Per @ArchRobison's [PR](https://github.com/JuliaLang/julia/pull/6271#issue-30255665), the compilation time cost was negligible with LLVM 3.5 but not 3.3, which was the reason for hiding them behind `-O`. We should verify that the compilation time cost is still negligible with LLVM 3.7, but if things haven't changed, it would be great to have these passes on by default.

**Comment by JeffBezanson** [comment]
We should also add `-O0` which only runs the mem2reg pass (and maybe 1-2 others?). I've done tests where this cuts down compile time significantly, with fairly little run time cost.

**Comment by tkelman** [comment]
It it at all feasible to make these in-language API's rather than command line flags?

**Comment by JeffBezanson** [comment]
I think we need both, since a command line option is the only way to be sure all compiled code is affected.

**Comment by vtjnash** [comment]
`-O` flags added in https://github.com/JuliaLang/julia/pull/14951

**Comment by KristofferC** [comment]
This doesn't seem resolved..

The issue is about enabling SLP and AA by default. Current default optimization level is 2 and SLP and AA are activated at optimization level 3 i.e. not by default.

**Comment by vtjnash** [comment]
It said we should consider it. It was considered, and decided that we need compilation to be faster.

**Comment by KristofferC** [comment]
Ok, I didn't see that conclusion in the linked PR.

**Comment by simonster** [comment]
Yes, if you've benchmarked this it would be useful to see the results.

**Comment by KristofferC** [comment]
FWIW worth the subarray test ran in 420 seconds with default optimization and 430 seconds with `-O3`.

**Comment by tkelman** [comment]
We should probably get the default compilation performance back to parity with where it was with LLVM 3.3, then re-run that comparison again. 5% sounds small enough to me to be worth enabling more optimizations by default, but we're comparing to a known-bad baseline at the moment.

**Comment by ArchRobison** [comment]
I concur.  Let's fix the baseline first.

**Comment by KristofferC** [comment]
Just pointing out that with `-O3` LLVM automatically vectorizes operations between tuples (no need for `VecElement`) and it is also quite good at it!. See for example https://github.com/JuliaDiff/ForwardDiff.jl/issues/98#issuecomment-253015052. It also uses AVX (<4x Float64>) if the sysimg is built locally. Due to the popularity of fixed size arrays package (https://github.com/JuliaArrays/StaticArrays.jl/) all of these would get lovely SIMD automagically if this could be enabled by default.
