### ISSUE TITLE
Any[1 [1,2]] ERROR: DimensionMismatch

### ISSUE THREAD

**Issue by egoecho** [JuliaLang/julia#14646]
In Julia 0.4.2,
```julia
julia> Any[1 [1,2]]
ERROR: DimensionMismatch("mismatch in dimension 1 (expected 1 got 2)")
 in cat_t at abstractarray.jl:850
 in typed_hcat at abstractarray.jl:878
```
The old style is fine:
```julia
julia> {1 [1,2]}
WARNING: deprecated syntax "{a b ...}".
Use "Any[a b ...]" instead.
1x2 Array{Any,2}:
 1  [1,2]
```
I also found that Any[1 [1]] = {1 1} rather than {1 [1]}
```julia
julia> Any[1 [1]]
1x2 Array{Any,2}:
 1  1

julia> {1 [1]}

WARNING: deprecated syntax "{a b ...}".
Use "Any[a b ...]" instead.
1x2 Array{Any,2}:
 1  [1]
```

**Comment by anthonyclays** [comment]
`Any[1 [1, 2]]` will call `typed_hcat`

**Comment by KristofferC** [comment]
Imo, if you specify "Any" then there shouldn't be any concatenation.

**Comment by anthonyclays** [comment]
@KristofferC You could specialize the typed concatenation functions when `typeC = Type{Any}`, but then again what should the behaviour of `AbstractArray[[1] [1, 2]]` be?
You can't simply special-case Any (like `{...}` used to do). It's not really obvious what the best behaviour would be here.

**Comment by anthonyclays** [comment]
There will be ambiguity when using any subtype of AbstractArray in the construction of an `Any`-typed array, I believe (for example `Any[1:3 10]` fails too)

**Comment by phobon** [comment]
This looks like more evidence there should be parallel syntaxes for array construction and concatenation. (#7128)

**Comment by tkelman** [comment]
Or concatenation should be a function call rather than syntax. We should also flip the switch on the concatenation deprecation behavior from #8599

**Comment by JeffBezanson** [comment]
This will stay as-is for now. As long as `[a b]` means concatenation, `T[a b]` should mean concatenation with an element type.

closing as dup of #7128
