### ISSUE TITLE
Order dependent crash with precompile in 0.4.3 

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaLang/julia#14663]
Reproduction, in a clean Julia 0.4.3 install 

    Pkg.generate("Foo", "MIT" )
    Pkg.generate("Bar", "MIT" )
 
edit Foo.jl to 

     __precompile__()
     module Foo
     using Bar
     # package code goes here
     end # module

now do 

    using Bar
    ...
    using Foo
    ...
      WARNING: Module Bar uuid did not match cache file
      ERROR: __precompile__(true) but require failed to create a precompiled cache file
       in require at ./loading.jl:257

clean the lib directory

    using Foo
    using Bar 

all good, exit come back in 

    using Bar
    using Foo

all good

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13200

**Comment by yuyichao** [comment]
The repro looks interesting. Will check if it is more deterministic.

**Comment by mdcfrancis** [comment]
This repro happens 100% of the time and is just a few lines of code. The issue is specifically caused by a child module not having __precompile__() in a module which does.
