### ISSUE TITLE
@parallel does not update shared array object

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#14664]
Running the following example [ from the Julia documentation](http://docs.julialang.org/en/latest/manual/parallel-computing/#parallel-map-and-loops) doesn't work on 0.5 (cf3259f) but does on 0.4.2
```
$ ./julia -p 2

julia> a = SharedArray(Float64,10)
       @parallel for i=1:10
         a[i] = i
       end
       a
10-element SharedArray{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

**Comment by amitmurthy** [comment]
@JeffBezanson commit https://github.com/JuliaLang/julia/commit/52deb9fa19fc5057188187e234a011a11cde84d1 is causing this issue.

**Comment by amitmurthy** [comment]
Works on current master. I am guessing https://github.com/JuliaLang/julia/pull/13412 fixed this?

**Comment by tkelman** [comment]
we should add a test case for this
