### ISSUE TITLE
Array hashing does not take order into consideration

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#14670]
Noticed [here](https://github.com/hayd/DataStructures.jl/commit/f4a905adb3bdb5953dd8caba9d8302e2688b42da#commitcomment-15441647).

Most of the time, it isn't actually necessary to think about array order when hashing, because primitive types do interesting things with mixing in `h` before they call `hash_uint64`.  But

```julia
julia> hash([Set(), Dict()]) == hash([Dict(), Set()])
true
```

Cc: @StefanKarpinski @simonster

**Comment by JeffBezanson** [comment]
I see:

```
julia> hash(Dict(),hash(Set(),UInt(0)))
0xf260958965163607

julia> hash(Set(),hash(Dict(),UInt(0)))
0xf260958965163607
```

Dict and Set are mixing their hash seed using `+`. They should be using a bit mixing primitive, which was removed in 0.3 but I think we should restore. `hash(x,y)` can be used for that but is suboptimal since it has to pay the cost of correct numeric hashing.

**Comment by StefanKarpinski** [comment]
Here's a patch that fixes this issue fairly straightforwardly:

```diff
diff --git a/base/dict.jl b/base/dict.jl
index e4e49c0..ebb39d6 100644
--- a/base/dict.jl
+++ b/base/dict.jl
@@ -282,7 +282,7 @@ end

 const hasha_seed = UInt === UInt64 ? 0x6d35bb51952d5539 : 0x952d5539
 function hash(a::Associative, h::UInt)
-    h += hasha_seed
+    h = hash(hasha_seed, h)
     for (k,v) in a
         h $= hash(k, hash(v))
     end
diff --git a/base/set.jl b/base/set.jl
index 56bd8b6..46a14aa 100644
--- a/base/set.jl
+++ b/base/set.jl
@@ -154,7 +154,7 @@ end

 const hashs_seed = UInt === UInt64 ? 0x852ada37cfe8e0ce : 0xcfe8e0ce
 function hash(s::Set, h::UInt)
-    h += hashs_seed
+    h = hash(hashs_seed, h)
     for x in s
         h $= hash(x)
     end
```

Results:

```jl
julia> hash(Dict(),hash(Set(),UInt(0)))
0x4cfeaffc446401d3

julia> hash(Set(),hash(Dict(),UInt(0)))
0x393f339c53b294b5
```

Given that the code for `hash(::UInt, UInt)` is pretty cheap compared to both the hashing that happens right after it and all of the iterating over containers, it doesn't seem worth it to reintroduce `bitmix`. Technically, transforming `h` with any functions `f` and `g` such that `f∘g ≠ g∘f` should be fine. The simplest example I can think of is this:

```diff
diff --git a/base/dict.jl b/base/dict.jl
index e4e49c0..f528ecb 100644
--- a/base/dict.jl
+++ b/base/dict.jl
@@ -282,7 +282,7 @@ end

 const hasha_seed = UInt === UInt64 ? 0x6d35bb51952d5539 : 0x952d5539
 function hash(a::Associative, h::UInt)
-    h += hasha_seed
+    h = hasha_seed - 3h
     for (k,v) in a
         h $= hash(k, hash(v))
     end
diff --git a/base/set.jl b/base/set.jl
index 56bd8b6..4aa795c 100644
--- a/base/set.jl
+++ b/base/set.jl
@@ -154,7 +154,7 @@ end

 const hashs_seed = UInt === UInt64 ? 0x852ada37cfe8e0ce : 0xcfe8e0ce
 function hash(s::Set, h::UInt)
-    h += hashs_seed
+    h = hashs_seed - 3h
     for x in s
         h $= hash(x)
     end
```

The main downside to something that simple is that you can prove that the hashes will always differ by 4 times the difference between the two hash seeds:

```jl
julia> h1 = hash(Dict(),hash(Set(),UInt(0)))
0xddb52caa2572b2cf

julia> h2 = hash(Set(),hash(Dict(),UInt(0)))
0x3d89a8431060e123

julia> h1 - h2 == 4(Base.hasha_seed - Base.hashs_seed)
true
```

But I'm not sure if that matters very much.

**Comment by JeffBezanson** [comment]
Yes, the simple fix of using `hash` is fine for now.
