### ISSUE TITLE
Chars with ending double quotes

### ISSUE THREAD

**Issue by pabloferz** [JuliaLang/julia#14683]
As stated <a href="https://groups.google.com/forum/#!topic/julia-users/DIQGaXEZLkI">here</a>. The following are valid inputs for `Char`

```julia
union('A', '\A', '\A"', '\A""', '\A"""') == Char['A']
```

More generally, it seems that if the input form of a `Char` can be matched by the `Regex("'\" * c * "\"*'")`, `c` being a valid `Char`, Julia parses it the same as `c`.

**Comment by pabloferz** [comment]
Actually, things like the following are valid too:

```julia
'I' == '\111"asdklfjq09423fu1'
```

The problem being the double quote and all that follows.

**Comment by pabloferz** [comment]
I would like to try to fix in order to familiarize myself more with the internals (at least the parser). But, I would need some pointers on where to begin.

@JeffBezanson

**Comment by JeffBezanson** [comment]
`parse-atom` in julia-parser.scm handles character literals. At a certain point, it calls `unescape-string`, which relies on its argument not containing unescaped quote characters. I think the easiest way to fix it is to only allow the forms `'"'` and '\"`, and give an error for any other input containing a double quote character.
