### ISSUE TITLE
Displaying a Dict in the REPL is frustrating

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#14684]
E.g.
````
julia> factor(prod(primes(30)))
Dict(7=>1,23=>1,13=>1,2=>1,3=>1,29=>1,19=>1,17=>1,11=>1,5=>1…)
```
The problem: my screen is wide enough to show much more than that.
Worse: this example shows actually all the factors, so the ellipsis is misleading in this case.

I personally prefer the old way of displaying a Dict (in a column), but at least let's use all the line width available (like the current displaying of ranges), and if possible a space after commas for readability. 

PS: IMHO `factor` was already frustrating by not showing the factors in sorted order, but now it is almost unusable as is in the REPL.

**Comment by StefanKarpinski** [comment]
I wholeheartedly agree.

**Comment by mbauman** [comment]
I think this was an unintentional side-effect of the IOContext work.  `Base.showdict` still formats as a column, it's just not getting called anymore.  I've not read up on the new way to hook into the display system, but I don't think it'll be hard to fix this.

The unnecessary ellipses is a separate bug.

**Comment by vtjnash** [comment]
it looks like i removed the special-case for displaying a Dict with `writemime` (in preparation for merging that with `show`) but `show` is setting the `compact` flag

**Comment by Ismael-VC** [comment]
:+1: for a space after commas, but not only in this case by the way, but in constructors and tuples also. A space should follow a comma in every case IMHO. What do you think?

**Comment by rfourquet** [comment]
@Ismael-VC yes I fully agree for a space after commas by default.

**Comment by bjarthur** [comment]
sorted `Dict` REPL output would be great too.  by key value.  i believe this feature was asked for once before, but i cannot find the issue.  would make a huge difference in readability.
