### ISSUE TITLE
behavior of type assertions on arguments

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#14682]
It seems that some Type assertions are ignored. For example the functions

```
function foo(x)
    x::Int64
    return x
end

function foo2(x::Float64)
    x::Int64
    return x
end
```

both can both be evaluated on x = 1.23 without error.

Julia Version 0.4.3-pre+6
Commit adffe19 (2015-12-11 00:38 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by nalimilan** [comment]
What do you mean?

**Comment by jw3126** [comment]
I would expect the behaviour 

```
function foo(x)
    x::Int64
    return x
end

foo(1.234)
```
throws an error like 

TypeError: typeassert: expected Int64, got Float64

but there is no such error.

**Comment by yuyichao** [comment]
I think this is a dup of https://github.com/JuliaLang/julia/issues/9765

**Comment by JeffBezanson** [comment]
`x::Int` in statement position is treated as a declaration, and affects all assignments to `x`. I'm not sure what it should do when `x` is an argument. Most consistent would be to insert an assignment `x=x` so the value gets converted to `Int`, but I'm not sure this is what people would expect.

**Comment by eschnett** [comment]
If you want the type assertion, you can put it into a tuple: `(x::Int,)`.

**Comment by anthonyclays** [comment]
The error does get through when you place the typeassert on the return expression:
```julia
function foo(x)
    x::Int
end
foo(1.234)
ERROR: TypeError: foo: in typeassert, expected Int64, got Float64
 in foo at none:3
 in eval at ./boot.jl:265
```

However, what I find far more worrying is the following inconsistency:
```julia
x = 1.234

function f(x)
    x::Int
    x
end
f(x) # no error

function f()
    x::Int
    x
end
f() # TypeError

function g()
    x = 1.234
    x::Int
    x
end
g() # InexactError
```

I would expect a typeassert to always simply do a typeassert - the current behaviour is very much unexpected in many cases.

**Comment by JeffBezanson** [comment]
`x::T` is not always a type assert, by design. In statement position, when applied to a local variable, it is a declaration that associates a type with a variable, such that assignments to the variable convert to that type. Otherwise it is a type assert. The first example you give is exactly the current issue, and it can be fixed for example by making it do the same thing as the third example.

**Comment by anthonyclays** [comment]
I see, so that's why the type error is thrown when you insert the `x=x`. Given that this behaviour only happens when x is a different type than the one you want to coerce to, won't this always cause type instability issues in functions?

```julia
julia> function f(x)
    x::Int
    x = x
    x
end

julia> @code_warntype f(1.6)
Variables:
  x::Any

Body:
  begin  # none, line 2: # none, line 3:
      x = (Base.box)(Int64,(Base.checked_fptosi)(Int64,x::Float64)) # none, line 4:
      return x::Int64
  end::Int64
```

**Comment by JeffBezanson** [comment]
To some extent yes, but this is a very innocuous type instability since all uses of `x` have fixed known types. Put differently, the type instability goes away completely in SSA form. However inserting assignments is something I'd rather avoid in general.

**Comment by StefanKarpinski** [comment]
> `x::T` is not always a type assert, by design. In statement position, when applied to a local variable, it is a declaration that associates a type with a variable, such that assignments to the variable convert to that type.

I have to say this is not my favorite feature since it's kind of confusing with type assertion meaning (not to mention the dispatch meaning). IIRC, we had at one point talked about limiting this meaning to `local` variable declarations. I'd still be in favor of that.

**Comment by johnmyleswhite** [comment]
FWIW, I personally find the polysemy of these type assertions a little hard to reason about.

For example, If I do `x = foo(y)::Float64`, where `foo` sometimes returns `Int` and sometimes returns `Float64`, I assume there's still boxing going on that's followed by a `convert` call.

**Comment by JeffBezanson** [comment]
Ok, I can get on board with limiting the declaration behavior to the syntax `local x::T`. Perhaps also `x::T = 0`?

@johnmyleswhite `foo(y)::Float64` will throw an error if `foo` does not return a `Float64`. Or maybe that is precisely the confusion you're describing?

**Comment by johnmyleswhite** [comment]
My belief that that fact wasn't true does indeed reflect me being confused about the feature.

**Comment by johnmyleswhite** [comment]
Just to be clear, that's a run-time error when you attempt to compile the method that contains that assertion? Or a run-time error that occurs when `foo` tries to return something that's not a `Float64`?

**Comment by JeffBezanson** [comment]
It's a run time error that occurs when `foo` returns a non-`Float64`.

**Comment by ma-laforge** [comment]
Along the same vein, I have noticed "type asserts" will get re-ordered in a function, causing unexpected behaviour.

For example, the following snippet calls a function returning either {`MyType`, or `nothing`}... so I check for `nothing` & `break`.  I then perform a type assert: `val::MyType` to make sure I am dealing with the correct data type.

```
type MyType
	x::Int
end

function getval(x::Int)
	if x>3
		return nothing
	end
	return MyType(x)
end

for i in 1:10
	val = getval(i)
	if nothing == val; break; end

	#odd... the following gets asserted before "if-statement" get to break out of loop:
	val::MyType #Assert type - does not work

	@show val
end
```

What's odd is that the type assert gets performed *before* the alogorithm gets to compare to `nothing` & `break` out of the loop.

The solution (similar to other people's suggestions above) is to re-assign:
`val = val::MyType #This assertion works, as expected`

NOTE: Using Julia  v0.4.2

**Comment by Keno** [comment]
"Type asserts" in void context or on the LHS of an assignment are typed variable declarations rather than actual type assertions

**Comment by ma-laforge** [comment]
I suppose the behaviour makes sense in that context.

...But I must admit the behaviour is very surprising for a language that is strongly imperative in nature (at least within the functions themselves)...

I might expect some of the module-level code to not strictly adhere to the order of my declarations/statements, but it is very surprising to see this at the function level.

...I suppose that might be because I am less familiar with less "mainstream" paradigms.

Thanks for your time.

**Comment by toivoh** [comment]
I think there's a case to be made for disallowing typed variable declarations that occur after the first use of a variable, since the result is quite confusing and there doesn't seem to be any real reason to allow it. 

Even better, why not require the use of `local` or `global` to make a typed variable declaration. That would be even less confusing.

**Comment by eschnett** [comment]
It gets even better.

This is a type assertion:
```Julia
function f()
x=1
x::Float64
end
```

And this is a declaration:
```Julia
function f()
x=1
x::Float64
x
end
```

**Comment by StefanKarpinski** [comment]
> why not require the use of `local` or `global` to make a typed variable declaration.

Yes. This – we should absolutely do this.

**Comment by jessymilare** [comment]
Seems to be fixed.

```
julia> function foo(x)
           x::Int64
           return x
       end
foo (generic function with 1 method)

julia> foo(1.234)
ERROR: TypeError: in typeassert, expected Int64, got a value of type Float64
Stacktrace:
 [1] foo(x::Float64)
   @ Main ./REPL[36]:2
 [2] top-level scope
   @ REPL[37]:1

julia> function foo2(x::Float64)
           x::Int64
           return x
       end
foo2 (generic function with 1 method)

julia> foo2(1.234)
ERROR: TypeError: in typeassert, expected Int64, got a value of type Float64
Stacktrace:
 [1] foo2(x::Float64)
   @ Main ./REPL[38]:2
 [2] top-level scope
   @ REPL[40]:1
```
