### ISSUE TITLE
Didn't find any test for det(F::BunchKaufman).

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [JuliaLang/julia#14697]
In this relevant test [file](https://github.com/JuliaLang/julia/blob/master/test/linalg/bunchkaufman.jl) there is no test for det.

**Comment by tkelman** [comment]
there are a few in symmetric.jl, ref https://github.com/JuliaLang/julia/pull/13166

**Comment by andreasnoack** [comment]
A way to check this is to look at the [coverage stats](https://coveralls.io/builds/4605335/source?filename=base%2Flinalg%2Fbunchkaufman.jl)

**Comment by sarvjeetsinghghotra** [comment]
@andreasnoack According to coverage stats its 100% covered. So shall I close this issue ?

**Comment by andreasnoack** [comment]
Yes, please close. I don't think there is an issue here.
