### ISSUE TITLE
subtypes of a type union

### ISSUE THREAD

**Issue by schmrlng** [JuliaLang/julia#14695]
Currently ```subtypes(::Union)``` is not defined in Base, but this seems to work and feels consistent with the existing documentation for ```subtypes(::DataType)```:
```julia
subtypes(x::Union) = sort(collect(x.types), by=string)
```
```subtypes(m::Module, x::Union)``` might be a bit more involved since I don't know a good way of checking what module a type is defined in. Would a PR with only the above version (+test) be acceptable?

**Comment by JeffBezanson** [comment]
This question is hard to answer, since the type system does not really give a meaning to enumerating subtypes. My interpretation of the current function is that it tells you which subtypes people have defined, i.e. all cases where somebody wrote `type A <: B ... end`. I guess you could do that recursively over the components of a Union, but I'm not sure what that would be for.

**Comment by schmrlng** [comment]
The utility of a ```subtypes(::Union)``` method could come up when trying to generate code to resolve a method ambiguity. This is sort of a contrived example:
```julia
julia> abstract A
       abstract A1 <: A
       type A1_1 <: A1 end
       type A1_2 <: A1 end
       type A2 <: A end
       abstract B
       type B1 <: B end

julia> f(::Union{A1_1, A2}, ::B1) = 1
       f(::Union{A1_1, A2}, ::B) = 2
       f(::A1, ::B1) = 3
       f(::A1, ::B) = 4
WARNING: New definition
    f(Main.A1, Main.B1) at none:3
is ambiguous with:
    f(Union{Main.A2, Main.A1_1}, Main.B) at none:2.
To fix, define
    f(Main.A1_1, Main.B1)
before the new definition.
f (generic function with 4 methods)
```
but if the type union is really large it might be convenient to do something like
```julia
for T in Union{A1_1, A2}.types
   @eval f(::$T, ::B1) = 1
   @eval f(::$T, ::B) = 2
end
```
(this had come up, e.g., in https://github.com/KristofferC/NearestNeighbors.jl/pull/19 with ```Distances.UnionMetrics``` and ```Distances.Metric``` being two types that intersect but neither contains the other).

Then again, a better way to programmatically resolve the ambiguity might be to define a method along the lines of  ```f(::typeintersect(Union..., OtherType), ...)```. I'll nix this issue in any case.

**Comment by jandehaan** [comment]
```julia
Base.collect(t::Union{Type, DataType, Union{}}) = _collect(t, [])
_collect(t::Type, list) = t<:Union{} ? push!(list, t) : _collect(t.b, push!(list, t.a))
_collect(t::Union{DataType,Core.TypeofBottom}, list) = push!(list, t)

julia> collect(Union{Int8, Int32, Int64})
3-element Array{Any,1}:
 Int8 
 Int32
 Int64
```

**Comment by rana** [comment]
Hi Jan,

Thank you for posting that code. 

Really helpful in resolving an issue.
