### ISSUE TITLE
Intermittent Travis build failure?

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#14705]
See [here](https://travis-ci.org/JuliaLang/julia/jobs/102882667) from #14703. The error is:

```
fatal error during bootstrap:

(parse-error "read: unexpected ']'")
```

Given this is happening while building inference0.ji and that PR only touched linalg code, I don't think my changes could cause this...

**Comment by yuyichao** [comment]
Thanks for openning an issue for this. IIRC, this happens mainly on travis linux although I've also seen it happen a few times on travis osx (before we disabled it). I haven't got any luck reproducing it locally. The time it starts to happen is around when we switch to the new travis setup.

**Comment by JeffBezanson** [comment]
Yes, I've seen this a few times too.

**Comment by Sacha0** [comment]
Likewise https://github.com/JuliaLang/julia/pull/14702#issuecomment-172287481

**Comment by tkelman** [comment]
Is anyone doing `make -j3 install` locally, with deps in place but none of src built yet? I think it's a race xondition while both release and debug system images are building in parallel.

**Comment by eschnett** [comment]
@tkelman I confirm this has been problem for some time; I have to do `make -j8; make -j8 install` to build. I haven't figured out where the conflict is, though -- sorry.

**Comment by yuyichao** [comment]
I guess it's probably `flisp.boot`... The first travis log linked even has a flisp warning about ignoring null characters.
