### ISSUE TITLE
Filtering DataFrame

### ISSUE THREAD

**Issue by iw2rmb** [JuliaLang/julia#14701]
There are two ways to filter DataFrame in case below:
1. `df = df[((df[:field].==1) | (df[:field].==2)), :]`
2. `df = df[(in(v, [1, 2]) for v in df[:field]), :]`
Second approach is slower but it's suitable for mutable set of values in condition.
Is there any syntax sugar I missed so I can get it as fast as 1st way but with some `in` construction?

**Comment by johnmyleswhite** [comment]
Questions like this are better suited for julia-users. GitHub is meant for bug reports and code changes.
