### ISSUE TITLE
Invalid BoundsError in Brim.jl test

### ISSUE THREAD

**Issue by blakejohnson** [JuliaLang/julia#14704]
I've been trying to reduce the Brim.jl test case failure that @tkelman noticed after the merge of the LLVM37 branch. To see it, launch julia with `--check-bounds=yes` and then run this script:

```julia
module MyTest

type Modular
    A::Array{Int64, 2}
    S::Array{Int64, 2}
end

function partition_lp(A::Array{Int64, 2})
    nc = size(A,2)
    S = eye(Int64, sum(size(A)))
    M = Modular(A, S)
    for node_bot in [1]
        lab_count = [1 0 0 0]
        for i = 1:length(lab_count)
            if lab_count[i] == 1
                M.S[node_bot+nc,i] = 1
                break
            end
        end
    end
    return M
end

A = [1 0; 0 1]
M = partition_lp(A)

end
```

Turns out that that this appeared prior to the LLVM37 merge. You can reproduce this on 0a00109 (before LLVM37 but after boundscheck changes) and on b727100 (before boundscheck changes).

**Comment by JeffBezanson** [comment]
That is truly bizarre!

**Comment by anthonyclays** [comment]
Runs fine with `--inline=no`.

**Comment by blakejohnson** [comment]
Here's a further simplification:

```julia
module MyTest

type Modular
    S::Array{Int64, 2}
end

function partition_lp()
    S = eye(Int64, 4)
    M = Modular(S)
    for node_bot in [1]
        lab_count = [1]
        for i = 1:length(lab_count)
            if lab_count[i] == 1
                M.S[node_bot,i] = 1
                break
            end
        end
    end
    return M
end

M = partition_lp()

end
```

There are *many* minor modifications that cause the `BoundsError` to go away. Such as removing the `break`, or replacing `for i = 1:length(lab_count)` with `for i = 1:1`.

**Comment by blakejohnson** [comment]
Does anyone have an example script they use with `git bisect` that I could modify to try to track down the source of this bug? I've spent quite a bit of time in lldb already with this and haven't really narrowed it down...

**Comment by vtjnash** [comment]
thus far tonight, @carnaval and I have managed to show this is a bug in LLVM's LSR. We're still working on finding the root cause.

**Comment by vtjnash** [comment]
patch created: http://reviews.llvm.org/D16505

**Comment by carnaval** [comment]
the real reason not to use 1-based indexing : nobody does

**Comment by blakejohnson** [comment]
Should we carry this as a local patch until it is merged upstream?

**Comment by ViralBShah** [comment]
Yeah - that seems like the right thing to do.
