### ISSUE TITLE
Enhance SIMD for vector not just range?

### ISSUE THREAD

**Issue by cwiese** [JuliaLang/julia#14712]
Would it be possible to get SIMD to work for vectors (not ranges with steps).   We accumulate multi-dimensional arrays with indexing into the dimension using a specific vector.  

Is there some specific reason we can not get SIMD to work for this case?

```
    in = rand(100,100)
s=0.0
for i in [8,11,34,35,36,37]
    @simd for j in [3,4,7,8,9]; 
              @inbounds s+=in[j,i]; 
             end
end
```

**Comment by yuyichao** [comment]
I don't think you can get simd for non uniform stride (and AFAIK we currently only support stride 1).
You can probably get simd by generating a mask from your index array but I don't think the code in this form can be vectorized.

Also note that your code is overriding a Base function `in`.

**Comment by Keno** [comment]
Could potentially be lowered to gather instructions though.

**Comment by cwiese** [comment]
Sorry, can you explain?  We are trying desperately to improve performance of huge aggregations like this.   Keno, I did not understand the comment above “be lowered to gather instructions”.

**Comment by yuyichao** [comment]
I guess gather instruction is possible. (Does llvm support it?).

IIRC, at least for AVX2 on haswell, the gather instruction doesn't perform better than scalar load though....

**Comment by Keno** [comment]
For a constant vector, the fastest way to do something like this with the recent instruction sets is with appropriately specialized [gather](https://software.intel.com/en-us/blogs/2011/06/13/haswell-new-instruction-descriptions-now-available) instructions followed by SIMD. I think llvm should actually be able to insert those if the loops are unrolled, but it might need some more codegen work.

**Comment by eschnett** [comment]
LLVM has SIMD vectors of pointers <http://blog.llvm.org/2011/12/llvm-31-vector-changes.html>. CUDA has respective machine instructions, as do Intel's AVX-512 instructions (in a way). Assuming that LLVM actually handles the code correctly, this code could trivially be vectorized similarly to:
```
svect = {0,0,0,0}
loopj:
jvect = {3,4,7,8}
svect = svect + in[ivect + i * stride]
...
s = sum(svect)
```
and should run efficiently on CUDA and with AVX-512.

**Comment by cwiese** [comment]
So is this the 4 way “accumulator” I see in core for sum?   I can do this without @SIMD just by adding 4 elements at a time?

**Comment by JeffBezanson** [comment]
It might also help to put the `@inbounds` on the outermost loop, so that it also removes bounds checks for iterating over the index vectors.

**Comment by eschnett** [comment]
The code I wrote is just pseudo-code; it is neither Julia nor will it compile.

**Comment by cwiese** [comment]
But is the concept the same as what is being attempted here:

https://github.com/JuliaLang/julia/commit/a1507d5cb8378e8cb4351f8c278d85f549457719 <https://github.com/JuliaLang/julia/commit/a1507d5cb8378e8cb4351f8c278d85f549457719>

**Comment by eschnett** [comment]
It's similar. The example you showed uses loop unrolling. SIMD vectorization uses loop unrolling as first stage; later, the four scalar instructions are combined into a single vector instruction. Ideally, the compiler (here: LLVM) does this automatically, "encouraged" by an `@simd` annotation.

What I was trying to show is that the array indexing operation can be expressed in LLVM's vector notation. That is, LLVM's vectorizer could/should/might take the code you showed originally, and then create vectorized code from this. I don't know whether it does on a regular CPU (probably not), nor do I know whether the code that Julia passes to LLVM is structure in such a way to make this possible.

My main point was to refute the assumption "everybody knows that irregular array indexing cannot be vectorized". I don't know whether a simple summation would benefit from vectorization (probably not, and certainly not on current mainstream CPUs), but it is possible in principle, and more complex algorithms will likely have performance benefits from vectorizing array indexing on future CPUs.

So: "Can we get SIMD to work for this example?": Yes, we should. "Will it improve performance for this example?": Probably not. "Will LLVM actually emit SIMD instructions?": Probably not.

**Comment by cwiese** [comment]
Thank you much for that very clarifying response.

**Comment by gbaraldi** [comment]
I'm not sure how good the code generated her is, but currently this code SIMDs just fine with gather instructions and whatnot
```julia
function foo()
        in = rand(100,100)
       s=0.0
       for i in [8,11,34,35,36,37]
           @simd for j in [3,4,7,8,9]; 
                     @inbounds s+=in[j,i]; 
                    end
       end
       s
       end
```
```llvm
 %37 = insertelement <4 x i64> poison, i64 %.scalar, i64 0
  %38 = shufflevector <4 x i64> %37, <4 x i64> poison, <4 x i32> zeroinitializer
  %39 = add <4 x i64> %38, %wide.load
  %40 = add <4 x i64> %38, %wide.load109
  %41 = add <4 x i64> %38, %wide.load110
  %42 = add <4 x i64> %38, %wide.load111
  %43 = getelementptr inbounds double, double* %.data5892, <4 x i64> %39
  %44 = getelementptr inbounds double, double* %.data5892, <4 x i64> %40
  %45 = getelementptr inbounds double, double* %.data5892, <4 x i64> %41
  %46 = getelementptr inbounds double, double* %.data5892, <4 x i64> %42
  %wide.masked.gather = call <4 x double> @llvm.masked.gather.v4f64.v4p0f64(<4 x double*> %43, i32 8, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, <4 x double> undef)
  %wide.masked.gather118 = call <4 x double> @llvm.masked.gather.v4f64.v4p0f64(<4 x double*> %44, i32 8, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, <4 x double> undef)
  %wide.masked.gather119 = call <4 x double> @llvm.masked.gather.v4f64.v4p0f64(<4 x double*> %45, i32 8, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, <4 x double> undef)
  %wide.masked.gather120 = call <4 x double> @llvm.masked.gather.v4f64.v4p0f64(<4 x double*> %46, i32 8, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, <4 x double> undef)
  %47 = fadd reassoc contract <4 x double> %vec.phi, %wide.masked.gather
  %48 = fadd reassoc contract <4 x double> %vec.phi106, %wide.masked.gather118
  %49 = fadd reassoc contract <4 x double> %vec.phi107, %wide.masked.gather119
  %50 = fadd reassoc contract <4 x double> %vec.phi108, %wide.masked.gather120
```
