### ISSUE TITLE
LoadError: no promotion exists for Complex{T<:Real} and Int64

### ISSUE THREAD

**Issue by iagoba** [JuliaLang/julia#14715]
I think there are more inconsistencies of this type

Reproduce:
1.  Use the typed constructor for array `Complex[ ]`
2.  Try to multiply any other array such as
```
Complex[1 2]*[3, 4]
```
You will get the error
```
LoadError: no promotion exists for Complex{T<:Real} and Int64
```

There is a workaround:
```
Complex[1 2]*Number[3, 4]
```
OR TRIVIAL
```
Complex[1 2]*Complex[3, 4]
```

**Comment by JeffBezanson** [comment]
I don't recommend using the `Complex` type; you should use a more specific type like `Complex64` or `Complex128` (see also #8142).
