### ISSUE TITLE
find not defined for SparseVectors

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaLang/julia#14717]
I'm using both sparse and full representations of adjacency matrices. As an example:

``` julia
mx = bitrand(10,10)
spmx = sprandbool(10,10,0.5)
```

In version `0.4` I could get the neighbors of a vertex by just running

``` julia
find(mx[:,1])
find(spmx[:,1])
```

Running `spmx[:,1]` on `0.4` returned a `SparseMatrix`, while in `0.5` it returns a `SparseVector`. `find` isn't defined on `SparseVector` in `0.5`. This breaks the interface common to `AbstractArray{Bool, 2}` and `SparseMatrixCSC{Bool,Int}`. Could we have `find` return the `nzind` field for `SparseVector`?

**Comment by tkelman** [comment]
There's a question of how much work find should do about any stored zeros. For now I'd do the same as SparseMatrixCSC in that respect.

**Comment by KristofferC** [comment]
`find` works in `SparseVector` now.
