### ISSUE TITLE
InexactError on Win32

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#14729]
Julia 4.3 Win64 and Win32

| statement | Win64 | Win32 |
| :-- | :-- | :-- |
| UInt32(0)-Int32(-1) | 1::Int64 | InexactError() |
| UInt64(0)-Int64(-1) | InexactError() | InexactError() |

due to `promote_type(Uint32, Int32)` returning `Int64` on `Win64` while it returns an unsigned for the other cases.
This seems to be inconsistent...

**Comment by SimonDanisch** [comment]
JuliaIO/MeshIO.jl#14

**Comment by JeffBezanson** [comment]
I think this was intentional. The idea was to avoid automatically promoting beyond the system word size. The alternative is to pick UInt32, as we pick UInt64 for UInt64-Int64. I definitely see the argument for making program behavior less platform dependent.

**Comment by JeffBezanson** [comment]
Notably, this is the only function in int.jl where behavior changes based on `WORD_SIZE`.

**Comment by tkelman** [comment]
I'm increasingly leaning towards accepting the slowdown on 32 bit and make `Int` 64 bit there just so code at least works more or less the same on 32 bit. Somewhere between a quarter and a third of Windows downloads are still on 32 bit, but most people aren't testing their code there..

**Comment by nalimilan** [comment]
> most people aren't testing their code there..

At least AppVeyor runs on 32-bit Windows (contrary to Travis CI).

**Comment by tkelman** [comment]
We could look into adding a Travis config that would download the 32 bit linux binaries and run them despite being on a 64 bit vm, but it would likely require a fair amount of extra messing with the apt packages addon to get the right multiarch versions of everything installed for things like bindeps to work properly.

**Comment by SimonDanisch** [comment]
...and most people don't use AppVeyor ;)
@tkelman, I was thinking the same. If you're on x32, it's unlikely that you're after the cutting edge. But then again, maybe you need the last bit of performance because your hardware is really weak...I don't know, but it would be definitely nice to make x32 more similar in behaviour.

**Comment by tkelman** [comment]
A pretty small number of people are still using 32 bit OSes. The main legitimate use case for needing to run 32 bit Julia is if you need to ccall (or using Cxx.jl perhaps) into a proprietary library where you only have access to 32 bit binaries. I think that's an important enough use case that we should still keep supporting 32 bit builds for as long as it's not seriously impeding development. I think making compatibility and language behavior more predictable on platforms not many people are testing on would be a little more beneficial than trying to avoid larger-than-word-size integers by default for performance reasons.

**Comment by aviks** [comment]
I would overall support this change, but would note that there is a lot of `ccall` code out there that assumes that the system pointer and Julia `Int` are of the same size. So while beneficial, this change won't be costless.

**Comment by PallHaraldsson** [comment]
If you're going to change this, needs it not be done before Julia 1.0?

**Comment by StefanKarpinski** [comment]
I don't think we do this anywhere anymore: the new behavior should be that the result is always the type of the larger input type and if they're the same size then unsigned wins. Someone on a 32-bit machine should verify that this is the case.

**Comment by notinaboat** [comment]
@StefanKarpinski, the subtraction example seems to behave the same on x86_64 vs ARMv6.

However, I have a case where code fails to run on 32-bit ARM because `UInt32(7) | 0` returns unsigned (whereas on x86_64 it returns signed).

Is this related? Is it a bug or a feature?

I wouldn't be surprised if I end up with different Int sizes across 32/64 bit machines, but it is surprising that a result is signed on one platform and unsigned on another.

```julia
julia> UInt32(0)-Int32(-1)                    |  julia> UInt32(0)-Int32(-1)
0x00000001                                    |  0x00000001
                                              |  
julia> UInt64(0)-Int64(-1)                    |  julia> UInt64(0)-Int64(-1)
0x0000000000000001                            |  0x0000000000000001
                                              |  
julia> typeof(0)                              |  julia> typeof(0)
Int32                                         |  Int64
                                              |  
julia> typeof(UInt32(7)|0)                    |  julia> typeof(UInt32(7)|0)
UInt32                                        |  Int64
                                              |  
julia> typeof(promote(UInt32(7), 0))          |  julia> typeof(promote(UInt32(7), 0))
Tuple{UInt32,UInt32}                          |  Tuple{Int64,Int64}
                                              |  
julia> versioninfo()                          |  julia> versioninfo()
Julia Version 1.5.2                           |  Julia Version 1.5.2
Commit 539f3ce* (2020-09-23 23:17 UTC)        |  Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:                                |  Platform Info:
  OS: Linux (arm-linux-gnueabihf)             |    OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: ARMv6-compatible processor rev 7 (v6l) |    CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 32                               |    WORD_SIZE: 64
  LIBM: libm                                  |    LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, arm1176jz-s)   |    LLVM: libLLVM-9.0.1 (ORCJIT, skylake)         
```

(My issue arrises from a MethodError on armv6 because [this code in TextUserInterfaces.jl](https://github.com/ronisbr/TextUserInterfaces.jl/blob/master/src/colors.jl#L67-L74) returns unsigned on armv6 (vs signed on x86_64).

**Comment by StefanKarpinski** [comment]
The rules are set in stone now for 1.x: mixed type integer operations promote to the larger argument type; if the arguments are the same size but one is signed and the other is unsigned, then the result is unsigned. Yes, this means that `Int` literals combined with `UInt32` values produce unsigned values on 32-bit platforms and `Int64` values on 64-bit platforms, but it was unavoidable that there be some platform dependency here, the only option is to push it around to a different place.

**Comment by notinaboat** [comment]
Thanks @StefanKarpinski,
I've started reading through open issues to get an idea of where things are at for 32-bit systems (I don't want to open new issues for stuff that has been discussed already).
It would apply "Label: [https://github.com/JuliaLang/julia/labels/32-bit](32-bit)" as I go, but I guess I need some GitHub permission to do that in this repo. Is that a thing that can be done?

**Comment by StefanKarpinski** [comment]
This issue already has the 32-bit label. Are you asking about applying it to some other issues?

**Comment by notinaboat** [comment]
Yep, I just though that if I am going to make a pass though the old issues searching for 32-bit relevant stuff, I may as well apply the tag as I go...

**Comment by StefanKarpinski** [comment]
Sure. I can give you triage permissions so that you can add labels.

**Comment by StefanKarpinski** [comment]
Done. You should be able to add/remove labels and close issues.
