### ISSUE TITLE
Type weirdness in division of array by scalar

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#14725]
Doing

```Julia
eltype(Vector{Number}([1, 2, 3]) + 1)
eltype(Vector{Number}([1, 2, 3]) - 1)
eltype(Vector{Number}([1, 2, 3]) * 1)
eltype(Vector{Number}([1, 2, 3]) / 1)
```

I would expect the result to be `Number` in all four cases. Indeed, this has been the case prior to dc12cc6a62e34fad08aa244c0decf52d910f0723 aka 0.4.0-dev+3331. Now however, only the first three yield `Number`, while the last one - division - gives `ANY`. Is there a good reason for this inconsistency or is this a bug?

**Comment by martinholters** [comment]
Taking a closer look at dc12cc6a62e34fad08aa244c0decf52d910f0723, why are `:./` and `:.\` removed from base/array.jl:783 ? (The corresponding code has in the meantime moved to base/arraymath.jl.) There is a quite extensive list of binary operators (even including `div`!), so why should normal division be excluded?

**Comment by nalimilan** [comment]
CC @timholy

**Comment by JeffBezanson** [comment]
@timholy Do you remember what the motivation was here?

**Comment by timholy** [comment]
Sorry I didn't notice this earlier.

It looked to me like that case should have been handled by lines 732-735 in that diff, but you're right that the mechanism is different. Now that we use `promote_op`, we could probably get rid of that whole section of code.
