### ISSUE TITLE
Linear algebra test coverage for SubArray

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#14732]
Below is the list of linear algebra test files that we'll need to extend with `SubArray` tests. Please update the list if `SubArray`s are already covered (systematically) for the file
- [ ] `arnoldi.jl`
- [x] `bidiag.jl`
- [x] `bunchkaufman.jl`
- [x] `cholesky.jl`
- [ ] `dense.jl`
- [x] `diagonal.jl`
- [x] `eigen.jl`
- [x] `generic.jl` (see #15145)
- [x] `givens.jl`
- [ ] `lapack.jl`
- [x] `lu.jl`
- [x] `lq.jl`
- [x] `matmul.jl`
- [ ] `pinv.jl`
- [x] `qr.jl`
- [x] `schur.jl`
- [ ] `special.jl`
- [x] `svd.jl`
- [ ] `symmetric.jl`
- [ ] `triangular.jl`
- [x] `tridiag.jl`
- [x] `uniformscaling.jl` (see #14731)

**Comment by andreasnoack** [comment]
@kshyatt Are `tridiagonal`, `bidiagonal` and `diagonal` now covered? If so, please update the list.

**Comment by pkofod** [comment]
just to be 100% sure, this is simple to make sure that the functions return the same thing / work even if it's a `SubArray` and not an array?

**Comment by kshyatt** [comment]
Yeah, the idea is to make sure `Diagonal {*, +, -, /} SubArray` still works.

**Comment by pkofod** [comment]
`svd.jl` should be covered by #15314 .

**Comment by andreasnoack** [comment]
Great. Top post is now updated.

**Comment by pkofod** [comment]
I'll probably grab some more the coming days, and pile them in a PR with separate commits. I assume none are taken?

**Comment by tkelman** [comment]
Nope, go nuts. Keep em coming @pkofod, big fan of your recent contributions.

**Comment by pkofod** [comment]
Most of `arnoldi.jl` is sparse matrices. Should these just be ignored here? Methods don't seem to be defined for sparse matrices (#15355 ) possibly because it will rarely be a good idea to operate on views of sparse matrices.

**Comment by tkelman** [comment]
I don't think this is intentional, it's just that few if any methods for working with views of sparse matrices have been written yet.

**Comment by pkofod** [comment]
As pointed out by Tim Holy at #15354, it works in  #15367

**Comment by tkelman** [comment]
Though if it's dispatching to a generic fallback, it's likely quite slow and not taking advantage of sparsity, so optimized methods do still need to be written to get decent performance.

**Comment by pkofod** [comment]
Yes I realize that, I was only thinking about: "does it work?". If it is expected to work, I figured it should be tested. Even if it would probably be stupid for most users to do it currently.

**Comment by pkofod** [comment]
Regarding this issue... Is it "acceptable" to continue down this road right now, or will a PR that increases test times not be merged anyway? (I'm thinking about the whole CI discussion...) Also, I think there are some completed files that are not ticked off (matmul, eigen, schur, bunchkaufman).

**Comment by andreasnoack** [comment]
I don't think we should hold back on adding tests here but @tkelman can tell if we are too close to the limit. Recently, the triangular tests got faster after avoiding many calls to `generic_matmatmul!` so maybe there is some extra room. It might be possible to further reduce the number of times `generic_matmatmul!` is compiled or reorganize that function to become cheaper to compile.

**Comment by tkelman** [comment]
The time per CI run has gotten about 20 minutes faster over the last few months, which is great work by the compiler gurus. But we are having more frequent freezes and it's generally busy with a lot of builds per day adding up to a usually-long queue.

**Comment by kshyatt** [comment]
I think `lq.jl` is actually covered? Since I pulled those tests from `qr.jl` it may be as well. See [here](https://github.com/JuliaLang/julia/blob/master/test/linalg/qr.jl#L44).

**Comment by ViralBShah** [comment]
@kshyatt Are we now in a good place, that we can close this?
