### ISSUE TITLE
DL_LOAD_PATH error on Mac OS 10.9.5

### ISSUE THREAD

**Issue by brenhinkeller** [JuliaLang/julia#14746]
I'm not sure if this issue is caused by some quirk of my system and path configuration or is more general, but I have run into an error when trying to use a new version of Julia on Mac OS 10.9.5. 

Julia v0.3.11 and v0.3.12 (possibly earlier versions as well) run without error for me in both command-line and IDE forms. However, when trying to use a newer version (I have tried both julia 0.4.3 and the current nightly v0.5.0-275c7e8929), I run into the following error:

`ERROR: LoadError: UndefVarError: DL_LOAD_PATH not defined`
 `in include at /opt/local/lib/julia/sys.dylib`
 `in include_from_node1 at /opt/local/lib/julia/sys.dylib`
 `in try_include at /opt/local/lib/julia/sys.dylib`
 `in load_juliarc at /opt/local/lib/julia/sys.dylib`
 `in process_options at /opt/local/lib/julia/sys.dylib`
` in _start at /opt/local/lib/julia/sys.dylib`
`while loading /Users/myusername/.juliarc.jl, in expression starting on line 1`

This seems to affect the julia/juno bundle, the julia stand-alone executable, and the macports command-line version on my system.

In v0.3.12, there seems to be no problem with my DL_LOAD_PATH, which is apparently set to the following:
`julia> Sys.DL_LOAD_PATH`
`3-element Array{Union(UTF8String,ASCIIString),1}:`
` "@executable_path/../lib/julia"`
` "@executable_path/../lib"      `
` "/opt/local/lib"   `

**Comment by tomaklutfu** [comment]
You should use new dynamic loading module Libdl. Libdl.DL_LOADPATH should work.

**Comment by brenhinkeller** [comment]
Rookie question: how exactly do I do that?

**Comment by tomaklutfu** [comment]
Look for Sys.DL_LOAD_PATH in file /Users/myusername/.juliarc.jl and replace with Libdl.DL_LOAD_PATH . You may have different compatibility problems in julia 0.4.x if .juliarc.jl is writen for julia 0.3.x . But this issue looks more like help you can get from julia-user google group or stackoverflow question maybe.

**Comment by brenhinkeller** [comment]
Ah, I see - that worked. Thank you!
