### ISSUE TITLE
Intermittent deadlock in readbytes(open(`echo $text`)) on Linux ?

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#14747]
[This test](https://github.com/JuliaLang/julia/blob/67f92564a3b1d82c3520a499923fbc18e455aca7/test/read.jl#L99) from https://github.com/JuliaLang/julia/pull/14699 runs ok on OSX but [sometimes passes and sometimes fails](https://travis-ci.org/JuliaLang/julia/builds/103603929) on Linux/Travis.

The test case covers a number of combinations of `::IO` subtypes and data sizes.

In [this test run](https://travis-ci.org/JuliaLang/julia/jobs/103603930#L1865) the test seems to [hang in `readbytes`](https://github.com/JuliaLang/julia/blob/67f92564a3b1d82c3520a499923fbc18e455aca7/test/read.jl#L175) in the following case...

``` julia
io = (text) -> open(`echo -n $text`)[1]
...
text = UTF8String(['A' + i % 52 for i in 1:Base.SZ_UNBUFFERED_IO])
...
@test readbytes(io(text)) == Vector{UInt8}(text)
```

Has anyone else experianced hangs around `PipeEndpoint` or `open(::Command)` ?

**Comment by samoconnor** [comment]
Related ? #15090

**Comment by vtjnash** [comment]
dup ~#22832~, but we should enable this test before closing
