### ISSUE TITLE
 unable to connect to github.com

### ISSUE THREAD

**Issue by manichem** [JuliaLang/julia#14762]
I recently installed Julia and running this command Pkg.add(''Ipopt'') but the execution stops giving a fatal error message as:

fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=No error

ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in run at process.jl:531

**Comment by ivarne** [comment]
Seems like a dup of https://github.com/JuliaLang/julia/issues/12583 if you are behind a firewall that blocks git traffic. The recommendation seems to be to run the following in a command prompt, to make git rewrite urls.

    git config --global url."https://".insteadOf git://

If you run the latest master, you might also try:

http://julia.readthedocs.org/en/latest/stdlib/pkg/#Base.Pkg.setprotocol!
