### ISSUE TITLE
release-0.4 make error

### ISSUE THREAD

**Issue by ryanpdwyer** [JuliaLang/julia#14789]
On OSX 10.9.5, `make` on the current release-0.4 branch fails with the error,

    ./ccall.cpp:1271:22: error: use of undeclared identifier 'sret_val'
            result = sret_val.V;
                      ^
    ./ccall.cpp:1274:9: error: use of undeclared identifier 'sretboxed'
        sretboxed = sret_val.isboxed;
                      ^
    ./ccall.cpp:1274:21: error: use of undeclared identifier 'sret_val'
        sretboxed = sret_val.isboxed;
                      ^

which appears to be caused by this section of `ccall.cpp`,

```cxx
    // First, if the ABI requires us to provide the space for the return
    // argument, allocate the box and store that as the first argument type
    if (sret) {
        result = emit_new_struct(rt,1,NULL,ctx); // TODO: is it valid to be creating an incomplete type this way?
        assert(result != NULL && "Type was not concrete");
        if (!result->getType()->isPointerTy()) {
            Value *mem = emit_static_alloca(lrt, ctx);
            builder.CreateStore(result, mem);
            result = mem;
        }
        else {
            // XXX: result needs a GC root here if result->getType() == T_pjlvalue
            result = sret_val.V;
        }
        argvals[0] = builder.CreateBitCast(result, fargt_sig.at(0));
        sretboxed = sret_val.isboxed;
    }
```

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/14194#issuecomment-174488834 maybe

**Comment by nalimilan** [comment]
Thanks. You can use the git/GitHub "blame" feature to find out what commit added this line: https://github.com/JuliaLang/julia/commit/e5977581262d34fbcf48424fa1eeddd60612d61a

Looks like a backport issue, as this variable isn't defined on release-0.4, but it is on master:
https://github.com/JuliaLang/julia/blob/66fb8588b6aad59f3ef595b7540cad574bf85be7/src/ccall.cpp#L1230

CC: @maleadt (author), @ViralBShah (committer), @tkelman (Master of backports)

**Comment by Fedster** [comment]
I have the same issue (the exact same) on OS X 10.11.3.

**Comment by tkelman** [comment]
A whole bunch of commits were pushed to the release branch that should not have been. Until they get reverted, check out v0.4.3.
