### ISSUE TITLE
Generic vecdot requires dot be implemented for scalars

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#14781]
The definition of `vecdot` (and its documentation) requires that user types define `dot` for scalars, instead of `*` like I would have guessed:
https://github.com/JuliaLang/julia/blob/70477b7e5cec35910237c3277ef004b31c90ea3f/base/linalg/generic.jl#L278-L287

I'm not sure what case this is expected to handle, but it increases the burden on people defining custom types, as in addition to multiplication (e.g. `*(MyType,Number)` and `*(Number,MyType)`) users must also define an analogous `dot` just for this case (and in the case of JuMP, where we have multiple types, all the other interaction terms).

I'm wondering if its too general. If the current functionality is desirable, then perhaps a generic `dot(x::Any,y::Any) = x*y` could be defined as a fallback?

**Comment by andreasnoack** [comment]
Is `YourType <: Number`. It's difficult to think of general behavior for `Any` so would it work if we had `dot(x::Number,y::Numner)=x'y`? It would then be similar to this definition https://github.com/JuliaLang/julia/blob/70477b7e5cec35910237c3277ef004b31c90ea3f/base/linalg/generic.jl#L214 for `norm`.

**Comment by tkelman** [comment]
JuMP types aren't subtypes of number AIUI, they're numberlike containers but inheriting from Number would result in too many behaviors that aren't all wanted. There have been other issues that mentioned having an AbstractScalar above Number in the hierarchy.

**Comment by IainNZ** [comment]
Yes not a number.
I mean, I'm a little confused about what `vecdot` is supposed to be doing. I thought it was Euclidean dot product, which would be a sum of multiplied scalars, but it seems that its coded for something much more general. Is there an example use-case for this more general "recursive" definition?

**Comment by andreasnoack** [comment]
See https://groups.google.com/forum/#!topic/julia-users/cPZnKPK4Hbw, https://github.com/JuliaLang/julia/pull/6057, and https://github.com/JuliaLang/julia/pull/11067 for the origins of this behavior. @stevengj has determined how these functions work so we should hear him about ideas here.

**Comment by stevengj** [comment]
`dot(x::Any,y::Any) = x*y` is incorrect as a fallback for non-real types.  `vecdot` really needs an inner product, which is in general distinct from multiplication.

**Comment by IainNZ** [comment]
Tidying up old issues/PRs.
