### ISSUE TITLE
Clarify `svd` documentation

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14788]
The `svd(A, B)` documentation (and similarly the `svdfact` documentation) currently say
```
  svd(A, B) -> U, V, Q, D1, D2, R0

  Wrapper around svdfact extracting all parts the factorization to a tuple.
  Direct use of svdfact is therefore generally more efficient. The function
  returns the generalized SVD of A and B, returning U, V, Q, D1, D2, and R0
  such that A = U*D1*R0*Q' and B = V*D2*R0*Q'.
```

I'm familiar with SVDs in the mathematical sense, but not with Julia's implementation. From convention, I know what `U` and `V` are, but I don't know the other symbols (`Q`, `D1`, `D2`, and `R0`). I assume that at least one of these is a vector (i.e. a diagonal matrix). I also assume that some additional conditions hold between these quantities.

If you're familiar with SVDs, could you update the documentation to have more detail? For example, a description in the style of `svd(A)` would already be sufficient for me.

**Comment by jiahao** [comment]
The notation is for the generalized SVD as provided by LAPACK.
