### ISSUE TITLE
Segfault in complex array comprehensions

### ISSUE THREAD

**Issue by ahonkela** [JuliaLang/julia#14786]
The below code snippet segfaults Julia 0.4.x, both on Mac (0.4.2 from Homebrew) and on Linux (self-built release-0.4 branch):

```jl
N = 51

function f(repeats)
    return zeros(repeats, N)
end

results = [((x, y), f(100)) for x in 1:2, y in 1:2]
```

Backtrace and full version info are at:
https://gist.github.com/ahonkela/516a7e6b530795c4ade1

Antti

**Comment by Varanas** [comment]
Interestingly enough, declaring `N` as `const N = 51` works fine.

**Comment by mauro3** [comment]
Crashes my 0.4.3 as well  (although with different backtrace). Works fine on 0.3.12

**Comment by yuyichao** [comment]
Somehow the type of `results` is not a concrete type ....

```
(gdb) p jl_(jl_typeof(args[0]))
Array{Tuple{Tuple{Int64, Int64}, Array{#T<:Any, N<:Any}}, 2}
```

Probably related to https://github.com/JuliaLang/julia/issues/7258

**Comment by yuyichao** [comment]
This case seems to be fixed now due to improvement in type inference.

**Comment by tkelman** [comment]
add the test to close then?

**Comment by ahonkela** [comment]
Just to verify: works for me too now on current master.

I did not check current 0.4 series. If not, it would be great if the fix can be backported there too.

**Comment by yuyichao** [comment]
The issue is hidden due to unrelated changes (either type inference or definition of `zeros`, neither is likely backportable). The real bug is still not fixed (i.e. #16420).

**Comment by vtjnash** [comment]
rendered irrelevant by jb/comprehensions

**Comment by tkelman** [comment]
still may as well add that test?
