### ISSUE TITLE
@doc with concatenated strings

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#14794]
`@doc` works for me with a plain string, but not with concatenated strings:

```
julia> @doc "foo()" foo()=1
foo (generic function with 1 method)

help?> foo
search: foo floor ifloor pointer_from_objref OverflowError RoundFromZero

  foo()

julia> @doc string("bar","()") bar()=2
bar (generic function with 1 method)

help?> bar
search: bar baremodule SubArray GlobalRef clipboard BitArray backtrace

1-element Array{ASCIIString,1}:
 "bar()"
```

this on a 0-day old master, and 0.4.2.

my use case is to generate docs programmatically:

```
for jfunc in (:foo, :bar)
  @eval function $jfunc()
    ...
  end

  @eval @doc """
  `"""*string($jfunc)*"""`

  implement this method
  """ $jfunc
end
```

is there a better way or workaround?  thanks.

**Comment by MichaelHatherly** [comment]
Using string interpolation should work fine I think. Something like:

```
julia> for jfunc in (:foo, :bar)
         @eval function $jfunc()
           
         end

         @eval @doc """
         `$($jfunc)`

         implement this method
         """ $jfunc
       end
```

(Note the need for two `$`s.)

**Comment by vtjnash** [comment]
you shouldn't depend on string interpolation in doc strings – that misfeature needs to be removed.

instead, for your example, use something like the following:
```
@eval @doc $(string("*", jfunc, """*

  implement this method
  """)) $jfunc
```

**Comment by bjarthur** [comment]
thanks for the workarounds.  i'll leave this issue open as it seems `@doc` should work with concatenated strings.

**Comment by omus** [comment]
I think removing string interpolation in docstrings would be a mistake.
```julia
@eval begin
    @doc """
        $($jfunc)() -> Int
    
    Detailed documentation on $($jfunc).
    """ $jfunc
end
```
vs.
```julia
@eval begin
    @doc (
    "`" * string($jfunc) * "() -> Int`" *
    "\n" *
    "Detailed documentation on " * string($jfunc))
    $jfunc
end
```

**Comment by eschnett** [comment]
@omus You could first assign a regular string to a let-bound variable, then use it with `@doc`. Also -- even if `@doc` doesn't interpolate, the `@eval` still would?

**Comment by omus** [comment]
@eschnett makes sense. 

I can get behind removing string interpolation from docstrings as long as it is still allowed within triple-quoted strings. That would allow still allow generated documentation to work while removing pain points with unintentional interpolation. I think the proposed [`doc!`](https://github.com/JuliaLang/julia/issues/15360#issuecomment-192598710) function may be the solution here.

**Comment by mbauman** [comment]
The initial example now works:

```Julia
julia> @doc string("bar","()") bar()=2
bar

help?> bar
search: bar baremodule SubArray GlobalRef clipboard BitArray backtrace BitMatrix catch_backtrace AbstractRange AbstractArray AbstractIrrational AbstractString AbstractChar AbstractMatrix

  bar()
```
