### ISSUE TITLE
Inconsistent behaviour of string interpolation in "$a" and "1$a"

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#14796]
```{julia}
immutable A
    x::Int
end
Base.show(io::IO, a::A) = print(io, "show A $(a.x)")
Base.string(a::A) = string("string A $(a.x)")
a = A(3)

# This calls string
show("$a")
"string A 3"

# This calls show.
show("33$a")
"33show A 3"
```

**Comment by JeffBezanson** [comment]
`string` is supposed to be consistent with calling `print` (which defaults to `show`). In fact, interpolation always calls `string`, but the implementation of `string` for multiple arguments works by `print`ing each argument to a buffer. So types are actually not expected to implement `string` unless there is a faster implementation than the default of calling `print`. So I don't think we need to change anything here.

**Comment by colinfang** [comment]
Thank you, I see your point.
