### ISSUE TITLE
Error message for type parameter is out-of-date

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#14809]
I get the following Error:

``` julia
julia> Val{convert(Float32,NaN)}
Val{NaN32}
julia> Val{convert(BigFloat,NaN)}
ERROR: TypeError: Val: in parameter, expected Int64, got BigFloat
```

**Comment by toivoh** [comment]
The error message could be improved, but in fact the allowable types for type parameters is pretty restricted. It used to be just types and ints, now I think also bitstype values and tuples of allowed values are allowed.

**Comment by gdkrmr** [comment]
i see, this is not a simple fix

**Comment by ivarne** [comment]
It is a simple fix to modify [`valid_type_param`](https://github.com/JuliaLang/julia/blob/63a1c81990f891cd2aa9707b7852b90e97495565/src/jltypes.c#L1690), to check for BigFloat. The question is rather if this is something we really want. Why do you need this?

The error message is created [here](https://github.com/JuliaLang/julia/blob/63a1c81990f891cd2aa9707b7852b90e97495565/src/jltypes.c#L1737), and an improvement would be a nice contribution for to get started.

**Comment by gdkrmr** [comment]
I wanted a function that handled `NaN`s differently than other values and
```julia
foo{U}(x, ::Type{Val{U}}) = do_something(x)
foo(x, ::Type{Val{NaN}}) = do_something_else(x)
```
works only for `Float64`, I tried to make this for all types of `NaN` (`subtypes(AbstractFloat)`), but I won't really need it for `BigFloat`.

```julia
for f in subtypes(AbstractFloat)
    na = convert(f,NaN)
    @eval foo(x::$f, ::Type{Val{$na}}) = do_something_else(x)
end
```

**Comment by yuyichao** [comment]
This is the wrong way to do what you want. Use a normal branch instead. Never use dispatch for simple runtime logic.

**Comment by StefanKarpinski** [comment]
Yeah, that's a fun party trick but not what you want to do for real code. Just use a branch on `isnan(x)`.

**Comment by gdkrmr** [comment]
You want to see what the party trick is good for, compare the timings, it beats branching by a factor of ~3 on my computer.
What else would I use value types for?

```julia 
isNA(x,m::Val{NaN}) = isnan(x)
isNA(x,::Type{Val{NaN}}) = isnan(x)
isNA{T}(x,m::Val{T}) = x == T
isNA{T}(x,::Type{Val{T}}) = x == T
isNA(x,NAval) = isnan(NAval) ? isnan(x) : x == NAval

function allNA(x,m)
    for v in x
        isNA(v,m) || return false
    end
    return true
end

tmp = fill(NaN,10_000_000)
tmp2 = fill(-9999.0,10_000_000)

# The manual recommends this way:
@time allNA(tmp,Val{NaN})
@time allNA(tmp2,Val{-9999.0})
# 30-50x faster than the recommended way:
@time allNA(tmp,Val{NaN}())
@time allNA(tmp2,Val{-9999.0}())
# with branching:
@time allNA(tmp,NaN)
@time allNA(tmp2,-9999.0)
```

**Comment by JeffBezanson** [comment]
> isNA(x,NAval) = isnan(NAval) ? isnan(x) : x == NAval

I see why it makes sense in your example, but it's a bit perverse to check both that NaN is NaN and that the value in question is NaN. Anyway in the near future this will best be done by `all(x->isequal(x,NAval), x)`.

**Comment by yuyichao** [comment]
> What else would I use value types for?

Don't use it unless you are sure you will never need it as a runtime branch and need completely different code path.

> # The manual recommends this way:

You need to specialized on the type if you want to use that way. i.e. define `allNA` as `allNA{T}(x, m::Type{T})`

Also make sure to compile the functions before benchmarking. I see no performance difference at all for the `Val{...}()` and value version.

Also note that there are multiple NaN's and if you really need a compile time branch you should just use a `Val{true}` or `Val{false}` (or a enum) instead.

**Comment by gdkrmr** [comment]
ok, with `allNA{T}(x, m::Type{T})` the function is as fast as the other one but less flexible and the 3x difference for the branching was, because I used `if ... else ...` instead of `... ? ... : ...` for testing, with  `... ? ... : ...` I get almost the same speed as with the others.
Where can I read up on the difference between `if ... else ...` and the ternary and short circuit evaluation?

**Comment by gdkrmr** [comment]
Is there a way to extract the value from a value type? E.g. `f(Val{true})` -> `true`

**Comment by yuyichao** [comment]
>  Where can I read up on the difference between if ... else ... and the ternary and short circuit evaluation?

There's none.

**Comment by gdkrmr** [comment]
so why is the code using the ternary operator??

**Comment by yuyichao** [comment]
None of the code you provided has any `if else` so it's impossible to tell what exactly you are doing.
You can figure out what you are doing wrong with `code_lowered` and `code_typed` (or `code_warntype`).

In any case, questions about how to write idiomatic code belongs to the mailing list and not the issue tracker.

**Comment by gdkrmr** [comment]
ok, sorry, anyways thank you for the help!
