### ISSUE TITLE
Improve docs for immutable composite type behavior as function arguments

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLang/julia#14801]
In continuation from: https://groups.google.com/d/msg/julia-users/ZjOHONlVhsQ/eUBW51B5CgAJ

The statement from the docs:

"An object with an immutable type is passed around (both in assignment statements and in function calls) by copying, whereas a mutable type is passed around by reference."

is misleading and may not always be true (see discussion posted above). 

My limited understanding and discussion with people on google groups suggests that the compiler is free to either copy or reference immutables (both singular or array of composite types ).

thanks,
Nitin

**Comment by JeffBezanson** [comment]
+1 Indeed, the whole point of immutable is that you can't tell whether the value was "copied".

**Comment by goelakash** [comment]
So from:
`To recap, two essential properties define immutability in Julia:

    An object with an immutable type is passed around (both in assignment statements and in function calls) by copying, whereas a mutable type is passed around by reference.
    It is not permitted to modify the fields of a composite immutable type.`

Could it be changed to:

`So essentially, It is not permitted to modify the fields of a composite immutable type."

**Comment by 315234** [comment]
Is the following a manifestation of this issue?

```
function normalize!(data)
    data /= data[end]
    data
end

data = fill(3.0, 10)
normalize!(data)
println(data[end])
```

I would expect this to print "1.0", instead it prints "3.0".

**Comment by yuyichao** [comment]
No, it is simply because `/=` is not a in-place update operator https://github.com/JuliaLang/julia/issues/249

**Comment by StefanKarpinski** [comment]
Even if `/=` were an in-place operator, this would still not work because floats are immutable and Julia functions cannot change bindings in the calling scope.

**Comment by 315234** [comment]
This immutable/mutable stuff is just way too subtle a distinction for most people. It is not intuitive that `+=` and friends, especially operating on arrays, will create an entirely new object and destroy the old one. It is counterintuitive that doing an operation element-wise on an array (`a[:] .*= a`) has a different effect of using array expressions (`a *= a`). In a numerical language where performance is supposed to be a focus, it is almost never anyone's intention to implicitly allocate a new block of memory and throw out the old one. The end result is that Julia has array expressions but you basically can't use them without sacrificing performance.

**Comment by mbauman** [comment]
This line fortunately no longer appears in the docs.
