### ISSUE TITLE
Lies... and then benchmarks...

### ISSUE THREAD

**Issue by ylluminate** [JuliaLang/julia#14808]
So I know how much we all hate this, but I wanted to draw some attention to a couple points.  After doing a good bit of research into Julia, I finally decided that I was going to dig in when I stumbled across these benchmarks:
https://github.com/kostya/benchmarks

I ran a few on my own system and had some mixed results.  Essentially the numbers were still falling somehwat in line with what was presented.  The results on these tables were a bit different than what I've read about elsewhere.  Are we seeing some inefficient code here for Julia that's the root of such results?

I was also saddened to see [this observation](http://www.davideaversa.it/2015/12/the-most-promising-languages-of-2016/):
```
Julia instead is slowing down and it disappeared from my radar during the last 9 month. It is still young and promising but it slowed down a bit this year so I don’t think it deserve the Top 5 for now.
```

Is this slowing down a general consensus?  It seems that a number of folks are not as excited about Julia as they were just a year or two ago.

**Comment by johnmyleswhite** [comment]
I think we've gotten much better at tracking performance regressions.

That said, I'm not totally clear what the action item for this issue is. What should be done? I think it's only natural that some people end up getting disillusioned with any language.

**Comment by ylluminate** [comment]
Well the primary takeaway may be to get some folks who are quite good with Julia to keep tabs on such benchmarks and work on raising the performance.  Granted it ends up being marketing, but it is still a critical role in building the desirability.  I can understand higher memory usage, especially with the distributive capacity of Julia, but the processor cycles should be something that can be brought to where we're reading that it's performance is "close to C" all over the place.  Reading all of these articles that shout and jump up and down about performance for Julia and then seeing things in rough can have negative impacts for the community.

**Comment by jiahao** [comment]
This issue is too open ended to read a bug report and the discussion is more suited for the julia-users mailing list.

For the record, @jrevels is working here at the Julia Lab at MIT on implementing a testing framework for detecting performance regressions.

**Comment by ylluminate** [comment]
Good to know @jiahao, thanks.  I thought that this would be a solid place to get an initial grasp around the sentiment towards such a discussion from those who are a bit more "in the know" on this and I'm glad to have gotten this input.

**Comment by jiahao** [comment]
In the future, please read our [contribution guidelines](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#before-filing-an-issue) to determine what is suitable for GitHub issues.

**Comment by Ismael-VC** [comment]
@ylluminate looking at the structure of the Julia programs, I can only see @kostya is timing both Julia startup, the JIT and the code at the same time, which is wrong

* https://github.com/kostya/benchmarks/blob/master/base64/test.jl
* https://github.com/kostya/benchmarks/blob/master/base64/run.sh#L25-L26

Let's continue this discussion at julia-users:

* https://groups.google.com/forum/#!topic/julia-users/4AgBccftrps

**Comment by tkelman** [comment]
You can write slow code in any language. You should look at how un-idiomatic one of the benchmarks in that repo was before I took the function fields out of the types with a PR. Most contributors would rather spend time working on developing the language and building libraries that don't exist in any other ecosystem than reading blogs and fixing bad benchmark code.

**Comment by Ismael-VC** [comment]
I agree, but let him fix them if he wants, else those kind of benchmarks spread FUD. The only problem is that the gitHub repo is not for casual chatting, but for issues and PRs, @ylluminate now you know about julia-users, there is also this julia chat room: https://gitter.im/JuliaLang/julia

**Comment by JeffBezanson** [comment]
If you're asking those likely to be reading this issue, you're not likely to find a general consensus that julia is slowing down (I take that to mean the pace of development?) Some do want more frequent releases, but I care more about the content. The ~year gap between 0.3.0 and 0.4.0 was bad; I think 0.4.0 to 0.5.0 will be closer to 6 months.

**Comment by timholy** [comment]
@ylluminate, check out the difference in [this implementation](https://github.com/kostya/benchmarks/blob/4441efe9b45e78c120b8741205a4c68dc647a07e/matmul/matmul.jl#L14-L21) vs [this one](https://github.com/kostya/benchmarks/blob/4441efe9b45e78c120b8741205a4c68dc647a07e/matmul/matmul.c#L31-L51). Comparing those two has nothing to do with the language, and all about comparing a good implementation against a bad one.
