### ISSUE TITLE
cholfact for sparse matrix does not keep floating type

### ISSUE THREAD

**Issue by KrisDM** [JuliaLang/julia#14810]
In Julia 0.4.3, and Julia 0.5.0-dev, calling cholfact on a sparse Float32 matrix promotes the Cholesky factorization to Float 64. On a dense matrix, it correctly gives a Float32 factorization.

Compare:

```
julia> cholfact(eye(Float32,3))
Base.LinAlg.Cholesky{Float32,Array{Float32,2}} with factor:
3x3 UpperTriangular{Float32,Array{Float32,2}}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```
With:

```
julia> cholfact(speye(Float32,3))
Base.SparseMatrix.CHOLMOD.Factor{Float64}
type:          LLt
method: simplicial
maxnnz:          3
nnz:             3
```

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/issues/14076#issuecomment-158998239. It's a limitation in the sparse factorization library CHOLMOD. Eventually, we'd like to have pure Julia implementations of the sparse factorizations, but for now there is not much we can do.

**Comment by kmsquire** [comment]
Would it be worthwhile leaving this open (and renaming it) as an issue to create a pure Julia sparse factorization library?

**Comment by jiahao** [comment]
At the very least, we should document the behavior. As an issue, "pure Julia sparse linalg" is rather too broad.

**Comment by andreasnoack** [comment]
I've changed the title to reflect the documentation issue.
