### ISSUE TITLE
need to install compiler-rt

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#14818]
```julia
~/julia$ ./build-llvm37/julia --precompiled=no -C generic
WARNING: unable to determine host cpu name.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+2360 (2016-01-26 23:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  jb/functions/6b04549* (fork: 46 commits, 0 days)
|__/                   |  x86_64-apple-darwin15.3.0

julia> @code_native Base.Threads.atomic_or!(Base.Threads.Atomic{Int128}(1),Int128(5))
LLVM ERROR: Program used external function '___sync_fetch_and_or_16' which could not be resolved!
~/julia
```

**Comment by yuyichao** [comment]
Llvm emits a function call for that?

**Comment by yuyichao** [comment]
Oh i see, it's probably caused by the generic arch.

**Comment by vtjnash** [comment]
yes, it's the combination of being a generic arch and i128 (and expecting that compiler-rt will exist). i guess i opened the issue so that nobody will be particularly surprised when I open a PR for it.

**Comment by yuyichao** [comment]
I think people will not be surprised if the PR includes tests for these functions =).

**Comment by vtjnash** [comment]
looks like the is actually an upstream bug (`__sync` instead of `__atomic`) – well, that and the support code has been disabled for a couple years https://github.com/llvm-mirror/compiler-rt/commit/fa3eee4101f39661b4a88ac0bc7f184ca8c1ecb1

**Comment by Keno** [comment]
There was a thread on llvm dev abouty `sync` vs `atomic` today.

**Comment by eschnett** [comment]
All modern Intel CPUs have the `cmpxchg16b` instruction. If LLVM can generate this instruction, then presumably it won't need to emit a call to `___sync_fetch_and_or_16`. So maybe the solution is to use a target architecture that is slightly less generic than `generic`? This would in effect increase the minimum hardware required to run a thread-enabled Julia.

I also hear that "The 64-bit version of Windows 8.1 requires this feature" <https://en.wikipedia.org/wiki/X86-64>.

**Comment by eschnett** [comment]
I confirm that this patch
```diff
$ git diff
diff --git a/src/codegen.cpp b/src/codegen.cpp
index 284ae89..e9a40ac 100644
--- a/src/codegen.cpp
+++ b/src/codegen.cpp
@@ -5802,6 +5802,8 @@ static inline SmallVector<std::string,10> getTargetFeatures() {
 #ifdef V128_BUG
   HostFeatures["avx"] = false;
 #endif
+  // Require cx16 (cmpxchg16b)
+  HostFeatures["cx16"] = true;
 #endif
 
   // Figure out if we know the cpu_target
```
resolves the issue.

**Comment by eschnett** [comment]
I believe this was corrected by #15219.

**Comment by eschnett** [comment]
Unfortunately, #15219 only corrects this for 64-bit Intel systems, not for 32-bit systems.

**Comment by yuyichao** [comment]
Looks like llvm-svn have some issue that might be related? http://buildbot.e.ip.saba.us:8010/builders/nightly_llvmsvn-x64/builds/196/steps/make%20testall/logs/stdio
