### ISSUE TITLE
minor promotion issue with A[t|c]_ldiv_B for triangular A and non-strided B

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#14816]
Tracker for the triangular case of #14506 described in https://github.com/JuliaLang/julia/pull/14506#issuecomment-168088706. Briefly, where `A` is a triangular matrix and `B` is not a `StridedVecOrMat`, the element-type promotion for `A[t|c]_ldiv_B` sometimes fails. For example
```julia
m = 10
intmat = fill(1, m, m);
ltintmat = LowerTriangular(rand(1:10, m, m));
At_ldiv_B(ltintmat, sparse(intmat))
```
fails with an `InexactError`. See #14506 for more. Best!

**Comment by Sacha0** [comment]
Fixed.

**Comment by tkelman** [comment]
is it sufficiently tested to stay that way?

**Comment by Sacha0** [comment]
Probably not. I'll have a look.

**Comment by Sacha0** [comment]
I am not certain whether existing general tests cover this, so to be safe I added a specific test in #16968. Thanks!
