### ISSUE TITLE
require for remote workers: rationale behind include_from_node1

### ISSUE THREAD

**Issue by yjk21** [JuliaLang/julia#14814]
Hello, 
I am trying to understand how importing packages works when using a SSHManager based cluster.

I would like to run Julia code on two machines that have different path names for the package directory.

In principle remote execution of Julia code works.

However, when I want to import a package (in my case HDF5), it seems that on the remote worker the package directory of the master is used.

While browsing through `loading.jl`, I noticed that `require()` spawns a call to `Base.include_from_node1` on the worker, which indicates that the behaviour I observe may be by design.

I suppose this is to make sure that the remote package version is compatible to the one on the master.
In my environment however, it would be great to be able to use packages locally installed on the worker.
Is there another way to load packages remotely, taking into account the configuration of the worker?

Thanks!

**Comment by tkelman** [comment]
I don't think there's an actionable specific issue here, except maybe doc improvements. There's a recent PR for that, I think we haven't merged it quite yet.

General usage questions should go to the julia-users list first unless there's a specific bug or documentation change, and in the latter case it's best to suggest a PR.
