### ISSUE TITLE
mod-function for floating point arguments can return values outside documented range

### ISSUE THREAD

**Issue by traktofon** [JuliaLang/julia#14826]
Hello,
the current implementation (julia-0.4.3) of the mod-function for floating point arguments may return values outside the range which is documented. Specifically, according to the docs, mod(x,y) should for positive y return a value strictly smaller than y. But due to FP rounding errors, it can actually return y. Example:

```
help?> mod
[...]
  mod(x, y)
  Modulus after division, returning in the range [0,y), if y is positive, or (y,0] if y is negative.

julia> x=-eps(1.0)
-2.220446049250313e-16

julia> mod(x,4.0)
4.0

julia> mod(x,4.0) < 4.0
false
```

A workaround could be applying the mod-function twice:

```
julia> mod(mod(x,4.0),4.0)
0.0
```

Admittedly, it is not obvious which result (0.0 or 4.0) is preferable. Since the correct result (4.0-eps(1.0)) cannot be represented exactly by Float64, returning the closest Float64 (i.e. 4.0) is understandable. However, when taken mod 4, 0.0 is as correct (or as wrong) as 4.0, but has the advantage of conforming to the specification. If 4.0 is determined to be an acceptable result, then the documentation of the mod-function should be expanded to mention that mod(x,y)<y might not always hold.

For completeness, my Julia version info:

```
julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Thank you,
Frank

**Comment by mschauer** [comment]
The property
```
y = fld(x,y)*y + mod(x,y)
```
with `` fld(x, y)`` defined as ``Largest integer less than or equal to x/y`` seems to exclude 0.0. An extended discussion is here #3127. Note that only exactness of rem is guaranteed.
