### ISSUE TITLE
reducedim test failure: BoundsError in sum!(R,A,init=false) == [36,41,46]

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14827]
I've seen this for the first time today when building RPM nightlies on RHEL7 (using LLVM 3.7.1):

```
    From worker 2:       * reducedim            Error During Test
    From worker 2:    Test threw an exception of type BoundsError
    From worker 2:    Expression: sum!(R,A,init=false) == [36,41,46]
    From worker 2:    BoundsError
    From worker 2:     [inlined code] from ./number.jl:15
    From worker 2:     in _mapreducedim! at ./reducedim.jl:218
    From worker 2:     [inlined code] from ./essentials.jl:118
    From worker 2:     in include_string at ./loading.jl:371
    From worker 2:     in include_from_node1 at ./loading.jl:420
    From worker 2:     [inlined code] from ./util.jl:179
    From worker 2:     in runtests at /builddir/build/BUILD/julia/test/testdefs.jl:7
    From worker 2:     in anonymous at /builddir/build/BUILD/julia/test/runtests.jl:36
    From worker 2:     in anonymous at ./multi.jl:1010
    From worker 2:     in run_work_thunk at ./multi.jl:714
    From worker 2:     [inlined code] from ./multi.jl:1010
    From worker 2:     in anonymous at ./task.jl:63
```

https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/epel-7-x86_64/00156219-julia/build.log.gz

**Comment by tkelman** [comment]
Can you reproduce this locally and try to bisect? I'm suspicious that https://github.com/JuliaLang/julia/commit/639621859863609c5f3abbc2ed75c675695b3693 may have ibtroduced some new intermittent failures.

**Comment by nalimilan** [comment]
I can try to reproduce it at least once first, but given that it appeared only once for 9 builds, it's going to be hard to bisect. Let's see...

**Comment by nalimilan** [comment]
I haven't been able to reproduce it with 100 runs of that test locally, and about 20 different builds didn't trigger it remotely either. So it's going to be a nightmare to bisect...

**Comment by KristofferC** [comment]
Please reopen if this happens again.
