### ISSUE TITLE
Cxx 11 issues calling llvm

### ISSUE THREAD

**Issue by dioptre** [JuliaLang/julia#14820]
Hi there,

I'm getting unexpected ABI results between Keno's Cxx.jl and the default build parameters for Julia on debian/Ubuntu using gcc/clang:

https://github.com/Keno/Cxx.jl/issues/223

I'm building julia from source, including llvm as per Keno's instructions...

I was hoping someone whos had experience building using Cxx 11 and Clang could point me in the right direction. I've tried -D_GLIBCXX_USE_CXX11_ABI=0 but it seems to crash all of Julia.

Thanks!
Andy

**Comment by ihnorton** [comment]
Please use the [julia-users mailing list](http://julialang.org/community/) for questions like this.

**Comment by maleadt** [comment]
For the record, this is a potential issue when building Julia and using multiple compilers. For example, when using `USE_SYSTEM_LLVM` on a distro which already uses the new ABI (ie. Arch Linux) while using `USECLANG=1` which doesn't support GCC's ABI tag (see [#23529](https://llvm.org/bugs/show_bug.cgi?id=23529)). It shouldn't be an issue when building everything from source -- it could have been for some deps which unset `USECLANG` (openspecfun, Rmath-julia and openlibm), but none of those libraries seem to export symbols using the new ABI.
