### ISSUE TITLE
"coverage=true" generates generated functions twice

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14834]
I find that Travis generates generated functions twice. This is a bit of a nuisance since I also define a new type in the process, and defining a type twice is an error.

This seems to be caused by the "coverage=true" flag.

(The work-around is simple, of course (use "eval" to check whether the type exists; break out early if it does), but I'm still wondering why this is the case.)

**Comment by yuyichao** [comment]
It is a documented (slightly above [this line](http://julia.readthedocs.org/en/latest/manual/metaprogramming/?highlight=generated#an-advanced-example)) undefined behavior if the generated function has side effect and the compiler is allowed to run the generated function as many time as it want.

> the foo function has side-effects, and it is undefined exactly when, how often or how many times these side-effects will occur.
