### ISSUE TITLE
`eigs` documentation doesn't describe `DLAMCH('EPS')`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14837]
The documentation of `eigs` mentions `DLAMCH('EPS')`. There is no such function in Julia. I believe this is `eps()/2` in Julia.

**Comment by jiahao** [comment]
Yes, `DLAMCH('E')` in `LAPACK` is indeed `eps()/2)`.

```
julia> ccall( (:dlamch, :liblapack), Cdouble, (Ptr{UInt8},), &'E')
1.1102230246251565e-16

julia> eps()
2.220446049250313e-16
```

I'll add this to #14880.
