### ISSUE TITLE
typealias constructor bug?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaLang/julia#14833]
(Julia v0.4.1)
Building a constructor from a parameterized type alias does not appear to work:

	type MyType{T1,T2}
		v::T1
		v2::T2
	end

	typealias MyType2 MyType{Float64}
	typealias MyType3 MyType{Float32}
	typealias MyType4{T2} MyType{Int, T2}

	MyType{T<:Integer}(v::Vector{T}) = :MTv #OK
	MyType{T<:Integer}(v::Vector{T},b) = :MTva #OK
	MyType2{T<:Integer}(v::Vector{T}) = :MT2v #OK
	MyType3{T<:Integer}(v::Vector{T}) = :MT3v #OK
	MyType4{T<:Integer}(v::Vector{T}) = :MT4v #No good
	 => LoadError: cannot define function MyType4; it already has a value

NOTE:
 - If the typealias is not parameterized, the "constructor" syntax works.  I call this a "constructor", assuming it would normally return a new MyType{...} - not just a symbol.
 - I can get the MyType4 "constructor" to work only with the more verbose "call" syntax:

		call{T<:Integer}(::Type{MyType4}, v::Vector{T}) = :MT4v

If there is no fundamental reason for the more succinct syntax to work on parameterized types, it would make code easier to read/maintain.

**Comment by JeffBezanson** [comment]
fixed by #13412

**Comment by ma-laforge** [comment]
Ok. Should I be closing the issue to reduce noise, or will you do this?

**Comment by JeffBezanson** [comment]
An issue should always be left open until it is actually fixed. Otherwise those who fix issues are robbed of the satisfaction of clicking the button :)
