### ISSUE TITLE
jit code debug registration is O(n^2)

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#14846]
Julia now runs extremely slowly inside GDB. I traced this to `NotifyDebugger`, which seems to call `__jit_debug_register_code` on an ever-growing linked list of functions. I confirmed that the slowdown is quadratic by printing the wall-clock time on each debug info registration.

**Comment by vtjnash** [comment]
i think you'll need to file this against gdb. `__jit_debug_register_code` only registers "relevant_entry" given the `JIT_REGISTER_FN` action (you can check the file `gdb/jit.c` to verify for youself). the linked list is only scanned (once) if gdb is attached after the process is started.

**Comment by JeffBezanson** [comment]
Looks like this has been observed before: https://github.com/v8/v8/wiki/GDB-JIT-Interface#known-limitations
Might make sense to keep this open with an upstream tag; running under gdb is now useless. Or maybe we should disable this feature for now.

**Comment by vtjnash** [comment]
i don't really like tracking bugs in other projects here, even less so when it is a performance issue, and even less so when we don't have an explicit dependency on that code.

**Comment by JeffBezanson** [comment]
That's reasonable, but this really blocks using gdb for anything that takes more than a few seconds. It looks like lldb implements the same interface, but I guess doesn't have the performance issue? Or do we just tell people to comment out `__jit_debug_register_code` if they want to use gdb?

**Comment by StefanKarpinski** [comment]
Does lldb have the same issue? I've been living with only lldb for a while now on OS X and it's ok.

**Comment by yuyichao** [comment]
@JeffBezanson Have you try to remove the linked list setup and see if the `O(n^2)` goes away? If I read the gdb code correctly, (as jameson mentioned) gdb should only check the `relavant_entry` when the breakpoint is triggered and the linked list should only be used when gdb is attached to a process. However, it seems that gdb doesn't actually go through this list when it attaches to a process, which causes bad backtrace/unwinding when using gdb attach so I think there's something wrong with GDB here.

I don't think lldb has this issue. It doesn't use this interface and doesn't have any idea about the functions we jit.

**Comment by JeffBezanson** [comment]
Yes, I tried not adding items to the list, and only passing one item every time. It's still O(n^2) in the number of calls to `__jit_debug_register_code`.

**Comment by Keno** [comment]
Yeah, this is a gdb bug. LLDB should work fine, but only on a 3.8 derived version, because they had jit-debugging broken for a while.
