### ISSUE TITLE
Unable to use Pkg

### ISSUE THREAD

**Issue by kgryte** [JuliaLang/julia#14841]
When running `Pkg` methods, I encounter the follow set of errors:

``` julia
julia> Pkg.status()
INFO: Initializing package repository /Users/<user>/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: AssertionError: 
 in test_success at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:52
 in cd at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in status at pkg.jl:32 (repeats 2 times)
```

``` julia
julia> Pkg.init()
INFO: Initializing package repository /Users/<user>/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: AssertionError: 
 in test_success at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:52
 in cd at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in init at pkg/dir.jl:50
 in init at pkg.jl:19
```

``` julia
julia> Pkg.add("JSON")
INFO: Initializing package repository /Users/<user>/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
ERROR: AssertionError: 
 in test_success at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:52
 in cd at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in add at pkg.jl:23
```

Am I missing something obvious in terms of setup or should `Pkg` just work out-of-the-box? Running on Mac OSX.

**Comment by kmsquire** [comment]
Presumably you changed your username to `<user>` manually in your description?

**Comment by kgryte** [comment]
@kmsquire That is correct.

**Comment by kmsquire** [comment]
Okay.  Since this seems to be working for everyone else (myself included), it's probably a problem with your setup somewhere (old version of git, or you didn't accept the xcode license, or some such thing).  Posting a message to julia-users will probably get you farther than here.

But, it would be good to post your solution back here once you get it, because it would be nice to give a better error message once we know what your actual problem is.

**Comment by tkelman** [comment]
The bundled version of git in the mac binaries is apparently not running correctly on your system.

**Comment by kgryte** [comment]
@kmsquire What constitutes an old version of `git`? All `Pkg` needs to do is clone, correct? And if so, I am able to clone and use `git` generally without any hitch.

**Comment by kgryte** [comment]
I ended up uninstalling and then reinstalling Julia. `Pkg` now works. 

@tkelman If a particular version of `git` is required to run `Pkg`, would be useful to have this stated explicitly in the docs.

**Comment by tkelman** [comment]
I think it's documented as any version newer than 1.7.3. The mac binaries do not assume the user has git installed, so include a copy of git that they should be using. On julia master this is no longer the case as we use libgit2 instead of command line git.

It sounds like you may have had a corrupted download or incomplete installation? Glad it's working now after a reinstall.

**Comment by kgryte** [comment]
@tkelman For the record, my `git` installation was not the one included with the Mac binaries. I did a fresh install upon setting up my machine. I am using `2.3.0`.

For completeness, I reverted my machine to the previous version of Julia I had installed. I then upgraded `git` to `2.6.4`. `Pkg` subsequently worked. In which case, my Julia installation did not work with a version of `git` greater than `1.7.3`.

**Comment by tkelman** [comment]
If you have multiple versions of git installed then I believe it will depend on what order they are found in `ENV["PATH"]`. The `juliarc.jl` that we include with the mac binaries prepends its embedded git before the rest of the existing path: https://github.com/JuliaLang/julia/blob/0e09b2aadc36e16531da49aa1e487d56621ae9b3/contrib/mac/juliarc.jl#L6

**Comment by kgryte** [comment]
@tkelman I see. Thanks for the clarification. That makes a bit more sense that somewhere configuration went askew.
