### ISSUE TITLE
blkdiag() fails without proper error message

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#14850]
In Julia 0.5.0-dev+2335:

```
julia> blkdiag()
ERROR: StackOverflowError:
 in convert at dates/periods.jl:22 (repeats 79996 times)
```

In Julia 0.3.2:

```
julia> blkdiag()
ERROR: `convert` has no method matching convert(::Type{None}, ::Int64)
 in _mapreduce at ./reduce.jl:158
 in blkdiag at ./sparse/sparsematrix.jl:1731
```

Both error messages are not very helpful. Arguably, `blkdiag()` without arguments is not a common use case, but I do something like `blkdiag([f(x) for x in X]...)` and in some cases, `X` can be empty. A helpful error message would have helped me track down that problem somewhat faster. (My ad-hoc fix is `blkdiag(spzeros(0, 0), [f(x) for x in X]...)`, which is a bit ugly but works.)

Another issue is whether `blkdiag()` should actually error or rather return an empty matrix. The latter might be more useful, but the type is ambiguous. I tried a rather simple fix to `blkdiag` which made it return a 0x0 matrix, but it turned out to be of type `SparseMatrixCSC{Union{},Union{}}` with `colptr[1]` being undefined. While `Union{}` might make sense for the element type, it clearly does not work for the index type. 

IMHO, the nicest solution would be to add a typed version of `blkdiag` such that:
- `blkdiag(a, b, c)` behaves as before
- `blkdiag(T, a, b, c)` yields of result of type `T` (provided the any necessary conversions work)
- `blkdiag(T)` yields an empty sparse matrix of type `T`
- `blkdiag()`  errors (in a more helpful way than now).

If this is judged useful, or there turns out to be a preferable alternative, I'd be happy to work on it.

**Comment by tkelman** [comment]
> the nicest solution would be to add a typed version of `blkdiag`

That sounds reasonable to me. If tweaking that code, would be good to try DRY'ing it up a bit since it shares so much with sparse hcat. Sparse `blkdiag` was my first PR to Julia, it's still not implemented for dense. Though there is `cat([1,2], A, B, ...)` now for the generic (only particularly efficient for dense) case, no one has tried unifying the two names for this.

**Comment by martinholters** [comment]
Actually, a typed `cat` similar to my above proposal for `blkdiag` sounds quite attractive to me. In addition to fixing/defining the (potentially) empty `cat` case, it would also allow constructing a sparse block diagonal matrix out of dense blocks with `cat(SparseMatrixCSC{Float64,Int}, [1 2], A, B, ...)`. Looks useful to me. Opinions?

**Comment by tkelman** [comment]
The current usual convention is for type inputs to be the element type for functions that return arrays, but it should maybe not stay that way. Ref https://github.com/JuliaLang/julia/issues/11557

**Comment by martinholters** [comment]
> The current usual convention is for type inputs to be the element type for functions that return arrays

Yes, but that doesn't help with the original problem because for sparse matrices, there is also the question of the index type. Defaulting to `Int` springs to mind, but consider a function `f(x)` that always returns a `SparseMatrixCSC{Float64,Int8}`. For type stability, I'd like `blkdiag(???, [f(x) for x in X]...)` (or `cat`) to always return a `SparseMatrixCSC{Float64,Int8}` as well, no matter whether `X` is empty or not. Surely, the `???` then has to include both element and index type. So where can I cast my vote on #11557?

However, if the convention stays the way it is, is there a way to solve this without violating the convention?

**Comment by tkelman** [comment]
I think changing the convention is fair game. No one seemed especially against the idea, though there are some subtleties. It might be confusing to be in a state where some functions use a container type convention and others use an element type convention, but I think the way forward is try implementing something to start with and see how it goes.

**Comment by ViralBShah** [comment]
I would pick Int by default
