### ISSUE TITLE
LoadError: UndefVarError: Model not defined

### ISSUE THREAD

**Issue by lamiastella** [JuliaLang/julia#14859]
Pkg.add("JuMP")
Pkg.add("Clp")
m = Model()
and I get the following error:
LoadError: UndefVarError: Model not defined
while loading In[4], in expression starting on line 1

**Comment by lamiastella** [comment]
You should say "using JuMP" before saying "m=Model()"

**Comment by ihnorton** [comment]
Hi @lamiastella, welcome to Julia, and glad you figured it out. In the future, the best place for JuMP questions is the [julia-opt](https://groups.google.com/forum/#!forum/julia-opt) mailing list, and general Julia quesions can go to [julia-users](https://groups.google.com/forum/#!forum/julia-users). Thanks!

**Comment by tkelman** [comment]
Is there example code you were working from somewhere that was missing the `using JuMP` ? If so it should be corrected.
