### ISSUE TITLE
Really slow compilation on ARM

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#14865]
The compilation on ARM is really slow. Is it possible to perhaps disable a few optimization passes to gain better compilation speed at the cost of some run time performance loss?

**Comment by yuyichao** [comment]
I don't think this is ARM specific. The compilation time on a ARM machine with more powerful cores is actually not bad with ORCJit (23.5min as I just measured). We already have an issue about [adding command line arguments for optimization](https://github.com/JuliaLang/julia/issues/14632) but I think such option shouldn't be enabled by default.

**Comment by ViralBShah** [comment]
Yes, it is slow machines. I guess we could have command line arguments that take care of this, and hopefully on these slow machines, it will mostly be precompiled deployments rather than development.

**Comment by ViralBShah** [comment]
Should we default to a lower level of optimization by default on arm? Perhaps `-O1`? I am not sure what the performance impact might be.

Cc @simonbyrne @aviks

**Comment by simonbyrne** [comment]
No, it doesn't seem to make much difference. e.g. when timing matrix printing (which is painfully slow at the moment)
```
time julia -O3 -e 'Base.showarray(STDOUT, rand(10,10),false)'
```
I get ~5s for `-O0` and ~7s for all others.

**Comment by ViralBShah** [comment]
Closing, since there is nothing directly actionable except making the compiler faster in general.
