### ISSUE TITLE
[Question] Julia deps

### ISSUE THREAD

**Issue by albap** [JuliaLang/julia#14868]
Why is it that when building Julia, it wants to compile almost all dependencies itself?
I think users should either check dependencies and build them themselves or install them through package manager. Doesn't seem to me the job of Julia to do this.
I know that LLVM has some optimizations that are not yet upstreamed. But when they are upstreamed in the future, will Julia stop compiling LLVM then? What about all other deps?

**Comment by vtjnash** [comment]
questions should go to julia-users, not the issue tracker

**Comment by albap** [comment]
Sorry, I didn't know. Closing.
