### ISSUE TITLE
[Bug] Julia uses internal glibc header sys/cdefs.h

### ISSUE THREAD

**Issue by albap** [JuliaLang/julia#14866]
Trying to compile Julia on a musl libc system together with @tkelman , we uncovered this error with Julia.
As instructed by [musl libc documentation](http://wiki.musl-libc.org/wiki/FAQ#Q:_I.27m_trying_to_compile_something_against_musl_and_I_get_error_messages_about_sys.2Fcdefs.h), I'm reporting the bug.

**Comment by yuyichao** [comment]
What's the exact error you get? A rough grep suggests that it might be `openlibm` that's including this header. If that is the case, this should be filed against openlibm instead and you can probably work around it now with `USE_SYSTEM_LIBM=1`.

**Comment by tkelman** [comment]
If `__BEGIN_DECLS` and `__END_DECLS` are the only thing that header is used for, then the fix should be pretty easy. Take https://github.com/JuliaLang/openspecfun/blob/86948788973da210329858537d35000c8fbabb8b/rem_pio2/cdefs-compat.h#L4-L18 and remove the `#if !defined(_WIN32) && !defined(__sun)` side of the ifdef.

**Comment by albap** [comment]
Should I file separate bugs for openlibm and openspecfun?
Even though the USE_SYSTEM_LIBM=1 workaround works for openlibm, this is still a bug according to musl libc documentation and no program should use sys/cdefs.h.
I did that, but now I get ``error: unknown type name 'u_int32_t'`` on math_private.h and e_rem_pio2.c.

I think that's because u_int32_t is implementation specific. Shouldn't the C99 standard uint32_t be used isntead?

**Comment by tkelman** [comment]
Yeah best to file issues in each individual repo. And include as much information as possible with the reports - error messages, build logs, etc.

> Shouldn't the C99 standard uint32_t be used isntead?

Yeah that seems like the right thing to do.

**Comment by yuyichao** [comment]
FWIW, `u_int32_t` is the type defined by `libsupport`. I think we can certainly move away from it as long as MSVC is happy.

**Comment by tkelman** [comment]
openspecfun does not depend on libsupport though. and I've yet to try building openspecfun with msvc, only the julia runtime.

**Comment by yuyichao** [comment]
Yeah, seems that glibc also define this. Given we actually use both versions in julia, we can probably just consistently use the standard `stdint.h` types.

**Comment by albap** [comment]
I like how trying to compile Julia on musl reveals bugs and non-standard behavior on the program :)
Let's fix 'em all!

**Comment by tkelman** [comment]
Yep, feel free to open pull requests at openspecfun and openlibm. We're happy to walk you through the process if you need any guidance, seeing as you're new to github.

**Comment by albap** [comment]
I sent a pull request to openspecfun fixing the issue.
I don't know how to fix openlibm.

**Comment by yuyichao** [comment]
Julia doesn't use any of the headers and they are fixed in other repos.
