### ISSUE TITLE
workaround/fix for manipulation of DateTime from a stat.mtime

### ISSUE THREAD

**Issue by crunch3** [JuliaLang/julia#14862]
There seems to be a type difference between the DateTime constructed from a yr,mon,day or a descriptive ASCII string and the DateTime you get from now() which causes comparisons between them to generate an InexactError.  Even if you trunc(stat.mtime), a comparison with now() nets you an error.  Will it always be like this (i.e. this behavior is by design)?  What is the conventional workaround?

**Comment by crunch3** [comment]
if I suck the field values out and create DateTimes from the values, e.g.
dn = now()
dn2 =DateTime( Dates.year(dn), Dates.month(dn), Dates.day(dn), Dates.hour(dn), Dates.minute(dn), Dates.second(dn) )

dt = DateTime( trunc(stat.mtime, Second) )
dt2 = DateTime( Dates.year(dt), Dates.month(dt), Dates.day(dt), Dates.hour(dt), Dates.minute(dt), Dates.second(dt) )

Day( dt2 - dn2 )
still fails with an InexactError()
  in divexact at dates/periods.jl:255
  in call at essentials.jl:56

so, I'm mystified.

**Comment by vtjnash** [comment]
> Day( now() - ms ); # in theory, the modify date

I get the day part of the modification date back, as I expected. I'm not sure what you mean by "just over the 3rd of January". Perhaps you meant `Dates.days(ms)`?

> to further eliminate type pollution

i've never heard of this concept

> Day( dt2 - dn2 )

`Day` requires a integer number of days ("January 31.45, 2016" would be highly non-conventional), while `dt2 - dn2` is an interval with millisecond accuracy. Again, perhaps you meant `Dates.days(dt2 - dn2)` to compute the integer number of days between `dt2` and `dn2`?

**Comment by crunch3** [comment]
yes, days() is fine.  Not sure why I got so stuck on Day().
