### ISSUE TITLE
sinpi returns negative zero for negative integer values

### ISSUE THREAD

**Issue by kgryte** [JuliaLang/julia#14870]
What is the rationale/usecase for copying the sign when `x` is an `integer`? https://github.com/JuliaLang/julia/blob/2d821670d2516cd38b51710b07b3eb18f191cd1b/base/special/trig.jl#L110

``` julia
julia> sinpi(4)
0.0

julia> sinpi(-4)
-0.0
```

The signs are opposite what is returned when using `sin` directly.

``` julia
julia> sin(4*pi)
-4.898587196589413e-16

julia> sin(-4*pi)
4.898587196589413e-16
```

**Comment by jiahao** [comment]
One reason is to preserve the identity that `sin(x) = -sin(-x)`. IEEE 754-2008 recommends that odd elementary functions have the property that [p. 43]: "f(+0) is +0 and f(−0) is −0 with no exception".

`sin(x)` calls whatever routine for sine is in the version of `libm` you are using underneath. The presumption is that if your application requires `sinpi` then you care to use an implementation that has all the mathematical niceties.

**Comment by jiahao** [comment]
Also, since

```
julia> 4π-big(4)*π
-4.898587196589412708904263729100004232838997783692312656251447921178145001272854e-16
```

`sin(float64(4π))` is slightly below the exact value of `sin(4π)` and vice versa for `sin(-4π)`. Therefore the observed behavior is correct and not a bug.

**Comment by kgryte** [comment]
@jiahao Thanks for the response and the IEEE reference.

**Comment by vtjnash** [comment]
please submit questions to the mailing list, not the bug tracker
