### ISSUE TITLE
An undefined variable doesn't raise an error

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#14878]
Thing to look for is that `junk` in `Weirdness` is not defined 

```julia
type Weird
    ext
end
Weird() = Weird(Dict())

type FooType
end
FooType(ng) = FooType()

function Weirdness()
    w = Weird()
    w.ext[:Iain] = FooType(junk)
    return w
end

versioninfo()
@show Weirdness()
```

On Julia 0.4.1:
```
$ jl WeirdStuff.jl
Julia Version 0.4.1
Commit cbe1bee* (2015-11-08 10:33 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Weirdness() = Weird(Dict{Any,Any}(:Iain=>FooType()))
```

On master, just built:
```
$ j5 WeirdStuff.jl
Julia Version 0.5.0-dev+2432
Commit d550b37* (2016-01-31 15:11 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
Weirdness() = Weird(Dict{Any,Any}(:Iain=>FooType()))
```

EDIT1: reduced complexity of code

EDIT2: no need for the `kwargs`

**Comment by IainNZ** [comment]
Oh, and one more piece of info: this is a reduced case, obviously. In the original case, I didn't even notice my mistake until it ran on Travis and failed - so something about Travis is different, possibly

**Comment by yuyichao** [comment]
The travis failure is probably due to no inlining.

**Comment by JeffBezanson** [comment]
Yep, inlining bug.

**Comment by KristofferC** [comment]
Is [this](https://github.com/EconForge/NLsolve.jl/commit/6b1a9c8183f65cde02669957f199c3261e9ff62f#diff-553eb2ad97af55fd609b933e5614b346R77) related? I acidentally added a random unicode character (a subscript k) to a line but all the tests passed. Is it because the statement was "effect free" and thus got dead code eliminated or something like that?

**Comment by yuyichao** [comment]
That one should be fixed by https://github.com/JuliaLang/julia/pull/14756

**Comment by KristofferC** [comment]
Ah, ok. Thanks.

**Comment by IainNZ** [comment]
This is still reproducible on master

**Comment by mschauer** [comment]
@IainNZ Can be closed, right?

**Comment by IainNZ** [comment]
@mschauer Can it? Does not happen anymore?

**Comment by IainNZ** [comment]
Still was happening 12 days ago

**Comment by yuyichao** [comment]
Seems to be fixed now. But need a test.
