### ISSUE TITLE
File and line number reporting in errors and warnings is inconsistent

### ISSUE THREAD

**Issue by 315234** [JuliaLang/julia#14889]
Most editors can be configured to parse strings like `filename.txt:23` and automatically open the file with the cursor at the correct line. This format is somewhat standard, sometimes including the column number too as in `filename.txt:23:5`. This can be used in conjunction with terminal emulators, allowing ctrl-clicking the `filename:line` to jump to that location in the default editor.

Julia sometimes uses this `filename:line` format for reporting errors, and sometimes not, often in the same output:

```
ERROR: LoadError:
 in error at error.jl:22
 in include at .../julia/0.4.2/lib/julia/sys.dylib
 in include_from_node1 at .../julia/0.4.2/lib/julia/sys.dylib
 in process_options at .../julia/0.4.2/lib/julia/sys.dylib
 in _start at .../julia/0.4.2/lib/julia/sys.dylib
while loading example.jl, in expression starting on line 11
```

which breaks the system described above; line numbers have to be typed manually.

I suggest a change to instead print the final line above as

```
while loading example.jl:11
```

**Comment by nalimilan** [comment]
While this sounds like a good idea in general, how would you print the additional information `in expression starting on line 11`? It tells you that the error isn't necessarily at line 11, but in the expression that starts there.

I guess there are other possible messages that would need to be preserved too.

**Comment by 315234** [comment]
How about something like
    in expression starting at example.jl:11

**Comment by nalimilan** [comment]
Why not. Would you have a look at the code and make a pull request if it works? FWIW:
```
$ git grep "in expression starting"
base/replutil.jl:    print(io, "\nwhile loading $(ex.file), in expression starting on line $(ex.line)")
base/util.jl:        print(io, "\nwhile loading $filename, in expression starting on line $lineno")
src/signal-handling.c:    jl_safe_printf("while loading %s, in expression starting on line %d\n", jl_filename, jl_lineno);
```
