### ISSUE TITLE
Sparse cholfact(speye(Float16,2)) and cholfact(speye(BigFloat)) generate StackOverflowError

### ISSUE THREAD

**Issue by KrisDM** [JuliaLang/julia#14894]
Related to #14076, it may be impossible to fix until the CHOLMOD library is fixed, but it should probably be handled differently from generating the following error (in both Julia 0.4.3 and Julia 0.5-dev):

```
julia> cholfact(speye(BigFloat,2)) 
ERROR: StackOverflowError:
[inlined code] from ./boot.jl:331
 in copy at ./array.jl:121 
 in float at ./sparse/sparsematrix.jl:251
in Type at ./essentials.jl:25 (repeats 506 times)
```

``cholfact(speye(Float16,2))`` gives the same error.

For full matrices, ``cholfact(eye(BigFloat,2))`` is supported, whereas ``cholfact(eye(Float16,2))`` is promoted to ``Float32``.

**Comment by andreasnoack** [comment]
#14902 should fix the issue for `Float16` and will give a better error for `BigFloat`. Unfortunately, we are not able to compute the Cholesky factorization of a sparse matrix right now because the underlying C library doesn't support it.
