### ISSUE TITLE
Rewrite @simd to use ISPC / libispc?

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#14905]
I see that work is going in the ISPC project to have not just a command-line entry point but also a [library](https://github.com/ispc/ispc/issues/1134).

If licensing and other considerations allow it, this could be a great way to improve the `@simd` macro with their excellent support for control flow and math functions inside the loop.

Any thoughts on that?

**Comment by KristofferC** [comment]
This looks perfect to start out as a package

**Comment by damiendr** [comment]
I've worked on the idea [here](https://github.com/damiendr/ISPC.jl), translating a subset of Julia's typed AST to ISPC-C, but it is rather brittle with respect to changes in the IR like the new function and closure types.

I was thinking that it could be much cleaner to integrate it into Julia's codegen in the future, like the current implementation of `@simd`.

**Comment by tkelman** [comment]
I don't think we can incorporate 4 clause bsd at this time, not by default anyway, as it's not gpl compatible.

**Comment by KristofferC** [comment]
Don't see a reason to keep this open.
