### ISSUE TITLE
"WARNING: Forcibly interrupting busy workers" when trying parallel computing in script mode on server

### ISSUE THREAD

**Issue by arielleon** [JuliaLang/julia#14909]
I am trying a test parallel computation with

# main.jl
require("step.jl")
x=5
r=@spawn f(x) 

f(x) is a function I define in step.jl, 
when computing locally, it could take one minute or more.

I run this on a server, in script mode, with

julia -p 2 main.jl

However, I always get "WARNING: Forcibly interrupting busy workers" 
I tried with a simpler function, say g(x) which takes less than a second locally,
then main.jl works easily. 
So I highly suspect the reason is the main process is exiting before the workers 
have finished their tasks, from a reading of related issue. 
I wonder if anyone know how to fix this problem. 

Thanks,
Ariel

**Comment by tomaklutfu** [comment]
I think @tkelman suggested this https://groups.google.com/forum/m/#!forum/julia-users for questions.

**Comment by StefanKarpinski** [comment]
Please quote code when posting issues, especially code with macros – otherwise the GitHub user by the name of the macro gets subscribed to the issue.
