### ISSUE TITLE
@printf string precision truncate

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#14908]
the precision of the string format specification should truncate the output, and doesn't.

```
julia> @printf "%.3s" "abcdef"
abcdef
```

```
$ cat foo.c 
#include <stdio.h>

int main()
{
  printf("%.3s\n","abcdef");

  return 0;
}

$ gcc foo.c

$ ./a.out
abc
```

**Comment by simonbyrne** [comment]
We need to be careful about how we deal with UTF8 boundaries/combining characters. The exact behaviour, according to the C 1999 spec is:
> If the precision is specified, no more than that many bytes are written.

**Comment by nalimilan** [comment]
That doesn't sound like a great definition, as getting half of a codepoint wouldn't be useful for anything. OTOH, the number of bytes might have a practical interest in some cases.

Does the current `@sprintf` implementation follow the C specs?

**Comment by simonbyrne** [comment]
@nalimilan I think that's why it says "no more than", so you don't print half a codepoint.

I'm not sure how closely we follow the spec, but I believe that is the general idea.

**Comment by bjarthur** [comment]
no.  `@sprintf` is broken too

```
julia> @sprintf "%.3s" "abcdef"
"abcdef"
```

**Comment by nalimilan** [comment]
@bjarthur `@printf`/`@sprintf` clearly don't follow the specs for this particular point. We were more wondering about whether the general goal was to follow it.

@simonbyrne Yeah, but that still doesn't make much sense for UTF-8. It's a useful guaranty in C when you're writing to a buffer to avoid overflows, but in Julia that problem doesn't exist. It would be more useful to consider e.g. the number of characters, or the number of columns the string would take in a fixed-width font (which utf8proc gives us).

**Comment by bjarthur** [comment]
is there a consensus on whether/how to fix `@printf` string precision?  this issue is targeted to the 0.6.0 milestone.  i'm happy to submit a PR but need to know what folks want to do.

**Comment by bjarthur** [comment]
fixing `@printf` string precision looks relatively straightforward.  i think all that would need to change is `string($x)[1:precision]` on the following line and the three other similar ones in the same `gen_s` function:

https://github.com/JuliaLang/julia/blob/master/base/printf.jl#L641

unless we want to actually limit the bytes written per the C spec, instead of the characters, in which case it's a bit more complicated as we'd need to iteratively use `nextind`.

**Comment by JeffBezanson** [comment]
@bjarthur If you're willing to submit a PR for that change, please go ahead.
