### ISSUE TITLE
Error arised when using Pkg.add() in Julia

### ISSUE THREAD

**Issue by zlqs1985** [JuliaLang/julia#14901]
I have a problem when trying to add any package in the terminal using `Pkg.add()`, the terminal gives me the following error message:

```
fatal:your current branch 'master' does not have any commits yet
Error: failed process: Process(`git' --git-dir=````)
```
How do I fix it?

**Comment by yuyichao** [comment]
What's your `versioninfo()` and how did you installed julia.

**Comment by zlqs1985** [comment]
@yuyichao  Thanks for reply, My Julia version is 0.4.2-win64 and I install it using Julia-lang Installer downloaded from Julia website

**Comment by zlqs1985** [comment]
Complete 
![Uploading QQ截图20160201234635.jpg…]()

**Comment by zlqs1985** [comment]
complete version info
```
Julia Version 0.4.2
Commit bb73f34 (2005-12-06 21:47 UTC)
Platform Info:
  systerm: Windows(X86_64-w64-mingw32)
  CPU：
  Word_size:64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
 LIBM: libopenlibm
 LLVM:.ibLLVM-3.3
```

**Comment by tkelman** [comment]
Exactly what command did you run that resulted in the above error?

What do the following return?
```jl
Pkg.dir()
ENV["HOMEDRIVE"]
ENV["HOMEPATH"]
readdir(Pkg.dir())
```

did you mean to close this, or accidentally hit the wrong button? (It's really poorly placed, we can reopen until this gets solved)

**Comment by zlqs1985** [comment]
@tkelman  thanks for reply, here are the results of commands
`Julia.dir()`
“C:\\Users\\Zhanglu\\.Julia\\v0.4”
`ENV["HOMEDRIVE"]`
"C"
`ENV["HOMEPATH"]`
\\Users\\Zhanglu
`readdir(Pkg.dir())`
11-element  Array{Byte,string}
".cache"
"Arrayviews"
"Compact"
"Distributions"
"JulEE62.tep"
"METADATA"
"META_BRANCH"
"PDMats"
"REQUIRES"
"STATBASE"
"STATFUNS"

**Comment by tkelman** [comment]
The fact that there is a JulEE62.tep (was that a typo, supposed to be .tmp?) in there makes it look like git failed partway through cloning something. Check if there's anything in that folder that you want to keep, delete it if not. If you haven't made any local changes to any packages, you could try deleting your entire C:\Users\Zhanglu\.Julia\v0.4 folder and try again from Pkg.init(); Pkg.add("Distributions")





From: zlqs1985

Sent: Tuesday, February 2, 2:31 AM

Subject: Re: [julia] Error arised when using Pkg.add() in Julia (#14901)

To: JuliaLang/julia

Cc: Tony Kelman



@tkelman thanks for reply, here are the results of commands

Julia.dir()

“C:\Users\Zhanglu\.Julia\v0.4”

ENV["HOMEDRIVE"]

"C"

ENV["HOMEPATH"]

\Users\Zhanglu

readdir(Pkg.dir())

11-element Array{Byte,string}

".cache"

"Arrayviews"

"Compact"

"Distributions"

"JulEE62.tep"

"METADATA"

"META_BRANCH"

"PDMats"

"REQUIRES"

"STATBASE"

"STATFUNS"
