### ISSUE TITLE
master fails on git checkout behind firewall

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaLang/julia#14911]
This is due to the libgit2 deps build being unable to find the libcurl dependency. 

    /usr/bin/pkg-config --debug --modversion libcurl -> fails from make 

This is caused by the following in the build env 
```
diff --git a/Make.inc b/Make.inc
index 7734667..9667d4a 100644
--- a/Make.inc
+++ b/Make.inc
@@ -201,7 +201,7 @@ BUILD_LLDB := 0
 CMAKE ?= cmake
 
 # Point pkg-config to only look at our libraries
-export PKG_CONFIG_LIBDIR = $(JULIAHOME)/usr/lib/pkgconfig
+#export PKG_CONFIG_LIBDIR = $(JULIAHOME)/usr/lib/pkgconfig
 
 # Figure out OS and architecture
 BUILD_OS := $(shell uname)
```

Should julia build curl? Note the install step for libgit2 will have to be modified to include the curl deps if this is to still be self contained.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13472
