### ISSUE TITLE
Issue with running external programs

### ISSUE THREAD

**Issue by mwojnowicz** [JuliaLang/julia#14925]
I'm running Julia 0.3.8, commit 507821*. I  want to search through a csv to find line numbers of rows which match an expression, in this case "=", and then save the resulting row indices to a file. 

In terminal, I can do this:
    grep -n -v "=" 20150817global.json.mv.fvm.exported.csv | awk -F: '{print $1}' > ctsfeats.csv

However, in Julia, the command
    cmd=`grep -n -v "=" 20150817global.json.mv.fvm.exported.csv | awk -F: '{print $1}' > ctsfeats.csv`
    run(cmd)

Fails with this error message:

grep: invalid option -- ':'
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help` for more information.
ERROR: failed process: Process(`grep -n -v = 20150817global.json.mv.fvm.exported.csv | awk -F: '{print $1}' > ctsfeats.csv`, ProcessExited(2)) [2]
 in pipeline_error at process.jl:502
 in run at ./process.jl:479

I see that there is a "pipeline" function that I would use in Julia 0.4.x, but this doesn't appear to be available for Julia 0.3.8.

**Comment by yuyichao** [comment]
You can use `|>`.

**Comment by yuyichao** [comment]
And questions should go to the julia-users mailing list.

**Comment by mbauman** [comment]
Please see the documentation on running shell pipelines: http://docs.julialang.org/en/release-0.4/manual/running-external-programs/#pipelines

In your case, you need to explicitly create a `Pipeline`:

```jl
cmd=pipeline(`grep -n …`, `awk … args`, stdout="ctsfeats.csv"`)
run(cmd)
```

**Comment by mwojnowicz** [comment]
@mbauman Thanks.  I am on Julia 0.3.8, however.  I will try @yuyichao 's solution.  Sorry for posting to the wrong place.

**Comment by mbauman** [comment]
Right, this has changed since 0.3 — here's that version's manual: http://docs.julialang.org/en/release-0.3/manual/running-external-programs/#pipelines

**Comment by mwojnowicz** [comment]
Thanks @mbauman.  Not sure whether to finish this off here or move to Julia Users' mailing list, but I'm still getting an error with `|>`:

julia> cmd=`grep -n -v "=" 20150817global.json.mv.fvm.exported.csv` |> `awk -F: '{print $1}' > ctsfeats.csv`
`grep -n -v = 20150817global.json.mv.fvm.exported.csv` |> `awk -F: '{print $1}' > ctsfeats.csv`

julia> run(cmd)
awk: cmd. line:1: fatal: cannot open file `>' for reading (No such file or directory)
ERROR: failed process: Process(`awk -F: '{print $1}' > ctsfeats.csv`, ProcessExited(2)) [2]
 in pipeline_error at process.jl:515
 in run at process.jl:479

**Comment by StefanKarpinski** [comment]
The `|>` goes between separate backticked expressions. This is not evaluated by a shell. Please see the documentation on this, which is thorough: http://docs.julialang.org/en/release-0.3/manual/running-external-programs/#pipelines.

**Comment by mwojnowicz** [comment]
Thank you @StefanKarpinski.  However, that did not work.  The `|>` actually is in separate backticked expressions above -- as suggested in the documentation; it just doesn't appear that way in this editor because it treats backticks as demarcating the beginning and ending of code blocks.   There appears to be some other, separate issue, perhaps with the > operator to write to file.

**Comment by mbauman** [comment]
You need to also pipe to the file: 

    `grep …` |> `awk …` |> "ctsfeats.csv"`

If you have further questions, please move them to the mailing list.

**Comment by mwojnowicz** [comment]
That also did not work, but okay, I will move it to the mailing list. Thank you.
