### ISSUE TITLE
Only catch exceptions of a certain type?

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/julia#14927]
Is it possible to only catch certain exceptions? My reading of <http://docs.julialang.org/en/release-0.4/manual/control-flow/#man-exception-handling> makes it seem like you have handle all exceptions.

E.g. something like this isn't possible

```{.julia}
try
    Int64(8.1)
catch InexactError as x
    #handle inexacterror only
end
```
which is (IMO) way more readable than the current solution because it only handles `InexactError`s, which means that every other error will still propagate up to the user. Compare it to this:

```{.julia}
try
    Int64(8.1)
catch x
    if isa(x, InexactError)
        # handle inexacterror only
    else
        throw(x) #handle every other error
    end
end
```

(and yes I'm coming from Python)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7026

**Comment by samoconnor** [comment]
Hi @tlnagy, you might find the `@protected try...` macro useful: https://github.com/samoconnor/Retry.jl

`julia> Pkg.add("Retry")`
