### ISSUE TITLE
Kernel error in IJulia Jupyter Notebook

### ISSUE THREAD

**Issue by lamiastella** [JuliaLang/julia#14931]
Can someone look at this error in SO and provide me with a fix?
http://stackoverflow.com/questions/35195061/kernel-error-in-ijulia-notebook

**Comment by lamiastella** [comment]
Pkg.update()
Pkg.build("IJulia")
using IJulia; notebook()

**Comment by kmsquire** [comment]
Looks like you found your own answer!  

For future reference, this type of question/request is better suited for the julia-users mailing list (or   StackOverflow, where you posted).  This area is for actual bugs in Julia itself.  If there's a bug in IJulia (the Jupyter interface), then https://github.com/JuliaLang/IJulia.jl is a better place.
