### ISSUE TITLE
Unnamed module

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#14938]
I have a strange use case where I want to have a temporary module for testing. Something similar to:

``` julia
julia> module X
       eval(:(f() = 1))
       end
X

julia> X.f()
1
```

Eventually I was tinkering with the idea with having a unnamed module:

``` julia
julia> module Y
       error("A")
       end
ERROR: A
 in error(::ASCIIString) at ./error.jl:21
 in eval(::Module, ::Any) at ./boot.jl:267

julia> module
       error("A")
       end
error

julia> module
       error("A")
       error("B")
       end
WARNING: replacing module error
ERROR: MethodError: no method matching argtype(::ASCIIString)
 in eval(::Module, ::Any) at ./boot.jl:267
```

Obviously what is happening is that the module in my example is being named "error". I would expect either this would work as unnamed module (as I expected) or Julia should expect a module name to be on the same line as `module` keyword and a syntax error should be thrown if it is missing.

**Comment by simonster** [comment]
I agree that Julia should require the module name to be on the same line as the `module` keyword, but if you want to create an anonymous module, you could do that like so:

```julia
julia> X = Module()
anonymous

julia> eval(X, :(f() = 1))
f (generic function with 1 method)

julia> X.f()
1
```

**Comment by mbauman** [comment]
More recent discussion at #40189

**Comment by omus** [comment]
@mbauman sounds good to me. One reason we may want to re-open this is to address the issue that Julia doesn't require the module name to be defined on the same line as the `module` keyword. That said adding support for unnamed modules would require that problem to be addressed.
