### ISSUE TITLE
Method ordering error

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#14935]
Noted [here](https://github.com/JuliaStats/DataFrames.jl/issues/906):

```julia
julia> Pkg.test("GZip")
INFO: Testing GZip
WARNING: New definition
    write(GZip.GZipStream, Array{#T<:Any, N<:Any}) at /Users/kmsquire/.julia/v0.5/GZip/src/GZip.jl:456
is ambiguous with:
    write(Base.IO, Array{UInt8, N<:Any}) at io.jl:154.
To fix, define
    write(GZip.GZipStream, Array{UInt8, N<:Any})
before the new definition.
```

This seems like an bug.  `GZipStream` is a concrete subclass of `IO`, so shouldn't the definition involving it take precedence?

```julia
julia> versioninfo()
Julia Version 0.5.0-dev+2440
Commit 2bb94d6 (2016-02-01 02:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM)2 Extreme CPU X7900  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Core2)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
```

**Comment by yuyichao** [comment]
Why is this a bug? The first method only works with `GZipStream` and the second method only works with `Array{UInt8}` so they are indeed ambiguous?

**Comment by yuyichao** [comment]
In another word, `write(::GZip.GZipStream, Vector{Int})` only matches the first one and `write(::IOBuffer, Vector{UInt8})` only matches the second one so none of them are more specific than the other so they are ambiguous.

I remember there's some discussion about sorting the method using the first argument first but I don't think we have that yet.

**Comment by kmsquire** [comment]
Hmm.. Okay.  

I see that this was caused by #14766, so `GZip.jl` will have to be updated to deal with that then.

**Comment by carnaval** [comment]
> I remember there's some discussion about sorting the method using the first argument first but I don't think we have that yet.

as an aside, please no. the fact that our multiple dispatch is symmetric is to me what makes it elegant

**Comment by kmsquire** [comment]
No worries--I think it was just my misunderstanding.  Cheers!
