### ISSUE TITLE
code_typed causes inference, removes some :meta information

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14942]
Given the following source:

```
Base.@pure foo() = return nothing
@code_llvm foo()
```

`@pure` sets `linfo.pure` in `inference.jl` (`linfo.pure = popmeta!(body, :pure)[1]`) which works fine:

```
$ gdb --args julia ./bug.jl
(gdb) break jl_get_llvmf
...
Temporary breakpoint 2, jl_get_llvmf (f=0x7ffdf01f4020, tt=0x7ffdf3593f70, getwrapper=false, getdeclarations=false) at julia/src/codegen.cpp:1460
1460	        linfo = jl_get_specialization1(tt, NULL);
(gdb) n
(gdb) p linfo.pure
$1 = 1 '\001'
```

However, if I first call `code_typed`, the `:meta` attribute is lost, probably because inference is run twice while `popmeta!` destructively removes the attribute after which the AST is saved again. Example:
```
Base.@pure foo() = return nothing
@code_typed foo()
@code_llvm foo()
```
```
$ gdb --args julia ./bug.jl
(gdb) break jl_get_llvmf
...
(gdb) p linfo.pure
$1 = 0 '\000'
```

There is also a non-destructive assignment to `li->pure` in `alloc.c`:
```
jl_lambda_info_t *jl_new_lambda_info(jl_value_t *ast, jl_svec_t *tvars, jl_svec_t *sparams,
                                     jl_module_t *ctx)
...
        if (has_meta(body, pure_sym))
            li->pure = 1;
...
```

Putting a breakpoint there reveals that pure is first set to 1, and later overwritten with 0 during inference.

I'm not sure what needs fixing here: the `linfo->pure` assignment overwriting what had been set previously already, make that inference isn't run twice when using `code_typed`, or fix the use of `popmeta!` such that the modified AST isn't saved afterwards.

Some back-story to what might seem like a contrived example: when running CUDA.jl in debug mode, the AST is dumped before code is generated, but at that point the `@target ptx` annotation (which uses `popmeta!` just like `@pure` does) has been removed.

**Comment by vtjnash** [comment]
i expect #15396 will fix this

**Comment by JeffBezanson** [comment]
Yes, I think it does.

**Comment by maleadt** [comment]
Sorry for the late response; this has gotten fixed indeed. Couldn't figure out a test though, as it only seemed to happen with `@pure` and I couldn't find a side-effect visible in the `code_llvm` output.
