### ISSUE TITLE
Confusing error thrown when mapping over a non-function

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#14940]
```jl
julia> x=map(randn(1), 1:10^6) #First argument is a number not a function
ERROR: MethodError: `call` has no method matching call(::Array{Float64,1}, ::Int64)
Closest candidates are:
  BoundsError()
  BoundsError(::Any...)
  DivideError()
  ...
 in map at abstractarray.jl:1305
```

~~Looks like the error handling code in `map()` isn't quite right.~~ This error is probably very confusing for a new user.

Observed on 0.4.3 release.

**Comment by yuyichao** [comment]
The error should have changed on master after `jb/functions` bug what's wrong with the error reported?

`randn(1)` returns a `Vector{Float64}` and the error is complaining that you can't call it on `Int64` which is the `eltype` of `1:10^6`.

**Comment by jiahao** [comment]
The error isn't wrong, just rather confusing, especially to a new user who doesn't know anything about call overloading

**Comment by yuyichao** [comment]
I see. This doesn't seem to be `map` specific though. Maybe when the object being called is not a `Function` we should say something like `the object cannot be called with signature ...` instead?

**Comment by jiahao** [comment]
I like that phrasing

**Comment by JeffBezanson** [comment]
Now the error reads

```
ERROR: MethodError: no method matching (::Array{Float64,1})(::Int64)
```

We could add a check in replutil for objects not of type Function that says something like: "object foo is not a function".

**Comment by vtjnash** [comment]
perhaps instead of `isa(f, Function)`, we could check `isdefined(typeof(f).name, :mt)` as a heuristic?

**Comment by JeffBezanson** [comment]
I think that check is always true. You can check whether the table is empty though.
