### ISSUE TITLE
Pkg.publish before tagging a version.

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#14944]
The [packaging docs](http://docs.julialang.org/en/latest/manual/packages/#tagging-and-publishing-your-package) suggest that you should `Pkg.publish()` before tagging a version. However this is not allowed by the travis check on METADATA.

We should update the docs, and possibly add a check to `Pkg.publish` that a version has been tagged.

cc @tkelman

**Comment by jiahao** [comment]
The manual could use a cross-reference to METADATA's README

https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md

**Comment by tkelman** [comment]
any code change to Pkg.publish should be opened as an issue in PkgDev.jl for 0.5

**Comment by goelakash** [comment]
So the package should be tagged before publishing?

**Comment by kshyatt** [comment]
Seems we can close this and if it's still a problem, deal with it over at PkgDev?

**Comment by tkelman** [comment]
we still need to update the package development docs here

**Comment by simonbyrne** [comment]
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl
