### ISSUE TITLE
LLVM patches are filtered out by Julia's .gitignore

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14975]
I notice that Julia keeps LLVM patches in the `deps` directory and names them `llvm-*.patch`. At the same time, there is a `.gitignore` filter `/llvm-*` in the `deps` directory that hides the patches.

I think the `.gitignore` filters may be outdated, and might be a relic from before the build directories were reorganized.

**Comment by vtjnash** [comment]
yes, we can probably change that now. I left them in place so devs could switch between v0.4 builds and master without showing lots of untracked files. but that's less important / useful as master gets more distant from the release
