### ISSUE TITLE
Add way of exposing functions for testing but not exporting them in a package

### ISSUE THREAD

**Issue by rawls238** [JuliaLang/julia#14978]
Guava has something similar with its [VisibleForTesting](http://guava-libraries.googlecode.com/svn/tags/release09/javadoc/com/google/common/annotations/VisibleForTesting.html) annotation. It would be nice to be able to test internal helper functions without having to export them in a module (let me know if you can already do this but I just can't figure out how to do so).

For instance, I might have a function called `fooHelperMethod` that I use for some internal logic that I want to write a unit test for, but I don't want to export this function so that users of the package can actually utilize it since it's intended to be a private helper function. However, when I run my tests I bring in the module and unless I export that function I'm not able to explicitly write a unit test for it.

**Comment by KristofferC** [comment]
You can always just `import Foo.fooHelperMethod` or explicitly specify it `@test Foo.fooHelperMethod() == true`.

**Comment by rawls238** [comment]
Interesting didn't know that, thanks!
