### ISSUE TITLE
TypeError constructing Val of a function

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14988]
Constructing a `Val` seems to fail when passing a function, but only for certain functions and not in all cases:

```julia
let
    inner() = return nothing
    outer() = return inner()

    @show Val{inner}   # this works
    @show Val{outer}   # this doesn't, unless when removing the let ... end
end
```

This is probably right up @JeffBezanson's alley.

**Comment by tkelman** [comment]
shouldn't only bitstypes be allowed for type parameters?

**Comment by vtjnash** [comment]
don't use `Val`

in this case, you can use `typeof(inner)` / `typeof(outer)` instead

**Comment by maleadt** [comment]
@vtjnash This is obviously a reduced example... I'm using this construction to pass a value to a generated function, which I though `Val` was meant to be used for?

**Comment by yuyichao** [comment]
Passing a value to a generated function is fine. You should just pass the function directly.

**Comment by maleadt** [comment]
Not if I want to dispatch on the value and/or need to use the value within the generated function.

Let me illustrate my use-case:
```julia
macro decorate(call::Expr)
    f = call.args[1]
    args = call.args[2:end]

    f_const = :(Val{$f}())
    esc(Expr(:call, actual_decoration, f_const, args...))
end

@generated function actual_decoration{F}(f::Val{F}, args::Any...)
    # do something very concrete with F here,
    # as an example, calling it
    F()
end

let
    inner() = println("calling inner")
    outer() = return inner()

    @decorate inner()   # this works
    @decorate outer()   # this doesn't, unless when removing the let ... end
end
```

This is extracted from CUDA.jl, where rather than calling the function, it is passed to the compiler in order to generate PTX assembly (as we can't `call` PTX functions directly). Using this generated function makes that compilation happens as early as possible, without runtime overhead.

**Comment by JeffBezanson** [comment]
Then you're going to love this:

```
julia> f(x) = x
f (generic function with 1 method)

julia> g(x) = 2x
g (generic function with 1 method)

julia> typeof(f)
#f

julia> typeof(g)
#g
```

In 0.5 the type of the function tells you which function you have.

**Comment by maleadt** [comment]
Oh, I completely missed that aspect of `jb/functions`, or at least its implications for this use case.
No need for `Val` indeed, thanks!

**Comment by maleadt** [comment]
@JeffBezanson What is the best way to reverse this process and get a function instance from its type? `((jl_datatype_t*)tupletype)->instance`? Any syntax to accomplish this?
I would like to use `_dump_function` (or similar) from my decorator, but these expect a normal function.

**Comment by vtjnash** [comment]
you can't always, although `jl_datatype_t->instance` will work if anything is possible. it will fail for closures and other types with fields however.
