### ISSUE TITLE
Heaviside function

### ISSUE THREAD

**Issue by pabloferz** [JuliaLang/julia#14981]
Would it be too much to have a `heaviside`function in base? Something like

```julia
heaviside(x::AbstractFloat) = ifelse(x < 0, zero(x), ifelse(x > 0, one(x), oftype(x,0.5)))
```

**Comment by jiahao** [comment]
I suppose so, but I don't really see much use for Heaviside functions in numerical code. Any good examples of when you'd use it in practice?

**Comment by pabloferz** [comment]
I don't have any good example. I have used the SymPy's to write some superpositions of planewaves.

The real reason I was thinking of having one is beacuase I was writing a printing method in SymPy to generate the equivalent Julia form. I guess it makes more sense to have the function in SymPy.jl to allow the translation of symbolic expressions to fast Julia methods.

**Comment by mschauer** [comment]
The function is mostly used as distribution, where it does not matter which value it takes at zero. A symbolic integration package might define ``heaviside`` as formal object. But I don't think it is needed as a real function

**Comment by pabloferz** [comment]
Of course, it is not needed as a real function. As I said, it was motivated from the idea to translate SymPy to Julia code and it probably makes more sense over SymPy.jl than in Base. I'll close this.

**Comment by moustachio-belvedere** [comment]
In case this is still of interest to anyone, a numerical example where a library piecewise function would be nice (I'm fitting to this function today):

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2744968/

See equation 2.
