### ISSUE TITLE
SLP Vectorizer initialization error with LLVM SVN

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#14998]
I've just got a LLVM pass initialization error on ARM and AArch64 with LLVM svn (~1weeks old llvm on aarch64 and today's llvm trunk on arm, julia master as of a few hours ago on both) with `-O3`

```jl
alarm% julia -O3                                     
Pass 'SLP Vectorizer' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
        Assumption Cache Tracker
        Scalar Evolution Analysis
        Function Alias Analysis Results
        Target Transform Information
        Natural Loop Information
        Dominator Tree Construction
[1]    13074 segmentation fault  julia -O3
```

More precise version info

AArch64
```jl
julia> versioninfo()
Julia Version 0.5.0-dev+2552
Commit 82f810d* (2016-02-08 14:04 UTC)
Platform Info:
  System: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY ARMV8)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.9.0svn-r259620
```

ARM (note that the CPU is a aarch64 CPU in 32bit mode)
```
julia> versioninfo()
Julia Version 0.5.0-dev+2552
Commit 82f810d* (2016-02-08 14:04 UTC)
Platform Info:
  System: Linux (armv7l-unknown-linux-gnueabihf)
  CPU: Cortex A57 Processor rev 1 (aarch64)
  WORD_SIZE: 32
  BLAS: libopenblas (NO_AFFINITY CORTEXA9)
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.0svn-r260101
```

I don't have a LLVM svn build for x86 but I think it's likely that this issue is not arm/aarch64 specific.

**Comment by yuyichao** [comment]
This is happening on the llvm-svn buildbots and I've also verified locally on x64 so this issue is not arm/aarch64 specific. Judging from the [buildbot log](http://buildbot.e.ip.saba.us:8010/builders/nightly_llvmsvn-x64?numbuilds=45), it probably happened in the past month.

**Comment by yuyichao** [comment]
(It is also possible that we just didn't used to have a test for the `-O` option.....)

**Comment by Keno** [comment]
Fixed upstream as http://reviews.llvm.org/rL263476.

**Comment by yuyichao** [comment]
I didn't expect the LLVM review to go through this fast.... otherwise I would have just do that instead....

Part of #15493 can be reverted now although keeping it for a while should be harmless (and could help ppl that doesn't have the most up-to-date llvm-svn).
