### ISSUE TITLE
greater/less for bools

### ISSUE THREAD

**Issue by marsue** [JuliaLang/julia#15015]
I noticed that Julia allows greater/less comparisons for bool-type variables. So the following expressions are valid:
```jl
julia> true>false
true
julia> true<false
false
```
Is this intentionally or some kind of C/C++ compatibility? Since from the mathematical point of view it does not make much sense to compare bools except for equality.

**Comment by nalimilan** [comment]
Please use the mailing list for questions like this. This basically comes from the fast that `Bool<:Number`, with `true` being equivalent to `1` and `false` to `0` for all operations. This is convenient in many cases, but it can also be surprising. A funny one I just discovered today:
```julia
julia> typemax(Bool)
true

julia> typemin(Bool)
false
```
