### ISSUE TITLE
Base.Test should not print anything by default

### ISSUE THREAD

**Issue by jkroso** [JuliaLang/julia#15027]
The new Base.Test looks really good. I will probably use it in place of [my own library](//github.com/jkroso/jest.jl). However I think it needs a better system for reporting results.

Currently `@resultset` will print a summary before returning a `DefaultTestSet`. There are a few use cases where this will cause problems:

- CI: A CI tool will probably want to be able to produce [TAP](https://testanything.org) while also rendering to the console
- Inline tests: I personally like to put my tests inside my source code and run them interactively whenever I change the code they test. Doing this would cause my tests to log results whenever my source is loaded or run. So I won't be able to inline tests
- Custom output: [as usual people will have their own opinions on how the results should look](https://github.com/JuliaCI/BaseTestNext.jl/pull/5)

I think instead it should emit test results on an [event emitter](//github.com/jkroso/emitter.jl) (or actually a set of singly linked lists would be better) and return a result. This result should have its `show` method defined the way results are currently printed.

BTW I'm happy to do the work if that suits I just want to make sure there is agreement before I make the effort.

cc: @IainNZ

**Comment by tkelman** [comment]
Making this customizable via user-defined handlers (including a few pregenerated commonly-used ones perhaps) sounds like a good idea. Ref https://github.com/JuliaLang/julia/pull/14971, @robertfeldt had some related proposals in this area. May want to coordinate efforts.

**Comment by robertfeldt** [comment]
Yes, I agree with this and I'm working on both a new TestReporter interface and integration as well as a more customizable way to add the testing of additional/different test assertions (now, we basically (only) have TestComparisonPredicate, TestPredicate and TestExceptionThrown even if not made explicit; people might want to add their own and have it hook easily into the framework). If you give me a few days and I can have a draft that we can iterate; I'm currently on a business trip so can commit this weekend.

**Comment by tkelman** [comment]
Ideally each separate addition would be its own mostly-independent PR. Reporting does not have to be in the same PR as modified predicates.

**Comment by robertfeldt** [comment]
Ok, yes, then I'll first work on the modified predicates and modified @testset hooks and will try to even keep those two in separate PRs. You can take a stab at the updated event emitter then @jkroso ... :)

**Comment by jkroso** [comment]
@robertfeldt Ok sounds good. I think I'll actually go with the linked list approach to start with since it will clearly be better even though it will take a bit more code to implement

**Comment by robertfeldt** [comment]
@jkroso I prefer event emitting and event listeners since saving every test event might take very much space when you come to automated, repeated testing etc. Isn't a way to hook in event listeners better than saving them all in lists? Or am I misunderstanding you? :)

**Comment by jkroso** [comment]
Yea I'll just have to make sure I don't hold on to the start of the list to handle that case. The advantage of linked lists is that they can implement the iterator methods which should make reporters a lot nicer to write.

**Comment by jkroso** [comment]
a simple reporter will just be `foreach(report, results)` with multiple dispatch on the type of result.

**Comment by jkroso** [comment]
can't do it without breaking existing test suites while supporting all use cases I care about. See #15055 for a little bit more info
