### ISSUE TITLE
After using print_with_color, text is printed as :normal even when improper

### ISSUE THREAD

**Issue by LachlanGunn** [JuliaLang/julia#15028]
Currently `print_with_color` prints the code for `:normal` after it has finished.  While normally this is fine, when used in a `show` implementation it produces a change in colour that has to be undone.  Here is some example code to demonstrate:

```
module PWCTest

import Base: print, show

type QuestionAnswer
    question::AbstractString
    answer::AbstractString
end

function print(io::IO, qa::QuestionAnswer)
    print(io, "No color: ")
    print(io, qa.question, " ", qa.answer, "\n\n")

    print(io, "   Color: ")
    print_with_color(:red, io, qa.question)
    print(io, " ",  qa.answer)
end

show(io::IO, qa::QuestionAnswer) = print(io, qa)

qa = QuestionAnswer("Is this a rhetorical question?", "No.")

end
```

And at the REPL:
![image](https://cloud.githubusercontent.com/assets/427759/12976744/93664376-d0c6-11e5-9004-951d0a30f906.png)

I have not yet dug into the code enough to work out how I should go about fixing this, but my initial instinct is to add a new field `current_color` to Base/client.jl, then before when we call `show()` in client.jl we can change it to `default_color_answer`, and back to `normal_color` afterwards.

Does anyone else have any thoughts?

**Comment by vtjnash** [comment]
I had started development on fixing this at https://github.com/JuliaLang/julia/compare/jn/iocolor, but got sidetracked with other issue questions.

**Comment by kshyatt** [comment]
I see the same behaviour in the REPL on master (nice example, btw).

**Comment by KristofferC** [comment]
Do you?

![image](https://cloud.githubusercontent.com/assets/1282691/22322682/18101062-e39e-11e6-954c-6386eb229e60.png)

**Comment by tkelman** [comment]
it would if you manually re enabled bold though.

**Comment by KristofferC** [comment]
No because I thought I fixed that in the `print_with_color` no longer default to bold PR:

![image](https://cloud.githubusercontent.com/assets/1282691/22323125/d5fd28e2-e3a0-11e6-920c-1756764941be.png)

**Comment by KristofferC** [comment]
This is even tested for. Maybe @kshyatt can elaborate on what it prints for her.

**Comment by KristofferC** [comment]
`@kshyatt` told me there is no problem here.

Note that using `print_with_color(...; bold = true)` will make this reappear but there is no way to keep track of the current text state. For that type of control you need something like https://github.com/KristofferC/Crayons.jl#nesting-colors-and-styles.

**Comment by tkelman** [comment]
Then what was happening with
> I see the same behaviour in the REPL on master

?

**Comment by KristofferC** [comment]
Sleep deprivation ;)

**Comment by tkelman** [comment]
why the game of telephone?

**Comment by KristofferC** [comment]
Not sure what that means.
