### ISSUE TITLE
`error: argument to ‘-O’ should be a non-negative integer` with gcc 4.7

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#15020]
Building `libccalltest` errors out with this message. Changing `-Og` to `-O0` in Make.inc fixes it.

**Comment by yuyichao** [comment]
Only `libccalltest`?

**Comment by yuyichao** [comment]
Seems that `-Og` is [new in gcc 4.8](https://gcc.gnu.org/gcc-4.8/changes.html).

**Comment by JeffBezanson** [comment]
Ah, ok. We document that gcc 4.7 or later is required, and I think it would be silly to increase the version requirement just for this switch.

**Comment by hammadattari** [comment]
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’ or ‘fast’
AmberTools/src/cpptraj/src/readline/CMakeFiles/readline.dir/build.make:62: recipe for target 'AmberTools/src/cpptraj/src/readline/CMakeFiles/readline.dir/bind.c.o' failed
make[2]: *** [AmberTools/src/cpptraj/src/readline/CMakeFiles/readline.dir/bind.c.o] Error 1
CMakeFiles/Makefile2:574: recipe for target 'AmberTools/src/cpptraj/src/readline/CMakeFiles/readline.dir/all' failed
make[1]: *** [AmberTools/src/cpptraj/src/readline/CMakeFiles/readline.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
