### ISSUE TITLE
Modify documentation after deprecation of |>

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#15041]
doc/stdlib/base.rst says
``run(`cat test.txt` |> DevNull)``

Perhaps change to
``run(pipeline(`cat test.txt`, DevNull))``

Also, consider adding a reference to DevNull to the Pipelines section of doc/manual/running-external-programs.rst

**Comment by nalimilan** [comment]
Would you make a pull request to fix this? You can do this online on GitHub.

**Comment by pkofod** [comment]
This was fixed in #15047 right?

**Comment by yuyichao** [comment]
Thanks for pointing that out, I guess github didn't pick it up...
