### ISSUE TITLE
Passing function to generated function breaks stuff

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#15043]
I've understood that since `jb/functions` has merged, each function has a unique type, so I was surprised that in the following snipped the `decorate` generated function isn't called twice:
```julia
@generated function decorate(t)
    println("Generated function executing for $t")
end

foo() = return nothing
decorate(foo)

bar() = return 1
decorate(bar)
```
```
Generated function executing for #foo
```

However, it seems like there's something iffy going on:
```julia
@generated function decorate(t)
    println("Generated function executing for $t")
end

foo() = return nothing
decorate(foo)

decorate("bar")
```
```
Generated function executing for #foo
```

Calling `decorate` with a function argument seems to breaks something; introducing calls _before_ `decorate(foo)` does work as expected.

**Comment by JeffBezanson** [comment]
Ah, my logic for reusing generated code for multiple function types might not be taking staged functions into account.

**Comment by JeffBezanson** [comment]
I think this was fixed by 63fa569300547c17a4f2eae8a883da815f4ae4da. Plz reopen if not.

**Comment by tkelman** [comment]
can this be tested?

**Comment by maleadt** [comment]
Fixed, thanks! Will submit a PR for testing this.
