### ISSUE TITLE
Colon overflows

### ISSUE THREAD

**Issue by lvnguyen** [JuliaLang/julia#15050]
```
julia> 1:big(2^63)
0-element UnitRange{BigInt}
```

Seems to be an issue with promote unable to handle bigInt
```
promote(big(2^63))
(-9223372036854775808,)
```

**Comment by eschnett** [comment]
That's unfortunately working as intended.

`2^63` is a large negative number; applying `big` doesn't change this; and the range is thus empty.

You can write `1:big(2)^63` instead, which switches to `BigInt` arithmetic before the overflow occurs.

**Comment by lvnguyen** [comment]
Sorry, silly me. Keep forgetting that I need to convert to bigInt first.
