### ISSUE TITLE
Build fails with JULIA_THREADS=1 again

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#15053]
Fails at f7d75b5; my last successful build was at d2f6428.

```
$ make
    JULIA usr/lib/julia/inference0.ji
LLVM ERROR: Program used external function 'jl_get_ptls_states.ptr' which could not be resolved!
make[1]: *** [/home/sachs/src/julia-multithreading/usr/lib/julia/inference0.ji] Error 1
make: *** [julia-inference] Error 2
```

**Comment by yuyichao** [comment]
did you clean it?

**Comment by josefsachsconning** [comment]
Do you mean `make clean`?  Yes.

**Comment by KristofferC** [comment]
I've had similar errors when I had a path to a different julia library in my library path.

**Comment by yuyichao** [comment]
I won't be surprised if the codegen_rewrite2 breaks it. I'll have a look at it later if no one beats me.
