### ISSUE TITLE
Inner function signatures cannot depend on static parameters

### ISSUE THREAD

**Issue by jgoldfar** [JuliaLang/julia#15068]
Defining
```
function dotest{T}(x::T)
    subf(x2::T)=println(x, ", ", x2)
    subf(one(x))
end
dotest(1.1)
```
gives "LoadError: UndefVarError: T not defined", but evidently it is. See https://groups.google.com/forum/#!topic/julia-users/Fvfmvtq8xVs and https://github.com/JuliaLang/julia/pull/13412#issuecomment-175200009

**Comment by JeffBezanson** [comment]
Yes, this affects at least NLsolve and SimJulia (see https://github.com/JuliaLang/julia/pull/13412#issuecomment-175200009). I think I'll be able to fix this before 0.5-final.

**Comment by scidom** [comment]
Lora also depends on this getting fixed as far as v0.5 is concerned.

**Comment by davidanthoff** [comment]
@scidom is this something that would block Lora from running on 0.5.0 until fixed in 0.5.1, or could you work around this somehow? If the former, please scream loudly now and try to convince the core team to make this a release blocking issue for 0.5.0 (my selfish reason for this is that I won't be able to update to julia 0.5 unless Lora runs on it).

@tkelman [as the (un?)official release manager].

**Comment by tkelman** [comment]
You don't need to ping me personally on this kind of thing, but thanks for the bump, a few more of these would be valuable. If you want to keep track of them in a single place, one comment per person on #17418 with a checklist of "issues/PR's I would personally like someone to look at before the release" would be a good idea. Everyone is likely to have their own such list, if issue numbers have already been linked from anyone else's comment there then just a +1 reaction is most appropriate.

**Comment by StefanKarpinski** [comment]
Unfortunately, @JeffBezanson is the person who would fix this and he just went on vacation, so I think it's a bit too late for this to make it into the 0.5.0 release.

**Comment by scidom** [comment]
@davidanthoff I just saw your message above, I can confirm that this now is not stopping Lora from running on Julia v0.5 anymore. In fact, I tried to update Lora today to work with v0.5, let me know if you have any issues.
