### ISSUE TITLE
System error when trying to read file in another directory on ubuntu

### ISSUE THREAD

**Issue by Stivanification** [JuliaLang/julia#15061]
I'm new to Ubuntu and Julia, so this might really be an Ubuntu issue and I'm sorry if this isn't the right place to ask for help for my problem. I'm running a .jl file on Ubuntu 14.04 with Julia 0.4.2 which I know works fine, but for some reason it doesn't on my system. This is my terminal in/output: 
```
julia> include("testscripts.jl")
show_Neumann (generic function with 1 method)

julia> show_Neumann()
ERROR: SystemError: opening file Geometries/mesh_s_p05.msh: No such file or directory
 in open at ./iostream.jl:90
 in open at ./iostream.jl:102
 in read_mesh at /home/stievahn/Documents/SPDE-Heitzinger/nsh_elliptic.git/Julia Package/elliptic.jl:20
 in show_Neumann at /home/stievahn/Documents/SPDE-Heitzinger/nsh_elliptic.git/Julia Package/testscripts.jl:5
```
Maybe this is a permission issue, so I tried running julia with sudo, but that didnt change anything, and I know the file is actually located in that directory.

**Comment by yuyichao** [comment]
Please use the julia-users mailing list for questions.

**Comment by tomaklutfu** [comment]
Hi @Stivanification, welcome to julia. Github is for bug reports only. You can ask this kind of question at
https://groups.google.com/forum/m/#!forum/julia-users
Having said that, I think you either need to change working directory to ../Geometries or provide the function that uses .msh file with full path to it.
