### ISSUE TITLE
Warning for deprecated call syntax even if you try to avoid it

### ISSUE THREAD

**Issue by jgoldfar** [JuliaLang/julia#15065]
Been following the latest function changes with interest, but disappointed that trying to conditionally use new syntax doesn't seem to work. For example, the following code correctly uses the new syntax, but still warns about the use of old syntax...

```
immutable Num{T}
           val::T
end

if VERSION >= v"0.4" && VERSION < v"0.5-"
       Base.call(n::Num) = println("Old: ", n.val)
elseif VERSION >= v"0.5-"
       (n::Num)() = println("New: ", n.val)
end

v = Num(-0.2)
v()
```

Would be happy to take a look into fixing this, but would need a pointer on where to look.
Thanks

**Comment by StefanKarpinski** [comment]
Syntax, by definition, involves parsing, not execution.

**Comment by jgoldfar** [comment]
Got it, makes sense. So this is something that would have to be handled by Compat? I suppose I will look to that
