### ISSUE TITLE
Error with Juno-Julia bundle on Windows 10W

### ISSUE THREAD

**Issue by kiplimw** [JuliaLang/julia#15066]
Hi,

I downloaded the juno-windows-x64.zip file and extracted the files.  I do not see a installer for Julia. When I run the Juno.exe file I get the following messages:

ERROR: Requires not found
 in require at loading.jl:47
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at client.jl:285
 in _start at client.jl:354

I then downloaded the and executed the file julia-0.4.3-win64.exe .

When I run Juno again, I get the same error messages.

Mike

**Comment by tomaklutfu** [comment]
You can direct this questions to
https://groups.google.com/forum/m/#!forum/julia-users
Github is only for julia bug reports.
