### ISSUE TITLE
Don't use `-pipe` in Makefile

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15063]
I am building Julia on a Raspberry Pi, and I find that the `-pipe` flag that is used in Julia's Makefile in several places hurts performance. With this flag, the compiler and assembler are running at the same time, making the system swap.

Julia should either not be using `-pipe`, or there should be a convenient way to remove this flag. Currently, this flag is used in several (five?) different locations; a simpler way to override this would be convenient.

**Comment by ViralBShah** [comment]
I think given that the Pi 3s are common now and we have arm binaries, this may not be necessary.
