### ISSUE TITLE
Readme.md not clear

### ISSUE THREAD

**Issue by rushikesh90** [JuliaLang/julia#15074]
In readme.md , below instruction of git checkout release, it is written as "now run make", but since the procedures for different platforms to build is different , the links should be mentioned before instructing to run make.

**Comment by nalimilan** [comment]
Thanks for the report. Could you make a pull request to fix this? You can edit this file directly fro GitHub.

**Comment by ivarne** [comment]
Seems like this was fixed by #15236. Feel free to suggest improvements if it could be even better.
