### ISSUE TITLE
New segfault in build during inference

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15079]
I see a new segfault 100% of the time when building RPM nightlies using LLVM 3.7.1 (including the three Julia patches). It has been introduced over the last two days.

I can do some debugging if you tell me what you need to know.

```
cd /builddir/build/BUILD/julia/base && /builddir/build/BUILD/julia/build/usr/bin/julia -C x86-64 --output-ji /builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl
/bin/sh: line 1: 14588 Segmentation fault      (core dumped) /builddir/build/BUILD/julia/build/usr/bin/julia -C x86-64 --output-ji /builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl
Makefile:214: recipe for target '/builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji' failed
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00159825-julia/build.log.gz

**Comment by vtjnash** [comment]
`cd /builddir/build/BUILD/julia/base && gdb --args /builddir/build/BUILD/julia/build/usr/bin/julia-debug -C x86-64 --output-ji /builddir/build/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl`

would be helpful to understand where this is failing, since it seems it is failing to start.

(you aren't trying to build with JULIA_THREADS=1, are you? https://github.com/JuliaLang/julia/issues/15053)

**Comment by yuyichao** [comment]
Also, unless the backtrace is not working at all there, it seems that we haven't got to the point to install our own signal handler yet? (since we should be printing the backtrace and a few other status otherwise)

**Comment by yuyichao** [comment]
I'm seeing this too on archlinux 32bit too. It seems that we are codegening `boot.jl` when the segfault happens. For some reason the module doesn't have `julia.gc_root_kill` and there seems to be other inconsistent states too.

**Comment by yuyichao** [comment]
Also, it looks like `finalize_gc_frame(Function*)` failed to lower our intrinsics to create a gc frame.

**Comment by nalimilan** [comment]
I guess my input is no longer needed since @yuyichao is able to reproduce it. But tell me if I should run something to help debugging.

**Comment by yuyichao** [comment]
@nalimilan I think the issue is that codegen_rewrite2 breaks MCJIT and I was accidentally using it since I forgot that my hack for enabling orcjit in julia was only working on 64bit.... (I was overriding the wrong header....)

It seems that you are using MCJIT too and you could use something similar to the trick used in [.travis.yml](https://github.com/JuliaLang/julia/blob/e160742f457e52df4bde3c7e599940c2239bef62/.travis.yml#L75) to enable ORCJIT since you are using our patch version of llvm.

**Comment by nalimilan** [comment]
Note this happens on both 32- and 64-bit.

I don't really care about whether the packages use MCJIT or ORCJT: I'd rather use the default settings to ensure they are extensively tested.

**Comment by yuyichao** [comment]
The default setting is ORCJIT and not MCJIT, if you are using a system llvm 3.7.1 it (ORCJIT) will not be automatically enabled even if you have our patch applied since there's no way we can tell that. Therefore, in such cases, you should enable ORCJIT manually.

**Comment by yuyichao** [comment]
> Note this happens on both 32- and 64-bit.

The comment that this happens for me on 32bit only was just because the way I packaged the patched llvm that includes the hack. If you are not doing anything special (apart from applying the patch) for your llvm package, it doesn't really apply.

**Comment by nalimilan** [comment]
OK, thanks. I'll enable it then, and I'll keep it that way for the official distribution packages when 0.5 is released.

I've tried building your branch, and it still fails: https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00160011-julia/build.log.gz

**Comment by yuyichao** [comment]
In that case I think it would be useful to get a backtrace.

**Comment by nalimilan** [comment]
Here it is (it happens almost immediately):
```
(gdb) r
Starting program: /home/milan/Dev/rpmbuild/BUILD/julia/build/usr/bin/julia -C x86-64 --output-ji /home/milan/Dev/rpmbuild/BUILD/julia/build/usr/lib64/julia/inference0.ji -f coreimg.jl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffecebf700 (LWP 22885)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7999827 in finalize_gc_frame (m=m@entry=0x7127e0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/codegen.cpp:3709
3709	    m->getFunction("julia.gc_root_kill")->eraseFromParent();
Missing separate debuginfos, use: dnf debuginfo-install libgcc-5.3.1-2.fc23.x86_64 libstdc++-5.3.1-2.fc23.x86_64 libunwind-1.1-10.fc23.x86_64 llvm37-libs-3.7.1-2.fc23.x86_64 ncurses-libs-5.9-21.20150214.fc23.x86_64 utf8proc-1.3-1.fc23.x86_64
(gdb) ba
#0  0x00007ffff7999827 in finalize_gc_frame (m=m@entry=0x7127e0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/codegen.cpp:3709
#1  0x00007ffff79a4452 in jl_finalize_module (m=m@entry=0x7127e0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/codegen.cpp:979
#2  0x00007ffff79be5a3 in jl_generate_fptr (li=li@entry=0x7ffdeacddeb0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/codegen.cpp:1084
#3  0x00007ffff794e925 in jl_call_method_internal (nargs=2, 
    args=0x7fffffffc880, meth=0x7ffdeacddeb0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/julia_internal.h:66
#4  jl_apply_generic (args=args@entry=0x7fffffffc880, nargs=nargs@entry=2)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/gf.c:1916
#5  0x00007ffff79643ee in do_call (args=args@entry=0x7ffdeacfabb0, 
    nargs=nargs@entry=2, locals=locals@entry=0x0, nl=nl@entry=0, 
    ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:65
#6  0x00007ffff7963615 in eval (e=0x7ffdeacfe990, locals=locals@entry=0x0, 
    nl=nl@entry=0, ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:185
#7  0x00007ffff79643d4 in do_call (args=args@entry=0x7ffdead014e0, 
    nargs=nargs@entry=4, locals=locals@entry=0x0, nl=nl@entry=0, 
    ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:64
#8  0x00007ffff7963615 in eval (e=0x7ffdeacfe970, locals=locals@entry=0x0, 
---Type <return> to continue, or q <return> to quit---
    nl=nl@entry=0, ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:185
#9  0x00007ffff79643d4 in do_call (args=args@entry=0x7ffdead01480, 
    nargs=nargs@entry=3, locals=locals@entry=0x0, nl=nl@entry=0, 
    ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:64
#10 0x00007ffff7963615 in eval (e=0x7ffdeacfe950, locals=locals@entry=0x0, 
    nl=nl@entry=0, ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:185
#11 0x00007ffff796343d in eval (e=e@entry=0x7ffdeacfe930, 
    locals=locals@entry=0x0, nl=nl@entry=0, ngensym=ngensym@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:268
#12 0x00007ffff7964b7d in eval_body (stmts=stmts@entry=0x7ffdead01390, 
    locals=locals@entry=0x0, nl=nl@entry=0, ngensym=ngensym@entry=0, 
    toplevel=1, start=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:550
#13 0x00007ffff7964ff6 in jl_toplevel_eval_body (stmts=0x7ffdead01390)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/interpreter.c:481
#14 0x00007ffff797aa6d in jl_toplevel_eval_flex (e=<optimized out>, fast=1)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/toplevel.c:530
#15 0x00007ffff797ab35 in jl_toplevel_eval_flex (e=<optimized out>, 
    fast=fast@entry=1)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/toplevel.c:422
---Type <return> to continue, or q <return> to quit---
#16 0x00007ffff79585ad in jl_parse_eval_all (
    fname=fname@entry=0x7ffff7a1e5ad "boot.jl", len=len@entry=8, 
    content=content@entry=0x0, contentlen=contentlen@entry=0)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/ast.c:784
#17 0x00007ffff797b2dd in jl_load (fname=fname@entry=0x7ffff7a1e5ad "boot.jl", 
    len=len@entry=8) at /home/milan/Dev/rpmbuild/BUILD/julia/src/toplevel.c:576
#18 0x00007ffff796a710 in _julia_init (rel=JL_IMAGE_JULIA_HOME)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/init.c:644
#19 0x00007ffff796ac8c in julia_init (rel=<optimized out>)
    at /home/milan/Dev/rpmbuild/BUILD/julia/src/task.c:275
#20 0x0000000000401743 in main (argc=1, argv=0x7fffffffddc8)
    at /home/milan/Dev/rpmbuild/BUILD/julia/ui/repl.c:653
```

**Comment by yuyichao** [comment]
From the backtrace it appears that it is not building my branch.

**Comment by yuyichao** [comment]
(The line that it is segfaulting on is replaced)

**Comment by nalimilan** [comment]
Ah, that was precisely the mistake I wanted to avoid. The actual build of the PR does not crash at the same place, but hits a type assertion error:
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00160033-julia/build.log.gz

**Comment by yuyichao** [comment]
The typeassersion is https://github.com/JuliaLang/julia/pull/14543#issuecomment-183679357 . Hopefully we will fix it before the release but for now the workaround is to increase the stack limit during compilation ....

**Comment by nalimilan** [comment]
OK. Actually, it looks like this affects only some of the builds.

I wonder whether I should keep using MCJIT to ensure it doesn't break as long as we claim it's supported. Or maybe it should be added to TravisCI?

**Comment by yuyichao** [comment]
Probably not travis (we don't need a even longer CI queue), maybe buildbot.

I'm not sure if we'll "support" MCJIT for long though. It doesn't seem to be the way moving forward and it isn't useful as a compiler performance baseline.

**Comment by nalimilan** [comment]
That's fine if the plan is to drop it soon.

**Comment by nalimilan** [comment]
OT, but: is it expected that enabling ORCJIT makes the build so much slower? It takes about 55-65 minutes, as opposed to 30-40 with MCJIT.

**Comment by yuyichao** [comment]
Hmm, I thought it is supposed to be faster..... unless the cpp files takes 20mins to compile...

**Comment by Keno** [comment]
It's only faster if all of our patches are applied.

**Comment by nalimilan** [comment]
The patches are applied AFAICT. You can have a look at the list of patched files here:
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00157239-llvm37/build.log.gz

Note that when I say "build time", I include the time needed to run the test suite.
