### ISSUE TITLE
readdir() not redirecting properly

### ISSUE THREAD

**Issue by morris25** [JuliaLang/julia#15109]
In the following piece of code reads pwd():
```julia
julia> !isempty(readdir(pwd()))
true
```
This code should also read pwd(), but instead it returns an error:
```julia
julia> !isempty(readdir(joinpath(pwd(), "foo", "..")))
ERROR: SystemError: unable to read directory ~/.julia/v0.4/Playground/foo/..: No such file or directory
in readdir at file.jl:241
```
(foo is a non-existent directory)  

This can be solved by using normpath(), however would this be considered a bug since readdir() is navigating to a place it does not have to? Should it not automatically take the ".." into account and redirect itself?

**Comment by vtjnash** [comment]
`pwd()` and `pwd()/foo/..` are not necessarily the same directory on unix (indeed, in this case, as the error indicates, the later does not exist)
