### ISSUE TITLE
Down Arrow no longer goes to the next command in the history

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15116]
To reproduce:
- Go up in history
- Hit enter
- Hit Down arrow

Should go to the next history entry after the one we just recalled. It appears that behavior regressed some time recently. I thought we had added a test for this behavior.

**Comment by yuyichao** [comment]
Seems fine on linux x64 with commit https://github.com/JuliaLang/julia/commit/b04b8cdfbded5ca4872f2a32e78f1f0e6ede4672 which is based on current (or a few hours old) master?

**Comment by vtjnash** [comment]
seems to work for me on 47adbb9 (current head)

**Comment by Keno** [comment]
So it does. Turns out I already fixed this in a604e195f97e17d6003496d69f331821d42215f0, but not on my current branch. I'll blame it on me getting old.
