### ISSUE TITLE
0.4.3: Special functions broken when building in OS X

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#15114]
Any thoughts on what's going on:

```julia
julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> airyai(1.)
ERROR: error compiling airyai: error compiling airy: error compiling _airy: could not load library "libopenspecfun"
dlopen(libopenspecfun.dylib, 1): Library not loaded: /usr/local/Cellar/gfortran/4.8.2/gfortran/lib/libgfortran.3.dylib
  Referenced from: /Users/solver/Projects/julia/usr/lib//libopenspecfun.dylib
  Reason: image not found
```

**Comment by dlfivefifty** [comment]
I built this from 0.4.3 source

**Comment by dlfivefifty** [comment]
My brew gcc is gcc-5.3.0, and the library its looking for is probably in

/usr/local/Cellar/gcc/5.3.0/lib/gcc/5

**Comment by andreasnoack** [comment]
Have you tried
```
make -C deps distclean-openspecfun
make
```?

**Comment by dlfivefifty** [comment]
Thanks!  that fixed it.  I had done 

```
git reset --hard
git clean -x -f -d
```

which I thought cleans the dependencies?

**Comment by vtjnash** [comment]
`git clean` won't recurse into other git directories

**Comment by andreasnoack** [comment]
I think you'll have to use `make` with the `distclean` targets to clean the dependencies. There should be one for most if not all of the dependencies. You can clean all of them with `distcleanall` but then you'll have to rebuild LLVM.

**Comment by dlfivefifty** [comment]
OK thanks.  I might just go back to deleting and git clone-ing again in that case.

**Comment by dlfivefifty** [comment]
I'd suggest rephrasing this guideline on the README as its misleading: "In extreme cases, you may wish to reset the source tree to a pristine state. The following git commands may be helpful"
