### ISSUE TITLE
Missing round methods for RoundNearest

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#15115]
A number of `round` methods which take a RoundingMode do not accept RoundNearest (but do accept the other modes). Evidence:

```
julia> round(0.5, RoundNearest)
ERROR: MethodError: no method matching round(::Type{Float64}, ::Float64, ::RoundingMode{:Nearest})
Closest candidates are:
  round{T}(::Type{T}, ::Rational{T<:Integer}, ::RoundingMode{:Nearest})
  round{T<:Integer}(::Type{T<:Integer}, ::AbstractFloat, ::RoundingMode{T})
  round{T,R}(::Type{T}, ::AbstractArray{R,1}, ::RoundingMode{T})
  ...
 in eval(::Module, ::Any) at ./boot.jl:267

julia> round(0.5, RoundDown)
0.0
```

This appears to be the case on 0.4 and master.

The missing methods are `round{T<:FloatingPoint}(::T, ::RoundingMode{:Nearest})`. There are other methods I found which depend on those, such as `round(::Type{Int64}, ::Float64, ::RoundingMode{:Nearest})`.

It seems to me like either `round(::Number, RoundingMode{:Nearest})` should call `round(::Number)` or the reverse should be true. If the latter option is preferred, there's a bunch of code overhaul to do, and packages probably have to be updated as well.

**Comment by simonbyrne** [comment]
Yes, it should. Unfortunately, LLVM doesn't support it, though hopefully they should in future as `roundeven` is part of the most recent C floating point technical spec: see https://github.com/JuliaLang/julia/issues/8750#issuecomment-65948396 for the full details.

**Comment by iamed2** [comment]
Oh, so it functionally can't be done, and `round` doesn't actually do `RoundNearest`? If that's the case, why do the docs say that the default is `RoundNearest`?

**Comment by iamed2** [comment]
If I understand correctly, it is impossible to have a RoundNearest rounding mode for floats because there's no way to ensure the correct behaviour other than setting the rounding mode?

**Comment by simonbyrne** [comment]
Yes, exactly.

**Comment by kshyatt** [comment]
It seems like this was an issue with the modes LLVM provides, which we can't do much about. I'm going to close this - feel free to reopen if I'm wrong in doing so.

**Comment by iamed2** [comment]
I think it would be nice to have a living issue for it, but this isn't it.
