### ISSUE TITLE
julia-mode.el indentation with function chaining

### ISSUE THREAD

**Issue by tcovert** [JuliaLang/julia#15118]
Currently, there is no defined indentation patterns for function chaining.  For example, consider this code from the documentation for `DataFramesMeta.jl`:

```jl
x_thread = @linq df |>
    transform(y = 10 * :x) |>
    where(:a .> 2) |>
    by(:b, meanX = mean(:x), meanY = mean(:y)) |>
    orderby(:meanX) |>
    select(:meanX, :meanY, var = :b)
```

In emacs, on my machine (Mac OS X Yosemite, emacs 24.5.1, julia-mode.el version 0.3), this renders as:

```jl
x_thread = @linq df |>
transform(y = 10 * :x) |>
where(:a .> 2) |>
by(:b, meanX = mean(:x), meanY = mean(:y)) |>
orderby(:meanX) |>
select(:meanX, :meanY, var = :b)
```

I suppose there may be differences of opinion as to how this should be represented, but I personally like the first layout better than the second layout.

**Comment by yuyichao** [comment]
I agree the first one is better (and this is also an issue about operators in general and not just `|>`).

Please quote your code (see my edit), especially when you are using (julia) macros since you might be pinging unrelated people.

**Comment by justbur** [comment]
@yuyichao could you point me to or provide a list of operators that should be indented this way? I'm new to julia but am interested in contributing.

Here's a function I came up with to calculate the indentation of the example above, which can be called in `julia-indent-line`
```elisp
(defun julia-chaining-operators-indent ()
  "Indent chained operators according to the following rules. If
the previous two lines end in an operator, return the indentation
level of the previous line. If only the previous line ends in an
operator, return the indentation of the previous line incremented
by `julia-indent-offset'. Otherwise, return nil."
  (let ((n-prev-lines 0)
        (regexp ".+\|>$")
        prev-line-indent)
    (save-excursion
      (when (and (= 0 (forward-line -1))
                 (looking-at regexp))
        (setq prev-line-indent (current-indentation))
        (incf n-prev-lines)
        (when (and (= 0 (forward-line -1))
                   (looking-at regexp))
          (incf n-prev-lines))))
    (cl-case n-prev-lines
      (1 (+ prev-line-indent julia-indent-offset))
      (2 prev-line-indent)
      (t nil))))
```

If there's interest I can work on it and make a pr.

**Comment by yuyichao** [comment]
I believe this applies to all the binary and ternary operators. There is a list of it at the beginning of `src/julia-parser.scm`.

**Comment by yuyichao** [comment]
Oh, a PR to fix this is definitely welcome.
