### ISSUE TITLE
Is it bug ? : 'endof()' returns curious values.

### ISSUE THREAD

**Issue by HatsuneMiku** [JuliaLang/julia#15127]
`endof()` returns curious values.

```jl
julia> endof("\u2200\u2200")
4
julia> endof("\u2200\u22007")
7
julia> endof("\u2200")
1
julia> endof("\u22004")
4
```

**Comment by yuyichao** [comment]
This is not a bug since `endof` returns the index you should use to get the last element. I think this is a consequence of how we do unicode indexing and hopefully https://github.com/JuliaLang/julia/pull/14383 could help?

**Comment by HatsuneMiku** [comment]
I understand it.

**Comment by StefanKarpinski** [comment]
If you have questions about things, please direct them to the julia-users list. If it turns out to be a bug, then an issue can be opened.
