### ISSUE TITLE
Schur factorization slow as compared to Octave

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#15131]
On MacOSX, the schur factorization is slower on Julia than on Octave. For a matrix of size 1500 x 1500,

```
octave:5> tic; [U,S] = schur(a); toc;
Elapsed time is 4.69628 seconds.
```
and Julia v0.4.1
```
julia> @time schur(a);
  6.623093 seconds (33 allocations: 34.772 MB, 1.30% gc time)
```
However, if you build Julia with system BLAS, which uses Apple's Accelerate, you get better performance:
```
julia> @time schur(a);
  3.334246 seconds (43 allocations: 34.773 MB, 0.10% gc time)
```

**Comment by ViralBShah** [comment]
Cc @xianyi

**Comment by ViralBShah** [comment]
I don't think this is mac specific in any way - just the easiest way to use a different vendor BLAS to see if this is potentially an openblas issue.

**Comment by tkelman** [comment]
Same guess as in https://github.com/JuliaLang/julia/issues/5728#issuecomment-185518733. If openblas built with icc and ifort is as fast as MKL, we have our answer and can file a bug with gfortran.

**Comment by ViralBShah** [comment]
openblas has very little fortran (except building lapack, I believe).

**Comment by tkelman** [comment]
Schur factorization will go through lapack.

**Comment by ViralBShah** [comment]
Go through lapack, but spend very little time in it. I believe all the FLOPS should be in BLAS.

**Comment by tkelman** [comment]
In theory. What will actually answer the question is running with the intel compilers and getting real data.

**Comment by andreasnoack** [comment]
This is the same as https://github.com/JuliaLang/julia/issues/5728 since Eig = Schur + "funny triangular solve".

**Comment by stevengj** [comment]
Closing as a dup of 5728.
