### ISSUE TITLE
MvLogNorma not defined on Julia 0.4.2

### ISSUE THREAD

**Issue by Chaoukia** [JuliaLang/julia#15143]
The documentation about Julia's distributions says that the package Distributions provides an implementation MvLogNormal for log-normal distributions, but when using it on Julia 0.4.2 it raises an error "MvLogNormal not defined". I Don't know why, can you help me with that?

**Comment by andreasnoack** [comment]
Please direct issues with packages to the relevant package repositories. In this case `Distributions.jl`. 

The `MvNLogNormal` was added very recently so try `Pkg.update()` and then restart Julia.

**Comment by KristofferC** [comment]
I believe that this question is better suited at the repo for  the distribution package. You can find D it here åh
