### ISSUE TITLE
@threads not starting multiple threads

### ISSUE THREAD

**Issue by cbecker** [JuliaLang/julia#15142]
Hello, I am testing the latest master with the `@threads` functionality. I am really glad it is making it into v0.5.

I have code that calls a function repeatedly with different inputs (randomized), and I am observing that Julia is not spawning threads, but instead running everything in a single thread.

My code is a bit complex, but I wanted to know if there are any checks to decide whether code with `@threads for` should not be parallelized, to check what could be happening.
Thanks.

**Comment by andreasnoack** [comment]
Hi Carlos,

It would be better to ask this as a question on julia-users.

Do you have `JULIA_THREADS=1` in your Make.user? What is the output from `Base.Threads.nthreads()`?

**Comment by cbecker** [comment]
Thanks, I will post to the user list next time.
It surprised me that `@threads` was working fine for some cases but not for other. So it doesn't seem to be completely disabled by `JULIA_THREADS != 1`. However, setting it to `1` fixed it, thanks.
