### ISSUE TITLE
nested escaped @everywhere const definition in macro 

### ISSUE THREAD

**Issue by thraen** [JuliaLang/julia#15149]
Hi, 

I try to redefine a global constant everywhere from inside a macro. Julia tells warns me about the redefinition, but doesn't actually redefine it until the macro terminated. When I run this with one worker:
```
macro wtf1()
    return esc(
        :(begin
            @show a
            @everywhere const b     = a
            @show b
        end))
end     
            
macro wtf2()
    return esc(
        :(begin
            @show c
            const d     = c
            @show d 
        end))
end

@everywhere const a = 0
@wtf1
@everywhere const a = 1
@wtf1 

println()

const c = 0
@wtf2
const c = 1
@wtf2
```
I get:
```
a = 0
b = 0
WARNING: redefining constant a
a = 1
WARNING: redefining constant b
b = 0

c = 0
d = 0
WARNING: redefining constant c
c = 1
WARNING: redefining constant d
d = 1
```
Outside of the macro b has changed as I expected it.
Probably I'm missing something about the scopes, but this is at least confusing.

**Comment by vtjnash** [comment]
`const` binding are, by nature, well, *constant*. while reassigning them is allowed for convenience in interactive settings (with a WARNING), the result is undefined.

**Comment by thraen** [comment]
thanks. why do you allow undefined things?

**Comment by thraen** [comment]
for the sake of whatever: I really doubt that the result of the redefinition of a global is undefined. After all the changed value is of the same type. If I can do it interactively and I can do it non interactively by copy and pasting, why shouldn't this be possible from within a macro. This code will never be used again, it was meant for running a script a few times the easiest ugliest and quickest way I could think of. Do I really have to copy and paste?

**Comment by tkelman** [comment]
If the situation we're warning about has really strange unpredictable consequences, we should make that warning more intimidating and say so.
