### ISSUE TITLE
Shared Julia installation across multiple architectures

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#15152]
I have Julia 0.4 installed on the filesystem shared by multiple cluster nodes. All nodes have Xeon CPUs, but of different generations, so on some I've got the message `ERROR: Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}.` when trying to start Julia.

Would it be possible to configure the environment, such that on this machine Julia would use sys.so from the alternative location and also store precompiled packages in an alternative folder, while still looking for the package sources in the default locations?

**Comment by yuyichao** [comment]
Please ask questions on julia-users and also read the [README](https://github.com/JuliaLang/julia#architecture-customization) first.
