### ISSUE TITLE
First line duplicated when pressing any arrow key in REPL

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15166]
If I paste this function in the REPL and hit one of the arrow keys, the first line is duplicated.
```julia
function f(io::IO, s)
    print(io, "StringDecoder from $(F()) to $(T()) wrapping $(s.istream)")
end
```
i.e. I get this:
```julia
julia> function f(io::IO, s)
julia> function f(io::IO, s)
           print(io, "StringDecoder from $(F()) to $(T()) wrapping $(s.istream)")
       end
```

Each additional press gives a new duplicated line.

**Comment by pkofod** [comment]
Not sure if it's directly related, but the "line repetition" seems superficially related to #14671

**Comment by Keno** [comment]
I suspect there's an off by one error in the REPL somewhere when it computes whether or not the string spans multiple lines.

**Comment by vtjnash** [comment]
agreed, it looks like the borked size for the example above is a width of 87
