### ISSUE TITLE
Basic arithmetic over Rational{Bool} doesn't work

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#15161]
```jl
julia> true//true * true//true
ERROR: checked_mul not defined for Bool
 in * at rational.jl:188
```

Similar errors are thrown for the other basic arithmetic operations -, +, /, \, ...

I'm not quite sure how arithmetic for this type ought to work. Note that not all arithmetic over `Bool`s is  closed, e.g. `true + true == 2`

**Comment by TotalVerb** [comment]
Are there any applications for `Rational{Bool}`? The integers mod 2 are a field already, so fractions aren't needed. `Bool` is not quite the integers mod 2 anyway because of addition behaviour.

**Comment by nalimilan** [comment]
I fixed this (without knowing) in https://github.com/JuliaLang/julia/pull/15294. It probably used to work before rationals switched to checked arithmetic recently:
```julia
julia> true//true * true//true
true//true

julia> true//true - true//true
0//1

julia> true//true + true//true
2//1

julia> true//true / true//true
true//true

julia> true//true \ true//true
true//true
```

I have no idea of whether this can be useful, but there isn't any reason not to support this either.

**Comment by tkelman** [comment]
We should probably add tests for these if someone wants them to continue working as they do at the moment.
