### ISSUE TITLE
Inconsistent parsing of `2._x`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15175]
The expression `2._x` is a parse error. However, the related expressions `2.x`, `2x`, and `2_x` all work. I think `2._x` should be parsed as `2. * _x`.

**Comment by JeffBezanson** [comment]
`2.x` is now disallowed.

**Comment by yuyichao** [comment]
Which version fixes it? AFAICT `2._x` still errors.

```
julia> 2._x
ERROR: syntax: invalid numeric constant "2._"
```

This is on c47412b741 but there doesn't seem to be any parser changes after that?

**Comment by yuyichao** [comment]
Oh, nvm. I read it backward.
