### ISSUE TITLE
Wrong example in the "Optional Arguments" section?

### ISSUE THREAD

**Issue by Dawny33** [JuliaLang/julia#15171]
The example for the "optional arguments" docs contain the following example:

```
function parse(type, num, base=10)
    ###
end
```

Isn't `type` a reserved keyword?

The execution of the function is throwing the following error:

```
julia> function parse(type, num, base=10)
ERROR: syntax: unexpected ,
```

Corresponding [discussion link](https://gitter.im/JuliaLang/julia?at=56c963a35c3b0559674da3e0) on Gitter.

**Comment by nalimilan** [comment]
Good catch, please make a PR to fix this. I think the convention is to write `T` for this kind of argument.

**Comment by Dawny33** [comment]
@nalimilan With `T`, the base argument is throwing an error:

```
julia> function(T, num, base=10)
           ###
       end
ERROR: syntax: "base=10" is not a valid function argument name
```

I have checked whether there is a problem with the specific name `base`, but looks like it's not. It has a problem with all argument names:

Example:
```
julia> function(T, num, dawny=10)
           ###
       end
ERROR: syntax: "dawny=10" is not a valid function argument name
```

**Comment by nalimilan** [comment]
That's because you forgot the name of the function. If I add `parse` back, it works.

(This syntax is supported in Julia 0.5 and it creates anonymous functions.)

**Comment by Dawny33** [comment]
@nalimilan   Yeah, my bad :+1: 

However, the `T` doesn't give the desired output. Gives out `nothing`

```
julia> function parse(T, num; base=10)
           ###
       end
parse (generic function with 2 methods)

julia> parse(Int, "12", 10)

julia> parse(Int, "12", 10) == nothing
true
```

**Comment by nalimilan** [comment]
The body of your function does not contain anything, what would you expect it to return?

Also, you need to write `Base.parse` instead of `parse` to extend the corresponding function from Base.

**Comment by Dawny33** [comment]
@nalimilan Yeah, I see that. I was trying to write the function as it was written in the example [here](http://docs.julialang.org/en/release-0.4/manual/functions/#optional-arguments)

So, what can be the correct implementation of the `parse` function for getting the desired output as shown in the docs?

**Comment by nalimilan** [comment]
Just replace `type` with `T`. The example is clearly not supposed to actually parse a number, it's just here to illustrate to use of optional arguments. If you find it's not clear enough, you could also replace `###` with something like `# Body of the function`.

We could also replace all the examples in that page with functions that you can actually copy/paste, but I'm not sure it's worth it.

**Comment by Dawny33** [comment]
@nalimilan Yeah, I have read through the doc for the third time, and looks like `parse` is a library function. It works as intended if executed as shown.

However, it is confusing for first timers as copy-pasting the example function throws an error in the REPL.

**Comment by elextr** [comment]
The example uses probably uses "type" because the documentation for `parse` uses "type" [here](http://docs.julialang.org/en/release-0.4/stdlib/numbers/?highlight=parse#Base.parse).

Note that as @nalimilan says the example is *not* how to parse a number, but how to use keyword arguments, and it uses the example of how the existing system `parse` function uses it.

It says (my emphasis) : "For example, the **library function parse(type,num,base)** interprets a string as a number in some base. The base argument defaults to 10. This behavior can be expressed concisely as:"

The system function is far more complex (eg one of its [methods](https://github.com/JuliaLang/julia/blob/master/base/parse.jl#L5)) and involves concepts that are irrelevant to the discussion at hand so it would be even more confusing to introduce a real declaration of that function.

So while `parse` illustrates the use-case for keyword arguments well, it doesn't lend itself to simple cut and paste examples that do anything.  

I don't think it should be required that all examples in the documentation paste and work since that would inevitably involve the example containing things irrelevant to the discussion (like body code).  But if its is required  a different function from `parse` should be used as the example, but I couldn't think of or find a good one quickly.

**Comment by eschnett** [comment]
The documentation `parse(type, str, [base])` is clearly not meant to be valid Julia code. However, it is somewhat confusing that `parse` can be pasted, while `type` needs to be replaced by a type. Other documentation systems express this by writing e.g.
```
parse(<type>, <str>, [<base>])
```
or by using italics for `type`, `str`, and `base`.

**Comment by Dawny33** [comment]
@eschnett Yes, the `< >` and `[< >]` looks good for explaining the parse function.

Anything which tells aloud, that `this piece of code shouldn't be copy-pasted` should be good.

Would be very important going forward with the docs, as it is meant for newcomers, and the current example in `[Optional Arguments](http://docs.julialang.org/en/release-0.4/manual/functions/#optional-arguments)` is definitely confusing for them.

**Comment by nalimilan** [comment]
Let's just replace `parse` with a simple test function like this:
```julia
function myfun(x, y=1)
    return x, y
end


julia> myfun(1)
(1,1)

julia> myfun(1, 2)
(1,2)
```

The advantage is that everything is visible, and it can easily be adjusted if the reader wants to test how things work. The text can still give examples of actual functions in Base which use this mechanisms (like `parse`).

**Comment by Dawny33** [comment]
@nalimilan Yeah, this looks a nice and simple example for the docs, which is clearer than the `parse` example.  :+1: 

Can you pl raise this in the mailing list? (My query is still under moderation since two days!)

**Comment by nalimilan** [comment]
> @nalimilan Yeah, this looks a nice and simple example for the docs, which is clearer than the parse example. :+1:
> 
> Can you pl raise this in the mailing list? (My query is still under moderation since two days!)
That's unfortunate (it happens only the first time I think), but we can discuss this here as well. The best would be to make a new pull request. I can try to do so if nobody beats me to it.

**Comment by Dawny33** [comment]
@nalimilan   I hope I can beat you to it. :D

But, there is a whole lot to be changed there, and I think you'll be the better one to do so. So, pl go ahead!

**Comment by nalimilan** [comment]
Please, go ahead! I think you can leave the other examples (`plot`, etc.) as they are, since the text does not actually show what calling these functions gives. Also call the function `f` for consistency with examples used below.
