### ISSUE TITLE
Matrix API: Why is it issym, but ishermitian ?

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#15182]
Is there any reason for the function name `issym` instead of `issymmetric` when it is not `isher` but `ishermitian`?

**Comment by KristofferC** [comment]
Matlab also uses `issymmetric`

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/julia/commit/0691bc1f043e9077bb9753b7f3bbe0ce39fde04a, but I couldn't find a discussion. I don't really like abbreviations, so I wouldn't mind `issymmetric`.

**Comment by StefanKarpinski** [comment]
+1 – `issym` has the potential to be confused with "is symbol", which is a silly function to have, but still.

**Comment by pkofod** [comment]
Exactly, how can you know (ignoring context) if `issym` is `issymmetric` or `issymbol`? I'll track down the uses of `issym`, make a PR with `issymmetric` and deprecate `issym`. Then we can see which one people prefer.
