### ISSUE TITLE
Call overloading example doesn't say how to specify type parameters

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15189]
The section "Function-like objects" of the documentation contains this example that explains how to make objects of a certain type (here `Polynomial`) callable:

``` Julia
immutable Polynomial{R}
    coeffs::Vector{R}
end

function (p::Polynomial)(x)
    v = p.coeffs[end]
    for i = (length(p.coeffs)-1):-1:1
        v = v*x + p.coeffs[i]
    end
    return v
end
```

This example doesn't say how one can specify a type parameter (here `R`). The type parameters go between the two sets parentheses, i.e. after it has already been used, as in

``` Julia
function (p::Polynomial{R}){R}(x)
```

The example should be updated to describe this case as well.

Note: This syntax is cute, but is far from being obvious to write or easy to understand. This is Julia, not Perl. Can we un-deprecate the much more obvious syntax `call{R}(p::Polynomial{R}, x)`?

**Comment by mbauman** [comment]
This is now unified with `where` clauses.
