### ISSUE TITLE
Over specialization on function argument

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15190]
Ref https://github.com/JuliaLang/julia/pull/15177#issuecomment-186896376
On my laptop, the following code takes `< 0.02s` on 0.4 and `> 40s` on master.

```jl
function f(m)
    for i in names(m)
        v = m.(i)
        isa(v, Function) && string(v)
    end
end
@time f(Base)
```

According to [the profiling result](https://gist.github.com/yuyichao/1007925f08cc0b16944b), it spends most of the time in inferencing and compiling `string` (or `print_to_string`) even though the result of the compilation isn't any useful since rerunning `f(Base)` takes roughly the same time on 0.4....

As Stefan [pointed out](https://github.com/JuliaLang/julia/pull/15177#issuecomment-187259584), the heuristic of not specializing on what we don't call should solve this issue but somehow it is not triggerred in this case.

@jrevels for performance benchmark. In additional to the reduced case above, the first half of `genstdlib.jl` script before #15177 should be a good candidate too.

c.c. @JeffBezanson

**Comment by carnaval** [comment]
@JeffBezanson the problem here is MAX_UNSPECIALIZED_CONFLICTS, so even though the logic for "this argument is or is not being called in this function" is correct, it gives up on unspecializing the cache entry

**Comment by JeffBezanson** [comment]
Ok, let's bump it to 20.

My job is so easy :)
