### ISSUE TITLE
Date, typemax() and string formatting

### ISSUE THREAD

**Issue by mturok** [JuliaLang/julia#15195]
The Dates.format string formatting function truncates dates that have years > 9999 by simply just displaying the specific number of characters requested.

```
julia> dt = typemax(Date)
252522163911149-12-31

julia> Dates.format(dt, "yyyy-mm-dd")
"1149-12-31"
```
Note that the month/day operator do the right thing when you ask for a single character, and the value of the month/day exceeds one single character.

```
julia> Dates.format(dt, "yyyy-m-d")
"1149-12-31"
```

**Comment by nalimilan** [comment]
Cc: @quinnj

**Comment by omus** [comment]
I believe this behavior is to support formatting short forms of year:

```julia
julia> Dates.format(Date(1999,12,8), "yy-m-d")
"99-12-8"
```

**Comment by StefanKarpinski** [comment]
Would it make sense to have a different format specifier for the other meaning? Maybe "Y" for truncated year and "y" for expanding?

**Comment by omus** [comment]
Possibly. I'll take a look into solutions for this issue today.

**Comment by omus** [comment]
@StefanKarpinski your proposed solution does work but I would use "y" for truncated year and "Y" for full year. This behavior is more consistent with how [Python formats dates](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior).

The new behaviour would look like this:
```julia
julia> Dates.format(Date(1999), "yy")
"99"

julia> Dates.format(Date(9), "yy")
"09"

julia> Dates.format(typemax(Date), "yy")
"49"

julia> Dates.format(Date(1999), "YY")
"1999"

julia> Dates.format(Date(9), "YY")
"09"

julia> Dates.format(typemax(Date), "YY")
"252522163911149"
```
I'll keep looking into other solutions.

**Comment by quinnj** [comment]
+1 to this ^ @omus. It would also be non-breaking; I would still use `y` for specifying exact # of digits, while `Y` would expand to fit.

**Comment by omus** [comment]
I'll make a PR for this
