### ISSUE TITLE
What determines when coverage.io and coveralls is updated?

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#15191]
Looking at #11885 and at the `README.md` badges I was wondering what fires the coverage-services? Both are 1-2 months old as far as I can see, so I expect the numbers to be a bit out-dated due to all the commits since then.

So, out of curiosity: when / how / why is it updated? Tried to search but couldn't find the answer.

**Comment by eschnett** [comment]
It's updated automatically when you push to the Github repository. It's just currently broken; see e.g. <https://github.com/JuliaCI/Coverage.jl/issues/101> or <https://github.com/JuliaWeb/MbedTLS.jl/pull/19>.

**Comment by pkofod** [comment]
Just what I needed to find - just didn't know where to look (JuliaCI). Thanks

**Comment by eschnett** [comment]
Does anybody know of an open (not-closed) issue tracking this?

**Comment by pkofod** [comment]
I didn't see they were closed! Reopening.

**Comment by eschnett** [comment]
I just see that Coverage submission is working again. If something is outdated, then pushing any change to the respective repository should push results. Of course, this assumes that the Travis script contains the necessary magic.

**Comment by tkelman** [comment]
Coverage runs for base don't get run on Travis, they run on the buildbot. However, like nightlies, they only trigger when all the test-running buildbots pass. The OSX buildbot has not had a passing build since Feb 1st, it has been timing out due to the LLVM 3.7 upgrade, #13412, etc. https://build.julialang.org/builders/build_osx10.9-x64?numbuilds=250

@ViralBShah do we have any ETA on getting better Mac hardware for that buildbot? Right now it's running on a VM of @staticfloat's, having more memory should help move things along.

**Comment by pkofod** [comment]
Hm, you say "has not had a passing build since Feb 1st" and I can see that from your link, but codecov has not been updated for "2 months" https://codecov.io/github/JuliaLang/julia/commits and coveralls.io has not been updated since 03 jan 2016 https://coveralls.io/github/JuliaLang/julia . Maybe I misunderstood you.

**Comment by tkelman** [comment]
This is just the latest in a series of buildbot problems, or broken webstack on master, etc. The previous issues have now been fixed, the osx issue is what's holding it up right this second.

**Comment by pkofod** [comment]
Thank you for explaining. I was just curious about the current code coverage numbers. Makes contributing to the "lets get code cov to XX%" issues a bit easier.

**Comment by tkelman** [comment]
I think you can run CoverageBase locally but I haven't done it myself. Someone else may have to chime in with advice while we get the buildbots fixed back up.

**Comment by kshyatt** [comment]
I have run CoverageBase locally on OSX and got a `replutil.jl` test failure. If you want to know more, hit me up.

**Comment by tkelman** [comment]
ref #14985 #14986, that test is relatively new and probably needs adjusting to work under the coverage flags

**Comment by StefanKarpinski** [comment]
@kshyatt: is that the threadcall error you mentioned? If so, please yell at me until I fix it :grin:.

**Comment by tkelman** [comment]
replutil, not threadcall. when inlining is off the results are different https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/56/steps/Run%20non-inlined%20tests/logs/stdio

**Comment by vtjnash** [comment]
something between 9cda4ab0292c45ed510a6335f8809d10f15f64b8 and c6c6842604d9f91983f16c7f31b51b563f108bba fixed the osx buildbot. the replutil no-inline error should be fixed by 8a54ed505b1da52abc1707390089db46ad207157 now.

the current issue (https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/66/steps/Test%20CoverageBase.jl/logs/stdio) now seems to be in Requests.jl (https://github.com/JuliaWeb/Requests.jl/pull/105)

**Comment by tkelman** [comment]
I think it was a change on the buildbot itself rather than a change in Julia, but we've been limping along the past few days successfully making binaries again. It's still quite slow, but we have the order in for a new mac mini to run it on.

**Comment by pkofod** [comment]
Sorry if the bump is annoying, but coverage numbers are still off. Is it something that is targeted to be fixed before the v0.5 release ? I know the coverage-tools don't explicitly add functionality, but it does seem quite important to know the extent to which the code is covered by tests. I know some people might be running these numbers locally or on their own repos, but it's not obvious how to find this information.

I tried to find the active issues regarding the failure to produce the correct numbers, but all issues or PRs I could find are either closed or merged, so it's not clear why it is failing currently.

Even if it might not be top priority, as key contributors might have an eye on the numbers on their own coveralls profiles, it might have an impact in the longer term with regards to attracting new contributors. At least the posts on contributing to Julia by Leah Hanson and Katherine Hyatt was what gave me the "courage" to even submit a PR to Julia in the first place. If I were to follow the guide in #11885 I would probably be quite confused :)

**Comment by tkelman** [comment]
Bump is certainly called-for. There are a handful of issues for specific test failures when tests are run with `--inline=no` as they are for coverage runs, but I'm having trouble finding them at the moment. The current failure (see https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/401/steps/Run%20non-inlined%20tests/logs/stdio for latest and https://build.julialang.org/builders/coverage_ubuntu14.04-x64?numbuilds=250 for older logs) looks like a timeout during bitarray. There was a change on master that made that test much slower when run with inlining disabled.

**Comment by timholy** [comment]
I assume we have control of the buildbots? Why not just increase the duration for the timeout?

**Comment by staticfloat** [comment]
We could, but this is getting a little excessive.  The timeout is set to trigger if there is no output from the process for an hour.  That means that the `bitarray` coverage test by itself is taking over an hour.

I've bumped up the timeout to two hours, we'll see if it makes it through now.

**Comment by timholy** [comment]
Ah. That does seem long. [test_showline](https://github.com/timholy/DebuggingUtilities.jl#test_showline) suggests that [this loop](https://github.com/JuliaLang/julia/blob/861100c15b050885297430e7afc24c7a638de982/test/bitarray.jl#L498-L525) is much (or perhaps all) of the culprit. If I'm reading it correctly, the inner loop runs `v1^2/6` times, on inputs that are of length `v1`, so it's of order `v1^3` operations. A natural way to speed it up would be to decrease `v1` from its current value of 260. Feasible, @carlobaldassi? I recognize that 64 is an important number when it comes to BitArrays, so maybe this won't work. What about iterating `m1` and `m2` more sparsely?

**Comment by vtjnash** [comment]
there's currently a MethodError occurring when it tries to upload the results: https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/403/steps/Gather%20test%20results%20and%20Submit/logs/stdio

**Comment by vtjnash** [comment]
Since https://github.com/JuliaLang/julia/pull/16692, we consider all call-site devirtualization optimizations to be a subset of inlining. I suspect that may be too expensive for the bitarray test (or any other test that tests compiled optimizations) to finish in any amount of time. But, while this provided a curious (and completely unawares workaround for #265), this is probably much too aggressive.
