### ISSUE TITLE
Testing coverage and IO methods

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#15205]
In #15105 I tried to increase the coverage in `rational.jl`. It seems to have helped (https://codecov.io/github/kshyatt/julia/base/rational.jl?ref=aa08b2aec7e72d2e3308cf7326a348e705cd3510), but it left me wondering: how do you test `show` and `read`?

(I also see that I missed ^ and some rounding modes, they'll get in when I figure out how to test the methods mentioned above).

Edit: scratch `show`, I guess that can be done using
`@test sprint(io -> show(io,Rational(3,4))) == "3//4"`

**Comment by KristofferC** [comment]
Couldn't you `show` to an `IOBuffer` and then read back the contents and see that it is what you expect.

**Comment by diegozea** [comment]
[This](https://github.com/diegozea/MIToS.jl/blob/master/test/multiplesequencealignment.jl#L462) is an example of printing into an `IOBuffer`. 
Maybe this should be documented or added as a `@testio` macro...

**Comment by pkofod** [comment]
Thanks to both of you! Exactly what I was looking for.
