### ISSUE TITLE
Detect aliasing in non-scalar indexed assignments

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#15209]
Right now we only check for aliasing in the most simple of array assignments (and only for exact object equality: `A===I`).  But with views becoming more prevalent, we'll need to add more aliasing checks to prevent corruption and unexpected behavior.

It'll be tricky to do in a type-stable manner since `copy(A)::typeof(A)` isn't true for views.

``` jl
julia> A = [2 1]
       A[A] = -4
       A
0×2 Array{Int64,2}

julia> B = [1, 2]
       B[[2, 1]] = view(B, :)
       B
2-element Array{Int64,1}:
 1
 1

julia> C = [2 1]
       C[C] = -2^30

signal (11): Segmentation fault: 11
```

**Comment by vtjnash** [comment]
maybe we should have a function that is defined to return the base array pointer, for checking for aliasing? or some more explicit / less conservative overlap computation such as a base + length conservative estimate?

**Comment by mbauman** [comment]
It's a little tricky with non-strided arrays, but I think a coarse `data_id` (a la `object_id`) could work:

```jl
data_id(A::StridedArray) = A === parent(A) ? UInt(pointer(A)) : data_id(parent(A))
data_id(A::AbstractArray) = A === parent(A) ? object_id(A) : data_id(parent(A))
```

For reference, Numpy does much more exact checking, and has some very nice documentation and algorithms for detecting strided array overlaps: https://github.com/numpy/numpy/blob/65aa24aa9e3c5da0a6ec1c2fc3d335d506a511df/numpy/core/src/private/mem_overlap.c.  Our case is *significantly* easier, though, since we can punt on arrays that were constructed with `pointer_to_array` with interior pointers — if they don't track their parent arrays they're in dangerous GC territory.
