### ISSUE TITLE
reinterpret(Float64, (1.0,2.0,3.0)) crashes Julia 0.4.2 on Ubuntu

### ISSUE THREAD

**Issue by JuhaHeiskala** [JuliaLang/julia#15214]
Could not find this in the issues.
Tested with Julia 0.4.2 on Ubuntu 14.04LTS.

julia> reinterpret(Float64,(1.0, 2.0, 3.0))
LLVM ERROR: Cannot select: 0x2c2d030: f64 = truncate 0x27830f0 [ORD=11511] [ID=4] dbg:essentials.jl:115:1
  0x27830f0: i64 = FrameIndex<0> [ORD=11511] [ID=1]
In function: julia_reinterpret_21205

julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by pkofod** [comment]
It shouldn't crash, but note that `A` in `reinterpret(T, A)` should be an array, not a tuple.

**Comment by tkelman** [comment]
This was likely fixed by the llvm upgrade which is too big to backport.

**Comment by JuhaHeiskala** [comment]
Ok, I didn't expect it to work, but give an error.

**Comment by vtjnash** [comment]
fixed by jn/codegen_rewrite + jn/runtime_intrinsics
