### ISSUE TITLE
AVX2 disabled for ORCJIT?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15217]
I see this code in `codegen.cpp`, lines 5797ff:
```
#ifndef USE_MCJIT
    // Temporarily disable Haswell BMI2 features due to LLVM bug.
  HostFeatures["bmi2"] = false;
  HostFeatures["avx2"] = false;
#endif
```
It seems this should be keyed on the the LLVM version, or there should be a comment for which LLVM version this bug was observed, and how the bug (or its absence) can be verified.

**Comment by yuyichao** [comment]
I believe currently `USE_ORCJIT` implies `USE_MCJIT`.

**Comment by vtjnash** [comment]
it was a bug in the old JIT, not a llvm version (also, yichao is correct, although over time, we should try to be explicit)
