### ISSUE TITLE
Identity matrix error

### ISSUE THREAD

**Issue by nickmalhotra** [JuliaLang/julia#15213]
eye(5) gives me a 5x5 identity matrix and creates a float64 array but eye(5.0) gives an error. Ideally this should not be an issue

![julia-eye-error]
(https://cloud.githubusercontent.com/assets/1036757/13283433/cc589ea2-db13-11e5-8149-175a803aed9e.png)

**Comment by KristofferC** [comment]
Why should `eye` work with non integers? You don't have a 5.0 x 5.0 matrix but a 5 x 5 matrix.

**Comment by nalimilan** [comment]
I think the policy is to support only integer types for operations which are only meaningful for ints, i.e. require you to call `Int(1.0)`. For example, indexing an array with floats is currently deprecated too.

**Comment by pkofod** [comment]
Could you perhaps give an example of when this would this be useful? I figure you found out in an application of sorts.

**Comment by nickmalhotra** [comment]
My challenge is not why but semantic consistency of the language
a)  if I write i = [1:5.0]  , the starting index is an integer but the ending index is a float, the resultant 5 element array is automatically typed to a float 64 
b) If I can state eye(5) and it converts it to a float, why not semantically take a float also and do the same thing. 
d) Practically I might be pulling up a float data and might need a ones or an eye matrix to multiply to . Now semantically keeping the flow of program consistent , I might make a matrix with a floating point number as well and readability improves

Hope that points out to why I have noted it down . It is not be an error but a semantic error nonetheless for people jumping on to Julia from other languages

**Comment by mbauman** [comment]
> If I can state eye(5) and it converts it to a float

It's not converting the `5` to a float.  It is creating a `5x5` matrix of floating point numbers.  You can ask for an integer identity matrix with `eye(Int, 5)`.

This is somewhat similar to the `fill` function:  `fill(1, 5, 5)` creates a `5x5` matrix filled with the integer `1`, whereas `fill(1.0, 5, 5)` contains floating point numbers.  Neither allow specifying their dimensions with a floating point number.

**Comment by pkofod** [comment]
Regarding a) and b) I think it's a quite deliberate design choice that if you mean "integer five number of rows and columns" you use "5", not "5.", as "floating point representation 5. number of rows and columns" doesn't really make sense if you think about it.

I'll just quickly give you a tip regarding d). I know this is not exactly the problem you're talking about, but maybe just use the `UniformScaling` `I`?
```julia
julia> A = rand(2,2)
2x2 Array{Float64,2}:
 0.972724  0.583711
 0.686784  0.364074

julia> I-A
2x2 Array{Float64,2}:
  0.0272757  -0.583711
 -0.686784    0.635926

julia> B = rand(3,3)
3x3 Array{Float64,2}:
 0.18451   0.424043  0.762329
 0.510615  0.897821  0.442729
 0.684719  0.245918  0.295252

julia> I-B
3x3 Array{Float64,2}:
  0.81549   -0.424043  -0.762329
 -0.510615   0.102179  -0.442729
 -0.684719  -0.245918   0.704748
```

**Comment by StefanKarpinski** [comment]
Here's the reasoning for not to allowing indexing with floats. When someone writes code that indexes with floats, it tends to indicate that they’re using the result of a computation that could also have given a non-integer value and used it as an index, e.g. `v[end/2]`. Allowing indexing with floats that happen to have integer values, would hide this problem and allow it to surface “in production” when the length of `v` in this example happens to be odd. By only allowing indexing with integer types, we force the choice of how to convert to integer up front, e.g. by writing `v[end÷2]` instead. It's occasionally slightly annoying, but it only in situations where your code was just waiting to break anyway.
