### ISSUE TITLE
Consistency of size checks in banded matrix constructions

### ISSUE THREAD

**Issue by gajomi** [JuliaLang/julia#15221]
There are two related issues for some of the banded matrix types. 

The first has to do with error checking of relative sizes of diagonal and off-diagonal bands in `SymTridiagonal` types. The following shows this in action:

``` julia
julia> A = SymTridiagonal([1,2,3],[4,5])
3x3 SymTridiagonal{Int64}:
 1  4  ⋅
 4  2  5
 ⋅  5  3
julia> A = SymTridiagonal([1,2,3],[4,5,6])
3x3 SymTridiagonal{Int64}:
 1  4  ⋅
 4  2  5
 ⋅  5  3
julia> A = SymTridiagonal([1,2,3],[4,5,6,7])
ERROR: DimensionMismatch("subdiagonal has wrong length. Has length 4, but should be either 2 or 3.")
 [inlined code] from ./strings/io.jl:73
 in SymTridiagonal{Int64}(::Array{Int64,1}, ::Array{Int64,1}) at ./linalg/tridiag.jl:13
 in SymTridiagonal{T}(::Array{Int64,1}, ::Array{Int64,1}) at ./linalg/tridiag.jl:19
 in eval(::Module, ::Any) at ./boot.jl:267
```

The first case makes sense. The second case seems allow the off-diagonal band to be one element larger than it should be. The third case correctly complains about the size, but makes the weird suggestion that the second case is OK behavior (or am I missing something?). Allowing diagonal/off-diagonal pairs of equal length could impact the correctness of user code that assumes otherwise (e.g. calling `A.ev[end]` to get the last off-diagonal element). 

The second issue is about consistency of allowed behavior across banded matrix types. The following illustrates that most banded types allow for the smallest possible bands, including possibly those of length zero when compatible with the overall shape:

``` julia
julia> Diagonal(Int[])
0x0 Diagonal{Int64}
julia> Bidiagonal([1,],Int[],true)
1x1 Bidiagonal{Int64}:
 1
julia> A = SymTridiagonal([1,],Int[])
1x1 SymTridiagonal{Int64}:
 1
```

The exception is `Tridiagonal`

``` julia
julia> A = Tridiagonal(Int[],[1],Int[])
ERROR: invalid Array dimensions
 [inlined code] from ./boot.jl:331
 in Tridiagonal{T}(::Array{Int64,1}, ::Array{Int64,1}, ::Array{Int64,1}) at ./linalg/tridiag.jl:345
 in eval(::Module, ::Any) at ./boot.jl:267
```

which has tighter restrictions than its cousin `SymTridiagonal`. It might be nice if the error checking on this type was relaxed to match the permissive behavior of the other banded matrices.

**Comment by andreasnoack** [comment]
Part of this is on purpose and part of this is not. The original reason for allowing the off-diagonal to have the same length as the diagonal in `SymTridiagonal` was that [this LAPACK solver](http://www.netlib.org/lapack/explore-html/d0/d3b/dstegr_8f.html) requires it in contrast to all the other symmetric tridiagonal eigensolvers in LAPACK.

On top of this, having equal length vectors is also necessary if we want to allow zero size Bi/Tridiagonal matrices.

The last example you show is probably too restrictive and should simply be changed. A PR would be great.

**Comment by jiahao** [comment]
`SymTridiagonal` allows an off-diagonal that is as long as the diagonal for two reasons. One is that you could not otherwise define a 0x0 symmetric tridiagonal matrix. The second is that a great many numerical algorithms working on symmetric tridiagonal matrices also calculate a number which would correspond to the off-diagonal element of the next column, were the calculation to be continued onto an extra row and column. This number also usually has the interpretation of the norm of some residual in the calculation and so is useful information to return.

**Comment by gajomi** [comment]
>  having equal length vectors is also necessary if we want to allow zero size Bi/Tridiagonal matrices.

<br />  

>  One is that you could not otherwise define a 0x0 symmetric tridiagonal matrix

Got it. It looks like it is currently possible to create 0x0 matrices for `Diagonal` and `SymTridiagonal` types, as well as `Symmetric`, `Hermitian` and the various `AbstractTriangular` types. `Bidiagonal`, `Tridiagonal` types currently throw errors, which i'm guessing one should think of as excessively strict.

With respect to the flexible behavior of `Bidiagonal` occurring outside the 0x0 case, for the purposes of wielding LAPACK's `stegr` and friends, sounds interesting and sensible. However, it looks like Julia's `stegr!` methods are doing some size checking that prevents equal length arguments (it appends a zero to the off diagonal before the `ccall`).
```julia
julia> A = SymTridiagonal(Float64[1,2,3],Float64[4,5])
3x3 SymTridiagonal{Float64}:
 1.0  4.0   ⋅ 
 4.0  2.0  5.0
  ⋅   5.0  3.0
julia> eigfact!(A)
Base.LinAlg.Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}([-4.37082,1.78548,8.58534],3x3 Array{Float64,2}:
 -0.524686   0.768751  0.365687
  0.704499   0.150959  0.693464
 -0.477897  -0.621477  0.62079 )
julia> A = SymTridiagonal(Float64[1,2,3],Float64[4,5,6])
3x3 SymTridiagonal{Float64}:
 1.0  4.0   ⋅ 
 4.0  2.0  5.0
  ⋅   5.0  3.0
julia> eigfact!(A)
ERROR: DimensionMismatch("ev has length 3 but needs one less than dv's length, 3)")
 [inlined code] from ./strings/io.jl:73
 in stegr!(::Char, ::Char, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Float64, ::Int64, ::Int64) at ./linalg/lapack.jl:3670
 in eigfact!(::SymTridiagonal{Float64}) at ./linalg/tridiag.jl:125
 in eval(::Module, ::Any) at ./boot.jl:267
```

My grep fu might be failing me, but I didn't find any place in base Julia where the LAPACK routine was called other than the `stegr!` wrapper. If this is correct I would suggest that we do checks on the relative size of diagonal/off-diagonal pairs of the sort that the `stegr!` wrapper expects. Advanced users who are interested in the extra information @jiahao describes can call LAPACK's `stegr` directly (presumably they must already being doing to get at this considering the behavior of Julia's `stegr!`).

**Comment by andreasnoack** [comment]
Thanks for looking into this. I think we should change the LAPACK wrapper such the it doesn't append the zero but just checks that the lengths are equal. That would be more in line with how the other wrappers work. Then we should *resize*, not concatenate, the vector in the `eigvals!` and `eigfact!` methods if necessary.

**Comment by gajomi** [comment]
> Then we should resize, not concatenate, the vector in the eigvals! and eigfact! methods if necessary.

Cool. 

I am quite keen to cook up a pull request to fix up all these things but I may need a bit more guidance before doing so (it's probably been a decade since I looked at a LAPACK function signature). There are two points I would like clarified

(1)
It looks like `stein!` suffers from the same issue:
```julia
julia> A = SymTridiagonal(Float64[1,2,3],Float64[4,5,6])
3x3 SymTridiagonal{Float64}:
 1.0  4.0   ⋅ 
 4.0  2.0  5.0
  ⋅   5.0  3.0

julia> eigvecs(A,[-4.37082,1.78548])
ERROR: DimensionMismatch("ev_in has length 3 but needs one less than dv's length, 3)")
 [inlined code] from ./strings/io.jl:73
 in stein!(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Int64,1}) at ./linalg/lapack.jl:3710
 [inlined code] from ./boot.jl:331
 in eigvecs(::SymTridiagonal{Float64}, ::Array{Float64,1}) at ./linalg/tridiag.jl:171
 in eval(::Module, ::Any) at ./boot.jl:267
```
which it also works around by appending a zero. 

There are, of course, more LAPACK functions :). The `stev` routine is called in `eigvals!{T<:BlasReal}(A::SymTridiagonal{T})`, and expects that the off diagonal array is one element shorter than the diagonal array
```julia
julia> A = SymTridiagonal(Float64[1,2,3],Float64[4,5,6])
3x3 SymTridiagonal{Float64}:
 1.0  4.0   ⋅ 
 4.0  2.0  5.0
  ⋅   5.0  3.0
julia> eigvals!(A)
ERROR: DimensionMismatch("ev has length 3 but needs one less than dv's length, 3)")
 [inlined code] from ./strings/io.jl:73
 in stev!(::Char, ::Array{Float64,1}, ::Array{Float64,1}) at ./linalg/lapack.jl:3621
 in eigvals!(::SymTridiagonal{Float64}) at ./linalg/tridiag.jl:145
 in eval(::Module, ::Any) at ./boot.jl:267
```
Based on what @andreasnoack has written, I would guess that it would be best to add some logic to either `eigvals!` or `stev!` to handle this. 

(2)
It seems that the `stebz!` isn't used anywhere in base Julia. That isn't to say that I am prejudiced against it, but I would like to know if it should also conditionally `resize!` the off diagonal as needed.

**Comment by andreasnoack** [comment]
1. I think it is fine that the LAPACK wrappers check the lengths provided that they also accept `StridedVector` and not only `Vector`. Most of our LAPACK wrappers accept `StridedMatOrVec`, but it appears that the signatures for the symmetric tridiagonal eigensolvers are too strict. Fixing this would good to include in a PR. Then `eigvals!/eigfact!` can just pass a `SubArray` of the right length to the wrapper.
By the way, the reason we use both `stev!` and `stegr!` is that the former is faster and more precise when all values are requested whereas the latter allows the calculation of only part of the spectrum.

2. Again, I think these checks and resizings should be made before we reach the wrappers.

**Comment by gajomi** [comment]
Sounds good to me.

> Again, I think these checks and resizings should be made before we reach the wrappers.

It would makes sense to me to do this in the inner constructors for `Tridiagonal` and `SymTridiagonal`. That way there is a guaranteed length at construction time. 

I am imagining a PR with three logical parts
1.  Liberalize matrix size restriction for `Tridiagonal` and `Bidiagonal`
2.  Add conditional `resize!` of offdiagonal to `Tridiagonal` and `SymTridiagonal` with some comments for devs to know what's going on
3.  Modify array length checks and removing append behavior from `stegr!` and `stein!`

**Comment by andreasnoack** [comment]
That is a good plan. Please go ahead and prepare a PR.

**Comment by andreasnoack** [comment]
@gajomi ping
