### ISSUE TITLE
Ubuntu 14.04 compilation issue

### ISSUE THREAD

**Issue by goelakash** [JuliaLang/julia#15235]
Building Julia from source gives this error-

> Linking C shared library libgit2.so
> /usr/bin/ld: /usr/local/lib/libssl.a(s23_meth.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libssl.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> make[4]: *** [libgit2.so.0.23.4] Error 1
> make[3]: *** [CMakeFiles/git2.dir/all] Error 2
> make[2]: *** [all] Error 2
> make[1]: *** [build/libgit2/libgit2.so] Error 2
> make: *** [julia-deps] Error 2

Do I have to recompile libssl?

**Comment by yuyichao** [comment]
IIUC your libssl.a is not compiled to be used in a shared library so you should recompile/reinstall it (depends on how did you install it in the first place..)

**Comment by goelakash** [comment]
It installed `libssl-dev` from the official repos.

**Comment by yuyichao** [comment]
Are you sure that's the only version you have? I don't think the libssl or libssl-dev package installs to `/usr/local` on ubuntu

**Comment by goelakash** [comment]
You are right. I had replaced the `openssl` version with a build from source. But after recompiling it with the `-fPIC` flag, I get a similar error, but this time for `libcrpto`.

> /usr/bin/ld: /usr/local/lib/libcrypto.a(poly1305-x86_64.o): relocation R_X86_64_PC32 against symbol `poly1305_blocks' can not be used when making a shared object; recompile with -fPIC

But I added -fPIC to both, openssl and crypto libs in the source before compilation. Any ideas?

**Comment by goelakash** [comment]
I downgraded `openssl` to a lower version and tried it again. Still no luck.

**Comment by pao** [comment]
I believe you need to use something like `./Configure shared`, per https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_.26_Config

**Comment by goelakash** [comment]
I did that, and got same errors. My Arch distro is probably laughing, since it compiled without a hitch in that.

**Comment by goelakash** [comment]
I reinstalled `openssl` dev version with some additional tweaks. [Thread](https://github.com/openssl/openssl/issues/744). 
That solved it.
