### ISSUE TITLE
cd() is not @async safe

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#15232]
I'm running into situations where some external tool I need to `run()` has to be run from a certain directory. As it stands, `cd()` can't safely be used in a program that uses `@async`. As a workaround I'm doing something like this:
```julia
@async run(`bash -c "cd $dir
                     external_tool"`)
```

Would it be sensible to have a seperate working directory for each task?

**Comment by yuyichao** [comment]
> Would it be sensible to have a seperate working directory for each task?

No.


[Set the working directory of the command instead](http://julia.readthedocs.org/en/latest/stdlib/base/?highlight=setenv#Base.setenv)

**Comment by samoconnor** [comment]
Thanks @yuyichao
I'm now doing this...
```julia
run(Cmd(`external_tool`, dir=dir))
``` 
This seems to work with 0.4 but is not documented in the 0.4 manual (it is documented in the [0.5 manual](http://docs.julialang.org/en/latest/stdlib/base/#Base.detach)).

**Comment by yuyichao** [comment]
`setenv` is documented on 0.4. If the `Cmd` constructor works on 0.4 and is not documented, the doc could probably be backported.

**Comment by vtjnash** [comment]
while yuyichao is correct about the solution in this instance, i'm waiting rather eagerly for `openat` (http://linux.die.net/man/2/openat) to be sufficiently widely available that a general solution can be depended on.
