### ISSUE TITLE
Better syntax for parametric function definitions

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#15233]
Consider the following definition of the functon
``` Julia
function foo{F<:Real,I<:Real}(x::Vector{F}, m::Matrix{I})
    println(typeof(x))
    println(typeof(m))
end
```

It would be nice to be able to define the function above the following way:

``` julia
function foo{F,I<:Real}(x::Vector{F}, m::Matrix{I})
    println(typeof(x))
    println(typeof(m))
end
```

I.e. to be able to group parametric types if they belong to the same abstract type

**Comment by yuyichao** [comment]
I think it's a bad idea to introduce more white space sensitivity.

**Comment by AzamatB** [comment]
Can you elaborate on what do you mean by white space sensitivity?

**Comment by yuyichao** [comment]
There's no difference between `foo{F,I  <: Real}(x::Vector{F}, m::Matrix{I})` and `foo{F,I<:Real}(x::Vector{F}, m::Matrix{I})` both of which are currently valid and widely used syntax which mean `foo{F<:Any,I<:Real}(x::Vector{F}, m::Matrix{I})`

**Comment by AzamatB** [comment]
Let me to clarify, my in proposition

``` Julia
function foo{F,I<:Real}(x::Vector{F}, m::Matrix{I})
end
```
would be equivalent of:
``` Julia
function foo{F<:Real,I<:Real}(x::Vector{F}, m::Matrix{I})
end
```

User would still be able to use
``` Julia
function foo{I<:Real,F}(x::Vector{F}, m::Matrix{I})
end
```

to mean

``` Julia
function foo{I<:Real,F<:Any}(x::Vector{F}, m::Matrix{I})
end
```

**Comment by yuyichao** [comment]
This should be very confusing since it will be parsed differently compare to normal expressions `Meta.show_sexpr(:(F,I<:Real))`. `(I,F)<:Real` is acceptable but this is only useful for a extremely limited case (two or more type parameters of exactly the same type constraint) and it's not a good reason for breaking lots of currently valid code.

**Comment by AzamatB** [comment]
This actually happens to me all the time. Most common case is when I want to define function with multiple input arguments all of which are subtypes of `Real`, but not necessarily of the same concrete type. Because of current syntax, many of my function definitions in such cases end up spanning 2-3 lines, which is hard to read

**Comment by yuyichao** [comment]
> Most common case is when I want to define function with multiple input arguments all of which are subtypes of Real

In which case use `f(a::Real)` instead. and for most cases you don't even need to specify the type constraint unless you want to define a more generic version that takes non-Real to do something else.

**Comment by AzamatB** [comment]
@yuyichao  just edited my comment.

**Comment by yuyichao** [comment]
The point about not specifying the type constraint of the type parameter or the argument still apply

**Comment by AzamatB** [comment]
Well, very common reason for specifying type constraints is to ensure that code will error out when called with inappropriate argument types, which makes error tracking way easier.

**Comment by JeffBezanson** [comment]
See https://github.com/JuliaLang/julia/issues/11310#issuecomment-170894828 , we're planning some syntax changes here already.

I think changing the meaning of `F,I<:Real` is a non-starter; maybe something ilke `(F,I)<:Real` instead, though that doesn't really make sense.

**Comment by AzamatB** [comment]
> `(F,I)<:Real` instead, though that doesn't really make sense.
Why?

**Comment by yuyichao** [comment]
```
julia> (Int,Int) <: Real
ERROR: TypeError: subtype: expected Type{T}, got Tuple{DataType,DataType}
 in eval(::Module, ::Any) at ./boot.jl:267
```

**Comment by StefanKarpinski** [comment]
This really doesn't see worth the complication to save a little typing.
