### ISSUE TITLE
NEWS: breaking changes section & ditch older news

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#15241]
It's hard to easily see which changes are breaking in a new Julia version – I propose that we have a section *just* for breaking changes, or that we at least prefix breaking changes with `[breaking]` or something like that. The NEWS file is also getting a bit long – how about deleting the old changes when we start development of a new version? I.e. NEWS.md would only contain changes since the last major release.

**Comment by tkelman** [comment]
We should maybe archive the release notes for old versions. Maybe just on the release branches is good enough.

**Comment by StefanKarpinski** [comment]
@JeffBezanson recommended moving old NEWS into a HISTORY file, which seems sensible.

**Comment by stevengj** [comment]
+1 for putting old news in a history file.  Maybe a ⚠️  (or 💔?) by breaking changes?

**Comment by stevengj** [comment]
PS. It would be nice to include release dates in the `HISTORY` file, too, for reference.

**Comment by JeffreySarnoff** [comment]
suggest collecting all the breaking changes together under their own heading as one of the first few sections (not the first, that should announce the more substantive advancements -- breaking or not) of the NEWS file.

**Comment by JeffBezanson** [comment]
Looking at the NEWS file recently, the breaking changes section seems tricky to maintain. The problem is that there are sections for language changes, library changes, and breaking changes, where some things obviously fit more than one category. So what exactly should the section be for? Maybe for things that don't have deprecation warnings? Then there are some in-between cases like `UTF16String`, which give a useful error but aren't set up to keep code working automatically.

**Comment by stevengj** [comment]
I would say that the breaking changes section should mainly be for things that could *silently* break existing code by changing an existing behavior.

**Comment by JeffreySarnoff** [comment]
To use the Breaking Changes section for breaking changes seems sane.
Library Changes and Library Improvements are much the same thing, 
Language Changes feels like a different heading .

**Comment by stevengj** [comment]
@JeffreySarnoff, language changes may also be breaking changes in some cases (where an existing construct changes in meaning), and not breaking in other cases (where a new construct is added).

I don't see a problem with listing something under both headings in cases where there is overlap but not equivalence — if a change has both breaking and non-breaking aspects.

**Comment by JeffreySarnoff** [comment]
@stevengj fair enough
