### ISSUE TITLE
not displaying function directive in Sphinx documentation

### ISSUE THREAD

**Issue by ultradian** [JuliaLang/julia#15243]
I'm not sure why, but when I view the many .rst files that contain a 
`. . function::`
directive, they don't show up on the page.  An example is  JuliaLang/julia/doc/stdlib/c.rst which shows up as two headings and no other text when I look at it.  I tried different browsers and editing the text to add a domain as described in http://www.sphinx-doc.org/en/stable/domains.html.  i.e.
`. . c:function::`
but that didn't work either.  Is this something with how Github renders or do I have something else I'm overlooking in my setup?  Are others seeing this problem?

**Comment by nalimilan** [comment]
Yes, it's an issue with GitHub. If you click on Raw to see the actual contents of the file, these sections are visible.
