### ISSUE TITLE
Problem with .^ Domain Error.

### ISSUE THREAD

**Issue by joseespino** [JuliaLang/julia#15253]
Hi! 

I have a problem with exponential operator. For example:

julia> **-2324.23424.^0.2**
-4.712550085432827
 or
julia> **-2324.23424^0.2**
-4.712550085432827

but when I assign this value to a variable o the value is in a matrix the problem appear.

julia> **a = -2324.23424**
-2324.23424

julia> **a.^0.2**
ERROR: DomainError
 in .^ at operators.jl:96

**Comment by tkelman** [comment]
Unary minus is lower precedence than exponentiation, so `-2324.23424^0.2` is equivalent to `- (2324.23424^0.2)`

**Comment by joseespino** [comment]
@tkelman but the problem is that I don't know the value of the variable. It could be positive or negative.

**Comment by tkelman** [comment]
What would you like to happen for a negative number to a fractional power? If you want a complex result, convert the input to a complex number before taking the fractional power. If you want NaN's, have a look at https://github.com/mlubin/NaNMath.jl

**Comment by joseespino** [comment]
@tkelman I would like to obtain the same result using the second option.

(1)    -2324.23424.^0.2
(2)    a.^0.2

**Comment by tkelman** [comment]
You need to do `(-2324.23424).^0.2` to get the same result as `a.^0.2` here, since `-` is a lower precedence than `.^`

**Comment by joseespino** [comment]
Ok, Thanks
