### ISSUE TITLE
moving the PKGDIR results in error

### ISSUE THREAD

**Issue by axsk** [JuliaLang/julia#15256]
After moving my PKGDIR (.julia) I was confronted with:

``` julia
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: symlink: file already exists (EEXIST)
 in symlink at fs.jl:167
 in mkcachedir at pkg/cache.jl:21
 in prefetch at pkg/cache.jl:29
 in update at ./pkg/entry.jl:289
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

I suppose this happens because the `v0.4/.cache` is a symlink to a void location, thus trying to be recreated but failing as it already exists.

Removing the symlink fixed the problem, but I think this should be handled anyhow.

**Comment by kshyatt** [comment]
Is this one of those Pkg bugs that still exists and that we want to address?

**Comment by tkelman** [comment]
We could try to re-link the cache if this specific error happens I suppose. Even if this were fixed, moving the package directory is likely to still be error-prone because of paths in `.ji` files and `deps.jl` files and any compiled binary dependencies.

**Comment by wildart** [comment]
I'd say do not move it but copy or better reinitialize. Moreover, dependency cache format is going to change, so any fix would be temporary.

But if anybody decides to to work on it, the file status info should be looked up for `.cache` dir/symlink.

**Comment by simonbyrne** [comment]
Should now be addressed with new Pkg.
