### ISSUE TITLE
The project name

### ISSUE THREAD

**Issue by rennis250** [JuliaLang/julia#15252]
I imagine this issue might not be taken well, especially since Julia has been in development for many years now and has seen widespread acknowledgement. However, I feel that the name of the project is less than optimal. I will start with two examples:

"Julia is fast."
"Julia is easy."

Taken out of context, both of these sentences are very derogatory remarks towards women, at least in American English. When we consider that talking with colleagues in the hallway is normally overheard out-of-context by those that walk by, then I hope you will immediately understand the point I am trying to make.

In addition, when I have tried to introduce the language, I have sometimes been smirked at by others, who typically make some comment about male computer scientists lacking relationships. While I agree that this response is also not appropriate, it does pose a barrier to acceptance of the language on a grand scale.

Please note, that I am not trying to offend any of the developers or the originators of this project. I am extremely grateful for it, and use it on a daily basis for my work, which has seen much benefit as a result. In fact, I open this issue not to criticize, but as an attempt to help the project move forward with as little friction as possible.

Best,
Rob

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/13531

**Comment by nalimilan** [comment]
Thanks for your suggestions, but at this point it is *very* unlikely that the name of the project will change. Though the potential issues regarding bad puns around the name have been discussed, and can be controlled by enforcing a code of conduct: https://groups.google.com/d/msg/julia-users/qUomRDzIRus/u_Ymk4WjAgAJ

**Comment by El-Zurdo-Sordo** [comment]
I have just learned to be a bit slower, and *always* say: "The julia language is fast", "The julia language is easy", "El lenguaje de programación julia es rapido" etc.

**Comment by JeffBezanson** [comment]
@rennis250 Suggest a new name.

Not so easy is it.

**Comment by StefanKarpinski** [comment]
Let's change the name to "Jill" – we can keep the same extension.

**Comment by essenciary** [comment]
@StefanKarpinski Assuming it's a joke... but in case it's not, "Jill" would have the same problem: "Jill is an English feminine given name, a short form of the name Jillian (Gillian), which in turn originates as a Middle English variant of Juliana, the feminine form of the name Julian." https://en.wikipedia.org/wiki/Jill

**Comment by El-Zurdo-Sordo** [comment]
What about "Juli@", that is the convention in Spanish for either masculine or feminine? i.e. Julia/Julio.

**Comment by essenciary** [comment]
I'm completely neutral about the issue, but since I bumped into it, I thought I could make myself useful and checked the thesaurus for interesting nouns that contain "J" and "L". Here are some: 

* jewel: http://www.thesaurus.com/browse/jewel <- the idea of a jewel of a language is kind of nice
* jillion: http://www.thesaurus.com/browse/jillion <- related to data (synonyms: abundance, collection, etc)
* joggle: http://www.thesaurus.com/browse/joggle <- related to "data joggling" 
* justle: http://www.thesaurus.com/browse/justle <- related to data (means cluster, deluge, swarm)
* jolt: http://www.thesaurus.com/browse/jolt <- short, memorable, strong
* javelin: http://www.thesaurus.com/browse/javelin <- kick ass word, could be related to data as in drilling down, slicing, etc.

**Comment by johnmyleswhite** [comment]
I'd like to propose that we lock this issue. Right now, the conversation is very well-intentioned and raises a real problem that worries me frequently. But I can see this issue coming to the attention of bad actors, who I fear will turn the currently polite conversation into a very hostile one.

Were we likely to change the name, I would not be proposing that we lock this issue. But given that I understand we are not likely to take actions based on this issue, I think we should preemptively close a potential forum for bad behavior.

**Comment by StefanKarpinski** [comment]
Sure. Let's lock it.
