### ISSUE TITLE
Julia build fails on OS X with latest master

### ISSUE THREAD

**Issue by protogeezer** [JuliaLang/julia#15255]
build with fresh git clone fails while building libosxunwind...

===========
```
et-imac-retina:julia sjbespa$ ./clone-julia julia-0.5-master
Cloning into 'julia-0.5-master'...
remote: Counting objects: 169353, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 169353 (delta 4), reused 0 (delta 0), pack-reused 169341
Receiving objects: 100% (169353/169353), 97.26 MiB | 8.92 MiB/s, done.
Resolving deltas: 100% (129141/129141), done.
Checking connectivity... done.

et-imac-retina:julia sjbespa$ cd julia-0.5-master

et-imac-retina:julia-0.5-master sjbespa$ make -j4
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/doc/julia/examples
Copying in usr/share/man/man1/julia.1
...
patching file TESTS/bug_1315_double.c
patching file TESTS/bug_1315_single.c
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
clang: error: no such file or directory: 'libosxunwind.a'
make[2]: *** [libosxunwind.dylib] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by vtjnash** [comment]
iirc, this indicates an issue with your path, such as having a space in it

**Comment by protogeezer** [comment]
The path is:
et-imac-retina:julia-0.5-master sjbespa$ pwd
/Users/sjbespa/work/julia/julia-0.5-master
No spaces; is there something else going on with the path?

BTW, I built from the master again, and still got the error about the circular dependency, but it didn't crash:

patching file TESTS/bug_1315_double.c
patching file TESTS/bug_1315_single.c
make[2]: Circular src/libuwind.cxx <- src/libuwind.cxx.o dependency dropped.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libosxunwind.a(Unwind-sjlj.c.o) has no symbols
clang: warning: optimization flag '-finline-functions' is not supported

so, since it's crashed twice and made it through once, perhaps there is a problem with the -j4 switch?

**Comment by ViralBShah** [comment]
Yes, the -j 4 switch is problematic. You can use it, but there will be a dependency problem at some stage, which can be cleaned up with a simple make (without -j).

**Comment by ViralBShah** [comment]
If pure make works, this issue should be retitled.

**Comment by tkelman** [comment]
And potentially moved to https://github.com/JuliaLang/libosxunwind, if that's the only place where parallel make can be repeatably demonstrated to cause problems right now.

**Comment by protogeezer** [comment]
This issue was moved to JuliaLang/libosxunwind#5
