### ISSUE TITLE
recent parser performance regression 

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#15262]
With the recent work on modifying julia-syntax, I assumed it should be faster now. However, I was surprised to find that f5033ad seemed to be about twice as fast on one of my torture benchmarks (https://github.com/JuliaLang/julia/pull/9729#issuecomment-71351493) than both v0.4 and master today (636916e).

(there's nothing special about that first commit, i just usually try to have one build on my machine that lags behind my current work)

**Comment by nalimilan** [comment]
Any chance it could be related with https://github.com/JuliaLang/julia/issues/15246?

**Comment by vtjnash** [comment]
Looks like this was fixed in v0.5
