### ISSUE TITLE
Doc banners not in sync.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julia#15268]
See:
- http://docs.julialang.org/en/latest/manual/interacting-with-julia
- http://docs.julialang.org/en/release-0.4/manual/interacting-with-julia

Refs:
- https://github.com/JuliaLang/julia/pull/15039
- https://github.com/JuliaLang/julia/pull/15038

Some banner examples in latest docs:

``` julia
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.3.0-prerelease+2834 (2014-04-30 03:13 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 64f437b (0 days old master)
|__/                   |  x86_64-apple-darwin13.1.0

julia>
```

We need this banner examples to be auto generated and tested to stay in sync. It's potentialy very confusing to newcomers. 

Also a little of topic, but, why was `help` function removed? I can't find the exact commit for when this happened.

**Comment by vtjnash** [comment]
i think the appropriate place to document this is: https://github.com/JuliaLang/julia/blob/91d466a9945b10ad9b6f00e864c9c517e070019c/Makefile#L154

**Comment by KristofferC** [comment]
Banner is now in sync.
