### ISSUE TITLE
explain length-1 tuple syntax in manual

### ISSUE THREAD

**Issue by grisuthedragon** [JuliaLang/julia#15279]
I am currently porting some code from Julia 0.3.11 to 0.4.3. There I had to adjust the structures like:

```
type d1
 x
 pos::(Int)
end

type d2
 x
 pos::(Int,Int)
end

type d3
 x
 pos::(Int,Int,Int)
end
```

and instantiate them using:

```
x1 = d1(1,(1))
x2 = d2(2,(1,2))
x3 = d3(3,(1,2,3))
```

This works fine in Julia 0.4.3 and now I port the stuff to julia 0.4.3 and get the following type definitions:

```
type d1
 x
 pos::Tuple{Int}
end

type d2
 x
 pos::Tuple{Int,Int}
end

type d3
 x
 pos::Tuple{Int,Int,Int}
end
```

and using the save instantiation. Thereby, it only works for _d2_ and _d3_ but in the case of _d1_ I get:

```
x1 = d1(1,(1))
LoadError: MethodError: `convert` has no method matching convert(::Type{Tuple{Int32}}, ::Int32)
This may have arisen from a call to the constructor Tuple{Int32}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::T<:Tuple{Any,Vararg{Any}})
  convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T<:Tuple{Any,Vararg{Any}}}, !Matched::Tuple{Any,Vararg{Any}})
  ...
while loading In[20], in expression starting on line 1

 in call at In[17]:2
```

**Comment by KristofferC** [comment]
Tuple of length 1 is written `(1,)`

**Comment by grisuthedragon** [comment]
Ok, this works . But than it needs to be mentioned as well in thge Types - Tuples section of the documentation. Because there http://docs.julialang.org/en/release-0.4/manual/types/#tuple-types it is not mentioned.

**Comment by nalimilan** [comment]
That section is about tuple types, not about tuples, so it's not really the best place. I think it's documented, but I don't remember where.

**Comment by nalimilan** [comment]
Got it, there's a mention of this in the "Calling C and Fortran code" section: http://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/#calling-c-and-fortran-code

But this is clearly not where one would expect to find such an information. Looks like we need a small part about tuples. The beginning of the manual covers numeric types, strings, functions, but not tuples. Where could we add this?

**Comment by phobon** [comment]
This is only slightly related, but I realized the manual also does a bad job of introducing dictionaries. As far as I can tell, the manual starts discussing their use before explaining their syntax and detailed discussion doesn't come until the standard library sections, which is clearly oriented more towards reference than tutoring.

Maybe a short chapter could be added towards the beginning to introduce the first-class collection types, including tuples, dicts, and basic arrays before the comprehensive array chapter later. Just a thought.

**Comment by nalimilan** [comment]
Makes sense. Pairs should also be introduced at the same time as dictionaries.

**Comment by JeffBezanson** [comment]
This syntax is now explained in the functions chapter.
