### ISSUE TITLE
merge 0.4.3 changes to multi-threading branch

### ISSUE THREAD

**Issue by pevnak** [JuliaLang/julia#15273]
Hello to all,
i do apologise for my request, though I have a following problem. I have checked about multithreading branch and compile it, but it has build the Julia version 0.4.0. Since I use Julia 0.4.3, there are some things missing, which prevents me to try my code with threading. Would it be possible to update the multi-threading branch to support features of Julia 0.4.3.
I do apologise for terminology, I am not very skilled in git.
Thank you very much.

**Comment by tkelman** [comment]
The multi-threading support has not existed as a separate branch for some time. It was merged into master and is enabled by a (currently) non-default make flag `JULIA_THREADS=1`. We're not likely to backport that to the release branch.
