### ISSUE TITLE
How to save file in.ipynb

### ISSUE THREAD

**Issue by FedericoF1993** [JuliaLang/julia#15287]
Hi everyone!
I started from a few days using Julia so I'm a beginner .
I created a new file in Julia(not through the console but online. Sorry, I don't know the name of the platform) using kernel Julia 0.3.12. The file contains also some filled markdown cells with LatEx
Now this file is saved as ps1.ipynb on my Juliabox. Since I need to send it via email, I've been asked to save it as "Julia Notebook File". I guess that is the Python Notebook.ipynb.
My problem is that when I save it in this format and I upload it on my Juliabox, as soon as I try to run it I don't get the same file I created anymore but just a series of codes.
I know there is a way since my teacher sent me the lecture done in class in .ipynb which I uploaded and run, getting exactly the same things we have done in class, with codes and markdown cells.
I guess I have to create the same file.
Also, I tried to download from Julia the file which has been sent to me from my teacher and once I have uploaded  this file I got again a page with a series of code.
It is obvious that I'm wrong with something. 
Can you please explain me how to get such a file in .ipynb so that once I upload it and I run it "I can see on my screen exactly what I've done?"
I'm sorry for the lack of technical language but I'm a beginner so far.
Thank you all!

**Comment by ViralBShah** [comment]
This is not an appropriate place for questions. It is mainly for reporting bugs and development related issues. Please ask on julia-box or julia-users mailing list.

**Comment by tomaklutfu** [comment]
Hi welcome to julia. There is a julia-users google group for questions. Github is only for bugs specific to julia.
Try asking here https://groups.google.com/forum/m/#!forum/julia-users or gitter https://gitter.im/JuliaLang/julia .
