### ISSUE TITLE
gmp: overflow in mpz type

### ISSUE THREAD

**Issue by drichardson** [JuliaLang/julia#15293]
I have a reproducible crash on multiple versions of Julia.

```
julia> log2(BigInt(2)^233423411231)
gmp: overflow in mpz type

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
```

My configuration:
OS X 10.11.2

Occurs in Julia 0.4.3 release and Julia 0.5 nightly as of today (0.5.0-dev+2440).

**Comment by JeffBezanson** [comment]
dup of #8286
