### ISSUE TITLE
Binary PPA for Ubuntu still on 0.4.2

### ISSUE THREAD

**Issue by joshjob42** [JuliaLang/julia#15297]
ppa:staticfloat/juliareleases latest version of Julia is 0.4.2. Given it's been several weeks since 0.4.3 came out, that ought to be updated, right?

**Comment by tkelman** [comment]
Yes, but that's maintained by `@staticfloat` who has been very busy lately. We recommend using the generic linux binaries. If anyone would like to help maintain the Ubuntu PPA, please contact Elliot. Otherwise we should probably remove the PPA from the list of downloads.

**Comment by ViralBShah** [comment]
+1 to removal.

**Comment by nalimilan** [comment]
Updating to 0.4.3 shouldn't be too much work given that 0.4.2 already builds fine. @petercolberg @ginggs Any interest? Or would you know potentially interested people?

**Comment by ginggs** [comment]
+1 for removal, too.  I'd rather see updates go into Ubuntu Backports https://help.ubuntu.com/community/UbuntuBackports

**Comment by nalimilan** [comment]
A user just reported at https://github.com/JuliaStats/GLM.jl/issues/133 that some sparse matrix operations do not work either because LAPACK doesn't seem to be available in OpenBLAS there. Indeed, OpenBLAS is still 0.2.8, which is getting old. So indeed we'd better not advertise the PPA if we can't fix this kind of issue.

@ginggs Would you be willing to set up an Ubuntu backports package?

**Comment by tkelman** [comment]
I thought the juliadeps ppa had a somewhat more recent version of openblas (though built as blas-only openblas then separate netlib blas, because old-fashioned distro packaging likes to split things up that way), but yeah I'll delete the PPA reference when I update the links for the latest release.

**Comment by tkelman** [comment]
ppa links removed from download page

**Comment by tkelman** [comment]
Looks like I missed https://github.com/JuliaLang/julialang.github.com/blob/master/downloads/platform.md#linux, should replace the ubuntu PPA instructions with generic linux nightly instructions of "download & extract tarball, optionally symlink or add to path"

**Comment by ginggs** [comment]
@nalimilan: With the release of Ubuntu 16.04 LTS less than a month away, I don't think it is worth backporting to 15.10 and 14.04 LTS. 

(I experimented with a 14.04 backport and it needs quite a few libraries to be backported along with it; openblas, lapack, pcre2, and the list goes on.  I didn't get around to testing)

I'm happy to manage Julia backports to Ubuntu 16.04 LTS going forward.

**Comment by nalimilan** [comment]
@ginggs Makes sense, thanks!
