### ISSUE TITLE
matrix multiply with mismatched inner dimensions gives unexpected result

### ISSUE THREAD

**Issue by johngrogan** [JuliaLang/julia#15305]
After updating my copy of julia 0.4, I'm finding multiplying a 3x3 matrix with a 1x3 matrix is producing output. It should complain about mismatched dimensions. Pretty sure it used to complain. Example below.

```
julia> a = [1 2 3; 0 0 0; 0 0 0]
3x3 Array{Int64,2}:
 1  2  3
 0  0  0
 0  0  0

julia> b = [1 2 3]
1x3 Array{Int64,2}:
 1  2  3

julia> a*b
3x3 Array{Int64,2}:
 14  8  3
  0  0  0
  0  0  0
```

I am building off git clone release-0.4 branch in Linux, and just done an update. Details below.

```
julia> versioninfo()
Julia Version 0.4.4-pre+35
Commit 1a9429e (2016-02-12 13:21 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     T7500  @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Core2)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
I did a git pull followed by 'make', to update. I'll try a complete clean and rebuild to see if that changes things.

**Comment by andreasnoack** [comment]
I can confirm the bug. Accidentally, the change in https://github.com/JuliaLang/julia/commit/6db0a4f31259cee57865d131bd591382a18cca86 removed the check for the inner dimension for 2x2 and 3x3 matrices. I'll submit a PR soon.

**Comment by StefanKarpinski** [comment]
Perhaps there should be tests that these cases raise DimensionMismatch errors?

**Comment by tkelman** [comment]
there are a few in #15306, could always be more though

**Comment by andreasnoack** [comment]
`DimensionMismatch` is already tested in all but the 2x2 and 3x3 cases for which I added tests in #15306

**Comment by johngrogan** [comment]
Thanks for the fast attention this issue has been given. I've also noticed that the DimensionMismatch error text sometimes gives the wrong dimensions. Not sure if you want to add this fix into your PR as well, or create another. Details below. Thanks.

Example:
```
julia> x = ones(Int,1,2)
1x2 Array{Int64,2}:
 1  1

julia> y = ones(4,4)
4x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> x*y
ERROR: DimensionMismatch("matrix A has dimensions (1, 4), matrix B has dimensions (4, 4)")
 in _generic_matmatmul! at linalg/matmul.jl:453
 in generic_matmatmul! at linalg/matmul.jl:439
 in * at linalg/matmul.jl:132
```

Line 453 in linalg/matmul.jl has
```
    if mB != nA
        throw(DimensionMismatch("matrix A has dimensions ($mA, $nB), matrix B has dimensions ($mB, $nB)"))
    end
```

But ($mA, $nB) should be ($mA, $nA) thus

```
    if mB != nA
        throw(DimensionMismatch("matrix A has dimensions ($mA, $nA), matrix B has dimensions ($mB, $nB)"))
    end
```

Example with fix
```
julia> x = ones(Int,1,2)
1x2 Array{Int64,2}:
 1  1

julia> y = ones(4,4)
4x4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> x*y
ERROR: DimensionMismatch("matrix A has dimensions (1, 2), matrix B has dimensions (4, 4)")
 in _generic_matmatmul! at linalg/matmul.jl:453
 in generic_matmatmul! at linalg/matmul.jl:439
 in * at linalg/matmul.jl:132
```

**Comment by andreasnoack** [comment]
@johngrogan Thanks for the followup. Please always provide the output of `versioninfo()` such that we know which version of Julia that causes the issue. The wrong reporting of the dimensions should be fixed on master. I might be possible to backport it to 0.4.

**Comment by andreasnoack** [comment]
I just checked and the fix is only 29 days old and marked for backporting so in next bugfix release of Julia 0.4 the dimensions reported should be correct.
