### ISSUE TITLE
jl_yield() causes segfault from c

### ISSUE THREAD

**Issue by dioptre** [JuliaLang/julia#15301]
I'm inserting a `jl_yield` so that my hungry process permits `@parallel` and `@spawnat` - but alas it doesn't look possible. It sometimes allows me to `@spawnat` but mostly it just crashes.

I tried: `uv_async_send` using multiple threads and it was about 1000 times slower than what I'm doing at present in a single thread (must be due to `lib_uv` joins).

If I leave the yield out it works fine :(

Not sure about this one!

``` jl
signal (11): Segmentation fault
unknown function (ip: 0x7faadaf6ea0c)
unknown function (ip: 0x7faadaf73b0c)
unknown function (ip: 0x7faadaf7e64c)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
wait at ./task.jl:369
yield at task.jl:355
jlcall_yield_21543 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_call0 at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
processmusesync at libmse.so.0.0.1 (unknown line)
anonymous at /home/a/projects/bxi/server/pipeline.jl:50
jl_f_apply at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at multi.jl:904
run_work_thunk at multi.jl:645
run_work_thunk at multi.jl:654
jlcall_run_work_thunk_21275 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at task.jl:58
unknown function (ip: 0x7faadafe0f83)
unknown function (ip: (nil))
Worker 2 terminated.
ERROR (unhandled task failure): EOFError: read end of file
```

Place of the call looks like:

``` c
    while(1) {
        if ((size_t)d[4] % 100 == 0) {
            jl_yield();
            usleep(30000);
        }
```

**Comment by yuyichao** [comment]
Please quote your code, especially macros in order to not pull in random unrelated people. Please also give a more complete picture of what you are doing.

**Comment by dioptre** [comment]
All I'm doing is writing to a buffer (float array) in RAM every 3 ms.

I pass a pointer from julia to the RAM location, and then write to it.

At this point I haven't even read the value back in Julia. Let me know if you'd like more details.

Ie.
   while(1) {
        if ((size_t)d[4] % 100 == 0) {
            jl_yield();
            usleep(30000);
        }
        d[1] = 0.5;
        d[2] = 0.5;
        usleep(3000);
}

**Comment by yuyichao** [comment]
It's still hard to tell what you are doing without seeing the complete picture.

**Comment by yuyichao** [comment]
i.e. the whole program or a stand alone repro.

**Comment by dioptre** [comment]
I run:
```
@spawnat 2 begin
ccall( (:process, "libms.so.0.0.1"), Csize_t, (Ptr{Float32},), ee)
end
```

Which runs the following code for a while above successfully, then randomly crashes.

The thing it runs is the code below:

```
   while(1) {
        if ((size_t)d[4] % 100 == 0) {
            jl_yield();
            usleep(30000);
        }
        d[1] = 0.5;
        d[2] = 0.5;
        usleep(3000);
}
```
When I comment out the jl_yield it works fine.

I'm running it so I can share volatile memory between a julia process and a few others. But as I said it never gets read and crashes.

If I remove the jl_yield I can read and write to it without issues.

**Comment by StefanKarpinski** [comment]
Is jl_yield being called from a different thread?

**Comment by dioptre** [comment]
no same one that i started with ccall from spawn 2
same effect happens too when called from pid 1

**Comment by dioptre** [comment]
Bueller? Damn

**Comment by tkelman** [comment]
Can you please provide a [MCVE](http://stackoverflow.com/help/mcve)?

**Comment by vtjnash** [comment]
if turning off COPY_STACKS in options.h fixes this, i suspect the solution is https://github.com/JuliaLang/julia/pull/13099

**Comment by dioptre** [comment]
Thanks guys! I'll take a look!

**Comment by KristofferC** [comment]
Closing due to lack of more info.
