### ISSUE TITLE
QuoteNode doesn't always preserve it's contents when returned from a macro

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#15310]
I thought that a `QuoteNode` as meant as a bulletproof way to be able to shield an expression from the compiler poking into it while e.g. returning it from a macro. But consider the following code with a macro which wraps an expression in a `QuoteNode` and returns it:

```
macro l()
    QuoteNode(Expr(:block, (Expr(:line,42,:none)), :(f(x))))
end
show(typeof(@l().args[1]))
```

This prints `LineNumberNode`, which means that the `Expr(:line,42,:none)` has turned into a `LineNumberNode`.

Should this be corrected, or do I misunderstand the intent of `QuoteNode`? If I do, does there exist a bulletproof way to shield an expression from the compiler?

**Comment by KristofferC** [comment]
This looks like it is fixed:

```jl
julia> show(typeof(@l().args[1]))
Expr
```

ok to close?

**Comment by JeffBezanson** [comment]
`LineNumberNode` is now the only official representation of locations in ASTs.

`QuoteNode` is still subject to syntax processing when it occurs in an AST (it only has the behavior of "return exactly this object" at the IR level). For example, an enclosing `quote` expression can interpolate into it:

```
julia> x = 3;

julia> ex = Expr(:quote, Expr(:tuple, 1, QuoteNode(Expr(:tuple,2,Expr(:$,:x)))))
:($(Expr(:quote, :((1, $(QuoteNode(:((2, $(Expr(:$, :x)))))))))))

julia> eval(ex)
:((1, $(Expr(:inert, :((2, 3))))))
```

(That `inert` expression should actually be a `QuoteNode`; I'll fix that. `inert` should also probably be renamed to something like `justquote`.)
