### ISSUE TITLE
Error "Function type in method definition is not a type"

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#15317]
It's related to #14919. Given the code
```julia
abstract FitnessScheme{F}

immutable MinimizingScalarScheme <: FitnessScheme{Float64}
end

is_better(x, y, fs::MinimizingScalarScheme) = x < y
```

I want to be able to call `fs(x, y)`, which would return `is_better(x, y, fs)` for any `fs::FS<:FitnessScheme`.
When I define it like this (works in v0.4):
```julia
Base.call{F}(fs::FitnessScheme{F}, x::F, y::F) = is_better(x, y, fs)
```
on v0.5 I get
```
WARNING: deprecated syntax "call(fs::FitnessScheme{F}, ...)".
Use "(fs::FitnessScheme{F})(...)" instead.
ERROR: cannot add methods to an abstract type
 in eval(::Module, ::Any) at ./boot.jl:267
```

If I try it the other way
```julia
(fs::FS){FS<:FitnessScheme,F}(x::F, y::F) = is_better(x, y, fs)
```
I get
```
ERROR: function type in method definition is not a type
 in eval(::Module, ::Any) at ./boot.jl:267
```

What would be the proper way to avoid Scylla of `abstract type` and Charybdis of `not a type` and achieve what I want?

**Comment by StefanKarpinski** [comment]
Please post usage questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.

**Comment by yuyichao** [comment]
And dup of https://github.com/JuliaLang/julia/issues/14919

**Comment by alyst** [comment]
It's not a complete duplicate of #14919, because "function type in method definition is not a type" error is not mentioned there.
Before posting the issue I've found this [thread in julia-users](https://groups.google.com/forum/#!topic/julia-users/Sbn9FQxXprY), where @yuyichao refers to the current behaviour as to a bug. That's why I have submitted the new issue.

You can leave it closed if you think it's a duplicate, or I can reformulate so it doesn't look like a usage question.

**Comment by StefanKarpinski** [comment]
> or I can reformulate so it doesn't look like a usage question.

Please do reformulate and we can reopen it.

**Comment by JeffBezanson** [comment]
It is a dup of #14919, because without that issue the first thing you tried would have worked.

**Comment by alyst** [comment]
> It is a dup of #14919, because without that issue the first thing you tried would have worked.
Would the 2nd thing work as well if #14919 is fixed?
