### ISSUE TITLE
Problems with the Dimensionality of n-by-1 and 1-by-n Arrays.

### ISSUE THREAD

**Issue by grisuthedragon** [JuliaLang/julia#15325]
I recognized the following strange behavior when creating n-by-1 and 1-by-n Arrays, which are from a mathematical point of view both arrays with two dimensions. I do not want to consider a vector of length n. 

First I considered a 1-by-n array: 
```
x = [[ 1 2 3 4 ]]
typeof(x)
```
gives 
```
Array{Int64,2}
```
which fits to the mathematical meaning. 

Second I tried
```
x = [ [ 1 ]; [ 2 ]; [ 3 ]; [ 4 ] ] 
typeof(x)
```
which gives 
```
Array{Int64,1}
```
which is wrong in my understanding and forces functions that are defined on `Array{Int,2}` do handle the n-by-1 case separately. 

Is this an bug or is there a reason why this behaves so strange? Because creating a clean n-by-1 array is possible using ` x = Array(Int,n,1)`.

**Comment by yuyichao** [comment]
FWIW, these are not the right syntax and the inner `[]` is not needed. Other than that, I think this is coverred by https://github.com/JuliaLang/julia/issues/4774

**Comment by grisuthedragon** [comment]
I do not think that it is the same as #4774. The problem is, that the syntax or the parser of julia seems not to realized that one tries to force a two dimensional array. In the case of the row vector it works, in the case of the column vector not.

**Comment by yuyichao** [comment]
The row vector one it works by accident and it will return a `Vector{Matrix{Int}}` in the future. I believe the currently the only syntax to get a column matrix is double transpose of a vector, which is why this is related to all the discussion in #4774 (and some other places linked).

**Comment by andreasnoack** [comment]
@grisuthedragon This is better suited for julia-users, but anyway: In

```jl
x = [ [ 1 ]; [ 2 ]; [ 3 ]; [ 4 ] ]
```
`[1]`, `[2]` etc are vectors of length one and `[[1]; [2]]` is concatenation of those vectors into a longer vector. You are right that entering a nx1 matrix is not super convenient. `x = [1 2 3 4]'` is probably the easiest. We have also discussed to make it possible to write `Matrix([1,2,3,4])`.

**Comment by grisuthedragon** [comment]
I think this implicit truncation of 1-by-n or n-by-1 objects to 1D arrays is the problem here, so introducing `Vector{Matrix{Int}}` for the row representation make the problem even worse. Doing a double transpose of a matrix is still a dirty trick.
