### ISSUE TITLE
joinpath returns UTF8String

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#15327]
despite inputing `ASCIIString`s, `joinpath` returns a `UTFString`, but only if one of the inputs contains a slash.  creating the same output string with `join` returns an `ASCIIString`, as expected.

this behavior (it's not by design, is it?) is an annoyance, for example, when passing strings to `MATLAB.jl`'s `mxcall`, as a call to `ascii` is needed.

```
julia> typeof(joinpath("/a","b"))
UTF8String

julia> typeof(joinpath("a","b"))
ASCIIString

julia> typeof("/a")
ASCIIString

julia> typeof("b")
ASCIIString

julia> typeof(join(["/a","b"],"/"))
ASCIIString

julia> using MATLAB

julia> mxcall(:disp,0,"a")
>> a

julia> mxcall(:disp,0,joinpath("a","b"))
>> a/b

julia> mxcall(:disp,0,joinpath("/a","b"))
>>     data: [4x1 uint8]

julia> mxcall(:disp,0,ascii(joinpath("/a","b")))
>> /a/b

```

**Comment by eschnett** [comment]
This is the reason:
```Julia
julia> typeof(string("a","/","b"))
ASCIIString

julia> typeof(string("a",'/',"b"))
UTF8String
```

Creating a string from a character (even if this is an ASCII character) creates a `UTF8String`. I assume that's necessary for type stability?

One way to solve this locally is to redefine `pathsep` to always return a one-character string instead of sometimes a character, i.e. to make `pathsep` type-stable as well.

**Comment by johnmyleswhite** [comment]
I'm pretty sure all such issues are going to go away once we remove the distinction between `ASCIIString` and `UTF8String`. I'm inclined to think we should wait for that.

**Comment by nalimilan** [comment]
@johnmyleswhite is right, but I think `mxall` should be changed to accept any `AbstractString` (and convert it if needed). Julia will still support several types of strings even when only one type is included in Base.
