### ISSUE TITLE
REPL data loss sadness

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#15326]
It used to be entirely reasonable to write an entire function in the REPL. Now, if you accidentally hit the up arrow one too many times, you are taken to the previous history entry and what you were editing and it is lost forever. This makes the REPL very risky for any non-trivial coding.

cc: @blakejohnson, @Keno

**Comment by blakejohnson** [comment]
I hear you. I guess this was the motivation for #9368, but at least in my own experimentation I found it substantially more annoying than the unique prefix search.

I guess I'm not sure why it would be lost forever, though. Ctrl+C resets the history search location, so it should be possible to find all unique versions of an input. If we are overwriting history somewhere, that's something we must fix.

**Comment by StefanKarpinski** [comment]
I never hit return, so the code is not in history and scrolling down does not get it back anymore.

**Comment by blakejohnson** [comment]
Ah, I understand now. I think we could fix that.

**Comment by pkofod** [comment]
Ah, yes, that is super annoying. +1 for being able to go back with a down arrow

**Comment by vtjnash** [comment]
@StefanKarpinski fwiw, i'm not seeing the behavior you described. in particular, if i hit 'up-arrow' then 'down-arrow', i'm right back to what i was editing. if i hit `up-arrow`, make edits, then `down-arrow`, i'm sent to the next history entry with that prefix (which is usually an empty line). but after pressing `ctrl-a` or `enter`, i can browse back to the partially edited entry in my history (@ c96f322)

**Comment by vtjnash** [comment]
now i'm seeing this too. in particular, though, it doesn't happen if i'm editing a previous history entry, but does happen if i'm writing an entirely new entry, hit up, then down.
