### ISSUE TITLE
Non-reproducible example in the Control Flow docs

### ISSUE THREAD

**Issue by Dawny33** [JuliaLang/julia#15330]
The example for `[Short Circuit Evaluation](http://docs.julialang.org/en/release-0.4/manual/control-flow/#short-circuit-evaluation)` is not reproducible, as it throws the following error:

`ERROR: error in method definition: function Base.factorial must be explicitly imported to be extended`

This is because the `factorial` function is already present in the `Base` library. 

So, it can cause confusion for starters. The name of the function in the example can be changed to something to `fact`, which can help avoid confusion without entirely changing the function.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15264

**Comment by Dawny33** [comment]
@yuyichao Thank you for pointing it out. Is it okay if I send a PR, changing the name from `factorial` to `fact`?

It can fix the problem in that doc!

**Comment by JeffBezanson** [comment]
This is only a problem if you have previously used `factorial` in the same session, but I agree we should rename it to `fact` to avoid this stumbling block.
