### ISSUE TITLE
Improve doc of eig

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#15343]
Suggestions:

* Quote from current `eig` documentation (http://docs.julialang.org/en/release-0.4/stdlib/linalg/#Base.eig):

 > See `eigfact()` for details on the ``balance`` keyword argument.  

 `balance` is not a keyword argument. Change it to plain text or replace it by `permute` and `scale`.

*  Mention that eigenvectors are in columns.

**Comment by andreasnoack** [comment]
Hi @innerlee. Thanks for the report. It would be highly appreciated if you could prepare a PR with the suggested changes.

**Comment by innerlee** [comment]
Thanks, I'll try.

**Comment by andreasnoack** [comment]
Great. Looking forward to it. Please let us know if you have any troubles in the process.
