### ISSUE TITLE
Build failure on Linux 4.4.1-2

### ISSUE THREAD

**Issue by Synthetica9** [JuliaLang/julia#15340]
This issue has existed (for me) for the last couple of days, and I don't have the slightest clue what it could be. It might be on my side. Whenever I call `make`, it starts to do stuff, until this happens: https://gist.github.com/anonymous/cda1db480657936816be. It seems to be a case of infinite recursion somewhere. Does anyone else have this problem?

**Comment by yuyichao** [comment]
Very likely dup of https://github.com/JuliaLang/julia/issues/15167

**Comment by mgr327** [comment]
I have/had the same problem. Just confirming that

  ulimit -s 10000
  make clean 
  make

fixed it for me, as it did in #15167

**Comment by Synthetica9** [comment]
@mgr327 Yep, that worked. Still, might be nice to give a hint somewhere about what it could be the cause, and how to fix it (or fix it automatically, even)

**Comment by Synthetica9** [comment]
Adding `ulimit -s 10000` to the recipe `julia-inference` works, but I doubt that's the cleanest option

**Comment by nalimilan** [comment]
I think the idea is that this should be fixed. But how long will it take, that's the question...
