### ISSUE TITLE
`powermod` with negative exponents

### ISSUE THREAD

**Issue by anthonyclays** [JuliaLang/julia#15350]
Currently, `powermod(2, -2, 5)` throws a DomainError. I think it would be both intuitive and useful to have `powermod` handle negative exponents as a modular inverse followed by a normal modular exponentiation.

As far as I can tell there aren't any noticeable performance drawbacks from implementing this - of course `invmod` can throw an Error when its arguments are not coprime, but as mentioned `powermod` currently also throws exceptions for negative exponents.

**Comment by StefanKarpinski** [comment]
Seems reasonable and useful.

**Comment by tkelman** [comment]
closed by https://github.com/JuliaLang/julia/pull/15448
