### ISSUE TITLE
Generating documentation in Base with `->`

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#15360]
I have been doing some dynamic documentation generation in Base and ran into a minor issue. Running the following code works fine from the REPL but putting the code in `base/dates/accessors.jl` and re-compiling Julia throws an exception:

```julia
using Base.Dates
for func in (:day, :dayofmonth)
   name = string(func)
   @eval begin
       @doc """
           $($name)(dt::TimeType) -> Int64

       The day of month of a `Date` or `DateTime` as an `Int64`.
       """ -> $func(dt::TimeType)
   end
end
```
When compiling I get the following exception:

```
$ make
...
profile.jl
Dates.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 309: LoadError(at "Dates.jl" line 9: LoadError(at "dates/accessors.jl" line 94: UndefVarError(var=:dt))))
[inline] at /Users/omus/Development/Julia/latest/src/task.c:667
rec_backtrace at /Users/omus/Development/Julia/latest/src/task.c:868
jl_undefined_var_error at /Users/omus/Development/Julia/latest/usr/lib/libjulia.dylib (unknown line)
eval at /Users/omus/Development/Julia/latest/src/interpreter.c:136
do_call at /Users/omus/Development/Julia/latest/src/interpreter.c:64
eval at /Users/omus/Development/Julia/latest/src/interpreter.c:422
do_call at /Users/omus/Development/Julia/latest/src/interpreter.c:64
eval at /Users/omus/Development/Julia/latest/src/interpreter.c:422
eval_body at /Users/omus/Development/Julia/latest/src/interpreter.c:519
jl_toplevel_eval_flex at /Users/omus/Development/Julia/latest/src/toplevel.c:537
jl_toplevel_eval_in_warn at /Users/omus/Development/Julia/latest/src/builtins.c:551
unknown function (ip: 0x31a89735e)
unknown function (ip: 0x31a897010)
[inline] at /Users/omus/Development/Julia/latest/src/./julia_internal.h:69
jl_call_method_internal at /Users/omus/Development/Julia/latest/src/toplevel.c:556
jl_parse_eval_all at /Users/omus/Development/Julia/latest/src/ast.c:784
jl_load_ at /Users/omus/Development/Julia/latest/src/toplevel.c:589
unknown function (ip: 0x311d0c040)
unknown function (ip: 0x31256d1b4)
do_call at /Users/omus/Development/Julia/latest/src/interpreter.c:61
eval at /Users/omus/Development/Julia/latest/src/interpreter.c:422
jl_toplevel_eval_flex at /Users/omus/Development/Julia/latest/src/toplevel.c:543
jl_eval_module_expr at /Users/omus/Development/Julia/latest/src/toplevel.c:170
jl_parse_eval_all at /Users/omus/Development/Julia/latest/src/ast.c:784
jl_load_ at /Users/omus/Development/Julia/latest/src/toplevel.c:589
unknown function (ip: 0x311d0c040)
unknown function (ip: 0x31256d1b4)
do_call at /Users/omus/Development/Julia/latest/src/interpreter.c:61
eval at /Users/omus/Development/Julia/latest/src/interpreter.c:422
jl_toplevel_eval_flex at /Users/omus/Development/Julia/latest/src/toplevel.c:543
jl_eval_module_expr at /Users/omus/Development/Julia/latest/src/toplevel.c:170
jl_parse_eval_all at /Users/omus/Development/Julia/latest/src/ast.c:784
jl_load at /Users/omus/Development/Julia/latest/src/toplevel.c:584
exec_program at /Users/omus/Development/Julia/latest/usr/bin/julia (unknown line)
true_main at /Users/omus/Development/Julia/latest/usr/bin/julia (unknown line)
main at /Users/omus/Development/Julia/latest/usr/bin/julia (unknown line)

*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/Users/omus/Development/Julia/latest/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2
```

Alternatively running the same code without `->` allows the code to work both in the REPL and compile in Julia. I realize that excluding the arrow is the correct thing to do when you are not defining a method but it seems strange that the arrow works fine on the REPL.

**Comment by MichaelHatherly** [comment]
If this behaviour is limited to bootstrapping `Base` and not present outside / in the REPL then my best guess is the problem is in [this code](https://github.com/JuliaLang/julia/blob/ca6f253c0c4c1c731621e02c1b00a6fe374fc473/base/docs/bootstrap.jl#L22-L34). The "call" syntax should be returning `nothing`, but it's clearly not given that you're getting an undefined var error. I'll have a closer look later this evening if no one else beats me to it.

**Comment by vtjnash** [comment]
This strikes me as an incredibly terrible way to create auto generated documentation.  We shouldn't need eval and a liberal sprinkling of $ and @ to insert a string into a Dict.

**Comment by StefanKarpinski** [comment]
I rather agree. Why can't the dynamic version of adding a doc strong just be inserting a key-value pair in a hash? Or maybe calling a function that does so?

**Comment by MichaelHatherly** [comment]
Yes, there's definitely a lot of symbols in that example. A reduced case for this failure would just be

```julia
@doc "..." -> func(x)
```

> Or maybe calling a function that does so?

It would be totally possible to add something like

```julia
for func in (day, dayofmonth)
    doc!(
        """
            $(func)(dt::TimeType) -> Int64

        The day of month of a `Date` or `DateTime` as an `Int64`.
        """,
        func, Tuple{TimeType}
    )
end
```

if you'd be more happy with that?

**Comment by tkelman** [comment]
I like the sound of a `doc!` function, if the generated case needs to jump through macro hoops to imitate the syntax of the non-generated case, maybe it's not worth using special syntax to do it.

**Comment by StefanKarpinski** [comment]
Agreed. In the generated case, it seems like the syntax is not going to be simple and clean no matter what, so trying to make it imitate the normal syntax seems like it might be counterproductive.

**Comment by omus** [comment]
I also like idea of a `doc!` function :+1:

**Comment by StefanKarpinski** [comment]
Yes, seems like a sane approach to me.

**Comment by MichaelHatherly** [comment]
Great, I'll sort out a PR for this once I've cleared out my currently pending PRs.
