### ISSUE TITLE
Bracketed-Paste-Mode pasting doesn't move cursor far enough

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15372]
To reproduce:
- Type something, e.g. `s = `
- Paste something else (if the terminal supports bracketed paste mode)

Result:
<img width="399" alt="screen shot 2016-03-05 at 11 39 53 pm" src="https://cloud.githubusercontent.com/assets/1291671/13552320/9a8ab78c-e32b-11e5-9362-9da54565cb4c.png">
i.e. the cursor is one spot too far to the left.

**Comment by StefanKarpinski** [comment]
I've seen this as well.

**Comment by vtjnash** [comment]
this seems to be an off-by-one error in `oldpos` during bracketed paste introduced by da9ef90b236b5d1dbe0cd06285c716c560558057 which affected the computation of the `seek` computation
