### ISSUE TITLE
ERROR: InexactError()  in *(SparseMatrix{Int,Int},Diagonal)

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#15380]
```
ERROR: InexactError()
 in scale!(::SparseMatrixCSC{Int64,Int64}, ::Array{Float64,1}, ::SparseMatrixCSC{Int64,Int64}) at ./sparse/linalg.jl:805
```
in 0.5. 0.4 is not affected.

This happens here:

```
using LightGraphs
g5 = DiGraph(4)
add_edge!(g5,1,2); add_edge!(g5,2,3); add_edge!(g5,1,3); add_edge!(g5,3,4)
pagerank(g5)
```

causing LG tests to fail on -nightly.

**Comment by sbromberger** [comment]
And for completeness, here's pagerank (I modified `scale` to `Diagonal` per the deprecation warning to see if it had any effect; it didn't.)

```
function pagerank(g::DiGraph, α=0.85, n=100, ϵ = 1.0e-6)
    M = adjacency_matrix(g)
    S = vec(sum(M,1))
    S = 1./S
    S[find(S .== Inf)]=0.0
    M = Diagonal(S) * M'
    N = nv(g)
    x = repmat([1.0/N], N)
    p = repmat([1.0/N], N)
    dangling_weights = p
    is_dangling = find(S .== 0)

    for _ in 1:n
        xlast = x
        x = α * (M.' * x + sum(x[is_dangling]) * dangling_weights) + (1 - α) * p
        err = sum(abs(x - xlast))
        if (err < N * ϵ)
            return x
        end
    end
    error("Pagerank did not converge after $n iterations.")
end
```

**Comment by sbromberger** [comment]
cc @jpfairbanks since he knows more about matrix operations than I do.

**Comment by jpfairbanks** [comment]
trying to scale Float64 by Int64. I guess `scale` used to promote and now it doesn't?

**Comment by sbromberger** [comment]
Closing since we managed to work around it.

**Comment by andreasnoack** [comment]
It is correct to throw `InexactError` in `scale!` since an array with `Int` elements cannot be scaled in place, but the should be promoted to a suitable element type in in `*(SparseMatrixCSC, Diagonal)` so I'll reopen with a new title.
