### ISSUE TITLE
A function works under @debug but crashes without

### ISSUE THREAD

**Issue by vepiteski** [JuliaLang/julia#15388]
The title says it all. The function is part of a larger project so submitting a 3 lines code to reproduce the issue is out of question.

Without debug: a parameter which should be of type A is dispatched to a function (expecting it to be of type A) as of type B. 

```
ERROR: LoadError: MethodError: `PreProcess` has no method matching PreProcess(::LinearOperators.LinearOperator, ::Array{Float64,1}, ::Int64, ::Int64, ::Int64)
```

`PreProcess` expects a `Array{Float64,2}`, NOT a `LinearOperators.LinearOperator`

With `@debug`, the parameter is indeed of class `A` and no error is triggered.
- The parameter is indeed a `Array{Float64,2}`, so I cannot find any fault in my code.

Thx,

JPD

**Comment by yuyichao** [comment]
Please quote your code, especially macros, or you'll be pulling random people into unrelated discussions (see my edit).

This is possibly a dispatch bug but without a piece of code to reproduce it (which doesn't have to be small but has to be complete) there's basically nothing we can do here.

**Comment by vtjnash** [comment]
What is `versioninfo`?

**Comment by toivoh** [comment]
I have done my best to make the `@debug` macro not change the meaning of any code, but if there is a difference then it might be because of a bug in `@debug`. Or maybe the debug instrumentation precludes Julia from carrying out some optimization that doesn't work right in this case.

**Comment by vepiteski** [comment]
Thank you all for the comments. 

julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3


Here is the situation: my code is structured as
` include("PDataK.jl")
  x, f, gNorm, gnorm2,iter, optimal, status = TRARC(nlp,   ...               
  reset!(nlp)
  include("PDataLDLt.jl")
  x, f, gNorm, gnorm2,iter, optimal, status = TRARC(nlp,  ...                                             
`

TRARC implements a general Newton like optimization algorithm. PDataK includes a function Hessian_Rep(nlp,x) to produce a "linear operator representation of the Hessian" for use within an iterative linear solver while PDataLDLt version of Hessian_Rep(nlp,x) produces an array{Float64,2} representation of the Hessian used within a LDLt factorization.

The second call to TRARC crashes because apparently the previous version of Hessian_Rep is still in use. I compiled TRARC with @debug to track down the bug but this time, no error.

Using "?Hessian_Rep" in the julia shell points to the correct version of Hessian_Rep, i.e. the file "PDataLDLt.jl".

Hope my issue is clearer now.

JPD

**Comment by vepiteski** [comment]
The code was badly formatted, sorry.
Here is it in plain text.


  include("PDataK.jl")

  x, f, gNorm, gnorm2,iter, optimal, status = TRARC(nlp, 

  reset!(nlp)

  include("PDataLDLt.jl")

  x, f, gNorm, gnorm2,iter, optimal, status = TRARC(nlp, 


JPD

**Comment by yuyichao** [comment]
Please quote your code. If you are not sure how it works, see my edit and use the "preview" tab. There's still not really much useful info to reproduce the bug. (i.e. it's impossible to reproduce the bug just from your discription)

**Comment by JeffBezanson** [comment]
@vepiteski I don't know if this is the problem, but I would suggest not including a different file and overwriting the `Hessian_Rep` function. The two versions of the function should be in separate modules, or have different names, or be distinguished by arguments somehow to allow them to coexist.

Other than that, without code we can actually run to see the problem I don't think we can make progress on this. The nature of bugs is that they usually depend on exactly how code is written.

**Comment by vepiteski** [comment]
Hi everyone!

Thank for all your comments. I solved my problem. Before the second call to TRARC, I  include("TRARC.jl"). I think that TRARC was compiled with the call to the previously included version of Hessian_Rep.

This raises the question: why, using @debug, the second call to TRARC accesses to the recently included version of Hessian_Rep while without, it still uses the first one and I need to explicitly include TRARC again to have it work? 

I don't know if my code design is sound, I include different versions of "PData" to make TRARC independent of the implementation choices in them, aka object oriented but coded using dispatch.

Thx again,

JPD

**Comment by toivoh** [comment]
Now that you know what caused the problem, would it be possible for you to distill a small test case and submit as an issue at https://github.com/toivoh/Debug.jl? Then maybe I could have a look to see what causes the difference.

**Comment by vepiteski** [comment]
I don't succeed in reproducing a small example exhibiting the differences between using debug or not. However, the "bug" seems related to the fact that the compiler inlines a function call so the currently loaded function is not executed. On my complete but quite elaborate example, it seems that the function was not inlined using debug while the opposite without. Here is a small example. 

I will try to produce a self contained (but quite large) example later on.

definition of function "f" in file fa.jl
`function f(dummy::Float64)
    return "A"
end
`
Definition of function "f"in file fb.jl:
`function f(dummy::Float64)
    return "B"
end
`
Definition of function example in file BufDebug.jl

    #@debug 
    function example(dummy::Int)
        a= f(1.0)
        println(a, "\n")
    end

The execution script in file execute.jl:

    include("BugDebug.jl")

    include("fa.jl")
    println(" should print A") 
    example(1)
    println("Result of f(1.0): $(f(1.0))")
    println("\n\n")

    include("fb.jl")
    println(" should print B")
    example(1)
    println("Result of f(1.0): $(f(1.0))")


the output:

      should print A
     A

     Result of f(1.0): A



     should print B
    A

    Result of f(1.0): B

**Comment by KristofferC** [comment]
Please update if this is still relevant after all changes (especially #265)
