### ISSUE TITLE
Problems handling multiple unicode characters in a string.

### ISSUE THREAD

**Issue by dcarrera** [JuliaLang/julia#15386]
Julia seems to have trouble handling the second sequential unicode character on a string:

```
julia> "ßß"[1]
'ß'
julia> "ßß"[2]
ERROR: UnicodeError: invalid character index
 in next at ./unicode/utf8.jl:65
 in getindex at strings/basic.jl:37
julia> "großgroß"[9]
'ß'

julia> "中国"[1]
'中'
julia> "中国"[2]
ERROR: UnicodeError: invalid character index
 in next at ./unicode/utf8.jl:65
 in getindex at strings/basic.jl:37

julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
...
```

Any ideas?

**Comment by nalimilan** [comment]
You need to read the manual about strings. Unicode characters can take more than one byte, so the second index of the string might not point to the start of a character (Unicode code point). See in particular `nextind`.
