### ISSUE TITLE
[release-0.4] Pkg.publish() failing

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#15381]
```
julia> Pkg.tag("LightGraphs")
INFO: Tagging LightGraphs v0.5.1
INFO: Committing METADATA for LightGraphs

julia> Pkg.publish()
INFO: Validating METADATA
INFO: Pushing LightGraphs permanent tags: v0.5.1
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
INFO: Submitting METADATA changes
INFO: Forking JuliaLang/METADATA.jl to sbromberger
ERROR: strangely formatted HTTP response
```

**Comment by toivoh** [comment]
I got the same thing a week ago.

**Comment by sbromberger** [comment]
@toivoh did you resolve it? (How?)

**Comment by yuyichao** [comment]
Given the error message is not `Pkg.publish() has been moved to the package PkgDev.jl.` I assume this is release-0.4?

**Comment by sbromberger** [comment]
Sorry - yes - this is 0.4:

```
Julia Version 0.4.4-pre+35
Commit 1a9429e* (2016-02-12 13:21 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-svn
```

**Comment by tkelman** [comment]
https or git protocol?

**Comment by sbromberger** [comment]
@tkelman - how do I tell? `~/.julia/v0.4/METADATA/.git/config` shows `url = https://github.com/JuliaLang/METADATA.jl.git`.

**Comment by toivoh** [comment]
I resolved it by manually creating a pull request based on the changes in
the METADATA repo. So, not the ideal solution.

**Comment by tkelman** [comment]
Since the error was "strangely formatted HTTP response," this might be due to something changing on github's API. Worth trying to reconstruct the same curl command that `Pkg.publish` was attempting to do and see what the full response looks like.

**Comment by sbromberger** [comment]
@tkelman can you post the command? I'm happy to try it.

**Comment by tkelman** [comment]
Probably something like `curl -i -u $(Pkg.GitHub.token()):x-oauth-basic https://api.github.com/repos/JuliaLang/METADATA.jl/forks`

**Comment by sbromberger** [comment]
Output: https://gist.github.com/sbromberger/6c2c83f185e972f9c48d

**Comment by tkelman** [comment]
It is JSON - it then runs through https://github.com/JuliaLang/julia/blob/147d6d01d4f50c3a075abd63fd29f6ac9e88c161/base/pkg/github.jl#L40-L53

**Comment by wildart** [comment]
I think it was some kind of problem with the response. Most likely it was empty. 

@sbromberger Do you still have this problem?

So far following GitHub repo fork code works without problem, and creates fork for me.
```julia
PkgDev.GitHub.POST("repos/JuliaLang/Example.jl/forks")
```

**Comment by slundberg** [comment]
@tkelman I think this may be caused by c0d41c982d6a04a51e64f4e595de8a1d56413603 since after moving the return statement inside a do-block there is now no way for the function to not hit the error at the end. This is likely only effecting the current 0.4 release, not the dev 0.5 version.

**Comment by tkelman** [comment]
huh? return from inside a do block should work fine? if not that seems like a bigger bug

**Comment by tkelman** [comment]
Oh I think I see what you mean, the return is from the anonymous function inside the do block. Wish you had figured that out before I tagged 0.4.4. And that we had some automated tests of publish, register, etc.

**Comment by slundberg** [comment]
Sorry my first comment could have been clearer. But yes, that's what I was getting at. I agree, hopefully the new PkgDev will end up with more unit tests etc.
