### ISSUE TITLE
Operator :call Expr containing splatting is shown incorrectly

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#15387]
### Current behaviour
```
julia> :(*(a, b...))
:(a * b...)

julia> :(/(a, b...))
:(a / b...)

julia> :(*(a, b, c...))
:(a * b * c...)
```
are all incorrect. Attempting to evaluate the expressions shown will not return the same result as evaluating the expressions input, if it works at all.

```
julia> :(/(a, b, c...))
:(/(a,b,c...))
```
is correct. `/` differs from `*` because `*` is a special case for parsing.

### Desired behaviour
I believe the top three should look like this instead:
```
julia> :(*(a, b...))
:(*(a,b...))

julia> :(/(a, b...))
:(/(a,b...))

julia> :(*(a, b, c...))
:(*(a,b,c...))
```

This holds on v0.4 and v0.5, except on v0.4 the fourth example works the same as the third.

**Comment by vtjnash** [comment]
this appears to be similar to ~~https://github.com/JuliaLang/julia/issues/14481~~
