### ISSUE TITLE
Supporting dependent loop ranges in comprehensions

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#15384]
Simple example,

this works:
```jl
for i in 1:3, j in 1:i
    println(i + j)
end
```

this fails with `UndefVarError` on `i`.
```jl
[i+j for i in 1:3, j in 1:i]
```

Would it be possible to support the syntax of the second version?

**Comment by nalimilan** [comment]
I don't see how it could work given that it wouldn't return a standard (rectangular) array. Would you expect it to return a triangular matrix? But then there is no general solution for arbitrary expressions of `j`.

**Comment by KristofferC** [comment]
I forgot that comprehensions don't just return a one dimensional array. What I wanted would just be the expression in a straight list, like `[2,3,4,4,5,6]`

**Comment by JeffBezanson** [comment]
Dup of #4867
