### ISSUE TITLE
Travis CI timeout on Linux

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#15399]
The build is successful on Mac, but isn't on Linux:

https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/114546661

**Comment by jiahao** [comment]
[The error](https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/114546661#L150-L152) suggests a connection problem on the Travis worker, not an actual problem with the build.

**Comment by juliohm** [comment]
Hi Jiahao,

It seems that the error is in the extract (gzip) stage. Like if the
downloaded file with the Julia binary is compromised.

-Júlio

**Comment by jiahao** [comment]
Yes, the error is in the unzipping, but it is because the file did not finish downloading. Please restart the build and try again.

**Comment by juliohm** [comment]
The build failed again for the same reason.

-Júlio

**Comment by tkelman** [comment]
Please file issues with Travis on the Travis issues page as instructed in the log, not here.

**Comment by juliohm** [comment]
Ok Tony, will do it next time.

-Júlio
