### ISSUE TITLE
`sum(dd:Diagonal,2)` throws an error

### ISSUE THREAD

**Issue by maxlarsen** [JuliaLang/julia#15397]
On 0.4.3:
~~~
julia> dd=Diagonal(ones(5));
julia> sum(dd,2)
ERROR: ArgumentError: diagonal matrix must be square
 in reducedim_initarray at reducedim.jl:85
 in sum at reducedim.jl:264
~~~

While a specialized `sum()` method for diagonal matrices would be ideal, it is strange that it currently fails rather than fall back on the generic method `sum(full(dd),2)`.

**Comment by andreasnoack** [comment]
This is fixed on master but it will probably not be backported to 0.4 since it is not just a bug fix.

**Comment by maxlarsen** [comment]
Thank you. Does the same answer apply to `rand(5,5)\Diagonal(ones(5))` or should I open an issue for that?

**Comment by andreasnoack** [comment]
No. Please open an issue for that. It still doesn't work in master.

**Comment by maxlarsen** [comment]
Thanks done.
