### ISSUE TITLE
native finalizers not called by `finalize()`

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#15408]
In CppWrapper I use `jl_new_closure` to register a finalizer that deletes the wrapped C++ object if appropriate. I notice that in 0.5 this function was removed. Is there any way to register a finalizer from C/C++? I looked at copying https://github.com/JuliaLang/julia/blob/master/src/builtins.c#L1083-L1094 but it seems that `jl_method_cache_insert` is not part of the public interface.

BTW, the declaration of` jl_new_closure` is still in julia.h, I'm assuming that's an oversight:
https://github.com/JuliaLang/julia/blob/master/src/julia.h#L929

My current use of `jl_new_closure`is here:
https://github.com/barche/CppWrapper/blob/master/deps/src/cpp_wrapper/type_conversion.hpp#L118

**Comment by JeffBezanson** [comment]
You can call `jl_gc_add_finalizer` with a boxed `Ptr{Void}` as the function. It should be the address of a C function that takes a single pointer argument (the jl_value_t* to free).

**Comment by barche** [comment]
Thanks, I almost got it to work on 0.5. The finalizer runs with automatic gc, but when calling finalize() manually from Julia, I get the following error (`World` is the Julia wrapper for a C++ type):
`error in running finalizer: Base.MethodError(f=0x00007f505249a4b0, args=(Main.World(cpp_object=0x0000000005ac20b0),))`

Just to be sure: this is 0.5-only because now `jl_function_t` and `jl_value_t` are the same, right?

**Comment by JeffBezanson** [comment]
That looks like a bug. Should be a quick fix.

**Comment by tkelman** [comment]
test?
