### ISSUE TITLE
`a \ b::Diagonal`  throws an error

### ISSUE THREAD

**Issue by maxlarsen** [JuliaLang/julia#15401]
On 0.4.3 and master:
~~~
julia> rand(5,5)\Diagonal(ones(5))
ERROR: MethodError: `A_ldiv_B!` has no method matching 
A_ldiv_B!(::Base.LinAlg.LU{Float64,Array{Float64,2}}, ::Diagonal{Float64})
~~~
I am not sure if a specialized method would make sense but in any case falling back on `a\full(b)` would  seem reasonable.

**Comment by andreasnoack** [comment]
Right now, we use `copy_oftype` to get the right element type in `\`, but it doesn't consider the posibilty that the array doesn't allow storing the result. We'd need something like `copy_oftype_with_array_that_allows_storing`.

**Comment by kshyatt** [comment]
This is still not working. I think this might be an issue for other special types too, right? (What if I `A \ B::Bidiagonal`?)
