### ISSUE TITLE
Sometimes fetching a Future more than once causes Julia to hang

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#15406]
If it is not allowed with `Future`s it would be great with an error instead of just hanging. Furthermore, it is not possible to interrupt Julia with ctrl+c. It is possibly a separate issue, though. The following reproduces the error.
```jl
julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> v = remotecall_wait(() -> 2, 2)
Future(2,1,3,Nullable{Any}())

julia> fetch(v)
2

julia> remotecall_wait(t -> fetch(t), 2, v)
```
cc: @amitmurthy

**Comment by amitmurthy** [comment]
This is a bug. Once fetched the value should be cached locally. Will fix.

**Comment by andreasnoack** [comment]
Thanks for fixing this.
