### ISSUE TITLE
support for non-markdown docstrings is broken?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#15424]
One of the original key points of the docsystem design was that `@doc` could use any Julia object as a docstring, and `writemime` would be used to convert that object to different formats as needed.  The default would be Markdown objects, but other objects would also be supported.

This seems to have been broken in a recent Julia 0.5 commit, causing stevengj/PyPlot.jl#198 because PyPlot uses "lazy" documentation objects that fetch docstrings from Python only when needed in order to speed up `using PyPlot`.

For example, `@doc 15 f(x) = 2` used to work in Julia 0.4, associating `15` as the documentation object for `f`, but it now gives:
```
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Base.Markdown.MD
This may have arisen from a call to the constructor Base.Markdown.MD(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, ::T)
  (::Type{BoundsError})(::ANY)
  (::Type{BoundsError})(::ANY, ::ANY)
  ...
 in convert(::Type{Nullable{Base.Markdown.MD}}, ::Nullable{Int64}) at ./nullable.jl:32
 in Base.Docs.DocStr(::Int64, ::Dict{Symbol,Any}) at ./docs/Docs.jl:134
 in eval(::Module, ::Any) at ./boot.jl:267
``

**Comment by MichaelHatherly** [comment]
Sorry about that @stevengj, will fix asap.

**Comment by stevengj** [comment]
Thanks for looking into it!
