### ISSUE TITLE
Julia 0.4.2: Sum wrong 

### ISSUE THREAD

**Issue by thwriedt** [JuliaLang/julia#15422]
julia> 12.58+2.59+15.98+3.69+9.48+4.95
49.2699999999999996
What is wrong hier the sum is 49.27

**Comment by johnmyleswhite** [comment]
This is standard behavior for floating point numbers when you print them in a way (as we do) that reproduces their binary value exactly. Definitely not a bug.

**Comment by StefanKarpinski** [comment]
http://stackoverflow.com/questions/588004/is-floating-point-math-broken
