### ISSUE TITLE
Contributing.md: Style Guide for macros in C

### ISSUE THREAD

**Issue by thepulkitagarwal** [JuliaLang/julia#15438]
A line could be added in [Contributing.md](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#general-formatting-guidelines-for-c-code-contributions) about indenting `#if` and `#ifdef` macros.
Something like:

```
No indentation for macros like #if and #ifdef
```

It isn't really necessary, and maybe is obvious from context, but it could be added for the sake of completeness.

**Comment by nalimilan** [comment]
Could you make a pull request for this? It would be nice if you could also mention that the function signature shouldn't be followed by an empty line (neither in Julia nor in C).

**Comment by thepulkitagarwal** [comment]
I made a pull request.
