### ISSUE TITLE
Do Julia accept template<int n> like CPP?

### ISSUE THREAD

**Issue by zhujinxuan** [JuliaLang/julia#15445]
Recently I am writing a self-use package for calculating space differiente.  The package accept 1-st order differiente and 2-nd order differiente but throw error when calculating higher oders.  

I was thinking about something like types like eval(SpaceDiff{1}, arg...) and eval(SpaceDiff{2}...) rather than juist 1/2, as it can throw an error in a separated defination.     

But I did not see anything similar in the document.  Is there a similar way to specify types or methods by an actual int?

Thank you.

**Comment by johnmyleswhite** [comment]
This question should probably be submitted to julia-users. We don't answer usage questions on GitHub to keep the level of e-mail manageable.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/9580
