### ISSUE TITLE
emacs mode no longer ignores keywords in comments

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#15461]
If I type

```
# if
<TAB>
```

the second line gets indented. This is emacs 23.4.1. This was caused by c8da4fbf74952593a33c74874d466a472aa8de47.

**Comment by JeffBezanson** [comment]
cc @justbur

**Comment by justbur** [comment]
Sorry for the trouble, but I can't reproduce this on my machine.

Does `M-: (forward-sexp -1)` put the point on the `if`? It should jump over comments, but it's possible this changed between your version of emacs and mine.

**Comment by JeffBezanson** [comment]
Yes, it puts the point on the `if`. Sounds like your diagnosis is right. What version of emacs are you on?

**Comment by justbur** [comment]
A recent build of emacs 25. Can you try setting `parse-sexp-ignore-comments` to `t`? Maybe it's as simple as setting that variable? I don't have it set, but maybe it will make a difference for you. 

If that doesn't work, I can add a workaround for your case.

**Comment by JeffBezanson** [comment]
Wonderful; setting that variable fixes it! Thanks.

**Comment by justbur** [comment]
@JeffBezanson I actually just tested the performance implications of the particular change that caused you problems, and that one didn't seem terribly important, so I made a PR to revert it if you want to.

**Comment by JeffBezanson** [comment]
Ok. I'll leave it to you whether it's better to revert that part or change the variable in julia-mode.

**Comment by justbur** [comment]
I'd revert it I think. It was an extra check that shouldn't have been necessary, but it turned out to affect you. Besides there don't seem to be big gains from removing it in the tests I just ran.
