### ISSUE TITLE
“Any subtype of the given abstract type” as type parameter is not expressible directly

### ISSUE THREAD

**Issue by ul** [JuliaLang/julia#15469]
If I have `abstract Foo` and `type Bar<:Foo ... end`, `type Baz<:Foo ... end`, how should I denote a `Vector` accepting only any _subtypes themselves_ (not instances) of `Foo` type?

This trick works:

```
typealias FooType{T<:Foo} Type{T}
v = Vector{FooType}
push!(v, Bar)
push!(v, Baz)
push!(v, Real) # throws an error as expected
```

But it would be nice to express that in-place, like `Vector{Type{T<:Component}{T}}` (not sure about concrete syntax, but you've got an idea)

**Comment by toivoh** [comment]
Seems like `UnionAll` in #8974.

**Comment by ul** [comment]
Yes, something similar. Should I close the issue as being a duplicate one?

**Comment by JeffBezanson** [comment]
Yes, this is a duplicate.
