### ISSUE TITLE
keyword args + default args = type instability

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#15468]
I'm not sure if this is a dup of some of the more general keyword argument performance issues, so feel free to insta-close if so.

It seems there's an interaction between positional arguments with default values and keyword arguments. For instance, without a keyword arg, everything's fine with or without giving the optional arg:
```julia
julia> foo(a, b=1) = a+b
foo (generic function with 2 methods)

julia> code_warntype(foo, (Int, Int))
Variables:
  a::Int64
  b::Int64

Body:
  begin  # none, line 1:
      return (Base.box)(Base.Int,(Base.add_int)(a::Int64,b::Int64))
  end::Int64

julia> code_warntype(foo, (Int,))
Variables:
  a::Int64

Body:
  begin  # none, line 1:
      return (Base.box)(Base.Int,(Base.add_int)(a::Int64,1))
  end::Int64
```

If I include a keyword argument though, I get type instability:
```julia
julia> bar(a, b=1; kwarg=42) = a + b + kwarg
bar (generic function with 2 methods)

julia> code_warntype(bar, (Int, Int))
Variables:
  a::Int64
  b::Int64
  ####xs#7097#7098::Tuple{}

Body:
  begin
      $(Expr(:line, 1, :none, symbol("")))
      return (Base.box)(Base.Int,(Base.add_int)((Base.box)(Base.Int,(Base.add_int)(a::Int64,b::Int64)),42))
  end::Int64

julia> code_warntype(bar, (Int,))
Variables:
  a::Int64

Body:
  begin
      $(Expr(:line, 1, :none, symbol("")))
      GenSym(8) = (top(ccall))(:jl_alloc_array_1d,(top(apply_type))(Base.Array,Any,1)::Type{Array{Any,1}},(top(svec))(Base.Any,Base.Int)::SimpleVector,Array{Any,1},0,0,0)::Array{Any,1}
      GenSym(9) = GenSym(8)
      return (Main.__bar#0__)(GenSym(9),a::Int64)::Any
  end::Any
```

Now the 1-argument version returns `Any`. Based on @simonster's comment [here](https://github.com/JuliaLang/julia/issues/10443#issuecomment-77894578), I think the problem is that the 1-argument version basically becomes `bar(a; kwarg=42) = bar(a, 1; kwarg=kwarg)`, which triggers the creation of the `Any` array for keyword argument parsing.

**Comment by JeffBezanson** [comment]
I think the lowering can be changed to be more efficient here, and possibly also generate less code while we're at it.
