### ISSUE TITLE
[Docs] Wrong info in Mathematical Operations Division Functions

### ISSUE THREAD

**Issue by thepulkitagarwal** [JuliaLang/julia#15470]
In both [latest](http://docs.julialang.org/en/latest/manual/mathematical-operations/#division-functions) and [release-0.4](http://docs.julialang.org/en/release-0.4/manual/mathematical-operations/#division-functions), for `lcm(x, y...)`, this is stated: `least common multiple of x, y,...; sign matches x`

But, on doing the following:

``` julia
julia> lcm(2, 3)
6

julia> lcm(2, -3)
6

julia> lcm(-2, -3)
6

julia> lcm(-2, 3)
6
```

All are positive, so not all match the sign of x. The same goes for `gcd(x, y...)`.

**Comment by kvmanohar22** [comment]
The documentation for `release-0.5` [here](http://docs.julialang.org/en/release-0.5/manual/mathematical-operations/#division-functions) is corrected and now it doesn't include the statement  `sign matches x` for both `gcd` and `lcm`. I think this issue can be closed now.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/15770 fixed the docs. `intfuncs.jl` has tests though it doesn't look like it currently has a test for the sign combinations in `lcm(-2, 3)`
