### ISSUE TITLE
Metaprogramming inconsistency

### ISSUE THREAD

**Issue by iceblue25** [JuliaLang/julia#15539]
I have a variable which contains

MyVariable = parse("using Amodule;function X(A) blah;end")

and parses to :
:($(Expr(:toplevel, :(using Amodule), :(function X(A) 
   blah 
end))))
the macro 

macro Amacro()
  MyVariable
end

returns

\#SomeNumber\#X (generic function with 1 method)

however eval(MyVariable)
returns X (generic function with 1 method)  which is different scope?

if I define the MyVariable = parse("function X(A) blah;end")

then the macro and eval match. Shouldnt the the eval and macro always match? If not what is the problem?

Thanks,
I

**Comment by vtjnash** [comment]
no, see chapter on macro hygiene

**Comment by tomaklutfu** [comment]
Check out http://docs.julialang.org/en/release-0.4/manual/metaprogramming/#hygiene  but I am not sure it should apply to function names. Maybe better ask in julia-users google group first.

**Comment by iceblue25** [comment]
@vtjnash I dont think the chapter on macro hygiene addresses my issue.

From my understanding the chapter differentiates between scoping of macro declarations.

Howeever, in this case 

1) MyVariable = parse("using Amodule;function X(A) blah;end")


and 

2) MyVariable = parse("function X(A) blah;end")

with macro 

macro Amacro()
  MyVariable
end

resolve into two different cases
1) X is not global scope
2) X is global scope

according to hygiene chapter both should not be global scope.

**Comment by tomaklutfu** [comment]
http://docs.julialang.org/en/release-0.4/stdlib/base/?highlight=esc#Base.esc and last example in hygiene chapter is your answer. Without esc around variables names, it will generate gensym for X in both case with macro. On the other hand, if you directly eval MyVariable it won't.
