### ISSUE TITLE
ishermitian() for Hermitian type instance should perform better, isn't it?

### ISSUE THREAD

**Issue by IagobaApellaniz** [JuliaLang/julia#15540]
Hey, 

Heve you notice that `ishermitian(h)` performs the same way when `h` is a matrix of any form and when `h` is of the type `Hermitian`.

Shouldn't take advantage of knowing the type of the argument?

**Comment by KristofferC** [comment]
This seems reasonable. Would make a nice introductory PR. Maybe you could take a stab at it?

**Comment by IagobaApellaniz** [comment]
What confuses me was the `@time` macro. 
```
a = rand(100,100)
h = a + a'
h2 = Hermitian(a)
```
Now I explain the situation
```
julia> @time ishermitian(a)
  0.000008 seconds (4 allocations: 160 bytes)
false
julia> @time ishermitian(h)
  0.014787 seconds (4 allocations: 160 bytes)
true
julia> @time ishermitian(h2)
  0.000012 seconds (4 allocations: 160 bytes)
true
```

All of them they have the same allocations and the negative result coming from `a` performs well because ones it finds a negative pair on the of diagonal it stops, no mater the size of the matrix.

On the other hand I don't see why the allocations of all the different methods are the same. o_O.

I'll keep investigating this. The `@time` macro is a bit confusing here.

**Comment by KristofferC** [comment]
Well, it seems that `ishermitian` is already special cased for `Hermitian` matrices: https://github.com/JuliaLang/julia/blob/fdbcdf78bf0106e609a8d83b9e896d2d11bae594/base/linalg/symmetric.jl#L59

Why did you think it wasn't? The allocations from time is because you run things in global scope.

**Comment by IagobaApellaniz** [comment]
Definitely, it is not a performance issue. But, I had the idea to compare only allocations to judge about performance. That's not the case, one has to see `@code_llvn` as well.

Thank you for the rapid responses :-)
