### ISSUE TITLE
Large array printing in windows console cannot display \vdots

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#15544]
Windows 10,
Julia latest v0.5 windows binary, and v0.4.3,

`⋮` and `⋱` are printed as `a`.

![juliabug](https://cloud.githubusercontent.com/assets/9464825/13851114/d22c969a-ec97-11e5-9e83-be094dc93ff7.PNG)

**Comment by musmo** [comment]
It's a font issue, not Julia.

**Comment by innerlee** [comment]
true! thanks.
