### ISSUE TITLE
type cannot be constructed

### ISSUE THREAD

**Issue by ThomasBrom** [JuliaLang/julia#15554]
Hi.
 
I have an error "type cannot be constructed" when I try to run my code on a linux platform but not with Juno on Windows 10. My code is log but I have the same error with this example:

```
using DataFrames
using Distributions
using StatsBase

#### objet Individu
type Individu
  position
  locus_disp_A_M
  locus_disp_B_M
  locus_disp_A_F
  locus_disp_B_F
  locus_sexe_A
  locus_sexe_B
  qualite
end

a=0
for i=1:10000
  a=i
end
print(a)

nbrindividus = a

males = Array{Individu}(nbrindividus)
femelles = Array{Individu}(nbrindividus)
```

the exact error is:

> ERROR: type cannot be constructed
>  in include at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
>  in include_from_node1 at ./loading.jl:128
>  in process_options at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
>  in _start at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so
> while loading /home/thomas/abeilles/test_serveur.jl, in expression starting on line 26
> 

Thank's for your help.

**Comment by StefanKarpinski** [comment]
Hello, @ThomasBrom. Please use the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list for usage questions. The GitHub issue tracker is for bugs and feature proposals.

**Comment by StefanKarpinski** [comment]
In this case, your code will not work on any platform: you must pass as many arguments to the default constructor of you type as it has fields.

**Comment by tkelman** [comment]
More likely this is a difference in Julia version. 0.3 didn't support call overloading.
