### ISSUE TITLE
DomainError message is not right

### ISSUE THREAD

**Issue by Jeffrey-Sarnoff** [JuliaLang/julia#15563]
It always shows: ERROR: DomainError:SYSTEM: show(lasterr) caused an error

julia> sqrt(-4)
ERROR: DomainError:SYSTEM: show(lasterr) caused an error

function test()
   throw(DomainError())
end
test
ERROR: DomainError:SYSTEM: show(lasterr) caused an error

**Comment by Jeffrey-Sarnoff** [comment]
omitted version: v"0.5.0-dev+2440"

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14985. Already fixed.
