### ISSUE TITLE
`@async` / let block scope issue

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#15576]
the `@async` block is creating a new variable instead of capturing the intended one from the let block (due to the presence of a global of the same name)

``` julia
julia> t = 3
3

julia> let t
           c = Condition()
           task = @async begin
               notify(c)
               t = Timer(0.055)
               wait(t)
           end
           wait(task)
           println(t)
       end
ERROR: UndefVarError: t not defined
 in eval(::Module, ::Any) at ./boot.jl:243
```

**Comment by amitmurthy** [comment]
Shouldn't the `let` statement be `let t=t`? With that change the above code block works fine.

**Comment by amitmurthy** [comment]
But the issue raised by you seems similar to https://github.com/JuliaLang/julia/issues/14399
