### ISSUE TITLE
Non-existent OS X version reported during 0.5 build

### ISSUE THREAD

**Issue by rprechelt** [JuliaLang/julia#15580]
I did a fresh checkout of the v0.5 master, and ran `make -j 4` on OSX 10.10.5. The build process completed but cmake weirdly reports that Julia was built for OSX 14.5, and is being linked to 10.7 (when I am in fact running 10.10.5)

    LINK usr/lib/julia/sys.dylib
    ld: warning: object file (/Users/rprechelt/julia/usr/lib/julia/sys.o) was built for 
    newer OSX version (14.5) than being linked (10.7)

`make testall` reports that all tests passed successfully, but thought this might be worth a look.

**Comment by vtjnash** [comment]
@Keno do we know the status of this bug upstream in llvm?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14182
