### ISSUE TITLE
Want to allow spaces before opening array index bracket

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15589]
I would like to format my Julia code like this, where the opening brackets align vertically:
```Julia
        h5file["$group/posx"] = p.posx[active]
        h5file["$group/posy"] = p.posy[active]
        h5file["$group/posz"] = p.posz[active]
        h5file["$group/vol"] =  p.vol [active]
        h5file["$group/mass"] = p.mass[active]
        h5file["$group/velx"] = p.velx[active]
        h5file["$group/vely"] = p.vely[active]
        h5file["$group/velz"] = p.velz[active]
        h5file["$group/uint"] = p.uint[active]
```
This now leads to a warning:
```
WARNING: deprecated syntax "p.id [" at /Users/eschnett/.julia/v0.4/SPH/src/SPH.jl:389.
Use "p.id[" instead.
```
Can you remind me why the space leads to an ambiguity?

**Comment by yuyichao** [comment]
```
julia> [[1] [1]]
1x2 Array{Int64,2}:
 1  1

julia> [1] [1]

WARNING: deprecated syntax "(vect 1) [".
Use "(vect 1)[" instead.
1
```

**Comment by eschnett** [comment]
If I expand your shorthand, I get:
- There is a syntax to create multi-dimensional arrays, which uses white space to separate elements
- It is possible to create an array, and index into it in the same expression, e.g. `[1,2,3][2]`
- If you write an expression that contains white space, it has a different meaning inside and outside of square brackets
- That's no good, hence the deprecation

However, I didn't write `] [`, I wrote `id [`. The special syntax for constructing 2d arrays only works for brackets, so there's no ambiguity in my case.

**Comment by yuyichao** [comment]
It has nothing to do with special syntax. It's just normal hcat and it is the same if you assign the array to a variable.

**Comment by yuyichao** [comment]
It has nothing to do with special syntax. It's just normal hcat and it is the same if you assign the array to a variable.

**Comment by eschnett** [comment]
@yuyichao I don't understand your comment. What is "normal hcat" in my example? Are you referring to the `[[1] [1]]` syntax for hcat? Then why do you say this is not a special syntax for hcat? What does assignment have to do with it?

**Comment by JeffBezanson** [comment]
This was agreed on in #7232. It seems odd to me to disallow `f (x)`, but allow `f [x]`.

@yuyichao 's example could be rewritten as `[a [i]]`.

**Comment by eschnett** [comment]
@JeffBezanson Thanks! The pointer to macro calls is helpful.

(The hcat argument is bogus, since e.g. `1 +1` also has a different meaning inside and out of brackets, and no one suggests deprecating spaces before `+`.)
