### ISSUE TITLE
`ERROR: syntax: malformed expression` in parsing `0x`

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#15597]
Hi, 

Not sure this can be considered as a bug or what, feel free to close it. Here is a demo:

```julia
julia> x = 32
32
julia> 2x
64
julia> 1x
32
julia> 0x
ERROR: syntax: malformed expression
julia> typeof(0x00)
UInt8
```

I understand why the syntax error is given, but I feel one should be able to write `0x` to mean `0*x` as easily as with other numbers.

**Comment by eschnett** [comment]
`0x` is a prefix that introduces hexadecimal numbers; `0b` introduces
binary numbers: `0xff` = 255, `0b10` = 2.

Thus `0x` is a parsing error. `0a` does what you think it should, `0*a`.

Note there's a similar problem with `e`: `4e` = `4*e`, `4e5` = 40000. So
maybe these cases should be handled consistently, and either `4e` be
forbidden, or `0x` be allowed?

-erik

On Wed, Mar 23, 2016 at 7:05 AM, Davide Lasagna <notifications@github.com>
wrote:

> Hi,
>
> Not sure this can be considered as a bug or what, feel free to close it.
> Here is a demo:
>
> julia> x = 3232
> julia> 2x64
> julia> 1x32
> julia> 0x
> ERROR: syntax: malformed expression
> julia> typeof(0x00)
> UInt8
>
> I understand why the syntax error is given, but I feel one should be able
> to write 0x to mean 0*x as easily as with other numbers.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julia/issues/15597>
>



-- 
Erik Schnetter <schnetter@gmail.com>
http://www.perimeterinstitute.ca/personal/eschnetter/

**Comment by gasagna** [comment]
Correct me if I am wrong, but I would say that `4e` unambiguously means `4 * e`, with `e` being the Napier constant, so the current behaviour with `e` looks fine to me.

**Comment by eschnett** [comment]
Yes, I was referring to `x` and `b`. Currently, `0x` doesn't mean `0 * x`, it's instead an ill-formed expression. This could be changed.
