### ISSUE TITLE
Calling @code_native on a function in a module segfaults.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#15606]
This segfaults julia 0.5:
```jl
module Foo
    foo() = 1
end

# Note lack of parenthesis
@code_native Foo.foo
```

In 0.4.3 this gives:
```
ERROR: no method found for the specified argument types
```

**Comment by vtjnash** [comment]
it looks like the key failure here is that it tries to emit code for the builtin function `Core.getfield(?)`, which has the following AST, so it fails in `jl_new_lambda_info`:

`
(lldb) p jl_(method->ast)
Expr(:lambda)::Any
`

**Comment by rfourquet** [comment]
Is it the same problem as the segfault in `@code_native applicable(typemax, Int)` ?

**Comment by yuyichao** [comment]
Yes, `applicable` is also a builtin.

**Comment by mauro3** [comment]
Another one:
```
    _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-pre+5609 (2016-07-22 07:00 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 21f28c9* (0 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> first(take(1:Inf,2))

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
jl_f_tuple at /home/mauro/julia/julialang_upstream/src/builtins.c:648
eval_user_input at ./REPL.jl:74
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:177 [inlined]
jl_apply_generic at /home/mauro/julia/julialang_upstream/src/gf.c:2034
macro expansion at ./REPL.jl:92 [inlined]
#3 at ./event.jl:46
jl_call_method_internal at /home/mauro/julia/julialang_upstream/src/julia_internal.h:177 [inlined]
jl_apply_generic at /home/mauro/julia/julialang_upstream/src/gf.c:2034
jl_apply at /home/mauro/julia/julialang_upstream/src/julia.h:1394 [inlined]
start_task at /home/mauro/julia/julialang_upstream/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 1621003 (Pool: 1620110; Big: 893); GC: 0
zsh: segmentation fault (core dumped)  julia5
```

**Comment by mauro3** [comment]
I'm on a roll! This segfaults too `f(aa) = (a,b=aa.a,aa.b; a+b)` as does this mal-formed expression `function f(aa)a,b=aa.a,aa.b; a+b)`.

**Comment by yuyichao** [comment]
Those are unrelated.

**Comment by mauro3** [comment]
You're sure? The backtrack is exactly the same though (modulo different allocation numbers).  Should I open another issue?

**Comment by yuyichao** [comment]
> You're sure?

Yes.

> Should I open another issue?

No, https://github.com/JuliaLang/julia/issues/17548

**Comment by mauro3** [comment]
Thanks.  No wonder it was so easy to find other examples...

**Comment by yuyichao** [comment]
> The backtrack is exactly the same though (modulo different allocation numbers)

Also note that both the backtrace and the allocation number are useless in terms of directly identify the cause of the failure. They are only useful when debugging the issue.
