### ISSUE TITLE
REPL not showing line number in error messages?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#15618]
```
julia> versioninfo()
Julia Version 0.4.6-pre+4
Commit 03c072d (2016-03-19 15:00 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-svn
```

```
using IndicatorGraphs   # a non-published module

julia> i = IndicatorGraph(1)
julia> j = IndicatorGraph(2)

julia> merge(i,j,0.0)   # I've imported Base.merge and exported merge
ERROR: type Array has no field get  # this particular error is in line 65 of my module code
```

It's been a while since I dove deep into Julia (work obligations) - but I recall getting line info on errors in the REPL. Did something change?

**Comment by vtjnash** [comment]
can you share the type signature of `merge`? i'm wondering if (for example) it is a small kwargs function...

**Comment by sbromberger** [comment]
`function merge(g1::IndicatorGraph, g2::IndicatorGraph, p::Float64, rewrite=true, interconnect=true`

However - this appears to be happening in all modules, and it was happening before I added the `rewrite` and `interconnect` args. 

For example, before I merged https://github.com/JuliaGraphs/LightGraphs.jl/pull/318, I was getting an error in
```
using LightGraphs
g = Graph(0);

collect(edges(g))   # this gave an array bounds error.
```

without a corresponding line number.

**Comment by tkelman** [comment]
Why are you using LLVM SVN on release-0.4?

**Comment by sbromberger** [comment]
It's probably left over from when I was trying to get Gallium working.

**Comment by sbromberger** [comment]
bump - any suggestions?

**Comment by tkelman** [comment]
> (Should I stop using LLVM SVN?)

Unless you have a really strong need to, yes. Gallium works on the default build configuration of master but not release-0.4.
