### ISSUE TITLE
fix jl_get_section_start introduced by #15616

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#15617]
the `objfilemap` test should be an exact test, rather than a guess (per the comment in the code). see the implementation of `insysimage` for an example of the exact test.

**Comment by Keno** [comment]
The correct way to get at the size of the mapped image is to look at the program header as i recently learned.

**Comment by vtjnash** [comment]
true, although also overkill in this case since we can query dyld for the base address and use `==`

**Comment by Keno** [comment]
Sounds expensive

**Comment by gbaraldi** [comment]
@vtjnash it seems this got fixed and the function doesn't seem to exist anymore?
