### ISSUE TITLE
6x slowdown in startup of module tests

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/julia#15615]
There has been an approximately 6x slowdown in the time it takes the test code in our current Julia project to start up after our module has loaded. The time has gone from 15s to 90s.

I spent a lot of time git-bisecting the Julia repository to find where the most significant performance regressions occurred. Rather than just present those commits I decided to present all my data. The points at which I have left spaces in the table should correspond to the precise commits where big regressions have occurred.

41fb1ba good 15s
79a0d7b good
5ea20fc good
275c7e8 good
bea07fc good
c5704ed good
0318444 good

6396218 bad1
3b7f18a bad1
63daf4f bad1
1bfabbb bad1
179a439 bad1
0b6cab6 bad1
d8ec4a7 bad1
064b03c bad1
53b02a6 bad1
ca6f253 bad1 42s

8f4238a bad2 59s
f67203c bad2 53s
af81431 bad2 58s

6382116 bad3 73s 
24276a5 bad3 74s
79b08ca bad3 73s
93cb2ae bad3 71s
5baedf4 bad3 72s
70a3120 ??   48s

8af0134 bad4 82s
def50a0 bad4 78s
039f57b bad4 78s
597dc7b bad4 78s
adc1ed8 bad4 78s
fc469b6 bad4 78s
ebf6c64 bad5 82s

c3039d4 bad6 87s
64dbecf bad6 89s
86e435c bad6 87s
4fba664 bad6 87s
a226803 bad6 85s
be9f208 bad6 87s
master  bad6 90s (today)

Limitations:
- In the last two groups of commits it is hard to tell precisely where the bad commits are. For all I know things are just slowing down as Julia gets larger and the code gets rearranged in memory.
- There was at least one point in the 72s range where I had a commit that took only 36s. But after that no Julia commit would build even after doing make clean. I checked git status and nothing looked out of place. Nonetheless I discarded this data point as likely corrupt (and git cloned Julia again).
- There was a commit 8 days ago where we had reached 120s. But this data is not included as we used a custom Make.user file in order to make use of Cxx. The data above is with no Make.user file.

**Comment by JeffBezanson** [comment]
Thanks for the detailed investigation. Is there any way I can reproduce the behavior?

**Comment by wbhart** [comment]
The only way I have is to Pkg.add("Nemo"); Pkg.build("Nemo") and
Pkg.test("Nemo").

The timings I've given are for a 3.1GHz AMD piledriver running Ubuntu 14.04.

The timings are taken from the point where it says welcome to Nemo until
the appearance of the first test.

**Comment by JeffBezanson** [comment]
Great, that's plenty to work with. The next step is probably to profile.

**Comment by wbhart** [comment]
Actually, I just realised you will need to do Pkg.clone("https://github.com/Nemocas/Nemo.jl") instead of Pkg.add("Nemo"). We switched repositories and only master has the patches that allow Nemo to work with recent Julia. Sorry about that.

Please let us know if you have any build issues. It does build on Travis, so should be ok on Linux at least.

**Comment by KristofferC** [comment]
Timings need to be redone against new julia now, timings here are too old to be relevant.
