### ISSUE TITLE
Constructor doesn't fall back to convert?

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#15611]
immutable AAA
        x::Int
    end
    Base.convert(::Type{AAA}, x::Float64) = AAA(1)
    AAA(1.1)
    # Inexact error

Seems there is another rule taking priority over the fallback.

Is this the desired behaviour? Do I have to manually build a constructor `A(x::Float64)` in this case?

**Comment by tomaklutfu** [comment]
I think this was covered as document issue a while ago. There is always one argument default constructor from Base definitions. So, you need `A(x::Float64)`.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15120
