### ISSUE TITLE
`SubString` reports out-of-bounds error for empty ranges

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15624]
I encounter this error when remaking the documentation (after adding more documentation to Base):
```
# GENSTDLIB

INFO: loading docstrings from modules.
INFO: parsing external documentation.
ERROR: LoadError: BoundsError: attempt to access "          "
  at index [15:14]
 in getindex(::SubString{ASCIIString}, ::UnitRange{Int64}) at ./abstractarray.jl:0
```

I think this is due to an error in `SubString`. This works:
```
julia> "x"[3:2]
""
```

This should have the same result, but doesn't:
```
julia> SubString("x", 1, 1)[3:2]
ERROR: BoundsError: attempt to access "x"
  at index [3:2]
 in getindex(::SubString{ASCIIString}, ::UnitRange{Int64}) at /Users/eschnett/julia05nt/lib/julia/sys-debug.dylib:-1
 in eval(::Module, ::Any) at /Users/eschnett/julia05nt/lib/julia/sys-debug.dylib:-1
```

**Comment by nalimilan** [comment]
Good catch. According to `git blame`, the method `getindex(s::AbstractString, r::UnitRange{Int64})` has been checking ranges like this forever (even when `getindex` was called `ref`). But nowadays `checkbounds` checks for `isempty(range)`, and we can call it directly, which ensures consistency. I've made a PR: https://github.com/JuliaLang/julia/pull/15625.

BTW, is it expected/desirable that `SubString("a", 1, 10)` works?

**Comment by eschnett** [comment]
`SubString("a", 1, 10)` looks strange; I would expect it to fail.

**Comment by nalimilan** [comment]
In that case, we could move the call to `checkbounds` from `getindex` to `SubString`.

**Comment by nalimilan** [comment]
@stevengj Do you have an opinion as regards checking bounds in `SubString` (see above)?

**Comment by vtjnash** [comment]
yeah, fixing that seems in line with https://github.com/JuliaLang/julia/issues/7811
