### ISSUE TITLE
Wrong documentation for documenting types

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15623]
The documentation <http://docs.julialang.org/en/latest/manual/documentation/> suggests to document types this way:
```Julia
"..."
type T end
```

This works for functions, where a line `function f end` is ignored. For types, this does not work; it leads to an error `invalid redefinition of constant T`.

**Comment by H-225** [comment]
I'd call that a bug; that syntax for documenting types should match that of everything else, and this is the best way to do it that I've seen so far.

**Comment by MichaelHatherly** [comment]
I can't reproduce this on current `master`. What versions are you both seeing this on?

The only way I can get a `invalid redefinition of constant` error is with a different definition with the same name. Redefining the same `type T end` just raises the usual warnings:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3263 (2016-03-24 19:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 77936d0 (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu

julia> "..."
       type T end
T

help?> T
search: T try Task toq toc tic tan Text Test Type type triu tril time tanh tand take

  ...

julia> "..."
       type T end
WARNING: Method definition (::Type{Main.T})() in module Main overwritten.
WARNING: replacing docs for 'T :: Union{}'.
T

julia> const S = 1
1

julia> "..."
       type S end
ERROR: invalid redefinition of constant S
 in eval(::Module, ::Any) at ./boot.jl:243
```

**Comment by eschnett** [comment]
This is on the current master.

Here is a more complete example:
```Julia
"""
    type Atomic{T}

Holds a reference to an object of type `T`, ensuring that it is only
accessed atomically, i.e. in a thread-safe manner.

Only certain "simple" types can be used atomically, namely the
bitstypes integer and float-point types. These are `Int8`...`Int128`,
`UInt8`...`UInt128`, and `Float16`...`Float64`.

Atomic operations are function calls with an `atomic_` prefix, such as
`atomic_add!`, `atomic_xchg!`, etc.
"""
type Atomic end

type Atomic{T<:AtomicTypes}
    value::T
    Atomic() = new(zero(T))
    Atomic(value) = new(value)
end
```

I now also find that I don't know how to add this to a `rst` file; writing
```rst
.. type:: Atomic
```
there doesn't seem to be replaced.

**Comment by H-225** [comment]
@MichaelHatherly I was just commenting on the issue - not that I also had the problem. However, I *can* reproduce the more complete example on current master.

@eschnett I was not aware that one was meant to be able to "predeclare" a type in that way. Presumably there isn't a test for that.

**Comment by MichaelHatherly** [comment]
That doesn't need the docstring to raise an error though:

```
julia> type Atomic end

julia> type Atomic{T<:AtomicTypes}
           value::T
           Atomic() = new(zero(T))
           Atomic(value) = new(value)
       end
ERROR: invalid redefinition of constant Atomic
 in eval(::Module, ::Any) at ./boot.jl:243
```

if I'm understanding correctly.

For the `.. type:: Atomic` we're not currently matching against `.. type::`, see https://github.com/JuliaLang/julia/blob/77936d0ebb98bf159fb2f2297943ec34edc6aac1/doc/genstdlib.jl#L6. You could probably just add `type` in that regex and then write the docstring signature as

```julia
"""
    Atomic

Holds a reference to an object of type `T`, ensuring that it is only
accessed atomically, i.e. in a thread-safe manner.
...
```

**Comment by eschnett** [comment]
No, types cannot be predeclared like this. Only functions can.

Thus the documentation should be updated, and should not give the impression that one can predeclare types. (The example for documenting functions predeclares a function, while the example for documenting types declares an empty type instead. This is confusing.)
