### ISSUE TITLE
Pkg.update() and related not working: "Connection timed out"

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#15645]
For example:

> julia> Pkg.update()
> INFO: Initializing package repository /home/[user]/.julia/v0.4
> INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
> fatal: unable to connect to github.com:
> github.com[0: 192.30.252.128]: errno=Connection timed out

But I have access to github. In fact, the following workaround:

`git config --global url."https://".insteadOf git://`

fixes the problem (see here: https://www.reddit.com/r/Julia/comments/3648ch/unable_to_use_pkgupdate_connection_timed_out/).

But that of course shouldn't be the final solution, I guess this should be functional when Julia is installed.

I am on Linux Mint 17.3, running Julia 0.4.2 (latest version on the stable release ppa)

**Comment by wildart** [comment]
This could happen when `git` or `ssh` protocols are blocked.

**Comment by mbauman** [comment]
Apparently both git and https can have firewall difficulties: https://github.com/JuliaLang/METADATA.jl/pull/3601#issuecomment-144727998.  This gets a little easier with 0.5 and `Pkg.setprotocol!`.

**Comment by cossio** [comment]
@wildart How can I check if `git` or `ssh` are blocked?

FYI, I use `ssh` to access other servers.

**Comment by MrMormon** [comment]
@cossio It sounds like you haven't had problems with `ssh` before. Try to `git clone` something without the `git config --global url."https://".insteadOf git://` workaround and you should see the same problem outside of Julia.

**Comment by cossio** [comment]
@MrMormon I confirmed my network was blocking the `git:` protocol. That was the problem.
