### ISSUE TITLE
Package addition of CHull (or adding Github packages generally).

### ISSUE THREAD

**Issue by jackChester** [JuliaLang/julia#15644]
My specific issue: I would like to add the "CHull" package (https://github.com/davidavdav/CHull.jl) but cannot install it from github. 

I first tried just Pkg.add("CHull") but this did not work; I suspect this is because CHull is not in the list of files in metadata.jl (although please correct me if I am wrong). Thus, I next tried the following Pkg.clone("...") commands (in the attached image) but no luck there. I ran Pkg.update() and repeated these steps, but still no luck. I have tried everything else I can think of without avail. 

Caveat: while I love Julia, I am not a computer scientist by trade, so layman's terms are very helpful. I appreciate the help with this.

![picture2](https://cloud.githubusercontent.com/assets/14843598/14066629/ab563ac4-f414-11e5-8e6c-496980fc8759.png)

**Comment by yuyichao** [comment]
Please use julia-users for questions. Note that there's also no image attached.
`Pkg.clone("https://github.com/davidavdav/CHull.jl"); Pkg.build("CHull")` should work. If you still have any issue with this, please ask on the mailing list.

**Comment by jackChester** [comment]
I amended to include the image now.

Also, I have posted when I thought there were genuine problems with Julia here before, but you seem to suggest I should go to the google forums. Is that the preferred venue? I don't want to post in the wrong place, and am always very appreciative of the help, so I am just trying to figure out why you recommended change-of-venue.

Thank you.

**Comment by yuyichao** [comment]
Posting at the wrong place is fine and the discussion can always be moved.

The github issue tracker is for bugs and feature requests while the mailing list is for all discussions and questions. When it is unclear whether this is a bug, it is preferred to ask on the mailing list first.

**Comment by jackChester** [comment]
Ok, great, thanks. I suspect this would be considered a bug, since I'm following the documentation exactly (either that or the "bug" is with the documentation, which is equally serious). I also tried your suggestions and those of a colleague, and variants of, and there was no resolution, but in any case your point is well taken so I've moved it over to google groups.
