### ISSUE TITLE
Documentation search: "C++"

### ISSUE THREAD

**Issue by MrMormon** [JuliaLang/julia#15646]
If this is a necessary sacrifice for using Sphinx, what should be done? Ironically, I'm not sure GitHub issues let me search for it either.

**Comment by yuyichao** [comment]
What exactly is the issue here?

**Comment by MrMormon** [comment]
I can't search "C++". I get a bunch of useless results, and the documentation is the best place, next to GitHub issues, for learning what the state of Julia is like (for my use case, finding out what the FFI can interface with).

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7134 and I dont think the doc mentioned much about c++ ffi anyway.

**Comment by MrMormon** [comment]
I wouldn't call this a dupe because it has nothing to do with readthedocs indexing. I get the exact same results searching "C++" or "C".

**Comment by vtjnash** [comment]
C++ doesn't have an FFI. If you use clang, you can search for the Cxx.jl package. Otherwise, CxxWrap.jl may be a better choice to match the compiler of the rest of the code.

**Comment by MrMormon** [comment]
@vtjnash Thanks for pointing me to CxxWrap.jl, but I didn't open this issue for help.

> documentation is the best place, next to GitHub issues, for learning what the state of Julia is like (for my use case, finding out what the FFI can interface with).

My use case is an example supporting my opinion that something should be done (low priority) to either fix Sphinx's behavior or find an alternative.

**Comment by StefanKarpinski** [comment]
We're migrating away from Sphinx but it's an rather slow process.

**Comment by MrMormon** [comment]
Great!
