### ISSUE TITLE
Automatic updating of libgit2 fails

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15642]
After a `git pull` on the master, the next `make` failed with this error:

```
# try to update the cache, if that fails, attempt to continue anyways (the ref might already be local)
cd /Users/eschnett/src/julia05/deps/srccache/libgit2.git && git fetch -q git://github.com/libgit2/libgit2.git v0.24.0:remotes/origin/v0.24.0
cd /Users/eschnett/src/julia05/deps/srccache/libgit2 && git fetch -q /Users/eschnett/src/julia05/deps/srccache/libgit2.git remotes/origin/v0.24.0:remotes/origin/v0.24.0
cd /Users/eschnett/src/julia05/deps/srccache/libgit2 && git checkout -q --detach 785d8c48ea8725691da3c50e7dae8751523d4c30
error: Your local changes to the following files would be overwritten by checkout:
	CMakeLists.txt
Please, commit your changes or stash them before you can switch branches.
Aborting
```

It seems that the auto-update mechanism for `libgit2` needs to clean the checkout directory before running git.

(I know I can just delete the directory as work-around, but this should happen automatically.)

**Comment by nalimilan** [comment]
Looks like the upstream `.gitignore` should include `CMakeLists.txt`. But I would think that since we are using an out-of-tree build, that file shouldn't be present. Not sure what's the best solution. Calling `git reset --hard` might be a bit dangerous.

**Comment by vtjnash** [comment]
the issue is more that we are manually patching libgit2 instead of using `git apply` which dirties the tree state and causes the Makefile to think the user modified the source directory

**Comment by wildart** [comment]
Because we patch CMakeLists.txt, `libigit2` local repo becomes dirty. So running `git reset --hard` is the right way to deal with it.

**Comment by tkelman** [comment]
`git apply` wouldn't help unless we were to also commit the change. We're not really gaining much from checking these out as git repositories, so we could just switch from a git external to a tarball build and this wouldn't be an issue.

**Comment by wildart** [comment]
@tkelman Is I recall, it was tarball before. Why was that changed?

**Comment by tkelman** [comment]
The argument, at least in the case of openblas, was that having the deps source as a git repository makes it easier to test and propose modifications. I was never really sold on that, and given the issues it causes with applying patches, I think we should switch the default back to using tarballs for deps that aren't under the JuliaLang org - so openblas and libgit2.

**Comment by nalimilan** [comment]
Agreed. Especially in the case of libgit2, I don't think Julia contributors send many patches upstream.

**Comment by tkelman** [comment]
We do. But having things be a git repository under deps is more trouble than it's worth. It could maybe continue to be supported as a non default option, since most people won't be making any additional modifications.

**Comment by wildart** [comment]
Agreed. We can switch back to tarballs. It is not a big deal to switch to out-of-build binary libraries during development.

**Comment by tkelman** [comment]
#15724
