### ISSUE TITLE
cumsum!/cumprod! wrong when dim>N

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#15654]
Discovered by @shashi:

```jl
julia> cumprod([2], 2)
1-element Array{Int64,1}:
 4

julia> cumprod([1 2; 3 4], 3)
2x2 Array{Int64,2}:
 1   4
 9  16
```

cc: @timholy

**Comment by spencerlyon2** [comment]
I'm close to a fix here

**Comment by timholy** [comment]
Sorry for the bug. And thanks @spencerlyon2 for tackling it.

FWIW I don't see any reason this needs to use Base.Cartesian anymore (but whatever fix arrives should be applied).

**Comment by andreasnoack** [comment]
It might be worth to consider https://github.com/JuliaLang/julia/issues/14730 as part of the fix if someone decides to rewrite the functions anyway.

**Comment by spencerlyon2** [comment]
I think the fix is a simple as adding this before any Cartesian magic happens:

```
if axis > N
    copy!(B, A)
    return B
end
```

**Comment by timholy** [comment]
That fix sounds rather sensible to me. And :+1: to #14730 as a more general approach.
