### ISSUE TITLE
Bug in comparison of `BigFloat` and rational

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#15659]
The following is reduced from an actual bug in testing my package. Confirmed on both 0.4.5 and current master:

```julia
julia> set_bigfloat_precision(53)
53

julia> big(1/3)   #  this is definitely less than a third
3.3333333333333331e-01

julia> big(1/3) < 1//3
false
```

cc @simonbyrne 

Digging down, this apparently uses the `Base.decompose` function from `hashing2.jl`, so also cc'ing @StefanKarpinski.

**Comment by JeffreySarnoff** [comment]
Assuming 1//3 really means 0.̅̅3̅̅3̅̅3̅̅   ... 
        promoting Rationals to BigFloats is never correct, and rarely right
Assuming 1//3 really means 0.3333
        promoting Floats to Rationals is never wrong, and usually correct

**Comment by dpsanders** [comment]
`1 // 3` is a Julia object that represents the *exact* rational number "one third", and must behave as such in arithmetic operations. As you point out, it should "never" be converted to a floating-point type without care.

In fact, what I was actually trying to do was be careful by doing outward rounding, as follows:
```
julia> set_bigfloat_precision(53)
53

julia> x = 1 // 3   # exact "one third"

julia> BigFloat(x, RoundDown), BigFloat(x, RoundUp)
(3.3333333333333326e-01,3.3333333333333331e-01)
```
This should be *guaranteed* to provide two end-points of an interval, such that the end-points are 
exactly-representable floating-point numbers and the interval contains the true real number "one third".

The fact that the interval does *not* contain "one third" is very bad news (a bug); I traced the origin of it to the comparison from my previous message.

**Comment by mbauman** [comment]
It's unrelated to promotion.  `Base.decompose` should obey the relationship:

```jl
recompose(n,p,d) = n * 2.0 ^ p / d
@assert recompose(Base.decompose(x)...) == x
```

That's not the case for non-256 bit BigFloats:

```jl
julia> setprecision(257) do
           recompose(Base.decompose(big(.5))...)
       end
4.611686018427387904000000000000000000000000000000000000000000000000000000000000e+18

julia> setprecision(256) do
           recompose(Base.decompose(big(.5))...)
       end
5.000000000000000000000000000000000000000000000000000000000000000000000000000000e-01

julia> setprecision(255) do
           recompose(Base.decompose(big(.5))...)
       end
1.00000000000000000000000000000000000000000000000000000000000000000000000000000

julia> setprecision(254) do
           recompose(Base.decompose(big(.5))...)
       end
2.00000000000000000000000000000000000000000000000000000000000000000000000000000
```

I blindly poked at the implementation looking for the off-by-one error, but I couldn't find it quickly.

**Comment by StefanKarpinski** [comment]
I regret not waiting for a better name that `decompose`... Taking a look at this.

**Comment by StefanKarpinski** [comment]
It's a bug in decompose, which is only correct when BigFloat precision is a multiple of 64.

**Comment by JeffreySarnoff** [comment]
[_any objection to fixing promotion with rationals_](https://github.com/JuliaLang/julia/issues/15659#issuecomment-202586552l)

**Comment by StefanKarpinski** [comment]
[Been there, done that](https://groups.google.com/forum/#!topic/julia-dev/2JcZdFKisis), would not repeat.

**Comment by simonbyrne** [comment]
@JeffreySarnoff Promotion rules aren't at fault here: we have specialised methods for all equality and inequality comparisons.

I'll look into this.

**Comment by StefanKarpinski** [comment]
@simonbyrne: I already have [a fix](https://github.com/JuliaLang/julia/pull/15663). (It's passing everywhere but Windows x86_64.)

**Comment by Jeffrey-Sarnoff** [comment]
@simonbyrne  thank you

**Comment by Jeffrey-Sarnoff** [comment]
@StefanKarpinski thank you

**Comment by dpsanders** [comment]
Great, thanks! Can this be backported to 0.4?

**Comment by StefanKarpinski** [comment]
Yes, it probably can and should be.

**Comment by tkelman** [comment]
backport was in #15704
