### ISSUE TITLE
Master process linking wrong libraries, but workers don't

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#15670]
This one breaks `eigs` and `svds` because the homebrew version is built with 32 bit integers. The tricky part is that we don't detect this because the tests are run as workers where the linking is correct.
```jl
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5-pre+7 (2016-03-17 05:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a5d90d8* (12 days old release-0.4)
|__/                   |  x86_64-apple-darwin15.3.0

julia> addprocs(2)
@ev2-element Array{Int64,1}:
 2
 3

julia> @everywhere println(Libdl.dlpath(:libarpack))
/Users/andreasnoack/Library/homebrew/Cellar/arpack/3.2.0/libexec/lib/libarpack.2.dylib
	From worker 3:	/Users/andreasnoack/julia/usr/lib/libarpack.2.dylib
	From worker 2:	/Users/andreasnoack/julia/usr/lib/libarpack.2.dylib
```

UPDATE:

Same thing with `libgit2`
```jl
julia> @everywhere println(Libdl.dlpath(:libgit2))
/Users/andreasnoack/Library/homebrew/Cellar/libgit2/0.23.4/lib/libgit2.0.23.4.dylib
	From worker 2:	/Users/andreasnoack/julia-dev/usr/lib/libgit2.dylib
	From worker 3:	/Users/andreasnoack/julia-dev/usr/lib/libgit2.dylib
```
which is probably causing https://github.com/JuliaLang/julia/issues/15681

**Comment by tkelman** [comment]
We shouldn't be using homebrew's arpack unless you also have everything else build for 32 bit ints

**Comment by andreasnoack** [comment]
Added the milestone since I don't think it is reasonable to ship 0.5 as long as installing a homebrew package can break the package manager.

**Comment by tkelman** [comment]
is 0.4 okay here? could you bisect with just `./julia test/runtests.jl linalg/arnoldi` or whatever triggers this?

**Comment by andreasnoack** [comment]
`0.4.5-pre+7` has the same issue.

**Comment by tkelman** [comment]
Hm. 0.3? Have we always gotten this wrong, or did we mistakenly backport whatever caused this?

**Comment by andreasnoack** [comment]
It seems to be a problem on 0.3 as well.

**Comment by andreasnoack** [comment]
`make testall1` also spawns the process so there the right library is loaded.

**Comment by tkelman** [comment]
Only if `n > 1` from my reading of `test/runtests.jl`

**Comment by andreasnoack** [comment]
Hm. You are right. However, I've run the tests with `JULIA_NUM_CORES=1` on both 0.4 and 0.5 and they don't fail so for some reason the right library is loaded. I'm not sure why. This issue is really good in avoiding being detected by tests.

**Comment by tkelman** [comment]
From discussion elsewhere, it sounds like this may be specific to running julia via the symlink? Should we warn against that on OSX then, or just not create it and recommend running via `usr/bin/julia` ?

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/pull/15756. I might have a solution.
