### ISSUE TITLE
Seg fault on `Pkg.update()`

### ISSUE THREAD

**Issue by ivirshup** [JuliaLang/julia#15681]
Running into a segfault whenever I try to update my packages on OS X. However if I build `julia-debug` it works fine. I've tried installing a newer version, `make cleanall` and rebuilding libgit2.

```
julia> versioninfo()
Julia Version 0.5.0-dev+3329
Commit a5f2c7a* (2016-03-29 22:27 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia> Pkg.update()
INFO: Updating METADATA...

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
Allocations: 6679485 (Pool: 6677929; Big: 1556); GC: 13
Segmentation fault: 11
```

Using `julia-debug`

```
julia> versioninfo()
Julia Version 0.5.0-dev+3329
Commit a5f2c7a* (2016-03-29 22:27 UTC)
DEBUG build
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating JuliaParser master...
INFO: Updating ComputeFramework master...
INFO: Updating Blink master...
INFO: Updating PlotlyJS master...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

**Comment by nalimilan** [comment]
Could run `git checkout c2c58a0b567fba7f1e4ffbaba64c2d9426afff7a`, rebuild Julia and check whether it still fails? Or can you simply confirm it used to work last week? I'm afraid I introduced this in https://github.com/JuliaLang/julia/pull/15587.

**Comment by nalimilan** [comment]
Depending on when it was introduced, could also be https://github.com/JuliaLang/julia/commit/48a8493ba767e59caecd5405b0b188b643ded476. You could also try after reverting it.

**Comment by ivirshup** [comment]
It was working last week. 

I wasn't able to build c2c58a0b5, and I get the same error with 48a8493, though I did get an extra line of output one time.

**Comment by nalimilan** [comment]
When I said "revert it", I meant call `git revert` on it. But you can as well do `git checkout fc11cf28be6d2cb5fe5b673498e44ad719be2053` (i.e. test the commit before it).

What error do you get with c2c58a0?

**Comment by ivirshup** [comment]
For c2c58a0 I was getting: 

```
...
configure: creating ./config.status
config.status: creating libuv.pc
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
make: *** [julia-deps] Error 2
```

for `make -j 4` ([gist of full session](https://gist.github.com/ivirshup/07ead2bb8c00e59824af0147bac5313f))

I'm building it again now with just `make`, and will update when it's done.

**Comment by nalimilan** [comment]
Try calling `rm /Users/isaac/github/julia/deps/srccache/libgit2/CMakeLists.txt` first.

**Comment by ivirshup** [comment]
Doing a serial build of c2c58a0 + removing CMakeLists.txt does the trick, thanks! 

This seems like more of a workaround than a fix to me, should I leave this issue up?

**Comment by nalimilan** [comment]
That wasn't supposed to be a workaround, but a debugging session. Could you also try with fc11cf28be6d2cb5fe5b673498e44ad719be2053? That will allow identifying the source of the bug.

**Comment by wildart** [comment]
@ivirshup What does `LibGit2.version()` reports?

**Comment by ivirshup** [comment]
@nalimilan Ah, you were so helpful I'd figured you were already aware of the cause! I'll try that now.

@wildart On the working build of c2c58a0 `LibGit2.version()` returns  `v"0.23.4"`.

**Comment by ivirshup** [comment]
#### Parallel build

Running the following commands
```
git checkout fc11cf2
make cleanall
make -j 6
```

Returns 

```
fatal: Couldn't find remote ref remotes/origin/v0.24.0
fatal: The remote end hung up unexpectedly
make[1]: *** [/Users/isaac/github/julia/deps/srccache/libgit2/CMakeLists.txt] Error 128
make: *** [julia-deps] Error 2
```

I keep getting this error after deleting `deps/srccache/libgit2/CMakeLists.txt` or the whole directory `deps/srccache/libgit2/`.

#### Serial build

Calling `make` immediately after a failed `make -j 6` succeeds in building Julia, but I still get that `signal (11): Segmentation fault: 11` error when I try to run `Pkg.update()`.

**Comment by wildart** [comment]
@nalimilan It looks like type conditioning for older libgit2 version (0.23.4) for DiffOptions does not work.

**Comment by wildart** [comment]
@ivirshup Try `make -C deps distclean-libgit2`

**Comment by ivirshup** [comment]
Following from having a succeeding build (fc11cf2), running `make -C deps distclean-libgit2` then `make` runs without errors. Julia still seg faults when I call `Pkg.update()`.

But I can run `make -C deps distclean-libgit2` then `make -j 6` without getting an error now? `Pkg.update()` still fails.

**Comment by nalimilan** [comment]
@ivirshup Thanks. Can you call `LibGit2.version()` and `fieldnames(LibGit2.DiffOptionsStruct())` on a build for which `Pkg.update()` segfaults?

@wildart That sounds really weird to me. The only possible explanation would be that the Julia files were compiled with 0.24, and then 0.23 would be loaded later. Did `make -C deps distclean-libgit2` fix it?

**Comment by wildart** [comment]
I thought version condition would work with either of `libgit2` binary builds.

**Comment by andreasnoack** [comment]
@nalimilan It's not your fault. See https://github.com/JuliaLang/julia/issues/15670. OS X linking on just broken right now. You can do

```jl
addprocs(1)
remotecall_fetch(2) do
    Pkg.update()
end
```
but that is probably not a long term solution.

**Comment by wildart** [comment]
Different binary versions shouldn't be a problem here. Recent update introduces backward compatibility with libgit2 version 0.23.4. Users should be able to use both 0.23.4 and 0.24.0. I wonder if precomilation of LibGit2 module does this trick.

**Comment by ivirshup** [comment]
@nalimilan 
```
julia> LibGit2.version()
v"0.23.4"

julia> fieldnames(LibGit2.DiffOptionsStruct())
13-element Array{Symbol,1}:
 :version          
 :flags            
 :ignore_submodules
 :pathspec         
 :notify_cb        
 :progress_cb      
 :payload          
 :context_lines    
 :interhunk_lines  
 :id_abbrev        
 :max_size         
 :old_prefix       
 :new_prefix  
```

I also get @andreasnoack's results with running it on other processes.

**Comment by nalimilan** [comment]
@andreasnoack So it would mean libgit2 0.23 is still installed somewhere on the system, and gets used instead of 0.24 (which was used for compilation)?

**Comment by andreasnoack** [comment]
@nalimilan Yes. Something like that.

**Comment by andreasnoack** [comment]
@ivirshup Can you check if https://github.com/JuliaLang/julia/issues/15670 fixed this?

**Comment by ivirshup** [comment]
@andreasnoack It did! Building julia and updating packages are working for me now on master.

**Comment by andreasnoack** [comment]
Great
