### ISSUE TITLE
Cannot find the toggle console in the atom

### ISSUE THREAD

**Issue by XuemeiHu** [JuliaLang/julia#15687]
I install the julia as in https://github.com/JunoLab/atom-julia-client/tree/master/manual, but I was stuck in the step :"Finally, run the Julia Client: Toggle Console command from Atom. When the console opens, type a Julia expression (e.g. 2+2) and press Enter to evaluate it."

I just cannot find the Julia Cliend: Toggle Console.
![image](https://cloud.githubusercontent.com/assets/16914649/14136868/ff18fbd6-f619-11e5-88d6-ae25b512f297.png)
![image](https://cloud.githubusercontent.com/assets/16914649/14136901/1f9030fa-f61a-11e5-92df-42d133bfe27e.png)

Can you help me with the problem?

**Comment by okvs** [comment]
This isn't a Julia issue, but a JunoLab issue, so it should be reported to one of the JunoLab repositories here: [https://github.com/JunoLab](), not sure which one, maybe [Julia Client](https://github.com/JunoLab/atom-julia-client).

BTW, I have the same problem as you. But if you select 'Open Console' instead, that seems to work. Maybe it's a documentation error.

**Comment by MikeInnes** [comment]
Yup, the correct command is "open console" – this changed recently and I've updated the docs accordingly. Thanks for reporting.
