### ISSUE TITLE
Line numbers in type fields

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15686]
If we have a type that contains a comment on the first line, the line number node will be there rather than on that of the first field. It seems to me that either that line number node should point to the location of the variable, or there should be an extra line number node for the field.
<img width="221" alt="screen shot 2016-03-30 at 2 29 24 am" src="https://cloud.githubusercontent.com/assets/1291671/14133682/61802b14-f61f-11e5-8a8e-1cb06c93d3f8.png">

**Comment by JeffBezanson** [comment]
Do you have a use for these line numbers?

**Comment by Keno** [comment]
No, I was just comparing discrepancies with JuliaParser.
