### ISSUE TITLE
Slightly confusion password question

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15697]
`Pkg.update()` on the master asks for my user name and password like this:

```
Username for 'https://github.com/PerimeterInstitute/BarrettCraneSpinNets.jl.git':
Password for 'eschnett@https://github.com/PerimeterInstitute/BarrettCraneSpinNets.jl.git':
```

The url `eschnett@https://github.com/...` is wrong; it should be `https://eschnett@github.com/...` instead. Alternatively, it could be expressed as `for user 'eschnett' at 'https://github.com/...`.

**Comment by KristofferC** [comment]
`user@host` is the common way of writing it, no? c.f ssh logins.

**Comment by eschnett** [comment]
Yes, `user@host` is common -- that's the ssh style of expressing it. But if you have a url, then it's always supposed to begin with the transport mechanism, and the user name is supposed to come directly in front of the host name -- hence `https://user@hostname/...`.

If you pass `user@https://hostname/` to git, it will complain about an unknown prototcol `user@https`. The other way, `https://user@hostname/`, works fine.

I understand that making the user name highly visible by having it in front is a good idea. But this doesn't require concatenating the two with an `@` character; we can just say `password for user 'user' at 'url'`.

**Comment by tkelman** [comment]
Is this fixed on master?

**Comment by KristofferC** [comment]
Please reopen on https://github.com/JuliaLang/Pkg.jl if this is still a problem.
