### ISSUE TITLE
Missing `copy(::MersenneTwister)`

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#15698]
On 0.4, at least.

**Comment by JeffBezanson** [comment]
How did this come up?

**Comment by JeffBezanson** [comment]
I see --- you might want a copy of the RNG state to restart generation from a certain point. That certainly makes sense.

**Comment by kswietli** [comment]
I have plans to dig around the RNG over the summer as part of my research work. If no one else wants this, I'd like a stab at it since I want to learn how the thing works anyway. Might be a few days, I'm kinda swamped with other work right now as a paper deadline approaches.

**Comment by ViralBShah** [comment]
Go for it! 

Cc @rfourquet

**Comment by rfourquet** [comment]
@kswietli sorry I ended up doing it, as I needed it.

**Comment by ivarne** [comment]
This issue will be fixed by #16919
