### ISSUE TITLE
document io and trailing args for print/ln

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#15693]
```
help?> print
search: print println print_joined print_escaped print_shortest print_unescaped print_with_color sprint

  print(x)

  Write (to the default output stream) a canonical (un-decorated) text representation of a value if
  there is one, otherwise call show. The representation used by print includes minimal formatting and
  tries to avoid Julia-specific details.

help?> println
search: println print_with_color print print_joined print_escaped print_unescaped print_shortest sprint

  println(x)

  Print (using print) x followed by a newline.
```

Doesn't mention the fairly important `io` argument or varargs versions.

**Comment by sg1101** [comment]
Hi @StefanKarpinski. I would like to try and solve this issue. I am new to open source and had not contributed yet. I can really use some guidience from you about how to proceed. Thank You :)

**Comment by StefanKarpinski** [comment]
Edit the docs to add the additional information and make a PR after reading through [CONTRIBUTING](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md).
