### ISSUE TITLE
Building Julia uses too many processes

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15716]
While installing Julia 0.4.5 on Stampede at TACC, I received this message from the system administrators:

```
You are still running too many tasks in the make, please 
STOP performing so many compile tasks at one time, you
are causing excessive load on the logins.  Thanks, TACC Admins
eschnett 18646 18633  0 12:07 pts/366  00:00:00 make -j4
eschnett 33142  9819  1 12:16 pts/366  00:00:00 make -j 16 GOTOBLAS_MAKEFILE= -C kernel TARGET_CORE=NEHALEM kernel
```

It seems that OpenBLAS builds with 16 processes (the number of cores on the login node), although I told Julia to use at most 4 processes (see the first `make` line quoted above).

Using many processes is fine when building on a laptop or private workstation, but on shared resources, one needs to be less possessive.

It seems that these lines in OpenBLAS's `getarch.c` are responsible for this:
```C
#if NO_PARALLEL_MAKE==1
    printf("MAKE += -j 1\n");
#else
#ifndef OS_WINDOWS
    printf("MAKE += -j %d\n", get_num_cores());
#endif
```

**Comment by yuyichao** [comment]
> It seems that these lines in OpenBLAS's `getarch.c` are responsible for this:

So report to OpenBLAS instead?

**Comment by eschnett** [comment]
Did that as well.

I just saw that Julia downloads the development version of OpenBLAS, so a correction should arrive quickly. I originally thought that we'd be using a particular version, which would require a patch in Julia.

**Comment by eschnett** [comment]
Correction: We're using OpenBLAS 0.2.15, so we need to update to a newer version to address this. I hope this can be backported as well.

**Comment by ViralBShah** [comment]
@xianyi
