### ISSUE TITLE
Is map(f) = f() wrong?

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#15710]
See: https://github.com/JuliaLang/julia/commit/dae8e19b0a7880f273237f1c95bc95d52fb44c43#commitcomment-16808689
... same for `pmap`: https://github.com/JuliaLang/julia/pull/15409/files/3b07d73354da3151e544d4a1ee6ae5e7dc168f4f#r58025185

**Comment by JeffBezanson** [comment]
Yes, this seems pretty useless.

**Comment by TotalVerb** [comment]
The type is wrong too. `map(f, ...)` should always return a collection of values that `f` may produce.

**Comment by samoconnor** [comment]
#15409 now removes `map(f)` and `pmap(f)`
