### ISSUE TITLE
KEEP_BODIES with OrcJIT

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15713]
`KEEP_BODIES` and `jl_function_ptr_by_llvm_name` are no-op with OrcJIT. Would be nice to make them working again since it is pretty useful for debugging...

**Comment by vtjnash** [comment]
we could keep a copy of the body in the shadow module (remove the test at https://github.com/JuliaLang/julia/blob/7b51368d95fa682052af0329cb2b03ca1409fbc7/src/jitlayers.cpp#L843-L844)
