### ISSUE TITLE
Support larger machines with OpenBLAS

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15715]
Julia's `deps/Makefile` contains these lines:

```
# On linux, try to provision for the largest possible machine currently
OPENBLAS_BUILD_OPTS += NUM_THREADS=16
```

We have a system with 28 cores, and larger systems exist. Should this limit be increased?

**Comment by yuyichao** [comment]
Maybe ref https://github.com/xianyi/OpenBLAS/issues/103

**Comment by andreasnoack** [comment]
It would be great to be able to set this with variable in `Make.user`.

**Comment by Keno** [comment]
The comment is misleading. @vtjnash explained what this number actually is in #14857

**Comment by eschnett** [comment]
@vtjnash Can you suggest a better formulation for this comment?

**Comment by ViralBShah** [comment]
The only way is to try this out, but we want a small default also for memory allocation reasons.

**Comment by ViralBShah** [comment]
Increasing this limit severely increases the amount of memory as @vtjnash mentions in https://github.com/JuliaLang/julia/issues/14857#issuecomment-177033584

Thus, it is unlikely the defaults will change unless upstream does something about it.
