### ISSUE TITLE
order of method loading/compilation is important

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#15727]
Though this is a rather pathological example it should show my concern:
```julia
same_type(a, b) = false;
same_type{T}(a::T, b::T) = true;

answer(a::Int) = same_type(a, Int64(12));

exp = quote
  same_type(a::Int64, b::Int64) = false;
end


println(answer(15));
println(same_type(Int64(12),Int64(15)));
eval(exp);
println(answer(15));
println(same_type(Int64(12),Int64(15)));
```
results in
```
true
true
true
false
```

Of course if I `eval` before calling `answer` the first time then it works as expected (even if the method `answer` was defined before defining the new case for `same_type`) resulting in
```
false
false
false
false
```

So it seems the code of a function is being frozen at the first call (because it's compiled) and won't be recompiled even if methods changed entirely. Means replacing all of the `same_type` methods won't change the `answer` method at all.
The other question coming up with this exactly same problem is, whether/why (Int64, Int64) is more special/exact than {T}(T, T). (I. e. it rather should be ambiguous)

Executed on Julia 0.5.0-dev though it won't be important because this is not an error/mistake.

**Comment by nalimilan** [comment]
Unfortunately, This is a known problem. See https://github.com/JuliaLang/julia/issues/265.

You don't even need to play with `quote` and `eval` to reproduce it: just redefine a function.
