### ISSUE TITLE
invalid character index in findfirst

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15723]
``` jl
julia> findfirst("⨳(",'(')
ERROR: UnicodeError: invalid character index
 in next(::UTF8String, ::Int64) at ./version.jl:106
 [inlined code] from ./strings/basic.jl:37
 in findnext(::UTF8String, ::Char, ::Int64) at ./array.jl:664
 in findfirst(::UTF8String, ::Char) at ./array.jl:670
 in eval(::Module, ::Any) at ./docs/bootstrap.jl:69
```

**Comment by vtjnash** [comment]
it looks like it's trying to treat the string as an array, but also assumes that arrays are indexed as `1:1:length(array)` (ref https://github.com/JuliaLang/julia/pull/15434#issuecomment-194991739)

**Comment by nalimilan** [comment]
Restricting the signature sounds like the best solution, and at some point we may want to add a specialized version for `AbstractString` to unify the API (https://github.com/JuliaLang/julia/issues/5664, https://github.com/JuliaLang/julia/issues/10593).

**Comment by nalimilan** [comment]
That said, it looks like it should be easy to generalize to any iterable and index type, returning the state from `next` as the index. Maybe we should decide that the iteration state must be usable as an index when a type supports indexing? Or create an `Indexable` trait to which this would apply?

**Comment by Keno** [comment]
Ran into this again:
```
julia> findnext("λ\n",'\n',1)
ERROR: UnicodeError: invalid character index
Stacktrace:
 [1] slow_utf8_next(::Ptr{UInt8}, ::UInt8, ::Int64, ::Int64) at ./strings/string.jl:172
 [2] next at ./strings/string.jl:204 [inlined]
 [3] getindex(::String, ::Int64) at ./strings/basic.jl:32
 [4] findnext(::String, ::Char, ::Int64) at ./array.jl:1213

julia> search("λ\n",'\n',1)
3

julia> findnext("a\n",'\n',1)
2

julia> search("a\n",'\n',1)
2
```
Putting on the 1.0 milestone since restricting the find functions after would be breaking.

**Comment by StefanKarpinski** [comment]
Would potentially be fixed by @JeffBezanson's proposal in https://github.com/JuliaLang/julia/issues/10593.
