### ISSUE TITLE
deps fail in .gitignore

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#15754]
At some point, the structure of our .gitignore changed, and now when I say `git status` I get listings like
```
        deps/SuiteSparse-4.4.2.tar.gz
        deps/SuiteSparse-4.4.2/
        deps/arpack-ng-3.1.5.tar.gz
        deps/arpack-ng-3.1.5/
        deps/arpack-ng-3.2.0.tar.gz
        deps/arpack-ng-3.2.0/
        deps/dsfmt-2.2.3.tar.gz
        deps/dsfmt-2.2.3/
        deps/dsfmt-2.2.tar.gz
        deps/dsfmt-2.2/
        deps/fftw-3.3.4-double/
        deps/fftw-3.3.4-single/
        deps/fftw-3.3.4.tar.gz
        deps/gmp-6.0.0.tar.bz2
        deps/gmp-6.0.0/
        deps/julia-env/
        deps/libgit2/
        deps/libmojibake/
        deps/libuv/
        deps/llvm-3.3.src.tar.gz
        deps/llvm-3.3/
        deps/llvm-svn/
        deps/mpfr-3.1.2.tar.bz2
        deps/mpfr-3.1.2/
        deps/openblas-v0.2.12.tar.gz
        deps/openblas-v0.2.12/
        deps/openblas-v0.2.13.tar.gz
        deps/openblas-v0.2.13/
        deps/openblas/
        deps/openlibm/
        deps/openspecfun/
        deps/patchelf-0.8.tar.gz
        deps/patchelf-0.8/
        deps/pcre2-10.20.tar.bz2
        deps/pcre2-10.20/
        deps/utf8proc/
        deps/virtualenv-1.11.6.tar.gz
        deps/virtualenv-1.11.6/
```
Moreover, this breaks tools like `git gui` which truncate the list of untracked files at 5000 (and there are almost 50k without the proper ignores).

However, I'm not submitting a patch to fix this because I worry it could affect the build, and that's not an area I know very well.

**Comment by StefanKarpinski** [comment]
@vtjnash, who I believe removed these patterns from `deps/.gitignore`.

**Comment by yuyichao** [comment]
These should be files from a really old build. You can just remove them and they shouldn't reapear.

**Comment by tkelman** [comment]
Those are all from a build of release-0.4. On master the tarballs have been moved to `deps/srccache` and the built copies to `deps/build`. I personally find it cleaner to have entirely separate clones for release-0.4 and master.

**Comment by StefanKarpinski** [comment]
That is what I do as well. Changing branches between major versions tends to confuse the Makefiles.

**Comment by vtjnash** [comment]
```
cd deps && git clean -fd -e build -e srccache . && rm -rf libuv openlibm openspecfun
```

**Comment by timholy** [comment]
They reappear when you do `git bisect`. But thanks for the command to clean, @vtjnash!
