### ISSUE TITLE
syntax for dispatch on tuple type of `...` arguments

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#15758]
Consider the following toy example:

``` julia
module Foos
type Foo{T <: Tuple} end 
_m{T}(f::Foo{T}, index::T) = 42
m{T}(f::Foo{T}, index...) = _m(f, index)
end

f1 = Foos.Foo{Tuple{Int}}()
Foos.m(f1, 9)

f2 = Foos.Foo{Tuple{Int,Symbol}}()
Foos.m(f2, 9, :a)
```

Here we dispatch on the type of elements following the first argument, and we want to match the type parameter `T`. The issue is that there is no syntax for this in Julia.

[discussion on julia-users](https://groups.google.com/d/topic/julia-users/1ial2qIipB8/discussion)
[real-world example where this came up for me](https://github.com/tpapp/DynamicTables.jl)

**Comment by JeffBezanson** [comment]
Related: #11242

**Comment by vtjnash** [comment]
Can mostly be done with Vararg now, though the general case (tuple_tail_cat) is not well-defined as a operation anyways
