### ISSUE TITLE
Inconsistency between `if` and `elseif` parsing

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15763]
This is legal syntax:
```
if
false
end
```
but this is not:
```
if
false
elseif
true
end
```
(`missing condition in elseif`). It seems like either both should be allowed or both disallowed.

**Comment by lobingera** [comment]
i got in several places the comment: Julia syntax is correct, if the parser accepts it (no, there is no formal syntax definition). So why not just accepting this?

**Comment by JeffBezanson** [comment]
The way we encode the syntax, and what we want the syntax to be, are totally separate issues. It's perfectly possible to specify an undesirable syntax in BNF.

**Comment by JeffBezanson** [comment]
I suppose we should deprecate `if<newline>`.

**Comment by StefanKarpinski** [comment]
I suspect you can just make it an error – I really doubt a lot of people are using this syntax.

**Comment by Keno** [comment]
There are definitely uses of it in packages as I had disallowed this in JuliaParser and it came up while running against all packages, so a deprecation is in order.

**Comment by PallHaraldsson** [comment]
In general, also also for this, is JuliaParser.jl thought of?
