### ISSUE TITLE
Printing of `Expr(:continue)`

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#15765]
In AWSLambda.jl there is [a macro](https://github.com/samoconnor/AWSLambda.jl/blob/master/src/AWSLambda.jl#L769) that takes a function and generates a string containing the body of the function.

It the function contains a `continue` statement, the function body string ends up containing, e.g.

```julia
        if length(r) == 0
            writecsv(out,[key,"?"])
            $(Expr(:continue))
        end
```
... where just `continue` was expected.

@toivoh: you previously helped out with the `clean_ex` function to remove line numbers. See #15299.
Any ideas on this one?

Another example
```julia
julia> ex = :(if true continue end)
:(if true # none, line 1:
        $(Expr(:continue))
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        $(Expr(:$, :(Expr(:continue))))
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        $(Expr(:$, :(Expr(:$,$(Expr(:quote, :(Expr(:continue))))))))
    end)
```

```julia
julia> ex = :(if true foo end)
:(if true # none, line 1:
        foo
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        foo
    end)

julia> ex = parse(string(ex))
:(if true # none, line 2:
        foo
    end)
```

**Comment by samoconnor** [comment]
As a work-around, I've extended `clean_ex` to handle `ex.head in [:break, :continue]`...
```julia
clean_ex(ex) = ex
function clean_ex(ex::Expr)
    args = map(clean_ex, ex.args)
    if ex.head in [:break, :continue]; return ex.head; end
    if ex.head != :block; return Expr(ex.head, args...); end

    args = collect(filter(ex->(!is_linenumber(ex)), args))
    length(args) == 1 ? args[1] : Expr(ex.head, args...)
end
is_linenumber(ex) = isa(ex, LineNumberNode) || Base.Meta.isexpr(ex, :line)
```

**Comment by toivoh** [comment]
It seems that printing of `continue` and `break` expressions was never actually implemented.
I believe it should be enough to add

    (nargs == 0 && head in (:break, :continue)) ||

as an additional condition at https://github.com/JuliaLang/julia/blob/fb8cd84542b0551866653866a4b6f4a755013854/base/show.jl#L731.

**Comment by samoconnor** [comment]
See PR #15769

**Comment by yuyichao** [comment]
Update the issue title since the `continue` expression is not meant to be the `continue` symbol.
