### ISSUE TITLE
WARNINGs when defining a new type that has been deprecated in Base

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/julia#15760]
When you define a "String" type, it throws a "WARNING: Base.String is deprecated" even though Base.String is not used.

![image](https://cloud.githubusercontent.com/assets/8954730/14253141/e3aab6c6-fabc-11e5-8df2-d0ab39532bad.png)

Reference julia-users: [WARNING: Base.String is deprecated [Help defining my own "String"]](https://groups.google.com/forum/#!topic/julia-users/utsbKPe8uzY)

**Comment by EricForgy** [comment]
This looks like a general issue with @deprecate_binding:

~~~julia
julia> module B
       type Nothing
       end
       end
B

julia> using B

julia> B.Nothing
WARNING: Base.Nothing is deprecated, use Void instead.
  likely near no file:0
B.Nothing
~~~

If you define a type that is deprecated, it will throw the warning.

**Comment by StefanKarpinski** [comment]
Bump. This is quite urgent now since it's blocking finishing the string work.

**Comment by JeffBezanson** [comment]
I have a fix; will push to master when tests pass locally.
