### ISSUE TITLE
Julia REPL is slow when pasting a large block of code. 

### ISSUE THREAD

**Issue by grinsted** [JuliaLang/julia#15787]
If i copy/paste a large block of code spanning multiple lines directly into the REPL then it is really slow. It looks like each code block is backspaced away and then completely retyped for every character in the pasted block of code. 

To illustrate: try copy/pasting this piece of code into the REPL
https://raw.githubusercontent.com/jheinen/GR.jl/master/examples/mandel.jl

**Comment by KristofferC** [comment]
This is on windows right?

**Comment by grinsted** [comment]
Yes. On Windows.

**Comment by KristofferC** [comment]
Some related discussion: https://groups.google.com/forum/#!topic/julia-users/MoNy5BLIbSs and #7267

**Comment by vtjnash** [comment]
I've found that if you shrink the window to show just one line, windows cmd.exe is able to update the screen much faster

**Comment by grinsted** [comment]
Thank you.  Additional info : it makes no difference if i use conemu or plain cmd.exe.

**Comment by vtjnash** [comment]
conemu is also backed by cmd.exe, it just hides the window and copies the text from that window, as it appears, onto the text area you can see.

**Comment by Keno** [comment]
I suppose Windows does not have bracketed paste mode. Is our heuristic to not redraw when inserting at the end not firing?

**Comment by vtjnash** [comment]
we don't have a heuristic for that, since the printing logic keeps the count of how many lines have been printed

**Comment by Keno** [comment]
I don't understand. We definitely used to have that heuristic. If the cursor is at the end of a non-full line, and we're inserting one character, there's no need to clear the screen.

**Comment by vtjnash** [comment]
true, the heuristic (in edit_insert – LineEdit.jl:449) looks like it isn't supposed to be using this information (which is likely private to refresh_multi_line – LineEdit.jl:1034)

**Comment by Keno** [comment]
Looks like somebody (probably me) just forgot that the position in the buffer is not the same as the column offset if there's multiple lines. Seems like that heuristic should be fixable.

**Comment by rennis250** [comment]
It does this on Mac in iTerm2 but not in Terminal.app.

**Comment by KristofferC** [comment]
This should be significantly improved now with #17868. The original code is pretty much instant now to paste. Please reopen if there are still problems with the Windows pasting.

**Comment by Giannettig** [comment]
![julia_slow_repl](https://user-images.githubusercontent.com/21956167/55680663-d7716500-591c-11e9-8f93-f63523d1e6a8.gif)

Getting this issue again I guess on Julia 1.1. using VSCode and WIn10

**Comment by Giannettig** [comment]
![julia_slow_repl](https://user-images.githubusercontent.com/21956167/55680700-59618e00-591d-11e9-82d9-e10befdcdcde.gif)

I believe I am getting this again on Julia 1.1.  - editor VSCode, Win10, ohMyRepl used in the example

**Comment by KristofferC** [comment]
OhMyREPL makes this worse (on Windows).

**Comment by MaximilianJHuber** [comment]
Please, reopen!

My REPL flickers heavily when I paste a large text. This is under Win10 and several Julia versions, also 1.4.0.

![capture](https://user-images.githubusercontent.com/6653641/77556863-66a9bc80-6e8f-11ea-8c09-d580194e6bab.gif)
![capture2](https://user-images.githubusercontent.com/6653641/77556879-6f9a8e00-6e8f-11ea-8d9a-15d31bb1b8f8.gif)

I [posted ](https://discourse.julialang.org/t/repl-flickers-when-pasting-large-text/36453)this issue on Discourse to no avail.

**Comment by StefanKarpinski** [comment]
Are you using OhMyREPL?

**Comment by MaximilianJHuber** [comment]
No.

**Comment by MaximilianJHuber** [comment]
I just tried it on a MacOS 10.11.6 with Julia 1.3.0 and pasting works fine. The issue seems to be on  Windows only.

**Comment by egoecho** [comment]
I suffered this problem on Emacs ansi-term for a long time.... Also, OhMyREPL makes it even worse.

**Comment by MaximilianJHuber** [comment]
On a Windows machine?

**Comment by egoecho** [comment]
No, on a macbook.

**Comment by musm** [comment]
Copy pasting is still slow, but vastly improved on v1.6

close?
