### ISSUE TITLE
`map(, ::Dict)` error in `Pkg.build`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15789]
This is kind of the opposite problem with https://github.com/JuliaLang/julia/issues/15342. On latest master, the following code that is slightly modified from `Pkg.Entry.build(::Vector)` throws an error since it want to construct a `Dict`. This causes the useless error message when the build process failed in https://ci.appveyor.com/project/StevenGJohnson/ijulia-jl/build/1.0.46/job/smsrhgui56r3w006

```jl
julia> errs = Dict()
Dict{Any,Any}()

julia> errs["1"] = "2"
"2"

julia> map(x->x[1], errs)
ERROR: MethodError: no method matching similar(::Dict{Any,Any}, ::Type{ASCIIString})
Closest candidates are:
  similar(::SubArray{T,N,P,I,L}, ::Any, ::Tuple{Vararg{Int64}})
  similar{T}(::Array{T,1}, ::Any)
  similar{T}(::Array{T,2}, ::Any)
  ...
 in _collect(::Dict{Any,Any}, ::Base.Generator{Dict{Any,Any},##1#2}, ::Base.EltypeUnknown, ::Base.HasLength) at ./array.jl:249
 [inlined code] from ./array.jl:224
 in map(::Any, ::Dict{Any,Any}) at ./abstractarray.jl:1168
 in eval(::Module, ::Any) at ./boot.jl:237
```

I opened this issue since I'm not sure which one should be fixed (the use or `map`).

**Comment by JeffBezanson** [comment]
It looks like this use case wants simply `keys(dict)`.

**Comment by yuyichao** [comment]
That's true. This case can easily be fixed. I'm more wondering about e.g. `map(x->x[1]*x[2], Dict("1"=>"2"))` and other subtle breakage caused by this change.

**Comment by JeffBezanson** [comment]
I think something that's expecting to construct an array derived from a `Dict` should not use `map`.

**Comment by yuyichao** [comment]
What to use instead? Comprehension?

**Comment by JeffBezanson** [comment]
Yes, a comprehension would be good. I'm not sure how usual it is to even define `map` on a Dict, but if it exists many would expect it to return another Dict.

**Comment by nalimilan** [comment]
> Yes, a comprehension would be good. I'm not sure how usual it is to even define map on a Dict, but if it exists many would expect it to return another Dict.

This is https://github.com/JuliaLang/julia/issues/5794.
