### ISSUE TITLE
--compile=all results in memory allocation problem on ARM

### ISSUE THREAD

**Issue by waTeim** [JuliaLang/julia#15783]
On a Rasberry Pi 3 the command 

```
julia --output-o sys-all.o --sysimage /usr/local/julia/lib/julia/sys.so --startup-file=no --startup-file=no --compile=all --eval nothing
```

does appear to function correctly but ultimately fails in the following way

```
 30658 / 30658
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Here's some output from top; this host has 1G RAM and 2G swap

```
KiB Mem:    948012 total,    58156 used,   889856 free,     4516 buffers
KiB Swap:  2199544 total,    13608 used,  2185936 free.    18276 cached Mem
```

**Comment by waTeim** [comment]
Suggestions?  requiring > 2G seems high.  IMaybe there some hidden error that only manifests as a memory error?

**Comment by vtjnash** [comment]
a general assumption of compilation is that the host machine has far greater available resources than the target machine. We're pretty wasteful while allocating llvm data, so > 2GB doesn't sound too unlikely to me

**Comment by waTeim** [comment]
The target machine has only 512 MB RAM and 0 swap (and 75 MB free disk space), 1 core and that core is much slower.  The Pi is the host machine.  I can definitely up the swap on the PI to more, but not a whole lot more. 3GB?

**Comment by waTeim** [comment]
Even after increasing the swap space to 4GB the same error resulted.  At the time of the error, only approximately 1G of RAM and (approximately) 1G of swap was being used, so maybe it's something else?  Maybe a 32-bit versus 64-bit issue?

**Comment by waTeim** [comment]
Running strace resulted in a whole lot of this:

    brk(0x49e13000)                         = 0x460e9000
    mmap2(NULL, 64135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mremap(0x7a2cf000, 32002048, 64004096, MREMAP_MAYMOVE) = -1 ENOMEM (Cannot allocate memory)
    mmap2(NULL, 64004096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mmap2(NULL, 64004096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    brk(0x49e13000)                         = 0x460e9000
    mmap2(NULL, 64135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mremap(0x7a2cf000, 32002048, 64004096, MREMAP_MAYMOVE) = -1 ENOMEM (Cannot allocate memory)
    mmap2(NULL, 64004096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mmap2(NULL, 64004096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)

Followed up with


    mprotect(0x7e22e000, 4096, PROT_READ|PROT_WRITE) = 0
    mprotect(0x7e22f000, 4096, PROT_READ|PROT_WRITE) = 0
    mprotect(0x7e230000, 4096, PROT_READ|PROT_WRITE) = 0
    mprotect(0x7e231000, 4096, PROT_READ|PROT_WRITE) = 0
    mprotect(0x7e232000, 4096, PROT_READ|PROT_WRITE) = 0
    mmap2(NULL, 16781312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mmap2(NULL, 16781312, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    brk(0x4710a000)                         = 0x460e9000
    mmap2(NULL, 16912384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    write(2, "terminate called after throwing "..., 48) = 48

Top

    KiB Mem:    948012 total,   936660 used,    11352 free,      240 buffers
    KiB Swap:  4296696 total,   750208 used,  3546488 free.     2932 cached Mem

      PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                         
      992 jeffw     20   0 2054660 885092    688 D   6.0 93.4  21:35.61 julia

**Comment by vtjnash** [comment]
perhaps your overcommit ratio is set too low?

**Comment by waTeim** [comment]
I tried various things according to [this](http://www.win.tue.nl/~aeb/linux/lk/lk-9.html#ss9.6), culminating in  the following, but now, same error every time.

    jeffw@gleek:~/src/jc-all $ cat /proc/sys/vm/overcommit_memory 
    2
    jeffw@gleek:~/src/jc-all $ cat /proc/sys/vm/overcommit_ratio 
    250

**Comment by waTeim** [comment]
Here's some perhaps useful [gdb output](https://gist.github.com/waTeim/e2e45527be57ea1405b9e2a5268fcec2).

**Comment by waTeim** [comment]
Is there maybe a halfway step to this, just compile a single thing rather than all of base, see if that works?

**Comment by vtjnash** [comment]
it looks like --compile=all currently needs about 6GB of RAM, but of course this being ARM32 it can only address about 3GB.

**Comment by waTeim** [comment]
This is ironic.  The problem that *compile=all* would help solve (limitations of a minimal system) can not be accomplished because of the limitations of a minimal system.  

There seem to be 2 possibilities.  Make *compile=all* more efficient in terms of memory usage, or allow breaking 1 giant step up into multiple smaller steps.

How difficult would it be to change Julia to rely not on only one sys.so, but rather a list of .so files?  It seems like loading incrementally is already supported, you simply have to load in the right order

As a stepping stone, since *precompile.jl* is already arranged linearly, what would happen if it were broken up into multiple precompile.jl and each one produced a different .so.
