### ISSUE TITLE
invoke with broadened type paramaters

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#15801]
ColorTypes defines parametric colors, e.g., `RGB{UFixed8}` and `Gray{Float32}`. Often when working with colors, one might want to say `convert(Gray, c)` without worrying about the element type. ColorTypes contains a traits-function, `ccolor` ("concrete color"), which performs inferrable "concretization" of the type, so that `convert(Gray, ::RGB{UFixed8}) -> Gray{UFixed8}` and `convert(Gray, ::RGB{Float64}) -> Gray{Float64}`. Naturally, if the user asks for type that's already concrete, `convert(Gray{Float32}, ::RGB{UFixed8})`, that's what s/he gets.

Now let's say I want to override [this method](https://github.com/JuliaLang/julia/blob/481a05c3bed0c3153f242f60d4364e1f39cf571f/base/bitarray.jl#L295-L302) to make sure that, when `T` is a `Colorant`, it's a concrete `Colorant`. Here's what I tried:
```jl
julia> using Colors

julia> import Base: convert

julia> S = TypeVar(:S)
S

julia> @eval function convert{T<:Colorant,n}(::Type{Array{T,n}}, x::BitArray{n})
           # Specify the type concretely, then invoke the general algorithm on
           # the concrete type
           invoke(convert, (Type{Array{$S,n}}, BitArray{n}), Array{ccolor(T,Gray{Bool}),n}, x)
       end
convert (generic function with 602 methods)

julia> b = bitrand(3,4)
3x4 BitArray{2}:
 false   true  false   true
  true   true   true  false
 false  false   true  false

julia> convert(Array{Gray}, b)
ERROR: invoke: argument type error
 in convert(::Type{Array{ColorTypes.Gray{T<:Union{AbstractFloat,Bool,FixedPointNumbers.FixedPoint{T<:Integer,f}}},N}}, ::BitArray{2}) at ./bitarray.jl:294
 in eval(::Module, ::Any) at ./boot.jl:237
```
It clearly invokes the correct method, but then I get a mismatch in the type.

Is there any reasonable solution?

**Comment by JeffBezanson** [comment]
This will require #8974. In the meantime you could try some of the workarounds for avoiding `invoke` discussed in #13123.

**Comment by timholy** [comment]
Thanks Jeff. I went with a non-exported `_convert` method as a workaround (see #15810). It is indeed much easier.
