### ISSUE TITLE
Something is borked with up arrow (prefix search?)

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#15800]
I am not sure what the exact circumstances are under which this happens, but it has happened for a while now and is getting somewhat annoying. Here is my `.julia_history`:

```
# time: 2016-04-08 03:51:20 EDT
# mode: julia
    x = CallFrameInfo.search_fde_offset(hdrref, lookupoffset)
# time: 2016-04-08 04:17:35 EDT
# mode: julia
    include(Pkg.dir("RR","scratch","count_malloc.jl"))
# time: 2016-04-08 04:22:19 EDT
# mode: help
    searchsortedlast
```

Now when I launch julia and hit up arrow I do get the help prompt with searchsortedlast as expected, but I cannot move past it.

**Comment by Keno** [comment]
This may have to do with interpreting the history entry as the start of a prefix search. A similar thing comes up when there's a multi-line history entry. I think a good policy would be to only enable prefix search if the user is currently on new-entry index rather than at a history index.

**Comment by StefanKarpinski** [comment]
I have really come to hate prefix search. I'd like to be able to turn it off entirely.

**Comment by vtjnash** [comment]
I have come to accept `C^a C^a up-arrow`

@Keno i don't follow how to reproduce this. I replaced my .julia_history with yours (switching spaces for tabs), and `up-arrow, up-arrow, up-arrow` let me walk through the entries as i would expect (not "getting stuck" unless i start editing the line)

**Comment by StefanKarpinski** [comment]
> I have come to accept `C^a C^a up-arrow` (edit: or `C^p / C^n`, if you like memorizing all the shortcuts)

😪

**Comment by blakejohnson** [comment]
> I have really come to hate prefix search. I'd like to be able to turn it off entirely.

Sorry 😞

**Comment by StefanKarpinski** [comment]
It's not your fault – a lot of people love it. I'm just not one of them. Which is why the option would be good!

**Comment by rfourquet** [comment]
I also don't follow how to reproduce this, can we close?

**Comment by ViralBShah** [comment]
FWIW,  this is what I get now
````

ERROR: Invalid history file (.julia_history) format:
An editor may have converted tabs to spaces at line 3
Stacktrace:
 [1] hist_from_file(::Base.REPL.REPLHistoryProvider, ::IOStream, ::String) at ./REPL.jl:365
 [2] #setup_interface#23(::Bool, ::Array{Dict{Any,Any},1}, ::Function, ::Base.REPL.LineEditREPL) at ./REPL.jl:771
 [3] run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:940
 [4] run_repl(::Base.REPL.LineEditREPL, ::Base.##507#508) at ./REPL.jl:180
 [5] _start() at ./client.jl:413

INFO: Disabling history file for this session.
julia> 
````

**Comment by rfourquet** [comment]
> FWIW, this is what I get now

In the history file from the OP, the spaces before a command should be replaced by 1 tab.

**Comment by rfourquet** [comment]
Closing as not reproducible, @Keno please re-open if this still happens.
