### ISSUE TITLE
installing Julia - ERROR: SystemError: opening file U:\.julia_history: No such file or directory

### ISSUE THREAD

**Issue by hililielala** [JuliaLang/julia#15829]
Hello,

I'm a new Julia's user and I heard a lot well about it.
I try to instal it in a professional computer but I have an error which I can not surpass:

```
 ERROR: SystemError: opening file U:\.julia_history: No such file or directory
 in open at iostrem.jl:90
 in setup_interface ar REPL.jl:746
 in run_frontend ar REPL.jl:858
 in run_repl at REPL.jl:167
 in _start at client.jl:420

INFO: Disabling history file for this session.
julia>
```

Does someone know how to fix it?

Thank you very much,

**Comment by tkelman** [comment]
Check your environment variables `ENV["HOME"]`, `ENV["HOMEDRIVE"]`, and `ENV["HOMEPATH"]`

**Comment by hililielala** [comment]
Hello tkelman, 
ENV["HOME"] gives an error message 
ENV["HOMEDRIVE"] giver "U:"
and
ENV["HOMEPATH"] gives "\\"

**Comment by tkelman** [comment]
As a workaround you can try setting either `ENV["HOME"]` to some full local-drive path (remember to double any backslashes, or just use forward slashes for everything), or setting `ENV["HOMEPATH"]` to something longer. It might work to set these in etc/juliarc.jl, or if that doesn't take effect early enough then you'd need to set the environment variable outside of Julia.

**Comment by hililielala** [comment]
Thank you, I'm really new on it and not well familiarised with its syntax.
So how can I set ENV["HOME"]?
I shoud do something like: julia> "HOME" = "C:\Users\yourusername"???

**Comment by tkelman** [comment]
It would be `ENV["HOME"] =  "C:\\Users\\yourusername"` - remember to double backslashes since it's the escape character (or use forward slashes). Setting this after the REPL has already started can't really make the message go away. But you might be able to add a line to the file `etc/julia/juliarc.jl` under your Julia installation and set it there. I'm not sure whether that file gets loaded early enough to fix this issue.

**Comment by timholy** [comment]
@tkelman, do you understand why this is happening? E.g., does this seem to be an unusual setup?

**Comment by lobingera** [comment]
Turn it around: There are not usual setups under windows ... and julia seems to be one of the few programs which take env(HOME) seriously...
My computer at work has different homes depending if it's connected to our company network or not. And i've seen the network connection on different letters recently. I think to have the history under an application directory would make more sense (at least have this as default).

**Comment by tkelman** [comment]
See the homedir() definition in base/path.jl, and find_hist_file() in base/repl.jl. There's even an env var JULIA_HISTORY you can set just for this file's location. I'm not sure why the error is happening, does the U drive exist?

**Comment by hililielala** [comment]
Thank you @tkelman, I think this is good now. ENV("HOME") stoped to returning an error.
But now I have a problem when I try Pkg.update()
It gives: fatal: Unable to look up github.com <port 9418> (Hôte inconnu)

This might be a restriction access made by the enterprise?

**Comment by tkelman** [comment]
Likely your firewall. You can try hitting semicolon `;` to get into shell mode then pasting
`git config --global url."https://".insteadOf git://`

**Comment by hililielala** [comment]
U exists.
But it is instaled in the C:\Users\yourusername\AppData\Local

**Comment by hililielala** [comment]
git config --global url."https://".insteadOf git:/ gives  the ERROR: syntax: extra token "config" after end of expression

**Comment by tkelman** [comment]
You weren't in shell mode. Hit semicolon first.

**Comment by hililielala** [comment]
sorry for the inattention
solving Pkg.update() gives fatal: unable to access 'HTTP://https:///github.com/JuliaLang/METADATA.jl/': Couldn't resolve host 'https'

**Comment by tkelman** [comment]
Something went wrong there. What is the content of your Git/mingw64/etc/gitconfig file?

**Comment by hililielala** [comment]
Opening it with .txt gives : 

[core]
	symlinks = false
	autocrlf = input
[color]
	diff = auto
	status = auto
	branch = auto
	interactive = true
[pack]
	packSizeLimit = 2g
[help]
	format = html
[http]
	sslCAinfo = /ssl/certs/ca-bundle.crt
[diff "astextplain"]
	textconv = astextplain
[rebase]
	autosquash = true
[core] eol = lf

**Comment by tkelman** [comment]
Hm. The url insteadOf change must have gone to a different gitconfig file then. I'm not sure where. You should try to see what happened with the config change and why you have the extra `HTTP://https:/`

**Comment by hililielala** [comment]
Hello, it was saved in another file, putting all together stops giving the error. But I still can not use .update or .add. Still the same error:  fatal: Unable to look up github.com (Hôte inconnu).

There is a manually way to add a package (without using .add)??

**Comment by StefanKarpinski** [comment]
You can clone the git repo into `~/.julia/v0.4` without the `.jl` extension.

**Comment by vtjnash** [comment]
does `open("U:\\.julia_history", "w")` work? Perhaps it's being hosted on a samba linux server configured to reject hidden files (e.g. `veto files = /.*/`)?

**Comment by mbauman** [comment]
The REPL history file is now contained in the `.julia` folder and its location is far more configurable (and essential).
