### ISSUE TITLE
Add --compilecache to repl.c on v0.4

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/julia#15823]
Would it be possible to add this line to the 0.4 release?  I am always forgetting this flag, and the first place I look is by running `julia --help`.  

https://github.com/JuliaLang/julia/blob/6b5a05eb1a029aef93f77b60bb1d745c7d6e1d8d/ui/repl.c#L62

**Comment by rsrock** [comment]
Whoops-- I should have actually tested that option on 0.4 first.  Turns out it must have arrived in 0.5?  Sorry for the noise.

**Comment by yuyichao** [comment]
I don't think this feature is backported.
