### ISSUE TITLE
Documentation: array.rst

### ISSUE THREAD

**Issue by ethomag** [JuliaLang/julia#15826]
This chapter looks strange on a few places.  I think it's because of a paragraph ending with "::" and the next paragraph is a ".. doctest::".
I believe the remedy is to replace the "::" with a single ":" in the first paragraph.
I don't have the repo forked, so I can't make a pull request (I think ?)

**Comment by nalimilan** [comment]
Thanks. Forking the repo is very easy, you can even make a PR directly using GitHub.

**Comment by timholy** [comment]
In your webbrowser, just navigate to the file and then click the little pencil icon.

**Comment by ethomag** [comment]
Thanks @timholy , just tried it.  Made the fix and proposed a pull request.

**Comment by vchuravy** [comment]
Also fixed in https://github.com/JuliaLang/julia/pull/15753/commits/55010dbc000f20e7ebabfeac2fe56f216c994d4d

but let's merge @ethomag version, since that PR will need some more review and discussions.
