### ISSUE TITLE
Define macro @display

### ISSUE THREAD

**Issue by chrisidefix** [JuliaLang/julia#15820]
If you want to get a **readable** output of large arrays in Julia it's very convenient to use the `display()` function. You could use `show()`, but you won't be able to make much sense of a 1000 x 1000 element matrix  that way. There is a macro `@show`, but there is none for the `display()` function.

It would make sense in my opinion to add a macro that could look something like this:

```
macro display(val)
    display(val);println()
end
```

**Comment by ihnorton** [comment]
See #14052 for upcoming changes to clarify the i/o situation.

> There is a macro @show, but there is none for the display() function

AFAICT, `julia> r` and `julia> display(r)` are identical on 0.4 and 0.5, so a macro would be redundant...

**Comment by chrisidefix** [comment]
that may be true when you use the julia console, but if you just execute julia code writing `r` doesn't output `display(r)`

**Comment by matthieugomez** [comment]
I think this issue should be reopened. A macro `@display` would be more useful than `@show` to print arrays within a function. See this [discourse issue](https://discourse.julialang.org/t/how-to-print-arrays-inside-functions/4091/5))

**Comment by knuesel** [comment]
I hit this while trying to show mid-cell values in a Jupyter notebook. Using `@show` produces one-line outputs, which are hard to read.

Since the fix from https://github.com/JuliaLang/julia/pull/22253 has been reverted in https://github.com/JuliaLang/julia/pull/25849 , shouldn't this issue be reopened?
