### ISSUE TITLE
Multiple methods with identical signatures

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#15834]
I was just messing around with some toy problems and discovered that you could create multiple methods with the same signature when using concrete types in parametric methods:
```julia
julia> foo(a::Int64, b::Int64) = a + b
foo (generic function with 1 method)

julia> foo{T<:Int64}(a::T, b::T) = a - b
foo (generic function with 2 methods)

julia> foo{A<:Int64,B<:Int64}(a::A, b::B) = a * b
foo (generic function with 3 methods)

julia> methods(foo)
# 3 methods for generic function "foo":
foo{T<:Int64}(a::T, b::T) at none:1
foo{A<:Int64,B<:Int64}(a::A, b::B) at none:1
foo(a::Int64, b::Int64) at none:1
```
If a parametric type variable uses a concrete type shouldn't that type replace the type variable in the signature?

**Comment by JeffBezanson** [comment]
Duplicate of #8974, and many of the issues with the "types and dispatch" tag.

**Comment by omus** [comment]
Thanks @JeffBezanson
