### ISSUE TITLE
Distribute header files for gmp?

### ISSUE THREAD

**Issue by laurentbartholdi** [JuliaLang/julia#15842]
Hi,
Following a thread on julia-users, I would very much like Julia to contain not just the libraries for gmp (libgmp.dylib or libgmp.so), but also the header files.

This is because one of the C dependencies of my package is a library that uses gmp, and it doesn't seem to make sense to compile/install gmp twice.

On the julia-0.3 bundle (/Applications/Julia-0.3.11.app/), only the libraries are shipped, at
/Applications/Julia-0.3.11.app//Contents/Resources/julia/lib/julia/libgmp.10.dylib
/Applications/Julia-0.3.11.app//Contents/Resources/julia/lib/julia/libgmp.dylib

On the julia-0.5 sources that I got from github, and which I put in /usr/local/src/julia, I find
/usr/local/src/julia/usr/lib/libgmp.10.dylib
/usr/local/src/julia/usr/lib/libgmp.dylib
/usr/local/src/julia/usr/include/gmp.h

so it seems that gmp is installed under joinpath(JULIA_HOME,".."). However, I was told that the libraries could also be at joinpath(JULIA_HOME,"..","lib64") rather than  joinpath(JULIA_HOME,"..","lib"), so a simple and clean mechanism to know which option to pass to my library (such as "--with-gmp="*joinpath(JULIA_HOME,"..")) would be welcome!

I guess my remark applies to all the libraries included in Julia: fftw, mpfr, suitesparse, colamd, which are often dependencies of C-code used by packages.

Thanks!

**Comment by nalimilan** [comment]
What we need is to add `LIBIDIR` and `INCLUDEDIR` to `base/build_h.jl`.

@laurentbartholdi If you like making a pull request, this shouldn't be too hard. Have a look at the line where `SYSCONFDIR` is used in `Makefile`, and use the same pattern for the two variables I mentioned (the small caps variables are defined in Make.inc, but you shouldn't have to tweak anything there).

**Comment by laurentbartholdi** [comment]
I can add LIBDIR=$libdir_rel, it's a bit more complicated for includedir, because no relative version exists yet, so Make.inc will have to be changed.

However, the big problem is that gmp.h is not included. When I compile julia from github sources, everything is fine, but when I look in the precompiled bundle (julia-0.4.5-osx10.7+.dmg) I see that it contains the libraries (.dylib) but not the includes. I don't see how to change that.

**Comment by nalimilan** [comment]
> I can add LIBDIR=$libdir_rel, it's a bit more complicated for includedir, because no relative version exists yet, so Make.inc will have to be changed.

You'll have to adapt code for `libdir` in Make.inc. Shouldn't be hard either.

> However, the big problem is that gmp.h is not included. When I compile julia from github sources, everything is fine, but when I look in the precompiled bundle (julia-0.4.5-osx10.7+.dmg) I see that it contains the libraries (.dylib) but not the includes. I don't see how to change that.

Right. That will require a bit more work. But first we need to ensure this wasn't done on purpose, i.e. that everybody is OK with shipping these header files.

Anyway, you can make the first part of the changes, it will be useful.

**Comment by laurentbartholdi** [comment]
I just created a PR for the above, "Added LIBDIR and INCLUDEDIR consts #16044"

**Comment by ViralBShah** [comment]
We do ship the headers now.

**Comment by StefanKarpinski** [comment]
We actually did but don't anymore 😬: https://github.com/JuliaLang/julia/issues/38781. Nevertheless, this can be closed.
