### ISSUE TITLE
Serialization errors with the type `Tuple`

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#15849]
Some of my code happended to produce a `Array{Tuple,1}` and such a thing appears to serialize/deserialize wrongly on both 0.4 and 0.5
```jl
julia> vt = Tuple[(1,)]
1-element Array{Tuple,1}:
 (1,)

julia> IOBuffer() |> t -> (serialize(t, vt); seekstart(t); deserialize(t))
1-element Array{Tuple{},1}:
 ()
```

EDIT [jwn]: min repro:
```julia
julia> z=Tuple{Vararg{Any}}
Tuple

julia> (b=IOBuffer()) |> t -> (serialize(t, z); seekstart(t); deserialize(t))
Tuple{}
```

**Comment by vtjnash** [comment]
it looks like this is a disagreement about how to serialize / deserialize the Type `Tuple` datatype for the eltype of the Array.

during serialization, it set `form == 0` and `parameters == svec()` (https://github.com/JuliaLang/julia/blob/e5b46c3f4bbcb49a1a1dd157b1d3a23b9897d827/base/serialize.jl#L414)

during deserialization, those parameters got applied to `Tuple` to make `Tuple{}` (https://github.com/JuliaLang/julia/blob/e5b46c3f4bbcb49a1a1dd157b1d3a23b9897d827/base/serialize.jl#L747-L748)

**Comment by vtjnash** [comment]
possibly related: part of the initial failure comes from `sertag` assuming that `pointer_from_objref === object_id` will filter out `Tuple`, but that's not really all that hard to break:

julia> z=Tuple{Vararg{Any}}
Tuple

julia> z === Tuple
true

julia> object_id(z)
0x272b34a749dea9d9

julia> object_id(Tuple)
0x272b34a749dea9d9

julia> pointer_from_objref(z)
Ptr{Void} @0x00000001109a4240

julia> pointer_from_objref(Tuple)
Ptr{Void} @0x0000000109ffc1f0
