### ISSUE TITLE
Precedence of transposition operator '

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15858]
Though not terrible, this is a bit unfortunate:

``` julia
julia> :(1:4')
:(1:(4)')
```

I can't find a case where one could want to create a range from a transposed last element. OTC, creating a row-matrix from a range can sometimes be useful.

Maybe we could change this? Or would it break something else?

Also, `'` isn't listed in the [table about operator precedence](http://docs.julialang.org/en/release-0.4/manual/mathematical-operations/?highlight=precedence#operator-precedence).

**Comment by stevengj** [comment]
Theoretically, this would be a breaking change, although it's hard to imagine it affecting user code.

**Comment by TotalVerb** [comment]
Currently transposition has higher precedence than multiplication and addition, and that's probably a good thing: `A + B'` should probably mean `A + (B')`, not `(A + B)'`.

But range has lower precedence than both: `1:10*10` is `1:(10*10)`. If we make this change, then we would have to break that behaviour. Especially concerning is this:

```
1:length(A)-1
```
which I think is likely quite common.

**Comment by timholy** [comment]
Seems like the easiest way to solve this is to make `4'` an error. Currently `ctranspose` is recursive (to handle arrays-of-arrays) and on numbers it computes `conj`. But perhaps we could make `ctranspose` recurse to `_ctranspose` (non-exported), and restrict `ctranspose` to `AbstractVecOrMat`.

**Comment by stevengj** [comment]
@TotalVerb, good point, we can't make `'` lower precedence than `:` without breaking the relationship with `+` (or breaking the partial ordering of precedences).

@timholy, please no.   `'` is adjoint, and making the adjoint of a number equal to its conjugate is extremely well established mathematics.  It seems crazy to break that just to give a syntax error for odd mistakes with colons.

**Comment by nalimilan** [comment]
I don't think there really a problem here. I was just wondering whether we could make this slightly more convenient without making anything more painful.

I'm inclined to close this issue. But I am right that `'` should be added to the operator precedence table? We can turn it into a docs issue.

**Comment by TotalVerb** [comment]
I think implicit multiplication (which binds quite strongly, but not as strong as exponentiation) is also missing from that table, along with probably many other common ones. All the unicode ones are missing too, but those can probably be left out.

**Comment by JeffBezanson** [comment]
This doesn't seem to be solvable with transitive operator precedence. `:` has lower precedence than `+`, but transpose has to have higher precedence than `+`. #18714 would be the change we could make here if anything.
