### ISSUE TITLE
llv3.8 support?

### ISSUE THREAD

**Issue by jiapei100** [JuliaLang/julia#15854]
Hi, all:

It looks current julia needs llvm, and the most current llvm is supported until 3.7.1 ?
I'm using llvm3.8... so... any plan to let julia be compatible with llvm3.8?

Cheers
Pei

**Comment by vtjnash** [comment]
duplicate

**Comment by jiapei100** [comment]
duplicated? But, where is the other issue? Just let me know where it is? I'd love to keep an eye on it???

Thank you ....

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/15417
