### ISSUE TITLE
Space not allowed 0.5 dev

### ISSUE THREAD

**Issue by sgt101** [JuliaLang/julia#15867]
Hi,

I pulled 3471 to try it out and noted that the syntax for calling functions now prohibits a space between the function name and the parenthesis for the parameters:

myfoo (mybar,thingy) 

used to be ok

now I must use 

myfoo(mybar,thingy)

For my small amount of code this is no problem, I just cleaned it up. But when I started precompiling packages that I depend on several failed to build. 

I don't think this is a good thing and wonder what your thinking is?

**Comment by yuyichao** [comment]
This is intentional.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/7232
