### ISSUE TITLE
Redundant vs. multiple type delcarations

### ISSUE THREAD

**Issue by didierverna** [JuliaLang/julia#15862]
Note: this is Julia 0.4.5.
```
julia> function foo()
         i::Int32 = 10
         for(i::Int32 = 1:3)
           println(i)
         end
       end
ERROR: syntax: multiple type declarations for "i"
```
In such a case, maybe a redundancy warning instead of an error would be more appropriate ?

Also, when a _different_ type declaration is given the second time, I'm wondering whether it wouldn't make more sense to create a new binding for i (as the for loop already does in some cases) instead of reporting an error.

**Comment by vtjnash** [comment]
at the syntax level, it doesn't know if the two declarations will resolve to the same type, so it must assume that they could be different

it also already handles the case where you create a different binding for `i`:
```julia
function foo()
  i::Int32 = 10
  for i::Int32 = 1:3; local i
    println(i)
  end
end
```

note that `for(i::Int32 = 1:3)` gives `ERROR: syntax: invalid iteration specification` on master

**Comment by didierverna** [comment]
I hardly see how a syntactically correct piece of code can lead to a syntax error. Maybe that's the real problem (handling this at the syntax level).

Also, you misunderstood my second point. I wasn't clear enough probably, sorry. I meant to say that:
```
julia> function foo()
         i::Int32 = 10
         for(i::Int64 = 1:3)
           println(i)
         end
       end
```
perhaps this code shouldn't lead to a "multiple type declarations" error, but instead to an implicit "local i" in the for loop. Issuing a new type declaration looks to me like a rather explicit way of requesting a new binding.
