### ISSUE TITLE
Multithreading segmentation fault

### ISSUE THREAD

**Issue by abhijithch** [JuliaLang/julia#15875]
For the example mentioned in #15874 for `nthreads()` > 30 julia segfaults. Julia version is `Version 0.5.0-dev+1918`.

**Comment by kpamnany** [comment]
On master, this occurs with 16 threads and there's this (hopefully useful) report:
```
GC error (probable corruption) :
Allocations: 252309766 (Pool: 252172502; Big: 137264); GC: 260
Array{Any, 1}[top(:_expr), :call, :size, Slot(id=4, typ=Symbol), :d]
Aborted
```
The backtrace for the segfault on commit https://github.com/JuliaLang/julia/commit/dc6b0de80550c58a2fbb7200632e3ecafaf4dca7 is:
```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
push_root at /home/kpamnany/julia/src/gc.c:1806
gc_push_root at /home/kpamnany/julia/src/gc.c:1665
push_root at /home/kpamnany/julia/src/gc.c:1891
gc_push_root at /home/kpamnany/julia/src/gc.c:1665
push_root at /home/kpamnany/julia/src/gc.c:1942
gc_push_root at /home/kpamnany/julia/src/gc.c:1665
push_root at /home/kpamnany/julia/src/gc.c:1942
gc_push_root at /home/kpamnany/julia/src/gc.c:1665
pre_mark at /home/kpamnany/julia/src/gc.c:2028
_jl_gc_collect at /home/kpamnany/julia/src/gc.c:2243
jl_gc_collect at /home/kpamnany/julia/src/gc.c:2443
__pool_alloc at /home/kpamnany/julia/src/gc.c:1217
pool_alloc at /home/kpamnany/julia/src/gc.c:1276
jl_gc_allocobj at /home/kpamnany/julia/src/gc.c:2517
_new_array_ at /home/kpamnany/julia/src/array.c:84
_new_array at /home/kpamnany/julia/src/array.c:144
jl_alloc_array_1d at /home/kpamnany/julia/src/array.c:339
call at ./essentials.jl:210
[inline] at ./dict.jl:317
ast_localvars at ./inference.jl:2287
inlineable at ./inference.jl:2476
jl_apply at /home/kpamnany/julia/src/julia.h:1393
<snipped>
```
HTH.

**Comment by ViralBShah** [comment]
There have been a bunch of updates to multi-threading. Can we see if this is addressed?

**Comment by jeff-regier** [comment]
I'm seeing a similar error with Julia version `0.5.0-dev+5539` (1 day old). This is with 16 threads.

```
signal (11): Segmentation fault
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 82
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:177 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:2027
process_options at ./client.jl:262
_start at ./client.jl:318
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:177 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:2027
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/ui/../src/julia.h:1394 [inlined]
true_main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:112
main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:232
unknown function (ip: 0xffffffffffffffff)
Allocations: 762411065 (Pool: 762124992; Big: 286073); GC: 2525

signal (11): Segmentation fault
while loading /global/homes/j/jregier/.julia/v0.5/Celeste/bin/celeste.jl, in expression starting on line 82
srun: error: nid00025: tasks 4,10: Segmentation fault
srun: Terminating job step 2760559.0
srun: error: nid00025: tasks 2,14: Segmentation fault
srun: error: nid00025: tasks 0-1,3,5-9,11-13,15: Segmentation fault
```

**Comment by ViralBShah** [comment]
Can you provide the instructions for reproducing?

**Comment by jeff-regier** [comment]
Sure, I'll post the commands I ran here, but without the account number and reservation number needed to run this job on cori.nersc.gov. (Those appear in our email thread.) The segfault appears reliably with 8 nodes and 16 threads per node. With 4 threads and just 1 node, I haven't seen the segfault happen.

```
# install celeste (and forks of some packages that don't yet support julia 0.5)
julia -e 'Pkg.clone("https://github.com/jeff-regier/Lumberjack.jl.git"); Pkg.build("Lumberjack")'
julia -e 'Pkg.clone("https://github.com/jeff-regier/FITSIO.jl.git"); Pkg.build("FITSIO")'
julia -e 'Pkg.clone("https://github.com/jeff-regier/WCS.jl.git"); Pkg.build("WCS")'
julia -e 'Pkg.clone("https://github.com/jeff-regier/Celeste.jl.git")'
julia -e 'Pkg.checkout("DocOpt")'

# stage the data
"$HOME/julia/bin/julia" "$HOME/.julia/v0.5/Celeste/bin/celeste.jl" stage-box 200 200.5 38.1 38.35

# run celeste on 8 nodes with 16 thread per node
#SBATCH --account=XXXXXX
#SBATCH --reservation=XXXXXX
#SBATCH --partition=debug
#SBATCH --nodes=8
#SBATCH --job-name=celeste
#SBATCH --time=00:30:00
export OMP_NUM_THREADS=1
export JULIA_NUM_THREADS=16
module load impi
export I_MPI_PMI_LIBRARY=/opt/slurm/default/lib/libpmi.so
export I_MPI_PIN_DOMAIN=auto
export USE_DETREE=1
srun -n 16 "$HOME/julia/bin/julia" "$HOME/.julia/v0.5/Celeste/bin/celeste.jl" infer-box 200 200.5 38.1 38.35 $SCRATCH
```

**Comment by kpamnany** [comment]
I'm not sure this is the same segfault as the OP's, but anyway.

I'm testing this also, but if you're trying to replicate, a couple of minor corrections: You don't need the reservation line. The 2nd last line should be ``export USE_DTREE=1``. Also, the last set of lines (beginning from the first SBATCH up to and including the last srun) should actually go into a SLURM script file (e.g. celeste_8.sl) which can be batched for execution via ``srun celeste_8.sl``.

**Comment by CorbinFoucart** [comment]
I am getting the same error, with a python code from which I call Julia. Making the standard call
`
# julia is a pyjulia instance of Julia()
julia.addprocs(3)
`

then I get a segfault. If I do the same call later in the code, there is no problem. The segfault is produced below.

`
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1343
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_stack at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1252
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1430
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_task at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1294
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1430
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1410
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_module at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1212
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1423
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1362
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1362
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1362
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_module at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1212
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1423
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1460
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_module at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1212
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1423
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
gc_mark_module at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1212
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1423
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1183 [inlined]
pre_mark at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1509
_jl_gc_collect at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1703 [inlined]
jl_gc_collect at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1858
jl_gc_pool_alloc at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:828
jl_gc_alloc_ at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:148 [inlined]
jl_gc_alloc at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1881
_new_array_ at /home/centos/buildbot/slave/package_tarball64/build/src/array.c:95 [inlined]
_new_array at /home/centos/buildbot/slave/package_tarball64/build/src/array.c:149 [inlined]
jl_alloc_array_1d at /home/centos/buildbot/slave/package_tarball64/build/src/array.c:346
reindex_labels! at ./inference.jl:3528
finish at ./inference.jl:1940
typeinf_frame at ./inference.jl:1849
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call at ./inference.jl:1096
unknown function (ip: 0x7fd18515d5ce)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1126
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1781
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call at ./inference.jl:1096
unknown function (ip: 0x7fd18515d5ce)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1126
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1781
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call at ./inference.jl:1096
unknown function (ip: 0x7fd18515d5ce)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1126
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1781
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1121
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_interpret at ./inference.jl:1249
unknown function (ip: 0x7fd185159c86)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1726
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call at ./inference.jl:1096
unknown function (ip: 0x7fd18515d5ce)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1126
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_interpret at ./inference.jl:1238
unknown function (ip: 0x7fd185159c86)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1726
typeinf_loop at ./inference.jl:1655
typeinf_edge at ./inference.jl:1592
unknown function (ip: 0x7fd1851631ca)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1598
unknown function (ip: 0x7fd185161a0a)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call_gf_by_type at ./inference.jl:888
unknown function (ip: 0x7fd185161406)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_call at ./inference.jl:1096
unknown function (ip: 0x7fd18515d5ce)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_eval_call at ./inference.jl:1126
abstract_eval at ./inference.jl:1147
unknown function (ip: 0x7fd18515b536)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
abstract_interpret at ./inference.jl:1238
unknown function (ip: 0x7fd185159c86)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_frame at ./inference.jl:1726
typeinf_loop at ./inference.jl:1672
unknown function (ip: 0x7fd18515960b)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_edge at ./inference.jl:1592
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
typeinf_ext at ./inference.jl:1616
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
jl_type_infer at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:210
jl_compile_for_dispatch at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1295
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:184 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
#649 at ./task.jl:360
unknown function (ip: 0x7fd1c50005af)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
start_task at /home/centos/buildbot/slave/package_tarball64/build/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 2431685 (Pool: 2430730; Big: 955); GC: 1
Segmentation fault
(venvJul2) ibfdr-compute-0-0(3D_tracer)% ERROR: write: broken pipe (EPIPE)
 in yieldto(::Task, ::ANY) at ./event.jl:136
 in wait() at ./event.jl:169
 in stream_wait(::Task) at ./stream.jl:44
 in uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:820
 in unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
 in write(::Base.PipeEndpoint, ::Array{UInt8,1}) at ./io.jl:175
 in print at ./strings/io.jl:70 [inlined]
 in start_worker(::Base.PipeEndpoint, ::String) at ./multi.jl:1539
 in process_options(::Base.JLOptions) at ./client.jl:220
 in _start() at ./client.jl:318
ERROR: write: broken pipe (EPIPE)
 in yieldto(::Task, ::ANY) at ./event.jl:136
 in wait() at ./event.jl:169
 in stream_wait(::Task) at ./stream.jl:44
 in uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:820
 in unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
 in write(::Base.PipeEndpoint, ::Array{UInt8,1}) at ./io.jl:175
 in print at ./strings/io.jl:70 [inlined]
 in start_worker(::Base.PipeEndpoint, ::String) at ./multi.jl:1539
 in process_options(::Base.JLOptions) at ./client.jl:220
 in _start() at ./client.jl:318
ERROR: write: broken pipe (EPIPE)
 in yieldto(::Task, ::ANY) at ./event.jl:136
 in wait() at ./event.jl:169
 in stream_wait(::Task) at ./stream.jl:44
 in uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:820
 in unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:830
 in write(::Base.PipeEndpoint, ::Array{UInt8,1}) at ./io.jl:175
 in print at ./strings/io.jl:70 [inlined]
 in start_worker(::Base.PipeEndpoint, ::String) at ./multi.jl:1539
 in process_options(::Base.JLOptions) at ./client.jl:220
 in _start() at ./client.jl:318
`

**Comment by yuyichao** [comment]
It's unrelated and fixed.

**Comment by CorbinFoucart** [comment]
Ok, sorry about that. Do you know what I can do to avoid this?

**Comment by yuyichao** [comment]
Nothing much. https://github.com/JuliaPy/pyjulia/issues/71

**Comment by CorbinFoucart** [comment]
Ok thanks, should I delete my previous comments in this thread?

**Comment by ViralBShah** [comment]
Let it be.

**Comment by JeffBezanson** [comment]
Could somebody check whether this is still a problem? A lot has certainly changed.

**Comment by Keno** [comment]
Closing. If similar issues recur with the new threading system, please file a new issue.
