### ISSUE TITLE
Equality between tuple types

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#15880]
I was trying to wrap a return value from `Cxx.jl` and got this error message when trying to create the wrapper:

```jl
ERROR: MethodError: Cannot `convert` an object of type 
Cxx.CppValue{Cxx.CxxQualType{Cxx.CppTemplate{Cxx.CppBaseType{symbol("Eigen::Matrix")},Tuple{Float64,-1,-1,0,-1,-1}},(false,false,false)},24} 
to an object of type 
Cxx.CppValue{Cxx.CxxQualType{Cxx.CppTemplate{Cxx.CppBaseType{symbol("Eigen::Matrix")},Tuple{Float64,-1,-1,0,-1,-1}},(false,false,false)},24}
```
The types here look identical and copy pasting them into the REPL shows that they indeed are `==` so the convert constructor shouldn't run.

After trying to distill what exactly was different between the two types I noticed that the `Tuple{Float64,-1,-1,0,-1,-1}` in the first type is not `==` the `Tuple{Float64,-1,-1,0,-1,-1}` in the second type. I extracted the first tuple type into `t1` and the second into `t2` (using `.parameters`):

```jl
# Copy pasting shows equality
julia> Tuple{Float64, -1, -1, 0, -1, -1} == Tuple{Float64, -1, -1, 0, -1, -1}
true

julia> t1
Tuple{Float64,-1,-1,0,-1,-1}

julia> t2
Tuple{Float64,-1,-1,0,-1,-1}

julia> t1 == t2
false
```

Looking at the object_id they are different:

```jl
julia> object_id(t1)
0xca36f0ab8c17be76

julia> object_id(t2)
0x7843e77a0396d329
```

This feels like a bug because the two tuple types are exactly the same type and should be `==`, no?

**Comment by JeffBezanson** [comment]
This is probably related to the fact that it doesn't make sense for a parameter of a Tuple type to be an integer, so some things in the system assume that doesn't happen.

**Comment by KristofferC** [comment]
Okay, this is the type that `Cxx` gives back when you instantiate a class templated on ints. Maybe creating this tuple type shouldn't be allowed if there are assumptions in the code that are being broken by it. 

 Anyway, feel free to close if this is purely a `Cxx` issue.

**Comment by JeffBezanson** [comment]
At one point there was an error for this, then @Keno twisted my arm into turning off the error, so I think that's how it happened :)

**Comment by Keno** [comment]
I'm fine with using Val{4} in the type instead.

**Comment by KristofferC** [comment]
Sounds like a plan

**Comment by JeffBezanson** [comment]
Actually I wonder if this is #15599. Aside from that there shouldn't be any way these types could be unequal. Did you run this with a recent build from master?

**Comment by KristofferC** [comment]
I am 95% certain that it was recent enough to include https://github.com/JuliaLang/julia/commit/e529058e386595f464e0eb85b34d1ffa75d2dbe8.

This was at my office computer and I am home now but I will build latest master and check on the home computer if I get the same thing.

**Comment by KristofferC** [comment]
Yes, this happens on latest master.

Full repo (with the Eigen lib http://bitbucket.org/eigen/eigen/get/3.2.8.tar.bz2 extracted to "../deps/eigen" relative to the file)

```jl
julia> using Cxx

julia> addHeaderDir("../deps/eigen/Eigen/"; kind = C_System)

julia> cxx"""
       #include <Core>
       """
true

julia> typealias DynamicEigenMatrixCppType{T} Cxx.CppValue{Cxx.CxxQualType{Cxx.CppTemplate{Cxx.CppBaseType{symbol("Eigen::Matrix")},Tuple{T,-1,-1,0,-1,-1}},(false,false,false)},24}
Cxx.CppValue{Cxx.CxxQualType{Cxx.CppTemplate{Cxx.CppBaseType{symbol("Eigen::Matrix")},Tuple{T,-1,-1,0,-1,-1}},(false,false,false)},24}

julia> immutable DynamicEigenMatrix{T} <: AbstractMatrix{T}
           cppvalue::DynamicEigenMatrixCppType{T}
       end

julia> t1 = DynamicEigenMatrixCppType{Float64}.parameters[1].parameters[1].parameters[2]
Tuple{Float64,-1,-1,0,-1,-1}

julia> t2 = typeof(icxx"Eigen::MatrixXd(3,4);").parameters[1].parameters[1].parameters[2]
Tuple{Float64,-1,-1,0,-1,-1}

julia> t1 == t2
false
```

**Comment by JeffBezanson** [comment]
This is strange. Could you check the values of `t1 === t2`, `issubtype(t1, t2)` and `issubtype(t2, t1)`?

**Comment by KristofferC** [comment]
```jl
julia> t1 === t2
false

julia> issubtype(t1, t2)
false

julia> issubtype(t2, t1)
false
```

**Comment by Keno** [comment]
Is is possible that the types of the integers are different?

**Comment by KristofferC** [comment]
When you say it.. it is so obvious.

```jl
julia> typeof(typeof(icxx"Eigen::MatrixXd(3,4);").parameters[1].parameters[1].parameters[2].parameters[2])
Int32

julia> typeof(DynamicEigenMatrixCppType{Float64}.parameters[1].parameters[1].parameters[2].parameters[2])
Int64
```
