### ISSUE TITLE
Pkg.update(), fatal: 'ColorMaps' does not appear to be a git rep

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/julia#15889]
and i tend to disagree...

ColorMaps was generated locally and has no github/anywhere counterpoint, so no remote, but i have other local packages that share that property.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.4-pre+218 (2016-01-29 21:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 386d77b* (77 days old release-0.4)
|__/                   |  x86_64-linux-gnu

julia> Pkg.status()
29 required packages:
 - BinDeps                       0.3.21
 - Cairo                         0.2.31
 - Clang                         0.1.0+             master
 - Colors                        0.6.3
 - CxxWrap                       0.1.2
 - Dates                         0.4.4
 - GR                            0.10.0
 - Gadfly                        0.4.0+             image (dirty)
 - GraphViz                      0.0.4+             master
 - Graphs                        0.6.0
 - Gtk                           0.9.3+             master
...
 - Winston                       0.11.13+           master
71 additional packages:
 - ColorMaps                     0.0.0-             master (unregistered)
...
 - Iplot                         0.0.0-             master (unregistered, dirty)
...
julia> Pkg.update()
INFO: Updating METADATA...
fatal: 'ColorMaps' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git pull --rebase -q`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 in anonymous at pkg/entry.jl:283
 in withenv at env.jl:160
 in anonymous at pkg/entry.jl:282
 in cd at ./file.jl:22
 in update at ./pkg/entry.jl:272
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45

```
the local git status:
```
lobi@orange4:~/.julia/v0.4/ColorMaps$ git status
On branch master
nothing to commit, working directory clean
lobi@orange4:~/.julia/v0.4/ColorMaps$ git branch
* master
lobi@orange4:~/.julia/v0.4/ColorMaps$ git remote
lobi@orange4:~/.julia/v0.4/ColorMaps$ 
```

**Comment by timholy** [comment]
My guess is it's complaining due to the lack of a remote; you might be able to test this guess by adding a remote for ColorMaps and seeing `Pkg.update()` then works. Probably the best thing for `update` to do is skip any directory that lacks a remote.

Did you create the ColorMaps directory manually, or did you use `Pkg.generate()`? I'm guessing the former, but if the latter then that may be a sign of a separate bug.

**Comment by lobingera** [comment]
a) generated with  Pkg.generate("ColorMaps","MIT")
b) i had on the list above Iplot, which is also local has no remote set

The error message (i couldn't find in julia base source) looks like from the git process.

**Comment by lobingera** [comment]
... and i had that before: statefull Pkg errors ...

```
julia> Pkg.rm("ColorMaps")
INFO: Removing ColorMaps (unregistered)

julia> Pkg.status()
29 required packages:
 - BinDeps                       0.3.21
 - Cairo                         0.2.31
 - Clang                         0.1.0+             master
...
 70 additional packages:
...
 - ColorBrewer                   0.3.0
 - ColorTypes                    0.2.2
 - ColorVectorSpace              0.1.2
 - Compat                        0.7.13
...
julia> Pkg.update()
INFO: Updating METADATA...
fatal: 'ColorMaps' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: failed process: Process(`git pull --rebase -q`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 in anonymous at pkg/entry.jl:283
 in withenv at env.jl:160
 in anonymous at pkg/entry.jl:282
 in cd at ./file.jl:22
 in update at ./pkg/entry.jl:272
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45

```

**Comment by wildart** [comment]
Have you looked at access permissions for this directory?

**Comment by lobingera** [comment]
Access permissions was drwxrwxr-x as with all packages in the .julia/v0.4. But in the meanwhile i Pkg.rm("ColorMaps"), the package directory is deleted but i still have the same error.

I didn't mention before: all this started with an unsucessful Pkg.add of QML, which was stopped in the build.

**Comment by lobingera** [comment]
@timholy, after some searching in pkg.jl and other places and some wild guesses i tracked down the problem in the METADATA update.
And.
```
lobi@orange4:~/.julia/v0.4/METADATA$ more .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = ColorMaps
        fetch = +refs/heads/*:refs/remotes/origin/*
        pushurl = git@github.com:JuliaLang/METADATA.jl.git
[branch "metadata-v2"]
        remote = origin
        merge = refs/heads/metadata-v2
[remote "lobingera"]
        url = https://github.com/lobingera/METADATA.jl.git
        fetch = +refs/heads/*:refs/remotes/lobingera/*

```
I'll try now to track down, how and why ColorMaps was put here.

**Comment by lobingera** [comment]
i tried to track down, what happened where and afaics i never manually touched the git configuration (shell history). The julia history of package operations is afaics:
        Pkg.generate("ColorMaps","MIT")
        Pkg.add("CxxWrap")
        Pkg.update()
and Pkg.add of CxxWrap failed with missing cmake3.0. 

and also afaics the only call from base julia that touches the git config is set_remote_url which is called in a few places.

I'm closing this now, as the reproducibility of the error is not given (on my side). 

P.S. i had a similar problem long, long ago in 0.3 with failing installation, but there i wasn't sure if i ever had touched the git config manually, here i'm sure.

**Comment by ShnitzelKiller** [comment]
I just had the same problem with a package I created using Pkg.generate(). The package name somehow got written over the origin URL for the METADATA repository.

**Comment by lobingera** [comment]
I closed this, because i couldn't reproduce the error. Do you have a sequence of commands that in any case and with a 'fresh' julia installation show the error? And if yes, what system/version do you use?

**Comment by deszoeke** [comment]
I have a similar issue when I update to julia 0.4.6. The NetCDF package (which should be a git repository) requires Homebrew, which dies trying to recompile. After that I get
`'NetCDF' does not appear to be a git repository`
whenever I try Pkg.update().

I had this happen on another Mac OSX 10.11.5 at home. I thought I resolved it by downloading a new julia binary, but I am using a fresh julia 0.4.6 binary.

Where is pkg.jl?

**Comment by tkelman** [comment]
I think Homebrew.jl has started misbehaving, Ipopt.jl has also had similat issues.

**Comment by deszoeke** [comment]
This seems to be a common problem. I'm guessing what happens is a Pkg build failed, corrupting ~/.julia/v0.4/METADATA/.git/config, which prevents further building and updating. In my case the dependency Homebrew wouldn't build, and the package NetCDF got corrupted. Packages seem to update again when from the julia prompt I run
```
export FC=gfortran
Pkg.build("NetCDF") # rebuilds the complaining package
Pkg.init()
Pkg.update()
```
I'm not sure if the first two lines are necessary.
