### ISSUE TITLE
Error from Libdl.dlopen is misleading when library file in fact contains a linker script

### ISSUE THREAD

**Issue by ackalker** [JuliaLang/julia#15899]
From my problem trying to get the TermWin package to work on Arch Linux x86_64, Julia 0.4.5, I find that I'm getting this error when trying to dlopen `libncurses`:

```sh
$ julia -e 'Libdl.dlopen("libncurses")'
ERROR: could not load library "libncurses"
libncurses: cannot open shared object file: No such file or directory
 in dlopen at libdl.jl:36
```

On my system, the file `/usr/lib/libncurses.so` actually does exist, but instead of a binary, it contains a linker script:

```sh
$ cat /usr/lib/libncurses.so
INPUT(-lncursesw)
```

Running with `strace` confirms that Julia does find both `libncurses.so` and `libncursesw.so`:
```sh
$ strace -f julia -e 'Libdl.dlopen("libncurses")' > strace.out 2>&1
```
Please look [here](https://gist.github.com/b80dec27d59918cf5490d2766cec76cf) for the full log.

If `Libdl.dlopen` is meant to behave more or less as the system `dlopen` (which doesn't support linker scripts, see [here](https://www.sourceware.org/ml/libc-alpha/2011-07/threads.html#00139) for arguments for and against), it should produce a different error message, as this small C program demonstrates.

```c
#include <stdio.h>
#include <dlfcn.h>

#define MODULE "libncurses.so" /* NOT working */

int main(int argc, char *argv[])
{
  void *hnd;
  if ((hnd = dlopen(MODULE, RTLD_LAZY | RTLD_DEEPBIND)) != NULL) {
    printf("Successfully dlopened %s, handle: %p\n", MODULE, hnd);
    dlclose(hnd);
  } else {
    printf("Failed to dlopen %s: %s\n", MODULE, dlerror());
  }
  return 0;
}
```

Compiling it using `cc -o dlopen dlopen.c -ldl`, then running it produces:
```sh
$ ./dlopen 
Failed to dlopen libncurses.so: /usr/lib/libncurses.so: file too short
```

Replacing `libncurses.so` with `libncursesw.so`, recompiling and running again produces:
```sh
$ ./dlopen 
Successfully dlopened libncursesw.so, handle: 0x1c8b030
```

This works in Julia:
```sh
$ julia -e 'Libdl.dlopen("libncursesw")'
```

**Comment by yuyichao** [comment]
You need to pass the same argument to the C function and the julia function.

```jl
yuyichao% LANG=C julia -f -e 'Libdl.dlopen("libncurses.so")' 
ERROR: could not load library "libncurses.so"
/usr/bin/../lib/libncurses.so: file too short
 [inlined code] from ./c.jl:89
 in dlopen(::ASCIIString, ::UInt32) at ./libdl.jl:66 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:237
 [inlined code] from ./sysimg.jl:11
 in process_options(::Base.JLOptions) at ./client.jl:240
 in _start() at ./client.jl:319
```

Feel free to submit doc improvement if it is not clear about this.

**Comment by ackalker** [comment]
I took the call to `Libdl.dlopen` from [here](https://github.com/tonyhffong/TermWin.jl/blob/b7bc07b7808526e97daa4f9141b2fc5e060b6ac7/src/ccall.jl#L9), hence my "behave more or less as the system `dlopen`" remark.

This makes the whole issue even more confusing than I thought it to be.
Could you please explain why `Libdl.dlopen("libncursesw")` does work in this case?

**Comment by yuyichao** [comment]
And some more detail about the error printed and why `libncursesw` works. Julia tried to add extensions to your file names when it calls `dlopen` and will succeed as long as one of them succeeded. This is `""` and `".so"` for linux. The error returned is the one for the last one tried. We can reverse the two to give better error for this case but it will give worse error if you supply the name with the extension (since the `*.so.so` file does not exist...).

**Comment by ackalker** [comment]
I would like to argue strongly for keeping `Libdl.dlopen` as close to the system implementation as possible (the very name of the module and the function suggest that much), to minimize confusion.

I'm aware of `ccall(:symbol, :library, ...)` which, as a pure Julia feature, can of course perform as much or as little 'magic' as it pleases.

**Comment by yuyichao** [comment]
> as close to the system implementation as possible

No, this makes it much harder to write system independent code.

I think I can find a way to make the error closer to the system one though. Will submit a PR later.

**Comment by ackalker** [comment]
Thanks for looking into this.
