### ISSUE TITLE
Varargs inside macros swallow keyword arguments

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15896]
Macros with complex uses of varargs and keyword arguments can give really weird results. In the following, the keyword argument `y` shouldn't be passed to `g()`, nor passed twice to `f()`, and using `,` or `;` shouldn't make any difference.

```julia
julia> macro test(d, x...; y=0)
           esc(:(f(g($d, $(x...)), $(x...); y=$y)))
       end
@test (macro with 1 method)

julia> macroexpand(:(@test(1, 2, 3; y=4)))
:(f(g(1,2,3; y=4),1,2,3; y=0))

julia> macroexpand(:(@test(1, 2, 3, y=4)))
:(f(g(1,2,3,y=4),2,3,y=4; y=0))

```

**Comment by yuyichao** [comment]
This is not related to `Varargs` since I don't think you can pass any kw argument to a macro in general, they are all passed as expressions, i.e. `Expr(:kw)` and `Expr(:parameters)`.

**Comment by nalimilan** [comment]
Thanks. Are there any plans to allow passing keyword arguments to macros? I have a case in which it would have been useful.
