### ISSUE TITLE
deps/jldownload: No se encontró el programa

### ISSUE THREAD

**Issue by primitivorm** [JuliaLang/julia#15901]
```bash
primi@primi-lap:~/src/julia$ make -C deps getall
make: se ingresa al directorio «/home/primi/src/julia/deps»
/home/primi/src/julia/deps/jldownload llvm-3.3.src.tar.gz http://llvm.org/releases/3.3/llvm-3.3.src.tar.gz
make: /home/primi/src/julia/deps/jldownload: No se encontró el programa
make: *** [llvm-3.3.src.tar.gz] Error 127
make: se sale del directorio «/home/primi/src/julia/deps»
```

**Comment by yuyichao** [comment]
Please post the error messages in English.

Which version are you building?
Can you check if `/home/primi/src/julia/deps/jldownload` exists and is executable?
Also if `/bin/sh` exists and is executable.

**Comment by tkelman** [comment]
You can do `LC_ALL=C make ...` to get english errors temporarily.

You might be missing curl and wget. Which operating systen (version? distribution?) is this?

**Comment by ivarne** [comment]
Lets close this, and reopen if @primitivorm answers the questions, and it turns out to be an actionable Julia problem.
