### ISSUE TITLE
Array{Int,0}() doesn't work

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15907]
0-dimensional arrays are inconsistent with other cases. The constructor would probably need to be adapted a bit.

``` julia
julia> Array{Int,0}() 
ERROR: MethodError: no method matching Array{Int64,0}()
 in eval(::Module, ::Any) at ./boot.jl:236

julia> Array{Int,1}()
0-element Array{Int64,1}

julia> Array{Int,2}()
0x0 Array{Int64,2}
```

UPDATE: fixed according to comments

**Comment by yuyichao** [comment]
Note that `Array{Int,0}(1)` should **NOT** work. `Array{Int,0}()` should though.

**Comment by eschnett** [comment]
What @yuyichao is saying is that array constructors are different from most other collection constructors: They don't take a list of elements to initialize the array; instead, they always produce an uninitialized array. They accept integer arguments to specify the array size, and for a zero-dimensional array, they should accept zero integers.

**Comment by nalimilan** [comment]
Yes, of course. Though what's slightly annoying is that `convert(Array{Int,0}, 1)` and `convert(Array{Int,1}, 1)` don't work either. What's the shortest way to create a 0-dimensional array from a scalar?

**Comment by eschnett** [comment]
This syntax would be
```Julia
let x=Array{Int}(); x[]=scalar; x end
```
If you find a way to avoid the local variable, let me know.

**Comment by nalimilan** [comment]
Yes, that's the shortest solution I could find. Is there a reason why `convert` is not supported?

**Comment by GunnarFarneback** [comment]
setindex!(Array(Int), scalar)

**Comment by nalimilan** [comment]
@GunnarFarneback Interesting one.

**Comment by JeffBezanson** [comment]
I like this game. Here's another one: `fill(scalar, ())`.

**Comment by eschnett** [comment]
On Sunday, April 17, 2016, Gunnar Farnebäck <notifications@github.com>
wrote:
> setindex!(Array(Int), scalar)

This returns the scalar, not the array.

-erik

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub<
https://ci4.googleusercontent.com/proxy/DBGJtaOCxaJQzmso8tNTFH-XRKtO9HnpvS04JrQkqZf3CrR7gQbETTiDEPUqhRoB8Pilj0a6dmk9JMI-85w6jsdN9iMA10TprfsfWgdxzGuOIqmfHKcOCfQX316OXHQLzw63l7R_xwwf4T8H-ilIspKqH9A9FQ=s0-d-e1-ft#https://github.com/notifications/beacon/AANCCnkqkUG8i7fvviTDpfc49hvarOoUks5p4kPrgaJpZM4IJJCC.gif
>

-- 
Erik Schnetter <schnetter@gmail.com>
http://www.perimeterinstitute.ca/personal/eschnetter/

**Comment by yuyichao** [comment]
> This returns the scalar, not the array.

```jl
julia> setindex!(Array(Int), 1)
0-dimensional Array{Int64,0}:
1
```

The return value of `setindex!` has nothing to do with the return value of `a[x] = b`

**Comment by cstjean** [comment]
`fill(scalar)`
