### ISSUE TITLE
sizeof sparse matrix gives wrong size

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#15903]
It seems that evaluating `sizeof` on a sparse matrix always return 40.

The `Base.summarysize` function does not have this problem.

**Comment by vtjnash** [comment]
that's the expected definition for Core.sizeof:
```
   8 type SparseMatrixCSC{Tv,Ti<:Integer} <: AbstractSparseMatrix{Tv,Ti}
   9     m::Int                  # Number of rows
  10     n::Int                  # Number of columns
  11     colptr::Vector{Ti}      # Column i is in colptr[i]:(colptr[i+1]-1)
  12     rowval::Vector{Ti}      # Row values of nonzeros
  13     nzval::Vector{Tv}       # Nonzero values
  14 
```

8bytes * 5 fields = 40 bytes

**Comment by yuyichao** [comment]
`sizeof` returns the size of the julia object for all the containers implemented in julia

**Comment by jebej** [comment]
I see, what is the proper function to know the full size of a variable in bytes then?

**Comment by yuyichao** [comment]
I think it is also hard to define `sizeof` for julia containers other than the one we have now. `length` should return the number of objects stored for a container but it is basically an implementation detain how much memory the container actually takes.

**Comment by vtjnash** [comment]
`summarysize` is the estimate on the full size of allocated memory reachable from that node
