### ISSUE TITLE
DivideError when dividing a zero rational by a complex number

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15920]
This happens in the numbers test on https://github.com/JuliaLang/julia/pull/15917

Slightly simplified repro:
```jl
julia> Rational(0, 3) / Complex(3, 2)
ERROR: DivideError: integer division error
 [inlined code] from ./rational.jl:19
 in +(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:179
 [inlined code] from ./complex.jl:4
 in inv(::Complex{Rational{Int64}}) at ./complex.jl:118
 in /(::Rational{Int64}, ::Complex{Int64}) at ./rational.jl:191
 in eval(::Module, ::Any) at ./boot.jl:237
```

**Comment by yuyichao** [comment]
Wow, the offending method is really old ... https://github.com/JuliaLang/julia/commit/93710f336308b175f4f3b4ad517781ad003c3770

**Comment by andreasnoack** [comment]
Even older since that commit is just some cleanup. I think this is the real offender https://github.com/JuliaLang/julia/commit/d0ac203c400c6eb71d4a3d967c4222740114545b. By the way, it looks as if you, in the summer of 2010, could muliply with white space.

**Comment by yuyichao** [comment]
The bad one is the [`/`](https://github.com/JuliaLang/julia/commit/93710f336308b175f4f3b4ad517781ad003c3770#diff-45dbc765e59a373a6e71dc40bbd456f3R69) which is added (agrees with the commit message) by the commit I linked. The clean up done in that commit is actually for another function....

**Comment by andreasnoack** [comment]
Yes, my bad. I was carried away with the Julia archeology.
