### ISSUE TITLE
show(::Vector{Float32}) always compact

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15926]
`Vector{Float32}` are always `show()`ed in their compact form, despite the existence of a longer form:
```julia
julia> showcompact(1f0)
1.0
julia> show(1f0)
1.0f0
julia> limit_output(STDOUT)
false
julia> showcompact([1f0])
Float32[1.0]
julia> show([1f0])
Float32[1.0]     # Instead of Float32[1.0f0]
```

I wonder whether this isn't yet another occurrence of inlined methods not being updated. Indeed, if I copy/paste the definition of ` show_delim_array` at the REPL, I get the non-compact form:
```julia
julia> Base.show_delim_array(STDOUT, [1f0], "[", ",", "]", false)
[1.0]
julia> show_delim_array(STDOUT, [1f0], "[", ",", "]", false)
[1.0f0]
```

That's obviously not a big deal, but I found it quite confusing when trying to replicate the behavior of `Float32` with `Nullable` (more on that in a PR soon). Also, the fact that it doesn't behave as intended means that tests in Base may not cover a more general mechanism on which packages could depend. If we could fix it, it would be nice.

We could also imagine changing the policy, as `Float32[1.0f0]` includes redundant information, which doesn't sound great as a default for `show`.

Cc: @vtjnash

**Comment by vtjnash** [comment]
a general cleanup would be appreciated. in particular, jeff has proposed that that we should eliminate `showcompact` in favor of having `limit_output` return a level-of-detail (https://github.com/JuliaLang/julia/issues/14052#issuecomment-168411163)

**Comment by nalimilan** [comment]
Yes, that's a great plan. But the issue I described above looks like a very localised bug, and it can be reproduced with `show(IOContext(STDOUT, :limit_output => true), [1f0])`, so it won't go away with the cleanup.

**Comment by vtjnash** [comment]
ah, ok. yeah, this seems like #265

**Comment by JeffBezanson** [comment]
Fixed:

```
julia> show(IOContext(STDOUT, :compact => false), [1f0])
Float32[1.0f0]
julia> show(IOContext(STDOUT, :compact => true), [1f0])
Float32[1.0]
```
