### ISSUE TITLE
0.4.6pre Documentation for SubArray looks out of date

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#15931]
It states that a `SubArray` is defined as

```julia
type SubArray{T,N,P<:AbstractArray,I<:(ViewIndex...),LD} <: AbstractArray{T,N}
    parent::P
    indexes::I
    dims::NTuple{N,Int}
    first_index::Int   # for linear indexing and pointer
    stride1::Int       # used only for linear indexing
end
```

when actually it's defined as

```julia
immutable SubArray{T,N,P<:AbstractArray,I<:Tuple{Vararg{ViewIndex}},LD} <: AbstractArray{T,N}
    parent::P
    indexes::I
    dims::NTuple{N,Int}
    first_index::Int   # for linear indexing and pointer
    stride1::Int       # used only for linear indexing
end
```

**Comment by mbauman** [comment]
Oh, yikes, I had totally forgotten about that chapter!  It's woefully out of date now; there's been an even bigger refactor in #15071.  In general, things are much simpler, but it'd still be worth documenting their internals.  I'm not sure when I'll find time for it; if anyone else wants to take a shot at it I'd happily provide feedback.

**Comment by mbeltagy** [comment]
It continues to be out of date. Now in 0.5, we do not have ``sub`` or ``slice``, only ``view``. Further the explanation of the SubArray type remains dated.
