### ISSUE TITLE
Diagonal \ SparseMatrixCSC throws StackOverflow

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/julia#15933]
Trying the following
```
D = Diagonal(rand(5))
A = sprandn(5,5,.1)
D\A
```
Gives me a StackOverflow error. Looking at linalg/generic.jl at line 323 it  seemed like the problem is that factorize(D) returns a Diagonal and then goes on forever. However, 
```
D\full(A)
```
works fine for me. I'm using 0.4.6-pre+23 by the way.

**Comment by lruthotto** [comment]
just checked and the problem still persists with version  0.4.6-pre+30

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14005
@andreasnoack maybe we can have a backportable version of the PR's that fixes it?

**Comment by tkelman** [comment]
apparently not
