### ISSUE TITLE
Variable inferred as Core.Box due to read-only access after definition

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15938]
With latest git master, in the function below, the type of `len` is inferred correctly, but not `lev` is marked as `Core.Box`. Removing the `ntuple` call fixes this. In 0.4, the types of both variables are inferred correctly.

Feel free to close if `Core.Box` isn't actually an indication of type instability (I'm merely trusting `@code_warntype` here).

```julia
function f{N}(x::NTuple{N})
    lev = [length(y) for y in x]
    len = [length(y) for y in x]

    ntuple(i -> length(lev[i]), N)
end

@code_warntype f((1,2))
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276

**Comment by nalimilan** [comment]
Ah, I had only looked for `Core.Box`, but the name wasn't fully qualified a few weeks ago. At least, this issue will help people doing a simple search as I did.

**Comment by yuyichao** [comment]
To be fair, `Box` isn't very searchable either.... I can only find it quickly because I pasted it to a more searchable and more recent issue lately....
