### ISSUE TITLE
Iterating over typemin(Int):typemax(Int) does nothing

### ISSUE THREAD

**Issue by hayd** [JuliaLang/julia#15935]
```
julia> for i in typemin(Int):typemax(Int)
         i == typemin(Int) && (println(i); break)
       end

julia> for i in typemin(Int32):typemax(Int32)
         i == typemin(Int32) && (println(i); break)
       end
-2147483648
```

*Presumably this is due to the [conversion to Int](https://github.com/JuliaLang/julia/blob/63920781bc9009d8792190801607f9a0cf78b0fd/base/range.jl#L410).*

If this is not fixable should `typemin(Int):typemax(Int)` be disallowed or warned about in the docs (perhaps it is already)?

**Comment by bicycle1885** [comment]
Maybe a dup of #11742.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/11742
