### ISSUE TITLE
Forward declaration parsing error

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#15949]
On 0.4.5

```julia
x = :foo
:(function $x end)
```

yields

`LoadError: syntax: expected "(" in function definition`

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14561 tentatively add backport pending, not sure if possible.

**Comment by cstjean** [comment]
The work-around is fine, it's not a significant issue.

**Comment by tkelman** [comment]
If #14562 caused major slowdowns on `SharedArray`s that were only fixed by jb/functions then I don't think we can backport it.
