### ISSUE TITLE
type-inference penalty for loops over conditional collections

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#15946]
In some cases it is nice to have a loop like `for x in (condition ? A : B) ... `, but it appears that this defeats type inference.

For example, in #15945 it turned out that I needed to traverse the same loop in a different order depending on the sign of a variable.  (Because I wanted to loop from big to small terms in a series, enabling me to stop the loop early when the series terms become small enough.)

e.g. `@code_warntype` shows `Any` types for
```
function foo(x)
    s = 0.0
    for i = (x < 0 ? (10:-1:1) : (1:10))
        s += 1/i^2
    end
    return s
end
```

Of course, I could always just write two loops here, but it is annoying to have to write an identical loop body twice — I wish the compiler could do this for me.

**Comment by KristofferC** [comment]
But the ranges are different types?

**Comment by KristofferC** [comment]
What happens if you change to `(1:1:10)`?

**Comment by stevengj** [comment]
Yes, if you make the collections of the same type, then the type inference succeeds.  It would be nice to have Julia split the loop for you in cases where the collections are two different types, though.

**Comment by yuyichao** [comment]
This is not specific about loops. In general any time you have a type unstable branch there's this problem. Being the range of the loop doesn't make it easier or harder to solve.

**Comment by stevengj** [comment]
Fair enough.
