### ISSUE TITLE
Logarithm Function

### ISSUE THREAD

**Issue by OrangeEfficiency** [JuliaLang/julia#15959]
Hi, has anyone noticed that log functions with log bases other than e, 2, 10 generate weird results ? For example:
```
log(3,27)
3.0000000000000004

log(3,81)
4.000000000000001

log(6,216)
3.0000000000000004
```
I was just wondering if that could be a bug.

**Comment by lobingera** [comment]
Welcome to the wonderful world of floating point math:http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

... read as: it's not a bug, you find situations like this all around and on other math systems, too.

**Comment by KristofferC** [comment]
log(3,27) is simply log(27) / log(3). You can't expect floating point operations to give exact results.

If you need more precision you can use `log(big(3), big(27))`

**Comment by OrangeEfficiency** [comment]
Thank a lot for your helpful explanation. Cheers :)
