### ISSUE TITLE
hash stability broken: hash(a) != hash(a) after pmap

### ISSUE THREAD

**Issue by yadongli** [JuliaLang/julia#15966]
I'm very surprised to find that hash stability is broken with parallel execution using pmap. The following results are obtained from the latest juliabox.org using Julia v0.4.5, it shows that when two objects are equal, somehow their hashes are different, it creates obvious and serious problems for parallel execution using pmap. 

```
addprocs(2)
println(nprocs(), " worker CPUs\n")

@everywhere immutable TwoInt
    a::Int
    b::Int
end

a = TwoInt(1, 2)
b = TwoInt(1, 2)

println("=== on local CPU ===")
println("a==b: ", a == b)
println("hash(a)==hash(b): ", hash(a) == hash(b))

println()
println("=== run in parallel by pmap ===")
as = pmap(identity, fill(a, 2))
println("a==a: ", as[1] == as[2])

hs = pmap(hash, fill(a, 2)) 
println("hash(a)==hash(a): ", hs[1] == hs[2])
println("hash values are: $(hs[1]), $(hs[2])")
```

The results of the above code on juliabox.org's v0.4.5 is:
```
3 worker CPUs

=== on local CPU ===
a==b: true
hash(a)==hash(b): true

=== run in parallel by pmap ===
a==a: true
hash(a)==hash(a): false
hash values are: 8933127515918620283, 9955233859733133294
```

Not sure if anyone has noticed this before, this behavior is really bizarre. The following is the versioninfo() output:

```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

many thanks,
@yadongli

**Comment by yuyichao** [comment]
Seems to be caused by the difference in type has on the worker?

**Comment by yadongli** [comment]
@yuyichao do you mean it is the expected behavior? 

I also tried to create a module file for the TwoInt, and use import to load it so that all the workers should have the same type, but the hashes are still different.

**Comment by yuyichao** [comment]
No I don't think that's expected behavior. I'm just saying it's because of the type...

**Comment by JeffBezanson** [comment]
#5849 perhaps
