### ISSUE TITLE
JuMP and SymPy

### ISSUE THREAD

**Issue by schalil** [JuliaLang/julia#15965]
I have a code that uses JuMP and SymPy
I am getting the below error message
`WARNING: both SymPy and JuMP export "solve"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: solve not defined
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib`

**Comment by IainNZ** [comment]
Hi @schalil,
This type of post is better made on the julia-users mailing list.
As to your problem, the error message is correct - both these packages export solve, so you need to specify which one you want, e.g. `JuMP.solve(your_model)`.

**Comment by schalil** [comment]
Thank you. It worked.
