### ISSUE TITLE
access to fused multiply-subtract etc.

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#15985]
Currently, `f(x,y,z) = @fastmath muladd(x, y, -z)` generates an explicit negation operation for the `-z` in the case of floating-point arguments, as can be seen by `@code_native f(3.0, 4.0, 5.0)`.   Similarly for `muladd(-x, y, z)` etcetera.

In #9881, @yuyichao indicated that this was due to the FastSel optimization in LLVM.

As I mentioned in #6330, it would be good to have access to fused multiply-subtract and similar operations.   LLVM doesn't provide intrinsics for these, but it would be good to have a way to write code that LLVM can transform into such instructions when they are available, and that will avoid explicit negations when fused operations aren't available.

cc: @eschnett, @simonbyrne

**Comment by yuyichao** [comment]
I had a hard time following the isel logic in LLVM but it seems that the logic of replacing `fmadd(x, y, -z)` with `fmsub(x, y, z)` only appears at one place and looks pretty general (eliminate the neg if it is only used by one fma-like instruction) so I don't think there's much we can do to help llvm recognizing the code pattern here.

Can we make https://github.com/JuliaLang/julia/pull/15984 close this and make this an upstream issue?

**Comment by stevengj** [comment]
Sounds good @yuyichao.

**Comment by yuyichao** [comment]
Might be related https://llvm.org/bugs/show_bug.cgi?id=13118
