### ISSUE TITLE
Why the Julia REPL does not accept the standard windows pathname (single slash)

### ISSUE THREAD

**Issue by zlqs1985** [JuliaLang/julia#15981]
I want to change my working directory to `C:\Users\zhanglu\Documents\Julia`, which is a windows style path containing  single back slashs `\` . However, the Julia REPL seems doesn't accept such expression and if I type like
`cd("C:\Users\zhanglu\Documents\Julia")`
I will receive error message like 
`Error syntax: invaild escape squence`
I have to manually change the single back slashs to double ones to make it work. Any convinent way?
One more question . Is there any convient way to change the working directory to a subfolder within the current one. say, `C:\Users\zhanglu\Documents\Julia` within `C:\Users\zhanglu\Documents `without typing the full path?

**Comment by yuyichao** [comment]
You need to escape `\` with `\\`

**Comment by StefanKarpinski** [comment]
Please post questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.

**Comment by ivarne** [comment]
You can define and use the simplest String macro

```julia
macro raw_str(x)
    x
end

# Now you can use `raw` as a string prefix
cd( raw"C:\Users\zhanglu\Documents\Julia" )
```
I'm not sure why we don't have such a macro in Base

**Comment by Ismael-VC** [comment]
Note that this way, just as in Python you would need to escape only one backslash (if it's the last one):

```julia
julia> raw"C:\Users\ismaelvc\Documents\julia\\"
"C:\\Users\\ismaelvc\\Documents\\julia\\\\"
```

Which IMO is fine as long as it is documented.

**Comment by pemryan** [comment]
macro raw_str(x)
    x
end

this macro doesn't work for windows disk drive root dir. e.g. raw"C:\"  would be treated as a incomplete statement.  It works when the last char is not a back slash.
