### ISSUE TITLE
float16 `trunc` doesn't work for certain input

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15993]
Happened on AppVeyor win64 for https://github.com/JuliaLang/julia/pull/15984 (https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.726/job/qux4bbryj4uuf9ts)

Basically [the test](https://github.com/JuliaLang/julia/blame/72ba87a5dc05480fa89b0492b53832d4157a7c18/test/float16.jl#L41) doesn't work for any input with fractional larger than `0.99975586`.

```jl
julia> x = 0.99975586f0
0.99975586f0

julia> trunc(Int,Float16(x)) == trunc(Int,x)
false

julia> Float16(x)
Float16(1.0)

julia> trunc(Int,x)
0
```

I'm not sure if the impl is wrong or the test is wrong. @kshyatt

**Comment by yuyichao** [comment]
Assuming the `Float16` constructor use the default `RoundNearest` in this case I guess the test is wrong here...

**Comment by tkelman** [comment]
Yeah, the test is wrong. I think this has come up before.
