### ISSUE TITLE
juno-mac-x64.dmg could not be identified on OS X EI Captain 10.11.4

### ISSUE THREAD

**Issue by zhaozhengbo** [JuliaLang/julia#16013]
Anyone can tell me a solution to this problem, thanks in advance.

juno-mac-x64.dmg could not be identified on OS X EI Captain 10.11.4

**Comment by yuyichao** [comment]
Please ask questions on julia-users mailing list or report to juno forum with a more detail description of the problem.

**Comment by zhaozhengbo** [comment]
OK, I uploaded the photo, that's what all I have, hope you will let it be.
