### ISSUE TITLE
Using `continue` in list comprehensions

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/julia#16027]
Is using `continue` in a list comprehension a bad idea? I was playing around and found the following behavior which could be a bit dangerous:

```julia
julia> [ z == 5 ? continue : z for z in 1:10]
10-element Array{Int64,1}:
  1
  2
  3
  4
  6
  7
  8
  9
 10
  0
```

Note that `z=5` is skipped as I wanted, but there is an (undesired) zero hanging at the end of the list. I presume this is because the array is preallocated... If that is the case, then maybe trying to do this should throw an error or at least a warning?

(I know that I could use `setdiff` to achieve the desired outcome for this specific example...)

**Comment by simonster** [comment]
Dup of #6476
