### ISSUE TITLE
Compilation failed on ppc64

### ISSUE THREAD

**Issue by Albert65** [JuliaLang/julia#16036]
Hi All, I am trying to compile Julia 0.4.5 on Power8, Redhat 7.2/64-bit. My "Make.user" file:

    prefix=${SOFT}/julia  
[julia.ppc64.log.zip](https://github.com/JuliaLang/julia/files/234398/julia.ppc64.log.zip)

                  # <-- custom destination folder, SOFT is defined in .bashrc
    include $(JULIAHOME)/Make.powerpc

The failure happens while "inference.jl" is compiled (the complete output file is attached):

```
inference.jl
julia: /home/albert/tmp/julia-0.4.5/deps/llvm-3.6.0/lib/CodeGen/MachineLICM.cpp:960: bool {anonymous}::MachineLICM::IsLoopInvariantInst(llvm::MachineInstr&): Assertion `MRI->getVRegDef(Reg) && "Machine instr not mapped for this vreg?!"' failed.

signal (6): Aborted
/bin/sh: line 1: 102713 Aborted                 (core dumped) /home/albert/tmp/julia-0.4.5/usr/bin/julia -C native --output-ji /home/albert/tmp/julia-0.4.5/usr/lib/julia/inference0.ji -f coreimg.jl
make[1]: *** [/home/albert/tmp/julia-0.4.5/usr/lib/julia/inference0.ji] Error 134
make: *** [julia-inference] Error 2
```

**Comment by Keno** [comment]
I would recommend testing with latest master of Julia and LLVM. There has been some work done on the LLVM Power backend, which may fix this.

**Comment by vtjnash** [comment]
agreed. llvm-3.6.0 is not going to be supported.

**Comment by ViralBShah** [comment]
Closing this for now. Please reopen if it fails even with Julia's default llvm choice or llvm master.

**Comment by tkelman** [comment]
We should probably update https://github.com/JuliaLang/julia/blob/release-0.4/Make.powerpc, 3.6 is apparently still the default setting for release-0.4.

**Comment by Albert65** [comment]
Hi All, I tried with the source from GitHub, the problem happens at a bit earlier stage than before (note, llvm-3.7.1 is used for now):

/home/albert/tmp/julia/src/ccall.cpp:127:4: warning: #warning is a GCC extension [enabled by default]
 #  warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination"
    ^
/home/albert/tmp/julia/src/ccall.cpp:127:4: warning: #warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination" [-Wcpp]
    CC src/disasm.o
    CC src/debuginfo.o
    CC src/llvm-simdloop.o
    CC src/llvm-gcroot.o
    LINK usr/lib/libjulia.so
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Warning: File `../src/julia_version.h' has modification time 84 s in the future
    CC ui/repl.o
    LINK usr/bin/julia
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/man/man1/julia.1
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/fenv_constants.jl
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
Copying in usr/share/doc/julia/examples
    JULIA usr/lib/julia/inference.ji
julia: /home/albert/tmp/julia/deps/srccache/llvm-3.7.1/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::MCSymbolELF; Y = llvm::MCSymbol; typename llvm::cast_retty<X, Y*>::ret_type = llvm::MCSymbolELF*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
/bin/sh: line 1: 196533 Aborted                 (core dumped) /home/albert/tmp/julia/usr/bin/julia -C native --output-ji /home/albert/tmp/julia/usr/lib/julia/inference.ji -f coreimg.jl
make[1]: *** [/home/albert/tmp/julia/usr/lib/julia/inference.ji] Error 134
make: *** [julia-inference] Error 2

**Comment by Albert65** [comment]
Hi Viral, I don't really understand how to reopen the closed issue, that is why the new one was opened.

**Comment by ViralBShah** [comment]
Understand. You should see a reopen button below, on the closed issue page, if you are the one that opened it.

**Comment by yuyichao** [comment]
An issue cannot be reopened by the reporter if it was closed by someone else. Just leave a comment in that case.
