### ISSUE TITLE
juno-mac-x64.dmg could not be identified on OS X EI Captain 10.11.4

### ISSUE THREAD

**Issue by zhaozhengbo** [JuliaLang/julia#16033]
Anyone can tell me a solution to this problem, the symptom and the dmg file are shown as in the photo, thanks in advance.

juno-mac-x64.dmg could not be identified on OS X EI Captain 10.11.4
![2016-04-25 9 54 07](https://cloud.githubusercontent.com/assets/18624268/14772074/2bfa49ea-0acc-11e6-972f-c05bdadf8a9b.png)

**Comment by yuyichao** [comment]
[As I said](https://github.com/JuliaLang/julia/issues/16013#issuecomment-213652583), the juno binary is not part of base julia and there're better places to ask about this.

**Comment by zhaozhengbo** [comment]
which place， could you provide me with a direct link given you have closed my question twice.
Zhao Hongsheng
Ph.D. 
R&D Center of ATM
AVIC Aeronautical Radio Electronics Research Institute 
No.432, Ziyue Street
Minhang District, 200241
Shanghai, China 

赵鸿盛 博士
中航工业无线电电子研究所
空中交通管理研究中心
上海市闵行区紫月路432号 200241

**Comment by yuyichao** [comment]
[juno forum julia](http://lmgtfy.com/?q=juno+forum+julia)
[julia-users](https://groups.google.com/forum/?fromgroups=#!forum/julia-users) The link is available from http://julialang.org/community/
