### ISSUE TITLE
define isless and other comparison operators for Arrays

### ISSUE THREAD

**Issue by aoboturov** [JuliaLang/julia#16046]
Define a comparison operators `<,>` etc for Arrays with obvious semantics:

     aa = [1., 2.]
     bb = [3., 1.]
     aa < bb

ERROR: MethodError: `isless` has no method matching isless(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  isless(::DataArrays.NAtype, ::Any)
  isless(::Any, ::DataArrays.NAtype)
 in < at operators.jl:33

**Comment by johnmyleswhite** [comment]
Use the existing `.<` operator.

**Comment by mbauman** [comment]
There's also [`lexless`](http://docs.julialang.org/en/release-0.4/stdlib/base/?highlight=lexless#Base.lexless), which I think has the semantics that you want.

**Comment by Keno** [comment]
Yes, arrays do not have a canonical order, so the user should be explicit about what they mean.

**Comment by aoboturov** [comment]
@johnmyleswhite thanks a lot :)

**Comment by roberthoenig** [comment]
For anyone else reading this: In Julia 1.0, `cmp` (and hence `isless`) is defined for vectors:

```julia
julia> isless([1,2], [2,1])
true
```

```julia
File: base/abstractarray.jl
1674: function cmp(A::AbstractVector, B::AbstractVector)
1675:     for (a, b) in zip(A, B)
1676:         if !isequal(a, b)
1677:             return isless(a, b) ? -1 : 1
1678:         end
1679:     end
1680:     return cmp(length(A), length(B))
1681: end
```
