### ISSUE TITLE
Compilation failed on ppc64

### ISSUE THREAD

**Issue by Albert65** [JuliaLang/julia#16053]
#Hi All, I have to reiterate the previous issue 16036.
I am compiling Julia 0.4.5 on Power8, Redhat 7.2/64-bit. My "Make.user" file:

prefix=${SOFT}/julia   # <-- custom destination folder, SOFT is defined in .bashrc
include $(JULIAHOME)/Make.powerpc

My system is equipped with "pcre" library while Julia needs "pcre2". I manually compiled and installed "pcre2" in the custom directory ${SOFT} (PATH, LD_LIBRARY_PATH, etc. were modified accordingly). 
The source code was pulled from the GitHub as suggested. LLVM 3.7.1 is used for now. The problem happens near the same step as before (issue 16036) but it is different:

/home/albert/tmp/julia/src/ccall.cpp:127:4: warning: #warning is a GCC extension [enabled by default]
 #  warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination"
    ^
/home/albert/tmp/julia/src/ccall.cpp:127:4: warning: #warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination" [-Wcpp]
    CC src/disasm.o
    CC src/debuginfo.o
    CC src/llvm-simdloop.o
    CC src/llvm-gcroot.o
    LINK usr/lib/libjulia.so
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Warning: File `../src/julia_version.h' has modification time 84 s in the future
    CC ui/repl.o
    LINK usr/bin/julia
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/man/man1/julia.1
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/fenv_constants.jl
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
Copying in usr/share/doc/julia/examples
    JULIA usr/lib/julia/inference.ji
julia: /home/albert/tmp/julia/deps/srccache/llvm-3.7.1/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::MCSymbolELF; Y = llvm::MCSymbol; typename llvm::cast_retty<X, Y*>::ret_type = llvm::MCSymbolELF*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
/bin/sh: line 1: 196533 Aborted                 (core dumped) /home/albert/tmp/julia/usr/bin/julia -C native --output-ji /home/albert/tmp/julia/usr/lib/julia/inference.ji -f coreimg.jl
make[1]: *** [/home/albert/tmp/julia/usr/lib/julia/inference.ji] Error 134
make: *** [julia-inference] Error 2

**Comment by ViralBShah** [comment]
Hi @Albert65. You can just reopen your older issue. Closing this as a dup of #16036, which is reopened.
