### ISSUE TITLE
NTuple zero-initialization performance

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#16064]
While trying to mirror the [`ogg_stream_state` struct from `libogg`](https://xiph.org/ogg/doc/libogg/ogg_stream_state.html), I picked up the hint from @quinnj to use `NTuple{282,Uint8}` to represent the `unsigned char header[282]` field.  When trying this out, however, I have found that this absolutely murders something in the compilation process.  Given `ntuple.jl`:

```julia
immutable OggStreamState
    # Pointer to data from packet bodies
    body_data::Ptr{UInt8}
    # Storage allocated for bodies in bytes (filled or unfilled)
    body_storage::Clong
    # Amount of storage filled with stored packet bodies
    body_fill::Clong
    # Number of elements returned from storage
    body_returned::Clong

    # String of lacing values for the packet segments within the current page
    # Each value is a byte, indicating packet segment length
    lacing_vals::Ptr{Cint}
    # Pointer to the lacing values for the packet segments within the current page
    granule_vals::Int64
    # Total amount of storage (in bytes) allocated for storing lacing values
    lacing_storage::Clong
    # Fill marker for the current vs. total allocated storage of lacing values for the page
    lacing_fill::Clong
    # Lacing value for current packet segment
    lacing_packet::Clong
    # Number of lacing values returned from lacing_storage
    lacing_returned::Clong

    # Temporary storage for page header during encode process, while the header is being created
    header::NTuple{282,UInt8}
    # Fill marker for header storage allocation. Used during the header creation process
    header_fill::Cint

    # Marker set when the last packet of the logical bitstream has been buffered
    e_o_s::Cint
    # Marker set after we have written the first page in the logical bitstream
    b_o_s::Cint
    # Serial number of this logical bitstream
    serialno::Clong
    # Number of the current page within the stream
    pageno::Cint
    # Number of the current packet
    packetno::Int64
    # Exact position of decoding/encoding process
    granulepos::Int64

    OggStreamState() = new(0,0,0,0,C_NULL,0,0,0,0,0,ntuple(x->0,282),0,0,0,0,0,0,0)
end

@time OggStreamState()
@time OggStreamState()
```

I get the timings:
```
$ julia ntuple.jl
 26.630638 seconds (3.11 M allocations: 165.694 MB, 0.42% gc time)
  0.001948 seconds (927 allocations: 439.891 KB)
```

My guess is that `NTuple` types weren't meant for such large values of `N`, but that is somewhat disappointing.  Lines such as [this](https://github.com/JuliaLang/julia/blob/04f3a78a75adc6c4dc3391504bf6bf9c21b744e7/base/tuple.jl#L57-L64) give me some small idea as to why this is so, but I don't know of any other way to do this neatly, other than just filling up the equivalent space with `UInt8`'s  (or `UInt64`'s if I want to save my fingers, I suppose).

**Comment by vtjnash** [comment]
dup of https://github.com/JuliaLang/julia/issues/15695

**Comment by vtjnash** [comment]
one option is to initialize with `([0 for i = 1:282]...)` to avoid the cost of calling the NTuple constructor

**Comment by staticfloat** [comment]
I tried that, and got `ERROR: syntax: ... is not supported inside "new"`.  Yet another case where I don't fully understand the difference between inner and outer constructors I suppose.

I moved `OggStreamState()` out into an outer constructor, and that does seem to help quite a bit, although it's still slower than I would expect:

```julia
OggStreamState() = OggStreamState(0,0,0,0,C_NULL,0,0,0,0,0,(UInt8[0 for i in 1:282]...),0,0,0,0,0,0,0)
```

```
6.222094 seconds (877.34 k allocations: 52.034 MB, 0.51% gc time)
0.000130 seconds (15 allocations: 9.844 KB)
```

**Comment by timholy** [comment]
Since tuples are immutable, can't you do
```
const nt282 = (zeros(UInt8, 282)...)
```
and then use it to initialize every new `OggStreamState`? That, plus package precompilation, seems likely to be effective.

**Comment by nalimilan** [comment]
> I tried that, and got ERROR: syntax: ... is not supported inside "new". Yet another case where I don't fully understand the difference between inner and outer constructors I suppose.

Looks like the parser confuses splatting with varargs syntax. Care to file an issue?

**Comment by staticfloat** [comment]
I like your style @timholy, even though I wish it weren't necessary.  :)

@nalimilan https://github.com/JuliaLang/julia/issues/16079

**Comment by vtjnash** [comment]
looking at this again, it's related to #15695, but the problem is with the definition of convert in this case:
```julia
essentials.jl
 68 convert{T<:Tuple{Any,Vararg{Any}}}(::Type{T}, x::Tuple{Any, Vararg{Any}}) =
 69     tuple(convert(tuple_type_head(T),x[1]), convert(tuple_type_tail(T), tail(x))...)
```
