### ISSUE TITLE
Updating a dense vector by a column of sparse matrix is slow

### ISSUE THREAD

**Issue by cedeerwe** [JuliaLang/julia#16069]
I am trying to tackle this problem for a long time now, and there really seems to be an issue. As a subroutine in my method, I need to add a multiple of a column of a sparse matrix to a vector. 

In the following simple test code I will do this operation with every column, to showcase the average behaviour.
```
n = 10000
A = sprand(n,n,0.01)
w = rand(n)
@time for i=1:n
  w += A[:,i]
end
0.260738 seconds (148.47 k allocations: 1.511 GB, 17.83% gc time)
```
Seems like a reasonable time, until we compare it to taking the same amount of inner products, which should take ~ the same time according to the sparse matrix theory
```
@time for i=1:n
  A[:,i]'*w
end
0.013407 seconds (108.47 k allocations: 21.167 MB, 18.72% gc time)`
```
Now we see, that it is actually quite slow. I looked for the BLAS function axpy, which should do exactly this operation. It is implemented for sparse vectors, so I tested it out.
```
@time for i=1:n
  LinAlg.axpy!(1,A[:,i],w)
end
2.813774 seconds (128.47 k allocations: 38.695 MB, 0.10% gc time)
```
That is even slower. So I made my own implementation of this operation in the function upd!(w,A,i,c), which updates w by a c-multiple of the i-th column of A:
```
function upd!(w,A,i,c)
  for j=A.colptr[i]:A.colptr[i+1]-1
    w[A.rowval[j]] += A.nzval[j]*c
  end
  return w
end
```
The implementation is very basic, with no optimization. However, running this code is way faster.
```
@time for i=1:n
  upd!(w,A,i,1)
end
0.003673 seconds (28.98 k allocations: 609.078 KB)
```
There should not be such a difference. I believe there is an issue somewhere, but cannot figure out where. Maybe there is a function, which does this correctly, but after couple of days I could not find it. Am I missing something?

**Comment by KristofferC** [comment]
I get:

```jl
@time for i=1:n
    LinAlg.axpy!(1.0, A[:,i],w)
end
  0.010930 seconds (58.98 k allocations: 18.645 MB)
```

The overhead compared to your function is that the command `A[:,i]` copies data to create a new `SparseVector`.

Why your first example is slow: `A[:,i]` creates a sparse vector, which then calls this function https://github.com/JuliaLang/julia/blob/1d7abfe38c25896ac4fcabf35a36abeb32b2e0bd/base/sparse/sparsevector.jl#L999 to do the update. This function could be optimized further for some `f` to not be O(n).

**Comment by cedeerwe** [comment]
@KristofferC I don't understand what is the difference between our two codes using axpy. They seem to be exactly the same.

If the overhead is in creating a new `SparseVector`, is there any way to avoid it without creating my own method?

**Comment by KristofferC** [comment]
Maybe you didn't run the code twice and you accidentally measured compilation time?

If you want a non allocating version this is probably the fastest you will get

```jl

function upd!(w,A,i,c)
   # Because SparseMatrixCSC is not an immutable, hoisting the field loads will improve performance
    rowval = A.rowval
    nzval = A.nzval
    @inbounds for j = nzrange(A, i)
        w[rowval[j]] += c * nzval[j]
    end
    return w
end

function test(A, n, w)
    @time for i = 1:n
      upd!(w, A, i, 1)
    end
end

n = 10000
A = sprand(n,n,0.01)
w = rand(n)

julia> test(A, n, w)
  0.002577 seconds
```

**Comment by cedeerwe** [comment]
I run the code multiple times, with the same performance. So I don't know what can be the issue.

So the bottom line is, that there is no good function in the base for updating dense vectors by columns of sparse matrices. The code you mentioned is probably the best we I can get, and that's the way to go.

Thanks.

**Comment by KristofferC** [comment]
Sorry, I have been running stuff on julia 0.5 where the situation is a bit different. The sparse vector functionality only came in julia v0.4 and you are right that axpy seems to be slow on v0.4. However, what I said still apply, your original function will create a copy and thus be slow.

**Comment by cedeerwe** [comment]
Makes sense, thanks!

**Comment by tomaklutfu** [comment]
Also, `w` is allocated for each loop for the first test( `w += A[:,i]` means `w = w+A[:,i]` thus 2 allocations one for result of `+` and one for `A[:,i]`).
