### ISSUE TITLE
sign of LinSpace/UnitRange

### ISSUE THREAD

**Issue by mzaffalon** [JuliaLang/julia#16067]
On Julia 0.4.5, `sign` is not defined for `LinSpace` and `UnitRange`.

```
julia> sign(-1:1)
ERROR: MethodError: `sign` has no method matching sign(::UnitRange{Int64})

julia> sign(collect(-1:1))
5-element Array{Int64,1}:
-1
0
1

julia> sign(linspace(-1,1,3))
ERROR: MethodError: `sign` has no method matching sign(::LinSpace{Float64})
```

**Comment by nalimilan** [comment]
This works on git master. It's been fixed by @timholy in 57c53afba29a06493a2d993fb571a992d0ad733a by making the signature less restrictive (form `StridedArray` to `AbstractArray`).

I wonder whether this would be safe to backport or not. At least, that precise part of the patch should be OK.

**Comment by timholy** [comment]
Probably not safe to backport the whole thing, see #14725. The reworking of `permutedims` also interacts with #15814, and that certainly should not be backported.

**Comment by nalimilan** [comment]
I've made a PR with the minimal backport at https://github.com/JuliaLang/julia/pull/16121.

**Comment by KristofferC** [comment]
This is fixed and tested.
