### ISSUE TITLE
Missing error for invalid loop declaration

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#16075]
The following would be great to capture in some kind of error

``` jl
julia> r = ones(1,1)
1x1 Array{Float64,2}:
 1.0

julia> for r(i) = b(prow(i))
       end

julia> r
svec()
```

This came up in code translated from Matlab

``` jl
for i = 1:m,
    r(i) = b(prow(i)); 
end
```

where removing the comma gives a reasonable error message. I think I've seen a similar issue with our fancy nested loop syntax before.

Update: This is on 0.4. It gives an error in 0.5. Would it be possible to fix easily on 0.4?

**Comment by JeffBezanson** [comment]
It looks like this needs a more specific syntax error, on 0.5 as well.

**Comment by JeffBezanson** [comment]
I believe this is superseded by #22167.
