### ISSUE TITLE
Splatting in Expr(:new)

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#16079]
Splatting doesn't work inside of internal constructors, @nalimilan thinks this is because it is getting confused for varargs syntax?  Or is this by design?

```julia
# splatting.jl
type foo
    x::UInt8
    y::Int16
    z::Int64

    foo() = new([0 for i in 1:3]...)
end
```

```
$ julia splatting.jl
ERROR: LoadError: syntax: ... is not supported inside "new"
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
while loading /Users/sabae/splatting.jl, in expression starting on line 8
```

**Comment by JeffBezanson** [comment]
Say what you will about our error messages in general, I think this one is pretty clear. `...` is not supported inside `new` because `...` requires passing a function to `_apply`, and `new` is not a first-class function so we can't do it.

**Comment by staticfloat** [comment]
Ah, I was following @nalimilan's suggestion, but looks like the error message is exactly what it's meant to be!  Thanks @JeffBezanson.

**Comment by nalimilan** [comment]
So my interpretation was wrong, sorry for the noise.
