### ISSUE TITLE
Compilation failed - Julia 0.4.5 i586

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#16087]
Hi guys!

Today, I noticed that julia was not building againt i586 on openSUSE servers. It is only happening at openSUSE Factory i586. It builds fine in openSUSE Tumbleweed i586. My best guess is that some package was updated and added an incompatibility with julia 0.4.5, but I have no idea which one could cause the problem.

The entire build log can be seen here: http://pastebin.com/yzefpSqt

The error is described next:

```
[  132s] llvm[4]: ======= Finished Linking Release Executable llvm-tblgen (without symbols)
[  132s] make[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/utils/TableGen'
[  132s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/utils'
[  132s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR'
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release > /dev/null
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/include/llvm/IR > /dev/null
[  132s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/.dir
[  132s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/include/llvm/IR/.dir
[  132s] llvm[3]: Building Intrinsics.gen.tmp from Intrinsics.td
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/Release/bin/llvm-tblgen -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/lib/IR -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/lib/Target  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/include/llvm/IR/Intrinsics.td -o  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp -gen-intrinsic
[  132s] Makefile:23: recipe for target '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp' failed
[  132s] make[3]: *** [/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp] Segmentation fault
[  132s] make[3]: *** Deleting file '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR/Release/Intrinsics.gen.tmp'
[  132s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release/lib/IR'
[  132s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/Makefile.rules:866: recipe for target 'all' failed
[  132s] make[2]: *** [all] Error 1
[  132s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.3/build_Release'
[  132s] Makefile:670: recipe for target 'llvm-3.3/build_Release/Release/lib/libLLVMCodeGen.a' failed
[  132s] make[1]: *** [llvm-3.3/build_Release/Release/lib/libLLVMCodeGen.a] Error 2
[  132s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps'
[  132s] Makefile:51: recipe for target 'julia-deps' failed
[  132s] make: *** [julia-deps] Error 2
```

The build flags are:

```
USE_SYSTEM_LLVM=0 \
USE_SYSTEM_LIBUNWIND=1 \
USE_SYSTEM_READLINE=1 \
USE_SYSTEM_PCRE=1 \
USE_SYSTEM_LIBM=0 \
USE_SYSTEM_OPENLIBM=1 \
USE_SYSTEM_OPENSPECFUN=1 \
USE_SYSTEM_DSFMT=1 \
USE_SYSTEM_BLAS=1 \
LIBBLASNAME=libblas.so.3 \
USE_SYSTEM_LAPACK=1 \
LIBBLASNAME=liblapack.so.3 \
USE_SYSTEM_FFTW=1 \
LIBFFTWNAME=libfftw3_threads.so.3 \
LIBFFTWFNAME=libfftw3f_threads.so.3 \
USE_SYSTEM_GMP=1 \
USE_SYSTEM_MPFR=1 \
USE_SYSTEM_ARPACK=1 \
USE_SYSTEM_SUITESPARSE=1 \
USE_SYSTEM_ZLIB=1 \
USE_SYSTEM_GRISU=1 \
USE_SYSTEM_RMATH=0 \
USE_SYSTEM_LIBUV=0 \
USE_SYSTEM_UTF8PROC=0 \
USE_SYSTEM_PATCHELF=1 \
USE_SYSTEM_LIBGIT2=1 \
USE_MKL=0 \
USE_BLAS64=0 \
USE_LLVM_SHLIB=0 \
VERBOSE=1 \
USECLANG=0
```

Does anyone have any idea?

Regards,
Ronan

**Comment by ronisbr** [comment]
By the way, this is the output of diff between the packages used to build julia in Factory and in Tumbleweed:

```
--- factory	2016-04-27 23:44:26.625113876 -0300
+++ tumbleweed	2016-04-27 23:44:09.301014052 -0300
@@ -8,12 +8,12 @@
 brp-check-suse-13.2+git20150521.971ea2f
 brp-extract-appdata-2012.02.13
 build-compare-20160406T155640.b74db7f
-build-mkbaselibs-20160331
+build-mkbaselibs-20160304
 bzip2-1.0.6
 coreutils-8.25
 cpio-2.12
 cpp-5
-cpp5-5.3.1+r234891
+cpp5-5.3.1+r233831
 cracklib-2.9.5
 dSFMT-devel-2.2.3
 desktop-file-utils-0.22
@@ -31,14 +31,14 @@
 gcc-5
 gcc-c++-5
 gcc-fortran-5
-gcc5-5.3.1+r234891
-gcc5-c++-5.3.1+r234891
-gcc5-fortran-5.3.1+r234891
+gcc5-5.3.1+r233831
+gcc5-c++-5.3.1+r233831
+gcc5-fortran-5.3.1+r233831
 gettext-runtime-mini-0.19.6
 gettext-tools-mini-0.19.6
-glibc-2.23
-glibc-devel-2.23
-glibc-locale-2.23
+glibc-2.22
+glibc-devel-2.22
+glibc-locale-2.22
 gmp-devel-6.1.0
 grep-2.22
 gzip-1.7
@@ -53,8 +53,8 @@
 libacl1-2.2.52
 libamd-2_4_1-2.4.1
 libarpack2-3.2.0
-libasan2-5.3.1+r234891
-libatomic1-5.3.1+r234891
+libasan2-5.3.1+r233831
+libatomic1-5.3.1+r233831
 libattr1-2.4.47
 libaudit1-2.5
 libblas3-3.5.0
@@ -66,7 +66,7 @@
 libcap2-2.22
 libccolamd-2_9_1-2.9.1
 libcholmod-3_0_6-3.0.6
-libcilkrts5-5.3.1+r234891
+libcilkrts5-5.3.1+r233831
 libcolamd-2_9_1-2.9.1
 libcom_err2-1.42.13
 libcrack2-2.9.5
@@ -80,21 +80,21 @@
 libfdisk1-2.28
 libfftw3-3-3.3.4
 libfftw3_threads3-3.3.4
-libgcc_s1-5.3.1+r234891
+libgcc_s1-5.3.1+r233831
 libgdbm4-1.11
-libgfortran3-5.3.1+r234891
+libgfortran3-5.3.1+r233831
 libgit2-24-0.24.0
 libgit2-devel-0.24.0
 libglib-2_0-0-2.48.0
 libgmp10-6.1.0
 libgmpxx4-6.1.0
-libgomp1-5.3.1+r234891
+libgomp1-5.3.1+r233831
 libhttp-parser-suse0-2.6.2
 libicu57_1-57.1
 libicu57_1-ledata-57.1
 libidn11-1.32
 libisl15-0.16.1
-libitm1-5.3.1+r234891
+libitm1-5.3.1+r233831
 libkeyutils1-1.5.9
 libklu-1_3_3-1.3.3
 liblapack3-3.5.0
@@ -106,8 +106,8 @@
 libmount1-2.28
 libmpc3-1.0.3
 libmpfr4-3.1.4
-libmpx0-5.3.1+r234891
-libmpxwrappers0-5.3.1+r234891
+libmpx0-5.3.1+r233831
+libmpxwrappers0-5.3.1+r233831
 libncurses5-6.0
 libncurses6-6.0
 libnghttp2-14-1.9.1
@@ -123,7 +123,7 @@
 libpopt0-1.16
 libpsl5-0.13.0
 libpython2_7-1_0-2.7.10
-libquadmath0-5.3.1+r234891
+libquadmath0-5.3.1+r233831
 librbio-2_2_1-2.2.1
 libreadline6-6.3
 libsasl2-3-2.1.26
@@ -134,10 +134,10 @@
 libsqlite3-0-3.12.1
 libssh2-1-1.7.0
 libstdc++-devel-5
-libstdc++6-5.3.1+r234891
-libstdc++6-devel-gcc5-5.3.1+r234891
+libstdc++6-5.3.1+r233831
+libstdc++6-devel-gcc5-5.3.1+r233831
 libsuitesparseconfig-4_4_6-4.4.6
-libubsan0-5.3.1+r234891
+libubsan0-5.3.1+r233831
 libumfpack-5_7_1-5.7.1
 libunwind-1.1
 libunwind-devel-1.1
```

**Comment by ronisbr** [comment]
The only packages that suffer a minor version change were:

* build-mkbaselibs (20160304 -> 20160331)
* glibc (2.22 -> 2.23)

Can anyone one of these two explain the reported behavior?

**Comment by vtjnash** [comment]
it failed while building llvm, so you might want to file this upstream. regardless, I think we've seen something similar when gcc miscompiles llvm.

**Comment by ronisbr** [comment]
@vtjnash thanks for the answer. I have triggered a rebuild many times and always with the same error. The environment used to build this in Factory and Tumbleweed are almost the same except for minor differences. I am really out of ideas here.

**Comment by vtjnash** [comment]
just from a quick google, it looks like glibc 2.22 and glibc 2.23 are incompatible. is there a chance something was not rebuilt on the system when switching from one to the other?

**Comment by ronisbr** [comment]
@vtjnash I thought about it, but it was failing since today in the morning. I think that there was enough time to rebuild everything. But, since you mentioned, I will wait until tomorrow. Maybe the servers are too busy. However, AFAIK there should be mechanisms to block packages until everything is rebuilt in these cases.

In the mean time, I reported to upstream: https://llvm.org/bugs/show_bug.cgi?id=27548

Thank you for the prompt answer!

**Comment by ronisbr** [comment]
I could pass the llvm build process. However, after that, I saw this other problem:

```
make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/src'
 gcc -m32  -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -DLIBRARY_EXPORTS -I. -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.so\"" -DNDEBUG -c jltypes.c -o jltypes.o
 gcc -m32  -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -ggdb3 -falign-functions -momit-leaf-frame-pointer -D_GNU_SOURCE -Iflisp -Isupport -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -DLIBRARY_EXPORTS -I. -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.so\"" -DNDEBUG -c gf.c -o gf.o
 ./flisp/flisp ./mk_julia_flisp_boot.scm
fatal error:
(io-error "file: could not open \"flisp.boot\"")
Makefile:97: recipe for target 'julia_flisp.boot' failed
make[1]: *** [julia_flisp.boot] Error 1
```

**Comment by ronisbr** [comment]
I'm running out of options. I think I will have to drop the support to i586 arch until julia 0.5 is released. However, can anyone tell me if it is possible to upgrade llvm 3.3 in julia 0.4.5?

**Comment by tkelman** [comment]
Are you building both release and debug versions simultaneously in parallel? There had been some makefile race conditions that maybe didn't have all fixes backported. I think the Fedora packages have been working on 32 bit without too much trouble, so maybe compare your spec files. It is possible to use newer LLVM on release-0.4 but it's not recommended as it's going to be much slower, especially on 32 bit.

**Comment by ronisbr** [comment]
@tkelman no, I'm building release and debug separately. Also, it is working for Tumbleweed that has glibc 2.22. Now, I could not build for Factory, which will make julia i586 unavailable in newer Tumbleweed snapshots. I'm thinking to update llvm only for 32-bit builds. Is there any documentation about it (update llvm in julia)?

**Comment by tkelman** [comment]
Is this a context where you're allowed to download tarballs and vendor things? If so then set `LLVM_VER=3.7.1` (that version has been well-tested on master for a few months, though many of the codegen changes were not backported to 0.4). If not, try `USE_SYSTEM_LLVM=1` against whatever's available.

**Comment by ronisbr** [comment]
@tkelman no, unfortunately I'm not allowed to download any package in the build server farm. However, I'm can download the llvm version and put in the right directory before the build process start. Now, openSUSE has llvm 3.8 and I could not build julia against it. I think I tried to use julia 0.4. together with llvm 3.7.1 without success sometimes ago. I'll try again to see if anything has changed. Thanks!

**Comment by ronisbr** [comment]
Something strange: I update to llvm 3.7.1 and I'm getting the same error. But now I have a little more information:

```
[   68s] llvm[4]: ======= Finished Linking Release Executable llvm-tblgen (without symbols)
[   68s] make[4]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/utils/TableGen'
[   68s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/utils'
[   68s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR'
[   68s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release > /dev/null
[   68s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/include/llvm/IR > /dev/null
[   68s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/autoconf/mkinstalldirs /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/./ > /dev/null
[   68s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/.//.dir
[   68s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/.dir
[   68s] echo 'Created.' > /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/include/llvm/IR/.dir
[   68s] llvm[3]: Building Intrinsics.gen.tmp from Intrinsics.td
[   68s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/Release/bin/llvm-tblgen -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/lib/IR -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/include -I  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/lib/Target  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/include/llvm/IR/Intrinsics.td -o  /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/Intrinsics.gen.tmp -gen-intrinsic
[   68s] llvm-tblgen: cxa_atexit.c:100: __new_exitfn: Assertion `l != NULL' failed.
[   68s] Makefile:23: recipe for target '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/Intrinsics.gen.tmp' failed
[   68s] make[3]: *** [/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/Intrinsics.gen.tmp] Aborted (core dumped)
[   68s] make[3]: *** Deleting file '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR/Release/Intrinsics.gen.tmp'
[   68s] make[3]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release/lib/IR'
[   68s] /home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/Makefile.rules:880: recipe for target 'all' failed
[   68s] make[2]: *** [all] Error 1
[   68s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/llvm-3.7.1/build_Release'
[   68s] Makefile:670: recipe for target 'llvm-3.7.1/build_Release/Release/lib/libLLVMCodeGen.a' failed
[   68s] make[1]: *** [llvm-3.7.1/build_Release/Release/lib/libLLVMCodeGen.a] Error 2
[   68s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps'
[   68s] Makefile:51: recipe for target 'julia-deps' failed
[   68s] make: *** [julia-deps] Error 2
[   68s] error: Bad exit status from /var/tmp/rpm-tmp.NGgAHD (%build)
```

Again, it is only happening in i586 with glibc 2.23.

**Comment by tkelman** [comment]
Well hey, at least you can get fewer eyebrows on your LLVM bug report then.

**Comment by ronisbr** [comment]
:D yes!

**Comment by tkelman** [comment]
@nalimilan has Fedora been as fast at upgrading to glibc 2.23? Or have they dropped 32 bit builds?

**Comment by ronisbr** [comment]
@tkelman I saw a bug report in RedHat about it:
https://bugzilla.redhat.com/show_bug.cgi?id=1283284

Exactly the same problem! 32-bit after upgrade to glibc 2.23

**Comment by nalimilan** [comment]
@ronisbr Note that the Fedora report is about "32-bit s390", not i586.Though it could indeed be the same issue.

I've built LLVM 3.3 and 3.8 without problems in the latest Fedora on i686 with glibc 2.23.1. But Fedora uses i686 and gcc 6, while you're using i586 and gcc 5.5. glibc and gcc seem to be strongly tied, so that could explain the difference (see e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1302825).

You could also have a look at what build flags the standard LLVM OpenSuSE package uses. The Fedora .spec file is here: http://pkgs.fedoraproject.org/cgit/rpms/llvm.git/tree/llvm.spec and an example of output (to see the flags) is here: https://kojipkgs.fedoraproject.org//packages/llvm/3.8.0/1.fc25/data/logs/i686/build.log

**Comment by ronisbr** [comment]
Thanks for the tip @nalimilan, but now things got really weird.
I tried to build llvm 3.3 against openSUSE Factory i586 (glibc 2.23) and everything worked perfeclty as it can be seen here:

* https://build.opensuse.org/package/show/home:Ronis_BR/llvm-3_3
* https://build.opensuse.org/build/home:Ronis_BR/openSUSE_Factory/i586/llvm-3_3/_log

I think the same will happen with llvm 3.7.1. Thus, now, I don't know if the problem is related to an upstream bug or a julia bug, since llvm build process is failing when it is being built together with julia. 

I'm thinking that this can be related to the `-march=pentium4` in Julia i586, but I'm not sure. Can anyone help me track down this problem?

**Comment by tkelman** [comment]
I have an opensuse partition I could boot into if it helps (not 32 bit though), what's the quickest way to reproduce? Can you build Julia against your separate-build LLVM package? I think that's what Milan does in his Fedora builds. Another option would be trying to tweak the flag application so LLVM does not get built with `-march=pentium4` but Julia (and openlibm etc) does. That's mainly to avoid x87 instructions since not all of our tests pass if some of the deps or Julia itself try to use them.

**Comment by ronisbr** [comment]
@tkelman you don't need 32-bit openSUSE, since it is possible to use `osc` to clone my repo and build it locally. I think you will need something like that:

```
osc co home:Ronis_BR julia
cd home:Ronis_BR/julia
osc build --root=`pwd`/jail openSUSE_Factory i586
```

Then, `osc` will create a chroot with the build environment.

Now, I'll try to build julia against this llvm that I created.

**Comment by ronisbr** [comment]
I tried to build julia using `-march=prescott`, `-march=i686`, and `-march=i586` to build LLVM 3.3 but every time the build fails with the same error.

**Comment by ronisbr** [comment]
Building julia with external llvm 3.3 gave me a very strange error. The build log is here: https://build.opensuse.org/build/home:Ronis_BR:branches:home:Ronis_BR/openSUSE_Factory/i586/julia/_log

The error seems to be this:

```
[   78s]  clang-3.3 -march=pentium4 -m32  -DSYSTEM_LLVM -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DCOPY_STACKS -O3 -g -D_GNU_SOURCE -Iflisp -Isupport -I/usr/include/llvm-3_3 -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/usr/include -DLIBRARY_EXPORTS -I. -I/home/abuild/rpmbuild/BUILD/julia-0.4.5/deps/valgrind -Wall -Wno-strict-aliasing -fno-omit-frame-pointer -fvisibility=hidden -fno-common "-DJL_SYSTEM_IMAGE_PATH=\"../lib/julia/sys.so\"" -DNDEBUG -c dump.c -o dump.o
[   78s] task.c:361:17: error: invalid operand in inline asm: ' movl $0, %esp;
[   78s]  xorl %ebp, %ebp;
[   78s]  push %ebp;
[   78s]  jmp ${1:P};
[   78s]  ud2'
[   78s]             asm(" movl %0, %%esp;\n"
[   78s]                 ^
[   78s] task.c:361:17: error: invalid operand in inline asm: ' movl $0, %esp;
[   78s]  xorl %ebp, %ebp;
[   78s]  push %ebp;
[   78s]  jmp ${1:P};
[   78s]  ud2'
[   78s] task.c:361:17: error: unknown token in expression
[   78s] <inline asm>:1:8: note: instantiated into assembly here
[   78s]          movl , %esp;
[   78s]               ^
[   78s] task.c:364:18: error: unknown use of instruction mnemonic without a size suffix
[   78s]                 " jmp %P1;\n" // call stack_task with fake stack frame
[   78s]                  ^
[   78s] <inline asm>:4:2: note: instantiated into assembly here
[   78s]  jmp ;
[   78s]  ^
```

**Comment by nalimilan** [comment]
(Note the direct links to the logs don't work unless you're logged into OBS.)

The LLVM 3.3 .spec file contains a lot of flags and patches. So it's hard to know which one exactly makes a difference. One thing I noted is that it hardcodes i586 in several places, so maybe this conflicts with pentium4. Have you tried building Julia with `USE_SYSTEM_LLVM=1` an `MARCH=i586`? Also, I noticed you set `USECLANG=1`; does it fail with gcc too?

Other than that, I guess you'll have to apply as much as possible the flags and patches from the .spec file to Julia's LLVM until it builds. The reverse strategy could also be used: remove custom settings from the .spec file (in particular, remove references to `i586`) until you get the same error.

**Comment by ronisbr** [comment]
@nalimilan Sorry about that.
I just tried with the options you gave me and I got the same error of my last comment.

**Comment by ronisbr** [comment]
Well, thanks guys! I will keep trying to fix the problem but it will take much more effort than I am capable to provide now. Thus, as of now, I'm dropping the support for i586 from julia in openSUSE. Notice that even julia-git could not be built against i586 using the new glibc 2.23. I tried all combinations possible, every time with a different error.

**Comment by tkelman** [comment]
Does opensuse give you download statistics? 32 bit Linux is much less used than 64 bit, and even opensuse doesn't do a 32 bit build at all for the stable Leap version. There's a bug somewhere here that it might be good to track down, but don't waste more time on it than your curiosity motivates you to.

**Comment by ronisbr** [comment]
@tkelman I think the same way. Thank you very much for all the attention!

**Comment by ronisbr** [comment]
The thread I opened in openSUSE-factory mailing list describing the problem as asking for help:
https://lists.opensuse.org/opensuse-factory/2016-04/msg00559.html

**Comment by ronisbr** [comment]
Hi guys!

For some strange, unexplainable, weird reason, julia started to build correctly for i586 (https://build.opensuse.org/package/show/home:Ronis_BR/julia-unstable). I have no idea what changed. What I know for sure is that the code, the patches, the building commands, etc. stayed the same.

Thus, my only logical conclusion is that something was rebuilt or updated in openSUSE server farm and fixed the problem. Anyway, it was not LLVM or julia fault, but some problem in openSUSE itself.

Thanks for all the help! I'm closing this issue.

**Comment by tkelman** [comment]
Can't complain when an issue resolves itself without us doing anything. Strange one, whatever it was.
