### ISSUE TITLE
Extra space in @sprintf("%.6g", 1.0)

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#16099]
The space at the end here seems to be a bug:
```
julia> @sprintf("%.6g", 1.0)
"1 "
```

**Comment by dpsanders** [comment]
Fixed on 0.5; sorry for the noise.

**Comment by StefanKarpinski** [comment]
Probably should be backported though.

**Comment by tkelman** [comment]
If not too disruptive. Blame or bisect to identify what the fix was?

**Comment by tkelman** [comment]
if anyone identifies the fix for this we can put the backport pending label back there - will need to happen soon to make 0.4.7 which might be the last 0.4 release though

**Comment by garrison** [comment]
This is a duplicate of #14331; ddd0f05 seems (on the surface) to be the commit that fixed it.

**Comment by tkelman** [comment]
Thanks. Closing and moving the backport label to https://github.com/JuliaLang/julia/pull/14348 then. If we make an 0.4.8 we can test it then.
