### ISSUE TITLE
DictChannel not defined error

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#16091]
Happens once in a while, I think I may have caused this actually in https://github.com/JuliaLang/julia/pull/15263/files#diff-58423af65cdd8c791e6fad72e0524984 - but why would `myid()` sometimes not return the right thing? Or is there a race condition?

example cases: https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.792/job/sxyalbspyv27fcs2
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.776/job/jj6iyr4w22kdupi4
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.770/job/8ftjs48560jpbdh8
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.760/job/nm0icqna2eyrwpu8

**Comment by amitmurthy** [comment]
The change seems harmless.....I would suspect a race condition. Any recent changes to the code loading logic for Windows?

**Comment by amitmurthy** [comment]
Is there a way to search all AV logs under Julia for "LoadError: UndefVarError: DictChannel not defined" to find the earliest logged instance on this error?

**Comment by tkelman** [comment]
I believe so, there is an API reference at http://www.appveyor.com/docs/api/projects-builds though our history before we switched from the StefanKarpinski account to the JuliaLang account was unfortunately deleted.

**Comment by tkelman** [comment]
might have something to do with heavy load, it happened on an osx buildbot: https://build.julialang.org/builders/build_osx10.9-x64/builds/705/steps/shell_2/logs/stdio

**Comment by amitmurthy** [comment]
Unless code loading has an asynchronous part that completes after `include` returns, I don't see an obvious reason for this error to occur. I propose merging #16095 and seeing if it helps identify the cause.

**Comment by vtjnash** [comment]
I tried to queue a few more builds, but it looks like Appveyor's configuration is broken right now

**Comment by tkelman** [comment]
Doesn't include do something funny now in case the file gets modified while running? Nothing should be getting modified here but maybe the workaround for that is causing issues.

**Comment by vtjnash** [comment]
https://travis-ci.org/JuliaLang/julia/jobs/127403744

**Comment by tkelman** [comment]
should've merged #16095 a little earlier, that merge commit was on 0821d57 so just missed it

**Comment by vtjnash** [comment]
I suspect this may be caused by the same issue as https://github.com/JuliaLang/julia/issues/15923

**Comment by tkelman** [comment]
did you see this again? link?

**Comment by vtjnash** [comment]
yeah, locally

**Comment by tkelman** [comment]
@ranjanan saw this today in https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.3375/job/tjrdj3erbwok88bm, looks like the new form this can sometimes take is `MethodError: no method matching Base.Serializer.__deserialized_types__.##269()`

**Comment by vtjnash** [comment]
Ah, this error makes far more sense. The old bug is probably that this conditional is sometimes wrong:
https://github.com/JuliaLang/julia/blob/master/base/serialize.jl#L747-L752


And that this gensym isn't unique enough:
https://github.com/JuliaLang/julia/blob/master/base/serialize.jl#L753

**Comment by vtjnash** [comment]
Ah, this error makes far more sense. The old bug is probably that this conditional is sometimes wrong:
https://github.com/JuliaLang/julia/blob/master/base/serialize.jl#L747-L752

I spent a while trying to reproduce this, before I realized that Amit included a patch for this in https://github.com/JuliaLang/julia/blob/master/base/clusterserialize.jl#L32 which makes it far harder to trigger manually. This change was also my first thought to correct this, until I saw it was already being done that way and still failing.

Upon reflecting further, I realized this may only be half of the problem.

There seem to be a few candidates for the other half. For one, `deserialize_cycle` appears to be implemented incorrectly for TypeName (called too late), which could corrupt the backref list. For another, the assignment to `known_object_data` appears to also happen much too late, which might result in the creation of multiple TypeNames for a Type.

(A third issue, not encountered yet here due to the aforementioned bugs, but encountered previously by dump.c, the general deserializer for `DataType.types` could encounter instances of DataType before the call to jl_new_datatype, resulting in either the error `error("Expected object in cache. Not found.")` or equivalently, an Undef access of `typename.primary`)

**Comment by vtjnash** [comment]
Adding this to the milestone since it needs a breaking change to the serializer protocol.

Likely related recent examples seem to be very frequent:
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4553/job/rubplkx8t4n4ooxi
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4561/job/ra21j0b9fjsyyvi2
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4531/job/bddo5asxefy35fxi
https://travis-ci.org/JuliaLang/julia/jobs/146696497
https://travis-ci.org/JuliaLang/julia/jobs/146004988
https://travis-ci.org/JuliaLang/julia/jobs/145918553

**Comment by vtjnash** [comment]
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.4678/job/o2l19ya94nreab0j

min repro (in a fresh julia session):
```
julia> f = ()->1
(::#1) (generic function with 1 method)

julia> addprocs(1)
1-element Array{Int64,1}:
 2

julia> fetch(@spawnat 2 @eval f = ()->2)
(::#1) (generic function with 1 method)

julia> @spawnat 2 f()
Future(2,1,5,Nullable{Any}())

julia> fetch(ans) # should return 1
2
```

**Comment by amitmurthy** [comment]
This example is expected behavior. You have 2 different definitions for `f` on master and 2.

**Comment by JeffBezanson** [comment]
I think what's happening is that it tries to send over the local `f`, but the target machine sees it already has a function with the same name `#1` so uses that instead. This might be the wrong thing to do for anonymous functions in `Main`.

**Comment by vtjnash** [comment]
While I used the same variable name, note that these are anonymous functions, not the function `f`

**Comment by amitmurthy** [comment]
I don't understand, isn't `f` bound to two different functions on master and 2?

`@spawnat 2 f()` actually executes an anonymous function `()->f()` on 2, and it expects `f` to be already defined on 2, which it is.

**Comment by vtjnash** [comment]
Might be easier to see if you call them `f1` and `f2`

**Comment by JeffBezanson** [comment]
`@spawnat` captures `f` from its environment. This example is clearer:

```
julia> f()
1

julia> remotecall_fetch(x->x(), 2, f)
2
```

I tried to explicitly send my `f` to processor 2, and it didn't work.

**Comment by amitmurthy** [comment]
It is even more confusing now. 

On master:
```
julia> whos()
                          Base  36383 KB     Module
                          Core  12471 KB     Module
                          Main  43285 KB     Module
                           ans      0 bytes  Base.#whos
                            f1      0 bytes  ##1#2
```

On 2:
```
julia> 	From worker 2:	                          Base  34723 KB     Module
	From worker 2:	                          Core  12352 KB     Module
	From worker 2:	                          Main  41369 KB     Module
	From worker 2:	                            f2      0 bytes  ##1#2
```

How can `@spawnat 2 f1()` ever return 2? It seems like it is being evaluated locally. `remotecall_fetch` has the correct behavior.

```
remotecall_fetch(()->f1(), 2)
ERROR: On worker 2:
UndefVarError: f1 not defined
```

**Comment by amitmurthy** [comment]
OTOH 

```
julia> remotecall_fetch(f1, 2)
2
```

**Comment by amitmurthy** [comment]
> @spawnat captures f from its environment.

My understanding was that globals are not captured. Guess the behavior is different for functions vs data?

**Comment by vtjnash** [comment]
I posted the min repro after seeing what needs to be added to my PR to fix this. The conditional at https://github.com/JuliaLang/julia/pull/17619/files#diff-aec7b7bfc3115e923e4137ad38876951R741
should have the following corrected branch structure:
```
elseif mod !== __deserialized_types__ && mod !== Main
    @assert isdefined(mod, name)
    ...
else
    mod = __deserialized_types__
    ....
end

**Comment by JeffBezanson** [comment]
> My understanding was that globals are not captured.

```
julia> macroexpand(:(@spawnat 2 f()))
:((Base.spawnat)(2,(((f,)->(()->begin  # multi.jl, line 1658:
                    f()
                end)))(f)))
```

This behavior is a bit controversial though.

> should have the following corrected branch structure

+1, though I think there's a chance we should only exclude `Main` for anonymous functions.

**Comment by vtjnash** [comment]
Right. That brings up the other possibility, which is that the serializer should redirect them into `__deserialized_types__` instead of repeating the ishidden test in the deserializer. Any thoughts / preference?

**Comment by amitmurthy** [comment]
Ah! Just to reconfirm, this is due to `Base.localize_vars` localizing all variables, correct?

**Comment by JeffBezanson** [comment]
> this is due to Base.localize_vars localizing all variables, correct

Yes.

**Comment by JeffBezanson** [comment]
> serializer should redirect them into __deserialized_types__ instead of repeating the ishidden test in the deserializer

Sounds like either would work.
