### ISSUE TITLE
`esc` cannot be used in function arguments

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/julia#16096]
``` julia
module Foo
macro iter()
  quote
    @inline function Base.start(sub)
      it = 1
    end
  end
end
end
```

Macroexpanding `Foo.@iter` yields a function with an argument `Foo.sub` and a local `Foo.it`, both of which are broken.

In fewer cases (but still in this case) 0.4 also qualifies `sub`, but gensyms `it` correctly.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/10887

**Comment by MikeInnes** [comment]
Another issue is that without the inline macro it's not possible to escape function argument names. I don't think that's a regression though (I think I might have seen an issue for it somewhere).

**Comment by vtjnash** [comment]
looks like it's still broken / the fix broke something else: http://buildbot.e.ip.saba.us:8010/builders/perf_nanosoldier-x64/builds/201

**Comment by JeffBezanson** [comment]
I can reproduce that on 0.4:

```
julia> macro foo()
        quote
         function foo($(esc(:x)))
           x
         end
       end
       end

julia> @foo
ERROR: syntax: "(escape x)" is not a valid function argument name
```

Maybe there was some intermediate time where it worked on master.

**Comment by MikeInnes** [comment]
Also, I'm not able to escape the entire signature when using block syntax:

```julia
:($(:(f())) = 1) # works
:(function $(:(f())) 1 end) # syntax: expected "end" in definition of function "($ '(call f))"
```
