### ISSUE TITLE
`gradient()`: remove from Base, then deprecate

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16113]
`gradient(1:10)` doesn't work because it dispatches to a method that only takes `Array` arguments.

Also, `gradient` doesn't support multi-dimensional arrays, whereas in Matlab and NumPy it returns an N-tuple of the gradients along different directions.

cc: @andreasnoack, who looked at these functions in #5321.

**Comment by stevengj** [comment]
Also, the [current implementation](https://github.com/JuliaLang/julia/blob/e5139a7f5f06bf33e507ea4607e198c0fe975965/base/linalg/dense.jl#L107-L122) allocates a lot of temporary arrays.

**Comment by tkelman** [comment]
The presence of this function in base is pretty annoying from a JuliaOpt / AD perspective. Do we need to keep it here?

**Comment by andreasnoack** [comment]
The function has received almost no attention over the years. I only fixed a small obvious error reported in #5320 and have never really used it. The gradients I use are those that @tkelman mentions.

**Comment by johnmyleswhite** [comment]
I would love to see this function removed.

**Comment by stevengj** [comment]
I don't have strong opinions about this function; I know that it has a long lineage (e.g. it is in Matlab and NumPy), but I doubt I've used it more than a couple of times in my life.   However, it is useful for plotting purposes, e.g.  [for quick gradient plots in 2d](http://www.mathworks.com/help/matlab/ref/quiver.html) or plots of the slope of a curve.   That's probably why it exists.

**Comment by StefanKarpinski** [comment]
My vote: deprecate and leave as-is.

**Comment by kshyatt** [comment]
I added the decision label to this because it seems there's some controversy. Whichever way we decide it's still an intro issue but it seems like someone ought to decide.

**Comment by stevengj** [comment]
Seems like the clear consensus is to leave as-is and deprecate.

**Comment by tkelman** [comment]
Yep. Though usually when we deprecate things we suggest a replacement. So we should pick some package to migrate this to, and the package can go ahead and deal with the input types. If it's mostly used for plotting, Graphics.jl maybe?

**Comment by stevengj** [comment]
Graphics.jl is more about drawing than plotting, so I don't think it's appropriate.   It's not really clear to me that there is any package in common to all plotting, except maybe ColorTypes.jl, but `gradient` doesn't belong there.

There is a `gradient` function in FiniteDiff.jl by @johnmyleswhite, but I don't know if it has the same semantics.

**Comment by musmo** [comment]
curl is also a quick and dirty MATLAB function that has seen my use. Would these all appropriately fit in a special function package (even though they're not what one would typically regard as a special function)

**Comment by tkelman** [comment]
MatlabCompat or an independent VectorCalculus package could work. Most packages that do gradients mean the functional gradient rather than gradient vector fields.

**Comment by kmsquire** [comment]
FWIW, there is also a `gradient` function in `Images.jl`, which calculates the gradient vector field.  But the 1D version doesn't really fit there...
