### ISSUE TITLE
Build LLVM as shared library by default

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#16117]
In order for Cxx.jl to be usable on a default julia distribution we need to either ship LLVM as a shared library or re-export the LLVM symbols. Given historic opposition to doing the latter, I suggest doing the former.

**Comment by nalimilan** [comment]
FWIW, this is what the Fedora packages use since the beginning, and it doesn't seem to create any issues (that is, on i686 and x86_64 at least).

**Comment by tkelman** [comment]
We can test this out on a branch and see what CI and all the buildbots think of it.

**Comment by JeffBezanson** [comment]
The only downsides I can see are a slightly larger install image, and possibly lower compiler performance. Neither of these seem too important. Seems generally better and simpler to use an external shared library in all installs.

**Comment by tkelman** [comment]
Wouldn't the install actually be smaller? Right now we statically link all of LLVM into both libjulia and libjulia-debug and ship both. This would at least have both libjulia and libjulia-debug linking to the same LLVM shlib.

**Comment by tkelman** [comment]
If we're going to make this change for 0.5, it should be done soon. Changes like this shouldn't be left to the last second, better for people to have time to test various configurations on master for a while.

**Comment by ViralBShah** [comment]
Given how the dynamic library search path logic will be different on all OSes, we should certainly do this now, or otherwise after release.

**Comment by tkelman** [comment]
Looks like it's roughly a wash on total size, libjulia and libjulia-debug are smaller when both linking to a shared libllvm (not as small as I'd thought they might be though), but the shared libllvm is bigger than the net difference of what we had been linking statically - guess the linker was good at getting rid of unused things when linking statically, that have to all be there in a shared libllvm.

Warning that cmake-built shared llvm doesn't export anything from the dll on Windows currently, so there's work to be done on llvm's build system before we can upgrade to the cmake-only 3.9. That hasn't even branched yet AFAIK, so maybe someone else will do this before we have to.
