### ISSUE TITLE
Closest candidates error message are worse than before and could in general be better

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#16118]
Many (every) time when I try to create a type and have the wrong type of one of the fields I get these as closes candidate suggestions:

```jl
Closest candidates are:
  (::Type{Expr})(::ANY...)
  (::Type{Core.Inference.JLOptions})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  (::Type{Base.JLOptions})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
```

Is it possible to special case these so that they don't show up because they clutter the output quite a lot and are almost surely not what the user want to create.

**Comment by KristofferC** [comment]
I added a special case to ignore these functions but then I just get:

```jl
Closest candidates are:
  (::Type{Base.GitVersionInfo})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  (::Type{Base.Libc.TmStruct})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  (::Type{Base.Filesystem.StatStruct})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
```

I guess there might be nothing to do here since this could be taken indefinitely. Feel free to close if this is desirable behavior.

**Comment by KristofferC** [comment]
I must also say that the suggested methods are much better in 0.4.

For:

```jl
type foo
    a
    b
end

foo(1.0)
```

v0.4 suggests:

![image](https://cloud.githubusercontent.com/assets/1282691/14912257/3f30a3d8-0dfb-11e6-9bb2-acb92ac2b5e4.png)

where the top result is what the user most likely looked for.

In v0.5:

![image](https://cloud.githubusercontent.com/assets/1282691/14912272/54b6bbfc-0dfb-11e6-945c-6abf124c113c.png)

which is much worse since it doesn't even show the `foo` constructor.

**Comment by nalimilan** [comment]
Agreed, the problem isn't so much with `JLOptions`, it's with the fact that other constructors for the same type aren't listed.

**Comment by KristofferC** [comment]
So what happens is that when a type with two fields are called with its constructor with three arguments `foo(a,b,c)` then we count this as two correct arguments. However, for some other constructor that happens to take 3 matching arguments we count this as three correct arguments and instead make this a closer method.

This means that for example `(::Type{Expr})(::ANY...)` will always match perfectly and will always be the top choice of a closest method.

**Comment by KristofferC** [comment]
I sort of just want to return here: https://github.com/JuliaLang/julia/blob/8d1f6bc329e31bc93df115fa70b1cd84c83db381/base/replutil.jl#L291


This would give
```jl
julia> type foo
       a
       b
       end

julia> foo(1,2,3)
ERROR: MethodError: no method matching foo(::Int64, ::Int64, ::Int64)
Closest candidates are:
  foo(::Any, ::Any)
  foo{T}(::Any)
 in eval(::Module, ::Any) at ./boot.jl:236
```

Does it even make sense to suggest a completely different function that happens to take the same argument types?

**Comment by H-225** [comment]
> Does it even make sense to suggest a completely different function that happens to take the same argument types?

I wouldn't say so.

**Comment by H-225** [comment]
> I wouldn't say so.

Actually, I guess it would make sense for those times where you call the wrong function, but with the right arguments.

However, matching what was specified is certainly be displayed first.

**Comment by StefanKarpinski** [comment]
It seems like some notion of specificity (like how dispatch itself works) would be helpful here. If a function name doesn't exist at all it would make sense to list similar function names by edit distance.

**Comment by KristofferC** [comment]
Maybe we can just tweak the scoring a bit. Right now, the scoring is very simple. Just count how many arguments that are `<:` and sort on that. One suggestion could be that matching a concrete type should score higher than matching an `Any` for example. Matching the actual function should also likely give a higher score than matching an argument.

A heuristic that gives pretty good suggestions (at least better than now) shouldn't have to be too complicated.

**Comment by KristofferC** [comment]
Hmm, there is a large difference in the result for type constructors and functions.

For a function, the loop to look for closest neighbors only go through the method table for that function:

```jl
julia> foo(a,b) = a
foo (generic function with 1 method)

julia> foo(a,b,c) = a
foo (generic function with 2 methods)

julia> Core.Typeof(foo).name.mt
# 1 method for generic function "foo":
foo(a, b) at REPL[1]:1
foo(a, b, c) at REPL[6]:1
```

This gives a good suggestion for 

```jl
julia> foo(1,2,3,4)
ERROR: MethodError: no method matching foo(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  foo(::Any, ::Any, ::Any)
  foo(::Any, ::Any)
 in eval(::Module, ::Any) at ./boot.jl:236
```

For type constructors we go through ALL other type constructors and look for matching arguments:

```jl
julia> type Foo
       a
       b
       end

julia> Core.Typeof(Foo).name.mt
.
.
(::Type{HTML{T}}){T}(content) at docs/utils.jl:23
(::Type{HTML{T<:Any}}){T}(content::T) at docs/utils.jl:23
(::Type{HTML{T<:Any}})(xs...) at docs/utils.jl:27
(::Type{Text{T}}){T}(content) at docs/utils.jl:68
(::Type{Text{T<:Any}}){T}(content::T) at docs/utils.jl:68
(::Type{T}){T}(arg) at sysimg.jl:50

julia> length(Core.Typeof(Foo).name.mt)
1308
```

This will of course give a bad suggestion:

```jl
julia> foo(1,2,3)
ERROR: MethodError: no method matching foo(::Int64, ::Int64, ::Int64)
Closest candidates are:
  (::Type{Expr})(::ANY...)
  (::Type{TypeError})(::Any, ::Any, ::Any, ::Any)
  (::Type{Core.Inference.JLOptions})(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any)
  ...
 in eval(::Module, ::Any) at ./boot.jl:236
```

**Comment by tkelman** [comment]
> I will add tests if this is likely to get merged.

**Comment by KristofferC** [comment]
Yes. I will.
