### ISSUE TITLE
Use intrinsics for `safe_add`/`safe_mul`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#16120]
[`safe_mul` and `safe_add`](https://github.com/JuliaLang/julia/blob/2aa5d4d6f159f855a1ec6b2b113bef54153ca3ad/base/parse.jl#L66-L69) return Nullables containing indicators as to whether they overflowed. Unfortunately these are currently written using inefficient `div` operations rather than native checked operations, so are quite slow.

I made an attempt to do this in #15040, but it's a bit of a hack using `llvmcall`. It would probably better to use the actual API and do this in intrinsics.cpp.

This would allow faster integer parsing, and also be useful to have in #11522.

**Comment by JeffreySarnoff** [comment]
That makes sense to me.  
Is there a reason that safe_sub does not exist?  
It may be helpful as safe_sub{T<:Integer}(n1::T, n2::T) != safe_add(n1, -n2)  when n2==typemin(T).

**Comment by simonbyrne** [comment]
I would guess because they are only used internally at the moment (in the integer parsing library), and `safe_sub` wasn't needed.

**Comment by simonbyrne** [comment]
Closed a while back by #17152
