### ISSUE TITLE
compilation fails on OSX

### ISSUE THREAD

**Issue by Ken-B** [JuliaLang/julia#16124]
on a fresh git pull on Macbook Pro 2015 with OSX 10.11.4
```
ken$ git clone git://github.com/JuliaLang/julia.git
ken$ cd julia
ken$ make
```

I get this strange error (same with `sudo make`):
```
/var/folders/h9/8wp6_1kx6_v6wm7_vy5w_pbm0000gn/T//ccs12bfn.s:1634:suffix or operands invalid for `movq'
/var/folders/h9/8wp6_1kx6_v6wm7_vy5w_pbm0000gn/T//ccs12bfn.s:1637:suffix or operands invalid for `movq'
make[2]: *** [amos/zbknu.f.o] Error 1
make[1]: *** [build/openspecfun-381db9bc865e51de67be9dcaa1610a6f90029c72/libopenspecfun.dylib] Error 2
make: *** [julia-deps] Error 2
```

Here's the [full gist of the output](https://gist.github.com/Ken-B/f9fb17c0f2cc8c500f0eef770934e49f).

And just in case here's the versioninfo from an existing release version:
```
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Let me know what I can do. Thanks!

**Comment by nalimilan** [comment]
Maybe related this Linux failure? https://github.com/JuliaLang/julia/issues/16087#issuecomment-215619696

**Comment by yuyichao** [comment]
I believe the linux one is a 32bit only issue on 0.4 in `task.c`. This one is a openspecfun issue.

**Comment by nalimilan** [comment]
Yes, these seem to happen in totally different places, but I had never seen those `suffix or operands invalid for 'movq'`. Could they be related to a compiler issue?

**Comment by Ken-B** [comment]
FWIW, I was able to compile 0.5.0-dev+2418 at the end of January on the same laptop but in a separate dir. When I run tests there again, I now get these test errors (I don't think I got them back then, but not sure):
```
Exception running test subarray :
On worker 7:
LoadError: Mismatch
 in test_cartesian at /Users/ken/Documents/Coding/juliadebug/test/subarray.jl:152
 in runtests at /Users/ken/Documents/Coding/juliadebug/test/subarray.jl:271
 in runviews at /Users/ken/Documents/Coding/juliadebug/test/subarray.jl:292
 [inlined code] from /Users/ken/Documents/Coding/juliadebug/test/subarray.jl:369
 in anonymous at ./no file:4294967295
 [inlined code] from ./essentials.jl:80
 in include_string at ./loading.jl:371
 in include_from_node1 at ./loading.jl:420
 [inlined code] from ./util.jl:179
 in runtests at /Users/ken/Documents/Coding/juliadebug/test/testdefs.jl:7
 in #16 at /Users/ken/Documents/Coding/juliadebug/test/runtests.jl:36
 in run_work_thunk at ./multi.jl:714
 [inlined code] from ./multi.jl:1010
 in #253 at ./task.jl:60
while loading /Users/ken/Documents/Coding/juliadebug/test/subarray.jl, in expression starting on line 351
ERROR: LoadError: Some tests exited with errors.
 in #11 at /Users/ken/Documents/Coding/juliadebug/test/runtests.jl:64
 in cd at ./file.jl:47
 in include at ./boot.jl:264
 in include_from_node1 at ./loading.jl:417
 in process_options at ./client.jl:244
 in _start at ./client.jl:300
while loading /Users/ken/Documents/Coding/juliadebug/test/runtests.jl, in expression starting on line 13
make[1]: *** [all] Error 1
make: *** [testall] Error 2
```

**Comment by vtjnash** [comment]
did you remember to do a fresh reinstall of gfortran / macports / homebrew after upgrading your OS (major version)? it looks like your compiler and assembler may be out-of-sync.

**Comment by Ken-B** [comment]
I did a fresh install of homebrew and `brew install gcc`, then upgraded macports, but it still doesn't compile with the same error.
Also an earlier version of v0.5 that I was able to compile in January doesn't compile now, so probably @vtjnash is right.
What should I do?

**Comment by vtjnash** [comment]
maybe check your ENV for unexpected variables or unexpected binaries on your PATH (e.g. I build without homebrew or macports on my path to reduce conflicts, just adding gfortran, cmake and a few others)

**Comment by Ken-B** [comment]
It worked with `PATH=/usr/bin:/usr/local/bin:/usr/sbin:/bin make` and tests pass.

For future reference, here's my full path:
```
ken$ $PATH
-bash: /opt/local/bin:/opt/local/sbin:/Users/ken/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/Applications/Julia-0.4.2.app/Contents/Resources/julia/bin: No such file or directory
```

Thanks for all the help, @vtjnash!
