### ISSUE TITLE
Extend `conv` to arbitrary lists of vectors

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#16126]
At this moment `conv` convolves only two vectors, `conv(u,v)`. If you have a list of vectors `lst` that you want to convolve, you can do it like this:

`reduce(conv, lst)`

But this is very inefficient because it computes the inverse Fourier transform too many times. A much more efficient way is to compute the FT of every vector once, multiply them element-wise, and then compute only one FT inversion of the product sequence. But for this you need a dedicated `conv(u, v, w, ...)` that accepts an arbitrary number of vectors.

**Comment by toivoh** [comment]
+1
Seems like the only reasonable definition for multi-argument conv, and
quite analogous to multi-argument *.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaDSP/DSP.jl/issues/166
