### ISSUE TITLE
Ambiguous TypeConstructor printing

### ISSUE THREAD

**Issue by ivirshup** [JuliaLang/julia#16141]
This got me really confused for a bit.

```julia
julia> tcs = filter(x->isa(x,TypeConstructor), map(y->eval(Base,y), names(Base)));

julia> tcs[end - 1]
Union{Array{T,1},Array{T,2}}

julia> typeof(tcs[end - 1])
TypeConstructor
```
Especially when:
```julia
julia> Union{Vector, Matrix}
Union{Array{T,1},Array{T,2}}

julia> typeof(Union{Vector, Matrix})
Union
```

edit:

Just noticed that `typealias`s in general have

```julia
julia> Vector
Array{T,1}

julia> typeof(Vector)
TypeConstructor

julia> Array{TypeVar(:T),1}
Array{T,1}

julia> Array{TypeVar(:T),1} |> typeof
DataType
```

Which might be the closer to the desired behavior, but can still be confusing when working with this kind of data.

**Comment by yuyichao** [comment]
Note that this is suppose to match the syntax of type alias and you should manually construct `TypeConstructor` in other ways or using `TypeVar`s since they are considered internal implementation detail.

```
julia> typealias A{T} Union{Vector{T},Matrix{T}}
Union{Array{T,1},Array{T,2}}

julia> A
Union{Array{T,1},Array{T,2}}

julia> typeof(A)
TypeConstructor
```

**Comment by ivirshup** [comment]
I'm a little unsure of what you're saying. Let me clarify my initial comment. Since `Vector` and `Array{T, 1}` are of different types and are not completely interchangeable, I think it would make sense for them to have different `show` methods to avoid confusion at the REPL.

What I would like to do is make a pull request redefining `show(io::IO, x::TypeConstructor)` from

```julia
show(io::IO, x::TypeConstructor) = show(io, x.body)
```
to something more like
```julia
function show(io::IO, x::TypeConstructor)
  print(io, "$(typeof(x)): ")
  show(io, x.body)
end
```

**Comment by yuyichao** [comment]
Yes, I know what you mean. What I mean is that the confusion isn't particularly bad since the only way you can construct such thing (with unbound `TypeVar`) should be through `typealias` (almost all other methods are relying on internal detail and are considered not supported, e.g. you can easily get into trouble if you construct TypeVar manually).

`show` is also not meant to print out the object unambiguously either. It would be a little annoy if we print out the types for all of the following.

```jl
julia> show(Int8(1))
1                                                                                 
julia> show(Int16(1))
1                                                                                 
julia> show(Int32(1))
1                                                                                 
julia> show(Int64(1))
1                                                                                 
julia> show(utf8(""))
""                                                                                
julia> show(ascii(""))
""                                                                                
```

**Comment by ivirshup** [comment]
Alright, I'd agree one can typically tell if a type is a TypeConstructor or not. I am looking through user defined types so this does occasionally get a bit hairy. I guess my preference is just for it to be a little more explicit. 

In ambiguous cases, I do think the difference between `TypeConstructor`s and `Union`s or `Type`s is less subtle (in terms of available methods and parameters) than with the various kinds of strings and integers.

```julia
julia> fnames(t) = map(x->x.func.name, methodswith(t,true))
fnames (generic function with 1 method)

julia> length(symdiff(fnames(UTF8String), fnames(ASCIIString)))
2

julia> length(symdiff(fnames(Int16), fnames(Int32)))
1

julia> length(symdiff(fnames(TypeConstructor), fnames(Type)))
49
```
