### ISSUE TITLE
Pkg.update fails for Julia 0.4.5

### ISSUE THREAD

**Issue by George9000** [JuliaLang/julia#16140]
Issue that affects both the Juno install and the CLI

Pkg.update() fails:

WARNING: julia is fixed at 0.4.5 conflicting with requirement for JuliaParser: [0.5.0-,∞)
ERROR: AbstractTrees can't be installed because it has no versions that support 0.4.5 of julia. 

from https://groups.google.com/forum/#!msg/julia-users/lU0UBIM1WOU/7vw_G9gmDAAJ
Pkg.free("JuliaParser")
Pkg.update()

**Comment by Ismael-VC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15939. @George9000 the error is telling you that JuliaParser is supporting now only v0.5 and above.
