### ISSUE TITLE
type computation in broadcast is worse than in map

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16164]
With current 0.5 master:
```
julia> map(Float32, [3,4,5])
3-element Array{Float32,1}:
 3.0
 4.0
 5.0

julia> broadcast(Float32, [3,4,5])
3-element Array{Int64,1}:
 3
 4
 5
```
We presumably want to return a `Float32` array in both cases?

cc: @ViralBShah: this affects the case you asked about in #8450, since my `f.(x...)` implementation in #15032 is equivalent to `broadcast`.

**Comment by GunnarFarneback** [comment]
I believe this not really a type inference issue but a type computation issue due to a missing piece in the promote_op machinery.

**Comment by JeffBezanson** [comment]
I think `broadcast` is due for an update now that higher-order functions are fast.

**Comment by stevengj** [comment]
Another instance of the same problem: `broadcast(sin, 3)` throws an `InexactError`.

**Comment by stevengj** [comment]
See also #11119, #12277.

**Comment by stevengj** [comment]
Duplicate of #4883.
