### ISSUE TITLE
master broke AutoHashEquals.jl

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#16169]
About 2 weeks ago AutoHashEquals.jl worked, but starting sometime last week the nightly build broke it. See andrewcooke/AutoHashEquals.jl#4.

I have no idea whether that is a regression on julia's side, or just the case of a package that needs to be updated. I'm also not sure whether you (core devs) want these sort of things reported here. If not, feel free to close this issue immediately.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/16158

**Comment by davidanthoff** [comment]
Ah, sorry for the noise.
