### ISSUE TITLE
Missing incomplete Beta function and its logarithm

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#16178]
Currently the standard library has no incomplete Beta function, or its logarithm:

log(B(\alpha, \beta, x))

which can be useful in some applications.

**Comment by cossio** [comment]
related: https://github.com/JuliaLang/julia/pull/16177

**Comment by andreasnoack** [comment]
For a summary of the history of "The Incomplete Beta Function in Julia" see https://groups.google.com/forum/#!searchin/julia-dev/Incomplete$20beta$20function/julia-dev/4dK0CuVvxrQ/8hLDO5UAsEAJ. To some extend, this is also dup of https://github.com/JuliaLang/julia/issues/4301 although it might be useful to have specific issues for each special function.

**Comment by simonbyrne** [comment]
You can use [StatsFuns.jl](https://github.com/JuliaStats/StatsFuns.jl), or [Distributions.jl](https://github.com/JuliaStats/Distributions.jl).

I think the general consensus of #4301/#8536 is that we will probably won't add more special functions to Base.

**Comment by cossio** [comment]
@simonbyrne Thanks for pointing out StatsFuns.jl, looks awesome, and it seems to include the logarithm of the incomplete Beta functions.

Although maybe a better organization is to have a dedicated module SpecialFuns.jl as a dependancy of both StatsFuns.jl and Distributions.jl, instead of duplicating code.

**Comment by kshyatt** [comment]
@cossio, is your issue resolved? Can I close this, since you've found a package that suits your needs?
