### ISSUE TITLE
Current method for loading modules into scope on all workers is unintuitive

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/julia#16189]
I ran into some weird problems when I need `Distributions.jl` in scope on all workers for a parallel workflow. @andreasnoack kindly pointed out to me (https://github.com/JuliaStats/Distributions.jl/issues/492) that the correct way for doing this is

```{.julia}
using Distributions
@everywhere using Distributions
```
which seems very unintuitive and AFAIK is also undocumented. Why is it this way? I can't find any reason for wanting to have a module loaded, but not in-scope on all workers *except* for the first one.

**Comment by simonster** [comment]
Dup of #9245.

> Why is it this way?

As far as I can tell, nobody knows.
