### ISSUE TITLE
UndefVarError `ANCHORED` on AV

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#16188]
This just started happening, maybe related to PCRE configuration.

e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.1152

**Comment by tkelman** [comment]
Fixed by e6593302788fb48528d629872db167ac925db82b. Not sure how long this has been the case or why it only started causing problems today, but the internal structure of the Windows binary installer files apparently changed.

**Comment by vtjnash** [comment]
didn't we just switch 7z version too?

**Comment by tkelman** [comment]
Possibly. The build image's MSYS2 installation was redone recently: https://github.com/appveyor/ci/issues/785 (had caused the failure a few days ago)

**Comment by yuyichao** [comment]
Happens again? https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.1183/job/jmwsl8dj05ruy33m

**Comment by yuyichao** [comment]
Happening on multiple PR's now....

**Comment by yuyichao** [comment]
Also happens on my appveyor account https://ci.appveyor.com/project/yuyichao/julia/build/1.0.240

**Comment by tkelman** [comment]
I had some debugging commits on a temporary branch yesterday. Already deleted but you should be able to find them in the av logs.

**Comment by yuyichao** [comment]
I couldn't find your debug commit so I tried to see what's wrong with the extraction of pcre_h.jl. https://ci.appveyor.com/project/yuyichao/julia/build/1.0.245/job/ff02etcy92lut1bg#L20 vs https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.1226/job/n2pow19fee438clq#L21

It looks like the 7z on my appveyor account is 5 years older than the one on the JuliaLang one? Could that be the issue?

**Comment by tkelman** [comment]
Roughly that, yeah. JuliaLang runs on a pro appveyor account, your account is presumably the free plan. Ref https://github.com/appveyor/ci/issues/785 there are some changes in default software versions installed in the VM image that probably vary by account type.

**Comment by yuyichao** [comment]
OK, I asked upstream at https://github.com/appveyor/ci/issues/793, close here.
