### ISSUE TITLE
Hello, Human.

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#16209]
julia ver: 0.4.5
os: windows 10

define function as
```julia
" with love "
function hi()
    println("Hello, Matrix.")
end
```
then enter help mode
```bash
help?> hi
```
we receive greetings from the matrix,
```txt
Hello, Human.
```
but, where is our `with love`?

**Comment by tkelman** [comment]
Nice issue title. You've found an easter egg that apparently doesn't like being overwritten?

**Comment by vchuravy** [comment]
`hi` and `hello` are defined as keywords in https://github.com/JuliaLang/julia/blob/6c67baee1af2d3ccd0e8fbd31aab1599e53980ad/base/docs/basedocs.jl#L11 (that was introduced in 08663d).

There are keywords in the current `Docs.keyword` which are legal function names:
- `hi`
- `hello`
- `help`
- `?`

and the keyword docs take precedent over the function docs.

**Comment by innerlee** [comment]
Thanks @vchuravy, glad to know this is on purpose :smile:
