### ISSUE TITLE
ERROR: system image file "/opt/julia-2ac304dfba/../lib/julia/sys.so" not found

### ISSUE THREAD

**Issue by Maple-Wang** [JuliaLang/julia#16228]
julia-0.4.5-linux-x86_64.tar.gz

[root@master1 ~]# julia
ERROR: system image file "/opt/julia-2ac304dfba/../lib/julia/sys.so" not found
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]#
[root@master1 ~]# 
[root@master1 ~]# julia --version
julia version 0.4.5
[root@master1 ~]#

**Comment by lobingera** [comment]
Your issue is missing a little bit of the information how you got from the tar ball to the executable ... read as: How did you build?

**Comment by Maple-Wang** [comment]
I just download the Generic Linux binaries version from the official website

**Comment by zhmz90** [comment]
There are some [Platform Specific Instructions](http://julialang.org/downloads/platform.html) in Julia official site. If your OS is not included, you can also build Julia from source.
```Bash
git clone git://github.com/JuliaLang/julia.git
make -C deps getall
make -j $num_threads
```
More details about how to make Julia from source, check [README.md](https://github.com/JuliaLang/julia/blob/master/README.md).

Hope this can help you.

**Comment by Maple-Wang** [comment]
@zhmz90   what does the second step means？ make -C deps getall

**Comment by zhmz90** [comment]
@Maple-Wang `make -C deps getall` will automatically download all the dependencies of `Julia` to your local machine.

**Comment by Maple-Wang** [comment]
@zhmz90  I donnot know what dependences，but I know the first step have already download all files. and do you kown where does julia installed,the current path ,or the system path. thanks for your help.

**Comment by tkelman** [comment]
The generic Linux tarball doesn't add itself to your path automatically, you have to do so with a symlink or a shell alias or similar. Check `which julia` and `ls -la $(which julia)`, it looks like whatever you had built or extracted at `/opt/julia-2ac304dfba/../lib/julia/sys.so` is a bit broken?

**Comment by zhmz90** [comment]
Building Julia requires that some software to be installed, which is listed at [Required Build Tools and External Libraries](https://github.com/JuliaLang/julia#required-build-tools-and-external-libraries).

`git clone git://github.com/JuliaLang/julia.git` doesn't download the code of `Julia`'s dependencies.
There will be an binary file `julia`  in your `julia` directory after  `make -j $num_threads` succeed.
You can add the `julia` director to your path.

**Comment by Maple-Wang** [comment]
@tkelman  no error occurs

**Comment by tkelman** [comment]
> no error occurs

When you do what? By "check" I meant post the output here.

You don't have to build from source unless you're on some exotic unconventional OS/architecture or want to follow along with development or make changes to the parts of Julia that are implemented in C code yourself. The binaries for common OS/architectures should work, though we do need to update the http://julialang.org/downloads/platform.html page and replace the PPA instructions with a few words on how to use the generic Linux binaries.

**Comment by Maple-Wang** [comment]
@tkelman  I just tar -zxvf julia*.tar.gz  .No error occurs.  Hope for the updatement

**Comment by Maple-Wang** [comment]
@zhmz90 


src/math_private.h:78: error: conflicting types for ‘ieee_double_shape_type’
src/math_private.h:60: note: previous declaration of ‘ieee_double_shape_type’ was here
make[2]: *** [src/s_fmax.c.o] Error 1
make[1]: *** [openlibm/libopenlibm.so] Error 2
make: *** [julia-deps] Error 2
[wangfeng@datatrans julia]$

**Comment by tkelman** [comment]
What kind of operating system and architecture is your computer, anyway? What does `gcc --version` say?

**Comment by Maple-Wang** [comment]
@tkelman 

[wangfeng@node1 bin]$ 
[wangfeng@node1 bin]$ gcc --version
gcc (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[wangfeng@node1 bin]$

**Comment by tkelman** [comment]
Yeah, gcc 4.4 is too old to build Julia from source. Are you on RHEL 6? If you can't get the devtoolset installed, then you're better off using the binaries.

**Comment by Maple-Wang** [comment]
@tkelman 

I give up build from source.but another strange occurs. i tar zxvf the binary tar.gz. 
Open two terminal use the same linux account.
**one terminal work correctly**

wangfeng@node1 bin]$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6 (2016-06-19 17:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> 



**the other not,and reaccese also failed,**



[wangfeng@node1 wangfeng]$ cd ProgramFiles/julia-2e358ce975/bin/
[wangfeng@node1 bin]$ ./julia
ERROR: system image file "/p200/chenhua_group/wangfeng/ProgramFiles/julia-2e358ce975/../lib/julia/sys.so" not found
[wangfeng@node1 bin]$ 
[wangfeng@node1 bin]$ 
[wangfeng@node1 bin]$

**Comment by tkelman** [comment]
What's different between the two? Compare things like `LD_LIBRARY_PATH` or `env` differences?

**Comment by Maple-Wang** [comment]
**the correct one:**
[wangfeng@node1 ~]$ echo $LD_LIBRARY_PATH
/public/software/mpi/openmpi-16-intel/lib:/public/software/intel/composer_xe_2011_sp1.7.256/compiler/lib/intel64:/public/software/intel/composer_xe_2011_sp1.7.256/mkl/lib/intel64:/opt/gridview//pbs/dispatcher427/lib::/usr/local/lib64:/usr/local/lib
[wangfeng@node1 ~]$ echo $PATH
/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/julia-2e358ce975/bin:/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/Meadmix:/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/Seq-Gen.v1.3.3/source:/share_bio/disk1/chenhua_group/Software/bin:/usr/lib64/qt-3.3/bin:/public/software/mpi/openmpi-16-intel/bin:/public/software/intel/composer_xe_2011_sp1.7.256/bin/intel64:/opt/gridview//pbs/dispatcher-sched/bin:/opt/gridview//pbs/dispatcher-sched/sbin:/opt/gridview//pbs/dispatcher427/bin:/opt/gridview//pbs/dispatcher427/sbin:/software/biosoft/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/wangfeng/bin
[wangfeng@node1 ~]$ 



**the failed one :**
[wangfeng@node1 ~]$ 
[wangfeng@node1 ~]$ echo $LD_LIBRARY_PATH
/public/software/mpi/openmpi-16-intel/lib:/public/software/intel/composer_xe_2011_sp1.7.256/compiler/lib/intel64:/public/software/intel/composer_xe_2011_sp1.7.256/mkl/lib/intel64:/opt/gridview//pbs/dispatcher427/lib::/usr/local/lib64:/usr/local/lib
[wangfeng@node1 ~]$ 
[wangfeng@node1 ~]$ 
[wangfeng@node1 ~]$ echo $PATH
/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/Meadmix:/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/Seq-Gen.v1.3.3/source:/home/wangfeng/WorkSpace1/wangfeng/ProgramFiles/julia-2e358ce975/bin:/share_bio/disk1/chenhua_group/Software/bin:/usr/lib64/qt-3.3/bin:/public/software/mpi/openmpi-16-intel/bin:/public/software/intel/composer_xe_2011_sp1.7.256/bin/intel64:/opt/gridview//pbs/dispatcher-sched/bin:/opt/gridview//pbs/dispatcher-sched/sbin:/opt/gridview//pbs/dispatcher427/bin:/opt/gridview//pbs/dispatcher427/sbin:/software/biosoft/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/wangfeng/bin
[wangfeng@node1 ~]$

**Comment by tkelman** [comment]
Did someone set a `JULIA_HOME` environment variable maybe? that variable is significant to the julia runtime and you shouldn't usually set it

**Comment by Maple-Wang** [comment]
@tkelman  yes I set it in the .bash_profile which terminal open julia failed,and source .bash_profile.The other not source .bash_profile

**Comment by Maple-Wang** [comment]
@tkelman  Why connot set the JULIA_HOME path. other program did.

**Comment by tkelman** [comment]
What other program? There's a `getenv` call in `src/init.c` that uses JULIA_HOME as a way of setting the system image location as another option other than the command line flag. Potentially useful for embedding but a lot of people seem to set this and accidentally break julia by doing so.

**Comment by KristofferC** [comment]
Please update if this still happens on the new releases.
