### ISSUE TITLE
String literal only evaluates once inside for loop

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#16246]
It is discovered in https://github.com/JuliaStats/RCall.jl/issues/109 that string literals only evaluates once inside a for loop.

```julia
s = 0
macro T_str(prefix)
    global s
    s = s + 1
    QuoteNode(string(prefix, s))
end
```

```
julia> T"foo"
"foo1"

julia> T"foo"
"foo2"

julia> for(i in 1:2) println(T"foo") end
foo3
foo3

julia> s
3
```
In the last for loop, `T"foo"` were run twice, but it returns the same result every time,

I gauss it is because Julia wrongly assumes that `T"foo"` is a constant and Julia is smart enough to not evaluate it twice. Is it considered a bug? or it is expected? I don't not sure.

**Comment by tomaklutfu** [comment]
I think it is because `T"foo"` replaced with `"foo3"`in parse time and so it is expected that it stays the same in runtime. Macros are not called in runtime and I think this behaviour expected in this case. It does not call `T"foo"` twice but it uses macro expanded value twice.

**Comment by randy3k** [comment]
Oh, I just didn't read the [documentation](http://docs.julialang.org/en/stable/manual/metaprogramming/#hold-up-why-macros) careful enough.
