### ISSUE TITLE
Segmentation fault in Lazy.jl

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#16245]
Precompiling `Lazy.jl` `v0.10.1` leads to a seqfault on master (5008bb962)

```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
[inline] at /home/wallnuss/src/julia/src/julia.h:908
jl_is_array_type at /home/wallnuss/src/julia/src/dump.c:765
jl_serialize_value_ at /home/wallnuss/src/julia/src/dump.c:913
jl_serialize_value_ at /home/wallnuss/src/julia/src/dump.c:841
jl_serialize_value_ at /home/wallnuss/src/julia/src/dump.c:785
jl_serialize_value_ at /home/wallnuss/src/julia/src/dump.c:841
jl_serialize_methcache_from_mod at /home/wallnuss/src/julia/src/dump.c:1005
jl_typemap_visitor at /home/wallnuss/src/julia/src/typemap.c:348
[inline] at /home/wallnuss/src/julia/src/dump.c:1025
jl_serialize_methtable_from_mod at /home/wallnuss/src/julia/src/dump.c:1047
jl_serialize_lambdas_from_mod at /home/wallnuss/src/julia/src/dump.c:1041
jl_save_incremental at /home/wallnuss/src/julia/src/dump.c:2163
[inline] at /home/wallnuss/src/julia/src/init.c:755
julia_save at /home/wallnuss/src/julia/src/init.c:223
unknown function (ip: 0x4016c3)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x401708)
Allocations: 2993049 (Pool: 2991435; Big: 1614); GC: 5
ERROR: Failed to precompile Lazy to /home/wallnuss/.julia/lib/v0.5/Lazy.ji
 [inlined code] from ./error.jl:21
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364
 in eval(::Module, ::Any) at ./boot.jl:230
```

I run a git bisect and the last good commit is a0f4920 and the first bad one is 39bb06d5d. On 39bb06d5d the segmentation fault looks different: https://gist.github.com/vchuravy/df36420647f8c28dc3c6700ac6c1d434

cc @timholy @yuyichao @IainNZ

**Comment by vchuravy** [comment]
It seems there are several problems interacting with each other. The difference in the segfaults led me to investigate a bit more.

The seqfault is fixed by https://github.com/MikeInnes/Lazy.jl/commit/4abf19fc9a (on master julia), but is still present in 39bb06d and is fixed in julia by 1782c4904e5, if `bisect` is to believe.

**Comment by timholy** [comment]
Are you saying that the segfault is now fixed on a fully up-to-date master?

**Comment by vchuravy** [comment]
Updating `Lazy.jl` to its most recent development branch doesn't show the segfault anymore, the currently tagged version still has the seqfault.

- master  => 5008bb9 
- `v0.10.1` => https://github.com/MikeInnes/Lazy.jl/commit/42b81ab

| Julia version  | Lazy.jl version | Status |
| ------------- | ------------- | ------------- |
| master | `v0.10.1`  | seqfault |
| master | https://github.com/MikeInnes/Lazy.jl/commit/4abf19fc9a | no seqfault |
| 39bb06d | https://github.com/MikeInnes/Lazy.jl/commit/4abf19fc9a | seqfaults |

So what I am trying to say is that there still is a scenario where precompilation seqfaults, but finding the cause of the issue might be tricky. Because there might be a second bug, that also causes a seqfault, but that has been fixed since then.

**Comment by timholy** [comment]
That table was very handy, thanks for taking the time it took to clarify the issues so thoroughly.
