### ISSUE TITLE
Error when using julia's packages

### ISSUE THREAD

**Issue by hililielala** [JuliaLang/julia#16272]
Hello,

I had instaled Julia and it was working perfectly last week. However, since 4 days ago I can not use any package. When I try to load one I have the following message:

using DataFrames
INFO: Precompiling module DataFrames...
Error: SystemError: mkdir: No such file or directory in mkdir at file.jl:42

using JuMP
INFO: Precompiling module JuMP...
Error: SystemError: mkdir: No such file or directory in mkdir at file.jl:42

And this happens for all the packages I try to load!!!

**Comment by StefanKarpinski** [comment]
Please post questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.
