### ISSUE TITLE
Delete or document "contains(eq::Function, itr, x)"

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#16277]
I'm not sure if the fact that it was not removed in 7ee71738 (replace `contains` by `in`) is an oversight, but this implementation doesn't seem like a good generic one for the "new" meaning ("substructure containment", cf. e.g. https://github.com/JuliaLang/julia/commit/98a490b8ea833d7b9dc8cbcc8971317ac2c55682#commitcomment-3986922, or #4153).

**Comment by ranjanan** [comment]
Yeah, this function seems like a generalized version of `in(item, collection)` wherein `f` is simply the `==` function. Maybe it would be worth changing this `contains` to `in` and then adding a docstring there?

**Comment by tkelman** [comment]
Looks pretty vestigial, is it called anywhere? Do tests pass if you delete it? If so then no rush and it's not really an 0.5 backport candidate. To be proper we'd move it to a deprecation first, but even if it's not very widely used we shouldn't squeeze in deprecations post-rc1 unless we absolutely have to for some bug fix reason.

**Comment by rfourquet** [comment]
Fixed by #19541.
