### ISSUE TITLE
Unable to run Juno.

### ISSUE THREAD

**Issue by spinozaEd** [JuliaLang/julia#16279]
Followed the instructions. Got the following messagejulia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating JuliaParser...
INFO: Computing changes...
WARNING: julia is fixed at 0.4.5 conflicting with requirement for JuliaParser: [0.5.0-,∞)
ERROR: AbstractTrees can't be installed because it has no versions that support 0.4.5 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in update at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib

julia> 
Please see attachments.
![julia errors](https://cloud.githubusercontent.com/assets/19273699/15127408/927edb02-1604-11e6-9363-c4fd5e8b1df8.jpg)

**Comment by pkofod** [comment]
This issue tracker is for bugs or issues relating directly to the base language. For package support or general help, you might find the julia-users mailing list (https://groups.google.com/forum/#!forum/julia-users ) more appropriate, and in this particular example you could ask at https://gitter.im/JunoLab/Juno

**Comment by ViralBShah** [comment]
Cc @MikeInnes
