### ISSUE TITLE
Wrong font color on windows console

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#16278]
When I start the latest nightly version from a PowerShell command prompt, the header is printed in yellow, not in white as it should:

![image](https://cloud.githubusercontent.com/assets/1036561/15124653/f131c118-15dd-11e6-9182-f31a161690ea.png)

Note that `juliadev` is a powershell alias that just points to the correct `julia.exe`.

I think this behavior started last week or the week before, but I'm not 100% sure...

**Comment by tkelman** [comment]
Side effect of https://github.com/libuv/libuv/pull/431. Now it's inheriting the background from the initial environment.

![console](https://cloud.githubusercontent.com/assets/5934628/15127649/5ffd05d6-15ec-11e6-91fe-8cd7aa79e42c.png)

**Comment by davidanthoff** [comment]
Ah, so it is just using the screen color that was last used, not the screen color that is actually configured... I guess the ideal solution would be if it would just use the screen text color that is actually configured, or just default to white?

**Comment by tkelman** [comment]
Defaulting to white wouldn't be a good idea if you have a light background. Powershell has set the highlighting to yellow, and if you set `$env:JULIA_INPUT_COLOR = "bold"` then your input ends up in that same yellow color so apparently that's what it's using in place of the bold color code.

**Comment by vtjnash** [comment]
now it's actually respecting the colors you chose (well, that Powershell chose for you) to represent "normal text" in the console configuration preferences.

however, we could probably actually print the banner in white (`CSI 37 m`) instead of normal

**Comment by davidanthoff** [comment]
I don't think any of my console preferences are set to yellow, I think this is purely a PowerShell setting as the ``Verbose ForegroundColor`` that it uses to color command names. For example, when I issue the following command in Powershell ``cmd /C dir``, then only the term ``cmd`` is yellow, everything else is white. All the output from executing that command is also white, not yellow.

Also, when I enter anything on the julia command prompt, it is white, so I guess the banner should just use the same color that the command prompt uses?

**Comment by vtjnash** [comment]
those two colors are "normal" and "bold/bright normal", it's usually up to the terminal emulator how they should appear on the screen. However, I don't know that cmd provides any way to query for or set the default color (such as being used by powershell), so libuv simply inherits whatever the environment contained to try to provide a consistent experience.

Perhaps eventually in Windows 10 conhost will support these VT100 codes better (https://msdn.microsoft.com/en-us/library/mt638032(v=vs.85).aspx), but I recommend switching to a better terminal emulator (such as mintty).

**Comment by davidanthoff** [comment]
I think this should get a "regression" label, at the end of the day the current 0.5 builds look odd on Windows.

**Comment by tkelman** [comment]
I think this is more of a bug fix than a regression. Powershell's fault for using strange color choices, and it's possible to set an environment variable to modify the defaults in Julia.

**Comment by davidanthoff** [comment]
From the point of view of a simple julia user (me), this looks like a julia regression. It might technically not be, but would still be good if julia had some work-around for this...

**Comment by ViralBShah** [comment]
Is this still an issue?

**Comment by tkelman** [comment]
I think this is a wontfix.

**Comment by ViralBShah** [comment]
Do we close wontfix issues?

**Comment by KristofferC** [comment]
Seems no point having it open.
