### ISSUE TITLE
Equality between symbols and strings

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#16271]
`"a" == :a` and `isequal("a", :a)` are both `false`. Shouldn't they return `true`?

**Comment by bicycle1885** [comment]
In that case, should `hash("a") == hash(:a)` be true?

**Comment by StefanKarpinski** [comment]
Why? This is no weird than the fact that `123 != "123"`.

**Comment by nalimilan** [comment]
My proposal is no weirder than the fact that `1.0 == 1 == true`... :-)

Symbols and strings are completely comparable without any ambiguity, which isn't the case of numbers (`"1.0"` vs `"1,0"` vs `"1e0"` vs `"1.00"`...). Indeed, symbols are constructed from strings in many cases. I don't see the problem with making them equal.

**Comment by StefanKarpinski** [comment]
If you do `Set(["a", :a])` what do you want the result to be?

**Comment by ararslan** [comment]
Personally I'm a little wary of things of different types being comparable like this. I don't think we want to follow Python 2 on its quixotic endeavor to compare any two objects and declare equality in weird situations.

Saying that a string and a symbol are equal is equivalent to saying `"a" == parse("a")` which is weird in my opinion.

**Comment by carnaval** [comment]
Wouldn't this also imply that `:(f(a)) == :(f("a"))` ? A string and a symbol mean completely different things in surface syntax trees.

**Comment by JeffBezanson** [comment]
Yes, the intended uses of strings and symbols make them too different to compare equal.
