### ISSUE TITLE
Win10 console keyboard shortcuts don't work in julia

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#16281]
The console in Windows 10 now supports things like copy & paste via Ctrl+C, Ctrl+V etc. None of these keyboard shortcuts seem to be supported in a julia session. Would be nice if these also worked in a julia session. I think a list of the shortcuts is [here](https://blogs.windows.com/buildingapps/2014/10/07/console-improvements-in-the-windows-10-technical-preview/), but there might also be a more official list that refers to the release version.

I guess there also some conceptual issues, i.e. how Ctrl-C could at the same time interrupt and be the copy function. Not sure how that is solved in a normal powershell session...

I should add that I don't find this an urgent issue at all, I just discovered it and thought it could be brought up.

**Comment by vtjnash** [comment]
The keyboard shortcuts are only available to non-readline-capable applications, enabling support in Julia would require either disabling line-editing or doing a complete reimplementation in Julia.

**Comment by vtjnash** [comment]
see also #7267 "bundle Julia with a better terminal on Windows"

**Comment by davidanthoff** [comment]
@vtjnash: Why is this being closed? Isn't this clearly something that would be nice to have? I completely understand that this isn't high priority, but that shouldn't be a reason to close the issue? Shouldn't there just be a label "backlog" or "not now" for issues like this?

Also, #7267 wouldn't resolve this issue, there are people out there that want to use the default windows console that is pretty good by now and probably only going to get better.

**Comment by vtjnash** [comment]
Until `cmd` is at least as functional as other existing terminal emulators (such as proposed in #7267), it's not "pretty good". When it gets to that point, the implementation of these should work due to the upstream fixes to the conhost terminal emulator without any action from us (as it already does for better emulators)
