### ISSUE TITLE
decompositions for Rational matrices

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#1629]
Currently, ```lu```, ```chol```, ```(\)```, etc. convert an ```Array{Rational{Int64},2}``` to ```Array{Float64,2}``` before doing any computation. These should actually compute the decompositions using rational arithmetic. Textbook implementations would likely be fine to start with, since the only possible numerical issues are integer overflow. 

Of course it's not always possible to use rational arithmetic. For QR it's pretty reasonable to just convert to floating-point.

**Comment by ViralBShah** [comment]
Much of this works now. Should we still leave this open?
