### ISSUE TITLE
Suggested fixed syntax for deprecation in == is wrong

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#16295]
```jl
julia> type T end

julia> Base.(:(==))(a::T, b::T) = true

WARNING: deprecated syntax "Base.(:==)".
Use "Base.:==" instead.
```

I used `Base.(:(==))` not `Base.(:==)`. Trying to use the latter:

```jl
julia> Base.(:==)(a::T, b::T) = true
ERROR: syntax: invalid identifier name ":="
 in eval(::Module, ::Any) at ./boot.jl:230
```

What I actually should write is:

```jl
Base.:(==)(a::T, b::T) = true
```

For one character operators like `+` the suggestions are correct.

cc @stevengj

**Comment by yuyichao** [comment]
Note that this is `==` specific due to how `=` is parsed. Other multi-character operators like `.+` or `++` are file.

**Comment by KristofferC** [comment]
Thanks for the correction.

**Comment by stevengj** [comment]
Will submit a fix soon.
