### ISSUE TITLE
Docstring headings do not work in manual

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#16296]
According to the [documentation guidelines](http://julia.readthedocs.io/en/latest/manual/documentation/) docstrings should be broken into sections using Markdown headings. I recently did this for [one of my PRs](https://github.com/JuliaLang/julia/pull/12282/files#diff-18ff5efda613bb05a8b004a550205c03R276) and I now noticed that the heading does not get rendered in the HTML.

Sphinx appears to be removing the heading when I run `make -C docs html`:
```
~/Development/Julia/latest/doc/stdlib/dates.rst:555: SEVERE: Unexpected section title.

Examples
********
```

**Comment by omus** [comment]
cc: @MichaelHatherly

**Comment by MichaelHatherly** [comment]
This got brought up in https://github.com/JuliaLang/julia/pull/15136#discussion_r53540712 back when the guidelines where written. Until we move away from RST translating headers to bold within docstrings might be a workable solution, I'll open a PR for comment shortly.
