### ISSUE TITLE
Provide A4 paper size PDF documentation

### ISSUE THREAD

**Issue by softgrow** [JuliaLang/julia#16290]
The PDF download provided under http://readthedocs.org/projects/julia/downloads/ is formatted for 8.5x11 inches. If you are outside North America you will probably not have this paper, but instead only A4 (8.26x11.69 inches). 

Workarounds: 
- Build from source (inconvenient) 
- Try printing as is. May not print nicely. 

To resolve:
Please provide A4 and Letter size for PDF downloads of the documentation. This should meet most peoples needs.

**Comment by ivarne** [comment]
Julia uses readthedocs.org to build our documentation from the source we maintain in our repo. The search term "A4" doesn't appear in their docs, nor their issues, so I don't think they'll see this as a high priority. I would guess most people don't print, or don't mind large top/bottom margins when they do. You might try to report an issue with them at [https://github.com/rtfd/readthedocs.org/issues/new](https://github.com/rtfd/readthedocs.org/issues/new).

**Comment by ufechner7** [comment]
Not nice, that you closed this issue without fixing it. I created an issue
in readthedocs:
https://github.com/rtfd/readthedocs.org/issues/2202

2016-05-10 8:59 GMT+02:00 Ivar Nesje <notifications@github.com>:

**Comment by nalimilan** [comment]
@ufechner7 Keeping an issue open here wouldn't help fixing it, as the bug isn't in Julia. Being "nice" isn't really the question here, if the issue doesn't contribute to improving things. Thanks for filing it upstream.

**Comment by StefanKarpinski** [comment]
These days just managing all the issues that get opened is a fair amount of work. Unfortunately, that means that we're a little faster to close unactionable issues than we used to be. Please don't take it the wrong way – we're just trying to keep the issue tracker under control. Keep in mind that discussion can continue on a closed issue and that issues can always be reopened if the discussion indicates that they should be.
