### ISSUE TITLE
ERROR: UndefVarError: calcCCM not defined

### ISSUE THREAD

**Issue by bmkrishna** [JuliaLang/julia#16293]
I have been trying to run the example script "CCM_example_para_didi" from CauseMap, by executing the code line by line:
while running the command 
" makeoptimizationplots(para, didi,
                                               E_vals, tau_s_vals, tau_p_vals,
                                               "Para.", "Didi.";
                                               nreps=10, left_E=2, left_tau_p=0,   # optional
                                               right_E=7, right_tau_p=12, lagunit=.5,
                                               unit="days", show_tau_s=false # optional
                                           )"
I am encountering an error:

Calculating manifolds

CoordDescent opt1
ERROR: UndefVarError: calcCCM not defined
 in _CoordDescentOpt at C:\Users\User\.julia\v0.4\CauseMap\src\coord_descent_tuning.jl:44
 in CoordDescentOpt at C:\Users\User\.julia\v0.4\CauseMap\src\coord_descent_tuning.jl:12
 in makeoptimizationplots at C:\Users\User\.julia\v0.4\CauseMap\src\plotting.jl:76
BUT
i found the function "calcCCM" to be exported in line 9 of causemap.jl and the corresponding function defined in line 311 of the same file.
The only difference i could find is: 
  var1 and var2 are defined as "var1::AbstractVector, var2::AbstractVector," in line 311 of causemap
whereas
in line 44 of "coord_descent_tuning.jl"
they are passed as "   librange, res12 = calcCCM(source_series, target_series, "
in  line30 of the same file the function _CoordDescentOpt they are defined as
"function _CoordDescentOpt(source_series::Vector{Float64}, target_series::Vector{Float64}, ......."
I could not figure out whether this is the reason for the error or rather how to overcome this error.
(I am using julia Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32)
and windows 10; 64bit
Please help
thanks in advance

**Comment by tkelman** [comment]
Please use either the package's own issues page (https://github.com/cyrusmaher/CauseMap.jl/issues) or the julia-users mailing list for issues in packages.
