### ISSUE TITLE
@inbounds can cause Core.Box

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#16304]
Maybe this is somehow a dup of https://github.com/JuliaLang/julia/issues/15276.

Consider:

```jl
function g{N}(::Type{Val{N}})
    @inbounds f = ntuple(k->k, Val{N}) # This @inbounds causes f to be Core.Box
    @inbounds I = ntuple(k->f[k], Val{N})
    return I
end

@code_warntype g(Val{3})
```

This shows:

```jl
julia> @code_warntype g(Val{3})
Variables:
  #self#::#g
  #unused#::Type{Val{3}}
  f::Core.Box
  #1::##1#3
  I::Tuple{Any,Any,Any}
.
```

Removing the first `@inbounds` fixes everything though:

```jl
function g2{N}(::Type{Val{N}})
    f = ntuple(k->k, Val{N}) 
    @inbounds I = ntuple(k->f[k], Val{N})
    return I
end

@code_warntype g2(Val{3})

Variables:
  #self#::#g2
  #unused#::Type{Val{3}}
  f::Tuple{Int64,Int64,Int64}
  #9::##9#11
  I::Tuple{Int64,Int64,Int64}
  #10::##10#12{Tuple{Int64,Int64,Int64}}
```

**Comment by yuyichao** [comment]
We basically need a more general solution to https://github.com/JuliaLang/julia/issues/15276 I'm not sure if it's useful to keep many issues for different cases but maybe Jeff want to fix simpler cases and closes these issue.

**Comment by KristofferC** [comment]
Depending on if the solution to Core.Box is a "one change to fix em all" or "case by case" influences if multiple issues are useful. I will leave this open but I have thick enough skin to not care if anyone feels like closing it ;)

**Comment by KristofferC** [comment]
I guess this was one of the "case by case"-cases :)

**Comment by tkelman** [comment]
could really use a test
