### ISSUE TITLE
a few places where help and manual are out of sync

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#16303]
Here are some examples. `@threadcall` has a docstring and `?` works at the command line, but the macro doesn't seem to appear anywhere in the manual. Going the other way, exported constants like `OS_NAME` appear in the manual but `?OS_NAME` says no documentation is found.

**Comment by tkelman** [comment]
ref https://github.com/JuliaLang/julia/pull/14264#issuecomment-162965476

**Comment by kshyatt** [comment]
`OS_NAME` is deprecated now, but `@threadcall` still isn't in the manual afaict.

**Comment by vtjnash** [comment]
afaik, `@threadcall` is not in the manual because it is unsupported

**Comment by kshyatt** [comment]
Ok, will close this then. Reopen if needed.

**Comment by tkelman** [comment]
If it's unsupported we shouldn't have it at all. It's exported, so it should be documented. Or we should deprecate it.

**Comment by vtjnash** [comment]
I think that's @StefanKarpinski's call, since he wrote the implementation

**Comment by amitmurthy** [comment]
Mark it as experimental and document it?

**Comment by StefanKarpinski** [comment]
@amitmurthy's suggestion seems like the soundest one. Marking as 0.5.x.
