### ISSUE TITLE
Rationalize fails to round to 0//0

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaLang/julia#16311]
I asked on the julia-user list about the `rationalize` function.

> Does rationalize ever return 0//1 for nonzero inputs?
>
> 0.0+eps(Float64) is much closer to 0//1 than to 1//1.
Why can't I get 0//1 out of rationalize(x) if x != 0.0?
Is this to avoid divide by 0 errors when using a/rationalize(x) where 0 < x <
tol?

For example on julia v0.4.5 
```julia
julia> rationalize(0.0)
0//1

julia> rationalize(0.0+eps(Float64))
1//4503599627370496

julia> rationalize(0.0+eps(Float64);tol=1e-4)
1//1

julia> rationalize(0.0+eps(Float64);tol=1e-4)
1//1
```

Jeffrey Sarnoff said:
> This appears to be a bug. The docs for rationalize say 
> rationalize([Type=Int, ]x; tol=eps(x)) Approximate floating point number x as a
> Rational number with components of the given integer type. The result will
> differ from x by no more than tol.
> 
> meanwhile, here is a "long way around" that may do what you want (signature and
> special cases are cribbed from rational.jl)
> 
> ```julia
> function rationalized{T<:Integer}(::Type{T}, x::AbstractFloat; tol::Real=eps(x))
>     tol < 0 && throw(ArgumentError("negative tolerance'))
>     isnan(x) && return zero(T)//zero(T)
>     isinf(x) && return (x < 0 ? -one(T) : one(T)) // zero(T)
>     rationalize(round(x, floor(Int,abs(log2(tol)))))
> end
> ```

Should the workaround be adopted as the correct version of `rationalize`?
Is this a regression that used to work correctly?

**Comment by JeffreySarnoff** [comment]
The workaround should not be the definition, the bug in the original implementation should be corrected.
