### ISSUE TITLE
is the Julia doc corrupted by python community?

### ISSUE THREAD

**Issue by diam** [JuliaLang/julia#16313]
When I search for a Julia function on the [http://docs.julialang.org](http://docs.julialang.org) site, the result search page give the list of the found page links: ok.
But every Base functions is titled with a python string! 

For example a search for the "exp" string give us the following page:
[http://docs.julialang.org/en/release-0.4/search/?q=exp](http://docs.julialang.org/en/release-0.4/search/?q=exp)

And this page shows as the first result: `Base.exp (Python function, in Mathematics)`

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/11527
