### ISSUE TITLE
should `fill(true, n)` return a BitArray?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#16318]
Then we could potentially deprecate `trues` and `falses`.

**Comment by tkelman** [comment]
I think `fill(true, n)` should stay an `Array{Bool}`.

`fill!(BitArray(n), true)` already works and is more explicit

**Comment by andyferris** [comment]
The problem goes beyond `Bool`, doesn't it? We should probably use `NullableArray` wherever appropriate, etc. So, would we stop at `Bool`? Would people have custom data structures as canonical for certain data types, or do they write it explicitly when they don't want `Array`?

@tkelman's suggest seems scalable to many types to me, like `fill!(NullableArray{Int}(n), Nullable{Int}())` should work fine.

**Comment by JeffBezanson** [comment]
Ok, fine with me to close this. I just wanted to raise the topic.

**Comment by rfourquet** [comment]
Not all users want a bitarray when calling `fill(true, n)`, so having this special case is not clearly a win. (FWIW, it reminds me of the `vector<bool>` "mistake" in C++, although this issue here would probably be less of a problem as it affects only a function, not a type).

**Comment by KristofferC** [comment]
> Ok, fine with me to close this. I just wanted to raise the topic

Looks like the discussion decided against doing the suggestion in the OP.
