### ISSUE TITLE
Type parameters slowing down compilation with many concrete types

### ISSUE THREAD

**Issue by ivirshup** [JuliaLang/julia#16321]
Probably related to #14743. I noticed that calling `unique` on an array of Functions was much much faster to compile than using `counter` from DataStructures.jl, so I cut down the what was going on behind `counter` to figure out why.

Using this basic setup

``` julia
import Base.push!
import Base.getindex
type Accumulator{T, V<:Number}
    map::Dict{T,V}
end
Accumulator{T,V<:Number}(::Type{T}, ::Type{V}) = Accumulator{T,V}(Dict{T,V}())
counter(T::Type) = Accumulator(T,Int)
function counter{T}(seq::AbstractArray{T})
    ct = counter(T)
    for x in seq
        push!(ct, x)
    end
    return ct
end
data = filter!(x->isa(x,Function), map(eval, names(Base)));
data = convert(Array{Function,1}, data);
```

With varying definitions of `push!` and `getindex`

``` julia
# parametric methods
getindex{T,V}(ct::Accumulator{T,V}, x::T) = get(ct.map, x, zero(V))
push!{T,V<:Number}(ct::Accumulator{T,V}, x::T, a::V) = (ct.map[x] = ct[x] + a)
push!{T,V<:Number}(ct::Accumulator{T,V}, x::T) = push!(ct, x, one(V))

# non-parametric methods
getindex(ct, x) = get(ct.map, x, zero(Int)) 
push!(ct::Accumulator, x, a) = (ct.map[x] = ct[x] + a)
push!(ct::Accumulator, x) = push!(ct, x, one(Int))
```

[Using the parametric methods](https://gist.github.com/ivirshup/a511f8e634fd168eb41e940395b8b83b) it takes about 40 seconds and 2.4 GB of memory to compile, but [with the non-parametric methods](https://gist.github.com/ivirshup/976c5dfd3d96aacbde6004327e2b3cc7) it takes about 0.1 seconds and 3.5 MB. Partial compilation speed-ups occur if some of the methods are non-parametric. Looking at the profiles, it seems like the parametric version spends waaaaay more time in inference and a little bit more doing dispatch-y stuff in reflection.

Also if I use unique function names I get a ~4x speedup in compilation of the parametric methods, so dispatch be playing a role too.

**Comment by tkelman** [comment]
ping @vtjnash

**Comment by vtjnash** [comment]
This is largely intentional. Adding `::T` tells the compiler to try to aggressively specialize the method. Adding `::ANY` would have the opposite effect.

**Comment by ivirshup** [comment]
Just to be sure I'm understanding you right:
```julia
foo(x) = ...
# and
foo{T}(x::T) = ...
```
will have different compilation behavior?

**Comment by vtjnash** [comment]
yes. As will `foo(x::ANY)`. It's not strictly necessary for them to diverge, but the specialization mechanism usually prefers to trusts the user over doing blind heuristics.

**Comment by JeffBezanson** [comment]
Yes, but the effect of `ANY` is much more dramatic. It pretty much inhibits specialization entirely, while `x` vs. `x::T` only differ in some corner cases.
