### ISSUE TITLE
Fail on installing Gadfly

### ISSUE THREAD

**Issue by Shoreshen** [JuliaLang/julia#16329]
Heres the error msg:

```
failed process: Process(`git clone -q --mirror git://github.com/JuliaLang/Iterators.jl.git 'C:\Users\shoren\.julia\v0.4\.cache\Iterators'`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
 in include_string at C:\Users\shoren\.julia\v0.4\CodeTools\src\eval.jl:28
 in include_string at C:\Users\shoren\.julia\v0.4\CodeTools\src\eval.jl:32
 [inlined code] from C:\Users\shoren\.julia\v0.4\Atom\src\eval.jl:39
 in anonymous at C:\Users\shoren\.julia\v0.4\Atom\src\eval.jl:62
 in withpath at C:\Users\shoren\.julia\v0.4\Requires\src\require.jl:37
 in withpath at C:\Users\shoren\.julia\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\Users\shoren\.julia\v0.4\Atom\src\eval.jl:61
 in anonymous at task.jl:58
```

**Comment by tkelman** [comment]
Was there any other error message? Can you run that `git clone -q --mirror git://github.com/JuliaLang/Iterators.jl.git C:\Users\shoren\.julia\v0.4\.cache\Iterators` command outside of Julia, say from git-bash? If not, try running `git config --global url."https://".insteadOf git://` from shell mode as described here https://github.com/JuliaLang/julia#source-download-and-compilation

**Comment by Shoreshen** [comment]
sorry, ima new to julia and programming language...........not really know how to do it....

**Comment by Shoreshen** [comment]
INFO: Cloning cache of Iterators from git://github.com/JuliaLang/Iterators.jl.git
INFO: Cloning cache of KernelDensity from git://github.com/JuliaStats/KernelDensity.jl.git
INFO: Cloning cache of Loess from git://github.com/dcjones/Loess.jl.git
INFO: Cloning cache of Measures from git://github.com/dcjones/Measures.jl.git
INFO: Cloning cache of Optim from git://github.com/JuliaOpt/Optim.jl.git
INFO: Cloning cache of PositiveFactorizations from git://github.com/timholy/PositiveFactorizations.jl.git
INFO: Cloning cache of Showoff from git://github.com/dcjones/Showoff.jl.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.120]: errno=No error

ERROR: failed process: Process(`git clone -q --mirror git://github.com/dcjones/Showoff.jl.git 'C:\Users\shoren\.julia\v0.4\.cache\Showoff'`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

**Comment by sahmed95** [comment]
@Shoreshen Hi, even I was facing the same issue but it seems it was due to a connection problem. Try again and check your internet connection.

**Comment by sahmed95** [comment]
I guess this was mostly because of a firewall. Using https instead of git, solves this.

git config --global url."https://".insteadOf git://

**Comment by tkelman** [comment]
@shoreshen please leave another comment if you're still having problems and we'll reopen this.
