### ISSUE TITLE
Parsing numbers via list comprehension is slower than deprecated int(arr)

### ISSUE THREAD

**Issue by brendano** [JuliaLang/julia#16338]
The deprecated method `int(stringlist)` is a bit faster than the recommended alternative.
In the following, `strs` is an `Array{ASCIIString}` that need to be parsed as integers.

Setup
```
julia> strs=[string(x) for x in 1:10000]
julia> using TimeIt
```

Deprecated:
```
julia> @timeit int64(strs);
1000 loops, best of 3: 888.78 µs per loop
```

The recommended alternative:
```
julia> @timeit [parse(Int64,x) for x in strs];
100 loops, best of 3: 7.49 ms per loop
```

(Also, `[int64(x) for x in strs]` is way slower than either, but presumably that's not an issue since this usage is deprecated.)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/8870. See performance tip about globals and don't benchmark loops in global scope.

**Comment by brendano** [comment]
Sorry I didn't even think about the globals issue being related here. Thanks!

**Comment by brendano** [comment]
OK, declaring `const strs=...` causes performance to be the same, even when doing the timing in the global scope.
