### ISSUE TITLE
Some inputs to the `deserialize` function can lead to Segmentation Faults

### ISSUE THREAD

**Issue by bwall** [JuliaLang/julia#16334]
During some exploratory fuzzing of the deserialize function, I found that multiple inputs could lead to segmentation faults or consumption of memory until the Julia process is killed.

I use a similar testing method as the following code stub to test inputs.

```julia
function create_serialization_stream(f::Function)
    s = IOBuffer()
    f(s)
    close(s)
end

function crash(to_write)
  create_serialization_stream() do s
    write(s, to_write)
    seek(s,0)
    try
      deserialize(s)
    catch
      nothing
    end
  end
end
```

The following calls lead to at least 6 GB of memory allocation:
`crash(UInt8[42,207,111,247,29,108,147,51,61,159])`
`crash(UInt8[25,209,79,146,38,118,46,248,145,39,42,154,21,138,121])`
`crash(UInt8[32,58,42,55,66,82,31,6,56,110,152,96,89,124])`
`crash(UInt8[31,42,102,116,1,39,23,45,36,254,12])`
`crash(UInt8[38,42,116,177,129,33,18,143])`
`crash(UInt8[39,42,13,187,175,33,77,171,150,156,83,92])`
`crash(UInt8[17,95,42,59,254,136,33,94,186,230,231,153,102,64,175])`
`crash(UInt8[35,42,203,140,146,36,191,18,222,9,212,165,244,218,47,51])`
`crash(UInt8[21,42,0,128,25,34,205,52,7])`
`crash(UInt8[30,42,133,166,191,29,35,227,177,63])`
`crash(UInt8[34,42,184,29,41,35,99,223,88,68,173,154,174,73,251,36])`
`crash(UInt8[44,208,115,62,250,112,247,181,148,42,222,204,86,36,170,250])`
`crash(UInt8[20,144,142,42,18,47,114,34,104,27,164,119,28,182,39,76])`
`crash(UInt8[19,177,17,100,214,191,246,88,153,135,42,29,154,20,30,211])`
`crash(UInt8[40,25,70,185,68,40,69,95,61,10,41,222,53,24,194,158])`
`crash(UInt8[33,42,170,20,51,41,161,88,143,211,170,244,31,221,158,5])`

The following leads to segmentation faults, and does not appear to be allocation based (at least at a cursory inspection):
`crash(UInt8[37,148,133,39,78,190])`
`crash(UInt8[37,88,55,39,57,193,153,130,197,34,11,172,88])`

**Comment by amitmurthy** [comment]
Thanks!

While not strictly a release blocker, marking this bug as priority as it leaves any code using networking and the inbuilt serialize/deserialize vulnerable.

**Comment by JeffBezanson** [comment]
This doesn't surprise me. The code was written for performance (and is still too slow for many people), and so assumes the stream is correctly formatted.

I don't believe there is a general solution, since there is no way to know if the data for an arbitrary object is actually valid. Every type would need a validation function of some kind, which we are not going to require, and which would be way too slow if we did.

If you get into a situation where an attacker can send arbitrary bytes to one of your julia processes, don't you have much worse problems than julia crashing? For example they could send *correctly* formatted data that requests execution of any shell command or exported C function.

**Comment by bwall** [comment]
#16292 is intended to make that far more difficult for an attacker to do

**Comment by amitmurthy** [comment]
For the specific case of a Julia cluster, we could avoid calling `deserialize` for the cookie read. i.e., we read only the length of the cookie directly from the socket first and disconnect if it does not match.

For other user programs, which do not use Julia parallel, but do use serialize/deserialize for messaging, we could explicitly mention in the documentation that the Julia serialization format is designed keeping simplicity and performance as a goal, and that users must secure their messaging by other means (for example, signing each payload and verifying the signature before deserializing).

**Comment by JeffBezanson** [comment]
Yes, that sounds good. #16292 is a very good change as well.
