### ISSUE TITLE
JLD package not working

### ISSUE THREAD

**Issue by laborhm** [JuliaLang/julia#16346]
Installed both HDF5 and JLD. Issuing the command `using JLD` raises a bunch of warnings and an error, 
including:
```
WARNING: Module HDF5 uuid did not match cache file. This is likely because module HDF5 does not support precompilation but is imported by a module that does
WARNING: deserialization checks failed while attempting to load cache from %USERPROFILE%\.julia\lib\v0.4\JLD.jl
...
ERROR: __precompile__(true) but require failed to create a precompiled cache file in require at loading.jl:268
```

How can I go about this problem (in Windows10, JL 0.4.5)? Thanks in advance.

**Comment by timholy** [comment]
What happens if you start a fresh julia session and say `using JLD`?

**Comment by laborhm** [comment]
using JLD - passed silently
issuing fld = jdlopen(joinpath(pwd(),"data","mydata.jld"), "w")  raises another one:
ERROR: UndefVarError: jdlopen not defined

**Comment by laborhm** [comment]
Sorry for troubling again. Looks like it's not JLD that doesn't operate...)) Mistyping error. Ple delete this branch. B.R.

**Comment by laborhm** [comment]
Solved. Obviously, not my day today.)) Ple remove this branch.

**Comment by tkelman** [comment]
In the future it's preferred to go to the mailing list before github with general questions, until you're sure it's a bug (usually a contributor will confirm when something looks like it's definitely a bug).
