### ISSUE TITLE
multithreading for interactivity

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#16350]
If I run the following code in a REPL (v0.4.5), I find that the REPL becomes very unresponsive. It will take many seconds to respond to just typing a few letters. In contrast, if I run the same code in an iJulia notebook, the iJulia notebook remains responsive to typing, even if it takes longer to evaluate things. It would be nice if the REPL remained responsive as well.

``` julia
function dowork(n)
       t = 0.0
       for i=1:n
       t+= @elapsed sort(rand(10^5))
       yield()
       end
       t
       end

 for i=1:100 @schedule dowork(1000) end
```

**Comment by yuyichao** [comment]
This probably requires a multithreaded repl.
