### ISSUE TITLE
Syntax issues with hexadecimal prefix

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#16356]
I was messing around with how the syntax for the hexadecimal prefix works while thinking about #15731 and I found something entertaining:

``` julia
julia> 0xenomorph
ERROR: UndefVarError: nomorph not defined

julia> xenomorph = 1
1

julia> 0xenomorph
ERROR: UndefVarError: nomorph not defined

julia> nomorph = 2
2

julia> 0xenomorph
28

julia> 0xgnomorph
ERROR: syntax: malformed expression

julia> 0xefnomorph
478
```

Maybe we should disallow juxtaposition with hexadecimals? Seems like it will just lead to confusion.

**Comment by JeffBezanson** [comment]
My favorite part is that the syntax coloring in github gets it exactly right :P

**Comment by omus** [comment]
Syntax highlighting makes it obvious what is going on. In the REPL however it isn't very clear.

**Comment by Keno** [comment]
The solution is clear: Add syntax highlighting to the REPL.

**Comment by omus** [comment]
I agree that adding syntax highlighting to the REPL would be great and would solve this issue. For this issue however I slightly lean towards disallowing juxtaposed hexadecimals as it avoids any potential confusion when syntax highlighting is unavailable.

**Comment by toivoh** [comment]
+1 to disallowing juxtaposed hexadecimals. I see no mathematical precedent
for that, and it seems highly confusing that the matter of where the
literal ends and the next symbol begins depends on which is the first
character after f in the alphabet.

**Comment by omus** [comment]
If we're disallowing juxtaposed hexadecimals we probably also want to do the same for binary and octals

```
julia> xep = 3
3

julia> 0xep0xep
42.0

julia> b0 = 2
2

julia> 0b1b0
2

julia> o0 = 3
3

julia> 0o1o0
3
```

**Comment by KristofferC** [comment]
> The solution is clear: Add syntax highlighting to the REPL.

![image](https://user-images.githubusercontent.com/1282691/27513824-fa85d8f8-5975-11e7-8864-da4e33feb8e2.png)

**Comment by omus** [comment]
Looks like the syntax highlighting isn't quite right for the second last example. I believe it should highlight `0x` and not just `0`:
```julia
julia> 0x
ERROR: syntax: invalid numeric constant "0x"

julia> 0xg
ERROR: syntax: invalid numeric constant "0x"

julia> g = 1
1

julia> 0xg
ERROR: syntax: invalid numeric constant "0x"

julia> xg = 1
1

julia> 0xg
ERROR: syntax: invalid numeric constant "0x"
```
