### ISSUE TITLE
Atom STDIN

### ISSUE THREAD

**Issue by AnthonyJacob** [JuliaLang/julia#16365]
It is not possible to readline(STDIN) int atom.

When I evaluate block @show readline() and then I type "Hello world!" in atom console and hit enter, nothing happens

**Comment by StefanKarpinski** [comment]
This seems like an Atom issue, not a Julia one, no?

**Comment by AnthonyJacob** [comment]
Sorry, my mistake!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Bez
virů. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-05-14 13:41 GMT+02:00 Stefan Karpinski <notifications@github.com>:

**Comment by StefanKarpinski** [comment]
I'm not positive, but I think https://github.com/JunoLab/Atom.jl/issues is where you should file issues.
