### ISSUE TITLE
Atom plotting

### ISSUE THREAD

**Issue by AnthonyJacob** [JuliaLang/julia#16367]
Atom is not using all space for plotting graphs

[image](http://i.imgur.com/oXXq1dV.png?1)

Also you have to use C^Enter to show it, because C^Shift^Enter doesn't do anything (plot(x = [1], y = [1]))

I am using gadfly.

**Comment by StefanKarpinski** [comment]
This is not the right place for Atom/Juno issues.

**Comment by kmsquire** [comment]
Cc: @MikeInnes, it's unclear from the outside which of [these repos](https://github.com/JunoLab) should be the target of this report...

**Comment by ufechner7** [comment]
I would post this issue here:
http://discuss.junolab.org/top/all

**Comment by MikeInnes** [comment]
Yup, Juno Discuss is right for this issue. We have that listed in a few places, I'm not sure where else we can put it that will help.

@AnthonyJacob this is just because the size of the plot pane isn't known before it first opens. If you run the plot again it should be fixed.
