### ISSUE TITLE
Integer division by 2 is 6x slower with FastISel

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#16375]
The following code is slightly modified from my answer to http://stackoverflow.com/questions/37193586/bigints-seem-slow-in-julia (a solution for Project Euler problem 78), a memoized calculation of number of partitions of integers.

(I don't guarantee that it is a correct solution but) I do see a **3-fold slowdown** from 0.4.5 to 0.5:

https://gist.github.com/bc07c76f6330799595f6f41fb0380307

0.4.5:    10.695675 seconds (5 allocations: 192 bytes)
0.5.0-dev+4088:    33.703394 seconds (5 allocations: 192 bytes)

**Comment by yuyichao** [comment]
LLVM issue? I see the same timing on `0.5.0-dev+4086` with LLVM 3.8.0 and on 0.4.6-pre+18 with LLVM 3.7.1.

**Comment by yuyichao** [comment]
`-O3` on master reduces it from 40s to 12s ....

**Comment by yuyichao** [comment]
OK, I believe this is FastISel's fault. The slow versions (0.4 llvm 3.7 default opt level and with `-O`, master llvm 3.8 default opt level) all have FastISel on. The fast versions (0.4 llvm 3.3, master llvm 3.8 with `-O3`) all have FastISel off.

Commenting out the line enabling fastisel reduces the runtime to 12s here without `-O3` on master so I'm convinced that this is the issue.

@Keno is this performance difference expected?

**Comment by yuyichao** [comment]
[LLVM IR and asm without FastISel (the one with better performance)](https://gist.github.com/yuyichao/53d79fdaa8b8df35a5423be94de1a918).

[LLVM IR and asm with FastISel (the one with worse performance)](https://gist.github.com/yuyichao/bdff579131fcd35701a0ce114a3b7573)

**Comment by yuyichao** [comment]
AND, noticing the missing of `idivq` in the non-fast version of asm ..... I believe this is due to the integer division.

```jl
@noinline f(n) = n ÷ 2

function g(n)
    for i in 1:n
        f(i)
    end
end

@code_native f(10)

@time g(10)
@time g(1_000_000_000)
```

On master by default

```asm
        .text
Filename: div.jl
Source line: 0
        pushq   %rbp
        movq    %rsp, %rbp
        movl    $2, %ecx
Source line: 3
        movq    %rdi, %rax
        cqto
        idivq   %rcx
        popq    %rbp
        retq
        nopw    %cs:(%rax,%rax)
  0.004269 seconds (1.61 k allocations: 73.923 KB)
 11.059803 seconds (4 allocations: 160 bytes)
```

With `-O3`

```asm
        .text
Filename: div.jl
Source line: 0
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 3
        movq    %rdi, %rax
        shrq    $63, %rax
        leaq    (%rax,%rdi), %rax
        sarq    %rax
        popq    %rbp
        retq
        nopw    %cs:(%rax,%rax)
  0.004843 seconds (1.61 k allocations: 73.923 KB)
  1.764239 seconds (4 allocations: 160 bytes)
```

So LLVM don't want to replace the division with a shift without fastisel......

The LLVM IR is identical in both cases.

**Comment by yuyichao** [comment]
And finally, .......... as what you might expect..... replacing `÷ 2` with `>> 1` in your code makes the runtime less than 12s here on all versions.

**Comment by StefanKarpinski** [comment]
IIRC, our integer division has a bunch of extra nonsense to avoid LLVM willfully emitting junk values in undefined cases, namely division by zero – but only in the case where LLVM knows that the divisor is zero at compile time. If we could figure out a way to avoid that nonsense, integer division would get faster in general.

**Comment by yuyichao** [comment]
I don't think the code we emit is the issue here at least. The LLVM IR is as simple as it can possibly be here.

```
julia> @noinline f(n) = n ÷ 2
f (generic function with 1 method)

julia> @code_llvm f(2)

define i64 @julia_f_49935(i64) #0 !dbg !6 {
pass:
  %1 = sdiv i64 %0, 2
  ret i64 %1
}
```

**Comment by StefanKarpinski** [comment]
Ah yeah, in this case the divisor is a known non-zero value, so that's not the issue. Carry on.

**Comment by yuyichao** [comment]
The zero check we emit also needs to be performed anyway. Dividing by zero is UB and the integer division instruction may trap or not depending on the architecture. The additional branch caused by that is also negligible compare to the actual cost of the integer division.....

**Comment by yuyichao** [comment]
Comparing the case where LLVM constant folds the branch but failed to use bitshift and the fully generic case with check for signed overflow and divide by zero, the fully generic case indeed has more instruction but the time it takes is very similar....

```
julia> f(a) = a ÷ 2
f (generic function with 1 method)

julia> f(a, b) = a ÷ b
f (generic function with 2 methods)

julia> @code_native f(1)
        .text
Filename: REPL[1]
Source line: 0
        pushq   %rbp
        movq    %rsp, %rbp
        movl    $2, %ecx
Source line: 1
        movq    %rdi, %rax
        cqto
        idivq   %rcx
        popq    %rbp
        retq
        nopw    %cs:(%rax,%rax)

julia> @code_native f(1, 2)
        .text
Filename: REPL[2]
Source line: 0
        cmpq    $0, %rsi
        je      L36
        movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
        cmpq    %rax, %rdi
        jne     L27
        cmpq    $-1, %rsi
        je      L36
L27:
        movq    %rdi, %rax
        cqto
        idivq   %rsi
        retq
L36:
        pushq   %rbp
        movq    %rsp, %rbp
        movabsq $jl_diverror_exception, %rax
        movq    (%rax), %rdi
        movabsq $jl_throw, %rax
        callq   *%rax
        nopw    %cs:(%rax,%rax)

julia> using Benchmarks

julia> @benchmark f(1)
================ Benchmark Results ========================
     Time per evaluation: 10.77 ns [10.50 ns, 11.03 ns]
Proportion of time in GC: 0.00% [0.00%, 0.00%]
        Memory allocated: 0.00 bytes
   Number of allocations: 0 allocations
       Number of samples: 2501
   Number of evaluations: 20901
         R² of OLS model: 0.959
 Time spent benchmarking: 1.77 s


julia> @benchmark f(1, 2)
================ Benchmark Results ========================
     Time per evaluation: 11.16 ns [10.94 ns, 11.37 ns]
Proportion of time in GC: 0.00% [0.00%, 0.00%]
        Memory allocated: 0.00 bytes
   Number of allocations: 0 allocations
       Number of samples: 4601
   Number of evaluations: 160601
         R² of OLS model: 0.956
 Time spent benchmarking: 3.14 s
```

**Comment by vtjnash** [comment]
Is this a critical v0.5 issue? I think the solution/workaround will be to write a new LLVM Pass and register that in our pass manager to run after all the other passes to lower an idiv IR to the right combination of shifts. That's not hard, but it's also not a trivial amount of work.

**Comment by ViralBShah** [comment]
If this needs to be done to fix our performance regressions, then it is important for 0.5.

**Comment by JeffBezanson** [comment]
We simply can't have performance regressions. It really is a slap in the face to pay so much more in compile time and get worse code out.

We could at least hack this in to our own `div` intrinsic --- not as good since it doesn't take llvm's constant folding into account, but better than nothing.

**Comment by timholy** [comment]
> I think the solution/workaround will be to write a new LLVM Pass and register that in our pass manager to run after all the other passes to lower an idiv IR to the right combination of shifts. That's not hard, but it's also not a trivial amount of work.

We kind of already [have this](https://github.com/JuliaLang/julia/blob/master/base/multinverses.jl), although it's in julia so perhaps it won't help. Of course it's much more general than powers of 2, which means it will be much faster for non-powers of 2 but slower for powers of 2.
