### ISSUE TITLE
Using pmap with multiple anon functions as arguments gives error

### ISSUE THREAD

**Issue by jonbarkerlondon** [JuliaLang/julia#16387]
First of all, I'm no Julia expert, so please forgive me if this is user error.

Under the following circumstances, i am unable to use pmap to call an anon function within an anon function.

The following error is displayed: 

 - `UndefVarError: 27#54 not defined`
 - `in #26 at [file.jl:pmap line of code]`

When running the following code:
```jl
pmap(arg -> method1(() -> method2(arg)), input_args_array, err_stop=true)

@everywhere function method1(sub_func)
    sub_func()
end`

@everywhere function method2(arg)
    println(arg)
end
```

Note this only occurs if I run up julia with `-p 1`. If i don't include `-p 1` everything works fine.

This also only occurs with -p 1 if i use 2x anon funcs. If i do the following it works fine:
`arg -> method1()`
`arg -> method1(method2)`

Thanks,
Jon

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15451 ?

**Comment by JeffBezanson** [comment]
Yes this appears to be a duplicate.
