### ISSUE TITLE
Pkg.submit() not working on Linux, can't find curl

### ISSUE THREAD

**Issue by Pbellive** [JuliaLang/julia#16407]
Hi,
       I tested this on the latest 0.4 release, the version info is:
```
Julia Version 0.4.6-pre+35
Commit e3ac4d1 (2016-05-13 09:37 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Also tested on 0.4.6-pre+18 (2016-04-01 03:37 UTC), Commit 198644a. I'm trying to submit a pull request for some changes I made to an unregistered package installed via `Pkg.clone()`. I get the error
```
julia> Pkg.submit("jInv")
INFO: Forking JuliaInv/jInv.jl to Pbellive
ERROR: could not spawn `curl --version`: no such file or directory (ENOENT)
```

I noticed that access to curl has been an issue for `Pkg.submit()` on Windows (#14813) but I haven't found any reference to the problem I'm having on Linux.

**Comment by timholy** [comment]
What happens when you type `curl --version` on the Linux command line?

**Comment by Pbellive** [comment]
Thanks for the quick response Tim. I get:
```
$ curl --version
The program 'curl' is currently not installed. You can install it by typing:
sudo apt-get install curl
```

I'm sorry, I should have mentioned that in my initial post. I thought that Julia was supposed to have its own version of curl or that it should be installed when installing Julia. If I'm completely wrong on that and I just need to install curl on my system then I'm sorry for wasting your time.

**Comment by Pbellive** [comment]
I see now that curl is listed as a required build tool on the main julia repo readme. So I'm completely in the wrong and this isn't a bug. I'll close this issue. However, I still think it's odd that I was able to build julia from source and install external dependencies without having curl installed, if it is indeed a required external build tool.
