### ISSUE TITLE
Bikeshedding filtered generator syntax

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#16428]
This started coming up in #16389 but it's a little off topic, so perhaps we should branch this discussion out into a separate issue.

@StefanKarpinski mentioned the nice, familiar syntax
```julia
x^2 if x % 3 == 0 for x = 1:100
```
which follows more closely what other languages do.

I had also proposed using `where`, e.g.
```julia
x^2 for x = 1:100 where x % 3 == 0  # or,
x^2 where x % 3 == 0 for x = 1:100
```
This, at least in my mind, makes the filtering aspect a little clearer than `if`, since `if` looks like it should be modifying the computation rather than the iterator. (Which perhaps is a little narrow-minded of me.)

Thoughts?

**Comment by ararslan** [comment]
I could also imagine `where` extending to other scenarios, e.g.
```julia
s = 0
for x = 1:100 where x % 3 == 0
    s += 1
end
```
This super contrived example would be equivalent to
```julia
s = 0
for x = 1:100
    if x % 3 == 0
        s += 1
    end
end
```
(or whatever single-line `if` comes about from #16389)

**Comment by JeffBezanson** [comment]
This can be moved to #550. We are also likely to use `where` for #11310.

**Comment by ararslan** [comment]
@JeffBezanson Okay, sounds good. Thanks!
