### ISSUE TITLE
Re-evaluating parameterized type definitions erros

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#16424]
I noticed this inconsistency (both in 0.4 and 0.5):

``` julia
julia> type B
       a
       end

julia> type B
       a
       end

julia> type A{T}
       a
       end

julia> type A{T}
       a
       end
ERROR: invalid redefinition of constant A
```

Would be nice if the second would not error.

**Comment by KristofferC** [comment]
A little bit of discussion here: https://groups.google.com/forum/?nomobile=true#!topic/julia-users/OM-NJMkkVoY

**Comment by mauro3** [comment]
I thought this must have been discussed somewhere.

**Comment by cstjean** [comment]
@vtjnash It seems that this code now fails:

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2778 (2017-02-12 11:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 71f6bc9 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> immutable X{T}
          a::T
       end

julia> immutable X{T}
          a::T
       end
ERROR: invalid redefinition of constant X
```

Is that a regression? It's a big bummer for https://github.com/cstjean/ClobberingReload.jl/issues/1#issuecomment-279239144 cc. @rdeits

**Comment by rdeits** [comment]
awesome, thanks @JeffBezanson and @cstjean

**Comment by cstjean** [comment]
Some definitions still cannot be reevaluated:

```julia
julia> const TupleOf{T} = NTuple{N, T} where {N}
Tuple{Vararg{T,N}} where N where T

julia> const TupleOf{T} = NTuple{N, T} where {N}
ERROR: invalid redefinition of constant TupleOf
```

**Comment by yuyichao** [comment]
That's not a type definition.

**Comment by cstjean** [comment]
Then parametric type aliases cannot be reevaluated. MWE: `MyVector{N} = Vector{N}`. Should this be a new issue? I couldn't find anything relevant.

**Comment by JeffBezanson** [comment]
We allow re-assigning constants if the new value is identical. We could expand the definition of "identical" for this case.

**Comment by cstjean** [comment]
Similar to the type-alias case, this type definition cannot be reevaluated:
```julia
struct GG{T<:(Vector{U} where U <: Integer)} end
```
