### ISSUE TITLE
what's the minimum required git version for the Package manager? docs.

### ISSUE THREAD

**Issue by floswald** [JuliaLang/julia#16448]
i frequently run into a problem like

```julia
julia> Pkg.checkout("PyCall","marcotools-fix")
INFO: Checking out PyCall marcotools-fix...
error: unknown switch `B'
usage: git checkout [options] <branch>
   or: git checkout [options] [<branch>] -- <file>...

    -q, --quiet           be quiet
    -b <new branch>       branch
    -l                    log for new branch
    -t, --track           track
    --orphan <new branch>
                          new unparented branch
    -2, --ours            stage
    -3, --theirs          stage
    -f, --force           force
    -m, --merge           merge
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively

ERROR: failed process: Process(`git --work-tree=/home/florian_o/.julia/v0.4/PyCall --git-dir=/home/florian_o/.julia/v0.4/PyCall/.git checkout -q -B marcotools-fix -t origin/marcotools-fix`, ProcessExited(129)) [129]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 in anonymous at pkg/entry.jl:192
 in transact at pkg/git.jl:97
 in _checkout at pkg/entry.jl:190
 in checkout at pkg/entry.jl:205
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
```

which arises for example on remote systems without root access where an old version of git is installed (`git version 1.7.2.5`). a fix is of course to checkout the required branch manually. maybe an entry on the docs for `Pkg` telling users whats the minimum git version assumed by `Pkg.checkout` would be helpful for less experienced users. (irrelevant if you think that less experienced users will ever have an old git lingering around).

**Comment by tkelman** [comment]
Should be 1.7.3 for 0.4 (and documented in the readme for that branch, and should be getting checked by Pkg), not applicable on master.

**Comment by floswald** [comment]
ok i see. i didn't know it was mentioned in the readme. to be fair, the section is "external software required to build julia", which is not what I think when I install a package. but this seems to be a minor issue, so close whenever you want.

**Comment by tkelman** [comment]
There should be a check for this when you first run `Pkg.init` that would give an error if your git is too old. Did that not happen here?

**Comment by floswald** [comment]
so i didn't pay a lot of attention, but given that i just upgraded to 0.4.5
on that system, and given that I reinstalled all packages, i assume that
there was a call to `Pkg.init`. I am definitely sure that I didn't get a
warning about an old git version.

**Comment by tkelman** [comment]
No longer relevant on master. We can reopen for possible backporting if you can identify why the check didn't run.
