### ISSUE TITLE
Build failure on Arch: could not load library "libgit2"

### ISSUE THREAD

**Issue by lmshk** [JuliaLang/julia#16459]
Building master julia (`make`) on a current Arch linux (x86_64) fails with the following error:

```
LoadError(at "sysimg.jl" line 310: LoadError(at "libgit2.jl" line 13: LoadError(at "libgit2/consts.jl" line 277: ErrorException("error compiling version: could not load library "libgit2"
libhttp_parser.so.2.6.2: cannot open shared object file: No such file or directory"))))
```

Points of interest:
- This is the first mention of both `libgit` and `libhttp` in all of the compiler output.
- It also tells me to `make cleanall`, which did not solve the problem.
- Comiler output is littered with messages like: `libtool: install: warning: '../libfftw3.la' has not been installed in '/path/to/julia/usr/lib'` and `libtool: warning: remember to run 'libtool --finish /path/to/julia/usr/lib'` -- running that command does not solve the problem.

**I can build perfectly if I install `libgit2` from `extra`**, but `README.md` tells me that julia should actually build that itself. Am I missing something? Is `libgit2` now a dependency?

**Comment by tkelman** [comment]
What seems to have happened is Julia's build of libgit2 picked up your system copy of libhttp_parser at build time but then can't find it when Julia tries to dlopen libgit2? Check `ldd /path/to/julia/usr/lib/libgit2.so`

**Comment by lmshk** [comment]
You are right, this prints:

    ...
    libhttp_parser.so.2.6.2 => not found
    ...

I have `community/http-parser `**`2.7.0-1`**` [installed]` though, and `ls /usr/lib/libhttp_parser*` prints:

    /usr/lib/libhttp_parser.so  /usr/lib/libhttp_parser.so.2.7.0

**Comment by tkelman** [comment]
Someone's build system may be getting their sonames wrong?

**Comment by tkelman** [comment]
You can also do `make -C deps distclean-libgit2 && make -j4 -C deps install-libgit2` to rebuild Julia's own copy of libgit2 and see what its cmake output is saying without all the other dependencies building at the same time.

**Comment by lmshk** [comment]
I ran that, and the only reference to http-parser is:

    -- Found HTTP_Parser: /usr/include

`/usr/include/http_parser.h` contains:

    #define HTTP_PARSER_VERSION_MAJOR 2
    #define HTTP_PARSER_VERSION_MINOR 7
    #define HTTP_PARSER_VERSION_PATCH 0

which is preceded by

    /* Also update SONAME in the Makefile whenever you change these. */

However, the makefile for http-parser 2.7.0 contains

    SONAME ?= libhttp_parser.so.2.7.0

and as far as I can see, no other `SONAME` is passed from the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/http-parser).

**Comment by tkelman** [comment]
and what about readlink on `/usr/lib/libhttp_parser.so` ?

**Comment by tkelman** [comment]
We also should be setting an env var to prevent pkg-config from picking up the system copies of things by default, wonder why that didn't work here...

**Comment by lmshk** [comment]
`libhttp_parser.so -> libhttp_parser.so.2.7.0`

**Comment by lmshk** [comment]
I reran `make cleanall` and `make` and now building works perfectly. Maybe the `make distclean-libgit2` fixed it?

**Comment by tkelman** [comment]
Odd. Maybe you upgraded system version of http-parser and just needed to rebuild and relink against the new soname?

**Comment by wildart** [comment]
`libgit2` compiles its own http-parser if could not find system one.

**Comment by lmshk** [comment]
@tkelman That seems likely. I upgraded `http-parser` on 2016-04-21, which is approximately when the error started happening.
So I guess we can close this? (But maybe the error that tells us to `make cleanall` should also suggest `make distcleanall` in case that doesn't work?)

**Comment by wildart** [comment]
So, using system libraries could become problematic. I think it's better to disable compilation againts system http-parser library.

**Comment by tkelman** [comment]
Or since libgit2 is building its own anyway, we should maybe just build it as a separate library so the webstack can use it too.

**Comment by wildart** [comment]
No, we do not want http-parser for webstack. We need a native http parser. Hopefully, HTTP/2 will be done this summer, then we can look at porting HTTP/1.1.

**Comment by tkelman** [comment]
I'm talking about now, not 6 months from now. And we won't be eliminating libgit2's need for it. HttpParser.jl could potentially already use the copy from inside libgit2, if we controlled whether it was always built into the same library.

**Comment by wildart** [comment]
Then by all means add it into build.

**Comment by KristofferC** [comment]
Please comment if this still happens.
