### ISSUE TITLE
Implement Power ABI

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#16455]
As the [power port is advancing rapidly](https://github.com/julialang/julia/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3APower+), the biggest remaining hurdle is now the C ABI. Opening this issue to track work towards getting the ABI working on Power.

**Comment by edelsohn** [comment]
This involves implementation of the PPC64 ELFv2 ABI in the Julia front-end for LLVM -- matching the definition in the LLVM backend for PPC64, and addressing lingering testsuite failures.

**Comment by ViralBShah** [comment]
The Vector ABI remains now. @edelsohn Would be great if someone on your side can test this out.

**Comment by edelsohn** [comment]
We have done some more testing, but it is unclear which tests should succeed without vector ABI support, i.e., the expected status of the testsuite is confusing.

**Comment by yuyichao** [comment]
I dont think any part of the test should depend on vector abi on power

**Comment by edelsohn** [comment]
We still see a number of errors with "make check".  Are those present in your tests?  Have they been traced to Julia code or LLVM code?

**Comment by yuyichao** [comment]
(I dont have the hardware but) I think it would be better to just paste the error.

**Comment by StefanKarpinski** [comment]
Or send to @ViralBShah if preferred.

**Comment by Keno** [comment]
What version of LLVM did you try with? I know @vtjnash had to fix a couple LLVM bugs. I believe they all should be in the build system if you're using the default configuration, but you may not have them yet if you're using a custom LLVM.

**Comment by vtjnash** [comment]
I ran into a number of openblas bugs, so I had to run the testsuite against the system reference blas. The result was that all tests passed for me (for reference, the last time I've run the whole test-suite was merging #16677).

I started writing tests for the POWER vector ABI: https://github.com/JuliaLang/julia/commit/33209f38d97a3d8a31f9f54f4b838cfe02be36ac, but they aren't yet part of the regular test-suite.

**Comment by edelsohn** [comment]
Have you reported any of the OpenBLAS bugs?

**Comment by vtjnash** [comment]
no, I hadn't worked on isolating them

**Comment by edelsohn** [comment]
Would you please reach out to Xianyi about the testsuite failures that are tied to OpenBLAS?

**Comment by Keno** [comment]
Vector ABI is merged, this should be complete.

**Comment by ViralBShah** [comment]
cc @xianyi
