### ISSUE TITLE
Stand-alone executable in standard OSX install directory /Applications/Julia-x.x.x.app/Contents/MacOS does not process command-line arguments

### ISSUE THREAD

**Issue by iacolippo** [JuliaLang/julia#16452]
Calling `julia -p 2` from the terminal (also with `julia -p 3` or 4), `nprocs()` returns always 1. Calling `addprocs(n)` works. I have 2 physical cores and 4 virtual cores.

Tried in

Julia Version 0.5.0-dev+3488
Commit e1cf87f\* (2016-04-11 17:05 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

Also tried in Julia 0.4. I work in OS X 10.9.5, but I tried also in El Captain, same result.

**Comment by andreasnoack** [comment]
I can't reproduce this on my Mac. Could you try and see if it also happens with latest master?

**Comment by iacolippo** [comment]
For sure, I will try tomorrow night, when I'll have decent internet connection.

**Comment by iacolippo** [comment]
I tried with

Julia Version 0.5.0-dev+4268
Commit fd559d3 (2016-05-22 01:51 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

still it doesn't work. I'm not building from source, because I've some problem with dependencies and I'm looking how to fix it. I installed Julia from the nightly build DMG file. To call Julia from the terminal I'm using `export PATH="/Applications/Julia-0.5.app/Contents/MacOS:${PATH}"` saved in .bash_profile. It doesn't work even if I go in Julia directory and call it with `./Julia -p 2`.

**Comment by ViralBShah** [comment]
cc @amitmurthy

**Comment by amitmurthy** [comment]
Try launching `/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -p 2` and not `/Applications/Julia-0.5.app/Contents/MacOS/Julia`

I don't know what `...../MacOS/Julia` is supposed to represent.

**Comment by iacolippo** [comment]
The command you propose works. At this point I don't know it too, it launches Julia, but it can't start it with more than one worker. 
Anyway I think maybe this should be made more clear in the documentation. A lot of people I know with Mac had my same difficulties.
Thank you!

**Comment by amitmurthy** [comment]
A cursory read through https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19 leads me to believe that `..../MacOS/Julia` ought to be the stand-alone executable with the `Resources` folder just having "resources" required for the stand-alone executable.

Currently the stand-alone executable `..../MacOS/Julia` does not process any arguments and always brings up a REPL, for example, `Julia -e "println(1)"` does not work as intended.

Documenting use of  `..../Resources/julia/bin/julia` should be done only if this is not going to be corrected in the near future as the behavior is non-standard.

**Comment by ViralBShah** [comment]
Let's reopen if still an issue. I don't think it is.
