### ISSUE TITLE
`match` returns me `SubString{UTF8String}` when the input is `ASCII`

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#16457]
That's very annoying, as I have to cast back to `ASCIIString` in my case.
```
x = "total"
typeof(match(r"(.*)", x).captures[1])
>>> SubString{UTF8String}
typeof(x)
>>> ASCIIString
```

**Comment by StefanKarpinski** [comment]
We can't change this behavior on 0.4.x and this is not an issue anymore on 0.5-dev.

**Comment by colinfang** [comment]
After some digging into other issues, I realized you killed `ASCIIString`.

**Comment by StefanKarpinski** [comment]
This sort of issue is one of the reasons why 👍.
