### ISSUE TITLE
@time 1 +4 vs. @time 1+ 4

### ISSUE THREAD

**Issue by hgeorgako** [JuliaLang/julia#16461]
Not sure if this is expected behavior: 

```jl
@time 1 +4
ERROR: wrong number of arguments

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
```

**Comment by yuyichao** [comment]
Using space as separator for macro call is space sensitive. The alternative would be to parse `@time 1 + 4` as `@time(1, +, 4)`, which I believe is even more confusing.

**Comment by ivarne** [comment]
See also https://github.com/JuliaLang/julia/issues/2861
