### ISSUE TITLE
`workspace` should provide a way to detect already-initialized modules

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16467]
For some C libraries (see stevengj/Blosc.jl#19), it is not safe to initialize them more than once, nor do we want to register an `atexit` hook more than once.    However, if you do a `workspace()` then re-import the module, its `__init__` is called a second time.   It would be good to have a documented way to check whether a module was already initialized in a previous workspace.

(It's not sufficient to look at `LastMain` because the user could call `workspace()` twice.)

For example, there could be some kind of `module_init_called(modulename)` function that looks up a module in a global list of initialized modules that persists across `workspace` calls.

**Comment by yuyichao** [comment]
Milestone moved from #18646

**Comment by maleadt** [comment]
Related: calling `reload($PKG)` does the same, so it would be nice for a fix to span both cases.

**Comment by JeffBezanson** [comment]
Fixed by #17997. Now top-level modules are kept in a hidden internal table, so `using X` in a new Main module just re-references the same module. An explicit `reload` is needed to actually load again.
