### ISSUE TITLE
String constructor can segfault

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#16470]
```julia
julia> String(convert(Ptr{UInt8}, 1))
Segmentation fault: 11
```

expected result: `MethodError`, `"Ptr{UInt8}(1)"`, anything but crashing?

Julia constructors shouldn't segfault, only methods that can should have `unsafe_` in the name

**Comment by nalimilan** [comment]
Cf. discussion following https://github.com/JuliaLang/julia/issues/16107#issuecomment-217533456. I also think methods playing with pointers should all be marked `unsafe_*`, but @stevengj has a different opinion.

**Comment by StefanKarpinski** [comment]
I don't really have a strong opinion here so whenever you guys decide what we should call this, I'll change it. If this is going to go out of the `String` constructor, then it should be part of the same function as `pointer_to_string`, which is a terrible name and also doesn't start with `unsafe_`.

**Comment by stevengj** [comment]
(If we rename `pointer_to_string`, we should also rename `pointer_to_array`.)

Maybe just `unsafe_string(ptr, [len])` for the copying constructor (analogous to the old `bytestring(ptr, len)` function).

**Comment by nalimilan** [comment]
We could also have a more generic API, which would allow extensions for custom string types. Something like `unsafe_constructor(String, ptr, [len])` and `unsafe_constructor(Array, ptr, dims)`.
