### ISSUE TITLE
Clearer error message when trying to use defined but uninitialized variable?

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#16496]
When trying to use a variable that has been declared but not given a value, the error message just says that the variable is `not defined`. This is confusing since it seems like that Julia doesn't recognize the variable at all.

```
julia> function f()
           local z
           z
       end

f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: z not defined
 in f() at ./none:3
 in eval(::Module, ::Any) at ./boot.jl:267
```

Could we improve this to say that the variable is not initialized, or something similar?

**Comment by KristofferC** [comment]
Closing in favor of https://github.com/JuliaLang/julia/issues/17062
