### ISSUE TITLE
serializing closures is slow on master

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#16508]
```
using Serialization

function foo(n)
    io=IOBuffer()
    f = x->x
    @time for i in 1:10^n
        serialize(io, f)
        seekstart(io)
        deserialize(io)
    end
end

function bar(n)
    io=IOBuffer()
    @time for i in 1:10^n
        serialize(io, "Hello World")
        seekstart(io)
        deserialize(io)
    end
end

foo(1)
bar(1)
foo(4)
bar(4)
```

On 0.4

```
julia> foo(4)
  0.208748 seconds (680.01 k allocations: 35.706 MB, 1.70% gc time)

julia> bar(4)
  0.010271 seconds (100.00 k allocations: 9.003 MB, 24.10% gc time)
```

On master

```
julia> foo(4)
  3.409323 seconds (9.96 M allocations: 541.994 MB, 1.60% gc time)

julia> bar(4)
  0.012568 seconds (80.06 k allocations: 9.616 MB, 19.17% gc time)
```

@andreasnoack, your hunch was correct, this looks like the cause of the slowdown in distributed arrays - https://travis-ci.org/JuliaParallel/DistributedArrays.jl/builds/131800408

**Comment by amitmurthy** [comment]
cc: @shashi could also explain the slowdown you are seeing in ComputeFramework.

**Comment by ViralBShah** [comment]
This is important for 0.5.

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/pull/16695 helps but is kind of a workaround.

**Comment by amitmurthy** [comment]
I'll leave this issue open as #16774 optimized it only for parallel processing - and still not upto 0.4 levels. Will remove the 0.5 tag though, because, as discussed in #16674, this is the best for now.

**Comment by ExpandingMan** [comment]
Not completely sure it's related to this, but serializing and deserializing large objects (in this case DataFrames) to disk seems to take significantly longer on 0.5 (took me 9 seconds for a 38 MB dataframe).  I'm afraid I can't give my 0.4 number because I replaced the 0.4 build, but I'm quite sure it was much faster (maybe 1 s at most?).

**Comment by oscardssmith** [comment]
Do we still care about this? It seems not to have significantly improved between 0.5 and master, but maybe we should close as wont-fix since no one has complained in 4 years?

**Comment by oxinabox** [comment]
Serializing closures is pretty cruicial for our distributed processing, so yes?

**Comment by timholy** [comment]
Julia 0.5 is when fast closures got added, so maybe it's just inevitable?

**Comment by ViralBShah** [comment]
Just tried the benchmark again, and still as slow as reported.

**Comment by vtjnash** [comment]
Yes, but we recommend not sending closures (rather load packages on all nodes), so this isn't really an issue

**Comment by andreasnoack** [comment]
If that is the case then it would be helpful with hints to how we can avoid closures when communicating between processes in e.g. DistributedArrays as mention above.
