### ISSUE TITLE
nested logit model in Julia

### ISSUE THREAD

**Issue by tjvyxjq** [JuliaLang/julia#16500]
Hi,

It is my first time to use Julia and I have no idea about it. I searched a lot but there is nothing mentioned nested logit model. Could anyone give me some hits based on the following related stata code?

nlogitgen type = travel (private:air/car, public:bus/train)
nlogittree travel type, choice (b)

Thanks a lot.

**Comment by yuyichao** [comment]
Please use the [julia-users](https://groups.google.com/forum/?fromgroups=#!forum/julia-users) mailing list for questions.
