### ISSUE TITLE
Rational{IntN}(pi) are poor approximations to Pi

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#16513]
These values are better approximations to Pi

Rational{Int32}(pi) = Int32(1068966896) // Int32(340262731)
Rational{Int64}(pi) = Int64(2646693125139304345) // Int64(842468587426513207)
Rational{Int128}(pi) = Int128(60728338969805745700507212595448411044) // Int128(19330430665609526556707216376512714945)

```
setprecision(BigFloat,500);
Q32pi =  Int32(1068966896) // Int32(340262731);
Q64pi = Int64(2646693125139304345) // Int64(842468587426513207);
Q128pi =  Int128(60728338969805745700507212595448411044) // Int128(19330430665609526556707216376512714945);

Float64(BigFloat(pi)-Q32), Float64(BigFloat(pi)-Rational{Int32}(pi)) # 3.1e-18, 1.2e-16
Float64(BigFloat(pi)-Q64), Float64(BigFloat(pi)-Rational{Int64}(pi)) # 1.4e-38, 1.2e-16
Float64(BigFloat(pi)-Q128) # -6.2e-76

**Comment by JeffreySarnoff** [comment]
And if Rational{64} means Int32//Int32, use Q32pi for Q64pi

**Comment by TotalVerb** [comment]
Is this operation meaningful? We have with the revised definitions
```jldoctest
julia> 4Rational{Int64}(π)
ERROR: OverflowError()
 in *(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:196
 in *(::Int64, ::Rational{Int64}) at ./promotion.jl:191
 in eval(::Module, ::Any) at ./boot.jl:226
```
which is somewhat unfortunate. More precision is not necessarily a good thing.

**Comment by JeffreySarnoff** [comment]
@TotalVerb How do you get that? Please show me what you changed, how you redefined things.

**Comment by TotalVerb** [comment]
@JeffreySarnoff What I did to change the definition was:
```jldoctest
julia> Base.convert(::Type{Rational{Int64}}, c::Irrational{:π}) = Int64(2646693125139304345) // Int64(842468587426513207)

julia> 4Rational{Int64}(π)
ERROR: OverflowError()
 in *(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:196
 in *(::Int64, ::Rational{Int64}) at ./promotion.jl:191
 in eval(::Module, ::Any) at ./boot.jl:226
```

But you can reproduce it without changing anything with

```jldoctest
julia> 4 * Int64(2646693125139304345) // Int64(842468587426513207)
ERROR: OverflowError()
 in *(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:196
 in *(::Int64, ::Rational{Int64}) at ./promotion.jl:191
 in eval(::Module, ::Any) at ./boot.jl:226
```

**Comment by JeffreySarnoff** [comment]
@TotalVerb Now I understand that.  
Pick maximal constant K for which K * Rational{Int64}(pi) should not overflow,
and if K is 2^61, then the current definition is appropriate.  
While K should be greater than 4, should it be greater than 2^31?

**Comment by JeffreySarnoff** [comment]
Apparently, not a pressing issue. I am retiring it.

**Comment by simonbyrne** [comment]
Good catch, I don't know how that happened!

**Comment by JeffreySarnoff** [comment]
:)
