### ISSUE TITLE
Accessing TypeMap is not threadsafe

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#16524]
This is causing the `threads` tests to hang. Open an issue since I'm not sure how to fix this now...

My limited understanding of the issue based on a discussion with @vtjnash . The cache operations in `TupleMap` effectively turns a read into a write in many cases. Since this is not locked/atomic, the cache can be corrupted causing a infinite loop (due to a loop created in the data structure). The case we want to optimize for is when there's no concurrent access and therefore we'd like to avoid a lock in the fast path (a read-write lock would not help since concurrent read is not what we want to optimize here either). Any atomic rmw (mainly cas and inc) should also be avoided in the fast path since it's basically as expensive as a lock.

Solving this issue might involve,

1. Reduce cache reordering so that most execution don't need any write.
2. Use atomic acquire/consume load for the cache read to make sure the result is never corrupted in the present of concurrent write.
3. Use a counter to detect concurrent write and in that case restart with a read lock acquired.
4. The writer should acquire a write lock and increment a counter before doing the write.

**Comment by vtjnash** [comment]
&nbsp;5. or don't solve the issue: #16839
