### ISSUE TITLE
Matrix division \ gets confused by UnitRange on RHS

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaLang/julia#16520]
If solving `A \ B` where `B` is a `UnitRange` type will return a nonsense vector if the dimensions don't match.

For example:
```jl
b = 1:100
ones(3, 2) \ b
```
doesn't return a dimension mismatch error the way
```jl
ones(3, 2) \ collect(b)
```
does.

Instead it gives back a nonsense vector of the length of the `UnitRange`.

**Comment by gabrielgellner** [comment]
Seems to work correctly on version 0.4.5, but not on my copy of  0.5.0-dev+4255

**Comment by andreasnoack** [comment]
Which version of Julia are you using? I get the expected error on `Version 0.4.5-pre+7 (2016-03-17 05:23 UTC)`

**Comment by gabrielgellner** [comment]
Yes, sorry was working on a patch for  0.5.0-dev+4255, and made the silly mistake of not checking it out on 0.4.5.

Can someone else check on the current bleeding edge. If this is a mistake on my build sorry for the noise.

**Comment by andreasnoack** [comment]
No, you are right. Master has an issue.

**Comment by gabrielgellner** [comment]
It also effects LinRange objects in the same way. I imagine it is related. Thanks for checking ... got nervous.
