### ISSUE TITLE
Weird type inference(?) behavior with a type unstable creation of a type wrapping a vector of tuples.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#16530]
This is a reduced example of some code that started failing for me. I haven't bisected it but my guess is the `Vararg` changes but it could also be something with when `typeof` is evaluated, @timholy

```jl
type Foo{dim}
    c::Vector{NTuple{dim, Float64}}
end

function f()
    sdim = 1+1
    c = Vector{NTuple{sdim, Float64}}(1)
    c[1] = (1.0, 2.0)
    a = Foo{sdim}(c)
    println(typeof(a.c))
    return a
end

a = f()
println(typeof(a.c))
```

Executing this on current master gives:

```jl
julia> a = f();
Array{Tuple{Vararg},1}

julia> println(typeof(a.c))
Array{Tuple{Float64,Float64},1}
```

Inside the function, `typeof(a.c)` is `Array{Tuple{Vararg},1}` but outside it is `Array{Tuple{Float64,Float64},1}`. Note that this problem goes away if `sdim` is made a constant. This also seems to go away if instead of storing a `Vector{NTuple}` a simple `NTuple` is stored.

On an old 0.5 commit this gives the expected:

```jl
julia> a = f();
Array{Tuple{Float64,Float64},1}

julia> println(typeof(a.c))
Array{Tuple{Float64,Float64},1}
```

**Comment by KristofferC** [comment]
Will run a bisect now.

**Comment by KristofferC** [comment]
Can't bisect because I keep getting:

```
/home/kristoffer/juliacxx/src/init.c: In function ‘init_stdio_handle’:
/home/kristoffer/juliacxx/src/init.c:350:48: error: ‘UV_TTY_MODE_NORMAL’ undeclared (first use in this function)
             uv_tty_set_mode((uv_tty_t*)handle, UV_TTY_MODE_NORMAL); //cooked stdio
                                                ^
/home/kristoffer/juliacxx/src/init.c:350:48: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [init.o] Error 1
make: *** [julia-src-release] Error 2
```

**Comment by vtjnash** [comment]
bisect shouldn't be needed here, it looks straightforward enough from your examples. in the future, you can do `rm usr/lib/libuv* && make` to force it to reinstall libuv (otherwise, it gets confused which version it has installed)

**Comment by KristofferC** [comment]
This is a regression so should have a tag + eventually 0.5.0 mark?

**Comment by KristofferC** [comment]
Bump.
