### ISSUE TITLE
Backslash with SparseMatrix falls back to the generic backslash method

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#16548]
This means that cholmod is actually never used even if the matrix is pos def for backslash.

```jl
julia> typeof(A)
SparseMatrixCSC{Float64,Int64}

julia> isposdef(A)
true

julia> typeof(x)
Array{Float64,1}

julia> @which A\x
\(A::AbstractArray{T<:Any,2}, B::Union{AbstractArray{T<:Any,1},AbstractArray{T<:Any,2}}) at linalg/generic.jl:333

julia> @time A \ x; # Uses LU factorization because the generic factorize uses this for square matrices
 13.809494 seconds (87 allocations: 1.744 GB, 0.97% gc time)

julia> @time factorize(A) \ x; # Uses Cholesky factorization 
  3.442693 seconds (79 allocations: 648.282 MB, 0.20% gc time)
```

Shouldn't backslash for sparse matrices use the factorize methods defined at https://github.com/JuliaLang/julia/blob/master/base/sparse/linalg.jl#L859?

cc @andreasnoack

**Comment by andreasnoack** [comment]
I'll have to look a little more into this. I consolidated some of the `\` logic at some point and maybe something unintentional happened.

**Comment by andreasnoack** [comment]
I think it was an unanticipated consequence of https://github.com/JuliaLang/julia/commit/87e26c516853dd395de3c50406076f2d4d7aa413. We should probably have what you suggested so it would be great if you could prepare a PR.

**Comment by KristofferC** [comment]
I tried the easy way with just `\(A, x) = factorize(A) \ x` but it fails on the `@inferred` test in `spqr.jl`. Julia infers `Any` from `factorize` and that of course propagates to `\`.

**Comment by andreasnoack** [comment]
..and suddenly I remember the issue and the reason why I added the `@inferred` test. We might have to add a `\` method that is almost identical to `factorize`.

**Comment by tkelman** [comment]
@sacha0 any chance you could take a look at this one? would be much-appreciated!

**Comment by Sacha0** [comment]
> any chance you could take a look at this one?

Shall do!

**Comment by Sacha0** [comment]
> > any chance you could take a look at this one?

> Shall do!

@tkelman I should be able to spend a decent fraction of the coming week on things Julia. So if there are similar RC-freeze-related tasks in need of attention, please don't hesitate to ask. Best!

**Comment by JaredCrean2** [comment]
I don't think I can add labels, but if any issue deserves the needs-a-test label, this one does.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/16979 includes a test, albeit brittle

**Comment by JaredCrean2** [comment]
Cool.  Dispatch tests like that are important.

**Comment by tkelman** [comment]
We just took it off the milestone, but maybe you'd be able to make a little bit of headway on #13171 while Andreas is overloaded with JuliaCon organizing?

**Comment by KristofferC** [comment]
Took what off milestone?

**Comment by Sacha0** [comment]
Close with benefit of #16979 and open a new issue to track https://github.com/JuliaLang/julia/pull/16979#issuecomment-226792186 / https://github.com/JuliaLang/julia/pull/16979#issuecomment-227935000, or leave this issue open to track those points?

**Comment by KristofferC** [comment]
Let's close since the actual problem is fixed. Can have another issue for the style "problem".
