### ISSUE TITLE
rename SerializationState to Serializer, make official, document

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#16558]
There are situations where you want to explicitly construct a serializer object such that outputting the same object through that serializer results in a reference to the previous incarnation of it, rather than serializing the whole object again. Moreover, sometimes it's important to be able to explicitly control how that context is shared. We already have a mechanism for this called `SerializationState` – which is even exported. However, it is not documented yet, making it only somewhat official, and I would propose that the name `Serializer`, which is currently claimed by the module in which serialization functionality is defined would be a better name. So I'm proposing that we rename the module to `Serialization` and rename the type to `Serializer` and document it's API.

**Comment by oxinabox** [comment]
Having dug through that code recently when trying to work out a better way to do https://github.com/JuliaLang/julia/issues/16345#issuecomment-220216310

It is not clear how the `SerializationState`  is mutated by the calls to serialize.
So +1 to documenting it.
It might be worth also renaming a bunch of things to include mutating bangs (!),
or making it pure.

**Comment by JeffBezanson** [comment]
The renaming part of this is done.

**Comment by StefanKarpinski** [comment]
This seems like it can be closed now.
