### ISSUE TITLE
windows libuv freeze when running tests

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#16556]
As seen every time appveyor times out lately. I get this locally once in a while, so it's probably not specific to the appveyor environment, but I've rarely if ever seen it happen on 32 bit appveyor.

I did attach gdb to this once and it looked like Julia was waiting in `uv_poll`, so this may be correlated with the libuv upgrade making this more frequent recently. I'll try to catch it again but could use debugging suggestions for how to start tracking down the underlying cause.

**Comment by vtjnash** [comment]
I wonder if it could be https://github.com/JuliaLang/julia/issues/11727

**Comment by tkelman** [comment]
Appveyor is not running tests within mintty, so while it may be related I doubt it's exactly the same issue.

**Comment by vtjnash** [comment]
#11727 isn't related to mintty either...

Do we know which workaround Appveyorbis using to emulate a terminal emulator?

**Comment by tkelman** [comment]
No, but we can ask.

**Comment by tkelman** [comment]
You should probably be the one to phrase exactly what you'd like to ask.

Here's a backtrace of an instance of this that was run in cmd, no redirection at all:
```
Reading symbols from /home/Tony/julia/usr/bin/julia-debug.exe...done.
0x00007ffeebbc4ab1 in ntdll!DbgBreakPoint () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
(gdb) thread 1
[Switching to thread 1 (Thread 10052.0x3850)]
#0  0x00007ffeebbc3df4 in ntdll!ZwRemoveIoCompletionEx ()
   from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
(gdb) bt
#0  0x00007ffeebbc3df4 in ntdll!ZwRemoveIoCompletionEx ()
   from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#1  0x00007ffee85d083f in KERNELBASE!GetQueuedCompletionStatusEx ()
   from /cygdrive/c/WINDOWS/system32/KERNELBASE.dll
#2  0x000000000170b25e in uv_poll_ex (loop=0x2e9f4c0 <default_loop_struct>,
    timeout=4294967295)
    at /home/Tony/julia/deps/srccache/libuv-a1d9166a440e4a0664c0e6de6ebe25350de56a42/src/win/core.c:317
#3  0x000000000170b89a in uv_run (loop=0x2e9f4c0 <default_loop_struct>,
    mode=UV_RUN_DEFAULT)
    at /home/Tony/julia/deps/srccache/libuv-a1d9166a440e4a0664c0e6de6ebe25350de56a42/src/win/core.c:399
#4  0x0000000001657a40 in jl_atexit_hook (exitcode=0) at /home/Tony/julia/src/init.c:312
#5  0x000000000040327d in wmain (argc=2, argv=0x3a4a3d8, envp=0x4fe1a80)
    at /home/Tony/julia/ui/repl.c:672
#6  0x000000000040140c in __tmainCRTStartup ()
    at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt/crtexe.c:329
#7  0x000000000040153b in mainCRTStartup ()
    at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt/crtexe.c:212
(gdb)
```

**Comment by tkelman** [comment]
I'm going to propose reverting back to the older branch of libuv if this bug can't be fixed soon.

**Comment by tkelman** [comment]
This has been happening on win32 appveyor as well. From checking in gdb when it happens locally, something is going wrong in libuv.
