### ISSUE TITLE
Something wrong with BigFloat

### ISSUE THREAD

**Issue by hoangngan82** [JuliaLang/julia#16591]
Hi,
I have the following code:
```
set_bigfloat_precision(10000)
mm = BigFloat(4.8078788612688259965466497851830224475696)
@printf("%55.46e \n",mm)
```
I ran this code on notebook using IJulia on julia 0.4.5 in Arch Linux. It printed a number different from the one I gave it:
`4.8078788612688259965466497851830224475696    (This is what I gave it.)`
`4.8078788612688256876026571262627840042114257812e+00    (It printed this.)` 
Could anyone please have an explanation on this?
Thanks,
Ngan

**Comment by andreasnoack** [comment]
`4.8078788612688259965466497851830224475696` is first parsed as a `Float64` and then converted to a `BigFloat`. You'd need to parse the input string as a `BigFloat`. You can do that with `big"4.807878861268825996546649785183022` but please ask questions like this on the mailing list.
