### ISSUE TITLE
--compile=all bug@windows 

### ISSUE THREAD

**Issue by jadamcak** [JuliaLang/julia#16595]
Hi, I found bug in 

`Version 0.5.0-dev+4311 (2016-05-25 04:35 UTC)
Commit 3a346a6 (1 day old master)
x86_64-w64-mingw32`

after building "sys_all.dll" from "sys.dll", command 

`julia -J sys_all.dll --compile=no`

make this log message:

`shell> julia -J share/julia/base/sys_all.dll --compile=no`
`code missing for Base.==(Base.#==, Base.Cstring, Ptr{Void})  sysimg may not have been built with --compile=all`
`code missing for Base.==(Base.#==, Ptr{UInt8}, Ptr{Void})  sysimg may not have been built with --compile=all`
`code missing for Base.pointer(Base.#pointer, Array{UInt8, 1}, UInt64)  sysimg may not have been built with --compile=all`
`code missing for Base.unsafe_convert(Base.#unsafe_convert, Type{Ptr{UInt8}}, Array{UInt8, 1})  sysimg may not have been built with --compile=all`
`code missing for Base.-(Base.#-, UInt64, Int64)  sysimg may not have been built with --compile=all`
`code missing for Base.promote(Base.#promote, UInt64, Int64)  sysimg may not have been built with --compile=all`
`code missing for Base.elsize(Base.#elsize, Array{UInt8, 1})  sysimg may not have been built with --compile=all`
`code missing for Base.+(Base.#+, Ptr{UInt8}, UInt64)  sysimg may not have been built with --compile=all`
`code missing for Base.rem(Base.#rem, UInt64, Type{UInt64})  sysimg may not have been built with --compile=all`
`code missing for Base.oftype(Base.#oftype, Ptr{UInt8}, UInt64)  sysimg may not have been built with --compile=all`
`code missing for Base.convert(Base.#convert, Type{Ptr{UInt8}}, UInt64)  sysimg may not have been built with --compile=all`
`code missing for Base.convert(Base.#convert, Type{Ptr{Int32}}, Ptr{UInt8})  sysimg may not have been built with --compile=all`
`code missing for Base.SparseArrays.CHOLMOD.set_print_level(Base.SparseArrays.CHOLMOD.#set_print_level, Array{UInt8, 1}, Int64)  sysimg may not have been built with --compile=all`
`code missing for Base.unsafe_store!(Base.#unsafe_store!, Ptr{Int32}, Int64)  sysimg may not have been built with --compile=all`
`code missing for Base.getindex(Base.#getindex, Base.EnvHash, String)  sysimg may not have been built with --compile=all`
`code missing for Base.*(Base.#*, String, String, String, String, String)  sysimg may not have been built with --compile=all`

`(julia banner)`

I think, 

`code missing for ...  sysimg may not have been built with --compile=all`

is sign of bug. This bug I see only at windows.

**Comment by tkelman** [comment]
Are you starting Julia with `--precompiled=yes` ? That's necessary to load precompiled code but not yet the default setting on Windows. Hopefully it will be turned on soon once @vtjnash figures out how to fix it without making backtraces worse.

**Comment by jadamcak** [comment]
Thanks, 

when I use `--precompiled=yes`, I don't see this messages.

**Comment by jadamcak** [comment]
I have found another bug with --compile=all.
During compilation I can see these log messages:

`found 24631 uncompiled methods for compile-all`
`WARNING: could not attach metadata for @simd loop.`
`zd / zd`

 Ubuntu shell displays "45 / 24631"

**Comment by tkelman** [comment]
probably something to do with
```
/home/Tony/julia/src/gf.c: In function ‘_compile_all_deq’:
/home/Tony/julia/src/gf.c:1314:13: warning: unknown conversion type character ‘z’ in format [-Wformat=]
             jl_printf(JL_STDERR, " %zd / %zd\r", found_i + 1, found_l);
             ^
/home/Tony/julia/src/gf.c:1314:13: warning: unknown conversion type character ‘z’ in format [-Wformat=]
/home/Tony/julia/src/gf.c:1314:13: warning: too many arguments for format [-Wformat-extra-args]
```
