### ISSUE TITLE
0.4 & 0.5: unsafe_load hangs on Ptr{BigFloat}

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#16607]
This is surprising:

```julia
A=zeros(BigFloat,10,10)
a=pointer(A)
pointer_to_array(a,(10,10))  # works fine
unsafe_load(a)  # hangs
```

My version info is

```julia
Julia Version 0.5.0-dev+3977
Commit 957f1d1 (2016-05-08 00:28 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

**Comment by vtjnash** [comment]
As the "unsafe" in the name implies, if you use it wrong the result is undefined

**Comment by dlfivefifty** [comment]
I assume the issue is that BigFloat is not an `isbits`?  There wasn't any documentation on `unsafe_load` to explain what was wrong in the above usage.

**Comment by vtjnash** [comment]
The issue is that you should never call unsafe_load/store on a Julia array and should almost never use the 'pointer' method.

**Comment by dlfivefifty** [comment]
OK, could this be added to the documentation for 'unsafe_load'?  I tried to look it up if this was expected, but I didn't see anything.

**Comment by dlfivefifty** [comment]
I would also think that throwing an error would be better behaviour than hanging, since the fact that it's not defined can be inferred from the type of Ptr.

**Comment by yuyichao** [comment]
The load is defined, just not for the pointer generated this why.
