### ISSUE TITLE
0.5: `1.im` gives error `ERROR: syntax: invalid numeric constant "1.i"`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#16609]
Not sure if this is intentional or not, but the syntax `1.im` now gives an error

```julia
ERROR: syntax: invalid numeric constant "1.i"
```

If this is intentional, I would have expected a more explanatory error message.

**Comment by yuyichao** [comment]
This is intentional. https://github.com/JuliaLang/julia/pull/16339

**Comment by JeffBezanson** [comment]
Maybe it would be better to say "numeric literals ending in `.` cannot be implicitly multiplied" or similar?
