### ISSUE TITLE
Should `sizeof(sub(A, ...))` return array size?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#16614]
I was surprised by this behavior:

``` julia
julia> A = collect(1:100)
100-element Array{Int64,1}:
   1
   2
   3
   ⋮
  99
 100

julia> sizeof(A)
800

julia> sizeof(sub(A, 1:10))
48

julia> sizeof(A[1:10])
80
```

**Comment by vtjnash** [comment]
probably. we don't have a definition for `sizeof` currently though. there's some question of whether this is the number of readable bytes if the type happened to be converted to a pointer, or the number of bytes it would be if written to a stream. Or maybe `sizeof` should just go away (and just have Core.sizeof + a new function for getting the nbytes in a utf8-cstring)

**Comment by andyferris** [comment]
Not sure what the solution is, but I do know the only time I've want to use `sizeof(T)` is for predicting the stride of `Array{T}` (and other similar things where I'm playing with naughty pointer arithmetic). The behaviour for `sizeof(::Array)` seems a bit off in that regard. Maybe we need both a `sizeof` and a `memsize` function (which count immediate fields and recursively through memory, respectively).

**Comment by KristofferC** [comment]
```
julia> sizeof(view(A, 1:10))
80

julia> sizeof(A[1:10])
80
```
