### ISSUE TITLE
How to kill previously opened process in Julia?

### ISSUE THREAD

**Issue by kerbenii** [JuliaLang/julia#16625]
I opened notepad via executing
open(`notepad`)
but how to close it?

Docs says something about kill(**p::Process**, signum=SIGTERM)
but what p::Process is?

I assumed that this is process_id, but it doesn't work.

**Comment by zhmz90** [comment]
```
julia> pipe,proc = open(`notepad`)
(Pipe(closed => open, 0 bytes waiting),Process(`notepad`, ProcessRunning))

julia> kill(proc)
0
```

**Comment by kerbenii** [comment]
Thanks for fast help :-)

**Comment by yuyichao** [comment]
Just a note that please use the julia-users mailing list for questions like this.
