### ISSUE TITLE
Why does BitArray not support Integer types other than the standard Int type in its constructor?

### ISSUE THREAD

**Issue by rfoxfa** [JuliaLang/julia#16636]
In bitarray.jl, it's clear that BitArrays can only be generated from Int values and do not support, for example, `BitArray(Int8(3))` or `trues(Int128(x))`. This is a frustrating limitation when trying to write extensible code and seems easy enough to generalize to different integer types (Unsigned as well), but I'm hesitant to go directly editing base-level Julia code without understanding why it was implemented this way.

Will this be supported/fixed in future versions of Julia? Or is there a reason why it was implemented to only support Int types?

Here is a link to the source code I'm referring to: https://github.com/JuliaLang/julia/blob/2152bf93b98089ccc5e4373d57af336a2ea9c10e/base/bitarray.jl

**Comment by tkelman** [comment]
#16582
