### ISSUE TITLE
Slow push! and unshift! for large number of arguments

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#16631]
The following code is slow (even if the `push!` and `unshift!` functions are run several times):

```
x = [1, 2, 3]
push!(x, (1:10000)...) # this is very slow
unshift!(x, (1:10000)...) # this is also very slow
```

compared to:

```
x = [1, 2, 3]
for i in 1:10000
    push!(x, i)
end
for i in 1:10000
    unshift!(x, i)
end
```

For smaller number of values (less than 10000) the speed of current implementation is not prohibitively low, but slower than loop.

The problem was encountered in `NullableArrays` (PR JuliaStats/NullableArrays.jl#110) and the solution comment by @nalimilan requires fixing the cases mentioned above.

**Comment by andreasnoack** [comment]
The issue is the splatting because you effectively call a function with 10001 arguments. Wouldn't `prepend!` work for the problem in NullableArrays?

**Comment by bkamins** [comment]
I will have to check. But see that the loop is reasonably fast:

```
x = [1, 2, 3]
@time push!(x, (1:10000)...)
# over 2s
x = [1, 2, 3]
@time push!(x, (1:10000)...)
# over 2s

function npush!(x, vs...)
    for i in vs
        push!(x, i)
    end
    return x
end

x = [1, 2, 3]
@time npush!(x, (1:10000)...)
# less than 0.01s
x = [1, 2, 3]
@time npush!(x, (1:10000)...)
# less than 0.001s
```

**Comment by yuyichao** [comment]
Calling a function with splatting of an container is a bad idea. The multi-args push and unshift are optimized for a small number of arguments. `append` exists for a reason.

**Comment by nalimilan** [comment]
Sorry if my comment on the other issue wasn't explicit enough, but I meant that there was no performance issue here.
