### ISSUE TITLE
`esc` cannot be used in function arguments

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#16644]
It's been reported at least twice on julia-users, but I couldn't find an issue describing it. On 0.4:

```julia
macro mac1(x)
    :(function foo($(esc(x)))
        2+$x
    end)
end

@mac1(i)

> LoadError: syntax: "(escape i)" is not a valid function argument name
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/16096#issuecomment-216626004, which should be renamed....
