### ISSUE TITLE
Difficulties using Pkg.submit in Julia 0.4.5

### ISSUE THREAD

**Issue by ccoffrin** [JuliaLang/julia#16659]
I was following the [Julia 0.4 manual](http://docs.julialang.org/en/release-0.4/manual/packages/#making-changes-to-an-existing-package) for submitting contributions to a Julia package and a ran into a few issues on the Pkg.submit step.

First, it does not seem to work with a github account that has 2-factor authentication enabled.  I received a message along the lines of,
```
julia> Pkg.submit("Coverage")
INFO: Forking JuliaCI/Coverage.jl to ccoffrin
Enter host password for user 'ccoffrin':
ERROR: Unknown value
Line: 0
Around: ...HTTP/1.1 401 Unauthor...
           ^
 in error at /opt/homebrew-cask/Caskroom/julia/0.4.5/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _error at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:61
 in parse_value at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:218
 in parse at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:308
 in token at pkg/github.jl:89
 in req at pkg/github.jl:99
 in POST at pkg/github.jl:112
 in fork at pkg/github.jl:125
 in pull_request at pkg/entry.jl:327
 in submit at pkg/entry.jl:339
 in submit at pkg/entry.jl:337
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in submit at pkg.jl:58
```
On each attempt Github did sent me a One Time Password, but there was no way to enter it.

I tried turning off 2-factor just to see if that would resolve the issue.  It did fix the 400 response, but a similar issue arose with the 201 response.
```
julia> Pkg.submit("Coverage")
INFO: Forking JuliaCI/Coverage.jl to ccoffrin
Enter host password for user 'ccoffrin':
ERROR: Unknown value
Line: 0
Around: ...HTTP/1.1 201 Created ...
           ^
 in error at /opt/homebrew-cask/Caskroom/julia/0.4.5/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _error at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:61
 in parse_value at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:218
 in parse at /Users/cjc/.julia/v0.4/JSON/src/Parser.jl:308
 in token at pkg/github.jl:89
 in req at pkg/github.jl:99
 in POST at pkg/github.jl:112
 in fork at pkg/github.jl:125
 in pull_request at pkg/entry.jl:327
 in submit at pkg/entry.jl:339
 in submit at pkg/entry.jl:337
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in submit at pkg.jl:58
```

After following the guide in manual I concluded that Pkg was just walking me through the process of generating a repository fork and pull request.  If there is no other special book keeping of Pkg.submit, it would be helpful to note in the manual that setting up the pull request by hand is a fine alternative.

**Comment by lobingera** [comment]
I recently had Pkg.publish problems also and i read the manual http://docs.julialang.org/en/release-0.4/manual/packages/#package-development like manual publishing is a fine alternative.

So i'd focus on the 2FA problems here. I guess manual PR works with 2FA?

**Comment by vtjnash** [comment]
Julia Pkg no longer uses `git`, and `Pkg.submit` has moved to `PkgDev.submit` (not in base)

**Comment by lobingera** [comment]
@vtjnash While your comment is correct on more recent versions, i tend to disagree, looking at
https://github.com/JuliaLang/julia/blob/v0.4.5/base/pkg/git.jl
