### ISSUE TITLE
Invalid iteration syntax does not error

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#16650]
I stumbled onto this by accident, but behavior of `in` seems weird in this case:

```julia
arr = Array(Array{Int, 1}, 2)
arr[1]= collect(1:3)
arr[2] = collect(4:6)

for (idx, val) in arr
  println("idx = ", idx)
  println("val = ", val)
end
```
gives output:
```julia
idx = 1
val = 2
idx = 4
val = 5
```
on version
```julia
Julia Version 0.4.4-pre+35
Commit 1a9429e* (2016-02-12 13:21 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by yuyichao** [comment]
This is valid syntax and expected behavior. Extra argument in an iterator is ignored when assigning to multiple variables. (There might be an old issue for this.)

**Comment by tkelman** [comment]
Wouldn't it be more consistent with destructuring elsewhere to have the rest of the iterator get assigned to `val` here?

**Comment by JeffBezanson** [comment]
We never do that as far as I know. But it has been proposed as the behavior for `a, b... = itr`.
