### ISSUE TITLE
No SONAME in libjulia-debug.so.0.5.0

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#16668]
Hi guys!

I'm packing latest git version of Julia and today I noticed the following warning:

```
julia-unstable-debug.x86_64: W: no-soname /usr/lib64/libjulia-debug.so.0.5.0
```

Indeed, using `objdump` I can see that there is no SONAME in the `-debug` library:

```
# objdump -x libjulia-debug.so.0.5.0  |grep SONAME
#
```

Notice that everything is fine with `libjulia.so.0.5.0`:

```
# objdump -x libjulia.so.0.5.0  |grep SONAME
  SONAME               libjulia.so.0.5
#
```
Is there anyway to fix this problem?

**Comment by nalimilan** [comment]
@staticfloat knows best.

**Comment by tkelman** [comment]
He also hasn't been on github in about a week, so may be faster to just read through the diff from https://github.com/JuliaLang/julia/pull/16362 and see what's missing for the debug library.

**Comment by ronisbr** [comment]
I think I got it. Look here how `libjulia.so` is built:

```
ifeq ($(SHLIB_EXT), so)
  SONAME := -Wl,-soname=libjulia.$(JL_MAJOR_SHLIB_EXT)
else
  SONAME :=
endif

$(build_shlibdir)/libjulia.$(JL_MAJOR_MINOR_SHLIB_EXT): $(SRCDIR)/julia.expmap $(OBJS) $(BUILDDIR)/flisp/libflisp.a $(BUILDDIR)/support/libsupport.a $(LIBUV)
	@$(call PRINT_LINK, $(CXXLD) $(CXXFLAGS) $(CXXLDFLAGS) $(SHIPFLAGS) $(OBJS) $(RPATH_ORIGIN) -o $@ $(LDFLAGS) $(JLIBLDFLAGS) $(RELEASE_LIBS) $(SONAME)) $(CXXLDFLAGS)
	$(INSTALL_NAME_CMD)libjulia.$(SHLIB_EXT) $@
```

On the other hand, the `libjulia-debug.so` is built using:

```
$(build_shlibdir)/libjulia-debug.$(JL_MAJOR_MINOR_SHLIB_EXT): $(SRCDIR)/julia.expmap $(DOBJS) $(BUILDDIR)/flisp/libflisp-debug.a $(BUILDDIR)/support/libsupport-debug.a $(LIBUV)
	@$(call PRINT_LINK, $(CXXLD) $(CXXFLAGS) $(CXXLDFLAGS) $(DEBUGFLAGS) $(DOBJS) $(RPATH_ORIGIN) -o $@ $(LDFLAGS) $(JLIBLDFLAGS) $(DEBUG_LIBS))
	$(INSTALL_NAME_CMD)libjulia-debug.$(SHLIB_EXT) $@
```

So, I think I need to change the `src/Makefile` so that I can build `libjulia-debug.so` using:

```
$(build_shlibdir)/libjulia-debug.$(JL_MAJOR_MINOR_SHLIB_EXT): $(SRCDIR)/julia.expmap $(DOBJS) $(BUILDDIR)/flisp/libflisp-debug.a $(BUILDDIR)/support/libsupport-debug.a $(LIBUV)
	@$(call PRINT_LINK, $(CXXLD) $(CXXFLAGS) $(CXXLDFLAGS) $(DEBUGFLAGS) $(DOBJS) $(RPATH_ORIGIN) -o $@ $(LDFLAGS) $(JLIBLDFLAGS) $(DEBUG_LIBS) $(SONAME))
	$(INSTALL_NAME_CMD)libjulia-debug.$(SHLIB_EXT) $@
```

I'll try and then I comment here if it worked.

Thanks for the help @tkelman and @nalimilan

**Comment by ronisbr** [comment]
Just one question: the SONAME of `libjulia-debug.so.0.5.0` should be `libjulia.so.0.5` or `libjulia-debug.so.0.5`?

**Comment by yuyichao** [comment]
`libjulia-debug.so.0.5` I believe duplicated soname will cause a lot of confusions.

**Comment by ronisbr** [comment]
Thanks @yuyichao

**Comment by tkelman** [comment]
Unrelated, but looks like `$(CXXLDFLAGS)` is needlessly duplicated at the end when linking the release libjulia, it's already there earlier after `$(CXXFLAGS)`

**Comment by ronisbr** [comment]
I added the SONAME to `libjulia-debug` and the problem is apparently fixed. Thus, I created a PR with the changes.
