### ISSUE TITLE
hcat between sparse matrix and sparse vector

### ISSUE THREAD

**Issue by blegat** [JuliaLang/julia#16661]
I would have imagined that concatenating a sparse matrix and a sparse vector would yield a sparse matrix but apparently this is not the case

```
Version 0.5.0-dev+4154 (2016-05-18 11:17 UTC)
Commit 778740e (11 days old master)
julia> [spzeros(2,2) spzeros(2)]
2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
julia> methods(hcat)
hcat(X::SparseMatrixCSC...) at sparse/sparsematrix.jl:2857
hcat{Tv,Ti}(X::AbstractSparseArray{Tv,Ti,1}...) at sparse/sparsevector.jl:704
```

It seems that there is no specific method so the general `hcat` is called. Is that on purpose or is there a definition missing ?

**Comment by tkelman** [comment]
The latter I think. A missed case from #15172.

**Comment by blegat** [comment]
Note that #15172 was closed 10 days ago and that nightly ubuntu's build are 11 days old, can you reproduce it on master ?

**Comment by zhmz90** [comment]
It still exists on master.
```
julia> [spzeros(2,2) spzeros(2)]
2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> versioninfo()
Julia Version 0.5.0-dev+4393
Commit 15626c3* (2016-05-29 22:12 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by pkofod** [comment]
Hm, as far as I remember, it was kind of on purpose. When I started working on the pr, I don't think sparse vec cat worked at all, I think it's in the discussion somewhere. I can make a pr to fix it.
