### ISSUE TITLE
falses and trues don't take Int32 arguments

### ISSUE THREAD

**Issue by gaika** [JuliaLang/julia#16660]
It is possible to create zeros(Int32(2)) and ones(Int32(2)) arrays but falses(Int32(2)) or trues(Int32(2)) fail both 0.4.5 with

`ERROR: MethodError: `convert` has no method matching convert(::Type{BitArray{N}}, ::Int32)`

and 0.5 with

`ERROR: MethodError: no method matching trues(::Tuple{Int32})`

```
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

**Comment by ivarne** [comment]
Why close? It seems to me like ``falses`` and ``zeros`` should behave similarly.

**Comment by gaika** [comment]
duplicate of #16582
