### ISSUE TITLE
Vararg Tuple leaftype representation error

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#16670]
The documentation for `isleaftype` doesn't seem to consider singleton types:

```
help?> isleaftype
search: isleaftype

  isleaftype(T)

  Determine whether T is a concrete type that can have instances, meaning its
  only subtypes are itself and Union{} (but T itself is not Union{}).

julia> isleaftype(DataType)
true

julia> Type{Int} <: DataType
true
```

**Comment by yuyichao** [comment]
Singleton is not the issue, `Type` is the really special case.

**Comment by TotalVerb** [comment]
@vtjnash Why the close?

**Comment by vtjnash** [comment]
as yuyichao said, it's not a bug, it's simply that `Type` is a special-case representation for typeof, which also allows doing fun things like:
```
julia> Type{123} <: Int
true
```

**Comment by TotalVerb** [comment]
I thought that the documentation could use improvement at least. There are some other exceptions too:

```
julia> Tuple{Int, Vararg{Int, 2}} <: Tuple{Int, Int, Int}
true
```

**Comment by vtjnash** [comment]
those are just different ways of writing the same type (compact / long):
```
julia> Tuple{Int, Vararg{Int, 2}} == Tuple{Int, Int, Int}
true
```

**Comment by TotalVerb** [comment]
That's not true according to `isleaftype`:

```
julia> isleaftype(Tuple{Int, Vararg{Int, 2}})
false

julia> isleaftype(Tuple{Int, Int, Int})
true
```
