### ISSUE TITLE
parsing differences between REPL and include()

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#16679]
Just ran into this. The following code parsed fine in the REPL.

```
rng=RandomDevice()
retval = @parallel (+) for _ in 1:10 rand(rng) end
@test retval > 0.0 && retval < 10.0
rand(rng)
retval = @parallel (+) for _ in 1:10 rand(rng) end
@test retval > 0.0 && retval < 10.0
```

But when added in the above form to a test script (which is included via `include`) it resulted in a
`ERROR: LoadError: malformed @parallel loop`

**Comment by JeffBezanson** [comment]
I can't reproduce this.

**Comment by amitmurthy** [comment]
Sorry for the noise, I think a non-printable character snuck into the code I was testing with and hence the issue.
