### ISSUE TITLE
Cannot declare symbols starting with a number using the ':' character

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#16678]
```
julia> :9A
ERROR: UndefVarError: A not defined
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

julia> :aA
:aA
```

**Comment by toivoh** [comment]
This is to be expected, the `:` is for quoting Julia code, and not only for symbol literals. So only valid Julia identifiers can be retrieved as symbols this way. If you want to create other symbols, you have to use `Symbol`.

**Comment by amitmurthy** [comment]
OK. Should be documented though.

**Comment by ivarne** [comment]
See also https://github.com/JuliaLang/julia/issues/9945.

**Comment by amitmurthy** [comment]
Maybe Stefan's answer from here - http://stackoverflow.com/questions/23480722/what-is-a-symbol-in-julia - can be edited and added to the manual.
