### ISSUE TITLE
Build with Clang on Windows not working

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/julia#16683]
Hello,
I'm not able to build latest Julia with Clang using the suggested Make.user file (suggested in Cxx.jl):

```
#GCC >= 5 will not work
#override USECLANG=1
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# Optional, but recommended
override LLVM_ASSERTIONS=1
# For LLDB support also
# override BUILD_LLDB=1
# override LLDB_DISABLE_PYTHON=1
override CMAKE=/E/Users/phlavenk/programs/cmake/bin/cmake.exe
```

```
Julia Version 0.5.0-dev+4409
Commit 8651708* (2016-05-31 05:37 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-4669 v3 @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

Could you please somebody guide me to where to find logs to see why the Clang executable was not build?
Otherwise, Julia itself is build OK and tests are passing.
Thanks,
Petr

**Comment by tkelman** [comment]
I think only Keno has been able to build Julia with clang on Windows, and he hasn't written down how.

**Comment by phlavenk** [comment]
Do you know if the Clang and Cxx out-of-the-box capabilities are planned for the 0.5 release?
I'm facing a need to interface a pretty large API consisting of large C structs pointing to another arrays of structs - all on Windows. So, instead of the tedious work with encapsulation, we could just use the fantastic Cxx package to write into the API directly from Julia. Thanks for the possible insight into the road map if possible.

**Comment by tkelman** [comment]
blocked on #16117 I believe

**Comment by vtjnash** [comment]
Not relevant anymore
