### ISSUE TITLE
Fails to install nightly builds on Fedora

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#16697]
When I try to update julia from repository "nalimilan/julia-nightlies" on fedora 22, since a while I get the error messages in the attached file. 
The essential message seems to be:
"Error: package julia-devel-0.5.0-0.20160531.fc22.x86_64 requires libjulia-debug.so()(64bit), but none of the providers can be installed.
package julia-devel-0.5.0-0.20160518.fc22.x86_64 requires julia(x86-64) = 0.5.0-0.20160518.fc22, but none of the providers can be installed."

[julia.txt](https://github.com/JuliaLang/julia/files/293503/julia.txt)

The currently installed version 0.5.0-0.20160518 is the last one, which installed properly. It did not help to remove julia completely and reinstall. Since there have been quite a few updates since then, I fear there could be a bug in the distribution (starting with 20160522).

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/julia/pull/16696 may well fix this. I'll tell you when it's included in the RPM nightlies.

**Comment by nalimilan** [comment]
Can you confirm it works now?

**Comment by KlausC** [comment]
I just succeded in installing Release 20160603 from julia-nightlies. See the dnf-output:

Running transaction
  Upgrading   : julia-devel-0.5.0-0.20160603.fc22.x86_64                                       1/10 
  Upgrading   : julia-common-0.5.0-0.20160603.fc22.noarch                                      2/10 
  Upgrading   : julia-0.5.0-0.20160603.fc22.x86_64                                             3/10 
  Cleanup     : julia-common-0.5.0-0.20160518.fc22.noarch                                      7/10 
  Cleanup     : julia-devel-0.5.0-0.20160518.fc22.x86_64                                       8/10 
  Cleanup     : julia-0.5.0-0.20160518.fc22.x86_64                                             9/10
  Verifying   : julia-0.5.0-0.20160603.fc22.x86_64                                             1/10 
  Verifying   : julia-devel-0.5.0-0.20160603.fc22.x86_64                                       2/10 
  Verifying   : julia-common-0.5.0-0.20160603.fc22.noarch                                      3/10  
  Verifying   : julia-common-0.5.0-0.20160518.fc22.noarch                                      6/10 
  Verifying   : julia-devel-0.5.0-0.20160518.fc22.x86_64                                       7/10 
  Verifying   : julia-0.5.0-0.20160518.fc22.x86_64                                            10/10 

Upgraded:
  julia.x86_64 0.5.0-0.20160603.fc22               julia-common.noarch 0.5.0-0.20160603.fc22        
  julia-devel.x86_64 0.5.0-0.20160603.fc22
