### ISSUE TITLE
BitVector shifts don't accept negative counts

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#16706]
Arithmetic shifts accept negative shift counts, and then shift in the opposite direction. `BitVector` does not yet do this.

The standard implementation would be to change the count argument in the current implementation from `Int` to `UInt`, and have an additional selector function that accepts `Int` and chooses the shift direction.

**Comment by sg1101** [comment]
Hi @eschnett . I would like to try and solve this issue. I am new to open source and had not contributed yet. I can really use some guidience from you about how to proceed. Thank You :)

**Comment by StefanKarpinski** [comment]
Unless I'm mistaken, this was fixed by https://github.com/JuliaLang/julia/pull/19760.

**Comment by tkelman** [comment]
they could still use docs though

**Comment by StefanKarpinski** [comment]
Agreed, but that is a different issue.
