### ISSUE TITLE
Should Base.Callable be exported?

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#16701]
When creating functions that take a function argument (e.g. `sum` and `prod`) it'd be convenient to be able to define the method with `Callable` rather than `Base.Callable` (which feels weird), or just `Function` or `Union{Function,DataType}`. Is there a reason why `Callable` isn't currently exported? At present I don't see why it shouldn't be, though perhaps there's a very good reason.

**Comment by yuyichao** [comment]
It should be deprecated.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/pull/8458 If anything, `Base.Callable` is not the right way to decide if an object is callable.

**Comment by ararslan** [comment]
Ah sorry, I didn't see that PR. Thanks, @yuyichao. Then should the methods that currently use `Callable` be changed to use `Function`? I assume they wouldn't be changed to use `Union{DataType,Function}`, as that's the current definition of `Callable`...

**Comment by yuyichao** [comment]
They should be changed to remove the constraint altogether whenever possible.

**Comment by ararslan** [comment]
I'm not sure what you mean. As an example, consider [this method](https://github.com/JuliaLang/julia/blob/master/base/reduce.jl#L250) for `sum`:
```julia
sum(f::Callable, a) = mapreduce(f, +, a)
```
Do you mean that we should remove the type assertion for the function argument altogether, i.e. something like this?
```julia
sum(f, a) = mapreduce(f, +, a)
```

**Comment by yuyichao** [comment]
Yes, in the case it is not ambiguous. I think there are still cases that there's ambiguity and we haven't settle on a solution to handle those cases yet, which is why it haven't been removed.

**Comment by martinholters** [comment]
Ref #16191
