### ISSUE TITLE
`String` constructor is bad

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#16713]
The `String` constructor here leaves a lot to be desired:

```
"""
    String(v::Vector{UInt8})

Wrap a vector of bytes encoding string data as UTF-8 in a `String` object.
The resulting `String` object takes ownership of the array.
"""
String(s::Vector{UInt8}) =
    ccall(:jl_pchar_to_string, Ref{String}, (Ptr{UInt8},Int), s, length(s))
```

 - It makes a copy, so it's very slow. At least in Julia 0.3, no copy was made.
 - The behaviour is different from the docstring. The `String` object doesn't take ownership of anything.
 - It's unsafe. `String([0x80]);` is allowed, even though is is an invalid string.
 - It overwrites the `String` inner constructor, making the inner constructor useless and emitting a warning at build time.

Obviously not all of these can be fixed (points 1 and 3 would move it in different directions), but I think it ought to pick a direction:

 - `String` should be safe, and check its input (along with making a copy). The method is updated to check validity of UTF8. The docstring is updated. An `unsafe_array_to_string` replaces the current behaviour, and additionally does not make a copy. The inner constructor is deleted.
 - `String` should not be safe, and does not check input, and does not make a copy. The method is deleted and the docstring moved to the inner constructor.

**Comment by ararslan** [comment]
Ref #16107 (general direction for `String`) and #16590 (recent developments)

**Comment by stevengj** [comment]
I think there was a conscious decision by @StefanKarpinski to allow invalid UTF-8 data, so that `String` containers could be used to pass through arbitrary binary data.  This is common to many UTF-8 implementations, including Python's. (The decoding algorithm to extract chars/codepoints must still check for invalid data, of course.  There have been a [lot of proposals](http://permalink.gmane.org/gmane.comp.internationalization.linux/920) for how to decode such data.)

**Comment by stevengj** [comment]
See also #16470.

**Comment by stevengj** [comment]
I think @StefanKarpinski may have accidentally changed the `String(::Vector{UInt8})` semantics in #16453.   When he renamed the `bytestring(::Vector{UInt8})` function to `String(::Vector{UInt8})`, he overrode the inner `String` constructor (which *doesn't* make a copy) from #16212.

Probably `bytestring(data::Vector{UInt8})` should have been deprecated to `String(copy(data))`.
