### ISSUE TITLE
adding workers: `disable_threaded_libs` should be set with a keyword argument

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#16729]
I noticed (1) that `addprocs` forces me to run blas with 1 thread even if I start a worker on a remote machine. The root cause is the `disable_threaded_libs` function which is called when adding a worker. You really should be able to change this behavior with a keyword argument (as acknowledged by a comment in the code (2)).

(1): https://groups.google.com/forum/#!topic/julia-users/EKv6MvL6Ta8
(2): https://github.com/JuliaLang/julia/blob/c95b61b1ec4a16953ca496f50ee6f0e0a2797529/base/multi.jl#L1288-L1291

**Comment by kitkat2233** [comment]
I found this via up for grabs intro issues and wrote a proposal for a flag that defaults to off

**Comment by StefanKarpinski** [comment]
@kitkat2233: link to proposal?

**Comment by StefanKarpinski** [comment]
Oh, sorry, I just saw that it's https://github.com/JuliaLang/julia/pull/17429 which references this :)

**Comment by amitmurthy** [comment]
Closed by #17429
