### ISSUE TITLE
^ operart

### ISSUE THREAD

**Issue by Tecnezio** [JuliaLang/julia#16738]
Look at this code:
```julia
x = 0.1:100
m = 10.1
display(typeof(x)) # FloatRange{Float64}
display(typeof((x-m))) # FloatRange{Float64}
bb = x-m
# x.^2.1 #correctly done
bb.^2.2 # error -> why ? 
```

The last line throw this error:
LoadError: DomainError:
while loading In[13], in expression starting on line 6

 in .^ at range.jl:653

Why cannot elevate the "bb" range to a float exponent ?

**Comment by tkelman** [comment]
This kind of question would be better for the [julia-users mailing list](https://groups.google.com/forum/#!forum/julia-users). See http://docs.julialang.org/en/release-0.4/manual/faq/#why-does-julia-give-a-domainerror-for-certain-seemingly-sensible-operations.

**Comment by swt30** [comment]
@Tecnezio, it is being treated as a float - the error is because the first few terms of `bb` are negative. I think the error you saw is a little terse. Evaluating the first term `(-10.0)^(2.2)` directly will give more information:

```jl
julia> (-10)^2.2
ERROR: DomainError:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
 in ^ at promotion.jl:171
```

**Comment by hesampour** [comment]
same problem. how did you solved it?

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.

**Comment by kongdd** [comment]
@swt30 Any solution?

**Comment by fredrikekre** [comment]
> Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
