### ISSUE TITLE
Regression in generated code with | in loop

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#16739]
On my machine, the following code is three times slower on git master than on 0.4.5. The generated code is also a lot messier.

``` julia
function f(x::Vector, y::Vector)
    @inbounds for i in 1:length(x)
        x[i] = x[i] | y[i]
    end
    x
end

x = Array(Bool, 1000000);
y = Array(Bool, 1000000);


using BenchmarkTools

mean((@benchmark f(x, y)).times)
```

On 0.4.5 (system LLVM 3.3):

``` asm
Source line: 2
    pushq   %rbp
    movq    %rsp, %rbp
Source line: 2
    movq    (%rsi), %rax
Source line: 2
    movq    8(%rax), %rcx
    xorl    %edi, %edi
    testq   %rcx, %rcx
    cmovgq  %rcx, %rdi
    testq   %rdi, %rdi
    je  L70
    decq    %rdi
Source line: 3
    movq    (%rax), %rdx
Source line: 2
    movq    8(%rsi), %rcx
Source line: 3
    movq    (%rcx), %rsi
L42:    movb    (%rdx), %cl
    orb (%rsi), %cl
    andb    $1, %cl
    movb    %cl, (%rdx)
    incq    %rdx
    incq    %rsi
    testq   %rdi, %rdi
    leaq    -1(%rdi), %rdi
    jne L42
Source line: 5
L70:    popq    %rbp
    ret
```

On master (in-tree LLVM 3.7.1):

``` asm
Source line: 0
    pushq   %rbp
    movq    %rsp, %rbp
Source line: 2
    movq    8(%rdi), %r8
    cmpq    $1, %r8
    jl  L97
Source line: 3
    movq    (%rdi), %rcx
    movq    (%rsi), %rdx
    nopw    %cs:(%rax,%rax)
L32:
    movb    (%rcx), %al
    andb    $1, %al
    setne   %al
    andb    $1, %al
    movb    %al, -3(%rbp)
    movb    (%rdx), %al
    andb    $1, %al
    setne   %al
    andb    $1, %al
    movb    %al, -2(%rbp)
    movb    -3(%rbp), %al
    orb -2(%rbp), %al
    andb    $1, %al
    setne   %al
    andb    $1, %al
    movb    %al, -1(%rbp)
    movb    -1(%rbp), %al
    andb    $1, %al
    movb    %al, (%rcx)
Source line: 2
    addq    $-1, %r8
    addq    $1, %rdx
    addq    $1, %rcx
    cmpq    $0, %r8
    jne L32
Source line: 5
L97:
    movq    %rdi, %rax
    popq    %rbp
    retq
    nopw    %cs:(%rax,%rax)
```

**Comment by nalimilan** [comment]
BTW, shouldn't SIMD instructions be used here? If I replace `|` with `+` and use `Vector{Int}` arguments, I get SIMD instructions on git master (but not on 0.4.5).

**Comment by vtjnash** [comment]
That's not the assembly code I get in either case (longer/messier assembly code is actually better here since it means the compiler did a better job scheduling instructions). You're better-off looking at code_llvm for this example. But on master, I see that llvm-3.3 can vectorize this and llvm-3.7 cannot (resulting in a 32x performance difference)

**Comment by nalimilan** [comment]
My CPU is a relatively old i5 450M (Westmere), so that may explain the difference. I assumed the longer code was the explanation for the slower execution, but that was a totally uninformed guess.

Should we create a reproducer to report this upstream?

**Comment by nalimilan** [comment]
BTW, are you able to build Julia master with LLVM 3.3? I get several failure about undeclared variables.

**Comment by eschnett** [comment]
I get SIMD code on Julia 0.4 (release branch), and the same large number of unnecessary `andb $1` instructions on Julia 0.5 (master branch). I also see the temporaries stored on the stack. This looks to me like an LLVM problem.

When I run Julia with `-O`, the code becomes better, but is still bad.

Did Julia's representation of `Bool` values change?

**Comment by vtjnash** [comment]
> I get SIMD code on Julia 0.4 (release branch)

I also get simd on llvm-3.3 with master

> and the same large number of unnecessary andb $1 instructions on Julia 0.5 (master branch). I also see the temporaries stored on the stack. This looks to me like an LLVM problem.

none of these are relevant to the issue

> When I run Julia with -O, the code becomes better, but is still bad.

It looks like FastISel is slightly worse at generating optimal code here, although that difference is within 2x (out of the 32x from missing the vectorization opportunity)

> Did Julia's representation of Bool values change?

no

> BTW, are you able to build Julia master with LLVM 3.3? I get several failure about undeclared variables.

yes, although perhaps you need to add `-std=c++11` to the build flags (clang sometimes complains without it, but still compiles, while gcc refuses to continue)

> Should we create a reproducer to report this upstream?

yes, although it's probably related to pass order or similar, such that some earlier optimization pass is inhibiting the ability vectorize later (I haven't been able to get `opt` to vectorize the unoptimized output with llvm 3.3 either)

**Comment by KristofferC** [comment]
This is faster on 0.6 than 0.4 for me. Please reopen if there is still a problem.
