### ISSUE TITLE
propagate_inbounds is not exported

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#16752]
`@propagate_inbounds` is not exported from `Base`, but it's mentioned in the [public documentation](http://docs.julialang.org/en/latest/devdocs/boundscheck/).

@blakejohnson is this an oversight?

**Comment by blakejohnson** [comment]
At the time, it seemed like it had a narrow enough use case that it didn't deserve to be exported. But, given that `@inbounds` and `@boundscheck` are exported, maybe it should be, too. I dunno. Anyone else want to venture an opinion?

**Comment by tkelman** [comment]
How widely will it need to be used?

**Comment by c42f** [comment]
Ah right: public interface and the export list aren't really the same thing, which is why this isn't exactly an inconsistency.

As you can see from the link, the reason for asking is because I was unsure about whether `@propagate_inbounds` should be implemented in Compat.  Not that I need it myself right now, I only thought it'd go nicely with the Compat version of `@boundscheck`.

**Comment by blakejohnson** [comment]
I briefly discussed this with @JeffBezanson today, and we agree that it should not be exported. To summarize my views, `@propagate_inbounds` is really an internal feature. In particular, I can't think of an example where a user-defined type would need to use it. It was more in support of the hierarchy of `getindex` and `setindex!` methods in Base defined on `AbstractArray`.

And as far as the docs go, it is in the developer section, not the interfaces section.

**Comment by c42f** [comment]
Hmm, I was anticipating using this inside FixedSizeArrays, as I've got some bounds check utility code inside a sub-function which constructs a FixedArray from operations involving a FixedArray an a generic AbstractArray - see https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/bc3c8fe24e49e422ca276deca4797ddad7a1dc4d/src/mapreduce.jl#L47

Does this mean I'm doing something wrong?

**Comment by JeffBezanson** [comment]
It's ok to use things that aren't exported, you just have to be aware that it's much more likely to change.

**Comment by c42f** [comment]
No problems, thanks for the clarification.

**Comment by blakejohnson** [comment]
@c42f I finally had time to take a look at what you were doing over in FixedSizeArrays. The size check you pointed to on line 47 is only done once, outside of a loop. So, I suspect that it is not important that it be marked with `@boundscheck`. More problematic is what is going on here:
https://github.com/SimonDanisch/FixedSizeArrays.jl/blob/bc3c8fe24e49e422ca276deca4797ddad7a1dc4d/src/mapreduce.jl#L81

Which for Julia 0.5 should have an expression head of `:inbounds` rather than `:boundscheck`.

**Comment by blakejohnson** [comment]
This is now getting far off topic, but I also expect that fast anonymous functions also makes many of the `@generated` functions in FixedSizeArrays unnecessary in Julia 0.5

**Comment by c42f** [comment]
The bounds check is done outside of a loop, but these arrays are very short (length 3 is typical) so even that bounds check could usefully be removed.  Thanks for reminding me about the `:boundscheck` Expr, I forgot about that, I thought I'd killed that off some time ago.

Agreed that 0.5 will make FixedSizeArrays a lot less horrible internally!
