### ISSUE TITLE
OS_NAME deprecation warning does not give details of alternate.

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#16757]
The warning just says

``` julia
WARNING: Base.OS_NAME is deprecated.
```

**Comment by tkelman** [comment]
I don't think any of the binding deprecations do.

**Comment by yuyichao** [comment]
The binding actually do,

```jl
julia> Uint
WARNING: Base.Uint is deprecated, use UInt instead.
  likely near no file:0
UInt64
```

But the deprecation here doesn't have a simple replacement (i.e. replacing `OS_NAME` by `Sys.KERNEL` won't just work).

**Comment by ViralBShah** [comment]
Perhaps we can link to the documentation?

**Comment by vtjnash** [comment]
I think the doc system should be able to handle that (and in certain cases, the system would be able to automatically print it too)

**Comment by dlfivefifty** [comment]
Base.writemime is another one, and I can't find what it's changed to

**Comment by yuyichao** [comment]
The printing of replacement for function is somehow turned of in https://github.com/JuliaLang/julia/commit/a1ee8676f00fc14bd67aaf7eb20ce46ff99f322e#diff-a31e41a9e523fbbf9e60ba9a31f38efeL540 @JeffBezanson
