### ISSUE TITLE
build failure under cygwin

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#16759]
My most recent successful build was 0.5.0-dev+4506 at cd2a278.
```
HAW7L0605$ make
    LINK usr/bin/libjulia.dll
/usr/lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lLLVM-3.7
collect2: error: ld returned 1 exit status
Makefile:219: recipe for target '/home/s2sajs/julia-master/usr/bin/libjulia.dll' failed
make[1]: *** [/home/s2sajs/julia-master/usr/bin/libjulia.dll] Error 1
Makefile:90: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```

**Comment by tkelman** [comment]
This is due to #16723. The new patch should have resulted in llvm rebuilding and creating a shared library. You may need a `make cleanall`, or worst case a `make -C deps distclean-llvm`.

**Comment by josefsachsconning** [comment]
This was with a fresh clone.

**Comment by tkelman** [comment]
Actually now I'm seeing this too. This worked on the branch for #16723, but I think #14863 managed to cause a bad interaction since LLVM builds the shared library as a "tool" and went and put it in bindir which #14863 moved. I'll have to either revert #14863 or add another patch.

**Comment by tkelman** [comment]
Still building, but from my reading of llvm's makefiles 1fdc251d8db12e853e61663fae788241c57d6d9d should hopefully work.

**Comment by tkelman** [comment]
Oh by the way, don't upgrade to make 4.2 if you can help it, it has some regressions and odd failures in parallel builds that I hadn't been seeing for a long time.

**Comment by josefsachsconning** [comment]
Thanks for the tip.
