### ISSUE TITLE
`ndigits(big(0), 1)` does not raise an error

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#16766]
I'm not sure if it should but it is [in the test](https://github.com/JuliaLang/julia/blob/f02bda88d55a4c9ad32bd55e1e3749a9c37dc34c/test/bigint.jl#L281) and I've just triggered it once while stress testing https://github.com/JuliaLang/julia/pull/13995 .

Either way, the test needs to be fixed with explicit test for this case added. The implementation possibly needs fixing too if an error is desired.

**Comment by Keno** [comment]
Also `ndigits(1, 1)` hangs for me.

**Comment by dpsanders** [comment]
Shouldn't bases -1, 0 and 1 all give errors?

**Comment by Keno** [comment]
There may be an argument to be made that `ndigits(x, 1) = x`. I believe 0 and negative numbers are already errors.

**Comment by yuyichao** [comment]
iiuc base `1` can really only represent `0` so returning 1 in that case makes some sense (I'd be quite surprised if anyone really relies on that behavior though) all other cases should be error, which is what the failing test is testing (at least for `BigInt`).

**Comment by rfourquet** [comment]
cf. https://en.wikipedia.org/wiki/Non-standard_positional_numeral_systems for an idea why `ndigits(x, 1) = x` can make sense, but it may be too non-standard to be implemented in base. I think I would also favor erroring on bases -1, 1, and 0, even when `x==0`.

**Comment by TotalVerb** [comment]
We would need to have a `bijective_ndigits` for that to make sense, and I think that's outside the scope of Base.

**Comment by simonbyrne** [comment]
What does a negative base mean?

**Comment by StefanKarpinski** [comment]
[Negative bases](https://en.wikipedia.org/wiki/Negative_base) are a real thing, e.g. negabinary. Since I believe there's only one thing they can mean, we might want to just support them correctly. But clearly it's not a high priority.

**Comment by simonbyrne** [comment]
Okay, but that isn't documented anywhere, nor are they supported by the `base` function.
