### ISSUE TITLE
coverage drop

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#16779]
Coverage is reporting 11%. Must be an instrumentation or toolchain problem.

**Comment by tkelman** [comment]
check the buildbot logs, I think it's timing out on bitarray

**Comment by tkelman** [comment]
https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/318/ timed out
https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/317/ finished but hit #16714

out of the changes between the two that would make bitarray time out, I suspect it was #16217

**Comment by kshyatt** [comment]
In the meantime, I managed to get a run to finish locally: https://codecov.io/gh/kshyatt/julia/branch/master

**Comment by vtjnash** [comment]
Currently failing due to https://github.com/JuliaCI/Coverage.jl/issues/109

**Comment by tkelman** [comment]
Now working again, at least on codecov

**Comment by vtjnash** [comment]
Thanks all. Last 3 builds have been green

**Comment by KristofferC** [comment]
Is there a reason for keeping both the coveralls and codecov badges? Does coveralls show anything codecov doesn't?
