### ISSUE TITLE
stacktrace() doesn't work on ARM

### ISSUE THREAD

**Issue by xqrongm** [JuliaLang/julia#16775]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4534 (2016-06-04 22:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d122e90 (1 day old master)
|__/                   |  arm-linux-gnueabihf

julia> stacktrace()
ERROR: TypeError: stacktrace: in typeassert, expected Array{StackFrame,1}, got Array{Any,1}

julia> backtrace()
0-element Array{Ptr{Void},1}

![image](https://cloud.githubusercontent.com/assets/12205732/15809285/8db002ec-2b5b-11e6-8c98-5f39defea54c.png)

**Comment by vtjnash** [comment]
dup #12346
