### ISSUE TITLE
Performance regression in isprimes

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#16780]
The function `isprimes`  of #16349, or more precisely of https://github.com/JuliaMath/Primes.jl/pull/9 with type hint for the `witnesses` observed a significant drop in speed recently, see the discussion at  https://github.com/JuliaMath/Primes.jl/pull/9. When I was writing the comment https://github.com/JuliaLang/julia/pull/16349#discussion_r63227124 (using a slightly outdated master) no allocation took place in the inner loops at all. This seems to have changed recently as well and allocation takes place.

**Comment by JeffBezanson** [comment]
Could you provide a link to the exact code you ran, and the test case you ran? (Particularly because the code paths depend a lot on which numbers are tested.)

If possible, would be great to have the commit hash or approximate date of the older/faster julia.

**Comment by mschauer** [comment]
@pabloferz Can you also look at what versions exactly you were benchmarking with benchmark? The

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaMath/Primes.jl/issues/46
