### ISSUE TITLE
Allow : in reshape

### ISSUE THREAD

**Issue by cortner** [JuliaLang/julia#16790]
I find myself writing a lot of this:

``` jl
A = reshape(A, N, div(length(A), N))
```

Instead, I'd like to write 

``` jl
A = reshape(A, N, :)
```

**Comment by gasagna** [comment]
IIRC, Python uses a -1 to achieve what you propose. I have to say that I never really liked it so much, and : looks way cleaner.

**Comment by cortner** [comment]
More generally, 
```jl
B = reshape(A,  N1, N2, N3, :)
```
etc

**Comment by KristofferC** [comment]
Yes I love this. Have wanted it so many times.

**Comment by andyferris** [comment]
Even more generally, allow a single colon in any position:

```julia
B = reshape(A, N1, :, N3, N4)
```

Should still be perfectly implementable.

**Comment by malmaud** [comment]
I remember proposing this a while ago in some issue and it wasn't generally liked.

**Comment by StefanKarpinski** [comment]
I forget what the objection was before. Seems like a reasonable thing to me. It's possible that it was before `:` became a thing we could dispatch on.

**Comment by tkelman** [comment]
didn't `:` use to have to be handled by the parser until not that long ago?

**Comment by ivarne** [comment]
@malmaud I think it was https://github.com/JuliaLang/julia/pull/4263 ([search term](https://github.com/JuliaLang/julia/issues?utf8=%E2%9C%93&q=author%3Amalmaud+reshape))

**Comment by cortner** [comment]
sorry I missed PR - anyhow it would be great if this feature could now be added

**Comment by malmaud** [comment]
I can revamp that PR, but maybe one of the array experts like @mbauman or @timholy can way in on what they think of this idea.

**Comment by mbauman** [comment]
+1.  I think it's handy and useful. That's why I tried resurrecting your PR… but it got no traction at the time.  Anyone's welcome to update either of [my old commits](https://github.com/JuliaLang/julia/compare/master...mbauman:reshape-colon) and try it again.  At a minimum the tests should be useful.

**Comment by tlnagy** [comment]
I feel like this is a common usage pattern and would be nice to have in Julia. MATLAB, for example, uses empty [] to tell reshape to compute the missing dimension: https://www.mathworks.com/help/matlab/ref/reshape.html#examples
