### ISSUE TITLE
cp copied files not complete

### ISSUE THREAD

**Issue by LeoK987** [JuliaLang/julia#16807]
Julia version is 0.4.5 on Ubuntu 64bits.

The file were written with DataFrames writetable.  Files were small and only had fewer then 20 lines.  Then files were copied with simply:
cp("dir1/srcfile.csv", "dir1/dstfile.csv").
"dstfile.csv" did not exist before copy.
Upon inspecting dstfile.csv, the last line was missing some numbers.  Example of the last two lines as follows:

10  1   33  67  8793    391 32  372343  358106  231.8   12  2000    4659    182 8   -79.5   36088   328336
0.03    1   58  60  4613    263 36  267541  267541  220.9   22  1001    17

**Comment by simonbyrne** [comment]
Can you upload the files somewhere, e.g. https://gist.github.com/

**Comment by KristofferC** [comment]
Needs more info to be actionable.
