### ISSUE TITLE
libLLVM.dylib missing from usr-staging

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#16801]
it looks like libLLVM isn't getting installed correctly anymore (to usr-staging) after some recent change and is now incorrectly getting installed straight to the usr directory

**Comment by vtjnash** [comment]
@tkelman caused by https://github.com/JuliaLang/julia/pull/16761 (it fails to respect DESTDIR). also, any idea if the build is working with cmake (since the fix in that PR wouldn't be applied then)?

**Comment by tkelman** [comment]
what build? cmake ahared library on windows? no, not without a hacky patch, needs proper fixing upstream.

I'm still not convinved the whole usr-staging build fixes any real issues to be worth the confusion and how error-prone it is.

**Comment by ihnorton** [comment]
@tkelman re LLVM as a shared library on Windows via CMake: CMake's new(ish) [https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature](WINDOWS_EXPORT_ALL_SYMBOLS) might help.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/16773/commits/924049af57b7d78ad4660c0d129a06b076a2bfd8 was a hacky attempt but it needs work
