### ISSUE TITLE
Enum showing is lousy

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#16815]
Current master:
```julia
julia> @enum(Color, Red = 0, Green = 1, Blue = 3)

julia> Color
Enum Color:
Red = 0
Green = 1
Blue = 3

julia> Red
Red::Enum Color:
Red = 0
Green = 1
Blue = 3 = 0

julia> Green
Green::Enum Color:
Red = 0
Green = 1
Blue = 3 = 1

julia> Blue
Blue::Enum Color:
Red = 0
Green = 1
Blue = 3 = 3
```
It's confusing because:
* `typeof(Red) == Color`, but we print `Red::Enum`, which is still true, but one level removed from the actual value of `typeof(Red)`
* Printing out the enum instance integer value on the last line is obviously very confusing:

 `Blue = 3 = 0`??
* It feels very cluttered to print the entire set of enum instances with each value; I find myself visually hunting around to figure out what exactly I'm looking at

I'd propose something more like:
```julia
julia> @enum(Color, Red = 0, Green = 1, Blue = 3)

# align the equal signs
julia> Color
Color::Enum:
Red   = 0
Green = 1
Blue  = 3

julia> Red
Red

# alternatively
julia> Red
Red::Color = 0
```

**Comment by JeffBezanson** [comment]
This doesn't look intentional. Need to check how the `multiline` flag is being used here.

**Comment by nalimilan** [comment]
Cf. https://github.com/JuliaLang/julia/issues/15454 See on 0.4.5 what was intended: instead of
```julia
julia> Red
Red::Enum Color:
Red = 0
Green = 1
Blue = 3 = 0
```
we expect:
```julia
julia> Red
Red::Color = 0
```

The bug here is just with the way the enum type is printed after `::`. Other improvements are of course possible.
