### ISSUE TITLE
"unknown package $pkg" error could be more helpfull

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#16810]
I did what I was told but it does not work.

``` julia
julia> isprime(6)
ERROR: isprime(6,) has been moved to the package Primes.jl.
Run Pkg.add("Primes") to install Primes on Julia v0.5-
 in isprime(::Int64, ::Vararg{Int64,N}) at ./deprecated.jl:942
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46

julia> Pkg.add("Primes")
ERROR: unknown package Primes
 in macro expansion at ./pkg/entry.jl:53 [inlined]
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:315
 in sync_end() at ./task.jl:281
 in macro expansion at ./task.jl:290 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N}) at ./pkg/dir.jl:31
 in add(::String) at ./pkg.jl:100
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

Version:

``` julia
julia> versioninfo()
Julia Version 0.5.0-dev+4359
Commit e11ff35 (2016-05-27 08:02 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, nehalem)
```

**Comment by tkelman** [comment]
when was the last time you ran `Pkg.update()` ? what does `Pkg.status()` say? how about
```
julia> cd(Pkg.dir("METADATA"))
shell> git branch
shell> git log -1
```

**Comment by thofma** [comment]
I always forget about `Pkg.update()`. Now it works. Thanks.

**Comment by ivarne** [comment]
Seems like changing the error to

```julia
julia> Pkg.add("Primes")
ERROR: unknown package Primes (maybe you need to call Pkg.update())
```
Would have avoided this issue, and saved @thofma some frustration.


https://github.com/JuliaLang/julia/blob/7fed6b0ecbf080c1815b8eb96fe9f3602d805522/base/pkg/entry.jl#L53 and the test in https://github.com/JuliaLang/julia/blob/7fed6b0ecbf080c1815b8eb96fe9f3602d805522/test/pkg.jl#L121

**Comment by tkelman** [comment]
We can't tell the future, I don't think recommending Pkg.update is necessarily a good idea in case of typos or unregistered packages.

**Comment by ivarne** [comment]
Then mention all 3 reasons. Typo, unregisterd package, or new package from after last run of Pkg.update()

**Comment by simonbyrne** [comment]
I'm don't think this is a big deal: this only affects people who are using the development version who haven't called `Pkg.update()` in a while. It won't affect users who only use 0.5 release, as they will have a new copy of METADATA.

**Comment by simonbyrne** [comment]
Ah, I misunderstood. Didn't we used to print a warning if you call `Pkg.add` having not updated METADATA in sometime?

**Comment by tkelman** [comment]
Ah good point, we do (did?) have that warning somewhere, maybe just trigger it ahead of this error code path.

**Comment by bjarthur** [comment]
`"unknown package"` also occurs when a user `rm -rf $pkg` and doesn't delete it from `REQUIRE` as well before trying to `Pkg.add($pkg)`

**Comment by KristofferC** [comment]
```
pkg> add lfhskjfbdsf
ERROR: The following package names could not be resolved:
 * lfhskjfbdsf (not found in project, manifest or registry)
```
