### ISSUE TITLE
Allow packages to live in a directory of repo

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#16830]
I've run into a couple of cases (FlatBuffers.jl/Feather.jl/Arrow.jl) where we're doing Julia implementations of existing "data interop" projects. The tradition has been to include each language implementation in its own directory in the "project repo", to encourage cross-collaboration and better consideration for potential breaking changes (thru comprehensive CI coverage).

It would be a bummer if Julia was the odd duck out because of a mere Pkg.add limitation. I've tried looking through the machinery a bit to generate ideas, but it touches quite a few different parts of the system and I thought I'd post a full issue to encourage broader ideas from those more in the know. Here are a few points I've noted:
- `git` doesn't seem to have a clean way to only clone a specific directory; there seems to be a way to clone a full repo and then ignore all but a single directory, but I don't think that actually helps because it still wouldn't look like a single, normal Julia package directory
- Doing a clone of the full repo, while a bit wasteful, doesn't seem like a terrible way forward. Most of these projects aren't hundreds of thousands of LOC, so it's not too much extra to clone.
- The `using`/`require` machinery seem to be a bit too rigid to know to look in a directory for a module definition (or sub-sub-directory for that matter) . I can't tell if this is something that could actually be changed in `using`/`require` or just how we define the package load path

Anyone have any ideas here? Ideally it'd be something simple, but maybe we need a PKG_LOC file for each package that defines where exactly the package module lives.

**Comment by tkelman** [comment]
> maybe we need a PKG_LOC file for each package that defines where exactly the package module lives

-100. Let's not make the filesystem clutter problem any worse. Would rather consolidate this kind of information (along with require, multiple versions from metadata, etc) into fewer files - https://github.com/JuliaLang/PkgDev.jl/issues/37 / https://github.com/JuliaLang/julia/issues/11955

**Comment by EricForgy** [comment]
I'm sure you know better than I do, e.g. from [this](https://groups.google.com/forum/#!topic/julia-users/pyeOM5NXSsQ), but for a similar thing and similar reasons, I am using [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). This seems to be a nice way to compartmentalize things.

If I understood, then you could have a parent repo with Git submodules and developers have the choice to either work on the submodules from the parent repo, if they want to, or work independently in the separate repos. It also helps keep things in sync on the parent repo (especially if you have private repos).

**Comment by EricForgy** [comment]
Oh. I see. That would be cool :)

**Comment by wildart** [comment]
I'm working on on julia environments (preliminary name) which would allow to move out development from the package directory to any location by introducing project (directory-level) dependency management.

More details during JuliaCon.

**Comment by rdeits** [comment]
@EricForgy I've had similar issues, and my solution has been https://github.com/rdeits/juliet which simply extends the `REQUIRE` syntax to support git URLs and SHAs instead of package names and version numbers. My workflow is to set the JULIA_PKGDIR environment variable to a folder within my project, then use `juliet install` instead of `git submodule update`. That lets me develop packages that depend on particular revisions of other submodules, but keeps most of the advantages of Julia's package manager (for example, installing a package with `juliet` will result in its dependent packages being installed, which is not the case if you simply add a new git submodule). 

However, I'm also very excited about Pkg3 and the new Julia environments, and I'm looking forward to `juliet` becoming obsolete 😄

**Comment by KristofferC** [comment]
Issue moved to [JuliaLang/Pkg.jl #691](https://github.com/JuliaLang/Pkg.jl/issues/691) via [**ZenHub**](https://www.zenhub.com/)
