### ISSUE TITLE
Document how to box/unbox struct types in C/C++

### ISSUE THREAD

**Issue by TheFausap** [JuliaLang/julia#16840]
Hello all,

I tried to find in the docs (also checked in embedding.c) how to get a complex number result from a julia function, but I didn't find anything. AFAIK there's no jl_box_complex or jl_unbox_complex function. So is the complex number returned as array ? If so there's some working example written somewhere ?

thanks,
fausto

**Comment by zhmz90** [comment]
Julia latest doc about [complex-and-rational-numbers](http://docs.julialang.org/en/latest/manual/complex-and-rational-numbers/)
Release v0.4 doc about [complex-and-rational-numbers](http://docs.julialang.org/en/release-0.4/manual/complex-and-rational-numbers/)

Hi, @TheFausap.  I find some document about complex numbers above. Is this what you are looking for?

**Comment by simonbyrne** [comment]
The Julia complex types match the memory layout of C, so you can use `Complex128` (for `double complex`) and `Complex64` (for `float complex`), as you would `Cdouble`, e.g.:
```julia
ccall(:csinh, Complex128, (Complex128,), complex(1.0))
```

Though perhaps we should add `Cdoublecomplex` and `Cfloatcomplex` aliases for consistency?

**Comment by TheFausap** [comment]
Hello,
thanks for the info. Just a question (dumb one): If I understood the examples I read ccall is called in a julia session. Is there an equivalent to use from a C/C++ program, calling a julia function ? 
I mean, something similar :

```
include <complex>

std::complex<double> c1 = 1. + 2.0i;
std::complex<double> c2 = 0. + 0.0i;

jl_function_t *f = jl_get_function(jl_base_module,"sinh");
jl_value_t *v1 = jl_box_complex64(c1);
jl_value_t *ret = jl_call1(f,v1);
c2 = jl_unbox_complex64(ret);

...
```
thanks,
Fausto

**Comment by LeoK987** [comment]
The new title doesn't correspond to what's been discussed about here, but I do wish to read some documentation about box/unbox'ing struct ASAP.  I am stuck on this now.

**Comment by simonbyrne** [comment]
I would suggest asking this on the julia-users.

**Comment by StefanKarpinski** [comment]
This is unrelated to passing complex numbers to C/C++: Julia uses the same calling convention as C/C++ so you can pass complex numbers the same way you pass ints and floats. This is well documented in https://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/.

This issue is about documenting how to construct a tagged, heap-allocated object that dynamic Julia code can understand from the C/C++ side. If you're working with something simple like a C struct or complex number, there's no need for that and you'll want to avoid it altogether.

**Comment by StefanKarpinski** [comment]
Also, there is nothing special about boxing a complex number versus any other Julia type, which is fairly thoroughly documented. There is no special C function for boxing a complex number but since boxing and unboxing general values is documented, I think this issue can be closed.

**Comment by ansmith3** [comment]
I have not found documentation on boxing/unboxing general types. The embedding portion of the documentation that I have seen only discusses basic types unless I a misunderstanding something. Could you point me to a reference that you speak of with regard to:
> Also, there is nothing special about boxing a complex number versus any other Julia type, which is fairly thoroughly documented

**Comment by StefanKarpinski** [comment]
https://docs.julialang.org/en/stable/devdocs/object/#Memory-layout-of-Julia-Objects-1 and to some extent https://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/#Calling-C-and-Fortran-Code-1 as well.

**Comment by Zueuk** [comment]
So, how do I unbox a Complex{Float64} value then, in C/C++?
Is it a tuple? Is it an array?
How can I check the return type with jl_typeis() ?
How should I box a complex number in C++ to pass it to Julia?

**Comment by gkdgoutam** [comment]
@StefanKarpinski, None of your links are accessible now.  Is there any documentation on passing complex type to Julia inside C++ environment?

**Comment by StefanKarpinski** [comment]
This didn't seem very hard to discover with google: https://docs.julialang.org/en/v1/devdocs/object/
