### ISSUE TITLE
`parse(Float64, "1,2")` and `parse(Float32, "1,2")` cause segfault on ARM 32 bit

### ISSUE THREAD

**Issue by xqrongm** [JuliaLang/julia#16849]
I apologize if this is a duplicated issue.

![image](https://cloud.githubusercontent.com/assets/12205732/15939506/ef73fe2e-2e45-11e6-954e-1bb48832bd16.png)

![image](https://cloud.githubusercontent.com/assets/12205732/15939411/92a10e12-2e45-11e6-8d18-6236d8bd04a4.png)

**Comment by yuyichao** [comment]
Dup of old ARM ABI issue. Fixed by https://github.com/JuliaLang/julia/pull/14194 on master. IIRC it's backported on the 0.4 but @tkelman has been having issue making the 0.4.6 release though.

**Comment by tkelman** [comment]
I'm working on it. I'll have to do win32 code signing manually for now. If you're building from source, pull the latest release-0.4 and build that.
