### ISSUE TITLE
Change sub behaviour to match getindex, possibly rename.

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#16846]
Following #13612, we should change `sub` behaviour to match which, as I understand it, basically means renaming `slice` to `sub` (and deprecating `slice`).

There was some discussion in #13157 of changing the name to `view` (which would conflict with ArrayViews), but if so we should make that decision soon.

cc: @andreasnoack @timholy @mbauman

**Comment by kmsquire** [comment]
:+1: to changing to `view`. I think it's clearer about what's happening semantically.

**Comment by StefanKarpinski** [comment]
+1 to both
