### ISSUE TITLE
Compilation issue with libunwind on Power PC

### ISSUE THREAD

**Issue by Albert65** [JuliaLang/julia#16845]
Hi All, there is a (minor) issue while compiling libunwind on Power 8, RedHat 7.2/64.
The binaries are created in julia/usr/lib/libunwind-ppc64.*
but shortly afterwards the compilation script attemps to find them in julia/usr/lib64 which is empty
(trying to find workaround, I created julia/usr/lib and julia/usr/lib64 manually before building)
If I create a simlink:   julia/usr/lib64 -> julia/usr/lib   the script also complains about coincident directories.

Making install in tests
 /usr/bin/mkdir -p '/dev/shm/julia/usr-staging/libunwind-1.1-julia2/dev/shm/julia/usr/include'
 /usr/bin/install -c -m 644 /dev/shm/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind-dynamic.h /dev/shm/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind-ptrace.h /dev/shm/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind-coredump.h /dev/shm/julia/deps/srccache/libunwind-1.1-julia2/include/libunwind-ppc64.h include/libunwind.h /dev/shm/julia/deps/srccache/libunwind-1.1-julia2/include/unwind.h '/dev/shm/julia/usr-staging/libunwind-1.1-julia2/dev/shm/julia/usr/include'
 /usr/bin/mkdir -p '/dev/shm/julia/usr-staging/libunwind-1.1-julia2/dev/shm/julia/usr/include'
 /usr/bin/install -c -m 644 include/libunwind-common.h '/dev/shm/julia/usr-staging/libunwind-1.1-julia2/dev/shm/julia/usr/include'
**mv: cannot stat ‘/dev/shm/julia/usr/lib64/libunwind*.a’: No such file or directory**
make[1]: *** [/dev/shm/julia/usr/lib/libunwind.a] Error 1
make: *** [julia-deps] Error 

I proceeded the compilation by invoking make the second time. Another problem showed up:
**Openblas** expects explicit target:   make OPENBLAS_TARGET_ARCH=POWER

Finally the **blocking problem** (double symbol ' , not a symbol " on the error line):
Creating usr/etc/julia/juliarc.jl
Copying in usr/share/man/man1/julia.1
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/fenv_constants.jl
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
Copying in usr/share/doc/julia/examples
    JULIA usr/lib/julia/inference.ji
**LLVM ERROR: unable to evaluate offset to undefined symbol ''**
make[1]: *** [/dev/shm/julia/usr/lib/julia/inference.ji] Error 1
make: *** [julia-inference] Error

**Comment by ViralBShah** [comment]
Is this still an issue? I am able to build julia just fine on a couple of different ppc boxes.

**Comment by tkelman** [comment]
Were any of them using red hat style distributions, or did you only test on debian derivatives? The `lib64` thing is probably a real issue here.
