### ISSUE TITLE
Include threading flags in julia-config.jl

### ISSUE THREAD

**Issue by TheFausap** [JuliaLang/julia#16868]
Hello,

I compiled several example programs without any problems, but now I have this undefined symbol.
It's defined in 
/usr/bin/g++ -Wall -DVERSION=\"3.02\" -fPIC -DJULIA_INIT_DIR=\"/Users/home/JULIA/DEV/lib\" -I/Users/home/JULIA/DEV/include/julia -o qmdd_cmd ./src/applications/qmdd_cmd.o ./src/core/QMDDpackage.o ./src/core/qcost.o ./src/core/textFileUtilities.o ./src/core/timing.o ./src/core/QMDDcircuit.o ./src/core/QMDDcomplexD.o  ./src/core/QMDDreorder.o -L/Users/home/JULIA/DEV/lib -Wl,-rpath,/Users/home/JULIA/DEV/lib -ljulia
Undefined symbols for architecture x86_64:
  "_jl_tls_states", referenced from:
      gCvalue(int) in QMDDcomplexD.o
      Clookup(complex) in QMDDcomplexD.o
      QMDDcos(double, double) in QMDDcomplexD.o
      QMDDsin(double, double) in QMDDcomplexD.o
      Ceq(int, int) in QMDDcomplexD.o
      Cgt(int, int) in QMDDcomplexD.o
      Cgt_new(int, int) in QMDDcomplexD.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found this symbol in julia_threads.h, but it seems missing in libjulia.

Any idea ?

thanks,
Fausto

**Comment by yuyichao** [comment]
`-DJULIA_ENABLE_THREADING=1`

**Comment by yuyichao** [comment]
This should be added to `julia-config.jl`, assuming you are using it. I thought there's already an issue opened for this but maybe it was just a mailing list post.

**Comment by TheFausap** [comment]
Yes, I'm using it in makefile. By the way I added manually 
thanks!
all ok now.

**Comment by TheFausap** [comment]
sorry I didn't see you just reopened to track down the julia-config.jl modification :)

**Comment by tkelman** [comment]
Should we also save whether or not threading is enabled in `build_h.jl` ?
