### ISSUE TITLE
Segfault when adding new zeros method

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#16860]
Discovered this in #16740.

The segfault happens on Travis' 64bit linux, no other CI, not my own 64bit linux, but I could nail it down using a [branch in my repo](https://github.com/martinholters/julia/tree/analyze_segfault), and it is actually sufficient to [add a definition](https://github.com/martinholters/julia/commit/fb7239212abf498512551214c1be664db6dc55b1) for `zeros{T<:AbstractArray}(::Type{T}, dims...)` (which is not even called).

The test triggering the segfault is [arrayops.jl:177](https://github.com/martinholters/julia/blob/bc56e326def6bf4eb122e15845274903b3fe6c02/test/arrayops.jl#L177), and it occurs in `sig_match_simple` at [typemap.c:127](https://github.com/martinholters/julia/blob/fb7239212abf498512551214c1be664db6dc55b1/src/typemap.c#L127), see [the travis output](https://travis-ci.org/martinholters/julia/builds/136645719).

**Comment by martinholters** [comment]
Setting up a (virtual) machine with Ubuntu 12.04 and following the build steps from the travis configuration, I can now reproduce the problem. That allowed me to narrow it down to the following code resulting in a segfault:

```Julia
import Base.zeros
zeros{T<:AbstractArray}(::Type{T}, dims...) = error("What, me? I'm not even being called!")

rng = (2,2:3,2:2:5)
tmp = zeros(Int,2,3,5)
tmp[rng...] = 1 # needs the splatting
B = cat(3,zeros(Int,2,3),zeros(Int,2,3),zeros(Int,2,3)) # needs three matrices cat'ed
```

I will try to bisect (assuming there is a version where this does not segfault) to figure out what might be going on...

**Comment by martinholters** [comment]
Ah, good news: Segfault is gone in current master, specifically since e03f01c3dd34e9d06847b89c37125d6e00bfb99f. However, considering how much the appearance of this bug depended on the build environment, I wonder whether the underlying cause has indeed been fixed or it is just better hidden now. CC @vtjnash 
Should we close this, or do some more investigation?

**Comment by vtjnash** [comment]
That commit seems a likely candidate for the fix. Since that commit was on master before this issue was found on travis, that may also suggest why it was hard to reproduce elsewhere?

**Comment by martinholters** [comment]
> Since that commit was on master before this issue was found on travis, that may also suggest why it was hard to reproduce elsewhere?

No, the problem first occurred in #16740 before that commit (including the hard reproducibility) and I started my investigations from there. Anyway, I'm glad it's fixed! (And having it nailed down to that specific commit gives the confidence that it is fixed indeed.)
