### ISSUE TITLE
Compilation failed on OS X 10.11.5

### ISSUE THREAD

**Issue by mroll** [JuliaLang/julia#16876]
Hi Julia community,

I went to compile Julia from source today. Running the build as suggested in the repo:

    $ git clone git://github.com/JuliaLang/julia.git
    $ cd julia
    $ make

Gets me the following error:

    /var/folders/2j/pwr6y31j4jgfzjycs7q064180000gn/T//ccUAzMBw.s:908:suffix or operands invalid for `movq'
    /var/folders/2j/pwr6y31j4jgfzjycs7q064180000gn/T//ccUAzMBw.s:912:suffix or operands invalid for `movq'
    make[2]: *** [amos/zunk2.f.o] Error 1
    make[1]: *** [build/openspecfun-e4df5ae16af1bb4d28729a2fb5a8c2f3a49cf7ad/libopenspecfun.dylib]   Error 2
    make: *** [julia-deps] Error 2

I saw the same thing mentioned in another [issue](https://github.com/JuliaLang/julia/issues/16124), so I tried compiling with a limited path like a comment on that issue suggests:

    $ PATH=/usr/bin:/usr/local/bin:/usr/sbin:/bin make

But no luck with that. I'm running OS X 10.11.5. I have updated brew, and used brew to update gcc (which updates gfortran). 

I'm happy to give more information. Any help is appreciated. Thanks

**Comment by vtjnash** [comment]
> I have updated brew, and used brew to update gcc (which updates gfortran). 

What was your upgrade path after updating XCode? (have you updated command line tools?) In particular, it's easiest if you wipe and reinstall brew after a major system update.

**Comment by mroll** [comment]
Yes, I have the most recent update of command line tools. What do you mean by upgrade path? I get "/Applications/Xcode.app/Contents/Developer" from `xcode-select -p`.

I have wiped and reinstalled brew, and I get the same error as above.

**Comment by tkelman** [comment]
```
which gfortran
which as
gfortran --version
as --version
```
x-ref https://github.com/Homebrew/legacy-homebrew/issues/45258

**Comment by mroll** [comment]
In fact I did not have the latest version of Xcode. Running `xcode-select --install` told me that I had the latest version of command line tools, but visiting the App Store page for Xcode allowed me to download a new version.

Apparently included in the update is a fix for the gfortran issue. I've successfully compiled Julia.

Thanks vtjnash and thanks tkelman for linking to that other issue!

**Comment by StefanKarpinski** [comment]
Glad you got it sorted out, @mroll :)

**Comment by sudoankit** [comment]
Note : 
This same issue is encountered if you got `Macports` installed. If you have `Macports` and are facing the same issue on MacOS Sierra, fix it using  
 `sudo mv /opt/local ~/macports` 

Welcome. 😄
