### ISSUE TITLE
"x not defined" error should print name of parent module when specified

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#16890]
When you try to access an object which does not exist inside a module, the error only gives the name of the object, and not that of the module. This is confusing at first when the object exists in another module or in the global scope, and the error happens in a complex code base.

``` julia
julia> module A
       end
A

julia> x = 1
1

julia> A.x
ERROR: UndefVarError: x not defined
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

Something like `x not defined in A` or `A.x not defined` would be much clearer.

**Comment by andyferris** [comment]
+1 (coincidentally, this one got me just last night).

**Comment by KristofferC** [comment]
Closing in favor of https://github.com/JuliaLang/julia/issues/17062
