### ISSUE TITLE
Messy @test output in case of success since IOContext changes

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#16910]
With recent master:
```julia
julia> @test [1,2] == [1,2]
Test Passed
  Expression: [1,2] == [1,2]
   Evaluated: 2-element Array{Int64,1}:
 1
 2 == (generic function with 128 methods) 2-element Array{Int64,1}:
 1
 2

```

The `Evaluated` part was likely supposed to use compact or non-`multiline` printing of arrays and methods.

**Comment by vtjnash** [comment]
This looks like the same issue as `Enum` printing, where we are finding that `multiline` shouldn't have been an IOContext attribute
