### ISSUE TITLE
Replace string parsing DateTime constructors with parse methods

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#16928]
I think it would lead to an overall more consistent design if `parse` (and `tryparse` etc.) would be the interface to convert strings to simpler types, including for `DateTime` and friends.

So maybe the constructor for `DateTime` that take a string as an input should just be deprecated and replaced by corresponding `parse` methods.

Might be an intro issue, if people agree with this design?

**Comment by nalimilan** [comment]
@quinnj?

**Comment by quinnj** [comment]
I've had some similar thoughts lately. Let me put my thoughts together and post something later today.

**Comment by omus** [comment]
Seems reasonable to me. My only concern is that these `parse` methods could conflict with packages such as https://github.com/invenia/DateParser.jl

**Comment by simonbyrne** [comment]
Seems like a good idea, but we should also improve the date parsing code if we're going to do this. The current design tries to be very general, but just ends up being ridiculously slow.

Here is some draft code I wrote for parsing RFC3339 strings:
https://github.com/simonbyrne/DateParsing.jl
which is around 100x faster.

I don't know if this could play nice with DateParser.jl: it might have to change to use it's own functions.

**Comment by davidanthoff** [comment]
Bump, could we either assign a "up for grabs" or "intro issue" to this, or assign it to a milestone?

**Comment by quinnj** [comment]
`parse` and `tryparse` are now supported w/ `Date`, `DateTime` and `Time`. I don't see any pressing need to deprecate the constructor methods.
