### ISSUE TITLE
Nullable(0, true) !== Nullable{Int}() false

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#16923]
Title says it all. It's possible to create two objects which are printed as `Nullable{Int}()` and are not supposed to differ in any way, and yet are actually different according to `===`.  This is because:
```julia
julia> dump(Nullable(0, true))
Nullable{Int64}
  isnull: Bool true
  value: Int64 0
julia> dump(Nullable{Int}())
Nullable{Int64}
  isnull: Bool true
  value: Int64 1
```

This is particularly annoying when writing tests, but it can also be disturbing in real uses.

For non-`isbits` types, a solution is to discard the value in the constructor when `true`, i.e.:
```julia
Nullable{T}(value::T, isnull::Bool=false) = ifelse(isnull, Nullable{T}(), Nullable(value))
```

But this doesn't work for `isbits` types, for which the field contains random values when left uninitialized. I guess there's a way to fill the `value` field with zeros à la `reinterpret`, but what's the best way to do it?

Cc: @johnmyleswhite

**Comment by JeffBezanson** [comment]
Related: #9147

**Comment by johnmyleswhite** [comment]
Without something like #9147, this seems hard to me. The current semantics of `===` seem right to me: the problem is really the variability in the bits of the uninitialized field.

**Comment by nalimilan** [comment]
No doubt `===` is correct here. But isn't there a way to zero-fill that field manually until #9147 is implemented, without a too big performance hit?

**Comment by johnmyleswhite** [comment]
I'm not aware of one. I wish we had a mechanism for doing that in general, but I don't see how to pull it off while preserving immutability. The only thing I can imagine is that we could provide a mechanism for asking for a pseudo-value that is equivalent to a bit pattern that's filled with zeros and has the right memory size.

**Comment by TotalVerb** [comment]
Zero-filling will have to [fix](https://github.com/JuliaLang/julia/blob/20d376e7a3cf5b9ae0569906ad66c9f213b01f60/src/builtins.c) a good amount of C code that bypasses the default constructor. I don't know if it's a good idea.

**Comment by simonbyrne** [comment]
Also note that this is similar to `NaN`s, which can also compare differently under `===` due to different payload values.

**Comment by JeffBezanson** [comment]
@TotalVerb Zero filling can be provided by the memory allocator, at a level of abstraction below constructors. Yes, several places in the C runtime code will have to be updated, but I don't see a problem with that.

**Comment by nalimilan** [comment]
I'm starting to think this behavior isn't really a problem. `===` should only be used in very specific cases where you know implementation details. It can also be useful when testing operations to check that the branch-free code was used (as in https://github.com/JuliaLang/julia/pull/19034). Of course it's still annoying when you want to check both the type and missingness, but not the value, but well...

Should we close the issue then?

**Comment by johnmyleswhite** [comment]
Fine by me.
