### ISSUE TITLE
Unexpected behavior of escape_string for $

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#16920]
I think that the following behavior should be corrected jn `escape_string`:

```
julia> escape_string("\$")
"\$" # should be "\\$"
```

The fix could be the following definition of `escape_string':

```
escape_string(s::AbstractString) = sprint(endof(s), print_escaped, s, "\"\$")
```

**Comment by yuyichao** [comment]
The doc for `escape_string(str::AbstractString)` is

> General escaping of traditional C and Unicode escape sequences.

Is `$` a C or Unicode escape sequence?

**Comment by bkamins** [comment]
Thank you for pointing this out.
