### ISSUE TITLE
I can enter the same keyword argument twice, and the second over-rules the first

### ISSUE THREAD

**Issue by colintbowers** [JuliaLang/julia#16937]
A short example:

```
f(x::Int ; kw::Int=0) = x * kw
f(2)
f(2, kw=3) #evaluates to 6
f(2, kw=3, kw=4) #evaluates to 8
```

I'm on v0.4, but I asked about it on the julia-users list [here](https://groups.google.com/forum/#!topic/julia-users/dkE3v5otv6k), and was told you can still do this in v0.5. The link also contains an argument for why this might be considered a feature and not a bug. Personally, it feels more like a bug to me - but I am a very small voice. 

I stumbled onto this when typing out several keyword arguments, and my mind was still on the previous keyword as I typed the next one, and so I accidentally typed it twice. Easy to do, and it took me quite a while to work out where I'd gone wrong.

**Comment by JeffBezanson** [comment]
It seems pretty reasonable to make this a syntax error.

**Comment by martinholters** [comment]
As mentioned on the list, the current behavior might be useful with splatting for something like `foo(;defaults..., overrides..)` to work, but the same could be achieved with an explicit `merge`, of course.
Well, not exactly the same: If `foo` is defined as `foo(;kwargs...)`, it can actually tell whether a value is given multiple times. This might be potentially useful if one actually wants to allow multiple values to one kwarg, but wants to avoid a collection for some reason E.g. `process_file(input="foo.txt", input="bar.txt")` could process both files. But this feels so fragile compared to "normal" kwarg behavior that I'm also in favor of making it a syntax error.

**Comment by ivarne** [comment]
Somewhat relevant discussion in https://github.com/JuliaLang/julia/issues/4916

**Comment by toivoh** [comment]
+1 for making it a syntax error.
