### ISSUE TITLE
2^63 gives negative number

### ISSUE THREAD

**Issue by AsTLAN** [JuliaLang/julia#16943]
In Julia I get that 2^63=-9223372036854775808, so in particular 2^63 <= 0 gives a true value.
I wonder if it is a problem with my installation.

**Comment by mbaz** [comment]
This behavior is documented: http://docs.julialang.org/en/release-0.4/manual/integers-and-floating-point-numbers/#overflow-behavior

Also, questions like this are more appropriate for the mailing lists.
