### ISSUE TITLE
User type 2-argument hash method not called

### ISSUE THREAD

**Issue by phobon** [JuliaLang/julia#16946]
If the single argument `hash` method is called on a user type before defining the two argument method, all future calls to the single argument one appear to preserve the old behavior.

```
julia> type X
       v::Int
       end

julia> hash(X(1))
0x165a18442649a549

julia> Base.hash(x::X, h::UInt) = hash(x.v, h)

julia> hash(X(1))
0x8efa6201973783e2

julia> hash(X(1))
0x665cd09ac7a9fc5d

julia> hash(X(1), zero(UInt))    #what the single arg method should be invoking
0x02011ce34bce797f
```

If that first call to `hash(X(1))` is not made before defining the new method, everything works as expected.

**Comment by vtjnash** [comment]
Dip #265

**Comment by phobon** [comment]
Thanks, that issue helped me understand what was going on.
