### ISSUE TITLE
deprecation warning should display file name and line number

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#16967]
See https://groups.google.com/forum/#!topic/julia-users/VAXsTGcuBzo

```
AWS-Sachs-Ubuntu$ cat /home/sachs/deprecated.jl
d = [a=>b for (a,b) in [(:a,1), (:b,2)]]
AWS-Sachs-Ubuntu$ usr/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4814 (2016-06-16 16:11 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 7ad5eee (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> include("/home/sachs/deprecated.jl")

WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.
Dict{Symbol,Int64} with 2 entries:
  :a => 1
  :b => 2
```

**Comment by timholy** [comment]
Looks like this might be generated from `julia-parser.scm`? CC @JeffBezanson.

**Comment by davidanthoff** [comment]
If it is difficult to give a filename and line number, could a module name be shown?

**Comment by timholy** [comment]
Agreed that even the module name would be a big step forward. My strategy in fixing these is:
```jl
cd <packagedir>/src
grep -R "using" *
# now from the REPL, one by one load all dependencies and see which one caused the warning
```
and iterate until the offending package has been isolated.

**Comment by JaredCrean2** [comment]
Could this be fixed for 0.5?  It makes upgrading to 0.5 difficult because tracking down deprecations warnings is rather painful.

**Comment by tkelman** [comment]
@JeffBezanson or @vtjnash even a small amount more information would be a big usability improvement here

**Comment by JeffBezanson** [comment]
Showing the module name is a good idea. That should be much easier.

**Comment by timholy** [comment]
@davidanthoff, just chiming in to say "thanks" for the way you've taken a very clear-headed look at this release and repeatedly come up with excellent suggestions.

**Comment by ihnorton** [comment]
xref Jeff's [comment](https://github.com/JuliaLang/julia/issues/17770#issuecomment-237134292) from 17770:

> Deprecation warnings from the lowering pass don't have easy access to location info, so this is pretty difficult to fix.

**Comment by JeffBezanson** [comment]
Parser deprecations now have location info.
