### ISSUE TITLE
Poor performance of TCPServer/TCPSocket on Julia 0.4

### ISSUE THREAD

**Issue by dfdx** [JuliaLang/julia#16971]
Here's a simple client-server pair based on Julia TCP sockets:

```julia
# server
server = listen(2000)
while true
    sock = accept(server)
    begin    
        while true
            @time readbytes(sock, 1024*1024)
        end
    end
end
```
```julia
# client
sock = connect(2000)
Mb = rand(UInt8, 1024*1024)   # 1 Mb of data
for i=1:1_000 write(sock, Mb) end
```
Essentially, the client simply writes 1Gb of data to the socket and the server reads it in chunks of 1Mb and measures resulting time. When I run this code in 2 different REPLs, I get the following measurements: 

**Julia 0.3.12**
> elapsed time: 0.030572218 seconds (1048640 bytes allocated)
elapsed time: 0.030935904 seconds (1048640 bytes allocated)
elapsed time: 0.030983416 seconds (1048640 bytes allocated)
elapsed time: 0.031210029 seconds (1048640 bytes allocated)

~32Mb/sec

**Julia 0.4.5**
> 0.026118 seconds (2 allocations: 1.000 MB)
  0.026585 seconds (2 allocations: 1.000 MB)
  0.026631 seconds (2 allocations: 1.000 MB)
  0.025656 seconds (2 allocations: 1.000 MB)

~38Mb/sec

**Julia 0.5.0-dev+4816 (2016-06-16)**

> 0.000365 seconds (89 allocations: 1.011 MB)
  0.000355 seconds (89 allocations: 1.011 MB)
  0.000328 seconds (89 allocations: 1.011 MB)
  0.000323 seconds (89 allocations: 1.011 MB)

~2.8Gb/sec, 75 times faster than the previous result.

Does it sound reasonable to investigate what have caused such a dramatic change in Julia 0.5?

**Comment by dfdx** [comment]
I also tried combining server on 0.4 with client on 0.5 and vice versa, and seems like the issue is _on the server side_: 

**client on 0.5 + server on 0.4**

> 0.026365 seconds (2 allocations: 1.000 MB)
  0.025908 seconds (2 allocations: 1.000 MB)
  0.026285 seconds (2 allocations: 1.000 MB)
  0.026279 seconds (2 allocations: 1.000 MB)

**client on 0.4 + server on 0.5**

> 0.000359 seconds (89 allocations: 1.011 MB)
  0.000384 seconds (89 allocations: 1.011 MB)
  0.000363 seconds (89 allocations: 1.011 MB)
  0.000374 seconds (89 allocations: 1.011 MB)

**Comment by StefanKarpinski** [comment]
Oh interesting. I thought this was a regression, not a progression.

**Comment by tkelman** [comment]
If you'd like to try bisecting and finding out if there was one really significant change, go for it? We already backported the most significant fix where the early 0.4.x releases are much slower than 0.4.4/0.4.5, but I suspect other improvements might be consequences of larger, harder to backport fixes. We hope to get an 0.5 RC out soon anyway.

**Comment by dfdx** [comment]
I tracked changes back to this January, but further testing goes pretty hard because many commits are not buildable. Here's one example of error during compilation from Dec 31, 2015:

**commit 17348360ab9e61c5a66618b9f3cbb990e24e90de**

> /home/username/work/repos/julia/usr/lib/libjulia.so: undefined reference to `jl_gc_preserve'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/username/work/repos/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2

I'd assume that some commits has just been broken, but I can hardly find any working before  ~ Jan 20. Any suggestions why this may happen?

**Comment by KristofferC** [comment]
You can bisect with `git run bisect ./bisect_script.sh` where `bisect_script.sh` is a script that is basically:

```
make clean
make || exit 125  

# call julia and run julia script here that returns 0 for success and 1 for non success
```

In that case git will automatically skip unbuildable commits and try the next one

**Comment by yuyichao** [comment]
I believe theres a few broken ommits on jb functions

**Comment by dfdx** [comment]
@KristofferC this is much easier than manual testing that I was doing :D Thanks!

`git bisect` pointed to the following commit, which looks relevant. Yet, I'm not very experienced in using `bisect`, so I'll check if this is really what we are looking for tomorrow. 
```
9dbc3abc0bf4f84332195882dda90d6c5b48d890 is the first new commit
commit 9dbc3abc0bf4f84332195882dda90d6c5b48d890
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Wed Jan 13 18:14:30 2016 -0500

    add fast-path optimizations for reading LibuvStreams
    
    fixes #14467 performance regression (and some)
```

-------
For reference, here's my `bisect_script.sh`: 

```
#!/bin/bash
make clean
make || exit 125
./julia test_tcp.jl
```
where `test_tcp.jl` looks like:

```
server = listen(2000)
t = 0
@async begin
    sock = accept(server)    
    for i=1:10
        global t = @elapsed readbytes(sock, 1024^2)
        println(t)
    end
end
c = connect(2000)
A = rand(UInt8, 1024^2)
for i=1:10
    write(c, A)
end
println("t = $t")
if t < 0.01
    exit(1)
end
```
It passes 10 blocks of 1Mb through TCP and, if time is less than 10ms, returns 1. I ran it as:
```
$ git bisect start 
$ git bisect old e755087cd783fe90fce89f7a06dddb5f10db9ebb
$ git bisect new 746fa8074d82a484e8150fee3e7019cedcaf4fc5
   Bisecting: 578 revisions left to test after this (roughly 9 steps)
   [bc1c18ec2f3452de4b5cb714191478e02bb3847a] Merge pull request #14425 from sarvjeetsinghghotra/issue-13690
$ git bisect run ./bisect_script.sh
```

**Comment by tkelman** [comment]
Right, that was exactly the commit that fixed this, and we backported the non-breaking parts of it already.

**Comment by dfdx** [comment]
Sounds like there's nothing more to do here, so closing the issue.

**Comment by StefanKarpinski** [comment]
Thanks for opening and investigating!
