### ISSUE TITLE
Strange BoundsError when trying to import Compose in userimg.jl

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#16970]
Linux x86_64, 4accf8a4f5b68dc9bfe410ae332fdc9d7b237722 - you'll need to check out Compose to latest master to avoid an unrelated syntax error on 0.5.
```
tkelman@nanosoldier1:~/Julia/julia-0.5$ echo 'import Compose' > base/userimg.jl
tkelman@nanosoldier1:~/Julia/julia-0.5$ make > /dev/null
WARNING: Method definition (::Type{#T<:Any})(Any) in module Inference at coreimg.jl:48 overwritten in module Base at sysimg.jl:60.

<a bunch of deprecation warnings that are no longer fatal and hopefully don't matter here>

LoadError("sysimg.jl",373,LoadError("/home/tkelman/Julia/julia-0.5/base/userimg.jl",1,LoadError("/home/tkelman/.julia/v0.5/Compose/src/Compose.jl",174,BoundsError(String[],(1,)))))
make[1]: *** [/home/tkelman/Julia/julia-0.5/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2
```

I feel like this may have worked once upon a time, before `__precompile__` existed? Though I get the same basic error on 0.4, and trying to go back to older versions of Compose doesn't change much either. It works outside of userimg, so what's happening here?

**Comment by vtjnash** [comment]
it looks like it's trying to call `Pkg.installed` which is wrong, broken, and not going to work

**Comment by tkelman** [comment]
Sure, but why the BoundsError?

**Comment by ViralBShah** [comment]
Is `Pkg.installed` itself broken, or that we shouldn't be calling it at all? I suspect it is the latter.

**Comment by ViralBShah** [comment]
Cc @shashi

**Comment by vtjnash** [comment]
I suspect that it is semi-intentionally broken because you should never be calling into `Pkg` from non-Pkg code

**Comment by shashi** [comment]
What do you suggest Compose should do here?

https://github.com/dcjones/Compose.jl/blob/09a85af07ed030235ec56e806fdbc3141060e77f/src/Compose.jl#L174-L208

It uses `Pkg.installed` to load code conditionally if Cairo and Fontconfig are installed. I suspect the answer is "Don't do it", or make "Compose pull both packages"...?

**Comment by tkelman** [comment]
The only reliable way to do optional dependencies and precompilation right now is to separate the code that depends on both packages being present into a third package that can unconditionally depend on both. Until `extern` gets implemented, anyway.

**Comment by tkelman** [comment]
closing in favor of https://github.com/dcjones/Compose.jl/issues/221
