### ISSUE TITLE
Safe non-traditional array indexing

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#16973]
With reference to #16260 (comment):

- transitionally (julia-0.5 only) make `size` and `length` throw an error for arrays with unconventional indexing
- introduce `@arraysafe` to rewrite calls to `size` and `length` to something that doesn't throw an error
- merge `allocate_for` into `similar`

**Comment by StefanKarpinski** [comment]
@timholy, where are we at on this?

**Comment by timholy** [comment]
As far as I'm concerned, all important known issues are closed by one merged PR (#17137) and two open PRs:  #17228 and #17355. It would be nice to have a better deprecation for `first(::Colon)`, see discussion starting at https://github.com/JuliaLang/julia/pull/16260#issuecomment-230477188. But once we decide on something it's a couple of lines to implement it.

However, I've gotten hints of some discontent, so most importantly see https://github.com/JuliaLang/julia/issues/17338#issuecomment-231439459 and https://github.com/JuliaLang/julia/pull/17228#issuecomment-231528864. FYI the DataArrays breakage is already fixed at https://github.com/JuliaStats/DataArrays.jl/pull/205, with https://github.com/tkelman/DataArrays.jl/pull/2 cued to improve the fix.

**Comment by timholy** [comment]
Oh, if folks are giving this some attention but need some time, my "merge by Monday" can obviously go on hold. I put a deadline on it because it seems like a bad idea to let them sit until moments before julia-0.5RC and THEN decide to either merge or revert (either of which could be disruptive). We should decide soon, but it doesn't have to be today.

**Comment by timholy** [comment]
Since @wildart seems to be coming to completion, I'm inclined to start hitting "merge" on my PRs. Speak now or...

**Comment by StefanKarpinski** [comment]
I think @JeffBezanson may have a few reservations, so maybe give him a chance to comment.

**Comment by timholy** [comment]
OK, that's the feedback I was waiting for. Silence is very hard to interpret.

**Comment by timholy** [comment]
#17228 seems ready for review. It also includes the revised deprecation for `front`.

I guess there is one potential last dangling issue: what to do, if anything, about #16378? The fundamental problem is that `(i,a) in enumerate(A)` is ambiguous: does `i` count entries of `A`, or is it an index for `A`? The name suggests it's a counter, and that's occasionally useful, but I'd wager that in practice it's more commonly used as an index for `A`. We can merge #16378, but I've never been thrilled with the name `eachindexvalue`, nor with having something so drattedly similar to `enumerate`.

**Comment by eschnett** [comment]
For dictionaries, enumerate adds a one-based index. That is not really comparable to arrays since dictionaries iterate over `(key,value)` pairs by default, while arrays don't, but it indicates that enumerate uses one-based enumeration even if a key is present.

What about `indexedvalues`? Similar to `enumerate`, the prefix `each` is not really necessary, and adding an index could be called "indexing".
