### ISSUE TITLE
include writemime in deprecation section of NEWS.md

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#16982]
While you're at it, is there a way to check that there are no other missing deprecations?

Also, I have seen discussion somewhere of removing 0.4 deprecations in 0.5.
All such removals should be listed in NEWS.md.

**Comment by JeffBezanson** [comment]
Will do.

Deprecations in previous versions are listed in `HISTORY.md`. We always remove 0.n deprecations in version 0.(n+1). Maybe a line saying "0.4 deprecations are removed, see this link"?

**Comment by josefsachsconning** [comment]
Such a link would be fine, as long as the list that it links to is correct and comprehensive.
I have not yet looked at the list for 0.4.
