### ISSUE TITLE
Slow compilation on windows

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#16987]
On windows, the Julia instances started to precompile don't use `precompiled=yes`.
As a result, GLVisualize needs almost 10 min to compile. 
Starting Julia without `precompiled=yes` accounts for ~23s per Julia instance, which adds up to a lot when firing up an instance per package.
Can we add `precompiled=yes` to https://github.com/JuliaLang/julia/blob/master/base/loading.jl#L458 ?
Or at least, propagate the flag? ;)

**Comment by pao** [comment]
I think #16953 etc. has this covered.

**Comment by KristofferC** [comment]
It is not the same. This is just for the precompilation stage where the problem with bad backtraces should matter much less.

**Comment by carnaval** [comment]
also if the user opt-in the bad backtraces in the parent process it's probably reasonable to do the same for the child

**Comment by vtjnash** [comment]
It might be safe there. I couldn't really care less about whether you are stuck with bad backtraces, unfortunately, you're stuck with `ntdll`, which *does* care. Backtraces must be perfect to ensure proper signal delivery (aka doesn't cause ntdll to instantly terminate the process), such as gc-statepoints, stack-overflow handling, debugger breakpoints, and perhaps a few other async events (such as GMP Div/0).

**Comment by vtjnash** [comment]
dup #16953
