### ISSUE TITLE
Ugly method ambiguity errors

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#17007]
Ambiguity errors are really hard to read and leak `svec` in 0.5. I consider this as a regression since ambiguity warnings were much cleaner on 0.4.
```julia
julia> f(x::Integer, y::Integer) = true
f (generic function with 1 method)

julia> f(x::Int, y::Any) = false
f (generic function with 2 methods)

julia> f(1, 2)
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  svec(Tuple{#f,Int64,Int64},svec(),f(x::Int64, y) at REPL[2]:1)
  svec(Tuple{#f,Int64,Int64},svec(),f(x::Integer, y::Integer) at REPL[1]:1)
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by timholy** [comment]
Just looks like the printing is broken: it should show just the 3rd item in the `svec`. Prob. broken in 0fa8bb59c.

**Comment by nalimilan** [comment]
Thanks, Tim!

Though I just realized something else is missing: in 0.4, a suggestion was also printed, giving the signature of the method one needs to define to fix the ambiguity. I think this was really useful, as ambiguities are quite hard to reason about, especially for newcomers. Any idea when/why it was removed?

**Comment by timholy** [comment]
As for "why," compare `using Images, DataArrays` on both julia-0.4 and 0.5, and you'll appreciate the motivation :smile:. More detail in #6190 and #16125.

I suppose we could add the printing of a signature of the method to resolve the ambiguity. In principle it's not hard: it's just `typeintersect(args1, args2)` on the argument tuple-types. However, I'm not certain it's all that useful except in cases where there are only two methods that are ambiguous: if there are 5 candidates, there are 10 pairs of methods to perform type-intersection on. I would also say it's hit-and-miss whether the advice is really worth following, vs. thinking it through carefully and redesigning the API. What are your thoughts?

**Comment by ufechner7** [comment]
Interestingly, in Julia 0.4.5 the warning is already printed, when the second function is defined. It is not necessary to call it:
`julia> f(x::Integer, y::Integer) = true
f (generic function with 1 method)

julia> f(x::Int, y::Any) = false
WARNING: New definition 
    f(Int64, Any) at none:1
is ambiguous with: 
    f(Integer, Integer) at none:1.
To fix, define 
    f(Int64, Integer)
before the new definition.
f (generic function with 2 methods)
`

**Comment by mauro3** [comment]
@ufechner7: with #16125 the warning on definition was changed to an error on usage.
