### ISSUE TITLE
Method sorting bug with map(f, ::Tuple, ::Tuple)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#17016]
On current master,
```jl
julia> @which map(-, (10,20,30), (1,2,3))
map(f, t1::Tuple, t2::Tuple, ts::Tuple...) at tuple.jl:122
```
This is pointing to [this method](https://github.com/JuliaLang/julia/blob/01e3c8a5c1dc6f61afc6c43fdfae87920b10707b/base/tuple.jl#L122), despite the presence of [this method](https://github.com/JuliaLang/julia/blob/01e3c8a5c1dc6f61afc6c43fdfae87920b10707b/base/tuple.jl#L104) (which is just lower down in the method table). This causes a huge performance problem for subtraction of `CartesianIndex`es, see [here](https://github.com/JuliaLang/julia/blob/01e3c8a5c1dc6f61afc6c43fdfae87920b10707b/base/multidimensional.jl#L50-L53).

This is not fixed by removing the parameter from `Any16` or any rearrangement of method definition order that I tried. (When you copy those methods and define them in an external module, then the method table is sensitive to definition order.)

**Comment by JaredCrean2** [comment]
I think this is #13651
