### ISSUE TITLE
Parametrised method not specialised correctly?

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#17023]
The following definition of `+` for a `Vol` type representing an `N`-dimensional volume should (I believe) call the parametrised `+` method when the two `N`s are the same; however, it calls the catch-all method that is designed for  `Vol` objects with different `N`  (EDIT: i.e. those not covered by the more restricted method definition):
```julia
immutable Vol{N,T<:Real}
    value::T   
end

Vol{T}(N, x::T) = Vol{N,T}(x)

import Base.+

+(V1::Vol, V2::Vol) = throw(ArgumentError("Volumes of different dimension cannot be added"))
+{N,T}(V1::Vol{N,T}, V2::Vol{N,T}) = Vol{N,T}(V1.value + V2.value)

V1 = Vol(3, 2)
V2 = Vol(3, 4)

julia> V1 + V2
ERROR: ArgumentError: Volumes of different dimension cannot be added
 in + at none:1
```

**Comment by dpsanders** [comment]
It does, however, seemingly work correctly if the catch-all method is replaced by the unwieldy
```
+{N1,N2,T}(V1::Vol{N1,T}, V2::Vol{N2,T}) = throw(ArgumentError("Volumes of different dimension cannot be added"))
```

**Comment by JeffBezanson** [comment]
I believe this is because `Vol` by itself has `T<:Real`, but in the parameterized method `T` is unrestricted. Try
```
+{N,T<:Real}(V1::Vol{N,T}, V2::Vol{N,T}) = Vol{N,T}(V1.value + V2.value)
```

**Comment by JeffBezanson** [comment]
Dup of #6383
