### ISSUE TITLE
Methods do not always specialize on the function type

### ISSUE THREAD

**Issue by pabloferz** [JuliaLang/julia#17029]
I would have thought that the following would work

```
julia> foo{T<:Integer}(op, ::Type{T}) = "Fallback"
julia> foo{T}(::typeof(convert), ::Type{T}) = "convert"
```

but when running foo(convert, Int) I get an error. Nevertheless the following would have worked in a clean REPL session

```
julia> foo{T}(op, ::Type{T}) = "Fallback"
julia> foo{T}(::typeof(convert), ::Type{T}) = "convert"
```

So inference works in some cases with the types of methods but not in others or am I missing something?

**Comment by nalimilan** [comment]
If you read the error message, you'll see that it's because of ambiguities:
```julia
julia> foo(convert, Int)
ERROR: MethodError: foo(::Base.#convert, ::Type{Int64}) is ambiguous. Candidates:
  svec(Tuple{#foo,Base.#convert,Type{Int64}},svec(Int64),foo{T}(::Base.#convert, ::Type{T}) at REPL[2]:1)
  svec(Tuple{#foo,Base.#convert,Type{Int64}},svec(Int64),foo{T<:Integer}(op, ::Type{T}) at REPL[1]:1)
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

Define an additional method to fix this:
```julia
 foo{T<:Integer}(::typeof(convert), ::Type{T}) = "convert"
```

**Comment by pabloferz** [comment]
I know I because of the ambiguities. I should have been clearer. What I wanted to express is that I don't think this should give raise to ambiguities.

Or why does the first example imply and ambiguity and not the second?

**Comment by nalimilan** [comment]
Because the type of the first argument is more specific in the first method than in the second one, while the reverse is true for the second argument.

**Comment by yuyichao** [comment]
The first method of the first example has a constraint on its second parameter more specific them the same parameter in the second method of the same example.

**Comment by pabloferz** [comment]
Ok. I get it, so if I wanted the second to method of the first example to be more specific than the first one I would need `foo{R<:typeof(convert),S}(::R, ::Type{S}) = "convert"` right?

**Comment by yuyichao** [comment]
No, you have to limit S
