### ISSUE TITLE
remove `repr(::UUID)`, move UUID code

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#17026]
Looking at https://github.com/JuliaLang/julia/pull/17017, I noticed that there is room for more specialized (eg. faster) method specializations for `repr()`.

``` jlterm
julia> methods(repr)
#2 methods for generic function "repr"
repr(u::Base.Random.UUID) at random.jl:1252
repr(x) at strings/io.jl:86
```

The generic implementation in [strings/io.jl:85](https://github.com/JuliaLang/julia/blob/7a65d001b952e57a4907c071a5590080c7065ac2/base/strings/io.jl#L85-l89) uses an `IOBuffer`, so it is probably much slower than it needs to be ~~(especially for Strings which I think could be implemented as `repr(s::string) = s`)~~. The documentation demands the result must be the same as `showall`, so testing should ensure that is still the case.

**Comment by nalimilan** [comment]
More precisely, it's an alias for `sprint(showall, ...)`, right? I agree about deprecating it, since in 0.5 what's often needed is `sprint(showcompact, ...)` instead, and the fact that we have `repr` can cause confusion.

**Comment by JeffBezanson** [comment]
It is not the case that `repr(x::String) = x`, since `repr` adds quotes and escaping.

**Comment by ivarne** [comment]
@JeffBezanson Thanks for noticing. I somehow managed to convince myself that it did not, but my REPL history shows I did not actually try.

**Comment by JeffBezanson** [comment]
If anything, the `repr` method for UUID should be removed since nothing else defines it directly. Instead it should define `string` or `show`. Then the UUID code is a good candidate for #5155, since AFAICT it's not used anywhere in Base.

**Comment by tkelman** [comment]
Some of the UUID code will be needed for Pkg3, but if that itself is a package then it can have other-package dependencies that aren't all Base code.

**Comment by StefanKarpinski** [comment]
Making this a method of `string` would be the way to go here. Moving UUIDs out would be good too.
