### ISSUE TITLE
Remove comma as column vector building operator

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#17049]
Wouldn't it make sense to disallow the comma as a vertical ~~concatenation~~ matrix building operator? Right now there are two ways to build vertical arrays:

```julia
julia> a=[1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> [1;2;3]
3-element Array{Int64,1}:
 1
 2
 3
```

But only there is only one way (at least after the deprecation period) to concatenate an array with another, or with numbers:

```julia
julia> [a,4,5]
WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at abstractarray.jl:29
 in vect at abstractarray.jl:38
while loading no file, in expression starting on line 0
5-element Array{Int64,1}:
 1
 2
 3
 4
 5
```

Since these two operations are very similar semantically it seems reasonable that they use the same operator.

As an added bonus, note that MATLAB uses the comma for *horizontal* concatenation. Removing the comma vcat would thus be less confusing for people coming from MATLAB.

I could only find issue #3737 that seemed relevant, but that was only for the [a,b] behavior, not [1,2].

**Comment by yuyichao** [comment]
`;` is `vcat`, `;` is array literal. They are distinct now. It just happens that for array they have the same effect.

**Comment by jebej** [comment]
What is `,`?

**Comment by yuyichao** [comment]
Sorry, corrected.

**Comment by yuyichao** [comment]
Now the deprecated meaning of `,` is removed, `;` and `,` are totally different.

```
julia> [[1, 2], [3]]
2-element Array{Array{Int64,1},1}:
 [1,2]
 [3]  

julia> [[1, 2]; [3]]
3-element Array{Int64,1}:
 1
 2
 3
```

**Comment by jebej** [comment]
I see. It seems like it is only useful to make arrays of arrays. Otherwise it would make more sense for there to be only one operator.

Note that this is inconsistent with the horizontal case (unless that was changed in 0.5):
```julia
julia> [1 2 [1 2]]
1x4 Array{Int64,2}:
 1  2  1  2
```

**Comment by yuyichao** [comment]
> useful to make arrays of arrays

This is the whole point, and it is useful.

> inconsistent with the horizontal case

How is it inconsistent? The space syntax is `hcat` and it is consistent with `vcat` (using `;`). There isn't really a syntax for multi dimensional array literals and it seems to be needed much less often than `Vector` of `Array`s.

**Comment by StefanKarpinski** [comment]
I can understand how this can be confusing, but it's pretty well trod territory.

**Comment by jebej** [comment]
It actually is not inconsistent, I apologizes. It only seems inconsistent because there exist an array literal to make arrays of arrays or just a vertical array, whereas in the horizontal case there is only the concatenation operator.

I guess the a possible suggestions would be to disallow `,` in the `[1,2,3]` case, and only allow it to make arrays of arrays.

**Comment by StefanKarpinski** [comment]
But the whole point of the `[a,b,c]` syntax is that it means "make a typed array of these objects, whatever they are" which is a very useful thing to express (and which we didn't have a syntax for previously).
