### ISSUE TITLE
Pkg.generate inside a pre-existing repo

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#17042]
If I have a git repo that I want to turn into a package, it would be useful to have `Pkg.generate` generate the appropriate files inside that repo, and copy everything over to `.julia`; currently this needs to be done by hand.

**Comment by tkelman** [comment]
Can you reopen this at https://github.com/JuliaLang/PkgDev.jl? `Pkg.generate` lives there now.

**Comment by dpsanders** [comment]
Ah, good point, thanks.
