### ISSUE TITLE
Should we define hash(x::Enum)?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#17043]
I'm running into issues with precompilation and a module-level dict with enum keys; I believe the root cause is because we don't define a hash function for Enums. Should we? What's the right way to do this? I can dig more into it, but I figured I'd bring it up because others probably know better.

**Comment by JeffBezanson** [comment]
`===` works for Enums, so we should see if we can make `object_id` more stable for types. It would probably work to base it on Module uuids and type names.
