### ISSUE TITLE
memory leak when using macro

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#17044]
The memory does not drop even after `gc()`

<img width="611" alt="screen shot 2016-06-20 at 8 03 05 pm" src="https://cloud.githubusercontent.com/assets/1690993/16214016/041ddd10-3722-11e6-8a5b-0d6a6b40c3d4.png">

```julia
macro foo()
    quote
        ret = randn(10^8)
        ret
    end
end
@foo;
gc()
gc()
gc()
```

interestingly, the following has no problem

```julia
macro bar()
    quote
        randn(10^8)
    end
end
@bar;
```

Mac OSX 10.11, Julia 0.4.5 and 0.5-dev.

**Comment by yuyichao** [comment]
This is expected, the returned expression assigns the big array to a global variable. Use `let` or `local` if you don't want it to be assigned globally.

**Comment by randy3k** [comment]
I am confusing, I didn't assign `@foo` to any variable, there should be no reference  to `ret`.

**Comment by yuyichao** [comment]
`ret` is a global variable.

**Comment by randy3k** [comment]
ic...it is because it is called `#1#ret`.

**Comment by yuyichao** [comment]
Demonstrated below (note that the gensym name will change from run to run),

```jl
julia> macro foo()
           quote
               ret = 1
               ret
           end
       end
@foo (macro with 1 method)

julia> @foo;

julia> getfield(Main, Symbol("#1#ret"))
1
```

You can probably understand this more easily by looking at `macroexpand(:(@foo))`, a macro is effectively evaluated as `eval(macroexpand(expr))`

**Comment by randy3k** [comment]
@yuyichao 
Thanks, just did that.
