### ISSUE TITLE
Compiled and installed Julia refuses to start

### ISSUE THREAD

**Issue by veita** [JuliaLang/julia#17056]
`git pull` followed by `make` followed by `make install` built me a Julia binary that cannot be run.

Last commit: dbac013de3cbf5dc9f69863d6569a0cc637d1491

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4887 (2016-06-21 19:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit dbac013* (0 days old master)
|__/                   |  x86_64-pc-linux-gnu
```

`julia: error while loading shared libraries: libLLVM-3.7.1.so: cannot open shared object file: No such file or directory`

`make clean`, `make cleanall` and `make -C deps distclean-llvm` did not solve the problem. The `julia` symbolic link to `usr/bin/julia` in the checkout directoy works.

`# uname -a
Linux tin 4.4.6-gentoo #2 SMP Mon May 2 15:43:34 UTC 2016 x86_64 Intel(R) Atom(TM) CPU C2750 @ 2.40GHz GenuineIntel GNU/Linux`

With previous versions the install procedure worked.

**Comment by tkelman** [comment]
Sorry this never got triaged. Did you ever resolve this? May have needed `rm -rf usr usr-staging` ?

**Comment by KristofferC** [comment]
Please open if this still happens on 0.6.
