### ISSUE TITLE
issues in sending long text to julia running on terminal/iterm using applescript

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#17051]
First of all, consider [this](https://gist.github.com/randy3k/7eb30737c18fb6c93cca5857accaf338) applescript which sends a long text to terminal/iterm on Mac. The command is arbitrary but has to be long.

I guess due to the bracketed paste mode, copying and pasting of the command works fine. However, sending via applescript doesn't work for both terminal or iterm.

Terminal evaluates only part of a function.

<img width="638" alt="screen shot 2016-06-21 at 11 08 17 am" src="https://cloud.githubusercontent.com/assets/1690993/16234797/8adf40f4-37a0-11e6-90a7-fbf3908d80d9.png">

Iterm stops at middle

<img width="602" alt="screen shot 2016-06-21 at 11 09 03 am" src="https://cloud.githubusercontent.com/assets/1690993/16234811/9abd47b4-37a0-11e6-8e6d-1070bb4acdde.png">

**Comment by randy3k** [comment]
It turns on one could quote the command with `(ASCII character 27) & "[200~"`
and 
`(ASCII character 27) & "[201~"` to manually activate bracketed paste mode.

**Comment by vtjnash** [comment]
yes, it can be fun to try typing `<escape>[200~` (and other other escape codes) quickly enough the terminal accepts them, since you can enter them manually in that way
