### ISSUE TITLE
Not consistent allocation for @time

### ISSUE THREAD

**Issue by IagobaApellaniz** [JuliaLang/julia#17050]
Hello, I found a bug for a particular case. Maybe it can be reproduced somewhere else...
```
julia> x = [1 0; 1 0]
julia> @time x
  0.000001 seconds (4 allocations: 160 bytes)
2×2 Array{Int64,2}:
 1  0
 1  0

julia> @time x
  0.000001 seconds (3 allocations: 144 bytes)
2×2 Array{Int64,2}:
 1  0
 1  0
```

And it repeats oscillating the allocation number. Predominantly `4` is the number that most times appears.

**Comment by StefanKarpinski** [comment]
There's no guarantee that allocation will be consistent across evaluations of the same expression.

**Comment by KristofferC** [comment]
Also this is in global scope. If you want accuracy, put it in a function.

**Comment by IagobaApellaniz** [comment]
Indeed, the function version of the example above does print the right thing, `5` in this case, all the time. 

```
julia> foo() = [1 0; 1 0]
julia> @time foo()
  0.000002 seconds (5 allocations: 272 bytes)
2×2 Array{Int64,2}:
 1  0
 1  0
...
```

Thanks.

**Comment by yuyichao** [comment]
I'm not sure why you think 5 allocation is the right value...

In any case, the difference is that the boxing of the type difference may or may not allocate depending on how long the function take.

**Comment by IagobaApellaniz** [comment]
Sorry, the consistent one. ;-)

**Comment by yuyichao** [comment]
FWIW, by putting in a function, it means you need to put `@time` itself in a function.

**Comment by IagobaApellaniz** [comment]
Thanks! I'll give it a try to this. It wasn't that obvious to me.
