### ISSUE TITLE
Parse should also work with Bool types when converting from strings

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#17065]
Currently, parse command can be used to convert numeric types from strings.
Thus, the following operations are OK

parse(Int64,"2")
parse(Float64,"3.1415")

but 

parse(Bool,"true") 

triggers  InexactError().

The fact that this operation is only possible with numerical types is pointed in the help, but I think that it should be also possible with basic types like Bool.

**Comment by quinnj** [comment]
We're missing an intermediate dispatch method for Bools; the internal parsing method is here: https://github.com/JuliaLang/julia/blob/c20199e11a190dc27a762f7610cd1fc0f783073f/base/parse.jl#L57
