### ISSUE TITLE
More help for users when encountering UndefVarError

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#17062]
The [printing of `UndefVarError`](https://github.com/JuliaLang/julia/blob/45fa65f1f950609e471ad5f15f31bea103f8c823/base/replutil.jl#L103) is very minimalistic and can be improved to look for common mistakes.
- [ ] Look for variable names that is similar to Base functions/types (eg, levenshtein distance/length)
- [ ] Collect a list of function names in other languages and add explanation of how to get equivalent results in Julia
- [ ] Collect a list of function names in common packages so that we can point users to the correct package (especially relevant now that we have started to move functions out of Base).

I opened the similar issue https://github.com/JuliaLang/julia/issues/7512 a while ago, but it was hard to find a general solution.

Ref https://github.com/JuliaLang/julia/issues/17046#issuecomment-227391728, and cc @tknopp

**Comment by oxinabox** [comment]
Is there  levenshtein distance already in Base?
(I know it is in Distences.jl)
But I'm not sure what is used for apropos.

**Comment by MichaelHatherly** [comment]
> Is there levenshtein distance already in Base?

Yup, there's one [here](https://github.com/JuliaLang/julia/blob/d9fecbf5d1712413fd9bbb13648c1039032c50dc/base/docs/utils.jl#L220).

**Comment by dbeach24** [comment]
Finding similar function names (based on levens
Is there a good way to get the names of the local variables within the stack frame that triggered the `UndefVarError`?
