### ISSUE TITLE
Are there any plans to finish DArray implementation anytime soon?

### ISSUE THREAD

**Issue by dlvick42** [JuliaLang/julia#17068]
I'm guessing that ultimately DArrays will wind up behaving sort of like in the PGAS model (e.g. CAF and UPC). We're currently starting to look into how SharedArrays scale on commodity clusters. Would be nice to be able to look into testing a fully functional distributed array implementation as well.

**Comment by KristofferC** [comment]
Probably better to discuss at the DArray repo: https://github.com/JuliaParallel/DistributedArrays.jl
