### ISSUE TITLE
SharedArray setindex! slower than for Array

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#17060]
Running this script:
```
@time 1
function f2(a)
    out = 0
    for i = eachindex(a)
        a[i] = out
    end
    a
end

n = 10^8
a = ones(Int, n)
f2([1])
@time f2(a)

a = convert(SharedArray, [1])
f2(a)
a = convert(SharedArray, ones(Int,n))
@time f2(a)
```
I get:
```
  0.000003 seconds (149 allocations: 9.013 KB)        <--- warm-up @time
  0.082624 seconds (4 allocations: 160 bytes)           <--- Array
  0.129632 seconds (4 allocations: 160 bytes)           <--- SharedArray
```
I don't know whether this is expected/fixable.  If not, please close.

timings edited for clarity - Amit

**Comment by amitmurthy** [comment]
I would guess the shmem segments have additional checks at the OS level compared to regular process memory. In context, the timings are over 100 million iterations - probably not much we can do here.

**Comment by yuyichao** [comment]
I don't think the OS does anything about shared segments (it will be super expensive). I believe the issue is the a combination of https://github.com/JuliaLang/julia/issues/15369 and `SharedArray` being a mutable type (so some load of fields needs to be rooted).

**Comment by simonster** [comment]
Another issue is that the field that holds the underlying Array object is undefined at SharedArray construction, so accessing that field requires an undefined check.
