### ISSUE TITLE
Function redefinition doesn't always work

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#17076]
I found that sometimes function overwriting does not work right away. The method redefinition warning gets triggered, but the old function definition is used.
Here is a minimal test case which shows the bug (the last call fails, but calling `f()` again then produces `2` as expected):

```julia
f() = 1

# at least two calls are required to trigger the bug
f()
f()

f() = 2

@assert f() == 2 # fails
```

This is on version `0.5.0-dev+4882`.

**Comment by vtjnash** [comment]
I was wondering when someone would notice this. (not a duplicate of #265)

**Comment by StefanKarpinski** [comment]
You want to explain what you changed, @vtjnash? Or should I go for it? It's not a bug, it's a feature!

**Comment by oxinabox** [comment]
I had been finding this also, kinda thought either it was by design (no redefining consts) or  that someone else had reported it.

**Comment by tkelman** [comment]
> You want to explain what you changed, @vtjnash?

Apparently not?

**Comment by vtjnash** [comment]
What better way to explain?

**Comment by tkelman** [comment]
A function with no comments or tests doesn't actually explain what was going wrong in a way that anyone other than you understands.
