### ISSUE TITLE
Mutating Array Using SubArray

### ISSUE THREAD

**Issue by alexmorley** [JuliaLang/julia#17071]
Hi there,
When using a SubArray I would have expected:
```
testarray = [1:5 1:5]
testsubarray = sub(testarray, [1; 6])
testsubarray = [10; 10]
testarray
```
to mutate 1st and 6th elements and give:
```
5x2 Array{Int64,2}:
 10  10
  2   2
  3   3
  4   4
  5   5
```
rather than:
```
5x2 Array{Int64,2}:
 1  1
 2  2
 3  3
 4  4
 5  5
```
I know that I can acheive this behaviour by using "testsubarray[:] = ..."
```
testarray = [1:5 1:5]
testsubarray = sub(testarray, [1; 6])
testsubarray[:] = [10; 10]
testarray
```

And I think I understand why this is the case but I'm not convinced that this is intuitive and/or whether one could easily have worked it out from the docs. Is it worth adding this info?

Also is there a more efficient way of mutating a large array many times that I am missing?

**Comment by KristofferC** [comment]
You have a misunderstanding how variables in Julia work. Please read http://www.johnmyleswhite.com/notebook/2014/09/06/values-vs-bindings-the-map-is-not-the-territory/.

General questions like this are better for the julia-user mailing list.
