### ISSUE TITLE
Dict{K, V}(::Dict) does not return a Dict{K, V}

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#17092]
On 0.4.5

```julia
Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))

-> Dict{Any,Any} with 1 entry:
->   :x => 3
```

**Comment by KristofferC** [comment]
Can't reproduce

```jl
julia> a = Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
Dict{Symbol,Any} with 1 entry:
  :x => 3

julia> versioninfo()
Julia Version 0.4.5
```

**Comment by cstjean** [comment]
Oops, you're right. It seems that the `SymDict` package defines a constructor that overrides the standard `Base` method. Thank you for checking.

**Comment by tkelman** [comment]
That should be reported as a bug in the package. Packages shouldn't be extending Base methods for signatures that only involve Base types.

**Comment by StefanKarpinski** [comment]
Yeah. What is this, Ruby or something?

**Comment by cstjean** [comment]
> Packages shouldn't be extending Base methods for signatures that only involve Base types.

That's the rule that I follow, but it's an easy mistake to make, because a typealias gives the illusion of a new type "owned" by the typealias-defining module. I found a [similar issue](https://github.com/dcjones/Gadfly.jl/issues/851) in Gadfly. Maybe it should be an error? It can lead to really subtle bugs across packages. Julia already forbids modifying a module's globals, so it's a natural extension.
