### ISSUE TITLE
Function with lambda expression with captured variable is not inlined

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17094]
I have this definition (see https://github.com/eschnett/Forall.jl)
```Julia
@inline function forall(f, iter)
    for x in iter
        f(x)
    end
end
```
and this function
```Julia
function isum(n)
    s = zero(n)
    forall(1:n) do i
        s += i
    end
    s
end
```
Unfortunately, the function `forall` is not inlined into `isum` (this is Julia 0.5, current master), leading to significantly worse code.

The alternative function `isum2`
```Julia
const s2 = Ref{Int}()
function isum2(n)
    s2[] = 0
    forall(1:n) do i
        s2[] += i
    end
    s2[]
end
```
(where the lambda expression does not capture anything) is optimized beautifully.

**Comment by yuyichao** [comment]
Inlining is fine afaict. The type stability issue is https://github.com/JuliaLang/julia/issues/15276 (and this is likely one of the hard cases). Close as dup.
