### ISSUE TITLE
Rationalisation？

### ISSUE THREAD

**Issue by a504082002** [JuliaLang/julia#17099]
While I was reading the docs, I try the realization of complex denominator.
It works! I also try the rationalisation.
But it doesn't work.

```julia
julia> 1//(3 + 4im)
3//25 - 4//25*im

julia> 1//(1 + sqrt(2))
ERROR: MethodError: `//` has no method matching //(::Int64, ::Float64)
Closest candidates are:
  //(::Integer, ::Integer)
  //(::Integer, ::Rational{T<:Integer})
  //(::Complex{T<:Real}, ::Real)
  ...

julia> 
```

It is excellent to have this property and just construct the type of `Root{m, n}`.
M means the number in the root and n means that n=2 stands for square root, n=3 stands for cubic root.
And does this feature conflict with the exponent expression `2^0.5`?

**Comment by dpsanders** [comment]
You can construct your own `Root` type to do this if this is useful to you. I don't understand what you want the result of  `1 + sqrt(2)` or `1//(1 + sqrt(2))` to be with your `Root` type, though.

In any case, I don't think that this belongs in `Base`.

If you want to find a rational close to the floating-point number `1 / (1 + sqrt(2))`, you can do
```
julia> rationalize(1/(1+sqrt(2)))
38613965//93222358
```
