### ISSUE TITLE
Are there binaries available?

### ISSUE THREAD

**Issue by Dillybob92** [JuliaLang/julia#17102]
Hey guys,

Loving this new language, but for some reason when using `julia echoserver.jl` (following the tcp tutorial) -- it takes around 7 seconds to compile and load up the app

I have a SAMSUNG EVO 850,  ssd and a FX 6300 processor. Is this normal or should I upgrade my CPU? I'm using the latest julia build (0.4.6) -- I know this might not really be a bug report, but it seems odd the compile times are like this.  Maybe this is normal, but just left C++ because the syntax was too confusing and it compiled around < 1-2 seconds (using codeblocks) -- I'm fairly new to programming so again, I apologize. Thanks!

Edit: This happens when just launching julian.exe as well. (before I see the colorful splash screen)  I thought it was just the TCP server, but its not, weird

Edit2: Oh, I'm using Win 7 64-bit if that helps

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/16987 https://github.com/JuliaLang/julia/issues/16953

Please use the julia-users list for questions.
