### ISSUE TITLE
Slow down when reading files in parallel

### ISSUE THREAD

**Issue by shashi** [JuliaLang/julia#17118]
![image](https://cloud.githubusercontent.com/assets/25916/16358986/b3888962-3b41-11e6-853e-b8c8fb9cbf0a.png)

This was created with the following code:

``` julia
addprocs(4)

[@elapsed(@sync @parallel(for fn in getindex(readdir("/tmp/X_data/"), 1:i)
       f=open("/tmp/X_data/$fn","r+")
       read(f)
       close(f)
end)) for i=1:32]
```

`/tmp/X_data` contains 32 files each of 245MB. The "Group" in the plot represents number of workers.

I ran this on a 2 core machine with 2 hyperthreads, and SSD.

Is this expected? Is there a way to make sure we can read at maximum speed?

**Comment by amitmurthy** [comment]
Could you run this test with a bash script, maybe using `GNU parallel` ? Will help understand how much of the slowdown is system related.
