### ISSUE TITLE
Feature Request: Freestanding support 

### ISSUE THREAD

**Issue by Immortalin** [JuliaLang/julia#17128]
Julia supports calling C code directly, making it extremely useful for a variety of purposes, it will be great if this can extended further so that libjulia can be compiled as a freestanding application I.e. capable of running on bare metal with minimal to no OS support. This will allow Julia to be used for low level programming e.g. kernel development, use in drivers etc. and broaden the range of applications Julia can be used in, increasing the overall utility of Julia.

**Comment by Keno** [comment]
Sorry, but this is not actionable. If anybody wants to take this forward, I'd recommend taking one of the library-OS style projects and just seeing where you run into issues, which can then be filed.
