### ISSUE TITLE
Display regression in assignment to composite type field

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17123]
While [updating the doctests](https://github.com/JuliaLang/julia/pull/17106) I found, what I believe to be, a regression:

Julia 0.4.6
```julia
julia> type Foo
         bar
         baz::Int
         qux::Float64
       end

julia> foo = Foo("Hello, world.", 23, 1.5)
Foo("Hello, world.",23,1.5)

julia> foo.qux = 2
2.0

julia> foo.qux
2.0
```

Julia 0.5-dev
```julia
...

julia> foo.qux = 2  # Should be print 2.0 since `qux` is a Float64 field
2  

julia> foo.qux
2.0
```
Apologies if this has been discussed elsewhere.

**Comment by omus** [comment]
cc: @tkelman (we discussed this earlier today)

**Comment by yuyichao** [comment]
The change is a bug fix. `a.b = c` is supposed to return `c`.

**Comment by yuyichao** [comment]
(Also this has nothing to do with displaying....)

Ref https://github.com/JuliaLang/julia/pull/15753#discussion_r59132424 and https://github.com/JuliaLang/julia/issues/14691

**Comment by tkelman** [comment]
whoops, thanks @yuyichao for having a better memory on this one than I did

**Comment by StefanKarpinski** [comment]
This behavior probably deserves a FAQ entry at this point.

**Comment by omus** [comment]
I've been re-reading the documentation and making corrections. If I find a good spot to mention this behavior I'll add something in.
