### ISSUE TITLE
code_native() output is in the weird AT&T assembly syntax

### ISSUE THREAD

**Issue by Zueuk** [JuliaLang/julia#17139]
While at the same time, every Julia example I find on the interned shows the good old "normal" Intel syntax... And it seems to be hardcoded this way - in src/disasm.cpp:

`unsigned OutputAsmVariant = 0; // ATT or Intel-style assembly`

where 0 = AT&T, and 1 = Intel.

**Comment by yuyichao** [comment]
Adding an option might be acceptable. Note that the option won't be meaningful everywhere.

FWIW this is at least consistent with the default choice in GDB and everything else on Linux.

**Comment by carnaval** [comment]
I'd add that comments are in the weird "english" syntax

**Comment by ivarne** [comment]
If LLVM supports other assembly syntaxes just by changing an option and we have users who wants to change the default output, we should support that (if someone wants to contribute the code). How does it make sense to expose this configuration?

- [ ] Commandline flag to the julia executable (``--asm=[Intel|ATT]``)
- [ ] Environment variable
- [ ] Global variable in Julia
- [ ] Global variable in C (with set/get functions in Julia)
- [ ] Function argument to `code_native` (does not apply well to the macro `@code_native`)


> I'd add that comments are in the weird "english" syntax

It would be nice if we could just make a `0` configurable to fix that :+1:

**Comment by NHDaly** [comment]
Hi, I saw this labelled as an "intro issue", so I've stopped by to look at implementing it.

Personally, I like the "Environment variable" option the least. I think Environment variables are too subtle, and often trip up those less familiar with unix.

The others all seem fine to me. I think I would vote for the commandline flag and a function argument to `code_native`, with the function argument defaulting to the flag's value. How does that sound?

Also, for my own edification, where is the macro `@code_native` defined? I guess `which(@code_native)` doesn't work for macros?

**Comment by MichaelHatherly** [comment]
> Also, for my own edification, where is the macro @code_native defined? I guess which(@code_native) doesn't work for macros?

`@which @code_native 1 + 1` should work in recent builds, but the definition for `@code_native` won't be all that useful to look at since it's just a wrapper around `code_native` (which is a wrapper for the unexported `Base._dump_function`, defined [here](https://github.com/JuliaLang/julia/blob/2c457011df50e173e9846bc9b4e13abfb005ac5e/base/reflection.jl#L335), if I'm following the function calls correctly...)

**Comment by aviks** [comment]
> where is the macro @code_native defined

https://github.com/JuliaLang/julia/blob/83ba37acd28bc1818ad834c70463aa41fa9a5ac4/base/interactiveutil.jl#L342

**Comment by citisolo** [comment]
Can someone assign this to me

**Comment by ivarne** [comment]
It doesn't seem like github lets us assign issues to people that have not (yet) been added to the committers group.

Just adding a comment here refering to your work in https://github.com/JuliaLang/julia/pull/18565 is enough. and if you add something like `fixes #17139` in the PR description, this issue will automatically get closed when the PR is merged.

**Comment by tkelman** [comment]
closed by https://github.com/JuliaLang/julia/pull/18565
