### ISSUE TITLE
Pkg.checkout() from tagged version fails unless checking out master

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#17146]
Starting from a tagged version:

```
julia> Pkg.checkout("TaylorSeries", "warningsv05")
INFO: Checking out TaylorSeries warningsv05...
ERROR: GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)
```

but this works if `master` is `checkout`ed first.

**Comment by tkelman** [comment]
closely related to #16372

**Comment by tkelman** [comment]
should we try a fetch if this tracking-info failure occurs?

**Comment by Keno** [comment]
Yes, we'll need to fetch here.

**Comment by omus** [comment]
Note that if the supplied branch name doesn't exist `Pkg.checkout` will create a branch with that name at the current HEAD.

**Comment by simonbyrne** [comment]
Should no longer be a problem with new Pkg. Please open further issues at https://github.com/JuliaLang/Pkg.jl
