### ISSUE TITLE
File ccalltest.c needs ifdef

### ISSUE THREAD

**Issue by VictorEijkhout** [JuliaLang/julia#17145]
Refer to this ticket:

https://groups.google.com/forum/#!topic/julia-users/PMrAfbaHwIE

The usage of "complex int" is afaik a gcc extension and needs to be ifdef'fed out for the Intel compiler. (At least Intel 15, which is the latest that I'm using.)

**Comment by jingpengwu** [comment]
I encountered the same problem. as suggested comment the error code works, but this is a dirty fix.

**Comment by tkelman** [comment]
there's also a lot of code in that file that MSVC can't compile due to lack of c99 complex support, which should probably also be addressed with appropriate ifdefs.
