### ISSUE TITLE
make empty mutable structs non-singletons

### ISSUE THREAD

**Issue by carnaval** [JuliaLang/julia#17149]
note to self

**Comment by vtjnash** [comment]
:)

I think there may even be a few places already where we do so, but inconsistently. Alternatively, you could make mutable singletons unique values instead of being strangely almost equivalent to their immutable cousins.

**Comment by eschnett** [comment]
Yes, having mutable singletons be unique would be cool. Currently I'm adding an unused `Int` field to a mutable type for this (is there a better way)?

**Comment by yuyichao** [comment]
I thought this is only about codegen calling convention rather than object construction? "mutable" singletons should already be unique. What does adding a `Int` field accomplish?

**Comment by eschnett** [comment]
@yuyichao 

```Julia
type N end
N()===N()
true

type N1 i::Int; N1()=new() end
N1()===N1()
false
```

Each call to `N1()` creates a new, unique object that can be used as abstract id. (An alternative would be using a global counter.) Calls to an empty type constructor such as `N()` don't; all objects of type `N` are identical, as if they were immutable.

**Comment by yuyichao** [comment]
OK, you mean `unique` as each of them are different, not that it has a global unique value.....

**Comment by toivoh** [comment]
@eschnett: You can use a field of eg type `Void` instead of an `Int` field, should save some space? 

But I agree that it would be nice if there could be multiple instances of mutable types without fields. The current behavior was very handy before we had immutables, but now that we do, it just feels inconsistent.

**Comment by stevengj** [comment]
This came up [on discourse recently](https://discourse.julialang.org/t/mutable-struct-without-fields-behaving-weirdly/8752).  I agree that having mutable singletons construct unique (not `===`) objects makes sense nowadays.

**Comment by stevengj** [comment]
Marking as triage since it seems like this should really get decided before 1.0.

**Comment by Keno** [comment]
Triage says yes, let's make empty mutable structs give non-singleton.
