### ISSUE TITLE
rem is broken for Float16

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#17148]
```julia
julia> rem(Float16(1.2),one(Float16(1.2)))
Float16(0.0)
julia> rem(1.2, one(1.2))
0.19999999999999996
```

**Comment by simonbyrne** [comment]
The definition is right: I have no idea what is happening here, but it's broken in 0.4 as well.

**Comment by pkofod** [comment]
No it's not, it's using `a` in both positional arguments on line 157: https://github.com/JuliaLang/julia/blob/861100c15b050885297430e7afc24c7a638de982/base/float16.jl#L157 

I don't hope a lot of people were using these :)

**Comment by simonbyrne** [comment]
Ah, I figured it out when I made exactly the same mistake. Which makes sense, as it was apparently me who made the original mistake.
83ae6d0af5ac7d57ab5f2b7e53d616e6b271ae14
