### ISSUE TITLE
side by side configuration is incorrect

### ISSUE THREAD

**Issue by abhishekupadh** [JuliaLang/julia#17158]
what is solution for showing the side by side configuration is not working

**Comment by tkelman** [comment]
will be fixed by #17136, but actually recording the real error message would be useful

**Comment by vtjnash** [comment]
SxS manifest fixed by https://github.com/JuliaLang/julia/pull/17136

**Comment by tkelman** [comment]
Someone who understands how will need to fix PyCall in a different way.

**Comment by tkelman** [comment]
As a temporary workaround, you can download Julia 0.4.5, or install the MSVC 2008 runtime redistributable package for 0.4.6.

**Comment by abhishekupadh** [comment]
here is the tab that open after complete installation of julia on starting

**Comment by tkelman** [comment]
Email attachments don't work on github. Either attach it here or post a link.

**Comment by abhishekupadh** [comment]
it show as

*The application has failed to start because its side-by-side configuration
is incorrect. Please see the application event log or use the command-line
sxstrace.exe tool for more detail.*

**Comment by abhishekupadh** [comment]
Youth4workHi ,Abhishek Upadhyay, your contact & who has this profileSuggests you to try a quick, 5 min, Online Skill test to know your own skillshttps://www.youth4work.com/onlinetalenttestIt’s a fun test that helps you know where you stand for your skills across the globe. It also helps you get professional opportunities.Regards,Youth4workUnsubscribe
