### ISSUE TITLE
`Pkg.pin` broken, test ineffective

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#17176]
Not sure if this is known, but I couldn't find any open issue about it:
`Pkg.pin` creates a pinned branch, but does not switch to it:

```
julia> Pkg.pin("Example", v"0.4.0")
INFO: Creating Example branch pinned.b1990792.tmp

julia> Pkg.installed("Example")
v"0.4.1"
```

Inside the `Example` directory, this is the situation:

```
~/.julia/v0.5/Example$ git status
Not currently on any branch.
nothing to commit, working directory clean

~/.julia/v0.5/Example$ git branch
* (no branch)
  master
  pinned.b1990792.tmp
```

Also, the part of the tests which should catch this bug is missing a `@test` macro, see [the last line of these three](https://github.com/JuliaLang/julia/blob/cfc10f07431f5c762d4531333864b245a038480d/test/pkg.jl#L185-L187), which is doing nothing with its return value.

This is on latest master, `0.5.0-dev+4990`. It works fine in 0.4.

cc @jakebolewski

**Comment by tkelman** [comment]
@wildart
