### ISSUE TITLE
Pkg.add fails with I/O Error

### ISSUE THREAD

**Issue by Yawolf** [JuliaLang/julia#17174]
Hi,
I'm having problems when I run Pkg.add with any package, at first, julia process consumes all my CPU and RAM, after several minutes, de Pkg.add returns this error:

```
ERROR: stat: i/o error (EIO)
 [inlined code] from stat.jl:44
 in stat at stat.jl:55
 in stat at stat.jl:58
 in isfile at stat.jl:107
 in edit at pkg/entry.jl:21
 in anonymous at task.jl:447
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
```

I' running Julia in my Archlinux, and its the 0.4.5.

Thank you :)

**Comment by tkelman** [comment]
What does `Pkg.status()` say? Where did you install Julia from?

**Comment by Yawolf** [comment]
```
julia> Pkg.status()
ERROR: stat: i/o error (EIO)
 [inlined code] from stat.jl:44
 in stat at stat.jl:55
 in stat at stat.jl:58
 in isfile at stat.jl:107
 in status at pkg/entry.jl:117
 in status at pkg/entry.jl:139
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in status at pkg.jl:32 (repeats 2 times)
```
I installed Julia from the Arch Linux official repositories (pacman), PKGBUILD searches julia in github:
`source=("git://github.com/JuliaLang/julia.git#tag=v$pkgver")`

**Comment by nalimilan** [comment]
Could you try with the generic Linux binaries from julialang.org? That would allow us to know whether this is specific to the way the Arch package is built or not.

**Comment by Yawolf** [comment]
For sure.
Downloading the Generic Linux Binary 64 bits, executing `Pkg.status()` returns the same:
```
ERROR: stat: i/o error (EIO)
 [inlined code] from stat.jl:44
 in stat at stat.jl:55
 in stat at stat.jl:58
 in isfile at stat.jl:107
 in available at ./pkg/read.jl:16
 in status at pkg/entry.jl:117
 in status at pkg/entry.jl:139
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in status at pkg.jl:32 (repeats 2 times)
```

**Comment by nalimilan** [comment]
Thanks. While you're at it, could you try with the development nightlies?

**Comment by Yawolf** [comment]
With the development nightlies wotks porperly :)

**Comment by tkelman** [comment]
Good news. Maybe possible to run in strace to see what file it was trying to stat?

**Comment by Yawolf** [comment]
Here is the trace, The file `intall.pkg` contains only a `Pkg.status()` sentence.
[trace.txt](https://github.com/JuliaLang/julia/files/339956/trace.txt)

**Comment by tkelman** [comment]
`stat("METADATA/SDL/url", 0x7ffdbf1543a0) = -1 EIO (Input/output error)`

does a file exist at `Pkg.dir("METADATA","SDL","url")` ?

**Comment by Yawolf** [comment]
Well, here we have the problem, the `METADATA/` folder exists but it is corrupted or similar, I cannot access or stat it from the shell... Weird...

**Comment by Yawolf** [comment]
Sorry, I can stat it or even list the contents, but cannot go inside, the shell process consumes whole CPU and RAM, well the same synthoms I described before :)

**Comment by tkelman** [comment]
Very strange. Did you upgrade your system git recently?

**Comment by Yawolf** [comment]
Last time I upgraded my git system was on 2016-06-18, so yes, 10 days ago.

**Comment by Yawolf** [comment]
I think it is problem of the shell interpreter, I'm using zsh or fish (this one since 4 days). Using bash as a shell interpreter I can go inside the 'METADATA/' folder.

**Comment by tkelman** [comment]
Very strange. Overloading git coloring or completions or something?

**Comment by Yawolf** [comment]
I think so, using a completely empty `.zshrc` I can go inside the folder without problems, so I guess the problem is in the zsh git completions or coloring. It makes sense because I use the same theme (Robbyrussell) in both interpreters.

**Comment by simonbyrne** [comment]
This does not look like it as an issue any more. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl
