### ISSUE TITLE
Mac OS X build failure

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#17177]
Using master branch.  Previous successful build was 05f2e31.
```
patching file lib/MC/WinCOFFStreamer.cpp
Hunk #1 FAILED at 199.
1 out of 1 hunk FAILED -- saving rejects to file lib/MC/WinCOFFStreamer.cpp.rej
make[1]: *** [/Users/sachs/src/julia-master/deps/srccache/llvm-3.7.1/llvm-win64-reloc-dwarf.patch-applied] Error 1
make: *** [julia-deps] Error 2
```

**Comment by tkelman** [comment]
Can you try applying https://gist.github.com/e349cf5213cfce6ddab21021e7268684 ? Maybe the version of `patch` is pickier on mac than elsewhere?

**Comment by josefsachsconning** [comment]
The tk/fixllvmpatch branch works for me on Mac OS X, if that answers your question.

**Comment by tkelman** [comment]
Yep, thanks!
