### ISSUE TITLE
`identity(;kw...)` should work.

### ISSUE THREAD

**Issue by jamesonquinn** [JuliaLang/julia#17189]
The `identity` function should accept keywords:

`identity((2,4,6)...;Dict(:odd=>1,:odd2=>3)` #=should return=# `(2,4,6,Semicolon,(:odd,1),(:odd2,3))`

...for some value of `Semicolon`, probably `Symbol(";")`.

If people don't want to do this (because it would break `f(#=stuff=#)==f(identity(#=stuff=#)...)`), then there should be something like `identity_with_kw` or `return_args` which does this.

It is of course trivial to write such functions, but there should be some version of them already written in Base, and I think `identity` is the right place for it.

**Comment by jamesonquinn** [comment]
On gitter, it was pointed out that this shouldn't be called `identity`, because `identity(1,2)` shouldn't equal `identity((1,2))`. So `argvalues` or (if "arg" sounds as if it means just positional arguments) `paramvalues` seems like a better name.

**Comment by vtjnash** [comment]
`identity` shouldn't accept multiple arguments. This is instead describing the `tuple` function, where the kwargs form would need to return a structural tuple.
