### ISSUE TITLE
`view` does not work without indices (except for 0-dim arrays)

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17194]
`view` should be able to create a view to a zero-dimensional array, but it does not:

``` Julia
julia> view([])
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
```

**Comment by timholy** [comment]
0-dimensional arrays are actually OK:
```jl
julia> b = reshape([3])
0-dimensional Array{Int64,0}:
3

julia> view(b)
0-dimensional SubArray{Int64,0,Array{Int64,0},Tuple{},false}:
3
```
But indeed, empty arrays are a problem.

**Comment by timholy** [comment]
No, I take that back:
```jl
julia> a = Int[]
0-element Array{Int64,1}

julia> view(a, :)
0-element SubArray{Int64,1,Array{Int64,1},Tuple{Colon},true}
```
The real problem is calling `view` with no indices when passing any kind of array, even one that's not empty:
```jl
julia> a = [3]
1-element Array{Int64,1}:
 3

julia> view(a)
ERROR: ArgumentError: Cannot call front on an empty tuple
 in front(::Tuple{}) at ./tuple.jl:52
 in rdims(::Tuple{}, ::Tuple{Int64}, ::Type{Val{0}}) at ./reshapedarray.jl:54
 in reshape(::Array{Int64,1}, ::Type{Val{0}}) at ./reshapedarray.jl:49
 in view(::Array{Int64,1}) at ./subarray.jl:77
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Expr) at ./REPL.jl:3
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
(though obviously these are two different backtraces). I'm unclear on what the proper behavior should be, and therefore whether this is even a bug. Thoughts?

**Comment by Jutho** [comment]
In my opinion, `view` on an `N`-dimensional array should be called with exactly `N` indices/arguments (not counting the array itself). So it seems this currently works for `N=0` also. The original error in the code of @eschnett is caused because `[]` does not create a zero-dimensional array but an empty (zero-sized) 1-dimensional array. I think the error is the correct behavior.

**Comment by eschnett** [comment]
@Jutho It's debatable whether `view` on any array should be a shortcut for `view(array, :, :, :)` with the appropriate number of `:`. (I think it should.)

Independent of this, the error message is bad. Why does `view` try to access index `1` of the empty array? Is it because it assumes this is a zero-dimensional array, and then tries to use linear indexing to access the element, which doesn't exist? I think this should be caught earlier, with a better error message, e.g. "array too small: trying to create a view of length 1 for an array of length 0".

**Comment by Jutho** [comment]
You are correct, the error message is not really correct nor informative.

As to the meaning of `view(array)`, would there be any use to just wrapping the original array in a `SubArray`?

**Comment by timholy** [comment]
For anyone who wants to look into this, one useful piece of information is that it's perfectly acceptable to supply fewer indices than dimensions: `view` reshapes the parent so it has the same number of dimensions as indices. Example:
```jl
julia> A = rand(3,4,5);

julia> v = view(A, :, 1:7);

julia> size(v)
(3,7)

julia> typeof(v)
SubArray{Float64,2,Array{Float64,2},Tuple{Colon,UnitRange{Int64}},true}

julia> size(parent(v))
(3,20)
```
So when you supply *no* indices, logically it should reshape the parent to a 0-dimensional array. Which means it had better have only one element.

**Comment by Jutho** [comment]
That sounds equivalent to generalized linear indexing, which I thought was seen as a potentially bad thing that might get deprecated ( #14770 ). I don't have a strong preference but don't see the need for such implicit reshapes my applications (which do often require `reshape`, but typically in combination with `permutedims`).

**Comment by timholy** [comment]
It's the better alternative to generalized linear indexing: reshape before you access elements. But we could indeed force the reshape to become explicit.

**Comment by mbauman** [comment]
I don't believe there is anything left to do in this issue beyond #26871 and #27061.  `view([])` checks bounds to make sure that it can access the first element as a zero-dimensional array. #14770 makes it so you can't just do this willy-nilly, you need exactly one element in the array to do it.  This all fits into the grand scheme we've built our arrays on.
