### ISSUE TITLE
Parallel build errors on OS X

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17227]
Since recently my Julia build aborts with this kind of error:
```
rm: build/objconv/: No such file or directory
checkdir:  cannot create extraction directory: build/objconv
make[1]: *** [build/objconv/config.status] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [julia-deps] Error 2
```
(interspersed with other output).

This happens when I build Julia from scratch and in parallel. A serial (`make -j1`) build works fine.

I assume there is a dependency conflict in a Makefile, but I couldn't find it. The `rm` warning seems to come from `objconv.mk` and is probably harmless. (You could add the `-f` flag to suppress the warning.)

**Comment by eschnett** [comment]
The OpenBLAS Makefile contains the line
```Makefile
OPENBLAS_BUILD_OPTS += OBJCONV=$(abspath $(BUILDDIR)/objconv/objconv)
```
I assume that this somehow creates the conflict, but I don't know yet how. I assume that the dependency (unpack objconv before configuring OpenBLAS) is not enforced correctly.

**Comment by tkelman** [comment]
Very plausible, the makefiles around objconv have been a bit unusual and error prone before and we only need to build that on mac. I never seem to write makefiles perfectly correctly, IMO that should be automake/cmake's job. Maybe separating objconv into a different STAGE#_DEPS might help?

**Comment by ViralBShah** [comment]
I think we shouldn't wait for automake/cmake. Best to use the STAGE#_DEPS and keep it as robust as possible.

**Comment by tkelman** [comment]
I'm completely guessing what the problem might be. race conditions or incorrect dependency specifications can be a nightmare to debug. If rr worked on mac then maybe you could deterministically record and replay a failure, but I don't think it does yet.

**Comment by vtjnash** [comment]
fixed by https://github.com/JuliaLang/julia/pull/17587
