### ISSUE TITLE
0.5 error in @time macro

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#17255]
I believe the following was caused by a call to `@time`, but I haven't been able to narrow it down:

```julia
ERROR: LoadError: DomainError:
log will only return a complex result if called with a complex argument. Try log(complex(x)).
 in nan_dom_err(::Float64, ::Float64) at ./math.jl:134
 in log(::Float64) at ./math.jl:140
 in log(::Int64) at ./math.jl:142
 in prettyprint_getunits(::Int64, ::Int64, ::Int64) at ./util.jl:99
 in time_print(::UInt64, ::Int64, ::Int64, ::Int64) at ./util.jl:115
 in macro expansion; at ./util.jl:159 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:266
 in _start() at ./client.jl:322
````

**Comment by tkelman** [comment]
Did a time somehow come out negative?

**Comment by ivarne** [comment]
Seems like `diff.allocd` is negative [here](https://github.com/JuliaLang/julia/blob/2e1bcc6f05c7130f79c999cee8adcc8352203819/base/util.jl#L159). I don't see how that can happen unless the allocation counter wraps?

**Comment by dlfivefifty** [comment]
Here’s the example that triggers it:

	https://travis-ci.org/ApproxFun/BandedMatrices.jl/jobs/141952456
	https://travis-ci.org/ApproxFun/BandedMatrices.jl/jobs/141952458

It’s possible it’s a pointer arithmetic error showing up late, but this seems unlikely if both Linux and Mac are seeing the error in the exact same place.

**Comment by yuyichao** [comment]
This is due to disabling the GC

**Comment by kpamnany** [comment]
One could argue that disabling the GC causes all sorts of unintended consequences and this won't be fixed, in which case this issue could be closed. Or, a simple fix would be to add:
```
if bytes < 0
    bytes = 0
end
```
At the beginning of ``time_print()``. And maybe for ``allocs`` also, if that too can go negative.

**Comment by KristofferC** [comment]
Or print something like "??" in case it is negative.
