### ISSUE TITLE
win32 missing linfo lookup

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#17251]
> It's missing type info. This would be a regression in backtrace quality on win32 which is still somewhat widely used.

https://github.com/JuliaLang/julia/pull/17179#issuecomment-229250386

**Comment by tkelman** [comment]
example comparison at https://github.com/JuliaLang/julia/issues/10595#issuecomment-229240681

**Comment by tkelman** [comment]
care to elaborate on how far you got? kinda sucks to have backtraces contain less information on 32 bit

**Comment by vtjnash** [comment]
decided not to work on it as it seemed annoying and low value.

**Comment by tkelman** [comment]
any breadcrumbs for how this might be fixed then? win32 is the 4th most widely used platform for julia, by a large margin over the 5th.

**Comment by vtjnash** [comment]
the basic idea would be to go through the symbol list and find the address of closest one, similar to https://github.com/JuliaLang/julia/blob/f5764ac530e75d90132b65216d2fc9abe2fa6ea1/src/codegen.cpp#L1205 but returning `lo` instead of `hi - lo` (this is probably essentially what the dlsym call is doing)
