### ISSUE TITLE
Manual notes not formatted

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17269]
The manual sometimes contains note sections which used to be formatted nicely (see [release-0.4](http://docs.julialang.org/en/release-0.4/stdlib/linalg/#Base.qrfact) vs. [latest](http://docs.julialang.org/en/latest/stdlib/linalg/#Base.qrfact)). It appears that the move away from reStructuredText for docstrings inadvertently caused this change.

**Comment by MichaelHatherly** [comment]
We could probably just add support for [admonitions](https://pythonhosted.org/Markdown/extensions/admonition.html) syntax, which appears to be the way to support notes and other "box"-like things in some markdown dialects. I'll have a look at it later tonight or in the morning.

**Comment by MichaelHatherly** [comment]
Closed by #17272.
