### ISSUE TITLE
Computation of mean of a sparse matrix

### ISSUE THREAD

**Issue by parme54** [JuliaLang/julia#17299]
Hi, 

I am a new user of Julia and I have some difficulties working on sparse matrices. 

I have a 506*1116 sparse matrix A for which I would like to compute mean(A,2). The problem is that the mean does not take into account the non zero values and it is like mean(A,2) = sum(A,2)/1116 instead of dividing by the real number of non zero values for each row. 

Could you please help me on the subject ? 
Thx in advance !

**Comment by simonster** [comment]
`sum(A, 2)./mapreducedim(x->x != 0, +, A, 2)`

In the future, please post questions like this to [julia-users](https://groups.google.com/forum/#!forum/julia-users). The issues section of this repository is intended for bug reports.
