### ISSUE TITLE
Mention difference between tarball and full tarball

### ISSUE THREAD

**Issue by Maple-Wang** [JuliaLang/julia#17311]
I want to know the difference bettwen tarball and full tarball? 

![1](https://cloud.githubusercontent.com/assets/7234912/16647276/10114c00-4461-11e6-9406-e8ca76ae5ad4.png)

**Comment by nalimilan** [comment]
The full tarball contains all needed dependencies. We should probably mention this below the table.

**Comment by ivarne** [comment]
Issues with the website should be reported at https://github.com/JuliaLang/julialang.github.com
