### ISSUE TITLE
Race condition with package precompile

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17320]
I have a situation where multiple julia instances might trigger precompilation of the same packages. If that happens, errors occur because the various julia instances try to write to the same precompile file at the same time. This is on a single machine.
#13684 describes a similar issue, but I'm opening a new issue here because the solutions suggested for #13684 won't work for my case: having a machine local precompile location would solve #13684 but not my issue here.

My wild guess is that to fix this problem, #7176 would have to be resolved.

**Comment by stevengj** [comment]
See #5622.

**Comment by ckoe-bccms** [comment]
Hello.

I believe I might be seeing this or a related problem when using the same module in a main program and another module, see [discourse](https://discourse.julialang.org/t/how-to-delete-precompile-cache/13622/11) for the unfortunately long story. Of course it might be that my module loading is messed up, but then the error message is not clear to me.

**Comment by stevengj** [comment]
@ckoe-bccms, this issue is about running multiple `julia` programs simultaneously, whereas your problem seems to involve a single `julia` instance, and hence is unrelated.

**Comment by simonbyrne** [comment]
Should be fixed by #36416.
