### ISSUE TITLE
Unable to use Atom

### ISSUE THREAD

**Issue by The-Kite-Runner** [JuliaLang/julia#17356]
The error messages are shown as follows（windows 8.1 64bit, julia 0.4.6）:

Atom Status:

![alwaysbooting](https://cloud.githubusercontent.com/assets/18660347/16711552/83396a02-4694-11e6-9305-8dbe0444f4f7.png)

Atom package

![usingatom](https://cloud.githubusercontent.com/assets/18660347/16711532/e51edc80-4693-11e6-918f-a60f97586725.png)

MbedTLS building

![mbedtlsbuliding](https://cloud.githubusercontent.com/assets/18660347/16711535/fb9abe20-4693-11e6-934a-569b65fc4900.png)

Curl adding 
![curladd](https://cloud.githubusercontent.com/assets/18660347/16711537/0a8a8564-4694-11e6-9ec3-497300688077.png)

Package Status
![pkgstatus](https://cloud.githubusercontent.com/assets/18660347/16711541/25a8cee6-4694-11e6-8de1-2360784d8252.png)

Thanks

**Comment by yuyichao** [comment]
Not a base julia issue. Also `curl`, `wget`, `fetch` are command line tools and not julia packages.

**Comment by tkelman** [comment]
The lack of a download agent means your PATH is wrong. You or sone piece of software took the location of powershell off your path, it should be there by default and not removed.

**Comment by tkelman** [comment]
See https://github.com/JuliaLang/BinDeps.jl/issues/228
