### ISSUE TITLE
Arrays changes broke JuMP

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#17354]
```jl
using JuMP
m = Model()
@variable(m, tri_3[(i,j)=[(i,i+2) for i in 1:5],k=i:j])
```
gives
```
ERROR: UndefRefError: access to undefined reference
 in copy!(::Base.LinearFast, ::Array{Tuple{Vararg{Any,2}},1}, ::Base.LinearFast, ::Array{Tuple{Any,Any},1}) at ./abstractarray.jl:412
 in rehash!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::Int64) at ./dict.jl:483
 in _setindex!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::JuMP.Variable, ::Tuple{Tuple{Int64,Int64},Int64}, ::Int64) at ./dict.jl:606
 in setindex!(::Dict{Tuple{Vararg{Any,2}},JuMP.Variable}, ::JuMP.Variable, ::Tuple{Tuple{Int64,Int64},Int64}) at ./dict.jl:626
 in setindex!(::JuMP.JuMPDict{JuMP.Variable,2}, ::JuMP.Variable, ::Tuple{Int64,Int64}, ::Int64) at /home/mlubin/.julia/v0.5/JuMP/src/JuMPContainer.jl:49
 in macro expansion; at /home/mlubin/.julia/v0.5/JuMP/src/macros.jl:137 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

This seems to have been broken for quite a while but I haven't been using 0.5. I can spend a bit more time to generate a pure julia error case, but opening this in case the issue is obvious.
CC @IainNZ @joehuchette @tkelman @timholy 

Version:
```
julia> versioninfo()
Julia Version 0.5.0-dev+5247
Commit dad6836 (2016-07-09 01:29 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

**Comment by timholy** [comment]
This actually looks like a type-system error: the key line is
```jl
in copy!(::Array{Tuple{Vararg{Any,2}},1}, ::Array{Tuple{Any,Any},1}) at ./abstractarray.jl:423
 ```
`Vararg{Any,2}` should be instantiated as `Tuple{Any,Any}`. Once these are the same, then rather than calling [this definition](https://github.com/JuliaLang/julia/blob/f8d67f7521287d9325e91fd2142dad5f222e6eaf/base/abstractarray.jl#L405-L406) it should call [this one](https://github.com/JuliaLang/julia/blob/f8d67f7521287d9325e91fd2142dad5f222e6eaf/base/array.jl#L65).

**Comment by timholy** [comment]
It seems possible this is the same as #17350, and if so that a possible fix might already be on the way.

**Comment by timholy** [comment]
To explain a little further, what's happening is that `copy!` is getting called as a consequence of `Dict` rehashing, and the array that's being copied has undefined elements in it. The `Array`-specific `copy!` method handles `#undef`.

**Comment by JeffBezanson** [comment]
Reverting the offending commit from #17350 doesn't seem to fix this.
