### ISSUE TITLE
Pkg.checkout had one job

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#17364]
aka "`Pkg.checkout` doesn't do a checkout"... you can reproduce this via
```
julia> Pkg.clone("https://github.com/tkelman/Git.jl")
INFO: Cloning Git from https://github.com/tkelman/Git.jl
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.checkout("Git","tk/bindeps")
INFO: Checking out Git tk/bindeps...
INFO: Pulling Git latest tk/bindeps...
WARNING: Cannot perform fast-forward merge.
INFO: No packages to install, update or remove

julia> cd(Pkg.dir("Git"))

shell> git log -1 origin/master
commit 8447f3a0e593dd09eac5c9b0341ee82fe6261682
Author: Alex Arslan <ararslan@comcast.net>
Date:   Sun Jul 10 12:46:27 2016 -0700

    Add informative Git badge [ci skip] (#6)

shell> git branch
  master
* tk/bindeps

shell> git log -1
commit 8447f3a0e593dd09eac5c9b0341ee82fe6261682
Author: Alex Arslan <ararslan@comcast.net>
Date:   Sun Jul 10 12:46:27 2016 -0700

    Add informative Git badge [ci skip] (#6)
```

It creates the branch (and tries to merge and pull by default, which is arguably questionable behavior but separate from this issue), but from the working copy rather than the upstream, and it doesn't actually do a checkout.

edit: worth noting that there are no tests of `Pkg.checkout` with more than 1 input

**Comment by tkelman** [comment]
The following patch helps a little and allows `Pkg.checkout("Git", "origin/tk/bindeps", merge=false, pull=false)` to kind of work (doesn't create the branch though, ends up detached), but that's not all the way there.
```diff
diff --git a/base/libgit2/libgit2.jl b/base/libgit2/libgit2.jl
index 89f05da..a2a4468 100644
--- a/base/libgit2/libgit2.jl
+++ b/base/libgit2/libgit2.jl
@@ -199,7 +199,7 @@ function branch!(repo::GitRepo, branch_name::AbstractString,
                  force::Bool=false,           # force branch creation
                  set_head::Bool=true)         # set as head reference on exit
     # try to lookup branch first
-    branch_ref = force ? nothing : lookup_branch(repo, branch_name)
+    branch_ref = force ? nothing : lookup_branch(repo, branch_name, !isempty(track))
     if branch_ref === nothing
         # if commit is empty get head commit oid
         commit_id = if isempty(commit)
```

**Comment by davidanthoff** [comment]
I just tried this on a fresh machine with today's build (Commit d528b63), and even this simple sequence of commands leaves the repo in a broken state:

``julia> Pkg.add("DataFrames")``
and then
``julia> Pkg.checkout("DataFrames", "nl/nullable")``
doesn't work.

A ``Pkg.status()`` then also shows a weird thing:

````
julia> Pkg.status()
1 required packages:
 - DataFrames                    0.7.6              nl/nullable
12 additional packages:
 - BinDeps                       0.4.1
 - Compat                        0.8.6
 - DataArrays                    0.3.7
 - Docile                        0.5.23
 - GZip                          0.2.19
 - Reexport                      0.0.3
 - Rmath                         0.1.2
 - SHA                           0.2.0
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - URIParser                     0.1.5
````
Note that the correct ``nl/nullable`` branch and 0.7.6 tag would point to different commits. This does semi-permanent harm to the local repo: it adds a local branch that points to the wrong commit. So even if this regression was fixed in a newer release, people would almost certainly have to manually clean up the branches in that repo before things would work again.

In my view this has to be a release blocker for 0.5.0.

**Comment by davidanthoff** [comment]
Hurray, thanks!
