### ISSUE TITLE
Set union returns the right value in some contexts ... not so much in others

### ISSUE THREAD

**Issue by chipkent** [JuliaLang/julia#17368]
Set operations using union!() and union() do not return correct values in some contexts.

Reproducer:  https://gist.github.com/chipkent/76593700e7b77b42aa816fd4acf2d576
Version: julia version 0.4.5

Running this reproducer results in:
11111 Set(AbstractString["/tmp/tmpOt808Z/X/B.ser"])
2222 Set(AbstractString["/tmp/tmpOt808Z/A.ser","/tmp/tmpOt808Z/X/B.ser"])
The second result is correct.

Sorry the reproducer is long.  I had problems making it shorter.

**Comment by TotalVerb** [comment]
Use `local s` to declare the variable in the inner scope (your definition of `glob1`). See https://github.com/JuliaLang/julia/issues/16727.

**Comment by chipkent** [comment]
Thanks for the quick reply.  It does work with the addition of `local`.  I guess I am surprised that the definition of s within the inner function actually defines it at the outer function scope.  This behavior seems strange and unexpected; although, I guess it could be done this way.
