### ISSUE TITLE
missing sparse(F[:PtL]) function

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#17370]
For the sparse Cholesky package (Cholmod), the Julia documentation states that the `:L` factor is not useful because it does not carry the permutation.  The manual states that the `:PtL` factor should be used instead.  But there doesn't seem to be a documented way to bring the `:PtL` factor back into Julia.  In other words,

``` julia
F = cholfact(A)
L = sparse(F[:L])
```

works as expected, but 

``` julia
F = cholfact(A)
PtL = sparse(F[:PtL])
```

causes an error:

``` julia
julia> PtL = sparse(F[:PtL])
ERROR: MethodError: `size` has no method matching size(::Base.SparseMatrix.CHOLMOD.Factor{Float64})
Closest candidates are:
  size(::Base.SparseMatrix.CHOLMOD.Factor{Tv}, ::Integer)
  size(::Any, ::Integer, ::Integer, ::Integer...)
 in convert at sparse/sparsematrix.jl:214
 in sparse at sparse/sparsematrix.jl:320
```

I already posted a question about this on the Julia users newsgroup.  Since nobody answered, I assume it is a legitimate issue.

**Comment by andreasnoack** [comment]
I agree that it would be useful have but I'm not sure how to either extract the `PtL` factor directly or just the permutation vector. If somebody can point a place in CHOLMOD where this can be done it probably shouldn't be hard to fix but if we can't find a function for this in CHOLMOD it will be difficult to support.

**Comment by StephenVavasis** [comment]
Andreas, i actually already wrote a function for the desired purpose because I need it for my application.  However, my function wastefully creates several intermediate arrays.  Here it is:

```julia
# Compute the permuted cholesky factor of a sparse, symmetric 
# positive definite matrix A.
function cholfactPtL(A)
    n = size(A,1)
    F = cholfact(A)
    L0 = sparse(F[:L])
    is, js, es = findnz(L0)
    p = Base.SparseMatrix.CHOLMOD.get_perm(F)
    sparse(p[is], p[js], es, n, n)
end
```

**Comment by andreasnoack** [comment]
Oh. I missed `get_perm`. Then it shouldn't be hard to get a method for this. It seems that

```jl
function myPtL(F)
    L = sparse(F[:L])
    p = Base.SparseArrays.CHOLMOD.get_perm(F)
    return L[invperm(p),:]
end
```

is a bit faster. I also tried with 
```jl
function myPtL2(F)
    L = sparse(F[:L])
    p = Base.SparseArrays.CHOLMOD.get_perm(F)
    return SparseArrays.permute_rows!(L, invperm(p))
end
```
but that was slower. So `myPtL` might be the best we can do if CHOLMOD doesn't have a function for this. A more advanced solution would be to construct the `PtL` matrix directly from the fields of the `Factor`. How performance critical is this construction to you? I guess that, most often, being able to solve with `F[:PtL]` is sufficient.

It would be great with a PR.

**Comment by StephenVavasis** [comment]
Andreas,

A proper PR for this would create functionality not only `:PtL` but also for `:UP` and many others, and it would also require proper test cases.  And ideally it should draw the data right out of the C data structures rather than relying on intermediate Julia arrays as in my solution.  I'm not able to commit to this much work right now, unfortunately.

-- Steve

**Comment by ViralBShah** [comment]
Perhaps the solution discussed in https://github.com/JuliaLang/julia/issues/26147 helps. Should we document it in the sparse docs?
