### ISSUE TITLE
Possible regression with dump of String

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17392]
Probably is intended behaviour but dumping strings no longer shows human friendly output. 
[As mentioned](https://github.com/JuliaLang/julia/pull/17106/files#r70366289) by @tkelman the change was made in 3405d26 (#15707).

Julia 0.4.6
```julia
julia> dump(:("a ($a) should equal b ($b)!"))
Expr 
  head: Symbol string
  args: Array(Any,(5,))
    1: ASCIIString "a ("
    2: Symbol a
    3: ASCIIString ") should equal b ("
    4: Symbol b
    5: ASCIIString ")!"
  typ: Any
```

Julia 0.5-dev
```julia
julia> dump(:("a ($a) should equal b ($b)!"))
Expr
  head: Symbol string
  args: Array{Any}((5,))
    1: String
      data: Array{UInt8}((3,)) UInt8[0x61,0x20,0x28]
    2: Symbol a
    3: String
      data: Array{UInt8}((18,)) UInt8[0x29,0x20,0x73,0x68,0x6f,0x75,0x6c,0x64,0x20,0x65,0x71,0x75,0x61,0x6c,0x20,0x62,0x20,0x28]
    4: Symbol b
    5: String
      data: Array{UInt8}((2,)) UInt8[0x29,0x21]
  typ: Any
```

**Comment by omus** [comment]
cc: @JeffBezanson, @StefanKarpinski

**Comment by JeffBezanson** [comment]
Yes, this was intended. `dump` now shows the gory details of all objects in a consistent way. Maybe we could add an option to `dump` to tell it not to expand certain objects, e.g. `dump(x, noexpand=[AbstractString])`.

**Comment by StefanKarpinski** [comment]
A depth option might be good too.

**Comment by tkelman** [comment]
there already is a depth option
```
julia> dump("foo"; maxdepth=0)
String
julia> dump("foo"; maxdepth=1)
String
  data: Array{UInt8}((3,)) UInt8[0x66,0x6f,0x6f]
```

**Comment by StefanKarpinski** [comment]
Right, I meant for expanding, not showing, but maybe those should be the same.

**Comment by tkelman** [comment]
@vtjnash should cross reference where this was changed instead of closing with no justification
