### ISSUE TITLE
fld(1,0.2) returns 4.0

### ISSUE THREAD

**Issue by remore** [JuliaLang/julia#17415]
I'm totally not sure why this happens. Does anyone know if this is spec or bug?

``` jl
julia> 1/0.2
5.0

julia> floor(1/0.2)
5.0

julia> fld(1,0.2)
4.0
```

I'm using Mac OSX and Julia version is `0.4.6`.

**Comment by pkofod** [comment]
This is due to `mod` used with floating point numbers. In the calculation, `mod(1., 0.2)` is calculated, and that is
```jlcon
julia> mod(1., .2)
0.19999999999999996
```

**Comment by vtjnash** [comment]
looks like a floating point rounding difficulty. for Reals, `fld` is defined as:
```
julia> (1 - mod(1, 0.2)) / 0.2
4.0
```

which comes from `rem(1, 0.2)` computing as being just less than 0.2, rather than exactly `0.0`, which comes from `fmod`, which is computing with the floating-point number closest to 0.2, not actually 0.2:

```
julia> ccall(:fmod, Cdouble, (Cdouble, Cdouble), 1.0, 0.2)
0.19999999999999996

julia> bits(0.2)
"0011111111001001100110011001100110011001100110011001100110011010"
```

**Comment by yuyichao** [comment]
Is there a reason `fld` is not just defined as `floor(x / y)`, since that's what the definition suggests and seems to use the same number of divisions?

**Comment by simonbyrne** [comment]
It's because `0.2` is stored in binary, so isn't actually 2/10, but instead:
```
julia> @printf "%.60f" 0.2
0.200000000000000011102230246251565404236316680908203125000000
```
For more details, see #3127.

We're probably not going to change behaviour, but this is probably worth documenting.

**Comment by yuyichao** [comment]
In that case is `floor(1 / 0.2)` wrong? And/or should the definition of `fld` be change to the largest interger `n` such that `y * n` is less than or equal to `x`?

**Comment by simonbyrne** [comment]
> And/or should the definition of fld be change to the largest interger n such that y * n is less than or equal to x

That seems like good idea.

**Comment by remore** [comment]
Everything makes sense to me. It would be nice if this is documented.

**Comment by JuliaNumberTypes** [comment]
+1 to better definitions (and fld, cld should be defined in that same better defined way)
it may be a little clearer to add that, for any real finite(x) and any real nonzero finite(y),
   fld(x,y) <= cld(x,y)

**Comment by eschnett** [comment]
You can extend that constraint to
```
fld(x,y) <= x/y <= cld(x,y)
```
for floating-point types, and
```
fld(x,y) <= div(x,y) <= cld(x,y)
```
for integer types.

**Comment by laborg** [comment]
I think this can be closed - the doc for `fld` has been updated:
```julia
  Because fld(x, y) implements strictly correct floored rounding based on the true value of floating-point numbers, unintuitive situations can arise. For
  example:

  julia> fld(6.0,0.1)
  59.0
  julia> 6.0/0.1
  60.0
  julia> 6.0/big(0.1)
  59.99999999999999666933092612453056361837965690217069245739573412231113406246995

  What is happening here is that the true value of the floating-point number written as 0.1 is slightly larger than the numerical value 1/10 while 6.0
  represents the number 6 precisely. Therefore the true value of 6.0 / 0.1 is slightly less than 60. When doing division, this is rounded to precisely 60.0,
  but fld(6.0, 0.1) always takes the floor of the true value, so the result is 59.0.
```
