### ISSUE TITLE
LibGit2 should not extend `Base.finalize`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#17414]
`Base.finalize` has well define meaning and the overload doesn't do that.

Ref https://github.com/JuliaLang/julia/pull/17409#discussion_r70791075

**Comment by JeffBezanson** [comment]
More importantly, if the intent was to add finalizers for these objects, then it's not working and the objects are never getting finalized.

**Comment by JeffBezanson** [comment]
Ah, I see the code uses `with`. If all objects are guaranteed to be freed that way, then these can just become methods of `close` instead.
