### ISSUE TITLE
Generic Linux Binaries are built with ABI tags

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#17446]
Doesn't make to much of a difference since we don't have public C++ APIs, but it does affect whether people with older systems can easily build Cxx.jl against a binary release of julia, which I think would be desirable.

**Comment by tkelman** [comment]
They need to be built with a newer gcc version than any users will have as their distro system compiler. At the moment I think it's 5.2, we'll upgrade to 6 when needed. I think clang just needs to fix this mess from their side. Try applying arch linux's clang patch set?

**Comment by Keno** [comment]
That's not the problem. The problem is older gccs.

**Comment by Keno** [comment]
Note, I'm not saying we should build with an older compiler, all I'm saying is we should build with the old C++ abi, which is compatible with older compilers.

**Comment by tkelman** [comment]
will that cause issues on distros that user newer gcc with the new abi by default? you can propose adding the old abi define in the buildbot config

**Comment by Keno** [comment]
Not really. As I said, it's only really a problem with Cxx.jl, since it needs our LLVM symbols, so as long as I keep the defines consistent, there's no problem. I think all you have to do is add `-D _GLIBCXX_USE_CXX11_ABI=0` to the compiler invocation.

**Comment by Keno** [comment]
Ok, so can we try out setting `-D_GLIBCXX_USE_CXX11_ABI=0`?

**Comment by tkelman** [comment]
we can try it. however the buildbot is not very flexible in terms of using different settings for different builds, so this would also apply to 0.4 builds.

**Comment by Keno** [comment]
Great, let me know when the first binaries with that change are up and I'll verify that it worked.

**Comment by tkelman** [comment]
A few hours hopefully, whenever https://build.julialang.org/builders/package_tarball64/builds/649 gets triggered. If this causes any noticeable issues we may need to revert it, but let's see.

**Comment by tkelman** [comment]
Does this mean that everyone who wants to use Cxx.jl needs to build their C++ libraries with the old ABI too, even on new distros?

**Comment by Keno** [comment]
For now, yes, but that's unrelated and because Clang doesn't support ABI tags until 3.9. Once we switch to 3.9, they won't have to anymore, independent of what this setting is.
