### ISSUE TITLE
integrate Float16 into stdlib along side Float32, Float64

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#17440]
Since we've decided that Float16 should behave like Float32 and Float64, the code for Float16 should probably be moved into the standard library alongside those other types. Since Float16 doesn't have hardware support on most systems Julia runs on, the core definitions will be quite different (convert to Float32, operate, convert back), but the higher level definitions will be much the same. Having definitions for Float16 alongside Float32 and Float64 will make it easier to ensure that the types have similar behaviors. See: #5942, #15359, #16411, #17261.

**Comment by quinnj** [comment]
An excellent starter, up-for-grabs kind of issue.

**Comment by vchuravy** [comment]
Also we have to think about how we are going to integrate `Float16` in Base with platforms that actually support it. The current definition will break those platforms. Secondly to actually reap benefits we should use the CPU instructions for conversion between Float32 to Float16, which will require some from of #17344 

Does anybody know any other platforms besides GPUs that actively supports operations on Float16?

**Comment by eschnett** [comment]
Some ARM CPUs have hardware Float16 instructions.
