### ISSUE TITLE
ccall fails from embedding Julia into C

### ISSUE THREAD

**Issue by akorotkov** [JuliaLang/julia#17451]
Hi!

I'm trying to run following example of embedding Julia into C.

```c
#include <julia.h>

int my_func()
{
    return 1;
}

int main(int argc, char *argv[])
{
    /* required: setup the julia context */
    jl_init(JULIA_INIT_DIR);

    /* run julia commands */
    jl_eval_string(
        "try\n"
        "    print(ccall(:my_func, Cint, ()))\n"
        "catch err\n"
        "    print(\"$err\n\")\n"
        "end\n"
    );

    /* strongly recommended: notify julia that the
         program is about to terminate. this allows
         julia time to cleanup pending write requests
         and run all finalizers
    */
    jl_atexit_hook(0);
    return 0;
}
```

And I got following error.

```
ErrorException("ccall: could not find function my_func")
```

The OS is CentOS Linux 7.1, compiler is gcc 4.8.5.

julia version 0.4.6 is installed from nalimilan/julia repository.
I'm building example using following command.

```bash
/usr/share/julia/julia-config.jl --cflags --ldflags --ldlibs | xargs clang embed.c -o embed
```

The same example works fine for me on Mac OS X 10.10.5.
What am I doing wrong?

**Comment by yuyichao** [comment]
`-Wl,--export-dynamic`

**Comment by akorotkov** [comment]
It works! Many thanks!

**Comment by tkelman** [comment]
Should that be added (sometimes?) to `julia-config.jl` ?

**Comment by yuyichao** [comment]
The option only makes sense for executables and not for shared objects (not sure if any linker gives warning or error for that though) so it shouldn't be added to `julia-config.jl` unless we have different options for executables and libraries.

**Comment by yuyichao** [comment]
This option is also not really necessary to make julia function correctly, only when a symbol in the main executable is looked up dynamically so it feels a little strange to require it. I do agree we should document this since many people might want to do this and hence the doc label.

**Comment by tkelman** [comment]
this also looks like exactly the same question as https://groups.google.com/forum/#!topic/julia-users/rj8i4r6id9M
