### ISSUE TITLE
`@code_warntype` etc confused by parsing `Ac_mul_B` etc

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#17469]
I came across this (rather minor) issue this morning: when I ran `@code_warntype` on some matrix multiplication code I have for [StaticArrays](https://github.com/andyferris/StaticArrays.jl) I was given the wrong return type (and code) for `@code_warntype A' * B`. 

It seems these macros first perform the transpose and then call `*`, instead of lowering it to `Ac_mul_B`. It seems the same issue persists with the other combinations of `'` and `.'` and the other `@code_x` macros.

**Comment by andreasnoack** [comment]
I didn't include a test in https://github.com/JuliaLang/julia/pull/12186

**Comment by andreasnoack** [comment]
Broken by #17096.

cc: @ihnorton

**Comment by JeffBezanson** [comment]
Fixed by new transpose/adjoint design.
