### ISSUE TITLE
`isvalid(::String)` is not defined but documented.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#17467]
Ref https://github.com/JuliaLang/julia/pull/16590#discussion_r71087766 and https://github.com/JuliaLang/IJulia.jl/pull/441 (Opening an issue so that it is not lost).

I'm not sure what's the decision (I assume the method was deleted by accident?) but we should either fix the document (for `isvalid(value) -> Bool`) or add the method back.

**Comment by stevengj** [comment]
Note that we still have `isvalid(String, s::String)`, so fixing this issue would be as simple as adding `isvalid(s::String) = isvalid(String, s)`
