### ISSUE TITLE
some deps/*mk don't honor USE_SYSTEM_*

### ISSUE THREAD

**Issue by ustcscgy** [JuliaLang/julia#17473]
````
grep USE_SYSTEM_ deps/*mk
````

You'll find only a few packages honor `USE_SYSTEM_`, most simply ignore it.  For example, `libgit2.mk`, `mbedtls.mk`.

**Comment by yuyichao** [comment]
I don't think this is the case.

**Comment by wildart** [comment]
We use patched versions of `mbedtls` and `libgit2` because not all system binaries provide required functionality.

**Comment by yuyichao** [comment]
i.e. these options works fine for me. Please comment for reopening if any of these options doesn't work for you.

**Comment by tkelman** [comment]
using a system libgit2 should be fine if it's new enough, we don't absolutely need the mbedtls stuff except to provide ssh in source builds

**Comment by ustcscgy** [comment]
Well, then maybe remove USE_SYSTEM_LIBSSH2 from Makefile to avoid confusion.

**Comment by wildart** [comment]
Not quite, it looks like `libgit2` 0.24 on Debian comes without SSL support, https://packages.debian.org/source/testing/libgit2

**Comment by yuyichao** [comment]
I don't know what's the confusion but FYI `grep USE_SYSTEM_ deps/*mk` is not the right way to check how the options work.

**Comment by tkelman** [comment]
we could also probably use a source build of libgit2 against a system copy of libssh, but that may need more testing and patches to ensure it works.

**Comment by ustcscgy** [comment]
@yuyichao , what do you mean by "these options works fine for me", you can build julia with a libssh2 from system, i.e. while building, julia doesn't download it?

**Comment by yuyichao** [comment]
Correct.

**Comment by ustcscgy** [comment]
@wildart , there are distros other than debian, for example, in gentoo, libgit2 can support ssh.

**Comment by tkelman** [comment]
we now have a test in julia which should fail if the used version of libgit2 doesn't support https or ssh.

**Comment by ustcscgy** [comment]
@yuyichao , my bad, seems I messed up somewhere else,
