### ISSUE TITLE
What goes into NEWS.md?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#17478]
I'm not sure of the rules that determine what gets into NEWS.md (aka Julia v0.5.0 Release Notes). Is it just the major changes and additions, or does it include most or all user-facing changes?

I'm wondering because I didn't see `walkdir()` in NEWS.md, which seems like a useful new function that people might want to know about. I had a quick look at the first page of the change history of the help file for file-related stuff ([julia/doc/stdlib/file.rst](https://github.com/JuliaLang/julia/commits/f53b00e95f08496c232a0203f6e1372dbadcb6a4/doc/stdlib/file.rst)) and saw some possibly useful additions and changes (`chown()`, `chmod()`) which don't appear to have made it through to NEWS.md.

I can see that the document might get too big if every single thing goes in... On the other hand, it's nice that people get to hear about any cool new stuff going in to the 0.5 release.

**Comment by tkelman** [comment]
Noticeable new functionality or performance improvements should at least be briefly mentioned. We don't need an entry for every little bug fixes, but for anything you'd notice I'd err on the including too much side rather than leaving things out.

**Comment by JeffBezanson** [comment]
@cormullion Feel free to make a pull request to add those functions to NEWS.md.
