### ISSUE TITLE
Julia TLS stream implementation for LibGit2

### ISSUE THREAD

**Issue by wildart** [JuliaLang/julia#17471]
In order to avoid OpenSSL dependency (https://github.com/JuliaLang/julia/issues/10763) in `libgit2`, custom TLS stream framework should be utilized to construct streams with different TLS library.

Required:
- [x] Native TLS stream implementation based on MbedTLS.jl: https://github.com/wildart/MbedTLSStream.jl
- [ ] remove OpenSSL dependency while building `libgit2` for Linux
 - `-DUSE_OPENSSL=OFF`
 - Enable https transport for custom TLS streams in `libgit2`, see https://github.com/libgit2/libgit2/pull/3850 
- [ ] Initialization of custom TLS stream in `LibGit2` module
- [ ] MbedTLS.jl should use on `libmbed*` from julia build, see https://github.com/JuliaWeb/MbedTLS.jl/issues/54
- [ ] Proxy support

Refs: https://github.com/JuliaLang/julia/pull/17246, https://github.com/JuliaWeb/MbedTLS.jl

**Comment by petercolberg** [comment]
If libgit2/libgit2#3462 is merged to transparently support MbedTLS in libgit2, will this no longer be needed?

**Comment by Keno** [comment]
correct
