### ISSUE TITLE
overloading `show` for text/plain requires 3-argument version if custom type is an `AbstractArray`

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#17491]
The latest docs for `show` and friends say:

> The default MIME type is MIME"text/plain". There is a fallback definition for text/plain output that calls show with 2 arguments. Therefore, this case should be handled by defining a 2-argument show(stream::IO, x::MyType) method.

However, if `MyType` subtypes `AbstractArray` and you define the 2-argument version of `show`, julia ends up calling [this 3-arg definition](https://github.com/JuliaLang/julia/blob/f5764ac530e75d90132b65216d2fc9abe2fa6ea1/base/replutil.jl#L136) for `AbstractArray` instead of your version.

Would it cause problems if the `AbstractArray` definition used the 2-argument version?

**Comment by vtjnash** [comment]
the doc update issue is https://github.com/JuliaLang/julia/issues/16763
