### ISSUE TITLE
make fails in cmake/FindmbedTLS.cmake?

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#17497]
Latest git pull for julia 5 fails during make. Versioninfo from version 4 (version 5 no longer available due to make distclean) is:
```
versioninfo()
Julia Version 0.4.6
Commit 2e358ce* (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: liblapack.so.3
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Error seems to be at
```
-- Installing: /home/colin/Downloads/julia/usr-staging/mbedtls-2.3.0/home/colin/Downloads/julia/usr/include/mbedtls/config.h
The next patch would create the file cmake/FindmbedTLS.cmake,
which already exists!  Applying it anyway.
patching file cmake/FindmbedTLS.cmake
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file cmake/FindmbedTLS.cmake.rej
patching file src/CMakeLists.txt
Hunk #1 FAILED at 48.
Hunk #2 FAILED at 71.
```
Full attempt in gist at https://gist.github.com/colbec/8001cacde5c2d9d1b97570265a953491

I attempted `make clean` and `make distclean` but no change.

**Comment by tkelman** [comment]
try `make -C deps distclean-libgit2 distclean-mbedtls distclean-libssh2`

**Comment by colbec** [comment]
@tkelman Thanks, this works. Make now completes and make testall is now running fine.

**Comment by Fedster** [comment]
I have the same issue (lates 0.5 pull today Agust 5th):

patching file include/mbedtls/config.h
Hunk #1 succeeded at 2482 (offset 48 lines).
/bin/sh: cmake: command not found
make[1]: *** [build/mbedtls-2.3.0/Makefile] Error 127
make: *** [julia-deps] Error 2

running make -C deps distclean-libgit2 distclean-mbedtls distclean-libssh2 and make cleanall does not fix

**Comment by yuyichao** [comment]
> /bin/sh: cmake: command not found
