### ISSUE TITLE
eachindex(::Number)

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#17492]
It's a little sad that this isn't defined. For instance, in [VectorizedRoutines.jl](https://github.com/ChrisRackauckas/VectorizedRoutines.jl), the implementation of [`rep`](https://github.com/ChrisRackauckas/VectorizedRoutines.jl/blob/master/src/r.jl) taking a number as the first argument has to either create a temporary array, or duplicate code, or create an immutable `AbstractArray` subtype that wraps a number. Neither are very attractive.

Is there any reason why the definition

``` julia
eachindex(::Number) = 1
```

does not exist? I realize `Number`s are not `AbstractArray`s, but neither are `Tuple`s or `Associative`s. If this definition seems acceptable to most, I'll make a PR.

**Comment by TotalVerb** [comment]
On the other hand, if the plan is to eventually go with https://github.com/JuliaLang/julia/issues/7903, I think we need some equivalent to `x -> setindex!(Array(typeof(x)), x)` that does not allocate—`Ref` does this, but is not an `AbstractArray` subtype.

**Comment by kshyatt** [comment]
Since we got rid of `getindex` for numbers, do we want to have this?

**Comment by TotalVerb** [comment]
@kshyatt If `getindex` has been eliminated, it looks like the vestiges of the 0-dimensional array interface are being taken apart. I think strongly that something needs to be added to replace this: a zero-allocation zero-dimensional array that simply wraps a single scalar value.

**Comment by tkelman** [comment]
We didn't get rid of getindex for numbers (yet). There was a PR but it hasn't been merged.

**Comment by KristofferC** [comment]
```
julia> eachindex(1)
Base.OneTo(1)
```
