### ISSUE TITLE
Wrong assert statement in gc.c?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17501]
gcc 6.1 tells me:
```
/Users/eschnett/src/julia-0.5/src/gc.c:1007:32: warning: comparison of constant
      -1 with expression of type 'uint16_t' (aka 'unsigned short') is always
      true [-Wtautological-constant-out-of-range-compare]
    assert(pg->fl_begin_offset != -1);
```
Maybe a cast is missing?

**Comment by yuyichao** [comment]
I think @vtjnash was working on a patch.

**Comment by vtjnash** [comment]
I gave up when I found that clang (incorrectly) was also giving me that same warning for the most standards-compliant way to write this comparison: `~(uint16_t)0`

**Comment by Keno** [comment]
Why doesn't `assert(pg->fl_begin_offset != (uint16_t)-1);` just work?

**Comment by eschnett** [comment]
@vtjnash Isn't the conversion to `uint16_t` undone by integer promotion? Integer promotion converts types that are "smaller" than `int` to `int` before applying an operator, thus your expression is equivalent to `~(int)(uint16_t)0`.

@Keno `pg->fl_begin_offset != (uint16_t)-1` is also used elsewhere, and seems to work.

What about using `UINT16_MAX` instead?
