### ISSUE TITLE
Very slow module load after addprocs()

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#17509]
This is a continuation of discussion from https://groups.google.com/forum/#!topic/julia-users/smW1fnz1gtA Copying my comment from there,

I noticed that once I addprocs(), subsequent "using" statements were extremely slow. I guess in this case its loading the module on each processor, but if it happens in parallel it shouldn't be _that_ much more wall time, and here I'm talking about two orders of magnitude difference. 

Assuming I've got a file Empty.jl who contents is,

``` julia
module Empty
end
```

then single threaded:

``` julia
tic(); using Empty; toc()
elapsed time: 0.024461076 seconds
```

vs. multi-threaded:

``` julia
addprocs() #I've got 8 procs
tic(); using Empty; toc()
elapsed time: 2.479418079 seconds
```

It was suggested this has to with JIT compiling of parallelization code, which might be partially true because loading a second module other than `Empty` isn't as slow (but still somewhat slower). However the slow down seems to also scale with how long it takes to load the module itself so it doesn't seem to be entirely the JIT compiling. E.g. 

``` julia
tic(); using PyPlot; toc()
elapsed time: 3.395904233 seconds
```

vs

``` julia
addprocs();
tic(); using PyPlot; toc()
elapsed time: 13.877550518 seconds
```

or even:

``` julia
addprocs();
using Empty; tic(); using PyPlot; toc()
elapsed time: 7.357315778 seconds
```
## Version Info

I've tested on:

```
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.8
```

as well as 

```
Julia Version 0.5.0-dev+4867
Commit 01e3c8a* (2016-06-19 11:17 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by stevengj** [comment]
Note that there are probably two separate things here.

First, `import` with multiple processes imports the module first on the master process, and then (in parallel) on the worker processes.  So, it takes at least twice as long as importing once.  This is probably the dominant effect for a large module like `PyPlot`.

Second, `import` with N worker processes processes requires that the master process read the files to be imported N times, sending them one-by-one as N strings to the worker processes.   This communication overhead is probably the dominant effect for small modules like `Empty`.  This could probably be improved if we read the file once, and then distributed it to the workers with a tree algorithm or something.   (But even then there would be a communications overhead vs. the serial `import`.)

**Comment by marius311** [comment]
Thanks, that's very helpful. The last thing I don't understand then is how this explains this case:

```julia
addprocs();
tic(); using PyPlot; toc()
elapsed time: 13.877550518 seconds
```

From the first `Empty` example, I gather JIT compiling whatever parallelization code exists is about ~2.5 seconds. From the following case,

```julia
addprocs();
using Empty; tic(); using PyPlot; toc()
elapsed time: 7.357315778 seconds
```

I have that all of the effects you described minus the JIT compilation (which presumably all happens on the `using Empty` outside the tic/toc) is the 7.3 you see there (and as expected based on your description, about twice what it is on just one core). 

But 7.3 + 2.5 I'm still short of 13.9 by about 4 seconds. 

Put another way, it would seem that I could speed up the initialization of my parallel script by putting a `using Empty` at the top of it, which to me seems like it must be indicative of some sort of bug. Am I missing something?

**Comment by marius311** [comment]
Well, that's odd, I tried reproducing this case

```
addprocs();
using Empty; tic(); using PyPlot; toc()
elapsed time: 7.357315778 seconds
```

and I'm getting instead ~11 seconds, which is the missing 4 sec, so nevermind. 

In the end though that does mean that even once parallelization code is compiled, a module the size of e.g. PyPlot takes ~3x longer to load than without parallization, so there must be more overhead there than just 2x expected from first loading it on the master then on the workers. 

Anyway, I'll leave it up to you whether to close this issue or continue digging.

**Comment by Volker-Weissmann** [comment]
For anyone asking if this is a real issue:

```julia
using Distributed
addprocs(128)
@time import DifferentialEquations
```

```
$ time julia-1.6.2/bin/julia perf.jl 



207.939578 seconds (28.80 M allocations: 1.986 GiB, 0.36% gc time, 0.01% compilation time)

real	3m36.545s
user	2m41.210s
sys	0m51.766s
```

```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7542 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

**Comment by vtjnash** [comment]
precompilation and multi-process races with it are fixed now. At some point I think it was doing the load first fully on proc 1 before sending the `@everywhere` message to the other workers. That code may be able to be simplified now, if still present.
