### ISSUE TITLE
Intrinsic misuse causes segfault

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#17538]
Since https://github.com/JuliaLang/julia/commit/7a6a9e0f275225d4e99d7007fd876e37c45a3577#diff-1c5f176b087e9647926b0146fd80117eL823 from #13485 the number of arguments to an intrinsic isn't checked anymore, commonly resulting in segfaults when passing too few of them:

```
julia> Base.box(1)

signal (11): Segmentation fault
```

While on 0.4:

```
julia> Base.box(1)
ERROR: error compiling anonymous: box: wrong number of arguments
```

I'm sure there's a plan forward here, and while intrinsic aren't meant to be used without care it doesn't seem like a good plan to just have them fault where there used to be some form of error reporting.

cc @vtjnash

**Comment by vtjnash** [comment]
Oscar (https://github.com/JuliaLang/julia/compare/ob/interp_call) and I (https://github.com/JuliaLang/julia/compare/jn/jlinterpreter) have fixed this, but we have just been bad about getting it onto master.

**Comment by KristofferC** [comment]
`Base.box` is now gone.

**Comment by maleadt** [comment]
Well, this issue wasn't about `Base.box` really, but it seems like intrinsic calls (both interpreted and compiled) do check their arguments again so this can be closed.

**Comment by KristofferC** [comment]
Sorry for premature closing and thanks for checking.

**Comment by maleadt** [comment]
No problem, thanks for working your way through stale issues!
