### ISSUE TITLE
Pkg.add("IJulia") issue in Julia 0.4.6

### ISSUE THREAD

**Issue by hnagib** [JuliaLang/julia#17535]
Getting the following error when trying to install IJulia:

![image](https://cloud.githubusercontent.com/assets/13231362/17031387/c79d4578-4f28-11e6-9e5f-f1f0621aaa64.png)

Any help would be much appreciated! Thanks.

**Comment by tkelman** [comment]
Is H a network drive? Are you able to run that git command outside of Julia? If you don't have git installed locally, look inside your Julia installation under Git and run git-bash.exe.

**Comment by hnagib** [comment]
Yup, it is a network drive. I can run git from command prompt. I also tried running git-bash.exe
Still no luck unfortunately.

**Comment by tkelman** [comment]
So the command also errors outside of Julia? In that case it sounds like a configuration problem. You could try setting `ENV["JULIA_PKGDIR"]` to a local-drive location and see if that makes any difference.

**Comment by KristofferC** [comment]
Since we now use `libgit2` this issue seems obsolete.
