### ISSUE TITLE
Feature request: `type_name` just like `function_name`

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#17555]
Would it be possible / make sense to get a `type_name` function that works just like the `function_name` one but for types? E.g.

```julia
module foo

type bar
end

bar2 = bar

println(type_name(bar))
println(type_name(foo.bar))
println(type_name(bar2)) 
# all three statements print "bar"

end
```

**Comment by tkelman** [comment]
`string(bar.name)` ?

**Comment by helgee** [comment]
That does not work as @marius311 intended because it will always return the fully qualified name, e.g. `foo.bar` in this case.

**Comment by helgee** [comment]
It never occured to me to search for a`name` within a `name` 😂 

But I think this should be documented either explicity or implicitly by just adding the function:
```julia
type_name(dt::DataType) = dt.name.name
```
`function_name` is a one-liner as well:
```julia
function_name(f::Function) = typeof(f).name.mt.name
```

**Comment by tkelman** [comment]
`function_name` is apparently documented but not exported, and doesn't look like it's used in base at all. What's the use case for this and `type_name` ? Having it unexported initially would be fine I guess, just curious.

**Comment by helgee** [comment]
In Astrodynamics.jl I use a lot of abstract types as type parameters, e.g. for time scales. They all print as `Astrodynamics.TYPE`. Since I want my epochs to print as `TIMESTAMP SCALE` and not `TIMESTAMP Astrodynamics.SCALE` this became a problem.
I solved it like this
```julia
scales = (:TT, :TDB, :TCB, :TCG, :TAI, :UTC, :UT1)
for scale in scales
    name = string(scale)
    @eval begin
        #= other stuff =#
        show(io::IO, ::Type{$scale}) = print(io, $name)
    end
end
```
because I did not find the `name.name`.

**Comment by JeffreySarnoff** [comment]
:ok_hand: &nbsp; ⟦ when the arg is a type aor function and nameof(that) is needed... _yes; that happens._.  ⟧
```julia
type_name(dt::DataType) = dt.name.name
function_name(f::Function) = typeof(f).name.mt.name
```
I feel this deserves to be generally available in the developer docs, reflective-ness assistance functions.
