### ISSUE TITLE
Document IOContext keys & values

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#17556]
As far as I can tell, IOContext is documented in these places:
- http://docs.julialang.org/en/latest/stdlib/io-network/?highlight=iocontext
- http://docs.julialang.org/en/latest/manual/networking-and-streams/?highlight=iocontext#io-output-contextual-properties

This doesn't seem like enough information to guide folks in how to use it; I just grep `base/` every time I need to remind myself, but we probably don't want to encourage that. At a bare minimum, it seems that `:limit`, `:limit_output`, `:compact`, and `:multiline` should be clearly described.

**Comment by tkelman** [comment]
x-ref #17545 which is adding a bit but not quite enough for this to be complete IMO

**Comment by JeffBezanson** [comment]
Dup of #16763.
