### ISSUE TITLE
Windows password prompt leaves password in memory

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#17560]
As I commented in #17506, the `Base.winprompt` function (used for password prompts by libgit2 on Windows) leaves several copies of the user's plaintext password in memory.   This seems undesirable from a security point of view.

cc @Keno

**Comment by Keno** [comment]
Should we have a `SensitiveData` type makes sure to zero itself when no longer needed?

**Comment by StefanKarpinski** [comment]
A `SensitiveData` type seems like a good way to go. The finalizer would then zero out the memory.

**Comment by stevengj** [comment]
I don't know, I think you want to zero the memory as soon as possible, not just wait for the finalizer.

Furthermore, the real problem here is not just that we aren't zeroing the memory, but that we are making multiple copies (3+ copies) in memory by incautious array manipulation.

I doubt there is much substitute for careful line-by-line attention to detail with this sort of thing.

**Comment by eschnett** [comment]
One typically does not want to wait for gc to kick in to have the password deleted; an explicit function to do so would be better.

**Comment by Keno** [comment]
We're caching this password for the duration of Pkg.update. I'm somewhat worried that passing this through all sorts of generic array/dict code will make extra copies that we don't know about, which is why I think a separate `SensitiveData` would be good.

**Comment by tkelman** [comment]
can we do something straightforward about this specific case now, and come up with a more general solution later while we're not in a rush?

**Comment by stevengj** [comment]
I implemented the obvious thing in #17579.

**Comment by StefanKarpinski** [comment]
Closed by https://github.com/JuliaLang/julia/commit/aa7acffa63a6c8c551c4ba75d001d6458891677c.
