### ISSUE TITLE
Julia Win32 crashes immediately after an error

### ISSUE THREAD

**Issue by s-broda** [JuliaLang/julia#17561]
Julia crashes whenever it wants to throw an error on the latest win32 nightly build on Windows 10 . For example, just starting Julia and entering 'k < enter >', I get this:

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x654a0d15 -- jl_gc_pool_alloc at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\gc.c:809
while loading no file, in expression starting on line 0
jl_gc_pool_alloc at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\gc.c:808
eval_user_input at .\REPL.jl:57
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\julia_internal.h:177 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\gf.c:2034
macro expansion at .\REPL.jl:92 [inlined]
#3 at .\event.jl:46
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\julia_internal.h:177 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\gf.c:2034
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\julia.h:1394 [inlined]
start_task at /home/Administrator/buildbot/slave/package_win6_2-x86/build/src/home/Administrator/buildbot/slave/package_win6_2-x86/build/src\task.c:253
wmain at /home/Administrator/buildbot/slave/package_win6_2-x86/build/ui\repl.c:232
Allocations: 1034590 (Pool: 1033848; Big: 742); GC: 0

Julia 0.4.6 works fine. I don't know when this error appeared, as I've only been using the win64 version so far. This happens on two machines, one running 32bit Windows 10, the other the 64bit version.

versioninfo()
Julia Version 0.5.0-pre+5609
Commit 21f28c9 (2016-07-22 07:00 UTC)
Platform Info:
  System: NT (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by JeffBezanson** [comment]
I also got this on linux; most likely #17288. Might be fixed by #17543.

**Comment by yuyichao** [comment]
Tentatively close as dup of #17288 . Please comment for reopening if this is still happening in the next nightly (or whatever version after `0.5.0-pre+5620`)
