### ISSUE TITLE
The two implementations of slicedim have different behavior

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#17589]
Ref. https://github.com/timholy/Images.jl/issues/513.

Which one do we want to keep? From the docstring (if we take that as defining the behavior we want), the abstractarray version is correct and the array one is not. Should we just delete the specialized implementation for arrays?

**Comment by timholy** [comment]
A little more digging:
```jl
julia> A = rand(100,100,100);

julia> foo(A::AbstractArray, d::Integer, i) =
           A[[ n==d ? i : (indices(A,n)) for n in 1:ndims(A) ]...]
foo (generic function with 1 method)

julia> @time foo(A, 2, 5);
  0.000247 seconds (24 allocations: 79.172 KB)

julia> @time slicedim(A, 2, 5);
  0.002900 seconds (39.91 k allocations: 861.359 KB)
```
So the one specialized for arrays is more complicated, 10x slower, and less consistent with the docstring. Seems like a no-brainer to me, I'll just nuke it.

**Comment by StefanKarpinski** [comment]
💣 🍄 ☁️
