### ISSUE TITLE
Scope issue with @static

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#17584]
I'm seeing some weird interaction between `cglobal` and `immutable` inside `@static`.

These two are okay
```jl
module A
    @static if true
        const B = cglobal((:ompi_mpi_wchar, :libmpi))
    end
end

module A
    @static if true
        immutable T end
        const B = :B
    end
end
```
but
```jl
julia> module A
    @static if true
        immutable T end
        const B = cglobal((:ompi_mpi_wchar, :libmpi))
    end
end
WARNING: replacing module A
ERROR: error compiling anonymous: type definition not allowed inside a local scope
```
```jl
julia> versioninfo()
Julia Version 0.5.0-pre+5651
Commit 17c34e7* (2016-07-23 19:42 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/2586

**Comment by andreasnoack** [comment]
@yuyichao Why is `cglobal` triggering the issue?

**Comment by vtjnash** [comment]
The at-static here is redundant and unnecessary (actually, it's pretty rare to need it)

**Comment by yuyichao** [comment]
> Why is `cglobal` triggering the issue?

It's an intrinsic

**Comment by andreasnoack** [comment]
@vtjnash I think I have to use `@static`. The example here was just the smallest possible. In the real use case, I have to construct immutables to match C structs depending on which MPI implementation is linked. It's true that I can make the definitions with `cglobal` without the `@static` but then I need to repeat the same condition twice - once with `@static` and once without. Naively, I would expect that
```jl
module A
    @static if true
        immutable T end
        const B = cglobal((:ompi_mpi_wchar, :libmpi))
    end
end
```
and
```jl
module A
    immutable T end
    const B = cglobal((:ompi_mpi_wchar, :libmpi))
end
```
would be equivalent. Wouldn't that be desirable?

**Comment by vtjnash** [comment]
Sure, but note that the definition of `@static` is simply "evaluates the conditional at the toplevel scope", which is redundant where you are also evaluating the `@static` at the toplevel scope.

**Comment by yuyichao** [comment]
> Wouldn't that be desirable?

Yes. But more fundamentally a `@static` block is equivalent to a normal block and you can reproduce the same bug with a normal block i.e. `begin ... end`. In any case, #2586 should clearly be fixed and this has nothing to do with `@static` at all.
