### ISSUE TITLE
Adding fma! and muladd! for Arrays (or can we specialize broadcast)?

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#17593]
Defining a `fma!(dest, x, y, z), ` and `muladd!(dest, x, y, z)` for arrays would give the casual user a very common operation (with an optimized internal implementation). It would also allow hardware-accelerated libraries (e.g. ArrayFire) to provide even more optimized versions. It would probably be good to explicitly allow `dest` to be the same as z.

There is `Base.LinAlg.axpy!`, but that's really BLAS-only (and may also not be an obvious choice for the casual user). Of course a `Base.muladd!` could use it (e.g. if the array is large).

Or could we provide specialized versions of `map!` or `broadcast!` with Julia v0.5, now that functions have individual types? Like

    Base.broadcast!(::typeof(muladd), ...) = ...

or so? That would of course be more elegant and generic than a `Base.muladd!`.

**Comment by oschulz** [comment]
This seems to work (with Julia 0.5):

    function broadcast!(::typeof(muladd), dest, x::Number, y::AbstractArray, z::AbstractArray)
        if is(dest, z)
            info("Using Base.LinAlg.axpy!")
            Base.LinAlg.axpy!(x, y, z)
            # Probably better avoid call to BLAS for small arrays, though ...
        else
            error("ToDo: Implementation for dest != z")
        end
    end

The argument types must be chosen carefully though, to avoid ambiguity with the standard `Base.broadcast`.

**Comment by yuyichao** [comment]
I don't think we need this if this is just element since we are going with broadcasting at syntax level instead of defining elementwise/broadcasting version for every single functions. This should be irrelevant with packages that want to provide with a faster version since those can (and should) be done explicitly and it's a really bad idea to override base functions like this especially since multiple packages can then fight for who got the last override in.

**Comment by oschulz** [comment]
> it's a really bad idea to override base functions like this especially since multiple packages can then fight for who got the last override in.

@yuyichao: I was thinking about packages like ArrayFire.jl. As it uses it's own type (`AFArray`), there should be no conflict with optimized versions of other packages (when specializing Base functions), right? From what I understood, one of the neat things about packages in the style of ArrayFire is the fact that (for most things) it *does* use the generic function name - and so fairly generic user code that only assume `AbstractArray` can run on `AFArray` without change.

**Comment by yuyichao** [comment]
And in such case there's no need to extend a base functions either.

**Comment by oschulz** [comment]
> And in such case there's no need to extend a base functions either.

Then how can a library like ArrayFire automatically optimize things like `broadcast(muladd, ...)` - without offering a specialized version for `AFArray`? Anyhow, as this seems to be possible with 0.5 without a need for `muladd!`, etc. I'm closing this.

**Comment by yuyichao** [comment]
Just to note that you shouldn't use the broadcast syntax for this since you will not be able to handle anonymous functions. Just define a `fma!` or `muladd!` yourself and it's much better than patching a base function.

**Comment by oschulz** [comment]
> [...] since you will not be able to handle anonymous functions. Just define a fma! or muladd! yourself and it's much better than patching a base function.

Uh, I think we're talking about different things, here. I wasn't going for anonymous functions, I was going for a very specific case, and for using multiple dispatch to use the same code for different array types (e.g. standard and accelerated) - as transparent to the (casual) user as possible.

**Comment by yuyichao** [comment]
You will get anonymous functions due to fusion.

**Comment by oschulz** [comment]
> You will get anonymous functions due to fusion.

@yuyichao Ah, right, thanks - I didn't think that far, that's a 0.6 feature, right? I was thinking about plain simple direct calls to `broadbast!`. :-)

**Comment by yuyichao** [comment]
It's a master feature. And in any case I don't think writing `broadcast!(muladd, a, x, y, z)` is much better than `ArrayFire.muladd!(a, x, y, z)`

**Comment by oschulz** [comment]
> It's a master feature.

So it could make it into 0.5? That would be fantastic ...

> And in any case I don't think writing broadcast!(muladd, a, x, y, z) is much better than ArrayFire.muladd!(a, x, y, z)

Well, the difference is that in the first case, the code will be generic and work with both normal and AF arrays (I was just using ArrayFire as an example, though), while in the second case it would be AF-specific. But anyhow, there is obviously no need to have something like `muladd!` in Base anymore, and package writer can choose if they want special function names or not.

**Comment by stevengj** [comment]
@oschulz, broadcasting/fusion of dotted binary operations (`.*` etc) will almost certainly *not* be in 0.5.  However, broadcasting/fusion of dotted function calls `f.(args...)` will be in 0.5.

**Comment by oschulz** [comment]
@stevengj, thanks for the information. Well, even limited fusion in 0.5 is already pretty awesome!
