### ISSUE TITLE
keyword arguments are not part of the function signature

### ISSUE THREAD

**Issue by randomizedthinking** [JuliaLang/julia#17596]
Not sure whether this is by design or something can be improved upon.

    myfunc(; x::Int64=1) = x + 1
    myfunc(; y::Int64=1) = y + 1

Below are the results of calling these functions.

    julia> myfunc(x=1);
    ERROR: unrecognized keyword argument "x"
    julia> myfunc(y=2);

The second definition of `myfunc` overrides the first one given that keyword arguments are not part of the function signature. It implies we can define generic functions with different keyword arguments.

The question is whether it is by design, or is there any way to achieve the similar effect?

**Comment by yuyichao** [comment]
This is by design, documented (kwargs doesn't participate in dispatch) and raise a warning on 0.5.

**Comment by JeffBezanson** [comment]
See #16580 for some work & discussion towards handling keyword args more like positional args.
