### ISSUE TITLE
Multiple regressions in last daily bencmark

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#17600]
Noticed by @Sacha0 https://github.com/JuliaLang/julia/commit/5fe9e5342b06ef0cec58e67b9f7e4e82a9f0a860#commitcomment-18371997

Report: https://github.com/JuliaCI/BaseBenchmarkReports/blob/049d3920f3b933d4a84f9739407cd870cbbbb7df/daily_2016_7_22/report.md

**Comment by JeffBezanson** [comment]
For the big SIMD regression, bisect points to 0d931fc2a153d525297b5fa7e698294935bd57aa.

**Comment by JeffBezanson** [comment]
This seems to be due to a subtle inlining heuristic problem due to the lowering of return type declarations. I'll cook something up.

**Comment by KristofferC** [comment]
Benchmark report for https://github.com/JuliaLang/julia/commit/0d931fc2a153d525297b5fa7e698294935bd57aa reverted: https://github.com/JuliaCI/BaseBenchmarkReports/blob/449375a2d193570b02ae0ef66b146d2d034bd87d/6bcb99c_vs_8f99882/report.md

**Comment by JeffBezanson** [comment]
The "array" regressions seem to be a separate issue from the simd regressions. I'm finishing up a bisect now.

**Comment by JeffBezanson** [comment]
Testing the following:

```
run(BaseBenchmarks.SUITE[["array","index",("sumrange","Array{Int32,2}")]])
```

bisect points to c9b5d9db7c21ea2334f3be3af2832dc32f8227ab @yuyichao .

Before:

```
BenchmarkTools.Trial: 
  samples:          2702
  evals/sample:     1
  time tolerance:   40.00%
  memory tolerance: 1.00%
  memory estimate:  1.06 mb
  allocs estimate:  1500
  minimum time:     266.79 μs (0.00% GC)
  median time:      280.32 μs (0.00% GC)
  mean time:        368.58 μs (23.00% GC)
  maximum time:     3.15 ms (85.50% GC)
```

after:

```
BenchmarkTools.Trial: 
  samples:          1836
  evals/sample:     1
  time tolerance:   40.00%
  memory tolerance: 1.00%
  memory estimate:  1.06 mb
  allocs estimate:  1500
  minimum time:     416.23 μs (0.00% GC)
  median time:      458.56 μs (0.00% GC)
  mean time:        542.23 μs (15.56% GC)
  maximum time:     3.11 ms (80.70% GC)
```

**Comment by JeffBezanson** [comment]
Narrowed down to:

```
julia> a=rand(Int32,500,500); r= 1:500;

julia> @code_native Base._unsafe_getindex(Base.linearindexing(a), a, r, 1)
```
