### ISSUE TITLE
undocumented 1 argument write

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#17612]
There is a 1 argument `write` in both 0.4.6 and 0.5.0 that is not described in the docstring or in the online documentation.

**Comment by JeffBezanson** [comment]
Not clear that this is necessary actually; I'm not sure it's even a good idea to have a shortcut for writing binary data to STDOUT.

**Comment by StefanKarpinski** [comment]
I agree. Not having a default output stream seems like a key difference between `print` and `write`.

**Comment by ggggggggg** [comment]
There are still multiple single argument write methods in 0.7.0-DEV.3096, which result from methods which have a splatted 2nd argument.
```
julia> methods(write,Tuple{Any})
# 3 methods for generic function "write":
[1] write(filename::AbstractString, args...) in Base at io.jl:275
[2] write(io::IO, xs...) in Base at io.jl:488
```
The first of these causes `write("a")` to create a file called "a" in the current directory, which seems undesirable.

Perhaps we should define something like:
```
Base.write(::AbstractString) = error("write requires two arguments")
Base.write(::IO) = error("write requires two arguments")
```

**Comment by StefanKarpinski** [comment]
Probably a good idea to fix. Also unlikely that fixing them will cause anyone grief, but still...

**Comment by JeffBezanson** [comment]
Good catch. I think the first one should get an extra argument:

```
write(filename::AbstractString, a1, args...) = open(io->write(io, a1, args...), filename, "w")
```

The second one could too, but we also might want to just deprecate vararg `write` (which just loops over the arguments and calls `write` on all of them).
