### ISSUE TITLE
Consider adding BigFloat support for randn/randexp

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#17629]
https://github.com/JuliaLang/julia/pull/17627 adds MethodError domain checks that you cannot call `randn` or `randexp` for any types besides the currently supported `Float16,Float32,Float64`.

Do we also want to extend support to `BigFloat`? I don't know much about, but I've left TODO code comments in https://github.com/JuliaLang/julia/pull/17627#issuecomment-235198088 asking to consider this question.

This is a tracking issue for that discussion.

**Comment by tkelman** [comment]
x-ref #13950

**Comment by ViralBShah** [comment]
I wonder what bits of the Marsaglia and Tsang paper need to be reworked to do this right.

**Comment by dpsanders** [comment]
cf http://randomlib.sourceforge.net/html/index.html, which has an MIT/X11 license.

**Comment by dpsanders** [comment]
Also http://exrandom.sourceforge.net/ 
and the paper  http://arxiv.org/abs/1303.6257

**Comment by Keno** [comment]
Looks like MPFR implements the cited paper: https://gforge.inria.fr/scm/browser.php?group_id=136? Any reason we don't just hook this up?

**Comment by StefanKarpinski** [comment]
Seems like a good project for someone to tackle!

**Comment by rfourquet** [comment]
> Any reason we don't just hook this up?

I guess this would be easy, but AFAIU, MPFR doesn't allow to pass our own random RNGs. So if we want to do this, we should IMHO first wrap GMP RNG into a proper Julia type, and then provide only `randn(::GMP_RNG, ...)`.

**Comment by StefanKarpinski** [comment]
Or patch GMP to allow arbitrary RNGs—that might not be so hard and I bet they'd accept a patch.

**Comment by chriscoey** [comment]
bump! this is sorely missing. anyone looking for a project could try this.

**Comment by rfourquet** [comment]
> AFAIU, MPFR doesn't allow to pass our own random RNGs

Actually I was wrong (unless this changed recently), you can pass your RNG, albeit in a quite involved way.
