### ISSUE TITLE
Julia 0.4 .tgz install on Ubuntu won't start

### ISSUE THREAD

**Issue by dwschulze** [JuliaLang/julia#17639]
I extracted the files from the .tgz and added it installation directory to the path.  When I start with "julia" I get:

$ julia
ERROR: system image file "/home/dschulze/bin/julia-2e358ce975/../lib/julia/sys.so" not found
$ which julia
/home/dschulze/bin/julia-2e358ce975/bin/julia

**Comment by tkelman** [comment]
did you set a `JULIA_HOME` environment variable?
```
$ echo $JULIA_HOME
```
if so, don't do that, that environment variable is meaningful for the julia runtime

**Comment by andreasnoack** [comment]
Please comment if this is still an issue.
