### ISSUE TITLE
Replacement for Base.length (due to custom-indexed arrays)?

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#17631]
Due to the new custom-indexed arrays, it's now [recommended](http://docs.julialang.org/en/latest/devdocs/offset-arrays/) to use `length(linearindices(A))` instead of `length(A)`, so that old code using `1:length(A)` doesn't result in disaster with a custom-indexed array.

So in a sense, we're kinda deprecating `Base.length`. Not explicitly, but as the recommendation is to not support it for custom-indexed arrays, we can't use `Base.length` in generic code any longer. After all, the author of a function may not know if someone else might want to use it with a custom-indexed array.

As, `length(linearindices(A))` is *very* unwieldy, I think we should provide a standard replacement for `Base.length`, like `Base.len` or so. E.g.:

    Base.len(A) = length(linearindices(A))

While `length` shouldn't be used for iteration any longer, functions/algorithms will still often need to get the length of an array (e.g. for normalization, etc.). If there's no "official" replacement for `length` in Base, I suspect that many packages will add their own internal version of it at some point (which would get very confusing). Also, if there's no short replacement, people might get tempted to continue using length() out of laziness  - resulting in code that fails for the new arrays.

Another question is how to handle non-array containers - I guess many custom container types provide a `length` method. However, I suspect few of them currently provide `linearindices`. But we should be able to use a standard generic length function (whatever it's name) for all types of containers.

See also [this discussion](https://groups.google.com/d/msg/julia-users/BEiYJX3RGnE/4KJfaCdeCAAJ).

**Comment by EricForgy** [comment]
I haven't played around with v0.5, but I am a little confused.

What would the types of `A` and `linearindices(A)` be and why couldn't this be done in Base with dispatch (assuming the two types are different?

For example,

~~~julia
julia> typeof(A)
NewArrayType

julia> typeof(linearindices(A))
NewLinearIndexType

Base.length(I::NewLinearIndexType) = whatever
Base.length(A::NewArrayType) = Base.length(linearindices(A))
~~~

I don't see the need for a new `Base.len` when we could just use dispatch for `Base.length`. 

I'm probably confused :sweat_smile:

**Comment by timholy** [comment]
It's because there might be code out there in the wild written like this:
```jl
function broken(v::AbstractVector)
    s = zero(eltype(v))
    for i = 1:length(v)
        s += v[i]
    end
    s
end
```

It should be pointed out, though, that throwing an error with `length` is almost always going to be redundant with "don't remove bounds checks on arrays with custom indexing". So we could live slightly more dangerously and just re-enable `length`.

**Comment by EricForgy** [comment]
Hi Tim :wave:

I'd vote for just living dangerously :smile:

**Comment by JeffBezanson** [comment]
`length` is not going to be removed, and will continue to mean the number of elements in a collection. As @timholy said, the plan is to eventually re-enable `length` on flexible arrays, when we have some more experience around the recommended use of them.

**Comment by tkelman** [comment]
If you aren't iterating from `1:length(v)` but rather a smaller subset, then you could silently get wrong results even with bounds checking enabled. I say verbosity is an acceptable price to pay for the unconventional arrays until we have a more systematic way of auditing code.

**Comment by oschulz** [comment]
Ah, right - sorry, I didn't know it was planned to eventually re-enable `length` on custom-indexed arrays. In that case, I can live with some verbosity for a while.

Until then, it may be difficult though to write generic code that gets the length of standard arrays, custom-indexed array and non-array containers, right? How would I do this - is there an easy way?

Anyhow, I'd be fine with closing this issue.

**Comment by timholy** [comment]
```
module MyPackage

_length(A::AbstractArray) = length(linearindices(A))
```
and then someday search/replace `_length`->`length`. It's shorter than `@compat` :smile:.
