### ISSUE TITLE
Behaviour of $ when printing a field of a custom type.

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#17647]
Consider the following example:

julia> type test
       a
       b
       c
       end

julia> t = test(1.0,2.0,3.0)
test(1.0,2.0,3.0)

I want to show a specific field of my type in an error message, for example.

--- First try (I think most users would try this at first)

julia> error(" $t.c ")
ERROR:  test(1.0,2.0,3.0).c  --> It shows the whole type.
 in error at error.jl:21

--- Working code.

julia> error(" $(t.c) ")
ERROR:  3.0
 in error at error.jl:21

I could not find any clue in the documentation about the use of () in order to show a specific field,  although it makes sense. It the type has lots of information, like large arrays, the error message is quite large to be useful. 

My question:  is this the expected behaviour or $test.c should resolve the field without using () ? As I undestand, one can use $variable with a string that should contain a dot rigth after the string interpolation, so the parser cannot diferentiate both situations. I just think that one shoud point it in the docs.

By the other side, it (should be/is)  possible to the parser to realize if $type is intended to show the whole type and $type.field should print the field ?

Thanks.

**Comment by MichaelHatherly** [comment]
http://docs.julialang.org/en/release-0.4/manual/strings/#interpolation

In particular the paragraph:

> The shortest complete expression after the $ is taken as the expression whose value is to be interpolated into the string. Thus, you can interpolate any expression into a string using parentheses:

describes how interpolation is handled.

**Comment by CodeLenz** [comment]
Thanks @MichaelHatherly. I miss it completely !
Time to make more coffe.
