### ISSUE TITLE
Tests don't ignore .juliarc.jl

### ISSUE THREAD

**Issue by rsrock** [JuliaLang/julia#17642]
On master, I have the following error show up with `make test`, and the tests hang.  If I move my .juliarc.jl out of the way, the tests pass as expected.

I believe there are a number of places in the tests that the `--startup-file=no` option is missing.  I have found many of them, which allows those tests to proceed, but some are still having issues. If I manage to figure it out, I'll set up a PR.

```
ERROR: LoadError: `@osx` is deprecated, use `@static is_apple()` instead
 in include_from_node1(::String) at ./loading.jl:426
 in try_include at ./client.jl:200 [inlined]
 in load_juliarc() at ./client.jl:278
 in process_options(::Base.JLOptions) at ./client.jl:216
 in _start() at ./client.jl:318
while loading /Users/rrock/.juliarc.jl, in expression starting on line 6
```

**Comment by kshyatt** [comment]
>If I manage to figure it out, I'll set up a PR.

💯 

Could you post the `.juliarc` file, by any chance? It might be helpful.

**Comment by vtjnash** [comment]
I think just putting 'error("don't include me")' in it would work (and we could add that to the CI setup)
