### ISSUE TITLE
make fails with segfault in inference.ji on version 0.5

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#17645]
In last 24 hours there have been a number of changes resulting from a git pull including an llvm recompile. Yesterday make and make testall ran fine, but this morning make is failing:
```
> make
    JULIA usr/lib/julia/inference.ji
/bin/sh: line 1: 21656 Segmentation fault      /home/colin/Downloads/julia/usr/bin/julia -C native --output-ji /home/colin/Downloads/julia/usr/lib/julia/inference.ji --startup-file=no coreimg.jl
Makefile:215: recipe for target '/home/colin/Downloads/julia/usr/lib/julia/inference.ji' failed
make[1]: *** [/home/colin/Downloads/julia/usr/lib/julia/inference.ji] Error 139
Makefile:96: recipe for target 'julia-inference' failed
make: *** [julia-inference] Error 2
```
If this is not enough info, I can provide the entire output but it is quite long.

**Comment by yuyichao** [comment]
Do you see warnings about `_MSC_VER` during llvm re-compilation?

**Comment by colbec** [comment]
@yuyichao Yes, 80 instances in the entire output beginning with:
```
In file included from /home/colin/Downloads/julia/usr/include/llvm/ADT/SmallVector.h:20:0,
                 from /home/colin/Downloads/julia/usr/include/llvm/ADT/ArrayRef.h:14,
                 from /home/colin/Downloads/julia/src/APInt-C.cpp:4:
/home/colin/Downloads/julia/usr/include/llvm/Support/MathExtras.h:74:7: warning: "_MSC_VER" is not defined [-Wundef]
 #elif _MSC_VER
       ^
/home/colin/Downloads/julia/usr/include/llvm/Support/MathExtras.h:90:7: warning: "_MSC_VER" is not defined [-Wundef]
 #elif _MSC_VER
       ^
/home/colin/Downloads/julia/usr/include/llvm/Support/MathExtras.h:143:7: warning: "_MSC_VER" is not defined [-Wundef]
 #elif _MSC_VER
       ^
/home/colin/Downloads/julia/usr/include/llvm/Support/MathExtras.h:159:7: warning: "_MSC_VER" is not defined [-Wundef]
 #elif _MSC_VER
```
......

**Comment by yuyichao** [comment]
I believe Jeff have seen the same. `make -C deps distclean-llvm` might fix it.

Both https://github.com/JuliaLang/julia/pull/17592 and https://github.com/JuliaLang/julia/commit/c31c5f69955644f0c5d9ff6f41c33c5751f6ef77 falls in the right time frame so @tkelman

**Comment by colbec** [comment]
As suggested, `make -C deps distclean-llvm fixes`. Thanks.

**Comment by goldfita** [comment]
Were these issues resolved?  I'm failing on the same line on v0.6-rc2 (Win 7, Intel Xeon CPU E5-1620).  I will try it on a newer machine at some point.  A fresh clone of git and 'make -C deps distclean-llvm' does not fix the problem.

I attempted to build with MKL and ran into the following.

`LLVM ERROR: Program used external function 'fmaf' which could not be resolved!`

<pre>XC_HOST = x86_64-w64-mingw32
USE_GPL_LIBS = 0
MARCH = native
USEICC = 0
USEIFC = 0
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
USE_INTEL_LIBM = 1</pre>


So I tried LLVM 4, but it fails sooner in the build.

`/bin/sh: line 1: 489268 Segmentation fault      /home/goldfing/tmp/julia/usr/bin/julia.exe -C native --outpu                                                                                                t-ji `cygpath -w /home/goldfing/tmp/julia/usr/lib/julia/inference.ji` --startup-file=no -g0 -O0 coreimg.jl
make[1]: *** [Makefile:214: /home/goldfing/tmp/julia/usr/lib/julia/inference.ji] Error 139
make: *** [Makefile:100: julia-inference] Error 2
`

<pre>XC_HOST = x86_64-w64-mingw32
LLVM_VER = 4.0.0
USE_GPL_LIBS = 0
MARCH = native (or x86-64)</pre>

**Comment by vtjnash** [comment]
Looks like you're missing libopenlibm

**Comment by goldfita** [comment]
Does setting USE_INTEL_LIBM replace libopenlibm?  I tried it without success setting only MKL_FFT=1 but I can't remember now if it was on a fresh git clone.
