### ISSUE TITLE
Installs unneeded headers to <prefix>/include/julia?

### ISSUE THREAD

**Issue by petercolberg** [JuliaLang/julia#17657]
In the process of packaging julia/0.5.0~rc0 for Debian, I noticed that the runtime library and headers are now installed system-wide for use by other programs. This is a list of headers currently installed here:

```
/usr/include/julia/END.h
/usr/include/julia/ENTRY.amd64.h
/usr/include/julia/ENTRY.i387.h
/usr/include/julia/MurmurHash3.h
/usr/include/julia/arraylist.h
/usr/include/julia/bitvector.h
/usr/include/julia/dirpath.h
/usr/include/julia/dtypes.h
/usr/include/julia/hashing.h
/usr/include/julia/htable.h
/usr/include/julia/ios.h
/usr/include/julia/julia.h
/usr/include/julia/julia_threads.h
/usr/include/julia/julia_version.h
/usr/include/julia/libsupport.h
/usr/include/julia/platform.h
/usr/include/julia/ptrhash.h
/usr/include/julia/strtod.h
/usr/include/julia/timefuncs.h
/usr/include/julia/tzfile.h
/usr/include/julia/utf8.h
/usr/include/julia/utils.h
/usr/include/julia/uv-errno.h
/usr/include/julia/uv-linux.h
/usr/include/julia/uv-threadpool.h
/usr/include/julia/uv-unix.h
/usr/include/julia/uv-version.h
/usr/include/julia/uv.h
```

Did you verify that all of these headers are in fact needed to link to libjulia.so?

**Comment by tkelman** [comment]
Most, but not all, of those are likely needed for embedding. What headers were being installed before?

**Comment by petercolberg** [comment]
With v0.4, no headers were installed, since libjulia was installed in julia’s private libdir. With v0.5, libjulia is installed in the system-wide libdir, so we will also ship the headers; ideally only those declaring functions that are exported for public use in `libjulia.so`.

**Comment by tkelman** [comment]
> no headers were installed

`make install` installs them. Was the debian packaging removing them? So you couldn't actually use libjulia from debian for embedding?

**Comment by petercolberg** [comment]
Correct, previously the headers were not packaged. Since I am not yet familiar with the libjulia API, it would be helpful if someone who is familiar could (as part of preparing for the 0.5.0 release) go over the list of headers installed with `make install` and check whether they actually refer to public symbols in libjulia.so.

**Comment by tkelman** [comment]
Try https://github.com/JuliaLang/julia/blob/master/doc/manual/embedding.rst as a start. `julia.h` defines the public interface, but also includes many of the rest of these. Anything that `julia.h` doesn't recursively include can probably be taken out of `make install`.

**Comment by petercolberg** [comment]
This is the list of required headers:
```
# cpp -M -I/usr/include/julia -include julia.h /dev/null | grep -o '/usr/include/julia/[^ ]*' | sort
/usr/include/julia/arraylist.h
/usr/include/julia/bitvector.h
/usr/include/julia/dirpath.h
/usr/include/julia/dtypes.h
/usr/include/julia/hashing.h
/usr/include/julia/htable.h
/usr/include/julia/ios.h
/usr/include/julia/julia.h
/usr/include/julia/julia_threads.h
/usr/include/julia/julia_version.h
/usr/include/julia/libsupport.h
/usr/include/julia/platform.h
/usr/include/julia/ptrhash.h
/usr/include/julia/strtod.h
/usr/include/julia/timefuncs.h
/usr/include/julia/utf8.h
/usr/include/julia/utils.h
/usr/include/julia/uv-errno.h
/usr/include/julia/uv-linux.h
/usr/include/julia/uv-threadpool.h
/usr/include/julia/uv-unix.h
/usr/include/julia/uv-version.h
/usr/include/julia/uv.h
```

**Comment by tkelman** [comment]
looks like we can be a little more selective about `src/support/*.h` here then https://github.com/JuliaLang/julia/blob/e717ded47a55d3526a10207d8d75ae5c9ab9646f/Makefile#L375

**Comment by ViralBShah** [comment]
This has all been considerably cleaned up.
