### ISSUE TITLE
Please install stdlib to versioned path

### ISSUE THREAD

**Issue by petercolberg** [JuliaLang/julia#17666]
Julia 0.5 will ship with a versioned `libjulia.so.0.5` that is installed system-wide for embedding by other programs. The standard library however is still installed to an unversioned path, which is inconsistent and creates a conflict when different versions of `libjulia.so.$(SOMAJOR)` are installed on a system, since these will depend on different versions of the standard library.

Therefore `base`  and `test` should be installed to a versioned path `$(prefix)/share/julia/$(SOMAJOR)`.

Likewise, `juliarc.jl` should be installed to `$(prefix)/etc/julia/$(SOMAJOR)`.

This also affects the private libdir, `$(prefix)/lib/$(MULTIARCH)/julia/$(SOMAJOR)`.

**Comment by stevengj** [comment]
Note that this is actually a duplicate of #2295 (see the third, unfinished bullet item).  I agree that it needs to be fixed.

**Comment by stevengj** [comment]
On second thought, maybe we should leave this open and close #2295, since this is now a more specific issue and is uncluttered with the discussion in #2295.

**Comment by stevengj** [comment]
Ping @tkelman on this.

**Comment by tkelman** [comment]
there was a PR that needs revisiting, we decided to hold off on likely breaking a bunch of scripts for 0.5 but should fix this for 0.6

**Comment by User-764Q** [comment]
The linked request has been closed and the contents of my folder is 
julia/environments folder includes directories v1.5 and v1.6 so I think this issue can be safely closed. 

Matt.

**Comment by ViralBShah** [comment]
We pretty much install each version of julia in its own directory now, and these are nicely managed by `juliaup`. The stdlibs are also installed on a versioned path now.

**Comment by stevengj** [comment]
Sounds like this can be closed, then.
