### ISSUE TITLE
Add relational algebra unicode characters

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaLang/julia#17677]
Thank you @JeffBezanson, the unicode extensions you added in resolving #6929 are great. Could [relational algebra](https://en.wikipedia.org/wiki/Relational_algebra) operators be added as well?

* [left](http://www.fileformat.info/info/unicode/char/27d5/index.htm)
* [right](http://www.fileformat.info/info/unicode/char/27d6/index.htm)
* [outer](http://www.fileformat.info/info/unicode/char/27d7/index.htm)
* [inner](http://www.fileformat.info/info/unicode/char/2a1d/index.htm)

I'm working on a tensor join package that will eventual use hash join/dictionaries for synchronized index iteration, and I would like to use the appropriate standard symbols to represent the joins.

**Comment by JeffBezanson** [comment]
I believe these were added in #8036
