### ISSUE TITLE
Adjust LLVM_OBJ_SOURCE

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#17671]
`libLLVMCodeGen.a` gets created about halfway through the build process. With CMake, `make install` does not retry to create any libraries that are missing, so interrupting the build after that library gets created but before the rest of the build is complete, will basically leave our build in an unrecoverable state (save for manually going into the build directory). We could make `LLVM_OBJ_SOURCE` the dylib, but figuring out the name thereof is a little tricky. I'm thinking maybe just making it `llc` or `clang` (the latter if the corresponding option is set), since for those to be linked, basically everything else has to be there as well.

**Comment by vtjnash** [comment]
So with cmake, `make install` doesn't have dependencies on the build targets? If so, we should be doing `make && make install` to work around that bug.

**Comment by Keno** [comment]
Correct, that's an option as well.

**Comment by Keno** [comment]
Though if we're using make && make install, there's a question of why we should have OBJ_SOURCE at all.

**Comment by vtjnash** [comment]
Fair enough, the separation between compile and install is somewhat arbitrary. But its correct if not interrupted and gets the correct result in the end even if interrupted there.

**Comment by Keno** [comment]
I wasn't advocating against it, just suggesting if we go that route, we should remove OBJ_SOURCE while we're at it.

**Comment by tkelman** [comment]
It is a source (sorry) of confusion...
