### ISSUE TITLE
test/sparsedir, why the 'dir'?

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#17678]
Is there a reason for the 'dir' in test/sparsedir? If not, should test/sparsedir become simply test/sparse, consistent with the naming of test/'s other subdirectories? Best!

**Comment by andreasnoack** [comment]
There used to be a bug such that you couldn't name the directory the same thing as the file. If it has changed then we should definitely rename it.

**Comment by kshyatt** [comment]
@Sacha0 I fixed this in my MEGA PULL #17165

**Comment by tkelman** [comment]
we could make that pr easier to review and split file moves out of it

**Comment by kshyatt** [comment]
Ah but I had to change `testdefs` and `choosetests` too. Let me see what I can do tonight.

**Comment by tkelman** [comment]
closed by https://github.com/JuliaLang/julia/pull/17165 / https://github.com/JuliaLang/julia/pull/18738
