### ISSUE TITLE
Map do not work for dictionaries in 0.5

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#17714]
It seems to be a regression that dictionaries cannot be mapped anymore. The input below works fine in 0.4.
```
julia> d=[i=>i+1 for i=1:10]
julia> map((x)->"$(x[1])=>$(x[2])",d) # Works in 0.4 but throws a method error in 0.5
ERROR: MethodError: no method matching similar(::Dict{Int64,Int64}, ::Type{String})
julia> map((x)->println("$(x[1])=>$(x[2])"),d) # Works in 0.4 but throws a method error in 0.5
ERROR: MethodError: no method matching similar(::Dict{Int64,Int64}, ::Type{Void})
```

**Comment by JeffBezanson** [comment]
`map` now does this:

```
julia> map(x->2x[1]=>x[2], Dict(1=>2, 2=>3))
Dict{Int64,Int64} with 2 entries:
  4 => 3
  2 => 2
```

If you want an array, I think it's better to use a comprehension for that.

**Comment by tkelman** [comment]
Is this change documented as breaking in NEWS?

**Comment by StefanKarpinski** [comment]
Speaking of which, I don't think the new `Dict(k(x) => v(x) for x in itr)` is in NEWS, is it?

**Comment by tkelman** [comment]
closed by https://github.com/JuliaLang/julia/commit/fc3cbc9e15c73c937afbee35e08b8809ef282f58 ? @dhoegh leave a comment if you disagree and we can reopen if there's anything else needed here
