### ISSUE TITLE
svdvals! has no method for Array{BigFloat,2}, causing norm2(::Array{BigFloat,2}) to error

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#17728]
The function `svdvals!` does not have a method for `Array{BigFloat,2}`. This is an issue because, as in the attached clip, it's pretty common to use the 2-norm of matrices, which inevitably calls `svdvals!` and fails.

![capture](https://cloud.githubusercontent.com/assets/1814174/17275591/0381ce60-56c2-11e6-9632-e6decec08535.PNG)

Simple example:

```
A = map(BigFloat,rand(4,2))
norm(A,2)
```

**Comment by simonbyrne** [comment]
You can use [GenericSVD.jl](https://github.com/simonbyrne/GenericSVD.jl): we should try to move this into Base at some point.

**Comment by simonbyrne** [comment]
See also #5429 re: generic linear algebra.

**Comment by ChrisRackauckas** [comment]
Closing because this works. Instead of moving to Base, this should probably move to LinearAlgebra.jl, which should move to JuliaMath.
