### ISSUE TITLE
Arrays always display scientific notation floats as Float64 in REPL, even when Array is of type Float32

### ISSUE THREAD

**Issue by esproff** [JuliaLang/julia#17720]
What I mean by the title is that if you write:

julia> [1f10]

The REPL will display this as:

1-element Array{Float32,1}:
1.0e10

instead of what it seems like it should be, which is:

1-element Array{Float32,1}:
1.0f10

**Comment by ararslan** [comment]
On the contrary, I think the visual distinction at the REPL is useful to have. Making `Float64` and `Float32` display the same way could be potentially confusing.

**Comment by esproff** [comment]
@ararslan I think we're in agreement then, it should be the latter, but it currently does the former.

**Comment by ararslan** [comment]
Sorry, I got it backwards! Yes, we're definitely in agreement here. What's especially weird is that it's inconsistent:

```julia
julia> 1f10
1.0f10

julia> [1f10]
1-element Array{Float32,1}
 1.0e10
```
Whatever function prints arrays must be ignoring the distinction between `Float32` and `Float64` in terms of how it's displayed.

**Comment by JeffBezanson** [comment]
Must be this:

```
julia> showcompact(1f10)
1.0e10
```
