### ISSUE TITLE
Overwriting Base.show for Enums

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/julia#17736]
Hi,

I am migrating my packages from v0.4.6 to v0.5.0-rc0 and everything seems to be going smoothly except some places where I'm dealing with Enums.

Here is an example:

``` julia
julia> @enum Test1 A B C

julia> @enum Test2 D E F

julia> A
A::Test1 = 0

julia> D
D::Test2 = 0

julia> Base.show(io::IO,t::Test1) = print(io,"Test1: $t")
WARNING: Method definition show(IO, Main.Test1) in module Main at Enums.jl:96 overwritten at REPL[4]:1.

julia> A
Test1: A

julia> D
D::Test2 = 0
```

The problem is that `WARNING`. I don't think I should receive a warning. It is working as I expect it to work and I think it is legitimate to want to overwrite Base.show like that. 

``` julia
julia> versioninfo()
Julia Version 0.5.0-rc0+0
Commit 0030eec (2016-07-26 20:22 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by KristofferC** [comment]
The reason for the warning is #265. It should work ok if you overwrite it before any other method has touched the show method defined by the macro.

**Comment by EricForgy** [comment]
But this was working fine without a warning in v0.4.6 (??)

**Comment by EricForgy** [comment]
FYI. @KristofferC , I didn't quite understand what you meant (sorry!), but here is another simpler example that shows the same WARNING even if I do not use Base.show before redefining it:

~~~julia
julia> @enum Test1 A B C

julia> @enum Test2 D E F

julia> Base.show(io::IO,t::Test1) = print(io,"Test1: $t")
WARNING: Method definition show(IO, Main.Test1) in module Main at Enums.jl:96 overwritten at REPL[3]:1.
~~~

**Comment by KristofferC** [comment]
I meant that the macro `@enum` defines a `show` method for the type. You are overwriting that method definition with another one. This can be dangerous because the previous method definition can be inlined / cached / whatever in other functions that called the previous method before it got overwritten.

**Comment by EricForgy** [comment]
Ok. I kind of see what you mean, but this was fine in v0.4.6. I don't understand why it is not legitimate in v0.5.0-rc0 if it was fine in v0.4.6. Should it not have been fine in v0.4.6?

It's not a big deal. I can remove my Base.show if that is the case.

**Comment by iamed2** [comment]
This should be possible. 

`show`/`print` should be defined on the `Enum` abstract type and call a function whose methods are generated by `@enum`. Then anyone can override `show`/`print` for their own `@enum`-generated type.

**Comment by oxinabox** [comment]
I think this was resolved by
https://github.com/JuliaLang/julia/pull/30924
and can be closed
