### ISSUE TITLE
NEWS: document command-line option changes

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#17740]

**Comment by ViralBShah** [comment]
@tkelman Would you be the right person to assign this to?

**Comment by tkelman** [comment]
Sure. I think breaking changes should be moved earlier, and ref https://github.com/JuliaLang/julia/pull/13612#issuecomment-236778544 - should also search for and address similar recent comments that say "this should be in NEWS."

Also the deprecations section is quite incomplete and could be fleshed-out better.

**Comment by tkelman** [comment]
- [ ] https://github.com/JuliaLang/julia/pull/16217#issuecomment-223346276 cc @vtjnash
