### ISSUE TITLE
Sequence in parentheses mis-interpreted as tuple

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17743]
Comma has a higher precedence than semicolon, as witnessed e.g. by `1,2;3` returning `3` (after evaluating the tuple `1,2`).

With this interpretation, I expect the expression below to be a sequence of two operations, where the first is an assigment. However, Julia interprets this as tuple, despite the semicolon:

``` Julia
julia> (a=1,2; a)
ERROR: syntax: unexpected semicolon in tuple
```

**Comment by JeffBezanson** [comment]
The problem is that `(a=1, b=2)` is an argument list with 2 keyword arguments (and in the future, that particular syntax will probably be an anonymous struct).

**Comment by andyferris** [comment]
Crazy question: Will anonymous structs have fields with names and fields without names, something like a hybrid of a tuple and a struct?

```julia
(1, 2, 3) # tuple
(a = 1, b =2, c = 3) # struct
(1, 2; c = 3) # hybrid
```
This is getting a little closer to a function signature (with keyword arguments), which (from what I read somewhere in the past) was supposed to be the motivating thought behind tuples. 

> The problem is that (a=1, b=2) is an argument list with 2 keyword arguments

Isn't `(; a=1, b=2)` an argument list with 2 keyword arguments? (and potentially a future syntax for anonymous structs, though admittedly uglier).

**Comment by JeffBezanson** [comment]
This syntax is now taken by named tuples.
