### ISSUE TITLE
make `===` primary, deprecate `is`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#17758]
Since we now almost universally use the `is` function by the operator `===`, we should make that the official name and make `is` a deprecated alias for `===` and eventually free up the name `is`.

**Comment by Ismael-VC** [comment]
> and eventually free up the name **`is`**

@StefanKarpinski is there a new meaning for `is` in the horizon? Or do you just mean to free the name for user code?

**Comment by StefanKarpinski** [comment]
No new meaning – it just seems weird to have two names for the same operation for no reason.
