### ISSUE TITLE
Performance regression for `exp`, `sin`, `cos`

### ISSUE THREAD

**Issue by cortner** [JuliaLang/julia#17751]
```julia
function test0(N)
   r = 0.234
   for n = 1:N
      exp(r)
   end
end
test0(10)
@time test0(1_000_000)
@time test0(1_000_000)
@time test0(1_000_000)
```
Output in v0.4:
```bash
> julia exp_test.jl
  0.006532 seconds (148 allocations: 10.151 KB)
  0.006524 seconds (4 allocations: 160 bytes)
  0.006999 seconds (4 allocations: 160 bytes)
```
Output in v0.5:
```bash 
$ julia5 exp_test.jl
  0.012711 seconds (133 allocations: 7.703 KB)
  0.012758 seconds (4 allocations: 160 bytes)
  0.014031 seconds (4 allocations: 160 bytes)
```
same if I replace `exp` with `sin` or `cos`; haven't tried others. I did test against a simple squaring function where the performance remains the same in both versions.

## LLVM code for `v0.4`
```
julia> @code_llvm test0(1_000_000)

define void @julia_test0_21678(i64) {
top:
  %1 = icmp sgt i64 %0, 0
  %2 = select i1 %1, i64 %0, i64 0
  %3 = icmp eq i64 %2, 0
  br i1 %3, label %L3, label %L

L:                                                ; preds = %L, %top
  %"#s1.0" = phi i64 [ %4, %L ], [ 1, %top ]
  %4 = add i64 %"#s1.0", 1
  %5 = call double inttoptr (i64 13299772784 to double (double)*)(double inreg 2.340000e-01)
  %6 = icmp eq i64 %"#s1.0", %2
  br i1 %6, label %L3, label %L

L3:                                               ; preds = %L, %top
  ret void
}
```

## LLVM output for `v0.5`
```
julia> @code_llvm test0(1_000_000)

define void @julia_test0_68854(i64) #0 {
top:
  %1 = icmp slt i64 %0, 1
  br i1 %1, label %L2, label %if.preheader

if.preheader:                                     ; preds = %top
  br label %if

L2.loopexit:                                      ; preds = %if
  br label %L2

L2:                                               ; preds = %L2.loopexit, %top
  ret void

if:                                               ; preds = %if.preheader, %if
  %"#temp#.03" = phi i64 [ %2, %if ], [ 1, %if.preheader ]
  %2 = add i64 %"#temp#.03", 1
  %3 = call double inttoptr (i64 13444864816 to double (double)*)(double 2.340000e-01)
  %4 = icmp eq i64 %"#temp#.03", %0
  br i1 %4, label %L2.loopexit, label %if
```

**Comment by johnmyleswhite** [comment]
I think the regression isn't in any of the functions you've listed, but in the way that this kind of no-op gets optimized. I see identical performance in 0.4 and 0.5 for the following:

```jl
function test0(N)
   r = 0.234
   s = 0.0
   for n = 1:N
      s += exp(r)
   end
end
test0(10)
@time test0(1_000_000)
@time test0(1_000_000)
@time test0(1_000_000)
```

**Comment by cortner** [comment]
I'm afraid not. I had tested precisely your version before as well, but had the same result, hence I posted the simpler code:

```
Sunrise:JuLIPtests ortner$ julia exp_test.jl
  0.006522 seconds (148 allocations: 10.151 KB)
  0.006903 seconds (4 allocations: 160 bytes)
  0.006181 seconds (4 allocations: 160 bytes)
Sunrise:JuLIPtests ortner$ julia5 exp_test.jl
  0.012776 seconds (133 allocations: 7.703 KB)
  0.012746 seconds (4 allocations: 160 bytes)
  0.013848 seconds (4 allocations: 160 bytes)
```

```
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
julia> versioninfo()
Julia Version 0.5.0-rc0+0
Commit 0030eec* (2016-07-26 20:22 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, has well)
```

**Comment by yuyichao** [comment]
Have you tried 0.4 with llvm 3.7.1 (and vice versa).

What's the native code?

Ref https://llvm.org/bugs/show_bug.cgi?id=25277

**Comment by cortner** [comment]
I'm afraid I haven't really explored Julia so deeply that I know how to switch LLVMs - sorry. Interesting though that @johnmyleswhite  cannot reproduce the problem.  Linux/Windows vs Apple?

**Comment by johnmyleswhite** [comment]
It turns out that my 0.5 build was a few days old. I'm currently building the latest commit to see if the reason I couldn't reproduce your results is that the regression happened in the last 5 days. Will report back once the build is finished.

**Comment by johnmyleswhite** [comment]
Still don't see it with the latest commit on master for 0.5:

```jl
julia> versioninfo()
Julia Version 0.5.0-rc0+122
Commit 633443c (2016-08-02 00:53 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

julia> function test0(N)
          r = 0.234
          s = 0.0
          for n = 1:N
             s += exp(r)
          end
       end
test0 (generic function with 1 method)

julia> test0(10)

julia> @time test0(1_000_000)
  0.008087 seconds (133 allocations: 7.703 KB)

julia> @time test0(1_000_000)
  0.008218 seconds (4 allocations: 160 bytes)

julia> @time test0(1_000_000)
  0.007780 seconds (4 allocations: 160 bytes)
```

```jl
julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> function test0(N)
          r = 0.234
          s = 0.0
          for n = 1:N
             s += exp(r)
          end
       end
test0 (generic function with 1 method)

julia> test0(10)

julia> @time test0(1_000_000)
  0.011705 seconds (146 allocations: 9.995 KB)

julia> @time test0(1_000_000)
  0.019303 seconds (4 allocations: 160 bytes)

julia> @time test0(1_000_000)
  0.007988 seconds (4 allocations: 160 bytes)
```

And I get the same results for your original example. Seems like there must be something subtly different between our Julia 0.5 setups. Did you build from source?

**Comment by cortner** [comment]
I just built from source (I don't normally), and now I don't see the regression anymore. On the nightly that I just downloaded I do see the regression.

**Comment by cortner** [comment]
```
Julia Version 0.5.0-rc0+122
Commit 633443c (2016-08-02 00:53 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, has well)
```
vs
```
Julia Version 0.5.0-rc0+115
Commit 643bac8 (2016-08-01 21:42 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by cortner** [comment]
Is the nightly built on a different system? see `x86_64-apple-darwin13.4.0` vs `x86_64-apple-darwin15.6.0`

**Comment by cortner** [comment]
let me know if you want me to try something else; I will also try the next nightly tomorrow.

**Comment by ViralBShah** [comment]
Is this only in the libm functions, or if you write a function f() that roughly takes the same execution time as `exp`, do you see the same perf regression?

**Comment by yuyichao** [comment]
> let me know if you want me to try something else;

https://github.com/JuliaLang/julia/issues/17751#issuecomment-236782490

> What's the native code?

**Comment by ViralBShah** [comment]
To build julia 0.4 with llvm 3.7.1, you have to clone julia and then change the llvm version in deps/Versions.make.

**Comment by KristofferC** [comment]
I can reproduce. rc0 is slow, built from source is fast. Rebuilding the sysimg file did not help. Native code is identical:

```jl
julia> @code_native test0(1_000_000)
	.text
Filename: REPL[4]
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r14
	pushq	%rbx
	subq	$16, %rsp
	movq	%rdi, %rbx
Source line: 3
	testq	%rbx, %rbx
	jle	L62
	movabsq	$140279242572400, %rax  # imm = 0x7F954E6C4270
Source line: 4
	vmovsd	(%rax), %xmm0           # xmm0 = mem[0],zero
	vmovsd	%xmm0, -24(%rbp)
	movabsq	$140279240293456, %r14  # imm = 0x7F954E497C50
L48:
	vmovsd	-24(%rbp), %xmm0        # xmm0 = mem[0],zero
	callq	*%r14
Source line: 3
	addq	$-1, %rbx
	jne	L48
Source line: 4
L62:
	addq	$16, %rsp
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
	nopw	(%rax,%rax)
```

**Comment by pabloferz** [comment]
I was seeing something like this using the generic Linux binaries vs. building from source a couple of months ago. The difference was that the generic ones were using a libm included in the binary, instead of the system one. Manually, changing the so files to point to the system libm makes the performance equal. I wouldn't be surprised if this is also the case here.

**Comment by ufechner7** [comment]
On my machine, Julia 0.5rc0, compiled from source is faster than Julia 0.4:

Julia 0.5:
julia> @time test0(1_000_000)
  0.005780 seconds (133 allocations: 7.703 KB)
julia> @time test0(1_000_000)
  0.005524 seconds (4 allocations: 160 bytes)
julia> @time test0(1_000_000)
  0.005612 seconds (4 allocations: 160 bytes)

Julia 0.4:
julia> @time test0(1_000_000)
  0.006219 seconds (39 allocations: 33.984 KB)
julia> @time test0(1_000_000)
  0.006888 seconds (4 allocations: 160 bytes)
julia> @time test0(1_000_000)
  0.006956 seconds (4 allocations: 160 bytes)

Julia 0.4:
Version 0.4.5 (2016-03-18 00:58 UTC)
Installed as Ubuntu package.

Julia 0.5:
Version 0.5.0-rc0+0 (2016-07-26 20:22 UTC)

Uwe

**Comment by yuyichao** [comment]
@ufechner7 Please quote your code, especially macro calls. Even though the poor https://github.com/time doesn't seems to be particularly active...

**Comment by ufechner7** [comment]
Sorry. Won't forget it next time.

**Comment by simonbyrne** [comment]
I'm seeing the same thing (i.e. [this example](https://github.com/JuliaLang/julia/issues/17751#issuecomment-236785753) being about 3x slower on the downloaded rc0 vs the same built locally). This is appears to be a problem with the openlibm build we include in the rc: when I built Julia with 
```
make LIBMNAME=/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/libopenlibm.dylib
```
I also get the same slowdown.

**Comment by tkelman** [comment]
OSX binaries are built with `MARCH=core2` so they run on old systems (Linux and Windows use `MARCH=x86-64`). That may be preventing openlibm from getting compiled with more modern SIMD instructions?

**Comment by KristofferC** [comment]
I reproduced on linux binary though.

**Comment by simonbyrne** [comment]
isn't `core2` newer than `x86-64`?

**Comment by tkelman** [comment]
yes. I don't think there were any intel macs that predated core2 though.

**Comment by simonbyrne** [comment]
However I can't seem to recreate the issue by just rebuilding libm with `MARCH=core2`. Could it be something else?

**Comment by tkelman** [comment]
rpath?

**Comment by simonbyrne** [comment]
That's beyond my skillset...

**Comment by simonbyrne** [comment]
But this wasn't an issue with 0.4 (and I don't see an issue if I build 0.5 with `LIBMNAME` pointing to the dylib in the 0.4 release). So something has gone wrong with either openlibm upgrade or the buildbot since then.

**Comment by tkelman** [comment]
the openlibm version that we're using is a fair bit different now isn't it?

**Comment by simonbyrne** [comment]
We haven't really changed any of the code though, only headers and build files.

**Comment by ViralBShah** [comment]
Our openlibm version is different from the one in julia 0.4. That still wouldn't explain why building the RC locally would result in a binary faster than the pre-built one.

**Comment by tkelman** [comment]
that would be down to compiler flags or compiler versions

**Comment by ViralBShah** [comment]
The flags will be the same as well for the same checkout. What compiler and compiler version are the buildbots using for mac and linux?

**Comment by tkelman** [comment]
No, as described above, the buildbots use a set of compiler flags that disable newer simd instructions so the binaries run on older hardware. I don't know offhand what compiler version is used on the mac buildbot. Linux buildbots are on gcc 5.1 or 5.2 I think.

**Comment by simonbyrne** [comment]
Are the same compiler flags used for 0.4 and 0.5?

**Comment by tkelman** [comment]
ah, right, yes they should be the same. so my best guess is still rpath making a difference somehow then.

**Comment by ViralBShah** [comment]
@simonbyrne you may recollect using -O0 for some of the rounding operations. But that shouldn't affect this. 

How might rpath affect this? It is unlikely that a different openlibm is being picked. I guess at best, perhaps a system libm is getting picked in some cases?

**Comment by ViralBShah** [comment]
I can confirm that the performance issue is certainly there - only on the 0.5 binaries, but not on the 0.4 binaries or on master built locally. There are 2 major changes worth noting:

We went from `-O3` in the 0.4 release to `-O2` now. Files related to rounding had to go to `-O0` for correctness reasons, but those are not relevant to these numbers.

**Comment by ViralBShah** [comment]
Copying the libopenlibm.dylib from master to the Julia-0.5 restores the performance level. I think the easiest way to test is to bump openlibm in julia to the latest release I just tagged (0.5.2) and try out the newest nightly.

**Comment by tkelman** [comment]
reopen if that doesn't actually fix it

**Comment by simonbyrne** [comment]
I just downloaded the latest nightly (d3df8e7), but still see the issue.

**Comment by cortner** [comment]
same for me; and for what it's worth: 

* v0.4.6, prebuilt  : 0.0064353 seconds
* v0.5-rc1 built locally :  0.007741 seconds
* nightly :   0.012451 seconds

**Comment by ViralBShah** [comment]
Is this issue only on mac, or on linux as well?

**Comment by simonbyrne** [comment]
Yes, according to Kristoffer above

**Comment by ViralBShah** [comment]
BTW, unlike Kristoffer, I do see different native code generated. The local build is generating `vmovsd` instructions before the call, whereas the downloaded one is generating `movsd`, perhaps because it is compiled to be more generic. On my local master build:

```
julia> VERSION
v"0.6.0-dev.72"

julia> @code_native test0(1_000_000);
	.section	__TEXT,__text,regular,pure_instructions
Filename: REPL[4]
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r14
	pushq	%rbx
	subq	$16, %rsp
	movq	%rdi, %rbx
Source line: 3
	testq	%rbx, %rbx
	jle	L62
	movabsq	$13175163952, %rax      ## imm = 0x3114D0C30
Source line: 4
	vmovsd	(%rax), %xmm0           ## xmm0 = mem[0],zero
	vmovsd	%xmm0, -24(%rbp)
	movabsq	$exp, %r14
L48:
	vmovsd	-24(%rbp), %xmm0        ## xmm0 = mem[0],zero
	callq	*%r14
Source line: 3
	addq	$-1, %rbx
	jne	L48
Source line: 4
L62:
	addq	$16, %rsp
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
	nopw	(%rax,%rax)
```

as opposed to the downloaded nightly:
```

julia> VERSION
v"0.6.0-dev.62"

julia> @code_native test0(1_000_000);
	.section	__TEXT,__text,regular,pure_instructions
Filename: REPL[5]
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r14
	pushq	%rbx
	subq	$16, %rsp
	movq	%rdi, %rbx
Source line: 3
	testq	%rbx, %rbx
	jle	L61
	movabsq	$13309076416, %rax      ## imm = 0x3194863C0
Source line: 4
	movsd	(%rax), %xmm0           ## xmm0 = mem[0],zero
	movsd	%xmm0, -24(%rbp)
	movabsq	$exp, %r14
L48:
	movsd	-24(%rbp), %xmm0        ## xmm0 = mem[0],zero
	callq	*%r14
Source line: 3
	decq	%rbx
	jne	L48
Source line: 4
L61:
	addq	$16, %rsp
	popq	%rbx
	popq	%r14
	popq	%rbp
	retq
	nopw	%cs:(%rax,%rax)

```

**Comment by ViralBShah** [comment]
For the openlibm from the nightlies, when I load with `gdb` and `disassemble sin`, I see many more instructions compared to the one that I have built locally.

The compile line does not have anything that suggests that arch specific stuff is being done:
```
clang -stdlib=libc++ -mmacosx-version-min=10.7 -m64  -O3 -fno-builtin -std=c99 -Wall -I/Users/viral/julia/deps/build/openlibm-0fa599cce845be67ed1729d9753f67e366c37b96 -I/Users/viral/julia/deps/build/openlibm-0fa599cce845be67ed1729d9753f67e366c37b96/include -I/Users/viral/julia/deps/build/openlibm-0fa599cce845be67ed1729d9753f67e366c37b96/ld80 -I/Users/viral/julia/deps/build/openlibm-0fa599cce845be67ed1729d9753f67e366c37b96/amd64 -I/Users/viral/julia/deps/build/openlibm-0fa599cce845be67ed1729d9753f67e366c37b96/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -fPIC  -c ld80/e_acoshl.c -o ld80/e_acoshl.c.o
```

To make this easier to analyse, what version of OS X are we building the nightlies on and with what compiler?

**Comment by simonbyrne** [comment]
This appears to be due to a change in the default openlibm build flags from -O3 to -O2, (https://github.com/JuliaLang/openlibm/pull/106), combined with the fact that we package on OS X 10.9 (which uses an older version of clang).

Some options:
- Build on a newer machine
- Change build flag in the deps makefile
- Change the build flag back in openlibm

**Comment by tkelman** [comment]
that was put back by https://github.com/JuliaLang/openlibm/commit/f8d64df5963f6f5343cc173e8a5d1908b22de87b though

**Comment by ViralBShah** [comment]
How about on linux? Similar old compiler issue?

**Comment by simonbyrne** [comment]
Ah okay: the problem on the OS X buildbot is that there is already a CFLAGS environment variable, which overrides this.

**Comment by simonbyrne** [comment]
No idea about linux, I don't have access to that buildbot.

**Comment by tkelman** [comment]
Who was setting `CFLAGS`, and to what?

**Comment by simonbyrne** [comment]
It appears to be homebrew related

**Comment by KristofferC** [comment]
Just to make sure. We have tested the new build?

**Comment by simonbyrne** [comment]
No, we will have to wait until new nightlies are available.

**Comment by ViralBShah** [comment]
The PR merge closed this issue. Let's reopen if necessary.

**Comment by simonbyrne** [comment]
Just confirming that this seems to be now fixed on OS X on RC-2.

@KristofferC Can you check the linux one?
