### ISSUE TITLE
flipdim(A,d) should throw an error if d > ndims(A)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#17752]
Right now, `flipdim([1,2,3],17)` silently succeeds.

I guess it sort of makes sense because we allow you to add trailing singleton indices in `getindex`, but it seems error prone.  I'm not sure if there any other cases where we allow this sort of thing?  e.g. `fft([1,2,3], 17)` throws a `BoundsError`.

(I just got bit by this in upgrading a package to 0.5.  If `A` is a 2d array, then `A[k,:]` gave a 2d array in Julia 0.4 but a 1d array in 0.5, and `flipdim(A[k,:],2)` unexpectedly worked in the latter case but didn't give what I wanted.  It would have been much easier to find if it threw an error.)

**Comment by StefanKarpinski** [comment]
Agreed, but should be changed asap or it can't go into 0.5.

**Comment by stevengj** [comment]
I can make a PR today.

**Comment by stevengj** [comment]
I'm not sure it should go into 0.5, however, since the old behavior was clearly intentional if you look at the code.

Probably the primary utility of the old behavior would be to allow polymorphic routines accepting `A::VecOrMat` to do `flipdim(A,2)` and have it be a no-op for vectors, analogous to the Matlab [`fliplr`](http://www.mathworks.com/help/matlab/ref/fliplr.html) function.

**Comment by stevengj** [comment]
I audited every call to `flipdim` in every registered Julia package, and the only case I could find that passed a dimension greater than `ndims` appears to be a bug (ajt60gaibb/FastGaussQuadrature.jl#36).

**Comment by timholy** [comment]
Seems reasonable to make an error, then, and it would be much better to have that change coincide with the change in the number of dimensions returned by indexing.

Nice job collecting the data needed to make a rational decision. :+1:

**Comment by ajt60gaibb** [comment]
The use of `flipdim(x,2)`, where `x` is a 1d array has been removed in [ajt60gaibb/FastGaussQuadrature.jl](https://github.com/ajt60gaibb/FastGaussQuadrature.jl). See ajt60gaibb/FastGaussQuadrature.jl#37.   @stevengj, judging from your work there should be no more calls with out-of-bound-dimensions to `flipdim` in any of the registered packages.

**Comment by StefanKarpinski** [comment]
I would support changing this now rather than later (despite feature freeze).

**Comment by JeffBezanson** [comment]
This seems to me to be just one among many of the expected side-effects of the indexing change.

Because there are still release-blocking items, there is no release. And because there is no release yet, we can keep adding release-blocking items...
