### ISSUE TITLE
Got exception when calling julia from c++

### ISSUE THREAD

**Issue by Jasonqian1** [JuliaLang/julia#17767]
Hi ,

I have a java test program that calling C++ (JNI) and the C++ calling Julia.
It works fine when running one instance, but when repeatedly running the instance, I got following 
error (In our real application, it killed the running processor).

Julia 0.4.6 : julia-0.4.6-linux-x86_64
Linux : 2.6.32-358.el6.x86_64
gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)

Thanks
Jason

fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
rec_backtrace at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
jl_throw at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
jl_exit_on_sigint at /home/Julia/julia-2e358ce975/lib/julia/libjulia.so (unknown line)
unknown function (ip: 0x3e8a40f500)
unknown function (ip: 0x7f9244ddf1e4)
unknown function (ip: 0x7f9244dd8365)
unknown function (ip: 0x7f9244f1992f)
unknown function (ip: 0x7f9244f19a35)
unknown function (ip: 0x7f9244de04b8)
unknown function (ip: 0x3e8a407851)
clone at /lib64/libc.so.6 (unknown line)
unknown function (ip: (nil))

**Comment by ViralBShah** [comment]
Can you provide a test snippet? Cc @aviks

**Comment by aviks** [comment]
This is usually a sign of memory corruption somewhere. Given your setup, there is clearly a large surface area for those kinds of errors, so it is difficult to say more without looking deeper into your code. 

The stack trace suggests julia is responding to a `SIGINT`, so one point to look into is how your application propagates signals, but there is no guarantee that the problem is in that area.

**Comment by Jasonqian1** [comment]
Thanks for the quickly reply.

Attached is the test program. There are 2 directories under jc dir.
jc
  cpp  -- cpp run time
  java -- java test driver

To run the test:

Go to the java directory and run "run.sh"

You many need to run "run.sh" repeatedly 3/4 times to recreate the problem.



Thanks
Jason Qian

**Comment by ViralBShah** [comment]
Attachments do not come through. You will probably have to post the code in a gist.

**Comment by Jasonqian1** [comment]
please try again,

**Comment by vtjnash** [comment]
Please post the code as a github repo or gist

**Comment by Jasonqian1** [comment]
https://github.com/Jasonqian1/julia_17767

Thanks
Jason Qian

**Comment by vtjnash** [comment]
You're calling the atexit callback hook, then attempting to continue using Julia. This is not supported.

**Comment by Jasonqian1** [comment]
Thanks Chao yuyi,

   1. I removed   //jl_atexit_hook(0);   but still got the same error.
   2. I removed all the Julia call, but only keep jl_init(juliaroot);  still got the same error.

  It seems the memory corruption happens when jl_init() out of scope.
  
Thanks again,
Jason Qian

**Comment by vtjnash** [comment]
From http://www.oracle.com/technetwork/java/javase/signals-139944.html#gbzcj 6.1.3, it sounds like you need to link with libjsig.so. Eventually (#16882), we need to implement the same for Julia so that we play nice with other runtimes that want to use unix signals.

**Comment by Jasonqian1** [comment]
Thanks a lot,  link with libjsig.so seems fixed the problem  :)
