### ISSUE TITLE
libgit2 and ssh keys - regression in 0.5.0-rc0 compared to 0.4.0

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaLang/julia#17768]
This is a regression on 0.5.0-rc0 with a local git repo using SSH, this is using the workaround for libcurl 

https://github.com/JuliaLang/julia/issues/13472

This is on Ubuntu 3.16.0-77-generic

```
INFO: Initializing package repository /home/michael/.julia/v0.5
INFO: Cloning METADATA from git@git.wow.com:external/METADATA.jl.git
ERROR: error authenticating:  ssh-agent
Private key location for 'git@git.wow.com' [/home/michael/.ssh/id_rsa]:
Passphrase for /home/michael/.ssh/id_rsa:

julia> Pkg.add( "Foo" )
ERROR: error authenticating:  ssh-agentINFO: Updating cache of Foo...

Private key location for 'git@git.wow.com' [/home/michael/.ssh/id_rsa]:ERROR: error authenticating:  ssh-agent
Private key location for 'ssh://git@git.wow.com' [/home/michael/.ssh/id_rsa]:
```
and then just hangs ...

**Comment by mdcfrancis** [comment]
actually does not hang, requests user input for each and every repo.

**Comment by Keno** [comment]
keys are cached during Pkg.update, or can be set using environment variables. For any other usage, I'd recommend starting an ssh agent.

**Comment by mdcfrancis** [comment]
This is very different behavior from previously. I don't have to do this with regular git commands. Makes the system much less friendly.

**Comment by Keno** [comment]
How is your regular git accessing ssh credentials?

**Comment by wildart** [comment]
It looks like #17691 changed credentials caching mechanism.

**Comment by mdcfrancis** [comment]
@Keno that's a good question and one that I would have to do some research on, but basically with a standard install on ubuntu you simply don't have to worry. This was never an issue with 0.4 or with any other git client.

**Comment by Keno** [comment]
Can you see if `ssh-add -l` lists your key? In that case there may be an issue with how libgit2 communicates with the agent.

**Comment by mdcfrancis** [comment]
no that does not list the key - by default it is just using ~/.shh/id_rsa.pub

**Comment by Keno** [comment]
Sure, but the key appears to be encrypted? Is it not?

**Comment by mdcfrancis** [comment]
no the key is not encrypted

**Comment by Keno** [comment]
Ah, maybe that commit did not make it into rc0, can you try rc1?

**Comment by mdcfrancis** [comment]
Worse :( Pkg.init( ... ) to a local fork of METADATA hosted internally

ERROR: error authenticating:  ssh-agent
ERROR: GitError(Code:ERROR, Class:SSH, Failed to authenticate SSH session: Unable to open public key file)
 in macro expansion at ./libgit2/error.jl:98 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractPayload}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:320

**Comment by mdcfrancis** [comment]
I'll try and figure out what is going on

**Comment by Keno** [comment]
Ah, I think I've seen that one and have a fix. Hold on

**Comment by mdcfrancis** [comment]
With master now I just get the following 

`ERROR: error authenticating:  ssh-agent`

but it correctly works with ssh

**Comment by wildart** [comment]
Which means that your `~/.shh/id_rsa` key was a correct key for the authentication, if you didn't get prompted.

@Keno I wounder can we drop this message about ssh-agent. If it fails, it fails. No harm done, so we switch to key-based authentication.

**Comment by mdcfrancis** [comment]
Yes exactly - this is working correctly, just the error message is distracting

**Comment by Keno** [comment]
Yes, we should drop the message.

**Comment by StefanKarpinski** [comment]
Isn't there a PR for this?

**Comment by Keno** [comment]
Already done.

**Comment by StefanKarpinski** [comment]
Can we have some cross references here then (and close the issue as appropriate).

**Comment by Keno** [comment]
The original issue was fixed as part of https://github.com/JuliaLang/julia/pull/17651, the ssh-agent issue I did in https://github.com/JuliaLang/julia/pull/17860. Though there have been a couple of others in between refactoring this stuff, so there may have been other issues in between.
