### ISSUE TITLE
Dict syntax deprecation warning doesn't show line numbers or filename on windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17770]
On the latest nightly build, I'm getting a fair number of deprecation warnings like this:
````
WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.

WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.
````
Would be great if these could show a filename and line number, kind of hard to fix them otherwise :)

**Comment by tkelman** [comment]
Can you provide a reproducible test case?

**Comment by tkelman** [comment]
Also try with `julia-debug` or `--precompiled=no` to see if either of those make any difference.

**Comment by JeffBezanson** [comment]
Dup of #16967.

Deprecation warnings from the lowering pass don't have easy access to location info, so this is pretty difficult to fix.
