### ISSUE TITLE
SSH clone fails against remotes running newer OpenSSH versions

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#17772]
libssh2 advertises support for `diffie-hellman-group-exchange-sha256`, but that kex protocol seems to be buggy or otherwise unsupported, causing Pkg clone failures if the remote has a decently up-to-date openssh. Right now GitHub does not have support for that protocol, but we should either patch libssh2 to disable this feature of figure out what's broken to avoid nasty surprises if GitHub upgrades.

**Comment by Keno** [comment]
Seems to only be an issue with the mbedTLS backend, cc @wildart

**Comment by Keno** [comment]
SSH log: https://gist.github.com/Keno/5052e76475ae56653ce398032e758404

**Comment by wildart** [comment]
I bet there is some flag that disables this protocol. Try to disable it  with `LIBSSH2_DH_GEX_NEW`.

**Comment by Keno** [comment]
Ok, the solution is simple. The required numbers are larger than `MBEDTLS_MPI_MAX_SIZE` (2055 > 2048), so all random numbers are 0, and the server gets confused (and the client doesn't do error checking. We should bump MBEDTLS_MPI_MAX_SIZE (maybe to 3072). I have also started a PR to add proper error checking to libssh2 here: https://github.com/libssh2/libssh2/pull/119.

**Comment by wildart** [comment]
make it, 4096

**Comment by wildart** [comment]
Have you seen this https://github.com/ARMmbed/mbedtls/blob/9803d07a63621697ff2f632066dce4d57f0f60fc/include/mbedtls/bignum.h#L70-L71?

**Comment by Keno** [comment]
Oh, hold on, there's an even worse bug. libssh2 passes the desired number of bits, but the mbedtls api takes bytes.

**Comment by wildart** [comment]
That could be my fault.

**Comment by Keno** [comment]
Well, many people took a look at that code, and nobody caught it so far, so I think there's some collective blame to go around. Let's fix it in any case.

**Comment by Keno** [comment]
I wonder if fixing that would allow us to not have to patch the config file

**Comment by wildart** [comment]
I see. I used `mbedtls_mpi_size` instead of `mbedtls_mpi_bitlen` in `mbedtls.c`.

**Comment by Keno** [comment]
No, I think that's correct.

**Comment by Keno** [comment]
The problem is in `_libssh2_bn_rand`

**Comment by Keno** [comment]
What we probably need to do is:
```
int _libssh2_bn_rand(bn, bits, top, bottom) {
    err = mbedtls_mpi_fill_random(bn, bits/8+1, mbedtls_ctr_drbg_random, &_libssh2_mbedtls_ctr_drbg)
    // check err, etc
    // zero out top bits%8 bits
}
```
Do you want to take care of that? In that case I'll move on to something else.

**Comment by Keno** [comment]
Hey, look we're not the only ones who were confused about that parameter: https://github.com/libssh2/libssh2/pull/103

**Comment by wildart** [comment]
Why do you need to zero out top bits%8 bits?

**Comment by Keno** [comment]
Otherwise you get numbers that are too large by a couple of bits. I don't see a problem with that in the way the numbers are used by libssh2 (since g^x retains wrap-around properties), but I imagine it would be good to follow the API in any case?

**Comment by wildart** [comment]
Indeed, problem was in incorrect byte size, so no config patch required. I'll submit libssh2-mbedtls patch ASAP.
