### ISSUE TITLE
Access to system process IDs via a Process

### ISSUE THREAD

**Issue by petersbr** [JuliaLang/julia#17787]
Below is a summarization of an issue I encountered and asked about on SO which has no direct solution short of modifying core julia itself so am re-sharing the possible solution that was supplied here .   [SO link](http://stackoverflow.com/questions/38644939/how-can-i-get-the-system-process-id-of-a-running-external-command-in-julia)

__Problem__: I would like to monitor runtime characteristics of calls made by Julia to the system which means I need to know the system process id of something I run or spawn.  My reasons for wanting to know had to do with memory consumption but there are endless other possibilities for why you would want to know what is happening with something you've launched from within julia at the system level.

I was looking for something like a nonblocking:

    pid = @async run( `my_external_program` )

where pid would be the system process id for my_external_program

__Answer given by sharededit pointing to how to change Process in Julia to provide this__:
Right now you can spawn a process asynchronously and grab a handle with spawn, e.g.

    process = spawn(`sleep 10`)

this returns a Process object. Unfortunately I don't see an easy way to get the pid from this right now, but it should be possible. The process.handle field is a pointer to the underlying libuv process struct. You could get that out by converting the struct to a Julia object, or alternatively you could write a small C function in Julia's source code to get it, e.g.

    # C
    int jl_get_proc_pid (uv_process *proc) { return proc.pid }
    # in Julia
    pid(process::Process) = ccall(:jl_get_proc_pid, (Ptr{Void},), Int, process.handle)

This might be a nice opportunity to make a patch to Julia, although it would be nice if someone told me I was wrong and there's an easier way that I've overlooked :)

shareedit
answered Jul 29 at 19:06

one-more-minute
1,013810
  	 	
In particular, I would open an issue requesting this feature: github.com/JuliaLang/julia/issues/new – StefanKarpinski 2 days ago

**Comment by Keno** [comment]
Dup of #10420, your solution is correct, I think we'd consider the pull request. Note that I had suggested `getpid(p::Porcess)` in that issue to be consistent with `getpid()`.

**Comment by JeffBezanson** [comment]
Closing as dup. I agree with @Keno .
