### ISSUE TITLE
Strange @sync @parallel loop behaviour

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#17788]
I  posted it to the users group but it got somehow ignored. Sometimes it happens and sometimes it does not and I cannot find an explanation.

My specs: 

Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

The problem:

```
> 
> julia> addprocs(4)
> 4-element Array{Int64,1}:
>  2
>  3
>  4
>  5
> 
> julia>  for k=1:1000
>                A = SharedArray(Int64,5)
>                @sync @parallel for i=1:1000
>                           for j=1:5
>                                A[j] += 1
>                           end
>                 end
>                if (sum(A)!=5000)
>                     println("\n Error :: ",A)
>                end
>        end
> 
>  Error :: [750,1000,1000,1000,1000]
> 
>  Error :: [1000,1000,1000,1000,750]
> 
>  Error :: [926,930,929,930,930]
> 
>  Error :: [954,959,946,941,953]
> 
>  Error :: [929,922,917,915,883]
> 
>  Error :: [993,994,994,994,994]
> 
>  Error :: [945,971,969,963,923]
> 
>  Error :: [916,921,922,924,922]
> 
>  Error :: [750,1000,1000,1000,1000]
> 
>  Error :: [933,962,955,951,932]
> 
>  Error :: [937,942,949,954,954]
> 
>  Error :: [916,926,914,921,915]
> 
>  Error :: [981,973,975,977,978]
> 
>  Error :: [957,964,960,953,950]
> 
>  Error :: [920,919,920,921,922]
> 
>  Error :: [952,957,955,942,952]
> 
>  Error :: [939,946,944,944,941]
> 
>  Error :: [943,948,946,950,949]
> 
>  Error :: [981,973,971,979,988]
> 
>  Error :: [948,943,924,922,935]
> 
>  Error :: [972,966,966,968,978]
```

**Comment by amitmurthy** [comment]
Somebody correct me if I am wrong. The issue here is that `A[j] += 1` isn't probably atomic when executed concurrently on 4 different processes with the same value of `j` and where `A` is shared memory.

**Comment by CodeLenz** [comment]
Hi @amitmurthy.

Do you mean that if two processes access the same position of A at same time, just one will modify the array  ?

**Comment by amitmurthy** [comment]
Assuming `A[j] += 1` is a fetch, increment and write-back operation, what is probably happening is two processes access the same position at the same time and hence fetch and write back the same incremented value.

**Comment by CodeLenz** [comment]
I was unaware of this. I guess it may hit others as well, so it may be a good idea to comment it in the documentation of SharedArray (if it's not already there).

Thank you very much  @amitmurthy for your time.

**Comment by amitmurthy** [comment]
What you probably need is to partition access to the shared array among workers. http://docs.julialang.org/en/latest/stdlib/parallel/#Base.localindexes specifies a simple partitioned range on each worker for this.
