### ISSUE TITLE
fill(Array, Int) copies by reference

### ISSUE THREAD

**Issue by esproff** [JuliaLang/julia#17796]
Writing something of the form:

`A = fill(zeros(4),2)`

will create a vector of arrays of type `Array{Array{Float64,1},1}`.  However each array in this vector is copied by reference.  Thus if you do

`A[1][1] = 5`

this will change the first element of both arrays to 5.  Is this the intended functionality?  Or should `fill` copy by value?

**Comment by yuyichao** [comment]
Yes this is intended. Use `deepcopy` if you really have to copy everything.

**Comment by yuyichao** [comment]
I somehow read that you did a copy. In any case, this is intended, documented (in the doc of `fill`).

**Comment by vtjnash** [comment]
The more idiomatic form would be a 2x2 comprehension, not deepcopy.

**Comment by yuyichao** [comment]
1d comprehension *, I only mentioned deepcopy since I somehow thought he was doing a copy to begin with.
