### ISSUE TITLE
Pkg.add should confirm any package downgrade with user

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17799]
Right now any `Pkg.add` can lead to a downgrade of some other installed package. That seems like a bad user experience: when I add a new package, I probably don't want my other packages to revert to an old version.

I think a better solution would be if `Pkg.add` detects that it needs to do some package downgrades, it should show the user the list of packages that would be downgraded and then confirm whether the user actually really wants to proceed or not. And then there could be a `force` argument to `Pkg.add` that would just go ahead without user confirmation.

The same logic might also apply to some other package commands. Probably `Pkg.clone`. Not sure about `Pkg.update`...

**Comment by JeffreySarnoff** [comment]
I concur -- never wanting downgrades to occur blindly, and always needing to undo them.  And Pkg.remove should not do it either (if it might).

**Comment by lobingera** [comment]
Example?

**Comment by JeffreySarnoff** [comment]
it happened to me a few times, some months ago -- I do not recall the packages

**Comment by tkelman** [comment]
If you don't want downgrades to happen, you can always add lower bounds to your `Pkg.dir("REQUIRE")` file. Then any time dependency resolution would have to download a package to find a feasible solution, you'll get an error.

**Comment by lobingera** [comment]
A good example would help the discussion. I (using julia for 3 years, although not in production) didn't have package downgrade problems. I'm not in favour to make Pkg.add an interactive activity. It should run or report an error and Tony's recommendation might already be the solution. Dependency problems might be better solved at the package development than on the users' side.

**Comment by davidanthoff** [comment]
My whole optimization stack has been downgraded for a couple of weeks on one of my machines (JuMP, MathProgBase etc.). At some point I must have added some package that caused this downgrade, but at that point I didn't notice it and now I'm stuck. My solution has been to do optimization work on my other machine, but that doesn't seem a good solution ;) If I had seen a warning at ``Pkg.add`` time that my optimization stack will be downgraded, I would not have added the offending package.

I see the problem with making ``Pkg.add`` interactive. I think there are a couple of options:
1) what I suggested, make ``Pkg.add`` interactive by default, but have a ``force`` option that will never interact.
2) make ``Pkg.add`` fail if not started in a REPL and if it would downgrade a package. Again also have a ``force`` option.
3) if you don't want interactive stuff at all, make it fail always when it would trigger a downgrade, unless a ``force`` option is specified.

I think most package managers have an interactive UI, and that is probably because people like to have predictability when it comes to package management and not surprises a la "I installed A, now B doesn't work anymore".

@tkelman Manually editing the ``REQUIRE`` file seems incredibly cumbersome and really not practical...

**Comment by tkelman** [comment]
> Manually editing the `REQUIRE` file seems incredibly cumbersome and really not practical...

Then write a script? It sounds like you want a one-sided pinning operation. While a lot of package managers do operate by default in a "say what you're going to do then ask for confirmation" mode, Julia's may have been intentionally designed not to be that way. Would have to ask Stefan and others who've been around long enough to see it in its earliest incarnations.

Asking for confirmation wouldn't help with what you're seeing about having packages get held back because of upper bounds - that's unfortunately a silent thing right now. You could write a little helper function that lets you know when newer versions of some packages are available in METADATA but you aren't upgraded to them because of upper bounds in some other installed packages, but the dependency resolution task of identifying exactly which constraints are active isn't always an easy thing to do.

**Comment by lobingera** [comment]
@davidanthoff: You could try to work out something more concrete as example with Pkg.status() of the machine and browsing the history file (which is quite nice as it includes time stamps).
I think you have a valid point, but i cannot imagine someone working on this (except yourself) without any testcase.

**Comment by davidanthoff** [comment]
> Then write a script?

I don't think this can be the answer to the problem of "I installed A, now B doesn't work anymore" problem. I could maybe write a script (but I'm too lazy), but the larger user group that julia targets certainly is not up to that, the defaults of the package manger should be such that they get a good user experience.

> may have been intentionally designed not to be that way

And maybe there are some good reasons for this, but we should still come up with a good solution to the problem I described. This is the kind of issue that really frustrates novice users...

> Asking for confirmation wouldn't help with what you're seeing 

It would have helped in my case, I know that on that machine JuMP and friends were at a higher version previously, so they must have been downgraded when I added another package. I think there is a difference between the case of a) "oh, all my packages don't upgrade because something is blocked", and b) "I added A, and now B is downgraded and my stuff doesn't work anymore".  a) is annoying but b) is the real culprit in my opinion, because there things actually get worse by a seemingly unrelated package manager thing.

> I think you have a valid point, but i cannot imagine someone working on this (except yourself) without any testcase.

My understanding is that the package manager will get revamped before 1.0, so it seems like a good time to give feedback here, even if I don't intend to work on the package manager itself.

**Comment by mdcfrancis** [comment]
FWIW - we run a specific branch of Julia which disables this behavior, reports the conflicts and exits. Chasing this down and fixing was a multi day exercise.

**Comment by mdcfrancis** [comment]
diff --git a/base/pkg/resolve/interface.jl b/base/pkg/resolve/interface.jl
index ce3426b..074afc5 100644
--- a/base/pkg/resolve/interface.jl
```
+++ b/base/pkg/resolve/interface.jl
@@ -176,6 +176,8 @@ function greedysolver(interface::Interface)
                 if rv > 0 && (sol[rp0] == spp[rp0] || sol[rp0] == rv)
                     sol[rp0] = rv
                 else
+                    error( "Unable to resolve dependecies for $p -> $rp @ $rvs found $(pvers[rp0])\n"
+                      * "This probably is due to a max version specified on $rp package" )
                     return (false, Int[])
                 end
```

**Comment by damiendr** [comment]
Agreed, I've been bitten several times by this and wasted a few hours getting my packages back into a workable state... The command should ask for user confirmation by default. Actually, it would be great if upgrades also asked for confirmation, like `apt-get`.

**Comment by StefanKarpinski** [comment]
This issue is obsoleted by the [new package manager](https://github.com/JuliaLang/Pkg.jl).
