### ISSUE TITLE
random number generation for benchmarks

### ISSUE THREAD

**Issue by alinelena** [JuliaLang/julia#17808]
I see the performance codes for matrix matrix multiplications include the time needed to generate the random numbers. 
Since different languages have different approaces to that and almost always users use special implementations for this scope it may be useful if the benchmark for matrices will contain strictly only matrx computation times.

Alin

**Comment by stevengj** [comment]
Considering that the whole point of that benchmark (if it has a point) is to measure how well the language's standard libraries interface to fast library codes, it seems just as valid to measure whether they interface fast RNG generators as to measure whether they interface a fast BLAS.

(The opposite extreme would be to make sure all the languages are linking to the same BLAS library, and then measure the time of the same dgemm call in all languages.  But of course that benchmark would be totally uninformative.)
