### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#17809]
```
AWS-Sachs-Ubuntu$ usr/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc0+193 (2016-08-04 04:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ff1b65c (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using JSON
WARNING: error while reinitializing value Base._array_for(...):
OutOfMemoryError()
```

**Comment by yuyichao** [comment]
Backtrace? `ulimit`?

**Comment by KristofferC** [comment]
Ref: https://github.com/JuliaLang/julia/commit/1d767cae23f389cf50f19ff78974d340c4bfdd6e#commitcomment-18514292

**Comment by yuyichao** [comment]
I see this on `0.6.0-dev.6` now It seems that the rehashing have blown up the table size somehow.

**Comment by tpapp** [comment]
I experienced the same error with `Version 0.5.0-rc1+0 (2016-08-04 08:48 UTC)`, with any package I tried (including `Distributions`, `StatsFuns`, etc). Deleting all the `*.ji` files in `~/.julia/lib/v0.5` fixed the problem and I now cannot reproduce.
