### ISSUE TITLE
Problems with latexpdf ing the documentation

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#17813]
If I try to build the documentation as described in the [Readme](https://github.com/JuliaLang/julia/tree/master/doc),
```
sudo apt-get install latex-cjk-all texlive texlive-lang-cjk texlive-latex-extra
make latexpdf
```
I get the following error:
```
! Package inputenc Error: Unicode char ∓ (U+2213)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.29842 ...e the scaled Hankel function \(\exp(∓
                                                  iz) H_ν^{(k)}(z)\), where...

? ^Cmake[1]: *** Deleting file 'JuliaLanguage.pdf'
! Interruption.
\GenericError  ...                                
                                                  \endgroup 
l.29842 ...e the scaled Hankel function \(\exp(∓
                                                  iz) H_ν^{(k)}(z)\), where...
```

I tried this on a fresh Ubuntu16.04 with the following julia:

Julia Version 0.5.0-rc0+0
Commit 0030eec (2016-07-26 20:22 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by tkelman** [comment]
Might need to be added here https://github.com/JuliaLang/julia/blob/043eb2636d378e7110de5b997dd869deebd2e906/doc/conf.py#L193

**Comment by jw3126** [comment]
Okay I will try and report.

**Comment by jw3126** [comment]
Okay I added
` \DeclareUnicodeCharacter{2213}{\ensuremath{\mp}}`
to the list and did
```
make cleanall
make latexpdf 
```

now it complains 

```
LaTeX Warning: Reference `stdlib/math:Base.besselhx' on page 403 undefined on i
nput line 29835.
! Missing { inserted.
<to be read again> 
                   \begingroup 
l.29843 ...aled Hankel function \(\exp(∓iz) H_ν
                                                  ^{(k)}(z)\), where \(k\) i...
? H
A left brace was mandatory here, so I've put one in.
You might want to delete and/or insert some corrections
so that I will find a matching right brace soon.
(If you're confused by all this, try typing `I}' now.)
```

**Comment by jw3126** [comment]
Ok it seems the problem was with the ν symbol, although not clear from the error. Now it works, will submit a PR.
