### ISSUE TITLE
How to obtain further improvements

### ISSUE THREAD

**Issue by MSYoon** [JuliaLang/julia#17828]
Dear all,

Now I'm working on a simple code using Julia to make it faster than that of the Matlab. 

Here's simple example of that code. 
---------------------------------------------------------------------------------
tt=900.0; start_t=[101.0 760.0]; delv_gnd=[100 200];  xf_rep=[40000 34000]; # these are all constant variables

xi_low = -delv_gnd.*(tt-start_t) + xf_rep;
xi_low[tt - start_t .< 0] = NaN;
--------------------------------------------------------------------------------
The performance is 1.5x slower that the same code of the Matlab. 
As you can see, this is quite simple code so I couldn't find any further improvement to get faster than the Matlab code. 

Please advise me.

Best regards.

**Comment by yuyichao** [comment]
Please use the julia-users mailing list for questions like this.

**Comment by johnmyleswhite** [comment]
@MSYoon: Please keep in mind that it's disrespectful to ask usage questions here when we've previously asked you not to do so.
