### ISSUE TITLE
Figure out what needs to be done for threads on power

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#17822]
Given that Power is quite different than x86, we need to figure out what the plan is for threading on Power. Specifically:

1. What changes are needed in Julia
2. What changes are needed upstream in LLVM

Currently, we get this:

````
    JULIA test/threads
     * threads              Warning: threaded loop executed in order
LLVM ERROR: Cannot select: 0x1000f4d6930: i32,ch = AtomicLoadMin<Volatile LDST2[%72]> 0x1000f5c0280, 0x1000f4896f0, 0x1000f4bc970
  0x1000f4896f0: i64,ch = load<LD8[%71](tbaa=!"jtbaa_immut")> 0x1000d9c3d30, 0x1000f5f35b0, undef:i64
    0x1000f5f35b0: i64 = add 0x1000f4d7f30, Constant:i64<8>
      0x1000f4d7f30: i64,ch = CopyFromReg 0x1000d9c3d30, Register:i64 %vreg36
        0x1000f4d2f90: i64 = Register %vreg36
      0x1000f4bd550: i64 = Constant<8>
    0x1000f5bc850: i64 = undef
  0x1000f4bc970: i32 = AssertSext 0x1000f43bca0, ValueType:ch:i16
    0x1000f43bca0: i32,ch = CopyFromReg 0x1000d9c3d30, Register:i32 %vreg26
      0x1000f4d21e0: i32 = Register %vreg26
In function: julia_#45###_threadsfor#277_68968
````

**Comment by yuyichao** [comment]
> Given that Power is quite different than x86, we need to figure out what the plan is for threading on Power. Specifically:

Not really. The failure isn't threading specific and seems to be simply because llvm failed to emit atomic instruction. Can you reduce the test and figure out which ones are failing? (Looks like atomic load of i32? but I don't read the IR in this form very well.)

**Comment by ViralBShah** [comment]
@vtjnash and I looked at this and he said it was indeed atomic load. But when we commented the failing test, there was another similar one, and upon commenting that, another failure. So, it seems like a fair amount of work to figure out all the test cases.

**Comment by yuyichao** [comment]
That's why I said `which ones` ;-p If a atomic load of non-i128 is failing, I will certainly expect it to happen way more often.

I think the only thing to do here is to figure out which ones are failing (we do have many tests that requires atomic load so you could easily be seeing the same issue over and over again), trying to get the llvm ir, see if you can reproduce it with llc and report it to llvm or see if it is fixed on llvm 3.9/4.0.

**Comment by tkelman** [comment]
would compiler-rt maybe help?

**Comment by yuyichao** [comment]
I'd be surprised if the power chip doesn't have any atomic instructions. In any case, no it shouldn't use compiler-rt, it should at most look up the symbols [in the corresponding platform library](https://github.com/JuliaLang/julia/pull/16066).

**Comment by vchuravy** [comment]
With #18557 we are down to one test [1] failure for threads and missing support for `128-bit` atomics [2]. 

[1] https://github.com/JuliaLang/julia/pull/18557#issuecomment-247776481
[2] https://github.com/JuliaLang/julia/pull/16066#issuecomment-247847964

**Comment by ViralBShah** [comment]
IIUC,

1. #18557 includes an LLVM patch that we will upstream and fixes lowering of atomics on ppc. We may need IBM's help in getting it into 3.9.1 (perhaps).
2. There is still one test failure that you mention in [1] above.
3. We still need support for 128-bit atomics in LLVM, which is not yet addressed in #16066

**Comment by Keno** [comment]
> #18557 includes an LLVM patch that we will upstream and fixes lowering of atomics on ppc. We may need IBM's help in getting it into 3.9.1 (perhaps).

I believe that patch is already upstream, no?

**Comment by tkelman** [comment]
for trunk, but not on 3.9.0, right? so we'd have to go through the new bugzilla nominating process to get it backported to 3.9.1

**Comment by vchuravy** [comment]
The patch is in trunk and I will nominate it to be backported to 3.9.1.

With regards to 128bit support I found this quote in the llvm docs:

> LLVM will emit a call to an appropriate __sync_* routine if the target ISelLowering code has set the corresponding ATOMIC_CMPXCHG, ATOMIC_SWAP, or ATOMIC_LOAD_* operation to “Expand”, and if it has opted-into the availability of those library functions via a call to initSyncLibcalls().

See http://llvm.org/docs/Atomics.html#libcalls-sync and https://github.com/llvm-mirror/llvm/commit/238d8199af3459b8

In order to support 128bit atomics we will need to support these `__sync*` libcalls (see @yuyichao comment in https://github.com/JuliaLang/julia/pull/16066#issuecomment-247848542).

**Comment by vchuravy** [comment]
For the remaining test failure I have a minimal test-case and I was planning to open an issue about it after we merged #18557.

It seems to be an upstream llvm issue.

**Comment by vchuravy** [comment]
The remaining test failure is https://llvm.org/bugs/show_bug.cgi?id=30451

**Comment by ViralBShah** [comment]
When I run the threads test now with your recent Power PR, I get:
```
[viral@ibm-power2 julia]$ make test-threads
    JULIA test/threads
     * threads              Warning: threaded loop executed in order
LLVM ERROR: Program used external function '__atomic_store' which could not be resolved!
make[1]: *** [threads] Error 1
```
Is this expected and the LLVM bug above will fix this one?

**Comment by yuyichao** [comment]
Do you have `libatomic.so.*`? and does it provide the symbol?

**Comment by ViralBShah** [comment]
Where do I find that from? Is Julia supposed to build it or should the system provide it?

**Comment by ViralBShah** [comment]
I see it is a system provided library.

**Comment by ViralBShah** [comment]
````
[viral@ibm-power2 julia]$ nm /usr/lib64/libatomic.so.1.0.0 
nm: /usr/lib64/libatomic.so.1.0.0: no symbols

[viral@ibm-power2 julia]$ nm /usr/lib/gcc/ppc64le-redhat-linux/4.8.2/libatomic.a | grep store
nm: init.o: no symbols
gstore.o:
0000000000000000 T __atomic_store
0000000000000000 T libat_store
                 U libat_store_1
                 U libat_store_16
                 U libat_store_2
                 U libat_store_4
                 U libat_store_8
store_1_.o:
0000000000000000 T __atomic_store_1
0000000000000000 T libat_store_1
store_2_.o:
0000000000000000 T __atomic_store_2
0000000000000000 T libat_store_2
store_4_.o:
0000000000000000 T __atomic_store_4
0000000000000000 T libat_store_4
store_8_.o:
0000000000000000 T __atomic_store_8
0000000000000000 T libat_store_8
store_16_.o:
0000000000000000 T __atomic_store_16
0000000000000000 T libat_store_16
````

**Comment by vchuravy** [comment]
What does your `LD_LIBRARY_PATH` look like?

```
[valentin@ibm-power2 julia]$ nm -D /usr/lib64/libatomic.so.1 | grep store
0000000000001ef0 T __atomic_store
00000000000030c0 T __atomic_store_1
00000000000057a0 T __atomic_store_16
0000000000003c00 T __atomic_store_2
0000000000004750 T __atomic_store_4
0000000000004fb0 T __atomic_store_8
```

**Comment by yuyichao** [comment]
Also note that it's illegal to link to the static library or compile the static library into a shared one unless the whole application is statically linked.

**Comment by vchuravy** [comment]
@ViralBShah I could reproduce your issue when doing a completely clean rebuild with only cmake on my path instead of using gcc 4.9.4. It seems I had a `libatomic.so.1.1.0` on my `LD_LIBRARY_PATH` while testing #18557

**Comment by ViralBShah** [comment]
That's awesome to have multi-threading working fully with the workarounds!
