### ISSUE TITLE
Strange interaction between return and try/finally

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#1784]
Discovered through https://github.com/toivoh/Debug.jl/issues/30 :
It seems that `try/finally` doesn't like that you leave the try block using `return`.
Sometimes it gives a syntax error, as in

    julia> let
               try
                   return 5
               finally
                   println("exiting")
               end                   
           end
       
    syntax error: misplaced return statement at line 3

Sometimes, it just bypasses the `finally` block, as in

    julia> let
               try
                   return 5
                   3
               finally
                   println("exiting")
               end                   
           end
       
    5

To my mind, both of these examples should print out `"exiting"`, and then return the value 5.

The reason that I bring this up is because [Debug.jl](https://github.com/toivoh/Debug.jl) wraps each scope block in a `try/finally` to make sure to capture when you leave a block, e.g. for step over/out. If the fix is nontrivial, is there some way to work around this issue in the meantime?

**Comment by stevengj** [comment]
This does not seem fixed yet:
```jl
function foo()
    (a,b) = try
        return true
        (0,1)
    finally
        println("exiting")
    end
end
```
gives `LoadError: syntax: misplaced return statement` in `master`.

**Comment by yuyichao** [comment]
Seems fixed now?

```jl
julia> function foo()
           (a,b) = try
               return true
               (0,1)
           finally
               println("exiting")
           end
       end
foo (generic function with 1 method)

julia> foo()
exiting
true
```

**Comment by tkelman** [comment]
add a test?

**Comment by JeffBezanson** [comment]
Possible this was fixed by my front-end redesign.
