### ISSUE TITLE
deepcopy bug

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#17853]
deepcopy creates unnecessary copies of bits type arrays if they are referred multiple times:

```
julia> a = [1,2,3]
 3-element Array{Int64,1}:
  1
  2
  3

 julia> b = Any[a,a]
 2-element Array{Any,1}:
  [1,2,3]
  [1,2,3]

 julia> b[1]===b[2]
 true

 julia> c = deepcopy(b)
 2-element Array{Any,1}:
  [1,2,3]
  [1,2,3]

!julia> c[1]===c[2]
 false
```

The issue can be fixed by modifying deepcopy.jl:59: instead of `return copy(x)`, it should say `return (stackdict[x]=copy(x))`.

A similar issue exists for immutable types on line 44, I believe we need one more `stackdict[x]=y` there.

**Comment by JeffBezanson** [comment]
The array issue has been fixed for 0.5.

Could you give an example of the other issue?

**Comment by yuyichao** [comment]
This shouldn't be an issue for immutables?

**Comment by denizyuret** [comment]
Example for the immutable issue:
```
julia> immutable foo; a; b; end

 julia> x=foo([1,2],3)
 foo([1,2],3)

 julia> a = Any[x,x]
 2-element Array{Any,1}:
  foo([1,2],3)
  foo([1,2],3)

 julia> a[1]===a[2]
 true

 julia> b = deepcopy(a)
 2-element Array{Any,1}:
  foo([1,2],3)
  foo([1,2],3)

!julia> b[1]===b[2]
 false
```

**Comment by JeffBezanson** [comment]
That is actually just the same `Array` problem again, so it is also fixed.
