### ISSUE TITLE
Restrict field type in composite types.

### ISSUE THREAD

**Issue by dylandbay** [JuliaLang/julia#17850]
Is there an easy way to restrict field types in composite types?
For example, I would like to define a Binary Search Tree.
```
type bst{T}
    parent::T
    left::Union{bst{T}, Void}
    right::Union{bst{T}, Void}
end

t = bst(10, bst(5, nothing, nothing), bst(15, nothing, nothing))
```
I would like to restrict the type of `parent` so that it can't be `nothing` or `bst`.
It would be even better if I can specify somehow that `left.parent` <= `parent` <= `right.parent`

It can be implemented like this (sort of):
```
type bst
    parent
    left::Union{bst, Void}
    right::Union{bst, Void}
    
    function bst(parent, left, right)
        if parent == nothing
            error("Parent cannot be nothing.")
        elseif typeof(parent) <: bst
            error("Parent cannot be a bst.")
        elseif typeof(left) == bst && left.parent > parent
            error("Left child is larger than parent.")
        elseif typeof(right) == bst && right.parent < parent
            error("Right child is smaller than parent.")
        else
            new(parent, left, right)
        end
    end
end
t = bst(10, bst(5, nothing, nothing), bst(15, nothing, nothing))
```
I can't figure out how to make this parametric though.

Is it possible to do the above without defining `bst(parent, left, right)`?

**Comment by johnmyleswhite** [comment]
Please post usage questions to julia-users.

**Comment by dylandbay** [comment]
It seems like it's part of the type system, isn't it? 
For `parent`, I want to be able to specify something like `parent::Difference{Any, Union{bst, Void}}`.
As for `left.parent` <= `parent` <= `right.parent`, isn't this dependent typing? Or am I mistaken? I'm not that familiar with dependent types.

**Comment by timholy** [comment]
GitHub is for reporting bugs or making improvements; the mailing list is great for questions. (So is the manual, see the chapter on types.)

**Comment by vtjnash** [comment]
> It seems like it's part of the type system, isn't it? 

that's true of some type systems, but not all. Julia's type system is less about enforcing correctness and more about optimization
