### ISSUE TITLE
Need .exe for CMAKE_C_COMPILER on Windows

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#17867]
I am trying to build julia on Windows with MSYS2 and had problems that CMAKE complained that the path it got for `CMAKE_C_COMPILER` was not a valid path to a compiler. It worked when I added a `.exe` to this line: https://github.com/JuliaLang/julia/blob/ec15da730a5b25431d3cfcdc04e3451a9f3e400e/deps/Makefile#L54. I know nothing about build stuff so would doing that on Windows be correct?

**Comment by tkelman** [comment]
what cmake version are you using, and where did you install it from? I don't recommend using msys2, we don't use it for building the binaries, only on appveyor which is a weird configuration.

**Comment by KristofferC** [comment]
Cmake 3.6.1 installed with the Windows installer from the homepage. From reading the building docs I did not get the impression that msys2 was not recommended and after adding the `.exe` everything went smoothly.

I tried with cygwin first but ran into https://groups.google.com/forum/#!msg/julia-dev/7svmmaXLvy4/cQ-rkwmtCAAJ;context-place=forum/julia-dev which I did not find a way to work around.

**Comment by tkelman** [comment]
Yeah, I need to reorder those docs, and probably move appveyor over to use cygwin-cross so we don't have to pretend to support msys2 at all.

With the cmake error without the .exe, could you gist a full log and error message? Adding the .exe would only be valid if `BUILD_OS` is Windows (or cygwin I suppose, but it's working fine there without).

On the cygwin problem, can you run the commands from these lines and see what they say? `CROSS_COMPILE` should be `x86_64-w64-mingw32-`. https://github.com/JuliaLang/julia/blob/9c214520b49d5dd7e7d7da2bb8dbbc8bcc26cdfe/Make.inc#L258-L261
