### ISSUE TITLE
I get ERROR: LoadError: UndefVarError: input not defined when I try to run the .jl file from the julia terminal

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [JuliaLang/julia#17877]
Hello,
I am a beginner in the Julia language .. 
I get this error while I try to run ****.jl Julia program file from the terminal. However It works perfectly fine in the Juno IDE. This following is the error message I receive while trying to run the program from the Linux terminal:

ERROR: LoadError: UndefVarError: input not defined
in legacy at /home/rishabh/Desktop/ProjectJulia/juliatest.jl:120
while loading /home/rishabh/Desktop/ProjectJulia/juliatest.jl, in expression starting on line 138

Thanks In advance
![screenshot from 2016-08-07 23-56-02](https://cloud.githubusercontent.com/assets/17016085/17464394/ece3840c-5cfa-11e6-893a-3129e226e0e9.png)

**Comment by KristofferC** [comment]
https://groups.google.com/forum/m/#!forum/julia-users is the place to ask usage questions. People will be happy to help you there.

**Comment by Rishabh-Raghunath** [comment]
Ohh .. Thank You
