### ISSUE TITLE
Wrong paths for `less` on windows

### ISSUE THREAD

**Issue by geekyI** [JuliaLang/julia#17872]
```
julia> less(sin,(Int64,))
ERROR: could not spawn `less +139g 'C:\Users\XXX\AppData\Local\Julia-0.4.6\bin\../share\julia\base\math.jl'`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```
Note the forward slash in `../share`

**Comment by TotalVerb** [comment]
Forward slash is probably a red herring, as @ChrisRackauckas replaced it with a backward slash, and the problem persisted.

Also, ```run(`less`)``` fails with the same error on Windows. Probably `less` needs to be bundled with Julia?

**Comment by geekyI** [comment]
There are 2 bugs in this, just changing the pager doesn't work:
```
julia> ENV["PAGER"] = "more"
"more"

julia> less(sin,(Int64,))
Invalid parameter - /share\julia\base\math.jl
```

**Comment by pfitzseb** [comment]
`more /h` tells us that the line number needs to be specified without the `g`. The forward slash is no problem in principle, as long as the path is properly quoted (which it isn't).

If the command is constructed as
```julia
Cmd(`more +$(line) \"$(file)\"`, windows_verbatim = true)
```
[here](https://github.com/JuliaLang/julia/blob/bc4eba5826f424b0734c9335cbe117c4112869a7/base/interactiveutil.jl#L75), `@less` works.

**Comment by geekyI** [comment]
Yeah, omitting out the 'g' at least doesn't produce an error anymore when I
manually enter the command. Will test when I have more time
