### ISSUE TITLE
Currently no way of downloading a Julia 0.5 binary

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#17881]
There seems to be now way to download a Julia 0.5 binary at the moment. The stable releaser binary is Julia 0.4.6, while the nightly build binary is Julia 0.6.

**Comment by KristofferC** [comment]
https://groups.google.com/forum/#!topic/julia-users/shrnNHpyliA

**Comment by ChrisRackauckas** [comment]
It should still be on the website someone.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julialang.github.com then?

**Comment by ChrisRackauckas** [comment]
Yes.

**Comment by baggepinnen** [comment]
The binary from the google groups page worked fine for me. Am I supposed to be able to install different binaries from the https://github.com/JuliaLang/julialang.github.com link?

**Comment by KristofferC** [comment]
I just meant that is the repo for the website.

**Comment by ChrisRackauckas** [comment]
You (or someone else) should open a pull request which adds links to the release candidates on that repo.

**Comment by ViralBShah** [comment]
I would wait to hear from @tkelman on what the process is.

**Comment by tkelman** [comment]
did we add links to the release candidates to the website last time?

**Comment by ararslan** [comment]
I believe so; I distinctly remember downloading the dmg for a 0.4-rc and I don't know where else I would have gotten it.

**Comment by andreasnoack** [comment]
https://github.com/JuliaLang/julialang.github.com/blob/03e19bfd865b6257acb6f0b30ef45778c4057161/downloads/index.md

**Comment by ararslan** [comment]
I put up a PR on the Julia website repo to add links to the 0.5-rc binaries.
