### ISSUE TITLE
Better handling of libgit2 related USE_SYSTEM_*

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#17884]
The USE_SYSTEM_* options related to libgit2's ssh/proxy handling roughly works but it seems that they can be handled better/more precisely. A few issues I've noticed,

1. IIUC mbedtls (and libssh2?) is (are) not used directly but only as dependencies of libgit2. Therefore, when the system version of `libgit2` is used, these dependencies shouldn't be built.

2. USE_SYSTEM_MBEDTLS without USE_SYSTEM_CURL does not work (mbedtls is built).

@tkelman

**Comment by ViralBShah** [comment]
If libgit2 is SYSTEM, then neither of libcurl, libmbedtls or libssh2 should be built.
