### ISSUE TITLE
RPATH issue with bundled CURL binary

### ISSUE THREAD

**Issue by helgee** [JuliaLang/julia#17889]
I tried to use the bundled curl binary to simplify the `download` function and in the process get rid of this warning:

> Note that this function relies on the availability of external tools such as curl, wget or fetch to download the file and is provided for convenience. For production use or situations in which more options are needed, please use a package that provides the desired functionality instead.

But the bundled curl fails on OSX with the following error message:

``` bash
dyld: Library not loaded: @rpath/libssh2.dylib
  Referenced from: /Users/helge/projects/julia/usr/bin/../tools/curl
  Reason: image not found
```

**Comment by ViralBShah** [comment]
I never tried doing that. If we want to use the bundled curl for `download`, which I very much like the idea of, we will also have to turn on building curl on windows. There are many other benefits to having curl and libcurl available by default on all platforms.

Despite that, we should certainly fix the rpath issue.

**Comment by Keno** [comment]
I thought we've generally not been shipping tools. Of course if we're shipping libcurl, also shipping the binary is not too far a stretch. However, there is the concern that libgit2 may drop curl as a dependency, in which case we'd end up either being stuck shipping something that's not actually a dependency.

**Comment by ViralBShah** [comment]
Is that a real possibility?

**Comment by Keno** [comment]
Yes, libcurl is only used for proxy support as you know, which is not that hard to implement.

**Comment by tkelman** [comment]
The libgit2 maintainers have expressed a desire to stop using libcurl in a few places.

**Comment by tkelman** [comment]
We should improve Base.download in a number of ways, but that's too big in scope to try rushing into 0.5 rc's right now. On Windows I don't think we absolutely need curl since we can get a lot of the same functionality built in via powershell, it's just a question of what would we rather write: build-system code to get curl building and shipped on Windows, or Windows specific powershell interface code.

**Comment by helgee** [comment]
`ccall`ing into libcurl would also be an option and should not be too difficult. But if it goes away that does not help of course...

**Comment by tkelman** [comment]
See https://github.com/JuliaWeb/LibCURL.jl which isn't as widely used as Requests / HttpParser within JuliaWeb. http-parser is a dependency if libgit2 that is less likely to go away, but the current way it builds gets vendored and built into libgit2. If we split it out to build as a separate library, then JuliaWeb could use it a bit easier.

**Comment by ViralBShah** [comment]
Cc @amitmurthy

**Comment by JeffBezanson** [comment]
Covered by #27043. Also resolving this by bundling `curl` everywhere does not seem likely.
