### ISSUE TITLE
Resizing console window on Win10 Anniversary update deletes all julia output

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17894]
I start a PowerShell instance, then start julia (0.4.6) from there. Then I do a `Pkg.update()` with lots of output. If I resize the console window while the command is still executing, it will a) delete all existing output and b) any future output from that command is also not shown. What does get shown is the green julia prompt once the command has executed. I end up with a console window that shows the green julia prompt at the bottom, and everything else is just black. When I scroll up, there is nothing there either, all just blank output.

**Comment by tkelman** [comment]
I see strange things happen when I resize a cmd window, but the prompt does eventually come back there. Not coming back looks specific to running in powershell.

**Comment by davidanthoff** [comment]
Sorry, I might not have been clear: the prompt is coming back, but all the other output is gone...

**Comment by tkelman** [comment]
I think what you're seeing is specific to the old libuv version on 0.4 writing a black background over everything, ref #16278

**Comment by davidanthoff** [comment]
On julia 0.5, starting julia directly (not via PowerShell), resizing the window during a ``Pkg.update()`` also deletes all previous output. It does show any new output after the resizing, but the first line is then indented incorrectly:

![image](https://cloud.githubusercontent.com/assets/1036561/17491651/58fdb56a-5d5d-11e6-91e9-ad665a15adaf.png)

**Comment by KristofferC** [comment]
Please comment if this is still an issue.

**Comment by davidanthoff** [comment]
Not seen this in years.
