### ISSUE TITLE
append!([1,2], [3]) should result in [1,2,[3]]

### ISSUE THREAD

**Issue by dylandbay** [JuliaLang/julia#17914]
Now that Julia 0.6 supports nested arrays so that `[1,[2,[3]]]` is different from `[1,2,3]`, it seems like `append!([1,2], [3])` should result in `[1,2,[3]]` instead of `[1,2,3]`.  

Python's approach seems more consistent. Maybe another function called `extend!` should be implemented where `extend!([1,2], [3])` will result in `[1,2,3]`.

Basically, `append!` treats the second argument as an element and adds it to the first argument which is an array. `extend!` treats both arguments as arrays and concatenates them. It throws an error if either argument is not an array.

**Comment by KristofferC** [comment]
It seems that you want `push!`. `append!` is your `extend!`.

```jl
julia> a = Any[1,2]
2-element Array{Any,1}:
 1
 2

julia> push!(a, [3])
3-element Array{Any,1}:
 1   
 2   
  [3]
```

**Comment by dylandbay** [comment]
Oh that was embarrassing. Sorry about that. I got confused because `append!([1,2], [3])` has the same result as `append!([1,2], 3)`

**Comment by StefanKarpinski** [comment]
@dylandbay: that's due to the fact that scalars are iterable and act like 0-dimensional collections of themselves. There's been a fair amount of discussion of changing this since it's confusing and often leads to hard-to-find bugs.

**Comment by KristofferC** [comment]
`for i in length(x)` anyone?
