### ISSUE TITLE
No method matching `*(::Array{Float32,1}, ::SubArray{Float32,1,Array{Float32,2},Tuple{Int64,Colon},true})`

### ISSUE THREAD

**Issue by lopezm94** [JuliaLang/julia#17924]
This is happening on nightly, not on `0.4`.

More info of the error [here](https://travis-ci.org/JuliaLang/IterativeSolvers.jl/jobs/141523848#L802).

**Comment by andreasnoack** [comment]
Please paste a reproducible example in the issue if possible.

**Comment by andreasnoack** [comment]
It's the new slicing behavior on 0.5. `sub(A,m,:)` is now a vector so you'll need to change [this line](https://github.com/JuliaLang/IterativeSolvers.jl/blob/2b3b9b9a5cc3324637b9a919b7d67eea27f379f1/src/svdl.jl#L532) to something like `view(A,m:m,:)`.
