### ISSUE TITLE
setrounding regression for 0.5.0-rc1

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17926]
Taken from a [rounding mode example](http://docs.julialang.org/en/latest/manual/integers-and-floating-point-numbers/#rounding-modes) in the manual:

Julia 0.4.6

``` julia
julia> with_rounding(Float64,RoundDown) do
           1.1 + 0.1
       end
1.2

julia> 1.1 + 0.1
1.2000000000000002
```

Julia 0.5.0-rc1

``` julia
julia> setrounding(Float64,RoundDown) do
           1.1 + 0.1
       end
1.2000000000000002

julia> 1.1 + 0.1
1.2000000000000002
```

**Comment by omus** [comment]
Looks to be that the example function is being optimized:
```julia
julia> x = 0.1
0.1

julia> setrounding(Float64,RoundDown) do
           1.1 + x
       end
1.2
```

**Comment by Keno** [comment]
I suspect this is LLVM inlining and constant folding. LLVM doesn't model rounding modes, so there is very little we can do.

**Comment by omus** [comment]
Makes sense. I guess the best course of action would be to update the manual to have a more complicated but working example.

**Comment by simonbyrne** [comment]
That's not good: previously we relied on the fact that anonymous functions weren't really optimised. Now that they are, I'm not sure what we can do until LLVM get around to allowing rounding mode changes (I wouldn't hold your breath...).

We should probably stick some warnings in there, and mark it as an experimental feature.

**Comment by yuyichao** [comment]
IIUC constant folding are usually done at default rounding mode. I don't think it's possible to know the right rounding mode anyway unless we disable **all** constant folding for floating point numbers since the rounding mode is a runtime setting.

**Comment by simonbyrne** [comment]
Could we have a meta tag that would disable constant folding?

**Comment by yuyichao** [comment]
`@noinline`

**Comment by simonbyrne** [comment]
Doesn't that just disable constant folding at definition time? How could I use it in the above example?

**Comment by yuyichao** [comment]
`@noinline f() = 1.0; f() + 1.1`

**Comment by yuyichao** [comment]
I just mean that `@noinline` is the only reliable optimization barrier we have and is likely to stay for some time.

**Comment by simonbyrne** [comment]
So one option is that we could change it to a macro which pulls out all the literals into a `@noinline` call, i.e.
```julia
@setrounding Float64 RoundDown 1.1 + 0.1
```
transforms to
```julia
@noinline syms() = (1.1,0.1)
old = rounding(Float64)
setrounding(Float64, RoundDown)
a,b = syms()
a+b
setrounding(Float64, old)
```

**Comment by simonbyrne** [comment]
Although that won't work with `const`s...

**Comment by dpsanders** [comment]
Ouch. This sounds like it will seriously break ValidatedNumerics.jl.
Why did this not get picked up by the Julia test suite?

**Comment by KristofferC** [comment]
How did it not get picked up by your test suite? :P

**Comment by dpsanders** [comment]
Apparently because we never have literals, everything that gets rounded comes out of an Interval object.

**Comment by tkelman** [comment]
I guess our rounding-mode tests aren't as comprehensive as they could be? That doc example was also not a doctest, but if it had been we likely would have noticed sooner.

**Comment by simonbyrne** [comment]
`setrounding` has now been deprecated: #27166
