### ISSUE TITLE
reading invalid text data, other encodings

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#1792]
We probably need to change 1 or 2 behaviors when reading invalid data or unknown encodings. There are two cases: `Char`, and things like `readuntil`/`readline`.

`readuntil` can be reasonably defined in terms of bytes: just read everything until a certain value. This is good because then you can at least get the data without explicit support for every encoding. Currently we might return an invalid `UTF8String`, from which you can get the (unaltered) data. I don't know whether that is the best approach. Maybe there should be a lower-level routine that returns a byte array. We also need functions that do the same for different fixed-width encodings (16-bit, 32-bit).

Reading a `Char` I don't think can be done reasonably without knowing the encoding. The best immediate change I can think of is to give an error for invalid data while trying to read a UTF-8-encoded Char.

**Comment by nalimilan** [comment]
An update on this old issue for people who might end up here: all string types are going to be replaced with a single `String` type stored in UTF-8 (https://github.com/JuliaLang/julia/pull/14383). I've just created a package to convert text from/to different encodings: https://github.com/nalimilan/StringEncodings.jl. Finally, additional string types storing data in arbitrary encodings will likely be supported in another package (or maybe in StringEncodings.jl).

So I'd say this issue can be closed.

**Comment by tkelman** [comment]
subsumed by #16107
