### ISSUE TITLE
Accuracy error on BLAS operations

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#17937]
@tkelman noticed a particular OpenBLAS error that occurred on Windows, Linux and Mac. The answer is supposed to be 1.0, but I get different answers. 
Here's the Windows bug: 
```
julia> n = 31
31

julia> a = ones(Float32, 2^n,1); b = a' * a; b/2^n
1×1 Array{Float32,2}:
 0.9

julia> versioninfo()
Julia Version 0.6.0-dev.62
Commit d3df8e7 (2016-08-07 02:31 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
On Mac OSX: 
```
julia> n = 32
32

julia> a=ones(Float32,2^n,1); b=a'*a; b/2^n
1×1 Array{Float32,2}:
 1.16667

julia> versioninfo()
Julia Version 0.5.0-rc1+0
Commit cede539 (2016-08-04 08:48 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
On Linux: 
```
julia> n = 32
32

julia> a = ones(Float32, 2^n,1); b = a' * a; b/2^n
1×1 Array{Float32,2}:
 1.16667

julia> versioninfo()
Julia Version 0.6.0-dev.142
Commit 3f6b2b2 (2016-08-10 07:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```
Is this a possible OpenBLAS bug?

**Comment by ranjanan** [comment]
cc: @xianyi

**Comment by andreasnoack** [comment]
Two things

1. On Windows `n=31` but on the other platform it's `n=32`.
2. Isn't this error within what to expect? Id' actually expect a larger error since
```jl
julia> eps(Float32(length(a)))
512.0f0
```

**Comment by tkelman** [comment]
the 0.9 and 1.16 are ratios. rounding error shouldn't be that far off

**Comment by vtjnash** [comment]
I agree with Andreas that I would have expected a larger error after 2^32 sums. Our compensated `sum` gets the right answer :), but it seems `dot` is further off?

```
julia> dot(a, a)
5.368709f8

julia> ans/length(a)
0.125f0
```

**Comment by andreasnoack** [comment]
When `eps` becomes larger than one adding more ones doesn't have an effect and there is still quite a bit of room left, i.e.
```jl
julia> x = Float32(2^24);

julia> x + 1 == x
true

julia> realmax(x)/x
2.0282408f31
```

**Comment by tkelman** [comment]
why would it overcount though? and it gets the right answer until it gets into needing ILP64 indices. the ratio is the same for Float64 where precision should be fine, it just takes twice as much memory to reproduce.

**Comment by andreasnoack** [comment]
Depending on the chunk sizes used in OpenBLAS you can have round ups, e.g.
```jl

julia> x = Float32(2^25);

julia> eps(x)
4.0f0

julia> x + 2 == x
true

julia> x + 3 == x
false

julia> (x + 3 + 3 + 3 + 3)/(x + 12)
1.0000001f0
```
Also, MKL has similar behavior.

**Comment by tkelman** [comment]
does MKL get these wrong by 10+ % ? Even in Float64 where these should be exact?

This smells like an ILP64 specific bug to me because of the cutoff where it starts happening.

**Comment by andreasnoack** [comment]
Here is MKL
```jl
julia> n = 31; m = 2^n - 1; ones(Float32, m, 1) |> t -> (t't)[1]/m
1.0f0

julia> n = 32; m = 2^n - 1; ones(Float32, m, 1) |> t -> (t't)[1]/m
0.5f0
```
