### ISSUE TITLE
Type inference error with inlining on

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#17934]
Reduced from a segfault reported by @davidagold 

``` jl
immutable Wrap{T}
    v::T
end
eltype2{T}(::Type{Wrap{T}}) = T
eltype2(::Type{Wrap}) = Any

abstract AbstractA{T,N}
immutable NullableA{T,N} <: AbstractA{Wrap{T},N}
    v::Array{T,N}
end

function similar2{T}(a::AbstractA{T})
    NullableA(Array{eltype2(T)}(3))
end
function copy2(tbl)
    similar2(tbl.x)
end

typealias NullableV{T} NullableA{T, 1}
immutable B
    x::NullableV
end
tbl = B(NullableA([4, 5, 6]))
new_tbl = copy2(tbl)
ccall(:jl_, Void, (Any,), new_tbl)
```

`new_tbl` is `Main.NullableA{Any, 1}(v=Array{Any, 1}[#<null>, #<null>, #<null>])` with inlining on and `Main.NullableA{Int64, 1}(v=Array{Int64, 1}[0, 0, 0])` (correct type) with inlining off on both 0.4 and 0.5. A slightly different/more complex version returns `Main.NullableA{Any, 1}(v=Array{Int64, 1}[0, 0, 0])` which is invalid which is what causing the original segfault.

One of the issue seems to be the `eltype2`, it seems that the type inference is using the wrong definition (there's a method error if the `eltype(::Type{Wrap})` definition is removed sometimes)

**Comment by vtjnash** [comment]
would this have been solved by merging https://github.com/JuliaLang/julia/pull/12604?

**Comment by KristofferC** [comment]
Is this fixed?

```jl
julia> ccall(:jl_, Void, (Any,), new_tbl)
Main.NullableA{Int64, 1}(v=Array{Int64, 1}[140041395332848, 140041327695568, 140041327788304])
```

**Comment by yuyichao** [comment]
Likely fixed by jb/subtypes.
