### ISSUE TITLE
`make` dumps a bunch of curl and libgit2 garbage on every build

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#17938]
I now get several screens of output from `make` even when julia is fully up to date.

**Comment by tkelman** [comment]
mind posting a gist?

**Comment by timholy** [comment]
https://gist.github.com/timholy/23213a4ad79873e241cfd0bf4e3d7219

**Comment by timholy** [comment]
And I get exactly the same thing if I immediately issue `make` again.

**Comment by tkelman** [comment]
what distro and cmake version? this is potentially the same curl build isolation issue that I've been meaning to fix but have been distracted the last few days

**Comment by vtjnash** [comment]
`CURL_SRC_TARGET` is wrong, it's missing an extra `/lib/` in the path (these issues with getting curl working are why my PR does away with the `touch`es entirely)

**Comment by timholy** [comment]
Sorry @tkelman, I missed your question. This is (K)Ubuntu 16.04 with cmake 3.5.1. I should say this started happening after I had (1) updated julia, (2) added a Make.user file to experiment with Cxx.jl, and (3) installed a whole heap of packages to try to build ArrayFire on my machine. I did all these things basically at once, so I'm not sure what is to blame.

For reference,
```jl
$ cat Make.user 
override BUILD_LLVM_CLANG=1
override USE_LLVM_SHLIB=1
# Optional, but recommended
override LLVM_ASSERTIONS=1
```
I'm a little reluctant to just test now what happens when I get rid of `Make.user` since it seems to be preparing to rebuild LLVM for me when I do that. If it would be useful to do so, I can try it when I'm preparing to be away from the keyboard for an hour or so.

**Comment by tkelman** [comment]
I can reproduce this so probably no need. It sounds like a potentially simple fix but I can't test until later today.

**Comment by tkelman** [comment]
possibly fixed by https://github.com/JuliaLang/julia/commit/e4b5233568d6b98b17dffbdc953f2878d2110b3e ?
