### ISSUE TITLE
Expression `Int{}` should be an error

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17943]
`Int` is not a type constructor, hence defining additional type parameters doesn't make sense.

**Comment by StefanKarpinski** [comment]
One can argue that concrete types as zero-parameter type constructors.

**Comment by eschnett** [comment]
Yes, though that's similar to arguing that scalars are 0d arrays, or that constants are functions that don't take arguments. I don't think it's a good thing. For example, Julia does make a distinction between `Tuple` and `Tuple{}`, so the empty curlies are not always a no-op.

I wrote up some thoughts about this a few weeks ago <https://eschnett.github.io/julia/2016/06/23/some-thoughts-on-generic-programming-in-julia>.

**Comment by JeffBezanson** [comment]
I think this can be handled in #8974. It will only be valid to do type application with UnionAll types (plus Tuple and Union as special cases), whereas now the meaning of `A{}` is fuzzier.

**Comment by JeffBezanson** [comment]
closed by #18457
