### ISSUE TITLE
Reserve keyword(s) for future trait-system now?

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#17942]
Would it make sense to reserve keyword(s) now which maybe used in the future for traits?  Doing this now would have them reserved in 1.0. Depending on the details, adding traits could then even be a non-breaking change.

If so, the question is which keyword(s). Previously discussed candidates are `trait`, `protocol`, and `interface`.  To get first dips on the bikeshed: I think `trait` is nicer than the other two, and shorter for sure.

**Comment by eschnett** [comment]
We also discussed `concept` (C++) and `typeclass` (Haskell).

**Comment by StefanKarpinski** [comment]
It's hard to pick a name before the thing is done and designed.

**Comment by MikeInnes** [comment]
Possible Solutions:

* Call it "Feature X" and simply reserve `x` as its keyword
* Reserve a large number of vague, non-specifc keywords (`floop`, `maugre`, `ebrious`) and use them for whatever we want after 1.0

**Comment by mauro3** [comment]
Whilst there is no guarantee, chances are that the trait design will work with just one extra keyword (+some other extra syntax).
