### ISSUE TITLE
Fully qualified names for subtypes

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaLang/julia#17944]
### Proposal

Having fully qualified subtype names would be a great feature to support the reuse of names that represent similar concepts, yet are still dependent on context, and to provide protected scoped namespaces . This would have applications to topics such as improving support for enumerations, and asynchronous data sources.

This would make typealias a powerful tool for simplifying syntax. For example for Int64, provided none of the abstract types have been aliased

```
immutable Int64 <: Signed <: Integer <: Real <: Number
    ...
end
typealias Int64 Number:>Real:>Integer:>Signed:>Int64
```
### Example Use Case

Consider building data readers from cloud sources. We would want to start with something like:

```
abstract Cloud
```

But each cloud source has different specifications for the fields in their states, so we would want: 

```
abstract Amazon <: Cloud
typealias Amazon Cloud:>Amazon

abstract Google <: Cloud
typealias Google Cloud:>Google 
```

However, even though the specific fields may be different in the composite types we will use to represent state it would be great to be able to write:

```
type Connect <: Amazon
    ...
end
immutable Pending <: Amazon
    ...
end
immutable Output <: Amazon
    ...
end

type Connect <: Google
    ...
end
immutable Pending <: Google
    ...
end
immutable Output <: Google
    ...
end
```

The end goal is to put this in an iterator:

```
function start(x::Google:>Connect)
    ...
    Google:>Pending()
end
function next(x::Google:>Connect, y::Google:>Pending)
    ...
    (Google:>Output(),  Google:>Pending())
end
function done(x::Google:>Connect, y::Google:>Pending) = x.googleclosed || y.googleisempty

function start(x::Amazon:>Connect)
    ...
    Amazon:>Pending()
end
function next(x::Amazon:>Connect, y::Amazon:>Pending)
    ...
    (Amazon:>Output(),  Amazon:>Pending())
end
function done(x::Amazon:>Connect, y::Amazon:>Pending) = x.amazonclosed || y.amazonisempty
```

**Comment by vtjnash** [comment]
I don't fully follow, but doesn't seem like something needed
