### ISSUE TITLE
Do not download dependencies from insecure sources

### ISSUE THREAD

**Issue by DemiMarie** [JuliaLang/julia#17945]
Currently, Julia downloads dependencies from insecure connections in many cases (`http://` or `git://`).  This allows for a man-in-the-middle attack, resulting in total compromise of the developer's system.

The only solution is to ensure that all downloads are fetched via secure `https://` connections (with strict TLS certificate checking) and (ideally) have SHA512 hashes as well.

**Comment by JeffBezanson** [comment]
I believe we do have and check SHA512 hashes for all dependencies.

**Comment by StefanKarpinski** [comment]
Since we do SHA512 hash checks, I don't think the transport matters.

**Comment by Keno** [comment]
Correct, all dependencies are checked for integrity visa SHA512 hashes: https://github.com/JuliaLang/julia/tree/master/deps/checksums. The transport should not need to be encrypted.

**Comment by tkelman** [comment]
we could change any of the urls to https if that doesn't break anything, I doubt anyone would notice a difference. would have to remove the insecure/`-k` flag from `deps/tools/jldownload` too though.

**Comment by DemiMarie** [comment]
`objconv` is not checked.  Switching to an HTTPS URL fails with a certificate error.

**Comment by Keno** [comment]
Good catch! @vtjnash points out that objconv is the only dependency that's not versioned, so upstream changes frequently without warning. We probably need to rehost that particular download.

**Comment by ViralBShah** [comment]
Even though 99% of those building Julia probably receive their libraries from Yggdrasil, this should be easy enough to fix this and close.
```
➜  deps git:(master) grep http\: *
blas.mk:	$(JLDOWNLOAD) $@ http://www.netlib.org/lapack/$(notdir $@)
grep: checksums: Is a directory
dsfmt.mk:	$(JLDOWNLOAD) $@ http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/dSFMT-src-$(DSFMT_VER).tar.gz
mpfr.mk:	$(JLDOWNLOAD) $@ http://www.mpfr.org/mpfr-$(MPFR_VER)/$(notdir $@)
objconv.mk:	$(JLDOWNLOAD) $@ http://www.agner.org/optimize/objconv.zip
```

**Comment by ViralBShah** [comment]
dsfmt and lapack should be picked up from github. I'll check the others as well.
