### ISSUE TITLE
FFTW planner is not thread safe.

### ISSUE THREAD

**Issue by DrTodd13** [JuliaLang/julia#17972]
Having fft/bfft/ifft/etc. calls in a threaded region exposes the fact that the planning portion of the fft call is not thread-safe in fftw.  Below is a potential patch to dft.jl if you just want to lock the planner.

```
global planner_mutex = nothing

function __init__()
    global planner_mutex = Base.Threads.Mutex()
end

# implementations only need to provide plan_X(x, region)
# for X in (:fft, :bfft, ...):
for f in (:fft, :bfft, :ifft, :fft!, :bfft!, :ifft!, :rfft)
    pf = Symbol("plan_", f)
    @eval begin
        function $f(x::AbstractArray)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x)
            Base.Threads.unlock!(planner_mutex)
            the_plan * x
        end
        function $f(x::AbstractArray, region)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x, region)
            Base.Threads.unlock!(planner_mutex)
            the_plan * x
        end
        function $pf(x::AbstractArray; kws...)
            Base.Threads.lock!(planner_mutex)
            the_plan = $pf(x, 1:ndims(x); kws...)
            Base.Threads.unlock!(planner_mutex)
            the_plan
        end
    end
end
```

**Comment by JeffBezanson** [comment]
Could the lock acquisitions be pushed into the planning functions themselves --- i.e. just around the relevant ccalls?

**Comment by DrTodd13** [comment]
Yes, that is probably better.  Just those 4 ccalls in the for block on fft/FFTW.jl line 454.

**Comment by stevengj** [comment]
Yes, plan execution is thread-safe.

See also FFTW/fftw3#16: FFTW version 3.3.5 added a function [`fftw_make_planner_thread_safe ()`](http://fftw.org/doc/Thread-safety.html#index-fftw_005fmake_005fplanner_005fthread_005fsafe) that puts [a mutex lock](https://github.com/FFTW/fftw3/blob/a17d44eeb3100780ba106a22f497d47a43be7642/threads/threads.c#L471-L490) around the planner calls.   Maybe we should just use this instead?

**Comment by tkelman** [comment]
x-ref https://github.com/JuliaLang/julia/issues/16570 something about the way fftw uses mutexes is highly performance-sensitive to operating system versions, so we might want to avoid that or be careful about how we build it. Distro packagers might not be too happy with requiring a minimum version that's only been released for a few weeks.

**Comment by stevengj** [comment]
Note that you also need a lock on the finalizer, since `fftw_destroy_plan` is not thread-safe either.

**Comment by KristofferC** [comment]
FFTW is no longer in this repo: https://github.com/JuliaMath/FFTW.jl

**Comment by martinholters** [comment]
Open an issue there?

**Comment by KristofferC** [comment]
Good point, https://github.com/JuliaLang/julia/issues/17972.
