### ISSUE TITLE
map over BitArray cannot return different type

### ISSUE THREAD

**Issue by ninegua** [JuliaLang/julia#17970]
The following code used to work in 0.4 but now doesn't work in 0.5:

```
julia> f(a,b)=map(x->x?1:2, (a.==b))
f (generic function with 1 method)

julia> f([1,2,3],[3,2,1])
ERROR: InexactError()
 in convert(::Type{Bool}, ::Int64) at ./bool.jl:6
 in setindex! at ./bitarray.jl:554 [inlined]
 in map!(::##3#4, ::BitArray{1}, ::BitArray{1}) at ./abstractarray.jl:1423
 in f(::Array{Int64,1}, ::Array{Int64,1}) at ./REPL[262]:1
```

If the inner function returns `Bool` instead of `Int`, then it'll work.

**Comment by JeffBezanson** [comment]
cc @martinholters 

We're already dispatching based on functions known to return Bool, so we should also use that info to select whether to produce a BitArray or Array.

**Comment by martinholters** [comment]
There is `Predicate` used to indicate to `mapreduce_sc` that the passed function is pure and returns a `Bool` (as kind of a trait). We could rewrite `map` to behave like this:
```Julia
map(identity, trues(10)) # gives Array{Bool}
map(Predicate(identity), trues(10)) # gives BitArray
```
I'm not sure we want this, but if, then we probably shouldn't restrict this to the case where the input is a `BitArray`. E.g:
```Julia
map(==, ones(10), zeros(10)) # gives Array{Bool}
map(Predicate(==), ones(10), zeros(10)) # gives BitArray
```

I'd prefer to figure out the returned element type similar to `map`ping of `Array`s and using a `BitArray` iff it is `Bool` and the input(s) are `BitArray`(s), though.

**Comment by martinholters** [comment]
Or, better yet, we allow something similar to template specialization in C++ for types and make `Array{Bool}` equal to `BitArray`... :laughing:

**Comment by pabloferz** [comment]
> I'd prefer to figure out the returned element type similar to mapping of Arrays and using a BitArray iff it is Bool and the input(s) are BitArray(s), though.

I believe that should be doable. At least I have a possible way to implement this in mind.
