### ISSUE TITLE
Property assignment during incomplete immutable inner construction should warn or error

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaLang/julia#17976]
### Problem

Currently the following compiles without warning

```Julia
immutable ego
	id::ego
	function ego()
		superego = new()
		superego.id = superego
		superego
	end
end
```

However on instantiation the following error is generated:

```
> x = ego()
  > type is immutable
```

At the very least during compile this should generate a "Type will be inaccessible" warning, and possibly error out. As well this should be reflected in the documentation, which does not currently state that only mutable types can have properties assigned during incomplete inner construction. There is, however, a use case for supporting this construction.

### Example Use Case

Consider a generic merge-branching list. We can represent the terminal nodes as reflective branches:

```Julia
immutable MergeBranch{T}
    from::MergeBranch{T}
    to::MergeBranch{T}
    value::T
    MergeBranch{T}(value::T, from::MergeBranch{T}, to::MergeBranch{T}) = new{T}(from, to, value)
    function MergeBranch{T}(value::T, other::MergeBranch{T}, from::Bool)
        t = new{T}()
        t.value = value
        if from
            t.from = other
            t.to = t
        else
            t.from = t
            t.to = other
        end
        t
    end
    function MergeBranch{T}(value::T)
        t = new{T}()
        t.value = value
        t.from = t
        t.to = t
        t
    end
end
deletes{T}(value::T, from::MergeBranch{T}) = MergeBranch(value, from, true)
creates{T}(value::T, to::MergeBranch{T}) = MergeBranch(value, to, false)
edits{T}(value::T, from::MergeBranch{T}, to::MergeBranch{T}) = MergeBranch(value, from, to)
editof(me::MergeBranch) = me.from == me.from.to
editedby(me::MergeBranch) = me.to == me.to.from
created(me::MergeBranch) = me.from == me
deleted(me::MergeBranch) = me.to == me
```
The use of this would be, for example, as a representation of revision control system. Where an element that is "from" another element that is "to" itself represents one element "copied" from a deleted element. A chain of parents and children that all "know" each other represent an unbroken chain of edits. The values could store the traversal deltas in this example.

**Comment by JeffBezanson** [comment]
That use case looks very easy to rewrite in a way that avoids mutation, unless I'm missing something.

We don't generate compile time type errors. Consider for example

```
mutate(x::Any) = (x.value = 0)

immutable MergeBranch{T}
...
function MergeBranch{T}(value::T, other::MergeBranch{T}, from::Bool)
        t = new{T}()
        mutate(t)
end
end
```

The point is that it is not necessarily obvious that there is an attempt to mutate an immutable value, and would depend on compiler implementation details unless we switch to a full static type system.

For a similar reason, there is no special case for things happening "during incomplete inner construction". A constructor is just normal code.

We thought that by using `immutable` as the very keyword for defining immutable types it would be clear that they are immutable. Apparently we were wrong.

**Comment by aaronsheldon** [comment]
That sounds good. I can see the very good reasons for the design choice.

Unfortunately the documentation does currently imply that inner constructors do have some special behaviors, i.e. the existence of "new()", which is not normally available in other contexts; without explicitly stating the limitations of those behaviors. This leads to incorrect generalization when reading the documentation.

So could the exact constraints on the use of "new()" be reflected in the documentation? Even just a single sentence explaining that assignment to properties of immutables during incomplete initialization is not possible. In particular that self referential immutable types are not possible.

If you are going to design inner constructors to process as normal code, just like everything else, then you need to caveat the use "new()" carefully, as that is a deviation from what is available in normal code.

**Comment by JeffBezanson** [comment]
I don't see how this is a constraint on the use of `new`. It concerns
mutation, which is operating the same as it does everywhere else. But we
can certainly add a bit of clarification to the manual.

**Comment by aaronsheldon** [comment]
Great! Thank you!

I do appreciate that immutable roughly means assignment at the time of allocation, and mutability roughly means deferred assignment after allocation.
