### ISSUE TITLE
RNG not defined

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#17983]
`RNG` is exported but not defined in `Base.Random`. 

```
julia> Base.Random.RNG   # Tab completion...
ERROR: UndefVarError: RNG not defined
```

I'm assuming I should use `AbstractRNG` but like `IO` maybe the shorter name is preferable? Or just delete the export.

**Comment by tkelman** [comment]
> Or just delete the export.

Yeah, do that for now. Looks like it may have been missed in a past renaming. `AbstractRNG` is already exported.
