### ISSUE TITLE
Inconsistency between map, broadcast, and comprehension behavior in the empty case

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#17984]
#17847 changed the behavior of empty comprehensions such that, for example, `typeof(abs(Integer[]))` yields `Array{Any,1}` rather than `Array{Union{},1}`. As `@stevengj` points out in https://github.com/JuliaLang/julia/pull/17847#issuecomment-238744364, `broadcast` presently exhibits the prior empty comprehension behavior, for example `typeof(broadcast(abs, Integer[]))` yields `Array{Union{},1}`; `map`, however, exhibits the new empty comprehension behavior, for example `typeof(map(abs, Integer[]))` yields `Array{Any,1}`. Should `broadcast`'s behavior match that of `map` and comprehensions in the empty case? Also see https://github.com/JuliaLang/julia/pull/17302#issuecomment-238981830. Best!

**Comment by stevengj** [comment]
Yes, let's have `broadcast` use the inference result in the empty case.
