### ISSUE TITLE
Test coverage for Pkg

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17996]
I believe I hit at least two repo corrupting bugs in the package manager on julia 0.5 RC2 in the first hour of using RC2 (#17994, #17995). None of what I did seems very exotic/corner cases etc. This does suggest that Pkg could use more comprehensive test coverage that actually exercises typical user scenarios, so that these sorts of bugs can be found in CI builds.

I'm just opening this issue so that such work can be tracked.

**Comment by KristofferC** [comment]
I added libgit2 to https://github.com/JuliaLang/julia/issues/11885. Do you feel it is still worth having a separate issue open?

**Comment by davidanthoff** [comment]
Good question, I'm not sure. I do feel that this is more about making sure that common Pkg manager user scenarios are actually tested end-to-end rather than getting high code coverage results.

**Comment by KristofferC** [comment]
It seems sensible to me to have one issue dealing with coverage in general and then specific issues regarding specific bugs. Is there any known with the package manager that we are not tracking?
