### ISSUE TITLE
Pkg.update caches invalid credentials

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17990]
After purposefully entering my username and password incorrectly three times for private repo I got the expected "Package ... cannot be updated." message. What I did not expect is that running `Pkg.update()` again does not reprompt the user for credentials.

**Comment by StefanKarpinski** [comment]
Does it just decide that you don't know them and stop asking you forever?

**Comment by Keno** [comment]
What version was this on. I did a bit of cleanup of this code in the past two days.

**Comment by omus** [comment]
OS X Julia v0.5.0-rc2.

**Comment by omus** [comment]
I just tried Julia v0.5.0-rc2 on Linux and it appears to ask forever for credentials. Also, I forgot to mention this using HTTP.

**Comment by omus** [comment]
As it turns out our private Git server will block access when entering invalid credentials repeatedly within a short duration of time. Once blocked, Julia will then cache the last invalid credentials and use them on subsequent `Pkg.update()` calls.

**Comment by KristofferC** [comment]
Issue moved to [JuliaLang/Pkg.jl #692](https://github.com/JuliaLang/Pkg.jl/issues/692) via [**ZenHub**](https://www.zenhub.com/)
