### ISSUE TITLE
`cholfact` gives different answers on v0.5 and v0.6 

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#17992]
I'm not sure if this has already been reported or this is expected, but I get these results. 

On v0.5 rc1:
```
julia> b1
2×2 Array{Float64,2}:
 11.0   45.0
 45.0  286.0

julia> cholfact(b1)
Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
[3.31662 13.568; 0.0 10.095]
```

On v0.6 master (`Version 0.6.0-dev.188 (2016-08-12 04:43 UTC), Commit 585fe0e*`): 
```
julia> b1
2×2 Array{Float64,2}:
 11.0   45.0
 45.0  286.0

julia> cholfact(b1)
Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
[3.31662 0.0; 13.568 10.095]
```
Caused MixedModels.jl to fail (https://github.com/dmbates/MixedModels.jl/issues/52)

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/17985
