### ISSUE TITLE
`Pkg.init()` fails on windows

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#18005]
The results:
```
julia> Pkg.init()
INFO: Initializing package repository C:\tw\.julia\v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:OS, failed to send request: The server name or address could not be resolved)
 in macro expansion at .\libgit2\error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at .\libgit2\repository.jl:191
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at .\libgit2\libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at .\<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at .\pkg\dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at .\file.jl:48
 in init(::String, ::String) at .\pkg\dir.jl:47
 in init() at .\pkg\pkg.jl:70
```
I am behind a somewhat strict firewall at work, though it hasn't been an issue with v0.4.

**Comment by twadleigh** [comment]
OK, I got a little further this morning, but am not out of the woods. I removed the `http_proxy` and `https_proxy` env vars that I had previously been using to indicate my corporate proxy server, and instead set it up through Internet Options. Doing that at least got `Pkg.init()` to succeed.

I followed with `Pkg.add("Atom")`. During the subsequent build of `MbedTLS` I got:
```
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
INFO: Attempting to Create directory C:\tw\.julia\v0.6\MbedTLS\deps\downloads
INFO: Directory C:\tw\.julia\v0.6\MbedTLS\deps\downloads already created
INFO: Downloading file https://malmaud.github.io/files/mbedtls-2.1.1-r1.zip
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (407) Proxy Authentication Required."
At line:1 char:1
+ (new-object net.webclient).DownloadFile("https://malmaud.github.io/fi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

=============================================================[ ERROR: MbedTLS ]=============================================================


LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -NoProfile -Command '(new-object net.webclient).
DownloadFile("https://malmaud.github.io/files/mbedtls-2.1.1-r1.zip", "C:\tw\.julia\v0.6\MbedTLS\deps\downloads\mbedtls-2.1.1-r1.zip")'`, Pro
cessExited(1)) [1]
while loading C:\tw\.julia\v0.6\MbedTLS\deps\build.jl, in expression starting on line 74

============================================================================================================================================


==============================================================[ BUILD ERRORS ]==============================================================


WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in C:\tw\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

============================================================================================================================================
```

**Comment by twadleigh** [comment]
Setting the proxy via Internet Options broke my ability to connect to the corporate network via VPN, so it isn't a long-term solution.

@tkelman I'm willing to help debug these proxy issues as far as I am able, but will probably need assistance to make headway. I figure my corporate environment provides a challenging test case. I currently have master building on my company laptop, and that is what I am testing, though I'm hoping that whatever fixes arise do make their way into 0.5.

**Comment by tkelman** [comment]
Well the powershell download is happening in BinDeps, I would think powershell should use the system-wide proxy settings?

**Comment by twadleigh** [comment]
@tkelman As I found out via [this link](http://www.zerrouki.com/working-behind-a-proxy/) powershell doesn't get those settings automatically. I'm retrying the initial clone with ideas from this link.

**Comment by twadleigh** [comment]
I'm not having the problem now that I'm on my home network (and have removed all the proxy settings). I'll try again when I'm back in the office on Monday.

**Comment by twadleigh** [comment]
Closing this. I'm back at work now. No proxy settings, and things look OK so far: I could both `Pkg.init()` and `Pkg.add("Atom")` successfully. Looks like I might have been overthinking it. I had to jump through a lot of hoops to get Atom working behind our firewall at my new organization, so I suppose I was prepping for another proxy nightmare, and just jumped the gun.
