### ISSUE TITLE
4x performance regression on "sumcartesian" benchmark with 0.5

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#18010]
[Here](https://github.com/JuliaCI/BaseBenchmarkReports/blob/6d82a5518a25740eef4abde8359ea3cdbc630375/0350e57_vs_2e358ce/report.md) it is shown that 0.5 has a 4x regression compared to 0.4. I looked into the typed code, and posted a gist [here](https://gist.github.com/timholy/0f14ba74f921193da28211e1aac48184). They're strikingly different, but I'm uncertain about what's happening; perhaps a difference in inlining?

**Comment by yuyichao** [comment]
Looks like this is not inlined?

```jl
$(Expr(:invoke, LambdaInfo for +(::CartesianIndex{1}, ::Int64), :(Base.IteratorsMD.+), SSAValue(11), 1))
```

**Comment by KristofferC** [comment]
This is still happening

**Comment by KristofferC** [comment]
The non inlined function comes from `Base.start` so that should be fine since it is shouldn't be in the loop?

```
julia> @code_typed Base.start(yy)
CodeInfo(:(begin 
        unless (Base.slt_int)((Base.getfield)((Core.getfield)((Core.getfield)(iter,:stop)::CartesianIndex{1},:I)::Tuple{Int64},1)::Int64,(Base.getfield)((Core.getfield)((Core.getfield)(iter,:start)::CartesianIndex{1},:I)::Tuple{Int64},1)::Int64)::Bool goto 4 # line 119:
        return $(Expr(:invoke, MethodInstance for +(::CartesianIndex{1}, ::Int64), :(Base.IteratorsMD.+), :((Core.getfield)(iter,:stop)::CartesianIndex{1}), 1))
        4:  # line 121:
        return (Core.getfield)(iter,:start)::CartesianIndex{1}
    end))=>CartesianIndex{1}
```

**Comment by KristofferC** [comment]
I've been hitting my head against the wall for an hour now. I thought the problem was with inlining of a CartesianIndex and an Int but after explicitly inlining that it made no difference to the benchmarks.

I put up the two LLVM codes in case any of the LLVM IR experts want to take a look:
https://gist.github.com/KristofferC/545f48517cd0a718c7244021c63258f7

**Comment by KristofferC** [comment]
It "feels" like the code on master is cleaner.. only the

```
 %9 = getelementptr inbounds %UnitRange, %UnitRange* %0, i64 0, i32 0
 %10 = load i64, i64* %9, align 8
```

in the loop(?) is strange.

**Comment by Keno** [comment]
That's just in the pre-header. Did you benchmark just this function? Also, how many loop iterations are there?

**Comment by mbauman** [comment]
Given the reported 4x difference and the fact that I see improvements over both 0.4 and 0.5, I'm guessing that this is missing some AVX SIMD-ification that my computer isn't capable of:

```julia
function perf_sumcartesian(A)
    s = zero(eltype(A))
    for I in CartesianRange(size(A))
        val = Base.unsafe_getindex(A, I)
        s += val
    end
    return s
end
```

0.4.7:

```julia
julia> @benchmark perf_sumcartesian($(1:100000000))
BenchmarkTools.Trial:
  minimum time:     91.324 ms (0.00% GC)
```

0.5.0:

```julia
julia> @benchmark perf_sumcartesian($(1:100000000))
BenchmarkTools.Trial:
  minimum time:     115.096 ms (0.00% GC)
```

master:

```julia
julia> @benchmark perf_sumcartesian($(1:100000000))
BenchmarkTools.Trial:
  minimum time:     71.91 ms (0.00% GC)
```

**Comment by KristofferC** [comment]
Yes I benchmarked.

```julia> function perf_sumcartesian(A)
           s = zero(eltype(A))
           for I in CartesianRange(size(A))
               val = Base.unsafe_getindex(A, I)
               s += val
           end
           return s
       end
perf_sumcartesian (generic function with 1 method)
```

## Master
```
julia> @benchmark perf_sumcartesian(1:1000000)
  minimum time:     1.215 ms (0.00% GC)
```

## 0.4

```
julia> @benchmark perf_sumcartesian(1:1000000)
BenchmarkTools.Trial: 
  minimum time:     303.769 μs (0.00% GC)
```

**Comment by KristofferC** [comment]
For compleness sake, here is the native code: https://gist.github.com/KristofferC/92e682f65679c836191f8722c53c0e49

**Comment by KristofferC** [comment]
LLVM learned math.

```
julia> @btime perf_sumcartesian(1:1000000)
  1.599 ns (0 allocations: 0 bytes)
500000500000
```
