### ISSUE TITLE
Incorrect reinterpret() UInt32 -> Float64 -> UInt64 behaviour on win32

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#18019]
The following command (for the context see JuliaStats/RData.jl#2)
```julia
reinterpret(UInt64, reinterpret(Float64, UInt32[0x1, 0x7ff00000])[1])
```
on julia-0.5-rc2 on linux 64bit gives
```
0x7ff0000000000001
```
but on julia-0.5-rc2 on win 32bit
```
0x7ff8000000000001
```
The latter doesn't seem right, because the final `UInt64` differs from the input array.
 
Interestingly, if the first `UInt32` is zero, both versions return the correct result.

**Comment by yuyichao** [comment]
This is a hardware/abi limit, it doesn't preserve the exact bit patter of NaN.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/17195
