### ISSUE TITLE
Inlining(?) bug on 0.5

### ISSUE THREAD

**Issue by swt30** [JuliaLang/julia#18015]
The following code works on julia 0.4 but fails on 0.5-rc2. It does, however, work when run through Gallium or when `setabc2!` is annotated with `@noinline`.

```jl
using Base.Test
import Base: ==

type Triple
  a::Int
  b::Int
  c::Int
end

a(tri) = tri.a
b(tri) = tri.b
c(tri) = tri.c
setabc!(tri, a, b, c) = (tri.a = a; tri.b = b; tri.c = c)
setabc2!(tri, a, b, c) = (tri.a = a; tri.b = b; tri.c = c; nothing)
==(tri1::Triple, tri2::Triple) = ((tri1.a, tri1.b, tri1.c) == (tri2.a, tri2.b, tri2.c))

function main()
  tri = Triple(1, 2, 3)
  tri2 = Triple(1, 2, 3)
  setabc!(tri, b(tri), c(tri), a(tri))
  setabc2!(tri2, b(tri2), c(tri2), a(tri2))
  @test tri == tri2
end

main()


```

**Comment by swt30** [comment]
```
Julia Version 0.5.0-rc2+0
Commit 0350e57 (2016-08-12 11:25 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by vtjnash** [comment]
It looks like Jeff deleted the handling of this case in 0547ab4498395d95018da124dcd2a24aa96d019b (https://github.com/JuliaLang/julia/pull/15609/files#diff-c0d983631c937ee5acfd0137cd7332deL2332), but the default fall-through was wrong (returning `true` instead of `false` when it couldn't analyze the expression)

**Comment by ViralBShah** [comment]
Should this not be 0.5?

**Comment by vtjnash** [comment]
I thought the v0.5 milestone is closed? Doesn't really matter either way since there's a PR to fix it.

**Comment by StefanKarpinski** [comment]
Bugs (which this is) are fair game for the next RC.

**Comment by tkelman** [comment]
label is already on the pr, not needed here.
