### ISSUE TITLE
0.5.0-rc2 performance regression of creating Float32/64 vectors

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaLang/julia#18021]
With the latest 0.5.0-rc2 Windows 64-bit binary I experience this.
Please, improve this serious slowdown if possible.

```
v32() = Float32[1,2,3]
v64() = Float64[1,2,3]

function test()
    n = Int(10e6)

    println("v32:")
    @time for i=1:n; v=v32(); end
    @time for i=1:n; v=v32(); end
    @time for i=1:n; v=v32(); end

    println("v64:")
    @time for i=1:n; v=v64(); end
    @time for i=1:n; v=v64(); end
    @time for i=1:n; v=v64(); end
end

test()
```
version 0.4.5 output:
v32:
  0.330550 seconds (10.00 M allocations: 762.939 MB, 13.90% gc time)
  0.317775 seconds (10.00 M allocations: 762.939 MB, 13.54% gc time)
  0.319554 seconds (10.00 M allocations: 762.939 MB, 13.54% gc time)
v64:
  0.310845 seconds (10.00 M allocations: 915.527 MB, 8.29% gc time)
  0.303964 seconds (10.00 M allocations: 915.527 MB, 8.05% gc time)
  0.304822 seconds (10.00 M allocations: 915.527 MB, 8.01% gc time)

version 0.5.0-rc2 output:
v32:
  3.291748 seconds (10.00 M allocations: 915.563 MB, 5.11% gc time)
  3.171754 seconds (10.00 M allocations: 915.527 MB, 2.14% gc time)
  3.183680 seconds (10.00 M allocations: 915.527 MB, 2.04% gc time)
v64:
  2.964666 seconds (10.00 M allocations: 1.043 GB, 0.76% gc time)
  2.866506 seconds (10.00 M allocations: 1.043 GB, 0.74% gc time)
  2.873545 seconds (10.00 M allocations: 1.043 GB, 0.75% gc time)

**Comment by ufechner7** [comment]
Same regression on Linux, 64 bits.
