### ISSUE TITLE
 A Julia equivalent to Pandas date_range function

### ISSUE THREAD

**Issue by femtotrader** [JuliaLang/julia#18024]
Hello,

I wonder if a Julia equivalent to Pandas `date_range` function exists.
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html

If not, adding such a function will be a nice feature.

With such a function you can for example get a date range given start date, periods and freq.

But this date_range have many other features

Here is Pandas `date_range` docstring

```
In [4]: ?pd.date_range
Signature: pd.date_range(start=None, end=None, periods=None, freq='D', tz=None, normalize=False, name=None, closed=None, **kwargs)
Docstring:
Return a fixed frequency datetime index, with day (calendar) as the default
frequency

Parameters
----------
start : string or datetime-like, default None
    Left bound for generating dates
end : string or datetime-like, default None
    Right bound for generating dates
periods : integer or None, default None
    If None, must specify start and end
freq : string or DateOffset, default 'D' (calendar daily)
    Frequency strings can have multiples, e.g. '5H'
tz : string or None
    Time zone name for returning localized DatetimeIndex, for example
Asia/Hong_Kong
normalize : bool, default False
    Normalize start/end dates to midnight before generating date range
name : str, default None
    Name of the resulting index
closed : string or None, default None
    Make the interval closed with respect to the given frequency to
    the 'left', 'right', or both sides (None)
```

maybe a convenience function like this will help many user who wants to deals with time series.

See Python Pandas code
https://github.com/pydata/pandas/blob/master/pandas/tseries/index.py#L390

Kind regards

See https://github.com/JuliaStats/TimeSeries.jl/issues/264

**Comment by cormullion** [comment]
A basic date range is built-in, eg. 30-day periods next year:

```
julia> foreach(d -> println(Dates.format(d, "d u yyyy")), 
       Date("2017-01-01"):Dates.Day(30):Date("2018-01-01"))

1 Jan 2017
31 Jan 2017
2 Mar 2017
1 Apr 2017
1 May 2017
31 May 2017
30 Jun 2017
30 Jul 2017
29 Aug 2017
28 Sep 2017
28 Oct 2017
27 Nov 2017
27 Dec 2017
```

There's a `Dates.recur` function for generating recurring dates, e.g. Sundays till the end of this year:

```
julia> Dates.recur(d->Dates.dayname(d) == "Sunday", Dates.today():Dates.Date(2016,12,31))
20-element Array{Date,1}:
 2016-08-14
 2016-08-21
 2016-08-28
 2016-09-04
 2016-09-11
 2016-09-18
 2016-09-25
 2016-10-02
 2016-10-09
 2016-10-16
 2016-10-23
 2016-10-30
 2016-11-06
 2016-11-13
 2016-11-20
 2016-11-27
 2016-12-04
 2016-12-11
 2016-12-18
 2016-12-25
```

Not sure how much of `pd.date_range` this covers, though.

**Comment by milktrader** [comment]
@femtotrader you could submit a PR

**Comment by malmaud** [comment]
I'd like this functionality too, but should it really be in `Base`? There's an on-going effort now to move non-core functionality out of Base and into libraries.

**Comment by quinnj** [comment]
@femtotrader, can you comment specifically on what you're not able to achieve using Base's built-in Date range functionality? From the description of `date_range`, it doesn't seem like we're missing anything here, and it seems, IMO, to even be a bit simpler given Julia's ability to build custom ranges using the `start:freq:end` syntax and the Date's module built-in Period types.

The documentation can probably be improved, so do let us know specific cases that you think are not possible or poorly documented.

**Comment by milktrader** [comment]
This covers most of what's in `date_range` (save timezones and normalization) but I don't see this belonging in base.

````julia
julia> function timestamps(start::TimeType, freq::DataType, obs::Int, step::Int=1)
         steps   = freq(step)
         periods = obs * step
         finish  = start + freq(periods - 1)
         collect(start:steps:finish)
       end
timestamps (generic function with 2 methods)
````

**Comment by femtotrader** [comment]
Here is my WIP proposition

```julia
function date_range(start; periods=9, freq=Dates.Day(1))
    start:freq:start + (periods - 1) * freq
end
```

but a date range could also be create using `stop` (and not start)
I don't think collect should be used inside this function

so maybe function prototype should looks like

```julia
function date_range(; start=nothing, stop=nothing, periods=nothing, freq=nothing)

end
```

(I'm not confortable with the way Julia handle `None`

**Comment by quinnj** [comment]
Both those examples strike me as examples of trying to fit another language's design onto Julia, most notably by how trivial the methods are. Again, I'd love to hear of specific cases where the current Base functionality falls short or lacks in some way.

**Comment by cormullion** [comment]
@quinnj  perhaps they want to specify how many dates should be in the resultin range rather than via supplying an end date. How would they do that?

**Comment by milktrader** [comment]
Agree with @quinnj this is not Python Pandas. It would be helpful to have a case that cannot be solved with the methods provided so far.

**Comment by milktrader** [comment]
@cormullion my example `timestamps` method does specify how many dates are in the range (obs for observations) and does not take an end date.

**Comment by femtotrader** [comment]
You can also want to get a date range using `end` date, `freq` (`Dates.Day(1)` by defaut) and `periods` (or `obs`)

**Comment by milktrader** [comment]
Sure you can add defaults it's just you'd need to re-arrange the argument order.

`function timestamps(start::TimeType, freq::DataType, obs::Int, step::Int=1)`

`function timestamps(start::TimeType, obs::Int, freq::DataType::Dates.Day, step::Int=1)`

**Comment by milktrader** [comment]
One way to get `end` dates, but this is a bit hackish is 

`function timestamps(ed::TimeType, obs::Int, freq::DataType::Dates.Day, step::Int=1, end=true)`

**Comment by quinnj** [comment]
I think we cover the original ask here pretty well with the `Base.range` function:
```julia
help?> range
search: range LinRange UnitRange StepRange StepRangeLen trailing_zeros AbstractRange trailing_ones OrdinalRange AbstractUnitRange AbstractString

  range(start; length, stop, step=1)

  Given a starting value, construct a range either by length or from start to stop, optionally with a given step (defaults to 1, a UnitRange). One of length or stop
  is required. If length, stop, and step are all specified, they must agree.

  If length and stop are provided and step is not, the step size will be computed automatically such that there are length linearly spaced elements in the range (a
  LinRange).

  If step and stop are provided and length is not, the overall range length will be computed automatically such that the elements are step spaced (a StepRange).

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> range(1, length=100)
  1:100

  julia> range(1, stop=100)
  1:100

  julia> range(1, step=5, length=100)
  1:5:496

  julia> range(1, step=5, stop=100)
  1:5:96

julia> range(Date(2018,1,1); step=Dates.Day(1), length=10)
2018-01-01:1 day:2018-01-10
```
