### ISSUE TITLE
Colon should be immutable

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#18034]
See https://github.com/andyferris/StaticArrays.jl/issues/17

Currently, [`Colon` is a `type` with no fields](https://github.com/JuliaLang/julia/blob/f578be39e9cf6e30caeaed22a233d0a832446cc7/base/essentials.jl#L205). This prevents `SubArray`s of a fixed-size matrix (e.g. a `StaticArrays.SMatrix`) with a `Colon` as one of the `indexes` from being `isbits` types, resulting in heap allocations. Making `Colon` immutable instead would solve this problem and enable the creation of `LinearFast` fixed _maximum_ size arrays, which is currently impossible (at least without jumping through lots of hoops).

Code example:
```julia
using StaticArrays
function view_colon()
    data = rand(SMatrix{3, 3, Float64})
    view(data, :, 1:2)
end

function view_range()
    data = rand(SMatrix{3, 3, Float64})
    view(data, 1:3, 1:2)
end

Base.linearindexing(view_colon()) # Base.LinearFast()
Base.linearindexing(view_range()) # Base.LinearSlow()

isbits(view_colon()) # false
isbits(view_range()) # true
```

So currently, one has to choose between a `LinearFast` view that is not `isbits`, or a `LinearSlow` view that is.

I'll try to submit a PR with (hopefully) a one line change; haven't contributed anything to Base before, so it may take me a while to get set up. Note that @andyferris proposed making it so that the compiler treats all field-less types as `isbits` singletons.

cc: @timholy

**Comment by JeffBezanson** [comment]
Good catch, yes let's change `Colon` right away.
