### ISSUE TITLE
ENV does not show the environment variables

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaLang/julia#18035]
I am testing the 0.5.0-rc2 Windows 64-bit binary.
Typing ENV in the REPL does not show the environment variables:
```
julia> ENV
Base.EnvHash with 1 entry:
  "=::" => "::\\"
```
while single items are there:
```
julia> ENV["HOMEDRIVE"]
"C:"

julia> ENV["OS"]
"Windows_NT"
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/17956

**Comment by GaborOszlanyi** [comment]
Sorry for the noise.
