### ISSUE TITLE
`fieldtype` returns too-general type

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18037]
In the function below, Julia returns `Any` for the field type of a tuple, although Julia actually knows that the field has type `Int`:
```Julia
function f{T}(::T)
    @show T
    @show [fieldtype(T, i) for i in 1:nfields(T)]
    nothing
end
f(((nothing, nothing), (nothing, 4)))
```

I see the output:
```
T = Tuple{Tuple{Void,Void},Tuple{Void,Int64}}
[fieldtype(T,i) for i = 1:nfields(T)] = DataType[Tuple{Void,Any},Tuple{Void,Any}]
```

This is different from Julia 0.5, which returns the fully specific type:
```
T = Tuple{Tuple{Void,Void},Tuple{Void,Int64}}
[fieldtype(T,i) for i = 1:nfields(T)] = DataType[Tuple{Void,Void},Tuple{Void,Int64}]
```

#12793 might be related.

**Comment by eschnett** [comment]
@vtjnash That went the other way around than I expected. I expected 0.6 to return the more specific type, not 0.5 to return a less specific type.

Put differently: How can I access the specific type information that is output by `@show`?

**Comment by vtjnash** [comment]
ok, I read that backwards: probably /broken/ by #17953

**Comment by eschnett** [comment]
Here is a work-around (it's not pretty):
```Julia
@generated function ft{T, i}(x::T, ::Type{Val{i}})
    :($(fieldtype(x, i)))
end

function f{T}(x::T)
    @show T
    @show [fieldtype(T, i) for i in 1:nfields(T)]
    @show [ft(x, Val{i}) for i in 1:nfields(T)]
    nothing
end

f(((nothing, nothing), (nothing, 4)))
```
This outputs
```
T = Tuple{Tuple{Void,Void},Tuple{Void,Int64}}
[fieldtype(T,i) for i = 1:nfields(T)] = DataType[Tuple{Void,Any},Tuple{Void,Any}]
[ft(x,Val{i}) for i = 1:nfields(T)] = DataType[Tuple{Void,Void},Tuple{Void,Int64}]
```

**Comment by vtjnash** [comment]
yes, the `@generated` ensures that the compiler can't optimize it
