### ISSUE TITLE
0.50-rc2 library compilation misconfigured?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#18038]
Not sure if this is a Julia problem or a Nemo issue -- 

```julia
ERROR: LoadError: error compiling __init__: could not load library "/home/jas/.julia/v0.5/Nemo/local/lib/libpari"
/home/jas/.julia/v0.5/Nemo/local/lib/libpari.so: wrong ELF class: ELFCLASS64
 in include_from_node1(::String) at ./loading.jl:426
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/jas/.julia/v0.5/Nemo/src/Nemo.jl, in expression starting on line 309
ERROR: Failed to precompile Nemo to /home/jas/.julia/lib/v0.5/Nemo.ji
 in compilecache(::String) at ./loading.jl:505
 in require(::Symbol) at ./loading.jl:364
```

The wrong ELF class: ELFCLASS64 message happens with the other libs as well.  This did not happen before.

Using Julia Version 0.5.0-rc2+0
Commit 0350e57 (2016-08-12 11:25 UTC)
Platform Info:
  System: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz
  WORD_SIZE: 32

This is running inside a 32bit VirtualBox from a Windows 64bit system.

**Comment by Keno** [comment]
You're trying to load a 64bit library in a 32bit process, that doesn't work.

**Comment by JeffreySarnoff** [comment]
@Keno yes, I get that -- before I upgraded to v0.5rc2 the system did the right thing.  Bill Hart thinks it may be that the Nemo build logic does not handle this case well.  My concern, and the reason I posted this issue, is that something which worked before, selecting the 32bit compilation of a library for me, stopped working.  If you find this has nothing to do with Julia changes, please close this issue.

**Comment by tkelman** [comment]
Check the config.log for libpari. It may have erroneously tried to build with `-m64` ?

**Comment by JeffreySarnoff** [comment]
@tkelman the same thing happens with every library, not just libpari -- I tried forcing -m32, and that did not work out (though it may be a secondary problem that arose).  I also tried setting ABI=32 in the ./configure line with appropriate --host.. --build.. settings, to no avail (though, again, it may be a secondary problem that arose).

For my purposes, it would suffice to know how to modify [Nemo's build.jl](https://github.com/Nemocas/Nemo.jl/blob/master/deps/build.jl) so the compilation of a source file recognizes when Sys.WORD_SIZE==32 while the actual machine archetecture is 64bit [as occurs running Linux via VirtualBox from Windows on a 64bit machine].

**Comment by tkelman** [comment]
The userland inside the VM shouldn't be able to know whether the VM host system is actually 64 bit. Are you sure the VM is 32 bit, or are you trying to run 32 bit Julia on a 64 bit VM OS? What does `gcc -v` say?

**Comment by JeffreySarnoff** [comment]
you found it! I had inadvertently downloaded the 32bit linux v0.5rc2.
