### ISSUE TITLE
Add lib/julia to DL_LOAD_PATH by default

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#18057]
This would simplify using some of julia's handy libraries it ships with (i.e. see mbedtls).

**Comment by vtjnash** [comment]
agreed. (we already do this on Darwin)

**Comment by tkelman** [comment]
Wouldn't it be better for packages to load specifically what they need rather than always making our versions of everything visible by default? Other pieces of software may need differently-configured versions of these (see e.g. Nemo's use of custom builds of mpfr and gmp).
