### ISSUE TITLE
eigfact

### ISSUE THREAD

**Issue by GCabrine** [JuliaLang/julia#18065]
I'm starting to use Julia, as a test for replacing the use of R in our organization. The first test that I'm planning is to evaluate the performance of the language to calculate eigenvalues and eigenvectors of a correlation matrix (that is not positive defined, I've actually need this calculation to make it semi PD).
But, when I try to run eig, Julia stops.

I retrieve the matrix from an ODBC as a vector, use the reshape to convert it to a 2-dim array (type Float64). The result is attached:
[Correlation.txt](https://github.com/JuliaLang/julia/files/421174/Correlation.txt)

When I use the eig function (I'm running Julia through Atom), I receive the following errors:

![image](https://cloud.githubusercontent.com/assets/21067045/17713835/55a5b54e-63d3-11e6-9ed1-961872c4da9e.png)

> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_FLT_DIVIDE_BY_ZERO at 0x71d8d56 -- ieeeck_64_ at C:\Program Files\Julia-0.4.6\bin\libopenblas64_.DLL (unknown line)
ieeeck_64_ at C:\Program Files\Julia-0.4.6\bin\libopenblas64_.DLL (unknown line)
dsyevr64_ at C:\Program Files\Julia-0.4.6\bin\libopenblas64_.DLL (unknown line)
syevr! at linalg/lapack.jl:4120
eigfact! at linalg/eigen.jl:31
julia_eigfact!_3407 at  (unknown line)
eigfact at linalg/eigen.jl:57
eig at linalg/eigen.jl:66
julia_eig_3402 at  (unknown line)
jl_apply_generic at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_parse_eval_all at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_load_file_string at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
include_string at loading.jl:288
jl_apply_generic at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
jl_f_tuple at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
eval at C:\Users\guilherme.cabrine\AppData\Local\.julia\v0.4\Atom\src\Atom.jl:3
jl_apply_generic at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
anonymous at C:\Users\guilherme.cabrine\AppData\Local\.julia\v0.4\Atom\src\eval.jl:39
withpath at C:\Users\guilherme.cabrine\AppData\Local\.julia\v0.4\Requires\src\require.jl:37
withpath at C:\Users\guilherme.cabrine\AppData\Local\.julia\v0.4\Atom\src\eval.jl:53
jlcall_withpath_1529 at  (unknown line)
jl_apply_generic at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)
anonymous at C:\Users\guilherme.cabrine\AppData\Local\.julia\v0.4\Atom\src\eval.jl:107
jl_unprotect_stack at C:\Program Files\Julia-0.4.6\bin\libjulia.dll (unknown line)

**Comment by andreasnoack** [comment]
Is there anything special about the machine that you are running this on? What is the output from `versioninfo()`. I cannot reproduce this on my Windows VM. There shouldn't be an exception when dividing with zero. It should just be an `Inf` or `NaN`.

**Comment by tkelman** [comment]
Does it occur if you run the code via the normal julia REPL shortcut?

**Comment by GCabrine** [comment]
> Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

When I run it on julia, it closes the terminal.

**Comment by andreasnoack** [comment]
Can you try just to run
```jl
ccall((:ieeeck_64_, Base.libblas_name), Int64, (Ptr{Int64}, Ptr{Float32}, Ptr{Float32}), &0, &Float32(0.0), &Float32(1.0))
```
?

**Comment by GCabrine** [comment]
Sure:

![image](https://cloud.githubusercontent.com/assets/21067045/17715444/76479252-63da-11e6-93ff-684b30850a7a.png)

**Comment by GCabrine** [comment]
The correlation matrix that I've passed come from an ODBC. The situations that ran into error I performed the following steps to get the matrix:

> using ODBC, SQLite;
> dsn = ODBC.DSN("dsn", "user", "pwd");
> source = Array{Float64,1}(ODBC.query(dsn, "SELECT Correlacao FROM vwCenarioCorrelacao WHERE dtIni <= '2016-08-10' and dtFim >= '2016-08-10' ORDER BY MercadoID1, MoedaID1, MercadoID2, MoedaID2")[1]);
> mCorrelacao = reshape(source, 62, 62);
> eig(mCorrelacao);


When I just reopened Atom and ran the code you've passed, it worked fine:
![image](https://cloud.githubusercontent.com/assets/21067045/17715632/70119e04-63db-11e6-8311-8b8ad5bb2baf.png)

**Comment by andreasnoack** [comment]
Interesting. Can you try just to call `1/0` after the database steps?

**Comment by andreasnoack** [comment]
I can get the same error if I first
```jl
ccall(:_controlfp, Cuint, (Cuint,Cuint), 3, 0x0008001f)
```
(according to https://msdn.microsoft.com/en-us/library/e9b52ceh.aspx it should be `8` instead of `3`) so maybe the database or the wrappers modify the floating point behavior of the machine.

**Comment by Keno** [comment]
Well, it does indeed look like ODBC or the particular ODBC driver is leaking floating point state. Can you clarify versions, what kind of library, etc.?

**Comment by Keno** [comment]
The SysV ABI explicitly calls out mxcsr as callee-saved. It appears the same is true on Windows (e.g. http://www.agner.org/optimize/calling_conventions.pdf). So this can indeed be classified as a bug in such a library.

**Comment by simonbyrne** [comment]
1. What version of Windows are you using? (and if you can find out, what version of odbc32.dll do you have installed?)
2. Do you still get the error if you do:
```julia
using ODBC
ccall((:ieeeck_64_, Base.libblas_name), Int64, (Ptr{Int64}, Ptr{Float32}, Ptr{Float32}), &0, &Float32(0.0), &Float32(1.0))
```

**Comment by GCabrine** [comment]
`1 / 0` returns `inf`
Windows 7 Professional

![image](https://cloud.githubusercontent.com/assets/21067045/17736928/ba2113d2-6460-11e6-823f-8ab1d9482444.png)

Returns the same error:
![image](https://cloud.githubusercontent.com/assets/21067045/17736985/05e1ddd8-6461-11e6-8dda-98f7eea74429.png)

ODBC Package version: 0.4.2

**Comment by GCabrine** [comment]
> andreasnoack
> I can get the same error if I first
> 
> ccall(:_controlfp, Cuint, (Cuint,Cuint), 3, 0x0008001f)
> (according to https://msdn.microsoft.com/en-us/library/e9b52ceh.aspx it should be 8 instead of 3) so maybe the database or the wrappers modify the floating point behavior of the machine.


This replicate the behavior of the error for me as well.

**Comment by andreasnoack** [comment]
@GCabrine Just to be sure. You did
```
using ODBC
1/0
```
and it didn't error?

**Comment by GCabrine** [comment]
Sorry, the `1/0` didn't error without the `using ODBC`. When I load the library before, it returns error.

**Comment by andreasnoack** [comment]
It's the `DecFP` package and not the database packages that are causing this. On my machine, it's sufficient to do
```jl
using DecFP
1/0
```
to get the error.

**Comment by simonbyrne** [comment]
Phew, I thought for a moment we would have to debug `odbc32.dll`. 

cc @stevengj

**Comment by simonbyrne** [comment]
Okay, looks like the solution here is to remove DecFP.jl as a dependency from ODBC.jl on windows: JuliaDB/ODBC.jl#137.

**Comment by GCabrine** [comment]
Thanks to all!
