### ISSUE TITLE
replace(string, pat, r) incorrectly handles escaped backslash

### ISSUE THREAD

**Issue by rprechelt** [JuliaLang/julia#18072]
`replace("this/is/a/dir", "/", "\")` results in a `ERROR: syntax: incomplete: invalid character literal` as `\"` is interpreted as an escaped `"`. However, 

`replace("this/is/a/dir", "/", "\\")` results in `"this\\is\\a\dir"` - i.e. it has used two backslashes. Typical escape character printing (such as C stdlib) interprets `\\` as a single backslash character which is what I would expect. 

`replace("this/is/a/dir", "/", "\\")` works as expected on `0.4.5` - i.e. `this/is/a/dir` to `this\is\a\dir`. 

N.B. Julia handles other escape characters normally (`replace("this/is/a/dir", "/", "\n")` is correctly printed as 

```
this
is
a
dir
```

Tested on `0.6-dev`.

**Comment by yuyichao** [comment]
This is just the printing. (`\` is printed as `\\` in string to match what they would appear in code.)
