### ISSUE TITLE
Setting env. variables like JULIA_NUM_THREADS for remote workers

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#18074]
There currently doesn't seem to be a method to control/set/forward environment variables for remote workers, e.g. workers started with

```
addprocs([host1, ...])
```

One important variable that users may want to set is `JULIA_NUM_THREADS`. But in more complex real-world situation, one may also need to set (resp. forward) things like PATH, LD_LIBRARY_PATH (for custom software packages) and other (site- and application-dependent) variables.

Maybe addprocs could get an `env` kwarg or so?

**Comment by ViralBShah** [comment]
cc @amitmurthy

**Comment by xgdgsc** [comment]
Also hoping this could be added so I only have one JULIA_DEPOT_PATH JULIA_PROJECT shared on nfs between nodes.

**Comment by mgkuhn** [comment]
Julia 1.6 added a new `env=["JULIA_DEPOT_PATH"=>"/depot", ...]` keyword argument to [Distributed.addprocs](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.addprocs) that solves this issue.
