### ISSUE TITLE
Nightlies behind on Travis?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#18079]
I had a [travis failure](https://travis-ci.org/timholy/FFTViews.jl/jobs/152987147) that I traced down to the fact that the nightly build was using https://github.com/JuliaLang/julia/commit/d3df8e7c1002380fab2a473e332aa5b26ff5f49b, which is 11 days old.

If this is a known problem, feel free to close this.

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/17651#issuecomment-238211150

**Comment by tkoolen** [comment]
I'm surprised this issue hasn't received more attention. It doesn't just affect Travis; the nightlies at http://julialang.org/downloads/ are also stuck at `d3df8e7`.

**Comment by musm** [comment]
17651 is closed is there anything else holding back the nightlies?

**Comment by musm** [comment]
bump  : )

**Comment by tkelman** [comment]
read the link. ssh tests fail on the buildbot. that has not changed.

**Comment by KristofferC** [comment]
Nightlies are now updated.
