### ISSUE TITLE
any() and all() functions broken for empty collections

### ISSUE THREAD

**Issue by dbeach24** [JuliaLang/julia#18073]
Julia raises an exception when invoking the `any()` and `all()` functions with empty collections.

In Julia 0.5.0-RC2, I get:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-pre+5606 (2016-07-21 19:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 5fe9e53* (26 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> any([])
ERROR: ArgumentError: reducing over an empty collection is not allowed
 in _mapreduce(::Base.#identity, ::Base.#or_bool_only, ::Base.LinearFast, ::Array{Any,1}) at ./reduce.jl:148
 in any(::Array{Any,1}) at ./reduce.jl:365
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:46

julia> all([])
ERROR: ArgumentError: reducing over an empty collection is not allowed
 in _mapreduce(::Base.#identity, ::Base.#and_bool_only, ::Base.LinearFast, ::Array{Any,1}) at ./reduce.jl:148
 in all(::Array{Any,1}) at ./reduce.jl:366
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:46
```

The behavior I would expect:

```
@assert any([]) == false
@assert all([]) == true
````

Note that this behavior is generally useful in most logic programming and matches Python:

```
Python 2.7.10 (default, Sep 22 2015, 12:25:10) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: any([])
Out[1]: False

In [2]: all([])
Out[2]: True
```

**Comment by dbeach24** [comment]
Update:

This is actually an inconsistency between any(iter) and all(iter) and their two argument counterparts that accept a predicate any(pred, iter) and all(coll, iter):

These two argument forms return the expected result in the case of an empty collection:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-pre+5606 (2016-07-21 19:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 5fe9e53* (26 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> any(x -> x > 1, [])
false

julia> all(x -> x > 1, [])
true
```

**Comment by yuyichao** [comment]
FWIW

```jl
julia> all(Bool[])
true

julia> any(Bool[])
false
```

**Comment by dbeach24** [comment]
@yuyichao 
Interesting. Perhaps this is only a bug for empty collections where `eltype(coll) == Any` ?

**Comment by TotalVerb** [comment]
Similar issue exists for `sum` and `prod`... I wonder if they should just return `Bool` on `Any[]` arrays. That case is not type stable anyway.

**Comment by eschnett** [comment]
I guess `any` and `all` should call `mapreduce` with the additional argument specifying the value for empty collections.

**Comment by dbeach24** [comment]
Looking at `sum` and `prod` the issue seems to exist for both the one- and two-argument forms:
 * `sum(iter)` and `prod(iter)`
 * `sum(func, iter)` and `prod(func, iter)`

I think we should expect these to default to the additive and multiplicative identities, respectively:
```julia
@test sum([]) == 0
@test sum(identity, []) == 0
@test prod([]) == 1
@test prod(identity, []) == 1
```

Again, there appears to be no problem if the array has a specific type:
```julia
julia> @test sum(Int[]) == 0
Test Passed
  Expression: sum(Int[]) == 0
   Evaluated: 0 == 0

julia> @test prod(Int[]) == 1
Test Passed
  Expression: prod(Int[]) == 1
   Evaluated: 1 == 1

julia> @test sum(identity, Int[]) == 0
Test Passed
  Expression: sum(identity,Int[]) == 0
   Evaluated: 0 == 0

julia> @test prod(identity, Int[]) == 1
Test Passed
  Expression: prod(identity,Int[]) == 1
   Evaluated: 1 == 1
```

This case might be less clear since, in the case of `any` / `all`, it is obvious that the result must be boolean, but in the case of `sum` / `prod` the expected result is the additive or multiplicative identity of `eltype(coll)`... leading to the question, should `Any` have an additive or multiplicative identity?  One could certainly manufacture such a type which satisfies the necessary properties, but how would that actually be useful?

Impressively, `sum` and `prod` get the additive and multiplicative identities right for other numeric types:

```julia
julia> using Quaternions

julia> sum(Quaternion{Float64}[])
0.0 + 0.0im + 0.0jm + 0.0km

julia> prod(Quaternion{Float64}[])
1.0 + 0.0im + 0.0jm + 0.0km
```

**Comment by stevengj** [comment]
@dbeach24, no, that would destroy type-stability of the `sum` function.   We've had many discussions of `sum`, see e.g. #8092 and #12461.

Let's keep this issue focused on the case at hand.  `any` and `all` always return `Bool`, so there it is no type-stability issue.  It is clear that they should return `false` and `true`, respectively, for empty arrays.   It should be quite a simple PR to fix this.

**Comment by dbeach24** [comment]
@stevengj Thanks for the background.  (Deleting my earlier comment as it is not pertinent to this issue.)
