### ISSUE TITLE
0.5.0-rc2+0 segfault

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#18085]
Two issues with the following code:
1. There is a warning I don't get in 0.4: `WARNING: Method definition #1(Any) in module Main at foo.jl:5 overwritten at foo.jl:5.`
2. The code segfaults.

```
foo(a,x...)=(randn(),)

for (f,g) in ((:asin,:sin), (:acos,:cos))
    gx = eval(g)
    foo(::Type{Val{f}},x...)=map(x->2gx(x),foo(Val{b},x...))
end

foo(Val{:asin},3)
```

**Comment by ViralBShah** [comment]
Verified - crashes on master.

**Comment by JeffBezanson** [comment]
Why is this release-blocking ahead of, say, #17003 #17288 #18069?
