### ISSUE TITLE
define isassigned(r::Ref) = isdefined(r, :x)?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18086]
It really seems like we should be able to do `isdefined(r::Ref)`, in analogy with `isdefined(a)` for a zero-dimensional array (in both cases, you access the contents with `[]`).   Right now, you have to do `isdefined(r, :x)`, which is annoying because it depends on the internal implementation of `RefValue`.

Unfortunately, it's not as simple as `Base.isdefined(r::Ref) = isdefined(r, :x)` because `isdefined` is a builtin.  Maybe `Core.isdefined` should be the builtin, and `Base.isdefined` should be a generic function that wraps around `Core.isdefined`?

(This came up in JuliaLang/IJulia.jl#447, cc @malmaud)

**Comment by malmaud** [comment]
I agree this would be the best, but it might also be reasonable to use `isassigned` for this purpose, https://github.com/JuliaLang/julia/pull/18082.

**Comment by yuyichao** [comment]
Closed by https://github.com/JuliaLang/julia/pull/18082
