### ISSUE TITLE
Error in `/usr/local/bin/julia': malloc(): smallbin double linked list corrupted

### ISSUE THREAD

**Issue by JuliaNumberTypes** [JuliaLang/julia#18098]
v0.5rc2 -- I assume that this should not occur while running Julia, even with ccalls.

My code uses a stable C library's initialization and freeing (as a finalizer) routines via ccall.  I do not do anything with Julia internals overtly. The log is available: [error.txt](https://github.com/JuliaArbTypes/ArbFloats.jl/blob/master/doc/error.txt)

**Comment by yuyichao** [comment]
> I assume that this should not occur while running Julia, even with ccalls.

No, this can easily occur with ccall when not used correctly.

**Comment by vtjnash** [comment]
yes, the slightest mistake in a `ccall` is likely to cause something like this

that said, where did you get julia from / which compilers did you use? it looks like there's a possibility you're trying to mix-and-match different version of the g++ compiler

**Comment by JuliaNumberTypes** [comment]
The version of Julia is from [the rc2 availability announcement, Linux 64bit](https://s3.amazonaws.com/julialang/bin/linux/x64/0.5/julia-0.5.0-rc2-linux-x86_64.tar.gz ).
The host is a 64bit Linux system running in a VirtualBox on a 64bit Win7 system.   

The ccall'ed libraries are not mine.  They are some of the libraries that Nemo.jl builds for its own use (those exact files accessed in place, with their permission).  The libraries are heavily used and thought to be stable with respect to such memory issues.  My package has worked without any memory or ccalling problems in different scenarios and interoperates smoothly with DifferentialEquations, DualNumbers, ForwardDiff, HyperDualNumbers, MappedArrays, Plots, Quaternions, and some other packages.

g++ --version is g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
I also have clang-dev installed, 
clang version 3.8.0-2ubuntu3 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by yuyichao** [comment]
I can reproduce this, this is most likely an user error.

**Comment by JuliaNumberTypes** [comment]
Does a "user error" means there is a malformed or inexact use of call?

**Comment by yuyichao** [comment]
Had a brief look at your code, there's a few problems

1. `.gitignore` is named `,gitignore`
2. Don't overwrite `finalize` it's very confusing.
3. You are explicitly calling the cleanup function as well as adding it as finalizer without checking in the fianlizer if it is already cleand up, this will certainly corrupt the memory.

**Comment by yuyichao** [comment]
Also, you are missing the `Nemo` dependency, making it much harder to test your code.

**Comment by JuliaNumberTypes** [comment]
am fixing, thanks for the pointers

**Comment by bjarthur** [comment]
regarding "mix-and-match different version of the g++ compiler", the way to look into this is:

```
$ strings -a <julia-dir>/usr/bin/julia-debug  | grep GCC
GCC: (GNU) 4.8.5 20150623 (Red Hat 4.8.5-4)
```

one can similarly check whatever .so files you're `ccall`ing to.

in my case the problem that i wasn't [passing pointers](http://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#passing-pointers-for-modifying-inputs) correctly.
