### ISSUE TITLE
Documentation guarantee that `keys(Dict)` and `values(Dict)` iterate the elements of a `Dict` in the same order

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#18090]
Looking at [dict.jl](https://github.com/JuliaLang/julia/blob/master/base/dict.jl) I see that `keys(Dict)` and `values(Dict)` simply iterate the `Dict`, returning the key or the value, respectively. Therefore they return the elements in the same order (see http://stackoverflow.com/questions/39002073/values-and-keys-guaranteed-to-be-in-the-same-order). It would be nice if this were guaranteed in the documentation (that is, that it doesn't change in the future).

**Comment by martinholters** [comment]
If we document it, we should also test it, which I think isn't done at present.

**Comment by prasad-marne** [comment]
can i solve this issue

**Comment by nalimilan** [comment]
We don't generally assign issues to somebody. Just mentioning here that you're working on it is fine.

**Comment by prasad-marne** [comment]
i am newbie to contributing, so just to confirm my tasks to solve this issue.

1) Update docstring of  Dict([itr]) with this string -> `keys(Dict)` and `values(Dict)` iterate the elements of a `Dict` in the same order.
2) add jldoctest to test that keys(Dict) and values(Dict) return elements in same order.

**Comment by nalimilan** [comment]
> i am newbie to contributing, so just to confirm my tasks to solve this issue.
> 
>     Update docstring of Dict([itr]) with this string -> keys(Dict) and values(Dict) iterate the elements of a Dict in the same order.

Rather to the docstrings for `keys` and `values`.

>     add jldoctest to test that keys(Dict) and values(Dict) return elements in same order.

You can add a doctest if it makes sense to present this in the docstring. If it's too long, add it to a test in `test/dict.jl` instead.

**Comment by prasad-marne** [comment]
i have created the pull request for this issue
