### ISSUE TITLE
Inconsistent behavior in sparse matrices when interacting with NaNs

### ISSUE THREAD

**Issue by gabgoh** [JuliaLang/julia#18091]
``` julia
julia> spzeros(2,2)*[NaN;NaN]    
2-element Array{Float64,1}:      
 0.0                             
 0.0                             

julia> zeros(2,2)*[NaN;NaN]      
2-element Array{Float64,1}:      
 NaN                             
 NaN            
```

I believe the latter behavior is the correct one

**Comment by tkelman** [comment]
Yes, this is wrong, our current sparse matrix implementation does not give proper IEEE754 results for operations on the implicit non-stored zeros. Should be fixable with a bit of care.

related: #14973

**Comment by KristofferC** [comment]
Is there any programming language that does this properly for all operations?

**Comment by JaredCrean2** [comment]
Oh, this again.  There was also some discussion in #15579 revolving around handling Infs and NaNs in sparse algorithms.

**Comment by ViralBShah** [comment]
Cc @Sacha0

**Comment by tkelman** [comment]
I'll repeat myself here too:

> Ignoring the corner cases doesn't make Julia's behavior materially more correct here. Fixing it, for the cases where that's not terribly complicated to do [...] means we're ahead of the curve in fixing bugs that have either not been reported yet, not been fixed yet, or been left unaddressed in existing libraries. We don't need to repeat the mistakes of our predecessors here.

Calling this a feature instead of a bug runs counter to the purpose of sparse matrices as a representation optimization that shouldn't change visible behavior in a generic programming sense.

**Comment by JaredCrean2** [comment]
@tkelman I think you and I should get matching shirts and wear them to the next JuliaCon: https://www.amazon.com/Arguing-Engineer-Like-Wrestling-shirt/dp/B01HJ85TTC 

Ok, if you are really intent on doing things this way, how about structuring the API in this way:

```julia
function func_unchecked(args...)
   # implement the algorithm, not performing any checks
end

function func_checked(args...)
  # do checks here
  func_unchecked(args...)
end
```
and export both versions, and also link this up to the `@fastmath` machinery so when the user decides they don't care about Infs and NaNs, calls to `func_checked` turn into `func_unchecked`?

**Comment by tkelman** [comment]
that seems fine, except that I don't think we should export the unchecked version

**Comment by JaredCrean2** [comment]
Why not?  It just unchecked, not unsafe.  The functions that do arithmetic don't check for overflow, underflow etc.

**Comment by tkelman** [comment]
namespace pollution - we should probably be putting these things in an Unchecked module.

**Comment by JaredCrean2** [comment]
Sounds reasonable.

**Comment by KristofferC** [comment]
Closing in favor of https://github.com/JuliaLang/julia/issues/22733
