### ISSUE TITLE
invoke should raise MethodError for ambiguous cases

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18095]
Currently we have this:

``` jl
julia> f(::Int, ::Number) = 1
f (generic function with 1 method)

julia> f(::Number, ::Int) = 2
f (generic function with 2 methods)

julia> f(1,2)
ERROR: MethodError: f(::Int64, ::Int64) is ambiguous. Candidates:
  f(::Number, ::Int64) at REPL[1]:1
  f(::Int64, ::Number) at REPL[0]:1

julia> invoke(f, (Int,Int), 1, 2)
1
```

When `invoke` is called with an ambiguous tuple of types, it should raise the same error as when the function is simply called with arguments of those types. Discovered while playing with the `@invoke` macro I cooked up [here](https://github.com/JuliaLang/julia/pull/13123#issuecomment-240552541).

**Comment by StefanKarpinski** [comment]
Was that a mis-reference, @vtjnash?

**Comment by vtjnash** [comment]
no, I simply elected to fix the occurrence there without also fixing it here

**Comment by tkelman** [comment]
invoke behavior seems unlikely to change for 0.6
