### ISSUE TITLE
julia 0.4.6: pcre libraries installed with RPATH into build directory.

### ISSUE THREAD

**Issue by buczek** [JuliaLang/julia#18106]
The julia build system installs the two pcre shared libraries /usr/lib/julia/libpcre2-8.so.0.2.0
and /usr/lib/julia/libpcre2-posix.so.0.0.0 with an RPATH to a build directory (eg. /dev/shm/bee-root/julia/julia-0.4.6-0/source/usr/lib) which is a security problem if the build directory is in a public writable temp space as is the case at our site.

The patch

```
--- a/deps/Makefile
+++ b/deps/Makefile
@@ -788,9 +788,6 @@ PCRE_OBJ_TARGET = $(build_shlibdir)/libpcre2-8.$(SHLIB_EXT)

 # Force optimization for PCRE flags (Issue #11668)
 PCRE_CFLAGS = -O3
-ifneq ($(OS),WINNT)
-PCRE_LDFLAGS = "-Wl,-rpath,'$(build_libdir)'"
-endif

 pcre2-$(PCRE_VER).tar.bz2:
        $(JLDOWNLOAD) $@ https://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-$(PCRE_VER).tar.bz2
--
```

fixes the problem only for one of the two libraries, as the RPATH of
the other one is also set by the pcre build system.

We fixed it for us by adding

```
    patchelf --remove-rpath $D/$LIBDIR/julia/libpcre2-8.so.0.2.0
    patchelf --remove-rpath $D/$LIBDIR/julia/libpcre2-posix.so.0.0.0
```

to our package build system.

**Comment by paulmenzel** [comment]
It’s partially fixed in Julia 0.5.0.

```
$ objdump -p /usr/lib/julia/libpcre2-8.so.0.3.0 | egrep 'RPATH|RUNPATH'
  RPATH                $ORIGIN
$ objdump -p /usr/lib/julia/libpcre2-posix.so.0.0.1 | egrep 'RPATH|RUNPATH'
  RPATH                /dev/shm/bee-root/julia/julia-0.5.0-0/source/usr/lib:$ORIGIN
```

**Comment by buczek** [comment]
Still relevant in 0.6.0

**Comment by ViralBShah** [comment]
Do we know if this is still a problem?

**Comment by buczek** [comment]
We removed our `patchelf` patch since version 1.0.0, as libpcre2 was no longer installed with julia.

I don't find any bad RPATH in any shared library from our julia installation and we no longer patch around this. so I'd say the problem is gone. I close the issue. Thanks!
