### ISSUE TITLE
findlast is incorrect for strings

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18109]
```
julia> findlast("fooα🐨βcd3", 'o')
ERROR: UnicodeError: invalid character index
 in slow_utf8_next(::Array{UInt8,1}, ::UInt8, ::Int64) at ./strings/string.jl:67
 in next at ./strings/string.jl:92 [inlined]
 in getindex(::String, ::Int64) at ./strings/basic.jl:70
 in findprev(::String, ::Char, ::Int64) at ./array.jl:982
 in findlast(::String, ::Char) at ./array.jl:1009
```

Reported [on julia-users](https://groups.google.com/d/msg/julia-users/ErKcGusASwk/bEgA0wCNBgAJ).

(Affects both 0.4 and 0.5.)

**Comment by stevengj** [comment]
The underlying bugs are in `findprev` and `findnext`.

The simplest solution would be to re-implement these for `AbstractString` using `nextind` and `prevind`.   However, there is also the concern that these functions will run into trouble for nontraditionally indexed arrays (e.g. 0-based); cc @timholy

**Comment by StefanKarpinski** [comment]
Is this 0.5.x material or 0.6 material?
