### ISSUE TITLE
julia.exe should cd to homedir() on Windows

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18112]
On Mac, when I double-click the `Julia` program and then run `pwd()`, I get my home directory.   But on Windows, when I double-click `julia.exe` I get the directory where the executable is.

It seems more useful (and more consistent) to default to `homedir()`.  (This would not apply to the command-line program, only to clicking the icon.  Is there a way to distinguish how Julia was launched in Windows?)

(This came up because it was apparently causing difficulties with IJulia: JuliaLang/IJulia.jl#449)

**Comment by stevengj** [comment]
Here are [various ways](http://stackoverflow.com/questions/510805/can-a-win32-console-application-detect-if-it-has-been-run-from-the-explorer-or-n) to detect whether a program was launched from `cmd.exe`.  We could [also check the parent process](http://stackoverflow.com/questions/2531837/how-can-i-get-the-pid-of-the-parent-process-of-my-application/2533287#2533287).

**Comment by vtjnash** [comment]
Make a startup `.lnk` and set its startup directory?

**Comment by GaborOszlanyi** [comment]
For serious work many people avoid using their ``homedir()`` on Windows.
So I suggest offering an option for the directory where ``Julia`` wakes up.

**Comment by stevengj** [comment]
@GaborOszlanyi, what do you mean by "where julia wakes up"?   If you launch Julia from a command-line, I agree that it should use that directory.  The question is, what directory should it use if you double-click on a Julia icon?

**Comment by stevengj** [comment]
The following code, [adapted from StackOverflow](http://stackoverflow.com/questions/9009333/how-to-check-if-the-program-is-run-from-a-console), looks like it works to detect whether Julia was launched in its own console:
```jl
consolehandle = ccall(:GetConsoleWindow, stdcall, Ptr{Void}, ())
consoleprocess = Ref{Cint}()
ccall((:GetWindowThreadProcessId,"user32"), stdcall, Cint, (Ptr{Void},Ref{Cint}), consolehandle, consoleprocess)
ccall(:GetCurrentProcessId, stdcall, Cint, ()) == consoleprocess[]
```
It yields `true` if Julia created its own console (i.e. you double-clicked on the `julia` icon) and `false` otherwise (e.g. you ran Julia from a terminal window).    My suggestion, consistent with our behavior on OS X, is to `cd` to `homedir()` if this code returns `true`.

**Comment by GaborOszlanyi** [comment]
@stevengj 
> The question is, what directory should it use if you double-click on a Julia icon?

This is what I meant for the directory where ``Julia`` wakes up.
Please ignore my suggestion because this directory 
can easily be changed by the ``Start in`` property of the Shortcut.

**Comment by tkelman** [comment]
Where is this behavior happening on mac? I don't see why the shortcut is any different than launching the executable. I prefer the way things are.

**Comment by stevengj** [comment]
I don't know where the code for this is, but Julia is in the Applications folder on OSX and double-clicking it opens with pwd == homedir.   Why should wherever the `julia.exe` executable is determine the startup directory on Windows?

**Comment by tkelman** [comment]
That's how many executables tend to behave, their default working directory is their location, if you start them via double-clicking on the exe. That's what `import os; os.getcwd()` does if I double-click on `python.exe`. Cygwin's `bash.exe` does the same, starts in `/usr/bin` (which is the posixy name for `C:\cygwin64\bin` where I have it installed) when you double-click it. It starts in `$HOME` if you ask for a login shell with `-l` from the command line.

**Comment by stevengj** [comment]
Okay, if that's the standard behavior on Windows, I guess we should leave it as-is.

**Comment by tkelman** [comment]
I'd have to check how various Linux window managers behave if you launch things via double-clicking instead of from the terminal, but I think Mac is the odd one out since its applications tend to be in deep nested hidden folders under /Applications that aren't usually intended to be touched. There might be an argument for behaving differently if we installed under a default read-only location like Program Files, but currently we don't. And it might still be more of a matter of opinion what we should set for the separate `.lnk` shortcut's "Start in" property. It's been a long time since I last used Matlab, but it starts in something like Documents\Matlab on Windows, right?

**Comment by tkelman** [comment]
(I wouldn't mind if the `notebook` function in IJulia wanted to add a startup location kwarg that defaulted to `homedir()` though, that would make a lot of sense to me.)

**Comment by StefanKarpinski** [comment]
Starting in the directory of the application seems like a really stupid default, for what it's worth.

**Comment by tkelman** [comment]
What else would explorer consider your current location to be?

**Comment by StefanKarpinski** [comment]
It's fine for Explorer to consider that your location, but it's a useless place to start working.

**Comment by tkelman** [comment]
Remember we're talking about console applications, so first a console has to be started somewhere to run the application. That location is the executable's own location, unless you start via a shortcut - this is one of the things shortcuts exist in order to handle.
