### ISSUE TITLE
Block coverage

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#18116]
I've poked around looking for whether an issue for this exists, but I didn't see any, and I asked on julia users and nothing. I'm getting pretty misleading coverage statistics with code blocks. For example,

```julia
d_reorder = Lazy.@> begin
        d
        DataStructures.OrderedDict()
        parameters_to_front
        dots_to_back
 end
```

In my code, even though the first line was called 32 times, coverage says that the rest of the lines were not called at all.

Here's another one. I've put the number of times the lines were called in brackets.

```julia
[36] function nonstandard1(f)
[54]      symbol_f = Symbol("@" * string(f) )
[54]      macro_f = Expr(:quote, Expr(:macrocall, symbol_f))
[54]      string_f = "See documentation of [`$f`](@ref)"
          quote
[0]           macro $f(args...)
[336]             esc($f(args...) )
              end
[0]           @doc $string_f $macro_f
          end
     end
```

Issues like this mean that the test coverage for ChainMap.jl is currently at 62%, while an accurate figure would be closer to 97% ish.

**Comment by ararslan** [comment]
Perhaps [Coverage.jl](https://github.com/JuliaCI/Coverage.jl) would be a more appropriate place for this issue?

**Comment by yuyichao** [comment]
Coverage collection is base issue.

**Comment by ararslan** [comment]
Sorry, didn't know.

**Comment by bramtayl** [comment]
I wasn't sure whether or not to post it here or in `Coverage.jl`. I'm glad I guessed right?

**Comment by bramtayl** [comment]
It looks like some packages have put quote blocks or macro begin blocks all on one line separated by ; to avoid these issues. Which works but makes code pretty unreadable for me.

**Comment by yuyichao** [comment]
Please provide a more complete script for reproducing.

**Comment by bramtayl** [comment]
Here's a simple script to run. I can't test this for sure because I'm not sure how to get coverage stats except via travis/coveralls, but I think that currently the lines `1` through `vcat(4)` won't get registered as covered. 

```julia
not_line(e) = true
not_line(e::Expr) = e.head != :line

function simple_chain!(a, b)
    insert!(b.args, 2, a)
    b
end

block_chain!(e) = reduce(simple_chain!, filter(not_line, e.args) )

macro block_chain(e)
    block_chain!(e)
end

Test.@test [1, 2, 3, 4] == @block_chain begin
    1
    vcat(2)
    vcat(3)
    vcat(4)
end
```

```

**Comment by yuyichao** [comment]
It's a bug in the macro. If the macro filters out the line numbers there's nothing the compiler can do to preserve those info.

**Comment by bramtayl** [comment]
Hmm. Ok. Well, is there a way to modify a chaining macro be able to properly keep the line number info?

**Comment by yuyichao** [comment]
Modify each line to be an assignment to a (`gensym`) variable and insert the argument to the call.

i.e. rewrite

```jl
<meta1>
x
<meta2>
vcat(2)
<meta3>
vcat(3)
<meta4>
vcat(4)
<meta5>
```

```jl
<meta1>
#1 = x
<meta2>
#2 = vcat(#1, 2)
<meta3>
#3 = vcat(#2, 3)
<meta4>
#4 = vcat(#3, 4)
#4
```

**Comment by bramtayl** [comment]
Great! I used your suggestions and coverage in ChainMap jumped to 94%. Note that the issues with my nonstandard macro still remain (the full code is above).
