### ISSUE TITLE
Vector-Matrix product again

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaLang/julia#18136]
While waiting for #18056 , I have found a suspicious method.

line 92 of matmul.jl is:
``(*)(A::AbstractVector, B::AbstractMatrix) = reshape(A,length(A),1)*B``

I think that this line is the reason why ``v*mx`` multiplication does not work at all.
The error message is the following:
```
julia> ones(3)*ones(3,3)
ERROR: DimensionMismatch("A has dimensions (3,1) but B has dimensions (3,3)")
 in gemm_wrapper!(::Array{Float64,2}, ::Char, ::Char, ::Array{Float64,2}, ::Array{Float64,2}) at .\linalg\matmul.jl:308
 in *(::Array{Float64,1}, ::Array{Float64,2}) at .\linalg\matmul.jl:86
```

If I redefine the method of line 92 in my workspace as:
```
import Base.*
(*)(A::AbstractVector, B::AbstractMatrix) = reshape(A,1,length(A))*B
```
then ``v*mx`` works and returns a 1xn matrix.

@andreasnoack @StefanKarpinski 
Note, that this is not the same issue as #18056.
Here I report something that should already work,
while there I would like the result to be a real 1-dimensional vector.

**Comment by andreasnoack** [comment]
This is the method that lets you compute `x*x'`. As mentioned the vector discussion is #4774 so I'll close here.

**Comment by GaborOszlanyi** [comment]
> This is the method that lets you compute ``x*x'``. 

Thank you. Then this is more serious than I have originally thought.
Based on the ``(*)(A::AbstractVector, B::AbstractMatrix)`` signature
we can only have a single method, which is only good for either ``v*v'`` or ``v*mx``.

The second usage is perfectly valid mathematics,
but only if it also returns a 1-dimensional vector.

I will try to summarize, and as you have suggested, move it to #4774.
