### ISSUE TITLE
provide a way for kill(p) to kill the whole process group

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18146]
Currently, `kill(p)` signals only a single process.  However, `spawn(detach(...))` creates a new process group, and killing the parent process does not necessarily kill the child processes.

I raninto this problem in IJulia, because on MacOS `p = spawn(detach(`ipython notebook`))` spawns a `bash` script that in turn spawns the actual `python` server, and doing `kill(p)` only kills the parent `bash` process and not the underlying `python` server, which is then orphaned.

(In fact, I would have thought that the _default_ of `kill` should have been to kill the whole process group.)

I don't see anything in `libuv` to provide this.  I guess you would have to call `getpgrp` on the process id to get the group id to kill?

**Comment by stevengj** [comment]
Hmm, it seems like (a) the process group includes Julia itself (i.e. on Unix there isn't one process group created per `spawn` — `uv_spawn` only calls `setsid()` before detaching a process) and (b) even killing Julia's process group doesn't kill `ipython` ... maybe `ipython` is doing something a bit odd?

So maybe there's not much we can do here, since the creation of process groups is under libuv's control?

**Comment by tkelman** [comment]
feature freeze is soon and no one has started working on this, moving to 1.0

**Comment by stevengj** [comment]
Not sure that this is even possible/desirable (see my comment above), so closing this unless the feature can be better defined.

**Comment by vtjnash** [comment]
Seems like you might be able to give it (`juypter`) a Pipe for it's STDIN, so that it will get a SIGPIPE when the parent (`julia`) died?
