### ISSUE TITLE
kill(process) should throw an exception rather than return -errno?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18145]
`kill(p)` currently returns 0 on success, -errno on failure, and -1 if the process was not running.  (This is undocumented, by the way.)  Shouldn't it throw an exception on failure instead?

**Comment by StefanKarpinski** [comment]
Proposal from @keno:

* return `true`/`false` indicating if the process was running.
* raise an error if the process failed.

I would add that we'd probably want a `force=false` keyword argument.

@JeffBezanson proposes renaming to `sigsend` (or something).

**Comment by JeffBezanson** [comment]
To continue quoting each other, @StefanKarpinski proposes something like `kill(p)` ensures the process stops in whatever way, e.g. succeeding if the process is already dead, while another function has lower-level signal-sending semantics.

**Comment by Keno** [comment]
Final proposal: Throw an error on `EPERM` and `EINVAL`, but silently allow `ESRCH`. On linux we should never get that because the kernel gives success if the process is a zombie. On windows it's racy, so we might get it.

**Comment by StefanKarpinski** [comment]
Can't you still get `ESRCH` if you've already successfully waited on the zombie previously? I.e. this should always work the first time, but could fail if you do it again.
