### ISSUE TITLE
Use printf instead of echo where suitable

### ISSUE THREAD

**Issue by LOAS2** [JuliaLang/julia#18175]
echo can have unspecified behavior which is very undesirable.
To stay on the safe side, it's good practice to always use printf.
echo "$var" can sting you whenever you do not have strict guarantees about the contents of var (for example that it contains a nonnegative integer).

READ - http://www.etalabs.net/sh_tricks.html

A failed attempt was done by a simple find-replace.
But @TotalVerb and @yuyichao showed how it's a bit more complicated than that.
https://github.com/JuliaLang/julia/pull/18158

Thanks.

**Comment by quinnj** [comment]
Is this still an issue? Something we want to do? It's not clear from the original post, but I assume the use of `echo` is in the build process somewhere?

**Comment by StefanKarpinski** [comment]
There's a bunch of uses of echo in the build process but they don't seem to be an issue since no one is complaining about them. May as well close this and react to actual problems.
