### ISSUE TITLE
openlibm doesn't build on arm as part of julia build

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#18174]
The Julia build invokes the openlibm build with `make ARCH=arm`, which the openlibm build does not like. Openlibm builds fine on arm and works there otherwise.

https://github.com/JuliaLang/openlibm/issues/143

Once we fix this issue, we can start using openlibm on arm just like the other platforms. Is it necessary to pass the `ARCH` argument to the openlibm build at all?

**Comment by nalimilan** [comment]
I don't think one actually needs to pass `ARCH` as long as `CFLAGS` includes `-march`.

**Comment by StefanKarpinski** [comment]
Bump, it's been a while since there was any comment here.
