### ISSUE TITLE
Add deprecation of `@unix_only` etc. to NEWS

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#18189]
The deprecation of `@unix_only`, `@osx` etc., should be added to `NEWS.md`.

**Comment by PallHaraldsson** [comment]
https://github.com/JuliaLang/julia/pull/18255 ok?

**Comment by PallHaraldsson** [comment]
This seems to be good to go, better than other guys version?). I didn't change wording elsewhere in NEWS: "The @windows_only and @osx family of macros" that was already in.. not asked for, could be separate if needed.
