### ISSUE TITLE
teach precompile about LambdaInfo

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#18184]
there's a serious (performance) bug in the way that precompile handles Expr(:invoke)

thanks to @keno for pointing this out to me

**Comment by StefanKarpinski** [comment]
Not release blocking.

**Comment by vtjnash** [comment]
tl;dr; incremental package loading doesn't work correctly. yes that is release blocking (also, the PR is ready)

**Comment by StefanKarpinski** [comment]
Ok, fair enough.
