### ISSUE TITLE
"must be explicitly imported to be extended"-error not always thrown

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#18181]
Compare the different results in executing these two code blocks:

```jl
julia> module Foo
           export foo
           foo(x) = x
       end
Foo

julia> using Foo

julia> foo(x::Int) = 3
foo (generic function with 1 method)
```

```jl
julia> module Foo
           export foo
           foo(x) = x
       end
Foo

julia> using Foo

julia> foo # Note this line
foo (generic function with 1 method)

julia> foo(x::Int) = 3
ERROR: error in method definition: function Foo.foo must be explicitly imported to be extended
```

Only in the second case is there an error getting thrown. Shouldn't this be the case in the first code block as well?

**Comment by eschnett** [comment]
I don't think the error message is correct. You can also define a function `Foo.foo` without importing it.

**Comment by vtjnash** [comment]
No, this is by design

**Comment by KristofferC** [comment]
Seems odd that printing a function should influence if you can override it or not...

**Comment by yuyichao** [comment]
Not `printing`, but using. This is to make exporting new functions always a non-breaking change.
