### ISSUE TITLE
Error running Pkg.update()

### ISSUE THREAD

**Issue by rjwaken** [JuliaLang/julia#18199]
Hello! I'm new to using a Mac and to using Julia (I'm looking for something faster than R), so this error may be a result of my inexperience with either. I'm trying to get Julia running through Atom, but keep getting error messages when I try to start Julia in Atom for the first time. 

If I run `Pkg.update()` in Julia (through the terminal), I get the following error:
```
INFO: Initializing package repository /Users/rjwaken/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out

ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in run at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:52
 in cd at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in init at pkg/dir.jl:50
 in cd at pkg/dir.jl:28
 in update at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
```

Any help would be appreciated!

**Comment by tkelman** [comment]
If you try to run `git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl` outside of Julia does it work?

**Comment by rjwaken** [comment]
It did after a little tweaking, but running that verbatim did shed light on what was happening:
First, I hadn't accepted the Xcode licensing agreement, which needed to be done. 
Second, it would appear that my employer has a firewall up, which can be gotten around by running `git clone -b metadata-v2 https://github.com/JuliaLang/METADATA.jl` instead.

Thanks!
