### ISSUE TITLE
The ci-skip and av-skip keywords should be determined automatically

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18190]
In addition to being able to manually specify whether Travis or Appveyor and friends should be skipped, there should be an automated mechanism that examines the diff, and looks which files changed.
- Documentation-only changes should only re-build the documentation
- Web documentation (markdown) changes should only re-validate their syntax
- If dependencies (`deps` directory) didn't change, a cached setup could be used (if that isn't already done)

**Comment by ViralBShah** [comment]
Given that most documentation is moving into .jl files like in #18041, this won't help. At that point, even doc only changes need to make sure they don't break the build. I believe we already cache the deps.

The only other use case is the manual, where this is perhaps easy to implement - but perhaps not worth the effort - given that we now have bought additional workers on Travis.

**Comment by martinholters** [comment]
The conversion in #18194 makes me wonder whether it would make more sense to check a diff whether it changes the build system and then rebuild the deps instead of using the cached ones.

**Comment by tkelman** [comment]
unfortunately the from scratch build takes very close to the timeout limit on travis, so it's not something we should occupy travis workers for too often. we should however have nanosoldier run automatically on nontrivial pr's whenever it's idle, that would also test the from scratch build at least on linux.

this issue sounds great in theory, but how are you proposing to implement the automatic commit diff content filter? I'll review any attempts at this, but it won't be straightforward.

**Comment by martinholters** [comment]
> how are you proposing to implement the automatic commit diff content filter?

For PRs where CI works on a merge commit, checking the output of `` git diff --name-only `git log -n 1 --pretty=format:%P` `` for critical files would be a start.

**Comment by KristofferC** [comment]
This seems unlikely to happen.

**Comment by StefanKarpinski** [comment]
Could be done with git post-commit hooks, but I don't think we need an open issue for it.
