### ISSUE TITLE
Constructor with partially specified type parameters fails to fallback to convert method

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#18203]
This works:

``` julia
julia> immutable Foo{X,Y}
           x::X
           y::Y
       end

julia> Base.convert{X,Y}(::Type{Foo{X}}, y::Y) = Foo{X,Y}(one(X), y)

julia> Foo{Int}(1.0)
Foo{Int64,Float64}(1,1.0)
```

So I would think this should work, but it doesn't:

``` julia
julia> immutable Foo{X,Y}
          x::X
          y::Y
          z::Int
       end

julia> Base.convert{X,Y}(::Type{Foo{X}}, y::Y, z::Int) = Foo{X,Y}(one(X), y, z)

julia> Foo{Int}(1, 1)
ERROR: MethodError: no method matching Foo{Int64,Y}(::Int64, ::Int64)
Closest candidates are:
  Foo{Int64,Y}{T}(::Any) at sysimg.jl:53
```

If I define the constructor it's looking for rather than the `convert` method, it works:

``` julia
julia> (::Type{Foo{X}}){X,Y}(y::Y, z::Int) = Foo{X,Y}(one(X), y, z)

julia> Foo{Int}(1, 1)
Foo{Int64,Int64}(1,1,1)
```

Note that I see similar behavior if I parameterize `z`'s type instead of restricting it to `Int`.

I guess this is similar to #15120, but with multiple fields? Version info just in case:

``` julia
julia> versioninfo()
Julia Version 0.5.0-rc2+1
Commit d259be5 (2016-08-18 20:15 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by tomaklutfu** [comment]
For correctness, `Base.convert{X,Y}(::Type{Foo{X}}, y::Y, z::Int) = Foo{X,Y}(one(x), y, z)` or `Base.convert{X,Y}(::Type{Foo{X}}, y::Y, z::Int) = Foo{X,Y}(one(X), y, z)` ?

**Comment by jrevels** [comment]
Sorry - the latter, I made a typo when copying the code over. Good catch, I've fixed it.

**Comment by mauro3** [comment]
Related: #17186

**Comment by yuyichao** [comment]
I don't think this is supposed to work. We only define fallback to convert for single argument. In fact, I don't think you are supposed to define `convert` with more than two arguments, it won't be called anywhere.
