### ISSUE TITLE
Add warning to Pkg.update() if updated modules were already imported

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18239]
If you do `Pkg.update()`, it should keep track of whether it updates any modules that were already imported into `Main`.   If so, it should print a warning message telling the user that they will need to restart Julia if they want to use the updated modules.

Should be pretty easy to implement.  (I would prefer that we *don't* print the warning unconditionally, e.g. if no imported modules were updated.)

See also #18150, cc @vtjnash.

**Comment by helgee** [comment]
Like this?
```julia
pkgsym = Symbol(pkg)
if isdefined(Main, pkgsym) && typeof(getfield(Main, pkgsym)) == Module
    warn("Package $pkg has been updated but it was already imported.")
    warn("Restart Julia to use the updated version.")
end
```

**Comment by stevengj** [comment]
@helgee, yes, something like that.   Note that you'll want to call `warn` only once (you can pass it a multi-line string).
