### ISSUE TITLE
Performance annotation docs shows SIMD slows down code by 10x

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#18231]
At http://docs.julialang.org/en/latest/manual/performance-tips/#performance-annotations  the docs talk about performance annotations. This section has a few confusing bits, which I'll list in order of decreasing importance.

The timings from the `@simd` example show `@simd` slowing down the code by almost 10x.
```
GFlop        = 1.9467069505224963
GFlop (SIMD) = 17.578554163920018
```
That seems like a poor result for something intended to speed up code.

The following example also confused me a few times, despite clearly showing `@fastmath` speeding up code
```
$ julia wave.jl
elapsed time: 1.207814709 seconds (0 bytes allocated)
4.443986180758243

$ julia --math-mode=ieee wave.jl
elapsed time: 4.487083643 seconds (0 bytes allocated)
4.443986180758243
```
While scanning the documentation to re-read sections my eye was drawn the the results 4.44... rather than the timings. This caused me to think that `@fastmath` had no effect on the timing, until I slowed down to read it more carefully.   I think it would be worth changing the example somewhat so that the result and the slower time don't both start with the same number.

**Comment by vtjnash** [comment]
flops are 1/time, so that's a 10x speedup, not slowdown

**Comment by eschnett** [comment]
The unit should probably be `GFlop/sec` instead of just `GFlop`, for clarity.

**Comment by eschnett** [comment]
Regarding `@fastmath`: We should probably just add a semicolon `;` to the command, which discards the output of the (here uninteresting) result.

**Comment by StefanKarpinski** [comment]
So the fixes here seem to be:

- change "GFlop" to "GFlop/sec"
- note that larger is better for "GFlop/sec"
- don't print return value for the `wave.jl` example

**Comment by ggggggggg** [comment]
I see that misinterpreted the GFlop statement, hopefully my revealed ignorance will aid future readers.
