### ISSUE TITLE
@macroexpand macro

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18240]
Writing `macroexpand(:(@foo x y z))` is a bit of a mouthful, but the expression passed to the `macroexpand` function needs to be quoted, of course. With a `@macroexpand` macro, this could be less annoying: `@macroexpand @foo x y z`

**Comment by simonbyrne** [comment]
I think the extra complications to the above are the handling of `$` in expressions (e.g. `@foo $x` may not expand correctly using `macroexpand(:(@foo $x))`), and his funny gensym names.

**Comment by jw3126** [comment]
A naive implementation would be as follows:
```
macro macroexpand(code)
    Expr(:call, :macroexpand, Expr(:quote, code)) |> esc
end
```
It would be good to have a concrete example that breaks this.

**Comment by simonbyrne** [comment]
```julia
macro foo(ex)
    isa(ex,Expr) && ex.head == :$ ? 7 : ex
end
```

**Comment by vtjnash** [comment]
the `macroexpand` also shouldn't be inside the `esc()` and only happens to work since you haven't put this inside a module and tested from a different module (with a different idea of what macroexpand means)

**Comment by jw3126** [comment]
Okay, if I run the function version of simonbyrne's example I get the same error:
```
julia> macroexpand(:(@foo $bar))
ERROR: UndefVarError: bar not defined
```
The problem is julia trying to interpolate bar into the expression, before the function gets even called. So this means getting the correct expansion of simonbyrne's example using a function is impossible. Do I see this correctly?

**Comment by jw3126** [comment]
I just meant it is impossible by using a function e.g. one has to write a macro which does not rely on a function, like the current `macroexpand` function.

**Comment by yuyichao** [comment]
The error has nothing to do with the function it's from the expression object. What you need is to properly convert the expression object before returning it from the macro.

**Comment by jw3126** [comment]
Thanks for the help and sorry for the confusion. It seems that `MacroTools` also has problems with the example:
```
julia> using MacroTools

julia> macro foo(ex)
          isa(ex,Expr) && ex.head == :$ ? 7 : ex
       end
@foo (macro with 1 method)

julia> @expand @foo $bar 
:bar
```

**Comment by jw3126** [comment]
```
macro macroexpand(code)
    Expr(:quote, ccall(:jl_macroexpand, Any, (Any,), code))
end
```
Passes the simonbyrne example. In this case the code gets passed directly to `:jl_macroexpand` so there is no chance for $ expansion to cause confusion. Any objections?

**Comment by yuyichao** [comment]
No need to use `ccall` the function call is **NOT** the problem.
It's a smart solution to do the expansion first. It changes the module the expansion takes place but that shouldn't be too bad for interactive use (and potentially better for that).

**Comment by jw3126** [comment]
Yes I know that the function call is not the problem, but $ interpolation that takes place before function is even called. 
So you suggest, to use the `macroexpand` function instead of the ccall? 
How to circumvent the $ interpolation then?
Do you need some recursive replacement thing like in MacroTools or is there an easy way?
And what is the problem with the ccall?

**Comment by yuyichao** [comment]
> Yes I know that the function call is not the problem, but $ interpolation that takes place before function is even called.

Only after the macro returns

> So you suggest, to use the macroexpand function instead of the ccall?

Yes

> How to circumvent the $ interpolation then?

It won't happen.

> Do you need some recursive replacement thing like in MacroTools or is there an easy way?

No

> And what is the problem with the ccall?

There's a function for it already.

**Comment by jw3126** [comment]
Thanks, finally I can see clear. I will put together a PR using
```
macro macroexpand(code)
    code_expanded = macroexpand(code)
    Expr(:quote, code_expanded)
end
```
