### ISSUE TITLE
lufact for sparse matrix pivot option error

### ISSUE THREAD

**Issue by garrettthomaskth** [JuliaLang/julia#18244]
base/sparse/umfpack.jl includes the following method definition for lufact

`lufact(A::SparseMatrixCSC, pivot::Type{Val{false}}) = lufact(A)`

This should likely be 

`lufact(A::SparseMatrixCSC, pivot::Type{Val{true}}) = lufact(A)`

because in lufact pivoting is on by default. 

The error is shown in the following example

```
A = speye(4)
A[1:2,1:2] = [-.01 -200; 200 .001]
F = lufact(A,Val{false})
F[:p]
```

which returns

```
julia> F[:q]
4-element Array{Int64,1}:
 3
 4
 1
 2
```

However it should return  

```
julia> F[:q]
4-element Array{Int64,1}:
1
2
3
4
```

because pivoting was turned off.

**Comment by jiahao** [comment]
Thanks for reporting the bug. Could you submit a PR?

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/18246
