### ISSUE TITLE
Any reason to not return a "DiagonalMatrix" type in eye()?

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#18247]
```julia
typeof(eye(3))
```
>Array{Float64,2}

A dense matrix is being returned always, which is not desired. It also makes code look uglier:

```julia
eigvals(eye(3), 1:2) # fails
eigavals(Symmetric(eye(3)), 1:2) # works, but... hmm...
```

**Comment by JaredCrean2** [comment]
One downside is this:
```julia
eye(3) -> Diagonal
eye(3,3) -> Array
eye(3,4) -> Array
```
eye(3) returning a different type than eye(3,3) seems a little weird to me, although that's not necessarily a deal breaker.  Alternatively, `Diagonal` could be extended to non-square matrices.

**Comment by juliohm** [comment]
What is the use of a m-by-n, m != n "identity" matrix?

**Comment by andreasnoack** [comment]
This is probably better suited for a Julia users discussion. The main reason to keep `eye` is to have a simple function for allocating a dense identity matrix. If you want an efficient identity matrix you should use `I`. We don't support `eigvals` for `I` but I don't really think a function for computing the eigenvalues of the identity matrix is necessary.

**Comment by martinholters** [comment]
Once I get to working on #16740 again, you could do `eye(Diagonal, 3, 3)` to explicitly ask for a `Diagonal`.

**Comment by juliohm** [comment]
I really don't see any benefit in having eye return a dense matrix nor in
the support for m != n? I expect Julia to be smart, save memory and
leverage the multiple dispatch with a more specific type. That is what I
signed for by choosing Julia in my research. Octave does that by default,
every function handling matrices returns the most specific type it can, at
least that is what I remember when I was an active contributor there.

-Júlio

**Comment by KristofferC** [comment]
Use `I` then which is what it is designed for? Don't have to allocate anything then.

**Comment by juliohm** [comment]
I never heard of I, and why is it called I and not eye? Shouldn't it be the
default behavior?

Can you explain the rationale for having a dense eye and this case with m
!= n?

**Comment by johnmyleswhite** [comment]
> This is probably better suited for a Julia users discussion.

To repeat this message: please do not use GitHub as a forum for speculative questions.

**Comment by KristofferC** [comment]
`I` is the identity element which seems to be what you are after. I guess it is called `I` because that is what it is usually denoted in math texts.

```jl
julia> I + rand(3,3)
3×3 Array{Float64,2}:
 1.43264    0.641925  0.577688
 0.141064   1.97744   0.914492
 0.0163053  0.912618  1.79047 
```

**Comment by juliohm** [comment]
That is true John, I'll open a thread in Google groups. Thank you.

**Comment by juliohm** [comment]
Thank you Kristoffer, my concern is two-fold: 1) why we are not taking
advantage of eye() structure in code that uses it? and 2) I can easily
overwrite a variable called I in my user code.

**Comment by timholy** [comment]
Use `Base.I` to be sure, then. Internally, Julia does make extensive use of `I`; it's up to you whether you use `eye` or `I`. Say you're initializing an algorithm that learns a matrix, and writes its updates inplace: use `eye`. Say you just want the identity: use `I`.

It's not julia's fault that other languages don't offer this kind of flexibility.

**Comment by juliohm** [comment]
Hi Tim,

Even if the algorithm is learning a matrix, is it not a good idea to start
with a specific type and let the operations carried on the type decide what
to output? It looks like we are asking too much from a user that might not
be aware of these internal details?

-Júlio

**Comment by StefanKarpinski** [comment]
Please move the conversation to julia-users.
