### ISSUE TITLE
add @callsuper macro

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18252]
As per https://github.com/JuliaLang/julia/pull/13123, we could add a `@supercall` macro that sweetens the interface to `invoke` and makes it more intuitive. My current implementation:

``` jl
macro callsuper(ex)
    ex.head == :call || error("@invoke requires a call expression")
    args = ex.args[2:end]
    types = Symbol[]
    vals = Symbol[]
    blk = quote end
    for arg in args
            val = gensym()
            typ = gensym()
            push!(vals, val)
            push!(types, typ)
            if isa(arg,Expr) && arg.head == :(::) && length(arg.args) == 2
                push!(blk.args, :($typ = $(esc(arg.args[2]))))
                push!(blk.args, :($val = $(esc(arg.args[1]))::$typ))
            else
                push!(blk.args, :($val = $(esc(arg))))
                push!(blk.args, :($typ = typeof($val)))
            end
    end
    push!(blk.args, :(invoke($(esc(ex.args[1])), ($(types...),), $(vals...))))
    return blk
end
```

Support for keyword arguments could be taken from https://github.com/JuliaLang/julia/pull/11165.

**Comment by tkelman** [comment]
do the types used in invoke actually have to be supertypes of the values provided?

**Comment by stevengj** [comment]
Or maybe `@callas foo(x, y::T)` could turn into `invoke(foo, (typeof(x), T), x,y)`

**Comment by fcard** [comment]
@tkelman No, they can all be concrete types and then be equivalent to a normal function call, although I wouldn't mind if `@supercall` checked that at least one of the types was a supertype, that would avoid unintended infinite recursion and whatnot, and avoid unnecessary invokes. Could be done at compile time with something like:
```julia
@generated function supercall{T<:Tuple}(f, types::Type{T}, vals...)
    @assert length(T.parameters) == length(vals) "A type must be given for every argument."
    atleastone = false
    for (t,a) in zip(T.parameters, vals)
        if a != t && a <: t
            atleastone = true
            break
        end
     end
    @assert atleastone "At least one supertype must be provided."
    quote
        invoke(f, types, vals...)
    end
end
```
(Although I've seen people trying to avoid `@generated` functions in base before, is that a thing?)
Then we change the definition of `@callsuper` a bit:
```diff
-    push!(blk.args, :(invoke($(esc(ex.args[1])), ($(types...),), $(vals...))))
+    push!(blk.args, :($supercall($(esc(ex.args[1])), $Tuple{$(types...)}, $(vals...))))
```
Also, @StefanKarpinski, `invoke` already does type assertation:
```julia
julia> invoke(+, Tuple{AbstractFloat, Int}, 1, 2)
ERROR: invoke: argument type error
```
But the better error message from the one inserted by the macro is welcome :P

**Comment by JeffBezanson** [comment]
As a new feature, can be considered post-1.0. Triage also feels it's unlikely we'll remove `invoke` for 1.0.

**Comment by Keno** [comment]
#38438
