### ISSUE TITLE
Docs for I

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#18250]
In #18247 , the `I` variable was mentioned, but (as far as I can see) there are no docs for it.

Just for clarification:

``` julia
julia> a = rand(3,3)
3x3 Array{Float64,2}:
 0.125392   0.162639  0.0208102
 0.0438847  0.253112  0.817613 
 0.877253   0.27941   0.94262  

julia> I + a
3x3 Array{Float64,2}:
 1.12539    0.162639  0.0208102
 0.0438847  1.25311   0.817613 
 0.877253   0.27941   1.94262  
```

**Comment by tomaklutfu** [comment]
http://docs.julialang.org/en/release-0.4/manual/linear-algebra/?highlight=identity#the-uniform-scaling-operator

**Comment by JaredCrean2** [comment]
Indeed, I did not see that.  However, searching for `Base.LinAlg.I` returns [no results](http://docs.julialang.org/en/latest/search/?q=Base.LinAlg.I&check_keywords=yes&area=default#), and the REPL help says that it is a `UniformScaling` of some kind, but not exactly what it is.

**Comment by stevengj** [comment]
```
help?> I
search: I IO if is Int in im Inf isa Int8 inv IPv6 IPv4 Int64 Int32 Int16 info imag ifft idct Inf64 Inf32 Inf16 Int128 issym isqrt isodd isnan isinf isdir irfft

  I

  An object of type UniformScaling, representing an identity matrix of any size.
```
This is a bit too terse to be useful, though.

**Comment by kshyatt** [comment]
@stevengj I agree! This would be a great first doc PR for someone who wants to make one.

**Comment by sudk1896** [comment]
@kshyatt: I'd like to take a stab at this. What do I have to do here ? Thanks.

**Comment by kshyatt** [comment]
Hi @sudk1896! That's great to hear. My suggestion would be to go into the `docs/stdlib/numbers.rst` to see how we've documented other constants (e.g. `pi` and `e`). Following that template, you could add a docstring for `I` to `docs/stdlib/linalg.rst` and then build the docs, commit your changes, and open the PR. Let me know if you would like more detailed instructions!

**Comment by sudk1896** [comment]
@kshyatt: AFAIK, I have to edit the doc-strings in the source and not the ```.rst``` since they are compiled automatically from the source. Also, which modules can I find the constants ```pi``` and ```e``` and ```I``` implemented in ? 
The docs don't include the links to the files that the functions are actually implemented in. 
Also, Shouldn't the docs point to the ```.jl``` files that the functions are implemented in instead of the ```.rst``` files, since that is where the doc-strings are originally generated from ?
Most of the python repos that I contributed to, did this.
Thanks.

**Comment by stevengj** [comment]
`I` (and its docstring) are in `base/linalg/uniformscaling.jl` (see #6472).  Things like `pi` are in `base/irrationals.jl`.

**Comment by vsart** [comment]
Given that the commit 573467a83442d8daae7bb386a12fe3914add7bbf already added some examples to the docstring (specifically [here](https://github.com/JuliaLang/julia/commit/573467a83442d8daae7bb386a12fe3914add7bbf#diff-2053e27c93f0362bfb456f36c77bb232R14)), is there still a need for more documentation or should this be closed?

**Comment by andreasnoack** [comment]
I think it is fine now that the example has been added.
