### ISSUE TITLE
Incorrect bounds check elimination

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#18261]
IIUC, `@inbounds` should only affect one level of inlining unless `propagate_inbounds` is specified, however, due to how inlining works, this is currently not true in certain cases.

``` jl
julia> @inline f(a) = a[1]
f (generic function with 1 method)

julia> @inline g(a) = f(a)
g (generic function with 1 method)

julia> function k(a)
           @inbounds x = g(a)
           return x
       end
k (generic function with 1 method)

julia> @code_warntype k(Int[])
Variables:
  #self#::#k
  a::Array{Int64,1}
  x::Int64

Body:
  begin 
      $(Expr(:inbounds, true))
      x::Int64 = (Base.arrayref)(a::Array{Int64,1},1)::Int64
      $(Expr(:inbounds, :pop)) # line 3:
      return x::Int64
  end::Int64

julia> k(Int[])
0
```

The issue here is that the `Expr(:return)` is not included when adding the `inbounds` metadata during inlining. A simpler case where `f(a)` and `g(a)` are not oneliner and have a simpler `return` statement is also currently wrong on master but is fixed in https://github.com/JuliaLang/julia/pull/18260 (see the added test).

Maybe we can just wait for fully linear IR?

**Comment by blakejohnson** [comment]
I'll take a look at this next week.

**Comment by vtjnash** [comment]
this is basically just a special case of #9765

**Comment by yuyichao** [comment]
Is it? The issue here is that we always need to inline

```jl
return foo(...)
```

as

```jl
Expr(:inbounds, false)
SSAValue(n) = foo(...)
Expr(:inbounds, :pop)
return SSAValue(n)
```

Unless `foo` is guaranteed to be not affected by boundscheck status. I don't think the effect_free check is wrong here (or is used at all).
