### ISSUE TITLE
can't redirect STDOUT and STDERR to `DevNull`

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#18268]
It seems that with recent changes (#17522) it's become more important to make sure that we have a reader set up in a `redirect_stdout` call before we start writing to it (see [this ZMQ fix](https://github.com/JuliaLang/ZMQ.jl/pull/112/files)). To throw away output it seems reasonable that you'd want to do `redirect_stdout(DevNull)`, but right now you get `ERROR: MethodError: no method matching redirect_stdout(::Base.DevNullStream)`.

**Comment by StefanKarpinski** [comment]
Bump.

**Comment by goretkin** [comment]
For anyone else coming to this, though it's maybe not as portable, one can do:
`redirect_stdout(open("/dev/null", "w”))`
(thanks @sbromberger ).

**Comment by StefanKarpinski** [comment]
Closing as dup of #22879.
