### ISSUE TITLE
Update dictionary value without recomputing hash

### ISSUE THREAD

**Issue by dbeach24** [JuliaLang/julia#18282]
Finding and replacing a value in a dictionary is a common use case, for example, when maintaining a hash of counters or running totals.  At present, Base does not expose any mechanism for accomplishing this in one shot.  Conventional solutions require re-computing the hash.

I propose that we add the following function for all `Associative` types:

```julia
update!(f::Function, a::Associative, key, default) = (a[key] = f(get(a, key, default))
```

This function would be specialized for the various dictionary implementations to avoid repeat computation of the hash & slot.  Common updater functions might add or increment a value, for example:

```julia
totals = Dict{String,Float64}()
for item in some_items
    update!(t -> t + item.value, totals, item.kind, 0.0))
    # computes hash(item.kind) just once
end
```

Instead of:
```julia
totals[item.kind] = get(totals, item.kind, 0.0) + item.value  # 2 hashes
```

Or (even worse):
```julia
key, value = item.kind, item.value
totals[key] = haskey(totals, key) ? totals[key] + value : value  # 3 hashes!
```

Timing tests show that even when the key is a simple `Int`, there is a substantial performance difference between these three approaches:

1. one hash -- 0.143845 seconds (54 allocations: 94.406 KB)
2. two hashes -- 0.176049 seconds (54 allocations: 94.406 KB)
3. three hashes -- 0.200050 seconds (5.64 k allocations: 350.717 KB)

Keys which are more costly to hash should show an even bigger performance improvement.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/12157
