### ISSUE TITLE
missing sub2ind ambiguity detection confuses inference

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#18307]
came across this while investigating why the inference of `isassigned` is bad. it seems the `sub2ind` definitions cause several problems for type intersection. for example:

``` julia
julia> @which sub2ind((1,))
ERROR: no method found for the specified argument types
 in which(::Any, ::Any) at ./reflection.jl:466

julia> sub2ind((1,)) # supposed to throw a MethodError (ambiguity)
1
```

this is caused by the intersection of the following 3 methods: 

``` julia
sub2ind{N,T<:Integer}(inds:: Union{Base.Indices{N}, Dims{N}}, I::AbstractArray{T,1}...) at abstractarray.jl:1482
sub2ind(::Base.DimsInteger) at abstractarray.jl:1429
sub2ind(dims::Base.DimsInteger, I::Integer...) at abstractarray.jl:1433
```

testing with:

``` julia
julia> g{N,T<:Integer}(inds::Dims{N}, I::AbstractArray{T,1}...) = 1
julia> g(::Base.DimsInteger) = 2
julia> g(dims::Base.DimsInteger, I::Integer...) = 3
```

with all 3, `@which` thinks none will be called, but actually 2 gets (incorrectly) called
with just method 1 and 2, `@which` thinks that 1 will definitely be called (but 2 is actually – correctly – called)
with just 1 and 3, it fails correctly
with just 2 and 3, it works correctly

**Comment by tkelman** [comment]
use milestones, not backport pending label if there isn't a PR yet

**Comment by yuyichao** [comment]
Another missing ambiguity from #17003 that might be related

```jl
julia> abstract A{T}

julia> type B{T} <: A{T}
       end

julia> f1(::A{Int}) = 1
f1 (generic function with 1 method)

julia> f1(::B) = 2
f1 (generic function with 2 methods)

julia> f1(B{Int}())
2
```

Here `B` isn't more specific than `A{Int}` even though it is more specific than `A`.

**Comment by vtjnash** [comment]
probably will get fixed by #18457?

**Comment by pabloferz** [comment]
The OP example seems to be working now.

**Comment by JeffBezanson** [comment]
This has a test in test/ambiguous that claims the methods should be ambiguous, but aren't currently. I'm not sure they really are ambiguous though.
