### ISSUE TITLE
Nightly binary "Target architecture mismatch." on travis

### ISSUE THREAD

**Issue by kdmurray91** [JuliaLang/julia#18317]
Hi all,

On multiple projects I work on, we get the following error during CI runs on travis.

```
$ julia -e 'versioninfo()'
ERROR: Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}.
```

E.g. https://travis-ci.org/kdmurray91/CountMin.jl/jobs/156745332 and https://travis-ci.org/BioJulia/Bio.jl/jobs/156719769

I couldn't find any current issues for this, and am unsure where to raise this issue (here or w/ Travis CI folks).

Any advice is appreciated.

Cheers,
Kevin

**Comment by yuyichao** [comment]
Supposedly fixed by https://github.com/JuliaLang/julia/pull/18311, wait for the next nightly.
