### ISSUE TITLE
type stability of map and empty arrays

### ISSUE THREAD

**Issue by mhauru** [JuliaLang/julia#18314]
I find it desirable that in `map(f, T[])`, if `f` is type stable on `T`, then `map` would return an empty array of the correct type. At the moment it returns an empty array of type `T`.

I ran into this when trying to do roughly this:
```
function f(x::Vector)
    y = map(symbol, x)
    return f(y)
end

function f(x::Vector{Symbol})
    # Do fun.
end
```

**Comment by cstjean** [comment]
#7258 It's not a simple issue.

**Comment by TotalVerb** [comment]
For what it's worth, this problem should be gone in v0.5, to be released soon.

```julia
julia> map(Symbol, [])
0-element Array{Symbol,1}
```

**Comment by mhauru** [comment]
That's indeed worth quite a lot.

Also, I found a duplicate: https://github.com/JuliaLang/julia/issues/12513
