### ISSUE TITLE
Performance of sleep ;)

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#18321]
For times < 1ms the sleep function sleeps too long:

```
using BenchmarkTools
@benchmark sleep(1e-4)
```
BenchmarkTools.Trial: 
  samples:          4567
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  368.00 bytes
  allocs estimate:  6
  minimum time:     18.53 μs (0.00% GC)
  median time:      1.09 ms (0.00% GC)
  mean time:        1.09 ms (0.00% GC)
  maximum time:     1.19 ms (0.00% GC)

**Comment by KristofferC** [comment]
```
help?> sleep
search: sleep selectperm selectperm! sylvester SimpleVector isleaftype specialized_bitwise_unary specialized_bitwise_binary

  sleep(seconds)

  Block the current task for a specified number of seconds. The minimum sleep time is 1 millisecond or input of 0.001.
```

**Comment by nalimilan** [comment]
Shouldn't it raise an error when a too short time is requested?

**Comment by yuyichao** [comment]
It can be inconvenient since all the callers need to make sure the time step is long enough and will be inconsistent since we are not (and can't) raise error if the step if not of a integer multiple of 1ms (the resolution).

**Comment by vtjnash** [comment]
What's "too short"? If I'm running a server optimized for throughput, I would say that 1 second it "too short". If I installed an RTOS kernel, then I might say 1 µs is too long. The docs should probably say "block for at least the specified time interval", since the actual sleep will be arbitrarily longer.
