### ISSUE TITLE
cumsum loses the sign of zero imaginary part

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18336]
```
julia> cumsum(1.7 - 0.0im + (0:7))
8-element Array{Complex{Float64},1}:
  1.7+0.0im
  4.4+0.0im
  8.1+0.0im
 12.8+0.0im
 18.5+0.0im
 25.2+0.0im
 32.9+0.0im
 41.6+0.0im
```
(I would have expected `-0.0im` imaginary parts.)

Similarly for `cumprod`.

**Comment by jiahao** [comment]
Similarly for `cumprod`. Probably a zero issue?

```jl
julia> cumprod!(Array{Complex128}(1), -0.0im + (0:0))
1-element Array{Complex{Float64},1}:
 0.0+0.0im
```

**Comment by jiahao** [comment]
Is it too horrible a hack to simply change `zero(...)` to `-zero(...)` in this line https://github.com/JuliaLang/julia/blob/40c0fc6b958c961c961c8bad77bc0a5abc7468bd/base/arraymath.jl#L445 ?

**Comment by stevengj** [comment]
Or we could just use `@inbounds c[i1] = v[i1]`.   I don't think calling `op` accomplishes anything there.  Even if `0+v[i1]` is of a different type than `v[i1]`, the assignment to `c[i1]` should do any necessary conversion.

**Comment by TotalVerb** [comment]
Would it be really breaking if `zero(Float)` returned `-0.0`? Technically, the real floating point additive identity is `-0.0`...

**Comment by stevengj** [comment]
Note that this is not specific to complex arithmetic:
```
julia> cumsum([-0.0])
1-element Array{Float64,1}:
 0.0
```

**Comment by eschnett** [comment]
Well -- if we're not changing `zero` to return the additive identity, then we can either special-case IEEE numbers here, or introduce a new function `additive_identity` that falls back to `zero`, but handles representations with negative zeros correctly.

Another option would be to change `cumsum`'s algorithm to work in the same way as `sum`, probably by special-casing empty arrays.

By the way:
```Julia
julia> cumsum([])
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
 in cumsum(::Array{Any,1}) at ./arraymath.jl:480
```

**Comment by stevengj** [comment]
@eschnett, see my comment above for  a simple fix.

**Comment by stevengj** [comment]
`cumsum` already special-cases empty arrays.  It looks sufficient to special-case length-1 arrays as well.

**Comment by eschnett** [comment]
2-element arrays also don't work correctly:
```Julia
julia> cumsum([-0.0, -0.0])
2-element Array{Float64,1}:
 0.0
 0.0
julia> sum([-0.0, -0.0])
-0.0
```

**Comment by TotalVerb** [comment]
That definitely is an argument to start at the additive identity, whether or not `zero` is changed to return it.

**Comment by oscardssmith** [comment]
I think I should probably mention that there is an argument over whether isequal(-0.0, 0.0) should return true. #18485

**Comment by timholy** [comment]
I'm not sure one can unambiguously say this was wrong. For example:
```jl
julia> 1.7 - 0.0im + convert(Vector{Complex128}, [0:7;])
8-element Array{Complex{Float64},1}:
 1.7+0.0im
 2.7+0.0im
 3.7+0.0im
 4.7+0.0im
 5.7+0.0im
 6.7+0.0im
 7.7+0.0im
 8.7+0.0im
```
If one considers that promotion should happen before arithmetic, then the given result is simply a consequence of the fact that `-0.0 + 0.0 === 0.0`.
