### ISSUE TITLE
Possible for #= to not interrupt tokens?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#18340]
Suppose I have a giant integer literal

```julia
const a = 11111111111111111111111111111111111111111111
```

and I want to wrap this onto multiple lines. I thought that

```julia
const a = 11111111111111111111111#=
=#111111111111111111111
```

might work, but this actually parses as an implicit multiplication. I suppose the `#=` interrupts the lexing of the numeric literal. Would it be possible/desirable to handle `#=` at an earlier lexing stage? Or maybe somehow resume the previous lexing context after reading the `=#`?

On another note, `#==#` is certainly the most interesting name for a multiplication operator I've seen in any language :laughing:.

**Comment by TotalVerb** [comment]
@davidanthoff, do you mind providing a more specific critique? It is not clear to me what the downside would be.

**Comment by davidanthoff** [comment]
1) It looks like a hack to me, i.e. trying to solve a line-break issue with a comment, 2) I believe it would make implementation of something like JuliaLang/JuliaParser.jl#22 much more difficult.

I don't feel strongly about this, though, this was just my gut reaction. There are probably other people here that can have a much more grounded opinion about this, so feel free to ignore my reaction.

**Comment by TotalVerb** [comment]
I also would really want a concrete syntax tree, and I see your point about how block comments inside tokens can make that much tougher. At the same time, it would be really nice to have a way to break lines... I suppose the following string macro would work?

```julia
macro ilb_str(s::String)
    parse(replace(s, "\n", ""))
end
```

Then

```julia
ilb"""
111111111111111111
111111111111111111
111111111111111111
"""
```

works great.

**Comment by davidanthoff** [comment]
I like that, given that this is probably really a rare corner case, solving this via a macro and not in the parser seems like a good idea!

**Comment by TotalVerb** [comment]
String macros are easily one of my favourite Julia features. Right, well this doesn't need to be in `Base` then.

**Comment by ihnorton** [comment]
> On another note, #==# is certainly the most interesting name for a multiplication operator I've seen in any language 😆.

Seems like a bug. Perhaps the parser should treat multiline comment-starts like a newline?

There's this oddity too:

```
julia> t= 11111111111111111111111 # foo
          44
44
julia> t= 11111111111111111111111
          44
44
```

**Comment by TotalVerb** [comment]
@ihnorton Doesn't seem like a bug to me. `x #= comment =# + y` is a valid use case for comments, and that should not become a new line. Implicit multiplication only happens when there is no spacing at all, which is expected. `x#==#y`.

I don't see why your example is odd. Should the single-line comment remove the newline?

**Comment by ihnorton** [comment]
> I don't see why your example is odd. Should the single-line comment remove the newline?

It's unrelated to the comment, really. Both should be parse errors, just like `t = 1 2 3`.

**Comment by TotalVerb** [comment]
But there's a new line there. It's more similar to `t = 1; 2`, which is perfectly fine.
