### ISSUE TITLE
copy! : indexed assignment not defined for linspace, range

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#18358]
Hit this issue while doing a test of QuantEcon.jl which passes fine in Julia 0.4.6 but fails in 0.6 current.
From QuantEcon:
```
Testing markov_approx.jl: Error During Test
  Got an exception of type ErrorException outside of a @test
  indexed assignment not defined for LinSpace{Float64}
   in copy!(::LinSpace{Float64}, ::LinSpace{Float64}) at ./multidimensional.jl:614
   in tauchen(::Int64, ::Float64, ::Float64, ::Float64, ::Int64) at /home/colin/.julia/v0.6/QuantEcon/src/markov/markov_approx.jl:76
   in macro expansion; at /home/colin/.julia/v0.6/QuantEcon/test/test_markov_approx.jl:15 [inlined]
```
Since this is related to copy! I ran a test
```
a = linspace(1,4,3)
b = linspace(1,4,3)
copy!(b,a)
ERROR: indexed assignment not defined for LinSpace{Float64}
 in copy!(::LinSpace{Float64}, ::LinSpace{Float64}) at ./multidimensional.jl:614
```
And the same happens for range objects but is fine for arrays.
It seems reasonable that copy should be defined at least for linspace, so I'm starting the report here, but can move elsewhere if advised.

```
versioninfo()
Julia Version 0.6.0-dev.488
Commit 79a7172* (2016-09-05 06:23 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)




```

**Comment by yuyichao** [comment]
Linspace is immutable so this can't be done.

FWIW, I don't really think this is a good argument against `linspace` returning a immutable type.

**Comment by yuyichao** [comment]
And the discussion of `LinSpace` vs `Vector` should be continued at https://github.com/JuliaLang/julia/issues/14420 (which is possibly an argument against `LinSpace`) or https://github.com/JuliaLang/julia/pull/17408

**Comment by colbec** [comment]
OK so I will report in QuantEcon. Thanks.

**Comment by colbec** [comment]
Also related is https://github.com/QuantEcon/QuantEcon.jl/issues/132
