### ISSUE TITLE
Markdown.readme does not work on packages in a non-default LOAD_PATH

### ISSUE THREAD

**Issue by bluesmoon** [JuliaLang/julia#18351]
If you add a directory to `LOAD_PATH`, and add a package in there, then `Markdown.readme("PackageName")` is unable to find `README.md`.

This happens because `Markdown.readme` uses `Pkg.dir` to determine the location of the package, which according to https://github.com/JuliaLang/julia/issues/18329 is absolutely the wrong thing to do.

Please fix to use the right path for the selected package.

**Comment by KristofferC** [comment]
Markdown doesn't have this capability anymore.
