### ISSUE TITLE
0.5 documentation error on Mac

### ISSUE THREAD

**Issue by LeoK987** [JuliaLang/julia#18350]
Opening with iBooks got the following error in section Linear Algebra:

“This page contains the following errors:

error on line 261 at column 421: PCDATA invalid Char value 8
Below is a rendering of the page up to the first error.”

Excerpt From: unknown. “Julia Language 0.5.0-dev documentation.” iBooks.

**Comment by LeoK987** [comment]
I am not sure what more info is needed.  The document “Julia Language 0.5.0-dev documentation” when opened with iBooks on MacBook Pro with OSX 10.11.6 shows the above error.

**Comment by yuyichao** [comment]
What document are you opening? A file? A URL?

**Comment by LeoK987** [comment]
Sorry.  The epub version of the documentation.

**Comment by yuyichao** [comment]
Both calibre and kchmviewer have no issue opening the page and other form of the document seems fine so it's probably either an sphinx bug or a iBook bug.

**Comment by KristofferC** [comment]
Since the docsystem is revamped, I don't think this is applicable anymore.
