### ISSUE TITLE
Passing redefined function as argument

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#18353]
The following code, where we pass a function as an argument, redefine it and pass it again,
```julia
q(n) = 0
@show map(q, 1:1)
q(n) = 1
@show map(q, 1:1)
```
doesn't work as expected on 0.5 and 0.6, outputting:
```
map(q,1:1) = [0]
WARNING: Method definition q(Any) in module Main at ...
map(q,1:1) = [0]
```
I am guessing it's due to #265 and the fact that every function is a separate type now.

However, unlike most of #265, it's a regression compared to 0.4, since there we get what we would expect:
```
map(q,1:1) = [0]
map(q,1:1) = [1]
```

Sorry if this has already been discussed, but I was not able to find any mention of this. I do feel that perhaps this is something that should be addressed in 0.5, since the regression makes REPL work a bit more tedious.

**Comment by yuyichao** [comment]
Dup of #265

**Comment by yuyichao** [comment]
And your case is discussed in #265 already https://github.com/JuliaLang/julia/issues/265#issuecomment-242102435

**Comment by mortenpi** [comment]
Sorry, missed that. However, will the fix of #265 get backported to 0.5 as well? It only has the 0.6 milestone at the moment.

**Comment by yuyichao** [comment]
No this is unlikely going to be fixed in 0.5.

**Comment by mortenpi** [comment]
In that case I would maintain that it's somewhat of an annoying regression compared to 0.4 :disappointed:. At least for me the REPL workflow where I keep redefining functions in the global scope is pretty common.

**Comment by mortenpi** [comment]
Should it at least be mentioned in `NEWS.md`? And while there is a `WARNING` now, perhaps that could be made more informative, stating something along the lines of "already called/compiled functions using this function or receiving it as an argument, will still use the old definition and hence may not work as expected".

**Comment by tkelman** [comment]
sure. fastest way would be to propose a wording which we could iterate on in a PR

**Comment by cstjean** [comment]
Is there any work-around? That's a big downer for interactive development in notebooks.

**Comment by iamed2** [comment]
The workaround would be to use anonymous functions:
```julia
julia> q(n) = 0
q (generic function with 1 method)

julia> map(x->q(x), 1:1)
1-element Array{Int64,1}:
 0

julia> q(n) = 1
WARNING: Method definition q(Any) in module Main at REPL[1]:1 overwritten at REPL[5]:1.
q (generic function with 1 method)

julia> map(x->q(x), 1:1)
1-element Array{Int64,1}:
 1
```
