### ISSUE TITLE
cumsum! does not check array sizes

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18363]
```
julia> cumsum!([0,0], 1:4)

signal (11): Segmentation fault: 11
```

**Comment by stevengj** [comment]
Also, it looks like the code assumes 1-based indexing; PR forthcoming that should fix both this and #18336.

**Comment by stevengj** [comment]
Another problem:
```
julia> cumsum(Any[])
ERROR: BoundsError: attempt to access 0-element Array{Any,1} at index [1]
 in cumsum(::Array{Any,1}) at ./arraymath.jl:448
```
which comes because the `_cumsum_type(v) = typeof(v[1]+v[1])` definition is wrong.  Grr.

**Comment by stevengj** [comment]
And `cumsum(Any[1, 2.3])` throws an `InexactError`.   I think `_cumsum_type` is just wrong and we should use `similar(v)` in all cases.

**Comment by andreasnoack** [comment]
`Bool`s are not stable under addition.

**Comment by stevengj** [comment]
Oh, right.

**Comment by nalimilan** [comment]
`promote_type(+, ...)`?

**Comment by stevengj** [comment]
We already have an `r_promote` that is used for reductions; it seems better to be be consistent with that.  In any case, please move this discussion to #18364.
