### ISSUE TITLE
32bit ARM download link is broken

### ISSUE THREAD

**Issue by LTGZZ** [JuliaLang/julia#18383]
Hi,
I'm sorry to put that here but there's no admin mail on the website.
https://status.julialang.org/download/linux-arm leads to an error.

**Comment by yuyichao** [comment]
Please report to the [julialang.github.com](https://github.com/JuliaLang/julialang.github.com/issues/new) repo instead.

**Comment by tkelman** [comment]
That isn't the repo for status.julialang.org. ARM nightlies haven't succeeded in long enough that the most recent build has expired and been automatically deleted from julianightlies.
