### ISSUE TITLE
A statement like `sometuple[index]` executed without error in a code branch when `sometuple` should **not** have a value at all 

### ISSUE THREAD

**Issue by zuo** [JuliaLang/julia#18385]
Very strange behaviour -- looks like having executed code that should **not** have been executed at all:

```
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> function f()
           if g
               x = (0, 42)
           else
               y = (1, 43)
           end
           println(g)
           println(x[2])
           println(y[1])
       end
f (generic function with 1 method)

julia> g = true
true

julia> f()
true
42
1

julia> g = false
false

julia> f()
false
42
1
```

What is interesting, the code starts to crash (**as expected**, with `UndefVarError`) when we either *use arrays instead of tuples* or try *referring to the variables themselves* without using the getindex syntax:

```
julia> function f2()
           if g
               x = (0, 42)
           else
               y = (1, 43)
           end
           println(g)
           println(x)
           println(y)
       end
f2 (generic function with 1 method)

julia> f2()
false
ERROR: UndefVarError: x not defined
 in f2() at ./REPL[5]:8

julia> g = true
true

julia> f2()
true
(0,42)
ERROR: UndefVarError: y not defined
 in f2() at ./REPL[5]:9

julia> function f3()
           if g
               x = [0, 42]
           else
               y = [1, 43]
           end
           println(g)
           println(x[2])
           println(y[1])
       end
f3 (generic function with 1 method)

julia> f3()
true
42
ERROR: UndefVarError: y not defined
 in f3() at ./REPL[9]:9

julia> g = false
false

julia> f3()
false
ERROR: UndefVarError: x not defined
 in f3() at ./REPL[9]:8
```

Checked with julia v0.5.0-rc3 and rc2.

(The problem was reported by the user huckl3b3rry87 at the julia IRC chat -- see: https://gitter.im/JuliaLang/julia?at=57cf5209f5a156f56489b57a).

**Comment by huckl3b3rry87** [comment]
I also mentioned that the behavior is as one (I) might expect when testing on julia 0.4.6:
`
**In [1]:**
function f()
           if g
               x = (0, 42)
           else
               y = (1, 43)
           end
           print("$g $(x[2]) $(y[1])")
end

**Out[1]:**
f (generic function with 1 method)

**In [2]:**
g = true

**Out[2]:**
true

**In [3]:**
f()
LoadError: UndefVarError: y not defined
while loading In[3], in expression starting on line 1
 in f at In[1]:7
`
So, this version of julia throws an error.

**Comment by yuyichao** [comment]
This is due to the allocation elimination pass, fix on the way.

**Comment by huckl3b3rry87** [comment]
So, is this issue fixed on the "Bleeding-edge" version of julia only? Or is it also going to be fixed on the something more stable like: Release Candidates (v0.5.0-rc3)

**Comment by yuyichao** [comment]
Wait for backport.

**Comment by huckl3b3rry87** [comment]
Not trying to rush you on the "backsuport", but I am getting quite a few errors doing different things in julia and I am not sure if they are related. Is there an eta on how long it might take to build the "backsupport"?

**Comment by timholy** [comment]
Most likely between a week and more than a month; it looks like rc4 has been released, and there may not be an rc5 (rc4 may become 0.5.0), and then it will have to wait for 0.5.1. 

If you build julia from source, you can apply this patch yourself, of course.
