### ISSUE TITLE
Unable to build Mongo package in El Capitan using 0.4.6 ver

### ISSUE THREAD

**Issue by nenandu** [JuliaLang/julia#18400]
Hi, I have recently switched to El Capitan and have installed Julia with below command.
**brew cask install julia**. For the first time I was seeing the version 0.4.6
Now I have opened the REQUIRE file located in /Users/mango/.julia/v0.4/ and added the below packages. 
**Mongo, Gadfly, PyPlot**
Now in the Julia REPL, I fired the command **Pkg.update()** to install and build the packages.
It seems Mongo package requires **LibBSON** as a dependency and has installed and build prior to Mongo.
The error is see here is:

_Pkg.build("Mongo")
INFO: Building Homebrew
Updated 1 tap (homebrew/core).
==> Updated Formulae
azure-cli           mercurial           pidcat              pypy              
INFO: Building LibBSON

WARNING: deprecated syntax "{a=>b, ...}" at /Users/mango/.julia/v0.4/LibBSON/deps/build.jl:12.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /Users/mango/.julia/v0.4/LibBSON/deps/build.jl:23.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /Users/mango/.julia/v0.4/LibBSON/deps/build.jl:26.
Use "Dict(a=>b, ...)" instead.
INFO: Building Mongo

WARNING: deprecated syntax "{a=>b, ...}" at /Users/mango/.julia/v0.4/Mongo/deps/build.jl:12.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /Users/mango/.julia/v0.4/Mongo/deps/build.jl:23.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /Users/mango/.julia/v0.4/Mongo/deps/build.jl:26.
Use "Dict(a=>b, ...)" instead.
==> Installing mongo-c from staticfloat/juliatranslated
Error: Cannot install staticfloat/juliatranslated/mongo-c because conflicting formulae are installed.

  libbson: because mongo-c installs the libbson headers

Please `brew unlink libbson` before continuing.

Unlinking removes a formula's symlinks from /Users/mango/.julia/v0.4/Homebrew/deps/usr. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
================================[ ERROR: Mongo ]================================

LoadError: failed process: Process(`/Users/mango/.julia/v0.4/Homebrew/deps/usr/bin/brew install staticfloat/juliatranslated/mongo-c`, ProcessExited(1)) [1]
while loading /Users/mango/.julia/v0.4/Mongo/deps/build.jl, in expression starting on line 26

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Mongo had build errors.

 - packages with build errors remain installed in /Users/mango/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Mongo")`
 - build a single package by running its `deps/build.jl` script

======================================================================_

**How do I build the Mongo package?**

**Comment by tkelman** [comment]
Not an issue with this repository. See https://github.com/pzion/Mongo.jl/issues/19.
