### ISSUE TITLE
Pkg.add "Invalid reference name"

### ISSUE THREAD

**Issue by odow** [JuliaLang/julia#18402]
I'm in the process of switching to 0.5 and I ran into issues installing PlotlyJS.

It looks like it has an issue with the `sl/js->julia` branch (https://github.com/spencerlyon2/PlotlyJS.jl/tree/sl/js-%3Ejulia).

I've also tried deleting the cache at `.julia/.cache/PlotlyJS` to no avail.

![plotly](https://cloud.githubusercontent.com/assets/8177701/18337377/1f3450b0-75e4-11e6-8fe7-8e6044568a40.png)

**Comment by tkelman** [comment]
maybe related to https://github.com/spencerlyon2/PlotlyJS.jl/issues/70 ?

**Comment by tkelman** [comment]
Or maybe @spencyerlyon2 might need to delete the branch at https://github.com/spencerlyon2/PlotlyJS.jl/tree/sl/js-%3Ejulia, I think I had seen this once before where libgit2 tries to create files for some branch names that might not be valid as Windows file names?

**Comment by odow** [comment]
Pinging @spencerlyon2 since Tony didn't quite get the spelling right.

**Comment by tkelman** [comment]
this is https://github.com/libgit2/libgit2/issues/3622

**Comment by spencerlyon2** [comment]
I deleted all the stale branches on PlotlyJS.jl github.

**Comment by KristofferC** [comment]
Obsolete with new package manager.
