### ISSUE TITLE
Ubuntu 14.04 recent update gives warning with julia 0.4.6 binary

### ISSUE THREAD

**Issue by ahmedfaroukyehia** [JuliaLang/julia#18407]
On starting Julia, I now get the warning

```WARNING: Error during initialization of module GMP:
ErrorException("The dynamically loaded GMP library (version 6.1.0 with __gmp_bits_per_limb == 64)
does not correspond to the compile time version (version 5.1.3 with __gmp_bits_per_limb == 64).
Please rebuild Julia.")```

This did not show up before the update.

**Comment by yuyichao** [comment]
Is this the generic linux binary?

**Comment by ahmedfaroukyehia** [comment]
Yes from the stable PPA.

**Comment by yuyichao** [comment]
No that's not the generic binary.

**Comment by yuyichao** [comment]
The PPA is in general not well maintained and is not the recommended way to install julia on ubuntu until that situation changes.

**Comment by StefanKarpinski** [comment]
The recommended installation can be found here: http://julialang.org/downloads/. Download the Generic Linux tgz file and untar it somewhere and you should be able to run Julia from there.
