### ISSUE TITLE
document abspath(p, p2...)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18406]
`abspath(p1, p2...)` is equivalent to `abspath(joinpath(p1, p2...))`, and has been for several versions of Julia now, but this isn't documented.

**Comment by sudk1896** [comment]
@stevengj: I'd like to take a stab at this. My suggestion would be to include a note saying that both these function calls i.e. ```abspath(p1, p2...)``` and ```abspath(joinpath(p1, p2...))``` are similar. Is that fine ?

**Comment by stevengj** [comment]
That's right.  (In fact, they are exactly equivalent, not just similar.)

**Comment by sudk1896** [comment]
@stevengj : Okay. I am working on this and will submit a PR. I have a question, Are docstrings included in the actual code or are they separately compiled in the ```.rst``` files. Do I have to edit the docstrings in the ```.rst``` files or the docstrings in the source code ? In python libraries that I've had to contribute, I always had to change the docstrings in the source code.

**Comment by stevengj** [comment]
You edit the docstring in the source code, and then run `./julia doc/genstdlib.jl` to re-generate the rst files.

**Comment by sudk1896** [comment]
Here is what I did:
1. Edited the doc-string in /base/path.jl
2. Then ran ./julia doc/genstdlib.jl
3. make html in the doc folder.
Even then I am unable to see the changes. Am I missing something ? Also after changing the doc-string in the source, I am unable to see any changes in the ```.rst``` files.
I am new to Julia. Thanks.

**Comment by yuyichao** [comment]
You need to run the script

> [with the newly compiled julia](https://github.com/JuliaLang/julia/pull/18483#discussion_r78608535)

**Comment by nsmith5** [comment]
@stevengj #21626 addresses this. Have a look and see what you think?

**Comment by tkelman** [comment]
reopen if any problems
