### ISSUE TITLE
New method causes resorting of old methods

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#18419]
From julia-users, ref https://groups.google.com/d/msg/julia-users/IsRlOLGeEs8/RRwrs3u2AQAJ

Shortened version:
```julia
julia> @which pi*pi
*(x::Irrational, y::Irrational) at irrationals.jl:88

julia> module Erratic2
           typealias DummyUnion Union{Irrational,AbstractFloat}
           abstract DummyReal <: Real
           import Base.*
           *(x::DummyUnion, y::DummyReal) = "wow"
       end
Erratic2

julia> pi*pi
------------------------------------------------------------------------------------------
ErrorException                                          Stacktrace (most recent call last)
[#1] — *(::Irrational{:π}, ::Irrational{:π})
       ⌙ at promotion.jl:256

* not defined for Irrational{:π}

julia> @which pi*pi
*{T<:Number}(x::T, y::T) at promotion.jl:256
```
This arises because of the following reordering of "old" methods (highlighting from `kdiff3`):
![methmul](https://cloud.githubusercontent.com/assets/1525481/18381927/426104a6-7644-11e6-902f-2f63e0f95785.png)

Note that the method at `promotion.jl:256` is now above the method at `irrationals.jl:88`.

**Comment by tomaklutfu** [comment]
dup #18390 . I had already reported but no attraction there.

**Comment by timholy** [comment]
Thanks for reporting, and pointing out the duplication.
