### ISSUE TITLE
Dealing with multiple alternative libraries

### ISSUE THREAD

**Issue by rennis250** [JuliaLang/julia#1842]
(See https://github.com/JuliaLang/julia/pull/1840)

Current possible solutions:

- Call jl_lookup_soname earlier in the library search process - @JeffBezanson 
- Add relevant paths to LD_LIBRARY_PATH - @ViralBShah 

Different implementations of the "same" library can coexist, but at the moment, they can cause problems for Julia users. For instance, my Fedora machine uses the nvidia closed-source drivers, but retains the open-source nouveau drivers as a backup. This produces two OpenGL libraries:

Open-source - /usr/lib64/libGL.so
Closed-source - /usr/lib64/nvidia/libGL.so.1

When told to open the "libGL" library, Julia uses the /usr/lib64/libGL.so library, since ".so.1" is not an element in the extensions list (src/dlload.c).  If Julia uses the /usr/lib64/libGL.so library (with or without the RTLD_GLOBAL flag), all OpenGL commands result in a blank screen without errors.  Using ldd on compiled C-OpenGL code showed that they linked to /usr/lib64/nvidia/libGL.so.1. Adding ".so.1" to the head of the extensions list in src/dlload.c fixes this problem.  It's agreed all around that this is NOT a satisfactory or permanent solution. 

To be honest, I'm not too familiar with what is happening here. I followed @pao 's recommendation of using dlopen's RTLD_GLOBAL flag, which is necessary to properly open nested libraries when using OpenGL, but it didn't seem to do anything.

These are the only references to libGL in the output of ldconfig:

libGL.so.1 -> libGL.so.304.64
libGL.so.1 -> libGL.so.1.2

The linking structure in /usr/lib64 is as follows:

/usr/lib64/libGL.so -> /usr/lib64/libGL.so.1
/usr/lib64/libGL.so.1 -> /usr/lib64/libGL.so.1.2
/usr/lib64/libGL.so.1.2

/usr/lib64/nvidia/libGL.so.1 -> /usr/lib64/nvidia/libGL.so.304.64
/usr/lib64/nvidia/libGL.so.304.64

In /etc/ld.so.conf.d, there is an nvidia-lib64.conf file, with the following entry:

/usr/lib64/nvidia

From what I can tell, the nvidia drivers (or the Fedora/RPMFusion package management systems) are violating the standard conventions for libraries?

My hope is to find a solution that doesn't require an average user of the OpenGL.jl package to start editing system files/environment variables.

--Rob

**Comment by ViralBShah** [comment]
Let's reopen if necessary.
