### ISSUE TITLE
No error when overwriting `show` in RC3, RC4 and dev

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#18427]
In a new REPL:

```julia
julia> show(x) = 1
show (generic function with 1 method)
```
with no error message shown about importing `Base.show`. 
This is on RC3, RC4 and 0.6-dev.481

**Comment by yuyichao** [comment]
I believe this is intentional and there never was an error. The error we had was for operators since they used to be implicitly imported.

**Comment by dpsanders** [comment]
I can overwrite operators without importing them as well:
```
julia> +(x,y) = 3
+ (generic function with 1 method)
```

**Comment by yuyichao** [comment]
Yes, because the deprecation period ends and now they are treated the same as normal functions.

**Comment by dpsanders** [comment]
This seems like a bad idea to me. Could you point me to the discussion about it, please?

**Comment by yuyichao** [comment]
Which one? Override bindings is never an error AFAICT (since 0.3 at least) so that adding API won't break people's code.

**Comment by dpsanders** [comment]
So now I am confused then:
```julia
Version 0.5.0-rc4+0 (2016-09-09 01:43 UTC)

julia> show(3)
3
julia> show(x) = 1
ERROR: error in method definition: function Base.show must be explicitly imported to be extended

julia> show(x::Float64) = 1
ERROR: error in method definition: function Base.show must be explicitly imported to be extended
```

**Comment by yuyichao** [comment]
Correct, if you've used the function, then we won't swap the definition behind you.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/issues/18181

**Comment by dpsanders** [comment]
I understand the reasoning, but I would like to at least be warned that I'm overwriting a function because I forgot to do `import Base.show`.

**Comment by yuyichao** [comment]
So always error means every addition of API is breaking.
Never error (even after you used it) means that either the function is changed implicitly or every use is an implicit `import`.
The current version at least makes sure valid use should never raise an error. It is true that it can be confusing in some cases but AFAICT no one have proposed an alternative that is clearly better.

**Comment by yuyichao** [comment]
I think there's valid use of locally defined `show` in packages for used as fully qualified name. This is a job for linting to warn you possible misuse.
