### ISSUE TITLE
Fixed sidebar for docs

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/julia#18429]
I didn't like that the sidebar was always fighting you as you clicked around the docs, so I made it `position: fixed`.

This was done with the css below. I don't really know where to put it though, so I opened an issue instead of a PR

Also, I kind of made the assumption that Julia users are on newer browsers, so we don't have to use (`-webkit-flex`, `-ms-flex`, etc)

-----------

```
.wy-grid-for-nav nav.wy-nav-side {
  display: flex;
  position: fixed;
  flex-direction: column;
  height: 100%;
  padding-bottom: 0;
}

.wy-grid-for-nav nav.wy-nav-side .wy-side-nav-search {
  flex: 0 0 auto;
}

.wy-grid-for-nav nav.wy-nav-side .wy-menu-vertical {
  flex: 1 1 auto;
  overflow-y: scroll;  
}
```

**Comment by yuyichao** [comment]
This is probably more a sphinx issue than a julia one....

**Comment by djsegal** [comment]
@yuyichao ok, closing it then
