### ISSUE TITLE
Is Base.print_matrix broken?

### ISSUE THREAD

**Issue by dbeach24** [JuliaLang/julia#18439]
For one thing, the docs don't seem right.  There is no `sz` tuple accepted by this function.

```jl
help?> Base.print_matrix
  print_matrix(io, X) composes an entire matrix, taking into account the screen size. If X is too
  big, it will be nine-sliced with vertical, horizontal, or diagonal ellipsis inserted as
  appropriate. Optional parameters are screen size tuple sz such as (24,80), string pre prior to
  the matrix (e.g. opening bracket), which will cause a corresponding same-size indent on
  following rows, string post on the end of the last row of the matrix. Also options to use
  different ellipsis characters hdots, vdots, ddots. These are repeated every hmod or vmod
  elements.
```

Secondly, even though my displaysize is defined:

```jl
julia> displaysize(STDOUT)
(40,100)
```

`Base.print_matrix` completely ignores this because of the following test:

```jl
    if !get(io, :limit, false)
        screenheight = screenwidth = typemax(Int)
    else
        sz = displaysize(io)
        screenheight, screenwidth = sz[1] - 4, sz[2]
    end
```

On my machine, evaluating `get(STDOUT, :limit, false)` is `false`, so I basically never get pretty-printing of matrices to the terminal.

Is anyone else experiencing this?

**Comment by JeffBezanson** [comment]
> so I basically never get pretty-printing of matrices to the terminal

`STDOUT` is the "undecorated" standard output stream; the REPL internally uses STDOUT wrapped in an IOContext with its default printing parameters.

**Comment by tkelman** [comment]
is this exported, should the docstring be in the rst?
