### ISSUE TITLE
Keyword arguments can hide objects from global scope when evaluating default value

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#18433]
In some cases, it would sound natural to have a keyword argument call a function of the same name to get it's default value. Yet this doesn't work:
```julia
julia> f(x; start=start(x)) = x[1]
f (generic function with 1 method)

julia> f(1:3)
ERROR: UndefVarError: start not defined
 in f(::UnitRange{Int64}) at ./REPL[10]:1

```

This is unfortunate, as both the keyword argument and the function names are part of public APIs: using different names would introduce inconsistencies in the API. The best workaround I could find to avoid this is to do `const _start = start` and use that internal function to get the default argument.

**Comment by yuyichao** [comment]
So what's the proposed solution here? Breaking

```jl
julia> function g(;a=b, b=1)
           (a, b)
       end
g (generic function with 1 method)

julia> g(b=2)
(2,2)
```

?

**Comment by nalimilan** [comment]
Not sure how it could work, but when evaluating the default for a keyword argument, no binding using that particular keyword argument's name should be defined yet. There's no point in referencing an argument before it's been assigned its default value anyway.

**Comment by yuyichao** [comment]
This follows the scope rules for keyword arguments that they are evaluated in the same scope and is equivalent to

```jl
b = 2
a = b
```

And it's one way to require either `a` or `b` to be specified.

Breaking this rule will likely make the keyword arguments scope even more complicated. This doesn't seem to be too different from any local symbol overwrite (for one thing you can't use the function `start` in the function body either and no tweak of the scope rule can help with that). It is easily solvable by using (module) local alias or simply with qualified names so IMHO it doesn't worth changing.

**Comment by nalimilan** [comment]
It's easy (though annoying) when you know what's happening, but the error is likely to be confusing for inexperienced users. It also means the actual signature with `start=_start(x)` isn't going to match the one shown in the docs with `start=start(x)` (unless you want to also explain what's `_start` in the docs). It could be annoying for automated checks of docstrings <-> code consistency.

So not a terrible issue, but IMHO still something which would be nice to have if possible.

Maybe all arguments could be renamed to generated symbols for the evaluation of defaults? That substitution would be done in all expressions *except* for arguments referencing themselves (where the only possible meaning is to refer to a global).

**Comment by yuyichao** [comment]
As I said you can use qualified name, i.e. `Base.start`. No need to explain what `_start` is.

Variable rename is just a worse way to tweak the scope rule and I think it'll be more confusing in general.

**Comment by nalimilan** [comment]
Yeah, in my case the module name was quite longer and I need to repeat this for many methods, so the underscore strategy is more appealing.

Anyway, feel free to close if I'm the only one to think it could be confusing.

**Comment by StefanKarpinski** [comment]
Keyword arguments should work the same way as positional argument, imo:

```jl
julia> f(a=b, b=1) = (a,b)
f (generic function with 3 methods)

julia> b = :foo
:foo

julia> f()
(:foo,1)

julia> b
:foo
```

I.e. each successive argument is evaluated as if in its own scope (let).

**Comment by yuyichao** [comment]
At least one important difference is that kw args can be specified in arbitrary order but not for optional arguments

**Comment by StefanKarpinski** [comment]
They can be provided in any order, but they are specified in the method definition in one specific order – that should be the order they're evaluated in.

**Comment by johnmyleswhite** [comment]
> They can be provided in any order, but they are specified in the method definition in one specific order – that should be the order they're evaluated in.

This seems really counter-intuitive. I might reasonably think that keyword arguments would get evaluated left-to-right, but this will teach me that the order of keyword arguments I use isn't relevant, only the order that the author chose.

**Comment by StefanKarpinski** [comment]
The defaults are evaluated from left to right; the provided values are also evaluated from left to right. Where does the confusion stem from? The only change is that each successive default should be evaluated in its own let block, effectively.

**Comment by dhoegh** [comment]
See #17240 for a related issue.

**Comment by JeffBezanson** [comment]
I believe it is a dup of that issue actually.
