### ISSUE TITLE
Missing print statement when using function(...)(...)

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#18454]
Browsing through the code accompanying https://groups.google.com/forum/#!topic/julia-users/Oip2KaZNiKg I was a bit baffled by the way functions are defined.
```
function(name::SomeType)(args...)
    body
end
```
Is this "supposed to work"? It does on RC3, but it doesn't print the usual message following a function definition if you specify `SomeType`:
  
```jlcon
julia> function(q::Int32)(x)
           x+1
end
```
although it does it you don't supply a type.
```jlcon
julia> function(q)(x)
           x+1
end
q (generic function with 1 method)
```
Also, it seems to work on RC3 but the following doesn't work on RC1
```jlcon
julia> function(q::Int32)(x)
                  x+1
              end

julia> q(2)
ERROR: UndefVarError: q not defined
```

**Comment by yuyichao** [comment]
This is call overload syntax and it is supposed to work.

**Comment by KristofferC** [comment]
```
julia> function(q::Int32)(x)
                         x+1
                     end

julia> Int32(5)(3)
4
```

**Comment by pkofod** [comment]
Thanks for the answer (and the example @KristofferC ), but is it intended that there is no message after the enter? And is this form documented? I couldn't find it in the docs.

**Comment by yuyichao** [comment]
The doc is linked in the julia-users thread and is at http://docs.julialang.org/en/latest/manual/methods/#function-like-objects . It is expected that it doesn't print the "generic function" message since this does not define a generic function.

**Comment by KristofferC** [comment]
Not related to issue but I think the docs should have an example of where to put the parameter in a parameterized call overloaded function. At least for me it is not obvious.
