### ISSUE TITLE
Define broadcast[!] in Base, and import/extend in module Broadcast?

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#18462]
The module `Broadcast` defines and exports `broadcast[!]`, and `Base` `importall`s `Broadcast` in `sysimg.jl`. This arrangement makes defining `broadcast[!]` methods prior to that point in `sysimg.jl` impossible (as `importall`'ing `Broadcast` then throws an existing-identifier-conflict warning for / does not import `broadcast[!]` from `Broadcast`). Simultaneously, `Broadcast`'s import in `sysimg.jl` can only happen so early (and only later than some existing vectorized function definitions that should transition to compact broadcast syntax, which is how I ran into this).

Instead, should `Base` define `broadcast[!]`, and `Broadcast` import/extend `broadcast[!]` from `Base`? Better solutions? Thanks and best!

**Comment by yuyichao** [comment]
Use case? I think we can certainly do so if there's need for it.

**Comment by Sacha0** [comment]
> Use case?

I ran into this while transitioning vectorized `float` methods to compact broadcast syntax. Those `float` methods live in `float.jl`, which `sysimg.jl` includes prior to where `broadcast.jl` can be included / `Broadcast` imported.

**Comment by Sacha0** [comment]
What would be the best approach? Is naively including `function broadcast[!] end` directly in `Base` and early in the `sysimg.jl` hierarchy the correct approach? If so, does an appropriate location for such definitions exist? Thanks!

**Comment by stevengj** [comment]
#17623 implements exactly this, so it should close this issue eventually if we don't do it sooner.

**Comment by stevengj** [comment]
(Though it doesn't implement `broadcast!` in Base.)
