### ISSUE TITLE
SubString error in Pkg.add on master

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#18486]
When I try to add a package on master, I get a `SubString` error. Not sure if the fault is on my side, but I just built it (latest commit is `d0e7684dd0ce867e1add2b88bb91f1c4574100e0`). I get
```julia
julia> Pkg.add("BenchmarkTools")
ERROR: ArgumentError: invalid SubString index
 in SubString{String}(::String, ::Int64, ::Int64) at ./strings/types.jl:17
 in replace(::String, ::Regex, ::String, ::Int64) at ./strings/util.jl:354
 in Base.Pkg.Reqs.Requirement(::String) at ./pkg/reqs.jl:22
 in read(::IOStream) at ./pkg/reqs.jl:70
 in open(::Base.Pkg.Reqs.#read, ::String) at ./iostream.jl:152
 in read at ./pkg/reqs.jl:74 [inlined]
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at ./pkg/entry.jl:23
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:363
 in sync_end() at ./task.jl:314
 in macro expansion at ./task.jl:330 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:50
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:69
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in add(::String) at ./pkg/pkg.jl:100
```
Not really sure how find the problem, so reporting it here. Can others replicate?

**Comment by KristofferC** [comment]
Can you add a `print(content)` above https://github.com/JuliaLang/julia/blob/d0e7684dd0ce867e1add2b88bb91f1c4574100e0/base/pkg/reqs.jl#L22 and rerun?

**Comment by pkofod** [comment]
> Can you add a print(content) above https://github.com/JuliaLang/julia/blob/d0e7684dd0ce867e1add2b88bb91f1c4574100e0/base/pkg/reqs.jl#L22 and rerun?

It prints "�Vâ�S�n[s�"

![error](https://cloud.githubusercontent.com/assets/8431156/18488034/fe7761b0-79f7-11e6-88cf-027d13f292b6.png)

**Comment by KristofferC** [comment]
Just a hunch but what about reverting https://github.com/JuliaLang/julia/pull/18325..

**Comment by pkofod** [comment]
I'll see if it works. I am a bit surprised this isn't caught by any of the `Pkg.add`-related tests. Is that because they don't add any "real" packages?

**Comment by KristofferC** [comment]
Does any of these error?

```jl
cd(Pkg.dir())
Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.1/requires")
Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.2/requires")
Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.3/requires")
Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.4/requires")
Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.5/requires")
```

Is it only for BenchmarkTools or for all packages? Is your METADATA nicely synced with remote?

**Comment by pkofod** [comment]
```Julia
julia> cd(Pkg.dir())

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.1/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])
 Base.Pkg.Reqs.Requirement("Compat","Compat",[0.0.0-,∞),AbstractString[]) 

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.2/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])      
 Base.Pkg.Reqs.Requirement("Compat 0.7.20","Compat",[0.7.20,∞),AbstractString[])

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.3/requires")
0-element Array{Base.Pkg.Reqs.Line,1}

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.4/requires")
0-element Array{Base.Pkg.Reqs.Line,1}

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.5/requires")
0-element Array{Base.Pkg.Reqs.Line,1}
```

I just tried to `Pkg.update()`
```julia
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of FixedPointNumbers...
INFO: Updating cache of Compat...
INFO: Updating cache of Colors...
ERROR: ArgumentError: invalid SubString index
 in SubString{String}(::String, ::Int64, ::Int64) at ./strings/types.jl:17
 in replace(::String, ::Regex, ::String, ::Int64) at ./strings/util.jl:354
 in Base.Pkg.Reqs.Requirement(::String) at ./pkg/reqs.jl:22
 in read(::IOStream) at ./pkg/reqs.jl:70
 in open(::Base.Pkg.Reqs.#read, ::String) at ./iostream.jl:152
 in read at ./pkg/reqs.jl:74 [inlined]
 in parse(::String) at ./pkg/reqs.jl:112
 in update(::String, ::Set{String}) at ./pkg/entry.jl:393
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:69
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in update() at ./pkg/pkg.jl:210
```

**Comment by pkofod** [comment]
Okay, so after updating with an error (as shown above) I now get
```julia
julia> cd(Pkg.dir())

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.1/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])
 Base.Pkg.Reqs.Requirement("Compat","Compat",[0.0.0-,∞),AbstractString[]) 

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.2/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])      
 Base.Pkg.Reqs.Requirement("Compat 0.7.20","Compat",[0.7.20,∞),AbstractString[])

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.3/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])      
 Base.Pkg.Reqs.Requirement("Compat 0.7.20","Compat",[0.7.20,∞),AbstractString[])

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.4/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])      
 Base.Pkg.Reqs.Requirement("Compat 0.7.20","Compat",[0.7.20,∞),AbstractString[])

julia> Pkg.Reqs.read("METADATA/BenchmarkTools/versions/0.0.5/requires")
2-element Array{Base.Pkg.Reqs.Line,1}:
 Base.Pkg.Reqs.Requirement("julia 0.4","julia",[0.4.0,∞),AbstractString[])      
 Base.Pkg.Reqs.Requirement("Compat 0.7.20","Compat",[0.7.20,∞),AbstractString[])
```

**Comment by pkofod** [comment]
Okay, I guess it's solved now. Wiped `.julia/v0.6/` and did `Pkg.init()` on @KristofferC s suggestion. It now works.
```julia
julia> Pkg.init()
INFO: Initializing package repository /home/pkm/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl

julia> Pkg.add("BenchmarkTools")
INFO: Installing BenchmarkTools v0.0.5
INFO: Installing Compat v0.9.2
INFO: Package database updated
```
It is still weird that I got the original message, as I had done nothing in `.julia/v0.6`, it was basically from a fresh master build. Anyway, now I am no longer able to reproduce the issue, so I guess it should be filed as "user error" unless someone else has the same problem later on.

**Comment by tkelman** [comment]
But we don't know what you may have done or how it got into that state, which is not very reassuring that no one else will hit the same situation.

**Comment by KristofferC** [comment]
The thing I can imagine causing this is a file corruption of one of the `require` files in METADATA. But then METADATA should have failed to update though due to checksum failures..?

**Comment by tkelman** [comment]
@pkofod was this on a network file system or did anything strange happen to your disk maybe?

**Comment by pkofod** [comment]
No, it was on a completely standard desktop setup - nothing special at all. I realize that it would be very helpful to know how I got in the "bad state", but I really have no idea - sorry. Obviously, as I have no idea how it happened, I cannot say for sure that I didn't simply do something stupid, but I don't recall doing anything special.

I downloaded the master using git clone (I had no v0.6 folder at the time, I had only run v0.4 official releases and v0.5 RCs) to a fresh folder, `sudo make`, did some standard REPL things. Returned the next day, did some changes to sparse concatenation, rebuilt, and then I wanted to install `BenchmarkTools` and the `SubString` error occured. Reverted my changes, rebuilt, and then the error was still there. Deleted the `v0.6` folder in `~/.julia/` and ran `Pkg.init()`, and then I could `Pkg.add("BenchmarkTools")`.

I should have backed up the `v0.6` folder instead of deleted it.

**Comment by tkelman** [comment]
Can you try replaying your `.julia_history` and what you can remember that happened outside of it? Maybe setting `JULIA_PKGDIR` to a temporary new location for testing. If this is a real bug then it would be ideal if we could come up with a reproducible set of steps to get it to happen, but if that proves too difficult then I guess we keep our fingers crossed that it doesn't happen to anyone else and was a one-time-only fluke.

**Comment by pkofod** [comment]
I won't be able to share my `.julia_history` for various reasons, but I can try to replay the relevant parts tomorrow, and see if I can mess up my package folder again. I've never really manually handled `.julia_history`, but I suspect it will also have everything I ran in the other versions of Julia as well, right? That might make it a bit difficult to be sure what was run in v0.6 and what was run in 0.5RCs, but maybe I can remember it when I see it :) Don't have time right now, but I'll have a look tomorrow.
