### ISSUE TITLE
Trouble with Generator Expressions in Julia

### ISSUE THREAD

**Issue by saarush2010** [JuliaLang/julia#18481]
sum(1/n^2 for n=1:3) throws the following error:

"syntax: missing comma or ) in argument list"

The syntax seems to match the guideline in http://docs.julialang.org/en/release-0.5/manual/arrays/?highlight=comprehension. What am I missing?

**Comment by swt30** [comment]
Which version of julia are you using (do `versioninfo()` at the prompt)? This syntax was only added in 0.5.

**Comment by yuyichao** [comment]
That's exactly the error thrown on 0.4 so I assume it's on 0.4.

**Comment by saarush2010** [comment]
Julia Version 0.4.6. Thanks swt30 and yuyichao.

**Comment by swt30** [comment]
Julia 0.5 is very close to release and <http://docs.julialang.org> currently points to version 0.5 of the documentation, so it's an understandable mistake!

**Comment by saarush2010** [comment]
Good point, version tab on bottom right shows 0.5 whilst for others shows 0.4. I'll check this going forward.
