### ISSUE TITLE
Sending Ctrl-C to REPL while running a threaded function Problem 0.5-rc4

### ISSUE THREAD

**Issue by jean-pierreBoth** [JuliaLang/julia#18489]
While running some significant computation in a function having  a  threaded loop with 4 threads
(OK as "top" shows julia with 400% cpu with real effect on time) , if  I interrupt the computation
it sems that it kills only one thread and not the whole group.
I get back  the REPL, but   top command shows  julia  300% .

Not so bad  , just a disagreement...

**Comment by yuyichao** [comment]
We do need better support for inter-thread communication which might include sending signals to thread but this is the expected default behavior and unlikely going to change.

**Comment by tkelman** [comment]
should we document it then?

**Comment by yuyichao** [comment]
http://julia.readthedocs.io/en/latest/stdlib/c/?highlight=sigint#Base.disable_sigint

**Comment by jean-pierreBoth** [comment]
RTFM as usual. .
Thanks!



via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.38&pv=6.0.1&source=email_footer_2] On Wed, Sep 14, 2016 at 1:22 PM, Yichao Yu < notifications@github.com [notifications@github.com] > wrote:
http://julia.readthedocs.io/en/latest/stdlib/c/?highlight=sigint#Base.disable_sigint [http://julia.readthedocs.io/en/latest/stdlib/c/?highlight=sigint#Base.disable_sigint]
