### ISSUE TITLE
equality, comparison, hashing and sorting

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18487]
Creating an umbrella issue for all issues involved in equality and comparison.

**Comment by StefanKarpinski** [comment]
We're experimenting with using [ZenHub](https://www.zenhub.com/), which allows you to create "Epics", which are more functional umbrella issues than normal. Unfortunately, they seem to have zero useful content if you're not using ZenHub.

**Comment by Keno** [comment]
Didn't have much useful content to me even with the extension, though refreshing fixed it.
![screen shot 2016-09-13 at 3 27 39 pm](https://cloud.githubusercontent.com/assets/1291671/18488266/a9b4810c-79c6-11e6-967c-a20d2d665f2d.png)

**Comment by tkelman** [comment]
more functional how? ideally this could at least be translated to a list of cross links or something outside the extension

**Comment by ararslan** [comment]
You could make this a [project](https://github.com/JuliaLang/julia/projects) (new GitHub functionality, woooooo)

**Comment by TotalVerb** [comment]
Interesting timing.

**Comment by StefanKarpinski** [comment]
I need to convert this to a project or something since our use of ZenHub has petered out.

**Comment by tkelman** [comment]
Let's close this here, reopen during 1.0-dev as a Julep with a design proposal?
