### ISSUE TITLE
move PriorityQueue out of Base?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18497]
Before resolving issues like https://github.com/JuliaLang/julia/issues/4372, we should figure out if we really want something like a priority queue in Base Julia.

**Comment by ViralBShah** [comment]
Seems like something that could live in DataStructures.jl.

**Comment by timholy** [comment]
I sometimes wonder if it would be useful in some kind of work scheduler, once multithreading becomes more common. But that's pure speculation...
