### ISSUE TITLE
Include release notes in release binaries

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#18501]
Please put an appropriate version of NEWS.md in the standard downloadable packages.
For extra credit, add a view_julia_news function to display it in the REPL (and the equivalent for Juno).

Also point out somewhere obvious that a local version of the manual is already included. This sort of thing gets to be important when several versions are available in the wild, and is particularly helpful to people working offline.

**Comment by malmaud** [comment]
What is a "standard" package?

**Comment by tkelman** [comment]
Guessing you mean release binaries, not packages in the non-base Julia code sense. We should probably put that file (and the license file, and maybe one or two others) somewhere in the install tree, maybe in `share/doc/julia` ?

**Comment by RalphAS** [comment]
Of course; sorry, I should have said release binaries.  The license is already in there, at the top of the tree.  That's a sensible location for the Linux versions (installed with tar by people who should instinctively look at what it gives them).  The challenge is how to point other users to an appropriate version of the release notes, perhaps via the result of ?help in the REPL and the like.

**Comment by tkelman** [comment]
Yep, there it is: https://github.com/JuliaLang/julia/blob/fdf374875bf6e0a63c182c33d1824ff36605901a/Makefile#L456

We can totally just add NEWS.md at the same place I think. The REPL isn't the greatest viewer for long-form markdown files like that, but at least putting it in the binaries should be a start.

**Comment by RalphAS** [comment]
resolved by #25476
