### ISSUE TITLE
a little issue

### ISSUE THREAD

**Issue by xj19850612** [JuliaLang/julia#18503]
I just make a simple test ,12.5-8.8,the result should be 3.7,but it is 3.6999999999 in julia

**Comment by ViralBShah** [comment]
This is not the right place to ask questions. Please use the julia-users list for that. Also, this issue has been brought up several times on the list.

**Comment by cdsousa** [comment]
@xj19850612, that's due to the limited precision of floating point numbers. You get the same in Python, C/C++, ...
