### ISSUE TITLE
Compiling Benchmarks Folder returns undefined functions, libraries

### ISSUE THREAD

**Issue by Knoxort** [JuliaLang/julia#18502]
Currently trying to compile benchmarks on a A53 board, the highkey. Was able to compile the OpenBLAS library:
make TARGET=ARMV8

and install, after adding the target line to this level as well:
make TARGET=ARMV8 PREFIX=/opt/Openblas install

However, making for the benchmarks folder doesn't seem to work. The result is below. A similar error is very apparent in the forums, but this seems to occur most often when OpenBLAS is being firstly compiled, due to not being able to detect the architecture, and is most easily resolved by adding the TARGET= argument. This doesn't seem to work in the benchmark file, though. The result is below. Also, references to an odd library as well, near the bottom, libopenblas_unknownp-r0.2.19.dev.a.

linaro@linaro-alip:~/P3/opt_libs/OpenBLAS/benchmark$ make
getarch_2nd.c: In function ‘main’:
getarch_2nd.c:12:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:12:35: note: each undeclared identifier is reported only once for each function it appears in
getarch_2nd.c:13:35: error: ‘SGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("SGEMM_UNROLL_N=%d\n", SGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:14:35: error: ‘DGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_M=%d\n", DGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:15:35: error: ‘DGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("DGEMM_UNROLL_N=%d\n", DGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:19:35: error: ‘CGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_M=%d\n", CGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:20:35: error: ‘CGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("CGEMM_UNROLL_N=%d\n", CGEMM_DEFAULT_UNROLL_N);
                                   ^
getarch_2nd.c:21:35: error: ‘ZGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_M=%d\n", ZGEMM_DEFAULT_UNROLL_M);
                                   ^
getarch_2nd.c:22:35: error: ‘ZGEMM_DEFAULT_UNROLL_N’ undeclared (first use in this function)
     printf("ZGEMM_UNROLL_N=%d\n", ZGEMM_DEFAULT_UNROLL_N);
                                   ^
make: *** [getarch_2nd] Error 1
make: *** No rule to make target '../libopenblas_unknownp-r0.2.19.dev.a', needed by 'slinpack.goto'.  Stop.

**Comment by vtjnash** [comment]
Did you mean to submit this to the OpenBLAS issue tracker? JuliaLang doesn't typically offer support for benchmarks for BLAS.

**Comment by ViralBShah** [comment]
Let's reopen if this is julia specific. Appears to be an openblas issue.

**Comment by Knoxort** [comment]
Yeah, this is an OpenBLAS issue. Apologies.
