### ISSUE TITLE
RFC: Replace Nullable's isnull field by hasvalue

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#18507]
I'd like to suggest changing the `isnull::Bool` field of `Nullable` to a `hasvalue::Bool` field with the opposite meaning. Indeed, all languages and formats I could find use this convention. Following the most common convention is generally a good idea, and it's particularly useful when creating `NullableArrays` from binary formats like Feather.

Of course, this would be a breaking change, but it would only affect code which does not use the public `isnull()` method. Since that method is a simple accessor to the eponymous field, there's no reason to access the field directly. Potential breakage would easily be fixed before 0.6 is released by changing `x.isnull` to `isnull(x)`, which works since Julia 0.4.

Here's a short survey of what other software does in that regard:

* [In C#](https://msdn.microsoft.com/library/1t3y8s4s.aspx), the `Nullable` type has an `HasValue` field.

* [In Scala](https://twitter.github.io/scala_school/collections.html#Option), the `Option` type has an `isDefined` method.

* [In Go](https://golang.org/pkg/database/sql/#NullString), null types have a `Valid` field.

* [In SQLite](http://www.sqlite.org/fileformat2.html#record_format), a `NULL` is marked via serial type `0` (equivalent to `false` in most languages).

* [In PostgreSQL](https://www.postgresql.org/docs/9.5/static/storage-page-layout.html), [in Feather](https://github.com/wesm/feather/blob/master/doc/FORMAT.md#primitive-arrays) and [in Pandas 2](https://wesm.github.io/pandas2-design/internal-architecture.html#a-proposed-solution), the null bitmask uses a `0` bit (again equivalent to `false` in most languages) to denote a `null`.

CC: @johnmyleswhite @quinnj @davidagold

**Comment by bramtayl** [comment]
R has `is.na()`, but I find myself almost exclusively doing `!is.na(x)`

**Comment by nalimilan** [comment]
Note that I'm not talking about changing the `isnull()` function here, only the underlying implementation.

**Comment by bramtayl** [comment]
Oh. Well, maybe changing the function is something to consider as well?

**Comment by johnmyleswhite** [comment]
I'm on board with this because I think it will simplify using the internals for fast math: you can treat these as frequency-count weights and do things like `x.value * x.hasvalue` as long as you guarantee the absence of `NaN`.

**Comment by nalimilan** [comment]
> Oh. Well, maybe changing the function is something to consider as well?

I'd rather discuss this somewhere else. If you open an issue, please also make a survey of what other languages do (it seems to me `isnull()` is the most common pattern).
