### ISSUE TITLE
PriorityQueue - peek versus dequeue!

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#18517]
`peek` returns the pair `(key,value)` whereas `dequeue!` only returns the `key`:

``` julia
using Base.Collections
pq = PriorityQueue()
enqueue!(pq, key, value)
key, value = peek(pq)
key = dequeue!(pq)
```

Can `dequeue!` return the pair?

To be consistent with the rest of the interface, should we rename some of these to `push!` and `pop!`?

**Comment by juliohm** [comment]
Anyone is taking care of this issue?

**Comment by t-lanigan** [comment]
Hey @juliohm, I'd like to try and tackle this issue although I've never contributed to an open source project before and could use a little guidance on how to approach this. I'm a little unsure on how to even find the code that produces this error.

Thanks for any help!

**Comment by juliohm** [comment]
Hi @t-lanigan, thank you for your interest. You will have to explore the code yourself and see if you are able to fix it. Almost all of us contributing to FOSS projects started that way.

If you come up with concrete questions along the process, we will always be willing to help.

**Comment by Keno** [comment]
> I'm a little unsure on how to even find the code that produces this error.

This particular code is in `base/collections.jl`. Generally it's possible to find where code is either by searching for a particular term, or using the `@which` or `@edit` macros.

**Comment by t-lanigan** [comment]
Hey thanks for the quick responses guys. I'll dive into it! Newbie question #2: how do I learn how to use these macros?

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaCollections/DataStructures.jl/issues/289

**Comment by sbromberger** [comment]
Ref: https://github.com/JuliaCollections/DataStructures.jl/pull/301
