### ISSUE TITLE
OS X .app not building correctly

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#18518]
There is a bug in platypus 5.1 which means that julia isn't actually being included in the .app:
https://github.com/sveinbjornt/Platypus/issues/78

**Comment by ViralBShah** [comment]
Didn't we have a PR somewhere that removed the dependency on Platypus?

**Comment by simonbyrne** [comment]
Not that I know of. You might be thinking of #16698, but that didn't remove platypus.

That said, the OS X application bundle structure isn't terribly complicated, so we might be able to do without it.

**Comment by simonbyrne** [comment]
Though apparently I did hit the same issue before (I thought it was familiar): https://github.com/sveinbjornt/Platypus/issues/67

**Comment by ViralBShah** [comment]
We should probably figure out how to generate the bundle with XCode and remove this dependency.

**Comment by simonbyrne** [comment]
We might not even need XCode, as the structure is fairly simple:
https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19
