### ISSUE TITLE
`Ptr` objects are set to 0 when precompiling and cause problems

### ISSUE THREAD

**Issue by xqrongm** [JuliaLang/julia#18527]
Julia v0.4.6
MySQL.jl v0.0.2+ master (latest)

I have this code
```
__precompile__()
module TestMySQL

    using MySQL

    i1 = 1

    type TestType
        ptr_a::Ptr
        ptr_d::Ptr
    end

    a1 = ones(3,2)
    ptr_a1 = pointer_from_objref(a1)
    println("pointer of a1: ", ptr_a1)

    d1 = Dict('a'=>1,'b'=>2)
    ptr_d1 = pointer_from_objref(d1)
    println("pointer of d1: ", ptr_d1)

    tt1 = TestType(ptr_a1, ptr_d1)
    println("tt1: ", tt1)
    println("pointer of tt1: ", pointer_from_objref(tt1))

    db_conn = mysql_connect("localhost", "root1", "pswd1", "test_1ch")
    println("pointer of db_conn: ", pointer_from_objref(db_conn))
    dump(db_conn)

    ms_df1 = mysql_execute(db_conn, "select * from steps where id=2")

    function __init__()

        global i2 = i1 + 1

        println("a1: ", a1)
        println("pointer of a1: ", pointer_from_objref(a1))
        println("ptr_a1: ", ptr_a1)

        println("d1: ", d1)
        println("pointer of d1: ", pointer_from_objref(d1))
        println("ptr_d1: ", ptr_d1)

        println("tt1: ", tt1)
        println("pointer of tt1: ", pointer_from_objref(tt1))

        println("pointer of db_conn: ", pointer_from_objref(db_conn))
        dump(db_conn)

        global ms_df2 = mysql_execute(db_conn, "select * from steps where id=2")

    end

end # TestMySQL
```

When I comment out `__precompile`, everything works just fine. This is the REPL output.

> julia> using TestMySQL
> pointer of a1: Ptr{Void} @0x00000000844dddd0
> pointer of d1: Ptr{Void} @0x00000000834f1e60
> tt1: TestMySQL.TestType(Ptr{Void} @0x00000000844dddd0,Ptr{Void} @0x00000000834f1e60)
> pointer of tt1: Ptr{Void} @0x0000000083116f50
> pointer of db_conn: Ptr{Void} @0x0000000082edecb0
> MySQL.MySQLHandle
>   mysqlptr: Ptr{Void} Ptr{Void} @0x000000000ffb63e0
>   host: ASCIIString "localhost"
>   user: ASCIIString "root1"
>   db: ASCIIString "test_1ch"
>   stmtptr: Ptr{MySQL.MYSQL_STMT} Ptr{MySQL.MYSQL_STMT} @0x000000000ffe1090
> a1: [1.0 1.0
>  1.0 1.0
>  1.0 1.0]
> pointer of a1: Ptr{Void} @0x00000000844dddd0
> ptr_a1: Ptr{Void} @0x00000000844dddd0
> d1: Dict('b'=>2,'a'=>1)
> pointer of d1: Ptr{Void} @0x00000000834f1e60
> ptr_d1: Ptr{Void} @0x00000000834f1e60
> tt1: TestMySQL.TestType(Ptr{Void} @0x00000000844dddd0,Ptr{Void} @0x00000000834f1e60)
> pointer of tt1: Ptr{Void} @0x0000000083116f50
> pointer of db_conn: Ptr{Void} @0x0000000082edecb0
> MySQL.MySQLHandle
>   mysqlptr: Ptr{Void} Ptr{Void} @0x000000000ffb63e0
>   host: ASCIIString "localhost"
>   user: ASCIIString "root1"
>   db: ASCIIString "test_1ch"
>   stmtptr: Ptr{MySQL.MYSQL_STMT} Ptr{MySQL.MYSQL_STMT} @0x000000000ffe1090

When I do use `__precompile__`, an error was raised.

> julia> using TestMySQL
> INFO: Precompiling module TestMySQL...
> pointer of a1: Ptr{Void} @0x0000000082f44630
> pointer of d1: Ptr{Void} @0x00000000837389c0
> tt1: TestMySQL.TestType(Ptr{Void} @0x0000000082f44630,Ptr{Void} @0x00000000837389c0)
> pointer of tt1: Ptr{Void} @0x00000000838f62f0
> pointer of db_conn: Ptr{Void} @0x0000000083fb8040
> MySQL.MySQLHandle
>   mysqlptr: Ptr{Void} Ptr{Void} @0x0000000005b86520
>   host: ASCIIString "localhost"
>   user: ASCIIString "root1"
>   db: ASCIIString "test_1ch"
>   stmtptr: Ptr{MySQL.MYSQL_STMT} Ptr{MySQL.MYSQL_STMT} @0x0000000005b8ec60
> a1: [1.0 1.0
>  1.0 1.0
>  1.0 1.0]
> pointer of a1: Ptr{Void} @0x00000000846dc7f0
> ptr_a1: Ptr{Void} @0x0000000000000000
> d1: Dict('b'=>2,'a'=>1)
> pointer of d1: Ptr{Void} @0x000000008301f3f0
> ptr_d1: Ptr{Void} @0x0000000000000000
> tt1: TestMySQL.TestType(Ptr{Void} @0x0000000000000000,Ptr{Void} @0x0000000000000000)
> pointer of tt1: Ptr{Void} @0x000000008476e990
> pointer of db_conn: Ptr{Void} @0x0000000084715a80
> MySQL.MySQLHandle
>   mysqlptr: Ptr{Void} Ptr{Void} @0x0000000000000000
>   host: ASCIIString "localhost"
>   user: ASCIIString "root1"
>   db: ASCIIString "test_1ch"
>   stmtptr: Ptr{MySQL.MYSQL_STMT} Ptr{MySQL.MYSQL_STMT} @0x0000000000000000
> ERROR: InitError: Method called with null connection.
>  in mysql_execute at E:\for_programs\julia_pkgs\v0.4\MySQL\src\handy.jl:144
>  in __init__ at E:\freelance\applications\010_qpcr\Julia\TestMySQL.jl:50
>  in _require_from_serialized at loading.jl:84
>  in require at loading.jl:267
> during initialization of module TestMySQL

I noticed that all the pointers changed when precompiling. The pointers for Array and Dict objects changed to some non-0 values and those objects still maintain their values as expected. In contrast, the Ptr objects were all set to 0 and (my guess) no longer point to where they supposed to, which caused the error.

I'm wondering if there is anything you can do to make such codes that work without precompling also work when precompiling? Thanks.

**Comment by Keno** [comment]
Please see the manual chapter on precompilation: http://docs.julialang.org/en/release-0.5/manual/modules/#man-modules-initialization-precompilation. All pointers needs to be re-created in __init__, since memory layout does not remain the same across process restarts.
