### ISSUE TITLE
Allowing space between function and arguments [fn (...)]

### ISSUE THREAD

**Issue by fb87** [JuliaLang/julia#18542]
I think it's rediculous that I get a deprecation warning, every time I make a space in between. This is personal style and has absolutely nothing to do with functionality, so this shouldn't be "deprecated".

Arguments pro:
1.) More orientation by separation of functions and arguments.
2.) One can align the arguments of serverals functions for an easier overview (especially on first sight), and this gives more orientation by scrolling through a long code file, too.

Arguments contra:
- I cannot imagine a single reason. -

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/issues/7232 and https://github.com/JuliaLang/julia/pull/11891

**Comment by simonster** [comment]
Ironically, the best argument contra is `[fn (...)]`

**Comment by fb87** [comment]
Julia would know that fn is a function, so that it could sum up until the closing parenthesis...

**Comment by nalimilan** [comment]
> Julia would know that fn is a function, so that it could sum up until the closing parenthesis, this should be no issue at all. Every other language I know of can deal with this.

Knowing that `fn` is a function doesn't fix the problem. This is a perfectly valid operation:
```julia
julia> [sum (1, 2)]
1×2 Array{Any,2}:
 sum  (1,2)

```
