### ISSUE TITLE
Base.runtests() failed

### ISSUE THREAD

**Issue by scottsallberg** [JuliaLang/julia#18544]
I'm running Julia version 0.5.0-rc3+0 on a Mac with OS X El Capitan version 10.11.6 (15G1004)

I just issued the Base.runtests() command at the Julia prompt to see how well everything works in this release that I have been working with for a week or so.

Since this level of work is beyond me, maybe I just need to download the next release candidate rc4...

Here's a screen dump of the error messages:

ERROR: LoadError: KeyError: key "PATH" not found
 in access_env(::Base.##339#340, ::String) at ./env.jl:45
 in getindex(::Base.EnvHash, ::String) at ./env.jl:73
 in getindex(::Base.EnvHash, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in load_juliarc() at ./client.jl:274
 in process_options(::Base.JLOptions) at ./client.jl:216
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Applications/Julia-0.5.app/Contents/Resources/julia/etc/julia/juliarc.jl, in expression starting on line 9
       	From worker 5: 	     * cmdlineargs          Error During Test
       	From worker 5: 	  Test threw an exception of type ErrorException
       	From worker 5: 	  Expression: parse(Int,readchomp(setenv(@cmd("\$exename -E \"Base.JLOptions().startupfile\" --startup-file=yes"),["HOME=/tmp"]))) == JL_OPTIONS_STARTUPFILE_ON
       	From worker 5: 	  failed process: Process(setenv(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=error --precompiled=yes -E Base.JLOptions().startupfile --startup-file=yes`,String["HOME=/tmp"]), ProcessExited(1)) [1]
       	From worker 5: 	   in pipeline_error(::Base.Process) at ./process.jl:616
       	From worker 5: 	   in read(::Cmd, ::Base.DevNullStream) at ./process.jl:576
       	From worker 5: 	   in readstring at ./process.jl:581 [inlined] (repeats 2 times)
       	From worker 5: 	   in readchomp(::Cmd) at ./io.jl:338
       	From worker 5: 	   in readchomp(::Cmd) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
       	From worker 5: 	   in include_string(::String, ::String) at ./loading.jl:380
       	From worker 5: 	   in include_string(::String, ::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
       	From worker 5: 	   in include_from_node1(::String) at ./loading.jl:429
       	From worker 5: 	   in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
       	From worker 5: 	   in macro expansion at ./util.jl:226 [inlined]
       	From worker 5: 	   in runtests(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/testdefs.jl:7
       	From worker 5: 	   in (::Base.Serializer.__deserialized_types__.##16#24)(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/runtests.jl:44
       	From worker 5: 	   in (::Base.##625#627{Base.CallMsg{:call_fetch}})() at ./multi.jl:1421
       	From worker 5: 	   in run_work_thunk(::Base.##625#627{Base.CallMsg{:call_fetch}}, ::Bool) at ./multi.jl:1001
       	From worker 5: 	   in macro expansion at ./multi.jl:1421 [inlined]
       	From worker 5: 	   in (::Base.##624#626{Base.CallMsg{:call_fetch},Base.MsgHeader,TCPSocket})() at ./event.jl:68
Exception running test cmdlineargs :
On worker 5:
LoadError: There was an error during testing
 in record at ./test.jl:397
 in do_test at ./test.jl:281
 in include_string at ./loading.jl:380
 in jlcall_include_string_37237 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:429
 in jlcall_include_from_node1_20229 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion at ./util.jl:226 [inlined]
 in runtests at /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/testdefs.jl:7
 in #16 at /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/runtests.jl:44
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
while loading /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/cmdlineargs.jl, in expression starting on line 277
ERROR: LoadError: Some tests exited with errors.
 in (::##11#19)() at /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/runtests.jl:72
 in cd(::##11#19, ::String) at ./file.jl:59
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Applications/Julia-0.5.app/Contents/Resources/julia/share/julia/test/runtests.jl, in expression starting on line 26
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

 in runtests(::Array{String,1}, ::Int64) at ./interactiveutil.jl:567
 in runtests() at ./interactiveutil.jl:556

**Comment by tkelman** [comment]
Thanks for the report! Do you have a `juliarc.jl` file under `/tmp`? Looks like the test at https://github.com/JuliaLang/julia/blob/8cb72ee64f7c09eabce10ec09793c959ed115598/test/cmdlineargs.jl#L304-L305 is more fragile than it should be, and should instead be creating a new clean temporary directory just for that test and getting rid of it when done.

**Comment by scottsallberg** [comment]
nope, no  .juliarc.jl file under /tmp.  Should there be?

**Comment by tkelman** [comment]
nevermind, it's not coming from tmp, it's coming from the binary https://github.com/JuliaLang/julia/blob/master/contrib/mac/juliarc.jl

We should pass PATH in the env keyword on that test line.
