### ISSUE TITLE
Pkg can't spawn git on windows

### ISSUE THREAD

**Issue by ivfiev** [JuliaLang/julia#18550]
Getting
```
ERROR: could not spawn `git version`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```
when trying to run ```Pkg.init()```

```git version``` gives (git that julia comes with is in my PATH)
```
git version 2.6.1.windows.1
```

I'm on windows 10 with julia 0.4.6 (binary distr)

don't have this issue on 0.5.0-RC

**Comment by tkelman** [comment]
And ```run(`git version`)``` inside Julia gives what? How about ```run(`where git`)``` ?

**Comment by ivfiev** [comment]
```
julia> run(`git version`)
ERROR: could not spawn `git version`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262

julia> run(`where git`)
ERROR: could not spawn `where git`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
```

**Comment by tkelman** [comment]
`ENV["PATH"]` ?

**Comment by ivfiev** [comment]
ah, I was having a ```.juliarc.jl``` file overriding ```ENV["PATH"]```
removing the file sorted my issue
thanks!
