### ISSUE TITLE
Compile source on Debian Jessie

### ISSUE THREAD

**Issue by hcarlsso** [JuliaLang/julia#18562]
Hi, 

I am trying to compile julia release-0.5 on debian jessie, and get this error on make. I also tried `make -C deps clean-llvm`

```
CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:293 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:277 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:294 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:277 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:296 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:277 (FIND_PACKAGE)


CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:298 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:277 (FIND_PACKAGE)


-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- Configuring incomplete, errors occurred!
See also "/home/hakcar/opt/julia/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd/CMakeFiles/CMakeOutput.log".
See also "/home/hakcar/opt/julia/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd/CMakeFiles/CMakeError.log".
/home/hakcar/opt/julia/deps/libgit2.mk:58: recipe for target 'build/libgit2-211e117a0590583a720c53172406f34186c543bd/Makefile' failed
make[1]: *** [build/libgit2-211e117a0590583a720c53172406f34186c543bd/Makefile] Error 1
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

I found a similar problem [here](https://github.com/libgit2/rugged/issues/403), and it seemed it was an error with an old version of libssh2, but libssh2 is included in the deps of julia.

Also included are the files:
*  [CMakeError.txt](https://github.com/JuliaLang/julia/files/478159/CMakeError.txt)
* [CMakeOutput.txt](https://github.com/JuliaLang/julia/files/478160/CMakeOutput.txt)

**Comment by tkelman** [comment]
It's a bug with an old version of cmake, see https://github.com/JuliaLang/julia/issues/13871 and https://github.com/JuliaLang/julia/pull/18530. Report the bug and tell Debian to not use broken versions of things. And just download and use the latest version: https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz

**Comment by hcarlsso** [comment]
Seems like already [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826656), and solution is to use [jessie-proposed-updates](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826656#27)

**Comment by hcarlsso** [comment]
Updating cmake did fix the problem, building and testing passed through.
