### ISSUE TITLE
Memory regressions in daily benchmark

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#18569]
Putting it here so it doesn't get forgotten.

https://github.com/JuliaLang/julia/commit/3a31155#commitcomment-19063411

https://github.com/JuliaCI/BaseBenchmarkReports/blob/c446686d038e02992f7b0a60490e04577069720f/daily_2016_9_17/report.md

Noticed by @Sacha0

**Comment by TotalVerb** [comment]
The `["array","cat",("catnd",5)]` regression seems to have been introduced by #18467 and has been fixed by #18575.

Local benchmarking has indicated that all other regressions are likely caused by a different PR.

**Comment by KristofferC** [comment]
Anyone has an idea about this?

**Comment by tkelman** [comment]
Did we trigger nanosoldier on all the intermediate commits to see which one it was?

**Comment by KristofferC** [comment]
Commit range is https://github.com/JuliaLang/julia/compare/ec3d29e66716069b104226a170b13a759e7f5328...3a311556050ee70e71c43c3ca6bc86165174da77

**Comment by KristofferC** [comment]
@jrevels is there anyway to run nanosoldier on two arbitrary commits?

**Comment by nalimilan** [comment]
Looks like you should be able to do that by commenting on a specific commit, and giving the reference commit via `vs`. See https://github.com/JuliaCI/Nanosoldier.jl#comment-examples

**Comment by KristofferC** [comment]
Yeah, just thought if I could do it here for example.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/commit/f30c9499b62e4959d8265b1e22401702f073aa15#commitcomment-19082011 seems to suggest that up to that commit things are ok?

**Comment by KristofferC** [comment]
Leaves  f30c949...3a31155 I guess

**Comment by TotalVerb** [comment]
Has this been figured out yet?

**Comment by KristofferC** [comment]
I couoldnt reproduce this
