### ISSUE TITLE
[0.4.7] test/file.jl hangs in test_monitor_wait

### ISSUE THREAD

**Issue by petercolberg** [JuliaLang/julia#18579]
When building julia 0.4.7 in a Debian unstable chroot, `test/file.jl` hangs in line 146, which is called by `test_monitor_wait(0.1)` in line 167. On the other hand, when commenting lines 167 and 168,  the calls to `test_monitor_wait_poll()` pass. Any ideas how to debug this regression further?

**Comment by felipenoris** [comment]
Does it show a error message?

**Comment by petercolberg** [comment]
No, it just hangs indefinitely. However, I discovered that it is not triggered by a regression, but a change in the build environment. I recently switched my [Debian sbuild](https://wiki.debian.org/sbuild) chroot to use overlayfs in tmpfs. After reverting the chroot to use btrfs snapshots, ` test_monitor_wait` passes again.

**Comment by tkelman** [comment]
I've never seen this happen and I don't think anything backported between 0.4.6 and 0.4.7 would change this. Can you provide full reproduction steps?

**Comment by felipenoris** [comment]
I recently had file.jl test problems on ubuntu. But I got `FSMonitorError`.
I fixed it running this (see https://github.com/wimleers/fileconveyor/wiki/Troubleshooting):
```
# Check inotify user watches current maximum
$ cat /proc/sys/fs/inotify/max_user_watches
8192
# Increase the maximum
$ echo 100000|sudo tee /proc/sys/fs/inotify/max_user_watches
Password:
100000
# Check again 
$ cat /proc/sys/fs/inotify/max_user_watches
100000
```

**Comment by KristofferC** [comment]
Please comment if this still happens on newer Julia verisions.
