### ISSUE TITLE
addprocs(): sh: 1: export: /usr/bin/julia/bin/julia: bad variable name

### ISSUE THREAD

**Issue by laurentheirendt** [JuliaLang/julia#18587]
- Relevant versions: Julia 0.5.0-rc4 & v0.4.6 & 0.4.5 || Linux 14.04 LTS
- PATH is set to /usr/bin/julia/bin

Adding processes using:
```
addprocs([("<first.last>@server.com",:auto)], tunnel=true, topology=:master_slave, dir=`~/`, sshflags=`-p9000`);
```
results in:
```
sh: 1: export: /usr/bin/julia/bin/julia: bad variable name
```

Is there anything that I am missing out here? This used to work ... On all the machines is the same version of Julia, freshly cloned.

**Comment by laurentheirendt** [comment]
Testing reveals that the issue is related to the function
```
launch_on_machine(manager::SSHManager, machine, cnt, params, launched, launch_ntfy::Condition)
```
in base/managers.jl. The `cmd`string is not properly built and `$exename` is called as part of the `export` command in `$tval`.

Following suggestions:
1) remove the `;` after the ENV variable - gives an error when connecting
```
    tval = haskey(ENV, "JULIA_WORKER_TIMEOUT") ?
        `export JULIA_WORKER_TIMEOUT=$(ENV["JULIA_WORKER_TIMEOUT"])` : ``
``` 

2) Change the `cmd`string by adding `&&` between `$tval` and `$exename`:
```
    cmd = `cd $dir && $tval && $exename $exeflags`
```
Further testing is needed before submitting a PR.

**Comment by amitmurthy** [comment]
I cannot reproduce this locally on OSX.

> This used to work ...

Which is the last version of Julia that it worked for you? Or did something else change when it stopped working?

Can you print the output of `set | grep JULIA` from your shell or the value of `ENV["JULIA_WORKER_TIMEOUT"]` from the Julia REPL?

**Comment by laurentheirendt** [comment]
I am actually trying to reinstall the old versions to figure out since when, but I am sure it still worked with v3.12.

Here is the output of the environment variable:
```
julia> ENV["JULIA_WORKER_TIMEOUT"]
"1000"
```

**Comment by amitmurthy** [comment]
I just tested on an Ubuntu system locally and it worked fine. 

Could you add a `println(cmd)` after 

    cmd = `ssh -T -a -x -o ClearAllForwardings=yes -n $sshflags $host $(shell_escape(cmd))`

so that we can see how the `cmd` is being built in your environment?

**Comment by laurentheirendt** [comment]
I upgraded all the Julia versions on all the nodes and on the host to v0.5.0. Most importantly, I set the environment explicitly in .bashrc as
```
export JULIA_WORKER_TIMEOUT=1000;
```
... and it works now! It seems as if previously, the environment was set such that there was a whitespace after the number 1000:
```
julia> ENV["JULIA_WORKER_TIMEOUT"]
"1000 "
```
Thanks for your help.

**Comment by amitmurthy** [comment]
Thanks. I have opened an issue to handle the error better - #18602
