### ISSUE TITLE
The 0.4.7 OS X .app is "damaged or incomplete"

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#18592]
I downloaded the Julia 0.4.7 .app bundle for OS X from the julialang downloads page. When I opened the .dmg to drag the .app into Applications, I noticed that the icon looked peculiar:

![screen shot 2016-09-19 at 5 06 25 pm](https://cloud.githubusercontent.com/assets/6396159/18654414/ce9d0092-7e95-11e6-9863-88e70b8b6de5.png)

Double clicking on the icon gives the following message:

![screen shot 2016-09-19 at 5 16 28 pm](https://cloud.githubusercontent.com/assets/6396159/18654415/cea249da-7e95-11e6-8db9-32d6b06b86d8.png)

Running `/Applications/Julia-0.4.7.app/Contents/Resources/julia/bin/julia` from the terminal works fine, however.

Attempting to verify the app using `codesign` yields this:
```zsh
$ codesign --verify -vvvv /Applications/Julia-0.4.7.app
/Applications/Julia-0.4.7.app: valid on disk
/Applications/Julia-0.4.7.app: satisfies its Designated Requirement
```

Also,
```bash
$ cd /Applications/Julia-0.4.7.app/Contents/MacOS/
$ ls
Julia
$ ls -la Julia
lrwxr-xr-x  1 ararslan  admin  51 Sep 18 12:11 Julia -> ../../Cellar/platypus/4.9/share/platypus/ScriptExec
```

That path does not exist.

In case it matters, I'm on OS X 10.10.5 Yosemite. Let me know if there's any other information you need.

**Comment by ViralBShah** [comment]
Cc @slarew

**Comment by ViralBShah** [comment]
I get the same thing. It shows damaged in the disk image itself:
<img width="488" alt="screen shot 2016-09-20 at 8 33 23 am" src="https://cloud.githubusercontent.com/assets/744411/18656208/f0247d9a-7f0c-11e6-99fe-2f2b160d683d.png">

**Comment by slarew** [comment]
0.4.7 was built with Platypus then?

**Comment by slarew** [comment]
Ok I see #18522 is still open. I can look at the 0.4.7 binary in the morning. Although I have no experience with platypus

**Comment by staticfloat** [comment]
Don't worry @slarew, I'll take care of this tonight.  We aren't using your/simon's improvements yet. :)

**Comment by staticfloat** [comment]
Looks like the problem might have been that we _didn't_ merge #18522.  :P  A platypus update changed some configuration on us, so I manually rolled back to a previous version of platypus, and we're rebuilding binaries now.

**Comment by tkelman** [comment]
Try downloading again? Should be fixed now, thanks to @staticfloat for fixing platypus on the buildbots.

**Comment by ararslan** [comment]
Looks like that did it! Thanks so much, @staticfloat!

**Comment by ViralBShah** [comment]
Verified. Works. Thanks all.
