### ISSUE TITLE
Docstring for `float` disagrees with/is unclear about behavour

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#18596]
The docstring says:

>   **float(x)**
> 
>   Convert a number, array, or string to a AbstractFloat data type. For numeric data, the smallest suitable AbstractFloat  type is used. Converts strings to Float64.

To me this reads like the new type is the smallest subtype of `AbstractFloat` that can actually exactly represent it's input exactly.  Which would result in 
- `typeof(float(1)) == Float16`
- `typeof(float(1.0)) == Float16`
- `typeof(float(big"2"^53)) == Float64`
- `typeof(float(big"10"^53+1)) == BigFloat`

What it [actually does](https://github.com/JuliaLang/julia/blob/d7a703f521fff9f81d2a7aef007d582936169a90/base/float.jl#L152)
is far more useful for most uses.
Which is to produce a generally appropriate Floating point type.
- `Base.BitIntegers` --> `Float64`
- `BigInt` --> `BigFloat`
- `T<:AbstractFloat --> T`

And similar conversions for `Complex{T]` applied to `T`.

What would be a better way to word this?
Rather than **smallest suitable AbstractFloat  type**, would **most suitable AbstractFloat subtype**, or **corresponding AbstractFloat  subtype**
Be more clear?

**Comment by nalimilan** [comment]
For type stability, the return type cannot depend on the actual value, only on the type.

But indeed you're right that `float` doesn't return the smallest type which can hold any value of the input type. For example, `float(Int8(1))` doesn't return `Float16(1)`. So "most suitable" sounds like a better description (even if it's a bit vague).

**Comment by simonbyrne** [comment]
How can we explain it's behaviour for `Complex` as well?
