### ISSUE TITLE
addprocs() with SSHManager fails to load more than 1 process on remote node

### ISSUE THREAD

**Issue by laurentheirendt** [JuliaLang/julia#18600]
- Relevant versions: Julia 0.5.0-rc4 & v0.4.6 & 0.4.5 || Linux 14.04 LTS

Once the modifications are implemented as suggested in #18587 , the following command stalls:
```
cmd1 = addprocs([("<first.last>@server.com",2)], tunnel=true, sshflags=`-p9000`,topology=:master_slave, dir=`~/`, exename = "/usr/bin/julia/bin/julia", max_parallel=10);
``` 
whereas this works:
```
cmd2 = addprocs([("<first.last>@server.com",1)], tunnel=true, sshflags=`-p9000`,topology=:master_slave, dir=`~/`, exename = "/usr/bin/julia/bin/julia", max_parallel=10);
```
Moreover, `cmd2` launches **16** julia instances with `--worker` in parallel. I guess that this is abnormal behaviour.

Testing shows that `cmd1` stalls at line 1760 of Base/multi.jl 
```
new_addresses = remotecall_fetch(launch_additional, frompid, cnt, cmd)
```
in the function `launch_n_additional_processes(manager, frompid, fromconfig, cnt, launched_q)`.

@amitmurthy, do you know more about this?

**Comment by ViralBShah** [comment]
Cc @amitmurthy

**Comment by laurentheirendt** [comment]
Version issue. All nodes and host upgraded to v0.5.0.
