### ISSUE TITLE
Julia does not build with clang 3.9

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18619]
Attempting to build Julia with clang 3.9 leads to a syntax error while building OpenBLAS. The problem is analyzed [here](https://github.com/xianyi/OpenBLAS/issues/942), but without solution or work-around. Julia should either disallow this compiler, or patch OpenBLAS to avoid this problem.

**Comment by Keno** [comment]
I'll bug the appropriate clang people to look at the upstream issue.

**Comment by ViralBShah** [comment]
Cc @xianyi

**Comment by Keno** [comment]
Upstream revision to fix this in clang is https://reviews.llvm.org/D24839.

**Comment by maleadt** [comment]
As suggested in xianyi/OpenBLAS#942, maybe we should add `-no-integrated-as` to OpenBLAS' CFLAGS if `USECLANG=1`.
