### ISSUE TITLE
v0.5 Base.Test output isn't as nicely formatted as v0.4 BaseTestNext

### ISSUE THREAD

**Issue by mweastwood** [JuliaLang/julia#18611]
This issue is a bit of a nitpick, but I like to eat my cake too.

On v0.5 with Base.Test I get

```
julia> @testset "some tests" begin
           @test 1==2
           @test 2==2
           @testset "more tests" begin
               @test 3==4
               @test 4==4
           end
       end
...
Test Summary: | Pass  Fail  Total
  some tests  |    2     2      4
  more tests  |    1     1      2
```

With BaseTestNext on v0.4 I instead get

```
...
Test Summary: | Pass  Fail  Total
some tests    |    2     2      4
  more tests  |    1     1      2
```

which has some helpful indentation indicating that "more tests" is a subset of "some tests".

**Comment by StefanKarpinski** [comment]
Can probably just be cherry-picked from the package version.

**Comment by tkelman** [comment]
Did this regress at some point or was it always different?

**Comment by kshyatt** [comment]
@tkelman I think this is likely my fault, because of the way I handled the top level test sets.

**Comment by kshyatt** [comment]
Since I'm familiar with this code and the problem is likely my fault, I've self-assigned, but if someone else wants to take a crack at it it's probably a pretty easy fix.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/20232
