### ISSUE TITLE
v0.5 Pkg operations through proxy failed

### ISSUE THREAD

**Issue by yangguang760** [JuliaLang/julia#18613]
I updated julia to v0.5 from apt-get and then the Pkg related operations failed, which worked well on v0.46.
The machine is behind a http proxy and the details are as below.

julia> Pkg.update()
INFO: Updating METADATA...
ERROR: METADATA cannot be updated. Resolve problems manually in /home/yang/.julia/v0.5/METADATA.
GitError(Code:ERROR, Class:Net, Failed to resolve address for github.com: 域名解析暂时失败)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #fetch#52(::Base.LibGit2.FetchOptions, ::String, ::Function, ::Base.LibGit2.GitRemote, ::Array{AbstractString,1}) at ./libgit2/remote.jl:70
 in (::Base.LibGit2.#kw##fetch)(::Array{Any,1}, ::Base.LibGit2.#fetch, ::Base.LibGit2.GitRemote, ::Array{AbstractString,1}) at ./<missing>:0
 in #fetch#93(::String, ::String, ::Array{AbstractString,1}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:164
 in (::Base.Pkg.Entry.##35#41)(::Base.LibGit2.GitRepo) at ./pkg/entry.jl:371
 in with(::Base.Pkg.Entry.##35#41, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in update(::String, ::Set{String}) at ./pkg/entry.jl:354
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in update() at ./pkg/pkg.jl:210
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
 in (::Base.Pkg.Entry.##35#41)(::Base.LibGit2.GitRepo) at ./pkg/entry.jl:378
 in with(::Base.Pkg.Entry.##35#41, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:638
 in update(::String, ::Set{String}) at ./pkg/entry.jl:354
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in update() at ./pkg/pkg.jl:210

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

yang@yang-VirtualBox:~$ git clone  https://github.com/Keno/ASTInterpreter.jl.git
正克隆到 'ASTInterpreter.jl'...
remote: Counting objects: 563, done.
remote: Total 563 (delta 0), reused 0 (delta 0), pack-reused 563
接收对象中: 100% (563/563), 208.87 KiB | 115.00 KiB/s, 完成.
处理 delta 中: 100% (274/274), 完成.
检查连接... 完成。

yang@yang-VirtualBox:~$ export | grep proxy
declare -x http_proxy="http://192.168.x.x:xxxx/"
declare -x https_proxy="https://192.168.x.x:xxxx/"

yang@yang-VirtualBox:~$ cat .gitconfig 
[user]
	name = xxxxxxxx
	email = xxxxxxxxx@xxxxxxxxx
[core]
	filemode = false
[gui]
	encoding = gbk
[http]
	proxy = 192.168.x.x:xxxx
[https]
	proxy = 192.168.x.x:xxxx
[url "https://"]
	insteadOf = git://
[url "https://github.com/"]
    insteadOf = git://github.com/

I really appreciate it if anyone could help : )

**Comment by tkelman** [comment]
> from apt-get

Try the generic linux binaries instead. If those work, then open an issue at https://github.com/staticfloat/julia-debian to update the libgit2 build in the PPA to include curl support.

**Comment by yangguang760** [comment]
The generic linux binaries worked.
Thx @tkelman

**Comment by ViralBShah** [comment]
IIRC, the curl dependency for proxy is 7.46 or something like that.
