### ISSUE TITLE
Pkg install - option to bypass SSL certification verification

### ISSUE THREAD

**Issue by gaborbernat** [JuliaLang/julia#18625]
Sitting behind a corporate proxy I'm unable to connect to https pages with SSL certification verification. Is it possible to disable it?

Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/

Thanks,

**Comment by tkelman** [comment]
Exactly what command did you run to get this error? That looks like it came from Python. https://github.com/python/cpython/blob/aba769999c9acecf617bccf1ca2599e7f172d249/Modules/_ssl.c#L590

**Comment by dpopadic** [comment]
The following resolved this issue:
1. create/edit the following file in your Julia-directory: `~/.atom/.apmrc`
2. add the following line in the `.arpmc` file: strict-ssl = false
