### ISSUE TITLE
∥ (\parallel) can not be used as character of a variable name

### ISSUE THREAD

**Issue by shorty66** [JuliaLang/julia#18624]
The unicode symbol ∥ typed \parallel  can not be used in variable names.

``` Julia
u∥ = 1
```

returns

```
LoadError: syntax: unexpected "="
while loading In[1], in expression starting on line 1
```

This is in contrast to ⟂ (\perp) which works as expected.

**Comment by martinholters** [comment]
```Julia
julia> dump(:(a∥b))
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol ∥
    2: Symbol a
    3: Symbol b
  typ: Any

julia> dump(:(a⟂b))
Symbol a⟂b
```

So `∥` is parsed as a binary operator, while `⟂` isn't. A bit inconsistent, but `∥` being a binary operator does sound reasonable to me.

**Comment by stevengj** [comment]
Hmm, they should probably be both operators or both identifier characters.   I would lean towards the latter.

**Comment by TotalVerb** [comment]
∥ is in Unicode block Mathematical Operators. ⟂ is in Miscellaneous Mathematical Symbols-A. That's probably why ∥ was added as an operator but ⟂ excluded.

**Comment by JeffBezanson** [comment]
Both are now operators.
