### ISSUE TITLE
documentation improvement C interface

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#18627]
within the [tutorial about julias C interface](http://docs.julialang.org/en/release-0.5/manual/calling-c-and-fortran-code/#creating-c-compatible-julia-function-pointers) there is the following unexpected example:

```
function mycompare{T}(a::T, b::T)
    return convert(Cint, a < b ? -1 : a > b ? +1 : 0)::Cint
end
```

From what is written in the [docs about types](http://docs.julialang.org/en/release-0.5/manual/types/#type-declarations) this should be equal to

```
function mycompare{T}(a::T, b::T)::Cint
    return a < b ? -1 : a > b ? +1 : 0
end
```

and as far as I tested it is indeed.

---

The sentence written above this code block would have to be changed as well

```
Notice that we have to be careful about the return type: qsort expects a function returning a C int,
so we must be sure to return Cint via a call to convert and a typeassert.
```

might become

```
Notice that we have to ensure the correct return type: qsort expects a function returning a C int.
```

---

Might be worth a change in documentation. Thanks a lot.

**Comment by kshyatt** [comment]
Hello @schlichtanders, thanks for putting the work in on this. Would you be willing to open a PR to make these changes?

**Comment by tkelman** [comment]
Agreed that sounds like a good change, that documentation section probably hasn't been updated since the return type declaration syntax was added (in https://github.com/JuliaLang/julia/issues/16432).
