### ISSUE TITLE
Cant find module in CWD if module name is different from the filename

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/julia#18630]
using julia 0.5rc4
LOAD_PATH contains current directory.
I have a filename AAA.jl defining en empty module BBB.jl

```
> #AAA.jl
> module BBB
> end
```

in a new shell

```
julia> using BBB
ERROR: ArgumentError: Module BBB not found in current path.
Run `Pkg.add("BBB")` to install the BBB package.
 in require(::Symbol) at .\loading.jl:365
```

Another peculiarity, if I try an import using the filename , then the second time it works:

```
julia> using BBB
ERROR: ArgumentError: Module BBB not found in current path.
Run `Pkg.add("BBB")` to install the BBB package.
 in require(::Symbol) at .\loading.jl:365

julia> using AAA
WARNING: requiring "AAA" in module "Main" did not define a corresponding module.

julia> AAA
ERROR: UndefVarError: AAA not defined

julia> using BBB

julia>
```

**Comment by stevengj** [comment]
This is how `using BBB` works: if `BBB` was not already imported, then it looks for a file `BBB.jl` or `BBB/BBB.jl` in the path.  How would you expect it to find `BBB` in a file `AAA.jl` automatically?

If you want to load `BBB` from the file `AAA.jl`, the right thing is:
```jl
include("AAA.jl") # execute everything in AAA.jl, which imports the BBB module
using BBB # import the exported symbols from the BBB module
```

**Comment by stevengj** [comment]
`using AAA` imports the file `AAA.jl`, which defines the `BBB` module, but then fails because no `AAA` module was defined.

**Comment by TsurHerman** [comment]
O.k thanks , it was not crystal clear from the documents.
So now I understand it as follows:
 
include("A.jl") -> effectively imports all modules defined in file A.jl + evaluates in Current scope any unscoped code in the file

import A -> imports module A from file A.jl on the searchpath

using A -> evaluates contents of module A in file A.jl in the current scope
 
So it seems to me that using and import are kind of a macro shortcut.
In my opinion it should be more verbose than that.
I suggest the following syntax :
import/importall/using **from** file
@import A = import A from A
@using A = using A from A


I did a quick test: 

```
#/file AAA.jl
module BBB
  f(x) = x;
end
module AAA
end
```
in the shell 

```
julia> import AAA

julia> BBB.f(1)
1

julia>
```

that seems wrong and convoluted ,  I did not ask for BBB why is it here? because it is in the same file?

**Comment by yuyichao** [comment]
You get `BBB` to because you are in `Main`. https://github.com/JuliaLang/julia/issues/17997

**Comment by TsurHerman** [comment]
I suggest the following for better readability on the expense of maybe less usability :

include("A.jl") -> evaluate contents  A.jl in the current scope
using A from B -> evaluates contents of module A from file B.jl in the current scope
import A from B -> evaluate contents of module A from file B.jl in current scope.A and export exported symbols to current scope

**Comment by stevengj** [comment]
@TsurHerman, that would be quite a large departure from how Julia works.   `using A` or `import A` currently includes and evaluates the whole `A.jl` file, not just the definition of `module A` (if any) in that file.  There is no notion of evaluating the contents of one module extracted out of one file, and in fact trying to implement that would break the `__precompile__(true)` function.

(Furthermore, your proposal swaps the meaning of `import` and `using`.  In Julia `using A` is what exports symbols to the current scope.)

**Comment by TsurHerman** [comment]
Thanks for clearing it out .. it should be stated somewhere very clearly that import and using first perform include modulename.jl.

 There should be a way to work more naturally when developing.

I am currently using 'import' only on my code since I reload it often using a convenient macro @!
However I would like to be able to use 'using' without needing to kill and restart the session every code change  I make.

So there must be a way to tag each symbol with the module it came from, and to further more automatically monitor the file system for changes and to reload modules and invalidate affected symbols.

This behavior can be only in interactive mode as probably it has some effect on performance. 
This way the barrier for new users of the language will be greatly lowered , and you will have much less
repetitive explanations to make to people like me :-) .

So far my initial experience with julia is excellent.

**Comment by stevengj** [comment]
@TsurHerman, see https://github.com/malmaud/Autoreload.jl

**Comment by TsurHerman** [comment]
I fumbled with that .. and didn't see any benefit over reloading my modules the normal way.
I think the syntax of that package was old and so it threw an error at me... as an exercise I tried to fix that package. 

I really like Julia but the infrastructure is lacking and some of the available packages are still immature and not properly maintained.

A maintained small and simple package is much better than an obscure generic code wizardry.

**Comment by yuyichao** [comment]
AFAICT there's nothing that needs to be done here. (Top level) Modules that are loaded automatically are always required to have the same module name and file (base)name. The confusion of getting a different module in `Main` is #17997. The syntax for relative loading/evaluation in a sub module is basically https://github.com/JuliaLang/julia/issues/4600
