### ISSUE TITLE
parser does not catch typo

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#18636]
Demo:

``` julia
if true
    print(true)
else/
    print(false)
end
```

This prints `true` and the parser does not see the extra `\`, whereas it should raise some syntax error.

This is on 0.5 but same happens in 0.4.

**Comment by yuyichao** [comment]
This is a valid syntax.

**Comment by gasagna** [comment]
I guess that it is equivalent to 
```julia
if true
    print(true)
else
    /
    print(false)
end
```
but it does not feel so right.

However, 
```julia
if true /
    print(true)
else
    print(false)
end
```
is not equivalent to 
````julia
if true
    /
    print(true)
else
    print(false)
end
````
but produces
````julia
julia> if true /
           print(true)
       else
           print(false)
       end
trueERROR: MethodError: `/` has no method matching /(::Void, ::Bool)
Closest candidates are:
  /(::Integer, ::Integer)
  /(::Complex{T<:Real}, ::Real)
  /{T<:Number}(::T<:Number, ::T<:Number)
  ...
 in \ at operators.jl:110
````

**Comment by yuyichao** [comment]
It's because binary operators are treated as operators when there's an value before it.

**Comment by stevengj** [comment]
Seems like we should require a space between keywords and operators.  e.g. `if!true` should be invalid.

**Comment by nbaum** [comment]
Perhaps this is best left to a linting tool that warns you that the value of `/` goes unused?

**Comment by yuyichao** [comment]
Linting tool should definitely warn about variables in void position if it is not already.

**Comment by brenhinkeller** [comment]
Looks like this likely to remain valid syntax in the language itself, but would be a great thing for linters to catch and warn about (if they don't already!)
