### ISSUE TITLE
Unable to install Julia from .dmg on Mac OS X Yosemite (10.10.5)

### ISSUE THREAD

**Issue by hedgy123** [JuliaLang/julia#18631]
Hi,

   I downloaded the mac installer for Julia and tried to run it on my Mac 10.10.5.  I got the following errors:

exec '/Volumes/Julia-0.5.0/Julia-0.5.app/Contents/Resources/julia/bin/julia'
WARNING: Error during initialization of module GMP:
ErrorException("PCRE JIT error: bad JIT option")
WARNING: Error during initialization of module LinAlg:
ErrorException("could not load library "libopenblas64_"
dlopen(libopenblas64_.dylib, 1): image not found")
fatal: error thrown and no exception handler available.
Base.InitError(mod=:Pkg, error=ErrorException("PCRE JIT error: bad JIT option"))
rec_backtrace at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/stackwalk.c:84
record_backtrace at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:232 [inlined]
jl_throw at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:550
jit_compile at ./pcre.jl:107
compile at ./regex.jl:56
ismatch at ./regex.jl:145 [inlined]
ismatch at ./regex.jl:145 [inlined]
isabspath at ./path.jl:46 [inlined]
joinpath at ./path.jl:79
_pkgroot at ./pkg/dir.jl:10
__init__ at ./pkg/pkg.jl:74
jlcall___init___24781 at /Volumes/Julia-0.5.0/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1392 [inlined]
jl_module_run_initializer at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:83
_julia_init at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/init.c:742
julia_init at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:283
main at /Volumes/Julia-0.5.0/Julia-0.5.app/Contents/Resources/julia/bin/julia (unknown line)

**Comment by ViralBShah** [comment]
Do you have something on your LD_LIBRARY_PATH?

**Comment by simonbyrne** [comment]
You appear to be running it from the .dmg volume. Can you try copying it to Applications, and running it from there?

**Comment by KristofferC** [comment]
Please comment if this is still a problem.
