### ISSUE TITLE
GitError after Cloning METADATA calls from Pkg. functions in Julia 0.5 on Windows behind Proxy

### ISSUE THREAD

**Issue by kawild** [JuliaLang/julia#18643]
I have seen some related issues but none with GitError(Code:ERROR, Class:Net, Cross host redirect not allowed).

```
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, Cross host redirect not allowed)
 in macro expansion at .\libgit2\error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at .\libgit2\reposito
ry.jl:191
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCr
edentials}, ::Function, ::String, ::String) at .\libgit2\libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String,
 ::String) at .\<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at .\pkg\dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at .\file.jl:48
 in init(::String, ::String) at .\pkg\dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at
.\pkg\dir.jl:28
 in update() at .\pkg\pkg.jl:210
```

**Comment by tkelman** [comment]
I'm not sure where that "Cross host redirect not allowed" message comes from, but you might need to set some environment variables to make proxies work in libgit2 with winhttp.

**Comment by aviks** [comment]
Are you hitting some kind of transparent proxy? Could you possibly sniff the packets using fiddler or wireshark? 

For the record, the error comes from libgit2 here: https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/src/netops.c#L190

**Comment by musm** [comment]
I'm hitting this too

**Comment by tkelman** [comment]
@musm that looks like a separate issue, probably unrelated to the OP here

**Comment by musm** [comment]
Apologies, should I file a separate issue? I know I could delete v0.5 folder but that seems excessive and other may also have the same issue

**Comment by tkelman** [comment]
check the git status in metadata and should probably be a separate issue unless you find another one where the only error message is similar to your
```
ERROR: METADATA cannot be updated. Resolve problems manually in C:\Users\Mus\.julia\v0.5\METADATA.
GitError(Code:ERROR, Class:Net, Unsupported URL protocol)
```

**Comment by kawild** [comment]
Seems that libgit2 is looking for lowercase versions of the environment variables for proxy-settings ("http_proxy" ...)
It also looks for .gitconfig in the Windows userpath.

It might be useful to add a troubleshooting section to the documentation which sums up such issues.

**Comment by KristofferC** [comment]
Please reopen at https://github.com/JuliaLang/Pkg.jl if this happens again.
