### ISSUE TITLE
Documentation: "Noteworthy Differences from other Languages" -- outdated information + minor mistakes

### ISSUE THREAD

**Issue by zuo** [JuliaLang/julia#18656]
This issue concerns [the v0.5 docs](https://github.com/JuliaLang/julia/blob/v0.5.0/doc/manual/noteworthy-differences.rst) as well as [the latest (master branch) docs](https://github.com/JuliaLang/julia/blob/master/doc/manual/noteworthy-differences.rst).
- The _Noteworthy differences from MATLAB_ section:
  - The paragraph starting with _In Julia v0.3, concatenating scalars and arrays with the syntax [x,y,z]_ -- It contains information only about v0.3 and v0.4 (probably not needed anymore) -- and nothing about v0.5.
- The _Noteworthy differences from R_ section:
  - The paragraph starting with _Julia's :func:`apply` takes the function first_ -- Is there a stdlib function called _apply()_ anymore? Maybe _mapslices()_ should be mentioned instead?
  - The paragraph: _Julia's -> creates an anonymous function, like Python._ -- It is not true; `->` in Python does not create an anonymous function (the _lambda_ keyword does; in Python 3.x, `->` exists but does something completely different: introduces the _result annotation_ of a named function).
  - The paragraph: _Julia has several functions that can mutate their arguments. For example, it has both :func:`sort` and :func:`sort!`._ -- This wording may be misleading (can be understood that _sort_ is a mutating function).

The _Noteworthy differences from Python_ section:
- The paragraph starting with: _In Julia, a vector of vectors can automatically concatenate into a one-dimensional vector if no explicit element type is specified._ -- Contains outdated information about automatic concatenation.
- The paragraph: _Julia's list comprehensions do not support the optional if clause that Python has._ -- It is no longer true.
- The paragraph starting with: _Julia's updating operators_ -- Ends with: the _InplaceOps.jl_ reference which may be unclear for newcomers (to whom the document is dedicated, at least to a great extent) -- especially without any hyperlink.

The _Noteworthy differences from C/C++_ section:
- The paragraph starting with: _In Julia, whitespace is significant_ -- May be a bit criptic or too laconic for Julia newcomers ("In what sense, exactly, whitespace is significant in Julia? As in Python? As in old Fortran dialects?").
- The paragraph starting with: _Julia does not require the use of semicolons to end statements._ -- Some its fragments seem to be irrelevant to C/C++ (especially the fragment starting with: _The results of expressions are not automatically printed (except at the interactive prompt, i.e. the REPL)_... -- probably copied from some MATLAB-related description...).

**Comment by ararslan** [comment]
Perhaps "Julia's `->` creates an anonymous function, like Python" should be changed to "Julia's `->` creates an anonymous function, like **Ruby**." (In Ruby, stabby lambdas are `->x{...}`)

**Comment by nalimilan** [comment]
@zuo Thanks for catching this. Would you make a pull request to fix these issues?

**Comment by sg1101** [comment]
I would like to work on this issue, please guide me how to proceed. Thank You.

**Comment by felixrehren** [comment]
@sg1101 Make a fork of JuliaLang/julia, create a branch in your fork, edit the documentation as outlined above, and create a pull request back to the main project. (Cf. [Contributing.md](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md).) If you need help with any of these steps, just open a thread on [discourse](discourse.julialang.org).

**Comment by laborg** [comment]
The Noteworthy Differences page has changed a lot since this issue has been reported and from my point of view only the last two points need to be tackled.

>    The Noteworthy differences from MATLAB section:
>        The paragraph starting with In Julia v0.3, concatenating scalars and arrays with the syntax [x,y,z] -- It contains information only about v0.3 and v0.4 (probably not needed anymore) -- and nothing about v0.5.

no Julia versions mentioned anymore (probably because Julia 1.0 was released in the meantime)

>    The Noteworthy differences from R section:
>     The paragraph starting with Julia's :func:apply takes the function first -- Is there a stdlib function called apply() anymore? Maybe mapslices() should be mentioned instead?

`map` is now mentioned

>    The paragraph: Julia's -> creates an anonymous function, like Python. -- It is not true; -> in Python does not create an anonymous function (the lambda keyword does; in Python 3.x, -> exists but does something completely different: introduces the result annotation of a named function).

"like Python"  has been removed

>    The paragraph: Julia has several functions that can mutate their arguments. For example, it has both :func:sort and :func:sort!. -- This wording may be misleading (can be understood that sort is a mutating function).

If people read this sentence the wrong way  - `sort` and `sort!` are both mutating - the reader will also be curious on how they differ and will click on their links which will make it clear what the difference is.

>The Noteworthy differences from Python section:

>   The paragraph starting with: In Julia, a vector of vectors can automatically concatenate into a one-dimensional vector if no explicit element type is specified. -- Contains outdated information about automatic concatenation.

Not included anymore.

>    The paragraph: Julia's list comprehensions do not support the optional if clause that Python has. -- It is no longer true.

Not included anymore.

>    The paragraph starting with: Julia's updating operators -- Ends with: the InplaceOps.jl reference which may be unclear for newcomers (to whom the document is dedicated, at least to a great extent) -- especially without any hyperlink.

The first google result of InplaceOps.jl is the corresponding package.

>The Noteworthy differences from C/C++ section:

>    The paragraph starting with: In Julia, whitespace is significant -- May be a bit criptic or too laconic for Julia newcomers ("In what sense, exactly, whitespace is significant in Julia? As in Python? As in old Fortran dialects?").

Agree, this sentence would be better with an example.

>    The paragraph starting with: Julia does not require the use of semicolons to end statements. -- Some its fragments seem to be irrelevant to C/C++ (especially the fragment starting with: The results of expressions are not automatically printed (except at the interactive prompt, i.e. the REPL)... -- probably copied from some MATLAB-related description...).

Agree, this should be updated.

**Comment by ViralBShah** [comment]
Closing this for now. Please submit PRs for things that are still relevant.
