### ISSUE TITLE
@fastmath does not apply muladd

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#18654]
The original goal for `@fastmath` (#9406) was to add all compiler optimizations to increase the speed of mathematical operations. It makes sense then for it to apply muladd, an operation which is for improving speed #9840. It was assumed that this was happening, but [from this julia-users thread](https://groups.google.com/forum/#!topic/julia-users/m29qLarlzXM) we see that `@fastmath` currently does not apply any fma/muladd instructions. 

The summary of the previous discussion is that this should be enabled by compiler flag, though the correct flag for doing so seems to be a more subtle question.

@eschnett @tkelman @yuyichao

**Comment by yuyichao** [comment]
Unless there's a magic option to specify the needed property on part of the function already, this will need upstream support. (AFAICT it currently requires marking the whole function with the fast math attribute which we can't do)
