### ISSUE TITLE
searchsortedfirst odd with reversed ranges

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#18653]
Something fishy here

```
julia> searchsortedfirst(10:-1:1.0, 9.4)
3

julia> searchsortedfirst(10:-1:1, 9.4)
1
```

correct is 2

```
julia> findfirst(10:-1:1.0.<=9.4)
2

julia> searchsortedfirst(collect(10:-1:1), 9.4, rev=true)
2
```

Sprinkling some `rev=true`:

```
julia> searchsortedfirst(10:-1:1.0, 9.4, rev=true)
2

julia> searchsortedfirst(10:-1:1, 9.4, rev=true)
1
```

**Comment by yuyichao** [comment]
At least the function is free to return anything for the first two versions. The third and the forth looks fine, not sure about the last two.

**Comment by mauro3** [comment]
Maybe the "free to return anything" should be documented better, at least to me that is not clear:
```
  searchsortedfirst(a, x, [by=<transform>,] [lt=<comparison>,] [rev=false])

  Returns the index of the first value in a greater than or equal to x, 
  according to the specified order. Returns length(a)+1 if x is greater than
  all values in a.
```

**Comment by yuyichao** [comment]
The

> , assuming that a is already sorted in that order.

should be copied from the doc of `searchsorted`. even though the name should be suggestive enough....

**Comment by yuyichao** [comment]
Other than the documentation issue, the specialization `searchsortedlast{T<:Integer}(a::Range{T}, x::Real, o::DirectOrdering)` is probably a little off.

**Comment by StefanKarpinski** [comment]
The alternative to blindly assuming that the input is in sorted order is to check that it is, which would turn an O(log(n)) operation into an O(n) one, which I don't think we want.

**Comment by mauro3** [comment]
@StefanKarpinski: no, that would be no good. 

Apart from the last case, it's a documentation issue.  I think it should be made clearer that the sorting needs to be according to `lt` and that output is undefined if it is not.  Probably best would be to unify the description of the `lt`, `by`, `rev` in one of the `sort` functions and reference that from all the others.  I can try to have a go at this next week.

**Comment by mbauman** [comment]
I just ran into this myself.  Part of the confusion for me was that it actually does the right thing some of the time.  The other part was that "of course ranges are sorted" — without thinking through the fact that `searchsorted` requires them to be increasing (or explicitly given an ordering).

**Comment by nalimilan** [comment]
This would probably be clearer if the `searchsorted*` functions were replaced with a `SortedArray` wrapper combined with standard `search` functions. Then the sorting order (increasing vs. decreasing) would be determined when creating the `SortedArray`.

**Comment by mbauman** [comment]
Why not just automatically detect the sorted order if none is given? It's a simple test to check `v[1] < v[end]`.

**Comment by StefanKarpinski** [comment]
That handles exactly two search orders, which is sufficient for ranges but doesn't address arrays.

**Comment by oscardssmith** [comment]
We won't change behavior now.
