### ISSUE TITLE
true and false can be assigned-to, breaking the REPL

### ISSUE THREAD

**Issue by nbaum** [JuliaLang/julia#18667]
```julia
julia> true = 3
3

julia> true
true

julia> true == 3
false

julia> #=PRESS TAB KEY=# WARNING: Caught an exception in the keymap:
ERROR: MethodError: no method matching isdeprecated(::Module, ::Bool)
Closest candidates are:
  isdeprecated(::Module, ::Symbol) at reflection.jl:83
```

I can't guess why the REPL breaks, but since `true`'s value is always `true`, allowing the assignment at all is probably wrong.

Is there a reason `true` and `false` aren't consts imported from `Core`, like `nothing`?

**Comment by yuyichao** [comment]
> Is there a reason `true` and `false` aren't consts imported from `Core`, like `nothing`?

So that they can't be assigned to. Looks like the lowering doesn't handle this well though.

**Comment by JeffBezanson** [comment]
Looks like this was only guarded against with an assertion.
