### ISSUE TITLE
problem when building julia 0.5 with devtoolset

### ISSUE THREAD

**Issue by floswald** [JuliaLang/julia#18666]
hi,

i am trying to build the julia release on a remote unix system and get until this step:

```
[uctpfos@jake julia]$ make
LINK usr/bin/julia
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/libstdc++_nonshared.a(system_error.o): undefined reference to symbol '_ZTVSt14error_category@@GLIBCXX_3.4.11'
/usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

[uctpfos@jake julia]$ echo $LD_LIBRARY_PATH
/usr/lib64/libstdc++.so.6:/opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1
```

I read here (http://stackoverflow.com/questions/24989432/linking-error-dso-missing-from-command-line) that i should explicitly link to the missing library. how do i do this with the julia makefile? what else needs to be on my LD_LBIRARY_PATH?

thanks

**Comment by nalimilan** [comment]
What's that "remote Unix system"? RHEL?

**Comment by floswald** [comment]
sorry, that is Centos 5.5

**Comment by nalimilan** [comment]
Maybe you shouldn't use the libstdc++ from `/usr/lib64`, but rather that from the devtoolset? I.e., remove it from the path or move it at the end?

**Comment by floswald** [comment]
I added the system lib after several attempts. in a new session my error looks like this

```
[uctpfos@jake julia]$ scl enable devtoolset-3 bash
[uctpfos@jake julia]$ make
    LINK usr/bin/julia
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/libstdc++_nonshared.a(system_error.o): undefined reference to symbol '_ZTVSt14error_category@@GLIBCXX_3.4.11'
/usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [/share/apps/econ/acapp/git/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2
[uctpfos@jake julia]$ echo $LD_LIBRARY_PATH
/opt/gridengine/lib/linux-x64:/opt/rh/devtoolset-3/root/usr/lib64:/opt/rh/devtoolset-3/root/usr/lib:/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib:/share/apps/econ/tcl/8.6.4/lib/:/share/apps/econ/tcl/8.6.4/lib/
```

**Comment by nalimilan** [comment]
Looks like it's still using `/usr/lib64/libstdc++.so.6`. Maybe you haven't installed the corresponding devtoolset package? You could also remove that package/file to ensure it's not used.

**Comment by floswald** [comment]
i don't have root privilege so can't install anyting devtoolset related I think. also, from looking at it, it seems the required libraries are all there:

```bash
[uctpfos@jake julia]$ ls /opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.1/
32           crtend.o       crtprec64.o  libcaf_single.a    libgcc_eh.a    libgfortranbegin.a       libgomp.a     libquadmath.a      libstdc++_nonshared.a
crtbegin.o   crtendS.o      crtprec80.o  libcilkrts.spec    libgcc_s.so    libgfortran_nonshared.a  libgomp.so    libquadmath.so     libstdc++.so
crtbeginS.o  crtfastmath.o  finclude     libcloog-isl.so.4  libgcov.a      libgfortran.so           libgomp.spec  libsanitizer.spec  libsupc++.a
crtbeginT.o  crtprec32.o    include      libgcc.a           libgfortran.a  libgfortran.spec         libitm.spec   libstdc++.a        rpmver
```
I was looking for some guidance re the `error adding symbols: DSO missing from command line` part? thanks

**Comment by nalimilan** [comment]
No idea, but I would try to fix the first error first. The second one might be a consequence of it. Also, the fact that it's not using the devtoolset library is a problem.

**Comment by tkelman** [comment]
when you double post something on both the mailing list and an issue, please cross link between the two

**Comment by tkelman** [comment]
the devtoolset is set up in a strange way where it tries to put all the newer libstdc++ stuff in a static library. I don't know if that'll work for Julia, we haven't been using the devtoolset to build binaries for several years becasue of the strange handling of libstdc++ and libgfortran.

**Comment by floswald** [comment]
Ok that is important to know (maybe even so many important as to mention on
the readme).

What is your advice? Install gcc 6 in my local user space and use that
instead?

Thanks and sorry for the double posting.

**Comment by tkelman** [comment]
if you can't come up with any better ideas. @staticfloat do you remember if we had to set anything funny to make devtoolset happy back when we used it?

**Comment by nalimilan** [comment]
At least I used it to build RPMs on RHEL6 (and maybe also 5) without special hacks. But maybe that's changed since then.

**Comment by floswald** [comment]
i installed with my own install of gcc on that machine.
