### ISSUE TITLE
Bug with methods of an inner function in different scopes

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#18674]
On 0.5/master, there seem to be conflicting assumptions somewhere regarding scope when different methods of inner functions have different scopes.

```julia
function outer()
    inner(x) = x
    let y = 1
        inner() = y
        inner
    end
end

julia> outer()
ERROR: UndefVarError: y not defined
 in outer() at ./REPL[1]:2
```

This doesn't seem to make much sense, since `inner` isn't even called. In fact, I get the error even if I wrap the `let` block in `if false ... end`.

On 0.4:

```julia
julia> outer()
inner (generic function with 2 methods)
```

and `inner` works as expected.

For fun, this works:

```julia
function outer()
    inner(x) = x
    let y = 1
        (::typeof(inner))() = y
        inner
    end
end
```

but it prints a warning about a rewritten method definition every time `outer` is called.

It may be that this code pattern is actually impossible to handle since  #13412, but if that's the case, we could be more explicit about that.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15602
