### ISSUE TITLE
Master process could not connect within 60.0 seconds

### ISSUE THREAD

**Issue by crunch3** [JuliaLang/julia#18684]
After a HARD machine crash and a very long recovery and Windows-10 64-bit update, Julia shell now reports "Master process (id 1) could not connect within 60.0 seconds.\nexiting."

**Comment by StefanKarpinski** [comment]
As the tag says, this needs more info to be actionable.

**Comment by yuyichao** [comment]
I should add that when I applied the tag I've thought for a while and had no idea what info I should ask for. It looks possible that you've just somehow broken something badly and the julia worker process just crashed for whatever reason......

**Comment by crunch3** [comment]
What info would help?

**Comment by amitmurthy** [comment]
What is the command you ran? Does it happen every time? What is the output of `versioninfo()`?

**Comment by crunch3** [comment]
that's in startup.  the only thing in there is a Pkg,update()

**Comment by amitmurthy** [comment]
You mean your startup script has a `Pkg.update()` ?

Appears to be the same issue as https://github.com/JuliaLang/julia/issues/17726

**Comment by crunch3** [comment]
yes, I have Pkg.update() in my startup

**Comment by amitmurthy** [comment]
Closing this as a dup of #17726 . I'll submit a fix as per https://github.com/JuliaLang/julia/issues/17726#issuecomment-236500858

**Comment by crunch3** [comment]
very good, thanks
