### ISSUE TITLE
rename IntSet to IndexSet

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18683]
Since `IntSet` cannot, in fact represent sets of `Ints` – only `Ints` that are valid index values. While we're at it, might as well remove support for putting zero in an `IndexSet`, which has already been deprecated.

**Comment by JeffBezanson** [comment]
It seems a bit unusual to refer to a natural number as an "index". `NatSet` might be an accurate name, albeit not very aesthetically appealing. Maybe `BitSet`?

**Comment by vtjnash** [comment]
I think LLVM would have called this a `DenseBitSet`, so just throwing that out there.

**Comment by StefanKarpinski** [comment]
These are values that we can use as valid indices in Julia, so that seems like a sensible name to me. Another option would be to bit rotate the sign to the lowest bit and allow negative values. But that makes the structure twice as big for the most common use cases.

**Comment by mbauman** [comment]
With offset and multidimensional arrays this becomes much more interesting and much more powerful.  We should be using an `IndexSet` for logical indexing.  In fact, I think it should allow wrapping of arbitrary `AbstractArray{Bool}` source data… and it should be parameterized by the dimensionality of the source data:

```jl
type IndexSet{N,A}
    data::A # <:AbstractArray{Bool, N}
    inverse::Bool
end
IndexSet{A<:AbstractArray{Bool}}(mask::A) = IndexSet{ndims(A), A}(mask, false)
```

And then the type it holds is dependent upon the number of dimensions:

```jl
eltype(s::IndexSet{1}) = Int
eltype{N}(s::IndexSet{N}) = CartesianIndex{N}
```

I think this could be a huge win for logical indexing: not only does it avoid a allocating the result from `find`, but it also will dramatically speed up `A[A .> 123]` when `A` is LinearSlow.  Go one step farther, and enable support for `OffsetArrays`, then the supported region of the set is the indices of the `data` array.  It's a little tricky to keep growable support for `IndexSet{1}`, but I think it could be manageable.

**Comment by JeffBezanson** [comment]
That makes me even less inclined to call this IndexSet, since the job of this type is just to hold a simple set of natural numbers, not indicate regions of arrays. We might want to reserve that name for something more array-index-oriented.

**Comment by StefanKarpinski** [comment]
Call it `UIntSet` and undeprecate zero as a value?

**Comment by JeffBezanson** [comment]
That sounds ok to me.

**Comment by StefanKarpinski** [comment]
The only usability / breakage issue with that is that values yielded from it would be of type `UInt` :-|

**Comment by JeffBezanson** [comment]
True... `BitSet`? But I don't see a really big problem here; I think we can keep it the way it is.

**Comment by StefanKarpinski** [comment]
Ok, let's not do this then.
