### ISSUE TITLE
Profile.print(cols=500) error

### ISSUE THREAD

**Issue by LeoK987** [JuliaLang/julia#18685]
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

julia> Profile.print(cols=500)
ERROR: MethodError: no method matching print(::Base.TTY, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}; cols=500)
you may have intended to import Base.print
Closest candidates are:
  print{T<:Unsigned}(::IO, ::Array{T<:Unsigned,1}, ::Dict{K,V}; format, C, combine, sortedby, maxdepth) at profile.jl:88 got unsupported keyword argument "cols"
  print{T<:Unsigned}(::IO, ::Array{T<:Unsigned,1}) at profile.jl:88 got unsupported keyword argument "cols"
  print(::IO) at profile.jl:88 got unsupported keyword argument "cols"
 in (::Base.Profile.#kw##print)(::Array{Any,1}, ::Base.Profile.#print, ::Base.TTY, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}) at ./<missing>:0
 in #print#3(::Array{Any,1}, ::Function, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}) at ./profile.jl:107
 in (::Base.Profile.#kw##print)(::Array{Any,1}, ::Base.Profile.#print, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}) at ./<missing>:0 (repeats 2 times)

**Comment by vtjnash** [comment]
where are you seeing `cols` in the docs? (It should specified by `io = IOContext(io, displaysize = (row, cols))` now)

```
help?> Profile.print
  print([io::IO = STDOUT,] [data::Vector]; kwargs...)

  Prints profiling results to io (by default, STDOUT). If you do not supply a data vector, the internal buffer of accumulated backtraces will be used.

  The keyword arguments can be any combination of:

    •    format can be :tree (default) or :flat.
      
    •    If C is true, backtraces from C and Fortran code are shown (normally they are excluded).
      
    •    If combine is true (default), instruction pointers are merged that correspond to the same line of code.
      
    •    maxdepth can be used to limit the depth of printing in :tree format, while sortedby can be used to control the order in :flat format :filefuncline (default)
        sorts by the source line, whereas :count sorts in order of number of collected samples.
      
    •    noisefloor only shows frames that exceed the heuristic noise floor of the sample (only applies to format :tree). A suggested value to try for this is 2.0
        (the default is 0). This parameters hides samples for which n <= noisefloor * √N, where n is the number of samples on this line, and N is the number of
        samples for the callee.
      
    •    mincount can also be used to limit the printout to only those lines with at least mincount occurrences.
      

  print([io::IO = STDOUT,] data::Vector, lidict::LineInfoDict; kwargs...)

  Prints profiling results to io. This variant is used to examine results exported by a previous call to retrieve. Supply the vector data of backtraces and a dictionary
  lidict of line information.

  See Profile.print([io], data) for an explanation of the valid keyword arguments.
```

**Comment by LeoK987** [comment]
in the 0.5.1 documentation.

“s = open("/tmp/prof.txt","w")
Profile.print(s,cols = 500)
close(s)”

Excerpt From: unknown. “Julia Language 0.5.1-pre documentation.” iBooks.

**Comment by KristofferC** [comment]
The manual (not docstring) for `Profile.print` is completely out of date. I'll try get to it sometime soon unless someone beat me to it

**Comment by KristofferC** [comment]
Docs have been updated

**Comment by tkelman** [comment]
by what pr?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/20661
