### ISSUE TITLE
hankelh1(n,0.0)

### ISSUE THREAD

**Issue by jecs** [JuliaLang/julia#18698]
According to the resolution of Issue #6564,
`hankelh1(1, 0.0::Real)`
should return something along the lines `0.0-1im*Inf`.

Instead, an AmosException is thrown:

```
julia> hankelh1(1,0.0) 
ERROR: Base.Math.AmosException(1)
 in _besselh at ./special/bessel.jl:128
 in besselh at ./special/bessel.jl:195
```

Is this the intended behavior of the function?

Thank you for your time.

(I'm using julia-0.4.)

**Comment by stevengj** [comment]
It should certainly throw an exception for `hankelh1(1, 0+0im)`, since the phase of the infinity depends on from what direction you approach `0` in the complex plane.   For real arguments, I guess it makes sense for `hankelh1(1, x)` to return `Complex(0, copysign(Inf, -x))`.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaMath/SpecialFunctions.jl/issues/29
