### ISSUE TITLE
Dict construction gives unhelpful error message on failure

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#18708]
e.g., in a session where `y` is undefined:

``` julia
julia> Dict(x => y for x in 1:10)
ERROR: ArgumentError: Dict(kv): kv needs to be an iterator of tuples or pairs
 in Dict{K,V}(::Base.Generator{UnitRange{Int64},##1#2}) at ./dict.jl:502
```

It seems like [this line](https://github.com/JuliaLang/julia/blob/06c0ba6233258dbfd9cbb301e3fa115ee1b8de49/base/dict.jl#L500) of the Dict constructor is checking for `next(::typeof(kv))` and `done(::typeof(kv))`. These methods don't exist for any iterator since the state argument is missing. The easy fix is to check for the right methods, but I wonder whether there isn't a better way to detect this failure case.

**Comment by tkelman** [comment]
This was fixed by something prior to #20189, what was it? If the fix can be found and isolated on its own and it doesn't rely on things like the type system rewrite then maybe it could be backported, but need to identify the actual commit / PR first.

**Comment by simonster** [comment]
https://github.com/JuliaLang/julia/commit/e3bec2a34d724843040e8101d22c5bfacf891968?

**Comment by simonster** [comment]
(It does not look like the fix actually relies on the type system rewrite, even though it is lumped in with a bunch of other changes that do.)
