### ISSUE TITLE
Allow newline in filtering comprehension

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#18707]
This is not currently allowed:

```julia
julia> [x for x = 1:10
       if true]
ERROR: syntax: expected "]"
```

Perhaps the comprehensions I write are too long, but can this restriction be relaxed? I can't come up with a case where this is ambiguous off the top of my head, and we do allow things like:

```julia
[x
for x = 1:10]
```

**Comment by StefanKarpinski** [comment]
:+1: I wanted to write the comprehension in http://julialang.org/blog/2016/10/julia-0.5-highlights as:

```jl
[(q,d,n,p) for q = 0:25:100
           for d = 0:10:100-q
           for n = 0:5:100-q-d
           for p = 100-q-d-n
           if p < n < d < q]
```
