### ISSUE TITLE
`reinterpret` does not recognize tuples as bitstypes

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18716]
This is Julia 0.5.

I want to reinterpret a tuple as another non-tuple type. This doesn't work:
```
julia> reinterpret(Int, (0,))
ERROR: reinterpret: expected bitstype value for second argument
 in reinterpret(::Type{Int64}, ::Tuple{Int64}) at ./essentials.jl:86
julia> isbits((0,))
true
```

**Comment by vtjnash** [comment]
It's `isbits`, it's not a bitstype. 

dup https://github.com/JuliaLang/julia/issues/10140

**Comment by vchuravy** [comment]
#18470 woudld allow this for tuples of `VecElement`
