### ISSUE TITLE
Build failed for julia-0.5. !

### ISSUE THREAD

**Issue by mouryarahul** [JuliaLang/julia#18718]
A week ago, successfully built julia-0.5 using Intel compiler (ICC 16.0.0) and MKL library.  Today, even with GCC-5.4 (Ubuntu 16.04), the build failed: 

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
  CMakeLists.txt:277 (FIND_PACKAGE)

[CMakeError.log.txt](https://github.com/JuliaLang/julia/files/499268/CMakeError.log.txt)

-- Configuring incomplete, errors occurred!
See also "/home/rahul/Downloads/julia/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd/CMakeFiles/CMakeOutput.log".
See also "/home/rahul/Downloads/julia/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd/CMakeFiles/CMakeError.log".
/home/rahul/Downloads/julia/deps/libgit2.mk:58: recipe for target 'build/libgit2-211e117a0590583a720c53172406f34186c543bd/Makefile' failed
make[1]: *** [build/libgit2-211e117a0590583a720c53172406f34186c543bd/Makefile] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

CMakeError.log file is attached.

**Comment by tkelman** [comment]
Do you have `libssl-dev` installed?

**Comment by mouryarahul** [comment]
Thanks @tkelman ! 
libssl-dev was missing from the machine! Build successful !
However, I didn't find that libssl-dev is mentioned in the list of Required External Libraries, or may be it's obvious!

**Comment by tkelman** [comment]
It was until a few days ago on master. It's still there on the release-0.5 readme.
