### ISSUE TITLE
eval/parse should respect the semicolon

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/julia#18717]
eval(parse(string_expression)) still outputs printed information even when string_expression contains 
a semicolon at the end

```
julia> eval(parse("A=rand(3,3);"))
3×3 Array{Float64,2}:
 0.531437  0.431793   0.109629
 0.623559  0.0290678  0.502003
 0.387679  0.280958   0.314009

julia>
```

this is happening because the 3x3 random array is an output of the eval function 
and there is no semicolon at the end of that statement.

however I would argue that forwarding the print suppression qualifier to the parent eval(the REPL console)
is the right thing to do.

**Comment by KristofferC** [comment]
The fact that trailing semicolon silences output is purely a REPL specific implementation.

**Comment by ararslan** [comment]
I think doing that would require a (potentially nontrivial) change in how things are parsed. Note:
```julia
julia> parse("x = 1")
:($(Expr(:toplevel, :(x = 1))))

julia> parse("x = 1;")
:($(Expr(:toplevel, :(x = 1))))

julia> parse("x = 1; y = 2;")
:($(Expr(:toplevel, :(x = 1), :(y = 2))))
```
The semicolon is stripped from the parsed expression, even when its use is syntactically significant, i.e. not just suppressing REPL printing, as in the case of `x = 1; y = 2`.

**Comment by yuyichao** [comment]
Note that this has nothing to do with parsing and `eval`. In additional to what @KristofferC said, `eval` never prints out the result and always only returns it. It is because you didn't put a semicolon in the repl input that the result is shown.
