### ISSUE TITLE
Linux ppa does not ship with build_sysimg.jl

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18723]
Following the steps here `http://julialang.org/downloads/platform.html` under Ubuntu

Trying
` julia> include(joinpath(dirname(JULIA_HOME),"share","julia","build_sysimg.jl"))`

Gives `ERROR: could not open file /usr/share/julia/build_sysimg.jl`

Checking the directory you find that  `build_sysimg.jl` is not included.

**Comment by yuyichao** [comment]
Don't use the PPA.

**Comment by musm** [comment]
Then why even include those instructions, if you don't suggest them?

**Comment by tkelman** [comment]
We should probably delete mentions of the PPA and distro packages if they're going to have this many packaging-specific issues. Reopen this at https://github.com/staticfloat/julia-debian.

**Comment by ViralBShah** [comment]
The PPA is good for basic use and convenient.

**Comment by ViralBShah** [comment]
But leads to many issues.

**Comment by tkelman** [comment]
It's ubuntu-specific and requires root to install. If anyone would like to assist `@staticfloat` in maintaining the PPA, please reach out to him.
