### ISSUE TITLE
Test printing refinement

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#18739]
followup to #17165 / #18738, cc @kshyatt

right now the base tests are printing both old as-you-go info, in addition to a new table so it looks like

```
     * dsp                   maxrss 3501.18 MB
     * examples              maxrss 3501.18 MB
     * compile               maxrss 3501.18 MB

Test Summary: |     Pass  Broken     Total
  Overall     | 22171317      28  22171345
Test:                 | Total time (s): | GC time (s): | Percent in gc: | Allocated (MB): | RSS (MB):
linalg/triangular     |  546.77         |   11.92      |    2.18        | 8420.77         |  680.38
linalg/qr             |   89.66         |    1.85      |    2.06        | 2312.61         |  751.55
```

I propose we get rid of the old style and attempt to make the table just print new rows as they come in, if that's possible. The maxrss numbers are the same so it's duplicated information.

Additional printing-related followup from https://github.com/JuliaLang/julia/pull/17165#issuecomment-250615742, printing of `@test true` or `@test 1==1` should be adjusted to not bother showing `Expression: nothing` now that passing tests don't save the input expressions any more.

**Comment by tkelman** [comment]
The table's also overly wide for default console widths so we should try to squeeze it down, maybe make the header wrapped to 2 rows with each title narrower, or drop the percent column?

https://github.com/JuliaLang/julia/pull/17165#discussion_r81069168 `name_align` is too short if you only run short-named tests like `env` or `int` or `pkg`.

**Comment by kshyatt** [comment]
It should be possible to print row-by-row as each `@testset` returns.

The widest columns are `Allocated`, `Percent in gc`, and the test names (depending on what they are). One obvious fix is `Percent -> %`. `Allocated -> Alloc.`?

**Comment by tkelman** [comment]
Yeah good abbreviations. Which worker the tests ran on when they execute in parallel is useful info to show, we may want to make room for it in the table.

**Comment by kshyatt** [comment]
`test_name (worker)` ?

**Comment by tkelman** [comment]
This remains incomplete. @kshyatt any intention of revisiting this? Cases like https://travis-ci.org/JuliaLang/julia/jobs/173755550 give no indication of what line number within the spawn test actually failed.

**Comment by kshyatt** [comment]
@tkelman sorry I have been totally *swamped* with work. I will see if I can take a look today or tomorrow.
