### ISSUE TITLE
Cannot use local types in anonymous functions

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18730]
I see this error in Julia 0..5.1-pre+2:

```
julia> function f()
           I = Int
           x::I -> 1
       end
ERROR: ArgumentError: invalid type for argument x in method definition for #1 at REPL[1]:3
```

Using `Int` instead of `I` in the lambda expression works fine.

**Comment by vtjnash** [comment]
I think we can fix the error message here

**Comment by eschnett** [comment]
I thought that the underlying problem could be fixed -- `I` should be captured in the lambda.

**Comment by yuyichao** [comment]
> `I` should be captured in the lambda.

`I` is not a captured variable. The meaning of `x::I -> 1` has changed from 0.4. The `::I` is the method signature on 0.5, not a type assertion.

**Comment by yuyichao** [comment]
To get the same behavior as 0.4 use `x -> (x = x::I; 1)` which still means type assertion and should work.

```jl
julia> function f()
           I = Int
           x -> (x = x::I; 1)
       end
f (generic function with 1 method)

julia> g = f()
(::#3) (generic function with 1 method)

julia> g(1)
1

julia> g(1.0)
ERROR: TypeError: typeassert: expected Int64, got Float64
 in (::##3#4{DataType})(::Float64) at ./REPL[1]:3
```

**Comment by eschnett** [comment]
`x::I` being a method signature is fine. But instead of being called an `invalid type`, it should take `I`'s definition from the enclosing scope. This works if the anonymous function is declared in the global scope.

**Comment by yuyichao** [comment]
> But instead of being called an invalid type, it should take I's definition from the enclosing scope

That means a new method every time.

> This works if the anonymous function is declared in the global scope.

That's not a closure.
