### ISSUE TITLE
Testing DataStructures fails on Beaglebone

### ISSUE THREAD

**Issue by smartphoneworld** [JuliaLang/julia#18741]
I am receiving the following error calling Pkg.test("DataStructures") on Julia release-0.5 on Beagelbone (armv7-a/coretex-a8):
Expression: u == sum(pn .^ 2)
Evaluated: 5.049890144e9 == 754922848

**Full test output:**
INFO: Computing test dependencies for DataStructures...
INFO: Installing BaseTestNext v0.2.2
INFO: Installing Primes v0.1.1
INFO: Testing DataStructures
/sdcard/upgrade/.julia/v0.5/DataStructures/test/test_int_set.jl ...
/sdcard/upgrade/.julia/v0.5/DataStructures/test/test_deque.jl ...
/sdcard/upgrade/.julia/v0.5/DataStructures/test/test_circ_deque.jl ...
Test Summary: | Pass  Total
  CircularDeque |   58     58
/sdcard/upgrade/.julia/v0.5/DataStructures/test/test_sorted_containers.jl ...
Test Failed
  Expression: u == sum(pn .^ 2)
   Evaluated: 5.049890144e9 == 754922848
ERROR: LoadError: LoadError: There was an error during testing
while loading /sdcard/upgrade/.julia/v0.5/DataStructures/test/test_sorted_containers.jl, in expression starting on line 1699
while loading /sdcard/upgrade/.julia/v0.5/DataStructures/test/runtests.jl, in expression starting on line 34
===========================[ ERROR: DataStructures ]============================

failed process: Process(`/sdcard/upgrade/julia-compile/julia/usr/bin/julia -Ccortex-a8 -J/sdcard/upgrade/julia-compile/julia/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /sdcard/upgrade/.julia/v0.5/DataStructures/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing BaseTestNext v0.2.2
INFO: Removing Primes v0.1.1
ERROR: DataStructures had test errors

![screenshot 2016-09-30 07 39 39](https://cloud.githubusercontent.com/assets/730655/18981710/1ecbf570-86e1-11e6-95d4-18965cf91707.png)

**Comment by simonbyrne** [comment]
This is an issue with the package tests, see https://github.com/JuliaLang/DataStructures.jl/issues/218
