### ISSUE TITLE
Error message for `/` is reversed

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#18742]
Consider:

```
A = rand(3,2)
B = rand(4,5)
```

`A\B` correctly gives:

> LoadError: DimensionMismatch("left hand side has 3 rows, but right hand side has 4 rows")
> while loading ..., in expression starting on line ...

But: `A/B` gives:

> LoadError: DimensionMismatch("left hand side has 5 rows, but right hand side has 2 rows")
> while loading ... in expression starting on line ...

Which is incorrect. 

The correct error message would be:

> LoadError: DimensionMismatch("left hand side has 2 columns, but right hand side has 5 columns")
> while loading ..., in expression starting on line ...

That is because it is dispatching to `\`, 
and not catching, then rethrowing the error after reversing

---

​I suggest that `DimentionMismatch` should be parameter-ised to have a `lhs::Int` and `rhs::Int` field, and a `indexname::Union{String,Int}`, and a suitable `display` method; or something kind of like that.

---

(editted: previous version had my corrected output in the quote for what was supposed to be the current (incorrect) output, and visa-versa)

**Comment by gauravsc** [comment]
if I am not mistaken then it seems the error message is correct. When you are doing A/B, you are essential solving the linear equation XB = A, and in this case B and A must have the same number of columns and X and A should have the same rows. Therefore, the error is correct in reporting the mismatch in number of columns in B and A.

**Comment by oxinabox** [comment]
@gauravsc Oops. Looks like I mistakenly pasted my corrected version, in the place of actual (incorrect) version, and visa versa.
I've editted the post.
So now it reflects the true behavour (I hope)
Thanks for catching that

**Comment by andreasnoack** [comment]
The error message is thrown from `\` and not `/` so it's not wrong although it might be confusing. The simplest solution is probably to add a check in the `/` method.
