### ISSUE TITLE
Strange Segmentation Fault error

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#18749]
the following code crashes and produces a segmentation fault on 0.5; it works ok on 0.4; i am not sure is it a Gadfy or Julia problem.

```
import Gadfly
b = rand(10,10)
for i in 1:1
#gs = Gadfly.spy(b)
gs = Gadfly.spy(b, Gadfly.Guide.title("w"),
    Gadfly.Guide.YLabel("Species"), Gadfly.Guide.XLabel("Sources"), Gadfly.Guide.colorkey(""),
    Gadfly.Theme(default_point_size=20Gadfly.pt, major_label_font_size=14Gadfly.pt, minor_label_font_size=12Gadfly.pt, key_title_font_size=16Gadfly.pt, key_label_font_size=12Gadfly.pt),
    Gadfly.Scale.ContinuousColorScale(Gadfly.Scale.lab_gradient(parse(Colors.Colorant, "green"), parse(Colors.Colorant, "yellow"), parse(Colors.Colorant, "red")), minvalue = 0, maxvalue = 1)
    )
end
```

if you remove the `for` loop, it works ok (very, very strange).

if you comment out `Gadfly.Scale.ContinuousColorScale(Gadfly.Scale.lab_gradient(parse(Colors.Colorant, "green"), parse(Colors.Colorant, "yellow"), parse(Colors.Colorant, "red")), minvalue = 0, maxvalue = 1)` also works.

something is very strange; i also reported under Gadlfy but I am not sure is this purely Gadfly problem.

https://github.com/dcjones/Gadfly.jl/issues/904#issuecomment-250174745

**Comment by yuyichao** [comment]
could you check with nightly or with package compile off using `julia --compilecache=no`? There has been a few precompile fixes and I'm not sure if all of them have been backported yet.

**Comment by montyvesselinov** [comment]
`julia --compilecache=no` resolves the problem. is this going to be fixed in the next release?

**Comment by tkelman** [comment]
Depends what the fix was. Could use a bisect if anyone has a source build and can reproduce, to pinpoint to a specific commit.

**Comment by montyvesselinov** [comment]
Is this going to be fixes soon?

**Comment by tkelman** [comment]
Do you have a source build of Julia? I can explain how to do a bisect and find out what the fix was, but have too many other things happening right now to run it myself.

**Comment by montyvesselinov** [comment]
No problem as long is going to be fixed in the julia next release.

I can run `julia --compilecache=no` for some of the scripts as a short term solution.

**Comment by tkelman** [comment]
If it's working on master then it should be fixed in 0.6. Whether or not it will be fixed in 0.5.1 depends on whether the fix is marked for backporting.

**Comment by montyvesselinov** [comment]
FYI: I tried to test on the latest nightly build but Gadfly fails to be installed.

**Comment by KristofferC** [comment]
Please comment if this happens again.

**Comment by montyvesselinov** [comment]
No bug in Julia 0.5.2
