### ISSUE TITLE
Refactoring base's runtests harness for packages to use too

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#18740]
Ref https://github.com/JuliaLang/julia/pull/17165#issuecomment-241830583, we should try to refactor what's currently in `test/runtests.jl` to instead be a default part of the `Base.Test` module so packages can also use it for pretty-printing, parallel execution, running of selective subsets of tests (related to https://github.com/JuliaLang/julia/issues/15404), and everything else that base's tests do but packages have to roll their own.

**Comment by kshyatt** [comment]
OK, so you ought to be able to give `runtests` function two args: a test dir (which may be base Julia `test/` or `joinpath(Pkg.dir(), test)`) and a list of test files to run - and if we have that, I think it should work? We might want to include sharding (like we have now for base, where all linalg tests run first)? Anything else?
