### ISSUE TITLE
Update the shootout benchmarks - now called benchmarks game

### ISSUE THREAD

**Issue by igouy** [JuliaLang/julia#18759]
"The source code for all the benchmarks are available there:
 http://alioth.debian.org/scm/viewvc.php/shootout/bench/?root=shootout"

ARCHIVE only since Dec 29 2012

The active repository is --

https://alioth.debian.org/scm/viewvc.php/benchmarksgame/bench/?root=benchmarksgame

**Comment by ViralBShah** [comment]
Commit 0723ac874c723c1d324d43440c3b91981fd3f142 updates some of the names and URLs. Probably a more detailed review is necessary across the codebase to refresh URLs and benchmarks as necessary.

Perhaps we can even submit it then.

**Comment by KristofferC** [comment]
Link and name seems like they got updated.
