### ISSUE TITLE
Cannot define type with name 'Type'

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#18756]
In wrapping LLVM (which provides provides classes named `Function`, `Module` and `Type`) I've been trying to create a non-exported type named `Type` in my package's namespace, for users to refer to by `LLVM.Type`. This fails (partially?):

```julia
julia> module Bar
       type Type
       end
       end
ERROR: too many parameters for type Type
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68

julia> Bar.Type
Bar.Type

julia> @which Type
Core
```

But does work for other types exported by Core, like `Module` or `Function`:

```julia
julia> module Foo
       type Module
       end
       end
Foo

julia> Foo.Module
Foo.Module

julia> @which Module
Core
```

What's so special about `Type`? I can just go ahead and call my type `LLVMType`, but using the module namespace for this seemed like a nicer approach.

**Comment by vtjnash** [comment]
It's probably an issue with the '*.scm' files for lowering Julia code. You could try searching for Type and replacing with (core Type)

**Comment by maleadt** [comment]
Good call, that's exactly it. I'll create a proper PR later today or tomorrow.

**Comment by mauro3** [comment]
`Tuple` suffers too
```
julia> module B
       type Tuple
       end
       end
WARNING: imported binding for Tuple overwritten in module B
ERROR: too many parameters for type Tuple
```

**Comment by maleadt** [comment]
Also seems to work after #18757.

**Comment by maleadt** [comment]
There's definitely others though:
```
julia> module Foo
       type Any
       end
       end
WARNING: imported binding for Any overwritten in module Foo
ERROR: invalid subtyping in definition of Any
```

For a list of identifiers which are sometimes used in a `(core ...)` but sometimes not:
```bash
for symbol in `egrep -oh '\(core \w+\)' *.scm | sort | uniq | cut -d ' ' -f 2 | cut -d ')' -f 1`; do
  echo "$symbol:"
  grep -P "(?<\!core )$symbol\b" *.scm
done
```
