### ISSUE TITLE
function definitions inside try / catch block behave differently in 0.5 - intended?

### ISSUE THREAD

**Issue by tauu** [JuliaLang/julia#18767]
The following code behaves differently in julia v0.4 and julia v0.5
```julia
try
  function test(x)
    return x+1;
  end
end
```

In Julia v0.4 it returns
```
  test (generic function with 1 method)
```
whereas in Julia v0.5 I get
```
  (::test) (generic function with 1 method)
```

So in Julia v0.5 the method is not defined in global scope. This is even the case if a function in global scope exists. For Example:
```julia
import Base.show
type myType
  text::AbstractString
end

try
  function show(io::IO,::MIME"text/plain",mt::myType)
    return string("-- ", mt.text, " --");
  end
end
```
will actually not create a new method for the function Base.show, but a new local function show with one method.

Is this change intended? I couldn't find anything about it in the release notes.

**Comment by JeffBezanson** [comment]
It looks like this was a bug in 0.4, since `try` blocks introduce scopes. For example in 0.4:

```
julia> for i=1:1
        function test(x)
          x+1
        end
       end

julia> test
ERROR: UndefVarError: test not defined
```

so other blocks that introduce scopes behaved this way before, but not `try` blocks for some reason.

**Comment by TotalVerb** [comment]
Use `global function show(...)` instead of `function show(...)` to explicitly define a function in global scope.

**Comment by tauu** [comment]
Thanks for the clarification! :-)  

`try global function show(...) end` works in v0.5 👍 , but doesn't work in v0.4 :-/ So its not ideal for backwards compatibility, but at least it works :-)

**Comment by TotalVerb** [comment]
This should work on both:

```julia 
try
    global foo
    function foo(...) ... end
```

**Comment by tauu** [comment]
it works, thanks! :-)

**Comment by kshyatt** [comment]
>works, thanks! :-)

Sounds like this was resolved? Feel free to reopen if not, @tauu :).
