### ISSUE TITLE
Incorrect line number in error when interpolating inside docstring

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#18764]
If you save this to a file and `include` it, you will get an error on line 481, which obviously doesn't exist. It looks like the line number is the same whatever the contents of the file.

``` julia
"""
$A
"""
function f end
```

Output:

``` julia
julia> include("/home/milan/tmp/test.jl")
ERROR: LoadError: UndefVarError: A not defined
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
while loading /home/milan/tmp/test.jl, in expression starting on line 481
```

Cc: @MichaelHatherly

**Comment by MichaelHatherly** [comment]
This isn't docsystem-specific as far as I recall:

```julia
macro m(str)
    quote
        $(esc(str))
    end
end

@m "$A"
```

```
julia> include("18764.jl")
ERROR: LoadError: UndefVarError: A not defined
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
while loading /home/mike/18764.jl, in expression starting on line 3
```

The last line should be `line 7`, not `line 3`. I'm pretty sure there's already an open issue for this.

**Comment by aviks** [comment]
This came up on SO: http://stackoverflow.com/questions/39884453/what-does-it-mean-when-a-julia-error-references-a-line-number-that-doesnt-exist

This is deeply confusing for most users, and makes it impossible to find errors. I had to resort to binary search by deletion to figure out the actual error :(

**Comment by nalimilan** [comment]
Fixed on master:
```julia
julia> include("test.jl")
ERROR: LoadError: UndefVarError: A not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:295 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1060
 [4] include(::Module, ::String) at ./sysimg.jl:27
 [5] include(::String) at ./sysimg.jl:66
 [6] top-level scope
in expression starting at /home/milan/tmp/test.jl:1
```
