### ISSUE TITLE
`names(m, true, true)` doesn't show names brought by `using` until they are used

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#18768]
```julia
module A
  export x
  const x = 10 # happens with normal globals and functions as well
end
```
```julia
julia> using A

julia> :x in names(Main, true, true)
false

julia> x
10

julia> :x in names(Main, true, true)
true

julia> :x in names(Main, true) # just to confirm it's being counted as an imported name
false
```
I don't know if the correct behavior is for `x` to always show up or to never show up at all, since it's not properly `import`ed. (If the latter, an `isusing(::Module, ::Module)` or `usedmodules(::Module)` function would fill the gaps nicely)

As tested in `0.5.0` and `0.6.0-dev.856`.

(sorry if this is a duplicate, `names` and `using` aren't easy to search for :P)

**Comment by tkelman** [comment]
possibly related to #17140 ?

**Comment by JeffBezanson** [comment]
I would say names visible only by `using` should never appear in there.
