### ISSUE TITLE
Julia IDE with server mode

### ISSUE THREAD

**Issue by kindlychung** [JuliaLang/julia#18775]
RStudio has this great feature that you can run it on the server and use it remotely from a web browser. Something like this for Julia would highly desirable.

**Comment by ViralBShah** [comment]
Please discuss this on julia-users. This repo is for the compiler and base libraries only.

**Comment by StefanKarpinski** [comment]
[Jupyter](http://jupyter.org/) + [IJulia](https://github.com/JuliaLang/IJulia.jl); hosted version of same: [JuliaBox](https://juliabox.com/).
