### ISSUE TITLE
callsite inlining

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18773]
Couldn't  find an issue  (somewhat related https://github.com/JuliaLang/julia/issues/15942) 

It would be great to be able to inline functions at callsite

``` julia
function f(x)
     y = x + 2
     @inline z = g(y)
     return z + y
end
```

This would be nice since it prevents having to rewrite the function `g(x)` to be a  'private' function that is always inlined with `@inline`   and then having to  rewriting a corresponding public function `g_public(x)` that  just calls private `g(x)` function that is always inlined.

**Comment by jw3126** [comment]
I think it would also be nice to have the same for `@noinline`. It would be useful in situations, where one has type instability and needs to make sure it does not propagate.

**Comment by musm** [comment]
Is this something Julia will implement in the near future for v0.6 or v1.0?

**Comment by StefanKarpinski** [comment]
As soon as someone harasses/bribes @vtjnash to implement it – which he's claimed a few times is "trivial"... There's probably a branch somewhere that implements it that he's withholding :P

**Comment by vtjnash** [comment]
`@noinline` is trivial, but `@inline` is not nearly as trivial anymore.

**Comment by musm** [comment]
If `@noinline` is trivial would be good to at least have that then?

**Comment by kcajf** [comment]
This would still be a very useful feature. How hard do you think it is to implement? With some guidance, I could try and make a stab at it.

**Comment by vtjnash** [comment]
I’d suggest doing callsite no-inline first. I think if you follow the implementation of the `@inbounds` annotation, that’ll lead you most of the way there. That would then likely provide a framework filling in the callsite inlining details subsequently.
