### ISSUE TITLE
CplexSolver doesn't work after using workspace() code

### ISSUE THREAD

**Issue by DuaaSerhan** [JuliaLang/julia#18776]
I have a problem with using CplexSolver in Atom. The first time I run the code, the code work fine. However, when I run it for the second time, an error shows up " solver argument (CPLEX.CplexSolver(Any[])) must be an AbstractMathProgSolver".  I found out when I use workspace() to clear the console, the same error shows up. This error appears when I updated julia-clinet, ink, uber-juno, and language-julia packages.  This error will also show up when using CbcSolver. 

![capture](https://cloud.githubusercontent.com/assets/20303523/19043413/0d08c2ee-895e-11e6-98a1-af72a25d0078.PNG)

Could you please help me with this issue? To avoid this issue, I keep reopening Atom each time I want to run the program again. 

**First part of the code:**    

# for powershell issue
#Pkg.build("MbedTLS")
#Pkg.build("Atom")
#Pkg.update()

# Instulling solver packages
#Pkg.add("GLPKMathProgInterface")
#Pkg.add("JuMP")
#Pkg.add("CPLEX")
#Pkg.add("Cbc")

workspace()

using JuMP
using CPLEX

obj = JuMP.Model(solver=CPLEX.CplexSolver());

**Packages installed:** 

5 required packages:
 - Atom                          0.5.2
 - CPLEX                         0.1.6
 - Cbc                           0.2.4
 - GLPKMathProgInterface         0.2.3
 - JuMP                          0.14.1
55 additional packages:
 - ASTInterpreter                0.0.4
 - AbstractTrees                 0.0.4
 - ArgParse                      0.3.1
 - BinDeps                       0.4.5
 - Blink                         0.4.1
 - BufferedStreams               0.2.0
 - COFF                          0.0.2
 - CRC                           1.1.1
 - Calculus                      0.1.15
 - CodeTools                     0.4.1
 - Codecs                        0.2.0
 - ColorTypes                    0.2.8
 - Colors                        0.6.8
 - Compat                        0.9.2
 - DWARF                         0.1.0
 - DataStructures                0.4.6
 - ELF                           0.1.0
 - FileIO                        0.1.2
 - FixedPointNumbers             0.1.8
 - ForwardDiff                   0.2.5
 - GLPK                          0.3.0
 - Gallium                       0.0.4
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.6
 - JSON                          0.7.1
 - JuliaParser                   0.7.4
 - Juno                          0.2.2
 - LNR                           0.0.2
 - Lazy                          0.11.2
 - LegacyStrings                 0.1.1
 - LibExpat                      0.2.1
 - Libz                          0.2.0
 - MachO                         0.0.4
 - MacroTools                    0.3.2
 - MathProgBase                  0.5.6
 - MbedTLS                       0.3.0
 - Media                         0.2.2
 - Mustache                      0.1.2
 - Mux                           0.2.1
 - NaNMath                       0.2.1
 - ObjFileBase                   0.0.4
 - Reactive                      0.3.5
 - Reexport                      0.0.3
 - Requires                      0.3.0
 - ReverseDiffSparse             0.5.8
 - SHA                           0.2.1
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WebSockets                    0.2.1
 - WinRPM                        0.2.1

**Comment by ViralBShah** [comment]
Please file this at [CPLEX.jl](https://github.com/JuliaOpt/CPLEX.jl)
