### ISSUE TITLE
Julia doesn't constant fold simple test funcion

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18789]
See
```julia
function test1(x)
	y = 2.0
	u = 2.320
	x < 0 && (u = 32.0)
	x > 1 && (u = 1.0)
	return u + y
end


function test2(x)
	y = 2.0
	u = 2.320
	u = x < 0 ? 32.0 : u
	u = x > 1 ? 1.0 : u
	return u + y
end
```

`@code_lowered test1(x)`  no temporaries
`@code_lowered test2(x)` temporaries

Coresponding c++ code  from gcc/clang compiler for test1 and test2  produce same native code: see  https://godbolt.org/g/lGxa5Y

**Comment by yuyichao** [comment]
Constant propagation is done in inference and the llvm ir produced are almost the same (at least there's no "temporaries" in either.)

**Comment by musm** [comment]
code_native for both are different

**Comment by yuyichao** [comment]
And they only differ by how llvm decides to load the constant. Both have similar number of instructions and both longer than the clang version because we turn off frame pointer omition for better backtrace.

**Comment by musm** [comment]
I see, thanks!
