### ISSUE TITLE
Function composition operator?

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#18783]
Would it be worthwhile to have a function composition operator in julia? I often have code which looks like
```
map(x -> g(f(x)), iter)
```
or maybe
```
hgf(x) = x |> f |> g |> h
map(hgf, iter)
```
I think it would be nice to write this as

```
map(g∘f, iter)
map(h∘g∘f, iter)
```

A basic implementation would be
```
∘(g,f) = x-> g(f(x))
```
See also  #5236

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/17184 and https://github.com/JuliaLang/julia/pull/17155

**Comment by jw3126** [comment]
Thanks, I guess there is no need to have another place for discussing this.
