### ISSUE TITLE
compiling from source fails with llvm-3.7.1.src.tar.xz on RHEL5

### ISSUE THREAD

**Issue by sfishback** [JuliaLang/julia#18787]
I'm running on RedHat EL5.   The make steps require access to a llvm-x.x.x.src.tar.xz file which isn't working.
I have xz and gtar installed but it doesn't recognize the format.   Is there a way to workaround the issue or what do you recommend?
 
<snip of compile>
patching file test.c
patching file dSFMT.c
--2016-10-03 16:18:08--  https://cache.julialang.org/http://llvm.org/releases/3.7.1/llvm-3.7.1.src.tar.xz
Resolving cache.julialang.org... 52.91.20.35
Connecting to cache.julialang.org|52.91.20.35|:443... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: https://juliacache.s3.amazonaws.com/llvm-3.7.1.src.tar.xz [following]
--2016-10-03 16:18:08--  https://juliacache.s3.amazonaws.com/llvm-3.7.1.src.tar.xz
Resolving juliacache.s3.amazonaws.com... 52.216.224.224
Connecting to juliacache.s3.amazonaws.com|52.216.224.224|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14592544 (14M) [application/octet-stream]
Saving to: `/netscr/fishback/julia/deps/srccache/llvm-3.7.1.src.tar.xz'

100%[==============================================================================================================>] 14,592,544  10.9M/s   in 1.3s    

2016-10-03 16:18:10 (10.9 MB/s) - `/netscr/fishback/julia/deps/srccache/llvm-3.7.1.src.tar.xz' saved [14592544/14592544]

/bin/gtar: This does not look like a tar archive
/bin/gtar: Skipping to next header
/bin/gtar: Archive contains obsolescent base-64 headers
/bin/gtar: Read 544 bytes from /netscr/fishback/julia/deps/srccache/llvm-3.7.1.src.tar.xz
/bin/gtar: Error exit delayed from previous errors
make[1]: *** [/netscr/fishback/julia/deps/srccache/llvm-3.7.1.extracted] Error 2
make: *** [julia-deps] Error 2

killdevil-login2:fishback: gtar -tf /netscr/fishback/julia-master/deps/srccache/llvm-3.7.1.src.tar.xz 
gtar: This does not look like a tar archive
gtar: Skipping to next header
gtar: Archive contains obsolescent base-64 headers
gtar: Read 544 bytes from /netscr/fishback/julia-master/deps/srccache/llvm-3.7.1.src.tar.xz
gtar: Error exit delayed from previous errors

killdevil-login2:fishback: xz --help |  egrep 'bsdtar|strip-components'

killdevil-login2:fishback: gtar --help |  egrep 'bsdtar|strip-components'
      --strip-components=NUMBER   strip NUMBER leading components from file

**Comment by vtjnash** [comment]
apparently most `tar` implementation we've come across so far autodetect the `-J` flag, but not yours. I guess we should probably be explicit about the format, or pipe it through `xz` manually.

**Comment by tkelman** [comment]
the version of tar you're using is too old. you can build a newer one.

**Comment by sfishback** [comment]
updating to gtar v1.29 fixed this issue.   I think RHEL5 comes with v1.15
