### ISSUE TITLE
ERROR: MethodError: no method matching bits(::BigFloat)

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18790]
Sure BigFloats are software and do not have a concrete representation in  hardware, but based in its precision we could still spit out the literal bit representation of the number. 

```
  bits(n)

  A string giving the literal bit representation of a number.

```

**Comment by yuyichao** [comment]
`bits(::BigInt)` might make sense (although how many `f` or `0` do you put?). I double if `bits(::BigFloat)` is meaningful though. How do you divide the sign bit, the exponent and the fraction parts?

**Comment by musm** [comment]
Good point on the BigFloat

BigInt makes sense

**Comment by yuyichao** [comment]
Although `BigInt` is also not stored in the same format as machine size integers so I'm not sure if `bits` makes sense for it either. (I would either not be what many people would expect, or not what actually stored)
