### ISSUE TITLE
  julialang.org uses an invalid security certificate.

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#18798]
from Firefox in Linux

> julialang.org uses an invalid security certificate.
> 
> The certificate is only valid for the following names:
>   *.github.com, github.com, *.github.io  
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by yuyichao** [comment]
Basically dup of https://github.com/JuliaLang/julialang.github.com/issues/198 (and it's a github issue unless we start our own host)
