### ISSUE TITLE
initialize uv_eventloop for userimg.jl

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#18792]
Need to rework a bit of this code, but should be safe to init `uv_eventloop` early and make it usable from userimg.jl code (needed for calling readdir, for example)

**Comment by brady9** [comment]
I am hitting this issue while statically compiling our code. Is there a patch for fixing this issue? If there is no patch, I can help to create one if someone can outline what work needs to be done. Please note I am new to Julia, I am taking this as a learning opportunity.

**Comment by tkelman** [comment]
what julia version are you using?

**Comment by brady9** [comment]
I am on release-0.5 branch.

**Comment by brady9** [comment]
I just tried on release-0.6 branch and latest code, I hit the same issue.

**Comment by tkelman** [comment]
exactly what are you trying to run and exactly what error do you get? what platform?

**Comment by brady9** [comment]
Based on logs, these are the commands are actual commands used:

build_sysimg.jl:
 /data/workspace/julia-latest/usr/bin/julia /home/brady/.julia/v0.7/BuildExecutable/src/build_sysimg.jl /data/workspace/julia-latest/usr/lib/libtest_executable native /tmp/tmp6lVLro/userimg.jl --force

Build inference.o
/data/workspace/julia-latest/usr/bin/julia -C native --output-ji /data/workspace/julia-latest/usr/lib/inference.ji --output-o /data/workspace/julia-latest/usr/lib/inference.o coreimg.jl

Build sys.o:
 /data/workspace/julia-latest/usr/bin/julia -C native --output-ji /data/workspace/julia-latest/usr/lib/libtest_executable.ji --output-o /data/workspace/julia-latest/usr/lib/libtest_executable.o -J /data/workspace/julia-latest/usr/lib/inference.ji --startup-file=no sysimg.jl

I use BuildExecutable.jl to build binary. BuildExecutable.jl doesn't work with latest Julia. I had to make a couple of minor changes.

Below is my build script.

using BuildExecutable
using Compat
script = joinpath(dirname(@__FILE__), "test.jl")
targetdir = joinpath(dirname(@__FILE__),"test_dir")
mkdir(targetdir, 0o777)
exename="test_executable"
build_executable(exename, script, targetdir, "native"; force=false) == 0

test.jl has the following code:

import Base.Test
import JSON
import CUBLAS
import CUDArt

function main()
    s = "{\"number\" : 5, \"arr\" : [3, 2, 5, 4]}"
    j = JSON.parse(s)
    Base.Test.@test  maximum(j["arr"]) == j["number"]
    println(join(ARGS,","))
end

My goal is build a binary which uses CUBLAS module. That is why the code is like this. I am attaching full log.

[julia_build_log.txt](https://github.com/JuliaLang/julia/files/1086414/julia_build_log.txt)

**Comment by brady9** [comment]
It is x86-64 Ubuntu 16.04.2 LTS. gcc 5.4.0

**Comment by Alexander-Barth** [comment]
I am hitting the same issue when I want to compile a code with BuildExecutables running an external program, such as:

```julia
readstring(`curl --data some_data http://some.domain`)
```

If I comment this line out, then the binary gets created. Calling directly the `download` function produces the same error. This is the error I get:

```
LoadError("sysimg.jl", 408, LoadError("/home/abarth/opt/julia-0.6.0/share/julia/base/userimg.jl", 1, LoadError("/home/abarth/src/HF-radar-assim-caen/submit-result.jl", 266, UndefVarError(:uv_eventloop))))
```

I use julia 0.6.0 on Ubuntu 14.04 x86_64.

**Comment by vtjnash** [comment]
Recommendation now is to avoid this and use incremental compile and then link the result (e.g. PackageCompilerX now), though we also now do this
