### ISSUE TITLE
Possible compilation bug - execution and `@code_native` sometimes don't terminate when rebinding variables

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#18794]
I have made a few small changes to *StaticArrays.jl* and found that my tests fail to terminate in certain circumstances. I've managed to make a smallish repro:

```julia
Pkg.add("StaticArrays")
Pkg.checkout("StaticArrays","fast_array_convert")
using StaticArrays
function f()
    m_array = rand(1:10, 10, 10)
    n_array = rand(1:10, 10, 10)
    a_array = m_array*n_array

    m = SMatrix{10,10}(m_array)
    n = SMatrix{10,10}(n_array)
    out1 = (m*n === SMatrix{10,10}(a_array))

    m_array = rand(1:10, 16, 16)
    n_array = rand(1:10, 16, 16)
    a_array = m_array*n_array

    m = SMatrix{16,16}(m_array)
    n = SMatrix{16,16}(n_array)
    out2 = ( m*n === SMatrix{16,16}(a_array) )
    out1, out2
end
f() # doesn't terminate - need to press ctrl-c 5 times
```

However this function is fine, where I use unique variable names:
```
julia> function f()
           m_array = rand(1:10, 10, 10)
           n_array = rand(1:10, 10, 10)
           a_array = m_array*n_array

           m = SMatrix{10,10}(m_array)
           n = SMatrix{10,10}(n_array)
           out1 = (m*n === SMatrix{10,10}(a_array))

           m_array2 = rand(1:10, 16, 16)
           n_array2 = rand(1:10, 16, 16)
           a_array2 = m_array2*n_array2

           m2 = SMatrix{16,16}(m_array2)
           n2 = SMatrix{16,16}(n_array2)
           out2 = ( m2*n2 === SMatrix{16,16}(a_array2) )
           out1, out2
       end
f (generic function with 1 method)

julia> f()
(true,true)
```

So avoiding rebinding the variables seems to fix the problem. I'm not sure what part of the process is going wrong. I can generate up to `@code_llvm` but `@code_native` is not terminating either. 

To give some hints: this seems really fragile to relatively small changes to `StaticArrays`. I came across this when I changed some code for the conversion from `Array` to static arrays (the lines starting with `m = ...` and `n = ...`). However the freezing specifically occurs when I include both the multiplication operations `m*n` (which result in a large amount of inlined code to be added to the function).

EDIT - I've reproduced this on Linux and Windows on v0.5.0, but somehow travis didn't have this problem (tests completed in 40 seconds which is typical for this package).

**Comment by vtjnash** [comment]
It looks like SMatrix is expanding to code that creates several thousand stack copies of `[256 x i64]`. In the type-stable case, the compiler is lazy and mostly elids these, but in the type-unstable case we are failing to fall back to malloc and making a copy of the gc-root instead. (well, we're also failing to call malloc in the first case, but it makes fewer copies so the performance loss from this is less obvious; and without loops there's no chance of it recognizing the blas kernel in this, or even just rerolled, so it's already giving up 1-2 orders of magnitude of performance anyways).

**Comment by andyferris** [comment]
> It looks like SMatrix is expanding to code that creates several thousand stack copies of [256 x i64]

Right - I'm not surprised these loops are harsh on the compiler! It was even worse when I unrolled all three matrix multiplication loops (now for dimensions greater than 14 it only unrolls two loops and the generated Julia code length is linear in the number of elements).

From memory it should have 256 `Int`s that are rebound in a loop 16 times. For each of these, there is a scalar `getindex` from a tuple of length 256 stored as a field of the `SMatrix` - to me that would seem to create 65536 `getelementptr` ops to retrieve single `Int`s. I don't really understand why it is creating any new `[256 x i64]` until [the last line of code](https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/matrix_multiply.jl#L305).

(The index provided to `getindex` is computed not static, and I'm not sure if the compiler is happier if I bind the tuple which is a field of `SMatrix` as a local variable and simply index it instead).

> but in the type-unstable case we are failing to fall back to malloc so that we can make a copy of the gc-root instead. 

The example should be type-stable. Is that right? Do you have any guesses what is going wrong here?

**Comment by vtjnash** [comment]
The last line is actually the only line that doesn't need to create an array, it's just a trivial memcpy. The compiler knows enough to avoid that one :)

The example isn't type-stable. See `@code_warntype` if you don't believe me. The compiler could transform this example into a type-stable equivalent, but that optimization isn't implemented yet.

**Comment by andyferris** [comment]
> The example isn't type-stable. See @code_warntype if you don't believe me. 

OK, wow, sorry, I have to admit I *really* wasn't expecting that (and I had briefly looked but there was so much code it wouldn't even fit in my terminal buffer).

So the issue isn't exactly what I thought it was. The second example function *is* type stable so this shouldn't be StaticArrays fault.  

I thought that variables were allowed to change type so long as that was predictable (e.g. they are being rebound unconditionally, outside a loop or whatever) and that inference followed that along more-or-less perfectly. But now I take it by the comment

> The compiler could transform this example into a type-stable equivalent, but that optimization isn't implemented yet.

you mean to say that rebinding variables to a new type isn't perfectly implemented yet in *inference.jl*? But that is planned? Is it intuitive when this currently works and when this currently doesn't work?

Then of course there is the second fault where the non-type stable code has problems compiling correctly which I think you are fixing in #18817? Is that right?

And thanks Jameson for looking into this for me :)

**Comment by tkelman** [comment]
having to use a different variable name when the type might change is a gotcha that has happened a number of times inside base too, it's an easy fix when someone pinpoints a type instability caused by this but kind of sad that the manual renaming is needed
