### ISSUE TITLE
Improve test coverage of package code

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18800]
See [here](https://codecov.io/gh/kshyatt/julia/tree/ec60445ef6f702f31a387bbca5370dee7b313816/base/pkg) for latest coverage run.

This code really needs some test TLC. If you have questions about what a piece of code does, ask @Keno, me, or @wildart.

**Comment by simonbyrne** [comment]
Now has pretty good test coverage: https://codecov.io/gh/JuliaLang/Pkg.jl

(I mean, it can always be improved, but this issue doesn't need to be in julia)
