### ISSUE TITLE
Row vector issue in v0.5

### ISSUE THREAD

**Issue by krisztiankosi** [JuliaLang/julia#18805]
I generate a matrix:

```jl
julia> A=zeros(5,6)
5×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
```

```jl
If I get the second column vector from A it is OK:
julia> A[:,2]
5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
```

But If I want to get the second row vector from A, it give back a column vector:
```jl
julia> A[2,:]
6-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

It should be a row vector. The quick workaround is to transpose the result, but mathematically the correct answer is a row vector.
I'm going back to version 0.4, that gives the correct answer.

(I did not find any open issue with that problem, If I missed it, please point me there.)

**Comment by yuyichao** [comment]
This is the intended behavior, you can use `A[2:2 :]`.

**Comment by andreasnoack** [comment]
Please see https://github.com/JuliaLang/julia/blob/master/NEWS.md#breaking-changes-1 and https://github.com/JuliaLang/julia/pull/13612
