### ISSUE TITLE
Dict generators hide error message

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#18814]
If there's an error in a Dict generator expression, it seems you just get a cryptic error message with the stack trace and original message entirely hidden:

```julia
julia> Dict(i=>throw("error") for i=1:2)
ERROR: ArgumentError: Dict(kv): kv needs to be an iterator of tuples or pairs
 in Dict{K,V}(::Base.Generator{UnitRange{Int64},##1#2}) at ./dict.jl:388
```

That was on 0.5, it seems to be partially a regression since on 0.4.5. I see:

```julia
julia> [i=>throw("error") for i=1:2]
ERROR: "error"
 in anonymous at ./no file:4294967295
```

Also, it seems to apply just to Dict's, as collecting or creating a list from the generator doesn't hide the error.

**Comment by simonster** [comment]
Dup of #18708. I believe this issue also existed on 0.4, although most people didn't pass arbitrary iterables that threw errors until the introduction of generators in 0.5.
