### ISSUE TITLE
libstdc++ on ARM release

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#18816]
The version of libstc++ we bundle on the ARM release is old, giving lots of errors like:

```
julia> Libdl.dlopen("libzmq.so")
ERROR: could not load library "libzmq.so"
/home/pi/julia-3c9d75391c/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/arm-linux-gnueabihf/libzmq.so)
```

This can be easily worked around by deleting the bundled library, but it would be better to have a more general solution.

from https://github.com/JuliaLang/ZMQ.jl/issues/103#issuecomment-185665391

**Comment by ViralBShah** [comment]
Is this we build on a very old arm box? Maybe the time has come to compiler our own gcc on the arm buildbot.

Cc @staticfloat

**Comment by yuyichao** [comment]
If we upgrade the compiler version on ARM, we also need to compile LLVM with LTO to avoid 少女编号

**Comment by yuyichao** [comment]
If we want to upgrade GCC on ARM we also need to compile LLVM with LTO on to avoid https://github.com/JuliaLang/julia/issues/14550

**Comment by staticfloat** [comment]
I'm installing our own GCC on the ARM buildslave as we speak, and I've [added `-fLTO` to `CPPFLAGS` and `LDFLAGS` temporarily](https://github.com/staticfloat/julia-buildbot/commit/c47bd097daef2c9de09414c01d96bc1c5b049713) on the buildbot.

Is there any reason we can't just always include those flags?  LTO is a good thing in general, right?

**Comment by yuyichao** [comment]
I've seen worse GC (allocation) performance with LTO on x86. Haven't got time to investigate though.

**Comment by ViralBShah** [comment]
If we need LTO, it should definitely go into Make.inc - so that all the developers also have the same build process.

**Comment by Keno** [comment]
> Is there any reason we can't just always include those flags? LTO is a good thing in general, right?

It tends to blow up memory use and compile time.

**Comment by yuyichao** [comment]
> If we need LTO, it should definitely go into Make.inc

No. We should also stop using `override` in it for ARM and Power since it makes testing non-default setup a lot harder.

**Comment by ViralBShah** [comment]
That needs some cleanup. I was just lazy when I did that.

**Comment by tkelman** [comment]
we also need to be using an older glibc to make these binaries actually generic

**Comment by ViralBShah** [comment]
We are on ubuntu 14.04, which I suspect is old enough for arm.

**Comment by tkelman** [comment]
Not if anyone wants to use anything older.

**Comment by ViralBShah** [comment]
Worry about it when someone asks?

**Comment by tkelman** [comment]
If we're going to reconfigure the buildbot, we should actually do it properly.

**Comment by yuyichao** [comment]
Fixed on the buildbot.
