### ISSUE TITLE
Switch dates tests to use testsets

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18828]
These tests are pretty straightforward and well-commented. Ask @quinnj for help if you need some!

**Comment by hevalazizoglu** [comment]
I can take this one if it can wait for two or three more days. I'm new to Julia so it may take some time to setup and start :)

**Comment by Keno** [comment]
Go for it!

**Comment by darshan934** [comment]
Hi, is this still available? 
I was hoping to solve all the older beginner-esque issues to get familiar with the code base and the language!

**Comment by KristofferC** [comment]
Go for it!

**Comment by darshan934** [comment]
Thanks, could also tell me how to get started with it? I am a little new to open source and still getting familiar with how things work. 
Thank you for bearing with me!

**Comment by KristofferC** [comment]
This is good to read https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md and for writing tests, the manual entry is useful https://docs.julialang.org/en/stable/stdlib/test/.

**Comment by darshan934** [comment]
I will go through them. Thank you!

**Comment by Sacha0** [comment]
Welcome `@darshan934`! The [Julia slack](https://slackinvite.malmaud.com) has a channel (`#my-first-pr`) dedicated to helping new contributors work through their first pull request. Consider checking it out! :)

**Comment by xorJane** [comment]
Hi @darshan934! I'm relatively new myself, but feel free to ping me either here or on slack if you have any questions about getting started!

**Comment by darshan934** [comment]
That is lovely, thank you!

**Comment by quinnj** [comment]
The Dates tests use `@testset`s now.
