### ISSUE TITLE
More doctests and examples for sorting functions

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18821]
There are so many options shown in the [documentation](http://docs.julialang.org/en/latest/stdlib/sort/) for sorting and it would be great to have some working examples that show what all of these do.

**Comment by xorJane** [comment]
Hey @kshyatt! I see that only certain uses of sort() have examples provided in the documentation and that there are no examples included inline for sort(). Are you hoping to augment the manual with additional examples, to add examples to the inline docs, or both? Would you like the examples given [here](http://docs.julialang.org/en/latest/stdlib/sort/) moved inline?

**Comment by kshyatt** [comment]
Inline would be stupendous! Ideally the examples would show the behavior of
each argument to supplement the docs. I can give a more thorough answer if
that would help.

**Comment by mauro3** [comment]
X-ref: https://github.com/JuliaLang/julia/issues/18653#issuecomment-253143627

**Comment by xorJane** [comment]
Thanks for the info! Is the PR referenced above along the lines of what you were thinking?

**Comment by fredrikekre** [comment]
I think #20491 covered this.
