### ISSUE TITLE
Switch unicode tests to use testsets

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18829]
Ping @StefanKarpinski if you have questions.

**Comment by StefanKarpinski** [comment]
![fry squinty eyes](https://cloud.githubusercontent.com/assets/153596/19215071/86d15f26-8d61-11e6-8b05-c5e23053620a.jpg)

**Comment by latticetower** [comment]
Hi, 
I can work on this issue, if no one else had started it yet

**Comment by kshyatt** [comment]
Wonderful! It's all you :)

**Comment by StefanKarpinski** [comment]
I will, despite my snarking Fry meme, do what I can to answer any questions. Don't hesitate to ask.

**Comment by latticetower** [comment]
@StefanKarpinski it's ok, I like Futurama :)
For now issue seems to be quite clear - I need to change these tests: https://github.com/latticetower/julia/tree/master/test/unicode - to use `@testset` macro for more fancier look and tests grouping - please correct me if I got something wrong :)

**Comment by kshyatt** [comment]
@latticetower you've got it. Check out `test/math.jl` for examples of what this can look like. We're happy to give feedback and help you revise the PR, so don't hesitate to open a WIP one :).

**Comment by latticetower** [comment]
@kshyatt but I could do it tomorrow evening (it's now 2 a.m. at local time and I have to wake up at 7 a.m.)

**Comment by StefanKarpinski** [comment]
We're not in any position to put deadlines on people doing unpaid open source work – whenever you can will be absolutely lovely :)
