### ISSUE TITLE
More doctests/examples for filesystem functions

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18827]
See [here](https://docs.julialang.org/en/v1/base/file/) for examples. Some of this might be hard to reproduce but having examples would still be very good.

[Link updated by @ViralBShah]

**Comment by sudoankit** [comment]
I will work on it. As I'm pretty new to Julia let me know if I'm going wrong. 

- Reproduce examples locally and add to the docs.
- Build the documentation using : 

```
$ make html
$ make latexpdf
```
-  Commit locally and test using travis on my cloned Julia repository. 
-  If passes, make a pull request

Am I going correct?

**Comment by kshyatt** [comment]
You have the right idea. You should do `make docs html` I think, to
generate the html version and give it a quick visual check. Then you can
run `make -C doc doctest` to make sure all the doctests pass. If they do,
commit and push.

**Comment by sudoankit** [comment]
Thank you. I'll continue this way.
