### ISSUE TITLE
installing libuv dependency fails

### ISSUE THREAD

**Issue by DemiMarie** [JuliaLang/julia#18837]
Installing libuv fails during make install:

```
libtool: install: /usr/bin/install -c .libs/libuv.so.1.0.0 /home/dobenour/repos/julia/usr-staging/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/home/dobenour/repos/julia/usr/lib/libuv.so.1.0.0
/usr/bin/install: cannot stat '.libs/libuv.so.1.0.0': No such file or directory
Makefile:970: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
Makefile:4358: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
/home/dobenour/repos/julia/deps/libuv.mk:46: recipe for target '/home/dobenour/repos/julia/usr-staging/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8.tgz' failed
make[1]: *** [/home/dobenour/repos/julia/usr-staging/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8.tgz] Error 2
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

**Comment by vtjnash** [comment]
what does libuv have in config.log? usually this means that it thought your system / linker doesn't support dynamic libraries (which is usually caused by a misconfiguration of your build environment so that some of your environment variables are wrong for your linker)

**Comment by Mirage10** [comment]
I am facing a similar error. No clue what to do ...

g++: error: libspqr.a: No such file or directory
/home/user/julia/deps/suitesparse.mk:58: recipe for target '/home/user/julia/usr/lib/libspqr.so' failed
make[1]: *** [/home/user/julia/usr/lib/libspqr.so] Error 1
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

**Comment by tkelman** [comment]
Start by telling us as much about your system as possible. Operating system and compiler versions, etc.

**Comment by Mirage10** [comment]
here are my settings:

user@user ~ $ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 




gcc-5 is installed:
Version: 5.4.0-6ubuntu1~16.04.2

**Comment by Mirage10** [comment]
when I submit the command   sudo -E make, the following is populated:

collect2: error: ld returned 1 exit status
Makefile:129: recipe for target 'sblat1' failed
make[3]: *** [sblat1] Error 1
Makefile:111: recipe for target 'tests' failed
make[2]: *** [tests] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0' if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
/home/user/julia/deps/blas.mk:82: recipe for target 'scratch/openblas-85636ff1a015d04d3a8f960bc644b85ee5157135/build-compiled' failed
make[1]: *** [scratch/openblas-85636ff1a015d04d3a8f960bc644b85ee5157135/build-compiled] Error 1
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2


(I cloned the github and do the make )

**Comment by tkelman** [comment]
That doesn't show the actual error message. Copy more of the output and post it as a gist (https://gist.github.com) link

**Comment by KristofferC** [comment]
Please comment again with a full error message if this error persists.
