### ISSUE TITLE
`writeall` referenced in docs, but doesn't exist

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#18834]
On line 325 of [docs/manual/running-external-programs.rst](https://github.com/JuliaLang/julia/blob/master/doc/manual/running-external-programs.rst) the example solution is using a `writeall(proc, x)` function that no longer exists.

**Comment by akaysh** [comment]
@Rory-Finnegan Should this reference be completely removed or something else is required in its place?
As it is referenced as one of the ways to avoid deadlock by separation or reading and writing operations in the pipeline, I think there should be an existing alternative way to do that.

**Comment by Rory-Finnegan** [comment]
@akaysh I think you should just be able to replace `writeall(...)` with `write(...)` the deadlock avoidance is due to using `readstring` vs `wait`.

**Comment by akaysh** [comment]
@Rory-Finnegan I found the `writeall` function in `process.jl` which asynchronously runs commands using `write` function. 
Is it still required to replace the reference?

**Comment by Rory-Finnegan** [comment]
Well it isn't exported, so the example should either be removed or the code should explicitly do a `Base.writeall`.

**Comment by akaysh** [comment]
#19975 
Removed the example from the docs.

**Comment by akaysh** [comment]
@Rory-Finnegan #19975
