### ISSUE TITLE
Improve docs about documenting Julia

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#18841]
The [docs about docs](https://docs.julialang.org/en/v1/manual/documentation/) are pretty good but some things, like how to doc `@eval`-ed functions, could really use some examples (writing doctests for this would probably be really hard). There are a couple of examples of what to do scattered throughout the Julia codebase if you go `grep` hunting.

**Comment by akaysh** [comment]
@kshyatt I can help in improving documentation. Can this still be worked on?

**Comment by kshyatt** [comment]
Yes! Docs always need improvements!

I think my statement about `@eval` still applies. Other things that could use with being documented (without reproducing all the Documenter docs...) are more examples of how to doc.

**Comment by mauro3** [comment]
https://github.com/JuliaIO/FileIO.jl/issues/97#issuecomment-273571802: 
"Doesn't look like the :: syntax for ? mode is documented currently, probably worth adding that somewhere in the manual."

**Comment by ayushi19031** [comment]
@kshyatt I would like to work on this issue. Julia is my first Open source organization I will contribute to, so it will be nice if you could give me tips and suggest more stuff I can start working on.

**Comment by fredrikekre** [comment]
I updated the link.

**Comment by ViralBShah** [comment]
I think these are pretty good now.
