### ISSUE TITLE
Two-argument `bin`, `oct`, `dec`, `hex` fail on `BigInt`

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#18849]
```julia
julia> bin(big"1", 5)
ERROR: argument is an abstract type; size is indeterminate
 in convert(::Type{Unsigned}, ::BigInt) at ./gmp.jl:181
 in bin(::BigInt, ::Int64) at ./intfuncs.jl:341
```

**Comment by KlausC** [comment]
I think, the following code change (in gmp.jl) would solve the issue:
``
bin(n::BigInt, p::Int) = base( 2, n, p)
oct(n::BigInt, p::Int) = base( 8, n, p)
dec(n::BigInt, p::Int) = base(10, n, p)
hex(n::BigInt, p::Int) = base(16, n, p)

function base(b::Integer, n::BigInt, pad::Int)
    nd = ndigits(n, b)
    nd >= pad && base(b, n)
    corr = BigInt(b) ^ (pad - 1)
    if n.size >= 0
        n += corr
    else
        n -= corr
    end
    s = base(b, n)
    s.data[ifelse(n.size >= 0, 1, 2)] = '0'
    s
end
``

**Comment by yuyichao** [comment]
@KlausC Do note that this is fixed already.
