### ISSUE TITLE
@inbounds swallows expresion result

### ISSUE THREAD

**Issue by dbeach24** [JuliaLang/julia#18859]
Adding `@inbounds` to an expression replaces the expected result with `nothing`.  Is this intentional?

Using Julia 0.5.0:
```jl
julia> mysum1(x) = (s = zero(eltype(x)); for i=1:length(x) s += x[i] end; s)
julia> mysum2(x) = @inbounds (s = zero(eltype(x)); for i=1:length(x) s += x[i] end; s)

julia> mysum1(1:10)
55

julia> mysum2(1:10)
# (no result)
```

I just got burned by this while creating an example for an unrelated issue.

**Comment by yuyichao** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/15558
