### ISSUE TITLE
Parsing inconsistency when indexing into (signed) literals

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#18851]
The Julia parser is currently inconsistent about  expressions that index into literals: running

```
@show parse(" 2[m]")
@show parse("-2[m]")
```

gives

```
parse(" 2[m]") = :((2)[m])
parse("-2[m]") = :(-2 * [m])
```

so the first case produces a `:ref` expression as expected, but the second interprets the expression as a multiplication instead. I would hope that both can be interpreted as indexing.

This is of course not a common thing to do; my motivation in this case is that I'm experimenting with a DSL where one can specify units for a literal by indexing into it.

**Comment by JeffBezanson** [comment]
Another issue is that `[]` normally has higher precedence than `-`:

```
julia> parse("-x[m]")
:(-(x[m]))
```

So yes, I agree it should be a `:ref`, but I'm not sure whether it should be `(-2)[m]` or `-(2[m])`.

**Comment by toivoh** [comment]
`-(2[m])` does seem more consistent. That would work just as well for my purposes.
