### ISSUE TITLE
time macro occasionally throws a DomainError

### ISSUE THREAD

**Issue by kpamnany** [JuliaLang/julia#18868]
It appears that ``GC_Diff.allocd`` can sometimes be negative after ``GC_Diff()`` is called. This causes a ``DomainError`` when ``prettyprint_getunits()`` (called from ``time_print()``) tries to take the log of this negative value.

**Comment by yuyichao** [comment]
I assume you are running threading code?

**Comment by kpamnany** [comment]
Yep!

**Comment by KristofferC** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/17255?

**Comment by yuyichao** [comment]
Ah, yeah. (Somehow I thought it was threading.)

**Comment by kpamnany** [comment]
Indeed it is. Closing.
