### ISSUE TITLE
Method definition overwritten in control flow

### ISSUE THREAD

**Issue by cedeerwe** [JuliaLang/julia#18864]
I upgraded my Julia to 0.5.0 and I observed the following behaviour. I created a file test.jl, which looks as follows:
```
function test(flag)
  if flag
    f(x) = x
  else
    f(x) = -x
  end
  return f
end
```
If I include the code by `include("test.jl")`, I get the following warning:
```
WARNING: Method definition f(Any) in module Main at C:\Users\cedeerwe\test.jl:3 overwritten at C:\Users\cedeerwe\test.jl:5.  
```
This is weird, as in any case the function `f` will be defined only once and it won't be overwritten. I did not get such a warning in Julia 0.4.5. 

My question: Is this an improper way of defining functions (i.e., the warning makes sense) or only an undesirable behaviour from Julia?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15602

**Comment by cedeerwe** [comment]
Thanks, could not find it!
