### ISSUE TITLE
code_warntype and Expr(:&)

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#18875]
```
julia> segfault() = ccall(:free, Void, (Ptr{Int},), &0)
segfault (generic function with 1 method)

julia> @code_warntype segfault()
Variables: #self#::#segfault
Body:
  begin
    SSAValue(0) = 0
    return (Core.ccall)(:free,Main.Void,(Core.svec)((Core.apply_type)(Main.Ptr,Main.Int)::Type{Ptr{Int64}})::SimpleVector,
                        &SSAValue(0)::ANY,SSAValue(0))::Void
  end::Void
```

`@code_warntype` highlights the &-expression in red, despite it not being an actionable type instability. Perhaps `@code_warntype` should ignore `&` expressions.

cc @musm

**Comment by musm** [comment]
Also empty union types
(Amal.throw)($(Expr(:new, :(Core.DomainError))))::Union{}

**Comment by yuyichao** [comment]
It is useful to have an indicator for error since it might not be what you want and they can be a performance issue. This is the consensus from https://github.com/JuliaLang/julia/issues/13295. As mentioned there, I agree we can have more document about this.

**Comment by TotalVerb** [comment]
Since `&` is deprecated, this can be closed now.
