### ISSUE TITLE
document AbstractSet

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18878]
https://github.com/JuliaLang/julia/pull/18626

**Comment by ararslan** [comment]
Intro issue and/or Hacktoberfest candidate?

**Comment by StefanKarpinski** [comment]
I don't think it's really an intro issue since describing this interface is kind of subtle and hard.

**Comment by ararslan** [comment]
Fair point.

**Comment by StefanKarpinski** [comment]
Here's the thread that led to the introduction of this abstract type:

https://github.com/JuliaLang/julia/issues/5533#issuecomment-52102437

This is partly a design problem: write down what it means to "act like a set".

**Comment by StefanKarpinski** [comment]
It should be noted that we don't have formal documentation for what the interfaces of things like AbstractArray or Associative are, so while we should document this, AbstractSet is hardly unique.

**Comment by StefanKarpinski** [comment]
This does not seem to be release-blocking.

**Comment by laborg** [comment]
Although older, I'm closing this in favour of the duplicate https://github.com/JuliaLang/julia/issues/34677  because the newer issue contains already content that might help in actually documenting the AbstractSet interface.
