### ISSUE TITLE
Unexpected behavior when assigning to function

### ISSUE THREAD

**Issue by mfalt** [JuliaLang/julia#18877]
I am not sure if this is a bug, but the following certainly creates some unexpected behavior (unexpected error message at least) and debugging headache where the assignment to length was supposed to be a test `length(b)==2`.

``` julia
function f(a, b)
    N = length(a)
    length(b) = 2
    return N
end
f((1,2),(3,4))
```

which results in

``` julia
ERROR: UndefVarError: length not defined
 in f(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at ./REPL[3]:2
```

especially when the assignment is not even reachable

``` julia
function g(a, b)
    return length(a)
    length(b) = 2
end
g((1,2),(3,4))
```

``` julia
ERROR: UndefVarError: length not defined
 in g(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at ./REPL[6]:2
```

Notice that the error occurs at the `length(a)` call, not in the assignment statements.

Running Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)

**Comment by yuyichao** [comment]
This has nothing to do with the `@assert`. You introduced a local `length` function.

**Comment by mfalt** [comment]
It seems you are right and that I was too quick to blame `@assert`, I updated my original post. It is however still unintuitive that a later command will affect a previous one.

**Comment by yuyichao** [comment]
This is also not related to functions and is how scope supposed to work.

```jl
julia> function f()
           a
           a = 1
       end
f (generic function with 1 method)

julia> a = 2
2

julia> function g()
           a
           b = 1
       end
g (generic function with 1 method)

julia> f()
ERROR: UndefVarError: a not defined
 in f() at ./REPL[1]:2

julia> g()
1
```

**Comment by yuyichao** [comment]
And this is documented in http://julia.readthedocs.io/en/latest/manual/variables-and-scoping/#hard-local-scope under

> An assignment introducing a variable used inside a function, type or macro definition need not come before its inner usage:

PR to add more doc about this possibly to a more obvious place is welcome.

**Comment by StefanKarpinski** [comment]
Where else would this be documented?

**Comment by mfalt** [comment]
Thanks, once I realized that the assign statement was not involved it is quite understandable that this is the behavior.
It would be nice however to explicitly state somewhere in the docs that introducing a local variable turns all references to that variable to local references (even those occurring before the assignment) as shown in your example. I see no reason not to document this at the same place.

**Comment by kshyatt** [comment]
@mfalt Would you be willing to open a PR to document this? As someone who got caught by it you're a natural candidate to explain it well to others. If you'd like help/guidance for the process of doing a Julia doc PR we'd be happy to help you out.
