### ISSUE TITLE
findmax does not squeeze out singleton index

### ISSUE THREAD

**Issue by floswald** [JuliaLang/julia#18884]
i'm not sure whether this is intended but I think `findmax` does not conform to the new rule on singleton indices:

```julia
julia> x = rand(2,2,2)
2×2×2 Array{Float64,3}:
[:, :, 1] =
 0.319551  0.616412
 0.740493  0.112079

[:, :, 2] =
 0.0639773  0.376866
 0.475386   0.46051 

julia> z = findmax(x,2);

julia> z[1]
2×1×2 Array{Float64,3}:
[:, :, 1] =
 0.616412
 0.740493

[:, :, 2] =
 0.376866
 0.475386
```
I would expect a `(2,2)`, i.e. the scalar dim should be `squeeze`d out.

```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

(sorry for posting on a [merged PR](https://github.com/JuliaLang/julia/pull/13612) before - deleted comment)

**Comment by simonster** [comment]
`sum`, `maximum`, etc. don't either. The behavior of reductions was intentionally not changed. See https://github.com/JuliaLang/julia/pull/13612#issuecomment-170288005

**Comment by floswald** [comment]
ah ok i see. thanks.
