### ISSUE TITLE
Non-standard literal convention

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#18898]
In a section of strings docs, I found a skeptical sentence:
> A non-standard string literal looks like a regular double-quoted string literal, but is immediately prefixed by an identifier, and doesn’t behave quite like a normal string literal. **The convention is that non-standard literals with uppercase prefixes produce actual string objects**, while those with lowercase prefixes produce non-string objects like byte arrays or compiled regular expressions. Regular expressions, byte array literals and version number literals, as described below, are some examples of non-standard string literals.

I've never seen any example of the exaggerated sentence and an example, `MIME_str` macro, doesn't follow it. So, I think we can safely remove it if the convention is no longer active. Any thoughts?

**Comment by JeffBezanson** [comment]
Yes I agree.

**Comment by StefanKarpinski** [comment]
Yeah, I wrote that and then everyone (myself included) ignored it, so +1 to deletion.

**Comment by bicycle1885** [comment]
Ok, thank you. I opened a pull request to remove it.
