### ISSUE TITLE
Parameterized methods can shadow other method without error/warning

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#18892]
Parameterized methods are more specific than non-parameterized ones:

```
julia> g(x) = 1
g (generic function with 1 method)

julia> g{X}(x::X) = 2
g (generic function with 2 methods)

julia> g(4)
2
```

I don't think there is any way to call the first method of `g`.

Similarly for several arguments:

```
julia> h(x,y) = 1
h (generic function with 1 method)

julia> h{X}(x::X,y) = 2
h (generic function with 2 methods)

julia> h{X,Y}(x::X,y::Y) = 3
h (generic function with 3 methods)

julia> h{Y}(x,y::Y) = 4
h (generic function with 4 methods)

julia> h(4,5)
2
```

One solution is to  consider above methods ambiguous and throw `MethodError ... is ambiguous.` on call.  Another solution is to make those method definitions overwrite the previous one.  Probably should be in sync with #8974.

X-ref: https://groups.google.com/d/msg/julia-users/-ldkZlbg76Q/pYRNT4eIBAAJ

**Comment by JeffBezanson** [comment]
Yes, #8974 will provide a definitive type equality test that will allow these method overwrites to happen.

**Comment by JeffBezanson** [comment]
closed by #18457

**Comment by vtjnash** [comment]
This is still an issue, since type-equal is not the same as sig-equal due to the extra parameters-must-match rule. That can cause us to incorrectly delete a method that may still be needed, or replace a method with one that is not equivalent (mostly resulting from Varargs).

**Comment by JeffBezanson** [comment]
Closing in favor of #21026, which is more specifically about that.
