### ISSUE TITLE
Pkg3 location and design documents?

### ISSUE THREAD

**Issue by habemus-papadum** [JuliaLang/julia#18897]
Apologies, but I could not find an existing issue discussing broad design changes and goals for the Pkg system in future Julia's -- I did come across #18795, which discusses some narrower issues regarding potential refactoring of code in `base` for 0.6, and I did see the JuliaCon16 slides for Pkg3 which were more ambitious, but I can't find much more detail and am wondering if Pkg3 was abandoned?   I am curious to know more about how the Pkg system will be evolving (and share some thoughts).  If you could point me to the proper discussion forum that would be great.  Cheers, nehal

**Comment by oxinabox** [comment]
julia-dev Mailing List
https://groups.google.com/forum/#!topic/julia-dev/PMVTzOjR3ZM

@StefanKarpinski 

> As soon as we get the 0.5 RC out I was going to start on working with Art to get a formal Julep out there.

I've been watching this space with interest also.  Yet to see anything, but patience is a virtue and all that.

**Comment by StefanKarpinski** [comment]
I'm working on it... imminently forthcoming.

**Comment by lilinjn** [comment]
Good to know, no worries, and don't rush it -- it all seems a bit complicated, and yet important.

**Comment by tbreloff** [comment]
https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md with discussion in the issues: https://github.com/JuliaLang/Juleps/issues

**Comment by KristofferC** [comment]
Nothing actionable here to do.
