### ISSUE TITLE
more precise typing in Dict constructor?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#18906]
`Dict(3=>4, 3.5=>4.5)` gives `Dict{Any,Any}`; shouldn't it give `Dict{Real,Real}`, since `typejoin(Int,Float64)` is `Real`?

Possibly the issue here is due to the behavior of `typejoin` on `Pair`s.  For example, `typejoin(Complex{Int},Complex{Float64})` gives `Complex{T<:Real}`, but `typejoin(Pair{Int,Int},Pair{Float64,Float64})` gives `Pair{A,B}`.

(A related question came up on [julia-users](https://groups.google.com/d/msg/julia-users/DWwR422c3NU/a5GvxEKyBAAJ).)

**Comment by stevengj** [comment]
Actually, the source of this behavior seems to be the `Dict(     ps::Pair...) = Dict{Any,Any}(ps)` constructor in `base/dict.jl`.  In principle, this seems like it could do a `typejoin` instead, though implementing this in a type-stable way may require careful coding?

Of course, the caller can always explicitly supply the dictionary types via `Dict{K,V}(...)`, but it is somewhat annoying to have to supply types that, in principle, the compiler could deduce.

**Comment by davidavdav** [comment]
The comprehension `Dict(x => y for (x,y) in [(3,4), (3.5,4.5)])` does give the expected `Dict{Real,Real}`.  That is why I was surprised by the result of `Dict(3=>4, 3.5=>4.5)`.

**Comment by stevengj** [comment]
@davidavdav, that's because `Dict(generator)` ends up in a different codepath [that does call typejoin](https://github.com/JuliaLang/julia/blob/4ba21aa57f57b9e42eeba5886d9dec772281e9f2/base/dict.jl#L168-L181).

**Comment by StefanKarpinski** [comment]
Technically breaking but only very mildly so. I think this change makes sense and bot constructors should call typejoin.

**Comment by KristofferC** [comment]
```
julia> Dict(3=>4, 3.5=>4.5)
Dict{Real,Real} with 2 entries:
  3   => 4
  3.5 => 4.5
```

https://github.com/JuliaLang/julia/pull/25805
