### ISSUE TITLE
Specific problem with readdlm / readcsv in a virtual linux environment

### ISSUE THREAD

**Issue by charlesll** [JuliaLang/julia#18916]
Hello,

OS: Fedora 24 in VirtualBox, host OSX
Julia versions: 0.4.6, 0.5

I encountered an interesting issue with trying to read files with readdlm / readcsv in a Virtualbox shared folder in Fedora 24 running in VirtualBox (host OSX).

Everything works fine if I try reading files in a folder in the Linux guest machine with the readdlm/readcsv commands. However, trying to read the same file dropped in a VirtualBox shared folder (between the host and the guest) with the same code, I get the following error message:

```
LoadError: SystemError: memory mapping failed: Invalid argument
while loading In[17], in expression starting on line 1

 in #mmap#1(::Bool, ::Bool, ::Function, ::IOStream, ::Type{Array{UInt8,1}}, ::Tuple{Int64}, ::Int64) at ./mmap.jl:124
 in (::Base.Mmap.#kw##mmap)(::Array{Any,1}, ::Base.Mmap.#mmap, ::IOStream, ::Type{Array{UInt8,1}}, ::Tuple{Int64}, ::Int64) at ./<missing>:0
 in open(::Base.Mmap.##7#8{Array{UInt8,1},Bool,Bool,Tuple{Int64},Int64}, ::String, ::String) at ./iostream.jl:113
 in #mmap#6(::Bool, ::Bool, ::Function, ::String, ::Type{Array{UInt8,1}}, ::Tuple{Int64}, ::Int64) at ./mmap.jl:152
 in #readdlm_auto#11(::Array{Any,1}, ::Function, ::String, ::Char, ::Type{T}, ::Char, ::Bool) at ./datafmt.jl:118
 in #readdlm#7(::Array{Any,1}, ::Function, ::String, ::Char, ::Char) at ./datafmt.jl:73
 in #readdlm#6(::Array{Any,1}, ::Function, ::String, ::Char) at ./datafmt.jl:65
 in #readcsv#12(::Array{Any,1}, ::Function, ::String) at ./datafmt.jl:623
 in readcsv(::String) at ./datafmt.jl:623
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/charles/.julia/v0.5/IJulia/src/execute_request.jl:169
 in eventloop(::ZMQ.Socket) at /home/charles/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360
```

This issue is very strange. Indeed, in the same context, the open() command works fine, and readtable() from the DataFrames package also works fine and imports the data. Therefore, I am quite puzzled about the origin of this issue that seems to concern specifically readdlm/readcsv, in this very particular case of reading the file in the VirtualBox shared folder...

I know that this is quite a specific issue, but it may be interesting to understand why it is badly behaving? I include a screenshot showing the tests I did with open(), readtable() and readcsv/readdlm. I tried in 0.4.6 and 0.5.0 and get the same errors for readcsv/readdlm.

Charles.

![screenshot from 2016-10-14 10-48-52](https://cloud.githubusercontent.com/assets/6821569/19371066/db1204e8-91fb-11e6-9950-d24be66af8b8.png)

**Comment by tkelman** [comment]
Another case in which enabling mmap by default causes problems. There's a keyword argument to not use mmap which should help here.

**Comment by charlesll** [comment]
Exact, it solved the issue. Any idea about why memory mapping fails on those VirtualBox shared folders?

**Comment by tkelman** [comment]
limitation of virtualbox host-guest mapping, probably? or maybe some kind of permissions thing?

**Comment by charlesll** [comment]
I guess it comes from the Virtualbox mapping, because the other commands (open, readtable) work fine and, hence, this rules out permission issues. 

Anyway, setting "use_mmap = false" in readcsv/readdlm completely solves the problem. Good to know for people using Julia in virtual environments!
