### ISSUE TITLE
possible GC performance regression

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#18914]
I came across a gc-heavy benchmark that seems to have regressed from 0.4 to 0.5:

```
@noinline f5() = Float64[2*j for j in 1:3]

f5()

@time for i in 1:100000; r = f5(); end
@time for i in 1:100000; r = f5(); end
@time for i in 1:100000; r = f5(); end
@time for i in 1:100000; r = f5(); end
@time for i in 1:100000; r = f5(); end
```

On 0.4:

```
  0.004160 seconds (100.00 k allocations: 9.155 MB)
  0.046366 seconds (100.00 k allocations: 9.155 MB, 92.20% gc time)
  0.003872 seconds (100.00 k allocations: 9.155 MB)
  0.038521 seconds (100.00 k allocations: 9.155 MB, 91.27% gc time)
  0.003446 seconds (100.00 k allocations: 9.155 MB)
```

on 0.5:

```
  0.003650 seconds (100.00 k allocations: 10.681 MB)
  0.005499 seconds (100.00 k allocations: 10.681 MB)
  0.062359 seconds (100.00 k allocations: 10.681 MB, 93.21% gc time)
  0.003345 seconds (100.00 k allocations: 10.681 MB)
  0.059929 seconds (100.00 k allocations: 10.681 MB, 94.70% gc time)
```

I tried disabling threading but it didn't seem to have any impact. It's also interesting that 0.5 allocates more memory, apparently in the same number of allocations, and I'm not sure why.

**Comment by yuyichao** [comment]
I need to do the math when I'm back ho

**Comment by yuyichao** [comment]
.... Probably shouldn't have typed on my phone while walking given I'm just 3min away to home..... The increase in allocation size is likely due to the increase in array alignment. Not sure about the increase in GC/allocation time yet.

@JeffBezanson what's your total memory size? I believe we set the collection interval based on that on 64bit systems. With 16G of ram, I'm seeing GC time ranging from 20% to 40% and never close to 90%.

**Comment by JeffBezanson** [comment]
I have 8GB.

**Comment by yuyichao** [comment]
Also, on master, there seems to be an allocation of `Tuple{Int}` per `f5`.

**Comment by PallHaraldsson** [comment]
"I believe we set the collection interval"

Are there many parameters? Are all hardcoded (or hardcoded based on 32- vs 64-bit)? Can't find anything on this, just "documented" by the source code? Go has just one tunable.

**Comment by ViralBShah** [comment]
On 0.6, I get the same amount of memory allocation (100k, 10.681MB) but in a couple of those runs, 20-50% GC time. Does this still need to be kept open?

**Comment by vtjnash** [comment]
I can confirm it seems like we avoid the 90% gc-time now.
