### ISSUE TITLE
inlining at top level can be a bad idea

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#18921]
This is an especially bad case of #12219:

```
f1(r) = [2.0*j for j in r]
@noinline f2(r) = [2.0*j for j in r]
r = 1:3

julia> @time for i in 1:100000; f1(r); end
  0.665140 seconds (200.00 k allocations: 12.207 MB, 9.28% gc time)

julia> @time for i in 1:100000; f2(r); end
  0.005548 seconds (200.00 k allocations: 12.207 MB)
```

Running type inference and optimizations at the top level is already often not worth it and can slow down loading. However this case seems easier to handle than the general problem. We can either use different inlining heuristics for toplevel code, or teach the inliner that a "global" has a fixed type once it has been substituted for a function argument.

**Comment by yuyichao** [comment]
Similar (not the same) to https://github.com/JuliaLang/julia/issues/12219

**Comment by StefanKarpinski** [comment]
> teach the inliner that a "global" has a fixed type once it has been substituted for a function argument.

That seems like the better way to go, no? Albeit possibly harder.

**Comment by vtjnash** [comment]
Replacing a local with a global during inlining is also a semantic bug (since it isn't affect-free), so we need to introduce a temporary in all cases where this can happen, top level scope or no.

**Comment by JeffBezanson** [comment]
This has been fixed. Probably by the new optimizer I assume.
