### ISSUE TITLE
1D array allocation is using jl_new_array

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#18922]
While looking at https://github.com/JuliaLang/julia/issues/18914 I noticed that `Array(Float64, 3)` (the allocation used by comprehension on master, but other constructors are the same) is calling `jl_new_array` which requires allocation of a tuple whereas it should be using `jl_alloc_array_1d`, as on 0.4 and 0.5.

**Comment by JeffBezanson** [comment]
#18917 :)
