### ISSUE TITLE
Macros with for loop arguments are parsed differently in comprehensions

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#18935]
These work:

``` julia
[for i = 1:10 end for i = 1:10]
@inbounds for i = 1:10 end
[@inbounds(for i = 1:10 end) for i = 1:10]
[@inbounds begin 
    for i = 1:10 end
end for i = 1:10]
```

These do not:

``` julia
[@inbounds for i = 1:10 end for i = 1:10]
[begin
   @inbounds for i = 1:10 end
end for i = 1:10]
```

**Comment by JeffBezanson** [comment]
The extra parens seem advisable there.

**Comment by simonster** [comment]
I agree that `[@inbounds for i = 1:10 end for i = 1:10]` is not so clear, but if it's inside a `begin`/`end` block inside a comprehension, it really seems like it should behave the same as if it were in a `begin`/`end` block outside of a comprehension.

**Comment by StefanKarpinski** [comment]
Related: https://github.com/JuliaLang/julia/issues/18650.
