### ISSUE TITLE
In POSIX sh, >& is undefined.

### ISSUE THREAD

**Issue by albap** [JuliaLang/julia#18951]
In POSIX sh, >& is undefined.
But many shell scripts on Julia uses it.
An alternative is needed.

**Comment by albap** [comment]
http://unix.stackexchange.com/a/80632

**Comment by yuyichao** [comment]
Yes it is.

**Comment by albap** [comment]
Was it introduced in POSIX later on? Couldn't find it.
Anyway now bash advises against it.
http://wiki.bash-hackers.org/scripting/obsolete

**Comment by yuyichao** [comment]
> Anyway now bash advises against it.

No it doesn't.

**Comment by albap** [comment]
I don't understand.
Look at this link http://wiki.bash-hackers.org/scripting/obsolete
It says &>FILE and >&FILE (especially >&)  is obsolete and >FILE 2>&1 is the replacement.

This redirection syntax is short for >FILE 2>&1 and originates in the C Shell. The latter form is especially uncommon and should never be used, and the explicit form using separate redirections is preferred over both. These shortcuts contribute to confusion about the copy descriptor because the syntax is unclear. They also introduce parsing ambiguity, and conflict with POSIX. Shells without this feature treat cmd1 &>file cmd2 as: "background cmd1 and then execute cmd2 with its stdout redirected to file", which is the correct interpretation of this expression.

**Comment by yuyichao** [comment]
Please read your own comment, understand shell and the use of it in julia more carefully. I do not find a single use of the advised against syntax in julia after other people insist on making them all sh compatible (which we really don't need anyway).

**Comment by albap** [comment]
I think people want to make shell scripts POSIX compliant so it works for everyone, not just bash users.

**Comment by yuyichao** [comment]
> so it works for everyone, not just bash users.

FWIW, many of these scripts are run only in environments where there's definitely bash available (e.g. the CI's). I'm not saying that we should use bash features whenever possible but we are happy to require it and use bash specific features if there's a case that's hard to implement in bash.

This is also totally unrelated to this issue and we are not using any bash extensions here.
