### ISSUE TITLE
Pushing to array of arrays

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#18958]
Is this expected behavior?

```julia
a = fill([], 3)
push!(a[1], 1)
a
```
>3-element Array{Array{Any,1},1}:
 Any[1]
 Any[1]
 Any[1]

My intention was to push to the first array only.

**Comment by andreasnoack** [comment]
Yes. See https://github.com/JuliaLang/julia/pull/8759#issuecomment-60127618.This question is probably better suited for julia users.
