### ISSUE TITLE
regression in float to int performance on master

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#18954]
```
function g(x)
               a = similar(x,Int)
               for i=1:length(x)
                 a[i] = x[i]
               end
              a
              end

x=Float64.(rand(1:1000000,2000,2000));
```

On 0.5.0:

```
julia> @time for i=1:20; g(x); end
  0.284237 seconds (40 allocations: 610.353 MB, 26.00% gc time)
```

on master:

```
julia> @time for i=1:20; g(x); end
  0.921421 seconds (40 allocations: 610.353 MB, 3.41% gc time)
```

The difference in generated code is that `convert` is no longer inlined, and it uses branches instead of eager `&`.

**Comment by simonbyrne** [comment]
Could be #14763 related, will look into it.

**Comment by vchuravy** [comment]
We should add a set of benchmarks for this.

**Comment by stevengj** [comment]
@vchuravy, just pushed a PR to BaseBenchmarks.

**Comment by KristofferC** [comment]
I'm getting:

### 0.6
```jl
julia> @btime g(x)
  11.714 ms (2 allocations: 30.52 MiB)
```

### 0.5
```jl
julia> @btime g(x)
  11.308 ms (2 allocations: 30.52 MiB)
```

So seems fixed?

**Comment by tkelman** [comment]
Do we know what fixed this? Am considering backporting the original change, but it causes a performance regression in conversion and whatever fixed it was not marked for backporting.
