### ISSUE TITLE
Is AsyncCondition leaking memory?

### ISSUE THREAD

**Issue by lilinjn** [JuliaLang/julia#18956]
Tracing through code, I can't find the `free` corresponding to this [`malloc`](https://github.com/JuliaLang/julia/blob/01e256310227b859651f4622d5c7c68b742ed25d/base/event.jl#L215)

This [line] (https://github.com/JuliaLang/julia/blob/master/base/event.jl#L236) in particular looks funny.   

Apologies if I'm missing something obvious, but if people concur this is a leak, I wouldn't mind taking a whack....  cheers, nehal

**Comment by yuyichao** [comment]
I believe it's done in `jl_uv_closeHandle`.
