### ISSUE TITLE
IO in threads corrupts heap even when protected

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#18962]
While experimenting with multithreading, it is helpful to have constructs like
```
lock(mylock)
println(message)
unlock(mylock)
```
in the thread functions, where `mylock` is a `Mutex` or `SpinLock`. Although this works most of the time, I find that programs which do a lot of allocation often segfault (in GC code) when such constructs are present.  Are such locks known to be insufficient to protect thread-unsafe code? If not, I can provide gists of code and tracebacks.

```
Julia Version 0.6.0-dev.787
Commit c71f205 (2016-09-26 16:28 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

Also seen in v0.5.0

**Comment by yuyichao** [comment]
In general locking is not enough to make IO thread safe.

**Comment by vtjnash** [comment]
Dup https://github.com/JuliaLang/julia/issues/15620. This is partly why threading support is still alpha/experimental

**Comment by RalphAS** [comment]
I'm trying to help you make it solid! Anyway, I think this may differ from #15620 because the crash is a
real segfault (i.e. invalid memory access) and often occurs after the thread loop has completed - hence the issue title.

[Here](https://gist.github.com/RalphAS/67aa34ba4783e7bc3852581689ee48e8) is example code and a valgrind log. Commenting out the print statement in the thread loop suppresses the problem (AFAICT).

**Comment by yuyichao** [comment]
Valgrind is pretty useless for this AFAICT. I don't think this is really a dup of #15620 but it's still dup of open thread safe issues.
