### ISSUE TITLE
Finalize fix for libgit2 SSL certificates

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#18963]
Putting this here to remind us to fix this, after discussion in https://github.com/libgit2/libgit2/pull/3935#issuecomment-253910017 settles on a reasonable modification to that pull request.  This will involve editing the [locally-carried patch](https://github.com/JuliaLang/julia/blob/master/deps/patches/libgit2-mbedtls.patch) to `libgit2`.

**Comment by StefanKarpinski** [comment]
This is essentially an upstream issue tracker, hopefully to be resolved by 0.6.

**Comment by tkelman** [comment]
Don't think there's anything we can do here where we have control over the timeline, all the patch changes we need should be in for bugs we've found. Bumping to 1.0 so we hopefully don't forget about getting it resolved properly upstream.

**Comment by StefanKarpinski** [comment]
Is this really release blocking? Seems like a bug fix.

**Comment by StefanKarpinski** [comment]
We also potentially want to move LibGit2 out of Base.

**Comment by staticfloat** [comment]
We've dropped that patch now, so I'm closing this.
