### ISSUE TITLE
cholfact and bkfact fail for non-<:StridedMatrix types

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#18972]
Similar to #18970, `cholfact` and `bkfact` fail for matrices that are not subtypes of `StridedMatrix`. Contrast with `qrfact`, which succeeds for many more matrix types. (The difference seems to be that [`qrfact` has a fallback that gracefully handles `<:AbstractArray`s more generally](https://github.com/JuliaLang/julia/blob/6c9f5afa89f451bf2262af6f2bdd87b7b7a328d4/base/linalg/qr.jl#L175). Fixing this may be as simple as adding such ~five-line fallbacks for `bkfact` and `cholfact`.) Best!

``` julia
julia> VERSION
v"0.6.0-dev.979"

julia> bkfact(SymTridiagonal(fill(2, 4), ones(3)))
ERROR: MethodError: no method matching bkfact(::SymTridiagonal{Float64})
Closest candidates are:
  bkfact(::Union{Hermitian{T,S},Symmetric{T,S}}) at linalg/symmetric.jl:183
  bkfact{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}) at linalg/bunchkaufman.jl:72
  bkfact{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64}}(::Union{Base.ReshapedArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2},SubArray{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},2,A<:Union{Base.ReshapedArray{T,N,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N}},L}}, ::Symbol) at linalg/bunchkaufman.jl:72
  ...
```

(Yes, `LDLt` would be better for [edit: positive- or quasi-definite] `SymTridiagonal`s.) (Edited to include `cholfact`.)

**Comment by tkelman** [comment]
> `LDLt` would be better for `SymTridiagonal`

Many indefinite cases won't necessarily admit a diagonal-D factorization, will they? Though I think once you need Bunch-Kaufman pivoting then you can't necessarily remain within a fixed number of subdiagonals unless you use the more recent banded retraction factorization, IIRC.

**Comment by Sacha0** [comment]
> Many indefinite cases won't necessarily admit a diagonal-D factorization, will they? Though I think once you need Bunch-Kaufman pivoting then you can't necessarily remain within a fixed number of subdiagonals unless you use the more recent banded retraction factorization, IIRC.

Good point --- I had only the positive- and quasi-definite cases in mind. Best!
