### ISSUE TITLE
Segfault in generate_func_sig

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#18986]
Following code makes 0.5 or higher segfault (on Linux, tested with LLVM 3.3 & 3.9) in `emit_ccall` → `generate_func_sig`:
```julia
dummy1() = return nothing

function main()
    cfunction(dummy1, Void, ())
    ccall((:dummy2,"nonexisting.so"), Void, ())
end

main()
```

Sometimes LLVM assertions are triggered instead of segfaulting, so it looks like there's corruption somewhere instead of a logic error. Trying an ASAN build, I'm getting `jl_value_t *jl_svecref(void *, size_t): Assertion 'jl_typeis(t,jl_simplevector_type)' failed` around [here](https://github.com/JuliaLang/julia/blob/1ea0de18a623d84423592e0dfc16896c426ddd9b/src/ccall.cpp#L1198) with `tt` being `<?#0x6110069b5750::Expr(:call, Core.tuple, :dummy2, "nonexisting.so")::Tuple{Symbol, String}>`. Not sure what's going on...

Works on 0.4, erroring out with `could not load library "nonexisting.so"`.
FWIW, bisected to e0bc056f20909634cdcce1ad0a548764a1cc9ea5 (by @vtjnash).

**Comment by yuyichao** [comment]
Looks similar to the issue @vtjnash had on another branch due to throwing in C++ frames?
