### ISSUE TITLE
Semicolon in generator: `(x; x for x in A)` becomes `(x; (x for x in A))`?

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#18988]
I don't even remember why I tried it, but...

``` julia
julia> :(x; x for x in A)
quote 
    x
    (x for x = A)
end
```

Which seems like a breach in the stated generator syntax, since this one doesn't start with a `(`.
Needs semicolons between two or more expressions but cannot have one right before the `for`*.
As occurring in `0.5.0` and `0.6.0-dev.994`.

---

*`:(x; for x in A)` gives the same error as #18650 .

**Comment by StefanKarpinski** [comment]
It's unclear to me that this is a bug. Wouldn't one write `:((x;x) for x in A)` to get a generator with body of `x;x`?

**Comment by fcard** [comment]
@StefanKarpinski I mean, I am not suggesting think this should be valid, imo it should throw a parser error. It's just that I think it's a fair expectation that the generator expression should start at the `(`, but here it starts at the second `x`. Don't you think that's weird? :P

**Comment by StefanKarpinski** [comment]
I don't really see the parens as part of the generator expression, otherwise to call `sum` on a generator, you'd need two sets of parens: `sum((x^2 for x = 1:10))` – one for the generator, one for the function call.

**Comment by fcard** [comment]
@StefanKarpinski Hmm, I can accept that, but now I also have to accept that parens aren't part of tuples either... My world, upside down!

I was going to say that it isn't consistent with `zip(x for x in 1:10, y for x in 1:10)`, but then there is `(x,x for x in 1:10)` which works like this. There is also #18731, but that's unresolved. `:(x,y; a,b)` makes some weird expression I've never seen before... ow, my head.

I am kinda 50:50 now, so I will just drop out and let you decide.

**Comment by StefanKarpinski** [comment]
I'm passing the buck on this to @JeffBezanson 😝

**Comment by JeffBezanson** [comment]
Since `;` is a statement separator I think it makes sense for it to have strictly lower precedence than basically everything else. Also given the role of `;` in argument lists it would be weird for `f(x; y for y in z)` to parse as `f((x;y) for y in z)`, and parens with no function call should be similar.

**Comment by fcard** [comment]
That last one is very convincing, and makes it clear to me that the current behavior is the correct one. Feel free to close then.

**Comment by JeffBezanson** [comment]
Thanks, @fcard .
