### ISSUE TITLE
Convert a BitArray to a Integer array in Julia

### ISSUE THREAD

**Issue by sujoydatta13** [JuliaLang/julia#18984]
I am a new user of Julia. Please help me to convert a nxm BitArray to an nxm IntegerArray.
What I want is to print 1 for 'true' and 0 for 'false'. I tried convert(), but did not succeed though the opposite is possible
Thank you in advance.

**Comment by nalimilan** [comment]
Please use the mailing list for questions, and keep GitHub for actual bug reports. Thanks! (Make sure to post code you tried and the errors you got if you want helpful replies).

**Comment by StefanKarpinski** [comment]
Please post questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.
