### ISSUE TITLE
Getting  (version 5.1.3 with __gmp_bits_per_limb == 64) on launching julia

### ISSUE THREAD

**Issue by bmandeepak** [JuliaLang/julia#18982]
ErrorException("The dynamically loaded GMP library (version 5.1.3 with __gmp_bits_per_limb == 64)

Ubuntu Version - 14.04

Followed the below steps -
sudo add-apt-repository ppa:staticfloat/juliareleases
sudo add-apt-repository ppa:staticfloat/julia-deps
sudo apt-get update
sudo apt-get install julia

Launch Julia

WARNING: Error during initialization of module GMP:
ErrorException("The dynamically loaded GMP library (version 5.1.3 with __gmp_bits_per_limb == 64)
does not correspond to the compile time version (version 6.1.0 with __gmp_bits_per_limb == 64).
Please rebuild Julia.")

Version 0.5.0 (2016-09-19 18:14 UTC)

**Comment by nalimilan** [comment]
Using the PPA is no longer recommended. Download the generic Linux binaries instead.

Cc: @staticfloat
