### ISSUE TITLE
julia-config.jl cflags incompatible with non-installed source builds

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#18993]
I have a package which needs to build against `libjulia`, but the cflags provided by `julia-config.jl` are incompatible with (what seems like a popular way of) running Julia from a built but not installed source tree.

For example, let's say we have sources checked out at `$REPO` and are building out-of-tree (doesn't matter though) at `$REPO/build`. The following flags are reported by `julia-config.jl`:

```
$ ./julia $REPO/contrib/julia-config.jl --cflags
-DJULIA_ENABLE_THREADING=1 -fPIC -DJULIA_INIT_DIR=\"$REPO/build/usr/lib\" -I$REPO/build/usr/include/julia
```

However, not having run `make install` the headers are scattered all over the place, and `$REPO/build/usr/include/julia` doesn't even exist yet. I'd need to include the following directories:

* `$REPO/src`: julia.h
* `$REPO/src/support`: ios.h etc
* `$REPO/build/src`: julia_version.h
* `$REPO/build/usr/include`: uv.h etc

Any suggestions here? Patching `julia-config.jl` is easy enough, but wouldn't look very nice (checking for existence of `$REPO/build/usr/include/julia`, maybe looking for a `Makefile`). Should we copy headers into `$REPO/build/usr/include/julia` during compilation already?

**Comment by tkelman** [comment]
we may want to restructure the source build to look more like an installed build.
