### ISSUE TITLE
segmentation fault : 11 unknown function

### ISSUE THREAD

**Issue by truefalsename** [JuliaLang/julia#18999]
Hi guys,

I made a julia wrapper for some C library and a simple script to make a scan using functions from this library. Everything works fine as long as I scan a restricted number of points (few thousands), but when I scan more points, say two order of magnitudes more, I get the following message

`signal (11): Segmentation fault: 11
while loading /Users/luca/Programming/Physics/micrOMEGAs scan/CoyDM/scan.jl, in expression starting on line 83
boost at /Applications/Physics/micromegas/sources/spectra.c:555
getSpectrum at /Applications/Physics/micromegas/sources/spectra.c:775
calcSpectrum0 at /Applications/Physics/micromegas/sources/spectra.c:985
calcSpectrum at /Applications/Physics/micromegas/sources/spectra.c:1104
sigmaV_ID at /Users/luca/Programming/Physics/micrOMEGAs scan/CoyDM/CoyDM.c:145
scan_out at /Users/luca/Programming/Physics/micrOMEGAs scan/CoyDM/scan.jl:62
#2 at ./<missing>:0
# writedlm#16 at ./datafmt.jl:678

unknown function (ip: 0x311f08ff9)
# writedlm#20 at ./datafmt.jl:703

unknown function (ip: 0x311f07e42)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
#1 at /Users/luca/Programming/Physics/micrOMEGAs scan/CoyDM/scan.jl:85

open at ./iostream.jl:113
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
do_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:66
eval at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:190
eval_body at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:465
jl_interpret_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:573
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:572
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20125 at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
process_options at ./client.jl:262
_start at ./client.jl:318
jlcall__start_21452 at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:189 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1942
true_main at /usr/local/bin/julia (unknown line)
main at /usr/local/bin/julia (unknown line)
Allocations: 1497222 (Pool: 1496353; Big: 869); GC: 0
zsh: segmentation fault  julia scan.jl
`

It could well be that I am doing something retarded as I am new to julia. In particular, my scanning script scan.jl contains this bit

`open(fname, "a") do f
    writedlm(f, scan_out(mdm, l_gdm, af, ma) 
        for mdm=mdm_min:mdm_step:mdm_max,
         l_gdm=l_gdm_min:l_gdm_step:l_gdm_max, 
         af=af_min:af_step:af_max,
         ma=ma_min:ma_step:ma_max)
end
` 
where scan_out is my function that calls the C-library wrapper.

What's going on? Thanks for your help!

**Comment by yuyichao** [comment]
Hard to tell without code. Very likely user error.

**Comment by truefalsename** [comment]
What bothers me is that the problem appear only be requiring a very large number of points, otherwise everything works fine. 
Can it be that writedlm() struggles with huge arrays?
As that was my suspicion, I am now running a version which uses nested for-cycles instead of  array comprehension to scan on the whole grid (replacing only the code pasted above). So far no errors regardless of the required number of points.

**Comment by yuyichao** [comment]
There are many reasons why an error only show up in some case and not others. In general the GC is very forgiving about user memory errors most of the time.

**Comment by KristofferC** [comment]
Please comment if this is still happening (and if possible give some runnable code that reproduces the problem).
