### ISSUE TITLE
Setting JULIA_HOME causes an error on start up

### ISSUE THREAD

**Issue by dwschulze** [JuliaLang/julia#18994]
If I set a JULIA_HOME variable in my .bashrc like this

```
export JULIA_HOME=/home/dschulze/bin/julia-1ea0de18a6
export PATH=$JULIA_HOME/bin:$PATH
```

julia crashes on startup with this message:

```
$ julia
ERROR: System image file "/home/dschulze/bin/julia-1ea0de18a6/../lib/julia/sys.so" not found.
```

If I modify my PATH in .bashrc like this it works:

`export PATH=/home/dschulze/bin/julia-1ea0de18a6/bin:$PATH`

If JULIA_HOME is a special environment variable that should not be used we need to know about this.

**Comment by JeffBezanson** [comment]
Yes, this environment variable is read on startup to (optionally) tell julia where it is installed.

**Comment by RalphAS** [comment]
JULIA_HOME is  the location of the executable, so you need to put "/bin" at the end.
This usage differs from certain other languages.

**Comment by fredrikekre** [comment]
Think this is better documented now?

```julia
help?> JULIA_HOME
search: JULIA_HOME

  JULIA_HOME

  A string containing the full path to the directory containing the julia executable.
```

And since #21480:

https://docs.julialang.org/en/latest/manual/environment-variables.html#JULIA_HOME-1

**Comment by KristofferC** [comment]
Yes, this looks good now.

**Comment by tkelman** [comment]
this behavior is arguably a bug that we should change
