### ISSUE TITLE
setfield! in same module failes

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#19006]
shouldn't this work?

```
julia> module Foo
           setfield!(Foo, :bar, 1)
       end
ERROR: cannot assign variables in other modules
```

**Comment by yuyichao** [comment]
Setfield is not allowed on modules.

**Comment by bjarthur** [comment]
using `setfield` in this way would be a convenient way to programmatically set global variables within the same module.  if this is not a desired feature, then at least the error message should be changed to be more accurate.

**Comment by JeffBezanson** [comment]
Yes, the error message should not say `other modules`. The idea is that `setfield!` should not depend on what module it is called from, since functions in general lack a notion of what module they are being used in.

**Comment by JeffBezanson** [comment]
Of course, an alternative is to allow `setfield!` to modify variables in any module at any time.

**Comment by StefanKarpinski** [comment]
`setfield!(M, :bar, 1)` is certainly better than `eval(M, :(bar = 1))` and still not likely to be done by accident (c.f. `M.bar = 1`).
