### ISSUE TITLE
Handle global references and remove localize_vars while serializing to other workers.

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#19000]
Copying @JeffBezanson 's comment from another issue - https://github.com/JuliaLang/julia/issues/15451#issuecomment-220389481

"I think the right solution is to look through the IR for the function when it's serialized, and send over all its dependencies. This could also potentially let us remove the localize_vars hack. We can also keep track of which items from Main we've sent to which processors and avoid re-sending, which would be a helpful optimization."

This will help in removing a major source of confusion in serialized closures which capture global variables vs local ones.

**Comment by amitmurthy** [comment]
> We can also keep track of which items from Main we've sent to which processors and avoid re-sending

Some thoughts/questions:
- Doing this should do away with the need for `@everywhere` for function definitions, since they will be automatically sent from the master.
- Limit the automatic sending to calls from the master only? Worker-worker calls will assume that the definitions have been defined on the target process?
- Should modules also be automatically loaded on the target worker if referenced during a deserialization? This would require deserialization to read the complete current message (possible as we now have a message boundary), pause the deserialization, load the missing module over the same stream and then continue the deserialization from the temporary buffer. Will do away with the need for `@everywhere using` - required modules are loaded on demand.

**Comment by bdeonovic** [comment]
Is there a time frame on this fix?

**Comment by amitmurthy** [comment]
Closed by #19594
