### ISSUE TITLE
How about a JuliaGraphics/ColorMaps.jl package?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#19004]
There seem to be a few colormap packages and related functionality floating around:

- PlotUtils.jl (part of @tbreloff 's Plots.jl)
- PyPlot.jl 
- Colorbrewer.jl
- NoveltyColors.jl (@randyzwitch)
- Colors.jl (part)
- ColorSchemes.jl 
- ColorMaps.jl (@lobingera)

Perhaps some kind of common format and interface, or some interoperability, would be handy?

I think [this](https://github.com/JuliaGraphics) is the organization for JuliaGraphics, though it's not listed [here](http://julialang.org/community/). 

(I don't know where else to put this issue...)

**Comment by randyzwitch** [comment]
In the case of ColorBrewer.jl (not mine) and NoveltyColors (mine), the packages are just trivial data loading packages made up of `Dicts` of string literals. That's all I need for Vega and ECharts, so the tradeoff is importing a heavier package such as ColorSchemes.jl vs packages with no other dependencies (vs. the dependencies might already be installed, so no practical "weight" added)

**Comment by yuyichao** [comment]
Please discuss this on the mailing list.

**Comment by lobingera** [comment]
@cormullion @randyzwitch, the previous discussion was in https://github.com/JuliaGraphics/Colors.jl/issues/246 and if needed we can discuss in https://github.com/lobingera/ColorMaps.jl (open an issue with API ideas?)
