### ISSUE TITLE
Allow `Pkg.test` to work on non installed packages in `LOAD_PATH`

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#19026]
I have a package like repository `path_to_A/A.jl`

`push!(LOAD_PATH, "path_to_A")` would make `A` available for `using`

However, `Pkg.test("A")` to run the test doesn't work.

Currently I have to do:

```
# Change pwd to the correct folder.
cd("path_to_A/A.jl/test")
include("runtests.jl")
```

**Comment by tkelman** [comment]
this is a subset of https://github.com/JuliaLang/julia/issues/8679
