### ISSUE TITLE
Performance regression in array comprehension between v0.4.7 and v0.5.0

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#19021]
On v0.4.7 the following code
```jl
tmp = [ones(100) for i = 1:100]
@time [tmp[i] for i = 1:length(tmp)]
```
runs very fast and has 302 allocations. However, on v0.5 it is much slower, and does around 22k allocations at a severe performance hit. On v0.5 the result is a vector of vectors of floats, and on v0.4.7 it is a vector of vectors of any. However, in something like
```julia
tmp = [ones(100) for i = 1:100]
@time sum([tmp[i] for i = 1:length(tmp)]);
```
I can get the correct (Vector{Float64}) answer about 600 times faster on v0.4.7 compared to v0.5 or master.

**Comment by KristofferC** [comment]
Don't benchmark in global scope?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/8870

**Comment by pkofod** [comment]
Yes, I know, don't time in global scope. Indeed timings are identical in a function call. Though, I am curious as to why this was faster before. I will direct my further questions to Julia-users.
