### ISSUE TITLE
\rightarrow for ->

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#19025]
I wonder if there is a plan to let Julia interpret `→` (inputted by `\rightarrow`) as `->`, like it interprets `≥` as `>=` and `∈` as `in`.  I was not able to find an issue created for this topic.

**Comment by JeffBezanson** [comment]
Related: #11223

**Comment by wsshin** [comment]
Thanks!  Couldn't find that issue.  I think `\mapsto` as suggested in #11223 is a better candidate than `\rightarrow`, if any Unicode would be ever assigned to `->`.
