### ISSUE TITLE
non-ideal type graph for `Dates.Period` and `Dates.CompoundPeriod`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#19023]
Right now if I ever have a reason to use these types I typically do

``` julia
typealias Duration Union{Dates.Period, Dates.CompoundPeriod}
```

This is because all of the concrete types down-graph of `Period`, as well as `CompoundPeriod` represent intervals in time.

I think there should be a single abstract type from which all periods inherit, but from which no "instants" inherit.  So for instance

``` julia
abstract Period <: AbstractTime
abstract TimePeriod <: Period
abstract DatePeriod <: Period

type CompoundPeriod <: Period
    ...
end
```

with all the concrete types (`Day`, `Hour`, et cetera) inheriting from `TimePeriod` and `DatePeriod` as they currently do.  (Currently `CompoundPeriod <: AbstractTime`).  I think I see the computational reason why things are currently the way they are, but conceptually it really makes no sense.

Also, it's possible I'm just not seeing them, but there seem to be no accessor functions for `Period` types, and it is currently no fun to have to, for instance, count the number of days in `Dates.Month(n1) + Dates.Week(n2) + Dates.Day(n3) + Dates.Hour(n4)`.

**Comment by quinnj** [comment]
Makes sense to me.

Can you expound on the "no accessor functions for Period types"? What exactly would you be looking for there?

**Comment by ExpandingMan** [comment]
For example,
```julia
using Base.Dates
hour(Day(1) + Hour(1) + Minute(1))
>>> 25 + 1//60
```
Granted, when you get to time periods longer than a week it starts to become ambiguous because months and years aren't even fixed periods (my god have we inherited a ridiculous system for measuring time), so I'm not sure what the best solution is.  If I were going to do it right now I'd just define a month to be 30 days and a year to be 365 + 1/4 days and leave it to the user to have to deal with that (of course accessor functions for `AbstractTime` subtypes where this ambiguity doesn't exist would behave normally).

**Comment by quinnj** [comment]
I think just doing
```julia
const Duration = Union{Dates.Period, Dates.CompoundPeriod}
```
seems best for this. Given the staleness of the issue, I'll close for now, but it can certainly still be discussed if there's more interest.

**Comment by ExpandingMan** [comment]
I ran afoul of this again today.  I still think it would be nice to change this, or, at the very least, to define `Duration` as @quinnj suggested above and export it from `Dates`.  Thoughts?

If everyone agrees but nobody wants to do it, I can, but I'm not sure when I'll get to it.
