### ISSUE TITLE
jlcall_api 2 breaks precompile

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#19030]
the inferred constant return value is potentially creating copies of values in the precompiled code. proposed fix from Jeff and myself is to limit jlcall_api 2 to only do isbits objects and Types.

**Comment by timholy** [comment]
x-ref a possible demo in #25279 that could potentially be copy/pasted into `test/compile.jl`.

**Comment by JeffBezanson** [comment]
Interesting --- how is this causing the issue in #25279?
