### ISSUE TITLE
Proposal: Initialize an immutable from `ccall`

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#19037]
It is currently possible to initialize, e.g., an `isbits` immutable from a `ccall` if it is the return value of that function.

On the other hand, it is quite common in C/C++ to allocate the memory in the caller and to pass a pointer to the callee which then populates that memory. As an example, in `C` I can create a stack-allocated (statically sized) array and call a BLAS function to populate it. 

Meanwhile, in Julia there are no mutable, stack allocated objects, and thus I cannot pass a pointer to my stack frame using `ccall` and `&` when the C function might mutate that memory (it would violate immutability). Yet for *StaticArrays.jl* (and I'm sure there are other contexts) I would love to be able to take advantage of libraries like BLAS and LAPACK without adding unnecessary heap allocations (and garbage collection). Performance wise, this makes sense for moderately sized matrices, for example.

My proposal is to allow a `ccall` to initialize a new immutable. It would be an atomic operation that both allocates memory (on the stack for `isbits` types) and passes that pointer to a C-function. After the `ccall` terminates, Julia will interpret that value as immutable as usual.

I'm not yet sure of a syntax that makes the atomic nature of that operation clear. One idea might be:

```julia
function f()
    local x::Int
    ccall(:my_c_func, Void, (Ptr{Int},), &x)
    ... # use x as an immutable
end
```
Here the compiler would be able to tell that `x` is a declared variable but not initialized, and makes the assumption that the `ccall` performs the initialization after Julia allocates the memory (on the stack, for `isbits` types, or on the heap otherwise).

I feel this addition would improve Julia's FFI by making it more compatible and performant with common idioms in C and other languages.

(A similar idea might apply to `llvmcall`, I'm not sure...)

**Comment by andyferris** [comment]
Alternative syntax using the `new` keyword inside `ccall`:
```julia
function f()
    ccall(:my_c_func, Void, (Ptr{Int},), new &x)
    ... # use x as an immutable
end
```

**Comment by yuyichao** [comment]
This is already possible using `Ref{Int}` and should work better with allocation elimination.

**Comment by andyferris** [comment]
Oh, right! That is yet another nice consequence of allocation elimination. Thanks @yuyichao 

(btw do you know if this is a likely feature for 0.6?)
