### ISSUE TITLE
Type stability of array concatenations 

### ISSUE THREAD

**Issue by cdsousa** [JuliaLang/julia#19038]
Both

```
@code_warntype [[1.0, 2.0]; 3.0]
```

and

```
@code_warntype vcat([1.0, 2.0], 3.0)
```

give `Any` as final inferred type.

Is this expected? Or must this be an issue? I couldn't find any previous issue on this...

**Comment by GunnarFarneback** [comment]
Differs by a transposition from #13665.

**Comment by KristofferC** [comment]
Looking at it:

```jl
julia> @code_warntype [[1.0,2.0]; 3.0]
Variables:
  #self#::Base.#vcat
  X::Tuple{Array{Float64,1},Float64}
  T::Type{T}
  #80::Base.##80#81

Body:
  begin 
      SSAValue(4) = (Core.getfield)(X::Tuple{Array{Float64,1},Float64},1)::Array{Float64,1}
      SSAValue(5) = (Core.getfield)(X::Tuple{Array{Float64,1},Float64},2)::Float64
      # meta: location abstractarray.jl cat 1056
      SSAValue(1) = Base.promote_type
      #80::Base.##80#81 = $(Expr(:new, :(Base.##80#81)))
      SSAValue(2) = #80::Base.##80#81
      T::Type{T} = (SSAValue(1))($(QuoteNode(Float64)),$(QuoteNode(Float64)))::Type{T}
      # meta: pop location
      return (Base.cat_t)(1,T::Type{T},SSAValue(4),SSAValue(5))::Any
  end::Any
```

Isn't the type stability in `T::Type{T} = (SSAValue(1))($(QuoteNode(Float64)),$(QuoteNode(Float64)))::Type{T}` weird? With `SSAValue(1) = Base.promote_type` being pure and both the arguments known, shouldn't the compiler be able to figure out `T` here?

**Comment by cdsousa** [comment]
Thanks, "inference" and "concatenation" should have been the words for issue search...

**Comment by stevengj** [comment]
`promote_type(map(x->isa(x,AbstractArray) ? eltype(x) : typeof(x), X)...)` in `function cat(catdims, X...)` probably defeats compile-time inference.  

Probably it should use `promote_eltype(X...)`?

**Comment by stevengj** [comment]
Also, the `function cat_t(catdims, typeC::Type, X...)` function signature should probably be `function cat_t{typeC}(catdims,::Type{typeC}, X...)` if we want `typeC` to be known at compile time.

**Comment by stevengj** [comment]
Argh, the `cat_t` function is horrible; it needs major surgery to be type stable.

**Comment by pabloferz** [comment]
I had a patch for the type promotion part. But decided not to do anything about it precisely because of `cat_t`. The main problem is making the dimension of the final array type stable. An option is to use a similar mechanism to `broadcast_indices` and `broadcast_shape` for `cat`. Still, I suspect that would require using a `Val{N}` for the `catdims`.
