### ISSUE TITLE
setindex with tuple argument

### ISSUE THREAD

**Issue by cortner** [JuliaLang/julia#19047]
```julia
x = rand(3)
x[(1,2)]             # ok, returns the relevant part of x
x[(1,2)] = 1.0    # error message 
```
LoadError: Dimension mismatch
in macro expansion at /Users/ortner/.julia/v0.5/StaticArrays/src/indexing.jl:99 [inlined]
 in setindex!(::Array{Float64,1}, ::Float64, ::Tuple{Int64,Int64}) at /Users/ortner/.julia/v0.5/StaticArrays/src/indexing.jl:85

I am assuming this is not intended behaviour?

**Comment by yuyichao** [comment]
Seems to be a package issue.

**Comment by StefanKarpinski** [comment]
To elaborate: StaticArrays seems to be defining some methods that cause this to fail.

**Comment by yuyichao** [comment]
Rather it's probably defining sth that makes the first one works when it shouldn't.

**Comment by cortner** [comment]
Thank you for clarifying.
