### ISSUE TITLE
Inconsistent namespacing when `using` modules in Main vs other modules

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#19048]
This might be intentional, I'm not sure (please close if so):

```julia
julia> using BaseBenchmarks # BaseBenchmarks loads BenchmarkTools via `using`

julia> BenchmarkTools # BenchmarkTools is available in Main
BenchmarkTools

julia> module A 
           using BaseBenchmarks
           println(BenchmarkTools)
       end
ERROR: UndefVarError: BenchmarkTools not defined
```

Alternatively, with a fresh REPL:

```julia
julia> module A
           using BaseBenchmarks
       end
A

julia> BaseBenchmarks
BaseBenchmarks
```

I would expect an `UnderVarError` to be thrown in all cases. I guess the required packages' modules are all getting loaded into Main when the package is loaded, which is why they're all visible?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/17997
