### ISSUE TITLE
Fix LLVM 3.8+ build

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#19051]
While working on https://github.com/staticfloat/julia-buildbot/issues/58 I noticed that there are multiple issues related to how we build LLVM 3.8+/on arm. Some of these already have PR's but it's scattered everywhere so here's a list since I'm starting to loose track of them... (I know umbrella issue can be bad but hopefully this is a short list that does not get longer....)

* [x] autotool build system for 3.8 seems buggy. (Missing include path on ARM) we should switch on CMake on 3.8+ (Fixed by #19054)
* [x] CMake shared build links the libLLVM to libLTO which we don't install, we need to set `-DLLVM_LINK_LLVM_DYLIB=ON` to fix it. (Fixed by #19054)
* [x] We need a way to turn on LTO for ARM. (Fixed by https://github.com/JuliaLang/julia/pull/19028)
* [x] We are not passing `CFLAGS`/`CXXFLAGS`/`LDFLAGS` to LLVM with cmake build. (Fixed by https://github.com/JuliaLang/julia/pull/19069)
* [x] We should not hard code LLVM version on arm and power. (Fixed by https://github.com/JuliaLang/julia/pull/19060)

**Comment by vchuravy** [comment]
I am working on a proper patch to the LLVM build-system for the second issue.

**Comment by yuyichao** [comment]
All fixed.
