### ISSUE TITLE
Incorrect parsing error message with four dots (....)

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#19072]
It would be nice if the error could mention the four dots.

``` julia
julia> function f(x...)
           vcat(x....)
       end
ERROR: syntax: missing comma or ) in argument list

```

**Comment by ararslan** [comment]
I don't know that the current message is actually *incorrect*, it's just not intuitive. Also note that the same message occurs for any number of dots > 3. What would you suggest instead?

**Comment by nalimilan** [comment]
A sequence of more than three consecutive dots is invalid AFAICT, so I'd rather get a message about that. How is the current message correct? Where could I add a parenthesis or a comma to make the syntax correct?

**Comment by ararslan** [comment]
Well, I guess I wouldn't really call it correct either, it's more just that you're giving it something it doesn't understand in the argument list, so it thinks the list should either have ended (`)`) or continued (`,`). I agree that a better message would be nice.

**Comment by jdlangs** [comment]
Probably it would be sufficient in such cases just to have the parser say "I was expecting A, B, or C, but I saw X."

Would something like that qualify as an intro issue?

**Comment by laborg** [comment]
On master with JuliaSyntax.jl the error message is clear enough:
```julia
julia> function f(x...)
           vcat(x....)
       end
ERROR: ParseError:
# Error @ REPL[27]:2:14
function f(x...)
    vcat(x....)
#            ╙ ── Expected `)`
Stacktrace:
 [1] top-level scope
   @ none:1
```
