### ISSUE TITLE
syntax confusion: `1.+2`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19089]
This sort of confusion keeps cropping up: https://groups.google.com/forum/#!topic/julia-users/aycsd2iAktE. Two possibilities seem possible:
- Eliminate `1.` as a short syntax for `1.0`;
- Allow `1.` but make ambiguous cases like `1.+2` a syntax error.

Related: https://github.com/JuliaLang/julia/issues/18714 – in that it also relates to making potentially ambiguous cases errors.

**Comment by ararslan** [comment]
+1 for eliminating `1.`. That change might be mildly annoying for some people, but it's much clearer to write floating point literals as `1.0` anyway.

The second point, allowing `1.` but making `1.+2` a syntax error, seems like more trouble than it's worth.

**Comment by tknopp** [comment]
given that `.` is extensively used in Julia I would also vote for eliminating `1.`
Making it a syntax error adds new special cases to the parser, which increases the complexity of a (potential) Julia grammar.

**Comment by JeffBezanson** [comment]
Disallowing `1.` seems too strict to me. *Many* languages allow that syntax, and getting rid of it because of a corner case seems like throwing out the baby with the bathwater. The problems with `1.+2` (either as it is now, or if we add a special case error for it) are much rarer and less significant than the use of `1.` as a literal.

**Comment by carlobaldassi** [comment]
I agree with Jeff even though I personally dislike `1.`, as I'm sure *a lot* of people would be very annoyed by not being able to write it/having to change their code. Simply disallowing ambiguous cases should be enough I believe.

**Comment by StefanKarpinski** [comment]
At this point everyone seems to agree that `1.+2` should be a warning, so let's agree to that. For what it's worth, Ruby doesn't seem to allow `1.` as a syntax – probably because the language allows calling methods on integers. C, C++, Python and Perl allow `1.`.  I'm not sure what R does since I don't have it installed.

**Comment by JeffBezanson** [comment]
R accepts it, as do octave/matlab. The syntax is nearly universal.

**Comment by mauro3** [comment]
Whilst we're at it, are there any problems with omitting the leading zero: `.1` which should be taken care of too?

**Comment by StefanKarpinski** [comment]
There seem to be a lot fewer issues with that syntax.

**Comment by StefanKarpinski** [comment]
For 0.6 this should be made a deprecation warning or an error, but this change is pretty minor and low impact, so I'm leaving this as up for grabs in case someone wants to do it.

**Comment by akaysh** [comment]
Hi @StefanKarpinski ,
I am a beginner, can I work on this issue?
Please help me how to get started.
Thanks

**Comment by StefanKarpinski** [comment]
@akaysh: anyone who wants to can work on it (no need to ask permission), but I suspect this is not a particularly easy issue. It requires some deep hacking on Julia's parser, which is written in Scheme. But if you think that sounds doable, you're welcome to give it a shot.

**Comment by Sacha0** [comment]
> are there any problems with omitting the leading zero: `.1` should be taken care of too?

> There seem to be a lot fewer issues with that syntax.

(Perhaps due to dot-ops presently have the dot on the left rather than right?)
