### ISSUE TITLE
improve error message for plan_ifft!(v::Vector{T<:Real})

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#19087]
This confused me for a second:

``` julia
julia> plan_ifft!(rand(10))
ERROR: MethodError: `plan_bfft!` has no method matching plan_bfft!(::Array{Float64,1}, ::UnitRange{Int64})
Closest candidates are:
  plan_bfft!(::Any, ::Any, ::Any)
  plan_bfft!(::Any, ::Any, ::Any, ::Any)
  plan_bfft!{T<:Union{Complex{Float32},Complex{Float64}},N}(::Union{DenseArray{T<:Union{Complex{Float32},Complex{Float64}},N},SubArray{T<:Union{Complex{Float32},Complex{Float64}},N,A<:DenseArray{T,N},I<:Tuple{Vararg{Union{Colon,Int64,Range{Int64}}}},LD}}, ::Any)
  ...
 in plan_ifft! at dft.jl:277
 in plan_ifft! at dft.jl:38
```

I think `plan_ifft!(v::Vector{T<:Real})` should be overriden to give an error message saying that the input has to be complex.

**Comment by akaysh** [comment]
@dlfivefifty I am trying to find some intro issues to work on. Can you help me start with this issue? (I am new to Julia)  Thanks.

**Comment by KristofferC** [comment]
What have you tried so far?

**Comment by akaysh** [comment]
@KristofferC I have read a bit on how to handle errors in Julia. I think I can use Gallium to find out the function call sequence and the override it to throw error (with the required message) when argument is not complex. Am I on the right track?

**Comment by KristofferC** [comment]
You don't need to use Gallium here since there is no need to know the call sequence (or stacktrace). The suggestion of the original poster is to just add a new method for `plan_ifft!` that gives a descriptive error message.

**Comment by akaysh** [comment]
@KristofferC I need a little help in figuring out how and where to override the method `plan_ifft!`. In the base file `dft.jl` the function call involves `eval` of `Symbol` like this:
`for f in (:fft, :bfft, :ifft, :fft!, :bfft!, :ifft!, :rfft)
    pf = Symbol("plan_", f)
    @eval begin
        $f(x::AbstractArray) = (y = to1(x); $pf(y) * y)
        $f(x::AbstractArray, region) = (y = to1(x); $pf(y, region) * y)
        $pf(x::AbstractArray; kws...) = (y = to1(x); $pf(y, 1:ndims(y); kws...))
    end
end` 
I am unable to identify the difference when the same function (`plan_ifft`) is called normally vs in-place (The issue occurs for the in place case while the normal one works fine). I am not yet familiar with the code base so a little hint or help would be enough for me to proceed with this.
Thanks

**Comment by lbollar** [comment]
Is the correct error to throw here an ArgumentError and like this?

```julia
plan_ifft!{T<:Real}(v::Vector{T}) = ArgumentError("plan_ifft! requires complex input.")
```

**Comment by fredrikekre** [comment]
See https://github.com/JuliaMath/FFTW.jl/issues/38
