### ISSUE TITLE
Gitter Mods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#19091]
[With the newest changes to the Gitter Moderation tools](https://gitter.im/gitterHQ/topics/topic/5809efc7b17b667961e0b359/moderation-tools), Gitter now allows for moderators/administrators for the Gitter channel who are not part of the Github organization. I was wondering if at least one of the "core Gitterers", either myself, @TotalVerb, @oxinabox, or @Ismael-VC, could have moderation privileges so that way there are active mods for the channel. While this hasn't been an issue yet (I have had to kick the same few who spam the linked IRC channel), this will help the Gitter community grow more comfortably as Julia grows.

**Comment by yuyichao** [comment]
I believe this should go to the mailing list since there's nothing we need to do here.

**Comment by ChrisRackauckas** [comment]
Got it.
