### ISSUE TITLE
Error from `eigvecs` on Hermitian matrix

### ISSUE THREAD

**Issue by Vectornaut** [JuliaLang/julia#19093]
Calling `eigvecs(Hermitian([1 1; 1 1]))` leads to the error

```
ERROR: MethodError: no method matching eigfact(::Hermitian{Int64,Array{Int64,2}}; permute=true, scale=true)
Closest candidates are:
  eigfact{T1<:Real,T2}(::Union{Hermitian{Complex{T1<:Real},T2},Hermitian{T1<:Real,T2},Symmetric{T1<:Real,T2}}) at linalg/symmetric.jl:198 got unsupported keyword arguments "permute", "scale"
  eigfact{T1<:Real,T2}(::Union{Hermitian{Complex{T1<:Real},T2},Hermitian{T1<:Real,T2},Symmetric{T1<:Real,T2}}, ::UnitRange{T<:Real}) at linalg/symmetric.jl:202 got unsupported keyword arguments "permute", "scale"
  eigfact{TA,TB}(::AbstractArray{TA,2}, ::AbstractArray{TB,2}) at linalg/eigen.jl:273 got unsupported keyword arguments "permute", "scale"
  ...
 in eigvecs(::Hermitian{Int64,Array{Int64,2}}) at ./linalg/eigen.jl:122
```

Changing the matrix entries to `Float64` leads to an analogous error. The calls
- `eigvecs([1 1; 1 1])`
- `eig(Hermitian([1 1; 1 1]))`
- `eigvals(Hermitian([1 1; 1 1]))`

all behave normally.

My `versioninfo()` is

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by xanfus** [comment]
Doesn't the log mean, new method for eigenfact() has to be implemented?

**Comment by andreasnoack** [comment]
No. Scaling and permuting are not necessary in the Hermitian case. We'll either have to implement `eigvecs(::Hermitian)` or simply remove `eigvecs`. The latter solution might be preferred since you don't save anything by only returning the vectors from the calculation.

**Comment by Vectornaut** [comment]
For what it's worth:

- I like `eigvecs` because it makes my code slightly more readable, by avoiding a mysterious indexing.
- Though it's presumably unrelated to the `scale` and `permute` options, I'd like to put in a good word for the fact that `eigvecs(::Hermitian)` used to call `sygvd`, which orders the eigenvalues by size. I know I have no right to expect that to keep working, since it was never documented, but I would be happy to see it appear as an official feature.

**Comment by xanfus** [comment]
Hermitian suits the candidates, but keyword arguments are not listed in candidates (have they to?).

**Comment by andreasnoack** [comment]
@xanfus I'm not sure I understand.

**Comment by xanfus** [comment]
@andreasnoack I mean, "permute" and "scale" are supplied to "eigfact", but there is no mention for them in method description.

**Comment by JeffBezanson** [comment]
The example in the OP works now. Please reopen if I'm missing something.
