### ISSUE TITLE
float(::Type) and real(::Type) are not documented

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#19113]
`float(Int) == Float64` and `real(Complex{Int}) == Int`.   This has worked since Julia 0.4, but doesn't seem to be documented.

**Comment by oxinabox** [comment]
Related: https://github.com/JuliaLang/julia/issues/18596
Not the same, but related;
since the current docs for `float`  are already  wrong/unclear on what they do cover.

**Comment by ararslan** [comment]
`complex` works similarly with similarly undocumented behavior:
```julia
julia> complex(Int)
Complex{Int64}
```

**Comment by H-225** [comment]
Fixed by #19166.
