### ISSUE TITLE
sparse binary broadcast incorrect for non-(zero-preserving) functions

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#19110]
The definitions [here](https://github.com/JuliaLang/julia/blob/b7634bec45dc6ca7b4317fc862cf632c0bcea27f/base/sparse/sparsematrix.jl#L1748-L1749) and [here](https://github.com/JuliaLang/julia/blob/b7634bec45dc6ca7b4317fc862cf632c0bcea27f/base/sparse/sparsematrix.jl#L1729) cause

``` julia
julia> VERSION
v"0.6.0-dev.1092"

julia> broadcast((x,y) -> sin(x) + cos(y), speye(5), speye(5))
5×5 sparse matrix with 5 Float64 nonzero entries:
    [1, 1]  =  1.38177
    [2, 2]  =  1.38177
    [3, 3]  =  1.38177
    [4, 4]  =  1.38177
    [5, 5]  =  1.38177

julia> broadcast((x,y) -> sin(x) + cos(y), Array(speye(5)), Array(speye(5)))
5×5 Array{Float64,2}:
 1.38177  1.0      1.0      1.0      1.0
 1.0      1.38177  1.0      1.0      1.0
 1.0      1.0      1.38177  1.0      1.0
 1.0      1.0      1.0      1.38177  1.0
 1.0      1.0      1.0      1.0      1.38177
```

Best!

**Comment by stevengj** [comment]
Ouch.  Yet another reason that all the sparse broadcast methods should be replaced with a unified approach that (a) assumes purity, (b) checks `f(0...)`, and (c) always returns a `SparseMatrixCSC` even if the output is dense, as we've discussed in #18590.

**Comment by Sacha0** [comment]
> Ouch. Yet another reason that all the sparse broadcast methods should be replaced with a unified approach that (a) assumes purity, (b) checks f(0...), and (c) always returns a SparseMatrixCSC even if the output is dense, as we've discussed in #18590.

Agreed. Discovered this bug while experimenting with an implementation; look for more from me shortly :). Best!

**Comment by Sacha0** [comment]
#19371 provided a partial fix. #19518 should close this altogether. Best!

**Comment by pabloferz** [comment]
I believe this one is already fixed. Right?

**Comment by Sacha0** [comment]
> I believe this one is already fixed. Right?

Yes, happily fixed :).
