### ISSUE TITLE
Inaccurate roots of a quadratic polynomial

### ISSUE THREAD

**Issue by tobydriscoll** [JuliaLang/julia#19128]
This is for a the Polynomials package, actually, but my report there has fallen on deaf or nonexistent ears:

https://github.com/Keno/Polynomials.jl/issues/70

It's a serious bug, in my opinion, as the error is too large by 9 orders of magnitude. Since Polynomials seems to be more or less the recommended package to deal with polynomials, I thought it was worth bringing to the core community.

**Comment by yuyichao** [comment]
It's on to ping the issue or ask on the mailing list but not report to the base repo.
