### ISSUE TITLE
sparse matrix  saved  in JLD format in 0.5 cant read in 4.5 

### ISSUE THREAD

**Issue by programistawpf** [JuliaLang/julia#19127]
sparse matrix  saved  in JLD format in 0.5 cant read in 4.5 

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using HDF5, JLD

julia> Fut=load("Fut.jld","Fut")
WARNING: type Base.SparseArrays.SparseMatrixCSC{Core.Int64,Core.Int64} not present in workspace; reconstructing
JLD.##Base.SparseArrays.SparseMatrixCSC{Core.Int64,Core.Int64}#7410(5240481,10,[1,269897,1814476,2025950,2309940,2849207
,3126588,3784531,4055609,4684957,5306980],[1,73,110,132,141,146,159,196,221,269    5240443,5240449,5240450,5240453,52404
56,5240457,5240463,5240464,5240473,5240474],[1,1,1,1,1,1,1,1,1,1    1,1,1,1,1,1,1,1,1,1])

Was saved in :
 Version 0.5.0 (2016-09-19 18:14 UTC)
 Official http://julialang.org/ release
 x86_64-w64-mingw32

by 
save("D.jld", "D", D)

Paul

**Comment by simonster** [comment]
Please report at https://github.com/JuliaIO/JLD.jl
