### ISSUE TITLE
Possible mistake in dispatch

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#19124]
I seem to be having problems where multiple dispatch is not choosing the function I expected it to.

The problem relates to two (in my opinion) non-ambiguous methods of `A_mul_B!`. It seems that the definition [here in Base](https://github.com/JuliaLang/julia/blob/master/base/linalg/matmul.jl#L87) is taking precedence over a more specific one I'm trying to implement [here in StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/matrix_multiply.jl#L503). 

In my case, the second input type is more specific than the function in Base, and the other parts of the type signature and the one type parameter are identical. Thus it should be deducible that my function is more unambiguously more specific. The function definitions are:

``` julia
A_mul_B!{T<:BlasFloat}(y::StridedVector{T}, A::StridedVecOrMat{T}, x::StridedVector{T})

@generated Base.A_mul_B!{T<:Base.LinAlg.BlasFloat}(c::StridedVector{T}, A::StaticMatrix{T}, b::StridedVector{T})
```

In no case I have found can I call the later function. However, if I tighten the type parameter `T` in any way, say to `T <: Union{Float64, Float32, Complex{Float64}}`, then suddenly multiple dispatch decides my function takes precedence. Further tightening of the second input type (even to a concrete type like `SMatrix{3,3,Float64,9}`, say) only results in no change or else an ambiguity between the two functions, which doesn't make any sense to me either.

I'm raising this issue because `A_mul_B!` is overloaded with nearly 100 quite complicated methods, so it's possible we're exploring corner cases of dispatch that haven't been exposed before. The issue seems somewhat related to mistakingly using the type parameter `T` to decide on specificity before the signature of the second input is analyzed properly, in the case where `T` is specified is being equally specific in the two methods.

**Comment by KristofferC** [comment]
How is this now with the new type system merged?

**Comment by andyferris** [comment]
Hmm... I would speculate that it would be improved given the other changes I'm aware of, but I had better double-check.

**Comment by fredrikekre** [comment]
Is this still a problem?

**Comment by nalimilan** [comment]
Bump.

**Comment by vtjnash** [comment]
closing as it wasn't reproduced with the new type system
