### ISSUE TITLE
on Raspberry Pi (arm), cannot find -lLLVM

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#19121]
On master branch at 2c5a2ed.  My previous successful build was at dee3c54.
```
raspberrypi% make
    LINK usr/lib/libjulia.so.0.6.0
/usr/bin/ld: cannot find -lLLVM
collect2: error: ld returned 1 exit status
Makefile:270: recipe for target '/home/sachs/src/julia-master/usr/lib/libjulia.so.0.6.0' failed
make[1]: *** [/home/sachs/src/julia-master/usr/lib/libjulia.so.0.6.0] Error 1
Makefile:90: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```

**Comment by josefsachsconning** [comment]
Hmm, if I checkout dee3c54, I get the same problem there, so I'm not sure what I'm doing wrong.

**Comment by yuyichao** [comment]
Can you run make with `VERBOSE=1` and check what do you have in `usr/lib` and `usr/lib/julia`?

**Comment by josefsachsconning** [comment]
I re-cloned and the build succeeded.  I guess something got screwed up in my working copy.  Is this worth pursuing?

**Comment by ViralBShah** [comment]
I think it is best to close it and reopen if necessary.
