### ISSUE TITLE
UnitRange{Int}*Int and StepRange{Int,Int}+Int could be faster

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#19131]
These operations currently take a code path that calls `steprange_last`, which requires a modulo operation for `steprem`. For `UnitRange{Int}*x`, this will be `(stop*x-start*x) % x`. For `StepRange{Int,Int}+x`, this will be `(stop+x-start-x) % step`, where `(stop-start) % step` was 0 before by construction. Both of these should be 0, at least if there's no overflow. I haven't thought through what happens if there's no overflow, but checking for overflow and throwing would almost certainly be cheaper than the expensive modulo operation.

**Comment by KristofferC** [comment]
This seems fixed

0.6
```
julia> @btime (1:5)*3
  18.922 ns (0 allocations: 0 bytes)
3:3:15

julia> @btime (1:3:10) + 5
  30.409 ns (0 allocations: 0 bytes)
6:3:15
```

0.7
```
julia> @btime (1:5)*3
  1.793 ns (0 allocations: 0 bytes)
3:3:15

julia> @btime (1:3:10) .+ 5
  1.599 ns (0 allocations: 0 bytes)
6:3:15
```
