### ISSUE TITLE
Incorrect type inference for Array{Pair{Symbol,*},1}

### ISSUE THREAD

**Issue by chipkent** [JuliaLang/julia#19139]
running: 
typeof([:X=>:(A+B), :Y=>:(A+1), :Z=>3])

produces:
Array{Pair{Symbol,B},1}

I have no clue where the "B" type comes from.  It seems like it should be resolved to Any.  Furthermore, type resolution seems to be broken for this case.

function func{T}(x::AbstractVector{Pair{Symbol,T}}) return "huh?" end
func([:X=>:(A+B), :Y=>:(A+1), :Z=>3])

yields a "MethodError: no method matching func(::Array{Pair{Symbol,B},1})  Closest candidates are: func{T}(!Matched::AbstractArray{Pair{Symbol,T},1})

versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by chipkent** [comment]
typeof(Dict(:X=>:(A+B), :Y=>:(A+1), :Z=>3))
properly resolves to
Dict{Symbol,Any}

**Comment by yuyichao** [comment]
`B` is a type parameter.

**Comment by yuyichao** [comment]
No. The printing of the type is not necessarily valid code.

**Comment by vtjnash** [comment]
But that will be fixed by #18457 :)

**Comment by nalimilan** [comment]
I've bumped into the same problem recently. See https://github.com/JuliaLang/julia/pull/19171 for a fix.

**Comment by yuyichao** [comment]
We can change the promotion rules but afaict there's nothing wrong with the current result and generic code should be prepared to accept `Vector{Pair{Symbol}}`.

**Comment by nalimilan** [comment]
The problem for me was that things like `[:a=>1, :b=>2.0]` did not use a concrete type like `[1, 2.0]` would. Promoting types seems more practical, efficient and consistent.
