### ISSUE TITLE
so many plotting packages

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#19149]
would be nice to have an organization to contain all of these.  as @StefanKarpinski pointed out (i forget where exactly), it would help to encourage developers to work together.  it would also help new users of julia figure out which package they want to use.

https://github.com/johnmyleswhite/ASCIIPlots.jl
http://github.com/baggepinnen/ExperimentalAnalysis.jl
http://github.com/jheinen/GR.jl
http://github.com/GiovineItalia/Gadfly.jl
http://github.com/mbaz/Gaston.jl
http://github.com/ma-laforge/GracePlot.jl
http://github.com/ma-laforge/InspectDR.jl
http://github.com/sisl/PGFPlots.jl
http://github.com/plotly/Plotly.jl
http://github.com/tbreloff/Plots.jl
http://github.com/JuliaPy/PyPlot.jl
http://github.com/ig-or/QWTwPlot.jl
http://github.com/tbreloff/Qwt.jl
http://github.com/rennis250/Sparrow.jl
http://github.com/sunetos/TextPlots.jl
http://github.com/Evizero/UnicodePlots.jl
http://github.com/nolta/Winston.jl

**Comment by yuyichao** [comment]
Please use the mailing lists for this since this is not something that we need to do in this repo.

**Comment by bjarthur** [comment]
https://groups.google.com/forum/#!topic/julia-users/Qx5CDrbFQPA
