### ISSUE TITLE
crazy idea: relegate IEEE 754 comparison to special ops

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19148]
There have been endless discussions about equality and inequality (e.g. https://github.com/JuliaLang/julia/issues/18485), many of the pains of which come from the fact that IEEE 754 mandates numerical comparisons which arguably beneficial for numerical analyis, have impressively bad consequences for language semantics for things like hashing and sorting. So here's the crazy idea that came up recently...

Normal comparisons `==`, `!=`, `<`, `>`, `<=` and `>=` do sane (i.e. non-IEEE) comparisons:
- these are used by hashing and sorting for all things
- `==` is reflexive and transitive, including `NaN == NaN`
- `-0.0 < 0.0` and `-0.0 != 0.0`

Introduce `~==`, `~!=`, `~<`, `~>`, `~<=` and `~>=` (or something) for IEEE comparisons:
- only used explicitly by user code
- defaults to calling normal comparisons
- `NaN ~!= NaN`
- `-0.0 ~== 0.0`

**Comment by yuyichao** [comment]
One issue is that this can make some of these operators much slower since the hardware generally implements the ieee version.....

**Comment by simonbyrne** [comment]
So would `x <= NaN` for all `x`?

**Comment by StefanKarpinski** [comment]
Yes.

**Comment by oscardssmith** [comment]
even for x=inf?

**Comment by StefanKarpinski** [comment]
Yes.

**Comment by tkelman** [comment]
> So would `x <= NaN` for all `x`?

Unless the NaN's sign bit is considered important, right?

**Comment by StefanKarpinski** [comment]
We don't currently sort floats by sign.

**Comment by StefanKarpinski** [comment]
NanS rather

**Comment by JeffBezanson** [comment]
Another compatibility strategy to consider is an `IEEE` module that defines its own `==` that falls back to Base's `==` but has its own methods for floats. This would be especially effective if we could have `using`s local to a function, so that a function could start with e.g. `using IEEE: ==`.

**Comment by JeffBezanson** [comment]
Actually you get the same effect from `(==) = IEEE.:(==)` at the top of a function. Maybe local `using` could even be syntax for that.

**Comment by simonbyrne** [comment]
I'm going to take the negative side here: I think the NaN ship has sailed, and we would be breaking compatibility with basically every other language in existence, as well as likely incurring a performance hit when comparisons are no longer single instructions.

**Comment by StefanKarpinski** [comment]
I agree with all of that, @simonbyrne, I'm just torn because I'm sick of all of the problems caused by IEEE semantics. In case they're unclear to people, let me spell them out. We have two nearly-identical sets of comparison operations:

- `==` and `<`: these are currently what you typically use and what you define methods for when defining equality or comparison for any type that isn't an IEEE floating-point type.

- `isequal` and `isless`: when you write generic code that does equality comparisons or sorting of values and thus requires reflexivity of NaNs and that -0.0 < 0.0, you have to use these.

This also means that doing obvious and tempting things like `sort(v, lt = >)` is wrong, instead you have to do something like `sort(v, lt = (a,b)->isless(b,a))` instead. These near-identical parallel universes of comparison operations extend to issues like does `v == w` use `==` or `isequal` for comparison when `v` and `w` are collections? When we do `x in v` do we check if `x` is `==` to each `y` in `v` or do we use `isequal`?

My proposal is essentially to stop catering to the bizarreness of IEEE for the general equality and comparisons and only opt into it for floating-point code, which is the only code that should really even worry about it.

**Comment by JeffBezanson** [comment]
A possible compromise is to do #9381, and take it as far as possible --- use `isequal` as the default comparison in all functions that "lift" comparison in some way. Maybe even inside `==` for arrays.

Currently, even types like `Tuple` and `Pair` define both `==` (which calls `==` internally) and `isequal` (which calls `isequal` internally). This is strange, since there isn't really any such thing as "IEEE-754 comparison of tuples". An extreme example is `Expr`, whose `==` method even today calls `isequal`, since two identical expressions containing NaNs are equivalent in any reasonable way you could care about when handling Exprs.

**Comment by tpapp** [comment]
With `Nullable` gaining support gradually, we have two parallel ways of representing missing/optional values: one general, and one specialized for floating point using sentinel values (`NaN`).

From this perspective,
1. what we call `Float64` is actually isomorphic to `Nullable{Float64}`, it just has different syntax and semantics,
2. this issue is related to #18264,
3. we could consider the possibility of enforcing semantics for `x op y` which are invariant to converting between `NaN` and `Nullable{Float64}()`.

The `0.0` vs `-0.0` issue is orthogonal to the above.

**Comment by nalimilan** [comment]
Doesn't sound like a bad idea; though `NaN` should probably not be used for missing values, since we have `Nullable{Float64}()` for that. Note that `isequal` and `isless` are already consistent between `NaN` and `Nullable{Float64}()`. Of course other operators are not.

**Comment by StefanKarpinski** [comment]
It's an interesting idea, although doing that would require `Nullable{Float64}` have the same in-memory representation as `Float64` – or more to the point, that `Vector{Nullable{Float64}}` and `Vector{Float64}` do – which is currently not the case.

**Comment by JeffreySarnoff** [comment]
If this is something that can occur without bothering unrelated normal use; it is a very compelling idea.  There are many Float64 and Float32  data vectors with the occasional missing value.  The performance uniformity is a big win. Please include Float16s.

**Comment by yuyichao** [comment]
Given the "voting result" 1 :+1: , 7 :-1: right now and the peformance impact on all current floating point code due to lack of hardware support, can we close this?

**Comment by StefanKarpinski** [comment]
Sure. I guess we'll have to live with the current unfortunate situation.
