### ISSUE TITLE
@testset results not being printed in REPL

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#19145]
Above is 0.6, below is 0.5:

![image](https://cloud.githubusercontent.com/assets/1282691/19812213/ef561cca-9d34-11e6-86f4-b466050a6362.png)

cc @kshyatt

**Comment by tkelman** [comment]
That was intentional for passing tests, but we should stop printing `Expression: nothing`, see https://github.com/JuliaLang/julia/issues/18739

**Comment by KristofferC** [comment]
Ok. Closing.

**Comment by KristofferC** [comment]
In my opinion this made the outputs in C.I worse for packages just because base decided to use `@testset`. Instead of changing defaults it would be been better in my opinion to have something akin `JULIA_DISABLE_TESTOUTPUT`.
