### ISSUE TITLE
inconsistent unique in Atom

### ISSUE THREAD

**Issue by missperovaz** [JuliaLang/julia#19165]
Hi folks,

I've noticed that in v5 the expression

`unique([122 122.5 10 10.3])
`
gives as result the following vector:

122 123 10 10.3

Any device? Is there any maximum number of characters displayed in the console, or something similar?

thanks,

**Comment by yuyichao** [comment]
AFAICT this does not happen in a bare REPL. Please ask these questions on the mailing list. Feel free to ping back here for reopen or open a new bug if it turns out to be likely a base issue.
