### ISSUE TITLE
code coverage on partial expressions

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#19161]
In https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/test/graphdigraph.jl#L65-L68:

```
g = Graph(sparse(adjmx1))
h = DiGraph(sparse(adjmx1))
@test !is_directed(g)
@test is_directed(h)
```

However, from `julia --inline=no --code-coverage=all test/runtests.jl`:

```
       17 ==(g::DiGraph, h::DiGraph) =
        -     vertices(g) == vertices(h) &&
        -     ne(g) == ne(h) &&
        -     fadj(g) == fadj(h) &&
        -     badj(g) == badj(h)
        -
        - is_directed(g::DiGraph) = true
        -
```

Codecov reports it similarly: https://codecov.io/gh/JuliaGraphs/LightGraphs.jl/src/c3fad06d21bb85c5b4685ccd1b23b2e5febd07c9/src/digraph.jl

There are a few other places where explicit tests are not being counted. How do I fix this so I can get LG to 100%?

**Comment by yuyichao** [comment]
The second case should be fixed on master already. The first case requires parser change and/or partial line/expression coverage support.

**Comment by sbromberger** [comment]
Sorry - what's the first case / second case?

**Comment by yuyichao** [comment]
First

```jl
       17 ==(g::DiGraph, h::DiGraph) =
        -     vertices(g) == vertices(h) &&
        -     ne(g) == ne(h) &&
        -     fadj(g) == fadj(h) &&
        -     badj(g) == badj(h)
```

Second,

```jl
        - is_directed(g::DiGraph) = true
```

**Comment by sbromberger** [comment]
Oh, the `==` looks fine (and isn't reported as a coverage failure). It's the `is_directed` that I'm concerned about.

**Comment by yuyichao** [comment]
AFAICT the second issue is fixed on master and should work even with inining on. I renamed the issue to cover the first case since I don't think we have an issue for it yet.

Please open a new issue about the second case if it is not fixed on master.

**Comment by sbromberger** [comment]
LightGraphs likely won't work on master so I can't really test it.

**Comment by yuyichao** [comment]
> Will the fix be backported to 0.5 at some point?

Very unlikely. There are multiple PR's involved (https://github.com/JuliaLang/julia/pull/18520 https://github.com/JuliaLang/julia/pull/18431 https://github.com/JuliaLang/julia/pull/18196) and it depends on a codegen change (https://github.com/JuliaLang/julia/pull/18163) and closely related to a type inference change (https://github.com/JuliaLang/julia/pull/18260).

**Comment by sbromberger** [comment]
OK, thanks for the input. The first case doesn't really affect me so feel free to use this as the issue, but I'll mute the notifications.

**Comment by sbromberger** [comment]
I'm going to close this out as I'm not sure it's relevant anymore.
