### ISSUE TITLE
apt-get install doesnt detect source-built opencv

### ISSUE THREAD

**Issue by Miej** [JuliaLang/julia#19167]
lots of errors like this when trying to do the 'standard' install.

"dpkg: warning: files list file for package 'libopencv-videostab2.4:amd64' missing; assuming package has no files currently installed
dpkg: warning: files list file for package 'libopencv-ocl-dev:amd64' missing; assuming package has no files currently installed
"

will be building from source so I can fix the hardcoded paths myself.

**Comment by yuyichao** [comment]
I can only assume you are trying to install a package that depends on opencv using an apt-get provider (or I can't see why it is related to julia at all). If that is the case, please report it to the package or BinDeps or whatever calls apt-get directly. I don't think we are doing that anywhere in the base repo.
