### ISSUE TITLE
split(s) not recognizing limit/keep

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#19178]
`split(s; limit=3)` gives a
```
MethodError: no method matching split(::String; limit=3)
Closest candidates are:
  split(::AbstractString) at strings/util.jl:151 got unsupported keyword argument "limit"
  split{T<:AbstractString}(::T<:AbstractString, ::Any; limit, keep) at strings/util.jl:127
  split{T<:SubString{T<:AbstractString}}(::T<:SubString{T<:AbstractString}, ::Any; limit, keep) at strings/util.jl:126
```
on 0.5 (but affects master too, I think).

I would expect that it should be possible to specify the `limit` and `keep` arguments in the default delimiter / whitespace case as well. I suppose [`strings/util.jl:276`](https://github.com/JuliaLang/julia/blob/master/base/strings/util.jl#L276) should be updated to pass the keyword arguments along?

Passing `Base._default_delims` manually mostly works (e.g. `split("A  B  C  D", Base._default_delims; limit=3, keep=false)` -> `["A", "B", " C  D"]`), except the bit where it keeps the whitespace before the last element -- I feel like that ought to be dropped as well when `keep=false`.

**Comment by KristofferC** [comment]
```
julia> s = "fo oo ba a a r"
"fo oo ba a a r"

julia> split(s; limit=3)
3-element Array{SubString{String},1}:
 "fo"
 "oo"
 "ba a a r"
```

It is tested.
