### ISSUE TITLE
convert(Unsigned, ::BigInt) and convert(Signed, ::BigInt) throw confusing error

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#19182]
Migrated from https://github.com/JuliaLang/julia/issues/15601#issuecomment-257641558:

```jl
julia> Unsigned(big(100))
ERROR: argument is an abstract type; size is indeterminate
 in convert(::Type{Unsigned}, ::BigInt) at ./gmp.jl:181
 in Unsigned(::BigInt) at ./sysimg.jl:53

julia> Signed(big(100))
ERROR: argument is an abstract type; size is indeterminate
 in convert(::Type{Signed}, ::BigInt) at ./gmp.jl:191
 in Signed(::BigInt) at ./sysimg.jl:53
```

The [methods here](https://github.com/JuliaLang/julia/blob/7aba3f57bcd370c7bda2a3df4ba6cecf3553df33/base/gmp.jl#L180-L200) (defined for `T<:Signed` and `T<:Unsigned`) fail because `sizeof(Signed)` and `sizeof(Unsigned)` are not defined, which are called in the cases `T==Signed` and `T==Unsigned`.

It seems clear to me that we need specialized methods to handle `convert(Unsigned, ::BigInt)` and `convert(Signed, ::BigInt)` to fix the issue, but I'm not sure what the correct thing to do is here. Two obvious options:

1. Try to convert to `Int` or `UInt`, else throw an `InexactError` if the `BigInt` is too big (or has the wrong sign in the case of `Unsigned(big(-1))`).

2. Always throw an `InexactError` (a better error than "argument is an abstract type").

**Comment by yuyichao** [comment]
Is there a different use case where converting to `Signed` and `Unsigned` is useful (and just work on `BigInt` for generic code). I see convertions to `Integer` in generic code a lot but not as much for `Unsigned` / `Signed` . If not then maybe throw a better error would be the way to go.

**Comment by stevengj** [comment]
It seems like we should define `BigInt :< Signed` and make `Signed(x::BigInt) = x` a no-op.  `Unsigned(::BigInt)` seems like it should throw an error since we don't have an unsigned bignum type.

**Comment by stevengj** [comment]
Seems wrong:
```
julia> BigInt <: Signed
false
```

(Note also that there is no docstring for `Signed`.)

**Comment by jiahao** [comment]
Yeah, `BigInt`s live outside of `Signed` and `Unsigned`, which seems strange.

**Comment by simonbyrne** [comment]
I think a few places may use an implicit assumption that `Signed` integers are stored as two's complement, which [BigInts are not](https://gmplib.org/manual/Integer-Internals.html).

**Comment by stevengj** [comment]
@simonbyrne, can you give an example?  I would think that any such methods would need (and maybe already have) specialized `BigInt` methods already.

**Comment by stevengj** [comment]
One problem is that we'll get a bunch of method ambiguities that we'll need to resolve.  e.g. `<( x::Signed,   y::Unsigned)` will become ambiguous with `<(x::BigInt, i::Integer)`.

**Comment by simonbyrne** [comment]
I had a quick look, and I didn't see any, so maybe it is okay (though packages may do this).

The other issue is the use of `typemin`/`typemax`: I think most uses in Base will be okay, but [this one](https://github.com/JuliaLang/julia/blob/30bf89f3d8e564b588b8e48993e92a551b384f2c/base/rational.jl#L190) will need another method.
