### ISSUE TITLE
Output warning when `@time` is called in global scope

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#19184]
One recurring topic on the mailing list is that people benchmark code in global scope. Since this usually involves calling `@time` or one of its friends, I wonder whether it would be possible to detect when this macro is used in global scope, and then output a respective warning?

Maybe this distinction would work: Calling `@time` either in local scope, or in global scope with a single function call as argument, are both fine.

**Comment by yuyichao** [comment]
I don't think this is the only way benchmarks or reflection functions are used in the wrong way when diagnosing performance issues. There are legit use of `@time` in global scope with a complex expressions (e.g. for purposefully benchmarking global operations, or when I know that the top level expression will be compiled, or when the additional code in the top level expression takes no time to execute compare to the function call). It'll be really annoy if there's a warning in each of those cases and I'd prefer to teach people the right way to benchmark using some other methods.

**Comment by KristofferC** [comment]
Agree with `yuyichao`. There are many use cases where this is valuable and trying to come up with a set of rules for when to warn or not seems error prone.
