### ISSUE TITLE
Variable scope in doctest system

### ISSUE THREAD

**Issue by xorJane** [JuliaLang/julia#19183]
Variables declared in unrelated doctests in the same file seem to live together in global scope and can impact each other's results. 

For example, if we try to use a function `foo()` in doctests for each of two functions declared in the same file, the second doctest will fail because of a warning about overwriting method definitions.

Would it be possible/valuable to change this behavior by introducing a new global scope for each code block beginning with `jldoctest`?

Thank you!

**Comment by MichaelHatherly** [comment]
(Will be fixed by #18588 since Documenter doctests each block in a separate module.)

**Comment by xorJane** [comment]
Awesome! Feel free to close this issue then.
