### ISSUE TITLE
REPL: alt- or ctrl-arrow inputs 'ABCD' characters

### ISSUE THREAD

**Issue by swt30** [JuliaLang/julia#19193]
Not a hindrance in any way, just slightly unusual. At the REPL, pressing alt-up or ctrl-up inputs 'A', alt-down inputs 'B', alt-right inputs 'C'... This only happens at the Julia prompt.

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by swt30** [comment]
Found this behaviour mentioned in https://github.com/JuliaLang/julia/issues/6347.

**Comment by vtjnash** [comment]
We just pass through any unrecognized character sequences to the terminal. Since these aren't defined to do anything, the terminal just prints them.
