### ISSUE TITLE
Julia starting problem

### ISSUE THREAD

**Issue by youeh1** [JuliaLang/julia#19201]
I just downloaded and installed the 64bit version of julia command line.

Starting julia by double clicking didn't work, with a flash pop up and fade away..
I can't see any interface for that.

What's the problem??

**Comment by StefanKarpinski** [comment]
Please post questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.

**Comment by tkelman** [comment]
this could be a valid issue report, but needs more information. what operating system? try running from the command line instead of double-clicking, see if there are any errors visible.

**Comment by youeh1** [comment]
I use 64bit windows 10 and Korean is background language.

I changed the path from the default to C:\julia, then it worked finally (surprised) ..I am not sure why..
Sorry, I am a new boy in the computer world.

**Comment by nalimilan** [comment]
And what was the default on your computer? Could be a character encoding issue.
