### ISSUE TITLE
make REPL modes sticky

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19202]
We all kind of agreed this would be better some time ago. I suspect that @Keno never implemented this because he has his REPL configured so it's already the case, but we should make it the default for everyone.

**Comment by ararslan** [comment]
Could you explain what it means for a mode to be "sticky" in the context of the REPL? Sorry, I'm not familiar with the terminology.

**Comment by StefanKarpinski** [comment]
Sticky means that after you evaluate something in a mode, your next prompt is in the same mode.

**Comment by JeffBezanson** [comment]
I'm not sure I'd want that for help mode.

**Comment by Keno** [comment]
Only the shell mode. I agree it's not what you want for help mode.

**Comment by StefanKarpinski** [comment]
Fair enough. Can we have a default stickiness map where shell mode defaults to sticky?

**Comment by amitmurthy** [comment]
I often find myself wishing that help modes are not part of the command history, but I suspect most people are fine with this behavior though.

**Comment by i-apellaniz** [comment]
I think help mode been sticky too would consistent and not so inconvenient.

Here come some arguments:
* having sticky modes in general is desired for most of us.
* Making help mode non-sticky is confusing, from the behavior point of view of the REPL.
* In MATLAB you have a little button to ask for help which opens a window, much more intrusive. You can also do `help <name>` but this cannot be considered as a mode.
* Last but not least, sticky mode for help would allow to have 2 terminals in which run Julia code on one and ask for clarifying questions on the other. This makes me imagine lots of possibilities.

The filtering of the command history could be solved by `? UP-ARROW` for only help history, `! UP-ARRW` for shell history and so on... while skipping them on the usual history.

**Comment by StefanKarpinski** [comment]
I actually think I would prefer having help mode be sticky as well and this is probably a more noobie-friendly default to be consistently sticky.

**Comment by garrison** [comment]
I tried having all modes be sticky for a few weeks, and it really just drove me crazy.  I think it may sense with shell mode, but I found myself stumbling almost every time I wanted to go back to the normal prompt after using help mode.

It might be nice to have this easily configurable per-mode on master for a bit, so that people can try various stickiness combinations and see how they work in practice (e.g. sticky on shell mode only).  I had thought I was going to like having everything be sticky, but I did not in the end.

**Comment by tkelman** [comment]
maybe should tie into https://github.com/JuliaLang/julia/issues/14081, have a stickiness modifier as part of a switcher menu

**Comment by musm** [comment]
Both Pkg and the shell are not sticky by default. Are we missing any other modes that prevent the closing of this issue?

**Comment by musm** [comment]
@StefanKarpinski  Should we rename this issue to make "help mode sticky by default", as per your comment:

> I actually think I would prefer having help mode be sticky as well and this is probably a more noobie-friendly default to be consistently sticky.

**Comment by quantum-booty** [comment]
@musm
I am a beginner and I like to have a separate Julia REPL instance opened in help mode. It would really improve my workflow if there is an option to make the help mode persistent!

**Comment by KristofferC** [comment]
> Should we rename this issue to make "help mode sticky by default", as per your comment:

I think in the vast majority of cases you run Julia code after looking up something in the help so persistent help mode seems like a worse default.

**Comment by rfourquet** [comment]
>  It would really improve my workflow if there is an option to make the help mode persistent!

I don't think we have an official API yet for that, but in the meantime you can do `Base.active_repl.interface.modes[3].sticky = true` (you can also do this in "startup.jl" in `atreplinit` after calling `REPL.setup_interface`).
