### ISSUE TITLE
Cannot add UniformScaling to symmetric sparse matrix

### ISSUE THREAD

**Issue by mihirparadkar** [JuliaLang/julia#19225]
I can't seem to add a symmetric sparse matrix to a UniformScaling.
This code:
```julia
#Create a sparse symmetric matrix
A = Symmetric( sparse([1 -1; -1 1]) )
#Add an identity doesn't work
# "indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"
AI = A + I
```
produces the following
`"indexed assignment not defined for Symmetric{Int64, SparseMatrixCSC{Int64,Int64}}"`

`versioninfo()`
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by ararslan** [comment]
Looks the issue is that copying the symmetric sparse matrix fails because there's no `setindex!` method for that type.

**Comment by andreasnoack** [comment]
In general, it is not possible to define `setindex!` for `Symmetric` meaningfully but it could work for the diagonal similarly to how it works for the non-zero part of `XTriangular`. That might fix this issue.

**Comment by ararslan** [comment]
Defining the requisite `copy!` methods helped but didn't solve it entirely; I ended up implementing specific `+` and `-` methods for `Symmetric` (and `Hermitian`) with `UniformScaling`.
