### ISSUE TITLE
Lack of DimensionMismatch error for A_mul_B! with small matrices

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#19224]
Behavior for 'big' matrices:
```julia
A = rand(6, 6)
B = rand(5, 5)
C = rand(5, 5)
A_mul_B!(A, B, C)
```
results in
```
ERROR: DimensionMismatch("A has size (5,5), B has size (5,5), C has size (6,6)")
```

However,
```julia
A = rand(6, 6)
B = rand(3, 3)
C = rand(3, 3)
A_mul_B!(A, B, C)
```
does not produce an error.

**Comment by ararslan** [comment]
Based on a cursory look through the code, it appears that the smaller case is going through `matmul3x3!`, which doesn't do dimension checking, whereas the larger case is going through `Base.BLAS.gemm!`, which includes the check that triggers the error.
