### ISSUE TITLE
Types referencing each other

### ISSUE THREAD

**Issue by wgreenr** [JuliaLang/julia#19234]
I apologize if this issue resolved elsewhere, I couldn't find how to make 2 types reference each other:

```julia
type A 
  b::B
end

type B
  a::A
end
```

What I get is
`UndefVarError: B not defined`

Wrapping them in the `module` doesn't help either. In other languages defining such types/classes/structs works seamlessly.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/269
