### ISSUE TITLE
How can I run .jl?

### ISSUE THREAD

**Issue by pepepepe2525** [JuliaLang/julia#19230]
I have a file of .jl that I want to run.How can I run it on julia0.5.0?

**Comment by ararslan** [comment]
Hello! Just so you know, questions like this should generally go to the [julia-users mailing list](https://groups.google.com/forum/#!forum/julia-users).

Julia files are run from the command line just like any other language. If the Julia binary is in your PATH, you can just do
```
julia yourfile.jl
```
otherwise you need
```
/path/to/julia yourfile.jl
```

**Comment by pepepepe2525** [comment]
Thank you very much , but my question was not complete.I want to run the "raijin" that is in under URL
https://github.com/iuraiura/raijin
I could download and manipulate parameters, but I couldn't run the raijin.jl
Could you help me?

**Comment by vchuravy** [comment]
Have you seen https://github.com/iuraiura/raijin#julia-実行環境構築? But as @ararslan said questions like this are better posted on the julia-users mailing list (https://groups.google.com/forum/#!forum/julia-users) or the issue tracker of the specific project: https://github.com/iuraiura/raijin/issues

**Comment by pepepepe2525** [comment]
thank you for your teaching. I post it in the mailing list. :)

2016-11-05 17:10 GMT+09:00 Valentin Churavy <notifications@github.com>:
