### ISSUE TITLE
quoting Module.operator for method definition

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#19235]
I was trying to define a method for `Base.==` **without** importing it.
```julia
julia> Base.==(::Foo,::Foo) = true
ERROR: syntax: "(::Foo,::Foo)" is not a valid function argument name
julia> Base.:==(::Foo,::Foo) = true
ERROR: syntax: invalid identifier name ":="
julia> Base.(==)(::Foo,::Foo) = true
ERROR: syntax: invalid function name "Base.((==,))"
```
Cf
```julia
julia> Base.:+(::Foo,::Foo) = Foo()
```
Which works fine. The issue is the following:
1. the manual could talk about the syntax for quoting operator names when qualified by a module,
2. if there is a uniform syntax, it should work for `==` too.

Using `v"0.5.0"`.

**Comment by andreasnoack** [comment]
You didn't try the remaining combination `Base.:(==)(::Foo,::Foo) = true` which is the one that works.

**Comment by yuyichao** [comment]
The document does mention that

> Sometimes extra parentheses around the argument to `:` are needed to avoid ambiguity in parsing.:

And uses `:` and `::` as examples.

**Comment by tpapp** [comment]
Thanks for the help. It did not occur to me to look in the Metaprogramming section, as I was not doing any metaprogramming. Perhaps a few examples or a remark in the Modules section could be helpful (I asked on Gitter before filing an issue and did not get a solution, so this is not something obvious).
