### ISSUE TITLE
Possible remaming of `num` and `den`?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#19233]
Could `num` and `den` be renamed to `numerator` and `denominator`? These function names are very unintuitive, and general policy is to avoid abbreviations unless they're very standard.

**Comment by StefanKarpinski** [comment]
Sure, seems like a good idea.

**Comment by thofma** [comment]
Where is the problem? There could not be more intuitive names for these functions. When your are working with rational types, it is only natural to look for something like `num` or `den`. No need to make it too verbose.

Please keep the abbreviations. They are standard.

**Comment by KristofferC** [comment]
+1 for renaming.

**Comment by KristofferC** [comment]
> There could not be more intuitive names for these functions. 

I disagree, `numerator` is more intuitive than `num`. This also has precedence from Python:

```python
>>> from fractions import Fraction
>>> a = Fraction(16, -10)
>>> a.denominator
5
>>> a.numerator
-8
```

**Comment by TotalVerb** [comment]
And [Racket](https://docs.racket-lang.org/reference/generic-numbers.html?q=numerator#%28def._%28%28quote._~23~25kernel%29._numerator%29%29).

**Comment by StefanKarpinski** [comment]
Can you cite some languages or libraries where this naming is used? Mathematica [uses](http://reference.wolfram.com/language/ref/Rational.html) "Numerator" and "Denominator"; Python [uses](https://docs.python.org/3.1/library/fractions.html) "numerator" and "denominator". Matlab doesn't have a standard way of representing or operating on rational numbers. R doesn't seem to either.

**Comment by ararslan** [comment]
Ruby also uses `numerator` and `denominator`: https://ruby-doc.org/core-2.2.0/Rational.html

**Comment by martinholters** [comment]
Add [Haskell](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Ratio.html) to the list for numerator and denominator.

**Comment by thofma** [comment]
Ok, convinced.
