### ISSUE TITLE
Numerical type conversion misbehaving with complex numbers

### ISSUE THREAD

**Issue by gmoutsin** [JuliaLang/julia#19240]
I am trying to compute something that is very sensitive to errors and I am failing. One of the things that seems to have an effect is the following.

By setting t` = 10 + 10im` then `1//t` gives the correct answer `1//20 - 1//20*im`.

However the command `BigFloat(1)/t` gives as an answer
`5.000000000000000277555756156289135105907917022705078125000000000000000000000000e-02 - 5.000000000000000277555756156289135105907917022705078125000000000000000000000000e-02im`
which is clearly wrong.

I assume that there is a conversion to `Float64` before the final conversion to `BigFloat`.

**Comment by gmoutsin** [comment]
By the way, when `t` is real, it seems to work as it should.

**Comment by andreasnoack** [comment]
Yes. The problem is here https://github.com/JuliaLang/julia/blob/master/base/complex.jl#L239. It should promote the types first. Maybe something like `/(x::Real,z::Complex) = x*inv(last(promote(x,z)))`.

**Comment by gmoutsin** [comment]
I am not completely sure what `promote` should do but this seems wrong
```
julia> promote(BigFloat(1/3))
(3.333333333333333148296162562473909929394721984863281250000000000000000000000000e-01,)
```

**Comment by andreasnoack** [comment]
`promotes` takes two arguments and converts the two arguments to the same common type determined by the promote rules. There is no problem in the example you just gave because the `BigFloat(1/3)=BigFloat(Float64(1)/Float64(3))=BigFloat(1.0/3.0)` so the division is made for `Float64`s and the conversion only happens after the division. An example of the difference could be
```
julia> BigFloat(1) / (2 + 1im)
4.000000000000000222044604925031308084726333618164062500000000000000000000000000e-01 - 2.000000000000000111022302462515654042363166809082031250000000000000000000000000e-01im

julia> /(promote(BigFloat(1), (2 + 1im))...)
4.000000000000000000000000000000000000000000000000000000000000000000000000000009e-01 - 2.000000000000000000000000000000000000000000000000000000000000000000000000000004e-01im``

**Comment by gmoutsin** [comment]
I just realised and deleted it. Sorry for that.
