### ISSUE TITLE
Synced array operation when a=b=c=[]

### ISSUE THREAD

**Issue by jac0320** [JuliaLang/julia#19241]
There might be a similar issue but I didn't figure out the best keyword to find it.

So, I was trying out this
a = b = c = []

Then if I push an element into c by calling
push!(c, 15)

Then this is the results
julia> a=b=c=[]
0-element Array{Any,1}

julia> push!(c,15)
1-element Array{Any,1}:
 15

julia> a
1-element Array{Any,1}:
 15

julia> b
1-element Array{Any,1}:
 15

It seems like these arrays are all pointed by the same pointer. The same situation goes for Set() and Dict(). When popping, all these perform the same operation at the same time.

Is there a way that I can break the link when at a good timing?

This won't apply to scalar assignment, 
a=b=c=5
Somehow this is not a linked case. Each of them is independent.

**Comment by cstjean** [comment]
[http://www.johnmyleswhite.com/notebook/2014/09/06/values-vs-bindings-the-map-is-not-the-territory/](http://www.johnmyleswhite.com/notebook/2014/09/06/values-vs-bindings-the-map-is-not-the-territory/) Julia is different from Matlab in this regard.
