### ISSUE TITLE
Showing README fallback for module help doesn't extend to modules found in LOAD_PATH

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#19248]
Showing help for modules falls back to displaying `README.md`, which is nice, but only if the module is located in `Pkg.dir()`. If the module is loaded from `LOAD_PATH` this fallback is unavailable.

This is obviously most interesting for locally developed code but to demonstrate we can look at `ImageFiltering` (which has a short `README.md`). With `ImageFiltering` in `Pkg.dir()` things work as expected:
```
julia> using ImageFiltering

help?> ImageFiltering
search: ImageFiltering

  No documentation found.

  Displaying the README.md for the module instead.

  ----------------------------------------------------------------------------

     ImageFiltering
    ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  (Image: Build Status)

  (Image: codecov.io)

  ImageFiltering implements blurring, sharpening, gradient computation, and
  other linear filtering operations, as well nonlinear filters like min/max.

  Read the documentation here:

  (Image: ) (Image: )
```
If we remove it from `Pkg.dir()` (most easily simulated by pointing `JULIA_PKGDIR` elsewhere) and instead load it from `LOAD_PATH` the fallback no longer works.
```
julia> pkgdir = Pkg.dir();

julia> ENV["JULIA_PKGDIR"]=""
""

julia> using ImageFiltering
ERROR: ArgumentError: Module ImageFiltering not found in current path.
Run `Pkg.add("ImageFiltering")` to install the ImageFiltering package.
 in require(::Symbol) at ./loading.jl:365

julia> push!(LOAD_PATH, pkgdir);

julia> using ImageFiltering

help?> ImageFiltering
search: ImageFiltering

  No documentation found.

  No README.md found for module ImageFiltering.
```

**Comment by yuyichao** [comment]
Basically dup of https://github.com/JuliaLang/julia/issues/8679

**Comment by KristofferC** [comment]
Markdown doesn't do this anymore so this issue is obsolete.
