### ISSUE TITLE
slow generator performance?

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#19256]
Hello all.  I apologize for how contrived this example must seem, and I'm not even completely sure if the problem has anything to do with generators.  In spite of this, this scenario actually did come up when I was trying to force proper dispatching to overcome slowness of macro-generated code which was suffering the ill-effects of the black-box nature of DataFrames with `NullableArray`s (I'm not necessarily claiming that I knew the best way to deal with that).  Anyway, see the following
```julia
const N = 10^6
A = rand(N)
B = rand(N)

f(x, y) = x + y 

# this function has generators in loop
function loopfunc1(vs::Vector...)
    o = Vector{Float64}(length(vs[1]))
    for i ∈ 1:length(o)
        o[i] = f((v[i] for v ∈ vs)...)
    end
    o
end

# I think this also has generators in the loop, but now it's called from a function.  why should that matter?
function loopfunc2(vs::Vector...)
    get_args(i) = (v[i] for v ∈ vs)
    o = Vector{Float64}(length(vs[1]))
    for i ∈ 1:length(o)
        o[i] = f(get_args(i)...)
    end
    o
end

@time loopfunc1(A, B)
>>>  6.126686 seconds (8.02 M allocations: 237.365 MB, 3.32% gc time)
@time loopfunc2(A, B)
>>>  0.286235 seconds (7.01 M allocations: 221.822 MB, 6.82% gc time) 
```

**Comment by pabloferz** [comment]
I'd suspect `loopfunc1` is creating a `Generator` type for every loop iteration while that is not the case for the latter.

**Comment by ExpandingMan** [comment]
I suppose it's possible that in the latter case the generator is not rebuilt on calls to `get_args`.

So is this even a bug?  It certainly doesn't seem like ideal behavior by any means, but is it fixable?  It is definitely not obvious to me as a user that I should avoid generator expressions in loops, and I suspect it won't be obvious to many other people either.

**Comment by yuyichao** [comment]
Dup of http://www.xiami.com/song/1770417429?spm=a1z1s.6659513.0.0.okaG3G

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276
