### ISSUE TITLE
start_reading

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#1925]
start_reading / stop_reading are needed on stdin_stream to share it with other processes. when should this be called? how automatic can it be? I suspect it's only needed with respect to spawning, in which case the default state could be start_reading and when spawning call stop_reading on the stream passed for stdin. currently the situation is a bit haphazard.

**Comment by JeffBezanson** [comment]
`start_reading`, `stop_reading`, and `start_watching` are all undocumented. We really must arrange to remove them from the exports. Nobody wants to have to use these functions.

**Comment by jiahao** [comment]
Closed by #10885 - don't recommend users to use them.
