### ISSUE TITLE
Combine `contains` and `ismatch`?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#19250]
[`ismatch`](http://docs.julialang.org/en/release-0.5/stdlib/strings/#Base.ismatch) and [`contains`](http://docs.julialang.org/en/release-0.5/stdlib/strings/#Base.contains) do basically the same thing, except the first takes a regex pattern, the second a string pattern, and the argument order is switched.

Can we combine them, and if so, which one should we keep?

**Comment by simonster** [comment]
See also #10593

**Comment by simonbyrne** [comment]
(lets try a vote by thumbs up)

`contains`
 - matches the argument order of `replace` (which already accepts both regexes and strings)

**Comment by simonbyrne** [comment]
`ismatch`
 - begins with `is` (making it easy to find by tab completion)
 - matches the argument order of `match`

**Comment by dhoegh** [comment]
See also discussion in #18028.

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/julia/pull/24673/
