### ISSUE TITLE
Creating a view (SubArray) of a Vector allocates memory

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#19257]
On 0.5 as well as the latest nightly, for matrices,
```julia
@benchmark view(a, 1:2, 1:2) setup = (a = rand(3, 3))
```
results in zero allocation.

However,
```julia
@benchmark view(a, 1:2) setup = (a = rand(3))
```
results in 48 bytes of allocation and is almost 6 times slower. I haven't been able to figure out what in `subarray.jl` causes this.

**Comment by prcastro** [comment]
I tracked a difference in memory allocation to `index_ndims`, but I still can't tell why.

**Comment by yuyichao** [comment]
I highly doubt you are testing the right thing. This sounds like a defect of `BenchmarkTools` since I believe both should actually allocate. `view(a, 1:2)` does seem to be slower and results in more allocation than `view(a, 1:2, 1:2)` and I assume that's what #19259 fixes.

**Comment by tkoolen** [comment]
Wow, thanks for the quick response!

@yuyichao, the only open issue I see in `BenchmarkTools` that could be related is https://github.com/JuliaCI/BenchmarkTools.jl/issues/26, but that seemed to not be an actual defect. I use `BenchmarkTools` a lot, so if there are cases where I can't rely on it, I'd be very interested in learning more about those.

To me, it conceptually doesn't make sense that `view(a, 1:2, 1:2)` should allocate, since `a` is already allocated, `1:2` is `isbits`, the `SubArray` resulting from `view` has no abstract members, and it contains just a reference to `a` plus some `isbits` offset/stride/index information.

**Comment by tkoolen** [comment]
Well, I guess I'm wrong :-)

**Comment by jrevels** [comment]
The missing allocation info here is definitely a BenchmarkTools issue, see my comment [here](https://github.com/JuliaCI/BenchmarkTools.jl/issues/26#issuecomment-259010332).

**Comment by andyferris** [comment]
> To me, it conceptually doesn't make sense that view(a, 1:2, 1:2) should allocate, since a is already allocated, 1:2 is isbits, the SubArray resulting from view has no abstract members, and it contains just a reference to a plus some isbits offset/stride/index information.

Currently, if it is not `isbits`, it isn't stack allocated. Because the view "struct" contains a reference to mutable `a`, my understanding is that the object will have to be allocated on the heap and GC'ed afterwards. It will only allocate a small amount of memory - enough for the `1:2` and a pointer to `a` (and anything else a view keeps around) and is "cheap" in the sense that it doesn't copy data in `a`.

Putting it on the stack requires scanning the stack for pointers that GC needs to know about, and this is tricky to do precisely (apparently - I'm no expert).

**Comment by andyferris** [comment]
BTW, I do agree with @yuyichao is correct and I'm still worried that *BenchmarkTools.jl* misses at lease some allocations. I'd love to be proven wrong, but...

**Comment by tkoolen** [comment]
> Currently, if it is not isbits, it isn't stack allocated. Because the view "struct" contains a reference to mutable `a` [...]

D'oh, I knew that; I was just confused.

**Comment by jrevels** [comment]
> I'm still worried that BenchmarkTools.jl misses at lease some allocations.

See https://github.com/JuliaCI/BenchmarkTools.jl/pull/28
