### ISSUE TITLE
sparse vector summation

### ISSUE THREAD

**Issue by jac0320** [JuliaLang/julia#19263]
I was trying to simply add two sparse vectors together within a function. But it returns me with an error.

hBar + hTilde
For debugging, I @show typeof(hBar), hBar.n, issparse(hBar) for both variables

This is what I got, what seem to be the issue?
(typeof(hBar),hBar.n,issparse(hBar)) = (SparseVector{Any,Int64},672,true)
(typeof(hTilde),hTilde.n,issparse(hTilde)) = (SparseVector{Any,Int64},672,true)
ERROR: LoadError: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(!Matched::Type{Base.LibGit2.Oid}) at libgit2/oid.jl:88
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:80
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:120
  ...
 in _binarymap(::Base.#+, ::SparseVector{Any,Int64}, ::SparseVector{Any,Int64}, ::Int64) at ./sparse/sparsevector.jl:936
 in vPlusv(::SparseVector{Any,Int64}, ::SparseVector{Any,Int64}) at /Users/sitew/Dropbox/SourceCodes/climate/./src/utility.jl:188
 in #benders#51(::Array{Any,1}, ::Function, ::Function, ::Function, ::Function, ::Function, ::Function, ::Function, ::#climate_benders_subprob_objective, ::Void) at /Users/sitew/Dropbox/SourceCodes/climate/./algo/benders.jl:153
 in (::#kw##benders)(::Array{Any,1}, ::#benders, ::Function, ::Function, ::Function, ::Function, ::Function, ::Function, ::#climate_benders_subprob_objective, ::Void) at ./<missing>:0
 in main(::Dict{Symbol,Any}) at /Users/sitew/Dropbox/SourceCodes/climate/adcc.jl:96
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/sitew/Dropbox/SourceCodes/climate/adcc.jl, in expression starting on line 138

**Comment by martinholters** [comment]
I don't think there is a reasonable way to do math with `SparseVector`s where the `eltype` does not support `zero`. In special cases, like adding two `SparseVector`s with the same sparsity structure, this might be doable, but I don't think it's worthwhile to rework the sparse array code to enable this.
