### ISSUE TITLE
Documentation of `EDITOR` environmental variable

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#19277]
The environmental variable `EDITOR` is not mention in the documentation of `Base.edit` or `Base.@edit`. The only place where it is mentioned is in the documentation for `Pkg.edit`. Would also be useful with documentation of how to set this (and other) environmental variables.

For reference:

```jl
help?> edit
search: edit @edit timedwait endswith redirect_stdin redirect_stdout redirect_stderr methodswith ObjectIdDict readandwrite WeakKeyDict

  edit(path::AbstractString, line::Integer=0)

  Edit a file or directory optionally providing a line number to edit the file at. Returns to the julia prompt when you quit the editor.

  edit(function, [types])

  Edit the definition of a function, optionally specifying a tuple of types to indicate which method to edit.
```

```jl
help?> @edit
  @edit

  Evaluates the arguments to the function or macro call, determines their types, and calls the edit function on the resulting expression.
```

```jl
help?> Pkg.edit
  edit()

  Opens Pkg.dir("REQUIRE") in the editor specified by the VISUAL or EDITOR environment variables; when the editor command returns, it
  runs Pkg.resolve() to determine and install a new optimal set of installed package versions.
```

**Comment by nalimilan** [comment]
Sounds like a good idea. Would you make a pull request? (You need to run `make julia-genstdlib` after changing docstrings to also update the manual.)

**Comment by fredrikekre** [comment]
Sure.
For the second part of the issue; should it be documented how to set environmental variables in Julia? Throughout the docs there are a lot of references to different such variables but nowhere documented how to set them. If yes, then where? Maybe open a separate issue for this?
