### ISSUE TITLE
Ubuntu failed to upgrade julia-common

### ISSUE THREAD

**Issue by nick3499** [JuliaLang/julia#19274]
Ubuntu repo provided Julia 0.4.7, which ran without a problem.

Later, I found a Julia PPA, which upgraded 0.4.7 to 0.5.0. But, after that, I was getting errors right away.

Then I found julia-deps PPA, and added that.

What I discovered was, even though `julia 0.5.0-yakkety7` had installed, `julia-common` was still at `0.4.7-1` in Ubuntu. Ubuntu seems to be treating Julia 0.4.7 as the current stable version.

So I uninstalled both `julia` (0.5.0) and `julia-common` (0.4.7-1). Then reinstalled `julia` 0.5.0 alone, without `julia-common`. Which seems to have solved my problem. I am currently running `julia` 0.5.0 without `julia-common`. Is `julia-common` essential? Do I have to have it?

1. installed Julia from Ubuntu repo
2. later added Julia PPA, and upgraded Julia
3. later than later added Julia-deps PPA

Do you think messing around with the repos might have caused my problem? It seems that by adding both Julia PPA and Julia-deps PPA at first, then installing Julia, might have avoided problems.

**Comment by tkelman** [comment]
Neither the PPA nor the Ubuntu packaging are maintained here. Report PPA issues to https://github.com/staticfloat/julia-debian, and issues with the official Ubuntu package through the Ubuntu bug reporting system.
