### ISSUE TITLE
`minimum` with collections of vectors inconsistent with `min`.

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#19275]
This behaviour seems inconsistent to me:

```julia
julia> min([1,2], [2,-1])
2-element Array{Int64,1}:
  1
 -1

julia> minimum([[1,2], [2,-1]])
ERROR: ArgumentError: ordering is not well-defined for arrays
 in _mapreduce(::Base.#identity, ::Base.#scalarmin, ::Base.LinearFast, ::Array{Array{Int64,1},1}) at ./reduce.jl:154
 in minimum(::Array{Array{Int64,1},1}) at ./reduce.jl:317

julia> reduce(min, [[1,2], [2,-1]])
2-element Array{Int64,1}:
  1
 -1
```

There seems to be two issues here:
1. To be honest, I was *really* expecting `minimum(x) = reduce(min, x)`. Currently, it is `mapreduce(identity, scalarmin, a)`. Fun. This seems to me to violate principles of simplicity and of least surprise.
2. Arguably, the first call arguably should be `min.([1,2], [2,-1])` and an error without the dot-call, e.g.: "`isless` on `Vector` not defined", since we are removing automatically vectorized functions.

With respect to the second, I *do* think that collections of collections are a little "ignored" with with dot-call syntax in general and that collections of collections remain difficult to work with.

**Comment by laborg** [comment]
Can be closed - This works on master (and 1.7.1):
```
julia> versioninfo()
Julia Version 1.8.0-DEV.1440
Commit e3b681c687 (2022-02-02 01:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, tigerlake)
Environment:
  JULIA_PKG_DEVDIR = /home/aigner/code

julia> min([1,2], [2,-1])
2-element Vector{Int64}:
 1
 2

julia> minimum([[1,2], [2,-1]])
2-element Vector{Int64}:
 1
 2

julia> reduce(min, [[1,2], [2,-1]])
2-element Vector{Int64}:
 1
 2
```
