### ISSUE TITLE
Manual: "Running External Programs" does not explain how to change working directory

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#19286]
I was surprised that this wasn't documented in the manual. Would be useful to have a section about `Cmd` objects and how you can customize them with the `dir` kwarg to set the working directory, and more generally the manipulation of working environments with `setenv()` and `withenv()`.

All of these are explained [in the standard library](http://docs.julialang.org/en/latest/stdlib/base/#Base.setenv), but it would be convenient to have a description in the manual, with suitable cross-references to the existing standard library documentation.

A simple example
```jl
Cmd(`pwd`, dir="..")
```

**Comment by nalimilan** [comment]
(I think `needs-docs` is for PRs which cannot be merged until docs have been added; `docs` would probably be more appropriate.)

**Comment by akaysh** [comment]
@jiahao This is pending from quite some time now. I think it would be appropriate to add a subsection called "Cmd" Object under the "Running External Programs" section with references across std-lib docs.
Any suggestions?
