### ISSUE TITLE
generator syntax for norm

### ISSUE THREAD

**Issue by chriscoey** [JuliaLang/julia#19289]
`sqrt(sumabs2(i for i=1:5))` works, so it would be nice to have `norm(i for i=1:5)` working.

**Comment by andreasnoack** [comment]
`norm` works for `AbstractVector` and `AbstractMatrix` whereas `vecnorm` works for iterables. 
```
julia> vecnorm(i for i=1:5)
7.416198487095663
```
To make it work for `norm` we'd have to define a method for `Generator` but it should be possible. Would you like to try to prepare a PR for this?

**Comment by chriscoey** [comment]
Ah, I didn't think to try vecnorm but that makes sense. Thanks!

I may run into this issue again for `AbstractVector` and `AbstractMatrix`, in about 1.5 months. I might have a go at a PR then but things are a little busy now.

**Comment by andreasnoack** [comment]
I'm tempted to think that we should close this one and refer to `vecnorm` for norm computations on generators. Any objections to that?

**Comment by oscardssmith** [comment]
Why not just give norm two definitions, one for matrices and one for vectors and remove vecnorm? Without thinking too hard, this seems to reduce the namespace and have no real downside. Am I missing something?

**Comment by johnmyleswhite** [comment]
The norm of a matrix is generally not equal to its norm when you treat it like a vector.

**Comment by nalimilan** [comment]
Though couldn't people write `norm(vec(x))`, which is very close to `vecnorm(x)`.

**Comment by andreasnoack** [comment]
`vecnorm` works for all iterables whereas `norm` is defined for `AbstractArray`s and is a matrix norm for `AbstractMatrix` and a vector norm for `AbstractVector`. E.g. you can do
```jl
g = (i + j for i in 1:3, j = 1:4)
vecnorm(g)
```
which wouldn't work for `norm(vec(g))`
