### ISSUE TITLE
Docstrings inside a begin block

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#19292]
This doesn't work. It's not a huge deal, but a bit inconvenient.

```{julia}
begin
    "A test function"
    test_function(a) = "testing"
end

@doc test_function
```

**Comment by yuyichao** [comment]
I believe this was intentional

**Comment by bramtayl** [comment]
Why?

**Comment by mbauman** [comment]
It's documented here: http://docs.julialang.org/en/release-0.5/manual/documentation/#advanced-usage

This is a duplicate of https://github.com/JuliaLang/julia/issues/15684.

**Comment by bramtayl** [comment]
Ok sorry for the duplicate
