### ISSUE TITLE
hcat is not type-stable for sparse matrices

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#19304]
```
julia> Base.Test.@inferred hcat(sparse(rand(3,4)) , eye(3,3))
ERROR: return type SparseMatrixCSC{Float64,Int64} does not match inferred return type Union{Array{Any,1},SparseMatrixCSC{Tv,Ti<:Integer}}
```

**Comment by Sacha0** [comment]
Ouch. In case someone looks into this in the near term, chances are the relevant code is [here](https://github.com/JuliaLang/julia/blob/42df52a356cb16f02651e4fe1e86533b74f9a7f7/base/sparse/sparsevector.jl#L845). Best!

**Comment by pabloferz** [comment]
Part of the problem is the same as #19038, that is, `cat_t` is no type stable and needs to be almost rewritten from scratch to fix it.
