### ISSUE TITLE
Document `@generated`

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#19300]
A docstring for `@generated` listing its capabilities and particularly its restrictions would be quite useful.

**Comment by oxinabox** [comment]
Would it suffice to copy-paste the top of:
https://docs.julialang.org/en/latest/manual/metaprogramming.html#Generated-functions-1
Up to the first example, 

into the docstring for `@generated`?

I feel like that would get most of the way there.
Maybe a little rewritting to be a bit more terse.

**Comment by laborg** [comment]
Can be closed - the docstring for `@generated` has been added in https://github.com/JuliaLang/julia/pull/27949
