### ISSUE TITLE
assertion failure with JULIA_THREADS=0

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#19328]
Adding `JULIA_THREADS=0` to Make.user results in:

```
    LINK usr/bin/julia-debug
    JULIA usr/lib/julia/inference.ji
julia-debug: /home/bezanson/src/julia/src/gc.c:821: jl_gc_pool_alloc: Assertion `ptls->gc_state == 0' failed.
```

On master.

**Comment by yuyichao** [comment]
That assertion can be disabled with threading off...

**Comment by StefanKarpinski** [comment]
Should we stop supporting turning threads off or do we still have use cases for it? If so, should we have a periodic CI run that checks that this still works?

**Comment by ararslan** [comment]
The README explicitly recommends setting `JULIA_THREADS=0` on x86 FreeBSD:

> The x86 arch doesn't support threading due to lack of compiler runtime library support (set `JULIA_THREADS=0`).

That text was introduced by @vtjnash, so maybe he'd have some insight. Though the [docs](https://www.freebsd.org/relnotes/CURRENT/hardware/proc.html) suggest that multithreading is indeed supported on i386 with Intel CPUs.

**Comment by vtjnash** [comment]
IIRC, last I checked, FreeBSD x86 was lacking a suitable libatomic library.
