### ISSUE TITLE
Type instability by interplay between `throw` and array comprehension?

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#19330]
I have a case where a function becomes type-unstable when it contains a `throw` clause AND array comprehension, and I don't understand why.  If either one of them disappears, type stability is recovered.

Here is a minimal working example.  First, function definitions:
```
function f(v::Vector{Int}, ind::Vector{Int})
    n = 2
    if n≠2; throw(ArgumentError()); end  # throw

    i1, i2 = ind[1], ind[2]
    [v[i1] for w = 1:2]  # array comprehension
    return v[i1]
end

function f_without_throw(v::Vector{Int}, ind::Vector{Int})
    n = 2
    # if n≠2; throw(ArgumentError()); end  # throw commented

    i1, i2 = ind[1], ind[2]
    [v[i1] for w = 1:2]  # array comprehension
    return v[i1]
end

function f_without_comp(v::Vector{Int}, ind::Vector{Int})
    n = 2
    if n≠2; throw(ArgumentError()); end  # throw

    i1, i2 = ind[1], ind[2]
    # [v[i1] for w = 1:2]  # array comprehension commented
    return v[i1]
end
```
Note that in `f()`, the `throw` clause is not even executed, and the array comprehension does not affect the return value.

Now, here are the excerpts from the `@code_warntype` result for `f()`.  Note that the local variable `i1` (`CORE.BOX`) and the return value (`ANY`) are type-unstable:
```
julia> v = [1,2,3]; ind = [1,2]; @code_warntype f(v,ind)
Variables:
  #self#::#f
  v::Array{Int64,1}
  ind::Array{Int64,1}
  n::Int64
  i1::CORE.BOX
  i2::Int64
  #1::##1#2{Array{Int64,1}}

Body:
  begin 
   ...
  end::ANY
```

On the other hand, we do not have such type instabilities for `f_without_throw()` and `f_without_comp()`:
```
julia> v = [1,2,3]; ind = [1,2]; @code_warntype f_without_throw(v,ind)
Variables:
  #self#::#f_without_throw
  v::Array{Int64,1}
  ind::Array{Int64,1}
  n::Int64
  i1::Int64
  i2::Int64
  #3::##3#4{Array{Int64,1},Int64}

Body:
  begin 
   ...
  end::Int64

julia> v = [1,2,3]; ind = [1,2]; @code_warntype f_without_comp(v,ind)
Variables:
  #self#::#f_without_comp
  v::Array{Int64,1}
  ind::Array{Int64,1}
  n::Int64
  i1::Int64
  i2::Int64

Body:
  begin 
  ...
  end::Int64
```

Why does `f()` suffer from type instability?

Here is the `versioninfo()` result:
```
julia> versioninfo()
Julia Version 0.5.1-pre+4
Commit 887ad05* (2016-10-28 19:39 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin16.0.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)
```

**Comment by vtjnash** [comment]
dup of https://github.com/JuliaLang/julia/issues/15276

**Comment by yuyichao** [comment]
And it's because of the branch, not the `throw`.

**Comment by wsshin** [comment]
@yuyichao  Why does the branch cause type instability and how can I work around it?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/17395#issuecomment-241911387

**Comment by wsshin** [comment]
Today I had an instance of similar type instability again, so I just revisited this thread and read #15276 and #17395.  However, it is still not clear to me how to work around this type instability.

The easiest solution for the example shown in this thread would be to not throw `ArgumentError`, but is that the only option?  Suppose I want to examine a function argument and throw an error depending on the properties of the argument (e.g., throw an error if a vector does not have a desired length).  What is the way to achieve this without causing the type instability described in this thread?
