### ISSUE TITLE
julia crashes without clear error message, when static parameter T does not occur within function

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaLang/julia#19339]
example codes are as follows
```
function foo{T<:Signed}(a::String, b::Vector{Int})
    println(a, b)
end
```
There are warning message for declaring functions like this.
 
but if you miss that warning, you might be confused when Julia crashes for calling
`foo("s", [10])`

![bugreport](https://cloud.githubusercontent.com/assets/7087745/20340309/472af094-ac24-11e6-8b9a-0e8f8b88c1ea.gif)

> Julia Version 0.5.0
> Commit 3c9d753 (2016-09-19 18:14 UTC)
> Platform Info:
>   System: NT (x86_64-w64-mingw32)
>   CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
>

**Comment by martinholters** [comment]
Dup of #18710.
