### ISSUE TITLE
Unique is not removing duplicate elements - hashing issue?

### ISSUE THREAD

**Issue by maximsch2** [JuliaLang/julia#19345]
I'm running a code similar to following (data: https://homes.cs.washington.edu/~grechkin/bugreport1.jld)
```julia
using JLD

type A1
    v1::String
    v2::String
end
type B1
    val::A1
    tag::String    
end

@load "bugreport1.jld" tmp_data2
Base.hash(x::A1) = hash((x.v1, x.v2))
Base.hash(x::B1) = hash((hash(x.tag), hash(x.val)))
import Base.==
==(x::B1, y::B1) = x.tag == y.tag && x.val.v1 == y.val.v1 && x.val.v2 == y.val.v2

@show tmp_data2 # 12 items in the array with last two duplicated

@show unique(tmp_data2[1:12]) # expect here that one of the last two entries will be removed

@show unique(tmp_data2[6:12]) # when I call it like this, last two items are actually deduplicated

# yet:
@show hash(tmp_data2[11]) == hash(tmp_data2[12]) # true
@show tmp_data2[11] == tmp_data2[12] # true
```
On Julia 0.5 and it looks like `unique` is not removing elements even though they are equal to each other and hash to the same value.

**Comment by yuyichao** [comment]
The hash isn't defined correctly.

**Comment by yuyichao** [comment]
And I can confirm that it's working with the correct `hash` and does not with the wrong hash definitions.

```jl
julia> using JLD

julia> type A1
           v1::String
           v2::String
       end

julia> type B1
           val::A1
           tag::String    
       end

julia> @load "bugreport1.jld" tmp_data2
1-element Array{Symbol,1}:
 :tmp_data2

julia> Base.hash(x::A1, h::UInt) = hash((x.v1, x.v2), h)

julia> Base.hash(x::B1, h::UInt) = hash((x.tag, x.val), h)

julia> import Base.==

julia> ==(x::B1, y::B1) = x.tag == y.tag && x.val.v1 == y.val.v1 && x.val.v2 == y.val.v2
== (generic function with 123 methods)

julia> tmp_data2
12-element Array{Any,1}:
 B1(A1("AREG","BRCA1"),"1")  
 B1(A1("ZNF750","TP63"),"2") 
 B1(A1("ZNF750","FLG"),"3")  
 B1(A1("EPHB6","ALB"),"4")   
 B1(A1("IFNB1","TLR7"),"5")  
 B1(A1("TLR7","IFNB1"),"6")  
 B1(A1("KRT20","CDX1"),"7")  
 B1(A1("MYLIP","TP53"),"8")  
 B1(A1("TBCE","IL1A"),"9")   
 B1(A1("ASPN","CTHRC1"),"10")
 B1(A1("CD34","MN1"),"11")   
 B1(A1("CD34","MN1"),"11")   

julia> unique(tmp_data2[1:12])
11-element Array{Any,1}:
 B1(A1("AREG","BRCA1"),"1")  
 B1(A1("ZNF750","TP63"),"2") 
 B1(A1("ZNF750","FLG"),"3")  
 B1(A1("EPHB6","ALB"),"4")   
 B1(A1("IFNB1","TLR7"),"5")  
 B1(A1("TLR7","IFNB1"),"6")  
 B1(A1("KRT20","CDX1"),"7")  
 B1(A1("MYLIP","TP53"),"8")  
 B1(A1("TBCE","IL1A"),"9")   
 B1(A1("ASPN","CTHRC1"),"10")
 B1(A1("CD34","MN1"),"11")   

julia> unique(tmp_data2[6:12])
6-element Array{Any,1}:
 B1(A1("TLR7","IFNB1"),"6")  
 B1(A1("KRT20","CDX1"),"7")  
 B1(A1("MYLIP","TP53"),"8")  
 B1(A1("TBCE","IL1A"),"9")   
 B1(A1("ASPN","CTHRC1"),"10")
 B1(A1("CD34","MN1"),"11")   
```

This is documented at http://docs.julialang.org/en/latest/stdlib/base/?highlight=hash#Base.hash

**Comment by maximsch2** [comment]
Ops, my bad. Thanks!

Does it ever make sense for a user to redefine `hash`? Getting a warning there would've been helpful.

**Comment by StefanKarpinski** [comment]
It's unfortunate that we can't prevent this or warn about it better, but I'm afraid that we can't currently do much else. It's certainly a concern for the future, however.

**Comment by maximsch2** [comment]
A somewhat insane suggestion might be to have `hash(x::T, h)` be a generated function that checks if x is a user-defined type and it has a `hash(x::T)` function and calls it with proper mixing. That would assume that user-defined hash is defined before the first time the dual argument hash is called, though, which might be a problem when it is not the case.

What is the reason for having `hash(x, h)` be a main function by the way? E.g.:
```julia
hash(x::Any, h:UInt64) = 3*hash(x) - h
hash(x::Any) = object_id(x)
```
instead of the current
```julia
hash(x::Any, h:UInt64) = 3*object_id(x) - h
hash(x::Any) = hash(x, zero(UInt64))
```

**Comment by StefanKarpinski** [comment]
How do you generically define the more general two-argument form of hashing in terms of the single-argument form?

**Comment by maximsch2** [comment]
What about this: ```hash(x::Any, h:UInt64) = hash_integer(hash(x), h)``` using `hash_integer` from hashing2.jl?
Of course, a better default mixing scheme can be devised, but is the current assumption that each user overloading two-argument `hash` is doing a really smart mixing?

**Comment by colinfang** [comment]
@maximsch2  Have you seen this? https://github.com/andrewcooke/AutoHashEquals.jl

**Comment by maximsch2** [comment]
@colinfang That's awesome, thanks for the pointer!

**Comment by StefanKarpinski** [comment]
@maximsch2, I believe that scheme has the problem that each value is hashed once as an object and then again as an integer, doubling the amount of work done to hash large objects. The user who overloads two-argument `hash` isn't expected to do anything all that clever: they're just supposed to use two-argument `hash` recursively on each essential component of a value.

**Comment by maximsch2** [comment]
@StefanKarpinski, fair enough. I did some experiments and there is a slight performance drop there (5-20% depending on the object), which can potentially be improved by using cheaper mixing function instead of `hash_integer`, but it wouldn't solve the problem similar to https://github.com/JuliaLang/julia/issues/12198. It sounds like the best case scenario would be to remove default `hash` for user-defined objects as #12198 suggests and then also throw a warning any time someone overrides single-argument version of hash (is this possible?).
