### ISSUE TITLE
isapprox behavior (bug?)

### ISSUE THREAD

**Issue by gragusa** [JuliaLang/julia#19353]
I just noticed the following behavior of `isapprox` (even considering floating point algebra arguments, I feel that the first argument should call should return `true`.

```julia
0.0 ≈ 4.440892098500626e-17
```
```
false
```

```julia
1+0.0 ≈ 1+4.440892098500626e-17
```
```
true
```

```julia
1+0.0-1 ≈ 1+4.440892098500626e-17-1
```
```
true
```

**Comment by yuyichao** [comment]
`isapprox` compares the relative difference.

```
julia> 1+4.440892098500626e-17-1
0.0
```

**Comment by colinfang** [comment]
@gragusa Check doc [here](http://docs.julialang.org/en/release-0.5/stdlib/math/?highlight=isapprox%20#mathematical-functions)
