### ISSUE TITLE
Chained assignment allowed with no effect when defining function

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#19368]
This syntax no error, but appears to completely ignore the `= y` part. Is this intended?

```julia
julia> f(x) = y = 1
f (generic function with 1 method)

julia> f(1)
1

```

**Comment by mauro3** [comment]
I don't think it is ignored.  Consider:
```
julia> let 
       y = 2
       f() = y = 1
       @show f()
       @show y
       end
f() = 1
y = 1
1
```

**Comment by nalimilan** [comment]
So it only has an effect if the variable is already defined? That means that chained assignment introduces a new scope? Sounds really weird to me, but maybe I'm missing something.

**Comment by yuyichao** [comment]
`f() = ...` is always same as `function f() ... end` so yes, a function always introduces a new scope.

**Comment by nalimilan** [comment]
Got it, so that's actually equivalent to `f(x) = (y = 1)`.

**Comment by tkelman** [comment]
worth clarifying somewhere in the docs?

**Comment by yuyichao** [comment]
[The first paragraph of the function doc](http://julia.readthedocs.io/en/latest/manual/functions/#functions)?

> There is a second, more terse syntax for defining a function in Julia. The traditional function declaration syntax demonstrated above is equivalent to the following compact “assignment form”:

**Comment by nalimilan** [comment]
That's fine, I had just interpreted this incorrectly, and I was wondering whether it could be a parsing bug.
