### ISSUE TITLE
file inclusion inside functions

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#19364]
Should "include" be allowed inside functions?

Suppose file "bar.jl" contains only
```
y=5
```

Then we have the following behavior:
```julia
julia> module M
          function main()
               include("bar.jl")
                x=3
                println("x is $x")
           end
           main()
           println("in module M y is $y")
           end # module
x is 3
in module M y is 5
M
```

So evaluation is in global scope of the current module (and no, it's not evaluated if `main` is not
invoked).

At the very least, the documentation ("evaluates the contents ... in the current context") is inadequate.

**Comment by JeffBezanson** [comment]
`include` is actually very similar to `eval`. Yes, the documentation should be improved to clarify that.

**Comment by RalphAS** [comment]
Documentation (as of v0.7-alpha) covers this now.

**Comment by martinholters** [comment]
I've been wondering whether we might want an `@include` macro that behaves more like inserting the given file in its place.

**Comment by StefanKarpinski** [comment]
Sure; open an issue if you think that's a feature we ought to have, @martinholters.
