### ISSUE TITLE
map lacks specializations for sparse matrices/vectors

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#19363]
`map` lacks specializations for sparse matrices/vectors (in contrast to `broadcast`):
```julia
julia> VERSION
v"0.6.0-dev.1234"

julia> @which map(sin, speye(4))
map(f, A::Union{AbstractArray,AbstractSet,Associative}) in Base at abstractarray.jl:1784

julia> @which map(sin, spzeros(4))
map(f, A::Union{AbstractArray,AbstractSet,Associative}) in Base at abstractarray.jl:1784

julia> @which map!(sin, speye(4))
map!{F}(f::F, A::AbstractArray) in Base at abstractarray.jl:1775

julia> @which map!(sin, spzeros(4))
map!{F}(f::F, A::AbstractArray) in Base at abstractarray.jl:1775
```
This lack results in poor performance (see https://github.com/JuliaOpt/JuMP.jl/issues/889). Ref. discussion in #7010. Best!

**Comment by stevengj** [comment]
It would be easy to add `map(f, args::AbstractSparseVector...) = broadcast(f, args..)` and `map(f, args::AbstractSparseMatrix) = broadcast(f, args)`, since I think the semantics of `map` and `broadcast` agree for multiple sparse-vector arguments or a single sparse-matrix argument.

**Comment by simonster** [comment]
The semantics do not agree if some but not all sparse vectors have only a single element. But it seems like we could handle this by first checking dimensions and then calling `broadcast` if they match.

**Comment by tkelman** [comment]
Do any existing map methods assume purity?

**Comment by Sacha0** [comment]
#19438 provided `map`/`map!` specializations for `SparseMatrixCSC`s (less a `map!(f, A::SparseMatrixCSC)` method), partially fixing this issue.

**Comment by tkelman** [comment]
assuming the rest was closed by https://github.com/JuliaLang/julia/pull/19690
