### ISSUE TITLE
Vectorization Regression on 0.6

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#19369]
I have a sample code [here](https://github.com/JaredCrean2/wave6d/blob/master/src/vectorization_sample.jl), where `blockLoop5_2_16` vectorizes using 0.4, but not on 0.6, and there is a corresponding slowdown in execution time.

0.4: (--check-bounds=no --math-mode=fast)
```
blockLoop timing:
  0.108555 seconds (1.70 k allocations: 93.875 KB)
  0.094948 seconds
```
versioninfo:
```
Julia Version 0.4.4-pre+35
Commit 1a9429e* (2016-02-12 13:21 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

0.6 (--check-bounds=no --math-mode-fast -O3)
```
blockLoop timing:
  0.126778 seconds
  0.123328 seconds
```

versioninfo:
```
Julia Version 0.6.0-dev.1288
Commit d2a19d8* (2016-11-20 04:16 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

(hilbertLoop5_2_16 doesn't vectorize in either case and can be ignored)

**Comment by JaredCrean2** [comment]
Bump

**Comment by oscardssmith** [comment]
Some basic poking makes it seem like an inlining thing, but I'm not sure.

**Comment by KristofferC** [comment]
I get:

0.4:
```
blockLoop timing:
  0.269882 seconds (1.70 k allocations: 93.875 KB)
  0.251356 seconds
hilbertLoop timing:
  0.412768 seconds (1.43 k allocations: 81.031 KB)
  0.387327 seconds
```

master:
```
blockLoop timing:
  0.258355 seconds
  0.254171 seconds
hilbertLoop timing:
  0.260094 seconds
  0.266345 seconds
```

can you confirm @JaredCrean2 and maybe add a benchmark?

**Comment by JaredCrean2** [comment]
I'll try to build the latest master later today and run the benchmark.  As a quick test, could you look at `code_native` and see if any `vmulp` instructions were generated?

**Comment by KristofferC** [comment]
Hmm, I see SIMD on 0.4 and not 0.6 but I can't see a speed difference between the two. Not sure how to interpret that.

**Comment by KristofferC** [comment]
After making sure the code on 0.4 was compiled for native architecture I do see a slowdown on master vs 0.4 so this issue is not fixed.

**Comment by JaredCrean2** [comment]
Thanks for checking.  What commit of 0.6 are you using?  I am having troubling building the latest master.

**Comment by KristofferC** [comment]
Built the latest master now without problems.

**Comment by vtjnash** [comment]
The difference is solved by `@simd ivdep`. That was the default in v0.4, but was found to be too surprising and unsafe, so now must be specified explicitly.

https://github.com/JaredCrean2/wave6d/pull/1/files
