### ISSUE TITLE
non-recursive macroexpand

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#19365]
Currently
```julia
macro foo(args...)
    args2 = do_something(args)
    quote
        @bar($(args2...))
    end
end
macroexpand(:(@foo arg1 arg2))
```
expands all the macros in the expression recursively. 

This makes debugging difficult if the expansion of the inner macro is a complicated expression.

It would be nice to have an alternative, possibly either called `macroexpand1`, or `macroexpand(expr, recursive=false)`, that would only expand the first level, similarly to [COMMON-LISP:MACROEXPAND-1](http://clhs.lisp.se/Body/f_mexp_.htm).

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/julia/pull/21662
