### ISSUE TITLE
32-bit backtrace problems failing tests

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#19360]
On 32-bit linux, backtrace problems are causing us to fail [this test](https://github.com/JuliaLang/julia/blob/c504a2478dd2c5cc83c432eb9f1f6fe1e4a134cb/test/replutil.jl#L267-L268).  Example:

On 64-bit OSX, attempting to take fractional powers of negative numbers errors out:
```
julia> (-1)^0.25
ERROR: DomainError:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
 in nan_dom_err at ./math.jl:257 [inlined]
 in ^(::Float64, ::Float64) at ./math.jl:464
 in ^(::Int64, ::Float64) at ./promotion.jl:194
```

And we get a nice error message due to [this inspection of our backtrace]().  Running the same on a 32-bit linux build, we get:
```
julia> (-1)^0.25
ERROR: DomainError:
 in nan_dom_err at ./math.jl:257 [inlined]
 in ^(::Float64, ::Float64) at ./math.jl:464
```

Problematic, but it gets the general point across.  The big problem is [this test in `test/replutil.jl`](https://github.com/JuliaLang/julia/blob/c504a2478dd2c5cc83c432eb9f1f6fe1e4a134cb/test/replutil.jl#L267-L268) that requires that "Exponentiation yielding..." message to be printed out.  This message is [generated in `base/replutil.jl`](https://github.com/JuliaLang/julia/blob/c504a2478dd2c5cc83c432eb9f1f6fe1e4a134cb/base/replutil.jl#L228-L231) in response to very specific backtraces.

Interestingly enough, if you purposefully catch a stacktrace of the above with `catch_stacktrace()`, you get enough information to trigger the conditions in the above error printing:

```
julia> stacktraces = nothing; try; (-1)^0.25; catch stacktraces = catch_stacktrace(); end
2-element Array{StackFrame,1}:
  in nan_dom_err at math.jl:257 [inlined]
  in ^(::Float64, ::Float64) at math.jl:464

julia> [(st.func, st.from_c) for st in stacktraces]
2-element Array{Tuple{Symbol,Bool},1}:
 (:nan_dom_err,false)
 (:^,false)
```

However, that's not what the error handling machinery does.  It instead passes in backtraces from somewhere, I'm not entirely sure where. If I use `catch_backtrace()`, I get a third, different answer which is missing some important functions:
```
julia> backtr = nothing; try; (-1)^0.25; catch backtr = catch_backtrace(); end
4-element Array{Ptr{Void},1}:
 Ptr{Void} @0x001d6207
 Ptr{Void} @0x001afe7c
 Ptr{Void} @0x001b0204
 Ptr{Void} @0x9077b217

julia> stacktr = [StackTraces.lookup(bt)[1] for bt in backtr]
4-element Array{StackFrame,1}:
  in rec_backtrace at stackwalk.c:84
  in record_backtrace at task.c:238
  in jl_throw at task.c:560
  in nan_dom_err at math.jl:257 [inlined]

julia> [(st.func, st.from_c) for st in stacktr]
4-element Array{Tuple{Symbol,Bool},1}:
 (:rec_backtrace,true)
 (:record_backtrace,true)
 (:jl_throw,true)
 (:nan_dom_err,false)
```

I take this to mean either the backtraces being printed are not garnered from `catch_backtrace()` as [this line of `task.jl`](https://github.com/JuliaLang/julia/blob/c504a2478dd2c5cc83c432eb9f1f6fe1e4a134cb/base/task.jl#L149) would lead me to believe, or that something is making the results of that call nondeterministic, as when I call it manually as above, I get nary a hint of the `^` function call.

In any event, we should probably fix this, if we can.

**Comment by tkelman** [comment]
Is this a recent regression or is it also a problem on 0.5?

**Comment by yuyichao** [comment]
This is with patched libunwind, patched llvm, debug info not stripped?

**Comment by yuyichao** [comment]
It basically seems that unwinding/debug info lookup is not working properly on your build. The `catch_stacktrace()` you show does not provide more info than the backtrace you show above and neither of them contains enough information to trigger the additional info printing.

I can't reproduce this with my local 32bit build and travis also seems find so this is most likely a build issue.

**Comment by staticfloat** [comment]
This is from a purely from-source build of Julia with the following make incantation:

```
make -j3 VERBOSE=1 TAGGED_RELEASE_BANNER="Official http://julialang.org/ release" JULIA_CPU_TARGET=pentium4 JULIA_CPU_CORES=4 JULIA_TEST_MAXRSS_MB=600 MARCH=pentium4
```

It appears that this issue is also present on 0.5.  Here's `versioninfo()`:
```
Julia Version 0.6.0-dev.1254
Commit 39778d8 (2016-11-17 07:43 UTC)
Platform Info:
  OS: Linux (i686-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by yuyichao** [comment]
The issue on the centos 5 system seems to be that the glibc returns `-1(ENOMEM)` for a stack address so libunwind refuses to access the base pointer for unwinding.......

**Comment by yuyichao** [comment]
From `mincore` manpage

> Before kernel 2.6.21, `mincore()` did not return correct information  for
> `MAP_PRIVATE` mappings,  or  for  nonlinear  mappings  (established using
> `remap_file_pages(2)`).

And the stack is hopefully privately mapped, causing the problem....
