### ISSUE TITLE
Problems documenting inner functions since 0.5

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#19386]
```julia
function addx(x)
  inner = (y) -> x + y
  @doc "`(y) -> $x + y`" -> inner
  return inner
end

function suby(y)
  @doc "`(x) -> x - $y`" -> inner(x) =  x - y
  return inner
end

add1 = addx(1)
add2 = addx(2)
sub1 = suby(1)
sub2 = suby(2)

display(@doc(add1))
display(@doc(add2))
display(@doc(sub1))
display(@doc(sub2))
nothing
```
`0.4.7`:
```
  (y) -> 1 + y
  (y) -> 2 + y
  (x) -> x - 1
  (x) -> x - 2
```
`0.5.0`..`0.6.0-dev.1293`:
```
WARNING: replacing docs for 'inner :: Union{}' in module 'Main'.
WARNING: replacing docs for 'inner :: Tuple{Any}' in module 'Main'.
  No documentation found.

  add1 is a Function.

  # 1 method for generic function "(::#1)":
  (::##1#2)(y) at /.../innerdoc.jl:2
  No documentation found.

  add2 is a Function.

  # 1 method for generic function "(::#1)":
  (::##1#2)(y) at /.../innerdoc.jl:2
  No documentation found.

  sub1 is a Function.

  # 1 method for generic function "(::inner)":
  (::#inner#3)(x) at /.../innerdoc.jl:8
  No documentation found.

  sub2 is a Function.

  # 1 method for generic function "(::inner)":
  (::#inner#3)(x) at /.../innerdoc.jl:8
```

**Comment by oscardssmith** [comment]
This isn't how we doc things anymore.

**Comment by fcard** [comment]
@oscardssmith Do you mean that since 0.5 you don't use a ObjectIdDict anymore and now use bindings? The `@doc` macro is still present so syntax-wise it's still very similar. Also I think it's still a bit weird that you "can" document inner objects despite it just creating documentation for global names, as I've eventually found out.

```jl
function add(x)
  @doc "$x" f(y) = x + y
end

function sub(y)
  @doc "$y" f(x) = x - y
end

add(1);
sub(2);
display(@doc(f));
```

Output (julia `1.8.2`):
```
  2
```

I feel like it should be possible to document local names, but if it's not something the team is interested in then it would be less confusing for this to simply not have any effect. (the simplest, possibly naive solution would be to make documentation a error/warning/no-op if the binding is available in local scope but not in global scope, i.e. `if @isdefined(x) && !isdefined(x)`)
