### ISSUE TITLE
Unable to load package modules when JULIA_PKGDIR is set on Windows 

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaLang/julia#19393]
Setting `JULIA_PKGDIR` on windows causes Julia to be unable to load installed packages.

When `JULIA_PKGDIR` is not set, I can do `Pkg.add("FactCheck"); using FactCheck`. When `JULIA_PKGDIR` is set (to a directory with read and write permissions) I can still add packages, but `using` and `import` fails with this message:
```
julia> using FactCheck
ERROR: ArgumentError: Module FactCheck not found in current path.
Run `Pkg.add("FactCheck")` to install the FactCheck package.
 in require(::Symbol) at .\loading.jl:365
```
The package is correctly cloned into `%JULIA_PKGDIR%\v0.5\FactCheck`. I can see that there is no `%JULIA_PKGDIR%\lib`.

I am using:
```
Version 0.5.0 (2016-09-19 18:14 UTC)
Official http://julialang.org/ release
x86_64-w64-mingw32
```
on a Windows Server 2012.

**Comment by nalimilan** [comment]
What's the contents of `JULIA_PKGDIR`? Does it contain non-ASCII characters by chance?

**Comment by vtjnash** [comment]
possibly fixed by https://github.com/JuliaLang/julia/pull/19291

**Comment by ulfworsoe** [comment]
@nalimilan No non-ASCII characters, no spaces: "`JULIA_PKGDIR=C:\Users\ulfw\juliapkg`"

@vtjnash It appears to have been fixed in the latest nightly. I'll just close this ticket.
