### ISSUE TITLE
"plot not defined" error

### ISSUE THREAD

**Issue by vinhqdang** [JuliaLang/julia#19395]
Hello all

I am very new to Julia and today I tried to start a very simple Julia program in Jupyter notebook (Ubuntu 16.04)

```
import DataFrames,Gadfly
p=plot(x=randn(2000), Geom.histogram (bincount=100))
```

and I have an error

``LoadError: UndefVarError: plot not defined``

I am using Julia 0.5.

What did I do wrong?

**Comment by andreasnoack** [comment]
Hi @vinhqdang. Please use https://discourse.julialang.org/ for questions like this.
