### ISSUE TITLE
Kernel continuously restarted in Mac OS X + Jupyter + Julia 0.5

### ISSUE THREAD

**Issue by vinhqdang** [JuliaLang/julia#19394]
Hello everyone

I am using Mac OS X 10.12.1

I downloaded Julia 0.5.dmg from the website, and put ``Julia-0.5.app`` into Applications folder.

Then I started julia-0.5 app, and typed:

``Pkg.add("Ijulia")``

The build failed at installing ``Nettle``.

I also installed ``jupyter`` 4.2.0 with anaconda (python 2.7)\

``conda install jupyter``

Now I used

``jupyter notebook``

and started a Jupyter notebook with julia as the kernel.

The problem now is the kernel will continuously restart. It reported that "the kernel about having die" and asked me to restart the kernel, and in fact I could not do anything.

What is the correct way to install IJulia and use it with Jupyter?

Thanks a lot,

**Comment by andreasnoack** [comment]
It looks like an issue with IJulia and not Julia. I'd recommend asking the question at https://discourse.julialang.org/ and, if the problem persists, file an issue at https://github.com/JuliaLang/IJulia.jl
