### ISSUE TITLE
Bind does not accept TCPSocket

### ISSUE THREAD

**Issue by kinoroy** [JuliaLang/julia#19406]
The documentation for bind says: it accepts "(socket::Union{UDPSocket, TCPSocket}, host::IPAddr, port::Integer; ipv6only=false)"

however in Julia 0.5 when running bind with a type "TCPSocket", you get the following error:

"ERROR: MethodError: no method matching bind(::TCPSocket, ::IPv4, ::UInt16)
Closest candidates are:
  bind(::Union{Base.TCPServer,UDPSocket}, ::IPAddr, ::Integer; ipv6only, reuseaddr, kws...) at socket.jl:404"

**Comment by laborg** [comment]
This has been fixed in https://github.com/JuliaLang/julia/pull/34556
