### ISSUE TITLE
Vararg's cannot be matched with function parameters

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#19400]
I'm pretty sure I've seen this discussed before but couldn't find an issue:

**Edit**: as @martinholters pointed out below, `f3` behaves as expected.  I'm unsure about `f1` though.
```julia
julia> f3{T}(::Tuple{Vararg{T}}) = T
f3 (generic function with 1 method)

julia> f3((2,"a"))
ERROR: MethodError: no method matching f3(::Tuple{Int64,String})
Closest candidates are:
  f3{T}(::Tuple{Vararg{T,N} where N}) at REPL[1]:1

julia> isa((2,"a"), Tuple{Vararg}) # my understanding was that this means that f3 should match
true

julia> f1{T<:Vararg}(::Tuple{T}) = 1
f1 (generic function with 1 method)

julia> f1((2,"a"))
ERROR: MethodError: no method matching f1(::Tuple{Int64,String})
Closest candidates are:
  f1{T<:Vararg}(::Tuple{T<:Vararg}) at REPL[7]:1

# without function type parameter it matches:
julia> f2(::Tuple{Vararg}) = 2
f2 (generic function with 1 method)

julia> f2((2,"a"))
2
```
Note this doesn't work either with the branch of #18457.

Related:  https://github.com/mbauman/Tuples.jl

**Comment by martinholters** [comment]
What would you `f3((2,"a"))` expect to return? Matching `T` against the first tuple entry would give `Int`, against the second would give `String`, hence no match. It's not different from `f{T}(::Vararg{T}) = T` or equivalently `f{T}(::T...) = T` not matching `f(2, "a")`, is it?

**Comment by mauro3** [comment]
That's a good point.  Running `f3((2,5))` returns `Int64`, as it should. 

But `f1` should still match, no?  However, the equivalent `isa` test for `f1` (on #18457) returns false and thus is consistent:
```
julia> isa((4,7), Tuple{T} where T<:Vararg)
false
```
What would the type `Tuple{T} where T<:Vararg` match?

**Comment by mauro3** [comment]
Also note that Vararg matching changed with #18457.  Before:
```
julia> f{T}(::Type{Tuple{T,Vararg}}) = T
f (generic function with 1 method)

julia> f(Tuple{Int,Int})
Int64
```
after
```
julia> f{T}(::Type{Tuple{T,Vararg}}) = T
f (generic function with 1 method)

julia> f(Tuple{Int,Int})
ERROR: MethodError: no method matching f(::Type{Tuple{Int64,Int64}})
Closest candidates are:
  f{T}(::Type{Tuple{T,Vararg}}) at REPL[2]:1
```
So before Vararg was covariant but now it is invariant. (note that in julia-0.4 it also throws a method-error).

Sorry, this issue is a bit a mess.  Let me know if I should do something about it.

**Comment by gtsotsos** [comment]
![add2int](https://cloud.githubusercontent.com/assets/15122982/20597895/9921c5da-b246-11e6-9402-aeda3306a66a.PNG)

I face the same issue since this morning. I think I upgraded Julia distro via apt-get last night.

Cheers,
Georgios

**Comment by martinholters** [comment]
@gtsotsos Everything is as it should in the output you posted (and I see no relationship to this issue). `add2Int(3, y=4)` does work, doesn't it?

**Comment by gtsotsos** [comment]
Thanks Martin. I does, i realized just a few seconds ago. I was about to delete my comment.

**Comment by JeffBezanson** [comment]
@mauro3 In that example it's not `Vararg` that's invariant but `Type`.

The case of `T<:Vararg` will be "fixed" by disallowing `Vararg` in typevar bounds. `Vararg` itself is not really a type; it is only part of the structure of a vararg tuple type.
