### ISSUE TITLE
plot() missing in Plots v0.10.1 

### ISSUE THREAD

**Issue by Rociocc93** [JuliaLang/julia#19417]
Hi!!

I just need to use the plot() function and have added the Plots package, updated it and written using Plots, but when I try to plot something this error message gets printed: 

UndefVarError: plot not defined

Anybody knows what might be happening here?

Thanks in advance!
Julia version: 0.5.9

**Comment by yuyichao** [comment]
Please use the [forum](https://discourse.julialang.org/) for questions and package issue tracker for package bugs.
