### ISSUE TITLE
@noinline ignored

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#19418]
It looks like Julia 0.6 ignores `@noinline` in the following snippet:

```julia
@noinline bar() = 1
function foo()
    bar()
end
@code_typed(foo())
```

Julia Version 0.5.0-dev+2349
Commit cf93d6f* (2016-01-29 02:19 UTC):
```
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[]], :(begin  # In[1], line 3:
        return (Main.bar)()::Int64
    end::Int64))))
```

Julia Version 0.6.0-dev.1297
Commit 416f5f2* (2016-11-23 13:12 UTC):
```
CodeInfo(:(begin 
        return $(QuoteNode(1))
    end))=>Int64
```

**Comment by yuyichao** [comment]
The pure+constant return logic bypasses noinline...

**Comment by damiendr** [comment]
OK, good to know. I was using noinline functions like these as a tag for introspection purposes, but I will find another way if that's the new logic.

**Comment by damiendr** [comment]
Won't this cause problems with #265 ?

**Comment by yuyichao** [comment]
This is unrelated to #265.

**Comment by nlw0** [comment]
Is this still the case? I am trying to implement a macro similar to how `@noinline` is supposed to work, but I'm no sure the code that arrives at `emit_function` in `codegen.cpp` really has the structure expected by `jl_has_meta`. I cannot make my macro work, and I guess it could be the same issue.

**Comment by nlw0** [comment]
If `@noinline` is still supposed to be propagated to LLVM then this would depend on https://github.com/JuliaLang/julia/issues/27104
