### ISSUE TITLE
wavplay() in WAV.jl does not work

### ISSUE THREAD

**Issue by Felix-Yan** [JuliaLang/julia#19412]
I tried to follow the example code given in https://github.com/dancasimiro/WAV.jl.
Below is the code I use:
julia> Pkg.add("WAV")
julia> using WAV
julia> x = [0:7999;]
julia> y = sin(2 * pi * x / 8000)
julia> wavplay(y,8000)

Then I get the error:
ERROR: MethodError: `convert` has no method matching convert(::Type{Cstring}, ::Ptr{Void})
This may have arisen from a call to the constructor Cstring(...),
since type constructors fall back to convert methods.

Not sure how to fix it.

**Comment by Felix-Yan** [comment]
The version is 0.4.3.

**Comment by yuyichao** [comment]
Please ask questions on the [forum](https://discourse.julialang.org/) or report incorrect example code on the package's issue tracker.
