### ISSUE TITLE
multipleDispatch for function extensions defined in modules (of subtypes)

### ISSUE THREAD

**Issue by kellertuer** [JuliaLang/julia#19420]
I'm having the following structure (planned and programmed today)

    module A
      abstract TypeA
      function myAlg(p::TypeA,q::TypeA)
        subTypeFun(p,q)
      end
    end #module A

where anybody who wants to use this on his own subtype does something like

    module B
      using A
      export subTypeFun
    
      type TypeB <:TypeA
      function subTypeFun(p::TypeB,q::TypeB)
        # do stuff required for this subtype and return a value
      end
    end #module B

or further on with a `module C` and so on such that any subtype can use `myAlg` by just implementing the `subTypeFun`. However, while these function signatures will definetly be distinct types, by ( I think) this thread https://github.com/JuliaLang/julia/issues/2327 only the last one “survives”, or to be precise loading

    include("A.jl")
    include("B.jl")
    include("C.jl")

would yield a warning `WARNING: ignoring conflicting import of C.subTypeFun into Main`

I thought the great advantage is multiple dispatch. How should I implement that if only one of my multiple dispatch versions survives the loading of my versions?
Or in other words: Whats the best practice for that, assuming that each of the subtypes provides roughly 5-10 methods implemented for them specifically and which should be employed in one `myAlg` afterwards? Maybe i'm just getting the theme to use wrong here...

**Comment by yuyichao** [comment]
You need to import a function to extend it. Please use https://discourse.julialang.org/ for further questions.

**Comment by kellertuer** [comment]
Thanks that hint at least made my programms running, will consult your link for further discussions.
