### ISSUE TITLE
Pkg.installed() misdocumented or misbehave

### ISSUE THREAD

**Issue by DANA-Laboratory** [JuliaLang/julia#19436]
Refer to [this doc paragraph](http://docs.julialang.org/en/release-0.5/stdlib/pkg/#package-manager-functions):

> installed(pkg) → Void | VersionNumber
> 
>     If pkg is installed, return the installed version number, otherwise return nothing.

and also this [relate QA](http://stackoverflow.com/questions/40826701/pkg-installedaninvalidpackage-should-return-nothing-or-throw-an-error):

`Pkg.installed("anInvalidPackage")` function should return `nothing` but it throws an error: 

    julia> VERSION
    v"0.5.0"
    julia> Pkg.installed("anInvalidPackage")
    ERROR: anInvalidPackage is not a package (not registered or installed)
     in installed(::String) at .\pkg\entry.jl:123
     in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#installed,Tuple{String}})
    () at .\pkg\dir.jl:31
     in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#installed,Tuple{String}
    }, ::String) at .\file.jl:48
     in #cd#1 at .\pkg\dir.jl:31
     in installed(::String) at .\pkg\pkg.jl:129

I think one of those, documentation or `Pkg.installed()` function behavior needs review.

**Comment by StefanKarpinski** [comment]
IIRC, this is intentional so this should be a doc fix:
- if the package is installed, return its version
- if the package exists but is not installed, return nothing
- if the package does not exist, raise an error.

**Comment by DANA-Laboratory** [comment]
same issue for `Pkg.available()`
related to: 
https://github.com/JuliaLang/julia/issues/18206

**Comment by alexmorley** [comment]
Related to  #19435 as well

**Comment by martinholters** [comment]
Yes.
