### ISSUE TITLE
Looking for immutable/constant Dict (and Array)

### ISSUE THREAD

**Issue by xianrenb** [JuliaLang/julia#19439]
I want to find an efficient way of using immutable/constant Dict or Array, as I find the following performance problem.
`julia> d = Dict{Symbol, Int64}()
Dict{Symbol,Int64} with 0 entries

julia> x = 2
2

julia> d[:a] = 3
3

julia> const ka = 3
3

julia> @time for i = 1:1000000
       if d[:a] == 3
       x = 2
       end
       end
  0.250152 seconds (3.48 k allocations: 166.690 KB)

julia> @time for i = 1:1000000
       if ka == 3
       x = 2
       end
       end
  0.007007 seconds

julia>
`
I believe Julia could optimize the constant ka in the code, but is there any way to put multiple similar constants in a dictionary or an array in which Julia could still generate optimized code?
Thank you.

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!

Regarding your question, see this: http://docs.julialang.org/en/stable/manual/performance-tips/#avoid-global-variables

**Comment by xianrenb** [comment]
I think it is a performance issue, or may be a feature request.
I just tried to write in a polite way.
Actually, I tried Base.ImmutableDict and const Dict, but it seems no improvement in processing time.

**Comment by yuyichao** [comment]
As mentioned, please continue this on the forum and not here.

**Comment by xianrenb** [comment]
I see why people start giving up on Julia.

**Comment by StefanKarpinski** [comment]
There was a polite request for you to ask this question in the appropriate forum, which you ignored. If you want to discuss this further, please do so by starting a thread at https://discourse.julialang.org.
