### ISSUE TITLE
Significant slowdown Julia 0.4 -> 0.5 ( and 0.6-dev)

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaLang/julia#19459]
I originally posted this bug to FactCheck, but I can see that the FactCheck has not changed between Julia 0.4 and 0.5/0.6-dev. The problem must be in Julia.

Following test runs in 8.5 seconds in Julia 0.4.5 and some 135 seconds in Julia 0.5.0 or 0.6.0-dev.1350):
https://gist.github.com/ulfworsoe/3f8c34d2d1998e4e2adce09d42855f64
* If I remove the `@ fact` and run the tests outside of the facts(...) do environment, it is nearly instantaneous. 
* If I make a loop inside the `facts(...) do` environment instead of repeating the lines, it is also nearly instantaneous.

Furthermore, in Julia 0.4 the slowdown seems to be linear in the number of lines with `@fact`, while in Julia 0.5/0.6-dev it appears to be closer to quadratic (or at least more and more expensive per line).

`@ profile` shows some very deep recursions in Julia 0.5 for this example, unlike in Julia 0.4.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15346 which isn't fully fixed.

**Comment by vtjnash** [comment]
This seems harder – the way cl-convert handles `method` declarations is `O(statements * declarations)` due to the need for `expr-find-all`. I don't think this can have such a trivial fix like the other case.
```
julia> ccall(:fl_show_profile, Void, ())
Function                     #Calls     Total Time (seconds)    Self Time (seconds)
--------                     ------     --------------------    -------------------
julia-expand1                73         265.696412563324        0.000270843505859375
closure-convert              73         262.8250417709351       5.173683166503906e-05
cl-convert                   101709     262.8249900341034       0.5684287548065186
map-cl-convert               33359      262.8246800899506       0.07861518859863281
expr-find-all                300807970  250.4162256717682       250.4162256717682
lambda-optimize-vars!        2177       11.09306049346924       11.09306049346924
analyze-variables!           73         2.254829168319702       2.254829168319702
lift-toplevel                973533     0.6682028770446777      0.6682028770446777
julia-expand-macros          143931     0.5433645248413086      0.5433645248413086
resolve-scopes               73         0.4038965702056885      0.4038965702056885
linearize                    2307       0.154111385345459       0.154111385345459
julia-expand0                73         0.08486819267272949     0.08486819267272949
renumber-slots-and-labels    75         0.05842781066894531     0.05842781066894531
--------                     ------     --------------------    -------------------
Total                                   266.3243532180786
```

**Comment by KristofferC** [comment]
Feels like this can be closed based on https://github.com/JuliaLang/julia/issues/15346#issuecomment-542122805.
