### ISSUE TITLE
Ternary operator twice as fast as if statement

### ISSUE THREAD

**Issue by vejitatoja** [JuliaLang/julia#19454]
I have noticed that using ternary operator instead If statement in an expression makes code execution 2 times faster and allocates only half the memory.

Is this intended? I couldn't find any information about this behavior in Julia manual.

```
function with_ternary()
  sum([x%3==0 || x%5==0 ? x : 0 for x=1:999])
end
@time with_ternary() 
0.015265 seconds (13.62 k allocations: 620.500 KB)
```
same thing using list comprehension syntax
```
function with_if()
  sum(x for x=1:999 if x%3 == 0 || x%5 == 0)
end
@time with_if()
0.035748 seconds (31.84 k allocations: 1.365 MB)
```

After runing this test many times to make sure that the results are consistent and trying to figure this out i have noticed that i was using the sum function incorrectly. I'm still learning and was playing only a bit with Python before so i didn't know it was possible to do:
```
function with_ternary2()
  (sum(x%3==0 || x%5==0 ? x : 0) for x=1:999)
end
@time with_ternary2()
0.002502 seconds (3.79 k allocations: 166.853 KB)
```
```
function with_if2()
  (sum(x) for x=1:999 if x%3 == 0 || x%5 == 0)
end
@time with_if2()
with_if2  0.004479 seconds (9.58 k allocations: 405.867 KB)
```
Using it this way makes both functions 10 times faster.
Ternary operator still makes it faster and allocates less memory

**Comment by mbauman** [comment]
You're not measuring the difference between the ternary operator and if expressions here.  Instead, you're measuring compile times. You need to call the function once before timing it to actually measure the computation.

While the actual computation is a minuscule part of the total time you're measuring here, it too is measuring three different things: comprehensions, generators, and generator creation. If you'd like to explore this further, please ask this question on the [discourse discussion board](http://discourse.julialang.org).

**Comment by yuyichao** [comment]
1. Please run the benchmark at least twice, you are benchmarking the compiler in all of them.
2. the ternary operator and the if statement you wrote are actually not the same.

And although @mbauman appears to beat me by a minute, please use the forum for further questions.

**Comment by vejitatoja** [comment]
Thank you for the explanation! That explains why it was using so much memory.
After making correct measurement (calling function 2 times before measuring with @time) it is still 2x faster to use ternary operator.
```
function with_ternary()
  sum(x%3==0 || x%5==0 ? x : 0 for x=1:999999999)
end
with_ternary()
with_ternary()
@time with_ternary()
2.184906 seconds (7 allocations: 240 bytes)
```
```
function with_if()
  sum(x for x=1:999999999 if x%3 == 0 || x%5 == 0)
end
with_if()
with_if()
@time with_if()
4.829896 seconds (12 allocations: 416 bytes)
```
I have posted that question on the board.

**Comment by yuyichao** [comment]
(OT: Please make sure to quote macros to avoid pinging random persons on github....)
