### ISSUE TITLE
inconsistent behavior of sub2ind

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaLang/julia#19453]
When sub2ind is called with a tuple as first parameter it gives the expected result:

```
julia> sub2ind((1,3),1,2)
2
```

however, when it is called with an array, I get in julia 0.5.0 the following:

```
julia> sub2ind([1,3],1,2)
3
```
This sounds like a bug to me.

**Comment by Gnimuc** [comment]
Another question is why `sub2ind` works fine when the subscript is out of bounds:
```julia
julia> sub2ind((1,3), 2,5)
6
```

**Comment by timholy** [comment]
If `A` is an array, then `sub2ind(A, i, j)` -> `sub2ind(indices(A), i, j)`.

Now that we have `@boundscheck`, it would be possible to add bounds-checking without killing performance in those places where `sub2ind` is used when bounds have already been checked.

**Comment by Alexander-Barth** [comment]
It seems that 

```
sub2ind([1,3],1,2)
```

is interpreted as 

```
sub2ind(size([1,3]),1,2)
```

In the same way that e.g. zeros handles array arguments

```
julia> zeros([2,3])
2-element Array{Int64,1}:
 0
 0

julia> zeros(size([2,3]))
2-element Array{Float64,1}:
 0.0
 0.0
```

It might just be a miss-understanding of my part. Maybe it would be useful to mention this in the documentation at:

http://docs.julialang.org/en/release-0.5/stdlib/arrays/

For example:

sub2ind(dims, i, j, k...) → index
The inverse of ind2sub, returns the linear index corresponding to the provided subscripts __for an array with the dimensions given by the of the tuple dims. If the first argument of sub2ind is an array, then its shape is used for the dimensions.__
