### ISSUE TITLE
Test for Java irrelevant

### ISSUE THREAD

**Issue by IRus** [JuliaLang/julia#19460]
Consider use of [JMH](http://openjdk.java.net/projects/code-tools/jmh/) for java performance tests. Also use latest stable JVM for tests.

**Comment by StefanKarpinski** [comment]
How would JMH affect performance? Is it just a matter of more precise measurement? We'll update the JVM next time we run the benchmarks.

**Comment by IRus** [comment]
Writing benchmarks right - is hard. I don't know if other languages have such thing like JMH, but in Java - JMH standard defacto for writing benchmarks. It's [covers](http://hg.openjdk.java.net/code-tools/jmh/file/b5cccfc59265/jmh-core/src/main/java/org/openjdk/jmh/infra/Blackhole.java#l241) [a lot of things](https://www.youtube.com/watch?v=VaWgOCDBxYw), which can be missed in code of developer. 

So:

> How would JMH affect performance? Is it just a matter of more precise measurement?

- JMH doesn't affect performance, it measure it with knowledge of JVM internals
- It's about measuring right on the JVM

> We'll update the JVM next time we run the benchmarks.

Thanks!

**Comment by StefanKarpinski** [comment]
So you're not saying that we're actually measuring Java performance wrong, just that using JMH is "the right way" to benchmark Java code? (Of course you need a framework in Java to time things.) Absent evidence that what we're timing is actually wrong, we're not going to make that change ourselves. Of course, if you want to submit a PR that changes the benchmark code to use JMH, that would be welcomed (assuming we can get it to compile and run without too much trouble).

**Comment by IRus** [comment]
Your benchmarks not necessary wrong, i say "they could be wrong, and please, use JMH for benchmarking".
Sure, i can send PR.

**Comment by IRus** [comment]
Moved to separate repo https://github.com/JuliaLang/Microbenchmarks/issues/33
