### ISSUE TITLE
task_done_hook has no InterruptException handler

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#19467]
Case 1:
```julia
function try_no_segfault()
    while true
        try
            sleep(1)
            println("trying...")
            # @async 1+1
        catch e
            if typeof(e) <: InterruptException
                println("caught Interrupt")
                return
            end
        end
    end
    return
end
```
Case 2:
```julia
function try_segfault()
    while true
        try
            sleep(1)
            println("trying...")
            @async 1+1
        catch e
            if typeof(e) <: InterruptException
                println("caught Interrupt")
                return
            end
        end
    end
    return
end
```

In the successful case, run `try_no_segfault()`, then CTRL+c to see a successful interrupt and return to the julia prompt.

To reproduce the segfault, run `try_segfault()`, then CTRL+c to see a segfault and end of the julia session.

**Comment by yuyichao** [comment]
Which version are you using? And is it actually a segfault?

**Comment by quinnj** [comment]
```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```
No, I'm not sure it's a segfault, but it does end my julia session instead of just exiting the function, and it seems to be purely because of the presence of the `@async` block.

**Comment by amitmurthy** [comment]
This may help in identifying the problem. Adding a `yield()` before the `sleep()` makes the problem go away.
```
        try
            yield()
            sleep(1)
            println("trying...")
            @async 1+1             
        catch e
``` 

Issue exists on 0.4 too.

**Comment by yuyichao** [comment]
The yield simply makes the window this can happen much smaller.

**Comment by amitmurthy** [comment]
There may be something more. I couldn't crash it with the yield() before the sleep() even after many tries. A yield() after the sleep() has no effect....

**Comment by yuyichao** [comment]
Well, it shortens the window from 1 second to few micro second so you'll have a pretty hard time triggering it.

**Comment by quinnj** [comment]
@yuyichao, any ideas on how to fix this?

**Comment by vtjnash** [comment]
This would be fixed by https://github.com/JuliaLang/julia/pull/14032

**Comment by StefanKarpinski** [comment]
Does changing the behavior of ctrl-C count as breaking production code?

**Comment by StefanKarpinski** [comment]
This doesn't seem like it needs to be in the 1.0 milestone. Speak up otherwise.

**Comment by arnaudh** [comment]
This is happening again, at least on Julia 1.9.0 and 1.8.3 (see https://github.com/JuliaLang/julia/issues/45055, which probably should be closed as duplicate if this is reopened).
