### ISSUE TITLE
No cov(::AbstractMatrix, ::Bool) method

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#19471]
Currently `cov(x, false)` fails when `x` is a matrix rather than a vector: you need to use `cov(x, 1, false)`. This is annoying since 1) the docstring appears to imply the both arguments are optional, and 2) it makes it harder to find the replacement for the deprecated `cov(x, corrected=false)` method.

Is this just an oversight?

Cf. https://discourse.julialang.org/t/what-is-the-current-best-practice-for-population-formula-for-cov/658

**Comment by andreasnoack** [comment]
There might be some cleanup left after the removal of the keyword arguments. However, we should think of this with https://github.com/JuliaLang/julia/issues/19451 in mind. We have very few functions left that defaults to `dim=1` so we should consider deprecating the `cov(Matrix)` method.

**Comment by nalimilan** [comment]
Right. Maybe the best thing to do is improving the deprecation warning.

**Comment by nalimilan** [comment]
`cov` now takes a `corrected` keyword argument.
