### ISSUE TITLE
Julia 0.5 incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#19474]
Specifically libgit2 v0.24.3 is incompatible with openssl 1.1.0. Compiling libgit2 with openssl 1.1.0 installed results in the error:

```
/usr/local/julia/deps/srccache/libgit2-211e117a0590583a720c53172406f34186c543bd/src/openssl_stream.c:217:19: error: storage size of 'git_stream_bio_method' isn't known
 static BIO_METHOD git_stream_bio_method = {
                   ^~~~~~~~~~~~~~~~~~~~~
```

Problem would be resolved by backporting #18658 which avoids using openssl 1.1.0. Alternatively, we could update the version of libgit2 to [v0.25.0-rc1](https://github.com/libgit2/libgit2/commit/7175222ce63ef61749cc00a1f29d11d098bd28a8) which is compatible with openssl 1.1.0 but would require some changes to the Julia libgit2 interface.

**Comment by tkelman** [comment]
I believe libgit2 plans on backporting and releasing a version of 0.24 that will be compatible

**Comment by iamed2** [comment]
The backport PR lives here: https://github.com/libgit2/libgit2/pull/4012 and AFAICT hasn't seen attention since it was created.
