### ISSUE TITLE
Give system image and .ji files cpuid-specific names if architecture is not specified

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#19481]
It is fairly common in HPC environment to have julia be installed on a network file system, with the actual CPU architecture, changing depending on compute nodes. It would be nice to add a flag to build cpuid-specific binaries and caches (or perhaps even do this automatically if no target architecture is specified), that are allowed to coexist (e.g. name the system image `sys-50670.so`).

**Comment by vtjnash** [comment]
see also https://github.com/JuliaLang/julia/pull/14995

**Comment by vtjnash** [comment]
fixed by https://github.com/JuliaLang/julia/pull/19486, but github didn't autodetect that
