### ISSUE TITLE
ObjectIdDict exported but not documented

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#19498]
This type (which I guess is supposed to hash things so that if I insert two references to the same object, that's not allowed?) has no docs at all.

**Comment by mauro3** [comment]
To nit-pick: there is one tiny bit in the manual: "ObjectIdDict is a special hash table where the keys are always object identities."

**Comment by kshyatt** [comment]
Ok, but if I go into help mode in the REPL there's nothing.
