### ISSUE TITLE
Unnecessary memory allocation when adding arrays in place

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#19495]
Can you please confirm this is a candidate for optimization?

```
julia --track-allocation=user --inline=yes foo.jl
```

```julia
        - function foo()
        -   B = zeros(100,100)
   160304   A = ones(100,100)
        0   for i in 1:10
   801120     B += A
        -   end
        - end
```

I have a package that is allocating gigabytes of data in a loop because of this behavior. Is the allocation necessary?

**Comment by yuyichao** [comment]
No this is not a candidate for optimization but there will be better syntax sugar for the manually optimized verion.

**Comment by nalimilan** [comment]
More precisely, the syntactic sugar will be `.+=`, but you can already use `B[:] += A[:]`.

Anyway, please use the Discourse forum for questions.

**Comment by Sacha0** [comment]
`B[:] += A[:]` (`bar` below) will also allocate unnecessarily. Prior to 0.6, consider `baz` below instead. Best!
```julia
julia> VERSION
v"0.6.0-dev.1362"

julia> using BenchmarkTools

julia> function foo()
           B = zeros(100, 100)
           A = ones(100, 100)
           for i in 1:10
               B += A
           end
           return B
       end
foo (generic function with 1 method)

julia> function bar()
           B = zeros(100, 100)
           A = ones(100, 100)
           for i in 1:10
               B[:] += A[:]
           end
           return B
       end
bar (generic function with 1 method)

julia> function baz()
           B = zeros(100, 100)
           A = ones(100, 100)
           for i in 1:10, I in eachindex(B)
               B[I] += A[I]
           end
           return B
       end
baz (generic function with 1 method)

julia> @benchmark foo()
BenchmarkTools.Trial:
  memory estimate:  938.44 kb
  allocs estimate:  24
  --------------
  minimum time:     94.439 μs (0.00% GC)
  median time:      148.297 μs (0.00% GC)
  mean time:        292.860 μs (26.99% GC)
  maximum time:     3.557 ms (75.61% GC)
  --------------
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark bar()
BenchmarkTools.Trial:
  memory estimate:  2.44 mb
  allocs estimate:  64
  --------------
  minimum time:     287.892 μs (0.00% GC)
  median time:      467.607 μs (0.00% GC)
  mean time:        827.361 μs (26.66% GC)
  maximum time:     3.960 ms (68.87% GC)
  --------------
  samples:          6025
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark baz()
BenchmarkTools.Trial:
  memory estimate:  156.41 kb
  allocs estimate:  4
  --------------
  minimum time:     105.151 μs (0.00% GC)
  median time:      114.286 μs (0.00% GC)
  mean time:        142.825 μs (8.95% GC)
  maximum time:     2.714 ms (93.37% GC)
  --------------
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

**Comment by juliohm** [comment]
By using the proposed syntax `A[:] += B[:]` I still have gigabytes of data allocated in my package. This is what I have currently after trying the different approaches: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L259

The garbage collector is responsible for 50% of the time and 240GB are allocated for just one example according to the `@time` macro.

**Comment by yuyichao** [comment]
`broadcast!(+, A, A, B)`. Before there's a syntax for it.

**Comment by juliohm** [comment]
Thank you @yuyichao the trick improved the performance already, the code is becoming unreadable though: :https://github.com/juliohm/ImageQuilting.jl/commit/91d0c61f576e3557af1c44998ed7b07f6cd452fd

I still have one line for which unnecessary copies are being made: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L364 Any ideas of why this is the case?

**Comment by KristofferC** [comment]
Maybe https://github.com/simonbyrne/InplaceOps.jl can help to make stuff look nicer.

**Comment by juliohm** [comment]
Thank you for sharing @KristofferC, good to know these issues are being tackled somewhere already. I wish they become part of Julia soon.

Currently this is the transformation I am doing to get the desirable performance:

```julia
# intuitive and slow
A += B[1:100,1:100,1:100]

# unnecessarily complex and fast
broadcast!(+, A, A, view(B,1:100,1:100,1:100))
```
