### ISSUE TITLE
track-allocation reporting wrong lines in 0.5.0

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#19502]
I ported my code from 0.4.6 to 0.5.0 and found a 60x slowdown in performance.  According to `@time`, at least one issue is huge additional memory allocation.  (I will probably open another issue when I finally find the cause of the slow-down.) Unfortunately, `--track-allocation=user` is not working on my code (0.5.0 released, Windows 10); it is reporting the wrong line number in my source code.   so I am having difficulty finding the problem. Here is an excerpt from the .mem file,

```
        - function update_statehist!(statehist, maprelabs, x, nnode, spacedim,
        -                            ubc, tind, deltat, massmat, ::BackwardEuler)
        -         
        -     uhist = statehist[:uhist]
        -     vhist = statehist[:vhist]
        -     umid0 = maprelabs * x
        -     umid = reshape(umid0, spacedim, nnode)' + ubc
        -     uhist[:, :, tind] = umid
        -     vhist[:, :, tind] = (umid - uhist[:,:,tind-1]) / deltat
        0     error("reached update_statehist for BackwardEuler")
79585871469     nothing
        - end
```
Note that the marked statement is never executed; in fact, the entire function is never invoked.   The --track-allocation feature of 0.4.6 seems to work fine on this same code.

**Comment by yuyichao** [comment]
Does it have the same problem on master?

**Comment by StephenVavasis** [comment]
I downloaded the 0.6.0-dev 0-day master and installed all the packages I use and re-ran the code.  It appears that the memory allocation problem is fixed in 0.6.0-dev as well as the `track-allocation=user` bug mentioned in my previous post.  However, there is still a very significant performance problem (20x slow-down) with my code in 0.6.0-dev, so the overall problem is not resolved yet.

**Comment by StephenVavasis** [comment]
Yichao,

May I ask why you closed this issue?  Even though track-allocation=user appears to be working in 0.6.0-dev, it is not working in 0.5.0.  I assume that the Julia developers are still fixing issues in 0.5, or has it been abandoned for work on 0.6?

-- Steve

**Comment by yuyichao** [comment]
The fix is not really backportable.

**Comment by yuyichao** [comment]
Also, these options are never supposed to work on <= 0.5 without turning off inlining.
