### ISSUE TITLE
@inbounds has a problem with simple functions

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#19521]
This works:

f(A) = @inbounds return A[1]

This doesn't:

f(A) = @inbounds A[1]

[Full functions work, not sure if "simple" functions have that name or some other, I mean the syntax, not the body.]

I thought I should report just in case: I was just testing some stuff, maybe @inbounds isn't supposed to work there and/or this is a known issue:

help?> @inbounds

  Base.@inbounds is a macro.

  # 1 method for macro "@inbounds":
  @inbounds(blk::ANY<:Any) at essentials.jl:144

**Comment by PallHaraldsson** [comment]
I see now, that full functions only work with return, the issue is there also if I drop return (that should always be optional?).

[I would have edited my original comment and title, but I'm using a new browser (for me) Netsurf, and it's not very capable..]

**Comment by martinholters** [comment]
Yes, `@inbounds expr` does not  itself return the return value of `expr`. You can also not do e.g. `f(@inbounds x[1])`.

Can we just do the following?
```
--- a/base/essentials.jl
+++ b/base/essentials.jl
@@ -160,8 +160,9 @@ end
 
 macro inbounds(blk)
     :($(Expr(:inbounds,true));
-      $(esc(blk));
-      $(Expr(:inbounds,:pop)))
+      ret=$(esc(blk));
+      $(Expr(:inbounds,:pop));
+      ret)
 end
 
 macro label(name::Symbol)
```

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/18859.

Fixed by https://github.com/JuliaLang/julia/pull/15558

**Comment by ararslan** [comment]
As an aside, it's best to surround issue code in backticks, as it ensures that the macro syntax doesn't ping a random user.
