### ISSUE TITLE
Re-enable doctests

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaLang/julia#19528]
Doctests were disabled in #18588 since Documenter is a bit more strict in what is allowed to pass in a doctest. This issue is just to track their current status, I'm currently working on reactivating them ASAP. If anyone is curious enough to try them out now to see what's failing then you should be able to just run

```
make -C doc doctest
```

from the root directory. Currently you'll get a lot of errors, but from the looks of them they are mostly just whitespace issues that shouldn't be too much trouble to sort out.

**Comment by tkelman** [comment]
disabled in what way? they still run if you ask for them, and we never ran them by default

**Comment by MichaelHatherly** [comment]
Yes, they won't run each time the docs are built, so that hasn't changed really. Currently they will fail if you try to run them though, but I'd like to get them into a state where they can just be run by default whenever the docs get built.

**Comment by MichaelHatherly** [comment]
Seems to have crept in during a rebase. I think I know the cause, will try to fix later today.
