### ISSUE TITLE
download function not working on Windows

### ISSUE THREAD

**Issue by jecs** [JuliaLang/julia#19526]
Hi. I installed julia-0.5 on Windows Server 2008 R2 SP1 via the installer. Once that was finished, I added `WinRPM` and fixed it by removing the malformed URLs from its _deps/build.jl_. Then I installed `curl` via `WinRPM` and added the `WinRPM` directory to Julia's path via _.juliarc.jl_ in my home directory. When I open up Julia and enter the shell, `curl` executes, but when I try to use the `download` function, I get the following error:

```
ERROR: automatic download failed (error: 2148270088): https://cdn.plot.ly/plotly
-latest.min.js
 in download(::String, ::String) at .\interactiveutil.jl:505
 in download(::String) at .\interactiveutil.jl:534
```

Here's my `versioninfo`:
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2687W 0 @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

Edit: I should add that I created a firewall exception for julia, so I don't think that the system firewall is the issue.

**Comment by tkelman** [comment]
`Base.download` on Windows doesn't use curl, so that part isn't necessary. It uses a ccall to `URLDownloadToFileW`, which we've seen in the WinRPM package can frequently have issues with Windows Server security settings. There's some download security setting, I'm not sure the exact name, that makes this API call error out.

**Comment by tkelman** [comment]
Would probably be more reliable, usually have been telling people to use `BinDeps.download_cmd` but may as well refactor it here and see how it goes. xref https://github.com/JuliaLang/BinDeps.jl/issues/135

**Comment by pszufe** [comment]
I found out that the above error can be avoided by turning off "IE Enhanced Security Configuration" (ESC). What is interesting  ESC allows to install some Julia packages but blocks others. Turning off the ESC setting seems to be a reasonable workaround (tested on Julia 0.6.0 being run on Windows Server 2016). 
P.S.
I just run into this post when Googling for "automatic download failed" on Windows Server so hopefully my post will be useful for others.

**Comment by JeffBezanson** [comment]
Just ran into this in a secure windows environment. Replacing the syscall with ```run(`curl -o $filename -L $url`)``` works. Would it make sense to try using `curl` if we get this error?

**Comment by SimonDanisch** [comment]
I think you can't rely on curl being available on windows - or do you plan to ship it with Julia?

**Comment by tkelman** [comment]
The curl executable isn't included in the julia distribution or likely to be present on most windows installs. Wherever you ran happened to have one, but that was from something else and can't be relied on.

**Comment by JeffBezanson** [comment]
I know that, which is why I suggested just trying it as a fallback method. As it is, on these systems `download` *does not work at all*, so keeping the current situation unchanged is hardly the pinnacle of reliability.

**Comment by tkelman** [comment]
Better to replace it with something that's always present than something that's not.

**Comment by StefanKarpinski** [comment]
We wouldn't have all these fallbacks if there was something that was always present everywhere.

**Comment by tkelman** [comment]
There are no fallbacks whatsoever in the windows implementation of this function. There also don't need to be, given powershell is always present on every supported windows version.

**Comment by JeffBezanson** [comment]
Ah, now I remember going through all this 2 years ago :-) I'll try to import the logic from bindeps.

**Comment by tkelman** [comment]
Uh, scroll up. Reopen and rebase https://github.com/JuliaLang/julia/pull/21968.
