### ISSUE TITLE
Can you please explain this error in julia function?

### ISSUE THREAD

**Issue by rahulmankare** [JuliaLang/julia#19520]
it shows error in line shows in bold text, the error is-
LoadError: MethodError: no method matching Array{Float64,N}(::Float64, ::Float64)
Closest candidates are:
  Array{Float64,N}{T}(::Any) at sysimg.jl:53
 while loading C:\Users\admin\Desktop\new julia program\runit1.jl, in expression starting on line 302

function search_roots(kz,win)
omr_lo=win[1];
  omr_hi=win[2];
  omi_lo=win[3];
  omi_hi=win[4];
  N=win[5];
  omr=omr_lo:(omr_hi-omr_lo)/N:omr_hi;
  omi=omi_lo:(omi_hi-omi_lo)/N:omi_hi;
  X=meshgridx(omr,omi);
  Y=meshgridy(omr,omi);
  zi=X+im*Y;
  **Z=zeros(N+1,N+1);**
  Z_curv=zeros(N+1,N+1);
  for ii=1:N+1
      for jj=1:N+1
      Z[ii,jj]=disp_bwo(kz,zi[ii,jj]);
      Z_curv[ii,jj]=abs(Z[ii,jj]);
      end
  end

**Comment by KristofferC** [comment]
`N` is a Float64 but should be an `Int` if you want to use the `zeros` function.

Please redirect further questions to the discussion forum: discourse.julialang.org

**Comment by rahulmankare** [comment]
N is a float64 value but getting same error again and again.

**Comment by rahulmankare** [comment]
ok fine
