### ISSUE TITLE
"divmod" version for floats [Feature request]

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [JuliaLang/julia#19525]
it would be nice to have a build in function like this:
```
function fun(x)
    i = floor(Int,x)
    di = x - i
    return (i,di)
end
x = 1.5
(i,di) = fun(x)
#  "i"  is 1
# "di" is 0.5
```
As far as I know, there is no such function. There should be a way to efficiently implement it.

**Comment by AlexanderKoshkarov** [comment]
and probably this one also
```
function fun2(x)
    i = ceil(Int,x)
    di = i - x
    return (i,di)
end
x = 1.5
(i,di) = fun2(x)
#  "i"  is 2
# "di" is 0.5
```

**Comment by ararslan** [comment]
I believe what you're looking for is `modf`: http://docs.julialang.org/en/release-0.5/stdlib/math/#Base.modf

**Comment by oscardssmith** [comment]
I understand that modf is the name Julia went with because C, Python and probably others, but divmod is a way better name for this and it would be kind of nice if the same function had the same name regardless of your input types.

**Comment by AlexanderKoshkarov** [comment]
neat, thanks!

**Comment by musm** [comment]
@oscardssmith agreed

**Comment by StefanKarpinski** [comment]
I don't much care for the name `modf` either, but I would expect a function named `divmod` to compute `div` and `mod`, i.e. `(x,y)->(div(x,y), mod(x,y))`. Of course, that's the wrong pairing, which is why we have `divrem` and `fldmod`.
