### ISSUE TITLE
0-Dimensional Arrays

### ISSUE THREAD

**Issue by jecs** [JuliaLang/julia#19532]
Hi.

I apologize if this has been asked before, but I'm a bit confused by 0-dimensional arrays.

You can access the elements of a 1D array via the syntax `x[k]`, of a 2D array via `x[k,l]` or `x[k]`, and so on. But a 0D array is nothing more than a scalar, or as implemented, a 1D array of constant length 1. Wouldn't it make more sense for 0D arrays to be equivalent to their elements types, i.e. `Array{Float64,0} ≡ Float64`? Is there a reason for allowing 0D arrays?

**Comment by StefanKarpinski** [comment]
It would be best to ask this sort of question on https://discourse.julialang.org.

**Comment by jecs** [comment]
@StefanKarpinski Cool. Thanks for pointing me to that site.

**Comment by ararslan** [comment]
Note that Discourse is mentioned as the place to ask questions in the autopopulated text when you open a new issue.

**Comment by jecs** [comment]
Oh, in the wall of text? Whoops.
