### ISSUE TITLE
`make install` do not respect to `JULIA_BUILD_MODE`

### ISSUE THREAD

**Issue by iblis17** [JuliaLang/julia#19549]
Hi,
I tried to build with `JULIA_BUILD_MODE=release` but got debugging related binary after `make install`. Hope following patch can fix this.

```diff
diff --git a/Makefile b/Makefile
index 8ff57b03b..864f0fb78 100644
--- a/Makefile
+++ b/Makefile
@@ -316,8 +316,7 @@ define stringreplace
        $(build_depsbindir)/stringreplace $$(strings -t x - $1 | grep '$2' | awk '{print $$1;}') '$3' 255 "$(call cygpath_w,$1)"
 endef

-install: $(build_depsbindir)/stringreplace
-       @$(MAKE) $(QUIET_MAKE) all
+install: $(build_depsbindir)/stringreplace default
        @$(MAKE) $(QUIET_MAKE) docs
        @for subdir in $(bindir) $(libexecdir) $(datarootdir)/julia/site/$(VERSDIR) $(docdir) $(man1dir) $(includedir)/julia $(libdir) $(private_libdir) $(sysconfdir); do \
                mkdir -p $(DESTDIR)$$subdir; \
```

**Comment by tkelman** [comment]
install should always build both release and debug

**Comment by iblis17** [comment]
Is there any way install `release` binaries only

**Comment by ararslan** [comment]
`make release`?

**Comment by iblis17** [comment]
@ararslan  hmm... `make all` implies `make debug release`. Those targets won't install anything to `DESTDIR`. Seems only `install` target will setup some dir in `DESTDIR` and install binaries, docs, ... etc properly. 

Is there any reason make user need to build and install debug related objects into system?

**Comment by nalimilan** [comment]
Conversely, is there any (strong) reason not to?

**Comment by iblis17** [comment]
I think this should be optional not forced. For an end user, obviously, they do not need the debug build, even someone will strip them during installation. It just wastes time, space or bandwith (while distributing/deploying).

----

patch v2:
```diff
diff --git a/Makefile b/Makefile
index 8ff57b03b..086e195b9 100644
--- a/Makefile
+++ b/Makefile
@@ -316,8 +316,7 @@ define stringreplace
 	$(build_depsbindir)/stringreplace $$(strings -t x - $1 | grep '$2' | awk '{print $$1;}') '$3' 255 "$(call cygpath_w,$1)"
 endef
 
-install: $(build_depsbindir)/stringreplace
-	@$(MAKE) $(QUIET_MAKE) all
+install: $(build_depsbindir)/stringreplace default
 	@$(MAKE) $(QUIET_MAKE) docs
 	@for subdir in $(bindir) $(libexecdir) $(datarootdir)/julia/site/$(VERSDIR) $(docdir) $(man1dir) $(includedir)/julia $(libdir) $(private_libdir) $(sysconfdir); do \
 		mkdir -p $(DESTDIR)$$subdir; \
@@ -399,10 +398,14 @@ else ifeq ($(OS), Linux)
 endif
 
 	# Overwrite JL_SYSTEM_IMAGE_PATH in julia library
+ifneq (,$(findstring release,$(JULIA_BUILD_MODE)))
 	$(call stringreplace,$(DESTDIR)$(libdir)/libjulia.$(SHLIB_EXT),sys.$(SHLIB_EXT)$$,$(private_libdir_rel)/sys.$(SHLIB_EXT))
+endif
+ifneq (,$(findstring debug,$(JULIA_BUILD_MODE)))
 	$(call stringreplace,$(DESTDIR)$(libdir)/libjulia-debug.$(SHLIB_EXT),sys-debug.$(SHLIB_EXT)$$,$(private_libdir_rel)/sys-debug.$(SHLIB_EXT))
 endif
 
+endif
 	mkdir -p $(DESTDIR)$(sysconfdir)
 	cp -R $(build_sysconfdir)/julia $(DESTDIR)$(sysconfdir)/
 ```

**Comment by tkelman** [comment]
No. The install should be as close to the contents of binaries as possible. We ship a debug build of julia by default because it's not straightforward to create one without a source build, and it doesn't take all that much space. If you're repackaging Julia you can modify the contents however you'd like, but I don't think we should be changing the default configuration here.
