### ISSUE TITLE
Inlining + bounds check issue

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#19554]
On master, the program
```jl
type BugType{T}
    m::Array{T}
end

function f(x)
    for i in 1:length(x.m)
        x.m[i] = x.m[i]
    end
    x
end

f(BugType{Float64}(randn(2,2)))
```
gives the error
```jl
ERROR: BoundsError: attempt to access 2×2 Array{Float64,2} at index [3]
 in f(::BugType{Float64}) at ./REPL[2]:3
```
but only with inlining on. Removing `T` also makes the error go away.

The error was introduced in 9f531d9a79f83daa9e888f15d94f817d22647c08.

cc: @MatthiasJReisinger

**Comment by yuyichao** [comment]
Reduced to
```jl
gm = rand(2, 2)

function f()
    (gm::Array{Float64})[3]
end
f()
```

Likely a codegen issue.

**Comment by yuyichao** [comment]
Caused by https://github.com/JuliaLang/julia/commit/9f531d9a79f83daa9e888f15d94f817d22647c08
