### ISSUE TITLE
Julia still tries to precompile even if disabled if previous cache still exists

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#19557]
This is a problem that I have received quite a few bug reports for in the Gitter chats for DifferentialEquations.jl. What happened is DiffEqProblemLibrary.jl (a dependency) used to be precompile-friendly, but it is now not precompile friendly. Therefore the newest version does not have `__precompile__()`.

However, users who have a previous version of the package get a segfault when they update. What happens is the package for some reason wants to update the precompile cache file that exists, even though precompilation is disabled on the newest version.

This has an easy fix: delete the precompile cache `.julia/lib/_____` matching the package name and it won't try to precompile anymore, but it can be to track down that this is the issue (it may only segfaulting because it's precompiling code that should be precompile-safe).

**Comment by vtjnash** [comment]
Use '__precompile__(false)' to disable precompilation

**Comment by StefanKarpinski** [comment]
@vtjnash: is that intended as a workaround or the correct solution?

**Comment by vtjnash** [comment]
Correct solution.

**Comment by StefanKarpinski** [comment]
Close then?

**Comment by musm** [comment]
fwiw I have been tripped by this in the past
