### ISSUE TITLE
empty loop in cholmod test

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#19583]
In `test/sparse/cholmod.jl`:

```
let # Issue 9160

    for Ti in CHOLMOD.ITypes.types
        for elty in CHOLMOD.VRealTypes.types
 ```

`VRealTypes.types` is intended to be the list of types in a union. By bad luck, both union types and DataTypes have a `.types` field, and `VRealTypes` is actually just the `Float64` type. Therefore `VRealTypes.types` is empty, and the loop doesn't execute. Fixing that reveals some failures that go beyond my knowledge of the cholmod code.

Noticed on my branch, where union types don't have a `.types` field any more (which, happily, will prevent this issue in the future).

**Comment by ViralBShah** [comment]
close this?

**Comment by tkelman** [comment]
the PR fixing it wasn't merged yet, it'll auto-close
