### ISSUE TITLE
`@printf` does not accept `*` to specify field width

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#19582]
I want to use this `printf` specification:
```Julia
@sprintf "%0*d" len id
```
This should format the integer `id` using `len` digits, filled with `0` characters. The C printf supports the `*` specifier. Julia should offer an equivalent feature.

**Comment by quinnj** [comment]
I think this would be much easier to do now that https://github.com/JuliaLang/julia/pull/32859 is merged; it updates all the Printf code to use more modern dispatch patterns rather than relying on an insane amount of straight code generation.

**Comment by johanmon** [comment]
I added this:
https://github.com/JuliaLang/julia/pull/40105

**Comment by laborg** [comment]
This works now:
```
julia> @sprintf "%0*d" 5 42
"00042"
```
