### ISSUE TITLE
Suggestion: Extend Pkg.add() to add multiple packages at once

### ISSUE THREAD

**Issue by miguelraz** [JuliaLang/julia#19591]
I've searched for this topic on the Discourse, github/issues and the google alert group, but couldn't find a relevant or prior discussion. If you know of one, would like to know about it. Thanks!

**Suggestion:**
Extend functionality of Pkg.add() so that you can add multiple packages at once.

e.g.
`julia > Pkg.add("IJulia", "Combinatorics", "Plots","TaylorSeries")`

would install the respective packages.

I am still trying to get a hold of Julia - if someone wants to help me PR (Or any other!) this into Base.Pkg, I would appreciate it. Vacations ahoy!

**Comment by StefanKarpinski** [comment]
Might not be worth the effort since we're planning on [replacing Pkg](https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md). Then again it probably won't be too hard to do, so if you'd like to dig into the Pkg code, go for it.

**Comment by fredrikekre** [comment]
Close this? https://github.com/JuliaLang/julia/issues/5366#issuecomment-303764469

```julia
Pkg.add.(["IJulia", "Combinatorics", "Plots", "TaylorSeries"])
```

is just 3 extra characters.

**Comment by timholy** [comment]
The cost is larger than 3 characters if, e.g., the resolver has to run `n` times rather than one time. We allow a vector of inputs to `Pkg.free` for precisely this reason (when doing "housecleaning" I tend to free a lot of packages at once).

**Comment by KristofferC** [comment]
Works on Pkg.jl `Pkg.add(["A", "B", ...])`.

**Comment by MohammadHudaNSW** [comment]
Is there a similar equivalent for using?

using ["IJulia", "Combinatorics", "Plots", "TaylorSeries"]

**Comment by KristofferC** [comment]
Just remove the braces and the quotes.

**Comment by MohammadHudaNSW** [comment]
I want to avoid hardcoding as much as possible.

This did the trick for me:

> pkgs = ["CSV", "DataFrames", "Dates", "Plots", "BenchmarkTools", "DataFramesMeta", "Pipe"];
> expr = "using " * join(pkgs, ", ")
> eval(Meta.parse(expr))
