### ISSUE TITLE
CUDArt assumptions not robust

### ISSUE THREAD

**Issue by robers97** [JuliaLang/julia#19601]
There is some pathing in the following file that presents errors for standard 64 bit CUDA installations in
/root/.julia/v0.5/CUDArt/src/CUDArt.jl

Symptom: Pkg.add("CUDArt") fails

In particular the line:
    const libcuda = Libdl.find_library(["libcuda"], ["/usr/lib/", "/usr/local/cuda/lib"])

wants to be
    const libcuda = Libdl.find_library(["libcudart"], ["/usr/lib/", "/usr/local/cuda/lib64"])

Three issues:

1) Since I don't have a 32bit CUDA install, I can't make a more robust suggestion than to say that the environment variable for CUDA_HOME should be checked
2)  I suspect that the find_library command might take another path such that you could put in cuda/lib64 ahead of cuda/lib
3) As of at least CUDA 8, its now libcudart instead of libcuda

julia> versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339 (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (powerpc64le-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY POWER8)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.0 (ORCJIT, pwr8)

**Comment by kshyatt** [comment]
Hi, this seems like a `CUDArt` issue rather than a base Julia issue. Could you reopen it at https://github.com/JuliaGPU/CUDArt.jl?
