### ISSUE TITLE
+ and - throw error with UpperTriangular matrices

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/julia#19615]
```
julia> m = [ 1 2 3
             4 5 6
             7 8 9 ]
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

julia> UpperTriangular(m)
3×3 UpperTriangular{Int64,Array{Int64,2}}:
 1  2  3
 ⋅  5  6
 ⋅  ⋅  9

julia> UpperTriangular(m) + 2
ERROR: ArgumentError: cannot set index in the lower triangular part (2, 1) of an UpperTriangular matrix to a nonzero value (2)
 in setindex!(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64, ::Int64, ::Int64) at ./linalg/triangular.jl:122
 in .+(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64) at ./arraymath.jl:82
 in +(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64) at ./arraymath.jl:94

julia> UpperTriangular(m) - 2
ERROR: ArgumentError: cannot set index in the lower triangular part (2, 1) of an UpperTriangular matrix to a nonzero value (-2)
 in setindex!(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64, ::Int64, ::Int64) at ./linalg/triangular.jl:122
 in .-(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64) at ./arraymath.jl:82
 in -(::UpperTriangular{Int64,Array{Int64,2}}, ::Int64) at ./arraymath.jl:96

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, nehalem)
```

**Comment by yuyichao** [comment]
So should these just return a full matrix?

**Comment by kshyatt** [comment]
@yuyichao yes, I think so. Probably something like `+(a::Number, b::UpperTriangular) = a + Array(b)` is the right way to go.

**Comment by tkelman** [comment]
not if the wrapped type is sparse.

**Comment by kshyatt** [comment]
Sorry - `parent(A)`?

**Comment by andreasnoack** [comment]
@tkelman Is this the conclusion in one of the recent `broadcast`+`sparse` issues? (I might have lost a little track of those discussion.) Right now, the behavior is mixed
```jl
julia> typeof(sprandn(10,10,0.1) .+ 1)
Array{Float64,2}

julia> typeof(broadcast(+, sprandn(10,10,0.1), 1))
SparseMatrixCSC{Float64,Int64}
```
but densifying seems more sensible for `+` and `-`.

**Comment by Sacha0** [comment]
#17623 fixed the inconsistency I believe
```julia
julia> typeof(sprandn(10,10,0.1) .+ 1)
SparseMatrixCSC{Float64,Int64}
```
Best!

**Comment by andreasnoack** [comment]
This works for the dot versions now that #17623 is merged. Anybody knows why [these](https://github.com/JuliaLang/julia/blob/master/base/arraymath.jl#L92-L131) wouldn't just call broadcast?

**Comment by Sacha0** [comment]
Perhaps for the special `promote_op`/`promote_array_type` behavior? Otherwise perhaps to avoid overhead (that may no longer exist)? Best!

**Comment by andreasnoack** [comment]
Maybe @stevengj would now if we can get rid of them.

**Comment by stevengj** [comment]
The promotion rules are slightly different for abstract types, so I didn't want to change them in that PR. It seemed best to do it in a separate PR.

**Comment by Sacha0** [comment]
Ref. related discussion https://github.com/JuliaLang/julia/issues/19595#issuecomment-268070182 and the forthcoming issue from `@martinholters`. Best!

**Comment by martinholters** [comment]
See #19669 re. the type behavior.
Some quick benchmarking shows that the comprehension is slightly slower than the explicit loop, which seems to be on par with `broadcast`, though. This is not a rigorous evaluation, just an indication that some more profound benchmarking might be in order.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/19746
