### ISSUE TITLE
ReadOnlyMemoryError() When trying to execute package-related commands

### ISSUE THREAD

**Issue by ehteqx** [JuliaLang/julia#19618]
With Julia 0.5.0 x86_64 for Linux (I am running Ubuntu 14.04 x86_64) every time I want to use the package manager - i.e. with Pkg.add() or Pkg.status() ... - it appears the following output:

INFO: Initializing package repository /home/emaballarin/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: ReadOnlyMemoryError()

I have already tries with a clean install, with no success.

After the execution of the commands, the /home/<username>/.julia folder remains empty, as it was prior to install.

**Comment by tkelman** [comment]
Are you working on a shared file system or in a VM or anything otherwise unconventional?

**Comment by ehteqx** [comment]
No, it's a really standard setup... nothing I am concerned of.

**Comment by tkelman** [comment]
Did you download the generic Linux binaries? If not, where did you install Julia from?

**Comment by ehteqx** [comment]
I used the stable PPA together with the Julia Dependencies PPA

**Comment by tkelman** [comment]
Try with the generic linux binaries. If that works, reopen this at https://github.com/staticfloat/julia-debian - the PPA is not officially supported.

**Comment by ehteqx** [comment]
Perfect, it works! Thank you for the support, and sorry if this wasn't the right place to discuss about the PPA.
