### ISSUE TITLE
A better least-squares with "thin" QR, than what is "\"'s default?

### ISSUE THREAD

**Issue by hrobotron** [JuliaLang/julia#19649]
Hello,

I have observed that default <code>A\y</code> solver for real matrices (see attached data in case of curiosity) gives very bad results, compared to <code>qrfact(A)\y</code>:

<pre>using JLD

@load "/tmp/lsq_qr_sample.jld"

e_bad=mean(abs(A*(A\y)-y))   # 184.04449212221158
e_good=mean(abs(A*(qrfact(A)\y)-y))   # 0.0018654587818872019

# nearly identical behaviour in Octave 3.8.2:
#  bad: A\y
#  bad: [Q,R]=qr(A); R\(Q'*y)
#  good: [Q,R]=qr(A,0); p=R\(Q'*y)
</pre>

(Data comes from real life experiment, and the default fit has no relevance, while the latter does its job.)
I have tried the same in Octave 3.8.2, seems to give almost identical results: the "full" QR gives wrong result, while the "thin" QR produces a good one.

I am far for claiming, that the thin QR, which is better for the above data set, is *generally* better. On the other hand, do you know what is the rationale behind current default, i.e. are there any tasks, where the default gives better results than the thin QR? If not, it would be tempting to make the thin QR the default...

Best regards,
Marek
[lsq_qr_test_jl.zip](https://github.com/JuliaLang/julia/files/661151/lsq_qr_test_jl.zip)

**Comment by andreasnoack** [comment]
It is better to ask questions like these on https://discourse.julialang.org/. The difference between the two methods is not thin vs. thick. It is columns pivoting QR and rank estimation vs. no pivoting and no rank estimation. Your matrix `A` is extremely badly conditioned so the numerical rank is estimated to be three. You should probably consider a different design for the data in `A` e.g. via orthogonal polynomials which wouldn't give a badly conditioned design matrix. Many, if not most, least squares problems have a genuine noise component so we believe that the current default is the best. For a longer discussion of this see https://github.com/JuliaLang/julia/pull/8859.

**Comment by hrobotron** [comment]
Dear @andreasnoack,

thank you for your guidance.

> You should probably consider a different design for the data in A e.g. via orthogonal polynomials which wouldn't give a badly conditioned design matrix.

Yes, for similar real-life tasks this would definitely help to overcome laziness. In lower order-tasks, I am already used to do so, e.g. in selecting Kalman filter state space; however here the bare <code>polyfit</code> led me to this ill-conditioned problem. I agree it is a fault of user and not the tool -- in this case, may be different in another task which is badly conditioned inherently.

> The difference between the two methods is not thin vs. thick. It is columns pivoting QR and rank estimation vs. no pivoting and no rank estimation.

>  Many, if not most, least squares problems have a genuine noise component so we believe that the current default is the best.

Thank you, this helped to my understanding. I translate the explanation as a clash between process noise (uncertainty of A) and measurement noise (uncertainty in b). i will probably consult algorithms such as http://web.stanford.edu/group/SOL/software/lsqr/ prior to continuing in this field.

Best regards,
Marek
