### ISSUE TITLE
Core.Inference.return_type and closures

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#19641]
In [this discourse thread](https://discourse.julialang.org/t/towards-broadcast-over-combinations-of-sparse-matrices-and-scalars/910), `@yuyichao` (thanks!) indicated that extending `Core.Inference.return_types` to handle closures should be possible. IIUC, doing so would enable simplification and improvement of the `broadcast` promotion mechanism. Ref. #19421 and #19633. Best!

**Comment by andyferris** [comment]
+100
