### ISSUE TITLE
add /(x::Number, y::Number) = /(promote(x,y)...) fallback?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19645]
[https://discourse.julialang.org/t/playing-around-with-intmod/980/5](https://discourse.julialang.org/t/playing-around-with-intmod/980/5?u=stefankarpinski)

Possibly also `^(x::Number, y::Number) = ^(promote(x,y)...)` but I'm less sold on that since promoting the exponent to the same type as the base generally makes a lot less sense.

**Comment by JeffBezanson** [comment]
I don't understand --- both of those definitions already exist in promotion.jl.

**Comment by JeffBezanson** [comment]
Closing as duplicate.
