### ISSUE TITLE
`pmap(f, c; distributed=false` is not equivalent to `asyncmap(f, c)`

### ISSUE THREAD

**Issue by Rory-Finnegan** [JuliaLang/julia#19652]
In the docs the following calls are described as equivalent.

> `pmap(f,c; distributed=false)` and `asyncmap(f,c)`

However, the `pmap` call will only run an `asyncmap` with `ntasks` equal to `nworkers(p)` (as shown [here](https://github.com/JuliaLang/julia/blob/master/base/pmap.jl#L120)) while the `asyncmap` call will run a `Task` for each element of `c`. If this is the intended behaviour it would help to mention it in the docs to avoid confusion.

**Comment by amitmurthy** [comment]
Just adding a reminder to also handle ExponentialBackOff in the pmap retry case when closing this issue (https://github.com/JuliaLang/julia/pull/19331#discussion_r95557044)

**Comment by Rory-Finnegan** [comment]
Thanks @amitmurthy!
