### ISSUE TITLE
Build error in release-0.5 branch

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#19650]
I have just cloned Julia and typed `make -j 8`, can you please help with the error below?

>llvm[3]: Linking Release Shared Library libLLVM-3.7.so
/home/juliohm/Projects/julia/deps/build/llvm-3.7.1/build_Release/Release/lib/libLLVMTransformUtils.a: member /home/juliohm/Projects/julia/deps/build/llvm-3.7.1/build_Release/Release/lib/libLLVMTransformUtils.a(SimplifyInstructions.o) in archive is not an object
collect2: error: ld returned 1 exit status
make[3]: *** [/home/juliohm/Projects/julia/deps/srccache/llvm-3.7.1/Makefile.rules:1207: /home/juliohm/Projects/julia/deps/build/llvm-3.7.1/build_Release/Release/lib/libLLVM-3.7.so] Error 1
make[2]: *** [/home/juliohm/Projects/julia/deps/srccache/llvm-3.7.1/Makefile.rules:880: install] Error 1
make[1]: *** [/home/juliohm/Projects/julia/deps/llvm.mk:527: /home/juliohm/Projects/julia/usr/lib/libLLVMCodeGen.a] Error 2
make: *** [Makefile:81: julia-deps] Error 2

**Comment by tkelman** [comment]
does it persist every time after say `make -C deps distclean-llvm && make -j4` ?

**Comment by juliohm** [comment]
So the target `distclean-llvm` only works if you change to the `deps` directory? Strange.

The build is successful now.

**Comment by tkelman** [comment]
sounds like you ran out of memory or the compiler wrote a corrupt file somehow. don't think there's anything we can do here.
