### ISSUE TITLE
`search()` returns different results if starting the search behind the string depending on search-term

### ISSUE THREAD

**Issue by SaschaMann** [JuliaLang/julia#19657]
This bug exists in both 0.5.0 and 0.6.0-dev.1584. Haven't tested older versions myself.

The behaviour of `search(string::AbstractString, chars::Chars, [start::Integer])` (1) and `search(str::Union{String,SubString}, re::Regex, idx::Integer)` (2, [source code](https://github.com/JuliaLang/julia/blob/master/base/regex.jl#L215-L218)) is really inconsistent for starting indices beyond the length of the string.

Depending on what you search for, it returns either `length+1:length`, `0:-1` or throws a `BoundsError`.

`str = "abcdef"` is used for the examples below.

Only (1) is documented and mentions `0:-1` for unmatched Strings which it also returns if `start>length(string)` (this however, is not explicitely mentioned in the docs):

```julia
julia> search(str, "abc", endof(str)+1)
0:-1

julia> search(str, "abc", endof(str)+2)
0:-1
```

(2) throws a `BoundsError` if you start the search 2 positions behind the string. This doesn't seem to be documented anywhere and isn't tested either. If you start 1 position behind it, it returns `7:6` if the regex is `r".?"` or `r".*"` but not for other regex without them:

```julia
julia> search(str, r".?", endof(str)+1)
7:6

julia> search(str, r".?", endof(str)+2)
ERROR: BoundsError
 in search(::String, ::Regex, ::Int64) at ./regex.jl:217

julia> search(str, r".*", endof(str)+1)
7:6

julia> search(str, r".*", endof(str)+2)
ERROR: BoundsError
 in search(::String, ::Regex, ::Int64) at ./regex.jl:217
```

However:

```julia
julia> search(str, r"abcdef", endof(str))
0:-1

julia> search(str, r"abcdef", endof(str)+1)
0:-1

julia> search(str, r"abcdef", endof(str)+2)
ERROR: BoundsError
 in search(::String, ::Regex, ::Int64) at ./regex.jl:217
```

There are also inconsistencies with (1) when searching for `""` or `r""`:

```julia
julia> search(str, "")
1:0

julia> search(str, "", endof(str))
6:5

julia> search(str, "", endof(str)+1)
7:6

julia> search(str, "", endof(str)+2)
0:-1

julia> search(str, r"", endof(str)+2)
ERROR: BoundsError
 in search(::String, ::Regex, ::Int64) at ./regex.jl:217
```

Regardless of which return value is correct, something isn't working as intended here.

**Comment by SaschaMann** [comment]
Fixing this shouldn't be too hard, I can probably make the PR myself; however, I'm not sure which one is the intended return value.

Imo it makes sense to throw a `BoundsError` for starting a search "behind" the string because it let's you distinguish between not matching anything and an incorrect starting position. However, it only seems to exist for (2) and isn't even implemented properly there (I think this would be fixed by testing for `start >= nextind(str, endof(str))` or `start > length(str)`).

**Comment by nalimilan** [comment]
I agree throwing a `BoundsError` when the start index is beyond the end of the string is the right behavior. This is consistent with `getindex` and `next`.
