### ISSUE TITLE
Expose LLVM optimization remarks

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#19654]
LLVM exposes various optimization remarks to inform the user why it wasn't able to optimize certain functions. We should find a nice way to expose this.

**Comment by smldis** [comment]
This is the reference:
2016 LLVM Dev. Meeting talk:
- Clip: https://www.youtube.com/watch?v=qq0q1hfzidg
- Slides: http://llvm.org/devmtg/2016-11/Slides/Nemet-Compiler-assistedPerformanceAnalysis.pdf
- The actual graphical tool used in the presentation can be found here: https://github.com/llvm-mirror/llvm/blob/master/utils/opt-viewer/opt-viewer.py

**Comment by KristofferC** [comment]
@keno, is `JULIA_LLVM_ARGS` enough to close this?

**Comment by Keno** [comment]
I'd prefer if they could be exposed in `@code_llvm`. As it stands, you can only turn them on globally and the output is a mess.

**Comment by vtjnash** [comment]
That's largely an upstream issue, and this issue is rather useless for tracking that. And there's a small but non-trivial cost to keeping it open.

**Comment by Keno** [comment]
Could you elaborate what you mean by that? My understanding is that we'd have to set up a remark streamer on the julia side and capture the output for display. What needs to be done upstream?

**Comment by vtjnash** [comment]
Yeah, a package could do that (or rather, did that for my London JuliaCon talk), but last I checked it is only a global LLVM option, so you can't properly scope it to a particular LLVMContext
