### ISSUE TITLE
fatal error when loading a file using "-L" when the "-p 2" option is also used

### ISSUE THREAD

**Issue by ahalwright** [JuliaLang/julia#19675]
The  file "fails.jl"  (attached as fails.jl.txt) causes a fatal error when I attempt to load into Julia using the following command:   "julia -p 2 -L fails.jl".

The problem is in the interaction of "-p 2", "-L" and "using".

The full error messages under julia and julia-debug are also attached.  The error message is the same in julia v5.0 (Linux or Windows) and in the latest build of julia v6.0 (Linux).

[fails.jl.txt](https://github.com/JuliaLang/julia/files/667650/fails.jl.txt)
[fails_error_message.txt](https://github.com/JuliaLang/julia/files/667651/fails_error_message.txt)
[fails_julia-debug_error_message.txt](https://github.com/JuliaLang/julia/files/667673/fails_julia-debug_error_message.txt)

**Comment by yuyichao** [comment]
Likely dup of https://github.com/JuliaLang/julia/issues/15766

**Comment by amitmurthy** [comment]
When completed #19073 and #19594 should help fix this.

**Comment by laborg** [comment]
Closing this as it doesn'fail anymore and dups have been closed too (https://github.com/JuliaLang/julia/issues/21704) :
```
~/code/julia (master*) » ./julia -p 2 -L fails.jl                                                                                                 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.1440 (2022-02-02)
 _/ |\__'_|_|_|\__'_|  |  Commit e3b681c687 (5 days old master)
|__/                   |

julia> 
```
