### ISSUE TITLE
PyCall.jlwrap issue when using r"$...$" syntax to allow greek in figure titles/axes lables

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [JuliaLang/julia#19676]
### Overview

The issue comes up when using PyPlot and syntax described [here](http://matplotlib.org/users/mathtext.html), to use math mode in figure titles and/or axes labels.

### Minimal working example
```
using PyPlot
plot(1:10,rand(10,1))
title(r"$α$")
xlabel(r"$β$")
ylabel(r"$γ$")
```
where the title instead of saying "α", says "<PyCall.jlwrap r"α">".
A simmilar issue appears when attempting to use legend:
```
using PyPlot
plot(1:10,rand(10,1))
legend(r"$δ$")
```
but now (potentially more helpfully) a following error apears:
```
LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('izip argument #2 must support iteration',)
  File "C:\Users\xyz\.julia\v0.5\Conda\deps\usr\lib\site-packages\matplotlib\pyplot.py", line 3560, in legend
    ret = gca().legend(*args, **kwargs)
  File "C:\Users\xyz\.julia\v0.5\Conda\deps\usr\lib\site-packages\matplotlib\axes\_axes.py", line 540, in legend
    in zip(self._get_legend_handles(handlers), labels)]

while loading In[48], in expression starting on line 1

 in pyerr_check at C:\Users\xyz\.julia\v0.5\PyCall\src\exception.jl:56 [inlined]
 in pyerr_check at C:\Users\xyz\.julia\v0.5\PyCall\src\exception.jl:61 [inlined]
 in macro expansion at C:\Users\xyz\.julia\v0.5\PyCall\src\exception.jl:81 [inlined]
 in #_pycall#62(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyCall\src\PyCall.jl:546
 in _pycall(::PyCall.PyObject, ::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyCall\src\PyCall.jl:534
 in #pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyCall\src\PyCall.jl:568
 in pycall(::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyCall\src\PyCall.jl:568
 in #legend#72(::Array{Any,1}, ::Function, ::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyPlot\src\PyPlot.jl:399
 in legend(::Regex, ::Vararg{Regex,N}) at C:\Users\xyz\.julia\v0.5\PyPlot\src\PyPlot.jl:396
```

### Futhrer thoughts

- simply writing the symbol like `title("α")` does not work.
- neither does `title("\alpha")
- neither does title(r"$\alpha$")
- the symbols are clearly getting rendered properly, but I immagine that the overhead from the julia function is beeing passed imporperly to matplotlib and thus incorporated into the title (and then passed back in form of a title of the rendered image).

### Versioninfo
Here is my `versioninfo()`
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

### Screenshot
![image](https://cloud.githubusercontent.com/assets/24707398/21412814/ec78f096-c7ea-11e6-850b-f5149ad64d64.png)

**Comment by yuyichao** [comment]
This is julia and not python so you cannot use the exact same syntax.

**Comment by yuyichao** [comment]
And please read the PyPlot.jl doc instead https://github.com/JuliaPy/PyPlot.jl

**Comment by MarcinKonowalczyk** [comment]
@yuyichao thank you.
It was not clear to me that this was so. I still experiance an error when using the correct syntax with `legend()` though, but I will raise it on the PyPlot.jl repository.
