### ISSUE TITLE
New broadcast lowering of .op is very slow

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#19706]
It with pointed in https://github.com/JuliaArrays/StaticArrays.jl/pull/90 that the new lowering of `.op`s didn't generate optimal code. Indeed, there seems to be something very wrong right now (completely unrelated to `StaticArrays`)
```jl
julia> x = randn(4);

julia> @time x .* 3.0;
  0.028046 seconds (9.30 k allocations: 461.111 KB)

julia> @time x .* 3.0;
  0.030100 seconds (9.30 k allocations: 461.861 KB)

julia> @time x .* 3.0;
  0.027147 seconds (9.30 k allocations: 462.596 KB)



julia> @time x * 3.0;
  0.000003 seconds (5 allocations: 272 bytes)

julia> @time x * 3.0;
  0.000003 seconds (5 allocations: 272 bytes)
```
Is the method getting recompiled for each invocation?

**Comment by yuyichao** [comment]
This is the wrong benchmark, put it in a function like

```jl
julia> f(x) = x .* 3.0
f (generic function with 1 method)
```

**Comment by andreasnoack** [comment]
Fair enough. I thought the new behavior of `.*` would be equivalent to calling `broadcast(*, x, 3.0)` (which is fast) but I guess you should think of it as `broadcast((t,s) -> t*s, x, 3.0)` such that a new version is compiled every time you execute this at the top level?

**Comment by yuyichao** [comment]
It's `broadcast(t->t * 3.0, x)`
