### ISSUE TITLE
`sleep`, etc. with `Dates.Period` types

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#19736]
It would be nice for standard library unity if this were supported:

```julia
sleep(Dates.Second(10))
sleep(Dates.Millisecond(10))
```

I personally have a hard time remembering whether sleep takes units of seconds or milliseconds.

The same goes for functions like `timedwait`.

**Comment by Shade5** [comment]
Will overloading the sleep function do?

**Comment by Shade5** [comment]
@TotalVerb Please review https://github.com/JuliaLang/julia/pull/19749
