### ISSUE TITLE
Difference between tic() toc(), @time or @elapse in Julia?

### ISSUE THREAD

**Issue by may811204** [JuliaLang/julia#19740]
Hi, I am new to Julia and I am wondering what's the difference between tic() toc(),@time, @elapse when measuring elapsed time in Julia.
I tried the codes below:
![image](https://cloud.githubusercontent.com/assets/8717276/21515172/32068c00-cd08-11e6-82b0-2b001c7d4573.png)
And here's the output:
![image](https://cloud.githubusercontent.com/assets/8717276/21515180/4598a10e-cd08-11e6-862a-c6685ae0c295.png)
It showed that tic() toc() and t2-t1 share relatively close quantity. On contrast, @time and @elapse are close. However, there is difference between tic toc and @time.
What is the difference and why?  
Which approach should I use to measure the elapsed time?
 Thanks a lot!

**Comment by tkelman** [comment]
Hi. Welcome, but as noted in the issue template, we use github issues for bug reports. If you post this question to https://discourse.julialang.org/ people will be happy to answer.
