### ISSUE TITLE
promoting `Nullable` with anything?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#19748]
e79e84654a40e8189e5dfbd55df232ae6c82a213 added the following definition:

```
promote_rule{S,T}(::Type{Nullable{S}}, ::Type{T}) = Nullable{promote_type(S, T)}
```

This might have unintended consequences. For example, we have:

```
julia> promote(1, "")
(1,"")

julia> promote(Nullable(1), "")
(Nullable{Any}(1),Nullable{Any}(""))
```

Given a `Nullable` and something completely unrelated, you get two `Nullable{Any}`s. I don't think two types should have a non-identity promotion just because one is Nullable. This was not obvious at the time.

I propose this definition instead:

```
function promote_rule{S,T}(::Type{Nullable{S}}, ::Type{T})
    R = promote_type(S, T)
    if R <: S || R <: T
    else
        if S <: R || T <: R
            return R
        end
    end
    return Nullable{R}
end
```

This says to leave the values alone if the promoted type (R) is a strict supertype of T or S, and otherwise promote as before. For example

```
julia> promote(Nullable(1),2.4)
(Nullable{Float64}(1.0),Nullable{Float64}(2.4))

julia> promote(Nullable(1),"")
(Nullable{Int64}(1),"")
```

This definition can still be type-inferred (since we can now handle constant conditions well).

**Comment by nalimilan** [comment]
I see your point. Maybe just check that the promoted type is different from `Any` instead? In practice I'm not sure it's really different, but it could be simpler to explain/remember.

Though there's always a cost in making rules more complex. Do you have a use case in mind where the current simple rule would be problematic?

**Comment by JeffBezanson** [comment]
There was a piece of code here: https://github.com/JuliaIO/JSON.jl/issues/39#issuecomment-194922317
that used `vcat` to combine values before assigning them to fields of another type. Since one was nullable, all values were converted to nullable and didn't match the expected field types.

**Comment by nalimilan** [comment]
OK. A related issue is that conversion to nullable is allowed, but conversion from nullable is not. Not sure we have other cases like this where promotion gives a type which cannot be converted back to the original type, but that sounds potentially problematic (as in your example).

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaArchive/Nullables.jl/issues/6
