### ISSUE TITLE
run julia.exe then entry not found: _ftime64s_ in msvrct.dll

### ISSUE THREAD

**Issue by lilydove** [JuliaLang/julia#19742]
I run julia.exe then the screen shows " entry not found: _ftime64s_ in msvrct.dll " in a window
I can not open julia's console.

system: windows xp
julia:1-5-0

![julia01](https://cloud.githubusercontent.com/assets/10510291/21518992/0bf459f8-cd25-11e6-8f40-ee2d0e00b647.PNG)

**Comment by KristofferC** [comment]
Please comment if this still happens.
