### ISSUE TITLE
World age error when using eval

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#19754]
Since two weeks or so I've been getting world age errors on 0.6:
https://travis-ci.org/JuliaInterop/CxxWrap.jl/jobs/187221362#L246

The relevant code is here:
https://github.com/JuliaInterop/CxxWrap.jl/blob/master/src/CxxWrap.jl#L276

By default, the passed parent_mod is Main, so in essence the code above is the same as this:
```julia
function f(mod)
  modsym = Symbol("testmod")
  mod.eval(:(module $modsym end))
end

f(Main)
```

But that doesn't trigger the error...

Any ideas what could be causing this?

**Comment by yuyichao** [comment]
Please use the discourse forum for questions.

**Comment by tkelman** [comment]
As people start fixing their broken packages for this kind of issue, we will need to document this in more detail.

**Comment by vtjnash** [comment]
It looks like CxxWrap is using the OO-looking `julia_mod.eval(f)` instead of the intended correct `eval(julia_mod, f)`
