### ISSUE TITLE
mktempdir doesn't work if parent doesn't exist

### ISSUE THREAD

**Issue by mpastell** [JuliaLang/julia#19756]
I noticed that calling `mktempdir` throws an error if the parent doesn't exist. 

```julia
julia> mktempdir("tempdirs")
ERROR: SystemError: mktempdir: No such file or directory
 in #systemerror#53 at ./error.jl:34 [inlined]
 in systemerror(::Symbol, ::Bool) at ./error.jl:34
 in mktempdir(::String) at ./file.jl:325
```
Would it make sense just to create the parent instead of throwing an error?

**Comment by yuyichao** [comment]
Sounds mostly a doc issue. I don't think we should create the parent automatically since it'll be hard to decide if we should remove it later. `mktempdir(::Function, parent)` is supposed to clear everything it created.

**Comment by mpastell** [comment]
Thanks for the fast response, makes sense.
