### ISSUE TITLE
Getting Openssl error while building from source on ubuntu 14.04.3 cmake version 2.8.12.2

### ISSUE THREAD

**Issue by arshpreetsingh** [JuliaLang/julia#19752]
This seems bug related to julia's build package. I am getting following error while building using make.

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  CMakeLists.txt:277 (FIND_PACKAGE)

**Comment by tkelman** [comment]
What branch are you building? Do you have `libssl-dev` installed?

**Comment by arshpreetsingh** [comment]
yes libssl-dev was not installed, closing the issue.

**Comment by tkelman** [comment]
that's documented in the readme for the release-0.5 branch, and no longer necessary on master
