### ISSUE TITLE
llvm-3.9.0_threads.patch breaks the build on FreeBSD

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#19769]
Our patched LLVM 3.7 built fine on FreeBSD, but it seems that LLVM 3.9 refuses to build on FreeBSD when llvm-3.9.0_threads.patch is applied. The following message is displayed, along with several other similar messages referencing other LLVM files:
```
CMake Error at cmake/modules/LLVMProcessSources.cmake:83 (message):
  Found unknown source file
  /usr/home/alex/repos/julia/deps/srccache/llvm-3.9.1/tools/lli/OrcLazyJIT.cpp


  Please update
  /usr/home/alex/repos/julia/deps/srccache/llvm-3.9.1/tools/lli/CMakeLists.txt
```
The build works fine if the application of this patch is commented out.

This is with CMake 3.7.1. I guess the patch was copied from Rust's fork of LLVM, so this issue may not be unique to Julia.

**Comment by tkelman** [comment]
try taking this section out of the patch https://github.com/JuliaLang/julia/blob/d7b6ac31025d8ca685ef9e725ea81981346bc50e/deps/patches/llvm-3.9.0_threads.patch#L331-L337 (then `distclean`ing llvm)

**Comment by ararslan** [comment]
For reference, the more complete log from building LLVM is [here](https://gist.github.com/ararslan/c9416e632be47abe65d5fb0819cf05f0). I'll try your suggestion and see what happens. Thanks as always, Tony!

**Comment by ararslan** [comment]
Looks like your suggestion plus the removal of [this section](https://github.com/JuliaLang/julia/blob/d7b6ac31025d8ca685ef9e725ea81981346bc50e/deps/patches/llvm-3.9.0_threads.patch#L996-L1018) got it building. 🎉

**Comment by ararslan** [comment]
I'm getting a ton of messages that say that libjulia.so contains undefined references to LLVM things. For example, here are the first few such messages:
```
/usr/home/alex/repos/julia/usr/lib/libjulia.so: undefined reference to `llvm::object::object_category()'
/usr/home/alex/repos/julia/usr/lib/libjulia.so: undefined reference to `llvm::ConstantExpr::getCompare(unsigned short, llvm::Constant*, llvm::Constant*, bool)'
/usr/home/alex/repos/julia/usr/lib/libjulia.so: undefined reference to `llvm::InsertValueInst::init(llvm::Value*, llvm::Value*, llvm::ArrayRef<unsigned int>, llvm::Twine const&)'
/usr/home/alex/repos/julia/usr/lib/libjulia.so: undefined reference to `llvm::ConstantInt::getSigned(llvm::Type*, long)'
```
For the full section of the log, see [here](https://gist.github.com/ararslan/05d2ca501f23009c9a70da4eb0dbf69b).

**Comment by tkelman** [comment]
do the linker errors happen if you don't apply any of our patches to llvm at all?

**Comment by ararslan** [comment]
Actually yes, they do. I guess those errors probably has more to do with LLVM 3.9 on FreeBSD in general than with our patches.

**Comment by tkelman** [comment]
It would be good to put together a Vagrantfile for the FreeBSD build at some point so it's easier to test against.

**Comment by tkelman** [comment]
Ooh, I think I know why this is FreeBSD-specific. Apparently when `patch` behaves in a way that strictly conforms to POSIX, it doesn't remove empty files by default. GNU patch, which I think Apple might also use (?), does. First, if a file exists at `deps/srccache/llvm-3.9.1/tools/lli/OrcLazyJIT.cpp`, how big is it? Try adding `-E` to the `patch` call here https://github.com/JuliaLang/julia/blob/c38a5a3044ffd62c585225a201422f95fd18f6dc/deps/llvm.mk#L432 and see if that fixes this issue.

**Comment by tkelman** [comment]
Scratch that, looks like busybox-based systems don't support `patch -E`. Try the commits I just added to #19810 (starting from distclean'ed llvm) which should hopefully make it unnecessary.
