### ISSUE TITLE
obsolete version of dependent function being called

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#19770]
I just noticed what seems to have been a resurgence of #265 or a similar problem in 0.6 master, in a context where it didn't appear before (hence a regression).

In IJulia, it calls `show(io, "text/plain", x)` to get the text representation of the execution result, so if a package or notebook overrides the 3-argument `show` it should display as such.  However, this doesn't seem to be happening anymore.  If I make a notebook with
```jl
type Foo; end
Base.show(io::IO, ::MIME"text/plain", x::Foo) = print(io, "got a Foo()")
Foo()
```
Then it displays simply as `Foo()`, corresponding to the default `show` for composite types.

The reason that I think this is a related to #265 (or its resolution) is that I was able to work around it by calling `eval` (https://github.com/JuliaLang/IJulia.jl/commit/3ed9573d517fa62dd3dd56c084d7549ec372c6ec), using the same workaround as in #7884.

**Comment by vtjnash** [comment]
This is working as intended. There's no more "obsolute" methods now. In the old #265, you couldn't predict whether the old or new dispatch got called. But now you can: it'll just always call the old one 😃 https://github.com/JuliaLang/julia/pull/17057/files#diff-619ea7b9ee7c2fa87a3720c1361ba46cR396

**Comment by stevengj** [comment]
Thanks for the clarification!  I'm still getting used to the new "world age" semantics.

It's really awkward to use `eval` with an expression to invoke the newest version of a function.  Can we have some more convenient methods to do `invokenewest(function, args...)`?  See also #19774
