### ISSUE TITLE
Error following installation.

### ISSUE THREAD

**Issue by GlennBurkins** [JuliaLang/julia#19772]
I installed the v0.5.0 x64 version of Julia on a 64bit Windows 10 (current). No problems encountered during installation.
I opened a command prompt and went to the directory where I had installed Julia. I attempted to run julia.exe and got the following messages:

fatal: error thrown and no exception handler available.
Base.InitError(mod=:Pkg, error=Base.KeyError(key="HOMEDRIVE"))
rec_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\stackwalk.c:84
record_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:232
jl_throw at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:550
access_env at .\env.jl:14
homedir at .\path.jl:41
_pkgroot at .\pkg\dir.jl:10 [inlined]
__init__ at .\pkg\pkg.jl:74
unknown function (ip: 0000000061D17BCE)
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:189 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1942
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1392 [inlined]
jl_module_run_initializer at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:83
_julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\init.c:742
julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:283
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:231
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)

Thank you.

**Comment by tkelman** [comment]
You need to have the HOMEDRIVE and HOMEPATH environment variables set.

**Comment by H-225** [comment]
> access_env at .\env.jl:14
homedir at .\path.jl:41
_pkgroot at .\pkg\dir.jl:10 [inlined]

Odd... `homedir` doesn't call `access_env`. `_pkgroot` calls `get` which does... Bug?

There also seems to be some funkiness with the line numbers as well: `homedir` doesn't start until line 58. Also a bug?

**Comment by tkelman** [comment]
This has changed on master. If you're running 0.5.0, look at the code at the 0.5.0 tag.

**Comment by tkelman** [comment]
not an issue on master, was fixed by https://github.com/JuliaLang/julia/pull/19636
