### ISSUE TITLE
doc: searchsorted should mention "binary search"

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19780]
Yes, this is specific to vectors since we don't use binary search for ranges, but the documentation for `searchsorted*` should mention the phrase "binary search" somewhere so that people can find it.

**Comment by rishikksh20** [comment]
I am interested in working on the issue. How do I go with it?

**Comment by tkelman** [comment]
see https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation

**Comment by akaysh** [comment]
@StefanKarpinski Can we start the explanation with `Uses Binary Search to return` in place of `Returns the index of....`  in `searchsorted*` ?

**Comment by rishikksh20** [comment]
@tkelman @StefanKarpinski The shared query in itself is quite complete and self explanatory. I have made little modification in the sentence without change anything in current order.
`Returns the range of indices of a which compare ( using binary search) as equal to x according to the order specified by the by, lt and rev keywords`
 If you need any more on this let me know.
