### ISSUE TITLE
deprecate rand! etc. in favor of x .= rand.()?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#19796]
Since we can now do `x .= rand.()` to evaluate `rand()` for each element of `x`, do we still need `rand!` etcetera?

See also #12277.

**Comment by stevengj** [comment]
(Though `rand!()` does have an optimized SIMD implementation IIRC.)

**Comment by KristofferC** [comment]
Can't the specific broadcast function that `x .= rand.()` lowers into be overloaded to use the optimized version?

**Comment by stevengj** [comment]
Yes, it can.  Of course, it won't work if you fuse the `rand.()` with additional operations.

**Comment by KristofferC** [comment]
Yes, but that should be fine I think. You couldn't used the optimized one if you wrote the fused version manually anyway, right?

**Comment by stevengj** [comment]
Right.

**Comment by TotalVerb** [comment]
Can one replace use cases like `rand!(similar(X))` with `similar(X) .= rand.()`?

**Comment by stevengj** [comment]
@TotalVerb, that would work.  I agree it's more verbose, but I don't think that construct is very common; I can only find two packages that use it in test scripts, and in both cases they could have used `rand(size(X)...)` as well.

**Comment by stevengj** [comment]
On the other hand, `x .= rand.()` is not a drop-in replacement for `rand!(x)` if `eltype(x)` != `Float64`, so I think probably we should keep `rand!`.

(The argument for replacing `fill!` and `scale!` remains, however.)

**Comment by Sacha0** [comment]
> On the other hand, x .= rand.() is not a drop-in replacement for rand!(x) if eltype(x) != Float64, so I think probably we should keep rand!.

Though slightly more verbose, perhaps `x .= rand.(eltype(x))` with appropriate `rand(::Type{...})` methods could work?

> (The argument for replacing fill! and scale! remains, however.)

Perhaps `fill!` and `scale!` deserve dedicated issues? Best!

**Comment by Sacha0** [comment]
(Also relevant to `randexp!` and `randn!`.)
