### ISSUE TITLE
nextpow2 as defined in Base not very useful

### ISSUE THREAD

**Issue by merl-dev** [JuliaLang/julia#19804]
I noticed that Julia's definition of `nextpow2` is odd (and this holds for the python def as well https://wiki.python.org/moin/NumericAndScientificRecipes]).  The function is generally used in fft to pad a series such that it's new length is  some power of 2.  So if we have a series of length 129, we would pad it up to length 256:  Since `7 = round(Int, log2(129))`, the next power of 2 would be `8 = round(Int, log2(256))`.  

However the current implementation in Base gives `256 = nextpow2(129)`, which is not the **next** power, but the result of 2^8, where 8 is the 'true' next power.

Not sure if this breaks anyone's code, nor if there is any interest to get this consistent with either the meaning of 'next power of 2' or say Matlab/Octave.

**Comment by vtjnash** [comment]
The function as defined as next-number-that-is-a-power-of-two, not ceiling-log2. Why is that odd or not useful?

**Comment by KristofferC** [comment]
If you google `nextpow2` you basically only get matlab / octave references where it is defined as " the exponents for the smallest powers of two". Same with ex. https://github.com/cran/pracma/blob/master/R/nextpow2.R.

**Comment by merl-dev** [comment]
I was porting some matlab code and came across the discrepancy in definitions...after looking at a few other languages I guess it is the matlab definition that is the oddity.
