### ISSUE TITLE
Check for paths with spaces and produce a more helpful message.

### ISSUE THREAD

**Issue by sidgupta234** [JuliaLang/julia#19806]
I was trying to setup my development environment for Julia, after cloning the repository. I tried to make, by running the ```make``` command. You can see below the dump of the shell session.

```
$ pwd
/media/sidgupta234/New Volume1/github-dev/julia

$ ls
appveyor.yml     deps             examples    Make.inc       README.windows.md  VERSION
base             DISTRIBUTING.md  HISTORY.md  NEWS.md        src                Windows.inc
contrib          doc              LICENSE.md  README.arm.md  test
CONTRIBUTING.md  etc              Makefile    README.md      ui

$ make
Makefile:2: /media/sidgupta234/New: No such file or directory
Makefile:2: Volume1/github-dev/julia/Make.inc: No such file or directory
find: ‘/media/sidgupta234/New’: No such file or directory
find: ‘Volume1/github-dev/julia/examples/clustermanager’: No such file or directory
find: ‘/media/sidgupta234/New’: No such file or directory
find: ‘Volume1/github-dev/julia/base’: No such file or directory
find: ‘/base’: No such file or directory
/bin/sh: 1: /media/sidgupta234/New: not found
make: *** No rule to make target 'Volume1/github-dev/julia/Make.inc'.  Stop.
```
@p-i- Pointed out that "make" doesn't work well with spaces in paths.

To save the new user from fury, I would suggest putting a flag somewhere in the ReadMe.md file or let us better the error message, maybe both.

**Comment by p-i-** [comment]
My only thought here is that it may be for the greatest good if the developer is simply informed to avoid paths containing spaces. I'm a bit surprised `make` doesn't take on this job of educating.

**Comment by p-i-** [comment]
Of course, I should have spotted that!

I suppose the only thing Julia could realistically do is add a note in the README to say:

**_"Ensure you don't have whitespace or weird characters in your Julia path!"_**

... immediately before `make`. I'll stick that in if nobody objects.

**Comment by sidgupta234** [comment]
Cool! I am creating a PR to add the caution to the README.

**Comment by sidgupta234** [comment]
As there is already a Note in the readme, about the same and we cant produce any helpful messages, closing this issue.

> 
Note: the build process fail badly if any of the build directory's parent directories have spaces or other shell meta-characters such as $ or : in their names (this is due to a limitation in GNU make).

Thank you @Ismael-VC for pointing this out.

**Comment by sidgupta234** [comment]
As there is already a Note in the readme, about the same and we cant produce any helpful messages, closing this issue.

> 
Note: the build process fail badly if any of the build directory's parent directories have spaces or other shell meta-characters such as $ or : in their names (this is due to a limitation in GNU make).

Thank you @Ismael-VC for pointing this out.
