### ISSUE TITLE
Deprecate frexp{T<:AbstractFloat}(A::Array{T}) in favor of broadcast ?

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#19817]
Now that we have `.` for broadcasting, the method `frexp{T<:AbstractFloat}(A::Array{T})` doesn't seem as useful as it once did?

Currently the method returns  `(F,E)` where `F` is an array of 'significands' and `E` is an array of 'exponents'. The behavior with the broadcast would instead return an array of tuples.

@ScottPJones  also mentioned on gitter that  it is also over specified, it only works for Array, not any AbstractArray

**Comment by simonbyrne** [comment]
Yes, we probably should deprecate it, though as you point out, the fact that there is no way to recreate this functionality via `.` is a little annoying, which is why I suspect it hasn't been done already.

**Comment by JeffBezanson** [comment]
The vectorized version of this is pretty weird. Is there a use case for getting these two arrays of values? Unlike other vectorized functions, returning a tuple of two arrays doesn't compose naturally with most other functions.

**Comment by stevengj** [comment]
If you just want an array of `F` you could do e.g. `first.(frexp.(A))`

**Comment by stevengj** [comment]
(I can't find any registered packages using `frexp`, vectorized or not.)

**Comment by simonbyrne** [comment]
I think we just deprecate and so it is no longer available. We don't provide vectorised forms of other 2-output functions (e.g. `modf`, `divmod`)

**Comment by simonbyrne** [comment]
Sorry, I accidentally pushed to master. Fixed by 2e0b00180eb827f4e2151d55dbdfca352b61fc65.
