### ISSUE TITLE
Search is broken on http://docs.julialang.org/en/latest/

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#19826]
Searching I always get
`Number of results: -`

@KristofferC   suggested the issue is better suited for this repo
https://github.com/JuliaLang/julialang.github.com/issues/482

**Comment by MichaelHatherly** [comment]
Probably not specific to the Manual, but only noticeable here since the search index is so much bigger than other packages. I'll see what I can do, probably just needs to have the js assets loaded in a different order.

**Comment by mbauman** [comment]
I think that there's a browser-dependent bug here.  I get results after about a second on Safari, but the page never changes on Chrome.

**Comment by MichaelHatherly** [comment]
Might have solved it... Can someone check whether the search on https://michaelhatherly.github.io/julia-docs/en/latest/index.html loads properly. (Note that there is a second or so delay while results are loaded from the index, but they do actually load now I think.)

**Comment by musm** [comment]
That link works for me.

Where should documentation bugs/requests for improvements be submitted? 

Search in the stable release version also highlights where in the text the search item is referenced if it is in a 'section'. In the latest release version   it just tells you it was reference in a certain ;section' with no reference to where in the text, which is harder to identify which section contains the information you seek, without clicking all the links.

**Comment by MichaelHatherly** [comment]
Thanks for checking.

> Where should documentation bugs/requests for improvements be submitted?

Content-related issues/bugs should be opened here I should think. Anything related to presentation/rendering of the generated docs can be opened in Documenter's issue tracker. Sometimes it's not too clear which is which, but we can always move issues to the right place if needed.

> Search in the stable release version also highlights

Yes, I'm planning on fixing that, probably with https://github.com/julmot/mark.js/.

**Comment by musm** [comment]
Thanks!

**Comment by MichaelHatherly** [comment]
Fixed by https://github.com/JuliaDocs/Documenter.jl/pull/401, will require upgraing Documenter version to 0.8.10 later today for this to be fixed on the main site though.
