### ISSUE TITLE
readline hangs using julia 0.6 on Windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#19825]
The following function using readline hangs using julia 0.6 but works perfectly well on julia 0.5
```julia
Julia Version 0.6.0-dev.1833
Commit 6484f4c* (2016-12-31 21:22 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

 function input(prompt::String = "")
           print(prompt)
           return chomp(readline())
end

input("Hang in there")
```

**Comment by dpsanders** [comment]
Works for me.
```
julia> input("Hang in there\n")
Hang in there
Hi
"Hi"

julia> versioninfo()
Julia Version 0.6.0-dev.1833
Commit a3db504* (2016-12-31 20:33 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.0.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by musm** [comment]
I'm pretty sure this is Windows specific

**Comment by dpsanders** [comment]
Looks like. Might be useful to change the issue title then.

**Comment by H-225** [comment]
Curiously, keys that are typed do not appear in the console - nor does the cursor move in any way.

This problem doesn't appear unique to `readline`; it also happens for `read(STDIN, UInt8)`.

**Comment by H-225** [comment]
I'll also note that anything you do type while Julia waits for input, is entered into the shell after you kill the julia process.

```
$ julia-dev
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.1861 (2017-01-03 16:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1c657f0* (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> read(STDIN, UInt8) # type `echo 1` and press enter - then kill process

$ echo 1
1

$
```

**Comment by musm** [comment]
I can't even kill the process using `ctrl+d or ctrl+z`
This is a serious regression/bug.

**Comment by H-225** [comment]
Likewise. Had to hold down `CTRL+C`.

**Comment by ChrisRackauckas** [comment]
I just gave this a try and yes, it hangs for me too. I think this is what's breaking `Pkg.update()` on Windows: https://github.com/JuliaLang/julia/issues/19717 .

**Comment by tkelman** [comment]
Can you try with older nightlies from http://julianightlies.s3.amazonaws.com/ ? Or bisect on a source build if you have one. The nightlies should go back as far as about a month.

**Comment by H-225** [comment]
I checked some nightlies. [This one](http://julianightlies.s3.amazonaws.com/bin/julia-0.6.0-8fdea47fd9-win64) is the first one that worked.

```
> julia-nightly\bin\julia.exe
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.1251 (2016-12-08 14:00 UTC)
 _/ |\__'_|_|_|\__'_|  |  master/8fdea47 (fork: 10 commits, 51 days)
|__/                   |  x86_64-w64-mingw32

julia> readline()

"\r\n"

julia>
```

I'll note that, while I didn't look at all of them, all the newer ones I specifically looked at that are newer than this one indicate that they are *not* part of a fork, unlike this one.

**Comment by tkelman** [comment]
Thanks! That looks like it was manually built off a branch. The master parent of 8fdea47 is https://github.com/JuliaLang/julia/commit/80770e955906c8cdbcfaf2ea73ed772195429aad, so this broke some time since November. Can you go further back in the ones that are from master?

**Comment by H-225** [comment]
It is rather unfortunate that I was unable to test this automatically; it does not happen if another process writes to STDIN - I am grateful to who whoever told us about the binary search. >)

I was able to determine that the newest failing commit is 806fb92bb4da23363f81471ac84a1efffbc90d2d.
```
$ git log -1
commit 806fb92bb4da23363f81471ac84a1efffbc90d2d
Merge: d9d0fad f8bafae
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Tue Nov 15 20:37:29 2016 -0500

    Merge pull request #19152 from JuliaLang/jn/io-poll-faster

    replace calls to libuv stop with faster deferred operations

$
```

cc @vtjnash

**Comment by musm** [comment]
0.6 milestone?

**Comment by tkelman** [comment]
We know what commit caused it, we can try reverting it and adding a test.

**Comment by musm** [comment]
shameless bump

**Comment by StefanKarpinski** [comment]
Agree, we can just revert that commit. cc @vtjnash
