### ISSUE TITLE
Build broken with `No docs found for 'Base.Dates.CompoundPeriod'`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#19848]
From what I can tell this is causing master and all PR builds to fail (at least on travis). I'm not sure what's going on, since the change that seems to have caused this passed CI. However I think it would be good to make errors like this non-fatal so other tests can run.

**Comment by tkelman** [comment]
It passed CI several months ago, but not since. If these are non fatal, no one will ever see or fix them.
