### ISSUE TITLE
Compact printing of Array{Char}s?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#19845]
@alanedelman brought up that `Array{Char}`s can be useful for summarizing numerical arrays but that it would be better if the printing of `Array{Char}` was more compact. I.e. instead of
```jl
julia> A = randn(10,10);

julia> ['+', '-'][(A .> 0) + 1]
10×10 Array{Char,2}:
 '+'  '-'  '-'  '-'  '-'  '-'  '-'  '+'  '+'  '-'
 '-'  '-'  '-'  '-'  '-'  '+'  '-'  '+'  '+'  '+'
 '-'  '+'  '+'  '+'  '+'  '+'  '-'  '-'  '-'  '+'
 '-'  '+'  '-'  '+'  '-'  '+'  '-'  '+'  '+'  '-'
 '-'  '-'  '+'  '+'  '-'  '-'  '-'  '-'  '+'  '-'
 '-'  '-'  '+'  '+'  '-'  '+'  '+'  '-'  '-'  '-'
 '+'  '-'  '+'  '+'  '-'  '+'  '+'  '-'  '+'  '-'
 '-'  '-'  '-'  '+'  '+'  '-'  '+'  '-'  '-'  '-'
 '-'  '-'  '-'  '-'  '+'  '+'  '-'  '-'  '+'  '-'
 '-'  '-'  '+'  '+'  '-'  '+'  '+'  '-'  '+'  '-'
```
it was proposed that we follow our competitor and print it like
```jl
julia> print(join(mapslices(String, ['+', '-'][(A .> 0) + 1], 2), '\n'))
+------++-
-----+-+++
-+++++---+
-+-+-+-++-
--++----+-
--++-++---
+-++-++-+-
---++-+---
----++--+-
--++-++-+-
```
Thoughts?

**Comment by stevengj** [comment]
That works well if all the chars have `charwidth(c) == 1`, but it seems problematic in other cases.

Also is a bit problematic if you have a lot of whitespace chars.

**Comment by andreasnoack** [comment]
Would it make sense to adjust the width of each "cell" to the maximum `charwidth` of the array? There seems to be something wrong with wide characters in the mac terminals, though, so I don't know if it is yet possible to make special characters look good in the terminal.

<img width="664" alt="screen shot 2017-01-03 at 8 28 00 pm" src="https://cloud.githubusercontent.com/assets/505001/21629118/328e92b8-d1f3-11e6-9ae0-533df1edd75e.png">

**Comment by stevengj** [comment]
@andreasnoack, that's #3721.  It seems to be really hard to solve unless the whole software stack (terminal on up) agrees on the width of the characters.

**Comment by stevengj** [comment]
Also, charwidth-0 characters (e.g. combining characters) are going to look odd.

**Comment by TotalVerb** [comment]
@stevengj combining characters already print odd (they combine with the initial single quote), so that will not be a new issue.

**Comment by oscardssmith** [comment]
given variable width chars, this is probably a bad idea.
