### ISSUE TITLE
svds documentation doesn't explain how to extract factors

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#19857]
Now that we use the `SVD` type to store the result of `svds`, we should explain the `SVD` type in the doc string for `svds`. We can probably find inspiration in the doc string for `svdfact`.

Update: It would also be good to extend with more examples.

**Comment by akaysh** [comment]
#20829

**Comment by andreasnoack** [comment]
Tracked in https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/18
