### ISSUE TITLE
speed.julialang.org now obsolete?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#19853]
The page [Julia Performance Monitoring](https://github.com/JuliaLang/julia/tree/master/test/perf) refers to a site `speed.julialang.org` which doesn't work (any more— presumably it used to once).

![screen shot 2017-01-04 at 07 51 37](https://cloud.githubusercontent.com/assets/52289/21634962/af386f78-d252-11e6-9f93-27fb81371594.png)

Also, the page refers to the abandoned [Benchmark](https://github.com/johnmyleswhite/Benchmark.jl) package.

**Comment by andreasnoack** [comment]
cc: @jrevels. You might want the opportunity to advertise for your stack here.

**Comment by ViralBShah** [comment]
In either case, we should remove the mentions.
