### ISSUE TITLE
Re-exporting one module's symbols from another

### ISSUE THREAD

**Issue by dcjones** [JuliaLang/julia#1986]
It would be convenient if there were a way to do this.

``` julia
module A
    export lots, of, stuff
    # ...
end

module B
    using A
    # magically export everything that was just imported from A
end
```

Doing this explicitly (copy the long list of exports from A into B) is a bit ugly and error prone. I imagine any alternative would involve a new keyword though.

Concretely, Gadfly is useless without symbols from Compose (and probably DataFrames), but a bunch of compulsory using statements isn't great.

**Comment by vtjnash** [comment]
Needs some design thoughts to figure out how we want this to work and interact with `using` / `import` / `importall` / etc.

**Comment by timholy** [comment]
Crossref #14472

**Comment by vtjnash** [comment]
I put together a macro implementation of something like this for one of my PRs as a demo: https://github.com/JuliaLang/julia/pull/22147/files#diff-4fc3422b2208cb02c3e17c7cc0a56446R44

**Comment by Keno** [comment]
Seems feature-y. There might be syntax we could want, but we if that does happen we can live with  a macro until 2.0.

**Comment by ip1981** [comment]
Re-export is evil.

**Comment by rapus95** [comment]
how about introducing the import/using syntax to export aswell? I.e.
```julia
using B
export B: *
```
for reexporting all exported identifiers from B
That would even allow exporting `as` something else 🤯 :D

**Comment by ViralBShah** [comment]
Is Reexport.jl still the recommended way to do this? Lots of packages are using it, and seems to work fine. If there isn't anything we are planning to do here, we can close this.

**Comment by vtjnash** [comment]
yes, Reexport.jl seems like an okay way to do this. The names are easy enough to get via reflection and eval into the current module
