### ISSUE TITLE
add special display for ≈ test failures

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19898]
As noted by @cstjean in https://github.com/JuliaLang/julia/pull/19880, `@test a ≈ b` differs from `@test_approx_eq a b` in that the former doesn't display test failures quite as nicely. We already have [specialized code](https://github.com/JuliaLang/julia/blob/5d90ab6f1407ff934825cfa234f8db378ec1161e/base/test.jl#L107-L111) for displaying some kinds of comparisons nicely, so perhaps we should have more logic there to display approximate equality failures as nicely as `@test_approx_eq` does.

**Comment by indexfrom0** [comment]
HELLO STEFAN. THANK YOU STEFAN. GOOD NIGHT STEFAN.

**Comment by akaysh** [comment]
@StefanKarpinski I would like to work on this. A little more info on what is to be done?

**Comment by Moelf** [comment]
```
julia> using Test

julia> @test 2.1 ≈ 1+1
Test Failed at REPL[2]:1
  Expression: 2.1 ≈ 1 + 1
   Evaluated: 2.1 ≈ 2
ERROR: There was an error during testing

julia> @test 2.1 == 1+1
Test Failed at REPL[3]:1
  Expression: 2.1 == 1 + 1
   Evaluated: 2.1 == 2
ERROR: There was an error during testing
```

looks find on master now?

**Comment by omus** [comment]
I believe this was addressed by https://github.com/JuliaLang/julia/pull/30721
