### ISSUE TITLE
replace `@test_approx_eq_eps` with another idiom

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19899]
Part of https://github.com/JuliaLang/julia/issues/4615. Now that `@test_approx_eq` has been [deprecated and removed](https://github.com/JuliaLang/julia/pull/19880) from our test suite, the next step is to replace all uses of `@test_approx_eq_eps` from the test suite and deprecate that macro in a similar fashion. Possible replacement for `@test_approx_eq_eps a b ɛ`:

```jl
@test ≈(a, b, atol = ɛ)
```

I kind of wish there was a nicer way to write that, but I'm not sure that there is.

**Comment by vtjnash** [comment]
`@test abs(a - b) < ɛ` ?

**Comment by StefanKarpinski** [comment]
One idea: change the `@test` macro (and `@test_{throws,broken,skip}` too) to accept zero or more trailing arguments of the form `x=y` which, if the test if a `call` form, are passed as keyword arguments to the call, even when it's not expressed using call syntax. That would allow writing:

```jl
@test a ≈ b atol=ɛ
```

**Comment by StefanKarpinski** [comment]
`abs` is no longer automatically vectorized and `<` never has been, so it would have to be something a bit more like this:

```jl
@test maximum(abs, a - b) < ɛ
```

Perhaps that's better since it's far more explicit about what the test is actually checking.

**Comment by vtjnash** [comment]
Or maybe `reduce(maxabs, a - b)`?

**Comment by andreasnoack** [comment]
`norm`?

**Comment by StefanKarpinski** [comment]
We also deprecated `maxabs`, so that won't work either.

**Comment by StefanKarpinski** [comment]
`norm` might be the right thing to check, but that's certainly not what the tests currently check, so that would not be a straightforward search-and-replace by any means.

**Comment by ararslan** [comment]
Would `@test isapprox(a, b, atol=ɛ)` not suffice? It's just the tolerance-provided version of `≈`, which we're already using in place of `@test_approx_eq`.

**Comment by StefanKarpinski** [comment]
Yes, I was just proposing a slightly nicer syntax for that kind of thing. Not sure if it's worth it.
