### ISSUE TITLE
0 .< A .< 1 gives deprecation warning in 0.6

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLang/julia#19891]
on 0.6.0-dev.1950 (Win 64), 
`0 .< randn(2,3) .< 1`
gives a warning about A & B being deprecated, and suggests using A .& B instead

**Comment by martinholters** [comment]
```Julia
julia> expand(:(a .< b .< c))
:((Base.broadcast)(<,a,b) & (Base.broadcast)(<,b,c))
```
but should be either
```julia
:((Base.broadcast)(<,a,b) .& (Base.broadcast)(<,b,c))
```
or even better
```julia
:((Base.broadcast)((x1,x2,x3) -> x1<x2<x3, a, b, c))
```
where the OP example is slightly more complicated in that it also involves numeric literals that should additionally still get their special treatment.

**Comment by Shade5** [comment]
Can I work on this?

**Comment by tkelman** [comment]
You don't have to ask permission to try. Are you able to find where in the code this happens, change it, and write a test case that would have triggered the warning before on master but doesn't after your change? If not, where do you need help?

**Comment by Shade5** [comment]
Sure :) just confirming that no one else was working on it.

**Comment by Shade5** [comment]
I tried a lot but can't figure out! :(
Which function turns this `a .< b .< c` to this `(Base.broadcast)(<,a,b) & (Base.broadcast)(<,b,c)` for evaluation?

**Comment by tkelman** [comment]
```
julia> expand(:(A .< B .< C))
:((Base.broadcast)(<,A,B) & (Base.broadcast)(<,B,C))
```
In terms of the source code, I'm pretty sure it's here, part of the scheme parsing/lowering: https://github.com/JuliaLang/julia/blob/c5f8375249293a2426648d6ec14184f4bf371432/src/julia-syntax.scm#L83

**Comment by Shade5** [comment]
https://github.com/JuliaLang/julia/pull/19928
