### ISSUE TITLE
Dates defines nonsensical conversions

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#19896]
I've posted this kind of thing elsewhere about other unitful quantities, but just noticed that we have the same problem with dates. Succinct example:
```jl
julia> d = convert(Dates.Day, 1)
1 day

julia> convert(Int, d)
1
```
Seems OK, right? But consider:
```jl
julia> s = convert(Dates.Second, d)
86400 seconds

julia> convert(Dates.Second, convert(Int, d))
1 second
```
You can get two wildly different answers when you convert days to seconds this way. The only sensible approach is not to define conversions between unitless and unitful objects.

**Comment by nalimilan** [comment]
Or to define such conversions only in one direction (probably the one from unitful to unitless?).

**Comment by TotalVerb** [comment]
See also #16109, #10451, #15934.

**Comment by timholy** [comment]
@nalimilan, I don't think they can be defined at all. Consider:
```jl
julia> d = convert(Dates.Day, 1)
1 day

julia> d == 1
false
```
Saying that you can `convert` one object to another type, but then to have those two not be equal, is pretty confusing. One should force people to explicitly use a constructor (`Dates.Day(1)`), which is a computer science construct, not something with physical meaning.

**Comment by martinholters** [comment]
Attaching units and removing _specific_ units are reasonable operations, but just removing any units from a quantity is usually dangerous and should not be easily available. "I know the computation lasted for 6.2, but I don't care whether it were seconds or hours."---That doesn't seem right.

And I also agree that attaching units should not be a `convert`, but maybe a constructor.
