### ISSUE TITLE
Update stable windows download to 0.5

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#19907]
This link http://status.julialang.org/stable/win64 still returns 0.4.x binaries, could that be switched over to 0.5.x binaries?

**Comment by tkelman** [comment]
status.julialang.org is deprecated

**Comment by davidanthoff** [comment]
Is there a new URL that will download the latest stable win binaries?

**Comment by tkelman** [comment]
there is a -latest url for each minor series

**Comment by davidanthoff** [comment]
Hm, having a URL that gave me the overall latest stable binary was quite handy, I used it in my auto-julia-update powershell script. Not a deal breaker, especially given that we don't seem to see many patch versions lately in any case, but if if could be easily enabled again, it would be nice.

**Comment by nalimilan** [comment]
I think that's exactly what Tony meant: https://s3.amazonaws.com/julialang/bin/winnt/x64/0.5/julia-0.5-latest-win64.exe

**Comment by davidanthoff** [comment]
I'd like a link that has no version info in it, like the original one I posted. The links you have are 0.5 specific.

**Comment by tkelman** [comment]
I'd be highly suspect of anything that auto-updates across breaking versions. Reopen at https://github.com/staticfloat/status.julialang.org/issues

**Comment by davidanthoff** [comment]
It is a user triggered update, essentially I have a update-julia power shell command that keeps my binaries up to date when I want them to be. Really handy with lots of machines. I'll follow up in the other repo.
