### ISSUE TITLE
zip as its own inverse

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#19917]
`?zip` says
```
Note that zip is its own inverse: collect(zip(zip(a...)...)) == collect(a).
```
but, at least in `0.5.0`, 
```julia
a = (1:3,1:3)
collect(zip(zip(a...)...)) == collect(a)
```
is false because the RHS is left as `(1:3,1:3)` and LHS is `((1,2,3),(1,2,3))`.

The docstring is misleading as is. It works if `a` is a tuple of tuples (eg `a = ((1,2,3),(1,2,3))`).

Slightly related (but not the only thing making it unqeual): #7867.

**Comment by TotalVerb** [comment]
The `collect` here is supposed to handle that, but of course `collect` only collects one level. It could be repaired by using `map(collect, collect(zip(zip(a...)...))) == map(collect, collect(a))`.

**Comment by mschauer** [comment]
Obsolete via #23162
