### ISSUE TITLE
Optionally treat NaNs as equal to each other in isapprox

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#19936]
`@test_approx_eq` has been deprecated by #19880, now the suggested way to compare numbers is `@test isapprox(a ,b)` (or some other fancy Unicode syntax).  However, `@test_approx_eq` had a feature that `isapprox` is missing: `@test_approx_eq NaN NaN` didn't error.  When performing tests, it makes sense to treat `NaN`s as equal (i.e., what `isequal` does): even if `isnan` is available, having `isapprox` dealing nicely with `NaN`s may be useful for cases like `isapprox([1, NaN, Inf], [1, NaN, Inf])`, where there is a mixture of numbers and not-numbers.

My suggestion: optionally have `isapprox` treat `NaN` values as equal to each other (maybe only in tests).

A bit of background: in a package of mines I have a test where I was using `@test_approx_eq`, relying on the fact that it treated `NaN`s as equal.  When I moved to `@test` + `isapprox` I had to define a new method for a custom type in the testing suite and now I'm fine.  With this ticket my aim is not to advocate for this feature, because I currently don't need it, but to suggest a possible improvement to `isapprox` that may be useful above for testing.

**Comment by yuyichao** [comment]
This also affects `Images.jl`.

**Comment by JeffreySarnoff** [comment]
Make sense to me.

```
function isapprox(x::Number, y::Number; 
                  rtol::Real=rtoldefault(x,y), atol::Real=0, nans::Bool=false)
    x == y ||
    (isfinite(x) && isfinite(y) && abs(x-y) <= atol + rtol*max(abs(x), abs(y))) ||
    (nans && (isnan(x) & isnan(y)))
end
```

```
julia> anan = NaN
julia> isapprox(anan, anan)
false
julia> isapprox(anan, anan, nans=true)
true
```

**Comment by StefanKarpinski** [comment]
I guess we should really do this in this release since we're deprecating `@test_approx_eq`.

**Comment by StefanKarpinski** [comment]
What should we call this keyword? `nans=true/false` is a bit terse but `nanseq` is kind of ugly.

**Comment by StefanKarpinski** [comment]
I guess `nans=true/false` is ok in the interpretation that `nans` refers to the comparison `NaN ≈ NaN` and the value indicates whether that comparison is true or false.

**Comment by JeffreySarnoff** [comment]
That was my intent. Also nanseq, reads like "nan sequence", so `nans` or `eqnans` unless `nansequiv`.

**Comment by JeffreySarnoff** [comment]
I have prepared candidate changes, if you would like to take a look: 
[https://github.com/JeffreySarnoff/julia/blob/js/isapprox/base/floatfuncs.jl](https://github.com/JeffreySarnoff/julia/blob/js/isapprox/base/floatfuncs.jl)
[https://github.com/JeffreySarnoff/julia/blob/js/isapprox/test/floatfuncs.jl](https://github.com/JeffreySarnoff/julia/blob/js/isapprox/test/floatfuncs.jl)
Or I could submit them as a PR.

**Comment by StefanKarpinski** [comment]
A PR would be lovely!

**Comment by JeffreySarnoff** [comment]
[PR #20022](https://github.com/JuliaLang/julia/pull/20022)

**Comment by tkelman** [comment]
Thanks @JeffreySarnoff !
