### ISSUE TITLE
Strange behavior when overwritten functions are passed as parameters

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#19952]
Hi guys!

I found a strange behavior (to me) when dealing to redefined functions in julia that are passed as parameters to other functions. For example, consider the following code:

```julia
function test_abs(func)
    abs(func())
end

function test_val()
    -3.0
end
println(test_abs(test_val))

function test_val()
    -2.0
end
println(test_abs(test_val))
println(test_val())
```

I really would expect to see this output:

```
3.0
WARNING: Method definition test_val() in module Main at test.jl:6 overwritten at test.jl:12.
2.0
-2.0
```

However, I am seeing this:

```
3.0
WARNING: Method definition test_val() in module Main at test.jl:6 overwritten at test.jl:12.
3.0
-2.0
```

Even if the function `test_val` is overwritten, when I call `test_abs(test_val)` it uses the first definition. I have no idea why this code should not work as I was expecting.

**Comment by nalimilan** [comment]
This was #265. The good news is that it works as you expect on git master.

**Comment by ronisbr** [comment]
@nalimilan thanks! I just checked and it was working as I expect in julia 0.4.7 also.

**Comment by nalimilan** [comment]
Yes, it was working on 0.4 but for different reasons (because methods were not specialized on functions passed as arguments).
