### ISSUE TITLE
Segfault and/or abort on bogus huge array allocation

### ISSUE THREAD

**Issue by DemiMarie** [JuliaLang/julia#19956]
The following code segfaults:

```julia
zeros(UInt64, 1 << 61) # or 62
```
This crashes with SIGABRT:
```julia
zeros(UInt64, 1 << 63)
```

Obviously none of these can succeed, but they should throw an exception rather than crashing.

`julia --version` gives `julia version 0.5.0`

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/18274
