### ISSUE TITLE
Poor performance of Threads.@threads, 4 orders slower

### ISSUE THREAD

**Issue by dehann** [JuliaLang/julia#19967]
After reading blogs issues and user forums I thought it worth while posting this performance issue. ```Threads.@threads``` seem very very very slow:
```julia
using Base.Test

@show Threads.nthreads()

function ff!(ret::Vector{Float64}, x::Vector{Float64}, i::Int)
  ret[i] = x[i]
  nothing
end

N = 12
a = randn(N)
r = zeros(N)
 # compile code
@time for i in 1:N  
  ff!(r,a,i)
end 
Threads.@threads for i in 1:N  ff!(r,a,i)  end

# get output
r = zeros(N)
@time for i in 1:N  ff!(r,a,i)  end     
r = zeros(N)
@time for i in 1:N  ff!(r,a,i)  end
@test norm(r-a) < 1e-10

r = zeros(N)
@time Threads.@threads for i in 1:N  ff!(r,a,i)  end
r = zeros(N)
@time Threads.@threads for i in 1:N  ff!(r,a,i)  end
@test norm(r-a) < 1e-10
```
Output:
```
Threads.nthreads() = 4
...
0.000014 seconds (13 allocations: 416 bytes)
0.000021 seconds (13 allocations: 416 bytes)
0.027476 seconds (4.14 k allocations: 189.999 KB)
0.025677 seconds (4.14 k allocations: 190.030 KB)
```
This shouldn't be a [type stability thing](http://julia-programming-language.2336112.n4.nabble.com/poor-performance-of-threads-td36897.html)? It would be great to use ```Threads``` for ```for loops``` of around 100 to 500 elements in an efficient manner.

Ubuntu 12.04.4, using generic binary file download from julialang.org.
```julia
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3920XM CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```
Thanks for the great work, I'm a big supporter.

**Comment by JeffBezanson** [comment]
This is probably compilation time; in `Threads.@threads for i in 1:N  ff!(r,a,i)  end` the whole expression has to be compiled. We don't yet recognize that an identical expression has been entered before to reuse its code.

**Comment by dehann** [comment]
Would it help if I dive lower down into ```@threads``` macro and use more native function calls? Maybe some of that code could eventually make it into documentation or elsewhere for general consumption. I already use ```remotecall```, ```@async``` and ```@sync``` quite a lot. I was hoping to use threads to further improve performance on a per process basis. I have plenty sub 1000 ```for-loops``` inside each process.

**Comment by yuyichao** [comment]
This is due to compilation and you are also benchmarking in global scope that uses non-const globals.

There isn't anything lower level than `@threads` to be exposed. More flexible threading construct is a 1.0 goal.
