### ISSUE TITLE
jl_free(NULL) crashes

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#19963]
At the moment julia crashes when `jl_free` is called with a null pointer. The standard (see C99 section 7.20.2.3) says that if a null pointer is provided, no action occurs.

We encountered this while wrapping a C library, which we hooked up with julias memory functions.

The following minor change to `jl_free` should fix it.

```c
JL_DLLEXPORT void jl_free(void *p)
{
    int64_t *pp; 
    size_t sz;

    if (p != NULL) {
        pp = (int64_t *)p - 2; 
        sz = pp[0];
        jl_gc_counted_free(pp, sz); 
    }    
}
```

**Comment by JeffBezanson** [comment]
Thanks. Would you be willing to open a pull request with that change?

**Comment by thofma** [comment]
Sure, see #19969. Just wanted to make sure my fix does not have unwanted side effects.
