### ISSUE TITLE
Pkg.add() behind the proxy fails with 'No Content-Type header in response' (RHEL 7.1)

### ISSUE THREAD

**Issue by mi-volodin** [JuliaLang/julia#19978]
I have RHEL 7 distribution behind a proxy. I installed julia using official documentation and everything seemed to be fine.

Here's the yum listing (note, libgit2 is 0.23.1)

```
Installed:
  julia.x86_64 0:0.5.0-1.el7.centos

Dependency Installed:
  arpack.x86_64 0:3.1.3-2.el7
  atlas.x86_64 0:3.10.1-7.el7
  dSFMT.x86_64 0:2.2.3-4.el7.centos
  fftw-libs-double.x86_64 0:3.3.3-8.el7
  http-parser.x86_64 0:2.7.1-3.el7
  julia-common.noarch 0:0.5.0-1.el7.centos
  julia-devel.x86_64 0:0.5.0-1.el7.centos
  libgit2.x86_64 0:0.23.3-1.el7.centos
  llvm3.7-libs.x86_64 0:3.7.1-3.el7.centos
  openblas-threads.x86_64 0:0.2.19-4.el7
  openlibm.x86_64 0:0.5.3-1.el7
  openspecfun.x86_64 0:0.5.3-1.el7
  pcre2.x86_64 0:10.21-11.el7
  suitesparse.x86_64 0:4.4.5-2.el7.centos
  tbb.x86_64 0:4.1-5.20130314.el7
  utf8proc.x86_64 0:2.0.2-1.el7.centos

Complete!
```

However, the further Pkg.add("IJulia") invocation failed on METADATA.jl cloning. 

```
julia> Pkg.add("IJulia")
INFO: Initializing package repository /root/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, No Content-Type header in response)
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCr                                              edentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in add(::String) at ./pkg/pkg.jl:100
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

I decided to post it as a bug, because 
1. Proxy settings seems to work fine. Without environment variables HTTP_PROXY/HTTPS_PROXY being set I'm getting the error `Failed to connect`, not the one posted above.
2. Git is also configured fine. And actually, I overrulled Pkg.init() by manually running this code with `run()`: `git clone [github]/METADATA.jl [HOME]/.julia/v.0.5/METADATA`.
3. I haven't find similiar errors in already posted issues.

**Comment by tkelman** [comment]
Any difference in behavior if you use the generic linux binaries?

**Comment by mi-volodin** [comment]
Hm... Yes, there's a difference.

What I did:
1. Erased julia with yum `sudo yum erase julia`
2. Downloaded binaries, extracted it and added path to PATH.
3. Now it almost works... at least with github.

So... even if there are instructions regarding RHEL, it's better to use generic binaries, isn't it?

Thanks for the solution.

**Comment by tkelman** [comment]
cc @nalimilan do you have a better place than here to report packaging-specific issues like this one?

Confirming [my general dislike](https://github.com/JuliaLang/julialang.github.com/pull/475) of the differences in distro packaging build configurations resulting in missing or broken functionality.

**Comment by nalimilan** [comment]
> cc @nalimilan do you have a better place than here to report packaging-specific issues like this one?

Sure, my mailbox (as advised on the Cop page). :-) We could stress on the webpage that reports should go directly to the package maintainers. But if you don't mind I can investigate this one here.

> Confirming my general dislike of the differences in distro packaging build configurations resulting in missing or broken functionality.

I have to admit this is unfortunate for my argument in favor of recommending the Copr repo. OTOH, reports like these allow catching bugs which would appear in distributions, and people will end up using distro packages for Julia whatever we think/say about it (especially after 1.0).

Regarding this particular issue, this is probably due to the Copr providing the old libgit2 0.23. @mi-volodin Could you retry the julia Copr package? It should install libgit2 0.24 now.

**Comment by mi-volodin** [comment]
@nalimilan 
Maybe I'm doing something wrong, but manually installing libgit2 with `yum` upgrades it to 0.24, however further installation of `julia` fails, because dependency set to 0.23.

Erase of libgit2, clean, then `yum install julia` prints the following proposal

```
Dependencies Resolved

==============================================================================================================================
 Package                     Arch                  Version                               Repository                      Size
==============================================================================================================================
Installing:
 julia                       x86_64                0.5.0-1.el7.centos                    nalimilan-julia                 12 M
Installing for dependencies:
 julia-common                noarch                0.5.0-1.el7.centos                    nalimilan-julia                915 k
 julia-devel                 x86_64                0.5.0-1.el7.centos                    nalimilan-julia                1.3 M
 libgit2                     x86_64                0.23.3-1.el7.centos                   nalimilan-julia                409 k

Transaction Summary
==============================================================================================================================
Install  1 Package (+3 Dependent packages)
```

**Comment by nalimilan** [comment]
The package cache has probably not been updated yet. Try with the `--refresh` option.

**Comment by mi-volodin** [comment]
Hmm. Where should I apply this option? `yum clean all` cleans the repository cache. But there's no option `--refresh` for yum.

That's strange... yum install still propose me the 0.23 version. However, dependency check is different
```
# yum deplist julia | grep libgit
  dependency: libgit2.so.24()(64bit)
   provider: libgit2.x86_64 0.24.6-1.el7.centos
```

I'll try to find out why.

**Comment by nalimilan** [comment]
Sorry, `--refresh` only works with `dnf`, on RHEL7 you need to use `yum clean expire-cache` instead. But the output you show below seems to indicate that yum has detected libgit2 0.24 now. Is it installed too (`ldd /usr/bin/julia` should tell you which version is used)?

**Comment by mi-volodin** [comment]
:) No sign of libgit2

```
# ldd /usr/bin/julia
        linux-vdso.so.1 =>  (0x00007fff469fe000)
        libjulia.so.0.5 => /usr/bin/../lib64/libjulia.so.0.5 (0x00007fc7d9faa000)
        libdl.so.2 => /usr/bin/../lib64/libdl.so.2 (0x00007fc7d9da5000)
        librt.so.1 => /usr/bin/../lib64/librt.so.1 (0x00007fc7d9b9d000)
        libpthread.so.0 => /usr/bin/../lib64/libpthread.so.0 (0x00007fc7d9981000)
        libc.so.6 => /usr/bin/../lib64/libc.so.6 (0x00007fc7d95bf000)
        libutf8proc.so.2 => /usr/bin/../lib64/libutf8proc.so.2 (0x00007fc7d9376000)
        libLLVM-3.7.1.so => /usr/lib64/llvm3.7/libLLVM-3.7.1.so (0x00007fc7d7082000)
        libstdc++.so.6 => /usr/bin/../lib64/libstdc++.so.6 (0x00007fc7d6d7a000)
        libm.so.6 => /usr/bin/../lib64/libm.so.6 (0x00007fc7d6a78000)
        libgcc_s.so.1 => /usr/bin/../lib64/libgcc_s.so.1 (0x00007fc7d6862000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc7da56b000)
        libz.so.1 => /usr/bin/../lib64/libz.so.1 (0x00007fc7d664b000)
        libffi.so.6 => /usr/bin/../lib64/libffi.so.6 (0x00007fc7d6443000)
        libtinfo.so.5 => /usr/bin/../lib64/libtinfo.so.5 (0x00007fc7d6219000)
```

**Comment by mi-volodin** [comment]
May I suggest, that the problem might be in duplicates. 
Libgit version is different and hence `yum` sees the difference.
However, there are two `julia` packages that seems to be the same. `yum` might select just particular one, which has wrong dependency.

**Comment by nalimilan** [comment]
OK, looks like rebuilding the package with the same version wasn't a good idea as it confuses yum. I've built a package with version 0.5.0-2, and now it seems to work in a VM.

**Comment by mi-volodin** [comment]
Yep. Installed. And working nicely.

**NOTE** THe build is still different from generic. `Pkg.add("IJulia")` thrown an Error and requested manual `Pkg.init()`. Previously first call of `Pkg.add()` automatically performed `Pkg.init()`. However, it worked just the same as the generic version.

**MAIN QUESTION** Which one should I continue to use? 😄

**Comment by nalimilan** [comment]
Cool. I don't understand how it could differ WRT calling `Pkg.init` automatically. Are you sure this isn't because the package dir has been created by previous attempts?

Use either version as you see fit. As Tony noted, bugs can appear with Copr packages which would not exist with generic binaries, but if you report them to me (via e-mail please) I'll try to fix them. In general the experience should be pretty similar.

**Comment by mi-volodin** [comment]
@nalimilan where can I find the e-mail?

**Comment by nalimilan** [comment]
About everywhere on the Internet, but in particular at https://copr.fedorainfracloud.org/coprs/nalimilan/julia/.

**Comment by mindis** [comment]
Had same issue on Centos 7 using platform specific binaries.  Had to remove and install generic linux binaries to work.
