### ISSUE TITLE
Pkg.update() fails on what appears to be a clean automatic install on Linux

### ISSUE THREAD

**Issue by vics0000** [JuliaLang/julia#19982]
```
julia> Pkg.update()
INFO: Updating METADATA...
ERROR: METADATA cannot be updated. Resolve problems manually in /home/somepath/.julia/v0.5/METADATA.
GitError(Code:ERROR, Class:Net, No Content-Type header in response)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in #fetch#52(::Base.LibGit2.FetchOptions, ::String, ::Function, ::Base.LibGit2.GitRemote, ::Array{AbstractString,1}) at ./libgit2/remote.jl:70
 in (::Base.LibGit2.#kw##fetch)(::Array{Any,1}, ::Base.LibGit2.#fetch, ::Base.LibGit2.GitRemote, ::Array{AbstractString,1}) at ./<missing>:0
 in #fetch#93(::String, ::String, ::Array{AbstractString,1}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:164
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

Linux OS info:
```
shell> uname -or
3.10.0-514.2.2.el7.x86_64 GNU/Linux

shell> cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by tkelman** [comment]
What does
```
cd /home/somepath/.julia/v0.5/METADATA
git status
```
say?

**Comment by vics0000** [comment]
I get:

[whatwins@vps2 METADATA]$ git status
# On branch metadata-v2
# Your branch is behind 'origin/metadata-v2' by 19 commits, and can be 
fast-forwarded.
#   (use "git pull" to update your local branch)
#
nothing to commit, working directory clean

Thanks, Dave Vicary

WhatWins Inc.
Softphone: (613) 454-8213
Mobile:    (613) 857-2117
Skype:     Dave.Vicary2

**Comment by vics0000** [comment]
I did a git pull and now git status is giving me:

    [whatwins@vps2 METADATA]$ git status
    # On branch metadata-v2
    nothing to commit, working directory clean

I then went back into julia and tried Pkg.update() but got the same 
error message as previous...

Thanks, Dave Vicary

WhatWins Inc.
Softphone: (613) 454-8213
Mobile:    (613) 857-2117
Skype:     Dave.Vicary2

**Comment by mpastell** [comment]
Is this the same issue as in #19978?

**Comment by vics0000** [comment]
You tell me, is there a solution/fix I can try?

Thanks, Dave Vicary

WhatWins Inc.
Softphone: (613) 454-8213
Mobile:    (613) 857-2117
Skype:     Dave.Vicary2

**Comment by vics0000** [comment]
I believe the difference is this is not tied to any specific package but 
an ERROR when executing Pkg.update(). They may be related in that a fix 
for this generic issue may also fix Pkg specific issues.

Thanks, Dave Vicary

WhatWins Inc.
Softphone: (613) 454-8213
Mobile:    (613) 857-2117
Skype:     Dave.Vicary2

**Comment by tkelman** [comment]
Where did you install Julia from? What does `Pkg.status()` say?

**Comment by vics0000** [comment]
Hi Tony,
I just did a completely new install and the issue seems to have been resolved - I will close, thanks for investigating.
