### ISSUE TITLE
should allocation tracking ignore compilation by default?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19981]
When using `--track-allocation` it's almost impossible to coax it into not putting a bogus looking large allocation on the first line of each function, which presumably is due to compilation kicking in when the function first runs. Can we turn off allocation tracking when we enter the compiler and then turn it back on once we've left compilation? Perhaps `--track-allocation=user` should exclude compilation time and `--track-allocation=all` should include it?

**Comment by vchuravy** [comment]
> The recommended procedure is to force compilation by executing all the commands you want to analyze, then call `Profile.clear_malloc_data()` to reset all allocation counters. Finally, execute the desired commands and quit Julia to trigger the generation of the .mem files.

Maybe we should make the above more prominent in http://docs.julialang.org/en/stable/manual/profile/#memory-allocation-analysis?

**Comment by StefanKarpinski** [comment]
Wouldn't it be better (if possible) to just do the right thing by default?
