### ISSUE TITLE
different Dicts hash to same value

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#19995]
As reported [on discourse](https://discourse.julialang.org/t/different-dicts-hashing-to-the-same-value/1441), it looks like there is a bug in `hash(a::Associative, h::UInt)`:
```jl
hash(Dict(Dict(1=>2) => 3, Dict(4=>5) => 6)) == hash(Dict(Dict(4=>5) => 3, Dict(1=>2) => 6))
```
returns `true` even though the dictionaries are different.

**Comment by stevengj** [comment]
Note that it seems specific to `Dict` keys.  `hash(Dict(1 => 3, 4 => 6)) == hash(Dict(4 => 3, 1 => 6))` returns `false` as expected, as does `hash(Dict(3 => Dict(1=>2), 6 => Dict(4=>5))) == hash(Dict(3 =>  Dict(4=>5), 6 => Dict(1=>2)))`.

**Comment by stevengj** [comment]
@ScottPJones found an easy fix for this: https://github.com/ScottPJones/julia/commit/8a2a8696846962b1202e6dc630ba56094e14ce44

**Comment by StefanKarpinski** [comment]
We should cherry-pick that commit so as to preserve his authorship of the fix.

**Comment by StefanKarpinski** [comment]
Oh, already done that way, I see. Carry on.
