### ISSUE TITLE
Provide scripts to install build requirements

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20002]
Basically a list of `apt-get install` or `brew install`.
cf. #20001 and https://discourse.julialang.org/t/cant-install-julia-5-0-via-git-on-amazon-ec2-instance/1444/10

**Comment by tkelman** [comment]
If you've already got brew and xcode command line tools installed on mac, it should be just `brew install gcc cmake`.

The packages go by different names on each linux distro. I think a set of dockerfiles added to `contrib/docker` would be a good way of documenting this for deb/buntu, fedora, centos, opensuse, arch, etc. On debian derivatives, if you're building master, I think you should just need `ca-certificates build-essential gfortran python curl m4 cmake` but someone should verify that in a docker container or clean bare-bones VM.

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/blob/master/doc/build/build.md
