### ISSUE TITLE
docs do not index "using"

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#20003]
Searching the docs for "using" or "import" or "importall" should find [summary-of-module-usage](http://docs.julialang.org/en/stable/manual/modules/?highlight=module#summary-of-module-usage).

**Comment by cormullion** [comment]
latest doc system is better:

http://docs.julialang.org/en/latest/search.html?q=Using

**Comment by yuyichao** [comment]
So it seems that this is not an issue anymore on master. Being a English word, the search result for `using` is unfortunately not very usable.... `importall` is much better http://docs.julialang.org/en/latest/search.html?q=importall

**Comment by JeffreySarnoff** [comment]
ok
