### ISSUE TITLE
workspace() call deletes IJulia.In variable

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/julia#20015]
In a qtconsole or notebook, one can access the command history through IJulia.In variable. However, once one clears the workspace by calling `workspace()` the variable is gone:

```
Jupyter QtConsole 4.2.1
Julia: A fresh approach to technical computing.

In [1]: 3+3
Out[1]: 6

In [2]: 4*2
Out[2]: 8

In [3]: In
Out[3]: 
Dict{Int64,String} with 4 entries:
  0 => ""
  2 => "4*2\n"
  3 => "In\n"
  1 => "3+3\n"

In [4]: workspace()

In [5]: In
UndefVarError: In not defined


In [6]: 3+3
Out[6]: 6

In [7]: 4*2
Out[7]: 8

In [8]: In
UndefVarError: In not defined 
```

A reset would be acceptable.

This is somewhat important in the light of the integration of a printhistory() function into IJulia ([Issue](https://github.com/JuliaLang/IJulia.jl/issues/497))

**Comment by yuyichao** [comment]
This should be a `IJulia.jl` issue.
