### ISSUE TITLE
Segfault on Linux Subsystem for Windows (libuv?)

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#20012]
Around Christmas, after struggling with MSYS, I successfully built Julia on my Windows machine using the new(ish) Linux Subsystem for Windows, which is running more-or-less Ubuntu 14.04 (Microsoft/Canonical  currently support 16.04 on the Windows Insider program, but the PC in question isn't a part of that).

However not long after that my Julia build on Windows stopped working, building fine but segfaulting at startup. The error message I get is:

```
ferris@MINI-PC:~/julia-dev$ ./julia

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
uv_free_interface_addresses at /home/ferris/julia-dev/deps/srccache/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/src/unix/linux-core.c:939
getipaddr at ./socket.jl:669
init_bind_addr at ./initdefs.jl:62
init_parallel at ./initdefs.jl:96
__init__ at ./sysimg.jl:396
unknown function (ip: 0x7fdfe6233f67)
jl_call_method_internal at /home/ferris/julia-dev/src/julia_internal.h:248 [inlined]
jl_apply_generic at /home/ferris/julia-dev/src/gf.c:2198
jl_apply at /home/ferris/julia-dev/src/julia.h:1389 [inlined]
jl_module_run_initializer at /home/ferris/julia-dev/src/toplevel.c:85
_julia_init at /home/ferris/julia-dev/src/init.c:699
julia_init at /home/ferris/julia-dev/src/task.c:292
main at /home/ferris/julia-dev/ui/repl.c:259
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4015fa)
Allocations: 997905 (Pool: 996778; Big: 1127); GC: 0
Segmentation fault (core dumped)
```

It's blaming `libuv`s function `uv_free_interface_addresses` for a segmentation fault. Not sure if `libuv` was bumped or patched around the Christmas period, but for whatever reason, Julia used to build and work fine on the Linux Subsystem for Windows and it no longer does.

I had hoped this was one of those issues that pops up and disappears quickly, but since the situation hasn't changed in weeks I thought I would open an issue here now.

**Comment by tkelman** [comment]
getipaddr wasn't implemented at all in WSL for a long time. I suspect you need to just wait until you can do windows update and get a more recent version of it.

**Comment by andyferris** [comment]
Thanks. I can verify that this fixed it for me.
