### ISSUE TITLE
Better printing for more complicated failure-to-match with new type system

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#20023]
I was briefly confused by the following:
```
julia> abstract Foo{A,B}

julia> immutable Bar{A} <: Foo{A,Int64}
       end

julia> f(::Type{C}) where C<:Foo{A,B} where A where B = B
f (generic function with 1 method)

julia> f(Bar)
ERROR: MethodError: no method matching f(::Type{Bar})
Closest candidates are:
  f{B,A,C<:Foo{A,B}}(::Type{C<:Foo{A,B}}) at :0
```

What I meant was:
```
julia> f(::Type{C}) where C<:(Foo{A,B} where A) where B = B
f (generic function with 2 methods)

julia> f(Bar)
Int64
```
But the error message wasn't particularly helpful in figuring out what the issue was. It would be nice to improve printing here.

**Comment by JeffBezanson** [comment]
I'm not sure what to do here. Do you have a more specific idea of what the output should look like? I see that (1) the bound on `C` is printed redundantly, and (2) we need to change to `where` for printing method parameters. Anything else?

**Comment by Keno** [comment]
Ideally I'd like it to give me explanation why `!(Type{Bar} <: Type{C} where C<: Foo{A,B} where A where B)`

**Comment by vtjnash** [comment]
Printing is better now (including color):
```
julia> f(Bar)
ERROR: MethodError: no method matching f(::Type{Bar})
Closest candidates are:
  f(::TYPE{C}) where {B, A, C<:Foo{A, B}} at REPL[4]:1
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```
