### ISSUE TITLE
Improve testsystem exception printing

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#20029]
Currently we print multiple exception stacks on a test failure. It will be good to

- Print only the first exception from a failing test only
- In the event of multiple exceptions from different testsets, print all of them only if an env variable is set. Default is to print only one.
- Don't print known exceptions raised in the testsystem machinery
- Limit stacktrace to last 30 lines?

**Comment by tkelman** [comment]
Mostly a duplicate of #18647. We can quiet this down a bit, but I'm very much against hiding valuable parts of stack traces for real failures.

**Comment by amitmurthy** [comment]
Yes it is.

**Comment by StefanKarpinski** [comment]
How about saving test results somewhere instead of verbose printing? If we pushed results to S3 from CI jobs we could track those too.
