### ISSUE TITLE
Return Q/R factors in SPQR

### ISSUE THREAD

**Issue by jagomezr** [JuliaLang/julia#20024]
Hi,

Has someone added the functionality to extract the Q and R factors of the SPQR factorization? So far, the result of using qrfact on a sparse matrix is the following:

Base.SparseArrays.SPQR.Factorization{Float64}(3,3,Ptr{Base.SparseArrays.SPQR.C_Factorization{Float64}} @0x0000000009f9d4a0)

I see that this issue has been reported in the past, but it seems no one has added this functionality to Julia.

Thanks!

**Comment by jagomezr** [comment]
In general, I have a system of the form:
A x = b

where A is a rectangular matrix. I want to obtain an equivalent system that is full row rank. The way I'm doing it is calculating the rank of A, and then using the QR = AE factorization and the rank r to find an equivalent system made of the first r rows of:

RE' x = Q'b. 

To do this I'm using the following code:

F = qrfact(model.S); 
    Sfull = full(model.S);
    r = rank(Sfull);
    bnew = Base.SparseArrays.SPQR.qmult(Base.SparseArrays.SPQR.QTX, F, Base.SparseArrays.CHOLMOD.Dense(model.b));
    Anew = sparse(Base.SparseArrays.SPQR.qmult(Base.SparseArrays.SPQR.QTX, F, Base.SparseArrays.CHOLMOD.Dense(Sfull)));
    r1 = rank(full(Anew));
    if r1 != r
       error("The full rank code is changing the original rank of the matrix");
    end
    model.S = Anew[1:r,:];
    model.b = bnew[1:r];

However, I'm getting the error below. Any ideas?

Thanks!


*** Error in `julia': double free or corruption (!prev): 0x00000000050961d0 ***

signal (6): Aborted
while loading no file, in expression starting on line 0
raise at /build/buildd/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56
abort at /build/buildd/eglibc-2.19/stdlib/abort.c:89
__libc_message at /build/buildd/eglibc-2.19/libio/../sysdeps/posix/libc_fatal.c:175
malloc_printerr at /build/buildd/eglibc-2.19/malloc/malloc.c:4996 [inlined]
_int_free at /build/buildd/eglibc-2.19/malloc/malloc.c:3840
jl_gc_counted_free at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1958
SuiteSparse_free at /home/jagomezr/Julia050/bin/../lib/julia/libsuitesparseconfig.so (unknown line)
cholmod_l_free at /home/jagomezr/Julia050/bin/../lib/julia/libcholmod.so (unknown line)
cholmod_l_free_sparse at /home/jagomezr/Julia050/bin/../lib/julia/libcholmod.so (unknown line)
free_sparse! at ./sparse/cholmod.jl:465
free! at ./sparse/cholmod.jl:1069
unknown function (ip: 0x7f1f4a0c66b2)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/src/julia.h:1392 [inlined]
run_finalizer at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:108
jl_gc_run_finalizers_in_list at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:190 [inlined]
run_finalizers at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:211
jl_gc_enable_finalizers at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:222
jl_mutex_unlock at /home/centos/buildbot/slave/package_tarball64/build/src/./julia_threads.h:476 [inlined]
jl_compile_for_dispatch at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1314
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:184 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
display at ./REPL.jl:132
unknown function (ip: 0x7f1f4a0d09e6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
display at ./REPL.jl:135
unknown function (ip: 0x7f1f4a0d06b6)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
display at ./multimedia.jl:143
unknown function (ip: 0x7f1f4a0d0502)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
print_response at ./REPL.jl:154
unknown function (ip: 0x7f1f4a090eb8)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
print_response at ./REPL.jl:139
unknown function (ip: 0x7f1f4a090938)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
#22 at ./REPL.jl:652
unknown function (ip: 0x7f1f4a08f931)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
#38 at ./REPL.jl:867
#13 at ./LineEdit.jl:736
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
prompt! at ./LineEdit.jl:1605
run_interface at ./LineEdit.jl:1574
unknown function (ip: 0x7f21645390bf)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
run_frontend at ./REPL.jl:903
run_repl at ./REPL.jl:188
unknown function (ip: 0x7f1f4a089532)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
_start at ./client.jl:360
unknown function (ip: 0x7f21645542e8)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1942
unknown function (ip: 0x4018ed)
unknown function (ip: 0x4013b6)
__libc_start_main at /build/buildd/eglibc-2.19/csu/libc-start.c:287
unknown function (ip: 0x4013fc)
Allocations: 5872265 (Pool: 5871060; Big: 1205); GC: 17
Aborted (core dumped)

**Comment by tkelman** [comment]
That looks like a bug, but separate from your feature request here. Can you provide self contained input data that reproducibly causes that? And platform and version info.

**Comment by jagomezr** [comment]
Hi,

You can try running test1.jl. The second file is being opened at line 78 (you'll need to modify this line at test1.jl with the address of the second file). I'm running this script in Ubuntu 14.04.1 LTS in a 64 bit machine. I'm using Julia 0.5.0.

I've tried commenting line 75. It fails in this case too. It always fails in a different way.

Let me know how I can help.

Jose A. Gomez


________________________________

**Comment by jagomezr** [comment]
You can try the following code:

`###### Definition of type Cvect: generates the structure for cost vectors ############################################################################
type Cvect
    sense::Int # +1 is for minimization and -1 is for maximization 
    rxns::Vector{Int} # Reaction indices that appear in cost vector
    wts::Vector{Float64} # Coefficients of the reaction indices 
    comment::String # String indicating the nature of the cost vector
    Cvect(sense,rxns,wts,comment) = length(rxns) == length(wts) ? new(sense,rxns,wts,comment) : error("Inconsistent size of rxns and wts vectors.");
end
# Constructors Cvect
Cvect(sense::Int,rxns::Int,wts::Int) = Cvect(sense,[rxns],[convert(Float64,wts)],"");
Cvect(sense::Int,rxns::Int,wts::Float64) = Cvect(sense,[rxns],[wts],"");
Cvect(sense::Int,rxns::Int,wts::Int,comment::String) = Cvect(sense,[rxns],[convert(Float64,wts)],comment);
Cvect(sense::Int,rxns::Int,wts::Float64,comment::String) = Cvect(sense,[rxns],[wts],comment);
Cvect() = Cvect(0,[0],[0],"");

type FBAmodel
    S::SparseMatrixCSC{Float64,Int64} # Stoichiometry matrix
    b::Vector{Float64} # Right-hand side: usually all zeroes
    lb::Vector{Float64} # Lower bound vector
    ub::Vector{Float64} # Upper bound vector
    C::Vector{Cvect} # Cost vector information
    DB::Float64 # Default bound equivalent to infinity. It's default value will be 1000.
    Penflag::Bool # To use a more specialized penalty function
    Penvector::Vector{Int} # Indices of reactions that will concentrate the penalty
    Pentype::Vector{Int} # For each reaction in penvector, we need to select 0 for lower bound, 1 for upper bound, 2 for both
    comment::String # String for comments
    FBAmodel(S,b,lb,ub,C,DB,Penflag,Penvector,Pentype,comment) = length(Penvector) == length(Pentype) ? new(S,b,lb,ub,C,DB,Penflag,Penvector,Pentype,comment) : error("Penvector and Pentype should have the same size.");
end

# Constructor FBAmodel
FBAmodel() = FBAmodel(sparse([0.0 0.0]),[0.0],[0.0],[0.0],[Cvect()],1000.0,false,[0],[0],"");

##### Function that replaces DB for Inf and returns full row rank system #################################################################################
function FullRank(model::FBAmodel)
    DB = model.DB;
    ind = find(x->(x >= DB),model.ub);
    model.ub[ind] = Inf;
    ind = find(x->(x <= -DB),model.lb);
    model.lb[ind] = -Inf;

    # Reformulating Ax = b for an equivalent system using QR factorization.
    # AE = QR, E-1 = E', Q-1 = Q'
    # QRE'x = b
    # RE'x = Q'b
    # Since R is an upper triangular matrix, only the first r rows of R (where
    # r is the rank of R) will contain the relevant information.
    # S = full(model.S);
    # F = qrfact(S,Val{true}); 
    # r = rank(S);
    # Q = F[:Q];
    # R = F[:R];
    # P = F[:P];
    F = qrfact(model.S); 
    Sfull = full(model.S);
    r = rank(Sfull);
    bnew = Base.SparseArrays.SPQR.qmult(Base.SparseArrays.SPQR.QTX, F, Base.SparseArrays.CHOLMOD.Dense(model.b));
    Anew = sparse(Base.SparseArrays.SPQR.qmult(Base.SparseArrays.SPQR.QTX, F, Base.SparseArrays.CHOLMOD.Dense(Sfull)));
    r1 = rank(full(Anew));
    if r1 != r
       error("The full rank code is changing the original rank of the matrix");
    end
    model.S = Anew[1:r,:];
    model.b = bnew[1:r];
    Base.SparseArrays.SPQR.free!(F);
end


iRC1080 = FBAmodel();
iRC1080.S = sprand(1000,2000,0.05);
iRC1080.b = zeros(1000);
iRC1080.DB = 1000;

FullRank(iRC1080);

model = Vector{FBAmodel}(1)
model[1] = iRC1080;
# Define cost vectors
minim = 1;
maxim = -1;

numcostvectors = Vector{Int}(1)
numcostvectors[1] = 4;

for i = 1:nmodel
    model[i].C = Vector{Cvect}(numcostvectors[i])
end

# Cost vectors algae
model[1].C[1]=Cvect(maxim,63,1,"Maximize growth") 
model[1].C[2]=Cvect(minim,28,1,"Maximize glucose consumption") 
model[1].C[3]=Cvect(maxim,[24,81],[1,1],"Minimize consumption, maximize production O2") 
model[1].C[4]=Cvect(maxim,407,1, "Minimize CO2 production")`

**Comment by jagomezr** [comment]
You can try the following code:


[test.txt](https://github.com/JuliaLang/julia/files/706931/test.txt)

**Comment by andreasnoack** [comment]
You are not supposed to free the SQPR object. Julia will do that for you so Julia segfault when you have already freed the object. If I uncomment the `free!` line then your code works fine.

**Comment by andreasnoack** [comment]
In [this file](https://github.com/JuliaLang/julia/files/706931/test.txt) line 75 has a `free!` which causes a segfault on my machine. If you are getting a segfault with a different program then please post a link to that.

**Comment by jagomezr** [comment]
The test.jl in the attached folder fails with 
*** Error in `julia': double free or corruption (!prev): 0x0000000004a2fc70 ***


[SPQR failure.zip](https://github.com/JuliaLang/julia/files/709666/SPQR.failure.zip)

**Comment by andreasnoack** [comment]
Thanks. Just tried it on my Mac. It works on both master and 0.5. What is your `versioninfo()`?

**Comment by jagomezr** [comment]
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by andreasnoack** [comment]
Just tried on a Linux machine with 0.5 and now I can reproduce the segfault. I'll look into it.

**Comment by jagomezr** [comment]
Thanks for looking into this!

For the record, the same code in Julia 0.5.0 in Windows 10 also fails. No error is returned, the terminal just shuts down.

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by andreasnoack** [comment]
I've spent some time on this but so far I haven't been able to figure out what the problem is including why this is not showing up on Mac.

**Comment by RalphAS** [comment]
The failure in the example "SPQR failure.zip" posted above is due to a malformed input: one of the matrices returned by `matread` has more indices than values, which leads to heap corruption after SuiteSparse frees its working arrays.  Whether this heap corruption causes a crash seems to be platform dependent.  I suspect a bug in MAT.jl or a flaw in the data file.

With regard to the request for Q and R matrices, they are not immediately accessible from the C API which Julia uses because they are wasteful for most purposes. One could of course apply `qmult` to the identity.

**Comment by andreasnoack** [comment]
See the discussion in https://github.com/JuliaLang/julia/pull/20464. It appears that we actually made some wrong assumptions about the buffer sizes. The PR fixes the issue on the Linux machine where I was able to reproduce the problem.

**Comment by jagomezr** [comment]
What does PR mean? I see you committed some changes that you are waiting to merge with master. How can I adopt the changes? Should I wait until the changes are pulled into the master?

Thanks!

**Comment by andreasnoack** [comment]
PR means *pull request*. There was a request for an extra test which I haven't added yet. It should happen soon.
