### ISSUE TITLE
import Markdown error

### ISSUE THREAD

**Issue by trans** [JuliaLang/julia#20038]
Try to import Markdown library and get the following:

```
julia> import Markdown
ERROR: LoadError: LoadError: syntax: space before "(" not allowed in "breaking ("
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/trans/.julia/v0.5/Markdown/src/parse/config.jl, in expression starting on line 28
while loading /home/trans/.julia/v0.5/Markdown/src/Markdown.jl, in expression starting on line 5
```

I'm using Julia `0.5.0`.

**Comment by ararslan** [comment]
Hi @trans. Since this issue is specific to the Markdown.jl package, please post the issue to https://github.com/JuliaArchive/Markdown.jl instead. Thanks!

**Comment by trans** [comment]
I'm confused. The README for that repository says:

> Note that Markdown.jl lives in Base Julia form 0.4 onwards. PRs and changes should be made over there.

**Comment by ararslan** [comment]
Ah, sorry about that. It looks like you're using the Markdown.jl package though; note the path in the error. Try instead `using Base.Markdown` to ensure you're importing the right one.

**Comment by trans** [comment]
Oh, I see. So I should not have done `Pkg.add("Markdown")` in the first place.

**Comment by ararslan** [comment]
Correct.
