### ISSUE TITLE
Inference regression for empty array

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#20037]
DataFrames formula code hits an inference regression with an empty array. This is problematic since `!` is now only defined for `AbstractArray{Bool}` (which might be an issue on its own).

```julia
function f()
    x = [1]
    x = x[!(x .== 1)]
    x .== 0
end

function g()
    x = Any[1]
    x = x[!(x .== 1)]
    x .== 0
end

function h()
    x = Any[1]
    x .== 0
end
```
On Julia 0.5.0:
```julia
julia> f()
0-element BitArray{1}

julia> g()
0-element BitArray{1}

julia> h()
1-element BitArray{1}:
 false

```

On master:
```julia
julia> f()
0-element BitArray{1}

julia> g()
0-element Array{Any,1}

julia> h()
1-element BitArray{1}:
 false

```

**Comment by Sacha0** [comment]
(Tangentially, perhaps we should deprecate `!` vectorized over `AbstractArray{Bool}`? Also, `!.[true]` yields `ERROR: syntax: invalid identifier name "."` (#20039). Best!)

**Comment by pabloferz** [comment]
In the meantime, if you need a workaround, you can do

```julia
iseq(x, y)::Bool = x == y

function g()
    x = Any[1]
    x = x[(!).(x .== 1)]
    h.(x, 0)
end
```

**Comment by TotalVerb** [comment]
For consistency with other operators, the operator form of this would have to be `.!A`, not `!.A`.

**Comment by KristofferC** [comment]
The original code is deprecated for broadcasted `!` which works fine.

**Comment by tkelman** [comment]
> works fine

How so? I still see

```
function g()
    x = Any[1]
    x = x[(!).(x .== 1)]
    x .== 0
end
g()
```

return a `0-element Array{Any,1}`

**Comment by KristofferC** [comment]
Yeah, I goofed here.

**Comment by vtjnash** [comment]
we can simplify the original question to simply:
```julia
julia> [] .== 0
0-element Array{Any,1}
```
Which further simplifies to:
```julia
Core.Inference.return_type(==, (Any, Int)) === Bool
```
However, we haven't typically been willing to commit to forcing `==` to always return `Bool`, so this isn't expected to work.

**Comment by TotalVerb** [comment]
Why do we return `Array{Any, 1}` instead of `Array{Union{}, 1}` in the empty case?

**Comment by nalimilan** [comment]
Are we OK with the current behavior of `[] .== 0`, or should it be changed to return `Union{}[]`?

**Comment by JeffBezanson** [comment]
In #17811 I was convinced to always use the inferred type instead of `Union{}`.

**Comment by nalimilan** [comment]
Let's close this then.
