### ISSUE TITLE
Array docs missing some functions

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20042]
`summary` and `accumulate` are missing from http://docs.julialang.org/en/latest/manual/arrays.html#Arrays-1

**Comment by ararslan** [comment]
`accumulate` appears in the "Arrays" section of the standard library docs but is not mentioned in the arrays section of the manual. `summary` appears in the "I/O and Network" section of the standard library.

**Comment by dpsanders** [comment]
Thanks.
