### ISSUE TITLE
copy! is wrong for overlapping views

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#20069]
The `copy!` function has special-casing to handle the case where the source and destination arrays are equal, but this machinery does not work for views:
```jl
julia> a = [1:10;]; copy!(a, 2, a, 1, 9)
10-element Array{Int64,1}:
 1
 1
 2
 3
 4
 5
 6
 7
 8
 9

julia> a = [1:10;]; v = view(a, 1:10); copy!(v, 2, v, 1, 9)
10-element SubArray{Int64,1,Array{Int64,1},Tuple{UnitRange{Int64}},true}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
```

**Comment by Keno** [comment]
@mbauman Can some of your new alias detection logic handle this case, or does it already?

**Comment by mbauman** [comment]
Nope, looks like I missed `copyto!` in implementing the detection.  Should be as easy as adding an `src′ = unalias(dest, src)` line there.

**Comment by StefanKarpinski** [comment]
I'm pretty sure that it's no longer a performance trap to just reuse the `src` name here.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/16705
