### ISSUE TITLE
BoundsError in 2d comprehension

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#20078]
From MAT.jl's test suite

```jl
julia> Any[v for _ in 1:1, v in (1.0, 2.01, "string", Any["string1" "string2"])]
ERROR: BoundsError: attempt to access 1×4 Array{Any,2} at index [5]
Stacktrace:
 [1] copy!(::Array{Any,2}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}) at ./abstractarray.jl:499
 [2] _collect(::Type{Any}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}, ::Base.HasShape) at ./array.jl:313
 [3] collect(::Type{Any}, ::Base.Generator{Base.Iterators.Prod2{UnitRange{Int64},Tuple{Float64,Float64,String,Array{Any,2}}},##1#2}) at ./array.jl:310
```

Bisection blames https://github.com/JuliaLang/julia/pull/18457

cc: @JeffBezanson

**Comment by yuyichao** [comment]
This seems to be caused by `Base.product` with a heterogeneous tuple input. It causes a infinite loop in

```julia
for x in Base.product(1:1, (1, "2"))
end
```

**Comment by yuyichao** [comment]
It's also important that the first iterator has a single element so probably a wrong handling of edge case there?

**Comment by yuyichao** [comment]
I think the issue is likely

```julia
julia> oftype(Nullable{Int}(), nothing)
Nullable{Int64}()

julia> oftype(Nullable{Any}(), nothing)
Nullable{Any}(nothing)
```

I assume using `typeof(nv2)()` should work?

**Comment by tkelman** [comment]
that `nothing` conversion method seems more dangerous than useful in terms of hitting corner cases like this. can we deprecate it?

**Comment by nalimilan** [comment]
I wouldn't deprecate it now if we expect `Nullable` to be replaced with `Union{T, Void}` soon. I think we just need a new method for `convert(Nullable{Any}, ...)`.

**Comment by JeffBezanson** [comment]
That workaround is safe, but there's a more general specificity problem. `Type{Nullable{T}}, Void` used to be more specific than `Type{Nullable{T}}, T`, and isn't anymore. That should be fixable.

**Comment by yuyichao** [comment]
Is `Type{Nullable{T}}, Void` actually more specific though? It matches `Type{Nullable{Int}}, Void` where as the second one doesn't.

**Comment by JeffBezanson** [comment]
True, but I think for any arguments where both definitions match, the one that explicitly names `Void` is arguably more specific.
