### ISSUE TITLE
Matrix factorization components have inconsistent types.

### ISSUE THREAD

**Issue by henrik227** [JuliaLang/julia#20089]
I noticed that the types of the components of some matrix factorizations are inconsistent:

```
n=10
A = rand(n, n)
F = lufact(A)
U = F[:U]
```

Here, U is of type `Array{Float64,2}` (even though it is upper triangular).

```
n=10
A = rand(n, n)
S = A+transpose(A)+n*eye(n)
F = cholfact(S)
U = F[:U]
```

In this case, U is of type `UpperTriangular{Float64,Array{Float64,2}}`. While this is not wrong, it is actually somewhat inconvenient because for example `Base.LinAlg.BLAS.trsm!` does not accept this as a type for A (even though it is supposed to be triangular).

The R of qrfact is of type `Array{Float64,2}` as well.

**Comment by andreasnoack** [comment]
The `U` in a Cholesky is always triangular. That is not the case for LU or QR. It depends on the shape of the input, e.g.
```jl
julia> qrfact(randn(3,4))[:R]
3x4 Array{Float64,2}:
 2.20049  -0.820463   2.10965    0.941363
 0.0      -0.938435   0.387982   0.280644
 0.0       0.0       -0.197187  -2.39108

julia> lufact(randn(3,4))[:U]
3x4 Array{Float64,2}:
 2.43084  -0.135418  0.850591   1.22028
 0.0       0.592936  1.87067   -0.552748
 0.0       0.0       0.944198   1.03617
```
The return type is not supposed to depend on the shape of the input so we cannot use `XTriangular`.

The blas wrappers are considered a low level API. Most often, it shouldn't be necessary to call it and if you use `\` or `A_ldiv_B!` then it shouldn't matter if the `U` is `XTriangular` or not. Do you have a specific reason to call `trsm!` directly?

**Comment by henrik227** [comment]
First of all, I'm tempted to argue with the underlying assumption that triangular matrices have to be square, but let's not go there ;) (Unless you want to. For my work, I'm using a more general definition.)

The reason is that I'm working on automatic code generation for linear algebra expressions, and instead of directly generating C code, I decided to use Julia for now because that makes my life easier. To get the best performance, and because my system has all the necessary knowledge, I'm directly using the BLAS wrappers. 

Of course, I can also generate the code to convert the type, but if I'm not mistaken, this is not possible without copying the array, which is not necessary in this case.

**Comment by andreasnoack** [comment]
> First of all, I'm tempted to argue with the underlying assumption that triangular matrices have to be square

It's okay. We have thought about this but it makes the types more complicated and in many places, we'd have to add checks so, at least for now, we have decided to assume that it is square.

> To get the best performance, and because my system has all the necessary knowledge, I'm directly using the BLAS wrappers.

You shouldn't get better runtime performance from calling the BLAS wrappers directly. You might save the time of a function call or two but unless all of your matrices are tiny, it shouldn't really matter relative to the time of BLAS operation.

> Of course, I can also generate the code to convert the type, but if I'm not mistaken, this is not possible without copying the array, which is not necessary in this case.

With a little care, you can convert without copying the data. Since you are probably using the types anyway, you could just unwrap the `Cholesky`
```jl
julia> unwrap(x::LinAlg.Cholesky) = x.data
unwrap (generic function with 1 method)

julia> unwrap(x::LinAlg.Factorization) = x
unwrap (generic function with 2 methods)
```

**Comment by henrik227** [comment]
> You shouldn't get better runtime performance from calling the BLAS wrappers directly. You might save the time of a function call or two but unless all of your matrices are tiny, it shouldn't really matter relative to the time of BLAS operation.

Good to know. But for something like syrk, I don't have a choice, or do I?

> With a little care, you can convert without copying the data. Since you are probably using the types anyway, you could just unwrap the Cholesky

Thanks, I guess that's what I will do. (I assume you mean `x.factors` instead of `x.data`)

**Comment by andreasnoack** [comment]
> Good to know. But for something like syrk, I don't have a choice, or do I?

It depends on the level of control. The you do `A'B` we'll check if `A===B` and call `syrk` in that case. If you want the full version you could do something like what I'm doing in
```
https://github.com/andreasnoack/LinearAlgebra.jl/blob/master/src/juliaBLAS.jl#L35
```

> Thanks, I guess that's what I will do. (I assume you mean x.factors instead of x.data)

Yes, I meant `.factors`.

**Comment by andreasnoack** [comment]
I'll close since this is a design choice.
