### ISSUE TITLE
Inconsistent types for scalar arguments in Base.LinAlg.BLAS

### ISSUE THREAD

**Issue by henrik227** [JuliaLang/julia#20088]
I noticed that the "alpha" argument for some functions in Base.LinAlg.BLAS has inconsistent types. The three functions shown below use Number, all others use more specific types (Float32,...).

```
syrk(uplo::Char, trans::Char, alpha::Number, A::StridedVecOrMat)
syr2k(uplo::Char, trans::Char, alpha::Number, A::StridedVecOrMat, B::StridedVecOrMat)
trmm!(side::Char, uplo::Char, transa::Char, diag::Char, alpha::Number,
                       A::StridedMatrix{$elty}, B::StridedMatrix{$elty})
```

**Comment by andreasnoack** [comment]
The `alpha` arguments are converted before the LAPACK call so these are harmless.

**Comment by fredrikekre** [comment]
This should be closed; the methods which only have `::Number` all convert to correct type, and this lets users use other number types.
