### ISSUE TITLE
misplaced quote in documentation on new type system

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#20093]
The material on the new type system in the developer documentation, that is

   http://docs.julialang.org/en/latest/devdocs/types.html

has a misplaced quote somewhere so that much of the quoted text is mistakenly unquoted and vice versa.

**Comment by ararslan** [comment]
The block that begins with `julia> dump(Array)` is missing the closing triple backquote that ends the code markdown.

**Comment by ararslan** [comment]
Placing in the 0.6.0 milestone to make sure we don't release 0.6.0 with garbled docs. 😉

**Comment by JeffBezanson** [comment]
Thanks for spotting this. There was some tricky rebasing when the doc format changed partway through my pull request :)

**Comment by ararslan** [comment]
Fix incoming, building the docs locally now.
