### ISSUE TITLE
Performance difference between two codes

### ISSUE THREAD

**Issue by kurtuba** [JuliaLang/julia#20098]
Hello,

I have two codes doing the exact same thing. I put them below. In the latter one, we use a multi-dimensional array instead of x. The former one is substantially faster than the other, and uses smaller number of allocations. What is the reason of it?

Thanks in advance.

—

x = [0.76,-1.13,1.33];
@time for m=1:450000
                 dot(x,[1.,2.,3.])
            end

0.034094 seconds (900.00 k allocations: 96.130 MB, 11.11% gc time)

—

X = zeros(3,3,3,100);
X[:,1,1,1] = x;
@time for m=1:450000
                 dot(X[:,1,1,1],[1.,2.,3.])
            end

  0.226584 seconds (2.70 M allocations: 130.463 MB, 3.27% gc time)

**Comment by yuyichao** [comment]
Please use https://discourse.julialang.org for questions and quote your code
