### ISSUE TITLE
Inconsistent behaviour with ranges containing NaN

### ISSUE THREAD

**Issue by spurll** [JuliaLang/julia#20110]
Generally, collecting a range that begins or ends with `NaN` results in `[]`:

```julia
julia> collect(1.0:1.0:NaN)
0-element Array{Float64,1}

julia> collect(NaN:1.0:1.0)
0-element Array{Float64,1}
```

When the step is negative, however, the result is different:

```julia
julia> collect(1.0:-1.0:NaN)
ERROR: InexactError()
 in vcat(::FloatRange{Float64}) at ./range.jl:801
 in collect(::FloatRange{Float64}) at ./range.jl:813

julia> collect(NaN:-1.0:1.0)
ERROR: InexactError()
 in vcat(::FloatRange{Float64}) at ./range.jl:801
 in collect(::FloatRange{Float64}) at ./range.jl:813
```

While my intuition is that `1:NaN` should collect to `[]`, [raising an exception](https://github.com/JuliaLang/julia/issues/17594#issuecomment-235091412) is also reasonable, as this is how ranges with `Inf` behave.

But either way, it seems that this behaviour shouldn't be affected by the sign of the step.

```julia
julia> versioninfo()
Julia Version 0.5.0-rc1+0
Commit cede539* (2016-08-04 08:48 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by mbauman** [comment]
All these examples now throw `InexactError`s at construction time, regardless of the step.

**Comment by tkelman** [comment]
I don't see any such tests from a quick grep, could've missed them though.
