### ISSUE TITLE
Request: more descriptive error for "ccall: wrong number of arguments to C function"

### ISSUE THREAD

**Issue by mcb0035** [JuliaLang/julia#20129]
When `ccall` is passed an unexpected number of arguments, it would be useful to know which function it is trying to call and what arguments it expects vs. what it gets.  For example,

    ccall: wrong number of arguments to C function foo
    expected (bar, baz), received (bar, bar, baz)

Or something like that.  I am looking at `ccall.cpp`, but if anyone already familiar with the Julia internals can do it better and faster that would be great.

Some `ccall`s started failing with this error while trying to work around #19774, but without this information it is hard to tell why.

**Comment by vtjnash** [comment]
should be largely fixed by https://github.com/JuliaLang/julia/pull/18754/files#diff-ab8c4a99930a43168794a7bd3b8bfa91R94

**Comment by thofma** [comment]
Is this fixed? I am on
```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2634
Commit 754757c* (2017-02-07 15:55 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, nehalem)
```
and I get
```
WARNING: ccall: wrong number of arguments to C function in Module
```
after `using Module`.

**Comment by vtjnash** [comment]
This error is now thrown as soon as it occurs so the backtrace information should be useful now.
