### ISSUE TITLE
segfault while loading a file

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#20121]
Loading [this file](https://gist.github.com/tanmaykm/917f4db0138627ce623fec91a81913a0#file-x-jl) causes Julia to [segfault](https://gist.github.com/tanmaykm/917f4db0138627ce623fec91a81913a0#file-err-md) on master branch.

Reducing the array being loaded by one row avoids the segfault.
Appears to be a memory corruption?

**Comment by yuyichao** [comment]
Likely dup of https://github.com/JuliaLang/julia/issues/20103

**Comment by JeffBezanson** [comment]
I think this one involves a long concrete tuple type that we can easily add a fast path for. #20103 I think is trickier.
