### ISSUE TITLE
`slicedim` is type-unstable

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#20141]
For example;

```
julia> @code_warntype slicedim([1 2; 3 4], 2, 1)
Variables:
  #self#::Base.#slicedim
  A::Array{Int64,2}
  d::Int64
  i::Int64
  nd::Int64
  #118::Base.##118#121
  #119::Base.##119#122
  #120::Base.##120#123{Array{Int64,2},Int64,Int64}

Body:
  begin 
[ truncated ]
(A::Array{Int64,2})::Tuple{Array{Int64,2}},SSAValue(12))::Any
  end::Any
```

While possibly a dynamic dispatch may be needed in the internal implementation, it seems to me that the function should always return a vector. Perhaps that can be annotated?

**Comment by martinholters** [comment]
I don't think this is possible in general. `slicedim(A, d::Integer, i)` boils down to returning `A[new_index_tuple...]` where the exact type of `new_index_tuple` depends on the _value_ of `d` (and the type of `i`). So the exact `getindex` method can only be chosen based on the _value_ of `d`. Not knowing which method is chosen makes it practically impossible to predict its return type. But granted, if `A::Array`, it should be possible to come up with something better than `Any`.

**Comment by martinholters** [comment]
Hm, actually, with relatively little effort, the `new_index_tuple` can be computed such that it is inferred as
```julia
Tuple{Union{Base.OneTo{Int64},Int64},Union{Base.OneTo{Int64},Int64}}
```
for the OP's example. The inferred return type for the `slicedim` then would be
```julia
Union{Array{Float64,1},Array{Float64,2},Float64}
```
which is already an improvement. Now if `new_index_tuple` could be inferred as
```julia
Union{Tuple{Base.OneTo{Int64},Int64},Tuple{Int64,Base.OneTo{Int64}}}
```
that would probably solve the case for the OP's example.

**Comment by martinholters** [comment]
Huh, no, by typeasserting `new_index_tuple` to `Union{Tuple{Base.OneTo{Int64},Int64},Tuple{Int64,Base.OneTo{Int64}}}`, the inferred return type of `getindex` is `Any` again. Interesting that the tighter bound on the argument type gives a looser bound on the return type. Would anyone with intimate knowledge of inference share some insights here?

Anyway, `slicedim([1 2; 3 4], 3, 1)` actually returns a matrix (and the `Union` I have typeasserted to above is wrong for this case), so the best result type inference could produce for the OP's example would be `Union{Array{Float64,1},Array{Float64,2}}`.

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/pull/20154#pullrequestreview-17745803
