### ISSUE TITLE
Define `eltype(::Type{Union{}}) = Union{}`?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#20140]
Currently, `eltype(Union{})` throws a method ambiguity error. Since there is nothing of type `Union{}`, it is natural that are no objects that are elements of objects of type `Union{}`, so the definition `eltype(::Type{Union{}}) = Union{}` makes sense.

**Comment by Keno** [comment]
The problem you run into is that your inferred result becomes `Union{Union{},Foo}`, whereas an error collapses the union.

**Comment by TotalVerb** [comment]
This seems to be a change from 0.5. I came across it while trying to get Lint to work on 0.6.

0.5:
```julia
julia> eltype(Union{})
Union{}
```

0.6:

```julia
julia> eltype(Union{})
ERROR: MethodError: eltype(::Type{Union{}}) is ambiguous. Candidates:
  eltype{E,T<:Tuple{Vararg{E,N} where N}}(::Type{T}) in Base at tuple.jl:52
  eltype{E,A<:(AbstractArray{E,N} where N)}(::Type{A}) in Base
  eltype{T<:AbstractString}(::Type{T}) in Base at strings/basic.jl:54
  eltype{T<:Base.Dates.Period}(::Type{T}) in Base.Dates at dates/types.jl:238
  eltype{T<:Number}(::Type{T}) in Base at number.jl:28
```

@Keno, I don't understand what you mean.

**Comment by Keno** [comment]
```
julia> Base.return_types(eltype, Tuple{(Type{T} where T<:(Array{Int64,N} where N))})
1-element Array{Any,1}:
 Type{Int64}

julia> Base.eltype(::Type{Union{}}) = Union{}

julia> Base.return_types(eltype, Tuple{(Type{T} where T<:(Array{Int64,N} where N))})
2-element Array{Any,1}:
 Type{Union{}}
 Type{Int64}
```

**Comment by TotalVerb** [comment]
OK, so this change would pessimize type inference in certain situations, and was therefore intentional?

**Comment by JeffBezanson** [comment]
It's a koan: "if you have no object at all, is it iterable?"

I would say no.

**Comment by timholy** [comment]
We should get into the habit of implementing these policy decisions via informative error messages. As it is now, this is an ambiguity error which leaves the intentionality...ambiguous. See #20568.
