### ISSUE TITLE
eltype(Tuple{...}) less specific than 0.5

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#20143]
One consequence of new subtyping is that the `eltype` for certain non-concrete `Tuple` types no longer returns the most specific possible result; i.e. in 0.5

```julia
julia> eltype(Tuple{Integer})
Integer
```

whereas in 0.6

```julia
julia> eltype(Tuple{Integer})
Any
```

Related: #20140

**Comment by vtjnash** [comment]
This appears to be a direct consequence of https://github.com/JuliaLang/julia/issues/19998#issuecomment-273966221

Maybe that condition needs more consideration, or it seems we might need to find a different way to express this.
