### ISSUE TITLE
Assigned anonymous function runs slow

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#20156]
Below, the function `f` and its anonymous version run roughly at the same speed:
```julia
julia> f(x,y) = x + y - x*y
f (generic function with 1 method)

julia> using BenchmarkTools

julia> @benchmark f(2,3)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  median time:      1.903 ns (0.00% GC)

julia> @benchmark ((x,y) -> x + y - x*y)(2,3)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  median time:      1.970 ns (0.00% GC)
```

However, once the anonymous function is assigned to a new variable `g` and then `g` is called instead, it runs ~10X slower:
```julia
julia> g = (x,y) -> x + y - x*y
(::#1) (generic function with 1 method)

julia> @benchmark g(2,3)
BenchmarkTools.Trial:
  memory estimate:  0.00 bytes
  allocs estimate:  0
  median time:      19.567 ns (0.00% GC)
```

This is strange, because `f` and `g` generate the same code:
```julia
julia> @code_typed f(2,3)
CodeInfo(:(begin
        return (Base.sub_int)((Base.add_int)(x,y)::Int64,(Base.mul_int)(x,y)::Int64)::Int64
    end))=>Int64

julia> @code_typed g(2,3)
CodeInfo(:(begin
        return (Base.sub_int)((Base.add_int)(x,y)::Int64,(Base.mul_int)(x,y)::Int64)::Int64
    end))=>Int64
```

Here is the version info:
```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2225
Commit 95cb94c39* (2017-01-20 13:26 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.3.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
Don't benchmark global variables.

**Comment by KristofferC** [comment]
Confirmed `const g = ...` runs at the same speed as `f`.

**Comment by wsshin** [comment]
Thanks! I remember you gave the same advice in another issue I filed.  Since then I have been making sure not to use global variables as _arguments_ of functions to benchmark, but in this case I didn't realize that the use of the global variable would interfere with benchmarking because it represented a _function name_.  

In other words, because we routinely benchmark functions defined in the global scope, I thought benchmarking `g` above wouldn't be that different from benchmarking other functions (because they are both in the global scope).  Apparently I was wrong.  Sorry for making the same mistake again!

**Comment by wsshin** [comment]
I also find that using `$`, which was the trick you mentioned in the other issue I filed, works in this case as well: `@benchmark $g(2,3)` reports no slowdown.

But last time I didn't understand clearly why `$` helps here.  Is it that `$` inlines the expression into the code?  Also, are there anythings that I need to be careful about when using `$` for global variables in `@benchmark`?

**Comment by KristofferC** [comment]
In your post you could do `g = 1` since `g` is just a binding. That is,  the type of `g` is unknown since it is a global variable. `f` on the other hand is an actual function that exist in the method table.
