### ISSUE TITLE
make JULIACODEGEN=none fails

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#20168]
Running
```
make JULIACODEGEN=none -j 4 >fout 2>errout
```

as described [here](http://juliacomputing.com/blog/2016/02/09/static-julia.html) on branch `jn/release-0.5-fix-compile-all`  fails with error:

```
/home/jared/build/julia_noc/usr/lib/libjulia.so: undefined reference to `jl_assign_functionID'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/jared/build/julia_noc/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2
```
The full contents of the error output is [here](https://gist.github.com/JaredCrean2/a55e6f5ecd5c05c1ff8cfa8895285c53). Building without `JULIACODEGEN=none` works correctly.

**Comment by JaredCrean2** [comment]
Bump

**Comment by JaredCrean2** [comment]
Anyone interesting in fixing a broken feature?

**Comment by StefanKarpinski** [comment]
Have you tried building without `-j4`?

**Comment by JaredCrean2** [comment]
The new commit doesn't build (without `-j 4`), but the error is different:

```
In file included from /home/jared/build/julia_noc/src/anticodegen.c:6:0:
/home/jared/build/julia_noc/src/intrinsics.h: In function ‘jl_init_intrinsic_functions’:
/home/jared/build/julia_noc/src/intrinsics.h:194:6: warning: old-style function definition [-Wold-style-definition]
 void jl_init_intrinsic_functions()
      ^
A method error occurred before the base MethodError type was defined. Aborting...
#<intrinsic #88 ccall>
(:jl_new_typevar, #<null>.Ref{#<null>.TypeVar}, svec(#<null>.Any, #<null>.Any, #<null>.Any), :T, 0, Union{}, 0, #<null>.Any, 0)
while loading boot.jl, in expression starting on line 273
Allocations: 7897 (Pool: 7897; Big: 0); GC: 0
Aborted (core dumped)
make[1]: *** [/home/jared/build/julia_noc/usr/lib/julia/inference.ji] Error 134
make: *** [julia-inference] Error 2
```

Log files [here](https://gist.github.com/JaredCrean2/4fc2fe0f42fc0a3cd46f02ec94fe836e)

**Comment by vtjnash** [comment]
That seems fine. It's not possible or expected for it to be able to bootstrap a compiler sans the compiler.

**Comment by JaredCrean2** [comment]
Looking deeper, I see `usr/bin/julia` does exist, but hasn't been symlinked into the repo root (probably because the bootstrap failed?).  However, I built `sys-all.so` using the latest commit (built with codegen) and tried to use it with the version without codegen, and it segfaulted:

```
jared@jared-r15:~/static_compile/test2$ julia_noc -q --compile=no --sysimage sys-all.so 
julia> println("hello world")

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
Allocations: 2485633 (Pool: 2484283; Big: 1350); GC: 0
Segmentation fault (core dumped)
```

Using the version built with codegen works : 

```
jared@jared-r15:~/static_compile/test2$ julia5s -q --compile=no --sysimage sys-all.so 
julia> println("hello world")
hello world
```

**Comment by JaredCrean2** [comment]
Any ideas on the segfault?

**Comment by vtjnash** [comment]
There's insufficient detail in your report to debug it from that alone, so it drops low on my priority list to try to reproduce the bug. Since this is all open source, you're welcome to submit a PR to fix the issue. I'm usually quite happy to provide guidance on getting started.

**Comment by JaredCrean2** [comment]
If I write a script that builds two versions of Julia in the appropriate states, generates the sysimage, and reproduces the segfault, would that be sufficient information?  I think asking users to debug segfaults in base Julia is excessive (and beyond my skill set).

**Comment by tkelman** [comment]
It's an undocumented, experimental build option, are you using it for something?

**Comment by JaredCrean2** [comment]
Eventually I want to use it to run my CFD code on a Blue Gene Q, which can't run a compiler on the compute nodes.  Right now I am testing out the static compilation features to see how they work, hoping to do a test with a small model code.

**Comment by vtjnash** [comment]
Running julia-debug instead of the release binary and getting a backtrace from gdb/lldb is more useful than a script to reproduce (I've run the necessary steps often enough that it's gotten easier for me to just type the commands rather than script them)

**Comment by StefanKarpinski** [comment]
> I've run the necessary steps often enough that it's gotten easier for me to just type the commands rather than script them

If it's scripted others can also run them.

**Comment by JaredCrean2** [comment]
Here is the [script](https://gist.github.com/JaredCrean2/3758c598f7cf66a5acbdd4e4176cf83c).   It turns out the segfault does not occur when running commands with `julia -e`, but does when the command is run directly in the repl.  I'll try to run gdb tomorrow, although it may not get done until this weekend.

**Comment by JaredCrean2** [comment]
gdb output for both debug and regular builds [here](https://gist.github.com/JaredCrean2/267684aedd14a9293881112d00c93e0b), showing both the error and a backtrace of where the error occured.  The debug version hit an assertion, while the regular build segfaulted.

**Comment by JaredCrean2** [comment]
Can I provide any additional information?

**Comment by JaredCrean2** [comment]
Any progress?
