### ISSUE TITLE
Trailing-1s indexing with 0-dimensional AbstractArrays

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#20175]
Given #19958 and #20079, there may be fixes already submitted for this (or possibly, this won't work in the future anyway), so for now I simply report this:

```jl
julia> a = reshape([5])
0-dimensional Array{Int64,0}:
5

julia> a[]
5

julia> a[1]
5

julia> immutable MyArray{T,N} <: AbstractArray{T,N}
           parent::Array{T,N}
       end

julia> b = MyArray(a);

julia> Base.getindex{T,N}(A::MyArray{T,N}, inds::Vararg{Int,N}) = A.parent[inds...]

julia> Base.size(A::MyArray) = size(A.parent)

julia> Base.linearindexing(A::MyArray) = Base.LinearFast()

julia> b[]
5

julia> b[1]
ERROR: indexing not defined for MyArray{Int64,0}
Stacktrace:
 [1] getindex(::MyArray{Int64,0}, ::Int64) at ./abstractarray.jl:792

julia> versioninfo()
Julia Version 0.6.0-dev.2260
Commit b44faa3* (2017-01-22 03:01 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

It succeeds if you omit the `linearindexing` specialization.

**Comment by mbauman** [comment]
I don't think this is a bug.  If you declare your type as a `LinearFast`, then you are promising that you've defined `getindex(::MyArray, ::Int)`, but the indexing method you've defined is the `LinearSlow` one.

I think this is how all the documentation is written, and I don't think sure it's worth adding a special case for this.  We could probably make that error method a little clearer, though.

**Comment by mbauman** [comment]
What would you think about renaming `LinearFast` to simply `LinearIndexing`?  And `LinearSlow` to `CartesianIndexing`?

**Comment by timholy** [comment]
Yes, having them mean "what methods I need to implement" would convey a lot of useful information to package developers. Great idea. If we wanted to do it in one shot, we could reverse word order and use `IndexedLinearly` and `IndexedCartesianly`. OK, I admit that last is a little awkward. If you don't like it, it's at least a candidate for a transitional name.

**Comment by mbauman** [comment]
Proposal: use the word index like a verb:

`LinearIndexing` -> `IndexMethod` (the abstract super)
`LinearFast` -> `IndexLinear`
`LinearSlow` -> `IndexCartesian`

**Comment by andyferris** [comment]
`LinearIndexing` and `CartesianIndexing` seems better to me, possibly along with `IndexingMethod`.

I feel that introspection works a bit like a conversation with the type/object:

"What is your `IndexingMethod`?"

"`LinearIndexing`"

"Thanks. In that case, give me element 1"

...

**Comment by timholy** [comment]
@mbauman, you're right about the fact that this isn't a bug. Turns out to have arisen in a package that formerly worked by overloading `Base._getindex`, and the order of checking for errors vs dispatch changed in 0.6. Since that's an internal detail, I'll close this.

@andyferris, we didn't explain that `LinearIndexing` already means something (it's an abstract type), so we need to choose a different name so we can deprecate the meaning of the old one.

**Comment by andyferris** [comment]
Right you are - that's a pity.
