### ISSUE TITLE
varargs+ntuple bug?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#20188]
I'm getting the following error that I can't figure out.  Seems like a bug, almost as if `args[i]` is returning the type rather than the value in this expression?
```jl
julia> foo{N}(args::Vararg{N}) = ntuple(i -> args[i], Val{N})
foo (generic function with 1 method)

julia> foo(3,4,5)
ERROR: TypeError: ntuple: in typeassert, expected Int64, got Type{Int64}
Stacktrace:
 [1] ntuple(::##1#2{Tuple{Int64,Int64,Int64}}, ::Type{Val{Int64}}) at ./tuple.jl:93
 [2] foo(::Int64, ::Vararg{Int64,N} where N) at ./REPL[1]:1
```

**Comment by stevengj** [comment]
Oh, nevermind, it should be `Val{N}()`.

**Comment by pabloferz** [comment]
Shouldn't it be `foo{N}(args::Vararg{Any,N}) = ntuple(i -> args[i], Val{N})`?

**Comment by stevengj** [comment]
Oh, right, I got it in the wrong order, thanks.
