### ISSUE TITLE
Add broadcast!{S,T,N}(identity, A::Array{S,N}, B::Array{T,N}) specialization calling memcpy

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#20227]
#19895 removed an (incorrect and ambiguity-causing) `broadcast!` specialization (roughly `broadcast!{S,T,N}(identity, A::AbstractArray{S,N}, B::AbstractArray{T,N}) = copy!(A, B)`). Restoring a narrower, corrected form of that specialization for `Array`s might be worthwhile; see discussion towards the end of #19895. `@martinholters` sketched an implementation [here](https://github.com/JuliaLang/julia/pull/19895#issuecomment-272386502). (@martinholters, do you plan to wrap that into a PR, or should we mark this up for grabs?) Best!

**Comment by martinholters** [comment]
Will make a PR shortly. Objections if I steal the commit from #20182 and include it to have the specialization and its tests in one PR?

**Comment by Sacha0** [comment]
> Objections if I steal the commit from #20182 and include it to have the specialization and its tests in one PR?

Please do! And please feel welcome to squash the commit from #20182 into the other test commit, no need to preserve authorship. Best!
