### ISSUE TITLE
Regression in min(-Inf, NaN) from 0.5 to 0.6

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20245]
Julia 0.5:  `min(-Inf, NaN)` gives `-Inf`
Julia 0.6: `min(-Inf, NaN)` gives `NaN`

Presumably one of these violates IEEE arithmetic; I believe it is Julia 0.6.

cc @simonbyrne

**Comment by dpsanders** [comment]
cf. the (inconclusive?) discussion in https://github.com/JuliaLang/julia/issues/10729

**Comment by simonbyrne** [comment]
The relevant commit by @stevengj  is https://github.com/JuliaLang/julia/commit/b1ecd5622eedc20e99e8bc70a45a1c7df17badd4 (not sure what is up with the dates on the commit, it was actually merged in September 2016). It doesn't seem to have been made from a PR, but presumably was in response to the discussion in https://github.com/JuliaLang/julia/issues/7866#issuecomment-246850798. Also some discussion in #12552 and #12564.

**Comment by simonbyrne** [comment]
Also, is documented in [NEWS.md](https://github.com/JuliaLang/julia/blob/1303dfb96aa4345dca5d225e7ae72348307aef25/NEWS.md#library-improvements)

**Comment by dpsanders** [comment]
OK, thanks.
