### ISSUE TITLE
LoadError: UndefVarError: int not defined

### ISSUE THREAD

**Issue by rushirg** [JuliaLang/julia#20244]
I am getting LoadError which says like this:
**ERROR: LoadError: UndefVarError: int not defined
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318**
i am converting character to int, as follow:
`yTrain = int(yTrain)`

**Comment by KristofferC** [comment]
Use `Int`.  Also please ask questions on discourse.julialang.org, thanks.
