### ISSUE TITLE
parsing failure for multi-line macro calls and +

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#20258]
Normally, if you type an incomplete binary expression like `1 + 1 +`, then the parser automatically looks to the next line to complete the expression.  However, this doesn't happen in macro calls (in both Julia 0.5 and 0.6):
```julia
julia> 1 + 1 +
       1
3

julia> Base.Test.@test 1 + 1 +
ERROR: MethodError: no method matching @test(::Expr, ::Symbol)
Closest candidates are:
  @test(::ANY) at test.jl:189
```
It seems to be related to the fact that `+` is both a binary and a unary operator, since it works fine for `*`, and hence I think it is a bug:
```julia
julia> Base.Test.@test 1 * 1 *
       1 == 1
Test Passed
  Expression: 1 * 1 * 1 == 1
   Evaluated: 1 == 1
```
(I got bitten by this in #20249 when `.+` became a unary+binary operator.)

**Comment by TotalVerb** [comment]
This seems to happen in all white-space sensitive contexts. For example

```julia
julia> [1 +
        1 2]
2×2 Array{Any,2}:
 1   +
 1  2 
```

```julia
julia> [1 +
        1]
ERROR: ArgumentError: number of columns of each array must match (got (2,1))
 in typed_vcat(::Type{Any}, ::Array{Any,2}, ::Array{Int64,2}) at ./abstractarray.jl:1039
 in vcat(::Array{Any,2}, ::Array{Int64,2}) at ./array.jl:726
 in hvcat(::Tuple{Int64,Int64}, ::Int64, ::Vararg{Any,N}) at ./abstractarray.jl:1361
```

**Comment by TotalVerb** [comment]
A workaround is to append a trailing whitespace

```
julia> @test 1 + ## note: there is a trailing space here
       1 == 2
Test Passed
  Expression: 1 + 1 == 2
   Evaluated: 2 == 2
```

**Comment by TotalVerb** [comment]
I thought this was familiar. This has already been reported at https://github.com/JuliaLang/julia/issues/16594.
