### ISSUE TITLE
Allow `@code_warntype a = f(b)`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20270]
Currently 
```
julia> f(x) = 2x
f (generic function with 1 method)

julia> @code_warntype a = f(1)
ERROR: expression is not a function call, or is too complex for @code_warntype to analyze; break it down to simpler parts if possible
```
It would be nice if it could ignore the `=` and `@code_warntype` the function.

**Comment by andyferris** [comment]
Yes! I get caught out on this *all* the time...

I guess the binding should still occur

**Comment by abalkin** [comment]
@andyferris - the `@code_warntype` does not evaluate the expression that it analyses.  This is the desired behavior when used in the interactive mode because evaluation can be slow and have undesired side-effects. 

Do you want `@code_warntype a = f(x...)` to expand into

```julia
code_warntype(f, x)
a = f(x...)
```

?

**Comment by andyferris** [comment]
No, I think you're right, it shouldn't evaluate it. When I use it I just want the printed output, with the convenience of not having to modify the start of the expression.
