### ISSUE TITLE
Weird manual example of inner/outer constructor. 

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#20296]
See https://github.com/JuliaLang/julia/pull/20285#discussion_r98315576 for more discussion.

cc @tkelman @JeffBezanson

**Comment by tkelman** [comment]
This file should also be showing people how to import and extend base generic functions, not overwrite them with module local shadowing replacements.

**Comment by fredrikekre** [comment]
OP fixed by 679175202f30808991c28d07188cb9309a4fdc78
Will submit a PR for `@tkelman`s comment.
