### ISSUE TITLE
Better deprecation message 

### ISSUE THREAD

**Issue by kindlychung** [JuliaLang/julia#20310]
I think deprecation messages should tell people the new way things work. Example:

```julia
julia> WORD_SIZE
WARNING: Base.WORD_SIZE is deprecated.
  likely near no file:0
64
```

Okay, I should not use `WORD_SIZE` any more, but what should I use instead?

**Comment by yuyichao** [comment]
Essentially dup of https://github.com/JuliaLang/julia/issues/19686#issuecomment-270748434, although that's a different problem from the one originally reported in that issue.

**Comment by yuyichao** [comment]
And for this particular case, the replacement is `Sys.WORD_SIZE`

**Comment by kindlychung** [comment]
Thanks. #19686 concerns location, this one concerns the correct syntax after deprecation. Another example is `{} vector syntax is discontinued`, fine, but what's the new syntax then? I think Julia deprecation messages are systematically unhelpful, even if exact alternative syntax may depend on the context and hence is not possible to pinpoint, at least an url could be given so the user can find out more info? This is a serious pain spot.
