### ISSUE TITLE
Old vectorized functions crash on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#20314]
Doing `sin(rand(100))` produces the right deprecation warning on x86, but leads to a crash on arm master. This is the case with a other such older vectorized functions as well.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2448 (2017-01-28 19:36 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fcc4d89* (0 days old master)
|__/                   |  arm-linux-gnueabihf

julia> sin(rand(100))
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_range_insert

signal (6): Aborted
while loading no file, in expression starting on line 0
terminate called recursively

signal (6): Aborted
while loading no file, in expression starting on line 0
unknown function (ip: 0xb6b3baf5)
gsignal at /lib/arm-linux-gnueabihf/libc.so.6 (unknown line)
abort at /lib/arm-linux-gnueabihf/libc.so.6 (unknown line)
unknown function (ip: (nil))
Allocations: 1214773 (Pool: 1213848; Big: 925); GC: 0
Aborted (core dumped)
```

**Comment by yuyichao** [comment]
Is this the nightly binary?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14550. ARM nightly download seems fine.

This is exactly why I didn't start working on ARM unwinding before a workaround of https://github.com/JuliaLang/julia/issues/14550 was found.

**Comment by ViralBShah** [comment]
This was with a build from source yesterday.

**Comment by yuyichao** [comment]
Then it certain looks like #14550. The solution is to use GCC 4.x or turn on LTO when compiling LLVM. We can't really turn on LTO by default on ARM since I believe it'll not compile on the majority of ARM systems (too high memory usage). Compiling with clang might also work though I've never tested it.
