### ISSUE TITLE
Function definition order matters with generated functions

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#20326]
Any function that is called within a generated function needs to be defined before the generated function definition otherwise  we encounter a `MethodError` from the world being too new:

```julia
julia> f1() = 1
f1 (generic function with 1 method)

julia> @generated function g1()
           v = f1()
           quote
               return $v
           end
       end
g1 (generic function with 1 method)

julia> g1()
1
```

vs.

```julia
julia> @generated function g2()
           v = f2()
           quote
               return $v
           end
       end
g2 (generic function with 1 method)

julia> f2() = 1
f2 (generic function with 1 method)

julia> g2()
ERROR: MethodError: no method matching f2()
The applicable method may be too new: running in world age 21396, while current world is 21397.
Closest candidates are:
  f2() at REPL[5]:1 (method too new to be called from this world context.)
Stacktrace:
 [1] g2(...) at ./REPL[4]:2
```

Introduced with #17057

**Comment by omus** [comment]
cc: @vtjnash

**Comment by yuyichao** [comment]
I believe this is documented.

**Comment by yuyichao** [comment]
Basically dup of https://github.com/JuliaLang/julia/issues/19942. Closing this and any discussion about it can continue on that issue.

**Comment by omus** [comment]
For completeness. Documented in [Metaprogramming](http://docs.julialang.org/en/latest/manual/metaprogramming.html#Generated-functions-1):

> Some operations that should not be attempted include:
> ....
> Calling any function that is defined after the body of the generated function.
