### ISSUE TITLE
Proposal: helpful warning when attempting to import / using a known but uninstalled package

### ISSUE THREAD

**Issue by tpapastylianou** [JuliaLang/julia#20339]
Currently if one attempts to use a package that is not installed, one gets a message like so:

    julia> using DataFrames
    ERROR: ArgumentError: Module DataFrames not found in current path.
    Run `Pkg.add("DataFrames")` to install the DataFrames package.

This is the case whether the package is known to julia or not. For example:

    julia> using dataFrameS
    ERROR: ArgumentError: Module dataFrameS not found in current path.
    Run `Pkg.add("dataFrameS")` to install the dataFrameS package.

    julia> Pkg.add("dataFrameS")
    ERROR: unknown package dataFrameS
    Stacktrace ... (etc etc)

Julia has access to registered packages that can be `Pkg.add`ed automatically by name. It would therefore be useful to have a more helpful message, e.g.

    julia> using DataFrames
    ERROR: ArgumentError: Module DataFrames not found in current path.
    'DataFrames' is a registered julia package; type `Pkg.add("DataFrames")` to install.

versus

    julia> using dataFrameS
    ERROR: ArgumentError: Module dataFrameS not found in current path.
    'dataFrameS' is not a registered julia package; did you mean one of the following: 
        DataFrames
        DataFramesMeta
        DataStreams
    Please check you have typed the module name correctly; if this is not a registered package
    please install the module manually (see http://link.to.julia.manual.relevant.section.com).

Furthermore, as an extension to this proposal, a similar warning would be useful if a function is called that is undefined in the current session, but defined in an already installed package (or even in a not-installed but registered package). This is how octave does it, by maintaining a very simple textfile of function names that comes with the distribution. e.g.:

    >> nanmean
    warning: the 'nanmean' function belongs to the financial package from Octave
    Forge which seems to not be installed in your system.

    >> mat2gray
    warning: the 'mat2gray' function belongs to the image package from Octave Forge
    which you have installed but not loaded.  To load the package, run 'pkg
    load image' from the Octave prompt.

The equivalent in julia could be something like:

    julia> DataFrame(a = 1)
    ERROR: UndefVarError: DataFrame not defined
    Warning: A "DataFrame" function is exported by the following modules
    installed on your system but not currently "used":
        DataFrames

    julia> Pkg.search("DataFrame")    # "+" means installed on system
    7x1 Array{String}
         + DataFrames.jl
           JimmysAwesomeDataFrames.jl
           DataFramesRUs.jl
           DataFramesSux.jl
           SarasCuteDataFrames.jl
           MoarDataFrames.jl
           DataFramesYUDoDis.jl

**Comment by StefanKarpinski** [comment]
In Pkg3 this will just load an installed package for you and if it's not installed but known, will interactivey prompt for installation, which would seem to sufficiently address this, right?

**Comment by andyferris** [comment]
The idea of having Pkg3 track exports seems worthy, too.

**Comment by nalimilan** [comment]
An additional feature mentioned in the description is listing approximate matches when no package is found. This is really helpful when you forget an `s` or get the case wrong. I guess the same code as for `help()` could be used.

**Comment by tpapastylianou** [comment]
@StefanKarpinski not sure if an interactive prompt is necessarily the way to go, but good to see the team has thought / addressed this already.

With regard to some of the later points, does Pkg3 also provide any "search module names / seach exported function names" functionality?

**Comment by KristofferC** [comment]
Issue moved to [JuliaLang/Pkg.jl #690](https://github.com/JuliaLang/Pkg.jl/issues/690) via [**ZenHub**](https://www.zenhub.com/)
