### ISSUE TITLE
StackOverflow in type inference

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#20344]
This is a pretty nifty one that @andreasnoack ran into. Probably related to #20103, but doesn't seem exactly the same.

To reproduce, checkout https://github.com/JuliaStats/Distributions.jl/commit/3e8d9f946b44a99a182ad176c5c365f43f1f83bd and https://github.com/JuliaDiff/ForwardDiff.jl/commit/791cd934166d6dd03705a79d2f346802268636ba (at the time of writing, these are both the head of the master branches of these packages).

Then, run the following: 

```julia
julia> using Distributions

julia> using ForwardDiff

julia> tmp1 = vcat([1,1], 1, 1)
WARNING: An error occurred during inference. Type inference is now partially disabled.
StackOverflowError()
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
intersect_ufirst at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1032 [inlined]
intersect_var at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1100
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
intersect_ufirst at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1032 [inlined]
intersect_var at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1100
intersect at /Users/jarrettrevels/data/repos/julia6/src/subtype.c:1626
⋮ # stacktace repeats for a while until it bubbles back up out of the recursion
4-element Array{Int64,1}:
 1
 1
 1
 1
```

The best part is that this bug can be circumvented by commenting out `Base.zero` and `Base.one` definitions on lines 132 and 135 [here](https://github.com/JuliaDiff/ForwardDiff.jl/blob/791cd934166d6dd03705a79d2f346802268636ba/src/dual.jl#L132).

versioninfo: 

```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2478
Commit dbf41c0 (2017-01-30 18:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by andreasnoack** [comment]
FWIW 93a725d51dde9bc5731e08fd50085108e3d43f3c caused this.

**Comment by mlubin** [comment]
I also see a [similar error](https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/197074472#L7523) on [this branch](https://github.com/JuliaOpt/JuMP.jl/pull/954) of JuMP. At the moment this is blocking me from doing any more work on JuMP compatibility with 0.6.

**Comment by tkelman** [comment]
I get a similar error from `Pkg.test("BaseBenchmarks")` on current master of that (and branch `tk/drop0.4` of FileIO)

**Comment by andreasnoack** [comment]
@JeffBezanson This was broken by 93a725d51dde9bc5731e08fd50085108e3d43f3c, i.e. the commit that fixed https://github.com/JuliaLang/julia/issues/20303

**Comment by JeffBezanson** [comment]
See how far #20448 gets you.
