### ISSUE TITLE
It is possible to create Rationals with 0 denominator

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20349]
```julia
julia> 1//0
1//0

julia> div(1,0)
ERROR: DivideError: integer division error
Stacktrace:
 [1] div(::Int64, ::Int64) at ./int.jl:144
```

Should `1//0` also error out?

**Comment by yuyichao** [comment]
I believe this is intentially used to represent infinity

```jl
julia> typemax(Rational{Int})
1//0
```

**Comment by JeffBezanson** [comment]
Yes, this was intentional.

**Comment by bramtayl** [comment]
The left and right hand limits disagree: -Inf and +Inf respectively.

**Comment by yuyichao** [comment]
> The left and right hand limits disagree: -Inf and +Inf respectively.

You mean `-Inf != Inf` and `-1//0 != 1//0`?

**Comment by bramtayl** [comment]
No 1//a really small positive number is a large positive number, but 1//a really small negative number is a large negative number

**Comment by yuyichao** [comment]
This is not at all aiming for a solution that's mathematically rigorous or even correct so what's the limit of `1/a` in math at `0` does not matter at all. Also note that there isn't a equivalent `//` in math and `1//a` in julia does not accept floating point number so it doesn't even make sense to talk about the limit here.

This is also exactly the same behavior as floating point division `1 / 0` vs `-1 / 0`.

**Comment by StefanKarpinski** [comment]
Since 1 is the smallest non-zero integer value you can divide by, this is a non-issue. It also doesn't really matter how we choose to represent ±inf as rationals as long as they behave correctly.
