### ISSUE TITLE
results for negative y in mod1(x,y) doesn't agree with documentation

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20355]
>    `mod1(x, y)`
>
>Modulus after flooring division, returning a value `r` such that `mod(r, y) == mod(x, y)`
>in the range ``(0, y]`` for positive `y` and in the range ``[y,0)`` for negative `y`

Note " in the range ``[y,0)`` for negative `y`".

```julia
julia> mod1(4, -3)
1

julia> [mod1(i,j) for i in 1:10, j in -1:-1:-10]
10×10 Array{Int64,2}:
 1  1   1   1   1   1   1   1   1   1
 1  0  -1  -2  -3  -4  -5  -6  -7  -8
 1  1   0  -1  -2  -3  -4  -5  -6  -7
 1  0   1   0  -1  -2  -3  -4  -5  -6
 1  1  -1   1   0  -1  -2  -3  -4  -5
 1  0   0  -2   1   0  -1  -2  -3  -4
 1  1   1  -1  -3   1   0  -1  -2  -3
 1  0  -1   0  -2  -4   1   0  -1  -2
 1  1   0   1  -1  -3  -5   1   0  -1
 1  0   1  -2   0  -2  -4  -6   1   0
```

**Comment by GunnarFarneback** [comment]
The integer specialization from #14140 gets negative y wrong. The general definition is fine.
```
julia> mod1.(1.0:10, (-1:-1:-10)')
10×10 Array{Float64,2}:
 -1.0  -1.0  -2.0  -3.0  -4.0  -5.0  -6.0  -7.0  -8.0   -9.0
 -1.0  -2.0  -1.0  -2.0  -3.0  -4.0  -5.0  -6.0  -7.0   -8.0
 -1.0  -1.0  -3.0  -1.0  -2.0  -3.0  -4.0  -5.0  -6.0   -7.0
 -1.0  -2.0  -2.0  -4.0  -1.0  -2.0  -3.0  -4.0  -5.0   -6.0
 -1.0  -1.0  -1.0  -3.0  -5.0  -1.0  -2.0  -3.0  -4.0   -5.0
 -1.0  -2.0  -3.0  -2.0  -4.0  -6.0  -1.0  -2.0  -3.0   -4.0
 -1.0  -1.0  -2.0  -1.0  -3.0  -5.0  -7.0  -1.0  -2.0   -3.0
 -1.0  -2.0  -1.0  -4.0  -2.0  -4.0  -6.0  -8.0  -1.0   -2.0
 -1.0  -1.0  -3.0  -3.0  -1.0  -3.0  -5.0  -7.0  -9.0   -1.0
 -1.0  -2.0  -2.0  -2.0  -5.0  -2.0  -4.0  -6.0  -8.0  -10.0
```

**Comment by KristofferC** [comment]
cc @eschnett

**Comment by cormullion** [comment]
Tangentially: while you're improving the docs (😁) is it worth mentioning this use case:

```
for i in 1:7
      println("$i => $(mod1(i, 3))")
end
1 => 1
2 => 2
3 => 3
4 => 1
5 => 2
6 => 3
7 => 1
```

I spent some time muttering about Julia's 1-based indexing until I asked around and was told about the `mod1()` function, which does what I'd been trying to persuade `mod()` to do — wrap around to the beginning but starting at 1. It's not clear (to me) from the current documentation that that's possible.

**Comment by GunnarFarneback** [comment]
This is a rather unfortunate bug to leave for 1.0, even though the use cases for `mod1`/`fld1` with negative second argument should be rare. For `mod1` the simple solution is to remove the integer specialization. Unfortunately `fld1` has two faulty implementations and the general case isn't correct even for positive arguments.

To spell out the problems more explicitly, this is the kind of inconsistencies between integer and floating point at this point.
```
# Should be -2.
julia> mod1(4, -3), mod1(4.0, -3)
(1, -2.0)

# Should be -1.
julia> fld1(4, -3), fld1(4.0, -3)
(0, -2.0)

# Should be 2.
julia> fld1(4, 3), fld1(4.0, 3)
(2, 1.0)

# This is easily fixed at least.
julia> fldmod1(4, 3), fldmod1(4.0, 3)
ERROR: MethodError: no method matching fldmod1(::Float64, ::Int64)
Closest candidates are:
  fldmod1(::T<:Integer, ::T<:Integer) where T<:Integer at operators.jl:705
  fldmod1(::T<:Real, ::T<:Real) where T<:Real at operators.jl:703
```
A PR is under preparation.

**Comment by GunnarFarneback** [comment]
I should probably have had some closes statement in my PR but this one should be ready to close now.
