### ISSUE TITLE
Can't search for a function with a bang in the HTML docs

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#20363]
<img width="591" alt="screen shot 2017-01-31 at 11 02 39 pm" src="https://cloud.githubusercontent.com/assets/2896623/22496713/76724142-e809-11e6-8393-124e8759008e.png">

Note that it works when searching 0.5 version of docs site; above behavior is only on "latest".

**Comment by tkelman** [comment]
the html is generated by documenter right, so would this issue be better filed there?

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/494

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaDocs/Documenter.jl/pull/560 in Documenter, which was upgraded in #24118
