### ISSUE TITLE
Setting JULIA_EDITOR in Windows

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#20365]
Issue discussed on Discourse https://discourse.julialang.org/t/edit-on-windows/1695

Trying to set JULIA_EDITOR using the "usual" double backslash for Windows:
```
julia> ENV["JULIA_EDITOR"] = "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"
"C:\\Program Files\\Sublime Text 3\\sublime_text.exe"

julia> Base.editor()
4-element Array{AbstractString,1}:
 "C:Program"
 "FilesSublime"
 "Text"
 "3sublime_text.exe"
```
`editor()` calls `shell_split()`.
Is this the expected behaviour of `shell_split`?

A workaround is to "double"-quote the path:
```
julia> ENV["JULIA_EDITOR"] = "\"C:\\Program Files\\Sublime Text 3\\sublime_text.exe\""
"\"C:\\Program Files\\Sublime Text 3\\sublime_text.exe\""

julia> Base.editor()
1-element Array{AbstractString,1}:
 "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"
```

However this workaround seems inconsistent and unintuitive.
It is also problematic when trying to set JULIA_EDITOR from Windows environment variable.

**Comment by ararslan** [comment]
Does it work from within Julia if you do
```julia
julia> ENV["JULIA_EDITOR"] = joinpath("C:", "Program Files", "Sublime Text 3", "sublime_text.exe")
```
?

**Comment by GregPlowman** [comment]
No, doesn't seem to work.
```
julia> ENV["JULIA_EDITOR"] = joinpath("C:", "Program Files", "Sublime Text 3", "sublime_text.exe")
"C:Program Files\\Sublime Text 3\\sublime_text.exe"

julia> Base.editor()
4-element Array{AbstractString,1}:
 "C:Program"
 "FilesSublime"
 "Text"
 "3sublime_text.exe"
```

Also note that `joinpath` appears to not add backslash between `"C:"` and `"Program Files"`
Is this intended?

**Comment by ararslan** [comment]
> Also note that `joinpath` appears to not add backslash between "C:" and "Program Files"
Is this intended?

Not that I know of... What's weird is that `abspath` seems to correctly insert the backslash but does not actually produce a valid file path (on 0.5.0-rc4, the only Windows Julia version to which I have access).

I don't know the ins and outs of file systems (especially Windows) but AFAIK the quotes are required for Windows to correctly recognize paths containing spaces (on Unix the spaces have to be escaped), so your `"\"...\""` solution is actually be the right way to do it. Indeed, a comment in the source suggests so:
```
# Note: the editor path can include spaces (if escaped) and flags.
```

**Comment by yuyichao** [comment]
All the behaviors seems correct maybe apart from `joinpath`. Both escape and quote should work on any system and it should be independent of the shell/os.

**Comment by GregPlowman** [comment]
I guess my point is that if `Base.editor()` returns  `"C:\\Program Files\\Sublime Text 3\\sublime_text.exe"` then `@edit` works. This looks like standard Windows paths treatment in Julia. I don't know anywhere else I need to "double"-quote paths. `ENV` contains many Windows paths, none of which are "double"-quoted.

The problem seems wholly within Julia. `Base.editor()` seems to mangle (via `shell_split()`) the value in `JULIA_EDITOR`. I don't understand why this is necessary. Why does `editor()` call `shell_split()`?

**Comment by yuyichao** [comment]
> The problem seems wholly within Julia. `Base.editor()` seems to mangle (via `shell_split()`) the value in `JULIA_EDITOR`. I don't understand why this is necessary. Why does `editor()` call `shell_split()`?

Because `JULIA_EDITOR` is not a path. It's a command with arguments to start the editor with. Close as dup of https://github.com/JuliaLang/julia/issues/19988. I've left a note in https://github.com/JuliaLang/julia/pull/20162#pullrequestreview-19662301 to make sure this is documented. Please open a new issue if the behavior of `joinpath("C:", "A")` is wrong on windows.

**Comment by GregPlowman** [comment]
OK thanks.
Opened issue for `joinpath` https://github.com/JuliaLang/julia/issues/20375

**Comment by vtjnash** [comment]
> Both escape and quote should work on any system and it should be independent of the shell/os

Not quite true. DOS didn't have a notion of argument lists, so you may need to pass the `windows_verbatim` flag to the `Cmd` constructor to skip the C-compatible argument list processing when call DOS-derived programs like `cmd` on windows.
