### ISSUE TITLE
Wrong display of FloatRange in REPL

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#20380]
E.g.
```julia
julia> u = eps(0.0f0);
julia> l = LinSpace(-u,u,4)
4-element LinSpace{Float32}:
 -1.4013f-45,0.0,1.4013f-45,2.8026f-45
```
but
```julia
julia> l[4]
1.0f-45
```
This doesn't happen for normal `print` and `show`. The reason is that the REPL show calls `print_range` which slices the `FloatRange`. With the recent changes to float ranges, a slice of a `FloatRange` is a `StepRangeLen`
```julia
julia> typeof(l)
LinSpace{Float32}

julia> typeof(l[1:4])
StepRangeLen{Float32,Base.TwicePrecision{Float32},Base.TwicePrecision{Float32}}
```
which has different rounding, so
```julia
julia> l[1:4][4] == l[4]
false
```
I don't know if the solution is to avoid the slicing in `print_range` or change the behavior of `FloatRange` slicing.

**Comment by timholy** [comment]
The more serious part of this is fixed in #20391. There's still something weird about the printing, though. I suspect it comes from this:
```julia
julia> convert(Float64, u)
1.401298464324817e-45
```
which probably explains the 1.4013 part. (I'm not tackling that since it has nothing to do with my code, hopefully someone else will.)
