### ISSUE TITLE
count(itr) to count trues

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#20403]
I think it would be useful to add a method of `count` that takes a single iterable argument of booleans and returns the number of `true` elements.

For example (imagine that the function `iseven` does not exist), I find this:

```julia
count(i % 2 == 0 for i in 1:10)
```

to be more readable than this:

```julia
count(i -> i % 2 == 0, 1:10)
```

**Comment by cossio** [comment]
I could do a PR if someone points me to the correct source file.

**Comment by nalimilan** [comment]
You can find out where the method lives with:
```julia
julia> @which count(isodd, 1:2)
count(pred, itr) in Base at reduce.jl:654
```

**Comment by ararslan** [comment]
This change could be as simple as
```julia
count(itr) = count(identity, itr)
```
That definition matches what we do with other reduction functions.

**Comment by stevengj** [comment]
`countnz(i % 2 == 0 for i in 1:10)` works, but since we already have `count` I agree that a one-argument version makes sense.

**Comment by cossio** [comment]
Closing this, since it is covered by https://github.com/JuliaLang/julia/issues/20404.
