### ISSUE TITLE
change parsing of `~` from macro to operator

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#20406]
From https://github.com/JuliaLang/julia/issues/19598:

- [ ] change parsing of `~` in Base from macro to plain infix operator (https://github.com/JuliaLang/julia/pull/20420)
- [x] change the one user of this as a macro – i.e. StatsModels (https://github.com/JuliaStats/StatsModels.jl/pull/9)

- [ ] update DataFrames to depend on the new version of StatsModels (issue/PR link?)

**Comment by JeffBezanson** [comment]
Currently this has n-ary parsing; `x ~ y ~ z` is parsed as a single 3-argument call. Do we want to keep that?

**Comment by ararslan** [comment]
Regarding updating DataFrames, the situation is a little complex, but we're getting there. Ref https://github.com/JuliaStats/DataFrames.jl/issues/1154#issuecomment-276748093

**Comment by ararslan** [comment]
@JeffBezanson I've never seen that used in the wild (and indeed I didn't even know about it) so I'd guess that if that behavior were removed with the parsing change, few people if anyone would notice. So if it's simpler to take it out then I'd say go for it.

**Comment by StefanKarpinski** [comment]
Good point: try parsing as binary and see if anyone screams 😬

**Comment by GunnarFarneback** [comment]
For what it's worth I have made use of the n-ary parsing, but it's moot when the macro parsing goes away.
