### ISSUE TITLE
nextprod with vector containing 1 gives DomainError 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20410]
```julia
julia> nextprod([1, 2], 10)
ERROR: DomainError:
Stacktrace:
 [1] nextpow(::Int64, ::Int64) at ./intfuncs.jl:284
 [2] collect(::Base.Generator{Array{Int64,1},Base.##410#411{Int64}}) at ./array.jl:389
 [3] nextprod(::Array{Int64,1}, ::Int64) at ./combinatorics.jl:210
```

This error could be better.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/12152

**Comment by KristofferC** [comment]
Not really.. could throw an argument error here.

**Comment by yuyichao** [comment]
Well, I think a `DomainError` is a perfectly good exception to use for this. Also, using an `ArgumentError` won't help with the performance issue at all and that's essentially what #12152 is about.

**Comment by KristofferC** [comment]
This function seems big enough for the performance problem to matter. It even allocates a temp array.

**Comment by yuyichao** [comment]
It seems like a bad idea to decide if a `DomainError` or an `ArgumentError` should be used based on how expensive the function is.

**Comment by KristofferC** [comment]
You were the one who brought up the performance problems. I just argued that performance was not relevant here.

**Comment by yuyichao** [comment]
I mean I don't think we should switching away from `DomainError` just for this. And in case you want to do it more generally, it'll still be the same issue as #12152 even though it's not about `DomainError` anymore.

**Comment by KristofferC** [comment]
OK,  added a comment there.
