### ISSUE TITLE
C compatible Int128 layout on x64

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#20415]
A recent discourse post just reminds me about this....

(Or in general, any C->LLVM mapping that requires explicit padding.)

The alignment for `Int128` on x64 is currently `8` in julia and LLVM. However, AFAIK, it should be `16` in order to match the C ABI. Fixing this may require adding explicit padding fields when we declare the LLVM struct in the same way clang does it. The hard part is to fix all the use of `gep` on a struct in codegen to use the actual field index including the padding field rather than the julia field index.

**Comment by PallHaraldsson** [comment]
https://reviews.llvm.org/D28990

**Comment by simonbyrne** [comment]
Will #22649 fix this?

**Comment by yuyichao** [comment]
Not afaict. The llvm pr might though.

**Comment by vchuravy** [comment]
The llvm PR got reverted in https://github.com/llvm-mirror/llvm/commit/8c54b816e554ff9f9a75ec8a1d50198d2bfd9633.

**Comment by StefanKarpinski** [comment]
I don't think this is a 1.0-blocking issue.

**Comment by yuyichao** [comment]
Note that fixing this will be breaking.

**Comment by StefanKarpinski** [comment]
> Note that fixing this will be breaking.

Only if we declare struct layout to be stable in 1.0, which I don't think we should do.

**Comment by yuyichao** [comment]
What do you mean? The structure layout (and size) is a user observable API so changing that is breaking.

**Comment by StefanKarpinski** [comment]
Yes, but what we promise not to break is up to us.

**Comment by yuyichao** [comment]
Well, that's an API that people needs to rely on so we'll have to call that a breaking change, especially for `isbits` layout.
Whether that can be an API breakage exception for 1.0 is another issue.

**Comment by vtjnash** [comment]
AFAIK, LLVM 18 fixed this?

**Comment by vchuravy** [comment]
We probably should add tests then?
