### ISSUE TITLE
Running julia via homebrew

### ISSUE THREAD

**Issue by sononix** [JuliaLang/julia#20438]
I posted over on 
https://discourse.julialang.org/t/julia-homebrew-install-git-error/1863

not much traction there - finally found I could run tests in the shell - test failed !!!

Base.runtests("libgit2")
     * libgit2              ERROR: LoadError: LoadError: GitError(Code:ERROR, Class:Invalid, Invalid version 0 on git_proxy_options)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#109(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::##29#43)(::String) at /usr/local/Cellar/julia/0.5.0/share/julia/test/libgit2.jl:218
 in mktempdir(::##29#43, ::String) at ./file.jl:286
 in mktempdir(::Function) at ./file.jl:284
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in macro expansion at ./util.jl:226 [inlined]
 in runtests(::String) at /usr/local/Cellar/julia/0.5.0/share/julia/test/testdefs.jl:7
 in (::Base.##600#601{##16#24,Tuple{String},Array{Any,1}})() at ./multi.jl:1030
 in run_work_thunk(::Base.##600#601{##16#24,Tuple{String},Array{Any,1}}, ::Bool) at ./multi.jl:1001
 in #remotecall_fetch#605(::Array{Any,1}, ::Function, ::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1055
 in remotecall_fetch(::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1055
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1080
 in macro expansion at /usr/local/Cellar/julia/0.5.0/share/julia/test/runtests.jl:44 [inlined]
 in (::##15#23{Array{Any,1},UInt64})() at ./task.jl:360
while loading /usr/local/Cellar/julia/0.5.0/share/julia/test/libgit2.jl, in expression starting on line 130
 in #remotecall_fetch#605(::Array{Any,1}, ::Function, ::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1056
 in remotecall_fetch(::Function, ::Base.LocalProcess, ::String, ::Vararg{String,N}) at ./multi.jl:1055
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1080
 in macro expansion at /usr/local/Cellar/julia/0.5.0/share/julia/test/runtests.jl:44 [inlined]
 in (::##15#23{Array{Any,1},UInt64})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in macro expansion at ./task.jl:327 [inlined]
 in (::##11#19)() at /usr/local/Cellar/julia/0.5.0/share/julia/test/runtests.jl:37
 in cd(::##11#19, ::String) at ./file.jl:59
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
while loading /usr/local/Cellar/julia/0.5.0/share/julia/test/runtests.jl, in expression starting on line 26
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.0
Commit 3c9d753* (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin16.0.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

 in runtests(::String, ::Int64) at ./interactiveutil.jl:567
 in runtests(::String) at ./interactiveutil.jl:556

Any suggestion what might be out of sync 

tks 
M

**Comment by tkelman** [comment]
homebrew uses a version of libgit2 that doesn't work with julia 0.5.0, see https://github.com/staticfloat/homebrew-julia/issues/231

unless you can reproduce with a non homebrew build, file homebrew issues there first.

**Comment by vinyll** [comment]
You may install Julia via homebrew with the following: https://github.com/staticfloat/homebrew-julia.
