### ISSUE TITLE
many-dimensional arrays broken in 0.5

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#20449]
A few months back, I reported on discourse that arrays with 5 or more subscripts have severe performance problems in 0.5.0.  This has apparently still not been fixed in 0.5.0 (although it is fixed in 0.6.0).  I've noticed on github that several important packages are preparing to drop 0.4 support.  If the consensus of the core Julia developers is to drop 0.4 support before 0.6.0 is released, then please issue a patch for this bug in 0.5.0, because right now 0.5.0 is unusable for me due to my heavy use of 5- and 6-subscript arrays.    Apparently the patch for this bug is quite simple, but I am not able to patch my system image in Windows 10. (The instructions in the docs for patching system images did not work for me).

Thanks,
Steve Vavasis

**Comment by ararslan** [comment]
I'm not sure where/when exactly it was fixed, but I believe any PR that's deemed a bug fix is backported from master to the affected maintained release branch(es). So if that's the case here, the fix should be in place in 0.5.1. cc @tkelman

**Comment by tkelman** [comment]
which commit fixed it?

**Comment by JaredCrean2** [comment]
I think this is #18774

**Comment by KristofferC** [comment]
Looks like this is fixed and backported.
