### ISSUE TITLE
Tuples can be indexed multidimensionally... kind of

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#20453]
Take a tuple, any old tuple, say `(1,)`. Now try to `getindex` it with as many indices as you'd like.
```julia
julia> (1,)[]  # 0 indices
ERROR: StackOverflowError:
Stacktrace:
 [1] getindex(::Tuple{Int64}) at ./multidimensional.jl:0
 [2] getindex(::Tuple{Int64}) at ./multidimensional.jl:387 (repeats 79999 times)

julia> (1,)[1]  # 1 index
1

julia> (1,)[1,1]  # 2 indices
ERROR: StackOverflowError:
Stacktrace:
 [1] getindex(::Tuple{Int64}, ::Int64, ::Int64) at ./multidimensional.jl:0
 [2] getindex(::Tuple{Int64}, ::Int64, ::Int64) at ./multidimensional.jl:387 (repeats 79999 times)
```
The offending definition is [here](https://github.com/JuliaLang/julia/blob/master/base/multidimensional.jl#L387), reproduced below:
```julia
getindex(t::Tuple, I...) = getindex(t, IteratorsMD.flatten(I)...)
```
It's pretty clear that this method will recurse infinitely since the only more specific `getindex` method for tuples is `getindex(::Tuple, ::Integer)`.

Tuples aren't really multidimensional objects, so it'd probably be best to stick with the one method.

**Comment by StefanKarpinski** [comment]
Removing non-linear indexing of tuples seems like a no-brainer to me, especially since it's currently too broken for it to actually be used anywhere.
