### ISSUE TITLE
Can't define dot product for Matrix/Vector of custom type?

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#20455]
Say I do, 

```julia
julia> type mytype end

julia> *(a::Array{mytype,2}, b::Array{mytype,1}) = 1
* (generic function with 1 method)

julia> m=mytype()
mytype()

julia> [m,m]' * [m,m]
ERROR: MethodError: no method matching dot(::mytype, ::mytype)
 in vecdot(::Array{mytype,1}, ::Array{mytype,1}) at ./linalg/generic.jl:263
 in Ac_mul_B(::Array{mytype,1}, ::Array{mytype,1}) at ./linalg/matmul.jl:73
```

Why is this not using my custom defined `*`, given that the following is true:

```julia
[m,m]'::Array{mytype,2}
[m,m]::Array{mytype,1}
```

and it seems like my definition of `*` is about as specific as it can get? Instead it looks like it goes through `Ac_mul_B` where it eventually errors out. Could this be a bug? 

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by fredrikekre** [comment]
The `'*` operator is actually going to the `Ac_mul_B` function between 2 vectors (`A` conjugate multiplied with `B`). In your case the first vector of `mytype`s is never conjugated. Consider the following:

```julia
julia> type mytype end

julia> m = mytype();

julia> Base.:*(A::Matrix{mytype}, B::Vector{mytype}) = 1

julia> A = [m m]; B = [m, m]; # A is a matrix and B is a vector

julia> A*B # this uses the method defined above
1

julia> Base.Ac_mul_B(A::Vector{mytype}, B::Vector{mytype}) = 2

julia> B'*B # this go to Ac_mul_B above
2
```

You could also overload the actual `dot` operator in julia:

```julia
julia> Base.dot(A::Vector{mytype}, B::Vector{mytype}) = 3

julia> dot(B, B)
3

julia> B⋅B # also the dot operator
3
```

You could also consult the [julia forum](https://discourse.julialang.org/) on discourse for this type of questions.
Hope that clear things up!

**Comment by marius311** [comment]
Thanks, I wasn't aware `'*` was an operator on its own. Moreover, I wasn't aware it behaved as weirdly as I see it now does, for example I can't force the conjugation to happen even with parentheses:

```julia
julia> ([m,m]') * [m,m]
ERROR: MethodError: no method matching dot(::mytype, ::mytype)
 in vecdot(::Array{mytype,1}, ::Array{mytype,1}) at ./linalg/generic.jl:263
 in Ac_mul_B(::Array{mytype,1}, ::Array{mytype,1}) at ./linalg/matmul.jl:73
```

I have to store a separate variable to make it work:

```julia

julia> mt=[m,m]'
1×2 Array{mytype,2}:
 mytype()  mytype()

julia> mt*[m,m]
1
```

A bit odd tbh and maybe deserving its own issue? In any case, I'll close this one.
