### ISSUE TITLE
FreeBSD: julia-0.5 build failed with clang 4.0

### ISSUE THREAD

**Issue by iblis17** [JuliaLang/julia#20454]
Hi,
We have had [a FreeBSD port](https://svnweb.freebsd.org/ports/head/lang/julia/) for julia already, although it is still not elaborated enough. 
The dev repo is [here](https://github.com/lwhsu/freebsd-ports-lang-julia).

Currently, the freebsd `-CURRENT` branch, the development branch, is upgrading Clang in the base to 4.0. (ref: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216008). And got some build failures in ports. 

Julia is [included](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216770).
Quote from bugzilla:
```
LoadError("sysimg.jl",309,LoadError("irrationals.jl",112,AssertionError("Float64(φ) == Float64(big(φ))")))
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
gmake[2]: *** [Makefile:229: /wrkdirs/usr/ports/lang/julia/work/julia-0.5.0/usr/lib/julia/sys.o] Error 1
```

`Make.user` :
```
└─[iblis@imfsa]% cat Make.user   
USE_SYSTEM_ARPACK=      1
USE_SYSTEM_BLAS=        1
USE_SYSTEM_GMP=         1
USE_SYSTEM_LAPACK=      1
USE_SYSTEM_LIBGIT2=     1
USE_SYSTEM_LIBM=        1
USE_SYSTEM_LIBUNWIND=   1
USE_SYSTEM_LIBUV=       0
USE_SYSTEM_LLVM=        1
USE_SYSTEM_MPFR=        1
# USE_SYSTEM_OPENLIBM=  0
USE_SYSTEM_PATCHELF=    1
USE_SYSTEM_PCRE=        1                                                                                                      USE_SYSTEM_UTF8PROC=    1

LLVM_CONFIG=    llvm-config38

USE_SYSTEM_FFTW=        1
USE_SYSTEM_SUITESPARSE= 1

LIBBLAS=        -lopenblas -L$(LOCALBASE)/lib
LIBBLASNAME=    libopenblas

LIBLAPACK=      $(LIBBLAS)
LIBLAPACKNAME=  $(LIBBLASNAME)
```

Any idea? (I am just a freebsd porter. To be honest, i'm not c/cpp developer, and cannot read any line of julia code...

**Comment by tkelman** [comment]
Does clang 4.0 miscompile MPFR or something? Can you try commenting out the asserts here https://github.com/JuliaLang/julia/blob/e4809693eaa331718527652968a35092146872bb/base/irrationals.jl#L126-L128 and see if the build gets any further? Would be easier to debug if you can get to a REPL / run tests.

**Comment by ViralBShah** [comment]
cc @ararslan

**Comment by iblis17** [comment]
I commented out those lines, and the build finished.
Here is the output of `make test`: https://gist.github.com/iblis17/72494b8a0ade3e5bb8b6f699902e633f

**Comment by tkelman** [comment]
And if you build with clang 3.8 or 3.9 you don't have these issues? Looks like clang may have changed something with its floating point handling?

**Comment by iblis17** [comment]
IIRC, if i build with clang 3.9, the `number` related test cases will pass.
I am building it with clang 3.9, let us wait for the build log.

**Comment by iblis17** [comment]
Here is the log of `make check` on mpfr with clang 4.0: https://gist.github.com/iblis17/72494b8a0ade3e5bb8b6f699902e633f#file-mpfr_check-log

**Comment by tkelman** [comment]
might be a ccall issue with llvm then. If the numbers test passes with clang 3.9 we'll try reducing it to a single call that's giving the wrong result and see whose bug it is

**Comment by iblis17** [comment]
clang 3.8.0 log: https://gist.github.com/iblis17/72494b8a0ade3e5bb8b6f699902e633f#file-clang3-8-log-L54-L67
clang 3.9.1 log:  https://gist.github.com/iblis17/72494b8a0ade3e5bb8b6f699902e633f#file-clang3-9-log-L56-L69

The test cases about float passed, but another test cases failed 😅

**Comment by iblis17** [comment]
@tkelman I can setup a jupyter notebook on my machine for debugging. Are you willing to give it a try?

**Comment by tkelman** [comment]
It looks like you got the same failure on both? Or am I misreading that?

**Comment by iblis17** [comment]
- For clang 3.9 and 3.8, I got a failure related to `BigInt`.
- For clang 4.0, got a failure related to `Float64`, no error about `BigInt`.

**Comment by tkelman** [comment]
Ah, okay I was misreading, thought your most recent post was logs for 3.9 and 4.0, but it was 3.8 and 3.9 which had the same errors. The 4.0 log from earlier has a different error. What do you get at the REPL with clang 4.0 from the following?
```
julia> Float64(int128"10633823966279328163822077199654060032")
1.0633823966279327e37

julia> 0x1p123
1.0633823966279327e37

julia> 1.0633823966279327e37
1.0633823966279327e37

julia> parse(Float64,"1.0633823966279327e37")
1.0633823966279327e37
```

**Comment by iblis17** [comment]
I got this:
```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: FreeBSD (amd64-unknown-freebsd12.0)
  CPU: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.8.1 (ORCJIT, westmere)

julia> Float64(int128"10633823966279328163822077199654060032")
1.0633823966279327e37

julia> 0x1p123
1.0633823966279327e37

julia> 1.0633823966279327e37
1.0633823966279321e37

julia> parse(Float64,"1.0633823966279327e37")
1.0633823966279321e37

```

**Comment by tkelman** [comment]
looks like the problem might be in C `strtod_l` messing up the last digit? or ccall's handling of floats. try a C test case that does strtod of that same number and see what happens?

**Comment by iblis17** [comment]
OMG, got this
```
julia@clang40-dev:~ % cat test.c
#include <stdio.h>      /* printf, NULL */
#include <stdlib.h>     /* strtod */

int main ()
{
  char str[] = "1.0633823966279327e37";
  char* end;
  double d;
  d = strtod (str, &end);
  printf("%f\n", d);
  return 0;
}
julia@clang40-dev:~ % cc test.c
julia@clang40-dev:~ % ./a.out 
10633823966279321080272352895186239488.000000
```

**Comment by iblis17** [comment]
And the `strtod_l` version:
```
julia@clang40-dev:~ % cat test.c
#include <stdio.h>
#include <stdlib.h>
#include <xlocale.h>

int main ()
{
  char str[] = "1.0633823966279327e37";
  char* end;
  double d;
  locale_t c_locale = newlocale(LC_ALL_MASK, "C", NULL);

  d = strtod_l(str, &end, c_locale);
  printf("%f\n", d);
  return 0;
}
julia@clang40-dev:~ % cc test.c
julia@clang40-dev:~ % ./a.out 
10633823966279321080272352895186239488.000000
```

**Comment by iblis17** [comment]
The result of clang 3.9 is here
```
└─[iblis@ionic]% cc --version                                                                            [1/28]
FreeBSD clang version 3.9.1 (tags/RELEASE_391/final 289601) (based on LLVM 3.9.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
┌─[~/tmp]
| [Venv(py36)] [-- INSERT --]
└─[iblis@ionic]% cat test.c
#include <stdio.h>
#include <stdlib.h>
#include <xlocale.h>

int main ()
{
  char str[] = "1.0633823966279327e37";
  char* end;
  double d;
  locale_t c_locale = newlocale(LC_ALL_MASK, "C", NULL);

  d = strtod_l(str, &end, c_locale);
  printf("%f\n", d);
  return 0;
}

┌─[~/tmp]
| [Venv(py36)] [-- INSERT --]
└─[iblis@ionic]% cc test.c
┌─[~/tmp]
| [Venv(py36)] [-- INSERT --]
└─[iblis@ionic]% ./a.out
10633823966279326983230456482242756608.000000
```

----
```
"1.0633823966279327e37" and
 1 0633823966279326983230456482242756608.000000
```

**Comment by tkelman** [comment]
yep, just like that. so looks like clang 4.0 miscompiled the freebsd c runtime or something, and it took running julia's tests before anyone noticed? time for a clang and/or freebsd bug report to cross-link here?

**Comment by tkelman** [comment]
since it's the last digit maybe it's technically still within spec, and it's our test that's being too picky about floating point round-triipping, not sure. the other strtod implementations we test against haven't had problems here. Though we do use our own strtod on Windows that we copied from Python since the Windows CRT one was so bad, IIRC.

**Comment by iblis17** [comment]
Ok, I filed the problem on the freebsd's bugzilla.

**Comment by tkelman** [comment]
can you post the link here just for tracking's sake? thanks!

**Comment by iblis17** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216770

**Comment by iblis17** [comment]
Update: this issue has been submitted to LLVM's bugzilla:
https://llvm.org/bugs/show_bug.cgi?id=31928

**Comment by iblis17** [comment]
Solved by adding `-fno-strict-aliasing` compiler flag. 
See also:
https://svnweb.freebsd.org/base?view=revision&revision=313706
