### ISSUE TITLE
Out-of-tree install fails due to docs

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#20457]
Running `make install` from an out-of-tree build seems to fail in the documentation building phase. It appears that the `Makefile` searches the docs `make.jl` script in the build not source directory.
[Gist with the output of `make install`](https://gist.github.com/mortenpi/03bfa592f9664b1cea7df9d3ff51c33c).

**Comment by tkelman** [comment]
try https://github.com/JuliaLang/julia/pull/20519
