### ISSUE TITLE
Pkg.update() / GitError(Code:ERROR, Class:Reference, Corrupted loose reference file: HEAD)

### ISSUE THREAD

**Issue by santiagofranchi** [JuliaLang/julia#20473]
Windows 10, updating pkgs last Friday have a problem with my pc which shutdown, and now when I try to run  `Pkg.update()` process I receive this erros, thanks in advance:

```
Pkg.update()

INFO: Updating METADATA...
INFO: Updating cache of DataFrames...

GitError(Code:ERROR, Class:Reference, Corrupted loose reference file: HEAD)

 in macro expansion at .\libgit2\error.jl:99 [inlined]
 in head(::Base.LibGit2.GitRepo) at .\libgit2\reference.jl:23
 in head_oid(::Base.LibGit2.GitRepo) at .\libgit2\repository.jl:45
 in installed_version(::String, ::Base.LibGit2.GitRepo, ::Dict{VersionNumber,Base.Pkg.Types.Available}) at .\pkg\read.jl:123
 in #7 at .\pkg\read.jl:208 [inlined]
 in with(::Base.Pkg.Read.##7#8{Dict{String,Tuple{VersionNumber,Bool}}}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:638
 in with(::Function, ::Type{Base.LibGit2.GitRepo}, ::String, ::Vararg{String,N}) at .\libgit2\types.jl:644
 in installed(::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at .\pkg\read.jl:207
 in update(::String, ::Set{String}) at .\pkg\entry.jl:392
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in update() at .\pkg\pkg.jl:210
```

**Comment by nalimilan** [comment]
Try removing `.julia/DataFrames`. Though it would be great if the package system was able to propose fixing this automatically.

**Comment by santiagofranchi** [comment]
Thanks for your help! No, doesn´t work. The same error.

**Comment by lobingera** [comment]
"fixing this automatically." or at least on request: Pkg.init(:rebuild)

**Comment by santiagofranchi** [comment]
Thanks!

Pkg.init(:rebuild)

MethodError: no method matching init(::Symbol)
Closest candidates are:
  init() at pkg/pkg.jl:70
  init(::AbstractString) at pkg/pkg.jl:70
  init(::AbstractString, ::AbstractString) at pkg/pkg.jl:70

**Comment by nalimilan** [comment]
Try `Pkg.init()`, and if that's not enough remove the `.julia` folder. Though be sure to backup `.julia/REQUIRE` if you want to save the list of installed packages.

**Comment by lobingera** [comment]
@santiagofranchi This was only a comment about a feature, that we might need. This isn't available right now.

**Comment by santiagofranchi** [comment]
@lobingera  ok! thanks jajaja

**Comment by santiagofranchi** [comment]
@nalimilan thanks!!! Done!!
