### ISSUE TITLE
Top stack frame missing in backtrace

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#20474]
```
julia> foo(a) = S
foo (generic function with 1 method)

julia> bar(a) = foo(a)
bar (generic function with 1 method)

julia> bar(1)
ERROR: UndefVarError: S not defined
Stacktrace:
 [1] bar(::Int64) at ./REPL[60]:1
```

**Comment by yuyichao** [comment]
Isn't this the issue that simple functions aren't inlined with metadata?

**Comment by Keno** [comment]
Maybe, but if it throws an error, it should tell me where it is. This is one of the most frustrating things about backtraces currently.

**Comment by c42f** [comment]
I've just tested and this works in 1.0
