### ISSUE TITLE
isdefined() gives unexpected result inside of __init__()

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#20487]
When trying to test if a particular value had been set within `deps.jl`, I discovered that `__init__()` is run inside the `Main` module (e.g. `current_module()` returns `Main`) which causes fun strangeness like the following:

```julia
# module_test.jl
module Foo

const bar = 1
function __init__()
    if isdefined(:bar)
        println("bar is defined!")
    else
        println("bar is undefined!")
    end

    println("Value of bar: $bar")
end
end # module Foo

using Foo
```
```
$ julia module_test.jl
bar is undefined!
Value of bar: 1
```

This can be easily remedied by using `isdefined(Foo, :bar)`, but it seems to me that having a situation where `isdefined()` fails to resolve scope the same way as the actual compiler is a bug.

**Comment by amitmurthy** [comment]
The doctstring for `current_module` is pretty explicit about its behavior - http://docs.julialang.org/en/latest/stdlib/base.html#Base.current_module. Maybe we should just add the above code as an example?

**Comment by staticfloat** [comment]
That may be true, and I can see why `current_module()` would have this behavior, but I still argue the functionality of `isdefined()` should always match the scope resolution semantics of the compiler itself.  Otherwise there seems little point to having `isdefined()` at all.

**Comment by yuyichao** [comment]
> `isdefined()` should always match the scope resolution semantics of the compiler itself.

No function can do that. A special expression/syntax might be useful but that's a different issue.

**Comment by vtjnash** [comment]
I recently proposed to Stefan (who was also complaining to me that this was confusing) that we eliminate this function entirely and replace it with `@__MODULE__` instead. Looking through base, the current uses of the function are either simply wrong (such as in `isdefined`), existed to work around lowering bugs, or are used in macros to implement macro hygiene (this case is actually correct, but perhaps could be handled better by passing an explicit argument to the macro via #13339).

**Comment by StefanKarpinski** [comment]
What about an `@isdefined` macro? Writing `@isdefined bar` would probably be more intuitive to most people than writing `isdefined(:bar)` is anyway.

**Comment by staticfloat** [comment]
I half expected it to be a macro already since it feels like that kind of operation, similar to `@__FILE__`.
