### ISSUE TITLE
Make ==(a::Nullable{T}, Nullable{T}) return a Bool

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#20504]
I started looking over the recent dot syntax for lifting stuff, and it looks awesome! In particular, I think we are *super* close to something that would really work well with my whole design for Query.jl.

The issue that I think was most tricky in past discussions was that I wanted comparison operators like ``==``, ``<=`` etc. to always return a ``Bool``, even if one of the arguments happens to be a ``Nullable``. @nalimilan I believe was the main voice that argued we should have a consistent lifting story for these, i.e. that they should return a ``Nullable{Bool}``. We never resolved this, but at the end it was pretty clear that there are good arguments on both sides.

I'm now wondering whether we can't have both now.

With the new . syntax for lifting we already have comparison operator versions that return ``Nullable{Bool}``, i.e. ``.==``.

So that might allow us to have ``==`` by itself (and the other operators) to return a ``Bool`` always, and thus address the use case problem I have in Query. Right now it just throws an error if one passes a ``Nullable``, which doesn't seem very useful.

Essentially my proposal here would be to make ``==`` adopt the current ``equals`` semantics if both arguments are ``Nullable``, and then also add definitions that handle mixed ``Nullable{T}`` and ``T`` arguments.

@nalimilan

**Comment by nalimilan** [comment]
That could make sense. If `Nullable` becomes something like a `Union{T, Void}` or `Union{NotNull{T}, Void}` (https://github.com/JuliaLang/Juleps/pull/21), then `==(::Nullable, ::Nullable)` could simply use the standard `==` definition on the wrapped elements, with special cases `nothing == nothing -> true` and `nothing == x::T -> false`. These are actually the C# semantics.

Though we may want to wait for that design to be settled before making this change.

**Comment by davidanthoff** [comment]
Maybe we could remove [this](https://github.com/JuliaLang/julia/blob/master/base/nullable.jl#L244) definition from Base for the 0.6 cycle? That would allow us to implement this proposal in a package during the 0.6 cycle, play with this and see how it goes, and then decide whether that semantics made sense and should be in base or not?

**Comment by nalimilan** [comment]
Removing that definition would be confusing as then `==` would silently fall back to `===`. You can still play with a different definition of  `==` by replacing the method from a package.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaLang/julia/issues/20504

**Comment by non-Jedi** [comment]
@KristofferC I was trying to go back and read some of the historical discussions on Nullable for julia. Do you remember enough to clarify where this was moved to since *this* issue is actually the #20504 you referenced?

**Comment by KristofferC** [comment]
https://github.com/JuliaAttic/Nullables.jl/issues/4

I always end up linking to the same issue when I move thing -.-
