### ISSUE TITLE
Disallow (at least deprecate for 0.6) overloading & and | to not hinder optimiztion opportunities

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#20507]
julia> (|)(x::Bool, y::Bool) = false # Note how not strictly disallowed
ERROR: error in method definition: function Base.| must be explicitly imported to be extended

unlike for:

julia> (||)(x::Bool, y::Bool) = false
ERROR: syntax: invalid identifier name "||"

[Note in C++, && and || are overloadable disabling short-circuiting, and then I guess optimizations..]

julia> import Base.|

julia> (|)(x::Bool, y::Bool) = false
WARNING: Method definition |(Bool, Bool) in module Base at bool.jl:20 overwritten in module Main at REPL[62]:1.
| (generic function with 21 methods)

Yes, I know it's not sane to overload for Bool, but is it needed for implementing similar for BitArray? Of course it's also insane to overload there..

E.g. I want this forced, as it is (similar to that Boolean is immutable):

(&)(x::Bool, y::Bool) = box(Bool,and_int(unbox(Bool,x),unbox(Bool,y)))
(|)(x::Bool, y::Bool) = box(Bool,or_int(unbox(Bool,x),unbox(Bool,y)))

[Can elementwise .| and .& do for all other cases?]

**Comment by JeffBezanson** [comment]
Adding definitions to `|` and `&` doesn't hinder optimizations. If it did, why would that apply to `|` but not e.g. `+` and `-`?
