### ISSUE TITLE
sum|mapreduce versus unrolled for-loop. performance disparity

### ISSUE THREAD

**Issue by felixrehren** [JuliaLang/julia#20517]
`mapreduce` can be much slower than the equivalent `for`-loop. A small ([real-life](https://discourse.julialang.org/t/review-pth-matrix-roots/1866)) example:
```julia
function dsum(A::Matrix)
    z = zero(A[1,1])
    n = Base.LinAlg.checksquare(A)
    B = Vector{typeof(z)}(n)

    @inbounds for j in 1:n
        B[j] = mapreduce(k -> A[j,k]*A[k,j], +, z, 1:j)
    end
    B
end
function dfor(A::Matrix)
    z = zero(A[1,1])
    n = Base.LinAlg.checksquare(A)
    B = Vector{typeof(z)}(n)

    @inbounds for j in 1:n
        d = z
        for k in 1:j
            d += A[j,k]*A[k,j]
        end
        B[j] = d
    end
    B
end

A = randn(127,127)
time(median(@benchmark dsum(A)))/time(median(@benchmark dfor(A)))
```
gives me a performance ratio of about x50 on Julia 0.5, juliabox.com. I think this could be because the `for`-loop can be automatically `simd`, and the mapreduce isn't? When `A = randn(N,N)` and `N` is `16`, the gap is around x75, and for `N = 10000`, the gap is around x25. Replacing the array access `A[j,k]` with `A[rand(1:size(A,1)),rand(1:size(A,2))]` destroys the performance on both, but the ratio becomes x1.

1. Is `simd` the reason why one is x50 faster?
1. Should this be described in [Performance Tips](http://docs.julialang.org/en/latest/manual/performance-tips.html)? `mapreduce` underlies `sum`, so this could be a popular trap that isn't currently mentioned
1. Would this be a useful benchmark? on nanosoldier?
1. Could the performance gap be smaller?

(Benchmarking `mapreduce` versus `for`-loops without array access, I still see a x2 performance gap. E.g. `mapreduce(identity, +, 0, i for i in 1:n)` versus the equivalent integer-summing `for` loop. It looks like this gap [used to be smaller](https://github.com/JuliaLang/julia/issues/16185)? Worth another benchmark in CI?)

**Comment by KristofferC** [comment]
Looks like dup of https://github.com/JuliaLang/julia/issues/15276.

Doing:
```jl
function dsum(A::Matrix)
    z = zero(A[1,1])
    n = Base.LinAlg.checksquare(A)
    B = Vector{typeof(z)}(n)
    @inbounds for j::Int in 1:n
        B[j] = _help(A, j, z)
    end
    B
end

_help(A, j, z) = mapreduce(k -> A[j,k]*A[k,j], +, z, 1:j)
```

gives 

```julia
julia> time(median(@benchmark dsum(A)))/time(median(@benchmark dfor(A)))
1.0013213312412255
```

**Comment by stevengj** [comment]
+1 for putting a benchmark of this in BaseBenchmarks; a PR there would be great.

**Comment by KristofferC** [comment]
Closing as dup of #15276.
