### ISSUE TITLE
Regression in performance since last nanosoldier daily, "scalar", "simd", "nullable", "dates, arithmetic".

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20528]
Nanosoldier got up and running again and the results are: https://github.com/JuliaCI/BaseBenchmarkReports/blob/88752349af4d3e9f4ae325f6d49f98edd661ad4f/daily_2017_2_8/report.md

It looks like a lot but there are not that many categories. To summarize, the following are the categories that I can see have gotten consistently slower:

* "scalar" stuff in general
* "simd"
* "nullable
* "dates", "artihmetic

The commit range is: 78448fa - e2cceb619d100d57

If people have ideas what could have caused this, please post.

**Comment by jrevels** [comment]
ref my comment [here](https://github.com/JuliaLang/julia/commit/e2cceb619d100d57ccdd06aa1fdc6b4ec6d650a5#commitcomment-20807356):

> Note that today's daily build report is comparing against a previous build which used a different version of BenchmarkTools, and so should not be taken as necessarily representative of changes in Julia itself (at least without further benchmarking).
>
> For example the new BenchmarkTools includes JuliaCI/BenchmarkTools.jl#30, which could've "slowed down" some benchmarks compared to the old BenchmarkTools.

Looks like you [just triggered a fairer comparison build](https://github.com/JuliaLang/julia/commit/e2cceb619d100d57ccdd06aa1fdc6b4ec6d650a5#commitcomment-20807331), which should report more meaningful results.

**Comment by KristofferC** [comment]
Thanks for the explanation. If we are lucky, it is just the SIMD ones that are real.

**Comment by KristofferC** [comment]
https://github.com/JuliaCI/BaseBenchmarkReports/blob/0783f58aad397786e26adcb24c1e5f3054dbe6e5/e2cceb6_vs_78448fa/report.md makes this much less alarming than it seemed, so closing.

**Comment by tkelman** [comment]
looks like one real one, isinteger of complex bigfloat?
