### ISSUE TITLE
linspace construction failures

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#20520]
Specifically [this line](https://github.com/JuliaLang/julia/blob/e849169bcf8ef79bd7c1dbfb6200a5a218496ceb/test/ranges.jl#L350
) fails on 32-bit systems. The failure is an `InexactError` and goes away when linspace construction in that loop is commented out, suggesting that there's some code somewhere that does a `trunc`, `floor` or `ceil` to `Int` with a value that is too large to represent as a 32-bit integer.

**Comment by timholy** [comment]
Hmm, tricky. I just searched through `twiceprecision`, and all the `Int` conversions that look dangerous seem to be protected already via a `maxintfloat`. There are some unprotected computations on `len`, but I don't think that's relevant for any of those cases and probably isn't a bug.

**Comment by StefanKarpinski** [comment]
I think this will require a 32-bit VM to debug. Fortunately, it fails on both Win32 and Linux32.

**Comment by tkelman** [comment]
you can use multilib compilers to build 32 bit julia on 64 bit linux. set `ARCH = i686` in Make.user.

**Comment by JeffBezanson** [comment]
I just saw what looks like a range length test failure on 64-bit, apparently due to unlucky random numbers:
https://travis-ci.org/JuliaLang/julia/jobs/199738457

**Comment by StefanKarpinski** [comment]
Hmm. Guess I didn't test thoroughly enough. Hi ho, hi ho, it's off to work we go...

![hi ho hi ho](https://cloud.githubusercontent.com/assets/153596/22760443/737f0b48-ee24-11e6-9e45-c74d1a65cc53.jpg)

**Comment by StefanKarpinski** [comment]
I've actually managed to reproduce this on 64-bit with enough iterations. Some cases:

```jl
(start, step, stop, n) = (-1.7123204f0, 3.2072393f-8, -1.7123204f0, 2)
(start, step, stop, n) = (1.3173739f0, -2.3759904f-8, 1.3173739f0, 3)
(start, step, stop, n) = (1.2467973f0, 4.1729544f-9, 1.2467973f0, 2)
```
