### ISSUE TITLE
colon & linspace fail to hit endpoints sometimes

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#20521]
See [this set](https://github.com/JuliaLang/julia/blob/e849169bcf8ef79bd7c1dbfb6200a5a218496ceb/test/ranges.jl#L342-L357) of new tests, first observed and discussed [here](https://github.com/JuliaLang/julia/issues/20373#issuecomment-276809008). cc: @timholy

**Comment by timholy** [comment]
The remaining concerns about `colon` might need a new issue.
