### ISSUE TITLE
ranges with ambiguous lengths

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#20532]
Uncommon failure case for range tests, [observed by @JeffBezanson](https://github.com/JuliaLang/julia/issues/20520#issuecomment-278481183) turns out to be somewhat philosophical: there are cases where `n` such that `start + (n-1)*step == stop` is not unique even when `step != 0`. Because floating-point. So the philosophical part is what should the length of a range be in such a case? The smallest viable choice of `n`? The largest viable choice of `n`?

**Comment by StefanKarpinski** [comment]
I think that the closest viable value of `n` to `round(Int, (stop-start)/step)` would be a sane choice.

**Comment by oscardssmith** [comment]
Alternative suggestion, should an `InexactError` be thrown when `eps(max(start,stop))>step`? Ranges with floats are weird enough, but I think we should force users to pay attention to code that is almost certainly not behaving properly.

**Comment by lobingera** [comment]
just by curiosity: Does anyone know how matlab adresses this? I run the same code over a wide range of systems and OSs and the only thing i (afair) never had to revisit was linspace or ranges.

**Comment by timholy** [comment]
Always returns a length-1 range:
```matlab
>> a = single(1.3173739)                         

a =

    1.3174

>> st = single(-2.3759904e-8)                

st =

   -2.3760e-8

>> a:st:a

ans =

    1.3174
>> linspace(a, a, 5)

ans =

    1.3174    1.3174    1.3174    1.3174    1.3174
```

**Comment by StefanKarpinski** [comment]
@lobingera: they do a hacky thing where if they hit the stop within a few arbitrary number of ulps, they consider it exact. Note that our implementation already works well enough that we essentially never get bug reports about it. This came up because I added more thorough tests that are wildly pathological some very rare fraction of the time. I literally have to run these tests tens of millions of times before I encounter these kinds of cases, so I'm not surprised you haven't encountered them in practice.

**Comment by StefanKarpinski** [comment]
@oscardssmith – it's a reasonable suggestion, but I think there are two cases here:

1. You depend on/expect the range to have a specific length. This was the case in the tests I added. In this case, you'll quickly get your error since the length will not be what you expect.

2. You don't. In that case, it seems better to give a range that has the right start, stop and step.

So picking a sensible choice like the length closest to `(stop-start)/step` seems to dominate raising an error in terms of usability.

**Comment by tkelman** [comment]
moving the backport label to the PR #20533
