### ISSUE TITLE
function: sum() arithmetic error?!

### ISSUE THREAD

**Issue by ianl15963247** [JuliaLang/julia#20547]
I found out mathematical logic error. After reading "How to file a Bug report", I am still weren't sure how to use it. Can someone please notify the julia contributor about sum().

<img width="412" alt="screen shot 2017-02-09 at 10 14 37 pm" src="https://cloud.githubusercontent.com/assets/19925567/22801364/330b828e-ef15-11e6-85ba-40e76bf6756d.png">

<img width="235" alt="screen shot 2017-02-09 at 10 01 31 pm" src="https://cloud.githubusercontent.com/assets/19925567/22800908/96591fb0-ef13-11e6-9b04-35d262cc8dd0.png">

**Comment by KristofferC** [comment]
https://en.wikipedia.org/wiki/Integer_overflow

**Comment by JeffBezanson** [comment]
We use fixed-size integer types that overflow, by default. See http://docs.julialang.org/en/stable/manual/faq/#why-does-julia-use-native-machine-integer-arithmetic
