### ISSUE TITLE
Documentation for eps(x::AbstractFloat)

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#20542]
The documentation for eps(x::AbstractFloat) is currently worded as

> The distance between `x` and the next larger representable floating-point value of the same
`DataType` as `x`.

which sounds to me like it's defined as  `_eps = x-> nextfloat(x) - x`, which it's not.

```julia
julia> eps(prevfloat(Inf))
1.99584030953472e292

julia> eps(-Inf)
NaN
```
Though for every other value I could think of, `eps` and `_eps` seem to behave the same.

**Comment by stevengj** [comment]
Is there some reason why we shouldn't just define `eps` as `nextfloat(x) - x`?

**Comment by StefanKarpinski** [comment]
That's how I'd originally defined it, but it got changed at some point, IIRC because we weren't following the IEEE 754 spec or something along those lines.

**Comment by oscardssmith** [comment]
I looked through IEEE 754 briefly, and didn't find anything on `eps`, might have missed it though. Also we break from IEEE several other times with floats, and this seems like a reasonable one to break even if it isn't technically correct.

**Comment by simonbyrne** [comment]
I think we chose `eps` to match with matlab/octave. I've tried to explain the logic in #20597.
