### ISSUE TITLE
hardcoded ANSI escape codes in Terminals

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#20557]
I was tracking down an issue in my [Emacs-based Julia REPL](https://github.com/tpapp/julia-repl/issues/2), which uses Emacs's `ansi-term`. The issue was that `Base.Terminals.cmove_col` [emits](https://github.com/JuliaLang/julia/blob/master/base/Terminals.jl#L116) `\E[$(n)G`, which `ansi-term` did not know how to deal with. Apparently this concrete issue will be fixed with the next Emacs release, but strictly speaking `ansi-term` was behaving correctly, because its `terminfo` entry did not report supporting `CHA` (Cursor Horizontal Absolute), so the Julia REPL should not have used it.

I don't know what the right approach would be to replace hardcoded sequences. For a fully general solution, one could parse `terminfo`, and then emit escape sequences accordingly, emulating missing ones, but that involves a lot of tedious work duplicated in eg `ncurses`, OTOH that using the latter would be overkill.

**Comment by Keno** [comment]
Meh, I'm not sympathetic to this. `terminfo` is a vestige of an earlier time, and causes a ton of complexity. There is really no reason why any terminal emulator shouldn't support the basic escape sequences we use here. Unless I see some pretty strong arguments to the contrary, I'm gonna go with "won't fix".

**Comment by Keno** [comment]
That said, I would take a PR that replaces that particular sequence with something else that is generally supported, if you want an immediate solution.

**Comment by StefanKarpinski** [comment]
VT100 came out in 1978, the year I was born. I think it's on Emacs to get with the program here.

**Comment by tpapp** [comment]
@StefanKarpinski : but AFAIK the `CHA` sequence above is [not supported by VT100](http://ascii-table.com/ansi-escape-sequences-vt-100.php), it is more like VT220 or similar (not that I know much about this).

The [linenoise](https://github.com/antirez/linenoise) library claims that one can emulate everything using VT100 codes. At least implementing that would be worthwhile, especially if it works with "semi-dumb" terminals like `comint-mode` & derivatives in Emacs.

**Comment by tpapp** [comment]
@StefanKarpinski : but AFAIK the `CHA` sequence above is [not supported by VT100](http://ascii-table.com/ansi-escape-sequences-vt-100.php), it is more like VT220 or similar (not that I know much about this).

The [linenoise](https://github.com/antirez/linenoise) library claims that one can emulate everything using VT100 codes. At least implementing that would be worthwhile, especially if it works with "semi-dumb" terminals like `comint-mode` & derivatives in Emacs.

**Comment by vtjnash** [comment]
it looks like linenoise recently removed it's usage of `CHA` for a similar reason (https://github.com/antirez/linenoise/commit/0a745fca68efdfe70cde46c588f41dd38f225da8)

**Comment by Keno** [comment]
I don't like doing it that way, because it relies on the terminal emulator being lenient in accepting movement past the edge of emulated area. Now, terminal emulators are generally fine with that, but I think it also masks bugs.

**Comment by StefanKarpinski** [comment]
> it is more like VT220 or similar

1983 is still 34 years ago, but it's a little more reasonable for systems not to support it.

**Comment by vtjnash** [comment]
Ah, yes. Continuing my code archeology there, it was reverted since it broke more important terminal emulators. Sending `\r` however, seemed to work everywhere, and is what it does now (https://github.com/antirez/linenoise/commit/01e723a095c181155e90fab2f9bb161c050a27ac)
