### ISSUE TITLE
Spurious method ambiguity error

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#20570]
On current master the following code generates an ambiguity error which does not happen on 0.5. Commenting out the second `convert` method and uncommenting the third one fixes the problem. Yet adding free type parameters shouldn't make any difference.

```julia
immutable CategoricalValue{T, R <: Integer}
    pool::T
    level::R
end

Base.convert{T, R}(::Type{CategoricalValue{T, R}}, x::CategoricalValue{T, R}) = 1
Base.convert{T}(::Type{T}, x::CategoricalValue) = 2
#Base.convert{S, T, R}(::Type{T}, x::CategoricalValue{S, R}) = 3

x = CategoricalValue{String, Int}("a", 1);

convert(CategoricalValue{String, Int}, x)
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/11597#issuecomment-275883785

**Comment by nalimilan** [comment]
I suspected this was already known, but it's hard for me to tell. Feel free to close.

**Comment by JeffBezanson** [comment]
Dup of #6383
