### ISSUE TITLE
string literal juxtaposition

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#20575]
`"a"x` is parsed as `"a" * x`, which is probably unintentional, especially given the `a"b"c` string macro syntax. It's very easy to remove, but when you do that `"a"x` becomes syntax for adding doc string "a" to variable `x`. Easy to see why that happens, but it's a bit odd. Should we just make `"a"x` a syntax error, requiring a space?

**Comment by ararslan** [comment]
+1 to making `"a"x` a syntax error and requiring a space. The only time I've seen `"a"x` used as string literal juxtaposition on purpose is in code golf, which isn't exactly a compelling use case.
