### ISSUE TITLE
Issues of eigmax and eigs with large Hermitian matrices

### ISSUE THREAD

**Issue by nangeschnappt** [JuliaLang/julia#20601]
1. `eigmax` seems to be quite inefficient with large Hermitian matrices. Here is an example.
```julia
m = 40
n = 20000
A = randn(m,n) + im*randn(m,n);
@time tmp1 = eigs(A'*A, nev=1)[1];
23.828036 seconds (500 allocations: 5.968 GB, 0.04% gc time)
@time tmp2 = eigmax(A'*A);
1787.158813 seconds (40 allocations: 17.897 GB, 0.03% gc time)
```
2. `eigs` returns a complex eigenvalue (with extremely small imaginary part) instead of a real one.
```julia
tmp1[1]
43476.6589828657 + 1.0863724496936137e-12im
tmp2
43476.65898286593
```
```julia
versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```
Update: The second issue also applies to small Hermitian matrices.

**Comment by andreasnoack** [comment]
There are two issues here.

1. `eigmax` uses an algorithm where the input matrix is converted to a bidiagonal form which is a relatively expensive computation when only an extreme eigenvalue is requested so maybe we should revisit that.
2. For some reason, the imaginary part returned from `eigs` is not zero. Besides being annoying, it could indicate that indicate that a non-symmetric solver is used which would be slower.

Just realized that something is completely wrong if the symmetry is annotated
```julia
julia> m = 40;

julia> n = 2000;

julia> A = randn(m,n) + im*randn(m,n);

julia> eigs(A'A, nev = 1)[1]
1-element Array{Complex{Float64},1}:
 5100.57+2.81134e-14im

julia> eigs(Symmetric(A'A), nev = 1)[1]
1-element Array{Complex{Float64},1}:
 2034.66+76.704im
```

**Comment by nan2ge1** [comment]
Indeed. Forcing `Hermitian` still produces a complex eigenvalue though.

**Comment by RalphAS** [comment]
`eigs` uses ARPACK, which does not have special code for Hermitian or symmetric complex matrices. To paraphrase the ARPACK user's guide, non-zero imaginary parts due to round-off error should be ignored. (The authors further claim that specializing to the Hermitian case is not worthwhile for their approach, because the differences only apply to the relatively small subspace.) Probably `eigs` should just null out the imaginary parts of eigenvalues when the matrix is Hermitian.

**Comment by andreasnoack** [comment]
@RalphAS Thanks. I wasn't aware that ARPACK didn't have a Hermitian solver. I agree that we should probably return the real part of the values when the input is wrapped in the `Hermitian` type.

**Comment by andreasnoack** [comment]
It is no longer possible to use ARPACK as an alternative method for computing `eigmax` since the ARPACK wrappers have been moved out. We could consider removing the imaginary part in `eigs` for `Hermitian` input but I'm not completely sure about that anymore.
