### ISSUE TITLE
atexit within base/userimg.jl

### ISSUE THREAD

**Issue by DrTodd13** [JuliaLang/julia#20618]
If you put the following in base/userimg.jl and attempt to build Julia 0.5 you will get a segfault.

```
Base.reinit_stdio()

function atexit_test()
    println("In atexit_test.")
end

atexit(atexit_test)
```

**Comment by JeffBezanson** [comment]
This seems to work on master. I tried adding a few more things to `atexit_test`, and it still seems to work.
