### ISSUE TITLE
Flisp leaking into syntax error for eval of a :(=>) Expr

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#20610]
Caused by https://github.com/JuliaLang/julia/pull/20327/commits/0352af08ac32a2442499ca227130294d439b2d29, some packages (e.g. PyTest.jl) were creating Expr's with `:(=>)` heads in macros. Now that gives
```
julia> eval(Expr(:(=>), :foo, (0,1)))
ERROR: syntax: invalid syntax (=> (outerref foo) #<julia: (0, 1)>)
```
Would it be worth attempting to deprecate that to the new call form?

**Comment by StefanKarpinski** [comment]
+1 on a deprecation

**Comment by tkelman** [comment]
@JeffBezanson would it be possible to deprecate macro-generated `:(=>)`-head Expr's?

**Comment by JeffBezanson** [comment]
Yes I can do that.
