### ISSUE TITLE
listen(tempname()) fails on Windows

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaLang/julia#20617]
Linux:
```julia
julia> listen(tempname())
Base.PipeServer(active)

julia> 
```
Windows:
```julia
julia> listen(tempname())
ERROR: ArgumentError: could not listen on path \AppData\Local\Temp\jl_ADD1.tmp
 in listen(::String) at .\stream.jl:944

julia>
```

Both with version v"0.5.0"

Documentation propose this should work also in Windows: http://docs.julialang.org/en/stable/manual/networking-and-streams/#a-simple-tcp-example

> ```julia
> julia> listen("testsocket") # Listens on a UNIX domain socket/named pipe
> PipeServer(active)
> ```

> Note that the return type of the last invocation is different. This is because this server does not listen on TCP, but rather on a named pipe (Windows) or UNIX domain socket.

**Comment by tkelman** [comment]
probably related: https://github.com/JuliaLang/julia/issues/9053

**Comment by vtjnash** [comment]
Windows doesn't support arbitrary paths, it requires that they conform to a specific pattern such that their name prefix (`\\.\path\`) uniquely identifies the filetype: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365783(v=vs.85).aspx

**Comment by TeroFrondelius** [comment]
Thanks @vtjnash this works:
```julia
julia> server = listen("\\\\.\\pipe\\lintserver7632sKFV0Qsock")
Base.PipeServer(active)

julia>
```

I think the documentation needs a small update. Maybe one Windows example? I guess this cannot be a doctest, because it would be Windows only?

How about adding a new function: `tempsocket()` or `tempnamedpipe()`? Which would return correctly named pipe with random temporyname for Windows and tempname() for Linux.
