### ISSUE TITLE
zip() has limits: bug or needs documenting?

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#20615]
Travis found this bug for me on 0.6: It seems that `zip()` can handle up to a certain number of inputs, then complains.

```
julia> a = 1:5
1:5

julia> b = ["e","d","b","c","a"]
5-element Array{String,1}:
 "e"
 "d"
 "b"
 "c"
 "a"

julia> for e in zip(a, b)
           println(e)
       end
(1, "e")
(2, "d")
(3, "b")
(4, "c")
(5, "a")

julia> for e in zip(a, b, a, b, a, b, a, b, a, b, a)
           println(e)
       end
(1, "e", 1, "e", 1, "e", 1, "e", 1, "e", 1)
(2, "d", 2, "d", 2, "d", 2, "d", 2, "d", 2)
(3, "b", 3, "b", 3, "b", 3, "b", 3, "b", 3)
(4, "c", 4, "c", 4, "c", 4, "c", 4, "c", 4)
(5, "a", 5, "a", 5, "a", 5, "a", 5, "a", 5)

julia> for e in zip(a, b, a, b, a, b, a, b, a, b, a, b)
           println(e)
       end
ERROR: type Array has no field a
Stacktrace:
 [1] start at ./iterators.jl:161 [inlined] (repeats 10 times)
 [2] anonymous at ./<missing>:?
```

# Version

```
julia> versioninfo()
Julia Version 0.6.0-dev.2635
Commit dc2459d (2017-02-13 07:46 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

```

**Comment by fredrikekre** [comment]
I did some digging on this. If I annotate `start`, `next` and `done` with `@noinline` for `Zip` it works:

```julia
julia> A = 1:2;

julia> zw = zip(A, A, A, A, A, A, A, A, A, A, A); # this length work on master

julia> z =  zip(A, A, A, A, A, A, A, A, A, A, A, A); # does not work on master

julia> start(z)
(1, (1, (1, (1, (1, (1, (1, (1, (1, (1, (1, 1)))))))))))
```

Too much inlining when the `Zip` is this deep? I guess using `@noinline` is not a good solution since that would slow down for smaller `Zip`s?

(It was a bit confusing debugging this, since [`start(z)`](https://github.com/JuliaLang/julia/blob/cb1aae9aef4eedec839dc246c87a00e9463efa6c/base/iterators.jl#L161) returns `tuple(start(z.a), start(z.z))` which works in the REPL, since `z.z` are on "working depth" :smile: )

**Comment by timholy** [comment]
Related: https://github.com/JuliaLang/julia/blob/cb1aae9aef4eedec839dc246c87a00e9463efa6c/base/tuple.jl#L128-L140

**Comment by martinholters** [comment]
Doing `@code_warntype` reveals that for the working case, the innermost `Zip2` is treated as `Base.Iterators.Zip2{_,_} where _<:UnitRange`, while for the non-working case, it's a `Base.Iterators.Zip2`. Might be related?

**Comment by martinholters** [comment]
Looking closer at the `@code_warntype` output, there is
```julia
      SSAValue(0) = (Core.getfield)(z::Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip2{UnitRange{Int64},UnitRange{Int64}}}}}}}}}}}}, :z)::Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{UnitRange{Int64},Base.Iterators.Zip{_,_}}}}}}}}} where _<:Base.Iterators.Zip2
```
near the top. The innermost type here is `Base.Iterators.Zip{_,_} where _ <: Base.Iterators.Zip2`. Is that just mis-printing, or is that actually wrongly inferred? The first `_` in there should obviously not be a `Zip2`.

**Comment by martinholters** [comment]
Looks like a bug in `limit_type_depth`:
```julia
julia> T=Core.Inference.limit_type_depth(typeof(z.z), 0);

julia> T.var
_<:Base.Iterators.Zip2

julia> T2 = T.body.types[2].types[2].types[2].types[2].types[2].types[2].types[2].types[2]
Base.Iterators.Zip{_<:Base.Iterators.Zip2,_<:Base.Iterators.Zip2}

julia> T2.parameters[1] === T2.parameters[2]
true
```
 Obviously, this would need to be two different `TypeVar`s with different upper bounds.

**Comment by fredrikekre** [comment]
This works on v0.5 actually:

```julia
start(zip(ntuple(i->1:2, N)...))
```

for arbitrary `N` although quite slow for `N` larger than, say, 1000.

**Comment by cormullion** [comment]
@fredrikekre Yes, the bug started to occur when I started Travis testing on v0.6.

**Comment by martinholters** [comment]
`limit_type_depth` was heavily modified as part of #18457. I suspect that's what broke this.
