### ISSUE TITLE
inferred macro has trouble with broadcasted operators?

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#20620]
I came across this behavior in my *StaticArrays* tests:

```julia
julia> v = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> .-v
3-element Array{Int64,1}:
 -1
 -2
 -3

julia> @inferred(.-v)
ERROR: AssertionError: ($(Expr(:globalref, Base.Test, :(==))))(($(Expr(:globalref, Base.Test, :length)))(#46#inftypes), 1)

julia> b = [true,false]
2-element Array{Bool,1}:
  true
 false

julia> .!b
2-element BitArray{1}:
 false
  true

julia> @inferred(.!b)
ERROR: UndefVarError: .! not defined
```

**Comment by TotalVerb** [comment]
This is not specific to unary operators. `@inferred` does not understand dot notation at all. It only appears to work for binary operators because binary operators can be used as function objects.

Note

```julia
julia> @inferred(foo.(true, false))
ERROR: @inferred requires a call expression
```

**Comment by andreasnoack** [comment]
@stevengj Do you have an idea how to handle dot expressions in `inferred`?

**Comment by TotalVerb** [comment]
An easy way to do it would be to `expand` the expression first, though I don't know if this is robust.

**Comment by andreasnoack** [comment]
Had the same idea before posting here but expanded dot expressions are not so simple.
