### ISSUE TITLE
No backtrace for error inside quoted expression in function called from macro

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20644]
```julia
julia> foo(x) = :(x)
foo (generic function with 1 method)

julia> macro foo(x)
              foo(x)
              end
@foo (macro with 1 method)

julia> @foo("hello")
ERROR: UndefVarError: x not defined
```

**Comment by yuyichao** [comment]
There should not be a backtrace from the function since the function doesn't raise an error.

**Comment by dpsanders** [comment]
I see what you mean, but I need a backtrace from somewhere, in order to be able to find the error buried in my code.

**Comment by yuyichao** [comment]
If it's just a symbol, there's no way we can print where it comes from. For a more complex expression this is doable assuming no one filter out the line numbers manually and it's a different issue that we throw those out for too simple expression/macro return.

**Comment by StefanKarpinski** [comment]
Perhaps if there are no line number nodes in the code that's returned by a macro they should be added upon macro expansion? Then at least there would be info about what macro generated it.

**Comment by yuyichao** [comment]
We do that already, just not for expressions that are too simple. That's the "different issue" I mentioned above.

**Comment by StefanKarpinski** [comment]
Ah, I see. In that case, carry on. I guess there's nowhere to put the line node in this case.

**Comment by KristofferC** [comment]
Don't think there is much to do here. The macro expands to `Main.x` which is then just evaluated.
