### ISSUE TITLE
Fails to build pcre2

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#20646]
I just cloned the repo and tried to make like I did in the past.
I have ``USE_SYSTEM_PCRE:=0`` in my ``Make.user``, as the system pcre in debian unstable is at version 3.

make doesn't seem to download or build pcre2 in deps/ at all.
In addition, make stops at some point with:

    make[1]: *** No rule to make target '/home/staging/src/julia/usr/include/pcre2.h', needed by 'pcre_h.jl'.  Stop.

**Comment by wavexx** [comment]
If you need more info, please tell. I'm on debian unstable, where pcre-dev is now pcre3.
I just cloned and attempted a make.

**Comment by tkelman** [comment]
more build output, more information about your system, what else you have installed, what happens if you do `make -C deps distclean-pcre && make -C deps install-pcre`, any steps to reproduce this (something repeatable like a docker container would be ideal)

**Comment by wavexx** [comment]
On Sat, Feb 18 2017, Tony Kelman wrote:
> more build output, more information about your system, what else you
> have installed, what happens if you do make -C deps distclean-pcre &&
> make -C deps install-pcre, any steps to reproduce this (something
> repeatable like a docker container would be ideal)

install-pcre actually moves the build forward. None of the pcre targets
in deps/ seem to be called in my case (including the download of the
dependency), despite setting USE_SYSTEM_PCRE to 0.

My main suspicion is that the system version of pcre (like I said,
pcre3) is causing the pcre2 to be skipped during build entirely.

I cannot debug it further right now.

**Comment by wavexx** [comment]
In an attempt to rebuild julia's master from scratch in a VM, I now incur in the following on today's master:

make[2]: *** No rule to make target '/home/test/src/julia/src/support/hashing.o', needed by '/home/test/src/julia/src/support/libsupport.a'.  Stop.
Makefile:208: recipe for target 'support/libsupport.a' failed
make[1]: *** [support/libsupport.a] Error 2
Makefile:55: recipe for target 'julia_flisp.boot.inc.phony' failed
make: *** [julia_flisp.boot.inc.phony] Error 2

I know it's bad to hijack issues, but are you aware of this issue?

Since pcre2 seem to be downloaded correctly now, I'm fairly confident there was some state that wasn't properly removed and was ready to close this issue.

**Comment by wavexx** [comment]
Ack, I found the issue for both. It was due how I was defining the values in Make.user.
Sorry :/
