### ISSUE TITLE
libgit2 fails with MacOS 10.7

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#20651]
As reported in JuliaLang/IJulia.jl#515 by @dpsanders, the libgit2 library on MacOS is expecting a symbol `_SSLCreateContext`, but this symbol was apparently introduced in MacOS 10.8 (see libgit2/libgit2#3386).  However, our download page advertises the binary as working in MacOS "10.7+".

Apparently it can be worked around by building libgit2 differently (libgit2/libgit2#3389).

**Comment by tkelman** [comment]
Unless it's possible to dynamically detect and switch SSL library at runtime, I think the solution to this will be "drop 10.7 support" in naming, links, and documentation

**Comment by ViralBShah** [comment]
I have been thinking about bumping the min version to 10.8 for a while now. Perhaps this is a good time.

**Comment by stevengj** [comment]
The only other solution would be to build libgit2 to *always* use OpenSSL rather than the built-in TLS functions on MacOS.

**Comment by tkelman** [comment]
using openssl is not desirable from a licensing standpoint, we've moved away from it on linux

**Comment by tkelman** [comment]
we require 10.8 for source builds since https://github.com/JuliaLang/julia/pull/18910 unless you set extra non-default build flags - we've been setting `MACOSX_VERSION_MIN` to 10.7 on the buildbots, apparently optimistically, to avoid changing the names and links everywhere.

**Comment by staticfloat** [comment]
I'm closing this as https://github.com/JuliaLang/julialang.github.com/pull/562 was merged, so the official solution to this is "use 10.8".
