### ISSUE TITLE
Use same code path for `count(pred, itr)` as `sum(pred, itr)`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20663]
`count(pred, itr)` (currently) has the same functionality as `sum(pred, itr)`, only slower:

```
julia> function bench(N)
       r = randn(N)
       @time count(i->i>1.96, r)
       @time sum(i->i>1.96, r)
       end
bench (generic function with 1 method)
```

After warmup on latest master:
```
julia> bench(10^8)
 0.108136 seconds
  0.075002 seconds
```

We could just define `count(pred, itr) = sum(pred, itr)`  ~but the `count` function just seems to be redundant~ (EDITED according to @ararslan's comment below and #20404 ).

This came up in 
https://discourse.julialang.org/t/compute-number-of-values-in-an-array-above-a-threshold/2167

**Comment by tkelman** [comment]
duplicate of https://github.com/JuliaLang/julia/issues/20404

**Comment by ararslan** [comment]
I very much disagree with this. To reiterate what I said in https://github.com/JuliaLang/julia/issues/20404#issuecomment-277327841, I assume the reason that we don't currently have a one-argument count method is that it's equivalent to sum in that case, but should we make `Bool` not a subtype of `Number` (see #19168), it makes more sense to count non-numbers than to sum them, even if we do still define arithmetic on `Bools`. The functionality of `sum` and `count` overlaps in some cases, but I think in general they serve different purposes.

**Comment by dpsanders** [comment]
Yes, I see what you mean; I hadn't seen that issue before I posted the issue.

In any case, `count` should not be 50% slower than `sum` in my example.

**Comment by dpsanders** [comment]
On current master, `count` is nearly 50% slower.

**Comment by dpsanders** [comment]
This seems to be fixed on latest master:
```
julia> r = randn(10^8);

julia> @btime count(i->i>1.96, $r)
  57.402 ms (0 allocations: 0 bytes)
2499971

julia> @btime sum(i->i>1.96, $r)
  56.915 ms (0 allocations: 0 bytes)
2499971
```
