### ISSUE TITLE
Extremely long delay and huge allocation defining `convert`

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#20671]
Accidentally noticed that `using SIUnits` was using more than half of the memory I have.

Reduced to the following file.

```julia
__precompile__()

module M

immutable SIQ{T<:Number,m,kg,s,A,K,mol,cd,rad,sr} <: Number
    val::T
end

function Base.convert{T,S,mS,kgS,sS,AS,KS,molS,cdS,radS,srS,mT,kgT,sT,AT,KT,molT,cdT,radT,srT}(::Type{SIQ{T,mT,kgT,sT,AT,KT,molT,cdT,radT,srT}}, val::SIQ{S,mS,kgS,sS,AS,KS,molS,cdS,radS,srS})
    SIQ{T,mT,kgT,sT,AT,KT,molT,cdT,radT,srT}(convert(T, val.val))
end

end # module
```

When running this from REPL, the method definition takes ~30s to complete with 16+G of allocation. With precompilation (put this in a file `M.jl`, add that to `JULIA_LOAD_PATH` and run `using M`), the loading of the precompiled file takes equally long and has similar allocations that is not free'd, causing a 16-17G peak memory consumption (see memory usage graph below, this is on a system with 32G of memory).

![spectacle l16052](https://cloud.githubusercontent.com/assets/712232/23098577/8ce81f72-f61f-11e6-8dd7-aa9475cf1975.png)

Seems like there are a few problems here.
1. Some type inference/dispatch heuristic might be broken causing us to do much more work than necessary
2. Somehow that work is done twice for precompilation (once on the precompile worker process and once on the loader)
3. In the precompile loader, that works seems to be done with the GC turned off. Causing the memory usage to sky-rocket at ~0.5G/s....

Adding to milestone since this is clearly a regression. We can remove this from the milestone after this is partially fixed if necessary.

**Comment by yuyichao** [comment]
Actually it seems that this is all due to a single type intersection in the ambiguity detection....

```julia
julia> immutable SIQ{T<:Number,m,kg,s,A,K,mol,cd,rad,sr} <: Number
           val::T
       end

julia> a = Tuple{Type{SIQ{T, mT, kgT, sT, AT, KT, molT, cdT, radT, srT}}, SIQ{S, mS, kgS, sS, AS, KS, molS, cdS, radS, srS}} where srT where radT where cdT where molT where KT where AT where sT where kgT where mT where srS where radS where cdS where molS where KS where AS where sS where kgS where mS where S where T
Tuple{Type{SIQ{T,mT,kgT,sT,AT,KT,molT,cdT,radT,srT}},SIQ{S,mS,kgS,sS,AS,KS,molS,cdS,radS,srS}} where srT where radT where cdT where molT where KT where AT where sT where kgT where mT where srS where radS where cdS where molS where KS where AS where sS where kgS where mS where S where T

julia> b = Tuple{Type{T}, T} where T
Tuple{Type{T},T} where T

julia> typeintersect(a, b)
Tuple{Type{SIQ{T,mS,kgS,sS,AS,KS,molS,cdS,radS,srS}},SIQ{T,mS,kgS,sS,AS,KS,molS,cdS,radS,srS}} where srS where radS where cdS where molS where KS where AS where sS where kgS where mS where T

julia> @time typeintersect(a, b)
 30.471441 seconds (240.14 M allocations: 16.675 GiB, 4.19% gc time)
Tuple{Type{SIQ{T,mS,kgS,sS,AS,KS,molS,cdS,radS,srS}},SIQ{T,mS,kgS,sS,AS,KS,molS,cdS,radS,srS}} where srS where radS where cdS where molS where KS where AS where sS where kgS where mS where T
```

So I guess removing it from the precompile loading could be hard. `typeintersect` should probably be faster on this and maybe we can delay the method insertion/ambiguity detection after we turn the GC back on?

**Comment by JeffBezanson** [comment]
+1 to turning the GC on sooner. Of course we need to try to improve type intersection here too.
