### ISSUE TITLE
trying to use pyplot

### ISSUE THREAD

**Issue by yaelvid** [JuliaLang/julia#20679]
<img width="406" alt="aaaaa" src="https://cloud.githubusercontent.com/assets/24911621/23105732/4f87e11c-f6ec-11e6-8e2b-39cf8fb93a35.PNG">

please help me, I want to use the pyplot, I tried to do the commend: "using PyPlot".
in the picture attached is the problem. I tried every thing I cloud find, nothing helped me. 

thanks in advanced

**Comment by KristofferC** [comment]
Hello! Please either use https://discourse.julialang.org/ for questions or  https://github.com/JuliaPy/PyPlot.jl for bug reports about the `PyPlot` package.
