### ISSUE TITLE
make keys(dict) and values(dict) more useful

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#20678]
Currently the very common operation of iterating a Dict's keys in sorted order requires writing the overly verbose `sort!(collect(keys(d)))`. This could be abbreviated to `sort(keys(d))` by adding a `sort` method for `KeyIterator`, but do we manually add methods for all relevant functions in Base? What about user-defined functions that make sense for general collection-like types? At some point (IIRC) I proposed making `KeyIterator` and `ValueIterator` subtypes of `AbstractVector`, which would make many things "just work". The trouble is that indexing is O(n); however, I believe that something like @JeffBezanson's [ordered dict experiment](https://github.com/JuliaLang/julia/pull/10116) could make indexing O(1).

**Comment by StefanKarpinski** [comment]
Mutating `keys(d)` and `values(d)` could actually potentially make sense – `keys(d)[i] = k` and `values(d)[i] = v` could be efficient equivalents of these:

```jl
# keys(d)[i] = k
d[k] = pop!(d, collect(d)[i].first)

# values(d)[i] = v
d[collect(d)[i].first] = v
```

Moreover, if dictionaries are ordered, then writing code like `sort!(keys(d))` could be another way of writing `sort!(d, by=p->p[1])` and similarly `sort!(values(d))` could be equivalent to doing `sort!(d, by=p->p[2])`, assuming `sort!` for Dicts is allowed (questionable since indexing Dicts can't be).

**Comment by ararslan** [comment]
Many moons ago I had a PR for a `sort` fallback that would handle general iterables (#16853), though it was somewhat ill-conceived at the time. The idea was to just `collect` before sorting.

**Comment by JeffBezanson** [comment]
Dup of #10092 (almost exactly 2 years later!) ?

**Comment by rfourquet** [comment]
I would often want to call also `sort(::Dict)` at the REPL, which @ararslan PR would allow.

**Comment by ararslan** [comment]
Wouldn't you want `sort(::Dict)` to give you a `SortedDict` though? 🙂

**Comment by rfourquet** [comment]
Like I said in your PR, I would prefer the predicability of getting an array out. If I wish a `SortedDict`, `SortedDict(::Dict)` is simple enough! As for my visual consumption at the REPL, an array of pairs is plenty enough :)

**Comment by mbauman** [comment]
We probably don't need both of these open.  Closing in favor of #10092.
