### ISSUE TITLE
CartesianIndex version of find/findnz?

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#20684]
Seems like it would be useful to have a version of `find` that returns a vector of cartesian indices, in analogy to the [new `enumerate`](https://github.com/JuliaLang/julia/pull/16378). `findnz` is basically a pre-CartesianIndex version of this idea that only happens to work for 2d arrays. 

One possible API, in analogy with the enumerate API, is to have `find` take a singleton-valued first parameter that selects the output format. 

Thoughts?

**Comment by nalimilan** [comment]
See recent discussion at https://github.com/JuliaLang/Juleps/pull/27.

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/julia/pull/24774 mostly implements this, by returning cartesian indices by default for matrices. It could then be extended so that the type of index is passed as the single argument (for when you want a linear index, or a cartesian index even for a vector).
