### ISSUE TITLE
in-place fftshift and in-place shifted ffts

### ISSUE THREAD

**Issue by JKrehl** [JuliaLang/julia#20696]
For various reasons I have large multidimensional complex datasets (sth like 512^3) which I need both in real space and Fourier transformed, both times centered around 0, i.e. separated by ifftshift(fft(fftshift(A))). Allocating a new array for every transform is a waste of good RAM.

I have not found any in-place fftshift so I wrote my own. The basic idea is to exchange four memory places over cross ( a,b = b,a ) which gives an atomically contained operation and the fftshift can be achieved using (almost) exclusively this operation. 

Of the n-dimensional array a subset of the axes are to be shifted (named `TS` in the code) and one of these axes has to be iterated only half over (denoted `HA`). Actually half of the n-dimensional space has to be iterated over and if split along a not-to-be-shifted axis I cannot use the over-cross exchange operation.
The case of an axis of odd length has to be considered on its own. If it is not the half iterated-over axis it is sufficient to formulate the shift parameters correctly. It it is iterated over (indicated by `HAEV` and that is sometimes unavoidable) one element has to be separately saved before the iteration, a lop-sided cross-exchange be used ( a,b-1 = b,a ) and the saved element copied back in. In order that only one element has to be saved in this case the half-length-iteration is pulled into the innemost loop while otherwise the loops are nested as the elements lie in memory (assuming Fortran order).

It's called `swaphs2!` not to interfere with the builtin `fftshift` and `swaphs!` is a doctored `fftshift` based on `circshift!` which cannot operate in-place.
```julia
using Base.Cartesian

##############################################################################
# an n-dimensional array is shifted along a given subset of its axes for a
# distance of half of the axes length (rounded downwards) as is done by 
# common implementations of fftshift


@generated function _swaphs2!{T, N, TS, HA, HAEV}(dest::AbstractArray{T,N}, src::AbstractArray{T,N}, sizes::NTuple{N, Int}, ::Type{Val{TS}}, ::Type{Val{HA}}, ::Type{Val{HAEV}})
    shift_syms = ((Symbol("sh_", i) for i in 1:N)...)
    wshift_syms = ((Symbol("wsh_", i) for i in 1:N)...)
    
    x_syms = ((Symbol("x_", i) for i in 1:N)...)
    sx_syms = ((TS[i] ? Symbol("sx_", i) : x_syms[i] for i in 1:N)...)
    bsx_syms = ((!HAEV && HA==i ? Symbol("bsx_", i) : sx_syms[i] for i in 1:N)...)
    
    ex = :(($(Expr(:ref, :dest, x_syms...)), $(Expr(:ref, :dest, bsx_syms...))) = ($(Expr(:ref, :src, sx_syms...)), $(Expr(:ref, :src, x_syms...))))
    
    if !HAEV
        ex = quote
            $(x_syms[HA]) = $(shift_syms[HA])+1
            tmp = $(Expr(:ref, :src, x_syms...))
            for $(x_syms[HA]) in 1:sizes[$HA]-$(shift_syms[HA])-1
                $(sx_syms[HA]) = $(x_syms[HA]) + $(shift_syms[HA])+1
                $(bsx_syms[HA]) = $(sx_syms[HA])-1
                $ex
            end
            $(x_syms[HA]) = sizes[$HA]
            $(Expr(:ref, :dest, x_syms...)) = tmp
        end
    end
    
    for i in 1:N
        if i==HA 
            if HAEV
                ex = quote
                    for $(x_syms[HA]) in 1:sizes[$HA]-$(shift_syms[HA])
                        $(sx_syms[HA]) = $(x_syms[HA]) + $(shift_syms[HA])
                        $ex
                    end
                end
            else
                nothing
            end
        else
            if TS[i]
                ex = quote
                    for $(x_syms[i]) in 1:sizes[$i]-$(shift_syms[i])
                        $(sx_syms[i]) = $(x_syms[i]) + $(shift_syms[i])
                        $ex
                    end
                    for $(x_syms[i]) in sizes[$i]-$(shift_syms[i])+1:sizes[$i]
                        $(sx_syms[i]) = $(x_syms[i]) + $(wshift_syms[i])
                        $ex
                    end
                end
            else
                ex = quote
                    for $(x_syms[i]) in 1:sizes[$i]
                        $ex
                    end
                end
            end
        end
    end
    
    quote
        $(Expr(:inbounds, true))
        @nexprs $N i->(sh_i = div(sizes[i], 2))
        @nexprs $N i->(wsh_i = div(sizes[i], 2)-sizes[i])
        
        $ex
        
        $(Expr(:inbounds, :pop))
        dest
    end
end

function swaphs2!{T, N}(dest::AbstractArray{T,N}, src::AbstractArray{T,N}, dim)
    @assert size(dest) == size(src)
    
    sizes = size(src)
    toshift = ((i in dim for i in 1:N)...)
    evensize = map(iseven, sizes)
    halfaxis = findlast(map(&, toshift, evensize))
    if halfaxis==0
        halfaxis = findfirst(toshift)
    end
    
    _swaphs2!(dest, src, sizes, Val{toshift}, Val{halfaxis}, Val{evensize[halfaxis]})
end
```

Of course, based on this shifted ffts that operate in-place can be formulated quite easily.

Is there any interest in this functionality at all?
And in such a (quite unreadable) approach?

If so I could tinker together a testing suite (I have tested it so far against `fftshift` in quite a number of situations and in benchmarking it reliably beat `fftshift`, even with `fftshift`s array allocation overhead removed). Also comment the code and maybe structure it more (this current state is optimized for brevity).

As a bye the bye question: Should I make such a question/contribution a PR from the start?

**Comment by StefanKarpinski** [comment]
cc @stevengj

**Comment by stevengj** [comment]
Seems like a dup of #19923.

**Comment by JKrehl** [comment]
The function `circshift!` is not in place, it does not accept the same array as both arguments. As it is based on copy operations (without intermediate caching) it cannot facilitate in place shifting.

**Comment by stevengj** [comment]
@JKrehl, as discussed in that issue, there is some desire to have a completely in-place `circshift!`. of which `fftshift!` would then be a special case.   (It's no harder to write a general in-place `circshift!` than it is to write an in-place `fftshift!`, by the algorithm I suggested in #16032, so if one is to do this it should be via the general case.)

**Comment by JKrehl** [comment]
Why does `fftshift!` need to be a special case? Since it swaps the half-spaces an algorithm is possible that only modifies each memory cell once and has very benign memory access patterns (it has achieved higher performance than a `fftshift!` based on the current `circshift!` by having a higher L2 HitRatio all the while having a lower IPC and not parallelising or vectoring) in reasonable cases (odd-axis length looks worse but still faster than copy-based `circshift`).

Is there no place for a bespoke half-space swap (or shift because that's the same here) in the light that this problem can be solved more efficiently?

What's the current status of the truly in-place `circshift!`?

**Comment by stevengj** [comment]
Yes, the `fftshift!` special case can be solved slightly more efficiently than `circshift!` because it avoids an extra pass over the array, but both of them have good spatial locality for cache utilization.  (Again, I'm comparing to the true in-place `circshift!` ala the one in suggested in #16032, not the current one that uses a buffer.)  But I'm skeptical that the performance difference matters (in cases where you are doing `fftshift`, you are also presumably doing `fft`, and the latter is far more expensive).

I'd rather see the implementation effort go into a more general-purpose function (`circshift!`) than into a more specialized one.  Especially if the general-purpose code is no longer than the specialized code, as seems to be the case here.  The more code we have, the higher the maintenance cost we incur in the long run.

**Comment by stevengj** [comment]
(By the way, if you really care about performance, a bunch of individual swap loops along each dimension, which is what it looks like your `@generated` function produces, is actually far from optimal along the dimensions that are not contiguous in memory.   See e.g. the section "2d optimized methods (same shift for every row)" in [this homework solutions notebook](https://github.com/stevengj/18S096-iap17/blob/master/pset1/pset1-solutions.ipynb) for performance discussions in a related problem — the case of `fftshift` along only the 2nd dimension of a 2d array is a special case of what is considered in that notebook.   But again, in this application I'm not convinced that such constant-factor performance improvements are worth the effort to pursue.)

**Comment by JKrehl** [comment]
So is it just by lack of manhours that this hasn't been implemented yet?
Is it worth getting into?

There is one swap expression around which loops in Fortran order (except for the odd-axis-length case) are nested (in all the `ex = quote` expressions). When shifting only the second axis, the inner loop is just an iteration.
I considered reshaping arrays to reduce the number of nested loops, as well as using flat indexes, but one has to stop somewhere,

**Comment by stevengj** [comment]
@JKrehl, yes, mostly, although there is also not a complete consensus on what set of functions should be included in Base for this.  See also #19923.

**Comment by JKrehl** [comment]
Something like that?
Shall I do a testset/some benchmarks/a PR?

```julia
@generated function splitreverse!{T,N,I<:Integer}(dest::AbstractArray{T,N}, src::AbstractArray{T,N}, split::NTuple{N, I})
    xs = ((Symbol("x_", i) for i in 1:N)...)
    rxs = ((Symbol("rx_", i) for i in 1:N)...)
    
    ex = :((dest[$(xs...)], dest[$(rxs...)]) = (src[$(rxs...)], src[$(xs...)]))
    
    for i in 1:N
        ex = quote
            $(rxs[i]) = split[$i]
            for $(xs[i]) in 1:$(i==N ? :(div(split[$i]+1, 2)) : :(split[$i]))
                $ex
                $(rxs[i]) -= 1
            end
            $(rxs[i]) = size(src, $i)
            for $(xs[i]) in split[$i]+1:$(i==N ? :(div(size(src, $i)+split[$i]+1, 2)) : :(size(src, $i)))
                $ex
                $(rxs[i]) -= 1
            end
        end
    end
    
    quote
        @inbounds $ex
        dest
    end
end

function circshift!{T,N,I<:Integer}(dest::AbstractArray{T,N}, src::AbstractArray{T,N}, shifts::NTuple{N, I})
    @assert size(dest) == size(src)
    
    splits = map(mod, map(-, shifts), size(src))
    
    splitreverse!(dest, src, splits)
    splitreverse!(dest, dest, size(src))
end
```

**Comment by KristofferC** [comment]
Seems like there is nothing concrete here to do.
