### ISSUE TITLE
Suboptimal assembly for short int ops

### ISSUE THREAD

**Issue by RauliRuohonen** [JuliaLang/julia#20697]
These are suboptimal both with 0.5 and master, with -O3 or without:

    foo1(x) = xor((~x & 1) % Int8, Int8(1))
    foo2(x) = x % Bool

    @code_llvm foo1(1)
    @code_llvm foo2(1)

resulting in:

    define i8 @julia_foo1_65966(i64) #0 !dbg !5 {
    top:
      %1 = and i64 %0, 1
      %2 = xor i64 %1, 1
      %3 = trunc i64 %2 to i8
      %4 = xor i8 %3, 1
      ret i8 %4
    }

    define i8 @julia_foo2_65968(i64) #0 !dbg !5 {
    top:
      %1 = and i64 %0, 1
      %2 = xor i64 %1, 1
      %3 = trunc i64 %2 to i8
      %4 = xor i8 %3, 1
      ret i8 %4
    }

The native code is not any better:

        notl    %edi
        andl    $1, %edi
        xorb    $1, %dil

With the equivalent C code:

    char foo(int x) { return (char)(~x & 1) ^ (char)1;  }

both clang and gcc produce the expected assembly:

        andl    $1, %edi

The C code is somewhat misleading, however. The xor is performed after 
promoting its arguments to int. Julia does not do this promotion — the result 
of xor(Int8, Int8) is Int8, unlike in C where it is Int. Might it be that LLVM
does not optimize this very well, because C does not produce it?

The following Julia code *is* properly optimized:

    fastxor{T}(x::T, y::T) = xor(Int(x), Int(y)) % T

    foo3(x) = fastxor((~x & 1) % Int8, Int8(1))

This results in:

    andb        $1, %dil

**Comment by KristofferC** [comment]
These all now generated the same code.
