### ISSUE TITLE
Splat operator unpacking

### ISSUE THREAD

**Issue by HarrisonGrodin** [JuliaLang/julia#20693]
In Python, one can use the `*` operator to unpack an iterable.
```python
In [1]: head, *tail = [1, 2, 3, 4, 5]

In [2]: head
Out[2]: 1

In [3]: tail
Out[3]: [2, 3, 4, 5]
```

I would love to see this feature in Julia, but using the splat (`...`) operator. It is currently a syntax error, though.
```julia
julia> head, tail... = [1, 2, 3, 4, 5]
ERROR: syntax: invalid assignment location "tail..."
```

Like in Python, it should work in the middle of or at the end of an expression, with any number of other variables before and after it.
```python
In [4]: head, *middle, tail = [1, 2, 3, 4, 5]

In [5]: head
Out[5]: 1

In [6]: middle
Out[6]: [2, 3, 4]

In [7]: tail
Out[7]: 5
```

In the case that the collection does not have enough elements to "fit" into the splatted variable, it should receive an empty collection.
```python
In [8]: head, *tail = [1]

In [9]: head
Out[9]: 1

In [10]: tail
Out[10]: []
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/2626
