### ISSUE TITLE
Dates.Time and UTInstant

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#20701]
The Date and DateTime types have their `instant` field of type `Base.Dates.UTInstant{Base.Dates.Day}` and `Base.Dates.UTInstant{Base.Dates.Millisecond}` respectively.  The Time type has the `instant` field of type `Base.Dates.Nanosecond`, not `UTInstant{Base.Dates.Nanosecond}`.

According to the docs 

> The UTInstant represents a machine timeline based on UT time (1 day = one revolution of the earth). The T is a Period parameter that indicates the resolution or precision of the instant. 

> Time wraps a Nanosecond and represents a specific moment in a 24-hour day. 

It seems that either `typeof(a_time.instant)` should be `UTInstant{Base.Dates.Nanosecond}` or the docs should be changed to explain why it is `Base.Dates.Nanosecond`.

**Comment by StefanKarpinski** [comment]
cc @quinnj, @simonbyrne

**Comment by quinnj** [comment]
Yeah, I wasn't quite sure what to go with here, on the one hand, we have `Date`/`DateTime` which represent fixed moments in an ever-increasing timeline of instants, a timeline which can be re-interpreted if you view the timeline in the lens of UT, UT1, etc. (the Base interpretation is UT, hence `UTInstant`).

On the other hand, `Time` represents a single fixed moment on a timeline that wraps around every 86400000000000 nanoseconds, so not quite the same situation as an ever-increasing timeline. For me, I took the approach that a `Time` is really just a convenient `CompoundPeriod` type that wraps according to a UT rotation of the earth.

Certainly open to other ways to think about it and better ways to go here; just trying to lay down my, admittedly a little shallow, original thoughts.

**Comment by JeffreySarnoff** [comment]
There is computational complexity and an opening for user error that is introduced by decoupling the Time time from the DateTime time, even though one wraps and the other does not. Additionally, most people will consider Time to be the type encoding of a primary concept -- representing it as a CompoundPeriod seems to be less intuitive.  Probably, as so much of DateTime is constructed atop lower resolution `UTInstant`s, this Time type is better off where  `typeof(a_time.instant)` is  `UTInstant{Base.Dates.Nanosecond}` with the docs explaining the resolution+wrapping distinction.

**Comment by quinnj** [comment]
I don't think we've seen any issues w/ having the internal field of `Time` be `Nanosecond`; we can certainly re-open and discuss further is people would like.
