### ISSUE TITLE
Custom getindex() for a tuple of tuples behaves incorrectly inside functions

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#20733]
I find that a custom definition of `getindex()` for a tuple of tuples behaves correctly in REPL, but incorrectly inside functions.

Consider a custom `getindex()` that takes an instance of `NTuple{3,NTuple{2,Int}}` as an input and returns an instance of `NTuple{3,Int}` whose each entry is taken from each inner tuple of the input.  For example, it takes `t = ((3,4), (5,6), (7,8))` and returns `(4,5,8)`.  The implementation of this custom `getindex()` is as follows, and it works as expected in REPL:
```julia
julia> VERSION
v"0.5.1-pre+31"

julia> Base.getindex(t::NTuple{3,NTuple{2,Int}}, i::Int, j::Int, k::Int) = 
(t[1][i], t[2][j], t[3][k])

julia> t = ((3,4), (5,6), (7,8))
((3,4),(5,6),(7,8))

julia> t[2,1,2]
(4,5,8)
```

However, if this new `getindex()` is used inside some function, it suddenly starts omitting the last entry of the output:
```julia
julia> test(t) = t[2,1,2]
test (generic function with 1 method)

julia> test(t)
(4,5)
```

This seems like a bug.  The above experiment was performed in Julia v0.5, but the same result is produced in v0.6 (hashcode 474d05d0be) as well.

**Comment by nalimilan** [comment]
There might be an underlying bug, but generally speaking defining a custom `getindex` method on `Tuple` isn't a good idea, as it may conflict with Base methods on which other code may rely.

**Comment by perrutquist** [comment]
The problem seems to be in the inference of the return type. With `t` and `test`from above:
```
julia> @code_typed test(t)
CodeInfo(:(begin 
        return (Core.tuple)((Base.getfield)((Base.getfield)(t, 1)::Tuple{Int64,Int64}, 2)::Int64, (Base.getfield)((Base.getfield)(t, 2)::Tuple{Int64,Int64}, 1)::Int64, (Base.getfield)((Base.getfield)(t, 3)::Tuple{Int64,Int64}, 2)::Int64)::Tuple{Int64,Int64,Int64}
    end))=>Tuple{Int64,Int64}
```
Note how the `return` statement gets a 3-tuple, which is correctly identified as such, yet the return value of the function is a 2-tuple.

**Comment by wsshin** [comment]
@nalimilan, that's a good point.  Thanks for the warning!  I'll keep that in mind.

Still, it is not acceptable, at least to me, that the same function (`getindex` in this case) behaves differently when it is called inside another function compared to when it is called directly inside REPL...

**Comment by ararslan** [comment]
I think it's generally not recommended to work directly from the release-0.5 branch, which is incrementally updated between 0.5-series patch releases and should not be assumed to be stable. Do you see the same behavior on master?

**Comment by wsshin** [comment]
@ararslan, yes, I can reproduce the problem in the master branch as well, as I alluded at the end of the original posting.  In other words, the problem has existed since v0.5 until the up-to-date v0.6 master.

**Comment by ararslan** [comment]
Sorry, missed the bit at the end.
