### ISSUE TITLE
Can't document bindings named 'hi'

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#20737]
```
julia> """
       test
       """
       function hi()
       1
       end
hi

help?> hi
search: while which shift! @which nothing unshift! eachindex CachingPool

  Hello, Human.
```

**Comment by H-225** [comment]
`hello` has the same problem.

**Comment by Sacha0** [comment]
Ref. #16209

**Comment by malmaud** [comment]
But why was that issue closed instead of this being fixed?

**Comment by ararslan** [comment]
Depends on whether you view it as a bug or a feature. 😉 I assume the other issue was closed since the behavior is more or less intentional, it seems.

**Comment by StefanKarpinski** [comment]
This seems distinctly unuseful. Can we get rid of these "keywords"?

**Comment by ararslan** [comment]
They could be changed from keywords to functions, which can then be overwritten by the user as needed.

**Comment by malmaud** [comment]
It's cute  enough as an eager egg; I just want it to be overridable when a real function comes along.

**Comment by StefanKarpinski** [comment]
Doesn't the function need to be defined in Main then? What's the purpose of these again?

**Comment by JeffBezanson** [comment]
Let's remove them.
