### ISSUE TITLE
unable to build master on OS X 10.12.3

### ISSUE THREAD

**Issue by protogeezer** [JuliaLang/julia#20739]
Clean build with fresh clone results in following error

```Scanning dependencies of target LLVMSupport
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APFloat.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APInt.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/APSInt.cpp.o
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/ARMBuildAttrs.cpp.o
...
[  7%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/TimeValue.cpp.o
[  7%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Valgrind.cpp.o
[  7%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Watchdog.cpp.o
[  7%] Linking CXX static library ../libLLVMSupport.a
Usage: /usr/local/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make[4]: *** [lib/libLLVMSupport.a] Error 1
make[3]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [scratch/llvm-3.9.1/build_Release/build-compiled] Error 2
```

**Comment by ararslan** [comment]
Do you have anything in your Make.user? Can you run `make VERBOSE=1` and post the output in a Gist?

**Comment by protogeezer** [comment]
The gist is:
https://gist.github.com/protogeezer/60d0fe9171ddb96b41f69b47627d83a7

There are a bunch of problems - the build doesn't reliably stop when a build stage returns an error. Or the build is indeterminate when run with the -jN switch. 

Secondly, there are two shared libraries that fail because of the -static flag, the final failed build stage, which might also be due to the static flag, and finally, I believe that the same thing happens with SuiteSparse. This build didn't get that far?

Without the -jN switch it stops when the first error happens.

You all really need to start using CMake. (When is that planned for?)

**Comment by ararslan** [comment]
> You all really need to start using CMake

One of the core contributors ported the build system to CMake a long time ago but it wasn't put in place. I don't think people felt that there was significant benefit to having it in CMake instead of Make.

> When is that planned for?

AFAIK it isn't being considered at the moment.

**Comment by protogeezer** [comment]
WRT the current build problems, if you need any more data I'll be happy to gather whatever is needed.

As far as CMake goes, I've been tracking #11754 for more than a year - it seemed like there was a growing consensus then. It's disappointing that interest has wained. 

I had been hoping to work on bringing 3D visualization to Gadfly via VTK, ITK and Blender - which would require platform specific configuration - for example versions of LibUV using the native runloop. In broad water color brush strokes, VTK doesn't play well with GTK, so I'd need to figure out how to slide in Qt, Cocoa or Windows ... All of that would be much easier - if even possible using CMake. So, how would you recommend fomenting (re)consideration?

**Comment by ihnorton** [comment]
It looks like you may have GNU libtool on your path, which might be from brew or ports. If so, please see the README about the recommended toolchain (Apple native).

Please take the CMake discussion to the other issue, or Discourse.
(what build system Julia uses is the most trivial part of your list -- by far)

**Comment by KristofferC** [comment]
Doesn't seem like anything concrete to do here.
