### ISSUE TITLE
big"x" macro expands to literals that can't be serialized

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#20749]
```julia
julia> typeof(macroexpand(:(big"10")))
BigInt

julia> typeof(macroexpand(:(big"10.0")))
BigFloat
```

This caused some grief when trying to precompile a package that used these "literals" in some functions. Ordinarily precompilation doesn't fail because of pointers in the AST, so this was hard to track down. Probably it would make more sense to expand to `parse(BigInt, "x")` and `parse(BigFloat, "x")`?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15722 Expanding to a parser call will totally defeat the purpose of a macro like this.

**Comment by TotalVerb** [comment]
This is not really a case of "initializing global constants that involve pointers returned by external libraries", because ASTs are not global constants, so at minimum the existing documentation should be amended.
