### ISSUE TITLE
Using/import module in the current directory

### ISSUE THREAD

**Issue by Thuener** [JuliaLang/julia#20760]
Many students ask me why the they can't use modules that are in the current directory. The .juliarc.jl sometimes became messy and it is not easy to explain to beginners. I think at least in the Julia installation the .juliarc.jl file should be created and the current directory added to LOAD_PATH. On linux and MAC is just add the following line to .juliarc.jl:
```julia 
push!(LOAD_PATH, ".")
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/4600. Creating a default `.juliarc.jl` with that would be pretty bad.
