### ISSUE TITLE
Unable to make `BigFloat` with different precision

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#20766]
```julia
julia> x = big"1.0";

julia> precision(x)
256

julia> y = BigFloat(x, 100);

julia> precision(y)
256
```
This should make a `BigFloat` with precision `100`.

**Comment by simonbyrne** [comment]
So the question is: should `BigFloat(x::BigFloat)` be able to give a result with different precision than `x`? What about `convert(::Type{BigFloat}, x::BigFloat)`?

**Comment by dpsanders** [comment]
I seem to have missed your comment, sorry.

I would say that following through the current policy of having a global precision for `BigFloat` construction means that indeed `BigFloat(x::BigFloat)` should convert `x` to a `BigFloat` with the current global precision. 

I do see that `convert(::Type{BigFloat}, x::BigFloat)` is questionable, though...

**Comment by StefanKarpinski** [comment]
Yet again, I find myself feeling that BigFloat should have a precision parameter.

**Comment by dpsanders** [comment]
Yes!
