### ISSUE TITLE
Compilation time regression when extending a Base method.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20780]
One of my packages (https://github.com/KristofferC/Crayons.jl) went from 0.02 seconds load time after precompilation to ~ 1 seconds from 0.5 to 0.6. I was able to reduce it to the following:

```julia
type Crayon end

begin
tic()
Base.print_with_color(crayon::Crayon, io::IO, msg::AbstractString...) =
    Base.with_output_color(print, crayon, io, msg...)
toc()
end
```

On 0.5:
```
elapsed time: 0.015108936 seconds
```

On 0.6:
```
elapsed time: 1.109898606 seconds
```

Removing that method, load time of package goes from 0.02s to 0.04s from 0.5 to 0.6.

**Comment by StefanKarpinski** [comment]
I'm guessing that's the #265 tax.

**Comment by KristofferC** [comment]
Why? I am just adding a new method. Why should there be any recompilation?

**Comment by yuyichao** [comment]
It's clear whether it's #265 or not but the point of the fix is that you only pay for it at method definition time (including figuring out what should trigger the recompilation during type inference) and not the runtime. It at least does spend most of the time in type inference.

**Comment by KristofferC** [comment]
I still think adding +1 second to a package load time (that's not even removed with precompilation) for a one line function that only extends a base method for a new type is unacceptable.

**Comment by vtjnash** [comment]
Oh, this is a bit confusing, since the time cost is in `toc`, not the method. There's definitely something wrong here:
```
julia> begin
       t0 = time()
       Base.print_with_color(crayon::Crayon, io::IO, msg::AbstractString) =
           nothing
       t1 = time()
       tic()
       t2 = time()
       toc()
       t3 = time()
       @show diff([t0, t1, t2, t3])
       end;
elapsed time: 0.048757574 seconds
diff([t0, t1, t2, t3]) = [0.00294709, 1.73136, 0.172295]
```

I don't see any reason that `tic` should have a back-edge to `print_with_color`.

**Comment by KristofferC** [comment]
It exactly the same timings when I had it in my package that did not use `tic`, `toc`. Maybe the `print_with_color` has a bunch of "spurious back edges" to other methods...
