### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on profiling plot

### ISSUE THREAD

**Issue by goldfita** [JuliaLang/julia#20803]
I ran into this problem while diagnosing [another issue](https://github.com/timholy/ProfileView.jl/issues/70).  Note that stem works fine without `@profile`.  It also seems to work if you call stem first and then call `@profile stem`.  Also note, I had [another problem](https://discourse.julialang.org/t/pyplot-crash/1706) with stem crashing when trying to close the window before plotting has finished.  Not sure if both issues are caused by matplotlib...

[profile_pyplot_crash.txt](https://github.com/JuliaLang/julia/files/801234/profile_pyplot_crash.txt)

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/17386
