### ISSUE TITLE
DOC: Memory layout - list of dead terms/links @ Manual

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#20813]
As of 2017-02-09.

Here is the list of terms (marked as code in markdown) that are mentioned @

http://docs.julialang.org/en/latest/devdocs/object.html
https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/object.md

and the result i found when i search them in the master branch of the src repo.

| TERM                        | IN_MASTER? |    WHERE?                                                              |
| --------------------------- | ---------- | ---------------------------------------------------------------------- |
| jl_alloc_array_1d           | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L369        |
| jl_alloc_array_2d           | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L374        |
| jl_alloc_array_3d           | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L381        |
| jl_alloc_tuple              | no         |                                                                        |
| jl_alloc_vec_any            | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L432        |
| jl_apply_array_type         | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L437        |
| jl_apply_type               | yes        | https://github.com/JuliaLang/julia/blob/master/src/jltypes.c#L686      |
| jl_datatype_t               | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L364        |
| jl_egal                     | yes        | https://github.com/JuliaLang/julia/blob/master/src/builtins.c#L316     |
| jl_gc_allocobj              | yes        | https://github.com/JuliaLang/julia/blob/master/src/gc.c#L2376          |
| jl_gc_wb                    | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L652        |
| jl_get_field                | yes        | https://github.com/JuliaLang/julia/blob/master/src/jlapi.c#L233        |
| jl_get_nth_field_checked    | yes        | https://github.com/JuliaLang/julia/blob/master/src/datatype.c#L681     |
| jl_init_types               | yes        | https://github.com/JuliaLang/julia/blob/master/src/jltypes.c#L1471     |
| jl_is_mutable               | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L832        |
| jl_new_array                | yes        | https://github.com/JuliaLang/julia/blob/master/src/array.c#L362        |
| jl_new_arrayv               | no         |                                                                        |
| jl_new_bits                 | yes        | https://github.com/JuliaLang/julia/blob/master/src/datatype.c#L418     |
| jl_new_generic_function     | yes        | https://github.com/JuliaLang/julia/blob/master/src/gf.c#L2422          |
| jl_new_method_instance      | no         |                                                                        |
| jl_new_struct               | yes        | https://github.com/JuliaLang/julia/blob/master/src/datatype.c#L610     |
| jl_new_structv              | yes        | https://github.com/JuliaLang/julia/blob/master/src/datatype.c#L625     |
| jl_new_uniontype            | no         |                                                                        |
| jl_set_typeof               | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L93         |
| jl_symbol                   | yes        | https://github.com/JuliaLang/julia/blob/master/src/symbol.c#L92        |
| jl_tuple                    | no         |                                                                        |
| jl_tuple_t                  | no         |                                                                        |
| jl_tuplev                   | no         |                                                                        |
| jl_typeof                   | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L91         |
| jl_typetag_t                | no         |                                                                        |
| jl_value_t                  | yes        | https://github.com/JuliaLang/julia/blob/master/src/julia.h#L71         |
| newobj                      | no         |                                                                        |
| newstruct                   | no         |                                                                        |

All zombies here:

- jl_alloc_tuple
- jl_new_arrayv
- jl_new_method_instance
- jl_new_uniontype
- jl_tuple
- jl_tuple_t
- jl_tuplev
- jl_typetag_t
- newobj
- newstruct

Hoping this could be helpful when someone needs to update the reference.

**Comment by o314** [comment]
Too much time has passed from there.

Closed to help Julia to stay lean and in good shape.

**Comment by mkitti** [comment]
Hmm, this still needs to be fixed
