### ISSUE TITLE
Python syntax

### ISSUE THREAD

**Issue by Octopoda7** [JuliaLang/julia#20811]
This is kindda lot to ask, but seriously, why not change to the best now? 
Python is more readable and human-friendly, and indentation is better than thousand "end".

**Comment by Octopoda7** [comment]
The Python syntax always uses words, for instance, xor (instead of $), "not", isnot, "and" and "or", etc...

**Comment by nalimilan** [comment]
Sorry, but that's really too late for this kind of change. You should be able to find a few threads about the syntax in the mailing list archives (old Google Group).

**Comment by nalimilan** [comment]
That said, limited changes like using `and` and `or` are not completely excluded (though not very likely either). See https://github.com/JuliaLang/julia/issues/5238.

**Comment by PallHaraldsson** [comment]
@Octopoda7 I recommend just learning the Julia syntax (and semantics), it's not that different. In case it helps you, see also:

https://github.com/TotalVerb/PythonSyntax.jl

Note, this is not for the same Python semantics (e.g. Julia is 1-based, by default).

"`and` and `or` are not completely excluded"

If Julia ends up with those operators, they could end up having slightly different semantics. I've at least proposed that.. e.g. not for sure short-circuit, but another proposal is for aliases, then would be same as Python.

**Comment by femtotrader** [comment]
+1 about adding `not` keyword.
Is there an issue or a PR opened about it?
