### ISSUE TITLE
Still unable to search for macros in the doc

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#20828]
When searching for `@inbounds` and press enter, the earch turns into `%40inbounds` and returns no result.
![spectacle h26173](https://cloud.githubusercontent.com/assets/712232/23365164/0134df3a-fcd0-11e6-83af-6bd45535e62d.png)

Replacing the `%40` in the search box works though before pressing enter again, and returns to the broken state after enter.

![spectacle h26341](https://cloud.githubusercontent.com/assets/712232/23365208/3479ddbe-fcd0-11e6-9d34-da7e161f80e7.png)

Tested on Chromium and Firefox.

Should this be opened here or `Documenter.jl` btw?

**Comment by tkelman** [comment]
Probably Documenter, since it would need to be fixed there, then once available and tagged the update here would be trivial.

**Comment by timholy** [comment]
Also noted that searches for two words produce misleading results, see https://github.com/JuliaLang/julia/issues/21356#issuecomment-293918854.

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/494

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaDocs/Documenter.jl/pull/560 in Documenter, which was upgraded in #24118
