### ISSUE TITLE
Relax timestamp check in precompiled images?

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#20837]
I am running into an issue when I transfer precompiled Julia packages to a GlusterFS volume.
The loader always finds the precompiled files stale. I see this:

```
INFO: JL_DEBUG_LOADING: Rejecting stale cache file /mnt/pkgdefault/.julia/lib/v0.5/JSON.ji (mtime 1.4881987029958088e9) because fil
e /mnt/pkgdefault/.julia/v0.5/JSON/src/JSON.jl (mtime 1.488198702995808e9) has changed.                                            
INFO: Recompiling stale cache file /mnt/pkgdefault/.julia/lib/v0.5/JSON.ji for module JSON. 
```

It seems to be due to [timestamp precision on GlusterFS being different](https://bugzilla.redhat.com/show_bug.cgi?id=1422074).

I think timestamp precision can be different for different filesystems, 1 sec being the lowest among the recent systems. Would it be better to relax the timestamp checking condition to 1 sec? (that is, checking `floor(ftime) != floor(ftime_req)` [here]( https://github.com/JuliaLang/julia/blob/d3de8cc9d9e2676bebd0dd98c4b2ca8e3bcf461e/base/loading.jl#L769) instead).

Ref. #13606: similar issue with docker

**Comment by tkelman** [comment]
Changes that happen in less than a second should still trigger recompilation, so no I don't think relaxing the check in that way is an appropriate fix.

**Comment by tanmaykm** [comment]
I wonder if there is a way to get the precision supported by the underlying filesystem. The check could then use that information. No?

**Comment by tkelman** [comment]
Dunno. Only one of the values gets truncated, right? Extending the way the docker check was done to a different allowed level of truncation should be fine and wouldn't be that likely to have false positives. Just don't take the floor of both sides.

**Comment by tanmaykm** [comment]
Yeah, sounds good. Will send a PR.
