### ISSUE TITLE
New "SSL error: syscall failure: " == "Invalid Content-Type: text/plain" in libgit2 test when building RPM nightlies

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#20860]
I see this consistently for a few days when building RPM nightlies. This is using the system libgit2 (both 0.24 and 0.25), and therefore the system openssl. The error comes form [this line](https://github.com/JuliaLang/julia/blob/c716e638bba74f52114c7adedfe4a653e42c40d0/test/libgit2.jl#L1151). It doesn't seem to happen 100% of the time on 32-bit, but it happens consistently on 64-bit.

Ideas?  FWIW, I can reproduce locally, even though cloning from HTTPS works fine.

```
	From worker 1:	Worker 2 failed running test libgit2:
Some tests did not pass: 316 passed, 1 failed, 0 errored, 0 broken.libgit2: Test Failed
  Expression: err.msg == "Invalid Content-Type: text/plain"
   Evaluated: "SSL error: syscall failure: " == "Invalid Content-Type: text/plain"
Stacktrace:
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:564
 [2] (::##33#40)() at /builddir/build/BUILD/julia/test/runtests.jl:169
 [3] cd(::##33#40, ::String) at ./file.jl:69
 [4] include_from_node1(::String) at ./loading.jl:539
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-25-x86_64/00520900-julia/build.log.gz

**Comment by tkelman** [comment]
do we have a way of forcing a source build to use openssl, when "system libgit2" isn't anything usefully recent?

**Comment by nalimilan** [comment]
What do you mean? libgit2 is recent in the present case.

**Comment by tkelman** [comment]
no, I mean for people who aren't compiling fedora packages to be able to reproduce a libgit2-against-openssl issue

can you try linking libgit2 to mbedtls and see if this ever happens there?

**Comment by nalimilan** [comment]
> no, I mean for people who aren't compiling fedora packages to be able to reproduce a libgit2-against-openssl issue

OK. I don't think it's possible, since we only have variables to use the system libgit2 or mbedtls, not to choose between mbedtls and openssl.

> can you try linking libgit2 to mbedtls and see if this ever happens there?

My standard build from git (using no system dependencies) works fine on the same machine, so no, it never happens.

**Comment by tkelman** [comment]
Does Fedora have mbedtls packaged?

**Comment by nalimilan** [comment]
Yes. I just have tried with `USE_SYSTEM_LIBGIT2=0`, but using other system libraries, but I get a similar error:
```
Error in testset libgit2:
Test Failed
  Expression: findfirst(f, LibGit2.Consts.FEATURE_SSH) > 0
   Evaluated: 0 > 0
Error in testset libgit2:
Test Failed
  Expression: err.msg == "Invalid Content-Type: text/plain"
   Evaluated: "SSL error: ffffffff - UNKNOWN ERROR CODE (0001)" == "Invalid Content-Type: text/plain"
ERROR: LoadError: Test run finished with errors
```
This seems to be due to:
```
CMake Warning at CMakeLists.txt:365 (FIND_PACKAGE):
  By not providing "FindLibssh2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libssh2", but
  CMake did not find one.
  Could not find a package configuration file provided by "Libssh2" with any
  of the following names:
    Libssh2Config.cmake
    libssh2-config.cmake
  Add the installation prefix of "Libssh2" to CMAKE_PREFIX_PATH or set
  "Libssh2_DIR" to a directory containing one of the above files.  If
  "Libssh2" provides a separate development package or SDK, be sure it has
  been installed.
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-25-x86_64/00521284-julia/build.log.gz

Looks like building libgit2 with system libssh2 hasn't been tested?

OTOH, I've discovered that the bug with openssl does not happen in Fedora rawhide, so something must have been fixed recently.

@omus Any suggestions about how to debug this?

**Comment by omus** [comment]
```
Test Failed
  Expression: err.msg == "Invalid Content-Type: text/plain"
   Evaluated: "SSL error: ffffffff - UNKNOWN ERROR CODE (0001)" == "Invalid Content-Type: text/plain"
```
The hostname verification test (above) does work with libgit2 linked against either openssl (Julia 0.5) or mbedtls (Julia 0.6). From what I can tell the missing libssh2 may your issue here. Maybe give `USE_SYSTEM_LIBSSH2=0` a try?

**Comment by nalimilan** [comment]
Yes, that's certainly the issue since apparently CMade didn't find libssh2 at all, but I'd rather debug why using system libraries doesn't work (both with openssl and with mbedtls, though for different reasons).

**Comment by nalimilan** [comment]
Oh, and when you say "linked against either openssl (Julia 0.5)", does that mean openssl isn't supported with 0.6? As noted above, the Fedora system libgit2 uses openssl.

**Comment by nalimilan** [comment]
Mmm, I get the same error even with `USE_SYSTEM_LIBSSH2=0`. The error only goes away with ` USE_SYSTEM_LIBGIT2=0 USE_SYSTEM_LIBSSH2=0 USE_SYSTEM_MBEDTLS=0 USE_SYSTEM_CURL=0`. The last one was required, but it's not enough on its own to fix the problem. Looks like there's a complex interaction between the system libraries.

**Comment by omus** [comment]
> Oh, and when you say "linked against either openssl (Julia 0.5)", does that mean openssl isn't supported with 0.6? As noted above, the Fedora system libgit2 uses openssl.

Julia 0.5 using no system packages uses OpenSSL within LibGit2 while Julia 0.6 with no system packages uses MbedTLS within LibGit2. I was just validating that the SSL error message was the same regardless of using OpenSSL or MbedTLS.

I believe Julia 0.6 will use OpenSSL with LibGit2 if using the system package of LibGit2.

**Comment by tkelman** [comment]
> Julia 0.6 will use OpenSSL with LibGit2 if using the system package of LibGit2.

If that system package of libgit2 was built to use openssl by the distro packager, yes. Fedora's probably does, Debian's doesn't (this is why Debian packaging is stuck at Julia 0.4).

**Comment by nalimilan** [comment]
OK. So any pointers about how I could debug this?

**Comment by nalimilan** [comment]
Since this works on Fedora rawhide, there's no problem to build the official Fedora RPM. I'll bundle mbedtls in the RPM packages on the Copr to support older releases.
