### ISSUE TITLE
Edit link in HTML docs

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#20870]
If I click the "Edit on GitHub" link on a manual page, it currently takes me to the page of a specific commit, e.g. [this one](https://github.com/JuliaLang/julia/blob/017f5b4e5efaa6c32463bfaf610732906b82a2cc/doc/src/manual/introduction.md). However GitHub doesn't let you edit pages that correspond to specific commits, so you need to first change the branch to master (by clicking on the "Tree" dropdown menu, finding `master` buried in there somewhere, clicking on it), then clicking the edit icon. That's a lot of extra steps: 3 extra clicks, plus a bit of searching via scrolling or typing, even if you know what exactly to do.

The situation is a even more confusing for Standard Library pages: clicking on "Edit on GitHub" will take you to the "index" page. To get to the docs of an individual function you need click on "source" instead, but when you change branches it loses the line numbers.

One possible solution would be to have separate "source" and "edit latest" (this could just be a pen icon?) links for both the pages and the embedded function docs: the "source" link would take you to the commit source as it does currently. The "edit latest" link would open up the same file on master, in the GitHub editor: e.g. https://github.com/JuliaLang/julia/edit/master/base/docs/helpdb/Base.jl#L1914-L1929. Obviously this has problems in that the path or line numbers may have changed between the commit and the branch, but there's not much we can really do about that.

**Comment by simonbyrne** [comment]
cc @MichaelHatherly

**Comment by tkelman** [comment]
This should probably be a Documenter.jl issue.

If we have a link anchor to refer to, maybe we can translate the line numbers intelligently.

**Comment by KristofferC** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/367
