### ISSUE TITLE
Manual describes deprecated inner constructor syntax

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#20877]
The [section of the manual about constructors](http://julia.readthedocs.io/en/latest/manual/constructors/#case-study-rational) currently recommends a syntax which prints a deprecation warning. Worse, there's no mention of the correct syntax when one needs type parameters.
```julia
julia> immutable Rational{T<:Integer} <: Real
           num::T
           den::T

           function Rational(num::T, den::T)
               if num == 0 && den == 0
                   error("invalid rational: 0//0")
               end
               g = gcd(den, num)
               num = div(num, g)
               den = div(den, g)
               new(num, den)
           end
       end

WARNING: deprecated syntax "inner constructor Rational(...) around REPL[9]:6".
Use "Rational{T}(...) where T" instead.
```

BTW, it would be useful to document a solution which also works on 0.5 somewhere. Maybe in Compat? Cf. https://github.com/JuliaLang/Compat.jl/issues/332.

**Comment by garrison** [comment]
I suggest this ought to be added to the 0.6.0 milestone.

**Comment by JeffBezanson** [comment]
The text on that page doesn't match what's currently in the source tree: https://github.com/JuliaLang/julia/blob/762c6db94092e70cc489a348186bd3760b2df545/doc/src/manual/constructors.md#case-study-rational
I definitely updated the manual for this.

**Comment by yuyichao** [comment]
The RTD version is not used anymore. The correct version is this. https://docs.julialang.org/en/latest/manual/constructors.html#Case-Study:-Rational-1

**Comment by JeffBezanson** [comment]
It would be nice to have a link so you can select a released version or the development version.

**Comment by yuyichao** [comment]
The new doc does have that function. I have no idea if we can link it the other way around/where do people get the link to the out of date RTD link though....

**Comment by dpsanders** [comment]
Googling "julia docs" gives https://docs.julialang.org/
This redirects to the stable version.

**Comment by nalimilan** [comment]
Should we just remove the Read the Docs pages then?

**Comment by StefanKarpinski** [comment]
I made http://julia.readthedocs.io/en/latest/ no longer active, which means it's permission denied. Maybe that's good enough?

**Comment by nalimilan** [comment]
Looks good, thanks!
