### ISSUE TITLE
similar(::Type, ::Int) is defined

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#20873]
Whether on 0.5 or on 0.6, for all types with one field,

```julia
julia> type XX
       a
       end

julia> similar(XX, 10)
XX((10,))
```
because of [this method](https://github.com/JuliaLang/julia/blob/e9c1c3b11775bcaffb2e8f3f934d95f40aa63591/base/abstractarray.jl#L552).

**Comment by KristofferC** [comment]
```
julia> similar(XX, 10)
ERROR: MethodError: no method matching similar(::Type{XX}, ::Int64)
```
