### ISSUE TITLE
Empty parameters error

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#20878]
This is a regression:

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.alpha.34 (2017-03-03 04:10 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit e9c1c3b (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> type Empty end

julia> f(::Empty{}) = 3
ERROR: TypeError: Type{...} expression: expected UnionAll, got Type{Empty}
```

**Comment by yuyichao** [comment]
What do you want?

**Comment by cstjean** [comment]
In 0.5, `Empty{} === Empty`, and that's convenient for writing generic code. Besides, it's inconsistent that 0.6 accepts `type Empty{} end`, but `Empty{}` is an error in other contexts.

**Comment by yuyichao** [comment]
The `Empty{} === Empty` was seen as a bug that's fixed by the change. I don't really see why you want this in generic code since the two behaves very differently anyway. `type Empty{} end` is not applying type parameters and is a declaration so it is allowed. We can certainly make it a syntax error though.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/17943

**Comment by StefanKarpinski** [comment]
There is something elegant about viewing non-parametric types just as parametric types with no type parameters. It would significantly reduce the number of different kinds of things in the language.
