### ISSUE TITLE
color scheme on windows

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#2088]
sometimes on windows I can click n the top bar and reset,
and other times I can't.  (vista for example didn't allow a reset)

Can we just get rid of blue on black as a default, once and for all?

and anyway what was that variable that lets you change it?

**Comment by ViralBShah** [comment]
I just taught a workshop. The windows blue that we use is just not visible. And one person said he was color blind and couldn't see it at all.

I am reopening this for 0.5 even if only to just have a monochrome option.

**Comment by tkelman** [comment]
there are environment variables that can set all the colors. we can do https://github.com/JuliaLang/julia/issues/7267 if we can figure out the issue with BinDeps.

**Comment by ViralBShah** [comment]
Perhaps we should at least pick different colors on Windows for now, to address the immediate issue, and even backport it.

**Comment by KristofferC** [comment]
> I am reopening this for 0.5 even if only to just have a monochrome option.

Doesn't `--color=no` do that?

**Comment by ViralBShah** [comment]
I mean something that does the right thing by default when you double-click.

**Comment by StefanKarpinski** [comment]
Not release blocking.

**Comment by tkelman** [comment]
Right-click on the shortcut, click properties, add `--color=no` to the "Target" setting.

**Comment by KristofferC** [comment]
The blue is now `cyan`.
