### ISSUE TITLE
@inbounds support for setindex!(A, X::AbstractArray, I::AbstractVector)

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#20907]
Would it be possible to add support for `@inbounds` to `setindex!(A::Array, X::AbstractArray, I::AbstractVector{Int})` (see [here](https://github.com/JuliaLang/julia/blob/73e20a36c421788113ed6a31fb4e28e78137927c/base/array.jl#L537)), so that when you know that all indices in `I` are valid for `A`, the `setindex!` calls for each element would skip the bounds check? This came up in [this DataTables PR](https://github.com/JuliaData/DataTables.jl/pull/17#discussion_r104326753).

Is it enough to mark that method with `@propagate_inbounds`, or do we need something more complex?

BTW, it looks like a bounds check could always be avoided for `X[count]`, since `count` depends on the size of `I`, which is checked at the top of the function. I guess that `setindex_shape_check` could also be marked as `@boundscheck`.

Cc: @mbauman

**Comment by mbauman** [comment]
Sure, it looks like `@propagate_inbounds` would do the trick.  But this is very early in bootstrap, so you'd need to use the more rudimentary `@_propagate_inbounds_meta`.  Mucking around this early in bootstrap often leads to surprises — the only reason these methods exist at all is because they're used internally before the general multidimensional machinery comes online.

**Comment by nalimilan** [comment]
Thanks, I've opened https://github.com/JuliaLang/julia/pull/20910.

BTW, is [this call](https://github.com/JuliaLang/julia/blob/73e20a36c421788113ed6a31fb4e28e78137927c/base/multidimensional.jl#L490) to `setindex_shape_check` really needed inside `_unsafe_setindex!`? Looks like this function should only be called with valid indices. Or is the shape of the index vector considered as out of scope for `@inbounds` (in that case I should adapt my PR)?
