### ISSUE TITLE
Loading package hangs on 0.6

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#20909]
Both ScikitLearn and RDatasets can be loaded fine on my system, but the combination of the two freezes (CPU at 0%), and I have to interrupt it. The failure is consistent, but it has changed when I cleared the cache and when I downloaded the latest nightly (i.e. while the code below ran fine, it froze if there was a function call in-between the two `using`). Possibly related: #20908 and #20893

```julia
  | | |_| | | | (_| |  |  Version 0.6.0-pre.alpha.50 (2017-03-05 09:11 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 97c40ed (1 day old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> using ScikitLearn
WARNING: Method definition require(Symbol) in module Base at loading.jl:383 overwritten in module Main at /Users/cedric/.julia/v0.6/Requires/src/require.jl:23.

julia> using RDatasets
^C^CERROR: InterruptException:
Stacktrace:
 [1] yieldto(::Task, ::ANY) at ./event.jl:160
 [2] wait() at ./event.jl:193
 [3] wait(::Condition) at ./event.jl:27
 [4] require(::Symbol) at /Users/cedric/.julia/v0.6/Requires/src/require.jl:25

julia> Pkg.status()
15 required packages:
 - DataFrames                    0.8.5+             anj/06
 - RDatasets                     0.2.0
 - ScikitLearn                   0.2.4+             master
69 additional packages:
 - DataArrays                    0.3.12+            master
 - PyCall                        1.10.0+            master
 - Requires                      0.3.0+             master
 - ScikitLearnBase               0.2.2+             master
```

**Comment by cstjean** [comment]
I've hit this a lot today. Often, the error I get when interrupting mentions `show(lasterr)`:

```julia
^C^C^CERROR: LoadError: ^CSYSTEM: show(lasterr) caused an error
InterruptException()

Stacktrace:
 [1] yieldto(::Task, ::ANY) at ./event.jl:160
 [2] wait() at ./event.jl:193
...
```

I've got three packages A, B, C, with C importing A and B (they also import other stuff). `import C` hangs, but `import A, B, C` doesn't. However, it seems that the system is then in a corrupted state. When I import module X, if X.jl is

```julia
module X
error("ASD")
end
```
then importing X ignores the `error`
```julia
julia> import A, B, C

julia> import X

julia>
```
And importing a non-existent module causes no error, but only a warning
```julia
julia> import ASDASDASD
WARNING: requiring "ASDASDASD" in module "Main" did not define a corresponding module.

```
If X.jl is instead
```julia
module Episodes
using ASDBASDBASD   # non-existent package
end
```
then the `A, B, C, X` import sequence hangs. Finally, if the module content is a syntax error, like `function 123 end`, importing it in the corrupted state yields
```julia
WARNING: requiring "Episodes" in module "Main" did not define a corresponding module.
```

For each of these examples, a fresh Julia was used. Entering the `module ... end` code at the REPL doesn't trigger any of these issues. It's only when `import` is used.

**Comment by cstjean** [comment]
Now that ScikitLearn's dependencies have been tagged, I could [run it on Travis](https://travis-ci.org/cstjean/ScikitLearn.jl/builds/207955696). Both OSX and Linux hang at the same spot as my laptop. When I Ctrl-C, I get the `yieldto` stack trace reported above. If anyone wants to take a look, use `Pkg.checkout("ScikitLearn", "hanging-06")`. Turning the DataFrames dependency from optional (via `Requires.@require`) to a regular import fixed the issue (cc. @MikeInnes).

Requiring DataFrames isn't so bad, so as far as ScikitLearn is concerned, this issue is solved.

**Comment by tkelman** [comment]
Closing as "don't use Requires.jl, it overrides module loading internals and breaks things" unless this can be reduced to use of a supported API that should work but doesn't.
