### ISSUE TITLE
Julia uses Homebrew, which phones home

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#20911]
While installing some Julia packages I saw this message scroll by on my screen:
```
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  http://docs.brew.sh/Analytics.html
```
I assume that means that Homebrew, used by some Julia packages, is collecting usage statistics.

I assume that many people won't have a problem with this and will be happy to help the Homebrew developers. However, I feel uneasy that this is the default setting, and that this isn't communicated more explicitly: Since everything is automated, it is very easy to miss this message. (For example, I've been using Julia since pre-0.4 and never saw this message before.)

**Comment by tkelman** [comment]
Not a base issue.

**Comment by StefanKarpinski** [comment]
What @tkelman is saying is that this issue should be filed with the [Homebrew package](https://github.com/JuliaPackaging/Homebrew.jl).
