### ISSUE TITLE
Impossible to define eltype in certain situations in 0.5.X

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#20926]
This is fixed in 0.6 but not in 0.5.1 and since it was mentioned on the forums there may be future 0.5 bugfix releases, I thought I'd mention this here. The problem is probably easiest explained through code:

```julia
immutable foo{T} end
typealias bar{T} foo{T}
import Base: eltype
eltype{T<:bar}(::Type{T}) = 1
eltype(foo{Float64}())
```

The last call to `eltype` returns `Any` instead of `1` as expected. 

Note both the `typealias` and the parametric type are necessary to trigger the bug. Defining `eltype{T<:foo}(::Type{T})` or even `eltype(::Type{foo})` works fine, as does keeping the `typealias` but having `foo` not be parametric.

**Comment by vtjnash** [comment]
fixed on master, but can't backport. the type system in v0.5 couldn't express this correctly
