### ISSUE TITLE
map(+, 1, (1, 2, 3)) succeeds

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#20930]
... returning `Vector{Int}(2)`. A consequence of `zip`'s truncation behavior and the absence of an argument shape check in the entry point to `map` I imagine? Should this behavior change? Best!

**Comment by dlfivefifty** [comment]
I think this is essentially the same issue: for custom iterators, `map` doesn't check bounds:
```julia
immutable FooIterator end

Base.start(::FooIterator) = 1
Base.next(::FooIterator,st) = st,st+1
Base.done(::FooIterator,st) = st ≥ 3
Base.length(::FooIterator) = 2
Base.eltype(::FooIterator) = Int

map((x,y)->x,[0.,0.,1.],FooIterator())  # succeeds
```

**Comment by martinholters** [comment]
Ref. #20499, especially https://github.com/JuliaLang/julia/issues/20499#issuecomment-293301856.

**Comment by vtjnash** [comment]
Not currently a bug, just how map and zip are currently defined in v1
