### ISSUE TITLE
Upstream Femtolisp changes

### ISSUE THREAD

**Issue by DemiMarie** [JuliaLang/julia#20953]
Julia has its own version of femtolisp, with many patches and improvements.  It would be nice if other users of femtolisp could also benefit.

**Comment by ararslan** [comment]
Hi @DemiMarie. We use the Julia issue tracker for bug reports and feature requests specific to Julia. Since this is more about FemtoLisp, it should be posted to https://github.com/JeffBezanson/femtolisp.

**Comment by StefanKarpinski** [comment]
This might be a good use case for a git submodule and some Julia-specific conditional stuff in the femtolisp repo. However, I kind of suspect that @JeffBezanson is a bit busy to tackle that, so it would probably get done a bit faster if someone is willing to take it on. Not necessarily you, @DemiMarie – I'm just being realistic about time and priorities.

**Comment by tkelman** [comment]
we moved away from submodules for various reasons, but could rearrange the build system to treat flisp in the same way as other external C dependencies if we needed to. the julia parsing code changes much more often than flisp itself.
