### ISSUE TITLE
generated function calls wrong method

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#20955]
```julia
f{T}(::Type{T}) = false
@generated function g{T}(::Type{T}) f(T) end
f(::Type{String}) = true

julia> g(String)
false
```

Only happens on master (e596063), not release-0.5, only when `g` is a generated function, and only when the methods are defined in this order.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/19942
