### ISSUE TITLE
Useless error message

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#20951]
I am using version 0.6.0-pre.alpha.34 (2017-03-03 04:10 UTC)

This thing here works perfectly fine, no crashes

```
function matrix_multiplication(a::Array{Float64, 2}, b::Array{Float64, 2})
  return 5;
end

a = [[1.0 2 3]; [4 5 6]; [7 8 9]; [10 11 12]];
b = [[10.0 20]; [30 40]; [50 60]];
println(matrix_multiplication(a, b));
```

It prints 5 as expected. Now I am trying something more complex

```
function matrix_multiplication(a::Array{Float64, 2}, b::Array{Float64, 2})
  a_height = size(a, 1);
  a_width = size(a, 2);
  b_height = size(b, 1);
  b_width = size(b, 2);
  assert(a_width == b_height);
  result = Array{Float64}(a_height, b_width);
  for height_index = 1:a_height
    for width_index = 1:b_width
      current_sum::Float64 = 0;
      for cross_index = 1:a_width
          tmp_a = a[height_index, cross_index];
          tmp_b = b[ cross_index, width_index];
          current_sum += tmp_a * tmp_b;
        end
      end
      result[height_index, width_index] = current_sum;
      println(current_sum);
    end
  end
  return result;
end

a = [[1.0 2 3]; [4 5 6]; [7 8 9]; [10 11 12]];
b = [[10.0 20]; [30 40]; [50 60]];
println(matrix_multiplication(a, b));
```

As you can see all I did was fill the body of the function with stuff. I did not touch the signature or the caller. But when I try to run this i get:

```
ERROR: LoadError: syntax: type declarations on global variables are not yet supported
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:539
 [2] include(::String) at .\sysimg.jl:14
 [3] process_options(::Base.JLOptions) at .\client.jl:305
 [4] _start() at .\client.jl:371
while loading <snip>, in expression starting on line 1

```
Where is my error? Line 1? Line 1 is the same as in the other example and it worked. And I expect anything that i declare inside the function to be locally scoped. The other lines mentioned arent even part of my code. Which line do you have a problem with julia?

**Comment by timholy** [comment]
Check your indentation in the `cross_index` loop and its corresponding `end`.

Not sure how easy it would be to make the message less confusing, but indeed it's not very helpful now.

**Comment by TotalVerb** [comment]
Here's a smaller repro.

```julia
julia> let
           let
               x::Int = 0
           end
           x
       end
ERROR: syntax: type declarations on global variables are not yet supported
```

**Comment by Jackels** [comment]
Thank you @timholy

**Comment by TotalVerb** [comment]
I guess the behaviour is that any use of a variable in a hard scope (without declaration in that scope) makes it global in that scope, and a variable being global in a hard scope makes it global in all nested scopes. That is indeed confusing behaviour, and while it is sensible after some thought, it probably isn't the default expected behaviour.

**Comment by laborg** [comment]
In the meantime global type declarations are a thing. So the confusing part is replaced with something that isn't useless anymore.
```
julia> let
                  let
                      x::Int = 0
                  end
                  x
              end
ERROR: UndefVarError: `x` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:5
```
