### ISSUE TITLE
Suggestion: Put the path of the executed .jl app at the start of LOAD_PATH

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaLang/julia#20966]
Python puts the  path of the executing .py app at the start of sys.path. What this means is that it is easy to create multi-file Python apps:
```
~/myapp/app.py
~/myapp/Mod.py
```
Here app.py can do
```
import Mod
```
and it will "just work".
But in Julia if you do the equivalent you'll get this error:
```
ERROR: LoadError: ArgumentError: Module Mod not found in current path.
Run `Pkg.add("Mod")` to install the Mod package.
```
which is both annoying and misleading if you have a Mod.jl sitting there!
So, at the moment for my multi-file Julia apps I have to start with this in the app.jl file:
```
LOCAL_PATH = dirname(PROGRAM_FILE)
if LOCAL_PATH == ""
    LOCAL_PATH = "."
end
push!(LOAD_PATH,  abspath(LOCAL_PATH))
```
This seems a bit much just to add the ability to create multi-file apps. Or is there a nicer way that I've missed in the docs?

**Comment by yuyichao** [comment]
In julia `include` is relative so `include("mod.jl")` will also just work.

**Comment by mark-summerfield** [comment]
According to the docs include basically evals the module into existence which (at least in terms of python with which I'm familiar) is dangerous because it reads the module as a string. So it doesn't seem to be the same thing to me as import Mod. However, I'm only starting out with Julia, so maybe it isn't bad style in Julia to include() things rather than import them --- if that's the case maybe the docs should say that very clearly!

**Comment by StefanKarpinski** [comment]
What you're looking for is https://github.com/JuliaLang/julia/issues/4600, which still has some open design questions and didn't quite make it into 0.6 (I did some work on it but opted for adding minimal changes to prepare for Pkg3). But, yes, we do need some mechanism for relative `using`/`import`.

**Comment by StefanKarpinski** [comment]
Putting the path of the current file in LOAD_PATH is not a good idea though. I'm going to close this as a dup of #4600.

**Comment by mark-summerfield** [comment]
OK. Anyway, I've now found that include("Worker.jl") does work without changing the LOAD_PATH; so my error somewhere sorry about that.
