### ISSUE TITLE
remote_do()'s argument order is surprising

### ISSUE THREAD

**Issue by mark-summerfield** [JuliaLang/julia#20972]
remote_do()'s argument order is surprising. I think it should be changed to:
remote_do(pool::AbstractWorkerPool, f, args...; kwargs...)

So calls to it will read:
remote_do(pid, myfunc, myfuncarg1, myfuncarg2, ...)
which seems a lot more natural to me.

**Comment by KristofferC** [comment]
The point is to use the `do` syntax which means that the function should be first.

**Comment by mark-summerfield** [comment]
But even with the do syntax what follows are the actual args not a pid which looks like it is passed as the function's first arg but isn't. I have never seen the pattern: myfunc, argnotpassed, arg1, arg2, ... Surely there's a more natural way (e.g., pool first)? Anyway, I guess it comes down to sensibility so I'll try to get used to it!

**Comment by andreasnoack** [comment]
As mentioned by @KristofferC, this is on purpose. We want to allow the `do` syntax and the arguments to the function have to come last since there can be an arbitrary number of them.
