### ISSUE TITLE
Re-enable the ambiguity test (Base, Core)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#20983]
Once #20982 merges, we should expunge all remaining ambiguities and re-enable the test.

EDIT: This is important for packages, a fair number of which test for ambiguities on 0.5 but have to disable that test on 0.6. A subset of packages that "pass" on 0.6 only do so because they've disabled the test.

**Comment by Sacha0** [comment]
Ref. #20986

**Comment by JeffBezanson** [comment]
This test has been re-enabled.

Although note https://github.com/JuliaLang/julia/issues/21160#issuecomment-289903153 --- we might want to change `detect_ambiguities` to only show methods defined in the specified modules, instead of any methods from functions referenced in the specified modules.
