### ISSUE TITLE
feature request: expose more of cholmod common struct (sparse matrices)

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#20985]
I am currently trying to figure out why my ccall to one of the SuiteSparse routines is not working.  The Cholmod common struct has a number of helpful fields, especially 'status', that could be of assistance. But I can't access these fields because I don't know their offsets.  Currently offsets are computed and stored in the source file deps/SuiteSparse_wrapper.c, but only some of the offsets are computed.  Could this file be extended so that more fields, and 'status' in particular, are exposed?

**Comment by tkelman** [comment]
We might not actually need that file any more with more recent versions of suitesparse that officially support building shared libraries. Can Clang.jl be applied to the headers here?

**Comment by ViralBShah** [comment]
Implemented in #38919
