### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Cody-G** [JuliaLang/julia#20991]
I'm surprised by the difference in iteration performance I see below.  Is this a bug?

```julia
julia> a = 200000000;
julia> ct = 0;
julia> @time for i = 1:200000000
             ct+=1
       end
  5.117046 seconds (200.00 M allocations: 2.980 GB, 3.55% gc time)
julia> ct = 0;
julia> @time for i = 1:a
             ct+=1
       end
 30.753691 seconds (800.00 M allocations: 14.901 GB, 4.86% gc time)
```

version info:
```julia
julia> versioninfo()
Julia Version 0.5.1-pre+55
Commit 8d4ef37* (2017-02-13 09:11 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

**Comment by oscardssmith** [comment]
This seems to only occur when in repl. When in a function this doesn't occur.

`using BenchmarkTools
function test1()
    ct = 0
    for l = 1:200000000
        ct += 1
    end
    ct
end

function test2()
    ct = 0
    n = 200000000
    for l=1:n
        ct += 1
    end
    ct
end

#compile
test1()
test2()

@benchmark test1()
@benchmark test2()`

julia> @benchmark test1()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     2.601 ns (0.00% GC)
  median time:      2.772 ns (0.00% GC)
  mean time:        2.977 ns (0.00% GC)
  maximum time:     23.945 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark test2()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     2.764 ns (0.00% GC)
  median time:      2.780 ns (0.00% GC)
  mean time:        3.040 ns (0.00% GC)
  maximum time:     24.105 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%

**Comment by yuyichao** [comment]
Don't benchmark in global scope

**Comment by Cody-G** [comment]
Okay sure. Just to be clear, is this because the compiler doesn't try to
optimize code executed in the global scope?

**Comment by yuyichao** [comment]
It's because non const global variables cannot be inferred. Please read the performance tip in the manual.

**Comment by StefanKarpinski** [comment]
http://docs.julialang.org/en/stable/manual/performance-tips/
