### ISSUE TITLE
ERROR: LoadError: UndefVarError: require not defined

### ISSUE THREAD

**Issue by G10DRAS** [JuliaLang/julia#21005]
I have installed Julia Version 0.6.0-pre.alpha.100 (2017-03-09 02:03 UTC) on Rasbian Jessie (linux-arm).
but when I tried to run 
`julia> require("../bin/abcxyz.jl")`
it display error 
`ERROR: UndefVarError: require not defined`
What should I do in this case ?

**Comment by KristofferC** [comment]
use `Base.require` since `require` is not exported.

Questions like this are kindly asked to be posted on the forum at https://discourse.julialang.org/ instead of on the issue trackers which is mostly used for bug reports.

**Comment by yuyichao** [comment]
Use `include()` or `import` since `require(::String)` has been deprecated for a long time and is removed.

**Comment by G10DRAS** [comment]
Thanks for info.

I am working on a project which uses `julia `and lots of `.jl` are already present in project.
I am running all this scripts on Raspbian Jessie (linux-arm).

First I tried` julia-0.6.0`, and found that I need to change so many functions (require,  readall , readbytes ...), which I dont want to, as I have not wrote those sripts.

Second, I tried `julia-0.5.1 `I got following error:
`julia: error while loading shared libraries: libLTO.so: cannot open shared object file: No such file or directory`
I saw some thread open for it, but no solution yet.

Now I am not sure what to do next...

**Comment by yuyichao** [comment]
You can use 0.5.0 from https://julialang.s3.amazonaws.com/bin/linux/arm/0.5/julia-0.5.0-linux-arm.tar.gz . Note that you still have to fix those issues on 0.5.

**Comment by G10DRAS** [comment]
Thanks for link.
I dont want to change .jl files, so which version will work with those old functions.

**Comment by G10DRAS** [comment]
Ok julia-0.4.7-linux-arm works for now.
