### ISSUE TITLE
Recursive re-defintions of an anonymous function creates self-reference loop

### ISSUE THREAD

**Issue by JKrehl** [JuliaLang/julia#21039]
When redefining a variable containing an anonymous function with an anonymous function containing the variable itself, that reference is not expanded properly before the new assignment. Therefore, the new function (now bound to the variable) contains a reference to itself and not the old function.

I do think this is erroneous behaviour, since in variable assignment the right side should be expanded fully before being bound to the left, just like `a=a+1` does not produce infinity.

Example
```julia
julia> f = x -> 2*x
(::#1) (generic function with 1 method)

julia> f = x -> 2*f(x)
(::#3) (generic function with 1 method)

julia> f(2)
ERROR: StackOverflowError:
Stacktrace:
 [1] (::##3#4)(::Int64) at ./REPL[2]:1 (repeats 26667 times)

julia> @code_lowered f(2)
CodeInfo(:(begin 
        nothing
        return 2 * (Main.f)(x)
    end))

```

I do not know where this problem stems from and where it should be fixed.
Apologies if this is a duplicate, I haven't found anything resembling this in the open issues.

**Comment by yuyichao** [comment]
This is expected behavior.

**Comment by yuyichao** [comment]
And this is totally different from `a = a + 1` since the variable is evaluated when, well, when it's evaluated which is execution time of the function for code in a function....

**Comment by JKrehl** [comment]
Sorry, I don't get that. Just as the `a` is not taken symbolic, giving a contradictory statement, the function `f` in the definition should be resolved to the underlying anonymous function ##whatever before assignment.

**Comment by yuyichao** [comment]
`a = a + 1` evaluates `a + 1`. `f = x -> 2 * f(x)` evaluates `x -> 2 * f(x)` but not `2 * f(x)` so `a + 1` evaluates `a` but `x->2 * f(x)` does not evaluate `f`.

**Comment by Keno** [comment]
Same behavior as this:
```
julia> n = 1

julia> f(x) = n + 1
f (generic function with 1 method)

julia> f(1)
2

julia> n = 2
2

julia> f(1)
3
``

**Comment by JKrehl** [comment]
Thanks, I can suspect why no introspection into the function body is done at the time of the evaluation of the assignment and without that all symbols in the function body have to be taken, well, symbolic.

**Comment by JeffBezanson** [comment]
You can capture the old value of the function by introducing a new variable, e.g.

```
let oldf = f
    global f = x -> 2*oldf(x)
end
```

**Comment by JKrehl** [comment]
Even this works:
```julia
f = let f=f
    x -> 2*f(x)
end
```
Although `f=f` looks horrible.
