### ISSUE TITLE
while installing JuliaPro,it stoped here and never go on

### ISSUE THREAD

**Issue by Maple-Wang** [JuliaLang/julia#21031]
![default](https://cloud.githubusercontent.com/assets/7234912/23933829/3070e86c-097c-11e7-931f-2123c5ab7f2b.PNG)

**Comment by bmharsha** [comment]
@Maple-Wang This is not an appropriate place to file JuliaPro issues, please consider emailing `JuliaPro@juliacomputing.com` for all JuliaPro specific issues.

**Comment by StefanKarpinski** [comment]
Thanks for reporting and please do email your issue to JuliaPro@juliacomputing.com.
