### ISSUE TITLE
Build failure due to symbol not defined

### ISSUE THREAD

**Issue by abhishek111226** [JuliaLang/julia#21042]
Hi I am building Julia with LLVM, But end up getting following error. Any suggestions?

> Making install in tools
>  /bin/mkdir -p '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/tools'
>   /bin/bash ../libtool   --mode=install /usr/bin/install -c fftw-wisdom '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/tools'
> libtool: install: warning: `../threads/libfftw3_threads.la' has not been installed in `/home/cs15mtech11018/julia_build/julia/usr/lib'
> libtool: install: warning: `../libfftw3.la' has not been installed in `/home/cs15mtech11018/julia_build/julia/usr/lib'
> libtool: install: /usr/bin/install -c .libs/fftw-wisdom /home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/tools/fftw-wisdom
>  /bin/mkdir -p '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/tools'
>  /usr/bin/install -c fftw-wisdom-to-conf '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/tools'
>  /bin/mkdir -p '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/share/man/man1'
>  /usr/bin/install -c -m 644 /home/cs15mtech11018/julia_build/julia/deps/srccache/fftw-3.3.5/tools/fftw-wisdom-to-conf.1 fftw-wisdom.1 '/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double/home/cs15mtech11018/julia_build/julia/usr/share/man/man1'
> Making install in m4
> /home/cs15mtech11018/julia_build/julia/usr/tools/patchelf: relocation error: /home/cs15mtech11018/julia_build/julia/usr/tools/patchelf: symbol _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
> make[1]: *** [/home/cs15mtech11018/julia_build/julia/usr-staging/fftw-3.3.5-double.tgz] Error 127
>

**Comment by yuyichao** [comment]
Do you mean you are building julia with clang? It seems that part of your setup cannot recognize the C++11 ABI of GCC. This is most likely a local setup issue and not a julia issue.
