### ISSUE TITLE
Parsing inconsistency of new `<:` syntax

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#21054]
This works:
```
julia> macro make_f(T)
       esc(:(f(X::Type{<:$T}) = 1))
       end
@make_f (macro with 1 method)

julia> @eval @make_f $Array
f (generic function with 1 method)
```
This doesn't:
```
julia> macro make_f(T)
              quote
                   f(X::Type{<:$T}) = 1
              end
          end
@make_f (macro with 1 method)

julia> @eval @make_f $Array
ERROR: ArgumentError: issubtype: too few arguments (expected 2)
Stacktrace:
 [1] eval(::Module, ::Expr) at ./sysimg.jl:23
```

**Comment by JeffBezanson** [comment]
What happens here is that in the broken case the macroexpander replaces `<:` with `Main.<:`, which is not recognized by lowering.

A related issue is that we parse `A <: B` with expression head `<:`, but `<:A` as a `call`. I'm not sure why, but that might be a mistake.

**Comment by StefanKarpinski** [comment]
I'm not sure allowing `<:` and other subtyping operators as user-definables is desirable.
