### ISSUE TITLE
sparse matrix printing is O(nnz)

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#21063]
The sparse matrix [printing code](https://github.com/JuliaLang/julia/blob/master/base/sparse/sparsematrix.jl#L131-L162) iterates over the entire sparse matrix despite only printing a fixed number of entries. Instead, it should look only at a fixed number of entries from the sparse matrix.

**Comment by andreasnoack** [comment]
Instead of fixing the current version, I'd love to see a Unicode spy plot instead. I think it is much more informative than a few entries.

**Comment by tkelman** [comment]
That's what UnicodePlots.jl is for, and too font-dependent for default behavior.

**Comment by andreasnoack** [comment]
It is true that the functionality is UnicodePlots.jl. I use it a lot and think it would be a great default for printing of sparse matrices.

**Comment by stevengj** [comment]
UnicodePlots seems too complicated to just pull the `spy` function into Base, cool as that would be.  

In any case, it seems like Stefan's issue could be fixed with the addition of 2–3 lines, which seems worth doing.
