### ISSUE TITLE
Update or remove stale code links in devdocs

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#21062]
4 files in devdocs (https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/init.md, https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/eval.md, https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/object.md, and https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/stdio.md) have a links to code or files in `src` that have been reorganized since these pages were written, and could use an update. In particular `alloc.c` no longer exists and is now a dead link.

**Comment by mubaris** [comment]
@tkelman I would like to work on this

**Comment by tkelman** [comment]
go for it. don't need to ask permission, but let us know if you have questions.
