### ISSUE TITLE
Bundle IJulia with Julia binaries

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/julia#21068]
I use Julia for teaching finance, and there's a lot of pain involved in making non-technical people touch a black screen terminal.

Of course there are ways around this, which led me to create a dedicated server (https://github.com/felipenoris/math-server-docker) that is what I actually use for teaching, but students often ask me to install Julia on their jobs, and corporates often use windows and firewalls.

Some Python distributions comes with a binary (or a shell script) that starts Jupyter notebook with just a double click.

I suggest to create a binary distribution with IJulia bundled, and a dedicated icon to open jupyter on a browser.

cc @tkelman

**Comment by tkelman** [comment]
http://juliacomputing.com/products/juliapro.html
