### ISSUE TITLE
eigs and cryptic arpack errors.

### ISSUE THREAD

**Issue by maartenvd** [JuliaLang/julia#21076]
As discussed [here](https://discourse.julialang.org/t/eigs-and-cryptic-arparck-errors/2722) eigs throws an arparck exception when it doesn't converge within maxiter. (example : eigs(randn(500,500),nev=1,maxiter=1))

It would be helpful to get a more specific exception or preferably return the partially converged eigenvectors with an error bound instead.

This also happens when the matrix contains an Inf or Nan, both can really be captured in some kind of sanitation step.

**Comment by ViralBShah** [comment]
Closing in favour of #24292
