### ISSUE TITLE
serving website and docs over HTTPS

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/julia#21078]
https://docs.julialang.org/en/stable/ returns `NET::ERR_CERT_COMMON_NAME_INVALID` on chrome

this is because ssl token is invalid/outdated

**Comment by sbromberger** [comment]
It's a hostname mismatch according to Safari:

<img width="578" alt="screen shot 2017-03-18 at 00 16 29" src="https://cloud.githubusercontent.com/assets/941359/24069890/2d006be4-0b70-11e7-89e5-69a8df7240be.png">

**Comment by tkelman** [comment]
did this ever work over https, or is this just https://github.com/isaacs/github/issues/156 ?

**Comment by ViralBShah** [comment]
This probably worked when we used to use readthedocs.org. Now the docs are hosted on github pages, making this the same issue as above.

**Comment by ViralBShah** [comment]
closing as dup of isaacs/github#156

**Comment by ViralBShah** [comment]
Non-ssl works.

**Comment by StefanKarpinski** [comment]
I'm going to reopen this as a thing we need to fix, rather than waiting for GitHub to provide a solution. I believe @staticfloat is looking into options.

**Comment by sbromberger** [comment]
Just FYI, we have the same sort of layout at JuliaGraphs (https://juliagraphs.github.io/) and aren't seeing the certificate errors.

**Comment by sbromberger** [comment]
(This also affects https://www.julialang.org, btw.)

**Comment by yuyichao** [comment]
It only affects custom domain.

**Comment by StefanKarpinski** [comment]
Which is what we use.

**Comment by TotalVerb** [comment]
An easy way to "fix" this is to use CloudFlare, which will allow replacing the GitHub certificate with its own.

**Comment by staticfloat** [comment]
We've now got things setup through [Fastly](https://www.fastly.com/), so https://julialang.org should now work, modulo DNS caching.

**Comment by djsegal** [comment]
Wasn't this always about https://docs.julialang.org not working?

**Comment by staticfloat** [comment]
Docs is also an objective, we'll get to work on that in the near future.

**Comment by StefanKarpinski** [comment]
> Wasn't this always about https://docs.julialang.org not working?

I broadened the scope because they're fundamentally the same issue. Might as well start with the main webpage.

**Comment by djsegal** [comment]
My bad. Didn't edit my answer. That makes a lot of sense. Thanks for working on it

**Comment by staticfloat** [comment]
I'm happy to report that this issue is now completely resolved, pending DNS propagation.

**Comment by djsegal** [comment]
Sorry to reopen this, but I found out pkg.julialang.org is not covered by this yet.

-----------------

How I found out:

+ Got the following error when trying to load a badge on my website:

```
QuantumOptics:1 Mixed Content: The page at 'https://juliaobserver.com/packages/QuantumOptics' was loaded over HTTPS, but requested an insecure image 'http://pkg.julialang.org/badges/QuantumOptics_0.4.svg'. This content should also be served over HTTPS.
```

+ Decided to try to regex swap out `http` and `https`:

https://pkg.julialang.org/badges/QuantumOptics_0.4.svg

+ Then got the following error (after navigating through Chrome:

```
Attackers might be trying to steal your information from pkg.julialang.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID
```

**Comment by tkelman** [comment]
guess that needs to be addressed at https://github.com/JuliaCI/pkg.julialang.org, but not sure how

**Comment by staticfloat** [comment]
This is a good point.  Looks like it's being served through GitHub, so we can do the same fastly trick as with docs.julialang.org.  I'll get on this today.

**Comment by staticfloat** [comment]
Alright, it's setup, we just need to get DNS switched over and wait for it to propagate.  In the meantime, you can test by setting `151.101.2.49 pkg.julialang.org` in your `/etc/hosts` file.

**Comment by staticfloat** [comment]
DNS has been switched over, we're just waiting for it to propagate now.
