### ISSUE TITLE
Strange SSL error while installing Plots.jl

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#21084]
While installing Plots.jl, and only Plots.jl, I see the following error on a Raspberry Pi:
```
Cannot clone Plots from https://github.com/JuliaPlots/Plots.jl.git. SSL error: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
```

This looks like an openssl bug. I am building a custom Julia to use as many system libs as I can :
```
USE_SYSTEM_LLVM:=1
LLVM_CONFIG:=llvm-config-3.9

USE_SYSTEM_BLAS:=1
LIBBLAS:=-lblas
LIBBLASNAME:=libblas
USE_SYSTEM_LAPACK:=1
USE_SYSTEM_LIBM:=1
USE_SYSTEM_FFTW:=1
USE_SYSTEM_GMP:=1
USE_SYSTEM_MPFR:=1
USE_SYSTEM_ARPACK:=1
USE_SYSTEM_OPENSPECFUN:=1
USE_SYSTEM_LIBSSH2:=1
USE_SYSTEM_CURL:=1
USE_SYSTEM_SUITESPARSE:=1
```

```             _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  arm-linux-gnueabihf

```

**Comment by ViralBShah** [comment]
Is there a workaround?

**Comment by tkelman** [comment]
Use mbedtls.

**Comment by ViralBShah** [comment]
Does our build not automatically pick up mbedtls on all platforms? I can never quite remember what happens where.

**Comment by tkelman** [comment]
depends what system libraries you're using. try not using system curl or libssh? or using openssl instead of mbedtls? run ldd on the built libs to see what they're linked against

**Comment by nalimilan** [comment]
Cf. https://github.com/JuliaLang/julia/issues/20860. May not be related, but my attempts there can give you inspiration regarding the variables to set.

**Comment by ViralBShah** [comment]
Closing in favour of #20860.
