### ISSUE TITLE
`@test @throws` instead of `@test_throws`

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#21098]
I recently had a case where some `@test_throws` were broken. Unfortunately, `@test_broken` cannot be composed with `@test_throws`.

I suggest to deprecate `@test_throws Ex expr` in favor of `@test @throws Ex expr` so that `@test_broken @throws Ex expr` can be used. This is similar to the existing `@test @inferred foo(x)` idiom.

**Comment by timholy** [comment]
Workaround: use `@test_skip(@test_broken ...)`.

**Comment by kunzaatko** [comment]
@vtjnash Why is this closed? Is it possible to declare a `@test_throws` as broken? I do not see any resolution to the issue that is mentioned in the issue statement...
Is there any discussion where it was decided that this is a non-feature?
