### ISSUE TITLE
Nesting multiplications harder on inference than nesting muladds?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#21090]
The code in [the gist](https://gist.github.com/KristofferC/61de1b92cc7365e59339901a89b8145e) uses dual numbers to compute hessian for tensors. The code is a bit contrived so just consider it a stress test for inference.
Two versions of the function `dcontract` is provided, `dcontract_mul` and `dcontract_muladd`. The only difference between them is whether the reductions are using nested multiplications `(((a * b) + c * d) + e * f + ...)` or nested muladds `muladd(a, b, muladd(c, d, muladd(e, f, ...)))))`.

These two reduction methods have very different impact on compilation time. `include`-ing the file above and running the muladd version gives:

```
julia> @time hessian(norm_muladd, v)
  0.939294 seconds (1.27 M allocations: 45.058 MiB, 1.04% gc time)
```

while running (with restarting julia) the nested multiplication version gives:

```
julia> @time hessian(norm_mul, v)
  9.351645 seconds (25.03 M allocations: 719.054 MiB, 0.91% gc time)
```

I am surprised the two versions are so different in terms of inference time.

**Comment by yuyichao** [comment]
FWIW, the `*+` version has many more function calls.

**Comment by KristofferC** [comment]
I think @yuyichao comment is the simple answer.
