### ISSUE TITLE
`generated function body is not pure` when using dot notation

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#21094]
I have a generated function in which I rely on Julia's new dot notation for "vectorised" operations on arrays. This results in an error shown below. The minimal working example is

````julia
versioninfo()

@generated function foo(out, x)
    quote
        out .= x .+ x
    end
end

foo([0.0], [1.0])
````

The output is
````
Julia Version 0.6.0-pre.alpha.146
Commit c399558* (2017-03-15 15:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
ERROR: LoadError: generated function body is not pure. this likely means it contains a closure or comprehension.
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
while loading /Users/davide/Codes/IMEXRK.jl/src/deleteme.jl, in expression starting on line 10
[Finished in 2.1s with exit code 1]
[cmd: ['/Users/davide/Software/julia-0.6/usr/bin/julia', '/Users/davide/Codes/IMEXRK.jl/src/deleteme.jl']]
[dir: /Users/davide/Codes/IMEXRK.jl/src]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
````

The only reference I could find similar to what I get is #19299. This issue seems different to me tough.

**Comment by yuyichao** [comment]
This is the same issue. The broadcast syntax generates anonymous function. I think we should remove this limitation at some point but for now this should be closed as a dup.

**Comment by gasagna** [comment]
Since #19299 was marked as a won't fix, I reckon it will never be possible to use the dot syntax in generated functions, which is a pity as the syntax is extremely convenient. Can that issue be reopened or reconsidered to keep track of this?

**Comment by gasagna** [comment]
Is there a time scale for this issue to be somehow solved, 0.7, 1.0?  I find the dot broadcast notation very useful to express complex arithmetic operations on generic types, with in place operations. This issue however prevents me from using it in generated functions. 

Any thoughts on how one would rewrite the original MWE with something that can be currently implemented? Thanks

**Comment by yuyichao** [comment]
Move the expression to a normal function.

**Comment by gasagna** [comment]
Not the best of the solutions as I need to abandon the generated function.

**Comment by yuyichao** [comment]
You don't. Just put that part in the normal function and call that function in the generated function.

**Comment by gasagna** [comment]
I have several expressions that would use the dot notation in my generated function. Moving all of those in different functions is not feasible, and not very transparent. 

I have somehow solved my issue by creating a macro `@over_i` that generate a loop so that the example in the original post becomes:

```julia
@generated function foo(out::T, x::T)
    quote
       @over_i out[i] = x[i] + x[i]
    end
end
``` 

and type `T` needs to implement a basic indexing behaviour.

**Comment by marius311** [comment]
@gasagna your solution is arguably already more readable, but if you really wanted to keep the loop fusion but not move the function definition in another place, you can always do stuff like,

```julia
@generated function foo(out, x)
    quote
        $((out,x)->(out .= x .+ x))(out,x)
    end
end
```

**Comment by gasagna** [comment]
Thanks @marius311 but I hope #23692 will land for v0.7!
