### ISSUE TITLE
big_str macro doesn't support underscores

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#21092]
```julia
julia> big"99_999_999_999" * 999_999_999_999
ERROR: ArgumentError: invalid number format 99_999_999_999 for BigInt or BigFloat
```

Tested on version `0.6.0-pre.alpha.182`.

**Comment by fcard** [comment]
```julia
julia> parse(BigInt, "1_000")
ERROR: ArgumentError: invalid BigInt: "1_000"
Stacktrace:
 [1] tryparse_internal(::Type{BigInt}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./gmp.jl:104
 [2] parse(::Type{BigInt}, ::String) at ./parse.jl:184
```
Hmm... `parse(Int, "1_000")` and co fail as well. Is that considered an issue? If so I guess fixing that would fix this as well.

**Comment by StefanKarpinski** [comment]
It seems sane that the `big"..."` macro should accept any valid Julia number syntax. For parsing numbers from external sources, the arguments for accepting so many different syntaxes is far weaker, although it could certainly be more configurable.

**Comment by fcard** [comment]
That seems alright. `parse("1_000")` works but I always felt the `parse(T, str)` and `parse(str)` to be almost completely different functions.

I guess `@big_str` can just strip `_` out of the input with `replace` or something before sending it to `parse`. (maybe checking that the first char isn't `'_'` so `_100` doesn't parse as a valid number)

---

Also for the record I was already orchestrating a [three layered solution to the float part of this by mimicking C11's `_Generic` with a macro expanding to a generated function just so I could simplify the tryparse functions with a common preamble](https://gist.github.com/fcard/8a2ad09318b90eeb2e82ecff435ace43), but that was just silly fun. KISS beats DRY as I've been learning.

**Comment by yuyichao** [comment]
> I always felt parse(T, str) and parse(str) to be almost completely different functions.

That is indeed correct. One (`parse(T, str)`) is to parse data in a given format/type and the other `parse(str)` is parsing julia code.
