### ISSUE TITLE
Add option to round by significant figures? i.e. round(x,n;significant=false)

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#21101]
It would be helpful to have the option to be able to round by significant figures, as opposed to decimal places.

While this can be done with `@sprintf("%.3g", pi)` I have found it elegant to work with rounded numerical values.

Perhaps `round(x,n;significant=false)` such that:
```
julia> round(pi,3,significant=true)
3.14
julia> round(pi/10,3,significant=true)
0.314
julia> round(pi,3)
3.142
julia> round(pi,3)
0.314
```

**Comment by stevengj** [comment]
This functionality seems useful, but I'm not sure about the naming.  Do other languages have such a feature?

It seems [missing from Python](http://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python) and [C#](http://stackoverflow.com/questions/374316/round-a-double-to-x-significant-figures) and Fortran.  R calls the function [signif](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Round.html).  Someone wrote a Matlab function called [roundsd](https://www.mathworks.com/matlabcentral/fileexchange/26212-round-with-significant-digits) for this, and someone else wrote [sd_round](https://www.mathworks.com/matlabcentral/fileexchange/21225-round-to-a-specified-number-of-significant-digits).

**Comment by JeffBezanson** [comment]
It seems better to me to use a different name instead of a keyword argument.

**Comment by StefanKarpinski** [comment]
It would make more sense to me to have two orthogonal keyword options. I.e. the signature would look like `round(x, trailing=t, significant=s)` which would round `x` to no more than `t` trailing digits and no more than `s` significant digits. The number of trailing digits defaults to zero while the number of significant digits defaults to infinite (or something effectively equivalent).

**Comment by StefanKarpinski** [comment]
This is actually also a fairly sensible interface to generic printing function for floating-point values, which could be part of the long-awaited printf rewrite.

**Comment by simonbyrne** [comment]
We already have a [`signif`](https://docs.julialang.org/en/stable/stdlib/math/#Base.signif) function. We should add a cross reference from the `round` docs though, as this has come up again.

**Comment by simonbyrne** [comment]
@StefanKarpinski Can we close this now, or should we keep it open to track your suggestion above?

**Comment by StefanKarpinski** [comment]
Eh, don't really mind either way.

**Comment by simonbyrne** [comment]
The printing thing is probably a separate issue.

**Comment by mforets** [comment]
For reference, now [Base.round](https://docs.julialang.org/en/v1/base/math/#Base.round-Tuple{Type,Any}) accepts the `sigdigits` keyword:

```julia
julia> round(pi, digits=3)
3.142

julia> round(pi, sigdigits=3)
3.14
```
