### ISSUE TITLE
Large performance regression with skipchars on small/medium inputs

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#21109]
Julia 0.5:
```
julia> mktemp() do _, file
                println(file, "G")
                flush(file)
                seek(file, 0)
                skipchars(file, islower)
                @time for i in 1:1000000; skipchars(file, islower) end
              end
  0.016611 seconds
```
Julia 0.6 (`alpha.182`):
```
julia> mktemp() do _, file
                       println(file, "G")
                       flush(file)
                       seek(file, 0)
                       skipchars(file, islower)
                       @time for i in 1:1000000; skipchars(file, islower) end
                     end
  0.951664 seconds (1000.00 k allocations: 30.518 MiB, 0.33% gc time)
```

Booo! [Whoever](https://www.github.com/fcard) introduced this sucks!

Just so people won't forget about it. This problem happens until there are about 40/50 characters to be skipped with an inexpensive predicate. (`islower`, `isspace`, etc)

I've got a first draft of a fix [>>here<<](https://github.com/fcard/julia/pull/8) (code under MIT license, etc etc), but I am not willing to make a PR at the moment.

**Comment by nalimilan** [comment]
What do you mean by "not willing"? Do you need some time, or do you need somebody else to fix this?

**Comment by fcard** [comment]
Ideally someone else will fix this, with my code or otherwise. In one or two weeks I will have a clear enough mind to submit a PR if nobody else wants to, but then this "clear mind" isn't going to last forever so I will need to establish some time limit (1, 2 months? Last time I managed 6 but...) before giving a ultimatum of "help me merge this soon or reject it", and if nobody responds I will just close the PR and postpone it for when I am ready again, if the maintainers are willing.

This whole thing sounds awfully stressful for both me and the maintainers, so again, ideally someone else will handle this. I really love to (try to) help but honestly the way my brain works just isn't compatible with large repos full of busy people. Hopefully I will eventually overcome this completely but for now that's how it's gonna be.

**Comment by fcard** [comment]
I was convinced to give a PR a go, because the solution turned out to be really simple. There it is: #21117

Now instead of a ~50x overhead we have a 2x one that only applies to the noop case where there are no characters to skip, then disappears fairly quickly as the skippable characters increase and the function becomes faster than the old one.

I don't know if that fixes this issue as there still would be a little bit of a regression, but at least I would have a excuse to change this stupid title.
