### ISSUE TITLE
Macro to check "Flow" Memory Usage

### ISSUE THREAD

**Issue by mes9** [JuliaLang/julia#21114]
The `@time` and `@allocated` macro give the total allocated memory. However, the computational constraints generally aren't on the total allocated memory, but instead on the RAM.

If I have a function `f()` which uses 1 GB RAM, then if I do something like
`@time (for i=1:100; f(); end)`
It will tell me that I allocated 100 GB, yet the largest "flow" memory usage in this case is only 1GB.

To get the flow memory I could do `@time f()` if `f()` is a simple function. If `f()` is complicated with many loops and iterations, it may be that the actual RAM usage is very small but the total allocated memory is big. 
Is there any easy way to discover the total flow utility a function uses? I could dig deep into that function and use the `@time` macro within every iteration to see how much RAM is begin used, but that can be tedious depending on the function. It seems like analyzing the system memory usage (via Task Manager or something similar) would give the flow utility, but that can't necessarily pin down the function's contribution to memory.

**Comment by yuyichao** [comment]
That concept basically does not exist with a GC.

**Comment by StefanKarpinski** [comment]
Well, the concept still exists, but it's equivalent to asking: what is the maximum memory this code would require if we were using reference counting? Which one cannot determine without switching to reference counting, which we're not going to do just to answer this question.
