### ISSUE TITLE
Bug in BLAS.ger! and BLAS.trsv! handling of SubArrays.

### ISSUE THREAD

**Issue by willtebbutt** [JuliaLang/julia#21122]
There appears to be a bug here:
https://github.com/JuliaLang/julia/blob/master/base/linalg/blas.jl#L927

The stride of the vectors `x` and `y` is assumed to be one, however, it is possible for this not to be the case. The code snippet below reproduces the bug by setting `y` to be a view into a matrix such that the stride > 1.

```
N = 5
Nb = 100
data = randn(Nb, Nb)

# Set up views into A. Note that the stride of y is greater than 1.
y = view(data, 1, 1:N)
x = view(data, 2:N+1, 1)
A = randn(N, N)

# Evaluate using Julia.
B_right = A - x * y'
B_wrong = BLAS.ger!(-1.0, x, y, copy(A))
println("Max difference between B_right and B_wrong is ", maximum(abs(B_right - B_wrong)))
```
Were this bug not present, the max difference should be `0`. A work around demonstrating that the bug is due to the stride of the vector is to just copy `y` into a new array such that the stride is actually `1`:
```
# Work around by re-allocating memory for y to make the stride=1 assumption hold.
ŷ = copy(y) # ŷ is an Array and therefore stride(ŷ, 1) = 1.
B_ger_right = BLAS.ger!(-1.0, x, ŷ, copy(A))
println("Max difference between B_right and B_ger_right is ", maximum(abs(B_right - B_ger_right)))
```

My guess is that the fix is simply to change the hard-coded `&1`s for `&stride(x, 1)` and `&stride(y, 1)` respectively.

`ctrl-f`-ing through blas.jl shows that there is exactly one other incidence of hard coded stride=1, in `trsv!` at https://github.com/JuliaLang/julia/blob/master/base/linalg/blas.jl#L894. An analogous bug can be generated and worked around as follows:
```
# Produce bug for trsv!
y = view(data, 2, 1:N) # Construct vector with stride > 1.
A = randn(N, N)
U = chol(A'A + UniformScaling(1e-2)) # Get invertible triangular matrix.

# Backsolve with BLAS functionality and Julia functionality.
x_julia = U \ y
println(maximum(abs(U * x_julia - y))) # Should be close to zero, is close to zero.
y_cp = copy(y)
x_blas = BLAS.trsv!('U', 'N', 'N', U.data, y)
println(maximum(abs(U * x_blas - y_cp))) # Should be close to zero, is not close to zero.
y_cp_2 = copy(y_cp)
x_blas_correct = BLAS.trsv!('U', 'N', 'N', U.data, y_cp_2)
println(maximum(abs(U * x_blas_correct - y_cp))) # Should be close to zero, is close to zero.
```
I would imagine the fix would be similar.

My versioninfo() is
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

Thanks,
Will

**Comment by andreasnoack** [comment]
Yes. That is wrong. See #21125.
