### ISSUE TITLE
mapslices for sparse matrices is wrong

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#21123]
E.g.
```julia
julia> mapslices(nnz, speye(3), 1)
1×3 Array{Int64,2}:
 1  2  3
```
The problem seems to be https://github.com/JuliaLang/julia/blob/90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1/base/abstractarray.jl#L1830 which  doesn't set structural zeros in the `slice` variable, e.g.
```julia
julia> Base._unsafe_getindex!(sparse(ones(3)), speye(3), 1:3, 1)
3-element SparseVector{Float64,Int64} with 3 stored entries:
  [1]  =  1.0
  [2]  =  0.0
  [3]  =  0.0
```
I don't know the behavior of `_unsafe_getindex!` should change or if `mapslices` should use a different function. I'm on
```julia
julia> versioninfo()
Julia Version 0.6.0-pre.alpha.180
Commit a365da4c6c* (2017-03-19 13:41 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

cc: @mbauman, @timholy

**Comment by mbauman** [comment]
It's not so much `_unsafe_getindex!` as it is sparse setindex.  `s[1]=0` doesn't set a structural zero.

We just need to be more strict in the determination of slices that are deemed [`safe_for_reuse`](https://github.com/JuliaLang/julia/blob/90cfb8292c5d8cdd25eb4b4653c03f6d382b42b1/base/abstractarray.jl#L1795)?  Not sure what the exact criterion should be here.
