### ISSUE TITLE
No implizit conversion of default arguments

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#21128]
I had this problem today

```
function stupid(foo::Array{Float64, 1}, index::UInt64 = 1)
end

stupid([1.0])
```

This is something that should run, but when you try it gives you a very confusing error.
```
ERROR: LoadError: MethodError: no method matching stupid(::Array{Float64,1}, ::Int64)
Closest candidates are:
  stupid(::Array{Float64,1}, !Matched::UInt64) at ~\julia-experiments\definitions.jl:2
  stupid(::Array{Float64,1}) at C:\Users\bossert\julia-experiments\definitions.jl:2
 in stupid(::Array{Float64,1}) at C:\Users\bossert\julia-experiments\definitions.jl:2
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:265
 in _start() at .\client.jl:321
```
This is telling me nothing useful or comprehensible. It does not find a method that matches, but the first candidate it finds matches everything? What does the '!' mean before Matched?

After toying around in frustration i found the solution to my problem

```
function stupid(foo::Array{Float64, 1}, index::UInt64 = UInt64(1))
end

stupid([1.0])
```
Next time please either tell me that my signature makes no sense ( which is btw. not on line 2 but on line 1 ) or do the conversion yourself.

**Comment by KristofferC** [comment]
`!Matched` means not matched. If you have a terminal that supports color this is showed in red.

**Comment by StefanKarpinski** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7357
