### ISSUE TITLE
UndefVarError: * not defined

### ISSUE THREAD

**Issue by fedorfro** [JuliaLang/julia#21139]
I simply try to multiply 2 by 2:
2*2
and it shows an error - UndefVarError: * not defined

Could you help me?

**Comment by ararslan** [comment]
Hi @fedorfro. It would be great if you could include your Julia version and more details about this. For example, if you open a new REPL session and type `2*2`, do you get the same error?

**Comment by fedorfro** [comment]
Thx, It works now after I restarted a kernel. Sorry for stupid question)
