### ISSUE TITLE
UndefVarError with both kwargs and type parameter chaining

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#21147]
On the latest master, I get,

```julia
julia> function foo(f::Tuple{A}; kwargs...) where {B,A<:Tuple{B}} end
ERROR: UndefVarError: B not defined
```

Getting rid of the kwargs fixes it, as does not doing parameter chaining; also, its not specific to Tuple, any other parametric type fails. Bug perhaps? (sorry if this is known or even not a bug, I couldn't find anything else searching)

**Comment by marius311** [comment]
Ahh and sorry I think there's a variant of this same thing that I missed originally that seems to still be an issue though, basically same thing but with optional positional args (checking now on 43fb9f0):

```julia
julia> function foo(f::Tuple{A}, g=1) where {B,A<:Tuple{B}} end
ERROR: UndefVarError: B not defined
```

**Comment by JeffBezanson** [comment]
Thanks. Fixed.
