### ISSUE TITLE
julia.exe won't start on Windows 7 64-bit, Windows 2008 after upgrade to 0.5.1

### ISSUE THREAD

**Issue by vh-d** [JuliaLang/julia#21149]
After I upgraded to julia 0.5.1 (from 0.5) julia.exe wont start REPL. The program silently ends without logo or errors messages. I can only get help (-h) and version (-v) printed. Only julia-debug.exe seems to run alright. 

Julia 0.6 nightly build does not start either.

**Comment by tkelman** [comment]
Do you get any messages if you run julia.exe from a command prompt instead of by double-clicking?

**Comment by vh-d** [comment]
No, just an empty line and then back to command line. 
Also `julia -E "1+1"` prints nothing.

Only --help and --version switches work.

**Comment by KristofferC** [comment]
Can you try `julia --startup-file=no`?

**Comment by tkelman** [comment]
Do you have anything strange in juliarc or on your path? Can you try running in a debugger (gdb, lldb, windbg, whatever) and see if that can give any more information?

What does `versioninfo(true)` from julia-debug say?

**Comment by tkelman** [comment]
`--precompiled=no` is also worth trying. and checking the difference in what julia.exe, libjulia.dll, and sys.dll link to in release vs debug versions using dependency walker or similar (I can look at this next time I have a windows build in front of me)

**Comment by vh-d** [comment]
```
julia> versioninfo(true)
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
DEBUG build
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
  WORD_SIZE: 64
           Microsoft Windows [Verze 6.1.7601]
Memory: 15.999523162841797 GB (5583.546875 MB free)
Uptime: 462904.6620759 sec
Load Avg:  0.0  0.0  0.0
Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz:
       speed         user       nice        sys       idle        irq ticks
#1  2500 MHz   44170731          0   20016425  398702847     406897 ticks
#2  2500 MHz   29458168          0   14903883  418527860     352031 ticks
#3  2500 MHz   25707888          0   14075143  423106754     209587 ticks
#4  2500 MHz   25871549          0   13977720  423040391     179557 ticks

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, westmere)
Environment:
  HOMEDRIVE = J:
  HOMEPATH = \
...
  JULIA_HOME = E:\julia\bin
  JULIA_PKGDIR = E:\VH\JULIA_LIB
  PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
...

Package Directory: E:\VH\JULIA_LIB\v0.5
11 required packages:
 - Conda                         0.5.2
 - IJulia                        1.4.1
...
```

**Comment by vh-d** [comment]
I don't think I have any juliarc and/so `julia --startup-file=no` does not help.

The only thing that might make the system different is that it's virtual machine with very limited permissions (usual corporate evironment). The Windows 7 is physical machine with similar priviledges.

**Comment by vh-d** [comment]
There are no debuggers on those machines but I will try to get my hands on some other/personal windows machines and test it.

**Comment by tkelman** [comment]
Does unsetting the `JULIA_HOME` environment variable help?

**Comment by vh-d** [comment]
Neither `--precompiled=no` nor unsetting the `JULIA_HOME` variable helps.

**Comment by vh-d** [comment]
Running in gdb:
```
GNU gdb (GDB) 7.3.50.20111208-cvs
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from E:\julia\bin/julia.exe...done.
(gdb) run
Starting program: E:\julia\bin/julia.exe
[New Thread 2956.0x1154]
warning: [4436] [SetupHookConfiguration] Performing Hook Feature Checks.

warning: [4436] [CDetourHelpers::CachedGetCurrentAppName] ProcessName[\Device\HarddiskVolume2\julia\
bin\julia.exe]

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [PipeComms::Do_Connection] [4436]PipeComms: Access - [c0000000] [\\.\pipe\appsense_C
onfigPipe_D3EA4760-A0CC-4d00-AA80-B0D747311668].

warning: [4436] [PipeComms::Do_SendMessage] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-
A0CC-4d00-AA80-B0D747311668] SendMessage result = [1] [0].

warning: [4436] [PipeComms::Do_ReceiveMessage] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA47
60-A0CC-4d00-AA80-B0D747311668] ReceiveMessage result = [1] [0].

warning: [4436] [SetupHookConfiguration] Features for [julia.exe], NET = [1], URM = [0]: PDM = [0].

warning: [4436] [SetupHookConfiguration] Other options for [julia.exe], hijack detect = [0], PauseCo
nsoleExit = [0], MSIHooking = [0].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-A0CC
-4d00-AA80-B0D747311668] Disconnecting [00000000000000F8].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-A0CC
-4d00-AA80-B0D747311668] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [CDetourWinSock::Load] Attempt to get exported GetAddrInfoExW and GetAddrInfoW funct
ion addresses on Vista+ OS's.

warning: [4436] [CDetourWinSock::Load] Got address of exported GetAddrInfoExW function.

warning: [4436] [CDetourWinSock::Load] Got address of exported GetAddrInfoW function.

warning: [4436] [CDetourWinSock::Load] Got address of exported WSASend function.

warning: [4436] [APCFuncInstallHook] AMAppHook::Install Result [0]

[New Thread 2956.0x3954]
[New Thread 2956.0x34cc]
warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [PipeComms::Do_Connection] [4436]PipeComms: Access - [c0000000] [\\.\pipe\appsense_C
onfigPipe_D3EA4760-A0CC-4d00-AA80-B0D747311668].

warning: [4436] [CAgentConfigCheck::CheckAgentActiveAndUpdateConfigVersion] Setting agent Active to
TRUE.

warning: [4436] [PipeComms::Do_SendMessage] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-
A0CC-4d00-AA80-B0D747311668] SendMessage result = [1] [0].

warning: [4436] [PipeComms::Do_ReceiveMessage] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA47
60-A0CC-4d00-AA80-B0D747311668] ReceiveMessage result = [1] [0].

warning: [4436] [CAgentConfigCheck::CheckAgentActiveAndUpdateConfigVersion] Config Version is Curren
tly [1]

warning: [4436] [CAgentConfigCheck::CheckAgentActiveAndUpdateConfigVersion] ConfigData is invalid!

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-A0CC
-4d00-AA80-B0D747311668] Disconnecting [00000000000001E4].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [\\.\pipe\appsense_ConfigPipe_D3EA4760-A0CC
-4d00-AA80-B0D747311668] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [CDetourWinSock::DebugStart_socket] Begin Detoured_socket.

warning: [4436] [CDetourWinSock::DebugStart_socket] af = [2] type = [1] protocol = [0].

warning: [4436] [CAgentConfigCheck::InitObjects] Init Objects Start.

warning: [4436] [CAgentConfigCheck::InitConfigurationTracker] ConfigData = [00000000001500A0]

warning: [4436] [CAgentConfigCheck::InitObjects] Init Objects Complete.

warning: [4436] [CDetourCommon::InitObjects] Init Objects Start.

warning: [4436] [CDetourCommon::InitHookManager] About to init hook manager

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [PipeComms::Disconnect] [4436]PipeComms: [] Disconnecting [FFFFFFFFFFFFFFFF].

warning: [4436] [CDetourCommon::InitObjects] Init Objects Complete.

warning: [4436] [CDetourWinSock::DebugEnd_socket] Blocked = [0].

warning: [4436] [CDetourWinSock::DebugEnd_socket] sckt = [488].

warning: [4436] [CDetourWinSock::DebugEnd_socket] End Detoured_socket.

warning: [4436] [CDetourWinSock::DebugStart_closesocket] Begin Detoured_closesocket [1e8].

warning: [4436] [CDetourWinSock::DebugStart_socket] Begin Detoured_socket.

warning: [4436] [CDetourWinSock::DebugStart_socket] af = [23] type = [1] protocol = [0].

warning: [4436] [CDetourWinSock::DebugEnd_socket] Blocked = [0].

warning: [4436] [CDetourWinSock::DebugEnd_socket] sckt = [488].

warning: [4436] [CDetourWinSock::DebugEnd_socket] End Detoured_socket.

warning: [4436] [CDetourWinSock::DebugStart_closesocket] Begin Detoured_closesocket [1e8].


Program received signal SIGSEGV, Segmentation fault.
jl_deserialize_value_ ()
    at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/dump.c:1750
1750    /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/dump.c: No such file or dire
ctory.
(gdb)
```

**Comment by tkelman** [comment]
lots of warnings from something that might be called appsense? not sure if related.

so what was being deserialized that caused the segfault that wouldn't be an issue with julia-debug... anyone have any ideas?

**Comment by vh-d** [comment]
Sorry, I forgot to say that those warnings show up when debugging julia-debug.exe too. The segfault does not of course.

**Comment by tkelman** [comment]
And you say this doesn't happen with 0.5.0? Given how this hasn't yet been reproduced anywhere but your system, could you try installing cygwin (https://github.com/JuliaLang/julia/blob/master/README.windows.md#cygwin-to-mingw-cross-compiling), building the release-0.5 branch from source and seeing if it's possible to bisect to find the commit that broke this?

**Comment by vh-d** [comment]
I installed Cygwin + dependencies and tried to bisect the bug between v0.5.0 and v0.5.1. I run into some other segfaults and errors until I run out of space on the virtual server and eventually deleted my JULIA_PKG folder which probably solved my problem. 

I know, it's embarrassing, I thought I did try that as the first thing but I probably did not. 
Interestingly, it did not solved it immediately. My builds were probably broken by some other issues (which I attribute to the incremental builds, complete build would be probably fine but took hours on my system) until I converged back to v0.5.1 which was suddenly ok.

I still have to test the Win7 machine tomorrow. But I had similar set of packages on them so I expect deleting the pkg folder should work as well.

It would be nice to have more friendly error messages when there is an issue with the pkg folder. But given the problem is reproducible only on my system I guess the lesson here (at least for me :-) ) is to put `try unsetting the JULIA_PKG environment variable` on the "try-first" solutions list.

**Comment by martinholters** [comment]
It would still be helpful if you could back up the broken state for further investigation, even if you can solve your immediate problem.

**Comment by vh-d** [comment]
Sure. There was a working state when I run git bisect even with the old pkg folder. Unfortunately the cygwin terminal crashed when I wanted to log the output. I believe it was somwhere between `4d4ca5b77528cbad41f33d922886116cda34001a` and `077b605a18341f6929fd8f74fdc194e0b8a72c55` commits in `release-0.5`.

I can try to run it again on the second machine, but it will take some time. Is there any way to force `make` to rebuild everything except dependencies such as llvm, etc... that take so long to build? Or maybe writing a shell script that would `make clean` in some relevant subfolders?

**Comment by vh-d** [comment]
It seems the problem was in the `JULIA_HOME` environment variable after all. Unsetting it on the physical machine solved the problem (since it pointed to the old julia binary v0.5.0), not deleting the JULIA_PKG folder. 

What was the cause on the virtual machine is not clear to me. Unsetting `JULIA_HOME` variable did not help and also the two different versions were never installed at the same time. Moreover it works now in almost the same setting (including the `JULIA_HOME` variable set at the same value as before but excluding the content of JULIA_PKG folder). 

The only thing that has changed since then is that the virtual server was restarted on its regular sunday midnight time so maybe the old julia binary was kept in some kind of cash/memory... I did run the old binary just before the update to v0.5.1. In any case, I can't reproduce the issue any more.
