### ISSUE TITLE
Generated functions to allow return of Julia IR instead of julia AST

### ISSUE THREAD

**Issue by DrTodd13** [JuliaLang/julia#21146]
Right now, generators can only return AST.  It would help ParallelAccelerator if generators were also allowed to return IR.

**Comment by yuyichao** [comment]
You mean generated functions? You can just return a llvmcall.

**Comment by DrTodd13** [comment]
Here is the gist of what I want to be able to do.

@generated function gf1(some_func, arg_type1, arg_type2, ..., arg_typeN)
    optimized_ir = ParallelAccelerator.optimize(some_func, arg_type1, arg_type2, ..., arg_typeN)
    return optimized_ir
end

The problem is that ParallelAccelerator produces an optimized IR for some function for a given set of argument types and then we need to have a Julia method instance created from that IR.  Currently, we do this in a really ugly way.  We make a stub function and then replace the stub's IR with the optimized IR.  This is very fragile and dependent on lots of internal moving parts of Julia.  If a @generated could return an IR, then this problem is mitigated to some degree.  We'd only then be dependent on the structure of the IR itself and not other Julia internals.

**Comment by pabloferz** [comment]
@DrTodd13 please quote code snippets and surround macros by backtics in other to avoid bringing accidentally unrelated people to the conversation. (I edited your post above, but consider this in the future)

**Comment by yuyichao** [comment]
Still, why can't you just return a `llvmcall`?

**Comment by DrTodd13** [comment]
Yes, @vtjnash is correct.  I want to return Julia IR, not LLVM IR.

**Comment by yuyichao** [comment]
You mean lowered AST?

**Comment by DrTodd13** [comment]
No, in effect it is an optimized version of typed IR return from code_typed.

**Comment by JeffBezanson** [comment]
Implemented by #22440.
