### ISSUE TITLE
Unable to clone v0.6.0 alpha.

### ISSUE THREAD

**Issue by vernwalrahul** [JuliaLang/julia#21159]
While writing the checkout command for v0.6.0-pre.alpha branch. Its showing the following error:

**HEAD is now at 29bc2ac... feature freeze master for 0.6-pre (#20762)**

and is jumping back to the previous branch. 
Is there any other link from where we can clone that repo?

**Comment by yuyichao** [comment]
`v0.6.0-pre.alpha` is not a branch and please use discourse.julialang.org for questions.
