### ISSUE TITLE
logm issue

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#21179]
As reported by @iamnapo in https://github.com/JuliaLang/julia/issues/21143#issuecomment-289306668

```julia
julia> B = [3 2; -5 -3]
2×2 Array{Int64,2}:
  3   2
 -5  -3

julia> expm(logm(B))
2×2 Array{Float64,2}:
 -5.33599  -5.66504
 17.5616   18.4572
```

**Comment by YingboMa** [comment]
Also, Julia will hang in this situation.

```
julia> B = [1 -1; 1 -1]
2×2 Array{Int64,2}:
 1  -1
 1  -1

julia> logm(B)
```

The while loop in this line will never terminate.

https://github.com/JuliaLang/julia/blob/master/base/linalg/triangular.jl#L1698

**Comment by iamnapo** [comment]
I'd like to work on this if anyone else isn't already. Are there any relevant commits/PRs I could look for help?

**Comment by andreasnoack** [comment]
I know that @YingboMa looked a bit at this function yesterday. @YingboMa, are you already working on this?

**Comment by YingboMa** [comment]
Yes, I plan to work on this.
