### ISSUE TITLE
Indexed assignment not defined for Hermitian matrices [0.5]

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#21186]
On 0.5.1, this does not work:

```julia
julia> 2.*Hermitian(rand(4,4))
ERROR: indexed assignment not defined for Hermitian{Float64,Array{Float64,2}}
 in .*(::Int64, ::Hermitian{Float64,Array{Float64,2}}) at .\arraymath.jl:95
```

It seems like it has been fixed on 0.6, but it would be nice to have the backport since many packages still do not work there.

**Comment by andreasnoack** [comment]
I don't think this will be fixed on 0.5 since it takes a completely different code path so fixing it would be to add new features to 0.5. If you want to use this syntax, it would probably be better just to migrate to 0.6 when it is released.

**Comment by jebej** [comment]
Shouldn't `x*A` just call `scale(x,A)`?

**Comment by andreasnoack** [comment]
There is no longer a `scale` function but I agree that `x * A::Hermitian` should work. What I think cannot be fixed generally in 0.5 is broadcasting for special matrices.

**Comment by jebej** [comment]
I see. Maybe `scale!` should be removed from the documentation then, right now it still appears [here](http://docs.julialang.org/en/latest/stdlib/linalg.html#Base.LinAlg.scale!).

Is there no way to do this other than going back to a `full` matrix right now then?

**Comment by jebej** [comment]
It seems `scale!(A.data,3)` still works.

**Comment by andreasnoack** [comment]
We still have `scale!` but not `scale`.

**Comment by jebej** [comment]
You're right. I will amend my previous comment then: could we have `x*A` call `scale!(x,A.data)` (as a fix for 0.5)? Note that `scale!(x,A)` does currently give that same error (for Symmetric too):

```julia
julia> scale!(A,3)
ERROR: indexed assignment not defined for Hermitian{Float64,Array{Float64,2}}
 in macro expansion at .\linalg\generic.jl:9 [inlined]
 in macro expansion at .\simdloop.jl:73 [inlined]
 in generic_scale!(::Hermitian{Float64,Array{Float64,2}}, ::Int64) at .\linalg\generic.jl:8
 in scale!(::Hermitian{Float64,Array{Float64,2}}, ::Int64) at .\linalg\generic.jl:44
```

**Comment by andreasnoack** [comment]
Yes. That is almost how it should be defined. Notice, though that `scale!` modifies the input matrix so it should be more like `scale!(x,copy(A.data))` and for real `x`, I think it should even be `Hermitian(scale!(x,A.data),A.uplo)`.

**Comment by jebej** [comment]
Right. I also was looking at the discussion over at issue #8415 and it seems it might be worth it to revisit the julia vs BLAS performance:

```julia
lia> B = rand(10000,10000);

julia> @benchmark scale!(B,2.0)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     64.793 ms (0.00% GC)
  median time:      64.926 ms (0.00% GC)
  mean time:        65.005 ms (0.00% GC)
  maximum time:     65.635 ms (0.00% GC)
  --------------
  samples:          77
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Base.LinAlg.generic_scale!(B,2.0)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     66.710 ms (0.00% GC)
  median time:      66.997 ms (0.00% GC)
  mean time:        67.150 ms (0.00% GC)
  maximum time:     68.595 ms (0.00% GC)
  --------------
  samples:          75
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> C = rand(1000,10000);

julia> @benchmark Base.LinAlg.generic_scale!(C,2.0)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     6.520 ms (0.00% GC)
  median time:      6.584 ms (0.00% GC)
  mean time:        6.618 ms (0.00% GC)
  maximum time:     7.800 ms (0.00% GC)
  --------------
  samples:          747
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark Base.LinAlg.scale!(C,2.0)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     6.333 ms (0.00% GC)
  median time:      6.479 ms (0.00% GC)
  mean time:        6.487 ms (0.00% GC)
  maximum time:     6.821 ms (0.00% GC)
  --------------
  samples:          761
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

This was with 0.6.0 (seems to be also the case on 0.5), and without changing the number of threads for BLAS, meaning that it was using my CPU at 100%, whereas julia was only taking 25%. I can open an other issue for this with more details if that's desired.

**Comment by jebej** [comment]
I can't figure out what method signature to add.
Defining this still calls the old scale method:
```
Base.scale{T<:Base.LinAlg.HermOrSym}(A::T,x) = T(scale!(copy(A.data),x),A.uplo)
```

**Comment by jebej** [comment]
Any pointers? Right now it is impossible to multiply hermitian and symmetric matrices...

**Comment by tkelman** [comment]
You probably want a `*` method where one input is `::Number` and the other input is Symmetric or Hermitian

**Comment by andreasnoack** [comment]
This no longer errors but as mentioned by @tkelman, we should have a special method for scalar multiplication with `Symmetric` and `Hermitian`. For the latter, the scalar would have to be `Real`, though.

**Comment by KristofferC** [comment]
This can be closed I think?

```jl
julia> 2 * Hermitian(rand(4,4))
4×4 Hermitian{Float64,Array{Float64,2}}:
 1.98653   0.569006    0.316969    0.770288
 0.569006  1.44052     0.00739729  1.93128
 0.316969  0.00739729  0.755068    1.51593
 0.770288  1.93128     1.51593     1.3288
```

Re-open if I missunderstood.
