### ISSUE TITLE
update precompile.jl

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#21196]
This file should be updated to reflect changes to Base over the 0.6 cycle, and will help repl startup time and package load times.

See e.g. https://github.com/JuliaLang/julia/pull/20793#issuecomment-289732784

This can now be done by defining `TRACE_COMPILE` in options.h.

**Comment by bjarthur** [comment]
while at it, could someone please improve the docstring for `precompile`?  specifically, a Bool is returned, but what does it mean?  i assume false indicates an error.  but under what circumstances does precompile not work?  thanks.
