### ISSUE TITLE
build_sysimg.jl failure on Windows

### ISSUE THREAD

**Issue by dextorious** [JuliaLang/julia#21236]
Trying to rebuild the system image on a fresh Julia 0.5.1 installation (official binaries, running on Windows 10) using:
```
Pkg.add("WinRPM")
using WinRPM
WinRPM.install("gcc")
include(joinpath(dirname(JULIA_HOME),"share","julia","build_sysimg.jl"))
build_sysimg(force=true)
```
works fine until the `build_sysimg(force=true)` part, which yields the following output (only the relevant ending is shown here):
```
docs/Docs.jl
C:\tools\Julia-0.5.1\share\julia\base\precompile.jl
INFO: Linking sys.dll
c:/users/admin/.julia/v0.5/winrpm/deps/usr/x86_64-w64-mingw32/sys-root/mingw/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
ERROR: failed process: Process(`'C:\Users\admin\.julia\v0.5\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\gcc.exe' '-LC:\tools\Julia-0.5.1\bin' -shared -ljulia -lssp -o 'C:\tools\Julia-0.5.1\bin\..\lib\julia\sys.dll' 'C:\tools\Julia-0.5.1\bin\..\lib\julia\sys.o'`, ProcessExited(1)) [1]
 in link_sysimg(::String, ::String, ::Bool) at C:\tools\Julia-0.5.1\share\julia\build_sysimg.jl:163
 in (::##2#3{Bool,String})() at C:\tools\Julia-0.5.1\share\julia\build_sysimg.jl:84
 in cd(::##2#3{Bool,String}, ::String) at .\file.jl:48
 in #build_sysimg#1(::Bool, ::Bool, ::Function, ::Void, ::String, ::Void) at C:\tools\Julia-0.5.1\share\julia\build_sysimg.jl:48
 in (::#kw##build_sysimg)(::Array{Any,1}, ::#build_sysimg, ::Void, ::String, ::Void) at .\<missing>:0 (repeats 2 times)
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:64
 in macro expansion at .\REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at .\event.jl:68
```

It looks to me like WinRPM is trying to use a version of gcc without pthreads support, but since the script is part of this repository and I'm not sure WinRPM is at fault, I'm posting the issue here for the time being.

**Comment by tkelman** [comment]
the documentation / error is a little out of date, you need to install pthreads separately - ref https://discourse.julialang.org/t/error-trying-to-build-system-image-on-windows/2745/4

**Comment by tkelman** [comment]
I just proposed adding the dependency at https://build.opensuse.org/request/show/483874, if that gets accepted then we won't need to change anything.

**Comment by dextorious** [comment]
Thank you for the quick clarification. Doing
```
Pkg.add("WinRPM")
using WinRPM
WinRPM.install("gcc", yes=true)
WinRPM.install("winpthreads-devel", yes=true)
include(joinpath(dirname(JULIA_HOME),"share","julia","build_sysimg.jl"))
build_sysimg(force=true)
```
fixed it for me, the image was built successfully. As soon as either the upstream dependency is added or the documentation changed this issue can be closed.

**Comment by m-j-w** [comment]
It appears the [upstream request](https://build.opensuse.org/request/show/483874#request_history) has now been accepted with a follow-up request for 32-bit.

**Comment by kEviN1H** [comment]
INFO: Upgrading DocStringExtensions: v0.3.2 => v0.3.3
INFO: Downgrading LightGraphs: v0.7.5 => v0.7.3
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
INFO: Building EzXML
====================================================[ ERROR: EzXML ]====================================================

LoadError: Package candidate for libxml2-2 not found
while loading F:\DevIDE\JuliaPro\pkgs-0.5.1.1\v0.5\EzXML\deps\build.jl, in expression starting on line 3

========================================================================================================================
INFO: Building Rmath
INFO: Building Blosc
INFO: Building HDF5
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
====================================================[ ERROR: HDF5 ]=====================================================
LoadError: None of the selected providers can install dependency libhdf5.
Use BinDeps.debug(package_name) to see available providers

while loading F:\DevIDE\JuliaPro\pkgs-0.5.1.1\v0.5\HDF5\deps\build.jl, in expression starting on line 27

========================================================================================================================
====================================================[ BUILD ERRORS ]====================================================
WARNING: HDF5 and EzXML had build errors.

 - packages with build errors remain installed in F:\DevIDE\JuliaPro\pkgs-0.5.1.1\v0.5
 - build the package(s) and all dependencies with `Pkg.build("HDF5", "EzXML")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================
julia> ENV
Base.EnvHash with 45 entries:
  "=C:"                     => "C:\\Windows\\System32"
  "=F:"                     => "F:\\DevIDE\\JuliaPro\\Julia-0.5.1\\bin"
  "ALLUSERSPROFILE"         => "C:\\ProgramData"
  "APPDATA"                 => "C:\\Users\\        \\AppData\\Roaming"
  "CommonProgramFiles"      => "C:\\Program Files\\Common Files"
  "CommonProgramFiles(x86)" => "C:\\Program Files (x86)\\Common Files"
  "CommonProgramW6432"      => "C:\\Program Files\\Common Files"
  "COMPUTERNAME"            => "         "
  "ComSpec"                 => "C:\\WINDOWS\\system32\\cmd.exe"
  "GADFLY_THEME"            => "dark"
  "HOMEDRIVE"               => "C:"
  "HOMEPATH"                => "\\Users\\        "
  "HTTPS_PROXY"             => "HTTP://127.0.0.1:8087"
  "HTTP_PROXY"              => "HTTP://127.0.0.1:8087"
  "JULIA_PKGDIR"            => "F:\\DevIDE\\JuliaPro\\pkgs-0.5.1.1"
  "JUPYTER"                 => "F:\\DevIDE\\JuliaPro\\Python\\Scripts\\jupyter.exe"
  "LOCALAPPDATA"            => "C:\\Users\\       \\AppData\\Local"
  "LOGONSERVER"             => "\\\      "
  "NUMBER_OF_PROCESSORS"    => "8"
  "OneDrive"                => "F:\\OneDrive"
  "OPENBLAS_MAIN_FREE"      => "1"
  "OS"                      => "Windows_NT"
  "Path"                    => "F:\\DevIDE\\JuliaPro\\Julia-0.5.1\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\S…
  "PATHEXT"                 => ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
  "PROCESSOR_ARCHITECTURE"  => "AMD64"
  ⋮                         => ⋮

**Comment by tkelman** [comment]
> As soon as either the upstream dependency is added or the documentation changed this issue can be closed.

Dependencies were added upstream on OBS for both win64 and win32
