### ISSUE TITLE
cannot document using function call after """ block.

### ISSUE THREAD

**Issue by usefulhyun** [JuliaLang/julia#21230]
Hello, while I write comment using """ block, I found an error.
using function call such as print, include, and any custom function just after """ block invokes
"LoadError:cannot document the following expression" error.

This is a simple code to reproduce the error I encountered. 

```
"""
  Here is a comment or documentation
"""
println("some text") # this can be any function call
```

Is this error intended? if so why and what syntax should I use for multiple line comment and documentation?

**Comment by tkelman** [comment]
Use `#` or `#= ... =#` for comments. Not sure this should be an error though, maybe a warning to still let you know that the docstring didn't work if that was the intent.

**Comment by usefulhyun** [comment]
`#= ... =#` does not invoke an error.
What I don't understand is they don't invoke an error for use of different statements such as assignment.

**Comment by tkelman** [comment]
Raw strings immediately preceding function definitions, field names, or constant assignments serve as docstrings. If you go into help mode in the repl via `?` and ask `help?> a` after that most recent example you'll see the docstring you gave it. That doesn't work for function calls though as your initial post reports. Though as I said it's probably not ideal to have it give an error for bad docstring formatting, a warning (one you could disable, maybe with `--depwarn=no` ?) or some other type of indication might be better.
