### ISSUE TITLE
Scripts run in interactive mode exit on Error

### ISSUE THREAD

**Issue by Benoit9** [JuliaLang/julia#21233]
If a script is run in interactive mode:

```julia -i myscript.jl arg1 arg2```

and it encounters an error, julia exits.

It's as if the script first runs normally, then after it finishes the REPL starts.

I expected (coming from Python) that it would as if the REPL was running the script line-by-line. In that case, the REPL would _not_ exit after an error and let me examine the variables, try to correct the error interactively, etc.

My apologies if it is the intended behavior or if it was discussed before. I couldn't find anything.

**Comment by r-barnes** [comment]
I also had this expectation.

**Comment by Benoit9** [comment]
I gather from [this comment](https://github.com/JuliaLang/julia/issues/26320#issuecomment-370424974) that it is the intended behavior.

Is there any chance that can be changed? Otherwise I should just close this.

**Comment by JeffBezanson** [comment]
Yes I think this could be changed.

**Comment by JeffBezanson** [comment]
Triage accepts.

**Comment by Benoit9** [comment]
Awesome! Thank you very much!
