### ISSUE TITLE
Inconsistent branch cut in square root function

### ISSUE THREAD

**Issue by ettersi** [JuliaLang/julia#21259]
I just spent three hours tracking down this:
```
julia> sqrt(-1.0+0.0im)
0.0 + 1.0im
julia> sqrt(-1.0-0.0im)
0.0 - 1.0im
```
I think it would be less confusing if the answer was `+1im` in both cases. For example, the above definition will lead to inconsistencies with types lacking a signed zero:
```
julia> sqrt(-1+0im)
0.0 + 1.0im
julia> sqrt(-1-0im)
0.0 + 1.0im
```
Even worse:
```
julia> z = -1.0im; sqrt(z^2)
0.0 + 1.0im
julia> z = -1.0im + 0.0; sqrt(z^2)  # Adding 0 is a noop, right? WRONG!
0.0 - 1.0im
```
[C++](http://en.cppreference.com/w/cpp/numeric/complex/sqrt) follows the convention currently implemented in Julia, Python implements what I suggested.

**Comment by yuyichao** [comment]
While it's debatable where the branch cut should be, there doesn't seem to be any inconsistency. The branch cut is at `0im`.

A few notes:

1. what you are asking for is basically ignore the IEEE semantics of signed zero, there are many other cases where it is significant.
2. Adding `0.0` is not no-op for floating point, adding `-0.0` is.
3. Python has the same behavior. It's just non-trival to get a complex number with a negative 0.

    ```python
    In [1]: import cmath

    In [2]: cmath.sqrt(complex(-1.0, -0.0))
    Out[2]: -1j

    In [3]: cmath.sqrt(complex(-1.0, 0.0))
    Out[3]: 1j
    ```

**Comment by yuyichao** [comment]
Also https://github.com/JuliaLang/julia/issues/20924

**Comment by ettersi** [comment]
Then maybe Python is even worse. I was pleased to see  `sqrt(-1.0 - 1.0*1j) -> 1j`, but only until you made me aware that actually `-1.0 - 1.0*1j -> -1+0j`. I guess if IEEE wants to have it this way, it is not up to Julia to change this.
I'm sure IEEE had their reasons to do what they did, but boy the consequences are annoying in this case!

**Comment by stevengj** [comment]
One of the advantages of signed zeros is precisely to express branch cuts in a reasonable way.  This is totally standard and we would be crazy to change it.

**Comment by timholy** [comment]
I don't think you can call it a "reasonable way": since there is no `2.0+` and `2.0-`, there is no mechanism to specify a branch cut for `f(z) = sqrt(z-2im)`. The IEEE mechanism works only for a single number, `0.0`, out of all possible floating-point numbers. The reasonable way to do this is (1) for there to be only one `0.0`, and (2) when you want to specify a branch cut, require the use of [dual numbers](https://en.wikipedia.org/wiki/Dual_number). The Julia package is [here](https://github.com/JuliaDiff/DualNumbers.jl).

That said, I assume the IEEE decision is enshrined in CPU instructions; if so, I don't think we should change it, since Julia should be in the business of leveraging the hardware.

**Comment by stevengj** [comment]
@timholy, 0 is somewhat special in the set of all possible numbers, and it plays a special role in floating-point arithmetic (underflow, reciprocal of Inf).  It is worth respecting the sign of 0.0 in making branch-cut decisions.

[Kahan's famous paper on the subject](http://people.freebsd.org/~das/kahan86branch.pdf) has a rather extensive discussion of why the computed branch cut should take advantage of the sign of zero.  All sorts of mathematical identities would cease to work. For example, `1/sqrt(z)` and `sqrt(1/z)` would take different branch cuts for `z=Complex(-1.0,0.0)` if you didn't respect the sign of zero: one would give `+im` and the other would give `-im`.  He also writes:

> The examples presented in this paper may give the impression that an analyst will benefit far less than a programmer from Principal Expressions because their benefits seem meagre unless slits run along straight lines. Moreover a signed Zero Seems useless. except when slits lie in the real and imaginary axes. True; but not the whole truth. Despite that applications of elementary functions frequently relocate their slits to nonstandard places, the functions so constructed have to be communicated to humans and to computers in terms of combinations of the standard elementary functions with which we are all acquainted.

(He then goes on to give an example in which you relocate the branch cut of arcsine, but still run into trouble if zero is unsigned.)

This is one of those things that were thought through heavily for the IEEE standard, and the resulting choices are now deeply ingrained in the way numerical analysts think about floating-point arithmetic.  As I wrote in #20924, we'd be crazy to discard the IEEE behavior based on people's gut reactions on a github thread.

**Comment by stevengj** [comment]
(This is not a hardware issue: `sqrt(::Complex)` is implemented in software, in pure Julia in fact.)

**Comment by simonbyrne** [comment]
As a point of pedantry: IEEE754 has nothing to say on complex numbers, though it does indirectly specify branch cuts via the behaviour via `atan2`.

A more formal specification is in ISO 10967-3 (Language independent arithmetic: Complex integer and floating point arithmetic and complex elementary numerical functions), which does explicitly mention the behaviour of complex square root.

**Comment by timholy** [comment]
Those are indeed concerns, but how does one handle `1/sqrt(z-2im)` vs `sqrt(1/(z-2im))`? 0 is indeed a special number, but we also have functions like `expm1`; any number is special to the right audience :smile:. `tan` obviously thinks that `pi/2` is pretty special. The IEEE solution defines a certain behavior as "correct" (and they're not wrong to think so), but then bizarrely makes it impossible to exhibit correct behavior at all points on the real line except for one.

**Comment by stevengj** [comment]
If you have a function of `δ = z - μ` for `μ ≠ 0`, then a lack of `μ⁺` and `μ⁻` values is the least of your problems.  You're going to have problems with cancellation errors for `z` near `μ`, and if you need high accuracy in this regime you're going to want to change variables from `z` to `δ` if you can.

**Comment by stevengj** [comment]
Can we close this issue and #20924?  It seems pointless to debate support for either IEEE signed zeros (which are ingrained in hardware) or ISO branch cuts (which are basically universal in modern languages and libraries).

(Nor are we going to switch Julia's default numerics to use dual numbers or interval arithmetic or unums or any other scheme that is not supported in hardware.)

**Comment by timholy** [comment]
With a dual number there's no concern about cancellation. But I agree there's nothing to be done, since (as I said) we should be in the business of leveraging the hardware.
