### ISSUE TITLE
Consider silencing warnings in compilation by adding `-w` in release builds

### ISSUE THREAD

**Issue by m-j-w** [JuliaLang/julia#21268]
Currently, when building Julia from source with a recent gcc, there are literally hundreds of warnings regarding unused variables, constness, misalignements etc, at least in the dependencies.
Considering Julia to be more and more used in professional environments, this might give the wrong impression about the overall code quality; and typical users and reviewers would more likely be scared off than go into the dependencies and fix those issues.

To improve the build experience I propose to add `-w` by default to silence the _release build_ warnings completely. This option works both for gcc and Intel compilers. Probably some of the above mentioned warnings would still be printed in which case I'd also propose to silence those with `-Wno-XXX`.

It may also be an option to turn this on selectively only in tagged versions, such as an upcoming 0.6.0.

**Comment by vtjnash** [comment]
Agreed that we can submit PRs to upstream projects to try to reduce the printout from the linter. Many projects (including Julia) try to minimize the rate of false-positives that get printed. But it's not actually possible to predict and get ahead of whatever warnings gcc might decide to implement in their next version.
