### ISSUE TITLE
No method for isless(::Complex128,::Int64)

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#21273]
It seems that there is no method for comparing complex numbers to integers, which seems to be required for (some) matrix exponentials, and for all complex matrix exponentials.

i.e., the following happens intermitently, depending on the random matrix
```julia
julia> rand(3,3)^2.3
ERROR: MethodError: no method matching isless(::Complex{Float64}, ::Int64)
Closest candidates are:
  isless(::AbstractFloat, ::Real) at operators.jl:98
  isless(::Real, ::Real) at operators.jl:266
Stacktrace:
 [1] (::Base.LinAlg.##17#18)(::Complex{Float64}) at .\<missing>:0
 [2] broadcast_t(::Function, ::Type{Any}, ::Tuple{Base.OneTo{Int64}}, ::Cartesia
nRange{CartesianIndex{1}}, ::Array{Complex{Float64},1}) at .\broadcast.jl:255
 [3] broadcast_c at .\broadcast.jl:298 [inlined]
 [4] broadcast(::Function, ::Array{Complex{Float64},1}) at .\broadcast.jl:415
 [5] ^(::Array{Float64,2}, ::Float64) at .\linalg\dense.jl:320
```
but this always throws an error:
```julia
julia> rand(Complex128,3,3)^2.3
ERROR: MethodError: no method matching isless(::Complex{Float64}, ::Int64)
...
```

**Comment by tkelman** [comment]
how would you compare complex numbers to real integers?

it's a bug in the matrix exponential, being worked on in https://github.com/JuliaLang/julia/pull/21184, that it's trying to do this

**Comment by jebej** [comment]
It seems that defining
```
Base.isless(a::Complex,b::Real) = isless(norm(a),b)
```
gives the right matrix exponential, and I think this is how MATLAB defines `<` as well.

**Comment by jebej** [comment]
Actually scratch that, it seems MATLAB compares the real part only.

**Comment by JeffBezanson** [comment]
Complex numbers don't have a well-defined total order. We should just fix matrix exponential.

**Comment by jebej** [comment]
Yes. Does #21184 also take care of complex matrix exponentials? If so we can close this issue.

**Comment by ararslan** [comment]
> Does #21184 also take care of complex matrix exponentials?

Yes
