### ISSUE TITLE
Bug for @s_str

### ISSUE THREAD

**Issue by AStupidBear** [JuliaLang/julia#21280]
```s"\n"``` should produce ```Base.SubstitutionString("\n")```, but in ```julia 0.5.1``` it produces ```Base.SubstitutionString("\\n")```. [Discourse Question: Bug of replace?](https://discourse.julialang.org/t/bug-of-replace/3023)

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/27125
