### ISSUE TITLE
Sneaky bait and switch in lowered code

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#21281]
Consider:

```jl
type Q{T}
    x::T
end

Q() = Q(0)

function f(qs)
    for i in 1:5
        q = qs[i]
        q.x = i
    end
end

qss = [Q() for i in 1:5, j in 1:5]
@code_warntype f(view(qss, :, 1))
```

Looking at the result we see:

```jl
Variables:
  #self#::#f
  qs::SubArray{Q{Int64},1,Array{Q{Int64},2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}
  i::Int64
  q::Any
  #temp#::Int64
  r::Q{Int64}
```

This leads us to believe that `q` is inferrred to `Any` and that we have a type instability. However, looking more carefully, we find that `q` is actually not used in the function body. Instead a new variable, `r` is introduced which takes the place of `q`. This one is correctly inferred to be of type `Q{Int64}`.

On 0.5 the result is instead:

```jl
Variables:
  #self#
::#f
  qs::SubArray{Q{Int64},1,Array{Q{Int64},2},Tuple{Colon,Int64},true}
  #temp#::Int64
  i::Int64
  q::Q{Int64}
  r::Q{Int64}
```

which infers `q` correctly. 

This probably does not have an impact on performance but makes `@code_warntype` much harder to use since you can't trust your variable names anymore.

**Comment by KristofferC** [comment]
Probably related (unused `y` is inferred as `Any`):

```jl
julia> z{T}(x::T, y::Vector{T}) = x
z (generic function with 1 method)

julia> @code_warntype z(3, [1,2])
Variables:
  #self#::#z
  x::Int64
  y::Any

Body:
  begin 
      return x::Int64
  end::Int64
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/20801
