### ISSUE TITLE
Dot operation between a tuple and a scalar variable generates type instability

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#21291]
For example, when a constant `Int64` is dot-added to a `Tuple{Int64,Int64,Int64}`, the result correctly remains a `Tuple{Int64,Int64,Int64}`:
```julia
julia> VERSION
v"0.6.0-pre.beta.30"

julia> function dotadd_tuple_intc()
           t = (1,0,1)
           t = t .+ 1
       end
dotadd_tuple_intc (generic function with 1 method)

julia> @code_warntype dotadd_tuple_intc()
Variables:
  #self#::#dotadd_tuple_intc
  t::Tuple{Int64,Int64,Int64}
  #41::##41#42
```

However, if you assign the constant `Int64` to a variable and dot-add that variable to a `Tuple{Int64,Int64,Int64}`, the result is no longer a `Tuple{Int64,Int64,Int64}`,  but just an abstract `Tuple`:
```julia
julia> function dotadd_tuple_intv()
           o = 1
           t = (1,0,1)
           t = t .+ o
       end
dotadd_tuple_intv (generic function with 1 method)

julia> @code_warntype dotadd_tuple_intv()
Variables:
  #self#::#dotadd_tuple_intv
  o::Int64
  t::Tuple
  #3::Base.Broadcast.##3#4{Base.#+,Tuple{Tuple{Int64,Int64,Int64},Int64}}
```

If we directly use `broadcast`, the same type instability occurs even if we do not assign the constant `Int64` to a variable :
```julia
julia> function bcadd_tuple_intc()
           t = (1,0,1)
           t = broadcast(+, t, 1)
       end
bcadd_tuple_intc (generic function with 1 method)

julia> @code_warntype bcadd_tuple_intc()
Variables:
  #self#::#bcadd_tuple_intc
  t::Tuple
  #3::Base.Broadcast.##3#4{Base.#+,Tuple{Tuple{Int64,Int64,Int64},Int64}}
```

**Comment by martinholters** [comment]
Also `broadcast(+, t, (1,1,1))` works fine, but for the mixed tuple/scalar case, the result size is handed to `ntuple` as a runtime parameter (i.e. `n`, not `Val{n}`).

**Comment by pabloferz** [comment]
I have a half-baked solution for this. Will submit a PR soon.

**Comment by pabloferz** [comment]
Closed by #21331

**Comment by wsshin** [comment]
Thanks!  This fix helps a lot.

One more question.  With this fix, dot-addition between a tuple and a scalar works not much slower than dot-addition between a StaticArray and a scalar:
```julia
julia> VERSION
v"0.6.0-pre.beta.86"

julia> using BenchmarkTools

julia> using StaticArrays

julia> function dotadd_tuple_intv()
           o = 1
           t = (1,0,1)
           t = t .+ o
       end
dotadd_tuple_intv (generic function with 1 method)

julia> function dotadd_svec_intv()
           o = 1
           v = @SVector([1,0,1])
           v = v .+ o
       end
dotadd_svec_intv (generic function with 1 method)

julia> @btime dotadd_tuple_intv()
  10.647 ns (0 allocations: 0 bytes)

julia> @btime dotadd_svec_intv()
  7.007 ns (0 allocations: 0 bytes)
```

However, inlining makes the StaticArray version much faster than the tuple version:
```julia
julia> @inline function inlined_dotadd_tuple_intv()
           o = 1
           t = (1,0,1)
           t = t .+ o
       end
inlined_dotadd_tuple_intv (generic function with 1 method)

julia> @inline function inlined_dotadd_svec_intv()
           o = 1
           v = @SVector([1,0,1])
           v = v .+ o
       end
inlined_dotadd_svec_intv (generic function with 1 method)

julia> @btime inlined_dotadd_tuple_intv()
  8.219 ns (0 allocations: 0 bytes)

julia> @btime inlined_dotadd_svec_intv()
  1.894 ns (0 allocations: 0 bytes)
```

I wonder if there is a way to make the inlined function with tuple operations as fast as the inlined function with StaticArray operations.

**Comment by pabloferz** [comment]
Hi @wsshin. You seem to be benchmarking on global scope, if you define

```julia
f() = inlined_dotadd_tuple_intv()
g() = inlined_dotadd_svec_intv()
```

you should observe the same difference you had with `dotadd_tuple_intv`  and `dotadd_svec_intv`.

**Comment by wsshin** [comment]
I see.  I knew functions defined in REPL are defined in global scope, but I though (without knowing why) I could benchmark functions directly if they do not take any arguments.  (Of course, when benchmarking functions with arguments, I interpolated the arguments with `$`.)

Why does this convention not work here?  Is this because of the `@inline` macro?

**Comment by yuyichao** [comment]
There doesn't seem to be any "Benchmark in global scope" here.

**Comment by wsshin** [comment]
@yuyichao, do you mean it is incorrect to say that I was benchmarking in global scope?  Then why is wrapping by another function (`f` and `g` in @pabloferz's example) the correct way of benchmarking an inlined function?

**Comment by yuyichao** [comment]
> do you mean it is incorrect to say that I was benchmarking in global scope?

Right.

> Then why is wrapping by another function (f and g in @pabloferz's example) the correct way of benchmarking an inlined function?

No it's not. It just disabled inlining.

**Comment by wsshin** [comment]
@yuyichao, thanks for your answer!

@pabloferz, then back to my original question: is there a way to make an inlined function that uses tuple operations as fast as an inlined function that uses equivalent StaticArray operations?

**Comment by yuyichao** [comment]
The issue seems to be that `ntuple` isn't inlined in the tuple version.

**Comment by pabloferz** [comment]
Oh, right. Sorry, @yuyichao is right, `ntuple` (on which `broadcast` over tuples relies) is not inlined. In the `StaticArrays` case the whole `broadcast` method is most likely getting inlined.

**Comment by Sacha0** [comment]
Hm, `@inline`ing `ntuple(..., Val{N})` specifically might be reasonable? Thoughts `@pabloferz`?

**Comment by pabloferz** [comment]
I guess it might be reasonable as long as we put some limit on the `N` to prevent inlining very long tuples.

**Comment by wsshin** [comment]
@Sacha0, @pabloferz, is there a PR on this `ntuple` issue?  I would like to follow it.

**Comment by Sacha0** [comment]
> is there a PR on this ntuple issue? I would like to follow it.

No PR exists specifically for inlining `ntuple(..., Val{N})` insofar as I am aware. Simple change to make and test though --- would you like to have a go? :)

**Comment by wsshin** [comment]
@Sacha0, sure.  Let me look into this.

**Comment by wsshin** [comment]
PR inlining `ntuple(f, Val{N})` for 1 ≤ N ≤ 10 is created: https://github.com/JuliaLang/julia/pull/21446.
