### ISSUE TITLE
method error 

### ISSUE THREAD

**Issue by 2gezer** [JuliaLang/julia#21297]
hi there! I am trying to reproduce the same comprehension like in the example of gadfly
-> http://gadflyjl.org/stable/lib/geoms/geom_errorbar.html

_using Distributions

sds = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
n = 10
ys = [mean(rand(Normal(0, sd), n)) for sd in sds]
ymins = ys .- (1.96 * sds / sqrt(n))
ymaxs = ys .+ (1.96 * sds / sqrt(n))

plot(x=1:length(sds), y=ys, ymin=ymins, ymax=ymaxs,
     Geom.point, Geom.errorbar)_

the error is than : "MethodError: objects of type Array{$Int,1} are not callable\nUse square brackets [] for indexing an Array." 

how can one solve it?

**Comment by andreasnoack** [comment]
Please ask questions at discourse.julialang.org
