### ISSUE TITLE
Unable to !push to a Float Array

### ISSUE THREAD

**Issue by RichardoC** [JuliaLang/julia#21306]
Hi there, I'm using Julia 0.5.1 on OSX and have encountered the following issue where I'm unable to extend a float array.

```
v_list = Float64[]
!push(v_list,1.0)

#Below is the output 

ERROR: UndefVarError: push not defined
```

However, if the type is Int32 it works fine.

UPDATE:
Should be push! instead.

Thanks,
RC

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
