### ISSUE TITLE
Please add a function to join an UDP multicast group

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/julia#21300]
Joining a UDP multicast group is not yet supported by Julia.
Probably it requires just one operation system specific function call to set the correct options.
We really need this!
Uwe

**Comment by Paul-in-CH** [comment]
This worked for me.

Create the socket:
`s = UDPSocket()'

Join the multicast group:
'ccall(:uv_udp_set_membership, Cint, (Ptr{Void}, Ptr{UInt8}, Ptr{UInt8}, Cint), s.handle, "multicast IP", C_NULL, 1)`

Get a message:
'msg = recv(s)'

Leave the multicast group:

'ccall(:uv_udp_set_membership, Cint, (Ptr{Void}, Ptr{UInt8}, Ptr{UInt8}, Cint), s.handle, "multicast IP", C_NULL, 0)'

**Comment by StefanKarpinski** [comment]
If someone wants to take these C calls and turn them into an API we'd be happy to have them.

**Comment by Paul-in-CH** [comment]
Sorry - I don't feel qualified to put it into the API!

I would add that in this call:
`ccall(:uv_udp_set_membership, Cint, (Ptr{Void}, Ptr{UInt8}, Ptr{UInt8}, Cint), s.handle, "multicast IP", C_NULL, 0)`

`C_NULL` refers to the interface from ifconfig command line.
