### ISSUE TITLE
Heisenbug involving map! and data corruption in Julia 0.6

### ISSUE THREAD

**Issue by traktofon** [JuliaLang/julia#21311]
While stress-testing my (registered) package [FortranFiles.jl](https://github.com/traktofon/FortranFiles.jl) I encountered failures which only happen in julia-0.6.  I believe the error lies in the Julia compiler, because very subtle (even unrelated) changes to the code influence whether the test passes or fails.

To reproduce, you need the "convert" branch of my package, and a simplified test case and input data can be found in the attachment "nasty.zip". Running the test script "nasty.jl" with julia-0.5 passes all tests, but with julia-0.6 some tests fail. In short, the tests read four arrays from a binary file. All tests read the same data, but differ in the way that the arrays-to-be-read are specified. The user can just pass an `Array` instance to be filled, or pass a tuple of `(DataType, dims...)` to request an array of that type and size. Specifically, test <3c> returns corrupted data.

Here are some **very weird observations** which lead me to believe this is an error in Julia. I've narrowed it down to [this read_spec method](https://github.com/traktofon/FortranFiles.jl/blob/convert/src/read.jl#L52):

* If you uncomment any of the `println`s, all tests pass.
* For the test case in question, `rec.convert.onread == identity`, so you could just comment out the `map!` call. That makes test <3c> pass, but test <5> still fails.
* Test <3b> contains the "unraveled" code for test <3c>, i.e. calling all the individual steps of [this read method](https://github.com/traktofon/FortranFiles.jl/blob/convert/src/read.jl#L35) on the top level, instead of calling `read`. It passes.
* Test <3a> does almost the same as <3c>, just it requests the third array "flattened" (i.e. as a 1D array instead of a 2D array). It passes.
* So the difference between test <3a> and <3c> is only in the specification of the 3rd array-to-be-read, yet all returned arrays are corrupted.
* Likewise, tests <1> and <3c> differ only in the specification for the 2nd array-to-be-read, yet all returned arrays are corrupted.
* Forgot to include in the script: If you change test <3c> to omit reading the last array, i.e. `a,b,c = read(f, (Complex64,a1), Array{Int64}(b1), (Float64,c1,c2))`, it also passes. That is, choosing to read the 4th array corrupts all arrays.

Additional info:

* without optimization (-O0) the failure still happens
* without inlining (--inline=no) already test <1> fails

Version info:

> Julia Version 0.6.0-pre.beta.61
> Commit caf8af5 (2017-04-07 01:18 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

Let me know if there is more information I can provide.

For convenience, here is the test script:
```julia
using FortranFiles  # need "convert" branch
using Base.Test

# --- dimensions

a1    = 2
b1    = 2
c1,c2 = 2,2
d1    = 2

# --- read native

f = open("nasty.bin")
lrm = read(f, Int32) # leading record marker
aa  = read(f, Complex64, a1)
bb  = read(f, Int64, b1);
cc  = read(f, Float64, c1, c2);
dd  = read(f, Complex64, d1);
trm = read(f, Int32) # trailing record marker
close(f)
@assert lrm==trm

# --- read with FortranFile

f = FortranFile("nasty.bin")

@testset "<1> tuple-tuple-tuple-tuple" begin
a,b,c,d = read(f, (Complex64,a1), (Int64,b1), (Float64,c1,c2), (Complex64,d1));
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

@testset "<2> array-tuple-tuple-tuple" begin
a,b,c,d = read(f, Array{Complex64}(a1), (Int64,b1), (Float64,c1,c2), (Complex64,d1));
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

@testset "<3a> tuple-array-tuple(flat)-tuple" begin
a,b,c,d = read(f, (Complex64,a1), Array{Int64}(b1), (Float64,c1*c2), (Complex64,d1));
@test a==aa
@test b==bb
@test vec(c)==vec(cc)
@test d==dd
rewind(f)
end

@testset "<3b> tuple-array-tuple-tuple unraveled" begin
rec = FortranFiles.Record(f)
specs = ( (Complex64,a1), Array{Int64}(b1), (Float64,c1,c2), (Complex64,d1) )
data = map( spec->FortranFiles.read_spec(rec,spec), specs )
close(rec)
a,b,c,d = data
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

@testset "<3c> tuple-array-tuple-tuple" begin
a,b,c,d = read(f, (Complex64,a1), Array{Int64}(b1), (Float64,c1,c2), (Complex64,d1));
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

@testset "<4> tuple-tuple-array-tuple" begin
a,b,c,d = read(f, (Complex64,a1), (Int64,b1), Array{Float64}(c1,c2), (Complex64,d1));
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

@testset "<5> tuple-tuple-tuple-array" begin
a,b,c,d = read(f, (Complex64,a1), (Int64,b1), (Float64,c1,c2), Array{Complex64}(d1));
@test a==aa
@test b==bb
@test c==cc
@test d==dd
rewind(f)
end

# done
close(f)
```

[nasty.zip](https://github.com/JuliaLang/julia/files/904839/nasty.zip)

**Comment by traktofon** [comment]
Update: I found a better test case, which narrows down the problem. Please see the test script and data in the attached file. Most notably, for this test case, it even fails if I uncomment the `println`s. The first test case already fails, which is:
```julia
a,b,c,d = read(f, (Int16,a1), (Float64,b1,b2,b3), (Int8,c1,c2,c3), (Float32,d1))
```
and the test output with the `println` enabled (plus printing the datatype) yields:
```
BEFORE map! (Float64) -1.3206112457504978e-236
AFTER map! -1.3206112457504978e-236
BEFORE map! (Int8) -28
AFTER map! -28
BEFORE map! (Float32) 9.379797e36
AFTER map! 9.379797e36
BEFORE map! (Int16) 8128
AFTER map! 8128
<1> tuple-tuple-tuple-tuple: Test Failed
[...]
```

Note the datatype of the elements printed out: the order is Float64, Int8, Float32, Int16. But it should be Int16, Float64, Int8, Float32. So it looks like the order in which [this map call](https://github.com/traktofon/FortranFiles.jl/blob/convert/src/read.jl#L37) processes its arguments is... weird (looks like circularly shifted).

**Concrete question:** is the order in which `map(f,list)` processes the elements of `list` defined at all?

[nasty3.zip](https://github.com/JuliaLang/julia/files/905347/nasty3.zip)

**Comment by yuyichao** [comment]
Whether is it define or not, the inference seems to be reordering the evaluation in
```julia
map2(f, t::Tuple{Any, Any, Any}) = (f(t[1]), f(t[2]), f(t[3]))
@inline map2(f, t::Tuple)                = ((f(t[1]), map2(f,Base.tail(t))...))
```

**Comment by yuyichao** [comment]
Standalone repro

```julia
using Base.Test

data = UInt8[0x50, 0x00, 0x00, 0x00, 0xd2, 0xeb, 0x23, 0x3f, 0x32, 0xc1, 0x6b, 0x3f, 0x84, 0xe1, 0x0d, 0x3f, 0xc4, 0x94, 0xa2, 0x3e, 0x0a, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xef, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x4c, 0x19, 0x64, 0x02, 0x6c, 0xd4, 0x3f, 0xce, 0x92, 0x64, 0xd7, 0x08, 0x0e, 0xe4, 0x3f, 0x78, 0x6f, 0xaa, 0x3b, 0xc3, 0x73, 0xc3, 0x3f, 0x74, 0x01, 0x77, 0x6c, 0x19, 0xa8, 0xdd, 0x3f, 0xc8, 0x12, 0x3f, 0x3f, 0xcc, 0x22, 0x82, 0x3e, 0x74, 0x53, 0xd2, 0x3e, 0x80, 0x67, 0xba, 0x3c, 0x50, 0x00, 0x00, 0x00]

f = IOBuffer(data)

read(f, Int32)
aa = read(f, Complex64, 2)

@noinline pr(spec::ANY) = (@show spec; @show typeof(spec))

@noinline function read_spec{T,N}(rec, spec::Array{T,N})
    read!(rec, spec)
    return spec
end

@noinline function read_spec{I<:Integer}(rec, spec::Tuple{DataType,I})
    T,n = spec
    read_spec(rec, Array{T}(n))
end

@noinline map2(f, t::Tuple{Any, Any, Any}) = (f(t[1]), f(t[2]), f(t[3]))
@inline map2(f, t::Tuple)                = ((f(t[1]), map2(f,Base.tail(t))...))

function read2(rec)
    specs = (Complex64, 2), (Int64, 2), (Int64, 4), Array{Complex64}(2)
    cb = function (spec)
        read_spec(rec, spec)
    end
    data = map2(cb, specs)
    return data[1]
end

f = IOBuffer(data)
read(f, Int32)
a = read2(f)
@test a == aa
```

Make `@noinline map2(f, t::Tuple{Any, Any, Any}) = (f(t[1]), f(t[2]), f(t[3]))` inline can make the issue go away.

**Comment by tkelman** [comment]
Thank you @traktofon for the very detailed bug report here!

**Comment by traktofon** [comment]
Thank you @yuyichao for the analysis and @JeffBezanson for the quick bugfix! I can confirm that my tests all pass with the current nightly build (b3a5100).
