### ISSUE TITLE
lfact(x) incorrectly evaluates to 0 for negative x

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#21318]
`lfact(x)`, the logarithmic factorial of `x`, gives the wrong answers for negative values of `x`.

Consider for example (-3)! = Γ(-2). Computing `factorial(-3)` raises a `DomainError`, as does `gamma(-2)`. However, `exp(lfact(-3)) == 1.0`, which is wrong:

```jl
julia> lfact(-3)
0.0

julia> exp(lfact(-3)) # = (-3)! = Γ(-2)
1.0

julia> factorial(-3)
ERROR: DomainError:
Stacktrace:
 [1] factorial_lookup(::Int64, ::Array{Int64,1}, ::Int64) at ./combinatorics.jl:30
 [2] factorial(::Int64) at ./combinatorics.jl:39

julia> gamma(-2.0)
ERROR: DomainError:
Stacktrace:
 [1] nan_dom_err at ./math.jl:299 [inlined]
 [2] gamma(::Float64) at ./special/gamma.jl:3
```

The fix should be a simple correction to the one-line definition:

```jl
lfact(x::Real) = (x<=1 ? zero(float(x)) : lgamma(x+oneunit(x)))
```

(also the domain of `lfact` is wrong - it should be consistent with `factorial`.)

**Comment by ararslan** [comment]
Note that restricting the domain to match that of `factorial` is technically a breaking change, though I agree it should happen (after 0.6).

**Comment by StefanKarpinski** [comment]
I would argue that the current behavior is a bug and should be fixed now.

**Comment by ararslan** [comment]
In that case, PR submitted. 😉
