### ISSUE TITLE
filter is deprecated, but does not give a deprecation warning

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#21334]
Using `filter` gives no deprecation warning:
```
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.83 (2017-04-08 21:57 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 965c938eb* (0 days old master)
|__/                   |  x86_64-apple-darwin16.0.0

julia> v = [1, 2, 3, 4, 5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> filter(x->x>3, v)
2-element Array{Int64,1}:
 4
 5
```

**Comment by yuyichao** [comment]
I don't think it's deprecated.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/pull/18839#issue-181774322

> - I separated `Base.filter` and `IterTools.filter` into two functions (since the latter is lazy and the former is eager). This is up for debate.

**Comment by dpsanders** [comment]
As far as I understand, `filter` was moved to `Iterators.filter`:

https://github.com/JuliaLang/julia/blob/master/base/deprecated.jl#L383

**Comment by yuyichao** [comment]
See my comment above. `Base.filter` and `Iterators.filter` (`IterTools.filter` in the first version of the linked PR) are two different functions. The deprecation was only added so that the separated function can still be used from `Base.filter` with a depwarn. Other methods are **NOT** deprecated.

**Comment by dpsanders** [comment]
OK thanks.
