### ISSUE TITLE
Delete max collection interval lower bound

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#21333]
Currently julia has a heap size lower bound of 1.1GiB. That's too much on some machines. Remove that lower bound and always let it figure out how much heap it has based on total memory/number of cores.

**Comment by oscardssmith** [comment]
I think this doesn't still exist.

**Comment by vtjnash** [comment]
max_collect_interval is still 1.192 GB, and thus still too large

**Comment by d-netto** [comment]
I believe we're no longer using these interval based heuristics on master.

Good to close?
