### ISSUE TITLE
Base.DATAROOTDIR file separator on windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#21330]
Base.DATAROOTDIR  shows up as
` "./share" `  on Windows and not `".\\share"`

**Comment by nalimilan** [comment]
I think this issue has been reported already, but I can't find it. The path is computed by the `relative_path.sh` script, which would need some tweaks to be correct on Windows. I guess that also affects other paths stored in `base/build_h.jl`?

**Comment by musm** [comment]
btw which file are you referring to I can't find a `base/build_h.jl`?

**Comment by nalimilan** [comment]
That file is generated during the build.

**Comment by musm** [comment]
Ok thanks, yep looks the others will need the same fix
```julia
# This file is automatically generated in base/Makefile
const MACHINE = "x86_64-w64-mingw32"
const libm_name = "libopenlibm"
const libblas_name = "libopenblas64_"
const liblapack_name = "libopenblas64_"
const USE_BLAS64 = true
const USE_GPL_LIBS = true
const libfftw_name = "libfftw3"
const libfftwf_name = "libfftw3f"
const libllvm_version = "3.9.1"
const VERSION_STRING = "0.6.0-pre.beta"
const TAGGED_RELEASE_BANNER = "Official http://julialang.org/ release"
const SYSCONFDIR = "../etc"
const DATAROOTDIR = "../share"
const DOCDIR = "../share/doc/julia"
const LIBDIR = "../lib"
const PRIVATE_LIBDIR = "../lib/julia"
const INCLUDEDIR = "../include"
```

**Comment by musm** [comment]
So I have been trying to fix this but run into the following issue

suppose we have replaced `/` to `\\`  so that in the makefile we have
`echo "const SYSCONFDIR = \"c\\mnt\\hello\\julia\"" > test`
now if you check the file `test`  you will see `const SYSCONFDIR = "c\mnt\hello\juliz"` 
that is, `make` has swallowed the backslashes. I have tried multiple ways to try and fix this swallowing but have come up short. 

For reference see: https://github.com/musm/julia/pull/4/files
