### ISSUE TITLE
include doesn't recognize '~' as home directory

### ISSUE THREAD

**Issue by m-j-w** [JuliaLang/julia#21337]
On Linux, using today's master, including a file using tilde as first character is not recognized as a file below the user home directory:
```jl
julia> include("~/test.jl")
ERROR: could not open file /home/mjw/src/julia-master/~/test.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
julia> pwd()
"/home/mjw/src/julia-master"
```

**Comment by m-j-w** [comment]
A possible fix might be to add `expanduser` to https://github.com/JuliaLang/julia/blob/master/base/sysimg.jl#L7-L17 where not in the first include state:
```jl
function include(path::AbstractString)
    local result
    if INCLUDE_STATE === 1
        result = Core.include(path)
    elseif INCLUDE_STATE === 2
        result = _include(expanduser(path))
    elseif INCLUDE_STATE === 3
        result = include_from_node1(expanduser(path))
    end
    result
end
```
giving
```jl
julia> include("~/test.jl")
ERROR: could not open file /home/mjw/test.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
```

If this is indeed a feasible fix I could make a PR.

**Comment by yuyichao** [comment]
No functions implicitly treat `~` as home directory. Doing that for low level functions will cause many unwanted corner cases.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/1136. AFAICT this is a shell thing so doing that in shell mode/command literal might make sense but doing it for other low level interfaces doesn't make sense.
