### ISSUE TITLE
Feature request: modeling concurrency

### ISSUE THREAD

**Issue by venkat-sreenivas** [JuliaLang/julia#21349]
Hi

I am just starting with Julia and would like to model concurrency as in digital circuits. A trivial example would be to model a 3 bit counter and see its output in a waveform viewer.

A more evolved example would be to use the MSB of the 3 bit counter above to enable a slower 2 bit counter.

How do I go about this?

Thanks,
Venkat Sreenivas

**Comment by yuyichao** [comment]
This is more likely a feature that belongs to a package. If you need any help developping/finding one please use discourse.julialang.org instead.
