### ISSUE TITLE
jl_type_morespecific returns false for identical types

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#21352]
Even though the dev docs state that it should be true for identical types, `jl_type_morespecific` returns false on the master branch, while on 0.5 it returns true. I believe this is because of the ordering of these lines:
https://github.com/JuliaLang/julia/blob/master/src/subtype.c#L2489-L2490

**Comment by JeffBezanson** [comment]
This change is intentional; I'll update the dev docs. When two types have a specificity ordering, I think it makes more sense for it to be strict.

**Comment by barche** [comment]
Indeed, makes sense, thanks!
