### ISSUE TITLE
`math-mode=fast` is too aggressive

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#21375]
I know it implies that computations aren't supposed to have NaNs in them. However, NaN is frequently used as a placeholder value in storage. I feel like just looking at them with `isnan` should be safe, as long as we're not computing on them. However:
```
julia> NaN
2.696539702293474e308

julia> isnan(NaN)
true

julia> x = NaN
2.696539702293474e308

julia> isnan(x)
true

julia> f(x) = !isnan(x)
f (generic function with 1 method)

julia> f(x)
true
```

**Comment by vtjnash** [comment]
All of those examples are doing substantial computation on them.

**Comment by Keno** [comment]
You mean, in showing them?

**Comment by vtjnash** [comment]
Asking `isnan` correctly is computationally expensive and slow

**Comment by oscardssmith** [comment]
We've killed `math-mode=fast`
