### ISSUE TITLE
Sparse-sparse matrix multiplication 4x slower on 0.5 than 0.4, 6x slower on master

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#21370]
Test code:
```
$ cat compare.jl
using BenchmarkTools
testfile = "amazon0302"
if !isfile("$(testfile)_inc.tsv")
    download("https://graphchallenge.s3.amazonaws.com/snap/$testfile/$(testfile)_inc.tsv",
        "$(testfile)_inc.tsv")
end
ii = readdlm("$(testfile)_inc.tsv", '\t', Int64)
E = sparse(ii[:,1], ii[:,2], ii[:,3])
@show VERSION
display(@benchmark E'*E)
println()

$ for v in 0.4 0.5 0.6; do ~/Julia/julia-$v/julia compare.jl; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.5M  100 26.5M    0     0  14.3M      0  0:00:01  0:00:01 --:--:-- 14.3M
VERSION = v"0.4.8-pre+3"
BenchmarkTools.Trial:
  memory estimate:  662.97 MiB
  allocs estimate:  4497172
  --------------
  minimum time:     1.231 s (0.00% GC)
  median time:      1.255 s (1.43% GC)
  mean time:        1.268 s (2.51% GC)
  maximum time:     1.331 s (6.86% GC)
  --------------
  samples:          4
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
VERSION = v"0.5.2-pre+1"
BenchmarkTools.Trial:
  memory estimate:  660.97 MiB
  allocs estimate:  2698301
  --------------
  minimum time:     5.189 s (4.54% GC)
  median time:      5.189 s (4.54% GC)
  mean time:        5.189 s (4.54% GC)
  maximum time:     5.189 s (4.54% GC)
  --------------
  samples:          1
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
VERSION = v"0.6.0-pre.beta.121"
BenchmarkTools.Trial:
  memory estimate:  660.97 MiB
  allocs estimate:  2698301
  --------------
  minimum time:     7.657 s (3.10% GC)
  median time:      7.657 s (3.10% GC)
  mean time:        7.657 s (3.10% GC)
  maximum time:     7.657 s (3.10% GC)
  --------------
  samples:          1
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
From looking into the profiles, almost all of the slowdown is from the sorting of the row indices that happens here https://github.com/JuliaLang/julia/blame/c8026a91acd988fbbb08158092a89e111c243965/base/sparse/linalg.jl#L192. Neither `spmatmul` nor `sortSparseMatrixCSC!` (https://github.com/JuliaLang/julia/blame/c8026a91acd988fbbb08158092a89e111c243965/base/sparse/sparsematrix.jl#L3310-L3362) have changed much from 0.4 to 0.5 or 0.5 to now.

**Comment by KristofferC** [comment]
```
julia> Profile.print(noisefloor=2)
1600 ./event.jl:73; (::Base.REPL.##1#2{Base.REPL.REPLBackend})()
 1600 ./REPL.jl:97; macro expansion
  1600 ./REPL.jl:66; eval_user_input(::Any, ::Base.REPL.REPLBackend)
   1600 ./boot.jl:235; eval(::Module, ::Any)
    1600 ./<missing>:?; anonymous
     1600 ./profile.jl:23; macro expansion
      1600 ./sparse/linalg.jl:134; Ac_mul_B(::SparseMatrixCSC{Int64,Int64}, :...
       1450 ./sparse/linalg.jl:192; #spmatmul#54(::Symbol, ::Function, ::Spar...
        1450 ./<missing>:0; (::Base.SparseArrays.#kw##sortSparseMatrix...
         1435 ./sparse/sparsematrix.jl:3350; #sortSparseMatrixCSC!#37(::Symbol, ::Fu...
          1409 ./sort.jl:660; #sortperm!#12(::Base.Sort.QuickSortAlg,...
```

Ref: https://github.com/JuliaLang/julia/issues/939#issuecomment-288758163

**Comment by KristofferC** [comment]
It seems that creating the `Perm` object takes the vast majority of the time.

Adding (using https://github.com/KristofferC/TimerOutputs.jl):
```
@timeit "create ord" begin
  order = ord(lt,by,rev,order)
end
@timeit "create perm" begin
  p = Perm(order, v)
end
@timeit "do sort" begin
  sort!(x, alg, p)
end
```

to `sortperm!` gives (with a loop):

```
 Section       ncalls     time   %tot     avg
 ────────────────────────────────────────────
 create perm       50   1.14ms  97.5%  22.8μs
 do sort           50   21.0μs  1.80%   420ns
 create ord        50   8.27μs  0.71%   165ns
 ────────────────────────────────────────────
```

**Comment by KristofferC** [comment]
Reduced to:

```
using BenchmarkTools

function _sortperm!(v::AbstractVector;
                   lt=isless,
                   by=identity,
                   rev::Bool=false,
                   order::Base.Ordering=Base.Order.Forward)
        order = Base.Order.ord(lt,by,rev,order)
        p = Base.Order.Perm(order, v)
end

v = rand(12)
@btime _sortperm!($v)
```

0.6: `14.255 μs (1 allocation: 16 bytes)`
0.5: `5.316 μs (1 allocation: 16 bytes)`

**Comment by martinholters** [comment]
With that benchmark, I also get:
0.6:  11.105 μs 
0.5:   5.36 μs
0.4: 648.852 ns

**Comment by fredrikekre** [comment]
From https://github.com/JuliaLang/julia/pull/20993 (benchmarking 0.6 vs 0.5):

| `["sort","insertionsort",("sort forwards","ascending")]` | 1.59 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sort! forwards","ascending")]` | 2.48 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm forwards","ascending")]` | 1.51 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm forwards","descending")]` | 1.42 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm forwards","random")]` | 1.41 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm reverse","ascending")]` | 1.42 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm reverse","random")]` | 1.41 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm! forwards","descending")]` | 1.42 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm! forwards","random")]` | 1.41 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm! reverse","ascending")]` | 1.42 (30%) :x: | 1.00 (1%)  |
| `["sort","insertionsort",("sortperm! reverse","random")]` | 1.41 (30%) :x: | 1.00 (1%)  |
| `["sort","issorted",("reverse","ascending")]` | 1.34 (30%) :x: | 1.00 (1%)  |
| `["sort","issorted",("reverse","random")]` | 1.35 (30%) :x: | 1.00 (1%)  |
| `["sort","quicksort",("sortperm forwards","ascending")]` | 1.36 (30%) :x: | 1.00 (1%)  |
| `["sort","quicksort",("sortperm forwards","descending")]` | 1.33 (30%) :x: | 1.00 (1%)  |
| `["sort","quicksort",("sortperm! reverse","descending")]` | 1.30 (30%) :x: | 1.00 (1%)  |

**Comment by KristofferC** [comment]
Is that the actual sorting that got slower or just overhead like here?

**Comment by StefanKarpinski** [comment]
We should probably have a dedicated sortperm implementation that doesn't use the same code paths as everything else. I believe can use a linear time sorting algorithm since you know the exact distribution of values.

**Comment by KristofferC** [comment]
While true, it's perhaps not relevant for this issue.

**Comment by jebej** [comment]
That sort of thing is why I wanted to check performance vs 0.4 in #20947

**Comment by tkelman** [comment]
We should add something derived from this to the performance tracking tests. I'll have to familiarize myself with how to structure those if no one beats me to it.

**Comment by RalphAS** [comment]
Although the constructor issue is solved, sparse matmul is still often dominated by sorting, so let me leave a note for future issue-posters or potential push-requesters to consider.
While investigating Julia's sorting schemes, I noticed @JeffBezanson's `Base.Sort.sortperm_int_range`, which is a degenerate form (i.e. stunningly elegant reduction) of radix sort. It seems tailor-made for this use case (post-anticipated by @StefanKarpinski above), but is not invoked because the CSC matrix code uses the pre-allocated `sortperm!` interface. (FWIW my experiments suggest that `sortperm_int_range` is faster than [tuned] traditional radix sort for ranges smaller than about `10^6`.)
