### ISSUE TITLE
Regression in integer mod1 since 0.4

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#21385]
Looking into the regressions from 0.4 in https://github.com/JuliaCI/BaseBenchmarkReports/blob/c95f3559e3e240a271c31e79239d832e75afadb2/5e1cd27_vs_ae26b25/report.md, I noticed that the reason the `query` benchmarks for the `Dates` module got significantly slower was due to `mod1` not inlining anymore:

```jl
julia> using BenchmarkTools

julia> n = now();

julia> @btime Base.Dates.dayofweek($n)
  13.596 ns (0 allocations: 0 bytes)
5

julia> @eval Base @inline mod1{T<:Integer}(x::T, y::T) = mod(x+y-T(1),y)+T(1)
WARNING: Method definition mod1(T<:Integer, T<:Integer) in module Base at operators.jl:644 overwritten at REPL[4]:1.
mod1 (generic function with 3 methods)

julia> @btime Base.Dates.dayofweek($n)
  5.201 ns (0 allocations: 0 bytes)
5
```

Is this an intentional change in the inlining heuristics? `mod1` is a quite simple function. I could just add a PR to inline it but there are a lot of functions there that look very similar so perhaps something more fundamental should be done. Or is this considered not a problem?

**Comment by JeffBezanson** [comment]
It looks like the IR of integer `mod` got bigger in 93bb096d675159917e70266f9edf3d77b5beef28, where the intrinsic implementation was replaced with julia.

**Comment by JeffBezanson** [comment]
It also has a branch that could maybe be replaced with `ifelse`.

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/julia/pull/21409
