### ISSUE TITLE
Missed leaf type canonicalization

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#21400]
The leaf types `Tuple{Int}` and `Tuple{T} where T <: Int` aren't canonicalized to the same thing.

```
julia> Tuple{Int} == (Tuple{T} where T <: Int)
true

julia> Tuple{Int} === (Tuple{T} where T <: Int)
false

julia> Tuple{Int} isa Type{Tuple{T} where T <: Int}
false
```

**Comment by JeffBezanson** [comment]
This was noted in #19998. Also, `isleaftype(Tuple{T} where T <: Int)` is `false`, so this has not been a major issue in practice so far.

**Comment by TotalVerb** [comment]
OK, no point duplicating this issue then.
