### ISSUE TITLE
LaTeX to unicode not working in REPL inside of certain list comprehensions

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#21414]
On master (commit 16d7342) if you do, for instance
```julia
Int[1 for i \in ...
```
The `\in` will not convert to its symbol.  Note that if you do *not* specify the list element type (i.e. with `Int` above), it works just fine.

**Comment by ararslan** [comment]
Looks like this works in 0.3 and 0.4 but was broken in 0.5. (And clearly the breakage persists.)

**Comment by nsmith5** [comment]
Seems to be *any* kind of tab-completion inside of a typed array constructor (best name I can think of...). 

**Examples**
```julia
julia> Float64[\alpha (tab)     # doesn't work
julia> Int[si (tab)             # doesn't work
julia> Symbol[\:smile: (tab)    # doesn't work
julia> [cos (tab)               # works!

cos   cosc   cosd   cosh   cospi
```

**Comment by laborg** [comment]
Can be closed - all of the mentioned examples work.
