### ISSUE TITLE
Drop support for EOLed Windows Vista? Use newer Windows features?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#21424]
I'm not pressing for dropping Vista support. Just FYI, it's EOLed, and maybe newer Win7 has APIs you couldn't (then) use, but wanted to..

I guess e.g. PowerShell can be relied upon now, and I e.g. see open issues https://github.com/JuliaLang/julia/issues/14270 but I guess it's already supported somewhere just conditionally (as it still should do).

There's no hurry dropping Vista, could say unsupported while still works (as of some version). That was done for XP; not sure why that wording was dropped..

I find only a few places that mention Vista, nothing major, only dependencies, e.g.:

https://github.com/JuliaLang/julia/blob/30bf89f3d8e564b588b8e48993e92a551b384f2c/contrib/windows/julia-manifest.xml

**Comment by vtjnash** [comment]
Yes, we should update the docs. The last version to support Vista was v0.6 – we haven't supported Vista on master for some months now (http://releases.llvm.org/3.8.1/docs/ReleaseNotes.html).

**Comment by tkelman** [comment]
docs and website say 7
