### ISSUE TITLE
Crash when using IO from finalizer inside Task

### ISSUE THREAD

**Issue by turtleslow** [JuliaLang/julia#21442]
A finalizer which uses print() was called from a Task that was created with @async, resulting in a crash with the following errors:

```
error in running finalizer: ErrorException("task switch not allowed from inside gc finalizer")
error in running finalizer: ErrorException("schedule: Task not runnable")

WARNING: Workqueue inconsistency detected: shift!(Workqueue).state != :queued
ERROR (unhandled task failure): schedule: Task not runnable
 in enq_work(::Task) at ./event.jl:77
 in yield at ./event.jl:126 [inlined]
 in macro expansion at ./someFile.jl:234 [inlined]
 in macro expansion at ./util.jl:188 [inlined]
 in macro expansion at ./someFile.jl:123 [inlined]
 in someFunction() at ./task.jl:360

fatal: error thrown and no exception handler available.
InterruptException()
jl_run_once at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/jl_uv.c:142
process_events at ./libuv.jl:82
wait at ./event.jl:147
task_done_hook at ./task.jl:191
unknown function (ip: 0x7fce8ba564e2)
jl_call_method_internal at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/julia_internal.h:210 [inlined]
jl_apply_generic at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/gf.c:1950
jl_apply at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/julia.h:1392 [inlined]
finish_task at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/task.c:215 [inlined]
start_task at /home/abuild/rpmbuild/BUILD/julia-0.5.1/src/task.c:262
unknown function (ip: 0xffffffffffffffff)
```

**Comment by JeffBezanson** [comment]
The error is correct; task switches (which includes most I/O) are not allowed in finalizers.

**Comment by JeffBezanson** [comment]
One workaround is to `@schedule` the I/O operation from the finalizer, instead of doing it in the finalizer itself.

**Comment by StefanKarpinski** [comment]
Can we make it so that all task switches invoked from finalizers automatically schedule the task instead of trying to run inside the finalizer? Wouldn't that typically have the desired effect?

**Comment by vtjnash** [comment]
that's possible, but it would mean wrapping all finalizers in a Task

**Comment by StefanKarpinski** [comment]
Would it be possible to do it lazily at the time when the finalizer tries to do the switch?

**Comment by StefanKarpinski** [comment]
Otherwise, it seems fine to just improve the error message here.

**Comment by StefanKarpinski** [comment]
Ok, in that case, let's just improve the error message to make it clear what the problem is – i.e. that you cannot do I/O or any other task switching from a finalizer, and maybe some kind of bread crumb to how to explicitly schedule a new task from a finalizer.

**Comment by turtleslow** [comment]
Thanks for the tip using `@schedule`.

The above error appeared to place me in a state where the REPL would no longer evaluate what I was typing.  The following seems to place me in the same state:
```
t = @schedule try
    while true; sleep(1); end
end

Base.throwto(t,InterruptException())
```
After this, it seems like the only thing I could do is hit Ctrl-C, which causes Julia to terminate.  Is that the expected behavior?  (I'm using 0.5.1)
