### ISSUE TITLE
+(x::T,y::T) where {T} not parsing correctly 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#21440]
Not sure if this is expected or not but the following declaration does not parse 
`+(x::T,y::T) where {T} = #`

whereas this correctly does
`+{T}(x::T,y::T) = #`

I know it  works if you use parenthesis, but there seems to be an inconsistency when there is no parens.

**Comment by TotalVerb** [comment]
The version without parentheses should in my opinion be disallowed. `+(1, 2)` still looks like a unary operator applied to a tuple.

**Comment by sclereid** [comment]
`(+)(1, 2)` or `(+(1, 2))` still likes a unary operator applied to a tuple, though.

**Comment by TotalVerb** [comment]
`(+(1, 2))` does, but `(+)(1, 2)` is fine.
