### ISSUE TITLE
`cond(F)` is not implemented for lufact return type

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#21453]
[The documentation for `lufact`](https://github.com/JuliaLang/julia/blob/8b2ee7126cc293893aae9acceb102fa766ccc6bf/base/linalg/lu.jl#L115) claims the returned factorization type implements `cond()`, but it does not:

    julia> cond(lufact([1 0; 0 -1]))
    ERROR: MethodError: no method matching cond(::Base.LinAlg.LU{Float64,Array{Float64,2}})

A similar issue exists in [base/sparse/umfpack.jl](https://github.com/JuliaLang/julia/blob/8b2ee7126cc293893aae9acceb102fa766ccc6bf/base/sparse/umfpack.jl#L131).

I believe these methods should be implemented (otherwise the doc should be changed).

**Comment by garrison** [comment]
Actually, this seems to be implemented; I'm not sure why https://github.com/JuliaLang/julia/blob/8b2ee7126cc293893aae9acceb102fa766ccc6bf/base/linalg/lu.jl#L312-L314 is not being called.

**Comment by andreasnoack** [comment]
I think the documentation is right since `cond` is implemented. I'm not sure how the table in the documentation could be improved and I don't think it makes sense to implement the `p=2` version for `LU` since such a method would have to recreate the original matrix. Right now, `p=2` is wrong and returns `p=Inf`. Do you think the table can be improved?

**Comment by garrison** [comment]
> Right now, p=2 is wrong and returns p=Inf.

To clarify: I think `p=2` is wrong (not sure what it returns, but it is not the same result as `p=Inf`).  On the other hand, passing `p=Inf` does indeed give the correct result.

> Do you think the table can be improved?

I think the table is fine as it is, but I think it would make sense to add a docstring for a second form of `cond()`, which takes an `LU` object as the first argument and which does not list a default `p` for the second argument.  (The first form is [here](https://github.com/JuliaLang/julia/blob/a2c1e333772c9ce03df2babc78c3c9f7e1056c89/base/linalg/dense.jl#L853-L858).)

**Comment by andreasnoack** [comment]
> On the other hand, passing p=Inf does indeed give the correct result.

[This line](https://github.com/JuliaLang/julia/blob/8b2ee7126cc293893aae9acceb102fa766ccc6bf/base/linalg/lu.jl#L313) is pretty broken. It asks LAPACK for the Inf norm condition number estimate but it passes the two norm of the input. This is why `1`, `2`, and `Inf` give different results. We should error if `p != 1 && p != Inf`.

> but I think it would make sense to add a docstring for a second form

Sounds like the right solution.

**Comment by garrison** [comment]
And actually, I think `inv()` should be added to the table as well.  It is mentioned in the docstrings for `bkfact`, `cholfact`, and `eigfact`.  But `lufact`, `ldltfact`, and `qrfact` currently neglect to mention it.

**Comment by andreasnoack** [comment]
I decided to take a different approach. See #21577. @garrison It would be great if you could open a PR with the doc changes.
