### ISSUE TITLE
Make sure NEWS.md lists all 0.6 deprecations and breaking changes

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#21475]
Reviewing the checklist I had in https://github.com/JuliaLang/julia/issues/17418 for the 0.5 release, pretty much the only thing we're missing for an 0.6 RC ~~(other than #21470)~~ is doing a final pass over NEWS.md and making sure all the deprecations and breaking changes that should be listed there are.

Check https://github.com/JuliaLang/julia/issues?utf8=%E2%9C%93&q=label%3Anews and https://github.com/JuliaLang/julia/issues?utf8=%E2%9C%93&q=label%3Adeprecation and https://github.com/JuliaLang/julia/blob/release-0.6/base/deprecated.jl#L117-L1325, make sure everything is listed.

**Comment by tkelman** [comment]
specific examples that had the news label, not yet mentioned in news (not a complete list)
- [ ] #19771
- [ ] #19779
- [ ] #18444
- [ ] #19901
- [ ] #19900
- [ ] #17155
- [ ] #10946
- [ ] #19786
- [ ] #19636
- [ ] #15850 
- [ ] #19811
- [ ] #12274
- [ ] #19594

**Comment by Sacha0** [comment]
My pleasure, thank you for the kind words, and thank you for reviewing! :)

**Comment by Sacha0** [comment]
I culled the set of closed pull requests labeled `news` to those still absent from `NEWS.md`. The following such pull requests remain in need of attention:
- [ ] #20345
- [ ] #20248
- [ ] #18342
- [ ] #18159
- [ ] #17439 ?
- [ ] #12807

**Comment by tkelman** [comment]
we should maybe rename the label to needs-news then if we're going to use it as a state tracker and remove it once added

**Comment by tkelman** [comment]
#17439 was 0.5, #12807 is 0.7

**Comment by Sacha0** [comment]
> #17439 was 0.5, #12807 is 0.7

Updated --- thanks! :)

**Comment by Sacha0** [comment]
The above pull requests should cover news for all closed pull requests labeled `deprecation` that remain in need of attention, excepting the following `LibGit2`-related pull requests that I am not certain what to do with immediately
- [ ] #20435 
- [ ] #20135 
- [ ] #19935 
- [ ] #19878

**Comment by Sacha0** [comment]
The above pull requests should cover news for all items in `base/deprecated.jl`, less
- [ ] #19730 
- [ ] #20952 ?
and the libgit2-refactor-related
- [ ] #20435 
- [ ] #20135 
- [ ] #19935 
- [ ] #19878 
- [ ] #19660
