### ISSUE TITLE
Printing and parsing BigFloats depends on locale

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#21494]
In Italian comma is the decimal separator, if I set locale to `"it_IT.UTF-8"` by `ccall`-ing `setlocale` then `BigFloat` are represented and parsed with a comma as decimal separator:
```julia
julia> big"1.0"
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> big"1,0"
ERROR: ArgumentError: invalid number format 1,0 for BigInt or BigFloat

julia> ccall((:setlocale, "libc"), Cstring, (Cint, Cstring), 1, "it_IT.UTF-8")
Cstring(0x0000564d300353b0)

julia> big"1.0"
1,000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> big"1,0"
1,000000000000000000000000000000000000000000000000000000000000000000000000000000
```

As [pointed out](https://github.com/JuliaGraphics/Gtk.jl/issues/308#issuecomment-296372379) by @yuyichao the first argument of `setlocale` depends on the system you're running (1 on GNU/Linux, 0 on macOS should work).

**Comment by yuyichao** [comment]
Also requires enabling corresponding settings in libc (at least on linux).

**Comment by vtjnash** [comment]
dup #7167
