### ISSUE TITLE
A function gets executes several times while being only called once

### ISSUE THREAD

**Issue by fjarri** [JuliaLang/julia#21518]
Consider the following code:

    function inner(; kw=nothing)
        println("in inner()")
    end

    function get_inner()
        println("in get_inner()")
        inner
    end

    function test1()
        f = get_inner()
        f(kw=1)
    end

    function test2()
        get_inner()(kw=1)
    end

    function test3()
        get_inner()(; :kw => 1)
    end

    println("test1:")
    test1()
    println("test2:")
    test2()
    println("test3:")
    test3()

In each of the `test` functions I would expect `get_inner()` to be only called once. Yet the output I get is 

    test1:
    in get_inner()
    in inner()
    test2:
    in get_inner()
    in get_inner()
    in inner()
    test3:
    in get_inner()
    in get_inner()
    in get_inner()
    in inner()

Is it some peculiarity of Julia syntax, or a bug?

`versioninfo()` output:

    Julia Version 0.5.1
    Commit 6445c82 (2017-03-05 13:25 UTC)
    Platform Info:
      OS: macOS (x86_64-apple-darwin13.4.0)
      CPU: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

**Comment by martinholters** [comment]
Also present on current master (but for `test3`, `get_inner` is only called twice). Seems to be a lowering issue:
```julia
julia> expand(:(get_inner()(kw=1)))
:(((Core.kwfunc)(get_inner()))((Base.vector_any)(:kw, 1), get_inner()))
```
AFAIU, the expression yielding the function to be called would need to be evaluated once with the result being stored in an `SSAValue` instead of evaluating it twice.
