### ISSUE TITLE
findin function is not working for string is confusing.

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaLang/julia#21512]
I was analyzing data which has mostly same column order, but rarely different like this
``` xml
<id>1</id><data>something...</data>
 <id>2</id><data>something...</data>
 ......
<data>something...</data><id>495</id>
```

so I thought I can use `findin` for indices of column names. by reading a tooltip 
>findin(a, b)
>Returns the indices of elements in collection `a` that appear in collection `b`.

and `findin` function seems to return indices of column names as I expected it to be.

After experiencing some data jumbles, I realized that I cannot use `findin` for finding indices of string vector. which is completely my fault because I didn't read usecases included within tooltip nor examined methods of `findin` 

But I think it can be confusing to beginners like myself. so updating tooltip to something like this might help.

>findin(a, b)
>Returns the indices of elements in collection `a` that appear in collection `b`. only works for real number, finding string indices is not supported.

Thanks.

**Comment by yuyichao** [comment]
It is certainly not limited to real numbers (or even numbers fwiw). It works for strings on both 0.4 and 0.5, what doesn't work?

```julia
julia> findin("abcdefg", "ab")
2-element Array{Int64,1}:
 1
 2
```

**Comment by YongHee-Kim** [comment]
I was using `findin` for something like this.
``` julia
findin(["aa","bb","cc"], ["cc", "aa"])
2-element Array{Int64,1}:
 1
 3
```
which I was expecting it to be `[3, 1]` but I just realized that this behavior is same for integers as well.
` findin([1,2,3], [3, 1]) => [1,3]`Bbecause all of the integers in my data was sorted. I should not have used `findn` in the first place. 😅 

`map(x->findfirst(ref_array, x), myarray)` is what I needed 

Thanks for taking your time to review my issue.

**Comment by yuyichao** [comment]
So AFAICT there isn't any issue left. Please use discourse.julialang.org for more questions. Also please be consistent on `findin` vs `findn`.............
