### ISSUE TITLE
typeassert: Expected Type, got TypeVar with ANY keyword argument

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#21510]
When a keyword argument is declared with `ANY` type, things don't work:

```julia
julia> foo(; a::ANY = Union{}) = a
foo (generic function with 1 method)

julia> foo(a=Union{})
ERROR: TypeError: typeassert: expected Type, got TypeVar
Stacktrace:
 [1] (::#kw##foo)(::Array{Any,1}, ::#foo) at ./<missing>:0
```

This may or may not be a problem (possibly it's intentional?); but if not, then the definition of `Base.summarysize` should be fixed.

```julia
function summarysize(obj::ANY;
                     exclude::ANY = Union{DataType, TypeName, Method},
                     chargeall::ANY = Union{TypeMapEntry, Core.MethodInstance})
```

**Comment by clouds56** [comment]
It's not mentioned in document, what's the difference between `ANY` and `Any` when occurs in parameter list?
Only thing I know is `Any` is a DataType while `ANY` is a TypeVar (it seems `ANY` should not be used in parameter list)?

**Comment by KristofferC** [comment]
`ANY` is removed. It is now `@nospecialize`.

**Comment by StefanKarpinski** [comment]
It was a hint to the compiler not to specialize the argument. The new `@nospecialize` annotation lets you convey the same thing, but still use a type besides `Any`, which is more flexible.
