### ISSUE TITLE
The devdocs page for functions is outdated

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#21532]
Currently devdocs/functions.md refers to `inference0` when talking about the bootstrap process, and @tkelman pointed out that `inference0` isn't a thing anymore. It would be great if someone could correct the description there.

**Comment by morrme** [comment]
what does it need to be changed to?

**Comment by ararslan** [comment]
I don't know, otherwise I would have made the change myself 😄

**Comment by ararslan** [comment]
The references to `inference0` appear to have been removed in #21933.
