### ISSUE TITLE
Prompt reply color is broken on powershell and cmd/powershell colors are too dark

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#21531]
As a result from changing to the use of  non bold colors.

I think we should rethink not using bold by default, in this case, as the best middle ground that isn't terrible for everyone.

powershell (have not changed from default color profile)
![image](https://cloud.githubusercontent.com/assets/4319522/25355418/9e41fd66-2904-11e7-96f6-a9c504dc4af3.png)

also for reference here are the colors on command prompt
![image](https://cloud.githubusercontent.com/assets/4319522/25355445/b620d1aa-2904-11e7-977f-4a72f0f19462.png)

On 0.6

![image](https://cloud.githubusercontent.com/assets/4319522/25356533/71d9fea0-2908-11e7-8117-d072975fc62e.png)

![image](https://cloud.githubusercontent.com/assets/4319522/25356547/8229fd5a-2908-11e7-9cf7-5479fd5f0523.png)

On 0.5
![image](https://cloud.githubusercontent.com/assets/4319522/25356703/35047ee6-2909-11e7-8b02-0fd124f4ae3f.png)

**Comment by KristofferC** [comment]
Can you do the `test_system_colors()` test in Powershell?

**Comment by musm** [comment]
![image](https://cloud.githubusercontent.com/assets/4319522/25356402/0c26e47e-2908-11e7-80c6-c17e51a0b543.png)

![image](https://cloud.githubusercontent.com/assets/4319522/25356412/10b95c92-2908-11e7-9fcf-363354d3f313.png)

**Comment by KristofferC** [comment]
So is it the switch from bold -> non bold that it can't handle?

Try something like 

```
using Crayons.Box
print(MAGENTA_FG(BOLD("WARNING:"), " blabla"))
```

**Comment by musm** [comment]
Yes that's the problem. I updated the original post to show a comparison with 0.5.

**Comment by musm** [comment]
I figured out the magenta issue, apparently I had a global env variable to set things to magenta for some reason?

one thing we should avoid using is normal yellow on windows, it simply is gray:
http://stackoverflow.com/questions/21941606/why-does-powershell-display-darkyellow-text-improperly
![image](https://cloud.githubusercontent.com/assets/4319522/25365710/83cb712c-2938-11e7-90d2-8dbcbada8cbf.png)

These things could be fixed by having different defaults on windows. Is there a problem with platform specific colors.

**Comment by musm** [comment]
Although that is a powershell specific issue and cmd is not effected....
