### ISSUE TITLE
reverse-i-search at REPL crashes julia for some unicode expressions

### ISSUE THREAD

**Issue by Cody-G** [JuliaLang/julia#21530]
To reproduce, at a Julia 0.5 REPL execute `ϕabc = 3`, then ctrl+r, and then type "ab".  Notice that the crash doesn't happen until you type "b".  Here's the error:

```
WARNING: Caught an exception in the keymap:
ERROR: UnicodeError: invalid character index
ERROR: AssertionError: false
 in mode(::Base.LineEdit.SearchState) at ./LineEdit.jl:1112
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##950#951) at ./REPL.jl:188
 in _start() at ./client.jl:363
```
The error doesn't happen on Julia 0.4. I don't know about Julia 0.6, didn't try it.

`versioninfo()` output:
```
Julia Version 0.5.1
Commit 6445c82* (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

**Comment by yuyichao** [comment]
Seems to be fixed on 0.6 (I thought we had an closed issue about it, couldn't find it)

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/19153

**Comment by yuyichao** [comment]
.... OK so it mentions neither unicode nor crash..............................

**Comment by KristofferC** [comment]
It does have

> julia crashed back to the linux prompt

I just remembered that Tim Holy posted it so I went through his closed issues :P

**Comment by yuyichao** [comment]
So close as dup. I'll leave it to @tkelman to decide about backporting....
