### ISSUE TITLE
triple quotes lose escaped whitespace

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#21542]
```
julia> s = """\n \t where is my newline?"""
"where is my newline?"
```

**Comment by jmkuhn** [comment]
If the escaped newline is replaced by a literal newline, this is behaving as documented.  The line of text is dedented and the newline immediately following the opening triple quote is stripped.  What is the desired behavior here?  Do we want escaped newlines to behave differently than literal newlines?  Do we skip dedenting after an escaped newline?  I like the current behavior of triple quotes including this example.

**Comment by alecloudenback** [comment]
I would expect the behavior in this case to retain the whitespace. Here's the different way this string is treated under different ways of declaring it:

```julia
julia> s = """\n \t where is my newline?"""
"where is my newline?"

julia> print(s)
where is my newline?

julia> q = raw"\n \t where is my newline?"
"\\n \\t where is my newline?"

julia> q = "\n \t where is my newline?"
"\n \t where is my newline?"

julia> print(q)

         where is my newline?
```

If anything I think I would expect the single quotes to trim the whitespace, but the triple quote to retain it. Triple quote feels more literal to me. Especially sine the triple quote retains the non-literal spaces [in the documentation](https://docs.julialang.org/en/latest/manual/strings/#Triple-Quoted-String-Literals-1):

```julia
julia> """    This
         is
           a test"""
"    This\nis\n  a test"
```

**Comment by StefanKarpinski** [comment]
I think it would make sense to retain the escaped `\n`—the indent stripping logic is intended to allow text in `"""` in the middle of indented code to have a matching indent without having that indent end up in the resulting text block. That logic doesn't apply to the `\n` here. This would require changing the order in which string unescaping and unindenting occur: unindenting currently happens after unescaping, it should happen before.

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/35001
