### ISSUE TITLE
isposdef not defined for symmetric matrices

### ISSUE THREAD

**Issue by mcopik** [JuliaLang/julia#21559]
The standard linalg function `isposdef` does not work for symmetric matrices (recent git master):

```
x = rand(5, 5)
x = x*x'
isposdef(x)
isposdef(Symmetric(x))
```

The last line fails with an error:

```
ERROR: MethodError: no method matching isposdef!(::Symmetric{Float64,Array{Float64,2}})
```

which I guess is caused by a missing definition. One workaround is to access underlying matrix directly but it is inconvenient:

```
isposdef(Symmetric(x).data)
```

I think this behavior is not correct and surprising for each user, I have not found any mention of such limitation in the documentation. There is an [additional implementation for Diagonal matrices](https://github.com/JuliaLang/julia/blob/db9709c6f282877f5afe3fd1fef45e0a459b81b0/base/linalg/diagonal.jl#L108) and this works fine:

```
isposdef(Diagonal(rand(1, 5)))
```

**Comment by fredrikekre** [comment]
The same applies for `Hermitian`. Something like this seems to be sufficient (for dense matrices at least):

```julia
isposdef!(A::HermOrSym{<:BlasFloat, <:StridedMatrix}) = ishermitian(A) && LAPACK.potrf!(A.uplo, A.data)[2] == 0
```

mirroring the definitions [here](https://github.com/JuliaLang/julia/blob/98414b9a8bfd0708a03a711cf22f87fd03dd789d/base/linalg/dense.jl#L54) (and [here](https://github.com/JuliaLang/julia/blob/98414b9a8bfd0708a03a711cf22f87fd03dd789d/base/linalg/dense.jl#L33)). I will submit a PR.

**Comment by mcopik** [comment]
@fredrikekre Why is `ishermitian(A)` necessary here? You're just passing a Hermitian/Symmetric matrix, right?

**Comment by fredrikekre** [comment]
For cases like this:

```julia
julia> A = complex.(rand(2, 2), rand(2, 2))
2×2 Array{Complex{Float64},2}:
 0.127036+0.875987im  0.702463+0.796754im
 0.631628+0.488688im  0.214832+0.825713im

julia> ishermitian(Symmetric(A))
false
```

**Comment by mcopik** [comment]
@fredrikekre I see, thanks. I forgot that one can make a complex symmetric matrix.

**Comment by KristofferC** [comment]
Instead of `A.data` shouldn't it be something like `triu(A.data)` (or `tril` depending on the `uplo` char). So "garbage" on the unused side gets ignored?

**Comment by andreasnoack** [comment]
I think the post 0.6 solution should be to store `info` in the `Cholesky` type and delay throwing. That is what we do for `LU` and `BunchKaufman` and then we could just have `isposdef(F::Cholesky) = F.info == 0` and something like `isposdef(A::AbstractMatrix) = ishermitian(A) && isposdef(cholfact(A))`.
