### ISSUE TITLE
Can't specify number of columns to print in Profile.print

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#21557]
According the the  [manual](https://docs.julialang.org/en/stable/manual/profile/)
`Profile.print` should take a kwarg saying how many columns to print.

Here is what happens when I run the example code:

```julia
s = open("/tmp/prof.txt","w")
Profile.print(s,cols = 500)
close(s)

MethodError: no method matching print(::IOStream, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}; cols=500)
you may have intended to import Base.print
Closest candidates are:
  print{T<:Unsigned}(::IO, ::Array{T<:Unsigned,1}, ::Dict{K,V}; format, C, combine, sortedby, maxdepth) at profile.jl:88 got unsupported keyword argument "cols"
  print{T<:Unsigned}(::IO, ::Array{T<:Unsigned,1}) at profile.jl:88 got unsupported keyword argument "cols"
  print(::IO) at profile.jl:88 got unsupported keyword argument "cols"
 in (::Base.Profile.#kw##print)(::Array{Any,1}, ::Base.Profile.#print, ::IOStream, ::Array{UInt64,1}, ::Dict{UInt64,Array{StackFrame,1}}) at <missing>:0
 in (::Base.Profile.#kw##print)(::Array{Any,1}, ::Base.Profile.#print, ::IOStream) at <missing>:0
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
 in (::Atom.##65#68)() at eval.jl:40
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:46
 in macro expansion at eval.jl:109 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
```

Looking in the [source](https://github.com/JuliaLang/julia/blob/98414b9a8bfd0708a03a711cf22f87fd03dd789d/base/profile.jl#L142)
it seems that now the number of columns is being determined by the displaysize.
Which has serveral problems:

 - Doesn't match docs
 - Not at all useful for deeply nestested code. I know my code, which isn't even that deep, is down to just a few letters for each function name, before it is cut-off, which makes it nearly useless
 - displaysize doesn't make sense when the output is not going to STDOUT anyway.

**Comment by yuyichao** [comment]
Removed in https://github.com/JuliaLang/julia/commit/52fecaf2c696160c85c44f389504ae99612ef90f#diff-fa495d378f45bcff3c89b27a8ce8eb02L50

**Comment by yuyichao** [comment]
And dup of https://github.com/JuliaLang/julia/issues/18685

**Comment by oxinabox** [comment]
Not quiet a duplicate.
I want the feature back.
Not just the documentation corrected.

**Comment by yuyichao** [comment]
The feature isn't removed https://github.com/JuliaLang/julia/issues/18685#issuecomment-249718536

**Comment by yuyichao** [comment]
And in any case further discussion should continue there. Adding the old interface back will also be a valid solution to #18685. Which one will be the accepted solution is a different question.
