### ISSUE TITLE
`read(::IO, ::Ref)` should be a method of `read!`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#21592]
This mutates the Ref so should have a `!`.

**Comment by vtjnash** [comment]
Or make it a method of `unsafe_read` instead?

**Comment by JeffBezanson** [comment]
It seems equally safe as `read!` with an array argument, which we also have.

**Comment by vtjnash** [comment]
Except that Ptr <: Ref

**Comment by JeffBezanson** [comment]
Ah yes, that continues to confuse me. I think any operation that can write to a Ptr needs to contain `unsafe_` if at all possible. So I think this should also be split into two methods. All in all I'd like:

- Define `read!(::IO ::RefValue)`.
- Since `unsafe_store!` has a `!`, `unsafe_read` probably should too, so rename to `unsafe_read!`.
- Replace `read(::IO, ::Ref)` with `unsafe_read!(::IO, ::Ptr)`.

This implies that `Ptr` should not really be a subtype of `Ref`, since otherwise any function with a `::Ref` argument needs to have `unsafe` in its name. If we change that, then we can have `read!(::IO, ::Ref)`.

**Comment by vtjnash** [comment]
> otherwise any function with a ::Ref argument needs to have unsafe in its name

only if it then proceeds to call `unsafe` on that argument, in which case, of course? It's not unsafe to have a Ptr, only to load/store it

**Comment by JeffBezanson** [comment]
Yes, that's true. But I don't think you should have to call `unsafe_read!` to safely fill a RefValue. Bottom line, using the same generic function name where some argument cases are safe and others are unsafe is not ideal.
