### ISSUE TITLE
Windows from-scratch build of LLVM broken

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#21621]
I'm tracking down when this broke, it wasn't noticed on appveyor or the buildbots until recently because in normal operation neither of those build LLVM from scratch (they respectively reuse binaries, or a previous build in-place unless manually cleaned out). This blocks the RC and will be needed on master too, so probably should hold off on merging https://github.com/JuliaLang/julia/pull/21610 until this is fixed.

**Comment by tkelman** [comment]
buildbot log: https://build.julialang.org/builders/package_win6.2-x64/builds/217/steps/make/logs/stdio

**Comment by Keno** [comment]
Copy the LLVM dll into usr/tools?

**Comment by tkelman** [comment]
Can you think of any cleaner place to do that than https://github.com/JuliaLang/julia/blob/8eca02717bcea524877fad01aacedc807898bcd1/deps/llvm.mk#L556-L557 ?

Trying https://gist.github.com/09b9c55ec968d7974c019b8f71a9fb95 right now
