### ISSUE TITLE
bits method for BitArrays?

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#21637]
No `bits` method exists for `BitArray`s. Should one? Best!

**Comment by tkelman** [comment]
`Array{Bool}(x)` works, doesn't it? aren't the other `bits` methods defined on scalar values rather than arrays?

**Comment by carlobaldassi** [comment]
Just FYI, there is a (not documented, intended for debugging) function `Base.bitstring`, in show.jl, that could be trivially modified to behave as `bits`:
```
julia-0.5> Base.bitstring(bitrand(154))
"10010111 00110110 11100011 01101010 11001000 01111010 00011100 00011011 : 10110001 10111000 10000010 11100110 01111101 01110111 00101000 10111000 : 10101110 01110101 01000001 01"
```

**Comment by Sacha0** [comment]
> aren't the other bits methods defined on scalar values rather than arrays?

That `bits` is for scalars seems to answer this question, so closing. Thanks! :)

**Comment by JeffBezanson** [comment]
`String(UInt8('0') + bitarray)` also works pretty well.
