### ISSUE TITLE
LibGit2 crash for closed repo

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#21638]
Noticed when debugging https://github.com/JuliaLang/julia/issues/21635 Possibly apply to many other types in libgit2 too since it doesn't seems to be handling this carefully. In particular, it doesn't seem to use proper `ccall` convertions at all and never checks if the pointer is NULL.

```julia
julia> dir = mktempdir()
"/tmp/tmpgtpCG3"

julia> LibGit2.init(dir)
LibGit2.GitRepo("/tmp/tmpgtpCG3")

julia> repo = ans
LibGit2.GitRepo("/tmp/tmpgtpCG3")

julia> close(repo)

julia> repo
LibGit2.GitRepo(julia: /home/yuyichao/projects/archcn/repo/libgit2-julia/src/libgit2-0.25.1/src/repository.c:2007：git_repository_path: 假设 ‘repo’ 失败。
```

**Comment by tkelman** [comment]
what's that say in english locale?

**Comment by yuyichao** [comment]
Assertion failure.

**Comment by yuyichao** [comment]
And this is with a debug build of libgit2 which I used to debug https://github.com/JuliaLang/julia/issues/21635. A release builld just segfault when it tries to load from the NULL pointer.

**Comment by kshyatt** [comment]
Is the problem in the `show` method?

**Comment by yuyichao** [comment]
No, the problem is everywhere in `LibGit2`..... In particular, the direct problem is in some getter functions called by `show`. Though it applies to essentially all `ccall`s in `LibGit2`.

> In particular, it doesn't seem to use proper ccall convertions at all and never checks if the pointer is NULL.
