### ISSUE TITLE
Inconsistent string of datetime

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#21650]
Using string interpolation, the datetime returned by ``now()`` is sometimes shorter than 23 characters. See the codes below for examples. However, if I manually construct a datetime with same value as in the second example, it prints a 23-length string. This is very strange.

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-pre.beta.436 (2017-04-30 05:01 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 46551cd (0 days old master)
|__/                   |  x86_64-pc-linux-gnu

julia> for i=1:100
              a="$(now())"
              length(a)<23 && println(a)
              sleep(rand())
              end
2017-04-30T16:14:28.91
2017-04-30T16:14:31.16
2017-04-30T16:14:34.68
2017-04-30T16:14:37.08
2017-04-30T16:14:41.81
2017-04-30T16:14:41.99
2017-04-30T16:14:46.11
2017-04-30T16:14:46.98
2017-04-30T16:14:47.32
2017-04-30T16:14:52.51
2017-04-30T16:14:53.29
2017-04-30T16:14:54.15
2017-04-30T16:14:58.74
2017-04-30T16:15:05.81

julia> DateTime(2017,4,30,16,14,28,91)
2017-04-30T16:14:28.091
```

**Comment by iamnapo** [comment]
I don't think this has to do with string interpolation, `now()` function. It's just that `DateTime(2017,4,30,16,14,28,910)` prints `2017-04-30T16:14:28.91` instead of `2017-04-30T16:14:28.910`

**Comment by yuyichao** [comment]
If you need a specific format/length. Use [`Dates.format`](https://docs.julialang.org/en/latest/stdlib/dates.html#Base.Dates.format) directly to specify the format you want.

```julia
julia> Dates.format(DateTime(2017,4,30,16,14,28,910), "yyyy-mm-ddTHH:MM:SS.sss")
"2017-04-30T16:14:28.910"
```

Please ask further questions on discourse.julialang.org
