### ISSUE TITLE
Canonical form of an expression

### ISSUE THREAD

**Issue by tehrengruber** [JuliaLang/julia#21663]
When I write macros acting on function expressions I often write a lot of code such that the macro works for different types of declarations. E.g:

```
@some_macro a(x)=1
@some_macro function a(x)
  1
end

# or
@some_macro function a{T <: Float64}(x::T)
  1
end
@some_macro function a(x) where T <: Float64
  1
end
```

Since this leads to a lot of unnecessary macro code it would be nice if there was some sort canonical form in which an expression could be converted to. I could now write a module that does exactly this, but I assume that there is already something under the hood in Base that does the exact some thing.

This issue is meant as a mix of discussion, help request and feature request. I would like to now if this is a common problem for other developers and whether someone has already found a clever way to solve this issue. If this is not the case and there is already some code in Base that could be used for this exact purpose I would be happy to know where it can be found, such that I can try to write something like `canonicalize(::Expr)` because I haven't found something in that regard.

**Comment by jw3126** [comment]
As another point of data, I also have this problem from time to time without a knowing a good solution.

**Comment by vtjnash** [comment]
I believe https://github.com/MikeInnes/MacroTools.jl covers this use case? Anyways, discussion of questions such as this should continue on the discourse site.

**Comment by tehrengruber** [comment]
Thanks for the link. I didn't know https://discourse.julialang.org/. Now I know :-)
