### ISSUE TITLE
`join(STDOUT, [1,2,3,4], ',', '\n')` returns wrong value

### ISSUE THREAD

**Issue by GlenHertz** [JuliaLang/julia#21678]
On 0.6.0-pre.beta.210:

```julia
julia> join(STDOUT, [1,2,3,4], ',', '\n')
1,2,3
4
```

I expect it to return `"1,2,3,4\n"`

**Comment by GlenHertz** [comment]
Ah sorry, I reread the docs and that is the way it is supposed to be.

**Comment by StefanKarpinski** [comment]
I guess this is the downside of making the print method part of the `join` function – it ends up having a somewhat unintuitive return value.

**Comment by GlenHertz** [comment]
Yeah, having the option to print a newline at the end is probably more common than wanting to change the last delimiter.  I can't think of a time where I wanted the last delimiter changed.

**Comment by nalimilan** [comment]
>  I can't think of a time where I wanted the last delimiter changed.

It's very useful when printing list of items in error messages. But it would make sense to make it a keyword argument instead.

**Comment by StefanKarpinski** [comment]
There is an option to print a newline at the end:

```
join(STDOUT, vals); println()
```

**Comment by StefanKarpinski** [comment]
Also I was confused about what you were confused about – you said you expected a different *return value* which I took to mean that you were expecting the function to return the joined string whereas with the IO argument, it returns nothing and instead prints the string. It seems that the nothing return value was not the issue, it was the fact that you can't use `join` as some kind of strange alias for `print`? I guess I don't really see the issue – that's just not what `join` does.
