### ISSUE TITLE
Distributions package unrecognized after installation

### ISSUE THREAD

**Issue by fjhickernell** [JuliaLang/julia#21675]
After installing the Distributions.jl package in JuliaPro, the commands do not seem to be recognized.
![juliaprodistributionsproblem_1](https://cloud.githubusercontent.com/assets/817530/25633898/538592ca-2f3e-11e7-87f4-c9d6b4434dc7.png)
![juliaprodistributionsproblem_2](https://cloud.githubusercontent.com/assets/817530/25633899/539a5322-2f3e-11e7-9477-f78105dd4a23.png)

**Comment by andreasnoack** [comment]
Please ask questions on discourse.julialang.org.
