### ISSUE TITLE
help?> search hangs when searching for "Function"

### ISSUE THREAD

**Issue by jecs** [JuliaLang/julia#21680]
I can search for any other term and get either a hit or a miss. But when I search for "Function", julia hangs. This is on OS X. I installed julia via `brew install julia`. My apologies if this issue has already been fixed.

versioninfo():
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/20904

**Comment by StefanKarpinski** [comment]
Closing as dup. Thanks for the report, @jecs, and the dup reference, @fredrikekre.
