### ISSUE TITLE
Julia 0.5.1 throwing error on Pkg.update()

### ISSUE THREAD

**Issue by udion** [JuliaLang/julia#21698]
I have downloaded Julia 0.5.1 and on doing Pkg.update() I am getting the following error 

~~~
ERROR: unknown package Observables required by WebDisplay
 in requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/query.jl:11
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:477
 in update(::String, ::Set{String}) at ./pkg/entry.jl:458
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#update,Tuple{String,Set{String}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:31
 in update() at ./pkg/pkg.jl:210
~~~

here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/18963158/25712158/7fc90e9e-310e-11e7-8b22-0e4835ec690a.png)

Kindly help me to resolve this

**Comment by tkelman** [comment]
WebDisplay (apparently moved to https://github.com/shashi/WebIO.jl) is not registered and depends on a different unregistered package https://github.com/JuliaGizmos/Observables.jl that you will have to clone manually. Pkg can't handle unregistered dependencies currently.

**Comment by timholy** [comment]
[Discourse](https://discourse.julialang.org/) is also a more appropriate forum for these kinds of questions, because they're not about Julia proper.
