### ISSUE TITLE
Detect nodes going down and reassigning work in @parallel

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#217]
The @parallel for could use some simple fault tolerance, where iterations just get scheduled on other processors if a processor disappears.

This could be simple and easy to do, before we do any fancy database backed stuff.

Assigning to Stephan since he said he wanted to do some compiler stuff. This could possibly qualify..

**Comment by amitmurthy** [comment]
`pmap` does this. `@parallel` currently does not.

**Comment by ViralBShah** [comment]
Given that this is done in `pmap` and the plan is to do away with `@parallel` eventually, we can close this.
