### ISSUE TITLE
For-Loop tuple destructuring

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#21724]
I suggest that:
```julia
for (x, y) in zip(xs, ys)
```

Should also be allowed to be written:

```julia
for x, y in zip(xs, ys)
```

Just as:
```julia
(x, y) = first(zip(xs, ys))
```
can  be written as
```julia
x,  y = first(zip(xs, ys))
```

this syntax is allowed in Python; and I've always expected it to work in julia, even now long after I last used python for anything.

Kinda related: #6614, #8522

---

I've been wanting this for a few years.
I always assumed there was an issue for it.
But after a concerted effort, I can not find one.
Though I still might have missed it.

**Comment by yuyichao** [comment]
I believe this is not allowed due to the the nested loop syntax `for x in a, y in b` which is not allowed in python. I'm not sure if there's a real ambituity thought it would be confusing when `,` means very different things in the for loop.

**Comment by quinnj** [comment]
The original issue for this is https://github.com/JuliaLang/julia/issues/6484

**Comment by oxinabox** [comment]
Ah there it is. 
I never tried searching on "breaking apart" I tried "unpacking" and "destructuring" and a few other things.

Closing as duplicate
