### ISSUE TITLE
variable scope error: macro in for loop

### ISSUE THREAD

**Issue by bluehope** [JuliaLang/julia#21722]
Accessing macro in for loop gives error as below (a1 not defined).
This example runs ok with Julia 0.5.x .

```julia
versioninfo()
```

Julia Version 0.6.0-pre.beta.460
Commit 63ae651d91* (2017-05-02 12:18 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

```julia
macro test_macro(a,b)
:(
    return $a+$b;
    )
end
```
@test_macro (macro with 1 method)

```julia
@test_macro(1,2)
```
3
```julia
aa = 1
bb = 2
@test_macro(aa,bb)
```

3

```julia
# macro in for loop
for a1 in 1:2
    @test_macro(a1,bb)
end
```
```julia
UndefVarError: a1 not defined

Stacktrace:
 [1] macro expansion at ./In[5]:2 [inlined]
 [2] anonymous at ./<missing>:?
```

**Comment by yuyichao** [comment]
This is expected. You must escape all user inputs. Please ask questions on https://discourse.julialang.org/

**Comment by tkelman** [comment]
the fact that this works on 0.5 but doesn't work on 0.6 is one of the larger breaking changes, even though it was caused by a hygiene bugfix - we need a news entry for it
