### ISSUE TITLE
Favicon for docs website?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#21723]
It'd be a nice visual convenience to have a cute little Julia logo for the docs website instead of the generic folded paper icon (2nd tab below):

<img width="418" alt="screen shot 2017-05-05 at 10 03 25 pm" src="https://cloud.githubusercontent.com/assets/2896623/25769741/d53b4448-31de-11e7-8f86-29a2dc35cf26.png">

**Comment by morrme** [comment]
I can't seem to see where this could be added.

**Comment by StefanKarpinski** [comment]
There's a `favicon.ico` file in the https://github.com/JuliaLang/julialang.github.com repo – if that's copied to right place in the docs repo, it should just work. Of course, I now realize that I have no idea what repo that even is.

**Comment by KristofferC** [comment]
I think it is this repo on the `gh-pages` branch.

**Comment by StefanKarpinski** [comment]
Ah right. That bizarre github oddity.

**Comment by mubaris** [comment]
I can work on this.

**Comment by morrme** [comment]
I was already moving the file over.....

**Comment by mubaris** [comment]
Okay. If you are working on it, I'm cool with it

**Comment by morrme** [comment]
@StefanKarpinski  I added the file to the root of the `gh-pages ` branch, assuming Jekyll builds from there as it does for the julialang.github.com repo .

**Comment by mubaris** [comment]
@morrme You should not add file to `gh-pages` branch. It's an autobuild branch. You should add favicon to docs directory, then try to build it. If it's working, it's good.

**Comment by morrme** [comment]
@mubaris OK, I was just working based on an earlier comment. I have closed that PR and opened another.

**Comment by tkelman** [comment]
@mubaris why do you say that? Are you positive Documenter and the doc build system here works that way?

**Comment by tkelman** [comment]
can anyone check whether https://github.com/JuliaLang/julia/issues/21821 fixed this?

**Comment by yuyichao** [comment]
Works for me on https://docs.julialang.org/en/latest/

**Comment by quinnj** [comment]
Hmmm....I'm still not seeing the favicon on the link @yuyichao posted. Maybe some sort of caching issue?

**Comment by KristofferC** [comment]
Probably, it didn't work for me at home but works here at work.

**Comment by tkelman** [comment]
I think we're using a fastly cdn now which may have something to do with it?

**Comment by morrme** [comment]
Very happy to say it works for me too! Thank you @tkelman  for re-directing me from that rogue advice. 🏆
