### ISSUE TITLE
slowdown with Val dispatch in v0.6

### ISSUE THREAD

**Issue by gaika** [JuliaLang/julia#21730]
```
using BenchmarkTools
const f32 = 0
jltype(::Val{f32}) = Float32
get_type(i) = jltype(Val{i}())
@benchmark get_type(f32)
```
Is almost hundred times slower with 0.6 (40 ns with v0.5 vs 4 μs with v0.6). Causes significant slowdown in ArrayFIre.jl package when types have to inferred.

**Comment by timholy** [comment]
That's a textbook example of misusing `Val`. https://docs.julialang.org/en/latest/manual/performance-tips.html#Types-with-values-as-parameters-1. Not that it wouldn't be good to fix the performance difference, but it's fundamentally non-inferrable.

**Comment by JeffBezanson** [comment]
Seems related to #21323. In this case since there is a 0-arg constructor we're forced to dispatch on the type instead of other arguments.

**Comment by musm** [comment]
closed by https://github.com/JuliaLang/julia/commit/ecff62420dd7b57b3545667a38eef8f5e1fb99db ?

**Comment by martinholters** [comment]
No. I have 44ns on 0.5, 6μs on 0.6 and 1.8μs on master. So it has improved since 0.6, but it's nowhere close to 0.5.

**Comment by KristofferC** [comment]
900 ns now.

**Comment by oscardssmith** [comment]
160ns now. Is that good enough to close?
