### ISSUE TITLE
Tuple from generator/comprehension syntax

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#21748]
It would be nice to have a syntax to make a tuple out of a generator/comprehension. Right now, this is possible by doing
```julia
ntuple(i->someoperation(aa[i]),length(aa))
```
A shorthand would be:
```julia
tuple(someoperation(a) for a in aa)
```

I couldn't find an already existing issue for this, but a [similar question](https://discourse.julialang.org/t/poor-typing-of-tuple-generators/2880) was raised on discourse recently.

**Comment by vtjnash** [comment]
That's correct, it just needs a ... to indicate that it should use the generator to fill the tuple (as opposed to making it the element of the tuple): `((someoperation(a) for a in aa)...)` (and for some uses cases, could also use some support from inference to give better answers)

**Comment by jebej** [comment]
The discourse post mentions a `@code_warntype` problem, is there an issue open already for that?

**Comment by JeffBezanson** [comment]
You can also use tuple types as constructors for this, e.g. `Tuple(someoperation(a) for a in aa)`. Works better if you happen to know the tuple type you expect to get, e.g. `NTuple{4,Int}(2x for x in 1:4)`.
