### ISSUE TITLE
LibGit2.set_remote_url sets remote as "both" https and ssh

### ISSUE THREAD

**Issue by christopher-dG** [JuliaLang/julia#21773]
If you add a remote to a git repository with an https url like so:
```julia
LibGit2.set_remote_url(repo, "https://github.com/christopher-dg/test.jl")
```
You end up with this in your `.git/config`:
```
[remote "origin"]
	url = https://github.com/christopher-dg/test.jl
	pushurl = git@github.com:christopher-dg/test.jl.git
```

***

What this means is that pushes require an ssh key/password, while fetches/puls don't. I feel like this probably isn't intended.

[This appears to be the relevant LibGit2 code.](https://github.com/JuliaLang/julia/blob/master/base/libgit2/libgit2.jl#L264-L270)

A potential solution could be converting the https url to an ssh one, or maybe taking a keyword that specifies whether the user wants the remote to be set up via https or ssh and then making the necessary conversions.

***

```julia
julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82* (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by kshyatt** [comment]
Thanks for the report! I agree this behaviour is both surprising and annoying - I'll see what I can do later today but others should feel free to patch this if they get to it before I do.
