### ISSUE TITLE
Redefining recursive type fails

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#21816]
Redefining non-parametric, recursive types fails:
```julia
struct Trace
    traces::Vector{Trace}
end
struct Trace
    traces::Vector{Trace}
end
> invalid redefinition of constant Trace
```

**Comment by andyferris** [comment]
Seems genuinely ambiguous which `Trace` is referred to in the body of the redefinition - but I guess if we want to support this then the recursive form needs to be assumed.

**Comment by StefanKarpinski** [comment]
I don't think it's actually ambiguous since only one thing can have the name `Trace` at the end of the day, and the "redefinition" can't actually change the identity of that thing.

**Comment by yashbha** [comment]
What is the solution for this one?

**Comment by StefanKarpinski** [comment]
You can wrap the definition in a module and reload the module, which lets you do this. Redefining a recursive definition in the same module does not yet work.

**Comment by michaelkyu** [comment]
I'd like to throw in my support for this issue. Being able to redefine structs without getting this error would be useful in Jupyter notebooks, where a user is often prototyping code and changing definitions. I am running into this issue myself.

**Comment by StefanKarpinski** [comment]
It would certainly be nice—I don't think there's any opposition. It's just a low priority annoyance that no one has had time or sufficient motivation to work on. If anyone wants to try, they're welcome to!

**Comment by pedroborgesmelo** [comment]
Need this here.
