### ISSUE TITLE
std() type instability?

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#21811]
Julia 0.5.2
```julia
julia> @code_warntype std(randn(5))
Variables:
  #self#::Base.#std
  A::Array{Float64,1}

Body:
  begin 
      return (Base.sqrt)($(Expr(:invoke, LambdaInfo for (::Base.#kw##var)(::Array{Any,1}, ::Base.#var, ::Array{Float64,1}), Base.#var, :($(Expr(:invoke, LambdaInfo for vector_any(::Any, ::Vararg{Any,N}), :(Base.vector_any), :(:corrected), true, :(:mean), :(Base.nothing)))), :(Base.var), :(A))))::Any
  end::Any
```

Julia 0.6rc-1
```julia
julia> @code_warntype std(randn(5))
Variables:
  #self#::Base.#std
  A::Array{Float64,1}

Body:
  begin 
      return (Base.sqrt)($(Expr(:invoke, MethodInstance for (::Base.#kw##var)(::Array{Any,1}, ::Base.#var, ::Array{Float64,1}), :($(QuoteNode(Base.#var))), :($(Expr(:invoke, MethodInstance for vector_any(::Any, ::Vararg{Any,N} where N), :(Base.vector_any), :(:corrected), true, :(:mean), :(Base.nothing)))), :(Base.var), :(A))))::Any
  end::Any
```

The 1st problem is type instability.

The 2nd problem is that for functions taking keyword arguments I cannot get the meaningful output since it only shows the wrapper call (but note that `var()` result is correctly inferred as `Float64`):
```julia
julia> @code_warntype var(randn(5))
Variables:
  #self#::Base.#var
  A::Array{Float64,1}

Body:
  begin 
      return $(Expr(:invoke, MethodInstance for #var#533(::Bool, ::Void, ::Function, ::Array{Float64,1}), :(Base.#var#533), true, :(Base.nothing), :(#self#), :(A)))
  end::Float64
```

**Comment by alyst** [comment]
Ah, looks like a dup of #21794. Well, at least it's a reminder to explicitly specify the result type of `std()`

**Comment by nalimilan** [comment]
But why does it work for `var` then?

**Comment by andreasnoack** [comment]
It doesn't if you supply the keyword so the version without keywords is probably handled in a special way. However, to pass the keyword values from `std` to `var` we'll have to use keywords even in the default case. Maybe we should get rid of the `mean` keyword as we have already done for `cov` and `cor`.

**Comment by alyst** [comment]
The "Performance tips" section of the manual is somewhat cryptic and doesn't describe the problem that we see here. The more relevant details are in #10443, #15468.
I'm a little bit lost, because to my understanding the behaviour of `std()` doesn't fit what is described in the issues: it doesn't look like the specialization on the default keyword argument value is working well.
Would be nice to clarify the situation either by updating the manual or updating the plan for #9551.

**Comment by KristofferC** [comment]
```
julia> using Test

julia> @inferred std(randn(5))
1.369033101041574
```
