### ISSUE TITLE
Segfault when inlining disabled on Mac ccall

### ISSUE THREAD

**Issue by JobJob** [JuliaLang/julia#21819]
Running the following with `julia --inline=no` segfaults on Mac (with julia >= 0.5). This caused Interact tests to fail for mac 0.5 builds, because Pkg.test with coverage=true runs without inlining on 0.5

```
using ZMQ

threadid = Vector{Int}(128) # sizeof(uv_thread_t) <= 8 on Linux, OSX, Win
sock = Socket(Context(), ROUTER)
function heartbeat_thread(sock::Ptr{Void})
    ccall((:zmq_device,ZMQ.zmq), Cint, (Cint, Ptr{Void}, Ptr{Void}),
          ZMQ.QUEUE, sock, sock)
    nothing
end
heartbeat_c = cfunction(heartbeat_thread, Void, (Ptr{Void},))
ccall(:uv_thread_create, Cint, (Ptr{Int}, Ptr{Void}, Ptr{Void}),
      threadid, heartbeat_c, sock.data)
```

@vtjnash's explanation is here: https://github.com/JuliaGizmos/Interact.jl/pull/163#issuecomment-300919055

**Comment by ViralBShah** [comment]
Closing as stale. Please reopen if still an issue with a current reproducer.
