### ISSUE TITLE
compile test fail with color output

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#21826]
The warning test at https://github.com/JuliaLang/julia/blob/2d65d184c7e0eafdd4d1336bdffa29f46a328631/test/compile.jl#L241 and https://github.com/JuliaLang/julia/blob/2d65d184c7e0eafdd4d1336bdffa29f46a328631/test/compile.jl#L321 fails with color output enabled. Noticed when debugging something else and don't have time to fix it at the moment...

**Comment by KristofferC** [comment]
These seem fixed now (tried to run the tests with `--color=yes` and they passed).
