### ISSUE TITLE
Segfault with --track-allocation on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#21838]
This is on julia 0.5.2 and on the current julia 0.6 release candidate. I have a file named ``test3.jl`` with this content:
````julia
using CSV
           
file = "data.csv"      # make sure some file like that exists

io = open(file, "r")

csv = CSV.Source(io, delim = ';')

Data.close!(csv)
close(io)

quit()
````
When I execute this command line: ``julia --track-allocation=user .\test3.jl``, I get a very long segfault output (multiple screens).

I also tried running the same code interactive, and in that case calling ``quit()`` throws an error at the end:
````
julia> quit()
ERROR: ReadOnlyMemoryError()
 in quit() at .\initdefs.jl:23
````

CCing @quinnj, although I feel that no matter what the CSV.jl package is doing, this shouldn't segfault.

**Comment by musm** [comment]
BTW I was seeing something similar yesterday with `--code-coverage` that also segfaulted on rc1-0.6
https://github.com/JuliaCI/Coverage.jl/pull/127/files

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/21289
