### ISSUE TITLE
zip() for arrays

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#2184]
I believe this should work:

```
julia> for (a,b) in reverse(zip([1,2],[3,4]))
         println(a,b)
       end
no method ref(Zip,Int64)
 in anonymous at no file
```

**Comment by JeffBezanson** [comment]
At this point I would favor having `zip` always return a zip iterator, and keep the current behavior which is this:

```
julia> reverse(zip([1,2],[3,4]))
ERROR: MethodError: `reverse` has no method matching reverse(::Zip2{Array{Int64,1},Array{Int64,1}})
```

Since we removed the `Reverse` iterator, the resulting method error is now much clearer.
