### ISSUE TITLE
More descriptive `@which` when calling constructors

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#21860]
Best illustrated by an example
```julia
julia> @which Float32(32)
(::Type{T})(arg) where T in Base at sysimg.jl:24
```
which isn't really helpful...

**Comment by fredrikekre** [comment]
What is wrong with that? That is the constructor which is called, isn't it?

**Comment by musm** [comment]
I suppose so, sorry about that.
I guess this is after all the default outer constructor
