### ISSUE TITLE
(Bug?) Variable scope in @sync and @async

### ISSUE THREAD

**Issue by pluskid** [JuliaLang/julia#21867]
I have been debugging a distributed numerical program forever until I pined down this thing. I'm not sure if this is a bug or an expected behavior. It seems to be very tricky to interpret `a += ...` as defining a new local scoped variable or reusing an outer scope variable. If this is expected behavior, could someone explain to me what is happening here?

Here is a simple program:
```julia
function foo()
  a = zeros(3)

  @sync begin
    for i = 2:nprocs()
      println(i)
      @async begin
        a += fetch(@spawnat i (xxx = ones(3); xxx)) # BUG LINE
      end
    end
  end

  println(a)
end

foo()
```
When tested with `julia -p 3 test.jl`, It outputs
```
2
3
4
[1.0,1.0,1.0]
```
But I was expecting `[3.0, 3.0, 3.0]`. Changing the **BUG LINE** to the following does **not** help:
```julia
        a[:] += fetch(@spawnat i (xxx = ones(3); xxx))
```
However, change it to the following two lines by introducing a temp variable does work:
```julia
        bbb = fetch(@spawnat i (xxx = ones(3); xxx))
        a += bbb
```

Outputs of `versioninfo()`
```
Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by amitmurthy** [comment]
As `fetch` and `@spawnat` are both yieldpoints, I suspect there is a data race happening between the read of `a` and its updation. A more minimal simulation is 
```
function foo()
  a = zeros(3)
  @sync for i = 1:5
      @async a += (yield();ones(3))
  end
  a
end

foo()
```

Without the `yield` it is fine.

On master in-place operation using `a .= a + ...` works.  I suspect `a[:] += fetch....` does not work because it uses temporaries?

**Comment by amitmurthy** [comment]
Closing this as it is not a scope issue and is related to general safe practices to be followed when dealing with parallel operations.

Note that a in-place `broadcast!(+, a, a, fetch(@spawnat i (xxx = ones(3); xxx)))` is also a workable solution for 0.5

**Comment by pluskid** [comment]
@amitmurthy Thanks! I still do not understand it very clearly why in-place operator works but otherwise it does not. Do you mean in-place work because the single integer/floating point operations are atomic, so still works even if race condition happens; but on the other hand, if temp matrices are created, the race condition will lead to assignment that overwrite the previous results?

Is there any "general safe practices" or guidelines in Julia doc to follow for this kind of things (e.g. must be careful when which functions/macros when used together, etc.)?
