### ISSUE TITLE
The .mem files are suspect  on the Mac

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#21871]
I ran Julia 0.5.2 on an up-to-date Mac with --track-allocation =all..  The produced .mem files are highly suspect.  Some lines are listed as having large allocations, when in fact that cannot be true.  Example:

  8718110           param_coords = [1./3. 1./3.];

This line gets called just once to create an array of floating-point numbers.  Yet it is listed as having allocated 8 MB?

**Comment by KristofferC** [comment]
Is it the first line of the function?

**Comment by PetrKryslUCSD** [comment]
It more or less is:
function TriRule(;npts=1)
#    npts=number of points (1-- one-point rule, 3 -- three-point rule,
#      6 -- six point rule, 10 -- Strang 10 point, order 13, degree of precision 7, rule).

    if npts==1 # integrates exactly linear polynomials
          param_coords = [1./3. 1./3.]; # <= This is where the allocation is shown

But the entire object is tiny: two floating-point arrays, each with two entries.  It gets created just once.  I can't believe the allocation would be 8 MB.

Another example: 
        -     #     # get the locations of all the nodes
        0     #     xs = fens.xyz;
   131072     #     #     Disqualify all the nodes that are not connected to the finite

The allocation is shown next to a comment line. And xs creates an alias for  an array, I don't think  this will  lead to memory allocation?

**Comment by PetrKryslUCSD** [comment]
Sorry, forgot about markdown.

**Comment by KristofferC** [comment]
Hm, if possible you could perhaps try the 0.6 release candidate, I think there are some improvements on line information. You could also try https://github.com/KristofferC/TimerOutputs.jl just as a double check.
