### ISSUE TITLE
segfault in Threads.@threads loop

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#21887]
Apologies for the sparse report, but I don't quite know how to collect more info.

I have a fairly complex function that has three nested loops, and I've used `Threads.@threads` inside the middle one. The function creates plots (in files) using PGFPlots.

When I run the function, I get
```
signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
sig_match_fast at /Users/seth/dev/julia/julia6/src/gf.c:1794 [inlined]
jl_lookup_generic_ at /Users/seth/dev/julia/julia6/src/gf.c:1865
jl_apply_generic at /Users/seth/dev/julia/julia6/src/gf.c:1927
jl_apply at /Users/seth/dev/julia/julia6/src/./julia.h:1422 [inlined]
start_task at /Users/seth/dev/julia/julia6/src/task.c:267
Allocations: 12065627 (Pool: 12062905; Big: 2722); GC: 90
Segmentation fault: 11
```
and get dumped back to the shell.

Again, not sure what other information I can provide here, but I'm open to suggestions.

```
Julia Version 0.6.0-pre.beta.325
Commit 6e0a2f8c94 (2017-04-25 14:57 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

**Comment by yuyichao** [comment]
If you are dealing with files then dup of https://github.com/JuliaLang/julia/issues/14494 . From the backtrace it could be something else or simply memory corruption but it's impossible to tell since there's no description of how to trigger the bug.

Just as any bug report, you don't have to debug it very deep yourself but you do need to provide the code to reproduce it.

**Comment by sbromberger** [comment]
I'm unfortunately not able to supply the code. I'll close this out.
