### ISSUE TITLE
Rename Range to AbstractRange?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#21901]
`Range` is one of the very few Base abstract types which do not contain "Abstract" in their names. The only other case that comes to my mind is number types (`Integer`, `Real`...), which have been granted an exception. Should we rename it to `AbstractRange`? This would be clearer IMHO, since `Range` can intuitively be understood as the default range type (equivalent to `Array` vs. `AbstractArray`).

**Comment by nalimilan** [comment]
Any opposition to this change? If not, I'll make a PR.

**Comment by StefanKarpinski** [comment]
It was once called this and we changed it. You may want to look for the discussion around that change before going ahead with this.

**Comment by mbauman** [comment]
I think you may be thinking of the `Ranges` -> `Range` change (#6326).  It doesn't look like they were ever called AbstractRange.

**Comment by StefanKarpinski** [comment]
Right, I was misremembering. At least we're not going in circles :)

**Comment by nalimilan** [comment]
Only in zigzags... I'll make a PR then.
