### ISSUE TITLE
truncating BigFloat results in InexactError at limits

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#21914]
```julia
julia> typemax(Int128)
170141183460469231731687303715884105727

julia> x = nextfloat(BigFloat(typemax(Int128)))
1.701411834604692317316873037158841057270000000000000000000000000000000000000015e+38

julia> trunc(Int128, x)
ERROR: InexactError()
 in trunc(::Type{Int128}, ::BigFloat) at ./mpfr.jl:133

julia> convert(Int128, trunc(BigInt, x))
170141183460469231731687303715884105727
```

**Comment by dpsanders** [comment]
Isn't this in fact a useful warning that you are out of the range of the destination type?

**Comment by StefanKarpinski** [comment]
In this case, I believe this should succeed since the truncation of `x` to an integer is representable as an `Int128`.

**Comment by omus** [comment]
When using `trunc` with `Float64` you can truncate slightly outside of the range of the destination type:

```julia
julia> x = typemax(Int8) + 0.9
127.9

julia> trunc(Int8, x)
127

julia> x = typemax(Int8) + 1.0
128.0

julia> trunc(Int8, x)
ERROR: InexactError()
 in trunc(::Type{Int8}, ::Float64) at ./float.jl:458
```

**Comment by StefanKarpinski** [comment]
Right, the policy is that as long as the correct numerical result value can be represented in the requested result type, we should produce it. We should only raise an InexactError if the correct values cannot be represented in the return type.

**Comment by omus** [comment]
Fixed by: https://github.com/JuliaLang/julia/pull/33681
