### ISSUE TITLE
Broken booleans as numbers?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#21919]
A recent change broke

```julia
julia> ndigits(true)
1
```

I'm not too fussed about this, and can understand why it didn't go through a deprecation cycle. But I was under the impression that the shift from `Bool <: Integer` to `Bool` as a separate concept has yet to happen. If so, I think it's better to continue to support integer operations on `Bool`.

**Comment by TotalVerb** [comment]
Hmm, on further investigation it was https://github.com/JuliaLang/julia/pull/16841/files which **only** changed `ndigits`. I had thought that there was a more comprehensive change, but the breakage of only `ndigits` seems like too minor an issue to care about.

**Comment by rfourquet** [comment]
Sorry I was not aware I broke that one, but I agree it's too minor to fix if the plan is to switch away from `Bool <: Integer`.

**Comment by JeffBezanson** [comment]
I think it should be fixed. It's weird for `ndigits(false)` to give ` and `ndigits(true)` to throw an error.
