### ISSUE TITLE
Loading a NTuple{N, VecElement{T}} can seqfault

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#21918]
Currently SIMD.jl reliably seqfaults on `release-0.6` and `master`. The particular backtrace that I captured in `rr`starts at [1] and ends at [2].
After talking to @yuyichao it looks like a load from the heap that is misaligned. Reverting #20975 makes the issue go away. 

[1] https://github.com/eschnett/SIMD.jl/blob/a4a12d9ea34e43ba66e14d8cecc71b1019aac65d/test/runtests.jl#L36
[2] https://github.com/JuliaLang/julia/blob/b7d6be0d14953be47b58e1a03a2ddbbd06e503d5/base/strings/io.jl#L101

**Comment by m-j-w** [comment]
Regarding alignment issues of `NTuple{N, VecElement{T}}` see also #20961.
It seems the special treatment of `VecElement` introduces false alignment assumptions, and in addition LLVM fails at N>32 plus a number of smaller values of N.

**Comment by vchuravy** [comment]
Yes that is definitely related, but in this case the vector is `vec = NTuple{4, VecElement{Float64}}` with a size of 32 and an alignment of 32. In my opinion that is correct for AVX.

**Comment by vchuravy** [comment]
fixed by #21980
