### ISSUE TITLE
Markdown parser inserts spurious paragraphs between list items

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#21922]
Lists without empty lines should not be rendered with `<p></p>` as shown in e.g. http://spec.commonmark.org/0.7/#example-206.

However, the markdown parser in base does insert these paragraphs which means that the list in for example https://raw.githubusercontent.com/JuliaLang/julia/master/doc/src/index.md has significantly larger vertical space between items than intended.

The screenshot below shows the stable manual to the left and the current to the right:

![image](https://cloud.githubusercontent.com/assets/1282691/26146347/215b4714-3af0-11e7-842f-6b4bef700bb0.png)

cc @mortenpi

**Comment by KristofferC** [comment]
Anyone that can help with this? I've been bumping my head at this for a while with something like:

```diff
diff --git a/base/markdown/Common/block.jl b/base/markdown/Common/block.jl
index a0c4a09..3ebcf3a 100644
--- a/base/markdown/Common/block.jl
+++ b/base/markdown/Common/block.jl
@@ -250,8 +250,9 @@ end
 mutable struct List
     items::Vector{Any}
     ordered::Int # `-1` is unordered, `>= 0` is ordered.
-
-    List(x::AbstractVector, b::Integer) = new(x, b)
+    isloose::Bool
+    List(x::AbstractVector, b::Integer, isloose) = new(x, b, isloose)
+    List(x::AbstractVector, b::Integer) = new(x, b, false)
     List(x::AbstractVector) = new(x, -1)
     List(b::Integer) = new(Any[], b)
 end
@@ -298,6 +299,7 @@ function list(stream::IO, block::MD)
                     pushitem!(list, buffer)
                     break
                 else
+                    list.isloose = true
                     newline = true
                     println(buffer)
                 end
@@ -322,11 +324,18 @@ function list(stream::IO, block::MD)
             end
         end
         count == length(list.items) || pushitem!(list, buffer)
+        if list.isloose
+            map!(Paragraph, list.items, list.items)
+        end
         push!(block, list)
         return true
     end
 end
-pushitem!(list, buffer) = push!(list.items, parse(String(take!(buffer))).content)
+function pushitem!(list, buffer)
+    content = parse(String(take!(buffer))).content
+    content_peeled = map(x -> isa(x, Paragraph) ? x.content : x, content)
+    push!(list.items, content_peeled)
+end
 
 # ––––––––––––––
 # HorizontalRule
```

which renders some random lists I tried correctly but it makes building the docs fail. @mortenpi @MikeInnes

**Comment by mortenpi** [comment]
What's the error you're getting in Documenter?

**Comment by KristofferC** [comment]
It is:

```
ERROR: LoadError: MethodError: no method matching start(::Base.Markdown.Paragraph)
Closest candidates are:
  start(!Matched::SimpleVector) at essentials.jl:259
  start(!Matched::Base.MethodList) at reflection.jl:560
  start(!Matched::ExponentialBackOff) at error.jl:107
  ...
Stacktrace:
 [1] mdflatten(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Base.Markdown.List, ::Base.Markdown.List) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Utilities/MDFlatten.jl:49
 [2] (::Documenter.Writers.HTMLWriter.##27#28{Documenter.Writers.HTMLWriter.HTMLContext,Documenter.Documents.NavNode,Documenter.Documents.Page,Documenter.Writers.HTMLWriter.SearchIndexBuffer})(::Base.Markdown.List) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/HTMLWriter.jl:460
 [3] collect_to!(::Array{Documenter.Utilities.DOM.Node,1}, ::Base.Generator{Array{Any,1},Documenter.Writers.HTMLWriter.##27#28{Documenter.Writers.HTMLWriter.HTMLContext,Documenter.Documents.NavNode,Documenter.Documents.Page,Documenter.Writers.HTMLWriter.SearchIndexBuffer}}, ::Int64, ::Int64) at ./array.jl:462
 [4] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},Documenter.Writers.HTMLWriter.##27#28{Documenter.Writers.HTMLWriter.HTMLContext,Documenter.Documents.NavNode,Documenter.Documents.Page,Documenter.Writers.HTMLWriter.SearchIndexBuffer}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:443
 [5] domify(::Documenter.Writers.HTMLWriter.HTMLContext, ::Documenter.Documents.NavNode) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/HTMLWriter.jl:459
 [6] render_article(::Documenter.Writers.HTMLWriter.HTMLContext, ::Documenter.Documents.NavNode) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/HTMLWriter.jl:419
 [7] render_page(::Documenter.Writers.HTMLWriter.HTMLContext, ::Documenter.Documents.NavNode) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/HTMLWriter.jl:169
 [8] render(::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/HTMLWriter.jl:117
 [9] dispatch(::Type{Documenter.Writers.FormatSelector}, ::Symbol, ::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Selectors.jl:164
 [10] render(::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Writers/Writers.jl:66
...
```

My patch above might just be bugged and produce crap in some cases.

**Comment by mortenpi** [comment]
I think here's the problem:

```julia
        if list.isloose
            map!(Paragraph, list.items, list.items)
        end
```

`.items` in `List` should always be a list of lists. You're mapping `Paragraph`s around the inner lists, but it should be around each element of each inner list.

**Comment by KristofferC** [comment]
Thanks! That seemed to have done the trick. There is a bug in how I detect if a list is loose but it should be an easy fix.

**Comment by KristofferC** [comment]
The previous strategy didn't really work because reasons... I also noticed that we don't actually support non loose list because as soon as there is a double line break the list is considered done. Instead I tried something like:

```diff
diff --git a/base/markdown/Common/block.jl b/base/markdown/Common/block.jl
index 0594ffe..113806f 100644
--- a/base/markdown/Common/block.jl
+++ b/base/markdown/Common/block.jl
@@ -6,9 +6,10 @@
 
 mutable struct Paragraph
     content
+    tag::Bool
 end
 
-Paragraph() = Paragraph([])
+Paragraph() = Paragraph([], true)
 
 function paragraph(stream::IO, md::MD)
     buffer = IOBuffer()
@@ -328,6 +329,13 @@ function list(stream::IO, block::MD)
 end
 pushitem!(list, buffer) = push!(list.items, parse(String(take!(buffer))).content)
 
+function pushitem!(list, buffer)
+    content = parse(String(take!(buffer))).content
+    # Strip paragraphs
+    foreach(x -> isa(x, Paragraph) ? (x.tag = false) : nothing, content)
+    #map!(x -> isa(x, Paragraph) ? x.content : x, content, content)
+    push!(list.items, content)
+end
 # ––––––––––––––
 # HorizontalRule
 # ––––––––––––––
diff --git a/base/markdown/render/html.jl b/base/markdown/render/html.jl
index 7e2f256..2b2e668 100644
--- a/base/markdown/render/html.jl
+++ b/base/markdown/render/html.jl
@@ -76,7 +76,11 @@ function html(io::IO, code::Code)
 end
 
 function html(io::IO, md::Paragraph)
-    withtag(io, :p) do
+    if md.tag
+        withtag(io, :p) do
+            htmlinline(io, md.content)
+        end
+    else
         htmlinline(io, md.content)
     end
 end
```

which seems to give ok html:

```jl
julia> doc = Markdown.parse(
       """
       ## Manual

        * [Introduction](@ref man-introduction)
        * [Getting Started](@ref)
        
        * [Performance Tips](@ref man-performance-tips)

       ## Standard Library
       """);

julia> Base.Markdown.html(STDOUT, doc)
<h2>Manual</h2>
<ul>
<li><a href="@ref man-introduction">Introduction</a>
</li>
<li><a href="@ref">Getting Started</a>
</li>
</ul>
<ul>
<li><a href="@ref man-performance-tips">Performance Tips</a>
</li>
</ul>
<h2>Standard Library</h2>
```

Trying to build the docs fails with:

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Any,1} to an object of type Base.Markdown.Paragraph
This may have arisen from a call to the constructor Base.Markdown.Paragraph(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] runner(::Type{Documenter.Expanders.TrackHeaders}, ::Base.Markdown.Header{1}, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Expanders.jl:216
 [2] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::Base.Markdown.Header{1}, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Selectors.jl:164
 [3] expand(::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Expanders.jl:29
 [4] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /home/kristoffer/julia/doc/deps/v0.6/Documenter/src/Selectors.jl:164
```

**Comment by KristofferC** [comment]
Ah nvm...

**Comment by KristofferC** [comment]
Okay so documenter has it's own HTML renderer so the change to the paragraph above does not change the rendered docs. @mortenpi do you think the approach here is sensible at all?

A patch like:

```diff
diff --git a/src/Writers/HTMLWriter.jl b/src/Writers/HTMLWriter.jl
index 84de8c8..711db66 100644
--- a/src/Writers/HTMLWriter.jl
+++ b/src/Writers/HTMLWriter.jl
@@ -751,7 +751,7 @@ end
 
 mdconvert(list::Markdown.List, parent) = (isordered(list) ? Tag(:ol) : Tag(:ul))(map(Tag(:li), mdconvert(list.items, list)))
 
-mdconvert(paragraph::Markdown.Paragraph, parent) = Tag(:p)(mdconvert(paragraph.content, paragraph))
+mdconvert(paragraph::Markdown.Paragraph, parent) = (x = mdconvert(paragraph.content, paragraph); paragraph.tag ? Tag(:p)(x) : x)
 
 mdconvert(t::Markdown.Table, parent) = Tag(:table)(
     Tag(:tr)(map(_ -> Tag(:th)(mdconvert(_, t)), t.rows[1])),
```

gives from a cursory glance, good docs:

![image](https://cloud.githubusercontent.com/assets/1282691/26403082/1e38944a-408d-11e7-88f5-a8c3b0c72d94.png)

**Comment by mortenpi** [comment]
I feel that whether a list is loose or not should be a property of the list, not the paragraph. In other words, if there's a `Markdown.Paragraph` somewhere then it should always correspond to a `<p>...</p>` in the output.

It feels like the parser should do all the hard work here:

```
- a *b*
- c
```
should parse into
```julia
Markdown.List(items=[ ["a ", Emphasis("b")], "c" ])
```

whereas the following should parse as

```
- a *b*

- c
```
```julia
Markdown.List(items=[
    Paragraph(["a ", Emphasis("b")]),
    Paragraph("c")
])
```

and this

```
- a *b*

  c
- d
```
```julia
Markdown.List(items=[
    [
        Paragraph(["a ", Emphasis("b")]),
        Paragraph("c")
    ],
    Paragraph("d")
])
```
And they should all render correctly.

By the way, the `mdflatten` thing in Documenter you ran into initially is actually kind of a bug, I now realized. The type of `List.items` is just a `Vector{Any}`, so I don't think one should actually assume that it will always be a list of lists (which is what Documenter does do right now). It is just that the parser in Base always generates lists of lists at the moment, which is why this has gone unnoticed, I think.

I.e. `List(items = ["a", "b", "c"])` should probably be a valid representation of a three element list. Alternatively we could make the type of `List.items` more strict (`Vector{Vector{Any}}`), but I don't think that's necessary / right. By that logic `Paragraph.contents` should also be a `Vector{Any}` instead of just `Any`.

**Comment by StefanKarpinski** [comment]
CommonMark makes it pretty clear that this is a property of the list (http://spec.commonmark.org/0.27/#lists), but various implementations don't necessarily do that. Seems sensible to follow CommonMark here.

**Comment by KristofferC** [comment]
Not putting in the paragraphs gives the following artifacts in the rendered documentation:

![image](https://cloud.githubusercontent.com/assets/1282691/26476186/4dc2d24e-41bd-11e7-8da7-51030abd85b0.png)

**Comment by mortenpi** [comment]
Documenter assumes that `List`s are always "block context", so `Code` gets displayed in `<pre>` blocks instead of just inline `<code>`. So we definitely need to update Documenter as well.

**Comment by KristofferC** [comment]
As @StefanKarpinski linked to:

> (The difference in HTML output is that paragraphs in a loose list are wrapped in <p> tags, while paragraphs in a tight list are not.)

So, I think we should still emit paragraphs inside loose lists but the Paragraph Writer needs to know if the paragraph it writes is inside a loose / tight list?

**Comment by mortenpi** [comment]
I'd say it's the writer of the `List` we need to update, and make sure it gets a reasonable input from the parser.

I guess the question is whether a `List` object should be able to represent something that can't be written down as Markdown, e.g.:
```julia
Markdown.List(items=[
    ["a ", Emphasis("b")],
    Paragraph("c")
])
```
which would be a mix of tight and loose. If we'd say that that's fine, then the tight-loose thing would completely be up to the parser. Although it would be a bit tricky for the writer to figure out if things are in a block-context or not.

So the cleanest solution still seems to be to have the `.loose` flag on a `List` and let the writer wrap `<p>` tags around list elements in that case. But no `Paragraph`s in the list in that case.

**Comment by KristofferC** [comment]
But the `List`-writer calls `html` on each item while the `Paragraph`-writer calls `htmlinline`. I tried what you suggested earlier but it doesn't give the same output. From the wording from commonmark above it seems that it is the rendering of paragraphs that should change based on the context (in a tight list or not).

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/26598
