### ISSUE TITLE
NaN in -Inf:Inf

### ISSUE THREAD

**Issue by jingpengw** [JuliaLang/julia#21941]
I would like to have a infinite range, the code do not return error, but have a NaN. This can easily create bugs in program.
```julia
julia> a = -Inf:Inf
-Inf:1.0:NaN
```

```julia
versioninfo()
Julia Version 0.5.1-pre+31
Commit 6a1e339* (2016-11-17 17:50 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by simonbyrne** [comment]
This should probably be an error. 

What do you expect your range to do?

**Comment by jingpengwu** [comment]
I would expect an infinity range as an initialization.
the expected output should be exactly: `-Inf:Inf`

**Comment by simonbyrne** [comment]
What would that mean though? How long would it be? What values would you
get when iterating over it?

**Comment by StefanKarpinski** [comment]
These should be an error on construction. There's no sensible meaning to such ranges.

**Comment by dpsanders** [comment]
Maybe you are looking for an infinite *interval*, rather than a range.
This is available in e.g. the [`IntervalArithmetic.jl` package](https://github.com/JuliaIntervals/IntervalArithmetic.jl/):

```
julia> using IntervalArithmetic

julia> x = -∞..∞   # .. constructs intervals of real numbers
[-∞, ∞]

julia> 1.5e15 ∈ x
true
```

**Comment by GregPlowman** [comment]
`-Inf:Inf` is an error since 0.5.1
`Inf:Inf` is an error on v0.6.0-rc1
```
Julia-0.5.0> -Inf:Inf
-Inf:1.0:NaN
```
```
Julia-0.5.1> -Inf:Inf
ERROR: InexactError()
 in trunc(::Type{Int64}, ::Float64) at .\float.jl:463
 in colon(::Float64, ::Float64, ::Float64) at .\range.jl:183
 in colon(::Float64, ::Float64) at .\range.jl:191
```
```
Julia-0.5.2> Inf:Inf
Inf:1.0:Inf
```
```
Julia-0.6.0-rc1> Inf:Inf
ERROR: InexactError()
Stacktrace:
 [1] trunc(::Type{Int64}, ::Float64) at .\float.jl:672
 [2] colon(::Float64, ::Float64, ::Float64) at .\twiceprecision.jl:156
 [3] colon(::Float64, ::Float64) at .\range.jl:67
```

**Comment by tkelman** [comment]
not that the 0.5.0 behavior is that useful, but that's a bit more of a behavior change between 0.5.0 and 0.5.1 than I usually would have preferred for backporting. any guesses which backport commit it was?

**Comment by GregPlowman** [comment]
#20396 ??

**Comment by StefanKarpinski** [comment]
Someone is welcome to figure out a way to restore the pre-0.5.2 behavior without breaking what that change fixed but it does not seem important enough to me to warrant much effort.

**Comment by NHDaly** [comment]
Looks like this be closed now? Or is there any work / discussion remaining?
