### ISSUE TITLE
security: compromise of multi-user cluster is possible even after #16292

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#21949]
#16292 is an effective way to mitigate a remote attack against a Julia cluster (ref https://www.cylance.com/compromising-an-entire-julia-cluster), but it does not effectively stop a local attack where the attacker has an account on the HPC system running the Julia cluster. Because the cookie is passed via command line, an attacker who has access to the running process information (trivially via `ps`) can obtain the cluster cookie and execute code in the context of the remote worker (typically running as the user who started the parallel Julia instance).

It is precisely this issue that precludes my use of Julia on our HPC systems at work. The documentation hints at being able to work around this security issue by generating and storing cookies in a file that can be read by the workers (ref https://github.com/JuliaParallel/ClusterManagers.jl/issues/69 and https://discourse.julialang.org/t/overriding-cookie-generation-handling-in-slurm-connection-manager/3791/1) but example code to change to this configuration is not readily apparent. Native filesystem access controls would provide the requisite protection of the cookie in this case.

IMO, fixing this so that parallel computing is "secure by default" should be a high priority since it represents a serious impediment to running Julia on HPC in security-conscious environments.

**Comment by StefanKarpinski** [comment]
Agree – secrets should never be passed on the command-line. They should either be passed via files which are checked to have sufficiently restricted permissions before loading (with an error if they don't), or passed via environment variables.

**Comment by StefanKarpinski** [comment]
We can add support for this to the 0.5 and 0.6 versions in a backwards compatible way if we continue support for the command-line option but add support for the environment variable. Going forward, we should deprecate the command-line option, however.

**Comment by sbromberger** [comment]
@StefanKarpinski thanks for your attention to and support of this proposal. In the meantime, do you know of any resource that would help me implement a file-based cluster cookie per https://docs.julialang.org/en/latest/manual/parallel-computing.html#Cluster-Cookie-1 ?

**Comment by amitmurthy** [comment]
For the built-in SSHManager and LocalManager, it should be possible to send the cookie via STDIN to the workers.

For other cluster managers where STDIN to the workers is unavailable, a shared filesystem may be the only solution.

@sbromberger are you using SSHManager to launch on your cluster? If so, you can use the SSHManager implementation in `base/distributed/managers.jl` as a template and change the cookie  transport mechanism to use the filesystem.

**Comment by sbromberger** [comment]
@amitmurthy For this particular system we're using Slurm.

**Comment by amitmurthy** [comment]
You can start with the slurm cluster manager and change the launch command to replace `--worker $(Base.cluster_cookie())` with a `-e 'Base.start_worker(readline("<cookie_file_name>"))'. `cookie_file_name` would be a file on the shared file system into which `Base.cluster_cookie()` is written by the master.

**Comment by sbromberger** [comment]
@amitmurthy thanks. I will try to hack something together this week and will let you know.

**Comment by amitmurthy** [comment]
Closed by https://github.com/JuliaLang/julia/pull/22114
