### ISSUE TITLE
for-loop variables escaping their scope

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#21950]
In Julia 0.6, a variable introduced by iteration stays defined outside of the loop. This is at variance from 0.5.
I couldn't find any notice of this change in behavior in the NEWS or in past issues, and it also seems weird to me, so it is likely unintentional?

Example:
```julia
function tst()
    for i = 1:3
        println(i)
    end
    println(i) # i shouldn't be defined here?
end
```

On Julia 0.6 and later (at least since rc1), this outputs:
```
1
2
3
3
```

On Julia 0.5, on the other hand, it gives an error after the first 3 lines.

**Comment by fredrikekre** [comment]
dup of https://github.com/JuliaLang/julia/issues/21900 ?

**Comment by KristofferC** [comment]
Yes, https://github.com/JuliaLang/julia/issues/21900#issuecomment-301840424 has the same example.

**Comment by carlobaldassi** [comment]
Ah yes sorry, I'm really bad at searching issues apparently.
