### ISSUE TITLE
`titlecase` should not capitalize small, common words

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#21954]
As far as I understand, the common practice is not to capitalize words like `and`, `to`, `the`, etc.

**Comment by ararslan** [comment]
There are exceptions to this though; for example, "the" or "a" should be capitalized after a colon.

**Comment by StefanKarpinski** [comment]
This is *very* language-specific – we don't do anything else like this in Base.

**Comment by dpsanders** [comment]
Sure - indeed, it's not clear to me why titlecase needs to be in Base at all.

**Comment by StefanKarpinski** [comment]
I did not include it originally for exactly this reason.

**Comment by ararslan** [comment]
Though you did suggest it be added (#19465). :wink: It seems to me that it's fine to be in Base so long as it consistently applies `ucfirst` to each word rather than trying to work around the idiosyncrasies of any particular language.

**Comment by dpsanders** [comment]
Isn't it just join(map(ucfirst, split(s))) ? Why does this need to be a separate function at all?

**Comment by ararslan** [comment]
> Isn't it just join(map(ucfirst, split(s))) ?

Well, not quite.
```julia
julia> titlecase("a        b")
"A        B"

julia> join(map(ucfirst, split("a        b")))
"AB"
```
`titlecase` preserves whitespace, which is somewhat nontrivial.

**Comment by TotalVerb** [comment]
That can be fixed by drop=false though.

**Comment by stevengj** [comment]
It's also vastly faster than `join(map(ucfirst, split(s)))`.

Arguably the right thing for uppercase, lowercase, and titlecase is to follow the algorithm in [UTR#21](http://www.unicode.org/L2/L1999/99190.htm), which is even more nontrivial to get right.

**Comment by stevengj** [comment]
Note that many languages and standard libraries have a `titlecase`-like function.  Go has [Title](https://golang.org/pkg/strings/#Title), Python has [capwords](https://docs.python.org/2/library/string.html), Rails has [titleize](https://apidock.com/rails/String/titleize), VB.NET has [vbProperCase](https://msdn.microsoft.com/en-us/library/microsoft.visualbasic.constants.vbpropercase(v=vs.110).aspx) or [ToTitleCase](https://msdn.microsoft.com/en-us/library/system.globalization.textinfo.totitlecase.aspx), CSS has the [capitalize](https://www.w3.org/TR/CSS2/text.html#caps-prop) text transform, Excel has the [PROPER](https://support.office.com/en-us/article/PROPER-function-52a5a283-e8b2-49be-8506-b2887b889f94) function, ....

**Comment by KristofferC** [comment]
I think we will just have to live with this. Adding a bunch of exceptions for differnt langauges seems like a non ending bike shed.
