### ISSUE TITLE
Bug or Feature: `fit(Histogram,...)` and DataFrames

### ISSUE THREAD

**Issue by 0kto** [JuliaLang/julia#21951]
Hi all,
I am relying quite a bit on Histograms in my scripts for my PhD, and I often calculate intensities of 2D detectors by supplying coordinates `x`,`y` and the signal intensity `I` as weight to the
`fit(Histogram,(x,y),weights(I)`. This is immideatly plottable via PyPlots `plt.imshow()`, etc

Since I get my data from DataFrames, a typical command looks like:

    dataTuple = (df[:colX], df[:colY])
    weights   = WeightVec(df_test[:I])

    hist      = fit(Histogram,dataTuple,weights)

This stopped working, instead I have to convert my DataFrames:

    dataTuple = convert(Tuple{Array{Float64,1},Array{Float64,1}},(df[:colX],df[:colY]))
    weights   = WeightVec(convert(Array{Float64,1},df[:I]))

was that intentional?

**Comment by KristofferC** [comment]
This issue seems not to be about the Base library but the package https://github.com/JuliaStats/StatsBase.jl.

**Comment by 0kto** [comment]
ups, posted into the wrong tab... sorry
