### ISSUE TITLE
Ambiguous method callable

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#21963]
Ref. https://github.com/JuliaLang/julia/pull/21892#issuecomment-302704983

```julia
julia> methods(string, Tuple{Char})
# 1 method for generic function "string":
string(a::Union{Char, String}...) in Base at strings/string.jl:351

julia> Base.string(a::Union{Char, Val{:foo}}...) = "bar" # that's ambiguous!

julia> methods(string, Tuple{Char}) # let's check
# 0 methods for generic function "string":

julia> string('0') # so should throw MethodError
"0"
```

**Comment by martinholters** [comment]
Looks like we were able to detect this ambiguity at some point in time: JuliaArchive/LegacyStrings.jl#8. Interstingly, even with 0.5.0, I don't get the `MethodError` reported there. @vtjnash do you remember what Julia version you were using (or how you got the  `MethodError` thrown)?

**Comment by vtjnash** [comment]
It's #265 :P (the method isn't getting flushed from the MethodTable cache)

I forget if I had hacked something, or just loaded other packages too.

**Comment by martinholters** [comment]
Ah, silly me, I thought #265 had been closed. No, wait...
