### ISSUE TITLE
UniformScaling does not support A_ldiv_B!

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#21961]
As a result, the following fails (with using Optim)
```
julia> Optim.optimize(x -> x[1]^2 + 10x[2]^2,randn(2),GradientDescent(P=I))
ERROR: MethodError: no method matching A_ldiv_B!(::Array{Float64,1}, ::UniformScaling{Int64}, ::Array{Float64,1})
```

cf http://julianlsolvers.github.io/Optim.jl/stable/algo/precondition/

Apologies if it's not the right place to post this: I'm not sure if this is a problem with Optim (should it not require A_ldiv_B! ?) or with julia (should UniformScaling implement it?).

**Comment by andreasnoack** [comment]
This is an oversight. We should implement this. Feel free to open a PR.

**Comment by antoine-levitt** [comment]
I've started to do that but there's a ton of in-place functions in there, see https://github.com/JuliaLang/julia/issues/5332, should UniformScaling implement them all?

**Comment by kshyatt** [comment]
Well, for most of them like `At_ldiv_B!` the transpose of a `UniformScaling` is just itself so you can directly call `A_ldiv_B!`. I think the `A{t,c}_ldiv_B{t,c}` are enough, not sure what everyone else thinks.

**Comment by goggle** [comment]
Now, as `A_ldiv_B!` has been deprecated, which method would be needed to be implemented?

**Comment by antoine-levitt** [comment]
I think it's `ldiv!(randn(2,2),I,randn(2,2))`. Generally there are a number of 3-arg methods missing for ldiv (and now I think there's even 5-arg versions). There was another thread (don't remember which one) where it was proposed to have `ldiv!(A,B,C)` = `ldiv!(B,copy!(A,C),)` as a fallback, which would solve this.

**Comment by dkarrasch** [comment]
This works now
```julia
julia> ldiv!(zeros(2,2),2I,ones(2,2))
2×2 Array{Float64,2}:
 0.5  0.5
 0.5  0.5
```
