### ISSUE TITLE
include values of significant environment vars in versioninfo()

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#21971]
See e.g. https://github.com/JuliaLang/julia/issues/21958: the output of `versioninfo()` should include the values of any `JULIA_` environment variables that can affect the behavior of the program.

**Comment by fredrikekre** [comment]
They are shown with `versioninfo(true)`

```
julia> versioninfo(true)
Julia Version 0.6.0-pre.beta.474
Commit b66792a (2017-05-06 15:06 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
  WORD_SIZE: 64
           Ubuntu 16.04.2 LTS
  uname: Linux 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64
Memory: 15.631458282470703 GB (9217.95703125 MB free)
Uptime: 12011.0 sec
Load Avg:  1.64794921875  1.70947265625  1.57763671875
Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz: 
       speed         user         nice          sys         idle          irq
#1  4060 MHz      80319 s       1097 s      10137 s    1106245 s          0 s
#2  4075 MHz      77647 s        569 s       9945 s    1109202 s          0 s
#3  4037 MHz      76784 s       1102 s      15132 s    1104085 s          0 s
#4  4073 MHz      79492 s        683 s      10715 s    1106339 s          0 s

  BLAS: libopenblas (USE64BITINT NO_AFFINITY HASWELL)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
  TERM = xterm-256color
  DEFAULTS_PATH = /usr/share/gconf/gnome.default.path
  PATH = /home/fredrik/anaconda3/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  MANDATORY_PATH = /usr/share/gconf/gnome.mandatory.path
  HOME = /home/fredrik
  WINDOWPATH = 2
  JULIA_EDITOR = subl

[...]
```

**Comment by musm** [comment]
`versioninfo(true)` almost hangs the repl because it takes so long on my windows machine (It prints out all the packages installed...)

**Comment by StefanKarpinski** [comment]
I believe that includes the entire environment, which is ok, but we should include Julia-significant environment variables even in `versioninfo()`. We should probably also switch to more fine-grained keyword-based control over what gets printed.

**Comment by fredrikekre** [comment]
> It prints out all the packages installed...

This actually surprised me, wasn't expecting package information from `versioninfo()`. Perhaps remove package information from `versioninfo()`?

**Comment by StefanKarpinski** [comment]
We could take it out and put it behind a `versioninfo(packages=true)` keyword option.

**Comment by ararslan** [comment]
Or we could just leave package listing to `Pkg.installed()` and keep `versioninfo` for more Julia build-specific stuff.

**Comment by fredrikekre** [comment]
> Or we could just leave package listing to `Pkg.installed()` and keep `versioninfo` for more Julia build-specific stuff.

Yes, I think it makes sense to separate them.
