### ISSUE TITLE
String interpolation doc should mention show

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#21982]
The docs [say](https://docs.julialang.org/en/v1/manual/strings/#string-interpolation-1) "Both concatenation and string interpolation call string() to convert objects into string form." but unless I'm mistaken, that's not true:

```julia
julia> immutable Blag end

julia> Base.string(::Blag) = "hoy"

julia> "jo $(Blag())"
"jo Blag()"
```

AFAICT the proper way to get custom printing is to [overload](https://docs.julialang.org/en/v1/manual/types/#man-custom-pretty-printing-1) `show`. If that's correct, I can make a PR.

**Comment by yuyichao** [comment]
The doc is correct.

```julia
julia> struct Blag end

julia> Base.string(a::String, b::Blag) = "hoy"

julia> "jo $(Blag())"
"hoy"
```

It can certainly be clarified if you find it confusing.

**Comment by yuyichao** [comment]
Link updated, doc issue still applies.
