### ISSUE TITLE
ishermitian can be wrong for complex symmetric matrices

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#21981]
A bit of a contrived example:

```julia
julia> B = complex(rand(4,4)); B[4,1] += 1.0im;
julia> Symmetric(B)
4×4 Symmetric{Complex{Float64},Array{Complex{Float64},2}}:
 0.254375+0.0im  0.627793+0.0im   0.84517+0.0im  0.585248+0.0im
 0.627793+0.0im  0.760274+0.0im  0.733126+0.0im   0.34415+0.0im
  0.84517+0.0im  0.733126+0.0im  0.659442+0.0im  0.750858+0.0im
 0.585248+0.0im   0.34415+0.0im  0.750858+0.0im  0.392022+0.0im
julia> ishermitian(Symmetric(B))
false
```

This is because ishermitian for complex symmetric matrices checks if the full underlying matrix is real.

As a side discussion relevant to this, what are the reasons for not making the underlying matrix symmetric, or Hermitian on construction? I know that LAPACK routines only look at the upper or lower triangle, but having the underlying matrix actually be hermitian or symmetric could be useful in certain situations.

In particular, using the `vec` form of such a matrix is really slow due to the non-ideal memory access pattern.

**Comment by andreasnoack** [comment]
Thanks for reporting this. See #21994. I don't think we should update the underlying array then constructing a `Symmetric` or `Hermitian`. It is useful that these are view and underlying memory can be updated by the user if convenient. If we did it automatically, then it wouldn't be possible to opt out.

**Comment by jebej** [comment]
Thanks.

> I don't think we should update the underlying array then constructing a Symmetric or Hermitian. It is useful that these are view and underlying memory can be updated by the user if convenient. If we did it automatically, then it wouldn't be possible to opt out.

Updating the array does no necessarily prevent the user from later updating the underlying array, it's just that construction operation would then modify the array.

Do you have any tips in the case where I might want to use the `vec` form of the Hermitian matrix, without killing the performance?

**Comment by andreasnoack** [comment]
Wouldn't your suggestion just mean that you traverse the array in the unfortunate fashion every time you construct a `HermOrSym`? Isn't the main reason that `vec` is so fast on `Array` that it avoids the copy? 

> Do you have any tips in the case where I might want to use the `vec` form of the `Hermitian` matrix, without killing the performance?

Would the unexported `LinAlg.full!` function work for your application?

**Comment by jebej** [comment]
> Wouldn't your suggestion just mean that you traverse the array in the unfortunate fashion every time you construct a HermOrSym? Isn't the main reason that vec is so fast on Array that it avoids the copy?

That's true, doing this would only make sense if there were other benefits.

For now I ended up "hermitianizing" my matrices on construction, and using `vec` on the raw array. For my use this is faster than `Hermitian` with `vec`.

> Would the unexported LinAlg.full! function work for your application?

Is that function supposed to be defined on the Hermitian type?

**Comment by andreasnoack** [comment]
> Is that function supposed to be defined on the Hermitian type?

I should have checked. It is only defined for the `XTriangular` family. We have moved a bit away from the name `full` so I don't know if want to extend the `full!` method. What would a good name for a function that makes the underlying array consistent with the view of it?

**Comment by jebej** [comment]
Here's a few (yay for synonym dictionaries!):
```
reconcile!
harmonize!
make_consistent!
adjust!
adapt!
```

**Comment by jebej** [comment]
If such a method is created, would there be a flag in the type indicating whether the `data` is Hermitian (Symmetric, etc...) such that all the methods that depend on `getindex` could benefit from the memory arrangement?

**Comment by andreasnoack** [comment]
I tend to think that it is not worth it and a better solution in those situations would be just to work with the underlying arrays.
