### ISSUE TITLE
Confusing error message with method ambiguity involving Union

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#22014]
```
julia> f(::Signed, ::Real) = 1
f (generic function with 1 method)

julia> f(::Union{Signed,Integer}, ::Unsigned) = 2
f (generic function with 2 methods)

julia> f(1, 0x1)
ERROR: MethodError: f(::Int64, ::UInt8) is ambiguous. Candidates:
  f(::Integer, ::Unsigned) in Main at REPL[2]:1
  f(::Signed, ::Real) in Main at REPL[1]:1
Possible fix, define
  f(::Signed, ::Unsigned)
```
The first candidate comes from the union, so it makes one believe that another potential candidate coming from the union is `f(::Signed, ::Unsigned)`, but the message suggests to define it. Possible fix is to show `f(::Union{Signed,Integer}, ::Unsigned)` as the first candidate (to help understand that a `Union` is less specific than the types in the union).

**Comment by yuyichao** [comment]
```
julia> Union{Signed,Integer}
Integer
```

**Comment by rfourquet** [comment]
Ah sorry I didn't realize that!

**Comment by oscardssmith** [comment]
Should `Signed` be renamed, as you pretty easily could distinguish between real numbers>0, and all real numbers.
