### ISSUE TITLE
Bad deprecation warning for Iterators.filter on 0.6

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#22037]
Importing `Iterators` (in the same, or in a separate module) triggers a spurious deprecation warning.
```julia
  | | |_| | | | (_| |  |  Version 0.6.0-rc1.0 (2017-05-07 00:00 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> module Blag
       import Iterators
       end
Blag

julia> Iterators.filter(n->true, (2, 1))
WARNING: filter(flt, itr) is deprecated, use Iterators.filter(flt, itr) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] filter(::Function, ::Tuple{Int64,Int64}) at ./deprecated.jl:51
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [5] macro expansion at ./REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
Base.Iterators.Filter{##1#2,Tuple{Int64,Int64}}(#1, (2, 1))
```

**Comment by StefanKarpinski** [comment]
Can we just delete that deprecation now?

**Comment by TotalVerb** [comment]
This actually isn't spurious: `import Iterators` is not importing `Base.Iterators`; it's importing the Iterators.jl package, which does not define `filter`.

**Comment by cstjean** [comment]
Oh, that makes sense. Then perhaps the deprecation warning should suggest `Base.Iterators.filter`? There are numerous packages that import `Iterators`, and importing any one of them causes the above problem at the REPL.

**Comment by TotalVerb** [comment]
That's moreso a problem of the REPL working in the same module as the packages are imported to. It would be nice if those could be separated. I don't think telling people to use `Base.Iterators` is the solution to the `Main.Iterators` module being silently replaced with one that's not the expected.
