### ISSUE TITLE
Should `real(Vector{Complex128})` return `Vector{Float64}`?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#22047]
The following seems inconsistent to me. I'd expect `real(::Type{T}) where {T}` to return the type of the result of  `real(::T)`, so in this case `real(::Vector{Complex128})` should return `Vector{Float64}`, since `real([1.0+0.0im]) isa Vector{Float64}`.

```julia
julia> real(Complex128)
Float64

julia> real(Vector{Complex128})
ERROR: MethodError: no method matching zero(::Type{Array{Complex{Float64},1}})
Closest candidates are:
  zero(::Type{Base.LibGit2.GitHash}) at libgit2/oid.jl:106
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:82
  zero(::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:124
  ...
Stacktrace:
 [1] real(::Type{T} where T) at ./complex.jl:89
```

**Comment by stevengj** [comment]
Makes sense to me and seems more consistent.

(The `real(Complex{T})` function was added relatively late (#12201) but has turned out to be pretty natural and useful, I think, despite being a bit of a pun.)

**Comment by stevengj** [comment]
That being said, I'm not sure if is possible to define this in general.  We can certainly define `real(::Type{Array{T,N}} where {T, N} = Array{real(T),N}`, but how would we define it for `AbstractArray`?

**Comment by fredrikekre** [comment]
There is also nested cases `real(Vector{Vector{Complex{128}})`, how could that be handled?

**Comment by dlfivefifty** [comment]
Nested cases work by recursion. For `AbstractArray`, wouldn't 
```julia
real(::Type{A}) where A<:AbstractArray = real(eltype(A))
```
Work?

**Comment by dlfivefifty** [comment]
Oh, sorry my code is wrong since it should return `ConcreteArray{real(eltype(A))}` where `ConcreteArray` is the array type...

**Comment by dlfivefifty** [comment]
I think this a reasonable definition 
```julia
real(::Type{A}) where {A<:AbstractArray{T}} where{T<:Real} = A
real(::Type{A}) where {A<:AbstractArray{T,p}} where {T,p} = Array{real(eltype(A)),p}
```
based on the following behaviour:
```julia
julia> a = rand(Complex128,10)
10-element Array{Complex{Float64},1}:
  0.855449+0.340496im
  0.569401+0.893036im
  0.339815+0.332744im
  0.569803+0.962953im
  0.110641+0.342221im
   0.88538+0.927446im
  0.558638+0.325267im
 0.0199807+0.618005im
  0.997634+0.977318im
  0.100074+0.816519im

julia> real(view(a,1:2:6))
3-element Array{Float64,1}:
 0.855449
 0.339815
 0.110641

julia> a = rand(10)
10-element Array{Float64,1}:
 0.431132
 0.785451
 0.786073
 0.404946
 0.116118
 0.975589
 0.382353
 0.369401
 0.764749
 0.457862

julia> real(view(a,1:2:6))
3-element SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true}:
 0.431132
 0.786073
 0.116118
```

Then if you override `real(::MyArray)` you should also override `real(::Type{<:MyArray})`.

**Comment by stevengj** [comment]
@dlfivefifty, the problem is that the output type of `real` can be changed by overriding `broadcast`, not `real`.

**Comment by dlfivefifty** [comment]
OK, this should work:
```julia
real(::Type{T}) where T = first(Base.return_types(real,Tuple{T}))
```
Though it's not type stable, so maybe add overrides for `Array`.

**Comment by oscardssmith** [comment]
now it does.
