### ISSUE TITLE
Rename `basename` to `filename`

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/julia#22045]
I would like to suggest to change the method name `basename` to `filename`.
The only reason is that it´s easier to remember.

So we would have:

```julia
julia> f = "/my/path/name.txt";
julia> dirname(f)
"/my/path"
julia> filename(f)
"name.txt"
```

**Comment by ararslan** [comment]
Presumably `basename` was chosen since it matches the shell function of the same name, which I _think_ is POSIX standard.

**Comment by dpsanders** [comment]
Isn't basename without the extension?

**Comment by ararslan** [comment]
No, `basename` includes the extension, both in Julia and in the shell.

**Comment by dpsanders** [comment]
I was remembering this :

basename /home/jsmith/base.wiki .wiki

Removes .wiki from the end.

**Comment by StefanKarpinski** [comment]
The name is standard in shell, Python, Perl, Ruby, etc.

**Comment by felipenoris** [comment]
If that's a standard, that's fine. Thanks!

**Comment by kungfooman** [comment]
There is (at least in 0.6.2) no `filename(path)`, but this helps:

	julia> filename(path) = splitext(path)[1]
	filename (generic function with 1 method)

	julia> filename("test.png")
	"test"

**Comment by o314** [comment]
it seems coreutils and posix does not match.

basename @ coreutils ~ filename @ julia
basename @ posix ~ basename @ julia

**Comment by o314** [comment]
it seems coreutils and posix does not match.

`basename` @ julia ~ `basename` @ posix
`nothing` @ julia ~ `basename` @ coreutils

Here is the coreutils version :

```julia
function Base.basename(path::String, suffix::String)
    (n,e) = splitext(basename(path))
    suffix==e ? n : path
end

@test Base.basename("foo", ".htm") == "foo"
@test Base.basename("foo.htm", ".htm") == "foo"
@test Base.basename("foo.jpg", ".htm") == "foo.jpg"
```
