### ISSUE TITLE
Constructing leaftypes by filling in dependent type parameters

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#22056]
We have some types that have "dependent" type parameters. For instance, in StaticArrays the `SArray` type is defined
```julia
immutable SArray{S <: Tuple, T, N, L} <: StaticArray{S, T, N}
    data::NTuple{L,T}
end
```
and an example for a 3x2x5 array might be `SArray{Tuple{3,2,5},Float32,3,30}`. In all "valid" (aka, useful) instances, `N = length(S)` and `L = prod(S)`. Consequently it might make sense for the package developer to be able to specify that `SArray{S, T}` constructs a *leaftype*, filling in the dependent parameters, rather than a `UnionAll` type.

Ref https://github.com/JuliaArrays/StaticArrays.jl/pull/181.

**Comment by timholy** [comment]
Alternatively one might want to declare the type
```julia
immutable SArray{S <: Tuple, T} where {N = length(S), L = prod(S)}  <: StaticArray{S, T, N}
    data::NTuple{L,T}
end
```
That might be cleaner.

**Comment by timholy** [comment]
xref: this appears to be a potential solution for #5560

**Comment by andyferris** [comment]
This also targets a different open issue (I'll try find it later) relating to allowing field types which are (more arbitrary) functions of the type parameters, which would be awesome to solve.

**Comment by andyferris** [comment]
xref: it is #18466

**Comment by vtjnash** [comment]
already implemented: https://github.com/JuliaLang/julia/issues/18466#issuecomment-274367080
