### ISSUE TITLE
real(::SparseMatrixCSC) should not be deprecated

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#22065]
This behaviour is inconsistent with `real(::Array)`, which is not deprecated (per discussion in https://github.com/JuliaLang/julia/issues/20387) 
```julia
julia> a = speye(Complex128,10,10);

julia> real(a)
WARNING: real(A::SparseMatrixCSC) is deprecated, use real.(A) instead.
```

**Comment by fredrikekre** [comment]
Ref https://github.com/JuliaLang/julia/pull/19242 where `conj` got un-deprecated for the same reason.

**Comment by stevengj** [comment]
Looks like a bug in #17265, cc @Sacha0

**Comment by Sacha0** [comment]
Bug indeed, good catch! :)
