### ISSUE TITLE
indextrema, findextrema ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#22072]
we have `minimum`, `maximum`, `indmin`, `indmax`, `findmin`, `findmax`.  we also have `extrema`, but so far as i can tell no equivalent of  `indextrema` and `findextrema`.  has this been decided against, or just not gotten around to?

**Comment by fredrikekre** [comment]
ref https://github.com/JuliaLang/Juleps/blob/master/Find.md

**Comment by kmsquire** [comment]
Also: #7327

**Comment by andreasnoack** [comment]
Closing as dup of #7327
