### ISSUE TITLE
Amalgamate redirect_stderr, redirect_stdout, redirect_stdin

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#22099]
It feels like these should be one single function.

It would also be helpful to have examples of usage in the docs.

**Comment by dpsanders** [comment]
This is also part of https://github.com/JuliaLang/julia/issues/20402 w.r.t. functions with underscores.

**Comment by dpsanders** [comment]
Bump

**Comment by dpsanders** [comment]
Maybe redirect!(stdout,...)?

**Comment by JeffBezanson** [comment]
Unfortunately that doesn't quite work; it would redirect whatever `stdout` happens to refer to, while we want to redirect fd 1. We could potentially add an object that unconditionally refers to fd 1 I guess.

**Comment by JeffBezanson** [comment]
Triage thinks this doesn't need to be changed for 1.0.

**Comment by vtjnash** [comment]
These are amalgamated now (into redirect_stdio and Base.RedirectStdStream())
