### ISSUE TITLE
Allow zero-method macros ? ?

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#22098]
?
```julia
julia> macro m end
ERROR: syntax: expected "(" in macro definition
```
[?](https://github.com/fcard/julia/pull/10/files)

**Comment by DrKrar** [comment]
macro(s) are to work on some code and deliver the result to run-time .
what is the use of a macro having no thing to work on.

**Comment by fcard** [comment]
Creating a zero-method macro makes its existence and name available to other meta-tools, the module system and the documentation system. (I personally wanted this for docstring purposes)

**Comment by nalimilan** [comment]
Can you give a concrete example of where you need this?

**Comment by DrKrar** [comment]
i suggest
    
    "docstring"    
    macro m() end
it define a macro

**Comment by fredrikekre** [comment]
https://docs.julialang.org/en/stable/manual/documentation/#macros

**Comment by vtjnash** [comment]
Seems possible for the frontend to allow this.

**Comment by fcard** [comment]
```diff
diff --git a/src/julia-parser.scm b/src/julia-parser.scm
index 7e05db3f7ff..ef8942bfd0a 100644
--- a/src/julia-parser.scm
+++ b/src/julia-parser.scm
@@ -1285,11 +1285,11 @@
        ((function macro)
         (let* ((paren (eqv? (require-token s) #\())
                (sig   (parse-def s (not (eq? word 'macro)))))
-          (if (and (eq? word 'function) (not paren) (symbol-or-interpolate? sig))
+          (if (and (not paren) (symbol-or-interpolate? sig))
               (begin (if (not (eq? (require-token s) 'end))
-                         (error (string "expected \"end\" in definition of function \"" sig "\"")))
+                         (error (string "expected \"end\" in definition of " word " \"" sig "\"")))
                      (take-token s)
-                     `(function ,sig))
+                     `(,word ,sig))
               (let* ((usig (unwrap-where sig))
                      (def  (if (or (symbol? usig)
                                    (and (pair? usig) (eq? (car usig) '|::|)
diff --git a/src/julia-syntax.scm b/src/julia-syntax.scm
index 78bdb2cd76d..cd289d4a2b0 100644
--- a/src/julia-syntax.scm
+++ b/src/julia-syntax.scm
@@ -1169,6 +1169,8 @@
                                           v))
                                     anames))
                        ,@(cddr e)))))
+        ((and (length= e 2) (symbol? (cadr e)))
+           (expand-forms `(function ,(symbol (string #\@ (cadr e))))))
         (else
          (error "invalid macro definition"))))
```
?
Also count me out of the discussion.

**Comment by stevengj** [comment]
It seems worthwhile to support this, if only for the sake of consistency.  We allow zero-argument functions, after all.

**Comment by vtjnash** [comment]
@fcard that patch looks like a good start to me. I assume this will also need support in the docs system (to detect it as a macro declaration for your original purpose of using this for doc strings), and it'll need a test.

**Comment by fcard** [comment]
FYI, the relevant line to change in the docsystem is [this one](https://github.com/JuliaLang/julia/blob/80369bf7b49959d28837e764b41621456ae0e32e/base/docs/Docs.jl#L682).

```diff
- isexpr(x, :function) && !isexpr(x.args[1], :call) ? objectdoc(source, mod, meta, def, x) :
+ isexpr(x, [:function, :macro]) && !isexpr(x.args[1], :call) ? objectdoc(source, mod, meta, def, x) :
```
And I think that does it.
Tragically that messes with the whitespace alignment, so it can't just be a one line fix :/

Tests could be (in *test/core.jl*?)
```julia
# issue 22098
macro m22098 end
@test_throws MethodError @eval @m22098()
```
Mimicking the [test for zero-method functions](https://github.com/fcard/julia/blob/45964f86b85995cbcde72dcb4e5a873a856e6312/test/core.jl#L2910-L2913). (minus the `isa Function` test because I don't see any documentation or test explicitly stating that `macro m end` will always result in a`@m` function)

and (*test/docs.jl*)
```julia
# issue 22098
"an empty macro"
macro mdoc22098 end
@test docstrings_equal(@doc(:@mdoc22098), doc"an empty macro")
```

<sub>I still don't get that comment simply pointing me to documentation and the support it got. I know how macros work, silly.</sub>

**Comment by KristofferC** [comment]
When you have an issue description so unclear as the first post people might misunderstand you. When you said "I personally wanted this for docstring purposes" it looked like you wanted to know how to define a macro without having to give the arguments to it which is what the linked documentation did.

**Comment by fcard** [comment]
sorry

**Comment by yuyichao** [comment]
Also, if you look at the second part of that document, it also clearly tell you the syntax for documenting an macro independent of it's definition, which afaict it what you claim you actually want.

Zero argument macros are much less useful than functions since dispatch on them doesn't work the same (and dispatching is much less useful on macros). Having them just for some sort of consistency should be fine too though....

**Comment by fcard** [comment]
You can't document a macro if it doesn't exist.
```julia
julia> "---" :@m
ERROR: UndefVarError: @m not defined
```
Which is what I want (maybe the docsystem can be made to document non-existing macros too? iunno)

Or rather, what led me to realize that I can't do it. I actually had a paragraph about consistency originally, and another one about flexibility of organizing files, examples and all, but took it all out because I don't want to be part of this conversation.

The only contributions I want to make are suggestions and code. I hate arguing.
I did deserve the lecture after making that stupid aside, but if we could all delete these last few comments as off-topic I'd be down for that.

**Comment by JeffBezanson** [comment]
There's nothing wrong with allowing zero-method macros; I don't think anybody's seriously against them. @fcard Please feel free to make a PR with your changes.

**Comment by vtjnash** [comment]
Agreed. I think this was a good suggestion. Did you mean to make the PR (https://github.com/fcard/julia/pull/10) against your own repo and slyly link it to the `?` above?

**Comment by fcard** [comment]
Busted! I linked to that in several of my comment drafts but in the end decided to just hide it there as an easter egg or something. But since that's done, I will just throw it out there that one can get the [PR as a patch file](https://github.com/fcard/julia/pull/10.patch) and start their own from that, ICYDK. Here, I will even give you this nifty shell command:
```sh
git apply <(wget -O - 'https://github.com/fcard/julia/pull/10.patch')
```
...As you know, I don't like PRs very much, so if somebody wants to make one feel free to use that. Otherwise, I will make one... Eventually.
