### ISSUE TITLE
Printing of Signature in libgit2

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#22103]
[Here:](https://github.com/JuliaLang/julia/blob/f67f58e525f7b11517e6f77135a767e3a38f2f4d/base/libgit2/signature.jl#L38) the unix time is computed as: `sig.time + sig.time_offset`. However, the  [docs for `TimeStruct`](https://github.com/JuliaLang/julia/blob/f67f58e525f7b11517e6f77135a767e3a38f2f4d/base/libgit2/types.jl#L47) says: `offset::Cint    # timezone offset in minutes`.

Should there be a `*60` on the `sig.time_offset` in show?

**Comment by simonbyrne** [comment]
Why don't we just print the time + offset, like command line git does?
