### ISSUE TITLE
Move remaining editor supports

### ISSUE THREAD

**Issue by femtotrader** [JuliaLang/julia#22106]
Hello,

following https://github.com/JuliaEditorSupport/JuliaEditorSupport/issues/4#issuecomment-304498699
pinging @oxinabox @davidanthoff @tkelman

There are 6 remaining editor supports in this repository.

They should probably be moved to repositories in https://github.com/JuliaEditorSupport/ GitHub org

Acccording https://github.com/JuliaLang/julia/tree/master/contrib#editors---debuggers

There are:

- ack/ag
- ctags
- Colorer
- GtkSourceView
- ~Notepad++~

Kind regards

**Comment by femtotrader** [comment]
We can see 2 ideas:

- 1 repository per editor support
- 1 repository for all these small files

**Comment by tkelman** [comment]
ack and ctags are for searching within this repo, I think?

also the file for kate/kwrite

if there's code reuse to be had in automatically populating or updating multiple of these at once, then a common repo makes sense to me. if not, small repos for each editor is also fine, don't think it matters much. +1 on moving them though

**Comment by davidanthoff** [comment]
I agree, both strategies seem fine to me.

**Comment by oxinabox** [comment]
>ack and ctags are for searching within this repo, I think?

AFAICT, ackrc is a normal ackrc file, not bound to the repo at all.
It even features shebang line support, and I don't think there are any files in the repo using that.
Also, it is two lines long...
https://github.com/JuliaLang/julia/blob/master/contrib/ackrc

Similar the ctags file looks like a normal ctags config file. 
Not a generated ctags file for this repo, but the configuration used to generate one.
It is a regex looking for function declarations,
which IIRC is what exuberant ctags eats for configuration.
It is 5 lines long.
https://github.com/JuliaLang/julia/blob/master/contrib/ctags
I know there are a few other julia ctags configurations floating around.
I think maybe @Evizero has one?

**Comment by Evizero** [comment]
> I think maybe @Evizero has one?

Not really. I only have a slightly modified one that is actually incorrect, but more convenient for me to use with CtrlP in vim to jump around in a project

**Comment by ViralBShah** [comment]
+1 to moving editor support out of Base.

**Comment by scls19fr** [comment]
See https://github.com/JuliaEditorSupport/roadmap/issues/5 about moving Notepad++ support from Base to [JuliaEditorSupport](https://github.com/JuliaEditorSupport/)

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/pull/32021 should move `ack` out. Even if we decide to leave it in contrib, this issue can be closed.
