### ISSUE TITLE
Wrong paths for docstrings

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#22105]
It seems that the `:path` data items for docstrings (`DocStr`) do not get populated properly anymore. Documenter uses it to filter methods by file.

```julia
julia> using Documenter
julia> x = (Docs.meta(Documenter) |> first).second.docs;
julia> first(x).second.data
Dict{Symbol,Any} with 5 entries:
  :typesig    => Tuple{}
  :module     => Documenter
  :linenumber => 57
  :binding    => Documenter.deploydocs
  :path       => "docs/Docs.jl"
```

On 0.6.0-rc2:
```julia
julia> first(x).second.data
Dict{Symbol,Any} with 5 entries:
  :typesig    => Tuple{}
  :module     => Documenter
  :linenumber => 57
  :binding    => Documenter.makedocs
  :path       => "/home/morten/Julia/pkg/v0.6/Documenter/src/Documenter.jl"
```

Interestingly, the docstrings for base seem fine on master:
```julia
julia> x = (Docs.meta(LinAlg) |> first).second.docs;
julia> first(x).second.data
Dict{Symbol,Any} with 5 entries:
  :typesig    =>  …
  :module     => Base.LinAlg
  :linenumber => 527
  :binding    => Base.LinAlg.lowrankupdate!
  :path       => "linalg/cholesky.jl"
```

**Comment by tkelman** [comment]
would help to bisect when it went wrong

**Comment by mortenpi** [comment]
It appears it was introduced in #21746. @vtjnash? I guess the problem could be [`base/docs/Docs.jl#L499`](https://github.com/JuliaLang/julia/blob/82e96382251a1e163860df03c846acec86d07c36/base/docs/Docs.jl#L499)?

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/21746 isn't on release-0.6 though...

**Comment by mortenpi** [comment]
Nope, the issue is with master/0.7. No worries if there isn't time to look into this now, it's a relatively obscure feature of Documenter that doesn't work properly on the nightlies. I just wanted to write up what I found since I was trying to figure out why the nightly tests fail on Documenter.

**Comment by tkelman** [comment]
Oh, I misread

> the docstrings for base seem fine on master:

then.

**Comment by vtjnash** [comment]
Thanks for the catch. I didn't realize I had the fix for this was trapped on https://github.com/JuliaLang/julia/pull/22064.
