### ISSUE TITLE
:macrocall expression broken in many packages

### ISSUE THREAD

**Issue by getzdan** [JuliaLang/julia#22116]
Packages which generate expressions including `:macrocall` seem to have been broken a few days ago.
These include DataArrays and BenchmarkTools.
A possible culprit (by noting commit message) is https://github.com/JuliaLang/julia/commit/fcdf4376415fde3b76faeb1c6f6841735497c8ea .

As an example, with BenchmarkTools:
The line: https://github.com/JuliaCI/BenchmarkTools.jl/blob/42e6e66989b098dd4f6212ddfec18d63402197e2/src/execution.jl#L358
probably causes the following error:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.360
Commit 7ffa3bf36d* (2017-05-26 15:00 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> using BenchmarkTools

julia> f(x) = (s = 0; for i=1:x s+= i ; end ; return s)
f (generic function with 1 method)

julia> @belapsed f(1_000_000_000)
ERROR: ArgumentError: tuple must be non-empty

```

while in older version (0.5), things work fine.

The fix I've found so far is to add a `LineNumberNode(@__LINE__)` argument after the `:macrocall`.

**Comment by yuyichao** [comment]
This should be a expected breakage.

**Comment by tkelman** [comment]
would be good to add a deprecation if we can

**Comment by yuyichao** [comment]
I don't think that's possible.

**Comment by getzdan** [comment]
The problem is each package breaks with a different cryptic error message.
If a warning with a link to a description is made in case the second parameter to `:macrocall` is not a LineNumberNode or empty Tuple, it might do the trick.
