### ISSUE TITLE
"invalid age range update" assertion error, present in 0.6RC2 but not 0.6RC1

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#22125]
Apologies again for lack of reduced code snippet since its a tough one to reduce. But I'm seeing the following error (full stack trace [here](https://gist.github.com/marius311/839a310d97879d057e4b79b873ba1b0c))

```
WARNING: An error occurred during inference. Type inference is now partially disabled.
Base.MethodError(f=typeof(Core.Inference.convert)(), args=(Base.AssertionError, "invalid age range update"), world=0x0000000000000ac2)
```

Its reproducible every time on 0.6RC2, but is not present on 0.6RC1.

**Comment by tkelman** [comment]
Seems similar to https://github.com/JuliaLang/julia/issues/21653. Can you bisect, or point to code (a large complicated test case is better than no test case at all) to reproduce?

**Comment by marius311** [comment]
Just bisected, it appears https://github.com/JuliaLang/julia/commit/205bf779fd299bfec04b3a663d1bbdc626e5b62e is the first bad commit. 

I'm happy to provide a test case but unless I can figure out how reduce it further, it requires some not-yet-public code. However, I'm happy to provide that privately to any of you guys that are interested, just let me know if I should go that route.

**Comment by tkelman** [comment]
@vtjnash will be better-equipped to debug inference issues than I will. Is it okay on master? If so, could you reverse-bisect to find what fixed it there? (If your git version is new enough, it'll support `git bisect new` and `git bisect old` which makes bisecting on a bugfix instead of a bug introduction a little easier to keep track of.)

**Comment by marius311** [comment]
Just tried on master but there's errors in other packages that prevent the offending code from running at all unfortunately.

**Comment by vtjnash** [comment]
Yes, I would like to take a look. Emailing me a link at vtjnash@gmail.com usually works pretty well.

**Comment by marius311** [comment]
Hi guys, just want to point out that I just tried and 0.6RC3 doesn't seem to have fixed this problem. The offending code should be in your guys' email. Let me know if there's anything else I can do to help. I think perhaps I need to sit down and really try to reduce this to something more useful...

**Comment by marius311** [comment]
So I spent a bunch of time reducing this error. I think I've got something of some use to you guys, although somewhere along the way I did something without realizing it so that its now happening on 0.6RC1 as well, oops, ha. Maybe that actually makes it easier to debug, I don't know, but the message at least is unchanged from my initial report. 

The crux is something like I import PyCall, define a generated function, then import ImageCore, then do some stuff which trigger some calls to convert and my generated function. I have no idea what's special about those two packages, neither are actually directly used from the code at all. There's a bunch of surrounding details that seem somewhat important too, here's the [full thing](https://gist.github.com/marius311/c0a364923101306586796fac4248e7c7). 

Since this may be important, this is PyCall 1.12.0 and ImageCore 0.3.3.

**Comment by vtjnash** [comment]
The reduced case appears to be fixed by https://github.com/JuliaLang/julia/pull/22340, but not the original issue.

**Comment by StefanKarpinski** [comment]
This should be fixed in 0.6.1 but it shouldn't block 0.6.0 at this point. @vtjnash has a largish PR that could fix this if backported in part or in its entirety, but that's too risky for 0.6.0.

**Comment by acrosby** [comment]
I am getting this error in v0.6.1, is it something I am doing wrong or is this still present? What should I avoid doing?

**Comment by hakanergun** [comment]
Is there any work around for julia 0.6.2? I suddenly started to have this problem under windows 10.
