### ISSUE TITLE
Make method_exists accept symbols and check for return types

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#22145]
Currently when you want to test for the existence of a function with method_exists if you enter a function that does not exist it crashes, which just so inconvient and counter-intuitive. I am checking if the function exist so it does not crash, not to have it crash when it does not. I know I can add a try block around it, but why do I have to do that every single time.
My proposal would be to allow method_exists to accept a symbol which can be evaluated inside method_exists function and you can put the try block in there.

Secondly please let me, at least optionally, also be able to check the return type of the specified function.

**Comment by nalimilan** [comment]
Can you give an example? I'm not sure what you mean by "crash", but I get an `UndefVarError` if the object I'm passing does not exist. You can call `isdefined` first if you're not sure whether the *function* exists.

**Comment by Jackels** [comment]
I am using crash as a synonym for UndefVarError. Yes I could check `isdefined` first, but that again just seems like unecessary logic that could be put into method_exists, otherwise every method_exists will always be accompanied be a preceding `isdefined`, which just shows me that they belong together.

**Comment by yuyichao** [comment]
`method_exists` should not do this. For one thing it doesn't even know what's your current scope.

**Comment by nalimilan** [comment]
`method_exists` checks whether a specific *method* exists for a given type signature. It's often used when you know the *function* exists, but want to check whether a particular type combination implements it.

**Comment by StefanKarpinski** [comment]
This is already closed, but I'm going to agree that whether a name is bound to anything and whether a function object has a particular method signature are totally orthogonal issues and should not be smooshed into a single function. You can, however, write a convenience macro in your own code if you find yourself doing this a lot, although if you find yourself doing that a lot something may be amiss.
