### ISSUE TITLE
[Docs] Make docs on `where` findable

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#22153]
The docs for `where` are [here](https://docs.julialang.org/en/latest/manual/types.html#UnionAll-Types-1), under the uninformative (to the casual user) heading `UnionAll types`, and searching for `where` in the docs search box gives 0 results.

I suggest moving / duplicating / referencing the `where` docs from the `Parametric Types` section. Not sure what to do about the search functionality.

**Comment by yuyichao** [comment]
It is availabe under [parametric method](https://docs.julialang.org/en/latest/manual/methods.html#Parametric-Methods-1), which is where it is the most useful. The search function is probably a Documenter.jl issue...
