### ISSUE TITLE
Incorrect dimension of Pair arrays on 0.5

### ISSUE THREAD

**Issue by Godisemo** [JuliaLang/julia#22157]
I noticed that arrays of Pairs are parsed with incorrect dimensions on Julia version 0.5.2
```
julia> [:a => 1
        :b => 2]
1×2 Array{Pair{Symbol,Int64},2}:
 :a=>1  :b=>2
```
while if the array type is specified, the correct dimension is obtained
```
julia> Pair{Symbol,Int64}[:a => 1
                          :b => 2]
2-element Array{Pair{Symbol,Int64},1}:
 :a=>1
 :b=>2
```

On Julia version 0.6.0-rc2 everything seems to work as expected.
```
julia> [:a => 1
        :b => 2]
2-element Array{Pair{Symbol,Int64},1}:
 :a=>1
 :b=>2

julia> Pair{Symbol,Int64}[:a => 1
                          :b => 2]
2-element Array{Pair{Symbol,Int64},1}:
 :a=>1
 :b=>2
```

**Comment by nalimilan** [comment]
Thanks for the report. If this only affects 0.5 and is already fixed in 0.6, it's kind of late to backport a fix. Some people might even rely on the broken previous behavior. I'd suggest moving to Julia 0.6 if it's possible for your project.
