### ISSUE TITLE
UniformScaling should use parentheses if the scalar is complex

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#22168]
entering `im*I+I` is shown as `1+1im*I` though it calculates as `(1+1im)*I` thus i guess that's some sort of wrong display algorithm.

(Since i've no clue of committing rules i thought that'd be a really easy to fix problem for you and can happen pretty much instant within your normal workflow ^^')

**Comment by sunoru** [comment]
Thanks. It should have parentheses for complex numbers.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/22169
