### ISSUE TITLE
Product of transposed real matrix with complex matrix slower than expected

### ISSUE THREAD

**Issue by langfeldt** [JuliaLang/julia#22178]
When computing the matrix product of a transposed real matrix with a complex matrix, I encountered a performance issue.

Consider the following computations:

```
julia> A=randn(1000,1000);
julia> B=randn(1000,1000);
julia> Z=complex(randn(1000,1000),randn(1000,1000));
julia> # pre-compiling
julia> A'*B;
julia> A'*Z;
julia> complex(A'*real(Z),A'*imag(Z));
julia> # timing
julia> @time A'*B;
  0.025224 seconds (130 allocations: 7.637 MB)
julia> @time A'*Z;
  1.899244 seconds (6 allocations: 15.259 MB)
julia> @time complex(A'*real(Z),A'*imag(Z));
  0.062084 seconds (16 allocations: 45.777 MB, 8.73% gc time)
```

The latter two computations are mathematically identical, however the last (more complex) expression is ~30x faster (and only ~2 times slower than the corresponding real-real product, as one would expect) than the straightforward expression `A'*Z`. Shouldn't both expressions be comparable in performance?

I am running Julia 0.5.2 on Ubuntu 14.04.

sysinfo() output:
```
Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by KristofferC** [comment]
When `A` and `Z` are different type this falls back to the generic matrix multiplication routine. This should probably do two matrix multiplication with stride 2 for `Z`.

**Comment by andreasnoack** [comment]
> This should probably do two matrix multiplications with stride `2` for `Z`.

`gemm` doesn't support that. A simpler solution just to promote the real matrix but it is a bit costly for very small matrices.

**Comment by KristofferC** [comment]
Yeah sorry, that only works for `gemv`. Maybe best with a heuristic threshold on the size?

**Comment by andreasnoack** [comment]
> Maybe best with a heuristic threshold on the size?

We should probably to that although the dispatch in the matmul code is already pretty complicated so I'm not super excited about adding more to it.

**Comment by fredrikekre** [comment]
duplicate-ish of #20060

**Comment by KristofferC** [comment]
Yeah, similar enough, let's continue there to not split the discussion.
