### ISSUE TITLE
using SIMD hangs on master

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#22171]
`using SIMD` (https://github.com/eschnett/SIMD.jl) hangs Julia (runs at 100% CPU). This is a regression compared to v0.6-rc2 where it takes a second to load.

**Comment by fredrikekre** [comment]
It's 8bacb65bbab9cbb7da2a266dc384cdd62df372aa

**Comment by KristofferC** [comment]
cc @vtjnash

**Comment by vtjnash** [comment]
I suppose this is the ultimate sort of punishment for defining a method ambiguity.
```
Tuple{typeof(Base.:(!=)), SIMD.Vec{N, T}, Union{Bool, Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128, Float16, Float32, Float64}} where T<:Union{Float16, Float32, Float64} where N
Tuple{typeof(Base.:(!=)), SIMD.Vec{N, T}, Union{Bool, Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128}} where T<:Union{Bool, Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128} where N
```
(the author probably intended to write `Union{(SIMD.Vec{N, T} for T in outer_union)...}`, but instead has an ambiguity when using objects of type `SIMD.Vec{N, Union{}}`)
