### ISSUE TITLE
cholfact[!] does not respect the uplo character

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#22187]
`cholfact` and `cholfact!` has an optional `uplo` input to only consider the upper/lower part of the matrix, but this is not taken into account when checking `ishermitian()`. For instance:

```julia
julia> A = [2. 1.; 0. 2.]
2×2 Array{Float64,2}:
 2.0  1.0
 0.0  2.0

julia> cholfact(A, :U)
ERROR: ArgumentError: matrix is not symmetric/Hermitian. This error can be avoided by calling cholfact(Hermitian(A)) which will ignore either the upper or lower triangle of the matrix.
Stacktrace:
 [1] cholfact(::Array{Float64,2}, ::Symbol) at ./linalg/cholesky.jl:344
```

This faulty behavior is actually also [tested(!)](https://github.com/JuliaLang/julia/blob/093115660130afc79d1eb09929bf9a0bba776822/test/linalg/cholesky.jl#L261-L263).

**Comment by fredrikekre** [comment]
I will push a fix later.

**Comment by andreasnoack** [comment]
This happened in the process of requiring that input is strict Hermitian either by value or `Hermitian`/`Symmetric`. I think the right fix is to remove the `uplo` argument completely. It is simpler only to pass it to the `Hermitian`/`Symmetric` constructors.

**Comment by fredrikekre** [comment]
Yea, thats what I planned.
