### ISSUE TITLE
Export cpad function

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/julia#22184]
for reference, this was started through the following discourse post:

+ https://discourse.julialang.org/t/is-there-native-function-for-cpad-center-version-of-lpad-rpad/4045

-------

summarizing, `cpad`:

+ is not exported
+ doesn't work with symbols
+ seems like it could be extracted w/ other string manipulations into their own package

**Comment by djsegal** [comment]
yes/no/maybe/so?

**Comment by fredrikekre** [comment]
Deprecated in #23187 instead.

**Comment by amanica** [comment]
aah, I found cpad quite useful :'(  .  Is there a String utils package for this sort of thing or should I create it?
