### ISSUE TITLE
`@muladd` macro

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#22217]
One thing we have been making quite a bit of use of in DiffEq is the `@muladd` macro:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/utils.jl#L29

It spits out nested `muladd`s. For example:

```julia
macroexpand(:(@muladd uprev+dt*(a71*k1+a72*k2+a73*k3+a74*k4+a75*k5+a76*k6)))
# (muladd)(dt, (muladd)(a71, k1, (muladd)(a72, k2, (muladd)(a73, k3, (muladd)(a74, k4, (muladd)(a75, k5, a76 * k6))))), uprev)
```

Since Julia doesn't add `muladd` as a default optimization, this is a nice "performance-macro" to sprinkle around and get some FMA operations. Is this a good candidate for Base? I thought others might find this useful.

If it is, there is one issue I have noticed with the current implemented (implementation courtesy of @fcard BTW). I realized it has a funny interaction with `@.`:

```julia
println(macroexpand(:(tmp = OrdinaryDiffEq.@muladd uprev+a*k1)))
#tmp = (muladd)(a, k1, uprev)
println(macroexpand(:(@. tmp = OrdinaryDiffEq.@muladd uprev+a*k1))) 
#tmp .= +.(uprev, *.(a, k1))
```

**Comment by yuyichao** [comment]
It can probably spell `@fastmath`..

**Comment by ChrisRackauckas** [comment]
>It can probably spell @fastmath..

https://github.com/JuliaLang/julia/issues/18654

You mean just add this to `@fastmath`?

**Comment by yuyichao** [comment]
Yes. It won't fix #18654 since it can't combine multiply and add in multiple expressions but the proposed `@muladd` can't do it either.

**Comment by simonbyrne** [comment]
It would be useful to have something that just does floating point contraction (as `@fastmath` as it can do some funny things if you have NaNs), similar to the `-ffp-contract=fast` option in GCC (I think Clang has it as well, but doesn't document it). 

Alternatively, we could combine it with `@simd` which is a similar optimisation, in that it allows limited changes to the order of operations.

**Comment by ChrisRackauckas** [comment]
>It would be useful to have something that just does floating point contraction (as @fastmath can do some funny things if you have NaNs), similar to the -ffp-contract=fast option in GCC (I think Clang has it as well, but doesn't document it).

We released MuladdMacro.jl for this purpose: https://github.com/JuliaDiffEq/MuladdMacro.jl . Base has `@fastmath` for this and then this package does semantic muladd applications via a performance macro. I think this makes the issue pretty much settled for any use case. Thanks @yuyichao!
