### ISSUE TITLE
Change the behavior of `dot` to not conjugate, and introduce an `inner` (product) function

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#22227]
As briefly discussed in #22220 (with relevance to #20978), I suggest removing the conjugating behavior from `dot`, and introducing an `inner` function which does take the adjoint. This is consistent with [numpy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html). The dot notation seems to rarely be used for complex numbers, for which the general inner product terminology ⟨a,b⟩ is more common. Of course, for real numbers, we have `inner == dot`.

I'm not sure where the discussion concerning the recursiveness of the dot product should go. It's been mentioned in #20978, but that doesn't seem to be the main point of that issue.

**Comment by stevengj** [comment]
This seems wrong to me (and will be breaking).  `dot` should denote an inner product.

**Comment by stevengj** [comment]
See also #8300.

**Comment by jebej** [comment]
I suppose the name change is not too important, especially with how breaking it would be. I still think `inner` is more appropriate a name however. I guess I can do `const inner = dot` if I really want to.

> (The recursiveness is essential for it to be an inner product.)

I'm not an expert, but I'd be curious to learn more about this. The only required properties of an inner product space are conjugate symmetry, linearity and positive-definiteness. Would a non-recursive inner product not satisfy those properties?

**Comment by stevengj** [comment]
An inner product needs to give an element of the scalar field.  Since scalar multiplication is done recursively, so must the inner product.

**Comment by jebej** [comment]
I'll close this since most of the discussion is now happening on the PR.

**Comment by ettersi** [comment]
Sorry if this is a stupid question, but did this discussion reach a conlusion? I haven't found any PR where the discussion was continued.
