### ISSUE TITLE
Deprecate `clamp!(A, lo, hi)` for `broadcast!(clamp, A, A, lo, hi)`?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#22236]
Should we deprecate `clamp!(A, lo, hi)` for `broadcast!(clamp, A, A, lo, hi)`? Note the latter can be written `A .= clamp.(A, lo, hi)`.

Related: https://github.com/JuliaLang/julia/pull/22235#discussion_r120257450

Part of #20402

**Comment by ararslan** [comment]
Should be `clamp.(A, lo, hi)`, otherwise I agree.

**Comment by TotalVerb** [comment]
My bad; the argument order for `clamp` is unintuitive to me, but I can understand why `clamp(x, lo, hi)` is read "clamp x between lo and hi".

**Comment by giordano** [comment]
`clamp!` is actually useful if the array isn't a named variable.

**Comment by martinholters** [comment]
You should benchmark against the inplace `foo(a) = a .= clamp.(a, 2, 7)` when comparing to `clamp!`, no?

**Comment by giordano** [comment]
Uhm, almost, you have to allocate the array, first.  Anyway, you're right, in that case `clamp.()` isn't much worse than `clamp!()`.
```julia
julia> using BenchmarkTools

julia> function foo()
           a = randn(10000)
           a .= clamp.(a, -1, 1)
       end
foo (generic function with 1 method)

julia> bar() = clamp!(randn(10000), -1, 1)
bar (generic function with 1 method)

julia> @benchmark foo()
BenchmarkTools.Trial: 
  memory estimate:  78.20 KiB
  allocs estimate:  2
  --------------
  minimum time:     87.944 μs (0.00% GC)
  median time:      93.500 μs (0.00% GC)
  mean time:        96.606 μs (2.87% GC)
  maximum time:     943.194 μs (86.66% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark bar()
BenchmarkTools.Trial: 
  memory estimate:  78.20 KiB
  allocs estimate:  2
  --------------
  minimum time:     84.859 μs (0.00% GC)
  median time:      87.922 μs (0.00% GC)
  mean time:        91.157 μs (3.08% GC)
  maximum time:     950.349 μs (86.95% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by ararslan** [comment]
I actually get that the `broadcast` version is faster, if the random number generation is removed from the functions:
```julia
julia> a = randn(10_000); b = randn(10_000);

julia> f(x) = (x .= clamp.(x, -1, 1)); g(x) = clamp!(x, -1, 1);

julia> @benchmark f($a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     8.120 μs (0.00% GC)
  median time:      8.125 μs (0.00% GC)
  mean time:        8.572 μs (0.00% GC)
  maximum time:     30.056 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     3

julia> @benchmark g($a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     9.607 μs (0.00% GC)
  median time:      9.616 μs (0.00% GC)
  mean time:        9.650 μs (0.00% GC)
  maximum time:     18.138 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by giordano** [comment]
Yes, but I was claiming that `clamp!(x, lo, hi)` is useful when you don't want/need to allocate `x` first, and instead you want to directly assign the result to a new array.

**Comment by Sacha0** [comment]
Perhaps the following alternatives are sufficient? :)
```julia
julia> @benchmark [clamp(randn(), -1, 1) for _ in 1:1000]
BenchmarkTools.Trial:
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     8.782 μs (0.00% GC)
  median time:      9.878 μs (0.00% GC)
  mean time:        11.005 μs (0.00% GC)
  maximum time:     779.968 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark collect(clamp(randn(), -1, 1) for _ in 1:1000)
BenchmarkTools.Trial:
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     8.842 μs (0.00% GC)
  median time:      10.252 μs (0.00% GC)
  mean time:        11.660 μs (0.00% GC)
  maximum time:     675.692 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map(_ -> clamp(randn(), -1, 1), 1:1000)
BenchmarkTools.Trial:
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     8.834 μs (0.00% GC)
  median time:      9.902 μs (0.00% GC)
  mean time:        10.910 μs (0.00% GC)
  maximum time:     651.152 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark (_ -> clamp(randn(), -1, 1)).(1:1000)
BenchmarkTools.Trial:
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     8.877 μs (0.00% GC)
  median time:      10.438 μs (0.00% GC)
  mean time:        12.043 μs (0.00% GC)
  maximum time:     800.743 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark clamp!(randn(1000), -1, 1)
BenchmarkTools.Trial:
  memory estimate:  7.94 KiB
  allocs estimate:  1
  --------------
  minimum time:     8.462 μs (0.00% GC)
  median time:      9.914 μs (0.00% GC)
  mean time:        11.508 μs (0.00% GC)
  maximum time:     662.747 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by TotalVerb** [comment]
‎Note that the behavior of `clamp!(A, lo, hi)` and `‎broadcast!(clamp, A, A, lo, hi)` are exactly identical: there is no excess allocation step.                                                                                                                                                                                                                From: Mosè GiordanoSent: Monday, June 12, 2017 1:15 PMTo: JuliaLang/juliaReply To: JuliaLang/juliaCc: Fengyang Wang; AuthorSubject: Re: [JuliaLang/julia] Deprecate `clamp!(A, lo, hi)` for `broadcast!(clamp, A, A, lo, hi)`? (#22236)Yes, but I was claiming that clamp!(x, lo, hi) is useful when you don't want/need to allocate x first, and instead you want to directly assign the result to a new array.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/JuliaLang/julia","title":"JuliaLang/julia","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/JuliaLang/julia"}},"updates":{"snippets":[{"icon":"PERSON","message":"@giordano in #22236: Yes, but I was claiming that `clamp!(x, lo, hi)` is useful when you don't want/need to allocate `x` first, and instead you want to directly assign the result to a new array."}],"action":{"name":"View Issue","url":"https://github.com/JuliaLang/julia/issues/22236#issuecomment-307911008"}}}

**Comment by StefanKarpinski** [comment]
I have to confess that I don't see the urgency of removing `clamp!`. It seems occasionally useful and `A .= clamp.(A, lo, hi)` is a bit less obvious and requires a name for `A`.

**Comment by fredrikekre** [comment]
Should we go ahead with this since we do the same for `flipbits!` (#27067)?

**Comment by fredrikekre** [comment]
Isn't it a bit weird to keep this one function when we have deprecated essentially all other auto-broadcasting functions?

**Comment by StefanKarpinski** [comment]
What's the alternative spelling again? `A .= clamp.(A, lo, hi)`? I dunno, that just does not seem as convenient as `clamp!(A, lo, hi)`. I actually generally feel like the in-place `clamp!` is more fundamental than `clamp` since clamping data in-place is much more often what you want to do, and `clamp!` only makes sense on a container. Perhaps that's where this is coming from. I am fine with doing away with vectorized `clamp` but keeping vectorized `clamp!`.

**Comment by StefanKarpinski** [comment]
Note that the same argument cannot be made in the other cases: `flipbits!` is clearly not more fundamental than `!` or `~`.

**Comment by fredrikekre** [comment]
Fair enough, guess we can close this issue then.

> I am fine with doing away with vectorized `clamp` but keeping vectorized `clamp!`.

`clamp(::AbstractArray)` where deprecated for v0.6, so thats where we are already.

**Comment by Sacha0** [comment]
> Isn't it a bit weird to keep this one function when we have deprecated essentially all other auto-broadcasting functions?

Regrettably vectorized `float` and `complex` remain as well. I still wholly favor nixing those. Best!

**Comment by StefanKarpinski** [comment]
They remain because they are vector operations, not vectorized operations.

**Comment by KristofferC** [comment]
Make `float` copy?

**Comment by Sacha0** [comment]
> Make float copy?

You mean `float.(A)`? 😄
