### ISSUE TITLE
Unify lpad, rpad and cpad and move to external package

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#22241]
`lpad`, `rpad` and `cpad` would seem to be good candidates to be unified in a `pad` function.

There are a lot of such string manipulation functions that feel like they should be moved from Base to a string manipulation package.

**Comment by KristofferC** [comment]
I don't see any benefit in moving short, pure, julia code that is generally useful to a package.

**Comment by quinnj** [comment]
I could see us making an official `Strings` module that would still be apart of Base/`StdLib`, but yeah, a lot of these functions are usually expected to be in the "default" language.

**Comment by StefanKarpinski** [comment]
We could always just use `https://api.left-pad.io/`

**Comment by KristofferC** [comment]
I don't think this will be moved out of this repo. Perhaps to a String stdlib as part of https://github.com/JuliaLang/julia/pull/25416
