### ISSUE TITLE
Infinite loop in compilation (with AxisArrays)

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#22248]
I tried to distill this so it didn't require AxisArrays with no luck. It seems to be a pretty complex interaction.

```julia
using AxisArrays

A = AxisArray([  1  4  7  10  13
                 2  5  8  11  14
                 3  6  9  12  15], :y, :x)
for C in (A,)
    for op in (sum,)
        C1t = op(C, Axis{:y})
    end
end
```

Making `A` `const` fixes it. Assigning the tuples to variables fixes it. Calling `op` with a numerical dimension instead of an `Axis` fixes it. 

This happens on `master` (`80369bf7b4` as of this post) and is not SIGINTable.

**Comment by iamed2** [comment]
This does not occur on `v0.6.0-rc3`

**Comment by StefanKarpinski** [comment]
So can it be closed then? What's the action here? Bisect to figure out what fixed it?

**Comment by iamed2** [comment]
No, I mean it's upstream from 0.6, on master.

Yeah a bisect would work, hopefully from someone with a more powerful Julia-compiling system (it would certainly take me a while on my laptop).

**Comment by iamed2** [comment]
A bisect might work to find out what introduced this, but since it's such a finicky example that might not find the actual underlying bug.

**Comment by vtjnash** [comment]
Is this fixed by https://github.com/JuliaLang/julia/pull/21933 now?

**Comment by iamed2** [comment]
Yep, looks like that did it 🎉
