### ISSUE TITLE
Add support for rectangular full packed matrix format

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#22259]
Rectangular full packed (RFP) format is a scheme due to Gustavson whereby a triangular matrix (or a triangular part of a symmetric/Hermitian matrix) is stored as a rectangular assembly of a square part and two triangles (one transposed).

Unlike the older packed formats, it allows for efficient processing with level-3 BLAS calls. The advantage over current `Symmetric`, `Triangular`, and `Hermitian` types is the savings of about half the memory.

RFP format is supported directly by LAPACK for some operations (introduced [here](http://www.netlib.org/lapack/lapack-3.2.html)) such as Cholesky factor/invert/solve and triangular solve. LAPACK also has conversion and updating routines.

RFP matrices could be added to Julia as a collection of types (`SymmetricRFP`, `HermitianRFP`, `TriangularRFP`). The LAPACK interface is obvious. Oddly I didn't find much precedent for `getindex`, `setindex!` or `A_mul_B`, but these seem straightforward.

This submission was inspired by @nalimilan's suggestion on [a discourse thread](https://discourse.julialang.org/t/symmetric-matrices/4086/10).

**Comment by andreasnoack** [comment]
I added them to Base back when Julia was young but they never got into real use and, eventually, we moved them to https://github.com/andreasnoack/LinearAlgebra.jl/blob/master/src/rectfullpacked.jl. We should probably play around with them there to figure out how they should look like. An advantage with Base's `Symmetric` etc is that it works for all matrix types whereas the RFP versions are a dense thing only.

**Comment by tkelman** [comment]
A FullPackedMatrices.jl (or RectFullPackedMatrices maybe?) package would be good if there's enough dedicated code for them to split on their own, as with BandedMatrices.jl.

**Comment by nalimilan** [comment]
> An advantage with Base's Symmetric etc is that it works for all matrix types whereas the RFP versions are a dense thing only.

Isn't the advantage of Julia's type system precisely that we can combine generic fallbacks with optimized specialized types where they exist? Ideally we would use an efficient storage for dense matrices, and the current `Symmetric` type would only be used for other cases.

**Comment by tkelman** [comment]
The packed formats often have somewhat worse performance due to the irregularly-strided access, so it's not always strictly better, there's a time-vs-space tradeoff.

**Comment by tkelman** [comment]
Fair enough, but it's a complicated enough memory layout that is pretty LAPACK-specific, and using it by default for Symmetric types on dense matrices could make it more difficult to write generic code.

**Comment by devonwp** [comment]
Just a note: just came across [this](https://stackoverflow.com/questions/8941678/lapack-are-operations-on-packed-storage-matrices-faster), which suggests LAPACK operations may indeed be slower with the packed format. Maybe based on @nalimilan this is outdated though?

**Comment by bjarthur** [comment]
18% slow down for a 2x reduction in memory footprint is an acceptable trade off for some applications i bet.
