### ISSUE TITLE
Precompilation doesn't mix with distribution anymore

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#22252]
I started julia for a distributed cluster using `julia --machinefile [file]`. However, I was unable to load any package, getting error messages like this from every node: 
```
WARNING: Node state is inconsistent: node 10 failed to load cache from /home/juliaclusteradmin/.julia/lib/v0.6/Celeste.ji. Got:
WARNING: can only precompile from node 1
```
rsyncing my entire `.julia` to every node worked fine. However, the workers should be pulling the packages from node 1.

**Comment by andreasnoack** [comment]
@vtjnash Any thoughts here? Basically, I cannot load any packages on workers that don't share the same package folder as the master. This also seems equally broken on 0.4 and 0.5. If I start all processes with `--compilecache=no` it works fine.

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/22252

**Comment by vtjnash** [comment]
I think the issue may have been resolved by https://github.com/JuliaLang/julia/pull/21695?

**Comment by andreasnoack** [comment]
Just updated and I still see the issue.
