### ISSUE TITLE
Provide a FindJulia.cmake file for helping embedding/building against Julia library

### ISSUE THREAD

**Issue by cdsousa** [JuliaLang/julia#22258]
Right now, for helping compile against the Julia dynamic library, the tool *julia-config.jl* is already provided.
It seems however too bare to enable simple use with CMake.

It is possible to find some *FindJulia.cmake* around the web (even one modified by me), however, none seems to work correctly as of v0.6.

It would be nice for Julia to provide an "official" *FindJulia.cmake* itself.

CCing @JayKickliter because of https://gist.github.com/JayKickliter/06d0e7c4f84ef7ccc7a9 and @barche because of https://github.com/JuliaInterop/CxxWrap.jl/blob/master/deps/src/jlcxx/FindJulia.cmake

**Comment by tkelman** [comment]
since this is unlikely to be tested within this repo, it would be better to keep outside. it's less flexible to update and won't be maintained very well if it's put here.

**Comment by cdsousa** [comment]
Ok thanks, better close it then.
