### ISSUE TITLE
Mutating version of `\`

### ISSUE THREAD

**Issue by shivin9** [JuliaLang/julia#22263]
This functionality will be quite helpful in cases where we have to solve a linear equation repeatedly like in 
https://github.com/JuliaMath/IterativeSolvers.jl/blob/master/src/cg.jl#L54
which is a wrapper over the `\` function
https://github.com/JuliaMath/IterativeSolvers.jl/blob/master/src/common.jl#L47

**Comment by KristofferC** [comment]
`A_ldiv_B! `?

**Comment by shivin9** [comment]
It doesn't cover all the cases I guess
`ERROR: LoadError: MethodError: no method matching A_ldiv_B!(::Array{Float64,1}, ::#JAC#64{Array{Float64,1}}, ::Array{Float64,1})`

**Comment by fredrikekre** [comment]
Second argument should be a matrix. Looks like you are talking about [this](https://github.com/JuliaMath/IterativeSolvers.jl/blob/7fd9fd0835fbbab4ffc57f2e5784af462cf32ee4/src/common.jl#L46) function. In-place method of that should probably be implemented in that package.

**Comment by shivin9** [comment]
Yeah I got that, I forgot to define the inplace version of solve! for a function.
Thanks for the help!
