### ISSUE TITLE
Real part of complex dot product

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#22261]
A common enough operation when dealing with complex vectors is taking the real part of the inner product, ie dotr(a,b) = re(dot(a,b)) = sum_i re(ai) re(bi) + im(ai) im(bi). This turns up when evaluating Taylor series of complex-to-real maps, when evaluating quadratic forms (z* A z where A is Hermitian), etc. It is not trivial enough that one can easily define a one-liner that computes this in an optimal way (ie not real(dot(a,b))). Would it be a good idea to add a "dotr" function to base Julia or is this considered namespace pollution?

**Comment by andreasnoack** [comment]
I feel that this falls under our usual "modulizing Julia" discussion. I think it would be ok to export this from the `LinAlg` module but it is probably not a sufficiently common operation to become a `Base` exported function.

**Comment by stevengj** [comment]
This should work for `Vector`, at least:
```jl
dotr{T}(a::Vector{Complex{T}}, b::Vector{Complex{T}}) = dot(reinterpret(T, a), reinterpret(T, b))
```

**Comment by antoine-levitt** [comment]
If anybody is interested I did some benchmarking on this. On a single thread, the `reinterpret` version is consistently slower than `real(dot())`, even for large-ish arrays (which is surprising to me). A dot product of length 2N is faster for small arrays (<~= 1000), but at that point switching to static arrays is much more beneficial anyway. So the benefit in introducing a `realdot` is pretty marginal.

However, OpenBLAS does not multithread the complex dot product, and so even the reinterpret version is better for large arrays. I guess this should rather be fixed in OpenBLAS (opened an issue here: https://github.com/xianyi/OpenBLAS/issues/2221). I'm closing this issue.
