### ISSUE TITLE
@enum in a function does not compile

### ISSUE THREAD

**Issue by jeanpierreboth** [JuliaLang/julia#22285]
```jl
julia> function functionWithEnum()
           @enum State  unexplored =1 explored = 2
           #           return 0
       end
functionWithEnum (generic function with 1 method)


julia> functionWithEnum()
ERROR: error compiling functionWithEnum: unsupported or misplaced expression "block" in function functionWithEnum
```

This with julia 0.5.2 and 
```
julia> versioninfo()
Julia Version 0.6.0-rc2.0
Commit 68e911b (2017-05-18 02:31 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by KristofferC** [comment]
Please don't open multiple issues for the same thing (ref https://github.com/JuliaLang/julia/issues/22284).

What is your use case? A locally defined enum?

**Comment by jeanpierreboth** [comment]
Sorry for the duplicate entry, bad manip.
I was translating a C++ function doing a graph exploration marking vertex after exploration.
I can just use Int instead, but there is a problem with the macro or it must be documented that enum are global...

**Comment by mauro3** [comment]
Type definitions are only allowed in global scope and `@enum` defines a type.  So this is not possible.  However, the error should be clearer.

**Comment by fredrikekre** [comment]
For reference, here is the error for defining a local `struct`:
```julia
julia> function foo()
           struct A end
       end
foo (generic function with 1 method)

julia> foo()
ERROR: error compiling foo: type definition not allowed inside a local scope
```

**Comment by jeanpierreboth** [comment]
OK. Clearer.
