### ISSUE TITLE
macro  @enum  in function does not not compile

### ISSUE THREAD

**Issue by jeanpierreboth** [JuliaLang/julia#22284]
If you have a question or are unsure if the behavior you're experiencing is a bug,
please search or post to our Discourse site: https://discourse.julialang.org. We use
the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by jeanpierreboth** [comment]
Just a function as

function functionWithEnum()
    @enum State  unexplored =1 explored = 2
    return 0
end

does :
julia> functionWithEnum()
ERROR: error compiling functionWithEnum: unsupported or misplaced expression "block" in function functionWithEnum
 with julia 0.5.2 and 0.6.rc2

**Comment by KristofferC** [comment]
What is your use case? A locally defined enum?
