### ISSUE TITLE
[Julia 0.5.1] option --track-allocation not write *.mem files on Windows 10

### ISSUE THREAD

**Issue by emanueleciola** [JuliaLang/julia#22294]
If I start Julia with the --track-allocation=user/all option, when I try to quit it I get the error message:

_ERROR: LoadError: ReadOnlyMemoryError()
 in exit() at .\initdefs.jl:22_

Clearly, my current working directory is not read only.
I also tried the sample code from the #9654 issue and I get the error anyway.

```
function f(n)
    m = 2*n  # first line is weird if called from REPL, so do something simple
    A = Array(Float64, n)
end

f(20)
Profile.clear_malloc_data()
f(20)
exit()
```

Anyone can tell me why Julia can not write the *.mem file?
Thank you

Here is my info:

_Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)_

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/21289

**Comment by yuyichao** [comment]
And if it still happens on later version you should comment there.
