### ISSUE TITLE
Using a dot, `.`, at the end for defining a float number doesn't always work

### ISSUE THREAD

**Issue by i-apellaniz** [JuliaLang/julia#22308]
It is usual to me to convert an integer using a dot at the end, e.g., `4` as integer and `4.` as a float point number. 
When some operator is next to the dot it doesn't belong anymore to the number but to the operator. I haven't seen this reported, so here it goes an example
```julia
julia> 1+2 # It gives an Int as expected
3 
julia> 1+2. # This way we obtain a Float
3.0
julia> 1.+2 # It is somehow inconsistent with the above use of the dot since we obtain an Int
3
julia> 1. +2 # A space solves it.
3.0
```

I would propose for the dot to belong to the digit.

Just to give a use case where special care must be taken, at least from my perspective
```julia
julia> function foo(x)
       x^20
       end
julia> foo(20)
-2101438300051996672
julia> foo(20.)
1.048576e26
```
whereas if one goes directly to the exponent and writes `20^20` and `20.^20`, they are both equally wrong.

**Comment by i-apellaniz** [comment]
Just to give you a use case where special care must be taken, at least from my perspective
```julia
julia> function foo(x)
       x^20
       end
julia> foo(20)
-2101438300051996672
julia> foo(20.)
1.048576e26
```
whereas if one goes directly to the exponent and writes `20^20` and `20.^20`, they are both equally wrong.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/19089
