### ISSUE TITLE
macro hygiene bug

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#22307]
this is a bit convoluted to come up with a good example, but macro hygiene is wrong for macros that return calls to macros:
```julia
# time: 2017-06-08 18:41:45 EDT
# mode: julia
        macro a()
          esc(:a)
        end
# time: 2017-06-08 18:41:58 EDT
# mode: julia
        macro b()
          :(@a)
        end
# time: 2017-06-08 18:42:16 EDT
# mode: julia
        function c()
          a = 1
          return @b
        end
# time: 2017-06-08 18:42:22 EDT
# mode: julia
        a = 2
        @test c() == 2
```

It seems like we're running hygiene over the AST before recursively expanding macros, whereas we should be doing it afterwards.

**Comment by JeffBezanson** [comment]
Maybe a good opportunity to revisit #10940.
