### ISSUE TITLE
REPL: delete key doesn't work (st)

### ISSUE THREAD

**Issue by Las1** [JuliaLang/julia#22323]
When running julia on the st terminal [0] the 'Delete' key doesn't have any effect.
After looking at their FAQ [1] I am lead to believe this is a bug in Julia and not in st.
A fix so that Julia follows the standard would be really welcomed. It's a minor annoyance not to be able to use Del.
Thank you.

[0] http://st.suckless.org/
[1] http://git.suckless.org/st/plain/FAQ (Why doesn't the Del key work in some programs?)

**Comment by StefanKarpinski** [comment]
I'm a bit confused by the logic here – the delete key works in other terminals and doesn't work in the st terminal, which has a FAQ section on why the delete key doesn't work. Doesn't that suggest that the issue is with st rather than Julia?

**Comment by rfourquet** [comment]
The delete key works for me in Julia within st. What doesn't is this key from within tmux, using julia or not, so this would suggest a problem between tmux and st. Closing for now as I cannot reproduce, please @Las1 comment here if you want to confirm the bug even when not using tmux or a similar layer.
