### ISSUE TITLE
Inconsistency between `findmax` and `maximum` with respect to `NaN`

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#22337]
I read [this discussion](https://github.com/JuliaLang/julia/pull/12563) about `max` and `maximum` returning `NaN` when the collection includes `NaN`.  For example,

```julia
julia> VERSION
v"0.7.0-DEV.82"

julia> v = [1.0, NaN, 2.0]
3-element Array{Float64,1}:
   1.0
 NaN
   2.0

julia> maximum(v)
NaN
```

However,  `findmax` still returns the maximum among non-NaN values and its index:
```julia
julia> findmax(v)
(2.0, 3)
```

This seems inconsistent.  Is this something intended or a bug?

**Comment by StefanKarpinski** [comment]
Seems like findmax needs to be updated to match maximum. There should also be tests to check that they agree.

**Comment by ararslan** [comment]
Note that the behavior of `findmax` is documented to skip `NaN`s: https://docs.julialang.org/en/latest/stdlib/collections/#Base.findmax-Tuple{Any}

> `NaN` values are ignored, unless all elements are `NaN`.

**Comment by StefanKarpinski** [comment]
Yes, it's documented to do this. The question is whether it should be changed to match `maximum` or not. It seems to me that these functions should have matching behavior.

**Comment by ararslan** [comment]
Right, I'm just addressing "is this something intended or a bug." I agree that the behaviors should match.

**Comment by cafaxo** [comment]
In 1.1, this works correctly:
```julia
julia> v = [1.0, NaN, 2.0]
3-element Array{Float64,1}:
   1.0
 NaN  
   2.0

julia> findmax(v)
(NaN, 2)

julia> maximum(v)
NaN
```
I think this issue can be closed.

**Comment by StefanKarpinski** [comment]
Seems like it on both counts. Thanks!
