### ISSUE TITLE
Performance Regression while collecting a UnitRange

### ISSUE THREAD

**Issue by shivin9** [JuliaLang/julia#22336]
When I do `y = collect(1:1.0:10).^2`, in Julia v0.6-rc3 and in v0.5.2, there is a severe performance regression (~10000x in terms of time and memory)
In v0.6-rc3
``` julia
julia> @time y = collect(1:1.0:10).^2;
  1.181859 seconds (101.86 k allocations: 5.693 MiB)

julia> @time y = collect(1:1.0:10).^2;
  0.027665 seconds (4.06 k allocations: 228.951 KiB)
``` 
vs
``` julia
julia> @time y = collect(1:1.0:10).^2;
  0.082686 seconds (78.11 k allocations: 3.360 MB)

julia> @time y = collect(1:1.0:10).^2;
  0.000006 seconds (8 allocations: 576 bytes)
``` 
in v0.5.2.

Is  this a bug or am I doing something wrong? Can anyone confirm this by reproducing a similar result?

**Comment by yuyichao** [comment]
This is expected due to the new semantic of dot operator. Don't benchmark in global scope.

**Comment by timholy** [comment]
In case it's not clear, what @yuyichao is suggesting is that you put that in a function and then benchmark the function.

**Comment by DNF2** [comment]
```
julia> using BenchmarkTools

julia> @btime y = collect(1:1.0:10).^2;  # note the 'b'
  310.195 ns (3 allocations: 384 bytes)

julia> @time y = collect(1:1.0:10).^2;  # no 'b'
  0.025663 seconds (4.06 k allocations: 228.732 KiB)
```
Also, in case it matters:
```
julia> @btime y = (1:1.0:10).^2;
  269.381 ns (1 allocation: 160 bytes)
```

**Comment by shivin9** [comment]
@timholy Yeah I understand. Missed the basic rule about not judging performance be running on REPL.
Thanks for the clarifications BTW!
