### ISSUE TITLE
Pkg.dir(pkg) does not always return path to package pkg.

### ISSUE THREAD

**Issue by richardreeve** [JuliaLang/julia#22357]
The [docs](https://github.com/JuliaLang/julia/blob/4aeb2d499686beab0e66978e8719357387dc1b25/base/pkg/pkg.jl#L71) for `Pkg.dir()` say *"In particular, `Pkg.dir(pkg)` returns the path to the package `pkg`."* However @tkelman points out in richardreeve/Phylo.jl#2 that this doesn't happen when `LOAD_PATH` is set. As a result there's no way of finding the path to a file in an installed package (from outside that package), which is extremely desirable if, for instance, you want to install a resource with a package for reference. If this is right, this seems like a bug as it conflicts with the documented behaviour...

**Comment by tkelman** [comment]
duplicate of https://github.com/JuliaLang/julia/issues/8679
