### ISSUE TITLE
Changes for new BinaryFormat module in llvm-svn

### ISSUE THREAD

**Issue by singam-sanjay** [JuliaLang/julia#22362]
Quoting from https://reviews.llvm.org/D34001,
> A new library named ``BinaryFormat`` has been created which holds a collection
> of code which previously lived in ``Support``.  This includes the
> ``file_magic`` structure and ``identify_magic`` functions, as well as all the
> structure and type definitions for DWARF, ELF, COFF, WASM, and MachO file
> formats.

This change has to reflect in Julia since it's using files and types including <llvm/Support/MachO.h>, <llvm/Support/COFF.h>, and struct file_magic. I made the following simple changes and the code compile (although I do not know if it preserves the semantics),
```
diff --git a/src/debuginfo.cpp b/src/debuginfo.cpp
index 11ac809..547f6ce 100644
--- a/src/debuginfo.cpp
+++ b/src/debuginfo.cpp
@@ -31,6 +31,7 @@
 #endif
 #include <llvm/Object/MachO.h>
 #include <llvm/Object/COFF.h>
+#include <llvm/BinaryFormat/Magic.h>
 #if JL_LLVM_VERSION >= 30700
 #  include <llvm/Object/ELFObjectFile.h>
 #endif
@@ -1009,7 +1010,7 @@ openDebugInfo(StringRef debuginfopath, const debug_link_info &info)
 
     auto error_splitobj = object::ObjectFile::createObjectFile(
             SplitFile.get().get()->getMemBufferRef(),
-            sys::fs::file_magic::unknown);
+            file_magic::unknown);
     if (!error_splitobj) {
 #if JL_LLVM_VERSION >= 30900
         return error_splitobj.takeError();
@@ -1181,7 +1182,7 @@ bool jl_dylib_DI_for_fptr(size_t pointer, const llvm::object::ObjectFile **obj,
         std::unique_ptr<MemoryBuffer> membuf = MemoryBuffer::getMemBuffer(
                 StringRef((const char *)fbase, msize), "", false);
         auto origerrorobj = llvm::object::ObjectFile::createObjectFile(
-            membuf->getMemBufferRef(), sys::fs::file_magic::unknown);
+            membuf->getMemBufferRef(), file_magic::unknown);
 #elif JL_LLVM_VERSION >= 30500
         MemoryBuffer *membuf = MemoryBuffer::getMemBuffer(
             StringRef((const char *)fbase, msize), "", false);
diff --git a/src/disasm.cpp b/src/disasm.cpp
index 2e30877..ff0929c 100644
--- a/src/disasm.cpp
+++ b/src/disasm.cpp
@@ -28,8 +28,8 @@
 
 #include "llvm-version.h"
 #include <llvm/Object/ObjectFile.h>
-#include <llvm/Support/MachO.h>
-#include <llvm/Support/COFF.h>
+#include <llvm/BinaryFormat/MachO.h>
+#include <llvm/BinaryFormat/COFF.h>
 #include <llvm/MC/MCInst.h>
 #include <llvm/MC/MCStreamer.h>
 #include <llvm/MC/MCSubtargetInfo.h>
```
If these are the correct changes, I would like to submit a PR, and would need some guidance on writing LLVM version compliant code.

**Comment by yuyichao** [comment]
You are using a Julia version without https://github.com/JuliaLang/julia/pull/22271

**Comment by singam-sanjay** [comment]
Thanks for pointing it out !

However, the header files llvm/Support/COFF and llvm/Support/MachO.h still need to be replaced by llvm/BinaryFormat/COFF.h and llvm/BinaryFormat/MachO.h respectively.

```
/home/sanjay/Software/julia/julia_src/src/disasm.cpp:31:32: fatal error: llvm/Support/MachO.h: No such file or directory
 #include <llvm/Support/MachO.h>
```

**Comment by yuyichao** [comment]
Seems that my local build picks up system llvm headers. It's a bit strange that there's no error/conflict when it does this, it usually does.....

Anyway, yeah, the includes still needs to be fixed. The linked PR should give you enough example of how llvm version conditions are written.

**Comment by singam-sanjay** [comment]
Please check #22371
