### ISSUE TITLE
a bug? relevant for > 0.4.6

### ISSUE THREAD

**Issue by rudolfII** [JuliaLang/julia#22378]
Hello,

the following code behaves unexpectedly:

if 1>0
	beta = 0.5
	print("1. beta=",beta,"\n")

	for i1=1:2
	end

	print("2. beta = ", beta, "\n")
end
print("3. beta = ", beta, "\n")

It produces:

    beta=beta
    beta = beta
    beta = 0.5
    WARNING: imported binding for beta overwritten in module Main

while if you comment out the for cycle, you always get the
expected beta = 0.5.

Please note that the result shown above is only seen
if the kerner runs for the first time over the code.

Also note, it's not the warning but the printing of 'beta=beta'
that bothers us.

Version 0.4.6 behaves, in contrast, as expected (we get 0.5).

Thanks for your work
Ruda

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/2586 and https://github.com/JuliaLang/julia/issues/21989

**Comment by JeffBezanson** [comment]
Also related to #18933 I'd say.
