### ISSUE TITLE
function call calls old function

### ISSUE THREAD

**Issue by kungfooman** [JuliaLang/julia#22387]
Minimal example:

```
evaluate(code) = ccall(:jl_parse_eval_all, Any, (Cstring, Cstring, Csize_t), "hurr.jl", code, sizeof(code))

function test()
	print("111\n")
end

function main2()
	test() # prints 111 (correct)
	evaluate("function test() print(\"222\n\") end")
	test() # prints 111 (wrong, imo)
end

function main()
	test() # prints 111 (correct)

	main2()

	test() # prints 111 (wrong, imo)
end

main()

test() # prints 222 (correct)

```

The output is:

```
111
111
111
111
222
```

Why is this? I really need this working, otherwise I cannot update any functions at runtime in my application from "within". Is there any way to force-update the function pointers or something?

**Comment by Keno** [comment]
You're looking for `Base.invokelatest`. Also, this kind of thing is generally discouraged.

**Comment by kungfooman** [comment]
What is the proper way then? I simply made a REPL and I wanna use it to update functions etc.

I don't want to call every function via `Base.invokelatest`, just because the REPL might have updated it.

**Comment by Keno** [comment]
Depends on what you want to do. We do not implement on-stack replacement (nor do we intend to add it), so if you want to update calls that are already in functions on that stack, those would indeed have to go through `invokelatest`. In typical scenarios, the REPL is at the top level, and a single `invokelatest` is sufficient.

**Comment by kungfooman** [comment]
Thank you alot, that makes sense. I've put my main loop body inside a function now and call only that one via Base.invokelast(), works great. :)
