### ISSUE TITLE
Plots: can't disable the colorbar in heatmap

### ISSUE THREAD

**Issue by ko56** [JuliaLang/julia#22384]
I am trying to display a heatmap without the colorbar.  In Julia 0.5.1 (on FreeBSD), neither
legend=false, nor colorbar=false, nor both of these succeed in eliminating the colorbar.

**Comment by ko56** [comment]
I forgot to mention that the problem occurs with the plotly back-end.  It does not occur with the PyPlot back-end.

**Comment by fredrikekre** [comment]
This is an issue for the [Plots.jl](https://github.com/JuliaPlots/Plots.jl) repository. You might also consider asking questions on the [discourse forum](https://discourse.julialang.org/) instead.

**Comment by ko56** [comment]
Yes, sorry, I should have opened the issue there.  There has already been discussion in the discourse forum.
