### ISSUE TITLE
Actually decouple special function (openspecfun) from base

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#22390]
`SpecialFunctions` relies on `openspecfun` from  Base. Like `FFTW` would the next logical step be to have `SpecialFunctions` actually carry out the build process instead of in base

**Comment by ararslan** [comment]
This is on my to-do list, we just need a pure Julia implementation of `rem2pi`. That's the only thing in Base that still uses openspecfun.

**Comment by ararslan** [comment]
Regarding a Julia implementation, ref discussion in https://github.com/JuliaLang/julia/issues/22004

**Comment by musm** [comment]
BTW there is https://github.com/JuliaLang/openlibm/blob/1581174c85f7b645b15ba1ac1c3a98fb601f0fe7/src/e_rem_pio2.c 

in openlibm which exactly the same as the openspecfun code ... but perhaps to call it some minor modification would need to be made to the C lib ?

**Comment by ararslan** [comment]
If I'm not mistaken, it's not standard to have that in system libms. Since we allow building with a libm other than openlibm but we don't allow any special function library other than openspecfun, we're likely calling it from openspecfun instead to ensure the function is always available.

**Comment by StefanKarpinski** [comment]
This doesn't actually affect any Base APIs, does it? If so, it's a non-breaking change and can be removed from the 1.0 milestone.

**Comment by tkelman** [comment]
Removing a library that people have been calling into and assuming gets shipped with julia binaries sounds breaking to me.

**Comment by ararslan** [comment]
Yeah, it's definitely breaking for anyone who could be `ccall`ing. This is a pretty easy removal anyway so I should have no trouble getting this out in the 1.0 timeframe.
