### ISSUE TITLE
names: __module__ and __source__ implicit macro arguments

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#22406]
The recently-added implicit arguments to macro – `__module__` and `__source__` are not terribly evocatively named. Can you guess what they do? I can't. Let's pick some less ad hoc, more suggestive names for these. I'd also like to suggest considering making their structures more symmetrical. There are fundamentally two contexts that a macro needs to know about: where it's defined and where it's called. Should there be a single, general way to represent a code context?

**Comment by StefanKarpinski** [comment]
cc: @vtjnash, @JeffBezanson

**Comment by vtjnash** [comment]
I like the symmetry of `__module__` and `@__MODULE__`, but as long as they remained similarly paired, I wouldn't be opposed any alternative naming strategies.

**Comment by JeffBezanson** [comment]
Could you expand on what more symmetrical would mean? Line numbers and modules are really different beasts; the former is just debug info, while the latter is critical for the behavior of some macros. Another distinction is that all code needs to and can access its own module easily, by name or via @__MODULE__, but accessing a call context only makes sense for macros.

**Comment by goretkin** [comment]
https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore , right?
