### ISSUE TITLE
Exception running test libgit2

### ISSUE THREAD

**Issue by ajgiuliani** [JuliaLang/julia#22407]
I ran /julia -e "Base.runtests()" to test an homebrew installation of julia on MacOS 10.10.5.  I got the following the following error:
```
Exception running test libgit2 :
On worker 2:
LoadError: There was an error during testing
 in record at ./test.jl:397
 in do_test at ./test.jl:281
 in #198 at /usr/local/Cellar/julia/0.5.1/share/julia/test/libgit2.jl:221
 in mktempdir at ./file.jl:286
 in mktempdir at ./file.jl:284
 in include_string at ./loading.jl:441
 in jlcall_include_string_33141 at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20276 at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in macro expansion at ./util.jl:230 [inlined]
 in runtests at /usr/local/Cellar/julia/0.5.1/share/julia/test/testdefs.jl:7
 in #24 at /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl:44
 in #645 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #644 at ./event.jl:68
while loading /usr/local/Cellar/julia/0.5.1/share/julia/test/libgit2.jl, in expression starting on line 130
ERROR: LoadError: Some tests exited with errors.
 in (::##19#27)() at /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl:72
 in cd(::##19#27, ::String) at ./file.jl:59
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
while loading /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl, in expression starting on line 26
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.1
Commit 6445c82d0* (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

 in runtests(::Array{String,1}, ::Int64) at ./interactiveutil.jl:571
 in runtests() at ./interactiveutil.jl:560
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
 in _start() at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
```

Any ideas of what happened ?
Regards,
Alex

**Comment by yuyichao** [comment]
Is there no other output?

**Comment by ajgiuliani** [comment]
There is no other output after issuing Base.runtests().

**Comment by nalimilan** [comment]
Well, there was necessarily more output showing the list of tests which were run. Isn't there any error message buried there? Could you post the full output in a gist?

**Comment by ajgiuliani** [comment]
Indeed, several tests were passed.  You'll find the full output below.

/usr/local/Cellar/julia/0.5.1/bin/julia -e "Base.runtests()"
	From worker 4:	     * linalg/dense          in  74.95 seconds, maxrss  314.15 MB
	From worker 4:	     * linalg/schur          in   9.01 seconds, maxrss  320.60 MB
	From worker 4:	     * linalg/special        in   3.59 seconds, maxrss  324.07 MB
	From worker 3:	     * linalg/qr             in 116.35 seconds, maxrss  369.35 MB
	From worker 4:	     * linalg/eigen          in  53.62 seconds, maxrss  368.41 MB
	From worker 5:	     * linalg/matmul         in 151.70 seconds, maxrss  330.60 MB
	From worker 4:	     * linalg/svd            in  11.22 seconds, maxrss  371.31 MB
	From worker 3:	     * linalg/bunchkaufman   in  44.15 seconds, maxrss  391.85 MB
	From worker 4:	     * linalg/tridiag        in  26.43 seconds, maxrss  398.61 MB
	From worker 3:	     * linalg/bidiag         in  35.20 seconds, maxrss  419.66 MB
	From worker 5:	     * linalg/lapack         in  47.11 seconds, maxrss  355.16 MB
	From worker 5:	     * linalg/givens         in   5.61 seconds, maxrss  359.09 MB
	From worker 3:	     * linalg/pinv           in  11.07 seconds, maxrss  490.37 MB
	From worker 4:	     * linalg/diagonal       in  53.76 seconds, maxrss  447.88 MB
	From worker 4:	     * linalg/symmetric      in  11.44 seconds, maxrss  452.54 MB
	From worker 3:	     * linalg/lu             in  37.67 seconds, maxrss  490.37 MB
	From worker 4:	     * linalg/generic        in   7.64 seconds, maxrss  452.54 MB
	From worker 5:	     * linalg/cholesky       in  68.75 seconds, maxrss  410.15 MB
	From worker 5:	     * linalg/hessenberg     in   0.80 seconds, maxrss  410.31 MB
	From worker 3:	     * linalg/uniformscaling in  33.37 seconds, maxrss  490.37 MB
	From worker 5:	     * linalg/arnoldi        in  30.92 seconds, maxrss  447.38 MB
WARNING: Method definition f(Tuple{Vararg{Int64, #N<:Any}}, AbstractArray{#T<:Any, #N<:Any}) in module Main at /usr/local/Cellar/julia/0.5.1/share/julia/test/core.jl:723 overwritten at /usr/local/Cellar/julia/0.5.1/share/julia/test/core.jl:729.
	From worker 4:	     * linalg/lq             in  62.42 seconds, maxrss  531.99 MB
	From worker 4:	     * inference             in   0.85 seconds, maxrss  532.37 MB
WARNING: Method definition f() in module JLCall14301 at /usr/local/Cellar/julia/0.5.1/share/julia/test/core.jl:3546 overwritten at /usr/local/Cellar/julia/0.5.1/share/julia/test/core.jl:3556.
	From worker 4:	     * keywordargs           in   1.46 seconds, maxrss  533.27 MB
	From worker 2:	     * linalg/triangular     in 328.20 seconds, maxrss  698.84 MB
	From worker 2:	     * printf                in  14.83 seconds, maxrss  720.32 MB
	From worker 2:	     * char                  in   0.77 seconds, maxrss  723.71 MB
WARNING: static parameter T does not occur in signature for bad_tvars at /usr/local/Cellar/julia/0.5.1/share/julia/test/core.jl:4621.
The method will not be callable.
	From worker 5:	     * core                  in  39.16 seconds, maxrss 1543.77 MB
	From worker 5:	     * triplequote           in   0.02 seconds, maxrss 1543.85 MB
	From worker 5:	     * unicode               in   4.34 seconds, maxrss 1553.98 MB
	From worker 2:	     * string                in  14.16 seconds, maxrss  738.65 MB
	From worker 2:	     * dict                  in  10.80 seconds, maxrss  756.93 MB
	From worker 2:	     * hashing               in   5.42 seconds, maxrss  767.06 MB
	From worker 2:	     * iobuffer              in   0.76 seconds, maxrss  767.99 MB
	From worker 2:	     * staged                in   0.77 seconds, maxrss  769.13 MB
	From worker 5:	     * dates                 in  33.42 seconds, maxrss 1589.54 MB
	From worker 4:	     * numbers               in  79.41 seconds, maxrss  636.86 MB
	From worker 4:	     * tuple                 in   1.57 seconds, maxrss  639.36 MB
	From worker 4:	     * reduce                in   3.80 seconds, maxrss  663.13 MB
	From worker 4:	     * reducedim             in  14.55 seconds, maxrss  678.04 MB
	From worker 5:	     * arrayops              in  43.45 seconds, maxrss 1697.22 MB
	From worker 4:	     * random                in  10.89 seconds, maxrss  701.73 MB
	From worker 4:	     * intfuncs              in   0.68 seconds, maxrss  704.92 MB
	From worker 4:	     * simdloop              in   1.22 seconds, maxrss  705.93 MB
	From worker 4:	     * vecelement            in   1.82 seconds, maxrss  710.71 MB
	From worker 2:	     * offsetarray           in  58.58 seconds, maxrss  879.05 MB
	From worker 4:	     * blas                  in  26.96 seconds, maxrss  749.88 MB
 	From worker 5:	     * abstractarray         in  68.28 seconds, maxrss 1714.70 MB
	From worker 5:	     * copy                  in   1.21 seconds, maxrss 1716.45 MB
	From worker 5:	     * math                  in  39.29 seconds, maxrss 1720.45 MB
	From worker 5:	     * fastmath              in   2.99 seconds, maxrss 1720.45 MB
	From worker 5:	     * functional            in  64.88 seconds, maxrss 1720.45 MB
	From worker 5:	     * operators             in   0.84 seconds, maxrss 1720.45 MB
	From worker 5:	     * path                  in   6.08 seconds, maxrss 1720.45 MB
	From worker 5:	     * ccall                 in   7.64 seconds, maxrss 1720.45 MB
	From worker 4:	     * bitarray              in 161.78 seconds, maxrss  776.69 MB
	From worker 4:	     * loading               in   0.09 seconds, maxrss  776.69 MB
	From worker 5:	     * parse                 in   3.22 seconds, maxrss 1720.45 MB
	From worker 5:	     * bigfloat              in   0.25 seconds, maxrss 1720.45 MB
	From worker 4:	     * bigint                in   1.95 seconds, maxrss  776.69 MB
	From worker 4:	     * statistics            in   9.95 seconds, maxrss  776.69 MB
	From worker 3:	     * subarray              in 354.40 seconds, maxrss  855.28 MB
	From worker 4:	     * spawn                       [stdio passthrough ok]
	From worker 3:	     * backtrace             in   0.77 seconds, maxrss  855.28 MB
	From worker 3:	     * priorityqueue         in   1.58 seconds, maxrss  855.28 MB
	From worker 4:	 in  22.54 seconds, maxrss  776.69 MB
	From worker 5:	     * sorting               in  45.07 seconds, maxrss 1720.45 MB
	From worker 3:	     * file                  in  41.05 seconds, maxrss  855.28 MB
	From worker 3:	     * version               in   1.35 seconds, maxrss  855.28 MB
	From worker 4:	     * read                  in  23.56 seconds, maxrss  776.69 MB
	From worker 4:	     * pollfd                in   3.84 seconds, maxrss  776.69 MB
	From worker 3:	     * resolve               in   4.54 seconds, maxrss  855.28 MB
	From worker 4:	     * mpfr                  in   2.45 seconds, maxrss  776.69 MB
	From worker 5:	     * mmap                  in  20.21 seconds, maxrss 1720.45 MB
	From worker 5:	     * socket                in   3.48 seconds, maxrss 1720.45 MB
	From worker 5:	     * floatapprox           in   0.34 seconds, maxrss 1720.45 MB
	From worker 4:	     * complex               in   8.16 seconds, maxrss  776.69 MB
	From worker 5:	     * datafmt               in   9.23 seconds, maxrss 1720.45 MB
	From worker 5:	     * regex                 in   0.60 seconds, maxrss 1720.45 MB
	From worker 4:	     * reflection            in   7.35 seconds, maxrss  776.69 MB
	From worker 4:	     * combinatorics         in   0.38 seconds, maxrss  776.69 MB
	From worker 4:	     * sysinfo               in   0.76 seconds, maxrss  776.69 MB
	From worker 5:	     * float16               in   1.33 seconds, maxrss 1720.45 MB
	From worker 4:	     * env                   in   0.59 seconds, maxrss  776.69 MB
	From worker 5:	     * rounding              in   0.92 seconds, maxrss 1720.45 MB
	From worker 5:	     * mod2pi                in   0.29 seconds, maxrss 1720.45 MB
	From worker 5:	     * euler                 in   1.05 seconds, maxrss 1720.45 MB
	From worker 3:	     * broadcast             in  34.17 seconds, maxrss  855.28 MB
	From worker 3:	     * lineedit              in   3.82 seconds, maxrss  855.28 MB
	From worker 3:	     * replcompletions       in   4.55 seconds, maxrss  855.28 MB
	From worker 2:	     * sparse                in 290.04 seconds, maxrss  947.55 MB
	From worker 5:	     * show                  in  26.61 seconds, maxrss 1720.45 MB
	From worker 2:	     * replutil              in   6.22 seconds, maxrss  947.55 MB
	From worker 3:	     * repl                  in   6.87 seconds, maxrss  855.28 MB
	From worker 3:	     * goto                  in   0.05 seconds, maxrss  855.28 MB
	From worker 3:	     * llvmcall              in   0.18 seconds, maxrss  855.28 MB
	From worker 5:	     * sets                  in   2.92 seconds, maxrss 1720.45 MB
	From worker 3:	     * grisu                 in   2.62 seconds, maxrss  855.28 MB
	From worker 3:	     * meta                  in   0.44 seconds, maxrss  855.28 MB
	From worker 3:	     * stacktraces           in   1.60 seconds, maxrss  855.28 MB
	From worker 2:	     * test                  in   8.98 seconds, maxrss  947.55 MB
	From worker 3:	     * profile               in   4.09 seconds, maxrss  855.28 MB
	From worker 4:	     * ranges                in  39.95 seconds, maxrss  776.69 MB
	From worker 3:	     * docs                  in   4.09 seconds, maxrss  855.28 MB
	From worker 3:	     * base64                in   0.32 seconds, maxrss  855.28 MB
	From worker 5:	     * nullable              in  13.16 seconds, maxrss 1720.45 MB
	From worker 4:	     * markdown              in   5.13 seconds, maxrss  776.69 MB
Warning: threaded loop executed in order
	From worker 4:	     * threads               in   4.22 seconds, maxrss  776.69 MB
	From worker 3:	     * serialize             in   6.80 seconds, maxrss  855.28 MB
	From worker 4:	     * enums                 in   2.04 seconds, maxrss  776.69 MB
	From worker 4:	     * i18n                  in   0.02 seconds, maxrss  776.69 MB
	From worker 4:	     * workspace             in   1.27 seconds, maxrss  776.69 MB
	From worker 2:	     * libgit2              Test Failed
	From worker 2:	  Expression: isfile(joinpath(repo_path,LibGit2.Consts.HEAD_FILE))
	From worker 4:	     * libdl                 in   2.36 seconds, maxrss  776.69 MB
	From worker 4:	     * int                   in   3.43 seconds, maxrss  776.69 MB
	From worker 6:	     * intset                in   1.20 seconds, maxrss  196.09 MB
	From worker 6:	     * floatfuncs            in   4.34 seconds, maxrss  207.57 MB
	From worker 5:	     * misc                  in  21.63 seconds, maxrss 1720.45 MB
	From worker 5:	     * inline                in   0.27 seconds, maxrss 1720.45 MB
	From worker 5:	     * boundscheck           in   4.94 seconds, maxrss 1720.45 MB
	From worker 5:	     * error                 in   0.72 seconds, maxrss 1720.45 MB
WARNING: Method definition ambig(Any, Integer) in module Main at /usr/local/Cellar/julia/0.5.1/share/julia/test/ambiguous.jl:7 overwritten at /usr/local/Cellar/julia/0.5.1/share/julia/test/ambiguous.jl:79.
	From worker 4:	     * checked               in  14.31 seconds, maxrss  776.69 MB
	From worker 4:	     * cartesian             in   0.01 seconds, maxrss  776.69 MB
	From worker 5:	     * ambiguous            Skipping Base.<|
	From worker 5:	Skipping Base.>:
	From worker 5:	Skipping Base.active_repl
	From worker 5:	Skipping Base.active_repl_backend
	From worker 5:	 in   1.64 seconds, maxrss 1720.45 MB
	From worker 5:	     * dsp                   in  15.06 seconds, maxrss 1720.45 MB
	From worker 4:	     * fft                   in  34.24 seconds, maxrss  776.69 MB
	From worker 5:	     * examples              in  22.24 seconds, maxrss 1720.45 MB
	From worker 6:	     * parallel              in  88.47 seconds, maxrss  208.04 MB
	From worker 3:	     * cmdlineargs           in 136.91 seconds, maxrss  855.28 MB
Exception running test libgit2 :
On worker 2:
LoadError: There was an error during testing
 in record at ./test.jl:397
 in do_test at ./test.jl:281
 in #198 at /usr/local/Cellar/julia/0.5.1/share/julia/test/libgit2.jl:221
 in mktempdir at ./file.jl:286
 in mktempdir at ./file.jl:284
 in include_string at ./loading.jl:441
 in jlcall_include_string_33141 at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20276 at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in macro expansion at ./util.jl:230 [inlined]
 in runtests at /usr/local/Cellar/julia/0.5.1/share/julia/test/testdefs.jl:7
 in #24 at /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl:44
 in #645 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #644 at ./event.jl:68
while loading /usr/local/Cellar/julia/0.5.1/share/julia/test/libgit2.jl, in expression starting on line 130
ERROR: LoadError: Some tests exited with errors.
 in (::##19#27)() at /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl:72
 in cd(::##19#27, ::String) at ./file.jl:59
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
while loading /usr/local/Cellar/julia/0.5.1/share/julia/test/runtests.jl, in expression starting on line 26
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.1
Commit 6445c82d0* (2017-03-05 13:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

 in runtests(::Array{String,1}, ::Int64) at ./interactiveutil.jl:571
 in runtests() at ./interactiveutil.jl:560
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
 in _start() at /usr/local/Cellar/julia/0.5.1/lib/julia/sys.dylib:?

**Comment by tkelman** [comment]
the failure is `isfile(joinpath(repo_path,LibGit2.Consts.HEAD_FILE))`

this is probably because the homebrew libgit2 version doesn't match what that version of julia supports. build 0.5.2 from source without using homebrew, or use the mac binaries.

**Comment by ajgiuliani** [comment]
Homebrew Julia 0.5.0 works fine, but I could get any later version to work.
Thank you for your help, I'll switched to the binaries.
