### ISSUE TITLE
Dispatch problems when reshaping a SubArray

### ISSUE THREAD

**Issue by mtfishman** [JuliaLang/julia#22411]
The following performance issue is present on master (as well as v0.6.0-rc3 and v0.5.2):

```
using BenchmarkTools
f1(A, B) = A*B
f2(A, B) = reshape(view(A, :, :), size(A))*B

N = 100
A = rand(N, N) 
B = rand(N, N)
@btime f1($A, $B)
@btime f2($A, $B)
```

gives

```
73.563 μs (2 allocations: 78.20 KiB)
1.510 ms (10 allocations: 78.61 KiB)
```

This occurs because a `ReshapedArray{T,N,P<:SubArray,MI}` is currently not considered a `StridedArray`:
```
julia> typeof(reshape(view(A, :, :), size(A))) <: StridedArray
false
```
so generic matrix multiplication is called instead of BLAS.

Extending the definition of `Base.StridedReshapedArray` from                     
```
StridedReshapedArray{T,N,A<:DenseArray} = ReshapedArray{T,N,A}
```
to
```
StridedReshapedArray{T,N,A<:Union{DenseArray,SubArray}} = ReshapedArray{T,N,A}
```
appears to fix this (I can create a pull request if that seems reasonable to the experts, I'm not sure if that new definition could have some unintended consequences).

For posterity:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.635
Commit e2ef50f7c8 (2017-06-17 21:49 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
Environment:
  JULIAPATH = /Users/mfishman/workdir/julia
```

**Comment by timholy** [comment]
Unfortunately, it's not quite so simple:
```julia
julia> A = reshape(1:15, 5, 3)
5×3 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

julia> (diff(A, 1), diff(A, 2))    # strided
([1 1 1; 1 1 1; 1 1 1; 1 1 1], [5 5; 5 5; … ; 5 5; 5 5])

julia> B = view(A, 1:4, :)
4×3 SubArray{Int64,2,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}},Tuple{UnitRange{Int64},Base.Slice{Base.OneTo{Int64}}},false}:
 1  6  11
 2  7  12
 3  8  13
 4  9  14

julia> (diff(B, 1), diff(B, 2))   # strided
([1 1 1; 1 1 1; 1 1 1], [5 5; 5 5; 5 5; 5 5])

julia> C = reshape(B, 3, 4)
3×4 Base.ReshapedArray{Int64,2,SubArray{Int64,2,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}},Tuple{UnitRange{Int64},Base.Slice{Base.OneTo{Int64}}},false},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}:
 1  4   8  12
 2  6   9  13
 3  7  11  14

julia> (diff(C, 1), diff(C, 2))   # not strided
([1 2 1 1; 1 1 2 1], [3 4 4; 4 3 4; 4 4 3])
```

However, certain types of SubArrays will be strided: for example, ones that use only Colons, or Colons followed by a one or more Int slices with no trailing Colons, or Colons followed by a single UnitRange, and several others. As you might imagine, this is a bit complicated, but the good news is that we've [already faced this](https://github.com/JuliaLang/julia/blob/3a17af0fe0caac34f8ef1594ce98ce5668ec54b1/base/subarray.jl#L40-L53) when deciding whether a SubArray can use linear indexing. So, it seems safe to call it strided if it's a `ReshapedArray{<:SubArray{<:StridedArray}}` and the linear-indexing parameter (the final parameter of the `SubArray` type) is `true`.

**Comment by mtfishman** [comment]
I figured it would be a bit more subtle. Would a safe definition be `StridedReshapedArray{T,N,A<:Union{DenseArray,FastContiguousSubArray}} = ReshapedArray{T,N,A}`?

As an example of my use case, this shows up when calling `eigs` on a custom linear map:
```
struct LinearMap{T} <: AbstractMatrix{T}
    A::Matrix{T}
end
Base.size(L::LinearMap) = (size(L.A,1)^2,size(L.A,2)^2)
Base.issymmetric(::LinearMap) = false
Base.A_mul_B!(Ṽ::AbstractVector, L::LinearMap, V::AbstractVector) = Ac_mul_B!(reshape(Ṽ, size(L.A)), L.A, reshape(V, size(L.A))*L.A)

L = LinearMap(rand(50,50))
d,v = eigs(L)
```
Internally, `eigs` works with `SubArray`'s, so a `ReshapedArray{<:SubArray}` is created in `A_mul_B!`. The definition above fixes the performance problems I was seeing.

**Comment by timholy** [comment]
That seems correct to me.
