### ISSUE TITLE
"Unexpected error in runtime" on AppVeyor

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#22431]
I've been seeing the following in packages' AppVeyor builds with Julia nightly:
```
Internal error: encountered unexpected error in runtime:
rec_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\stackwalk.c:86
record_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:245
jl_throw at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:564
jl_type_error_rt at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\rtutils.c:118
jl_type_error at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\rtutils.c:124
jl_f_issubtype at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\builtins.c:284
abstract_call at .\inference.jl:2198
unknown function (ip: 0000000061B260AD)
```
The backtrace extends for another 1100 lines or so, then ends with
```
TypeError(func=:issubtype, context="", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:issubtype, context="", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:issubtype, context="", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
Internal error: encountered unexpected error in runtime:
TypeError(func=:Tuple, context="parameter", expected=Type{T} where T, got=<?#0000000004AAEA80::<circular reference @-1>>)
```
This example is taken from a DataFrames PR. The full log can be found here, beginning on the highlighted line: https://gist.github.com/ararslan/ffdb837ebeb1747c98b228bc5bd5360c#file-log-txt-L428

**Comment by ararslan** [comment]
This has not been fixed; I'm still getting it for example with FFTW on Julia nightly. Full AppVeyor log from FFTW build: https://gist.github.com/ararslan/5085b87ced86ce22c9ad4a9f64a5745c

**Comment by ararslan** [comment]
Looks like this is only happening on 32-bit now, whereas before it was happening on 32- and 64-bit IIRC.

**Comment by tkelman** [comment]
if it's win32 only, it's probably a gcc runtime version mismatch. winrpm libs are built with gcc 7, julia windows binaries are currently built with gcc 5

**Comment by ararslan** [comment]
I'm surprised, I would have assumed that we handled GCC runtime version mismatches more gracefully than this, but maybe that isn't possible. I don't know much about that stuff. Are there any plans to upgrade the toolchain for the Window binaries to GCC 7? Seems like it would be ideal to do that sooner rather than later to ensure that things that use WinRPM still work (assuming that's the issue here).

**Comment by tkelman** [comment]
We don't control the toolchain that gets used on the windows buildbots, so we can't really upgrade until the cygwin package maintainer chooses to.

**Comment by ararslan** [comment]
Is it only the 32-bit binaries that are being built with GCC 5? I'm unclear on why it now works on 64-but but not on 32.

**Comment by tkelman** [comment]
there are newly introduced functions in libgcc that aren't relevant on 64 bit

**Comment by mortenpi** [comment]
Not sure if related, but I'm also seeing an error with the current (96a30059aa) 32-bit Windows nightly in [Documenter's Appveyor](https://ci.appveyor.com/project/JuliaDocs/documenter-jl/build/mp/appveyor-debug-7#L4619). It should be possible to reproduce it locally with the [`mp/appveyor-debug`](https://github.com/JuliaDocs/Documenter.jl/tree/mp/appveyor-debug) branch by running `Pkg.test("Documenter")`.

I managed to track it down to [src/DocChecks.jl#L200-L204](https://github.com/JuliaDocs/Documenter.jl/blob/mp/appveyor-debug/src/DocChecks.jl#L200-L204), when that gets called with a harmless `@assert isodd(3) "..."` expression. But adding `println`/`write` calls into those blocks, or in fact, simply running `julia test/runtests.jl` makes the crash go away, so I left it there.

**Comment by KristofferC** [comment]
Re-open if this still happens.
