### ISSUE TITLE
New AddrSpaceCast error when building RPM nightlies

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#22439]
I've just seen this new error when building the RPM nightlies, using system LLVM 3.9.1. Do we require new LLVM patches?
```
/builddir/build/BUILD/julia/base/precompile.jl
AddrSpaceCast must be between different address spaces
AddrSpaceCast must be between different address spaces
  %.sroa_cast = addrspacecast i8* %66 to i8*, !dbg !76331
  %.sroa_cast = addrspacecast i8* %66 to i8*, !dbg !76331
LLVM ERROR: Broken function found, compilation aborted!
LLVM ERROR: Broken function found, compilation aborted!
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
Makefile:233: recipe for target '/builddir/build/BUILD/julia/build/usr/lib64/julia/sys.o' failed
```
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-26-x86_64/00567889-julia/build.log.gz

**Comment by yuyichao** [comment]
I assume this is master? It shouldn't be an issue on 0.6. There are indeed two new patches added compare to 0.6 (check `deps/llvm.mk` and check the last two for 3.9.x) For a complete list of patches for 4.0 that I'm currently using, see https://github.com/archlinuxcn/repo/blob/4b27a509d0831880afce76c8eba02a5e1cf232af/llvm-julia/PKGBUILD#L116-L132

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/22022

**Comment by nalimilan** [comment]
Thanks. (I guess I should have searched better, but that PR has been merged one month ago, when builds were still fine.)
