### ISSUE TITLE
reload("PackageName") does not work correctly

### ISSUE THREAD

**Issue by shivin9** [JuliaLang/julia#22438]
I work using the REPL + SublimeText setup and while working on the code, I have to test it on the go.
But every time I make a change in the code, to get the changes reflected I have to restart Julia and setup everything again. 
Ideally the `reload("PackageName")` command should update all the changes but it doesn't. It just precompiles the module again without updating the definitions on the REPL.
 
Can it fixed? 

[EDIT]
``` julia
julia> versioninfo()
Julia Version 0.6.0-rc3.0
Commit ad290e9 (2017-06-07 11:53 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by DrKrar** [comment]
please add the information of versioninfo()

**Comment by quinnj** [comment]
close since `reload` is no longer?
