### ISSUE TITLE
Inconsistent broadcasting of .! on Nullable

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#22444]
On RC3. This is fine:
```julia
> .!(Nullable{Bool}())
Nullable{Bool}()

> Nullable() .& Nullable()
Nullable{Union{}}()
```

but

```julia
> .!(Nullable())
Nullable{Nullable{Union{}}}()   # UPDATE: because of NullableArrays
```

**EDIT**: my bad; this turns out to be another instance of type piracy in NullableArrays. However, even on a fresh 0.6 session, it yields

```julia
julia> .!(Nullable())
Nullable{Tuple{}}()
```

which is a bit inconsistent. Perhaps it does not matter though?

**Comment by martinholters** [comment]
```julia
julia> Base.return_types(!, Tuple{Union{}})
1-element Array{Any,1}:
 Tuple{}

julia> methods(!, Tuple{Union{}})
# 1 method for generic function "!":
!(::Base.##768#769) in Base at deprecated.jl:843

julia> methods(!)
# 5 methods for generic function "!":
!(::Base.##768#769) in Base at deprecated.jl:843
!(x::Bool) in Base at bool.jl:36
!(f::Function) in Base at operators.jl:904
!(B::BitArray) in Base at deprecated.jl:56
!(A::AbstractArray{Bool,N} where N) in Base at deprecated.jl:56
```
I'd expect `!(::Union{})` to be ambiguous. Why is the first method more specific than the others? I suppose no reasonable specifity is defined for `::Union{}` arguments (such calls can never happen, after all), but probably the method list should contain either all methods (with the correct number of arguments) or none. That would also allow `return_types` to give a less arbitrary result here.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaArchive/Nullables.jl/issues/7
