### ISSUE TITLE
Shell is broken in the REPL

### ISSUE THREAD

**Issue by ZacCranko** [JuliaLang/julia#22464]
The shell is broken in the Julia REPL here. 

```
784f43a0c033:~ zcrank$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

shell> ls
ERROR: could not spawn `/bin/false -i -c '(ls) && true'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at ./process.jl:360
 [2] #373 at ./process.jl:512 [inlined]
 [3] setup_stdio(::Base.##373#374{Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:499
 [4] #spawn#372(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at ./process.jl:511
 [5] run(::Cmd) at ./process.jl:650
 [6] repl_cmd(::Cmd, ::Base.Terminals.TTYTerminal) at ./client.jl:111
```

The problem seems to be because Julia is looking for `true` and `false` at the location `/bin`, when on this machine they're stored at
```
784f43a0c033:~ zcrank$ which false
/usr/bin/false
784f43a0c033:~ zcrank$ which true
/usr/bin/true
```

I'm running macOS 10.12.1. This is an Amazon-imaged machine, so there might have been some messing with the paths of things.

**Comment by DrKrar** [comment]
I have a same issue on windows 10.

**Comment by tkelman** [comment]
There is no ls on the path on windows generally, so that's a different and expected issue.

**Comment by otaithleigh** [comment]
@tkelman There is if you're using PowerShell. But using CMD or PS, I have the same issue.
```
C:\Users\peter>julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

shell> dir
ERROR: could not spawn `dir`: no such file or directory (ENOENT)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at .\process.jl:360
 [2] #375 at .\process.jl:512 [inlined]
 [3] setup_stdio(::Base.##375#376{Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:499
 [4] #spawn#374(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:511
 [5] run(::Cmd) at .\process.jl:650
 [6] repl_cmd(::Cmd, ::Base.Terminals.TTYTerminal) at .\client.jl:111
```

**Comment by vtjnash** [comment]
@otaithleigh That is expected: windows doesn't provide a `dir` program

**Comment by otaithleigh** [comment]
@vtjnash It does; it's the CMD version of `ls`.
https://en.wikipedia.org/wiki/Dir_(command)

**Comment by yuyichao** [comment]
It's an internal command, not a program.

**Comment by yuyichao** [comment]
This isn't really a julia issue. There's not direct reference of `/bin/false` it comes from your shell setting. People expect the shell mode to be as close as possible to their shell so I think it's fair to give a broken shell mode if you have a broken shell. Setting `SHELL` or changing the shell setting should fix this.

**Comment by wr125** [comment]
Same here, great advice; "People expect the shell mode to be as close as possible to their shell so I think it's fair to give a broken shell mode if you have a broken shell. Setting JULIA_SHELL or SHELL to a correct value should fix this." Which folder reference do we change exactly on windows?. Many thanks in advance.

**Comment by tkelman** [comment]
@wrt25 that looks like a separate issue that should be opened on the Genie.jl issue tracker, it has likely not been tested on Windows.

**Comment by yuyichao** [comment]
Please do not report unrelated issues here....

FWIW, there are 3 different windows issues reported here, none of which has anything to do with the original issue. In fact, due to the broken state of cmd on windows we don't even use a shell wrapper and the issue here currently cannot happen on windows............

**Comment by wr125** [comment]
I've figured the issue I have here is not with "PowerShell" but with configuring the installation of Genie within the Juno/Julia environment. Moving this concern over https://github.com/essenciary/Genie.jl/issues/24
