### ISSUE TITLE
Creating the same matrix in Julia as in Matlab takes longer time

### ISSUE THREAD

**Issue by nako95** [JuliaLang/julia#22476]
I have a matrix g size(g)=(1,9,512), typeof(g)=Array{Complex{Float64},3}.
P is a vector type(P)=Array{Any,1} with 736 elements.

In Matlab I use gP=g(: , : , P); to create gP.       size(gP)=(1,9,length(P)).

When I do the same in Julia (gP=g[:,:,P]) and time it with @time in Julia and ( tCPU=cputime; "code" cputime-tCPU ) in Matlab I get that it's slower in Julia. Since I'm doing this within a loop in both Julia and Matlab and doing practically the same line twice I get a second slower in Julia than Matlab in total and I'd therefore really like to improve this line if it's possible. 

I tried using view() which was faster but then the next coming code went extremely slow and I've tried both cat and append! but nothing seems to give me the correct gP. I did solve it with a loop that was a little bit faster but still not as fast as Matlab. Here is my alternative as a loop: 

```julia
j=0
for i in P
      j+=1
      gP[: , : ,j]=g[: , : ,i] 
end
```

I have read performance tips in Julialang  but I still can't figure out what's wrong.

Is there anyone who has any idea what's slow? I also don't understand why my loop is faster than the original line. Anyone who has any idea how to improve the line so it's as fast as Matlab?

**Comment by nalimilan** [comment]
Can you post reproducible examples with the actual timings you get in both MATLAB and Julia?

**Comment by martinholters** [comment]
FWIW, I'm seeing relatively similar times for Matlab and Julia using `g[:,:,P]`, while the loop version is significantly (more than factor 10) slower. Another case of benchmarking in global scope?

**Comment by nako95** [comment]
@martinholters That seems more logical yes! I did try to reproduce the example with less complex values and I reached the same result. Maybe it's something happening above that makes that line slow, not the line itself. I'm new to benchmarking and using @time so maybe it could be somethings regarding that as well, still I notice Julia taking longer time than Matlab.

I've tried to create a good example that does the same thing but I couldn't come up with anything. So I'm posting my example here (Julia code) and maybe you can still see if there's something strange even if you don't have the rest of the code. I time my function like this:

@time ip( edgesTotal,trianglesTotal,
            trianglePlus,triangleMinus,center,center2) 

And the function is: 

function ip( edgesTotal,trianglesTotal,
                            trianglePlus,triangleMinus,center,center2)   

     gP=complex(zeros(1,9,edgesTotal))
     gM=complex(zeros(1,9,edgesTotal))
 
     for p=1:trianglesTotal
          plus=find(trianglePlus[1:736]-p.==0)
          minus=find(triangleMinus[1:736]-p.==0)
          D=center2.-center[:,p] 
          R=sqrt.(sum(D.*D,1))                             # [1 9 trianglesTotal]
          g=exp(-K.*R)./R                               #  [1 9 trianglesTotal]   
          gP=g[:,:,trianglePlus]
      end 
end


Which gives result: (notice memory allocation...)
0.943518 seconds (7.22 M allocations: 559.592 MB, 15.35% gc time)

When I comment: #gP=g[:,:,trianglePlus] I get the following result instead: 
0.375961 seconds (53.91 k allocations: 294.959 MB, 6.79% gc time)

Corresponding times in Matlab:
Entire code: 0.5148
Excluding gP-line: 0.3900

The times differs a bit each time I run the code (0.1 sec difference) but these are usual values for me and as you can see it's something strange going on in the Julia code.

**Comment by yuyichao** [comment]
Please use discourse.julialang.org for questions like this.
