### ISSUE TITLE
Weird ordering of docs version dropdown

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#22470]
This is a minor issue, but the dropdown box on `docs.julialang.org` has a rather arbitrary ordering.  It'd be nice to get something a little more intuitive.

<img width="286" alt="screen shot 2017-06-21 at 3 51 56 pm" src="https://user-images.githubusercontent.com/130920/27410072-d718df48-5699-11e7-9397-df6ca4e74f11.png">

**Comment by yuyichao** [comment]
Seems that it simply place the current one at the top?

**Comment by staticfloat** [comment]
Even disregarding that one, It's neither alphabetic nor chronological, nor in order of stability.  We should choose some reasonable gradient to sort by, even if the current one always gets put at the top.

**Comment by KristofferC** [comment]
Looks consistent now: 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/1282691/103278007-b1320980-49ca-11eb-96bc-7172d728fbcc.png">
