### ISSUE TITLE
Strange parse() of triple quoted strings in Julia v0.6.0

### ISSUE THREAD

**Issue by LaszloHars** [JuliaLang/julia#22487]
`parse("12")   # 12 {OK}
parse("""12""")   # 12 {OK}

#Embedded quotes
parse("""1"2" """)   # :(1 * "2") {Invalid: cannot multiply numbers and strings. It should be the string literal "1\\"2\\""}

#Extra space inside the above string literal:
parse("""1 "2" """)   # ERROR: ParseError("extra token \\"\\"\\" after end of expression")

#Extra letter inside a string literal:
parse("""1x"2" """)   # :(1 * @x_str("2")) {no @x_str macro exists}
`
These are valid string literals. If they are not supported, could this be documented and meaningful error messages displayed?

**Comment by yuyichao** [comment]
Please quote your code.

Triple quote string allows unquoted `"` in it since there's no reason not to. This is unrelated to `parse`. You can print the string yourself to see what you are parsing.

**Comment by LaszloHars** [comment]
Try them! All these strings print, and displayed in the REPL correctly.

**Comment by yuyichao** [comment]
> All these strings print, and displayed in the REPL correctly.

So? Any string can print and be displayed in the REPL. It doesn't make them valid julia code.

**Comment by LaszloHars** [comment]
My point was that a valid string literal should parse to a string literal, not to some invalid Julia code.

**Comment by yuyichao** [comment]
And if you want to see what you are actually doing in the REPL, no they aren't valid

```julia
julia> 1"2"
ERROR: MethodError: no method matching *(::Int64, ::String)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:424
  *(::Real, ::Complex{Bool}) at complex.jl:257
  *(::Real, ::Complex) at complex.jl:269
  ...

julia> 1 "2"
ERROR: syntax: extra token """ after end of expression

julia> 1x"2"
ERROR: UndefVarError: @x_str not defined
```

**Comment by yuyichao** [comment]
> My point was that a valid string literal should parse to a string literal, not to some invalid Julia code.

It's unclear what you mean. The input you give to `parse` are all string objects. None of the strings contains a string representation of a string literal though and they indeed contains invalid julia code. If you want some function that returns the string you pass in, use `identity`.

**Comment by LaszloHars** [comment]
There are 3 cases. (1) from a string literal invalid code is generated - instead I expect an error message. (2) the string literal cannot be parsed, and the error message is not helpful, (3) the parsed expression contains a reference to a non-existent macro - which is even more confusing.

**Comment by yuyichao** [comment]
> from a string literal invalid code is generated - instead I expect an error message.

Those are valid syntax so there should not be a syntax error.

> the string literal cannot be parsed, and the error message is not helpful

In general the parser is laking context right now. It's a know problem and yes I agree it's not helpful. A better versio in in `JuliaParser.jl` though moving that into base can be hard for bootstrap.

> the parsed expression contains a reference to a non-existent macro

Again, this is valid code. The macro is not pre-defined but it's still valid code and it can be defined.
