### ISSUE TITLE
Tags in git repository

### ISSUE THREAD

**Issue by paulmenzel** [JuliaLang/julia#22488]
Although being on the master branch, looking what version that might relate to shows 0.2.0, which is quite confusing.

```
$ git log --oneline -1
7b7939c Merge pull request #22483 from JuliaLang/ksh/gittests
$ git describe --tags
v0.2.0-22462-g7b7939c
$ git branch -a --contains 903644385b91ed8d95e5e3a5716c089dd1f1b08a
  remotes/origin/release-0.6
```

One solution is, to merge the release branches back into master.

**Comment by yuyichao** [comment]
> looking what version that might relate to shows 0.2.0

That shouldn't be the case. It seems that you are just not fetching them.

```
yuyichao% git describe --tags
v0.6.0-pre.beta-1133-g8915d9b338
```

> One solution is, to merge the release branches back into master.

No. They contains very different changes.

**Comment by paulmenzel** [comment]
No, I fetched all tags before reporting the issue.

```
$ git tag
v0.1
v0.1.1
v0.1.2
v0.2.0
v0.2.0-rc1
v0.2.0-rc2
v0.2.0-rc3
v0.2.0-rc4
v0.2.1
v0.3.0
v0.3.0-rc1
v0.3.0-rc2
v0.3.0-rc3
v0.3.0-rc4
v0.3.1
v0.3.10
v0.3.11
v0.3.12
v0.3.2
v0.3.3
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.4.0
v0.4.0-rc1
v0.4.0-rc2
v0.4.0-rc3
v0.4.0-rc4
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.5.0
v0.5.0-rc0
v0.5.0-rc1
v0.5.0-rc2
v0.5.0-rc3
v0.5.0-rc4
v0.5.1
v0.5.2
v0.6.0
v0.6.0-pre.alpha
v0.6.0-pre.beta
v0.6.0-rc1
v0.6.0-rc2
v0.6.0-rc3
```

**Comment by yuyichao** [comment]
In that case something else about your git is not working properly. Note that the output you get is expected from `git describe` if you didn't specify `--tags` so you could be running the wrong command too.

Do note that it is expected to see the tag on the branching point this way and having that tag should fix this issue. It is important for us to branch before final release therefore we'll not merge release branch back after the branching.
