### ISSUE TITLE
Support parsing in different bases for non-integers

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#22480]
Would be nice if this worked...
```
julia> parse(Float64, "1.1", 2)
ERROR: MethodError: no method matching parse(::Type{Float64}, ::String, ::Int64)
Closest candidates are:
  parse{T<:Integer}(::Type{T<:Integer}, ::AbstractString, ::Integer) at parse.jl:150
  parse{T<:AbstractFloat}(::Type{T<:AbstractFloat}, ::AbstractString) at parse.jl:166
  parse{T<:Integer}(::Type{T<:Integer}, ::Char, ::Integer) at parse.jl:6
  ...

```
Even if it only supported powers of 2.

**Comment by christianbender** [comment]
yep. thats a problem , too.

![julia2](https://user-images.githubusercontent.com/23243382/34907481-62378a20-f87f-11e7-8fc5-a09f6f9fd8c0.png)

**Comment by vtjnash** [comment]
More suitable for a package (e.g. https://github.com/JuliaData/Parsers.jl), and really not a good-first-issue

**Comment by quinnj** [comment]
Yes, this wouldn't be very hard to support in Parsers.jl if someone wanted to take a stab there; it would involve adding an additional field to the `Parsers.Options` struct, parsing the base, and passing it to the `Integer` and `Float` `typeparser` methods. The code in those files are fairly "unrolled", so there are a few places to update depending on the base requested, but it wouldnt' be too hard. I've been meaning to do it for a while, but it's never been requested. It's the only remaining feature difference between `Parsers.parse` and `Base.parse` that I'm aware of (at least for integers)
