### ISSUE TITLE
strange parse error for `+.( ... )`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#22498]
Was just looking at #20540 and noticed this:

```
julia> +.(1,2)
ERROR: syntax: numeric constant "." cannot be implicitly multiplied because it ends with "."
```

At the very least, the error message doesn't make sense.
```[tasklist]
### Tasks
```

**Comment by JeffBezanson** [comment]
Noticed in a different form here: https://github.com/JuliaLang/julia/issues/32860#issuecomment-520187931

```
julia> +.
ERROR: LoadError: ArgumentError: invalid base 10 digit '.' in "."
```
Because `+` can be part of numeric literals, we try to parse the dot as one. For example `+.1` works. We should do what non-numeric-literal unary operators do:
```
julia> !.
ERROR: syntax: invalid identifier name "."
```

**Comment by brenhinkeller** [comment]
Still reproduces in 1.8.3

**Comment by adienes** [comment]
> We should do what non-numeric-literal unary operators do

this is now the observed behavior now with JuliaSyntax merged.
```
julia> +.
ERROR: ParseError:
# Error @ REPL[7]:1:2
+.
#╙ ── invalid identifier
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by vtjnash** [comment]
This could use a test, if you would be willing to write one.
