### ISSUE TITLE
endof(Dict) missing or Collections documentation is off

### ISSUE THREAD

**Issue by garborg** [JuliaLang/julia#22499]
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> endof(Dict{Int,Int}())
ERROR: MethodError: no method matching endof(::Dict{Int64,Int64})
```

[Collections doc](https://docs.julialang.org/en/stable/stdlib/collections/#General-Collections-1) groups `endof` under 'General Collections' and says `Dict` fully implements it

**Comment by nalimilan** [comment]
I guess `endof` should be moved to the "Indexable Collections" section, and `Dict` should be moved to "partially implemented" for that section?

**Comment by bramtayl** [comment]
Hmm, `endof` doesn't make sense for a Dict, does it? In which case you can just say fully implemented where applicable or something.

**Comment by garborg** [comment]
Indexable Collections makes sense to me.
