### ISSUE TITLE
Feature requested: Randomly generate float in a range

### ISSUE THREAD

**Issue by fufjvnvnf** [JuliaLang/julia#22502]
Right now we have the `rand()` function to randomly generate a float between `0` and `1`. I would like to create a matrix of float between `-1` and `1`, conveniently, meaning I would like to do it one line as usual by providing arguments to the normal `rand()` function. I tried feeding `rand()` `-1:1` along with my `dim`, yet it treats my range as a two-element list instead of a float range.

**Comment by fredrikekre** [comment]
```julia
julia> s = 2; A = s*rand(3, 3)-s/2
3×3 Array{Float64,2}:
 0.286097  -0.619115   0.841564
 0.505293   0.237119  -0.656106
 0.823477   0.118682   0.663241
```

**Comment by fufjvnvnf** [comment]
@fredrikekre wow.... genius

**Comment by fufjvnvnf** [comment]
Still could be nice if we were to be provided a range argument in `rand()` tho!

**Comment by kmsquire** [comment]
```julia
Pkg.add("Distributions")
import Distributions: Uniform 
rand(Uniform(-1,1), 3, 3)
```

**Comment by StirlingNewberry** [comment]
We should say whether it is random, or pseudo-random - right now it won't
make a difference, but will soon.

**Comment by nalimilan** [comment]
@fufjvnvnf Note that a float range is *not* the same as an interval, contrary to what happens with integers. So `rand(1.0:5.0)` would have to be equivalent to `Float64.(rand(1:5))`, which probably isn't very useful, and could even be misleading.

**Comment by kirui93** [comment]
@kmsquire can I do the same too for Normal?

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
