### ISSUE TITLE
at-edit does not handle `'\` correctly

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#22505]
The docs says

> Matrix operations involving transpositions operations like A' \ B are converted by the Julia parser into calls to specially named functions like Ac_ldiv_B. 

```julia
julia> B = [1.5 2 -4; 2 -1 -3; -4 7 5]
3×3 Array{Float64,2}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0   7.0   5.0

julia> x = [1; 2; 3]
3-element Array{Int64,1}:
 1
 2
 3

julia> @edit B'\x
```
It opens this [line](https://github.com/JuliaLang/julia/blob/d04015144f1cd3daa2f53473beb22bff417ac692/base/linalg/generic.jl#L804) which is not related to `Ac_ldiv_B` or `At_ldiv_B `.

**Comment by fredrikekre** [comment]
Related: https://github.com/JuliaLang/julia/issues/20620 and https://github.com/JuliaLang/julia/issues/20159

**Comment by fredrikekre** [comment]
and https://github.com/JuliaLang/julia/issues/21014

**Comment by andreasnoack** [comment]
Dup of #17469
