### ISSUE TITLE
I'm trying to do large computations, but at a certain point it just says the number is Inf rather than evaluating.  For example, I type in 2017^2017. and it returns Inf. If they are both integers, then it returns a negative number. Other languages like python and Mathematica can do this in seconds though. How do I get it work?

### ISSUE THREAD

**Issue by jgk99** [JuliaLang/julia#22539]
If you have a question or are unsure if the behavior you're experiencing is a bug,
please search or post to our Discourse site: https://discourse.julialang.org. We use
the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by fredrikekre** [comment]
You can use `big(2017)^2017` see https://docs.julialang.org/en/stable/manual/integers-and-floating-point-numbers/#Overflow-behavior-1
Please use https://discourse.julialang.org for questions like this.
