### ISSUE TITLE
Segfault with julia v0.6

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#22537]
I get a segfault in my code with julia 0.6. It's a bit tricky to get a MWE (and I can't post the code publicly), but the segfault is reliable although non-systematic (I seem to get it about once every three runs). I get

*** Error in `/home/antoine/julia-0.6.0/usr/bin/julia-debug': corrupted double-linked list (not small): 0x0000000003106b00 ***

The backtrace (with julia-debug) is here: https://gist.github.com/antoine-levitt/d8a768c6caf9eaf6196ab9df42abc93e. I saved the coredump so can investigate more if needed. The last function I recognize is a function that does some fancy indexing, but nothing that should be particularly problematic. The only place where I do weird stuff is these functions

```julia
function real_to_complex(A::AbstractArray{T}) where T<:Real
    @assert size(A)[1] == 2
    sizeB = size(A)[2:end]
    return unsafe_wrap(Array, convert(Ptr{Complex{T}}, pointer(A)), sizeB)
end
function complex_to_real(B::AbstractArray{Complex{T}}) where T<:Real
    sizeA = tuple(2,size(B)...)
    return unsafe_wrap(Array, convert(Ptr{T}, pointer(B)), sizeA)
end
```
but these should be OK, I think? I ran with julia --check-bounds=yes, didn't change anything. I tried to run under valgrind, but that takes ages.

**Comment by yuyichao** [comment]
No, these functions are wrong and can segfault since the base array can be freed.

**Comment by antoine-levitt** [comment]
I see, thanks! If anyone is interested, the following is the correct way to do it:

```julia
function real_to_complex(A::Array{T}) where T<:Real
    @assert size(A)[1] == 2
    sizeB = size(A)[2:end]
    return reinterpret(Complex{T}, A, sizeB)
end
function complex_to_real(B::Array{Complex{T}}) where T<:Real
    sizeA = tuple(2,size(B)...)
    return reinterpret(T, B, sizeA)
end
```
