### ISSUE TITLE
REPL: allow attaching a module other than Main

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#22562]
It would be very convenient to be able to eval code in the context of a different module than `Main`. This could be reflected by the prompt output or be a separate REPL mode or something. The implementation is probably largely just a matter of making references to `Main` in the REPL code use a global instead that is set to `Main` initially but can be changed.

**Comment by tshort** [comment]
Here's a quick hack at a REPL mode that does this.

https://github.com/tshort/REPLinModule.jl

An advantage of a REPL mode is that you can easily switch between `Main` and another module.

**Comment by StefanKarpinski** [comment]
Very cool! Serves as an excellent prototype for this feature.

**Comment by KristofferC** [comment]
There is a difference in case between the repo name and the file name of the module which makes it fail on case sensitive systems.

**Comment by tshort** [comment]
Thanks, @KristofferC. Hopefully fixed.

**Comment by ZacLN** [comment]
If this were integrated into base it would be nice to hook the active module up to [this](https://github.com/JuliaLang/julia/blob/master/base/repl/REPLCompletions.jl#L23) so that completions worked as expected

**Comment by tkelman** [comment]
@ZacLN hit `y` for a permalink when you link to lines of code, otherwise master will change around and the link might no longer be relevant - I think you meant https://github.com/JuliaLang/julia/blob/ff706aa0dc3e7b74ffd290a247e8cc91e4fe9197/base/repl/REPLCompletions.jl#L23 ?

**Comment by NightMachinary** [comment]
Any updates? VSCode's Julia extension has this feature, and I like to add to emacs.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/33872 is the latest on it I think.
