### ISSUE TITLE
Printing for BunchKaufman factorizations could be better

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#22571]
Ref https://github.com/JuliaLang/julia/pull/22568#discussion_r124227734

**Comment by andreasnoack** [comment]
See comment in https://github.com/JuliaLang/julia/pull/22345#discussion_r124275489. We don't support extracting the factors of the Bunch Kaufman. They are a bit messy to extract.

**Comment by tkelman** [comment]
we should show the raw data then, including the permutation

**Comment by andreasnoack** [comment]
I've looked before but tried again and voilà http://www.netlib.org/lapack/explore-html/d3/db6/group__double_s_ycomputational_ga03e63781ce348cc17a7065520bc7dc1a.html#ga03e63781ce348cc17a7065520bc7dc1a
