### ISSUE TITLE
<TAB> completion for "~" should hint nothing

### ISSUE THREAD

**Issue by i-apellaniz** [JuliaLang/julia#22599]
Let me show you a simple example, assuming there is a `Documents/` folder in `$HOME`, of this bug
```julia
julia> cd("~/Doc
```
and hitting `<TAB>` one gets
```julia
julia> cd("~/Documents/")
ERROR: chdir ~/Documents/: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at ./libuv.jl:68 [inlined]
 [2] cd(::String) at ./file.jl:50
```
whichever is the current directory.

**Comment by ararslan** [comment]
This is because we don't perform tilde expansion in paths. See #1136

**Comment by i-apellaniz** [comment]
Then <TAB> should give nothing. But that's not what happens

**Comment by ararslan** [comment]
Will reopen as a suggested change

**Comment by TotalVerb** [comment]
Can we just improve this error message by checking if `~` is in the result, and suggesting user possibly call `expanduser` if so?
