### ISSUE TITLE
rand(::UnitRange) slower than older StatsBase implementation

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#22600]
StatsBase includes a custom function `randi(a, b)` equivalent to `rand(a:b)`, and originally based on almost the same code. The StatsBase code is [here](https://github.com/JuliaStats/StatsBase.jl/blob/5e4fbd3c085231f304cb6704eb383aa49f57c6ca/src/rand.jl), the PR which included it in Julia is https://github.com/JuliaLang/julia/pull/5444 (both were written almost on the same day by @lindahua). The Base implementation has been slightly adapted over time, but remains quite similar to the previous one. Yet, now it turns out `rand` is about 70% slower than `StatsBase.randi`:
```julia
julia> using BenchmarkTools, StatsBase

julia> @btime StatsBase.randi(1, 100)
  18.216 ns (0 allocations: 0 bytes)
5

julia> @btime rand($(1:100))
  31.021 ns (0 allocations: 0 bytes)
14
```
(This difference persists in variations I tested, including a higher upper bound and a loop inside a function.)

This is probably worth some investigation.

**Comment by mschauer** [comment]
Constructing the range generator takes more time because it checks whether the range is small or large and chooses the entropy accordingly and ends up having one division more, but then ``rand(1:100, n)`` is faster in base for big n because it uses less entropy and only has to compute the generator once. See #5741

**Comment by nalimilan** [comment]
Nice to hear somebody familiar with that code! Do you think we should use a simpler version when `n` is omitted (or small)?

**Comment by mschauer** [comment]
Part of the difference comes from randi just failing for invalid input and rand giving instructive error messages, so this creates an additional branch.

```
julia> StatsBase.randi(1,0)
ERROR: DivideError: integer division error

julia> StatsBase.randi(typemin(Int64),typemax(Int64))
ERROR: DivideError: integer division error

julia> rand(1:0)
ERROR: ArgumentError: range must be non-empty

julia> rand(typemin(Int64):typemax(Int64))
151896083233090605
```

What would be interesting to check dropping importance sampling all together for small ranges.
The distribution of ``rand(1:3)`` is (1/3, 1/3, 1/3), the distribution of ``mod1(rand(Int), 3)`` is
 ```
[3.333333333333333333152632971252415927665424533188343048095703125000000000000000e-01

3.333333333333333333694734057495168144669150933623313903808593750000000000000000e-01

]
```

**Comment by nalimilan** [comment]
I can't tell what solution is best, I just wanted to report this possible performance issue before removing the code from StatsBase so that the information isn't lost.

**Comment by mschauer** [comment]
Maybe this is a doc-issue, I'll add a remark in the docs.

**Comment by nalimilan** [comment]
I don't think that's only a docs issue, since there are sampling algorithms in StatsBase which need to call `rand` repeatedly on different ranges to get a single random number (see for example [this line](https://github.com/JuliaStats/StatsBase.jl/blob/master/src/sampling.jl#L98), but there are other places in that file), so a worse performance matters.
