### ISSUE TITLE
floatrange() overflows for some inputs on 32-bit

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#22613]
The following behavior on 32-bit is unexpected to me. It doesn't happen on 64-bit:
```
julia> Base.floatrange(-3e9, 1.0, 1, 1.0)
ERROR: InexactError()
Stacktrace:
 [1] trunc at .\float.jl:651
 [2] floatrange(::Float64, ::Float64, ::Int32, ::Float64) at .\twiceprecision.jl:111

# And yet:
julia> Base.floatrange(-3e18, 1.0, 1, 1.0)
-3.0e18:1.0:-3.0e18
```

The `colon` method in the same file as `floatrange` has a `# will round succeed?` comment, but the relevant checks are not present around the offending `floatrange` line.

(FWIW, this triggers a test failure in StatsBase, cf https://github.com/JuliaStats/StatsBase.jl/pull/279.)

Cc: @timholy

**Comment by angusmoore** [comment]
I discovered a similar problem doing this:
```linspace(log(0.2), log(10.0), 10)```

Same error, and only occurs on 32-bit (ARMv7 in my case).

I think it's a relatively easy fix, and I'm happy to attempt to put together a PR.

**Comment by nalimilan** [comment]
@angusmoore Please go ahead, then we can ask @timholy to review it.

**Comment by angusmoore** [comment]
With #22644 merged, I think we can close this?
