### ISSUE TITLE
Build fails for src/codegen.cpp, src/llvm-late-gc-lowering.cpp and src/jitlayers.cpp with llvm-svn

### ISSUE THREAD

**Issue by singam-sanjay** [JuliaLang/julia#22628]
Julia was at de746144cfe76de27b08874b4e37da2f8d10935f and LLVM was at [11496e](https://github.com/llvm-mirror/llvm/commit/11496e7e16e6f3e26fb8df6d9a862301aab9b293) when I encountered these errors.

I have tried to highlight the main error that caused a cascade of other errors, and have attached the full output of each file's build.
```
In file included from julia_src/src/codegen.cpp:101:0:
julia_src/src/jitlayers.h:151:55: error: ‘llvm::orc::RTDyldObjectLinkingLayerBase::ObjSetHandleT’ has not been declared
         void operator()(RTDyldObjectLinkingLayerBase::ObjSetHandleT H, const ObjSetT &Objects,
                                                       ^

```
[codegen.fullerr.txt](https://github.com/JuliaLang/julia/files/1114456/codegen.err.txt)
```
In file included from julia_src/src/jitlayers.cpp:69:0:
julia_src/src/jitlayers.h:151:55: error: ‘llvm::orc::RTDyldObjectLinkingLayerBase::ObjSetHandleT’ has not been declared
         void operator()(RTDyldObjectLinkingLayerBase::ObjSetHandleT H, const ObjSetT &Objects,
```
[jitlayers.fullerr.txt](https://github.com/JuliaLang/julia/files/1114457/jitlayers.err.txt)
```
julia_src/src/llvm-late-gc-lowering.cpp: In member function ‘bool LateLowerGCFrame::CleanupIR(llvm::Function&)’:
julia_src/src/llvm-late-gc-lowering.cpp:1045:21: error: no matching function for call to ‘llvm::AllocaInst::AllocaInst(llvm::Type*&, llvm::Constant*, int, const char [1], llvm::Instruction*&)’
         "", StartOff);      
```
[llvm-late-gc-lowering.fullerr.txt](https://github.com/JuliaLang/julia/files/1114458/llvm-late-gc-lowering.err.txt)

**Comment by StefanKarpinski** [comment]
Not sure what's actionable here... building with a random LLVM version is not generally expected to work.

**Comment by yuyichao** [comment]
It's not really "a random LLVM version" but supporting of svn build are basically done by whoever needs it and we generally don't take issues and only prs (as in no one will be fixing it just because of an open bug report).

**Comment by tkelman** [comment]
5.0 just branched, so we should probably start thinking about patching things up for their `release_50` branch so we can upgrade

**Comment by singam-sanjay** [comment]
Have tried to address these errors in #22971. Please review.
