### ISSUE TITLE
Timeout at high worker usage

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#22636]
I am on a grid with roughly 1000 cores. They are all well connected, so there are no connection issues or something like that.

Now when I try to launch my script with 500 workers ( like `julia -p 500 file.jl` ) it results in basically all workers timing out after a minute. The workercount when this timing out usually starts happening is roughly at `-p 100` I have one or zero time outs at that worker count.

Then I tried adding those workers per hand like this

	let
	  addedCount::Int64 = 0
	  while addedCount < hpc.cpuCount
		toAdd::Int64 = min(40, hpc.cpuCount - addedCount)
		addprocs(toAdd; restrict=false, topology=:master_slave)
		addedCount += toAdd
	  end
	end

hpc.cpuCount being 500 in my case.

Now this still leads to 1/10 of the processes timing out, which I do not understand. Firstly I only add 40 at a time, so less than 100 which mostly worked. Secondly I am even demanding less communicaiton-overload since I want master-slave communication.

How can I add a high number of workers without it resulting in these timeouts?

**Comment by amitmurthy** [comment]
You can try setting env var `JULIA_WORKER_TIMEOUT` to a value greater than 60.0 seconds. However, it should not be taking that long to start workers in a `master_slave` configuration.

What is the elapsed time for adding 50 workers? Try `@elapsed addprocs(50; restrict=false, topology=:master_slave)`.

For example, adding 90 workers on my local machine with master takes around 5.7 seconds.
```
julia> @elapsed addprocs(90; topology=:master_slave)
5.669107573
```


Which version of Julia are you using?

**Comment by Jackels** [comment]
Adding 40 workers a time, with master_slave, takes between 13 and 15 seconds.

This is with julia 0.5.2

**Comment by Jackels** [comment]
Now I tried my original approach ( adding workers in increments ) with 0.6 and it works, but my sys-admin came to me saying I was causing all sorts of out of memory, because I was not adhering to the 6 gig memory limit. This makes sense, since in addprocs I can not specify any kind of memory limit. So this approach is out of the park for me as long as I can not control memory usage. We are using an sge.

Then I tried, again, with `julia -p 250` and this lead again to timeouts, not everywhere, but still timeouts.

So I am where I started again. -p leads to timeouts and addprocs does not give me enough control.

**Comment by amitmurthy** [comment]
Each fresh Julia worker takes around 75MB of private memory on my local OSX machine. 

Assuming the numbers are in the same ballpark on Linux, with a 6GB limit, you should be able to start a max of around 80 workers. Note that this does not take into account memory requirements of the program you are running.

**Comment by amitmurthy** [comment]
I am going to close this for now as it seems to be related to resource / environment issues on the target machine. The largish startup memory requirement of a Julia process is a known issue.
