### ISSUE TITLE
`Base.invokelatest` doesn't accept kwargs.

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#22642]
I took a quick scan through the code in case there was an easy fix, but it looks like `Base.invokelatest(f, args...)` (`base/essentials.jl`) jumps directly to `Core._apply_latest(f, args)` (`src/builtin.c`). Is there a way to add this functionality without editing multiple functions in builtins.c?

**Comment by Keno** [comment]
Use a closure?

**Comment by rofinn** [comment]
Yep, that works. Thanks @Keno!
