### ISSUE TITLE
Different colors for stacktraces

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#22653]
Complex stacktraces can be a bit hard to read (although they are much better in 0.6!). In particular, I often find myself reading the stacktrace line by line to find the first place in my code (as opposed to julia Base code or package code) where the error is.

Would it be possible to annotate the source line by the provenance of the code? Ideally, there would be three colors: 1 internal julia code 2 package code 3 user code. Obviously these categories intersect but in most situations simple heuristics should do the trick: if the file is in julia's dir (./ in backtraces) then 1, if in Pkg.dir() then 2, otherwise 3.

**Comment by ararslan** [comment]
cc @KristofferC

**Comment by KristofferC** [comment]
Closing in favor of https://github.com/JuliaLang/julia/issues/25375 since it has more discussion.
