### ISSUE TITLE
LLVM error when building master on Power VM (OSU)

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#22650]
I'm trying to build a 100% fresh install of latest Julia, but I get the following error
```
    PERL base/version_git.jl.phony
Copying in usr/share/doc/julia/examples
    JULIA usr/lib/julia/inference.ji
LLVM ERROR: Cannot select: 0x1001dd63a60: i64 = addrspacecast[0 -> 10] Constant:i64<0>
  0x1001dd658d0: i64 = Constant<0>
In function: japi1_Typeof_0
Makefile:215: recipe for target '/home/ubuntu/julia/usr/lib/julia/inference.ji' failed
make[1]: *** [/home/ubuntu/julia/usr/lib/julia/inference.ji] Error 1
Makefile:100: recipe for target 'julia-inference' failed
make: *** [julia-inference] Error 2
```
In https://github.com/JuliaLang/julia/pull/22603 I got the same error, but following the suggested method from that thread does not help here. I'm on Power VM @ OSU (Open Source Lab). cc @simonbyrne

**Comment by vchuravy** [comment]
This looks like we might need to strip address spaces on Power as well  x-ref  #22414 and https://github.com/JuliaGPU/CUDAnative.jl/issues/73#issuecomment-310867640
