### ISSUE TITLE
Change Union types sort order

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#22664]
The order of types in a Union should be mostly irrelevant, but with WIP work on inline, isbits Union types, the "default initialization" for Arrays requires the underlying Union selector byte to be zeroed out (otherwise an array element could be tagged as an "out of bounds" type for the Union). There are a few conveniences if the Union types sort order followed a pattern like:

1) Singleton types
2) Sizeof isbits types
3) All reference types....alphabetically?

**Comment by nalimilan** [comment]
For a bit of context, it would be convenient if `Union{T, Null}` and `Union{Null, T}` had identical coding of their type tags, with `0` denoting `Null`. This is the convention used by Pandas, PostgreSQL, SQLite and Arrow/Feather.  See also https://github.com/JuliaLang/julia/issues/18507. So sorting singleton types first would handle this case.

**Comment by quinnj** [comment]
Do we already have code that sorts Union types? Or is that just enforced in the `show` method for Unions? I'm happy to take a crack at this if someone could give a few tips or places to look/start.

**Comment by vtjnash** [comment]
No, show just sorts them alphabetically while printing them

**Comment by JeffBezanson** [comment]
Should probably be done in `jl_type_union` in jltypes.c, which handles normalization (currently, removing types subsumed by others in a union).

**Comment by quinnj** [comment]
Yeah, I'm stepping through that function right now actually. Is it ok if I just do a separate sort call after normalization but before the Union structs are made?

**Comment by JeffBezanson** [comment]
Yes that sounds fine.
