### ISSUE TITLE
A_ldiv_B!(::LU, ::StridedVector) not updating input rhs

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#22683]
See https://github.com/JuliaLang/julia/blob/bf83397c1c7677ea8776ab792b761fcb3d0607ef/base/linalg/lu.jl#L248. When applying the permutations via `getindex`, a new vector is returned so the input vector is not updated with the solution. The fix is to apply the permutation in place.

Update: Should probably mention that this only happens for the generic fallback and not for BLAS element types.

**Comment by haampie** [comment]
The simplest solution seems to wrap the right-hand side in a view, right?

**Comment by andreasnoack** [comment]
Good point. I was thinking we needed a fancy `A_ldiv_B!` that allowed for a `ipiv` argument but our views support this. Would you like to open a PR?

**Comment by haampie** [comment]
I wasn't really thinking. The right-hand side must be permuted of course.

**Comment by andreasnoack** [comment]
But I think you can just to `view(b, F[:p])` or the inverse permutation.
