### ISSUE TITLE
Ternary (?:) operator vs just using if-else-end

### ISSUE THREAD

**Issue by saolof** [JuliaLang/julia#22692]
Since If blocks are expressions, Julia's ternary operator is redundant since it is just a less readable alias for an if block. Furthermore, since Julia uses both : as a separate operator it leads to ambiguous parses in cases like  `whichrange()?1:2:3:4` (which returns 1 or 2:3:2 in Julia 0.6).

Deprecating the ?: syntax in favor of just pointing people to if blocks would make the language more consistent, it would eliminate the possibility of an ambiguous parse, and it would mean that people coming from Python or Matlab would have one less new bit of syntax to learn. Using if as a ternary expression is natural enough that I don't think that having the same syntax as C is of any benefit tbh.

Regarding the same tradeoff in other languages, Rust had both if expressions and ?: in beta, but deprecated ?: before 1.0. When someone put up a post-1.0 pull request in favor of adding (?:) it was overwhelmingly voted against 
( https://github.com/rust-lang/rust/issues/1698
https://github.com/rust-lang/rust/pull/1705
https://github.com/rust-lang/rfcs/issues/1362 ).

**Comment by nalimilan** [comment]
See discussion at https://github.com/JuliaLang/julia/issues/16389. Closing as a duplicate since the two questions cannot be addressed separately (and honestly, I think that ship has sailed).
