### ISSUE TITLE
Update ReadTheDocs pdf or remove it and provide an updated PDF doc

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#22704]
Hello,

Following https://github.com/JuliaLang/julia/pull/20418#issuecomment-285857868

A Google search with "julia 0.6 pdf doc"

https://www.google.fr/search?q=julia%200.6%20pdf%20doc

shows

Julia Language Documentation - Read the Docs
https://media.readthedocs.org/pdf/julia/latest/julia.pdf

[PDF]Julia Language Documentation - Read the Docs
https://media.readthedocs.org/pdf/julia/stable/julia.pdf

but these docs are not updated.

ReadTheDocs pdf should be updated or removed 

Pinging @tkelman @nalimilan 

Kind regards

**Comment by scls19fr** [comment]
A PDF version of language documentation would also a nice feature to have (again).
https://docs.julialang.org/ doesn't seems to provide such a PDF version

**Comment by nalimilan** [comment]
I think we should just remove the Read the Docs project, just like we recently did for StatsBase. It's easy to do from the project page, but if an admin gives the me authorizations I can do it.

**Comment by tkelman** [comment]
All the old links there are for old versions, but what would shutting it off do to all those links? Can we put in a redirect somehow?

**Comment by scls19fr** [comment]
Some other Julia users are also looking for PDF version of doc
https://discourse.julialang.org/t/pdf-version-of-docs-for-v0-6/4559/13

**Comment by nalimilan** [comment]
After closing a project, all links give an empty page: http://dataframesjl.readthedocs.io/. It seems they provide a redirect feature: https://docs.readthedocs.io/en/latest/user-defined-redirects.html

**Comment by cossio** [comment]
I believe a PDF version of the docs would be very nice. For example, this is a nice format if you want to read on a tablet, or if you want to write annotations to it. Also, it's a single file which makes it very portable.

**Comment by cossio** [comment]
Could we rename this issue to "PDF version of the docs" or something like that? Itsn't just about updating / removing the outdated readthedocs version. It's also about maintaining a PDF version of the latest docs, don't you agree @scls19fr ?

**Comment by iblis17** [comment]
Actually the PDF file can be generated via `make -c doc pdf` simply, so... if we want PDF file be auto-deployed, we will need to patch `deploydocs` of Documenter.

---

[TheJuliaLanguage.pdf](https://github.com/JuliaLang/julia/files/1203147/TheJuliaLanguage.pdf)

**Comment by cossio** [comment]
@iblis17 Thanks, where can I run this command to compile a PDF myself?

**Comment by iblis17** [comment]
`cd /path/to/your/julia/repo && make -C doc pdf`
and it's at `doc/_build/html/en/TheJuliaLanguage.pdf`

**Comment by sarming** [comment]
After installing the fonts I also had to add `\usepackage{shellesc}` to the preamble of `TheJuliaLanguage.tex`, see [this SO answer](https://tex.stackexchange.com/a/313289/1451).
I don't know if this should be fixed in Documenter.jl or if one should wait for minted to fix it...
Anyway, here is the pdf: [TheJuliaLanguage.pdf](https://github.com/JuliaLang/julia/files/1230438/TheJuliaLanguage.pdf)

**Comment by cossio** [comment]
@sarming Nice, thanks.

**Comment by IngoHeimbach** [comment]
Here is the PDF documentation for the current stable version `0.6.2`: 
[TheJuliaLanguage_v0.6.2.pdf](https://github.com/JuliaLang/julia/files/2027100/TheJuliaLanguage_v0.6.2.pdf)

**Comment by adamryczkowski** [comment]
Here is the PDF with the current master (marked as version 1.1.0)
[TheJuliaLanguage 1.1.0.pdf](https://github.com/JuliaLang/julia/files/2300379/TheJuliaLanguage.1.1.0.pdf)

**Comment by adamryczkowski** [comment]
Note, that the Robo Mono font the docs are using lack several Unicode math symbols. Further details on https://github.com/JuliaDocs/Documenter.jl/issues/803

**Comment by mortenpi** [comment]
An up-to-date PDF has been available for a while now, advertised on the main page of the docs, so this can be closed I think. cc @fredrikekre 

The Unicode issue is tracked in #31048.
