### ISSUE TITLE
Building Rmath fails on macOS

### ISSUE THREAD

**Issue by mxkramer** [JuliaLang/julia#22706]
Hello,

I'm trying to install the `SpecialFunctions` package, but when building `Rmath` I get an error: "No rule to make target `qlnorm.o', needed by `libRmath-julia.dylib'.". Running `Pkg.rm("Rmath")` and then `Pkg.add("Rmath")` does not fix the issue.

I'm on macOS 10.12.5, here is the output from `versioninfo`:

```
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by ararslan** [comment]
Hey @mxkramer. Since this is a problem with the Rmath package rather than with Julia itself, I'm going to close this issue. Could you reopen it at https://github.com/JuliaStats/Rmath.jl? Thanks!
