### ISSUE TITLE
type inference fails for hash(::Array) in 0.7

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#22740]
The following test succeeds in 0.5 and 0.6 but fails in 0.7 master:
```jl
julia> using Base.Test; @inferred hash([1,2,3])
ERROR: return type UInt64 does not match inferred return type Any
Stacktrace:
 [1] error(::String) at ./error.jl:21
```
(Reported by @wsshin in stevengj/GeometryPrimitives.jl#8)

**Comment by nalimilan** [comment]
What is particularly interesting is that calling `hash([1,2,3], UInt(0))` or just `@code_warntype hash([1,2,3], UInt(0))` makes the return type instability disappear according to  `@code_warntype hash([1,2,3])`, but not according to `@inferred hash([1,2,3])`.

**Comment by nalimilan** [comment]
Could also be related to https://github.com/JuliaLang/julia/pull/16401#issuecomment-313514573 (see paragraph about `_hash`).
