### ISSUE TITLE
Documentation of slurping type constraint

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#22755]
If I understand it correctly:
```
f(x::Any...) = x
```
is a shorthand for:
```
f(x::Vararg{Any,N}) where N = x
```
However, I could not find it documented. I would recommend adding the following sentence at the end of [Parametrically-constrained Varargs methods](https://docs.julialang.org/en/latest/manual/methods.html#Parametrically-constrained-Varargs-methods-1) section of Julia manual:

> When only type of supplied arguments needs to be constrained `::Vararg{T,N}` can be equivalently written as `::T...`, for instance `f(x::Any...) = x` is a shorthand for `f(x::Vararg{Any,N}) where N = x`.

**Comment by timholy** [comment]
That section does link backwards to https://docs.julialang.org/en/latest/manual/functions.html#Varargs-Functions-1. Does that address your concern?

**Comment by bkamins** [comment]
I know, but there is no definition of `f(x::T...)` there.
I have submitted this because `x` does not have type `T` in the body of `f` and this is normally what you get when you write `x::T` in function definition.

**Comment by JeffBezanson** [comment]
More accurately, `x::Any...` is shorthand for `x::Vararg{Any}`.

**Comment by bkamins** [comment]
So is it worthwhile to make a PR with the text below?

When only type of supplied arguments needs to be constrained `Vararg{T}` can be equivalently written as `T...`. For instance `f(x::Int...) = x` is a shorthand for `f(x::Vararg{Int}) = x`.
