### ISSUE TITLE
touch up exit/quit docstrings

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#22765]
As discussed in https://github.com/JuliaLang/julia/pull/22651#pullrequestreview-47535698, the docstrings for `exit` and `quit`,
```julia
help?> exit
[...]
  exit([code])

  Quit (or control-D at the prompt). The default exit code is zero, indicating that the processes completed successfully.

help?> quit
[...]
  quit()

  Quit the program indicating that the processes completed successfully. This function calls exit(0) (see exit).
```
 might benefit from a wordsmith's attention. Specifically, `exit` could benefit from a reference to `quit`, somehow integrating "control-D at the prompt" more gracefully as a synonym could be an improvement, and smoothing out the somewhat-jarring but technically correct use of plural "processes" could also be a step forward. Best!

**Comment by Ismael-VC** [comment]
c vas
