### ISSUE TITLE
Implementation of var(v::Range) is not type-stable

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#22773]
Return type of, e.g., `var(0f0:1f0:10f0)` is `Union{Float32, Float64}`, due to conditional return of `NaN` in the implementation.

Example:

       @code_warntype var(0f0:1f0:10f0)q

`var(v::Range{T})` should probably return `real(momenttype(T))` in all cases, like `var(A::AbstractArray{T})` does.

May also affect implementation of similar functions.

**Comment by stevengj** [comment]
Looks like [this line](https://github.com/JuliaLang/julia/blob/d5035d85f74341faaf316dd66d812e33d215e9a9/base/statistics.jl#L226) should be
```jl
l < 2 && return momenttype(eltype(v))(NaN)
```
(`real` is unnecessary since ranges can't be complex-valued.)  Similarly for `varm`

**Comment by StefanKarpinski** [comment]
Might be a good use for return type annotation?
