### ISSUE TITLE
Methods can be extended improperly

### ISSUE THREAD

**Issue by ajkeller34** [JuliaLang/julia#22782]
Let's start with the following expected behavior:

```
julia> module A
       export test
       function test end
       end
A

julia> using A

julia> test
test (generic function with 0 methods)

julia> test() = 3
ERROR: error in method definition: function A.test must be explicitly imported to be extended

julia> test()
ERROR: MethodError: no method matching test()

julia> A.test()
ERROR: MethodError: no method matching test()
```

This is all well and good. We should have imported first. However, by omitting the line `julia> test`, apparently we can extend the method, sort of:

```
julia> module A
       export test
       function test end
       end
A

julia> using A

julia> test() = 3
test (generic function with 1 method)

julia> test()
3

julia> A.test()
ERROR: MethodError: no method matching test()
```

This seems to happen on 0.5.2, 0.6.0, and the latest master (macOS 10.12).

**Comment by fredrikekre** [comment]
#18181 ?

**Comment by ajkeller34** [comment]
I guess it is. That being said, this behavior is manifestly unclear to users. Three people have now raised similar issues (also https://github.com/JuliaLang/julia/issues/18427), so perhaps at least one of them should stay open, so that someone has the opportunity to see the issue and propose an alternative or otherwise address this?

My problem here is that the user thinks that `test` has been brought into the namespace once the module has been used. Apparently that doesn't happen until the symbol is resolved by either using the function or simply typing its name. At least, that's how it appears to me...

In the context of this example, how about silently evaluating in `Main` the symbols that were exported from `A` when the module is used? I'm not sure if that could have side effects in general but if not it would resolve the user-unfriendly behavior, without changing the behavior of method definition more generally.

**Comment by antoine-levitt** [comment]
Just ran into this, I agree it's very annoying, especially because it also happens to functions in Base. I wanted to extend A_ldiv_B! to a custom type, and my extension just erased the previous definitions. Definitely a big gotcha.

**Comment by StefanKarpinski** [comment]
We should require qualification to extend functions. That's a bit more verbose but it clears up any possible confusion.

**Comment by yuyichao** [comment]
So remove `import`?

**Comment by StefanKarpinski** [comment]
Yep. Remove import, require qualified names for extension. I discovered that `Base. ==` already works for extending operators in `Base`; people couldn't decide if this was brilliant or horrible. I'm still not sure myself, but it's easier and more consistent than `Base.:+` and `Base.:(==)`. See the `#modules` channel on the JuliaLang Slack for discussion.

**Comment by yuyichao** [comment]
While I don't really like to use `import` it seems that we mostly get complain that a `using`d method is not being extended (just like this one). Removing `import` seems to be fixing the wrong problem.

**Comment by StefanKarpinski** [comment]
The problem is that people expect that they can write `f(...) = ` and extend another package's `f`. If they're taught from the start that you have to write `A.f(...) = ` to extend `A`'s `f` function, then there's no more issue. This has already become a fairly widespread best practice anyway.

**Comment by KristofferC** [comment]
I don't see how extending methods without module qualification is related to removing `import`. `import` still has use even if you are not using if for method extension.

**Comment by yuyichao** [comment]
I just think that the difference between function from another module and function from your own module might be a little too subtle and it makes moving code harder. I think people will also expect if they can call `f` in one module, `f(...) = ...` can also extend it.

> `import` still has use even if you are not using if for method extension.

How is it useful other than for method extension? It's just `using`. You can rename `using` to `import` but the one(semantic) that's removed is still `import`.

**Comment by KristofferC** [comment]
Maybe I'm wrong but I thought `import` on a package allowed you to not bring all the exported stuff  into scope.

**Comment by JeffBezanson** [comment]
Obviously it's not up to me what other people find confusing, but the current approach is a "local by default" approach. The idea is that it's safer to make new, module-local functions than to extend other people's functions. Otherwise this scenario could happen:

```
using Foo

f() = ...
```

Here I intend to make my own new function `f`. However, if package `Foo` one day adds an `export f`, I would then be extending Foo's function without realizing it. That would be bad. As it is, only 3 things can happen:

1. You get a new local function of your own.
2. You explicitly import or qualify a name to indicate that you want to extend another function.
3. You get an error.

I contend that all of these are reasonable. There is no "sort of" function extension --- either you extend a function, or make a new one.

The only thing I can imagine adding to this is an error or warning in part (1) if your new function conflicts with a name brought in by `using`. That would avoid any potential confusion, but to fix it you'd have no choice but to individually import every name you want to use, which many people find unacceptable.

**Comment by JeffBezanson** [comment]
> import on a package allowed you to not bring all the exported stuff into scope

:100: Yes, `import X` and `import X.y` have the very nice property that they always import exactly one name. While `using A.B` brings in everything from `B` *if* it's a module, and otherwise brings in the one name A.B. I think this is a quasi-bug.

**Comment by ajkeller34** [comment]
Sorry all, in retrospect I was just confused about the behavior of `using` and why the method definition warnings appeared "inconsistently" (to me, but not really). The following in the manual is pretty crucial to keep in mind:
> The statement `using Lib` means that a module called `Lib` will be available for resolving names as needed. When a global variable is encountered that has no definition in the current module, the system will search for it among variables exported by `Lib` and import it if it is found there.

Compare that with the table in the summary of module usage in the docs. The table says that `using MyModule` and `importall MyModule` "bring into scope" all exported names, but there can be differences in the warnings generated if you try to define something after `using MyModule` or `importall MyModule`, even when we're not talking about method extension. Maybe the table could highlight this difference somehow because otherwise the table alone is not enough to understand that behavior. I suspect others besides myself will read the manual once, refer to the table only for years afterward, and forget the particulars of `using`, leading to issues like this popping up once in a while. Perhaps simply an asterisk in the table linking to the text I mentioned would suffice to avoid that.
