### ISSUE TITLE
file testset fails unless curl is installed (0.6.0)

### ISSUE THREAD

**Issue by ilia-kats** [JuliaLang/julia#22783]
In particular, the exact failure is
```
Test Failed
  Expression: download("ba\0d", "good")
    Expected: ArgumentError
      Thrown: Base.UVError
```
This boils down to download() choosing wget to download the file. Wget is never run however, since run() throws the ArgumentError. The catch clause (interactiveutil.jl:595) assumes that wget did run, and tries to remove the newly created file, which fails with UVError since the file was not greated due to wget never being executed.

**Comment by tkelman** [comment]
thanks for reporting and debugging a bit. throwing a different exception depending on what downloader is used doesn't seem desirable to me. why does wget throw an ArgumentError but curl doesn't?

**Comment by ilia-kats** [comment]
sorry, clicked on the wrong button...
it's the other way around: curl throws ArgumentError, wget doesn't. In both cases, run() throws ArgumentError, but when wget is used that error is caught and the catch clause tries to do some cleanup after wget, where rm() throws the UVError.

**Comment by tkelman** [comment]
Ah, gotcha. That seems like an oversight in #21071 then, maybe that rm call should use the force keyword argument?

**Comment by ilia-kats** [comment]
probably, yes

**Comment by KristofferC** [comment]
I think this should be fixed with the new ´Downloads` stdlib.
