### ISSUE TITLE
Rename select

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#22791]
`select` is a very overloaded term, with common meanings in databases (inspired from [SQL](https://en.wikipedia.org/wiki/Select_(SQL))) and [Unix I/O APIs](https://en.wikipedia.org/wiki/Select_(Unix)). The fact that Base defined a function with that name is annoying for query packages: both Query.jl and DataFramesMeta.jl define a `@select` macro, and the latter currently defines a `select` function (with type piracy issues, cf. https://github.com/JuliaStats/DataFramesMeta.jl/pull/75).

On top of this, `select` does not appear to be a standard name at all for what this function does, i.e. partial sorting a.k.a. selection algorithm. Very few languages seem to provide such a function in their standard library, and none uses this name. The closest example I could find is the C++ stdlib, which provides [`partial_sort`](http://en.cppreference.com/w/cpp/algorithm/partial_sort) and [`nth_element`](http://en.cppreference.com/w/cpp/algorithm/nth_element) (the latter being equivalent to our `select` when passed a single index). Perl's [`Sort::Key::Top`](http://search.cpan.org/dist/Sort-Key-Top/lib/Sort/Key/Top.pm) module provides `topsort` and `atpos`, respectively. Python provides `heapq.nlargest`/`heapq.nsmallest`, but no equivalent of `nth_element`/`atpos`. C++, MATLAB, Ruby, Rust and Go do not support this AFAICT.

I suggest renaming `select` to `partial_sort` or `partialsort`. It appears to be the most common name used on forums (in particular since the C++ stdlib is the only major implementation around), it's similar to `sort`, it's more explicit and thus easier to find and it does not conflict with other uses.

For reference, `select` was added in 51d055d07747e9564844ea52b7395db3289a6d6d and integrated to Base in 561bcc32e3cea6bc519e6ec9a8c44ae511ff1bf2.

**Comment by andyferris** [comment]
This has bothered me previously. 

`partialsort` seems like an excellent replacement to me.
