### ISSUE TITLE
correct method not called when adding one involving Type of Union

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#22792]
Sorry for the bad title (I lack vocabulary on that topic, please edit it). It looks like a #265 problem:
```
julia> foo(::Type{<:Union{Int8,Int,UInt}}) = 1;

julia> foo(Union{Int,UInt})
1

julia> foo(::Union) = 2; 

julia> foo(Union{Int,UInt})
1

julia> foo(Union{Int8,UInt})
2

julia> foo(Union{Int,UInt}) # now works correctly
2
```

**Comment by vtjnash** [comment]
Likely the same as https://github.com/JuliaLang/julia/issues/11840

**Comment by JeffBezanson** [comment]
Seems to work now. The first method is always more specific, and `1` is always returned.
