### ISSUE TITLE
Error adding remote workers on Windows

### ISSUE THREAD

**Issue by ivborissov** [JuliaLang/julia#22807]
Didn't have this error with 0.5 and faced it on 0.6. Trying to add remote worker on windows machine using HTCondor/ClusterManagers and facing the following error:
Error: ERROR:Unable to read host:port string from worker. Launch command exited with error?

In logs I have:

fatal: error thrown and no exception handler available.
Base.InitError(mod=:Pkg, error=UndefVarError(var=:UV_ENOBUFS))
rec_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\stackwalk.c:84
record_backtrace at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:245
jl_throw at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:564
jl_undefined_var_error at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\rtutils.c:129
jl_get_binding_or_error at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\module.c:236
homedir at .\path.jl:71
_pkgroot at .\pkg\dir.jl:10 [inlined]
__init__ at .\pkg\pkg.jl:91
unknown function (ip: 0000000061DFB54E)
jl_call_fptr_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:339 [inlined]
jl_call_method_internal at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia_internal.h:358 [inlined]
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1933
jl_apply at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1424 [inlined]
jl_module_run_initializer at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\toplevel.c:87
_julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\init.c:733
julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:297
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:259
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:329
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.2-1/crt\crtexe.c:212
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
close: Result too large

**Comment by tkelman** [comment]
need to backport https://github.com/JuliaLang/julia/pull/22457, believe that would fix this

**Comment by ivborissov** [comment]
thanks. In 0.7-dev I have the following error in logs:
Error: ERROR:Unable to read host:port string from worker. Launch command exited with error?
Base.InitError(mod=:Pkg, error=ErrorException("unable to retrieve home directory"))

**Comment by ivborissov** [comment]
Solved the issue (on 0.6) by adding USERPROFILE env variable 
http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_homedir
