### ISSUE TITLE
MyType[:a :b; :c :d] is a syntax error on latest master

### ISSUE THREAD

**Issue by eveydee** [JuliaLang/julia#22840]
In v0.6, this works:
```julia
struct MyType{T}
    value::T
end
Base.convert(::Type{MyType}, x::MyType) = x
Base.convert(::Type{MyType}, x) = MyType(x)
A = MyType[:a :b; :c :d]
```
to create a Matrix of `MyType`s.

In latest master this gets interpreted as a slicing of some sort, I guess, because I get the following error:
```julia
ERROR: syntax: expected separator between arguments to "[ ]"; got ":a:"
```
Same thing for larger matrices of symbols. But
```julia
A = MyType[:a; :c]
```
has no such problems.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/22816#issuecomment-315681589
