### ISSUE TITLE
"method definition has free type variables" error when ANY used as type parameter

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#22854]
```
julia> foo(a::Tuple{Symbol,ANY}) = a[1]
ERROR: ArgumentError: method definition for foo at REPL[1]:1 has free type variables
```

This probably didn't mean much of anything, but would be good if the ANY deprecation could handle it better than an error since various packages had been doing this.

**Comment by JeffBezanson** [comment]
I think it's good to turn this into an error. This code was never valid, and could very well be causing problems in the system.

**Comment by ararslan** [comment]
What's the correct fix in this case? In FFTW there's code that was using `ANY` as a type parameter, but exchanging for `Any` or for `T` with a `where T` seem to be producing different results than the previous behavior.

**Comment by JeffBezanson** [comment]
Generally `<:Any` should be similar, but this was not really a valid type so it's hard to predict how it would have behaved.

**Comment by tkelman** [comment]
sounds like this a won't fix then, unless someone speaks up loudly in favor of reopening for a deprecation warning
