### ISSUE TITLE
copy(x::Symbol) isn't defined

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#22851]
Is there a particular reason this method was omitted?

**Comment by yuyichao** [comment]
Yes because it can't be copied. https://github.com/JuliaLang/julia/pull/15675

**Comment by sbromberger** [comment]
As mentioned in the linked issue, this is inconsistent. `copy(5.3)` works, and it's puzzling to have to do, e.g.,

```
copy(g::T) where T <: AbstractMetaGraph = 
    T(
        copy(g.graph), 
        copy(g.vprops), 
        copy(g.eprops), 
        copy(g.gprops), 
        g.weightfield, 
        copy(g.defaultweight)
    )
```

**Comment by JeffBezanson** [comment]
Generally a `copy` method for a (mutable) container should only copy the container structure, and not values inside.
