### ISSUE TITLE
Changing order of iterators gives an error

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#22867]
```
prod([i for j = 1:10 for i in 1:10 if i > 10])
# result = 1
```

but

```
prod([i for i in 1:10 if i > 10 for j = 1:10])
```
> ERROR: ArgumentError: argument to Flatten must contain at least one iterator

Something seems wrong here...

Related: https://discourse.julialang.org/t/can-i-type-assert-the-eltype-of-an-iterator/4936

**Comment by JeffBezanson** [comment]
An interesting case of #18852. `Flatten` is able to accept a single empty iterator, but not zero iterators.

**Comment by JeffBezanson** [comment]
Dup of #18852.
