### ISSUE TITLE
function isfull for channel

### ISSUE THREAD

**Issue by usefulhyun** [JuliaLang/julia#22863]
In order to avoid blocking, I need ``isfull`` function or function that have the same functionality for channels.

**Comment by amitmurthy** [comment]
Yes, I think we should have this. Like we have `isready` for `take!`, `isfull` will be the analogous check-if-it-will-block function for `put!`.

If you are using a buffered channel, you can use the undocumented `Base.n_avail(::Channel)` call and check if `Base.n_avail(c) == channel_size`. It will not do what you want on unbuffered channels.

PRs to add this functionality are welcome.

**Comment by StefanKarpinski** [comment]
Keep in mind that `full` already means something unrelated when choosing a name here so `isfull` may not be the best name choice.

**Comment by touchft** [comment]
How about possible options:
isready(::Channel, put=true)
isready(::Channel, :put)
isready(::Channel,  dir="put)
isready(::Channel;  dir=:put)

**Comment by KronosTheLate** [comment]
I was about to make a PR to add `isfull` for channels, as I found myself implementing it for a project. It was the first and only project where I used channels, which I think says something about how useful and natural such functionality was.

There is also a [relevant discourse discussion](https://discourse.julialang.org/t/function-to-check-if-channel-is-full/44795). Between me about to make a PR, that discourse post, and this issue, I would say that this is worth re-visiting. The implementation suggested in the discourse post is:
```julia
begin isfull(ch::Channel) =
    if ch.sz_max===0
        isready(ch)
    else
        length(ch.data) ≥ ch.sz_max
    end
end
```

My proposed implementation, relying on other definitions, is as follows:
```julia
isfull(c::Channel) = isbuffered(c) ? (Base.n_avail(c) == c.sz_max) : isready(c)
```
Note that "Base.n_avail is a "Lock-free equivalent to `length(c.data) + length(c.cond_put.waitq)`", meaning that the proposals are not exactly equivalent. I am not sure about which is better in terms of behaviour, as I do not know in which cases `length(c.cond_put.waitq` would make a difference.

Regarding @StefanKarpinski note about `isfull` not being an ideal name, I need a little more convincing. I currently find that that name is very natural and therefore discoverable, nicely mirrors `isempty` (which is defined for `Channel`), and is easy to read and understand the meaning of. I also do not know about good alternatives.

Note that DataStructures exports `isfull`, so a compatability-PR should be made there should this go through.

**Comment by StefanKarpinski** [comment]
Yeah, seems fine to me. It's not even clear to me what other meaning of "full" I was thinking of in 2017 😂

**Comment by vtjnash** [comment]
It might need some locks and/or atomics, but yes, that sounds fine (and very similar to https://github.com/JuliaLang/julia/pull/40720)

**Comment by KronosTheLate** [comment]
> It might need some locks and/or atomics, but yes, that sounds fine (and very similar to https://github.com/JuliaLang/julia/pull/40720)

So that PR has been stale since mid-2021. Particularly relevant is perhaps Jeff's comment:
> These functions seem like a bad idea to me --- don't they just encourage writing race conditions?

I would clearly like to have this implemented, and it seems like you both are also not against it. What is the appropriate path forward? I have to say that the names proposed in #40720 seem quite bad to me, especially when `isfull` is available. I am unsure if it is most appropriate to change that PR, make a new one, or wait until someone with merge rights just "gets it done" (It seems like things progress somewhat faster when the core devs are the only ones involved, which is of course completely fair).

**Comment by vtjnash** [comment]
If you make a new PR (with `isfull`), I will try to get to it soon to merge it. However, please recognize some credit to SamuraiAku in your commit for his past attempt (Co-authored-by is fine), as even if you don't use anything from his PR, it is nice to recognize his work.

It isn't quite true that things progress faster if you wait for someone like me to do it, as clearly I have not gotten around to doing that for several years now, despite being on my list for an even longer while to improve the Channels API. If anything the correlation is reversed: when we see an author is prompt about updating their PRs and getting CI to pass, new tests written, and consensus reached, then we tend to try to recognize that by handing them commit rights also.

**Comment by KronosTheLate** [comment]
Done! Feel free to take a look.

**Comment by KronosTheLate** [comment]
Will be closed by https://github.com/JuliaLang/julia/pull/53159

**Comment by SamuraiAku** [comment]
Issue did not close automatically with the merging of #53159
