### ISSUE TITLE
OutofMemory Error when use remote reference model.

### ISSUE THREAD

**Issue by usefulhyun** [JuliaLang/julia#22862]
Sometimes my program get stuck, but sometimes that program finishes well.
There is no any input. Just static program.
The program is my profiling program for parallel computing.
When program got stuck, I input Ctrl+C and got error and I checked The error is OutOfMemoryError().
does Anyone suffer from this kind of problem like me?

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
