### ISSUE TITLE
Cryptic error for `Complex(::Irrational)`

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#22878]
```julia
julia> complex(pi)
```
```
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Irrational{:π}
```

**Comment by mschauer** [comment]
That is 
```
zero(pi)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Irrational{:π}
```

**Comment by strickek** [comment]
or here?
```
julia> convert(Irrational, 0)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Irrational
This may have arisen from a call to the constructor Irrational(...),
since type constructors fall back to convert methods.
```

**Comment by malmaud** [comment]
Should be pick a default reasonable precision, like `Float64`, to make `complex(pi)` work? Or just add a more understandable error message?

**Comment by tkelman** [comment]
See the last remaining bullet on #21204, cc @giordano

**Comment by giordano** [comment]
The decision in PR #22928 was to keep the error and don't provide a default behavior.  I guess this ticket can be closed, unless someone wants to improve the error message.

**Comment by malmaud** [comment]
I think this should stay open until the error is approved.

**Comment by perrutquist** [comment]
`complex(pi)` is one of many methods that would start working if `zero(pi)` were defined.

**Comment by vtjnash** [comment]
We discussed this on triage, and felt that it is better to be explicit about the transforms for irrational numbers into the appropriate computational types and not add more methods to them.

In this way, this type could be viewed as being similar to `undef`, that exist as a token to pass to various constructors, but is not itself a fully-fledged type (another example of this may be `I` in LinearAlgebra).
