### ISSUE TITLE
build failure on Windows

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#22873]
At 44f3d7c921.  My previous successful build was at 7c045f0277.
Build succeeds on Ubuntu, macOS and arm.

```
JOSEFSACHS7548$ make
cp  /home/sachs/src/julia-master/usr/bin
cp: missing destination file operand after '/home/sachs/src/julia-master/usr/bin'
Try 'cp --help' for more information.
make: *** [Makefile:326: /home/sachs/src/julia-master/usr/bin/libatomic-1.dll] Error 1
```

**Comment by tkelman** [comment]
What is `x86_64-w64-mingw32-gcc --version` ? No longer need to hold back to 4.9, upgrading to latest via the cygwin package manager is recommended.

**Comment by josefsachsconning** [comment]
```
JOSEFSACHS7548$ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tkelman** [comment]
Upgrade to 5.4. Sorry you'll have to clean out the existing builds for at least the C++ dependencies.

**Comment by josefsachsconning** [comment]
Will 5.4 work for release-0.5 and release-0.6 in addition to master?

**Comment by tkelman** [comment]
Yes it should, though it's an ABI change relative to what the 0.5.2 release binaries were built with IIRC. So any C++ binary dependencies used by packages might need to be recompiled.

**Comment by josefsachsconning** [comment]
Builds successfully with gcc 5.4.0.

**Comment by tkelman** [comment]
closing then, but leave a comment if you think there's anything that needs to be done here
