### ISSUE TITLE
Embedding include cleanup

### ISSUE THREAD

**Issue by tkonolige** [JuliaLang/julia#22887]
The julia embedding include directory should be cleaned up. It has a couple of potential issues right now:

1. Poor include guard names: the embedding interface header files have very guard names like `UTILS_H`. If other projects also use generic names, then they can conflict. Prefixing each guard name with `JULIA_` would fix this problem.
2. Polluting the include namespace: `julia-config.jl` generates `$JULIA_HOME/include/julia` as an include directory. The user then uses `#include <julia.h>` to embed julia. The problem is that this directory contains a lot of files that the user doesn't need to import and that will conflict with other libraries (for example `#include <uv.h>`). Ideally `julia-config.jl` would generate `$JULIA_HOME/include` as the include directory and the user would type `#include <julia/julia.h>` to embed julia.

I would be happy to submit patches for both these issues if they would be accepted.

**Comment by StefanKarpinski** [comment]
The Julia prefix in C-land is `JL_` but otherwise spot on. A PR would be very welcome!
