### ISSUE TITLE
Slowdown with @fastmath and complex numbers

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#22898]
```jl
using BenchmarkTools 

function fractal(z, c, lod)
   for i in 1 : lod
          @fastmath (abs(z) > 2) ? (return i) : (z = z^2 + c) 
   end
   return lod
end
```

```jl
julia> @btime fractal(1im,1im,1)
  46.854 ns (2 allocations: 48 bytes)
```

Removing `@fastmath`:

```jl
julia> @btime fractal(1im,1im,1)
  9.455 ns (0 allocations: 0 bytes)
```

Ref: https://github.com/JuliaLang/julia/issues/19298

One problem is the type instability where `z` first is a `Complex{Int64}` and then turned into a `Comlex{Float64}` after the exponentiation. Fixing this removes the allocation but doesn't change the execution speed:

```jl
julia> @btime fractal(1.0im, 1.0im, 1)
  46.405 ns (0 allocations: 0 bytes)
```

Edit: It seems that the fast macro makes the exponent dispatch to a function that promotes both numbers to complex.

Edit2: Fixing the above, it turns out that the generic power by squaring is faster anyway up to  an exponent of ~ 1000000000...

Edit3: The `@fastmath` macro also destroys the `Val{2}` exponent optimization in the lowering since the syntax is rewritten to `pow_fast(z, 2)`.

**Comment by ajkeller34** [comment]
re: edit3: https://github.com/JuliaLang/julia/pull/21099 has been open for a while. It'd be nice to either merge or close that.

**Comment by KristofferC** [comment]
Runs at same speed now.
