### ISSUE TITLE
Misleading/inconsistent depwarn and error on `zeros` and `ones`

### ISSUE THREAD

**Issue by evanfields** [JuliaLang/julia#22903]
I came across this situation organically today (on 0.6, same on 0.7.0-DEV.1063):
```
julia> zeros(Int, 3.0)
WARNING: zeros(T::Type, arr) is deprecated, use zeros(T, size(arr)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] zeros(::Type{T} where T, ::Float64) at .\deprecated.jl:57
 [3] eval(::Module, ::Any) at .\boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\REPL.jl:66
 [5] macro expansion at .\REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
0-dimensional Array{Int64,0}:
0
```
Even if it's appropriate for `zeros` to treat floats as 0-dimensional arrays, this warning is misleading by suggesting an array was passed. I suspect in regular usage neglecting to convert to an int is more common than accidentally creating a 0-dimensional array. Further
```
julia> zeros(Int, Array{Int,0}())
ERROR: `zeros{T}(::Type{T}, arr::Array{T})` is deprecated, use `zeros(T, size(arr))` instead.
Stacktrace:
 [1] zeros(::Type{Int64}, ::Array{Int64,0}) at .\deprecated.jl:1329
```
So there seem to be two inconsistencies: first, it's confusing for an error message to say a function is deprecated; if the function is deprecated, it should still work with a warning. Secondly, the warning on the first call and subsequent return type suggest the argument `3.0` is being treated as a 0-dimensional array, but the error in calling `zeros` with an actual 0-dimensional array suggests this is not so.

Clearly these are minor points and easy to work around in practice, but still, a bit confusing.

**Comment by fredrikekre** [comment]
Given that `zeros(Int, 3.0)` is a `MethodError` on 0.5 I think this is fine?
It is a bit tricky to change [this deprecation](https://github.com/JuliaLang/julia/blob/4fea2033758793c6ba980695fe252eeb69fa5761/base/deprecated.jl#L1315) since we would have to restrict it to all types where `Array{T}(A)` works (and the rest should still be a `MethodError`), see [this](https://github.com/JuliaLang/julia/blob/c3b8ad0ba9c514db9014eaa8e53ef789e1ebf1e8/base/array.jl#L169).

The second case seem correct to me:
```julia
julia> zeros(Int, Array{Int,0}())
ERROR: `zeros{T}(::Type{T}, arr::Array{T})` is deprecated, use `zeros(T, size(arr))` instead. 
Stacktrace:
 [1] zeros(::Type{Int64}, ::Array{Int64,0}) at ./deprecated.jl:1329

julia> zeros(Int, size(Array{Int,0}()))
0-dimensional Array{Int64,0}:
0
```

Not sure if there is anything we can do here?

**Comment by StefanKarpinski** [comment]
Two possible options:

1. Allow numbers for dimension sizes.
2. Handle the error case for numbers separately from other objects and give a better error.

**Comment by JeffBezanson** [comment]
Not an issue anymore. We allow 3.0 as a size argument, and these deprecations have been removed.
