### ISSUE TITLE
Tensor Contraction Multiplication

### ISSUE THREAD

**Issue by cstepper** [JuliaLang/julia#22914]
The multiplication behavior is unexpected relative to other languages, particularly R and Matlab.  I know #3250 was closed.  But I feel like this should be called out in the noteworthy differences between Julia and other languages documentation. 

Also, I think the comment "If A and B are matrices, then A * B denotes a matrix multiplication in Julia, equivalent to R's A %*% B" in the "Noteworthy-Differences" section isn't correct in the contraction scenario.

**Comment by StefanKarpinski** [comment]
What are you saying is different here? Perhaps an example would help explain what you mean.

**Comment by yuyichao** [comment]
I think he's talking about the difference between `*` and `.*`.

**Comment by StefanKarpinski** [comment]
That behavior is exactly like Matlab...

**Comment by cstepper** [comment]
Hopefully this clarifies:

```
  rect3x2::Matrix{Int} = [0 1; 2 3; 4 5]
  try
    println("Will make an error: ", rect3x2*rect3x2)
  catch err
    println(err)
  end
  println("Expected behavior: ",
    kron(rect3x2[:,1],rect3x2[:,1]') .+
    kron(rect3x2[:,2],rect3x2[:,2]'))

OUT:
DimensionMismatch("matrix A has dimensions (3,2), matrix B has dimensions (3,2)")
Expected: [1 3 5; 3 13 23; 5 23 41]
```
