### ISSUE TITLE
Base.parse(stream::IO, ...) method is in a weird place

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#22924]
It's defined [in the markdown code](https://github.com/JuliaLang/julia/blob/master/base/markdown/Julia/interp.jl#L3). Seems like it would be good to move it to the same place as the rest of the parsing methods or make it a private method for the markdown code.

Also, it reads until the end of the string and then seeks back to just after the part it's actually looking for, which is a bit weird and not particularly efficient. I'm not sure the current flisp parsing code would allow us to easily write this method differently though.

**Comment by JeffBezanson** [comment]
Yep, that's why the "official" `parse` method only accepts strings.
