### ISSUE TITLE
Documentation for old/unmaintained releases of julia

### ISSUE THREAD

**Issue by alexmorley** [JuliaLang/julia#22936]
Many google searches will often bring up the documentation for older releases of julia. When trying to search for e.g. "julia integer" or something similar the docs for v0.4 will be the first hit.

To prevent confusion I think it would be useful to either:

-  Provide an obvious warning somewhere on each page (ala [scikit-learn](http://scikit-learn.org/stable/supervised_learning.html#supervised-learning)) - stating that those docs are for an un-maintained version of julia
- Automatically redirect (maybe with a notice saying "you have been redirected to the documentation for the latest stable version of julia - click here to see the docs for v0.x".

Happy to submit a PR if people agree.

**Comment by ararslan** [comment]
It should be possible to keep old versions of the documentation out of Google search results entirely (maybe via robot.txt or something?). That might be the best solution. I don't think we necessarily want to redirect people since there are probably people still stuck on e.g. 0.4 for whatever reason who still need access to the documentation.

**Comment by maleadt** [comment]
> It should be possible to keep old versions of the documentation out of Google search results entirely (maybe via robot.txt or something?). That might be the best solution.

What about googling for functions that have been deprecated and are not part of the current documentation?

**Comment by ararslan** [comment]
Ah, a very good point. Perhaps a big warning at the top of the old page would be good then.

**Comment by alexmorley** [comment]
Sounds like a warning on old versions is the best way to go. Anyone got any smart ideas about how easiest to do that (not super familiar with Documenter)?

**Comment by ararslan** [comment]
The documentation for versions of Julia prior to 0.6 didn't use Documenter. I'm not sure how those docs were generated.

**Comment by iblis17** [comment]
It's via sphinx

**Comment by iblis17** [comment]
https://github.com/JuliaLang/julia/blob/release-0.5/doc/Makefile#L69
this target can generate static html, and you will need a python virtualenv with sphinx installed

**Comment by iblis17** [comment]
Please checkout this PR: #23043
