### ISSUE TITLE
tempnam() should be avoided in the unix version of tempname() function

### ISSUE THREAD

**Issue by sambitdash** [JuliaLang/julia#22949]
tempnam() is marked obsolete in the opengroup spec as well. See the link for Issue 7.

http://pubs.opengroup.org/onlinepubs/9699919799/functions/tempnam.html

**Comment by tkelman** [comment]
I think we should deprecate the Julia `tempname` completely, it's got a lot of problems (xref https://github.com/JuliaLang/julia/issues/9053 as well)

**Comment by nalimilan** [comment]
Right, `tempname` isn't safe due to race conditions with potential attackers. Better make this clear by requiring people to use `randstring` explicitly when they really can't use `mktemp`.

Let's close this in favor of #9053, where the discussion has already happened?

**Comment by laborg** [comment]
The use of `tempnam` has been removed in https://github.com/JuliaLang/julia/pull/38879/files
