### ISSUE TITLE
LOAD_PATH should play nicely with FHS and external packagers

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2295]
Most people seemed to agree with the basic improvements I [suggested on the mailing list](https://groups.google.com/forum/#!msg/julia-dev/Z6GsLURuIZE/AmxBLNsz60MJ) in order for Julia to play nicely with the Unix [FHS](http://www.pathname.com/fhs/) as well as with external (non-Pkg) packagers like Linux distributions.  See also #1692.

The main changes that are needed are:

- [x] Put standard places in the `LOAD_PATH` for non-Pkg code. *Done in issue #2550*
- [x] On Unix, there should be places for code installation under both `/usr/share` and `/usr/local/share` according to the FHS (the former for system packagers, i.e. distros, and the latter for local installations from source etc.) *Done in issue #2550*
- [ ] The Julia version (major.minor only) should be a part of the path so that different Julia versions can co-exist.   That is, install everything under `/usr/share/julia/0.1`, not under `/usr/share/julia` directly.

These kinds of path choices need to be made ASAP, in my opinion; the longer you wait, the more disruptive it gets to make this kind of change.

The first two points require only a trivial patch (#2296): modify `base/client.jl` to define `LOAD_PATH` as:

	global const LOAD_PATH = ByteString[
            ".", # TODO: should we really look here?                               
            abspath(Pkg.dir()),
            abspath(JULIA_HOME,"..","share","julia","extras"),
            abspath(JULIA_HOME,"..","local","share","julia","lib"),
            abspath(JULIA_HOME,"..","share","julia","lib"),
        ]

Change (*update*: changed from `nonpkg`) `lib` to whatever directory name you prefer.  (`external`, `site`, ...?)

The third point requires a bit more invasive patch to the `Makefile` etcetera in order to update the installation paths.  (You might also consider installing `julia` as `julia`_major.minor_, e.g. `julia0.1`, with `julia` being a symlink, similar to Python.)   I looked through the `src/` directory, but I couldn't find where `jl_load("boot.jl")` looks to find `boot.jl`, but that would need to be changed too.

(Possibly the /usr/local/share path should be `@unix_only`, but it seems harmless to include it on Windows too.)

**Comment by stevengj** [comment]
Closing in favor of #17666 for the remaining directory-versioning issue.

**Comment by steverweber** [comment]
When a developer needed to know the path of their package to lets say access some extra files under a dir `data` they would do something like:
```
extra_json = Pkg.dir("NoveltyColors", "data", "file.json")
```
But if the package was installed in a different location `Pkg.dir` wont work...

**Comment by tkelman** [comment]
`dirname(@__FILE__)`

**Comment by steverweber** [comment]
thanks... ill pass that on!
