### ISSUE TITLE
some functions are still implicitly vectorized for SparseVector

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#22959]
I haven't seen an issue or PR for this, but feel free to close if I'm missing something.

base/sparse/sparsevector.jl still has method definitions for sin, tan, exp, etc. that operate element-wise over SparseVectors.

**Comment by ararslan** [comment]
As a tip to anyone who wants to take this on: The deprecations for these functions are for `AbstractArray`, so simply removing the explicitly defined methods for sparse arrays should let those go through the existing deprecation path without having to add a new one.

**Comment by fredrikekre** [comment]
> so simply removing the explicitly defined methods for sparse arrays should let those go through the existing deprecation path without having to add a new one.

But the deprecations for `SparseVector` should still be there for another release, since this does not depwarn in 0.6? Probably easiest to just add new deprecations for the special case of `SparseVector`?

**Comment by Sacha0** [comment]
PR inbound :).

**Comment by ararslan** [comment]
> But the deprecations for SparseVector should still be there for another release

The goal is to have no depwarns for anything in 1.0

**Comment by fredrikekre** [comment]
> The goal is to have no depwarns for anything in 1.0

Yes, but IIUC `sin(x::SparseVector)` should depwarn on 0.7, but `sin(x::AbstractVector)` should not be defined since the 0.6 deprecations are removed?

**Comment by ararslan** [comment]
Oh I see what you mean. Yeah I guess adding explicit deprecations is probably better then.
