### ISSUE TITLE
Segfault during coreimg bootstrap with old glibc

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#22952]
Bisect points to https://github.com/JuliaLang/julia/pull/22818/commits/5ff4353468293289c0b70741a384f4f0c3d9b128 as being the first bad commit. I tried and failed to reproduce this in a centos 6 docker container, seems to only happen on x86_64 linux, centos 5. The generic linux binaries are still built from centos 5 until we get the new buildbots finished and deployed, so nightlies are stuck at older than https://github.com/JuliaLang/julia/pull/22818 until this gets resolved (~~that buildbot along with the win64 buildbot happen to be down right now for other reasons that we can hopefully~~ fix[ed] separately).

I built all the deps into a docker container so you can reproduce this with `docker run -it tkelman/c6g6:juliadeps05 /bin/bash` then `make -j4` (everything but julia src is built already), it's a few GB to download so don't try on a slow connection. Release coreimg complains about
```
llvm::cast<llvm::Instruction, llvm::User> (Val=0x745c4c7db603d350)
    at /tmp/julia/usr/include/llvm/Support/Casting.h:237
237       assert(isa<X>(Val) && "cast<Ty>() argument of incompatible type!");
```
Debug coreimg backtrace here: https://gist.github.com/2dce6ebb0edbdd857d68c0bee791ec67

**Comment by JeffBezanson** [comment]
Fixed by #22993.
