### ISSUE TITLE
Suspected incorrect value in exponential random generator ziggurat coefficient table

### ISSUE THREAD

**Issue by bashtage** [JuliaLang/julia#22965]
The first value in `ke` is `0x000e290a13924be3`.  This is returned, multiplied by a 52-bit uniform whenever the random is less than this value.  Then this occurs, the random is multiplied by `1.9311480126418366e-15`, and which produces a uniform on [0,8.697117470131047).  This happens about 88% of the time.  

https://github.com/JuliaLang/julia/blob/master/base/random.jl#L1403

When this does not occur, `randexp_unlikely` is called and a seperate exponential is returned right shifted by `ziggurat_exp_r=7.6971174701310497140446280481`.  I beleive in ziggurat methods that the tail should start at the end of the uniform block for the bottom slice of the distirbution, and so using two different values, 7.697117470 and 8.69711747013 (which differ exactly by 1), may not be correct.

**Comment by andreasnoack** [comment]
@bashtage Did you close this intentionally?

**Comment by bashtage** [comment]
Yes.  I believe I made a mistake in my calculations.
