### ISSUE TITLE
[0.6] LLVM intrinsics are looked up in the wrong place

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#23009]
See e.g. https://ci.appveyor.com/project/Keno/pyjulia/build/1.0.15/job/mtc9w4vf23l0nu5y. When llvm lowers intrinsics to libcalls, it apparently tries looking them up in the base executable, which doesn't have them. We should either do look them up in openlibm or, even better, do something like #18927.

**Comment by vtjnash** [comment]
It should have them? We statically link libopenlibm into most places to make sure this works.

**Comment by vchuravy** [comment]
Since #18927 is uncertain #16066 might be the more actionable approach.

**Comment by KristofferC** [comment]
@keno, anything left to do here?

**Comment by Keno** [comment]
There is a more generalized problem about communicating with LLVM about libcalls, but I think this particular issue is resolved. A new issue can be filed with a reproducer when this issue rears its head again.
