### ISSUE TITLE
system image build time regression (after new optimizer and iteration protocol)

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23006]
For me this takes about 3m10s on v0.6, and 5m30s on master. One theory is that this is due to more inlining and thus generating longer functions (perhaps in just a few pathological cases), but we don't really know yet.

**Comment by StefanKarpinski** [comment]
This took long enough that I thought it was hung, so yeah, this has definitely regressed. On the other hand, now that #265 is fixed, sysimg build time only really matters to people who build Julia themselves often, so I'm not sure how critical this is.

**Comment by timholy** [comment]
Inlining is a good theory, but:

`d6a0bbdb2dd9694f032bf04eb008756625d33e5c` (just before merging #22210): 3m17.835s
After the merger: 3m41.295s

**Comment by maleadt** [comment]
I'm currently measuring release sysimg build times on an old but idle system of mine, and it just got past df63db683237fdb90fc1f93136400cfa34d6bd33:

![alt text](http://i.imgur.com/Vb1d5sk.png )

**Comment by StefanKarpinski** [comment]
We should be tracking and charting this and other performance metrics automatically all the time.

**Comment by maleadt** [comment]
The script reached `v0.5.0`, with some clear regressions and improvements visible.

Is this a useful thing to have? If so, I can deploy this in a more persistent manner (ie. keeping track of `master`).

Also, I should have measured real+user+sys & rss+vsz instead of just wall seconds; would that be useful to regenerate the dataset for?

**Comment by djsegal** [comment]
Is there a public-facing dashboard for this kind of stuff?

**Comment by ViralBShah** [comment]
We have now added the new Package Manager and still have the old one. I assume the goal here is not to reduce sysimage build time as much as improve the compiler speed that everyone can benefit from. Do we need more specific issues instead?

**Comment by JeffBezanson** [comment]
This is a specific issue --- it's an example case where compiler performance regressed. In fact when the new iteration protocol and optimizer were merged, there was another significant regression in this case. So it's not just caused by adding more code to the system image.

**Comment by ViralBShah** [comment]
Ok, I'll see if I can quantify that for discussion here and update the title.

**Comment by KristofferC** [comment]
Can be closed?

**Comment by KristofferC** [comment]
I think it is pretty good now (the precompilation script takes a while but that is not really related to this issue).
