### ISSUE TITLE
\ for RowVector should take scalar right-hand sides

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#23028]
This seems inconsistent (I haven't tested it in 0.7 yet):

```julia
julia> a = [1,2]'
1×2 RowVector{Int64,Array{Int64,1}}:
 1  2

julia> b = a*[3,4]
11

julia> a \ b
ERROR: MethodError: no method matching /(::Int64, ::Array{Int64,1})
Closest candidates are:
  /(::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, ::Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at int.jl:38
  /(::Union{Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8}, ::BigInt) at gmp.jl:381
  /(::T<:Integer, ::T<:Integer) where T<:Integer at int.jl:36
  ...
Stacktrace:
 [1] \(::RowVector{Int64,Array{Int64,1}}, ::Int64) at ./operators.jl:457
```

**Comment by andyferris** [comment]
What is scalar divided by vector meant to do? `a \ b == (b / a)'` and I'm not sure what `b / a` is.

**Comment by dlfivefifty** [comment]
That's undefined but isn't pertinent. \ is least squares, so should return the vector `v` that minimizes `norm(a*v - b)`

**Comment by dlfivefifty** [comment]
That is, it should mimic this:
```julia
julia> a = [1 2]
1×2 Array{Int64,2}:
 1  2

julia> b = a*[3,4]
1-element Array{Int64,1}:
 11

julia> a \ b
2-element Array{Float64,1}:
 2.2
 4.4
```

**Comment by martinholters** [comment]
Then this probably should work, too:
```julia
julia> b / [3; 4]
ERROR: MethodError: no method matching /(::Int64, ::Array{Int64,1})
```
because this does:
```julia
julia> hcat(b) / [3; 4]
1×2 Array{Float64,2}:
 1.32  1.76
```
So add a `/(::Number, ::AbstractVector)` method that returns a `RowVector`? This could do it:
```julia
/(x::Number, v::AbstractVector) = x * v' / sum(abs2, v)
```
Opinions?

**Comment by andyferris** [comment]
We do have some distinction between scalars and 1-element arrays - we're not aiming to make every array-scalar op behave as if the scalar was a small array. 

I'm not sure which side of the line this one falls on, however. This could be convenient in some circumstances, I guess.

**Comment by martinholters** [comment]
There is an argument to be made that `a / b` should yield the same as `a * pinv(b)` (similar for `\` of course). Let's see what happens for row and column vectors (candidates and stack traces omitted for brevity):
```julia
julia> r=[1; 2]'
1×2 RowVector{Int64,Array{Int64,1}}:
 1  2

julia> c=[3; 4]
2-element Array{Int64,1}:
 3
 4

julia> (r*c)*pinv(c)
1×2 Array{Float64,2}:
 1.32  1.76

julia> (r*c)/c
ERROR: MethodError: no method matching /(::Int64, ::Array{Int64,1})

julia> pinv(r)*(r*c)
ERROR: MethodError: no method matching pinv(::RowVector{Int64,Array{Int64,1}})

julia> r\(r*c)
ERROR: MethodError: no method matching /(::Int64, ::Array{Int64,1})
```

As the major reason for adding `RowVector` was that `v1'*v2` would give a scalar, I see no harm in letting the inverse (well, more or less...) operations go back from scalar to (row) vector. Otherwise, we should probably drop the `pinv` method for vectors. Oh, and if we keep it, it might better return a `RowVector`, BTW.
