### ISSUE TITLE
Regression calling cfunction

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#23020]
```julia
using BenchmarkTools

foo(x) = x + 1
f() = cfunction(foo, Int, (Int,))

@btime f();
  815.538 ns (3 allocations: 96 bytes)

# version
# Julia Version 0.7.0-DEV.1159
# Commit 8d752a07f4* (2017-07-29 02:32 UTC)
# OS: Windows (x86_64-w64-mingw32)
```

Julia 0.6
```julia
using BenchmarkTools

foo(x) = x + 1
f() = cfunction(foo, Int, (Int,))

julia> @btime f();
  1.578 ns (0 allocations: 0 bytes)
```

**Comment by yuyichao** [comment]
Use `cfunction(foo, Int, Tuple{Int})` instead.

**Comment by tkelman** [comment]
should the `(Int,)` form be deprecated if it's a performance trap?

**Comment by yuyichao** [comment]
That's why I also added the `deprecation` label....

**Comment by musm** [comment]
@yuyichao  Is there  reference for the updated syntax ?

**Comment by yuyichao** [comment]
New tuple type syntax? https://github.com/JuliaLang/julia/pull/10380 ?

**Comment by musm** [comment]
Thanks. Does it not seem  little inconsistent that, e.g., `ccall` (and some other methods) takes a tuple of types but `cfunction` and `invoke` take a tuple type?

**Comment by tkelman** [comment]
It should probably eventually be deprecated in `ccall` too - we should make a decision on whether we're going to do that soon

**Comment by musm** [comment]
Of the top of my head `code_llvm`, `code_typed`, `code_warntype`, `ccall` . All use a tuple of types instead of a tuple type.

**Comment by yuyichao** [comment]
`ccall` is special since it's a syntax and not a function.
Other functions also doesn't matter since they are only for reflection.

**Comment by quinnj** [comment]
I'm not a big fan of the inconsistency here, the fact that we now have
`cfunction(foo, Cint, Tuple{Ptr{Void}})`
vs.
`ccall((:foo, lib), Void, (Ptr{Void},), ptr)`
As a user/library author, how am I supposed to remember/guess whether you want a `Tuple{...}` or a `(...)`. Let's pick one and use it everywhere, `ccall`, reflection, etc.

**Comment by yuyichao** [comment]
Tuple of types is only kept for convinience. If people don't like that, we can certainly just drop all of them.

**Comment by musm** [comment]
@quinnj  I thought so too initially, but I'm pretty satisfied with `@yuyichao` comment above.
- `invoke`, `cfunction` operatore on julia function and thus the tuple type. (consistent)
- `ccall` is syntax
- reflection methods doesn't matter
