### ISSUE TITLE
where: is it counter-intuitive result at Array?

### ISSUE THREAD

**Issue by songroom2016** [JuliaLang/julia#23038]
in julia 0.6, 
arr1  = Array{Array{T,1} where T,1}() ;
arr2  = Array{T where T,1}() ;

i think it is so, arr1 looks like  an Array{Array{Any,1},1} ; arr2 looks like an Array{Any,1} . but i get this:

arr1==arr2 

but it is counter-intuitive result for me,  is it a  intentional arrangement at Array ?

**Comment by KristofferC** [comment]
> but it is counter-intuitive result for me

The content is the same (empty) which is what `==` checks.
