### ISSUE TITLE
0.7: Meaningful deprecation error for `f(::)`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#23044]
This change gives a confusing error message in 0.7:
```julia
julia> f(::) = 1
ERROR: syntax: unexpected ")"

julia> versioninfo()
Julia Version 0.7.0-DEV.1164
Commit 1ce3c8e60e (2017-07-29 16:50 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
```

PS What's the recommended alternative? Giving it a dummy name `f(_) = 1` or typing with `Any`: `f(::Any) = 1`?

**Comment by KristofferC** [comment]
Both alternatives seem fine to me. Why is the error message confusing?

**Comment by dlfivefifty** [comment]
it required me to guess why that line was suddenly throwing an error message. Though I suppose it didn't take long ...

**Comment by KristofferC** [comment]
For reference, it throws because `::` can no longer be a value.

On 0.6:
```
julia> x(::) = (::):(::):(::)
x (generic function with 1 method)

julia> x(3)
3:3:3
```

**Comment by dlfivefifty** [comment]
Ah ok, I withdraw the issue then since I wasn't using it correctly in 0.6 (I was under the impression that this was shorthand for `::Any`)
