### ISSUE TITLE
Cannot infer a method that calls an inferrable method

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#23063]
```julia
julia> using AbstractFFTs, FFTW, Base.Test

julia> using AbstractFFTs: complexfloat

julia> x = randn(10, 12);

julia> @inferred brfft(x, 18);
ERROR: return type Array{Float64,2} does not match inferred return type Any
Stacktrace:
 [1] error(::String) at ./error.jl:28

julia> @inferred brfft(complexfloat(x), 18);
```
The definition of the method that fails `@inferred` is
```julia
brfft(x::AbstractArray{<:Real}, d::Integer, region=1:ndims(x)) =
    brfft(complexfloat(x), d, region)
```
These functions used to be in Base, as did the `@inferred` tests, so at some point something in Base changed that broke this. This works fine on 0.6.

**Comment by vtjnash** [comment]
This isn't expected to work (specifically, we would rather use this known inference result, even though it's strictly tighter than we would have gotten if we tried to re-infer it, rather than spend time checking if we should worsen the result).

**Comment by JeffBezanson** [comment]
I just tried this on master and it seems to work.
