### ISSUE TITLE
reduce and reducedim have inconsistent signature

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#23064]
Currently (in v0.7) `reduce`'s signature is `reduce(op, itr)` and `reduce(op, v0, itr)`, whereas `reducedim`'s signature is `reducedim(f, A, region[, v0])`.  It was surprising to me that the order of `v0` is inconsistent between the two functions.

It is understandable that `v0` comes earlier than `itr` in `reduce(op, v0, itr)`, because `v0` is the left argument of the binary operator `op` and `itr` supplies right arguments.  To be consistent, wouldn't it be better to separate the definition `reducedim(f, A, region[, v0])` into two: `reducedim(f, A, region)` and `reducedim(f, v0, A, region)`?  Or, is there any particular reason for this inconsistency?

**Comment by StefanKarpinski** [comment]
They should definitely be made to match. @simonbyrne has an idea of introducing a `Slices` type that might help refactor this.

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/julia/pull/27711 will fix this. Cc: @andyferris

**Comment by nalimilan** [comment]
Actually it's already fixed since `reducedim` has been merged with `reduce`.
