### ISSUE TITLE
Syntax error message on parametric macro

### ISSUE THREAD

**Issue by eveydee** [JuliaLang/julia#23069]
No comment on what I was trying to do, but this error message is confusing, as it suggests you to write exactly what you already wrote, even though it is illegal syntax:
```julia
julia> dump(:(@(MyMacro{T}) expr))
ERROR: syntax: invalid macro use "@(MyMacro{T})"
```

**Comment by martinholters** [comment]
It is not saying `invalid macro, use "@(MyMacro{T})"`, but that difference is pretty subtle...

**Comment by eveydee** [comment]
Panda: eats, shoots, and leaves ... duh!

At first I wrote (without the parentheses):
```julia
julia> dump(:(@MyMacro{T} expr))
ERROR: syntax: invalid macro use "@(MyMacro{T})"
```
and so I naively thought the error message told me to add parentheses around it.  I guess if I'm the only one who gets confused by this, it's alright, but maybe a near-synonym of "use" could be used in this context like `invalid macro call` or `invalid macro name`?

**Comment by JeffBezanson** [comment]
Yes we can change it to `invalid macro call`.

**Comment by KristofferC** [comment]
`invalid macro, call ...` can we have something that does not end with an imperative?

**Comment by eveydee** [comment]
```julia
julia> @Jeff{Bezanson}
ERROR: syntax: invalid macro call "@Jeff{Bezanson}"
```
I agree. Is `invalid macro name`, `invalid macro statement`, or `invalid macro usage` better?

**Comment by KristofferC** [comment]
`invalid macro usage` seems good to me. I'm also happy with deferring to calling Jeff but then his phone number should be in there too.

**Comment by JeffBezanson** [comment]
+1 for `macro usage`, -1 for including my phone number :)
