### ISSUE TITLE
Printing of ranges: number of omitted elements 

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#23071]
Since some time (say recent master) I get a test error because locally the number of print elements in a range differs. This could also be a fault of my configuration if this is locally configurable, but I do not see how and perhaps the test should not fail regardless.

```
Error in testset ranges:
Test Failed
  Expression: replstrmime(LinSpace{Float64}(0, 100, 10000)) == "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,…,99.95,99.96,99.97,99.98,99.99,100.0"
   Evaluated: "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,0.050005,0.060006,0.070007,0.080008,0.090009,…,99.86,99.87,99.88,99.89,99.9,99.91,99.92,99.93,99.94,99.95,99.96,99.97,99.98,99.99,100.0" == "10000-element LinSpace{Float64}:\n 0.0,0.010001,0.020002,0.030003,0.040004,…,99.95,99.96,99.97,99.98,99.99,100.0"
ERROR: LoadError: Test run finished with errors
```

```
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu) [PRETTY_NAME="Debian GNU/Linux 8 (jessie)]
  CPU: Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by nalimilan** [comment]
Maybe related to @rfourquet's recent changes?

**Comment by rfourquet** [comment]
@mschauer would you mind trying replacing the definition of `replstrmime` in test/ranges.jl by `replstrmime(x) = sprint((io,x) -> show(IOContext(io, limit = true, displaysize = (80, 80)), MIME("text/plain"), x), x)` and tell if this solve the issue?

**Comment by mschauer** [comment]
Strange, the change works for ranges but does not work for test/show.jl which also has a 
```julia
replstr(x) = sprint((io,x) -> show(IOContext(io, :limit => true), MIME("text/plain"), x), x)
```

Edit: 
```diff
--- a/test/show.jl
+++ b/test/show.jl
@@ -3,7 +3,7 @@
 # For curmod_*
 include("testenv.jl")
 
-replstr(x) = sprint((io,x) -> show(IOContext(io, :limit => true), MIME("text/plain"), x), x)
+replstr(x) = sprint((io,x) -> show(IOContext(io, limit=true, displaysize=(24, 80)), MIME("text/plain"), x), x)
```
does it!

**Comment by rfourquet** [comment]
OK thanks, so I set also `(24, 80)` for `replstrmime` (actually, `displaysize()` which hard-codes those values) in #23113.

**Comment by tkelman** [comment]
Does this only fail when run in a narrow terminal or something like that?

**Comment by mschauer** [comment]
It always fails. I think it may pass if run in a terminal exactly of size (24, 80), but I'd have to try.
