### ISSUE TITLE
mark `start_task` with ".cfi_undefined rip"

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#23074]
Annotate `start_task` with `asm(".cfi_undefined rip");`, just like https://github.com/scylladb/seastar/commit/1fa13238fe9c907a27bd7fdea814081b2f6e386c

**Comment by maleadt** [comment]
So maybe that's why #14727 still had some unannotated frames.

**Comment by shivakrishna9** [comment]
@vtjnash I will take this up. Need more info on where to add annotations.

**Comment by yuyichao** [comment]
We set the RIP to 0 so it shouldn't point to garbage at least...

**Comment by vtjnash** [comment]
I think it's just the `start_task` function that needs annotation, and testing that `backtrace()[end] != C_NULL` (only seems to be an issue on Linux).
