### ISSUE TITLE
min, max, minmax should use isless, not <

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23094]
See https://discourse.julialang.org/t/max-x-t-y-t-and-min-must-be-commutative/5165.

**Comment by StefanKarpinski** [comment]
Very slightly technically breaking.

**Comment by KlausC** [comment]
I saw the `findmin` and `findmax` are implemented using `a1 < m || m!=m` , which is targets the Float64 idiosyncrasies. In line with the proposed changes in `min` and `max`, the `<` should be replaced by `isless` for non-numeric types. Distinction by `eltype(itr)` required?
