### ISSUE TITLE
@async fetch to the same future concurrently make program stop. 

### ISSUE THREAD

**Issue by usefulhyun** [JuliaLang/julia#23109]
```
addprocs()
future = @spawn rand(1,1)

@sync begin
        @async fetch(future)
        @async fetch(future)
end
```
above program does not terminate because second fetch gets stuck.
and the below code works.
I think the reason is a change that the first call of fetch function makes ( it fetches data and then saves it on future variable for reuse ).
```
addprocs(1)
future = @spawn rand(1,1)
fetch(future)
fetch(future)
```

This problem causes more big issues my big parallel program uses futures as channels, so many processes, or actors, sometimes access the same future at the same time, then my program gets stuck. So it is a big problem for my dynamic parallel runtime system.

Does Anyone have a solution for this problem?

**Comment by StefanKarpinski** [comment]
Can confirm, this does seem to be a deadlock bug.

**Comment by amitmurthy** [comment]
A workaround till this is fixed and backported would be to fetch from the remote only once and put in a local Channel. You can have any number of waiters on the local channel.

```
@sync begin
        c = Channel(1)
        @async put!(c, fetch(future))
        @async fetch(c)
        @async fetch(c)
end
```
