### ISSUE TITLE
Odd behavior working with multiple files

### ISSUE THREAD

**Issue by cstepper** [JuliaLang/julia#23102]
I have a directory where I keep two *.jl files, say “core.jl” and “scripts.jl” One has most of the core analytical code, the other has some very project specific scripts. At the top of scripts.jl, I have:

```
using DataFrames, StatsBase, Distributions, MyModule
```
where MyModule is in core.jl. If I run scripts.jl without running core.jl first, I get:

```
LoadError: ArgumentError: Module MyModule not found in current path.
Run `Pkg.add("MyModule")` to install the MyModule package.
while loading C:\SummerProject17\scripts.jl, in expression starting on line 11
in require at base\loading.jl:398
in _require at base\loading.jl:428
```

I tried putting the following code at the top of scripts.jl (path edited for brevity):

```
if length(findin(pwd(),LOAD_PATH)) == 0
  push!(LOAD_PATH,pwd())
end
```
This had no effect.

As was pointed out on the discourse board by @KristofferC, I can use include("core.jl") but then export doesn't work, say on myMethod, and I get the following error:

```
LoadError: UndefVarError: myMethod not defined
while loading C:\SummerProject17\scripts.jl, in expression starting on line 5
```

If I put in both `include("core.jl")` AND `using MyModule`, I get the following warnings each time I re-run (not the first run):

```
WARNING: replacing module MyModule
WARNING: using MyModule.myMethod in module Main conflicts with an existing identifier.
```

But it does work. In summary, having both `include("core.jl")` and `using MyModule` works but with warnings, 'include' works but invalidates export, and `use` alone doesn't work. Happy to clarify or edit the above if needed.

**Comment by yuyichao** [comment]
Please keep using the forum for usage questions and discussions.

**Comment by cstepper** [comment]
@yuyichao This wasn't a question a report on odd behavior.

**Comment by KristofferC** [comment]
It is not odd behavior, see e.g. https://docs.julialang.org/en/stable/manual/modules/#modules-1. If you are new to the language it might be worth floating your ideas in discourse before opening an issue since issues are mostly about tracking bugs.

**Comment by cstepper** [comment]
@KristofferC  I did and I'm thankful for, and followed the responses. I''m also appreciative of the link you sent. 

That said, I don't see anything referencing the warning I was getting on recompilation in the link you sent.

**Comment by yuyichao** [comment]
And again, please continue the discussion back on discourse.
