### ISSUE TITLE
arpack-ng-3.3.0.tar.gz checksum fails in jula0.6 source installation:

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#23101]
ERROR: sha512 checksum failure on arpack-ng-3.3.0.tar.gz, should be:
      8d0e526831d62200af9d939e77e41548875caacdf39543c3f33a00321bb18fc0
      4ffa625d9c4103f84c1f6a03a3c362dc1df8571db9a525d46487e5d1ae682474

But `sha512sum deps/srccache/arpack-ng-3.3.0.tar.gz | awk '{ print $1; }'` results in:
      deb33b87e1d55ec76387d3a860debf6458d794fc8434023c2b4721f8c449f5bf
      9a68c76ded5322ee94a88f9c571611b5f2ae71ca803cef7e84d59798f58c8873

**Comment by ViralBShah** [comment]
The 3.5.0 release says it fixes shared libraries. May be a good reason to update, but will need some build system work. May be best to just fix this for now, and bump releases whenever arpack is moved out of base.

**Comment by tkelman** [comment]
where did `deps/srccache/arpack-ng-3.3.0.tar.gz` come from? sounds like an incomplete download, delete it and try again.

arpack needs to be taken out of base.

**Comment by montyvesselinov** [comment]
I downloaded it from the web; i will try with make -C deps getall

-monty

**Comment by tkelman** [comment]
closing since you aren't using the tarball that checksum was calculated for
