### ISSUE TITLE
Make `find`'s default predicate be `identity`

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#23120]
As discussed in #23005, the zeroness predicate is not uniquely defined. It seems odd to pick one for `find`. However, one really useful property of this is that it returns the `true` indices for boolean arrays, so you can do things like `find(x .== 1)`, which we should preserve. I thus propose to make the default predicate be `identity` to retain the useful behavior for boolean arrays, but force the user to choose their predicate for numeric arrays.

**Comment by nalimilan** [comment]
+1

If we do that, then the [Search & Find Julep](https://github.com/JuliaLang/Juleps/blob/master/Find.md) should be updated to say "true values" rather than "non zeros" in a few places.
