### ISSUE TITLE
Running julia with compile=no and precompiled=no makes REPL unusable

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#23125]
This is probably a won't fix, so feel free to close this, but the following makes the REPL unusable 
`julia --compile=no --precompiled=no`

**Comment by musm** [comment]
Yes, and if you try to type anything in the repl it keeps spitting the messages and does not stop.

**Comment by KristofferC** [comment]
Works fine for me now. Please comment if this is reproducible with 1.3.
