### ISSUE TITLE
Documentation: Misleading statement about passing behavior of immutables

### ISSUE THREAD

**Issue by jrklasen** [JuliaLang/julia#23127]
The following statement seems wrong ('Documentation / Type / Mutable Composite Types'):

> * An object with an immutable type is passed around (both in assignment statements and in function calls) by copying, whereas a mutable type is passed around by reference.

This reads to me as if values are copied, which seems not to be the case. See 'Documentation / Functions / Argument Passing Behavior':

> Julia function arguments follow a convention sometimes called "pass-by-sharing", which means that values are not copied when they are passed to functions. Function arguments themselves act as new variable bindings (new locations that can refer to values), but the values they refer to are identical to the passed values.

Edit: removed misleading example

**Comment by yuyichao** [comment]
The code is invalid. There's no difference between function call and assignment.

The doc should say

> An object with an immutable type is allowed to be passed around (...) by copying.

**Comment by jrklasen** [comment]
the documentation contains a additional paragraph, depending on this statement, which requires a bigger change

**Comment by JeffBezanson** [comment]
Agreed. It's weird to say "immutable values are passed by copying"; the only thing that would make sense is "you can't tell whether immutable values are passed by copying" or, equivalently, say nothing :)
