### ISSUE TITLE
findnz/nnz mismatch: findnz returns actual, not structural zeros

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23121]
```jl
julia> S = sparse([1], [1], [0])
1×1 SparseMatrixCSC{Int64,Int64} with 1 stored entry:
  [1, 1]  =  0

julia> nnz(S)
1

julia> findnz(S)
(Int64[], Int64[], Int64[])

julia> findn(S)
(Int64[], Int64[])
```

Given their similar naming, it seems like these should match. Given the decision in https://github.com/JuliaLang/julia/issues/23005 that we're replacing `countnz(S)` with `count(!iszero, S)` it might make sense to find actual non-zeros with a more generic function and a `!iszero` predicate.

**Comment by KristofferC** [comment]
#24724
