### ISSUE TITLE
Division of finite values by infinite complex values should always return zero

### ISSUE THREAD

**Issue by LordZorgoth** [JuliaLang/julia#23134]
Since [Issue 9790](https://github.com/JuliaLang/julia/issues/9790) was closed and it was mentioned that corner cases should be separate issues, I am reposting one particular element of that issue where Julia is currently both wrong and, according to a comment in the thread, inconsistent with C++.

Division of any finite value by any complex infinite value should return 0. Currently, we have the following behavior in Julia 0.6.0:

    julia> 1/(Inf+im*Inf)
    NaN + NaN*im
    
    julia> 1/(Inf+im*NaN)
    NaN + NaN*im
    
    julia> 1/(Inf+0*im)
    0.0 - 0.0im

The third case is correct, but both of the other two cases are mathematically wrong. The first case is wrong. The second case is also wrong because if NaN is replaced by some real value, or by Inf, or by -Inf, it is clear that the result should be zero in each case. Further, it is inconsistent with the behavior of C++.

**Comment by LordZorgoth** [comment]
The

**Comment by pabloferz** [comment]
It was just recently discussed that we actually follow the ISO standard (including the cases you posted above), see this https://github.com/JuliaLang/julia/issues/22983#issuecomment-318675138. It is actually the C and C++ compilers (at least gcc and g++) that do not follow it.

**Comment by martinholters** [comment]
Wasn't that about division by (complex) zero?

**Comment by LordZorgoth** [comment]
The discussion in that thread, as far as I can tell, was indeed about division by zero, not infinity. I can't access the complex division standard because of the paywall, so I don't know what, if anything, it says about division by infinity. It would be quite odd if it was expected to return NaN, though I suppose the reasoning would be to avoid an operation to check for infinity in the denominator when performing complex division.

**Comment by LordZorgoth** [comment]
Oh, I see now, The specific algorithm for complex division is defined, and it doesn't cover the special case where the denominator is Infinity, which would result in NaNs being returned.

**Comment by pabloferz** [comment]
> Wasn't that about division by (complex) zero?

Sorry, yes, you're right.

> I can't access the complex division standard because of the paywall, so I don't know what, if anything, it says about division by infinity.

http://standards.iso.org/ittf/PubliclyAvailableStandards/. Anyway, the relevant information about complex division is already in the other issue I linked.

> The specific algorithm for complex division is defined, and it doesn't cover the special case where the denominator is infinite, which would result in NaNs being returned.

It defines as a fallback `(x + y*im) / (z + w*im)` as `( (x*z + y*w) + (y*z + z*w)*im ) / (z*z + w*w)` which will give the results on the OP if I'm not mistaken.

**Comment by pabloferz** [comment]
Though, I'd like to point that having `1/(Inf+im*Inf) == 0.0` seems sensible. As for `1/(Inf+im*NaN) == 0.0` I'm not so sure.

**Comment by LordZorgoth** [comment]
From a mathematical perspective, you definitely do want 1/(Inf+im*NaN) to be zero. Inf+im*NaN is still an infinite number. You can't add an imaginary anything to real infinity and get something that isn't infinity. An example of where Inf+im*NaN comes from is (1+0*im)/0. That's definitely infinite. The reason it has an imaginary part of NaN is simple because we don't know the relative sizes of the zeroes if we are taking some kind of limit.

Further, from a computational perspective, if you are already checking for 1/(Inf+im*Inf) to make it return zero, it is actually more efficient to make 1/(Inf+im*NaN) return zero, as you only have to find one infinity, not two.

**Comment by simonbyrne** [comment]
For the record, both Octave and R give the equivalent of `1/Complex(Inf, Inf) == 1/Complex(Inf, NaN) == 0`. It would else help deal with some edge cases of #29840.

**Comment by stevengj** [comment]
Python gives:
```py
>>> 1/complex(inf,inf)
(nan+nanj)
```
ISO/IEC 10967-3:2006(E) seems to be silent on this issue: section 5.2.6.3 (*Complex division*) only defines the result for inputs in `c(F)`, which is defined as complex numbers over "non-special" floating-point values (i.e. not including NaN, ±Inf, and -0), unless I am missing some discussion elsewhere in the standard.

**Comment by stevengj** [comment]
See also the discussion in #9790.

**Comment by stevengj** [comment]
gcc 6.3 on GNU/Linux and clang on MacOS both give `0-0i` from `1 / (INFINITY + INFINITY*I)`:
```c
#include <complex.h>
#include <stdio.h>
#include <math.h>
int main(void) {
     double complex z = 1 / (INFINITY + INFINITY*I);
     printf("%g%+gi\n", creal(z), cimag(z));
     return 0;
}
```

**Comment by stevengj** [comment]
Overall, I can't find any reason not to give something `== 0` from division of  finite value by `±Inf ± Inf*im`.

**Comment by giordano** [comment]
The code above with `icc`:
```sh
$ icc -std=c99 complex.c && ./a.out 
complex.c(5): warning #1189: complex floating-point operation result is out of range
       double complex z = 1 / (INFINITY + INFINITY*I);
                                                  ^

-nan-nani
```

and this C++ code
```cpp
#include <complex>
#include <iostream>

int main(void) {
  std::cout << 1.0 / std::complex<double>(INFINITY, INFINITY) << std::endl;
  return 0;
}
```
with `icc` gives:
```sh
$ icc complex.cpp && ./a.out 
(-nan,-nan)
```

In Mathematica, dividing 1 by [`ComplexInfinity`](https://reference.wolfram.com/language/ref/ComplexInfinity.html) gives 0:
```
In[1]:= 1 / ComplexInfinity

Out[1]= 0
```

**Comment by giordano** [comment]
Note also that currently in Julia there is a mismatch between `Float64` and `BigFloat`:
```julia
julia> 1 / complex(BigFloat(Inf))
NaN - 0.0im

julia> 1 / complex(BigFloat(Inf), BigFloat(Inf))
NaN + NaN*im

julia> 1 / complex(Inf)
0.0 - 0.0im

julia> 1 / complex(Inf, Inf)
NaN + NaN*im
```

**Comment by giordano** [comment]
Folks, sorry for the spam, didn't plan to write more than one message at the beginning (and more than two after the second), but the topic is interesting and I went on investigating the issue.

---

So, the problem with division by complex infinity is ultimately related to `inv(::Complex)`, as this is the function that it's called.  In particular, for `Float64` input the responsible of `inv(complex(Inf, Inf))` giving `NaN` is this line (`c` and `d` are the real and the imaginary part of the input):
https://github.com/JuliaLang/julia/blob/b5a4601bbe8a6f1b8ce8f4e307543850c08adb8e/base/complex.jl#L444

What about simply doing
```julia
(isinf(c) || isinf(d)) && return zero(w)
```
at the beginning of the function?

**Comment by giordano** [comment]
I've opened #32050 to fix the issue (at least for `ComplexF64`, will have to look into `BigFloat`).
