### ISSUE TITLE
sort and friends allow passing by= and order= together, but ignore the latter

### ISSUE THREAD

**Issue by tkluck** [JuliaLang/julia#23131]
As documented, `sort` allows passing both `by=` and `lt=`, and when both are passed, the result of `by=` is passed to `lt`. Example:
```julia
julia> sort([(1,3),(2,2),(3,1)], by=i->i[2], lt=(a,b)->isless(a,b))
3-element Array{Tuple{Int64,Int64},1}:
 (3, 1)
 (2, 2)
 (1, 3)
julia> sort([(1,3),(2,2),(3,1)], by=i->i[2], lt=(a,b)->isless(b,a))
3-element Array{Tuple{Int64,Int64},1}:
 (1, 3)
 (2, 2)
 (3, 1)
```

It is also possible to pass both `by=` and `order=`. However, when doing that,  `order=` is ignored:
```julia
julia> sort([(1,3),(2,2),(3,1)], by=i->i[2], order=Base.Order.Forward)
3-element Array{Tuple{Int64,Int64},1}:
 (3, 1)
 (2, 2)
 (1, 3)

julia> sort([(1,3),(2,2),(3,1)], by=i->i[2], order=Base.Order.Reverse)
3-element Array{Tuple{Int64,Int64},1}:
 (3, 1)
 (2, 2)
 (1, 3)
```

Is this intentional? It is kind of surprising to me.

From reading the `Base.Order` code, it seems the `order=` parameter is intended to encompass all functionality of `by=`, `rev=` and `lt=`, which may explain why its behaviour in combination with those hasn't received much attention. Furthermore, while reasonable behaviour can be defined for the combinations involving `by=`, `rev=`, `order=`, the same can't be said when `lt=` enters the mix.

In my opinion, `lt=` and `order=` are (rightly) mutually exclusive, but `order=` should interact with the others in the same way `lt=` does.

If others share my opinion, I can provide a pull request. Thanks for reading!

**Comment by nalimilan** [comment]
Right, thanks for reporting it. `order` is an internal implementation detail which shouldn't have been documented. See https://github.com/JuliaLang/julia/pull/22388.

**Comment by kmsquire** [comment]
> `order` is an internal implementation detail which shouldn't have been documented. See #22388.

At this point, it's probably an implementation detail (and could/should be removed from the documentation), but I believe when it was first introduced, it was meant to be used (meaning that it was documented purposefully).
