### ISSUE TITLE
The same code sometimes gets stuck.

### ISSUE THREAD

**Issue by usefulhyun** [JuliaLang/julia#23140]
```
addprocs(1)

@everywhere function foo(future)
	v = fetch(future)
	r = rand()
	v = v + r
	return v
end

SIZE = 10

mat = [ zeros(1000,1000) for i=1:SIZE]
vec = Vector()
@sync for i=1:SIZE
	push!(vec, @spawnat 2 foo(mat[i]))
	@async begin
		result = fetch(vec[i])
		println(i, " : ", result[1,1])
	end
end
``` 
When you run the code, it sometimes will complete well, but it often block.
Does anybody know the actual reason or is it a bug?

**Comment by iblis17** [comment]
The `fetch` call in function `foo` is quite confused, since you do `@spawnat 2 foo(mat[i])`.
The parameter `mat[i]` is not a future.

**Comment by amitmurthy** [comment]
1. This appears to be an issue on 0.6, works on master.
2. The issue appears to be in the task `@sync` / `@async` code as all 10 `println` statements are printed.
3. Issue is related to size of `mat` - works fine for smaller sizes of `mat` 

Ctrl-C results in 
```
^Cfatal: error thrown and no exception handler available.
InterruptException()
jl_run_once at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/jl_uv.c:132
process_events at ./libuv.jl:82 [inlined]
wait at ./event.jl:216
task_done_hook at ./task.jl:256
jlcall_task_done_hook_21956 at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia.h:1424 [inlined]
finish_task at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:232
start_task at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/task.c:275
```

@vtjnash do you recall any updates to the tasking / libuv code recently that may have addressed this?

**Comment by KristofferC** [comment]
> This appears to be an issue on 0.6, works on master.

Ok.
