### ISSUE TITLE
Request => Update readthedocs for the latest stable julia 0.6.0

### ISSUE THREAD

**Issue by abhi18av** [JuliaLang/julia#23153]
Hi Julia team

I just wanted to bring to your notice that the docs haven't been updated for the latest stable.

https://readthedocs.org/projects/julia/downloads/

Also, the old pop-up regarding the `download as PDF/HTML` seems to be missing.

I think that people do prefer the unplugged PDF for a good read, it'd be great if this would be updated 👍

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/22704

**Comment by abhi18av** [comment]
whoops :)
