### ISSUE TITLE
remove vectorized dates methods

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23167]
https://github.com/JuliaLang/julia/blob/0f4229d2e744375255fa1b27cb180f678ebf3e76/base/dates/io.jl#L561-L580

These are actually fairly convenient since they construct format objects a single time and then call the vectorized implementation with the format object. Still, it would be nice to get rid of all vectorized methods.

**Comment by nalimilan** [comment]
Maybe we could turn these into `broadcast(::typeof(DateTime), ...)` methods? That way the simple case would still be efficient and only build the `DateFormat` object once?

**Comment by quinnj** [comment]
Woah, those are pretty neat inline code snippets in the OP.

I actually don't think it should be an issue to remove these anymore, with the introduction of the `dateformat"yyyy-mm-dd"` DateFormat string macro, which ensures the DateFormat object is created only once, a la Regex.

**Comment by nalimilan** [comment]
We can remove these methods, and add the `broadcast` specializations later if they turn out being useful.

**Comment by Sacha0** [comment]
Addressed by #23207. Best!
