### ISSUE TITLE
periodic crash in distributed tests on 32-bit AV

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23177]
E.g. here:

https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.17526/job/dsgt9h9yo0qb032t
https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.17530/job/vm0e8b0p4njc3771

**Comment by amitmurthy** [comment]
This is a segfault that I have seen on Linux and OSX too. Happens at different points in the test suite. Probably a symptom of a deeper underlying cause.

**Comment by amitmurthy** [comment]
Has anyone successfully run valgrind with the master branch on OSX?

**Comment by amitmurthy** [comment]
Managed to run valgrind on anubis - output here -
 https://gist.github.com/amitmurthy/6acdb1421ff67322861d239036820711

Can't detect any obvious issues. Can others have a look?

**Comment by KristofferC** [comment]
Seems to not happen anymore.
