### ISSUE TITLE
segfault on `@eval import $x` with `x = :.`

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/julia#23173]
```
signal (11): Segmentation fault
while loading /home/zac/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/main.jl, in expression starting on line 27
eval_import_path_ at /home/zac/github/julia-master/src/toplevel.c:361
eval_import_path at /home/zac/github/julia-master/src/toplevel.c:430 [inlined]
jl_toplevel_eval_flex at /home/zac/github/julia-master/src/toplevel.c:510
jl_toplevel_eval_in at /home/zac/github/julia-master/src/builtins.c:496
macro expansion at /home/zac/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:34 [inlined]
#3 at ./event.jl:73
unknown function (ip: 0x7f59c401193f)
jl_call_fptr_internal at /home/zac/github/julia-master/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/zac/github/julia-master/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/zac/github/julia-master/src/gf.c:1933
jl_apply at /home/zac/github/julia-master/src/julia.h:1424 [inlined]
start_task at /home/zac/github/julia-master/src/task.c:267
unknown function (ip: 0xffffffffffffffff)
Allocations: 11642048 (Pool: 11639283; Big: 2765); GC: 26
```
The relevant code run is `@eval import $modname` at `languageserverinstance.jl`, line 34
with `modname = :.`

I can't replicate this in the REPL but has been happening with the [julia-vscode](https://github.com/JuliaEditorSupport/julia-vscode) plugin. 

We were accidentally importing the first argument of any import statement which resulted in `@eval import $(:.)` when relative module paths were used in code.

To replicate (though it doesn't occur 100% of time) you: 
1. need [vscode](url) and the plugin (install from [vsix](https://github.com/JuliaEditorSupport/julia-vscode/releases/download/v0.7.0-rc.5/language-julia-0.7.0-rc.5.vsix))
2. when installed open `~/.vscode/extensions/julialang.language-julia-0.7.0-rc.5/scripts/languageserver/packages/CSTParser`
3. open `src/CSTParser.jl` and when it is finished parsing/loading up hover over something.
4. error logs can be found from the `View: Toggle Output` command

**Comment by tkoolen** [comment]
I can reproduce this in the REPL, both on 0.6 and on (fairly recent) master:
```
ulia Version 0.7.0-DEV.1165
Commit 1a43098cf7 (2017-07-31 03:33 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
Environment:
```
