### ISSUE TITLE
[windows, 0.6] isdir only works on absolute paths -> walkdir doesn't work correctly

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#23186]
when calling `isdir` on relative paths it'll always return false on windows (at least for me)

thus the separation into files and directories for `walkdir` doesn't work (nothing is a dir, though nothing is a file either)

workaround: instead of writing `walkdir(path)` write `walkdir(abspath(path))`

**Comment by simonbyrne** [comment]
libuv bug?

**Comment by simonbyrne** [comment]
@rapus95 can you try
```
stat(dirname)
stat(abspath(dirname))
```
where `dirname` is a relative path, and paste the results?

**Comment by musm** [comment]
```julia
julia> stat(d)
StatStruct(mode=0o040444, size=0)

julia> abspath(d)
"C:\\Users\\Mus\\My Documents"

julia> abspath(d)|>stat
StatStruct(mode=0o040444, size=0)

julia> d
"My Documents"
```

**Comment by rapus95** [comment]
Well sadly or luckily i haven't been able to reproduce it :/ (Circumstances when it occured was that there have been 20Gb of small files across several thousand directories, so maybe it was a system bug?!)

Thanks for investigation and extremely fast response though!

**Comment by simonbyrne** [comment]
No problem: having looked at the libuv code, there are a few kludges to deal with Windows file systems, so you may have hit some edge case.

If it does happen again, please record the above output, and the type of filesystem on the partition.
