### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on closing a pipe

### ISSUE THREAD

**Issue by fjarri** [JuliaLang/julia#23198]
Platform:

```
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

Code:

```
STDOUT_OLD = STDOUT
rd, wr = redirect_stdout()

println("!!!")

redirect_stdout(STDOUT_OLD)
close(wr)
output = readstring(rd)
close(rd)

println("Captured: $output")
```

Result: the execution hangs; if ctrl+C is pressed, the following output appears:

```
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64f75a6a -- jl_enter_handler at /home
/Administrator/buildbot/slave/package_win6_2-x64/build/src/home/Administrator/bu
ildbot/slave/package_win6_2-x64/build/src\rtutils.c:213
while loading D:\Dropbox\Jute\test\t.jl, in expression starting on line 7
```

The same code works as expected (captures and later displays the captured output) on Linux and OSX.

**Comment by tkelman** [comment]
Does this work on nightly?

**Comment by fjarri** [comment]
I only have access to Windows on Appveyor right now, but my package's tests that use this functionality [seem to pass](https://ci.appveyor.com/project/fjarri/jute-jl/build/1.0.25).

**Comment by vtjnash** [comment]
https://docs.julialang.org/en/latest/manual/running-external-programs/#Avoiding-Deadlock-in-Pipelines-1

**Comment by fjarri** [comment]
Do you mind showing what the snippet from the top post should look like? I am already using `readstring()` as the quoted section of the docs (the `stable` part, since we're talking about 0.6) recommends.

**Comment by vtjnash** [comment]
```julia
STDOUT_OLD = STDOUT
rd, wr = redirect_stdout()
reader = @async readstring(rd)

println("!!!")

redirect_stdout(STDOUT_OLD)
close(wr)
output = wait(reader)

println("Captured: $output")
```

(although, if you can do `io = IOBuffer(); println(io, "!!!"); output = String(take!(io))`, it'll be much more efficient 😛)

**Comment by fjarri** [comment]
Thanks, I thought just `readstring()` would suffice, creating a task just to read from a pipe seemed a bit of an overkill.

> (although, if you can do io = IOBuffer(); println(io, "!!!"); output = String(take!(io)), it'll be much more efficient 😛)

Unfortunately it is not an option, since I need to capture the output of arbitrary code.
