### ISSUE TITLE
Specify repository for dependencies in REQUIRE file

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#23217]
I looked at the official [documentaiton][1] and found no way to specify the git-repo for dependencies to unregistered packages. Is this just not possible? Seems somewhat crucial to specify repositories.

  [1]: https://docs.julialang.org/en/stable/manual/packages/#Requirements-Specification-1

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7737
