### ISSUE TITLE
file test failure on travis macOS

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#23215]
I have seen this several times, on different PR's (eg.  #23154, and twice on  #22311) now so filing an issue. The same happens on some recent builds on the `master` branch as well (for instance https://travis-ci.org/JuliaLang/julia/jobs/263269413)
Two logs here:
https://gist.github.com/fredrikekre/cb3df94976f47a0ab3075ccd121b244e
https://gist.github.com/fredrikekre/be6c80360eab0cfc50e4541af4b8bdaf

Here is the output:
```
From worker 7:	Assertion failed: (args[0]), function jl_uv_call_close_callback, file /Users/travis/build/JuliaLang/julia/src/jl_uv.c, line 73.
From worker 7:	
From worker 7:	signal (6): Abort trap: 6
From worker 7:	while loading no file, in expression starting on line 0
From worker 7:	__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
From worker 7:	Allocations: 147198897 (Pool: 147099722; Big: 99175); GC: 427
```

and finally
```
    FAILURE
Error in testset file:
Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: InterruptException:
  while loading /private/tmp/julia/share/julia/test/file.jl, in expression starting on line 1139
ERROR: LoadError: Test run finished with errors
while loading /private/tmp/julia/share/julia/test/runtests.jl, in expression starting on line 29
```

**Comment by yuyichao** [comment]
The second one is https://github.com/JuliaLang/julia/issues/17626, which might be causing the first one.
