### ISSUE TITLE
generated functions seem to have too-conservative world age counter set

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#23223]
Note the following:
```julia
julia> @generated function foo(::Type{T}) where {T}
           b = bar(T)
           return :($b)
       end
foo (generic function with 1 method)

julia> bar(::Type{Int}) = 1
bar (generic function with 1 method)

julia> bar(::Type{Float64}) = 2
bar (generic function with 2 methods)

julia> foo(Int)
ERROR: MethodError: no method matching bar(::Type{Int64})
The applicable method may be too new: running in world age 22424, while current world is 22426.
Closest candidates are:
  bar(::Type{Int64}) at REPL[16]:1 (method too new to be called from this world context.)
  bar(::Type{Float64}) at REPL[17]:1 (method too new to be called from this world context.)
Stacktrace:
 [1] foo(...) at ./REPL[15]:2

julia> function foo2(::Type{T}) where {T}
           b = bar2(T)
           return b
       end
foo2 (generic function with 1 method)

julia> bar2(::Type{Int}) = 1
bar2 (generic function with 1 method)

julia> bar2(::Type{Float64}) = 2
bar2 (generic function with 2 methods)

julia> foo2(Int)
1
```

I find this behavior surprising because it feels like a "which was defined first" kind of pickiness which doesn't seem characteristic of Julia.

Secondly, if I try to publish my package `CoolOptimizationsForTypes.jl` where users' types need to define their own `bar(::Type{T})` (a required interface for my cool `foo` function), this workflow falls apart because their type can't participate, even if `foo` has never been called/generated on their type.

**Comment by yuyichao** [comment]
This is expected, documented and **NOT** a supported usage of generated function.

**Comment by quinnj** [comment]
I realize this is documented; consider this an "enhancement request" :)

I'd also be interested in hearing more details about the potential problems of using the generation-time world age counter as opposed to definition-time.

**Comment by yuyichao** [comment]
It is basically impossible to figure out when generated functions needs to be regenerated.

**Comment by vtjnash** [comment]
Method source code ("ages") is not allowed to depend on data. This is fundamental to the design of the fix for #265. I realize that it's weird to think of the execution of code as data, but welcome to LISP :)

**Comment by quinnj** [comment]
That indeed seems like it'd be a hard problem, but re-generation *does* occur sometimes, and we know about it, so it still seems that when we *do* decide to re-generate, the current generation-time world-age counter could be used.

In my case, it'd even work to just be able to use `Base.invokelatest`, but that seems to just give up inside generated functions. But maybe that's an easier/more plausible solution here.

In my use-case, I have some serialization-like code that aims to be very performant by generating streamlined code based on a specific type's fieldnames, fieldtypes, and some additional "type properties" that constitute the "interface" that custom types can optionally implement if they desire to adjust the serialization. I can't use a `const TYPE_PROPERTIES = ...` dict for users to store their type traits in, because that gets clobbered by pre-compilation, and my efforts to allow users' to define "trait functions" are now thwarted by this world age issue (since they define their type properties after my module is loaded).

And honestly, could it really be that much more scary than the current generated function story? I mean, geez, the section on GF's is basically a collection of "don't-do-that" "yeah, that's not going to work", "nope, not that either", "you probably shouldn't use this for that", etc.

**Comment by yuyichao** [comment]
> re-generation does occur sometimes

Basically no. We don't guarantee that but if we ever do that for dispatch it's a performance bug.

> the current generation-time world-age counter could be used.

So reintroduce #265?

**Comment by vtjnash** [comment]
>> the current generation-time world-age counter could be used.
>
> So reintroduce #265?

It's possible to design a language where even data is immutable, but that's not #265.

> scary than the current generated function story

It shouldn't be scary. It's just important to realize that they are part of the compiler (and thus are data), not the runtime (and thus are not similar to methods). As such, it is strictly impossible (by definition) for them to be more capable than a normal function. They are, however, capable of implementing optimizations that are not currently part of the compiler, or that aren't worthwhile to code for generically. It would be possible to define them to be part of the runtime, but then it would be invalid for the compiler to inspect them, making there existence as an annotation pointless (because they would be strictly inferior to not annotating them at all).

**Comment by quinnj** [comment]
But could `Base.invokelatest` at least be made to work? I think I understand the "code as data" point, it's just somewhat frustrating because it seems like user types/functions get left out of the game, just because they happen to come later stage.

Also because in my use-case, I'm dealing with super-pure, static, const type properties that won't change. A user defines a type, defines `foo(::Type{MyType}) = [const]` and `bar(::Type{MyType}) = [const]` and they're done, and I just need to be able to "see" those static methods when generating.

**Comment by yuyichao** [comment]
> But could Base.invokelatest at least be made to work?

Which is what I said about reintroducing #265 

> that won't change

But you are saying that you are, by overloading the functions.
