### ISSUE TITLE
deprecate Date(d::AbstractString, format::AbstractString; locale) method

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#23225]
`Date(d::AbstractString, format::AbstractString)` should be deprecated In favor of `Date(d::AbstractString, df::DateFormat)` for the sake of performance. Ref. discussion in https://github.com/JuliaLang/julia/pull/23207#issuecomment-321903831. Best!

**Comment by StefanKarpinski** [comment]
No longer a milestone blocker since we're moving `Dates` out of Base: https://github.com/JuliaLang/julia/issues/23302.

**Comment by laborg** [comment]
This has been removed.
