### ISSUE TITLE
parse \mapsfrom and rest of unicode arrows as infix operators

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#23224]
Mentioned in #11223: `\mapsfrom` `↤` (U+21A4) is not currently parsed as an infix operator.  It should be parsed with the same precedence as `\mapsto` (`↦`).

**Comment by StefanKarpinski** [comment]
This doesn't really belong on the 1.0 milestone since fixing this will not break any code. Of course it would be nice to have, and if someone implements it, great, but it's not a release blocker.

**Comment by stevengj** [comment]
Currently it is parsed as an identifier for some reason, so this would be a breaking change:
```
julia> ↤ = 7
7

julia> ↤ + 2
9
```

**Comment by stevengj** [comment]
The reason it is an identifier is that `\mapsfrom` = [U+21A4](http://www.fileformat.info/info/unicode/char/21a4/index.htm) is in category So (Symbol, Other), not category Sm (Symbol, Math), unlike `\mapsto` = [U+21A6](http://www.fileformat.info/info/unicode/char/21a6/index.htm).

**Comment by stevengj** [comment]
However, many of the things in the [Arrows block](https://en.wikipedia.org/wiki/Arrows_(Unicode_block)) are parsed as operators, so U+21A4 must have been an oversight.

**Comment by stevengj** [comment]
One issue with some of the elements of the arrows block is precedence.   Horizontal arrows are parsed with `-->` precedence, and vertical arrows are parsed with `^` precedence, but I wasn't sure what to do with things like `↗` or `↺`

**Comment by JeffBezanson** [comment]
Maybe leftward arrows should also be right-associative as well? (#24153)

**Comment by mschauer** [comment]
Ideally if  `x ↦ y ↦ z` is `x ↦ (y ↦ z)` then `z ↤ y ↤ x` should be `(z ↤ y) ↤ x`.

**Comment by JeffBezanson** [comment]
I was confused: all arrow-precedence operators are currently right associative. I believe that is standard both in logic and type notation (mumble mumble isomorphism). `|>` and `<|` have their own precedence level and are left associative, and arguably `<|` should be changed to right associative.

Currently everything in the arrows block with category Sm is parsed as an operator, which is good. For every remaining arrow character, we should either parse it as an arrow if it's obviously a sensible mathematical operator, or make it an invalid character. Then the invalid characters can be added as needed, if ever.
