### ISSUE TITLE
Missing GC roots in libgit2 code

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#23231]
LibGit2 doesn't root the credentials object when it passes it to C (https://github.com/JuliaLang/julia/blob/51fbb0cfd37072940ada59a997ebb9490de93d48/base/libgit2/types.jl#L186-L192). Common symptoms are crashes or incorrectly refused connections.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/21638
Knowing it's been doing invalid things all along, I'm still surprised that no one have reported a crash.

**Comment by Keno** [comment]
Well, I'm reporting a crash right here, right now :)
