### ISSUE TITLE
Float16/32 inconsistent compact NaN printing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23248]
While writing tests for #23244, I encountered this inconsistency:

```jl
julia> AbstractFloat[NaN16, NaN32, NaN64]
3-element Array{AbstractFloat,1}:
   NaN
 NaN32
   NaN
```

For compact printing, either `NaN16` should print as "NaN16" or `NaN32` should print as "NaN". Both changes are fairly straightforward, to implement the former, just change the `false` on this line to `true`:

https://github.com/JuliaLang/julia/blob/131807cc574bc8452b463247d4903d2eb6cfec6b/base/grisu/grisu.jl#L127

To implement the latter, just change the `true` on this line to `x isa Float32`:

https://github.com/JuliaLang/julia/blob/131807cc574bc8452b463247d4903d2eb6cfec6b/base/grisu/grisu.jl#L119

In either case, tests should be added to check the printing behavior of `NaN` in compact context. This is quite straightforward so I'm labeling it as an intro issue.

**Comment by StefanKarpinski** [comment]
Sorry, this was on 0.6, on 0.7 I get the correct behavior:

```jl
julia> AbstractFloat[NaN16, NaN32, NaN64]
3-element Array{AbstractFloat,1}:
 NaN16
 NaN32
   NaN
```

**Comment by StefanKarpinski** [comment]
Ah, the discrepancy still exists, it's just harder to trigger now since we don't use compact printing for vectors anymore:
```jl
julia> show(IOContext(STDOUT, :compact => true), NaN16);
NaN

julia> show(IOContext(STDOUT, :compact => true), NaN32);
NaN32
```

**Comment by StefanKarpinski** [comment]
This really just needs a decision on which way to go: either print all NaNs as `NaN` in compact mode or print the non-Float64 one as `NaN16`, `NaN32`, etc.

**Comment by Vaibhavdixit02** [comment]
Hey, I would like to work on this issue. Can you help me out?

**Comment by StefanKarpinski** [comment]
We need a decision first, but either way this is a small change, so you might consider preparing to PRs – one in each direction. Once you've done one, the other is easy.

**Comment by StefanKarpinski** [comment]
The guide to making a contribution is here: https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md.

**Comment by StefanKarpinski** [comment]
Decision made: since other compact show methods discard type identifying information, NaN printing should too. So that's the latter option, i.e. change this line:

https://github.com/JuliaLang/julia/blob/131807cc574bc8452b463247d4903d2eb6cfec6b/base/grisu/grisu.jl#L119

Specifically, change the first `true` to `x isa Float32`.

**Comment by Vaibhavdixit02** [comment]
Yes I have gone through https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md . I did not get what you meant by "PRs – one in each direction". I will make the change and send a PR.

**Comment by StefanKarpinski** [comment]
Yeah, don't worry about the two PRs thing – just do the one changing line 119. You'll want to add tests for compact printing of NaN in each floating-point type and make sure that they're all "NaN".

**Comment by Vaibhavdixit02** [comment]
Hey, sorry to be a bother. Actually I was confused about the test, I went through the instructions given in https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md but I was not able to figure it out. Can you help me out?

**Comment by fredrikekre** [comment]
If want you can join the julia slack forum (see https://github.com/JuliaLang/julia#resources), there is a channel dedicated to `#my-first-pr` where you probably can get help faster for quick and small questions.
