### ISSUE TITLE
convert to Float16 fails for NaN with large payloads

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23250]
```jl
julia> nan = reinterpret(Float32, typemax(UInt32))
NaN32

julia> convert(Float16, nan)
ERROR: InexactError()
Stacktrace:
 [1] convert(::Type{Float16}, ::Float32) at ./float.jl:148
```

**Comment by yuyichao** [comment]
If we want convert to be precise and keep the payload at the same time, what else can we do here? (Make `nan % Float16` work?)

**Comment by StefanKarpinski** [comment]
Yes, that's what the PR I just opened does. Didn't realize fixing that would end up fixing this, but making the round tripping work correctly required fix both directions.
