### ISSUE TITLE
download() does not disable globbing for curl (-g)

### ISSUE THREAD

**Issue by 0x47** [JuliaLang/julia#23254]
When using download() with a URL that contains `[ ]` or `{ }`, Julia crashes with

    ERROR: LoadError: failed process: Process(`curl ...

This could be prevented by using the `-g` or `--globoff` switch.
Version info (Arch Linux binary):

    Julia Version 0.6.0
    Commit 903644385b* (2017-06-19 13:05 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
      WORD_SIZE: 64
      BLAS: libblas
      LAPACK: liblapack
      LIBM: libm
      LLVM: libLLVM-4.0.0 (ORCJIT, skylake)

**Comment by nalimilan** [comment]
Thanks for the report. Would you make a pull request to fix this?

**Comment by 0x47** [comment]
There you go
