### ISSUE TITLE
State clearly in the documentation that the iteration of a Set occurs in undefined order

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#23269]
Since Sets hash items depending on memory locations, this is not deterministic. Therefore iterating over a Set will traverse items in undefined order.

This behaviour has been the cause of some hard to find bugs for me. I am not saying that there is something wrong with it, but it should be clearly stated in the documentation, so that we are alert.

**Comment by JeffBezanson** [comment]
> depending on memory locations

The results of hash functions that don't depend on memory locations aren't exactly predictable either. While the same from run to run, one still shouldn't depend on the order.

**Comment by JeffBezanson** [comment]
ref #12198

**Comment by Zapiano** [comment]
Is this issue still relevant? Julia's documentation about Set says: "The order of elements in a Set is an implementation detail and cannot be relied on." Should it be more clear than that? If so, I could solve this one.

**Comment by oscardssmith** [comment]
looks good as is to me
