### ISSUE TITLE
REPL improvement: filter history using typed input when pressing ^P/^N

### ISSUE THREAD

**Issue by eveydee** [JuliaLang/julia#23299]
This is what happens in IPython: Start typing:
```python
In [1]: abc = 4
In [2]: xyz = 6
In [3]: a # press up
---> In [3]: abc = 4
```
I have tried to get used to using C-r and C-s, but this feature from IPython is just so useful, that I think the Julia REPL should have should have something similar too.

What I would want is something that does the following, which probably isn't exactly as it is in IPython:
- When you start typing at the beginning of the input line, the input should be saved in a temporary buffer, `buffer`
- Pressing up/down saves the buffer and skips entries in the history until `ismatch(r"^$buffer", history_entry)` (ignoring that interpolation won't work here).
- Moving the cursor after having traversed the history clears the buffer.

**Comment by JeffBezanson** [comment]
I believe the REPL already does this?

**Comment by eveydee** [comment]
Oh my, you are right. But not when pressing C-p. >_<

**Comment by StefanKarpinski** [comment]
I'd actually prefer if it *only* did this when doing ctrl-P/N but that's my personal preference. What we really need is a better (and documented) interface for customizing this sort of thing.
