### ISSUE TITLE
huge performance hit in 0.6.0 - concatenation of sparse matrices

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#23296]
I ported my code from 0.5.2 to 0.6.0 and found that it took almost twice as long.  The cause seems to be a single statement that concatenates sparse matrices.  I have put together a test code to illustrate the problem.  To run this code, you first need to download the data file containing the sparse matrices.  

http://www.math.uwaterloo.ca/~vavasis/testout.txt

According to my timing tests (see below), this test code is 10x slower in 0.6.0 than in 0.5.2:

0.5.2:
```
julia> @time test_sparse_cat.test()
  5.722144 seconds (82.99 M allocations: 1.933 GB, 25.27% gc time)
-1733.3448898316724
```

0.6.0:
```
julia> @time test_sparse_cat.test()
 57.610521 seconds (3.64 M allocations: 1.205 GiB, 1.68% gc time)
-1733.3448898316724
```

Here is the test code.
```julia
module test_sparse_cat


function test()
    testout = open("testout.txt", "r")
    hxx = readsparse(testout)::SparseMatrixCSC{Float64,Int}
    hxs = readsparse(testout)::SparseMatrixCSC{Float64,Int}
    hxt = readsparse(testout)::SparseVector{Float64,Int}
    hss = readsparse(testout)::SparseMatrixCSC{Float64,Int}
    hst = readsparse(testout)::SparseMatrixCSC{Float64,Int}
    htt = readsparse(testout)::SparseVector{Float64,Int}
    close(testout)
    s = 0.0
    h = spzeros(0,0)
    for trial = 1 : 15
        hxx[1,1] += 1.0
        h = [hxx   hxs   hxt
             hxs'  hss   hst
             hxt'  hst'  htt]
        s += h[1,1]
    end
    s
end

function readsparse(io)
    s = readline(io)
    w = split(s)
    if length(w) == 2
        return readsparsevec(io, w)
    end
    @assert length(w) == 3
    return readsparsemat(io, w)
end

function readsparsevec(io, w)
    nrow = parse(Int, w[1])
    nnz = parse(Int, w[2])
    is = Vector{Int}(nnz)
    es = Vector{Float64}(nnz)
    for i = 1 : nnz
        s = readline(io)
        w = split(s)
        @assert length(w) == 2
        is[i] = parse(Int, w[1])
        es[i] = parse(Float64, w[2])
    end
    SparseVector(nrow, is, es)
end

function readsparsemat(io, w)
    nrow = parse(Int, w[1])
    ncol = parse(Int, w[2])
    nnz = parse(Int, w[3])
    is = Vector{Int}(nnz)
    js = Vector{Int}(nnz)
    es = Vector{Float64}(nnz)
    for i = 1 : nnz
        s = readline(io)
        w = split(s)
        @assert length(w) == 3
        is[i] = parse(Int, w[1])
        js[i] = parse(Int, w[2])
        es[i] = parse(Float64, w[3])
    end
    sparse(is, js, es, nrow, ncol)
end

end
```

**Comment by KristofferC** [comment]
Looks like the specialized concatenation functions are not being used.

**Comment by fredrikekre** [comment]
Perhaps because `sprand(5, 0.5)'` on 0.6 is a `RowVector{Float64,SparseVector{Float64,Int64}}` and we dispatch incorrectly on that?

**Comment by KristofferC** [comment]
Yes,
```jl
@time h = [hxx                   
           hxt']
```

is enough to induce the slowdown.

**Comment by fredrikekre** [comment]
Until this is fixed, using a one-column `SparseMatrixCSC` instead of a `SparseVector` should do the trick I suppose.

**Comment by StephenVavasis** [comment]
Fredrik,

Yes, thanks, using only sparse matrices instead of a mix of matrices and vectors  seems to fix the problem.  I'll update my main code with this fix and hope for the best.

-- Steve

**Comment by StephenVavasis** [comment]
This is the second time that I have been hit by a serious performance bug involving sparse matrices because a routine unintentionally fell back to an abstract array implementation.  The previous occurrence was with a pre-release master of 0.6.0 in which `-A` for sparse `A`, defaulted to a loop over all (dense) entries. 

Could I suggest that permitting sparse matrix routines to fall back to abstract array implementations allows performance-killing bugs to slip through the regression checking unnoticed, and that therefore this maybe should be forbidden or at least restricted?

**Comment by tkelman** [comment]
Performance regressions will be tracked and noticed for anything added to https://github.com/JuliaCI/BaseBenchmarks.jl - always encouraged to add more test cases there
