### ISSUE TITLE
Disallow juxtaposition with hex literals

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#23304]
While juxtaposition is very useful for things like `2x`, `100y`, etc, it can get very confusing with hex literals:
```
0xapi # 0xa * pi
0xax
0xap0 # hexfloat literal
```
I propose disallowing juxtaposition of hex literals.

**Comment by JeffBezanson** [comment]
Knew I'd seen this somewhere before: #16356

**Comment by Keno** [comment]
Closing as dup then, and I'll but that one on the milestone.
