### ISSUE TITLE
What is the plan for the {} literals in future versions of julia

### ISSUE THREAD

**Issue by sighoya** [JuliaLang/julia#23346]
When using {} in julia v 0.6.0
we receive 
ERROR: syntax: { } vector syntax is discontinued

Could we use {} for Sets and Dicts instead with:
{1,2,3} == Set([1,2,3])
{1=>2,3=>4} == Dict(1=>2,3=>4)

What do you think about. Would it be possible?

**Comment by fredrikekre** [comment]
#8470
