### ISSUE TITLE
Why Dict does support polyvariadic number of pairs but not of tuples? 

### ISSUE THREAD

**Issue by sighoya** [JuliaLang/julia#23347]
When specify Dict with:
 Dict(1=>2,3=>4)
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 2
But 
Dict((1,2),(3,4))
ERROR: MethodError: no method matching Dict(::Tuple{Int64,Int64}, ::Tuple{Int64,Int64})

gives an error.

Would it be better to add support for varargs for Tuple, Array parameters?

The same could be done for Sets:
Set(1,2,3,4)
ERROR: MethodError: no method matching Set(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  Set(::Any) at set.jl:10
Stacktrace:
 [1] macro expansion at ./REPL.jl:97 [inlined]
 [2] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

**Comment by andreasnoack** [comment]
Please ask questions at discourse.julialang.org

**Comment by rfourquet** [comment]
For the part concerning `Set`, #22477
