### ISSUE TITLE
Float precision bug?!

### ISSUE THREAD

**Issue by yjw413** [JuliaLang/julia#23344]
today I install Julia software of v0.6.0, when I using it to calculate the expresion "1.011-0.011", it returns "0.9999999999999999" while it should be 1.0.  The result confuses me now, I don't what causes this happen and how to fix it?! Is that a bug?
 How could I do for right calculating? Thanks
`julia> 1.011-0.011
0.9999999999999999`

**Comment by lobingera** [comment]
It's no bug, 1.011 and 0.011 can not be represented exactly in floating point. But this behaviour shows up in various places: https://blogs.office.com/en-us/2008/04/10/understanding-floating-point-precision-aka-why-does-excel-give-me-seemingly-wrong-answers/
