### ISSUE TITLE
fatal error in type inference (type bound)

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#23356]
```julia
struct BitsUnion
    x::Union{Int64,Float64}
end
bitsunion = BitsUnion(5.0);
f(x) = nothing
g(x) = f(convert(Union{Float64, Int64}, getfield(x, 1)))

julia> g(bitsunion)
ERROR: fatal error in type inference (type bound)
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] g(::BitsUnion) at ./REPL[4]:1
```

Only happens on master.

**Comment by quinnj** [comment]
Probably also a dup of https://github.com/JuliaLang/julia/issues/23351 since type inference can't load what the type of `bitsunion.x` is.

**Comment by simonster** [comment]
You're probably right that it's the same issue. It seems like `"fatal error in type inference (type bound)"` is actually a runtime error that type inferences writes into the generated code and it gets triggers when the `getfield` call doesn't return a Float64 or Int64.
