### ISSUE TITLE
Tab complete non-module after using and import

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#23374]
This behavior is really annoying:
```julia
julia> using Base.LinAlg.Po<TAB> # nothing happens ...
```
Need to spell out `PosDefException`, since it does not auto complete.
It would be much nicer if we allowed completion of non-module things also.
Ref https://github.com/JuliaLang/julia/pull/23193#issuecomment-321785186

**Comment by RatanRSur** [comment]
I'd like to take a stab at this

**Comment by fredrikekre** [comment]
Great, the relevant code to modify is probably https://github.com/JuliaLang/julia/blob/056b374919e11977d5a8d57b446ad1c72f3e6b1d/base/repl/REPLCompletions.jl#L385-L394 and more specifically https://github.com/JuliaLang/julia/blob/056b374919e11977d5a8d57b446ad1c72f3e6b1d/base/repl/REPLCompletions.jl#L393
See also #23193

**Comment by KristofferC** [comment]
This is actually correct for `using` now since `using A.B` is only correct if `B` is a module. However, should still work with `import`.

**Comment by fredrikekre** [comment]
Would it be possible to tab-complete in situations like this? `using Base.LinAlg: <TAB>`
