### ISSUE TITLE
build_sysimg fails when Julia directory is not writable

### ISSUE THREAD

**Issue by alhirzel** [JuliaLang/julia#23370]
https://github.com/JuliaLang/julia/blob/b0b0cbc014fa2651a0daf04e40882347436b93d2/contrib/build_sysimg.jl#L69

When playing around with BuildExecutable, I noticed that it attempts to copy userimg.jl into /usr/share/julia during build. I believe this should be avoided (e.g. because some distributions put Julia under a read-only directory). I also understand that currently this mechanism is used because userimg.jl is assumed to be in the same directory as all system files. Is there a way to change this behavior to use an externally-located userimg.jl?

**Comment by vtjnash** [comment]
@ViralBShah is there some way we could update the docs to use your `juliac.jl` script instead? Or maybe we should delete this contrib script when https://github.com/dhoegh/BuildExecutable.jl/issues/45 is resolved?
