### ISSUE TITLE
Use min(m,n) instead of max(m,n) when determining numerical rank in pinv and \

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#23386]
Following up on https://github.com/JuliaLang/julia/pull/23067#discussion_r131481492. I did some simulations and it seems that error is determined by the minimum and not the maximum size. This would also make the vector and matrix case consistent.

**Comment by StefanKarpinski** [comment]
Breaking change or not?

**Comment by andreasnoack** [comment]
Slightly but subtly breaking. Most matrices won't be affected but a few will get a different numerical rank.
