### ISSUE TITLE
Add doctest examples to some of the stdlib string functions

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#23392]
Scrolling through [the documentation](https://docs.julialang.org/en/stable/stdlib/strings/) we can see that many of the string functions (especially ones involving regexes) don't have any doctest examples. Adding some would be a great way to get started if you're looking to contribute!

If the docstring mentions several possible behaviours of a function (for instance, if there's a kwarg) it's nice to provide examples for each of the described behaviours.

**Comment by fredrikekre** [comment]
Regex-related string docstrings could still use more examples.

**Comment by bkamins** [comment]
In #24039 I have added some additional doctests for strings.

**Comment by josobar** [comment]
I have added additional doctests in #34271

**Comment by KristofferC** [comment]
With all the work done, probably no need to keep this open.
