### ISSUE TITLE
doctests that ignore Stacktrace and "..."

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/julia#23390]
Documentation has to be updated too often as the code changes, because rapidly changing parts of output (mostly stacktraces) are checked by doctests. 

It would be nice to have something similar to Python doctests, which ignore stacktraces and ellipses (see https://docs.python.org/3/library/doctest.html#what-about-exceptions and https://docs.python.org/3/library/doctest.html#doctest.ELLIPSIS). For example for stacktraces the analog of Python doctests in Julia would be that
```
"""jldoctest
julia> 2^-5
ERROR: DomainError with -5:
Cannot raise an integer x to a negative power -5.
Make x a float by adding a zero decimal (e.g., 2.0^-5 instead of 2^-5), or write 1/x^5, float(x)^-5, or (x//1)^-5
Stacktrace:
 [1] throw_domerr_powbysq(::Int64) at ./intfuncs.jl:164
 [2] power_by_squaring at ./intfuncs.jl:179 [inlined]
 [3] ^ at ./intfuncs.jl:203 [inlined]
 [4] literal_pow(::Base.#^, ::Int64, ::Val{-5}) at ./intfuncs.jl:214
"""

```

would match
```
"""jldoctest
julia> 2^-5
ERROR: DomainError with -5:
Cannot raise an integer x to a negative power -5.
Make x a float by adding a zero decimal (e.g., 2.0^-5 instead of 2^-5), or write 1/x^5, float(x)^-5, or (x//1)^-5
Stacktrace:
 [1] ANY OTHER STUFF at ./ANY_OTHER_FILE.jl:999
 [2] something at ./something.jl:1234
"""
```

For ellipses,
```
"""jldoctest
julia> (42, rand()) # doctest: +ELLIPSIS
(42, ...)
"""
```
would match
```
"""jldoctest
julia> (42, rand())
(42, 0.1190827822639473)
"""
```
(In Python doctests, random numbers would actually be dealt with by https://docs.python.org/3/library/doctest.html#doctest.SKIP and not ellipses)

**Comment by fredrikekre** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/540

**Comment by afniedermayer** [comment]
Thanks, I looked for this feature in JuliaLang, but didn't see it in JuliaDocs. So that PR would fix stacktraces once it's merged. There's still features like ellipsis and skip ( https://docs.python.org/2/library/doctest.html#option-flags ). Is this issue more appropriate for JuliaDocs than JuliaLang?

**Comment by KristofferC** [comment]
https://github.com/JuliaDocs/Documenter.jl/pull/573
