### ISSUE TITLE
Dates.year(now()) returns an Int64 on 32-bit AppVeyor

### ISSUE THREAD

**Issue by christopher-dG** [JuliaLang/julia#23403]
This prevents me from passing its output to methods that take an `Int`.
 
[Demo code](https://github.com/christopher-dG/ThirtyTwo.jl)

[Failing 32-bit build](https://ci.appveyor.com/project/christopher-dG/thirtytwo-jl/build/job/xfg62meogarl07xm)

The issue is present on both 0.6 and 0.7. I'd dig into this myself, but I:

a) Am scared by looking at the source for `Dates.year`
b) Don't have a 32-bit machine to play around with.

**Comment by quinnj** [comment]
`Dates.year(::TimeType)` has never returned anything _but_ an Int64, so nothing is wrong or broken. `Int64` was chosen due to the higher precision. If you need it to be an `Int`, just call `Int(Dates.year(now()))`.

**Comment by christopher-dG** [comment]
Thanks for the clarification. It's even documented, and I didn't check! :man_facepalming:
