### ISSUE TITLE
StackOverflow during inference

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#23409]
https://gist.github.com/iamed2/af0beb227398080e5375f6ce8616710e

Checkout the `partition-length` branch of `IterTools`. Then run:

```julia
using IterTools
foo(p) = length(collect(p)) == length(p)
foo(partition([1], 759))
```

Useful facts:
* 367 is the lowest number which causes this error on 0.7.
* That number is 759 on 0.6.
* `partition(::I, n::Int)::Partition{I, n}` and `collect(::Partition{I, N})::Vector{NTuple{N, eltype(I)}}`
* the function does execute and returns `true`
* If you run the above code with a small number first, the error does not occur

**Comment by vtjnash** [comment]
Works for me now, though note that there's a missing `where {I}` in that branch, so while it still gets the right answer (as long as it does `using LinearAlgebra: I`), it's not probably what the author intended.

```
julia> using IterTools

julia> Base.IteratorSize(::Type{<:IterTools.Partition{I}}) where {I} = IterTools.longest(Base.HasLength(), Base.IteratorSize(I))

julia> Base.length(p::IterTools.Partition{I, N}) where {I, N} = max(fld(length(p.xs) - N, p.step) + 1, 0)

julia> foo(p) = length(collect(p)) == length(p)
foo (generic function with 1 method)

julia> foo(partition([1], 759))
true
```
