### ISSUE TITLE
Feature request: collect coverage data from the worker processes

### ISSUE THREAD

**Issue by fjarri** [JuliaLang/julia#23416]
In Julia v0.6 (and a semi-recent nightly), the coverage is only collected for the main process in a multi-process run:

```
@everywhere function f(x)
    if x == 1
        println(1)
    else
        println(x)
    end
end

@everywhere f(myid())
```

Running as `julia --code-coverage=user --inline=no -p 1 t.jl` gives the output:

```
1
	From worker 2:	2
```

while the coverage output shows that the second println was not touched:

```
        - @everywhere function f(x)
        1     if x == 1
        1         println(1)
        -     else
        0         println(x)
        -     end
        - end
        - 
        - @everywhere f(myid())
        - 
```

It would greatly increase the usefulness of multi-process test execution if it was possible to collect the coverage data for all the processes and not just for the main one.

**Comment by timholy** [comment]
@kshyatt, I thought you implemented this?

**Comment by vtjnash** [comment]
Coverage files are created per-process, and the code-coverage flags should typically be propagated (e.g. Base's own test suite does exactly this with runtests and addprocs)
