### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by Polyergic** [JuliaLang/julia#23425]
macOS 10.12.6 (16G29) with macports and `/opt/local/libexec/gnubin/` in my path.

output from `make`:

```
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
make[1]: *** [scratch/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/build-configured] Error 1
make: *** [julia-deps] Error 2
```
That is the complete output of my last attempt at `make`, after running `make clean`, and is identical to the attempt immediately before `make clean` and to the output of `make debug`.

I started out following directions in the readme, with these commands (all of which seemed to work):
```
git clone https://github.com/JuliaLang/julia
cd julia/
git checkout v0.6.0
make
```
The first attempt at `make` gave [18643 lines of output](https://github.com/JuliaLang/julia/files/1248635/julia.make.output.txt) (I gather most of it is related to dependencies), including a large number of compile warnings and passing tests, and ended with the same output preceded by additional errors:
```
/opt/local/bin/ranlib: file: libspqr.a(spqr_parallel.o) has no symbols
/opt/local/bin/ranlib: file: libspqr.a(spqr_debug.o) has no symbols
ranlib: file: libspqr.a(spqr_parallel.o) has no symbols
ranlib: file: libspqr.a(spqr_debug.o) has no symbols
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    497      0  0:00:01 --:--:--  0:00:01  2715
100 1378k  100 1378k    0     0   689k      0  0:00:02  0:00:02 --:--:-- 1507k
rm: cannot remove '/Users/polyergic/Downloads/julia/deps/srccache/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/': No such file or directory
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
make[1]: *** [scratch/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/build-configured] Error 1
make: *** [julia-deps] Error 2
```

When I run `ls -t` it seems to work; `ls` is aliased to `ls $LS_OPTIONS`, which expands to `ls -N --color=tty -T 0`, and removing the alias has no effect.  My system clock seems to be set and working correctly.

**Comment by Polyergic** [comment]
Tried again on a different mac, and everything seemed to work.  I have no idea what differences might affect this.  Where can I see what the sanity checks on `ls -t` and file times actually do?

**Comment by StefanKarpinski** [comment]
This seems to be a `libuv` build issue. Can you build `libuv` from source on that machine?

**Comment by Polyergic** [comment]
No, `libuv`'s `./configure` fails with the same error messages:

```
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... configure: error: ls -t appears to fail.  Make sure there is not a broken
  alias in your environment
configure: error: newly created file is older than distributed files!
Check your system clock
```

**Comment by Polyergic** [comment]
It turns out I had my own long forgotten `~/bin/ls` which was forcing color output and making the test fail. Removing that (hopefully I don't need it anymore) fixed both the `libuv` build and the `julia` build.  Hopefully this means we actually can [update the macports package](https://trac.macports.org/ticket/53124).
