### ISSUE TITLE
Range, UnitRange, AbstractUnitRange have no inline documentation

### ISSUE THREAD

**Issue by sambitdash** [JuliaLang/julia#23421]
This makes it harder understand what object can be used / instantiated. Below is the REPL inline doc dump. 

```
help?> UnitRange
search: UnitRange AbstractUnitRange

  No documentation found.

  Base.UnitRange is of type UnionAll.

     Summary
    ≡≡≡≡≡≡≡≡≡

  struct UnionAll <: Type{T}

     Fields
    ≡≡≡≡≡≡≡≡

  var  :: TypeVar
  body :: Any

     Supertype Hierarchy
    ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

  UnionAll <: Type{T} <: Any

help?> AbstractUnitRange
search: AbstractUnitRange

  No documentation found.

  Base.AbstractUnitRange is of type UnionAll.

     Summary
    ≡≡≡≡≡≡≡≡≡

  struct UnionAll <: Type{T}

     Fields
    ≡≡≡≡≡≡≡≡

  var  :: TypeVar
  body :: Any

     Supertype Hierarchy
    ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
```

**Comment by fredrikekre** [comment]
I think #21126 would partially fix this, would still be good to add explicit docstrings for these types.

**Comment by rfourquet** [comment]
Dup of #16393.

**Comment by fredrikekre** [comment]
> Dup of #16393.

I disagree, #16393 is more about a general manual section on ranges, and this is about documenting the specific types.

**Comment by rfourquet** [comment]
I agree with you that both issues have their specificities, but I felt that 2 open github issues to track this long-standing range-doc issue was not necessary. Feel free to reopen though.
