### ISSUE TITLE
check_ambiguous_visitor Assertion failure

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#23456]
Steps to reproduce on latest master:
```julia
Pkg.clone("CategoricalArrays"); using CategoricalArrays
```

My output:
```julia
julia> using CategoricalArrays
INFO: Recompiling stale cache file /Users/jacobquinn/.julia/lib/v0.7/CategoricalArrays.ji for module CategoricalArrays.
Assertion failed: (!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)), function check_ambiguous_visitor, file /Users/jacobquinn/julia/src/gf.c, line 1128.

signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 10101350 (Pool: 10099217; Big: 2133); GC: 16
Abort trap: 6
```
FWIW, I tried on the current `jq/bitsunions` branch as well and got the same result (not that this is necessarily related, but I happened to be on the branch when I first saw the bug).

**Comment by nalimilan** [comment]
Surprisingly, CategoricalArrays loads fine locally as well as on Travis and AppVeyor. Tests fail, but without crashing.

**Comment by quinnj** [comment]
I believe this actually only crashed on `made debug`

**Comment by quinnj** [comment]
Bump; it'd be good to get this one figured out so downstream segfaults involving the same packages could be investigated.

**Comment by quinnj** [comment]
Ok, did some digging here, the actual arguments which are leading to the assertion failure
```
(lldb) call jl_(sig)
Tuple{typeof(Base.convert), Type{Union{Nulls.Null, S}}, CategoricalArrays.CategoricalValue{T, R} where R<:Integer where T} where S
(lldb) call jl_(type)
Tuple{typeof(Base.convert), Type{S}, CategoricalArrays.CategoricalValue{T, R} where R<:Integer where T} where S
(lldb)
```
And it seems to be happening when loading the precompiled CategoricalArrays.ji file; there is one other TypeMapEntry that looks odd `TypeMapEntry(sig=Tuple{typeof(Base.convert), Type{Union{Nulls.Null, T}}, Any} where T, simplesig=nothing, guardsigs=svec(), min_world=22772, max_world=-1, func=Nulls.convert(...), isleafsig=false, issimplesig=false, va=false, next=↩︎`, in particular, I'm not sure I've seen `Type{Union{Nulls.Null, T}}, Any} where T` before; as far as I can tell, `Type` is only allowed to have a single type parameter.

**Comment by quinnj** [comment]
Ok, so minimum repro:

```julia
# B.jl
__precompile__(true)
module B

struct CategoricalValue end

Base.convert(::Type{S}, x::CategoricalValue) where {S} = convert(S, index(x.pool)[x.level])
Base.convert(::Type{Union{S, Void}}, x::CategoricalValue) where {S} = convert(S, index(x.pool)[x.level])

end # module
```
Then just do
```julia
using B
```
and hit the assertion error w/ `julia-debug`. In particular, it requires _both_ `convert` definitions in module `B`, which I'm guessing is the cause of the issues here, since `Base.convert(::Type{S}, ...` and `Base.convert(::Type{Union{S, Null}}, ...` are ambiguous?

For the 2nd convert definition, it seems I've noticed that, for example, `Any <: Union{T, Void} where T`. It seems like it would be preferable to somehow _*require*_ that the 2nd type there actually be a Union type, so as to _exclude_ `Any` from matching there. I'm sure that breaks all sorts of fundamental type operations or something though.

**Comment by vtjnash** [comment]
julia> Any == Union{T, Void} where T
true
```

**Comment by nalimilan** [comment]
It would be enough to be able to say `Union{T, Null} where {T != Any}`, e.g. via a strict subtyping operator (`T <<: Any`?).
