### ISSUE TITLE
Let's have the release version instead of the git hash in the directory name

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#23452]
When you download julia binaries, (example 0.6), the binaries are placed in a  directory like  `julia-903644385b`. What you really want is `julia-0.6.0` for the released versions.

**Comment by ViralBShah** [comment]
@staticfloat Any thoughts on if this is an easy thing to pull off or will it have ramifications on too many things in CI and buildbots?

**Comment by ViralBShah** [comment]
I really think that when we release 1.0, it should unpack as `julia-1.0` and not `julia-<hash>`.

**Comment by staticfloat** [comment]
This shouldn't hurt anything in CI or the buildbots.  We typically do things like `cd julia-*` if we need to anyway.  This should be as easy as changing these lines https://github.com/JuliaLang/julia/blob/master/Make.inc#L164-L168 to something more like:

```

ifneq ($(NO_GIT), 1)
JULIA_COMMIT := $(shell git rev-parse --short=10 HEAD)
else
JULIA_COMMIT := $(JULIA_VERSION)
endif

# Override `JULIA_COMMIT` to `JULIA_VERSION` if we're on a tagged commit
ifeq ($(shell git describe --tags --exact-match 2> /dev/null && echo true),true)
JULIA_COMMIT := $(JULIA_VERSION)
endif
```

I haven't tested that, but it seems like roughly what we want to do.

**Comment by ViralBShah** [comment]
Trying it now and making a PR if successful.
