### ISSUE TITLE
LLVM Install fails when building with DESTDIR=

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#23462]
I have [a `Dockerfile` that sets `DESTDIR=/var/task`](https://github.com/samoconnor/AWSLambda.jl/blob/master/docker/lambdajlbase/Dockerfile) to build Julia v0.6.0 for AWS Lambda.

It seems that when `cmake` installs llvm into a staging area, it prefixes the install path with `DESTDIR` even though `CMAKE_INSTALL_PREFIX` is a fully qualified path. The result is that llvm ends up in a different directory to the one that the [staging `.tgz` creation rule expects](https://github.com/JuliaLang/julia/blob/master/deps/tools/common.mk#L156).

e.g. `llvm-config` is staged to:
```
/var/task/var/src/julia/usr-staging/llvm-3.9.1/build_Release/var/src/julia/usr/tools/llvm-config
```
It should be:
```
/var/src/julia/usr-staging/llvm-3.9.1/build_Release/var/src/julia/usr/tools/llvm-config
```

I've worked around the problem with [this patch to set `DESTDIR=""` when running `cmake_install.cmake`](https://github.com/samoconnor/AWSLambda.jl/blob/master/docker/lambdajlbase/llvm.mk.patch).

**Comment by o01eg** [comment]
It causes error on gentoo https://bugs.gentoo.org/675326

**Comment by vtjnash** [comment]
Apparently patched downstream only now?? If only Julia was an open-source project that could somehow accept patches....
