### ISSUE TITLE
Subtyping test slows code down

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#23465]
On 0.6.0,

```julia
@generated function foo(x)
    return Nullable{Int}
end

function my_return_type(expr_type::Type)
    t = foo(expr_type)
    t <: Nullable
    return t
end

@btime my_return_type($Int)
  181.774 ns (0 allocations: 0 bytes)
```

Without the `t<:Nullable` line, it takes less than a nanosecond. It seems to me that the subtyping test should be computable at compile-time, since both of these functions are type-stable.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaCI/BenchmarkTools.jl/issues/71
