### ISSUE TITLE
Do string interpolation in non standard string representations

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/julia#23481]
It would be nice to do something like the following.

```julia
macro d_str(str)
    quote
        $str
    end
end

x = "world"

d"hello $x"
# Currently returns -> "hello \$x"
# Should return     -> "hello world"
```

Thoughts?

**Comment by yuyichao** [comment]
I'm pretty sure we've decided against it since you can already do that by parsing the string and it is very useful for string macros to be able to use the `$` syntax for something else.

**Comment by KristofferC** [comment]
e.g. LaTeXStrings.

**Comment by Keno** [comment]
Yeah what @yuyichao said. This used to work this way, but it was decided to let the macros handle interpolation themselves.

**Comment by StefanKarpinski** [comment]
You can get almost all of the behavior of normal strings except for using string literal syntax inside of the interpolated expression. That requires being built into the parser.

**Comment by kdheepak** [comment]
Thanks for the replies everybody. If I understand correctly, the recommended way to go about this is as follows:

```julia
macro d_str(str)
    try
        str = eval(parse(string(""" "$str" """)))
    catch exception
        error(string("syntax: ", exception.msg))
    end
    return str
end

x = "world"

d"hello $x"
# returns -> "hello world"
```

Would this be an acceptable approach? Is there something else you'd recommend instead of the `try/catch` block?
