### ISSUE TITLE
Printing of failed factorizations

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#23508]
Noticed this when trying to show a failed Cholesky factorization:
```julia
julia> cholfact(rand(2,3))
Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
Error showing value of type Base.LinAlg.Cholesky{Float64,Array{Float64,2}}:
ERROR: DimensionMismatch("matrix is not square: dimensions are (2, 3)")
Stacktrace:
[...]
```
I think we should not try to print the factors if the factorization failed, this is what we have now:
```julia
julia> lufact(zeros(2,2))
Base.LinAlg.LU{Float64,Array{Float64,2}} with factors L and U:
[1.0 0.0; 0.0 1.0]
[0.0 0.0; 0.0 0.0]
successful: false

julia> cholfact(zeros(2,2))
Base.LinAlg.Cholesky{Float64,Array{Float64,2}} with factor:
[0.0 0.0; 0.0 0.0]
successful: false
```
I propose we instead print something like:
```julia
julia> lufact(zeros(2,2))
Failed factorization of type Base.LinAlg.LU{Float64,Array{Float64,2}}.

julia> cholfact(zeros(2,2))
Failed factorization of type Base.LinAlg.Cholesky{Float64,Array{Float64,2}}.
```
because the failed factors are not even useful.

**Comment by fredrikekre** [comment]
And I guess we should then remove the printing of `successful: true`; if the factors are printed it will be implicit that the factorization was successful.

**Comment by KristofferC** [comment]
I think it is good to highlight that the factorization failed.

**Comment by andreasnoack** [comment]
I think we should throw on non-square input. That is almost surely caused by a programming error.

**Comment by andreasnoack** [comment]
...but I also think changing the printing to suppress the factors when the factorization has failed is a good idea.
