### ISSUE TITLE
julia-0.6.0-linux-x86_64.tar.gz downloads Version 0.4.5 

### ISSUE THREAD

**Issue by mirisr** [JuliaLang/julia#23512]
I'm trying to instill the latest version of julia on my Ubuntu machine. It installs fine, but when I run the 'julia' command in my terminal, it shows up at Version 0.4.5. 

My Machine is ubuntu 16.04 LTS
OS type 64-bit

**Comment by ararslan** [comment]
Hey @mirisr, thanks for the report. What's the full URL of the download you're using? The correct URL should be https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz.

**Comment by mirisr** [comment]
The URL looks correct: https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz

and that's the file that is downloaded. Everything in there looks like it is version 0.6

I didn't have julia installed in the machine before
`which julia` gives me `/usr/bin/julia/`
![screenshot from 2017-08-30 14-58-21](https://user-images.githubusercontent.com/3237465/29894821-0b561d62-8d94-11e7-9d72-5ad706b1474e.png)

**Comment by PallHaraldsson** [comment]
Right @mirisr 

I find it hard to believe that
 
https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.0-linux-x86_64.tar.gz

that I just downloaded from the "Downloads" page is actually 0.4.5. I just downloaded it and decompressed by clicking the file (you can in the GUI file manager or use the shell tools if you know):

then:

julia-903644385b/bin/julia

works.

Note, /usr/bin/julia/ doesn't I guess you must have installed an older version earlier. You need not use julia from that location, but it's in PATH.

**Comment by PallHaraldsson** [comment]
Note there's also JuliaPro at juliacomputing.org and it has an install script.

**Comment by mirisr** [comment]
You're completely right, `julia-903644385b/bin/julia` works.... I can work from there! Thanks!

**Comment by fredrikekre** [comment]
Some relevant instructions here https://julialang.org/downloads/platform.html

**Comment by mirisr** [comment]
@fredrikekre That's exactly where I looked to install julia.
