### ISSUE TITLE
Defining a struct inside a struct succeeds

### ISSUE THREAD

**Issue by jmert** [JuliaLang/julia#23518]
Without any reason for why I tried this beyond thinking, "C can declare anonymous struct elements...", I realized that the following succeeds without throwing an error. I'm not sure what I really expected — probably either a parse error or for the inner types to have been ignored. I thought I'd just point it out since a quick attempt at searching for "inner struct" or "nested immutable" didn't obviously return any related issues.

```julia
julia> struct outer
         struct inner
           a
         end
       end

julia> mutable struct mouter
         mutable struct minner
           a
         end
       end

julia> fieldnames(outer)
0-element Array{Symbol,1}

julia> fieldnames(inner)
1-element Array{Symbol,1}:
 :a

julia> fieldnames(mouter)
0-element Array{Symbol,1}

julia> fieldnames(minner)
1-element Array{Symbol,1}:
 :a
```

```julia
julia> versioninfo()    
Julia Version 0.6.0     
Commit 903644385b* (2017-06-19 13:05 UTC)      
Platform Info:          
  OS: Linux (x86_64-pc-linux-gnu)              
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64         
  BLAS: libblas         
  LAPACK: liblapack     
  LIBM: libm            
  LLVM: libLLVM-4.0.0 (ORCJIT, skylake)        
```

**Comment by mauro3** [comment]
In that case the scope-docs are wrong, https://docs.julialang.org/en/v1/manual/variables-and-scoping/ top-table, which suggest that structs are only allowed in global scope.  But they seem to be allowed in all local scopes except those of functions and macros.
