### ISSUE TITLE
implement `union!`, `intersect!`, `setdiff!` for non-sets

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23524]
We already have the mutating set operators for `Set` objects, but they make sense for vectors as well, which have the non-mutating versions already. The mutating operations should work on vectors as well.

**Comment by Vaibhavdixit02** [comment]
I would like to work on this issue, is it still up for grabs?

**Comment by rfourquet** [comment]
I have been working on this already in the last couple weeks, as a complentary PR to #23528 (that's why I assigned myself here).

**Comment by rfourquet** [comment]
@Vaibhavdixit02 If you feel like reviewing, please check #23528.

**Comment by rfourquet** [comment]
Closed by #23528.
