### ISSUE TITLE
gmtime_r not found, so UT is wrong

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#23540]
The C/C++ Standard Library function `gmtime_r` had been accessible using `ccall`.      
That no longer works: *ERROR: ccall: could not find function gmtime_r*. 
  
It is a known that one cannot correctly and consistently determine UT (leap second agnostic UTC)  given the host local time and all other C Library time functions.  Today I tried to update my universal time code,, and discovered this issue.

**Comment by lobingera** [comment]
If you know it's in a standard library and installed everywhere, why don't you just call with the proper reference?

**Comment by JeffreySarnoff** [comment]
What would that be?  I do not know where (or that) the C Standard library is installed on your machine.
I meant that having access to that function, as had been the case through libc.jl, should not be optional.

**Comment by lobingera** [comment]
One of the nicer properties of the ccall implementation is:  libraries can be found by name only. See the clock/libc example in https://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/ and there is also https://docs.julialang.org/en/stable/stdlib/libdl/#Base.Libdl.dlopen

So if you are sure it's in a reasonable C standard, you should be able to find.

**Comment by JeffreySarnoff** [comment]
The (stable) docs give this example    
```
As a complete but simple example, the following 
calls the clock function from the standard C library:

julia> t = ccall((:clock, "libc"), Int32, ())
2292761
```

when I type that to the Repl (v0.6 and v0.7dev, win)
```
julia> t = ccall((:clock, "libc"), Int32, ())
ERROR: error compiling anonymous: could not load library "libc"
The specified module could not be found.
```

**Comment by rfourquet** [comment]
But `ccall(:clock, Int32, ())` works for me.

**Comment by JeffreySarnoff** [comment]
me too

**Comment by JeffreySarnoff** [comment]
with some digging, I see that localtime_r is in libjulia -- please [re]put gmtime_r there.

**Comment by JeffreySarnoff** [comment]
(I scanned all the libraries in Julia subdirectories, none held gmtime_r)

**Comment by yuyichao** [comment]
If it's in libc, `ccall(:gmtime_r)` should work, if not there's nothing we can do about it.

**Comment by jmert** [comment]
> I scanned all the libraries in Julia subdirectories, none held gmtime_r)

That's because they shouldn't. `libjulia` is dynamically linked to `libc` — which should be in your system's lib directory — so you'll find it there:

(On my Arch machine:)
```shell
$ nm -D /usr/lib/libjulia.so | grep gmtime_r
$ ldd /usr/lib/libjulia.so | grep libc.so | awk '{print $3;}'
/usr/lib/libc.so.6
$ nm -D /usr/lib/libc.so.6 | grep gmtime_r
00000000000aae90 T __gmtime_r
00000000000aae90 W gmtime_r
```

And my tests using the following code work both on v0.6 and master:
```julia
julia> struct tm
         sec::Int32
         min::Int32
         hour::Int32
         mday::Int32
         mon::Int32
         year::Int32
         wday::Int32
         yday::Int32
         isdst::Int32
       end

julia> tm() = tm(zeros(Int32,9)...)
tm

julia> const Ctime_t = Csize_t
UInt64

julia> timep = Ctime_t(trunc(Dates.datetime2unix(now())))
0x0000000059a90edd

julia> res = tm()
tm(0, 0, 0, 0, 0, 0, 0, 0, 0)

julia> ccall(:gmtime_r, Ref{tm}, (Ref{Ctime_t}, Ref{tm}), timep, res)
Base.RefValue{tm}(tm(13, 40, 7, 1, 8, 117, 5, 243, 0))
```

You probably need to debug some other issue with your system.

**Comment by JeffreySarnoff** [comment]
ok -- thanks
