### ISSUE TITLE
argument order of several-argument A[t|c]_mul_B[t|c]! signatures

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#23552]
Some `A[t|c]_mul_B[t|c][!]` signatures involving several arguments have said arguments ordered in the style of BLAS/LAPACK rather than Julia, for example
```julia
A_mul_B!(α::Number, A::SparseMatrixCSC, B::StridedVecOrMat, β::Number, C::StridedVecOrMat)
```
Such method signatures could perhaps use revision. See https://github.com/JuliaLang/julia/pull/20053#discussion_r96290616 and https://github.com/JuliaLang/julia/pull/20053#discussion_r96290778 for the discussion that precipitated this issue. Best!

**Comment by StefanKarpinski** [comment]
Ideally, we'll be deleting these functions entirely in 1.0.

**Comment by andreasnoack** [comment]
@StefanKarpinski I assume you are referring to the transposed type that would make it possible to get rid of the `Ax_` and `_Bx` parts. However, the signature problem will remain for the new `mul!` function.

This is a dup of #9930.

**Comment by Sacha0** [comment]
Thanks for the ref Andreas! :)
