### ISSUE TITLE
qrfact docs and help need to be corrected

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/julia#23560]
The docs and help on `qrfact` and its variants say that I can use the following command `qrfact(A, pivot=Val{true})` but in fact `qrfact` does not accept keyword arguments as shown in the error thrown `ERROR: function qrfact does not accept keyword arguments`. `qrfact(A, Val{true})` works and so the [docs](https://docs.julialang.org/en/stable/stdlib/linalg/#Base.LinAlg.qrfact) and help should be corrected. This happens on both v0.6 and v0.7.

**Comment by fredrikekre** [comment]
That notation specifies a default value for `pivot`, it is not a keyword argument.

**Comment by mohamed82008** [comment]
I see, thanks for pointing that out.

**Comment by fredrikekre** [comment]
See also #4902
