### ISSUE TITLE
Syntax ambiguity when range is used in ternary operator

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#23599]
The following code produces unexpected output:
``` Julia
julia> true ? 1:3 : 4:7
1
```
of course, it can be fixed by adding braces:
``` Julia
julia> true ? (1:3) : (4:7)
1:3
```
However, I still think it should be deprecated for the same reason that
1.+2 [was deprecated](https://github.com/JuliaLang/julia/issues/19089). Especially, in light of the fact that it produces erroneous output.

**Comment by ararslan** [comment]
This is actually expected, since ternaries are parsed more eagerly than ranges. You can see what's actually happening by inspecting the output of `parse`:
```
julia> parse("true ? 1:3 : 4:7")

WARNING: deprecated syntax "true ? 1:".
Use "true ? 1 :" instead.

WARNING: deprecated syntax "true ? 1 :3".
Use "true ? 1 : 3" instead.
:(if true
        1
    else
        3:4:7
    end)
```
That is, the precedence is `(true ? 1 : (3:4:7))`.

**Comment by AzamatB** [comment]
Which version is this? I don't get these warnings, in 0.6.

**Comment by GregPlowman** [comment]
I'm not sure it's erroneous output, but rather a case of parsing precedence.
Presumably it is parsed as:
true ? 1 : (3:4:7)
which is valid syntax.

**Comment by ararslan** [comment]
The output I posted was from the current master, but the parsing is the same across all Julia versions (or at least 0.3-0.7—I don't have 0.2 or lower installed).

**Comment by AzamatB** [comment]
Can you confirm that these warnings don't show up in 0.6?

**Comment by StefanKarpinski** [comment]
Yes – as a side effect of requiring space after `?` in ternary on master, we've also required spaces around the `:` in ternary, so this is now already a warning, forcing parens or spaces matching.
