### ISSUE TITLE
listenany and listen security bug

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#23607]
Documentation for listen states that it defaults to "listen on localhost only". The implementation, however, fails to get this right (and instead listens on all ports)

**Comment by Keno** [comment]
I believe the history of this is that incorrect documentation got written for this function. Of course that may make this security sensitive now, since people may have relied on it. localhost does seem like a better default.

**Comment by StefanKarpinski** [comment]
This is definitely a security issue and should be fixed. If it breaks people's code, that's fine since their code may be opening their machines up to vulnerabilities. It's better to inconvenience people that get them hacked.
