### ISSUE TITLE
Cannot compile Julia 0.6 with libunwind 1.2.1 

### ISSUE THREAD

**Issue by kzapfe** [JuliaLang/julia#23615]
I am pretty sure this is a bug, but I am not completely sure if its Julia or libunwind the culprit here:

I am trying to compile the 0.6 Julia version but it fails with the following error:

```
from /usr/include/x86_64-pc-linux-gnu/libunwind-x86_64.h:129:0,
                 from /usr/include/x86_64-pc-linux-gnu/libunwind.h:25,
                 from /usr/include/libunwind.h:10,
                 from /var/tmp/portage/dev-lang/julia-0.6.0/work/julia-0.6.0/src/julia_internal.h:642,
                 from /var/tmp/portage/dev-lang/julia-0.6.0/work/julia-0.6.0/src/dlload.c:11:
/var/tmp/portage/dev-lang/julia-0.6.0/work/julia-0.6.0/src/julia_internal.h:646:35: error: floating constant in preprocessor expression
        (UNW_VERSION_MAJOR == 1 && UNW_VERSION_MINOR > 1))
```

It looks like it interpreting the condicional there as a floating number where it should be an integer? If I read it correctly, it looks like a contradiction. Should unwind be at the same time equals to 1 and bigger than 1? 

I am on a GNU/Linux machine (gentoo) with kernel  4.10.4 and gcc 5.4.

**Comment by yuyichao** [comment]
It's an upstream bug. Should be fixed in the next release https://github.com/libunwind/libunwind/issues/30

**Comment by kzapfe** [comment]
Thanks, yuyichao.  I'll go and bother there, then.

**Comment by yuyichao** [comment]
It's unclear when they want to release 1.2.2 (or whether this is seen as a big enough issue to make a release) but what you can also do in the meantime is to let your distro patch the package. See the linked nixos PR in that issue.

**Comment by jirutka** [comment]
BTW, @yuyichao, what about using [LLVM’s libunwind](https://github.com/llvm-mirror/libunwind) instead of GNU’s one? Have you tried it with Julia?

**Comment by yuyichao** [comment]
ACAICT more distro ships the GNU libunwind so we'll not switch away from using it as default unless that changes. The GNU libunwind is having a maintainer again and I don't see switching to the LLVM one has a clear advantage. AFAICT the LLVM one is specifically for C++ and is less willing to take guess when unwind info isn't available.

It's certainly fine to make our code compatible with LLVM's libunwind if anyone is interested of course.

**Comment by jirutka** [comment]
Alpine Linux ships both. However, we don’t have any specific reason to switch to LLVM’s libunwind, it was just an idea that _maybe_ it may be better for Julia.

I’ve already patched that silly bug in GNU libunwind and currently finishing upgrade of the julia package to 0.6.0.
