### ISSUE TITLE
require explicit `rng` for seeded use

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23624]
In other words, hide the implementation of the default RNG behind an opaque `DefaultRNG` type and do not allow it to be seeded. Thus, if you want reproducible sequences, you *have* to pass an RNG object around. Benefits:

1. Would allow changing the default RNG in the future without breaking user code.

2. Makes it completely explicit which code depends on the reproducible sequence. This is often unclear in test files where some seed is set and then *everything* after that is affected by that seeding, but only some of the tests actually depend on the seed. With this change, the pattern would be to write `let rng = MersenneTwister(1234)` and then have a block that uses that `rng`.

3. Has some potential benefit for threaded use of `rand()` without an explicit RNG argument since there's no way (unless the RNG is badly broken) to distinguish between a single shared default RNG, an RNG per task, or an RNG per thread – or whatever other scheme we care to implement.

The drawback, of course, is that you can't get reproducible random numbers without explicitly passing an RNG object around.

**Comment by malmaud** [comment]
I definitely understand the motivation and think it's in general good practice to do this for serious libraries and test code, but I'm against making it required because it penalizes quick interactive workflows too harshly.

I often code up quick simulations in my interactive workflows where I enjoy the convenience of setting the seed so my simulations are deterministic within the the few days I'm using it and would find it a burden to have to be explicit with the RNG object in those scenarios. I suspect others involved in running Monte Carlo scripts in Julia (which Julia's JIT makes it very appealing for in general) might have similar sentiments.

**Comment by StefanKarpinski** [comment]
What about making a `DefaultRNG` type that mixes given seeds with new random values in each session so that you can't write code that relies on a particular behavior for a given seed? That would seem to preserve most of the convenience without the risk of lock-in. It doesn't address help the threading case much, but it could be documented that mixing threading and seeding of the default RNG will cause unpredictable results.

**Comment by malmaud** [comment]
What is a 'session'? Do you mean starting a new Julia process, and calling it with the same `srand`, will deliberately not give the same sequence? If so, I still that's needlessly patronizing to scientific end users.

**Comment by oscardssmith** [comment]
Yes. The reason this is desirable is it makes the sequence of numbers produced by the default RNG unstable, which allows the algorithm to change between versions without possibility of breaking code. By making the numbers change, we make the default RNG for people who want ¨Randomness" and specific ones for people who want specific, reproducible pseudo random sequences of numbers

**Comment by StefanKarpinski** [comment]
We can partly address this issue by having people do `using MersenneTwisterRNG: srand, rand`. That works fine if you only want to seed an RNG and call `rand`. Where it falls apart is if you want to use `Distributions`, for example, which uses Base's default RNG in various situations to generate random samples from distributions and exposes that functionality through other exported generic functions. Perhaps the best we can do is vehemently document that the default RNG may change and that if you need long-term reproducible random sequences, you *must* construct and pass around an RNG.

**Comment by malmaud** [comment]
Yes, I'm very on board the 'vehemently document' train. Could also be a linter warning in an aggressive linting mode.

**Comment by malmaud** [comment]
If this change happens (against my preferences), it needs to be made to work with Distributions.jl or many people will be unhappy.

**Comment by rofinn** [comment]
@malmaud Distributions.jl already has problems with rngs because it still depends on several R implementations.

**Comment by StefanKarpinski** [comment]
Ok, I guess we can just vehemently document that the default RNG may change in the future.

**Comment by rfourquet** [comment]
I think I would be rather against this change, which feels too "patronizing" as has been said. In a recent workflow working on improving Primes.jl, which doesn't allow using a non-default RNG, it was very useful to seed the default RNG on two different julia sessions, one with the master branch from Primes.jl, another one with my work-in-progress, to compare performance (which depend excessively on the state of the RNG). So in this use case "making a DefaultRNG type that mixes given seeds with new random values in each session" would not work, but mixing seeds with the sha1 of the julia version would be fine; still there will probably be more use cases where this is not enough, and where it would feel like an unnecessary restriction.

For point 2 in the OP, concerning tests (in base at least), I had a couple PRs addressing this which I started updating recently.
