### ISSUE TITLE
Windows segfault involving promote_typeof

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#23633]
More a breadcrumb so I can investigate whenever I can get a windows box w/ current master on it.

Noticed in a DataFrames pull request CI run on appveyeor, both [32-bit](https://ci.appveyor.com/project/nalimilan/dataframes-jl/build/1.0.345/job/c2f1nb9a8raiu6wa) and [64-bit](https://ci.appveyor.com/project/nalimilan/dataframes-jl/build/1.0.345/job/73lqif8lu6f9ahhv).

The offending test seems to be:
```julia
@test DataFrame([Union{Int, Null}[1, 2, 3], Union{Float64, Null}[2.5, 4.5, 6.5]],
                    [:A, :B]) ==
        DataFrame(A = Union{Int, Null}[1, 2, 3], B = Union{Float64, Null}[2.5, 4.5, 6.5])
```
and I'm guessing the promote_typeof error is coming specifically from:
```julia
[Union{Int, Null}[1, 2, 3], Union{Float64, Null}[2.5, 4.5, 6.5]]
```

**Comment by KristofferC** [comment]
Reopen if this is still a problem.
