### ISSUE TITLE
docs.julialang.org Navigation bar scrolls to top on clicking an entry

### ISSUE THREAD

**Issue by halirutan** [JuliaLang/julia#23660]
The official online documentation consists of a navigation menu on the left and the content on the right

![doc](http://i.imgur.com/5aW1NnS.png)

Whenever you click on one of the main entries that is farther down the navigation menu (e.g. "Essentials") the page loads in the content area, but then the navigation bar scrolls right back to the top.

This does not happen if you click an item that is on the level 2 of the navigation! Can this be fixed?

My system is Linux with a Chrome browser and the behaviour was verified by a second user.

**Comment by vchuravy** [comment]
Julia uses [`Documenter.jl`](https://github.com/JuliaDocs/Documenter.jl) for generating the docs, could you fill an issue there for this?

**Comment by halirutan** [comment]
Done! https://github.com/JuliaDocs/Documenter.jl/issues/564

**Comment by vchuravy** [comment]
Thank you!
