### ISSUE TITLE
xcorr with complex vector

### ISSUE THREAD

**Issue by caffery-chen** [JuliaLang/julia#23662]
It seems there is a problem in the the xcorr when dealing with complex vector .

I am expecting to see a peak when I do the following:

val = xcorr(x,x)
figure(1)
plot(abs.(val))

however it is not as expected. I have to manually conjugate the second vector then the results is correct.
val = xcorr(x,conj(x))
figure(1)
plot(abs.(val))

conclusion would be in the current xcorr function, there is no conjugation implemented for the 2nd input vector.

**Comment by KristofferC** [comment]
`xcorr` is no longer in Base but has been moved to https://github.com/JuliaDSP/DSP.jl so the issue should be reopened there.

The definition is at https://github.com/JuliaDSP/DSP.jl/blob/3b9aad80c0635072c949b1b2671458f90a5f5997/src/dspbase.jl#L193 and it seems there is indeed no conjugation.
