### ISSUE TITLE
QuoteNode, LineNumberNode leaking into macros

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#23661]
```julia
julia> macro foo(ex)
           dump(ex)
       end
@foo (macro with 1 method)

julia> @foo :x
QuoteNode
  value: Symbol x

julia> @foo begin
           1
           2
       end
Expr
  head: Symbol block
  args: Array{Any}((4,))
    1: LineNumberNode
      line: Int64 2
      file: Symbol REPL[12]
    2: Int64 1
    3: LineNumberNode
      line: Int64 3
      file: Symbol REPL[12]
    4: Int64 2
  typ: Any
```

The behavior here is different than the previous behavior of passing these in as `Expr(:quote)` and `Expr(:line)`. If this is an intended change (which would be unfortunate, in my opinion), then it should be documented in NEWS.

**Comment by TotalVerb** [comment]
Probably related to https://github.com/JuliaLang/julia/pull/23533, cc @vtjnash

**Comment by vtjnash** [comment]
essentially a dup of https://github.com/JuliaLang/julia/issues/15310

**Comment by kmsquire** [comment]
Except that, presumably, #15310 didn't [cause breakage in DataStructures.jl](https://github.com/JuliaCollections/DataStructures.jl/issues/327#issuecomment-328404193)?

**Comment by JeffBezanson** [comment]
I don't think it's a dup; that was about expressions returned from macros, while this is a change in what we pass to macros.

**Comment by JeffBezanson** [comment]
After exploring this, it seems we've been using QuoteNode and LineNumberNode quite a bit. Trying to eliminate them from macro arguments actually required more code changes, so we'll keep the new behavior. It's in the ast devdocs, but the summary is that `QuoteNode` is used for quoted atoms (e.g. symbols) and `LineNumberNode` is used for all line number info.
