### ISSUE TITLE
Delay fatality of Travis tests

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#2367]
Is there a way we can make a best effort to run all the tests, even if a test fails? Instant fatality means that unrelated tests to a patchset can prevent the patchset from getting appropriate test coverage.

**Comment by IainNZ** [comment]
@tkelman you just did the opposite of this right, fail-fast?

**Comment by tkelman** [comment]
Ref #12387. That was more about the situation where you open a branch or PR and push a bunch of commits to it in rapid succession. It's easier on the Travis and AppVeyor queues to not bother building the redundant builds there when something newer is queued for the same PR/branch.

I think this PR is more about the test framework itself, like your #9398. So if there are multiple problems with a commit, may as well run the tests to completion to find out about all of them at once.

**Comment by vtjnash** [comment]
I think we can call this resolved by #10835 and testsets (e.g. #13470). Eventually, we may want testfiles to adopt `@testset` to increase their granularity, but that can be done incrementally and may require performance fixes first (#15346).
