### ISSUE TITLE
inconsistency in docs or implementation of sprand

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#23672]
>   sprand([rng],[type],m,[n],p::AbstractFloat,[rfn])
>
>  Create a random length m sparse vector or m by n sparse matrix, in which the
  probability of any element being nonzero is independently given by p (and
  hence the mean density of nonzeros is also exactly p). Nonzero values are
  sampled from the distribution specified by rfn and have the type type. The
  uniform distribution is used in case rfn is not specified. The optional rng
  argument specifies a random number generator, see Random Numbers.

```
julia> sprand(Int, 2,2, 0.5)
2×2 SparseMatrixCSC{Int64,Int64} with 1 stored entry:
  [2, 1]  =  4741737022034175226

julia> sprand(Void, 2,2, 0.5)
ERROR: MethodError: no method matching rand(::MersenneTwister, ::Type{Void})
Closest candidates are:
  rand(::AbstractRNG, ::Type, ::Tuple{Vararg{Int64,N}} where N) at random.jl:371
  rand(::AbstractRNG, ::Type, ::Integer, ::Integer...) at random.jl:372
  rand(::MersenneTwister, ::Type{I<:Base.Random.FloatInterval}) where I<:Base.Random.FloatInterval at random.jl:138
  ...
Stacktrace:
 [1] rand!(::MersenneTwister, ::Array{Void,1}) at ./random.jl:379
 [2] sprand(::MersenneTwister, ::Int64, ::Int64, ::Float64, ::Base.SparseArrays.##9#10{Void}, ::Type{Void}) at ./sparse/sparsematrix.jl:1286
 [3] sprand(::Type{Void}, ::Int64, ::Int64, ::Float64) at ./sparse/sparsematrix.jl:1306
```
(yes, I actually have a valid use case for a sparse matrix of `Void`.)

**Comment by sbromberger** [comment]
I think part of the issue is that there is no `zero(Void)`. I'm not sure how to do this but I suppose it's going to be really difficult to do what I want to do with the `SparseMatrixCSC` type, so I'll close this out.

**Comment by yuyichao** [comment]
What was inconsistent about the doc? It didn't say explicitly how it creates the sample but it did say it need to do that using `rfn`.

**Comment by sbromberger** [comment]
The doc says that `rfn` is optional.

**Comment by yuyichao** [comment]
It **is** optional?

**Comment by sbromberger** [comment]
yeah, I guess the failure is in `rand`. Never mind.
