### ISSUE TITLE
Inference (correctness) regression

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#23685]
Reduced from `DataStructures.jl` test failure. The following code causes a incorrect `Union{}` inference and crashes at runtime. On 0.6, the inference result for `update!` also seems wrong but the one for `f()` is somewhat correct and doesn't crash...

```julia
struct Node{T}
end
@inline function update!(::Node{T}) where T
    convert(Node{T}, Node{Float64}())
end
h = Node{Float64}()
# h = Node{Int}()
f() = update!(h)
code_warntype(update!, Tuple{Any})
@code_warntype f()
f()
```

Output on master
```
Variables:
  #self# <optimized out>
  #unused# <optimized out>

Body:
  begin
      return (Main.convert)((Core.apply_type)(Main.Node, $(Expr(:static_parameter, 1)))::TYPE{NODE{_1}} WHERE _1, $(QuoteNode(Node{Float64}())))::UNION{}
  end::UNION{}
Variables:
  #self# <optimized out>

Body:
  begin
      return (Main.update!)(Main.h)::UNION{}
  end::UNION{}
Unreachable reached at 0x7f14e2314c92
```

Could be related to https://github.com/JuliaLang/julia/issues/23675

**Comment by JeffBezanson** [comment]
Might have been caused by #23643. In 0.6 we had

```
julia> (Tuple{Type{Node{T}} where T, Node{Float64}})  <:  Tuple{Type{T},T} where T
true
```

which is wrong. #23643 fixed that, but that bug was covering for intersection giving `Union{}` for this type (both before and after #23643).
