### ISSUE TITLE
doc: wrong reference link in manual/style-guide.md

### ISSUE THREAD

**Issue by iblis17** [JuliaLang/julia#23689]
https://docs.julialang.org/en/latest/manual/style-guide/#Do-not-write-x-f(x)-1

The link of `map` refers to libgit2.

**Comment by StefanKarpinski** [comment]
Even more concerning is that `LibGit2.map` is listed as `Base.map` here:

https://docs.julialang.org/en/latest/devdocs/libgit2/#Base.map-Tuple{Function,Base.LibGit2.GitRevWalker}

Also, what's up with that URL fragment specifier?

**Comment by laborg** [comment]
Has been fixed.
