### ISSUE TITLE
Move FileWatching into stdlib

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23715]
This is base/poll.jl and test/pollfd.jl. This code calls into libuv, but I believe it still makes sense to separate it since it's self-contained and has been a bit fussily platform-dependent.

**Comment by timholy** [comment]
The only reason I can think of not to do this would be if we decided to move Revise to base. But I think #23448 would make that unnecessary. And my experience trying to support OSX leads me to agree with the "fussy" and "platform-dependent" part.
