### ISSUE TITLE
Rename realmin -> realabsmin?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#23710]
Potentially confusing:
```julia
julia> typemax(Float32)
Inf32

julia> typemin(Float32)
-Inf32

julia> realmax(Float32)
3.4028235f38

julia> realmin(Float32)
1.1754944f-38
```

**Comment by timholy** [comment]
Or maybe: `typemax` -> `maxtype` and `realmax` -> `maxabsfinite`

**Comment by pablosanjose** [comment]
How about `positivemax` and `positivemin`?

**Comment by TotalVerb** [comment]
It's also not the minimal representable positive value. I don't think there's a good term for this.

**Comment by TotalVerb** [comment]
For `typemax` and `typemin`, I wonder if folding into `maximum` and `minimum` make any sense (thinking of the type as a set, of sorts).

For `realmax` and `realmin`, correct terms might be `maxabsnormal` and `minabsnormal`.

**Comment by alyst** [comment]
Another alternative:
* `typemax()`/`typemin()` -> `maxfinite()`/`minfinite()` (`maximum()`/`minimum()` might be confusing because of `Inf`)
* `realmax()`/`realmin()` -> `maxposnormal()`/`minposnormal()` (to match with `isposdef()`)

**Comment by TotalVerb** [comment]
Note

```julia
julia> typemax(Float64)
Inf
```

**Comment by oscardssmith** [comment]
These are renamed and further renaming can't happen in 1.x.
