### ISSUE TITLE
Move SharedArrays to a package

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23713]
Nothing in Base depends on this, it's pretty self-contained and should be easy to move.

Part of #5155.

**Comment by tknopp** [comment]
@JeffBezanson: Great that you are pushing this. To make the transition smoothly it would IMHO be great to have 5-10 metapackages that just reexport a larger set of packages. Think about this as "toolboxes" in Matlab. For instance a "Parallel.jl" package could be the home for all parallel computing stuff (i.e. Shared Arrays) If you promote these metapackages people will not have issues discovering them. We could even have in Julia a function 

```
list_recomended_metapackages()
```
My proposal in #5155 was to install them by default but nowadays I am not sure if this is really required.

**Comment by ChrisRackauckas** [comment]
>If you promote these metapackages people will not have issues discovering them. We could even have in Julia a function

I think it would be better if this was just formalized as part of the package system. I.e. there are packages and metapackages (or toolboxes). If we end up doing a "curated METADATA" like people have been suggesting, then the recommended metapckages could just be those in the curated METADATA.

**Comment by KristofferC** [comment]
Was at least moved to stdlib in https://github.com/JuliaLang/julia/pull/23931

**Comment by ararslan** [comment]
Let's keep this open to remember to move it out of the repo entirely. Though not urgent.

**Comment by ViralBShah** [comment]
Seems like we should be able to close this, since we have a whole bunch of such things in `stdlib`.

**Comment by StefanKarpinski** [comment]
Yes, shared arrays is already in stdlib so this seems to be done. Is there anything else to do?

**Comment by ararslan** [comment]
There's nothing else to do if we intend to keep it in the repo. I generally assume that the stdlib in this repo is like a holding ground for things that will be moved to packages in other organizations, so I kept this open to track its complete removal from the repo. If that's not the plan then this can just be closed.

**Comment by ViralBShah** [comment]
I think we have been closing the others. I am in favour of closing. If necessary, when we start the move out of stdlib, we can have an issue to discuss that. Perhaps they can all be moved out in one shot, since a lot of the detangling work will be done.

**Comment by StefanKarpinski** [comment]
It's easy enough to keep track of things in `stdlib` that we might want to move out: `ls stdlib`. We may or may not end up wanting to move things from stdlib into standalone packages. I think that's a discussion for a future (post-1.0) time.
