### ISSUE TITLE
Tab completion causes ambiguity warning

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/julia#23736]
Tab completion causes an ambiguity warning for Main when two modules define the same symbol (intentionally).

This is an example of the behaviour (tab was pressed on the final line):

```
julia> module Bar1
          function foo()
             nothing
          end
          export foo
       end
Bar1

julia> module Bar2
          function foo()
             nothing
          end
          export foo
       end
Bar2

julia> using Bar1

julia> using Bar2

julia> Main.MWARNING: both Bar2 and Bar1 export "foo"; uses of it in module Main must be qualified
```
I have checked this happens with the latest nightly.

**Comment by wbhart** [comment]
This appears to be related to, or may even be the cause of #23677

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14787
