### ISSUE TITLE
broadcasting and multiple values

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#23734]
Sometimes it would be advantageous to broadcast functions which return multiple values, without creating intermediate arrays of tuples. Eg
```julia
f(x) = x, x+1
x = reshape(1:6,2,3)
@syntax_to_be_determined a, b = f.(x) # creating new arrays
a2 = similar(a)
b2 = similar(b)
a2, b2 .= f.(x) # in-place syntax is free, currently gives MethodError for broadcast!
```
so that
```julia
a == a2 == x
b == b2 == x.+1
```
would hold.

([short discussion in Discourse](https://discourse.julialang.org/t/destructuring-and-broadcast/5672/2))

**Comment by TotalVerb** [comment]
#22129

**Comment by mbauman** [comment]
Let's close this as a dup of #22129 — I think that captures the same idea.
