### ISSUE TITLE
Randstat Python micro benchmark is buggy.

### ISSUE THREAD

**Issue by lazarox** [JuliaLang/julia#23741]
https://github.com/JuliaLang/julia/blob/3b45cdc9aab03850ee57f52c7b2389723f0811e8/test/perf/micro/perf.py#L46-L52

Multiple bugs in this code, which is computing nothing like the reference Julia implementation... this also has effects on its speed. I'm surprised no one has noticed this in years.

Bug #1: loop goes from 1 to t-1. It should go from 0 to t. I.e., it should be range(t), not range(1,t).

Bug #2: the line concatenate((a, b, c, d))  concatenates the matrices _vertically_ whereas the original Julia code that this is supposed to mimic concatenates them _horizontally_. This makes a difference in the successive operations since P.T.dot(P) will be 20x20 in the Julia code, but is 5x5 in the Python code.

Bug #3: same thing for the next line, though it doesn't affect performance

Efficiency comment:
Use of matrix_power is a terrible idea. Something like trace(PTP.dot(PTP).dot(PTP).dot(PTP)) is much faster.

**Comment by lazarox** [comment]
```
def randmatstat(t):
    n = 5
    v = zeros(t)
    w = zeros(t)
    for i in range(t):
        a = randn(n, n)
        b = randn(n, n)
        c = randn(n, n)
        d = randn(n, n)
        P = concatenate((a, b, c, d),axis=1)
        Q = concatenate((concatenate((a, b),axis=1), concatenate((c, d),axis=1)),axis=0)
        PTP = dot(P.T,P)
        v[i] = trace(PTP.dot(PTP).dot(PTP).dot(PTP))
        QTQ = dot(Q.T,Q)
        w[i] = trace(QTQ.dot(QTQ).dot(QTQ).dot(QTQ))
    return (std(v)/mean(v), std(w)/mean(w))
```

This is the corrected version, in case anyone wants to turn it into a PR.

**Comment by ViralBShah** [comment]
@lazarox The purpose is to be idiomatic rather than have the fastest implementation. I think while the rest of it all looks good, we will probably want to retain the matrix power.

**Comment by StefanKarpinski** [comment]
Thanks for taking a look at that, @lazarox! We specifically avoid doing "hand optimization" like strength reducing `matrix_power` to a manual series of `dot` calls – e.g. there are other places where we don't change `x^2` to `x*x` intentionally, since measuring whether a runtime can do that sort of optimization is very much of interest from an implementation benchmarking perspective.

**Comment by lazarox** [comment]
`matrix_power` is properly implemented, but for such small matrices (n=5) its overhead is excessive.

However, I understand the motivation to use it in this specific benchmark.

**Comment by StefanKarpinski** [comment]
It would be great to get a PR for this and update the benchmarks (again).
