### ISSUE TITLE
BigFloat core if prec is changed

### ISSUE THREAD

**Issue by Liso77** [JuliaLang/julia#23745]
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3360M CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia> ff = BigFloat(1)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> ff.prec=1024
1024

julia> ff
/home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/get_str.c:153: MPFR assertion failed: size_s1 >= m

signal (6): Aborted
while loading no file, in expression starting on line 0
raise at /build/glibc-bfm8X4/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54
abort at /build/glibc-bfm8X4/glibc-2.23/stdlib/abort.c:89
mpfr_assert_fail at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/mpfr-gmp.c:305
mpfr_get_str_aux at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/get_str.c:153
mpfr_get_str at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/get_str.c:2518
regular_eg at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/vasprintf.c:1082
partition_number at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/vasprintf.c:1640 [inlined]
sprnt_fp at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/vasprintf.c:1708 [inlined]
__gmpfr_vasprintf at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/vasprintf.c:2031
mpfr_snprintf at /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/mpfr-3.1.5/src/printf.c:169
string at ./mpfr.jl:895
show at ./mpfr.jl:907
unknown function (ip: 0x7ffb1da9beb6)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
display at ./REPL.jl:122
unknown function (ip: 0x7ffb1da9bd86)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
display at ./REPL.jl:125
unknown function (ip: 0x7ffb1da9bad6)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
display at ./multimedia.jl:194
unknown function (ip: 0x7ffb1da9b992)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:75
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:242
eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:539
jl_toplevel_eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:511
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:571
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7ffb320c339f)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
print_response at ./REPL.jl:144
unknown function (ip: 0x7ffb321320f0)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
print_response at ./REPL.jl:129
unknown function (ip: 0x7ffb321317f0)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
do_respond at ./REPL.jl:646
unknown function (ip: 0x7ffb1da9ade1)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:75
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:242
eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:539
jl_toplevel_eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:511
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:571
jl_toplevel_eval_in at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:496
eval at ./boot.jl:235
unknown function (ip: 0x7ffb320c339f)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
run_interface at ./LineEdit.jl:1583
unknown function (ip: 0x7ffb321277bf)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
run_frontend at ./REPL.jl:945
run_repl at ./REPL.jl:180
unknown function (ip: 0x7ffb1da94282)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
_start at ./client.jl:413
unknown function (ip: 0x7ffb321056e8)
jl_call_fptr_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1933
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/ui/../src/julia.h:1424 [inlined]
true_main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:127
main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:264
__libc_start_main at /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x40170c)
Allocations: 1043265 (Pool: 1042170; Big: 1095); GC: 0
Aborted (core dumped)

**Comment by KristofferC** [comment]
This is not the way to change the precision, see https://docs.julialang.org/en/latest/manual/integers-and-floating-point-numbers/#Arbitrary-Precision-Arithmetic-1 and `setprecision`. Is changing the `precision` field documented anywhere?

**Comment by Liso77** [comment]
@KristofferC I am really surprised that this could be closed so easy. :) It could not be the way how to change precision (I just tried this way). And I don't complain that my way didn't work. I just think that it is definitely not normal behavior to **crash** whole Julia process!

**Comment by yuyichao** [comment]
This is treated as an unsafe operation since you are modifying data structures read by the underlying C library.

**Comment by Liso77** [comment]
@yuyichao sorry I am just starting to play with Julia. There is no possibility to make attribute readonly/private or at least "hidden" (invisible in tab completion) in Julia? In other words - there is no possibility to write BigFloat (or similar types) more foolproof?

**Comment by yuyichao** [comment]
In general, reading all fields are fine (code that do so can break due to internal changes) but writing to them are usually not fine. Private fields are pretty annoy in general.

**Comment by StefanKarpinski** [comment]
The general rule is that unless you know what you're doing, don't change the fields of some type. We could add some privacy controls on fields in the future, but there's nothing that anyone can't do because of the lack of such a feature, so it's not a high priority currently.

**Comment by Liso77** [comment]
Thanks all ( @KristofferC @yuyichao @StefanKarpinski ) for clarifying! :) I start to love this language. Julia has much bigger potential than to be "just" tool for scientists and possibility to write foolproof modules is IMHO quite important. But although I like to have "privacy controls on fields" in 1.0 I understand that decision what to include is much more complicated than I could currently comprehend. :) Just one humble proposal: If this feature is planned (maybe in 1.x) than it may be better to not close similar issues.  Move it to appropriate tag could help to track future improvements. Have a nice day! :)
