### ISSUE TITLE
Improve linreg documentation

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#23769]
Documentation for `linreg` should explain how to do multiple regression and probably shouldn't use `PyPlot`.

**Comment by alanedelman** [comment]
best to use `Plots`

**Comment by MatthiasKauer** [comment]
So, this issue is about adding another example for multiple regression and about replacing PyPlot.
By multiple regression you mean sth like $y = a + b1 x1 + b2 x2$ or do you have something more complicated in mind?
Is Plots a good replacement for PyPlot?

**Comment by fredrikekre** [comment]
I think we should remove the plotting completely, and just show the output of `linreg`.

**Comment by sblcook** [comment]
I'm interested in working on this. What should I do to get started?

**Comment by skylanskylion** [comment]
I'm interested in learning in Julia. where do I start?

**Comment by fredrikekre** [comment]
A good start would be to read https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md
