### ISSUE TITLE
Miscompilation on 0.6 for CSTParser

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#23766]
The example below works fine on 0.7 but I thought I would show it here just in case it started working "by accident".
This came up by trying to figure out an error that happened on only one of the Windows workers for a PR to CSTParser (but I can reproduce it locally on Ubuntu, https://ci.appveyor.com/project/ZacLN/cstparser-jl/build/1.0.98/job/088xxiaanjyxma44).

In short, by just observing a field in a struct (with `@show`) or adding a `@noinline`, the result of the function changes. 

What follows is a short description of the problem.

In CSTParser, the only way the function `parse_module` is called is from:

```
k = ps.t.kind
[....]  
    elseif k == Tokens.MODULE
        return parse_module(ps)
    elseif k == Tokens.BAREMODULE
        return parse_module(ps)
[...]
```
see, https://github.com/KristofferC/CSTParser.jl/blob/kc/rawtoken2/src/CSTParser.jl#L124-L127

Hence, upon entering the function`parse_module` we have the invariant that `ps.t.kind == Tokens.MODULE || ps.t.kind == Tokens.BAREMODULE`.

The very first statement in the `parse_module` function is:

```
kw = KEYWORD(ps)
```
see, https://github.com/KristofferC/CSTParser.jl/blob/kc/rawtoken2/src/components/modules.jl#L2 is.

This is a constructor that invokes:

```
struct KEYWORD
    kind::Tokenize.Tokens.Kind
    [...]
end
KEYWORD(ps::ParseState) = KEYWORD(ps.t.kind, [...])
```

From our previous established invariant of `ps.t.kind`, we **know** that the `.kind` field of the created `KEYWORD` must be `Tokens.MODULE` or `Tokens.BAREMODULE`.

However, when we run the code: `CSTParser.parse("module a() end", true)`, that ends up calling `parse_module`, we find that this `KEYWORD` is created with a `Tokens.IDENTIFIER` instead (which is the `kind` of the next token after `module`). This should be impossible.

Things that make the correct behavior appear:

* Prevent inlining of the `KEYWORD` constructor.
* Add a `@show kw.kind` to the `parse_module` function. "If you look at it, it works...".
* Run on 0.7.

To reproduce: check out the branch at https://github.com/KristofferC/CSTParser.jl/tree/kc/rawtoken2 and update `Tokenize` to master.
Run `CSTParser.parse("module a() end", true)`. The bugged version has a `CSTParser.KEYWORD(IDENTIFIER, 1, 1:6)` in the returned AST, which breaks the invariant in that the `kind` that says `IDENTIFIER` instead has to be a `MODULE` or`BAREMODULE`. My 0.6 commit is 4b967d4.

**Comment by ZacLN** [comment]
I'd add that I've encountered these sorts of errors before, always involving repeated nested calls

**Comment by KristofferC** [comment]
Obsolete.
