### ISSUE TITLE
`isnumber(::Number)` undefined

### ISSUE THREAD

**Issue by eveydee** [JuliaLang/julia#23767]
Is there a reason `isnumber(::Number)` is left undefined? There are a billion other ways to check for it, I guess, but it's a bit odd that it has only been defined as a function on `Char`. I don't have a good use case for it, just one of surprise that the function tab-completed but didn't do what I expected. And also that I define my own `isnumber` with `isnumber(::Number) = true`. Would be nicer just to extend the one in Base with my own types, so other people wouldn't have to overwrite my `isnumber` for their personal number types that for some reason don't inherit from `Number`.

**Comment by yuyichao** [comment]
What do you want it to do? It's for checking if a character is a number so do you want it to be `isnumber(::Number) = true` or `isnumber(a::Number) = isnumber(Char(a))`? Better to leave this undefined I think.

**Comment by StefanKarpinski** [comment]
Yes, it does what's documented, but the name makes this quite confusing. It should at the very least have a better name or be scoped to a string-specific module. There has previously been talk of folding all character class checks into a single function with an enum argument for the class.

**Comment by eveydee** [comment]
Sorry, yes, I would suggest `isnumber(::Number) = true`. I understand that it checks if a `Char` is in the number range, and there is nothing inherently wrong with the fact that it only does that, but it is a surprising behaviour. It's a bit like defining `ismatrix` to only check if a string parses into a `Matrix`.

**Comment by omus** [comment]
Maybe this should be renamed to `isnumeric`? I'm not sure `isnumber(::Number)` needs to be defined as you should be doing `isa(x, Number)` instead.

**Comment by yuyichao** [comment]
So this can be closed and any discussion about changing the name should go to https://github.com/JuliaLang/julia/issues/14347 where previous discussion is. It doesn't make sense to define `isnumber(::Number)`.

**Comment by nalimilan** [comment]
So let's reopen https://github.com/JuliaLang/julia/issues/14347? :-)
