### ISSUE TITLE
Crash when loading DataFrames w/ make debug

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#23768]
```julia
  likely near /Users/jacobquinn/.julia/v0.7/DataFrames/src/subdataframe/subdataframe.jl:8
WARNING: Base.Range is deprecated, use Base.AbstractRange{T} where T instead.
  likely near /Users/jacobquinn/.julia/v0.7/DataFrames/src/subdataframe/subdataframe.jl:8
WARNING: Base.Range is deprecated, use Base.AbstractRange{T} where T instead.
  likely near /Users/jacobquinn/.julia/v0.7/DataFrames/src/subdataframe/subdataframe.jl:8
Assertion failed: (callee->min_world <= caller->min_world && callee->max_world >= caller->max_world), function jl_method_instance_add_backedge, file /Users/jacobquinn/julia/src/gf.c, line 1327.

signal (6): Abort trap: 6
while loading /Users/jacobquinn/.julia/v0.7/DataFrames/src/subdataframe/subdataframe.jl, in expression starting on line 8
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 18405884 (Pool: 18404543; Big: 1341); GC: 28
ERROR: Failed to precompile DataFrames to /Users/jacobquinn/.julia/lib/v0.7/DataFrames.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:598
 [2] _require(::Symbol) at ./loading.jl:407
 [3] require(::Symbol) at ./loading.jl:318

```

**Comment by quinnj** [comment]
Currently blocked by https://github.com/JuliaLang/julia/issues/23456 (in that I can't get to loading `subdataframe.jl` using `julia-debug` since CategoricalArrays crashes first).

**Comment by quinnj** [comment]
Working around #23456, I'm now seeing the following assertion error on current DataFrames master
```
Assertion failed: (fptr.fptr != NULL), function jl_generate_fptr, file /Users/jacobquinn/julia/src/codegen.cpp, line 1385.
```
It seems to be right near the end of loading the entire package (i.e. it seems to load all the code correctly, but fails before fully returning).

**Comment by quinnj** [comment]
Ok, so the offending line is actually [here](https://github.com/JuliaData/DataFrames.jl/blob/8fd08510606badc51893efaf9bab1d7421549390/src/abstractdataframe/reshape.jl#L322)
```julia
CategoricalArrays.CategoricalArray(v::StackedVector) = CategoricalArray(v[:]) # could be more efficient
```
Not quite sure why this is killing precompilation/loading compiled code. But if I take off the `precompile` directive, DataFrames is able to load.

Commenting out the line above allows the entire package to precompile/load fine.

**Comment by quinnj** [comment]
Ok, scratch my last comment, the _real_ offending line seems to be [here](https://github.com/JuliaData/DataFrames.jl/blob/8fd08510606badc51893efaf9bab1d7421549390/src/abstractdataframe/reshape.jl#L380).
```julia
Base.unique(v::RepeatedVector) = unique(v.parent)
```
I can fully include all other existing code in DataFrames and it precompiles/loads fine; but if this line is included, I get
```
julia> using DataFrames
INFO: Recompiling stale cache file /Users/jacobquinn/.julia/lib/v0.7/DataFrames.ji for module DataFrames.


signal (11): Segmentation fault: 11
in expression starting at no file:0
unknown function (ip: 0xffffffffffffffff)
Allocations: 22222148 (Pool: 22219383; Big: 2765); GC: 27
Segmentation fault: 11
jq-mbp:julia jacobquinn$
```

So the real question is: what's so _unique_ about `Base.unique`??

**Comment by nalimilan** [comment]
And if keep the line but change `Base.unique` to something else, e.g. `myunique`?

**Comment by quinnj** [comment]
> And if keep the line but change Base.unique to something else, e.g. myunique?

No segfault.

**Comment by quinnj** [comment]
Alright, this seems to be a bit of a moving target. On current master (37d47ba006), it's now this line that, if included, causes precompilation to segfault
```julia
Base.copy(df::DataFrame) = DataFrame(copy(columns(df)), copy(index(df)))
```
which is located in `src/dataframe/dataframe.jl`. 

Commenting out that one line allows the entire package to load w/ no problem.
