### ISSUE TITLE
Look into reorganizing pass pipeline

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#23772]
There's some feedback from upstream that our pass pipeline is suboptimal. Look into this
to see if there are any compile/runtime improvements to be had.

**Comment by maleadt** [comment]
Note from external codegen: it would be useful to have a PMbuiler-like extension mechanism, to inject eg. NVPTX-specific passes where appropriate, instead of after the fact. Might be appropriate to think about when reorganizing the passes.

**Comment by gbaraldi** [comment]
This has happened a couple of times and now we have moved to LLVMs NewPM
