### ISSUE TITLE
Cannot define types inside a @testset

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#23794]
If I do:

```julia
julia> begin
           struct foo
               bar
           end
       end
```

Everything is fine, however if I make this a `@testset`, I get:

```julia
julia> @testset "Baz" begin
           struct foo
               bar
           end
       end
ERROR: error compiling anonymous: type definition not allowed inside a local scope
```

It would be nice to be able to define types within a testset.

**Comment by StefanKarpinski** [comment]
It would probably be fine if the `@testset` macro hoisted the type definition out of its scope and just evaled it in global scope (once, presumably).

**Comment by staticfloat** [comment]
Yes, the only point of subtlety is that I would like the type definition itself to happen within the test set error handling domain, as I want to test things like `@io struct Foo` for StructIO

**Comment by mauro3** [comment]
Could the testset define a module?  Then the global runtest.jl scope would not be polluted.

**Comment by NHDaly** [comment]
Have there been any more thoughts on this since last year? I agree this would be really nice.

In particular, `@testset`s defining a module seems nice. Are there any problems that would come from that?

**Comment by fredrikekre** [comment]
> In particular, @testsets defining a module seems nice.

Don't you then have to `using MyPackage, Test, etc` for each `@testset`?

**Comment by gafter** [comment]
I cannot reproduce this on julia 1.8.

**Comment by inkydragon** [comment]
- ✔ 1.6.7
- ✔ 1.8.5
- ✔ 1.9.0-rc2
- ✔ 1.10.0-DEV.955 (2023-04-05)

It looks like `@testset` will define the new type in the top-level module.
+ 1.10.0-DEV.955
```julia
julia> foo(-1)
ERROR: UndefVarError: `foo` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> using Test

julia> @testset "Baz" begin
                  struct foo
                      bar
                  end
              foo(0) |> println
       end
foo(0)
Test Summary: |Time
Baz           | None  0.4s
Test.DefaultTestSet("Baz", Any[], 0, false, false, true, 1.680745856542e9, 1.680745856953e9, false)

julia> foo(1)
foo(1)
```

**Comment by staticfloat** [comment]
Closing as fixed. Thanks for the follow-up everybody!

**Comment by NHDaly** [comment]
Oh huh, cool! Good to know! Great work everyone. :)

(@gafter: We might have a different experience at RAI since we've started using `@testitem`s, from the VSCode package, where each `@testitem` actually _is_ a module, with "soft scope". I'm not sure if that's contributing to what you saw on 1.8 or not.)
