### ISSUE TITLE
Generated functions with gensym arguments are broken

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#23809]
On 0.6,
```julia
julia> sym = gensym()
Symbol("##657")

julia> eval(Expr(:stagedfunction, Expr(:call, :foo, sym), Expr(:quote, sym)))
foo (generic function with 1 method)

julia> foo(1)
ERROR: UndefVarError: ##657 not defined
Stacktrace:
 [1] foo(::Int64) at ./<missing>:0
```
Putting a normal symbol in place of `gensym()` fixes `foo`.

**Comment by bkamins** [comment]
Following https://discourse.julialang.org/t/invalid-redefinition-of-constant-in-comprehensions/6252
On 0.6 and on 0.7.0-DEV.1758 (2017-09-11 20:45 UTC) is another example of a similar problem. A MWE is:
```
s1() = 1
Int[i for i in 1:10]
```
which throws:
```
ERROR: invalid redefinition of constant #s1
Stacktrace:
 [1] anonymous at .\<missing>:?
```

**Comment by yuyichao** [comment]
They are not actually the same problem. I said it's similar just because both are caused by generated names.

**Comment by bkamins** [comment]
Sorry for the confusion. I have opened another issue #24002 to cover this problem.

**Comment by vtjnash** [comment]
:stagedfunction doesn't exist anymore
