### ISSUE TITLE
expand could use a better name

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#23808]
Breadcrumb to a slack discussion in which giving `expand` a better name came up. `@StefanKarpinski` suggested `Meta.lower`. Best!

**Comment by vtjnash** [comment]
That would seem to correspond nicely to `code_lowered`, which gives the same output. Would `macroexpand` change too?

**Comment by ararslan** [comment]
+1 for changing `expand` to `Meta.lower`, but I think we should keep `macroexpand` as-is. As far as I can tell, `macroexpand` doesn't do any code lowering as such, it only expands the macros in the given expression.

**Comment by StefanKarpinski** [comment]
`macroexpand` also has the word `macro` in it. `expand` is a rather generic term for such a specific and not-terribly-useful-to-99.9% of users function.

**Comment by chakravala** [comment]
Agreed, this needs to be changed. In the [Reduce.jl](https://github.com/chakravala/Reduce.jl) package for example, the `expand` keyword will be needed to algebraically expand `Expr` objects:
```Julia
julia> :((x + y) ^ 3) |> expand
:(x ^ 3 + 3 * x ^ 2 * y + 3 * x * y ^ 2 + y ^ 3)
```
However, importing `Base.expand` in conjunction with this method will then make the lowered code feature unavailable for expressions.

**Comment by KristofferC** [comment]
#24278
