### ISSUE TITLE
Sign Windows and Mac executables

### ISSUE THREAD

**Issue by jayschwa** [JuliaLang/julia#2381]
Currently, the Windows 8 "Smart"Screen filter tries to protect me by preventing the Julia executables and batch files from being executed. I have not read up on this filter, but I suspect it would be less hostile if executables were signed.

Before reaching v1.0, you ought to get signing integrated into your release process.

[ViralBShah: Updated title]

**Comment by tkelman** [comment]
Looks like this certificate lasts for a year, so will need to be renewed in the next 3 weeks?

**Comment by StefanKarpinski** [comment]
Yeah, I'm on it.

**Comment by tkelman** [comment]
Awesome. Let @staticfloat know when it's renewed, I think he has to move the certificate over to the buildbots somehow.

**Comment by tkelman** [comment]
Bump. Certificate's expired, needs to be renewed.

**Comment by ViralBShah** [comment]
This would have been better opened as a new issue. I believe the mac certificate requires renewing right now, is that right?

**Comment by tkelman** [comment]
If not for the reminder here from 3 weeks ago, I would have gone with a new issue or a direct email to whoever is able to make the renewal.

I don't know how long the OSX keys last for. The OSX buildbot has not been having any issues so I assume that one's still okay.

**Comment by ViralBShah** [comment]
Basically, IIRC, @StefanKarpinski did the mac certificate, and I did the windows certificate. So, just ping me if I need to do something.

**Comment by tkelman** [comment]
I see. Sorry I should've been more specific, it's the Windows certificate that is expired and needs to be renewed. It's been failing for a day or so - http://buildbot.e.ip.saba.us:8010/builders/package_win8.1-x64

Once it's ready we need to ping Elliot about getting it migrated over to the windows buildbots. The step is here https://github.com/staticfloat/julia-buildbot/blob/70571c66606fc744cf75597e1d207b5641161224/master/package_win.py#L81-L84 but I'm having a hard time finding where `sign.sh` comes from.

**Comment by ViralBShah** [comment]
I have initiated the process for a new Windows code signing certificate. Hopefully we will have one in a couple of days.

**Comment by ViralBShah** [comment]
I have the new windows code signing certificate (I think). @tkelman Would you know what to do with it? I believe @ihnorton set it up the last time.

**Comment by tkelman** [comment]
We need to get it up onto the buildbots somehow. @staticfloat knows how, I hope? Would be good if he could enlighten a few more of us what to do with it, if it's anything more complicated than just copying it over manually onto the buildbots.

**Comment by staticfloat** [comment]
Yep, send it to me and I'll load it onto the buildbots.  Here's how the signing process works:

* On OSX, the signing private key (a `.p12` file) and the public certificate (a `.cer` file) must be imported into the machine's keychain.  This can be done through the GUI, or using the `security` command-line tool.  Before attempting to sign (which is done in [this step](https://github.com/JuliaLang/julia/blob/master/contrib/mac/app/Makefile#L28) of the `.app` creation process) the keychain must be unlocked, which is done via the `~/unlock_keychain.sh` script.  Once the keychain is successfully unlocked, and the `codesign` tool has run, the `.app` is signed and can be bundled up into a `.dmg`.  The only thing that needs to happen once we get a new key here, is to login to the buildbot, import the `.p12` file into the keychain, and potentially change the key fingerprint being passed to `codesign` inside `contrib/mac/app/Makefile`.

* On Windows, there is no keychain, you just store the private key file (a `.pfx` file) on the buildbot somewhere, then pass it to `signtool.exe`.  This is done by the `~/sign.sh` file, and I believe the only thing that needs to happen here is to replace the `.pfx` and `.cer` files.  The `~/sign.sh` file is invoked from the buildbot [here](https://github.com/staticfloat/julia-buildbot/blob/master/master/package_win.py#L81-L84).

**Comment by ViralBShah** [comment]
@staticfloat confirmed the new Windows code signing certificate works.
