### ISSUE TITLE
build failure on macOS

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#23819]
(My most recent successful build was at 5ad2246266)

```
Josefs-MacBook-Pro$ make
make[4]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework', needed by `libgit2_clar'.  Stop.
make[3]: *** [CMakeFiles/libgit2_clar.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [scratch/libgit2-15e119375018fba121cf58e02a9f17fe22df0df8/build-compiled] Error 2
make: *** [julia-deps] Error 2
```

**Comment by josefsachsconning** [comment]
Note that I updated Xcode to version 9.0 on September 20.  Not sure whether that is relevant.

**Comment by yuyichao** [comment]
Is this a clean build?

**Comment by Keno** [comment]
Seconded on @yuyichao's question. It looks like the configuration step picked up an old SDK which no longer exists. That would happen if you configured before upgrading xcode and then built with the new xcode.

**Comment by josefsachsconning** [comment]
Problem was not on a clean build.  I will try that.

**Comment by ViralBShah** [comment]
Reopen if persists.

**Comment by josefsachsconning** [comment]
In a clean install, I get this:
```
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[4]: *** [testlsame] Error 1
make[3]: *** [lapack_install] Error 2
make[2]: *** [netlib] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0' if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [scratch/openblas-5dde4e65d321076582a2fafe16949d2160551e81/build-compiled] Error 1
make: *** [julia-deps] Error 2
```

**Comment by yuyichao** [comment]
According to https://github.com/Homebrew/legacy-homebrew/issues/45011 returned by googling the error message, you need to reinstall gcc after updating xcode.

**Comment by josefsachsconning** [comment]
Thanks for the multiple tips, and for your forbearance.  I forgot that surrounding my Google search string in quotation marks would improve my search results.

After `brew reinstall gcc`, `make` now gives me the following.

```
Josefs-MacBook-Pro$ make
Making all in lib
  CC       libcurl_la-connect.lo
/Users/sachs/src/julia-master/deps/srccache/curl-7.55.1/lib/connect.c:1069:12: error:
      'connectx' is only available on macOS 10.11 or newer
      [-Werror,-Wunguarded-availability]
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/socket.h:713:5: note:
      'connectx' has been explicitly marked partial here
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
/Users/sachs/src/julia-master/deps/srccache/curl-7.55.1/lib/connect.c:1069:12: note:
      enclose 'connectx' in a __builtin_available check to silence this warning
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
make[4]: *** [libcurl_la-connect.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [scratch/curl-7.55.1/build-compiled] Error 2
make: *** [julia-deps] Error 2
```

**Comment by yuyichao** [comment]
Upstream issue afaict https://github.com/curl/curl/issues/1330
You should be able to workaround this by passing `-Wno-error` C flags.

**Comment by josefsachsconning** [comment]
I don't understand the connection to curl/curl#1330
since I am running on macOS 10.12.6

As you suggested, I do seem to have gotten around the problem by using `make CFLAGS=-Wno-error`.  Thanks again.

**Comment by iamed2** [comment]
Looks like whichever version of curl comes next should fix it, as this commit supposedly fixes the issue: https://github.com/curl/curl/commit/870d849d48a26b8eeb0d4bb1f4655367a4a191ca

**Comment by iamed2** [comment]
@josefsachsconning it looks like it can happen if you have XCode 9.0 tools, even if you don't have High Sierra yet.

**Comment by iamed2** [comment]
@ViralBShah Do you think this should be reopened or should I make a new issue with this root cause?

**Comment by ViralBShah** [comment]
I think a new issue would be better.
