### ISSUE TITLE
`round(Int, Float64(typemax(Int)))` gives InexactError

### ISSUE THREAD

**Issue by vipinv** [JuliaLang/julia#23859]
Title says it all. I would expect this to work. `trunc(Int, Float64(typemax(Int)))` doesn't work either. Right now, I have no way to truncate a large Float64 value to an Int.

**Comment by yuyichao** [comment]
Both of them are expected since

```julia
Float64(typemax(Int)) > typemax(Int)
```

You can easily do that with a branch.
