### ISSUE TITLE
clear/remove names from repl

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#2385]
This is rapidly becoming a frequently-requested feature, and there doesn't appear to be a current tracking issue for it, so this will at least give me something to point to.

I think it would be acceptable if this only works from the REPL, though others may disagree.

**Comment by pannous** [comment]
Why is this closed? We still can't delete individual symbols / functions, can we?

**Comment by timholy** [comment]
It was fixed in 0.3 but problematic so removed before 1.0.

We do have `Base.delete_method` (and Revise will handle deletions automatically for you), but that doesn't work if you wanted that name to not be a function.

**Comment by pannous** [comment]
Thanks, that's what I had been looking for  
`delete(func)=Base.delete_method(@which func)`

**Comment by ptoche** [comment]
In atom/juno is ``exit()`` the way to restart a session without closing atom?

**Comment by jankap** [comment]
Can it be reopened? :)

**Comment by oscardssmith** [comment]
I'm re-opening, despite personally thinking that this is probably a bad thing to have.

**Comment by jankap** [comment]
Thank you. Maybe my workflow is not suitable then. Could you please
elaborate a little bit about why you don't like it?
I mean, Julia is designed as a dynamic language with strong REPL support.
How would you avoid re-defining errors in a longer REPL session? Especially
when certain lines of code are copy pasted from examples or so?

I'm coming from Matlab and there it wasn't unusual to clear variables and
functions.

Thanks!

**Comment by KristofferC** [comment]
The old strategy of "redefining" `Main` should now work much better because packages are not loaded directly into Main but into another hidden module.

**Comment by jankap** [comment]
@KristofferC , is this still working or is that an idea how to tackle this ticket?

Thanks

**Comment by StefanKarpinski** [comment]
Now that we can activate a different module than Main, it might be possible to create a new Main module and replace the old one with the new one. It could further be possible to copy some of the old bindings over, which would allow emulating the deletion of the non-copied bindings.

**Comment by tgross35** [comment]
Just to add a specific use case - this is pretty brutal for jupyter notebooks. It's not uncommon to have something simple like:

```julia
using Plots

x = 10
plot(...)
```

If you wanted to change `x` to `x(t) = 10 * t`, your only option is to restart the kernel - same if you need to change it back later. Now of course it would be nice if restarting the kernel and loading plots was faster out of the box, but I don't think it really needs to be when a call to `clear()` at the beginning of the cell could be significantly faster. I don't think the suggested workaround in the docs is very good when it requires modules for even the most simple program like this.

It seems like there was some opposition to adding a `clear()` function at some point - anyone know why? I can't seem to find if it was a technical limitation (seems like that was at least part of it), or if there was some subjective reason. The other discussions seem to point to a mailing list - but somewhat unhelpfully, there are no links and it seems like the list may no longer be in existence.

**Comment by vtjnash** [comment]
Eventually we said this should be implemented by the interactive package (eg juypter), to manage Modules and allow you to get a new one whenever and however you want, instead of providing a single behavior in Base.

**Comment by vtjnash** [comment]
x = t->10t

Also would work for your case

**Comment by tgross35** [comment]
Thanks for the tip about workaround syntax.

Do you mind clarifying the reason you don't think this would be reasonable in base? Coming from Matlab or R, it's very handy to be able to remove specific variables from scope in REPL without needing module workarounds.

**Comment by vtjnash** [comment]
Yeah, we are still considering if we could let Revise.jl delete variables, but currently it is a major reason Julia is fast so it is a bit tricky to change

**Comment by StefanKarpinski** [comment]
The thing we could do at this point is create a new Main module, make it the new active REPL module, and then throw out the old Main module. That would have the desired effect (mostly). We now have the ability to replace the active REPL module, so this might be much easier to do now than in the past.

**Comment by vtjnash** [comment]
Right. Notably though that must be implemented in REPL / IJulia / etc. now, since they have the capability of giving the user a new module, but Julia base cannot force them to implement it

**Comment by gwd666** [comment]
btw afaict abstract classes behave the same way
