### ISSUE TITLE
help for cov function (statistics.jl) outdated, vardim keyword not supported

### ISSUE THREAD

**Issue by nil-8** [JuliaLang/julia#23873]
`A = randn(5,5)`
`cov(A,vardim=2)`
fails, with an error "

> No method matching ...
> unsupported keyword argument "vardim"

However ?cov gives that vardim should be a valid keyword.

**Comment by andreasnoack** [comment]
Thanks for reporting. It is now a positional argument so you can do
```julia
cov(A, 2)
```
Unfortunately, the documentation hasn't been updated for that change. It would be great if you could prepare a pull request with a fix.

**Comment by nalimilan** [comment]
`?cov` doesn't say `vardim` is a keyword argument AFAICT. Though I agree it's not obvious and we should use different colors to distinguish positional and keyword arguments in the docs.

**Comment by fredrikekre** [comment]
Closing in favor of the more general #4902
