### ISSUE TITLE
addprocs() ERROR: KeyError: key "stdout" not found

### ISSUE THREAD

**Issue by 4lrdyD** [JuliaLang/julia#23879]
I tried to add work processes in Julia0.5, but I get an error as follows:

**julia> addprocs()**
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
        From worker 7:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 7:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
        From worker 7:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 7:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
Worker 7 terminated.
        From worker 4:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 4:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
Worker 4 terminated.ERROR (unhandled task failure): Version read failed. Connection closed by peer.
        From worker 4:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB

        From worker 4:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
        From worker 2:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
Worker 2 terminated.    From worker 2:  [0] NVIDIA  : GeForce GT 630M, 2048 MB

        From worker 2:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 2:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
        From worker 5:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 5:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
        From worker 5:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 5:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
Worker 5 terminated.
ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
Worker 8 terminated.
ERROR (unhandled task failure): Version read failed. Connection closed by peer.
 in process_hdr(::TCPSocket, ::Bool) at .\multi.jl:1410
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1299
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1276
 in (::Base.##620#621{TCPSocket,TCPSocket,Bool})() at .\event.jl:68
        From worker 8:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 8:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
        From worker 8:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 8:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
Worker 9 terminated.
ERROR (unhandled task failure): Version read failed. Connection closed by peer.
 in process_hdr(::TCPSocket, ::Bool) at .\multi.jl:1410
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1299
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1276
 in (::Base.##620#621{TCPSocket,TCPSocket,Bool})() at .\event.jl:68
        From worker 9:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 9:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
        From worker 9:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 9:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB
ERROR: KeyError: key "stdout" not found
 in getindex at .\dict.jl:688 [inlined]
 in send_stream(::String) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:109
 in flush(::Base.PipeEndpoint) at C:\Users\user\.julia\v0.5\IJulia\src\stdio.jl:231
 in start_worker(::Base.PipeEndpoint, ::String) at .\multi.jl:1543
 in process_options(::Base.JLOptions) at .\client.jl:220
 in _start() at .\client.jl:318
Worker 3 terminated.
ERROR (unhandled task failure): Version read failed. Connection closed by peer.
 in process_hdr(::TCPSocket, ::Bool) at .\multi.jl:1410
 in message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1299
 in process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at .\multi.jl:1276
 in (::Base.##620#621{TCPSocket,TCPSocket,Bool})() at .\event.jl:68
        From worker 3:  ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
        From worker 3:  [0] NVIDIA  : GeForce GT 630M, 2048 MB
        From worker 3:  -1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
        From worker 3:  -2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB

then I have to restart Julia, since it no longer works

**julia> afinfo()**
ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
[0] NVIDIA  : GeForce GT 630M, 2048 MB
-1- INTEL   : Intel(R) HD Graphics 4000, 1400 MB
-2- INTEL   : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz, 6037 MB

**julia> versioninfo()**
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**julia> Sys.CPU_CORES**
8

**Comment by andreasnoack** [comment]
I don't see this issue on 0.6 or 0.5.1 so could you try to update your Julia to either 0.5.1 or 0.6 to see if the problem remains?

**Comment by 4lrdyD** [comment]
yes I have Julia0.6 and this does not happen, but the problem is that in version 0.6 I can not work with some packages, this is going to be problematic for me

**Comment by andreasnoack** [comment]
What about 0.5.2?

**Comment by 4lrdyD** [comment]
i don't use that versión, but i guess that i must attempt, thanks a lot.

**Comment by felixcremer** [comment]
This issue can be closed. The problem has been fixed in 0.6.
