### ISSUE TITLE
Type instability of the std function?

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaLang/julia#23877]
Please consider the following code:

```
function fun1(x)
    delta = std(x)
    
    for i in eachindex(x)
        if x[i]<delta
           x[i] = -x[i]
        end
    end

    return x
end

function fun2(x)
    delta::Float64 = std(x)
    
    for i in eachindex(x)
        if x[i]<delta
           x[i] = -x[i]
        end
    end

    return x
end


x = rand(100_000);

@time for i=1:1000 fun1(x); end
@time for i=1:1000 fun2(x); end
```
  2.233152 seconds (100.01 M allocations: 1.490 GiB, 4.51% gc time)
  0.404369 seconds (8.43 k allocations: 360.187 KiB)

This is a significant speed difference.
Does it come from from the type instability of the std function?

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

**Comment by StefanKarpinski** [comment]
I think this is coming from the fact that `std` passes a function as a keyword argument and I don't think that we can infer keyword function arguments like can positional function arguments. Nothing fundamental here, it's just a matter of optimization elbow grease.

**Comment by GaborOszlanyi** [comment]
Thank you for the clear explanation.
Is there already a more general issue for the inference of keyword function arguments?

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/9551 https://github.com/JuliaLang/julia/issues/21794 https://github.com/JuliaLang/julia/issues/23548 https://github.com/JuliaLang/julia/pull/21915 and all linked issues.

Dup of https://github.com/JuliaLang/julia/issues/21811

**Comment by GaborOszlanyi** [comment]
Huh. That is a substantial history.
Thank you for linking it here.
