### ISSUE TITLE
consistent, descriptive terminology for orthogonal factorizations

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#23882]
Breadcrumb to https://github.com/JuliaLang/julia/pull/23813#discussion_r140434228: We should consider selecting broadly descriptive terminology for orthogonal factorizations (for example the adjective "truncated" rather than "thin" to describe the relevant type of QR/LQ/RQ/QL factorization), and then use that terminology consistently across all orthogonal factorizations (documentation, comments, function names and arguments, etc). Best!

**Comment by andreasnoack** [comment]
Thanks. This is breaking so I've added it to the milestone. Good news is that it is easy to fix.

**Comment by Sacha0** [comment]
Re. the milestone, this issue could be addressed after 1.0 if `LinAlg` moves out of base as anticipated? Best!

**Comment by andreasnoack** [comment]
I'd be fine with either `truncated` or to "invert" the keyword such that you can ask for `square`.

**Comment by Sacha0** [comment]
(The decision in triage was to leave this issue on the milestone under the assumption that the rename etc should require little time.)

**Comment by Sacha0** [comment]
While preparing a pull request addressing this issue I realized that "truncated" has failings, particularly that "truncated [QR|RQ|LQ|QL]" can mean either "thin"/"reduced" or "truncated" in the SVD sense (which also exists for QR/RQ/LQ/QL). "reduced" isn't particularly descriptive. So `@andreasnoack`'s suggestion of "inverting" the keyword to "square" now strikes me as wisest. Best!

**Comment by Sacha0** [comment]
Closed by #24279. Thanks all! :)
