### ISSUE TITLE
subtyping segfault

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#23908]
```julia
julia> A = Pair{nothing, Pair{Array{Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, 1}, Void}};

julia> B = Pair{nothing, Pair{Array{Union{Int8, UInt128, UInt16, UInt32, UInt64, UInt8, _}, 1}, Void}} where _;

julia> A <: B
Assertion failed: (i >= 0 && i < sizeof(st->stack) * 8), function statestack_get, file /Users/jameson/julia/src/subtype.c, line 117.

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2666407 (Pool: 2666102; Big: 305); GC: 5
Abort trap: 6
```

**Comment by JeffBezanson** [comment]
Probably similar to or dup of #22688?

**Comment by Keno** [comment]
Yes, same issue. We need to improve the algorithms for unions here.

**Comment by vtjnash** [comment]
Since we're now sorting Unions, a quick-fix may be to allocate them as a balanced tree instead of a linked list.

**Comment by JeffBezanson** [comment]
I tried the balanced tree thing. With it, the good news is that we can handle 1 more union component in variations of this example than before. The bad news is that it doesn't fix the original example, and seems to make some of these cases much slower to subtype.

**Comment by JeffBezanson** [comment]
Basically what happens here, and in the hang in #22688, is `forall_exists_equal` runs through a bunch of left union states without consuming any right union states, causing the right stack to expand much more than necessary.

One thing that almost works is to call `forall_exists_subtype` from `forall_exists_equal`, resetting and restoring the union stacks around the call. That fixes the cases in these issues, but has 2 subtype test failures.
