### ISSUE TITLE
Symbol "jl_repl_raise_sigtstp" is not defined in libjulia.so

### ISSUE THREAD

**Issue by abalkin** [JuliaLang/julia#23918]
I am running Julia embedded in another program and whenever I hit <kbd>^Z</kbd>, my program crashes with the following message:

```
ERROR: could not load symbol "jl_repl_raise_sigtstp":
myprog: undefined symbol: jl_repl_raise_sigtstp
Stacktrace:
 [1] run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1580
 [2] run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:945
 [3] run_repl(::Base.REPL.LineEditREPL, ::Base.##507#508) at ./REPL.jl:180
 [4] _start() at ./client.jl:413
```

Looking at the libjulia.so.0.6 binary, I see that indeed jl_repl_raise_sigtstp is not defined there:

```
$ nm libjulia.so.0.6 | grep jl_repl_raise_sigtstp
<empty output>
```

I am using julia version 0.6.0 on CentOS release 6.9.

**Comment by yuyichao** [comment]
It's defined in the executable so we just need to move it...

**Comment by abalkin** [comment]
That's right. 
 The definition is in [ui/repl.c](https://github.com/JuliaLang/julia/blob/6a1e339cf60a95fd34f588f43df8e956c8f637c9/ui/repl.c#L77).
