### ISSUE TITLE
Hadamard Product Julia .6

### ISSUE THREAD

**Issue by kbojanek** [JuliaLang/julia#23927]
Hadamard Product seems to be significantly slower in Julia .6 compared to Julia .5, across matrices of several different sizes. Is anyone else noticing this problem?

**Comment by KristofferC** [comment]
Can you please give some concrete examples.

**Comment by kbojanek** [comment]
When I was testing it, I ran over several different random matrices of several different sizes to compare times.  But here's one particular example. Problem seems to be more severe  for smaller matrices. 

julia .5 

a = rand(64,64)
b = rand(64,64)

@time a.*b;
average for this is 0.000028 seconds

same for julia .6

average for this is 0.000112 seconds

**Comment by stevengj** [comment]
This is just the usual problem with benchmarking in global scope.  In a function, it should be fine.  With `using BenchmarkTools, Compat`, I get:

Julia 0.5:
```
julia> a = rand(64,64); b = rand(64,64); @btime $a .* $b;
  4.047 μs (13 allocations: 32.41 KiB)
```

Julia 0.6:
```
julia> a = rand(64,64); b = rand(64,64); @btime $a .* $b;
  3.083 μs (2 allocations: 32.08 KiB)
```

(The `$a` and `$b` is a trick in BenchmarkTools to eliminate the use of globals.)
