### ISSUE TITLE
should we move printf code out of Base?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#23929]
The real motivation is to replace it with something standard that's better in 1.x. The current code works, but it requires macros for invocation, which is suboptimal and has long been (low down) on my todo-list for a redesign. If we make a `Printf` standard library package then we can evolve this in the future, potentially in a backward incompatible way.

**Comment by JeffBezanson** [comment]
Yes, that's the spirit! Move out all the things!! :)

I actually don't have a strong opinion on this one though, since printf is such standard functionality.

**Comment by StefanKarpinski** [comment]
Perusing the code base, `@printf` is only used in a few utility functions and in parts of Base that should be moved into packages. The laziest future-proof approach to excision is to leave the definition in Base and add a `Printf` stub module to `stdlib` that just exports the functionality that's defined in `Base`. The same approach could be used for other excisions as well.

**Comment by StefanKarpinski** [comment]
The 1.0 to do here is:

1. unexport `@printf` and co from `Base`
2. create `Printf` in `stdlib` which exports the above.

Later we can more thoroughly extract this and replace the few uses of `printf` in Base (mostly to print a fixed number of floating-point digits) with simpler more targeted functionality.

**Comment by brenhinkeller** [comment]
Agh, this is all good reasoning but having everything moved to its own little package is starting to wear me down; being able to write useful code without a ton of "using"s and "includes" in every file was originally one of the things I really liked about Julia vs., e.g., Python.
