### ISSUE TITLE
Multiword searches in the online docs give zero results if you hit enter

### ISSUE THREAD

**Issue by nicknack23** [JuliaLang/julia#23934]
If you enter multiple words in the search box and hit enter you get zero results. For example, there is a major section heading called `control flow`, so try that. This may have gone unnoticed because you get plenty of results as you type if incremental search is active. However pasting some words in the search box and quickly hitting enter will always return zilch.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaDocs/Documenter.jl/issues/494
