### ISSUE TITLE
Issues with FFT when compiled with MKL

### ISSUE THREAD

**Issue by mfsch** [JuliaLang/julia#23945]
I experience two issues with the FFT when Julia is configured to use MKL. The first one is the one described in [this discussion](https://discourse.julialang.org/t/plan-fft-fails-when-julia-is-built-with-intel-mkl/4284/6), which does not seem to be resolved in Julia 0.6 (the FFTW version is set to 3.3.4 even when MKL is used). The second issue is that MKL does not seem to like three-dimensional arrays.

Printing the FFT plan fails:
```
julia> plan_fft(zeros(64,64))
FFTW forward plan for 64×64 array of Complex{Float64}Error showing value of type Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,2}:
ERROR: ccall: could not find function fftw_sprint_plan in library libmkl_rt
Stacktrace:
 [1] sprint_plan(::Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,2}) at ./fft/FFTW.jl:295
 [2] show(::IOContext{Base.Terminals.TTYTerminal}, ::Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,2}) at ./fft/FFTW.jl:305
```

Creating a plan works for a 2D array, but not for a 3D array (even if the FFT itself is one-dimensional):
```
julia> plan_fft(zeros(64,64),1); # works

julia> plan_fft(zeros(64,64,1),1);
ERROR: FFTW could not create plan
Stacktrace:
 [1] Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,3}(::Array{Complex{Float64},3}, ::Base.DFT.FFTW.FakeArray{Complex{Float64},3}, ::Int64, ::UInt32, ::Float64) at ./fft/FFTW.jl:484
```

Version/library information:
```
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.9.0 (ORCJIT, broadwell)

julia> Base.libfftw_name
"libmkl_rt"

julia> FFTW.version
v"3.3.4"
```

All of these commands work for my local installation which does not use MKL (`Base.libfftw_name == "libfftw3_threads"`).

**Comment by fredrikekre** [comment]
AFAICT this is not a julia issue. Please open an issue at the appropriate fftw package. Related (and perhaps fixed by?) to https://github.com/JuliaMath/FFTW.jl/pull/42

**Comment by EthanAnderes** [comment]
The issues I'm seeing are with Julia v0.6, before FFTW was split to a separate package.

**Comment by EthanAnderes** [comment]
Also, see [#21546](https://github.com/JuliaLang/julia/pull/21546).
