### ISSUE TITLE
An apparent minor bug

### ISSUE THREAD

**Issue by FredJames32** [JuliaLang/julia#23946]
```julia
A = zeros(3,1)'
B = zeros(3)'
A == B  # true
A' == B' # false
```

**Comment by FredJames32** [comment]
A = zeros(3,1)'
B = zeros(3)'
A == B  # true
A' == B' # false

**Comment by FredJames32** [comment]
A = zeros(3,1)'
Out[1]:
1×3 Array{Float64,2}:
 0.0  0.0  0.0
In [2]:
B = zeros(3)'
Out[2]:
1×3 RowVector{Float64,Array{Float64,1}}:
 0.0  0.0  0.0
In [3]:
A == B  #true
Out[3]:
true
In [4]:
A'==B'   # false
Out[4]:
false

**Comment by fredrikekre** [comment]
#21998
