### ISSUE TITLE
An apparent minor bug

### ISSUE THREAD

**Issue by FredJames32** [JuliaLang/julia#23947]
```julia
A = zeros(3,1)'
B = zeros(3)'
A == B # true
A' == B' # false
```

**Comment by yuyichao** [comment]
AFAICT this is not the case,

```
julia> A = zeros(3,1)
3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

julia> B = zeros(3)'
1×3 RowVector{Float64,Array{Float64,1}}:
 0.0  0.0  0.0

julia> A == B # true
false

julia> A' == B' # false
false
```

**Comment by yuyichao** [comment]
(Last comment was a wrong editting, dup of https://github.com/JuliaLang/julia/issues/23946#issuecomment-333346671)

**Comment by FredJames32** [comment]
Thanks for the reply. But, this is the case. A should be defined as A = zeros(3,1)'  (transpose). Here it is
A = zeros(3,1)'
Out[1]:1×3 Array{Float64,2}:
 0.0  0.0  0.0In [2]:B = zeros(3)'
Out[2]:1×3 RowVector{Float64,Array{Float64,1}}:
 0.0  0.0  0.0In [3]:A == B  #true
Out[3]:trueIn [4]:A'==B'   # false
Out[4]:false
