### ISSUE TITLE
how to build julia for posix cygwin julia

### ISSUE THREAD

**Issue by devel-chm** [JuliaLang/julia#23953]
I tried make in the 0.6 source distribution but that seems to be cross compiling 
for native windows and not building a cygwin/posix executable.  Is there a way to 
tell the make process that I want the unix/posix configuration on cygwin rather 
than a win32/mingw binary?

Is there a make option for generic unix detection and build that I could
start from?

Thanks!

**Comment by vtjnash** [comment]
No, that configuration is not supported as we wanted to provide a high-performance library so we target the OS directly instead of the posix shim. But please use discourse to ask questions.

**Comment by devel-chm** [comment]
Apologies, I was following the directions on the Julia Downloads page:

> If the provided download files do not work for you, please file an issue in the Julia project.
