### ISSUE TITLE
more generic LU factorization

### ISSUE THREAD

**Issue by ityonemo** [JuliaLang/julia#23950]
I'm playing around with using the built-in LU factorization solver for other numerical types, in particular ones which are in fields (e.g. finite fields) that have true one() and zero() values, but may not have values for which a direct conversion from integer makes sense.  A few of the functions in the LU factorization throw flags, so currently I patch them as follows:

```julia
function Base.LinAlg.istril(A::AbstractMatrix)
    m, n = size(A)
    for j = 2:n, i = 1:min(j-1,m)
        if A[i,j] != zero(eltype(A))
            return false
        end
    end
    return true
end
```

as with istriu, and generic_lufact! also has a comparison to zero which should be zero(T).

**Comment by andreasnoack** [comment]
Please always include your `versioninfo()`. I think this might be fixed on master where we use `iszero` instead of `A[i,j] != 0`. Could you try out your example on master?

**Comment by ityonemo** [comment]
versioninfo:
versioninfo()
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-alpine-linux-musl)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-4.0.0 (ORCJIT, broadwell)

**Comment by ityonemo** [comment]
oh perfect, it's fixed in master!  Sorry about that!
