### ISSUE TITLE
Each module should have a README

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#23959]
```julia
julia> using DelimitedFiles

help?> DelimitedFiles
search: DelimitedFiles

  No documentation found.

  No docstring or README.md found for module DelimitedFiles.
```

**Comment by jw3126** [comment]
Do I understand this correctly, there should be a docstring added for each module and not a `README.md` file put somewhere?

**Comment by fredrikekre** [comment]
The docsystem first searches for a docstring for the module, if that does not exist it searches for a README. In this case I think we would prefer a docstring for the module.

**Comment by jw3126** [comment]
I can add a stub to each module.
