### ISSUE TITLE
0.7 build on Mac 0S X Sierra: ld: library not found for -lSystem

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#23962]
I get the error below. I'm on Mac OS X Sierra, and just upgraded to XCode 9.0.  My Make.user is
```
override USE_SYSTEM_BLAS = 1
override USE_SYSTEM_LAPACK = 0
```

Here is the error:

```
[ma-solver-imac:~/Projects/julia7] solver% make
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   465  100   465    0     0    565      0 --:--:-- --:--:-- --:--:--   565
100 24.3M  100 24.3M    0     0  5016k      0  0:00:04  0:00:04 --:--:-- 6207k
patching file SuiteSparse_config/SuiteSparse_config.h
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0    217      0  0:00:02  0:00:02 --:--:--   217
100 6165k  100 6165k    0     0  1450k      0  0:00:04  0:00:04 --:--:-- 2964k
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[3]: *** [testlsame] Error 1
/bin/sh: ./testlsame: No such file or directory
/bin/sh: ./testslamch: No such file or directory
/bin/sh: ./testdlamch: No such file or directory
/bin/sh: ./testsecond: No such file or directory
/bin/sh: ./testdsecnd: No such file or directory
/bin/sh: ./testieee: No such file or directory
/bin/sh: ./testversion: No such file or directory
make[2]: *** [lapack_install] Error 127
make[1]: *** [scratch/lapack-3.5.0/build-compiled0] Error 2
make: *** [julia-deps] Error 2
```

**Comment by ararslan** [comment]
I wonder if anyone regularly tests Julia with Apple's vecLib. Does it work for you if you build OpenBLAS?

**Comment by dlfivefifty** [comment]
I can try. but last I checked Apple's BLAS is _significantly_ faster, especially for `eigs`.

(Worse, with Julia 0.4 `svd` would crash using OpenBLAS, but I think that was fixed.)

**Comment by ViralBShah** [comment]
Can you try with 0.6? There have been many updates to openblas. I don't think we test the vecLib stuff at all.

**Comment by BrunoFiligree** [comment]
I'm currently trying to build v0.6.0 on OSX 10.12.6 and run into a similar problem when trying to build with openBlas as opposed to the system blas. I get....

> ld: library not found for -lSystem
> collect2: error: ld returned 1 exit status
> make[4]: *** [testlsame] Error 1
> make[3]: *** [lapack_install] Error 2
> make[2]: *** [netlib] Error 2

Digging into it, gfortran is being used to link a test program in openblas/lapack-netlib/INSTALL and is failing to find libSystem.dylib. This library exists in /usr/lib. I'm using gfortran 7.2.0 installed via brew. The line is...

> gfortran -mmacosx-version-min=10.8 -m64 -pthread -O2 -fPIC -m128bit-long-double -Wall -m64 -fdefault-integer-8 -fPIC -lpthread -lgfortran -o testlsame lsame.o lsametst.o

If I add -L/usr/lib the above link line works perfectly. 

If I try to build with the system blas I get exactly the same issues in v0.6.0 as the OP does.

**Comment by malmaud** [comment]
I'm seeing the same thing, even with no custom Make.user. This is stopping me from developing against master on my main computer now.

**Comment by malmaud** [comment]
@Ismael-VC suggested `brew rebuild gcc`, which worked for me.

**Comment by ihnorton** [comment]
x-ref: https://github.com/JuliaLang/julia/issues/19588#issuecomment-266979910

**Comment by dlfivefifty** [comment]
Hah, that’s

**Comment by dlfivefifty** [comment]
Whoops, accidental click

**Comment by malmaud** [comment]
Note that `brew upgrade gcc` from that issue wasn't sufficient for me, I had to to do `brew rebuild gcc`.

**Comment by dlfivefifty** [comment]
Upgrading to High Sierra and doing `brew update` has seemed to fix this issue, but ran into another issue: https://github.com/JuliaLang/julia/issues/23980
