### ISSUE TITLE
Proposal: allow snippets and code from users in julia docs

### ISSUE THREAD

**Issue by affans** [JuliaLang/julia#23966]
I would like to propose a "comments" section in Julia docs. At the end of a particular document, for example, [parallel computing](https://docs.julialang.org/en/stable/manual/parallel-computing/), users should be able to submit small snippets of code to outline intricacies and optimizations of the code. 

I got the idea from reading about an old issue #21940 and #21946. In those threads, I got the idea of using `CachingPool` when using `pmap` and it has helped my simulation code greatly. I am not sure if I would've learned about it otherwise. 

Also, as an aside, for open source projects does it also mean that the documentation is open source? Can I go ahead and write up some stuff for `pmap` and `cachingpool` in the documents?

**Comment by vchuravy** [comment]
> Also, as an aside, for open source projects does it also mean that the documentation is open source? Can I go ahead and write up some stuff for pmap and cachingpool in the documents?
Yes! You can edit the docs at https://github.com/JuliaLang/julia/tree/master/doc/src some specific docs for functions are associated to their Julia code.

Instead of having a comment section I would say improving the current manual and adding paragraphs with examples would be more beneficial.

**Comment by KristofferC** [comment]
There could be something like a wiki for this but I don't think adding comments to the manual itself is that good of an idea in the long run.
