### ISSUE TITLE
remove module self-bindings?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23965]
Currently every module `Foo` contains an identifier `Foo` pointing to itself. What's more, that name is exported. I've heard a couple votes for removing this feature.

After writing `using Foo`, this default exported name is actually the reason the name `Foo` is available in your namespace. In hindsight, that's a bit weird. If we change this, we should also implement the proposal in #8000, so that `import Foo: ...` soft-imports just the exported names, and `using Foo` does both `import Foo` and `import Foo: ...`.

One of the best features of this change is that it would allow a pattern for "all-qualified" APIs, e.g. having the CSV package export `CSV.read` and `CSV.write` but not `read` and `write`:

```
module CSV

read() = ...
write() = ...
private_function() = ...

module CSV
import ..read, ..write
export read, write
end

export CSV

end
```

Making that fully work might require an extra rule, e.g. if `Foo` exports the name `Foo`, `using Foo` should not also add a binding for the top-level `Foo`.

**Comment by vtjnash** [comment]
What does that example mean? That it would be used as `using CSV.CSV: ...`? That `using CSV.read` != `CSV.read`?

**Comment by JeffBezanson** [comment]
The example means you could write `using CSV`, get only `CSV` in your namespace, and `CSV.` would tab-complete only to stuff you're supposed to use. You could also obtain the `CSV` name via `import CSV.CSV` or `import CSV: ...`.

**Comment by vtjnash** [comment]
What advantage does that have over:
```julia
module CSV

module Internal
read() = ...
write() = ...
private_function() = ...
end

export .Internal: read, write

end
```

**Comment by JeffBezanson** [comment]
True, that's very similar. I guess the advantage (albeit a small one) is that it does a bit more to discourage using `read` and `write` unqualified. But anyway, the change should be considered independent of this particular use case.

**Comment by JeffBezanson** [comment]
Triage is not too excited about this; the current situation doesn't seem to be causing real problems.

@Keno suggests that if we remove this binding, we should disallow exporting something with the same name as the module, to avoid confusion.

**Comment by malmaud** [comment]
It would still be good tol have a way to get a reference to the current module that doesn't involve knowing its name.

**Comment by StefanKarpinski** [comment]
Does `@__MODULE__` not do what you need?

**Comment by samoconnor** [comment]
I've just recently found it helpful to have the module name symbol in the module.
The module is called `JSON` and has `struct String`, `struct Number` and `struct Array`. I found it helpful to refer to `Base.String` and  `JSON.String` etc throughout the code of the module to avoid ambiguity.

Perhaps I could defined `const MyModule = @__MODULE__` to retain this behaviour.

**Comment by StefanKarpinski** [comment]
After a number of in-person discussions, I think we've settled on keeping this as is. It does seem useful and it seems actively confusing for `Foo` in the `Foo` module to refer to anything but the module itself.

**Comment by JeffBezanson** [comment]
A possible variation of this change is just to stop *exporting* the module self-binding.

**Comment by StefanKarpinski** [comment]
> A possible variation of this change is just to stop exporting the module self-binding.

Yes, I think we should do that, but we should also have `using Foo` create a hard binding for `Foo` as part of the semantics of `using`, which has much the same effect.

**Comment by erezsh** [comment]
I would also like to have the ability to remove the module name, so I can have more control over what `Core.eval` sees and does. That could be useful, for instance, for evaluating user expressions in a "safe" way (by allowing only certain kinds of expressions).

Right now, even `Module()` creates `:anonymous`, and there is no way to separate it from actual variables, other than "remembering" that specific symbol. Perhaps creating a fix for that specific use-case (for example `Module(self_reference=false)` would be good enough.
