### ISSUE TITLE
Document Pair

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#23979]
`Pair` does not have a docstring and is not mentioned even once in the manual. Could use both a manual snippet and a docstring with some examples for `Pair`.

**Comment by jdlangs** [comment]
Relevant: #21656 and #15279.

**Comment by shyshin** [comment]
Hi! I am new to open source and would like to work on this issue. Could please guide me as to what I have to do?

**Comment by KristofferC** [comment]
Someone made a PR already. https://github.com/JuliaLang/julia/pull/24018

**Comment by fredrikekre** [comment]
> Hi! I am new to open source and would like to work on this issue.

Hi and thanks for you interest in contributing to open source. Unfortunately there is already an open PR (#24018) to fix this issue, as you see linked just above your comment.

> Could please guide me as to what I have to do?

A good starting point is [CONTRIBUTING.md](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md), but you can also have a look at #24018 to see what was done for this particular documentation issue.

**Comment by shyshin** [comment]
Thanks Fredrik.
