### ISSUE TITLE
curl build broken with XCode 9.0

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#23980]
From https://github.com/JuliaLang/julia/issues/23819#issuecomment-331609093:
```
Josefs-MacBook-Pro$ make
Making all in lib
  CC       libcurl_la-connect.lo
/Users/sachs/src/julia-master/deps/srccache/curl-7.55.1/lib/connect.c:1069:12: error:
      'connectx' is only available on macOS 10.11 or newer
      [-Werror,-Wunguarded-availability]
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/socket.h:713:5: note:
      'connectx' has been explicitly marked partial here
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
/Users/sachs/src/julia-master/deps/srccache/curl-7.55.1/lib/connect.c:1069:12: note:
      enclose 'connectx' in a __builtin_available check to silence this warning
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
make[4]: *** [libcurl_la-connect.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [scratch/curl-7.55.1/build-compiled] Error 2
make: *** [julia-deps] Error 2
```

Mentioned in https://github.com/curl/curl/issues/1330, https://github.com/curl/curl/pull/1336, https://github.com/curl/curl/issues/1339 and fixed in https://github.com/curl/curl/commit/870d849d48a26b8eeb0d4bb1f4655367a4a191ca

This should be available in the next curl release (whatever comes after v7.55.1).

This currently prevents Julia from building on macOS with XCode 9.0.

**Comment by yuyichao** [comment]
Set `-Wno-error` in `CFLAGS`

**Comment by iamed2** [comment]
Oh right, yes, forgot to post the workaround, thanks.

**Comment by dlfivefifty** [comment]
I'm seeing this too on High Sierra

**Comment by ViralBShah** [comment]
Curl 7.56 fixes this. Preparing a PR.

**Comment by Ken-B** [comment]
I just hit this issue on macOS 10.13.5 with Xcode 9.4.1 (`xcode-select install` already ran) and latest julia master (commit 9a4ecaa4e463c46e2071aa17b5c50212130e6799).

The old workaround still works though: `make CFLAGS=-Wno-error`.
