### ISSUE TITLE
Heterogeneous Array literals promote row by row

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#23994]
This surprised me:

```
julia> [1 "two"; 3im 4.0; 5 6//1]
3×2 Array{Any,2}:
    1           "two"
 0.0+3.0im  4.0+0.0im
   5//1       6//1
```

I would have expected promotion to have been completely disabled since there's a string in there.  Is this the expected behavior?  Is it useful?  Should we change it?

**Comment by StefanKarpinski** [comment]
Agree, this seems like a bug to me.

**Comment by JeffBezanson** [comment]
Also agree, we should change it.
