### ISSUE TITLE
linearindices(::String) is wrong

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#24006]
The [default method for `linearindices(A::Any)`](https://github.com/JuliaLang/julia/blob/37ad1206cbc36d2cb0c10c8110d42188b4203818/base/abstractarray.jl#L104) is `OneTo(length(A))`, which is wrong for `A::String`.

```jl
julia> linearindices("fooαβ")
Base.OneTo(5)

julia> collect(eachindex("fooαβ"))
5-element Array{Any,1}:
 1
 2
 3
 4
 6
```

Why is there an `::Any` method of this function at all?

**Comment by JeffBezanson** [comment]
Agree, that method should be removed.
