### ISSUE TITLE
'julia-config.jl': ldflag '-Wl,--export-all-symbols' is needed to compile dlls in Windows 

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/julia#24010]
@vtjnash 
See: [Compiling and building binaries from your julia code](https://discourse.julialang.org/t/compiling-and-building-binaries-from-your-julia-code/5687)
This is fixed with PR #24248

**Comment by ViralBShah** [comment]
The issue is that we need `--export-all-symbols` on Windows for static-julia. This used to work correctly at one point.

**Comment by vtjnash** [comment]
PackageCompiler contains the correct flags for linking a system image. This file is for configuring an external library to link against libjulia or a system image.
