### ISSUE TITLE
round methods missing in base

### ISSUE THREAD

**Issue by ethomag** [JuliaLang/julia#24021]
Referencing  this [discourse entry](https://discourse.julialang.org/t/round-methods-for-complex/6260)

In Julia 0.6, there seems to be some round methods missing for basic types in `Base`:

```
julia> round(Float32, 1.0)
ERROR: MethodError: no method matching round(::Type{Float32}, ::Float64)
[...]
julia> round(Float64, 1.0)
ERROR: MethodError: no method matching round(::Type{Float64}, ::Float64)
[...]
julia> round(Complex64, Complex(0, 1.0))
ERROR: MethodError: no method matching round(::Type{Complex{Float32}}, ::Complex{Float64})
[...]
```
I interpreted @StefanKarpinski 's entry as a request to file an issue.  I hope I did the right thing ?

**Comment by StefanKarpinski** [comment]
Perfect, thank you!

**Comment by ggggggggg** [comment]
This doesn't seem much nicer than `Float16(round(1.0)` but it does seem a bit more consistent with the docs. Here is an implementation

```
using Base.Test

myround(::Type{T}, x::AbstractFloat) where T<:Union{Real,Complex} = T(round(x))
myround(::Type{T}, x::AbstractFloat, r::RoundingMode) where T<:Union{Real,Complex} = T(round(x,r))
types = [Float16, Float32, Float64, BigFloat, Complex{Float64}, Int16, Int32, Int64, BigInt]
for T in types, S in types[1:4]
    @test myround(T, S(1.1))==1
    @test myround(T, S(1.1)) isa T
end
```

**Comment by BeastyBlacksmith** [comment]
I would like to add that I would like to see https://github.com/JuliaLang/julia/blob/master/base/floatfuncs.jl#L151-153 defined with `x::Number`, so that they work with Complex and other number-types (Measurements, Units, ... ).

**Comment by adienes** [comment]
I believe this is closed by https://github.com/JuliaLang/julia/pull/50812, which also closes the associated PR https://github.com/JuliaLang/julia/pull/30456
