### ISSUE TITLE
Another hook for codegen to help with WebAssembly

### ISSUE THREAD

**Issue by tshort** [JuliaLang/julia#24038]
At [ExportWebAssembly](https://github.com/tshort/ExportWebAssembly.jl), I've prototyped a package for converting Julia code to WebAssembly. It uses the awesome [LLVM](https://github.com/maleadt/LLVM.jl) package, and much of this code is straight from [CUDAnative](https://github.com/JuliaGPU/CUDAnative.jl/). This approach works much better than my previous efforts of trying to get `julia --output-bc` incantations to work.

Right now, it works fine for code using StaticArrays and other immutables. Nothing works that uses `ccall`'s, though. Using Emscripten, I've gotten big chunks of libjulia and libuv compiled to bitcode, so if I can get the `ccall`'s to link with that bitcode, that will open up much more Julia code that will compile to WebAssembly/JavaScript.

`llvmcall`'s are handled fine by this package. In `llvmcall`'s, you can include calls to functions that are declared but not defined. So, it may be possible to convert a `ccall` to an `llvmcall` with a declared function and let the linking happen later. 

Supporting `ccall` may require changes to codegen in Julia. So, would it be appropriate to add another hook or two to those added by @maleadt (#19290, #23581)? To get at the `ccall`'s before they are converted to calls to memory addresses, it looks like I need a hook earlier in the codegen process ([here?](https://github.com/JuliaLang/julia/blob/master/src/codegen.cpp#L3689)).

If hooks aren't the way to go, are there any other suggestions?

**Comment by Keno** [comment]
Seems reasonable to me.

**Comment by davidrapin** [comment]
Any updates on the status of this? I'm very interested.

**Comment by tshort** [comment]
I played around with it enough to find something that worked for my application, but it wasn't very general. I changed focus to try implementing codegen in Julia: https://github.com/tshort/CodeGen.jl

It's still a WIP.

**Comment by davidrapin** [comment]
Thank you for the update!
