### ISSUE TITLE
Binaries compiled with 'static-julia' on Windows do not print an error message when shared libraries cannot be found

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/julia#24044]
I am testing '[static-julia](https://github.com/JuliaComputing/static-julia)' on Linux and Windows.

On Linux, if I run a program compiled with 'static-julia' without the proper Julia shared libraries in path I get the following error message:

> error while loading shared libraries: libjulia.so.0.6: cannot open shared object file: No such file or directory

This is expected.

If I do the same on Windows, I do not get any error messages (the program simply does not do anything). The program should instead print the following error message:

> error while loading shared libraries: libjulia.dll: cannot open shared object file: No such file or directory

**Comment by StefanKarpinski** [comment]
This seems like an issue with https://github.com/JuliaComputing/static-julia more than here, no?

**Comment by lucatrv** [comment]
I can reproduce this issue with the following commands (without using 'static-julia'), that is why I opened it here, but if you prefere I can open this issue on the 'static-julia' repository instead.

File 'program.c':
```
#include <string.h>
#include <stdint.h>
#include "uv.h"
#include "julia.h"
extern void julia_main();
int main(int argc, char *argv[])
{
  intptr_t v;
  uv_setup_args(argc, argv);
  libsupport_init();
  jl_options.image_file = "libhello";
  julia_init(JL_IMAGE_CWD);
  julia_main();
  jl_atexit_hook(0);
  return 0;
} 
```

File 'hello.jl':
```
module mystuff
Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    println("hello, world")
    return 0
end
end
```

Build object file 'hello.o':
`julia -Cx86-64 "-J<juliainstalldir>\lib\julia\sys.dll" --compile=yes --depwarn=yes --startup-file=no --output-o hello.o -e "include("""hello.jl"""); push!(Base.LOAD_CACHE_PATH, """<userhome>\\.julia\\lib\\v0.6"""); empty!(Base.LOAD_CACHE_PATH)"
`

Build dynamic library 'libhello.dll':
`gcc -m64 -shared -o libhello.dll hello.o -std=gnu99 -I"<juliainstalldir>\include\julia" -DJULIA_ENABLE_THREADING=1 -L"<juliainstalldir>\bin" -Wl,--stack,8388608 -ljulia -lopenlibm -Wl,-rpath,\$ORIGIN -Wl,--export-all-symbols
`

Build executable 'hello.exe':
`gcc -m64 -o hello.exe program.c libhello.dll -std=gnu99 -I"<juliainstalldir>\include\julia" -DJULIA_ENABLE_THREADING=1 -L"<juliainstalldir>\bin" -Wl,--stack,8388608 -ljulia -lopenlibm -Wl,-rpath,\$ORIGIN
`

If I run 'hello.exe' with the Julia shared libraries in path I get "hello, world", If I run 'hello.exe' without the Julia shared libraries in path I get nothing (and no error messages).

**Comment by StefanKarpinski** [comment]
> I can reproduce this issue with the following commands (without using 'static-julia'), that is why I opened it here, but if you prefere I can open this issue on the 'static-julia' repository instead.

No, if it's an issue independent of `static-julia` then this is the right place. MWE appreciated!

**Comment by lucatrv** [comment]
I have just found that if I run `hello.exe` within the Windows Command Prompt I get the above described behavior, while if I run it within the Cygwin terminal I get the following message (expected):

> error while loading shared libraries: libjulia.dll: cannot open shared object file: No such file or directory

Maybe the issue is due to `MinGW-w64`?

**Comment by lucatrv** [comment]
I have finally confirmed that this issue is actually due to `gcc` itself on Windows. I have just reported it [here](https://cygwin.com/ml/cygwin/2017-10/msg00162.html). I am sorry for the false alarm.

**Comment by StefanKarpinski** [comment]
No worries, thanks for reporting in any case. Better a false alarm than a serious compilation bug that we don't know about.
