### ISSUE TITLE
REPL does not handle well multi-line input bigger than the screen 

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#24049]
When entering a mulit-line input bigger than the available number of lines in the screen window, it becomes impossible to navigate back to the beginning of the input (or it seems kind of possible in a blind way, i.e. the screen is not refreshed accordingly).

**Comment by oheil** [comment]
Confirmed problems with Julia 0.1.* under Windows 7 + 10 with terminal cmd.exe and powershell.
I you paste more lines into the REPL as lines visible in the terminal window, the pasted code is duplicated multiple times until the complete code is shown.
Or in aother words:
If you paste larger code into the REPL what happens is:
After some number of lines, typicaly more than the terminal window can show at once, the complete pasted code is printed newly from the beginning. This happens multiple times depending on the number of code lines pasted, until the last time, when the complete code is shown as one block.
Example result:

julia> function test()
julia> function test()
julia> function test()
           println("1")
julia> function test()
           println("1")
julia> function test()
           println("1")
           println("2")
julia> function test()
           println("1")
           println("2")
julia> function test()
           println("1")
           println("2")
           println("3")
julia> function test()
           println("1")
           println("2")
           println("3")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
           println("7")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
           println("7")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
           println("7")
           println("8")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
           println("7")
           println("8")
julia> function test()
           println("1")
           println("2")
           println("3")
           println("4")
           println("5")
           println("6")
           println("7")
           println("8")
           println("9")
           println("10")
           println("11")
           println("12")
           println("13")
           println("14")
           println("15")
           println("16")
           println("17")
           println("18")
           println("19")
           println("20")
           println("21")
       end
test (generic function with 1 method)

This does not happen with Windows but cygwin terminal.
