### ISSUE TITLE
bug in BigFloat trunc / floor / ceil / round

### ISSUE THREAD

**Issue by getzdan** [JuliaLang/julia#24041]
The following error should not occur, as `trunc(255.5)` is 255 which is a legal UInt8:

```
julia> trunc(UInt8,BigFloat(255.5))
ERROR: InexactError: trunc(UInt8, 2.555000000000000000000000000000000000000000000000000000000000000000000000000000e+02)
Stacktrace:
 [1] trunc(::Type{UInt8}, ::BigFloat) at ./mpfr.jl:209
```

The same logic applies to the other casting functions.

A proper solution should be to perform the `round`/`trunc`/`floor`/`ceil` in the source type, i.e. BigFloat and then cast to the target type and error if it doesn't fit correctly.

The relevant code is:

https://github.com/JuliaLang/julia/blob/c6899ecfd32b19279bd6e29ff2005ddfd3f4aab5/base/mpfr.jl#L207-L223

**Comment by StefanKarpinski** [comment]
> A proper solution should be to perform the round/trunc/floor/ceil in the source type, i.e. BigFloat and then cast to the target type and error if it doesn't fit correctly.

Yes, I do think that would work. The assumption required is that you can correctly do the round/trunc/floor/ceil operation in the original type. That seems like a reasonable requirement. Once the value is correct in the source type, the value can simply be converted and rely on domain checking of convert, so the implementation is quite simple:
```jl
$op(::Type{T}, x::Number) = convert(T, $op(x))
```

**Comment by drpn** [comment]
I would like to suggest a solution. Can't we convert BigFloat to AbstractFloat first and then, go for trunc?
Thats even working fine. Thus I want to know its performance too.

**Comment by StefanKarpinski** [comment]
> Can't we convert BigFloat to AbstractFloat first and then, go for trunc?

BigFloat is an implementation of AbstractFloat, so that conversion would do nothing.

**Comment by drpn** [comment]
Ok, can you just tell me how can I test if I edit the code which I have cloned in my desktop? I  want to try both the suggested one and mine.

**Comment by mbauman** [comment]
In simple cases like this you can just re-define the method at the REPL:

```
julia> @eval Base.MPFR function trunc(::Type{T}, x::BigFloat) where T<:Union{Signed,Unsigned}
            (typemin(T) <= x <= typemax(T)) || throw(InexactError(:trunc, T, x))
            println("NEW IMPLEMENTATION!")
            unsafe_cast(T, x, RoundToZero)
        end
WARNING: Method definition trunc(Type{T<:Union{Signed, Unsigned}}, Base.MPFR.BigFloat) in module MPFR at REPL[13]:2 overwritten at REPL[14]:2.
trunc (generic function with 66 methods)

julia> trunc(Int, big(2.4))
NEW IMPLEMENTATION!
2
```

**Comment by laborg** [comment]
This has apparently been handled in https://github.com/JuliaLang/julia/pull/29157
```julia
julia> trunc(UInt8,BigFloat(255.5))
0xff
```
