### ISSUE TITLE
API for directly accessing the selector bytes of an isbits Union Array

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#24057]
This wasn't included in the original work on isbits Union optimizations, but there are cases where it'd be useful to access the "selector" byte array directly for certain operations. If I recall, @vtjnash had some concerns around ensuring the byte array had correct owner lineage to the original array. I'll try to take a look into it this week.

**Comment by vtjnash** [comment]
We already have this (by working on the types with `isa`, for example).

**Comment by StefanKarpinski** [comment]
Can you explain in a bit more detail, please, @vtjnash? How do I get the selector bits of a union-typed vector?

**Comment by vtjnash** [comment]
`typeof`

**Comment by quinnj** [comment]
??

How do I get a `Vector{UInt8}` from `typeof`? That was the original ask here; there are certain APIs where it would be useful to get that vector directly.

**Comment by StefanKarpinski** [comment]
I agree that it would be nice to be able to get the selector bits directly, but let's make it an internal, non-exported API for now. We don't really want to commit to this yet long-term – it's too couple with our internals and might change in the future.

**Comment by nalimilan** [comment]
See [this Discourse thread](https://discourse.julialang.org/t/fastest-way-to-count-unique-elements-in-vector-union-bool-missing/8355) about a use case where accessing the underlying arrays could be useful for performance: counting the number of `true`, `false` and `missing` values in a vector.

**Comment by quinnj** [comment]
We now have `ccall(jl_array_typetagdata, Ptr{UInt8}, (Any,), A)` to get a pointer to the start of the selector bytes (which will have length equal to the length of the array). I'm sure @vtjnash has concerns around people actually doing anything w/ that, but I think w/ having to `ccall` + unsafe_wrap the result, it's sufficiently layered in enough "unsafeness" that the casual passerby would think twice before getting in too much trouble.

I think if people have more clear/concrete use-cases around needing these selector bytes, we can consider making them more safe/accessible, but for now, I think this should do.

**Comment by vtjnash** [comment]
Note that `unsafe_wrap` will _definitely_ corrupt both arrays mercilessly. You would have to hide any usage of this behind a function barrier to prevent LLVM from realizing it's allowed to destroy your program, and even then, it's pretty dangerous and a lot slower than just using `typeof(a[i])`, which already safely does exactly what this issue requests.
