### ISSUE TITLE
BitArray constructor should not accept any array of integers

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24062]
I find this behavior very surprising, even more so for `convert`:
```julia
julia> BitArray([0, 1, 2, 3])
4-element BitArray{1}:
 false
  true
  true
  true

julia> convert(BitArray, [0, 1, 2, 3])
4-element BitArray{1}:
 false
  true
  true
  true
```

Is this a remnant from times when `Bool(5) === true`? I suggest deprecating these before 1.0, especially given that we now have a very convenient way of performing this operation explicitly:
```julia
julia> [0, 1, 2, 3] .!= 0
4-element BitArray{1}:
 false
  true
  true
  true

```

**Comment by StefanKarpinski** [comment]
I agree in this case, but please use the "triage" label if you want to add something to 1.0.

**Comment by JeffBezanson** [comment]
I think all we need to do here is change `A[ind] != 0` to `convert(Bool, A[ind])` in the BitArray `convert` method.

**Comment by JeffBezanson** [comment]
```
julia> convert(BitArray, [0, "hello"])
2-element BitArray{1}:
 false
  true
```

**Comment by StefanKarpinski** [comment]
"The current behavior is just silly" – Jeff
