### ISSUE TITLE
Reserve a word for chaining

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#24082]
Using a word/symbol to refer to the previous result is by far the most straightforward implementation of chaining, IMO. So I think Julia should reserve a word/symbol to refer to a chained item before 1.0 hits, even if chaining itself isn't implemented. Possibilities include `it` or `ans`.

**Comment by andyferris** [comment]
I like the way that `ans` is the same as the REPL, but I've also suggested `_` as a right-hand-value for this. 

I agree this would be a simple and straightforward way to do chaining but I'd settle for `ans` or `_` after `|>`.

**Comment by bramtayl** [comment]
I've been convinced that _ as a right hand chained value is too confusing when it also means discard this as a l value. But it is convenient in that its already reserved

**Comment by bramtayl** [comment]
I like `it` because pronouns are English's build in system of chaining

**Comment by andyferris** [comment]
It's not a "binding", it's a "probinding" :)

**Comment by bramtayl** [comment]
what does that mean?

**Comment by andyferris** [comment]
Just being silly. 

Noun -> pronoun
Julia variable binding -> ?

**Comment by bramtayl** [comment]
Ah got it lol
