### ISSUE TITLE
how about rename `=>` to `:` in Dict?

### ISSUE THREAD

**Issue by moldray** [JuliaLang/julia#24106]
though many languages use `=>` in hash table,  it is not comfortable for keyboard input. how about rename it to `:` like objects in javascript?

**Comment by iblis17** [comment]
well, it's not Dict
```
julia> typeof("A" => "B")
Pair{String,String}
```

**Comment by KristofferC** [comment]
`a:b` already has a meaning (creates a range).

**Comment by moldray** [comment]
@KristofferC I see thanks!
