### ISSUE TITLE
Method specificity bug with Union

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24124]
On Julia 0.6, the third command returned `Void` because the first method was used. Is this expected?
```julia
julia> f(::Type{T}) where {T} = T
f (generic function with 1 method)

julia> f(::Type{Union{T, Void}}) where {T} = T
f (generic function with 2 methods)

julia> f(Void)
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] f(::Type{Void}) at ./REPL[6]:1
```

**Comment by JeffBezanson** [comment]
This might be unavoidable --- the second method is definitely more specific, and `f(Void)` matches it. You can use `@isdefined(T)` however.

**Comment by nalimilan** [comment]
I must say I have a hard time reasoning about which method is the most specific, so you think that's OK, it's fine with me. At least you get an error, which forces you to make a choice by defining `f(::Type{Null})`.

**Comment by ArchieCall** [comment]
I think you mean "specificity" rather than "specifity" in the title.

**Comment by rfourquet** [comment]
I don't really understand the issue, the second method is called on master (or maybe in the OP you mean the first method was called, not the second?)

**Comment by nalimilan** [comment]
Ah, right, I meant that the *first* method was used on Julia 0.6.

**Comment by StefanKarpinski** [comment]
> the second method is definitely more specific

Can you explain why, Jeff? I'm having trouble seeing it.

**Comment by yuyichao** [comment]
The second method matches a strict subset of signatures. e.g. `Int` won't match the second one but will match the first.

Note that the arguments are `::Type`.

**Comment by yuyichao** [comment]
And also note that when you don't have `::Type` the two are exactly the same so the second overwrite the first one.

```julia
julia> f(::T) where T = T
f (generic function with 1 method)

julia> f(::Union{T,Void}) where T = T
f (generic function with 1 method)

julia> f(nothing)
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] f(::Void) at ./REPL[2]:1
```

AFAICT this is a pretty confusing though also unambiguous case for specificity so I think this can be closed. The behavior change since 0.6 is a direct result of https://github.com/JuliaLang/julia/pull/23117 which removes the rule that previously make it dispatch to the second one.

**Comment by JeffBezanson** [comment]
A case where a method overwrite warning might be helpful :trollface: 

One intuitive way to look at it is that `Type{T} where T` matches any type whatsoever. So if you put more stuff in there, it can only get more specific. The only thing less specific would be `Any`.
