### ISSUE TITLE
How to work with an interval values

### ISSUE THREAD

**Issue by leaoshark** [JuliaLang/julia#24136]
my program have a

> sigma = 0.6 

, but i must change to 

> sigma = 0.319 / R

  , for R in [0.5:0.5:10]

and in the final line of the program i want to calculate an integral, and this integral depends of the R value ... for each R value i have a integral value ...  and i have to print a table of these values ... 

how can i do that ? 

i tried 

> R=[0.5:0.5:10] 
> sigma = 0.319./R

but is not working

**Comment by yuyichao** [comment]
Please use discourse.julialang.org for questions.
