### ISSUE TITLE
REPL: Include all *.jl-files in current directory by default

### ISSUE THREAD

**Issue by bwilliges** [JuliaLang/julia#24150]
Currently every single .jl file in the current directory must be included, before being usable from REPL.
Having a Python/Matlab background I found this behaviour a big hurdle.
Including files make sense for modules and packages, but for just quick running of a script it is too difficult.

Scenario:
myScript.jl

julia>myScript.jl

Expected behaviour:
myScript.jl will run

Current behaviour:
include("myScript.jl")
julia>myScript.jl

Proposed solution:
Inside of the REPL all .jl-files of the current directory as specified by pwd() are automatically included.

**Comment by KristofferC** [comment]
When you move from one language to another, it might be the case that you have to change your workflow slightly. While in e.g. Matlab, it is common to have one file per function, which exists in the global namespace if they are in your current working directory, that is not really how it works in Julia. Better ways to structure your code is, for example, to have a module that includes all the files you need. Then you can just include that file and you get everything inside the module.

If you are interested in workflow tips, I would suggest making a post at https://discourse.julialang.org/ which is a more suitable place to start when you are new to the langauge.

**Comment by djsegal** [comment]
see: https://discourse.julialang.org/t/how-to-organise-files-and-modules/4842/4
