### ISSUE TITLE
Libdl does not recognise homedir

### ISSUE THREAD

**Issue by AShedko** [JuliaLang/julia#24152]
When installing mxnet it did not install correctly, so i used a source distribution.
This line returns a `""`
`
Libdl.find_library(["libmxnet", "libmxnet.so"], ["~/mxnet/lib"])
`
while 
`
Libdl.find_library(["libmxnet", "libmxnet.so"], ["/home/ashedko/mxnet/lib"])
`
does return `"/home/ashedko/mxnet/lib/libmxnet"`

maybe consider permitting one to use `~` in paths in Libdl, as well as other

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/1136. No function will do that automatically.
