### ISSUE TITLE
Nested functions defined in If-Else block

### ISSUE THREAD

**Issue by jrsimmon** [JuliaLang/julia#24154]
I am having trouble defining nested functions in if-elseif-else blocks. Here is a particularly stark example illustrating the problem:

```
julia> function hello(a, b)
               if (a == b == 0)
                function hi()
                 return 0
                end
               elseif (a > 0) & (b == 0)
                function hi()
                 return 1
                end
               else
                function hi()
                 return 2
                end
               end
              end
hello (generic function with 1 method)

```

When the first nested case is invoked, the output is as expected:

```
julia> hello(0,0)
(::hi) (generic function with 1 method)
```

I receive an error when the latter cases are invoked:

```
julia> hello(1,0)
ERROR: UndefVarError: hi not defined
Stacktrace:
 [1] hello(::Int64, ::Int64) at ./REPL[1]:11

julia> hello(0,1)
ERROR: UndefVarError: hi not defined
Stacktrace:
 [1] hello(::Int64, ::Int64) at ./REPL[1]:11
```

Version information:
```
julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

I have read the documentation concerning variable scope within functions and nested functions, but have not found anything that suggests the syntax is illegal. What strikes me as odd about this behavior is that the function hi() is never actually called within the function hello() -- I only attempt to define it.

Thank you for your time!

**Comment by JeffBezanson** [comment]
Thanks for reporting this. See #15602 for some discussion and workarounds.

**Comment by jrsimmon** [comment]
Thanks for the quick response. This should suit my purposes for the moment, but are there workarounds for function definitions that can't be easily expressed in the form "f(x) = return value"?

**Comment by KristofferC** [comment]
You can do 

````
f = function(x)
    code
end
```

**Comment by jrsimmon** [comment]
See my original post -- that syntax appears unsupported when nested in an If-Else block within a function.

**Comment by yuyichao** [comment]
It is. Theres isn't a name after `function`.

**Comment by KristofferC** [comment]
I didn't use the same syntax as your original post.

```

julia> function g(x)
           if x < 2
               f = function(x)
                       println(x, " less than two")
               end
           else
               f = function(x)
                       println(x, " greater than two")
               end
          end
       end
g (generic function with 1 method)

julia> f1 = g(1)
(::#3) (generic function with 1 method)

julia> f1(2)
2 less than two

julia> f2 = g(3)
(::#4) (generic function with 1 method)

julia> f2(2)
2 greater than two
```

**Comment by jrsimmon** [comment]
My mistake, thank you for pointing this out.
