### ISSUE TITLE
signal (6): Abort trap:6 on emacs

### ISSUE THREAD

**Issue by hawkish** [JuliaLang/julia#24169]
I'm trying to use Julia and emacs in concert. 

I would really like to use Julia with a nice REPL, so I've been trying to setup julia-mode with julia-repl or Julia-shell or simply ESS, but everything I've tried results in the same error.  

To reproduce:
M-x ansi-term RET
julia> using Requests
julia> import Requests: get, post, put, delete, options
julia> get("http://www.google.dk")

Error:
signal (6): Abort trap: 6
while loading no file, in expression starting on line 0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2009569 (Pool: 2008310; Big: 1259); GC: 2
Abort trap: 6

I'm on MacOS High Sierra, Emacs 25.3 and Julia 0.6.0

**Comment by hawkish** [comment]
This issues seems to be already solved but never applied to the libuv fork. See the comments by @andreasnoack and @vtjnash in #18818. Any chance of this happening soon - and can I help?

**Comment by ararslan** [comment]
Sorry, this got auto-closed. Not fixed quite yet.
