### ISSUE TITLE
Can't interpolate in nested QuoteNodes

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#24172]
From this [discourse thread](https://discourse.julialang.org/t/escaping-in-nested-expr/6481/3). Here is what I was trying:

```
macro color_output(enabled, block)
    quote
        prev_color = Base.have_color
        eval(Base, :(have_color = $$enabled))
        $(esc(block))
        eval(Base, :(have_color = $prev_color))
    end
end
```

In a nested quotenode, you can use `$$var` to access `var` in the outer scope, and I'd expect to be able to use `$var` to access one level up, but it doesn't seem to work.

**Comment by JeffBezanson** [comment]
I believe this is a duplicate of #17588.

**Comment by ssfrr** [comment]
Yep, that definitely looks like the same thing. Closing as duplicate. Thanks!
