### ISSUE TITLE
Codegen bug with isa

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24177]
Both on Julia 0.6 and on current master, the following code does not throw an error as it should when Nulls from master is used. Yet it does if you comment out `using Nulls` and uncomment `struct Null end`.
```julia
using Nulls
#struct Null end
struct EachFailNull{T}
    x::T
end
Base.iteratorsize(::Type{EachFailNull{T}}) where {T} =
    Base.SizeUnknown()
Base.start(itr::EachFailNull) = start(itr.x)
Base.done(itr::EachFailNull, state) = done(itr.x, state)
@inline function Base.next(itr::EachFailNull, state)
    v, s = next(itr.x, state)
    v isa Null && error()
    (v, s)
end
collect(EachFailNull([1, Null()]))
```

Changing `next` to the following also fixes the problem:
```julia
@inline function Base.next(itr::EachFailNull, state)
    v, s = next(itr.x, state)
    if v isa Null
        error()
    else
        (v, s)
    end
end 
```

Cf. https://github.com/JuliaData/Nulls.jl/pull/50.

**Comment by vtjnash** [comment]
It looks like at some point during optimization, some pass is replacing the `ssavaluetype` for the return value `v` from `Union{Null, Int}` to just `Int`.

**Comment by KristofferC** [comment]
This cannot really be reprod anymore due to the change to the iteration protocol. Someone can make a new issue if something similar happens.
