### ISSUE TITLE
Inconsistent constraints on type variables are ignored without type application

### ISSUE THREAD

**Issue by julbinb** [JuliaLang/julia#24179]
Here is a julia 0.6.0 example:
```julia
julia> T where String<:T<:Signed
Signed
```
Lower bound is simply ignored, although `String` is not a subtype of `Signed`.

Also, this type is not equal to `Union{}`:
```julia
julia> (Ref{T} where String<:T<:Signed) <: Union{}
false
```
Despite the fact there are no valid instantiations of `T`. Of course, when we try to instantiate the type, we got an error message:
```julia
julia> (Ref{T} where String<:T<:Signed){Int}
ERROR: TypeError: Type: in T, expected String<:T<:Signed, got Type{Int64}

julia> (Ref{T} where String<:T<:Signed){String}
ERROR: TypeError: Type: in T, expected String<:T<:Signed, got Type{String}

julia> (Ref{T} where String<:T<:Signed){Signed}
ERROR: TypeError: Type: in T, expected String<:T<:Signed, got Type{Signed}

```

Version info:
```
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by JeffBezanson** [comment]
That is correct, we don't yet check consistency on type variable bounds. The right thing to do is probably check as soon as bounds have no free variables, and give an error if they're not consistent. It would be nice to check bounds even if they do have free variables, but it's not obvious how that should be done.

**Comment by vtjnash** [comment]
I don't think we must rigorously prove the type is inhabited during construction and subtyping (though it seems valid to replace the `UnionAll` with `Union{}` if we do prove it is uninhabited)

**Comment by nsajko** [comment]
I have no idea how viable fixing this in general is, but surely some simple cases should be handled? For example, when both bounds are concrete:

```julia-repl
julia> String <: (T where {String<:T<:Int})
false

julia> versioninfo()
Julia Version 1.11.0-DEV.1208
Commit b6825924aef (2024-01-06 08:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```
