### ISSUE TITLE
Upstream LLVM SROA miscomputation

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#24176]
So we don't forget: https://bugs.llvm.org/show_bug.cgi?id=34940

**Comment by yuyichao** [comment]
Seems to be not a llvm issue after all....

**Comment by StefanKarpinski** [comment]
Context from the upstream bug issue:
> @vtjnash: Sorry, this was just my confusion: I forgot to set the isPacked attribute in my code.

**Comment by yuyichao** [comment]
I believe https://github.com/JuliaLang/julia/pull/24197 has fixed this with tests.
