### ISSUE TITLE
isequal(x,y) appears twice in a row in docs

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#24188]
Follow this link to see: https://docs.julialang.org/en/stable/stdlib/base/#Base.isequal-Tuple{Any,Any}

The lower entry is not identical, it has all the same text as the top entry, plus info on `isequal(x::Nullable, y::Nullable)`.

Seems like the repetition should be avoided as it is in the case of the next method `isless`.

**Comment by nalimilan** [comment]
Thanks for the report. That's been fixed on master: https://docs.julialang.org/en/latest/stdlib/base/#Base.isequal
