### ISSUE TITLE
`@testset` doesn't handle variable as description

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#24201]
If you try to use a variable holding a string as a description for a `@testset`, it interprets it as the `TestSet` class to use. Is a workaround you can use `"$var"` instead of just `var`.

MWE:

```julia
julia> using Test

julia> desc = "description"
"description"

julia> @testset desc begin
           @test true
       end
ERROR: MethodError: objects of type String are not callable
Stacktrace:
 [1] macro expansion at /home/sfr/local/src/julia/usr/share/julia/site/v0.7/Test/src/Test.jl:931 [inlined]
 [2] anonymous at ./<missing>:?

julia> @testset "$desc" begin
           @test true
       end
Test Summary: | Pass  Total
description   |    1      1
Test.DefaultTestSet("description", Any[], 1, false)
```

Unfortunately I'm not sure if there's a good way for the macro to distinguish between `@testset MyCoolTestSet begin...` and `@testset somedescription begin...`, so perhaps the workaround here is the right thing to do. I wanted to flag it so folks could decide whether to leave as-is or whether it's worth figuring out a solution.

**Comment by StefanKarpinski** [comment]
What's the intended purpose of using a type as a testset name?

**Comment by KristofferC** [comment]
Custom testset implementation.

**Comment by StefanKarpinski** [comment]
Can `@testset` be made to behave the same way regardless of what the testset "name" is and just rely on dispatch to select different behaviors? The problem here is doing dispatch on the expression type, which doesn't have enough information.
