### ISSUE TITLE
Build failure with MKL and ICC

### ISSUE THREAD

**Issue by matteoacrossi** [JuliaLang/julia#24210]
Trying to build Julia v0.6 using ICC and MKL 2017 on a `CentOS 7` HPC 

I did the following

    git clone git@github.com:JuliaLang/julia.git
    git checkout v0.6.0

Created the file `Make.user` with

    USEICC = 1
    USEIFC = 1
    USE_INTEL_MKL = 1
    USE_INTEL_LIBM = 1

Sourced the MKL environment vars, and run `make`. I get 

```
$ make
  CC       src/libuv_la-fs-poll.lo
gcc: error: unrecognized command line option ‘-static-intel’
make[2]: *** [src/libuv_la-fs-poll.lo] Error 1
make[1]: *** [scratch/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/build-compiled] Error 2
make: *** [julia-deps] Error 2
```

**Comment by ViralBShah** [comment]
ICC is not a supported compiler.
