### ISSUE TITLE
Feature request: Allow for multiplication by juxtaposition of root operators

### ISSUE THREAD

**Issue by Sleort** [JuliaLang/julia#24226]
It would be great if writing e.g. `2√2` could be made valid syntax. (Currently, one has to write either `2sqrt(2)` or insert an explicit multiplication sign, like `2*√2`.)

**Comment by ararslan** [comment]
My only reservation about this would be that `p√a` could be mistaken for the `p`th root of `a`:

![oaz9e](https://user-images.githubusercontent.com/6396159/31801278-dccb8c90-b4fb-11e7-8296-4e9c529f6c6c.png)

(`p` and `a` chosen based on first Google result for that image)

**Comment by Sleort** [comment]
I see your point, but to me `p√a = p*√a` is more natural (and very common in mathematical literature). I think the "could be mistaken for the `p`th root of `a`" is more of a symptom of being used to bad mathematical typography, and hence "you parse the expression in your head" to something like $\sqrt[p]{a}$ (Latex)?

Also, [the manual](https://docs.julialang.org/en/stable/stdlib/math/#Base.sqrt) says
> prefix operator √ is equivalent to sqrt
so why shouldn't `2√a = 2sqrt(a)`? To the non-expert user, I don't think this is obvious at all. At least I was surprised when `2√2` gave me an error...

**Comment by martinholters** [comment]
Should this be special to `√`, or for all unary-only operators? Not that `2!false` is particularly useful, but for consistency, it should then probably work (and give `2`)?

**Comment by cossio** [comment]
@martinholters I agree. There should not be a special rule for `√`
