### ISSUE TITLE
Remove DirectIndexString from Base

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#24259]
It was discussed in #23805 that `DirectIndexString` should be moved from Base to LegacyStrings.

I can start working on it. However, I am not sure about the expected details of this process. In particular:
* should it be moved to LegacyStrings first and after it is merged there be removed from Base (those are two separate repositories);
* `nextind` and `prevind` for `DirectIndexString` are inconsistent with other `AbstractString` types - should this be fixed or left as is for backward compatibility?
* I understand that this code should be included only under versions later than 0.6 - is the best practice for that to wrap the code in `if VERSION >= v"0.6.0"` block?

CC @nalimilan @ararslan @StefanKarpinski

**Comment by ararslan** [comment]
I recommend taking a look at the structure of LegacyStrings. As an example, I have a PR up there that adds `RevString`. Putting stuff in there is pretty straightforward. You just move the type and all of the Base methods for it.

**Comment by nalimilan** [comment]
No need to change the behavior of `prevind` and `nextind` since `DirectIndexString` will be semi-deprecated in LegacyStrings anyway.

**Comment by bkamins** [comment]
close?
