### ISSUE TITLE
more Unicode dots as infix operators

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#24269]
This is a feature request to add `…` (`\dots`) and `⋯` (`\cdots`) as infix operators, possibly with the same precedence as `..` (8).

Currently, `…` cannot be used as a function name at all, while `⋯` works, but is not infix:
```julia
julia> …(a,b) = a+b
ERROR: syntax: invalid character "…"

julia> ⋯(a,b) = a+b
⋯ (generic function with 1 method)

julia> 1⋯2
ERROR: UndefVarError: ⋯2 not defined

julia> ⋯(1,2)
3
```

This would be useful to define alternatives to `:` (with different, but related semantics) in packages. @timholy's [IntervalSets.jl](https://github.com/JuliaMath/IntervalSets.jl) uses `..`, other operators would be good to have to avoid conflict.

(Incidentally, font rendering of these characters was discussed in https://github.com/JuliaLang/julia/pull/8636, but as they are supported already I assume this is not an issue).

**Comment by JeffBezanson** [comment]
Looks like we should add `\cdots` to the `..` precedence level at least. I'm less sure about `\dots`, and that would be a less breaking change since it's currently disallowed.
