### ISSUE TITLE
rename `bits` to `bitstring`?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24263]
Mentioned [here](https://github.com/JuliaLang/julia/issues/20402#issuecomment-334796455), the `bits` function, as named, should return a vector of Bools, but instead returns a string of `'0'` and `'1'` characters that are a convenient representation of the bits of the item in question. Rather than change the functionality to something less convenient, I propose renaming the function to `bitstring` which indicates that it returns a string representing the bits.

**Comment by JeffBezanson** [comment]
Closed by #24281.
