### ISSUE TITLE
SIGPIPE on Windows builders

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#24268]
On the windows buildbots, the NSIS installer maker is reliably throwing a SIGPIPE when run within buildbot.  [Here's an example log](https://buildog.julialang.org/#/builders/74/builds/139/steps/11/logs/stdio).  Unfortunately, this does not occur when the NSIS installer is run outside of the buildbot environment.  As best I can tell, the actual way in which subprocesses are invoked from within buildbot is by using `twisted.internet.process.Process()`, but I have not had time to try to reproduce yet.

**Comment by staticfloat** [comment]
@vtjnash pointed out [this issue](https://github.com/buildbot/buildbot/issues/3153), which got me to try running the `nsis.exe` invocation inside of python then call `output.decode('utf-8')`, which threw the same error we see in the logs, due to `nsis.exe` outputting some kind of weird non-UTF-8 symbol, probably for a copyright symbol.

I've switched the default encoding on windows buildbots to `ISO-8859-1` which, during manual testing, allowed it to properly decode the `nsis.exe` output.  We'll be able to see if this fixes the windows buildbots after we fix the libgit2 problems. (https://github.com/JuliaLang/julia/issues/24611)

**Comment by JeffBezanson** [comment]
Wow, because of a copyright symbol, the kingdom was lost :-P

**Comment by staticfloat** [comment]
This is confirmed fixed.  🙌
