### ISSUE TITLE
replace ambiguous scale! methods

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#24276]
Discussion in #16772 revealed some dubious `scale!` methods. For example (https://github.com/JuliaLang/julia/issues/16772#issuecomment-236724393), determining what either of
```julia
scale!(A::AbstractArray{T<:Any,2}, b::AbstractArray{T<:Any,1}) at linalg/generic.jl:477
scale!(b::AbstractArray{T<:Any,1}, A::AbstractArray{T<:Any,2}) at linalg/generic.jl:478
```
does requires reading the associated code. And as `@Keno` suggests, expressing these operations as e.g. `A*Diagonal(B)` might be better. Best!

**Comment by Sacha0** [comment]
Moreover we should consider whether `scale!` should exist at all: Two-argument `scale!` methods are just in-place multiplication, and (the undocumented) three-argument `scale!` methods are just out-of-place multiplication. If we address https://github.com/JuliaLang/julia/issues/16772#issuecomment-338496796, all `scale!` methods could then simply disappear into in-place and out-of-place multiplication. Best!

**Comment by andreasnoack** [comment]
The fundamental question here is exactly the same as in #16772 so let's keep the general discussion in that issue. Whatever we decide and as you point out, it makes sense to deprecate these in favor of mutating multiplication. The methods are already defined in https://github.com/JuliaLang/julia/blob/0385a60fc7d46569ef48e6e4db70190febf8c0ca/base/linalg/diagonal.jl#L233-L238.

**Comment by Sacha0** [comment]
> The fundamental question here is exactly the same as in #16772 so let's keep the general discussion in that issue.

Yes, apart from the additional question of whether `scale!` should exist all :).

**Comment by Sacha0** [comment]
Triage settled on deprecating `scale!` in favor of `mul!` once the in-place/out-of-place `mul!` question is settled. Best!

**Comment by JeffBezanson** [comment]
That implies that mul1! and mul2! should be exported, since `scale!` currently is.

**Comment by andreasnoack** [comment]
Let me do it.
