### ISSUE TITLE
Repeated code_warntype output changes

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#24277]
Calling `@code_warntype` twice yields different-but-equivalent results in 0.6:

```julia
julia> g(x) = true
g (generic function with 1 method)

julia> @code_warntype g(1)
Variables:
  #self#::#g
  x::Int64

Body:
  begin 
      return true
  end::Bool

julia> @code_warntype g(1)
Variables:
  #temp#@_1
  #temp#@_2

Body:
  begin 
      return $(QuoteNode(true))
  end::Bool
```
It looks inconsequential, but I'm reporting it in case it's a symptom of some other underlying problem.

**Comment by JeffBezanson** [comment]
It is inconsequential. This is fixed on master; it was just a matter of being inconsistent about when to wrap things in `QuoteNode`.
