### ISSUE TITLE
Exceedingly long compilation time of a function involving StaticArrays

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#24286]
I have a function which takes way too much to be compiled on Julia master, 10x slower than on Julia 0.6.  It involves `StaticArrays.jl`.  Actually, this package seems to be quite broken right now on Julia master, just entering the line `Svector` makes Julia crash very badly.

That said, until a couple of days ago this function:
```julia
using StaticArrays

const A1 = SVector(collect(1.0:60.0))
const B1 = SVector(collect(1.0:60.0))
const C1 = SVector(collect(1.0:60.0))
const D1 = SVector(collect(1.0:60.0))
const A2 = SVector(collect(1.0:60.0))
const B2 = SVector(collect(1.0:60.0))
const C2 = SVector(collect(1.0:60.0))
const D2 = SVector(collect(1.0:60.0))

function test()
    arg1 = A1 * 1.0 + B1 * 2.0 + C1 * 3.0 + D1 * 4.0
    arg2 = A2 * 1.0 + B2 * 2.0 + C2 * 3.0 + D2 * 4.0
    e = sin.(arg1)
    f = cos.(arg1)
    g = sin.(arg2)
end
```
took about 9-10 seconds to be run the fist time on Julia master (so including compilation time), while it takes ~0.9 seconds to be run the first time on Julia 0.6.  The code returned by `@code_llvm` on Julia master is *loooong*, more than 5k lines, it doesn't fit in my terminal screen.  My full (non-minimal) function takes actually even longer to be compiled, about 35 seconds, In Julia 0.6 it takes 1.5 seconds, what seems to cause the huge slowdown should be those `sin` and `cos` calls.

I was trying to reduce further the example, but a few minutes ago I updated Julia and I don't have the time to go back to a working version.

**Comment by pkofod** [comment]
This will probably be due to the inlining that is due to be removed again in 

https://github.com/JuliaLang/julia/pull/24117

:)

**Comment by giordano** [comment]
Thanks for looking into this!  I'll let you know if this is indeed fixed by merging your PR as soon as I'll be able to use `StaticArrays.jl` again on master.

**Comment by fredrikekre** [comment]
Seems to be back on 0.6 times after #24117. Timings for first and second call:
```julia
julia> @time test();
  0.973949 seconds (776.59 k allocations: 36.718 MiB, 1.00% gc time)

julia> @time test();
  0.000012 seconds (5 allocations: 704 bytes)
```

**Comment by giordano** [comment]
How can you precompile `StaticArrays` at all?
```julia
INFO: Precompiling module StaticArrays.
ERROR: LoadError: UndefVarError: S not defined
Stacktrace:
 [1] StaticArrays.Size(::Type{SYSTEM: show(lasterr) caused an error
UndefVarError(:N)

Stacktrace:
 [1] StaticArrays.Size(::Type{StaticArrays.SArray{Tuple{S},T,1,S} where T where S}) at /home/mose/.julia/v0.7/StaticArrays/src/traits.jl:51
 [2] length(::Type{StaticArrays.SArray{Tuple{S},T,1,S} where T where S}) at /home/mose/.julia/v0.7/StaticArrays/src/abstractarray.jl:2
 [3] convert at /home/mose/.julia/v0.7/StaticArrays/src/convert.jl:21 [inlined]
 [4] StaticArrays.SArray{Tuple{S},T,1,S} where T where S(::Array{Float64,1}) at /home/mose/.julia/v0.7/StaticArrays/src/convert.jl:4
 [5] include_relative(::Module, ::String) at ./loading.jl:509
 [6] include(::Module, ::String) at ./sysimg.jl:15
 [7] include(::String) at ./sysimg.jl:54
 [8] eval(::Module, ::Expr) at ./repl/REPL.jl:3
 [9] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./repl/REPL.jl:69
 [10] macro expansion at ./repl/REPL.jl:100 [inlined]
 [11] (::getfield(Base.REPL, Symbol("##1#2")){Base.REPL.REPLBackend})() at ./event.jl:96
```

**Comment by fredrikekre** [comment]
`¯\_(ツ)_/¯` Used current julia master (https://github.com/JuliaLang/julia/commit/7ae9955c933ff11182f0d383592d70304ee4be68) and StaticArrays master (https://github.com/JuliaArrays/StaticArrays.jl/commit/715fefe58bef7ef1d9b2e693d3468d4fd585e11f)

**Comment by giordano** [comment]
Exactly same configuration here...

**Comment by fredrikekre** [comment]
Oh, and I also changed `SVector(collect(1.0:60.0))` to `SVector(1.0:60.0...)`, seems like the constructor from `Vector` is broken.

**Comment by giordano** [comment]
You cheated! ;-)  Ok, now it works for me and the reported issue is indeed fixed, thanks.  However, running the function is slightly slower on master than on Julia 0.6, 2.400 μs vs 2.127 μs, according to `BenchmarkTools.jl`.
