### ISSUE TITLE
BLAS: Local vs Remote Numerical Differences

### ISSUE THREAD

**Issue by klowrey** [JuliaLang/julia#24291]
In the course of making a distributed conjugate-gradient method, I started noticing numerical errors that were breaking algorithmic expectations ( negative dot(x,b) when solving for Ax=b ). I think I've boiled down to at least one essential component: BLAS performs different calculations on different processor families.
In the following code, we have a function performing some matrix math and returning the result before comparing the results. When we fix the number of BLAS threads used, all local computation we expect to be the same. Even with a fixed number of BLAS threads, the computation on a remote node produces different results.

```
#addprocs(1)
addprocs(["hulk"]) # remote (different computer) process
@everywhere function foo(n,t=1)
   BLAS.set_num_threads(t)
   srand(12345)
   NUM = n
   x = rand(Float32, NUM, NUM)
   y = x*x'
   return y
end

for i=1:11
   n = 2^i
   v =foo(n)
   v1=remotecall_fetch(foo, 1, n) # same function, same process
   v2=remotecall_fetch(foo, 2, n) # same function, different process
   d1 = v-v1
   d2 = v-v2
   if d1 != d2
      println("$n")
      @printf "L: %8.16f\n" maximum(d1)
      @printf "R: %8.16f\n" maximum(d2)
      println()
   end
end
```
So, for even a 4x4 matrix, I get the following:
```
4
L: 0.0000000000000000
R: 0.0000002384185791
...
2048
L: 0.0000000000000000
R: 0.0001831054687500
```
The error for the remote process increases with the matrix size used, of course. Using double precision of course reduces the 'error' but still, there is a difference between the two processors:\
```
# Remote
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
# Local
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

While I can't expect that Floating point calculations be entirely consistent, this seems a bit unreliable and can affect distributed calculations greatly; I know how I can re-write my distributed CG to avoid this problem, but are there work-arounds to ensure similar calculations for different processes? Even different number of blas threads used on one machine can cause this affect [discourse thread here](https://discourse.julialang.org/t/distributed-conjugate-gradient-numerical-errors/6602/8). For example, if i compiled Julia with MKL would this still be an issue?

**Comment by andreasnoack** [comment]
There is nothing we can do here. These differences are within the magnitude of what can be expected from different architectures. The difference can be reproduced on a single machine by setting `OPENBLAS_CORETYPE`. The relative difference between the results is pretty small, e.g. for `n=2048` I get
```julia
julia> maximum(abs, oldB["B"] - B)/maxabs(B)
7.503469f-7
```
which not much larger than `eps(Float32)`. Normally, relative differences of this magnitude shouldn't be a concern but if you really want to avoid differences like these, you could look into http://bebop.cs.berkeley.edu/reproblas/. I know that there are efforts to write an implementation in Julia but I don't know the current status of the project.
