### ISSUE TITLE
parsing of parenthesized expressions in compact for loops

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#24294]
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.2270 (2017-10-22 23:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  expandlower/385177d (fork: 1 commits, 1 day)
|__/                   |  x86_64-apple-darwin15.6.0

julia> foo(x) = for k in x println(1) end
foo (generic function with 1 method)

julia> bar(x) = for k in x (println(1)) end

ERROR: syntax: space before "(" not allowed in "x '('"

julia> baz(x) = for k in x; (println(1)); end
baz (generic function with 1 method)
```
The error exists to disallow e.g. `f (a, b)` rather than `f(a, b)` (https://github.com/JuliaLang/julia/commit/dacbdd453ca043d57b2812664adcd50630e205e6). If possible, simultaneously interpreting the user's code more charitably in such compact for loops might be nice? Best!

**Comment by JeffBezanson** [comment]
No, this is ambiguous. Also note that the extra parens around `println(1)` aren't necessary,
```
baz(x) = for k in x; println(1); end
```
is sufficient.

**Comment by Sacha0** [comment]
> No, this is ambiguous.

Though ambiguous, doesn't one interpretation make sense in this context, while the other doesn't?

> Also note that the extra parens around println(1) aren't necessary

Yes, I have expressions more complex than the above illustration in mind :).

**Comment by Sacha0** [comment]
Perhaps I miss an ambiguity you see. To clarify, I see two interpretations of
```julia
for k in x (println(1)) end
```
Either (1) the loop's iterable is a function call with a space separating the name and arguments (i.e. `x (println(1))`) and the loop body is empty, or (2) the loop's iterable is `x` and the loop body is `(println(1))`. Calling a function with a space separating the name and arguments is not allowed, so only (2) seems like a reasonable interpretation? Thanks!

**Comment by JeffBezanson** [comment]
One issue is that a user might not realize that `f (x)` is disallowed, and intend it to be a function call, and then silently get a strange different behavior. The other issue is that using the other interpretation would make parsing more complex and unpredictable.
