### ISSUE TITLE
Wrong ARPACK error messages

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#24292]
As pointed out in https://github.com/JuliaLang/julia/pull/24192#discussion_r146352634, the error messages in the show method for `ARPACKException` are not always correct. There are two kinds of ARPACK subroutines (eupd and aupd) that use the same error codes for completely different errors. Right now, the error messages from eupd are used for all exceptions.

Previously, it has been discussed that ARPACK throws more than it should since it is sometimes useful to have access to the intermediate output in cases where we throw, e.g. when the maximum number of iterations has been reached. Hence, this issue could also be fixed as part of a more general adjustment of the error handling in our ARPACK wrappers.

**Comment by ViralBShah** [comment]
Basically, in https://github.com/JuliaLang/julia/blob/master/stdlib/IterativeEigenSolvers/src/arpack.jl, we need to introduce function specific error messages, and also map the codes to strings in a dictionary. 

Should be straightforward.

**Comment by ViralBShah** [comment]
I guess the real question is whether we want more Exception types.

**Comment by andreasnoack** [comment]
Tracked in https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/16
