### ISSUE TITLE
Nightly OSX builds failing with "hdiutil: mount failed - image not recognized"

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#24308]
Example: https://travis-ci.org/simonster/JLD2.jl/builds/291950847?utm_source=github_status&utm_medium=notification

But it's every package I've tried lately.

**Comment by ararslan** [comment]
I think the nightly buildbots have been down, which means that `curl` is probably producing an empty .dmg file which can't be mounted. @staticfloat?

**Comment by ararslan** [comment]
This should be fixed by https://github.com/travis-ci/travis-build/pull/1239.
