### ISSUE TITLE
JULIA_ENV

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#2430]
instead of allowing `using` to take arguments, I thought it might make sense to provide a global dictionary `CONFIG` of type `Dict{String, Any}`, roughly equivalent to `ENV` that could take arbitrary configuration parameters.
e.g.

``` julia
CONFIG["PyCall/Python"] = "/usr/bin/python2"
CONFIG["gfx/backend"] = "gtk" # shared graphics property using pseudo-group "gfx"
CONFIG["Winston/backend"] = "tk" # graphics override for Winston
CONFIG["answer_color"] = "green" # a configuration property currently in ENV["JULIA_ANSWER_COLOR"]
CONFIG["OUTPUT_STREAM"] = PipeBuffer() # properties don't need to be strings
```

(note the convention that items in base will be only names, whereas Modules should prefix their variables with their uppercase module name, or a meaningful lowercase string if it is a shared option)

and then we can also allow a callback notification function to be registered which can do additional work and/or disallow changes:

``` julia
CONFIG_cb["OUTPUT_STREAM"] = function(new_val, old_val)
    if isa(new_val, IO)
        OUTPUT_STREAM = new_val
        true
    else
        false
    end
end
```

edit: replaced `JULIA_ENV` variable with `CONFIG`

**Comment by StefanKarpinski** [comment]
This will be part of Pkg3:

https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md#runtime-configuration

But can only be given at the project environment level, not globally, and not in packages.
