### ISSUE TITLE
document & speed up isless for tuples

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#24330]
Unless I'm missing something, it doesn't seem to be documented anywhere that `isless` for tuples is lexicographical.  Can we document this more clearly?

A common question on the mailing lists (e.g. [here](https://groups.google.com/d/msg/julia-users/MsBCWqrwWfw/SowNYHwzDAAJ) or [here](https://discourse.julialang.org/t/the-sorting-of-tuples/6682/3)) and elsewhere (e.g. [here](JuliaCollections/SortingAlgorithms.jl/issues/12) or [here](https://stackoverflow.com/questions/35805099/julia-sorting-a-matrix-by-2-columns-in-different-orders)) is how to sort lexicographically in Julia.  The answer, of course, is to use tuples, but it would be easier for people to figure this out if we documented it in the sorting section.

Also, I noticed that the [`isless(::Tuple,::Tuple)` implementation](https://github.com/JuliaLang/julia/blob/b74b30422c9f7ecd49d723ed3045bc969810ad61/base/tuple.jl#L286-L295) uses explicit runtime loops, rather than unrolling the loop when the tuple type is known at runtime.  Replacing this with a compile-time loop (via the usual dispatch tricks) would be an easy speedup (for the common case of short tuples).

For example, a completely unrolled `isless` for tuples of 3 elements is `isless3(a,b) = isequal(a[1],b[1]) ? (isequal(a[2],b[2]) ? isless(a[3],b[3]) : isless(a[2],b[2])) : isless(a[1],b[1])`, and on my machine this is significantly faster than `isless`:
```jl
julia> a = (1,2,3); b = (1,2,4);

julia> @btime isless($a, $b);
  5.235 ns (0 allocations: 0 bytes)

julia> @btime isless3($a, $b);
  3.207 ns (0 allocations: 0 bytes)
```

**Comment by KristofferC** [comment]
Why couldn't LLVM unroll the loop by itself? It knows the number of iterations statically. Anyway, there is an `@inbounds` missing.
