### ISSUE TITLE
Interaction of setenv and cmd interpolation

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#24353]
I think interpolating a cmd that had its env set should either raise an error or propagate the environment. Current behavior:

```
julia> c = setenv(`x`, "A"=>true)
setenv(`x`,String["A=true"])

julia> `$c`
`x`
```

**Comment by Keno** [comment]
Just ran into this again. We missed 1.0 of course, but marking for triage on what to do here.

**Comment by Keno** [comment]
Quick discussion with @JeffBezanson, one possible solution may be to allow interpolation in first position, but make it an error everywhere else.

**Comment by vtjnash** [comment]
Also, by `setenv`, I assume we mean, "all keyword args to the Cmd constructor (ignorestatus, env, dir, detach, windows_verbatim, windows_hide, flags)"

**Comment by StefanKarpinski** [comment]
Triage decision:
- if a command with environment is spliced into the first position in another command, then we should propagate the environment
- if a command with environment is spliced into another command anywhere else, then it should be an error since we can't know what was intended
