### ISSUE TITLE
Tell GitHub to add Julia dependecies

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/julia#24375]
GitHub has a feature to display dependencies for a repo (mainly for JavaScript and Ruby)

https://help.github.com/articles/listing-the-packages-that-a-repository-depends-on

It works by checking a json file or gemfile. So I sent Github a message saying that it should be easily possible for them to also check the [REQUIRE](https://docs.julialang.org/en/stable/manual/packages/#Requirements-Specification) file for Julia packages for dependencies. They responded by saying they have forwarded this request to their team, but cannot guarantee anything.

So if you are also interested in seeing this feature, perhaps consider sending a [support ticket](https://github.com/contact) to express your interest in having a Julia dependency feature on the Github website. If more than one person expresses an interest, it might have a chance of becoming a reality.

Regards,

https://discourse.julialang.org/t/tell-github-to-add-julia-dependecies/6691

@jballanc  came up with this message:

> The Julia programming language has adopted a standard format for packages that includes a way to specify dependencies, described here: https://docs.julialang.org/en/stable/manual/packages/#Requirements-Specification-11 . The developers of the Julia language and the larger Julia community have eagerly embraced GitHub as a platform, relying on it for everything from organizing groups of developers (e.g. https://github.com/JuliaStats, https://github.com/JuliaIO, https://github.com/JuliaDB, and many more) to serving as the central store for Julia packages. Given how integral GitHub already is in the Julia ecosystem, having the ability to visualize the dependencies of any package right on the GitHub web interface would be immensely helpful. Please consider adding support for parsing and presenting the data in Julia packages’ REQUIRE files in addition to the existing support for Gemfile and package.json files.

**Comment by yuyichao** [comment]
This doesn't seem to be an actionable issue here. Discourse is good enough for this.
