### ISSUE TITLE
@raw_str backslash inconsistency

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/julia#24417]
On julia 0.6.0, win64 binary build:
The parsing of \ inside of @raw_str macro is not 100%. the REPL + parser canot deal correctly with backslash at the end of string literal. Actually it interprets this as escaping the `"` indicating the end of string literal. Example from jupyter (becuse on repl `\"` is incomplete and cannot be entered).
```julia
> raw"\\"
"\\\\"
> raw"\"
syntax: incomplete: invalid string syntax

Stacktrace:
 [1] include_string(::String, ::String) at .\loading.jl:515
```
I understand this is not solvable inside the `raw""` macro. On the other hand, I find the macro extremely useful on windows for dealing with the path to files (especially long paths...) . I know it is a fault of windows, but we (windows users) must live with it.
If there is no better way to solve it, I'll do PR into the doc so it is an expected behavior.

**Comment by fredrikekre** [comment]
#22926

**Comment by phlavenk** [comment]
Ok, didn't know it's a hot topics right now. Definitely worth solving for 1.0. Closing in favor of #22926.
