### ISSUE TITLE
make `prod(::Vector{Bool})::Int`?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24425]
Came up over here: https://github.com/JuliaLang/julia/pull/24396#discussion_r147857846. We already have `sum([false,false,false]) === 0` but we have `prod([true,true,true]) === true`. I understand the logic that the value of the product can only be `true` or `false` so it might as well be of type `Bool`, but I think it makes sense that `sum` and `prod` return the same type; if someone really wants a `Bool` result, they can always use `all`.

**Comment by ararslan** [comment]
Personally I like the idea of deprecating `sum` and `prod` on collections with `Bool` elements in favor of `count` and `all`, respectively. (Though it may only make sense to do that if we didn't have `Bool <: Integer`, otherwise that would be a bit inconsistent.)

**Comment by StefanKarpinski** [comment]
I don't think it's justifiable not to allow `sum` and `prod` on booleans unless they're made non-numbers – which we've already decided is too annoying and disruptive.

**Comment by JeffBezanson** [comment]
-1. The same difference exists for the scalar operation:

```
julia> false+false
0

julia> false*false
false
```

I don't see much reason to introduce a different result type just because a reduction is being done.

**Comment by StefanKarpinski** [comment]
Based on triage discussion, we seem to be at a local optimum, with booleans behaving as strong zero and strong one for multiplication whereas as long as booleans are numbers, summing them is useful. FWIW, Knuth is very pro strong zero as a concept: https://arxiv.org/abs/math/9205211.
