### ISSUE TITLE
String(::Symbol) == string(::Symbol)

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#24436]
Bug of feature?

```julia
julia> String(:Hello)
"Hello"

julia> string(:Hello)
"Hello"
```

Should `string(:Hello)` return `":Hello"` instead?

For `Vector{UInt8}`, `string` produces a "code string" describing the vector and `String` converts the bytes to a `String`. 
```julia
julia> v = UInt8[0x48, 0x65, 0x6c, 0x6c, 0x6f]

julia> string(v)
"UInt8[0x48, 0x65, 0x6c, 0x6c, 0x6f]"

julia> String(v)
"Hello"
```

Looking at it another way, in one case the result of `string` is parseable and in the other it isn't:
```julia
julia> eval(parse(string(v))) == v
true

julia> eval(parse(string(s))) == v
ERROR: UndefVarError: Hello not defined
Stacktrace:
 [1] eval(::Module, ::Any) at ./boot.jl:288
 [2] eval(::Any) at ./boot.jl:287
```

**Comment by yuyichao** [comment]
AFAICT this is not a bug.

> `julia> eval(parse(string(v))) == v`

No, that's kind of what `show` is for, now `string`. After all, `string("Hello")` isn't `"\"Hello\""`.

**Comment by JeffBezanson** [comment]
`string` gives you the output of `print`, and `repr` gives you the output of `show`. So, feature :)
