### ISSUE TITLE
Julia 0.6.1: make install is trying to build documentation again

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#24432]
Hi guys,

I am trying to pack julia 0.6.1 to openSUSE. However, in the build process (`make install`), I am seeing this error:

```
[  497s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/julia'
[  497s] Warning: git information unavailable; versioning information limited
[  497s] make[2]: '/home/abuild/rpmbuild/BUILD/julia/usr/lib/julia/sys.so' is up to date.
[  497s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia'
[  497s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/julia/doc'
[  497s] Warning: git information unavailable; versioning information limited
[  497s] /home/abuild/rpmbuild/BUILD/julia/deps/tools/jldownload http://www.unicode.org/Public/9.0.0/ucd/UnicodeData.txt
[  497s] Could not find working curl, wget, or fetch.
[  497s] You need to install one of these to download dependencies.
[  497s] make[2]: *** [Makefile:22: UnicodeData.txt] Error 1
[  497s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia/doc'
[  497s] make[1]: *** [Makefile:119: docs] Error 2
[  497s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia'
[  497s] make: *** [Makefile:59: /home/abuild/rpmbuild/BUILD/julia/doc/_build/html/en/index.html] Error 2
[  497s] error: Bad exit status from /var/tmp/rpm-tmp.DCcxzr (%install)
[  497s] 
[  497s] 
[  497s] RPM build errors:
[  497s]     Bad exit status from /var/tmp/rpm-tmp.DCcxzr (%install)
```

This is really strange, because the file `/home/abuild/rpmbuild/BUILD/julia/doc/_build/html/en/index.html` exists. Furthermore, I had no problem with julia v0.6.0 and nothing seems to have changed between v0.6.0 and v0.6.1 with respect to the Makefiles.

**Comment by ronisbr** [comment]
I am using the following patch as a workaround:

```patch
Index: julia/Makefile
===================================================================
--- julia.orig/Makefile
+++ julia/Makefile
@@ -332,7 +332,7 @@ define stringreplace
 	$(build_depsbindir)/stringreplace $$(strings -t x - $1 | grep '$2' | awk '{print $$1;}') '$3' 255 "$(call cygpath_w,$1)"
 endef
 
-install: $(build_depsbindir)/stringreplace $(BUILDROOT)/doc/_build/html/en/index.html
+install: $(build_depsbindir)/stringreplace
 	@$(MAKE) $(QUIET_MAKE) all
 	@for subdir in $(bindir) $(datarootdir)/julia/site/$(VERSDIR) $(docdir) $(man1dir) $(includedir)/julia $(libdir) $(private_libdir) $(sysconfdir); do \
 		mkdir -p $(DESTDIR)$$subdir; \
```

**Comment by nalimilan** [comment]
I have bumped into the same problem when trying to build Fedora RPMs. In fact I had introduced this code in https://github.com/JuliaLang/julia/pull/19705 precisely for this reason.

I think the problem has to do with timestamps. In the 0.6.0 tarball, doc/_build/html/en/index.html had the most recent timestamp of all files. In the 0.6.1, some files under src are slightly more recent than it, like src/version_git.jl.

@ararslan Any idea what could have triggered an update of version_git.jl after the docs where built when preparing the tarball? Ideally one would just need to call `make release-candidate`, but maybe some steps are still manual?

**Comment by ararslan** [comment]
I have no idea.

**Comment by nalimilan** [comment]
I think I have a fix at https://github.com/JuliaLang/julia/pull/24496. I have no idea why this used to work, since `version_git.jl` has been introduced before #19705, but excluding it from dependencies seems to fix the problem here. Nevertheless, we should definitely check that it works before uploading the tarballs for the next release.
