### ISSUE TITLE
Dispatch in macros

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#24457]
Macro calls allow a certain level of dispatch, but the documentation does not mention that.
I think `::Char`, `<: Number`, `::String` and `::Symbol` typed literals are possible and otherwise the argument is an `::Expr` . Anything missing?

**Comment by yuyichao** [comment]
> Anything missing?

Yes, it can be any objects when there's interpolation.

**Comment by jw3126** [comment]
what is meant by interpolation here?

**Comment by yuyichao** [comment]
Yes.

**Comment by jw3126** [comment]
Let me see if I get this correctly. If I am willing to use `eval`, I can explicitly construct some `Expr`:
```julia
ex = Expr(:macrocall, Symbol("mymacro"), @__MODULE__, args...)
eval(ex)
```
and then `@mymacro` will dispatch on the types of `args` no matter how crazy they are, just like a normal function would. If I don't explicitly construct an `Expr` and `eval` it, like in
```julia
@mymacro "some" stuff 123
```
then julia will create an `Expr`:
`Expr(:macrocall, Symbol("mymacro"), @__MODULE__, "some", :stuff, 123)`
and still dispatch on the type of the args (`Tuple{String, Symbol, Int}`). Are the types @mschauer  mentions the only types I can get this way?

**Comment by yuyichao** [comment]
You don't need to construct `Expr` explicitly. You can also get at least `QuoteNode` and `Bool`.

**Comment by jw3126** [comment]
Okay construct `Expr` explicitly was poor wording. I wanted to distinguish between julia code that directly manipulates AST / requires knowledge about the AST and julia code that does not.

**Comment by jw3126** [comment]
I can write some docs for this.
