### ISSUE TITLE
Julia 0.6.1: libgit2 test failed

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#24453]
Hi guys,

I am trying to build Julia 0.6.1 package to openSUSE and I got this error during `runtest.jl`:

```
Error in testset libgit2:
Test Failed
  Expression: err.msg == "Invalid Content-Type: text/plain"
    Evaluated: "invalid Content-Type: text/plain" == "Invalid Content-Type: text/plain"
ERROR: LoadError: Test run finished with errors
while loading /usr/share/julia/test/runtest.jl, in expression starting on line 29
```

I am using libgit2 0.26.0.

**Comment by StefanKarpinski** [comment]
Looks like a case mismatch, maybe the test needs to normalize case?

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/23115#issuecomment-320018563

**Comment by ronisbr** [comment]
Hi @StefanKarpinski and @vtjnash ,

I was about to write this. It was already fixed in master. The problematic line was changed from:

```Julia
@test err.msg == "Invalid Content-Type: text/plain"
```

to

```julia
@test lowercase(err.msg) == lowercase("invalid Content-Type: text/plain")
```

Can it be ported to v0.6 series?

Btw, the tests pass after correcting this line.

**Comment by ronisbr** [comment]
@vtjnash, do you suggest to bundle libgit2 with Julia for openSUSE package?

**Comment by aytekinar** [comment]
I have the same error when building v0.6.2 from source even though `USE_SYSTEM_LIBGIT2=0` in `Make.user`.

**Comment by nalimilan** [comment]
It doesn't really indicate a problem, so you can either remove the offending line or change it to the version above. It's fixed in git master.

**Comment by ronisbr** [comment]
We are already in v0.7-alpha. This bug is fixed in v0.7 AFAIK. Question: Do you want me to submit a PR fixing it in v0.6-branch or should we close this bug?

**Comment by nalimilan** [comment]
I guess if you make a PR against the release-0.6 branch to use `lowercase` it will be accepted. There may well be a 0.6.4 release since regressions have been found in 0.6.3.

**Comment by ronisbr** [comment]
Ok! I will do as soon as I get in home. Thanks

**Comment by KristofferC** [comment]
Fixed.
