### ISSUE TITLE
integer truncation in truncate on Windows

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#24466]
While [ios_trunc](https://github.com/JuliaLang/julia/blob/33763a01c3af2d3fe543f2f3ca253cd3a1421e82/src/support/ios.c#L569) accepts a size argument of type `size_t`, it calls [_chsize](https://msdn.microsoft.com/en-us/library/dk925tyb.aspx), which takes a `long` (32-bit int on Windows), and it doesn't check for overflow. As a result, this fails:

```julia
open("some_file_name", "w") do f
    truncate(f, 2^31+1)
end
```

`ios_trunc` should probably be modified to use [_chsize_s](https://msdn.microsoft.com/en-us/library/whx354w1.aspx).

(Originally reported as https://github.com/simonster/JLD2.jl/issues/50.)

**Comment by jaakkor2** [comment]
Looks like it used to be `_chsize_s`, but was changed to `_chsize` here https://github.com/JuliaLang/julia/pull/3011/files back in 2013 due to  MinGW compilation problems.

If `defined(__MINGW32__)` continue to use `_chsize`, otherwise `_chsize_s` on Windows?

**Comment by vtjnash** [comment]
MinGW is long dead

**Comment by jaakkor2** [comment]
Consequence of this bug: on Windows 64-bit files larger than 2 GB cannot be truncated. For example, JLD2-files are now limited to 2 GB size.

Looks like cygwin64/mingw64-x86_64 is used to compile the version downloadable at https://julialang.org/downloads/ .  And looks like mingw64 has `_chsize_s` defined in mingw-w64/mingw-w64-crt/secapi/_chsize_s.c  .  But I do not find references to `--enable-secure-api` option in Julia code.

If we are targeting systems newer than Windows XP, `_chsize_s` should be ok, but I have no possibility to do testing now.  Help wanted :)
