### ISSUE TITLE
Cannot install julia 0.6.1 in win 10

### ISSUE THREAD

**Issue by rbacher** [JuliaLang/julia#24479]
Downloaded 0.6.1 in win 10 (german languagen)
Then try to install. Comes back with a "box" saying: 
![grafik](https://user-images.githubusercontent.com/6154671/32416517-845f1c96-c24a-11e7-9a91-dbb6ca5e9586.png)
(Unknown developer or so)

Note: When downloading the old 0.5.2 then I can install it nicely and I get:
![grafik](https://user-images.githubusercontent.com/6154671/32416522-a00f5654-c24a-11e7-82cc-8f3d9565ee69.png)
Note: Here, the developer is known.
Please, change 0.6.1 with correct editor/developer.
Thx.
Rainer

**Comment by ararslan** [comment]
The code signing certificate seems to have been revoked. We're working on getting a new certificate. Once we do that, the 0.6.1 binaries will be re-signed and re-uploaded.

**Comment by ViralBShah** [comment]
The code signing certificate is not revoked. How do we find out what is happening?

**Comment by rbacher** [comment]
I never had that with any other app. On win 10. You saw the screendumps. And I am able to install any other app. Any idea what to do? Can you recompile just for me 0.5.x? And then 0.6.x and send me both?
BR, Rainer 

---
Dr. Rainer Bacher
CEO
BACHER ENERGIE AG
Baldeggstrasse 27
CH 5400 Baden
Schweiz/Switzerland 

Ph +41564935930
Mob +41797638609
Email rainer.bacher@bacherenergie.ch
Skype bacher.rainer

**Comment by ViralBShah** [comment]
We have verified that an old certificate got used. 0.6.2 will soon be released and will be signed with the right certificates.

**Comment by ararslan** [comment]
We should still get the existing 0.6.1 binaries signed properly in the meantime.

**Comment by rbacher** [comment]
Thx. Would be great.
BR, Rainer

---
Dr. Rainer Bacher
CEO
BACHER ENERGIE AG
Baldeggstrasse 27
CH 5400 Baden
Schweiz/Switzerland 

Ph +41564935930
Mob +41797638609
Email rainer.bacher@bacherenergie.ch
Skype bacher.rainer

**Comment by JeffBezanson** [comment]
Were the 0.6.1 binaries re-built? Closing in any case since this is superseded by 0.6.2.

**Comment by ararslan** [comment]
@JeffBezanson Thanks, yes, they were. I forgot to close this afterward.
