### ISSUE TITLE
Should eachindex() check that inputs are of the same length?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24486]
Currently, `eachindex` does not check that the sizes of the input arrays are compatible, and just returns the size of the largest array:
```julia
julia> eachindex(1:2, 1:3)
1:3

```

That's dangerous since we often think it's safe to use `@inbounds` as long as we only use indices returned by `eachindex`. For example:
```julia
function f(x, y)
    @inbounds for i in eachindex(x, y)
        x[i] = y[i]
    end
end
x = [1]
y = rand(Int, 10000)
f(x, y) # Crash
```

See [this Discourse post](https://discourse.julialang.org/t/histogram-fit-error/6900) about a real case in StatsBase.

Shouldn't `eachindex` throw an error if the passed arguments are not of the same length?

Cc: @mbauman @timholy

**Comment by mkborregaard** [comment]
I actually thought this was the very purpose of the multi-arg version of eachindex.

**Comment by nalimilan** [comment]
> I actually thought this was the very purpose of the multi-arg version of eachindex.

It could make sense to return a tuple of iterators over broadcasted indices, but I can't think of a situation where the current behavior could be useful.

**Comment by mbauman** [comment]
Dup of #13310, which I just tagged as triage earlier this week to have a discussion on what kind of behavior we want here.  This definitely needs to be changed for 1.0.
