### ISSUE TITLE
randn(Float32) is slower than randn()

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#24516]
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     7.974 ns (0.00% GC)
  median time:      8.862 ns (0.00% GC)
  mean time:        9.214 ns (0.00% GC)
  maximum time:     83.854 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999

julia> @benchmark randn(Float32)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     9.137 ns (0.00% GC)
  median time:      10.170 ns (0.00% GC)
  mean time:        11.205 ns (0.00% GC)
  maximum time:     707.108 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     999
```

**Comment by yuyichao** [comment]
This is why I've been using `T(rand())` instead of `rand(T)` ;-p

**Comment by musm** [comment]
It's doing a `convert` : https://github.com/JuliaLang/julia/blob/940c770e8a458dafe7e87fb5c064ac19af860fb1/base/random/normal.jl#L165

**Comment by simonbyrne** [comment]
We really should generate Ziggurat tables for `Float32` as well.

**Comment by simonbyrne** [comment]
We really should generate ziggurat tables for `Float32` as well.

**Comment by yuyichao** [comment]
I guess this is a different one from the one I've seen then.

```
julia> @benchmark rand()
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.416 ns (0.00% GC)
  median time:      3.751 ns (0.00% GC)
  mean time:        3.813 ns (0.00% GC)
  maximum time:     25.602 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> @benchmark rand(Float32)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.160 ns (0.00% GC)
  median time:      4.495 ns (0.00% GC)
  mean time:        4.882 ns (0.00% GC)
  maximum time:     35.047 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> @benchmark Float32(rand())
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.667 ns (0.00% GC)
  median time:      4.000 ns (0.00% GC)
  mean time:        4.266 ns (0.00% GC)
  maximum time:     32.371 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```

**Comment by simonbyrne** [comment]
Not sure what that issue is about. Perhaps something to do with inlining?

**Comment by ViralBShah** [comment]
cc @andreasnoack 

I thought we had a PR with Float32 tables at one point.

**Comment by andreasnoack** [comment]
I think we have discussed that but I can't find it. However, I put the code for generating the tables in `test/random.jl` so I think it should be fairly easy to create the `Float32` tables by adjusting [these two lines](https://github.com/JuliaLang/julia/blob/caa7f04da63bb13fb56560843ad84b09b33d6280/test/random.jl#L131-L132)

**Comment by rfourquet** [comment]
Maybe there is indeed an inlining problem (or maybe micro-benchmarking shows its limitations). We even get different perfs between `randn()` and `randn(Float64)`... Here are the relative minimum times I get with benchmarktools for some operations, normalized by `randn()`, where `m` is a `MersenneTwister` object (could be `GLOBAL_RNG`):
+ `randn()` -> 1
+ `randn(m)` -> 0.92
+ `randn(Float64)` -> 1.13
+ `randn(m, Float64)` -> 1.11
+ `randn(Float32)` -> 1.17
+ `randn(m, Float32)` -> 1.13
+ `Float32(randn())` -> 1.03
+ `Float32(randn(m))` -> 0.94

Maybe generating the tables for `Float32` can help, but at least it seems that with what we have now, `randn` for `Float32` could be computed with very little overhead compared to `Float64` (0.94 vs 0.92).

**Comment by oscardssmith** [comment]
All are the same on master now.
