### ISSUE TITLE
Add `copy(::CodeInfo)` method

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#24518]
You can `deepcopy` a CodeInfo, but you can't `copy` it. I want to copy it because I modify it slightly in the debugger. Deep copying doesn't always work, because sometimes there's un-deep-copyable literals in the AST. Would be nice to have a `copy` method.

**Comment by StefanKarpinski** [comment]
Don't literals generally `deepcopy` as the identity? If not, shouldn't they?

**Comment by Keno** [comment]
Any julia object can be a `literal` depending on how the AST is created.

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/blob/master/base/inference.jl#L397

**Comment by vtjnash** [comment]
Yeah, exactly, that would probably make way more sense. We just haven't needed it yet. I suppose it's also slightly ambiguous whether you want the full copy (that it does here), or just the minimal copy (done by the ccall). But probably it's always the full copy that users intend.

**Comment by vtjnash** [comment]
There's a `copy` function now.
