### ISSUE TITLE
should `get(f, Nullable)` be defined?

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#24528]
I noted that my code include a fair bit of

```
maybe_res::Nullable = try_solve(...)
if isnull(res)
     # do some stuff
     # return some alternative
else
     get(maybe_res)
end
```

If `get(f, Nullable) was defined, like it is for dictionaries, then that would become

```
get(try_solve(...)) do
     # do some stuff
     # return some alternative
end
```

which is a bit nicer.

**Comment by nalimilan** [comment]
`Nullable` is on its way out: https://github.com/JuliaLang/julia/pull/23642. But we could define a similar `get` method for `Some`. Note that if the wrapped value cannot be `nothing`, you can use `Union{T, Void}` to replace `Nullable{T}`, so that you don't need to call `get` at all.

**Comment by vtjnash** [comment]
`Some` can't be null, so the situation is a bit different. I believe the current thinking is to have someone propose and develop a set of null-handling operators (with `?` prefix/suffix) and in the meantime to use straightforward conditional form.

**Comment by nalimilan** [comment]
> Some can't be null, so the situation is a bit different.

Yes, but #23642 includes a method `get(::Void, x::Any) = x`, so we could do the same here.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaArchive/Nullables.jl/issues/5
