### ISSUE TITLE
Linking in julia 0.6 fails in centos 6.8

### ISSUE THREAD

**Issue by adrianor** [JuliaLang/julia#24524]
In a related post https://github.com/JuliaLang/julia/issues/18666, there is some trouble in linking julia to `/usr/bin/julia` step. Mine is related, and the debugger tells me the solution, but I do not know how to go and modify the Makefile in order to feed the right path.

My error:

```
LINK usr/bin/julia
/usr/opt/centos/devtoolset-1.1/root/usr/bin/../libexec/gcc/x86_64-redhat-linux/4.7.2/ld: /usr/opt/centos/devtoolset-1.1/root/usr/bin/../lib/gcc/x86_64-redhat-linux/4.7.2/libstdc++_nonshared.a(system_error44.o): undefined reference to symbol '_ZTVSt14error_category@@GLIBCXX_3.4.11'
/usr/opt/centos/devtoolset-1.1/root/usr/bin/../libexec/gcc/x86_64-redhat-linux/4.7.2/ld: note: '_ZTVSt14error_category@@GLIBCXX_3.4.11' is defined in DSO /usr/lib64/libstdc++.so.6 so try adding it to the linker command line
/usr/lib64/libstdc++.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[1]: *** [/home/adrian/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2
```

I just need to change `/usr/opt/centos/devtoolset-1.1/root/usr/bin/../lib/gcc/x86_64-redhat-linux/4.7.2` to something in `/usr/lib64/libstdc++.so.6`, I suppose. I also added manually /usr/lib64/libstdc++.so.6 to my `LD_LIBRARY_PATH`, ran `make clean` and `make`, but nothing happens. I would be willing even to take the step of the automatic link and make it by myself, but I would need to know how to override this command. Yes, the machine is CentOs

**Comment by ViralBShah** [comment]
Which CentOS?

**Comment by adrianor** [comment]
It is

`Description:	CentOS release 6.8 (Final)`

(sorry for not posting it before)

**Comment by nalimilan** [comment]
Note that at #18666 the solution that was found was to install GCC manually and use that.

Regarding devtoolset issues, as I said there I used to be able to build Julia on Centos 6 with it, but maybe that doesn't work now. @staticfloat might know.

**Comment by staticfloat** [comment]
This looks like it's related to devtoolsets unorthodox choice to make `libstdc++` a static library.  My recommendation is to build your own GCC, we're currently using the latest 7.2.0.  We use Dockerfiles to do this but it's not hard to mentally translate that to bash commands. Our configuration is [here](https://github.com/staticfloat/julia-docker/blob/master/workerbase/lib/gcc_install.harbor), if that helps.  You can install it to someplace like `~/local`, then compile julia with `CC`, `CXX`, `FC`, etc.. pointing to the binaries within `~/local/bin`.

**Comment by adrianor** [comment]
The problem persists even with the newest gcc:

`$ make
    LINK usr/bin/julia
/usr/opt/rh/devtoolset-7/root/usr/bin/../libexec/gcc/x86_64-redhat-linux/7/ld: /usr/opt/rh/devtoolset-7/root/usr/bin/../lib/gcc/x86_64-redhat-linux/7/libstdc++_nonshared.a(cow-stdexcept.o): undefined reference to symbol '_ZTVSt11logic_error@@GLIBCXX_3.4'
/usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [/home/adrian/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2`

Would it be possible to get a patch from you (in a separate branch) such that the step of automatic linking is not done?

**Comment by adrianor** [comment]
I don't understand the `CC`, `CCX`, `FC`... How this is included in the `make step`?

**Comment by staticfloat** [comment]
That doesn't look like you built your own `GCC`, it looks like you're still using `devtoolset`.  I believe that devtoolset is patching GCC such that it's causing those errors, you should download the GCC source and compile it yourself.

The `CC`, `CXX`, stuff means that when you run `make` you should run `make CC=/path/to/built/gcc CXX=/path/to/built/g++ FC=/path/to/built/gfortran`, pointing the Makefile to the gcc that you custom-built.

**Comment by adrianor** [comment]
Ok, now I have 

`LINK usr/lib/libjulia.so.0.7.0
/usr/bin/ld: BFD version 2.20.51.0.2-5.44.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
make[1]: *** [/home/adrian/julia/usr/lib/libjulia.so.0.7.0] Error 1
make: *** [julia-src-release] Error 2`

It doesn't look like it is the same error as before.

**Comment by adrianor** [comment]
I don't understand the `CC`, `CCX`, `FC`... How this is included in the `make step`?

**Comment by adrianor** [comment]
This is as far as I can go. It still complains on the same library, although I have installed my own `gcc`

`[ 10%] Building AttributesCompatFunc.inc...
../../bin/llvm-tblgen: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ../../bin/llvm-tblgen)
../../bin/llvm-tblgen: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ../../bin/llvm-tblgen)
../../bin/llvm-tblgen: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../../bin/llvm-tblgen)
make[4]: *** [lib/IR/AttributesCompatFunc.inc.tmp] Error 1
make[3]: *** [lib/IR/CMakeFiles/AttributeCompatFuncTableGen.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [scratch/llvm-3.9.1/build_Release/build-compiled] Error 2
make: *** [julia-deps] Error 2`

**Comment by staticfloat** [comment]
You need to completely clean out your Julia build and start over from scratch while using your new compiler toolchain.  Run `make distclean` and then run your `make CC=... CXX=...` step again

**Comment by adrianor** [comment]
Thanks Elliot, sorry for taking away your time. When I installed the `gcc`, the make install step asked me to provide sudo, in order to install the programs at `/usr/local/bin`. If I go there I can see that my installation of gcc is succesfully done. Do you recommend to install the executables intead in my local home?

**Comment by staticfloat** [comment]
> Thanks Elliot, sorry for taking away your time.

No worries, we all start somewhere.  If you go back far enough in this repository, you can find me asking the same kinds of questions a couple years back.  :)

> Do you recommend to install the executables intead in my local home?

What's done is done; as long as the executables are easily run-able, there shouldn't be any problems with Julia.  The only problem with installing it to `/usr/local/` is that other programs may use the newer GCC now, instead of the older GCC, which ideally shouldn't cause problems but may in fact cause problems down the line.  If you don't want that, you should remove the GCC-installed files from `/usr/local/bin`, then reinstall, passing a home-local prefix argument to GCC's `configure` script.  Note that you may have to recompile GCC to get it to install in the right place.

**Comment by KristofferC** [comment]
Not sure if there is anything actionable left to do here.
