### ISSUE TITLE
excessive "From failed worker startup" output in tests

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#24546]
```
	From worker 2:		From failed worker startup:	1
	From worker 2:		From failed worker startup:	2
	From worker 2:		From failed worker startup:	3
	From worker 2:		From failed worker startup:	4
	From worker 2:		From failed worker startup:	5
	From worker 2:		From failed worker startup:	6
	From worker 2:		From failed worker startup:	7
	From worker 2:		From failed worker startup:	8
	From worker 2:		From failed worker startup:	9
	From worker 2:		From failed worker startup:	10
	From worker 2:		From failed worker startup:	11
```

and so on for 1000 lines (there's a convenient counter...). What is going on here? This is very annoying.

**Comment by yuyichao** [comment]
The printing is from https://github.com/JuliaLang/julia/blame/master/base/distributed/cluster.jl#L309 which prints 1001 lines to overflow the initialization read limit which is 1000. https://github.com/JuliaLang/julia/commit/82c7759bb308439df29de9c8890d38ff699f33d2 enabled printing of that 1000 lines of output when the connection fails.

**Comment by amitmurthy** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/24610 I believe
