### ISSUE TITLE
Julia print commands not working in emacs org-mode

### ISSUE THREAD

**Issue by Shuvomoy** [JuliaLang/julia#24551]
I am trying to run julia in emacs org-mode by following the instructions at [https://github.com/JuliaEditorSupport/julia-emacs](https://github.com/JuliaEditorSupport/julia-emacs). Everything seems to be working except print commands.

If I have the following source block:
```
#+BEGIN_SRC julia
a=[1;2;3];
b=[3;4;5];
c=a+b;
print(c)
#+END_SRC
```

Then I get the following error:
```
ERROR: MethodError: no method matching start(::Void)
Closest candidates are:
  start(!Matched::SimpleVector) at essentials.jl:258
  start(!Matched::Base.MethodList) at reflection.jl:560
  start(!Matched::ExponentialBackOff) at error.jl:107
  ...
Stacktrace:
 [1] #writedlm#18(::Array{Any,1}, ::Function, ::IOStream, ::Void, ::Char) at ./datafmt.jl:673
 [2] #20 at ./datafmt.jl:683 [inlined]
 [3] open(::Base.DataFmt.##20#21{Array{Any,1},Void,Char}, ::String, ::String) at ./iostream.jl:152
 [4] #writecsv#23(::Array{Any,1}, ::Function, ::String, ::Void) at ./datafmt.jl:705
 [5] writecsv(::String, ::Void) at ./datafmt.jl:705

```

I am using emacs 25.3.2 on ubuntu 16.04, julia 0.6. I will appreciate any help. If I take away commands associated with print or println, everything works.

I will appreciate any suggestion.

Best Regards,
Shuvomoy

**Comment by garrison** [comment]
Please do not cross post: https://discourse.julialang.org/t/julia-print-commands-not-working-in-emacs-org-mode/6944

**Comment by fredrikekre** [comment]
This does not seem to be an issue with julia.
