### ISSUE TITLE
x and y should both be declared constant in const x = y = 1

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#24576]
Suppose `x,y` are not defined. Then
```
const x = y = 1
```
should declare both as constants. Currently, only `x` is declared constant. Is this intentional?

**Comment by JeffBezanson** [comment]
Yes, it's intentional. Note that `const x = const y = 1` works to make both constant. `const` applies to one `=` operation, so that `const x = y = 1` is equivalent to `const x = 1; y = 1`. For comparison, in `const x, y = 1, 2` both `x` and `y` are declared constant because there is a single `=` to which the `const` applies.

**Comment by Ismael-VC** [comment]
@cossio maybe we could add your example to the `const` docstring and document it, I never knew about this, this is the only example of multiple assignement in the docstring:

    Multiple variables can be declared within a single const:

    const y, z = 7, 11

**Comment by cossio** [comment]
@Ismael-VC  Where is the `const` docstring?

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/blob/daa58bb183799aac11f069e5b17a689e7fb8ec1b/base/docs/basedocs.jl#L274-L297

**Comment by cossio** [comment]
Hmmm, I already have an open pull request with another issue on my fork. I don't seem to be able to create a separate PR for this.

**Comment by StefanKarpinski** [comment]
You need multiple branches to make multiple PRs.

**Comment by cossio** [comment]
I don't see a way to create another branch.

**Comment by StefanKarpinski** [comment]
https://git-scm.com/docs/git-branch, probably best to take the rest of this conversation to Slack or Discourse
