### ISSUE TITLE
Regressions in daily benchmarks after the Nanosoldier outage

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#24577]
After Nanosoldier came back, I manually ran a benchmark comparing the current master to the one where the latest daily benchmark was run (https://github.com/JuliaLang/julia/commit/26eb512367936550a0fd1c6414f09215845f6eb1#commitcomment-25531390).

The results are at https://github.com/JuliaCI/BaseBenchmarkReports/blob/fde6d79bccb873b00a5cd44a5dc8e3e1eec286d0/26eb512_vs_fce2d68/report.md and there are some regressions to look at. The sparse dense matmul is very noise, but excluding those, what seems to be real regressions are:

```
["linalg", "arithmetic", ("*", "Tridiagonal", "Vector", 1024)]
Julia Parse
JSON Parse
```

**Comment by KristofferC** [comment]
Hm, I can't really reproduce the JSON one, anyone else can try.

**Comment by fredrikekre** [comment]
`["linalg", "arithmetic", ("*", "Tridiagonal", "Vector", 1024)]`
That is my fault from  #24324, will submit a PR later.
