### ISSUE TITLE
0.6.x: strange dispatch error after package loading

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#24585]
See robertfeldt/BlackBoxOptim.jl#73.
It looks like after `using BlackBoxOptim` something is happening with the method dispatch, although I cannot trace a direct connection (note that `convert()` still works properly, but calling `convert` from `g()` seems broken):
```
julia> g(R, x) = convert(Set{R}, x)
g (generic function with 1 method)

julia> Base.Test.@inferred g(Any, Set([1]))
Set(Any[1])

julia> convert(Set{Any}, Set([1]))
Set(Any[1])

julia> using BlackBoxOptim

julia> convert(Set{Any}, Set([1]))
Set(Any[1])

julia> Base.Test.@inferred g(Any, Set([1]))
ERROR: return type Set{Int64} does not match inferred return type Set{Any}
Stacktrace:
 [1] macro expansion at ./REPL.jl:97 [inlined]
 [2] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

**Comment by alyst** [comment]
I've just thought that maybe there's something special about `Any`, but also `Base.Test.@inferred g(Float64, Set([1]))` works properly before `using BlackBoxOptim` and fails afterwards (`ERROR: return type Set{Int64} does not match inferred return type Set{Float64}`).

**Comment by StefanKarpinski** [comment]
Does `BlackBoxOptim` do some type piracy here and change `convert` for `Set{Any}`?

**Comment by alyst** [comment]
> Does BlackBoxOptim do some type piracy here and change convert for Set{Any}?

AFAICT, no. `BlackBoxOptim` does define a few `Base.convert()` methods, but in the branch I'm testing at least one argument of each `convert()` is of `BlackBoxOptim`-specific type.
Also `convert(Set{Float64}, Set([1]))` still works fine if called directly, and `g(Float64, Set([1]))` still fails even if I redefine `g` after `using BlackBoxOptim` (in case it's related to the world age).
But maybe there's some debugging technique to identify what `convert()` is actually called by `g`?

**Comment by KristofferC** [comment]
Comment if this still happens.
