### ISSUE TITLE
fewer unicode unary operators

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#24608]
In #21037 , in relation to allowing new postfix operators for transpose, came the proposal to allow more general postfix operators (e.g. powers) when they explicitly separated from the identifier using parentheses (or other?), as in `(A)ᵀ` and `(a)²`.

Without the parenthesis, the postscript together with whatever comes before (and after) would just form a single unit, i.e. a valid identifier name, i.e. you could do
```julia
Aᵀ = (A)ᵀ
a² = (a)²
```
For consistency, it would be great to also be able use `√a` as identifier name, and require parenthesis for explicitly applying it, i.e.
```julia
√a = √(a)
```
Note that it already works with parenthesis, so it's a matter of disabling (and properly deprecating, which is beyond my capabilities) `√` as unary operator.

**Comment by JeffBezanson** [comment]
The problem is that `ᵀ` is a letter and `²` is a number character, while `√` is not. It's a mathematical symbol. By the same rule of consistency, it seems we'd have to make `-a` an identifier as well.

**Comment by Jutho** [comment]
That's true if you know about unicode classes, but I am not sure it applies to the general user. Anyway, I don't care about this issue too much myself, I just find the current situation a bit inconsistent to those that think they can use some kind of fancy math notation as valid code. I only filed an issue because @StefanKarpinski suggested to do so.

Feel free to close.

**Comment by JeffBezanson** [comment]
I don't really understand the consistency point. What would be consistent? Making all non-ASCII characters identifier characters? Requiring parentheses for all unary operators? I don't see a simple rule that would be desirable here.

**Comment by Jutho** [comment]
Well if a new user sees that `√a` does what he expects, he will be surprised that `a²` does not. So I'd say either both compute what one would expect, or both are identifiers (possibly  in combination with making the actual computation work when using parentheses).

I doubted a long time before submitting my comment in #21037 and would certainly not have submitted an actual issue without explicit request to do so.  I won't be using either (nor as identifier, nor as function application, partly because I find this distinction confusing, and partly because the ascii syntax is as convenient and equally well established).

So again, feel free to close right away.

**Comment by JeffBezanson** [comment]
Ah, I can see this better if we consider `²` to be the problem, rather than `√`. I would argue that the meaning of `²` is more ambiguous. To me `√` is obviously an operator, and it would be very surprising if e.g. `√2` were a variable name. I also don't see a way to be fully consistent by making `√x` a variable name. If `√x` is an identifier, why not `-x` and `+x`? On the other hand, making `x²` mean `x^2` would match common notation, and we also have the option of disallowing it to avoid confusion. However, math notation itself quickly gets inconsistent here, since `xᵀ` does not mean `x^T`.

**Comment by Jutho** [comment]
Fair enough, I should also have suggested the alternative to make `a²` work, but didn't dare as I know that several people (not me) care very much of having `a²`  as an identifier. For transpose, `Aᵀ` is also less popular than `(A)ᵀ` in the vote over at #21037.

**Comment by stevengj** [comment]
I care very much about having things like `χ⁽²⁾` available as identifiers, but `x²` is useful as well, and we already have a perfectly good `x^2` notation for the math operation.
