### ISSUE TITLE
cgroup aware `Base.Sys.cpu_info` and `Base.Sys.total_memory`

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#24617]
Not sure if it is possible, but it will be good to have `Base.Sys.cpu_info` and `Base.Sys.total_memory` aware of linux cgroups and report cgroup info instead.

It will also be useful when Julia is being run within a docker container with cgroup limits.

**Comment by vtjnash** [comment]
I tried looking into this before, and tried to write down a few of my findings: https://github.com/JuliaLang/julia/issues/17987#issuecomment-245360596

**Comment by vtjnash** [comment]
may be addressed by https://github.com/libuv/libuv/issues/2249

**Comment by maleadt** [comment]
This isn't really fixed: although https://github.com/JuliaLang/julia/pull/36479 introduced uses of `uv_get_contrained_memory` for setting-up the heap and managing collections, that information isn't exposed in the Sys module as requested here. Furthermore, with Linux distributions moving to cgroup2, `uv_get_contrained_memory` becomes useless unless https://github.com/libuv/libuv/pull/2323 is merged. So I think we better re-open this issue.
