### ISSUE TITLE
Deploy docs to readthedocs

### ISSUE THREAD

**Issue by henrykironde** [JuliaLang/julia#24623]
## Details

* Project URL: https://github.com/henrykironde/Retriever.jl
* Build URL: https://readthedocs.org/projects/retrieverj/builds/
* Read the Docs username: henrykironde

## Expected Result

Deploy `Julia` project's documentation to `readthedocs` (host ready built documentation on `readthedocs`)

*A description of what you wanted to happen*

I want to build and deploy(host) my documents to readthedocs.
Since this is Julia project, Julia enable building the documentation using 
a `make.jl` file, how do we get these docs to be deployed on readthedocs

## Actual Result
no docs built
*A description of what actually happened*

http://retrieverjl.readthedocs.io/en/latest/?badge=latest

**Comment by swissr** [comment]
This question has not much to do with the Julia core project. My suggestion is to ask at the community forum: https://discourse.julialang.org/. People are friendly and helpful. (Note: not sure, but I 'half-remember' that (some) people moved away from readthedocs, e.g. JuMP https://jump.readthedocs.io/en/latest/, don't recall why.)

**Comment by nalimilan** [comment]
@swissr is right that this is more a question about how to use Documenter, better ask it on Discourse. I think Read The Docs is no longer the recommended way of deploying package docs, look at the Documenter manual for details (it's now uploaded to the GitHub-hosted pages in the `gh-pages` branch).
