### ISSUE TITLE
Bug in "1.1+0.1",what is wrong with it? 

### ISSUE THREAD

**Issue by askuyue** [JuliaLang/julia#24639]
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e (2017-10-24 22:15 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

julia> 1.1 + 0.1
1.2000000000000002

**Comment by andreasnoack** [comment]
This is how binary floating points work. Take a look at https://stackoverflow.com/questions/588004/is-floating-point-math-broken.

**Comment by Ismael-VC** [comment]
You may also use `Rationals`:

```julia
julia> 11//10 + 1//10
6//5                 
```

**Comment by askuyue** [comment]
Thanks very much. But this is bug. How to amend it in the interior of Julia?

**Comment by yuyichao** [comment]
No this is **NOT** a bug. Please use discourse for further questions.

**Comment by askuyue** [comment]
Thanks. It is my fault.






At 2017-11-18 12:42:19, "Yichao Yu" <notifications@github.com> wrote:


No this is NOT a bug. Please use discourse for further questions.
