### ISSUE TITLE
ERROR: LoadError: UndefVarError: delim not defined

### ISSUE THREAD

**Issue by gtollefson** [JuliaLang/julia#24644]
Hi,

I'm trying to load a tab delimited file using the following code:

`vcf=readdlm("/Users/George/Desktop/work_projects/Sept2017_24patients_visualize/24patients_edit_test.vcf", delim::"\t")`

and receive the following error:

> ERROR: LoadError: UndefVarError: delim not defined

I'm using julia v6.0.

Does anyone know why this is happening?

Thanks,
George

**Comment by gtollefson** [comment]
I've also tried using `delim="\t"`

**Comment by yuyichao** [comment]
You are not using the right syntax.
Also I believe the error for `delim="\t"` will not be the same one so please post the error message next time.

This is not a bug and please use discourse for further questions.
