### ISSUE TITLE
Option to rebuild system image at installation

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#24646]
The standard binary downloads use generic "build" options.
I now almost always want to rebuild the system image with cpu_target="native".
Could rebuilding a custom system image be included as an installation option?
I'm thinking a dialog box:
```
Do you want to build a custom system image? (yes/no)
```
Or something similar but more friendly (particularly for Windows)

**Comment by yuyichao** [comment]
Not needed anymore.

**Comment by Sacha0** [comment]
Chances are `@yuyichao` had #21849 in mind (?) when he closed this issue. Best!
