### ISSUE TITLE
Include Win10 user symlink support at next libuv bump

### ISSUE THREAD

**Issue by ihnorton** [JuliaLang/julia#24667]
Recent Win 10 updates permit [unprivileged users to create symlinks](https://github.com/libuv/libuv/issues/1157), much like a proper OS.

Currently Julia returns `permission denied` on such symlinks (tested in Fall Creators Update), because the libuv fork does not correctly handle the applicable reparse points. Doing so will require backporting at least the following upstream change:

https://github.com/libuv/libuv/pull/1466

(x-ref #24483 which also involves reparse point support)

**Comment by musm** [comment]
I think we already include the patch on our version of libuv

**Comment by musm** [comment]
@ihnorton  please re-open if not, but I'm almost certain it is.
