### ISSUE TITLE
Add missing atomic operations on struct and pointer types.

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#24662]
All the atomic operations (except [some](https://github.com/JuliaLang/julia/blob/06a6afb507a7d0165f3c229ddab72f28a6e7e250/base/atomics.jl#L412-L427)) currently directly dispatch to to LLVM atomics.
These are only available for certain primitive types.

I suggest for consistency, it would be good to have an Atomic
that takes anything (eg `BigInt`), and uses locking to achieve atomicity.

This would mean adding a type (bikesheding on name pending):

```
struct LockingAtomic{T, L<:AbstractLock}  <: AbstractAtomic{T}
    lock::L
    value::T
end
```
maybe it should be `value::Ref{T}`)

and defining its operations as something like:

```
function atomic_foo!(at::LockingAtomic{T}, x::T) where T
    lock(at.lock) do
        foo!(at.val, x)
    end
end
```

Plus the code for where atomics don't quiet do what you think, and e.g. return old values.

I think this can be written generically, to work with any type that has an suitabled defined `foo!`, and then it can work by duck-typing.

I think this is safe against being able to deadlock.
Because inside any of the operations no further locks are required before they can unlock.  

(cf https://github.com/JuliaLang/julia/issues/18706)

**Edit**: to be precise I don't mean arbitrary operations.
`atomic_foo!` is a stand in for:
exactly the set: `atomic_cas!`, `atomic_xchg!`, `atomic_add!`, `atomic_sub!`, `atomic_and!`, `atomic_nand!`, `atomic_or!`, `atomic_xor!`, `atomic_max!`, and `atomic_min!`.
Plus anything else that we later pull from LLVM and give to primitive types.
Simple operations with only one atomic variable.

**Comment by vchuravy** [comment]
While I think in general this might be a good idea (and you could even use a `atomic_apply(foo,. Val)` it is not something that needs to go into `Base`.

**Comment by oxinabox** [comment]
I suggest it belongs in base because it makes the language more consistent.
It is weird to write code that works for some Base integer types,
but not for others.

It certainly doesn't have to go into Base (not much does really).
I think it would be cleaner to have it in Base though.

I can see the argument though, it is good to keep Base small.

**Comment by yuyichao** [comment]
Atomics on complicated types can be added. This is not the right way to do it (it violate the ABI) and this can't support arbitrary operation.

**Comment by yuyichao** [comment]
Also, the use of fine grain lock is invalid....

**Comment by yuyichao** [comment]
A few more important notes,

> I suggest for consistency

This is a fundamental misunderstanding of atomics. There's no inconsistency hereq. They are not the magic tool to make operation on any data thread safe. They are the synchronization mechanism to ensure that. Support of simple/basic atomic operations on complex type is reasonable (and we are missing a few there), support of complecated operations will not be added and should not be needed. If it comes up, you are definitely not using atomics correctly.

> it would be good to have an Atomic that takes anything (eg BigInt), and uses locking to achieve atomicity.

And this is another fundamental misunderstanding of atomics. Using a local lock will not give you atomic semantics. They are tools to do the synchronization and without a global lock it cannot be done.

> ```julia
> function atomic_foo!(at::LockingAtomic{T}, x::T) where T
>     lock(at.lock) do
>         foo!(at.val, x)
>     end
> end
> ```
>
> I think this can be written generically, to work with any type that has an suitabled defined foo!, and then it can work by duck-typing.
> I think this is safe against being able to deadlock.
> Because inside any of the operations no further locks are required before they can unlock.

No that's impossible. It's extremely hard to wrap generic operation and you'll very easily get dead lock unless you know the code does not do any synchroniation in any way. The optimum (or even usable) locking pattern is also only known by the user and there's no way base / package code or at least any code that's not the direct user of the synchronization an know what pattern you need.

**Comment by oxinabox** [comment]
> And this is another fundamental misunderstanding of atomics. Using a local lock will not give you atomic semantics. They are tools to do the synchronization and without a global lock it cannot be done.

I see, I have been using the word *atomic* laxly.
I'm rereading the [LLVM docs for atomics](https://llvm.org/docs/Atomics.html), and the [source](https://github.com/JuliaLang/julia/blob/master/base/atomics.jl),
I'm still gronking it.

> No that's impossible. It's extremely hard to wrap generic operation ...

I'm **not** talking about wrapping generic operations. I am talking about wrapping **generic types,**
for the **current set of atomic operations.**
AFAICT, that current set of operations only makes ordering promises relevant to its first operand.
Where in all cases it has acquire-release ordering.
Which I think is emulated by local-locking.
(Except maybe `atomic_cas!` I think that is maybe the exception to everything I'm saying, so maybe I am completely wrong.)


> and you'll very easily get dead lock unless you know the code does not do any synchroniation in any way.

I can't see any way for a single nonlocal lock plus any number of local locks on fake atomics, can deadlock.
Working it through out-loud
To deadlock one needs two (or more) threads to be attempting to acquire two (or more) locks,
and for each to hold the one the other needs.
i.e. for them to acquire them in different orders.
So say thread 1 has a local lock for some fake atomic, which it holds because it is doing some `atomic_*!` operation.
and thread 2 has the nonlocal lock.
Then to deadlock thread 1 must want the nonlocal lock.
But we can't be in that state as nowhere inside an  `atomic_*!`  operation is there any attempt to get an lock except the local lock. And no user provided code is executed.
Ergo, no deadlock can occur.

Unless the user is accessing the locallock directly outside of an `atomic_*!` operation.

Or do you mean by synchroniation doing something the code triggering `atomic_fence`.
I'm not sure exactly what that would do.
I don't think it can lead to a deadlock but I'm not sure.


PS: thank you for taking the time to explain to me. This is really interesting stuff.

**Comment by StefanKarpinski** [comment]
> I'm not talking about wrapping generic operations. I am talking about wrapping generic types,
> for the current set of atomic operations.

I don't think there's any difference since the implementation of one of those operations for a generic type can be absolutely anything. It might be helpful for the discourse here if @yuyichao explained what he means by atomic and why it cannot be applied to general operations.

**Comment by JeffBezanson** [comment]
Closing in favor of similar issues #29943 and #32455.
