### ISSUE TITLE
Feature Request: step(::AbstractVector{Dates.TimeType})

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#24661]
`step` is currently implemented for `AbstractRange`. However, sometimes it is useful to know the step in a sequential vector such as with `AbstractVector{Dates.TimeType}`. One applications that can benefit from it is first-differencing. As a first attempt I implemented something that works for `Date`.
```
function Base.step(obj::AbstractVector{Base.Dates.Date})
    hopeful = Dates.CompoundPeriod.(Year.(diff(year.(obj))) .+
                                    Month.(diff(month.(obj))) .+ Day.(diff(day.(obj))))
    if all(length.(getfield.(hopeful, :periods)) .== 1)
        output = minimum(first.(getfield.(hopeful, :periods)))
    else
        hopeful = getfield.(diff(getfield.(obj, :instant)), :value)
        if all(hopeful .% 7 .== 0)
            output = Week(minimum(hopeful) / 7)
        else
            output = Day(minimum(hopeful))
        end
    end
    return output 
end
```
This handles common steps such as `Day(x)`, `Week(x)`, `Month(x)`, `Year(x)`.

**Comment by stevengj** [comment]
It sounds like you want `oneunit`?
```jl
julia> oneunit(Dates.Day(3))
1 day
```

**Comment by Nosferican** [comment]
This applies to `Vector{T} where T <: Date`. For example,
```
day_step = collect(Date(2000):Day(2):(Date(2000) + Day(9)))
week_step = collect(Date(2000):Week(2):(Date(2000) + Week(9)))
month_step = collect(Date(2000):Month(3):(Date(2000) + Month(9)))
year_step = collect(Date(2000):Year(2):(Date(2000) + Year(9)))
```
These should return
```
step(day_step)
2 days
step(week_step)
2 weeks
step(month_step)
3 months
step(year_step)
2 years
```
when the step is not constant, it should return the smallest non-negative value (i.e., step).
```
step([day_step[2], week_step[2], month_step[2], year_step[2]])
12 days
```

**Comment by quinnj** [comment]
`step` is already defined for `AbstractRange` types, which apply to `Dates.TimeType`s (in addition to any other types w/ defined ordering). I think `step` on an `AbstractVector` is a special-case that probably isn't useful generally since most will be able to use Ranges for that. I also tend to use a couple rules when considering whether something should be included in Base:
1) is it sufficiently low-level that it needs to call other internal `Base` methods?
2) for a generic function, is it so widely used and overloaded that it would make sense to "centralize" its definition in Base so it can be consistently overloaded?
3) is it a sufficiently complex algorithm or needed functionality that it would provide a great convenience to just provide it in Base?

In this case, I don't think `step(::AbstractVector{T}) where {T <: Dates.TimeType}` really hits any of those 3 points.

**Comment by Nosferican** [comment]
Are you aware of any package that extends on Base.Dates (à la Lubridate in R) which might be a good candidate to have these extended functionality to Dates? Otherwise I could have it in a general data wrangling packages.

**Comment by stevengj** [comment]
Defining this in a package seems like type-piracy to me... you would want to give it a different name.

Also, if you defined `step` for arrays of dates, then it seems like you would also want it for arbitrary arrays, i.e. `step(x::AbstractVector) = minimum(diff(x))`.   I'm skeptical that we want such a function.

**Comment by Nosferican** [comment]
I don't think is type piracy as currently `step` is only implemented for `AbstractRange`. I would argue it is quite useful to have it for data science. For example, `step(::CategoricalArrays.AbstractCategoricalVector)`. `diff` is not defined for some subtypes of `AbstractVector`. For example,
`diff(obj::CategoricalArrays.AbstractCategoricalVector{T}) where T = diff(get.(obj))` might be the default, but it will fail for `AbstractString` or give not very useful answers for `Date`.
Ideologically there is no reason why `step` shouldn't be defined for any `AbstractVector` that can be ordered.

**Comment by stevengj** [comment]
It is type piracy (a technical term in Julia-verse), because this hypothetical package would be extending a function `step` defined in another package acting on types defined in another package (`AbstractVector` and `Date`).

**Comment by Nosferican** [comment]
Sorry, I was under the impression it was overwriting methods rather than extending these. Type piracy is the way I am used to working with StatsBase. I am against using another name since `step` is the definition of the procedure. Making a new struct (`TemporalSeq`) as a wrapper really doesn't seem like a good solution either since the operation would most heavily be used in the context of a DataFrame column and possibly a CategoricalVector. Guess I will see how feasible is the `TemporalSeq` approach.

**Comment by Nosferican** [comment]
Gonna leave this here in case someone reads it while looking for it.
```
function frequency(obj::AbstractVector{T}) where T <: Dates.Date
    FirstDifference = Dates.canonicalize.(Dates.CompoundPeriod.(diff(obj)))
    if all(length.(getfield.(FirstDifference, :periods)) .== 1)
        output = minimum(FirstDifference)
    else
        output = minimum(Dates.canonicalize.(map(ymd -> Dates.Year(ymd[1]) +
                                     Dates.Month(ymd[2]) + Dates.Day(ymd[3]),
                                     diff(collect.(Dates.yearmonthday.(obj))))))
        if any(Dates.value.(output.periods) .< 0)
            output = minimum(FirstDifference)
            output = convert(Dates.Day, output.periods[1]) + output.periods[2]
        end
    end
    return output
end
```
