### ISSUE TITLE
Typo in JS benchmark code?

### ISSUE THREAD

**Issue by bcolloran** [JuliaLang/julia#24680]
I think I spotted a very minor typo in the JS benchmark code:

https://github.com/JuliaLang/julia/blob/d14843749a57c880a64689673fe7317bd721747c/test/perf/micro/perf.js#L407

Throughout the benchmarks, arrays are initialize with e.g. `new Float64Array(m*n);` but in the `matmul` function, the output array is initialized with `new Array(m*n);`. I think this is probably just a typo, b/c it seems inconsistent with the rest of the file.

A quick test showed a more than 2x improvement on that particular test. Of course, this is not at all a big deal in the grand scheme of things, but I thought I'd mention in just in case...

**Comment by JeffBezanson** [comment]
Thanks, that does look wrong.

**Comment by JeffBezanson** [comment]
Also, please feel free to open a PR with this change if you'd like.
