### ISSUE TITLE
feature request: mandatory keyword arguments (without default value)

### ISSUE THREAD

**Issue by timkittel** [JuliaLang/julia#24685]
Hi, I am currently getting into Julia and really love it. As I am coming from Python, I love how Julia combines simplicity (of code development) with speed. Congratulations for this amazing project.

As there are already keyword arguments implemented in Julia, I would love to see see not only optional keyword arguments but mandatory ones, too. Meaning, I don't have to set a default value and during the call a value has to be set by keyword.

Why?: In functions where several arguments have to be passed to a function, it can easily happen to make mistakes with the order. Also, even if it's correctly programmed, mandatory keyword arguments could improve the legibility of the code, hence reduce the probability of bugs and make the programming life a lot easier.
A work-around would be to define a struct and put the arguments in there, but that makes the whole procedure a lot more complicated and negates the aforementioned advantages.
Further, from my naive perspective this sounds like a simple extension and I hope you could find the time to implement it.

Syntax?: As keyword arguments are already separated from normal arguments with a semicolon, the syntax would only need to be extended to allow omitting the default value.

**Comment by fredrikekre** [comment]
#5111

**Comment by JeffBezanson** [comment]
@timkittel Thanks for the kind words!
