### ISSUE TITLE
rr 5.0.0 can no longer trace Julia

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#24693]
I am having issues tracing the current master with `rr 5.0.0`.

```
rr record ./julia

ERROR: Unable to find compatible target in system image.
```

@Keno mentioned on slack that `rr` is masking out some of the `cpuid` stuff https://github.com/mozilla/rr/blob/fdd2cbe2f4006dd714b725469cbd2351ee1da7ce/src/record_signal.cc#L124-L137,
Which is likely causing issues with out processor detection.

I was hoping that I could specify `JULIA_CPU_TARGET=skylake` in my `Make.user` and then get away with a `./julia -C skylake, but alas that doesn't work.

Ping @yuyichao since you are most familiar with your processor detection infrastructure.

--edit:
I should add that this is happening on a Kabylake machine with kernel `4.13.12`

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/21849#issuecomment-331942140 https://github.com/archlinuxcn/repo/commit/a012518ebec3ca733ddaed2a7ead7e46a4cd1348#diff-ccbc31c2859fe983dac381684a691b61

**Comment by Keno** [comment]
I feel like since LLVM doesn't emit those instructions, so we should just accept it.
