### ISSUE TITLE
Unicode entering mode within square brackets broken

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#24705]
Within square brackets that follow a variable (i.e. a `getindex` operation), tab completion for entering Unicode is broken, unless the variable in front is a `Dict` or an `Array`. I tried to trace down the error in `REPLCompletetions`. 

I think the problem is that `dict_identifier_key` returns `(true,nothing,nothing)` for any variable (which is not a dict), such that the function `completions` returns early with this line:
https://github.com/JuliaLang/julia/blob/master/base/repl/REPLCompletions.jl#L493

The only exception are `Array`s, since they are special cased in `dict_identifier_key` to return `(nothing,nothing,nothing)` in line
https://github.com/JuliaLang/julia/blob/master/base/repl/REPLCompletions.jl#L459

Is it my understanding that something is wrong here.  I don't know much about the whole `REPL` module, but the name `dict_identifier_key` seems to suggest that it should only pick out `Dict`s, and should therefore return `(nothing,nothing,nothing)` for anything that is not a `Dict`.

**Comment by Jutho** [comment]
Also, minimal working example:
```julia
a=randn(2,2);
f=qrfact(a)
a[\+TAB]  #=> all possible Unicode completions
f[\+TAB] #=> nothing
```

**Comment by Jutho** [comment]
If somebody could give some pointers as to the correct fix, I could try to prepare a PR.

**Comment by IlyaOrson** [comment]
I also found this recently:
```julia
# X is undefined
X["\Delta<TAB>"] # X["Δ"]
X["\Delta<TAB><TAB>"] # X["Δ"]

X = Dict("Δ" => 1)
X["\Delta<TAB>"] # X["Δ"]
X["\Delta<TAB><TAB>"] # UnicodeError

X = 1
X["\Delta<TAB>"] # no completion
```

**Comment by CarloLucibello** [comment]
actually for me on 1.0.1 general completion within indexing is broken, e.g.:

```julia
jualia> using FataFrames

julia> df = DataFrame(ciao=rand(3))
3×1 DataFrame
│ Row │ ciao      │
│     │ Float64   │
├─────┼───────────┤
│ 1   │ 0.175749  │
│ 2   │ 0.0407557 │
│ 3   │ 0.0945494 │

julia> df[df.ci<Tab>            # NOT COMPLETING
```

**Comment by stevengj** [comment]
I have an updated version of this PR with tests, and will open a new PR shortly.
