### ISSUE TITLE
repl test errors on windows

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#24730]
win32 and win64 buildbots are running into repl test errors, although I have been unable to reproduce the errors outside of the buildbot environment.  The error is:

```
Error in testset repl:
Test Failed at C:\cygwin\home\Administrator\buildbot\slave\package_win32\build\test\repl.jl:161
  Expression: contains(s, "shell> ")
```

Which I traced back to [this commit](https://github.com/JuliaLang/julia/pull/23881) by @vtjnash.  Again, when running Julia directly in `bash` on the windows buildbot this works just fine, but when run inside of the buildbot, it seems to be [having trouble](https://build.julialang.org/#/builders/44/builds/52).

**Comment by vtjnash** [comment]
I think that test may be assuming —color=true gets selected.

**Comment by staticfloat** [comment]
Yes, I think you're right.  Although I'm not entirely sure why this would be happening, as [setting `--color=no` doesn't actually remove the color from the prompt](https://github.com/JuliaLang/julia/issues/24737), unless we actually have three code paths here, (`--color=yes`, `--color=no`, and something else that actually does disable color in the prompt) ;)

**Comment by KristofferC** [comment]
Closing as stale.
