### ISSUE TITLE
Sum of two Symmetric matrices is not of the same type 

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#24733]
Hi 

I don't know if it is the intended behaviour (master 0.7.0-DEV.2597 Commit 682717024f)

Lets create a symmetric sparse matrix B

 `A = sprand(5,5,0.8); A = A+A';  B=Symmetric(A);
`
and copy it to another symmetric C

 ```
C = copy(B);
 typeof(C)==typeof(B)
 true
```

The sum of B and C should be (or it should not?) of the same type, but

```
typeof(B+C) 
Array{Float64,2}

```

**Comment by fredrikekre** [comment]
#22550
