### ISSUE TITLE
Function module does not accept keyword arguments

### ISSUE THREAD

**Issue by Strider26** [JuliaLang/julia#24745]
`Pkg.add("JuMP")
Pkg.add("GLPK")
Pkg.add("GLPKMathProgInterface")

using JuMP
using GLPKMathProgInterface
function solveTSP(;n=2,cities=[0 0; 0 0])
    dist=zeros(n,n)
    for i = 1:n
        for j = 1:n
            d=norm(cities[i,1:2]-cities[j,1:2])
            dist[i,j]=d
            dist[j,i]=d
        end
    end
    m=Model(solver=GLPKMathProgInterface(LazyConstraints=1))
    @variable(m,x[1:n,1:n])
    @objective(m,Min,sum(dist[i,j]*x[i,j],i=1:n,j=1:n))
    for i=1:n
        @constraint(m,x[i,i]==0)
        for j=1:n
            @constraint(m,x[i,j]==x[j,i])
        end
    end
    for i=1:n
        @constraint(m,sum(x[i,j],j=1:n)==2)
    end
    
    solve(m)
    return extractTour(n,getValue(x))
end

n=6
cities=[50 100; 100 250; 100 300; 200 500; 500 300; 550 200]
tour=solveTSP(n,cities)
println("Solution:")
println(tour)`

Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by fredrikekre** [comment]
Please use https://discourse.julialang.org/ for questions.
