### ISSUE TITLE
handle leak in BLAS.vendor()

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#24753]
BLAS.vendor() calls `Libdl.dlopen_e`, but is missing `try/finally; Libdl.dlclose(lib); end`

**Comment by ViralBShah** [comment]
Can it not just unconditionally dlclose before returning?

**Comment by ViralBShah** [comment]
Well, to answer my question, it would be a problem if the returned value was `C_NULL`.

**Comment by YingboMa** [comment]
I will make a PR if no one minds.
