### ISSUE TITLE
Heavy for loop is much faster inside function

### ISSUE THREAD

**Issue by doraemonho** [JuliaLang/julia#24792]
Hello,

  I am doing some heavy for loop inside julia and found a funny fact. When i compress a 3d array to 2d array using the following code
`nx,ny,nz=size(3dArray);`
`2darray=zeros(nx,ny);`
`for k in 1:nz,j in 1:ny, i in 1:nx`
`   2darray[i,j]+=3dArray[i,,j,k]`
`end`

If I took those code from main to the following 
`function compress!(3dArray::Array)`
`nx,ny,nz=size(3dArray);`
`2darray=zeros(nx,ny);`
`for k in 1:nz,j in 1:ny, i in 1:nx`
`   2darray[i,j]+=3dArray[i,,j,k]`
`end`
`end`

The perfornamce difference will look like that
 `julia> @time B=compress!(3dArray);`
  `0.091047 seconds (6 allocations: 1012.719 KB)`
`julia> @time for k in 1:nz,j in 1:ny, i in 1:nx`
`   2darray[i,j]+=3dArray[i,,j,k]`
`end`
`13.739274 seconds (280.20 M allocations: 5.570 GB, 4.15% gc time)`

The nx,ny,nz is quite large (nx*ny*nz~10^8-9)
I am curious why would it happen?

**Comment by timholy** [comment]
As it says in the default text when you first open an issue, please direct questions to https://discourse.julialang.org/; this site is for collaboratively developing Julia.

Please read https://docs.julialang.org/en/latest/manual/performance-tips/#man-performance-tips-1 before wondering about performance.
