### ISSUE TITLE
Linspace defaults the `n` parameter to 50

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#24794]
I was surprised when I found that Julia's `linspace` function uses the number 50 as the default argument for the number of steps:

```julia
linspace(start, stop, n=50)
```

Discussion on Slack indicated that this behavior comes from [SciPy](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linspace.html), but that it should probably be dropped for 0.7.

**Comment by JeffBezanson** [comment]
Agreed; that seems like a pretty arbitrary default value.

**Comment by fredrikekre** [comment]
What would be a better default value? Or is the idea that we shouldn't have a default value at all?

**Comment by nalimilan** [comment]
No default makes sense for this function IMHO.

**Comment by lobingera** [comment]
btw: on matlab 100

**Comment by timholy** [comment]
@yurivish, let me know if you intend to submit a PR, otherwise I will do it.

Relatedly, `logspace` has a default `base` of 10. I'm inclined to say it's fine to keep this.

**Comment by yurivish** [comment]
@timholy submitted: https://github.com/JuliaLang/julia/pull/24805

I noticed that `logspace` also had the default value `50` for its `n` argument so I changed that in the above PR as well for the same reasons we decided to remove it from `linspace`.

Unrelatedly, I noticed that the actual parameter for `linspace` is called `len` in the code, though it's `n` in the docs — should I file a separate PR for that?
