### ISSUE TITLE
Deprecate sum_kbn and cumsum_kbn?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24804]
It's unusual in the API to provide a separate function just to use a different algorithm. A more general and Julian approach would be to use something like `sum(x, alg=KahanBabuskaNeumaier)` or `sum(KahanBabuskaNeumaier, x)` (or just `KBN`).

Just like there is a separate SortingAlgorithms package, this does not need to live in Base.

**Comment by ViralBShah** [comment]
What are the upvotes for - baking into `sum` or removing from Base into a package?

**Comment by StefanKarpinski** [comment]
Let's just remove it for now, we can create a summation algorithms package or something.

**Comment by JeffBezanson** [comment]
Fine to move this out if somebody gets to it but seems pretty non-urgent to me.

**Comment by StefanKarpinski** [comment]
We could just delete it and let someone create a package if they really want it.
