### ISSUE TITLE
Build failure with libunwind 1.2.1

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24802]
I've bumped into this issue in Fedora rawhide, filing it here just in case somebody else is looking for it. Basically, the `UNW_VERSION_MINOR` constant contains a float value for releases with a patch version. So 1.3 (currently in RC) should work fine, but 1.3.1 will be problematic again. The error looks like this:
```
In file included from /usr/include/libunwind-x86_64.h:129:0,
from /usr/include/libunwind.h:25,
from /builddir/build/BUILD/julia-0.6.0/src/julia_internal.h:642,
from /builddir/build/BUILD/julia-0.6.0/src/typemap.c:7:
/builddir/build/BUILD/julia-0.6.0/src/julia_internal.h:646:35: error: floating constant in preprocessor expression
(UNW_VERSION_MAJOR == 1 && UNW_VERSION_MINOR > 1)) 
```
https://kojipkgs.fedoraproject.org/work/tasks/2353/23402353/build.log

I've filed the issue upstream here: https://savannah.nongnu.org/bugs/index.php?52529

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/23615
