### ISSUE TITLE
Unable to update or add new packages after JuliaPro 0.6.1 upgrade

### ISSUE THREAD

**Issue by pavanefpm** [JuliaLang/julia#24819]
I upgraded recently from Julia 0.6 to 0.6.1, using the Julia Pro installer.
    Julia Version 0.6.1
    Commit 0d7248e2ff* (2017-10-24 22:15 UTC)
    Platform Info:
      OS: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas64_
      LIBM: libopenlibm
      LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

However, installing a package or trying to update throws up the following error.

    julia> Pkg.add("Plots")
    ERROR: fixed packages introduce conflicting requirements for Gallium:
       available versions are 0.1.0
     check_requirements(::Dict{String,Base.Pkg.Types.VersionSet}, 
    ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Base.Pkg.Types.Fixed}) at 
    .\pkg\query.jl:222
    resolve(::Dict{String,Base.Pkg.Types.VersionSet}, 
    ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, 
    ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at .\pkg\entry.jl:496
    resolve(::Dict{String,Base.Pkg.Types.VersionSet}, 
    ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, 
    ::Dict{String,Base.Pkg.Types.Fixed}) at .\pkg\entry.jl:479
    edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at 
    .\pkg\entry.jl:30
    (::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at .\task.jl:335
    Stacktrace:
     [1] sync_end() at .\task.jl:287
     [2] macro expansion at .\task.jl:303 [inlined]
     [3] add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
     [4] (::Base.Pkg.Dir.##3#6{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:33
     [5] cd(::Base.Pkg.Dir.##3#6{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:59
     [6] withenv(::Base.Pkg.Dir.##2#5{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String},String}, 
    ::Pair{String,String}, ::Vararg{Pair{String,String},N} where N) at .\env.jl:157
     [7] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at .\pkg\dir.jl:32
     [8] add(::String) at .\pkg\pkg.jl:117

**Comment by KristofferC** [comment]
Will likely be fixed when https://github.com/JuliaLang/METADATA.jl/pull/12264 is merged.

**Comment by aviks** [comment]
Should be good now.
