### ISSUE TITLE
dump(T) should not print a subtype tree

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24812]
> dump [v]: Show every part of the representation of a value.

```jl
julia> dump(AbstractString)
AbstractString
  RevString{T<:AbstractString}
  Base.String = String
  SubString{T<:AbstractString}
  Base.SubstitutionString{T<:AbstractString}
  String
```

Printing a tree of all the subtypes of a type is not what it says on the tin. Dump should not do this – there should be a dedicated function that does this instead, such as the one proposed in #24741. Triaging just for getting rid of the current printing behavior. Adding the dedicated function can be done any time.

**Comment by vtjnash** [comment]
Cross-ref https://github.com/JuliaLang/julia/pull/921

**Comment by JeffBezanson** [comment]
I think this should print the fields of the given object, like it does for everything else. `subtypes` exists for seeing subtypes.

**Comment by StefanKarpinski** [comment]
Triage: this should print the visible fields of the type object itself, which probably just entails deleting the special handling code for types and letting the default implementation do its thing.

**Comment by timholy** [comment]
Currently `dump(T)` is also the most convenient way to see the parameters of `T` (vs `Base.unwrap_unionall(T)`). Presumably that use will continue with whatever new scheme is developed.

**Comment by Subhash-Saurabh** [comment]
I want to work on this issue. Can anyone tell me where to start.

**Comment by StefanKarpinski** [comment]
The starting point is

https://github.com/JuliaLang/julia/blob/292a3b4c73b91bcb3dbe2d9d7c56f8d747ce5207/base/show.jl#L1531

Instead of calling `dumptype`, that line should show the structure of the type.
