### ISSUE TITLE
document what `isbsd` means.

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#24813]
What does it mean to be a "derivative of BSD" ?

```
help?> Sys.isbsd
  Sys.isbsd([os])

  Predicate for testing if the OS is a derivative of BSD. See documentation in Handling Operating System Variation.
```

https://docs.julialang.org/en/latest/manual/handling-operating-system-variation/
gives no more help.

[Wikipedia says:](https://en.wikipedia.org/wiki/Berkeley_Software_Distribution)

> BSD releases provided a basis for several open source development projects that are ongoing, including FreeBSD, OpenBSD, NetBSD, Darwin, and TrueOS, among others. These, in turn, have been incorporated in whole or in part in modern proprietary operating systems, e.g., the TCP/IP networking code in Windows NT 3.1 and most of the foundation of Apple's macOS and iOS.

A key question is thus, is **OS X an included by `isbsd`?**,
or is that only covered by `isapple`?

**Comment by iblis17** [comment]
> A key question is thus, is OS X an included by isbsd?

yes, `Darwin` kernel included.

**Comment by ararslan** [comment]
It would be technically inaccurate to exclude macOS from `isbsd`, but at the same time I find it really annoying that I always have to write `Sys.isbsd() && !Sys.isapple()` to get "typical" BSDs.
