### ISSUE TITLE
Pkg.add() stalls 

### ISSUE THREAD

**Issue by ovidiugabriel** [JuliaLang/julia#24827]
Pkg.add() stalls on my julia running on  Windows 10 machine. The is no timeout for the command. I don't see any error message or any progress indicator.

**Comment by fredrikekre** [comment]
What are you trying to add?

**Comment by ovidiugabriel** [comment]
It doesn't matter. it's the same for  `Pkg.add("Gadfly")` or any other package as well, Pkg.add("Plots") or DataFrames... the result is the same; There is no feedback from the console after I press enter.

**Comment by ovidiugabriel** [comment]
If I wait 5 minutes, at the end the output is  Package Gadfly is already installed

**Comment by ovidiugabriel** [comment]
DataFrames is not responding at all...

**Comment by robmaz** [comment]
Are you behind a proxy? (see #24835)

**Comment by ovidiugabriel** [comment]
No, I am not behind a proxy and according to speedtest.net I have 93.78 Mbps download and 92.90 Mbps upload, so I don't think the Internet connection is an issue either.

I discussed with some guys on julia slack channel and they told me it is known that Pkg.add is slow and this will be improved in Julia 1.0. Is this true?

**Comment by StefanKarpinski** [comment]
Yes, it's true.

**Comment by dimitrijepetrovic** [comment]
Is anyone still seeing this issue. I'm on 1.2.0

**Comment by StefanKarpinski** [comment]
Since the package manager has been completely rewritten since this was filed, seems no longer relevant to keep this issue open. If someone gets `pkg> add` stalling it will be a new issue.
