### ISSUE TITLE
LoadError when throwing exception from macro

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#24825]
On 
```
Version 0.7.0-DEV.2675 (2017-11-27 20:28 UTC)
Commit f383276c5b (1 day old master)
```
I get
```julia
julia> macro myerror()
           throw(ErrorException(""))
       end
@myerror (macro with 1 method)

julia> @myerror()
ERROR: LoadError:
Stacktrace:
 [1] @myerror(::LineNumberNode, ::Module) at ./REPL[3]:2
in expression starting at REPL[4]:1
```

**Comment by yuyichao** [comment]
Addict this is expected. Your error message is empty which is why it doesn't show up

**Comment by andreasnoack** [comment]
Why does it throw a `LoadError`? It didn't do that on 0.6?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/23533

**Comment by andreasnoack** [comment]
Thanks. Is this
```julia
julia> @test_throws ErrorException eval(:(@myerror()))
Test Failed at REPL[26]:1
  Expression: eval($(Expr(:quote, :(#= REPL[26]:1 =# @myerror))))
    Expected: ErrorException
      Thrown: LoadError
ERROR: There was an error during testing
```
then an issue with `@test_throws`? I noticed that I can catch the `eval`ed version and not the non-evaled, i.e.
```julia
julia> try eval(:(@myerror()))
       catch
       end

julia> try @myerror()
       catch
       end
ERROR: LoadError: 
Stacktrace:
 [1] @myerror(::LineNumberNode, ::Module) at ./REPL[12]:2
in expression starting at REPL[30]:1
```

The `LoadError` is also a bit unintuitive given the documentation which states that
> An error occurred while includeing, requireing, or using a file. The error specifics should be
  available in the .error field.

and I'm probably not the only user for whom it is not obivous where to look for the `include`, `require`, or `using`.
