### ISSUE TITLE
Improved consistency of @ inferred with other test macros

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#24829]
As a heavy user of `@inferred` I'd like it to be a little more user friendly and consistent with the other testing macros.  My main gripe is that it's a test in its own right; I'd like to be able to write `@test_inferred f(x)` and have it register with the current test set, rather than unilaterally throwing an exception on failure.

The `@test_warn` macro does exactly this, and also returns the result so that it can be composed with `@test` if desired:

```julia
@test (@test_warn "deprecated" num2hex(1)) == "0000000000000001"
```

See related discussion over at: https://github.com/JuliaLang/julia/issues/20348#issuecomment-347563061

I think there's two separate decisions here:
1. Make `@inferred` register the result with the current test set
2. If this is done, consider renaming to `@test_inferred` for consistency with other testing macros.

**Comment by c42f** [comment]
Original discussion around `@inferred`: https://github.com/JuliaLang/julia/pull/5404

**Comment by fredrikekre** [comment]
Related: #21098
