### ISSUE TITLE
pkg.jl has problems behind a proxy

### ISSUE THREAD

**Issue by robmaz** [JuliaLang/julia#24835]
Pkg.init() & Co. do not seem to respect the proxy settings of the environment (export http_proxy=http://proxy.host:port) and consequently fail with a timeout. This happens for me with Julia 0.6.1 for MacOS (binary distribution) where I use git and curl from the command line all the time without problems, but a bit of googling reveals that many people have similar problems. This makes Julia currently basically unusable behind stricter firewalls.

Variants of this problem have been reported on and off for two or more years. Some people have seen this as a libgit2 problem, but the libgit2 people do not seem to agree, see https://github.com/libgit2/libgit2/issues/4069

**Comment by robmaz** [comment]
Maybe also related: #24202

**Comment by StefanKarpinski** [comment]
cc @omus

**Comment by omus** [comment]
I'll try to look into it. Have you tried setting the proxy using the git configuration? Something like:
```bash
git config --global http.proxy http://proxy.host:port
```

**Comment by robmaz** [comment]
I have settings for http.proxy and https.proxy in my ~/.gitconfig and also
http_proxy and https_proxy
environment variables, which, according to the libgit2 people, should be
picked up by libgit2, although
I cannot seem to find any clear documentation on this.

I also have this in .gitconfig:

 [url "https://"]

    insteadOf = git://


but it seems that Pkg.init() is trying
https://github.com/JuliaLang/METADATA.jl anyway:


  julia> Pkg.init()

  INFO: Initializing package repository /Users/maz/.julia/v0.6

  INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl

  ERROR: GitError(Code:ERROR, Class:OS, Failed to connect to github.com:
Operation timed out)

  Stacktrace:

   [1] macro expansion at ./libgit2/error.jl:99 [inlined]

   [2] clone(::String, ::String, ::Base.LibGit2.CloneOptions) at
./libgit2/repository.jl:276

   [3] #clone#100(::String, ::Bool, ::Ptr{Void},
::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String,
::String) at ./libgit2/libgit2.jl:562

   [4] (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone,
::String, ::String) at ./<missing>:0

   [5] (::Base.Pkg.Dir.##8#10{String,String})() at ./pkg/dir.jl:55

   [6] cd(::Base.Pkg.Dir.##8#10{String,String}, ::String) at ./file.jl:70

   [7] init(::String, ::String) at ./pkg/dir.jl:53

   [8] init() at ./pkg/pkg.jl:85

Many thanks for looking into this.

2017-12-05 23:20 GMT+01:00 Curtis Vogt <notifications@github.com>:

**Comment by robmaz** [comment]
A potential peculiarity in our proxy setup is that the https proxy has a
http url, i.e.,

  [https]

proxy = http://proxy.host:port/


I do not know how common this is, and wonder if this url maybe confuses
mbedTLS?

Probably none of the working programs (git, curl, wget, Firefox, Safari) use
this library.

2017-12-06 17:21 GMT+01:00 Curtis Vogt <notifications@github.com>:

**Comment by ethomson** [comment]
👋  Just to confirm:  libgit2 should have no problem using the `https.proxy` configuration setting _or_ using `HTTP_PROXY` and `HTTPS_PROXY` environment variables.  These aren't curl specific (they actually originated in lynx, if memory serves).

You do, however, need to make sure that you ask libgit2 to pay attention to all of these things; the default behavior is to honor proxies that were explicitly passed in the configuration.

In particular, when [setting up your clone options structure](https://github.com/JuliaLang/julia/blob/84ff39fe568476d1cd1bdb017a325fb5faa9368b/stdlib/LibGit2/src/LibGit2.jl#L534), you need to set `fetch_opts.proxy_opts.type = GIT_PROXY_AUTO`.

**Comment by robmaz** [comment]
Many thanks for looking into this. In fact, it looks as if it actually works already (in 0.6.2) with the uppercase versions of the environment variables, but not the lowercase ones.

**Comment by omus** [comment]
I'm glad things are working for you @robmaz. Since the proxy is working on Julia 0.6.2 should this issue be closed?

**Comment by robmaz** [comment]
I guess it should. Thanks again!
