### ISSUE TITLE
bounds checking of "abc"[1:3] is very redundant

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24841]
Partly due to https://github.com/JuliaLang/julia/issues/24840, taking a slice of a string ends up checking bounds at least three different times. This should be reduced to a single time.

**Comment by laborg** [comment]
On master I could only spot one `boundcheck`  (and https://github.com/JuliaLang/julia/pull/29796 has improved performance and added the necessary `@inline`).

**Comment by laborg** [comment]
Ah, calling `j = nextind(s,j) -1` might still be a redundant.
