### ISSUE TITLE
sprint: rename `env` keyword, add `size` keyword

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24868]
As observed in https://github.com/JuliaLang/julia/pull/24727, the `sprint` function takes an `env` keyword which could have a better name, e.g. `context`. All methods should accept that keyword. It would also be better to have a `sizehint` keyword than the awkward leading positional size argument.

**Comment by JeffBezanson** [comment]
We could also replace the `env` keyword with `sprint(io->f(IOContext(io, your_env_here), ...`

**Comment by AvikPal14** [comment]
I would like to tackle this issue. As this is my first ever open source contribution it would be great to get some help and other recommendations .

**Comment by StefanKarpinski** [comment]
@evetion already did this: https://github.com/JuliaLang/julia/pull/24913.
