### ISSUE TITLE
Documentation of `isreal` is incorrect for Inf and NaN

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#24870]
```
help?> isreal

  isreal(x) -> Bool

  Test whether x or all its elements are numerically equal to some real
  number.
```
But
```
julia> isreal(Inf)
true

julia> isreal(NaN)
true
```
Neither `Inf` nor `NaN` is "numerically equal to a real number".

**Comment by dpsanders** [comment]
(I was looking for `isfinite` and thought `isreal` would behave the same.)

**Comment by StefanKarpinski** [comment]
I would argue that `Inf` is an extended real number so that's probably ok, but `NaN` might be considered non-real. It's unclear to me if that's a helpful definition or not though.

**Comment by Subhash-Saurabh** [comment]
I am new to julia and I want to work on this. Can anyone tell me what exactly needs to be done.

**Comment by andreasnoack** [comment]
@Subhash-Saurabh You could open a PR that adds a the uncontroversial `NaN` check to `isreal` and as well as tests. Then we can continue the discussion of `Inf` in your PR.

**Comment by StefanKarpinski** [comment]
The current definition has the benefit of always being true for subtypes of `Real`. I'm not actually sure that we want to change that – I suspect that the best course of action here is just to fix the documentation.
