### ISSUE TITLE
Performance on small matrix algebra

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#2489]
The following code compares current Julia implementation and hand-crafted implementation of matrix multiplication and inversion on 2-by-2 matrices.

``` julia
a = rand(2, 2)
b = rand(2, 2)

r = a * b  # warming up
@time for i = 1 : 10^6
    r = a * b
end

function mul2(a::Matrix, b::Matrix)
    c = Array(Float64, 2, 2)

    c[1] = a[1] * b[1] + a[3] * b[2]
    c[2] = a[2] * b[1] + a[4] * b[2]
    c[3] = a[1] * b[3] + a[3] * b[4]
    c[4] = a[2] * b[3] + a[4] * b[4]
    c
end

mul2(a, b) # warming up
@time for i = 1 : 10^6
    r = mul2(a, b)
end
```

`mul2(a, b)` is about 4x faster than `a * b`.

Even more significant difference is observed for inversion.

``` julia
a = rand(2, 2)

r = inv(a)
@time for i = 1 : 10^6
    r = inv(a)
end

function inv2(a::Matrix)
    c = Array(Float64, 2, 2)

    detv = a[1] * a[4] - a[2] * a[3]
    inv_d = 1 / detv

    c[1] = a[4] * inv_d
    c[2] = -a[2] * inv_d
    c[3] = -a[3] * inv_d
    c[4] = a[1] * inv_d
    c
end

r = inv2(a)
@time for i = 1 : 10^6
    r = inv2(a)
end
```

`inv2` is about 25x faster than `inv`.

A carefully crafted SIMD implementation can lead to 5x to 10x gain compared to the scalar version `inv2` and `mul2` -- which is at least two orders of magnitude faster than current Julia version.  There are some reference SIMD implementation in Intel's website. Eigen also implements some of these.

Fast implementation on small matrices (e.g. `2 x 2`, `3 x 3`, and `4 x 4`) are important for graphics, geometric computation, and some image processing applications.

**Comment by felixrehren** [comment]
Current status:
* `a * b` takes 25% longer than `mul2(a,b)`
* `inv(c)` takes x10 longer than `inv2(c)`

Big improvements from OP. Tests:

    julia> a = rand(2,2);
    julia> b = rand(2,2);
    julia> r = a * b;
    julia> @time for i = 1 : 10^6
           r = a * b
           end
      0.112353 seconds (1000.00 k allocations: 106.812 MB, 8.97% gc time)
    julia> mul2(a,b);
    julia> @time for i = 1 : 10^6
           r = mul2(a,b)
           end
      0.087943 seconds (1000.00 k allocations: 106.812 MB, 6.36% gc time)

    julia> c = rand(2,2);
    julia> r = inv(c);
    julia> @time for i in 1:10^6
           r = inv(c)
           end
      1.072095 seconds (10.00 M allocations: 1.654 GB, 8.07% gc time)
    julia> r = inv2(c);
    julia> @time for i in 1:10^6
           r = inv2(c)
           end
      0.085211 seconds (1000.00 k allocations: 106.812 MB, 8.60% gc time)

Is this already benchmarked?

**Comment by andreasnoack** [comment]
Notice that we now have https://github.com/JuliaArrays/StaticArrays.jl. Also, although the Base methods possibly could do better for small matrices, the fast versions used in the benchmarks here are not directly comparable to the Base versions because the fast versions use less precise algorithms.

**Comment by KristofferC** [comment]
I feel this is sufficiently covered by StaticArrays (which also automatically uses SIMD in matmul with -O3).
