### ISSUE TITLE
rename Factorization to AbstractFactorization

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#24917]
Being the abstract supertype of all factorizations, `Factorization` should probably be renamed `AbstractFactorization`. Best!

**Comment by andreasnoack** [comment]
The naming convention has been discussed a couple of times over the years. At some point, the consensus was that *Abstract* in the name was generally redundant and should be avoided unless the type could be confused with a concrete type. Maybe it was discussed as part of the change from `FloatingPoint` to `AbstractFloat`.

**Comment by JeffBezanson** [comment]
I don't think this rename is necessary.

**Comment by Sacha0** [comment]
Cheers, @andreasnoack's explanation is convincing. Thanks al! :)
