### ISSUE TITLE
segfault on BLAS operation with incorrect character input

### ISSUE THREAD

**Issue by colintbowers** [JuliaLang/julia#24923]
The following:
```
m = randn(4, 2)
v = randn(2)
Base.LinAlg.BLAS.gemv('n', 1.0, m, v)
```
results in a segfault on v0.6 and v0.7.

One possible fix could be to include an additional `else` clause at line 559 in master of https://github.com/JuliaLang/julia/blob/master/base/linalg/blas.jl to catch other character inputs. But this would only help for calls to `gemv`. Maybe someone else can think of a more universal fix? (I'm probably out of my depth here)

**Comment by simonbyrne** [comment]
Ultimately the question is how much checking we want to do here. These are meant to be advanced interfaces.

**Comment by StefanKarpinski** [comment]
I don't think that segfaulting on any non-unsafe interface from Julia should happen. This seems like a very cheap and easy check to add, especially compared to the cost of a gemv.

**Comment by andreasnoack** [comment]
We generally try to check for everything before calling BLAS or LAPACK so I think we should just adjust the checks here to make sure that the input is valid. However, most people shouldn't need to call the methods in the `BLAS` or `LAPACK` modules. There are currently a few use cases for this but eventually, we should extend the signatures for `A_mul_B!` family such that calling the methods in `BLAS` directly isn't needed.

**Comment by RalphAS** [comment]
I think the segfault is due to the fact that BLAS accepts the 'n' but the Julia wrapper only allocates the correct result space for the upper case 'N', so BLAS trashes the heap here.

Other characters do the "expected" thing, viz.:
```julia
julia> Base.LinAlg.BLAS.gemv('w',1.0,m,v)
 ** On entry to DGEMV  parameter number  1 had an illegal value
2-element Array{Float64,1}:
 0.0
 0.0
```
and the result is usually junk (zero here by luck of the draw).  To second Andreas: BLAS does not return an error condition, so Julia must validate inputs. To second him again, Julia **does** validate inputs for the public API.  If I were a developer, I'd ask @colintbowers to write his own PR.

**Comment by ViralBShah** [comment]
These are very low-level wrappers and not for the uninformed user. I doubt we are going to add these checks all over, and it should be openblas that guards against these.

**Comment by ViralBShah** [comment]
Original case no longer segfaults, and bad inputs give a warning, but not an error yet. The error handling of BLAS/LAPACK routines and making them end-user safe would be a major undertaking, and should have its own investigation and issue, if we want to do something.

```
julia> BLAS.gemv('n', 1.0, m, v)
2-element Vector{Float64}:
 -0.6933114114350734
 -3.0674262838789312

julia> BLAS.gemv('q', 1.0, m, v)
 ** On entry to DGEMV  parameter number  1 had an illegal value
2-element Vector{Float64}:
 0.0
 0.0
```
