### ISSUE TITLE
Provide a way to update METADATA without upgrading packages

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#2492]
There are two different things that `Pkg.update()` does right now - it updates the metadata, and the packages, both. Typically, package managers use `update` for metadata, and `upgrade` for packages.

It is useful to differentiate between these two operations. There are often times when I just want the latest metadata, so that I can pull some new packages. However, I am not interested in upgrading my existing packages (unless the new package has dependencies that upgrade existing packages).

This would be a major API change, and perhaps we can let `update` do what it currently does, and have a different function for just updating the metadata. However, the terminology would then be inconsistent with most other package managers.

**Comment by vtjnash** [comment]
there have been no comments here in over a year. Stefan, can you give us an update on your last comment there and a proposed resolution for this issue (close as unnecessary/wont-fix; moved to another issue for development of Pkg3; will implement the `cd METADATA && git pull` behavior; etc.)?

**Comment by StefanKarpinski** [comment]
Yeah, revamping Pkg is not happening in 0.4 at this point.

**Comment by wildart** [comment]
Probably no backports as well, and so it falls into 0.5

**Comment by vtjnash** [comment]
any comment on what will be done?

**Comment by wildart** [comment]
Not sure, there are many issues put on hold and only be addressed after `libgit2` transition. See `package` tag.
