### ISSUE TITLE
"missing" test conflict

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#24949]
https://circleci.com/gh/JuliaLang/julia/10994?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
  Expression: zero(String)
    Expected: MethodError
  No exception thrown
```
(this method is defined by test/sparse/sparse.jl)

**Comment by rfourquet** [comment]
cc @nalimilan

**Comment by nalimilan** [comment]
I don't understand. Why doesn't it happen on Travis in recent builds? See for example https://travis-ci.org/JuliaLang/julia/builds/313160852.

**Comment by KristofferC** [comment]
Probably needs to run on the same worker for it to occur.

**Comment by rfourquet** [comment]
I could be that the failure depends on the order in which the tests are run.

**Comment by rfourquet** [comment]
You can reproduce with: `JULIA_CPU_CORES=1 julia test/runtests.jl sparse/sparse missing`

**Comment by nalimilan** [comment]
OK, I think I have a simple fix.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/pull/24984.
