### ISSUE TITLE
JuliaPro 0.6.0.1 crash at activation

### ISSUE THREAD

**Issue by Alex0573** [JuliaLang/julia#24958]
I have been using JuliaPro 0.6.0.1 on a Mac and it worked click-and-go. 
when trying to open it, after a restart, it issued an error:

Error: EACCES: permission denied, open '/Applications/JuliaPro-0.6.0.1.app/Contents/MacOS/JuliaPro-Juno-0.6.0.1.app/Contents/Resources/julia_atom_0.6.0.1/compile-cache/less/df1b7fbc57dbeed23a8f1f8de95b4dfebcc06066/imports.json'

<a longer log>

Help is appreciated

**Comment by ViralBShah** [comment]
Please do not file JuliaPro issues here. Email juliapro@juliacomputing.com.
