### ISSUE TITLE
multi-loop lowering bug

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#24979]
Reported here https://github.com/JuliaLang/julia/issues/330#issuecomment-350134536:
```
julia> for x=1:4, y=1:2
          println( (x,y) )
          (y,x) = (x,y)
       end
(1, 1)
(1, 2)
(2, 1)
(1, 2)
(3, 1)
(1, 2)
(4, 1)
(1, 2)
```
Expected (`x` and `y` reset):
```
(1, 1)
(1, 2)
(2, 1)
(2, 2)
(3, 1)
(3, 2)
(4, 1)
(4, 2)
```
Seen on both 0.6.1 and recent master (00e3a9faeb).

**Comment by martinholters** [comment]
I think this is a dup of #330, see https://github.com/JuliaLang/julia/issues/330#issuecomment-350210304.

**Comment by StefanKarpinski** [comment]
We'll close if it is a dup 👍

**Comment by JeffBezanson** [comment]
Closing as dup.
