### ISSUE TITLE
code_warntype does not give good information with keyword arguments

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#24985]
I am surprised I couldn't find an issue to follow for this. `@code_warntype` does not give good information on functions with keyword arguments because it instead just shows that an internal function is called. With the change of keyword arguments to NamedTuples, presumably the setup is different and `@code_warntype` can be more informative about type-stability of functions behind keyword argument walls.

**Comment by quinnj** [comment]
dup of https://github.com/JuliaLang/julia/issues/5230

**Comment by cossio** [comment]
It doesn't look like the same issue @quinnj ? Also that one was closed, but `@code_warntype` still fails to print the code of functions with keyword arguments (it just prints a call to the internal function). 

https://discourse.julialang.org/t/code-warntype-fails-when-function-has-a-keyword-argument/21907
https://discourse.julialang.org/t/use-of-code-warntype-on-a-function-with-keyword-arguments/5521

Should this be reopened?
