### ISSUE TITLE
Make `helpdb.jl` and docs as part of build

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#2501]
Now that binary builds are a reality, it might be time for us to stop checking in `helpdb.jl` and make Sphinx a build dependency. We could consider making it an option so you could choose not to build the docs (another Make variable?)

This has implications for the work @wlbksy is doing in #2499.

**Comment by ViralBShah** [comment]
@staticfloat @tkelman What do you guys feel about doing this, and autogenerating helpdb.jl - requiring sphinx as a build dependency. I think we are ready for it.

**Comment by ViralBShah** [comment]
Of course, non-existence of sphinx should be detected and become a warning, rather than fail the build.

**Comment by tkelman** [comment]
Worth trying a PR for it, sure. Especially now that we've got the virtualenv stuff hooked up. It's making our build more reliant on Python's package manager working properly, but we can try it out. I haven't timed `make -C doc`, about how much time would it add to the Travis build? I'd want to skip it (so fail fast or add a simple variable to disable it) on AppVeyor if it takes any more than about 30-60 seconds, to avoid making the queue any longer.

**Comment by ViralBShah** [comment]
`make helpdb.jl` is 47 seconds on my mac, which includes getting all the deps and setting up the virtualenv.

**Comment by tkelman** [comment]
It's about 50 seconds using Cygwin's python, not too bad. I think AppVeyor probably has a win32 python on the path. I'd probably want to disable it on all the CI except Travis, maybe even do helpdb.jl (along with code style / whitespace checks) in a separate build matrix entry.

**Comment by ViralBShah** [comment]
That seems quite reasonable.

**Comment by staticfloat** [comment]
Since we have the `virtualenv` stuff working pretty well now, I think it's definitely worth a shot as a separate build matrix entry.  Debian does this with their arch-independent build targets.  :P

**Comment by tkelman** [comment]
see #9553 and #9554

**Comment by tkelman** [comment]
With #11906 I think this can be closed. AIUI `helpdb.jl` is now the manually created version, but will be gradually separated out into docstrings at definitions instead.
