### ISSUE TITLE
SimJulia

### ISSUE THREAD

**Issue by rbacher** [JuliaLang/julia#25024]
After installing SimJulia under Julia 0.6.1 (Win 10), I try to run simple examples such as shown below.
But I get a very early ERROR message such as: 
![grafik](https://user-images.githubusercontent.com/6154671/33823030-f26a302e-de59-11e7-800b-9ac1ce0d246f.png)
(ERROR: UndefVarError: Environment not defined.)
What is wrong?
Thanks
Rainer
---

Pkg.add("SimJulia") # works perfectly
using SimJulia # works perfectly
(Pkg.test("SimJulia") # works just fine.
# the next function dies
function car(env::Environment)
while true
println("Start parking at $(now(env))")
parking_duration = 5.0
yield(Timeout(env, parking_duration))
println("Start driving at $(now(env))")
trip_duration = 2.0
yield(Timeout(env, trip_duration))
end
end

**Comment by fredrikekre** [comment]
Please ask questions on discourse https://discourse.julialang.org/
If this is a legitimate issue and not a user error it should be reported to https://github.com/BenLauwens/SimJulia.jl and not this repo.
