### ISSUE TITLE
missing two-argument fastmath logarithm

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#25027]
Same for bigger float types, both on julia 0.6 and 0.7:

```
@fastmath log(2.4,5.6)
MethodError: no method matching log_fast(::Float64, ::Float64)
```

Currently code using the two-argument form of log fails to compile under fastmath.

As far as I gathered, we use log(base, x)= log(x)/log(base) anyway (no simplifications that need only one ccall to libm, as opposed to pow), so we'd need something like `log_fast(base,x)=log(base,x)` (if `log(base,x) `is inlined and fastmath is propagated; I'm not sure how this is handled, but we want the division to be inlined and fastmath'ed). Alternatively `log_fast(base,x)=log_fast(x)/log_fast(base)`, but this might be breaking for some user-defined types and log-functions (e.g. discrete log in small group), so one should restrict to appropriate types. 

The fix should be a one-liner, I'm just not sure what line.

But maybe one should also consider altogether removing the two-argument form of log, since it doesn't save us a ccall anyway and encourages users to not think about saving `log(base)` (this would be breaking).

**Comment by mcognetta** [comment]
I looked into this and just added a line
`
log_fast(base::T, x::T) where {T<:FloatTypes} = div_float_fast(log_fast(x), log_fast(base))
`
into fastmath.jl. Having trouble testing if it really helps or if I just did it wrong.

**Comment by fredrikekre** [comment]
#25674
