### ISSUE TITLE
fix isbits predicate

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#25044]
Right now, it returns wrong answers. Also, we should look into fixing the `isleaftype` predicate.

**Comment by JeffBezanson** [comment]
Example(s)?

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/issues/23567 and https://github.com/JuliaLang/julia/issues/17086

**Comment by StefanKarpinski** [comment]
@vtjnash: please define what your notion of "correct" is in this case. I've noticed that your definitions are not always what I would consider intuitive.

**Comment by vtjnash** [comment]
Master is the only version where this is broken. It was correct on all our releases.

**Comment by StefanKarpinski** [comment]
Yes, but previously `Union{Int, Void}` for example, was not represented as "just bits". Does that qualify as `isbits` according you your notion of this or not?

**Comment by vtjnash** [comment]
`isbits` is defined in https://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/#Type-Correspondences:-1 (somewhat vaguely worded, but that can be fixed). It isn't a floating definition based on the representation. This is already documented in the linked issues, I just needed a placeholder issue to make sure I remember to address this regression before 0.7-release

**Comment by StefanKarpinski** [comment]
Are tuples of bits types also bits types? Again, that definition was written before we had the ability to represent simple unions as "just bits". Yes, we could just leave it as is, but should we?

**Comment by vtjnash** [comment]
simple unions aren't represented as "just bits", they use a special layout and don't map to a C type

**Comment by StefanKarpinski** [comment]
They do map to C unions if you ignore the selector bits, which are not in the "main" part of the value.
