### ISSUE TITLE
Using Pyplot for the first time - Matplotlib error

### ISSUE THREAD

**Issue by MerryMurray** [JuliaLang/julia#25053]
Julia 0.6.1  Anconda

hope this is the right forum

using PyPlot

sys:1: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to u'Qt5Agg' by the following code:
  File "/root/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

Thanks

**Comment by fredrikekre** [comment]
As stated in the issue template you should use https://discourse.julialang.org/ for questions. If this is a legitimate issue it should be reported to https://github.com/JuliaPy/PyPlot.jl and not this repository.
