### ISSUE TITLE
isascii was left behind in the Unicode move

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#25075]
On 0.6:
```
julia> isascii
isascii (generic function with 2 methods)
```
On 0.7.0-DEV.2949:
```
julia> isascii
ERROR: UndefVarError: isascii not defined

julia> Base.isascii
ERROR: UndefVarError: isascii not defined

julia> Unicode.isascii
ERROR: UndefVarError: isascii not defined

julia> Base.Unicode.isascii
isascii (generic function with 2 methods)
```
Seems like it should be defined in the Unicode stdlib package and have a deprecation message.

**Comment by StefanKarpinski** [comment]
Not exported from stdlib `Unicode`:
https://github.com/JuliaLang/julia/blob/756936abe846c1e46a9751a238ba0dcac7f45160/stdlib/Unicode/src/Unicode.jl#L12-L15

**Comment by StefanKarpinski** [comment]
I wonder if we shouldn't just leave `isascii` in Base? It's not like its meaning is going to change.

**Comment by nalimilan** [comment]
Woops, looks like I stopped half-way... Yes, we could keep it in Base (actually I think I suggested that in the PR), since it's not really a Unicode function. Also it's special because it's the only predicate which accepts a string argument, and not only a `Char`.

**Comment by StefanKarpinski** [comment]
Ok, let's just reinstate it to Base then.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/pull/25076.

However, regarding a more general rule to decide which functions should live in Unicode, note that `isdigit` and `isxdigit` do not depend on changes in the Unicode standard either, so they could be kept in Base by that rule. Same for `isvalid` IIUC.

**Comment by StefanKarpinski** [comment]
Those all seem reasonable to me. We may want to rename `isxdigit` to `ishexdigit` while we're at it, to avoid being quite as cryptic, although the name `isxdigit` is quite ubiquitous, unfortunately.

**Comment by IgorFomenko** [comment]
Hi, why I`ve got the same error with variable name beginning with \partial unicode?

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
