### ISSUE TITLE
Annotation (Metadata association)

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#2508]
This might sound speculative, but can be useful in developing a system with many interacting types. 

What I request here is to be able to associate metadata to types, methods, and modules. Such capability has been implemented in a series of popular languages -- they call it using different names though. For example,
* C# has [attributes](http://oreilly.com/catalog/progcsharp/chapter/ch18.html).
* Java has [annotations](http://en.wikipedia.org/wiki/Java_annotation).
* Python has [decorators](http://www.python.org/dev/peps/pep-0318/).
* C++ add [attributes](http://www.codesynthesis.com/~boris/blog/2012/04/18/cxx11-generalized-attributes/) in the latest C++11 standards.

These languages implement this capability using different ways.

The development of an inference framework reminds me of the benefit of being able to add metadata. To be more specific, I am considering something like this

```julia
[[factor_params(:mu, :sigma)]]
[[message_type(GaussMessage)]]
type GaussFactor <: AbstractFactor
    mu::Float64
    sigma::Float64
end
```

There are many discussions on the utility of metadata in more general setting. Here is one in Stackoverflow: http://stackoverflow.com/questions/20346/net-what-are-attributes

**Comment by hayd** [comment]
>  anything Python decorators can do, Julia macros can also do, by the nature of the Python decorator implementation.

It's be great if there was a (simple) example of how to do python-like decorators in julia. In the metaprogramming docs there doesn't seem to be any examples which pass a function (aside perhaps from `@generated`? but only this macro's *usage* is described not it's definition).

A logging ~~macro~~ decorator you can do easily in python:
```
def print_calltime(func):
    "Each time func is called print the time taken."
    @functools.wraps
    def wrapped(*args, **kwargs):
        before = datetime.now()
        res = func(*args, **kwargs)
        time_taken = datetime.now() - before
        print("call to", func.__name__, "took", time_taken)
        return res
    return wrapped
```

**Comment by vtjnash** [comment]
we have macros, first-class lambdas, a doc system, and `:meta` expr nodes. (as well as dispatch, and staged functions if you must). i feel that must must cover everything? if not, there's also Dict and ObjectIdDict.
