### ISSUE TITLE
renaming ind2sub and sub2ind?

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#25084]
from [API Consistency review issue](https://github.com/JuliaLang/julia/issues/20402#issuecomment-315080271), which received some support, and `rad2deg` & `deg2rad` was mentioned too.

**Comment by rfourquet** [comment]
my bad, this have [just](24999) been deprecated already!

**Comment by StefanKarpinski** [comment]
No, that was `chr2ind` and `ind2chr`, afaik, `ind2sub` and `sub2ind` still exist but there was some talk of a better replacement that's more generic in terms of how array indexing is done.

**Comment by rfourquet** [comment]
x-ref: #25113
I'm re-opening so that @timholy can have the satisfaction to close an issue... or maybe he has already closed plenty enough of them for a lifetime :grin:

**Comment by timholy** [comment]
Really this one is @barche's!
