### ISSUE TITLE
Add workspace deprecations?

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julia#25166]
Workspace wasn't deprecated, just removed, was this intended?

```julia
julia> VERSION
v"0.7.0-DEV.3089"

julia> workspace()
ERROR: UndefVarError: workspace not defined
```

**Comment by Ismael-VC** [comment]
Should we add some mesage like "`workspace` is deprecated, check out Revise.jl instead"?

* Reference: https://github.com/JuliaLang/julia/pull/25046#discussion-diff-156563358R735

**Comment by KristofferC** [comment]
I don't think it is worth deprecating. It is an interactive feature. A more detailed error message could be beneficial though.

**Comment by fredrikekre** [comment]
Huh, wonder why this wasn't auto closed...

**Comment by StefanKarpinski** [comment]
Autoclose has not been working well for me for a while.
