### ISSUE TITLE
Merge bkfact and ldltfact

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#25194]
Unless I'm missing something, it seems that bkfact and ldltfact perform the same function, one for dense matrices, the other for sparse. Among other things, it means that if one looks for a LDLT factorization, one finds ldltfact, sees that it works only for sparse matrices, and concludes that julia doesn't wrap dense LDLT factorization, as was the case e.g. in https://discourse.julialang.org/t/type-stable-matrix-factorization-corner-case-with-forwarddiff/7791/10. If possible, the two should be merged.

**Comment by andreasnoack** [comment]
They are related but not the same. What we call LDLt has a diagonal D matrix and doesn't apply pivoting. Bunch-Kaufman can have 2x2 blocks in the diagonal and applies pivoting. The Bunch-Kaufman furthermore uses some square roots when deciding between 1x1 and 2x2 blocks in the diagonal so in contrast to the LDLt it isn't possible to compute in rational arithmetic.

**Comment by antoine-levitt** [comment]
LDLT uses pivoting by default, but fair point on the 2x2 blocks. Still the functional uses are the same (factor this symmetric indefinite matrix), the current signatures are exclusive (sparse and dense), and the literature refers to LDLT even in the case where D has 2x2 blocks, so it looks like it would make sense to merge both into `ldltfact`.

**Comment by andreasnoack** [comment]
> Still the functional uses are the same (factor this symmetric indefinite matrix), the current signatures are exclusive (sparse and dense), and the literature refers to LDLT even in the case where D has 2x2 blocks

I agree and I think it would make sense to rename `bkfact` to `ldltfact`.

> LDLT uses pivoting by default

Currently, we have two different versions of LDLt, one for `SymTridiagonal` and from SuiteSparse. The former doesn't use pivoting at all and the latter only uses pivoting during the symbolic factorization to reduce fill.

**Comment by timholy** [comment]
I'm fond of those papers that distinguish the factorizations using `LBLt`. (`D` means "diagonal" to me.) It's not even true that all matrices have an `LDLt` factorization, but all have an `LBLt`.

**Comment by raphaelchinchilla** [comment]
Quick question, what happened to bkfact and ldltfact? I am trying to use them but cannot find them. It seems that the issue has been solved and could be marked as closed.

**Comment by ViralBShah** [comment]
Unlike to change this now. We have `bunchkaufman` and `ldlt`.

**Comment by raphaelchinchilla** [comment]
@ViralBShah I spent a good amount of time looking for a LBL decomposition, which, if I understand well, is implemented as `bunchkaufman`. I suggest some reference to it somewhere, maybe having an alias called `lblt` or having it in the list of similar functions to `ldlt`. Otherwise, I am not sure how someone can have the idea of finding it under `bunchkaufman`
