### ISSUE TITLE
Bikeshed better positional argument names post 1.0

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/julia#25198]
There are many one letter argument names, that really should be more mnemonic IMHO, things like `r`/`f` for **replacement**, for example. While all objects should be documented someday, good names should be a must for the public Julia API, since method signatures, argument and parameters names are part of this API.

Reference: https://github.com/JuliaLang/julia/pull/25165#issuecomment-352892601

> Positional argument names can be changed at any point without breaking anyone's code. We are at the moment focused on things that need to be changed for 1.0. We can bikeshed better positional argument names until the cows come home post 1.0. - Stefan

**Comment by Ismael-VC** [comment]
Maybe it's time to follow JuliaPraxis guidelines?

* https://github.com/JuliaPraxis/Naming/blob/master/guides/ShortForms.md#table-of-abbreviations

And expand those guidelines as needed.

**Comment by Ismael-VC** [comment]
@arsalan It's just a suggestion, but wonder why do you disagree with. JuliaPraxis guidelines? Enforcing *any* guidelines? Renaming these variables?

I'm all in for consistency and good naming practices, I'm ok with whatever the guidelines end up being as long as we do enforce it's use, specially in base Julia, even if this cryptic variables are properly documented.

**Comment by ararslan** [comment]
JuliaPraxis guidelines are not official. Any discussion regarding those guidelines should happen on that repo.

**Comment by Ismael-VC** [comment]
That is true, but I think the very purpose of JuliaPraxis is to become something we all agree becomes an official guideline, what are the official guidelines that we can discuss here then? There is the "official" style guide, but it doesn't mention any of this.

* https://docs.julialang.org/en/stable/manual/style-guide

And some minor stylistic conventions here:

* https://docs.julialang.org/en/stable/manual/variables/#Stylistic-Conventions-1

At least I think the intention of @JeffreySarnoff was never to start a separate Style guide just for the sake of having something different than what is told in the links above. On the contrary, I believe JuliaPraxis was born precisely from the need of having some place to discuss this bike shedding stuff without nagging everyone else with "noise".

If the problem is that the style guide is not in this repository, then it would be easy to add those documents here, the issue remains the same, we need to discuss and enforce the agreed guidelines, sooner or later.

This kind of things may not impact something as crucial as performance, so it's not top priority, I get it, but they impact the users and their development time IMO.

**Comment by JeffreySarnoff** [comment]
they are not official -- they exist to encourage something official, and to contribute to that
