### ISSUE TITLE
Cannot execute Linux 64-bit

### ISSUE THREAD

**Issue by kaism** [JuliaLang/julia#25202]
I downloaded the Julia 0.6.2 generic x86 Linux binary. I attempted to execute it on my system, OpenSuSE Leap 42.3 using both bash and zsh. In each case I get the errors,

bash: ./julia: cannot execute binary file: Exec format error

zsh: exec format error: ./julia

Julia 0.6 works just fine.

**Comment by ararslan** [comment]
Did you use the 32- or 64-bit generic x86 binary for Linux?

**Comment by kaism** [comment]
I used the 64 bit generic x86 binary.

**Comment by ararslan** [comment]
Okay. I've been using that binary on my Linux system (Ubuntu 16.04) without issue, but I don't have access to an OpenSUSE system. I'm not entirely sure what to suggest so I'll cc @staticfloat, maybe he has some ideas. In the meantime, can you provide the output of `objdump -p ./julia`?

**Comment by staticfloat** [comment]
What does `file julia` say?

**Comment by johnfgibson** [comment]
I've had no problems downloading and running the generic 0.6.2 binary on openSUSE Linux LEAP 42.3. That's what I run on my office desktop; on my laptop here at home I run openSUSE Tumbleweed, and it looks like this:

```
gibson@sophist$ head -1 /etc/issue
Welcome to openSUSE Tumbleweed 20180103  - Kernel \r (\l).
gibson@sophist$ uname -a
Linux sophist.math.unh.edu 4.14.9-1-default #1 SMP PREEMPT Mon Dec 25 15:42:48 UTC 2017 (9423ca2) x86_64 x86_64 x86_64 GNU/Linux
gibson@sophist$ wget https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.2-linux-x86_64.tar.gz
<output supressed>
gibson@sophist$ tar xfpz julia-0.6.2-linux-x86_64.tar.gz
gibson@sophist$ ls
julia-d386e40c17/
gibson@sophist$ ln -s julia-d386e40c17/ julia-0.6.2
gibson@sophist$ file ./julia-0.6.2/bin/julia
./julia-0.6.2/bin/julia: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, with debug_info, not stripped
gibson@sophist$ ./julia-0.6.2/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release                                                             
|__/                   |  x86_64-pc-linux-gnu                                                                                
                                                                                                                             
julia> 2+2
4
```

**Comment by johnfgibson** [comment]
The generic Linux binary for julia-0.6.2 works just fine for me on openSUSE Leap 42.3. I suspect you accidently downloaded the generic Linux binary for ARM, which is just below the x86 binary on https://julialang.org/downloads/. I tried that and replicated the error message you quote above. As @staticfloat suggest, you should run `file ./julia` or `file julia-d386e40c17/bin/julia` to double-check which binary architecture you've downloaded. 

This issue should be closed. Probably better to report problems like this to https://discourse.julialang.org/

Transcript: observe the `x86-64` in the first `file` output and the `ARM` in the second.
```
gibson@sophist$ file julia-d386e40c17/bin/julia
julia-d386e40c17/bin/julia: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, not stripped

gibson@sophist$ julia-d386e40c17/bin/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> iseven(4+7)
false

gibson@sophist$ file ARM/julia-d386e40c17/bin/julia

ARM/julia-d386e40c17/bin/julia: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, not stripped

gibson@sophist$ ARM/julia-d386e40c17/bin/julia
bash: ARM/julia-d386e40c17/bin/julia: cannot execute binary file: Exec format error
```
