### ISSUE TITLE
Larger octal literals produce smaller types, sometimes

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#25216]
```
julia> typeof(0o047)
UInt16

julia> typeof(0o134)
UInt8
```

This seems...wrong. These should either both be `UInt8` or both be `UInt16`. I think the bug is probably in the `sized-uint-oct-literal` function in [src/julia-parser.scm](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L436) but I'm having a hard time figuring out what the pertinent functions are supposed to do.

**Comment by KlausC** [comment]
I agree that it looks wrong, but maybe it is intended.
Currently, the type of the constant is determined this way:
If the first character after the `o` is a `0`, the number of octal digits in the constant determines the size of the type (function `sized-uint-literal`). In Julia syntax `length(s)-2)*3` gives the number of required bits.
In the other case, the smallest type, which can hold the actual value is chosen.
Unfortunately, this decision leads to a non-monotone behaviour.
If we change that to always account only for the number of digits, it would not be possible to define a constant of minimal type for a given value. E.g. `0o100` == `0x0040` would require 16 bits.
If we change it to only use the value alone, the leading `0` would be silently ignored and we have no way to create bigger type constants with small values. E.g. `0o0001` would become `0x01` with 8 bits.

**Comment by JeffBezanson** [comment]
> If the first character after the o is a 0, the number of octal digits in the constant determines the size of the type (function sized-uint-literal). In Julia syntax length(s)-2)*3 gives the number of required bits.
In the other case, the smallest type, which can hold the actual value is chosen.

Correct; it looks like this rule was deliberately implemented in a789828d92f106fa92a8e7dfd14a0667dcac0fe9.

**Comment by iamed2** [comment]
> it would not be possible to define a constant of minimal type for a given value

What is the use case for this?

**Comment by KlausC** [comment]
Probably there aren't many use cases for octal constants at all, nowadays. The comments in the referred commit do not help much.
 I could imagine an old-fashioned programmer, knowing the octal encodings of all ASCII characters by heart, who wants to code `String([0o150, 0o145, 0o154, 0o154, 0o157])`. A change would be breaking in this case.

**Comment by StefanKarpinski** [comment]
https://discourse.julialang.org/t/is-julia-suitable-for-the-development-of-proprietary-derived-softwares/7912

**Comment by StefanKarpinski** [comment]
https://discourse.julialang.org/t/solution-for-issue-25216-larger-octal-literals-produce-smaller-types-sometimes/7918
