### ISSUE TITLE
Add special printing for length method error

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#25232]
A common mistake for people adding new iterators of unkown length is that they don't define the iterator type trait, so if they call things like `isempty` they get a `length` MethodError. We should add some logic in the error printing to hint that the user may wish to change the iterator trait.

**Comment by firedranzer** [comment]
@Keno I want to take this issue. Please guide me with the required files and corrections. I am new to this organisation.

**Comment by Keno** [comment]
You need to add a new special case to [this function](https://github.com/JuliaLang/julia/blob/1238bad60fc7d3b5984fbf25423d60159147462c/base/replutil.jl#L310) that catches cases like this:

```
struct Foo; end
start(::Foo) = false
next(::Foo, s) = (x = rand(); (x, x < 0.2))
done(::Foo, s) = s
```
```
ERROR: MethodError: no method matching length(::Foo)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:544
  length(::Base.MethodList) at reflection.jl:670
  length(::MethodTable) at reflection.jl:745
  ...
Stacktrace:
 [1] _similar_for(::UnitRange{Int64}, ::Type, ::Foo, ::Base.HasLength) at ./array.jl:446
 [2] _collect at ./array.jl:476 [inlined]
 [3] collect(::Foo) at ./array.jl:470
 [4] top-level scope
```
and gives an appropriate error message about implementing `Base.iteratorsize`.

**Comment by ArunSanganal** [comment]
I want to take upon this issue. I am new to Open Source and Julia. Please guide me through the same.

**Comment by pranavmkoundinya** [comment]
If this issue is still open, I would like to take it up. Can u please walk me through the steps I must carry out?

**Comment by vtjnash** [comment]
updated example:```
julia> struct Foo; end
julia> iterate(::Foo) = nothing
```
