### ISSUE TITLE
Type parameter corrupted when matching

### ISSUE THREAD

**Issue by alyst** [JuliaLang/julia#25240]
This should be the more confined example of the bug that hit quinnj/WeakRefStrings.jl#20 on Julia nightly (Julia 0.7.0-DEV.3018):

```julia
julia> foo(A::Array{T}) where {T} = @show T eltype(A)
foo (generic function with 1 method)

julia> bar(A::Array{T}) where {T <: Union{Integer, Missing}} = @show T eltype(A)
bar (generic function with 1 method)

julia> bar2(A::Array{T}) where {T <: Union{Int, Missing}} = @show T eltype(A)
bar2 (generic function with 1 method)

julia> foo([1, missing])
T = Union{Missing, Int64}
eltype(A) = Union{Missing, Int64}
Union{Missing, Int64}

julia> bar([1, missing])
T = Int64
eltype(A) = Union{Missing, Int64}
Union{Missing, Int64}

julia> bar2([1, missing])
T = Union{Missing, Int64}
eltype(A) = Union{Missing, Int64}
Union{Missing, Int64}
```

For some reason `T===Int` instead of `T=Union{Int, Missing}` inside `bar()`.

**Comment by nalimilan** [comment]
Sounds similar to the bug signalled at https://github.com/JuliaLang/julia/pull/24653#discussion_r151874283, which has a `@test_broken` call.

**Comment by alyst** [comment]
Actually, if `Missing` is replaced with `Float64` and the functions are called like `foo(Union{Int, Float64}[1, 1.5])` the bug is still there.
