### ISSUE TITLE
Initialize Julia v0.6.2 behind a proxy 

### ISSUE THREAD

**Issue by pol31** [JuliaLang/julia#25245]
Hi,

I try to initialize Julia v0.6.2 behind a corporate Proxy. The error message is:
```
$ > julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.init()
INFO: Initializing package repository /users/l0476057/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ECERTIFICATE, Class:SSL, SSL error: ffffd900[8] - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed)
Stacktrace:
 [1] macro expansion at ./libgit2/error.jl:99 [inlined]
 [2] clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:276
 [3] #clone#100(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:562
 [4] (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 [5] (::Base.Pkg.Dir.##8#10{String,String})() at ./pkg/dir.jl:55
 [6] cd(::Base.Pkg.Dir.##8#10{String,String}, ::String) at ./file.jl:70
 [7] init(::String, ::String) at ./pkg/dir.jl:53
 [8] init() at ./pkg/pkg.jl:85
```

I have initialized ~/.gitconfig with `git config --global https.proxy <proxy:port>`,  `git config --global http.sslVerify "false"`, `git config --global http.proxy <proxy:port>`, `git config --global http.sslVerify "false"` and `git config --global url."git://".insteadOf https://"`. Also I have configured environment variables in the shell.

Outside env Julia, `git clone"https://github.com/JuliaLang/METADATA.jl"` command works. 
```
$ > git clone "https://github.com/JuliaLang/METADATA.jl"
Initialized empty Git repository in /julia/METADATA.jl/.git/
remote: Counting objects: 118884, done.
remote: Compressing objects: 100% (349/349), done.
remote: Total 118884 (delta 233), reused 103 (delta 88), pack-reused 118444
Receiving objects: 100% (118884/118884), 21.69 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (24790/24790), done.
```

I thinks this subject is linked to these issues https://github.com/JuliaLang/julia/issues/14167 or https://github.com/JuliaLang/julia/issues/15128.

I think I must just change the Libgit2 configuration but I don't know how ? Any ideas ?

Thanks,

Paul

**Comment by ViralBShah** [comment]
I thought we build libgit2 with libcurl. Thus proxy settings need to be set up using curl variables. But I can never get this stuff straight.

**Comment by sparrowhawker** [comment]
I have exactly the same situation with Pkg.update(). I can clone using git, but not add from within Julia

This has suddenly made julia unusable behind the office firewall :(

**Comment by ViralBShah** [comment]
At this point, the focus is to get all these things working in 0.7 with Pkg3.

**Comment by KristofferC** [comment]
The way Pkg3 downloads the registry is very similar to Pkg2 though.

**Comment by triceraflops** [comment]
Does anyone know the status of this? I'm having the same problem.

After a little looking around, I see a few people with the same problem. If no one else is working on a fix (and I get some free time) I might be able to help out.

**Comment by StefanKarpinski** [comment]
No one is working on it as far as I can tell. @triceraflops is a great user name, by the way 😁

**Comment by triceraflops** [comment]
@pol31 

Could you try again and let us know the result.

What version of Windows are you running?

First make sure you've got the latest version of [powershell ](https://www.microsoft.com/en-us/download/details.aspx?id=54616 ), plus [this security update](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in).

**Comment by KristofferC** [comment]
Outdated with move to new package manager. Please report to https://github.com/JuliaLang/Pkg.jl for further issues.
