### ISSUE TITLE
Old method incorrectly called after redefining it

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25252]
I've experienced a weird bug when working on https://github.com/JuliaLang/julia/pull/16401. When debugging the `hash(::AbstractArray, ::UInt)` method, I repeatedly pasted it in the REPL and called `hash(::AbstractArray)`. It turns out that under some circumstances, the redefinition has no effect: the old method is still used.

I've been able to reproduce the problem with relatively simple steps:
1. start REPL in the Julia source directory and call `import Base: hash, hash_range, TypeRangeStep, RangeStepRegular, hashaa_seed, hashr_seed, hashrle_seed`
2. copy [these lines](https://github.com/JuliaLang/julia/blob/6c94bd84a275b96e4f7d8d77d1563561978b686c/base/abstractarray.jl#L1959-L2046) to the REPL after adding a statement like `println(1)` at the top of the function
3. call `hash([1])` and check that it prints `1`
4. run `using Test; include("test/hashing.jl")`
5. copy the lines from step 2 after increasing the value in the `println` call
6. call `hash([1])` and observe that it still prints `1`

If you skip step 4, the call in the last step prints `2` as expected.

**Comment by StefanKarpinski** [comment]
cc @vtjnash

**Comment by timholy** [comment]
I've seen something like this before too but never tracked down a reproducer. Awesome work, @nalimilan.

**Comment by nalimilan** [comment]
Yeah, when I started to have serious doubts about the fact that I wasn't just mad, but that something weird was going on, I thought it was probably worth reporting, since it's not that common to be able to reproduce this kind of thing. The fact that I identified the problem is an indication of the hard time I had getting the hashing algorithm to work (and of my lazy trial-and-error approach :-p).

**Comment by KristofferC** [comment]
This doesn't repro anymore and a lot of things have changed since the issue opened. Please reopen if this can be reproduced some other way.
