### ISSUE TITLE
Multiplication Error

### ISSUE THREAD

**Issue by dciwalsh** [JuliaLang/julia#25269]
I'm running Julia on my Macbook Air, installed via home-brew, and I've noticed this multiplication error:

julia> 3 * 0.1
0.30000000000000004

Is this a common problem or is my setup weird?

My version info is:

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

**Comment by Sacha0** [comment]
Welcome @dciwalsh! You might find [the Wikipedia article on floating point arithmetic enlightening](https://en.wikipedia.org/wiki/Floating-point_arithmetic). In the future, please post questions to the discourse forums :). Best!
