### ISSUE TITLE
Avoid name clash on Types and Modules with same name

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/julia#25262]
Repeat of Discourse Post:

+ [Way to be explicit with different objects sharing the same name?](https://discourse.julialang.org/t/way-to-be-explicit-with-different-objects-sharing-the-same-name/7961)

-------

From Post:

> Let's say you have a module in a package called `IO` (obviously not preferable):
> 
> ```
> module IO
>  custom_input_output_stuff = true
> end
> ```
> 
> The problem now is that the module `IO` will clobber the Base `IO` type in calls.
> 
> ------
> 
> This leads to the following errors:
> 
> ```
> > foo(bar::IO) = "nope, chuck testa"
> ERROR: ArgumentError: invalid type for argument bar in method definition for foo at REPL[10]:100:
> 
> > struct Fizz ; buzz::IO ; end 
> ERROR: TypeError: Fizz: in type definition, expected Type, got Module
> ```
> 
> -----
> 
> How do you tell the package to use `Base's IO` when a type is expected?
> 
> *edit: tangentially related to https://discourse.julialang.org/t/julia-reserved-key-words/4781*

**Comment by vchuravy** [comment]
Please do not double post. Especially not within an hour of each other.

**Comment by djsegal** [comment]
That's valid. And I won't do it again.

But on discourse you said it is not currently possible and might be a nice feature.

Wouldn't a github issue then be the logical move?

------

Also, is there a way to remove discourse posts? sometimes you:
+ post a question
+ do some research
+ then realize it's not possible in the current environment
+ then post an issue

// closing this issue makes it appear like this is a solved issue
