### ISSUE TITLE
Add way to get module of variable from an UndefVarError

### ISSUE THREAD

**Issue by djsegal** [JuliaLang/julia#25263]
Repeat of Discourse Post:

+ [Way to get module of undef variable?](https://discourse.julialang.org/t/way-to-get-module-of-undef-variable/7931)

-------

From Post:

> If you do:
> 
> ```
> cur_error = nothing 
> 
> try 
>   foo(bar::Main.baz) = "Rambo"
> catch tmp_error
>   cur_error = tmp_error
> end
> ```
> 
> which gives
> 
> ```
> > cur_error
> UndefVarError(:baz)
> 
> > cur_error.var
> :baz
> ```
> 
> -----
> 
> The thing I'm kind of curious about is if there is a way to get the module that should have `:baz` in it (i.e. `Main`)?

**Comment by vchuravy** [comment]
Again please do not double post. Discourse is meant for questions like this and by double posting you are sending everyone two emails.

**Comment by vtjnash** [comment]
I agree - don’t double post. But this one seems like a good idea, and probably not bad as a first PR.

**Comment by djsegal** [comment]
Won't double post in the future.

The reason for this one though is because:
+ it didn't get traction on Discourse
+ then i realized it's probably because it would have to be implemented.

Is that not a correct workflow?

(i.e. avoid making issues on github as long as possible. but do so once you realize it's the place to go?)

**Comment by djsegal** [comment]
Also @vtjnash, what spec should I build this under?

Do you add a `:mod` field to `UndefVarError` that stores a symbol representation of the module?

// or do you just store the module object directly?

**Comment by vtjnash** [comment]
> it didn't get traction on Discourse

Also probably just slow for the holidays. This could have been opened straight as a feature request on github. Posting an update on Discourse to say that you had turned it into an issue would also be good (to try to avoid splitting any discussion, and avoid the appearance of double posting).

I recommend just storing the Module reference directly in a new field (and leave it uninitialized for local variables - or better yet store the Method)

**Comment by JeffBezanson** [comment]
> avoid making issues on github as long as possible

+1 to what vtjnash said, and I'll add that I mostly read github issues so I'm more likely to see things here. I will never tell anybody not to open a github issue --- if an issue is inappropriate for whatever reason it is very quick and easy to close one.
