### ISSUE TITLE
Potential problems with triangular matrix-vector multiplication

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#25266]
There is a (recently kluge-patched) bug in OpenBLAS (issue [here](https://github.com/xianyi/OpenBLAS/issues/1332))  for `xTRMV`, which apparently applies to the version included in the normal Julia build.  (I verified relevance by linking a version of the Fortran code mentioned in the OpenBLAS issue to the DLL from Julia.)

Interestingly, I haven't yet been able to provoke the bug from Julia (I am using v0.6.2).  However, I haven't found any reason preventing it from affecting us. It smells like a threading race problem, so it may be hard to test.

**Comment by andreasnoack** [comment]
Thanks for letting us know. I've also unsuccessfully tried to replicate this in Julia. We can probably close this when we bump the version of OpenBLAS.
