### ISSUE TITLE
bug in Ranges code / tests

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#25286]
https://travis-ci.org/JuliaLang/julia/jobs/322299046#L2743

The global RNG seed was 0x9f3eab042ace5a84ce808fe88cd020d3.
Error in testset ranges:
Test Failed at /tmp/julia/share/julia/test/ranges.jl:159
  Expression: cmp_sn2(Tw(xw / yw), astuple(x / y)..., slopbits)

**Comment by StefanKarpinski** [comment]
cc @nalimilan, @rfourquet

**Comment by vtjnash** [comment]
Is this new? Just happened on HEAD too https://circleci.com/gh/JuliaLang/julia/13506?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by rfourquet** [comment]
I saw it [4 days ago](https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.22744/job/aw5scwanriorw3bq) too. I've no idea what this test does, but it occurs at iteration `i=14919` for the seed given in the OP. In case this could help, the two random values are then equal to `(0.7127141735154066, 0.35635710631367434)`, with the 2nd one being almost the half of the first one.

**Comment by vtjnash** [comment]
Happened again twice today, if that helps at all:
https://travis-ci.org/JuliaLang/julia/jobs/324701948
https://ci.appveyor.com/project/JuliaLang/julia/branch/master/job/2xaj1of76cw5l7mr
