### ISSUE TITLE
Homepage screenshot with code that does not run

### ISSUE THREAD

**Issue by Dmitrii-I** [JuliaLang/julia#25299]
On https://julialang.org/ there is a screenshot https://julialang.org/images/ijulia.png containing code

```
using RDatasets
using Gadfly
set_default_plot_size(9inch, 9inch/golden)
plot(data("datasets", "iris"), x="Sepal.Width", y="Sepal.Length", color="Species")
```

Running this code in 0.6.2 results in error:

```
MethodError: no method matching data(::String, ::String)

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522
```

**Comment by KristofferC** [comment]
I would argue this whole section on the home page should be removed.

**Comment by StefanKarpinski** [comment]
We need a full overhaul of the website for the 1.0 release.

**Comment by JeffBezanson** [comment]
Thank you for pointing this out. Should be filed at https://github.com/JuliaLang/julialang.github.com
