### ISSUE TITLE
python micro perf test - printfd does not mimic other languages tests

### ISSUE THREAD

**Issue by ColemanTom** [JuliaLang/julia#25291]
Hi,

I noticed that the printfd perf/micro test for python does not mimic the behaviour of the other language versions. It is not doing any string substituion, and is in fact just printing `%d %d\n`.
Compare (python): https://github.com/JuliaLang/julia/blob/master/test/perf/micro/perf.py#L108
Against (c): https://github.com/JuliaLang/julia/blob/master/test/perf/micro/perf.c#L226

I believe the line should be `f.write("%d %d\n" % (i, i))` but I have not done any performance comparison to check if that is the fastest approach. This difference will make the python tests run slower for this case.

**Comment by StefanKarpinski** [comment]
cc @johnfgibson, this appears to have been introduced in https://github.com/JuliaLang/julia/pull/23922.

**Comment by johnfgibson** [comment]
Indeed that looks wrong. I'll fix that up when I return to work after New Year's. Thanks for spotting this @ColemanTom.
