### ISSUE TITLE
Consider bundling an up-to-date libz

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#25295]
Julia loads libz upon initialization, because of dependencies (e.g., libgit2). Currently this links to whatever is on the system path.

This is problematic for packages, which may need recent libz capabilities. Poster child is the PyPlot package; Issue [here](https://github.com/JuliaPy/PyPlot.jl/issues/151). This is becoming a FAQ for PyPlot, and the users are not happy with the current resolution.

An up-to-date version would fix this. I should add that the libz developers are more careful about backwards compatibility than any project I know of, so it's hard to see a downside.

**Comment by v-i-s-h** [comment]
+1

**Comment by evetion** [comment]
+1 
We're also running into this visr/GDAL.jl#42. 

The workaround (LD_PRELOAD / LD_LIBRARY_PATH) is platform specific and requires user intervention. Other options (compiling external libraries against an older libz or explicitely requiring older versions of external packages) require a lot of extra work and are in my opinion bad practices.

**Comment by JeffBezanson** [comment]
Seems important but not really breaking. Tentatively marking 1.0.x.

**Comment by vtjnash** [comment]
ref #8186 (when it was deleted) and 0d5af2c867a (when it was disabled)

**Comment by visr** [comment]
We could possibly use [ZlibBuilder](https://github.com/staticfloat/ZlibBuilder) and add it to the list at #26640.

**Comment by ViralBShah** [comment]
What exactly still needs to be done here?

**Comment by visr** [comment]
I believe this can be closed, since the libz dependency was removed altogether in #26888.
