### ISSUE TITLE
AbstractChar type

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#25302]
As was [briefly discussed last month](https://github.com/JuliaLang/julia/pull/24439#issuecomment-346880932), it would be nice to have `Char <: AbstractChar`, and to have Base functions take `AbstractChar` arguments where appropriate.

I think this can be added in 1.1 since it would not be breaking?

**Comment by StefanKarpinski** [comment]
It is non-breaking. I may get around to adding this during the alpha period (since it's non-breaking, that should hopefully be ok), since it would be nice to support non-UTF-8 encodings without requiring transcoding to `Char`.

**Comment by Keno** [comment]
I have most of a branch of this because I wanted to make sure there was nothing breaking required, but once I got to that point, I stopped shorting of cleaning up, writing tests, documenting, etc.

**Comment by StefanKarpinski** [comment]
Would be good to have a PR in case anyone wants to do the rest.

**Comment by stevengj** [comment]
Bump @Keno.

**Comment by stevengj** [comment]
I'll have a PR shortly.
