### ISSUE TITLE
Corner cases with `std` and `var` using Rational

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#25300]
When using `Real`s which are not floating-point numbers we can see some corner cases when using `var` and `std`:
```julia
julia> var([1//1, 1//2])  # Returns a `Rational{Int}`
1//8

julia> std([1//1, 1//2])  # Returns a float (since `sqrt` ends up calling `float`)
0.3535533905932738

julia> var([1//1])  # Due to `Rational{Int}(NaN)` call
ERROR: DivideError: integer division error
Stacktrace:
 [1] //(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:51
 [2] #varm#533(::Bool, ::Function, ::Array{Rational{Int64},1}, ::Rational{Int64}) at ./statistics.jl:153
 [3] (::Base.#kw##varm)(::Array{Any,1}, ::Base.#varm, ::Array{Rational{Int64},1}, ::Rational{Int64}) at ./<missing>:0
 [4] #var#536(::Bool, ::Void, ::Function, ::Array{Rational{Int64},1}) at ./statistics.jl:184
 [5] var(::Array{Rational{Int64},1}) at ./statistics.jl:184

julia> std([1//1])
ERROR: DivideError: integer division error
Stacktrace:
 [1] //(::Rational{Int64}, ::Rational{Int64}) at ./rational.jl:51
 [2] #varm#533(::Bool, ::Function, ::Array{Rational{Int64},1}, ::Rational{Int64}) at ./statistics.jl:153
 [3] (::Base.#kw##varm)(::Array{Any,1}, ::Base.#varm, ::Array{Rational{Int64},1}, ::Rational{Int64}) at ./<missing>:0
 [4] #var#536(::Bool, ::Void, ::Function, ::Array{Rational{Int64},1}) at ./statistics.jl:184
 [5] (::Base.#kw##var)(::Array{Any,1}, ::Base.#var, ::Array{Rational{Int64},1}) at ./<missing>:0
 [6] std(::Array{Rational{Int64},1}) at ./statistics.jl:246
```

We may want to switch `var` to always return a `float` similarly to `std` such that we can always return a `NaN`.

Alternatively we may want to introduce a check in `std` such that `length(A) <= Int(corrected) && return NaN`. This would at the very least allow for `std` to avoid the exception.

**Comment by omus** [comment]
cc: @TotalVerb

**Comment by omus** [comment]
Originally noticed with `FixedDecimal` values: https://github.com/JuliaMath/FixedPointDecimals.jl/pull/19

**Comment by omus** [comment]
Some more type stability issues:
```julia
julia> std([1//1, 1//2])
0.3535533905932738

julia> std([1//1, 1//2], 1)
1-element Array{Rational{Int64},1}:
 6369051672525773//18014398509481984
```

**Comment by andreasnoack** [comment]
Except for
```julia
julia> std([1//1, 1//2], 1)
1-element Array{Rational{Int64},1}:
 6369051672525773//18014398509481984
```
which is due to an unfortunate conversion of a `Float64` to a `Rational{Int}`, I don't see the problem here. `var` is a rational operation so promotion is not necessary but it has the consequence that it throws an exception instead of a `NaN`. Why not convert the input to floats if you want floating point behavior?

**Comment by omus** [comment]
> Why not convert the input to floats if you want floating point behavior?

Currently that is a reasonable work around.

**Comment by omus** [comment]
At this point I'm uncertain as to what a good solution to this problem is. We should definitely address the different types which are being returned. I don't think we want to support a representation of `NaN` as a `Rational`.

 I think possibly we may want to make `Rational{T}(NaN)` a `DomainError` as a first step.

**Comment by andreasnoack** [comment]
> We should definitely address the different types which are being returned.

Which methods and types are you referring to here? I don't see any type stability issues in the examples.

**Comment by omus** [comment]
> Which methods and types are you referring to here? I don't see any type stability issues in the examples.

For Julia 0.7 I don't think there are type stability problems (there was some in 0.6). I was specifically referring to the `eltype` different between:
```julia
eltype(std([1//1, 1//2]))::Float64
eltype(std([1//1, 1//2], 1))::Rational{Int}
```

**Comment by andreasnoack** [comment]
@omus What is left here after https://github.com/JuliaLang/julia/pull/25304 has been merged?

**Comment by omus** [comment]
I'd like to look into either improving the error message for `std([1//1])` or either adding in some logic to make these return `NaN` instead of throwing an error.

**Comment by martinholters** [comment]
I vaguely remember a discussion about NaN vs. throwing where the consensus was to generally prefer throwing an error unless that means introducing additional checks because the machine instructions naturally produce a NaN.

**Comment by omus** [comment]
I finally had some time to look into improving `std([1//1])`. I'm not happy with any of changes I've made so far so I think the status quo is the way to go.
