### ISSUE TITLE
Pkg.build() fails with space in path name on macOS 10.13.2

### ISSUE THREAD

**Issue by essandess** [JuliaLang/julia#25325]
Calling `Pkg.build` fails in a home directory with a space in the POSIX path name.

```
$ echo $HOME
/Volumes/Macintosh HD/Users/username
```

```
julia> Pkg.build("IJulia")
INFO: Building Conda
INFO: Building Homebrew
Already up-to-date.
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
INFO: Downloading miniconda installer ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.2M  100 29.2M    0     0  14.6M      0  0:00:02  0:00:02 --:--:-- 12.6M
INFO: Installing miniconda ...
ERROR: did not recognize option 'HD/Users/username/.julia/v0.4/Conda/deps/usr', please try -h
```

The fix should be easy enough. Any quick fixes would also be appreciated.

**Comment by StefanKarpinski** [comment]
This seems to be a miniconda bug, not a Julia bug.

**Comment by essandess** [comment]
> This seems to be a miniconda bug, not a Julia bug.

Perhaps, or it could be in Julia’s `Pkg.build` call to miniconda. Not sure. I’d be happy to upstream this if I understood the details better.

**Comment by StefanKarpinski** [comment]
In any case, the issue should go on the [Conda.jl package](https://github.com/JuliaPy/Conda.jl), not the Julia language repo.

**Comment by essandess** [comment]
@StefanKarpinski Thank you. Cross reference [link](https://github.com/JuliaPy/Conda.jl/issues/98).
