### ISSUE TITLE
union of tuples is broken

### ISSUE THREAD

**Issue by ajkeller34** [JuliaLang/julia#25338]
On 0.6.2:
```
julia> union((1,2))
2-element Array{Int64,1}:
 1
 2
```

0.7.0-DEV.3222:
```
julia> union((1,2))
ERROR: MethodError: no method matching emptymutable(::Tuple{Int64,Int64}, ::Type{Int64})
...
```

You can try to take the union of multiple tuples (e.g. `union((1,2), (3,))`) and that doesn't work either. I haven't bisected to be sure, but this broke quite recently so I think #23528 is responsible.

cc @rfourquet

**Comment by rfourquet** [comment]
Thanks for reporting! `emptymutable` was meant to have a default fall-back, but I forgot about it and no test caught this.
