### ISSUE TITLE
nested broadcast should evaluate non-broadcasted part once

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#25340]
MWE following [discussion](https://discourse.julialang.org/t/why-are-there-broadcast-versions-of-functions/4708):
```julia
struct Bar
    data
    Bar(data) = (println("expensive"); new(data))
end
(B::Bar)(x) = B.data * x
Bar(2).([1,2,3])                  # Bar(2) will be only evaluated once
broadcast(sqrt, Bar(2).([1,2,3])) # Bar(2) will also be evaluated once
sqrt.(Bar(2).([1,2,3]))           # Bar(2) will be evaluated three times
```

**Comment by nalimilan** [comment]
Making for triage as changing this to evaluate `Bar(2)` only once is technically breaking, though probably few packages rely on it (so it could be fixed after the alpha).

**Comment by StefanKarpinski** [comment]
This would be good, but it seems like some effort. I would propose documenting that this may change and then changing it in 1.x at some point. As already noted, it's unlikely that people are relying on this.

**Comment by vtjnash** [comment]
Should be fixed by https://github.com/JuliaLang/julia/pull/23692#issuecomment-329212286, although Jeff doesn't consider this a bug, so it can get changed anytime

**Comment by JeffBezanson** [comment]
In these kinds of functional programming contexts it's not a good idea to depend on side effects happening in a particular way. For example, does `map` on a sparse matrix call the function again for every non-stored zero?

Yes, I consider this mostly undefined behavior, so it's fine to change it as well.
