### ISSUE TITLE
slight inaccuracy in findn docstring

### ISSUE THREAD

**Issue by Benoit9** [JuliaLang/julia#25343]
https://github.com/JuliaLang/julia/blob/ebc24938e112f113db9876c296141fb157c564a1/base/array.jl#L1810

Instead of :

> If there are no non-zero elements of `A`, return a 2-tuple of empty arrays.

It should read:

> If there are no non-zero elements of `A`, return a tuple of empty arrays.

**Comment by fredrikekre** [comment]
But it does return a 2-tuple of empty arrays?

**Comment by Benoit9** [comment]
It returns an n-tuple where n is the number of dimensions of the array.
