### ISSUE TITLE
Propagate parameter constraints to derived UnionAlls

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#25361]
Very close to #9441 (open), #6721 (closed), and several related issues.

```julia
julia> struct Thing{A<:AbstractUnitRange,B} end

julia> const ThingInt{A} = Thing{A,Int}
Thing{A,Int64} where A

julia> ThingInt <: Thing
false

julia> ThingInt{<:AbstractUnitRange} <: Thing
true
```
yet
```julia
julia> ThingInt{Float64}
ERROR: TypeError: in Thing, in A, expected A<:AbstractUnitRange, got Type{Float64}
```

Where this seems like it could be slightly tricky is something like this:
```julia
julia> struct DimsThing{Dims<:Tuple{Vararg{Int}},B} end

julia> const DimsInt{N} = DimsThing{<:NTuple{N},Int}
DimsThing{#s1,Int64} where #s1<:(Tuple{Vararg{T,N}} where T) where N

julia> DimsInt <: DimsThing
false
```
However, this too seems pretty easily solved by computing the type intersection of the RHS with the constraints in the type definition.

**Comment by JeffBezanson** [comment]
Basically a dup of #6383 I think.

**Comment by timholy** [comment]
Yeah, it's the same. I'll close this and link here, since this is a pretty easy test case. Thanks for finding that.
