### ISSUE TITLE
`nfields` works for AbstractTypes but `fieldcount` does not

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/julia#25389]
![Screen Shot 2018-01-04 at 6.11.26 AM.png](https://user-images.githubusercontent.com/1813121/34565093-c39eda04-f116-11e7-8ac6-498fa7e12af1.png)

**Comment by yuyichao** [comment]
This is expected. The answer `nfields` give is wrong. https://github.com/JuliaLang/julia/pull/22350

**Comment by JeffBezanson** [comment]
Yes, this is why there's a deprecation. In the future `nfields(x)` will give the number of fields in the object `x`, which should work for all objects, and `fieldcount(type)` tries to determine the number of fields that an instance of the given type would have.

**Comment by kdheepak** [comment]
Thanks! I did look for other issues with `fieldcount` / `nfields` but must have missed that one.
