### ISSUE TITLE
Infinite loop with miniconda installation on julia 0.6.2 for Windows 10

### ISSUE THREAD

**Issue by dpriego87** [JuliaLang/julia#25399]
I can't install PyCall package on Julia 0.6.2 for Windows 10.

It only gives me an infinite loop trying to install miniconda:
`julia> Pkg.add("PyCall")
INFO: Installing PyCall v1.15.0
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...
INFO: Downloading miniconda installer ...
INFO: Installing miniconda ...`

This is my versioninfo output:

`julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

`

**Comment by ararslan** [comment]
Hi there! The appropriate place to report issues with packages is the individual package repositories. In this case the problem seems to be with Conda, so you should open an issue on [the Conda package repo](https://github.com/JuliaPy/Conda.jl).
