### ISSUE TITLE
libwhich not able to find libmkt_rt.so

### ISSUE THREAD

**Issue by JonathanAnderson** [JuliaLang/julia#25400]
I’ve been having an issue building master from source for the last few days…

My Make.user

```
override MARCH=core-avx2

CXXFLAGS=-std=c++17
LDFLAGS=-lstdc++

CMAKE=/usr/bin/cmake3

USE_INTEL_MKL=1
USE_INTEL_MKL_FFT=1
USE_BLAS64=1
MKLROOT=/gpfs/tcs3/users/janders/usr/vendor/packages/mkl/install
```

I’m failing when it tries to start making base.

I built single threaded and put the whole log as a gist here: https://gist.github.com/JonathanAnderson/2730569c0edf5d65d70dc1e1b8f79bc0

When i run libwhich manually
```
cd base
/gpfs/tcs3/users/janders/root/usr/install/julia/julia_latest/usr/tools/libwhich -p libmkl_rt.so

failed to open library: libmkl_rt.so: cannot open shared object file: No such file or directory
```

if i copy the file into the base directory is also fails

 ```
cp "${MKLROOT}/install/lib/intel64/libmkl_rt.so" base
cd base
/gpfs/tcs3/users/janders/root/usr/install/julia/julia_latest/usr/tools/libwhich -p libmkl_rt.so

failed to open library: libmkl_rt.so: cannot open shared object file: No such file or directory
```

but if I put a `./` before libmkt_rt.so...

 ```
cd base
/gpfs/tcs3/users/janders/root/usr/install/julia/julia_latest/usr/tools/libwhich -p ./libmkl_rt.so

./libmkl_rt.so
```

then lib which runs.

So now, that I've manually copied over `libmkl_rt.so` into `base` and if apply the following patch

```
diff --git a/base/Makefile b/base/Makefile
index 664467d..31d42d7 100644
--- a/base/Makefile
+++ b/base/Makefile
@@ -150,7 +150,7 @@ endif
 define symlink_system_library
 symlink_$1: $$(build_private_libdir)/$1.$$(SHLIB_EXT)
 $$(build_private_libdir)/$1.$$(SHLIB_EXT):
-       REALPATH=`$$(call spawn,$$(build_depsbindir)/libwhich) -p $$(notdir $$@)` && \
+       REALPATH=`$$(call spawn,$$(build_depsbindir)/libwhich) -p ./$$(notdir $$@)` && \
        $$(call resolve_path,REALPATH) && \
        [ -e "$$$$REALPATH" ] && \
        ([ ! -e "$$@" ] || rm "$$@") && \
```

Then my build will complete successfully.

I would normally try to add a PR, but I dont know Makefile syntax very well. Hopefully this helps someone else figure out what to do.

@ararslan @vtjnash might have some idea whats going on since they saw this on slack.

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/15133
