### ISSUE TITLE
`@edit a[1]` no longer works

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#25474]
`@edit a[1] = 1` still works. Seems to be because of:

```
julia> Meta.lower(@__MODULE__, :(a[1] = 1))
:(begin
      setindex!(a, 1, 1)
      return 1
  end)

julia> Meta.lower(@__MODULE__, :(a[1])) # Wat
:($(Expr(:thunk, CodeInfo(:(begin
      SSAValue(0) = getindex(a, 1)
      return SSAValue(0)
  end)))))
```

**Comment by JeffBezanson** [comment]
Calling `lower` is probably no longer a good idea here. Note that the setindex case works because the code for `@edit` painstakingly looks for that exact result from `lower`. I think it will be easier to manually write cases for syntax forms like these that have a (theoretically) simple correspondence with function calls.

**Comment by KristofferC** [comment]
FWIW, I think it has been there since the feature originally got introduced, 5 years ago: https://github.com/JuliaLang/julia/commit/85fdc92007223ebe6b55c27ea5c0e113ed3d7567

**Comment by vtjnash** [comment]
I think we could still call `Meta.lower`, but then scan the results looking for 1. the `call` argument to `return` (following SSAValues) 2. that all other operations are in some whitelist (conditionals, variables, calls, constants, labels, metadata, etc.)

**Comment by tkoolen** [comment]
In similar vein, `@edit [3]`, `@edit [3 4]`, and `@edit [3; 4]` are broken.

Is there a way to be sure that all of such cases are handled? https://github.com/JuliaLang/julia/pull/28122 is great, but I'm afraid this is a game of whack-a-mole.

Also, I have a package that was relying on `expand` (now `Meta.lower`, but the output is vastly different) to avoid having special cases for all of these. Could this be reinstated in some form or another?

**Comment by JeffBezanson** [comment]
Some of these are fixed but `setindex!` is still broken.
