### ISSUE TITLE
Custom output for tests that use  `contains`, `endswith`, `startswith`, and `match`

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#25486]
Tests for comparisons triggers special outputting that inserts the value of variables

```
julia> Base.Test.@test a==25
Test Failed
  Expression: a == 25
   Evaluated: 51 == 25
ERROR: There was an error during testing
```

The common similar case for strings is `contains`, `endswith`, `startswith`, and `match`.

```
julia> a = "hello world"
"hello world"

julia> Base.Test.@test contains(a, "good bye")
Test Failed
  Expression: contains(a, "good bye")
ERROR: There was an error during testing
```

It would be good if these tests received the same special treatment.

**Comment by jw3126** [comment]
One possibility is to show the arguments of any test that consists of a `:call`. Its implemented like that in [ArgCheck.jl](https://github.com/jw3126/ArgCheck.jl).
```julia
julia> Pkg.add("ArgCheck"); using ArgCheck
INFO: Package ArgCheck is already installed
INFO: METADATA is out-of-date — you may not have the latest version of ArgCheck
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> x=1; y=2; f(args...) = false
f (generic function with 2 methods)

julia> @argcheck f(x,y,9)
ERROR: ArgumentError: f(x, y) must hold. Got
x => 1
y => 2

**Comment by omus** [comment]
#30721 addresses this for `occursin` (replacement for `contains`), `startswith` and `endswith`. I'm not sure what the `match` request was about as that doesn't return a `Bool`

**Comment by oxinabox** [comment]
The `match` one probably should have been `ismatch`.

Do you think that is worth openning a new issue for?

**Comment by omus** [comment]
`ismatch` was deprecated in favor of `occursin` in Julia 0.7 so no issue needed.
