### ISSUE TITLE
accumulate(op, v0, x) fails on arrays of non-numeric types

### ISSUE THREAD

**Issue by chfin** [JuliaLang/julia#25506]
The following produces an error:

```julia
julia> accumulate((acc, x) -> acc+x[1], 0, [(1,2), (3,4), (5,6)])
ERROR: MethodError: no method matching rcum_promote_type(::##1#2, ::Type{Int64}, ::Type{Tuple{Int64,Int64}})
Closest candidates are:
  rcum_promote_type(::Any, ::Type{T<:Number}) where T<:Number at multidimensional.jl:585
  rcum_promote_type(::Any, ::Type{T}) where T at multidimensional.jl:586
  rcum_promote_type(::Any, ::Type{T}, !Matched::Type{S<:Number}) where {T, S<:Number} at multidimensional.jl:584
  ...
Stacktrace:
 [1] accumulate at ./multidimensional.jl:760 [inlined] (repeats 2 times)
 [2] macro expansion at ./REPL.jl:97 [inlined]
 [3] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```
The same happens for
```julia
accumulate((acc, x) -> x, "", ['a', 'b', 'c'])
```

It seems that `accumulate(op, v0, x)` tries to guess the type of the output array based on both the type of the initial value and the type of the input array, while it should only consider the first.

Changing this line:
https://github.com/JuliaLang/julia/blob/4440b0f2a12479dfc691c6b4d079ba113290d7de/base/multidimensional.jl#L1105
to:
```julia
    T = rcum_promote_type(op, typeof(v0))
```
seems to fix the issue, but I am not sure whether there is a reason to prefer the original version.

**Comment by jw3126** [comment]
```julia
accumulate(+,0, [1.1])
```
would fail with the proposed fix.

**Comment by simonbyrne** [comment]
A full solution to this would probably involve extending #25051 to `accumulate`

**Comment by motjuste** [comment]
I am facing this issue while trying cumulative counting along the lines of the following:
``` julia
accumulate((acc, c) -> acc + (c == 'a' ? 1 : 0),  0, collect("cdaabcaa"))  # ERROR
```

My workaround for such a case was:
```julia
accumulate(+, map(c -> c == 'a' ? 1 : 0, collect("cdaabcaa")))
```

I would love to know if there is a better approach to do this!

**Comment by simonbyrne** [comment]
not yet, unfortunately.

**Comment by rfourquet** [comment]
All the examples here don't produce any error now.
