### ISSUE TITLE
shuffle method for matrix

### ISSUE THREAD

**Issue by sdmcallister** [JuliaLang/julia#25526]
I am wondering if it makes sense to add the following method?
```
m = [1 2 3;4 5 6]

Base.Random.shuffle(m) = reshape(shuffle(m[:]),size(m,1),size(m,2))

julia> shuffle(m)
2x3 Array{Int64,2}:
 3  6  2
 4  1  5
```

Thanks -Steve

**Comment by StefanKarpinski** [comment]
Having both `shuffle!` and `shuffle` for arrays of arbitrary dimension makes sense to me. Of course, implementation for some matrix types are either tricky to do efficiently (e.g. sparse matrices – you don't want to select and insert O(m*n) zeros), or impossible (e.g. diagonal, banded, etc.).

**Comment by mcognetta** [comment]
Assuming you want to preserve structural properties of the matrix (banded, sparse [this is sort of meaningless here though], symmetric,...), I don't see why these should be impossible.

For banded matrices, we know the bandwidth so we can just treat this as a random shuffle of band arrays concatenated together, the shuffle for symmetric and upper-diagonal matrices also seems to be the same although we have to take care with elements in the main diagonal. I do see how sparse matrices would be tricky to implement efficiently though.

Anyway, I think this should be doable for any (reasonable) agreed upon definition of shuffling for the special matrix types.

**Comment by StefanKarpinski** [comment]
I think shuffling the data in the structural nonzeros is a somewhat surprising behavior for these generic functions. Sure, that's the only thing you can do for some matrix types, but I think that operation deserves its own function, maybe `sufflenz!(A)` which would degenerate to `shuffle!` when `A` is dense, but would do quite different things on structured matrices. The `shuffle!` function should raise an error if called on a matrix type that cannot arbitrarily move nonzeros around. Note that an efficient `shuffle!` for `SparseMatrixCSC` is entirely possible but will want to shuffle values and resample indices in various ways.

**Comment by laborg** [comment]
`shuffle[!]` has been added for multidimensional arrays in https://github.com/JuliaLang/julia/pull/22226 
If really needed, the idea of `shufflenz` should probably be tracked in a specific issue.
