### ISSUE TITLE
StepRange + Float gives incorrect length

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#25521]
From https://discourse.julialang.org/t/properties-of-range/8298

```
julia> R = (22:-1:7)
22:-1:7

julia> x = -0.0030026930763747783
-0.0030026930763747783

julia> broadcast(+,x, R)
21.996997306923625:-1.0:7.996997306923625
```

**Comment by mbauman** [comment]
This happens to be fixed by #25377 (that's one of my current branches) — it's a simple change that could easily be split out.
