### ISSUE TITLE
Generalize `join` to allow use with non-strings

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#25534]
In writing some code just now I found myself wanting to pass non-strings to `join`: I have a vector of `Node`s representing HTML elements, and wanted to intersperse them with `", "` and `", and "`.

This is exactly the logic `join` offers, but it auto-`print`s its arguments to an `io` and does not generalize to the case of putting the results in a vector.

Here's the code for the four-argument version of `join`:

```julia
function join(io::IO, strings, delim, last)
    i = start(strings)
    if done(strings,i)
        return
    end
    str, i = next(strings,i)
    print(io, str)
    is_done = done(strings,i)
    while !is_done
        str, i = next(strings,i)
        is_done = done(strings,i)
        print(io, is_done ? last : delim)
        print(io, str)
    end
end
```

If the type annotation on `io` were lifted and a user-defined function could be passed in instead of `print`, I think the code as written would do what I want: I would pass in an empty vector as `io` and `push!` as the function.

Of course, it would probably also want to return `io`, which in this case represents the final result of the `join`.

Thoughts?

**Comment by nalimilan** [comment]
Looks like you want a separate function to me. `join` is designed to return a string, so if you want to return a vector better use something else. It only takes a few lines of code to implement.

**Comment by kmsquire** [comment]
The guideline that I would follow would be to extend the method if the underlying behavior is essentially the same, which it seems to be here. That said, I think the extended behavior could be implemented as part of the OP’s project/package, and only should be moved to Base if it proves to be more generally useful.
