### ISSUE TITLE
broken links in manual-functions

### ISSUE THREAD

**Issue by christianbender** [JuliaLang/julia#25543]
for example 
![juliamanual](https://user-images.githubusercontent.com/23243382/34907589-6e0524dc-f881-11e7-8c82-b50d9d4972c2.png)

I want like fix that with this link https://docs.julialang.org/en/stable/manual/functions/#man-anonymous-functions-1

greetings

**Comment by vtjnash** [comment]
I don't see that when I follow the link to the docs:
![screen shot 2018-01-13 at 2 11 52 pm](https://user-images.githubusercontent.com/330950/34909258-b7c27f22-f86b-11e7-9e3f-255a4bfddaa2.png)
Where are you seeing this rendering incorrectly?

**Comment by musm** [comment]
obsolete, links are correctly rendered
