### ISSUE TITLE
ccall should allow the same type signatures as cfunction

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2554]
Commit d42bb6dc16ff1468cd006904704999650113f1cd updated `cfunction` to allow more type signatures, such as `Function`, which is great for callback routines in which the C caller passes through some arguments as `void*` through to the callback.  However, the same arguments must currently be passed as `Any` to `ccall`, which is a bit counter-intuitive.

It would be nice if `ccall` and `cfunction` accepted and treated argument types in the same way.

For example, consider the following method to pass a re-entrant callback routine to the GNU libc `qsort_r` function.  (Warning: don't try this with MacOS or BSD, where `qsort_r` has a different argument order in its callback.)

````
function qsort_r_callback{T}(a::Ptr{T},	b::Ptr{T}, f::Function)
    int32(f(unsafe_ref(a), unsafe_ref(b)) ?
          -1 : unsafe_ref(a) == unsafe_ref(b) ? 0 : +1)
end

function qsort_r{T}(A::Vector{T}, f::Function)
    ccall(:qsort_r, Void, (Ptr{T}, Uint, Uint, Ptr{Void}, Any),
          A, length(A),	sizeof(T),
          cfunction(qsort_r_callback, Cint, (Ptr{T}, Ptr{T}, Function)),
          f)
    A
end
````

This works great, even for anonymous functions, e.g. `qsort_r([17,2,7,3,-1,14], (a,b) -> a < b)`.   However, if you change the `Any` argument of `ccall` to the sensible-seeming `Function` type, it segfaults.

**Comment by vtjnash** [comment]
cfunction will be significantly altered when https://github.com/JuliaLang/julia/pull/7906 merges (soon)

**Comment by JeffBezanson** [comment]
@vtjnash is this fixed now?
