### ISSUE TITLE
enable debug logging via environment variable

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#25549]
Previously, I could run julia with `JULIA_DEBUG_LOADING=1 ./julia` to quickly enable debug statements in subprocesses that I don't control. Now there doesn't seem to be a way to activate them at all? The new infrastructure is great, since this is really critical, useful stuff, but how do I use it?

**Comment by StefanKarpinski** [comment]
I had also proposed `Logging.debug(true | false)` to turn logging on or off. Any chance of getting that kind of an interface for this?
