### ISSUE TITLE
type alignment declaration

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#2555]
I am soliciting syntax ideas for alignment contraints on types (if Jeff approves). Below is one proposal:

```julia
type X
  a::Int32,16 #bits, underaligned (might cause segfaults due to unaligned memory access)
  b::Int32,128 #bits, overaligned
end
```

Additionally, we may want to be able to specify absolute offsets:
```julia
type X
  a::Int32,64 #bits, sets minimum alignment of entire type
  b::Int32,-128 #offset of 128 bits
  c1::Uint16,-128 #also offset 128 bits (creates a type union)
  c2::Uint16,-144 #remaining bits of type union
end
```

**Comment by eschnett** [comment]
I imagine one would want to define integer constants for the alignment, and then refer to these constants when specifying the alignment. This would e.g. allow defining several types with identical alignment, or using `if` statements when specifying the alignment, or using simple integer expressions for the alignment.

This would not work well with the `@` syntax. An explicit keyword, e.g. `aligned(64)`, possibly in square brackets, would allow this.

**Comment by ScottPJones** [comment]
I was just checking to see if Julia already had something like this, not just to control alignment in a structure, but of the structure itself...  this is very important if you need to lay things out so that they are on cache-line boundaries (usually 32 for ARM, 64 for Intel/AMD..., 128 for POWER).
Is this PR just dead?

**Comment by elextr** [comment]
@ScottPJones I don't think Julia can control the alignment of objects, but wouldn't that be needed as well as internal organisation to ensure cache alignment?

**Comment by ScottPJones** [comment]
Julia allocates all of the memory for objects, so it can align allocations.   As far as global objects (which I am also interested in aligning, C can do this with the `__declspec(align(n))` or `__attribute(align(n))` compiler directives... that information must be passed on to LLVM somehow.

**Comment by elextr** [comment]
Yes, what I meant is that Julia code doesn't have any way of specifying a required object alignment to its allocators, as you said "that information must be passed on to LLVM somehow".

**Comment by vtjnash** [comment]
It's perhaps worth pointing out that the gcc alignment attribute tells the compiler to assume the address is aligned, but does not guarantee alignment. For example the gcc docs suggest it may only provide int alignment. Also: http://stackoverflow.com/questions/1468513/attribute-aligned-not-working-with-static-variables

**Comment by elextr** [comment]
@vtjnash that SO points the finger at the system linker as the actual problem, but being JITed, does Julia actually use the system linker?

**Comment by vtjnash** [comment]
closing in favor of https://github.com/JuliaLang/julia/pull/15244
