### ISSUE TITLE
The paragraph in deprecation documentation does not look correct. 

### ISSUE THREAD

**Issue by sambitdash** [JuliaLang/julia#25556]
https://docs.julialang.org/en/latest/NEWS/#Deprecated-or-removed-1 states the following. The 1st and the 3rd items are repetitive and conflicting.

- Nullable{T} has been deprecated and moved to the Nullables package (#23642). Use Union{T, Nothing} instead, or Union{Some{T}, Nothing} if nothing is a possible value (i.e. Nothing <: T). isnull(x) can be replaced with x === nothing and unsafe_get/get can be dropped or replaced with coalesce. NullException has been removed.
- unshift! and shift! have been renamed to pushfirst! and popfirst! (#23902)
- Nullable{T} has been deprecated and moved to the Nullables package (#23642). Use Union{T, Void} instead, or Union{Some{T}, Void} if nothing is a possible value (i.e. Void <: T). isnull(x) can be replaced with x === nothing and unsafe_get/get can be dropped or replaced with coalesce.

**Comment by JeffBezanson** [comment]
Thanks. Looks like a rebasing issue probably.
