### ISSUE TITLE
Behavior of --check-bounds=yes

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#25566]
The command line option *check-bounds* has the following description:
```
 --check-bounds={yes|no}   Emit bounds checks always or never (ignoring declarations)
```

But when I run the code with `--check-bounds=yes` actually it does not seem to guarantee that bounds are always checked.

Consider the following code (copied definition of `thisind` from current master which is incorrect and due to be changed in #25533, but shows the problem):

```
import Base: between

function thisind2(s::String, i::Int)
    n = ncodeunits(s)
    i == n + 1 && return i
    @boundscheck between(i, 0, n) || throw(BoundsError(s, i))
    @inbounds b = codeunit(s, i)
    b & 0xc0 == 0x80 || return i
    @inbounds b = codeunit(s, i-1)
    between(b, 0b11000000, 0b11110111) && return i-1
    (b & 0xc0 == 0x80) & (i-2 > 0) || return i
    @inbounds b = codeunit(s, i-2)
    between(b, 0b11100000, 0b11110111) && return i-2
    (b & 0xc0 == 0x80) & (i-3 > 0) || return i
    @inbounds b = codeunit(s, i-3)
    between(b, 0b11110000, 0b11110111) && return i-3
    return i
end

function thisind3(s::String, i::Int)
    n = ncodeunits(s)
    i == n + 1 && return i
    @boundscheck between(i, 0, n) || throw(BoundsError(s, i))
    b = codeunit(s, i)
    b & 0xc0 == 0x80 || return i
    b = codeunit(s, i-1)
    between(b, 0b11000000, 0b11110111) && return i-1
    (b & 0xc0 == 0x80) & (i-2 > 0) || return i
    b = codeunit(s, i-2)
    between(b, 0b11100000, 0b11110111) && return i-2
    (b & 0xc0 == 0x80) & (i-3 > 0) || return i
    b = codeunit(s, i-3)
    between(b, 0b11110000, 0b11110111) && return i-3
    return i
end
```

Now I run Julia without any flags `./julia`:
```
julia> s = String([0x85])
"\x85"

julia> thisind(s, 1)
1

julia> thisind2(s, 1)
1

julia> thisind3(s, 1)
ERROR: BoundsError: attempt to access "\x85"
  at index [0]
Stacktrace:
 [1] checkbounds at .\strings\basic.jl:179 [inlined]
 [2] codeunit at .\strings\string.jl:78 [inlined]
 [3] thisind3(::String, ::Int64) at .\REPL[10]:7
 [4] top-level scope
```
this is to be expected (`thisind` has a bug, removing `@inbounds` in `thisind3` catches this bug).

But now I run `./julia --check-bounds=yes` to get:
```
julia> s = String([0x85])
"\x85"

julia> thisind(s, 1)
1

julia> thisind2(s, 1)
ERROR: BoundsError: attempt to access "\x85"
  at index [0]
Stacktrace:
 [1] checkbounds at .\strings\basic.jl:179 [inlined]
 [2] codeunit at .\strings\string.jl:78 [inlined]
 [3] thisind2(::String, ::Int64) at .\REPL[2]:7
 [4] top-level scope

julia> thisind3(s, 1)
ERROR: BoundsError: attempt to access "\x85"
  at index [0]
Stacktrace:
 [1] checkbounds at .\strings\basic.jl:179 [inlined]
 [2] codeunit at .\strings\string.jl:78 [inlined]
 [3] thisind3(::String, ::Int64) at .\REPL[3]:7
 [4] top-level scope
```

And although `thisind` from Base is identical to `thisind2` the first does not throw an error. While `thisind2` correctly does.

**Comment by bkamins** [comment]
I guess that for the compiled code the macros are resolved so that bounds checking is removed from it it? If this is the reason maybe documentation of *--check-bounds* should make it clear when this flag has effect?

**Comment by KristofferC** [comment]
I think code compiled into the sysimg cannot change based on runtime flags because it would mean that you would need to recompile the code.

Perhaps running with `sysimage-native-code=no` would help here.

**Comment by bkamins** [comment]
Checked and `sysimage-native-code=no` does not help. Actually there are two parts of the issue:
* is it possible to turn off `@inbounds` completely and if not it would be good if there were a switch for this (needed mostly for development of Base);
* improvement of documentation that would precisely explain what the switch does.
