### ISSUE TITLE
Documentation on german

### ISSUE THREAD

**Issue by christianbender** [JuliaLang/julia#25560]
I want like write documentations on german. 
Is that needed?

greetings

**Comment by ararslan** [comment]
Hi @christianbender! It's great to hear that you'd be willing to translate Julia's documentation to German.

On the [community page](https://julialang.org/community/) of the Julia site, under the heading "Localization," there are organizations listed that are dedicated to localization efforts for Julia's documentation into various languages. Currently these include Japanese, Chinese, Spanish, Portuguese, and Korean. What I would recommend is to start such an organization for German and just start plugging away at the translation. There are plenty of Julians who speak German, so I'm sure you'd be able to recruit some help for the effort. Once you've made some headway, feel free to submit a pull request to [the Julia site](https://github.com/JuliaLang/julialang.github.com) to include your organization amongst the other localization efforts.

A good place to discuss this would be [Discourse](https://discourse.julialang.org), our official discussion forum. Indeed, we try to reserve the GitHub issue tracker for bug reports and feature requests, so I'm going to close this issue. I recommend starting a thread on Discourse for further advice on getting started and recruiting some help.

Thanks for your interest in this effort!

**Comment by christianbender** [comment]
@ararslan  thanks for response.

**Comment by christianbender** [comment]
@ararslan  

> What I would recommend is to start such an organization for German and just start plugging away at the translation.

How I can do that?

**Comment by JeffBezanson** [comment]
Create an organization on github, like https://github.com/JuliaLangPt

**Comment by christianbender** [comment]
@JeffBezanson @ararslan  
I created an organization https://github.com/JuliaLangGerman
What next? Can I simply create a repository (for instance Julia_Dokumentation-Deutsch) ?
Or must be keep guidelines?

**Comment by ararslan** [comment]
I'd recommend asking on [Discourse](https://discourse.julialang.org). Hopefully someone from one of the other localization communities will be able to provide some guidance. :slightly_smiling_face:

**Comment by christianbender** [comment]
@ararslan  @JeffBezanson 
https://github.com/JuliaLangGerman/Julia_Handbuch_Deutsch
I started writing the manual like a tutorial. I oriented me on https://docs.julialang.org/en/stable/manual/introduction/
Should I prepare exercises? For newbies a advantage.

**Comment by nalimilan** [comment]
Ask `@IsmaelVC` on Discourse.

**Comment by christianbender** [comment]
I registered on discourse. (ChristianBender)
I created a first topic but that post must be first reviewed.
