### ISSUE TITLE
interpolation functions needed

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2557]
Julia should have linear/cubic/spline interpolation functions in 1+ dimensions, along the line of Matlab's [interp1](http://www.mathworks.com/help/matlab/ref/interp1.html) and friends.

This is a basic tool for numerical calculations, and shouldn't be too hard to implement.

**Comment by timholy** [comment]
Closing as an issue for packages, and one that has several partial solutions already (at least [Dierckx.jl](https://github.com/kbarbary/Dierckx.jl), [GridInterpolations.jl](https://github.com/sisl/GridInterpolations.jl), [ApproXD.jl](https://github.com/floswald/ApproXD.jl), and [Interpolations.jl](https://github.com/tlycken/Interpolations.jl)).
