### ISSUE TITLE
Is it possible to redirect a function / method call?

### ISSUE THREAD

**Issue by Smoobly** [JuliaLang/julia#25570]
That is, I want to modify a function—at run time—so that any call to it will actually go somewhere else, some other function. The new target function would do some stuff and then call the original function.

The purpose is to implement a log/trace facility that doesn't crap up the source code, making it difficult to read. If we could apply a log/trace at run time, the source would be unaffected.

**Comment by JeffBezanson** [comment]
There is no official feature for this, but https://github.com/jrevels/Cassette.jl might help.

**Comment by Smoobly** [comment]
> 
There is no official feature for this, but https://github.com/jrevels/Cassette.jl might help.
--
Looks very interesting, and it might do the trick. Thanks!

**Comment by vtjnash** [comment]
`@debug` and macros in general, can also be helpful for adding and computing useful log information with minimal affect on the normal source
