### ISSUE TITLE
Special underline printing for commands disappeared

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#25589]
The code is still there, but looks like the new way to do coloration broke it:
https://github.com/JuliaLang/julia/blob/master/base/process.jl#L105-L111
```
`curl abc`
```
should have underlines under the command parts.

**Comment by stevengj** [comment]
Yes, since the `io` created by `sprint` is an `IOBuffer`, color will be disabled for it.  The fix would be to something like:
```jl
replace(sprint() do buf
    with_output_color(:underline, IOContext(buf,io)) do io
        print_shell_word(io, arg, shell_special)
    end
end
```

**Comment by stevengj** [comment]
Actually, even easier, you can just do `sprint(context=io)`.
