### ISSUE TITLE
Suggestion for an improved ascii Julia logo

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#25587]
Obviously low priority.. But I was wondering whether the ASCII art logo when loading Julia could be a bit cleaner, and perhaps more accurate to the logo, both of which would help readability

Here's a proposed change (colorings would need to be added to the circles where appropriate)
```                  
             _   ( )      |  A fresh approach to technical computing
  ( )       | |( ) ( )    |  Documentation: https://docs.julialang.org
   _  _   _ | | _  ____   |  Type "?help" for help.
  | || | | || || |/_   |  |
  | || |_| || || |/ (| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
  | | \__,_||_||_|\__,_|  |  Official http://julialang.org/ release
(__/                      |  x86_64-w64-mingw32

```
Current version
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32
```

<img src="https://user-images.githubusercontent.com/1694067/35006198-065af02e-fac4-11e7-97b1-bd72899b2e1c.png" width="170">

**Comment by JeffBezanson** [comment]
The idea of removing the `_`s from the circles is not bad, but I think the new `a` is uglier.

**Comment by StefanKarpinski** [comment]
The ASCII art logo came first (designed by @JeffBezanson), I designed the vector logo much later to match it, so I'm not sure the ASCII logo can be inaccurate by definition 😁

**Comment by StefanKarpinski** [comment]
Removing the `_`s is not bad. Agree with Jeff about the original "a" being better.

**Comment by simonbyrne** [comment]
Also, the left dot of the triangle should be aligned on top of the i

**Comment by Keno** [comment]
```
           _  ⬤       |  A fresh approach to technical computing
  ( )     | |⬤⬤      |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32
```

**Comment by ianshmean** [comment]
Not sure if those circles are compliant, they seem to take up more than a unicode space (others likely more informed than me)

So reverted to the previous "a", and I rounded the bottom left of the "j", and made the bottom `'`s `,`s

```
           _   ( )     |  A fresh approach to technical computing
  ( )     | |( ) ( )   |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__,_|_|_|\__,_|  |  Official http://julialang.org/ release
(__/                   |  x86_64-w64-mingw32
```

In my first I did also add letter spacing to match the image logo, but given what @StefanKarpinski said, perhaps I was going by the wrong ground truth! ha!

**Comment by ianshmean** [comment]
Letter spaced version of the above, for reference
```
             _   ( )      |  A fresh approach to technical computing
  ( )       | |( ) ( )    |  Documentation: https://docs.julialang.org
   _  _   _ | | _  __ _   |  Type "?help" for help.
  | || | | || || |/ _` |  |
  | || |_| || || | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ | \__,_||_||_|\__,_|  |  Official http://julialang.org/ release
(__/                      |  x86_64-w64-mingw32
```

**Comment by StefanKarpinski** [comment]
That's not bad!

**Comment by JeffBezanson** [comment]
+1 to rounding the J. I don't like the other changes that much though.

**Comment by JeffBezanson** [comment]
Whether the underscores look good in the dots is quite font-dependent. If they don't line up, it looks bad, but if they line up it looks better than without IMO.

**Comment by ianshmean** [comment]
To be honest, if I knew that this logo was the first to be designed, before the rendered logo, I probably wouldn't have suggested edits in the first place.. Gotta respect history!

**Comment by petertuuk** [comment]
+1 to putting the left circle directly above the `i`, which both the current version and the first proposed change do (but that the OP's subsequent modification does not).

**Comment by ianshmean** [comment]
@petertuuk As it renders on my mac, the last one I posted above has the circle directly above the i. Is that not the case for you? (I guess this is the big risk with fixing something that wasn't broken...)

**Comment by petertuuk** [comment]
@ianshmean I now see that you posted *two* subsequent modifications, the second of which ("Letter spaced version of the above") does have the circle aligned.

**Comment by peterkovesi** [comment]
```
     _____                     _ 
   / __ _  \                  | |
  / / _` | |         _  _   _ | | _  __ _  
 | | (_| | |        | || | | || || |/ _` | 
  \ \__,___|        | || |_| || || | (_| | 
   \ \__     ( )   _/ | \__,_||_||_|\__,_| 
    \___|         (__/                     

```

**Comment by mauro3** [comment]
The underscores in the circles look good in a terminal with color, I think better than without. Most terminals have color (I think), thus they should be kept.

**Comment by nalimilan** [comment]
It's not such much that circles look better when color is support AFAICT, it's just that they look better on the terminal than in GitHub, since their vertical position isn't correct there. So better not base the choice on how it looks on GitHub.

**Comment by ianshmean** [comment]
Yeah, I think that's fair. I'll close the thread. Interesting discussion at least

**Comment by vtjnash** [comment]
Also ref https://github.com/JuliaLang/julia/pull/16143
