### ISSUE TITLE
change `match` arg order to match `contains`?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#25584]
Having used it for a bit, I don't mind `contains(string, regex)` but the fact that `contains(string, regex)` gets used a lot together with `match(regex, string)` and they have different argument order is really a bummer. Perhaps we should change `match` and similar functions to take arguments in the other order? Since one of the arguments is a regex object, we could really support either order.

**Comment by KristofferC** [comment]
This seems to make sense to me. A string `contain`s a regex but a regex `match`es a string.

**Comment by StefanKarpinski** [comment]
I know, it makes sense by the verb(subject, object) convention, but it's just really annoying switching back and forth between the two orders for example, in this code:

https://github.com/JuliaLang/julia/blob/1c499c73b0e9528e5cacec6ab59cf51a7f4bb1f2/base/loading.jl#L471-L489

You can also say that a string matches a regex rather than that a regex matches a string, so the other order is justifiable as well.

**Comment by malmaud** [comment]
I've been bugged by the inconsistent order too.

**Comment by nalimilan** [comment]
It's inconsistent with all `find*` functions too, so I'd rather than `contains` to use the same rule as other functions than `match`. The only justification for the current argument order of `contains` is that it could read as an infix operator (`c contains y`), but since it's not an operator...

The problem is that we cannot switch arguments for `contains(::String, ::String)` with a deprecation. I guess we could provide a temporary replacement in 0.7, and reintroduce the method with reversed arguments in 1.0.

**Comment by StefanKarpinski** [comment]
I guess we need a "contained in" operator.

**Comment by simonbyrne** [comment]
cf #19250

**Comment by simonbyrne** [comment]
> I guess we need a "contained in" operator.

```
\isinE    \isindot   \isinobar  \isins     \isinvb
```
Pick one?

**Comment by KristofferC** [comment]
Just put back `ismatch`...?

**Comment by nalimilan** [comment]
Or maybe we don't need this at all, and `isempty(findfirst(needle, haystack))` is enough?

OTOH https://github.com/JuliaLang/julia/issues/24303 gives a possible reason why we would want to have a dedicated function/operator (tentatively called `issubseq` there): to check in a generic way whether any collection contains a sequence of elements (and not only for strings). I suggested to do this via something like `findfirst(sequence(needle), haystack)`, but I'm not against having an operator.

**Comment by StefanKarpinski** [comment]
We need something that actually returns the `RegexMatch` object, not just whether something matched, so we can't really get rid of `match` here. We could also support both argument orders.

**Comment by nalimilan** [comment]
I don't think anybody suggested getting rid of `match`. `contains` is the only outlier here vs. `find*` and `match`.

**Comment by JeffBezanson** [comment]
The argument order "x contains y" makes too much sense to me to change. It can be understood by anybody who knows english, while the other argument order requires you to know the convention used by `find` functions.

**Comment by JeffBezanson** [comment]
But if we renamed it or added e.g. `findsubseq` or `containedin` then the argument order could be changed.

**Comment by simonbyrne** [comment]
We do the opposite for collections, i.e. "x in y".

**Comment by StefanKarpinski** [comment]
`x in y` tests whether `x` is in `y`...

**Comment by simonbyrne** [comment]
Yes, my point was that the smaller element (x) comes first. So it would make sense that in matching, the pattern which your looking for should also come first.

**Comment by StefanKarpinski** [comment]
We can always add a function that's like `contains` but with the reverse argument order, e.g. `contained(needle, haystack)` or `within(needle, haystack)` but that can be done at any point.
