### ISSUE TITLE
Mistypo on Base.FFTW 

### ISSUE THREAD

**Issue by appleparan** [JuliaLang/julia#25598]
I found [this mistypo](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/fft/FFTW.jl#L685) on `plan_inv` function in old Base.FFTW module and this cause syntax error on v0.6.2

It's simple. Just change `Arra` to `Array`.

However, I have no idea it is worth to fix it because all FFT modules are moved to `AbstractFFTs.jl` and `FFTW.jl`. If there is a actual plan to release 0.6.3, it may be worth to fix it, but I don't know whether it is.

Do I need to create pull request?

**Comment by ViralBShah** [comment]
We aren't planning on having any more 0.6 releases.

**Comment by appleparan** [comment]
ok. never mind. I close it.

**Comment by ViralBShah** [comment]
Good to know though and have this issue.

**Comment by appleparan** [comment]
there still exists same mistypo in [FFTW.jl](https://github.com/JuliaMath/FFTW.jl) (I thought this statement was removed on new repo), so I created new pull request JuliaMath/FFTW.jl#60
