### ISSUE TITLE
Problem with parsing triple quoted strings

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#25592]
Following https://stackoverflow.com/questions/48288817/does-the-first-line-of-triple-quoted-string-impact-indentation/48289353#48289353.

Julia documentation in https://docs.julialang.org/en/stable/manual/strings/#Triple-Quoted-String-Literals-1 states:

> First, if the opening `"""` is followed by a newline, the newline is stripped from the resulting string

But the actual behavior seems different, as described on SO. Literally:
1. first stripping is performed for all lines but the first
2. then newline is removed if `"""` is followed by a newline

Which means that the statement in the documentation is not precise, e.g. those are not equivalent:
```
julia> print("""
         aaa
         bb
         cc""")
aaa
bb
cc
julia> print("""  aaa
         bb
         cc""")
  aaa
bb
cc
```
although they should according to the documentation.

Actually there are two issues here:
1. first line (text just after `"""` is ignored in dedentation);
2. stripping newline after `"""` actually matters;

I would propose the following target behavior (which would be in line with the documentation):
1. first remove newline after `"""` if present
2. perform dedentation including the first line in the process

But maybe there are reasons for the current behavior. In such a case current rules should be probably documented.

**Comment by StefanKarpinski** [comment]
The current behavior seems desirable to me which would mean only the documentation needs to be fixed.

**Comment by bkamins** [comment]
OK. I have proposed a wording here https://github.com/JuliaLang/julia/pull/25594.

**Comment by Liso77** [comment]
if we want indented text without \n in the end then we have to hack it?

```julia
julia> """
        first
        second
       """[1:end-1]  # this line define indentation but we need to remove end of line
" first\n second"
```

Maybe strip newline if it is followed by last """ could improve expressivnes of this kind of literals.

**Comment by JeffBezanson** [comment]
You can write

```
julia> """
        first
        second"""
" first\n second"
```

to avoid the last `\n`.

**Comment by bkamins** [comment]
@JeffBezanson How do you exactly achieve this? If I copy-paste your recommendation I get `"first\nsecond"` both under 0.7 and 0.6.2.
I can get it by putting `\enspace` before `first` instead of normal space - but I would say it is a hack.

**Comment by JeffBezanson** [comment]
Oops, my mistake.

It's pretty odd to want to write the string `" first\n second"` --- where each line begins with spaces --- using a syntax explicitly designed to remove leading whitespace.

**Comment by StefanKarpinski** [comment]
I don't really see what the issue here is. Sure, you can't express every possible thing with just this construct, but so what? The point is just for it to conveniently handle common cases easily. If you want to have the leading whitespace and strip the newline, you can call `chop` on the string.

**Comment by Liso77** [comment]
Yes. It is more about **design beauty** than about technical bug. 

I wanted to propose to add possibility to define minimal indent without changing result string. 

But I used bad wording. :/ 

We could strip last line **if it include only whitespaces** (which would be used to define minimal indent) instead of <strike>last newline if it is followed by triple-quote</strike>.

**Comment by Liso77** [comment]
@bkamins - last empty line is special in current behavior. (maybe you like to put it in doc too)

one tab in empty line inside is ignored (in finding minimal indentation process):

```julia
# second line is represented by 1 tab ->
julia> open((f)->write(f, """testvar = \"\"\"\n\t\tone\n$("\t"^1)\n$("\t"^2)two\"\"\";"""), "/tmp/test_3quo.jl", "w");

julia> include("/tmp/test_3quo.jl")
"one\n\t\ntwo"

julia> println("[$testvar]")
[one

two]
```

But one tab in last line is not ignored:
```julia
julia> open((f)->write(f, """testvar = \"\"\"\n\t\tone\n$("\t"^2)two\n$("\t"^1)\"\"\";"""), "/tmp/test_3quo.jl", "w");

julia> include("/tmp/test_3quo.jl")
"\tone\n\ttwo\n"

julia> println("[$testvar]")
[       one
        two
]
```

There is also problem (bug?) if we mix tabs and spaces for indentation. I wanted to check if tab is equal to 8 spaces but got this: 

```julia
julia> open((f)->write(f, """testvar = \"\"\"\n\t\tone\n$(" "^16)two\"\"\";"""), "/tmp/test_3quo.jl", "w");

julia> include("/tmp/test_3quo.jl")
"\t\tone\n                two"

julia> println("[$testvar]")
[               one
                two]
```

**Comment by bkamins** [comment]
I guess the algorithm is:
* a longest common whitespace prefix is found using space or tab combination for all lines counting from the second line; lines containing only whitespace are ignored; last line is always included in the count;
* then this prefix is stripped from all lines counting from the second line - including lines containing only whitespace if that prefix was present in them;

I will update the docs

**Comment by tlienart** [comment]
can this be closed given the merged  PR https://github.com/JuliaLang/julia/pull/25594 ?

**Comment by bkamins** [comment]
One more small case that maybe it would be good to discuss before closing the issue. The white space stripping happens before interpolation is done, so we have:
```
julia> x=" "
" "

julia> """
       $(x)a
        b"""
" a\n b"
```
I think it an expected behaviour and it is OK to leave the docstring as-is, but just wanted to cross check with others if we are in agreement here.

**Comment by simeonschaub** [comment]
The current behavior definitely makes the most sense to me. Stripping whitespace after interpolation also isn't possible with the current design, because whitespace gets stripped at parse time.

**Comment by bkamins** [comment]
OK - so I am closing it. Please reopen/comment if you have some additional issues here.
