### ISSUE TITLE
Weirdness w/ label + LineNumberNode lowering?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#25607]
I don't quite understand why the LineNumberNode is getting spliced into the middle of the `@label` Expr, but this throws off some code I have that walks Expr trees looking for LineNumberNodes
```julia
julia> t = quote
       @label end_of_loop
       end
quote
    #= REPL[20]:2 =#
    #= REPL[20]:2 =# @label end_of_loop
end

julia> t.args
2-element Array{Any,1}:
 :(#= REPL[20]:2 =#)                   
 :(#= REPL[20]:2 =# @label end_of_loop)

julia> t.args[1]
:(#= REPL[20]:2 =#)

julia> t.args[2]
:(#= REPL[20]:2 =# @label end_of_loop)

julia> t.args[2].args
3-element Array{Any,1}:
 Symbol("@label")   
 :(#= REPL[20]:2 =#)
 :end_of_loop       
```

**Comment by yuyichao** [comment]
This is just the line number arguments of the macro call

**Comment by quinnj** [comment]
Oooooohhhh........, I had a little helper function that was removing LineNumberNodes to reduce clutter when looking at generated blocks of code, but things were breaking because I was removing the macro input arguments.

Got it.
