### ISSUE TITLE
docs for `Base.promote_op`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#25609]
`Base.promote_op` is used quite a bit through Base, mostly it seems for determining array output types, but it is undocumented. It would be nice to know (a) what it is supposed to do, and (b) where and when it can be used.

see also #25515 and #25591.

**Comment by martinholters** [comment]
(a) `promote_op(f, argtypes...)` guesses what an appropriate container eltype would be for storing results of `f(::argtypes...)`. It invokes inference for coming up with the guess, so it can change its mind any time.
(b) It can safely be used whenever you don't care about the result (remember, it's just guessing). If you now think "but then I can never use it!", you got it. The only excuse to use it is if you don't have any elements to figure out their types and guessing is the best you can do. (E.g. `broadcast`ing over empty input containers.)

Should I add that as a docstring to `promote_op`?

**Comment by simonbyrne** [comment]
Yes, please open a PR.

**Comment by simonbyrne** [comment]
Well, it is used for determining non-empty container types, e.g. for [matrix multiplication](https://github.com/JuliaLang/julia/blob/625923f99374093d708b31e34bdacd6375bc9be7/stdlib/LinearAlgebra/src/matmul.jl#L75).

**Comment by martinholters** [comment]
Ref. #19669.
