### ISSUE TITLE
Precompiled module loading issue

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#25604]
Given a package
```julia
__precompile__()
module Foo
using ProgressMeter
using DataStructures
end
```
I see
```julia
julia> using Foo
┌ Warning: Replacing module `Compat`
└ @ Base loading.jl:350
```
once `Foo` has been precompiled (but in a fresh Julia session). I don't think this is specific to PorgressMeter and DataStructures, they just happen to both depend on the same package (Compat) and be loadable on current master. However, it does look like the packages have to be registered.

While this is more or less just an annoyance, I guess the same underlying problem is responsible for something more severe. Consider the package (which unfortunately depends on some patches to FFTW to make it loadable):
```julia
__precompile__()
module Foo
using AbstractFFTs
using FFTW
foo() = fft([1])
end
```
Loading this for the first time, I get
```julia
julia> using Foo
[ Info: Recompiling stale cache file /tmp/julia/lib/v0.7/Foo.ji for module Foo

julia> Foo.foo()
# a bunch of deprecation warnings
1-element Array{Complex{Float64},1}:
 1.0 + 0.0im
```
Repeating (in a fresh session), I get
```julia
julia> using Foo
┌ Warning: Replacing module `Compat`
└ @ Base loading.jl:350
┌ Warning: Replacing module `AbstractFFTs`
└ @ Base loading.jl:350

julia> Foo.foo()
WARNING: both AbstractFFTs and FFTW export "fft"; uses of it in module Foo must be qualified
ERROR: UndefVarError: fft not defined
Stacktrace:
 [1] foo() at /tmp/julia/Foo/src/Foo.jl:5
 [2] top-level scope
```
(Note that FFTW imports `AbstractFFTs.fft`.)

**Comment by martinholters** [comment]
Bisection points to f53209354b1c802ded472466ccf0635018d0c8e0, CC @vtjnash

**Comment by StefanKarpinski** [comment]
I've been seeing this too on #25455 but I thought that it was some change on that branch.
