### ISSUE TITLE
Command line flag `machinefile` should be `machine-file`

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#25603]
To match `startup-file` and `history-file`. Alternatively, the latter two could be changed. I think this has been mentioned somewhere previously but I couldn't find it. Should probably be done before 1.0.

**Comment by StefanKarpinski** [comment]
Seems easier and more "correct" to change `--machinefile` to `--machine-file`.

**Comment by JeffBezanson** [comment]
Seems unobjectionable to me. If done before 1.0, can be deprecated, otherwise can be added as an alias.

**Comment by hackboxlive** [comment]
Hi, I would like to start contributing to Julia by working on this issue. So far, I think, changing the `{ "machinefile",     required_argument, 0, opt_machinefile },` in `jloptions.c` file should do it, right? Also, the `README` will be updated. Am I right?

**Comment by martinholters** [comment]
Yes, except that we probably want to keep `--machinefile` for now, doing the same as `--machine-file`, but also printing a deprecation warning to use the latter.

**Comment by StefanKarpinski** [comment]
You can see other similar deprecation warnings for old versions of various options in that file if you look around.

**Comment by srbcheema1** [comment]
Made a PR for this at  **#25673**
