### ISSUE TITLE
how to call a Anonymous Functions?

### ISSUE THREAD

**Issue by mixml** [JuliaLang/julia#25619]
How to call a Anonymous Functions
when I type in REPL
**julia> x->x>2**
(::#1) (generic function with 1 method)

then what should i do to call this funtions in REPL?

**Comment by ararslan** [comment]
Hi @mixml! As the issue template text says, we use the GitHub issue tracker for bug reports and feature requests. For questions, ask on https://discourse.julialang.org.

Since the answer is so simple I'll just go ahead and answer this here.
```
julia> (x->x > 2)(1)
false

julia> f = x->x > 2;

julia> f(1)
false
```

**Comment by mixml** [comment]
@ararslan I have known the way that you post to call Anonymous Functions. But I want to konw that when I type 
**julia> x->x>2
(::#1) (generic function with 1 method)**
then how can i use the consecutive numbering "::#1" to call the Anonymous Functions

**Comment by JeffBezanson** [comment]
In general there is no way to do that. Anonymous functions are like other values; you need to have some reference to it (like a variable) to be able to use it.

**Comment by mixml** [comment]
@JeffBezanson Thanks!

**Comment by shorty66** [comment]
There is also the variable `ans` whcih gets set to the last output.
```julia
julia> x->x>2
(::#1) (generic function with 1 method)
julia> ans(1)
false
```
