### ISSUE TITLE
import of modules and using

### ISSUE THREAD

**Issue by christianbender** [JuliaLang/julia#25618]
Is that normal? If you create my own module

```julia
module myModule

export x
x = 56
end
```

and save it under ```myModule.jl``` in the same directory as my main program.
Then I must first ```include``` the file before I can use the modul over ```using``` ?

```julia
include("myModule.jl")
using myModule

println(myModule.x) # print the module variable x
```

If I don't include the file before I use ```using``` or ```import``` I became an error message.

**Comment by fredrikekre** [comment]
Please use https://discourse.julialang.org/ for questions.
