### ISSUE TITLE
Sparse + Transpose(Sparse) not defined and hence this sum becomes DENSE

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#25656]
```
julia> S = sparse([2, 3], [1, 2], [3., 4.], 3, 3)
3×3 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [2, 1]  =  3.0
  [3, 2]  =  4.0
julia> S + transpose(S)
3×3 Array{Float64,2}:
 0.0  3.0  0.0
 3.0  0.0  4.0
 0.0  4.0  0.0
```
I am guessing that the method for the addition of a sparse matrix and the transpose of a sparse matrix is not defined, and the default `+` produces a regular dense array?

**Comment by fredrikekre** [comment]
dup of your own issue #25331

**Comment by PetrKryslUCSD** [comment]
Not really. In that issue my solution `S + transpose(S)` produced a correct, sparse, matrix. With the current 0.7 master it no longer works. (Lazy transpose?)

**Comment by PetrKryslUCSD** [comment]
The required code now is
```
S + copy(transpose(S))
```
I think the issue deserves to be reopened. @fredrikekre : what do you think?

**Comment by KristofferC** [comment]
I think #25331 tracks it perfectly.

**Comment by PetrKryslUCSD** [comment]
Yes, except there `transpose(S)` was sparse; now it isn't.

**Comment by PetrKryslUCSD** [comment]
So, maybe attach a comment to https://github.com/JuliaLang/julia/issues/25331?

**Comment by KristofferC** [comment]
Yes
