### ISSUE TITLE
`return` matters in generated function lowering

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#25678]
Haven't tracked this down fully, but something is up with lowering:
```
@generated function code_llvm_helper(f, args...)
    NI.code_typed(f.parameters[1], Tuple{args...})[1].first
end
@generated function code_llvm_helper2(f, args...)
    return NI.code_typed(f.parameters[1], Tuple{args...})[1].first
end

julia> typeof(first(methods(code_llvm_helper)).generator.gen(nothing, Val{x->x}, [Bool]))
Expr

julia> typeof(first(methods(code_llvm_helper2)).generator.gen(nothing, Val{x->x}, [Bool]))
CodeInfo
```

This distinction matters quite a bit of course, since `CodeInfo` returns get treated specially.
Looks like the extra Expr in the first case is a LineNumberNode.

**Comment by vtjnash** [comment]
The result of code_typed isn’t valid as the return object for generated functions (we’re just sloppy about detecting this). Do you have an example with code_lowered?

**Comment by Keno** [comment]
Haven't tried, but it's a lowering transform that's being misapplied here, so I suspect the same will work.

**Comment by Keno** [comment]
Also, it would be nice if `code_typed` was valid for this, so I could feed my inference experiments to the code generator. It already does mostly work (prints an error, but then does compile the right code).

**Comment by vtjnash** [comment]
It's not valid because inference is an iterative algorithm, and this would be calling it recursively. It's also the wrong sort of return object (inferred code contains expressions that can't be passed to inference).

**Comment by Keno** [comment]
Well, I'm calling a different Inference's `code_typed` so from Inference's point of view I'm not calling it recursively.

**Comment by oxinabox** [comment]
aslo came up in https://github.com/NHDaly/StagedFunctions.jl/pull/8

**Comment by NHDaly** [comment]
Copied from that issue:

> Apparently using an actual `return code_info` line, instead of just having the `code_info` as the final expression, prevents Julia lowering pass from wrapping the return value in an `Expr(:block, ...)`, meaning it can be used by Julia to build the generated function.
> 
> Here is an example showing that difference:
> 
> With `return`:
> 
> ```julia
> julia> Meta.@lower @generated function f() return 2 end
> ...
>     $(Expr(:meta, :nospecialize, :(@_2)))
>     return 2
>     Core._expr(:block, $(QuoteNode(:(#= REPL[107]:1 =#))), nothing)
>     return %3
> ...
> ```
> 
> Without `return`:
> 
> ```julia
> julia> Meta.@lower @generated function f() 2 end
> ...
>     $(Expr(:meta, :nospecialize, :(@_2)))
>     Core._expr(:block, $(QuoteNode(:(#= REPL[108]:1 =#))), 2)
>     return %2
> ...
> ```
> 
> As far as I can tell, it's been like this since Julia 0.7.

It looks to me like the lowering was _attempting_ to wrap the return value in a `QuoteNode` (potentially to _prevent_ returning a CodeInfo to have the above effect?), but that there's a bug that prevents that from happening if you `return` the expression instead of leaving it as the last line?
