### ISSUE TITLE
Julia installer for Windows contains out-of-date properties

### ISSUE THREAD

**Issue by jayschwa** [JuliaLang/julia#25677]
The Julia installer for Windows contains out-of-date properties. The version displays `0.3-pre` and the copyright is a few years behind. Affects the installers for both 0.6.2 and nightlies. I grepped the repo and was unable to find the source of these values.

![julia_installer_wrong_version](https://user-images.githubusercontent.com/475017/35198757-aa9f1038-fec1-11e7-8cee-ce2740c4d6ec.png)

**Comment by vtjnash** [comment]
I think it's from this file: https://github.com/JuliaLang/julia/commits/master/contrib/windows/7zS.sfx

**Comment by simonbyrne** [comment]
Is this even worth fixing?

cc @ihnorton

**Comment by ViralBShah** [comment]
Seems like we should either fix or not ship (if not required).

**Comment by ihnorton** [comment]
The only way to change this string is to edit the resource table of the sfx
file Jameson linked. I did a quick google and didn't find a command line
utility to do this on linux, so I'm inclined to just change the string to
"See filename" for now... Unless someone has time to add resource table
support to COFF.jl, including in particular [StringFileInfo](
https://msdn.microsoft.com/en-us/library/windows/desktop/aa381049(v=vs.85).aspx),
and teach the build system how to use it.

**Comment by ihnorton** [comment]
Well here's one that has command line support and could be run under wine:
http://www.angusj.com/resourcehacker/
Not inclined to do that, though, because it seems like another brittle
step. If anyone knows of a linux-native alternative, let me know.

**Comment by vtjnash** [comment]
We could probably change this once, to "Installer v1.0 for Julia", and then leave it alone.

**Comment by tkelman** [comment]
shouldn't windres be able to modify these?

**Comment by visr** [comment]
It's no longer outdated, I just checked the properties of `julia-1.3.0-rc3-win64.exe`
```
Product version: 1
Copyright: Copyright (c) 2009-2019 Julia Language
```

And for nightly it's slightly different:
```
Product version: 1.4.0-DEV
Copyright: Copyright 2009-2019; Julia Language
```

**Comment by musm** [comment]
yep now fixed
