### ISSUE TITLE
More information on network activity during Pkg.add(..) Pkg.update() (to highlight if network slow)

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#25690]
After getting frustrated with very long pauses with no text output after running Pkg.add() and Pkg.update() I finally realized that my network was crawling to a halt.

I'm wondering whether there might be a better way to handle this than just hanging with no output?

Some sort of `get` progress meter? Or maybe just a timed message saying 'Attempting to connect' if a get isn't successful by a fixed time etc.

**Comment by simonbyrne** [comment]
The new Pkg is so amazingly fast that this should no longer be an issue. (it also gives much nicer output).

Future issues should be filed at https://github.com/JuliaLang/Pkg.jl
