### ISSUE TITLE
document function return type declaration

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#25718]
The Function section of the documentation does not mention the possibility of declaring a return type.  

When googling *julia return type*, the first results are https://github.com/JuliaLang/julia/issues/1090 and the Function section of the doc, the first one being long and closed, the second one not containing the info.

The information is actually located [here](https://docs.julialang.org/en/latest/manual/types/#Type-Declarations-1), would it make sense to also mention it at least in the Functions and/or Methods section?

**Comment by c-p-murphy** [comment]
I would be interested in tackling this (as my first contribution to Julia 😃).

**Comment by matbesancon** [comment]
@JeffBezanson @adrianisuru closing this with #26195, thanks
