### ISSUE TITLE
convert & promote_rule for Char and strings

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#25728]
Came up over here: https://github.com/JuliaLang/julia/pull/25515#issuecomment-359816093. I think we should consider adding something like:
```jl
promote_rule(::Type{Char}, ::Type{S}) where {S<:AbstractString} = S

convert(::Type{String}, c::Char) = string(c)
convert(::Type{S}, c::Char) where {S<:AbstractString} =
    convert(S, convert(String, c))
```
Previously when `Char <: Integer` this was considerably sketchier but that's not the case anymore.

**Comment by nalimilan** [comment]
That's tempting, but I'm not sure that's right to allow converting an entry into a one-element collection like that. Shouldn't we define `==` between strings and chars if we do that?

Do we have other use cases than `accumulate(*, ['a', 'b'])`? For example, `['a', "b"]` would give `["a", "b"]`, which may or not be desirable.

**Comment by JeffBezanson** [comment]
I think this is non-breaking?

**Comment by nalimilan** [comment]
Changes to promotion affect the type of elements inside array literals, so I think it's breaking (though not terribly so).

**Comment by JeffBezanson** [comment]
True.

I'm starting to think I'd prefer a slightly different approach to promotion in general. The only cases where I really want it are arithmetic, and mixed numeric array literals like `[0, 0.5, pi]`. It would be much simpler if we could say it's only for arithmetic, but AFAICT we need to have `[0, 0.5]` give a Float64 array or we'll have huge problems. Maybe special case array constructors where everything is a Number? I'm not even sure `[[1], [1.0]]` needs to give a homogeneous array result.

**Comment by StefanKarpinski** [comment]
Triage: decided against.
