### ISSUE TITLE
Logging missing from the manual

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#25737]
It looks like the logging facilities (e.g. `@info`, `@warn`, etc.) have docstrings but are not in the manual. It would be great to have a section of the manual devoted to logging now that we have the framework for it.

**Comment by c42f** [comment]
Absolutely agreed, I just need to find time for this.  Dup of #25154!

**Comment by ararslan** [comment]
Oops, sorry for the duplicate!

**Comment by c42f** [comment]
No problems, it's a good reminder that I need to get that stash out again and finish it.
