### ISSUE TITLE
Sign windows binaries correctly and enable for Windows Desktop Application Analytics

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#25730]
https://blogs.windows.com/buildingapps/2018/01/23/introducing-windows-desktop-program-desktop-application-analytics/

I believe essentially it should be enough that the ``julia.exe`` is code signed with the Julia Computing certificate (for the prebuilt binaries from the web that is not the case right now, only the installer seems code signed), and then someone from Julia Computing needs to sign up for that program.

I believe at that point you would automatically get usage statistics and crash reports that Windows collects for julia. There would be really two benefits: a) probably much more reliable usage data than download numbers (at least for Windows) and b) you learn about those bugs that no one bothers to report manually.

We recently enabled crash reporting for the julia VS Code extension, and it is quite eye opening what kind of bugs you learn about when you do that :)

**Comment by ViralBShah** [comment]
This is a great idea. We should do it.

cc @mdpradeep @aviks

**Comment by davidanthoff** [comment]
Bump, any chance this might be done for 1.2? I think it should be relatively easy, but the payoff seems really, really significant.

**Comment by KristofferC** [comment]
Won't happen for 1.2 at least which has been in bugfix mode for a long time.

**Comment by davidanthoff** [comment]
Maybe it would be possible to add code signing of the produced exe to the nightly build and see how that goes?

**Comment by ViralBShah** [comment]
Fixed in https://github.com/JuliaCI/julia-buildbot/pull/129

**Comment by ViralBShah** [comment]
@davidanthoff Should we need to do anything further?

**Comment by ViralBShah** [comment]
@mdpradeep Can you sign us up for the relevant program at Microsoft so we can get access to the  various stats?

**Comment by davidanthoff** [comment]
My understanding is that this should be enough :)

**Comment by mdpradeep** [comment]
This was set up about 2 weeks ago but it does not seem to be pulling any data although it recognizes the certificates (as it is able to recognize the certs).

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/13034211/64350624-9c33a900-d016-11e9-9b95-6289539cbb93.png">

**Comment by davidanthoff** [comment]
Might it make sense to try to resolve this via MS support, even if it costs something? It seems to me that this info would be really valuable (because you would get that data even for users that haven't opted-in for any Julia telemetry, it would be enough that they opted into the Windows telemetry at some point).

**Comment by ViralBShah** [comment]
@mdpradeep Do we have to enable the analytics or something? Can we file a microsoft support issue?

**Comment by davidanthoff** [comment]
I took another look at the Julia binaries, and as far as I can tell they are not signed correctly. If that is so, then it is not surprising that this is not working properly.

Here is why I think that is so: when I look at the properties (in explorer) of say code.exe (the VS Code binary), I see a tab "Digital Signatures" in there, and then a signature from MS.

When I look at the properties of julia.exe, I don't even see a tab for Digital Signatures, which seems to suggest that minimally there is some difference in how these exes are signed (if the Julia binary is signed at all).

CC @staticfloat

**Comment by ViralBShah** [comment]
I think we only sign the installer.

**Comment by davidanthoff** [comment]
I thought https://github.com/JuliaCI/julia-buildbot/pull/129 was meant to install the `julia.exe`? For this issue here to work, the `julia.exe` needs to be signed.

**Comment by staticfloat** [comment]
So I looked into this, and the mono signcode is returning success and modifying the `.exe`, but Windows explorer and the `SignTool` from the windows 10 SDK doesn't show any signatures.  So there's probably a bug in the mono signcode implementation.

**Comment by davidanthoff** [comment]
Sorry, I should have followed up on this: I came to the same conclusion, but via a different path :)

I’ve been playing around a lot with the MSIX stuff. And the MSIX toolchain seems to think that the official `Julia.exe` that is ships as part of the Julia setup has an invalid format (and so I can’t actually put it into an MSIX installer). I can also not sign the exe that is in the official installer with the SDK signtool, it also complains about a badexe format.

So what I’ve been doing instead is building from source, and then signing the Julia.exe (and all dlls) with the SDK signtool myself. Works like a charm, and those signed files are accepted by the MSIX toolchain.

So my guess is that the mono signtool actually adds a corrupt signature, that is ignored by Windows, but not the MSIX toolchain.

Why not try to use the SDK signtool again? That must literally be used to sign thousands of files every day, and at least in my experiments over the last weeks it worked without a flaw..

**Comment by staticfloat** [comment]
> Why not try to use the SDK signtool again? That must literally be used to sign thousands of files every day, and at least in my experiments over the last weeks it worked without a flaw..

It would work for weeks, then mysteriously stop working.  It would fail with internal error codes that would not go away unless I wiped the windows buildbots and reinstalled windows from scratch, then would stop working after a few weeks again.  I was never able to figure out what was wrong.

**Comment by davidanthoff** [comment]
Hm, that sounds really strange for a tool that must be used so widely? Isn’t like almost every single piece of Windows software signed with it? Is there maybe something strange going on with the build bot machines? Also, I think it probably gets updated with every SDK release, maybe worth trying with the latest version?

Can you point me to the code where the actual signtool is invoked? I could try to cross check it with how I have run it, maybe it is a config problem?

**Comment by ViralBShah** [comment]
Is it possible to use whatever the standard Windows SDK thing is instead of Mono's tool to sign? I am assuming the Mono one is different from Microsoft official, reading this discussion.

**Comment by ViralBShah** [comment]
Could this also be the reason why we have ongoing issues with antivirus programs?

**Comment by davidanthoff** [comment]
Who knows what antivirus programs do, but if one can appease them by having a properly signed exe and dlls (which seems fairly plausible), then yes, I could imagine that signing correctly might help :)

**Comment by davidanthoff** [comment]
https://www.microsoft.com/security/blog/2018/08/16/partnering-with-the-industry-to-minimize-false-positives/ suggest that it might help a lot with the antivirus issues.

**Comment by ViralBShah** [comment]
Could it be that we need some new type of certificate?

**Comment by davidanthoff** [comment]
The installer exe seems to get properly signed, which seems to suggest that the certificate is ok?

**Comment by davidanthoff** [comment]
Just a quick update on this: that system is now collecting _something_. We were just looking into something unrelated, and happened to now have access to that account and took a look. It is now showing number of installs, per version and per region. For example, it shows this for the last 30 days:

![image](https://user-images.githubusercontent.com/1036561/117347519-0f319a80-ae5e-11eb-9f25-be7851b66f64.png)

It looks to me like we are maybe shipping `julia.exe` binaries at the moment that have incorrect version meta data included? At least unless there is a secret Julia version 51 ;)

I am not so sure anymore how useful this thing could actually be, though, because it seems to just count every install, including CI builds... So it actually says that there were 1.5 million installs over the last 30 days :) But maybe worth looking into this a bit more to figure out whether one could somehow exclude CI builds from this.

I _also_ collects crash reports and statistics. At the moment they are kind of pointless because there is no symbol information to make them useful, but I think there are instructions on how that could be done. I think one can for example upload symbol information to that web page and then it just uses those, or something like that.

@staticfloat do you have have idea where these Julia versions with version numbers that start with 51 might originate from? They must come from Julia Computing somehow, because this system would only count things that are signed with the Julia Computing code signing certificate.

**Comment by staticfloat** [comment]
That's hilarious.  I have no idea.  @aviks do you have any idea?

**Comment by vtjnash** [comment]
10.20.0.0 seems like the older (v1.3-) installer (internal)
51.1052.0.0 seems to be the newer one (internal)

I just launched each installer to confirm, but it is on a different machine, so I can't screenshot for proof

**Comment by ViralBShah** [comment]
Is this possible to close now?

**Comment by davidanthoff** [comment]
Probably, the `julia.exe` definitely is being signed correctly now, and some data is showing up in the Windows Desktop Application Analytics.

I think there is still a question whether it would make sense to actually sign all dlls that are shipped as part of the Julia distribution, I think that would be best practice with no real downside? Probably would be enough to add another call `signtool *.dll` somewhere?

**Comment by ViralBShah** [comment]
@staticfloat @DilumAluthge Should we be adding a `signtool *.dll`?

**Comment by ViralBShah** [comment]
I believe this is resolved, but please reopen if not.
