### ISSUE TITLE
readuntil_indexable cache construction algorithm is broken

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#25754]
In #25713 I mentioned that the cache-construction algorithm was suboptimal, to which @vtjnash said that if that were so, the function would be broken. As a result we were able to construct the following example of broken behavior:
```
julia> readuntil(IOBuffer("abcaabcaabcxl"), "abcaabcx")
"abcaabcaabcxl"
```
should not include the last `l`. This is a bug in the cache construction part of the algorithm.

**Comment by vtjnash** [comment]
The issue appears to be that in the cache construction, we're only testing `ci == cb`, but failing to then run the backtracking algorithm on the target if that is not matching.
