### ISSUE TITLE
showcompact() docstring outdated?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25765]
The docstring for `showcompact` still says that it's used to avoid repeating type information, but AFAIK this is no longer the case since we now use the `typeinfo` property for that (https://github.com/JuliaLang/julia/pull/24651/).

@rfourquet Is that right?

```
help?> showcompact
search: showcompact

  showcompact(x)
  showcompact(io::IO, x)

  Show a compact representation of a value to io. If io is not specified, the
  default is to print to STDOUT.

  This is used for printing array elements without repeating type information
  (which would be redundant with that printed once for the whole array), and
  without line breaks inside the representation of an element.

  To offer a compact representation different from its standard one, a custom
  type should test get(io, :compact, false) in its normal show method.
```

**Comment by stevengj** [comment]
Should we just deprecate `showcompact` in favor of `show(IOContext(io, .....appropriate options....), x)`?

**Comment by nalimilan** [comment]
That would make sense. `showcompact` is not really meant to be called directly AFAIK.

**Comment by rfourquet** [comment]
> @rfourquet Is that right?

Yes

**Comment by nalimilan** [comment]
Filed https://github.com/JuliaLang/julia/pull/26080 to deprecate `showcompact`.
