### ISSUE TITLE
Julia - is a fractal of good design?

### ISSUE THREAD

**Issue by EldarAgalarov** [JuliaLang/julia#25771]
Hello, dear developers of the Julia language!

I came across one very popular article about the PHP language, namely its bad design.

[PHP: a fractal of bad design](https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/)

It is clear that Julia has nothing to do with PHP, but I propose to read the article and check whether there are any similar problems and defects in the language Julia. Soon the release of the language will take place and it is better to correct everything now. After the release, nothing can be changed without breaking backward compatibility.

Personally, I have high hopes for Julia language and I want to replace R with Julia.

**Comment by KristofferC** [comment]
Thanks for the comment. I'm not sure this type of general discussion is very useful to have on the issue tracker and would encourage posting it to e.g. the discussion forum at discourse.julialang.org.

**Comment by JeffBezanson** [comment]
Yep, I've read that one :) Please let us know if you find anything.
