### ISSUE TITLE
Capitalization of `DevNull`

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#25786]
`DevNull` is proper case while `STDOUT` is upper case. Since we generally only use CamelCase for types and modules, this should perhaps be changed to something like `DEVNULL`.

(cc @nalimilan)

**Comment by yurivish** [comment]
Bump. This is a small but backwards-incompatible name consistency change. Should it be done for 1.0?

**Comment by nalimilan** [comment]
Let's hear what triage thinks about this (will happen tomorrow).

**Comment by ararslan** [comment]
I think we should do this.

**Comment by ararslan** [comment]
As an aside, the Julia Vim definitions used to highlight `DevNull` as a type, likely because it's cased like it is one.

**Comment by JeffBezanson** [comment]
From triage: there is some significant support for making these all lowercase --- `stdout`, `stdin`, `stderr`, `devnull` --- which follows C more. It also matches the keyword argument names to `pipeline`, e.g. `pipeline(cmd, stderr=stdout)`.

**Comment by nalimilan** [comment]
But don't we follow the convention that constants use uppercase?

**Comment by mbauman** [comment]
It turns out neither `STDOUT` nor `STDIN` are constants.  `DevNull`, however, is.

**Comment by ararslan** [comment]
> But don't we follow the convention that constants use uppercase?

It was pointed out that we don't always: `Inf`, `NaN`, `missing`, `nothing`, etc. (That said, I'm still in favor of this particular change.)

**Comment by JeffBezanson** [comment]
I like lowercasing all of these: stdin, stdout, stderr, devnull. @Keno points out that devnull comes from `/dev/null`, which is lowercase.

**Comment by StefanKarpinski** [comment]
Triage votes for lowercasing all of these with a dissenting vote from @ararslan.

**Comment by ararslan** [comment]
I've adjusted #25959 per triage consensus.
