### ISSUE TITLE
Spurious space before "(" not allowed with anonymous function

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#25806]
Ok, so I probably shouldn't try to squeeze this anonymous function all on one line in the first place, but the error here is misplaced — it's thinking that `(head, tail...)` is the function name:

```julia
julia> function(head, tail...) (head, f(tail...)...); end
ERROR: syntax: space before "(" not allowed in "(head, tail...) '('"
```

**Comment by JackDevine** [comment]
I think that you missed a semi colon. I don't understand how you could expect julia to work out what you mean with everything on one line.

```julia
julia> a = function(head, tail...); (head, f(tail...)...); end
```

Although I could be missing something really obvious here...

**Comment by mbauman** [comment]
Semicolons aren't required if the body of the function isn't parenthesized:

```
julia> function() 1 end
#1 (generic function with 1 method)

julia> function f() 1 end
f (generic function with 1 method)

julia> function() (1) end
ERROR: syntax: space before "(" not allowed in "() '('"

julia> function f() (1) end
ERROR: syntax: space before "(" not allowed in "f() '('"
```

You're right, it's easy to work around with semicolons and newlines, though.  Not a big deal here, just flagging it in case someone interested in the parser wanted to pick it up.

**Comment by mbauman** [comment]
Fair enough, I can live with that.
