### ISSUE TITLE
REPL completion tests are fragile

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#25816]
Some tests use `tempdir()` directly:
https://github.com/JuliaLang/julia/blob/544a5b8e395120bed3c860c77142de954de09c32/stdlib/REPL/test/replcompletions.jl#L715
https://github.com/JuliaLang/julia/blob/544a5b8e395120bed3c860c77142de954de09c32/stdlib/REPL/test/replcompletions.jl#L741-L742

The test above creates a file, eg. ```test`test```, making sure `test<TAB>` correctly completes to ```test`test/```. On my system, I had a file `test.jl` in `/tmp/`, causing mysterious test failures on my buildbot:

```julia
Test Failed at stdlib/REPL/test/replcompletions.jl:752
  Expression: c[1] == test_dir * if Sys.iswindows()
            "\\\\"
        else
            "/"
        end
   Evaluated: "test.jl" == "test`test/"
```

The tests should probably use `mktempdir` to avoid this.

**Comment by KristofferC** [comment]
To add to this, having

```
print("Hello")
```

in `.juliarc.jl` will cause the REPL tests to fail.

**Comment by iblis17** [comment]
`mktempdir` has been added in this PR.
https://github.com/JuliaLang/julia/pull/26705/files#diff-bc833edc8bc0faa18d6e265976e20435R715
