### ISSUE TITLE
(U)Int32 * irrational = Float64

### ISSUE THREAD

**Issue by chriselrod** [JuliaLang/julia#25842]
Multiplying rational numbers and 32 bit (un)signed integers results in Float64 outputs.

```julia
julia> π * Cint(2)
6.283185307179586

julia> typeof(ans)
Float64

julia> Cuint(2) * ℯ
5.43656365691809

julia> typeof(ans)
Float64

julia> versioninfo()
Julia Version 0.7.0-DEV.3580
Commit 296d572 (2018-01-26 00:07 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, znver1)
Environment:
```

```julia
julia> π * Cuint(2)
6.283185307179586

julia> typeof(ans)
Float64

julia> Cint(2) * ℯ #I had loaded Compat. This still occurs in a fresh session.
5.43656365691809

julia> typeof(ans)
Float64

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 1950X 16-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (ZEN)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, generic)
```

This can cause unexpected type instabilities, in particular when using GPUArrays. I think it is more intuitive for result to be of the same size -- a Float32. This result is also unexpected:
```julia
julia> Cuint(1) * π * 1f0
3.141592653589793

julia> Cuint(1) * 1f0 * π
3.1415927f0
```

**Comment by stevengj** [comment]
I don't see how this could cause a type instability, could you clarify?

This seems consistent with Julia's other rules — when pretty much any fixed-width integer type is converted to floating-point, the default is `Float64` except when it's explicitly combined with `Float32`, e.g. `UInt(8)/UInt(9)` produces `Float64` while `UInt(8) * 1.0f0/UInt(9)`  produces `Float32`.

(`Cuint(1) * π * 1f0` vs. `Cuint(1) * 1f0 * π` occurs because `*` is left-associative.)

**Comment by chriselrod** [comment]
The type instability was because a Float32 later got updated into a Float64 (and began converting other variables). Took me a while to find out which was the initial Float32 -> Float64, because I didn't expect Cuint(2)pi to be the cause.

Now that I know I won't make the mistake again. Code for GPUArrays is ugly anyway; may as well make sure.
Producing Float64 by default also sounds more reasonable than having special cases, and if it sounds reasonable to people with way more experience that myself, I'm closing this.

Thanks.
