### ISSUE TITLE
Bug in distributed garbage collection of Futures

### ISSUE THREAD

**Issue by Pbellive** [JuliaLang/julia#25847]
Hi,
      Please see the [discussion of this issue on discourse](https://discourse.julialang.org/t/understanding-distributed-memory-garbage-collection/8726) for a more detailed explanation. I'm grateful to @amitmurthy for his quick response to my original Discourse post. Here's a shorter description of the bug, including the same MWE as on Discourse:

We have a master function that manages a parallel computation in which subproblem computations are performed on remote worker processes and the results are collected on the master process. There can be more than one subproblem per worker. There is some input data on the master process needed by all subproblems. The master process communicates this data once to each worker. When this is implemented as in the MWE below the input arrays passed to the workers seem to never be garbage collected and the memory used by the program increases until the system runs out of memory and the program crashes. This "memory leak" occurs only when there are multiple Julia worker processes and there is more than one subproblem per worker. The code needed to reproduce this is:
```
function workerFunction( sigmaRef::Future )

   sigma = fetch(sigmaRef)
   println(sum(sigma))

   return true
end

function leakingMasterFunction( n1::Int, n2::Int )

   sigma      = ones(n1)
   nw         = nworkers()
   workerList = workers()
   sigmaRef   = Array{Future}(nw)
   
   @sync begin
       for i in 1:nw
           p = workerList[i]
           @async begin

              sigmaRef[i] = remotecall_wait(identity,p,sigma)
              
              for idx = 1:n2
                 b = remotecall_fetch(workerFunction,p,sigmaRef[i])
              end  # idx

           end  # @async begin
       end  # p
   end  # @sync begin

end  # func
```
Assuming we've launched Julia with two or more workers and loaded the above functions, executing the following from the REPL with two or more subproblems per workers (`nPerWorker >= 2`) causes the memory used by Julia to increase until the system runs out of memory and the code crashes with an out of memory error
```
> nPerWorker = 2
> while true; masterFunction( 5000000 , nPerWorker); end
```
With `nPerWorker = 1` The infinite loop continues to run forever with relatively constant memory usage. This behaviour has been confirmed by my colleagues on OS X and Linux with Julia versions 0.6.1 and 0.6.2. as well as by @amitmurthy on 0.6.2. I've also confirmed that it exists on Linux on master:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.3677
Commit ecb8b56075 (2018-02-01 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
@amitmurthy suggested a workaround on Discourse, which he tested on 0.6.2. I've confirmed that his workaround also works on master at the commit in the above versioninfo dump.

**Comment by jingpengw** [comment]
FYI, this simple code modified from documentation can also reproduce the memory leak issue.
```julia
function worker()
    a = rand(1024,1024)
    svd(a)
    gc()
end
pmap(x->worker(), 1:10000);
```
tested in julia 0.6.2

**Comment by amitmurthy** [comment]
@jingpengw , I couldn't detect a leak on 0.6.2 (OSX) for the code snippet you have posted. Can you provide some more information?

**Comment by jingpengw** [comment]
@amitmurthy you are right, I double checked in Mac and Ubuntu 14.04, I can not reproduce it!
