### ISSUE TITLE
Keyword argument containers are not named tuples

### ISSUE THREAD

**Issue by traktofon** [JuliaLang/julia#25875]
I'm probably misunderstanding something, but the current NEWS.md for julia-0.7 says, under "new language features":

> * Named tuples, with the syntax (a=1, b=2). These behave very similarly to tuples, except components can also be accessed by name using dot syntax t.a [...]
> * Keyword argument containers (kw in f(; kw...)) are now named tuples. [...]

But when I define a function that returns its keyword argument container `kw`, the returned object is not a named tuple:

```julia
# named tuples do work
julia> t = (x=1, y=2)
(x = 1, y = 2)

julia> t.x
1

# getting myself a keyword argument container
julia> f(;kw...) = kw
f (generic function with 1 method)

julia> t = f(x=1, y=2)
pairs(::NamedTuple) with 2 entries:
  :x => 1
  :y => 2

# can't access with the dot-syntax
julia> t.x
ERROR: type Pairs has no field x
Stacktrace:
 [1] getproperty(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol,Symbol},NamedTuple{(:x, :y),Tuple{Int64,Int64}}}, ::Symbol) at ./sysimg.jl:8
 [2] top-level scope

# though by symbol works
julia> t[:x]
1
```

Could the NEWS.md be updated to say what the keyword argument container actually is? Thanks.

Obligatory
```
julia> versioninfo()
Julia Version 0.7.0-DEV.3712
Commit 80abd3dd89 (2018-02-04 03:26 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD Ryzen 5 1600X Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, znver1)
Environment:
```

**Comment by nalimilan** [comment]
See also discussion at https://github.com/JuliaLang/julia/pull/25711.
