### ISSUE TITLE
Implicit cast of *Error to String

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#25882]
In Julia 0.6, after
```
err = nothing;
try
    throw(DomainError());
catch err
end
```
`print(err)` works, but `print("ERROR: " * err)` doesn’t.

Could that be done implicitly, without requiring an explicit `string()` cast every time?

**Comment by ararslan** [comment]
`print` supports multiple arguments, so you can do `print("ERROR: ", err)`.

**Comment by fbruetting** [comment]
Ok, sorry.
