### ISSUE TITLE
Find exact command to reproducibly compile an official release

### ISSUE THREAD

**Issue by skoranne** [JuliaLang/julia#25887]
Can we see the EXACT command line used to build a specific version of Julia, eg, 0.6.2
I am trying to repeat the build and it would be good to have the specific command line.

In particular on ARM v7a architectures I still see Seg fault when compiling 
    JULIA usr/lib/julia/inference.ji
Segmentation fault

**Comment by skoranne** [comment]
Thanks, 
Are the binaries on the Julia website built with 
make
and no special target or system settings ?
(eg if you do gcc -v, you can actually see the full compiler build settings used to compile gcc
and I think it will be useful to keep the build argument with the Julia binary)

**Comment by ararslan** [comment]
Yes, the official Julia binaries are built without any special flags. You can see the machinery used to build the official binaries here: https://github.com/JuliaCI/julia-buildbot/blob/master/master/package.py. Perhaps @staticfloat could fill in any extra information about the exact build process, GCC versions, etc.
