### ISSUE TITLE
HttpParser Build Errors [LoadError: HttpParser not properly installed]

### ISSUE THREAD

**Issue by anirudhmurali** [JuliaLang/julia#25888]
I deployed a Jupyter notebook with Julia 0.6.2 Kernel. Facing a build error with the HttpParser package for the **release: x86_64-pc-linux-gnu**.

![image](https://user-images.githubusercontent.com/3096325/35798073-b6c448ca-0a87-11e8-86b9-728cbeed6a5a.png)

The build is successful on **release: x86_64-apple-darwin14.5.0** (local Mac).

Is the problem with the HttpParser package or the build? TIA.

**Comment by KristofferC** [comment]
It was correct to file an issue at https://github.com/JuliaWeb/HttpParser.jl/issues/81. This is not an issue with the Julia language itself.
