### ISSUE TITLE
Possible parser/docstring bug?

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#25915]
Coverage builds are failing trying to parse the first docstring in `base/operators.jl`. In particular,

```julia
"""
    <:(T1, T2)

Subtype operator: returns `true` if and only if all values of type `T1` are
also of type `T2`.
...
"""
(<:)
```

Put through to the parser gives:
```julia
julia> io = open("base/operators.jl", "r");

julia> Meta.parse(read(io, String), position(io))
ERROR: Base.Meta.ParseError("unexpected \")\"")
Stacktrace:
 [1] #parse#1(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Int64) at ./meta.jl:129
 [2] parse(::String, ::Int64) at ./meta.jl:121
 [3] top-level scope

julia> close(io);
```

Whereas if I change to:

```julia
"""
    <:(T1, T2)

Subtype operator: returns `true` if and only if all values of type `T1` are
also of type `T2`.
...
"""
(<: )
```
Note the extra space ^

then the same REPL parser experiment happily succeeds.

Is this a parser problem? Can anyone else reproduce?

**Comment by ararslan** [comment]
> Can anyone else reproduce?

I can reproduce on current master with both Linux and FreeBSD.

**Comment by JeffBezanson** [comment]
The example code isn't working for me --- `position(io)` is called after reading the whole file, and so returns the position at the end, and I get

```
julia> io = open("base/operators.jl", "r");

julia> Meta.parse(read(io, String), position(io))
(nothing, 18476)
```

**Comment by kshyatt** [comment]
@JeffBezanson weird, when I split this up a little more:
```julia
julia> io = open("base/operators.jl", "r");

julia> position(io)
0

julia> str = read(io, String);

julia> position(io)
18473

julia> Meta.parse(str, 18473)
ERROR: Base.Meta.ParseError("unexpected \")\"")
Stacktrace:
 [1] #parse#1(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Int64) at ./meta.jl:129
 [2] parse(::String, ::Int64) at ./meta.jl:121
 [3] top-level scope
```

**Comment by kshyatt** [comment]
The problem was in Coverage.jl - since `position` is 0-based, and `base/operators.jl` is missing its trailing newline, we needed to pass `position(io) + 1` to `parse`. Not a bug in Julia.
