### ISSUE TITLE
write scripts with julia performance

### ISSUE THREAD

**Issue by eggcaker** [JuliaLang/julia#25921]
I want to start learn julia with write shell scripts.  I have created a simple julia script to run on command line as : 

```
#!/usr/bin/env julia
for x in ARGS; println(x); end
```

when I timing this script 
```
❯ time ./script.jl foo bar
foo
bar
./script.jl foo bar  1.71s user 0.13s system 105% cpu 1.747 total
```

it's normal  or missing some thing?

**Comment by mistguy** [comment]
julia is not suitable for writing computationally inexpensive small scripts since the compiling overhead is significant. Also, https://discourse.julialang.org/ is more appropriate for this kind of discussion.
