### ISSUE TITLE
Proposal: wait/fetch on Task

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#25928]
Right now `wait` has the same meaning for almost everything: wait for something to be available or for something to happen. With `Task`, it means the above _plus_ get a result. For AbstractRemoteRef, this is what `fetch` does. 

I propose moving that functionality of `Task` to `fetch`. Here's what it would look like in 0.7:

```julia
function fetch(t::Task)
    if !istaskdone(t)
        if t.donenotify === nothing
            t.donenotify = Condition()
        end
    end
    while !istaskdone(t)
        wait(t.donenotify)
    end
    if istaskfailed(t)
        throw(t.exception)
    end
    return task_result(t)
end

@deprecate wait(t::Task) fetch(t)
```

and in 1.0:

```julia
function wait(t::Task)
    if !istaskdone(t)
        if t.donenotify === nothing
            t.donenotify = Condition()
        end
    end
    while !istaskdone(t)
        wait(t.donenotify)
    end
    if istaskfailed(t)
        throw(t.exception)
    end
end

function fetch(t::Task)
    wait(t::Task)
    return task_result(t)
end
```

How does this sound?

If this is not accepted I would still like to define `fetch(t::Task) = wait(t)`, as it has a clear meaning and allows `Task`s and `Future`s to be used interchangeably in some cases.

**Comment by iamed2** [comment]
Working on a PR now

**Comment by JeffBezanson** [comment]
Triage accepts.
