### ISSUE TITLE
Nightlies page has old windows installers

### ISSUE THREAD

**Issue by RandomString123** [JuliaLang/julia#25926]
The Windows download from the nightlies page on julialang.org https://julialang.org/downloads/nightlies.html has a version that is now 3 weeks old.  I think the process to get the nightly binaries there is broken.  I noticed this when tests / warnings in my local environment were not matching those produced by travis CI.

**Comment by ararslan** [comment]
There are some unresolved issues with the Windows buildbots. We'll try to get them back up ASAP.

**Comment by staticfloat** [comment]
X-Ref: https://github.com/JuliaLang/julia/issues/25574

**Comment by StephenVavasis** [comment]
For the past two days, I haven't been able to download a Win64 .exe nightly at all (even an outdated one); the link is broken.  Is the broken link a symptom of this same issue?
