### ISSUE TITLE
Brief and extensive docs with `?` and `??`

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#25930]
Most methods have short documentation, but there are a few exceptions. It might be nice to have `??foo` mean something like "print only the first few lines of help for `foo`," basically for experienced users to remind themselves what arguments should be supplied in what order. EDIT: or the opposite, long docs with `??` and short docs with `?`.

Inspired by some extremely thorough (and useful) documentation in https://github.com/JuliaImages/ImageFiltering.jl/pull/54.

**Comment by cormullion** [comment]
Users might expect `?` to give brief, and `??` more copious, information. (Is this similar to `vvv` options for Unix commands?

**Comment by yurivish** [comment]
Brief docs with `?` would be wonderful — I’ve often had to scroll through pages of output at the REPL when I just needed a quick overview. 

Additionally, if the brief display became standard, that would be a good forcing function for the convention of supplying a quick summary sentence at he top of each docstring, which would lend itself well to tooling (e.g. hover a function name in your editor to see a tooltip with the signature and brief description).

**Comment by ChristianKurz** [comment]
If this is implemented, it would be nice to have separate REPL-modes for brief and full help.

E.g. typing `?` would change the prompt to `brief help>` and adding another `?` would change to `help>`.
Additionally, just entering `?` and hitting enter without further text should hint at adding another `?` to show full help.

**Comment by StefanKarpinski** [comment]
I do think that `?` for brief default help and `??` for long help would be good (opened in a pager).

**Comment by mauro3** [comment]
Case in point is the current `Base.getproperty` help, which is cluttered with help about factorizations and the main help is lost somewhere at the top.

**Comment by tpapp** [comment]
> opened in a pager

It would be best if that was customizable, eg for opening nicely formatted HTML in a browser.
