### ISSUE TITLE
build_sysimg breaks permanently if userimg is a symlink

### ISSUE THREAD

**Issue by goerz** [JuliaLang/julia#25931]
It appears that if the userimg-file given to `build_sysimg` cannot be a symlink

    julia>  include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))

    julia>  @time build_sysimg(default_sysimg_path(), "native", joinpath(homedir(), ".userimg.jl"); force=true)
    ERROR: symlink: file already exists (EEXIST)

What is worse is that after this, if I replace `~/.userig.jl` with a proper file, `build_sysimg` will still crash:

    julia>  @time build_sysimg(default_sysimg_path(), "native", joinpath(homedir(), "userimg.jl"); force=true)
    ERROR: open: no such file or directory (ENOENT)

Building the system image still works without the "userimg".

This persists through restarts of Julia. The only thing I've found to get the compilation working again is to completely re-install Julia.

**Comment by KristofferC** [comment]
`build_sysimg` has been deleted.
