### ISSUE TITLE
file stdlib

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#25939]
Might be worth considering a file standard library. As a start, I checked to see how often file functions are used in Base.

I'm consider functions listed in the Filesystem section of the docs and how many times they are used in Base outside of other Filesystem functions. Of the 59 methods, about 2/3 are never used in Base. For the rest of the methods, here's how many total times they were used and in what files

pwd: 4 (client.jl, loading.jl)
cd: 3 (client.jl)
readdir: 1 (loading.jl)
mkpath: 1 (loading.jl)
mtime: 1 (loading.jl)
filesize: 4 (filesystem.jl, iostream.jl, loading.jl, util.jl)
rm: 1 (loading.jl)
isdir: 5 (loading.jl)
isfile: 10 (client.jl, loading.jl, sysimg.jl)
ispath: 2 (loading.jl)
homedir: 3 (client.jl, initidefs.jl, loading.jl)
dirname: 11 (loading.jl, methodshow.jl, sysimg.jl)
basename: 8 (client.jl, loading.jl, logging,, stacktraces.jl)
isabspath: 1 (loading.jl)
joinpath: lots
abspath: lots
normpath: 3 (loading.jl)
realpath: 1 (methodshow.jl)
splitdir: 1 (loading.jl)
splitext: 1 (logging.jl)
@\_\_DIR\_\_: 1 (sysimg.jl)

**Comment by JeffBezanson** [comment]
Triage thinks we can leave this for now.

**Comment by bramtayl** [comment]
What about a stat stdlib?

**Comment by StefanKarpinski** [comment]
`issticky` could be moved somewhere but `isfile` and `isdir` are pretty darned crucial.

**Comment by bramtayl** [comment]
For reference, here's a list of file functions not used in Base (except in other file functions):

walkdir, mkdir, symlink, readlink, chmod, chown, stat, lstat, ctime, filemode, uperm, gperm, operm, cp, download, mv, touch, tempname, tempdir, mktemp, mktempdir, isblockdev, ischardev, isfifo, islink, ismount, issetgid, issetuid, issocket, issticky, @__FILE__, isdirpath, relpath, expanduser, splitdrive
