### ISSUE TITLE
allow JULIA_EDITOR to specify how to pass file and line to an editor

### ISSUE THREAD

**Issue by wlbksy** [JuliaLang/julia#2594]
- `file2` in `function edit(file::String, line::Integer)` need modification

should be `file2 = "$JULIA_HOME/../share/julia/base/$file"`

However, files in `base/linalg/` and `base/pkg/`  cannot be tracked even under this modification.

Should figure out a new way to track all the "*.jl" files.
- On Windows, if user set JULIA_EDITOR something different from `start`  or `notepad`, this function would never deal with it.
  Should add some branch to enable some editors with specific command line syntax , i.e. "notepad++" : `"<bla~bla~bla~>/notepad++ $file -n$line"`

**Comment by mgkuhn** [comment]
I've tried to look for some existing practice of specifying in an environment variable not only the path to another application (e.g., editor, pager, web browser, file explorer) to invoke, but also an entire shell command, including options argument syntax. I couldn't find much so far:

`man --html` or `man -H` on Debian/Ubuntu use the following environment variable:
```
       BROWSER
              If  $BROWSER is set, its value is a colon-delimited list of com‐
              mands, each of which in turn is used  to  try  to  start  a  web
              browser  for  man  --html.  In each command, %s is replaced by a
              filename containing the HTML output from groff, %%  is  replaced
              by a single percent sign (%), and %c is replaced by a colon (:).
```

In the case of starting an editor, there is also the question of how to express what to do in case no line number (or column number) is specified, whether lines or columns start at 0 or 1, etc.

**Comment by mgkuhn** [comment]
A simple alternative to the Julia user specifying in an environment variable how to pass a line (and column) number on to the application `$JULIA_EDITOR` is to simply cause Julia to set two environment variables (e.g., `LINE` and `COLUMN`) when calling `$JULIA_EDITOR`. This way, `$JULIA_EDITOR` can be pointed by the user at a simple shell-script wrapper that does convert `**env` parameters into the `**argv` syntax required by the desired editor.

**Comment by fredrikekre** [comment]
xref https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.define_editor which might be enough to close this?

**Comment by StefanKarpinski** [comment]
Indeed: the set of editors that work can be extended using `define_editor` to handle the case when `JULIA_EDITOR` is set to `notepad++`. If someone wants to add that definition to the set of defaults, that could be done as well.
