### ISSUE TITLE
Run the license header script

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#25952]
A bunch of new files without licenses.

**Comment by martinholters** [comment]
From #25961:

>There's probably gonna be some more changes to Base with Pkg3 and all that so could either rebase this then or just merge this and do it again.

>I'll just do it again before the next release.

So reopening as a reminder.

**Comment by JeffBezanson** [comment]
Fixed by #27328. Other than that, this is part of every release process.
