### ISSUE TITLE
Dependency tree of stdlibs

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#25951]
Below is the dependency graph of our stdlib:

![screen shot 2018-02-08 at 14 29 31](https://user-images.githubusercontent.com/1282691/35975295-843755b2-0cdc-11e8-89ac-471794e9ccd5.png)

There are a few unfortunate dependencies. One for example is the Test --> Distributed --> LinearAlgebra, which means that you cannot use the Test stdlib without having the LinearAlgebra stdlib.
Perhaps some refactorings to avoid this would be useful. Test uses only `myid` from Distributed for example.

Figure created with:

```jl
cd("/Users/kristoffer/julia/stdlib")
import TOML
using LightGraphs
using TikzGraphs
using TikzPictures

const STDLIB_DIR = "."
const STDLIBS = readdir(STDLIB_DIR)
deps = Dict{String, Int}()
for (i, stdlib) in enumerate(STDLIBS)
    deps[stdlib] = i
end
g = LightGraphs.SimpleGraphs.SimpleDiGraph(length(STDLIBS))

for (i, stdlib) in enumerate(STDLIBS)
    proj = TOML.parsefile(joinpath(STDLIB_DIR, stdlib, "Project.toml"))
    if haskey(proj, "deps")
        for (stdlib_dep, uuid) in proj["deps"]
            add_edge!(g, deps[stdlib], deps[stdlib_dep])
        end
    end
end
t = TikzGraphs.plot(g, Layouts.SimpleNecklace(), STDLIBS)
TikzPictures.save(SVG("graph"), t)  
```

**Comment by JeffBezanson** [comment]
Nice, +1 to breaking dependency edges.

Distributed only uses LinearAlgebra in order to call `BLAS.set_num_threads(1)`. That could be replaced with some kind of hook mechanism instead, so all threaded libraries can register callbacks to do the same thing.

Another one I noticed: SharedArrays uses a single sprintf call that could easily be replaced.

**Comment by fredrikekre** [comment]
Updated version of the tree
![graph](https://user-images.githubusercontent.com/11698744/48347926-0b06d680-e680-11e8-8b8d-95df99559d4c.png)

**Comment by StefanKarpinski** [comment]
Is it actually a DAG now?

**Comment by leethargo** [comment]
GraphViz/dot says yes:

![stdlib](https://user-images.githubusercontent.com/43053/48830168-3d958b00-ed74-11e8-95a5-ea827155df57.png)
(see [gist](https://gist.github.com/leethargo/21c12edc29024789b15390b45e9c2f82))

**Comment by KristofferC** [comment]
Nice graph!

**Comment by StefanKarpinski** [comment]
Yes, very nice graph! This dependency graph is starting to look a bit more reasonable.

**Comment by fredrikekre** [comment]
Update after #29978 and #30004 :

![stdlibs](https://user-images.githubusercontent.com/11698744/49635564-7da96e80-fa00-11e8-892b-4ad866daa405.png)

In particular `LinearAlgebra` is not pretty isolated to packages that are actually linalg related and e.g. the package manager is not dependent on `LinearAlgebra` anymore :tada:

**Comment by KristofferC** [comment]
Very good, this looks quite well reasonable.

**Comment by StefanKarpinski** [comment]
Wow, that's such a nice, sane dependency graph now!

**Comment by ViralBShah** [comment]
Close?
