### ISSUE TITLE
mv: rename `remove_destination` keyword to `force`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#25979]
I can never remember this keyword name. It's way too long and this kind of option is almost always called `force` in UNIX commands, which is what we model our file system API on.

**Comment by StefanKarpinski** [comment]
While we're at this, we may want to look at other file API functions and make sure they have consistent keyword names. I.e. `force` and `recursive`.

**Comment by JeffBezanson** [comment]
`cp` also has this argument.

**Comment by turing93** [comment]
I would like to work on this, if it's alright with everyone. 
I am new to the community,so where and how should I start?

**Comment by StefanKarpinski** [comment]
Hi, @turing93. Thanks for the help! First check out

https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md

Keep the advice there in mind. For this particular change, you'll want to add the `force` keyword and keep the old `remove_destination` keyword but change its default to `nothing`. If any value is supplied for `remove_destination` print a deprecation warning (there are various places in the code base that do this, so find one and do something similar) and overwrite the default value of `force` with it. Then change all usages of the functions that you update (`mv` and `cp`). After that run `make testall` and check that all the tests pass. Beware that this can take a long while and use a lot of CPU. You may want to get on the Julia Slack and ask questions in the #my-first-pr channel on there.
