### ISSUE TITLE
Permission of precompiled files

### ISSUE THREAD

**Issue by damhiya** [JuliaLang/julia#25971]
Hello.
I installed julia packages with root privileges at /opt/julia by setting JULIA_PKGDIR=/opt/julia. Permission of the directory is 755.

I executed `using PackageName` as root after installing packages. However, default permissions of the files in /opt/julia/lib/v-0.x is 600. So I have to change these to 644 manually if I want to use packeges as non-root user. Permissions of other files that in /opt/julia/v-0.x is 644.

**Comment by Keno** [comment]
I suspect what we should do here is match the permissions of the package from which we precompiled.
