### ISSUE TITLE
ArgumentError while importing from a module alias

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#25970]
On 0.6.2:
```julia
julia> const It = Base.Iterators
Base.Iterators

julia> import It: product # fine
```
but
```julia
julia> module M
       const It = Base.Iterators
       import It: product
       end
ERROR: ArgumentError: Module It not found in current path.
Run `Pkg.add("It")` to install the It package.
```

On 9-day old master (0f95988141), both result in the ArgumentError. I would expect both to work.

**Comment by JeffBezanson** [comment]
The new behavior is correct. In `import X`, `X` is not evaluated in the current lexical scope, but rather names a top-level package to be found in the load path (and using other package management mechanisms). Previously `Main` was special, in that it was effectively used to cache loaded packages. See #17997.

**Comment by JeffBezanson** [comment]
To look in the current namespace, use `import .It`.

**Comment by tkoolen** [comment]
OK, thanks for the explanation.
