### ISSUE TITLE
should supertype(Foo{...}) return Foo?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#25977]
Currently, `supertype(Foo{...})` returns `supertype(Foo)`, but it would make a lot of sense if it returned `Foo` instead.

(I ran into this recently in #25974, a bug that this would have prevented because `eltype(T)` defaults to `eltype(supertype(T))`.  Not sure what the other implications of the change would be, though.)

**Comment by JeffBezanson** [comment]
No, I don't think so. The intent of it is to move up the hierarchy to the declared parent type. In fact these uses of `supertype` in Base should probably be removed; I think they were only there to work around the lack of triangular dispatch.

**Comment by JeffBezanson** [comment]
Another reason from @vtjnash is that it's helpful for `supertype(::DataType)` to return another `DataType` rather than a UnionAll.
