### ISSUE TITLE
DevDocs Book of Black Magic

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#25988]
An idea that came up on Slack was having a section of the devdocs where people can document tricks they use to work on Base. Everything from how to turn on allocation tracking to the trick @mbauman recently mentioned where he reloads `sysimg.jl` from a working Julia to debug bootstrapping problems, and @keno's trick for loading a second copy of inference and using Revise to work on that plus a second copy of base inferred by that second copy of inference. I'm sure we all have clever tricks that we use that others don't know about or haven't thought of.

Credit to @miguelraz for the awesome name "Book of Black Magic" 😈

**Comment by vtjnash** [comment]
We do not currently name it "the book of black magic", but we have slowly added various sections to the devdocs.
