### ISSUE TITLE
Thread safety of rand and regex

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#26006]
Currently working with `MersenneTwister` and with regular expressions are not thread safe, as both operations manipulate passed object (although many functions using them do not have `!` in their signature and it is not obvious for everyone that they actually modify their arguments).

I recommend to add an appropriate warning in the manual as this can lead to hard to catch bugs in users code.

I can write a PR, but I do not know the details about the plans for threading in 1.0 so I first wanted to ask if this is appropriate.
I recommend to add a new subsection in https://docs.julialang.org/en/latest/manual/parallel-computing/#Multi-Threading-(Experimental)-1 that would list functions in base that are not thread safe. Would this be OK?

**Comment by ViralBShah** [comment]
I think this is a good idea, but we should be clear that the list is not exhaustive.

**Comment by bkamins** [comment]
Agreed. I will start with those two and if something more is identified it should be added.

**Comment by bkamins** [comment]
Closed with #26019
