### ISSUE TITLE
Make _apply use the `append_any` function from its calling module

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#26001]
In the builtin code for `_apply`, we have the following:
```
(jl_function_t*)jl_get_global(jl_top_module, jl_symbol("append_any"));
```
I think it would be better to use `jl_base_relative_to` the module of the caller
to avoid a new top module breaking code in an old top module.

**Comment by JeffBezanson** [comment]
Conceptually I agree, but this would be slower and/or trickier to implement. We haven't done it since having multiple top modules is not formally supported.

**Comment by vtjnash** [comment]
I think we could readily change the lowering to explicitly include the desired `iterate` function itself, if we want to do this: `f(args...)` ==> `(call (core '_apply) (top 'iterate) ,f ,@args)`.

Might need a slightly different name than `Core._apply` (so we put a deprecation shim in place), but thoughts on whether that's an acceptable approach?

**Comment by JeffBezanson** [comment]
Yes that seems like a good approach to me. `_apply` is not exported and lowering is allowed to change, so I think we can change it.
