### ISSUE TITLE
build instructions for windows

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/julia#26010]
Building master on windows I was momentarily stumped by a missing `perl` dependency which is omitted from the [instructions](https://github.com/JuliaLang/julia/blob/master/README.windows.md#cygwin-to-mingw-cross-compiling) for the Cygwin installation. 

Should it be added?

**Comment by ViralBShah** [comment]
Build dependencies mention `perl` in https://github.com/JuliaLang/julia/blob/master/doc/build/build.md
