### ISSUE TITLE
Segmentation faults when running a script

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaLang/julia#26024]
I am experiencing segmentation faults when running a script and submitting their backtraces as gists. Unfortunately, as I am experiencing it with my private package, I cannot make its minimal example. 

Since I am not sure if these two outputs originate from the same issue, I am attaching two backtraces I got.
https://gist.github.com/hayatoikoma/921e51cf5e5954b10c94fadad37eaa0a
https://gist.github.com/hayatoikoma/6f501fc21a3992a0cc402876f91511c6

This is the version info of my Julia.
```
Julia Version 0.6.3-pre.0
Commit 93168a6 (2017-12-18 07:11 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

I hope this information helps improving Julia.

**Comment by StefanKarpinski** [comment]
Hard to diagnose without knowing anything about the code you're running. The backtraces look like you're running ArrayFire / CUDA code, which seems likely to be the source of the segfaults. Perhaps the first step would be to post a full code example on the ArrayFire repo?

**Comment by hayatoikoma** [comment]
Thank you for commenting on it.
Since the segmentation fault happens before the program uses ArrayFire, I didn't think it is from ArrayFire.
I will try to reproduce it with a minimal code example and post it to its corresponding repo.
