### ISSUE TITLE
Pointer hashing breaks equality

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#26038]
```
p0=reinterpret(Ptr{Int8},0)
isequal(p0,C_NULL)
#true 
isequal(hash(p0),hash(C_NULL))
#false 
```
both on 0.62 and current 0.7. 

I feel silly about opening so many small hashing-related issues (and apologize for spamming the tracker); if there is a more appropriate meta-issue for collecting these, could anyone tell me and/or move this to there? [this one is actually not so pathological: using pointers as keys in a dict makes sense; but then they should all be turned into void-pointers for type-stability anyway, at least as long as two pointers of different types to the same address are `isequal`]

**Comment by mbauman** [comment]
```
julia> @which p0 == C_NULL
==(x::Ptr, y::Ptr) in Base at pointer.jl:150

julia> @which hash(p0, UInt(0))
hash(x, h::UInt64) in Base at hashing.jl:23
```

This is effective the same as #12198, but it's really good to audit our codebase for those issues.  This would make for a really easy and good PR, if you're game.
