### ISSUE TITLE
problem with llvm `switch` statement

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#26044]
In the following discourse thread:

https://discourse.julialang.org/t/match-llvm-with-julia-source/9017/5

I describe how my Julia 0.6.2 code that uses `if`...`elseif`...`elseif`...`elseif` ...`else` is compiled to an LLVM `switch` statement that apparently triggers a bug in LLVM, causing my code to crash.  I don't have an MWE; the bug is apparently triggered by a particular alignment of memory addresses of the code.  So I would like to suggest to the developers that the compiler avoid the LLVM `switch` statement until the LLVM problem can be fixed.

**Comment by yuyichao** [comment]
https://reviews.llvm.org/D34409

**Comment by yuyichao** [comment]
And I'm 99% sure that we worked around that on master.

**Comment by yuyichao** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/22451
