### ISSUE TITLE
memory leak of @async and Channel

### ISSUE THREAD

**Issue by jingpengw** [JuliaLang/julia#26077]
could be reproduced with the following code. 
tested in Julia 0.6.1

```
c = Channel{Array}(1)

@sync begin
    for _ in 1:100
        @async put!(c, rand(1024*1024*32))
    end
    @async begin
        for arr in c
             sleep(1)
            @show size(arr)
        end
    end
end
```

**Comment by tanmaykm** [comment]
Did you mean to do this instead?

```
c = Channel{Array}(1)

@sync begin
    @async for _ in 1:100
        put!(c, rand(1024*1024*32))
    end
    @async begin
        for arr in c
             sleep(1)
            @show size(arr)
        end
    end
end
```

**Comment by jingpengw** [comment]
@tanmaykm thanks, your modified code still not work for me. The memory usage keep going up to over 1.3GB.

**Comment by tanmaykm** [comment]
That could be memory waiting for gc.
Maybe try calling `gc()` in the loop? e.g.: `... sleep(1); gc(); ...`.

**Comment by jingpengw** [comment]
the memory usage looks stable until ~1.5 GB in my ubuntu workstation. previous test was done in a small memory laptop.
