### ISSUE TITLE
rename mimewritable -> mimeshowable

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#26082]
The name `mimewritable` stems from the output function being called `writemime`.  Now that `writemime` has been renamed to `show`, maybe `mimewritable` should be renamed to `mimeshowable` or similar.  Not sure what the best name is here.

**Comment by StefanKarpinski** [comment]
`mimeshowable` seems fine to me. Not the catchiest name, but this is a bit of a niche API.

**Comment by JeffBezanson** [comment]
Since this refers to the `show` function, maybe just `showable`?
