### ISSUE TITLE
Bug in broadcast! involving nothing

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#26097]
This is fixed by https://github.com/JuliaLang/julia/pull/25377, but if that doesn't make it into 1.0, this is just a reminder to fix the old code.

From https://github.com/JuliaLang/julia/pull/25377#discussion_r159956996:

```julia
julia> X = Any[1,2]
2-element Array{Any,1}:
 1
 2

julia> X .= missing
2-element Array{Any,1}:
 missing
 missing

julia> X .= nothing
ERROR: MethodError: no method matching _broadcast!(::typeof(identity), ::Array{Any,1})
Closest candidates are:
  _broadcast!(::Any, ::AbstractArray, ::K, ::ID, ::AT, ::BT, ::Val{N}, ::Any) where {K, ID, AT, BT, N} at broadcast.jl:377
  _broadcast!(::Any, ::AbstractArray, ::K, ::ID, ::AT, ::Val{nargs}, ::Any, ::Any, ::Any) where {K, ID, AT, nargs} at broadcast.jl:489
  _broadcast!(::Any, ::Any, ::Any, ::Any...) where N at broadcast.jl:477
  ...
Stacktrace:
 [1] broadcast!(::Function, ::Array{Any,1}, ::Nothing) at ./broadcast.jl:455
 [2] top-level scope
```
and from https://github.com/JuliaLang/julia/pull/24992#issuecomment-366432806:

> I note that now I can't use nothing as the first input for `broadcast` / `broadcast!` as a scalar value. For instance I can do `tuple.([1,2,3], nothing)` but I can't do `tuple.(nothing, [1,2,3])`. This strikes me as odd.

**Comment by mbauman** [comment]
Fixing this requires a change in the broadcast APIs.  It's fixed in https://github.com/JuliaLang/julia/pull/25377#discussion_r159956996.
