### ISSUE TITLE
Need to invoke gc explicitly to collect reassigned local variables.

### ISSUE THREAD

**Issue by bb4242** [JuliaLang/julia#26101]
Hello!

This is also posted on the discussion forum, but hasn't received any replies: https://discourse.julialang.org/t/worker-process-memory-leak/9005

I have a question about garbage collection on worker processes (this is on 0.6.2). I have a long-running function that uses a RemoteChannel to communicate with the master node. This function allocates and frees memory over the course of its operation, but the freed memory doesn’t appear to be reclaimed by the garbage collector, even if `@everywhere gc(true)` is called.

Here’s a simple example. First, define the worker function:

```julia
function worker(channel)

    println("Starting")
    a = 0

    while true
        cmd = take!(channel)

        if cmd == :alloc
            println("Allocating")
            a = zeros(10000, 50000)

        elseif cmd == :free
            println("Freeing")
            a = 0

        elseif cmd == :quit
            println("Quitting")
            return
        end
    end
end
```

Start julia with a worker process (`julia -p 1`), load the function, and start a worker running:

```julia
> @everywhere include("worker.jl")
> c = RemoteChannel(()->Channel(1))
> remote_do(worker, 2, c)
```

Allocate some memory on the worker, and note that the memory usage of the julia worker process (as measured by the operating system, i.e. htop’s RES field) increases by several GB as expected:
```julia
> put!(c, :alloc)
```

Now, let’s try to free the memory:
```julia
> put!(c, :free)
```

The memory usage of the worker process doesn’t go back down. Calling `@everywhere gc(true)` has no effect. However, if we quit the worker process (`> put!(c, :quit)`) and then garbage collect (`@everywhere gc(true)`), the memory usage of the worker process does get collected. This feels like a bug to me, but if I’m not understanding something about how garbage collection is supposed to happen on worker processes, please let me know! :)

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

By the way, thanks to the community for such a great language! Julia is a pleasure to use.

**Comment by bb4242** [comment]
Also, this might be related to #25847

**Comment by amitmurthy** [comment]
On 0.6.2, I can confirm this is an issue. I think is related to when and how variables within long running functions are collected. Not related to distributed gc as such. Unrelated to #25847 .

On 0.7.0, you still need to do an explicit `gc` call, i.e.,
```
        elseif cmd == :free
            println("Freeing")
            a = 0
            gc()
```

Maybe @JeffBezanson or @vtjnash can throw some light on what is happening here?

**Comment by amitmurthy** [comment]
Simpler example of the above without remote invocations.

```
c=Channel(1)
@schedule begin
    a = 0
    while true
        cmd = take!(c)

        if cmd == :alloc
            println("Allocating")
            a = zeros(10000, 50000)

        elseif cmd == :free
            println("Freeing")
            a = 0

        elseif cmd == :quit
            println("Quitting")
            return
        end
    end
end

put!(c, :alloc)
put!(c, :free)
```

The array is not freed till an explicit `gc()` is invoked. Also further allocations,  i.e., `put!(c, :alloc)` does not result in additional memory being locked up.

The issue seems to be similar to https://github.com/JuliaLang/julia/issues/6597

**Comment by hhaensel** [comment]
I had a similar problem and solved it by calling `GC.gc()` without deinstalling and installing any package.
I realised that `LazyArrays` was downgraded during installation of `DifferentialEquations`. Maybe it has to do with that ... ?
