### ISSUE TITLE
subtyping bug with comparing diagonal and triangular tuples

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#26108]
```julia
T, S = Tuple{T, T, Any} where T, Tuple{T, T, Vector{T}} where T
(Tuple{T, T, Any} where T, Tuple{T, T, Array{T, 1}} where T)

julia> S <: T
true
```

However, it's easy to find types (such as `R = Tuple{Int16, Int32, Vector{Any}}`) for which returning `true` here makes inference unsound

**Comment by martinholters** [comment]
And of course (at the risk of pointing out the obvious) this breaks transitivity:
```julia
julia> R<:S<:T
true

julia> R<:T
false
```

**Comment by julbinb** [comment]
Interesting: this looks almost exactly as a _fixed_ transitivity bug [#24166](https://github.com/JuliaLang/julia/issues/24166) I reported earlier. If use `Vector` instead of `Any`, subtype check is correct:

```julia
julia> T1, S1 = Tuple{T, T, Vector} where T, Tuple{T, T, Vector{T}} where T
(Tuple{T,T,Array{T,1} where T} where T, Tuple{T,T,Array{T,1}} where T)

julia> S1 <: T1
false
```
