### ISSUE TITLE
Inconsistent type after vector operations (e.g. +, *) for Vector{Real}

### ISSUE THREAD

**Issue by xukai92** [JuliaLang/julia#26118]
```julia
julia> v = Real[1.0, 2.0]
2-element Array{Real,1}:
 1.0
 2.0

julia> v + v
2-element Array{Float64,1}:
 2.0
 4.0

julia> v * v
2-element Array{Float64,1}:
 1.0
 4.0
```

After operations they are no longer `Array{Real,1}`. Is this intended?

**Comment by elextr** [comment]
Yes, Real is an abstract type so its impossible to perform operations on it, the operation is performed on the underlying concrete type, and so produces a result that is a concrete type.

See [also](https://docs.julialang.org/en/stable/manual/types/#Parametric-Types-1).

**Comment by martinholters** [comment]
Right, this is by design. It used to be different, but that didn't work out too well.
