### ISSUE TITLE
[help wanted] convert date to milliseconds

### ISSUE THREAD

**Issue by anil-k-n** [JuliaLang/julia#26121]
How can I convert date in string format "2018-02-19" (y-m-d) to milliseconds so that I can use it for jcall setDate(long milliseconds)?

**Comment by ViralBShah** [comment]
Please ask this question at discourse.julialang.org. The issues are for bug reports etc.

**Comment by quinnj** [comment]
but while we're here
```julia
julia> Int(Dates.datetime2unix(DateTime("2018-02-19")) * 1000)
1518998400000
```

**Comment by anil-k-n** [comment]
thanks alot @quinnj  that worked!!
