### ISSUE TITLE
Base.LibGit2 test fails, Pkg.update() error

### ISSUE THREAD

**Issue by zhangliye** [JuliaLang/julia#26168]
1. I got the following error when I tried to update the packages. I use `Pkg.checkout(“CSV”)` to get the latest version of CSV.jl. Today, I called Pkg.free(“CSV”). After doing this, I cannot update the packages. (Window 7, pro, 64bit, Julia0.6.2)
![1](https://user-images.githubusercontent.com/8065051/36578958-61c38c7e-189b-11e8-9f10-07a5fedc68fe.PNG)
2. When I run the test of “libgit2”, and the test fails as follows.
`Base.runtests("libgit2")`
![2](https://user-images.githubusercontent.com/8065051/36578987-8b89b952-189b-11e8-91b2-1c4bfa378b58.PNG)
![3](https://user-images.githubusercontent.com/8065051/36579041-ddf39e88-189b-11e8-9457-b362ae37e0ea.PNG)

**Comment by zhangliye** [comment]
According to the explanation by @avik , this could be caused by the dropping support for old cipher suits by Github.([https://discourse.julialang.org/t/pkg-update-error-base-libgit2-test-fails/9272/7](Github dropped support for old cipher suits))
"
> Github dropped support for old cipher suits last night. Apparently our windows MbedTLS builds ask for old versions. Julia on Linux works for 0.6, but fails on 0.5.

Last year we announced the deprecation of several weak cryptographic standards. Then we provided a status update toward the end of last year outlining some changes we’d made to make the transition easier for clients. We quickly approached the...
[https://githubengineering.com/crypto-removal-notice/](url)

> This does look like a critical issue (at least on windows – 0.5 is really really unsupported at this time for linux), and hopefully we’ll come up with a workaround as the day goes by.
"

**Comment by KristofferC** [comment]
The LibGit2 failures seems to have something to do with different line endings `\r\n` vs ` \n` which I don't think is related to the first issue.

**Comment by andreasnoack** [comment]
The first part of this is a dup of https://github.com/JuliaLang/julia/issues/26167 and given that libgit2 has completely changed in 0.6 it is probably not worth keeping this open for the second issue. Please reopen or comment if you disagree.
