### ISSUE TITLE
`isless` for Vector

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#26189]
We have lexicographical `isless` for several list types:

```julia
('a', 'b') < ('c', 'd') #true
"ab" < "cd" #true
```

yet we don't have it for `Vector`:

```julia
['a', 'b'] < ['c', 'd'] # ERROR: MethodError: no method matching isless(::Array{Char,1}, ::Array{Char,1})
```

From a mathematical point of view it might make sense _not_ to have `isless` for vectors, but for general purpose it seems at least consistent to have it. If it's supported in Base, then so will it be in StaticArrays.jl, which is useful (https://github.com/JuliaArrays/StaticArrays.jl/issues/367).

Thoughts?

**Comment by iblis17** [comment]
I prefer to have this feature in https://github.com/JuliaStats/Distances.jl

**Comment by haampie** [comment]
It's not entirely clear to me how distance and order are related; defining `isless(x, y) = dist(x) < dist(y)` doesn't produce a totally ordered set.

**Comment by JeffBezanson** [comment]
This is implemented on master.

**Comment by haampie** [comment]
That's great, sorry for the noise.
