### ISSUE TITLE
Julia/Examples/ndgrid.jl

### ISSUE THREAD

**Issue by skeletonyk** [JuliaLang/julia#26197]
For the function ndgrid.jl inside 'examples', it seems there has been some changes to the function base.repeat which requires a 'inner' and 'outer' input arguments. Maybe we can do something like:

    function meshgrid(vx::AbstractVector{T}, vy::AbstractVector{T}) where T
        m, n = length(vy), length(vx)

        gx = reshape(repeat(vx, inner = m, outer = 1), m, n)
        gy = reshape(repeat(vy, inner = 1, outer = n), m, n)

        return gx, gy
    end

Thanks.

**Comment by StefanKarpinski** [comment]
Thanks for the report. We're planning on deleting the `example` directory anyway, so probably a non-issue at this point.

**Comment by mauro3** [comment]
ref for the move: #26153

**Comment by ViralBShah** [comment]
Moved to: https://github.com/JuliaArchive/Examples
