### ISSUE TITLE
Consider build Julia with multiple system LLVM libraries.

### ISSUE THREAD

**Issue by o01eg** [JuliaLang/julia#26190]
Currently LLVM library name is hardcoded to be `libLLVM` but in some configuration like Gentoo LLVM builds with `BUILD_SHARED_LIBS=ON` so it have a multiple libraries none of them named `libLLVM`.

It causes error while linking which was fixed by with Gentoo's patch for Julia but later it causes error on step `symlink_libLLVM` in `base/Makefile`.

**Comment by ihnorton** [comment]
For the multiple-symbol issue issue see https://github.com/JuliaLang/julia/pull/25597

There is an option to use system LLVM, but it is strongly discouraged because Julia carries a number of functional and bug fix-related LLVM patches.

**Comment by o01eg** [comment]
I have an different issue, not with symbols.
I don't have a system `libLLVM.so` binary. I have multiple binaries libraries `libLLVM*.so` in LLVM's libdir provided by LLVM installation.

**Comment by yuyichao** [comment]
Multiple system (/external) llvm is supported. AFAICT the only issue is https://github.com/JuliaLang/julia/pull/19443, which require patches on mac I believe.

**Comment by inkydragon** [comment]
The llvm library that comes with julia now includes the `-$(MAJOR_VER)jl` suffix,
so it no longer conflicts with the system libraries.

https://github.com/JuliaLang/julia/blob/ea825388134b356210d74b13e75326c7d2b636f1/deps/llvm.mk#L208-L212
