### ISSUE TITLE
Promotion of AbstractString to String

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#26200]
A quick bit of gitarcheology (see below) reveals that the promotion rule for the modern `AbstractString` has evolved from a more primitive soup of `CharStrings`, `ASCIIStrings` and `UTF8Strings`.
Back in the day, this beast was expected to devour all in its path and excrete ~~steaming~~ shiny chunks of UTF8.

In today's world, a range of `AbstractString` subspecies have emerged with specialised characteristics for particular niches: We have a [`SubString`](https://github.com/JuliaLang/julia/blob/f9f11a3102042d53de04ef48a83c713467bbd241/base/strings/substring.jl) that excels at digesting little bites of larger prey; a [`DecodeString`](https://github.com/JuliaLang/julia/blob/6d9fb91e8e7576ac8886a77ecafad9447e8aff41/test/strings/teststringtypes.jl#L76) and a [`LazyJSON.String`](https://github.com/samoconnor/LazyJSON.jl/blob/master/src/AbstractString.jl#L38) that can consume all manner of emoji without choking; a [`RopeString`](https://github.com/JuliaLang/julia/blob/6d9fb91e8e7576ac8886a77ecafad9447e8aff41/test/strings/teststringtypes.jl#L15) that appends but doesn't; an [`IOString`](https://github.com/samoconnor/LazyJSON.jl/blob/master/src/IOStrings.jl) that lets parsers see into the cloud (and someone will surely breed a [`🐮String`](https://en.wikipedia.org/wiki/Copy-on-write) sooner or later).

But, there is a problem with the old `promotion_rule`. It still roams around faithfully doing as it was asked to do, but these days it crushes all the delicate efficiency specialists into ordinary `Base.Strings`.

e.g.
```julia
julia> s1 = "Foo"
julia> s2 = SubString("Bar")

julia> v = [s1, s2] ; typeof(v), typeof(v[1]), typeof(v[2])
(Array{String,1}, String, String)

julia> v = AbstractString[s1, s2] ; typeof(v), typeof(v[1]), typeof(v[2])
(Array{AbstractString,1}, String, SubString{String})
```
I'll post an example that causes a real memory copying overhead issue below.

Here's the `promotion_rule` history...

2018:
https://github.com/JuliaLang/julia/blob/e3b214af7af8c0fdf23195bdb58816d75f555c21/base/strings/basic.jl#L197

2015:
https://github.com/JuliaLang/julia/blob/38c6925ee12d1128cee5444faf7b6799de30b9b3/base/strings/basic.jl#L213

2014:
https://github.com/JuliaLang/julia/blob/f0e86116e4016d7d7367a38057078adf7e12069e/base/string.jl#L817

2012:
https://github.com/JuliaLang/julia/blob/dda65c21367dd641f4ff1085099c17271f2596f3/j/string.j#L361-L363

**Comment by samoconnor** [comment]
```julia
julia> s = String(read("ec2-2016-11-15.normal.json")) ; typeof(s)
String

julia> sizeof(s)
1035940

julia> j = LazyJSON.value(s) ; typeof(j)
LazyJSON.Object{String}

julia> @time ss1 = string(j.operations); typeof(ss1)
  0.000249 seconds (8 allocations: 272 bytes)
SubString{String}

julia> @time ss2 = string(j.shapes); typeof(ss2)
  0.001482 seconds (8 allocations: 272 bytes)
SubString{String}

julia> @time ss3 = j.documentation ; typeof(ss3)
  0.001540 seconds (6 allocations: 224 bytes)
LazyJSON.String{String}
```
Making a vector from these three tiny `AbstractStrings` causes 1000k of allocation:
```julia
julia> @time v = [ss1, ss2, ss3] ; typeof(v)
  0.000180 seconds (11 allocations: 1011.875 KiB)
Array{String,1}
```

Overriding the promotion rule results in only a few hundred bytes of allocation:
```julia
julia> @time v = AbstractString[ss1, ss2, ss3] ; typeof(v)
  0.000008 seconds (5 allocations: 272 bytes)
Array{AbstractString,1}
```

**Comment by samoconnor** [comment]
... work arounds like this are possible:
```julia
Base.promote_rule(::Type{<:SubString}, ::Type{<:AbstractString}) = SubString 
```
But doing that in a package might change the behaviour of someone else's code.

**Comment by nalimilan** [comment]
`SubString` is an abstract type, so that's probably not a good idea for a promotion rule anyway. The idea with promotion is to find a common concrete type which can hold all values. Couldn't you define a promotion rule returning a common type which would allow unwanted allocations (e.g. some kind of `SubString`)?

Could you give more details about the actual use case?

**Comment by samoconnor** [comment]
> SubString [...] not a good idea for a promotion rule

Fair enough, my intention with that was just to be consistent with my original example.
However, something like this might be actually useful:
```julia
Base.promote_rule(::Type{<:SubString{T}}, ::Type{<:T}) = SubString{T}
```

> Could you give more details about the actual use case?

The `ec2-2016-11-15.normal.json` example above shows an example of allocating an extra 1MB due to "promotion" of an efficient string representation to an ordinary `String`.

Another example is in [`SplicedString`](https://github.com/samoconnor/LazyJSON.jl/blob/master/src/SplicedStrings.jl#L24-L26) where I have defined:
```julia
Base.promote_rule(::Type{<:AbstractString},
                  ::Type{<:AbstractString}) = AbstractString
```
With this I get:
```julia
julia> s = LazyJSON.SplicedString("Foo", "Bar", SubString("SS"))
"FooBarSS"

julia> map(typeof, s.v)
3-element Array{DataType,1}:
 String
 String
 SubString{String}
```
Without the rule I get:
```julia
julia> map(typeof, s.v)
3-element Array{DataType,1}:
 String
 String
 String
```

I think this is caused by `mapreduce` applying the promotion rule here:
[`splice_vector(s) = mapreduce(splice_item, vcat, s)`](https://github.com/samoconnor/LazyJSON.jl/blob/master/src/SplicedStrings.jl#L17)

In LazyJSON.jl I've been experimenting with building lazy implementations of `AbstractDict`, `AbstractString` etc. My goal is to be able to slice/dice/combine large strings efficiently using the normal `Base` APIs. e.g. you might have a multi-GB `mmap`-ed text file and create a whole cloud of little reference objects that represent parts of it, or mutations of it. This is all fine until a casual `for x in [s1, s2, s3]` results in three tiny abstract strings being solidified into three huge `String`s.

I want it to work for AbstractString the way it does for AbstractDict where the `Array` type is an abstract type that has parameters compatible with everything in the array. i.e. the items in the array are not converted to a new type.
```julia
julia> v = [IdDict(:a => 1), Dict(:b => 2)]
2-element Array{AbstractDict{Symbol,Int64},1}:
 IdDict(:a=>1)
 Dict(:b=>2)

julia> map(T -> T(:t => T), [Dict, IdDict])
2-element Array{AbstractDict{Symbol,UnionAll},1}:
 Dict(:t=>Dict)
 IdDict(:t=>IdDict)

julia> map(T -> T(:t => T, :foo => 7), [Dict, IdDict])
2-element Array{AbstractDict{Symbol,Any},1}:
 Dict{Symbol,Any}(Pair{Symbol,Any}(:t, Dict),Pair{Symbol,Any}(:foo, 7))
 IdDict{Symbol,Any}(Pair{Symbol,Any}(:foo, 7),Pair{Symbol,Any}(:t, IdDict))

julia> map(x -> x[1](x[2]), zip([Dict, IdDict], [:a => 1, :b => BigFloat(2.0)]))
2-element Array{AbstractDict{Symbol,BigFloat},1}:
 Dict(:a=>1.0)
 IdDict(:b=>2.0)
```

**Comment by StefanKarpinski** [comment]
The main difference is that `String` can represent any valid string value whereas `BigFloat` cannot represent every possible real value. Always converting everything to `SubString` seems pretty questionable – we don't really want a proliferation of substrings everywhere, although of course there are cases where that is what you want.

**Comment by JeffBezanson** [comment]
I could get on board with narrowing this method to specific cases like `String` and `SubString{String}`. In the case of strings, it seems questionable to assume that in `[a, b]` the first priority is to convert `a` and `b` to a common type. As Sam points out, it's easy to encounter cases where that is much less efficient than using an abstract element type and accepting some dynamic dispatches.

**Comment by bkamins** [comment]
The problem is that converting `SubString{String}` to `String` is expensive in some cases (it costs time and possibly memory is a reference to `SubString{String}` is left somewhere).
Ideally would be to get rid of `SubString{String}` (there were such plans in the past if I remember correctly) and we do not have a problem.
Otherwise a union of `SubString{String}` and `String` could be considered (possibly also with `Missing` if it would happen to occur in the vector). Would this be fast given the improvements of performance of unions on 0.7?

**Comment by StefanKarpinski** [comment]
@JeffBezanson and I are in favor of restricting this to types that Base knows about and doing an AbstractString promotion otherwise. @vtjnash wants to keep the behavior as is.

**Comment by samoconnor** [comment]
It would be really nice if there were no default `promotion_rule`s for custom `AbstractString` types.

**Comment by JeffBezanson** [comment]
I'm considering:

```
promote_rule(::Type{SubString{String}}, ::Type{String}) = String # or SubString{String}?
```

We don't think `Union{String,SubString{String}}` is likely to be highly efficient. `String` is generally a better choice for shorter strings. `SubString` is better for really long strings, but would create an extra object for each `String` that needs to be converted to a `SubString{String}`, so could have much more overhead. Overall I would favor `String` in this case, for being simpler and because a `SubString` by its nature is likely to be short, or at least shorter than its parent string.

**Comment by samoconnor** [comment]
I would say `promote_rule(::Type{SubString{String}}, ::Type{String}) = SubString{String}` makes more sense. There is only a tiny overhead in wrapping a `String` with `SubString`, whereas converting an array of mostly `SubStrings` to `Strings` could involve lots of allocation and copying.

Maybe this makes sense:
`promote_rule(::Type{SubString{S}}, ::Type{S}) where S <: AbstractString = SubString{S}`

**Comment by samoconnor** [comment]
I guess it comes down to deciding which use case to assume.

Given that `SubString` is a fixed size thing (a ref and two ints) can it be stored in-line in an array?

Why not have no promotion rule? There is none for `AbstractDict`. If I want all my strings promoted I can write `String[a,b,c,d]`.

**Comment by JeffBezanson** [comment]
Yes, if we're going to return `SubString`, then it probably makes sense to expand it to all kinds of strings, since any string can be converted to a `SubString`.

> converting an array of mostly SubStrings to Strings could involve lots of allocation and copying

True, but often what matters is the final memory size, in which case it can be good to copy out a substring to make it possible to discard the parent string.

**Comment by JeffBezanson** [comment]
I think just removing the string promotion rule is also viable.

**Comment by samoconnor** [comment]
My recent use of `SubString` has involved one large parent string and many substrings that all refer to it. e.g. a HTTP message header with SubString references into fields, or a JSON string with SubStrings for the values. I'm imagining that because SubString is so simple, it will be stack allocated one day.

**Comment by JeffBezanson** [comment]
Triage likes `promote_rule(::Type{SubString{String}}, ::Type{String}) = String`. I feel it's a better default to assume that SubStrings are fairly small, and it's better to end up with less memory footprint than to try to avoid copying. Also, we might merge `SubString{String}` into `String` one day internally. This will not affect JSONStrings, which are free to have their own promotions or none.

**Comment by samoconnor** [comment]
If we're saying that most places that use `SubString` result in fairly short strings, and that these would be more efficiently represented as `String`. Then shouldn't those places just use `String` in the first place?

I think eventually merging the implementation of `String` and `SubString` makes a lot of sense.

Promoting `(SubString, String)` to `String` is a big improvement on the current promotion of `(AbstractString, AbstractString)` to `String`. However, it still seems like we'd have less potential for surprising behaviour if the promotion rule for strings was removed completely.

The problem is that the time and place of application of the promotion rule is kind of magical and hidden from the end user point of view. Lets say I'm finding the next delimiter and making one substring for everything before it and another for everything after it. The remaining part could be large. My code might work nicely with very low memory usage until the day that I use some construct like `map` or an array that invokes the promotion rule. At that point a seemingly innocent code change results in the entire tail of the the input string being copied at every step. After I figured this out I would revert to using indexes or pointers for future string code to avoid "sometimes SubStrings get copied when you don't expect it".

**Comment by samoconnor** [comment]
Another way to look at this is that `SubString` should behave like `SubArray`.
i.e. there is no rule `promote_rule(::Type{SubArray{...}}, ::Type{Array{...}) = Array{...}`

```julia
julia> x = [1,2,3,4]
julia> y = view(x, 2:3)
julia> a = [x, y]
2-element Array{AbstractArray{Int64,1},1}:
 [1, 2, 3, 4]
 [2, 3]

julia> map(typeof, a)
2-element Array{DataType,1}:
 Array{Int64,1}
 SubArray{Int64,1,Array{Int64,1},Tuple{UnitRange{Int64}},true}
```

**Comment by nalimilan** [comment]
> My code might work nicely with very low memory usage until the day that I use some construct like map or an array that invokes the promotion rule.

FWIW, `map` doesn't use promotion, it uses `typejoin`. Only array concatenation does. So that's less of an issue since you can easily specify a more appropriate type if you want.

**Comment by samoconnor** [comment]
> FWIW, map doesn't use promotion

Ok, I didn't know that. I guess my impression that map was involved came from this: https://github.com/JuliaLang/julia/issues/26200#issuecomment-368350007

>  I think this is caused by `mapreduce` applying the promotion rule here:
[`splice_vector(s) = mapreduce(splice_item, vcat, s)`](https://github.com/samoconnor/LazyJSON.jl/blob/master/src/SplicedStrings.jl#L17)

Is guess it is `vcat` that is doing promotion.
