### ISSUE TITLE
Rename/restructure SuiteSparse

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#26210]
It's not great to ask users so run `using SuiteSparse` before they can solve a sparse linear system. Ideally, most users shouldn't need to know what SuiteSparse is in the same way as we don't require them to know about LAPACK to do dense linear algebra. Either, we could make the sparse solvers part of `SparseLinearAlgebra` module or load them as part of the `SparseArrays` module.

**Comment by KristofferC** [comment]
Loading `SuiteSparse` automatically if it exists when loading `SparseArrays` makes sense. We could say that `SutieSparse` is a conditional dependency to `SparseArrays` ;)

**Comment by ViralBShah** [comment]
We should load all the sparse matrix stuff, sparse solvers, eigensolvers with `using LinearAlgebra`.

**Comment by ViralBShah** [comment]
The plan is to move it out of stdlib, so not a matter to be discussed further here.
