### ISSUE TITLE
Crossreference hasmethod <-> applicable in documentation

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#26219]
It was hard to find "What is like `applicable` but works with types?"

**Comment by himanshuladia** [comment]
Hi, I'm new to the community. Can I take this up?

**Comment by StefanKarpinski** [comment]
Yes, this would be a very nice doc improvement to have. Thanks! If you have any questions or problems, there's a #my-first-pr channel on Julia's Slack forum.
