### ISSUE TITLE
Precompiled Module Loading Error

### ISSUE THREAD

**Issue by kris0412** [JuliaLang/julia#26226]
Getting the following error messages:

julia> using MAT
INFO: Precompiling module MAT.
ERROR: LoadError: syntax: extra token "CartesianIndices" after end of expression
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /u/kris/.julia/v0.5/Compat/src/Compat.jl, in expression starting on line 1130
ERROR: LoadError: Failed to precompile Compat to /u/kris/.julia/lib/v0.5/Compat.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /u/kris/.julia/v0.5/HDF5/src/HDF5.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile HDF5 to /u/kris/.julia/lib/v0.5/HDF5.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in include_from_node1(::String) at ./loading.jl:488
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
while loading /u/kris/.julia/v0.5/MAT/src/MAT.jl, in expression starting on line 29
ERROR: Failed to precompile MAT to /u/kris/.julia/lib/v0.5/MAT.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422

**Comment by martinholters** [comment]
Looks like a problem in Compat. Please verify that your Compat.jl is ok and belongs to a Compat version that supports Julia 0.5. If that is the case, you can file an issue at https://github.com/JuliaLang/Compat.jl, but as Julia 0.5 is basically unsupported, changes of having fixed are slim. (That said, Compat is so widely used that I really don't expect it to have a release so broken that it doesn't even load.)

Anyway, does not seem to be a Julia issue (or at least not on current versions).
