### ISSUE TITLE
make ccall sigatomic (defer SIGINT handling)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2622]
Currently, a ctrl-c in the REPL can interrupt a `ccall` to an external library, leaving that library in an inconsistent state and producing crashes or other problems later (see e.g. [PyCall issue #15](https://github.com/stevengj/PyCall.jl/issues/15)).

Julia's C API (`julia.h`) has `SIGATOMIC` macros to protect critical code regions from being interrupted by ctrl-c (`SIGINT`), but these are not easily accessible from Julia.   

Arguably, *every* `ccall` should be made sigatomic by default, on the theory that C code in general is not interrupt-safe (with a separate `interruptable_ccall` for cases that are known to be re-entrant and interrupt-safe). Note that [Python does the same thing](http://docs.python.org/2/library/signal.html).  As noted below, the performance penalty for this is almost certainly negligible under ordinary circumstances.

**Comment by mossr** [comment]
@JeffBezanson is there a way to completely remove signal handling (other than the `//jl_install_sigint_handler` method)? You mentioned a compiler switch, has that been implemented?

Because MATLAB runs on the JVM, if a library installs it's own signal handler then complications can cause MATLAB to crash.

**Comment by stevengj** [comment]
(Note that the `sqrt` function has been inlined for some time, since 244ec92f55bb5433898c5a859a0cb452aafa1673, so `ccall` overhead will no longer affect it.)

**Comment by ViralBShah** [comment]
How do the LLVM intrinsics work? Do they end up calling the system libm, or does LLVM have fast implementations? We have @simonbyrne 's `log` implementation in Julia that is probably the fastest one for now.

**Comment by simonbyrne** [comment]
From what I understand they just call the system libm functions, though they are also able to optimise repeated calls with the same argument (#414, #9942, #10922).

**Comment by stevengj** [comment]
Hooray!
