### ISSUE TITLE
Improve the codegen of objectid

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#26236]
Performance enhancement request: it'd be nice to not have to ccall in order to access the `objectid`.  I'm imagining this to be a similar type of optimization as `pointer` — both use `ccall`s, but the latter emits specialized native code.

**Comment by JeffBezanson** [comment]
`objectid` is a hash, and as such is a fairly involved algorithm. Could your case use `pointer_from_objref` instead?

**Comment by mbauman** [comment]
Absolutely.

**Comment by mbauman** [comment]
#26237
