### ISSUE TITLE
Docs are generated twice on every CI run

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26245]
- Once on `make install` (I think)
- And then once in the end, as an explicit `after_success` step.

That seems like a waste.

**Comment by JeffBezanson** [comment]
There is logic in doc/make.jl to do the deployment step only on x86_64, but (1) it's too late since that check happens after doing the doc build, and (2) deployment is skipped on non-master branches anyway.

This is only on travis, right?

**Comment by KristofferC** [comment]
Yeah, it looks like there is no explicit `make doc deploy` in the other CI files.

**Comment by KristofferC** [comment]
We could put the deploy call behind some env variable like `TRAVIS_BRANCH`, would only double generate on the master branch then.

**Comment by KristofferC** [comment]
I don't think this still happens.
