### ISSUE TITLE
inconsistent return values for `axes` of `SubArray{T,N}`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#26281]
```julia
A = collect(1:10)

v = view(A, [1])
axes(v)  # returns (Base.OneTo(1),)
v.indices  # returns  ([1],)
v0 = view(A, 1)
axes(v0)  # returns () 
v0.indices  # returns (1,)
```
I'm not sure whether this is desired behavior, but it complicates code that attempts to use `axes` for `SubArray` of rank-0 as well as higher ranks.  Is it intended that `v.indices` be used in those cases?

**Comment by mbauman** [comment]
This is very intentional and desired.  `view(A, 1)` is a zero-dimensional array with size `()` and axes `()`.

If you want scalars out of views, the `@views` macro is helpful.

**Comment by ExpandingMan** [comment]
Sorry, I was in fact getting confused about `v.indices`, it's totally different than `axes`.  Nevermind.
