### ISSUE TITLE
convert a code matlab to julia

### ISSUE THREAD

**Issue by imaneamiri** [JuliaLang/julia#26290]
function [y1,y2]=Croisement(ch1,ch2)
%ch1 chromosome 1;
%ch2 chromosome 2;
nVar=numel(ch1);
c=randi([1 nVar-1]);
y1=[ch1(1:c) ch2(c+1:end)]
y2=[ch2(1:c) ch1(c+1:end)]
end
this code done by matlab how can I write it by julia
please I need your help

**Comment by Keno** [comment]
Welcome. This issue tracker is for issues with the julia language itself. Please consider the user forum at discourse.julialang.org or the slack channel for help requests.
