### ISSUE TITLE
custom character literal macros?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#26305]
I wonder if we want to support character literal macros analogous to custom string macros, e.g. `b'x'` as a synonym for `UInt8('x')`.

This would be a breaking change because `b'x'` is currently parsed as `b' * x'`:
```jl
julia> b = 3; x = 7
7

julia> b'x'
21
```

This occurred to me in connection with #26286, e.g. if you want to have custom literals for a new character type.    Also, there is a lot of code that prints individual ASCII bytes to an `io` stream.   To do this efficiently while still supporting streams in different encodings, you'd ideally want an `ASCIIChar` type, and it would be convenient to write this as `a'x'`.  Of course, we could define a custom string literal for this, like `a"x"`, but it would be confusing if that were defined to produce a character.

Not a necessary feature by any means, just wanted to throw it out there since it would be a breaking change.

**Comment by JeffBezanson** [comment]
I think it's better to use string macros for this than to sacrifice `x'y'`.

**Comment by stevengj** [comment]
Okay, I figured it wouldn't be popular.
