### ISSUE TITLE
copy: move to LinearAlgebra?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#26319]
Shouldn't these be in LinearAlgebra? Transpose and Adjoint are...
```
copy(A::Transpose)
copy(A::Adjoint)
```

**Comment by fredrikekre** [comment]
They are in LinearAlgebra:
https://github.com/JuliaLang/julia/blob/f569ebe9bcfdeeae94952d9105c33dbf6b545da7/stdlib/LinearAlgebra/src/transpose.jl#L178-L179

**Comment by PetrKryslUCSD** [comment]
OK, so then only the documentation is out of whack then.

**Comment by PetrKryslUCSD** [comment]
Similarly the function `adjoint()`: listed as `Base.adjoint()` in the docs, but defined under LinearAlgebra.

**Comment by PetrKryslUCSD** [comment]
Oh, maybe I see why: the function is defined in Base, but the method in LinearAlgebra. Is that it?
