### ISSUE TITLE
Overloading ! crashes REPL

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#26311]
e.g. 

```julia
import Base: !
!(x::String) = x
```

**Comment by StefanKarpinski** [comment]
Works fine for me:
```jl
julia> import Base: !

julia> !(x::String) = x
! (generic function with 4 methods)

julia> 1 + 2
3
```
Also, note that overloading Base's functions can and will result in crashes.

**Comment by bramtayl** [comment]
After I run it, the REPL completely freezes for me and I can't type anything else.

```
julia> versioninfo()
Julia Version 0.7.0-DEV.4389
Commit d6edb86bc0* (2018-02-25 21:29 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:
```

**Comment by bramtayl** [comment]
P.S. the actual context I want to use it in is:

```julia
struct True end
struct False end
import Base: !
!(::True) = False()
!(::False) = True()
```

**Comment by KristofferC** [comment]
Works fine here too.

**Comment by bramtayl** [comment]
Maybe fixed since the last nightly binary?

**Comment by JeffBezanson** [comment]
Works for me too. Can reopen if this becomes a problem again.

**Comment by bramtayl** [comment]
So downloaded the new Julia binary and this is still a problem for me. Curiously only a problem when the lines are inside of a package. The offending lines are

```julia
!(::False) = True()
!(::True) = False()
```

If they are inside the TypedBools package, loading TypedBools freezes the repl. If I load TypedBools then run the lines, there is no problem.
