### ISSUE TITLE
Inner type parameter depending on outer type parameter loses the fixed outer parameter information

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#26321]
This problem was originally reported [here](https://discourse.julialang.org/t/strange-behavior-of-arrays-of-unionall-type/9440) in Julia discourse.  The following is a simplified description of the problem through the discussion there.

Consider a parametrized type `MyType` with two type parameters `N` and `S`, where the range of the inner type parameter `S` depends on the outer type parameter `N`:
```julia
julia> VERSION
v"0.7.0-DEV.4465"

julia> struct MyType{N,S<:NTuple{N}}
           t::S
       end
```
Now, create instances of two different `MyType` types—one with a tuple of three `Int64`'s and another with a tuple of three `Float64`'s:
```julia
julia> mi = MyType{3,NTuple{3,Int64}}((1,2,3))
MyType{3,Tuple{Int64,Int64,Int64}}((1, 2, 3))

julia> mf = MyType{3,NTuple{3,Float64}}((1.0,2.0,3.0))
MyType{3,Tuple{Float64,Float64,Float64}}((1.0, 2.0, 3.0))
```
Note that both `mi` and `mf` have the outer type parameter `N = 3`, and therefore their inner type parameter `S` must be subtypes of `NTuple{3}`.  However, the information of `N` in `S` is lost when an inhomogeneous array of `mi` and `mf` is constructed:
```julia
julia> vm = [mi, mf]; typeof(vm)
Array{MyType{3,S} where S<:(Tuple{Vararg{T,N}} where T) where N,1}
```
Notice that the information `N = 3` is correctly passed to the element type `MyType{3,S}` here, but not in `S<:(Tuple{Vararg{T,N}} where T) where N`.  As a result, the following generates an error:
```julia
julia> vm::Vector{<:MyType{3}}
ERROR: TypeError: typeassert: expected Array{#s1,1} where #s1<:(MyType{3,S} where S<:(Tuple{T,T,T} where T)), got Array{MyType{3,S} where S<:(Tuple{Vararg{T,N}} where T) where N,1}
```
even though both `mi` and `mf` are of type `MyType{3}`:
```julia
julia> mi::MyType{3}
MyType{3,Tuple{Int64,Int64,Int64}}((1, 2, 3))

julia> mf::MyType{3}
MyType{3,Tuple{Float64,Float64,Float64}}((1.0, 2.0, 3.0))
```

Is this an expected behavior?

**Comment by JeffBezanson** [comment]
This is the result given by `typejoin`, which is sometimes lazy and gives a wider type than it could. It should be improved in this case: instead of using the original typevar when corresponding parameters don't match, it should use the typevar obtained after substituting values for prior parameters.

**Comment by wsshin** [comment]
Thanks a lot for fixing this issue so quickly!
