### ISSUE TITLE
Suggestion: End*alias*

### ISSUE THREAD

**Issue by iwelch** [JuliaLang/julia#26348]
#define endfor end
#define endwhile end
#define endfunction end
#define endlet end
#define enddo end
#define endif end
#define endstruct end

`julia> open("/etc/passwd","r") do fout;  while (!eof(fout)); endwhile;  enddo
`

* Allows endusers to express intent a little more clearly.  In the future, julialint could check and warn, too, when needed.   Anyone who prefers the plain end can continue to use the plain end.

* Can occasionally make it a little easier to write non-Julia code (e.g. in perl) to parse to the end of a (non-nested) julia expression, though end#function could fulfill the same role here.

``julia> function f() ...many many things that could have ends... endfunction
``

* Some familiarity by shell, latex, and other programmers already, makes entry easier.

* Presumably, no one would use `endif` as a variable, so no meaningful namespace pollution.

**Comment by JeffBezanson** [comment]
I appreciate the suggestion, but this is too large a disruption of our syntax. Making these alternative keywords optional is also undesirable, since it would overall hurt code uniformity and readability.
