### ISSUE TITLE
Functions parenthesis

### ISSUE THREAD

**Issue by christianbender** [JuliaLang/julia#26353]
**Reproduce steps**  

Based on this code  

```julia
function g(x,y)
    return x+y
end

print(f (4,5)) # error!
print(f(4,5)) # ==> 9

```
**julia version 0.4.5**  

---

**Behavior**  

If we write f (...) the interpreter throws an error like:  

```
WARNING: deprecated syntax "f (" at /home/christian/Programmierung/GitHub/julia/test.jl:5.
Use "f(" instead.
ERROR: LoadError: UndefVarError: f not defined
while loading /home/christian/Programmierung/GitHub/julia/test.jl, in expression starting on line 5
```  

---

**Expected**  

In other programming languages the extra whitespace don't throws an error!  For example Python, JavaScript, Octave etc.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/18542, see https://github.com/JuliaLang/julia/issues/7232, https://github.com/JuliaLang/julia/pull/11891

**Comment by JeffBezanson** [comment]
Yes, this is intentional.

**Comment by christianbender** [comment]
@KristofferC @JeffBezanson  Ok, I understand.
