### ISSUE TITLE
Temporaries are not GCed until the function exits

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#26355]
On 0.6, I was tracking down a memory leak in a recursive function, and it came down to this MWE:

```julia
julia> function rec(i)
           if i==0 return end
           finalizer(randn(10000), _->global bbb+=1)
           rec(i-1)
       end
rec (generic function with 1 method)

julia> gc(); bbb = 0; @time(rec(1000)); bbb
  0.075851 seconds (2.00 k allocations: 76.370 MiB, 1.33% gc time)
0
```

AFAICT, the memory from the `randn` call isn't free for GC'ing until `rec` exits, even though it's clearly unaccessible. There's a lot of subtleties around finalizers, so hopefully this demo is correct.  Alternatively, this simpler MWE:

```julia
julia> function rec(i)
           if i==0 return end
           rand(1000000)
           rec(i-1)
       end
rec (generic function with 1 method)

julia> rec(300)
```

Jumps memory usage to ~3 GB on my machine. Shouldn't memory usage be roughly constant?

**Comment by cstjean** [comment]
What I find surprising is that this does not affect non-recursive functions. This code is fine:

```julia
julia> function loop(i)
           for _ in 1:i
              rand(1000000)
           end
       end
loop (generic function with 1 method)

julia> loop(3000)
```

**Comment by yuyichao** [comment]
The GC root allocation on 0.6 is very inefficient and that's not something we can backport.

**Comment by mbauman** [comment]
It's also reproducible on master.

**Comment by yuyichao** [comment]
Which part? If it didn't crash there's basically no problem since you don't want to free memory that fast anyway.

**Comment by vtjnash** [comment]
Not a bug to not free memory before a function returns

**Comment by yuyichao** [comment]
OK it does seems that in this case the cause in the MWE is that we don't clear any GC slots. While there's some version of https://github.com/JuliaLang/julia/pull/24431 that can improve this case we'll never make such a guarantee especially since such optimization can easily cause worse performance and I highly doubt the new cause is what's causing the original issue.
