### ISSUE TITLE
eltype(a::Ref{T}) returning Any

### ISSUE THREAD

**Issue by favba** [JuliaLang/julia#26363]
On Julia 0.7

```julia-repl
julia> a = Ref(3.0)
Base.RefValue{Float64}(3.0)

julia> eltype(a)
Any

julia> versioninfo()
Julia Version 0.7.0-DEV.4390
Commit 79c7bdd9ec (2018-02-26 07:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.4.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 2

```
[This](https://github.com/JuliaLang/julia/blob/f3118ce6a39b1adeac345c6ddd9c46d9f6676316/base/refpointer.jl#L36) definition doesn't work  because:
```
julia> Type{Base.RefValue{Float64}} <: Type{Ref{Float64}}
false
```

On Julia v0.6 this works because of [this](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/array.jl#L46) definition, which doesn't exist on v0.7 anymore.

**Comment by JeffBezanson** [comment]
Quite right, thanks for catching this!
