### ISSUE TITLE
QR-factorization for sparse matrices inconsistent array sizes

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#26368]
This issue is related to #26367
```
help?>qrfact
  qrfact(A) -> QRSparse

  Compute the QR factorization of a sparse matrix A. Fill-reducing row and column permutations are
  used such that F.R = F.Q'*A[F.prow,F.pcol]. The main application of this type is to solve least
  squares or underdetermined problems with \. The function calls the C library SPQR.

 A
2×4 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 2]  =  0.0
  [2, 2]  =  1.0
julia> F = qrfact(A);
julia> F.R == F.Q'*A[F.prow,F.pcol]
false

julia> F.R
1×4 SparseMatrixCSC{Float64,Int64} with 1 stored entry:
  [1, 1]  =  -1.0

julia> F.Q'*A[F.prow,F.pcol]
2×4 SparseMatrixCSC{Float64,Int64} with 1 stored entry:
  [1, 1]  =  -1.0

julia> F.Q * F.R
ERROR: DimensionMismatch("matrix A has dimensions (2,2), matrix B has dimensions (1,4)")
```
The last result is remarkable for a Q-R factorization.

**Comment by andreasnoack** [comment]
I think this is a dup of #26367 but I'll take a closer look later.

**Comment by andreasnoack** [comment]
I've taken a closer look and there are two separate issues here. I'd actually like to blame our upstream vendor in this case here since they have decided to truncate `R` and we are just returning it as it is provided to us. We should probably adjust the size before returning it.

**Comment by KlausC** [comment]
I am going to write a clarification about QR-factorization in discourse. I think, we can do a lot in making the experience for Julia users much better. Link follows when available.
