### ISSUE TITLE
Package Update Behavior

### ISSUE THREAD

**Issue by chelseas** [JuliaLang/julia#26376]
Why does the Pkg.update("SomePackage") command update _anything more_ than the package indicated and its direct dependencies? It seems instead that ALL packages are updated when I call Pkg.update() on a _specific_ package. 

This is a problem for me because I have lots of projects that depend on specific package versions -- but I don't want to go through the trouble to Pkg.pin() all twenty different packages -- I would much prefer to simply install new versions of the specific packages (and direct dependencies) via Pkg.update() and not have to worry about pinning everything else. 

If this is already an option -- I really think this ought to be the default behavior (only updating exactly what is requested).

**Comment by JeffBezanson** [comment]
What version of julia is this?

See #13487; this seems to have been implemented already. The new version of the package manager (Pkg3) should also improve the situation.

**Comment by StefanKarpinski** [comment]
This complaint only applies to the old package manager which we are deleting in 1.0.
