### ISSUE TITLE
Inference breaks as a result of a no-op

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#26402]
As reported in https://discourse.julialang.org/t/inference-breaks-as-a-result-of-a-simple-no-op/9624, the output of the following MWE, and many variations of it, are not inferred if we uncomment the no-op in the first line of `test`. 
```
struct Bar{L}
    nt::NTuple{L,Int}
end

function test(bar::Bar{L}) where {L}
    # true && nothing
    v = rand(-5:5, L)
    r = ntuple(k -> v[k], Val(L))
    return r
end
```  
The return type of `test` with the no-op becomes `NTuple{L, Any}` instead of `NTuple{L, Int}`. The failed inference is not inconsequential, and the performance goes from 89ns (1 alloc) to 427 ns (4 allocs). 
The same problem happens with other types of no-ops, such as `if true; nothing; end`. The failure seems to require a conditional no-op. Removing either of the other two lines also makes the problem go away.

(The issue came up in real code, the above is just an minimal reduction of the issue)

[EDIT: The problem happens both in `0.7.0-DEV.4055` and in v0.6.2, so it is probably old]

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276

**Comment by KristofferC** [comment]
Could you give an explanation how it is a dup? The extra statement seems to be completely separated from any of the closures, so why is it interfering?

**Comment by yuyichao** [comment]
It's pretty clear if you look at the inferred code. And there is a closure.

**Comment by KristofferC** [comment]
I know there is a clousre, I was wondering why `true && nothing` which is not a closure would interfere.

The inferred codes are:

```
julia> @code_warntype test(Bar((1,2,3,4)))
Body:
  begin
      Core.SSAValue(12) = $(Expr(:new, UnitRange{Int64}, -5, 5))
      Core.SSAValue(31) = $(Expr(:foreigncall, :(:jl_alloc_array_1d), Array{Int64,1}, svec(Any, Int64), :(:ccall), 2, Array{Int64,1}, 4, 4))
      Core.SSAValue(22) = $(Expr(:invoke, MethodInstance for rand!(::Random.MersenneTwister, ::Array{Int64,1}, ::UnitRange{Int64}), :(Random.rand!), :(Random.GLOBAL_RNG), Core.SSAValue(31), Core.SSAValue(12)))::Array{Int64,1}
      Core.SSAValue(38) = (Base.arrayref)(true, Core.SSAValue(22), 1)::Int64
      Core.SSAValue(41) = (Base.arrayref)(true, Core.SSAValue(22), 2)::Int64
      Core.SSAValue(44) = (Base.arrayref)(true, Core.SSAValue(22), 3)::Int64
      Core.SSAValue(47) = (Base.arrayref)(true, Core.SSAValue(22), 4)::Int64
      Core.SSAValue(35) = (Base.tuple)(Core.SSAValue(38), Core.SSAValue(41), Core.SSAValue(44), Core.SSAValue(47))::NTuple{4,Int64}
      return Core.SSAValue(35)
  end::NTuple{4,Int64}


julia> @code_warntype test(Bar((1,2,3,4)))
Body:
  begin
      Core.SSAValue(4) = $(Expr(:new, :(Core.Box)))
      Core.SSAValue(11) = $(Expr(:new, UnitRange{Int64}, -5, 5))
      Core.SSAValue(30) = $(Expr(:foreigncall, :(:jl_alloc_array_1d), Array{Int64,1}, svec(Any, Int64), :(:ccall), 2, Array{Int64,1}, 4, 4))
      Core.SSAValue(21) = $(Expr(:invoke, MethodInstance for rand!(::Random.MersenneTwister, ::Array{Int64,1}, ::UnitRange{Int64}), :(Random.rand!), :(Random.GLOBAL_RNG), Core.SSAValue(30), Core.SSAValue(11)))::Array{Int64,1}
      (Core.setfield!)(Core.SSAValue(4), :contents, Core.SSAValue(21))::Array{Int64,1}
      t_1::Any = $(Expr(:invoke, MethodInstance for (::getfield(Main, Symbol("##9#10")))(::Int64), :(#9), 1))::Any
      t_2::Any = $(Expr(:invoke, MethodInstance for (::getfield(Main, Symbol("##9#10")))(::Int64), :(#9), 2))::Any
      t_3::Any = $(Expr(:invoke, MethodInstance for (::getfield(Main, Symbol("##9#10")))(::Int64), :(#9), 3))::Any
      t_4::Any = $(Expr(:invoke, MethodInstance for (::getfield(Main, Symbol("##9#10")))(::Int64), :(#9), 4))::Any
      Core.SSAValue(34) = (Base.tuple)(t_1::Any, t_2::Any, t_3::Any, t_4::Any)::NTuple{4,Any}
      return Core.SSAValue(34)
  end::NTuple{4,Any}
```

respectively.

So why is `true && nothing` forcing putting `v` into a `Box`?

**Comment by yuyichao** [comment]
That's exactly what #15276 is about.

**Comment by pablosanjose** [comment]
I see! Should I post the MWE in the #15276 issue, or is it not really helpful?

**Comment by pablosanjose** [comment]
(By the way, what would be the `let` workaround in this case? It might be useful for my real-world code)

**Comment by KristofferC** [comment]
First comment by Jeff of #15276 is "This is due to that line capturing `prepad` in a closure." and the line in question is 

```
indexesK = ntuple(d->[size(krn,d)-prepad[d]+1:size(krn,d);1:size(kern,d)-prepad[d]], N)::NTuple{N,Vector{Int}}
```

So it doesn't look the same to me.

**Comment by yuyichao** [comment]
> or is it not really helpful?

There has actually been quite a few cases that are exactly the same posted there already.

>  what would be the let workaround in this case?

Around that closure line `ntuple(k -> v[k], Val(L))` or in this case just move the `v = ` assignment onto the let should work.

**Comment by pablosanjose** [comment]
You're right! The example here has actually the same structure of the one in [this comment](https://github.com/JuliaLang/julia/issues/15276#issuecomment-363465182) of #15276. Thanks @yuyichao for pointing it out! Also, the `let` workaround indeed works, so it does seem that this is a dup, although I also don't understand the role of the `true && nothing` line in the whole business.
