### ISSUE TITLE
deprecate `isreal(::AbstractArray)`?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#26401]
In 0.6 we deprecated `isinteger(a::AbstractArray)` to `all(isinteger, a)`. However we still have such a method for `isreal`.

If `any` and `all` had inbounds annotations, then we would be able to optimize these to constants.

**Comment by ararslan** [comment]
I believe that was discussed somewhere and IIRC @stevengj was against that change for mathematical reasons.

**Comment by ararslan** [comment]
Ah https://github.com/JuliaLang/julia/pull/19996

**Comment by JeffBezanson** [comment]
Oh, ok. Then perhaps this release is converging after all :)

**Comment by stevengj** [comment]
Yes, I still feel the same way.

**Comment by nalimilan** [comment]
Don't the same linear algebra considerations apply to both `isreal` and `isinteger`? I.e. shouldn't we deprecate both or none of them?

**Comment by stevengj** [comment]
@nalimilan, no.  You wouldn't say that `[1,2,3]` "is an integer".  You *would* say that it "is real".   There is a well defined, standard, sense in which operations like `real` and `conj` apply to vectors.
