### ISSUE TITLE
String promotion rules

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#26409]
Current promotion rules for `AbstractString` have the following consequences:

```
julia> x = "1234"
"1234"

julia> y = SubString("1234", 3)
"34"

julia> [x, y]
2-element Array{String,1}:
 "1234"
 "34"
```
Similarly for `hcat` or `vcat`.

Is this intended? For numbers such conversions (`Bool` => `Int` or `Int` => `Float64`) are cheap, but for strings they are potentially expensive.

**Comment by JeffBezanson** [comment]
See #26200. For combinations of e.g. `String` and `SubString{String}` the extra type information might be worth it, but certainly not for arbitrary combinations of strings.
