### ISSUE TITLE
Incorrect ambiguity error

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#26428]
IIUC this call should trigger and ambiguity error, yet it doesn't:
```julia
f(A::Array{T, N}, v::String, i::Int) where {T, N} = 1
f(A::Array{T, N}, v::String, I::Vararg{Int, N}) where {T, N} = 2
f([1], "a", 1)
```

At https://github.com/JuliaData/CSV.jl/issues/142#issuecomment-372168989, some users reported that a similar method triggered ambiguity errors but only after loading Plots or DiffEqBase.

**Comment by JeffBezanson** [comment]
It's possible this was fixed by #25832

**Comment by nalimilan** [comment]
Why "was"?

**Comment by JeffBezanson** [comment]
Because that PR is already on master, and I had the impression the linked issue has only been test on 0.6.x.

**Comment by mbauman** [comment]
Ah, so is it the case that `f` in the MWE above should never be getting flagged as ambiguous?  Is the rule that matching a type-parameter across multiple arguments is strictly more specific than the equivalent method without the matching type-parameter?  I had been thinking they were equivalent, but I think I've been bitten by exactly this bug on 0.6 myself.

**Comment by nalimilan** [comment]
> Because that PR is already on master, and I had the impression the linked issue has only been tested on 0.6.x.

Ah, no, sorry, it's both on master and on 0.6.2.

**Comment by JeffBezanson** [comment]
@mbauman Yes, the second method is considered more specific. If adding another method causes an ambiguity error though, it probably means there's a non-transitivity lurking somewhere.

**Comment by nalimilan** [comment]
> If adding another method causes an ambiguity error though, it probably means there's a non-transitivity lurking somewhere.

Yet `using Plots` does not add any `setindex!` method for `WeakRefStringArray`.

I've been able to reproduce the problem locally once, but after loading one by one all Plots.jl dependencies, it disappeared. :-/ I couldn't test on 0.7 since the package doesn't load there.

**Comment by nalimilan** [comment]
Good news: I've been able to reproduce this on 0.6.3, but after backporting https://github.com/JuliaLang/julia/pull/25832 the problem no longer happens. So looks like it should be fixed on master even if we can't confirm it until packages have been ported.
