### ISSUE TITLE
Check isdir(dest) and copy into that directory in cp and friends?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#26423]
Should we check if `"dest"` is a directory, and if so, copy `"src"` to that directory?
```julia
julia> mkdir("dest"); touch("src"); cp("src", "dest")
ERROR: ArgumentError: 'dest' exists. `force=true` is required to remove 'dest' before copying.
Stacktrace:
 [1] #checkfor_mv_cp_cptree#10(::Bool, ::Function, ::String, ::String, ::String) at ./file.jl:191
 [2] #checkfor_mv_cp_cptree at ./<missing>:0 [inlined]
 [3] #cp#12(::Bool, ::Bool, ::Nothing, ::Function, ::String, ::String) at ./file.jl:241
 [4] cp(::String, ::String) at ./file.jl:236
 [5] top-level scope
```
Compare e.g. with
```
fredrik@fredrik-laptop:~$ mkdir dest && touch src && cp src dest && ls dest
src
```

**Comment by KristofferC** [comment]
Adding triage since this changes behavior and probably needs to be decided before 1.0.

**Comment by nalimilan** [comment]
What do other languages do? I would think it's reasonable to be stricter in a programming language than in the shell, which allows catching potential mistakes.

**Comment by fredrikekre** [comment]
Just noting also that the current behaviour is not very useful; it is unlikely that you want to replace a folder with a file which is the result of setting `force = true` in the call.

**Comment by mbauman** [comment]
Python has both [`copyfile`](https://docs.python.org/3/library/shutil.html#shutil.copyfile) (with our current semantics) and [`copy`](https://docs.python.org/3/library/shutil.html#shutil.copy) (which supports directory targets).  Ruby is similar with [`copy_file`](https://ruby-doc.org/stdlib-2.5.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-copy_file) and [`cp`](https://ruby-doc.org/stdlib-2.5.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-cp).

**Comment by martinholters** [comment]
Would `cp(src, into=dir)` be a good API here?

**Comment by JeffBezanson** [comment]
I think changing this would be worse in terms of orthogonality --- if you actually want the logic "if this is a directory then copy into it", then you should write that. Conditional behavior should not be built into the library function itself.

**Comment by stevengj** [comment]
`cp(src, into=dir)` doesn't seem that much better than `cp(src, joinpath(dir, src))`
