### ISSUE TITLE
bits function for BigFloat

### ISSUE THREAD

**Issue by milankl** [JuliaLang/julia#26441]
Is it possible to implement the bits function also for BigFloats?
```
julia> bits(12345.0)
"0100000011001000000111001000000000000000000000000000000000000000"

julia> bits(BigFloat("12345.0"))
ERROR: MethodError: no method matching bits(::BigFloat)```

**Comment by antoine-levitt** [comment]
I don't think so, because BigFloats are not implemented as primitive types:

```
julia> isbits(BigFloat)
false
```

**Comment by yuyichao** [comment]
Being a primitive type isn't the issue, a struct can also have `bits` if it's useful. However, `BigFloat` does not have a canonical bit representation so there's nothing we can implement.

**Comment by milankl** [comment]
How would you extract the value of the exponent and the fraction then? Is there a way to obtain this information of a given BigFloat in what format ever?

**Comment by yuyichao** [comment]
`bits` is not the right function to do that for any type. Please use discourse for further questions.
