### ISSUE TITLE
Make PETSc solvers available

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2645]
Rather than rolling our own sparse-matrix library, it seems like it would be much better to use [PETSc](http://www.mcs.anl.gov/petsc/), which is the de-facto standard here.

PETSc would give us access to a huge number of sparse-direct back-ends (#2632), iterative solvers, sparse eigensolvers (#1573) via the [SLEPc](http://www.grycap.upv.es/slepc/) library, optimized implementations (#942), multiple output formats, and parallel support (currently completely missing and quite nontrivial to implement well).

Re-inventing the wheel here is a little like rewriting LAPACK.

**Comment by jiahao** [comment]
@JaredCrean2 and @stevengj have started work on [PETSc.jl](https://github.com/JaredCrean2/PETSc.jl), so let's move further discussion over there. `PETSc.jl` still needs a lot of work since PETSc is such a massive library, and we can use all the help we can get!

**Comment by stevengj** [comment]
Note that PETSc.jl seems to be progressing nicely.   @JaredCrean2 and @ihnorton put together auto-generated Clang wrappers of the entire PETSc API, so the low-level C API is completely wrapped and available, and we are slowly progressing towards a nicer high-level API built on top of that.

Also note that we are wrapping/linking the double, single, and complex-double versions of PETSc simultaneously, so that you don't need to recompile to switch precisions or from real to complex.

**Comment by BarrySmith** [comment]
> On Nov 18, 2015, at 11:51 AM, Steven G. Johnson <notifications@github.com> wrote:
> 
> Note that PETSc.jl seems to be progressing nicely. @JaredCrean2 and @ihnorton put together auto-generated Clang wrappers of the entire PETSc API, so the low-level C API is completely wrapped and available, and we are slowly progressing towards a nicer high-level API built on top of that.
> 
> Also note that we are wrapping/linking the double, single, and complex-double versions of PETSc simultaneously, so that you don't need to recompile to switch precisions or from real to complex.

   Nice, how are you managing the fact that in our C code we use the same symbol for, for example, VecAXPY() independent of he data type. Are you somehow automatically mapping to different symbols? Maybe we should use that same technology of PETSc as well?

   Does this mean I can remove the small amount of .jl code I put in PETSc a few years ago as a test prototype?

   Barry

**Comment by JaredCrean2** [comment]
Hello Barry,
    We build 3 versions of Petsc, and add a static parameter to all the Julia objects that is the datatype of the library they belong to.  Multiple dispatch does the rest for us.  We do have to run the auto-generation process 3 times, generating 3 versions of the low level wrappers.

    I think its safe to remove the .jl code in Petsc at this point.

**Comment by tkelman** [comment]
> the small amount of .jl code I put in PETSc a few years ago as a test prototype

Fun fact: that little bit of code was the first place I ever heard of Julia. I didn't actually start using it for another 1.5-2 years, but oh well.

**Comment by stevengj** [comment]
@BarrySmith, to clarify, when you call a C function in Julia, you do supply *both* the symbol *and* the library name, via `ccall((symbol,libname), ....args...)`.   So, there is no obstacle to calling the same symbol for functions in different shared libraries (here, 3 different Petsc libraries).

The analogous thing in C would be to `dlopen` all three Petsc libraries, call `dlsym` to lookup a symbol in the desired library, and call the function via that function pointer.
