### ISSUE TITLE
Build failure on armv7-l: "Stack layout invariants violated."

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#26473]
@staticfloat recently turned the buildbots for armv7-l back on, but the compilation currently fails with:

```
In file included from /buildworker/worker/package_linuxarmv7l/build/src/interpreter.c:9:0:
/buildworker/worker/package_linuxarmv7l/build/src/julia_internal.h:41:29: error: static assertion failed: "Stack layout invariants violated."
 #      define static_assert _Static_assert
                             ^
/buildworker/worker/package_linuxarmv7l/build/src/interpreter-stacktrace.c:263:1: note: in expansion of macro 'static_assert'
 static_assert(sizeof(interpreter_state) <= MAX_INTERP_STATE_SIZE,
 ^~~~~~~~~~~~~
make[1]: *** [interpreter.o] Error 1
```
https://build.julialang.org/#/builders/4/builds/797

This might a configuration issue of the buildbots, but maybe @yuyichao knows what is going on here.

**Comment by staticfloat** [comment]
An important detail here is that this is running inside of qemu on an x86_64 machine, while waiting for @yuyichao to figure out why the armv7l buildbot went offline. :)

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/commit/8345b783993a61ba0e2865e11c51538ebf4d6237 makes the struct bigger so the size is too big for the asm code.... Just increase the `MAX_INTERP_STATE_SIZE` def a few lines above should work. I think we align the stack in the asm code even though it's not required so we can just increase the size by 16 everytime or in another word make it 48 for now.
