### ISSUE TITLE
Better error messages for code loading

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26472]
The current error message:

```
ERROR: ArgumentError: Module dfsohgfdg not found in current path.
Run `Pkg.add("dfsohgfdg")` to install the dfsohgfdg package.
```

is not very good. `current path` doesn't make sense, `Pkg.add` might not be the solution, it doesn't distinguish between the "identify"- and `"location" phase etc.

We should probably thread something through code loading that keeps track of where we looked for stuff so that we can give a good error message.

@StefanKarpinski

**Comment by polytomous** [comment]
I'm eagerly awaiting some more progress on this item. (It's *very* relevant to my interests)
I tossed two small comments on the latest commit here: https://github.com/JuliaLang/julia/commit/8e34ee9768d07b5e1122555ba408933a8ba68aaa
