### ISSUE TITLE
Casual language construct in documentation

### ISSUE THREAD

**Issue by sambitdash** [JuliaLang/julia#26485]
`and can cause especial headaches with Arrays:`

[Numeric Comparisons](https://docs.julialang.org/en/stable/manual/mathematical-operations/#Numeric-Comparisons-1)

A formal language will be better for the product documentation.

**Comment by fredrikekre** [comment]
PR's improving the documentation is welcome, but I don't think it is very useful with issues pointing to specific sentences.

Personally I like that the manual is, what you call, "casual" and I would be sad to se that go.

**Comment by sambitdash** [comment]
@StefanKarpinski you may want to review the specific sentence.

**Comment by StefanKarpinski** [comment]
I'm fine with it.

**Comment by StefanKarpinski** [comment]
As Fredrick said, feel free to make a PR to improve it.
