### ISSUE TITLE
Document SubstitutionString

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#26497]
This has been noted [on StackOverflow](https://stackoverflow.com/questions/49276960/replace-with-captured-group-in-julia). The `replace` docstring mentions `SubstitutionString`, but this type is not exported, not documented, and there's no example. Only the manual explains its use, and without mentioning the type.

We should probably add:
- a docstring for `SubstitutionString`
- a link from `replace` to the above docstring
- examples of use

Maybe the type should be exported too?

**Comment by digital-carver** [comment]
Hi @nalimilan , I've added some docs and made a pull request (#27134), could you take a look and let me know if it fits the bill?
