### ISSUE TITLE
Remove contrib/vagrant?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#26492]
Is `contrib/vagrant` used by anyone? Seems to be based on a much older version of julia and is using system libs. Seems best to remove it altogether or move it to a different repo.

**Comment by ViralBShah** [comment]
In fact most of the things in `contrib` are essentially for building or should be removed. It should probably be renamed to `build`. Most unused stuff seems gone.

**Comment by StefanKarpinski** [comment]
How about `tools` instead of `build` – `build` seems suggestive of the wrong thing.

**Comment by musm** [comment]
I'd support renaming `contrib` to something else, it's a name I never understood. Does anyone know what `contrib` is supposed to stand for?

**Comment by ViralBShah** [comment]
To answer the old question - many open source projects have `contrib` for contributed code. This made sense when there was only one Julia repo and all contributions used to end up in here. Anyways, it no longer makes sense, but changing it has to be done carefully, since a lot of build tooling lives in there.

`vagrant` is no more. So closing.
