### ISSUE TITLE
umfpack library issue on mac os travis

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#26499]
E.g. https://travis-ci.org/JuliaLang/julia/jobs/354433461

**Comment by ararslan** [comment]
Looks like [Travis is using repackage_system_suitesparse4](https://github.com/JuliaLang/julia/blob/master/.travis.yml#L102), which was removed without a PR in https://github.com/JuliaLang/julia/commit/1b099846879a02cd4c9884f33f690e6813f1415f.

**Comment by StefanKarpinski** [comment]
@ViralBShah, this is how you get ants!

**Comment by KristofferC** [comment]
Like... Can we just not do that...

**Comment by ViralBShah** [comment]
Sorry about that. I could never imagine that is where we might be using it. :-(

**Comment by ViralBShah** [comment]
Not relevant, but we could just move suitesparse and arpack out of stdlib into packages, now that BinaryBuilder seems to be working.
