### ISSUE TITLE
 git error(code : ecertificate, class:os, user cancelled certificate check: )

### ISSUE THREAD

**Issue by ldpontes** [JuliaLang/julia#26490]
Some help with this error?
I can't execute the command Pkg.add("JuMP")
Win7 64bits
Thanks :+1:

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/errors-for-git-pkg/9351


https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in
