### ISSUE TITLE
Precompilation as a part of the release process

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26503]
[The precompile statements](https://github.com/JuliaLang/julia/blob/master/base/precompile.jl) are there to generate machine-code that is put in the sysimg to reduce latency when starting Julia and doing common operations. It includes initializations of different modules and functions that happen to get precompiled from standard REPL usage.

As we know, Julia provides fast anonymous functions. By letting each function have its own type we can generate specialized code when functions are passed as arguments.

However, any use of an anonymous function is filtered away in the precompilation list. This is because the names of the anonymous function changes as code develop and the precompile statements become stale quickly. AFAIU the names might be different on different architectures as well.

This means that any code that uses anonymous functions is currently not precompiled. Anonymous functions are introduced frequently in e.g. comprehensions and generators. The REPL uses many of them for different keybinding.

The user experience boost when using Julia when the anonymous are still kept should not be understated. The REPL feel very fast and e.g. Pkg3 that uses a lot of comprehensions gets a very nice boost from keeping them.

Therefore, I think it would be good if the precompilation statements were generated as a part of the release process. The way it works would be as follows. Julia is first built without any precompilation statements. Then we play up a prerecorded "script" where we record all the functions that are being precompiled. This script would start a REPL, do some common stuff, perhaps some Pkg3 actions. We then rebuild Julia with those precompile statements *while keeping the anonymous functions in place*. The names of the anonymous functions are correct for this release, so the problem with the precompile statements becoming stale is no longer there.

Having an automated way of generating these precompile statements would be good in itself, they are very important and right now, they become stale too easily.

**Comment by TsurHerman** [comment]
I have issued a [PR](https://github.com/JuliaLang/PackageCompiler.jl/pull/45) for PackageCompiler that does exactly that.

you do `log_bootstrap()` to start logging (logging is appended to the previous log if there exist one)
`log_bootstrap(true)` to start logging and discarding any previous logs.

This logs all calls for the Julia compiler (like SnoopCompile)

you then do bootstrap(;force = true) to invoke building a new sysimg where all the statements previously logged are turned into precompilation statements and "appended" to the sysimg.

all statements are surrounded with try catch so the process is stable even if recompilation fails for some reason.

I use it for all pack ages , since my own code is not discoverable without first adding some directories for `LOAD_PATH`, the effect is a super smooth experience with Atom Repl and all the packages I use.

The down side is that this process needs to repeat itself if I want to update existing packages

**Comment by KristofferC** [comment]
We do have something quite similar in Base. Swapping the `TRACE_COMPILE` flag in `options.h` and then dumping the stderr to file and running the `contrib/fixup_precompile` script with merge options. This will append the new precompile statements to the `base/sysimg.jl`.

This is not the issue I am getting at here though. The problem is that:

* Precompile statements become stale and even though you protect them with `try catch` they will stop being effective. This might have a very large impact on e.g. start time.
* Different architecture need different statements. Some functions on 32bit architectures will be called with 32-bit Ints when run in the standard case. Generating precompile statements on 64-bit architecture will be ineffective.
* Also anonymous function quickly become stale from standard code development.

What I want here is that the precompile statements are an output from a "behavior". What I am envisioning is that you do something like `start_record()` which dumps you in a new REPL where every keystroke you type is recorded. You can then "replay" that record on whatever architecture you want at any time you want and record the functions being compiled. This is what I mean that the precompile statements are just an output from behavior. At release time, every buildbot would generate their own precompile file (from the same REPL record) and build that into the sysimg. This would mean that the precompile statements would always be up to date, always be valid for that architecture and anonymous functions could be included.

**Comment by KristofferC** [comment]
This is done (and with good result).
