### ISSUE TITLE
Consistency of using keywords as names

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#26507]
While poking around parsing of Julia, I found some inconsistent handling of reserved words (or keywords). Specifically, some keywords are parsed in different ways. Here are some examples:

| code | parsable | result |
| --- | --- | --- |
| `@try` | ✓ | `#= none:1 =# @try` |
| `@catch` | ✗ | `Base.Meta.ParseError("unexpected \"catch\"")` |
| `macro try() end` | ✗ | `Base.Meta.ParseError("invalid name \"try\"")` |
| `macro catch() end` | ✗ | `Base.Meta.ParseError("unexpected \"catch\"")` |
| `foo.try` | ✓ | `foo.try` |
| `foo.catch` | ✗ | `Base.Meta.ParseError("unexpected \"catch\"")` |
| `foo.:try` | ✓ | `foo.try` |
| `foo.:catch` | ✗ | `Base.Meta.ParseError("unexpected \"catch\"")` |

I think there are some problems:
- `@try` is allowed but `@catch` is not.
- We cannot define a `try` macro, but it is callable (actually, we can define one with metaprogramming, but it is an unusual way).
- `foo.try` is allowed but `foo.catch` is not.
- We cannot define a struct with a field named `try`, but it is usable (again, metaprogramming would make it possible but it is weird).
- `foo.:try` is allowed but `foo.:catch` is not.

My proposals are:
- [ ] Disallow macro call of a keyword name (e.g. disallow `@try`).
- [ ] Disallow field access of a keyword name (e.g. disallow `foo.try`) [#26622].
- [x] Allow field access of a keyword name if it is quoted (e.g. allow `foo.:catch`) [#26540].

If we make this change before 1.0, we can allow some keyword names if we really need them, but the opposite is impossible.

Any opinions?

**Comment by JeffBezanson** [comment]
> foo.:try is allowed but foo.:catch is not.

Good "catch" :) This seems to just be an oversight. I'll put up a fix.

I think the rest of the proposals are reasonable.

**Comment by JeffBezanson** [comment]
These are now consistent over all keywords.

**Comment by bicycle1885** [comment]
💯
