### ISSUE TITLE
MurmurHash3 has undefined behavior

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#26512]
Our implementation of MurmurHash3 has:

https://github.com/JuliaLang/julia/blob/ed3798495d735a9608ef42ac266649a2a3fe085e/src/support/MurmurHash3.c#L60-L63

However, the pointer is not necessarily properly aligned, making this undefined behavior.
The proper fix is to stop casting to an invalid pointer type and to use `memcpy`, which all modern compiler optimize to a proper sequence for unaligned access.

This is the same issue as https://github.com/grpc/grpc/issues/13221

**Comment by yuyichao** [comment]
[These](https://github.com/JuliaLang/julia/blob/master/src/julia_internal.h#L1044) can be moved to support.
