### ISSUE TITLE
Printing of dotted operators in macroexpand

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#26517]
```julia
julia> x = 1.0:3.0; y = similar(x);

julia> @macroexpand @. y = x + 3 * sin(x)
:(y .= +.(x, *.(3, sin.(x))))

julia> y .= +.(x, *.(3, sin.(x)))
ERROR: syntax: numeric constant "." cannot be implicitly multiplied because it ends with "."
```
`+.` and `*.` should be displayed as `.+` and `.*`.

**Comment by ChristianKurz** [comment]
I thought only infix operators are used with a preceeding dot and the call notation `+(...)` would still need the dot between operator and parens?

This is just another argument for dots after the operator...

**Comment by mbauman** [comment]
It's just missing the parentheses that disambiguate the infix operator from a function name and call:

```
julia> Meta.parse("y .= (+).(x, (*).(3, sin.(x)))")
:(y .= +.(x, *.(3, sin.(x))))
```
