### ISSUE TITLE
wrongly overloading "getproperty" crashes REPL

### ISSUE THREAD

**Issue by longqian95** [JuliaLang/julia#26528]
julia> versioninfo()
Julia Version 0.7.0-DEV.4625
Commit 57cbdf9f05 (2018-03-18 09:35 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:

julia> Base.getproperty(t,f::Symbol) = nothing

fatal: error thrown and no exception handler available.
MethodError(f=typeof(Base.start)(), args=(nothing,), world=0x0000000000006a11)

**Comment by fredrikekre** [comment]
See #20945, #22132, #23605, #21944, #24078, #24122, #25208, #26438

**Comment by KristofferC** [comment]
This is type piracy; destroying methods used by Julia will destroy Julia.

Dup of #20945, #22132, #23605, #21944, #24078, #24122, #25208,  #26438
