### ISSUE TITLE
`permdims(::SparseMatrixCSC)` or `maximum(::SparseMatrixCSC)` broken?

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#26534]
Please look at the following results (v"0.7.0-DEV.4633"):

```
julia> A = sparse([1 2; 3 0; 0 6]);
julia> B = permutedims(A)
2×3 SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  1
  [2, 1]  =  2
  [1, 2]  =  3
  [2, 3]  =  6

julia> dump(B)
SparseMatrixCSC{Int64,Int64}
  m: Int64 2
  n: Int64 3
  colptr: Array{Int64}((4,)) [1, 3, 4, 5]
  rowval: Array{Int64}((8,)) [1, 2, 1, 2, 140027692354904, 140027691616968, 140027691624584, 0]
  nzval: Array{Int64}((8,)) [1, 2, 3, 6, 140027713764912, 140027713764944, 140027779521904, 140027691600400]

julia> maximum(B)
140027779521904

julia> maximum(A)
6
```
While the out put of `show(B)` looks fine, `dump(B)` reveals, that `permutedims` created `B.rowval`and `B.nzval` arrays which are oversized and contain uninitialized elements. That would be no harm, if *all* functions handling sparse matrices would ignore these entries. Obviously `maximum` does not, and I guess there are some more.
I propose to fix `permutedims` for sparse matrices, as I do not see the advantage of unused elements in the internals of `SparseMatrixCSC`.

**Comment by andreasnoack** [comment]
It can be useful to allow the buffers to be larger than necessary so functions should only look at the with `colptr[n + 1] - 1` elements of `rowval` and `nzval` as in https://github.com/JuliaLang/julia/blob/master/stdlib/SparseArrays/src/sparsematrix.jl#L72. Hence https://github.com/JuliaLang/julia/blob/f0c09df61ebf3cf3d1a558693f23832b4087f8a1/stdlib/SparseArrays/src/sparsematrix.jl#L1643 is not correct. I'm curious what has caused the change in `permutedims` though.

**Comment by KristofferC** [comment]
The issue is that a sparse matrix that has been created from `similar` (in other words, it has garbage `rowval`, `nzval`) is used to repeatedly call `setindex!` upon. `setindex!` checks if it finds the row (which it won't in this case, and then `insert!`s it into the correct position, pushing the garbage `rowval`, `nzval` back. These are never resized so the garbage values are still there in the end.

**Comment by andreasnoack** [comment]
That sounds like a pretty slow way of doing this. Is this dispatching differently from what `permutedims(A, (2, 1))` used to do in 0.6?

**Comment by KlausC** [comment]
> It can be useful to allow the buffers to be larger than necessary ...

Yes, I can imagine, that sometimes it could be useful and it can be worked around by using a view of the proper size, but I am missing a really good use case. At the end, one of the main motivation of sparsity, the saving of memory space, is jeopardized. The created array size is typically exactly double of the required size.

**Comment by KristofferC** [comment]
Previously, the `rowval` and `nzval` fields were empty when calling `similar`.

**Comment by andreasnoack** [comment]
> but I am missing a really good use case

It can be much faster to preallocate all the memory and then populate it with values later.

> Previously, the `rowval` and `nzval` fields were empty when calling `similar`.

Do you remember where this was changed or the reason for doing it?

**Comment by KristofferC** [comment]
> Do you remember where this was changed or the reason for doing it?

Nope. `permutedims` should be extremely slow both on 0.6 and 0.7 though, except on 0.7 it would allocate ~2x as much memory.

**Comment by KlausC** [comment]
> It can be much faster to preallocate all the memory and then populate it with values later.

That is no convincing me! Populating the matrix using assignment to array elements of the matrix, or `setindex` does not make use of the preallocated cells, but resizes `nzval` and `rowval`. The pre-allocation of memory would only make sense if not re-sizing.
 At least the unused cells should not be presented to the user. It also comes with the extra cost of added complexity, programming overhead, memory and time consumption.

>  >Previously, the rowval and nzval fields were empty when calling similar.

> Do you remember where this was changed or the reason for doing it?

> Nope. permutedims should be extremely slow both on 0.6 and 0.7 though,

I propose to change `similar` in the way it used to work in 0.6. Maybe with a `sizehint!` on the empty arrays.

I also propose to provide a specialized version of `permutedim` for the sparse case, which has a performance measure of `O(nnz(A))`. I already implemented that and can make a PR, if you want.

**Comment by fredrikekre** [comment]
> I also propose to provide a specialized version of permutedim for the sparse case

Presumably `permutedims(A::SparseMatrixCSC) = transpose(A)` would be all that is required here.

**Comment by KristofferC** [comment]
Also a check for the explicit `(2,1)` case, I guess.

**Comment by fredrikekre** [comment]
`permutedims(A::SparseMatrixCSC, perm) = perm == (1, 2) ? copy(A) : copy(transpose(A))` :)

**Comment by KristofferC** [comment]
What if someone puts in `(3,1)` ;)

**Comment by KlausC** [comment]
> Presumably permutedims(A::SparseMatrixCSC) = transpose(A) would be all that is required here.

Unfortunately not. I wanted to do `qrfact(transpose(A))`, which fails, because the `Transpose` wrapper is not handled. So I implemented (as a work-around) `hardadjoint`, which does the job. 

> Also a check for the explicit (2,1) case, I guess.

For `SparseMatrixCSC` that would be the default case. No need to support other cases, I think.

**Comment by KristofferC** [comment]
>  which fails, because the Transpose wrapper is not handled

Yes so we materlailize it with `copy`.

> For SparseMatrixCSC that would be the default case. No need to support other cases, I think.

Still want to use the fast version if someone does `permutedism(A, (2,1))`.

**Comment by KlausC** [comment]
> Yes so we materlailize it with copy.

Yes, I see. I checked `copy(transpose(A))` is as effective as my `hardadjoint(A)`, which I retire herewith.

> Still want to use the fast version if someone does permutedism(A, (2,1)).

`permutedims(A::SparseMatrixCSC) = copy(transpose(A))`
`permutedims(A::SparseMatrixCSC, perm) = perm = (2,1) ? permutedims(A) : t

`permutedims(A::SparseMatrixCSC, perm) = perm == (2,1) ? permutedims(A) : invoke(permutedims, (AbstractMatrix, Any), A, perm)` ?
