### ISSUE TITLE
stdlib/Sockets: `getaddrinfo("☃.net")` non-ASCII hostname (RFC 3492)

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#26551]
https://github.com/JuliaLang/julia/blob/569981ab61c40089490a9b45b4f4699440f440f8/stdlib/Sockets/src/addrinfo.jl#L51-L52

Should this changed be to `isascii(host) || host = `[`Punycoder.encode(host)`](https://github.com/apricis/Punycoder.jl/blob/master/punycoder.jl) ?

References:
https://www.ietf.org/rfc/rfc3492.txt
https://github.com/JuliaWeb/URIParser.jl/issues/9
http://☃.net

**Comment by vtjnash** [comment]
Seems vaguely like something that should be handled at the application-level (URIParser.jl? HTTP.jl? higher?), and not in the stdlib.

**Comment by samoconnor** [comment]
I'm not familiar with this in practice, just noticed this as a loose end in the URIParser.jl issues.
However, it seems like "Internationalized Domain Names in Applications (IDNA): Protocol" https://tools.ietf.org/html/rfc5891, is a well defined thing. It tays DNS lookup of non-ascii names should be done by converting to punycode (an "A-label" in the language of the RFC).

    5.6.  DNS Name Resolution
    
    The A-label resulting from the conversion in Section 5.5 or supplied
    directly (see Section 5.3) is combined with other labels as needed to
    form a fully-qualified domain name that is then looked up in the DNS,
    using normal DNS resolver procedures.  The lookup can obviously
    either succeed (returning information) or fail.

Doing this in stdlib/Sockets might be a simple way to help all Julia systems to be IDNA compatible.

**Comment by inkydragon** [comment]
upstream `libuv` has already supported non-ASCII hostname. 
- [unix,win: support IDNA 2008 in uv_getaddrinfo() · libuv/libuv@6dd44ca](https://github.com/libuv/libuv/commit/6dd44caa35b4697d7e8c1b9fa0ba8e95d73355de)

so, just remove this line and `getaddrinfo("☃.net")` works fine.

https://github.com/JuliaLang/julia/blob/4f8a7b965a98c307f48820c35ca98f9d754096a9/stdlib/Sockets/src/addrinfo.jl#L60

**Comment by inkydragon** [comment]
`using Sockets; getaddrinfo("☃.net")` works fine on Julia 1.6.3/1.7.0-rc1.

This issue can be closed now.
