### ISSUE TITLE
Incorrect return type in docstring for `redirect_stdout(stream)`

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/julia#26558]
The docstring for `redirect_stdout` states that it will return a tuple `(rd, wr)` of the pipe ends, regardless of whether a `stream` input argument is provided:

https://github.com/JuliaLang/julia/blob/7674acada0c6b645319c54ed2a6606b5408f5693/base/stream.jl#L943

 However, if the function is called with a new stream as its argument, then only that new stream is returned, not a tuple of pipes:

https://github.com/JuliaLang/julia/blob/7674acada0c6b645319c54ed2a6606b5408f5693/base/stream.jl#L931

Should we update the behavior or the documentation?

**Comment by laborg** [comment]
The docstring has changed in the meantime to `redirect_stdout([stream]) -> stream`
