### ISSUE TITLE
stop supporting bases > 36 without explicit alphabet?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#26571]
https://discourse.julialang.org/t/what-is-the-effect-of-parse-on-char-types/9874/2

The fact that we have this seems like asking for trouble:
```jl
julia> parse(Int, 'a', base=36)
10

julia> parse(Int, 'A', base=36)
10

julia> parse(Int, 'a', base=37)
36

julia> parse(Int, 'A', base=37)
10
```
Perhaps it would be best to stop supporting bases larger than 36 since it's standard to parse hex in a case insensitive manner. At the very least we should make sure that we audit all the places where we print and parse bases larger than 36 and make sure that they're all internally consistent at least.

**Comment by JeffBezanson** [comment]
Actually this might be the real issue:

```
julia> parse(Int, "z")
ERROR: ArgumentError: invalid base 10 digit 'z' in "z"
Stacktrace:
 [1] tryparse_internal(::Type{Int64}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:117
 [2] #parse#360(::Nothing, ::Function, ::Type{Int64}, ::String) at ./parse.jl:216
 [3] parse(::Type{Int64}, ::String) at ./parse.jl:216
 [4] top-level scope

julia> parse(Int, 'z')
35
```

We use 36 as the default base for parsing Chars, and 10 elsewhere. I think we should change the default to 10 everywhere.

**Comment by ttparker** [comment]
The method `parse(type, c::Char)` is currently undocumented - should we add it to the documentation?

**Comment by o314** [comment]
Even in base < 32, there is not always a strictly direct 1 to 1 mapping to a digits + hexa base.

Ex: base32 crockford = base36 - `I`, `L`, `O`, `U`
Very useful to avoid confusion for human readable identifier (no more is it a 1, a L, or an I; a O or an 0 ?)


https://github.com/JuliaLang/julia/blob/master/base/parse.jl#L36-L44 seems a bit too much hardcoded

**Comment by ttparker** [comment]
@JeffBezanson It seems that there's still no docstring for the `parse(T, ::Char)` method? (I could try adding one myself, but I haven't contributed to Julia yet so it might take me a while to figure out how.)
