### ISSUE TITLE
Pig.add error

### ISSUE THREAD

**Issue by trimQiu** [JuliaLang/julia#26584]
hello,
    When I use Pkg.add("IJulia") to add IJulia,it failed. And infomation of the error is:
  ERROR: GitError (Code:ECERTIFICATE,Class:OS, user cancelled certificate check:)
   My julia version is 0.6.2, System version is Windows 7. And I can download JuliaLang/IJulia.jl both way of "git clone" and "download zip".

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/julia/issues/26167, https://discourse.julialang.org/t/errors-for-git-pkg/9351
