### ISSUE TITLE
Improving iteration performance of ranges of small integer types

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#26586]
Julia currently supports iterating over the _full_ range of representable integers
````
for i = typemin(T):typemax(T) ... end
````
when `T` is a 'small' integer type `Union{Int8,UInt8,Int16,UInt16,Int32,UInt32}`. The overflow problem is solved by conversion to `Int`.

However, there is a very large overhead due to conversion of `Int` to `T` in each iteration. Take for example these two functions which imho should have the same performance:

```julia
function copy_via_iterator!(x::AbstractVector{T}, r::UnitRange{T}) where {T}
    @inbounds for (i_large, i_small) = enumerate(r)
        x[i_large] = i_small
    end
    x
end

function copy_via_loop!(x::AbstractVector{T}, r::UnitRange{T}) where {T}
    value = r.start
    @inbounds for i = 1 : length(r)
        x[i] = value
        value += T(1)
    end
    x
end
```

Benchmarks (iterator vs loop resp):
- Int8: 75ns vs 5.0ns with `r = Int8(-128) : Int8(127)`
- Int32: 8.2μs vs 3.1μs with `r = Int32(1) : Int32(50_000)`
- Int64: 8.8μs vs 8.8μs with `r = Int64(1) : Int64(50_000)`

One way to fix this problem is to keep track of two indices, one of type `Int` and one of type `T`. Something along the lines of:

```julia
import Base: start, next, done

struct MyUnitRange{T}
    start::T
    stop::T
end

const SmallIntT = Union{Int32, Int16, Int8} # and others...

struct SmallIntState{T<:SmallIntT}
    idx_small::T
    idx_large::Int
    stop::Int
end

# Int
start(r::MyUnitRange{T}) where {T} = r.start
next(r::MyUnitRange{T}, i) where {T} = i, i + one(T)
done(r::MyUnitRange{T}, i) where {T} = i == r.stop + one(T)

# Small integer types
function start(r::MyUnitRange{<:SmallIntT})
    SmallIntState(r.start, Int(r.start), Int(r.stop))
end

function next(r::MyUnitRange{T}, state::SmallIntState{T}) where {T} 
    state.idx_small, SmallIntState(state.idx_small + T(1), state.idx_large + 1, state.stop)
end

function done(r::MyUnitRange{T}, state::SmallIntState{T}) where {T} 
    state.idx_large == state.stop + 1
end
```

Same benchmarks with this implementation:
- Int8: 5.0ns :tada:
- Int32: 3.5μs :tada:

---

Finally I'm wondering why we don't treat Int32 the same way as Int64. Should all iterations with `UnitRange{Int32}` have this overhead cause we support the very exceptional case of iterating over the range `Int32(-2147483648):Int32(2147483647)`?

**Comment by mschauer** [comment]
On 32bit systems, `Int32`s are just `Int`s and  corrresponding `for`-loops with are already behaving like this, so this would only increase overall  consistency.

**Comment by StefanKarpinski** [comment]
I believe that the new iteration protocol that @keno has a PR for fixes the boundary conditions since it essentially adds an extra bit of iteration state in the form of "there is a value | we're done".

**Comment by haampie** [comment]
@mschauer mentioned that on Slack, but the PR shows the same implementation (https://github.com/JuliaLang/julia/pull/25261/files#diff-c5053a63cd3df77d9079e95f29f350adR471)

Allowing iteration all the way from `typemin(T)` to `typemax(T)` requires looping like

```julia
function my_loop(start::T, stop::T) where {T}
  idx = start
  idx > stop && return # This
  while true
    do_something(idx)
    idx == stop && break # And this
    idx += one(T)
  end
end
```

which might not fit the iterator concept. (I might be missing something of course.)
