### ISSUE TITLE
Computing Error

### ISSUE THREAD

**Issue by SuttonP** [JuliaLang/julia#26596]
Julia 6.1 and 6.2 arithmetic
.1*3=.30000000000000004
.1+.1+.1= .30000000000000004
.1+.1+.1+.1+.1+.1+.1+.1+.1=.89999999999

**Comment by KristofferC** [comment]
See e.g. https://github.com/JuliaLang/julia/issues/25269

**Comment by mbauman** [comment]
There are more beginner-friendly approaches at http://0.30000000000000004.com and https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678.  Future discussion here should be taken to https://discourse.julialang.org.
