### ISSUE TITLE
Fail to build ZMQ

### ISSUE THREAD

**Issue by trimQiu** [JuliaLang/julia#26590]
Hello,
       After I add "IJulia", when I run "using IJulia" , returns a LoadError : ZMQ not properly installed. Please run Pkg.build("ZMQ").
       So I do it, stil, it returns a LoadError: None of the selected providers can install dependency zmq. Use BinDeps.debug(package_name) to see avaliable providers.
    All informations is here:
     INFO: Reading build script...
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to d
ownload
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to d
ownload
The package declares 1 dependencies.
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: received error 0 while downloading https://cache.julialang.org/http://d
ownload.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repod
ata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repos
itories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: Unknown download failure, error code: 2148270085
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.open
suse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.x
ml
WARNING: received error 0 while downloading https://cache.julialang.org/http://d
ownload.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repod
ata/repomd.xml
 - Library "zmq"
    - Providers:
      - Autotools Build
      - BinDeps.AptGet package libzmq3 (can't provide)
      - BinDeps.Yum package czmq (can't provide)
      - BinDeps.Pacman package zeromq (can't provide)
      - WinRPM.RPM package zeromq (can't provide)

**Comment by ggggggggg** [comment]
this issue should be closed, and re-opened at: t https://github.com/JuliaInterop/ZMQ.jl 

also it would be best to include the output of `versioninfo()`
