### ISSUE TITLE
Call to cfunction(noop_func, ...) [without using the result pointer] segfaults since 0.7.0-DEV.4497

### ISSUE THREAD

**Issue by luchr** [JuliaLang/julia#26607]
The following few lines produce (for me) a deterministic segfault inside the `callthis(Int32(0))` call:

```julia
noop_func = () -> nothing

function callthis(args)
  cfunction(noop_func, Cvoid, Tuple{})
  return nothing
end

callthis(Int64(0))
callthis(Int32(0))
```
Julia-Version:
```
Julia Version 0.7.0-DEV.4690
Commit 78c7d87369 (2018-03-23 22:25 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
```
I have no idea why. Perhaps the `noop_func` is "optimized" away?

**Comment by ararslan** [comment]
Also note that this doesn't happen on 0.6.

**Comment by luchr** [comment]
Oh. I forgot to mention: This bug was introduced somewhere between 0.7.0-DEV.4362 and 0.7.0-DEV.4690.

**Comment by luchr** [comment]
After git bisect:
The bug was introduced in commit 793481037a30fb02b09efdad447fa1d13e11390c (=0.7.0-DEV.4497).

**Comment by StefanKarpinski** [comment]
cc @vtjnash
