### ISSUE TITLE
Openblas tests take a lot of space

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26609]
```
➜  pwd
/Users/kristoffer/julia/deps/scratch/openblas-5dde4e65d321076582a2fafe16949d2160551e81/ctest
➜  du -ch .
811M	.
811M	total
```

Can we avoid building these tests or clean them out after building is done?

**Comment by ViralBShah** [comment]
What's a GB here or there? Will they get rebuilt every time we do `make testall`? If not, we could definitely clean them.

**Comment by KristofferC** [comment]
My Julia folder is 2,5 GB so having 800 MB or more than 30% of that be test executables for one of the dependencies seems unnecessary.

**Comment by JeffBezanson** [comment]
I agree we should delete them if at all possible. I see some environments where disk quotas are a problem, and there are many people building julia on the same shared filesystem. It can add up fast.

**Comment by vtjnash** [comment]
I've set up the Makefile rules such that we should be able to remove the dependency on keeping those files around and erase the whole `deps/scratch` folder if we would like to (there's even more significant savings to be had if you have build LLVM_DEBUG, which contains 6-8 GB). For example, this works now:

```
find deps/scratch -not -name 'build-compiled' -and -not -name 'source-extracted' -and -not -name 'build-configured' -and -not -name '*.patch-applied' -and -not -type d -delete
```

But this won't rebuild cleanly automatically if there's a new patch (not hard to fix, but you would need to manually remove the folder to unstick the build). So altering the Makefile rules would generally be preferable.

**Comment by KristofferC** [comment]
Probably fixed with binarybuilder. @staticfloat good to close?
