### ISSUE TITLE
Additional documentation for setting up command line interface for Julia?

### ISSUE THREAD

**Issue by conradwt** [JuliaLang/julia#26614]
Hi, I'm unable to find the complete documentation for setting up the command line.  At this time, I have completed the following:

1) installed JuliaPro 0.6.2.2

2)  adding the following environment variables to my .profile
     ```
     export JULIA_HOME=/Applications/JuliaPro-0.6.2.2.app
     export PATH=${JULIA_HOME}/Contents/Resources/julia/Contents/Resources/julia/bin:${PATH}
    ```

3) using the command line

    ```
     $ julia

     ```
      
I see the following error in the terminal
     
```
      ERROR: could not load library "/Applications/JuliaPro-0.6.2.2.app/../lib/julia/sys.dylib"
dlopen(/Applications/JuliaPro-0.6.2.2.app/../lib/julia/sys.dylib, 6): image not found
```

**Comment by fredrikekre** [comment]
https://discourse.julialang.org/t/documentation-for-setting-up-command-line-interface-after-installing-julia-pro/9986
