### ISSUE TITLE
Lowering of `.=`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#26612]
Currently `x .= x .+ x` lowers to:

```
      #6 = $(Expr(:new, :(Main.:(##6#8))))
      Core.SSAValue(0) = #6
      (Base.broadcast!)(Core.SSAValue(0), x, x)
```

which is a sensible definition for mutable types.
As mentioned in https://discourse.julialang.org/t/is-broadcast-supposed-to-work-on-staticarrays/9977/3
it might be beneficial (I am not a 100% on that) for immutable types to define `.=` as well, but the lowering get's in the way of that.

I propose that we change the lowering to:

```
      #6 = $(Expr(:new, :(Main.:(##6#8))))
      Core.SSAValue(0) = #6
      x = (Base.broadcast!)(Core.SSAValue(0), x, x)
```

which will require `broadcast!` to return the argument it is modifying and would allow immutable container types to 
chose to implement `.=` as well.

**Comment by mbauman** [comment]
Dup of https://github.com/JuliaLang/julia/issues/19992
