### ISSUE TITLE
Can't Add Packages

### ISSUE THREAD

**Issue by Ingovs** [JuliaLang/julia#26611]
When i try to add the GLPKMathProgInterface, or any other package, i receive the following message: 

"Cannot clone GLPK from https://github.com/JuliaOpt/GLPK.jl.git. user cancelled certificate check:" 

What does that mean? I need to add some packages in order to use the solver, but i'm not able to.
What should i do?

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/julia/issues/26167, https://discourse.julialang.org/t/errors-for-git-pkg/9351
