### ISSUE TITLE
Behavior of Array substitution with multiple indexes is unexpected

### ISSUE THREAD

**Issue by utotch** [JuliaLang/julia#26620]
I tried a substition of subarray with multiple indexes. 
When I use only 3 indexes for substitution, 4 elements changed in the result.
The result is unexpected but do you think the behavior is correct or a bug??

```
A = zeros(Int, 2,2)
A[[1,2],[1,1]] = 1
@show A
```
A = [1 0; 1 0]

```
B = zeros(Int, 2,2)
B[[1,2,1],[1,1,2]] = 1
@show B # Why not [1 1; 1 0] but [1 1; 1 1] ??
```
B = [1 1; 1 1]  # I expect output = [1 1; 1 0]

$ versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

(I checked it with both Julia 0.6.2 on Linux & Julia 0.6.2 on JuliaBox)

**Comment by mbauman** [comment]
Julia's indexing behaves differently from NumPy's.  `B[[1,2,1],[1,1,2]]` does not select the three elements `[B[1,1], B[2,1], B[1,2]]`.  Instead, it selects the product of rows `[1,2,1]` and columns `[1,1,2]` — nine elements in total. They overlap and coincide in your `A` case which makes this confusing. For more details, check out [Array indexing](https://docs.julialang.org/en/stable/manual/arrays/#man-array-indexing-1).  Further questions should be taken to our [discourse discussion board](https://discourse.julialang.org).

**Comment by utotch** [comment]
Oh, I understand!
Thank you very much for the accurate explanation!
