### ISSUE TITLE
Bounds check in step range does not take into account overflow

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#26623]
For example

```
> (1:3:4)[6148914691236517207]
3
```

This happens because `first(v) + (i - 1)*step_hp(v))` in `getindex` can overflow. A solution is to use `checkbounds(1:3:4, 6148914691236517207)` which _will_ throw a BoundsError for the above, but is not suitable for step ranges where the length cannot be represented in the integer type: `checkbounds(-10:1:typemax(Int), 10)` throws an OverflowError.

**Comment by brenhinkeller** [comment]
Still overflowing on 1.8 and 1.9, FWIW
```
julia> (1:3:4)[6148914691236517207]
3

julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```
