### ISSUE TITLE
Segfault on debug bootstrap on armv7l

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#26639]
We're getting a segfault on `make debug` when running on `armv7l`:

```
signal (11): Segmentation fault
in expression starting at no file:0
_ZN4llvm15MCSymbolRefExprC1EPKNS_8MCSymbolENS0_11VariantKindEPKNS_9MCAsmInfoE at /buildworker/worker/package_linuxarmv7l/build/usr/bin/../lib/libLLVM-3.9.so (unknown line)
unknown function (ip: 0x8f64efa7)
Allocations: 226471069 (Pool: 226441832; Big: 29237); GC: 1332
Segmentation fault (core dumped)
```

See https://build.julialang.org/#/builders/4/builds/881 for more details.  Interestingly enough, we make it through `make release` just fine.  Perhaps our recent alignment fixes aren't getting applied properly to debug builds?

**Comment by vtjnash** [comment]
Seems to have been a std::bad_alloc up until https://build.julialang.org/#/builders/4/builds/616, but f9f11a3102042d53de04ef48a83c713467bbd241...12964e839e57154b43f1d1423ebf5547df932756 doesn't seem very interesting

**Comment by ViralBShah** [comment]
Maybe related to https://github.com/JuliaLang/julia/issues/26122
