### ISSUE TITLE
0.6.2 Wrong output at the first execution within REPL

### ISSUE THREAD

**Issue by xanfus** [JuliaLang/julia#26641]
To be precise, workspace wasn't empty, Julia ran, as is seen with warnings generated by Python.
![screenshot from 2018-03-28 11-14-45a](https://user-images.githubusercontent.com/5682375/38017250-2e112ffa-327a-11e8-8f5c-9eacc90fd838.png)
```
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by StefanKarpinski** [comment]
It looks like something weird may be going on in your startup script. Can you run `julia --startup-file=no` and see if that fixes it? Either that or temporarily move your `~/.juliarc.jl` file to a different location if that's easier.

**Comment by dmbates** [comment]
@xanfus Are you running Julia from within Python?  I am wondering where the line
```
Press Enter to start Julia
```
came from.

If you are running Julia from within Python it would not be surprising if Julia automatically loaded the `PyCall` package.  I know that the `JuliaCall` package for `R` automatically loads the `RCall` Julia package because many of the data structure translation functions live there.

**Comment by xanfus** [comment]
Julia is run in Atom thanks to "uber-juno" package bundle. Recently "REPL" tab have replaced "Console" tab by default. The latter can be turned switched back in "julia-language" package settings.
I start Julia and load PyCall manually. Julia can be started explicitly as depicted above or implicitly either in "Console" tab or by call of script lines.

**Comment by StefanKarpinski** [comment]
Can you reproduce the above starting Julia directly in the terminal?

**Comment by xanfus** [comment]
I'm sequencing the sample.

**Comment by xanfus** [comment]
I've reduced script to "gn=randn(2^22)". "1/sqrt(2)" behaves nominally after call to "randn(2^22)", which launches new Julia session, if one doesn't press "Enter" in "REPL" tab to start session. Another Julia session runs at the same time, which allows error-free kill and call of the aforementioned Julia session. "Terminal" Julia session computes "1/sqrt(2)" nominally.

**Comment by xanfus** [comment]
I'm applying your first directions, Stefan.
