### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 54

### ISSUE THREAD

**Issue by conradwt** [JuliaLang/julia#26650]
After upgrading Atom 1.25.0 to the latest stable release, I'm seeing the following error dialog on startup:

```
The module '/Applications/JuliaPro-0.6.2.2.app/Contents/MacOS/JuliaPro-Juno-0.6.2.2.app/Contents/Resources/julia_atom_0.6.2.2/packages/julia-client/node_modules/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

There appears to be an internal version of Node/Npm which is current;y having the issue.  I have tried the following without success: `npm rebuild` and `npm install`.  It doesn't like Python 3.6.4 and having trouble installing Node package.  Outside of JuliaPro 0.6.2.2, I have node v9.10.0 and npm 5.8.0 installed on macOS 10.13.3.  Would it possible to simply use the node v9.10.0 instead having a version of both npm and node for JuliaPro.

**Comment by fredrikekre** [comment]
This seems like a problem with JuliaPro and/or Atom and should be reported elsewhere.
