### ISSUE TITLE
Subtyping is wrong (because of variable bounds?)

### ISSUE THREAD

**Issue by ulysses4ever** [JuliaLang/julia#26654]
Julia used to say `true` (e.g. in 0.6.2) here:

    Ref{Union{Int64, Ref{Number}}} <: Ref{Union{Ref{T}, T}} where T

but current master, quite reasonably, says `false`. If you change, though, `Ref` to `Val` it is `true` again:

    Ref{Union{Val{Number}, Int64}} <: Ref{Union{Val{T}, T}} where T

Which seems to be a bug.

**Comment by JeffBezanson** [comment]
Seems to be related to `Ref` being an abstract type.

**Comment by JeffBezanson** [comment]
...which affects the order of the `Union` components. When the types "line up":

```
Ref{Union{Val{Number}, Int64}} <: Ref{Union{Val{T}, T}} where T
```

then we say true, but with the other order on the left:

```
Ref{Union{Int64, Val{Number}}} <: Ref{Union{Val{T}, T}} where T
```

we say false.
