### ISSUE TITLE
Reshape/reinterpret svd fails

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#26662]
```
A = randn(Complex128,2)
C = reshape(reinterpret(Float64,A),2,2)
svd(C)
```
fails (no method matching svdfact) in 0.7. It worked in 0.6. Other linalg methods (qr,lu) seem to work fine.

(reduced from https://github.com/JuliaNLSolvers/Optim.jl/pull/547)

More generally, is the new reinterpret here to stay, or a transitional thing? There appears to be several issues associated with it (speed, missing methods). This is to know if we should work around it, file bugs such as this one or wait for the situation to stabilize.

**Comment by andreasnoack** [comment]
The problem is that `C` is now a
```julia
julia> typeof(C)
Base.ReshapedArray{Float64,2,Base.ReinterpretArray{Float64,1,Complex{Float64},Array{Complex{Float64},1}},Tuple{}}
```
insteand of a `Matrix{Float64}` and
```julia
julia> C isa StridedMatrix
false
```
Apparently, there were some issues with the old reinterpret.

**Comment by mbauman** [comment]
Right now we're playing whack-a-mole with strided wrappers of wrappers.  Is a reshaped reinterpret a common data structure for you?  We could easily add this into the `StridedArray` typealias for now.

In order to support this with full generality we need #25558.

**Comment by antoine-levitt** [comment]
We use that in Optim.jl to convert a complex array (say NxM) to a real array (2xNxM). Actually simply reinterpreting it (2NxM) should be sufficient, I'll play with that.
