### ISSUE TITLE
FreeBSD instructions are wrong

### ISSUE THREAD

**Issue by yurivict** [JuliaLang/julia#26677]
In README, you explain how to build Julia on FreeBSD.
There is no need to guide users through the build process, because Julia is supported in ports.
All instructions should say is:
```
You can install the Julia package with the command: pkg install julia

If you would like to install Julia with custom options, you can do this building the port withe these options:
1. cd /usr/ports/lang/julia
2. make config
3. {select desired options}
4. make install clean
```

**Comment by ViralBShah** [comment]
Thank you for the comment. That is perhaps more appropriate for the Julia downloads page on the website.

The README is about instructions to build Julia from source - for developers.
