### ISSUE TITLE
Extract Q from qrfact! allocation-free

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/julia#26673]
I would like to request a function that can extract `Q` from the `qrfact` and `qrfact!` outputs allocation-free. That is the function should accept a buffer to fill it with `Q` by accumulating the Householder reflectors.

**Comment by stevengj** [comment]
Doesn’t `lmul!(QR.Q, mymatrix)` already do this, assuming `mymatrix` is initialized to I?

**Comment by mohamed82008** [comment]
Yes this works, thanks. But I believe it only gives the full Q though, not the thin version. Is it also possible to extract only the thin part? If not, I believe this https://github.com/mohamed82008/InplaceQR.jl/blob/96afa5c4b732b1aacd2210f1ad38cbbfd7ae50d5/src/qr_fact.jl#L35 can be used on the Householder vectors and multipliers. I am using QR to orthogonalize a few very long vectors so getting the full Q is really not helpful.

```julia
julia> A = rand(3,2);

julia> qrf = qrfact!(copy(A));

julia> mymatrix = Matrix{Float64}(I, 2, 2);

julia> lmul!(qrf.Q, mymatrix);
ERROR: DimensionMismatch("first dimensions of C, 2, and V, 3 must match")
Stacktrace:
 [1] gemqrt!(::Char, ::Char, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\site\v0.7\LinearAlgebra\src\lapack.jl:2796
 [2] lmul!(::LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}, ::Array{Float64,2}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\site\v0.7\LinearAlgebra\src\qr.jl:549
 [3] top-level scope

julia> mymatrix = Matrix{Float64}(I, 3, 3);

julia> lmul!(qrf.Q, mymatrix);

julia> mymatrix[1:3,1:2] * qrf.R
3×2 Array{Float64,2}:
 0.88633   0.618428
 0.687095  0.0959251
 0.252104  0.370464

julia> A
3×2 Array{Float64,2}:
 0.88633   0.618428
 0.687095  0.0959251
 0.252104  0.370464
```

**Comment by stevengj** [comment]
Think about your linear algebra a little more: as the error messages say, your matrices are the wrong size.  To get the thin Q you need to multiply by the first n columns of the identity matrix.
```jl
julia> A = rand(3,2);

julia> qrf = qrfact(A);

julia> mymatrix = Matrix{Float64}(I, 3,2)
3×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0
 0.0  0.0

julia> lmul!(qrf.Q, mymatrix)
3×2 Array{Float64,2}:
 -0.174787   0.14516 
 -0.267293  -0.958925
 -0.947631   0.243705
```

**Comment by mohamed82008** [comment]
Of course, my bad, thanks!
