### ISSUE TITLE
isfile() now throws an error on Windows

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#26685]
On Windows, `isfile()` now throws an error when given an "invalid argument".

On 0.6:
```
julia> isfile("http://google.com")
false
```

On 0.7:
```
julia> isfile("http://google.com")
ERROR: stat: invalid argument (EINVAL)
Stacktrace:
 [1] stat(::String) at .\stat.jl:68
 [2] isfile(::String) at .\stat.jl:303
 [3] top-level scope
```

**Comment by staticfloat** [comment]
This is kind of weird; `GetLastError()`, after calling `CreateFileW()`, is giving two different answers for identical inputs.  It all boils down to [this call](https://github.com/JuliaLang/libuv/blob/be317349252699670131395f125c3861d793ca86/src/win/fs.c#L1171-L1181) on 0.7, and [the analogous call](https://github.com/JuliaLang/libuv/blob/d8ab1c6a33e77bf155facb54215dd8798e13825d/src/win/fs.c#L1169-L1179) on 0.6.  The result of `GetLastError()` when `req->file.pathw == L"http://google.com"`  is -4058 (`Base.UV_ENOENT`) on 0.6, but is -4071 (`Base.UV_EINVAL`) on 0.7.

Is there some kind of "win32 API version" that we're targeting that is causing this difference?  We could, of course, add `Base.UV_EINVAL` to [this list](https://github.com/JuliaLang/julia/blob/a55c280d1b28a4cb069b43cb5691ec8a3b248801/base/stat.jl#L68) to patch over the behavior change, but somehow I don't think that's the right solution.

**Comment by jebej** [comment]
This might have been changed here: https://github.com/libuv/libuv/pull/1088

**Comment by staticfloat** [comment]
Thanks @jebej, that is indeed the source of the issue.

**Comment by vtjnash** [comment]
FYI https://github.com/libuv/libuv/pull/2375 and https://github.com/libuv/libuv/pull/2601
