### ISSUE TITLE
`cumsum` and friends don't support tuples

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#26690]
`cumsum(x)`, `cumprod(x)` and `diff(x)` (maybe others?) don't have methods defined for tuples. `vec` also doesn't have a tuple method so it can't be used to convert (though if `cumsum(::Tuple)` were implemented I'd expect it to also return a tuple)

**Comment by stevengj** [comment]
You can use `collect` to convert a tuple to an array, e.g. `cumsum!(collect(x))` where `x` is a tuple.

See also #25766.

**Comment by KristofferC** [comment]
Tuples are not AbstractArrays so perhaps better to use StaticArrays.jl for this?

**Comment by mbauman** [comment]
On #25766 `cumsum((1,2,3))` returns an `Array` `[1,3,6]`, so that's not quite what I'd want here.

I've thought before that `(1, cumprod(front(size(A)))...)` would be helpful just for pseudocode in expressing stride computations.  That's a case where you want to use and get back tuples.

**Comment by bramtayl** [comment]
Are all the times in the tuple the same type? If they aren't and the tuple is short you might be better of going with recursion? I could make an `accumulate_unrolled` function in RecurUnrolled

**Comment by ssfrr** [comment]
@stevengj thanks for that suggestion, `collect` is definitely more concise than what I did (using an array comprehension)

@KristofferC 
> Tuples are not AbstractArrays so perhaps better to use StaticArrays.jl for this?

For me this came up in the context of wanting to do something like `foo(xs...) = cumsum(xs)`, and wanting a tuple output, so it would be more convenient to stay in tuple-land.

**Comment by tkf** [comment]
I implemented `accumulate(op, xs::Tuple)` in #34654.
