### ISSUE TITLE
`start` missing for Nothing

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#26695]
```
julia> setdiff!([1, 2, nothing], nothing)
ERROR: MethodError: no method matching start(::Nothing)
Closest candidates are:
  start(::Core.SimpleVector) at essentials.jl:533
  start(::Base.MethodList) at reflection.jl:684
  start(::ExponentialBackOff) at error.jl:170
  ...
Stacktrace:
 [1] mapfoldl(::Function, ::Function, ::Set{Union{Nothing, Int64}}, ::Nothing) at ./reduce.jl:59
 [2] foldl at ./reduce.jl:90 [inlined]
 [3] setdiff! at ./abstractset.jl:149 [inlined]
 [4] _shrink! at ./array.jl:2338 [inlined]
 [5] setdiff!(::Array{Union{Nothing, Int64},1}, ::Nothing) at ./array.jl:2343
 [6] top-level scope
```
Needs an implementation of:
```
start(::Nothing)
```
and a test.

**Comment by KristofferC** [comment]
```
help?> setdiff
search: setdiff setdiff! selectdim setrounding searchsortedfirst

  setdiff(s, itrs...)

  Construct the set of elements in s but not in any of the iterables in itrs.
```

`nothing` is not an iterable so why do you expect this to work?

**Comment by StefanKarpinski** [comment]
Probably because numbers are iterable so it works if you replace the second `nothing` with `2`.

**Comment by JeffBezanson** [comment]
`nothing` should not be iterable.

**Comment by Nosferican** [comment]
It seems to be a bit arbitrary,
```
setdiff([1,2,3], 1)
setdiff(['a','b','c'], 'c')
```
work, but
```
setdiff(["a","b","c"], "b")
setdiff(["a","b",missing], missing)
```
doesn't. I thought the `String` example would work after the efforts to make `"a" == "a"` return `true` (and it works when enclosed in a `Vector`). What is the rule for making `Number`, `Char`, and `String` (even if it doesn't work as intended) iterables, but `Nothing` and `Missing` not? I thought these where valid values to have in collections to represent values (at least `missing`). If `missing` and `nothing` are treated differently for some issues I guess people can fall back to,
```
setdiff(["a","b",missing], [missing])
setdiff(["a","b",nothing], [nothing])
setdiff(["a","b","c"], ["c"])
```
which actually work are intended.

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/julia/issues/7903
