### ISSUE TITLE
reducedim allocates array of incorrect eltype

### ISSUE THREAD

**Issue by blegat** [JuliaLang/julia#26709]
To compute the `eltype` of the array storing the result, `reducedim` does
https://github.com/JuliaLang/julia/blob/bce5bbef9ba4b0a30a857d9032c00b1375de73ff/base/reducedim.jl#L119
I don't understand the reasoning behind the condition `typeof(z) == typeof(x) && !isbits(T)`. Why not just do `Tr = typeof(z)` ?

Here is a MWE:
```julia
struct Variable
    name::Symbol
end
struct AffExpr
    vars::Vector{Variable}
end
Base.zero(::Union{Variable, Type{Variable}, AffExpr}) = AffExpr(Variable[])
Base.:+(v::Variable, w::Variable) = AffExpr([v, w])
Base.:+(aff::AffExpr, v::Variable) = AffExpr([aff.vars; v])
Base.:+(aff1::AffExpr, aff2::AffExpr) = AffExpr([aff1.vars; aff2.vars])
```
The reduction fails because `Tr` is `Variable` instead of `AffExpr`. `typeof(z)` and `typeof(x)` are `AffExpr` and `isbits(Variable)` is `false`.
```julia
julia> sum([Variable(:x), Variable(:y)], 1)
ERROR: MethodError: Cannot `convert` an object of type AffExpr to an object of type Variable
This may have arisen from a call to the constructor Variable(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] fill!(::Array{Variable,1}, ::AffExpr) at ./multidimensional.jl:841
 [2] reducedim_initarray(::Array{Variable,1}, ::Int64, ::AffExpr, ::Type{Variable}) at ./reducedim.jl:73
 [3] _reducedim_init(::Base.#identity, ::Base.#+, ::Base.#zero, ::Base.#sum, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:102
 [4] reducedim_init(::Function, ::Base.#+, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:87
 [5] mapreducedim(::Function, ::Function, ::Array{Variable,1}, ::Int64) at ./reducedim.jl:242
 [6] sum(::Array{Variable,1}, ::Int64) at ./reducedim.jl:585
 [7] macro expansion at ./REPL.jl:97 [inlined]
 [8] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

**Comment by JeffBezanson** [comment]
Agreed; I don't see why `isbits` would be relevant here.

**Comment by nalimilan** [comment]
Bump. I was going to make the same PR. @JeffBezanson Any objections?

Though I'm not sure the test needs to be so complex. A much shorter reproducer is:
```julia
julia> mapreduce(cos, +, Union{Int,Missing}[1], dims=1)
ERROR: InexactError: Int64(Int64, 0.5403023058681398)
```

**Comment by nalimilan** [comment]
For the curious, this line comes from a generalization of a method which worked only for `+` (https://github.com/JuliaLang/julia/commit/54e034aac5500d1f8264e6454163ab56e2ddfe78). That weird `typeof(z) == typeof(x)` check comes from that legacy, but it doesn't really make sense.

**Comment by non-Jedi** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/28089

**Comment by blegat** [comment]
Indeed, thanks for the fix @nalimilan
