### ISSUE TITLE
typeof(1.*im) returns Complex{Int64}

### ISSUE THREAD

**Issue by yanncalec** [JuliaLang/julia#26713]
In Julia 6.0
```julia
julia> 1.*im==1.0*im
true
```
while the types of these two complex numbers are different:
```
julia> typeof(1.*im)
Complex{Int64}

julia> typeof(1.0*im)
Complex{Float64}
``` 
This seems incoherent with the case of real numbers.

**Comment by fredrikekre** [comment]
Thanks for the report. This is deprecated on julia master to avoid confusion with broadcasting:
```julia
julia> 1.*im==1.0*im
┌ Warning: Deprecated syntax `1.*` at REPL[1]:1.
│ Use `1 .*` instead.
└ @ nothing REPL[1]:1
```

See  #19089
