### ISSUE TITLE
for syntax without a variable

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#2675]
Especially with comprehensions I do this by accident fairly often:

``` .jl
[@elapsed f() for 1:10]
```

We could support the same for loops:

``` .jl
for 1:10 f() end
```

Not super crucial, but seems like something we might as well allow.

**Comment by ScottPJones** [comment]
I think the `@repeat n expr` syntax is the cleanest, just saying!

**Comment by KristofferC** [comment]
Seems this is likely not to happen. Also, `_` is deprecated for rvalue-usage so `for _ = 1:10` seems good enough.
