### ISSUE TITLE
Passing fields as pointers can pin large allocations to the stack

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#26756]
Suppose we have a struct like:

```
struct Large
     a::NTuple{9, Int}
     b::NTuple{9, Int}
     c::NTuple{9, Int}
     Large() = ...
end
```
and function like
```
foo(x::NTuple{9, Int}) = ...
function bar()
    l = Large()
    foo(l.a)
end
```
In the absence of ir-level getfield elimination, we will emit this as one copy of `Large` on the stack
and then pass a pointer to the field to `foo`. However, this presents a problem. Because `l.a` is a pointer to the inside of `l`, LLVM is not free to SROA `l` itself, because the pointer to it escapes.
Ideally, we'd have some LLVM attribute like `max_dereferenceable(n)` that would tell LLVM that while the pointer escapes, the callee is only allowed to look at the `n` bytes following the passed pointer, which would make SROA legal.

**Comment by gbaraldi** [comment]
We do this now!

**Comment by vtjnash** [comment]
yeah, there are still cases where we could be better, but that statement is always true
