### ISSUE TITLE
ERROR: no promotion exists for MyInt and Int64

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#26779]
The behaviour below seems inconsistent, and I couldn't find any documentation on why this is correct.  Perhaps it's a case of a `Number` interface in the docs is needed?

```julia
julia> struct MyInt <: Integer 
       x::Int
       end

julia> promote_type(MyInt, Int) # Why not Integer?
ERROR: no promotion exists for MyInt and Int64
Stacktrace:
 [1] error(::String, ::Type, ::String, ::Type) at ./error.jl:42
 [2] promote_to_supertype at ./promotion.jl:294 [inlined]
 [3] promote_result at ./promotion.jl:285 [inlined]
 [4] promote_type(::Type{MyInt}, ::Type{Int64}) at ./promotion.jl:220
 [5] top-level scope

julia> promote_type(MyInt, Vector)
Any
```

**Comment by StefanKarpinski** [comment]
I think you may be confusing `promote_type` with `typejoin`, which does what you want:
```jl
julia> typejoin(MyInt, Int)
Integer
```
The promotion mechanism is for converting to an appropriate common concrete type, which requires an explicit choice in this case—how would Julia guess which concrete type you want to promote to? The `typejoin` mechanism is for finding a "reasonable" (read: union-free) common abstract supertype.

**Comment by dlfivefifty** [comment]
How does it guess that I want `Any` when I call `promote_type(MyInt, Vector)`?

**Comment by dlfivefifty** [comment]
To clarify, I don't think this should error out:
```julia

julia> [MyInt(5),4]
ERROR: no promotion exists for MyInt and Int64
Stacktrace:
 [1] error(::String, ::Type, ::String, ::Type) at ./error.jl:42
 [2] promote_to_supertype at ./promotion.jl:294 [inlined]
 [3] promote_result at ./promotion.jl:285 [inlined]
 [4] promote_type at ./promotion.jl:220 [inlined]
 [5] promote_typeof(::MyInt, ::Int64, ::Vararg{Int64,N} where N) at ./promotion.jl:263
 [6] vect(::MyInt, ::Vararg{Any,N} where N) at ./array.jl:104
 [7] top-level scope
```
Maybe `vect` needs to call `typejoin`, not `promote_type`?

**Comment by StefanKarpinski** [comment]
It calls `typejoin` in some cases. Whether that's a good idea or not is debatable.

**Comment by JeffBezanson** [comment]
At some point we decided to require specific promotion rules to be defined for subtypes of `Number`. I think the original reason for that was to prevent definitions like 
```
+(x::Number, y::Number) = +(promote(x,y)...)
```
from being circular --- promoting `Int` and `MyInt` to `Integer` wouldn't actually convert any values. However now there is an explicit check that `promote` changes types, so we might be able to remove that other rule.
