### ISSUE TITLE
Inference regression with Union{T,Nothing} arrays

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#26771]
The following MWE used to be inferred as `Array{_,1} where _` on Julia 0.6, but on a recent master it's only inferred as `Array`. This regression is probably recent, as it breaks `@inferred` on `vcat` for CategoricalArrays, yet I hadn't noticed any test failure until today.
```julia
function f(a)
    v = [1, nothing]
    [v[x] for x in a]
end
@code_warntype f([1])
```

**Comment by oscardssmith** [comment]
Fixed on master.

**Comment by KristofferC** [comment]
Should have a test before close
