### ISSUE TITLE
Summary errors out for UnitRange{<:BigInt}

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#26799]
```julia
julia> summary(BigInt(1):BigInt(10))
ERROR: MethodError: no method matching dims2string(::Tuple{BigInt})
Closest candidates are:
  dims2string(::Tuple{Vararg{Int64,N}} where N) at show.jl:1837
Stacktrace:
 [1] summary(::Base.GenericIOBuffer{Array{UInt8,1}}, ::UnitRange{BigInt}, ::Tuple{Base.OneTo{BigInt}}) at ./show.jl:1846
 [2] summary at ./show.jl:1844 [inlined]
 [3] summary(::UnitRange{BigInt}) at ./show.jl:1831
 [4] top-level scope
```

`show` works fine though because it doesn't call `summary`. 

I'm happy to make a PR to fix `dims2string` to take in `<:Integer`.

**Comment by dlfivefifty** [comment]
Actually, I see no reason why `dims2string` or `inds2string` should have restriction on the types.

**Comment by JeffBezanson** [comment]
Yes, agreed. Feel free to remove the type restrictions.

**Comment by dlfivefifty** [comment]
It looks like there are a few types that don't yet support `BigInt`:
```julia
julia> reshape(BigInt(1):BigInt(10), BigInt(1), BigInt(10))
ERROR: MethodError: no method matching reshape(::UnitRange{BigInt}, ::BigInt, ::BigInt)
Closest candidates are:
  reshape(::AbstractArray, ::Int64...) at reshapedarray.jl:95
  reshape(::AbstractArray, ::Union{Int64, AbstractUnitRange}...) at reshapedarray.jl:90
  reshape(::AbstractArray, ::Tuple{Vararg{Int64,N}} where N) at reshapedarray.jl:92
```
I could try to tackle these issues in a more expansive PR.

PS Surprisingly, `view(a, BigInt(1):BigInt(3))` works fine apart from the printing bug.
PPS Motivation: when `BigInt` works well as an index, so does `∞` (https://github.com/JuliaApproximation/InfiniteArrays.jl)
