### ISSUE TITLE
redirect_stderr() and redirect_stdout() do not control logging output

### ISSUE THREAD

**Issue by gaika** [JuliaLang/julia#26798]
```
redirect_stderr()
redirect_stdout()
@warn "should not be able to see it"
```
The output is 
```
┌ Warning: should not be able to see it
└ @ Main t.jl:3
```
Expected no output.

**Comment by gaika** [comment]
And `@info` goes into `stderr` instead of expected `stdout`, not able to control it too.

**Comment by gaika** [comment]
Makes debugging harder, see https://github.com/timholy/Revise.jl/pull/80

**Comment by stevengj** [comment]
I think the problem is that `SimpleLogger` (the default logger) stores `stderr` as its `stream::IO` member, so it keeps a reference to the original `stderr` stream even when the `stderr` global has been redirected.

**Comment by staticfloat** [comment]
Not just `SimpleLogger`; `ConsoleLogger` does as well.  @c42f what, in your opinion, is the best way to change streams out from underneath a logger?  Should we destroy the current loggers and create new ones that point to the streams we like?

**Comment by maleadt** [comment]
It's what we do in the `atexit` hook: https://github.com/JuliaLang/julia/blob/665b1def2710f1f5d956b47c670034be0600ebb1/stdlib/Logging/src/Logging.jl#L55-L63
