### ISSUE TITLE
performance-improvement request: no run-time impact for @inferred

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#26809]
I recently learned on the discourse site (link below) that the `@inferred` macro from Base.Test, which determines whether the compiler is able to infer a concrete type for the result of a call, could be a very useful tool in development performant code.  It provides a straightforward means to confirm type stability (versus trying to understand the output of `code_warntype`).  The issue is that the current version of `@inferred` makes this determination via a run-time test and therefore has a significant impact on performance.   It seems that there should be a way for the compiler to assist `@inferred` so that there is no run-time impact and thus the macro can be used in production code.  So I would like to request that `@inferred` be rewritten as a compile-time test.

https://discourse.julialang.org/t/feature-request-type-assertion-for-compiler-known-type/10305/23

**Comment by fredrikekre** [comment]
`@inferred` is meant for testing (thats why it is in the `Test` stdlib). Why is performance important for this?

**Comment by yuyichao** [comment]
`@inferred` is not useful for that case at all. (It's also a test macro that should not be used in normal code.)

What you want in that post is not local to the expression so it's impossible to do so with a macro. It has to be done on the function as a whole, a function already provided by `code_warntype`. Suggestions to make `code_warntype` even easier to use is welcome but that does not belong to this issue.
