### ISSUE TITLE
Method redefinition does not take effect

### ISSUE THREAD

**Issue by s-broda** [JuliaLang/julia#26820]
Reduced from here https://discourse.julialang.org/t/julia-calls-the-old-method-after-method-is-redefined/10327/7:

Setup:
```
abstract type VolatilitySpec end
struct GARCH{p,q} <: VolatilitySpec end
struct ARCHModel{VS<:VolatilitySpec}
    ARCHModel{VS}() where {VS}=new()
end
ARCHModel(VS::Type{T}) where {T<:VolatilitySpec} = ARCHModel{VS}()

loglikelihood(am::ARCHModel{T}) where{T} = arch_loglik!(T)

function arch_loglik!(M::Type{GARCH{p,q}}) where {p, q}
    return 5.
end

function selectmodel()
    res = Array{ARCHModel, 2}(4, 4)
    for p = 0:3, q = 0:3
        res[p+1, q+1] = ARCHModel(GARCH{p, q})
    end
    crits = loglikelihood.(res)
end
```

Calling the method works as expected:
```
julia> arch_loglik!(GARCH{1, 1})
5.0
```
Now, call the function `selectmodel` (this step is crucial for reproducing the issue) and redefine the method (note no warning about the method redefinition):
```
julia> selectmodel();

julia> arch_loglik!{p, q}(M::Type{GARCH{p,q}}) = 1
arch_loglik! (generic function with 1 method)
```

However, the new definition doesn't take effect, despite `@code_llvm` showing the updated definition:
```
julia> arch_loglik!(GARCH{1, 1})
5.0

julia> @code_llvm arch_loglik!(GARCH{1, 1})

; Function Attrs: uwtable
define i64 @"julia_arch_loglik!_63633"(i8**) #0 !dbg !5 {
top:
  ret i64 1
}
```

**Comment by s-broda** [comment]
PS: This is on both 0.6.2 (Windows and Linux) and 0.7 latest nightly.

**Comment by s-broda** [comment]
Should this perhaps get a bug label? It seems that it may be related to #265 and its awesome fix by @vtjnash.

**Comment by Keno** [comment]
I can no longer reproduce this. There've been a bunch of bug fixes in this area. Can you try your original problem and see if the bug persists?

**Comment by s-broda** [comment]
My code is not compatible with 0.7 yet, so I can't test the original issue. I can confirm however that the MWE above is fixed on latest Windows nightly. Feel free to close.
