### ISSUE TITLE
Issue with eachmatch using unicode and regex pipes

### ISSUE THREAD

**Issue by lancebeet** [JuliaLang/julia#26829]
This call doesn't terminate (eachmatch produces an infinite iterator):
`collect(eachmatch(r"^$|\S", "ö"))`

The following calls do terminate:

```
collect(eachmatch(r"\S", "ö"))
collect(eachmatch(r"^$", "ö"))
match(r"^$|\S", "ö")
matchall(r"^$|\S", "ö")
```

Related issue(?): https://github.com/JuliaLang/julia/issues/26199

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Phenom(tm) II X4 965 Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, amdfam10)
```

**Comment by stevengj** [comment]
It seems like [this line](https://github.com/JuliaLang/julia/blob/c0e6b5ba8125f86d377edc2c8297365bf6427caf/base/regex.jl#L337) should be calling `ncodeunits` rather than `lastindex`.
