### ISSUE TITLE
Inference failure for known static parameters matched with unknown type

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#26827]
Reduced from a test failure in FFTW.jl:
```julia
julia> struct Foo{inplace,N}; end

julia> Foo{inplace,N}(X::StridedArray{Float32,N},Y) where {inplace,N} = Foo{inplace,N}()

julia> code_warntype(Foo{false,1}, Tuple{Any,Any})
Variables:
  X<optimized out>
  Y<optimized out>

Body:
  begin
      Core.SSAValue(0) = (Core.apply_type)(Main.Foo, $(Expr(:static_parameter, 1)), $(Expr(:static_parameter, 2)))::Type{Foo{_1,_2}} where _2 where _1
      Core.SSAValue(1) = (Core.SSAValue(0))()::Foo{_1,_2} where _2 where _1
      return Core.SSAValue(1)
  end::Foo{_1,_2} where _2 where _1
```
Compare with 0.6:
```julia
Variables:
  #self# <optimized out>
  X <optimized out>
  Y <optimized out>

Body:
  begin 
      return $(QuoteNode(Foo{false,1}()))
  end::Foo{false,1}
```
Remarks:
* Works if the type of `X` is known.
* Works if using a simpler type instead of `StridedArray`, e.g. `AbstractArray{Float32,N}`.
* Second parameter `Y` is irrelevant, but avoids cluttering the output from the `convert`/constructor deprecation method.
* Also fails without the `inplace` parameter, but I find it particularly puzzling that it is also affected.

**Comment by martinholters** [comment]
Ah, bisection points to 00b7ff82382025f2408729440611f97e7c026805 (https://github.com/JuliaLang/julia/pull/26012), and indeed, the modified
```julia
struct Foo{inplace,N}; end
Foo{inplace,N}(X::Union{Array{Float32,N},Val{N}},Y) where {inplace,N} = Foo{inplace,N}()
code_warntype(Foo{false,1}, Tuple{Any,Any})
```
fails (i.e. infers `Foo{_1,_2}  where _2 where _1` as the return type) on 0.6, too. So it's not actually inference that has regressed here, it's just that it's triggered now with the new definition of `StridedArray`.

**Comment by JeffBezanson** [comment]
The union is probably somehow pessimizing typevar value inference in subtyping.

**Comment by martinholters** [comment]
Hm, yes, that's unfortunate.  I think the following should give `svec(false,1)`, right?
```julia
julia> Base._methods_by_ftype(Tuple{Type{Foo{false,1}},Any,Any}, 10, typemax(UInt))[1][2] # sparams of match
svec(inplace, N)
```
Note also that
```julia
julia> Base._methods_by_ftype(Tuple{Type{Foo{false,1}},Array,Any}, 10, typemax(UInt))[1][2]
svec(false, 1)

julia> Base._methods_by_ftype(Tuple{Type{Foo{false,1}},Val,Any}, 10, typemax(UInt))[1][2]
svec(false, 1)
```
(And yes, `code_warntype(Foo{false,1}, Tuple{Array,Any})` and `code_warntype(Foo{false,1}, Tuple{Val,Any})` both show an inferred return type.)

**Comment by martinholters** [comment]
Poking at this again, I've reduced it to the following type-intersection problem:
```julia
julia> T1 = Tuple{Ref{Int},Any};

julia> T2 = Tuple{Ref{T},Union{Val{N}, Array{Float32,N}}} where {T,N};

julia> typeintersect(T1, T2)
Tuple{Ref{T},Union{Val{N}, Array{Float32,N}}} where N where T

julia> typeintersect(T2, T1)
Tuple{Ref{Int64},Any}
```
Ideally, it should give `Tuple{Ref{Int},Union{Val{N}, Array{Float32,N}}} where N`.

**Comment by martinholters** [comment]
Just realized this has a rather obvious cause:
https://github.com/JuliaLang/julia/blob/91d2071f0776ceb4c53bc95277ba967aaa0a5608/src/subtype.c#L2235-L2239
And sure enough, before that, `ans` is `Union{Tuple{Ref{Int64}, Base.Val{N}} where N, Tuple{Ref{Int64}, Array{Float32, N}} where N}`. But then it's just set to the second argument, which is exactly what we see above.

I've tried adding some code there to turn the `Union` of `Tuple`s into a `Tuple` of `Union`s, which seems to fix this issue, but it also turns
```julia
Union{Tuple{typeof(Base.promote_result), Type{Bool}, Type{#s58} where #s58, Type{Any}, Type{S}} where S,
      Tuple{typeof(Base.promote_result), Type{Bool}, Type{#s58} where #s58, Type{T}, Type{S}} where S where T<:Number}
```
into
```julia
Tuple{typeof(Base.promote_result), Type{Bool}, Type{#s58} where #s58, Union{Type{Any}, Type{T}}, Union{Type{S}, Type{S}}} where S where S where T<:Number
```
when building the sysimg which gives a segfault in `jl_method_table_insert`.

**Comment by JeffBezanson** [comment]
The segfault there sounds worth investigating; I can't think of a good reason that would happen with that type.

**Comment by martinholters** [comment]
Turns out the segfault was caused by me getting the GC rooting wrong. Fix that fixed everything builds and
```julia
julia> T1 = Tuple{Ref{Int},Any};

julia> T2 = Tuple{Ref{T},Union{Val{N}, Array{Float32,N}}} where {T,N};

julia> R = typeintersect(T1, T2)
Tuple{Ref{Int64},Union{Val{N}, Array{Float32,N}}} where N where N # 🎉

julia> R.var === R.body.var
true # is that a problem?
```
The double `where N` comes from separately unwrapping the two union members and then rewrapping the result twice. Is that a problem? Is there an easy way around?

I'll start the tests now and if that looks promising, I'll clean up the code and open a PR next week.

**Comment by JeffBezanson** [comment]
Nice. Yes, it would be best to avoid the double wrapping. Once the type is wrapped in one `where N`, `N` no longer has free occurrences in the type so the extra `where N` can be dropped. This logic is used by `jl_type_unionall`, so if you use that function it should be automatic.
