### ISSUE TITLE
Can't download pcre2 on https://ftp.csx.cam.ac.uk

### ISSUE THREAD

**Issue by Stargateur** [JuliaLang/julia#26846]
I don't really understand why this "https://ftp.csx.cam.ac.uk" exist cause I don't see why a ftp server should receive a HTTPS connection... and so that probably why it's doesn't work anymore, https://ftp.csx.cam.ac.uk refuse all connections.

**Comment by vchuravy** [comment]
The full tarball from https://github.com/JuliaLang/julia/releases/tag/v0.6.2 includes all the dependency sources.

x-ref #26848

**Comment by jhgoebbert** [comment]
Why is this issue closed?
If one downloads Julia from https://github.com/JuliaLang/julia/releases/download/v<version> and runs "make", the script trys to connect to https://ftp.csx.cam.ac.uk.
Shouldn´t this be fixed?

**Comment by jhgoebbert** [comment]
Thank you for the quick answer. We will move to 0.6.3 then.
