### ISSUE TITLE
replace `size(A, d1, d2, ds...)` with `size(A, (dims...))`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#26851]
Right now the general signature `size(A, dims...)` does different things depending on whether there are zero, one or many dimensions provided. It seems like it would be better to separate this into: no dimension argument, scalar dimension argument, and tuple dimension argument.

**Comment by StefanKarpinski** [comment]
Yes, the proposal would be that these three forms are supported:

1. `size(A)` --> `(sizes[1], sizes[2], ...)`
2. `size(A, d)` --> `sizes[d]`
3. `size(A, (dims...))` --> `(sizes[dims[1]], sizes[dims[2]], ...)`

**Comment by StefanKarpinski** [comment]
Or we could just deprecate it entirely...

**Comment by mbauman** [comment]
Supporting a tuple argument would be a bigger change. Many `size` methods don't constrain the dimension argument at all, and I think that's just fine.

This was only used within tests of `size` itself within the entire testsuite.  I think we'll be just fine without it.
