### ISSUE TITLE
ERROR: METADATA cannot be updated

### ISSUE THREAD

**Issue by programistawpf** [JuliaLang/julia#26866]
Internet is working
Win7 
Version 0.6.2 (2017-12-13 18:08 UTC)
Official http://julialang.org/ release
x86_64-w64-mingw32
`
julia> Pkg.update(
INFO: Updating METADATA...
ERROR: METADATA cannot be updated. Resolve problems manually in C:\Users\Analiza\.julia\v0.6\METADATA.
GitError(Code:ECERTIFICATE, Class:OS, user cancelled certificate check: )
macro expansion at .\libgit2\error.jl:99 [inlined]
#fetch#41(::Base.LibGit2.FetchOptions, ::String, ::Function, ::Base.LibGit2.GitRemote, ::Array{Abstract
1}) at .\libgit2\remote.jl:226
(::Base.LibGit2.#kw##fetch)(::Array{Any,1}, ::Base.LibGit2.#fetch, ::Base.LibGit2.GitRemote, ::Array{Ab`

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/26167
