### ISSUE TITLE
Boundschecking indexing an array with another array allocates

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26899]
```
julia> a = rand(5); b = [1,2,3];

julia> @btime checkbounds($a, $b);
  12.159 ns (1 allocation: 16 bytes)

julia> @btime checkbounds(Bool, $a, $b);
  4.465 ns (0 allocations: 0 bytes)
```

Splatting here allocates? Just a guess.

https://github.com/JuliaLang/julia/blob/9f5351c36abb1cc7c7e1df9b1b73df696401d13a/base/abstractarray.jl#L427-L431

**Comment by KristofferC** [comment]
So that is exactly the same function, just regenerated? So the problem is that the code we cached in the sysimg is inefficient?

**Comment by mbauman** [comment]
No, they're different — my `_throw_boundserror2` is varargs while the builtin one takes a tuple.  Simply regenerating it isn't sufficient.

**Comment by KristofferC** [comment]
Oh, sorry, I missed that.

**Comment by KristofferC** [comment]
```
julia> a = rand(5); b = [1,2,3];

julia> @btime checkbounds($a, $b);
  4.608 ns (0 allocations: 0 bytes)

julia> @btime checkbounds(Bool, $a, $b);
  2.941 ns (0 allocations: 0 bytes)
```
