### ISSUE TITLE
shell mode on windows sometimes corrupt the terminal state

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#26894]
repo `;ls` in windows REPL.

![image](https://user-images.githubusercontent.com/1282691/39179602-0030c2f8-47b5-11e8-87a0-987d231157b9.png)

Seems to work on 0.6.2. Can anyone repro?

**Comment by helgee** [comment]
Successfully reproduced, is this the `ls` from Git?

**Comment by helgee** [comment]
Seems to happen with all the utils shipped with Git for Windows:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.4939 (2018-04-24 02:56 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ef9168a6f8* (0 days old master)
|__/                   |  i686-w64-mingw32

shell> ..\\Programs\\Git\\usr\\bin\\echo.exe blob
blob

[7C[32m[1mjulia> [0m[0m
```

**Comment by KristofferC** [comment]
Perhaps we should add a 

`write(terminal, "\033c")` (reset the terminal state)

in the beginning of

https://github.com/JuliaLang/julia/blob/ef9168a6f8a7eb016519649e0dd2cf49f8a81648/stdlib/REPL/src/LineEdit.jl#L1180-L1185

**Comment by PetrKryslUCSD** [comment]
@KristofferC : This issue has been closed, but has the problem been solved? I can still see it happening with  Version 0.7.0-beta2.43...

**Comment by KristofferC** [comment]
How is this closed?

**Comment by PetrKryslUCSD** [comment]
Sorry, I meant #27782.
