### ISSUE TITLE
Change the name of the sort reverse keyword from `rev` to `reverse`

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#26911]
Might `reverse` be a better name than `rev` for the keyword argument to `sort`? 

I just tried "reverse" and discovered it didn't work. I'm not sure there are any other functions that take an argument to denote reverse order, but we do have the function `reverse(arr)` which is named that way.

**Comment by affans** [comment]
I would like to get on this. Is there a way to search the Julia code for the `sort` function? I don't even know where to start.

**Comment by nalimilan** [comment]
You can have a look at base/sort.jl. But better make sure this change is really wanted before spending time on it.

**Comment by noahhaasis** [comment]
Is this issue still up for grabs?

**Comment by nalimilan** [comment]
AFAIK it's not been decided whether this should be done or not.

**Comment by GregPlowman** [comment]
> It is worth noting that reverse(sort(a)) is not the same as sort(a, rev=true), which makes me somewhat less inclined to want to name the keyword reverse (the difference is that rev=true preserves order in stable sorts will reverse reverses it).

Not sure if it's relevant, but also note this difference:
```
Julia-0.7.0-DEV> sort(3:5, rev=true)
3-element Array{Int64,1}:
 5
 4
 3

Julia-0.7.0-DEV> reverse(sort(3:5))
5:-1:3
```

**Comment by JeffBezanson** [comment]
I don't have a strong opinion here; leaning somewhat against the change since we hardly need more things to do for 0.7 Ping @StefanKarpinski since I think he originally named this argument.

**Comment by StefanKarpinski** [comment]
I think that `rev` is a bit more convenient, indicates some difference and is the least churn.

**Comment by JeffBezanson** [comment]
I don't think this is worth the extra churn.
