### ISSUE TITLE
Support keyword args in anonymous functions with optional positional args

### ISSUE THREAD

**Issue by AndiMD** [JuliaLang/julia#26916]
The following behavior seems erroneous, or at least confusing to me:

These work:
```f(x=1;y=2)=x+y```
```(x;y=2)->x+y```
```(x=1,y=2)->x+y```

This errors:
```(x=1;y=2)->x+y```

ERROR: syntax: invalid assignment location "begin
    x=1
    y=2
end"

```versioninfo()```
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

**Comment by mbauman** [comment]
For reference, anonymous functions created with the `function` keyword were fixed in https://github.com/JuliaLang/julia/pull/19744.  Looks like we still need to fix this case.

**Comment by AndiMD** [comment]
@mbaumann: Unfortunately, there still seems to be an issue when the first parameter has a default value:
```
f = function(x=1; kwargs...) return x; end
f = function(x=1; y=2) return x+y; end
```

**Comment by mbauman** [comment]
Ah, I see now. Thanks for the correction.
