### ISSUE TITLE
Coalesce for mixed nothing/missing: bug and design issue

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#26927]
First let me report a bug:
```
julia> coalesce.([missing, nothing, Some(nothing), Some(missing)], "replacement")
ERROR: MethodError: convert(::Type{Union{Missing, Nothing, Some{Union{Missing, Nothing}}}}, ::Some{Nothing}) is ambiguous. Candidates:
  convert(::Type{Union{Missing, T}}, x) where T in Base at missing.jl:39
  convert(::Type{Union{Nothing, T}}, x) where T in Base at some.jl:21
Possible fix, define
  convert(::Type{Union{Missing, Nothing}}, ::Any)
```

But I have tracked it because I want to get back to #26661 and I have second thoughts about the fact that `coalesce` mixes handling `missing` and `Some`/`nothing`. It would help me if I understood why (maybe e.g. @nalimilan could explain or give a reference to an earlier discussion - I could not find it unfortunately).

The problem I have is that I feel that current `coalesce` is not very useful for handling missing values because `coalesce(Some(missing), "replacement")` returns `missing`, so e.g. this pattern to get rid of missings in a vector does not work (it worked in old *Missings.jl* package): `coalesce.([Some(missing), "a", "b", missing], "replacement")`.

My first reaction is to have separate function for `missing` and separate for `Some/nothing` but maybe there is some good reason to mix it.

**Comment by nalimilan** [comment]
Good catch about the `convert` bug. It's a pretty unlikely situation but we should handle it correctly. I'm not sure how to fix that though. These `::Type{Union{...}}` methods are terrible to manage. FWIW, defining the following function makes Julia crash when creating the array:
```julia
 Base.convert(::Type{Union{Missing, Nothing, T}}, x::Any) where {T} = convert(T, x)
```

Regarding the behavior of `coalesce`, the main reason it handles both `missing`, `nothing` and `Some` is that it's useful for all three cases, and it's not clear how we would name separate functions if we distinguished these behaviors. In practice I'm not sure it's a problem. What's the issue with `coalesce(Some(missing), "replacement")` returning `missing`? `Some(missing)` is definitely not a missing value, it's precisely a missing value protected by the `Some` wrapper to be able to distinguish it from standard missing values. Anyway I doubt actual use cases would mix `missing` and `Some` like that.

**Comment by bkamins** [comment]
The problem I have is that I would not like to have `Some(missing)` unwrapped when I use coalesce in "remove missing" mode. In particular, if I understand it correctly `Some` is designed to work with `Nothing` (and this is how it is documented). Unwrapping `Some(missing)` is a side effect only of the fact that now `coalesce` works on both `missing` and `nothing`.

I agree that the situation that we mix `missing` with `nothing/Some` will be rare. In the worst case we can write a clear documentation warning not to mix them, but I feel it is not clean. I would prefer two functions. One handling `missing` (it could have another name e.g. `fuse`) only and the other handling `nothing`/`Some` (this could keep `coalesce` name).

Alternatively `coalesce` could get a keyword argument `mode` with three traits:
* `missing` (only works with `missing`);
* `nothing` (only works with `nothing` and unwraps `Some`);
* *some third option* (default - this would be current behavior).
(or some other similar solution)

**Comment by nalimilan** [comment]
There's nothing special about `Some(missing)`, it's just like `Some(1)`. AFAICT the question is rather whether `coalesce` should replace `missing` given that it also replaces `nothing` and unwraps `Some`. We could obviously allow tweaking the behavior with a keyword argument as you suggest, but that would be really verbose, when the point of `coalesce` is to be short and convenient.

`coalesce` is the standard SQL (and dplyr) term for this operation, so I'd rather not use another one like `fuse`. `unwrap` would be a good term, but it only applies to `Union{Some{T}, Nothing}`, not to `Union{T, Nothing}`.

I guess one possibility would be to introduce `??` as the null-coalescing operator, and reserve `coalesce` to `missing`. That would be consistent with C# and Swift (for `??`), and with SQL and dplyr (for `coalesce`).



I've filed https://github.com/JuliaLang/julia/issues/26929 for the crash mentioned above.

**Comment by bkamins** [comment]
To show a situation that bothers me this is a simplified situation I had today:
```
julia> x = ["a", "b", missing]
3-element Array{Union{Missing, String},1}:
 "a"
 "b"
 missing

julia> y = [ismissing(v) ? missing : findfirst("a", v) for v in x]
3-element Array{Any,1}:
 1:1
 nothing
 missing
```

and now you cannot use `coalesce` meaningfully on such a vector.

My point is that for interactive use current `coalesce` is probably not a problem (as user will know what and why is being replaced) but for production code (e.g. writing a general purpose package) it is very easy to forget some use-case of `coalesce` and end up with a hard to catch bug in the code. Consider eg. some NLP processing package that would do processing similar to what I have given on the top.

**Comment by JeffBezanson** [comment]
I think coalesce should handle exactly one value specially; a different value requires a different function.

**Comment by JeffBezanson** [comment]
@vtjnash has proposed this patch:

```diff
diff --git a/base/some.jl b/base/some.jl
index f75a493d91..6b9e1c84b6 100644
--- a/base/some.jl
+++ b/base/some.jl
@@ -64,8 +64,8 @@ function coalesce end
 
 coalesce(x::Any) = x
 coalesce(x::Some) = x.value
-coalesce(x::Nothing) = nothing
-coalesce(x::Missing) = missing
+coalesce(x::Nothing) = error("no default value")
+coalesce(x::Missing) = error("no default value")
```

Basically, the idea is that `coalesce` can never return `nothing` or `missing` unless it was wrapped in `Some`. That effectively forces you to supply a "default value", e.g. `coalesce(x, y, Some(missing))`.

**Comment by nalimilan** [comment]
Throwing an error when the result would be `missing` or `nothing` could make sense, but AFAICT it wouldn't fix the difficulty that both `missing` and `nothing` values are replaced when they are mixed. @Keno's proposal to specify the sentinel value as the first argument would be more to the point. To be clear: we would retain the current behavior, but allow a more restrictive one when passing `missing` or `nothing` as the first value?

**Comment by Keno** [comment]
The idea of my proposal is that the sentinel value is optional. That way if you have a bunch of functions `f`,`g`,`h` that return either a value (other than `missing`) or `nothing`, `coalesce(f(), g(), h())` would just work.

**Comment by bkamins** [comment]
@Keno: yes - I understand this. But my question is: does there exist a realistic use case, when you use `coalesce` where you may get `nothing` or `missing` in the process and you want to skip over BOTH (effectively not knowing which one did happen).

**Comment by Keno** [comment]
This came up on the triage call, and I think the consensus was to create a separate function what takes an explicit predicate for this case instead. (Or just use `first(filter(x->x === nothing || x === missing, args)))`).

**Comment by nalimilan** [comment]
With https://github.com/JuliaLang/julia/pull/27157, `coalesce` throws an error when all arguments are `nothing`/`missing`. This strict behavior can always be made more permissive in 1.x since it wouldn't be breaking.

I've thought a bit more about how to handle the case where `missing` and `nothing` would be mixed, and it's not really possible to choose the sentinel value based on the first argument, unless you always require specifying it: if you don't know whether the first value is a "normal" value or whether it's supposed to indicate that the behavior should be strict, you can't change the behavior based on it. But `coalesce(Missing, x, y...)` or `coalesce(ismissing, x, y...)` would be fine.

**Comment by Keno** [comment]
> I've thought a bit more about how to handle the case where missing and nothing would be mixed, and it's not really possible to choose the sentinel value based on the first argument, unless you always require specifying it: if you don't know whether the first value is a "normal" value or whether it's supposed to indicate that the behavior should be strict, you can't change the behavior based on it.

Yes, that is part of the design. The idea would be that the most common case is that function would return either a sentinel or a value guaranteed not to be either sentinel (e.g. Union{Missing, Int}). It would be odd for a function to return either sentinel or a value. If a function does that, I agree the behavior is confusing, but the though was to make things as simple as possible for cases where the user knows things to be unambiguous (i.e. not requiring a first argument for the most common cases).

**Comment by nalimilan** [comment]
OK, got it. Basically we just need to add methods to handle cases where `nothing` and `missing` follow one another. I've added a commit to https://github.com/JuliaLang/julia/pull/27157, please tell me what you think. The main issue is that I find it hard to describe in simple terms.

**Comment by Keno** [comment]
The other approach that was discussed was to go back to having two separate generic function. One that unwraps `Some`, skips `nothing` and errors if nothing is found and one that skips `missing`.

**Comment by StefanKarpinski** [comment]
To give a concrete example of the first-argument-as-sentinel problem, suppose both `f()` and `g()` return `nothing` to indicate no value but can otherwise sometimes return `missing` (say because they're functions that operate on data frames or whatever). Then you can have code like this:
```jl
coalesce(f(), g(), 0)
```
If `f()` returns `missing` as a _value_ and `g()` returns `nothing` to indicate "no value", then you would get `nothing` when the intended behavior would be to `missing`. You could argue that the call should be `coalesce(nothing, f(), g(), 0)`, but it's far too easy for people not to do that and it would be better to require the caller to explicitly indicate which sentinel they want.

**Comment by StefanKarpinski** [comment]
How about calling that `unwrap` function `something`? As in it's guaranteed to return something. It also makes it unsurprising that it has to do with both `nothing` and `Some`.

**Comment by bkamins** [comment]
> I think we should define two domains, and have a function for each

This is exactly what I think is best from the very start.
