### ISSUE TITLE
what to do with `setrounding`?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#26935]
Although marked as experimental in the docs, it still triggers a lot of issues (#17926, #26801, #26934).  Perhaps we should unexport it, or deprecate it all together (functionality could be moved to a package).

cc: @dpsanders

**Comment by dpsanders** [comment]
Moving it to a package sounds reasonable.
We have effectively almost removed the dependence on `setrounding` in `IntervalArithmetic.jl`, at least for `Float64`, which was possibly its biggest consumer?

**Comment by dpsanders** [comment]
Basically rounding seems to be completely broken on Windows.

**Comment by JeffreySarnoff** [comment]
(a) unexport setrounding  (b) eventually favor rounding mode savvy mathops

**Comment by JeffreySarnoff** [comment]
Earlier this year, I wrote [DirectedRoundings.jl](https://github.com/JeffreySarnoff/DirectedRoundings.jl).  This is a small package that intends to make making good use of directing rounding directions.  The approach there lets setrounding do much of this governed crunching ... leaving to us the higher order engagements.  With the apparent sidelining of reliable and portable and subtype specific setrounding, do we have any winning way waiting?

**Comment by dpsanders** [comment]
I recently realised that this has negative consequences for MPFR, where the rounding is done in software and so works on any machine.

Perhaps it is enough to have `MPFR.setrounding` for that case?

**Comment by simonbyrne** [comment]
@JeffreySarnoff do you have an example?

**Comment by simonbyrne** [comment]
@dpsanders I intentionally kept `setrounding` to work for MPFR. But we could move it to the module.

**Comment by dpsanders** [comment]
@simonbyrne Thanks, I just realised that `setrounding` still worked for `BigFloat`.
It would seem sensible to move it to the module. Maybe it would make sense to change the module name to `BigFloats`?

**Comment by JeffreySarnoff** [comment]
I have no example, and no specific details.  I was testing some extended precision trig or arctrig functions and using BigFloat values for comparison -- one test failed and I tracked it back to BigFloat's value after redoing the work in Maple.  At the time, frustration and recordkeeping/filesaving were at odds.  The only detail I recall is 3 days of yuck.
