### ISSUE TITLE
Inlining changes the behaviour of `isdefined` and `getfield` on an ill-initialized value

### ISSUE THREAD

**Issue by Liozou** [JuliaLang/julia#26949]
I tried to manipulate the return value of `jl_new_method_uninit`, which is a function defined in `src/method.c`, but printing it causes a segfault. Having segfaults after doing a ccall is not that surprising but what startles me is that manipulating this value through `isdefined` or `getfield` does not yield the same result whether the functions are inlined or not. Is that normal?

```
julia> m = ccall(:jl_new_method_uninit, Ref{Method}, (Any,), Main); # Do not show

julia> function my_isdefined(x)
          isdefined(x, :sig)
       end
my_isdefined (generic function with 1 method)

julia> isdefined(m, :sig)
false

julia> my_isdefined(m)
true

julia> function my_getfield(x)
           getfield(x, :sig)
       end
my_getfield (generic function with 1 method)

julia> getfield(m, :sig)
ERROR: UndefRefError: access to undefined reference

julia> my_getfield(m)

signal (11): Segmentation fault
in expression starting at no file:0
jl_checked_assignment at /home/liozou/julia/src/module.c:624
unknown function (ip: 0x7fa2ad01f1d7)
Allocations: 2662909 (Pool: 2661212; Big: 1697); GC: 6
Segmentation fault (core dumped)
```

I'm working on 0.7-dev

**Comment by Keno** [comment]
> Is that normal?

Yes, the compiler is allowed to elide checks that it can statically prove don't get triggered for well formed objects. In this case, your object is likely not well formed, so BOOM.

**Comment by Liozou** [comment]
Alright. It seems that the check is wrong here because the value was created by a ccall and not through a Julia constructor. However, if it is possible to make values that have undefined fields (using `new`) correctly caught by `isdefined`, shouldn't it also be done for this `jl_new_method_uninit` function?

**Comment by Keno** [comment]
For julia-defined types the compiler looks at all constructors to determine the number of fields that are guaranteed to be initialized (for builtin types this is set manually). If you stick to julia itself, everything is safe. If you start poking at the runtime system using unsafe mechanisms, you need to be careful to not violate any invariants that the compiler usually guarantees for you (including not accessing invalid objects).

**Comment by Liozou** [comment]
Sure, I understand. OK thanks.
