### ISSUE TITLE
MIME/media type for .jl files

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#26947]
Would be nice if you could register something like `text/julia`. :)

**Comment by stevengj** [comment]
There's not even a `text/python` standard MIME type, so I doubt we could get IETF to accept `text/julia`.  But if anyone here is actually knowledgable about the registration process, please chime in.

However, I would just go ahead and use `text/julia` if you need a MIME type (the old `x-` prefix for unregistered MIME types is deprecated).

**Comment by fbruetting** [comment]
Rust already has `text/rust`, for example. I think you don’t need to register at IANA, more important would be to get an entry at XDG’s `mime.types` file.

**Comment by stevengj** [comment]
I see. Adding to the freedesktop.org registry sounds like a great idea. Do you know where one goes to propose additions? I can’t find a link at first glance.

**Comment by stevengj** [comment]
Ah, this is how Rust did it: https://bugs.freedesktop.org/show_bug.cgi?id=90487

**Comment by stevengj** [comment]
Any volunteers to submit a pull request to freedesktop.org?  The [rust patch](https://bugs.freedesktop.org/attachment.cgi?id=115844) looks pretty trivial to emulate.

**Comment by nalimilan** [comment]
We should also register .jld files at the same time, ideally with a "magic pattern" which allows detecting them even without the extension.

**Comment by MikeInnes** [comment]
Not sure about that, given the current state of JLD.jl.

**Comment by nalimilan** [comment]
We can leave magic bytes out for now if they are too likely to change. But it's useful to include .jld at least based on extension, and doing so right now ensures it will be available in distributions in the future when the format stabilizes. (I have no idea whether detection can start from the end of a file, but I imagine it would be relatively slow.)

**Comment by stevengj** [comment]
(There's no inherent reason why seeking to the end of a file would be slow, but I don't see any indication that `magic` supports this.)

I looked to see if the HDF5 format has any unused header space that can be used to tag a particular flavor of HDF5 file, but I don't [see anything usable](https://support.hdfgroup.org/HDF5/doc/H5.format.html#FileMetaData).

(`.jli` files already have magic bytes at the beginning.)

**Comment by stevengj** [comment]
Actually, maybe we could use the "File Driver Info" block in HDF5 to tag the file as JLD.

**Comment by fonsp** [comment]
The IANA MIME registry is also open to contributions, and it seems like the best place to make it "official".

The registration process is outlined here: https://datatracker.ietf.org/doc/html/rfc6838#section-5

**Comment by spaette** [comment]
The proposed iana registration is not indicated.

[f75cbe0d](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/commit/f75cbe0d37c990580dbb6f0694b53bc0c914d933) (GitLab)
Add text/rust for Rust source code
committed May 18, 2015

@nalimilan

Would a Julia Member submit an MR?

<hr>

MR submission [requires](https://gitlab.freedesktop.org/users/sign_in) opening an account or signing in, _e.g._  via a GitHub account.

data/freedesktop.org.xml.in

```diff
    </mime-type>
+   <mime-type type="text/julia">
+     <comment>Julia source code</comment>
+     <sub-class-of type="text/plain"/>
+     <glob pattern="*.jl"/>
+   </mime-type>
    <mime-type type="text/rust">
```

tests/mime-detection/list

```diff
  test.cr text/x-crystal ox
+ test.jl text/julia ox
  test.rs text/rust ox
```

tests/mime-detection/test.jl

```diff
+ println("hello world")
```

**Comment by spaette** [comment]
@ViralBShah 

One can see in the below *.desktop file a value for MimeType=.

https://hg.die-offenbachs.homelinux.org/eric/file/tip/src/eric7/data/linux  
eric7_ide.desktop

The foregoing is provided simply to demonstrate a specific use case of patching the [xdg/shared-mime-info](https://gitlab.freedesktop.org/xdg/shared-mime-info/) code.

If gitlab.freedesktop.org constitutes a GL instance, signing in via a GitHub account, would likely create a new instance account.

<hr>

I have https://github.com/JuliaLang/julia/issues/46681 currently open; that is linked to as only nominally relevant as it also addresses *.desktop files.

**Comment by spaette** [comment]
> not certain that the shared-mime-info devs request a test file
> for added languages; opening an Issue first might clarify that


@dfaure-kdab

Can you clarify whether a test file would be requested?

**Comment by dfaure-kdab** [comment]
Yes, a test file is always a very good idea. The above "patch" for share-mime-info looks ok to me.

**Comment by spaette** [comment]
A merge request can soon be opened with the "patch" and this Issue after merge can be closed.

A freedesktop.org GitLab instance account has been registered for which requires approval from the developers.

**Comment by spaette** [comment]
An MR has been opened and the pipeline passed.

This Issue can now be closed.

**Comment by nalimilan** [comment]
For reference, this was https://gitlab.freedesktop.org/xdg/shared-mime-info/-/merge_requests/202.

**Comment by spaette** [comment]
[fea642e9](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/commit/fea642e9a88fffc8fb14793a5cbd6c4031d4271b) (GitLab)
Add text/julia for Julia source code
committed Nov 5, 2022
