### ISSUE TITLE
DataFrame fill in NA with random values

### ISSUE THREAD

**Issue by cici7941** [JuliaLang/julia#26946]
I have a `DataFrame` like this
```
3×2 DataFrames.DataFrame
│ Row │ col1 │ col2 │
├─────┼──────┼──────┤
│ 1   │ "a"  │ NA   │
│ 2   │ "b"  │ 2    │
│ 3   │ "c"  │ 3    │
```
I was trying to replace `NA` with a replacement_val. It works fine when I replace the NA with an `Int`. However, when I was trying to replace the `NA` with a `String`, it throws an error (of course), but it fills in the `NA` in the `DataFrame` with a random number.
```
using DataFrames
df = DataFrame(col1 =["a", "b", "c"], col2 = @data([NA,2,3]))
df[isna.(df[2]), 2] = "x"
print(df)
```
`df` becomes 
```3×2 DataFrames.DataFrame
│ Row │ col1 │ col2 │
├─────┼──────┼──────┤
│ 1   │ "a"  │ 2    │
│ 2   │ "b"  │ 2    │
│ 3   │ "c"  │ 3    │
```

**Comment by mbauman** [comment]
Looks like this belongs over at the DataFrames.jl package — would you mind opening this issue there?  https://github.com/JuliaData/DataFrames.jl/issues/new

**Comment by cici7941** [comment]
May I ask when there will be a 0.6.3 release?
