### ISSUE TITLE
UndefVarError when calling a function of another .jl file

### ISSUE THREAD

**Issue by guillempuig** [JuliaLang/julia#26957]
Hi!
I'm using include("filename.jl") to add some functions "self-created" to my main run. Whereas I'm obtaining:
```
UndefVarError: function_name not defined
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80
```
I don't understand why once included the script containing the function "function_name" the system continues to not detecting it.

In case of need:
```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

I have found related posts but most of them where related to julia's packages, so I have not been able to solve my problem from there.

Thanks!

**Comment by KristofferC** [comment]
This is unlikely to be a bug with the language. You will likely get better help by posting this at https://discourse.julialang.org/. Please also include the content of `filename.jl`.

**Comment by ArchieCall** [comment]
A minimum working example (MWE) is needed for someone to help.  This would  be the actual file you are including and the main program.
