### ISSUE TITLE
Tiny bug for SymTridiagonalMatrix of size 1

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaLang/julia#26994]
Hi, I try to implement pentadiagonal matrix as close as possible to tridiag.jl and I found a tiny bug in it:
It is possible to build a SymTridiagonal matrix of size 1 (with a single elt).
In this case the method `A_mul_B!` (and others) has undefined behaviour (look for second elts inside @inbounds ).

I don't know if it is better to forbid single elt SymTridiagonal  or to protect the methods.
Best,

Laurent

**Comment by fredrikekre** [comment]
It would be helpful with an example of what is failing.

**Comment by LaurentPlagne** [comment]
```julia
a=SymTridiagonal{Float64}([1.0],Vector{Float64}(0))

b=ones(Float64,1)
c=zeros(Float64,1)
c=a*b
println("a=$a, typeof(a)=$(typeof(a))")
println("b=$b, typeof(b)=$(typeof(b))")
println("c=a*b=$c, typeof(c)=$(typeof(c))")

a=SymTridiagonal{Float64}([1.0],[3.0])
b=ones(Float64,1)
c=zeros(Float64,1)
c=a*b
println("a=$a, typeof(a)=$(typeof(a))")
println("b=$b, typeof(b)=$(typeof(b))")
println("c=a*b=$c, typeof(c)=$(typeof(c))")
```
returns
```
a=[1.0], typeof(a)=SymTridiagonal{Float64}
b=[1.0], typeof(b)=Array{Float64,1}
c=a*b=[0.0], typeof(c)=Array{Float64,1}
a=[1.0], typeof(a)=SymTridiagonal{Float64}
b=[1.0], typeof(b)=Array{Float64,1}
c=a*b=[3.0], typeof(c)=Array{Float64,1}
```
I do not know if it helps more than a direct look at the mul! methods (the name changed in master from the 0.62 version):
https://github.com/JuliaLang/julia/blob/2cab81442986590078dd6131a743095eaffa10f9/stdlib/LinearAlgebra/src/tridiag.jl#L151-L177
