### ISSUE TITLE
External profiling support

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#26999]
During the move to ORC from MCJIT (#22471), we lost the capability for using Intel VTunes and OProfile.
The build-system still has the remnants of the JITEVENTS support leading me on a merry chase, where the heck we register the listeners.
We also still mention it in the documentation.

It would be great if we could resurrect support for VTunes and OProfiles.

x-ref: https://github.com/JuliaLang/julia/pull/14727#issuecomment-386840042

**Comment by vtjnash** [comment]
> cf: http://lists.llvm.org/pipermail/llvm-dev/2017-October/118134.html and #22471 and NotifyGDB in jitlayers.cpp

or even, the JITEventListener::NotifyObjectEmitted support in debuginfo.cpp (under the name ORCNotifyObjectEmitted)

**Comment by maleadt** [comment]
#27466
