### ISSUE TITLE
make order irrelevant to ambiguous method warnings

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#270]
It would be nice to be smarter about giving these warnings, so that if the needed method is defined, say, before the end of a file, no warning is printed.

**Comment by timholy** [comment]
Wow, this is the 11th-oldest open issue. Fun!

**Comment by StefanKarpinski** [comment]
Thanks, @timholy – I actually strongly believe that this will improve the "feel of maturity" of Julia considerably. All those warnings when loading packages, even if they were harmless did not look good or give a warm and fuzzy feeling.

**Comment by timholy** [comment]
julia-0.5 just feels SO solid. Aside from having some amazing new features and fewer performance gotchas than ever, I am grateful on a nearly daily basis for the work ferreting out GC/dispatch/etc problems and things like the work done improving the line numbers in backtraces. It really adds up to a great experience.
