### ISSUE TITLE
Comprehension inside function destroys function argument

### ISSUE THREAD

**Issue by mobius-eng** [JuliaLang/julia#27004]
Consider the following function:

```julia
function foo(tmax, a, b, M, N)
    println("1: a=$a, b=$b, tmax = $tmax, M = $M, N = $N")
    tpts = [ tmax/M*i for i in 0:N ]
    println("2: a=$a, b=$b, tmax = $tmax, M = $M, N = $N")
    xpts = [ a+(b-a)/N*j for j in 0:M ]
    println("3: a=$a, b=$b, tmax = $tmax, M = $M, N = $N")
    return (tpts, xpts)
end
```

Argument `b` is nullified after the first comprehension:

```julia
(t1, x1) = foo(1.0, -1.0, 2.0, 10, 10);
```

Output:

```
1: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
2: a=-1.0, b=0.0, tmax = 1.0, M = 10, N = 10
3: a=-1.0, b=0.0, tmax = 1.0, M = 10, N = 10
```

Tested on 

```
Julia Version 0.7.0-DEV.4690
Commit 78c7d87369* (2018-03-23 22:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
```

and

```
Julia Version 0.7.0-DEV.5012
Commit 4339f7416a* (2018-05-05 21:39 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
```

[Discussion on Discourse](https://discourse.julialang.org/t/is-it-a-bug-in-comprehension/10725/8)

Maybe related to #26037

**Comment by sbromberger** [comment]
I canot reproduce with `Version 0.7.0-DEV.4727 (2018-03-31 15:54 UTC)`:

```
julia> (t1, x1) = foo(1.0, -1.0, 2.0, 10, 10);
1: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
2: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
3: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
```

**Comment by sbromberger** [comment]
I can't reproduce it with today's build either `Version 0.7.0-DEV.5021 (2018-05-06 00:40 UTC)`:

```
julia> (t1, x1) = foo(1.0, -1.0, 2.0, 10, 10);
1: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
2: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
3: a=-1.0, b=2.0, tmax = 1.0, M = 10, N = 10
```

**Comment by KristofferC** [comment]
Discourse:

> Would it be Windows specific? All failures are in mingw environment.

**Comment by JeffBezanson** [comment]
This reminds me of LLVM codegen bugs we've seen before such as #22582 and #19352.

**Comment by KristofferC** [comment]
Would be interesting to see it on a llvm 6 build. Not sure we managed to get out any windows nightlies with that yet though.

**Comment by StephenVavasis** [comment]
In case it helps, I've cut the example to an MWE, which is:
```
function foo(tmax, b)
    tpts = [1.1*i for i in 0:4 ]
    println("$b $tmax")
    nothing
end
```
and I've posted the LLVM of the MWE here: https://gist.github.com/StephenVavasis/18be8f27ea2098fed180ae2eab02f381 and the code native here: https://gist.github.com/StephenVavasis/e103ddef682ac74e772652d30f078033

**Comment by vtjnash** [comment]
I can repro on v0.6 with `-C sandybridge`, but the vectorizer choices changed so much by v0.7, that it isn't feasible to compare anymore, and the issue went away.

**Comment by vtjnash** [comment]
@yuyichao pointed me to `-C sandybridge,+prefer-128-bit`, which generates more similar code to v0.6, but still doesn't exhibit the bug: https://www.diffchecker.com/ibNJXB4I

But that also lets me see there's no issue with that code. The issue was that LLVM used to think it was okay to smash XMM6 inside `code_native(Base.collect_to!, (Array{Float64, 1}, Base.Generator{Base.UnitRange{Int64}, getfield(Main, Symbol("##1#2"))}, Int64, Int64))`. It was still correct to close though, since LLVM doesn't think that anymore.
