### ISSUE TITLE
vec doesn't always return a column vector

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#27001]
It seems that either the documentation of vec or the function itself should be modified:
```
julia> vec(0:8)
0:8
```
The docs say that `vec` returns a column vector.

**Comment by mbauman** [comment]
That is a column vector.  It's subtle, but throughout the documentation we consistently make a distinction between vectors and `Vector`s (and arrays/`Array`s).  Lowercase vector simply means a one-dimensional `AbstractArray`.  If you want a `Vector` you can use `Vector(0:8)`.

**Comment by StephenVavasis** [comment]
Got it, thanks!
