### ISSUE TITLE
svds gives wrong results for degenerate singular values

### ISSUE THREAD

**Issue by amiragha** [JuliaLang/julia#27009]
The `svds` code seems to assume the outcome of `eigs` is alternative positive and negative eigenvalues corresponding to the singular values of the original matrix. This is not always true when the singular values are degenerate. For example, for the following code gives false half of the time!
```
A = zeros(2,4)
A[2,1] = 1.0
A[1,4] = 1.0
for i=1:10
    fact=svds(A, nsv=2)[1]
    println(A ≈ fact[:U] * diagm(fact[:S]) * fact[:Vt])
end
```
I was able to fix my issue by changing the line (in the `svds` [source code](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/linalg/arnoldi.jl#L333-L381))
```
ind = [1:2:ncv;]
```
to
```
ind = findn(ex[1] .> 0)
```
Is this the best approach to fix it? Also, with this change, there will be no need for checking the sign of eigenvalues as well, which also simplifies the code following this line. 

-- Amir

**Comment by stevengj** [comment]
Yes, that makes sense to me.  Probably `ind = find(λ -> λ > 0, ex[1])` to avoid allocating the temporary array from `.>`.

**Comment by andreasnoack** [comment]
Dup of https://github.com/JuliaLang/julia/issues/16608 and fixed by https://github.com/JuliaLang/julia/pull/21701
