### ISSUE TITLE
undef warning during build after LLVM upgrade

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#27019]
```
In file included from /home/jeff/src/julia/usr/include/llvm/ADT/EpochTracker.h:19:0,
                 from /home/jeff/src/julia/usr/include/llvm/ADT/DenseMap.h:18,
                 from /home/jeff/src/julia/usr/include/llvm/PassRegistry.h:20,
                 from /home/jeff/src/julia/usr/include/llvm/PassSupport.h:26,
                 from /home/jeff/src/julia/usr/include/llvm/Pass.h:376,
                 from /home/jeff/src/julia/src/llvm-ptls.cpp:12:
/home/jeff/src/julia/usr/include/llvm/Config/abi-breaking.h:23:6: warning: "LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING" is not defined [-Wundef]
 #if !LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING
      ^
```

**Comment by vchuravy** [comment]
So this is a bit convoluted, the relevant PRs are:

- https://reviews.llvm.org/D27432
- https://reviews.llvm.org/D29919
- https://reviews.llvm.org/D30578

TL,DR: It seems Swift wants to opt out of the LLVM ABI checks, and to that effect a cmake flag was introduced that defaults to off,
for one reason or another LLVM migrated away from that cmake flag to only using a preprocessor flag. Which is now causing the undef warning.

IIUC we should simply add `-DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=0` to our preprocessor flags and maybe complain about this causing a warning upstream.

**Comment by vchuravy** [comment]
I have been swamped with JuliaCon, but yes I am planning to make a PR for
this.

**Comment by vchuravy** [comment]
Corresponding change in swift https://github.com/apple/swift/pull/7469

**Comment by vchuravy** [comment]
Should be fixed by #27182, but I still need to upstream that change.

**Comment by JeffBezanson** [comment]
This does not seem to be fixed for me. Is `make -C deps reinstall-llvm` sufficient?

**Comment by vchuravy** [comment]
Their should be a dependency edge between `reinstall-llvm` and the patches via `build-compiled` and `build-configured`.
Did LLVM recompile?

**Comment by JeffBezanson** [comment]
It did a bunch of stuff but IIRC it might have only re-copied files. Not sure it actually compiled anything.
