### ISSUE TITLE
Enum doesn't display UInt8 correctly

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#27025]
Hello,

Enum doesn't display UInt8 correctly

```julia
julia> @enum(MyEnum::UInt8,
  A=0x00,
  B=0x01,
  C=0xf0,
)

julia> Base.Enums.basetype(MyEnum)
UInt8

julia> MyEnum
Enum MyEnum:
A = 0
B = 1
C = 240
```

althought

```julia
julia> Base.Enums.basetype(MyEnum)(C)
0xf0
```

I was expecting

```julia
julia> MyEnum
Enum MyEnum:
A = 0x00
B = 0x01
C = 0xf0
```

Kind regards

**Comment by nalimilan** [comment]
Should be easy to fix, would you like to try making a pull request? In base/Enum.jl, the `Base.show` method should call `show` instead of `print` when printing the integer codes of values.

**Comment by scls19fr** [comment]
Thanks @guilhermeleobas you can do it
