### ISSUE TITLE
Performance example for simd is now non-effective

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#27029]
The example at https://docs.julialang.org/en/latest/manual/performance-tips/#man-performance-annotations-1 is now confusing.

~LLVM has learned some new mathematical identities so we now get;~
Things are now inlined that previously were not.

```
julia> timeit(1000,1000)
GFlop/sec        = 21505.376344086024
GFlop/sec (SIMD) = 14.103477212306695
```

**Comment by KristofferC** [comment]
Ok, adding `@noinline` to the functions is enough. Will put it into another PR with some other doc stuff.

**Comment by KristofferC** [comment]
But it feels a bit odd that we inline something with a loop like that?

**Comment by raminammour** [comment]
In this case, I think LLVM figured out that `s` was unneeded and optimized the whole first loop out (hence the very high Gflop/sec count). Why it didn't do the same with the second beats me!
If you just return `s`, or check that the results from the two sums are the same, there is no need for the `@noinline`.

p.s: I was tracking down another issue with `@simd` and I fell on this, sorry about the noise :)
