### ISSUE TITLE
Searching for @__DIR__ in the manual doesn't yield anything

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#27035]
`@__DIR__`: help in the REPL works, but the online manual search doesn't yield anything for this macro.

**Comment by tkoolen** [comment]
Strangely, `@__DIR_` does (on latest).

**Comment by fredrikekre** [comment]
Heh, did you mean to use only one trailing `_`? `@__DIR__` does not work, but `@__DIR_` does. Anyways, this is likely a Documenter problem (https://github.com/JuliaDocs/Documenter.jl/issues/720).

**Comment by tkoolen** [comment]
Yes.

**Comment by fingolfin** [comment]
This seems to be working fine now
