### ISSUE TITLE
CI: download test failing

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#27041]
This is now happening in almost every build, e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.26549/job/o1wf4032nc5k8nca

**Comment by vchuravy** [comment]
httpbin seems to have gone from reliable to unreliable. We could probably host it ourselves or use a different sitw

**Comment by ararslan** [comment]
Seems to have resolved itself?

**Comment by KristofferC** [comment]
Reopen if this keeps happening.

**Comment by StefanKarpinski** [comment]
The `httpbin` downloads are failing all the time again. I think it would be worth hosting these downloads elsewhere since this is getting really annoying.

**Comment by staticfloat** [comment]
We have our own copy of httpbin at `https://httpbin.e.ip.saba.us/`, hosted on OpenStack (As that's the default cloud provider that I have access to for Julia stuff).

Whether that's more reliable or not, who knows.  Personally, I'd rather we hosted it on AWS.

Perhaps allow for failover from the official httpbin to ours?

**Comment by StefanKarpinski** [comment]
Any reason we can’t just use AWS or GitHub for this?

**Comment by ViralBShah** [comment]
Yes, why not just use the JuliaLang AWS account?

**Comment by staticfloat** [comment]
Okay, sounds good.  https://httpbin.julialang.org is now hosted on AWS.

**Comment by StefanKarpinski** [comment]
Excellent! The httpbin site seems better for now so the urgency is lessened, but we should switch over to a site that we control.

**Comment by JeffBezanson** [comment]
Seems to be resolved?
