### ISSUE TITLE
Bug with `import` on Windows?

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/julia#27048]
This is an issue that seems to affect Windows users:
```Julia
julia> module  ModPlus
           +(r...) = Base.:+(r...)
       end
ModPlus

julia> import ModPlus: +

julia> module ModTimes
           *(r...) = Base.:*(r...)
       end
ModTimes

julia> import ModTimes: *
WARNING: ignoring conflicting import of Mod.* into Main
```
It seems that on Windows version of Julia, there is an issue with importing the `*` method.

For some reason, this is the only method that doesn't get imported.

I am actually not a Windows user, but this issue came up when I was checking the compatibility of my package. This issue does not happen on Linux or OSX and it is only specific to `*`.

Is this a bug? What's going on here?

A possible workaround is to do
```Julia
* = ModTimes.:*
```
but this is not an ideal solution.

https://discourse.julialang.org/t/bug-with-import-on-windows/10798

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/18769
