### ISSUE TITLE
similar breaks permutedims

### ISSUE THREAD

**Issue by mattm1** [JuliaLang/julia#27072]
Consider the following code sample:

    function type_testB(B::StridedArray)                                                            
        return typeof(similar(B, size(B)))                            
    end       

Then I get

    julia> bb_inp = reshape(eye(2^8), fill(2,16)...);
    julia> typeof(similar(bb_inp, size(bb_inp)))
    Array{Float64,16}
    julia> type_testB(bb_inp)
    Array{Float64,2} #<----------- wrong
    julia> bb_inp = reshape(eye(2^7), fill(2,14)...);
    julia> typeof(similar(bb_inp, size(bb_inp)))
    Array{Float64,14}
    julia> type_testB(bb_inp)
    Array{Float64,14}

I use Julia Version 0.6.2 (2017-12-13 18:08 UTC) on Windows 64 Bit.

The difference is just a function call. Yet it only fails for larger tupels. It works fine for `bb_inp = reshape(eye(2^n), fill(2,2*n)...); n < 8` Why? What is a workaround?

Consequences
-----------------
The main consequence is that this behavior breaks some other code.

I was trying to permute subsystems of a Kronecker product in Julia - it's a common mathematical operation.
I noticed that the implementation fails for larger matrices. See the following minimal working example:

    function test_permute(nn::Int)
        matid = eye(2^nn)
        perm = collect(1:nn); perm[1] = 2; perm[2] = 1;
        data = reshape(matid, fill(2, 2*nn)...)
        data = permutedims(data, [perm; perm + length(perm)])
        data = reshape(data, 2^nn, 2^nn)
        return sum(data-matid)
    end

First it creates an identity matrix of size `2^nn`, creates a permutation vector `perm` to swap subsystems `1` and `2`. Then `reshape(...)` decomposes the matrix into `2x2` "subvectors". `permutedims` reorders the "subvectors" and `reshape` composes them to a `2^n x 2^n` matrix.

`test_permute(2)` up to `test_permute(7)` works fine. But for `test_permute(8)` I get 

    ERROR: MethodError: no method matching checkdims_perm(::Array{Float64,2}, ::Array{Float64,16}, ::Array{Int32,1})
    Closest candidates are:
      checkdims_perm(::AbstractArray{TP,N}, ::AbstractArray{TB,N}, ::Any) where {TP, TB, N} at multidimensional.jl:1301
    Stacktrace:
     [1] permutedims! at .\permuteddimsarray.jl:132 [inlined]
     [2] permutedims(::Array{Float64,16}, ::Array{Int32,1}) at .\multidimensional.jl:1297
     [3] test_permute(::Int32) at .\REPL[50]:5

The respective code is given by:

    """ at .\multidimensional.jl:1297 """
    function permutedims(B::StridedArray, perm)
        dimsB = size(B)
        ndimsB = length(dimsB)
        (ndimsB == length(perm) && isperm(perm)) || throw(ArgumentError("no valid permutation of dimensions"))
        dimsP = ntuple(i->dimsB[perm[i]], ndimsB)::typeof(dimsB)
        P = similar(B, dimsP)
        permutedims!(P, B, perm)
    end

    function checkdims_perm{TP,TB,N}(P::AbstractArray{TP,N}, B::AbstractArray{TB,N}, perm)
        indsB = indices(B)
        length(perm) == N || throw(ArgumentError("expected permutation of size $N, but length(perm)=$(length(perm))"))
        isperm(perm) || throw(ArgumentError("input is not a permutation"))
        indsP = indices(P)
        for i = 1:length(perm)
            indsP[i] == indsB[perm[i]] || throw(DimensionMismatch("destination tensor of incorrect size"))
        end
        nothing
    end

    """ at .\permuteddimsarray.jl:132 """
    function Base.permutedims!(dest, src::AbstractArray, perm)
        Base.checkdims_perm(dest, src, perm)
        P = PermutedDimsArray(dest, invperm(perm))
        _copy!(P, src)
        return dest
    end

And one can see the same structure in `permutedims` as above.

**Comment by mbauman** [comment]
Very strange bug — thanks for the report.  I can reproduce on 0.6.2, but it appears to be fixed on master.

**Comment by mbauman** [comment]
I think we should be able to backport 4f1b479d755bad5d8e36a0d6a7ce3c70bcbbe484 or a minimal subset thereof.  I tried doing so but got stuck building release-0.6 ([no, not the obvious stucks](https://gist.github.com/mbauman/b8b70e64372b59e64ded33b3b24b39ef)).  I'll give it another shot next week if there's still an open window for 0.6.3.
