### ISSUE TITLE
Can not do cholesky decomposition 

### ISSUE THREAD

**Issue by coolestname** [JuliaLang/julia#27085]
I try to do chol decompose with the following matrix
Here is the matrix 
Σ = eye(4)
k₁ = 0.6
k₃ = 0.4
k₂ = sqrt(1-k₃^2)
var₁ = 1
Σ = [k₁^2+var₁ k₁*k₂ 0 k₁; k₁*k₂ 1 k₃ k₂; 0 k₃ 1 0;k₁ k₂ 0 1 ]

doing chol(Σ ) throws me error  Base.LinAlg.PosDefException(4)
But I can do the decomposition in Matlab with exactly the same matrix. Can anyone help with this?
 Thanks!

**Comment by haampie** [comment]
The matrix is singular, so the exception is corect. 

Are you sure you're doing the same thing in Matlab? Maybe you forgot to add the identity `Σ += [...]`?

**Comment by coolestname** [comment]
Yeah , I found the mistake, when I construct the cov matrix, I forget to add the var of error terms.  Thanks

**Comment by StefanKarpinski** [comment]
Glad you got this resolved. In general, questions like this should be asked on [discourse](https://discourse.julialang.org) not on GitHub until it's clear that there is definitely a bug to report.
