### ISSUE TITLE
Option to use PCRE2_UCP in regular expressions ("u regex flag)

### ISSUE THREAD

**Issue by digital-carver** [JuliaLang/julia#27084]
Per the [PCRE2 documentation](http://www.pcre.org/current/doc/html/pcre2pattern.html#extraprops): 

> 
> If the PCRE2_UCP option is set, the behaviour is changed so that Unicode properties are used to determine character types, as follows:
> 
>   \d  any character that matches \p{Nd} (decimal digit)
>   \s  any character that matches \p{Z} or \h or \v
>   \w  any character that matches \p{L} or \p{N}, plus underscore
>     
(This is only a subset of the changes, other parts of the documentation mention changes to POSIX character class interpretations among other things.)

There's a `const UCP = UInt32(0x00020000)` defined in `base/pcre_h.jl`, but it doesn't seem to be used for anything. It would be very useful to have a regex flag that allowed us to specify to the regex library when we wanted UCP set. 

Perl seems to automatically set its `/u` flag (http://perldoc.perl.org/perlre.html under "Character set modifiers") when in 'unicode_strings' mode, which is the default mode in recent Perl versions. Julia could do the same (since Julia is also in 'unicode strings' mode by default) and make PCRE2_UCP the default mode, but the PCRE2 documentation says "Matching these sequences is noticeably slower when PCRE2_UCP is set" - if that's still the case in practice and there's performance impact, then UCP can be left just as a non-default flag that the user can enable by saying, for eg., `match(r"\w+"u, "~~கசடதபற_2!! ")`. Currently this returns: 

```
ERROR: LoadError: ArgumentError: unknown regex flag: u
Stacktrace:
 [1] Regex(::String, ::String) at .\regex.jl:43
 [2] @r_str(::LineNumberNode, ::Module, ::Any, ::Vararg{Any,N} where N) at .\regex.jl:83
in expression starting at REPL[76]:1
```

**Comment by nalimilan** [comment]
Good catch. The current behavior doesn't sound very intuitive given that our strings are supposed to be Unicode:
```julia
julia> match(r"\w+", "café")
RegexMatch("caf")
```

So maybe we should make UCP the default, with a flag to disable it when performance is a concern and the caller only cares about ASCII .

**Comment by nalimilan** [comment]
Yes, that's why it would have to happen before 1.0.

**Comment by JeffBezanson** [comment]
Does anybody know what other languages do?

**Comment by digital-carver** [comment]
(Just some tentative info from some searching around - keep grains of salt handy, and please point out any errors you find in this.)

Perl automatically matches as if PCRE2_UCP was set, and so implicitly does Unicode Character Property-based matching by default. 

Python barely has any Unicode regex support in the default `re` module (Python 2 has practically no support). The `regex` module is commonly recommended for doing any Unicode matching in Python, and [that uses UCP matching automatically](https://bitbucket.org/mrabarnett/mrab-regex/src/3bdfdd3fe8ac4f8011353225edff5d86532ba2f6/regex_3/regex.py?at=default&fileviewer=file-view-default#regex.py-158), unless it's a bytestring or a string marked with the ASCII flag.

PHP, as far as I can tell, doesn't use PCRE2_UCP at all, things like `\w` and `[:alpha:]` always match only within the ASCII range. It's possible to use Unicode categories and script names with a `/u` suffix, which enables things like `\pL` and `\p{Greek}`. Based on those, people [bake](https://stackoverflow.com/a/16863679/8127) their own versions of the Unicode equivalents to `\w`, `[:alnum:]`, etc. (I believe Julia's current behaviour matches PHP's, except Julia doesn't need a suffix to enable `\p` patterns).

[ .NET documentation](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#WordCharacter) says it automatically uses UCP based matching for strings with Unicode encoding, which seems to be the default encoding. 

Ruby above version 1.9 uses the Onigmo library, [which is halfway between explicit and implicit UCP support](https://github.com/k-takata/Onigmo/blob/master/doc/RE#L239): for POSIX character classes like `[:alpha:]`, it uses Unicode properties automatically, as if PCRE2_UCP was set. For the shorthand character classes like `\w`, the Unicode property mode has to be enabled with `(?u)`: 
```
$ ruby -e 'print(/[[:alpha:]]+/.match("$café."))'
café
$ ruby -e 'print(/\w+/.match("$café."))'
caf
$ ruby -e 'print(/(?u)\w+/.match("$café."))'
café
```

Java 7 and above work similar to PHP, in that [UCP support has to be explicitly enabled](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#UNICODE_CHARACTER_CLASS) (with `Pattern.UNICODE_CHARACTER_CLASS` or `(?U)`).

**Comment by StefanKarpinski** [comment]
It does seem like we should use UCP by default. Possible transition path:

1. 0.7: add flags for turning UCP mode on and off
2. 0.7: deprecate not using either one — use the off flag to keep old non-UCP behavior
3. 1.0: remove warning for no-flag, flip its behavior from non-UCP to UCP

It's kind of annoying for everyone to need to add a flag to all their regexes and then delete it again, especially when they may well have wanted UCP behavior in the first place. We could potentially be smart about it and only give the warning for regular expressions whose meaning has changed.

**Comment by nalimilan** [comment]
Agreed. We could check whether the regex contains common patterns like `\w`, `[:alnum:]`, etc. IIUC the number of patterns affected by UCP [is limited](https://www.pcre.org/original/doc/html/pcrepattern.html).

**Comment by StefanKarpinski** [comment]
There is some dissenting opinion: https://discourse.julialang.org/t/regex-pcre2-and-the-pcre2-ucp-ucp-flag/10930.

**Comment by JeffBezanson** [comment]
I think we should just change the default and add a flag to enable the old behavior.
