### ISSUE TITLE
Markdown page is empty

### ISSUE THREAD

**Issue by cormullion** [JuliaLang/julia#27094]
There's an empty page in the v0.7 docs:

<img width="887" alt="screen shot 2018-05-14 at 11 35 31" src="https://user-images.githubusercontent.com/52289/39993379-90b53f3a-576d-11e8-8e58-2e5ded4abc0f.png">

from the file https://github.com/JuliaLang/julia/blob/master/stdlib/Markdown/docs/src/index.md.

I don't know what should go there, though.

**Comment by fredrikekre** [comment]
> I don't know what should go there, though.

Documentation about the Markdown stdlib :smile: .

Quite a lot of markdown docs now resides in the Documentation section of the manual, perhaps some should be moved here. From a quick look it seems that the Markdown module in general is poorly documented and, in particular, I find barely no docstrings.
