### ISSUE TITLE
Define `eval` and `include` consistently in non-bare modules?

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#27093]
When a module is defined generic functions for `eval` and `include` are added.  However, `eval` has two methods `eval([m::Module,] expr)` and `include` only one `include(str)`.  Shouldn't those be symmetric?  I would argue that the `eval(m, expr)` should be dropped; if one really wants to evaluate/include into another module (which should be rare), calling it via the `Core.eval`/`Core.include` is fine (or via `OtherModule.eval(expr)`). 

Removing one of the `eval`-methods would be a breaking change, adding one `include` method wouldn't be.

Edit: note that "my solution" is what the current docs of `eval` state:
```
help?> eval                                                                        
search: eval evalfile @eval @evalpoly bytesavailable readavailable TypeVar         
                                                                                   
  eval([m::Module], expr::Expr)                                                    

  Evaluate an expression in the given module and return the result. Every Module
  (except those defined with baremodule) has its own 1-argument definition of
  eval, which evaluates expressions in that module.
```
So, if no change to eval is made then the doc-string needs updating.

**Comment by JeffBezanson** [comment]
I agree that it's silly for every module to have `eval(::Module, expr)`. We should just remove that.
