### ISSUE TITLE
sortperm docs & stability

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#27112]
There's a couple issues with the docs and the internals of `sortperm`. The docs say:

>     sortperm(v; alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
> Return a permutation vector of indices of `v` that puts it in sorted order. Specify `alg` to
choose a particular sorting algorithm (see Sorting Algorithms). `MergeSort` is used by
default, and since it is stable, the resulting permutation will be the lexicographically
first one that puts the input array into sorted order – i.e. indices of equal elements
appear in ascending order. If you choose a non-stable sorting algorithm such as `QuickSort`,
a different permutation that puts the array into order may be returned. The order is
specified using the same keywords as `sort!`.

1. The default algorithm is `DEFAULT_UNSTABLE`, but the docs mention it's stable (MergeSort).
2. Even if one selects an unstable algorithm, the actual permutation is _always_ stable, because the `Perm` ordering is defined first by value, then by index.

What should the desired behaviour be?

I'd say: make sortperm's default algorithm DEFAULT_STABLE, remove the part in the binary op of Perm that forces stable sort. That way we have stable sort by default, but people can opt out if they need better performance.

**Comment by StefanKarpinski** [comment]
That's a bug: it should be stable. I'm not sure when this was introduced.

**Comment by haampie** [comment]
But after `alg::Algorithm=DEFAULT_STABLE`, should we change

```
function lt(p::Perm, a::Integer, b::Integer)
    da = p.data[a]
    db = p.data[b]
    lt(p.order, da, db) | (!lt(p.order, db, da) & (a < b))
end
```

to

```
lt(p::Perm, a::Integer, b::Integer) = lt(p.order, p.data[a], p.data[b])
```
?

**Comment by StefanKarpinski** [comment]
Ah I see. This was changed to use an unstable algorithm with a default comparison function that ensures stability. So it's not buggy, it's actually fine. Again, it would be good to look where this change was introduced and see if there's any documentation in the commit and/or PR that did the change.

**Comment by haampie** [comment]
So we should change the docs to reflect that sortperm is always stable irrespective of the algorithm.

But what about performance? `lt(p.order, da, db) | (!lt(p.order, db, da) & (a < b))` does not look very performant and would be a waste with a stable algorithm.

**Comment by StefanKarpinski** [comment]
I'm guessing this was actually done for performance. For a simple `lt` function (i.e. single-instruction) all that is probably no more than two CPU cycles (and no branches).
