### ISSUE TITLE
Automatic conversion from positive integers to UInt

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#27114]
When I write a function like `bla(x ::UInt)` for making sure that only positive values are allowed, invoking it by `bla(3)` leads to the error:
```
ERROR: MethodError: no method matching bla(::Int64)
Closest candidates are:
  bla(::UInt64)
```

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum. Julia never does automatic conversion of function arguments.

**Comment by krrutkow** [comment]
I have encountered situations in Julia where automatic conversion happens, which was unexpected. It was on creating a type instance though, not a function call.  On 0.6.2:
```julia
julia> struct bla
           x::UInt
       end

julia> bla(1)
bla(0x0000000000000001)

julia> bla(-1)
ERROR: InexactError()
Stacktrace:
 [1] bla(::Int64) at ./REPL[30]:2
 [2] macro expansion at ./REPL.jl:97 [inlined]
 [3] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

```
Whether that conversion behavior here is intended or not, I could see how it might lead to confusion about automatic conversion in Julia.

**Comment by StefanKarpinski** [comment]
There is still no "automatic conversion"; there is a constructor which does conversion by default:
```jl
julia> methods(bla)
# 3 methods for generic function "(::Type)":
[1] bla(x::UInt64) in Main at REPL[5]:2
[2] bla(x) in Main at REPL[5]:2
[3] (::Type{T})(arg) where T in Base at deprecated.jl:463
```
This is all documented in the manual:

https://docs.julialang.org/en/stable/manual/constructors/

Let's continue the conversation on Discourse if there's any further confusion.

**Comment by fbruetting** [comment]
This was not a question. When I create a function with an `UInt` argument, I expect being able to pass a positive integer. As this is not the case (with `3` being a perfectly valid unsigned integer), I see an implementation error here. That code works in all other languages I’m used to.

Seems like every number (by itself, without an assigned variable & type) is superfluously converted to `Int` first, which leads to the quoted error message, that a method with `Int` signature is missing. If you don’t see a problem here, I’d open a thread at discourse then.

**Comment by KristofferC** [comment]
This is not the place for this discussion. Open a thread on discourse. Continuing discussing here is heavily discouraged.

**Comment by StefanKarpinski** [comment]
@fbruetting, while I see what you're saying, that's just not how the language works. This is not an "implementation error": the literal `3` is always of type `Int` and no other type. There is no conversion, superfluous or not: `3` is syntax for producing an `Int`. As @KristofferC said, please feel free to ask further questions on Discourse.
