### ISSUE TITLE
SHA1 & UUID: avoid creating strings when showing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#27121]
See this comment: https://github.com/JuliaLang/julia/pull/27036#discussion_r187761249

> This seems suboptimal: It seems like we should have a bytes2hex(io, bytes) method that writes the hex digits to a stream rather than allocating a string. That way you can print the hex digits directly instead of allocating a string first.

This issue is about doing the refactoring of `hex2bytes` and these `show` methods so that SHA1 and UUID values can be printed directly to an output stream without needing to allocate their string representation.

**Comment by stevengj** [comment]
(The UUID output does not use `bytes2hex`.)

**Comment by fredrikekre** [comment]
#27124
