### ISSUE TITLE
Remove Pkg.dir from LOAD_PATH

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#27133]
Would be good to have it removed for alpha because it will be removed in 0.7. Will also force people to use the new package manager (or at least put in a little bit of work to avoid using it...).

**Comment by StefanKarpinski** [comment]
I have a simple patch to do this:
```diff
diff --git a/stdlib/Pkg/src/Pkg.jl b/stdlib/Pkg/src/Pkg.jl
index 11e1c03a8c..01f774a344 100644
--- a/stdlib/Pkg/src/Pkg.jl
+++ b/stdlib/Pkg/src/Pkg.jl
@@ -86,13 +86,6 @@ custom METADATA setup.
 """
 init(meta::AbstractString=DEFAULT_META, branch::AbstractString=META_BRANCH) = Dir.init(meta,branch)

-function __init__()
-    if !Base.creating_sysimg
-        vers = "v$(VERSION.major).$(VERSION.minor)"
-        push!(Base.LOAD_PATH, dir)
-    end
-end
-
 """
     edit()
```
That works, but I wanted a solution where doing `using OldPkg` automatically adds `Pkg.dir` to `LOAD_PATH`. However, it requires removing `OldPkg` from the sysimg which is a little tricky and I haven't quite gotten working yet (too much travel and other nonsense this week). But perhaps the fancy version is unnecessary and we can just tell people that they need to do `using OldPkg; push!(LOAD_PATH, OldPkg.dir)`. Thoughts?

**Comment by KristofferC** [comment]
Should remove the `using Pkg` in the precompile stuff in `loading.jl` as well.

**Comment by KristofferC** [comment]
I think this is done.
