### ISSUE TITLE
move stats functions from Base to StatsBase, move StatsBase to stdlib?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#27140]
It doesn't seem ideal to have a tiny number of stats functions in Base, and also have a StatsBase package. These could be consolidated and moved to the stdlib, possibly as `Statistics.jl`.

**Comment by nalimilan** [comment]
I've made that proposal before, so +1. A few things to discuss, some of which make the situation more complex:
- Which functions should be moved to stdlib? I guess `cor`, `cov`, `var`, `std` and `quantile`, but probably not `mean` nor `middle`?
- StatsBase currently depends on SortingAlgorithms (for radix sort), which would also have to be moved to the stdlib. I think that's a good idea anyway. There's also a dependency on DataStructures, but it's only used in one function (for heaps), so maybe we can work around it.
- We plan to have (actually, update) a Stats.jl meta-package which will load [all packages](https://github.com/JuliaStats/Stats.jl/pull/4) providing what people generally expect to have available by default for a statistical environment. So StatsBase is a better name than Statistics to avoid confusion; or we should call the meta-package AllStats, StatsEnvironment or something like that.
- I'm not sure we are completely happy with all the APIs provided in StatsBase. I know stdlib isn't guaranteed to remain completely stable, but we could also move only parts of StatsBase to the stdlib, and keep the StatsBase package in parallel for some time.

**Comment by JeffBezanson** [comment]
I think we should move everything listed under `statistics` in export.jl, which includes `mean`. Anything else seems too arbitrary.

**Comment by ViralBShah** [comment]
I would think that `mean` is more generally used and it could perhaps continue to be in Base as a reducer.

**Comment by fredrikekre** [comment]
Seems a bit iffy to to have a `*Base` library as a stdlib. Why can't we just move them out completely to a package, like we did with e.g. `FFTW`, `SpecialFunctions`, `QuadGK` etc?

**Comment by alanedelman** [comment]
Alright i'm obviously 6 months late to this discussion, but I really miss  `mean`.  Can we tell users where to look for some of the most common functions instead of the standard error message?  I'm thinking of undergrad users of Julia in classes, and new Julia users elsewhere?

**Comment by StefanKarpinski** [comment]
`using Statistics`
