### ISSUE TITLE
Reduction stage in "@parallel [reducer] for" seems not parallel

### ISSUE THREAD

**Issue by lchen91** [JuliaLang/julia#27142]
I read the related code about the macro @parallel and the function preduce. It appears that if there is a reducer in the "@parallel [reducer] for" statement, the reduction stage is not parallel and finished only on the calling process. My observation may be very wrong. If this is actually the case, does Julia have any plan to support true parallel reduction (i.e., performing the reduction in a parallel way)? Thank you!

**Comment by raminammour** [comment]
Not sure it is correct. Probably https://discourse.julialang.org/ is a bettter place for this conversation :)

```
julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @everywhere f(a,b)=(@show (myid(),a+b);a+b);

julia> @parallel f for i=1:4
       i^2
       end
        From worker 2:  (myid(), a + b) = (2, 5)
        From worker 3:  (myid(), a + b) = (3, 25)
(myid(), a + b) = (1, 30)
30
```

**Comment by lchen91** [comment]
Thanks Rami. I tested this code. You are right.

On May 18, 2018 at 11:48:07 AM, Rami (notifications@github.com) wrote:

Not sure it is correct. Probably https://discourse.julialang.org/ is a
bettter place for this conversation :)

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @everywhere f(a,b)=(@show (myid(),a+b);a+b);

julia> @parallel f for i=1:4
       i^2
       end
        From worker 2:  (myid(), a + b) = (2, 5)
        From worker 3:  (myid(), a + b) = (3, 25)
(myid(), a + b) = (1, 30)
30

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaLang/julia/issues/27142#issuecomment-390249618>,
or mute the thread

**Comment by vchuravy** [comment]
For questions like these discourse.julialang.org is a better place, please continue this discussion there.
