### ISSUE TITLE
Vararg version of hypot does overflow and underflow on master

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#27141]
The point of the `hypot` function is to avoid underflow and overflow, however the implementation of the vararg method introduced with PR #25571 defeats this purpose:
```julia
julia> hypot(1e200, 0, 0)
Inf

julia> hypot(1e-300, 0, 0)
0.0
```
Instead in Julia 0.6 it gives the correct result:
```julia
ulia> hypot(1e200, 0, 0)
1.0e200

julia> hypot(1e-300, 0, 0)
1.0e-300
```

**Edit**: I've just seen this was already pointed out in https://github.com/JuliaLang/julia/pull/25571#discussion_r162442508

**Comment by fredrikekre** [comment]
![img](https://user-images.githubusercontent.com/11698744/40198703-775651bc-5a17-11e8-92a4-bfe71daa0b1c.gif)

**Comment by stevengj** [comment]
Maybe just define:
```jl
hypot(x::Number...) = vecnorm(x)
```

**Comment by simonbyrne** [comment]
@stevengj I think the problem is that `vecnorm` is part of LinAlg.

One alternative would be
```julia
hypot(x,y,z...) = hypot(hypot(x,y), z...)
```

**Comment by stevengj** [comment]
That would be a performance trap, in that it would be much slower than expected. 

We can also just reimplement the relevant part of vecnorm: it doesn’t take more than a few lines to do the right thing.

**Comment by stevengj** [comment]
The following case gives an even worse failure due to integer wraparound:
```jl
julia> i = typemax(Int)
9223372036854775807

julia> hypot(i,i,i)
1.7320508075688772

julia> i*√3
1.5975348984942514e19
```
