### ISSUE TITLE
@cfunction macro does not work with locally defined functions

### ISSUE THREAD

**Issue by macd** [JuliaLang/julia#27215]
In 0.7 `@cfunction(f, ...)` complains about `f` not being defined if `f` is not in global scope.

Specifically, if we wrap the example from the manual in another function call:

```julia
function once_removed()
    function mycompare(a, b)::Cint
        return (a < b) ? -1 : ((a > b) ? +1 : 0)
    end
    mycompare_c = @cfunction(mycompare, Cint, (Ref{Cdouble}, Ref{Cdouble}))
end
```
it results in:
```
ERROR: UndefVarError: mycompare not defined
```
A workaround would seem to be to `$`-interpolate the name into the macro call, i.e.
```julia
function once_removed()
    function mycompare(a, b)::Cint
        return (a < b) ? -1 : ((a > b) ? +1 : 0)
    end
    mycompare_c = @cfunction($mycompare, Cint, (Ref{Cdouble}, Ref{Cdouble}))
end
```
but if we call once_removed as in  `a = once_removed()`, it results in 
```
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Any, (1,)}[typeof(Main.once_removed)], i=(2,))
rec_backtrace at /home/macd/julia/src/stackwalk.c:94
record_backtrace at /home/macd/julia/src/task.c:246
jl_throw at /home/macd/julia/src/task.c:577
jl_bounds_error_ints at /home/macd/julia/src/rtutils.c:187
getindex at ./array.jl:681
_widen_all_consts! at ./compiler/optimize.jl:666
_widen_all_consts! at ./compiler/optimize.jl:662
widen_all_consts! at ./compiler/optimize.jl:695
optimize at ./compiler/optimize.jl:331
typeinf at ./compiler/typeinfer.jl:436
typeinf_frame at ./compiler/typeinfer.jl:96 [inlined]
typeinf_code at ./compiler/typeinfer.jl:191
...
```
However, it seems that `a` is still a good function pointer for C or Fortran (at least my Fortran wrappers still seem to work OK)
```
julia> versioninfo()
Julia Version 0.7.0-DEV.5175
Commit 9f2f712* (2018-05-23 01:11 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by vtjnash** [comment]
The internal error appears to be a bug in the new optimizer.

The initial behavior is described explicitly in the first paragraph: https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code.html#Creating-C-Compatible-Julia-Function-Pointers-1

My favorite way to write this though is:
```julia
function once_removed()
    mycompare_c = @cfunction(function mycompare(a, b)::Cint
            return (a < b) ? -1 : ((a > b) ? +1 : 0)
        end, Cint, (Ref{Cdouble}, Ref{Cdouble}))
    return mycompare_c
end
```
It's admittedly a bit of a hack (since it makes use of the non-standard evaluation scope and order), since it's exactly the same as just declaring `mycompare` at the top-level earlier. But I like that it keeps the code together.

**Comment by StefanKarpinski** [comment]
> The internal error appears to be a bug in the new optimizer.

Can you work with @keno to get this fixed as appropriate?

**Comment by macd** [comment]
Ok, compiler bug I get, but I am uncertain about what you mean for 'initial
behavior'.  The link
you posted 404's on me and looking at that section of the manual (again) it
is not clear what
you are pointing to.  So is it the case that only top level functions can
be used with @cfunction?
This would be a problem for me since I construct functions on the fly and
then need to make
them into C functions.  If the $-interpolation is intended to work, then
that is a solution.

**Comment by StefanKarpinski** [comment]
https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#Creating-C-Compatible-Julia-Function-Pointers-1

**Comment by macd** [comment]
Hmmm, weird, I still get a 404, but no matter, I can certainly find that
section.
My guess is that you are referring to the following sentence in the manual.

"Like ccall, all of these arguments will be evaluated at compile-time, when
the containing method is defined."

My question is that I should still be able to define a function
programmatically, eval it, and
then pass it to @cfunction?  If not, then this is a serious issue for
interfacing with
C or FORTRAN optimization packages, as well as others.



On Wed, May 23, 2018 at 11:01 AM, Stefan Karpinski <notifications@github.com

**Comment by vtjnash** [comment]
You can’t do anything like that in C, so calling it a “serious issue” is nonsense. There are several alternatives described in the manual (specifically showing how to pass an unknown, custom ‘cmp’ function to qsort)

**Comment by macd** [comment]
OK, well "nonsense" sounds like a strong characterization.  Why should C
be the touchstone here anyway?  This worked just fine in Julia 0.6.  I will
look again
at the manual for the alternatives.
