### ISSUE TITLE
`atan2` as 2-arg method of `atan`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#27248]
Should `atan2` become a 2-argument method of `atan`?

The main argument against would be convention: `atan2` is well-established, going back at least to Fortran IV (1961).

The only languages I have found that do combine them are [Mathematica `ArcTan`](http://reference.wolfram.com/language/ref/ArcTan.html) and [Common Lisp `atan`](http://clhs.lisp.se/Body/f_asin_.htm).

**Comment by StefanKarpinski** [comment]
We could at least allow `atan(y, x)` as another way of writing `atan2(y, x)`.

**Comment by jrevels** [comment]
The convention is cemented enough that it has its own wikipedia entry under https://en.wikipedia.org/wiki/Atan2. The discoverability factor there might be a point in favor of keeping the current name.

**Comment by StefanKarpinski** [comment]
I would favor keeping two-argument `atan2` but also allowing `atan(y, x)`.

**Comment by jrevels** [comment]
I'm just bikeshedding here, but I don't think the proposed change renders a benefit that outweighs the detriment of exporting multiple names for the same operation. My preference is just to keep `atan2` due to convention.

**Comment by Sacha0** [comment]
> I'm just bikeshedding here, but I don't think the proposed change renders a benefit that outweighs the detriment of exporting multiple names for the same operation. My preference is just to keep atan2 due to convention.

I would begin arguing along the same lines as Jarrett, but instead conclude that discarding the relic of past programming languages' constraints that is `atan2` is best 😉.
