### ISSUE TITLE
inconsistency in indexing arrays in square brackets

### ISSUE THREAD

**Issue by michalsteuden** [JuliaLang/julia#27261]
Hi,
I am newbe here
I don't quite understand why using semicolons in square brackets while indexing arrays  throws an error? Is this intended or some kind of a bug? Here in this code A[i;j]   is the same as A[k] but will rise an error. I find this in some way inconsistent. 

```
julia> A = rand(1000);

julia> i = find(A.>.7);

julia> j = find(A.<.2);

julia> k = [i;j];

julia>

julia> A[i];

julia> A[j];

julia> A[k];

julia> A[i;j]   #this is the same as A[k] but will rise an error on Julia 0.6.2
ERROR: MethodError: no method matching typed_vcat(::Array{Float64,1}, ::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  typed_vcat(::Type{T}, ::AbstractArray{T,1} where T...) where T at abstractarray.jl:1080
  typed_vcat(::Type, ::AbstractArray, ::AbstractArray) at abstractarray.jl:1318
  typed_vcat(::Type, ::AbstractArray...) at abstractarray.jl:1319`
  ...

```

**Comment by fredrikekre** [comment]
> this is the same as A[k] but will rise an error on Julia 0.6.2


No, it is not the same thing. `k` is not `i; j`, `k` is `[i; j]`. `A[k]`  is equivalent to `A[[i; j]]`. In the future, please use https://discourse.julialang.org/ for questions.
