### ISSUE TITLE
Stop distributing the debug build in our downloads

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#27264]
Going forward, we should stop including the debug build of Julia in the default binaries.

**Comment by ViralBShah** [comment]
There's also some large DWARF symbol `.dSYM` directories on Mac. Can those be removed?

**Comment by JeffBezanson** [comment]
This doesn't seem to need an urgent decision.

**Comment by ViralBShah** [comment]
I'm happy to prepare the builds for this, but only if we have broad agreement at some point on if we are ok with the decision to drop the debug builds from the distribution. We don't have to stop building them.
