### ISSUE TITLE
Writing to IOBuffer from `@async`/`@sync`

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#27266]
Disclaimer: I'm not positive if this is an issue or just a behaviour change, but I didn't find an existing issue/topic on github or discourse.

## Issue
Specifically, the following sample code seems to run fine on 0.6, but fails on a recent nightly.

```julia
using Base.Test, Compat

struct Logger
    parent::Union{Logger, Compat.Nothing}
    handle::Union{IO, Compat.Nothing}
end

io = IOBuffer()

root = Logger(nothing, io)
a = Logger(root, nothing)
b = Logger(a, nothing)

function log(logger::Logger, str)
    @async begin
        if logger.handle !== nothing
            println(logger.handle, str)
        end
    end
    if logger.parent !== nothing
        log(logger.parent, str)
    end
end

function test()
    @sync log(b, "Foo")
    @test !isempty(String(take!(io)))
end

test()
```

If I remove the `@async` on nightly then it works again.

## versioninfo:
```
julia> versioninfo()
Julia Version 0.7.0-DEV.5214
Commit 14dbdf509a* (2018-05-24 11:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.5.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = /usr/local/bin/atom -n
  JULIA_HISTORY = /Users/rory/.playground/share/memento/.julia_history
  JULIA_PKGDIR = /Users/rory/.playground/share/memento/packages
```

The above code was using Compat 0.65.0

**Comment by JeffBezanson** [comment]
This is a behavior change, from #27164. `@sync` now only waits for `@async`s that are lexically inside its argument expression. This is intended to make it easier to reason about what things it will wait for, and closer to the semantics of e.g. Cilk.

**Comment by rofinn** [comment]
Yep, moving the `@sync` into the same function solved my issue. Thanks.
