### ISSUE TITLE
AppVeyor CI failures in starting workers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#27274]
There's a recurring failure on AppVeyor where it fails to start a worker and then hangs for the rest of the session:
```
Timed out waiting to read host:port string from worker.
      From worker 13:	ERROR: Timed out waiting to read host:port string from worker.
      From worker 13:	error at .\error.jl:33 [inlined]
      From worker 13:	read_worker_host_port(::Pipe) at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\cluster.jl:291
      From worker 13:	connect(::Distributed.LocalManager, ::Int64, ::WorkerConfig) at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\managers.jl:397
      From worker 13:	create_worker(::Distributed.LocalManager, ::WorkerConfig) at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\cluster.jl:501
      From worker 13:	setup_launched_worker(::Distributed.LocalManager, ::WorkerConfig, ::Array{Int64,1}) at C:\projects\julia\usr\share\julia\stdlib\v0.7\Distributed\src\cluster.jl:447
      From worker 13:	(::getfield(Distributed, Symbol("##47#50")){Distributed.LocalManager,WorkerConfig})() at .\task.jl:254
      From worker 13:	Stacktrace:
      From worker 13:	 [1] sync_end(::Array{Any,1}) at .\task.jl:221
      From worker 13:	 [2] macro expansion at .\task.jl:240 [inlined]
```
E.g.: https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.27132/job/c7n39lsfix6j2mi3

It would be nice to figure out what's going on here. Maybe some windows-specific race condition?

**Comment by Keno** [comment]
We also have another failure where the tests are handing and never complete, e.g. https://ci.appveyor.com/project/JuliaLang/julia/build/1.0.27135/job/707kib8lw7xwkje7

**Comment by Sacha0** [comment]
Ref. another, somewhat different (?), AV timeout: https://github.com/JuliaLang/julia/pull/27249#issuecomment-392624795. Best!

**Comment by Keno** [comment]
That looks like a network error, leading to a hang in the OldPkg testsuite. Ideally we should make sure that all network errors result in reliable failures of the test suite rather than hangs.

**Comment by StefanKarpinski** [comment]
Should we just stop running the OldPkg tests for now since we're deprecating/deleting it in 0.7/1.0?

**Comment by ViralBShah** [comment]
Yeah, it would be good to remove the OldPkg tests.

**Comment by KristofferC** [comment]
Not using AV anymore.
