### ISSUE TITLE
Make tests not fail if doc deployment fails

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#27292]
In https://travis-ci.org/JuliaLang/julia/jobs/384698968, the build failed because the docs could not be pushed. Presumably what happened is that it raced with another CI job to push a new version of the docs. That seems fine, and we should probably just ignore those failures and let the build succeed anyway.

cc @MichaelHatherly

**Comment by Keno** [comment]
Additionally, we should probably only have one of the CI workers push the docs. Right now I see three gh-pages commits per commit on master.

**Comment by fredrikekre** [comment]
That is strange, the idea is precisely that only Travis Linux 64-bit should try to push the docs. Why is the other workers not exiting here:
https://github.com/JuliaLang/julia/blob/746d08fdfe65888ca8a30e8cfa3ef2b439251d22/doc/make.jl#L1-L5
?

**Comment by fredrikekre** [comment]
Oh... I think we push when `make install`ing...
