### ISSUE TITLE
Short-form REPL error output

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#27305]
Error output can be thousands of lines using packages like Unitful and DifferentialEquations in the REPL. Its an insane amount of scrolling, and can cut off completely in some terminals.

Discussed on discourse:
https://discourse.julialang.org/t/units-errors-and-type-display/11220

Solution: REPL errors are shortened, and somehow don't print all the type information.
REPL.reshow_error() is there if you do need to see it all.

**Comment by phlavenk** [comment]
It would be also nice to be able to define aliases or alias patterns where one (may be the package author) could define them to improve type definition readability. 
```
Unitful.Quantity{Int64,Unitful.Dimensions{(Unitful.Dimension{:Time}(1//1),)},Unitful.FreeUnits{(Unitful.Unit{:Second,Unitful.Dimensions{(Unitful.Dimension{:Time}(1//1),)}}(0, 1//1),),Unitful.Dimensions{(Unitful.Dimension{:Time}(1//1),)}}}
```
would become `Quantity{Int64,Second}`  or even more compact `Int64|u"s"`.

**Comment by rafaqz** [comment]
Somehow the 0.63 update also made the REPL slower, and also slow down over time as some function of error length. I just waited 3 minutes for an error to print.

Any pointers on where to start having a crack at fixing this? errorshow.jl?

Also are there some stop-gap `Base.show()` overrides that will fix this temporarily? I can't get that to work so far.

**Comment by arnavs** [comment]
Checking in from the future: are there any packages or hacks which deal with this issue? 

Whenever something goes wrong, there's a lot of scrolling (sometimes hundreds or thousands of lines, as mentioned above.) And in the whole thing, I'm just looking for something like "tell me the function call/LOC."

**Comment by BioTurboNick** [comment]
Linking this up with #40138 and #40537

**Comment by phlavenk** [comment]
Check the amazing https://github.com/MichaelHatherly/InteractiveErrors.jl
