### ISSUE TITLE
Nanosoldier woes

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#27344]
Nanosoldier is down which is quite unfortunate since it is pretty much blocking performance relevant PRs and making releases without Nanosoldier means we have no idea what we are releasing...

@ararslan any ideas what is going on? Any interesting logs etc?

**Comment by ararslan** [comment]
It doesn't appear to be a problem with the server itself, which is the only log that isn't public. The build logs are available in https://github.com/JuliaCI/BaseBenchmarkReports. It seemed to start failing right around the Pkg3 change, but I've looked through the Nanosoldier code in https://github.com/JuliaCI/Nanosoldier.jl to see whether anything needed adjusting, but nothing appears to me to be heinously incorrect. Your knowledge of Pkg3 _far_ exceeds mine, Kristoffer, so I'd appreciate it if you could also look over the Nanosoldier code.

**Comment by KristofferC** [comment]
The build logs work fine so something errors when the execution starts. Are there no logs for that?

**Comment by KristofferC** [comment]
What is the state where Nanosoldier executes? Has it been updated at all for Pkg3 + removal of OldPkg.dir?

**Comment by KristofferC** [comment]
It seems that the problem now is the `std` movement? Can we do something about this quickly so we can get back to merging performance PRs?

**Comment by KristofferC** [comment]
Seems to work fine now.
