### ISSUE TITLE
Deploying julia packages once in the cloud (google dataflow)

### ISSUE THREAD

**Issue by guillempuig** [JuliaLang/julia#27342]
Hi everyone!

I'm trying to run my julia model in google dataflow. The issue is that I have to install Julia(>=v0.5.2) by an script of python (language supported in GCP) via subprocess statements because I need that the VMs I'm running each time install Julia language, givent the fact that after tu running of cloud process everything is deleted. The installation goes well so I have Julia(>=v0.5.2) installed in the cloud system. Nevertheless, I have to use certain Julia packages (as `ODBC, DataFrames, CSV, Distributions`,...) to run my model.
BUT, as I have to install julia every time I run the program in the cloud, I'm not able to use `Pkg.add("package_name")` and as result, I can not run my model beacuse packages are not available.

I have looked fo some solutions and I have found that there is the option of modifying the` juliarc.jl` file, and to run it before the run of my model. However, I haven't managed to make it work yet.

Any other possibility? Is there the possibility of writting a piece of code on the begging of my model(.jl file) so that it can be used in the following lines? Maybe including to the script `run(Pkg.add("pkg_name")`?

Thanks you,
Guillem

**Comment by fredrikekre** [comment]
Please use https://discourse.julialang.org/ for questions.
