### ISSUE TITLE
rename `.julia/compiled`?

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#27362]
Just a minor thing. The directory `.julia/compiled` contains the `.ji` code that is actually not yet "fully compiled" but only lowered.  This is a little bit confusing. Actually this of course includes the entire `precompile` terminology. If the plan is to at some point include native code in `.ji` files then one can stick with the notation of course.

**Comment by StefanKarpinski** [comment]
The plan is to eventually save llvm and/or native code in `.ji` files. Another way to look at it is that `.ji` files are compiled, we just have a very fancy linker.

**Comment by tknopp** [comment]
ok, if the plan is to but more native code into `.ji` images the folder name is fine.
