### ISSUE TITLE
julia default math weirdness and limitations

### ISSUE THREAD

**Issue by newcc4** [JuliaLang/julia#27372]
I've been trying out Julia lately and I noticed some weirdness with the default math library.

```
julia> 2^10
1024
julia> 2^62
4611686018427387904
julia> 2^63
-9223372036854775808
julia> 2^64
0
```
Everything after 2^64 gives 0.
There are two things to note here.
-  2^63 shouldn't return a negative number, because it clearly isn't negative
-  2^64 and onward shouldn't return 0, because it clearly isn't null

I did some tests on R for comparison and I think the behavior there is much better and maybe you should consider it for julia. (note I had to go to much higher values, because by default R is able to deal with higher numbers well beyond 2^62.)

```
> 2^10
[1] 1024
> 2^62
[1] 4611686018427387904
> 2^63
[1] 9223372036854775808
> 2^64
[1] 18446744073709551616
> 2^1022
[1] 44942328371557897693232629769725618340449424473557664318357520289433168951375240783177119330601884005280028469967848339414697442203604155623211857659868531094441973356216371319075554900311523529863270738021251442209537670585615720368478277635206809290837627671146574559986811484619929076208839082406056034304
> 2^1023
[1] 89884656743115795386465259539451236680898848947115328636715040578866337902750481566354238661203768010560056939935696678829394884407208311246423715319737062188883946712432742638151109800623047059726541476042502884419075341171231440736956555270413618581675255342293149119973622969239858152417678164812112068608
> 2^1024
[1] Inf

```

So in R `2^n` never gives either a negative number or zero.
Which is what somebody would expect.
When the number is too big for R, it gives `Inf` which is also not true, but closer to reality.
Something like `Ind` for indeterminate could be worth considering?

**Anyway, I just wanted to point out these things**
- **2^n should never return a negative number or zero**
- **by default R can calculate up to 2^1023, but julia can't go beyond 2^62**

**I'm very excited for Julia 1.0 and I hope it comes with a stronger math package by default after consideration.**

**Thanks all for the hard work, all things considered Julia is** ***SWEET!***

**Comment by pkofod** [comment]
https://discourse.julialang.org/t/a-plea-for-int-overflow-checking-as-the-default/3338

**Comment by andreasnoack** [comment]
Please take a look at the thread linked above and the documentation for Julia's integers. It is generally also a good idea to ask on Discourse first before filing and issue.

**Comment by newcc4** [comment]
Ok, now I understand why the desired behavior is the way it is.
Thanks for pointing to the discourse discussion and documentation.

So I decided to try with BigInt but I found the syntax very weird.
Is there any reason the first command doesn't work but the second does?
I'd say the second command is much less intuitive.


```
julia> BigInt(2^122)
0

julia> 2^(BigInt(122))
5316911983139663491615228241121378304

```

**Comment by nalimilan** [comment]
`BigInt(2^122)` is equivalent to `x = 2^122; BigInt(x)`, and as you've observed `2^122` gives `0` due to overflow.

**Comment by newcc4** [comment]
Got it, thanks.
But still don't understand why the second options works... `2^(BigInt(122))`

**Comment by mbauman** [comment]
Folks will be able to answer your questions much more effectively on the [discourse message board](https://discourse.julialang.org).  We try to reserve the issue tracker here to development tasks.
