### ISSUE TITLE
REPL printing slow in 0.6.3

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#27381]
Especially noticeable to me, because of:
https://github.com/JuliaLang/julia/issues/27305

Printing long errors slows during the error, the longer it is the slower it gets. 100% CPU the whole time is all used by Julia. This didn't happen in 0.6.2, some errors now take minutes to print.

Temp fix is overriding `Base.show(io::IO, frame::StackFrame; full_path::Bool=false)` but that's a little debilitating...

**Comment by YongHee-Kim** [comment]
Printing on a julia 0.6.3 REPL is getting slower over time 
This is test result on my Windows pc 
``` julia
using BenchmarkTools
const x = Array{Int}(50, 10)

@btime show(x) # 99.452 ms
@btime show(x) # 117.794 ms
@btime show(x) # 336.763 ms
@btime show(x) # 484.131 ms
```
But it's not slowing on Julia 0.7.0-beta 😃

**Comment by rafaqz** [comment]
Ok good to know its not just me, and there's an end in sight.. I waited 10 minutes for sensitivity analysis to print yesterday!

For error legibility until 0.7 is fully usable, I do this:
```julia
function Base.show(io::IO, frame::StackFrame; full_path::Bool=false)
    file_info = full_path ? string(frame.file) : basename(string(frame.file))
    print(io, " at ")
    Base.with_output_color(get(io, :color, false) && get(io, :backtrace, false) ? Base.stackframe_lineinfo_color() : :nothing, io) do io
        print(io, file_info, ":")
        if frame.line >= 0
            print(io, frame.line)
        else
            print(io, "?")
        end
    end
end
```

**Comment by KristofferC** [comment]
Haven't seen this happen on 0.7+. Please comment if this is still an issue.

**Comment by rafaqz** [comment]
Although the REPL is still pretty slow to print complex types, like Interact interfaces and large models with units.
