### ISSUE TITLE
Different behavior for loading in REPL and in script

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#27390]
The following works in the REPL, but not when the same functions are called from within a script:
```
julia> d = pwd()
"c:\\Users\\PetrKrysl\\devel\\CoNoGMOR\\investigations\\square_plate_hva"
julia> cd("../../../FinEtools/src")
julia> println("pwd() = $(pwd())")
pwd() = c:\Users\PetrKrysl\devel\FinEtools\src
julia> include("./FinEtools.jl")
Main.FinEtools
julia> cd(d)
```
From within a script the loading of `include("./FinEtools.jl")` fails:
```
julia> include("runsimadapt.jl")
pwd() = c:\Users\PetrKrysl\devel\FinEtools\src
ERROR: LoadError: could not open file c:\Users\PetrKrysl\devel\CoNoGMOR\investigations\square_plate_hva\FinEtools.jl
```
Apparently the file is being sought in the wrong folder (even though `pwd` says we are in the correct folder containing the file to be loaded).

**Comment by StefanKarpinski** [comment]
`include` works relative to the directory in which the current source file resides or the current working director if you're in the REPL. This allows sets of files that are "glued together" by relative `include` calls to be position-independent in your file system. So the `include("FinETools.jl")` call looks for `c:\Users\PetrKrysl\devel\FinEtools\src\FinETools.jl` in the REPL but looks for `c:\Users\PetrKrysl\devel\CoNoGMOR\investigations\square_plate_hva\FinEtools.jl` when it occurs inside of `c:\Users\PetrKrysl\devel\CoNoGMOR\investigations\square_plate_hva\runsimadapt.jl`.

**Comment by PetrKryslUCSD** [comment]
That makes a lot of sense. Thanks.

Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/
