### ISSUE TITLE
Missed package when constructing .toml files on CI

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#27421]
I can see the tests of my package fail on CI because StatsBase is not included in the project files (my package currently has the old structure w/o the .toml files):

https://ci.appveyor.com/project/PetrKryslUCSD/finetools-jl/build/job/fqch3ssgkd2l0jwf

**Comment by fredrikekre** [comment]
You need to list `StatsBase` in  your `REQUIRE` file (alternatively in a `test/REQUIRE` file if you only need it for testing purposes).

**Comment by PetrKryslUCSD** [comment]
The weird thing is, my REQUIRE files does not list ANY other packages that
are apparently successfuly added to the .toml files. I thought therefore
that the required packages were somehow computed on-the-fly and this one
was missed.

Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by KristofferC** [comment]
Stdlibs are added on the fly because there is no way to define these in REQUIRE files so it was the easiest way to be compatible with old and new packages while we are in a transition period.

**Comment by PetrKryslUCSD** [comment]
OK, that makes sense. Thanks.
Petr Krysl
Professor
University of California, San Diego
9500 Gilman Dr., #0085, La Jolla, CA 92093
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/
