### ISSUE TITLE
Segmentation fault in test/sparse/cholmod.jl test on Alpine Linux x86_64

### ISSUE THREAD

**Issue by tmh1999** [JuliaLang/julia#27431]
Hello,

We at Alpine Linux has been experiencing test failure with Julia on x86_64, both 0.6.2 and 0.6.3 versions.

With OpenBLAS 0.2.19, it used to build a while ago : http://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/julia/julia-0.6.2-r2.log
(backup: https://gist.github.com/tmh1999/e57ea4b21bef15f36c7adbc4de8bfadc)

but it currently fails.

With OpenBLAS 0.3.0, the same failure : http://build.alpinelinux.org/buildlogs/build-3-8-x86_64/community/julia/julia-0.6.2-r2.log
(backup: https://gist.github.com/tmh1999/d19bacde76d0b772afe87897eb416f64)

Our "recipe" and patches are at : https://git.alpinelinux.org/cgit/aports/tree/community/julia/. Please see APKBUILD for dependencies' versions. Failure happens in check() function in APKBUILD, doing $ make test.

Someone suggested the test error is related to : https://github.com/JuliaLang/julia/pull/26464 but I tried that and still didn't work on my local build machine.

Would you mind having a look ? Thanks

**Comment by tmh1999** [comment]
Failure happens in check() function in APKBUILD, doing $ make test.

**Comment by ViralBShah** [comment]
Closing this as an old issue. Please reopen if necessary.
