### ISSUE TITLE
math functions to move to SpecialFunctions.jl

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#27459]
* `lgamma`
* `gamma`
* `lfact`
* `beta`
* `lbeta`

**Comment by ViralBShah** [comment]
Sounds good. Where should they go?

**Comment by JeffBezanson** [comment]
SpecialFunctions.jl?

**Comment by StefanKarpinski** [comment]
`[l]gamma` and `[l]beta` should likely go in https://github.com/JuliaMath/SpecialFunctions.jl with the rest of the `*gamma` functions. `lfact` should probably be called `lfactorial` and live there as well, largely because it's implemented in terms of the `lgamma` function.

**Comment by dpsanders** [comment]
Or better `loggamma`, `logfactorial` etc.

**Comment by StefanKarpinski** [comment]
The `lfunction` convention is pretty standard but sure. We could also do `log(gamma)(x)`... not entirely sure if :trollface:ing or not...

**Comment by dpsanders** [comment]
`log(gamma)` is a neat idea.

**Comment by alanedelman** [comment]
+1 on log(gamma)

**Comment by freeboson** [comment]
FWIW, they're called `lbeta`, `lgamma` in R and Tensorflow

**Comment by StefanKarpinski** [comment]
I do think that `lbeta`, `lgamma`, `lfactorial` and `lbinomial` are fine names.

**Comment by freeboson** [comment]
Sorry if this is a dumb question, but how can you do `log(gamma)(x)`?

**Comment by freeboson** [comment]
Oh, I didn't know method names had their own unique types. Did you mean something like `log(typeof(gamma)) = x -> lgamma(x)`?

**Comment by ararslan** [comment]
`log(gamma)` is a fun idea in theory but you then lose the ability to sensibly overload `lgamma`, since `log(gamma)` would then return an anonymous function.

**Comment by andreasnoack** [comment]
It doesn't have to be anonymous. You could have `Base.log(::typeof(gamma)) = lgamma`

**Comment by ararslan** [comment]
Then what's the point of having `log(gamma)` if you still have `lgamma`...

**Comment by andreasnoack** [comment]
It looks better and `lgamma` doesn't need to be exported.

**Comment by martinholters** [comment]
`(log∘gamma)` would be more sensible than `log(gamma)`, but having this overload of `∘` would also be a very-hard-to-discover feature...

**Comment by StefanKarpinski** [comment]
Let's just stick with the more traditional names, i.e. `lgamma`, etc.

**Comment by pkofod** [comment]
Speaking of `lgamma`, I have a port of openlibm's lgamma that can be used in SpecialFunctions.jl.
