### ISSUE TITLE
build.log file disappears?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#27463]
In the process of updating packages for 0.7, I notice that building packages doesn't seem to leave the promised `build.log` file:
```jl
(v0.7) pkg> build ZMQ
  Building ZMQ → `~/.julia/dev/ZMQ/deps/build.log`
 Resolving package versions...

julia> isfile(homedir() * "/.julia/dev/ZMQ/deps/build.log")
false
```
By watching the directory in anothe terminal window, I see that an empty `build.log` exists while the build is occurring, but it never seems to contain anything, and it is apparently deleted when the build completes.  This doesn't seem very useful?

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaLang/Pkg.jl/issues/347
