### ISSUE TITLE
Move ARPACK out of Base

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#27460]
We now have functioning binary builders in the new JuliaLinearAlgebra org for:

https://github.com/JuliaLinearAlgebra/SuiteSparseBuilder
https://github.com/JuliaLinearAlgebra/ArpackBuilder

We also have 

https://github.com/JuliaLinearAlgebra/Arpack.jl

Plan is to move both these libraries out of stdlib into standalone packages.

cc @andreasnoack @staticfloat

**Comment by PallHaraldsson** [comment]
This one is done, right, so issue can be closed?

These where some of the final GPL-licenced, or the last ones, I can't easily locate other ones; except LGPL-licenced, e.g. GNU MPFR, that's one of the other two issues open with "excision" tag. To me Julia is GPL-free, unless I'm mistaken, as LGPL isn't too much of an issue (or dual-licenced or those with linking-exceptions).

**Comment by ViralBShah** [comment]
We moved ARPACK out, but there are challenges with SuiteSparse, which we can track separately.

**Comment by waldyrious** [comment]
> We moved ARPACK out

For reference, that was done in #27616

> there are challenges with SuiteSparse, which we can track separately.

#27638, I suppose?

**Comment by waldyrious** [comment]
@ViralBShah since #27638 has been closed, shouldn't the SuiteSparse removal be tracked elsewhere? Either a new issue, or perhaps reopening this one.

**Comment by ViralBShah** [comment]
At the moment, SuiteSparse and SparseArrays are closely related, and we need to move both together (or else people have to guess what functions are in which package). It is unlikely we will do that as it was quite confusing when we tried it out back then.

**Comment by waldyrious** [comment]
> It is unlikely we will do that

You mean moving both SuiteSparse and SparseArrays out of Base? (Note, I'm just trying to make sure the current thinking and potential next steps are recorded somewhere, since the related issues/PRs seems to be all closed at the moment.)

**Comment by ViralBShah** [comment]
Yes, it is either move both or no change. At least that is what I concluded.

**Comment by ViralBShah** [comment]
This discussion is best had in #27638 even though closed (where much of this has happened)
