### ISSUE TITLE
at-cfunction doesn't work on local variable

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#27464]
```jl
let foo(x)=x+1, Foo=Int, bar() = @cfunction(foo, Foo, (Foo,)), ptr = bar()
    ptr
end
```
gives `ERROR: UndefVarError: foo not defined`.  Encountered when testing JuliaLang/Compat.jl#566.  

@vtjnash, is this the intended behavior?

**Comment by KristofferC** [comment]
I thought you had to interpolate `foo` in this case.

**Comment by stevengj** [comment]
Ah, I see that this is documented, thanks.
