### ISSUE TITLE
Possible anti-pattern in creation of Rational from Integer

### ISSUE THREAD

**Issue by halleysfifthinc** [JuliaLang/julia#27471]
In [rationals.jl](https://github.com/JuliaLang/julia/blob/91d2071f0776ceb4c53bc95277ba967aaa0a5608/base/rational.jl#L79), the code for creating a Rational from an Integer is:

```julia
Rational{T}(x::Integer) where {T<:Integer} = Rational{T}(convert(T,x), convert(T,1))
```

should the denominator instead (as a more Julian/correct way of doing things) be:

```julia
Rational{T}(x::Integer) where {T<:Integer} = Rational{T}(convert(T,x), one(T))
```
I can open a PR if the change should be made.

**Comment by StefanKarpinski** [comment]
`convert(T, 1)` is the generic definition of `one(T)` for most number types but yes, it would probably be better to call `one(T)` instead. It's possible that this definition predates the existence of the `one` function (which means is very old).

**Comment by JeffBezanson** [comment]
If we know `T` is a subtype of `Integer`, I believe they should be equivalent.

**Comment by StefanKarpinski** [comment]
For `BigInt`, `convert(T, 1)` could be less efficient than `one(T)`. The latter can easily reuse a common pre-allocated instance of `big(1)` where as the former might naively reallocate a new one every time.

**Comment by halleysfifthinc** [comment]
I tested `convert` vs. `one` for BigInt:

```
julia> convertbigint() = convert(BigInt,1)
convertbigint (generic function with 1 method)

julia> onebigint() = one(BigInt)
onebigint (generic function with 1 method)

julia> @time convertbigint()
  0.000003 seconds (6 allocations: 200 bytes)
1

julia> @time onebigint()
  0.000003 seconds (6 allocations: 200 bytes)
1
```

It doesn't appear to be anything more than a cosmetic/style change. Do you want me to put together a pull request?

I also did a quick grep of the codebase for any other occurrences of `convert(T,1)` and found these:

```
test/fastmath.jl
77:        one = convert(T,1) + im*eps(real(convert(T,1)))

base/fastmath.jl
356:    atanh_fast(x::T) where {T<:ComplexTypes} = convert(T,1)/2*(log(1+x) - log(1-x))
359:    cosh_fast(x::T) where {T<:ComplexTypes} = convert(T,1)/2*(exp(x) + exp(-x))
372:    sinh_fast(x::T) where {T<:ComplexTypes} = convert(T,1)/2*(exp(x) - exp(-x))
```

I could also change those while I'm at it. FWIW I also compared `convert` and `one` for the Complex case and it also didn't seem to make a difference in terms of memory allocations.

**Comment by brenhinkeller** [comment]
Looks like this is fixed in the current https://github.com/JuliaLang/julia/blob/master/base/rational.jl
