### ISSUE TITLE
Window's splitdir bug?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#27498]
Our window `splitdir` regex appears to be wrong: the last two elements can never be matched (the 2nd element would always consume the match first).

Omus on Slack proposed:
> My Windows path knowledge may not be up to date but I think the regex needs to have all of the `[^\\]` changed to `[^\\:]`. I think this works as intended (also changed the second clause so the third gets used properly):
```
julia> function splitdrive2(path::String)
           m = match(r"^([^\\:]+:|\\\\[^\\:?]+\\[^\\:]+|\\\\\?\\UNC\\[^\\:]+\\[^\\:]+|\\\\\?\\[^\\:]+:|)(.*)$", path)
           String(m.captures[1]), String(m.captures[2])
       end

julia> splitdrive2(raw"\\?\UNC\a\b\c")
("\\\\?\\UNC\\a\\b", "\\c")

julia> splitdrive2(raw"\\?\a:\b\c")
("\\\\?\\a:", "\\b\\c")

julia> splitdrive2(raw"\\a\b\c")
("\\\\a\\b", "\\c")

julia> splitdrive2(raw"C:\dir")
("C:", "\\dir")```
```

**Comment by omus** [comment]
We may want to handle other reserved path characters as well. See: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx
