### ISSUE TITLE
Weird BoundsError on threaded loops causes segfaults

### ISSUE THREAD

**Issue by kozross** [JuliaLang/julia#27519]
If I put this program in a file ``test.jl``:

```
Threads.@threads for i in 13:33
    println(i)
end
```
And try to execute it with ``JULIA_NUM_THREADS=8 julia test.jl``, I get this as output:

```
[koz@Sebastian complete]$ JULIA_NUM_THREADS=8 julia test.jl

Error thrown in threaded loop on thread 1: BoundsError(a=Array{Task, 1}[], i=1)
Error thrown in threaded loop on thread 3: BoundsError(a=Array{Task, 1}[], i=1)
Error thrown in threaded loop on thread 2: BoundsError(a=Array{Task, 1}[], i=1)
Error thrown in threaded loop on thread 6: BoundsError(a=Array{Task, 1}[], i=1)28
29
signal (11): Segmentation fault
while loading /home/koz/documents/uni/research/phd/simd-paper/data/complete/test.jl, in expression starting on line 1
jl_apply_generic at /usr/bin/../lib/libjulia.so.0.6 (unknown line)
unknown function (ip: 0x7ffff7740aa9)
unknown function (ip: 0xffffffffffffffff)
Allocations: 830190 (Pool: 829160; Big: 1030); GC: 0
Segmentation fault
```

I've never experienced this kind of issue before. What could be the cause? ``julia --version`` outputs ``0.6.2``, and I'm on Gentoo Linux.

**Comment by StefanKarpinski** [comment]
Unless I'm mistaken, I/O is still not threadsafe, so this is expected.

**Comment by kozross** [comment]
@StefanKarpinski That's extremely surprising to me, since I've done I/O in threaded loops before without these kinds of issues. Admittedly it was file I/O, but I had threaded loops with only file I/O start failing recently as well.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14494
