### ISSUE TITLE
`sort` ERROR: UndefKeywordError: keyword argument dims not assigned

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#27527]
`sort` is suppose to be a column-wise function by default...
```
A = rand(3,3)
sort(A) == sort(A, dims = 1)
```
However, due to the current depreciation system,
```
sort(A)
ERROR: UndefKeywordError: keyword argument dims not assigned
```

**Comment by ararslan** [comment]
> `sort` is suppose to be a column-wise function by default...

What makes you say that? Note that in previous versions there's no `sort(A)` method at all for multidimensional arrays. This is consistent with that, except that the error message is clearer: you need to provide `dims` if you're sorting something with multiple dimensions.

**Comment by Nosferican** [comment]
Outdated documentation told me so...
```
In Julia, functions such as sort that operate column-wise by default (sort(A) is equivalent to sort(A,1)) do not have special behavior for 1xN arrays; the argument is returned unmodified since it still performs sort(A,1). To sort a 1xN matrix like a vector, use sort(A,2).
```
Should I make a PR to fix that? I can change `sort` to `maximum` which is column-wise by default.

**Comment by Nosferican** [comment]
I will work on it then. `maximum` and `minimum` are still column-wise by default.

**Comment by Nosferican** [comment]
Can we get the issue re-opened to track this?

**Comment by mbauman** [comment]
Would you mind just open a new issue instead? Otherwise the thread can be quite confusing in retrospect.

**Comment by Nosferican** [comment]
Sounds good.

**Comment by StefanKarpinski** [comment]
I'm fairly certain that `maximum` and `minimum` have never been column-wise by default:
```jl
julia> A = rand(3, 4)
3×4 Array{Float64,2}:
 0.493376  0.821977  0.822948  0.884212
 0.99451   0.601008  0.368455  0.519526
 0.267353  0.862873  0.939849  0.83221

julia> maximum(A)
0.9945103687378949

julia> minimum(A)
0.26735327121441355
```
