### ISSUE TITLE
syntax: invalid macro usage 0.7

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#27521]
I just recently found out, that you can actually do
```Julia
@macro(args...) do x
    ...
end
```
Not on 0.7 anymore though:
```Julia
julia> macro test(args...)
       println(args)
       end
julia> @test(test) do x
       println(x)
       end
ERROR: syntax: invalid macro usage "@(test(lol) do x
    # REPL[70], line 2
    println(x)
end)"
```
Is this a regression, or did this get removed?

**Comment by JeffBezanson** [comment]
This is probably due to changing the parsing of `do` to preserve the `do` syntax, rather than parsing it like other function calls. I think it could be made to work again though.

**Comment by SimonDanisch** [comment]
Awesome, thank you!
