### ISSUE TITLE
7z.exe gone

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#27522]
Does 7z not get shipped anymore on windows?
Just build master today with cygwin on windows and there is no 7z.exe anywhere in the julia folder (breaking e.g. WinRPM).

I checked my other julia installs, which I downloaded as binaries, and they all have 7z:
Julia 0.6.3
Version 0.7.0-DEV.5246 Commit 2edd482af4* (12 days old master)

**Comment by SimonDanisch** [comment]
Version 0.7.0-alpha.0 (2018-05-31 00:07 UTC) just downloaded from the website also has the 7z exe...

**Comment by ViralBShah** [comment]
Get on with the times, and move to BinaryBuilder. Bwahahahaha.

**Comment by ararslan** [comment]
Sounds like there's no issue here then, since the binaries have 7zip and source builds can still get it with the `win-extras` target.
