### ISSUE TITLE
unescape_string and `\$`

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/julia#27528]
On v0.6.x
```
Main> unescape_string("""\"\\\\\$ch\"""")
"\"\\\$ch\""

Main> unescape_string("""\"\\\$ch\"""")
"\"\$ch\""
```

and on v0.7: 
```
julia> unescape_string("""\"\\\\\$ch\"""")
"\"\\\$ch\""

julia> unescape_string("""\"\\\$ch\"""")
ERROR: ArgumentError: invalid escape sequence \$
Stacktrace:
 [1] unescape_string(::Base.GenericIOBuffer{Array{UInt8,1}}, ::String) at .\strings\io.jl:371
 [2] #sprint#336(::Nothing, ::Int64, ::Function, ::Function, ::String) at .\strings\io.jl:99
 [3] #sprint at .\<missing>:0 [inlined]
 [4] unescape_string(::String) at .\strings\io.jl:325
 [5] top-level scope
```

Is this change intended?

**Comment by StefanKarpinski** [comment]
Yes, it is: https://github.com/JuliaLang/julia/issues/21284. `escape_string` supports some configurable escaping but `unescape_string` does not.

**Comment by ZacLN** [comment]
Ta

**Comment by StefanKarpinski** [comment]
If you really need it, we could add support for what extra escape characters to allow in `unescape_string`, but if you don't need it now it would be preferable to put it off into the future.

**Comment by ZacLN** [comment]
Can I (or what do I need to include in terms of licensing) drop in the old implementation to CSTParser for now?

**Comment by StefanKarpinski** [comment]
If CSTParser is MIT-licensed, you can just copy it.

**Comment by ZacLN** [comment]
Sorted, cheers
