### ISSUE TITLE
No reduction functions should be column-wise by default (update code and docs)

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#27532]
There still outdated documentation and functions that still have a column-wise by default behavior. These should be updated to taking the `dims` argument and the documentation should reflect the change.

**Comment by Nosferican** [comment]
Some cases identified,
- https://docs.julialang.org/en/latest/manual/noteworthy-differences/
```
In Julia, functions such as sort that operate column-wise by default
(sort(A) is equivalent to sort(A,1)) do not have special behavior for 1xN
arrays; the argument is returned unmodified since it still performs sort(A,1).
To sort a 1xN matrix like a vector, use sort(A,2).
```

**Comment by JeffBezanson** [comment]
`sort` does require the `dims` argument now. I think this is just a doc issue?

**Comment by Nosferican** [comment]
If all functions are have been updated, yes. Is there any reason for why `sort` API is different from other functions,
```
using LinearAlgebra
A = rand(3,3)
maximum(A) == maximum(A[:,:])
norm(A) == norm(A[:,:])
mean(A) == mean(A[:,:])
```
while `sort`
```
sort(A)
ERROR: UndefKeywordError: keyword argument dims not assigned
```
shouldn't it be,
```
sort(A) == sort(A[:,:])
```
for consistency?

**Comment by JeffBezanson** [comment]
Those functions are reductions that have always operated over the whole array, unlike `sort`.
