### ISSUE TITLE
recent benchmark regressions

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#27539]
Identified in https://github.com/JuliaLang/julia/commit/2ba3fbbd4ffb03eda89c942ce9bc422e265e3c86#commitcomment-29323024

**Comment by fredrikekre** [comment]
Quoting Jamesons comment from the link:

> Looks like the test for `atan2` needs to be updated (now deprecated to `atan`) and the following were broken sometime since it last ran (vs = [daily_2018_5_23](https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/daily_2018_5_23/report.md)):
>  - sumlinear_view
>  - collection iteration (Dict, Set, Vector)
>  - lufact Tridiagonal factorization
>  - problems: go_game, parse_json, grigoriadis_khachiyan, laplacian, spellcheck, stockcorr, ziggurat
>  - simd: conditional_loop, loop_fields!, manual_example!, sum_reduce, two_reductions
>  - string join
> 
> https://github.com/JuliaLang/julia/compare/79486b3f66c261f95326728de3bf92b25c43a7d4...2ba3fbbd4ffb03eda89c942ce9bc422e265e3c86 [173 commits]

`lufact` is most likely due to the deprecation too.

**Comment by vtjnash** [comment]
I think I've fixed string join. Do we know if any of the others have been addressed? When we run a benchmark comparison against v0.6, it would be helpful to add that link here also.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/27030

Has updated benchmark runs.

**Comment by KristofferC** [comment]
`sumlinear_view` regression dissappear when `@simd` is removed.

**Comment by vtjnash** [comment]
OK. The rest seem to be fixed too now, I'll merge this into #27685
