### ISSUE TITLE
nullspace() function doesn't produce right values?

### ISSUE THREAD

**Issue by Tomkaehst** [JuliaLang/julia#27531]
When I try to determine the nullspace of some matrices, Julia is producing a lot of floating point numbers. The general "direction" of the null space is correct.

`M = [1 -1 0 0 -1 0; 0 1 -1 0 0 0; 0 0 1 -1 0 1]`
`nullspace(M)`
`6×3 Array{Float64,2}:
  0.243884   0.68145    -0.243884
  0.406912  -0.0466822  -0.406912
  0.406912  -0.0466822  -0.406912
  0.703456  -0.0233411   0.296544
 -0.163028   0.728133    0.163028
  0.296544   0.0233411   0.703456`

or

`M = [1 -1 0 0 0; 0 0 -1 1 0; 0 0 1 -1 0; 0 0 0 0 1]`
`nullspace(M)`
`5×2 Array{Float64,2}:
  0.707107      0.0     
  0.707107      0.0     
 -1.11022e-16  -0.707107
 -1.11022e-16  -0.707107
  0.0           0.0`

The example from the documentation does work (https://docs.julialang.org/en/v0.6.2/stdlib/linalg/). 

Has anyone an idea what could be the problem here?

Thanks in advance,
Tom

**Comment by andreasnoack** [comment]
The `nullspace` function is based on the SVD so the input matrix is converted to floating point values. We currently don't have a rational nullspace function. Please ask questions on discourse.julialang.org.
