### ISSUE TITLE
Incorrect alignment of nested colored output

### ISSUE THREAD

**Issue by HarrisonGrodin** [JuliaLang/julia#27540]
When calculating the maximum width for an expression, the `show` function for `AbstractDict` fails to take into account the fact that ANSI formatting codes do not take up character space. Thus, the output of other pairs within an `AbstractDict` can appear to be shifted unnecessarily.

Additionally, when shortening output to fit the screen, the ANSI codes are sometimes be split apart, showing strange filler characters and recoloring the arrow `=>` and remaining output based on the previously-set color.

![screenshot](https://user-images.githubusercontent.com/25474424/41266214-f818399a-6dc3-11e8-94a7-b4131b64862a.png)

(Note: produced within an `xterm-256color` terminal.)

**Comment by vtjnash** [comment]
One fix fix may be https://github.com/JuliaLang/julia/pull/27430. I haven’t implemented it there yet though.

**Comment by HarrisonGrodin** [comment]
This issue also applies to arrays of pairs.

![array of pairs](https://user-images.githubusercontent.com/25474424/41813826-98cb822a-770b-11e8-81b0-d26b97987033.png)

**Comment by vtjnash** [comment]
Not just limited to that either, an Matrix has the same issue:
![image](https://user-images.githubusercontent.com/330950/41814170-7b49d1c2-7713-11e8-933a-9be8a039f18a.png)

In #27430, I've got this printing correctly for Dict now. The matrix code is more complex, so I'm only partway done with fixing it there.

**Comment by laborg** [comment]
Fixed by
https://github.com/JuliaLang/julia/pull/45521
https://github.com/JuliaLang/julia/pull/37568
