### ISSUE TITLE
SSAValue objects should not occur in an AST

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#27556]
Julia: Commit 4420717206* (0 days old master)
```Julia
julia> Expr(:return, Core.SSAValue(1))
ERROR: syntax: SSAValue objects should not occur in an AST
```
I guess I can see where that's coming from, but do we really want to error when displaying valid IR?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/27546
