### ISSUE TITLE
Standards for machine-readable package metadata

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#27567]
The new package manager allows for `project.toml` to store metadata. However, in order to maximize the benefits from this system it necessary to adopt certain standards that allows the information to be systematically parsed (i.e., machine-readable). This information can help registries better serve the community as well as other potential tools (e.g., citation packages, C.I. tools, etc.)

In order to get the discussion started I wanted to provide a first proposal and gather the thoughts of the community.

```
name = "MyPkgName.jl"
desc = "Example Package."
uuid = "some UUId4 that determines where the source is"
repository = "https://github.com/User/Name"
package_status = "Production/Stable"
maintainer = "Shepard, Jane [Maintainer] <jane@shepard.edu>"
keywords = ["examples", "documentation"]
versions = ["1.0.0"]

[license]
id = "MIT" # SPDX ID
attribution = ["Smith, John [Author, Creator] <john@smith.com>",
               "Shepard, Jane [Maintainer] <jane@shepard.edu>"]
year = 2020
uses_components_with_other_licenses = "No"
doi = "" # Potentially give a DOI for citing it

[Infrastructure]
os = ["Linux", "Mac", "Windows"]
versions = ["release", "development"]

[dependencies]
ThisStdLib = "ItsUUID"
```
For the license standard a few good resources:
  - [SPDX](https://spdx.org/licenses/)
    - Comprehensive list of licenses and ID for each version and common exceptions
    - Machine-readable guidelines
    - Widely accepted and used (e.g., Github)
  - [Choosealicense](https://github.com/github/choosealicense.com/)
    - Three layers model: (1) Legal Code, (2) Human-readable, (3) Machine-readable
    - Licenses are classified by three dimensions: (1) Permissions, (2) Conditions, (3) Limitations

Some package managers that have implemented these features include:
  - [CRAN](https://cran.r-project.org/web/packages/available_packages_by_name.html)
  - [Pypi](https://pypi.org/)
  - [Cargo](https://crates.io/crates/)
  - [rubygems](https://rubygems.org/gems/)
  - [CTAN](https://ctan.org/pkg/)
  - [Cabal](https://hackage.haskell.org/packages/browse)
  - [Nuget](https://www.nuget.org/packages)

It would be nice to have a robust machine-readable metadata to support features such as:
  - Discoverability based on package status, license types, etc.
  - Make it easy to catalog for a centralized review system
  - Customize C.I. support based on supported OS/versions
  - Easier to cite and review packages for security and quality assurance

Some program languages specify these features systematically:
  - CSS (e.g., [Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/package.json))
  - JS (e.g., [EmberJS](https://github.com/emberjs/ember.js))
  - Python (e.g., [Pandas](https://github.com/pandas-dev/pandas/blob/master/setup.py))
  - Ruby (e.g. [Bundler](https://github.com/bundler/bundler/blob/master/bundler.gemspec))

**Comment by Datseris** [comment]
ref https://github.com/JuliaLang/Pkg.jl/issues/212

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/1070

**Comment by StefanKarpinski** [comment]
Should have remembered that this existed. Thanks for the background research, @Nosferican!
