### ISSUE TITLE
Instantiating Julia 0.7.0 packages from the shell (not from REPL)

### ISSUE THREAD

**Issue by tjlittle** [JuliaLang/julia#27564]
I'm looking to perform the equivalent of `npm install` using the Julia package managing system. (By the way, kudos to the the team for the big improvements in package management with version 0.7).

I have seen the instructions on how to do so from the REPL, but I'm trying to create a script that can run unattended as part of a reproducible devOps process. Is there a CLI?

**Comment by auxetic** [comment]
`julia -e "using Pkg; pkg\"instantiate\" "`

**Comment by KristofferC** [comment]
That works, but we want people to use the `Pkg.` functions to be the way you interact with the package manager from scripts. The problem right now is that those functions are not documented yet. But they will be...

**Comment by tjlittle** [comment]
Thanks! That does the trick.

**Comment by KristofferC** [comment]
Note that there is `Pkg.instantiate()` as well.
