### ISSUE TITLE
size(::Broadcasted) throws UndefVarError

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#27575]
```julia
julia> b = Broadcast.broadcasted(exp, randn(5));

julia> size(b)
ERROR: UndefVarError: bc not defined
Stacktrace:
 [1] _size(::Tuple{Base.OneTo{Int64}}) at ./broadcast.jl:246
 [2] size(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(exp),Tuple{Array{Float64,1}}}) at ./broadcast.jl:245
 [3] top-level scope at none:0
```

Probably line 246 in broadcast.jl should be
```julia
_size(ax::Tuple{Vararg{Base.OneTo}}) = map(length, ax)
```

**Comment by mbauman** [comment]
Nice catch, but I'm not sure size should be defined in the first place. `Broadcasted`s aren't arrays and they can have offset axes, making that definition wrong.  Use `axes` instead.

**Comment by dlfivefifty** [comment]
I don't see how offset `axes` affects the notion of size: isn't the size of an `OffsetArray` still the same as `map(length, axes(A))`?

It doesn't affect me much though: this is for my own type `BroadcastArray` 

https://github.com/JuliaApproximation/InfiniteArrays.jl/blob/master/src/lazybroadcasting.jl

which is meant to be the same as `Broadcasted` but a subtype of array. I'm piggy-backing off all the array-like features of `Broadcasted` that are now implemented, e.g., `getindex`:
```julia
julia> b = Broadcast.broadcasted(exp, randn(10,10));

julia> b[1,3]
1.8024776863891105
```
But anything that's not defined (like `size`) I can just define myself for `BroadcastArray`.

**Comment by mbauman** [comment]
`size` is currently meant to be an error for objects with offset axes.  We've talked about re-enabling it at some point, but for now it'd be good to match the status quo.

**Comment by dlfivefifty** [comment]
I assume disabling is to catch bugs related to using ` 1:size(A,1) `  instead of ` axis(A,1) `? I see the logic then (I’m certainly guilty of this.)
