### ISSUE TITLE
`addprocs_ssh` doesn't return control after entering password

### ISSUE THREAD

**Issue by zachallaun** [JuliaLang/julia#2757]
While experimenting with multiprocessing, I ran into some trouble adding processes on non-local hosts using `addprocs_ssh`. The issue seems to persist on OSX 10.7 and 10.8.

Basically, running `addprocs_ssh({"user@host"})` successfully starts a Julia worker, but fails to return control to the REPL.

```jl
julia> addprocs_ssh({"user@host"})
Password:
# starts the Julia worker at host
# hangs...
```

I'm having trouble figuring out where in the code it's hanging, but if someone's willing to point me in the right direction, I'm willing to spend some time tinkering.

**Comment by ihnorton** [comment]
There have been a number of improvements to SSH addprocs support. Please comment if this is still an issue and it will be re-opened.
