### ISSUE TITLE
Avoid stripping versioning in libopenblas

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#27610]
It causes some issues when using Binarybuilder with OpenBLASBuilder to prepare libraries. See https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/issues/3.

cc @staticfloat

**Comment by staticfloat** [comment]
I guess the fundamental question here is; why do we rename `libopenblas64_p-r0.2.20.so` to `libopenblas64_.so`?  That seems like not a good idea to me.
