### ISSUE TITLE
Documented function string(5, base = 13, pad = 4) returns error

### ISSUE THREAD

**Issue by michaelgoldendev** [JuliaLang/julia#27623]
The following documented function call in the [latest docs](https://docs.julialang.org/en/latest/base/strings/):
> string(5, base = 13, pad = 4)

Returns an error:
> string(5, base = 13, pad = 4)
> ERROR: function string does not accept keyword arguments
> Stacktrace:
>  [1] kwfunc(::Any) at ./boot.jl:237

Instead of:
> "0005"

I'm using the following version of julia on linux:
> julia> VERSION
> v"0.6.3"

**Comment by KristofferC** [comment]
Latest docs is for latest julia. Release 0.6.3 docs is for 0.6.3 julia.

**Comment by michaelgoldendev** [comment]
Thank you!
