### ISSUE TITLE
Julia 0.6.3 - Building system image does not finish

### ISSUE THREAD

**Issue by bdahon** [JuliaLang/julia#27631]
Hi,

I'm trying to build a system image with some packages embedded into the image. To do so, I'm using Docker. Here are the steps to reproduce:

`docker run -ti julia:0.6.3-stretch bash`

Once in the container I'm creating a userimg.jl (in /root) file whose content is

`Base.require(:JSON)`

I'm also running a `Pkg.add("JSON") `from the Julia REPL.

Finally, I'm launching the build_sysimg.jl utility:

`julia /usr/local/julia/share/julia/build_sysimg.jl /root/sys native /root/userimg.jl --force`

The build hangs for hours and never finishes. The last log line is

`/usr/local/julia/share/julia/base/precompile.jl`

I don't know whether I'm doing anything wrong, or if this is a bug.

**Comment by staticfloat** [comment]
Sounds like a bug.  Are you building it locally, or on some kind of buildservice?

**Comment by bdahon** [comment]
I'm building it locally through Docker. Maybe this is an important point, I'm using windows.

**Comment by staticfloat** [comment]
Hmmm, when I run it locally (on a Linux machine), it all works for me:

```
$ docker run -ti julia:0.6.3-stretch bash
Unable to find image 'julia:0.6.3-stretch' locally
0.6.3-stretch: Pulling from library/julia
Digest: sha256:874a871e3bfe6850c648d7e745646c60bdcbdd2469639bda984f58fc24de0ce5
Status: Downloaded newer image for julia:0.6.3-stretch
root@3a58389f2f33:/# vi /root/userimg.jl
bash: vi: command not found
root@3a58389f2f33:/# echo "Base.require(:JSON)" >> /root/userimg.jl
root@3a58389f2f33:/# julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.3 (2018-05-28 20:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.add("JSON")
INFO: Initializing package repository /root/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of JSON from https://github.com/JuliaIO/JSON.jl.git
INFO: Cloning cache of Nullables from https://github.com/JuliaArchive/Nullables.jl.git
INFO: Installing Compat v0.68.0
INFO: Installing JSON v0.17.2
INFO: Installing Nullables v0.0.5
INFO: Package database updated

julia>

# julia /usr/local/julia/share/julia/build_sysimg.jl /root/sys native /root/userimg.jl --force
WARNING: No supported compiler found; startup times will be longer.
INFO: Building inference.o
INFO: /usr/local/julia/bin/julia -C native --output-ji /root/inference.ji --output-o /root/inference.o coreimg.jl
essentials.jl
ctypes.jl
generator.jl
...
docs/basedocs.jl
markdown/Markdown.jl
docs/Docs.jl
/usr/local/julia/share/julia/base/precompile.jl
INFO: System image successfully built at /root/sys.ji.
INFO: To run Julia with this image loaded, run: `julia -J /root/sys.ji`.
```

**Comment by bdahon** [comment]
Ok, let me try to run that on a linux box. Quick question, I'm running julia in the cloud at scale, and I'd like to avoid to download / install packages every time I spawn a new VM. 
Could you confirm that building a sys image with embedded packages should work ?

Thanks

**Comment by staticfloat** [comment]
I'm assuming by "VM" you are referring to a Docker container.

You don't need to use precompilation to avoid downloading and installing packages.  When you first `Pkg.add("Foo")`, Julia will download and install a package, and it will be stored within the `~/.julia` folder (although you can override this location with the `JULIA_PKGDIR` environment variable).  If you do that in your `Dockerfile`, (e.g. `RUN julia -e "Pkg.add(\"Foo\")"`) the package will be saved within the docker image, and ready to be used without downloading or installing anything else at runtime.  What you will waste, however, is the initial compilation work that must be done to load in and parse your package.  Many (but not all) packages support precompilation, and you can force that compilation to occur by simply running `using Foo` within your `Dockerfile` (e.g. `RUN julia -e "using Foo"`), or for even greater time savings, you can precompile a new julia sysimg, which is what `build_sysimg.jl` does.  That gives you the greatest time savings, as it doesn't keep the precompiled package code separate from the rest of the precompiled julia code.

**Comment by bdahon** [comment]
By VM I actually meant real virtual machines. I'm running Julia at scale using Google Dataflow (Apache Beam). You could almost see it as a serverless approach. What Google dataflow is doing is basically spawning VMs where my code is being run automatically. 

I don't have much access to the VM and it's short lived (the time for my pipeline to be run). So the caching doesn't work in my case, as everytime I run my code I get a brand new VM. That's why I wanted to get a system image I could download with packages embedded.

I hope that makes enough sense to you ;)

**Comment by staticfloat** [comment]
Ah; I see what you're saying; you want to build a "julia distribution" that has packages baked in so that you don't have to download/install them.  Unfortunately, I don't think that will work, in general.  While the packages will be precompiled and quick to load, I believe they still need to be loadable (e.g. the source needs to exist and be installed on the filesystem).  I could be wrong about that part, however many packages will have auxilliary data (external binaries, configuration files, data files, etc...) that will need to exist.  And so you'll need to have those packages installed.

I think the simplest thing for you to do would be to bake everything into a docker image such that everything is installed already, and the only step you need to perform is `docker run bdahon/julia_app` or something similar.  Hopefully Google's internet pipe is fat enough that downloading/unpacking that docker image is only a few seconds of work.  You will still want to precompile your packages in that case (via the `RUN julia -e 'using Foo'` method I described above) to minimize unnecessary re-compilation.

How's that sound to you?

**Comment by bdahon** [comment]
Unfortunately, I do not have access to the running docker instance. The way Google Dataflow works is that you submit your code (in my case some python that calls models in Julia), which is bundled and deployed in a prepackaged Docker image. At this stage of their product, we cannot interact with the Docker image. Hence, I cannot alter the Dockerfile.

That's why I was looking into the sys image, because I thought all my required packages would be in the image, and I could just download that image as part of my pipeline. 

If I understood correctly, it seems that building a sys image would not help me in this task. Am I correct ?

**Comment by staticfloat** [comment]
> If I understood correctly, it seems that building a sys image would not help me in this task. Am I correct?

Yes, I think that is correct.

**Comment by bdahon** [comment]
@staticfloat Thanks for your help.
