### ISSUE TITLE
Memory allocation during broadcast to sparse matrix

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaLang/julia#27653]
A very sparse matrix with 1000 rows and 100000 columns with only 10 entries is multiplied by a dense vector column-wise:

```
sparse(rand(1:1000, 10), rand(1:100000, 10), rand(10), 1000, 100000) .* rand(1000, 1)
```

This throws (maybe you have to increase the column numbers from `100000` to something higher, but you will get there):

> OutOfMemoryError()
Stacktrace:
[1] _allocres at .\sparse\higherorderfns.jl:168 [inlined]
[2] _diffshape_broadcast(::Base.#, ::SparseMatrixCSC{Float64,Int64}, ::SparseMatrixCSC{Float64,Int64}) at .\sparse\higherorderfns.jl:132
[3] broadcast(::Base.#, ::SparseMatrixCSC{Float64,Int64}, ::SparseMatrixCSC{Float64,Int64}) at .\sparse\higherorderfns.jl:121

This memory error is thrown despite the fact the resulting matrix has only 10 entries. Maybe the broadcasting could be improved to reflect this.
[Here](https://discourse.julialang.org/t/very-sparse-matrix-but-still-out-of-memory/11766) is the thread on Discourse and here the version info, but @tkoolen saw the same behavior on the nightly build:

> Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

**Comment by Sacha0** [comment]
A few related threads exist, essentially covering this issue, e.g #26561, #21747, and others. Best!

**Comment by MaximilianJHuber** [comment]
Thank you @Sacha0, my issue is essentially a duplicate of those!
