### ISSUE TITLE
Improve documentation of sort

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#27661]
Following issue https://github.com/JuliaLang/julia/issues/26741 I have another problem with `sort` when using `order` argument. Consider the following inconsistency as an example (similar thing is present with `lt`):

```
julia> sort([1,-1,2], by=identity, order=Base.By(abs))
3-element Array{Int64,1}:
  1
 -1
  2

julia> sort([1,-1,2], by=x->-x, order=Base.By(abs))
3-element Array{Int64,1}:
  2
  1
 -1
```

In the first case, following the implementation in ordering.jl, Julia ignores `by` argument in the first case, because it is equal to the default and in the second case it respects it.

In general `order` argument is not documented well and it defaults to a non-exported value.
I am not sure, given we are in 0.7.0-alpha stage if this should be:
* fixed (e.g. by not exposing `order` argument in public API)
or
* only documented precisely describing the way it works (or at least saying to either use `lt`, `by` and `rev` or `order` keyword argument)?

**Comment by haampie** [comment]
See also https://github.com/JuliaLang/julia/pull/22388#issuecomment-362380962

**Comment by haampie** [comment]
Crazy idea: for the whole zoo of sort-related functions deprecate the signature

```julia
sort(x, by = b, lt = l, rev = r)
```  
to positional argument
```julia
sort(x, ord(by = b, lt = l, rev = r))
```
Deprecate
```julia
sort(x, order = o)
```
to
```julia
sort(x, o)
```

This avoids (1) the type instability within the `sort` function -- only `ord` is type unstable now, and (2) it avoids the incompatibility between the kwargs. Then advocate the use of `Order` instances in most cases. Export some sensible defaults:

```julia
sort(x, rev = true)
```
becomes

```julia
# Backward = Rev(Forward), Forward = Lt(isless)
sort(x, Backward)
```

And make `Order` objects fully compositional. The following type-unstable call
```julia
sort(x, lt = my_op, rev = true, by = abs)
```
can be written in a stable way as
```julia
sort(x, Rev(By(abs, Lt(my_op))))
```

**Comment by bkamins** [comment]
Given the number of open issues for `sort` API its consistency should be improved in my opinion. The question to core-devs is if it would be allowed at this stage.

**Comment by StefanKarpinski** [comment]
Good thoughts but not gonna happen in 0.7/1.0; we're trying to get 0.7-beta out quite soon.

**Comment by LilithHafner** [comment]
The observed inconsistency in the OP is due to the fact that the `by` is applied in addition to, not instead of, the `order` keyword. That is, `sort(v, by=f, order=By(g, Forward))` is equivalent to `sort(v, by=g∘f)`.

**Comment by bkamins** [comment]
My key point was, as noted in the title, that I do not find a clear documentation how different arguments interact (but maybe I missed something in the manual).

**Comment by LilithHafner** [comment]
My comment was to help whomever documents this behavior not to invalidate the issue
