### ISSUE TITLE
ismissing(x) much slower than x === missing

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#27681]
Since #27651 a loop involving `x === missing` can be very fast, but using the more generic `ismissing(x)` leads to much less efficient code being generated. Apparently, the compiler isn't able to detect that `!ismissing(x)` implies that `x::Int`.

```julia
function mysum(X)
   s = zero(eltype(X))
   @inbounds @simd for x in X
       if x !== missing
           s += x
       end
   end
   s
end

function mysum2(X)
   s = zero(eltype(X))
   @inbounds @simd for x in X
       if !ismissing(x)
           s += x
       end
   end
   s
end


X1 = rand(Int, 10_000_000);
X2 = Vector{Union{Missing,Int}}(X1);
X3 = ifelse.(rand(length(X2)) .< 0.9, X2, missing);

julia> @btime mysum(X1);
  5.631 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);

  5.785 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  5.670 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X1);
  5.676 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X2);
  16.377 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X3);
  20.681 ms (1 allocation: 16 bytes)
```

**Comment by StefanKarpinski** [comment]
What if you change the definition to `ismissing(x::Any) = x === missing`?

**Comment by StefanKarpinski** [comment]
What's the inference issue?

**Comment by JeffBezanson** [comment]
#26417

**Comment by nalimilan** [comment]
> What if you change the definition to ismissing(x::Any) = x === missing?

One of the points of having `ismissing` is that it could be overloaded in the future by a `TypedMissing` type which would behave like `Missing`, but also carry an additional information about the reason why it's missing which could be used explicitly, e.g. when recoding/imputing (see e.g. https://www.hl7.org/fhir/v3/NullFlavor/cs.html).

Though I guess having this definition as a fallback would be OK if that's more efficient. I'll let @vtjnash decide whether it's a good idea.

**Comment by Keno** [comment]
> What's the inference issue?

`===` is special in inference and inference happens before inlining, so even if they're the same after inlining, Inference doesn't know that.

**Comment by nalimilan** [comment]
Timings regressed between 1.5.0 and master:
- 1.5.0:
```julia
julia> @btime mysum(X1);
  5.581 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);
  6.224 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  6.294 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X1);
  5.558 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X2);
  22.348 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X3);
  22.258 ms (1 allocation: 16 bytes)
```

- master:
```julia

julia> @btime mysum(X1);
  5.941 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);
  6.261 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  6.232 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X1);
  5.982 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X2);
  37.539 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X3);
  45.600 ms (1 allocation: 16 bytes)
```

**Comment by nalimilan** [comment]
Thanks to @aviatesk's work at https://github.com/JuliaLang/julia/pull/38905, this is now fixed!

For reference, here are the results of the benchmarks above on master:
```julia
julia> @btime mysum(X1);
  6.282 ms (1 allocation: 16 bytes)

julia> @btime mysum(X2);
  6.370 ms (1 allocation: 16 bytes)

julia> @btime mysum(X3);
  6.343 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X1);
  5.957 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X2);
  6.757 ms (1 allocation: 16 bytes)

julia> @btime mysum2(X3);
  6.703 ms (1 allocation: 16 bytes)
```

Though cases that were already fast are about 10% slower than on 1.5, but nothing dramatic.
