### ISSUE TITLE
eigvals(::Number) returns a vector

### ISSUE THREAD

**Issue by perrutquist** [JuliaLang/julia#27687]
(From [this discourse thread](https://discourse.julialang.org/t/why-does-eigvals-number-return-a-vector/11731).)

The function `eigvals` returns a vector of length 1 when given a scalar input.
For example:  `typeof(eigvals(1.0)) == Array{Float64,1}`. 

This is inconsistent with `svdvals` which returns a scalar. For example: `typeof(svdvals(1.0)) == Float64`. 

Since Julia currently allows array-like indexing into scalars, code like `eigvals(x)[1]` or `for λ in eigvals(x)` would continue to work for a scalar return value, and this would save the overhead of allocating an array. (Maybe `eigvals` was overlooked when `svdvals` was updated?)

**Comment by GunnarFarneback** [comment]
As noted on discourse, `eigvals` for a scalar was changed to return a vector in https://github.com/JuliaLang/julia/commit/6fb7fbde1225f74e0a5e3832b29b40e4b7101899,
where at the same time `svdvals` for a scalar was introduced and also returned a vector.

A little more archaeology reveals that `svdvals` was changed to return a scalar in
https://github.com/JuliaLang/julia/commit/ff1b30bf5f0956a6ec1b809a8904080719423f4f.

Regardless of history, which does look a little random, I see no reason for these methods to turn a scalar into a vector.

**Comment by andreasnoack** [comment]
Fixed by #27730
