### ISSUE TITLE
Code Generation Docs example yields LoadError

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaLang/julia#27692]
I am using Julia 0.6.3 on Windows 7, Intel Processor.

When I run the first block of example code in the Metaprogramming - Code Generation section:

```
for op = (:+, :*, :&, :|, :$)
    eval(quote
        ($op)(a,b,c) = ($op)(($op)(a,b),c)
    end)
end
```
I get:

```
ERROR: LoadError: error in method definition: function Base.* must be explicitly imported to be extended
while loading C:\Projects\11_Louis\AleAleVisco\latest\RHEOS.jl\examples\test.jl, in expression starting on line 1
```

I'm just trying to learn about metaprogramming so I don't understand exactly why this bug is occuring or the most sensible way to fix it unfortunately, otherwise I would put in a PR.

**Comment by StefanKarpinski** [comment]
Thanks for the very thorough doc-bug report! This example should definitely be updated.

**Comment by moustachio-belvedere** [comment]
Thanks (both) for the work on such a great language, enjoying it immensely!

I did figure out the cause in the end after re-reading the modules section of the docs but I guess the update was still necessary!
