### ISSUE TITLE
Bug: write(s, 5, MyType) causes error while write(s, 5); write(s, MyType) does not (pointer.jl/operators.jl)

### ISSUE THREAD

**Issue by Helveg** [JuliaLang/julia#27717]
My entire project is a bit big but I don't think the context matters alot because the bug boils down to this:

I've overloaded Base.write to match write(s::IO, v::MyType) where MyType is an Array{Tuple{UInt32,OtherMyType}} and the OtherMyType is a type with lots of fields that also has its own version of write(s::IO, v::OtherMyType). 

The error does not occur if I write to the stream like this:
`write(s, 3456)`
`write(s, MyTypeObj)`
but it does occur when I call the shortened form:
`write(s, 3456, MyTypeObj)`

Error message:
`ERROR: MethodError: no method matching +(::Int64, ::Void)`
`Closest candidates are:`
`  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:424`
`  +(::T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, ::T<:Unio`
`n{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) where T<:Union{Int128,`
` Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:32`
`  +(::Integer, ::Ptr) at pointer.jl:128`
  `...`

versioninfo() output:
`Julia Version 0.6.2`
`Commit d386e40c17* (2017-12-13 18:08 UTC)`
`Platform Info:`
`  OS: Windows (x86_64-w64-mingw32)`
`  CPU: Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz`
`  WORD_SIZE: 64`
`  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)`
`  LAPACK: libopenblas64_`
`  LIBM: libopenlibm`
`  LLVM: libLLVM-3.9.1 (ORCJIT, nehalem)`

**Comment by fredrikekre** [comment]
From the error message it looks like your own `write` definition does not return the number of bytes written, it returns `nothing`.

**Comment by StefanKarpinski** [comment]
The generic contract expected from `write` methods is that they return the number of bytes written as an `Int`. If you do that then this will work and the multi-arg version will return the total bytes written.

**Comment by Helveg** [comment]
Yup, that solved it. I was finally convinced I might have actually contributed a bug :)
