### ISSUE TITLE
Memory usage of printing DArrays

### ISSUE THREAD

**Issue by cpcloud** [JuliaLang/julia#2771]
I was playing around with `@parallel` doing the comprehension example from the recently posted videos on the Julia blog and I noticed something strange. I happened to have `htop` running at the time and I noticed that when I evaluated the `DArray` at the command line (just printing itself), the amount of memory used on my machine would increase by about the number of bytes that the array takes up in memory. Just as a sanity check I tried the same thing with a regular old `Array` and it works fine. 

I then `grep`ed the code for "\u22ee" (the vertical dots unicode symbol) to try to find where the issue might lie in `show.jl`. 

The `show_vector` method of `AbstractArray`s calls the `DArray` `reshape` method which may be making a copy of the chunks making up the darray in `darray2.jl` on line 188. I have no idea how to go about fixing this.

**Comment by malmaud** [comment]
Should this issue be closed and moved to https://github.com/JuliaParallel/DistributedArrays.jl, or is it something that needs to be fixed in Base?

**Comment by ViralBShah** [comment]
Yes, this should be moved there - and have a specific issue opened here if there is a dependency on fixing something in Base.

**Comment by malmaud** [comment]
OK, moved.

**Comment by jakebolewski** [comment]
This uses so much memory because of the way we do array printing in Base.  The way we print matrices could be much more efficient.

**Comment by jakebolewski** [comment]
It would be useful to see if #13598 helps this situation or not.

**Comment by amitmurthy** [comment]
DArrays are out of Base now.
