### ISSUE TITLE
enumerate() direct in-place operation

### ISSUE THREAD

**Issue by kawild** [JuliaLang/julia#27728]
Hi,

while iterating over the value from enumerate() it seems that in-place operations to the value are not possible. I was a little surprised and don´t know if it is intended.

```
z = zeros(5)

for (i, x) in enumerate(z)
  x += 1
end

show(z)
```

-----------------------------------------------------
Julia Version 0.6.3
Commit d55cadc350* (2018-05-28 20:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

**Comment by KristofferC** [comment]
Please ask questions on https://discourse.julialang.org.
