### ISSUE TITLE
Rename `srand` to `Random.seed`

### ISSUE THREAD

**Issue by ChristianKurz** [JuliaLang/julia#27726]
I frequently need to look this up and it seems to be against the naming convention of spelling things out. 
Other scientific languages do not use that syntax either:
* R had `srand` but its deprecated, now uses `set.seed()`
* MATLAB uses `rng(seed)`
* Python uses `random.seed()`

While C actually uses `srand`, i think we want to improve upon C-Syntax?

Edit: There has been some short [discussion about this in 2014](https://github.com/JuliaLang/julia/issues/9105#issuecomment-64155541)

**Comment by rfourquet** [comment]
I would also propose `reseed!`

**Comment by ViralBShah** [comment]
I prefer something with rand in it. So `seedrand`.

**Comment by StefanKarpinski** [comment]
Yes, `seedrand` seems like a pretty good name.

**Comment by fredrikekre** [comment]
Unexported `Random.seed`?

**Comment by rfourquet** [comment]
> Since we do have randjump, why not go with randseed instead?

I like the increased consistency (but see also `bitrand`), although it may sound to some like `randseed` would return a random seed, in the same way we have `randperm` and `randstring` producing random permutations and strings.

**Comment by ViralBShah** [comment]
That is a good point.

**Comment by ChristianKurz** [comment]
So the choice is between `seedrand` and unexported `Random.seed`.
 I like both, but I think `Random.seed` may be the better option:
* it's reasonably short
* seeding an RNG may not be considered beginners usage, so discoverability should not be a problem.
* i like how `Random` stands out in the code for readability

**Comment by StefanKarpinski** [comment]
`Random.seed` can happen if someone makes a PR in the next day, but this is not a release blocker.
