### ISSUE TITLE
take! on IOBuffer is not optimized for the common usecase where the buffer is not used again

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#27741]
See discussion in https://github.com/JuliaLang/julia/pull/27691#discussion_r197556137.

**Comment by JeffBezanson** [comment]
Yes. `take!` currently tries to reset the IOBuffer to a state where it can still be used, but that requires allocating a new buffer, which sort of defeats the purpose. If you want the data without destroying the buffer, just call `read!`. `take!` should just resize the vector, mark the iOBuffer as closed and unusable, and return the vector to you.

**Comment by StefanKarpinski** [comment]
That would make sense to me: I think as long as the IOBuffer object is not reusable that should work well. Reusing closed IOBuffers seems like a questionable and rare thing to do.

**Comment by stevengj** [comment]
Is there a non-breaking way to improve this in the meantime?   There are dozens of usages of `take!` in Base and stdlib that could be improved if we provided a better function for this.
