### ISSUE TITLE
Channel should disallow `isempty`

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#27754]
It's a mutable iterator without lookahead. We cannot support `isempty` on this iterator. We should disallow it instead (and perhaps point the user to `isready`). At the moment, calling isempty consumes an element of the Channel, which is problematic.

**Comment by haampie** [comment]
Related: https://github.com/JuliaLang/julia/issues/27412

**Comment by laborg** [comment]
Now that `isempty` isn't mutating the channel anymore (https://github.com/JuliaLang/julia/pull/36641) this issue can closed, right?
