### ISSUE TITLE
Stop bundling debug versions of libraries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#27753]
On 0.7-alpha, out of the 600M, 250M are just the debug libs. I am pretty sure that 99% of the users do not use the debug libs in any way. Would be nice to slim down our download.

**Comment by ararslan** [comment]
Duplicate of #27264?

**Comment by JeffBezanson** [comment]
Agreed. People really are bothered by the size of the download sometimes, and it makes the system seem bloated.

**Comment by ViralBShah** [comment]
Closed the older issue. Let's discuss here. I will try prepare a PR.

**Comment by ararslan** [comment]
Only tangentially related, but for what it's worth the debug build uses a _huge_ amount of memory, so much so that I was unable to make a FreeBSD release for 0.7-alpha on my own computer because the debug part got OOM killed.

**Comment by ViralBShah** [comment]
We probably won't stop building the debug versions of the libraries since we want that to get CI tested. But we can remove it from the binary-dist step.

After fixing the sys.ji stuff, with debug versions, the download is 126M and without those, it is 82M.

By comparison 0.6 binaries were 65M with debug libs.

**Comment by ViralBShah** [comment]
I was thinking about doing that too. However, it is still going to be a significant difference.

**Comment by ViralBShah** [comment]
The better compression takes us from 82M to 52M (after deleting the debug files).

**Comment by nalimilan** [comment]
It's now quite common to use .tar.xz files, which should save a few more MBs.
