### ISSUE TITLE
sys.ji is included in the 0.7-beta binaries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#27779]
`sys.ji` is included in the 0.7-beta binaries, increasing the amount of disk space the `beta` uses by 145M over the `alpha`.

**Comment by ararslan** [comment]
Weird, I'm not sure what changed to make that get packaged along with the necessary stuff, but I can confirm it's there on Linux and macOS at least.

**Comment by vtjnash** [comment]
I suspect we are packaging `lib/julia/sys*`, and that it's getting picked up somewhat accidentally

**Comment by ViralBShah** [comment]
Isn't it happening here: https://github.com/JuliaLang/julia/blob/af35743e21678da18d844ab69a59cef40bca1912/Makefile#L196

**Comment by vtjnash** [comment]
No, it happens because of https://github.com/JuliaLang/julia/commit/89bce0de1e5f5e26ce17d1e3c8c589af20f51e3a
