### ISSUE TITLE
Wording of depreciation warning with ones()

### ISSUE THREAD

**Issue by ckoe-bccms** [JuliaLang/julia#27795]
Hello everybody,

I would like to file an enhancement request concerning the wording of a depreciation warning I observed with the current 0.7-beta.

Reduced minimal working example:
```
julia> m=2.0
2.0

julia> ones(m)
┌ Warning: `ones(dims...)` is deprecated, use `ones(convert(Dims, dims)...)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
2-element Array{Float64,1}:
 1.0
 1.0
```
In the actual code which triggered this the problem (which went undetected in previous julia versions) was that a Float64 scalar was passed as an argument to ones. However, from the wording of the warning, especially the "convert(Dims, dims)" I was looking for an actual array (multi-dimensional object)  or similar passed as an argument to ones() not realizing that the concrete type of the scalar was the problem. Would it be possible to change or amend the warning in a way which makes that clear in case the argument is an scalar of the wrong type ?

I realize this is probably not very useful that late in the 0.7 release cycle, but it was suggested to me on discourse to file an issue anyway.

Thank you very much in advance !

Best regards

Christof

**Comment by KristofferC** [comment]
Deprecation is removed.
