### ISSUE TITLE
Sockets: example echo server ok in 0.7 but does not echo in 0.6

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#27799]
I posed a question on this issue in discourse but no responses. Issue is that the example socket echo client/server from docs runs without error in 0.6.3 released binary but the echo does not come back to the client. In 0.7 alpha and master the example code for it works fine, echo comes back.
My understanding is that socket functionality went to its own package in 0.7 where its package is testable. I would just keep using 0.7 but of course a lot of functionality does not work there yet, so I am interested in getting more info on why 0.6.3 does not echo back. Any suggestions for casting light on this otherwise silent error?

**Comment by laborg** [comment]
0.6 isn't supported anymore and the example works in 1.6, 1.7 and on master.
