### ISSUE TITLE
Documented return type incorrect for redirect_stdout and redirect_stderr on 0.6.2

### ISSUE THREAD

**Issue by galenlynch** [JuliaLang/julia#27805]
The documentation for [redirect_stdout](https://docs.julialang.org/en/v0.6.2/stdlib/io-network/#Base.redirect_stdout) as well as [redirect_stderr](https://docs.julialang.org/en/v0.6.2/stdlib/io-network/#Base.redirect_stderr) says that these functions return a (rd, wr) tuple of the pipe ends. While this is true if no arguments are used, if an `IOStream` argument is used for either function, then the return type is not a tuple but is instead a single `IOStream`.

Without optional argument:
```julia
julia> typeof(redirect_stdout())
Tuple{Base.PipeEndpoint,Base.PipeEndpoint}
```

With optional argument:
```julia
julia> typeof(redirect_stdout(open("test.txt", "w+")))
IOStream
```

I've seen this behavior on 0.6.2 but have not tested other versions:
```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by JeffBezanson** [comment]
Fixed by #28064.
