### ISSUE TITLE
cholesky(::Diagonal)

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#27821]
```julia
julia> VERSION
v"0.7.0-beta.44"

julia> using LinearAlgebra

julia> cholesky(Diagonal(ones(3)))
ERROR: MethodError: no method matching cholesky(::Diagonal{Float64,Array{Float64,1}})
```

I would be happy to make a PR, but I wonder if the omission is intentional. In any case, it would be great if one did not have to special-case `Diagonal`.

**Comment by andreasnoack** [comment]
Please go ahead and prepare a PR. I agree that it would be good to have.

**Comment by simonbyrne** [comment]
`SymTridiagonal` would be great as well.

**Comment by tpapp** [comment]
@simonbryne: I agree, but I only have time for Cholesky ATM; also, I find the cholesky code in Julia somewhat complex so I will wait for the current PR to be merged to make sure I am doing these things right, then I will tackle the `SymTridiagonal`.
