### ISSUE TITLE
current_module vs `@__MODULE__

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#27835]
When using `@__MODULE__` inside a function, it returns the module that defines that function, while the deprecated `current_module()` returns the module calling the function. I need the latter behavior, is ccalling `jl_get_current_module` a safe workaround, or is that function scheduled for removal as well?

My use case is CxxWrap, where I would like this interface for wrapping a C++ module:

```julia
module Foo
using CxxWrap

wrap_module("libfoo.so")
end
```

The `wrap_module` function looks like this:

```julia
function wrap_module(so_path::AbstractString, m::Module=current_module())
# add stuff to m
end
```

So with the new `@__MODULE__` macro it seems impossible to set a default value on m that is equal to the calling module.

**Comment by vtjnash** [comment]
> returns the module calling the function

Since it's unclear what you mean by this (mostly, it's just expected to return `Main`), this functionality is gone. `@__MODULE__` is now precisely what it used to mean, or you can write your own macro to do the same (c.f. `Meta.@lower` or `@__MODULE__`)

**Comment by JeffBezanson** [comment]
Right; it is not really correct to say that `current_module` gives the module calling the function. One way to do this is to write a macro, and there `__module__` gets bound to the module containing the macro call.

**Comment by tknopp** [comment]
I have been googling around about this issue and finally went here. In Gtk.jl one cannot simply replace `current_module` with `@__MODULE__`. My workaround now is to define:
```
curr_module() = ccall((:jl_get_current_module,:libjulia), Ref{Module}, ())
```
But if I get it right that function is removed in 1.0?

**Comment by barche** [comment]
From what I understand the C function will be removed too, yes. In the case of CxxWrap.jl I replaced the function that called `current_module` with a macro and used `__module__`, not sure if that is an option for Gtk.jl.
