### ISSUE TITLE
Julia v0.7.0-beta and master (but not alpha) build fails on CentOS-7

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#27839]
Building Julia v0.7.0-beta, as well as the current master, on stock CentOS-7 (official Docker container) fails:

```
    CC ui/repl.dbg.obj
    LINK usr/bin/julia-debug
Creating usr/etc/julia/startup.jl
Copying in usr/share/man/man1/julia.1
/opt/julia/contrib/install.sh 755 /opt/julia/contrib/julia-config.jl /opt/julia/usr/share/julia/
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
    JULIA usr/lib/julia/corecompiler.ji

/bin/sh: /opt/julia/usr/bin/julia: No such file or directory
make[1]: *** [/opt/julia/usr/lib/julia/corecompiler.ji] Error 127
make: *** [julia-sysimg] Error 2
```

However, Julia v0.7.0-alpha builds without problems.

I'm using this (fairly minimal) Dockerfile to build:

```
FROM centos:7

# User and workdir settings:

USER root
WORKDIR /root


# Initial steps:

RUN true \
    && sed -i '/tsflags=nodocs/d' /etc/yum.conf \
    && dbus-uuidgen > /etc/machine-id


# Install current CMake:

RUN true \
    && yum install -y wget \
    && wget -O- https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz \
        | tar --strip-components=1 -x -z -f - -C /usr/local/


# Install Julia build dependencies:

RUN true\
    && yum groupinstall -y "Development Tools" \
    && yum install -y wget git which


# Build Julia:

RUN true\
    && cd /opt \
    && git clone "https://github.com/JuliaLang/julia" julia \
    && cd julia \
    && git checkout "v0.7.0-alpha" \
    && time \
        MARCH=x86-64 \
        JULIA_PKG3_PRECOMPILE=enable \
        make -j"$(nproc)" all debug

ENV \
    PATH="/opt/julia/usr/bin:$PATH" \
    MANPATH="/opt/julia/usr/share/man:$MANPATH"
```

**Comment by nalimilan** [comment]
I guess the failure goes away if you don't set `PATH`?

**Comment by oschulz** [comment]
> I guess the failure goes away if you don't set PATH

No, I set PATH after the build, the failure happens during make.

**Comment by nalimilan** [comment]
OK, thanks. Since you use git already, it would be very useful if you could identify the commit (or the range of commits) which created the problem. It's most likely one of the commits which touched `Makefile`, for example 18e6b4d3324ae873304d68212558d525e01d261e.

**Comment by oschulz** [comment]
I'll try to bisect ...

**Comment by oschulz** [comment]
Ok, did a bisect between v0.7.0-alpha and v0.7.0-beta. The commit that breaks the build on CentOS-7 is 18e6b4d  (@vtjnash).

Using this Dockerfile

```
FROM centos:7

# User and workdir settings:

USER root
WORKDIR /root


# Initial steps:

RUN true \
    && sed -i '/tsflags=nodocs/d' /etc/yum.conf \
    && dbus-uuidgen > /etc/machine-id


# Install current CMake:

RUN true \
    && yum install -y wget \
    && wget -O- https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz \
        | tar --strip-components=1 -x -z -f - -C /usr/local/


# Install Julia build dependencies:

RUN true\
    && yum groupinstall -y "Development Tools" \
    && yum install -y wget git which


# Build Julia:

RUN true\
    && cd /opt \
    && git clone "https://github.com/JuliaLang/julia" julia

ARG julia_version=master

RUN true\
    && cd /opt/julia \
    && git checkout "$julia_version" \
    && time \
        MARCH=x86-64 \
        JULIA_PKG3_PRECOMPILE=enable \
        make -j"$(nproc)" all debug

ENV \
    PATH="/opt/julia/usr/bin:$PATH" \
    MANPATH="/opt/julia/usr/share/man:$MANPATH"
````

The following succeeds

    docker build --build-arg julia_version="44f2507" -t julia07 .

While this fails:

    docker build --build-arg julia_version="18e6b4d" -t julia07 .

@vtjnash, could spare a moment to take a look at this (I'm not familiar with the internals of the Julia Makefile)? With the Dockerfile and commands above, the failure should be fully reproducible .

**Comment by ViralBShah** [comment]
Does it work if you build with `make -j1`?

**Comment by vtjnash** [comment]
Yes, I think I have a patch for this locally and need to migrate that to master. Doing `make all debug` is unusual (it creates the same output as `make all`, but is much slower to do it since it uses the debug binaries to do more of the heavy lifting)

**Comment by oschulz** [comment]
> Does it work if you build with make -j1

Nope. :-( Tried that early on.

**Comment by oschulz** [comment]
> Doing make all debug is unusual

Just curious - the official build are also done with debug included, right?

**Comment by oschulz** [comment]
I'm mainly building for production use, should I do `make all` instead of `make all debug`?

**Comment by nalimilan** [comment]
> Just curious - the official builds are also done with debug included, right?

Until now, yes, but that will no longer be the case soon: https://github.com/JuliaLang/julia/pull/27814.

> I'm mainly building for production use, should I do make all instead of make all debug?

Probably, yes.

**Comment by oschulz** [comment]
Thanks for the heads-up, @nalimilan .

**Comment by oschulz** [comment]
Thanks for the quick fix, @vtjnash!
