### ISSUE TITLE
deepcopy is slow

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#27841]
`deepcopy` is very slow on master and allocates an `ObjectIdDict`:

```julia
julia> using BenchmarkTools

julia> f(x) = deepcopy(x)
f (generic function with 1 method)

julia> function g(x::Array{T}) where T
           y = Array{T}(undef, length(x))
           copyto!(y, x)
       end
g (generic function with 2 methods)

julia> x = collect(1:100);

julia> @benchmark f($x)
BenchmarkTools.Trial: 
  memory estimate:  1.30 KiB
  allocs estimate:  3
  --------------
  minimum time:     201.290 ns (0.00% GC)
  median time:      220.049 ns (0.00% GC)
  mean time:        269.109 ns (13.64% GC)
  maximum time:     63.888 μs (99.18% GC)
  --------------
  samples:          10000
  evals/sample:     606

julia> @benchmark g($x)
BenchmarkTools.Trial: 
  memory estimate:  896 bytes
  allocs estimate:  1
  --------------
  minimum time:     106.996 ns (0.00% GC)
  median time:      124.724 ns (0.00% GC)
  mean time:        150.505 ns (13.92% GC)
  maximum time:     41.561 μs (99.36% GC)
  --------------
  samples:          10000
  evals/sample:     935
```

**Comment by yuyichao** [comment]
Yes it is, and it has to be slower than `copy`. If you need `copy` (i.e. `g`) instead of `deepcopy` (i.e. `f`), you should use that instead.

The `ObjectIdDict` is needed to maintain object identity and to handle loops.

**Comment by JeffBezanson** [comment]
Correct; `deepcopy` is generally not recommended. I see it as violating abstraction: it copies *every* object reachable from the one you specify, when in fact some of them might not be appropriate to copy, and what gets copied will change if an object's representation changes.

Yichao is right; to make a new array with the same data as another, use `copy` instead.
