### ISSUE TITLE
Memory corruption

### ISSUE THREAD

**Issue by PtrMan** [JuliaLang/julia#27844]
julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.3 (2018-05-28 20:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Array{Float64}(3,1)
3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

julia> Array{Float64}(3,1)
3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

julia> [5, 5, "a"]
3-element Array{Any,1}:
 5   
 5   
  "a"

julia> Array{Float64}(3,1)
3×1 Array{Float64,2}:
 0.0
 0.0
 0.0

julia> Array{Float64}(3)
3-element Array{Float64,1}:
 0.0
 0.0
 0.0

julia> Array{Float64}(3,1)
3×1 Array{Float64,2}:
 6.90105e-310
 6.90105e-310
 6.90103e-310

(I assumed it to be zero)

**Comment by KristofferC** [comment]
> (I assumed it to be zero)

That was not a correct assumption.

In 0.7 that is written as

```
julia> Array{Float64}(undef, 3,1)
3×1 Array{Float64,2}:
 2.234230083e-314
 0.0
 2.2342621893e-314
```

Please ask further questions on https://discourse.julialang.org/

**Comment by PtrMan** [comment]
Oh I should read the docs - thank you!
