### ISSUE TITLE
LinearAlgebra.eigmin(::Diagonal) MethodError

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#27847]
```julia
julia> VERSION
v"0.7.0-beta.65"

julia> using LinearAlgebra

julia> eigmin(Diagonal([1.0]))
ERROR: WARNING: Base.eigmin is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Base
MethodError: no method matching eigmin(::Diagonal{Float64,Array{Float64,1}})
```

Will make a PR. But why the deprecation warning?

**Comment by KristofferC** [comment]
Because `eigmin` has been moved? 

Or do you mean https://github.com/JuliaLang/julia/issues/26140?

**Comment by tpapp** [comment]
I understand it has been moved, that's why I am `using LinearAlgebra`. But from a clean session, similarly
```julia
julia> using LinearAlgebra

julia> LinearAlgebra.eigmin(Diagonal([1.0]))
ERROR: WARNING: Base.eigmin is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Base
```

To clarify, the primary issue is that the method is missing, I have now learned about #26140 so please disregard that part.

**Comment by tpapp** [comment]
Also, the fix should be pretty simple I think, [this method](https://github.com/JuliaLang/julia/blob/354ea7befdcbc9df4bf369c7144007031aa7f23d/stdlib/LinearAlgebra/src/eigen.jl#L299) should just also accept `Diagonal`, because `eigvals` works fine with `Diagonal`.

**Comment by andreasnoack** [comment]
It should probably be fine to loosen that method to `AbstractMatrix` which I think would make this work. I think the deprecation warning happens when a function has been deprecated to a stdlib package but that package doesn't have a matching method.

**Comment by tpapp** [comment]
@andreasnoack: I did what you suggested in #27863, can you please take a look?
