### ISSUE TITLE
`findnz` does not work for arrays of arbitrary dimension

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#27849]
It is only defined for matrices. But to me it seems reasonable to define `findnz(A)` for any higher-dimensional array. It would return `(I1, I2, ..., Id, V)`, where `d` is the number of dimensions in `A`, `Ii` is the indices of non-zero entries along dimension `i`, and `V` is the value of those non-zero entries.

**Comment by cossio** [comment]
The implementation could be something like

```julia
function findnz2(A::AbstractArray{T, N}) where {T, N}
    nnzA = count(t -> t != 0, A)
    idxs = ntuple(_ -> zeros(Int, nnzA), N)
    V = Vector{T}(nnzA)
    cnt = 0
    for idx in eachindex(A)
        if A[idx] ≠ 0
            cnt += 1
            indexes::NTuple{N, Int} = ind2sub(A, idx)
            for d = 1 : N
                idxs[d][cnt] = indexes[d]
                V[cnt] = A[idx]
            end
        end
    end
    return (idxs..., V)
end
```

**Comment by nalimilan** [comment]
`findnz` has been moved to SparseMatrices since it's mainly designed for this case. Use `findall(iszero, x)` instead for general arrays. On 0.7, it returns cartesian indices.

**Comment by mbauman** [comment]
Note that `findnz` on dense matrices is a strange operation — and one that we had been considering deprecating (#24910 and #25641).  It's really `X <: SparseArray ? findstored(X) : find(!iszero, X)`.

Unfortunately that discussion had gotten closed and forgotten without fully resolving the deprecation.

**Comment by cossio** [comment]
I guess it's better to deprecate it then, before 0.7 is out.
