### ISSUE TITLE
IJulia installation issue

### ISSUE THREAD

**Issue by skiran87** [JuliaLang/julia#27878]
Hi,
I am new to Julia and am trying to add IJulia package and is getting an error. Log file is given below. Any help will be appreciated.

WARNING: `JULIA_HOME` environment variable is renamed to `JULIA_BINDIR`

signal (11): Segmentation fault
in expression starting at /home/.julia/packages/IJulia/oaZM/deps/kspec.jl:6
is_ast_node at /buildworker/worker/package_linux64/build/src/dump.c:445 [inlined]
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:499
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:467 [inlined]
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:640
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:467 [inlined]
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:640
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:618 [inlined]
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:622
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/dump.c:2302 [inlined]
jl_compress_ast at /buildworker/worker/package_linux64/build/src/dump.c:2304
jl_method_set_source at /buildworker/worker/package_linux64/build/src/method.c:528 [inlined]
jl_new_method at /buildworker/worker/package_linux64/build/src/method.c:587 [inlined]
jl_method_def at /buildworker/worker/package_linux64/build/src/method.c:761
eval_methoddef at /buildworker/worker/package_linux64/build/src/interpreter.c:310
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:666
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:798
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff55dc95daf)
unknown function (ip: 0x11)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:807
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:856
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:852
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:894
include at ./boot.jl:314 [inlined]
include_relative at ./loading.jl:1071
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
include at ./client.jl:393
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:416
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:367 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:700
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:624
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:798
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff55e63132f)
unknown function (ip: 0xb5)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:807
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:856
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:852
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:894
include at ./boot.jl:314 [inlined]
include_relative at ./loading.jl:1071
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
include at ./client.jl:393
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1823
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:416
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:559
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:798
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff55d93e9af)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:807
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:856
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:802
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:631
eval at ./boot.jl:316
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
exec_options at ./client.jl:244
_start at ./client.jl:427
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2140
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1540 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:112
main at /buildworker/worker/package_linux64/build/ui/repl.c:243
__libc_start_main at /build/buildd/eglibc-2.19/csu/libc-start.c:287
_start at /home/wares/julia-22590d529d/bin/julia (unknown line)
Allocations: 8549594 (Pool: 8548637; Big: 957); GC: 19

**Comment by ViralBShah** [comment]
Which version of Julia and are these the official binaries?

**Comment by skiran87** [comment]
Julia Version 0.7.0-alpha.0
Commit 22590d529d (2018-05-31 00:07 UTC)

**Comment by skiran87** [comment]
OS: Linux (x86_64-pc-linux-gnu)

**Comment by fredrikekre** [comment]
Please open a new issue at the [IJulia repo](https://github.com/JuliaLang/IJulia.jl) if this still happens with julia 0.7 and IJulia master.
