### ISSUE TITLE
[DOC/NEWS] 0.7 how to bring back the history from 0.6

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#27885]
Since the position and name of the history file has changed (which should be mentioned in the news file) history by default isn't transferred to the new 0.7 installation.
Maybe there should be a guide/hint on how to bring back the old history.

**Comment by brenhinkeller** [comment]
A good idea, though it looks like enough time has elapsed that if it hasn't been done yet we've probably missed our window
