### ISSUE TITLE
T(x::T) type unstable in 0.7

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#27893]
I ran into the following fairly simple type instability in 0.7 which was not present in 0.6. Its this:

### 0.6
```
julia> struct Foo
       end

julia> myidentity(x::T) where {T} = T(x)
myidentity (generic function with 1 method)

julia> @code_warntype myidentity(Foo())
Variables:
  #self# <optimized out>
  x <optimized out>

Body:
  begin 
      return $(QuoteNode(Foo()))
  end::Foo
```

### 0.7.0-beta.105 (commit 656d58782c)

```
julia> struct Foo
       end

julia> myidentity(x::T) where {T} = T(x)
myidentity (generic function with 1 method)

julia> @code_warntype myidentity(Foo())
Body::Any
1 1 ─ %1 = invoke :($(Expr(:static_parameter, 1)))(%%x::Foo)::Any                                 │
  └──      return %1                                                                              │
```

I know some stuff re: constructors / convert was changed that maybe affected this, but I wasn't sure if this is intended or not.

**Comment by JeffBezanson** [comment]
In 1.0 `myidentity(Foo())` will throw a method error, because there's no constructor `Foo(x)`. The only method that matches now is the deprecation, which is deliberately not inferred.

**Comment by marius311** [comment]
Ah I missed it was a deprecated method since I had warnings turned off, this makes sense, thanks!
