### ISSUE TITLE
Error: Non-bolean used in bolean context

### ISSUE THREAD

**Issue by muriloasouza** [JuliaLang/julia#27920]
Hello, i'm getting this error when i try to run a file i just made.

> LoadError: [91mTypeError: non-boolean (Array{Float64,2}) used in boolean context[39m
while loading C:\Users\Muril\AppData\Local\atom\app-1.28.0\Arquivos Feitos\fsdfsdfs.jl, in expression starting on line 40

Here's my code. I'm loading some numeric data from a txt file. 
```
dados = readdlm("C:/Users/Muril/AppData/Local/atom/app-1.28.0/Arquivos Feitos/Dados.txt")

Nt = dados[2,12]; 
maxiter = dados[2,13];
tol = dados[2,14]; 
U0 = dados[2,15]*1e3; 
delta = dados[2,16]; 
# cosphi = dados[2,17]; 
# senphi = sin(acos(cosphi));
de = dados[2:Nt+1,1];
para = dados[2:Nt+1,2]; 
Lcomp = dados[2:Nt+1,3]; 
r = dados[2:Nt+1,4];
x = dados[2:Nt+1,5]; 
R = (r.*Lcomp); 
X = (x.*Lcomp); 
PLlin = (dados[2:Nt+1,7])*1e3; 
QLlin = (dados[2:Nt+1,8])*1e3; 
PLnlin = (dados[2:Nt+1,9])*1e3;
QLnlin = (dados[2:Nt+1,10])*1e3; 
Qshunt = (dados[2:Nt+1,11])*1e3; 
Perc = 105; 
Qmod = dados[2,18]*1e3; 
kj = dados[2,19]; 
fq = dados[2,20]; 
hmax = 25; 
f = 60; 

PLtotal = (PLlin + PLnlin); 
QLtotal = (QLlin + QLnlin - Qshunt); 

maiornivel = 1; 
nivel = zeros(1,Nt); 
nivel[find(de .== 0)] = maiornivel;
i = 0;
while nivel[sum(nivel .== 0)] >= 0
for i = 1:Nt
if nivel[i] == maiornivel
nivel[find(de .== i)] = maiornivel+1;
end
end
maiornivel = maiornivel+1;
if nivel ~= 0
    break
end
end
```

I was trying to convert a Matlab code to Julia. It's something related to the while loop... i think in Julia it only accepts Boolean. Is there anyway i can fix to make it work?

Thanks in advance!

**Comment by JeffBezanson** [comment]
Julia uses `!=` instead of `~=`, and it only gives a single boolean answer. To check whether every element of an array is zero, use `iszero(a)` or `all(iszero, a)`. I'm not sure where this is happening in your specific program.

In the future, please use the discourse forum for help.
