### ISSUE TITLE
ArgumentError("stream is closed or unusable") && Error in testset cmdlineargs

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [JuliaLang/julia#27943]
Running `make test` fails when it reaches cmdlineargs
I have provided a created a [gist](https://gist.github.com/ChukwuemezieChristopherAneke/4f8a4c30edda91dfcade2d83b7939a1d) for the stacktrace.
### julia version
julia version 0.7.0-beta

### OS
x86_64_Linux *fedora latest*
### Environment variables set for intel-mkl
```
$INTEL_COMPILERS_AND_LIBS="/opt/intel/compilers_and_libraries_2018.3.222/linux"
source $INTEL_COMPILERS_AND_LIBS/mkl/bin/mklvars.sh intel64 ilp64
```
### Make.user contents

```
MARCH=native
USE_INTEL_MKL = 1
prefix=/home/user/local
```
### UPDATE
I think this warning that comes before the test fails may provide a clue to the `cmdlineargs` error:

```
Warning: TerminalMenus: Unable to enter raw mode: ArgumentError("stream is closed or unusable")
└ @ REPL.TerminalMenus util.jl:21
      From worker 2:	
┌ Warning: TerminalMenus: Unable to enter raw mode: ArgumentError("stream is closed or unusable")
└ @ REPL.TerminalMenus util.jl:21
```

**Comment by ViralBShah** [comment]
Many of these have been fixed. Please reopen if still an issue.
