### ISSUE TITLE
Make !=== equal to !(===), !== equal to !(==) and deprecate !=.

### ISSUE THREAD

**Issue by favba** [JuliaLang/julia#27947]
This would by highly, annoyingly breaking, but isn't it more consistent?
I've mistakenly used `!==` thinking it had the meaning of `!(==)` for a long time.
Even the doc string for `!` says:
```
!f::Function

  Predicate function negation: when the argument of ! is a function, it returns a function which
  computes the boolean negation of f.
```
Which is *not* true for "function" `==`, since `!==` equals to `!(===)`. (Btw, is `==` considered a function?).

I decided to open this issue after seeing that even [core developer](https://discourse.julialang.org/t/new-iteration-protocol-much-slower/12169/9) sometimes fall on this trap (not on actual code, though, but on discourse).

**Comment by JeffBezanson** [comment]
Yes `==` and `===` are functions. They also predate (by a lot) the use of `!` to negate functions, which helps explain how we got here. There is also a very strong precedent for `!=` from other languages, which does not follow this pattern.

Also, syntax and semantics are different. Particularly in the case of multi-character operators, textual substitution is not necessarily equivalent to function application.

**Comment by Keno** [comment]
I think `!===` is too long.

**Comment by favba** [comment]
I'm not sure myself this change is worth doing. But IMO the way it is now is slightly prone to confusion and I do thing the proposed way is more consistent. But it is a hard precedent to break. So I though to throw it out here to see what others think. 

---

As a side note: I always saw the `!` on `!=` originally -- on C -- as  representing the slash in `≠`. Probably because I learned programming in Fortran, where `!=` is `/=`, so, definitively representing the slash. Things only get confusing when one introduces the `===` and `!==` operators...

**Comment by favba** [comment]
Yes, that is true. But AFAIK "Julia" has been preferring consistency over "tradition". Like choosing `*` for string concatenation instead of `+` (although this is not as strong "tradition" as `!=`).

I think my position on this is that it is not worthwhile changing this, but I have this nagging feeling that making `!==` == `!(==)` is "the right thing to do".

**Comment by KristofferC** [comment]
This is extremely unlikely to happen.
