### ISSUE TITLE
diff(Vector,dims=1)

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLang/julia#27957]
in 0.7.0-beta.108,
```diff(ones(6),dims=1)```  gives

> ERROR: MethodError: no method matching diff(::Array{Float64,1}; dims=1)

In contrast, ```sum(ones(6),dims=1)``` works.

**Comment by martinholters** [comment]
Yes, I don't see why we shouldn't have a general `diff(A::AbstractArray; dims)` method which would also cover the `Vector` case.

**Comment by deepaknalore** [comment]
@PaulSoderlind Hey A newbie here. Can you please point me at the right direction?

**Comment by shaktee** [comment]
What should its be behavior be?

**Comment by PaulSoderlind** [comment]
> What should its be behavior be?

The same as cumsum seems to be a good starting point. /Paul S
