### ISSUE TITLE
Change unspecified defaults in Base.@kwdef to required kwargs

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#27970]
Currently we have the handy macro `Base.@kwdef`, which turns
```julia
Base.@kwdef struct A
    a::String = "hello"
    b::Int
end
```
effectively into
```julia
struct A
    a::String
    b::Int
end
A(; a::String="hello", b::Int=0) = A(a, b)
```
Note that `b` is given a default value of 0, even though no default was specified in the initial definition.

The introduction of `Base.@kwdef` predates required keyword arguments. But since we now have them, I would propose that any fields not explicitly given a default in `Base.@kwdef` become required keyword arguments. That is,
```julia
Base.@kwdef struct A
    a::String = "hello"
    b::Int
end
```
would instead become
```julia
struct A
    a::String
    b::Int
end
A(; a::String="hello", b) = A(a, b)
```
which will throw an error if `b` is not specified.

If we choose to go ahead with this, we could implement it straight away, which would be breaking, or we could emit a deprecation warning when no default is given, then implement this between 0.7 and 1.0.

Thoughts?

**Comment by JeffreySarnoff** [comment]
I second your suggestion (as there  is no alternative that is not more cacophonous)

**Comment by fredrikekre** [comment]
Note that `@kwdef` is not exported, and not documented in the manual, so we can do whatever we want with it (?) :slightly_smiling_face:

**Comment by StefanKarpinski** [comment]
Correct, since `@kwdef` is not public, we can change it whenever. I do think this change is a good one though.

**Comment by ararslan** [comment]
> not documented in the manual

Ah, it has a docstring but I didn't realize it wasn't in the manual. Perhaps a deprecation is unnecessary then and we can just do this?

**Comment by StefanKarpinski** [comment]
Sure, that seems reasonably to me. It kind of depends on how much havoc it causes in the ecosystem.

**Comment by fredrikekre** [comment]
> It kind of depends on how much havoc it causes in the ecosystem.

This is the only use I found searching all registered packages:
https://github.com/ZacLN/DocumentFormat.jl/blob/6c62c89d907d9f59d5fa63d7599fb84b21972f8a/src/formatconfig.jl#L16

**Comment by KristofferC** [comment]
Guilty!

**Comment by ararslan** [comment]
This wouldn't even break that one use given that they specify values for all fields.
