### ISSUE TITLE
cross reference `isdefined` and `@isdefined`

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#27978]
I prepared a branch that does this and tested the html locally, but did not issue a PR.

A possible issue:
At the REPL, I think this is useful. 
But, in the html docs, the documentation for the macro is adjacent to the documentation for the function.

**Comment by open-source-explorer** [comment]
@fredrikekre What is to be done here?

**Comment by StefanKarpinski** [comment]
Just add the appropriate "See also:" line to each with the right links.
