### ISSUE TITLE
perf regression with `findfirst` over a `svec`

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#27995]
`findfirst` over a `svec` allocates and is slower on 0.7:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-beta.206 (2018-07-08 19:42 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit b6f9244* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> v = Core.svec([Symbol("s$n") for n in 1:20]...)
svec(:s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :s9, :s10, :s11, :s12, :s13, :s14, :s15, :s16, :s17, :s18, :s19, :s20)

julia> using BenchmarkTools

julia> @btime findfirst(x->(x===:s20), v);
  6.940 μs (40 allocations: 1.25 KiB)
```

With 0.6.3:

```
julia> @btime findfirst(x->(x===:s20), v);
  297.317 ns (0 allocations: 0 bytes)
```

And on both 0.6 and 0.7:
```
julia> v = ([Symbol("s$n") for n in 1:20]...,);

julia> @btime findfirst(x->(x===:s20), v);
  32.161 ns (0 allocations: 0 bytes)
```

**Comment by nalimilan** [comment]
The return value of `getindex(::SimpleVector, ::Int)` is no longer inferred on 0.7, contrary to 0.6.

**Comment by JeffBezanson** [comment]
I don't think we could ever infer `getindex` of a `SimpleVector` (its element type is `Any`). Do you have an example?

This is caused by SimpleVector not being an AbstractVector, so `pairs` for it does not return a `Pairs` object.

**Comment by nalimilan** [comment]
> I don't think we could ever infer getindex of a SimpleVector (its element type is Any). Do you have an example?

Carry on, I mistakenly copied `v = ([Symbol("s$n") for n in 1:20]...,)` on 0.6 instead of `v = Core.svec([Symbol("s$n") for n in 1:20]...)`.

**Comment by martinholters** [comment]
Looks like
```julia
Base.pairs(v::Core.SimpleVector) = Base.Iterators.Pairs(v, LinearIndices(v))
```
does the trick. Guess we could add it here:
https://github.com/JuliaLang/julia/blob/092b6c906c77187d391b3f8d5f6000d0ba08716e/base/iterators.jl#L223-L226
