### ISSUE TITLE
poor inference when calling constant IntrinsicFunction passed as argument

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#28003]
~A non-Cassette MWE for https://github.com/jrevels/Cassette.jl/issues/45 and a demonstration of a regression from #26826 (ported to the new optimizer in #26981)~ see comment below

On current master (b6f9244d6b):

```julia
julia> g(f, args...) = f(args...)
g (generic function with 1 method)

julia> h(args...) = g(Base.pointerref, args...)
h (generic function with 1 method)

julia> code_typed(h, (Ptr{Float32}, Int, Int); optimize = false)
1-element Array{Any,1}:
 CodeInfo(
1 1 ─ %1 = :(Base.pointerref)::Core.Compiler.Const(pointerref, false)       │
  │   %2 = Core.tuple(%1)::Core.Compiler.Const((pointerref,), false)        │
  │   %3 = Core._apply(Main.g, %2, %%args)::Any                             │
  └──      return %3                                                        │
) => Any
```

This was previously working at commit 1d53232f7d (not an exact bisect):

```julia
julia> g(f, args...) = f(args...)
g (generic function with 1 method)

julia> h(args...) = g(Base.pointerref, args...)
h (generic function with 1 method)

julia> code_typed(h, (Ptr{Float32}, Int, Int); optimize = false)
1-element Array{Any,1}:
 CodeInfo(:(begin
      nothing
      Core.SSAValue(0) = Base.pointerref
      Core.SSAValue(1) = (Core.tuple)(Core.SSAValue(0))::Tuple{Core.IntrinsicFunction}
      Core.SSAValue(2) = (Core._apply)(Main.g, Core.SSAValue(1), args)::Float32
      return Core.SSAValue(2)
      6:
  end)) => Float32
```

**Comment by jrevels** [comment]
Argh - I bisected this MWE to 9277d3af2dcfc107021989473829a6c9454d83fb (cc @JeffBezanson), but that's too recent for it to be the direct cause of the problem in jrevels/Cassette.jl#45 (commits before 9277d3af2dcfc107021989473829a6c9454d83fb exhibit the regression there). Oh well, back to the bug hunt.

**Comment by JeffBezanson** [comment]
This is because in `g(f::IntrinsicFunction, ...) = f(...)`, the call to `f` is dynamic (since the call target isn't known). Previously the inlining cost model said this call has no cost, which is wrong, so this method was marked as inlineable. Inference then used that as a hint that it's worth doing constant propagation.

The only fix that comes to mind is always doing constant propagation if an argument is a known IntrinsicFunction.

**Comment by jrevels** [comment]
Right, Cassette'ified calls inferring poorly due to intrinsic functions not constant propagating was the main motivation for me to implement vararg constant propagation in the first place.

> Inference then used that as a hint that it's worth doing constant propagation. The only fix that comes to mind is always doing constant propagation if an argument is a known IntrinsicFunction.

It seems dangerous to let inlining heuristics determine whether or not constant propagation happens when we're relying on constant propagation to infer basic function calls.

I guess the only alternative besides further special-casing for IntrinsicFunctions is to give each IntrinsicFunction its own type. This would be nice for other reasons as well, but I'm assuming that would result in non-negligible compile-time/memory regressions.

**Comment by jrevels** [comment]
@vtjnash @Keno Well whaddayaknow, this is indeed fixed by setting `aggressive_constant_propagation=true`:

```
julia> code_typed(h, (Ptr{Float32}, Int, Int))
1-element Array{Any,1}:
 CodeInfo(
1 ─ %1 = (getfield)(args, 1)::Ptr{Float32}
│   %2 = (getfield)(args, 2)::Int64
│   %3 = (getfield)(args, 3)::Int64
│   %4 = (pointerref)(%1, %2, %3)::Float32
└──      return %4
) => Float32
```

What does that mean for next steps for resolving this issue?

**Comment by vtjnash** [comment]
This can probably be assumed to be improved now.
