### ISSUE TITLE
[wishlist/appearance] Julia's default prompt string

### ISSUE THREAD

**Issue by CDLuminate** [JuliaLang/julia#28024]
Unicode has been extensively used by Julia, and by bash/zsh/fish users. Some users may also want to add some unicode in their prompt string.

After a quick search, I found two characters that looks like Julia's logo: `∴ "therefore"`, `⛬ "historic site"`. Actually in order to avoid confusion, the mathematical symbol should no appear in prompt string.

```
Base.active_repl.interface.modes[1].prompt = "⛬ "
```

^ How about this prompt string?

**Comment by W4anD0eR96** [comment]
bad charset? I see a `⛬` and think it might be not what you want to show.

**Comment by CDLuminate** [comment]
![image](https://user-images.githubusercontent.com/5723047/42494246-34894318-840f-11e8-83e1-8fd5d6166de0.png)

**Comment by CDLuminate** [comment]
https://unicode-table.com/en/26EC/ @W4anD0eR96

**Comment by StefanKarpinski** [comment]
What's the request here? To change the default prompt or to allow users to change their prompt?

**Comment by CDLuminate** [comment]
@StefanKarpinski This is a request to change the default prompt. Although it would require more checks such as font support, but I'm not sure whether there is anybody who likes it.

BTW, I know it is not a problem for a user to change the default prompt. One just need to change the following line and recompile.
```
base/REPL.jl
  39 const JULIA_PROMPT = "julia> "
```

**Comment by fredrikekre** [comment]
I don't think we should change the default prompt at this stage. Fortunately this is very easy to configure yourself; put the following in `./julia/config/startup.jl`:
```
import REPL
function myrepl(repl)
    repl.interface = REPL.setup_interface(repl)
    repl.interface.modes[1].prompt = "⛬ >"
    return
end
atreplinit(myrepl)
```

See also https://discourse.julialang.org/t/changing-the-repl-prompt-from-startup-file/2151/18

**Comment by StefanKarpinski** [comment]
Agree, we're not going to change the default prompt. Given that is there anything actionable here?

**Comment by CDLuminate** [comment]
@fredrikekre Thanks for the snippet and the link, it works perfectly! If it's not inproper to change the prompt string at this stage, how about we just put the above snippet to `etc/startup.jl` as a comment?

**Comment by KristofferC** [comment]
https://kristofferc.github.io/OhMyREPL.jl/latest/features/prompt.html

**Comment by antoine-levitt** [comment]
> This seems to be a very personal preference on your part, @CDLuminate. We have not encountered particularly widespread interest in changing the default Julia prompt. So I'm not sure why that, of all the things one might put in a default startup script, commented out, would be the one thing to put there. I agree it could be documented and given a better API, but that's a different matter.

Many packages ship a default init file with a commented out list of common customizable options. The prompt is the most basic one that people like to change, and that particular prompt is pretty cool, so I think it makes sense.

**Comment by StefanKarpinski** [comment]
That makes sense, although we don't really have an official configuration system so it's hard to have all of the options. We should, however, have an official configuration system and have all of the options commented out in it—or maybe even have a wizard for configuring things a la "[oh my zsh](https://github.com/robbyrussell/oh-my-zsh)".
