### ISSUE TITLE
Printing of some characters seems broken on Windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#28029]
When I run ``println('─')`` on a fresh 0.7-beta REPL on Windows, I get this:

![image](https://user-images.githubusercontent.com/1036561/42510199-7b983de2-844e-11e8-8a21-3d2211a0d62e.png)

Things work fine on julia 0.6. Note that this is not the normal dash, but one that is longer.

EDIT: Oh, and I should add that this breaks the display of DataFrames.jl, so this is not a corner case issue.

**Comment by StefanKarpinski** [comment]
Dup of https://github.com/JuliaLang/julia/issues/27267 which has stalled PR https://github.com/JuliaLang/julia/pull/27380.
