### ISSUE TITLE
diag(::Diagonal) now returns a copy of the underlying diagonal vector

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#28041]
#24324 introduced a breaking change whereby `diag(::Diagonal)` returns a copy of the underlying vector, rather than the vector itself as it used to be in 0.6 (@fredrikekre ). For code that relies on `diag(::Diagonal)` as an accessor function, this now produces large memory allocations. 

This was a somehow breaking change but no warnings are emitted. Perhaps, the NEWS.md should be updated to reflect the new behaviour and probably the docs of `diag(::Diagonal)` too. What is the recommended way of accessing the underlying field?

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/julia/pull/24324 for the rationale of the change.

> For code that relies on diag(::Diagonal) as an accessor function, this now produces large memory allocations.

Use `D.diag`?

**Comment by oscardssmith** [comment]
does that work in generic code?

**Comment by fredrikekre** [comment]
No, there you should use `diag(A)`.

**Comment by oscardssmith** [comment]
so then the issue is that previously, `diag(A)` would convert if necessary, but would not copy of it didn't need to, while now it copies no matter what making generic efficient code harder.

**Comment by fredrikekre** [comment]
No? Now you can use `x = diag(A)` and freely change `x` without modifying `A`, making generic code easier. This was one of the motivations for the change.

**Comment by gasagna** [comment]
IIUC, the rationale of #24324 was that to have `diag(A::Diagonal)` return a copy vector, like when `A` is a dense matrix. While I understand why this would useful in generic code, this remains a breaking change that should be documented, at least in NEWS.md. Possibly a deprecation warning should be emitted.
