### ISSUE TITLE
`@which` pointing to buildbot directory on nightly builds

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#28052]
```julia
julia> using LinearAlgebra

julia> @which Matrix(Diagonal(rand(3)))
(::Type{Array{T,2} where T})(D::Diagonal) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/diagonal.jl:56

julia> versioninfo()
Julia Version 0.7.0-beta.201
Commit cdd4e84ac9 (2018-07-07 22:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

**Comment by KristofferC** [comment]
Hasn't that always been the case?

**Comment by fredrikekre** [comment]
> I think that has always been the case?

But when stdlib was in the `base/` directory the path was printed relative that, so it never leaked out.

**Comment by KristofferC** [comment]
Ah, good point.

**Comment by fredrikekre** [comment]
Perhaps those paths should be printed relative the julia root directory instead? IMO
```
julia> @which println("Hello")
println(xs...) in Base at base/coreio.jl:4
```
is better than the current
```
julia> @which println("Hello")
println(xs...) in Base at coreio.jl:4
```

and files in stdlib files would then print like `stdlib/LinearAlgebra/...`

**Comment by tkoolen** [comment]
Note by the way that this also applies to `@edit`, which makes it harder to see how things are implemented in stdlib packages on nightly.

**Comment by hessammehr** [comment]
Getting the same behaviour now on 0.7.0. :( 

Seconding @tkoolen's point: it's a shame because you lose the easy path to debugging/contributing to Julia using @edit <broken function call>.

**Comment by crstnbr** [comment]
Just ran into this issue on stable Julia 1.0. Note that the links generated when executing `@which` in a jupyter notebook won't work because of this. Hope this will be fixed soon!

**Comment by tpapp** [comment]
@crstnbr: note that compiling from source is a very simple workaround in the meantime.

**Comment by crstnbr** [comment]
Because of this Rebugger can't jump into stdlib code.

---

> @crstnbr: note that compiling from source is a very simple workaround in the meantime.

It's not very simple on Windows but thanks for the comment.

**Comment by RalphAS** [comment]
dup of #26314. Workaround is to build one's own system image. (Easier now that PkgCompiler works.)

**Comment by cossio** [comment]
Seems that `@edit` does not work for stdlib functions because of this, Julia v1.0.1.

**Comment by vtjnash** [comment]
as mentioned above, this is a duplicate
