### ISSUE TITLE
AbstractChannel is currently not parametric

### ISSUE THREAD

**Issue by donm** [JuliaLang/julia#28124]
The `AbstractChannel` type is not parametric; it's defined as
```
abstract type AbstractChannel end # channels.jl: 3
```

But should it be parametric?  Will something with the `Channel` interface ever require more flexibility than would be allowed by this?:
```
abstract type AbstractChannel{T} end
```

The reason why this came up is because `Channel` and `RemoteChannel` do not share a common supertype below `Any`, and I'd like to create a type union for functions that accept anything with the channel interface.  This is valid and catches most (all?) of the built-in cases: 
```
 AnyChannel{T} = Union{Channel{T}, RemoteChannel{Channel{T}}}  
```
but trying to expand that definition to `AbstractChannel`s is not valid
```
 AnyChannel{T} = Union{AbstractChannel{T}, RemoteChannel{AbstractChannel{T}}}  # -> TypeError
```

**Comment by StefanKarpinski** [comment]
This seems like a good idea; also shouldn't `AbstractChannel` be a supertype of `RemoteChannel`?

**Comment by donm** [comment]
That would be excellent, and it would also be great if `RemoteChannel` supported what seems to bethe full Channel interface (iteration, `isopen`, ....).  But currently `RemoteChannel` is a `Base.Distributed.AbstractRemoteRef`.  It could instead just _have_ a `RemoteRef`, but _be_ an `AbstractChannel`. But that's a bigger change and I haven't thought through the implications.

**Comment by StefanKarpinski** [comment]
The immediate change to Base (as opposed to stdlib/Distributed) is just adding the type parameter.

**Comment by JeffBezanson** [comment]
Sounds good.
