### ISSUE TITLE
attaching docstring triggers a deprecation warning in 0.7

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaLang/julia#28123]
The following code runs well

```
function main(x::(a=Integer))
    println(x)
end
main(2)


$ julia test.jl
2
```

But this gives a deprecation warning with no useful information:

```
"a doc string"
function main(x::(a=Integer))
    println(x)
end
main(2)


$ julia test.jl
┌ Warning: Deprecated syntax `assignment inside T{ }`.
└ @ none:0
2
```

I noticed that the docstring is actually transformed to a macro call, which after expand is something like

```
#= REPL[3]:2 =#
begin
    function main(x::(a = Integer))
        #= REPL[3]:4 =#
        println(x)
    end
    (Base.Docs.doc!)(Main, (Base.Docs.Binding)(Main, :main), (Base.Docs.docstr)((Core.svec)("a doc string"), (Dict)(:path => "REPL[3]", :linenumber => 2, :module => Main)), Union{Tuple{a = Integer}})
end
```

which also means that if it's an expression (like `function f(x::get_type()) = `), it will be called twice and the docstring would be attached to a different method if `get_type()` does not always return the same type.

**Comment by JeffBezanson** [comment]
It's certainly possible to fix this, but I would also strongly recommend against writing code like this.
