### ISSUE TITLE
Reference to `Base.parse` in section on Julia ASTs should be to `Meta.parse`

### ISSUE THREAD

**Issue by mlhetland** [JuliaLang/julia#28125]
In the documentation section on Julia ASTs, there is [a reference to `parse`](https://github.com/JuliaLang/julia/blame/a8c53e08e961cad86b391dac6b3c212417960d89/doc/src/devdocs/ast.md#L4), which goes to the documentation for [`Base.parse`](https://docs.julialang.org/en/latest/base/numbers/#Base.parse) – specifically the version for numbers (i.e., not the deprecated version that would technically be correct here). It should instead go to [`Meta.parse`](https://docs.julialang.org/en/latest/base/base/#Base.Meta.parse-Tuple{AbstractString}). (I was about to edit the Markdown source, but realized I wasn't sure how to make the `@ref` go to the correct function :->)

**Comment by fredrikekre** [comment]
Should be enough to change it to
```
[`Meta.parse`](@ref)
```
