### ISSUE TITLE
Sparse Matrix performance regression in Julia 0.7.0-beta2.12 (addition, substraction, multiplication, division)

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaLang/julia#28134]
I see a performance regression in Julia 0.7.0-beta2.12 (2018-07-15 15:57 UTC, Commit a878341b2b ) for the arithmetic on sparse matrices, for example the addition:

```julia
using SparseArrays
using LinearAlgebra
using BenchmarkTools
n = 10000; S = sparse(1.0I,n,n); S2 = sparse(1.0I,n,n); @btime $(S)+$(S2);
```

In Julia 0.6.4, I get:
146.918 μs (7 allocations: 390.97 KiB)

while in Julia 0.7.0:
32.961 ms (557135 allocations: 9.04 MiB)

In both cases, the execution time scales linearly on n. 
I see similar regression for the operations `S-S2` and `S*S2`, `S/S2` and `S\S2`, this time with slight smaller matrices:

```
n = 1000; S = sparse(1.0I,n,n); S2 = sparse(1.0I,n,n); 
@btime $(S)-$(S2)
@btime $(S)-$(S2)
@btime $(S)\$(S2)
@btime $(S)/$(S2)
```
Julia 0.6.4:
```
14.172 μs (4 allocations: 39.55 KiB)
14.200 μs (4 allocations: 39.55 KiB)
6.297 ms (24 allocations: 15.30 MiB)
30.555 ms (41 allocations: 30.62 MiB)
```

Julia 0.7.0-beta2.12:

```
2.595 ms (28718 allocations: 504.52 KiB)
2.602 ms (28718 allocations: 504.52 KiB)
5.307 s (55765198 allocations: 866.48 MiB)
5.348 s (55811776 allocations: 867.45 MiB)
```

**Comment by KristofferC** [comment]
Seems fixed on new beta?

`Julia Version 0.7.0-beta2.0`:

```
julia> @btime $(S)+$(S2);
  7.529 μs (4 allocations: 39.55 KiB)

julia> @btime $(S)-$(S2);
  6.883 μs (4 allocations: 39.55 KiB)

julia> @btime $(S)\$(S2);
  10.954 ms (27 allocations: 64.81 KiB)

julia> @btime $(S)/$(S2);
  10.941 ms (41 allocations: 112.81 KiB)
```

`0.6.4`:

```
julia> @btime $(S)+$(S2);
  10.355 μs (4 allocations: 39.55 KiB)

julia> @btime $(S)-$(S2);
  9.265 μs (4 allocations: 39.55 KiB)

julia> @btime $(S)\$(S2);
  4.910 ms (24 allocations: 15.30 MiB)

julia> @btime $(S)/$(S2);
  24.809 ms (41 allocations: 30.62 MiB)
```

`\` seems a bit slower than 0.6 though.

**Comment by Alexander-Barth** [comment]
Sorry, I was running julia with `--inline=no` to get better stack straces (for porting my code to julia 0.7). Without this option, I get about the same speed as julia 0.6.4.
