### ISSUE TITLE
When precompilation fails the output isn't helpful

### ISSUE THREAD

**Issue by kshyatt** [JuliaLang/julia#28148]
I'm attempting to precompile some GPU packages on a GPU worker node on a cluster (with `release-0.6`). When I precompile packages on the head node (such as JSON.jl), everything is fine! When I try to precompile something on the worker node, which theoretically shares the same filesystem as the head node (and I verified the permissions look the same on both), I get:

```julia
julia> using MicroLogging
INFO: Precompiling module MicroLogging.
WARNING: --output requested, but no modules defined during run
WARNING: Cache file "/mnt/home/khyatt/.julia/lib/v0.6/MicroLogging.ji" not found.
ERROR: Module MicroLogging declares __precompile__(true) but require failed to create a usable precompiled cache file.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:502
 [2] require(::Symbol) at ./loading.jl:405
```

I'm pretty sure there's something funny going on with the cluster. But this output is not at all helpful to figure out what that might be. Is there any way the warnings/error messages for When ~~Prophecy~~ Precompilation Fails could be improved? I dug into the precompilation C code and it wasn't particularly illustrative.

**Comment by kshyatt** [comment]
Update: looks like this was a bug with Julia handling Skylake CPUs, and after I built things on the GPU node with `MARCH=haswell` everything works. Nevertheless, I think my complaint that the error/warning output is opaque about what the real problem is stands.

**Comment by affans** [comment]
As a very unrelated question, what scheduling manager are you using on your cluster? We have slurm installed on our cluster with node018 as the GPU node. I usually just use a modified `ClusterManager.jl` to allocate resources, but I don't know how to connect to node018 specifically. This might be more of a question of using the cluster than Julia.

**Comment by vtjnash** [comment]
`__precompile__(true)` is removed, so I think this should now fallback to loading it at runtime, and indicating whatever failed (I suspect the file was empty here because of some sort of cluster error)
