### ISSUE TITLE
Documentation of outputs in ordschur() wrong

### ISSUE THREAD

**Issue by BenjaminBorn** [JuliaLang/julia#28145]
The docstring of `ordschur` states:
```
ordschur(S::StridedMatrix, T::StridedMatrix, Q::StridedMatrix, Z::StridedMatrix, select) 
-> S::StridedMatrix, T::StridedMatrix, Q::StridedMatrix, Z::StridedMatrix, α::Vector, β::Vector
```

However, the vectors α and β are actually the third and fourth outputs as you can see here:
```
A = randn(10, 10)
B = randn(10, 10)

S, T, Q, Z =  schur(A, B)[1:4]

select = bitrand(size(S, 1))

s, t, α, β, qq, zz = ordschur(S, T, Q, Z, select)
```

Would it make sense to change the ordering of the outputs? I'm also happy to open a pull request to correct the docstring if the order is here to stay.

Edit: This is in Julia 0.6.4 on MacOS.

**Comment by andreasnoack** [comment]
Thanks. Actually, I think we should simply deprecate the two methods where the individual components are passed instead of the factorization. That would also fix the problem here. It would be great with a PR.

**Comment by affans** [comment]
I can work on this. Does it make sense to change the return the output of the function or simply change the docstring to match the current function?

**Comment by BenjaminBorn** [comment]
I think Andreas' idea is it to deprecate the two methods that don't just return the factorization object.

**Comment by BenjaminBorn** [comment]
Andreas, I'm happy to do a PR if @affans doesn't beat me to it. Could you point me to an example of how to do the deprecation? Haven't done this before. Thanks!

**Comment by andreasnoack** [comment]
> Could you point me to an example of how to do the deprecation?

Yes. Please have a look at https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/deprecated.jl. For this deprecation, it might make more sense to write a custom one like https://github.com/JuliaLang/julia/blob/299300a409c35153a1fa235a05c3929726716600/stdlib/LinearAlgebra/src/deprecated.jl#L85-L90 explaining the user should use a factorization. The alternative is to use `@deprecate` and construct the factorization from the factors but I don't really like that. If the user wants to reorder then the users shouldn't have extracted the factors in the first place.

**Comment by affans** [comment]
@BenjaminBorn You may go ahead with this if you want. I just submitted my first PR yesterday (a very small doc change) and I am still on that open-source PR high :)

**Comment by BenjaminBorn** [comment]
I have opened #28155 but I think I need some help.

**Comment by kshyatt** [comment]
That PR was merged so this is dealt with, right?
