### ISSUE TITLE
Performance issue with append! and UnitRange on 0.7

### ISSUE THREAD

**Issue by mgcth** [JuliaLang/julia#28143]
There seems to be performance issues with `append!` of `UnitRange` in 0.7.

**MWE:**
```
function test()
    x1 = Vector{Int64}() # or x1 = Vector{Int64}(undef, 0) for 0.7 (no difference)
    for i = 1:1e5
        x2 = 1:3
	append!(x1, x2)
    end
end
```

**0.6:**
```
@time test() # second run
  0.005858 seconds (23 allocations: 5.001 MiB)
```

**0.7:**
```
@time test() # second run
  9.813174 seconds (23 allocations: 5.001 MiB)
```

**0.6 `versioninfo()`:**
```
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**0.7 `versioninfo()`:**
```
Julia Version 0.7.0-beta2.6
Commit faee1df893* (2018-07-14 20:16 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

See also, [https://discourse.julialang.org/t/binary-data-reader-200x-slower-on-0-7/12424/5](https://discourse.julialang.org/t/binary-data-reader-200x-slower-on-0-7/12424/5). There a solution was proposed wrapping around `push!` instead which improved performance.

**Comment by KristofferC** [comment]
Seems like it is O(n^2) in the `∈` check in that is checked in every iteration.

https://github.com/JuliaLang/julia/blob/fbc30cd6c744c8cef82cb6fd54d10bdce9b36692/base/abstractarray.jl#L765-L777

**Comment by KristofferC** [comment]
Seems like it becomes O(n^2) in the `∈` check in that is checked in every iteration.

https://github.com/JuliaLang/julia/blob/fbc30cd6c744c8cef82cb6fd54d10bdce9b36692/base/abstractarray.jl#L765-L777

The difference is that `linearindeces` on 0.6 used to give a `Base.OneTo(3)` which had a O(1) `in` lookup since it was an `AbstractRange`. It now gives a `LinearIndices` which does not have a O(1) lookup.
