### ISSUE TITLE
inlining regression in large StaticArray kernels

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#28168]
See https://github.com/JuliaLang/julia/issues/28078#issuecomment-405026204

We should improve the inlining cost model to account for the time needed to return large structs on the stack.

**Comment by vtjnash** [comment]
StaticArrays looks like it very aggressively marks these kernels `@inline` now. While that is generally bad, it does hide this issue with the benchmarking performance of repeatedly running the same matmul.
