### ISSUE TITLE
Memory leak when writing to console with println in Julia 0.6.3 and 0.6.4

### ISSUE THREAD

**Issue by doctordreas** [JuliaLang/julia#28165]
In version 0.6.3, and version 0.6.4 there is a memory leak when writing to console with println.

The following code snippet demonstrates the problem.
```julia
julia> for i=1:typemax(Int); println("i=",i); end
```
Task manager shows the working set memory continuously increasing.

Have observed this on Windows 7 and Windows 10 in both cmd and powershell.
Not yet tested on OSX or Linux.

Interrupting the loop with CTRL-C and running `gc()` has no or little effect.

The memory leak is not present in 0.6.2, or 0.7 beta 2.
```
julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb* (2018-07-09 19:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, nehalem)
```

**Comment by ararslan** [comment]
I can reproduce on Linux. In 0.6.4, `top` shows the percent of memory used by Julia steadily climb to 3.0% (then stop), whereas 0.7.0-beta2.35 takes a flat 1.8%.

**Comment by traktofon** [comment]
I can also reproduce an elevated memory usage in Linux, where the julia 0.6.4 process takes significantly more memory than 0.6.2 or 0.7.0-beta2.91. Moreover, the printing is much slower in 0.6.4. With the following definition
```julia
doprint(n) = begin; for i=1:n; println("i=",i); end; end
```
the call `@time doprint(100_000)` gives on 0.6.2
> 0.903938 seconds (911.99 k allocations: 27.649 MiB, 0.35% gc time)

and likewise on 0.7.0-beta2.91
> 0.938301 seconds (1.01 M allocations: 27.641 MiB, 0.21% gc time)

while on 0.6.4
> 80.690286 seconds (899.50 k allocations: 526.881 MiB, 0.32% gc time)

Additional observation on 0.6.4: the printing starts fast but becomes slower and slower. Eventually it suddenly becomes fast again, then gradually slows down again. This process repeats. The jumps in speed coincide with a sudden increase in memory usage of the julia process.

Julia 0.6.3 behaves like 0.6.4 in this respect.

**Comment by KristofferC** [comment]
FWIW here is the diff between 0.6.2 and 0.6.3 in case anyone want to dig: https://github.com/JuliaLang/julia/compare/v0.6.2...v0.6.3.

**Comment by vtjnash** [comment]
I strongly suspect the bugfix 
https://github.com/JuliaLang/julia/commit/fe59a2b2be242e1bfd94390dc51b7cfec6b97a29 might be at fault for the performance change. We might need to further investigate performance tuning issue with IdDict.

**Comment by mgkuhn** [comment]
Can't reproduce in Julia 1.6.2, so I assume this has long been fixed.
