### ISSUE TITLE
sqrt of complex numbers does not work right

### ISSUE THREAD

**Issue by toftul** [JuliaLang/julia#28176]
Result of sqrt(-x^2) depends on both sing of Re x and sing of Im x which is nonsense!
From complex calculations sqrt(-2^2) = **+** i 2.

Minimal example:

```
x = 2. + 0im
x^2  # result = 4.0 + 0.0im
sqrt(-x^2)  # result = 0.0 - 2.0im

# however this works fine
sqrt(-4 - 0im)  # result = 0.0 + 2.0im
```

My versioninfo() output:
> Julia Version 0.6.4
> Commit 9d11f62bcb (2018-07-09 19:09 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin14.5.0)
>   CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

I also tried on my Linux machine (Manjaro KDE 64bit, Julia 0.6.4) and in JuliaBox (julia 0.6.2). Same output.

**Comment by yuyichao** [comment]
I believe this makes sense since the sign of the zero determines the branch cut and the sign of the zero after squaring depends on the both the real and the imag part.

**Comment by toftul** [comment]
Thank you for the fast answer!

No, I don't think that is makes sense and everything is OK. How can you explain this:
```
x = -4. - 0im 
sqrt(x)  # 0.0 - 2.0im
sqrt(- 4 - 0im)  # 0.0 + 2.0im
```

**Comment by yuyichao** [comment]
Unfortunately signed 0 is only a property of floating point type so the sign of the 0 in the `-4 - 0im` is "lost", i.e.

```julia
julia> -4 - 0im
-4 + 0im

julia> -4.0 - 0im
-4.0 - 0.0im
```

**Comment by toftul** [comment]
Sorry, I think math doesn't work so, the answer here is well defined and does not depend on sing of **zero** imaginary part. By definition i = sqrt(-1). 

I didn't really get about what branches you are saying here in this context:
> I believe this makes sense since the sign of the zero determines the branch cut and the sign of the zero after squaring depends on the both the real and the imag part.
Or I am missing something very simple here...

**Comment by yuyichao** [comment]
> does not depend on sing of zero imaginary part.

That is actually not how math works, in particular not how multivalued complex function works.

`sqrt` on complex number is a multivalue function and you can find out about branch cut [here](https://en.wikipedia.org/wiki/Branch_point#Branch_cuts). If you have more questions about any concepts I've mentioned above, please post it on [discourse](discourse.julialang.org) instead. There's nothing actionable or julia related about `sqrt` here.

**Comment by StefanKarpinski** [comment]
Correct link for discourse: https://discourse.julialang.org/. The short version is that `sqrt` is a multi-valued function in the complex plane: `(0.0 - 2.0im)^2 == (0.0 + 2.0im)^2 == -4`; in other words ±2i are both roots of -4 and the sign of zero of the input in this case distinguishes which of the possible answers you get. This is standard (and even _standardized_) behavior in numerical computing.

**Comment by toftul** [comment]
Thank you very much for the explanation and for the links! I got it now.
