### ISSUE TITLE
Interpolation of __FILE__ into cmd

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#28188]
This used to work on 0.6 
```
julia> @show @__FILE__
#= REPL[1]:1 =# @__FILE__() = "REPL[1]"
"REPL[1]"

julia> @show `$(@__FILE__)`
#= REPL[2]:1 =# @cmd("\$(@__FILE__)") = `none`
`none`
```

**Comment by JeffBezanson** [comment]
#3150 would fix this. Workaround for now is to store the value of `@__FILE__` in a variable:
```
f = @__FILE__
`$f`
```

Another way to fix this is to pass `__source__` from the `cmd` macro into `shell_parse`, and have it set the current source file to that when it calls `parse`.
