### ISSUE TITLE
`@view` doesn't play nicely inside other expressions

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#28189]
currently the `@view` macro [throws an error](https://github.com/JuliaLang/julia/blob/b012ab3a44b64a145d993824319abe00d77e8e32/base/views.jl#L103-L116) if the expression given to it isn't a `:ref` type.

If it is used in an expression like `foo(@view a[1:5], 42)` the arguments are parsed as a tuple:

```
Expr
  head: Symbol tuple
  args: Array{Any}((2,))
    1: Expr
      head: Symbol ref
      args: Array{Any}((2,))
        1: Symbol x
        2: Expr
          head: Symbol :
          args: Array{Any}((2,))
            1: Int64 3
            2: Int64 4
          typ: Any
      typ: Any
    2: Int64 42
  typ: Any
```

If `@view` were expanded to allow a `:tuple` expression as long as a `:ref` expression is the first item, then it could be used in this context. It should also be backwards compatible as that syntax was previously an error. Are there cases where this would be ambiguous?

It would also work if `:(=)` were allowed as well, so `@view x[1:5] = y[6:10]` would work (though in this case broadcasting would be the right thing to do, so I'm not sure if there's a real use-case for this).

**Comment by ssfrr** [comment]
OK, looking into this a little more I realized that if the macro returns a `:tuple` expression then that ends up getting passed through to the function as a literal `Tuple`, instead of an argument list. I think in order for this to work the parser would have to pass in a special `:arglist` expression or something.

So if this was something worth pursuing there'd probably need to be a prerequisite issue "macros can't be used inside argument lists without parentheses", and maybe this isn't a yak worth shaving.

**Comment by mbauman** [comment]
Yup, exactly. I'm not sure there's too much we can do here; the way around is either to use `foo(@view(a[1:5]), 42)` or `@views foo(a[1:5], 42)`.

This is generally a restriction with macros.  They'll "gobble up" a whole tuple into one argument if given the chance.  I think there's an issue about this, but searching for combinations of macro/tuple/argument yields a gazillion results.

**Comment by ssfrr** [comment]
Part of the issue is that in the expression `foo(1, 2)`, the `1,2` part isn't parsed as a tuple before being passed to `foo`, but if you have `foo(@bar 1, 2)` then `1,2` is a tuple. Even if the macro grabs expressions greedily I could see an argument for making sure that what gets passed to the macro is the same parsing as without it, so a macro like:

```julia
macro passthrough(ex)
    ex
end
```

would always be a no-op. This is also an issue with things like array literals, so `[@passthrough 1, 2]` ends up being a `Vector{Tuple{Int64, Int64}}`

**Comment by vtjnash** [comment]
The issue isn't that `@passthrough` doesn't work, it's that the parser state has different rules than normal for consuming white-space-separated expressions inside `macrocall` and `[]` contexts, so the syntax intent is ambiguous
