### ISSUE TITLE
FreeBSD ccall failure

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#28191]
Examples:

* https://freebsdci.julialang.org/#/builders/1/builds/11427
* https://freebsdci.julialang.org/#/builders/1/builds/11292
* https://freebsdci.julialang.org/#/builders/1/builds/11452

Seems to be getting more frequent perhaps?

**Comment by vtjnash** [comment]
We should change that `read` call to pass `stdout=stdout`, so we can learn what failure occurred.

**Comment by ararslan** [comment]
I've been running the `ccall` tests 100 times in a loop on FreeBSD 11.2 (note that the CI machines are running 11.1) trying to reproduce the failure but no luck thus far.

**Comment by ararslan** [comment]
@iblis17, have you managed to reproduce this at all?

**Comment by ararslan** [comment]
Looks like this hasn't happened in a long time, so I'm going to close.
