### ISSUE TITLE
importing Compat.Libdl and Libdl gives an error

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#28190]
Even though `Compat.Libdl === Libdl`, Julia 0.7 gives:
```jl
julia> import Compat.Libdl

julia> import Libdl
ERROR: importing Libdl into Main conflicts with an existing identifier
```
Oddly enough, importing in the other order is fine:
```jl
julia> import Libdl

julia> import Compat.Libdl
```
This is causing an problem at JuliaPackaging/BinaryProvider.jl#90 …

I think we should fix this so that both orders work.  cc @ararslan

**Comment by stevengj** [comment]
@JeffBezanson, it looks like [the intention of this code](https://github.com/JuliaLang/julia/blob/b012ab3a44b64a145d993824319abe00d77e8e32/src/toplevel.c#L536-L539) is that it should work — why is it failing in one order?

**Comment by vtjnash** [comment]
(it's probably that "owner" of the first binding is `Compat`, so it's refusing to re-direct it locally, and unaware that it is `const`, so it doesn't matter)

**Comment by stevengj** [comment]
@vtjnash, so maybe we should just change `b->owner != m` into `(!b->constp && b->owner != m)`?
