### ISSUE TITLE
DateTime hour=24

### ISSUE THREAD

**Issue by christinegz** [JuliaLang/julia#28203]
Hi, I'm using julia to read data files with hourly observations. These also include data at midnight, recorded as 24:00 rather than 00:00. This gives an error upon reading, for example:

DateTime("2018-01-01 24:00","yyyy-mm-dd HH:MM")
ERROR: ArgumentError: Hour: 24 out of range (0:23)

It might be good to make an exception for 24:00, changing to 00:00 the next day, but I'm not sure how/where to change this. (I have little experience with julia so far). Thanks for advice!

**Comment by stevengj** [comment]
Apparently `24:00` is [allowed by ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Times), so this is a bug.  See also https://stackoverflow.com/questions/20879834/parse-date-of-iso-8601-value-240000-fails, moment/moment#1174
