### ISSUE TITLE
IdDict for doc system make it impossible to get signature like `AbstractMatrix{<:Real}`

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#28217]
I asked on discourse but nobody replied...: https://discourse.julialang.org/t/replace-docstring-for-signatures-like-abstractmatrix-real/12541

I think this is mainly because the `IdDict` here, why not `Dict` and if you need `IdDict` for store docstring, then how can I workaround? Pls help me on this.

**Comment by JeffBezanson** [comment]
I'm guessing performance is not an issue here, so when a signature is not found you could iterate through the table to see if there is a matching key.

**Comment by Roger-luo** [comment]
@JeffBezanson So if I just compare the signature (say it is `AbstractMatrix{<:Real}`) with existing keys in the `META` with `==` rather than `===` will this cause any potential error?

**Comment by JeffBezanson** [comment]
No; that should work.

**Comment by Roger-luo** [comment]
Cool，Thanks
