### ISSUE TITLE
Pkg test with arguments for testing packages

### ISSUE THREAD

**Issue by v-i-s-h** [JuliaLang/julia#28219]
Pkg REPL in Julia-0.7.0 allows only to pass the Package name as argument. But there is no way to give an argument (or a list of arguments) to the test script from Pkg REPL.

From bash, we can do (from the corresponding package directory)
```
$ julia ./test/runtests.jl <args>
```
Even though it is possible to give it through julia REPL, like this
```
ARGS = [ <args> ]; include( joinpath(Pkg.dir(<PackageName>),"test","runtests.jl") )
```
but produces the following warning:
```
 Warning: Pkg.dir is only kept for legacy CI script reasons
└ @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:433
```

**Comment by fredrikekre** [comment]
Can you reopen this at https://github.com/JuliaLang/Pkg.jl?

**Comment by v-i-s-h** [comment]
Ok.. Reopened at https://github.com/JuliaLang/Pkg.jl/issues/518
