### ISSUE TITLE
Threading: EXCEPTION_ACCESS_VIOLATION on Linux and Windows

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#28218]
I am on Windows 10, and Julia 0.7.0-beta2.0 (2018-07-13 19:54 UTC).

The following error sometimes is triggered, but not always (and I am reporting it following the instruction given on top of the message):
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 --  at 0x0 --  CESS_VIOLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
in expression starting at KissThreading.jl:19
unknown function (ip: FFFFFFFFFFFFFFFF)
unknown function (ip: 000000006B58F594)
unknown function (ip: 000000006B593305)
_deepcopy_array_t at .\deepcopy.jl:83
unknown function (ip: 000000006B593305)
deepcopy_internal at .\deepcopy.jl:78
unknown function (ip: 000000006B58F594)
unknown function (ip: 000000006B593305)
deepcopy_internal at .\deepcopy.jl:67
deepcopy at .\deepcopy.jl:28 [inlined]
macro expansion at KissThreading.jl:14 [inlined]
#3#threadsfor_fun at .\threadingconstructs.jl:64
#3#threadsfor_fun at .\threadingconstructs.jl:31
unknown function (ip: 000000006B5DC777)
unknown function (ip: 000000006B5DD256)
macro expansion at .\threadingconstructs.jl:75 [inlined]
#trandjump#3 at KissThreading.jl:13
unknown function (ip: 000000006B58F594)
unknown function (ip: 000000006B5921C4)
trandjump at KissThreading.jl:11 [inlined]
trandjump at KissThreading.jl:11
unknown function (ip: 000000006B58F594)
unknown function (ip: 000000006B593305)
unknown function (ip: 000000006B715E41)
unknown function (ip: 000000006B716A8D)
unknown function (ip: 000000006B717FB2)
unknown function (ip: 000000006B7185C0)
unknown function (ip: 000000006B5A992F)
Allocations: 2190486 (Pool: 2190024; Big: 462); GC: 3
```

by running the following code on 2 threads (I have trimmed the file KissThreading.jl only to relevant lines but to keep line counts from the above error message correct):

```
module KissThreading

using Random: MersenneTwister
using Future: randjump



_randjump(rng, n, jump=big(10)^20) = accumulate(randjump, [jump for i in 1:n], init = rng)

function trandjump(rng = MersenneTwister(0); jump=big(10)^20)
    n = Threads.nthreads()
    rngjmp = _randjump(rng, n, jump)
    Threads.@threads for i in 1:n
        rngjmp[i] = deepcopy(rngjmp[i])
    end
    rngjmp
end

const TRNG = trandjump()

end
```

It seems that the reason of the problem is `deepcopy` - but I am not sure - is something wrong with my code?

**Comment by UserQuestions** [comment]
This may not be a Windows-specific problem. I also get a segfault issue from the [same function](https://github.com/bkamins/KissThreading.jl/issues/10) when using Julia v0.7 on Linux (CentOS7).

**Comment by KristofferC** [comment]
A bit off topic but is it guaranteed that thread `i` allocates the RNG at `rngjump[i]` here? Or is the partition of the range made such that this is guaranteed?

**Comment by bkamins** [comment]
This is how `_threadsfor` is implemented in threadingconstructs.jl to my understanding.

In particular if `lenr` is equal to `nthreads` then `len==1` and `rem==0` so `f==l==threadid()` should be met.

We could write:

    Threads.@threads for i in 1:n
        tid = threadid()
        rngjmp[tid] = deepcopy(rngjmp[tid])
    end

to be safe but it should be equivalent (but maybe it is not and this is what causes the problem 😄).

**Comment by KristofferC** [comment]
Or something like https://github.com/nacs-lab/yyc-data/blob/8c7427334869f4c292eae9c8c3828ca03ec0244a/lib/NaCsCalc/src/utils.jl#L120-L142

**Comment by bkamins** [comment]
This a lazy variant of initialization that does not control for proper initialization of RNGS (but we could lazily do a `deepcopy` to another array when needed and use that pattern). But as you have said - this is a side issue. I will try to reproduce the problem without using RNGS but arrays only.

**Comment by JeffBezanson** [comment]
Does this still happen?

**Comment by bkamins** [comment]
I have run some tests on Julia 1.1.0 under Windows and I did not get any errors.

**Comment by JeffBezanson** [comment]
Great, thanks. Feel free to reopen if it comes back.
