### ISSUE TITLE
View allocation elimination stumped by conditional?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#28226]
Tracked down after performance report on Distances.jl (https://github.com/JuliaStats/Distances.jl/issues/100)

Code to reproduce:

```jl
module Distances2

function colwise!(r, a, b)
    @inbounds for j = 1:size(a,2)
        r[j] = evaluate(view(a, :, j), view(b, :, j))
    end
    r
end

@inline function evaluate(a, b)
    length(a) == 0 && return 0.0 # comment out and 0.7 is super fast
    @inbounds begin
        s = 0.0
        @simd for I in eachindex(a, b)
            ai = a[I]
            bi = b[I]
            s += abs2(ai - bi)
        end
        return s
    end
end

end

using BenchmarkTools
z = zeros(41); A = rand(2, 41); B = rand(2, 41);
@btime Distances2.colwise!($z, $A, $B);
```

On 0.7:

```
 562.371 ns (82 allocations: 3.84 KiB)
```

On 0.6:

```
 255.466 ns (0 allocations: 0 bytes)
```

Now, if we comment away the `length(a) == 0 && return 0.0` line:

0.7:
```
100.298 ns (0 allocations: 0 bytes)
```

0.6:
```
 206.193 ns (0 allocations: 0 bytes)
```

**Comment by KristofferC** [comment]
Actually, changing out `eachindex(a, b)` to `1:size(a, 2)` also seems to help.

**Comment by Keno** [comment]
Smells like the inlining heuristic change.

**Comment by KristofferC** [comment]
I checked out the commit before https://github.com/JuliaLang/julia/pull/27857 and it didn't change anything.

**Comment by KristofferC** [comment]
Changing the `if` to a `ifelse` makes the allocation go away, I will use that to work around the original issue.

**Comment by KristofferC** [comment]
Fixed, now zero allocations.
