### ISSUE TITLE
Wrong checksum of utf8proc (Julia 0.6.4)

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#28228]
Hi guys!

It seems that the checksum of the file `utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz` is wrong.

When I download it using:

```
wget https://api.github.com/repos/JuliaLang/utf8proc/tarball/d688ac122660e465dc65c8eb7b1c2444fcd52829 -O utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz
```

I got

```
md5sum utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz
1cbb82b5423a41b7df8cd98c605b81de  utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz
```

However, according to the file `./deps/checksums/utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz/md5` it should be:

```
9e62d28101ad9792161813bb43402202
```

It does not seem something in my connection because `libuv` is working fine.

P.S.: I cannot use the downloader that comes with Julia because I am building the openSUSE package in a server farm.

**Comment by ronisbr** [comment]
I see what happened.

In the past, the tarball came with the following directory structure:

```
JuliaLang-utf8proc-d688ac1/
JuliaLang-utf8proc-d688ac1/.gitignore
JuliaLang-utf8proc-d688ac1/.travis.yml
JuliaLang-utf8proc-d688ac1/CMakeLists.txt
JuliaLang-utf8proc-d688ac1/Doxyfile
JuliaLang-utf8proc-d688ac1/LICENSE.md
...
```

Now it has:

```
JuliaStrings-utf8proc-d688ac1/
JuliaStrings-utf8proc-d688ac1/.gitignore
JuliaStrings-utf8proc-d688ac1/.travis.yml
JuliaStrings-utf8proc-d688ac1/CMakeLists.txt
JuliaStrings-utf8proc-d688ac1/Doxyfile
JuliaStrings-utf8proc-d688ac1/LICENSE.md
...
```

Hence, due to the new names, the checksum should be different. It is not a simple pull request to change the checksum in the aforementioned file, because it can have implications in the compilation process. Any ideas how to fix it?

**Comment by ronisbr** [comment]
In the mean time, I used an old version of `utf8proc` I had with the old directory structure and the v0.6.4 build process finished correctly. I am attaching the file here in case someone need to build Julia v0.6.4.

[utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz](https://github.com/JuliaLang/julia/files/2217293/utf8proc-d688ac122660e465dc65c8eb7b1c2444fcd52829.tar.gz)

**Comment by KristofferC** [comment]
Is this an issue on 1.0?

**Comment by ronisbr** [comment]
It is definitely not an issue in v0.7, since the package built fine without any further modification. Hence, I think v1.0 should be ok (I will let more time for people get used to v0.7 before migrating to v1.0).

**Comment by KristofferC** [comment]
Ok, I think we can close then.
