### ISSUE TITLE
Mmap bus error

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#28245]
```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-beta2.84 (2018-07-23 19:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 10002fcb5e* (0 days old master)
|__/                   |  x86_64-apple-darwin16.7.0

julia> using Mmap

julia> a = Mmap.mmap("foo2", Vector{NTuple{1, Int8}}, 1, 0)
1-element Array{Tuple{Int8},1}:
Bus error: 10
```
Also happens for simple structs like `struct Wrapper; x::Int; end`. I plan on taking a look at this to see what's going on, but if anyone else has any ideas, please share in the mean time.

**Comment by JeffBezanson** [comment]
Works for me.

**Comment by xgdgsc** [comment]
I get bus error if specified shape larger than the file size. Julia would crash. Is it possible to make it not crash the session and only report an error? I think it could check filesize first.

**Comment by xgdgsc** [comment]
```

**Comment by Moelf** [comment]
Does this still crash for some people?

**Comment by xgdgsc** [comment]
The original poster code doesn' t crash. My code in the comment above still crashes.

**Comment by vtjnash** [comment]
As mentioned above https://github.com/JuliaLang/julia/issues/28245#issuecomment-408116616, there is a missing call to `open(identity, "foo2", "w")` in the MWE

**Comment by davidbp** [comment]
On 1.8 I still get weird errors. For example, depending on which position I get from the memmapped file the code crashes ```julia> using Mmap

julia> data = Mmap.mmap("./test.mmap", Matrix{Float32}, (64, 2000_000));

julia> data[:,1_00]; #works fine

julia> data[:,1_000_000]

signal (10): Bus error: 10
in expression starting at REPL[4]:1
getindex at ./array.jl:925 [inlined]
macro expansion at ./multidimensional.jl:903 [inlined]
macro expansion at ./cartesian.jl:64 [inlined]
_unsafe_getindex! at ./multidimensional.jl:898 [inlined]
_unsafe_getindex at ./multidimensional.jl:889 [inlined]
_getindex at ./multidimensional.jl:875 [inlined]
getindex at ./abstractarray.jl:1241
unknown function (ip: 0x10851c1df)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
do_call at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
eval_body at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_toplevel_eval_in at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
eval at ./boot.jl:368 [inlined]
eval_user_input at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:151
repl_backend_loop at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:247
start_repl_backend at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:232
#run_repl#47 at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:369
run_repl at /Users/administrator/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-1.0/build/default-macmini-aarch64-1-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl:355
jfptr_run_repl_67919 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
#966 at ./client.jl:419
jfptr_YY.966_42132 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_f__call_latest at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:729 [inlined]
invokelatest at ./essentials.jl:726 [inlined]
run_main_repl at ./client.jl:404
exec_options at ./client.jl:318
_start at ./client.jl:522
jfptr__start_58825 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
true_main at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
Allocations: 2906 (Pool: 2894; Big: 12); GC: 0
Bus error: 10```

**Comment by elextr** [comment]
Just a note that the Linux [mmap](https://man7.org/linux/man-pages/man2/mmap.2.html) documentation says SIGBUS occurs when an attempt is made to access pages of the mapping beyond the size of the file.

**Comment by vtjnash** [comment]
Still a bug on macOS
