### ISSUE TITLE
Missing doc for Dates.canonicalize (except the function doc of course)

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#28255]
When looking for a way to print a time period as hours and minutes (rounded if necessary) that function was the one that came next. Thus i wanted to search the docs for any way to restrict printing upon hours and minutes (thus interrupting the "breakdown" at hours and allowing >24 hours). Then I found there's nothing to find :D

So if anyone has a hint on how to solve my problem it'd be nice aswell.

**Comment by quinnj** [comment]
I'm not quite sure I understand what the issue is here; is the request to add something to the Dates manual about `canonicalize!`?

**Comment by eengad** [comment]
I would like to clarify that it would be useful to have `canonicalize` in the Dates manual. It is useful for me to implement a custom progress meter, and it was harder to find out about it since it is not in the manual.

**Comment by laborg** [comment]
This has been done in https://github.com/JuliaLang/julia/pull/41775
