### ISSUE TITLE
Unicode 11 support

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#28263]
I just noticed Unicode 11 is out. I'm not sure what needs updating (if anything; may just be in ICU package code).

OR in, I just see that link is now dead (at least Readme.md has this bad link):

https://julialang.org/utf8proc/

I've assumed up to now that Julia at least support up to Unicode 10.0, is that for sure correct?

**Comment by digital-carver** [comment]
A working URL for utf8proc is https://github.com/JuliaStrings/utf8proc, and it looks like it has been updated for Unicode 11 already - just around the time this issue was created in fact.

**Comment by stevengj** [comment]
See also JuliaLang/julialang.github.com#809 — we really need to set up a redirect so that the old URL continues to work.

**Comment by stevengj** [comment]
(The previous version of utf8proc only supported Unicode 9, so that is all that is supported in the current Julia version.)
