### ISSUE TITLE
Parameterized vararg called with no arguments

### ISSUE THREAD

**Issue by HarrisonGrodin** [JuliaLang/julia#28278]
During the development of v0.7, the following behavior has been introduced. When a parameterized vararg is called with no arguments, the use of the parameter (in the following case, `T`) will produce an `UndefVarError`. (This is in contrast to the v0.6 behavior of producing a `MethodError`.)

```julia
julia> f(xs::Val{T}...) where {T} = T
f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] f() at ./REPL[5]:1
 [2] top-level scope at none:0
```

Assuming this is the correct behavior, a more descriptive error message (including where the variable was supposed to be derived/"defined") would likely be less confusing.

---

Edit: @rdeits pointed me to #23117 and [this Discourse conversation](https://discourse.julialang.org/t/remove-additional-rule-that-parameters-must-match-for-dispatch/11482), where the change and its implications are described.

**Comment by JeffBezanson** [comment]
Yes, this is the new intended behavior. The action item is probably to improve the error message.

**Comment by vtjnash** [comment]
done
```
julia> f()
ERROR: UndefVarError: `T` not defined in static parameter matching
Suggestion: run Test.detect_unbound_args to detect method arguments that do not fully constrain a type parameter.
```
