### ISSUE TITLE
Large first compile time regressions for OrdinaryDiffEq.jl on v0.7

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#28293]
User @datseris reported a long compile time regression when using OrdinaryDiffEq.jl (the ODE solvers of DifferentialEquations.jl) on v0.7. The MWE is as follows:

```julia
using OrdinaryDiffEq, StaticArrays
using DiffEqBase: __init

function loop(u, p, t)
    σ = p[1]; ρ = p[2]; β = p[3]
    du1 = σ*(u[2]-u[1])
    du2 = u[1]*(ρ-u[3]) - u[2]
    du3 = u[1]*u[2] - β*u[3]
    return SVector{3}(du1, du2, du3)
end
loopp = [10, 28, 8/3]

function gissinger_eom(u, p, t)
    μ, ν, Γ = p
    du1 = μ*u[1] - u[2]*u[3]
    du2 = -ν*u[2] + u[1]*u[3]
    du3 = Γ - u[3] + u[1]*u[2]
    return SVector{3}(du1, du2, du3)
end
gp = [0.119, 0.1, 0.9]

function hheom!(du, u, p, t)
    du[1] = u[3]
    du[2] = u[4]
    du[3] = -u[1] - 2u[1]*u[2]
    du[4] = -u[2] - (u[1]^2 - u[2]^2)
    return nothing
end

const SOLVER = Vern9()
const DEFAULT_DIFFEQ_KWARGS = (abstol = 1e-9,
                               reltol = 1e-9, maxiters = typemax(Int))

function integrator(f, u0, p, iip = false)

    prob = ODEProblem{iip}(f, u0, (0.0, Inf), p)

    solver = SOLVER
    integ = __init(prob, solver; save_everystep = false, dt = 0.1)
    return integ
end

println("first ever compile")
@time integrator(loop, rand(SVector{3}), loopp)
println("re init: same system")
@time integrator(loop, rand(SVector{3}), loopp)

# change system: Keep dimensionality and in-place form
println("init: new system, same D, IIP")
@time integrator(gissinger_eom, rand(SVector{3}), gp)

# change system: Change dimensionality and in-place form
println("init: new system, different D, IIP")
@time integrator(hheom!, rand(4), nothing, true)
```

The timings on v0.6 on his computer were:

```julia
first ever compile
27.585471 seconds (22.87 M allocations: 1.010 GiB, 1.04% gc time)
re init: same system
0.000128 seconds (162 allocations: 21.359 KiB)
init: new system, same D, IIP
1.039494 seconds (126.18 k allocations: 7.800 MiB)
init: new system, different D, IIP
1.584868 seconds (555.58 k allocations: 29.888 MiB, 0.64% gc time)
```

while on v0.7:

```julia
first ever compile
 26.641318 seconds (16.83 M allocations: 908.779 MiB, 5.36% gc time)
re init: same system
  0.000645 seconds (210 allocations: 24.984 KiB)
init: new system, same D, IIP
  4.906538 seconds (2.84 M allocations: 154.814 MiB, 2.59% gc time)
init: new system, different D, IIP
 76.214160 seconds (93.34 M allocations: 4.366 GiB, 4.64% gc time)
```

A few explanations are probably in order. The first ever compile is easy to understand and was larger than we liked in v0.6 as well, though it's not clear to us what the issue exactly is. Disregarding that, on each new input function the solvers recompile which is the `init: new system, same D, IIP` setup and that shows a 4x regression. There's an alternative function definition form which is allowed (iip: is inplace) and that shows a huge regression (this is the standard DifferentialEquations.jl use case, so this is quite worrisome).

What happens if you don't specialize on the ODE function? Well on DiffEq v0.7 we added a compile-time constant that can control that: https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/diffeqfunction.jl#L1 . On my computer with `true` the timings are:

```julia
first ever compile
  5.732393 seconds (16.24 M allocations: 876.301 MiB, 6.03% gc time)
re init: same system
  0.000108 seconds (210 allocations: 24.984 KiB)
init: new system, same D, IIP
  1.825962 seconds (2.84 M allocations: 154.782 MiB, 3.20% gc time)
init: new system, different D, IIP
 34.937379 seconds (93.35 M allocations: 4.366 GiB, 6.31% gc time)
```

and with false:

```julia
first ever compile
  6.171682 seconds (17.46 M allocations: 942.681 MiB, 6.44% gc time)
re init: same system
  0.000134 seconds (257 allocations: 26.016 KiB)
init: new system, same D, IIP
  0.022453 seconds (34.59 k allocations: 1.851 MiB)
init: new system, different D, IIP
 37.914473 seconds (94.43 M allocations: 4.426 GiB, 6.15% gc time)
```

So we are considering reducing the function specialization default, but it doesn't change the first compile time or the first IIP compile time. I mention that it's first IIP compile time since append this gives:

```julia
function loop2(du, u, p, t)
    σ = p[1]; ρ = p[2]; β = p[3]
    du[1] = σ*(u[2]-u[1])
    du[2] = u[1]*(ρ-u[3]) - u[2]
    du[3] = u[1]*u[2] - β*u[3]
end
@time integrator(loop2, ones(3), loopp, true) # RECOMPILE_BY_DEFAULT = true
0.931281 seconds (3.60 M allocations: 188.634 MiB, 7.76% gc time)
```

i.e. it you can consider the code as fully compiling once when `iip = false` and once when `iip = true`. 

These timings include the fix for https://github.com/JuliaLang/julia/issues/28221 .

I'm not sure how to profile compilation correctly so if someone has tips I can help post some profiler results.

**Comment by ChrisRackauckas** [comment]
Profiler output gist: https://gist.github.com/ChrisRackauckas/981c40c0a9d1757c057867d5ada81387

It couldn't save the whole trace though. And that output looks like nonsense to me haha.

**Comment by KristofferC** [comment]
You can set the trace collection frequency https://docs.julialang.org/en/stable/manual/profile/#Configuration-1.

**Comment by JeffBezanson** [comment]
Do you have a sense of what the big difference in code paths is between the super-slow case and the other case? E.g. a large function or set of functions that are only used in one? Might be useful if you happen to know, otherwise some thing are already evident in the profile.

**Comment by ChrisRackauckas** [comment]
Better profile ran with:

https://gist.github.com/ChrisRackauckas/6377bd4031661d1481f7be54a966f088

```julia
using Profile
Profile.init(n = 10^6, delay = 4.0)
cd()
cd(".julia")
Profile.@profile integrator(hheom!, rand(4), nothing, true)
open("profile_results.txt","w") do f
  Profile.print(IOContext(f, :displaysize => (50, 2500)),format=:flat)
end
```

Lower delay values and high `n` tend to segfault (?). I can try to tune it more if needed.

**Comment by ChrisRackauckas** [comment]
The difference from IIP is whether to run the not-in-place stepping:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/verner_rk_perform_step.jl#L634-L703

Or the in-place stepping:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/verner_rk_perform_step.jl#L705-L899

Both have a long base compile time, but the latter regressed a bunch while the former did not. This algorithm does have very long hand-written linear combinations so it may be something to do with long tuple changes? Though I'm surprised that would not hit the static array path but would hit the array looping path really hard. Note that `@tight_loop_macros` is currently nothing.

**Comment by JeffBezanson** [comment]
Looks like constant propagation is involved; possibly due to all the constant indices.

**Comment by JeffBezanson** [comment]
Timings I get:
```
first ever compile
 10.297412 seconds (16.46 M allocations: 887.439 MiB, 4.65% gc time)
re init: same system
  0.000313 seconds (208 allocations: 24.938 KiB)
init: new system, same D, IIP
  3.786700 seconds (2.52 M allocations: 138.093 MiB, 1.59% gc time)
init: new system, different D, IIP
 57.621791 seconds (91.65 M allocations: 4.276 GiB, 5.41% gc time)
```

Disabling constant propagation:
```
first ever compile
 15.096547 seconds (23.48 M allocations: 1.191 GiB, 3.76% gc time)
re init: same system
  0.000727 seconds (814 allocations: 43.438 KiB)
init: new system, same D, IIP
  2.427433 seconds (2.48 M allocations: 122.034 MiB, 3.09% gc time)
init: new system, different D, IIP
  3.606424 seconds (3.82 M allocations: 191.862 MiB, 2.78% gc time)
```

So it seems fair to say this is hitting a pathological case in constant propagation.

**Comment by JeffBezanson** [comment]
One thing I found is that we spend a lot of time trying to constant propagate calls like

```
  a1=T(parse(BigFloat,"0.07879572252168641926390768"))
```

where there are many different string literals. We need to avoid this in the compiler, but in the meantime it will work better to use `big"0.0"` instead, which became possible to precompile fairly recently.

**Comment by oscardssmith** [comment]
Is the problem that these are inherently slower or just that there are lots of them? How does post compile time performance compare?

**Comment by JeffBezanson** [comment]
Calling `parse` does the parsing at runtime, while the `big""` macro does the parsing at load time. In that sense `parse` is slower, but the big slowdown in this issue is the compiler's fault.
