### ISSUE TITLE
clearer parse errors for invalid characters

### ISSUE THREAD

**Issue by ckoe-bccms** [JuliaLang/julia#28339]
Hello,

I would like to file an issue about the current (0.7.0-beta2.0, Linux) error reporting with UTF characters. Copy and Pasting the following numeric value from a pdf (https://arxiv.org/pdf/cond-mat/0110585) via the X11 clipboard into julia or reading the pasted numerical value from a file gives an error:
```
julia> -0.6626458266981849E−01
ERROR: syntax: invalid character "−"
```

Reading from a file this becomes
```
julia> using ode_symplektisch
ERROR: LoadError: syntax: invalid character "−"
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1034
 [3] macro expansion at ./logging.jl:312 [inlined]
 [4] _require(::Base.PkgId) at ./loading.jl:929
 [5] require(::Base.PkgId) at ./loading.jl:838
 [6] require(::Module, ::Symbol) at ./loading.jl:833
in expression starting at /home/ckoe/src/cp/ODE_Integratoren/ode_symplektisch.jl:198
```

I see two issues with this error message:
1. It does not indicate which "minus" (hint: it is the second one in the exponent)
2. It could contain the hint that an UTF character is involved, eventually even which actual character code

Considering the fact that julia explicitely allows a lot of UTF characters in normal source makes this error message even more unsatisfying. Note: I do not at all propose that the parser should accept this UTF character as a valid "minus"  ! But it would be very helpfull if the error message could at least indicate the actual character (position on input line).

Best Regards

**Comment by stevengj** [comment]
See also #26193.

**Comment by ckoe-bccms** [comment]
Hello,

> I'm not exactly certain what a better error message would look like. Maybe

in my opinion it would be sufficient to give the number of the column on the line, I assume most editors display the cursor column. So it would be easier to figure out which character it is. Something like
`ERROR: syntax: invalid character "−" in: -0.6626458266981849E−01 column 21`
or
`in expression starting at /home/ckoe/src/cp/ODE_Integratoren/ode_symplektisch.jl:198 column 23`
Generally, it might be useful to give a column with other error messages, too.

Also, indicating that it is from the viewpoint of the parser an UTF  and not some other formatting issue (caused by some typo earlier in a source file, we all know those) would be  helpful when reading from a file obviously.

Concerning 26193: I have no opinion on that.

Best Regards

**Comment by stevengj** [comment]
>  it would be sufficient to give the number of the column on the line

That also depends on charwidth matching the editors charwidths.  (Some Unicode characters take up 0 columns, and some take up 2 columns, but there isn't universal agreement on which is which — see #3721.)

But, it will match for most text, and I suppose we could say "near column 21" for the rare cases where the charwidths don't agree.

**Comment by StefanKarpinski** [comment]
We could just approximate column number with character number. After all, most people code in fixed-width fonts and for a lot of code this approximation will be correct. It seem better than not providing any information for fear of doing so imperfectly.

**Comment by stevengj** [comment]
summing the charwidths is a better approximation, and is easy to compute

**Comment by vtjnash** [comment]
c.f. https://github.com/JuliaLang/julia/pull/9579, which also added support for the necessary column number tracking in the parser

**Comment by stevengj** [comment]
#9579 counts code units, which is even cruder than counting characters… I wonder why the count wasn't incremented in `ios_getutf8` instead of `ios_getc`?

**Comment by ckoe-bccms** [comment]
Thank you !
