### ISSUE TITLE
REPL Correction

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/julia#28347]
There's a useful terminal utility on macOS called `fu*k`, which tries to contextually fix typos (and is fairly effective).

I wonder if something like this is possible for Julia. For example, if we detect (say) an unclosed parantheses sequence, or a misspelling of a common command, typing in something like `fixit` will pre-load an ordered set of guesses.

**Comment by affans** [comment]
This is similar to Matlab where the error for wrong command error will return something like `did you mean abs()`

**Comment by arnavs** [comment]
I think the use cases are a bit different, though. Because REPL help mode is to let people find functions/objects, whereas REPL correction would be to help people run code.

**Comment by arnavs** [comment]
@viralBShah Thanks, will do.
