### ISSUE TITLE
Missing method for argmin with generators

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#28349]
In Julia v0.6, I could do:

```julia
indmin(i for i=1:10000)
```

In Julia v0.7, this doesn't work:

```julia
argmin(i for i=1:10000)
```

Can you please add a lazy version again?

**Comment by JeffBezanson** [comment]
See #27612 and #27613.

**Comment by juliohm** [comment]
Thank you, so it is already in your radar, I will close this one.
