### ISSUE TITLE
@spawn Documentation is incorrect - Parallel Computing

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaLang/julia#28350]
This applies to both Julia v0.6 and v0.7, and the documentation for both.

In the first section on 'Parallel Computing', the final example is the following:

```
julia> r = @spawn rand(2,2)
Future(2, 1, 4, Nullable{Any}())

julia> s = @spawn 1 .+ fetch(r)
Future(3, 1, 5, Nullable{Any}())

julia> fetch(s)
2×2 Array{Float64,2}:
 1.38854  1.9098
 1.20939  1.57158
```
Below this example, it says:

> In this case, @spawn is smart enough to perform the computation on the process that owns r, so the fetch() will be a no-op (no work is done).

Apologies if I'm mistaken here but - as far as I understand - the addition in the second line has actually taken place in process 3, so that the call to fetch is **not** a no-op. 

Unfortunately I don't think I understand parallel Julia well enough to clarify this part of the docs so I haven't submitted a PR. Also see related discussion on Julia Discourse:
https://discourse.julialang.org/t/understanding-pid-and-rrid-in-future-objects-related-to-spawn-and-spawnat-in-documentation/9462

**Comment by ViralBShah** [comment]
I believe subsequent updates have clarified the documentation here. Please reopen if necessary.
