### ISSUE TITLE
cholesky factors and transposed sparse matrices in julia 0.7.0

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaLang/julia#28363]
In Julia 0.7.0-beta2.0 and 0.7.0-beta2.188, the following code

```julia
using SparseArrays
using LinearAlgebra
F = cholesky(Symmetric(sparse(1:4,1:4,[1,1,1,1])))
F \ sparse(1:4,1:4,[1,1,1,1])'
```

produces this error:

```
ERROR: 
MethodError: no method matching ldiv!(::SuiteSparse.CHOLMOD.Factor{Float64}, ::SparseMatrixCSC{Float64,Int64})
```
while `F \ copy(sparse(1:4,1:4,[1,1,1,1])')` works.

The equivalent code also fails on 0.6.4 but it would be nice if Julia 0.7.0 accepts it. 

It is related to the comment here: https://github.com/JuliaLang/julia/issues/27860#issuecomment-402284473

**Comment by Alexander-Barth** [comment]
The issue is also present in julia 1.0.0.

**Comment by ViralBShah** [comment]
Should be straightforward to fix. Bumping this so it gets noticed.
