### ISSUE TITLE
Race condition in precompilation for shared file-system and multiple workers

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#28412]
Originally described and encounter in https://github.com/JuliaLang/julia/issues/28406#issuecomment-409975302, we probably want a better fix, but it is not immediately clear what that should be.

My current recommendation is that users use `] precompile` before spinning up workers until this is fixed.

**Comment by JeffBezanson** [comment]
dup of #17320?

**Comment by vchuravy** [comment]
Well I will be damned.
