### ISSUE TITLE
inference hang in DiffEqBiological

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#28417]
Pulling https://github.com/JuliaLang/julia/issues/28356#issuecomment-409297092 out to a new issue since this second example doesn't seem to be exactly the same as the previous fix. In this case, a code which compiles a function call in the global scope is okay, but when the same function call is compiled in a local scope then compilation hangs. Using a recent nightly with the fix for #28356

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-rc1.18 (2018-08-02 13:13 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 34b0dd097f (0 days old master)
|__/                   |  x86_64-w64-mingw32
```

I run the code:

```julia
using DiffEqBiological, StochasticDiffEq

model = @reaction_network rn begin
    (d,1000), X ↔ 0
end d

i = 1.0
prob = SDEProblem(model,[1000.0+i],(0.,200.),[i])
sol = solve(prob, EM(), dt = 0.01)

for i in [1., 2., 3., 4., 5.]
    prob = SDEProblem(model,[1000.0+i],(0.,200.),[i])
    sol = solve(prob, EM(), dt = 0.01)
end
```

and it's just fine. However, when I do not allow it to compile the `solve` call in the global scope first, it hangs at compilation.

```julia
using DiffEqBiological, StochasticDiffEq

model = @reaction_network rn begin
    (d,1000), X ↔ 0
end d

for i in [1., 2., 3., 4., 5.]
    prob = SDEProblem(model,[1000.0+i],(0.,200.),[i])
    sol = solve(prob, EM(), dt = 0.01)
end
```

Given my working knowledge of the Julia compiler, both `solve` calls are compiling the same thing so 🤷‍♂️ I don't get it. 

Note that the example from https://github.com/JuliaLang/julia/issues/28356 displayed some of this behavior too, since the original example only ran into the issue when the `function integrator(...)` was involved. If you refactor it so that way it does the same commands in the REPL, then even before the #28356 fix there was no issue. Given @JeffBezanson 's comments about how the hang was due to inference generating unions, my guess is that somehow a difference in inference could be involved, but I'm of course not the expert on this so that could be totally wrong.

**Comment by JeffBezanson** [comment]
https://github.com/symengine/SymEngine.jl/issues/132 blocks me from reproducing this. Can you provide one of (1) a fix or workaround for that, (2) a version of this that happens without needing SymEngine, or (3) interrupt the hanging process in gdb and get a stack trace?

**Comment by ChrisRackauckas** [comment]
I setup the `nosym` branch https://github.com/JuliaDiffEq/DiffEqBiological.jl/tree/nosym without SymEngine and confirm it still hangs on this branch.

**Comment by JeffBezanson** [comment]
Thanks!

**Comment by JeffBezanson** [comment]
Well, this is bad. Inference seems to be stuck in a cycle on this definition in DiffEqBiological/problem.jl:
```
DiffEqBase.SDEProblem(rn::DiffEqBase.AbstractReactionNetwork, u0::Union{AbstractArray, Number}, args...; kwargs...) =
    SDEProblem(rn, rn.g, u0, args...;noise_rate_prototype=rn.p_matrix, kwargs...)
```

It thinks this call is recursive but doesn't limit it because nothing is growing much. So far it looks like a case of pathological tree recursion. I see combinations of at least these types (listed for each of 8 argument slots):
```
 1: SDEProblem#36
 2: Pairs or Any
 3: Type
 4: AbstractReactionNetwork
 5: Union{Number, AbstractArray}, Vector{Float64}
 6: AbstractArray, Number, Vector{Float64}
 7: Number, Vector{Float64}, Tuple{Float64, Float64}, Vararg{AbstractArray}, AbstractArray, Vararg{Any}
 8: Vector{Float64}, Vararg{Any}, nothing
```

However, I'm not sure whether the problem is a large number of combinations, or if we are doing duplicate work.

A workaround is to annotate the type of the rn.g argument as `rn.g::Function` --- that makes the problem go away as we now know the definition isn't recursive.

**Comment by vtjnash** [comment]
Works fine now for me
