### ISSUE TITLE
Add unique!(f, itr)

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#28415]
We have a `unique(f, itr)`:
```
  unique(f, itr)

  Returns an array containing one value from itr for each unique value produced by f applied to
  elements of itr.
```
but no corresponding in-place version, would be nice to have. See https://github.com/JuliaLang/julia/pull/20619

**Comment by bvsravikiran** [comment]
Can I work on this issue?

**Comment by fredrikekre** [comment]
Yes.

**Comment by deepaknalore** [comment]
@bvsravikiran If you are not working on it. I would like to pick it up

**Comment by bvsravikiran** [comment]
Sure. Go ahead.

**Comment by shaktee** [comment]
Yikes. I was unaware that someone was working on this. I had already done this because I needed it. So, I created a pull request for it #28737

**Comment by shaktee** [comment]
If it is not the best implementation, please feel free to discard the pull request. (But, I would appreciate a commentary on the things that need improvement.)

**Comment by raghav9-97** [comment]
If I am understanding it correctly, the return values of unique!(f, itr) does not really care about original order of occurrence.As it is also clear from the documentation of ```unique (f itr) :```
```
unique(f, itr)

Returns an array containing one value from itr for each unique value produced by f applied to elements of itr.
```
Ex- ``` A = [1,-1,3,-3,5,-5]```

The unique!(f, itr) can generate -1,-3,-5 (if sort!(A) and _groupedunique!() like function applied) as well as 1,3,5 if order of occurence is necessary.

**Comment by StefanKarpinski** [comment]
I think we generally want to leave the elements in their original order. There's no reason not to do so.
