### ISSUE TITLE
Sending code to the REPL via tmux causes new indentations and is slower

### ISSUE THREAD

**Issue by Evizero** [JuliaLang/julia#28423]
I realize this is might be a very workflow specific issue, but here it goes

I use tmux with vim and slimux to develop julia code. This means I can use the visual mode in vim to select multiple lines of code and then send it to an open REPL in some other tmux pane.

On 0.6 this worked very well and fast and all the indentation was preserved:

```
julia> function foo()
           println("a")
           println("a")
           println("a")
           println("a")
           println("a")
           println("a")
       end
foo (generic function with 1 method)
```

on 0.7 however things it behaves very differently and quite a bit slower as well since it seems to be processsing the input in some additional way.

```
julia> function foo()
           println("a")
               println("a")
                   println("a")
                       println("a")
                           println("a")
                               println("a")
                               end
foo (generic function with 1 method)
```

Is this expected behaviour and if so is there any known workaround?

EDIT: this is in ubuntu 16.04

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/25186

**Comment by jbrea** [comment]
@Evizero, did you figure out a workaround?
I face the same issue  with vim, slimux or vim-slime & tmux on Arch Linux.
Manual copy-pasting works for me.

**Comment by Evizero** [comment]
no

**Comment by rfourquet** [comment]
A workaround for me in tmux is to call `Base.active_repl.options.auto_indent = false` before pasting. So I usually copy-paste with "select/middle-mouse-button" (the X11 way) in the terminal to avoid this problem.

**Comment by jbrea** [comment]
Awesome, thanks. This works for me.

**Comment by StefanKarpinski** [comment]
Closing as dup.
