### ISSUE TITLE
Wrong docstring: selectperm/sortperm

### ISSUE THREAD

**Issue by Wikunia** [JuliaLang/julia#28426]
I think the behavior of `selectperm` does not fully match the documentation:
Link to documentation:
https://github.com/JuliaLang/julia/blob/release-0.6/base/docs/helpdb/Base.jl#L1231-L1243

Full text:

> Return a partial permutation of the vector `v`, according to the order specified by
> `by`, `lt` and `rev`, so that `v[output]` returns the first `k` (or range of adjacent values
> if `k` is a range) values of a fully sorted version of `v`. If `k` is a single index
> (Integer), an array of the first `k` indices is returned; if `k` is a range, an array of
> those indices is returned. Note that the handling of integer values for `k` is different
> from [`select`](@ref) in that it returns a vector of `k` elements instead of just the `k` th
> element. Also note that this is equivalent to, but more efficient than, calling
> `sortperm(...)[k]`.

If I have the array `a = [4,3,2,1]` and use `selectperm(a,2)` I can read this part:

> If `k` is a single index (Integer), an array of the first `k` indices is returned;

then the expected behavior is: to get `[4,3]` as `a[[4,3]]` is `[1,2]` but regarding this:

>  Also note that this is equivalent to, but more efficient than, calling
> `sortperm(...)[k]`.

I would suspect to get only a single index (`3`) which is what `selectperm` actually does.

Using it without documentation I assumed to get `[4,3]` but I'm also happy to use `selectperm(a,1:2)`. Anyway the documentation seems to be wrong.

Happy to change the docstring if the function works as it should. ;)

Cross-posted: 
https://discourse.julialang.org/t/selectperm-bug-or-wrong-documentation/12852

**Comment by nalimilan** [comment]
A PR to fix this would certainly be appreciated.

**Comment by Wikunia** [comment]
Alright. I'll do it tomorrow.
Btw I think this one is wrong as well:
https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/sort.jl#L573-L603

In the list of parameters it says: Default unstable and in the description it says default is a stable merge sort. 
I didn't have a look in the code but I assume that the default is a stable merge sort.

**Comment by Keno** [comment]
This function got renamed to `partialsortperm`, but I believe the docstring is correct now.
