### ISSUE TITLE
qr error for matrices with 0 columns

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#28447]
Function `qr` in 0.6 works fine for matrices with 0 columns, but not in 0.7.0-beta2:

```
julia> F = qr(zeros(4,0))
WARNING: Base.qr is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Main
LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
4×4 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
R factor:
Error showing value of type LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}:
ERROR: ArgumentError: the requested diagonal, 0, must be at least 1 and at most 1 in an 0-by-0 matrix
```

**Comment by StephenVavasis** [comment]
It's true that not displaying the answer prevents the problem from occurring immediately, but the it still occurs later:
```
julia> F = qr(zeros(4,0));

julia> R = Matrix(F.R)
ERROR: ArgumentError: the requested diagonal, 0, must be at least 1 and at most 1 in an 0-by-0 matrix
Stacktrace:
 [1] triu!(::Array{Float64,2}, ::Int64) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\LinearAlgebra\src\dense.jl:175
 [2] triu! at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\LinearAlgebra\src\generic.jl:237 [inlined]
 [3] getproperty(::LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}, ::Symbol) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\LinearAlgebra\src\qr.jl:419
 [4] top-level scope at none:0
```

**Comment by andreasnoack** [comment]
```julia
julia> triu!(randn(0,0));
ERROR: ArgumentError: the requested diagonal, 0, must be at least 1 and at most 1 in an 0-by-0 matrix
Stacktrace:
 [1] triu!(::Array{Float64,2}, ::Int64) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/dense.jl:175
 [2] triu!(::Array{Float64,2}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/generic.jl:237
 [3] top-level scope at none:0
```
We added some checks to the `triu/l` functions to catch potential user errors but so far these checks have mainly been causing problems. I think we should seriously consider to revert the change that introduced the checks.

**Comment by StefanKarpinski** [comment]
100%. We need to either do the looser bounds or delete the checks altogether.

**Comment by chenxlieee** [comment]
julia> a=[1 2 3; 4 5 6; 7 8 9]
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

julia> using LinearAlgebra: qr

julia> q,r=qr(a)
LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.123091   0.904534   0.408248
 -0.492366   0.301511  -0.816497
 -0.86164   -0.301511   0.408248
R factor:
3×3 Array{Float64,2}:
 -8.12404  -9.60114   -11.0782
  0.0       0.904534    1.80907
  0.0       0.0        -8.88178e-16

julia> q
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.123091   0.904534   0.408248
 -0.492366   0.301511  -0.816497
 -0.86164   -0.301511   0.408248

julia> r
3×3 Array{Float64,2}:
 -8.12404  -9.60114   -11.0782
  0.0       0.904534    1.80907
  0.0       0.0        -8.88178e-16

It seems the q and r matrices are not compact.

**Comment by StephenVavasis** [comment]
With respect to the previous comment, I don't see anything wrong with the output from `qr` in your posting.  Could you say more precisely what is the issue you are raising?

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/28480

**Comment by StephenVavasis** [comment]
With respect to the comment from @chenxlieee , plain QR is not suitable for use as a rank estimator.  For rank estimation, use either pivoted QR or, for greatest robustness, SVD.
