### ISSUE TITLE
IO read performance

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#28481]
I opened https://github.com/JuliaCI/BaseBenchmarks.jl/pull/223 to track performance of reading a `Float64` from an `IOBuffer`. This currently allocates.

I thought that maybe this would be resolved in 0.7 (elimination of the allocation of the `Ref` [here](https://github.com/JuliaLang/julia/blob/master/base/io.jl#L598)), but I guess that's being explicitly prevented by the `@noinline` [here](https://github.com/JuliaLang/julia/blob/a2149f890fb9ba8846e2731cd193774597bd4916/base/io.jl#L592).

BufferedStreams.jl has [this implementation](https://github.com/BioJulia/BufferedStreams.jl/blob/15accc20738f4f8348fcb307d4889277572fc7e8/src/bufferedinputstream.jl#L194-L208), which doesn't allocate. Is something like this acceptable for Base as well? I don't *think* there are any issues with GC roots or alignment in this implementation, are there?

**Comment by tkoolen** [comment]
Also, should the `@noinline` (comment: `mark noinline to ensure ref is gc-rooted somewhere (by the caller)`) just be replace with a `GC.@preserve` now?

**Comment by JeffBezanson** [comment]
Yes, That noinline should be replaced with a gc-preserve now.

**Comment by vtjnash** [comment]
No, that’s there to guarantee the allocation. We can’t fix that (or enable general stack allocation) due to copy-stacks.

**Comment by JeffBezanson** [comment]
Oh, right. Well that will be fixed pretty soon too.

**Comment by tkoolen** [comment]
Is the BufferedStreams implementation OK though? I understand this should all get better soon, but I kind of need a non-allocating solution right now.

**Comment by damiendr** [comment]
@tkoolen came across the same problem, your package works well for me so far. It would be nice to have this level of performance by default.

**Comment by tkoolen** [comment]
FYI, I just redid the performance comparisons in the [FastIOBuffers.jl](https://github.com/tkoolen/FastIOBuffers.jl) readme, and while `IOBuffer` has gotten a lot better, it's still not quite as good. Performance on latest nightly is about the same as on 1.1.0. Specifically:
* `FastWriteBuffer` is about 44% faster than `IOBuffer` at writing `Float64`s and doesn't allocate, while `IOBuffer` still allocates 16 bytes.
* `FastReadBuffer` is about 150% faster than `IOBuffer` at reading `Float64`s (neither allocate).

**Comment by tkoolen** [comment]
It seems that the `read` performance difference can be mostly attributed to this check:

https://github.com/JuliaLang/julia/blob/5741c7f53c5ea443bbd73cc5157b83de415c6d1b/base/iobuffer.jl#L171

**Comment by KristofferC** [comment]
If that is the case, a PR to manually outline this would be welcome since it is a performance sensitive function.

**Comment by tkoolen** [comment]
See https://github.com/JuliaLang/julia/issues/28481#issuecomment-485948983.
