### ISSUE TITLE
Bidiagonal times Triangular matrix multiplication fails

### ISSUE THREAD

**Issue by mcognetta** [JuliaLang/julia#28493]
Multiplying a bidiagonal matrix times a triangular matrix fails as there is no matching rmul method.

MWE:
```
julia> A = Bidiagonal(rand(10, 10), :U)
julia> B = UpperTriangular(rand(10,10))
julia> B*A #this works
julia> A*B
ERROR: MethodError: no method matching rmul!(::SparseMatrixCSC{Float64,Int64}, ::UpperTriangular{Float64,Array{Float64,2}})
```

------------------------------------------------------------------------------

Tests for this should also be added to LinearAlgebra/test/bidiag,jl around line 281. In that section, some sets of matrix types are evaluated but not in all orders so this method error doesn't show up.

I have two WIP PRs (#28343 #28345) to specialize the output types of these sorts of matrix multiplications but this should be fixed first. There are a few small bugs that pop up when doing special combinations of matrices and types (especially triangular and bigint/bigfloats).

**Comment by ArunSanganal** [comment]
A*B works as well. This issue can be closed I guess.
