### ISSUE TITLE
Allow operator suffixes to the postfix apostrophe

### ISSUE THREAD

**Issue by perrutquist** [JuliaLang/julia#28494]
Since #22089 it is possible to add suffixes to existing binary operators in order to create entirely new ones.

If it were possible to add suffixes to the postfix `'` operator as well, then that would make it possible for the user to create an arbitrary number of new postfix operators. For example, it would make it possible to make `A'ᵀ` the transpose of `A`.

See #21037 for the beginning of this discussion. Here's a brief summary as best as I've understood: The original proposal was to map `x'` to the function call `'(x)`, and then allow suffixes on that function name, but this is not possible.  The first character of an identifier cannot be `'`, because `'` is already used to introduce character literals. On the other hand, using a function name like `apostrophe` can lead to problems similar to #25947. That problem can be avoided by mapping to `Base.apostrophe` instead of using the local scope.

**Comment by perrutquist** [comment]
I believe that it would be possible to shoehorn in a `'` literal by allowing it 
in contexts where a character literal is not allowed. The most important 
use cases: `function '`, `import '`, and `export '` would work, because a 
character literal cannot follow those keywords.

In other contexts, one would need something convoluted like `eval(Symbol("'"))`.
For example, the `Base` module might have `const apostrophe = eval(Symbol("'"))`,
so that `Base.apostrophe(::Foo) = bar`, would be equivalent to
`import Base: '; function '(::Foo); bar; end'`. 
But these would be rare cases, that normal users need not worry about.

**Comment by simeonschaub** [comment]
Should be fixed by #37247

**Comment by stevengj** [comment]
Closed by #37247
