### ISSUE TITLE
`cluster_cookie()` issues `UndefRefError` on `v0.7-rc2`

### ISSUE THREAD

**Issue by raminammour** [JuliaLang/julia#28499]
Just noticed this:

```
julia> cluster_cookie()
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getproperty at ./sysimg.jl:18 [inlined]
 [2] cluster_cookie() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Distributed/src/cluster.jl:647
 [3] top-level scope at none:0

julia> versioninfo()
Julia Version 0.7.0-rc2.0
Commit 78540cba4c (2018-08-02 19:14 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)
```
Cheers!

**Comment by JeffBezanson** [comment]
Out of curiosity, what is the reason for calling this directly? It can still be fixed of course.

**Comment by raminammour** [comment]
It is called by `ClusterManagers` to generate the random cookie. Incidentally `cluster_cookie(cookie)` still works, I thought I can use that as a workaround. 

However, something  between `beta2` and `rc2` broke `ClusterManagers` even if I run `cluster_cookie("whatever")` before (but that is a separate issue to take with that package that has not updated to `0.7` yet...).

Thanks for the help!

**Comment by raminammour** [comment]
Ok some advance, calling `Distributed.init_multi()` manually before `using ClusterManagers` fixes `ClusterManagers`. So I guess it is deeper than just `cluster_cookie` and prob this is prob related too https://github.com/JuliaLang/julia/pull/28140.

Cheers!

**Comment by JeffBezanson** [comment]
Yes, that is the cause.
