### ISSUE TITLE
Matrix multiplication - efficient self adjoint?

### ISSUE THREAD

**Issue by jeffwong-nflx** [JuliaLang/julia#28501]
I am wondering if Julia uses an efficient implementation to multiply a matrix transpose with itself?

```
A = randn(10000, 100)
A'A

A = sprandn(10000, 100,  .1)
A'A
```

For example in R this operation has a special function `crossprod(A)` because the result is known to be symmetric, and only half of the multiplications need to be done.

**Comment by andreasnoack** [comment]
Please ask questions on discourse.julialang.org.
