### ISSUE TITLE
README still claims Julia uses LLVM 3.9

### ISSUE THREAD

**Issue by non-Jedi** [JuliaLang/julia#28529]
Per comment on discourse (https://discourse.julialang.org/t/julia-v1-0-rc1-is-now-available/13008/6), it seems Julia now uses LLVM 6.0 however the README has info about 3.9 all over it. Should be a relatively straightforward PR to fix that up, but I don't have time myself at the moment, so I thought it ought to be documented as an issue.

**Comment by NicolasCARPi** [comment]
Created a PR [here](https://github.com/JuliaLang/julia/pull/28530).
