### ISSUE TITLE
Scoping rules

### ISSUE THREAD

**Issue by sherrinm** [JuliaLang/julia#28523]

**Comment by sherrinm** [comment]
Julia v1.0 seems to have problems with scope in the REPL within a for loop

viz:  A quick evaluation of PI ( -- the code works fine in 0.6.4)

julia> k = 0;
julia> n = 1000_000;
julia> @time for i in 1:n
         if (rand()^2 + rand()^2) < 1.0 
           k += 1       
         end
       end
ERROR: UndefVarError: k not defined
Stacktrace:
 [1] macro expansion at ./REPL[3]:3 [inlined]
 [2] top-level scope at ./util.jl:156 [inlined]
 [3] top-level scope at ./none:0

Wrap this in a let .. end block and it is OK

julia> let
       k = 0; 
       n = 1000_000;
       @time for i in 1:n
         if (rand()^2 + rand()^2) < 1.0 
           k += 1       
         end
       end
       p = 4*k/n
       end
  0.010449 seconds
3.13978

**Comment by ararslan** [comment]
Closing as the current behavior is intended.
