### ISSUE TITLE
segmentation fault on 1.0 (and 1.1 and 0.7)

### ISSUE THREAD

**Issue by kafisatz** [JuliaLang/julia#28536]
My tests fail due to a segfault.

I am not sure if I am doing 'something unsafe', but I am pretty sure the tests were almost identical on 0.7beta where things went fine.

https://discourse.julialang.org/t/segmentation-fault-on-0-7/13065/2 

any ideas?

the error occurs on 0.7, 1.0 and 1.1 too
https://travis-ci.org/kafisatz/DecisionTrees.jl/builds/415879916

**Comment by mauro3** [comment]
Can you provide a minimal working example? (Ideally without depending on your package)  Thanks!

The link to the segfault: https://travis-ci.org/kafisatz/DecisionTrees.jl/jobs/412500251#L974

**Comment by kafisatz** [comment]
I cannot, as I am not sure how I would approach that.
It seems to me it is line 43 of this function  https://github.com/kafisatz/DecisionTrees.jl/blob/master/test/smoketests.jl#L43 
that is causing the issue though. 
I.e. when the function dtm is called, the segfault occurs (prinln commands implied that at least)

**Comment by kafisatz** [comment]
The more visibility this issue gets (even if yours may not be identical), the better ->please tag along.  

Thanks for the MWE. Interesting observations...

I do not know anything about segfaults, but I note that Keno recently fixed an issue related to garbage collection. I am not sure if this is related though.

**Comment by JeffBezanson** [comment]
With LLVM assertions enabled, DecisionTrees tests print:
```
Use of %693 does not have a corresponding definition on every path:
896r %1029:vr128 = PSHUFDri %693, 78; VR128:%1029,%693
LLVM ERROR: Use not jointly dominated by defs.
```

**Comment by JeffBezanson** [comment]
I get a very similar error from the case in https://github.com/JuliaLang/julia/issues/28536#issuecomment-412181449 .

**Comment by vtjnash** [comment]
That output form is from LLVM's MIR passes. Since the IR domination was valid according to the IR Validation passes, it seems likely this is an upstream bug, so marking as such.

**Comment by kafisatz** [comment]
I was able to fix the segfault in my code (see this commit https://github.com/kafisatz/DecisionTrees.jl/commit/6e35c57fd3516206b391a632d27726d697d31e7c ) 
I had a `begin end` block which I have now removed (possibly it led to some scoping issues...?)

**Comment by JeffBezanson** [comment]
Since it's probably an LLVM bug, that change is not necessarily connected in a meaningful way. Glad you have a workaround though.

**Comment by Keno** [comment]
I do actually see a verifier error here, so this may be on us yet:
```
Instruction does not dominate all uses!
  %4118 = phi <2 x %jl_value_t addrspace(10)*> [ %1744, %L2956 ], [ %3341, %6621 ]
  %96 = extractelement <2 x %jl_value_t addrspace(10)*> %4118, i32 0
Instruction does not dominate all uses!
  %4118 = phi <2 x %jl_value_t addrspace(10)*> [ %1744, %L2956 ], [ %3341, %6621 ]
  %98 = extractelement <2 x %jl_value_t addrspace(10)*> %4118, i32 1
```
