### ISSUE TITLE
Should make it explicit in the FAQ that you target iOS and Android as well as Win/Lin/Mac

### ISSUE THREAD

**Issue by paul-hammant** [JuliaLang/julia#28545]
I know this can be inferred from the LLVM capability, and the downloads page talking about architectures, but it is worth nailing explicitly in the FAQ IMO.

**Comment by ararslan** [comment]
While Julia may happen to run on the necessary architectures for iOS and Android, at this time we do not actively target those platforms.

**Comment by paul-hammant** [comment]
FAQ should be updated to say "Julia may happen to run on the necessary architectures for iOS and Android, at this time we do not actively target iOS and Android platforms." 

Ref: https://docs.julialang.org/en/v1.0.0/search/?q=Android

Closed too hastily?

**Comment by StefanKarpinski** [comment]
Want to make a PR? It's a bit weird to mention some platforms that we don't target, since there are many platforms that we don't target—Julia has not yet been ported to PDP-11, for example. Of course, there's probably more interest in iOS and Android, but I can't say it's a FAQ just yet. If you want to add that to the FAQ, we'd be happy to include it.

**Comment by paul-hammant** [comment]
Here's a honest and **appropriate** FAQ question "Can I deploy Julia applications to iOS or Android". Answer "Not officially. We may support this in the future".

From https://www.rust-lang.org/en-US/faq.html ->

    Can Rust be used for Android/iOS programming?

    Yes it can! There are already examples of using Rust for both 
    Android and iOS. It does require a bit of work to set up, but 
    Rust functions fine on both platforms.

Dec PDP-11 ... *chortle*.

**Comment by StefanKarpinski** [comment]
Please port Julia to iOS & Android so that it can be used in Game development!

**Comment by Freelane-team** [comment]
+1 using Julia on iOS/Android, you get even more traction and contributors..

**Comment by StirlingNewberry** [comment]
++

**Comment by StefanKarpinski** [comment]
Please stop “me too”img this issue. If you want Julia to run on iOS or Android, then either port it or pay someone to port it. Anything else is entirely unhelpful.
