### ISSUE TITLE
Deprecation warning for `RowVector` to `Adjoint` is missing

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/julia#28540]
As discussed on [discourse](https://discourse.julialang.org/t/julia-v1-0-rc1-is-now-available/13008/29?u=chakravala), it turns out that the deprecation warning is missing.

For example, in 0.7
```Julia
julia> RowVector
WARNING: Base.RowVector is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Main
LinearAlgebra.RowVector
```
while in 1.0
```Julia
julia> using LinearAlgebra

julia> RowVector
ERROR: UndefVarError: RowVector not defined

julia> LinearAlgebra.RowVector
ERROR: UndefVarError: RowVector not defined
```
Apparently, `Adjoint` is now used.

**Comment by StefanKarpinski** [comment]
This appears to be behaving as expected: there are no deprecation warnings on 1.0, that's what 0.7 is for.

**Comment by chakravala** [comment]
Okay, I now realized what my issue specifically was. I think I had confusion because I updated my code a few months ago already before the `Adjoint` change was made. Therefore, I may not have properly received the warning about it. Not sure if that was the exact reason, either way, this can probably be closed.
