### ISSUE TITLE
Pkg.xxx is not working

### ISSUE THREAD

**Issue by patdub** [JuliaLang/julia#28547]
On Julia 1.0.0 I cannot install external package using Pkg.add. The error message in the console is 

ERROR: UndefVarError: Pkg not defined

I have the same error message for all commands starting with Pkg.xxx.

The used solution is to enter in "Pkg REPL mode" using ] but I have after lot of error for all packages I try to install.

Thanks for your help.

**Comment by KristofferC** [comment]
You need to do `import Pkg` first. Many packages are not updated yet so the fact that they fail is not unexpected.
