### ISSUE TITLE
feature request: repl>exit

### ISSUE THREAD

**Issue by amanica** [JuliaLang/julia#28551]
Please let typing `exit<ENTER>` in the repl, actually exit the repl, like most other shells I've used do.

julia> exit

or if you really don't want that, please at least tell the user how to exit the shell eg. exit() or CTRL+D

thanks

**Comment by affans** [comment]
See `quit()`

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/20579

> please at least tell the user how to exit the shell eg. exit() or CTRL+D

Yea, both of those work, where do you suggest we should tell users about this?

**Comment by amanica** [comment]
@fredrikekre Thanks for pointing to that, I didn't find it when I searched, probably because I only searched open issues. Although that would solve the issue, it was very broad and I can understand why that was rejected. Perhaps an exception can be made for exit? i.e. don't allow calling all functions without brackets.

**Comment by StefanKarpinski** [comment]
What about this:
```jl
julia> function Base.display(::typeof(exit))
           println("Use `exit()` or ctrl-D to exit the interactive prompt.")
           invoke(display, Tuple{Any}, exit)
       end

julia> exit
Use `exit()` or ctrl-D to exit the interactive prompt.
exit (generic function with 2 methods)
```

**Comment by amanica** [comment]
That would be awesome!
