### ISSUE TITLE
Error buiding Conda (installing Pkg IJulia) with 1.0.0

### ISSUE THREAD

**Issue by patdub** [JuliaLang/julia#28550]
I do not succeed installing IJulia on last 1.0.0 version.

Installation failed when building Conda. I get the following error message :
 
Building Conda ──→ `C:\Users\Patrick\.julia\packages\Conda\a196m\deps\build.log`
┌ Error: Error building `Conda`:
│ ERROR: LoadError: ArgumentError: isdefined: too few arguments (expected 2)

Thanks for your help.

**Comment by KristofferC** [comment]
Not a Julia issue. A PR to Conda that seems to fix this already seems to exist.

**Comment by StefanKarpinski** [comment]
The https://github.com/JuliaPy/Conda.jl Julia package, that is, not conda itself.
