### ISSUE TITLE
Adding a package changes the REPL window title to "Windows PowerShell"

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaLang/julia#28561]
Add any new package using the new package manager in 0.7/1.0. When it logs "Resolving package versions..." to the REPL, the window title changes to "Windows PowerShell". This happens consistently on my 64 bit Windows 10 system. It's not just a cosmetic problem for two reasons:
1. It becomes much harder to see that Julia is running from looking at the taskbar, especially if you use PowerShell for other things.
2. If you have two different versions of Julia running simultaneously, you can no longer tell the two REPL windows apart.

**Comment by kafisatz** [comment]
I tend to open PowerShell first and then start Julia, thus I have not noticed the title change. I wanted to add, that the 'resolving package versions... ' also changes the font (or at least the spacing) see screenshot.

It never really bothered me enough to report it, but I guess it might be related to this topic. 

<img width="418" alt="before_after" src="https://user-images.githubusercontent.com/15026865/43988648-d2234968-9d3a-11e8-8ada-8ab5f8b63f9c.png">

**Comment by KristofferC** [comment]
Closing in favour of https://github.com/JuliaLang/Pkg.jl/issues/641.
