### ISSUE TITLE
Performance of immutable vs mutable unions

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#28567]
In some situations using an array of union of immutable types is slower than using and array of union of mutable types.

In the code below three functions `f`, `g` and `h` do the same operation on array of union of immutables or mutables. Functions `f` and `h` are much slower in union of immutables case. Function `g` behaves as expected.

Here is the example:
```
struct A1
    x::Int
end

struct A2
    x::Int32
end

mutable struct B1
    x::Int
end

mutable struct B2
    x::Int32
end

a = Union{A1,A2}[isodd(i) ? A1(i) : A2(i) for i in 1:10^6]
b = Union{B1,B2}[isodd(i) ? B1(i) : B2(i) for i in 1:10^6]

function f(z)
    s = 0
    for v in z
        s += v.x
    end
    s
end

g(a) = sum(v -> v.x, a)
h(a) = sum(v.x for v in a)
```

And here are benchmark results on Julia 1.0:
```
julia> using BenchmarkTools

julia> @btime f($a)
  4.214 ms (0 allocations: 0 bytes)
500000500000

julia> @btime f($b)
  1.728 ms (0 allocations: 0 bytes)
500000500000

julia> @btime g($a)
  1.578 ms (0 allocations: 0 bytes)
500000500000

julia> @btime g($b)
  1.757 ms (0 allocations: 0 bytes)
500000500000

julia> @btime h($a)
  4.783 ms (1 allocation: 16 bytes)
500000500000

julia> @btime h($b)
  1.782 ms (1 allocation: 16 bytes)
500000500000
```

CC @vchuravy @dfdx - I have added two alternative implementations apart from `f` function we have discussed.

**Comment by dfdx** [comment]
Could you please remind me about that discussion? I feel a bit out of context here.

**Comment by bkamins** [comment]
Sorry - my bad - I have mixed up Github user name. This is a note from a discussion at JuliaCon2018.

**Comment by mofeing** [comment]
This issue seems to no longer exist as of Julia v1.9.3. Now is the other way around and mutable unions take between 15-66% more time.

```
julia> using BenchmarkTools

julia> @btime f($a)
  1.071 ms (0 allocations: 0 bytes)
500000500000

julia> @btime f($b)
  1.232 ms (0 allocations: 0 bytes)
500000500000

julia> @btime g($a)
  845.625 μs (0 allocations: 0 bytes)
500000500000

julia> @btime g($b)
  1.049 ms (0 allocations: 0 bytes)
500000500000

julia> @btime h($a)
  441.792 μs (0 allocations: 0 bytes)
500000500000

julia> @btime h($b)
  733.416 μs (0 allocations: 0 bytes)
500000500000
```
