### ISSUE TITLE
Pkg.status() not working

### ISSUE THREAD

**Issue by KathyGCY** [JuliaLang/julia#28565]
<img width="571" alt="screen shot 2018-08-10 at 10 14 10 am" src="https://user-images.githubusercontent.com/14912791/43962596-2777e316-9c86-11e8-9f11-1b120dacad7d.png">

**Comment by fredrikekre** [comment]
You need to load `Pkg` with `using Pkg` before you use it. In the future, please use http://discourse.julialang.org for questions.
