### ISSUE TITLE
Plots package doesn't precompile in Julia 1.0

### ISSUE THREAD

**Issue by julian43** [JuliaLang/julia#28573]
versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

<img width="598" alt="screen shot 2018-08-10 at 3 38 51 pm" src="https://user-images.githubusercontent.com/23178241/43980396-9daecc48-9cb3-11e8-8452-398874104b51.png">

I received the very same error on a fresh install of Kubuntu 18.04

**Comment by KristofferC** [comment]
I don't think plots is upgraded yet. But this type of issues should be opened at the package repo not the julia repo.

**Comment by pkofod** [comment]
Many packages are getting ready for Julia 1.0 right now. I think it’s a good bet that Plots  will be ready tomorrow during the hackathon at JuliaCon 2018. It’s an unfortunate inconvenience for new users, but we’re all trying to get it done ASAP!

In the future you should direct a question like this towards the issue tracker at Plots.jl or discourse.julialang.org as this is not a problem with the language as such.
