### ISSUE TITLE
excessive inference time (regression v0.7-v1.0)

### ISSUE THREAD

**Issue by visr** [JuliaLang/julia#28575]
I just tried upgrading TiledIteration.jl to 1.0, when I came across something odd.

Look at the 8 minute slowdown of all tests on 1.0 and nightly here:
https://travis-ci.org/JuliaArrays/TiledIteration.jl/builds/414702960

The function `g` below runs very fast on v0.7, but super slow on v1.0, with ever increasing RAM. So slow in fact that I assumed it was stuck, but since Travis passed it seems there is an end.

```julia
outer = CartesianIndices((0:4,))
inner = CartesianIndices(1:3)
f(inner, outer) = ((first(inner) ∈ outer) & (last(inner) ∈ outer))
f(inner, outer)
g(inner, outer) = ((first(inner) ∈ outer) & (last(inner) ∈ outer)) || throw(DimensionMismatch("$inner $outer"))
g(inner, outer)
```

I included `f` to show it doesn't happen there. If in the `DimensionMismatch` I interpolate only `inner` or `outer` it also works fine, but both is a no-go. Also running the content of `g` directly in the REPL works fine.

**Comment by visr** [comment]
Ah it just finished on my Win64:
```julia
julia> @time g(inner, outer)
362.057698 seconds (645.53 M allocations: 35.693 GiB, 7.33% gc time)
true
julia> @time g(inner, outer)
  0.000005 seconds (4 allocations: 160 bytes)
true
```

Second time is fast.

For context, here are the relevant lines from the package:
https://github.com/JuliaArrays/TiledIteration.jl/blob/8e3a65741a5cc80c3e4af754072dd11089ddcc66/src/TiledIteration.jl#L64
https://github.com/JuliaArrays/TiledIteration.jl/blob/8e3a65741a5cc80c3e4af754072dd11089ddcc66/test/runtests.jl#L109

**Comment by JeffBezanson** [comment]
We seem to be inferring this list of signatures repeatedly: (first and last lines are the same; the list repeats at that point)
```
Tuple{Type{Base.IteratorsMD.CartesianIndex{N}}, Integer} where N
Tuple{Type{Base.IteratorsMD.CartesianIndex{_}} where _, Tuple{Integer}}
Tuple{Type{Base.IteratorsMD.CartesianIndex{N}}, Tuple{Vararg{Integer, N}}} where N
Tuple{typeof(Base.convert), Type{Tuple{Vararg{Int64, _}}}, Tuple{Integer, Vararg{Integer, N}} where N} where _
Tuple{typeof(Base.convert), Type{#s54} where #s54<:Int64, Integer}
Tuple{Type{T}, Base.GMP.BigInt} where T<:Int64
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{Type{Base.IteratorsMD.CartesianIndex{N}}, Tuple{Vararg{Integer, N}}} where N
Tuple{typeof(Base.convert), Type{Tuple{Vararg{Int64, _}}}, Tuple{Integer, Vararg{Integer, N}} where N} where _
Tuple{typeof(Base.convert), Type{#s54} where #s54<:Int64, Integer}
Tuple{Type{T}, Base.GMP.BigInt} where T<:Int64
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{Type{Base.IteratorsMD.CartesianIndex{N}}, Tuple{Vararg{Integer, N}}} where N
Tuple{typeof(Base.convert), Type{Tuple{Vararg{Int64, _}}}, Tuple{Integer, Vararg{Integer, N}} where N} where _
Tuple{typeof(Base.convert), Type{#s54} where #s54<:Int64, Integer}
Tuple{Type{T}, Base.GMP.BigInt} where T<:Int64
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{typeof(Base.string), Type{T} where T<:Int64}
Tuple{typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{getfield(Base, Symbol("##print_to_string#326")), Nothing, typeof(Base.print_to_string), Type{T} where T<:Int64}
Tuple{Type{Base.IteratorsMD.CartesianIndex{N}}, Integer} where N
```

**Comment by JeffBezanson** [comment]
I believe this is related to #28417, and both issues seem to involve inference results not getting cached, leading to lots of repeated work. For example this fixes it:
```
--- a/base/compiler/typeinfer.jl
+++ b/base/compiler/typeinfer.jl
@@ -148,7 +148,6 @@ function finish(me::InferenceState)
         # a top parent will be cached still, but not this intermediate work
         # we can throw everything else away now
         me.cached = false
-        me.linfo.inInference = false
         me.src.inlineable = false
     else
```
since otherwise `cache_result` doesn't cache anything.

**Comment by vtjnash** [comment]
That's an odd line to remove – I think you're effectively stating that if we see that a limit cycle is possible, we should prohibit inference from ever attempting to infer this method ever again. (and yes, I've made precisely that mistake before, to my own great confusion).

**Comment by JeffBezanson** [comment]
Well, not inferring something might indeed be preferable to taking a very long time to infer it. I also think this slightly abuses the meaning of `inInference` --- it seems like deciding whether to cache a result should be part of cache_result or its caller. Anyway we need to cache these results somehow to fix this family of issues.

**Comment by vtjnash** [comment]
It’s the intended behavior, although I agree the set of flags we check and set is less than ideal and completely opaque (even to me). Because the `limit` flag is set, we know we halted inference before it could compute the complete answer. So we want to let dispatch know here that we’re choosing not to cache this method and so it is free to pick it up again. We’re expecting that the caller at the top of this cycle will be cached though, leading to a total expected work being O(n^2) in the size of the executed loop (loops are typically very small).

**Comment by JeffBezanson** [comment]
Yes, I know it's intended, but the loops in this case are not small. Maybe we could do something like caching the inferred type if it seems to be good enough?

**Comment by visr** [comment]
This was originally reported on 1.0.0, and took 263 seconds to compile.
I just tried it again on both 1.0.3 and 1.1.0, and it compiles in 0.5 seconds!

So feel free to close if you feel like the underlying issue has been dealt with.
