### ISSUE TITLE
Pkg not defined - Julia 1.0 

### ISSUE THREAD

**Issue by JackHo327** [JuliaLang/julia#28574]
Hi Team,

I am a new Julia user.

I just installed the Julia 1.0 on my mac, but I found out that it looks like I could not use the Pkg directly?

```julia
julia> Pkg
ERROR: UndefVarError: Pkg not defined

julia> Pkg.add("IJupyter")
ERROR: UndefVarError: Pkg not defined
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by pkofod** [comment]
You need to `using Pkg` first.

**Comment by affans** [comment]
See related issue https://github.com/JuliaLang/julia/issues/28553
I've already submitted a PR with better documentation as suggested.

**Comment by JackHo327** [comment]
@affans Oh, I see. That's make sense. I watched the [youtube video -- starts at 4:17](https://youtu.be/oyx8M1yoboY?t=4m17s) -- she just directly use the Pkg.add("IJulia") -- right now, I guess that's the feature of version 0.6.0?

**Comment by affans** [comment]
It works in both 0.6 and 0.7/1.0 however in 0.7/1.0 it now requires a specific `import Pkg` to use the functionality of the new, overhauled system.

You can also enter the package manager from the repl using `]` (and existing out of it using backspace). When it `pkg>` prompt, you can use `add [pkgname]` and `st` to add and look at package status.

**Comment by JackHo327** [comment]
@affans Great. Thank you very much.

**Comment by rajacsp** [comment]
> Hi Team,
> 
> I am a new Julia user.
> 
> I just installed the Julia 1.0 on my mac, but I found out that it looks like I could not use the Pkg directly?
> 
> ```julia
> julia> Pkg
> ERROR: UndefVarError: Pkg not defined
> 
> julia> Pkg.add("IJupyter")
> ERROR: UndefVarError: Pkg not defined
> Stacktrace:
>  [1] top-level scope at none:0
> ```

Try this if you face the issue still,
Julia>using Pkg

more:
https://snag.gy/xhZd19.jpg

**Comment by SaiNikhileshReddy** [comment]
I just set up my Julia and IJulia. Setups I followed.

``` Julia
julia> using Pkg
julia> Pkg.add("IJulia")
```
