### ISSUE TITLE
Building julia on old Cray system fails

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#28585]
We think an old git is the reason for this but @pszufe will confirm by updating git.

Trying to build julia 1.0 on a system with git version 1.7.1 fails and outputs:

```
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
....
```

to stderr, and the process hangs.

Perhaps we should document the minimum git version required to build julia.

What is odd is that building on this system worked on 0.6 and I cannot find any difference in the way we call `git rev-list` since then.

cc @pszufe

**Comment by simonbyrne** [comment]
Is it something to do with the version number?

**Comment by simonbyrne** [comment]
In case anyone is wondering, it's called here:
https://github.com/JuliaLang/julia/blob/7c9383fc989c644c2bf6c5d09d7c3d97e7269190/contrib/commit-name.sh#L16

**Comment by pszufe** [comment]
I have built a new git (2.18.0) and added it to the system PATH before anything else (`git --version` returns `2.18.0`). 

Unfortunately this did not help. Now the build process again stops at the log line:
`JULIA usr/lib/julia/sys-o.a` and nothing more happens. 
This time there is no `usage: git rev-list ...` output. The build process just fails silently, gets stalled (does not stop build process) and there is no information what went wrong. 

Additional note: on the same system with the same configuration and settings I have built Julia 0.6 without any problem (using Git 1.7.1).

**Comment by KristofferC** [comment]
Hey @pszufe, really liked your JuliaCon talk!

Can you try the following patch:

```diff
diff --git a/Makefile b/Makefile
index 5846f65ee5f..eaa1e8c2e9c 100644
--- a/Makefile
+++ b/Makefile
@@ -206,7 +206,7 @@ define sysimg_builder
 $$(build_private_libdir)/sys$1-o.a $$(build_private_libdir)/sys$1-bc.a : $$(build_private_libdir)/sys$1-%.a : $$(build_private_libdir)/sys.ji
        @$$(call PRINT_JULIA, cd $$(JULIAHOME)/base && \
        if ! $$(call spawn,$3) $2 -C "$$(JULIA_CPU_TARGET)" --output-$$* $$(call cygpath_w,$$@).tmp $$(JULIA_SYSIMG_BUILD_FLAGS) \
-               --startup-file=no --warn-overwrite=yes --sysimage $$(call cygpath_w,$$<) $$(call cygpath_w,$$(JULIAHOME)/contrib/generate_precompile.jl) $$(call cygpath_w,$$<); then \
+               --startup-file=no --warn-overwrite=yes --sysimage $$(call cygpath_w,$$<) -e0; then \
                echo '*** This error is usually fixed by running `make clean`. If the error persists$$(COMMA) try `make cleanall`. ***'; \
                false; \
        fi )
```

**Comment by pszufe** [comment]
Hi @KristofferC 
Still the same. The build process freezes at:
`JULIA usr/lib/julia/sys-o.a`
- When git 1.7.x (this is standard for Scientific Linux or on Cray XC40) is present:
`usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]`
- When git 2.18: No error information at stdout nor stderr. 
When it's stalled the `julia` process keeps running (but is just blocked). If you tell me what file is being run (`Pkg.jl`?) I can try to repair it myself.

**Comment by KristofferC** [comment]
My guess with the patch above was that the precompile generation script was broken somehow so that removes it. But since it still hangs that doesn't seem to be the case. 

What happens in that stage is that llvm generates native code. Perhaps run with assertions in llvm enabled to see if something bad is happening...

**Comment by ViralBShah** [comment]
Perhaps this is no longer an issue. Please reopen if it is.
