### ISSUE TITLE
REPL Documentation outdated for 0.7/1.0

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaLang/julia#28584]
Documentation for 0.7/1.0 both include a console 'screen-shot' of 0.6 and do not have any mention of the new Pkg3 REPL mode that can be entered through ']'.

**Comment by fredrikekre** [comment]
Where is this screenshot?

**Comment by moustachio-belvedere** [comment]
https://docs.julialang.org/en/latest/stdlib/REPL/

**Comment by moustachio-belvedere** [comment]
replacing it now but not as confident writing the 'pkg' mode explanation addition required further down

**Comment by fredrikekre** [comment]
Will be fixed by #28520, thanks!
