### ISSUE TITLE
inconsistent errors with negative dimensions in Array constructor

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#28597]
This was reported on slack:
```julia
julia> Array{Int, 2}(undef, 0, -10)
0×0 Array{Int64,2}

julia> Array{Int, 2}(undef, -10, 0)
ERROR: invalid Array dimensions
Stacktrace:
 [1] Array{Int64,2}(::UndefInitializer, ::Int64, ::Int64) at ./boot.jl:396
 [2] top-level scope at none:0
```
This comes from the `_new_array_` function in "array.c", which computes the product of the dimensions: if `0` comes first, then the product is `0` and doesn't grow out of bounds.

**Comment by andreasnoack** [comment]
There is some int/uint conversion stuff going on here. The array allocators's size argument is `size_t`, see e.g. https://github.com/JuliaLang/julia/blob/3fe2d08c1546c41ade0459122905016527efa03f/src/array.c#L414 but we pass the value as an `Int`, see https://github.com/JuliaLang/julia/blob/3fe2d08c1546c41ade0459122905016527efa03f/base/boot.jl#L394-L395
so e.g. `-1` becomes a very large number which errors in https://github.com/JuliaLang/julia/blob/3fe2d08c1546c41ade0459122905016527efa03f/src/array.c#L63-L68 unless the previous size was zero, in which case `prod` becomes zero.
