### ISSUE TITLE
UndefVarError: endof not defined

### ISSUE THREAD

**Issue by cxzhoucom** [JuliaLang/julia#28596]
New to julia 1.0, tried the following simple tests from the tutorial, got UndefVarError for endof() and start(), do you have any idea how to solve this? 

> julia> str = "Hello World"
"Hello World"
 
>julia> length(str)
11

>julia> start(str)
ERROR: UndefVarError: start not defined
Stacktrace:
 [1] top-level scope at none:0

>julia> endof(str)
ERROR: UndefVarError: endof not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by KristofferC** [comment]
Which tutorial are you referring to?

**Comment by fredrikekre** [comment]
> from the tutorial

Which one? Those functions does not exist in Julia v1.0 so you likely have an old tutorial. In the future, please consult http://discourse.julialang.org for questions.

**Comment by StefanKarpinski** [comment]
https://discourse.julialang.org/t/psa-use-julia-0-7-if-you-are-upgrading/13321/2
