### ISSUE TITLE
Performance issue due to loading modules multiple times

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#28607]
I have the following issue. In Julia 0.6.4:
```
julia> @time using Winston
  2.243335 seconds (1.85 M allocations: 101.901 MiB, 8.10% gc time)
julia> @time using Gtk
  0.000084 seconds (4 allocations: 160 bytes)
julia> @time using Gtk
  0.000005 seconds (4 allocations: 160 bytes)
```
What you can see here is that loading Gtk was basically a noop since Winston did already load it. 

Now lets have a look at Julia 0.7:
```
julia> @time using Winston
  2.222762 seconds (2.47 M allocations: 139.271 MiB, 1.73% gc time)
julia> @time using Gtk
  1.344923 seconds (2.42 M allocations: 113.772 MiB, 2.38% gc time)
julia> @time using Gtk
  0.000379 seconds (317 allocations: 16.375 KiB)
```
Now loading Gtk seems to be no noop anymore. If these things add up it might get into a serious issue.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/28425

**Comment by KristofferC** [comment]
What is the difference in `Base.loaded_modules` before and after loading `Gtk` the second time?

**Comment by tknopp** [comment]
```
julia> @time using Winston
  2.265382 seconds (2.47 M allocations: 139.271 MiB, 1.73% gc time)

julia> length(Base.loaded_modules)
49

julia> @time using Gtk
  1.363364 seconds (2.42 M allocations: 113.772 MiB, 2.30% gc time)

julia> length(Base.loaded_modules)
49

julia> @time using Gtk
  0.000381 seconds (317 allocations: 16.375 KiB)

julia> length(Base.loaded_modules)
49
```

As I have said, things are loaded twice now.

**Comment by KristofferC** [comment]
> As I have said, things are loaded twice now.

We are trying to determine what is happening.

Can you run

```
for (k, m) in Base.loaded_modules
    string(m) == "Gtk" && println(k)
end
```

before and after `using Gtk` and

`Base.identify_package("Gtk")`

**Comment by tknopp** [comment]
```
julia> @time using Winston
  2.421674 seconds (2.54 M allocations: 143.315 MiB, 5.09% gc time)

julia> for (k, m) in Base.loaded_modules
           string(m) == "Gtk" && println(k)
       end
Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]

julia> @time using Gtk
  1.357142 seconds (2.42 M allocations: 113.768 MiB, 2.72% gc time)

julia> for (k, m) in Base.loaded_modules
           string(m) == "Gtk" && println(k)
       end
Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]
```

**Comment by tknopp** [comment]
May it be an issue that `Winston` is currently in `dev` mode? `gtk` is freed

**Comment by tknopp** [comment]
```
julia> Base.identify_package("Gtk")
Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]
```

**Comment by tknopp** [comment]
I have `freed` Winston now but the issue persists.

**Comment by KristofferC** [comment]
How about

```
p = Base.PkgId(UUID("4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"), "Gtk")
Base.root_module_exists(p)
```

before and after?

**Comment by tknopp** [comment]
```
julia> using UUIDs

julia> p = Base.PkgId(UUID("4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"), "Gtk")
Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]

julia> Base.root_module_exists(p)
false

julia> @time using Winston
  2.653949 seconds (2.56 M allocations: 144.104 MiB, 7.09% gc time)

julia> Base.root_module_exists(p)
true

julia> @time using Gtk
  1.251557 seconds (2.25 M allocations: 105.871 MiB, 2.61% gc time)

julia> Base.root_module_exists(p)
true
```

**Comment by KristofferC** [comment]
If instead of `using Gtk` the second time you do `@time Base.require(p)` where `p` is the same as before?

**Comment by tknopp** [comment]
like this?:
```
julia> p = Base.PkgId(UUID("4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"), "Gtk")
Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]

julia> @time using Winston
  2.555716 seconds (2.56 M allocations: 143.638 MiB, 5.26% gc time)

julia> @time Base.require(p)
  1.270235 seconds (2.25 M allocations: 105.883 MiB, 2.61% gc time)
Gtk
```

**Comment by KristofferC** [comment]
The function `require` is defined at:

https://github.com/JuliaLang/julia/blob/04f4884873c9a91ac506d422638b34f050897c7e/base/loading.jl#L850-L859

We have already established that `root_module_exists` is `true`.

So this should simply be `return root_module(uuidkey)` which is just a dictionary lookup

https://github.com/JuliaLang/julia/blob/04f4884873c9a91ac506d422638b34f050897c7e/base/loading.jl#L892

Not sure what I am missing.

**Comment by tknopp** [comment]
This is on 0.7, just to make sure that the code has not changed since then.

**Comment by tknopp** [comment]
Wait, this is interesting:
```
julia> @time using Winston
  2.407431 seconds (2.56 M allocations: 144.152 MiB, 4.83% gc time)

julia> @time using Graphics
  1.377791 seconds (2.42 M allocations: 113.772 MiB, 2.74% gc time)

julia> @time using Gtk
  0.000435 seconds (318 allocations: 16.422 KiB)
```
Note that `Winston` -> `Gtk` -> `Graphics`. So maybe everything is ok, but this code path is simply not precompiled in the system image?

**Comment by JeffBezanson** [comment]
My guess is that this is due to #28290. We aren't re-loading the package, but re-compiling the loading code (which depends on which methods are invalidated, and so varies among packages).

**Comment by KristofferC** [comment]
@tknopp Perhaps you can revert #28290 and see if the issue persists.

**Comment by tknopp** [comment]
sorry I am currently using the binaries and in turn cannot revert that commit quickly.

**Comment by KristofferC** [comment]
This is due to the require code itself getting invalidated. There are other issues about this so this can be closed.

**Comment by tknopp** [comment]
yep, the new insights are really great.
