### ISSUE TITLE
request more extensive docs on how to use Pkg for application development

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#28601]
The description of how to develop an application project (as opposed to a package) in the latest release of the 1.0 docs is too brief.  I'm referring specifically to the section "Creating your own projects" in the chapter entitled "Pkg" of the manual section entitled "Standard library".  This section tells you how to get started with the `activate` command, but it is missing: (1) that you need to make a src subdirectory, and that the main entrypoint needs to go in that subdirectory and needs to be named the same as the project (and maybe needs to have its module named same as the project? not sure about that).  (2) that you need a Project.toml file.  Is `generate` the correct way to make this file?  The doc says that `generate` is for packages, not application projects.  Please refer to:

https://discourse.julialang.org/t/workflow-for-developing-application-in-new-pkg-manager/13051

for some discussion about this matter that reveals uncertainty among us users.

**Comment by fredrikekre** [comment]
Can you reopen here https://github.com/JuliaLang/Pkg.jl

**Comment by StephenVavasis** [comment]
Done!  Resubmitted as https://github.com/JuliaLang/Pkg.jl/issues/623
