### ISSUE TITLE
Offer PDF version of manual

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#28604]
There was a request for having an offline version of the manual in this Discourse [post](https://discourse.julialang.org/t/offline-julia-1-0-documentation/13263/2). We could use Documenter.jl option to generate a PDF version with LuaLaTeX and have it in the website available for download.

**Comment by cdluminate** [comment]
P.S. We have just uploaded julia 1.0 to Debian experimental with a pdf file shipped within it. The package will be available in debian experimental soon.

If someone wants the pdf now, he/she can download this deb package and grab the pdf.
http://debomatic-amd64.debian.net/debomatic/unstable/pool/julia_1.0.0-1/julia-doc_1.0.0-1_all.deb
