### ISSUE TITLE
calling a c function which triggers a longjmp

### ISSUE THREAD

**Issue by randy3k** [JuliaLang/julia#28606]
My situation is a bit complicated, it actually appears in RCall.jl when I am trying to pass some callbacks to R.

*Without Julia*

There is a c function `foobar` which takes a c function pointer as a callback. Then the callback function will be evaluated down the stream. Upon failure of evaluating the callback, a longjmp shall be triggered by the callback to jump back to `cfunction1`. It could be done by using `Rf_error` in R (something like `jl_throw` of julia).

*With Julia*

Of course, now with julia, I want to replace the callback with a julia function with something like the following

```julia
function callback()
	....
	if failure
		ccall((:Rf_error, libR).......)
	end
end
ccall((:foobar, libR), (Ptr{Cvoid}, ), @cfunction(callback, Cvoid, (,))

```

When the evaluation fails, we need to issue an `Rf_error` to signal `foobar` an error has occurred.

This piece of code has been doing well in julia 0.6. However, random segfaults occur starting with julia 0.7+. I might be doing something terribly wrong here, so I hope someone can point me to a right direction in writing a callback which is `longjmp` torelent.

**Comment by JeffBezanson** [comment]
One thing to try is to put the code that does most of the work into a separate `noinline` function that always returns, to help ensure that its frame is cleaned up:
```
@noinline function callback_impl()
    ...
    if failure
        return true
    end
    return false
end

function callback()
    err = callback_impl()
    if err
        ccall((:Rf_error, libR), ...)
    end
end
```
