### ISSUE TITLE
wrong URL (? not sure) attached to "Edit in Github"

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#28602]
I'm not sure this is actually an error -- if not, please close this issue immediately and sorry to bother you.  In the latest release of the docs in https://docs.julialang.org, in the upper right corner of each doc page, there is a link labeled "Edit in GitHub".  This link points here:

https://github.com/fredrikekre/julia/blob/master/doc/src/index.md

but maybe it's supposed to point here?

https://github.com/JuliaLang/julia/blob/master/doc/src/index.md

**Comment by fredrikekre** [comment]
Yes, I'm on it.
