### ISSUE TITLE
`println.([1,2,3])` prints confusing `3-element Array{Nothing,1}`

### ISSUE THREAD

**Issue by roberthoenig** [JuliaLang/julia#28629]
```julia
julia> println.([1,2,3])
1
2
3
3-element Array{Nothing,1}:
 nothing
 nothing
 nothing
```
I'd expect the broadcasted `println` to print just
```julia
1
2
3
```
For now, a workaround is to append a `;`:
```julia
julia> println.([1,2,3]);
1
2
3
```
From what I see, the problem here lies in the nature of broadcasting: `println` normally returns `nothing`, which is displayed by the repl as a blank line. If we broadcast `println`, however, the returned `nothing`s get  accumulated and stored in an array. 

I was able to partially solve this by specializing `copy` for the `println` function:
```julia
function copy(bc::Broadcasted{DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(println),Tuple{Array{Int64,1}}})
    ElType = combine_eltypes(bc.f, bc.args)
    if Base.isconcretetype(ElType)
        # We can trust it and defer to the simpler `copyto!`
        copyto!(similar(bc, ElType), bc)
        return nothing
    end
    # When ElType is not concrete, use narrowing. Use the first output
    # value to determine the starting output eltype; copyto_nonleaf!
    # will widen `dest` as needed to accommodate later values.
    bc′ = preprocess(nothing, bc)
    iter = eachindex(bc′)
    y = iterate(iter)
    if y === nothing
        # if empty, take the ElType at face value
        similar(bc′, ElType)
        return nothing
    end
    # Initialize using the first value
    I, state = y
    @inbounds val = bc′[I]
    dest = similar(bc′, typeof(val))
    @inbounds dest[I] = val
    # Now handle the remaining values
    copyto_nonleaf!(dest, bc′, iter, state, 1)
    nothing
end
```
 
This works for the simple case `println.([1,2,3])`, but it breaks e.g.
```julia
julia> map.(x -> "foo", println.([1,2,3]))
1
ERROR: MethodError: no method matching iterate(::Nothing)
```
(not to imply that this code actually exists)

If this gets fixed, it should also be fixed for other print-ish functions like `print`, etc.
If people agree that this should be fixed, I'd love to take this up, with a little guidance on how to properly spezialice the broadcasting.

**Comment by KristofferC** [comment]
This is just the return value that the repl prints. `print` indeed returns `nothing`.
