### ISSUE TITLE
LoadError: MbedTLS not installed properly, run Pkg.build("MbedTLS")

### ISSUE THREAD

**Issue by lwhjyun** [JuliaLang/julia#28628]
REPL in Juno for JuliaPro 0.6.3.1 is not working. 
![image](https://user-images.githubusercontent.com/13863279/44028356-2c750300-9f2c-11e8-98c4-7432f689f04a.png)

**Comment by fredrikekre** [comment]
Use https://discourse.julialang.org/ for questions.
