### ISSUE TITLE
architecture customization in README is obsolete

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#28626]
*README.md* still contains

> You can also set `MARCH=native` for a maximum-performance build

I would issue a PR, but I am not sure if the section `#### Architecture Customization` should be updated, or removed entirely.
Ref: https://discourse.julialang.org/t/julia-1-0-released/13208/19?u=jlapeyre

**Comment by ViralBShah** [comment]
@yuyichao @staticfloat 

Is this ok? If not, can you suggest edits to make it accurate? 

https://github.com/JuliaLang/julia/blob/master/doc/build/linux.md

**Comment by jlapeyre** [comment]
This has been resolved in the mean time. There is no longer a reference to `MARCH=native` in the build documentation.
