### ISSUE TITLE
Out of order binding to parent scope

### ISSUE THREAD

**Issue by hjabird** [JuliaLang/julia#28633]
If you  write
```
function my_func()
    function f()
        b = true
        return b
    end
    b = ()->f()
    return b
end
```
you obtain something that will return a function.

If instead you evaluate `b()`:
```
function my_func()
    function f()
        b = true
        return b
    end
    b = ()->f()
    b()
    return b
end
```
then you find that `true` is returned.

Whether this is a bug I do not know. In one sense, the innermost scope takes the b from the mid-level scope, which is logical. It is less logical that it can take something from the outer scope that has yet to be declared, and consequently it seems that the mid-level scope is taking from the innermost scope.

Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by yuyichao** [comment]
Scope cannot be sensitive to execution or control flow (or each line of code will basically introduce a new scope).

This binding is also desired for circular reference (or it'll be impossible to create a recursive function). Note that the global scope behavior is also the same (you don't need to declare everything you reference before defining the function.).
