### ISSUE TITLE
?Symbol help message gives info on constructor, not on type

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#28647]
Looking up help on a type should first explain what the type is and does before going into how to call the constructor. This is not the case for Symbol
```
?Symbol
  Symbol(x...) -> Symbol

  Create a Symbol by concatenating the string representations of the arguments
  together.
```

**Comment by fredrikekre** [comment]
The fix here is to add a docstring to the `Symbol` type.

**Comment by matbesancon** [comment]
We can't have docstrings for both type and constructor right? So it needs to be moved from `Symbol(string)` and edited

**Comment by fredrikekre** [comment]
> We can't have docstrings for both type and constructor right?

Why not?
```
julia> struct Foo x end

julia> """
           Foo

       The type.
       """
       Foo
Foo

julia> """
           Foo(x)

       The constructor.
       """
       Foo(x)
Foo

help?> Foo

  Foo

  The type.

  ─────────────────────────────────────────────────────────────────────
  Foo(x)

  The constructor.
```

**Comment by matbesancon** [comment]
Oh ok my bad, always thought they were shown from one docstring only

**Comment by underscoreorcus** [comment]
I would like to contribute. How can I add the docstring?

**Comment by matbesancon** [comment]
The doc for Symbol is in `base/docs/basedocs.jl` line 1251
