### ISSUE TITLE
Parallel precompilation of packages

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/julia#28658]
Now that new Pkg and v1.0 are in place, it would be great if the precompilation step could be done in parallel (Threads?).

```
pkg> add [packages...]
pkg> precompile
INFO: precompiling using all CPUs...
```

Ref #26503, #15048.

**Comment by ufechner7** [comment]
Why did you close this issue?

**Comment by lassepe** [comment]
Is this idea discussed somewhere else? All I can find about this is the very brief point at the end of [this blogpost](https://julialang.org/blog/2019/07/multithreading/) which states:

> Here are some of the points we hope to focus on to further develop our threading capabilities:
> [...]
> - Using multiple threads in the compiler.
