### ISSUE TITLE
nb_available is not available in Julia 1.0

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#28667]
Hello,

while working on https://github.com/andrewadare/LibSerialPort.jl/issues/14 I noticed that `nb_available` is not available in Julia 1.0 (or at least not in Base)

I haven't seen any depreciation warning in Julia 0.7.

Is there a workaround?

Kind regards

**Comment by laborg** [comment]
on 0.7.0:
```
nb_available(IOBuffer())
┌ Warning: `nb_available` is deprecated, use `bytesavailable` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
0
```

So the replacement is `bytesavailable`

**Comment by scls19fr** [comment]
Sorry 

```julia
using LibSerialPort
```

didn't display this warning

Thanks @fredrikekre

**Comment by scls19fr** [comment]
Thanks @StefanKarpinski it's filled in https://github.com/andrewadare/LibSerialPort.jl/issues/14#issuecomment-413173545

Sorry for noise here.

`nb_available` for LibSerialPort was defined using
https://github.com/andrewadare/LibSerialPort.jl/blob/795a6df86f64468b20d7021f66948855858ca477/src/high-level-api.jl#L403

This kind of error could be better catched with CI https://github.com/andrewadare/LibSerialPort.jl/issues/16

We didn't see warning about this with Julia 0.7. Could you explain why?

Is it because we should have import `nb_available` from `Base` instead of bindly overload `Base.nb_available`?

**Comment by KristofferC** [comment]
Overloading a deprecated method and then extending it, unfortunately, does not generate a deprecation warning. It is a bit of a flaw with the current depreciation implementation.
