### ISSUE TITLE
a fault in getting started when using the '-e' option.

### ISSUE THREAD

**Issue by nagexiucai** [JuliaLang/julia#28662]
[screenshot](https://github.com/JulialangOrgCN/JuliaDocCN/blob/master/bug/Manual-GettingStarted-Julia-Eoption-CLI-Arguments.png)

Even "julia -e '1+1'" will show "ERROR: syntax: invalid character literal".

On Windows 10 Home Edition, 1803, 17134.165, Intel Core i7-8550U.

BTW, can we merge "-g, -g <level>" into "-g [level]" in [doc.manual](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/getting-started.md)?

**Comment by ontouchstart** [comment]
From your screenshot, the symbol looks like `’` instead of `'`. That is why you see the
 `invalid character literal` error message. 

<img width="1030" alt="screen shot 2018-08-15 at 9 37 27 pm" src="https://user-images.githubusercontent.com/41637129/44182114-78cc5200-a0d3-11e8-903e-c3331ec2a184.png">

On my machine, both single quotes and double quotes work:

```
julia -e "println(PROGRAM_FILE); for x in ARGS; println(x); end" foo bar

foo
bar

```

```
julia -e 'println(PROGRAM_FILE); for x in ARGS; println(x); end' foo bar

foo
bar

```

**Comment by nagexiucai** [comment]
@ontouchstart :) thanks for your response. though the single quotes looks like chinese punctuation in my [screenshot](https://github.com/JulialangOrgCN/JuliaDocCN/blob/master/bug/Manual-GettingStarted-Julia-Eoption-CLI-Arguments.png), but it is a real english half angle symbol.

@racaljk :) aha~good, use double quotes instead of single quotes. cmd.exe features it, if not this issue(first feeling) i never notice quotes in cmd.exe.

=====references=====
[i](https://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q)
[ii](https://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files)
[iii](https://msdn.microsoft.com/en-us/library/a1y7w461.aspx)
