### ISSUE TITLE
Should +(::Any, Missing) be defined in base?

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#28676]
Let's say you have a custom type and you want `+` to work on it, but you don't wnat to make it `<:Number`. You are likely to define `+(x::MyType, b::Number)` and so forth, but neglect to define propogation of `missing`s. 

This results in errors where `missing` values don't propagate and users get errors where they expect silent propagation of missings. One way to get around this is to define `+(x::Any, m::Missing)` such that `+` will fall back on that implementation if you haven't defined any propagation rules for your new type. 

I suspect this is a bad idea. If you have a type for which `+` doesn't make any sense at all, you will want `+` to throw an error, regardless of whether or not it is with missing values or not. 

R does this:
```
> "three" + "four"
Error in "three" + "four" : non-numeric argument to binary operator
> "three" + NA
Error in "three" + NA : non-numeric argument to binary operator
```

But this might merit some discussion, or at least have an issue to point to when people have errors relating to basic operators on custom types with `missing`s.

**Comment by JeffBezanson** [comment]
> I suspect this is a bad idea.

I agree :)
