### ISSUE TITLE
Dates allows non-broadcasted arithmatic

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#28672]
Dates redefines `+(::Array{Date}, Date...) = .+`, meaning that array + scalar doesn't throw an error. 

https://github.com/JuliaLang/julia/blob/f8d82ccba81223c9d0d43e4077acb2a208bedc7a/stdlib/Dates/src/arithmetic.jl#L94 

This should probably be deprecated for consistency.

**Comment by JeffBezanson** [comment]
Oh dear, how did we miss this. Maybe add a deprecation warning in v1.1?

**Comment by StefanKarpinski** [comment]
I suspect that Dates will need a major version upgrade in the near future, pretty much as soon as we figure out how to version and allow selection of stdlibs. (Or maybe just move it out of stdlib.)

**Comment by JeffBezanson** [comment]
Deprecated in #29509.
