### ISSUE TITLE
∀, ∃ and other special characters not available in the Roboto Mono font used in the pdf documention

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaLang/julia#28686]
I suggest changing the monospace font used by the PDF documentation, so the special Unicode strings displayed in e.g. Manual -> Strings -> Unicode and UTF-8.

**Comment by fredrikekre** [comment]
Can you reopen this issue at https://github.com/JuliaDocs/Documenter.jl/issues ? Thanks!
