### ISSUE TITLE
Segmentation fault from changing constants

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#28689]
I have been struggling for quite some time to debug a code by one of my students, and finally managed to trace the error down to modifying constant global variables, which are not `isbits`, and which have been referred to in functions that are compiled. Julia gives a gentle warning upon redefining constants, but you don't expect a segmentation fault resulting from it. The bug was originally in a julia 0.6 code, but the same still happens in 1.1-DEV
```julia
const A = randn(10)
function f()
   return sum(A)
end

f() # -> returns something

A = randn(10) # -> redefine, Julia prints a warning

f() # -> still returns the old value

# do some more stuff, until at some point the garbage collector is triggered
GC.gc()

f() # -> segfault, probably not directly, but eventually, just do some more times gc() and other allocating stuff

```

**Comment by KristofferC** [comment]
Maybe just make the warning more scary?

**Comment by Jutho** [comment]
`WARNING: redefining constant ... . All hell breaks loose!`

**Comment by Jutho** [comment]
To what extent can we think about constants as just inlined functions that return the constants value? I was wondering wether the same machinery that makes dependence between functions trigger recompilation when a method is redefined can do the same for constants? No idea if that is at all feasible?

**Comment by tknopp** [comment]
Why is redefining constants allowed at all?

**Comment by JeffBezanson** [comment]
> Julia gives a gentle warning upon redefining constants

The warning is not supposed to be interpreted as gentle! Aside from deprecations, we give warnings quite rarely and only when something is really wrong.

> Why is redefining constants allowed at all?

It can be convenient interactively. Maybe it should only be allowed in the REPL?

**Comment by JeffBezanson** [comment]
> using deprecated functions does not lead to segfaults

That's why I said "aside from deprecations". But what I don't understand is why somebody would be ok with their program printing warnings. Is the desired outcome really to have the warning, but no segfault? I would think no warning *and* no segfault would be better. I agree we should probably strengthen the warning though, adding something like `this may corrupt your program`.

**Comment by Jutho** [comment]
I think the reason that I interpreted this warning is gentle and typically go over it lightly, is because I read this in the help for the `const` keyword:

> Technically, you can even redefine const variables, although this will generate a warning from the compiler. The only strict requirement is that the type of the variable does not change, which is why const variables are much faster than regular globals.

I am exaggerating a bit here, but I could imagine people interpreting this as: Adding `const` seems like an another `trick` to let julia do its magic and get a speedup. There is no explicit warning against this in the help.

However I did just find that the docs are more explicit (I don't remember reading that back when I started using Julia, so I should maybe read the latest version again):

> Note that although possible, changing the value of a variable that is declared as constant is strongly discouraged. For instance, if a method references a constant and is already compiled before the constant is changed then it might keep using the old value.

Feel free to close.

**Comment by JeffBezanson** [comment]
I'll reword the manual and help. The warnings there should be much stronger.

**Comment by StefanKarpinski** [comment]
Can we just add GC edges from compiled functions to values they depend on? That seems like it would fix this segfault.

**Comment by StefanKarpinski** [comment]
People _really_ like reloading files and I don't see why we should make it impossible to do so just because we've made redefining constants an error. Sure, adding 265-style back edges for constants would be good, but rooting all constants seems like it would straightforwardly fix this segfault without causing any major complications. If someone doesn't redefine any constants then it has no impact since their constants are rooted anyway; if someone does redefine constants, then they might end up with some extra rooted values which could potentially leak memory, but that's way better than having segfaults.

**Comment by andyferris** [comment]
> People *really* like reloading files

No argument there!

So long as we acknowledge the lack of a backedge as a bug, like #265, I'm happy :) (I feel similarly for `@pure` but let's not go there...)

**Comment by StefanKarpinski** [comment]
It's not a bug since redefining a constant isn't really something one can expect to work.

**Comment by andyferris** [comment]
Hmm... sorry, this seems like a curious comment. You're the one that argued people *really* like to (i.e. expect to be able to) reload code (and potentially redefine constants).

Honestly, I similarly never thought of #265 as a "bug" - it's just the way the system works. I feel this is equivalent to #265 is all (whether we call that a bug or not). Coming from many other programming languages, redifining a method isn't really something one would expect to work, either.

It's just my feeling that the work relating to world consistency is only semi-complete (don't see this as a critism - modern versions of Julia are way better and more usable than earlier versions!). I think you're right that we shouldn't make this an error. and that we should make it work to the best of our ability, and that adding a permanent GC root is a decent solution.

**Comment by StefanKarpinski** [comment]
My position is this: it's not a bug if redefining a constant doesn't work flawlessly; a segfault, however, is too great a flaw. It's over and above the call of duty for redefinition of a constant to recompile code that depends on it; but of course, sure it would be nice, but not doing it is certainly not a bug.

**Comment by JeffBezanson** [comment]
The trouble is that not being able to assume global constants are rooted will hinder optimizations. The two categories of problems are (1) needing to set up GC frames and allocate roots in generated code for these values, and (2) the overhead of scanning the extra roots during GC and relocating them when loading the system image.

**Comment by StefanKarpinski** [comment]
> The trouble is that not being able to assume global constants are rooted will hinder optimizations.

My proposal was that old values of constant bindings remain rooted forever (or as long as the module they were once bound in exists), which doesn't seem to undermine that assumption in any way.
