### ISSUE TITLE
Can pkg use another directory rather than the default $HOME?

### ISSUE THREAD

**Issue by einzigsue** [JuliaLang/julia#28715]
I just installed julia/v1.0.0 on a cluster and didn't find a way to redirect the pkg environment to use another directory rather than $HOME to install modules in the general.git such as CSV.
Is there a way to reset the default path? similar to JULIA_PKGDIR in v6.

**Comment by 00vareladavid** [comment]
Are you looking for `DEPOT_PATH`? Docs for `Pkg` are [here](https://docs.julialang.org/en/latest/stdlib/Pkg/)

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
