### ISSUE TITLE
Julia 1.0 - Queryverse - Failed

### ISSUE THREAD

**Issue by ss-roy** [JuliaLang/julia#28718]
Hi,

I'm trying to use query verse in Julia 1.0. But I'm getting a load error. Screen shot of the error is attached here. Any suggestion or recommendation would be helpful.

Thanks!
<img width="868" alt="screen shot 2018-08-17 at 3 47 30 pm" src="https://user-images.githubusercontent.com/16146646/44247393-31130b00-a238-11e8-83fe-b57381cfffb4.png">

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/. Also, it is better to post a copy-paste of the error instead of a screenshot, since an image will not be searchable (and its also not very readable either).
