### ISSUE TITLE
REPL docs for __init__

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#28730]
```
help?> __init__
search:

Couldn't find __init__
Perhaps you meant @__dot__
  No documentation found.

  Binding __init__ does not exist.
```

would be good to  have. Should be added here: https://github.com/JuliaLang/julia/blob/master/base/docs/basedocs.jl and documented like the other keywords I guess.

**Comment by Moelf** [comment]
I'd like to contribute, is this a good source document to paraphrase from?
https://docs.julialang.org/en/v0.6.0/manual/modules/

**Comment by Moelf** [comment]
PR submitted: https://github.com/JuliaLang/julia/pull/28903

**Comment by Moelf** [comment]
Can we maybe merge this?

**Comment by fredrikekre** [comment]
#31930
