### ISSUE TITLE
Unable to install Julia on Windows using self-extracting exe

### ISSUE THREAD

**Issue by mypatience** [JuliaLang/julia#28734]
I was unable to install Julia on my Windows 7 machine.

I downloaded the self-extracting julia-1.0.0-win32.exe file.
When running the exe, I see it first extract another exe (Julia-installer.exe) in a temp directory (C:\Users\<User>\AppData\Local\Temp\<some_name>.tmp.

The problem is that my PC has an antivirus software (Sophos) that is set by my company and that I don't have much control on. The Sophos antivirus does not allow and exe to run from a temp directory in  User\AppData\Local\Temp. It detect this as "Generic ML PUA" threat.

At the moment, I can't see a way to go around this issue. The only option for me is to build Julia from source code, which I believe would be a little more work and not sure if I would have issues with that.

It would be great if the Windows installer can handle issues with antivirus software.

**Comment by ViralBShah** [comment]
The best hope we have is to address https://github.com/JuliaLang/julia/issues/25730

Nothing else we can do here otherwise, if this is still an issue.
