### ISSUE TITLE
conditional @warn("...") leads to a segfault

### ISSUE THREAD

**Issue by kafisatz** [JuliaLang/julia#28746]
I have made a PR to my package which only adds a `@warn("...some text...")` statement (inside an if end clause).
This leads to a segfault.
See travis of this PR: https://github.com/kafisatz/DecisionTrees.jl/pull/22

Any ideas why that would happen?
The change seems so minor, I am puzzled why this crashes Julia.
Am I missing something?

Notably the all tests ran fine before that change.
This can be seen in build 304 on travis:
https://travis-ci.org/kafisatz/DecisionTrees.jl/builds/417735978

**Comment by kafisatz** [comment]
On second thought it might be the if condition itself that leads to the crash of Julia (and not the warn). 
But the if condition is so simple. It is unclear to me why it crashes Julia.

I quickly ran all the tests with this snippet of code (at the right location). It runs through fine. 
`
    @show size(features,1)
    @show obstrn+obsval
    @show typeof(obstrn+obsval)
    @show typeof(size(features,1))
    @assert isa(obstrn+obsval,Int)
    @assert isa(size(features,1),Int)
    if size(features,1) != obstrn+obsval 
    #    @warn("DTM: obstrn+obsval != size(features,1). This is experimental.")
    end
`

**Comment by Keno** [comment]
I suspect this is another instance of the bug you reported in #28536 (fixed by #29015). Your code has patterns that is likely to trigger that issue. If you run into this again on a version that includes that fix, please file a new issue.
