### ISSUE TITLE
`unsafe_convert(::Type{Ptr{Nothing}}, ::Ref{Nothing})` recurses infinitely

### ISSUE THREAD

**Issue by distractedlambda** [JuliaLang/julia#28774]
As the title suggests, an invocation of `unsafe_convert(::Type{Ptr{Nothing}}, ::Ref{Nothing})` recurses infinitely, due to the recursive definition of `unsafe_convert(::Type{Ptr{Cvoid}}, RefValue{T}) where {T}` on line 30 of refvalue.jl. I'm not sure what the correct behaviour of this invocation should be, but infinite recursion doesn't seem quite right.

**Comment by nsajko** [comment]
Seems fixed on v1.6 and up.
