### ISSUE TITLE
Julia 64bit ARM Binary Version is missing for Julia 1.0.0

### ISSUE THREAD

**Issue by jamitzky** [JuliaLang/julia#28783]
The arm version of julia 1.0.0 does not run on my android device because it needs a 64bit-version. Julia 0.6.2 worked fine. Why did you drop the 64bit Version?
I was using termux and proot/fedora to provide a container for it on android 6.0.

**Comment by vchuravy** [comment]
I believe AArch64 support is currently blocked on #27174, and the ARM/AArch64 port is currently lacking a maintainer.

**Comment by ararslan** [comment]
> Why did you drop the 64bit Version?

It was not a conscious choice. As Valentin said, it was due to technical limitations in supporting AArch64. Hopefully we'll be able to get that fixed and provide AArch64 binaries again in the future.

**Comment by PallHaraldsson** [comment]
FYI: In the mean-time, the README is no longer correct, only about what we want, with it only correct for pre-1.0): "Julia fully supports ARMv8 (AArch64) processors, and supports ARMv7 and ARMv6 (AArch32) with some caveats."

**Comment by robsmith11** [comment]
There's a 1.0.3 aarch64 binary now, so this could be closed.

**Comment by ViralBShah** [comment]
Arm binaries are still an issue. But at least we have 1.0 binaries.
