### ISSUE TITLE
Workers should inherit Pkg environment

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#28781]
(Moved over from https://github.com/JuliaLang/Pkg.jl/issues/675)

If I have a project where I installed `MyPackage` and I can say

```julia --project -e "using MyPackage"```

the following does only work when I manually activate the environment:

```jl
using Distributed
using MyPackage   # works
addprocs(3)
@everywhere
  using Pkg; Pkg.activate(".")  # required
  using MyPackage
  ...
end
```

I would suggest that workers inherit the environment that is active when they are added with `addprocs`. Should there be any calls to `Pkg.activate` after `addprocs` they have to be manually performed by the user on all workers.

**Comment by affans** [comment]
Can you explain a little bit more to whats happening? I have a large codebase I want to port to 1.0 that uses HPC/addprocs quite a bit. If I know better what is happening, maybe I can submit a PR

**Comment by Element-126** [comment]
I just got bitten by this issue while I was porting a small project from 0.6 to 1.0. As soon as I started using a separate environment for the project, worker processes started to throw `Package ... is required but does not seem to be installed` exceptions.

In addition to @rened's suggestion, I would also suggest that `(MyProject) activate .` activates the environment on worker processes as well, or at least issues a warning instead of silently ignoring them. This would be useful when starting Julia with the `-p <N>` option and then manually activating the environment.

**Comment by Element-126** [comment]
@affans It seems that `(MyProject) activate .` and `Pkg.activate(".")` only activate the environment on the master process. To activate it on all processes, you would need to use the following code:
```julia
using Distributed
@everywhere using Pkg
@everywhere Pkg.activate(".")
```
You can then use `@everywhere using MyPackage` as usual.

**Comment by StefanKarpinski** [comment]
This requires some careful thinking about how best to do this. One possibility is to send a manifest from the master node to the workers and insist that the manifest be usable on all nodes. That's fine for non-dev packages and even for dev packages with relative paths but dev packages with absolute paths may be a bit of an issue. We could rewrite dev paths to use a commit instead and then send that over; of course, it requires that the workers know about the tree hash that's being used...

**Comment by matteoacrossi** [comment]
I ran into the same problem and it took me a while to understand that the problem was with `activate`. So I believe there should at least be a warning when using activate with worker processes.

**Comment by simonbyrne** [comment]
Another work around is to use the `JULIA_PROJECT` environment variable instead of `--project`, as that will be passed to subprocesses.

**Comment by StefanKarpinski** [comment]
For now, that's the recommended way to do this.

**Comment by oxinabox** [comment]
One thing one wants to be clear on is which enviroment a worker should be getting.
If a Package is startng a worker, then the worker should probably have that packages enviroment.
not the enviroment that the main process  is running in.

As in: https://github.com/malmaud/TensorFlow.jl/pull/493/files

**Comment by oxinabox** [comment]
Oh in the case of a package that owns a worker and want it it use it's environment it is even more complicated. Since even if the package created the worker, 
It will still exist globally, and so when any `using` is run in the main process, the worker will attempt to load the module -- which will be from the main environment.

So workers need both the packages environment and the main environment.
I think this can be done with `LOAD_PATH` for nested environments right?

**Comment by simonbyrne** [comment]
As an additional point, it turns out that setting `JULIA_PROJECT` doesn't work when starting with `--machine-file`.

**Comment by chriselrod** [comment]
I always run something like:
```julia
addprocs(18, exeflags = "--project=$(Base.active_project())")
```
would be nice if this could be the default, at least for local `addprocs`, where all workers should have access to the same `Manifest`.

**Comment by garrison** [comment]
In addition to inheriting the project environment, I believe that local workers should use the same depot settings as well.  (Technically, this is a separate issue, but I think it would be good to revisit and fix this at the same time as this.)  Example of me working around this is [here](https://github.com/garrison/Pluto.jl-on-sandstorm/blob/619f3c7336703c994ed60213914c7286dd04a428/launcher.jl#L3-L7).

**Comment by garrison** [comment]
> I think this can be done with `LOAD_PATH` for nested environments right?

If the `LOAD_PATH` of each child were set to be the same as the output of `Base.load_path()`, I believe this would effectively set the "project environment" for all things except `Pkg` operations -- it would at least make the installed packages available to the workers.

**Comment by KristofferC** [comment]
Here is another kinda sad situation:

```jl
❯ cat src/Package.jl  
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: src/Package.jl
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ module Package
   2   │ 
   3   │ using Distributed
   4   │ 
   5   │ function f()
   6   │     addprocs(4)
   7   │     return @distributed (+) for i = 1:20000000
   8   │         1
   9   │     end
  10   │ end
  11   │ 
  12   │ end # module
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

```jl
❯ julia --project -e 'using Package; Package.f()'
ERROR: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:322 [inlined]
 [2] fetch
   @ ./task.jl:337 [inlined]
 [3] preduce(reducer::Function, f::Function, R::UnitRange{Int64})
   @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/macros.jl:278
 [4] f()
   @ Package ~/Documents/JuliaTests/Package/src/Package.jl:7
 [5] top-level scope
   @ none:1

    nested task error: On worker 2:
    KeyError: key Package [d2156de5-0bca-4c89-9c3d-7078f44b555d] not found
    Stacktrace:
      [1] getindex
        @ ./dict.jl:482 [inlined]
      [2] root_module
        @ ./loading.jl:979 [inlined]
      [3] deserialize_module
        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Serialization/src/Serialization.jl:962
...
     [11] deserialize_msg
        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/messages.jl:87
     [12] #invokelatest#2
        @ ./essentials.jl:708 [inlined]
     [13] invokelatest
        @ ./essentials.jl:706 [inlined]
     [14] message_handler_loop
        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:169
     [15] process_tcp_streams
        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:126
     [16] #99
        @ ./task.jl:411
    Stacktrace:
     [1] remotecall_fetch(::Function, ::Distributed.Worker, ::Function, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:394
     [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Function, ::Vararg{Any, N} where N)
       @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:386
     [3] remotecall_fetch(::Function, ::Int64, ::Function, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:421
     [4] remotecall_fetch
       @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:421 [inlined]
     [5] (::Distributed.var"#157#158"{typeof(+), Package.var"#1#2", UnitRange{Int64}, Vector{UnitRange{Int64}}, Int64, Int64})()
       @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/macros.jl:274
```
