### ISSUE TITLE
typealias of abstract type ignores parameters

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#28794]
```julia
julia> const Foo{T} = Array
Array

julia> Foo{Int}
Array{Int64,N} where N

julia> Foo{Int, 1}
Array{Int64,1}
```

I suppose that to the extent that `Foo{T} == Array`, the last two are not surprising. I encountered that while debugging something else, so I don't have an immediate use/problem with this behavior, but isn't it a bit off?

Similarly, 

```julia
julia> const Car{T, U} = T
Any

julia> Car{Int}
ERROR: TypeError: in Type{...} expression, expected UnionAll, got Type{Any}
```

That should probably be an error?

**Comment by JeffBezanson** [comment]
This is just how the type system works. It should be understood that `A{T} = B` is a rewrite of `A = B where T`. If you want a function from types to types, use a function, `A(T) = B`.

**Comment by cstjean** [comment]
Fair enough.
