### ISSUE TITLE
Type piracy over Union{} with Dict

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#28798]
On 0.7, this seemingly innocent `convert` method (taken from [ShiftedArrays.jl](https://github.com/piever/ShiftedArrays.jl/blob/master/src/offset.jl#L1-L4)) is unexpectedly called by a `Dict(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}})` call. It caused https://github.com/mauro3/Parameters.jl/issues/73

```julia
julia> struct Foo end

julia> Base.convert(::Type{<:Array}, ss::AbstractArray{<:Foo}) = stop()

julia> bar(; kw...) = kw
bar (generic function with 1 method)

julia> Dict(bar())
ERROR: UndefVarError: stop not defined
Stacktrace:
 [1] convert(::Type{Array{Union{},1}}, ::Array{Union{},1}) at ./REPL[2]:1
 [2] Dict{Union{},Union{}}() at ./dict.jl:91
 [3] Type at ./dict.jl:102 [inlined]
 [4] dict_with_eltype at ./abstractdict.jl:566 [inlined]
 [5] Dict(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./dict.jl:129
 [6] top-level scope at none:0
```

It gets called because `Union{} <: Foo`. Is `Base` is at fault here, or should ShiftedArrays be rewritten? I wouldn't have called it type piracy, but it's behaving as such.

**Comment by piever** [comment]
I feel bad about this, I definitely think it's ShiftedArrays fault. `Array{Union{}}` is a bit of a funky type but still it belongs to Base, so a package should not affect how that gets converted to `Array`. I simply did not think about this corner case.

**Comment by rdeits** [comment]
Dispatching on `AbstractArray{<:Foo}` seems like a perfectly reasonable thing to do in many cases. That technique is common in the Images ecosystem where an image is just an `AbstractArray{<:Colorant}` (e.g. [Images/showmime.jl](https://github.com/JuliaImages/Images.jl/blob/d136d963db7192a105382ae866e36a4b6f239b49/src/showmime.jl#L19)) or in JuMP which has specialized linear algebra for vectors of variables or affine terms (e.g. [JuMP/operators.jl](https://github.com/JuliaOpt/JuMP.jl/blob/1ca6a8f5a38640717ae1713fedc8facd7a41e17d/src/operators.jl#L467)). So I wouldn't blame ShiftedArrays for trying to do the same thing.

**Comment by vtjnash** [comment]
Not sure whether to call it type piracy or not, but it works fine now
```
julia> struct Foo end

julia> Base.convert(::Type{<:Array}, ss::AbstractArray{<:Foo}) = stop()

julia> bar(; kw...) = kw
bar (generic function with 1 method)

julia> Dict(bar())
Dict{Symbol, Union{}}()
```
