### ISSUE TITLE
Add `keys` for `zip`

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#28796]
The iterator created by `zip` does not have `keys` defined. I think it would be good to add it.

Without it e.g. `paris` on `zip` fails. Then in consequence all infrastructure using `pairs` like `findall` fails on the result of `zip`.

Is there any reason why this was not implemented? I could try propose a PR for this if we agree that it is good to have `keys` for `zip`.

**Comment by ararslan** [comment]
Zip iterators aren't indexable, so what are their keys? I'm not sure it's well-defined in this case.

**Comment by bkamins** [comment]
This is right, but the idea was that often you `zip` collections that support indexing. Then `keys` for `zip` would return tuples of keys of underlying collections. If at least one of zipped collections does not support indexing then `keys` on `zip` would error.

But I was not 100% sure if this is a good concept - that is why I have asked.

**Comment by rfourquet** [comment]
In #22489 is a related proposal to allow indexing into zip iterators.

**Comment by JeffBezanson** [comment]
Some might expect `keys(zip(a,b)) == a`, so I'd hesitate to do this.

See also #27855.

**Comment by bkamins** [comment]
I am OK to close it if it is not a clear cut thing (and it seems so).
