### ISSUE TITLE
ERROR: Unable to find compatible target in system image

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaLang/julia#28801]
I have compiled the current master branch of Julia on compute node on our HPC. Instalation wasn't smooth, but eventually I managed to do that with GCC 6.4.0 (attempt on GCC 4.x failed, attempt on GCC 7.x failed as well), CMake 3.12, make 4.2.1, pkg-info 0.29.2 and git 2.15.1. Julia works fine there (or at least displays the prompt and I can do basic math). 

```
./julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.unknown (2018-08-20)
 _/ |\__'_|_|_|\__'_|  |  Commit ae0738e (0 days old master)
|__/                   |

julia> 2+2
4
```

Unfortunately, in our setup compute nodes do not have access to the internet, so to install any Julia module from the repository I need to run Julia on access node as well.

The access node is implemented as a virtual machine on top of one compute node with the same architecture and access the same root filesystem as all the compute nodes. So whatever runs on the access node, will run on compute node as well.

Except for Julia. When I run Julia from the access node I get the following error:

```
./julia 
ERROR: Unable to find compatible target in system image.
```

Do you have any idea, even very remote, what should I tell system administrator (who is new to Julia, obviously)?

**Comment by yuyichao** [comment]
You need to specify a target list that's compatible with all the nodes. Please use discourse for questions.
