### ISSUE TITLE
Ptr <: Ref

### ISSUE THREAD

**Issue by mylincode** [JuliaLang/julia#28806]
I was surprised to find out that `Ptr{T} <: Ref{T}`. I'm guessing that there's a reason for this, but it complicates a key conceptual aspect of `Ref`s:

> This type is guaranteed to point to valid, Julia-allocated memory of the correct type. The underlying data is protected from freeing by the garbage collector as long as the Ref itself is referenced.

Granted, the above statement remains true for anything constructed with `Ref(...)`, but the problem remains that something which, under the type system, is a `Ref{T}`, could violate those guarantees by concretely being a `Ptr{T}` (as opposed to e.g. a `Base.RefValue{T}`).

**Comment by vtjnash** [comment]
Addressed by https://github.com/JuliaLang/julia/pull/31700
