### ISSUE TITLE
Embedded Julia doesn't know how to include

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#28825]
If you do
```
jl_eval_string("include(\"mystuff.jl\")");
```
the result is
```
UndefVarError: include not defined
```
Instead you have to do `Base.include(Main, filename)` or first eval `include(x) = Base.include(Main, x)`.
I don't know whether this is intentional or an oversight, but it should either be fixed or documented.

**Comment by tkf** [comment]
Another approach would be to do `jl_eval_string("@eval Main import Base.MainInclude: eval, include")` as done in `Base._start`:

https://github.com/JuliaLang/julia/blob/2715fb2904f233e1e1b5f23c52612b9955ee6461/base/client.jl#L416-L419

**Comment by c42f** [comment]
This is a bug IMO.  It's also worth noting that `Main.eval` is not present for the same reasons. This can cause a very confusing difference between embedded vs normal julia, eg this discourse question: https://discourse.julialang.org/t/problem-calling-string-parse-eval-from-c/23701

The origin of `MainInclude` is purely aesthetic, as stated here: https://github.com/JuliaLang/julia/pull/23664
