### ISSUE TITLE
Dynamically loaded embedding doesn't know the spelling of jl_init

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#28824]
When dynamically loading libjulia, it depends on how Julia was built whether you should initialize it with `jl_init` or `jl_init__threading`. While it's not the most difficult workaround to check which of the two functions exists in the loaded library, it's far from elegant or convenient, as well as undocumented.

(This is a regression from Julia 0.6, where it was always `jl_init`.)

**Comment by c42f** [comment]
Looking at julia.h this was done on purpose so that non-dlopen based embedding would give a visible error. Which leaves us in an uncomfortable situation for a dlopen based version where you're not depending on the threading details.

**Comment by fingolfin** [comment]
I think PR #40637 may have effectively resolve this, as it renames `jl_init__threading` to `jl_init`?

**Comment by c42f** [comment]
Agreed
