### ISSUE TITLE
getpass not working on Windows

### ISSUE THREAD

**Issue by crbinz** [JuliaLang/julia#28828]
`Base.getpass` does not appear to accept input when used on Windows (64-bit Windows 7):

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Base.getpass("Test: ")
Test: : SecretBuffer("*******")

julia> read(ans,String)
┌ Warning: a SecretBuffer was `shred!`ed by the GC; use `shred!` manually after use to minimize exposure.
└ @ Base secretbuffer.jl:169
""
```

Also tested under v1.0 with the same result. I've tried regular keyboard input, and pasting from the clipboard. `Base.winprompt` works as expected.

ref: https://discourse.julialang.org/t/how-do-i-use-getpass/13880

**Comment by mbauman** [comment]
Thanks for the report, and sorry about this! Looks like we're missing a `seekstart` here.  Does the following work for you?

```julia
s = Base.getpass("Test: ")
seekstart(s)
read(s, String)
```

In general, `winprompt` is a _much_ better solution on Windows and will be more secure.

**Comment by crbinz** [comment]
That does indeed do the trick, and noted about `winprompt`.

**Comment by StefanKarpinski** [comment]
> In general, `winprompt` is a much better solution on Windows and will be more secure.

Can we make `Base.getpass` use `winprompt` on Windows then?

**Comment by mbauman** [comment]
I really wanted to unify these, but it's just a very different API — `winprompt` pops up a GUI window and asks for a username and password pair.  As far as I'm aware, Windows doesn't expose an API for secure entry from STDIN, so we're emulating one to the best of our ability.

**Comment by giordano** [comment]
Can this be closed?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/28832
