### ISSUE TITLE
provide a mapping from Serialization protocol version to package version

### ISSUE THREAD

**Issue by iwelch** [JuliaLang/julia#28837]
It would be useful to add a version number to serialization, if only to ascertain that one tries to read a serialized object with the same version Serialization.

(PS: The Serialization format should probably keep this version together with its front magic byte, too.)

**Comment by mbauman** [comment]
It does? https://docs.julialang.org/en/stable/stdlib/Serialization/#Serialization.writeheader

**Comment by iwelch** [comment]
great.  that's the PS.  on the main one,

```
julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 19 entries:
...
  "DelimitedFiles"    => nothing
```

**Comment by JeffBezanson** [comment]
I don't understand. What is the connection to DelimitedFiles? What lookup table are you referring to?

**Comment by iwelch** [comment]
Sorry, I removed the wrong line from the Pkg.installed output.  I meant

```
  "Serialization"     => nothing
```

It would be nice if one could query a serialized file and learn that it was created by Serialization 0.7.3 .  That way, I do not need to figure out whether protocol version 15 is Serialization 0.7.1 or 0.7.3.
