### ISSUE TITLE
Julia 0.7 crashed after applying colorbar() (PyPlot)

### ISSUE THREAD

**Issue by cwb0** [JuliaLang/julia#28830]
I am not sure if this is the right place for a bug report. Nevertheless I will report the following session which ends up in a crash (which is reproducible): 

versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "C:\Users\Carsten\AppData\Local\atom\app-1.29.0\atom.exe" -a
  JULIA_NUM_THREADS = 2

(v0.7) pkg> up
  Updating registry at `C:\Users\Carsten\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Carsten\.julia\environments\v0.7\Project.toml`
 [no changes]
  Updating `C:\Users\Carsten\.julia\environments\v0.7\Manifest.toml`
 [no changes]

(v0.7) pkg> st
    Status `C:\Users\Carsten\.julia\environments\v0.7\Project.toml`
  [c52e3926] Atom v0.7.3
  [0c46a032] DifferentialEquations v5.2.1
  [7a1cc6ca] FFTW v0.2.4
  [7073ff75] IJulia v1.9.3+ [`C:\Users\Carsten\.julia\dev\IJulia`]
  [4138dd39] JLD v0.8.3
  [e5e0dc1b] Juno v0.5.2
  [b964fa9f] LaTeXStrings v1.0.2
  [5fb14364] OhMyREPL v0.3.0
  [d96e819e] Parameters v0.9.2
  [91a5bcdd] Plots v0.19.3
  [92933f4c] ProgressMeter v0.6.0
  [438e738f] PyCall v1.18.1
  [d330b81b] PyPlot v2.6.0
  [ade2ca70] Dates
  [37e2e46d] LinearAlgebra
  [de0858da] Printf

julia> using PyPlot
WARNING: using PyPlot.axes in module Main conflicts with an existing identifier.
julia> a = rand(Float64,20,20);
julia> figure("Title")
Figure(PyObject <Figure size 640x478 with 0 Axes>)
 cmap = get_cmap("tab20b")
┌ Warning: `linspace(start, stop, length::Integer)` is deprecated, use `range(start, stop=stop, length=length)` instead.
│   caller = show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("image/svg+xml")}, ::Array{ColorMap,1}) at colormaps.jl:161
└ @ PyPlot C:\Users\Carsten\.julia\packages\PyPlot\jXCXB\src\colormaps.jl:161
ColorMap "tab20b"
pcolormesh(a,cmap=cmap)
PyObject <matplotlib.collections.QuadMesh object at 0x000000003072CD68>

So far a plot window opens showing the expected plot, now carry out the follwing leads to a crash

julia> cb = colorbar()

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x58579d53 -- PySet_Contains at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
in expression starting at no file:0
PySet_Contains at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PyObject_Call at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
macro expansion at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\exception.jl:81 [inlined]
__pycall! at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:117
_pycall! at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:30
#pycall#88 at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:16 [inlined]
pycall at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:160 [inlined]
gcf at C:\Users\Carsten\.julia\packages\PyPlot\jXCXB\src\PyPlot.jl:149
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1538 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:563
jl_f__apply_latest at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:601
#invokelatest#1 at .\essentials.jl:691 [inlined]
invokelatest at .\essentials.jl:690
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1538 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:563
_pyjlwrap_call at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\callback.jl:28
unknown function (ip: 0000000001DA5DD4)
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
pyjlwrap_call at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\callback.jl:49
unknown function (ip: 0000000014498711)
PyObject_CallFunctionObjArgs at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PyEval_EvalFrameDefault at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PyObject_CallFunctionObjArgs at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PyEval_EvalFrameDefault at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
Py_CheckFunctionResult at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PySet_Contains at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
PyObject_Call at C:\Users\Carsten\.julia\packages\Conda\m7vem\deps\usr\python36.DLL (unknown line)
macro expansion at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\exception.jl:81 [inlined]
__pycall! at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:117
_pycall! at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:30
#pycall#88 at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:16 [inlined]
pycall at C:\Users\Carsten\.julia\packages\PyCall\uX707\src\pyfncall.jl:160 [inlined]
#colorbar#31 at C:\Users\Carsten\.julia\packages\PyPlot\jXCXB\src\PyPlot.jl:172
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1538 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
colorbar at C:\Users\Carsten\.julia\packages\PyPlot\jXCXB\src\PyPlot.jl:169
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:428
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:682
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:799
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 00000000283B1BDF)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:831
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:633
eval at .\boot.jl:319 [inlined]
#29 at C:\Users\Carsten\.julia\packages\Atom\jJn7Y\src\repl.jl:125 [inlined]
with_logstate at .\logging.jl:397
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
with_logger at .\logging.jl:493
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
top-level scope at C:\Users\Carsten\.julia\packages\Atom\jJn7Y\src\repl.jl:124
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:825
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:633
eval at .\boot.jl:319
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\REPL\src\REPL.jl:117 [inlined]
#28 at .\task.jl:262
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1829
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2182
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1538 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 77756551 (Pool: 77740685; Big: 15866); GC: 177

These few lines were working prior to a PyCall updating today.

**Comment by KristofferC** [comment]
Please report to the `PyCall.jl` package repo (https://travis-ci.org/JuliaPy/PyCall.jl) since it seems that is where the error comes from.

**Comment by KristofferC** [comment]
Sorry, bad link by me! https://github.com/JuliaPy/PyCall.jl

**Comment by cwb0** [comment]
I did it already some minutes ago.
