### ISSUE TITLE
Avast thinks Julia is a virus

### ISSUE THREAD

**Issue by nshusa** [JuliaLang/julia#28840]
Julia version: 1.0.0
Operating System: Windows 10
Both 32-bit and 64-bit installers get this issue
Installation directory: C:\Users\chief\AppData\Local\Julia-1.0.0

Downloaded installer from [https://julialang.org/downloads/](https://julialang.org/downloads/)

Here's my test

32-bit installation
![https://i.imgur.com/UxZZCE7.gif](https://i.imgur.com/UxZZCE7.gif)

64-bit installation
![https://i.imgur.com/mSRcwUC.gif](https://i.imgur.com/mSRcwUC.gif)

**Comment by ViralBShah** [comment]
Any ideas what it takes to make it change its mind?

**Comment by nshusa** [comment]
@ViralBShah I'm not 100% positive, but I don't think Avast likes the way the installer creates temporary files.

The Avast details is not very helpful.
![https://i.imgur.com/w9LTVRt.png](https://i.imgur.com/w9LTVRt.png)

**Comment by Keno** [comment]
Did we forget to sign the installer? Usually signed binaries are exempt from these kinds of detections. cc @ararslan

**Comment by ararslan** [comment]
I think the buildbots sign them and I re-sign them just in case. @nshusa, can you check whether this happens with other versions of Julia, e.g. 0.7 or 0.6? They're available on https://julialang.org/downloads.

**Comment by nshusa** [comment]
@ararslan Just tested on Julia 32-bit version 0.7 installer and works no problem.
![https://i.imgur.com/FRI0UEz.gif](https://i.imgur.com/FRI0UEz.gif)

**Comment by ararslan** [comment]
Okay, good to know. I'll recheck the 1.0 Windows binaries in a bit.

**Comment by ararslan** [comment]
I've signed the Windows binaries again and reuploaded them. Could you try again?

**Comment by nshusa** [comment]
@ararslan The antivirus doesn't show up up, but now I still can't install it. Now it gives me an error and I can't close the program by clicking abort, retry or ignore. I have to use task manager to close the installer.

![https://i.imgur.com/zzU4vIK.gif](https://i.imgur.com/zzU4vIK.gif)

**Comment by saersamani** [comment]
Hi, 

I am having the same issue with julia 1.0.3 64-bit and Avast. It keeps deleting my installation from my PC with Windows 10. 

Thank you very much in advance.

Cheers,
Saer

**Comment by mbauman** [comment]
As far as I can see, we're following Avast's ["Clean" guidelines](https://support.avast.com/en-ww/article/228/).  You could report this as a false positive to Avast here: https://www.avast.com/false-positive-file-form.php.

**Comment by StefanKarpinski** [comment]
Are the binaries signed? That's been a problem in the past.

**Comment by saersamani** [comment]
I reported this to Avast and waiting for the response.

**Comment by ararslan** [comment]
> Are the binaries signed? That's been a problem in the past.

I sign them as part of the release process, but there's always a chance I (or something else) can mess it up. Either way, we shouldn't be identified as a virus.

**Comment by ViralBShah** [comment]
I think people would quickly let us know if binaries were not signed.

**Comment by saersamani** [comment]
The Avast has whitelisted the julia executable. I just received a message from them.

**Comment by JayJay3** [comment]
Julia binary was a virus. I downloaded and installed. Then my Windows 10 file access control information started corrupted. So I had to reinstall Windows plus dozens of other packages. It was a very painful experience! I still havn't fully restored yet.

Probably Julia site was hacked. I have to say that many other people had similar problem I had.

**Comment by Keno** [comment]
Which binary did you download that you believe to be compromised and did you check the fog to make sure you weren't mitm'd?

**Comment by JayJay3** [comment]
I don't know which version I downloaded because I had to reset Windows. So I don't have a copy of that file. But was about a week ago. I am sure it was Julia. I didn't install any other things on that day. After installing Julia, suddenly I could not send emails from Eudora. This traced to contamination of file access control information. I tried to fix it. But problem got bigger and bigger. So I had to reset Windows 10 completely.

The funny thing is that the installer does not suggest to install on normal Windows app directory "C:\Program File. Windows 10 blocks if I tried to install on "C:\Program Files'. So I ran the installer as administrator. After that things got corrupted.

The version I downloaded was a virus.

**Comment by JayJay3** [comment]
PS: 

Exact download date was 11, July, 2019.

**Comment by Keno** [comment]
Unfortunately without knowing where you got the file from, there is nothing actionable her however all officially binaries are provided with signatures of verify validaty and integrity. In addition, we sign these binaries using the appropriate OS mechanism, which is another layer of protection. We've had no other reports of any suspicious binary and I don't see any other evidence of compromise. There is of course also the possibility that the binary was legit, but something went wrong during the install process. We haven't had any reports of such corruption either, but it sounds like there was something unusual about your install, so if you remember additional details, do post those.

**Comment by JayJay3** [comment]
In addition to corruption to file access control information, my email account was spam-listed. But a few days later was lifted. Obviously the virus was monitoring my computer usage and corrupting what I use. I think Avast noticed this.

**Comment by aminya** [comment]
So is there any way to fix this?

**Comment by StefanKarpinski** [comment]
> So is there any way to prevent this from happening? Like contacting Avast or something.

Yes, please do contact Avast and let them know that their product is mistakenly identifying Julia as malware.

**Comment by aminya** [comment]
> 
> 
> > So is there any way to prevent this from happening? Like contacting Avast or something.
> 
> Yes, please do contact Avast and let them know that their product is mistakenly identifying Julia as malware.

Done. Waiting for their response:
https://forum.avast.com/index.php?topic=229447.0

**Comment by aminya** [comment]
Email from AVAST:

Re: Avast: Report a URL https://julialang-s3.julialang.org/bin/winnt/x64/1.3/julia-1.3.0-rc2-win64.exe    [ ref:_00Db0Z3Sf._5000N1y2znT:ref ]:
> Greetings,
> 
> Thank you for contacting Avast with your concerns.
> 
> Our virus specialists have been working on this problem and the provided file has been whitelisted.
> 
> For future reference you might also find the following articles to be useful:
> - Avast Threat Labs - Clean guidelines: https://support.avast.com/en-ww/article/228/
> - Avast Threat Labs - Mobile application clean guidelines: https://support.avast.com/en-ww/article/151/
> 
> Best Regards,
> 
> Ondřej
> The Avast Support Team
> 
>   
>
