### ISSUE TITLE
Constant propagation for tuple in operator only works for first element

### ISSUE THREAD

**Issue by sjoelund** [JuliaLang/julia#28844]
```julia
:a in (:a, :b)
```
Is optimized to `true` in `@code_llvm`, as expected. However, 
```julia
:b in (:a, :b)
```
is not optimized and falls back to iterating over the tuple.

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by haampie** [comment]
Digging into this I found a related issue: `iterate` for Tuple has bounds checks. Removing it like

```diff
-iterate(t::Tuple, i::Int=1) = length(t) < i ? nothing : (t[i], i+1)
+iterate(t::Tuple, i::Int=1) = length(t) < i ? nothing : (@inbounds t[i], i+1)
```

still does not resolve the issue above though.

**Comment by frigaardj** [comment]
Sort of related:
```
foo(x::Int64) = x in (4, 5)
```
This currently doesn't even compile to true when calling `foo(4)` though.

**Comment by nalimilan** [comment]
@frigaardj It can't since the value of `x` isn't known at compile time. That will only be the case if `foo` is inlined in a function which calls it with a literal/constant `4` (like `var() = foo(4)`).

**Comment by frigaardj** [comment]
Oh, yeah, sorry that was me being stupid. Ignore my message - long day..

**Comment by Keno** [comment]
There have been significant improvements to constant prop this year, so this is fixed:
```
julia> f() = :a in (:a, :b)
f (generic function with 3 methods)

julia> @code_typed f()
CodeInfo(
1 ─     return true
) => Bool

julia> g() = :b in (:a, :b)
g (generic function with 1 method)

julia> @code_typed g()
CodeInfo(
1 ─     return true
) => Bool
```

**Comment by giordano** [comment]
Can add a test to avoid regressions, if there aren't already?
