### ISSUE TITLE
Problem using native functions in Julia-1.0.0

### ISSUE THREAD

**Issue by MeBlueDolphin** [JuliaLang/julia#28853]
Hi,

I updated to Julia-1.0.0 yesterday on Windows-10, but am having problems using some basic native functions (e.g. dot, tr, inv, etc.).  For example,

   u = UniformScaling(2)
   ERROR: UndefVarError:  UniformScaling not defined
  Stacktrace:
  [1] top-leve scope at none:0

What am I missing?

Thank you,
Ismail

**Comment by mbauman** [comment]
Questions like this are best asked on the [discourse message board](https://discourse.julialang.org).  This is expected; use version 0.7 to update old code to get deprecation warnings that will tell you how to fix it.  In this case, it's `using LinearAlgebra`.

**Comment by MeBlueDolphin** [comment]
Thank you Matt :)
  And sorry for using the wrong discussion board.
Greatly appreciated,
Ismail
