### ISSUE TITLE
Unknown package dependency problems

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#28851]
More than one user has reported a problem where a dependency in a package seems to be of a lower version when `using` than `test`ing, which seems odd to me so hopefully upstreaming the issue will find a solution?

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/338

**Comment by KristofferC** [comment]
Reopen at Pkg.jl. Likely fixed on master of Pkg but would be good to try. Can try with https://github.com/JuliaLang/julia/pull/28822 to see if it is indeed fixed.

**Comment by ChrisRackauckas** [comment]
Would one easy way to test this be to use the Julia nightly binary?

**Comment by KristofferC** [comment]
No because that PR is not merged

**Comment by ChrisRackauckas** [comment]
Oh I didn't see that. Well I'll see if the users will do it but there's a level of indirection here so 🤷‍♂️ .

**Comment by ChrisRackauckas** [comment]
For reference, the issue seems to be Linux only.
