### ISSUE TITLE
add Base.hasproperty?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#28850]
I just realized that we don't have a `hasproperty(x, s)` function, analogous to `haskey`.   We could define one with the default definition:
```jl
hasproperty(x, s::Symbol) = s in propertynames(x)
```

This came up in https://github.com/JuliaPy/PyCall.jl/pull/517/files#r212317623

**Comment by ararslan** [comment]
Relatedly, a `hasfield` function to accompany `getfield`/`setfield!` may be nice. This definition actually works for that:
```julia
hasfield(T::DataType, name::Symbol) = fieldindex(T, name, false) > 0
```
