### ISSUE TITLE
No `unsafe_string` for `Cwstring`

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#28863]
There is no obvious way to convert `Cwstring` to a Julia `String`:
```
julia> s = "aaa";

julia> a = Base.cconvert(Cwstring,s);

julia> w = Base.unsafe_convert(Cwstring, a)
Cwstring(0x000000010e4d5fd0)

julia> unsafe_string(w)
ERROR: MethodError: no method matching unsafe_string(::Cwstring)
Closest candidates are:
  unsafe_string(::Cstring) at c.jl:193
  unsafe_string(::Union{Ptr{Int8}, Ptr{UInt8}}) at strings/string.jl:56
  unsafe_string(::Union{Ptr{Int8}, Ptr{UInt8}}, ::Integer) at strings/string.jl:52
```

from https://stackoverflow.com/questions/51994365/convert-refcwstring-to-string

**Comment by mgkuhn** [comment]
What is still needed to fix this, other than a pull-request to add your stackoverflow.com solution

```
function Base.unsafe_string(w::Cwstring)
    ptr = convert(Ptr{Cwchar_t}, w)
    ptr == C_NULL && throw(ArgumentError("cannot convert NULL to string"))
    buf = Cwchar_t[]
    i = 1
    while true
        c = unsafe_load(ptr, i)
        if c == 0
            break
        end
        push!(buf, c)
        i += 1
    end
    return String(transcode(UInt8, buf))
end
```

to [c.jl](https://github.com/JuliaLang/julia/blob/master/base/c.jl)?

I just stumbled into this while trying to access the unparsed Windows command line using
```
println("GetCommandLineW = '",
        unsafe_string(ccall( (:GetCommandLineW, "kernel32"), stdcall, Cwstring, () )), "'")
```

**Comment by simonbyrne** [comment]
Please do open a pull request! It would also be good to have an additional method with a `length` argument to support non-null terminated strings.

**Comment by simonbyrne** [comment]
Actually, I don't think what you're proposing will work for UTF-16 (which is `Cwstring` on windows), since codepoints can be made up of one or two code units. I think the only way to avoid copying would be to modify `transcode` to accept an iterator rather than an `Array` so you can do it on the fly.

**Comment by StefanKarpinski** [comment]
Since `transcode` is only meant for Windows APIs where strings are expected to be trivially short, I'm not sure that avoiding a copy is really that necessary. That said, if `transcode` can be modified to support this without much complication that would be ok.
