### ISSUE TITLE
BigInt loss of precision during divide

### ISSUE THREAD

**Issue by gnujosh** [JuliaLang/julia#28862]
I'm having issues with Julia BigInts losing precision after division with some numbers greater than 10^78.  Examples below:

```
a = BigInt(2)^258
b = BigInt(2)^259
c = BigInt(2)^267
println(a)
println(floor(BigInt, a/10))
println(floor(BigInt, a/100))
println(b)
println(floor(BigInt, b/10))
println(floor(BigInt, b/100))
println(c)
println(floor(BigInt, c/10))
println(floor(BigInt, c/100))
```

Gives:

```
463168356949264781694283940034751631413079938662562256157830336031652518559744
46316835694926478169428394003475163141307993866256225615783033603165251855974
4631683569492647816942839400347516314130799386625622561578303360316525185597
926336713898529563388567880069503262826159877325124512315660672063305037119488
92633671389852956338856788006950326282615987732512451231566067206330503711949
9263367138985295633885678800695032628261598773251245123156606720633050371194
237142198758023568227473377297792835283496928595231875152809132048206089502588928
23714219875802356822747337729779283528349692859523187515280913204820608950258944
2371421987580235682274733772977928352834969285952318751528091320482060895025888
```

Note how dividing and flooring properly removes the last few digits in 2^258, it gets incorrect results for 2^259, and appears to get two digits wrong when we go up to 2^267.

This should be a fairly recent version of Julia.  Running versioninfo() gives:

```
Julia Version 1.1.0-DEV.61
Commit 640fc09 (2018-08-19 16:28 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by simonbyrne** [comment]
Ordinary division `/` converts to a floating point type: the promotion rules are such that they will promote to `BigFloat`, which by default has 256 bits of precision, which is about 77 decimal digits.

You can either increase `BigFloat` precision (via `setprecision`), or use a truncating division operator (`div`, `fld` or `cld`, depending on the direction of rounding you desire).
