### ISSUE TITLE
CLI Prompt for package missing

### ISSUE THREAD

**Issue by K-Kent** [JuliaLang/julia#28861]
Windows 10
Julia V1.0.0
When entering the package manager using `]` the prompt is invisible but the package commands are effective. Issuing commands will work but the prompt never appears.

**Comment by K-Kent** [comment]
Yes, i still see the feedback. The cursor moves over a few space from tje
isial position. Typing '?' Goves help on Pkg REPL-mode

**Comment by K-Kent** [comment]
No joy on any start method - did not try WSL
I have an Ubuntu machine and that install works.

**Comment by ararslan** [comment]
When you say "the prompt," do you mean the start of each line of the REPL that asks for input, i.e.
```
(v1.0) pkg>
```
If so, is the background of your terminal by any chance blue? Could be that the text is the same color as the terminal background.

**Comment by K-Kent** [comment]
Success !
The default background color is blue. 
The `(v1.0) pkg>`  prompt is also blue. 
I am having other issues with the default command shell on Windows. 
I should probably switch to WSL
Thanks to all for the quick response !

**Comment by ararslan** [comment]
Sounds like this is resolved then, so I'll go ahead and close this. You should be able to change the background color in the terminal, I would think. As for the other issues you cite, please do report them.

**Comment by K-Kent** [comment]
It should be noted that it if the julia.exe (in the /bin directory) is used instead of the julia.lnk (in the Julia directory) this is not an issue. YMMV
