### ISSUE TITLE
Question: Getting a Fatal IO error 11 with plot on RH Linux 

### ISSUE THREAD

**Issue by MeBlueDolphin** [JuliaLang/julia#28884]
Hi,

   I get a fatal IO error when running any plot command in Julia v1.0.0 on RH Linux.  For example,

       julia> plot(x,y,layout=(4,1))
       julia> <unknown>: Fatal IO error 11 (Resource temporarily unavailable) on X server srvx130:5.0.
 
      ismail%echo $DISPLAY
      srvx130:5.0

   What am I doing wrong?

Thank you,
Ismail

**Comment by yuyichao** [comment]
Please use discourse.julialang.org for question or at least report to the package that provide the `plot` function. It seems like a setup issue though given the X error.

**Comment by MeBlueDolphin** [comment]
Thank you Yuyichao (also for fixing my typos).   

Definitely, a setup issue, as it is working fine on my Windows 10 and Mac OS laptops.   Any useful links to diagnose what I missed in my linux install setup, or any Julia display variables I need to set?

Regards,
Ismail
