### ISSUE TITLE
Error thrown from the julia-client package in Atom

### ISSUE THREAD

**Issue by MuriloZucatelli** [JuliaLang/julia#28895]
I can not use Juno and Julia because the julia-client package fails to load.
Installing “julia-client@0.7.5” failed:
EPERM: operation not permitted, unlink 'C:\Users\user\.atom\packages\julia-client\node_modules\node-pty-prebuilt\build\Release\pty.node'

![image](https://user-images.githubusercontent.com/28695391/44624155-7bd9f600-a8bc-11e8-9b1d-95d8514e120c.png)

**Comment by andreasnoack** [comment]
Please file this issue at https://github.com/JunoLab/Juno.jl
