### ISSUE TITLE
Building on cygwin fails

### ISSUE THREAD

**Issue by mintty** [JuliaLang/julia#28891]
Building on cygwin (native, not for MinGW) fails:

Makefile:303: target '/home/towo/tmp/julia/usr/bin/lib.dll' does not exist
cp  /home/towo/tmp/julia/usr/bin
/bin/cp: missing destination file operand after '/home/towo/tmp/julia/usr/bin'
Try '/bin/cp --help' for more information.
make: *** [Makefile:303: /home/towo/tmp/julia/usr/bin/lib.dll] Error 1

**Comment by Keno** [comment]
Cygwin is not a supported platform. We do however recognize the cygwin tty names, so please try a native build for your purposes.

**Comment by mintty** [comment]
It's not my purpose but your's. In #7267, the Julia community discusses to integrate with a better terminal, considering mintty. This would be seamless if Julia were running on Cygwin.
As you support Linux, I see no essential obstacles to support Cygwin as well.

**Comment by vtjnash** [comment]
Hi! Are you the real MinTTY? There's no need to build Julia against the cygwin dll to get seamless support with MinTTY—it's already fully integrated (as long as we are able to exec the `stty.exe` binary that's usually shipped alongside it). From perusing #7267, the obstacle with shipping MinTTY  has come from its reliance on some posix compatibility layer (e.g. cygwin1.dll) causing packaging headaches when integrating with software that uses a different version of it (e.g. when we used to ship with Git for Windows). Personally, I almost exclusively use Julia on Windows through MinTTY (installed via Cygwin).

Btw, dup #6925 (and others), so I'm going to try to fork this discussion thread back to #7267

**Comment by mintty** [comment]
Ah, so julia calls `stty raw -echo onlcr -ocrnl opost` and catches ^C, ^D from the tty, thus avoiding the signal handling incompatibility. Assumedly it also checks the environment (TERM, LC_*) to adapt properly.
That's fine.
Maybe a small how-to entry on the project page might teach people that this integration works already.
