### ISSUE TITLE
Expand literal_pow to dispatch on non-integers

### ISSUE THREAD

**Issue by platawiec** [JuliaLang/julia#28892]
Currently `x^y` is only lowered to `Base.literal_pow(^, x, Val(y))` if `y` is an integer literal.

If we allow `y` to be non-integral, for instance `x^0.5` or `x^(1/2)`, we can dispatch to `sqrt` through the `literal_pow` machinery. This can also allow us to dispatch to other optimized function calls while still using a natural syntax (e.g. `x^(-1/3)` if we have an optimized inverse cube root).

However, I understand that parsing `0.5` or even `(-1/3)` as a literal might be difficult. Having read the previous discussions of `literal_pow`, I didn't see much talk of non-integral powers, so I'm wondering about the feasibility of this proposal.

**Comment by yuyichao** [comment]
Replacing `x^0.5` with `sqrt` does not change the semantics so this is purely an optimization problem and shouldn't introduce the syntax complexity. It will of course still be better if these could work for user defined types but I feel like something like a `__builtin_constant_p` will be a much more generic mechanism to take advantage of constant input without adding unnecessary branches in generic case.

**Comment by platawiec** [comment]
If I understand correctly, you're saying that `x^0.5` and `sqrt` are equivalent, so it is up to the user to know/optimize the problem with the correct calls?

That's certainly a good position, but, for instance, `x^2` is lowered to `x*x` without the user knowing anything, and my understanding of Stefan's comment [here](https://discourse.julialang.org/t/confusing-difference-literal-vs-variable/13515/6?u=platawiec) is that the overall design goal of achieving mindless plug-and-play optimization for the user is achieved either with "clever optimizations" or syntax specialization, the latter being chosen here. I'm wondering if there is a route to apply the same syntax specialization for non-integral literal powers. Maybe this is what your second sentence is getting at, from a more generic viewpoint than just `literal_pow`.

**Comment by yuyichao** [comment]
> If I understand correctly, you're saying that x^0.5 and sqrt are equivalent, so it is up to the user to know/optimize the problem with the correct calls?

No I'm saying it's the job of the optimizer to do that and shouldn't be in the semantics. New syntax/builtins could be added to allow the user to help the optimizer though.

And no `literal_pow` was not added as an optimization, it's added to completely change the meaning of literal negative power. Allowing optimization in certain case is a sideeffect in the absense of more generic solution but that alone would not justify such a change.

**Comment by platawiec** [comment]
> And no `literal_pow` was not added as an optimization, it's added to completely change the meaning of literal negative power. Allowing optimization in certain case is a sideeffect in the absense of more generic solution but that alone would not justify such a change.

Ok, this is very clear, thanks. To summarize:

1. there is no machinery the user can currently use to dispatch on (non-integer) powers
2. a generic solution would be the preferred way to do so
3. `literal_pow` is not intended to be nor will be that solution

Let me know if I'm missing anything, I appreciate the conversation.

**Comment by StefanKarpinski** [comment]
A straightforward way to do this would be to simply add a special case for `p == 0.5` that calls `sqrt` in the definition of `^`. This would guarantee that `x^0.5` and `sqrt(x)` always behave the same and constant propagation would then cause `x^0.5` to simplify to `sqrt(x)`.

**Comment by platawiec** [comment]
Thanks, constant propagation is very powerful!
