### ISSUE TITLE
for loop consumes extreme amount of memory even though operation can be considered "pure"

### ISSUE THREAD

**Issue by rongcuid** [JuliaLang/julia#28909]
The behaviour is that, even though the loop itself is pure(except for printing), and that results can be safely discarded after execution, Julia still consumes large amount of memory, seeming to keep the entire array being looped over in memory. Ideally, the used items should be freed.

This is the code I used. The goal was to exhaustively search for specific pattern in the entire range of 32-bit random number:

```
using Random
# dice rolling
function ndx!(rng, sp, N)
    L = 0
    for n in 1:N
        L += rand(rng, sp)
    end
    L
end
#generate a sequence
function gensum!(seed)
    rng = MersenneTwister(seed)
    d6 = Random.Sampler(rng, 1:6)
    ndx!(rng,d6,21)
end

l = Threads.SpinLock()
Threads.@threads for i in 0x00000000:0xFFFFFFFF
    s = gensum!(i)
    if (i | 0xFFF00000 == 0xFFF00000)
        lock(l)
        if (i | 0xFF000000 == 0xFF000000)
            if (i | 0xF0000000 == 0xF0000000)
                print(";")
            end
            print(",")
        end
        print(".")
        unlock(l)
    end
    if (s == 126)
        lock(l)
        println("Found Legendary Character, seed ",i)
        unlock(l)
    end
end
```

I did not shrink my example because it cost me 3 hours to run under 12 threads. During the beginning, memory usage climbs up to 15G rapidly, and stays steady throughout the majority of the computation. However, when the computation nears the end (I presume the last minute or so), the memory usage quickly doubles to 30G. 

I cannot explain this behaviour since I am unfamiliar with internal implementation of Julia, but I strongly suspect that it is caused by GC. I did not use alternative loops due to parallel computation, and attempting a `map` operation using `filter(condition,map(f, 0x00000000:0xFFFFFFFF))`immediately throws an out of memory exception(possibly due to the lack of lazy evaluation).

**Comment by rfourquet** [comment]
I don't know if your example reveals a problem with the GC, but clearly this code allocates a lot via creation of `MersenneTwister` objects at each iteration, maybe the GC can't catch up?
A simple work-around seems to be something like:
```julia
const RNGs = [MersenneTwister(0) for i in 1:Threads.nthreads()]

function gensum!(seed)
    rng = Random.seed!(RNGs[Threads.threadid()], seed)
    d6 = Random.Sampler(rng, 1:6)
    ndx!(rng,d6,21)
end
```
(Note that in this example you may also create your `d6` sampler from outside of `gensum!` to compute it only once, as `1:6` is constant here).

**Comment by andreasnoack** [comment]
This discussion is better suited for discourse.julialang.org
