### ISSUE TITLE
Unions with empty tuple causes error in conversions

### ISSUE THREAD

**Issue by arbenson** [JuliaLang/julia#28915]
Minimal working example:
```
TupleType = Union{NTuple{0,Int64},NTuple{1,Int64}}
convert(TupleType, (1,))
```

The error is

> ERROR: BoundsError: attempt to access Tuple{}
  at index [1]
Stacktrace:
 [1] tuple_type_head(::Type) at ./essentials.jl:175
 [2] convert(::Type{Union{Tuple{}, Tuple{Int64}}}, ::Tuple{Int64}) at ./essentials.jl:269
 [3] push!(::Array{Union{Tuple{}, Tuple{Int64}},1}, ::Tuple{Int64}) at ./array.jl:855
 [4] top-level scope at none:0

This error comes up when I want to push tuples of type TupleType to, say, an instance of `Vector{TupleTyple}`.

This was not a problem in 0.6.2 but is a problem in 1.0.

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by Sacha0** [comment]
(Great to see you here Austin! :) 👋)

**Comment by JeffBezanson** [comment]
In this case, the conversion is an identity conversion. Out of curiosity, do you need it to work more generally as well, e.g. `convert(TupleType, (1.0,))`?

**Comment by arbenson** [comment]
No, I wouldn't actually need the more general type conversion of Float to Int for my use case.

My use case is a small library I built for small fixed-size sets. It is used for datasets consisting of a large number of sets of Integers, but each set is small (cardinality between 0 and 5), and the algorithms perform lots of intersections and set creations. I was abstracting the set structure by these tuples (and keeping them ordered internally), which made the set intersections much faster and removed some of the overhead in instantiating Set{Int64}().

**Comment by arbenson** [comment]
Thanks, @JeffBezanson !
