### ISSUE TITLE
dont  work for NOTHING!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by yolanda123a** [JuliaLang/julia#28920]
hello
i have windows 10 64bit
installed julia 1.0 64bit
after go to page and make new julia 1.0 document

for example i write
1+2
and press ALT+enter CTRL+enter Shift+enter
and never give 3

like this

https://imgur.com/EW8xrwv

thanks, because i cant do nothing!!!! and need work for study

and how solve

**Comment by StefanKarpinski** [comment]
Hi @yolanda123a, since you keep opening the same issue and closing it and have been asked to stop several times and post on the [discourse](https://discourse.julialang.org) forums, I'm going to block you from this org. If you want to be unblocked, you can direct message me on discourse.

**Comment by StefanKarpinski** [comment]
GitHub seems to have a feature where you can put a time-limit on a user block, so I've blocked you for three days, after which the block will expire so no need to direct message me on discourse.
