### ISSUE TITLE
maximum! allocates

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#28928]
```julia
X = rand(10,3,4); x= rand(1,3,4);
@btime maximum!($x,$X)
# 452.492 ns (6 allocations: 240 bytes)
```

See https://discourse.julialang.org/t/maximum-allocates/14191.

**Comment by cossio** [comment]
@mbauman Your recent commits are beyond my understanding, so I'm not sure if they fixed the allocations? If so please close this issue.

**Comment by mbauman** [comment]
No, unfortunately I just helped the issue a little bit.  As I mentioned in the commit message itself:

> Alleviates #28928 but does not completely remove allocations due to the allocation of the view that gets passed to `map!`.

Your example is down to just one allocation (for that view). You're on a faster machine than me — my previous was ~670ns.

```julia
julia> X = rand(10,3,4); x= rand(1,3,4);

julia> @btime maximum!($x,$X)
  546.149 ns (1 allocation: 64 bytes)
```

**Comment by KristofferC** [comment]
Don't think this needs to be kept open since it is unlikely that this single allocation is a performance issue.
