### ISSUE TITLE
dont recognize ALT+enter NOTHING

### ISSUE THREAD

**Issue by yolanda123a** [JuliaLang/julia#28921]
ello
i have windows 10 64bit
installed julia 1.0 64bit
after go to page and make new julia 1.0 document

for example i write
1+2
and press ALT+enter CTRL+enter Shift+enter
and never give 3

like this

https://imgur.com/EW8xrwv

thanks, because i cant do nothing!!!! and need work for study

**Comment by yuyichao** [comment]
Please stop

**Comment by yuyichao** [comment]
You are posting to the wrong place. See the link given to you in the first one. Alternatively, if you are not using ijulia but is using the default reply instead, use enter. For other questions, use discourse.julialang.org.
