### ISSUE TITLE
Libssh2 on Windows has outdated ciphers

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#28933]
When using `Pkg` to add repositories with ssh URLs, the ssh connection initiated through libssh2 offer the following ciphers.
Official Windows binaries (64-bit): `aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,arcfour128,arcfour,3des-cbc`
Official Linux binaries (x86 64-bit): `aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,3des-cbc`

All ciphers offered on Windows are outdated and not accepted by a default configured OpenSSH server (at least on Ubuntu and Debian). It has caused failure to add packages from a Bitbucket server, which does work from Linux. The `aesNNN-ctr` ciphers offered on Linux are still effective and the libssh2 bundled with the Windows binaries needs to provide them as well (or some other current alternative).

See https://discourse.julialang.org/t/libssh2-on-windows/14193 for some more discussion.

**Comment by GunnarFarneback** [comment]
I changed `/etc/ssh/sshd_config` on my computer to have `LogLevel DEBUG3` (might be enough with some lower level) and restarted the ssh server, then asked Pkg to add a bogus package with an ssh URL on that host, e.g. from the same computer
```
pkg> add ssh://localhost:foo.jl.git
```
In `/var/log/auth.log` the full conversation gets recorded, where the interesting parts are
```
Aug 28 20:36:00 akka sshd[4119]: debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
Aug 28 20:36:00 akka sshd[4119]: debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com [preauth]
...
Aug 28 20:36:00 akka sshd[4119]: debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,3des-cbc [preauth]
Aug 28 20:36:00 akka sshd[4119]: debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,3des-cbc [preauth]
```
The first group are the ciphers the server is willing to use and the second group those that the client offers (Linux in this case).

**Comment by crstnbr** [comment]
Any update on this? Not being able to `add`/`dev` a package from a private gitlab or else is rather limiting. I'd fix it myself but I have no clue about those ciphers.

**Comment by AsafManela** [comment]
I think I've got the same problem on my windows machine running julia v1.1.
I checked and it is still an issue with current julia nightlies (v1.2-DEV), and the libssh2.dll that comes with it is verison 1.7.0.
It looks like libssh2 released a [new version](https://github.com/libssh2/libssh2/releases) 1.8.2 a few days ago, but it is not available at the link used by the julia [mk file](https://github.com/JuliaLang/julia/blob/master/deps/libssh2.mk): `https://api.github.com/repos/libssh2/libssh2/tarball/$1`

**Comment by AsafManela** [comment]
Correction: version 1.8.2 is available, but these two files specify version 1.8.0 currently:
https://github.com/JuliaLang/julia/blob/06b186771acb9595fe01670557eb978aaf3163d9/deps/libssh2.version#L1-L2
https://github.com/JuliaLang/julia/blob/06b186771acb9595fe01670557eb978aaf3163d9/deps/Versions.make#L24-L25

I tried changing them and building julia again but then got 404 errors in the part of `libssh2.mk` that patches libssh2:
https://github.com/JuliaLang/julia/blob/06b186771acb9595fe01670557eb978aaf3163d9/deps/libssh2.mk#L77-L80
Happy to do more here but clearly requires some guidance.

**Comment by musm** [comment]
@AsafManela  The make file is pulling in libssh2 from binary builder. THe appropriate changes that need to be made are at  https://github.com/JuliaPackaging/Yggdrasil/blob/master/LibSSH2/build_tarballs.jl

**Comment by AsafManela** [comment]
Current dev branch upgraded to libssh 1.8.2 but I still can't pull a package via ssh on windows:
```julia
PS C:\Users\Manela> julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0-DEV.259 (2019-05-21)
 _/ |\__'_|_|_|\__'_|  |  Commit 633ad822ed (0 days old master)
|__/                   |

(v1.3) pkg> dev git@gitlab.com:AsafManela/HurdleDMR.jl.git
  Updating registry at `C:\Users\Manela\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `git@gitlab.com:AsafManela/HurdleDMR.jl.git`
ERROR: failed to clone from git@gitlab.com:AsafManela/HurdleDMR.jl.git, error: GitError(Code:ERROR, Class:SSH, failed to start SSH session: Unable to exchange encryption keys)

(v1.3) pkg> st
    Status `C:\Users\Manela\.julia\environments\v1.3\Project.toml`
  (empty environment)

(v1.3) pkg>
```
any ideas?

**Comment by GunnarFarneback** [comment]
For what it's worth, `https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibGit2/build_tarballs.jl` build depends on libssh2 1.8.0, but I don't know whether that has any significance.

**Comment by GunnarFarneback** [comment]
Those who have run into this issue should also be aware of #32907.

**Comment by GunnarFarneback** [comment]
I have found why 1.8.2 doesn't solve this problem. Support for AES CTR mode was added in https://github.com/libssh2/libssh2/commit/2de14f8f9ac6bb48c0ec596fd501bcec11cedbfc in February 2017 but didn't go into the 1.8.x updates (1.8.0 was released in October 2016), presumably because it is a new feature. It is in 1.9.0 though, released June 20 2019, so another upgrade on the Julia side should have potential to be effective.

**Comment by GunnarFarneback** [comment]
Local testing confirms that libssh2 1.9.0 adds `aes128-ctr`, `aes192-ctr`, and `aes256-ctr` to the offered ciphers, which is sufficient to solve this issue.

**Comment by StefanKarpinski** [comment]
Good. Seems like just updating this dependency should be simple enough.

**Comment by KristofferC** [comment]
Should be fixed with the new libssh2
