### ISSUE TITLE
Can't inspect C-program with embedded Julia in Valgrind

### ISSUE THREAD

**Issue by kim366** [JuliaLang/julia#28945]
Consider this simple code:

```c
#include <julia/julia.h>

int main() {
  jl_init();
  jl_atexit_hook(0);
}
```

When I try to run this program through Valgrind, it errors with

`valgrind: m_debuginfo/debuginfo.c:737 (check_CFSI_related_invariants): Assertion 'cfsi_fits' failed.`

I have briefly checked the source code but was unable to find what `CSFI` even is.

If the `jl_` calls are not present in the program, but the Julia header i still included and the program is still compiled and linked with Julia, the Valgrind issue does not exist.

I am using `--smc-check=all-non-file` as advised by the Julia docs, but I believe that is only relevant for Julia scripts 

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

[Full Valgrind Log](https://pastebin.com/raw/QtHtfvkb)

Should I open the same issue at Valgrind?

For reproduction, I am running

```bash
gcc -c -DJULIA_ENABLE_THREADING=1 -fPIC testing.c && gcc testing.o -ljulia -o testing && valgrind --smc-check=all-non-file ./testing 
```

The code is in `testing.c`

**Comment by kim366** [comment]
For reproduction, I am running

```
gcc -c -DJULIA_ENABLE_THREADING=1 -fPIC testing.c && gcc testing.o -ljulia -o testing && valgrind --smc-check=all-non-file ./testing 
```

The code is in `testing.c`

**Comment by Keno** [comment]
Definitely a valgrind issue, but you may want to try a more up to date version of valgrind first.

**Comment by kim366** [comment]
Hmm, on http://valgrind.org/ it says the current version is 3.13, but I'm running 3.14. I'll open an issue over there, although reproducibility will be harder

**Comment by StefanKarpinski** [comment]
You should downgrade to a version from the present instead of using that sketchy future software 😛

**Comment by kim366** [comment]
That's what the arch repos gave me. I have filed a bug report at valgrind, I'll see what the resolution will be. Need to learn for my drivers license now anyways, not programming :sweat_smile:
