### ISSUE TITLE
Embedding Julia in C on Windows

### ISSUE THREAD

**Issue by NiklasGustafsson** [JuliaLang/julia#28969]
Following the [article](https://docs.julialang.org/en/v1/manual/embedding) on how to embed Julia in C/C++ programs, using Windows, surfaces two problems:

1. The article doesn't really cover using Windows / Visual Studio at all. Since it does work on Windows, I think it would be valuable to add those instructions, too.

2. A few of the symbols exported from libjulia.dll have "__threading" appended to their names. I found that I needed to modify my local copy of julia.h to get the program to link and run:

```C
#ifndef _OS_WINDOWS_
JL_DLLEXPORT void julia_init(JL_IMAGE_SEARCH rel);
JL_DLLEXPORT void jl_init(void);
JL_DLLEXPORT void jl_init_with_image(const char *julia_bindir,
                                     const char *image_relative_path);
#else
JL_DLLEXPORT void julia_init__threading(JL_IMAGE_SEARCH rel);
JL_DLLEXPORT void jl_init__threading(void);
JL_DLLEXPORT void jl_init_with_image__threading(const char *julia_bindir,
	                                            const char *image_relative_path);
#define julia_init julia_init__threading
#define jl_init jl_init__threading
#define jl_init_with_image jl_init_with_image__threading
#endif
```

For jl_init(), specifically, there is also an exported symbol 'jl_init_threading' (just one underscore before 'threading').

**Comment by ViralBShah** [comment]
Would you be able to submit a PR?

**Comment by ViralBShah** [comment]
Ideally this should become part of CI too.

**Comment by NiklasGustafsson** [comment]
I can certainly submit a PR for the 'build using VS' part, but the fixup I made to julia.h locally seems more of a workaround hack than a solution.

**Comment by NiklasGustafsson** [comment]
I have the doc fix in my own fork. Which branch should I submit a PR against? Master?

**Comment by vchuravy** [comment]
Yes master is the correct branch to submit a PR against.

**Comment by yuyichao** [comment]
The change is wrong. You appear to be not using `julia-config.jl` which should give you the `JULIA_ENABLE_THREADING` flag. The change in the symbol name is used to catch exactly this.

**Comment by yuyichao** [comment]
PR for doc about VS compilation is still welcome of course.

**Comment by NiklasGustafsson** [comment]
PR #28974 modifies the documentation, including the need to define JULIA_ENABLE_THREADING. julia-config.jl is not particularly useful with Visual Studio, since it's giving GCC compiler flags.

I forgot to link the PR to this issue.

**Comment by fingolfin** [comment]
I believe this issue can be closed? The documentation seems to cover Windows and Visual Studio these days, and discusses julia-config.jl.

Finally, PR #40637 renamed `jl_init__threading` to `jl_init`, so really all aspects of this seem to be taken care of?

**Comment by NiklasGustafsson** [comment]
I agree.
