### ISSUE TITLE
Inconsistent behaviour for `replace` 

### ISSUE THREAD

**Issue by getzze** [JuliaLang/julia#28967]
Julia Version 1.0.0

Steps to reproduce:
```
a = "1,2,3"
replace(a, "1"=>"0", "2"=>"1")
# MethodError: no method matching replace(::String, ::Pair{String,String}, ::Pair{String,String})
```

When acting on a String, `replace` argument is: `replace(::AbstractString, pat=>r)`, where (quoting from the docs)

>  pat may be a single character, a vector or a set of characters, a string, or a regular expression

On the contrary, when acting on a collection (although Strings are collections): `replace(collection, new_old::Pair...)` with variable number of arguments.

`replace` for Strings should follow the same semantics as for collection (maybe also implementing the version taking a function as argument). But the fact that `pat` can be an array of characters is useful for removing several characters for example.

**Comment by nalimilan** [comment]
Yes, the multiple-pair method is missing. https://github.com/JuliaLang/julia/pull/25732 fixes this.

**Comment by diegozea** [comment]
https://github.com/JuliaLang/julia/pull/25732 hasn't been merged, so this inconsistency behaviour of `replace` between `String`s and `Vector`s remains.

Related issue: https://github.com/JuliaLang/julia/issues/29849

**Comment by o314** [comment]
Hiccup.jl use the macrotools package to do this

```julia
htmlescape(s::AbstractString) =
    @> s replace("&" => "&amp;") replace("<" => "&lt;") replace(">" => "&gt;")
```
but i found it's very overkill there.

**Comment by o314** [comment]
That's simply works
```julia
Base.replace(s::String, oldnews::Pair...) = reduce(replace, oldnews, init=s)

using Test
@test Base.replace("a & b > c", "&"=>"&amp;",">"=>"&gt;") == "a &amp; b &gt; c"
```

**Comment by laborg** [comment]
This has finally been implemented in https://github.com/JuliaLang/julia/pull/40484
