### ISSUE TITLE
Default type deterimined by platform creates Maintenance burden

### ISSUE THREAD

**Issue by jwwb** [JuliaLang/julia#28960]
Allowing the default type to vary by platform will create bugs that wouldn’t exist otherwise. These bugs will exist anywhere the assumption about type size are broken, such as: at module interfaces (one developer assumes 32-bits another 64), anywhere 64-bit integers are needed bit the code is running on a 32-bit platform (but was developed and tested on a 64-bit machine.)

Anyone wanting to write cross-platform code will be forced to use explicitly sized types or test on both/all platforms. This unnecessarily deprives the coder of the benefits of a typeless system. Better to fix the default and allow a module-wide override

**Comment by StefanKarpinski** [comment]
Again, we’re not making breaking changes at this point.
