### ISSUE TITLE
Broadcasting fails on `Expr` objects

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#28961]
I have come to use broadcasting so much that I don't even stop to think about using `.(` syntax anywhere it might be useful.  However, applying `.(` to an `Expr` causes an error:

```
julia> expr = Expr(:a)
:($(Expr(:a)))

julia> println(expr)
$(Expr(:a))

julia> println.(expr)
ERROR: MethodError: no method matching length(::Expr)
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:571
  length(::Base.MethodList) at reflection.jl:728
  length(::Core.MethodTable) at reflection.jl:802
  ...
Stacktrace:
 [1] _similar_for(::UnitRange{Int64}, ::Type, ::Expr, ::Base.HasLength) at ./array.jl:532
 [2] _collect(::UnitRange{Int64}, ::Expr, ::Base.HasEltype, ::Base.HasLength) at ./array.jl:563
 [3] collect(::Expr) at ./array.jl:557
 [4] broadcastable(::Expr) at ./broadcast.jl:609
 [5] broadcasted(::Function, ::Expr) at ./broadcast.jl:1134
 [6] top-level scope at none:0
```

My guess is that we just need to define `length(::Expr) = 1`?

**Comment by martinholters** [comment]
`Expr` can neither be indexed nor iterated, so what should the broadcast do here, anyway? Or is this a request to make `Expr` be treated as a scalar? I.e. `broadcastable(x::Expr) = Ref(x)`?

**Comment by JeffBezanson** [comment]
It's definitely not obvious to me what broadcasting should do to an `Expr`, so an error seems pretty reasonable. @staticfloat can you describe more of the use case?

**Comment by staticfloat** [comment]
I guess this comes down to a philosophical discussion on broadcasting; because broadcasting works on things like symbols, characters, etc... I assumed that anything that wasn't defined to be a "container" would instead be treated as a "scalar".  Things that broadcasting doesn't really make sense for (but is defined anyway) are things like `FloatX`, `IntX`, `nothing`, `missing`, `Symbol`, `Ptr{X}`, etc....  If all of those things can be broadcast over (and treated like scalars) why not have absolutely everything be treated like a scalar, unless it is explicitly enabled?

**Comment by KristofferC** [comment]
See e.g https://discourse.julialang.org/t/recent-broadcast-changes-iterate-by-default-scalar-struct-and/11178

**Comment by staticfloat** [comment]
Thanks Kristoffer, that was a good read.  I just replied with a big comment to that thread, and since this is a philosophical discussion I'll close this issue until something actionable comes out of it.
