### ISSUE TITLE
lmul!(0, A) should replace `NaN` with `0.0`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#28972]
Standard arrays have the feature that `lmul!(0.0, A)` replaces `NaN`s with `0.0`, consistent with BLAS:
```julia
julia> lmul!(0.0,fill(NaN,3,3))
3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
```
This is gone when `generic_lmul!` is called:
```julia
julia> lmul!(0,fill(NaN,3,3))
3×3 Array{Float64,2}:
 NaN  NaN  NaN
 NaN  NaN  NaN
 NaN  NaN  NaN
```

I'd propose fixing this inconsistency by making `generic_lmul!` follow the BLAS convention.

**Comment by raghav9-97** [comment]
I tried to reproduce the problem and got following results
```julia> lmul!(0.0,fill(NaN,3,3))
3×3 Array{Float64,2}:
 NaN  NaN  NaN
 NaN  NaN  NaN
 NaN  NaN  NaN
```
```julia> versioninfo()
Julia Version 1.1.0-DEV.823
Commit c3b2bbb (2018-12-06 10:55 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by dlfivefifty** [comment]
Julia 1.1-pre has actually gone the other way and changed the behaviour for BLAS types. I think this issue can therefore be closed?
