### ISSUE TITLE
Don't print unnecessary stuff when precompiling packages

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#28976]
I think we don't really need the commit hash (appears as random hexadecimal characters to a majority of the Julia users):

Here's an example when doing a first time using:
````
[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
````

The stale cache message could be perhaps simpler too:
````
[ Info: Recompiling stale cache file /Users/viral/.julia/compiled/v1.0/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
````

**Comment by Keno** [comment]
> commit hash

It's not the commit hash. Nevertheless, I agree it's unnecessary to print for unambiguous cases.
