### ISSUE TITLE
Documenting JULIA_DEPOT_PATH for v0.7 in manual/environment-variables.md?

### ISSUE THREAD

**Issue by fsaad** [JuliaLang/julia#28988]
Julia v0.6 used to have the global environment variable `JULIA_PKGDIR`, which in v0.7 seems to be gone in favor of `JULIA_DEPOT_PATH` (https://stackoverflow.com/questions/36398629/change-package-directory-in-julia). Should we document `JULIA_DEPOT_PATH` in [environment-variables.md](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/environment-variables.md)?

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/blob/master/doc/src/manual/environment-variables.md#julia_depot_path
