### ISSUE TITLE
Lowering of dotted calls in a macro

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#28992]
```julia
julia> macro foo(x) x end
@foo (macro with 1 method)

julia> @macroexpand @foo 1 .+ 1
:(1 .+ 1)

julia> @foo 1 .+ 1
ERROR: UndefVarError: .+ not defined
Stacktrace:
 [1] top-level scope at none:0

julia> 1 .+ 1
2
```

It surprised me that the passthrough macro applied to `1 .+ 1` gives an `UndefVarError`.

Why was the dot not lowered to a broadcast call either before the macro received the expression or afterwards? Not sure if this is a bug, but it feels like one.

**Comment by yuyichao** [comment]
Ref https://discourse.julialang.org/t/macro-behaves-differently-than-manually-running-the-output-of-macroexpand/12727/7

**Comment by JeffBezanson** [comment]
Seems to be because `.+` is getting qualified. The macroexpander should probably just skip dot operators.

**Comment by yurivish** [comment]
In the mean time, what is the best way to define a macro that allows this to work? Inspecting whether the string form of a symbol starst with `.` and rewriting it to something else?

**Comment by JeffBezanson** [comment]
Applying `esc` to the whole expression or just to `.+` should make it work well enough for now.

**Comment by JeffBezanson** [comment]
We can come up with a hack to fix this in a non-breaking way, but triage also feels changing the parsing would be a fairly minor change and could probably go in 1.x.

**Comment by mbauman** [comment]
To expand just a little bit more: right now we have two parsed representations of a dot-call:

```
julia> Meta.show_sexpr(:(x .+ y))
(:call, :.+, :x, :y)
julia> Meta.show_sexpr(:((+).(x, y)))
(:., :+, (:tuple, :x, :y))
```

The minor change would be to standardize the two to dot-head expression type, which macros need to handle in any case.  Note that there was a deprecation in the way of doing this for 0.7.

**Comment by JeffBezanson** [comment]
Chained comparison complicates this. It's straightforward to parse `x .+ y` as `(dotcall + x y)`, but how to parse e.g. `a .< b < c .< d`?

**Comment by JeffBezanson** [comment]
Another parsing idea: parse `.+` as `(dotted +)`. You can't evaluate a `dotted` expression by itself, but it will turn enclosing calls and comparisons into broadcasts. That makes it easy to rename the `+` inside.

**Comment by StefanKarpinski** [comment]
I wonder if that would help with the occasional desire to use `.+` as an operator by itself, e.g. `map(.+, vs, ws)` where `vs` and `ws` are collections of arrays, pairs of which you want to add pairwise. Currently this has to be written as `map((v, w) -> v .+ w, vs, ws)` which is fine but it would be cool if `map(.+, vs, ws)` worked.

**Comment by JeffBezanson** [comment]
True; `(dotted +)` could lower to something like `(args...)->broadcast(+, args...)` in other contexts.

**Comment by mbauman** [comment]
I like it.  It also gives us a direction (if not yet a top-level syntax) for multi-level broadcasts with `(dotted (dotted +))`.
