### ISSUE TITLE
improve performance of `rand(n:m)`

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#29004]
A recently published algorithm is unbiased and more performant than `rand(n:m)`.

See https://discourse.julialang.org/t/rand-1-10-vs-int-round-10-rand/14339/10.

**Comment by affans** [comment]
Reference issue on the speed of `rand()` https://github.com/JuliaLang/julia/issues/20582

**Comment by rfourquet** [comment]
Closed by #29240.
