### ISSUE TITLE
"3.0 == 3.0000000000000001" returns true

### ISSUE THREAD

**Issue by treeww** [JuliaLang/julia#29009]
3.0 is not equal to 3.0000000000000001 but Julia thinks so.
```
julia> 3 == 3.0000000000000001
true

```

**Comment by treeww** [comment]
```
julia> 3.0000000000000000 == 3.0000000000000002
true

```

**Comment by fredrikekre** [comment]
https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678/4

**Comment by rickhg12hs** [comment]
Using `Float64` ([IEEE-784 Double Precision Floating Point Format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)), `3.0000000000000001` cannot be represented exactly.  See documentation for other number representations, limitations, etc.
