### ISSUE TITLE
Documentation of Pkg.activate is somewhat incomprehensible

### ISSUE THREAD

**Issue by aviks** [JuliaLang/julia#29008]
The documentation of `Pkg.activate` states:

_If s is a package name in the current project activate that is tracking a path, activate the environment at that path_

I do not understand what that sentence means.

**Comment by 00vareladavid** [comment]
I think there is just an extra "activate" in there.

I'm pretty sure the intention was:
> If s is a package name in the current project ~activate~ that is tracking a path, activate the environment at that path

**Comment by KristofferC** [comment]
Issue moved to [JuliaLang/Pkg.jl #707](https://github.com/JuliaLang/Pkg.jl/issues/707) via [**ZenHub**](https://www.zenhub.com/)
