### ISSUE TITLE
Codegen: Reading a big field from a mutable struct generates unnecessary stack copy

### ISSUE THREAD

**Issue by simonfxr** [JuliaLang/julia#29000]
The code generated for loading big fields is currently very bad. Here is a small example:
```julia
mutable struct Mut
    data::NTuple{10, Int}
end

struct Immut
    data::NTuple{10, Int}
end

load(x, i::Int) = @inbounds x.data[i]
```
Comparing the generated code (on the offial julia-0.7.0 linux x64 binaries):
`code_native(load, (Immut, Int))`
```
mov	rax, qword ptr [rdi + 8*rsi - 8]
ret
```
with:
`code_native(load, (Mut, Int))`
```
movups	xmm0, xmmword ptr [rdi]
movups	xmm1, xmmword ptr [rdi + 16]
movups	xmm2, xmmword ptr [rdi + 32]
movups	xmm3, xmmword ptr [rdi + 48]
movups	xmm4, xmmword ptr [rdi + 64]
movaps	xmmword ptr [rsp - 88], xmm0
movaps	xmmword ptr [rsp - 72], xmm1
movaps	xmmword ptr [rsp - 56], xmm2
movaps	xmmword ptr [rsp - 40], xmm3
movaps	xmmword ptr [rsp - 24], xmm4
mov	rax, qword ptr [rsp + 8*rsi - 96]
ret
```
In the mutable case, the tuple is first copied to the stack and then loaded from there.
This currently makes `MArray` (from `StaticArrays`) very slow in some cases, e.g. `sort!` slows down proportional to the size of the MArray. It would be possible to do the loads through a pointer, but this inhibits a lot of optimisations on the Julia side.

I looked at the emitted llvm code, and in the difference is apparently, that in the mutable case Julia generates `alloca + load + store` and in the immutable one just a `getelementptr`, LLVM is not able to optimize this code.

**Comment by chethega** [comment]
I think `MArray` used to avoid this problem by using `load(x::Mut,i) = unsafe_load(reinterpret(Ptr{Int64},pointer_from_objref(x)),i)` and emit tight code for `getindex` and `setindex!`. That being said, I also observe the bad code on 1.0, so this issue should probably go there as well.

I think the hope was that llvm would eventually learn to avoid the stack copy, and Keno was considering an upstream fix at some point?

So I'm pretty sure the general issue is duplicate and goes back several years, but I currently can't find the other entries. Maybe this should also be documented better in the performance tricks (one should access single elements of large heap-allocated immutables through pointers, not through `getindex`).

**Comment by simonfxr** [comment]
Okay, I see. I already had a hunch that this might me a known problem, but couldn't find anything. Loading through a pointer is possible, but as I have sad, I would like to avoid that, since it confuses the Julia IR optimizer. Regarding LLVM: I wrote a small (hopefully) equivalent C example and fed it to different compilers on [](https://godbolt.org/) (Clang, GCC, MSVC, Intel) , not a single one gets rid of the stack copy. However I'm not sure this is even a valid optimisation given C's semantics.

Another possibility would be to introduce something like Clang's __builtin_constant_p, we could then generate different code for literal and non literal indices, allowing the Julia optimiser to do its work. Would it be hard to add something like this to Julia's constant propagation? It would also be pretty useful in other scenarios like `getproperty()`, `setproperty`, math expressions (e.g. as an alternative to `literal_pow()` we could even build an entire ecosystem to optimize all kinds of code (String/Array functions, e.g. concatenation of constants). The possibilities are endless :-).

NB: Here is the c code mentioned earlier:
```C

typedef struct
{
    int data[16];
} Big;

typedef struct
{
    Big field;
} Foo;

int
getindex(const Foo *foo, int i)
{
    Big b = foo->field;
    return b.data[i];
}
```

**Comment by chethega** [comment]
See also [https://github.com/JuliaLang/julia/issues/27715](https://github.com/JuliaLang/julia/issues/27715). Merge issues?

**Comment by vtjnash** [comment]
yes, mark as dup
