### ISSUE TITLE
Base.LOAD_CACHE_PATH : ERROR: UndefVarError: LOAD_CACHE_PATH not defined

### ISSUE THREAD

**Issue by albeiroep** [JuliaLang/julia#29007]
Hello wonderful Julia community. I'm trying to access the `Base.LOAD_CACHE_PATH` variable in Julia 1.0 but i receive the error  

**ERROR: UndefVarError: LOAD_CACHE_PATH not defined.**

It's strange because when i try to access `Base.LOAD_PATH`, it works, the console shows the information. So i don't understand what's happening with the `Base.LOAD_CACHE_PATH` variable, it's very strange for me. 

Also, when i try to execute `Pkg.add("PyCall")` in the Julia console it doesn't work, i get an undefined variable error too. So i have to open directly the pkg module to install packages.

Thank you so much.

**Comment by KristofferC** [comment]
`LOAD_CACHE_PATH` was removed in https://github.com/JuliaLang/julia/pull/26165
