### ISSUE TITLE
a query over an executable that spits out a list of uses of unsafe method

### ISSUE THREAD

**Issue by sgt101** [JuliaLang/julia#29013]
Hi, I note unsafe_store and unsafe_load (for example). Also the "don't expose unsafe operators at an interface level". It's obvious that to deal with the two languages problem Julia needs these features, but if I am building (what I think might be) safe code then I would like to be able to check to see what libraries that I have used have made use of these features. I know that it will be true that many databases and so on will use these features, but I want to be able to encapsulate the unsafe parts of my codebase and to be able to talk about them in terms of risk (and to investigate and attempt to underwrite said risk), y'know - like an engineer and stuff. Anyway - is this a hard thing to implement (a query over an executable that spits out a list of uses of unsafe method - possibly excluding Base?)

**Comment by yuyichao** [comment]
It's unclear what **exactly** you mean. (i.e. what count as unsafe operations for you, what risk are you talking about. e.g. is a "safe" wrapper of "unsafe" method unsafe?).

Anyway, in general, base provides the reflection tools to do querys of the kind you want so there's no point for having that in base. Further discussion should go to discourse.julialang.org.

P.S. Please avoid typing everything into a single line title.
