### ISSUE TITLE
Multiplication of sparse matrices could be faster (2x - 3x) with a small change

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaLang/julia#29022]
The current sparse matrix multiplication function sorts the indices with the option `:sortcols`.

But using the `:doubletranspose` option, the matrix multiplication is about 2x to 3x faster in the benchmarks I made. The speed is then comparable to GNU Octave 4.0.0. Cholmod uses also the double transpose to sort the indices.

| N | julia - sort cols (default) | julia - double transpose | octave |
|--:|:---------------------|-------------------------:|-------:|
| 10000 |     2.720 ms (30019 allocations: 3.13 MiB)       |   0.788709 ms (28 allocations: 1.76 MiB)    | 3.12185 ms |
| 100000 |    29.656 ms (300019 allocations: 31.28 MiB)    |   9.119 ms (28 allocations: 17.55 MiB)     | 14.039 ms   |
| 1000000 |   445.464 ms (3000019 allocations: 312.81 MiB) |   174.792 ms (28 allocations: 175.48 MiB)  | 116.564 ms   |

Could `:doubletranspose` be made the default option?

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

julia script

```julia
using SparseArrays
using BenchmarkTools


println("sort indices")
fun(S) = S*S';
for N = [10000 100000 1000000]
    S = spdiagm(0 => ones(N), 1 => -ones(N-1));
    @show N
    @btime fun($S);
end

println("double transpose")
fun2(S) = SparseArrays.spmatmul(S,copy(S'),sortindices=:doubletranspose)
for N = [10000 100000 1000000]

    S = spdiagm(0 => ones(N), 1 => -ones(N-1));
    @show N
    @btime fun2($S);
end
```

Octave/matlab script:

```matlab
for N = [10000 100000 1000000]
   S = spdiags([ones(1,N); -ones(1,N)]',[0,1],N,N);
   N
   tic; A = S*S'; toc
end
```

**Comment by stevengj** [comment]
See also #8316.

**Comment by KristofferC** [comment]
Using https://www.cise.ufl.edu/research/sparse/matrices/Wissgott/parabolic_fem.html I get

```jl
using MatrixMarket
using SparseArrays

urls = [
"https://www.cise.ufl.edu/research/sparse/MM/Wissgott/parabolic_fem.tar.gz",
]

for url in urls
    filename = basename(url)
    if !isfile(filename)
        download(url, filename)
        run(`tar -xvf $filename`)
    end
end


fun(S) = S*S';
fun2(S) = SparseArrays.spmatmul(S,copy(S'),sortindices=:doubletranspose)

for url in urls
    path = split(basename(url), ".")[1]
    M = MatrixMarket.mmread(joinpath(path, path*".mtx"))
    println(path)
    @time fun(M)
    @time fun2(M)
end
```

```
  0.785875 seconds (1.58 M allocations: 396.785 MiB, 15.31% gc time)
  0.875573 seconds (10.84 k allocations: 452.956 MiB, 15.98% gc time)
```

so it doesn't seem like a completely clear cut choice?

**Comment by KristofferC** [comment]
@Alexander-Barth could you rerun the benchmarks with https://github.com/JuliaLang/julia/pull/29682 and see if the result change?

**Comment by Alexander-Barth** [comment]
Thank you for looking into it.  I rerun the benchmarks with Julia master compiled from source with the patch #29682 applied.

| N  |  julia   1.1.0-DEV.468 with patch #29682 |
|---|------------------------------------|
| 10000 |   838.068 μs (26 allocations: 1.45 MiB) |
| 100000  |  8.699 ms (26 allocations: 14.50 MiB) |
| 1000000 |  154.708 ms (26 allocations: 144.96 MiB) |

This is really great and a significant improvements. Thanks a lot!

**Comment by KristofferC** [comment]
I would say https://github.com/JuliaLang/julia/pull/29682 closes this.
