### ISSUE TITLE
Julia crashes on any package command

### ISSUE THREAD

**Issue by fbryandavies** [JuliaLang/julia#29027]
All versions of Julia worked on my Windows 10 machine.  Recently I have tried julia 0.6.4, julia 0.7.0, and julia 1.0.0.  They install with no issues.  However, almost any command related to package versions, building, or updates crashes the Julia terminal window.  I include one example here that doesn't crash the window.  I notice that the environments directory never gets created.  I have uninstalled and installed many times.  I have the julia bin directory in my path.  
I apologize if this isn't a bug - I'm a geophysicist, not a computer scientist.  
![julia-update](https://user-images.githubusercontent.com/5050093/45003184-ba9f3880-afad-11e8-8431-c1d95503c93a.PNG)

**Comment by 00vareladavid** [comment]
Have you read the [Pkg documentation](https://docs.julialang.org/en/latest/stdlib/Pkg/)?

My guess as to why you are seeing that error is that you do not have julia's `PyPlot` package installed. If this is not a bug but you have further usage questions, [discourse](https://discourse.julialang.org/) is a much better place to ask.

**Comment by fbryandavies** [comment]
I was afraid that might mislead you. I used it as an example because I use PyPlot a lot. It was just an example that keeps the repl open.  Probably a bad example.  A simpler issue is just ] up.  It says Resolving package versions and then the window completely disappears.  If I run the same thing in Atom, the message stays, but it hangs and there is no further output.

**Comment by 00vareladavid** [comment]
Ok, I don't think that should happen. What about`] status`? That should at least tell us if the environment is being created correctly

**Comment by fbryandavies** [comment]
I do think it is to do with the environment.  ] status provides:
C:\Users\****\.julia\environments\v1.0\Project.toml

The thing is that the environments directory is not getting created so this file doesn't actually exist.  I have another Windows 10 laptop that does work correctly (environments folder does exist) so I know the binary download is fine.

**Comment by MoonCoral** [comment]
Does the .\julia\registries\General folder and its contents exist?

**Comment by fbryandavies** [comment]
Yes General does exist, and content looks reasonable.
However, the only top level (.julia) folders are clones, dev, logs, and registries i.e. no environments, packages, lib or environments folder exist.

**Comment by 00vareladavid** [comment]
The first command that requires a certain file/directory should take care of creating it. Your first (`update`) example is working as intended (given you do not have `PyPlots` installed). 

Can you give a sequence of `Pkg` commands which cause the Julia process to fail?

**Comment by MoonCoral** [comment]
open a command prompt (cmd.exe or powershell) and type julia. The console should then stay open even after julia crashes.

**Comment by 00vareladavid** [comment]
Yeah, sorry, I just realized that. I'm not sure what "window" you are reffering to. Can you run the failing command in a standalone terminal? So we can determine whether it is `Pkg` or atom is failing

**Comment by fbryandavies** [comment]
Sorry - the window that stays up is the repl window in Atom.  

Running from the command prompt exits Julia but isn't providing any additional output.

**Comment by fbryandavies** [comment]
What command should be run so Julia generates the environments directory

**Comment by 00vareladavid** [comment]
Try running `] add Example`. It should automatically create the environments directory and the `Project.toml` file.

**Comment by MoonCoral** [comment]
There should be a debug version of Julia in the bin folder which may give more information.

**Comment by ararslan** [comment]
We actually no longer ship debug binaries as of 0.7.

**Comment by fbryandavies** [comment]
I only see one Julia app in bin - BTW its Julia 1.0.0

**Comment by MoonCoral** [comment]
My bad

**Comment by fbryandavies** [comment]
] add Example behaves the same way - says Resolving package versions and exits Julia.  The environments directory is not created.

**Comment by KristofferC** [comment]
It will only be created after it is successfully  added. What is needed is a backtrace which you can get if you open julia from a powershell or cmd terminal window instead of directly clicking on the executable. Then the window should persist.

**Comment by fbryandavies** [comment]
My confusion is that powershell, or cmd makes no difference - it exits julia at resolving package versions - see below
![julia2](https://user-images.githubusercontent.com/5050093/45004719-01485f00-afbd-11e8-9dab-699eef6dbfa8.PNG)

**Comment by KristofferC** [comment]
Oh... That is unfortunate. It usually gives something at least.

**Comment by MoonCoral** [comment]
You could try to copy a Manifest and Project file from your working machine over and do `] instantiate` either in the hope of getting a helpful error or having a, admittedly clunky, workaround

**Comment by fbryandavies** [comment]
Unfortunately that does the exact same thing ...
![image](https://user-images.githubusercontent.com/5050093/45006062-11643c80-afc5-11e8-9fdc-b2ab82c0f774.png)

**Comment by fbryandavies** [comment]
@MoonCoral I actually tried that earlier, but I didn't know about the instantiate.  I tried that and it seemed to kick me out of Julia as well.  It must be something basic about my environment, but I just don't know what it could be
![image](https://user-images.githubusercontent.com/5050093/45006307-28575e80-afc6-11e8-9ec8-cce3bf458c43.png)

**Comment by fbryandavies** [comment]
So from the powershell this time I did get traceback! Thanks for that. 
![julia3](https://user-images.githubusercontent.com/5050093/45007927-fea23580-afcd-11e8-9910-81d6b9192e70.PNG)

**Comment by 00vareladavid** [comment]
From my limited understanding: `Pkg` seems to be triggering an out of bounds memory access on Windows? Seems like a job for the big guns(i.e. definitely not me :sweat_smile:), although I don't know if we have enough information to hunt down the bug.

**Comment by fbryandavies** [comment]
Well I will keep trying to pry a few more clues - and thanks

**Comment by 00vareladavid** [comment]
Welcome

**Comment by JeffBezanson** [comment]
Thanks for pursuing this. It's definitely a frustrating issue and I hope we can do something about it. Is there anything unusual about how your home directory is set up?

**Comment by fbryandavies** [comment]
Not that I'm aware if. it should just be the standard set up.

**Comment by fbryandavies** [comment]
OK - it seems solved. I started to simplify my windows10 path by incrementally removing the (few) items in the path - noticed that java was still in the path even though I had uninstalled it earlier. After deleting Java, Julia worked immediately. Atom went through a long re-initialise re-compile? But all well now!

Thanks to all who helped a frustrated geophysicist

**Comment by KristofferC** [comment]
Please reopen on https://github.com/JuliaLang/Pkg.jl if this is still a problem.
