### ISSUE TITLE
Document active_project()

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#29030]
Figuring out the current active project programmatically seems to be undocumented at the moment, but there is `Base.active_project()`. Perhaps it should get documented and become part of the public API?

**Comment by tpapp** [comment]
Also, how is it different from `Base.current_project()`?

**Comment by KristofferC** [comment]
AFAIU, `current_project()` answers, "if I where to `Pkg.activate(pwd())`, what would be the path to the active project".

**Comment by mortenpi** [comment]
> `current_project()` answers, "if I where to `Pkg.activate(pwd())`, what would be the path to the active project?"

This does not appear to be exactly accurate: if you have `foo/Project.toml`, but `pwd() == "foo/bar/"` (no `Project.toml` there), then `current_project() == "foo/Project.toml"`, but `Pkg.activate(pwd())` activates `foo/bar/Project.toml`. In fact, even after activating `pwd()`, `current_project()` is still `"foo/Project.toml"`, since activation doesn't create a `Project.toml` file.

Other than possibly being used internally in `Pkg`, I can't really think of a use case for `current_project()` at the moment. Maybe it should be dropped from Base altogether?

**Comment by KristofferC** [comment]
It is used to figure out what project should be active if `@.` (or no argument) is used for the `--project` flag though, right?

**Comment by laborg** [comment]
Closed by https://github.com/JuliaLang/julia/pull/38234
