### ISSUE TITLE
error in `convert` for `Diagonal`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#29054]
Playing with #29052, I discovered this:
```
julia> convert(Diagonal{Int,Vector{Int}}, Diagonal(1:4))
ERROR: MethodError: no method matching Array{Int64,1}(::Diagonal{Int64,UnitRange{Int64}})
```

The reason is that the only constructor for instantiated Diagonal types like `Diagonal{Int,Vector{Int}}` (the "inner" constructor) expects its argument to be a vector. `Diagonal(x)` accepts both vectors and matrices.

This could be fixed by adding another inner constructor. Or we could add `convert` methods, since it seems at least conversion should work. Also we could add `::AbstractVector` to the argument of the current inner constructor.

**Comment by mcognetta** [comment]
These should be defined individually for all of these matrices (`Bidiagonal`, `Tridiagonal`, etc) right?
If this is the case, adding

`Diagonal{T, V}(A::Diagonal) where {T, V<:AbstractVector{T}} = Diagonal(convert(V, A.diag))` and analogous ones for the other types should be sufficient.

**Comment by ViralBShah** [comment]
```
julia> convert(Diagonal{Int,Vector{Int}}, Diagonal(1:4))
4×4 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅
 ⋅  ⋅  3  ⋅
 ⋅  ⋅  ⋅  4
```
