### ISSUE TITLE
Docs: Julia version dropdown missing from top left menu in documentation for v0.5.2 and older

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#29051]
There's no other obvious indication of the version relevant for the docs (apart from the URL), so that being missing is an obvious source of confusion

https://docs.julialang.org/en/v0.6.0/ <-present
https://docs.julialang.org/en/v0.5.2/ <-missing
https://docs.julialang.org/en/v0.4.7/ <-missing

**Comment by KristofferC** [comment]
Those docs were generated using a completely different system and did not have the drop down.

Perhaps we should inject a warning or something in the old docs to highlight that they are for old julia versions.

**Comment by ianshmean** [comment]
I think a warning is a good idea.. especially given how high some of the the v0.4.7 pages currently rank in google (for me at least)

**Comment by fredrikekre** [comment]
This will be fixed with the next Documenter update. In particular see https://github.com/JuliaLang/julia/issues/26825#issuecomment-413450489. Closing as dup of #26825
