### ISSUE TITLE
`Base.open` documentation error

### ISSUE THREAD

**Issue by lucatrv** [JuliaLang/julia#29067]
Documentation of [`Base.open(command, stdio=devnull; write::Bool = false, read::Bool = !write)`](https://docs.julialang.org/en/v1/base/io-network/#Base.open) function is not aligned with current [implementation](https://github.com/JuliaLang/julia/blob/e7d15d4a013a43442b75ba4e477382804fa4ac49/base/process.jl#L574-L582), which returns `processes`.

See:
> Start running command asynchronously, and return a tuple (stream,process).

**Comment by fredrikekre** [comment]
Funny coincidence, #25563 ficed this just 2 hours ago.

**Comment by lucatrv** [comment]
Maybe just when I hit on it, that's good timing :)
