### ISSUE TITLE
Signal (11): Segmentation Fault on Raspberry Pi 3B+ running Raspbian

### ISSUE THREAD

**Issue by ChristianF88** [JuliaLang/julia#29088]
Hi,

I do have the following issue:

Julia crashes as soon as I produce an error (e.g. if I execute 3+"a").
So julia starts fine.
That's the error message:

```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
Segmentation fault

```

my version info is:

```
Julia Version 0.6.0
Platform Info:
  OS: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 4 (v7l)
  WORD_SIZE: 32
  BLAS: libopenblas (NO_LAPACKE NO_AFFINITY ARMV6)
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, generic)
```

Ps: Just to find out whether its my linux setup. I reinstalled raspbian and then julia. Same thing happend. I also tried the raspbian light version. Same issue.

Thank you for your help!

Christian

**Comment by JeffBezanson** [comment]
How did you install julia?

**Comment by ChristianF88** [comment]
hey, as described here:

https://juliaberry.github.io/

simply:

`
sudo apt update
sudo apt install julia
sudo apt install libzmq3-dev
`

I did not install jupyter, since I had it installed beforehand.

**Comment by ViralBShah** [comment]
Can you try the arm binaries from julialang.org?

We will update the instructions on JuliaBerry.

**Comment by ChristianF88** [comment]
these?

https://julialang.org/downloads/platform.html#generic-binaries

...will try now
