### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [JuliaLang/julia#29081]
I suggest to reuse a higher level build system than [your current make script](https://github.com/JuliaLang/julia/blob/4c02077a3a88f7d28dfa6f8d839f3483dceda84b/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by KristofferC** [comment]
See discussion in https://github.com/JuliaLang/julia/issues/1832 and also https://github.com/JuliaLang/julia/pull/9422, https://github.com/JuliaLang/julia/pull/11645. Don't think there needs to be a dedicated issue open about this.

**Comment by musm** [comment]
See also cmake pr https://github.com/JuliaLang/julia/pull/11754
