### ISSUE TITLE
Style guide conflict

### ISSUE THREAD

**Issue by dan87134** [JuliaLang/julia#29096]
Two of the examples in the "Variables" section of the documentation conflict with the style guidance later in the same section.

```jl
julia> Z = "My string"
"My string"
```

and

```jl
julia> UniversalDeclarationOfHumanRightsStart = "人人生而自由，在尊严和权利上一律平等。"
"人人生而自由，在尊严和权利上一律平等。"
```

Both of these variable names use capital letters.

The style guidance says that variable names should always be in lower case and use underscores when the variable consists of a sequence of words that would be hard to read without using underscores.

I point this out because it it is easy to for someone new (like me :-) ) to miss the guidance at the end of the section about lower case for variable names and end up making names like `PrimeInstance` and then later have to clean things up. Cleaning up variable names is probably the most tedious programming task there is.

The style guidance would be strongly implied if the second example above was `universal_declaration_of_human_rights_start` (and the first, of course, was `z`)

**Comment by pepsiman** [comment]
This is deliberate, as the section is demonstrating that case has no semantic meaning:
"Variable names are case-sensitive, and have no semantic meaning (that is, the language will not treat variables differently based on their names)."

**Comment by dan87134** [comment]
I understand what you are trying to get across so  this is really just me being me. I think what is going on with Julia is great as is as much of the documentation that I have gotten through so far.

I think style is very important to making programs readable and making it easier to learn.  I think the doc's should explicitly mention that even though Julia allows some of these examples like "Z" and "Univer..." they shouldn't be used in practice because they don't conform to the common conventions used in writing Julia programs that will be discussed later.

As is the first thing someone, maybe a new programmer, learns in this documentation is that you can use anything for names in Julia... then at end of the has to unlearn that, if they even notice the styling section. The thing about no semantics in names is important for Julia language implementors but not so much for programmers.

Semantics in names, even they are not enforced, are what make programs readable. If you saw a program using variable names like "A", "B", "C" and so on you probably not want to support it (or maybe it  was just an old Basic program :-)). That's why most languages/projects end up with a styling guide.

**Comment by KristofferC** [comment]
Semantics,  here,  means the effect it has on program execution. In some language (Fortran) the name of the variable does impact the semantics since different starting letters of the variable implicitly also sets the type of the variable.

**Comment by JeffBezanson** [comment]
However we update the documentation here, it should not imply that uppercase should never be used. For example single uppercase letters are commonly used for matrices, and there's nothing wrong with that.
