### ISSUE TITLE
Windows cross-compile build process picks up wrong mingw runtime libraries

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#29103]
On a fresh build, setting `CC` to the mingw posix variant (since the win32 variant fails to build LLVM), I get:
```
wine: Call from 0x7bc5bf2c to unimplemented function libstdc++-6.dll._ZNSt6thread20hardware_concurrencyEv, aborting
002b:err:module:attach_dlls "LLVM.dll" failed to initialize, aborting
002b:err:module:attach_dlls Initializing dlls for L"Z:\\home\\keno\\julia-win64-nononsense\\usr\\bin\\julia.exe" failed, status 80000100
```
This is because our build process ignores an explicitly set `$(CC)` when determining where to copy the runtime libraries from and ends up picking up the -win32 variants instead.

**Comment by vtjnash** [comment]
Sounds strange—don’t we explicitly ask CC for its library search path?

**Comment by Keno** [comment]
No, we ask `$(CROSS_COMPILE)gcc` which is the wrong compiler.
