### ISSUE TITLE
Windows Install path and environment path

### ISSUE THREAD

**Issue by ghost** [JuliaLang/julia#29106]
When installing Julia under Windows ( non-admin ), it installs by default under:

> C:\Users\UserName\AppData\Local\Julia-1.0.0

After this the only way to access Julia is by running the Julia Shortcut. Julia does not get added to the systems environment path, making it impossible to access Julia from CLI ( unless you manually change paths ).

Most other languages add there binary locations to the Windows path.

The following install path needs to be added automatically to the path by the installer:

> C:\Users\Benny\AppData\Local\Julia-1.0.0\bin

This path also breaks the default installation behavior. One expect Julia to install under:

> C:\Program Files (x86)
or
> C:\Program Files

Not under the hidden AppData locations...

**Comment by thchr** [comment]
Just a slight bump for this issue, by way of a reference to a recent [discourse discussion](https://discourse.julialang.org/t/what-is-the-best-way-to-set-the-path-to-julia-on-windows-10/16467/10). What's the reason for the current, at face value, strange Windows install location?
