### ISSUE TITLE
[manual, docs] possible bad `ssh` parameter in Parallel Computing manual

### ISSUE THREAD

**Issue by proflage** [JuliaLang/julia#29101]
hello,

In [Network Requirements for LocalManager and SSHManager
 section](
https://docs.julialang.org/en/v1/manual/parallel-computing/#Network-Requirements-for-LocalManager-and-SSHManager-1), I'm afraid the right sshflags parameter is `-i` instead of `-e`:

..."Authentication credentials can be supplied via sshflags, for example sshflags=`-e <keyfile>`."...

[SSH manual](https://man.openbsd.org/ssh).

**Comment by StefanKarpinski** [comment]
Yes, that does appear to be correct. Care to take a crack at fixing it? You can do it online through the GitHub editing interface even :)

**Comment by andreasnoack** [comment]
Fixed by #29122
