### ISSUE TITLE
Allow `push!(d::Dict, (a, b))`

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#29126]
Right now, a user is allowed to push pairs onto a `Dict`:

```julia
julia> d = Dict{String, String}();

julia> push!(d, "b" => "boo")
Dict{String,String} with 1 entry:
  "b" => "boo"
```

It is sometimes useful to construct a dictionary using tuples, e.g. with 

```julia
julia> push!(d, ("c", "cat"))
ERROR: MethodError: no method matching push!(::Dict{String,String}, ::Tuple{String,String})
Closest candidates are:
  push!(::Any, ::Any, ::Any) at abstractarray.jl:2064
  push!(::Any, ::Any, ::Any, ::Any...) at abstractarray.jl:2065
  push!(::Array{Any,1}, ::Any) at array.jl:862
  ...
```

`Dict*` types in `DataStructures.jl` allow this, and it is used (at least) [by Gadfly](https://github.com/GiovineItalia/Gadfly.jl/blob/1d087016bd51f27793b891e29a58c6b4db86c7ef/src/geom/polygon.jl#L73-L76).

Would it be reasonable to (re-)introduce that functionality for `Dict`s?  Alternatively, is it better to remove that functionality from `DataStructures.jl` (see https://github.com/JuliaCollections/DataStructures.jl/pull/254)?

**Comment by kmsquire** [comment]
@keno, I added a specific example of what I'm asking for in the description in response to your "confused" emoji response...  (Sorry, it was late when I wrote that.)

**Comment by Keno** [comment]
So my concern here is that `Tuple` is not the element type of a Dict, so this is a bit confusing. How does this generalize? Do we iterate any iterable to get the first two elements and give a pair. What about `push!(d, (a =>b, c =>d))`. Some might expect that to push two pairs (though arguably one should use broadcast syntax instead).

**Comment by kmsquire** [comment]
> What about `push!(d, (a =>b, c =>d))`

I'd love to see an example like this in the wild! 😜 
(In all seriousness, I guess something like this could exist in a graph algorithm, although the `=>` might be considered a pun...)

> Some might expect that to push two pairs (though arguably one should use broadcast syntax instead).

Are there any examples in Julia where passing a tuple implies iterating over its elements?  My (perhaps incorrect) impression/assumption is that tuples are generally considered "scalar" in these contexts, whereas arrays would be considered iterable.

Anyway, my preference would be to write generic code like this:

```julia
function munge(mydict, pairs)
    for pair in pairs
        push!(mydict, pair)
    end
end
```

or

```julia
function remunge(mydict, shortpairs)
    # do some stuff
    # ...
    push!(mydict, shortpairs...)
end  
```

and have it just work regardless if `pairs` / `shortpairs` are lists of `Pair`s or 2-tuples.  Right now, if I want to handle both, I have to be a little more verbose.

For reference, if we remove this behavior from `DefaultDict`s in DataStructures.jl, Gadfly would have to make something like (this change)[https://github.com/kmsquire/Gadfly.jl/commit/b885108046bc3fd7e451b2407bc92a56a91f0b64], which to my eyes is a bit ugly.

Now, that's just my preference, but if the decision is made not to add this functionality, then I'll remove the corresponding behavior in `DataStructures.jl`, because I think the consistency is worth it.

**Comment by Ethycs** [comment]
Wish this would work

**Comment by vtjnash** [comment]
Lots of downvotes, and we are not likely to do this currently. We just are not generally assuming that Pair is the same as arbitrary-thing-which-iterates-to-give-two-values.
