### ISSUE TITLE
Suggestion for website: code example on homepage

### ISSUE THREAD

**Issue by kennethreitz** [JuliaLang/julia#29125]
I'm checking out Julia, out of interest, and finding it difficult to find a visual example of the syntax. Would be nice if it was right on the homepage, like Python has:

![p](http://share.kennethreitz.org/313a64922fbf/Screen%20Shot%202018-09-11%20at%202.40.36%20AM.png)

Just a suggestion — trying to be helpful!

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/www.julialang.org/issues/115

**Comment by kennethreitz** [comment]
✨🍰✨
