### ISSUE TITLE
Feature Request: specify name when adding unregistered package

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#29138]
I'm just getting starting figuring out how the new Pkg system works. I see that you can still call 
`Pkg.clone("...url...", "PackageName")` which is nice because I have a few packages where the url is mangled and doesn't conform with Julia package requirements (bitbucket makes its url slug all lowercase). 

Can we add this option of specifying the package name to `add` ?

**Comment by KristofferC** [comment]
Should be opened on the Pkg.jl repo but this is already documented... 

https://julialang.github.io/Pkg.jl/latest/#Pkg.add

**Comment by bdeonovic** [comment]
Thanks @KristofferC I see the functionality is still not working though (https://github.com/JuliaLang/Pkg.jl/issues/667), it still guesses the name from URL even if you specify name kwarg.

**Comment by KristofferC** [comment]
Oh I forgot about that. Should be an easy fix.
