### ISSUE TITLE
adding a method to Base.Int can result in (seemingly) unrelated recompilation

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#29166]
This is a MWE:
```julia
struct X <: Integer end
Base.Int(::X) = 0
```
After entering this in the REPL, it becomes annoyingly slow (even for simple things as entering `1+2`), while Julia apparently recompiles a bunch of functions. This problem apparently disappears for other Base builtin integers, or when using e.g. `Real` instead of `Integer` as the supertype. 
Also, this doesn't happen on 0.7, so I will label as a regression.

**Comment by JeffBezanson** [comment]
I'll note that this is not really a bug --- AFAICT we were not invalidating any methods incorrectly --- but it did point to some places we could improve the typing of Base code. This new definition invalidates anything that calls `Int(x::Integer)`. In general it is not easy to guess how many inferred methods might contain that, or any other function/type pair.
