### ISSUE TITLE
Travis Mac CI running out of memory on sysimg build

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#29160]
It looks like the OS X builder are running our of memory on travis.
Not sure if anything major changed recently, but let's try to find out.

**Comment by KristofferC** [comment]
Example log https://travis-ci.org/JuliaLang/julia/jobs/427715475

Stacktrace

```
error during bootstrap:
LoadError("sysimg.jl", 446, LoadError("version.jl", 50, ErrorException("PCRE JIT error: no more memory")))
rec_backtrace at /Users/travis/build/JuliaLang/julia/src/stackwalk.c:94
record_backtrace at /Users/travis/build/JuliaLang/julia/src/task.c:249 [inlined]
jl_throw at /Users/travis/build/JuliaLang/julia/src/task.c:580
error at ./error.jl:33
jit_compile at ./pcre.jl:110 [inlined]
compile at ./regex.jl:70
```

so doesn't seem to be the at the same place as there were problems before (LLVM native codegen).

**Comment by Keno** [comment]
The fact that PCRE always shows up in these is indeed a bit suspicious. We uses system pcre on OS X, so perhaps that got updated without our knowledge?
