### ISSUE TITLE
Precompile generation is broken under wine

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#29161]
Listening on a named pipe returns EINVAL. This Wine bugs seems equivalent: https://bugs.winehq.org/show_bug.cgi?id=45749

**Comment by vtjnash** [comment]
I thought we were patching through this in our libuv at some point

**Comment by Keno** [comment]
I remembered something like that to but it's certainly broken at this point.

**Comment by Keno** [comment]
Fixed upstream
