### ISSUE TITLE
Issue with edit, which, etc. macros for `x[end]`

### ISSUE THREAD

**Issue by tomaklutfu** [JuliaLang/julia#29177]
In reference to https://discourse.julialang.org/t/issue-with-macros-and-x-end/14850, base macros I tested do not allow `getindex` syntax with `end`.
```
julia> @which xdots[end]
ERROR: UndefVarError: end not defined
Stacktrace:
 [1] top-level scope at none:0

julia> @which xdots[1]
getindex(A::Array, i1::Int64) in Base at array.jl:731
```
@mauro3 further explained what happens in syntax transformation

> Yes, looking at the macroexpand:
> 
> `julia> @macroexpand @which x[end]`
>` :((InteractiveUtils.which)(getindex, (Base.typesof)(x, end)))`
> 
>` julia> @macroexpand @which x[1]
> `:((InteractiveUtils.which)(getindex, (Base.typesof)(x, 1)))`
> so, what should be done is check for an end and if found instead expand to
> 
> `InteractiveUtils.which(getindex, (Base.typesof)(x, lastindex(x)))`
> However, that might be more trouble than it is worth.

**Comment by JeffBezanson** [comment]
Yes, I'm not sure this is worth supporting.

**Comment by tomaklutfu** [comment]
Close per the comment.
