### ISSUE TITLE
`readdlm` speed regression

### ISSUE THREAD

**Issue by alexmorley** [JuliaLang/julia#29170]
```bash
yes 1234567 | head -1000000 > test.txt
julia -e "versioninfo()"
julia test.jl
juliav7 -e "versioninfo()"
juliav7 test.jl
```

Gives

> julia version 0.6.0
>   0.823502 seconds (286.43 k allocations: 31.633 MiB)
>   1.165942 seconds (3.09 M allocations: 104.117 MiB, 48.31% gc time)
> julia version 0.7.0
>   6.022019 seconds (34.26 M allocations: 859.682 MiB, 4.85% gc time)
>   5.411997 seconds (35.93 M allocations: 875.413 MiB, 4.22% gc time)

where test.jl is 
```julia
if VERSION >= v"0.7.0"
    using DelimitedFiles
end
@time readdlm("test.txt",' ', Int, '\n',dims=(1000000,1))
@time readdlm("test.txt")
```

Version Information Below:
> Julia Version 0.6.0
> Commit 9036443 (2017-06-19 13:05 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: Intel(R) Xeon(R) CPU E7-8860 v4 @ 2.20GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: libopenblas64_
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
> 
> Julia Version 0.7.0
> Commit a4cb80f3ed (2018-08-08 06:46 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: Intel(R) Xeon(R) CPU E7-8860 v4 @ 2.20GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

**Comment by JeffBezanson** [comment]
Duplicate of #29036?

**Comment by alexmorley** [comment]
Yes, probably! Sorry not sure I didn't hit that on my search. Thanks.
