### ISSUE TITLE
Char reinterpret is (kind of) broken

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#29181]
```jl
julia> reinterpret(UInt32, reinterpret(Char, 0x00ff0000))
0x00000000

julia> u2c(u::UInt32) = reinterpret(Char, u)
u2c (generic function with 1 method)

julia> c2u(c::Char) = reinterpret(UInt32, c)
c2u (generic function with 1 method)

julia> u2c(0x00ff0000)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> c2u(u2c(0x00ff0000))
0x00000000

julia> u2u(u) = c2u(u2c(u))
u2u (generic function with 1 method)

julia> u2u(0x00ff0000)
0x00ff0000

julia> c2u(u2c(0x00ff0000))
0x00000000
```
The fortunate thing is that it doesn't seem to be broken in a way that affects any `Char` values that can be produced naturally—you can only produce the values for which this is broken through reinterpret of `UInt32` values.

**Comment by chethega** [comment]
I think the problem is weirder, i.e. looks like a wrong optimization somwhere? I cannot reproduce outside of the REPL, so far.
```
julia> f(x)=reinterpret(UInt32, reinterpret(Char, x));
julia> f(0x00ff0000)
0x00ff0000
julia> reinterpret(UInt32, reinterpret(Char, 0x00ff0000))
0x00000000
julia> x=0x00ff0000;
julia> @noinline to_i(x)=reinterpret(UInt32,x);
julia> @noinline to_c(x)=reinterpret(Char, x);
julia> to_i(to_c(x))
0x00000000
julia> g(x)=to_i(to_c(x));
julia> g(x)
0x00ff0000
```

**Comment by StefanKarpinski** [comment]
It's actually the opposite of a mis-optimization: the optimized version is correct, it's the version that's told not to optimize that gives the wrong answer. @vtjnash said on Slack that he thought it might have to do with a bug in our `boxed_char_cache` except that we don't have one... except that we do. So that might be it.

**Comment by StefanKarpinski** [comment]
Yup, that's it. Fix incoming.
