### ISSUE TITLE
reload() function not defined in Julia 1.0.0

### ISSUE THREAD

**Issue by gregorydavidmartinez** [JuliaLang/julia#29195]
I'm trying to reload a module after I made a few changes.  In the manual it say to use the "reload("Module")" function, but when I try it I get:

ERROR: UndefVarError: reload not defined

**Comment by fredrikekre** [comment]
The documentation have been corrected in #28644. For reloading code automagically I can highly recommend [Revise.jl](https://github.com/timholy/Revise.jl).
