### ISSUE TITLE
Conditional inner constructor

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#29190]
If you add a inner constructor which is conditional even if the condition is false it results in the default inner constructors being removed and you can end up with an struct which you cannot create an instance of:

Run on Julia 1.0:
```julia
julia> struct Foo
           x
           if VERSION < v"1.0"
               Foo(x) = new(x)
           end
       end

julia> Foo(1)
ERROR: MethodError: no method matching Foo(::Int64)
Stacktrace:
 [1] top-level scope at none:0

julia> methods(Foo)
# 0 methods for generic function "(::Type)":
```

I'll note that this isn't much of a problem as you can use `@static` to have the intended behaviour:
```julia
julia> struct Bar
           x
           @static if VERSION < v"1.0"
               Bar(x) = new(x)
           end
       end

julia> Bar(1)
Bar(1)
```
However I expect this will stump some newcomers so it may be worth fixing.

**Comment by StefanKarpinski** [comment]
If there's any code in the type body you don't get the default constructors. I think that's the simplest and most easy to understand behavior and it's been that way from day one...

**Comment by StefanKarpinski** [comment]
Any methods of what? The type itself?

**Comment by JeffBezanson** [comment]
The default constructors are added by lowering. I think basing it on what happens when the code is run is too dynamic; e.g. that would be one more thing an external tool would never be able to resolve.

I don't think this case needs a warning. There are rare situations where you want something like
```
struct Foo
    x
    global f(x) = new(x)
end
```
where instances can only be created by calling some function other than the type itself. There's nothing dangerous about that.

**Comment by StefanKarpinski** [comment]
Agree, the current rule is simple and strictly syntactic, which is ideal. Anything else would be too dynamic and fiddly. As Jeff said, it's unusual but sometimes desirable to provide a function that constructs objects of a type by calling some other function instead of calling the type itself.

**Comment by omus** [comment]
That's a very interesting use case I hadn't considered. Thinking about this more I believe my example is rare enough that only experienced Julia developers encounter it. I appreciate the enlightening responses.
