### ISSUE TITLE
Hard to use LOAD_PATH and import

### ISSUE THREAD

**Issue by AlphaFase** [JuliaLang/julia#29202]
Isn't LOAD_PATH a global variable, a temporary variable?

Can you unload the loading path like env in Python?

# No.1
### setting.jl
```
push!(LOAD_PATH, joinpath(pwd(), "libs"))
```
### Types.jl
```
module Types
globla b=100
export b
end
```
### Server.jl
```
using Types

b=200
```

### main.jl
```
include("./setting.jl")
using Server
@show LOAD_PATH
```
### out
```
LOAD_PATH
4-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
 "E:\\julia_project\\niuniu\\conf"    # The LIBS directory is missing.？？？
```

## Error
```
ERROR: LoadError: Failed to precompile Server [top-level] to C:\Users\Administrator\.julia\compiled\v1.0\Server.ji.

```

**Comment by AlphaFase** [comment]
Is bug the same as using and import now?
Using should import all variables into the current scope.

### Error code
```
push!(LOAD_PATH, joinpath(pwd(), "server"))
using Setting
@show b
```
### Correct Code
```
push!(LOAD_PATH, joinpath(pwd(), "server"))
using Setting
@show Setting.b
```
So, what's the difference between using and import?

**Comment by KristofferC** [comment]
Please ask questions at https://discourse.julialang.org.
