### ISSUE TITLE
`$` not accesible from the `help?>` prompt in REPL

### ISSUE THREAD

**Issue by miguelraz** [JuliaLang/julia#29219]
When in the REPL, one can get information from the help prompt from `!`, `?`, but not from `$`.

I think this would make a good addition and some healthy examples for beginners, especially with the splatting interpolation form, which I just learned. 

I volunteer making a PR if someone helps review it.

**Comment by miguelraz** [comment]
[PR has been opened](https://github.com/JuliaLang/julia/pull/29220).

**Comment by Keno** [comment]
This issue is fixed, though the docstring could be expanded. PRs welcome.
