### ISSUE TITLE
Allow for recursive merge of NamedTuples

### ISSUE THREAD

**Issue by stakaz** [JuliaLang/julia#29215]
Hello, it would be great, when something like this:

```julia
Base.merge(front::NamedTuple, tail::NamedTuple...) = merge(merge(front, tail[1]), tail[2:end]...)
```

would be available in Base.

It is a very common thing to merge multiple tuples together and would be really a sweet sugar. like this:

```julia
julia> A = (a = 1, b = 1);
julia> B = (a = 2, c = 2);
julia> C = (b = 3, d = 2);
julia> merge(A,B,C)
(a = 2, b = 3, c = 2, d = 2)
```

Are there any reasons this is **not** in Base?

Thanks

**Comment by JeffBezanson** [comment]
Yes, this could be added.

**Comment by fredrikekre** [comment]
#29259
