### ISSUE TITLE
Inference fails when passing more than five arguments to zip

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#29214]
I suspect this is the symptom of a known issue, but I thought I'd better file it anyway.

The function `test` is inferred correctly up to three arguments, but above that there are lots of occurrences of `Tuple{Any}`, which totally kills performance.

```julia
function test(X)
    res = Vector{Bool}(undef, length(X))
    i = 1
    @inbounds for x in X
        res[i] = x[1] > 0
        i += 1
    end
    res
end

# Good
@code_warntype test(zip([1], [1], [1], [1], [1]))
# Bad
@code_warntype test(zip([1], [1], [1], [1], [1], [1]))
```

**Comment by JeffBezanson** [comment]
Dup of #26765?

**Comment by nalimilan** [comment]
Probably, though the limit on the number of iterators seems to have decreased from 7 to 3 even with the example from https://github.com/JuliaLang/julia/issues/26765.
