### ISSUE TITLE
Confusing error when `cat` is called with wrong keyword

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#29225]
```
julia> cat([1], dim=1)
ERROR: UndefKeywordError: keyword argument dims not assigned
Stacktrace:
 [1] (::getfield(Base, Symbol("#kw##cat")))(::NamedTuple{(:dim,),Tuple{Int64}}, ::typeof(cat), ::Array{Int64,1}) at ./none:0
 [2] top-level scope at none:0
```
(NB: `dim` vs `dims`)

**Comment by KristofferC** [comment]
How is this confusing? Seems like a very direct, correct error message?

**Comment by mschauer** [comment]
It is confusing because it confused you? I provide keyword argument `dim`, it complains about `dims`. I was confused by this too. Or am I missing something?

**Comment by KristofferC** [comment]
It complains about `dims` because that's the keyword you need to assign and you didn't.

```
julia> f(;this_is_needed) = this_is_needed
f (generic function with 1 method)

julia> f(; x = 3)
ERROR: UndefKeywordError: keyword argument this_is_needed not assigned
```

**Comment by mschauer** [comment]
Ah, I get it finally, I stumbled over the meaning of assigned. I think of a way to say it clearer.

**Comment by KristofferC** [comment]
Yeah, sounds more clear to me.
