### ISSUE TITLE
Show me an example of Julia on the home page

### ISSUE THREAD

**Issue by bfirsh** [JuliaLang/julia#29236]
I don’t know anything about Julia, and the best way for me to understand the language is to see a few examples. When I landed on the home page, the features and advantages make sense, but I still don’t really understand what it is without seeing an example. 

I clicked around a few times and still couldn’t find some examples. Even the getting started guide is just how to use the REPL and command line flags. 

Compare to:

https://www.rust-lang.org/en-US/ (There is also “rust by example” beyond the home page)
https://golang.org/

I had a quick search through the issues but couldn’t find this already filed. Perhaps I’m using the wrong keywords.

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/www.julialang.org/issues/115
