### ISSUE TITLE
Inaccurate Sys.MACHINE assignment for FreeBSD11.2

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaLang/julia#29237]
I noticed an Inaccurate assignment of Sys.MACHINE for FreeBSD11.2. 

Presumably, this machine should be assigned `x86_64-unknown-freebsd11.2` and not `x86_64-unknown-freebsd11.1`

```bash
Last login: Tue Sep 18 04:18:14 2018
FreeBSD 11.2-RELEASE (GENERIC) #0 r335510: Fri Jun 22 04:32:14 UTC 2018
FreeBSD julia.novalocal 11.2-RELEASE amd64
 4:55AM  up 15:21, 3 users, load averages: 0.00, 0.01, 0.00
 username@hal  /u/h/username  julia                                                                                                                    Tue Sep 18 04:55:47 2018
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: FreeBSD (x86_64-unknown-freebsd11.1)
  CPU: AMD Opteron 63xx class CPU
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, bdver1)

julia> Sys.MACHINE
"x86_64-unknown-freebsd11.1"
```

I don't yet know what implications this has on package management for FreeBSD11.2.

**Comment by nalimilan** [comment]
AFAIK that's the platform used to build the binary, not the one you're using.

**Comment by ararslan** [comment]
Milan is correct. The machine that builds the FreeBSD binaries runs 11.1, and the builds work on 11.1, 11.2, and the current 12.0. The same thing happens on macOS, which uses an older version for builds.

**Comment by martinholters** [comment]
The docstring also says "A string containing the _build_ triple." (Highlight by me.) However, `Sys.MACHINE` certainly sounds like it contains information about the machine Julia is running on, which might also be the more useful piece of information...

**Comment by CiaranOMara** [comment]
To clarify, `Sys.MACHINE` provides information about the build machine, and `versioninfo()` provides information about my system?

**Comment by nalimilan** [comment]
No, `versioninfo()` just prints the contents of `Sys.MACHINE` (and other things).

**Comment by CiaranOMara** [comment]
How about having `buildinfo()` that explicitely says something like, "Julia was built with...", and `systeminfo()` that says something like, "Julia is running on/with..."?

**Comment by nalimilan** [comment]
I don't think we don't store/extract the current OS version at the moment (we don't need it, except on Windows). A simple fix would be to indicate "build" before the build machine triple.
