### ISSUE TITLE
Support Windows 10 in SSHManager

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#29243]
Windows 10 now has facilities for [native ssh handling](https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/), but that uses the native shell and not `sh` which we currently assume to be available on the remote host. 

See https://discourse.julialang.org/t/cant-add-windows-workers-due-to-a-missing-sh-shell/15055?u=vchuravy for where this came up.

**Comment by mgkuhn** [comment]
Julia 1.6 has a new `shell=:wincmd` option of [Distributed.addprocs()](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.addprocs) for Windows workers where you ssh into `cmd.exe`. If you use any older Windows versions than Windows 10 semi-annual 20H1 with latest updates, and it doesn't work, also try the `cmdline_cookie=true` option as a workaround.
