### ISSUE TITLE
sizeof for Set (and Dict) incorrect

### ISSUE THREAD

**Issue by mboratko** [JuliaLang/julia#29257]
It seems like the sizeof function does not work on Sets (or Dicts):
```
julia> sizeof(Set([1]))
8

julia> sizeof(Set([1,2]))
8

```

**Comment by JeffBezanson** [comment]
`sizeof` defaults to giving the size of the struct itself. It is generally not meaningful for types that lack an obvious "flat" representation. Arguably these cases should be method errors, forcing you to use `Core.sizeof` if you want the size of the struct.

**Comment by mboratko** [comment]
Thanks, I was misled by [the docs for sizeof](https://docs.julialang.org/en/v1/base/base/#Base.sizeof-Tuple{Type}):

> sizeof(T::DataType)
> sizeof(obj)
> Size, in bytes, of the canonical binary representation of the given DataType T, if any. Size, in bytes, of object obj if it is not DataType.

It seems like `Core.sizeof` has the same problem, but `Base.summarysize` works correctly:

```
julia> Core.sizeof(Set([1,2]))
8

julia> Base.summarysize(Set([1,2]))
336
```

[I wasn't able to find anything about this in the docs though](https://docs.julialang.org/en/v1/search/?q=summarysize), instead it was in a comment to [this StackOverflow answer](https://stackoverflow.com/a/35132990).

**Comment by laborg** [comment]
Now that `summarysize` has been linked from and to `sizeof` in the docstrings (https://github.com/JuliaLang/julia/pull/41453) this shouldn't be a problem anymore.
