### ISSUE TITLE
Long compile time followed by wrong/inconsistent results for Polyhedra.jl

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#29276]
I am getting a very strange result on Julia 0.7.
Sorry I don't have a smaller example. The `polyhedron` call takes very long, and then `removevreundancy!` crashes either due to an index error (on my macOS machine) or an OutOfMemory error, arising from the length of an array or iterator being reported as ~gazillion instead of 0.

I have instrumented the code with some debugging statements here: https://github.com/goretkin/Polyhedra.jl/blob/a67cce6ff8a316d9c13c0b78eb56d8097e072f5e/src/liftedrep.jl#L83

To reproduce, run: (I don't actually know if I got the Pkg3 commands right, but make sure you're on the `ggdebug` branch of https://github.com/goretkin/Polyhedra.jl.git
```julia
]develop https://github.com/goretkin/Polyhedra.jl.git
]add Polyhedra#ggdebug

using Revise
using Polyhedra
v = vrep(rand(20,2))
p = polyhedron(v) # takes very long (multiple minutes) to compile
removevredundancy!(p)
```

The output of the above code:
```
julia> removevredundancy!(p)
vits = ([[0.684871, 0.422565], [0.325961, 0.098132], [0.162097, 0.260722], [0.241066, 0.72386], [0.904699, 0.668316], [0.169152, 0.210273], [0.511557, 0.263185], [0.647133, 0.530529], [0.483491, 0.811134], [0.22725, 0.319179], [0.266512, 0.97481], [0.868765, 0.145148], [0.732469, 0.0106707], [0.456108, 0.38461], [0.980455, 0.581537], [0.980481, 0.783638], [0.620545, 0.385467], [0.473935, 0.295459], [0.944959, 0.0708203], [0.563476, 0.465936]], [], [])
typeof(vits) = Tuple{RepIterator{2,Float64,Array{Float64,1},Tuple{MixedMatVRep{2,Float64,Array{Float64,2}}}},RepIterator{2,Float64,Line{2,Float64,Array{Float64,1}},Tuple{MixedMatVRep{2,Float64,Array{Float64,2}}}},RepIterator{2,Float64,Ray{2,Float64,Array{Float64,1}},Tuple{MixedMatVRep{2,Float64,Array{Float64,2}}}}}
typeof(vits[1]) = RepIterator{2,Float64,Array{Float64,1},Tuple{MixedMatVRep{2,Float64,Array{Float64,2}}}}
points = [[0.684871, 0.422565], [0.325961, 0.098132], [0.162097, 0.260722], [0.241066, 0.72386], [0.904699, 0.668316], [0.169152, 0.210273], [0.511557, 0.263185], [0.647133, 0.530529], [0.483491, 0.811134], [0.22725, 0.319179], [0.266512, 0.97481], [0.868765, 0.145148], [0.732469, 0.0106707], [0.456108, 0.38461], [0.980455, 0.581537], [0.980481, 0.783638], [0.620545, 0.385467], [0.473935, 0.295459], [0.944959, 0.0708203], [0.563476, 0.465936]]
lines_ = []
rays = []
npoint = 20
nline = 140421676981264
nray = 140423539322816
ERROR: OutOfMemoryError()
```
In addition to printing stuff, the `ggdebug` branch also populates a global variable:

```
julia> Polyhedra.debug
Dict{Symbol,Any} with 8 entries:
  :T      => Float64
  :N      => 2
  :vits   => ([[0.684871, 0.422565], [0.325961, 0.098132], [0.162097, 0.260722], [0.241066, 0.72386], [0.904699, 0.668316], [0.169152, 0.210273], […
  :nline  => 140421676981267
  :nray   => 140423537774064
  :MT     => Array{Float64,2}
  :lines_ => []
  :npoint => 20
```

The big inconsistency is that `length(Polyhedra.debug[:lines_])==0` and not `Polyhedra.debug[:nline]`, which is some junk number.

(The slow compilation time is possibly related to https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/110)

I reproduced the issue on 
```Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
```
and
```
julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by KristofferC** [comment]
What julia version did you run this on?

**Comment by goretkin** [comment]
Sorry that I missed that crucial detail... Edited above.

**Comment by andreasnoack** [comment]
Please provide the output from `versioninfo`

**Comment by andreasnoack** [comment]
It looks like `Polyhedra` still triggers a lot of deprecation warnings. As a consequence, the code doesn't load on Julia 1. I think the deprecations have to be fixed before it makes sense to look into the performance problem here since it might simply be that deprecated functions are called many times.

**Comment by blegat** [comment]
Polyhedra master with JuMP in the branch release-0.18 is now working on Julia v1.0
Due to all the issues we had in Julia v1.0 such as https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/109, I did a major breaking change in https://github.com/JuliaPolyhedra/Polyhedra.jl/pull/116.
@goretkin Do you still have the issue described in this PR ?
Now the issues blocking the update to Julia v1.0 are gone but new ones have appeared:
* https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/121
* https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/123

**Comment by ViralBShah** [comment]
Reopen if still an issue.
