### ISSUE TITLE
Tab completion of symbols fails when doing using Package: Foo

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#29275]
For example:

```jl
julia> using LibGit2: GitRepo

julia> GitR<TAB> # doesn't complete

julia> using LibGit2

julia> GitR<TAB> # completes to GitRepo
```

This also fails on 0.6 but according to @ararslan it works on 0.5 so marking as regression.

**Comment by KristofferC** [comment]
So, where does the `GitRepo` binding live (or how can I find out that it exists)?

```
julia> GitRepo
GitRepo

julia> names(Main; all=true, imported=true)
11-element Array{Symbol,1}:
 Symbol("##1#2")
 :Base
 :Core
 :InteractiveUtils
 :Main
 :Markdown
 :REPL
 :Revise
 :ans
 :eval
 :include
```

**Comment by stevengj** [comment]
`:GitRepo in names(Main, all=true, imported=true)` returns `false`.  If you do `import LibGit2: GitRepo` then tab-completion works.

**Comment by KristofferC** [comment]
Yeah, you mean that that's the bug?
