### ISSUE TITLE
REPL helpmode for "=" returns error

### ISSUE THREAD

**Issue by aaraun** [JuliaLang/julia#29282]
```
help?> =
ERROR: LoadError: Invalid @var syntax `unexpected "="`.
Stacktrace:
 [1] splitexpr(::Any) at ./docs/bindings.jl:28
 [2] bindingexpr(::Any) at ./docs/bindings.jl:17
 [3] lookup_doc(::Expr) at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/REPL/src/docview.jl:137
 [4] @doc(::LineNumberNode, ::Module, ::Expr, ::Vararg{Expr,N} where N) at ./boot.jl:451
in expression starting at /build/julia/src/julia/usr/share/julia/stdlib/v1.0/REPL/src/docview.jl:301
```

Looking at `basedocs.jl`, it seems like there isn't actually a docstring for `=`, so maybe parsing it isn't important. OTOH at least one user (me) has thought this would be the quick way to get answers about how `=` works in Julia.

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 2
```

**Comment by fredrikekre** [comment]
Docs for `=` should definitely be added.

**Comment by aaraun** [comment]
Would that I were competent to do so myself. I'll just also note that it seems like the parsing issue lies with splitexpr, and the way it tries to look up a `symbol` using `getfield(Base, :symbol)`, which isn't valid for a variety of more special symbols, like `=`, `.`, or `@`.

**Comment by fredrikekre** [comment]
Right, thats why some things are documented using the `kw_str` string macro, for example https://github.com/JuliaLang/julia/blob/6fa3e45531a68fae34f31214cbf7e008298995d5/base/docs/basedocs.jl#L29-L37

So this work:
```julia
julia> import Base.BaseDocs.@kw_str

julia> """
           =

       Assignment operator.
       """
       kw"="

help?> =
search: => == === >= <= != !==

  =

  Assignment operator.
```

**Comment by aaraun** [comment]
Ah, great. Then I'll at least draft a doc.

**Comment by fredrikekre** [comment]
#30745
