### ISSUE TITLE
maxintfloat should return an ::Integer

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#29297]
Contrary to its [documentation](https://github.com/JuliaLang/julia/blob/ce6454642ca2f6075623179c6804ea6c78d1fdb5/base/floatfuncs.jl#L25) which says (emphasis mine)

> ... `maxintfloat` returns the smallest positive **integer** ...

it actually returns floating point values.

I don't know if this is a problem with wording or the implementation. IMO returning integers would be more useful as one could perform exact arithmetic & comparisons with them around the edge of the representable region.

**Comment by StefanKarpinski** [comment]
The word "integer" is a bit ambiguous in this case it means "integer-valued floating point number", so we could replace the word with that in the docs. Changing the type returned would be a breaking change, so we're not going to do that but you can easily just do `Int(maxintfloat())` to get an integer.

**Comment by tpapp** [comment]
Not quite, eg `maxintfloat(BigFloat)`, but `Integer(maxintfloat(...))` seems to do the trick.

I will make a PR about the documentation then, and perhaps mention this?

**Comment by StefanKarpinski** [comment]
Yes, that would be great!

**Comment by JeffBezanson** [comment]
I think it makes sense to return special values of a type as that type itself. Improving the docs sounds like the right thing here.
