### ISSUE TITLE
win64 CI failing

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#29300]
All builds are failing with
```
Extracting julia-latest-win64.exe
ERROR: julia-latest-win64.exe
julia-latest-win64.exe
Open ERROR: Can not open the file as [PE] archive
```

**Comment by StefanKarpinski** [comment]
@staticfloat, @ararslan, any ideas here?

**Comment by ararslan** [comment]
It appears we don't have a folder for x64 in julialangnightles/bin/winnt on S3, so this is downloading nothing:
https://github.com/JuliaLang/julia/blob/e1ae9f0081bc99491ed14714eeb93156cf1b377f/contrib/windows/appveyor_build.sh#L94

**Comment by ararslan** [comment]
So says Elliot:

> The win64 buildbot has been dead for a month (whoops) so I turned it on again today.  Its first build failed (of course) its second build is going right now

Apparently the buildbot processed stopped and wasn't restarted because nobody noticed. Once the second build goes through we should have that available again.

**Comment by ararslan** [comment]
@staticfloat, any news on this?

**Comment by JeffBezanson** [comment]
Seems to be fixed.
