### ISSUE TITLE
Better error messages for UndefVarError

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#29313]
UndefVarError reports the location of the first use of a global variable, without the location of the offending assignment making the variable local. This can be quite puzzling.

```
a = 1
while true
    println("do stuff")
    println(a)
    println("do stuff")
    a = 2
    break
end
```

```
julia> include("project/linenumbertest.jl")
do stuff
ERROR: LoadError: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope at /Users/schauermr/.julia/v0.6/Bridge/project/linenumbertest.jl:4 [inlined]
 [2] top-level scope at ./none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1041
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] include(::String) at ./client.jl:388
 [7] top-level scope at none:0
in expression starting at /Users/schauermr/.julia/v0.6/Bridge/project/linenumbertest.jl:2
```

**Comment by JeffBezanson** [comment]
I didn't realize it was a matter of opinion which statement is "offending" here :) The problem is that introducing a local variable is not an error, but accessing an undefined one is. I think for multiple reasons the current way the error is reported is the only real option.

**Comment by mschauer** [comment]
The meaning of line 4 is changed by line 6. So when reporting that line 4 is an error also referencing line 6 would be very helpful in my opinion.

**Comment by JeffBezanson** [comment]
Ok, I can see that it would be useful to say "`a` (introduced on line 6) undefined on line 4". It is just not very practical. We would have to keep around a bunch of extra information in the compiler, and somebody would have to do a lot of tedious work to implement it. Seems like low value-to-effort to me.

**Comment by mschauer** [comment]
Could there be a hint like: `local variable a not defined yet` versus `a not defined`?

**Comment by JeffBezanson** [comment]
What about a case like this:
```
if false
    a = 0
end
a
```

**Comment by StefanKarpinski** [comment]
I think the conclusion is this: yes, it would be great to have better error messages like this. If someone wants to implement them (in a way that doesn't excessively complicate the parser and compiler), we will be very grateful.

**Comment by JeffBezanson** [comment]
It's possible it could be done a bit more easily by looking at the IR when the error is thrown and checking whether any assignments exist before the line with the error. That's fairly heuristic, but might be accurate enough to be helpful.

**Comment by JeffBezanson** [comment]
Also, changing #28789 would make it harder to hit cases like this.

**Comment by mschauer** [comment]
Thats of course a point in case of doing nothing. Picking up the example 
```
while true
    if false
        a = 0
    end
    a
end
```
I think distinguishing `local variable a not assigned` for unassigned local variables vs `a  not defined` for undefined variables which could be local or global would still be helpful if that information is readily available.

**Comment by KristofferC** [comment]
The `a=2` makes `a` local to the scope of the `while` and it has indeed not been defined yet.

**Comment by KristofferC** [comment]
Because you are not using the variable before it has been defined in those cases.

**Comment by VictorelPetrovich** [comment]
Thanks for the answers; I thought it's a bug.
1. In the last loop,  `print(a)` comes before `a=2`; why doesn't it print `1`?
2. If `a=2` makes `a` local, does not that also defines what is `a`?  `a=2` looks like a definition.

**Comment by chethega** [comment]
Your error should better be called `UndefVarError: local variable a accessed before initialization`. 

Assignment `a=2` follows control-flow (in order, affected by if / while / goto); declaration is decided at compile time (at parsing or lowering?) and holds for the entire scope. The assignment `a=2` implies the declaration that `a` is local, and this holds for the entire block. The declaration, i.e. the shadowing of the global `a`, can travels back in time from dead code, so to speak.

**Comment by VictorelPetrovich** [comment]
Maybe better not "UndefVarError:..." here (because the var is defined), but just "VarError:..." or "VarDefError:...".
But what is going on is way, way too complicated, for most of intended Julia users. 
I still don't fully get it, I should ask on forums.

**Comment by mschauer** [comment]
You are right, you'll find plenty of good arguments supporting various stances on discourse. Here, I'd like to focus this issue entirely on the error messages for `UndefVarError` and leave discussion about how scope should be handled to other places.

**Comment by xinkai-zhou** [comment]
> Because you are not using the variable before it has been defined in those cases.
I thought in this case we're using the variable before it has been define. no?
```julia> a=1; while a<5; print(a);            break; end```

**Comment by KristofferC** [comment]
It gets defined in the very first statement `a = 1`. Please redirect further questions about scoping to http://discourse.julialang.org/.
