### ISSUE TITLE
`rand` docstring example is broken

### ISSUE THREAD

**Issue by harryscholes** [JuliaLang/julia#29317]
The docstring for `Base.rand` contains this example:

https://github.com/JuliaLang/julia/blob/cc0de4389b6ced991efb83297a4fd47fdba51dc8/stdlib/Random/src/Random.jl#L303

However, `Random` must be explicitly imported for this to work.

```julia
help?> rand
  # ...
  julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
    1=>2
  # ...

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
ERROR: UndefVarError: MersenneTwister not defined
Stacktrace:
 [1] top-level scope at none:0

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1 => 2
```

Should `julia> using Random` be added to the docstring examples?

**Comment by ssainz** [comment]
Yes, adding `using Random` to the docs will make it easier.
