### ISSUE TITLE
Crash when defining a `convert` method for `NTuple`

### ISSUE THREAD

**Issue by fjarri** [JuliaLang/julia#29321]
The following code:

    Base.convert(tp, x::NTuple{N, T}) where {N, T} = x
    foo()

crashes when executed both in Julia 1.0 and nightly (Version 1.1.0-DEV.263 (2018-09-15), commit e2c98780e2) on MacOS 10.13.6. In Julia 1.0 the error is:

    fatal: error thrown and no exception handler available.
    MethodError(f=typeof(Base.convert)(), args=(Tuple{}, ()), world=0x00000000000061af)
    rec_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/stackwalk.c:94
    record_backtrace at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:246 [inlined]
    jl_throw at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:577
    jl_method_error_bare at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1614
    jl_method_error at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1632
    jl_lookup_generic_ at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:2159
    jl_apply_generic at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:2179
    Type at ./iterators.jl:169
    pairs at ./iterators.jl:226
    #printstyled at ./none:0
    jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
    display_error at ./client.jl:93
    jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
    display_error at ./client.jl:102
    jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
    jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1536 [inlined]
    jl_f__apply at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:556
    jl_f__apply_latest at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:594
    #invokelatest#1 at ./essentials.jl:686 [inlined]
    invokelatest at ./essentials.jl:685 [inlined]
    _start at ./client.jl:423
    true_main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
    main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)

For v1.1 the error is similar, with some differences in line numbers.

**Comment by yuyichao** [comment]
You are overriding base method which is one of the worst kind of type piracy.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/issues/27472 https://github.com/JuliaLang/julia/issues/26311 https://github.com/JuliaLang/julia/issues/24122 https://github.com/JuliaLang/julia/issues/24078 https://github.com/JuliaLang/julia/issues/23605 https://github.com/JuliaLang/julia/issues/22132 https://github.com/JuliaLang/julia/issues/21944 https://github.com/JuliaLang/julia/issues/20945
