### ISSUE TITLE
Overwriting .ji files for modules with the same name (in Main)

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/julia#29330]
I posted this on discourse but didn't get any feedback on it: 
https://discourse.julialang.org/t/overwriting-ji-files-for-modules-with-the-same-name/15228

I'm a bit concerned, especially as I envision multiple apps running on the same server, at the same time -- many of them with possibly different yet identically named modules (think `User`, `Order`, etc). Or having a staging app running in parallel with a production one, with different code in the same modules. 

It seems very limiting to identify a file by name alone for modules loaded into `Main`.

**Comment by StefanKarpinski** [comment]
@KristofferC, can you do that thing where you move this issue over to Pkg.jl?

**Comment by KristofferC** [comment]
I could but I'm not sure what Pkg has to do with this. I don't think the example given in discourse even touch Pkg code.

**Comment by StefanKarpinski** [comment]
I guess that's true, it's more of a code loading and precompilation issue. Unless I'm misunderstanding the issue entirely (which is quite possible).

**Comment by essenciary** [comment]
The issue is that if there's a module `A` being loaded in `Main`, it's going to be precompiled as `.julia/compiled/v1.0/A.ji`. 

If there's another REPL session running in parallel and loading a different `A` module in `Main`, the `.ji` files will overwrite each other. 

At some point, the app with the overwritten cache throws a `module is not stored in the source-text cache` error. 

I can imagine that running multiple apps in parallel might not be common yet -- but it does happen when hosting multiple web apps on a server.

**Comment by KristofferC** [comment]
Different packages have different UUIDs though, and get compiled to `compiled/v1.1/UUID_SLUG.ji` where `UUID_SLUG` is unique to that UUID. What is the content of the file with `A` and how do you include it?

**Comment by essenciary** [comment]
Yes, but these are not packages -- these are standalone Julia apps. Give me a minute, I'll share my test.

**Comment by KristofferC** [comment]
> these are standalone Julia apps

I don't know what that means :).

**Comment by essenciary** [comment]
App -- application? :) 

If I understand correctly the docs, I think we're referring at pretty much the same thing. 

Per the docs: 
```
Application: a project which provides standalone functionality not intended to be reused by other Julia projects. For example a web application or a commmand-line utility
```

**Comment by vtjnash** [comment]
These are stored by UUID now
