### ISSUE TITLE
environment vars on Windows should be case-insensitive

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#29334]
Disclaimer: I don't personally use Windows and I inferred this behavior only through appveyor. So maybe I'm missing some points here.

Anyway, how do you update `PATH` to be used for `setenv(command::Cmd, env)` on Windows?  For example, if I do

```julia
env_var = copy(ENV)
env_var["PATH"] = "some_new_path" * ';' * env_var["PATH"]
setenv(command::Cmd, env_var)
```

it doesn't work since the original PATH is in `env_var["Path"]` not `env_var["PATH"]`.  I had to [implement](https://github.com/JuliaPy/Conda.jl/blob/dfdfa387ab3a8d98bf038bf2ccbde3641db5c870/src/Conda.jl#L118-L121) something like this (https://github.com/JuliaPy/Conda.jl/pull/121#discussion_r219715161):

```julia
env_var = copy(ENV)
all_keys = collect(keys(env_var))
ikey = findfirst(x -> uppercase(x) == "PATH", all_keys)
has_key = ikey !== nothing
path_key = has_key ? all_keys[ikey] : "PATH"
if has_key
    env_var[path_key] = extra_path * path_sep * env_var[path_key]
else
    env_var[path_key] = extra_path
end
```

I tried `empty!(ENV); merge!(ENV, env_var)` but apparently `empty!(ENV)` is not implemented (at least on Linux).  Also, it would have emitted bunch of syscalls so maybe not a good idea in the first place.

So, I thought maybe `Base` needs to have a case-insensitive (in-memory) dictionary and `copy(ENV)` on Windows should return it.  It also facilitates cross-platform testing.

cc: @stevengj

**Comment by stevengj** [comment]
It seems like `Base.EnvDict` should treat the keys case-insensitively on Windows:

* Make key lookups (`getindex`, `haskey`, etcetera) case-insensitive.

* Always display the keys as uppercase

* `copy(ENV)` should return a `Dict` with uppercase keys.

Or does it do this already?

**Comment by stevengj** [comment]
See e.g. dotnet/corefx#13146 and cucumber/aruba#291 for related discussions in other languages.

**Comment by tkf** [comment]
I thought `ENV` was already case-insensitive as it just wraps syscalls. For example `getindex` just calls:

https://github.com/JuliaLang/julia/blob/fa7d1a9b48cb46f1467012425f05c1d350859a0d/base/env.jl#L9-L23

The problem I wanted to brought up here is:

* What (should) happen for `run(setenv(..., Dict("PATH"=>"...", "Path"=>"...")))`?
* Similarly, what should happen when `merge!(ENV, env)` when `env` has the overlapping keys?

> `copy(ENV)` should return a `Dict` with uppercase keys.

Yes, I think this is a good idea (on Windows). (On Linux, I see that `copy(ENV)` calls `copy(::AbstractDict)` (which is fine on Linux).  Not sure if it dispatches to other method in Windows.)

**Comment by tkf** [comment]
`merge!(ENV, Dict("key" => "1", "KEY" => "2"))` doesn't throw:

https://ci.appveyor.com/project/tkf/myplayground-jl/build/job/4pej3sggfba38gc8#L98

`setenv(cmd, env)` doesn't throw when `env` has overlapping keys:

https://ci.appveyor.com/project/tkf/myplayground-jl/build/job/4pej3sggfba38gc8#L110

code: https://github.com/tkf/MyPlayground.jl/blob/32ee7fce51a7512d0e2a91a4123278e4a9f3965a/test/runtests.jl

**Comment by stevengj** [comment]
What case does `keys(ENV)` return?  My impression was that the `GetEnvironmentVariables` is case-preserving even though `getindex` is case-insensitive.  If so, I think these should be uppercased on windows.

**Comment by tkf** [comment]
> What case does keys(ENV) return?

Not the direct answer, but see the output of `setdiff(keys(ENV), Set(map(uppercase, collect(keys(ENV))))` above.

> My impression was that the GetEnvironmentVariables is case-preserving even though getindex is case-insensitive.

Yeah, it looks like so. Here is the output of `display(ENV)`:

```
Base.EnvDict with 102 entries:
  "7zip" => "\"C:\\Program Files\\7-Zip\\7z.exe\""
  "=::" => "::\\"
  "=C:" => "C:\\projects\\myplayground-jl\\test"
  "ALLUSERSPROFILE" => "C:\\ProgramData"
  "APPDATA" => "C:\\Users\\appveyor\\AppData\\Roaming"
  "APPVEYOR" => "True"
  "APPVEYOR_ACCOUNT_NAME" => "tkf"
  "APPVEYOR_API_URL" => "http://localhost:1035/"
  "APPVEYOR_BUILD_AGENT_HYPERV_NIC_CONFIGURED" => "true"
  "APPVEYOR_BUILD_FOLDER" => "C:\\projects\\myplayground-jl"
  "APPVEYOR_BUILD_ID" => "19015984"
  "APPVEYOR_BUILD_NUMBER" => "2"
  "APPVEYOR_BUILD_VERSION" => "1.0.2"
  "APPVEYOR_BUILD_WORKER_IMAGE" => "Visual Studio 2015"
  "APPVEYOR_JOB_ID" => "4pej3sggfba38gc8"
  "APPVEYOR_JOB_NAME" => "Environment: julia_version=1; Platform: x86"
  "APPVEYOR_JOB_NUMBER" => "1"
  "APPVEYOR_PROJECT_ID" => "495883"
  "APPVEYOR_PROJECT_NAME" => "MyPlayground.jl"
  "APPVEYOR_PROJECT_SLUG" => "myplayground-jl"
  "APPVEYOR_REPO_BRANCH" => "appveyor/main"
  "APPVEYOR_REPO_COMMIT" => "32ee7fce51a7512d0e2a91a4123278e4a9f3965a"
  "APPVEYOR_REPO_COMMIT_AUTHOR" => "Takafumi Arakaki"
  "APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL" => "aka.tkf@gmail.com"
  "APPVEYOR_REPO_COMMIT_MESSAGE" => "Test ENV canse-(in)sensitivity"
  "APPVEYOR_REPO_COMMIT_TIMESTAMP" => "2018-09-24T22:14:51.0000000Z"
  "APPVEYOR_REPO_NAME" => "tkf/MyPlayground.jl"
  "APPVEYOR_REPO_PROVIDER" => "gitHub"
  "APPVEYOR_REPO_SCM" => "git"
  "APPVEYOR_REPO_TAG" => "false"
  "APPVEYOR_URL" => "https://ci.appveyor.com"
  "APR_ICONV_PATH" => "C:\\Program Files (x86)\\Subversion\\iconv"
  "AVVM_DOWNLOAD_URL" => "https://appveyordownloads.blob.core.windows.net/avvm"
  "ChocolateyInstall" => "C:\\ProgramData\\chocolatey"
  "ChocolateyLastPathUpdate" => "Fri Jan 19 03:37:46 2018"
  "CI" => "True"
  "CI_LINUX" => "False"
  "CI_WINDOWS" => "True"
  "CodeContractsInstallDir" => "C:\\Program Files (x86)\\Microsoft\\Contracts\\"
  "CommonProgramFiles
```

https://ci.appveyor.com/project/tkf/myplayground-jl/build/job/4pej3sggfba38gc8#L57
