### ISSUE TITLE
Proxy credential (in download.jl) on windows

### ISSUE THREAD

**Issue by haavardhvarnes** [JuliaLang/julia#29343]
In windows, using default credentials on proxy could be included with something like this (starting from line 8 in download.jl):
```julia
function download(url::AbstractString, filename::AbstractString)
    ps = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
    tls12 = "[System.Net.ServicePointManager]::SecurityProtocol =[System.Net.SecurityProtocolType]::Tls12"
    # client = "New-Object System.Net.Webclient"
    cl = string(Char('$'), "client = New-Object System.Net.Webclient")

    prxy = string(Char('$'), "client.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials")
    # in the following we escape ' with '' (see https://ss64.com/ps/syntax-esc.html)
    # downloadfile = "($client).DownloadFile('$(replace(url, "'" => "''"))', '$(replace(filename, "'" => "''"))')"
    downloadfile = string(Char('$'), "client.DownloadFile('$(replace(url, "'" => "''"))', '$(replace(filename, "'" => "''"))')")
    # PowerShell v3 or later is required for Tls12
    # proc = run(pipeline(`$ps -Version 3 -NoProfile -Command "$tls12; $client;$ $downloadfile"`; stderr=stderr); wait=false)
    proc = run(pipeline(`$ps -Version 3 -NoProfile -Command "$tls12; $cl; $prxy; $downloadfile"`; stderr=stderr); wait=false)
    if !success(proc)
        if proc.exitcode % Int32 == -393216
            # appears to be "wrong version" exit code, based on
            # https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-startup-tasks-common
            error("Downloading files requires Windows Management Framework 3.0 or later.")
        end
        pipeline_error(proc)
    end
    filename
end
```

This is adopted from: https://stackoverflow.com/questions/14263359/access-web-using-powershell-and-proxy

**Comment by GeraldKaeferle** [comment]
Same problem: Pkg works but calling download for dependencies doesn't.

There is a solution in Pkg.jl

proxy error 407 on corporate proxy [#647](https://github.com/JuliaLang/Pkg.jl/issues/647)
use default proxy credentials when downloading via powershell [#714](https://github.com/JuliaLang/Pkg.jl/pull/714)

Unfortunatly there is the same issue on  BinaryProvider in PlatformEngines.jl  and in BinDeps.

**Comment by GeraldKaeferle** [comment]
A workaround for this problem use this code in your julia session or in ~/.julia/config/startup.jl file.

`
 function Base.download(url::AbstractString, filename::AbstractString)
	ps = joinpath(get(ENV, "SYSTEMROOT", "C:\\Windows"), "System32\\WindowsPowerShell\\v1.0\\powershell.exe")
	tls12 = "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
	proxydefaultcredentials = "[net.webrequest]::defaultwebproxy.credentials = [net.credentialcache]::defaultcredentials"
	client = "New-Object System.Net.Webclient"
	# in the following we escape ' with '' (see https://ss64.com/ps/syntax-esc.html)
	downloadfile = "($client).DownloadFile('$(replace(url, "'" => "''"))', '$(replace(filename, "'" => "''"))')"
	# PowerShell v3 or later is required for Tls12
	proc = run(pipeline(`$ps -Version 3 -NoProfile -Command "$tls12; $proxydefaultcredentials; $downloadfile"`; stderr=stderr); wait=false)
	if !success(proc)
		if proc.exitcode % Int32 == -393216
			# appears to be "wrong version" exit code, based on
			# https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-startup-tasks-common
			error("Downloading files requires Windows Management Framework 3.0 or later.")
		end
		pipeline_error(proc)
	end
	filename
end
`

This line `proxydefaultcredentials = "[net.webrequest]::defaultwebproxy.credentials = [net.credentialcache]::defaultcredentials"` tells the request to us network credentials for web proxy authentication.  This works without any proxy as well.

Finally is used in this line `proc = run(pipeline(`$ps -Version 3 -NoProfile -Command "$tls12; $proxydefaultcredentials; $downloadfile"`; stderr=stderr); wait=false)` after Tls12 command token

**Comment by musm** [comment]
Hi @GeraldKaeferle  and @haavardhvarnes, is there any chance you are on the spring creators update build of windows ? 

If so I wonder if https://github.com/JuliaLang/julia/pull/31173 fixes issues with the download function?

**Comment by GeraldKaeferle** [comment]
Hi @musm , I'm still on Windows 7.

**Comment by ViralBShah** [comment]
We have done a bunch of work on improving proxy support, and hopefully this is fixed. Please reopen if necesary.
