### ISSUE TITLE
row-vector/column-vector products should act like dot products

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#2936]
If `x` and `y` are vectors of the same length, then `(x*x')*y` works but `x*(x'*y)` does not (it gives `ERROR: no method *(Array{Float64,1},Array{Float64,1})`).  The latter can only be accomplished with `x*dot(x,y)`.

This is surprising and, I think, undesirable: `*` should be associative (neglecting floating-point roundoff errors, of course).

Another way of putting it is that `x'*y`, or any product of a row vector and a column vector, should return a scalar, not a vector of length 1.  (And it should probably just call the BLAS `dot`.)

**Comment by pabloferz** [comment]
This works now, right?

**Comment by StefanKarpinski** [comment]
Yes:

```jl
julia> x = rand(3)
3-element Array{Float64,1}:
 0.61878
 0.178213
 0.0933086

julia> y = rand(3)
3-element Array{Float64,1}:
 0.954149
 0.0926293
 0.336523

julia> (x*x')*y
3-element Array{Float64,1}:
 0.394978
 0.113756
 0.0595605

julia> x*(x'*y)
3-element Array{Float64,1}:
 0.394978
 0.113756
 0.0595605
```
