### ISSUE TITLE
mechanism for obtaining local variable names and values

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#29366]
It could be useful for debugging to be able to easily get the names and values of all variables in scope, e.g. so you don't have to manually write them all in a call to `@show`. This could be provided as a macro `@locals` (though needs to be implemented specially in lowering, since the set of variables in scope is not available during macro expansion), returning a dictionary, similar to `locals()` in python: https://docs.python.org/3/library/functions.html#locals

Thoughts?

**Comment by ararslan** [comment]
Is this different from `varinfo()`?

**Comment by JeffBezanson** [comment]
`varinfo` only applies to globals. For locals, it can't be implemented as a function, and you'd also probably rather get the values themselves rather than a table summarizing them. `names` and `eval` give you everything you need for globals.

**Comment by mattcbro** [comment]
This would be super useful.  I see some code here but does it actually exist in any version of Julia?  I can't seem to find it in Julia 1.0.3.   @locals is not defined in Base.

**Comment by KristofferC** [comment]
It exists in the downloadable release candidate for julia 1.1.0.
