### ISSUE TITLE
illegal instruction in try/finally

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#29382]
To reproduce:
1. Check out this PR: https://github.com/JuliaOpt/JuMP.jl/pull/1498
2. Run JuMP's tests
3. Wait a few minutes
4. Expected output: https://travis-ci.org/JuliaOpt/JuMP.jl/jobs/433523251#L864

@tkoolen correctly guessed an issue with `try/finally`. The illegal instruction goes away when I comment out the `try/finally/end` lines at https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/fdad2fb72a93be219573e48248b141380c821ee8/src/GLPKInterfaceMIP.jl#L457-L471 leaving the code in between.

Note that this code involves callbacks through C back to Julia which has caused issues with exception handling in the past (https://github.com/JuliaLang/julia/issues/14284).

**Comment by mlubin** [comment]
Reduced test case. Using JuMP@1fd17f17 (`release-0.18`) and GLPKMathProgInterface v0.4.3 
```julia
using JuMP, GLPKMathProgInterface

mod = Model(solver=GLPKSolverMIP())
@variable(mod, 0 <= x <= 2, Int)
@variable(mod, 0 <= y <= 2, Int)
@objective(mod, Max, y + 0.5x)
function corners(cb)
    x_val = getvalue(x)
    y_val = getvalue(y)
    TOL = 1e-6
    if y_val + x_val > 3 + TOL
        @lazyconstraint(cb, y + 0.5x + 0.5x <= 3)
    end
end
addlazycallback(mod, corners)
@show solve(mod)
```

Interestingly enough, the crash goes away with https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/54. So it looks like it was the missing method errors that turned into illegal instructions.

**Comment by c42f** [comment]
This sounds familiar, I've seen the missing method error turn into an illegal instruction. I think it was over at https://github.com/JuliaArrays/StaticArrays.jl/issues/493, but annoyingly I can't put my finger on the exact code now.

**Comment by ViralBShah** [comment]
Reopen if still an issue.
