### ISSUE TITLE
readdlm header is an Array{AbstractString,2}

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#29385]
```julia
open("foo.csv", "w") do io
    write(io, "a, b, c")
end
using DelimitedFiles
_, header = readdlm("foo.csv", header=true)
typeof(header)
```

is `Array{AbstractString,2}`. First; should it be `Array{String, 2}`? Second, should it be `Vector{String}`?

The eltype is probably currently `AbstractString` because of the big `String` -> `AbstractString` change, https://github.com/JuliaLang/julia/blame/da964d6178c5b22e9dc4b1dd8489f052f4b73e94/stdlib/DelimitedFiles/src/DelimitedFiles.jl#L310.

**Comment by derikk** [comment]
Ran into this issue as well. It looks like DelimitedFiles.jl has hardly been updated over the past couple years. Is CSV.jl now recommended for most use cases?

**Comment by quinnj** [comment]
Yes, please use CSV.jl for any delimited file that isn't basically a matrix of a single type.
