### ISSUE TITLE
run wait=false problem on WINDOWS cmd

### ISSUE THREAD

**Issue by leu14** [JuliaLang/julia#29387]
I want to run this command "run(`notepad.exe`,wait=false)" in a Julia file "test.jl" from the WINDOWS command line "...\system32\cmd.exe" (WINDOWS 10 64-bit)

"test.jl" looks like this:
println("before call")
run(`notepad.exe`,wait=false)
println("after call")

EDIT: The backticks are not visible in the report, but I used them in the call to run.

When started from the command line like this:
c:\Julia-1.0.0\bin\julia.exe test.jl

println calls get processed both and Julia ends, but "notepad" does not stay open. With luck I see it come up, but it immediately closes again, though most of the time I see nothing of the program.

In REPL everything is fine.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
