### ISSUE TITLE
Missing division of time periods

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#29395]
Currently, 

```julia
julia> Millisecond(10) / Millisecond(1)
10.0

julia> Minute(10) / Millisecond(1)
ERROR: MethodError: no method matching /(::Minute, ::Millisecond)
```

If division is supported at all, it would be very convenient to be able to divide across compatible units.

**Comment by oscardssmith** [comment]
The problem is that there is no unique answer here. Consider `Year(1)/Day(1)` should this be 364 or 365?

**Comment by cstjean** [comment]
Right, it should only be done for units that can be converted.

```julia
julia> convert(Millisecond, Year(1))
ERROR: MethodError: Cannot `convert` an object of type Year to an object of type Millisecond
Closest candidates are:
  convert(::Type{Millisecond}, ::Second) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Dates/src/periods.jl:421
  convert(::Type{Millisecond}, ::Minute) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Dates/src/periods.jl:421
  convert(::Type{Millisecond}, ::Hour) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Dates/src/periods.jl:421
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> convert(Millisecond, Day(1))
86400000 milliseconds
``` 

Converting the bigger of the two units to the smaller unit seems like the best way to go about it.

**Comment by oscardssmith** [comment]
in that case, only second to millisecond should work, as leap seconds allow impression for all larger units

**Comment by oscardssmith** [comment]
it's unfortunate, but time units really sex sic suck

**Comment by cstjean** [comment]
> in that case, only second to millisecond should work, as leap seconds allow impression for all larger units

I think that `Dates` is not meant for high-fidelity date manipulation. Its `DateTime + Period` arithmetic is not even associative 😛 

```julia
julia> DateTime(2017, 2) + (Day(30) + Month(1))
2017-03-31T00:00:00

julia> (DateTime(2017, 2) + Day(30)) + Month(1)
2017-04-03T00:00:00
```

In any case, all I'm asking is for `/` to be the natural extension of `convert`.

**Comment by laborg** [comment]
This has been implemented in https://github.com/JuliaLang/julia/pull/43360
```julia
julia> Minute(10) / Millisecond(1)
600000.0
```
