### ISSUE TITLE
Performance issue with iteration over StepRange{<:TimeType}

### ISSUE THREAD

**Issue by frigaardj** [JuliaLang/julia#29403]
Iteration on a TimeType range is defined [here](https://github.com/JuliaLang/julia/blob/v1.0.0/stdlib/Dates/src/ranges.jl#L55) as:
```
Base.iterate(r::StepRange{<:TimeType}, i::Int=0) = length(r) <= i ? nothing : (r.start + r.step*i, i + 1)
```
This is inefficient due to the `length(r)` call on every iteration. 

A trivial improvement would be caching the length at the start e.g.:
```
Base.iterate(r::StepRange{<:TimeType}, state::Tuple{Int, Int}=(length(r), 0)) = begin l, i = state; l <= i ? nothing : (r.start + r.step*i, (l, i + 1)) end
```
I'm new to Julia - so just wanted to check if there were no obvious problems with this. If not, I'll submit a PR.

Performance improvement:
before
```
julia> @btime collect(Date(2010, 1, 1):Day(1):Date(2018, 1, 1));
  15.422 μs (2 allocations: 22.95 KiB)
```
after
```
julia> @btime collect(Date(2010, 1, 1):Day(1):Date(2018, 1, 1));
  1.505 μs (2 allocations: 22.95 KiB)
```

**Comment by frigaardj** [comment]
Just made a PR for this.

**Comment by nalimilan** [comment]
Good catch. I wonder why the compiler isn't able to hoist the call to `length` out of the loop despite inlining. I've made a few tests, and it appears that adding `@inline` to the relevant `iterate` and `length` methods improves performance a lot. Can you check whether it can make it unnecessary to change the iteration state as in your PR?

**Comment by frigaardj** [comment]
I played around with this a bit, and adding `@inline` to all the little functions in that file improves things but doesn't seem to get it down all the way to the speed that my PR achieves (PR takes 950ns on above example, inlining takes ~4us, original method takes ~15us). I tried to debug why the compiler couldn't do this, but I'm not very familiar with the tools so couldn't work it out.

**Comment by nalimilan** [comment]
OK. Hopefully somebody who knows the compiler can comment on whether that's expected. Maybe I'm asking too much from it.

**Comment by quinnj** [comment]
I've seen similar performance issues before w/ recomputing things on each iteration (most recently I noticed a similar performance hit in iterating DataFrame rows that also recomputes length on each iteration: https://github.com/JuliaData/DataFrames.jl/blob/master/src/abstractdataframe/iteration.jl#L22). In general, I don't think I've seen compiler optimizations that would hoist this call; I don't think there's any way it could assume that `length(rng)` wouldn't change from iteration to iteration, so the solution in #29404 seems optimal to me right now. @vtjnash @Keno, is there any other compiler hint/trick that would allow hoisting this kind of call out of the inner iteration loop?

**Comment by frigaardj** [comment]
Yeah, that makes sense given that the `iterate` calls are happening 'externally', e.g. in `collect`, and that arbitrary stuff could be done to the object between those calls.

**Comment by vtjnash** [comment]
That compiler optimization is some form of loop-invariant-code-motion. The issue to track enabling that more is #29285.
