### ISSUE TITLE
multiple issues with binary operators applied to arguments of mixed precision

### ISSUE THREAD

**Issue by bsxfan** [JuliaLang/julia#2941]
@JeffBezanson and @ViralBShah , I'm creating this issue to subsume issues #2853 and #2933, in the hope that they can be addressed together with a single solution.

* #2853 was closed with a commit that introduced a bug, see details below
* #2933 was closed without being resolved, in order to include it in this issue

The general problem is that operations like matrix-matrix or matrix-vector multiplication are fast when dispatched to BLAS, but this can only be done if the arguments are of the same precision. Otherwise Julia defaults to slower implementations. Converting (and therefore unfortunately copying) one of the arguments to make the types agree and then sending to BLAS can be much faster.

In a solution, I propose that the following be addressed:
- [ ] Include  operators *, \ and /
- [ ] consider matrix and vector arguments
- [ ] consider mixtures of precisions (32 vs 64 bits) and maybe also Integer and Rational
- [ ] consider mixtrures of real and complex types
- [ ] consider the interaction of multiplication and transposition

Although issue  #2853 was addressed via commit https://github.com/JuliaLang/julia/commit/4b7ef605cf0e4ba852b76d9b1f0775e3319013a2, the following problems remain:

- [x] New bug: The solution fails to cater for P = A*X where A::StridedMatrix{Float64} and X::StridedVector{Complex64}. It crashes with InexactError(), because it is trying to convert from single-precision complex to double-precision real.
- [x] For matrix A and vector v, the element type of P = A*v depends only on the element type of A. I think it should depend on both. This is what causes the above crash and it also causes perhaps unexpected behaviour: Elsewhere in Julia, one finds for example:

    `promote_type(Float32,Float64) == promote_type(Float64,Float64) == Float64`

while in the case of P = A*v, v will be downcast (not promoted) to 32-bit precision if A is of 32-bit precision.

- [ ] matrix-matrix multiplication and the operators \ and / have not been addressed.

**Comment by andreasnoack** [comment]
I don't think there is much else to do here. Now we promote to common element type for multiplication and solve and we reinterpret complex arrays to real when possible.
