### ISSUE TITLE
Array slicing step / aka Extended Slices

### ISSUE THREAD

**Issue by belgiancoder** [JuliaLang/julia#29427]
Suppose this elegant python code
```
>>> def f(*a, step=1): print(*a[::step])
>>> f(1,2,3,4, step=-1)
4 3 2 1
>>> f(0,1,2,3,4,5,6,step=2)
0 2 4 6
>>> f(1,2,3,4)
1 2 3 4
```
[More on Extended slices](https://docs.python.org/2.3/whatsnew/section-slices.html)
I don't see an elegant way of doing this in Julia, maybe like that:
```
julia> y(a...; step=1) = println([i for (n, i) in enumerate((step>0) ? a : reverse(a)) if (n-1)%abs(step)==0]...)
y (generic function with 1 method)

julia> y(1,2,3,4)
1234

julia> y(1,2,3,4,step=2)
13

julia> y(1,2,3,4,step=-2)
42

```
But it would be a great thing to add extended slices to Julia
The Python function is 17 char long, the Julia one is 123 char long, it also requires some avoidable brain stretching.

**Comment by yuyichao** [comment]
`y(a...; step=1) = println(step > 0 ? a[1:step:end] : a[end:step:1])`. Expression length at this level is never the goal. The inferability to the compiler and reader is. It's very important for the compiler to know what the first element is, which isn't possible for the python code. That's exactly why the initial and final steps are required in the julia code.

**Comment by yuyichao** [comment]
See also, https://github.com/JuliaLang/julia/issues/28276 and related negative step issues (they are the same class of fancy indexing behavior that is extremely hard on the compiler and reader).

**Comment by belgiancoder** [comment]
I agree that negative *indexing* from the end feels wrong in Julia (offset etc) but negative *step* doesn't. You can step forwards, you should be able to step backwards.
while I like this solution:
`step > 0 ? a[1:step:end] : a[end:step:1]`
this is even better
`a[1:step:end]`

Anyway, thanks.
