### ISSUE TITLE
Weird behaviour with optional args in varargs

### ISSUE THREAD

**Issue by belgiancoder** [JuliaLang/julia#29426]
Optional args are impossible with functions that take a variable number of arguments :
```
julia> f(a..., reversed=false) = println((reversed ? reverse(a) : a)...)
ERROR: syntax: invalid ... on non-final argument
```
But, you can put them before right ?
```
julia> f(reversed=false, a...) = println((reversed ? reverse(a) : a)...)
f (generic function with 5 methods)
```
Yes, but no, because now, there are not optional : 
```
julia> f(1,2,3,4)
ERROR: TypeError: non-boolean (Int64) used in boolean context
Stacktrace:
 [1] f(::Int64, ::Int64, ::Int64, ::Vararg{Int64,N} where N) at ./REPL[130]:1
 [2] top-level scope at none:0
```
So... what is the problem with ` f(a..., reversed=false)`.
Well, there is no problem with that, python handles it :
```
>>> print(1,2,3,4, sep=' - ', flush=True)
1 - 2 - 3 - 4
```
**Since there is no problem, why does it raise an error in Julia ?**

**Comment by yuyichao** [comment]
> Yes, but no, because now, there are not optional :

It **is** optional.

```julia
julia> f(reversed=false, a...) = println((reversed ? reverse(a) : a)...)
f (generic function with 2 methods)

julia> f()

```

Optional parameter is a simple dispatch based on the number of arguments and pretty much the only thing sensible to do here is to allow 0 or more than 1 arguments. If you need type based dispatch, which you didn't even specify, you should create two functions instead with the correct type on the argument you want. Or you should just use keyword argument instead.

> Well, there is no problem with that, python handles it :

No it doesn't, that's not optional parameter, it's keyword (only) parameter. Julia handles that too.

**Comment by StefanKarpinski** [comment]
It may be better to ask questions about things like this that may or may not be actual issues on https://discourse.julialang.org/ rather than open issues on GitHub. If something is really an issue after asking about it, it's easy enough to open an issue and link back to the discourse thread.

**Comment by JeffBezanson** [comment]
Yes I think here you want a keyword argument: `f(a...; reversed=false) = ...`.
