### ISSUE TITLE
Build broken on OS X Mojave

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#29433]
I just upgraded and ran `xcode-select --install`, but get the following error:
```julia
Warning: Possible change of value in conversion from INTEGER(8) to REAL(4) at (1) [-Wconversion]
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
make[3]: *** [sblat1] Error 1
make[2]: *** [tests] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0' if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [scratch/openblas-e8a68ef261a33568b0f0cf53e0e2287e9f12e69e/build-compiled] Error 1
make: *** [julia-deps] Error 2
```

**Comment by ajkeller34** [comment]
I'm also running Mojave, but I cannot reproduce when building the release-1.0 branch. I ran `make deps clean` first.

```
julia> versioninfo()
Julia Version 1.0.2-pre.0
Commit 4aea3d2b7c* (2018-09-30 15:02 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.0.0)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by dlfivefifty** [comment]
No luck: I already have 
```julia
[solver-mbook:~/Projects/julia] solver% xcodebuild -version
Xcode 10.0
Build version 10A255
```
and I don't see how to reinstall Xcode.

**Comment by tkoolen** [comment]
The suggested `make -C deps clean-openblas` didn't work I assume? Is this a clean build?

**Comment by dlfivefifty** [comment]
Yes it was a clean build. 

I was having trouble before I upgraded to Mojave (https://github.com/JuliaMath/SpecialFunctions.jl/issues/123) so perhaps the next step is to reinstall the OS from scratch. (I don't think I've done that in the last 10 years.... hopefully I can figure it out.)

**Comment by Roger-luo** [comment]
Have trouble build on Mojave too: https://github.com/JuliaLang/libosxunwind/issues/11

**Comment by dlfivefifty** [comment]
I think this is the key, from the XCode 10 [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes) (still need to see if I can get it working):
> The Command Line Tools package installs the macOS system headers inside the macOS SDK. Software that compiles with the installed tools will search for headers within the macOS SDK provided by either Xcode at:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
```
or the Command Line Tools at:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
depending on which is selected using xcode-select.
The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at:
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
 To make sure that you're using the intended version of the command line tools, run xcode-select -s <path to Xcode> or xcode select -s /Library/Developer/CommandLineTools after installing.

**Comment by pablosanjose** [comment]
I also had problems building after upgrading to Mojave, but it wasn't Xcode. It seems it was rather an issue with my homebrew installation that got corrupted by the upgrade, somehow. This thread reported similar problems, and the combined answers there fixed the problem for me: 
https://stackoverflow.com/questions/47635408/cythonizing-fails-because-of-unknown-type-name-uint64-t

**Comment by Roger-luo** [comment]
@pablosanjose I think it will be fixed by JuliaLang/libosxunwind#11 have a try.

**Comment by pablosanjose** [comment]
> @pablosanjose I think it will be fixed by [JuliaLang/libosxunwind#11](https://github.com/JuliaLang/libosxunwind/issues/11) have a try.

Yay, that did it! It's now compiling LLVM (clean clone), so it'll be a while. Thanks a lot @Roger-luo!

**Comment by dlfivefifty** [comment]
Reinstalling homebrew and gcc fixed this for me.

**Comment by quinnj** [comment]
FWIW, I just had to install `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` in order to get source build working on mojave.

**Comment by BenjaminBorn** [comment]
Thanks @quinnj! Running `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /` solved the issue for me as well.
