### ISSUE TITLE
Trying to import my package and I’m getting errors

### ISSUE THREAD

**Issue by TheOnlyArtz** [JuliaLang/julia#29438]
Hey, I know you don't like questions here or issues of that kind BUT I'm not really getting much help on discourse as you can see [here](https://discourse.julialang.org/t/trying-to-import-my-package-and-im-getting-errors/15694)

Basically:
 I’ve uploaded my package to Github and did
`Pkg.clone("REPO")` in order to download the package from the source.
As soon as I'm tried to use it `import Julicord` I'm getting warnings:
![image](https://user-images.githubusercontent.com/30025874/46257011-60fe3100-c4bb-11e8-957d-1912fd79f86c.png)
And I don't understand what to do, this is my Project.toml
```julia
authors = ["TheOnlyArtz <MAIL>", "PurgePJ <MAIL>"]
name = "Julicord"
uuid = "91c305b0-c482-11e8-244f-23e78ed5e04c"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
```

**Comment by yuyichao** [comment]
> I'm not really getting much help on discourse as you can see here

You mean in less than two hours during night time in the US?

**Comment by StefanKarpinski** [comment]
Seriously, please stop asking questions on GitHub or you'll get blocked.

**Comment by TheOnlyArtz** [comment]
> Seriously, please stop asking questions on GitHub or you'll get blocked.

Okay sorry I'll stop, I'm just not getting answers to my questions and it's frustrating, I got a [question](https://discourse.julialang.org/t/how-to-import-a-module-and-keep-its-properties-i-saved-in-different-file/15684) that hangs for 9 hours now
and you guys are replying damn quick on GitHub
