### ISSUE TITLE
parseint_preamble bounds check fails for AbstractString

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#29451]
~`i <= ncodeunits(s)`~ should be `i <= endpos` ?
https://github.com/JuliaLang/julia/blob/1a1d6b6d1c636a822cf2da371dc41a5752e8c848/base/parse.jl#L75-L76

When I do `parse(Int, "0")` where `"0"` is an `AbstractString` and `ncodeunits` > `lastindex`, i get this:
`TypeError: in parseint_preamble, in typeassert, expected Tuple{Char,Int64}, got Nothing`

https://github.com/JuliaLang/julia/commit/1a1d6b6d1c636a822cf2da371dc41a5752e8c848#r30713661

Monkeypatching `parseint_preamble` for my string type with `i <= endpos` seems to fix the problem.

**Comment by StefanKarpinski** [comment]
Since there seems to be a fix in that monkey patch, would you be willing to make a PR to fix this in Base Julia?
