### ISSUE TITLE
`String` is not a good example of a `mutable struct`

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#29454]
In the docs on mapping julia types to C types,
it gives `String` as an example of a `mutable struct`

Which is not really a clear example.

https://github.com/JuliaLang/julia/blob/391f2dd2b5ac67da4a136673b1923d966b606439/doc/src/manual/calling-c-and-fortran-code.md#type-correspondences

**Comment by StefanKarpinski** [comment]
Yes, that is really a bad choice for that example.

**Comment by oxinabox** [comment]
There are very few good examples in `Base`,
We use very few mutable structs that are not type parametric,
or otherwise weird.


```
filter(names(Base)) do name
	T = try
		eval(name)
	catch
		return false
	end
	
	isconcretetype(T) &&
	T.mutable &&
	fieldcount(T) > 0 && # knocks out String
	nameof(T) == name && # Knock-out type-aliases
	!any(F <: Ptr for F in fieldtype.(T, fieldnames(T))) # Nothing Pointer based
end
```

Gives back:
```
4-element Array{Symbol,1}:
 :BitSet
 :Condition
 :Pipe
 :ReentrantLock
```

So it really looks like `BitSet` is our best option.

**Comment by KristofferC** [comment]
#29475
