### ISSUE TITLE
end ambiguity for malformed UTF-8 strings

### ISSUE THREAD

**Issue by schlurp** [JuliaLang/julia#29455]
When accessing UTF-8 strings, that are malformed, the behaviour of `end` and `[]` seems ambiguous. So if I access the last character via `a[end-1]` (`a` being the string), then for the malformed string, the last (malformed) whole character is returned, the same for a correct string. However, if I wish to cut of the last character via `a[1:end-1]`, then for the malformed string `end-1` seems to reference the byte position, for the well formed string it seems to reference the second-last character position.

**Example:** 

`a` is the malformed string, `b` is a valid string.

```
julia> a = "夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针\xe8\xa7"
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针\xe8\xa7"

julia> isvalid(a)
false

julia> a[end]
'\xe8\xa7': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> a[1:end-1]
ERROR: StringIndexError("夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针\xe8\xa7", 50)
Stacktrace:
 [1] string_index_err(::String, ::Int64) at ./strings/string.jl:12
 [2] getindex(::String, ::UnitRange{Int64}) at ./strings/string.jl:246
 [3] top-level scope at none:0

julia> b = "夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针"
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针"

julia> isvalid(b)
true

julia> b[end]
'针': Unicode U+9488 (category Lo: Letter, other)

julia> b[1:end-1]
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, "

```

Using `prevind` works as intended

```
julia> a[1:prevind(a, end)]
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针"
```

```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9* (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by StefanKarpinski** [comment]
When slicing into a string, both the start and end index of the index range must be valid indices that would yield characters when iterating over the string. Because of that, `a[1:end-1]` is wrong any time that the second-to-last character is multibyte, regardless of if the last character is valid or not (the fact that the last character is invalid here is a red herring, i.e. not relevant). You get the same error with a valid string:
```jl
julia> s = "αβγ"
"αβγ"

julia> s[1:end-1]
ERROR: StringIndexError("αβγ", 4)
Stacktrace:
 [1] string_index_err(::String, ::Int64) at ./strings/string.jl:12
 [2] getindex(::String, ::UnitRange{Int64}) at ./strings/string.jl:246
 [3] top-level scope at none:0
```

> Using `prevind` works as intended

This is the correct way to do this:
```jl
julia> a[1:prevind(a, end)]
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针"

julia> b[1:prevind(b, end)]
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, "

julia> s[1:prevind(s, end)]
"αβ"
```
The `chop` function provides a more convenient way to write this:
```jl
julia> chop(a, tail=1)
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, 针"

julia> chop(b, tail=1)
"夹紧螺母 ER 25 普通型, CortaaM5x0,8x23, "

julia> chop(s, tail=1)
"αβ"
```
It is quite possible that this is misdocumented somewhere as quite a lot of things changed between 0.6 and 1.0. If there's somewhere that the documentation can be improved, please let us know!

**Comment by schlurp** [comment]
Thanks for the explanation. So I see that I fell for the deception, that when the second last element of the string is a non-multibyte character, then `end-1` works. I am still confused about the meaning (or is type, the correct word) of `end` then. Does it refer to the last byte index of the string or the last character index of the string, since

```
julia> s = "αβγ"
"αβγ"
julia> s[end]
'γ': Unicode U+03b3 (category Ll: Letter, lowercase)
```

still works, even if the last byte index would index past the last byte of the γ character and then in my eyes would be invalid, where as I could follow that `end-1` would index the second last byte which is also in the middle of the γ character utf-8 encoding.

**Comment by StefanKarpinski** [comment]
`end` is always the last valid index into a collection, in this case the index of the last character that would be iterated from a string. Previously we allowed the end value of a slice to be either the first or last code unit index of the ending character which allowed `end-1` to work, but it was deemed safer to only allow valid starting indices. I’m still a bit ambivalent about that but by choosing the more restrictive behavior, we always have the option to be more lax in the future.

**Comment by schlurp** [comment]
Thanks for the clarification. I would propose to update the documentation along the lines as proposed in the referenced commit (please adjust language etc. appropriately) to make it more clear.

**Comment by laborg** [comment]
The documentation has been updated in https://github.com/JuliaLang/julia/pull/31049
