### ISSUE TITLE
Docs for 1.0.1 failed to deploy

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#29461]
The 1.0.1 tag failed to deploy documentation because the Documenter version was too old (0.19.1 still has some 0.7 deprecation): https://travis-ci.org/JuliaLang/julia/jobs/435064733#L4261-L4291

I will put together a PR against gh-pages in the next 1-2 days to do it manually, unless someone beats me to it.

Before 1.0.2, Documenter should also be updated on release-1.0. I can also do a PR against release-1.0 for that unless there are any objections to doing it this way.

**Comment by vchuravy** [comment]
That would be https://github.com/JuliaLang/julia/pull/28559, right? I marked it as backport so kristoffer's script should pick it up on the next run.

**Comment by mortenpi** [comment]
Yup, that should do. There was also #28792, but that was already backported to 1.0.1.
