### ISSUE TITLE
Disable USE_GPL_LIBS by default?

### ISSUE THREAD

**Issue by djmilstein** [JuliaLang/julia#29504]
Should we disable USE_GPL_LIBS by default? Having it enabled by default might discourage use in industry since commercial software accidentally linked with GPL software needs to be released under the GPL.

**Comment by KristofferC** [comment]
Don't think we need to have an open issue about this.

**Comment by djmilstein** [comment]
Agreed. I'm sorry for wasting your time on this - this perspective should
have occurred to me before I opened the issue.

**Comment by StefanKarpinski** [comment]
No worries! Doesn’t hurt to raise the idea.
