### ISSUE TITLE
Module() is unsafe

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#29503]
I just run into https://github.com/JuliaLang/julia/issues/28917, because I was using `Module(:name)` to create an isolated eval context.
I was wondering if Julia Base actually uses this pattern, and found one occurrence:
https://github.com/JuliaLang/julia/blob/4d06e004562b5061b2ac3691fe4ddd2b0acf5d71/base/loading.jl#L1075
I guess at least that particular line should get fixed, or even better, `Module()` should return a module that is gc rooted - if that's reasonable.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/28917

**Comment by SimonDanisch** [comment]
Well... it's not a dub - it brings concrete new issues to the table. Do you want me to post this to #28917 instead of opening a new issue?

**Comment by SimonDanisch** [comment]
Ok you changed the title of #28917 - guess that makes it clear.
