### ISSUE TITLE
UndefVarError: T not defined

### ISSUE THREAD

**Issue by Bishu1991** [JuliaLang/julia#29511]
So This is  the function I am trying to define:
function roots{T<:FinFieldElem}(f::PolyElem{T})
	fac = Nemo.factor(f)
	res = Dict{T, Int}()
	for index in fac
		P, exp = index
		if degree(P) == 1
			res[- coeff(P, 0)] = exp
		end
	end
	res = collect(res)
	return res
end

But every time I call the function it gives an error.

ERROR: LoadError: UndefVarError: T not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] include(::String) at ./client.jl:388
 [6] top-level scope at none:0
in expression starting at /home/cssc/myfile.jl:69

**Comment by quinnj** [comment]
You're using 0.6 syntax; in 0.7/1.0, you should do:
```julia
function roots(f::PolyElem{T}) where {T <: FinFieldElem}
...
```

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum and use GitHub only for verified issues.
