### ISSUE TITLE
Structured matrices with Range (off-)diagonals don't allow indexed mutation

### ISSUE THREAD

**Issue by mcognetta** [JuliaLang/julia#29516]
This is a more general issue compared to #28994 (and solving this would help when solving that issue).

Using UnitRange or StepRange in a Diagonal/Bidiagonal/Tridiagonal/Symtridiagonal matrix breaks mutation.

For example:
```
julia> D = Diagonal(1:5)
5×5 Diagonal{Int64,UnitRange{Int64}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅  ⋅
 ⋅  ⋅  3  ⋅  ⋅
 ⋅  ⋅  ⋅  4  ⋅
 ⋅  ⋅  ⋅  ⋅  5

julia> D[1,1] = 3
ERROR: setindex! not defined for UnitRange{Int64}
Stacktrace:
 [1] error(::String, ::Type) at ./error.jl:42
 [2] error_if_canonical_setindex(::IndexLinear, ::UnitRange{Int64}, ::Int64) at ./abstractarray.jl:1006
 [3] setindex! at ./abstractarray.jl:997 [inlined]
 [4] setindex!(::Diagonal{Int64,UnitRange{Int64}}, ::Int64, ::Int64, ::Int64) at /home/mc/github/julia-dev/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/diagonal.jl:99
 [5] top-level scope at none:0

julia> T = Tridiagonal(1:4, 1:5, 1:4)
5×5 Tridiagonal{Int64,UnitRange{Int64}}:
 1  1  ⋅  ⋅  ⋅
 1  2  2  ⋅  ⋅
 ⋅  2  3  3  ⋅
 ⋅  ⋅  3  4  4
 ⋅  ⋅  ⋅  4  5

julia> T[1,2] = 11
ERROR: setindex! not defined for UnitRange{Int64}
Stacktrace:
 [1] error(::String, ::Type) at ./error.jl:42
 [2] error_if_canonical_setindex(::IndexLinear, ::UnitRange{Int64}, ::Int64) at ./abstractarray.jl:1006
 [3] setindex! at ./abstractarray.jl:997 [inlined]
 [4] setindex!(::Tridiagonal{Int64,UnitRange{Int64}}, ::Int64, ::Int64, ::Int64) at /home/mc/github/julia-dev/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:585
 [5] top-level scope at none:0
```

One approach that might work is to specialize matrix operations based on if their underlying representation is `<: AbstractRange` and convert them accordingly. This seems like it will be a lot of work and prone to human error. Any thoughts?

------------------
```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by fredrikekre** [comment]
I think that if you want to mutate, then you should use mutable containers (i.e. collect the range before you create the special matrix).

**Comment by mcognetta** [comment]
I agree. But still, this is a reasonable use case and it causes a lot of issues. I have a branch where I specialized methods for UniformScaling + Bidiagonal/Tridiagonal/... to broadcast the operation over the underlying array but it still fails when the types become different (one or two are UnitRanges and one is a StepRange or array, etc.).

**Comment by StefanKarpinski** [comment]
This seems fully equivalent to complaining that you can't mutate a range. It's hard to see how wrapping the range in a Diagonal or any other kind of special matrix changes anything: ranges are immutable, if you represent the diagonal with a range then the diagonal is also immutable. If, on the other hand, you use a mutable vector to store the diagonal then you can mutate it no problem:
```jl
julia> D = Diagonal(collect(1:5))
5×5 Diagonal{Int64,Array{Int64,1}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅  ⋅
 ⋅  ⋅  3  ⋅  ⋅
 ⋅  ⋅  ⋅  4  ⋅
 ⋅  ⋅  ⋅  ⋅  5

julia> D[1,1] = 3
3

julia> D
5×5 Diagonal{Int64,Array{Int64,1}}:
 3  ⋅  ⋅  ⋅  ⋅
 ⋅  2  ⋅  ⋅  ⋅
 ⋅  ⋅  3  ⋅  
 ⋅  ⋅  ⋅  4  ⋅
 ⋅  ⋅  ⋅  ⋅  5
```
Julia gives maximum flexibility here: you can either have a compact, immutable representation or a less compact mutable representation; it's your choice. If you wanted to get really fancy, you could even design some kind of "layered vector" type that allows you to use a range as an immutable backing and store modified values sparsely on top of that, but that's way to fancy for the stdlib.

**Comment by mcognetta** [comment]
Fair enough, thanks for info.
