### ISSUE TITLE
A little slip in Julia 1.0.1 documentation

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#29510]
In current Julia 1.0.1 documentation, a little leftover exists.
1. In section [Channels](https://docs.julialang.org/en/stable/manual/parallel-computing/#Channels-1), the code block, there is a sentence `# and a function `foo` which reads items from from c1, processes the item read`, there are 2 `from`s.
2. In section [Multi-Core or Distributed Processing](https://docs.julialang.org/en/stable/manual/parallel-computing/#Multi-Core-or-Distributed-Processing-1), there exists a sentence: `This is the current state of implementation (dev v0.7) and it may change for future Julia versions...`. However, the current version is v1.0.

**Comment by nalimilan** [comment]
Thanks for the report. Would you make a pull request to fix this? You can do that directly on GitHub. Make sure to put `[ci skip]` in the commit message (since CI isn't needed for documentation). The mention of the Julia version can probably be removed.

**Comment by timholy** [comment]
> You can do that directly on GitHub.

https://help.github.com/articles/editing-files-in-your-repository/. You don't need any special permissions, anyone can do it. (Permissions are needed to *merge*, but not to *submit* changes.)
