### ISSUE TITLE
Failure to promote Int8 to Complex{Float64}

### ISSUE THREAD

**Issue by SammyTheSnake** [JuliaLang/julia#29517]
In REPL, experimenting with `promote()` I got the following

```julia
julia> promote(1::Int8, 1.0 + 1.0im)
ERROR: TypeError: in typeassert, expected Int8, got Int64
Stacktrace:
 [1] top-level scope at none:0
```

I would expect this to result in `(1.0 + 0.0im, 1.0 + 1.0im)`

**Comment by KristofferC** [comment]
```
julia> promote(Int8(1), 1.0+im)
(1.0 + 0.0im, 1.0 + 1.0im)
```

Please ask further questions as https://discourse.julialang.org

**Comment by rfourquet** [comment]
You are using a typeassert so this result is expected, use `1 % Int8` or `Int8(1)` instead.
