### ISSUE TITLE
Consider using `realloc` for growing arrays, instead of malloc, memcpy, free every time

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#29526]
Branching out this discussion from https://github.com/JuliaLang/julia/issues/28588 to keep that issue on-track.

To summarize that thread:

> > > So... this is probably an orthogonal, unrelated problem, but JeffBezanson and I have found that We're manually doing a malloc, memcpy, free every time an array is grown, rather than using realloc:
> > 
> > This is still an `O(1)` operation (and this implementation is better for future threading changes and will be required when switching to the Buffer-based pure-julia `Array` implementation)
>
> I still think we should use the technique of calling realloc, checking the alignment, and only copying if necessary. realloc is essential at large array sizes, and at that point also highly likely to be aligned.

So the question remains about how best to implement the array growth with regard to alignment.

**Comment by NHDaly** [comment]
CC: @vtjnash
CC: @JeffBezanson

**Comment by brenhinkeller** [comment]
Not sure if it's getting used but looks like at least some of the relevant machinery for this is present in array.c nowadays: https://github.com/JuliaLang/julia/blob/185b5839ea4d7b885a8c08834f53a608338e1760/src/array.c#L669-L674

**Comment by ViralBShah** [comment]
I think this can be closed with all the new work on `Memory`. @vtjnash @NHDaly please reopen if necessary.

**Comment by oscardssmith** [comment]
We aren't reallocing yet.

**Comment by vtjnash** [comment]
Memory doesn't need it and doesn't support it, so there isn't anything left to do here

**Comment by oscardssmith** [comment]
For malloc managed Memory, can't we realloc a new data section and make a new Memory using it?

**Comment by vtjnash** [comment]
No, that leaves behind UB in the form of the old Memory. If we switch allocators, we could use something like `expand` instead of `realloc` though
