### ISSUE TITLE
Easy way to convert between string and hex?

### ISSUE THREAD

**Issue by tucker-chambers** [JuliaLang/julia#29537]
Hi there,

I have done quite a bit of searching for a good way to convert an integer to its hexadecimal equivalent in Julia, but have had no luck. I am looking ideally for a return beginning with 0x (though I can add that to a naked hex string afterwards, if necessary) and then the hex representation.

I've experimented with parse() and bytes2hex(),

For example:

```
>parse(Int, "60456", base= 16)

394326
```

But when I do that conversion with an online converter, the value is EC28.

So, does anyone have a good technique for converting integers to hexadecimal values? Or maybe there is a bug in my thought process?

Thanks a lot.

**Comment by KristofferC** [comment]
What you wrote converts "60456" in hex to an integer.

If you just want the hex string of a number you do

```
julia> string(60456, base=16)
"ec28"
```

Please ask further questions at https://discourse.julialang.org

**Comment by tucker-chambers** [comment]
Thank you so much @KristofferC . I will move to the discourse server in the future.
