### ISSUE TITLE
Example in Julia document "Channels and RemoteChannels" report error when running

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaLang/julia#29538]
Hi,

In documentation about "[Channels and RemoteChannels](https://docs.julialang.org/en/v1/manual/parallel-computing/#Channels-and-RemoteChannels-1)".

The code example for  interprocess communication, when I run the last part, I have the following error msg:
![image](https://user-images.githubusercontent.com/18593116/46545338-efd3ca80-c87a-11e8-8d1d-ad27a0dc7dea.png)

![image](https://user-images.githubusercontent.com/18593116/46545195-82c03500-c87a-11e8-89a9-fb4005fae698.png)

Can someone tell me what's going on?
New to Parallel Computing in Julia. Thx.

**Comment by KristofferC** [comment]
Should be `global n = n - 1`.

**Comment by KristofferC** [comment]
This was fixed in https://github.com/JuliaLang/julia/pull/28800 but only one of the commits was backported, I think.

**Comment by zhaotianjing** [comment]
Thanks!

**Comment by KristofferC** [comment]
Issue should be open until it is fixed :)

**Comment by zhaotianjing** [comment]
sorry! got it!

**Comment by amitmurthy** [comment]
closed by https://github.com/JuliaLang/julia/pull/28800 I believe
