### ISSUE TITLE
sort(A, dims=1) mixing rows 

### ISSUE THREAD

**Issue by programistawpf** [JuliaLang/julia#29575]
```
julia> slow
4811392×2 Array{Any,2}:
 "Ag"       "Aga"
...
 "zzg"       "z"

```
when
`sort(slow,dims=1)` 
rows are mixed :/ very denger ! Intuitively sort refers to the table and not each column separately. Is somthing like sortrows in ver  0.6 ?
only 
```
p=sortperm(slow[:,1])
slow[p,:] 

```

wokrs correcttly

Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)

Paul

**Comment by timholy** [comment]
You're using the wrong function for the operation you want to achieve. Please use https://discourse.julialang.org/ for questions.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/26333#issuecomment-370705366
https://github.com/JuliaLang/julia/issues/26635#issuecomment-376639547
https://github.com/JuliaLang/julia/issues/29226#issuecomment-422011886
https://github.com/JuliaLang/julia/issues/26632
