### ISSUE TITLE
no Base.tail for NamedTuple

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#29572]
```julia
julia> Base.tail((a = 1, b = 2))
ERROR: MethodError: no method matching tail(::NamedTuple{(:a, :b),Tuple{Int64,Int64}})
Closest candidates are:
  tail(::Tuple) at essentials.jl:173
Stacktrace:
 [1] top-level scope at none:0

julia> VERSION
v"1.1.0-DEV.431"
```

Is this intentional, or is it just waiting for me to make a PR?

**Comment by JeffBezanson** [comment]
Yes this can be added. `tail` is not exported, but also the named tuples API is deliberately minimal since adding new, otherwise undefined methods is non-breaking. That gives us time to decide what should be defined and how it should work.

**Comment by tpapp** [comment]
Reflecting on this, think I agree with the wait & see approach, since I am not sure what semantics I would find useful. Originally I was expecting
```julia
Base.tail((a = 1, b = 2, c = 3)) == (b = 2, c = 3)
```
but then it turned out I need to work with the `values` anyway, which is a `::Tuple` and I can just use `Base.tail`. Also, `first` returns just the first value, so
```julia
(first(x), Base.tail(x)...) == x
```
would not hold either.

The alternative is making
```julia
Base.tail(nt::NamedTuple) = Base.tail(values(nt))
```
which seems kind of contrived too.

**Comment by JeffBezanson** [comment]
Named tuples are ordered though, so returning a new named tuple with the first element dropped seems to make sense.
