### ISSUE TITLE
code_native corrupt output for called function names

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#29588]
`code_native` gives nonsense for the names of some functions on latest master.  For example, consider the annotation next to the `callq` below:

```
$ ./julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.440 (2018-10-10)
 _/ |\__'_|_|_|\__'_|  |  Commit e20d1ee686* (0 days old master)
|__/                   |

julia> code_native(maximum, Tuple{Vector{Int}})
	.text
; Function maximum {
; Location: reducedim.jl:645
; Function #maximum#541; {
; Location: reducedim.jl:645
; Function _maximum; {
; Location: reducedim.jl:649
; Function _maximum; {
; Location: reducedim.jl:650
; Function mapreduce; {
; Location: reducedim.jl:301
; Function #mapreduce#535; {
; Location: reducedim.jl:301
; Function _mapreduce_dim; {
; Location: reducedim.jl:645
	pushq	%rax
	callq	"size;"
;}}}}}}
	popq	%rcx
	retq
	nopl	(%rax,%rax)
;}
```

I came across this while searching for the cause of the segfault in the tests over at https://github.com/JuliaLang/julia/pull/28878 (https://travis-ci.org/JuliaLang/julia/jobs/438390168).

Possibly related: https://github.com/JuliaLang/julia/issues/28046

**Comment by c42f** [comment]
Ok, which is it:
1. "We" (not myself!) know why it's happening and it's annoying but harmless
2. Nobody knows why it's happening, and it could well be the source of a latent memory bug leading to the segfault I'm seeing.

**Comment by vtjnash** [comment]
Expected to be 1: annoying, but harmless. The process by which we emit these names is heuristic-driven, but should be valid.
