### ISSUE TITLE
Julia on Scaleway ARMv7 bare metal server 

### ISSUE THREAD

**Issue by abhi18av** [JuliaLang/julia#29589]
Hi Team Julia,

I'd like to learn more about how to build julia on the Scaleway bare metal C1 server, it's mentioned over here that https://github.com/JuliaLang/julia/blob/master/README.arm.md#scaleway-cloud-hosted-arm-servers julia works out of the box.

I am running Ubuntu in that server and does this mean that there's a ppa for Julia or it builds fine on the server ? 

Also, could you tell me how to build `julia` on the server ? The instructions in the `README` are a bit old and are for `Ubuntu-14.04`

**Comment by nalimilan** [comment]
Please use [the Discourse forum](http://discourse.julialang.org/) for questions, and keep GitHub for bug reports. Thanks!
