### ISSUE TITLE
Constructing N-dimensional rectangular regions

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#29598]
In Julia v1.0 the type `CartesianRange` was removed in favor of `CartesianIndices`. To construct a N-dimensional rectangular region, we have to do:

```julia
CartesianIndices(ntuple(i -> start[i]:finish[i], N))
```

which is relatively ugly. Could we have the old syntax like `CartesianIndices(start, finish)` work again?

**Comment by timholy** [comment]
Already done, see #29440
