### ISSUE TITLE
Julia Escape Sequence Syntax

### ISSUE THREAD

**Issue by resstymanuzon** [JuliaLang/julia#29593]
Hi guys! So I'm really new to Julia and only came across it because of trying to use Julius for a Speech-to-Text Project  (http://julius.osdn.jp/en_index.php) . Everything is set up but I keep getting an "Invalid Escape Sequence" Error originating from one of the files used. Specifically, the following line:

    write(mlf,"\#\!MLF\!\#\n")

Can anyone explain what the symbols after "write(mlf,...)" mean? Or have any suggestions about how to rewrite it? I'm considering rewriting the whole code in Python but don't know what that line means. Any help would be much appreciated.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
