### ISSUE TITLE
Triangular Matrix Conversion to Dense Array fails

### ISSUE THREAD

**Issue by mattcbro** [JuliaLang/julia#29607]
This is a regression in Julia 1.0.   Consider this code
`
using LinearAlgebra
Umat = [ 4.10229+0.0im      -0.00360251-2.02412im ; -0.00360251+2.02412im      1.30966+0.0im]
R = cholesky(Umat) ;
display(R)

V = Array(R) ;
display(V)

X = zeros(Complex{Float64}, 2, 2, 2) ;
X[2,:,:] = R ;
`
The output of this in Julia 1.0 is:
<pre>Cholesky{Complex{Float64},Array{Complex{Float64},2}}
U factor:
2×2 UpperTriangular{Complex{Float64},Array{Complex{Float64},2}}:
 2.02541+0.0im  -0.00177866-0.999363im
         ⋅         0.557612+0.0im     
2×2 Array{Complex{Float64},2}:
     4.10229+0.0im      -0.00360251-2.02412im
 -0.00360251+2.02412im      1.30966+0.0im    
<font color="#EF2929"><b>ERROR: </b></font>LoadError: <font color="#EF2929">MethodError: no method matching setindex_shape_check(::Cholesky{Complex{Float64},Array{Complex{Float64},2}}, ::Int64, ::Int64, ::Int64)</font>
Closest candidates are:
  setindex_shape_check(<font color="#EF2929">::AbstractArray</font>, ::Integer...) at indices.jl:154
  setindex_shape_check(<font color="#EF2929">::AbstractArray{#s57,1} where #s57</font>, ::Integer, ::Integer) at indices.jl:196
  setindex_shape_check(<font color="#EF2929">::AbstractArray{#s57,2} where #s57</font>, ::Integer, ::Integer) at indices.jl:200
  ...
</pre>

This code works perfectly in Julia 0.6.4  once cholesky is replaced with chol()  and the using LinearAlgebra statement is removed.   

So it appears that the Array() constructor fails to work with a triangular matrix as an argument.  (It worked before).   Furthermore there no longer appears to be a working auto-conversion to a dense matrix when I attempt to load the triangular matrix into a dense array.

Even worse,  this fails
` convert(Array{ComplexF64,2}, R)
`
with:
<pre><font color="#EF2929"><b>ERROR: </b></font><font color="#EF2929">MethodError: no method matching Array{Complex{Float64},2}(::Cholesky{Complex{Float64},Array{Complex{Float64},2}})</font>
</pre>
How am I supposed to convert these matrices to regular dense arrays when I need to?

**Comment by mattcbro** [comment]
It seems that nothing can actually be done with triangular matrices output from Cholesky.   All of these operations fail:
`
R' * R
R[1,1]
R + R
R * 2
`
In other words cholesky and probably a bunch of other linear algebra routines are now useless.

**Comment by KristofferC** [comment]
Please ask questions on https://discourse.julialang.org

**Comment by mattcbro** [comment]
Seems like a bug to me.  convert(Array, R) is supposed to work according to the documentation for Julia 1.0

**Comment by KristofferC** [comment]
`convert(Array, R)` does work.

**Comment by mattcbro** [comment]
Really? This is what I get:
julia> convert(Array, R)
2×2 Array{Complex{Float64},2}:
     4.10229+0.0im      -0.00360251-2.02412im
 -0.00360251+2.02412im      1.30966+0.0im    

That equals R' * R  not R.   
Even worse is that inv(R)  converts first to R' * R before inverting.  inv(R) should be upper triangular just like R but it's not.

**Comment by mattcbro** [comment]
julia> inv(R)
2×2 Array{Complex{Float64},2}:
    1.02676+0.0im      0.00282432+1.58688im
 0.00282432-1.58688im     3.21614-0.0im   

Are things working differently on your installation?

**Comment by mattcbro** [comment]
OK I missed the fact that R.U is what I actually want.  However the default conversion is not correct IMHO.
