### ISSUE TITLE
overflow in Rational arithmetic

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#2960]
Rational - Int comparisons are susceptible to overflow:

```
julia> 3//2 > typemax(Int)
true
```

This is due to multiplying the integer argument by the rational's denominator.

Other operations that use `*` this way are similarly afflicted:

```
julia> r = (typemax(Int)-1)//typemax(Int)
9223372036854775806//9223372036854775807

julia> div(r,2)
-4611686018427387903
```

**Comment by simonbyrne** [comment]
These should now all be sorted: if not, please reopen.
