### ISSUE TITLE
Zero-dimensional SubArrays are considered non-contiguous

### ISSUE THREAD

**Issue by mfsch** [JuliaLang/julia#29608]
In Julia 1.0, I get the following:

```
julia> Base.iscontiguous(view(zeros(8), 5))
false
```

This means that a view of a single value cannot be used directly when packages call out to C and rely on `iscontiguous` to decide whether they can simply pass a pointer to the C function. This is the case in the MPI.jl package, but other packages might be using a similar approach.

A workaround is to use a range of length one instead, but I think it would make sense to use linear indexing for zero-dimensional views.
```
julia> Base.iscontiguous(view(zeros(8), 5:5))
true
```

To fix this, I think it would be enough to add the following definition to `subarray.jl`.
```
viewindexing(I::Tuple{ScalarIndex}) = IndexLinear()
```

**Comment by mbauman** [comment]
Good catch, and great solution! Would you like to submit a pull request with that change?

**Comment by mfsch** [comment]
If I find some time in the next couple of days I’ll give it a try.
