### ISSUE TITLE
The readme for build instruction on ARM platform is outdated.

### ISSUE THREAD

**Issue by abhi18av** [JuliaLang/julia#29612]
Hi Julia team,

https://github.com/JuliaLang/julia/blob/master/README.arm.md

I was wondering if you could update the readme and the build instructions for the `ARM` devices since the instructions still depend on the `gcc-4.8` and `Ubuntu-14.04`.

Also, on `Ubuntu-18.04`, I'm having trouble building and installing various dev libraries 

For example
```
root@pup:~/julia# apt install libblas3gf
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libblas3gf

```

I'd like to like to highlight that the link to `nightly` builds for `arm` devices isn't working at all. 

I also have a request that perhaps the `Ubuntu-ppa` could provide an `arm` variant of `julia-1.0.x` as well ?

**Comment by ViralBShah** [comment]
The build on ARM should work on the default build path. I removed some of these outdated build instructions in a13c2cde9304797fdced920a0ac7cac1a2816fc4
