### ISSUE TITLE
build: libgit2 does not detect libssh2 on FreeBSD

### ISSUE THREAD

**Issue by iblis17** [JuliaLang/julia#29625]
I installed a new FreeBSD VM,
and the log from here (https://build.julialang.org/#/builders/67/builds/3/steps/7/logs/stdio)

shew this:
```
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```

and this build got following test error
```julia
Error in testset LibGit2/libgit2:
Test Failed at /usr/home/julia/julia-fbsd-buildbot/worker/freebsdci_test/build/usr/share/julia/stdlib/v1.1/LibGit2/test/libgit2.jl:161
  Expression: findfirst(isequal((LibGit2.Consts).FEATURE_SSH), f) !== nothing
   Evaluated: nothing !== nothing
ERROR: LoadError: Test run finished with errors
in expression starting at /usr/home/julia/julia-fbsd-buildbot/worker/freebsdci_test/build/test/runtests.jl:61
```

Seems that our build script doesn't point the correct path of `libssh2` for `libgit2`?

**Comment by nalimilan** [comment]
I've also seen this on Fedora with some combinations of `USE_SYSTEM_LIBSSH2` and `USE_SYSTEM_LIBGIT2`. But you don't set these variables, right?

**Comment by iblis17** [comment]
No, I do not set any `USE_SYSTEM_*` variables.
This build is driven by `.freebsdci.sh` (https://github.com/JuliaLang/julia/blob/master/.freebsdci.sh)
