### ISSUE TITLE
Julia 0.7 REPL dies

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#29628]
Frequently the Julia 0.7 REPL dies and does not accept any typing. Kill & Restart is the only option. No idea when and why occurs. typically when editing a command and going to the line beginning. it is very annoying.

**Comment by montyvesselinov** [comment]
I think it is when you press crtl-V to paste a string at the beginning of the line

**Comment by nalimilan** [comment]
It would be very useful to find a way to reproduce the problem. Else it's almost impossible to fix.

Also worth trying on Julia 1.0.1.

**Comment by montyvesselinov** [comment]
I spent more time on this.

Actually, the problem is caused by TerminalExtensions.jl
