### ISSUE TITLE
HelloWorld documentation for Pkg doesn't work

### ISSUE THREAD

**Issue by crlaugh** [JuliaLang/julia#29621]
The HelloWorld example provided at https://docs.julialang.org/en/v1/stdlib/Pkg/#Creating-your-own-packages-1 does not work when followed strictly.  The fix provided at https://github.com/JuliaLang/julia/issues/27359 addresses the problem, but this involves adding a dependency, which is only described in the following section (i.e., https://docs.julialang.org/en/v1/stdlib/Pkg/#Adding-dependencies-to-the-project-1).  I would try to correct it and submit a PR, but there is something of a philosophical question on how the section should be organized if a dependency is required to execute the MWE; I am therefore hoping that someone closer to this documentation can make the required change.

**Comment by fredrikekre** [comment]
Can you reopen this at https://github.com/JuliaLang/Pkg.jl instead? Thanks!
