### ISSUE TITLE
mktempdir should accept keyword arguments

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/julia#29659]
From the docs:

```
Base.Filesystem.mktempdir — Method.
mktempdir(parent=tempdir())
```

From the REPL: 

```
julia> mktempdir(parent=tempdir())
ERROR: function mktempdir does not accept keyword arguments
Stacktrace:
 [1] kwfunc(::Any) at ./boot.jl:321
 [2] top-level scope at none:0
```

**Comment by StefanKarpinski** [comment]
`mktempdir(parent=tempdir())` indicates that `mktempdir` takes an optional `parent` argument, not that it's a keyword argument. If it was a keyword argument, it would instead be written as
```jl
mktempdir(; parent=tempdir())
```

**Comment by fredrikekre** [comment]
It is Julia syntax for defining a method with keyword arguments.
