### ISSUE TITLE
Allow empty @logmsg

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#29672]
I was trying to use `@debug` like this:

```
@debug if expensive_check
     @error "massive failure"
end
```

If `Debug` logging is enabled, I perform an expensive check. If the check is not true, the event should log as an error (I want to see the red color pop out in the middle of many logging messages). In this case, the `@debug` itself should not log at all.

However currently an empty `@logmsg` (with return value `nothing) produces an error:

```
julia> @warn begin end
┌ Error: Exception while generating log record in module Main at REPL[4]:1
│   exception =
│    ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.
│    Stacktrace:
│     [1] print(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Nothing) at ./show.jl:566
│     [2] print_to_string(::Nothing) at ./strings/io.jl:122
│     [3] string(::Nothing) at ./strings/io.jl:155
│     [4] #handle_message#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Logging.ConsoleLogger, ::Base.CoreLogging.LogLevel, ::Nothing, ::Module, ::String, ::Symbol, ::String, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Logging/src/ConsoleLogger.jl:108
│     [5] handle_message(::Logging.ConsoleLogger, ::Base.CoreLogging.LogLevel, ::Nothing, ::Module, ::String, ::Symbol, ::String, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Logging/src/ConsoleLogger.jl:100
│     [6] top-level scope at REPL[4]:1
│     [7] top-level scope at logging.jl:321
│     [8] eval(::Module, ::Any) at ./boot.jl:319
│     [9] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
│     [10] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
│     [11] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:259
└ @ Main REPL[4]:1
```

Would it be worthwhile to allow empty `@logmsg` to simply register no log message at all instead of throwing an error that doesn't seem to serve any purpose?

**Comment by maleadt** [comment]
ref https://github.com/JuliaLang/julia/pull/27650

**Comment by c42f** [comment]
This is an interesting use case; it's certainly not what I had in mind for `@debug` but I can see the value in what you're trying to do.

One possibility would be to have something like `@if_shouldlog` (`@iflog` / `@logif` / `@logwhen` ) or some such thing which runs the standard log filtering checks and executes the block when they're true. The best thing would be if we can design things so that the behavior of `@info` and friends can be specified in terms of this lower level primitive operation.

```julia
@if_shouldlog Debug begin
    @error "massive failure"
end
```

**Comment by tkf** [comment]
Why not just a function like `shouldlog(:info)`?  None of [the advantages of macros in logging](https://github.com/JuliaLang/julia/pull/24490#issuecomment-342375477) seem to apply here (e.g., you don't need to create a record id).  Or maybe I'm missing something?

**Comment by c42f** [comment]
@tkf I think the logic should be as similar as possible to the macro versions, including passing any statically known metadata to `shouldlog` such as the current module. With a function the users would have to do that manually by inserting `@__MODULE__` which might be kind of annoying. Other than that though, yes; we could have a function version.

**Comment by tkf** [comment]
Thanks for the clarification. I missed that `@__MODULE__` was used for filtering.

**Comment by vtjnash** [comment]
This now works (`nothing` can again be printed)
