### ISSUE TITLE
Array printing alignment code adds too much whitespace

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#29690]
<img width="1018" alt="screen shot 2018-10-17 at 12 07 39" src="https://user-images.githubusercontent.com/3131001/47103867-cb2a0c00-d205-11e8-9eea-80e6cbcf58a2.png">

The difference in length between the first and second items causes the amount of added whitespace to increase (in `print_matrix_row`). I've been encountering cases where I get a full screen of whitespace.

AFAICT this bug has been present as long as `print_matrix_row` has existed, so it's not a new issue. I couldn't find previous reports though. I also can't really tell what to fix.

**Comment by vtjnash** [comment]
I think the issue is that it doesn't consider the width of the screen, and just pads them all to the same number of characters (rather than ignoring anything that gets wider than some percentage of the output when computing layout)?

**Comment by Keno** [comment]
I mean if it's a vector there isn't really any need to add padding white space at all.

**Comment by StefanKarpinski** [comment]
There does need to be left padding in general for alignment though.

**Comment by KristofferC** [comment]
Fixed

![bild](https://user-images.githubusercontent.com/1282691/66837873-0455a300-ef64-11e9-8a4d-eedde058326f.png)
