### ISSUE TITLE
[BUG] `triu` returns wrong matrix when `M<N` and `k<0`

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaLang/julia#29711]
When I intended to implement `rq` decomposition, I finded this bug in `triu!` function by accident.
When the input matrix size (M, N) with `M>N`, for `k<0`, the following behavior is not correct

e.g.
```julia console
julia> mat=[1 2;
            3 4;
            5 6;
            7 8]
4×2 Array{Int64,2}:
 1  2
 3  4
 5  6
 7  8

julia> triu!(mat, -1)
4×2 Array{Int64,2}:
 1  2
 3  4
 0  6
 0  8
```
which is wrong, it should be 
```julia
[1 2;
 3 4;
 0 6;
 0 0]
```

Here, `min(n, n + k)` should be replaced by `min(n, m + k)`
https://github.com/JuliaLang/julia/blob/592a4745012a3d1b920fb1c95093bc5c7453323d/stdlib/LinearAlgebra/src/dense.jl#L174

A PR is ready to fix this.

**Comment by staticfloat** [comment]
Closed by #29712
