### ISSUE TITLE
[ARMv7]: bad instruction `br r2`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#29710]
The recently-resurrected ARMv7 buildbot is failing with the following error while compiling `src/task.c`:

```
{standard input}: Assembler messages:
{standard input}:133: Error: bad instruction `br r2'
```

Example error log: https://build.julialang.org/#/builders/5/builds/6/steps/4/logs/stdio

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/blame/5f2759d85eeeb9c68e35e5e84b10715a49f4449d/src/task.c#L730 needs to be `bx`. Introduced in https://github.com/JuliaLang/julia/pull/13099. I don't know why it was changed from `b start_task` though, since the latter should be one instruction shorter...

**Comment by staticfloat** [comment]
I've changed it from `br` to `bx` on [this branch](https://github.com/JuliaLang/julia/tree/sf/fixarm), but [reading the ARM docs on `b` vs. `bx`](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0204j/Cihfddaf.html) makes me think that you are correct; we should be able to just use `b` instead of `bx` here, since I don't think we should _ever_ be in thumb mode.  @vtjnash do you have any insight to share?

**Comment by vtjnash** [comment]
I thought it was supposed to be common with AARCH64, I guess not, and should just use `b`.
