### ISSUE TITLE
`make binary-dist` creates an unusable installer on Windows via Cygwin

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#29719]
Cygwin  cross-compile build for windows, using 
```sh
$ make
$ make win-extras
$ make binary-dist
```

An unusable installer is created, see below:

 
![f](https://user-images.githubusercontent.com/4319522/47178878-73b19c00-d2ea-11e8-9406-092897c495b8.gif)

**Comment by musm** [comment]
This is the offending line `	cd $(BUILDROOT) && cat $(JULIAHOME)/contrib/windows/7zS.sfx $(JULIAHOME)/contrib/windows/7zSFX-config.txt "julia-install-$(JULIA_COMMIT)-$(ARCH).7z" > "$(JULIA_BINARYDIST_FILENAME).exe"
` in the Makefile


If you execute   `copy /b  a + b + c  output.exe`  the installer works. Now it seems that within cygwin the exe gets malformed. I'm not exactly sure what is the best way about fixing this problem.

**Comment by vtjnash** [comment]
Perhaps just needs `chmod a+x`?

**Comment by musm** [comment]
that fixes the problem!
