### ISSUE TITLE
List JULIA_DEPOT_PATH under Environment variables in the docs

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#29714]
Shouldn't JULIA_DEPOT_PATH be listed under https://docs.julialang.org/en/v1/manual/environment-variables/?

**Comment by fsaad** [comment]
Agreed. Note that `JULIA_DEPOT_PATH` is documented at at the end of the glossary in the documentation of `Pkg.jl` v1.1: https://julialang.github.io/Pkg.jl/v1.1/glossary/

**Comment by jadijadi** [comment]
May I send a PR for this?

**Comment by fredrikekre** [comment]
Yes.
