### ISSUE TITLE
missing matrix exponentiation methods for `\euler`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#29729]
Is there any reason for this?  Currently the following is defined in `base/mathconstants.jl`:
```julia
for T in (AbstractIrrational, Rational, Integer, Number, Complex)
    Base.:^(::Irrational{:ℯ}, x::T) = exp(x)
end
```
Is there any reason why this is not simply
```julia
Base.:^(::Irrational{:ℯ}, x) = exp(x)
```

**Comment by StefanKarpinski** [comment]
I can't recall, but one thing that occurs to me is that it might cause a lot of method ambiguities?

**Comment by ExpandingMan** [comment]
Why?  The type on the first argument is `Irrational{:\euler}`, that's pretty specific.

**Comment by StefanKarpinski** [comment]
It is, but the other argument is as general as it gets so this would be ambiguous with `^(::Number, ::T)` for any type that's more specific than `Any`, for example.

**Comment by ExpandingMan** [comment]
Oh yeah, I didn't think of that, that could be bad.  So, I suppose what it should be is
```julia
for T ∈ (AbstractIrrational, Rational, Integer, Number, Complex)
    Base.:^(::Irrational{:ℯ}, x::T) = exp(x)
    Base.:^(::Irrational{:ℯ}, x::AbstractArray{T}) = exp(x)
end
```

**Comment by ExpandingMan** [comment]
Wow, there's even a comment right there that says it was to avoid ambiguities for `^(::Number, x)`.  I feel really stupid.
