### ISSUE TITLE
Trivial at-threads loop allocates

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#29748]
With `JULIA_NUM_THREADS=2 julia`,

```julia
julia> using BenchmarkTools

julia> function f()
           Threads.@threads for i = 1 : 10
           end
       end
f (generic function with 1 method)

julia> @btime f()
  224.018 ns (1 allocation: 32 bytes)
```

Is this expected? It's also the case on 0.6, but I seem to recall having achieved zero allocation at some point using master sometime between 0.6 and 0.7.

**Comment by JeffBezanson** [comment]
This is expected. Now it will allocate even more, since we create tasks. Of course eliminating allocations is always great, but trying to make this loop have 0 allocations is probably not going to be a priority.
