### ISSUE TITLE
Missing methods for Float16 - Integer comparison

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#29743]
Currently comparisons between `Float16` and integer types fall back to using `promote_type` (instead of specific methods as for other floating point types).  The promotion goes to `Float16`. This leads to the following sort of errors and inconsistencies:

```julia
julia-1.1> Inf16 == typemax(Int)
true

julia-1.1> Inf16 == 10^5
true
```
Compare:
```julia
julia-1.1> Inf16 == 1.0e5  # promotion works for float-float comparisons
false

julia-1.1> Inf32 <= typemax(UInt128)
false

julia-1.1> Float32(typemax(UInt128))
Inf32  # overflow is ok when it doesn't confound comparisons
```

Verified on a variety of Julia versions from 0.6.4 through a recent nightly.

**Comment by elperkerson62** [comment]
Why is Float16 not simply included in line 476 in float.jl:

for Ti in (Int64,UInt64,Int128,UInt128)
    for Tf in (Float32,Float64) # Why not include Float16 here?
        # Defines comparison methods
    end
end

**Comment by StefanKarpinski** [comment]
Because LLVM does not support 16-bit float operations.

**Comment by sam0410** [comment]
Can we change Float16 to Float64 and check for comparison?

**Comment by sam0410** [comment]
Hi @StefanKarpinski, I added comparison by changing it to Float64. Please review my PR #29870

**Comment by cossio** [comment]
@StefanKarpinski Close this?
