### ISSUE TITLE
Use busybox wget for downloading on Windows

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#29752]
So it turns out that we still bundle busybox on Windows installations. Should we use `busybox wget` instead for downloading? This would solve the problem of needing to instal WMF 3 on Windows 7 (if you're still using Win 7, you're probably in a corporate environment where you can't do that).

(discovered in https://github.com/JuliaPackaging/BinaryProvider.jl/pull/132)

**Comment by staticfloat** [comment]
I seem to remember this being a no-no; something about busybox wget being very unreliable (it didn't obey corporate proxy rules, perhaps?).  But I am not a first-hand source of that knowledge, it was someone else telling me it, so I don't know how true it is.  We could try it.

**Comment by simonbyrne** [comment]
Not sure. We could fall back on busybox if powershell doesn't work?

That said, I think BinaryProvider is the main problem, since that is the one that breaks package installation. Once we fix that, we might be better off focusing on #27043 instead of the existing `Base.download`.

**Comment by musm** [comment]
Why not use curl https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/ 

Here are the windows compatible  binaries  https://curl.haxx.se/windows/  roughly ~3mb

**Comment by simonbyrne** [comment]
We would have to bundle it.

**Comment by simonbyrne** [comment]
I'm not, but that would perhaps be better discussed in #27043.

**Comment by musm** [comment]
I think we should close this. On newer Windows builds we use the system shipped `curl.exe` if available, which avoids the  original issue in this thread.  Longer term we can chose to improve functionality of the download function  (perhaps also by  shipping curl for all distributions, even those where it's not available system wide, but not necessarily).

**Comment by simonbyrne** [comment]
Closing this as no Downloads.jl is now a stdlib.
