### ISSUE TITLE
A bug in ":" for accessing Vectors/Arrays

### ISSUE THREAD

**Issue by PeterJacko** [JuliaLang/julia#29776]
Consider the following example:

D = zeros( 5 )
D_sub = D[ 2:3 ]
D_sub = D[ 2 : 3 ]
D_sub = D[ 2: 3 ]
D_sub = D[ 2 :3 ]

Note the different spacings around ":". The first 3 variants work, but the 4th one gives an error:

ERROR: MethodError: no method matching typed_hcat(::Array{Float64,1}, ::Int64, ::Int64)
Closest candidates are:
  typed_hcat(::Type{T}, ::Number...) where T at abstractarray.jl:1209
  typed_hcat(::Type{T}, ::Union{Number, Adjoint{T,#s561} where #s561<:(AbstractArray{T,1} where T) w
here T}...) where T at C:\Users\julia\AppData\Local\Julia-1.0.1\share\julia\stdlib\v1.0\LinearAlgebr
a\src\adjtrans.jl:165
  typed_hcat(::Type{T}, ::Union{Number, Transpose{T,#s561} where #s561<:(AbstractArray{T,1} where T)
 where T}...) where T at C:\Users\julia\AppData\Local\Julia-1.0.1\share\julia\stdlib\v1.0\LinearAlge
bra\src\adjtrans.jl:166
  ...
Stacktrace:
 [1] top-level scope at none:0

The anoying thing is that for Arrays, the error I get is an "unexpected comma" error, which took me a while to track down to the spacings around ":".

A = zeros( 5 , 5 , 5 )
A_sub = A[ 1 :2 , 3:4 , 1:2 ]
ERROR: syntax: unexpected comma in matrix expression

I hope there is a way to sort this out. For the direct use of "1 :2" or in the VIEW function, for instance, such a spacing around ":" works fine.

versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\JuliaPro-1.0.1.1\app-1.29.0\atom.exe" -a
  JULIA_NUM_THREADS = 2
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com/
  JULIA_PKG_TOKEN_PATH = C:\Users\Peter\.julia\token.toml

**Comment by KristofferC** [comment]
`D[ 2 :3 ]` is ambiguous to `D[ (2) (:3) ]` (which is the same as `D[2 3]`).

**Comment by JeffBezanson** [comment]
The syntax `Int[1 2]` can be used to construct a 1-row matrix with a given element type, and a prefix `:` "quotes" the following expression, which is usually used for symbols (`:x`). I don't consider this syntax collision so bad, since `2 :3` is a confusing way to write a range; `2:3` and `2 : 3` seem clearly preferable to me.

**Comment by KristofferC** [comment]
Closing since this is intended.
