### ISSUE TITLE
Spaces are allowed in broadcast calls `f. ()`

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#29781]
We dropped support for spaces between function names and parens in normal calls (#11891), but unfortunately the addition of dot-broadcasting brought this back!

```julia
julia> sin    (1)
ERROR: syntax: space before "(" not allowed in "sin ("

julia> sin.    (1)
0.8414709848078965
```

**Comment by mschauer** [comment]
There is a difference that the first disarms a trap
```
# Old julia
julia> [sin (1)]
1×2 Array{Any,2}:
 sin  1

julia> sin (1)
0.8414709848078965
```
while the second is harmless
```
julia> [sin. (1)]
1-element Array{Float64,1}:
 0.8414709848078965

julia> sin. (1)
0.8414709848078965
```

**Comment by JeffBezanson** [comment]
I believe this is because we intentionally allow space after the dot in `a.   b`. I don't remember why but I think I remember some discussion about this.

**Comment by vtjnash** [comment]
I'd guess it's to allow the development of future syntax concepts? Potentially something along the lines of javascript's chaining:
```julia
a.
  b().
  c().
  (broadcast!).
  d()
```
But also because there's no reason (ambiguity) to disallowing it, so we let people experiment.

**Comment by JeffBezanson** [comment]
Ah yes, see #17305.

**Comment by JeffBezanson** [comment]
> While we're at it, let's also fix the parsing of this:
> 
> ```
> julia> sin. .
> ERROR: type #sin has no field .
> Stacktrace:
>  [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
> ```

Ok, I see that that could be an error, but does this cause an actual problem?

I also suppose we could allow `a.   b` but disallow `a.   (b)`.

**Comment by shrivaa** [comment]
I am a novice to Julia. I started out with the documentation and the first echo command in it. What is the fix? Please help.

**Comment by mbauman** [comment]
@shrivaa Please ask questions on the [discourse message board](https://discourse.julialang.org). Folks will happily help you out there.
