### ISSUE TITLE
type parameter `UndefVarError` when dispatch matches `UnionAll`

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#29788]
This behavior surprised me:

```julia
sometype = Array{Tuple{R}} where {R}

something(::Type{T}) where {T <: Array{S}} where {S<:Tuple} = S

something(sometype) # gives ERROR: UndefVarError: S not defined
```

I am not sure if I expected `S` to be bound to `Tuple{R} where {R}` or for a `MethodError`. But either way, I was not expecting `S` to be ever undefined if it shows up in a `where`.

versioninfo: 
```julia
julia> versioninfo()
Julia Version 1.1.0-DEV.318
Commit 993e7d7733 (2018-09-25 06:36 UTC)
```

**Comment by JeffBezanson** [comment]
This is intentional; see #23117. The type is a subtype of the signature, so the method should match. But there is no unique correct value for `S`.

**Comment by goretkin** [comment]
Thanks for the explanation. I ran into this when using the `Size` trait of `StaticArrays.jl` (e.g. `Size(SVector)`). Looks like I wouldn't have run into it on the master branch of `StaticArrays`: https://github.com/JuliaArrays/StaticArrays.jl/commit/bfa5536913389884f3505e8571c41d3968c01577
