### ISSUE TITLE
Hard-coded path in Base.download to PowerShell may fail

### ISSUE THREAD

**Issue by jdchn** [JuliaLang/julia#29802]
In v1.0.1, [base/download.jl](https://github.com/JuliaLang/julia/blob/0d713926f85dfa3e4e0962215b909b8e47e94f48/base/download.jl#L7) uses a hard-coded path to locate `powershell.exe`:
```julia
5 if Sys.iswindows()
6   function download(url::AbstractString, filename::AbstractString)
7     ps = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

This fails if `C:\Windows` is not the Windows directory. One consequence is that Pkg may fail to download artifacts during an `add` operation.

It may be more robust to use [`WINDIR`](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables):
```julia
5 if Sys.iswindows()
6   function download(url::AbstractString, filename::AbstractString)
7     ps = "%WINDIR%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

**Comment by KristofferC** [comment]
Pkg doesn't use the Base `download` functions.

**Comment by jdchn** [comment]
Apologies -- I was too concise. This is not a `Pkg` issue.

This issue was motivated by errors from using `Pkg` due to `build.jl` scrips using `Base.download`. More specifically, I ran into this with `Pkg.add("Plots")`, one of the errors being the binary download for `GR`.

However, this generalizes to anything that may call `Base.download` on a Windows system where `C:\Windows` is not the Windows directory. This is probably not common.

**Comment by jdchn** [comment]
After a little extra research, `SYSTEMROOT` may be an alternative for `WINDIR`. 

Both variables nominally point to the Windows directory on modern systems. However, `SYSTEMROOT` is a read-only built-in variable, whereas `WINDIR` can be modified (per <https://ss64.com/nt/syntax-variables.html>).

**Comment by musm** [comment]
@jdchn  SYSTEMROOT  is the newer version and WINDIR seems to be there for compatibility purposes

**Comment by vtjnash** [comment]
Window's doesn't have any read-only or built-in variables (as far as I'm aware)—the documentation appears to be for powershell. The builtin API would be a kernel syscall (GetSystemDirectory or SHGetKnownFolderPath(FOLDERID_System)).

**Comment by musm** [comment]
@vtjnash do we want to wrap the sys call or use the env variable approach?
