### ISSUE TITLE
File extension for libjulia and libopenlibm is `.a` on windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#29812]
I'm not sure if this is causing any issues, but nonetheless should be corrected

under `/lib` folder Julia appends the `.a` prefix to the `libjulia.dll` and `libopenlibm.dll` files so that the are actually `libjulia.dll.a` and `libopenlibm.dll.a`

  
![t1](https://user-images.githubusercontent.com/4319522/47576806-62344980-d913-11e8-9fc2-896159f91323.gif)

**Comment by vtjnash** [comment]
This is the correct suffix for these files (the .dll file is in bin, if that's what you're looking for)

**Comment by musm** [comment]
shouldn't they be `.lib` and without the  subextension `.dll`
