### ISSUE TITLE
`zero` should be type preserving

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaLang/julia#29839]
The change of type causes trouble in https://github.com/FluxML/Flux.jl/issues/472

```julia console
julia> A = randn(2,2)
2×2 Array{Float64,2}:
 -2.75325    0.338825
 -0.611465  -1.18981 

julia> A'
2×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 -2.75325   -0.611465
  0.338825  -1.18981 

julia> zero(A')
2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

julia> transpose(A)
2×2 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
 -2.75325   -0.611465
  0.338825  -1.18981 

julia> zero(transpose(A))
2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
```
`Adjoint`, `Transpose` wrappers should be keeped.

I think this PR https://github.com/JuliaLang/julia/pull/29777 is a proper place to make this change?

**Comment by StefanKarpinski** [comment]
> `Adjoint`, `Transpose` wrappers should be keeped.

Why?

**Comment by GiggleLiu** [comment]
`zero` should be type preserving, to make program more predictable
```julia
# trivil case
m = randn(2,2)
a = MyArr(m')
a.arr = zero(a.arr) # break

# what's happening in Flux
mutable struct MyTracker{AT}
    arr::AT
    grad::AT

    MyTracker(x) = new{typeof(x)}(x)
end
m = randn(2,2)
a = MyTracker(m')
a.grad = zero(a.arr)  # break
```

**Comment by GiggleLiu** [comment]
Also, if we believe `0' == 0` always hold, we can define
```julia
Base.zero(ad::Adjoint{T, AT}) where {T, AT} = Adjoint{T, AT}(zero(parent(ad)))
```
to make `Adjoint` propagate.

Then the following example will work
```julia
using LinearAlgebra
Base.zero(a::MyArr) = MyArr(zero(a.arr))
adarr = Adjoint(MyArr);
zero(adarr);
```

**Comment by StefanKarpinski** [comment]
This could also be handled by having an appropriate convert method.

**Comment by StefanKarpinski** [comment]
There's also an argument to be made that the type of the `grad` field is wrong.

**Comment by GiggleLiu** [comment]
Ok, it is really a hard decision between `consistency` and `easy to use`. Let's keep this issue open and see if threre are more feedbacks.

**Comment by GiggleLiu** [comment]
I think we can close this issue now, because recently someone fixed it.

```julia
julia> zero([1,2,3]')
1×3 adjoint(::Vector{Int64}) with eltype Int64:
 0  0  0

julia> similar([1,2,3]')
1×3 adjoint(::Vector{Int64}) with eltype Int64:
 139677310498048  139677310498496  139677310498832
```

Cheers!
