### ISSUE TITLE
`resize!` failure after using ldiv! on v1.0

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#29852]
MWE:

```julia
using LinearAlgebra
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lu(W)
  ldiv!(vec(w),luw,v)
  resize!(v,3)
end
resizer()
```

The `resize!` fails because of the view on `v` which is built internally. Patching with

```julia
function LinearAlgebra.ldiv!(Y::AbstractVecOrMat, A::Factorization, B::AbstractVecOrMat)
    @assert !LinearAlgebra.has_offset_axes(Y, B)
    m, n = size(A, 1), size(A, 2)
    if m > n
        ldiv!(A, B)
        return copyto!(Y, B)
    else
        return ldiv!(A, copyto!(Y, B))
    end
end
```

fixes the issue. Note that this is a regression from v0.6 where

```julia
function resizer()
  v = rand(7)
  w = similar(v)
  W = rand(7,7)
  luw = lufact(W)
  A_ldiv_B!(w,luw,v)
  resize!(v,3)
end
resizer()
```

works.

Is that viewless version fine? Should I PR it? I don't really understand what supporting using only part of `B` is for. For reference the dispatch is

https://github.com/JuliaLang/julia/blob/f104ea4ec352519de76e52bf65ea7b3ed2dc6155/stdlib/LinearAlgebra/src/factorization.jl#L98-L108

Why not generally use `B`?

**Comment by andreasnoack** [comment]
> Why not generally use `B`?

Because they are not the same size when the system is underdetermined.

**Comment by fredrikekre** [comment]
dup of  #29713?

**Comment by andreasnoack** [comment]
> dup of #29713?

No that one is the overdetermined branch

It's actually surprising to me that `ldiv!(A, copyto!(Y, view(B, 1:m, :)))` works. I hadn't realized `copyto!` behaved like this
```julia
julia> Ones = ones(2,2);

julia> OnesView = view(Ones, 1:2, :);

julia> Ones == OnesView && size(Ones) == size(OnesView)
true

julia> copyto!(zeros(3,2), Ones)
3×2 Array{Float64,2}:
 1.0  1.0
 1.0  0.0
 1.0  0.0

julia> copyto!(zeros(3,2), OnesView)
3×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 0.0  0.0
```

**Comment by JeffBezanson** [comment]
Uhoh.
