### ISSUE TITLE
Strange runtimes for lmul!(::Number,::AbstractArray) with different number types

### ISSUE THREAD

**Issue by dkarrasch** [JuliaLang/julia#29857]
I noticed very different runtimes for `lmul!` with a (zero) real/complex vector and different `Number` types:
```
using BenchmarkTools, LinearAlgebra

α = 3
β = @btime convert(Float64, $α)
γ = @btime convert(Rational, $α)
δ = @btime convert(Complex, $α)
η = @btime convert(Complex, $β)
ξ = @btime convert(Complex, $γ)
v = zeros(ComplexF64, 5000)
@btime lmul!($α, $v) # 2.357 μs
@btime lmul!($β, $v) # 2.795 μs
@btime lmul!($γ, $v) # 2.360 μs
@btime lmul!($δ, $v) # 3.426 μs
@btime lmul!($η, $v) # 1.141 μs
@btime lmul!($ξ, $v) # 13.179 μs
@which lmul!(α, v)
@which lmul!(β, v)
@which lmul!(γ, v)
@which lmul!(δ, v)
@which lmul!(η, v)
@which lmul!(ξ, v)

w = zeros(5000)
@btime lmul!($α, $w) # 523.094 ns
@btime lmul!($β, $w) # 867.519 ns
@btime lmul!($γ, $w) # 524.801 ns
```
I'm on
```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 4
```
Looking at the `lmul!(::Number,::AbstractArray)` implementation, there is a loop in which the scalar is multiplied with each element of the array. In most of the above cases, this would imply a type conversion in the scalar multiplication. I was told that surely this conversion would be hoisted out of the loop by LLVM. This, in turn, would result in a single number conversion (which take on the order of `ns`), which cannot explain the runtime differences.

So, is the conversion not hoisted out of the loop? Am I missing something very simple here? This seems to put some burden on the user to "prepare" the scaling factor and convert manually in advance [LinearMaps.jl#33](https://github.com/Jutho/LinearMaps.jl/issues/33).

**Comment by KristofferC** [comment]
If you believe that the hoisting of a conversion is the problem, did you benchmark

```jl
function generic_lmul2!(s::Number, X::AbstractArray)
    ss = convert(eltype(X), s)
    @simd for I in eachindex(X)
       @inbounds X[I] = ss*X[I]
    end
    X
end
```

and found a performance improvement?

**Comment by dkarrasch** [comment]
Thanks @KristofferC, I haven't tried, but just did. For the six complex-vector examples I get with your `generic_lmul2!`
```
3.370 μs (0 allocations: 0 bytes)
3.378 μs (0 allocations: 0 bytes)
3.374 μs (0 allocations: 0 bytes)
3.373 μs (0 allocations: 0 bytes)
3.427 μs (0 allocations: 0 bytes)
3.364 μs (0 allocations: 0 bytes)
```
so consistent runtimes, but overall **slower** (except for the complex-integer and complex-rational). For the three real-vector cases, I again get consistent runtimes, this time at the previous **top** performance level:
```
524.547 ns (0 allocations: 0 bytes)
523.476 ns (0 allocations: 0 bytes)
523.772 ns (0 allocations: 0 bytes)
```
In particular, this improves the Float64 * Vector{Float64} case!

**Comment by dkarrasch** [comment]
The "outliers" (the fast ComplexF64-ComplexF64 and the slow Float64-Float64) are related to the use of this method and the BLAS branch there:
```
lmul!(s::T, X::Array{T}) where {T<:BlasFloat}
```
which has been deleted recently. When I use the `generic_lmul!`, I don't see any significant runtime differences in the real case.

For the six complex cases above, I get
```
2.358 μs (0 allocations: 0 bytes) # integer scalar
2.795 μs (0 allocations: 0 bytes) # float64 scalar
2.356 μs (0 allocations: 0 bytes) # rational scalar
3.437 μs (0 allocations: 0 bytes) # complex{integer}
3.422 μs (0 allocations: 0 bytes) # complex{float64}
13.161 μs (0 allocations: 0 bytes) # complex{rational}
```
I remain slightly confused about the 1.18 factor in runtime for the float64 * complex{float64} case compared to int64 * complex{float64}, since on the component level, the first is faster than the second:
```
@btime 2.0 * (1.0 + 3.0im)
@btime 2 * (1.0+3.0im)
```

**Comment by dkarrasch** [comment]
I'll close this for now, and get back to it with Julia v1.0.2 if necessary.
