### ISSUE TITLE
Bug in `Base.schedule_and_wait`

### ISSUE THREAD

**Issue by yebai** [JuliaLang/julia#29869]
There seems to be a bug in function Base.schedule_and_wait, which does not throw exceptions when an error is encountered in a task. Here is an MWE

```julia
function f()
    t = 0;
    while true
        t[2] = 0
    end
end

Base.schedule_and_wait(Task(f)) # never returns. 
```

However, `Base.schedule` seems to be able handle exceptions correctly:

```julia
Base.schedule(Task(f))
Task (failed) @0x0000000113da86d0
MethodError: no method matching setindex!(::Int64, ::Int64, ::Int64)
f() at ./REPL[4]:4
```

Julia version information

```julia
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

**Comment by JeffBezanson** [comment]
`schedule_and_wait` is not documented or exported, but the comment for it states that it's equivalent to `schedule(task); wait()` --- in other words it just blocks the caller, it does not wait for the passed task.

In the second example, `schedule` is just returning the Task object, and the printing of it shows its stack trace.
