### ISSUE TITLE
norm function in Julia 1.0

### ISSUE THREAD

**Issue by mikelehu** [JuliaLang/julia#29866]
Hi,

I have this error with Julia 1.0:

julia> v=[3,-2,6]`
julia> norm(v)

ERROR: UndefVarError: norm not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by joshday** [comment]
Julia 0.7 has deprecation warnings that are then removed in Julia 1.0.  To upgrade your code from 0.6 to 1.0, you should first use 0.7 and fix the deprecations.

```
julia> norm(1:10);
WARNING: Base.norm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Main
```

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
