### ISSUE TITLE
reverse(A; dims): Allow tuple for "dims" keyword

### ISSUE THREAD

**Issue by AndiMD** [JuliaLang/julia#29871]
Hi,

I suggest allowing a tuple for the dims keyword to make it consistent with sum(A;dims=(1,2)) etc.
Also, size(A,dims) could support a dims keyword for consistency.

Thanks!
Andreas

**Comment by StefanKarpinski** [comment]
> if I understand it correctly, reverse is implemented in lisp

Huh? Where are you getting that?

**Comment by HDictus** [comment]
Ah, ok,. thanks!

**Comment by HDictus** [comment]
#31716 should close this, only I'm having some trouble with the win32 build, which seems to have had some trouble cleaning and running tests on time, and the xcode tests, which can't seem to connect to github.
If anyone knows where to start wuth looking into this, please let me know.

**Comment by mcabbott** [comment]
Closed by  #37367, I think.
