### ISSUE TITLE
Cost Vector Formulation-Shipment Cost Minimization

### ISSUE THREAD

**Issue by vikas9087** [JuliaLang/julia#29897]
Hi All,

I am trying to solve shipment cost minimization. I am facing problem for creating Cost vector. Need your help to create Cost vector from a CSV file. Problem is as below

# of suppliers 100 (let us denote them as "i")
# of plants 250 (let us denote then as "j")

I need to make cost vector Cij for unit cost of shipment from "i" supplier to "j" plant. 

The data is given in a row form in a CSV file. For your reference I am including the sample file. 

Much Thanks.
VG
[Sample Data.xlsx](https://github.com/JuliaLang/julia/files/2541178/Sample.Data.xlsx)

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by vikas9087** [comment]
Thanks.
