### ISSUE TITLE
julia master crashes on const longer than 48 characters

### ISSUE THREAD

**Issue by macd** [JuliaLang/julia#29903]
Very long (>48) constant names crash in flisp

macd@mlap:~/jlang$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.603 (2018-11-02)
 _/ |\__'_|_|_|\__'_|  |  Commit cbb4f699c5 (0 days old master)
|__/                   |

julia (v1.1)> const this_is_a_very_long_constant_name_is_it_not_not_=144
144

julia (v1.1)> const this_is_a_very_long_constant_name_is_it_not_not_y=144fatal error: stack corruption detected

signal (6): Aborted
in expression starting at no file:0
__libc_signal_restore_set at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/nptl-signals.h:80 [inlined]
raise at /build/glibc-OTsEL5/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:48
abort at /build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79
__stack_chk_fail at /home/macd/julia/src/codegen.cpp:123
fl_accum_julia_symbol at /home/macd/julia/src/flisp/julia_extensions.c:325
apply_cl at /home/macd/julia/src/flisp/flisp.c:1226
do_trycatch at /home/macd/julia/src/flisp/flisp.c:898
apply_cl at /home/macd/julia/src/flisp/flisp.c:1806
do_trycatch at /home/macd/julia/src/flisp/flisp.c:898
apply_cl at /home/macd/julia/src/flisp/flisp.c:1806
do_trycatch at /home/macd/julia/src/flisp/flisp.c:898
apply_cl at /home/macd/julia/src/flisp/flisp.c:1806
do_trycatch at /home/macd/julia/src/flisp/flisp.c:898
apply_cl at /home/macd/julia/src/flisp/flisp.c:1806
_applyn at /home/macd/julia/src/flisp/flisp.c:682
fl_applyn at /home/macd/julia/src/flisp/flisp.c:722
jl_parse_input_line at /home/macd/julia/src/ast.c:774
#717 at ./client.jl:156 [inlined]

**Comment by JeffBezanson** [comment]
This seems to be due to a build inconsistency; `src/flisp/` needs to be rebuilt after #28373. `touch src/flisp/flisp.h` and `make` should do it.

**Comment by StefanKarpinski** [comment]
Can confirm that I could reproduce this and that rebuilding flisp fixes it.

**Comment by macd** [comment]
Confirmed that rebuild fixes it.  Thanks!
