### ISSUE TITLE
Using `repr` on `DateTime` shows pretty-printed version

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#29909]
According to the docstring for `repr`:

> Note that `repr(x)` is usually similar to how the value of x would be entered in Julia

Unfortunately this is not the behaviour of `Date` and `DateTime`:

```julia
julia> using Dates

julia> x = Date(2018)
2018-01-01

julia> repr(x)
"2018-01-01"

julia> y = DateTime(2018)
2018-01-01T00:00:00

julia> repr(y)
"2018-01-01T00:00:00"
```

**Comment by omus** [comment]
cc: @quinnj

**Comment by omus** [comment]
I'll note that I thought of this based upon a [comment](https://discourse.julialang.org/t/is-julia-a-general-purpose-language/17071/33) @JeffBezanson made on discourse.

**Comment by StefanKarpinski** [comment]
Yeah, this is not the desired behavior—it should print the way you input it.

**Comment by quinnj** [comment]
Yeah, looks like TimeTypes are just hitting the default path which calls `show`. Should be an easy up-for-grabs if anyone wants to take a crack at it.

**Comment by p-murli** [comment]
Hey, I'd like to contribute to this if it is open. I'm a beginner, so could you also guide me on how to get started with this issue?

**Comment by omus** [comment]
Hi @p-murli. To get started you should take a look at the code that the Dates stdlib uses for `show` and `string`. You can do that easily by running `using Dates; @edit show(stdout, today())`. I think what we want is to have the current `show` methods be `print` methods instead and add some new `show` methods. The end result should look like:

```julia
julia> using Dates

julia> d = Date(2018)
2018-01-01

julia> print(d)
2018-01-01
julia> string(d)
"2018-01-01"

julia> show(d)
Date(2018, 1, 1)

julia> repr(d)
"Date(2018, 1, 1)"
```
I'll mention that the `repr` method calls `show` and `string` calls `print` so you should only need to define `Base.show(io::IO, ...)` and `Base.print(io::IO, ...)` methods.

**Comment by sam0410** [comment]
Hi @omus, Please tell me if I am missing something. But aren't the following two outputs contradictory ? 
`
julia> d = Date(2018)
`
`
2018-01-01
`
and
`
julia> show(d)
`
`
Date(2018, 1, 1)
`

**Comment by JeffBezanson** [comment]
REPL printing calls `display`, which calls the 3-argument form of `show` (including a MIME type). So they can be different, e.g.
```
julia> [1,2]
2-element Array{Int64,1}:
 1
 2

julia> show([1,2])
[1, 2]
```
