### ISSUE TITLE
Function chaining and composition with funcitons having more that one argument

### ISSUE THREAD

**Issue by sirex** [JuliaLang/julia#29917]
It would be nice if these would work:

```julia
julia> 1:9 |> filter(isodd)
5-element Array{Int64,1}:
 1
 3
 5
 7
 9

julia> sqrt(16) |> convert(Int)
4

julia> map(convert(Int) ∘ sqrt, [4, 9, 16])
3-element Array{Int64,1}:
 2
 3
 4
```

Probably there are more functions like this, that could return function with single argument to be used in chaining or composition.

This is not easy to do in all cases, for example `split` with single argument can't be converted to function.

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaLang/julia/issues/5571, https://github.com/JuliaLang/julia/pull/24990 and https://github.com/JuliaLang/julia/pull/26436 for related discussions.

**Comment by javadba** [comment]
This JIRA was closed without a clear explanation of what if anything were added to the language. Per instruction by @StefanKarpinski have posted a question here  https://discourse.julialang.org/t/does-julia-support-chaining-of-collections-methods-function-chaining-at-this-point/32519
