### ISSUE TITLE
can't install IJulia

### ISSUE THREAD

**Issue by craig47** [JuliaLang/julia#29931]
The current version is 0.6.4, already installed Anaconda, jupyter Notebook. I installed Python 3.7 before, but then I uninstall it. What's worse, on 1.0.1 of Julia, if I type Pkg.add(), it directly splashes screen. The code in 0.6.4 is here. Thank you very much!

![1](https://user-images.githubusercontent.com/26669114/47982441-5116d580-e095-11e8-85a6-f76f9f8c6f3c.png)
![2](https://user-images.githubusercontent.com/26669114/47982442-5116d580-e095-11e8-8612-e2cdbf74df96.png)

**Comment by fredrikekre** [comment]
This looks like an error from one of the packages (maybe https://github.com/JuliaWeb/MbedTLS.jl ?) and should be reported there. Please direct any further questions to https://discourse.julialang.org/.

**Comment by craig47** [comment]
I directly copy julia0.6.4, .julia and julia. history from another PC, and it works

**Comment by craig47** [comment]
The solution I mentioned before didn't work. Finally, I uninstalled JAVA and cleaned Environment Variables about JAVA, then on Julia 1.0.1, it works.

**Comment by StefanKarpinski** [comment]
It's bizarre that Java should have anything to do with this. For further discussion, please use Discourse.
