### ISSUE TITLE
Contributing guide is somewhat outdated

### ISSUE THREAD

**Issue by christopher-dG** [JuliaLang/julia#29954]
The recommended tutorials are fairly old, and I have not watched them in depth but there may be plenty of code in there which no longer works. Perhaps refer to [this playlist](https://www.youtube.com/playlist?list=PLP8iPy9hna6SCcFv3FvY_qjAmtTsNYHQE) instead?

Dead link:
> New libraries should be developed as [packages](https://docs.julialang.org/en/latest/manual/packages#Package-Development-1).

Perhaps this link should point to Pkg.jl now instead:
> Julia has a built-in [package manager](https://github.com/JuliaLang/METADATA.jl)

This is more or less outside the "outdated" point, but immediately seeing the warning that says "this is unreleased and in-development" can be misleading and intimidating if you don't realize that it's not the stable docs (I think this applies to all the documentation links):
> The [Julia documentation](https://docs.julialang.org/en/latest) covers the language and core library features, and is searchable.

Another dead link:
> The Julia manual provides instructions on [creating Julia packages](https://docs.julialang.org/en/latest/manual/packages)

**Comment by laborg** [comment]
`CONTRIBUTING.md` has been updated many times since this issue was filed. I've checked and couldn't find any dead links in it anymore.
