### ISSUE TITLE
Issue installing Julia from Copr RHEL/Centos 7 Repo

### ISSUE THREAD

**Issue by gt-jpdied** [JuliaLang/julia#29967]
I'm trying to install Julia from the copr repo (https://copr.fedorainfracloud.org/coprs/nalimilan/julia/repo/epel-7). I have added epel as directed by the platform documentation (https://julialang.org/downloads/platform.html) however Julia will not install. Diving a bit into the RPMs, the Julia package wants libgit2.so.26, but the copr repo only provides libgit2.so.24. I'm thinking either a typo was made in the rpm dep list or libgit2 was not updated in the repo.

Yum output:
yum install julia
Resolving Dependencies
--> Running transaction check
---> Package julia.x86_64 0:1.0.1-2.copr2.el7 will be installed
--> Processing Dependency: julia-common = 1.0.1-2.copr2.el7 for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: openblas-threads for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libutf8proc.so.2()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libpcre2-8.so.0()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libopenlibm.so.2()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libopenblasp64_.so.0()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libmbedtls.so.10()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libjulia-debug.so.1()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libgit2.so.26()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Processing Dependency: libdSFMT.so.2.2()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
--> Running transaction check
---> Package dSFMT.x86_64 0:2.2.3-4.el7.centos will be installed
---> Package julia.x86_64 0:1.0.1-2.copr2.el7 will be installed
--> Processing Dependency: libgit2.so.26()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
---> Package julia-common.noarch 0:1.0.1-2.copr2.el7 will be installed
---> Package julia-devel.x86_64 0:1.0.1-2.copr2.el7 will be installed
---> Package mbedtls.x86_64 0:2.7.6-1.el7 will be installed
---> Package openblas-threads.x86_64 0:0.3.3-2.el7 will be installed
--> Processing Dependency: libgfortran.so.3(GFORTRAN_1.0)(64bit) for package: openblas-threads-0.3.3-2.el7.x86_64
--> Processing Dependency: libgfortran.so.3()(64bit) for package: openblas-threads-0.3.3-2.el7.x86_64
---> Package openblas-threads64_.x86_64 0:0.3.3-2.el7 will be installed
---> Package openlibm.x86_64 0:0.5.3-1.el7 will be installed
---> Package pcre2.x86_64 0:10.20-1.el7.centos will be installed
---> Package utf8proc.x86_64 0:2.1.1-1.el7.centos will be installed
--> Running transaction check
---> Package julia.x86_64 0:1.0.1-2.copr2.el7 will be installed
--> Processing Dependency: libgit2.so.26()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
---> Package libgfortran.x86_64 0:4.8.5-36.el7 will be installed
--> Processing Dependency: libquadmath = 4.8.5-36.el7 for package: libgfortran-4.8.5-36.el7.x86_64
--> Processing Dependency: libquadmath.so.0(QUADMATH_1.0)(64bit) for package: libgfortran-4.8.5-36.el7.x86_64
--> Processing Dependency: libquadmath.so.0()(64bit) for package: libgfortran-4.8.5-36.el7.x86_64
--> Running transaction check
---> Package julia.x86_64 0:1.0.1-2.copr2.el7 will be installed
--> Processing Dependency: libgit2.so.26()(64bit) for package: julia-1.0.1-2.copr2.el7.x86_64
---> Package libquadmath.x86_64 0:4.8.5-36.el7 will be installed
--> Finished Dependency Resolution
Error: Package: julia-1.0.1-2.copr2.el7.x86_64 (nalimilan-julia)
           Requires: libgit2.so.26()(64bit)
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles –nodigest

**Comment by ararslan** [comment]
Please note that, [as stated in the README](https://github.com/JuliaLang/julia#binary-installation), we do not endorse, maintain, nor recommend the installation of Julia binaries via system package managers. As such, there is nothing actionable for the Julia developers on this issue. You're welcome to ask for assistance with this on the Julia [Discourse](https://discourse.julialang.org).
