### ISSUE TITLE
Dict

### ISSUE THREAD

**Issue by peboes** [JuliaLang/julia#29964]
Hallo!
Error in Dict - keys
testconcordia="the here means that the first item in this line of output is item in this case our output consists of only one line and one item so this is redundant but this notation helps to read voluminous output that consists of many items spread over many lines for example if there were two rows of output with six items per row the second row would be labeled"

wordlist = split(lowercase(testconcordia))

wordcounts = Dict{String,Int64}() # Anlage wordcounts als Dict

for word in wordlist
       wordcounts[word]=get(wordcounts, word, 0) + 1
       end
       
wordcounts1=wordcounts # Sicherung

julia> [["$i, $(wordcounts1[i])"]  for i in sort(collect(values(wordcounts1)),rev=true) if "$(wordcounts1[i])" < "21"]
ERROR: KeyError: key 4 not found

julia> for i in 1:length(wordcounts1)
              println("$i => $(wordcounts1[i])")
              end
ERROR: KeyError: key 1 not found

Salutations
(x3.pb@t-online.de)

**Comment by vchuravy** [comment]
Hello there please post usage questions like this to https://discourse.julialang.org
