### ISSUE TITLE
customize @edit for any editor

### ISSUE THREAD

**Issue by haberdashPI** [JuliaLang/julia#29979]
I would like to propose adding the following function (or something like it) to julia, specifically the `InteractiveUtils` standard package. I am happy to make a pull request (looks very easy to change).

```julia
    define_editor(name => fn)
````

This would be an alternative to some sort of parsing of more complicated `$EDITOR` values to handle line numbers gracefully (ala https://github.com/JuliaLang/julia/issues/3165): the idea is that instead, for a given command, matched by `name`, you define a function to insert the line number, and you can add this to `~/.julia/config/startup.jl`.

`define_editor` would take a Pair matching a string (or regex) to a function. The function `fn` should accept two or three arguments: the command, the file path, and optionally the line number. It should return the command to open the file (at the given line number if passed), or nothing if this editor doesn't apply due to some condition (e.g. the format of the command or the operating system). 

When opening a file for editing, all defined editors are examined: if the regex name matches the specified editor and the specified `fn` returns a non-nothing value, the defined editor will be used to open a file for editing; otherwise we continue to check the other entries. There would be a fallback which would just call `$command $file`, but all other entries below could be defined in terms of this function.  
https://github.com/JuliaLang/julia/blob/0358a615c914e34e7b094c1de7694d5b228c96ec/stdlib/InteractiveUtils/src/editless.jl#L45-L63

For example, the following would define the commands to open neovim and to open Visual Studio Code on windows. 

```julia
define_editor("nvim" => (cmd,file,line) -> `$cmd +$line $file`)
if Sys.iswindows()
    define_editor(r"(?i)CODE\.EXE" => (cmd,file,line) ->  `$cmd -g $path:$line`
    define_editor(r"(?i)CODE\.EXE" => (cmd,file) ->  `$cmd -g $path`
end
```

I could just make a pull request for the editor I want to add (`nvr`:  this would allow me to open files in neovim from a terminal within neovim running julia); but it would be nice if I could just add

```
define_editor("nvr" => (cmd,file,line) -> `$cmd +$line $file`)
```

To `~/.config/init/startup.jl`

**Comment by StefanKarpinski** [comment]
Seems like a good idea. I would use `define_editor(f, pattern)` instead so that it can be called thusly:
```jl
define_editor(r"(?i)CODE\.EXE") do cmd, file, line
    `$cmd -g $path:$line`
end
```
It would be good to refactor the existing code to use the same mechanism to define editors. Care to take a crack at it?

**Comment by haberdashPI** [comment]
Sure! Sounds great. I'll give it a shot.

**Comment by laborg** [comment]
This has been implemented in https://github.com/JuliaLang/julia/pull/34107
