### ISSUE TITLE
completion resolves used names

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#29987]
This was making me think I was crazy for a while today:
```jl
julia> module M
           export blah
           blah = 1
       end
Main.M

julia> using .M

julia> bl<tab> = "other"
ERROR: cannot assign variable M.blah from module Main
Stacktrace:
 [1] top-level scope at none:0
```
Tab completing a name provided by `using` should not resolve it.

**Comment by JeffBezanson** [comment]
Dup of #29962?

**Comment by StefanKarpinski** [comment]
I'll rebuild and see if that fixes it. There's also a way to trigger this by pasting code that has the exported name in it even though it's a local variable. I'm guessing that there's some kind of accidental name lookup happening during the code paste.

**Comment by StefanKarpinski** [comment]
Yes, seems to be fixed by that PR. Will open a new issue if the cut-and-paste thing resurfaces.
