### ISSUE TITLE
1.0 badges

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#29984]
Are we going to have 1.0 badges?

https://pkg.julialang.org/badges/JLD_1.0.svg

**Comment by mbauman** [comment]
This isn't really actionable in this repository. A better place for it would be https://github.com/JuliaCI/PackageEvaluator.jl or https://github.com/JuliaComputing/NewPkgEval.jl

**Comment by StefanKarpinski** [comment]
Also generally better to ask questions like this on discourse.
