### ISSUE TITLE
Limit `nothing` interpolation error to `AbstractCmd` subtypes

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#30008]
The introduction of disallowing `print`/`string` with `nothing` (https://github.com/JuliaLang/julia/pull/27829) has introduced some headaches. From a recent [#gripes session](https://julialang.slack.com/archives/C67TK21LJ/p1541598629252300):

> Mike Innes [2018-11-07 07:50]
> ```julia
> julia> xs = [1, 2, 3]
> 
> julia> xs[nothing]
> ERROR: ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output > instead.
> ```
>
> Simon Danisch [08:32]
> I'm getting so sick of `nothing` should not be printed errors :smile: The worst is, they usually happen in the display stack, which has the bad habbit of removing stack traces
> 
> Eric Davies [10:43]
> It feels like an evil wizard is like "haha! you've fallen into my 'printing nothing' trap!"
> And it causes so many special cases to be written in Base and in user code, all because special > casing Cmd interpolation was too hard to do in the very short period of time before release.
> 
> Stefan Karpinski [10:46]
> I think it would be fine to limit the `nothing` error to splicing `nothing` into command objects
> 
> Stefan Karpinski [10:46]
> if someone wants to make a PR for that

**Comment by JeffBezanson** [comment]
I think this is actually a bug in the error throwing code, which should be using show/repr instead of interpolation. For example:

```
julia> xs["my horse is"]
ERROR: ArgumentError: invalid index: my horse is of type String
```

**Comment by omus** [comment]
I've also found this to be an annoyance with the change:
```julia
julia> x = nothing

julia> @error "Found unexpected value: $x"
┌ Error: Exception while generating log record in module Main at REPL[2]:1
│   exception =
│    ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.
│    Stacktrace:
│     [1] print(::Base.GenericIOBuffer{Array{UInt8,1}}, ::Nothing) at ./show.jl:566
│     [2] print_to_string(::String, ::Vararg{Any,N} where N) at ./strings/io.jl:122
│     [3] string(::String, ::Nothing) at ./strings/io.jl:155
│     [4] top-level scope at logging.jl:321
│     [5] eval(::Module, ::Any) at ./boot.jl:319
│     [6] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/omus/Development/Julia/1.0/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
│     [7] macro expansion at /Users/omus/Development/Julia/1.0/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
│     [8] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:259
└ @ Main REPL[2]:1
```

**Comment by StefanKarpinski** [comment]
I agree, let's just restrict the error to splicing `nothing` into command objects.

**Comment by KristofferC** [comment]
It seems like most of the time this issue comes up it is actually a bug that is being discovered.

**Comment by nickrobinson251** [comment]
https://github.com/JuliaLang/julia/pull/32148

**Comment by omus** [comment]
Thanks for the reminder. This issue has been resolved. At least all of the original gripes.
