### ISSUE TITLE
Master has an extra GC frame in gcd compared to 1.0.2

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#30037]
## 1.0.2:

```jl
julia> @code_llvm gcd(2,3)

; Function gcd
; Location: intfuncs.jl:31
define i64 @julia_gcd_35086(i64, i64) {
top:
; Location: intfuncs.jl:32
; Function ==; {
; Location: promotion.jl:425
  %2 = icmp eq i64 %0, 0
;}
  br i1 %2, label %L4, label %L6
...
```

## master:

```jl
julia> @code_llvm gcd(2,3)

; Function gcd
; Location: intfuncs.jl:31
define i64 @julia_gcd_354031087(i64, i64) {
top:
  %2 = alloca %jl_value_t addrspace(10)*, i32 3
  %gcframe = alloca %jl_value_t addrspace(10)*, i32 4
  %3 = bitcast %jl_value_t addrspace(10)** %gcframe to i8*
  call void @llvm.memset.p0i8.i32(i8* %3, i8 0, i32 32, i32 0, i1 false)
  %4 = call %jl_value_t*** inttoptr (i64 4466112080 to %jl_value_t*** ()*)() #4
...
```

Would be good to figure out why.

Ref https://github.com/JuliaLang/julia/pull/30036#issuecomment-438752535.

**Comment by KristofferC** [comment]
Ok..........

running

```
julia> @code_typed gcd(2,3)
```

before `@code_llvm` makes the gcframe go away.

```
julia> @code_typed gcd(2,3);

julia> @code_llvm gcd(2,3)

; Function gcd
; Location: intfuncs.jl:31
define i64 @julia_gcd_286418422(i64, i64) {
top:
; Location: intfuncs.jl:32
; Function ==; {
; Location: promotion.jl:403
  %2 = icmp eq i64 %0, 0
;}
  br i1 %2, label %L4, label %L6
...
```

**Comment by vtjnash** [comment]
we can see from the IR that inference had trouble inferring the throw:
%61 = call nonnull %jl_value_t addrspace(10)* @jl_invoke(%jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4458010768 to %jl_value_t*) to %jl_value_t addrspace(10)*), %jl_value_t addrspace(10)** %2, i32 3)

julia> unsafe_pointer_to_objref(Ptr{Any}(4458010768))
MethodInstance for (::getfield(Base, Symbol("#throw1#305")))(::Int64, ::Int64)

julia> ans.inferred
ERROR: UndefRefError: access to undefined reference

I suspect we use `gcd` to implement `string`, so inference is unable to determine if the result type will converge (similar to other recent issues like #29952). This is a special case though, where we avoided caching the inference result type (out of concern that it might be wider than desired)—but then we figure out that it is Bottom, so we've later discovered that the type actually cannot possibly get any better.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/30036.

Closing, feel free to open if this should be tracked further.
