### ISSUE TITLE
`ERROR: syntax: invalid named tuple element` misleading message

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#30030]
The following code produces the following syntax error.
```
julia> d = 4
4

julia> (
           a=2,
           b=3,
           c = (d=d)
           )
ERROR: syntax: invalid named tuple element "2"
```

The fix is to add a trailing `,` (comma) to the named tuple of one element, which is not quite what the error message says.

```
julia> (
           a=2,
           b=3,
           c = (d=d,)
           )
(a = 2, b = 3, c = (d = 4,))

```

```julia
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

(I ran into this when porting code away from using `NamedTuples.jl`on juia v0.6)

**Comment by JeffBezanson** [comment]
Thanks for catching this. There is indeed a glaring bug here, but after fixing it there won't be an error, since `(d=d)` is a valid expression. For example `f(a=(b=c))` assigns `b = c`, then passes the value of `c` as the `a` argument to `f`. I guess we can decide separately whether to change anything about that.

**Comment by goretkin** [comment]
I didn't catch that, but of course you're right. I had some non-syntax bugs in my code because @NT(a=3) produced a tuple, but (a=3) on v0.7 did not.

I think it's perfectly okay if there is no error for my original code. `(3)` doesn't produce a tuple, and neither does `(a=3)`.
