### ISSUE TITLE
Documentation of BLAS and LAPACK functions

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#3003]
Documentation of BLAS functions is not completed (for example ``trmv`` and ``trmm`` are not there)

Documentation of LAPACK functions seems to be missing.

**Comment by kshyatt** [comment]
Now that we have LAPACK documentation of some sort I am bumping this. LAPACK functions known to be missing:
- [ ] `laic1`
- [ ] `gelqf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `geqlf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `geqrt!{T<:BlasFloat}(A::StridedMatrix{T}, nb::Integer)`
- [ ] `geqrt3!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `geqrf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `gerqf!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `geqp3!{T<:BlasFloat}(A::StridedMatrix{T},jpvt::Vector{BlasInt})`
- [ ] `geqp3!{T<:BlasFloat}(A::StridedMatrix{T})`
- [ ] `stegr!(jobz::Char, dv::Vector, ev::Vector)`
- [ ] `stein!(dv::Vector, ev::Vector, w_in::Vector)`
- [ ] `stein!(dv::Vector, ev::Vector, eval::Real)`

**Comment by kshyatt** [comment]
`laic1` is still missing but I think everything else here is covered. Feel free to reopen if that's not the case.
