### ISSUE TITLE
performance problem at zip

### ISSUE THREAD

**Issue by thautwarm** [JuliaLang/julia#30042]
let's start with a simple case:
suppose we have a datasets which is typed with
```julia
Dtype = Float64
Vec = Vector{Dtype}
Data = Tuple{Vec, Int}
DataSets = Vector{Data}

# some records
x = [([-0.797886, -0.704789], 1), ([0.542116, -0.954421], 1), ([-0.880103, 0.772704], -1)]
```
And I want to get labels and features separated from a given datasets `d` through: `collect(zip(d...))`.

```julia
d= [x; x; x; x; x; x]
collect(zip(d...))
```
that works well, however, when it comes to a bit larger scale:

```julia
d = [x; x; x; x; x; x; x; x; x; x; x; x]
collect(zip(d...))
```
which seems to never stop...

Zipping numerous sequences used to work well at some early versions, any explanation?

P.S: I found this problem when trying to run some old codes and it turns out that Julia becomes running like falling into a dead loop.

**Comment by StefanKarpinski** [comment]
One doesn't generally want to use splatting on variable sized collections.

**Comment by thautwarm** [comment]
so which label(s) would you like to add to this issue? will it be considered to improve? 
In fact I'm not expecting to zip variable sized collections, and `unzip` is what I want. 
However it seems that `unzip` will not be added to built-ins recently.

**Comment by thautwarm** [comment]
unzip, unzip3, unzip4 seems to be essential infrastructures.

**Comment by StefanKarpinski** [comment]
There's an open issue to implement `unzip`: https://github.com/JuliaLang/julia/issues/13942. Someone just needs to do it.
