### ISSUE TITLE
lu! does not work for SparseMatrixCSC{Float64,Int64}

### ISSUE THREAD

**Issue by paul-packetized** [JuliaLang/julia#30053]
If you have a question or are unsure if the behavior you're experiencing is a bug,
please search or post to our Discourse site: https://discourse.julialang.org. We use
the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by paul-packetized** [comment]
Running this code on version 1.0.2 and 0.7 produces:
`A = sprand(10,10,.9)`
`lu!(A)`
produces:
`ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64,Int64})`

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/, as you self included in the top post:

> If you have a question or are unsure if the behavior you're experiencing is a bug,
please search or post to our Discourse site: https://discourse.julialang.org. We use
the GitHub issue tracker for bug reports and feature requests only.
