### ISSUE TITLE
sinpi and cospi return incorrect results when using `--math-mode=fast`

### ISSUE THREAD

**Issue by AboAmmar** [JuliaLang/julia#30073]
Julia 1.0:

I observed that when starting up Julia with the `--math-mode=fast` option, I get incorrect results for sinpi and cospi functions. 

With the default math mode:
```
julia> a = rand(5)
5-element Array{Float64,1}:
 0.5897641978923696
 0.2459464145866952
 0.06373272357797632
 0.26244049804714087
 0.7254898186800567

julia> cospi.(a)
5-element Array{Float64,1}:
 -0.27827964958957724
  0.7160540045153001
  0.9800223981473272
  0.6789380012385138
 -0.650617399829044

julia> sinpi.(a)
5-element Array{Float64,1}:
 0.9605000971495538
 0.6980448858186719
 0.19888715174581242
 0.7341956077737403
 0.7594056880480248
```
while with `--math-mode=fast` option:
```
julia> cospi.(a)
5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

julia> sinpi.(a)
5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
```

**Comment by vtjnash** [comment]
Yes, that’s what it means to run in fast math mode. If you wanted correct answers, you should pass the ieee flag.

**Comment by tomaklutfu** [comment]
If you look at llvm ir of `cospi(...::Float64)` in fast mode it just returns 1.00 and it goes away if `--inline=no` flag is used together.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/blob/6b2d211d22288ef7e66fc0f5bd21d8db952f28ba/base/special/trig.jl#L826 is 0 under fast math. That's pretty much the expected result...

**Comment by Keno** [comment]
... In which we discover why global fast math flags are a horrible idea. I guess we could have a `@nonfastmath` macro to say "no really, I need IEEE behavior here".

**Comment by vtjnash** [comment]
> Fast math mode should be off by no more than a few ulps;

That's a cute idea, but not what the flag means.

**Comment by StefanKarpinski** [comment]
> ... In which we discover why global fast math flags are a horrible idea.

💯%. However, we have it so should make this less broken.

This patch makes `@fastmath sinpi(x)` call `sin(pi*x)` instead of calling the `sinpi` implementation. However, it doesn't fix the behavior with the global `--math-mode=fast` flag on. Does that flag have a different effect than wrapping everything in `@fastmath`?

**Comment by StefanKarpinski** [comment]
Stop closing the issue, @vtjnash.

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/24568
dup https://github.com/JuliaLang/julia/issues/21375
ref https://github.com/JuliaLang/julia/issues/25028

**Comment by vtjnash** [comment]
> Does that flag have a different effect than 

dup https://github.com/JuliaLang/julia/issues/26828

**Comment by vtjnash** [comment]
Why can't we close duplicate issues with extensive prior discussion?

**Comment by StefanKarpinski** [comment]
Forgot to include the patch:
```diff
diff --git a/base/fastmath.jl b/base/fastmath.jl
index 0dccf8ba4b..482050da81 100644
--- a/base/fastmath.jl
+++ b/base/fastmath.jl
@@ -61,6 +61,7 @@ const fast_op =
          :cbrt => :cbrt_fast,
          :cis => :cis_fast,
          :cos => :cos_fast,
+         :cospi => :cospi_fast,
          :cosh => :cosh_fast,
          :exp10 => :exp10_fast,
          :exp2 => :exp2_fast,
@@ -75,6 +76,7 @@ const fast_op =
          :min => :min_fast,
          :minmax => :minmax_fast,
          :sin => :sin_fast,
+         :sinpi => :sinpi_fast,
          :sincos => :sincos_fast,
          :sinh => :sinh_fast,
          :sqrt => :sqrt_fast,
@@ -310,6 +312,9 @@ sincos_fast(v) = (sin_fast(v), cos_fast(v))
     min_fast(x::T, y::T) where {T<:FloatTypes} = ifelse(y > x, x, y)
     minmax_fast(x::T, y::T) where {T<:FloatTypes} = ifelse(y > x, (x,y), (y,x))

+    cospi_fast(x::Union{Real,Complex}) = cos(pi*x)
+    sinpi_fast(x::Union{Real,Complex}) = sin(pi*x)
+
     # complex numbers

     function cis_fast(x::T) where {T<:FloatTypes}
```
With this patch applied we have this which is amusing:
```jl
julia> sinpi(0.25)
0.0

julia> @fastmath sinpi(0.25)
0.7071067811865475
```
It seems like one approach to improving this situation would be automatically applying the `@fastmath` transformation when in `--math-mode=fast` since then at least any specific behaviors that `@fastmath` applies will happen in the global mode too, which seems better.

**Comment by StefanKarpinski** [comment]
Because I reopened it for discussion and asked you to stop closing it.

**Comment by vtjnash** [comment]
Please stop re-opening it then, and do discussion on discourse

**Comment by StefanKarpinski** [comment]
First off, do not tell me how to use GitHub on the JuliaLang project—it is rude and disrespectful.

The problem here is not the general brokenness of `--math-mode=fast`, which I am extremely well aware of. The specific problem here is that `sinpi` and `cospi` are very broken under `--math-mode=fast`. I also have a specific fix this problem: apply the patch I've posted here and change `--math-mode=fast` to apply `@fastmath` universally. That seems like it would fix this issue.

**Comment by vtjnash** [comment]
It would hinder our inference in more cases (we shouldn't run inference on floating point numbers when fast-math might get specified), wouldn't alter the case where the user calls `sinpi` directly, and leads to weird scope issues (`@fastmath` is a syntactic, not semantic, transform—doc issue #26828—so applying it would not preserve behavior). It also can't really fix the correctness issues with that flag, just handle a different subset of cases until the compiler becomes smarter (or does something dumber)...

What does it mean to "apply a macro everywhere"?

**Comment by StefanKarpinski** [comment]
> What does it mean to "apply a macro everywhere"?

I guess it would mean apply the macro to the input of eval before evaling.

**Comment by PallHaraldsson** [comment]
Maybe my PR #41638 should be backported to 1.8.1 and 1.6.x?

With `@fastmath` this is however fixed on both.

**Comment by KristofferC** [comment]
> Maybe my PR https://github.com/JuliaLang/julia/pull/41638 should be backported to 1.8.1 and 1.6.x?

No, that is exactly something that you shouldn't backport.

**Comment by oscardssmith** [comment]
Also, is this now ready to close?

**Comment by PallHaraldsson** [comment]
Should bugs (like these) be kept open, that are still bugs in 1.6?
