### ISSUE TITLE
Julia 1.0.2 reapeat function cost many times than matlab‘s repmat

### ISSUE THREAD

**Issue by outyang** [JuliaLang/julia#30082]
i update mycode at here[https://github.com/outyang/repeatandrepmat](url)
I found julia’s repeat function run very slowly than matlab’s repmat and python too,here is my code of julia and matlab for a test of two functions,
the test contains smaller arrays and bigger,script and function,if any illogicality please point it out and i’ll try to write a correctly ones.

**Comment by fredrikekre** [comment]
Closing in favor of https://discourse.julialang.org/t/julia-1-0-2-reapeat-function-cost-many-times-than-matlab-s-repmat/17708.
