### ISSUE TITLE
Feature request: round-to-nearest integer division

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#30099]
Integer division currently offers 3 rounding modes: `fld`, `cld`, and `div`, corresponding to the rounding modes offered by `floor`, `ceil`, and `trunc` (round towards minus infinity, plus infinity, and zero).

I suggest a fourth integer division function, maybe called `rdd`, that rounds towards the nearest integer, breaking ties towards even, corresponding to the rounding performed by `round`:

```Julia
function rdd(x::T, y::T)::T where {T <: Integer}
    round(T, x / y)
end
```
... except without converting to a floating-point number.

**Comment by chethega** [comment]
>... except without converting to a floating-point number.

What is the problem of the code you wrote?

**Comment by simonbyrne** [comment]
Rather than add a new function, we can just overload `div` with rounding mode arguments. See https://github.com/JuliaLang/julia/issues/9283

**Comment by eschnett** [comment]
@chethega The code I wrote is an experiment with fixed point arithmetic, quite similar to [`FixedPointNumbers`](https://github.com/JuliaMath/FixedPointNumbers.jl). To implement correct rounding after division, I had to implement an `rdd` function as described above. The function is non-trivial, and would benefit from low-level optimizations.

@simonbyrne Yes, overloading `div` seems better than yet another cryptic function name.

(This is the function I wrote:
```Julia
# Correctly rounded division (breaking ties towards even)
export rdd
function rdd(x::T, y::Signed)::T where {T <: Signed}
    d, m = fldmod(x, y)::Tuple{T, T}
    a2m = abs(m << 1)
    ay = abs(y)
    if a2m > ay
        # Round up
        d += T(1)
    elseif a2m == ay
        # Break tie towards even (round up if the result is odd)
        d += d & T(1)
    end
    d
end
```
)

**Comment by bobcassels** [comment]
For the benefit of those who stumble on this issue, Julia `div(x, y, RoundNearest)` now does this.

It would have saved me some floundering if someone had noted this and closed this issue.
