### ISSUE TITLE
addproc execname not evaluated on remote machine

### ISSUE THREAD

**Issue by rabarar** [JuliaLang/julia#30104]
when calling addproc on a collection of heterogeneous machines, the default for execname as written in the docs is

```
exename: name of the julia executable. Defaults to "$(Sys.BINDIR)/julia" or "$(Sys.BINDIR)/julia-debug" as the case may be.
```
But the calling value's default is used rather than the value of the remote host. Shouldn't the excename if not specified be the default value ON THE MACHINE that is being called?

**Comment by andreasnoack** [comment]
Very similar to https://github.com/JuliaLang/julia/issues/22841

**Comment by vtjnash** [comment]
I think this is intended behavior, the default behavior is to try to start a homogeneous cluster. It should take additional effort for the user to do differently
