### ISSUE TITLE
include a model file, but having error "missing last argument in "2:" range expression "

### ISSUE THREAD

**Issue by Balance37** [JuliaLang/julia#30100]
Hi, 
I was trying to use a Model that I created in the same directory as the "main.jl", however, it has an error "missing last argument in "2:" range expression " when running this line of code:
include("MyModel.jl")

Thanks

(I am not sure if this is the right place to post my question, please let me know if I should post it somewhere else)

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
