### ISSUE TITLE
addprocs(machines; tunnel=false, sshflags=``, max_parallel=10, kwargs...) exename keyword

### ISSUE THREAD

**Issue by rabarar** [JuliaLang/julia#30103]
when calling addproc on a collection of heterogeneous machines, the default for execname as written in the docs is

**Comment by ViralBShah** [comment]
Please provide a coherent report. We can reopen this once you update it.

**Comment by ViralBShah** [comment]
Dup of #30104.

**Comment by rabarar** [comment]
What song you understand? the problem is that the value passed  for execname to the remote proc isn't the default value on the remote machine, rather it's the default value from the calling machine -- which isn't necessarily the same. And when they are not the same, the proc fails to start since I can't find the Julia executable.
