### ISSUE TITLE
(;) returns nothing rather than empty named tuple

### ISSUE THREAD

**Issue by piever** [JuliaLang/julia#30115]
Intuitively I would have imagined that `(;)` would be the syntax for the empty `NamedTuple`, whereas it returns `nothing` instead. After posting it on slack it seems that the rationale is that it is parsing as a concatenation of expressions. For example `(1;)` returns `1`, so `(;)` should return the value of the first expression which is `nothing`.

I'm not sure which is more intuitive but maybe it could be changed to return `NamedTuple()`. The change in technically breaking though I imagine in practice very little code will rely on `(;) === nothing`

**Comment by StefanKarpinski** [comment]
We should definitely fix this since the empty named tuple is something that it's useful to have syntax for whereas having `(;)` as a confusing syntax for `nothing` is distinctly non-useful.

**Comment by JeffBezanson** [comment]
Used to be a syntax error, then from what I can tell this "feature" was "added" in v0.5 :) Probably best to make it an error again in 1.1?

**Comment by StefanKarpinski** [comment]
Is the plan to make it an error and later use if for an empty named tuple? Or leave it as an error?

**Comment by JeffBezanson** [comment]
I'm not sure; I guess it's (slightly) breaking either way, so maybe it's equally good/bad to just switch it directly to an empty named tuple?

**Comment by StefanKarpinski** [comment]
> so maybe it's equally good/bad to just switch it directly to an empty named tuple?

👍 yes, I think that's the way to go.

**Comment by JeffBezanson** [comment]
There is some package code (very little) that uses `:(;)` in macros to make an empty block expression.

**Comment by StefanKarpinski** [comment]
Triage has decided to make `(;)` an error for now.

**Comment by StefanKarpinski** [comment]
We never did end up doing anything about this, did we?

**Comment by JeffBezanson** [comment]
It doesn't seem too important. I can make a branch that turns it into an error though. MacroTools changed its use of it already, so it might be ok.

**Comment by JeffBezanson** [comment]
Here's something I don't think came up: how to parse `(;;)`, `(;;;)` etc? Error? Still as an empty block?

**Comment by StefanKarpinski** [comment]
As 3- and 4-dimensional tuples, obviously.
