### ISSUE TITLE
Colorize output of `methods` in REPL

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#30110]
The output of `methods` can be hard to read in the REPL
It would be good to use some colour (/bold) 
to seperate the signature from the line-info.

You can see that in the stacktrace at the top of the image below.
Contrast how easy to read it is, vs the methods list at the bottom.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/5127634/48843626-7bec7380-ed8f-11e8-97eb-c8a0110c4773.png">

**Comment by StefanKarpinski** [comment]
Seems like an OhMyREPL issue rather than a Base one? cc @KristofferC

**Comment by oxinabox** [comment]
could be
though OhMyREPL does not currently do any reformatting of outputs / `display`/`show`

And doing this would most definately be monkey-patching `show`.

**Comment by StefanKarpinski** [comment]
The colorization in your REPL is not due to Base and requires CSTParser, which is not a stdlib. So doing this would either require including CSTParser and much of OhMyREPL in stdlib or it would require having OhMyREPL monkey-patch Base's printing of methods to colorize them.

**Comment by KristofferC** [comment]
It could perhaps be colorized in the same way as the stacktrace.

<img width="690" alt="screenshot 2018-11-21 at 11 17 12" src="https://user-images.githubusercontent.com/1282691/48854138-24460c00-ed7f-11e8-9c69-47aa0ed1a2fc.png">

**Comment by o314** [comment]
It seems to me that `print(IOContext(stdout, :compact => true), methods(+))` does not handle compact correctly. It could be a good thing to fix them both by the way, they're very close.
