### ISSUE TITLE
generic linear-algebra functions for Number types (e.g. BigFloat)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#3014]
It would be nice to have linear-algebra functions for `BigFloat` (possibly as an external package?) and other generic `Number` types.

~~Currently, `\` on a `BigFloat` converts to `Float64`; `eig` and `qr` don't work at all.~~`eig` doesn't work.

The good news is that LINPACK-style triple-loop textbook implementations (straight out of Trefethen or Golub & Van Loan) should mostly suffice.  Since `BigFloat` operations are CPU-limited rather than memory-limited, there is no reason to implement a LAPACK/BLAS-style blocked algorithm.

cc: @andrioni

Updated 21 August 2015 by @andreasnoack

**Comment by paulanalyst** [comment]
what wrong , in last line :
ERROR: EigenGeneral not defined


               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+1984 (2014-12-07 23:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 052f54e (24 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using LinearLeastSquares
ERROR: LinearLeastSquares not found
 in require at loading.jl:47

julia> A = big(randn(3,3));b = A*ones(3)
3-element Array{Base.MPFR.BigFloat,1}:
 -2.9446960791946807933783247790415771305561065673828125e-01
  3.236218918047749248945166300472919829189777374267578125e+00
 -2.56092452427787808932890811774996109306812286376953125e+00

julia> A\b # by LU
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 9.999999999999999999999999999999999999999999999999999999999999999999999999999827e-01

julia> qrfact(A)\b
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000035e+00
 9.999999999999999999999999999999999999999999999999999999999999999999999999999741e-01

julia> cholfact(A'A)\(A'b)
3-element Array{Base.MPFR.BigFloat,1}:
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1.000000000000000000000000000000000000000000000000000000000000000000000000000017e+00
 1e+00

julia> vr, vi, v3 = big(randn(3)), big(randn(3)), big(randn(3));

julia> V = [vr + vi*im vr - vi*im  v3];

julia> V = [vr + vi*im vr - vi*im  v3]
3x3 Array{Complex{Base.MPFR.BigFloat},2}:
 -2.92480246431090773473471244869870133697986602783203125e-01-1.23301741773709269689440759520948631688952445983886
71875e-01im    -6.248288026283737028876430485979653894901275634765625e-01+0e+00im
     1.2486111443976664059363201886299066245555877685546875e+00-4.780390824486795975367670052946778014302253723144
53125e-01im     -1.437786704485576105838617877452634274959564208984375e+00+0e+00im
    4.5285454219578136214607866349979303777217864990234375e-02-7.6873228736745721767498196186352288350462913513183
59375e-02im     -8.374534723584889928105212675291113555431365966796875e-01+0e+00im

julia> A = real(V*diagm([1 + im, 1 - im, 1])/V)
3x3 Array{Base.MPFR.BigFloat,2}:
  2.576802034195741440834721530934809151596626451040076198981114681613706386162393e+00    -2.111621855823541931575
384837701543463270383359650712117854830826270375426030325e+00
 -8.559677601741757504896778861974182932186714773709164352191451088403852069777578e+00      9.78052219886619411959
11689523504923366255761234952124648193339633989847339366e+00
 -4.188140715194974510238856704548191419461734044485174519602972737487350197843463e-01      1.40012483629965998591
0674299516564706036794287389179472732815371667614610927464e+00

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: LinearAlgebra not defined

julia> Pkg.clone("https://github.com/andreasnoack/LinearAlgebra.jl")
INFO: Cloning LinearAlgebra from https://github.com/andreasnoack/LinearAlgebra.jl
INFO: Computing changes...

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: LinearAlgebra not defined

julia> A
3x3 Array{Base.MPFR.BigFloat,2}:
  2.576802034195741440834721530934809151596626451040076198981114681613706386162393e+00    -2.111621855823541931575
384837701543463270383359650712117854830826270375426030325e+00
 -8.559677601741757504896778861974182932186714773709164352191451088403852069777578e+00      9.78052219886619411959
11689523504923366255761234952124648193339633989847339366e+00
 -4.188140715194974510238856704548191419461734044485174519602972737487350197843463e-01      1.40012483629965998591
0674299516564706036794287389179472732815371667614610927464e+00

julia> using LinearAlgebra
ERROR: ArrayViews not found
 in require at loading.jl:47
 in include at boot.jl:242
 in include_from_node1 at loading.jl:128
 in include at boot.jl:242
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\cholesky.jl, in expression starting on line 6
while loading C:\Users\SAMSUNG2\.julia\v0.4\LinearAlgebra\src\LinearAlgebra.jl, in expression starting on line 11

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating LinearAlgebra...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("ArrayVievs")
ERROR: unknown package ArrayVievs
 in wait at task.jl:51
 in sync_end at task.jl:311
 in add at pkg/entry.jl:319
 in add at pkg/entry.jl:71
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:30
 in cd at pkg/dir.jl:28
 in add at pkg.jl:20

julia> Pkg.add("ArrayViews")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Installing ArrayViews v0.4.8
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating LinearAlgebra...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using LinearAlgebra

julia> LinearAlgebra.EigenGeneral.eigvals!(copy(A))
ERROR: EigenGeneral not defined


Paul

**Comment by andreasnoack** [comment]
@paulanalyst This should be reported at https://github.com/andreasnoack/LinearAlgebra.jl

**Comment by andreasnoack** [comment]
Closing in favor of #5429
