### ISSUE TITLE
IdDict does not fully implement `Dictionaries` specification: missing `get!(Callable, IdDict, Key)` method

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#30165]
This issue appears in both Julia 1.0 and `master:

The user manual claims that the functions listed under https://docs.julialang.org/en/v1/base/collections/#Dictionaries-1 are "Fully implemented by:" `IdDict`, `Dict` and `WeakKeyDict`.

But that does not seem to be the case:
```
julia> d = IdDict(Pair(:a,1), Pair(:b,2), Pair(3,3))
IdDict{Any,Int64} with 3 entries:
  :a => 1
  :b => 2
  3  => 3

julia> get!(d, "b") do
           42
       end
ERROR: MethodError: no method matching get!(::getfield(Main, Symbol("##5#6")), ::IdDict{Any,Int64}, ::String)
Closest candidates are:
  get!(::IdDict{K,V}, ::Any, ::Any) where {K, V} at abstractdict.jl:649
  get!(::Dict{K,V}, ::Any, ::Any) where {K, V} at dict.jl:421
  get!(::Union{Function, Type}, ::Dict{K,V}, ::K) where {K, V} at dict.jl:448
  ...
Stacktrace:
 [1] top-level scope at none:0
```

Compared to this:
```
julia> d = Dict(Pair(:a,1), Pair(:b,2), Pair(3,3))
Dict{Any,Int64} with 3 entries:
  :a => 1
  :b => 2
  3  => 3

julia> get!(d, "b") do
           42
       end
42
```

It would be really nice if this could be fixed. I'd try to write a PR, but this is seems to be way beyond my current Julia-Fu, involving undocumented macros like `@nospecialize` etc.

BTW, I also wonder if one could/should write a generic set of tests which take any object which claims to implement the fully Dictionary implementation, and then thoroughly verifies this by trying all kinds of methods. Then one could systematically and uniformly test this for the three supposedly conforming implementations.

**Comment by JeffBezanson** [comment]
This can just be added. At first we only need an implementation that works, and it can be made more efficient (avoiding a double lookup) later.
