### ISSUE TITLE
mul! of sparse and diagonal for non-commutative eltypes?

### ISSUE THREAD

**Issue by dkarrasch** [JuliaLang/julia#30161]
Here (and in the corresponding `rmul!`/`lmul!`)

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1165-L1192

we assume that multiplication of the eltypes of `D` and `A` is commutative, whereas we do care about the order of multiplication here:

https://github.com/JuliaLang/julia/blob/58c0ed57dc796a9bb0759ce49781d97b8474eee3/stdlib/SparseArrays/src/linalg.jl#L1194-L1218

I don't have a use/test case for matrix multiplication with non-commutative eltypes, so somebody should tell if there is an issue here (with an easy fix). @Jutho ?

**Comment by andreasnoack** [comment]
It's only the second of the methods and `lmul!(D::Diagonal, A::SparseMatrixCSC)` that have the problem, right?

**Comment by dkarrasch** [comment]
@andreasnoack: Yes, that's right, sorry for being imprecise. I'll prepare a PR with a fix.

@Jutho: I just remembered your comment in the other discussion on how you learned to appreciate `rmul!` and `lmul!` in the non-commutative case, and that made me check this situation here.
