### ISSUE TITLE
Warning: Some registries failed to update: Julia version 1.0.2

### ISSUE THREAD

**Issue by jimibengbeng** [JuliaLang/julia#30170]
julia> using Pkg

julia> Pkg.update()

Warning: Some registries failed to update:
│     — `~/.julia/registries/General` — registry dirty
└ @ Pkg.API /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:157

**Comment by KristofferC** [comment]
Delete the registry folder and it should fix itself.
