### ISSUE TITLE
standalone greek letter with hat does not show  in REPL

### ISSUE THREAD

**Issue by epogrebnyak** [JuliaLang/julia#30175]
I would like to use small greek letter beta with a hat in REPL.

For latin letters I type `b\hat<tab>` and get b with a hat.

`\beta<tab>\hat<tab>`  does not show beta with a hat, but rather a beta and a hat after it.

I can get [beta][beta-hat] by `\beta<tab>\hat<tab>\beta<tab>`, which indicates the chracter beta with hat above it does graphically exist.

The [documentation](https://docs.julialang.org/en/v1/manual/variables/index.html) also endorses a hat after, and not above a greek, which I think is not correct: 

> For example, the variable name δ can be entered by typing \delta-tab, or even α̂₂ by \alpha-tab-\hat- tab-\_2-tab.

**Comment by Keno** [comment]
The rendering of these characters is up to the terminal emulators. Please file an issue against the one you're using. E.g., it works fine in iTerm:
<img width="152" alt="screen shot 2018-11-28 at 11 01 10 am" src="https://user-images.githubusercontent.com/1291671/49144168-f459b400-f2fc-11e8-8385-7bf0fe8cfbd8.png">

**Comment by StefanKarpinski** [comment]
Yes, that's `β̂` (beta hat) as intended on macOS using iTerm2. I guess Windows may just not by default have a font that includes that character. There's much we can do, unfortunately, short of shipping both a better terminal emulator (https://github.com/JuliaLang/julia/issues/7267) and a better Unicode font.

**Comment by epogrebnyak** [comment]
There is some strange console behaviour: 

1. *the font is not a problem*: the sequence `\beta<tab>\hat<tab>\beta<tab>` actually produces a beta and a beta hat, so we know that physically the font used is capable of combining the beta and ^ in one character. Same behaviour in IPython console. Must be console reaction to character sequences. 

2. `println("\u03B2\u0302")` is two characters on my screen, beta and hat and `println("k\u0302")` is one character k with hat, similar in python.

For reference, 
- conemu has a lot of font settings and trials for non-combined [unicode symbols](https://conemu.github.io/en/UnicodeSupport.html)
- [this stackoverflow answer](https://stackoverflow.com/questions/388490/how-to-use-unicode-characters-in-windows-command-line) was very helpful about Windows unicode
- this arctile about [greeks in python](https://pythonforundergradengineers.com/unicode-characters-in-python.html) provides a usecase for engineers:

> A useful one in engineering is the hat ^ symbol. This is typically used to denote unit vectors. We can add a hat ^ (also called a circumflex) by putting the unicode escape after the letter you want to add a hat to.

Looks like a topic generally peripheral to julia development, not a priority, but nice julia allowed at least to address this issue. Thanks for your comments!
