### ISSUE TITLE
String type have many unexpected behaviour.

### ISSUE THREAD

**Issue by aaronmatrix** [JuliaLang/julia#30176]
1. it's not expected to using `*` to join two string. 
2.i think the char type is not used in many applications, why don't use `char(CharType)` to declare a char type? and then we can use `'StringType'` or `"StringType"` to declare string. It's useful when you do not want to enter a `Shift`.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
