### ISSUE TITLE
BigFloat rounding no longer works

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#30188]
```jl
julia> BigFloat(1//10, RoundDown)
1.0000000000000001e-01

julia> BigFloat(1//10, RoundUp)
1.0000000000000001e-01
```

This is causing failures of `IntervalArithmetic.jl` with latest Julia master and is a regression from 1.0.2.

cc @simonbyrne

**Comment by simonbyrne** [comment]
Probably due to #29157: I'll look into it
