### ISSUE TITLE
`<<` StackOverflowError instead of MethodError

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#30197]
The definition
```
<<(x::Integer, c::Unsigned) = c <= typemax(UInt) ? x << (c % UInt) : zero(x)
```
https://github.com/JuliaLang/julia/blob/89a2c08136ec516031eca276f612631b4ab010bf/base/operators.jl#L568

loops. For example

```
julia> using GeometryTypes
julia> OffsetInteger{-1}(3) << UInt(2)
ERROR: StackOverflowError:
Stacktrace:
 [1] <<(::OffsetInteger{-1,Int64}, ::UInt64) at ./operators.jl:568 (repeats 80000 times)
```

or, self-contained
```
julia> struct A <: Integer
       end

julia> A() << UInt(2)
ERROR: StackOverflowError:
Stacktrace:
 [1] <<(::A, ::UInt64) at ./operators.jl:568 (repeats 80000 times)
```

Obviously, to get `<<` working, I need to define an additional method, which would be more specific and prevent infinite recursion. So I'm not sure if this counts as a bug. Making an issue just in case there's a way to fix it to get a `MethodError` instead.

Related: https://github.com/JuliaLang/julia/issues/26552
```
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by vtjnash** [comment]
Fixed by 9562bdfc8bc4ef09426b697ee8e29d06e1643575 (#30906)
