### ISSUE TITLE
Add ldiv!(::Diagonal, SparseMatrixCSC)

### ISSUE THREAD

**Issue by dkarrasch** [JuliaLang/julia#30207]
I realized we only have an `rdiv!(A::SparseMatrixCSC, ::Diagonal)` method, so I decided to check which method is called for `ldiv!` with reversed argument order, and I found it's this one

https://github.com/JuliaLang/julia/blob/795591f3eb3ec4d9980926d0cd6738692a6d821a/stdlib/LinearAlgebra/src/diagonal.jl#L321-L336

which doesn't seem to make use of sparsity. I thought I'd give it a quick try to implement a sparse version:
```
using LinearAlgebra, SparseArrays, BenchmarkTools

function ldiv2!(D::Diagonal{T}, A::SparseMatrixCSC{T}) where {T}
    # @assert !has_offset_axes(A)
    if size(A, 1) != length(D.diag)
        throw(DimensionMismatch("diagonal matrix is $(length(D.diag)) by $(length(D.diag)) but right hand side has $(size(A,1)) rows"))
    end
    nonz = nonzeros(A)
    Arowval = A.rowval
    b = D.diag
    any(iszero, b) && throw(SingularException())
    @inbounds for col = 1:n, p = A.colptr[col]:(A.colptr[col + 1] - 1)
        nonz[p] = b[Arowval[p]] \ nonz[p]
    end
    # lmul!(Diagonal(inv.(b)), A)
    A
end
```
After testing
```
m, n = 10000, 2000
D = Diagonal(rand(m) .+ 1);
A = sprand(m, n, 0.02);
using Test
@test ldiv!(D, copy(A)) == ldiv2!(D, copy(A))
@btime ldiv!($D, $A); # 1.054 s (0 allocations: 0 bytes)
@btime ldiv2!($D, $A); # 61.155 ms (2793085 allocations: 48.78 MiB)
```
I found that it has two disadvantages:
1. In contrast to the above method, the elements of `b = D.diag` are accessed several times (i) due to the `any(iszero, b)`, and (ii) in the loop, but (ii) is consistent with `lmul!` where you need to hop around the diagonal entries of `D`.
2. For some reason that I don't understand, it allocates quite some memory.

The big advantage, however, is that it is way faster, the fastest version being the one with the commented out line `lmul!(Diagonal(inv.(b)), A)`, which obviously allocates the most. I tried that one only for comparison.

Would this be useful? If yes, how can I avoid the allocations?

**Comment by andreasnoack** [comment]
> For some reason that I don't understand, it allocates quite some memory.

It's because you have forgotten to define `n=size(A,2)` in the function so it's currently using the global `n`. One that has been fixed, there are no allocations.

**Comment by dkarrasch** [comment]
So cool, thanks @andreasnoack ! I guess there is then no doubt that this is useful?
```
@btime ldiv2!($D, $A); # 13.406 ms (0 allocations: 0 bytes)
```

**Comment by andreasnoack** [comment]
No doubt. It would be great if you could prepare a PR.
