### ISSUE TITLE
Use where keyword only once in displaying parametric types

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#30201]
**Edit**:
For example:
```Julia
julia> Dict{K,V} where {V,K}
Dict{K,V} where K where V

julia> Dict{K,V} where K where V
Dict{K,V} where K where V
```
It would be nice to print both as `Dict{K,V} where {V,K}`.

**Comment by JeffBezanson** [comment]
They are printed the same for me on master.

**Comment by JeffBezanson** [comment]
Note that sometimes the following distinction needs to be conveyed though:
```
julia> Dict{K, V} where {V, K}
Dict{K,V} where K where V

julia> Dict{K, V} where {K, V}
Dict

julia> (Dict{K, V} where {V, K}){Int}
Dict{K,Int64} where K

julia> (Dict{K, V} where {K, V}){Int}
Dict{Int64,V} where V
```

**Comment by AzamatB** [comment]
@JeffBezanson Sorry, I've edited my original formulation.

**Comment by JeffBezanson** [comment]
I like the idea of printing only one `where`, but I think it would be very annoying to always print Dict as `Dict{K,V} where {K,V}`. It makes sense to print anything structurally equal to `Dict` as `Dict`.

**Comment by StefanKarpinski** [comment]
I don't see the issue with the current printing since as @JeffBezanson said, `Dict{K,V} where {K,V}` and `Dict{K,V} where {V,K}` are not the same—they take their type parameters in opposite order. They are type-equal but they are not the same so imo they shouldn't print the same.

**Comment by StefanKarpinski** [comment]
Agree that printing `Dict{K,V} where K where V` as `Dict{K,V} where {V,K}` would be nice, however.

**Comment by tkf** [comment]
Is `show(::IO, ::Type)` a part of the public API?  If so, I think this is impossible until 2.0?

Actually, I think it makes sense to explicitly mark `show(::IO, ::Type)` to be non-public API.  Otherwise, it is impossible to extend the APIs based on struct (e.g., adding new parametrized fields to a struct).  But I'm not entirely sure about this.

**Comment by JeffBezanson** [comment]
> And the proposal is that the latter should print symmetrically as `Dict{K,V} where V where K` – reordering keywords should just reorder them in printing as well, instead of entirely changing what's printed.

This is just not practical. As types get more complicated it's way too verbose.

**Comment by affans** [comment]
Sorry to derail the topic but what does `Dict{K, T} where {K, T}` actually mean .. i.e how does one use it? I tried 
```
a = Dict{K, T} where {K, T}
a["1" => 1]
ERROR: MethodError: Cannot `convert` an object of type Pair{String,Int64} to an object of type Dict
```

**Comment by AzamatB** [comment]
@affans We've discussed your exact question on the Julia's Slack. The channel is #general

**Comment by mbauman** [comment]
Bringing some of my comments from there:

Perhaps this concrete example is helpful:
```julia
julia> DimsFirstArray{N,T} = Array{T,N}
Array{T,N} where T where N

julia> DimsFirstArray{2}
Array{T,2} where T
```

Using the shorthand DimsFirstArray{N,T} = Array{T,N}`` is exactly the same as `const DimsFirstArray = Array{T,N} where T where N`.

Doing these kinds of type-parameter swaps used to be more helpful before we got the `Array{<:Any, 2}` shorthand.

**Comment by o314** [comment]
`where` while a good thing has today too much complex part at (show, parse, store ...).
There is a lot of complexity that pops here and there without adding real benefit. it may become a big issue for julia user. The julia user manual for v1.2 has more than 1200 pages ! It's not sustainable.

So i am a strong supporter of this too.
`params` do not have to be orderered.  `fieldnames` aren't. `union` fields aren't too
what matters is how to assign them in regard to any pick aka permutation you need

> julia> (Dict{K, V} where {K, V}){Int}
> Dict{Int64,V} where V
>
> julia> (Dict{K, V} where {V, K}){Int}
> Dict{K,Int64} where K

could be easily replaced by

> julia> `(Dict{K, V} where {K, V}){Int}`
> `Dict{Int64,V} where V`
>
> julia> `(Dict{K, V} where {K, V}){_,Int}`
> `Dict{K,Int64} where K`

if we consider to add `_` binding like KristofferC propose in #29875

I propose to go further and only use one `where` per function signature (no where @ arg) ...

**Comment by StefanKarpinski** [comment]
Field names are ordered. Parameters are also ordered. It's a fundamental property of a parametric type what order it takes its parameters in. I don't see how it could not be. You seem to be proposing a rather radical type system redesign because you don't like the printing of some types.

**Comment by o314** [comment]
may be my words were not clear enough. `params` are defined/passed thru vec. that's work well.
a shortcut with `_` could be even more great.

At the physical design, filelds are implemented via vec so ordered. At the logical one, the interface, they are consumed thru `fieldnames` / `fieldtypes` that isn't ordered.

> you don't like the printing of some types

part of what i don't like comes from that half of the implementation is done thru linked list, half is done thru vec. and that's pop up with pain from times to times.

another thing that is weakening the strength of julia developer and user is the quantity of code dups. method show is at least dupped 5 times here :

- `show(io::IO, ::MIME"text/html", m::Method; kwtype::Union{DataType, Nothing}=nothing)` @ https://github.com/JuliaLang/julia/blob/v1.3.0-rc4/base/methodshow.jl#L326
- `show(io::IO, m::Method; kwtype::Union{DataType, Nothing}=nothing)` @ https://github.com/JuliaLang/julia/blob/v1.3.0-rc4/base/methodshow.jl#L158
- `show(io::IO, ::MIME"text/plain", f::Function)` @ https://github.com/JuliaLang/julia/blob/v1.3.0-rc4/base/show.jl#L21
- `show_tuple_as_call(io::IO, name::Symbol, sig::Type)` @ https://github.com/JuliaLang/julia/blob/v1.3.0-rc4/base/show.jl#L1498
- `jl_static_show_func_sig(JL_STREAM *s, jl_value_t *type)` @ https://github.com/JuliaLang/julia/blob/v1.3.0-rc4/src/rtutils.c#L1094

cons are that

- leads to a partially done approach.
- leads to difficulty while fixing bug.
- leads to difficulty to consume code. where do we plug? combinatorial explosion upcoming.
- in the large, leads to splipping delay, splipping cost too when codebase has 10-100k locs or more.

Not a cosmetics issue. sorry if it's bit abrupt. it's not Julia own problems. I have worked with a lot of venerable legacy system and i'am used to that. V1 is young, first commit already far away. It may already applied.

I have done a lot of code review of Julia internals those day, and believe parametric constraint will be way easer without lost of caps with two patches:

- unchained where @ intra proc
- collected where @ inter proc (still under test, particulary around the double unwrap_unionall at typename/sig in mt)

Not a printing issue. it's only its coming out. That issue may not be the place to discuss all that.

**Comment by laborg** [comment]
`where` prints nicely on 1.6
```julia
julia> Dict{K, V} where {V, K}
Dict{K, V} where {V, K}

julia> Dict{K, V} where {K, V}
Dict

julia> (Dict{K, V} where {V, K}){Int}
Dict{K, Int64} where K

julia> (Dict{K, V} where {K, V}){Int}
Dict{Int64, V} where V
```
and the last case has improved on 1.7
```julia
julia> (Dict{K, V} where {K, V}){Int}
Dict{Int64}
```

**Comment by vtjnash** [comment]
yes, this is done now
