### ISSUE TITLE
Errros while running the test suite on Lunix 18.04

### ISSUE THREAD

**Issue by fremling** [JuliaLang/julia#30211]
Ran the test suite on my Linuz 18.05 mashine.

Some tests did not pass: 780 passed, 1 failed, 0 errored, 0 broken.file: Test Failed at /home/fremling/codes/julia-1.0.2/share/julia/test/file.jl:878
  Expression: download("ba\0d", "good")
    Expected: ArgumentError
      Thrown: Base.IOError
Stacktrace:
 [1] record(::Test.DefaultTestSet, ::Test.Fail) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:745
 [2] (::getfield(Main, Symbol("##42#48")))() at /home/fremling/codes/julia-1.0.2/share/julia/test/runtests.jl:237
 [3] cd(::getfield(Main, Symbol("##42#48")), ::String) at ./file.jl:96
 [4] top-level scope at none:0
 [5] include at ./boot.jl:317 [inlined]
 [6] include_relative(::Module, ::String) at ./loading.jl:1044
 [7] include(::Module, ::String) at ./sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at ./client.jl:231
 [9] _start() at ./client.jl:425

[............]

The global RNG seed was 0x49c671605e005fcd0e08106f23865745.

Error in testset file:
Test Failed at /home/fremling/codes/julia-1.0.2/share/julia/test/file.jl:878
  Expression: download("ba\0d", "good")
    Expected: ArgumentError
      Thrown: Base.IOError
ERROR: LoadError: Test run finished with errors
in expression starting at /home/fremling/codes/julia-1.0.2/share/julia/test/runtests.jl:61
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #runtests#666(::Int64, ::Bool, ::Nothing, ::Function, ::Array{String,1}) at ./util.jl:734
 [3] runtests(::Array{String,1}) at ./util.jl:721 (repeats 2 times)
 [4] top-level scope at none:0

**Comment by StefanKarpinski** [comment]
What are the results of running these commands:
```jl
Sys.which("curl")
Sys.which("wget")
Sys.which("fetch")
```

**Comment by StefanKarpinski** [comment]
This patch might fix the issue:
```diff
diff --git a/base/download.jl b/base/download.jl
index 7ee4a73adb..ebd44f267f 100644
--- a/base/download.jl
+++ b/base/download.jl
@@ -28,8 +28,9 @@ else
         elseif Sys.which("wget") !== nothing
             try
                 run(`wget -O $filename $url`)
-            catch
-                rm(filename, force=true)  # wget always creates a file
+            catch err
+                # wget always creates a file
+                err isa ArgumentError || rm(filename, force=true)
                 rethrow()
             end
         elseif Sys.which("fetch") !== nothing
```

**Comment by fremling** [comment]
Starting from a clean Julia:

    julia> Sys.which("curl")
    
    julia> Sys.which("wget")
    "/usr/bin/wget"
    julia> Sys.which("fetch")
    
    julia> Sys.which("curl") == false
    false
    julia> Sys.which("wget") == true
    false

**Comment by KristofferC** [comment]
This should be fixed now since we always use Downloads.jl so the exception should be consistent.
