### ISSUE TITLE
x.a = 1.0 works when a is UInt64, even though typeof(1.0) != UInt64

### ISSUE THREAD

**Issue by hgeorgako** [JuliaLang/julia#30229]
```julia
mutable struct A
    a::UInt64
end

# works
x = A(1)
x.a = 2

# Works. shouldn't it error out since typeof(1.0) != UInt64
x.a = 1.0
```

versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by JeffBezanson** [comment]
Values are converted when assigned to locations with declared types. See https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#When-is-convert-called?-1 .

**Comment by mbauman** [comment]
This is expected. Please ask this question over at discourse.julialang.org for a more thorough explanation.
