### ISSUE TITLE
UInt(-1) yields an obscure error message

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#30247]
It would be nice if this error was a little less opaque; even something like `DomainError` would be easier to understand than `InexactError: check_top_bit(Int64, -1)`.

```
julia> UInt(-1)
ERROR: InexactError: check_top_bit(Int64, -1)
Stacktrace:
 [1] throw_inexacterror(::Symbol, ::Any, ::Int64) at ./boot.jl:567
 [2] check_top_bit at ./boot.jl:581 [inlined]
 [3] toUInt64 at ./boot.jl:692 [inlined]
 [4] UInt64(::Int64) at ./boot.jl:722
 [5] top-level scope at none:0
```

**Comment by JeffBezanson** [comment]
See also #29766

**Comment by kim366** [comment]
We could catch in the UInt constructor and rethrow; I don't know the performance implications of this, though.

The related code snippets are
https://github.com/JuliaLang/julia/blob/59762368ed7b43288605466556c97b03f09e4671/base/boot.jl#L586
and
https://github.com/JuliaLang/julia/blob/59762368ed7b43288605466556c97b03f09e4671/base/boot.jl#L729
