### ISSUE TITLE
Warning about `uv_fs_lchown` being defined twice

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#30264]
After PR #30046 was merged, in C code including `julia.h`, I am now seeing this warning:
```
In file included from /home/travis/build/gap-system/gap/julia-7920a2a1fb/include/julia/ios.h:7:0,
                 from /home/travis/build/gap-system/gap/julia-7920a2a1fb/include/julia/libsupport.h:13,
                 from /home/travis/build/gap-system/gap/julia-7920a2a1fb/include/julia/julia.h:12,
                 from src/gap.c:54:
/home/travis/build/gap-system/gap/julia-7920a2a1fb/include/julia/uv.h:1472:15: error: redundant redeclaration of ‘uv_fs_lchown’ [-Werror=redundant-decls]
 UV_EXTERN int uv_fs_lchown(uv_loop_t* loop,
               ^
/home/travis/build/gap-system/gap/julia-7920a2a1fb/include/julia/uv.h:1466:15: note: previous declaration of ‘uv_fs_lchown’ was here
 UV_EXTERN int uv_fs_lchown(uv_loop_t* loop,
               ^
```

Indeed, the declaration appears twice in a row. I'd submit a PR to https://github.com/JuliaLang/libuv (assuming that is the right repository?), but I have a hard time figuring out which branch there is relevant -- there are 32 branches on that repository with various unclear names ("382" is my "favorite" ;-) ). The default branch is `julia-uv2`, but that one was last updated in July.

**Comment by fingolfin** [comment]
OK, I remebered that GitHub shows the most recently modified branches on https://github.com/JuliaLang/libuv/branches and thus was able to identify the relevant branch as `julia-uv2-1.24.0`. The problematic commit introducing the duplicate data is https://github.com/JuliaLang/libuv/commit/6e7da5fbc082f62853f470ed884c526c9343ebd4#diff-56343bd7ad8bf449c2693082fb3e4081

I noticed another problem: [this bugfix commit](https://github.com/libuv/libuv/commit/4f43a8673b1e1ae6a5a02c77ee83d2af003b45bb#diff-56343bd7ad8bf449c2693082fb3e4081) is missing in the Julia libuv, compared to the official libuv 1.24.0. That is, I do see the commit in the history, but its changes are reverted by https://github.com/JuliaLang/libuv/commit/6e7da5fbc082f62853f470ed884c526c9343ebd4#diff-56343bd7ad8bf449c2693082fb3e4081

**Comment by fingolfin** [comment]
BTW, I noticed this because it causes our tests for GAP (a computer algebra system, with optional WIP Julia bridge) to fail, as we compile with -Werror by default, and now the code testing Julia integration does not compile. I'll workaround that for now, but it'd be nice to get this resolved here, too.

**Comment by vtjnash** [comment]
None of those are coding errors (your Werror level is too high and is blocking on linting checks), although you can submit a PR to https://github.com/libuv/libuv against the master branch and they'll get fixed.

**Comment by fingolfin** [comment]
The second is actually an ABI breaking bug, but perhaps this is irrelevant inside the Julia ecosystem, I can't judge that, and won't attempt to do so either, as you are far more qualified than me to do so. And as I already said, the other is just a warning that indeed we can easily workaround.

Of course both are essentially trivial issues, but it still worries me that they slipped through the merge or rebase process, and makes me wonder whether other accidental differences compared to baseline libuv were introduced. 

Finally, I'd appreciate if you refrained from telling us which compiler warnings we need or want to enable. This is something you can not possibly judge, nor is it relevant to this discussion.

**Comment by fingolfin** [comment]
And I don't see how submitting a PR to libuv/libuv, as you suggest, would help, as neither issue is present there. Alas, perhaps that was simply a typo in the repository URL?

**Comment by vtjnash** [comment]
They were likely not caught during the merge process since neither is a bug. The second is a bug only with libuv v1 (we use v2). The first really is valid code (albeit unnecessary). You can submit PRs to fix warnings, but in general, you can't expect upstream projects to be warning-free or respond to issues about them. As you say, it can be easily worked around in a variety of ways.

The warnings were brought in via libuv at the link I posted, where it is also present. I double-checked.

**Comment by fingolfin** [comment]
Submitted a PR to https://github.com/JuliaLang/libuv/pull/50 . I would also submit one to upstream libuv, but I don't see either issue in their master branch nor in their 1.24.0 release. I also don't see a v2.x branch there. Since per your comments, you have double checked the issue is present on <https://github.com/libuv/libuv>, I'd appreciate if you could give me a pointer on which branch I need to look. Thanks!

**Comment by fingolfin** [comment]
Ahh, found it -- it's on the libuv master branch, which is annoyingly not the default branch. I'll submit another PR there.
