### ISSUE TITLE
Code coverage nonsensical

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#30273]
I wonder if anyone else has seen really strange reports of code coverage on github?
For instance:
![image](https://user-images.githubusercontent.com/9855832/49482867-b91c2100-f7e5-11e8-9fad-c7571fdb82a1.png)
Clearly it is impossible to get coverage on line 80 without hitting the lines preceding it, yet they are marked as not having been hit.

**Comment by fredrikekre** [comment]
#28192
