### ISSUE TITLE
Kron of transpose/adjoint of sparse matrix with other sparse matrix becomes dense

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#30271]
This is because of the `kron` fallback for `AbstractMatrix` in LinearAlgebra catching the `Transpose{Float64,SparseMatrixCSC{Float64,Int64}}` matrix type.

This is a manifestation of the issue noted here https://github.com/JuliaLang/julia/pull/27586#issuecomment-398242875. I had tried a bunch of different signatures in that PR in order to switch to an abstract type instead of `VecOrMat`, but it caused an ambiguity with the LinearAlgebra method.

Note that this is a regression since 0.6 properly returned a sparse matrix by materializing the transpose/adjoint immediately instead of wrapping.

**Comment by jebej** [comment]
Example for experimentation: `kron(adjoint(sprand(4,4,0.2)), sprand(4,4,0.2))`

**Comment by fredrikekre** [comment]
`kron(copy(adjoint(sprand(4,4,0.2))), sprand(4,4,0.2))` should work (and be equivlent to the 0.6 behavior).

**Comment by jebej** [comment]
> `kron(copy(adjoint(sprand(4,4,0.2))), sprand(4,4,0.2))` should work (and be equivlent to the 0.6 behavior).

Won't this copy unnecessarily if the matrix is dense?

**Comment by fredrikekre** [comment]
No? `copy` is how you materialize an adjoint/transpose wrapped matrix.

**Comment by jebej** [comment]
I guess that `copy` could be done automatically in the `SparseMatrixCSC` constructor, because calling the constructor directly on `Adjoint` or `Transpose` is slow.

**Comment by ViralBShah** [comment]
Anyone want to submit a PR for this one?
