### ISSUE TITLE
tests hang at `Resolving package versions...`.

### ISSUE THREAD

**Issue by epogrebnyak** [JuliaLang/julia#30294]
I'm running tests for a package on a Windows machine and on [Travis](https://travis-ci.org/epogrebnyak/LessOLS.jl) and the test take very long time (5-8 sec on Windows and up to a minute on Travis) hanging at `Resolving package versions...`. Even when I comment out the tests, the delay is very considerable.  

My dependencies are below, I use Julia 1.0. Cross-posted at [Discourse](https://discourse.julialang.org/t/mac-resolving-package-versions-takes-a-long-time/16905/3)

```
name = "LessOLS"
uuid = "3e4c6e70-f926-11e8-0fa5-39915c5a2b72"
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

**Comment by KristofferC** [comment]
From the link it seems that this is just precompilation of dependencies.
