### ISSUE TITLE
Eigen of Symmetric Matrices is 2x slower than NumPy

### ISSUE THREAD

**Issue by massimilianocomin** [JuliaLang/julia#30325]
The following benchmark is self-explanatory

```
using LinearAlgebra
using PyCall
using BenchmarkTools
using StaticArrays
@pyimport numpy.linalg as np


const x = rand(1000, 1000)
const A = x + x'
const B = Symmetric(A)

@btime eigen(A)
@btime np.eigh(A)
@btime eigen(B)
```

On my machine I get 

```
  196.329 ms (15 allocations: 23.25 MiB)
  96.906 ms (155 allocations: 7.64 MiB)
  193.465 ms (15 allocations: 23.25 MiB)
```

I saw on the docs (and it is apparent here) that `eigen` is not optimized for Symmetric matrices (only the eigenvalues are). 
Is there a way to call a better optimized function for Symmetric / Hermitian matrices without having to rely on NumPy/PyCall, which is a bit of a shame since there is a performance loss due to the copying of arrays ?

**Comment by ViralBShah** [comment]
Which blas are you using with numpy?

**Comment by massimilianocomin** [comment]
The output of `np.__config__.show()` is 
```
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/mcomin/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/mcomin/miniconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/mcomin/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/mcomin/miniconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/mcomin/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/mcomin/miniconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/mcomin/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/mcomin/miniconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/mcomin/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/mcomin/miniconda3/include']
```

**Comment by dillondaudert** [comment]
[Arpack.jl](https://github.com/JuliaLinearAlgebra/Arpack.jl) has an optimized method for symmetric matrices, `eigs`. On my machine this is roughly 5x faster than `LinearAlgebra.eigen`.

**Comment by ViralBShah** [comment]
What this is basically saying is that MKL is faster than openblas in this case.

**Comment by ViralBShah** [comment]
@andreasnoack Are we now able to replace OpenBLAS at MKL without having to recompile things?

**Comment by andreasnoack** [comment]
Eigen is optimized for symmetric matrices but MKL has a very optimized symmetric eigensolver. You can get MKL by installing https://github.com/JuliaComputing/MKL.jl but please read the README first.

**Comment by massimilianocomin** [comment]
I am unsure of how `eigs` could be 5x faster than `eigen`, as Lanczos method is not supposed to be faster for full diagonalization (otherwise it would be the default routine for full diagonalization).

By default it computes the 6 first eigenvectors, not the full spectrum.
On my machine, running `eigs` is way slower than `eigen` even for computing less than the half of  the eigenvectors.


MKL is interesting though, but it's not a solution as no sparse eigensolvers will work after installation. So numpy remains the fastest solution for now...

**Comment by dillondaudert** [comment]
Yes, this was my mistake - `eigs` is useful for sparse matrices (symmetric or otherwise).

**Comment by andreasnoack** [comment]
It's because the ARPACK binaries are currently built against OpenBLAS. See https://github.com/JuliaComputing/MKL.jl#caveats.

**Comment by Jutho** [comment]
I was referring to the "**no** sparse eigensolvers"; there are pure Julia alternatives to ARPACK, and they should work with MKL as well. Look for ArnoldiMethod.jl and KrylovKit.jl (the latter is shameless self-promotion).

**Comment by andreasnoack** [comment]
Good points. Many things would indeed be simpler if we just used Julia implementations.

**Comment by massimilianocomin** [comment]
@Jutho Thank you for the alternatives, I will take a look !

**Comment by massimilianocomin** [comment]
UPDATE : In Julia 1.1.0 PyCall is slower... The following code

```
using LinearAlgebra
using PyCall
using BenchmarkTools
np = pyimport("numpy.linalg")


const x = rand(1000, 1000)
const A = x + x'
const B = Symmetric(A)

@btime eigen(A)
@btime np.eigh(A)
@btime eigen(B)
```

now gives 

```
201.860 ms (15 allocations: 23.25 MiB)
  1.779 s (10000103 allocations: 251.78 MiB)
  196.187 ms (15 allocations: 23.25 MiB)
```

Should I also post the issue in the PyCall github ?

**Comment by ViralBShah** [comment]
Yes, do post in PyCall.jl

**Comment by ViralBShah** [comment]
Closing since not a direct Julia issue, but underlying BLAS issue. We may want to have a good way to replace the BLAS we ship with MKL - but maybe should be a separate issue.
