### ISSUE TITLE
put bracket characters in the non-identifier category of characters

### ISSUE THREAD

**Issue by dmitry-v-vlasov** [JuliaLang/julia#30327]
ERROR: LoadError: LoadError: syntax: interpolated variable $j ends with invalid character "⟩"; use "$(j)" instead.
Example: "START smoothing ⟨$i|∂/∂R|$j⟩"
It worked in Julia 0.5

**Comment by JeffBezanson** [comment]
We did this because `⟩` being invalid allows us to add it as available syntax later without breaking code. If it later became a valid identifier character, the meaning of `"$j⟩"` would change. Hence we require parentheses to ensure the code keeps working.

**Comment by StefanKarpinski** [comment]
I do think we could put `⟨` and `⟩` in the "definitely not part of a variable name" category, which would allow interpolation into a string literal like this to work. Unless you think there's some chance that we would make `j⟩` a valid identifier name. You would, of course, still not be able to use the `⟨$i|∂/∂R|$j⟩` syntax as normal Julia code.

**Comment by JeffBezanson** [comment]
Yes, marking those as never-identifier seems reasonable to me. Eventually allowing them as bracket syntax (if they're ever allowed at all) seems like the only sensible path.

**Comment by StefanKarpinski** [comment]
Same goes for all forms of paired brackets.
