### ISSUE TITLE
Travis OSX CI failure due to build log overflow

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#30345]
This seems intermittent; I've seen it before, but here it is again:

https://travis-ci.org/JuliaLang/julia/jobs/466296802

The issue appears to be due to homebrew deciding it must build some of the dependencies from source. Building gcc in verbose mode is just too much for travis which kills the build with "The job exceeded the maximum log length, and has been terminated".

Suspicious log snippet:

```
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.el_capitan.bottle.1.tar.gz^M^M
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.11.6\)\ curl/7.43.0 --fail --silent --location --remote-time --continue-at 0 --output /Users/travis/Library/Caches/H
omebrew/downloads/756ed970bfcfdf378ce6cf57a656b0db918fff502f4d0bcf0d779f22fd5380be--gcc-8.2.0.el_capitan.bottle.1.tar.gz.incomplete https://homebrew.bintray.com/bottles/gcc-8.2.0.el_capitan.bottle.1.tar.gz^M^M
curl: (56) SSLRead() return error -9806^M^M
Error: Failed to download resource "gcc"^M^M
Download failed: https://homebrew.bintray.com/bottles/gcc-8.2.0.el_capitan.bottle.1.tar.gz^M^M
Warning: Bottle installation failed: building from source.^M^M
```

Followed by a huge amount of verbose logging due to the gcc source build, which eventually kills the job.

**Comment by KristofferC** [comment]
Travis building GCC at all is the problem but that should be fixed now.
