### ISSUE TITLE
LLVM error on armv7l

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#30362]
On the newly-created armv7l buildbot (still in testing) I am getting the following error: https://buildog.julialang.org/#/builders/28/builds/5

```
      From worker 4:	Don't know how to custom lower this!
      From worker 4:	UNREACHABLE executed at /buildworker/worker/package_linuxarmv7l/build/deps/srccache/llvm-6.0.1/lib/Target/ARM/ARMISelLowering.cpp:7856!
      From worker 4:	
      From worker 4:	signal (6): Aborted
      From worker 4:	in expression starting at /buildworker/worker/tester_linuxarmv7l/build/share/julia/test/ccall.jl:837
      From worker 4:	unknown function (ip: 0xf6d0ff95)
      From worker 4:	gsignal at /lib/arm-linux-gnueabihf/libc.so.6 (unknown line)
      From worker 4:	unknown function (ip: 0x1)
      From worker 4:	Allocations: 560397257 (Pool: 560338885; Big: 58372); GC: 2923
```

The relevant code in `test/ccall.jl`: https://github.com/JuliaLang/julia/blob/f49cb42fb06492765f6320f3161e8363be5b7ada/test/ccall.jl#L816-L837

I've opened up an interactive shell and gotten the `@code_lowered`, `@code_llvm`, `@code_native`, etc.... and gathered them here: https://gist.github.com/staticfloat/7677743ec0a47905282f615a440be249

**Comment by staticfloat** [comment]
Just updating this to note that the same thing is happening on AArch64: https://buildog.julialang.org/#/builders/47/builds/360/steps/2/logs/stdio

**Comment by ViralBShah** [comment]
Since we do have builds now, I am closing this.

**Comment by staticfloat** [comment]
This seems to have changed behavior a while back, we now just get a segfault without any more information, but it's still happening during the `ccall` test suite.  :(

**Comment by ViralBShah** [comment]
Do we now have an easy way for people to log into an arm machine to diagnose and fix?

**Comment by staticfloat** [comment]
Yes, if someone wants to login and diagnose, I can provide easy SSH access.
