### ISSUE TITLE
inconsistent floatmin for `BigFloat`

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#30387]
This seems inconsistent with the definition of `floatmin` being the smallest non-subnormal value:
```jl
julia> [floatmin(T) == nextfloat(zero(T))/eps(T) for T in (Float16, Float32, Float64, BigFloat)]
4-element Array{Bool,1}:
  true
  true
  true
 false
```
Is this intentional?

Maybe we should define the fallback:
```jl
floatmin(::Type{T}) where {T<:AbstractFloat} = nextfloat(zero(T)) / eps(T)
```
cc @andreasnoack

**Comment by StefanKarpinski** [comment]
This does seem like a bug since `floatmin` is (or should be) defined to give the smallest normal (non-subnormal) floating-point value. The fallback seems good to me although I have to admit it wouldn't have occurred to me to compute it that way :)

**Comment by stevengj** [comment]
Yes, the documentation for `floatmin` defines it as *The smallest in absolute value non-subnormal value representable by the given floating-point DataType T.*

**Comment by stevengj** [comment]
(I noticed this because the correct behavior of `floatmin` is required for the underflow check in #30301.)

**Comment by simonbyrne** [comment]
`BigFloat` doesn't have subnormals, so the current answer is correct according to that definition.

**Comment by StefanKarpinski** [comment]
Aside, but I suppose the definition of subnormal is a number with less than the usual precision, right?

**Comment by simonbyrne** [comment]
Basically, yes.

**Comment by stevengj** [comment]
I see, you're right that `BigFloat` does not seem to have subnormals in the usual sense.  Of course, we could simply redefine `floatmin` to be `nextfloat(zero(T))/eps(T)`; this happens to be what is needed for #30301, but I'm not sure it is justified more generally.

**Comment by sam0410** [comment]
Hi @stevengj, should we redefine `floatmin` for `BigFloat` as well?

**Comment by stevengj** [comment]
Closing as bigfloats don't have subnormals as noted above, so they really are inconsistent.
