### ISSUE TITLE
Consider unblocking blocked user[s]?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#30391]
I only know of one blocked users, but not all the details.

It seems the user is still blocked, and I've thought this from time to time: Maybe this user should be let back in. I'm not sure what the policy is or if there's a time-frame (but it seems it's been a long time, with Julia 1.0 out since and now Julia 1.2 in dev.) This PR just reminded me:

https://github.com/JuliaLang/julia/pull/28761#issue-209353246

**Comment by timholy** [comment]
We already have this. The policy is spelled out [here](https://julialang.org/community/stewards/).
