### ISSUE TITLE
Using MKL with Julia on master causes `fatal error. 

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#30402]
I attempted to build Julia master with MKL and after the build finished without error I tried to startup Julia and got the error 
```
Intel MKL FATAL ERROR: Cannot load libmkl_core.so.
```

Following the same steps but checking out version 1.0.2 worked fine. 

Steps to reproduce (AMD Threadripper CPU with Ubuntu 18.10):
```
git clone https://github.com/JuliaLang/julia.git
cd julia
source /opt/intel/bin/compilevars.sh intel64
echo "USE_INTEL_MKL = 1" > Make.user
make
```
Once the build finished I attempted to do
```
julia/./julia
```
And got the above error.

**Comment by chriselrod** [comment]
I don't think you're likely to get better performance with MKL and an AMD Threadripper. That wasn't the case for large matrices as of a year ago, anyway. It could have changed.

Did you run `source /opt/intel/bin/compilevars.sh intel64` in the tab before starting Julia?
You have to have run the script for Julia to be able to find `libmkl_core.so`.
I simply added `source /opt/intel/bin/compilevars.sh intel64` to my `~/.bashrc`.

**Comment by MasonProtter** [comment]
Correct on both counts, thanks. 

This issue can be closed.
