### ISSUE TITLE
Issue with testing Trig Functions (Periodicity & Double Angle Formula)

### ISSUE THREAD

**Issue by dou10** [JuliaLang/julia#30412]
![double angle sin](https://user-images.githubusercontent.com/17975407/50061632-08a00c80-0157-11e9-8091-d127c7e0ce46.PNG)
Above, I made a formula for the double angle formula for sin. It seems to be rounding one part differently from the other. 
![sin perodicity](https://user-images.githubusercontent.com/17975407/50061636-0dfd5700-0157-11e9-90bf-4b6135f40b07.PNG)
Below is  a function I made for the periodicity of sin. It is rounding differently for the float value.

Since these are properties in trig, should these be equal when evaluated? Even if its comparing float values?

**Comment by yuyichao** [comment]
No.

And more specifically for your examples, for the first one I'm pretty sure you can even find cases where the LHS is not possible to be reproduced by the RHS for any floating point numbers in the right range (might need to involve denormal numbers).

For the second one `1 + 2pi` is already inaccurate. (It doesn't seem that `sinpi` has this garantee either though).
