### ISSUE TITLE
filter(::Function, ::Tuple) is not defined

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#30418]
It should be defined? It would be consistent with the other methods:

```julia
julia> map(x->x+2, (1,2,3))
(3, 4, 5)

julia> filter(iseven, (1,2,3))
ERROR: MethodError: no method matching filter(::typeof(iseven), ::Tuple{Int64,Int64,Int64})
Closest candidates are:
  filter(::Any, ::Array{T,1} where T) at array.jl:2352
  filter(::Any, ::BitArray) at bitarray.jl:1638
  filter(::Any, ::AbstractArray) at array.jl:2313
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> collect(Iterators.filter(iseven, (1,2,3)))
1-element Array{Int64,1}:
 2
```

I get that it's not a type-stable operation except in special cases like `filter(isa(Int), (2,3.0,4))`, but it would still be occasionally convenient.

**Comment by o314** [comment]
Idem with

```julia
filter(BitArray, itr)
filter(Vector{Bool}, itr)
```

patching
```julia
struct Filter{F,I}
    flt::F
    itr::I
end
```
with 

```julia
struct Filter{F<:Function,I}
    flt::F
    itr::I
end
```
can do the trick for my 2 cts.

The problem may be restated: shall the base do it -or- shall it let us do it when needed.

If the compiler handles this issue by catching all the call eg. `filter(s::Any, itr::Any)` is for me, this will lead to both bottleneck and opaque interface/interop at module boundary.

**Comment by o314** [comment]
Have you notice that

```julia
@test tuple(Iterators.filter(isodd, (1, 2, 3, 4, 5))...) == (1,3,5)
Test Passed
```
works ?
