### ISSUE TITLE
sqrt vs ^(1/2)

### ISSUE THREAD

**Issue by ohhmm** [JuliaLang/julia#30424]
implement different functionalities according to words of [El'endia Starman](url
https://math.stackexchange.com/questions/41784/convert-any-number-to-positive-how/41787#comment5776496_41787)

**Comment by ohhmm** [comment]
bug

**Comment by Keno** [comment]
Hi @ohhmm, as @yuyichao indicated, please indicate what the action item is that you want to be resolved and otherwise use discourse.julialang.org for questions. In particular, it would help to have a code snippet of the behavior you consider problematic. The linked stackoverflow question does not seem to answer that question.

**Comment by ohhmm** [comment]
STR:
1) 4^(1/2)

Result expected:
[2,-2]

Result:
2

**Comment by Keno** [comment]
Ah, that's not a bug. Both for efficiency and usability, only the principal root is returned. The same applies to many other multi-valued functions. Julia is a calculational utility, rather than a computer algebra system, which may make different tradeoffs.

**Comment by yuyichao** [comment]
No.

1. Programming language is not math. And following the math definition blindly is almost always a bad idea. There's nothing you cannot do with the current definition but can with yours.
2. Branchcut also exist in math, which is how you give a multi-valued function a single value at each point.

**Comment by ohhmm** [comment]
@Keno, it is bug, because principal root is not ^(1/2). what if ^(1/8)? its just lame rude error guys. I wouldn't make it in brand new purified language. why not use some principal_pow for this purpose?

@yuyichao, what no? 
1. Despite that fact that a programing language may be inconsistent with math, which is I believe not the Julia case, I wouldn't agree that blind following the math is even a tiny bit not good idea.
2. When you power into even values you receive reduction of count of values, and when you power into 1/even values then you receive increasing of values count. I would say this is unignorable part of math. You need support of sets anyway. 

But if you need single expression result only then this is also reachable: https://www.quora.com/profile/Sergej-Krivonos/Posts/Converting-polynomial-to-x-expression-form

**Comment by yuyichao** [comment]
This is a question please use discourse instead.

**Comment by ohhmm** [comment]
no @yuyichao, this is not a question, I have nothing to ask from you
