### ISSUE TITLE
llvmcall(Function*) does not survive precompilation

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#30434]
`Bug.jl`:

```julia
module Bug

# from test/llvmcall.jl
function julia_to_llvm(@nospecialize x)
    isboxed = Ref{UInt8}()
    ccall(:julia_type_to_llvm,Ptr{Cvoid},(Any,Ref{UInt8}),x,isboxed)
end
const AnyTy = julia_to_llvm(Any)

const libllvmcalltest = joinpath(Sys.BINDIR, Base.LIBDIR, "libllvmcalltest")
const the_f = ccall((:MakeIdentityFunction, libllvmcalltest), Ptr{Cvoid}, (Ptr{Cvoid},), AnyTy)

@eval identity(x) = Base.llvmcall($(the_f), Any, Tuple{Any}, x)

end
```

`main.jl`:

```julia
using InteractiveUtils
using Bug

code_warntype(Bug.identity, Tuple{Any})
Bug.identity(nothing)
```

Crashes depending on precompilation:

```
$ JULIA_DEBUG=all JULIA_LOAD_PATH="@::." jj --compiled-modules=no main.jl
Body::Any
1 ─ %1 = Base.llvmcall::Core.Compiler.Const(llvmcall, false)
│   %2 = (%1)(Ptr{Nothing} @0x000056204b539648, Bug.Any, Tuple{Any}, x)::Any
└──      return %2
```

```
$ JULIA_DEBUG=all JULIA_LOAD_PATH="@::." jj test.jl
┌ Debug: Precompiling Bug [top-level]
└ @ Base loading.jl:1186
Body::Any
1 ─ %1 = Base.llvmcall::Core.Compiler.Const(llvmcall, false)
│   %2 = (%1)(Ptr{Nothing} @0x0000000000000000, Bug.Any, Tuple{Any}, x)::Any
└──      return %2
julia: /home/tbesard/Julia/julia-dev/deps/srccache/llvm-6.0.1/include/llvm/Support/Casting.h:106: static bool llvm::isa_impl_cl<llvm::GlobalVariable, const llvm::GlobalValue *>::doit(const From *) [To = llvm::GlobalVariable, From = const llvm::GlobalValue *]: Assertion `Val && "isa<> used on a null pointer"' failed.
```

A `NULL` function handle obviously crashes immediately, so the exact backtrace isn't interesting. Reproduces on both 1.0 and master. Looks like https://github.com/JuliaLang/julia/issues/25041 but the handle really is a literal here.
Ref https://github.com/JuliaGPU/CUDAnative.jl/pull/303

**Comment by vtjnash** [comment]
Yes, this is what https://github.com/vtjnash/julep/wiki/0002:-Enhanced-llvmcall is intended to fix (note that it's the first item on the list of primary issues with the current design), and also might help #25984 get moving again

**Comment by maleadt** [comment]
Uh, of course, not sure what I was thinking. Would it make sense to prevent precompilation of methods with `llvmcall`, in the meantime?

**Comment by maleadt** [comment]
It looks like this function, `identity`, which uses `llvmcall`, isn't even precompiled. The function isn't called when loading the module, dumping compile commands shows it isn't compiled, and adding a `jl_` call to `jl_save_incremental`->`jl_serialize_value` shows that only `julia_to_llvm` is serialized to the precompile cache. How, then, does the IR for `identity` end up with an null pointer as argument to `llvmcall`? Shouldn't that code get generated when the method is called (ie. not part of precompilation)? The `llvmcall` doesn't need to be statically compiled here.

Furthermore, other uses of `llvmcall` in CUDAnative that similarly are part of methods that are not precompiled work just fine. Could you explain what's happening here?

**Comment by maleadt** [comment]
My original MWE was oversimplified. I'm actually doing something like:

```julia
module Bug

function julia_to_llvm(@nospecialize x)
    isboxed = Ref{UInt8}()
    ccall(:julia_type_to_llvm,Ptr{Cvoid},(Any,Ref{UInt8}),x,isboxed)
end

@generated function indirect_llvmcall()
    AnyTy = julia_to_llvm(Any)
    the_f = ccall((:MakeIdentityFunction, "usr/lib/libllvmcalltest"), Ptr{Cvoid},
                  (Ptr{Cvoid},), AnyTy)
    quote
        Base.@_inline_meta
        Base.llvmcall($the_f, Any, Tuple{Any}, nothing)
    end
end
test() = indirect_llvmcall()

end
```

Which works, because the `Function*` is looked up as part of the `@generated` function, so it isn't precompiled. However, during some unrelated other change I introduced a global call to `return_types`, which now causes the function containing the `llvmcall` to be precompiled:

```julia
module Bug
...
Base.return_types(test, Tuple{})
...
end
```

So I can work around this limitation by not calling `return_types`.
