### ISSUE TITLE
change println to printline

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#30454]
given `readline`, and julia's general inclination to not abbreviate excessively, would it make sense to change `println` to `printline`?  something to think about for 2.0.  could even add the latter earlier and just not deprecate the former until 2.0.  see https://github.com/JuliaLang/julia/issues/2551 for previous discussion.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/2553#issuecomment-14811772

Thanks for the suggestion but this will realistically not happen.
