### ISSUE TITLE
BoundsError on master but works fine on 1.0.3 (and previous)

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#30462]
A test with nightly builds of GMT.jl package started to fail since about two days ago (18 December). All tests pass with version 1.0.3 but one of them now fails in master. See
https://travis-ci.org/GenericMappingTools/GMT.jl/builds/470272490?utm_source=github_status&utm_medium=notification
The [failure ](https://travis-ci.org/GenericMappingTools/GMT.jl/jobs/470272492#L3122) is about accessing an array out of bounds but the same code has been working with no problem till 2 days ago and still works fine with 1.0.3
```
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_PKGDIR = c:\j\.julia
```

**Comment by tkoolen** [comment]
So it's the `minimum` call on this line: https://github.com/GenericMappingTools/GMT.jl/blob/76956f441b137f4f610058c7ac9bd81f1f715883/src/gmt_main.jl#L1690.

https://github.com/JuliaLang/julia/pull/30320 / https://github.com/JuliaLang/julia/pull/30436 / https://github.com/JuliaLang/julia/pull/30441?

**Comment by KristofferC** [comment]
cc @jw3126

**Comment by joa-quim** [comment]
Hmm don't know. It looks like a very likely candidate but I manually forced relaunching the failing CI job and it still fails for the same reason. #30441 was merged 14 hours ago (at time of this writing ofc) so it should have been used in this run, right?
```
$ julia --color=yes -e "VERSION >= v\"0.7.0-DEV.3630\" && using InteractiveUtils; versioninfo()"
Julia Version 1.2.0-DEV.42
Commit 258e08a605 (2018-12-20 07:34 UTC)
```

**Comment by KristofferC** [comment]
Yep, here is a MWE:

```
➜  julia git:(master) ✗ ./julia --check-bounds=yes -q
julia> a = rand(128, 128);

julia> minimum(a)
ERROR: BoundsError: attempt to access 128×128 Array{Float64,2} at index [16385]
```
