### ISSUE TITLE
How to create a fortran shared library that uses BLAS and LAPACK

### ISSUE THREAD

**Issue by vincentcp** [JuliaLang/julia#30463]
How to create a fortran shared library that uses BLAS and LAPACK (preferably platform-independent)?

I want to use the Fortran functions in band_qr.f90 in a julia. The page [https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/index.html](url) proposes to use the options -shared and -fPIC; but I do not know how to indicate what LAPACK or BLAS library to use. 

First I tried
`gfortran band_qr.f90 -shared -fPIC  -llapack -lblas -o libbandqr.dylib`

leading to a segmentation fault when I try to execute the fortran functions from Julia with ccall.
Probably, because julia does not use the LAPACK/BLAS libraries in de /usr/lib folder.

I would like to use the same shared libraries as Julia uses in LinearAlgebra.jl; but I do not find the right way to do this. 

Or is it safer to create my own library which contains all the necessary functions needed from LAPACK and BLAS.

**Comment by ararslan** [comment]
Please use [Discourse](https://discourse.julialang.org) for questions; we use GitHub issues for bug reports and feature requests. Thanks!
