### ISSUE TITLE
Source code for julia/contrib/windows/7zS.sfx missing

### ISSUE THREAD

**Issue by cdluminate** [JuliaLang/julia#30475]
I'm afraid there isn't source code for `7zS.sfx` in julia's source tarball. Missing source code violates Debian's free software guideline, and we (Debian) will remove `7zS.sfx` from the source tarball being distributed by Debian itself[1].

Is source code for `7zS.sfx` available?

Sorry if I opened a stupid issue, but I'm really not familiar with any windows-related file.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916957

**Comment by musm** [comment]
Seems to be fixed according to the last message in  the linked thread https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916957 ?

**Comment by vtjnash** [comment]
Only in their out-of-tree fork. Note that the source for this file is contained in the original commit message: 21e12c49935dd1863a966c1cdb0b1371cc1a3789.

**Comment by musm** [comment]
someone should reopen this issue since it's not fixed

**Comment by vtjnash** [comment]
Or just merge https://github.com/JuliaLang/julia/pull/33302?

**Comment by musm** [comment]
Right, my only concern with that PR is that NSIS doesn't use lzma2 so the compression and decompression speeds area  bit worse. My laptop is very old so I can notice the difference, but perhaps it doesn't matter that much or we dont' care?

**Comment by musm** [comment]
Although I do think the current method is pretty round-about and it would be very nice to simplify the build process  by merging  #33302

**Comment by musm** [comment]
Ideally we should just switch to inno setup, it's far more robust and easier and more modern.

They only question is how to run it in the makefile, I think can only be run on windows?

**Comment by staticfloat** [comment]
As noted on Slack, our windows buildbots are actually running windows, so that's no problem.
