### ISSUE TITLE
--output-o executes with incorrect BINDIR + STDLIB  

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#30479]
```julia
run(`julia --output-o sys-o.a -J /usr/local/julia/lib/julia/sys.so -e 'Base.reinit_stdio(); Base.init_load_path();Base.init_depot_path(); println(Base.LOAD_PATH); using Pkg'`)
```
the `output-o` messes with the load path, since not everything is initialized yet. This is known, which is fixed by inserting a `Base.init_load_path()`. This works fine most of the time, but I run into a peculiar failure when trying it in a docker environment in nextjournal:
https://nextjournal.com/sdanisch/pkg_scompile_debug
You can edit the article if you want to debug it (sign up julia1.0).
Or just tell me some things I could check - I'm a bit out of ideas, what else could go wrong here! 
I'm guessing there needs to be something else initialized, which is only relevant on some platforms.

The Julia version is the same as what I use locally (1.0.2), julia is started normally as can be seen by `Base.julia_cmd()`, as far as I know we don't mess with any of the paths & package repositories and the load path is the same as locally (`["@", "@v#.#", "@stdlib"]`).

Thanks for any help :)

**Comment by fredrikekre** [comment]
What is the expanded load path, i.e. the output of `Base.load_path()`?

**Comment by SimonDanisch** [comment]
I see, that looks highly suspicious:
```Julia
["/root/.julia/environments/v1.0/Project.toml", "/buildworker/worker/package_linux64/build/usr/bin/../share/julia/stdlib/v1.0"]
```

**Comment by SimonDanisch** [comment]
Hm, I'd have thought this fixes it, but it still can't find it:
```julia
run(`julia --output-o sys-o.a -J /usr/local/julia/lib/julia/sys.so -e 'Base.reinit_stdio(); Base.init_load_path();Base.init_depot_path(); pop!(LOAD_PATH); push!(LOAD_PATH, (Sys.BINDIR * "/../share/julia/stdlib/v1.0")); using Pkg'`)
```
I double checked, that `(Sys.BINDIR * "/../share/julia/stdlib/v1.0")` contains the folder Pkg

**Comment by SimonDanisch** [comment]
Ooooh, what? `Sys.BINDIR = /buildworker/worker/package_linux64/build/usr/bin` if I run it with `--output-o` :-O

**Comment by SimonDanisch** [comment]
Ok, so this works:
```Julia
run(`julia --output-o sys-o.a -J /usr/local/julia/lib/julia/sys.so -e 'Base.reinit_stdio(); @eval(Sys, BINDIR = "/usr/local/julia/bin");@eval(Sys, STDLIB = "/usr/local/julia/share/julia/stdlib/v1.0"); Base.init_load_path(); Base.init_depot_path(); println(Base.load_path()); using Pkg'`)
```

**Comment by SimonDanisch** [comment]
Okay, this is because `Sys.__init__()` doesn't get called, because of: https://github.com/JuliaLang/julia/issues/22910
