### ISSUE TITLE
`signed(x)` and `unsigned(x)` should agree on whether they'll only reinterpret the standard BitInt types.

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#30473]
Branching this Issue off of the conversation here: https://github.com/JuliaLang/julia/pull/30445#discussion_r243427894

----------------------
Reproducing it in this Issue:

> Also, I wanted to ask: Does anyone know why `signed` takes `x::Unsigned`, but `unsigned` takes `x::BitSigned`? I'm _guessing_ it's to prevent `BigInt` from falling under the `reinterpret` implementation. I'm currently just copying that in the `::Type{T}` definitions -- does that seem reasonable?

--------------

> yes -- the set difference is the presence/absence of `BigInt`
> also Signed is an abstract type, BitSigned is a Union (in this context it is immaterial pbly).

--------------

> Now that you mention it, it is a little weird, because there's nothing about the docstring for `Unsigned` that specifies it needs to be `isprimitivetype`. Nothing stops me from defining
> 
> ```julia
> struct WeirdUnsigned <: Unsigned
>     msg::String
>     val::UInt16
> end
> WeirdUnsigned(x::Int) = WeirdUnsigned("missing", UInt16(x))
> Base.Signed(x::WeirdUnsigned) = signed(x.val)
> 
> julia> signed(WeirdUnsigned(4))
> ERROR: bitcast: expected primitive type value for second argument
> Stacktrace:
>  [1] reinterpret at ./essentials.jl:381 [inlined]
>  [2] signed(::WeirdUnsigned) at ./int.jl:162
>  [3] top-level scope at none:0
> ```
> 
> Of course this isn't a catastrophe: the error is sensible and one could always provide a more specialized definition. (If it returned a borked answer, that would be a genuine problem.) But of course the same could be said of `Signed`, and `reinterpret(UInt, BigInt(4))` throws the same error.

--------------

> Yeah, that's exactly the sort of thing I was referring to. Thanks for including an example.
> 
> > Of course this isn't a catastrophe: the error is sensible and one could always provide a more specialized definition. (If it returned a borked answer, that would be a genuine problem.) But of course the same could be said of `Signed`, and `reinterpret(UInt, BigInt(4))` throws the same error.
> 
> Totally, I agree. But I think that it's the inconsistency with `unsigned()` that's a little weird. I think _either_ we should change this to also accept only `BitUnsigned`, so that you'd get the correct behavior above, _OR_ we should loosen `unsigned()` to accept any kind of `Signed`, and just add an extra overload for `BigInt`, exactly as you'd have to do for `WeirdUnsigned` above. Does that seem reasonable to you?

**Comment by NHDaly** [comment]
Here are the lines in question:

https://github.com/JuliaLang/julia/blob/8b1bf4cd9c2f2585ae3d984310c0e1a608457d85/base/int.jl#L140
https://github.com/JuliaLang/julia/blob/8b1bf4cd9c2f2585ae3d984310c0e1a608457d85/base/int.jl#L161

https://github.com/JuliaLang/julia/blob/8b1bf4cd9c2f2585ae3d984310c0e1a608457d85/base/int.jl#L162
https://github.com/JuliaLang/julia/blob/8b1bf4cd9c2f2585ae3d984310c0e1a608457d85/base/int.jl#L170

-------------

It seems to me that we should probably loosen `unsigned` to accept any kind of `Signed` (and add a specific overload for `BigInt`), in order to minimize the amount of work to add a new Integer type.


-----


For example, currently the [BitIntegers.jl](https://github.com/rfourquet/BitIntegers.jl) package has to duplicate the definition of `unsigned(x::T)` for any new type it defines, despite already defining `convert(Unsigned, x)`. It doesn't need to do that for `signed(x)` because that function is looser in what it accepts.

This is where it defines the types and `convert`:
https://github.com/rfourquet/BitIntegers.jl/blob/219681ecf2595754f88426a9d2f2fe5cd843d31a/src/BitIntegers.jl#L53-L57

And here, it has to redefine `unsigned(x)`:
https://github.com/rfourquet/BitIntegers.jl/blob/219681ecf2595754f88426a9d2f2fe5cd843d31a/src/BitIntegers.jl#L134

And indeed, it gets `signed` for free: 
```julia
julia> @which signed(BitIntegers.UInt256(3))
>> signed(x::Unsigned) in Base at int.jl:162
```

**Comment by NHDaly** [comment]
CC: @timholy 

Adding you to the discussion here since I branched it off our other conversation. :)

**Comment by JeffreySarnoff** [comment]
This issue affected the type design and type-driven logic of 'SaferIntegers.jl' and the alternate approach necessitated to obviate this issue precludes elegance that is evermoreso Julia.

**Comment by JeffreySarnoff** [comment]
This issue affected the type design and type-driven logic of 'SaferIntegers.jl' and the alternate approach necessitated to obviate this issue precludes elegance that is evermoreso Julia.

**Comment by JeffreySarnoff** [comment]
@NHDaly lets make this sound take on things a formal PR  so we can step forward.  I am happy to write it -- would you mind re-reviewing the relevant parts of Base and its Tests and locate + show/link lines that would change + note why + show how you would change them to comport with our (@NHDaly , @rfourquet , @timholy , @JeffreySarnoff ) shared understanding of the proper way to design this smattering of subtype algebra.  After a few days for comments, if any -- I'll PR-ify it with rationale and link to this and link to https://github.com/JuliaLang/julia/pull/30445#discussion_r243014703.

**Comment by JeffreySarnoff** [comment]
[ Hi Tim, let the other @timholy pings from me go ]
if this were about trading Baseball cards -- here's Mickey Mantle:
> How do we do this non-breaking-ly?

**Comment by NHDaly** [comment]
Hi @JeffreySarnoff. To be honest, i don't remember enough of the details to say, but after thinking this through again, i think the correct solution is to make these symmetric by restricting both `reinterpret` implementations to only apply for `Base.BitInteger` types:

```julia
 signed(x) = convert(Signed, x) 
 signed(x::BitUnsigned) = reinterpret(typeof(convert(Signed, zero(x))), x) 
 unsigned(x) = convert(Unsigned, x) 
 unsigned(x::BitSigned) = reinterpret(typeof(convert(Unsigned, zero(x))), x) 
```

The extra `reinterpret` overloads are simply a performance optimization, since without them the default `convert` method would still call the correct constructors. But the reinterpret is faster:
```julia
julia> @btime map(x->convert(Unsigned, x), a)   setup=(a=rand(1:100, 1000));
  817.235 ns (2 allocations: 7.95 KiB)

julia> @btime map(x->unsigned(x), a)            setup=(a=rand(1:100, 1000));
  648.462 ns (2 allocations: 7.95 KiB)
```

But the `reinterpret` would not necessarily be correct for _any_ subtype of `Unsigned` or `Signed`, because it makes specific assumptions about the bit-layouts. So for this reason, it should be explicitly restricted to the Base types.

This would also be sufficient to make the types symmetric, which I think satisfies your original concerns! :)

What do you think?

**Comment by NHDaly** [comment]
To be clear, it would just be applying this diff:

````diff
diff --git a/base/int.jl b/base/int.jl
index c5274e40a6..3f6dae35e0 100644
--- a/base/int.jl
+++ b/base/int.jl
@@ -137,9 +137,6 @@ abs(x::Signed) = flipsign(x,x)

 ~(n::Integer) = -n-1

-unsigned(x::BitSigned) = reinterpret(typeof(convert(Unsigned, zero(x))), x)
-unsigned(x::Bool) = convert(Unsigned, x)
-
 """
     unsigned(x) -> Unsigned

@@ -159,7 +156,7 @@ julia> signed(unsigned(-2))
 ```
 """
 unsigned(x) = convert(Unsigned, x)
-signed(x::Unsigned) = reinterpret(typeof(convert(Signed, zero(x))), x)
+unsigned(x::BitSigned) = reinterpret(typeof(convert(Unsigned, zero(x))), x)

 """
     signed(x)
@@ -168,6 +165,7 @@ Convert a number to a signed integer. If the argument is unsigned, it is reinter
 signed without checking for overflow.
 """
 signed(x) = convert(Signed, x)
+signed(x::BitUnsigned) = reinterpret(typeof(convert(Signed, zero(x))), x)

 div(x::BitSigned, y::Unsigned) = flipsign(signed(div(unsigned(abs(x)), y)), x)
 div(x::Unsigned, y::BitSigned) = unsigned(flipsign(signed(div(x, unsigned(abs(y)))), y))
````

(Note that I deleted the extra method for `unsigned(x::Bool)` because that's already covered by the other two cases, since `(Bool <: Base.BitSigned) == false`)
