### ISSUE TITLE
A typo in i18n_data when testing DelimitedFiles. not "한민국" but "대한민국"

### ISSUE THREAD

**Issue by petershintech** [JuliaLang/julia#30486]
While reading tests for DelimitedFiles, I found the following typo.

Line 209 and 210 of julia/stdlib/DelimitedFiles/test/runtests.jl:
"Rep. of Korea", "AHN Sung-Gi", "한민국", "안성기",
"Rep. of Korea", "SHIM Eun-Ha", "한민국", "심은하",

The official country name of Rep. of Korea Korea is:
"대한민국" not "한민국"

**Comment by StefanKarpinski** [comment]
Care to make a PR to fix it?

**Comment by fredrikekre** [comment]
#30567
