### ISSUE TITLE
Typo of issue reference in `doc/make.jl`

### ISSUE THREAD

**Issue by d4n1elchen** [JuliaLang/julia#30489]
In the `doc/make.jl`, there is a code block for making links for stdlib. It mentioned JuliaDocs/Documenter.jl#522 in the comment but JuliaDocs/Documenter.jl#522 seems not relevant to this. Should it be JuliaDocs/Documenter.jl#552? If it is considered to be a typo, I'll make a PR for this.

**Comment by fredrikekre** [comment]
Yes that seems right, its not very important since it is just a comment, but if you wanna make a PR then great!
