### ISSUE TITLE
Julia pdf manual overfull

### ISSUE THREAD

**Issue by shabmk** [JuliaLang/julia#30491]
From https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.2.0-DEV.pdf page 18.

![](http://oi67.tinypic.com/2cd95on.jpg)

In any case, it's awesome that now there's a pdf manual. Great work.

**Comment by fredrikekre** [comment]
Can you reopen this issue at https://github.com/JuliaDocs/Documenter.jl? Thanks!

**Comment by shabmk** [comment]
Of course, reopened there.
Issue number 920 at Documenter.jl repository.
