### ISSUE TITLE
Code for faster factorial (and gamma); in general issue of optimizing "between"

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#30493]
I made a PR #30665, that's also better on Julia 1.2. "between" logic is handled in Julia 1.2 better and the same code works in 0.5 (not as optimized but still better than before).

I'll let the original stand here, even with the error (see below):

I can make a PR for the factorial, it seems with this change it should be faster (at least on my very old laptop; I don't trust the optimizer to do better on latest chips with the original code):

```
@inline function factorial_lookup(n::Integer, table, lim)
    if n & 15 == 0  # equiv.:  if 0 <= n < 16  neither does:  if 0 <= n & n < 16  get me same assembly
        @inbounds f = table[n]
        return oftype(n, f)
    end
    return factorial_lookup_helper(n, table, lim)   # currently same as function I'm replacing
end
```

before this change I get three branches before the common case, the look-up from the table. Now I get one:

```
I originally had @code_native factorial_lookup(15, _fact_table128, 32) here, that's more verbose, and I've not investigated why.

julia> @code_native factorial_lookup(15, _fact_table64, 32)
	.text
Filename: REPL[349]
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 2
	testb	$15, %dil
	je	L24         # is it better to branch to the common case? Seems optimizer thinks it less common, can I change its mind?
Source line: 6
	movabsq	$factorial_lookup_helper, %rax
	callq	*%rax
	popq	%rbp
	retq
Source line: 3
L24:
	movq	(%rsi), %rax
	movq	-8(%rax,%rdi,8), %rax
Source line: 4
	popq	%rbp
	retq
	nopw	%cs:(%rax,%rax)
```

the "if n & 15 == 0" isn't exactly the range I need to check, the fallback catches the higher values, or at least one of the tables could be extended and e.g. "if n & 64 == 0" used.

I'm guessing no compiler would have figured this out from the original source, but shouldn't LLVM do it from "if 0 <= n < 16" when given a convenient range?

Is this the type of optimization we want for factorial, or for Julia in general? I'm not sure the factorial case is too important (and e.g. to inline it). I'm thinking more in general and should code be written for readability to check for error conditions first (almost) tying the hand of the optimizer?

Can anyone check this for me in Julia 1.0.3, or better yet, 1.1 or master (code_native and speed vs stdlib factorial)?

The source below, is the one from master, while I renamed and added: @outline to that function:

```
const _fact_table64 = Vector{Int64}(undef, 20)
_fact_table64[1] = 1
for n in 2:20
    _fact_table64[n] = _fact_table64[n-1] * n
end

const _fact_table128 = Vector{UInt128}(undef, 34)
_fact_table128[1] = 1
for n in 2:34
    _fact_table128[n] = _fact_table128[n-1] * n
end

@noinline function factorial_lookup_helper(n::Integer, table, lim)
    n < 0 && throw(DomainError(n, "`n` must not be negative."))
    n > lim && throw(OverflowError(string(n, " is too large to look up in the table")))
    n == 0 && return one(n)  #what's the point of this line?
    @inbounds f = table[n]
    return oftype(n, f)
end

factorial(n::Int128) = factorial_lookup(n, _fact_table128, 33)
factorial(n::UInt128) = factorial_lookup(n, _fact_table128, 34)
factorial(n::Union{Int64,UInt64}) = factorial_lookup(n, _fact_table64, 20)
```

What's the point of ```n*n``` in typeof(n*n) there?
```
function factorial(n::Integer)
    n < 0 && throw(DomainError(n, "`n` must be nonnegative."))
    f::typeof(n*n) = 1
    for i::typeof(n*n) = 2:n
        f *= i
    end
    return f
end
```

**Comment by PallHaraldsson** [comment]
Thanks, yes I'm getting rusty and flipped this around in my head.

However, it seems I can just do (at least on Julia 1.2-dev):

```
@inline function factorial_lookup(n::Integer, table, lim)
           if !(0 <= n < 16)
               factorial_lookup_helper(n, table, lim)
           else
               @inbounds f = table[n]
               return oftype(n, f)
           end
       end
```

On Julia @outline is gone, it seemed like a synonym for the better name @noinline; I changed my example at the top, but only for that.

**Comment by KristofferC** [comment]
It's quite unclear what this issue is about. If it is just about performance of `factorial`, counting branches is likely not that useful since that is unlikely to be a bottleneck in any real code.
