### ISSUE TITLE
No longer available? https://docs.julialang.org/en/stable/

### ISSUE THREAD

**Issue by petershintech** [JuliaLang/julia#30524]
I can see the Julia documentation website does not support the following link any more.

https://docs.julialang.org/en/stable/

The omission leaves many links from 3rd party packages to Julia documents broken.
Any reason for the omission? Should we replace all the links with e.g. https://docs.julialang.org/en/v1/?

**Comment by fredrikekre** [comment]
> Should we replace all the links with e.g. https://docs.julialang.org/en/v1/?

Yes, or simply https://docs.julialang.org.
