### ISSUE TITLE
how to protect julia code source ?we don't want to public our code source

### ISSUE THREAD

**Issue by 564064202** [JuliaLang/julia#30530]
how to protect julia code source ?we don't want to public our code source

**Comment by ararslan** [comment]
Hi @564064202, glad you're using Julia! We reserve the GitHub issue tracker for bug reports and feature requests, so I'm going to close this. For questions, please use https://discourse.julialang.org. I recommend including a bit more information in your question.

**Comment by 564064202** [comment]
@ararslan I see.**But we just wan't you to know Intellectual property is every import**.So,julia should have this function

**Comment by PallHaraldsson** [comment]
See PackageCompiler.jl and e.g. Medium article on it from Jan 2 2017.
