### ISSUE TITLE
Travis linux 1.1 CI failure due to gzip error

### ISSUE THREAD

**Issue by antimon2** [JuliaLang/julia#30555]
I tried to build my package with Julia v1.1 on Travis-CI linux, but a build-error occurred:

> gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command "curl -A "$CURL_USER_AGENT" -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1-latest-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -" failed and exited with 2 during .
> 
> Your build has been stopped.

ref: https://travis-ci.org/antimon2/QDates.jl/jobs/474272290

The command works on my local (ubuntu on vagrant).

What's happened? Or what should I do?

**Comment by anders-dc** [comment]
Same problem for me on [Travis with Granular.jl](https://travis-ci.org/anders-dc/Granular.jl/builds/474335350).

**Comment by ararslan** [comment]
I ran into the same thing with the FreeBSD binaries on Cirrus CI. The weird thing is that both the Linux and FreeBSD binaries work fine for me locally; no `gzip` errors.

**Comment by anders-dc** [comment]
> Same problem for me on [Travis with Granular.jl](https://travis-ci.org/anders-dc/Granular.jl/builds/474335350).

I think it may have been a temporary glitch with the download link. When [restarting the previously failing build](https://travis-ci.org/anders-dc/Granular.jl/jobs/474335353), the run now completes successfully.

**Comment by anders-dc** [comment]
> Same problem for me on [Travis with Granular.jl](https://travis-ci.org/anders-dc/Granular.jl/builds/474335350).

I think it may have been a temporary glitch with the download link. When [restarting the previously failing build](https://travis-ci.org/anders-dc/Granular.jl/jobs/474335353), the run now completes successfully.

**Comment by antimon2** [comment]
> I think it may have been a temporary glitch with the download link.

I restarted the [failed job](https://travis-ci.org/antimon2/QDates.jl/jobs/474272290) in the last hour, and it completed successfully.

If I fall on a similar error, I will try again and again after a while. Thanks.
