### ISSUE TITLE
`@inbounds` pessimizes closure

### ISSUE THREAD

**Issue by affans** [JuliaLang/julia#30563]
Consider the following function. Add `@inbounds` to this line to trrigger it
```
function bar()
       x=[2]
       for i in 1:10_000 #Add @inbounds to this line to trrigger it
       (m->2i)(x)
       end
 end
```
@oxinabox also found the bug is triggered with `@sync` and `@time` as well.

**Comment by oxinabox** [comment]
For record keeping purposes @simonbyrne  noticed this as a special case of 
https://github.com/JuliaLang/julia/issues/15276
