### ISSUE TITLE
Support alternative OSes, e.g. Haiku

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#30586]
I have one to three in mind:

a) Haiku (is a BeOS clone, i.e. not Linux based).
b) ReactOS (a clone of Windows NT) is another.
c) RISC OS (probably not going to happen... nostalgia). Python did support. $ as directory separator may be a problem... and lots more.

Would e.g. supporting a) be too difficult? What in general would be needed?

I see as of OpenBLAS 0.3.3 (what we're using), Haiku support was added.

We would need to add IsHaiku() etc. (IsBeOS() more appropriate?) and more dependencies would need to compile.

Since these, i.e. Perl (so I assume PCRE2) work, it's a good sign:
https://www.haiku-os.org/about/faq/#is-there-python-ruby-perl

I looked into Libuv WIP:
https://github.com/haikuports/haikuports/pull/1849/files

[Since Keno is working on Julia without needing libuv (done?), that might also be an option, while you would I guess want support with.]

For ReactOS, since it's a Windows clone, it should just work, without any changes (and IsReactOS() not needed/wanted?). However at some point it only had FAT (no NTFS) support. Maybe Julia on Windows requires NTFS? Maybe it's there now, while anyway they now have [Win]BTRFS support. It would be interesting to know of ReactOS (or even regular Windows) works, with or without it:

https://github.com/maharmstone/btrfs

**Comment by StefanKarpinski** [comment]
> Since these, i.e. Perl (so I assume PCRE2) work

Perl does not use PCRE2, afaik—the point of PCRE is to emulate what Perl does natively.

> Would e.g. supporting a) be too difficult? What in general would be needed?

Pretty hard to know in advance. The only way to find out is to clone Julia on one of these systems and try building it. I'm not sure if we need an issue open for this. If someone wants Julia on one of these systems, they should try it and see what happens. If there are changes required to support them, they can make PRs which can be included if they don't break other builds. Of course, keeping these builds working would be an uphill struggle without CI to make sure they don't work.

**Comment by ViralBShah** [comment]
This is better suited for discourse. I don't think this is the right place to bring up these platforms - since it is unlikely that Julia dependencies work and even if they do, we need someone to contribute fixes and maintain them.
