### ISSUE TITLE
rest(itr) does not give the rest of itr

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#30629]
https://github.com/JuliaLang/julia/blob/dffe119421157e4d55caf78801bb15b45b020e5d/base/iterators.jl#L465

One may assume that first/rest work like car/cdr in lisp, however currently `rest(itr)=itr` so we have `first(itr) === first(rest(itr))` which may be confusing. Since this is not documented and `rest(itr)` is not doing anything (so probably nobody is using it right now), can we change it to `rest(itr)=peel(itr)[2]` ?

**Comment by StefanKarpinski** [comment]
This seems incorrect... @JeffBezanson?

**Comment by JeffBezanson** [comment]
The purpose of `Iterators.rest` is to give an iterator starting at a given state, not to drop 1 (or any particular number) of elements. Prior to 0.7 it only had the signature `rest(itr, state)`. The 1 argument method seems to have been added as part of the new iteration protocol (1a1d6b6d1c636a822cf2da371dc41a5752e8c848). I don't know why, but I guess it's related to `iterate(...)`, where dropping the second argument uses the initial state.

**Comment by Keno** [comment]
Yes, it's for consistency with iterate. If there's no state the `rest` is the entire iterator.

**Comment by denizyuret** [comment]
OK, I can see the current definition is more consistent with the
description. What do you guys do when you need a command that plays the
role of `cdr` for iterators?  Use `peel`?

**Comment by JeffBezanson** [comment]
I use `drop`.

**Comment by denizyuret** [comment]
Doesn't that get slower the deeper you get into the iterator? Drop does not seem to keep state, just the original iterator and n, drop(drop(itr)) increases n, and iterate(::Drop) starts counting from the beginning every time.

**Comment by JeffBezanson** [comment]
Yes of course; if you need to drop incrementally then you use `peel`.

**Comment by denizyuret** [comment]
Sounds good.
