### ISSUE TITLE
In iterators.jl:1092 and 1095 Stateful{T,VS} is reversed to {VS,T}

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#30643]
https://github.com/JuliaLang/julia/blob/34f7a4a50458594e6d72793b4f371227e8e842e3/base/iterators.jl#L1092

e.g. Stateful(cycle(itr)) claims it has length.

**Comment by JeffBezanson** [comment]
Wow, thank you. Good catch. Could you prepare a PR?
