### ISSUE TITLE
Export Base.nonmissingtype

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#30657]
It would be nice to have this name documented and exported. It should be used often in stats packages.

The old way with `Missings.T` is not as descriptive.

**Comment by nalimilan** [comment]
It's not exported because we hoped to offer something more general, like `Core.Compiler.typesubtract(T, Missing)`. But I don't remember what as the problem (except that `Core.Compiler.typesubtract` cannot be used directly since it's not specialized on purpose -- but another method can be exported).

**Comment by galenlynch** [comment]
The function `union_poptype` in #30549 Is more general (along the lines of `typesubstract`), and type stable.

**Comment by juliohm** [comment]
There are plans to export the name in the next minor release of the language?

**Comment by nalimilan** [comment]
Maybe make a PR and see how it's received.
