### ISSUE TITLE
Enum should be a scalar for broadcast

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#30669]
It seems like we need a definition
```
broadcastable(x::Enum) = Ref(x)
```
like the ones [here](https://github.com/JuliaLang/julia/blob/428eb0a07121249a8ba4ac3b239c16c24548cdc4/base/broadcast.jl#L608).

Pointed out recently [on discourse](https://discourse.julialang.org/t/recent-broadcast-changes-iterate-by-default-scalar-struct-and/11178/67?u=stevengj).

This won't break backwards compatibility, because currently broadcasting over an enum gives `MethodError: no method matching length(::Foo)`.

**Comment by AzamatB** [comment]
Was fixed by #30675, close this?

**Comment by pjgorski** [comment]
In Julia LTS this error still exists:

Example:

```
@enum E x = 0 y = 1
Es = [E(0) for i in 1:100]
Es .== E(0)
```

**Comment by stevengj** [comment]
This feature requires Julia 1.2 or later.
