### ISSUE TITLE
order of simultaneous garbage collection

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#3067]
This code:
```julia
type foo
    x
end

function f()
    a = foo(0)
    b = foo(a)
    finalizer(a,(t)->println("GC'd a"))
    finalizer(b,(t)->println("GC'd b"))
    return
end

f()
gc()
```

sometimes outputs
```
GC'd a
GC'd b
```
and sometimes
```
GC'd b
GC'd a
```

So there's no guarantee that when the finalizer is called, the members of an object remain valid? Is this intended? This was causing an issue with a C library that wants certain objects to be released in order.

**Comment by carnaval** [comment]
Any guarantee on the finalizer order would be likely to make them even slower than they are. If you want the ordering you'll have to handle it on the application level.
