### ISSUE TITLE
0/1 printing of false/true is confusing in Dict

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#30683]
```julia
julia> VERSION
v"1.2.0-DEV.146"

julia> show(Dict(true => false))
Dict(1=>0)
```

Also,

```julia
julia> Dict(true => false)
Dict{Bool,Bool} with 1 entry:
  true => false
```

seems to be inconsistent with

```julia
julia> [true => false]
1-element Array{Pair{Bool,Bool},1}:
 1 => 0
```

It looks like `display(Dict(...))` does not set `typeinfo` while `show(Dict(...))` does.  Here is the code I used to check it:

```julia
function logio_show(io, mime)
    push!(logio_log, ("mime", mime))
    push!(logio_log, ("io isa IOContext", io isa IOContext))
    if io isa IOContext
        push!(logio_log, ("io.dict", io.dict))
    end
    print(io, "LogIO")
end

Base.show(io::IO, mime::MIME"text/plain", ::LogIO) =
    logio_show(io, mime)

Base.show(io::IO, ::LogIO) =
    logio_show(io, nothing)
```

then

```julia
empty!(logio_log)
display(Dict(:a=>LogIO()))
logio_log
```

shows

```julia
3-element Array{Any,1}:
 ("mime", nothing)                                                                                                
 ("io isa IOContext", true)                                                                                       
 ("io.dict", Base.ImmutableDict{Symbol,Any}(:compact=>true,:SHOWN_SET=>Dict(:a=>LogIO),:module=>Main,:limit=>true,:color=>true))
```

(i.e., no typeinfo) while

```julia
empty!(logio_log)
show(Dict(:a=>LogIO()))
logio_log
```

shows

```
3-element Array{Any,1}:
 ("mime", nothing)                                                                                                
 ("io isa IOContext", true)                                                                                       
 ("io.dict", Base.ImmutableDict{Symbol,Any}(:typeinfo=>LogIO,:compact=>true,:compact=>true,:typeinfo=>Pair{Symbol,LogIO},:SHOWN_SET=>Dict(:a=>LogIO),:color=>true))
```

i.e., typeinfo is set to `LogIO`.

**Comment by stevengj** [comment]
The `show(io, dict)` method [sets `:typeinfo` here](https://github.com/JuliaLang/julia/blob/b73d34f87d2497c2356fa13fbb150512ca111b02/base/dict.jl#L24-L27), which it shouldn't since it doesn't print the type.  Whereas the `show(io, text/plain, dict)` method [fails to set `:typeinfo` here](https://github.com/JuliaLang/julia/blob/b73d34f87d2497c2356fa13fbb150512ca111b02/base/show.jl#L73-L75).

**Comment by stevengj** [comment]
That being said, we may want to think about disabling printing of boolean values as 0/1 when printing dict (or maybe in general for printing pairs and tuples even if the typeinfo indicates a `Bool` field).

**Comment by stevengj** [comment]
Would be good to revisit this.

**Comment by JeffBezanson** [comment]
This might be another case where a `parseable` or `repr` printing flag would make sense.

**Comment by tkf** [comment]
> a `parseable` or `repr` printing flag would make sense

Please see #33260

**Comment by stevengj** [comment]
> This might be another case where a parseable or repr printing flag would make sense.

That seems orthogonal to the present issue, which is simply that `typeinfo` is being set incorrectly.

**Comment by logankilpatrick** [comment]
@JeffBezanson @stevengj Can you add some context as to why this behavior exists: 

```
d = [true, false, true]
3-element Vector{Bool}:
1
0
1
```
instead of showing `true, false, true` in the output?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/30575 is the context. Now, one could ask the question if it is worth printing it compactly like that for a `Vector{Bool}` where every element is on its own line.
