### ISSUE TITLE
Undefined reference to `sgemm_kernel_direct` during OpenBLAS build

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#30696]
When using ccache, OpenBLAS build regularly fails with:
```
../libopenblas64_p-r0.3.5.a(cblas_sgemm.o): In function `cblas_sgemm':
gemm.c:(.text+0x582): undefined reference to `sgemm_kernel_direct_performant'
gemm.c:(.text+0x5d6): undefined reference to `sgemm_kernel_direct'
```
Most likely explanation is a race condition inside the OpenBLAS build system.

**Comment by ararslan** [comment]
Do you see the same thing when building OpenBLAS outside of Julia's build system?

**Comment by Keno** [comment]
Heavn't tried, but @staticfloat reports he saw this in the OpenBLAS builder, so probably.

**Comment by cdluminate** [comment]
I can build julia against openblas 0.3.5 without problem. Check our official buildlog here if you like: https://buildd.debian.org/status/fetch.php?pkg=julia&arch=amd64&ver=1.0.3%2Bdfsg-2&stamp=1547386704&raw=0

**Comment by Keno** [comment]
It's a race condition of some sort in the build system most likely, so it only shows up at high concurrency and with hot build caches.

**Comment by staticfloat** [comment]
This is a problem with OpenBLAS v0.3.5 when cross-compiling to a 32-bit architecture.  It has since been fixed, and the following patch is sufficient to fix it for our purposes:

```diff
diff --git a/Makefile.system b/Makefile.system
index fb8e7ea4..c7c4fedf 100644
--- a/Makefile.system
+++ b/Makefile.system
@@ -151,7 +151,8 @@ GETARCH_FLAGS       += -DNO_AVX
 endif

 ifeq ($(BINARY), 32)
-GETARCH_FLAGS  += -DNO_AVX
+GETARCH_FLAGS  += -DNO_AVX -DNO_AVX2 -DNO_AVX512
+NO_AVX512 = 1
 endif

 ifeq ($(NO_AVX2), 1)
```

**Comment by ViralBShah** [comment]
The build seems more reliable since we build with `make -j` on BB reliably. Please reopen if still an issue.
