### ISSUE TITLE
lower bound interferes with typevar value inference

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#30713]
Consider the following:

```
struct XX end
struct YY end

bar(a::A, b::B, c::C) where Tuple{A,B}<:C<:Union{Tuple{XX,YY}, Tuple{YY,XX}} where A where B = C

@show bar(XX(), YY(), (XX(),YY()))
```
gives:
```
julia> @show bar(XX(), YY(), (XX(),YY()))
ERROR: UndefVarError: C not defined
Stacktrace:
 [1] bar(::XX, ::YY, ::Tuple{XX,YY}) at ./REPL[3]:1
```
Expected  is to return `Tuple{XX,YY}`

Similarly:
```
julia> @show bar(YY(), XX(), (YY(),XX()))
ERROR: UndefVarError: C not defined
Stacktrace:
 [1] bar(::YY, ::XX, ::Tuple{YY,XX}) at ./REPL[3]:1
```

Expected  is to return `Tuple{YY,XX}`

For interest:
`bar(XX(), YY(), (XX(), XX())` and `bar(XX(), XX(), (XX(), XX())` , and `bar(XX(), XX(), (YY(),YY()))` and `bar(YY(), YY(), (YY(),YY()))` and `bar(YY(),XX(), (YY(),YY()))` give method errors

**Comment by JeffBezanson** [comment]
Yes, I think the lower bound just makes it too hard for us to derive a unique value for `C`. It works without the lower bound.

**Comment by oxinabox** [comment]
It looks to me, based on the `MethodErrors` the dispatch is actually working,
it is just loosing `C` somewhere.
