### ISSUE TITLE
Inline exports

### ISSUE THREAD

**Issue by dalum** [JuliaLang/julia#30714]
In some cases, it would be nice to be able to write:
```julia
export x = 42
export f(x) = x^2
export function my_very_long_function_name(a, b, c, d...)
    # ...
end
```
instead of:
```julia
export x, f, my_very_long_function_name

x = 42
f(x) = x^2
function my_very_long_function_name(a, b, c, d...)
    # ...
end
```
I have found this to be the case when I write non–package code, and just want my module/project to be used as a sandbox with `using` and Revise in the REPL.

The syntax is currently an error, and I can't think of an alternative interpretation of its meaning.

**Comment by tknopp** [comment]
dup of https://github.com/JuliaLang/julia/issues/8005
