### ISSUE TITLE
Regression from 0.6: Type inference failure

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#30720]
Type inference in the following example fails on Julia v1.0.3 and v1.2.0-DEV.169.  `@code_warntype` shows a `fatal error in type inference (type bound)`

```julia
using Test

function innersize(A::AbstractArray{<:AbstractArray{T,M},N}) where {T,M,N}
    s = if !isempty(A)
        sz_A = size(first(A))
        ntuple(i -> Int(sz_A[i]), Val(M))
    else
        ntuple(_ -> zero(Int), Val(M))
    end

    if !all(X -> size(X) == s, A)
        throw(DimensionMismatch("Shape of element arrays of A is not equal, can't determine common shape"))
    end

    s
end

A = [[1, 2, 3], [4, 5, 6]]

@inferred innersize(A)

@code_warntype innersize(A)
```

When splitting `innersize` into two parts, all seems fine on Julia v1.2.0-DEV.169, but the problem still occurs on v1.0.3:

```julia
function _innersize_first(A::AbstractArray{<:AbstractArray{T,M},N}) where {T,M,N}
    s = if !isempty(A)
        sz_A = size(first(A))
        ntuple(i -> Int(sz_A[i]), Val(M))
    else
        ntuple(_ -> zero(Int), Val(M))
    end

    s
end

function innersize2(A::AbstractArray{<:AbstractArray{T,M},N}) where {T,M,N}
    s = _innersize_first(A)

    if !all(X -> size(X) == s, A)
        throw(DimensionMismatch("Shape of element arrays of A is not equal, can't determine common shape"))
    end

    s
end

@inferred innersize2(A)

@code_warntype innersize2(A)
```

**Comment by oschulz** [comment]
This seems to be a regression from Julia v0.6, when running the examples above on v0.6.2, `@inferred` does *not* throw an error.

**Comment by Keno** [comment]
Does the warning actually ever trigger? If not everything is fine. The warning is being conservatively added by the compiler whenever it does some type based splitting.

**Comment by oschulz** [comment]
Ah, you mean does it actually throw the "error in type inference" exception? No - sorry, I didn't realize that that was just inserted for safety, I just never noticed that in the output of `@code_warntype` before, so I thought it indicated a problem.

However

    @inferred innersize(A)

throws

    ERROR: return type Tuple{Int64} does not match inferred return type Any

on Julia v1.0, v1.1.0-rc2.0 and 1.2.0-DEV.169, whereas v0.6.2 manages to infer the return type (so `@inferred` doesn't throw an exception on v0.6.2).

However, `@inferred innersize2(A)`, which just splits `innersize` into two functions, doesn't throw an exception on 1.2.0-DEV.169, but does throw on v1.0, v1.1.0-rc2.0.

I changed the title of this issue accordingly.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276. Putting something like `let s = s` around the closure (the `all`) and it infers.

On 1.0.3, the same has to be done with `sz_A`.

**Comment by oschulz** [comment]
Ah, of course, the closure in `all()`, I should have known. Thanks, @Keno and @KristofferC, and sorry for the dup!
