### ISSUE TITLE
Improve docs for Random

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#30732]
To make `randn` and `randexp` work for a new RNG it necessary to also define
```julia
Random.rng_native_52(::NewRNG) = Float64
```
This isn't clear so it would be good to have in the docs.

**Comment by rfourquet** [comment]
The API for defining a new RNG is not fully sorted out, and `rng_native_52` is still an internal method which I'm reluctant to document officially. However a docstring could be added to make it easier for RNG implementors in the meatime.
Alternatively, a default implementation returning `Float64` could be defined, I think in most cases it would be fine.
