### ISSUE TITLE
jlchecksum is sensitive to the linefeed used on the system

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#30752]
Trying to build Julia on cygwin I get a problem during checksum verification made by `jlchecksum`:

```
  ERROR: sha512 checksum failure on cacert-2018-12-05.pem, should be:
      1896c83c6bad4f1ab2a5c1fa04f694597e8319e1892eb48c74ce85dad82c924c
      143c1e09b8d86354ba7b1ef001237a52b503c9ebe06eef61dd16c3689a5e9b30

  But `sha512sum /cygdrive/c/Users/Kristoffer/julia/deps/srccache/cacert-2018-12-05.pem | awk '{ print $1; }'` results in:
      1896c83c6bad4f1ab2a5c1fa04f694597e8319e1892eb48c74ce85dad82c924c
      143c1e09b8d86354ba7b1ef001237a52b503c9ebe06eef61dd16c3689a5e9b30
```

These look the same, but dumping them to hex, we can see

```
$ hexdump deps/curr_check
0000000 3831 3639 3863 6333 6236 6461 6634 6131
0000010 3262 3561 3163 6166 3430 3666 3439 3935
0000020 6537 3338 3931 3165 3938 6532 3462 6338
0000030 3437 6563 3538 6164 3864 6332 3239 6334
0000040 3431 6333 6531 3930 3862 3864 3336 3435
0000050 6162 6237 6531 3066 3130 3332 6137 3235
0000060 3562 3330 3963 6265 3065 6536 6665 3136
0000070 6464 3631 3363 3836 6139 6535 6239 3033
0000080 000a
0000081

Kristoffer@DESKTOP-188MN1B ~/julia
$ hexdump deps/true_check
0000000 3831 3639 3863 6333 6236 6461 6634 6131
0000010 3262 3561 3163 6166 3430 3666 3439 3935
0000020 6537 3338 3931 3165 3938 6532 3462 6338
0000030 3437 6563 3538 6164 3864 6332 3239 6334
0000040 3431 6333 6531 3930 3862 3864 3336 3435
0000050 6162 6237 6531 3066 3130 3332 6137 3235
0000060 3562 3330 3963 6265 3065 6536 6665 3136
0000070 6464 3631 3363 3836 6139 6535 6239 3033
0000080 0a0d
0000082
```

Which to me indicates different line endings (`0a0d`). The true checksum is read with `cat` while the computed one is printed with `awk` and it seems these disagree.

**Comment by vtjnash** [comment]
We may want to tell git not to corrupt any files (right now, we tell it only to not corrupt files ending in `.patch`). c.f. #25537 and related issues / PRs

**Comment by KristofferC** [comment]
This was attempted (https://github.com/JuliaLang/julia/pull/27291) and subsequently reverted (https://github.com/JuliaLang/julia/pull/28280). Any idea for a workaround to that?

**Comment by vtjnash** [comment]
That's the reverse: it asked git to corrupt any occurrence of CR, we want the opposite (preserve exact contents of repository)

**Comment by davidanthoff** [comment]
> That's the reverse: it asked git to corrupt any occurrence of CR, we want the opposite (preserve exact contents of repository)

That was not the problem with #27291, the problem was that it didn't work with older versions of git.

I have a new attempt up at https://github.com/JuliaLang/julia/pull/32781. Feedback would be welcome!

**Comment by BioTurboNick** [comment]
Putting in a vote for addressing this, would have saved me a bit a trouble building julia for the first time :-)
