### ISSUE TITLE
issetequal doesn't check IteratorSize

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#30768]
[This](https://github.com/JuliaLang/julia/blob/b8c0ec8a0a2d12533edea72749b37e6089a9d163/base/abstractset.jl#L291) method kicks in for arbitrary iterables. It shouldn't just call ``length`` therefor, but instead first check ``IteratorSize``, and then fall back on some other implementation if it returns ``SizeUnknown()``.

**Comment by laborg** [comment]
This has been changed in the meantime (starting with https://github.com/JuliaLang/julia/pull/28871):
https://github.com/JuliaLang/julia/blob/cc345f6bc5f1406bd8d5af8265b91645f0adaeaf/base/abstractset.jl#L439-L443
