### ISSUE TITLE
mistake types as free variables when sharing types among nested closure

### ISSUE THREAD

**Issue by thautwarm** [JuliaLang/julia#30772]
When creating a generic nested function and referencing a generic type variable inside the inner closure of its inner closure, an unexpected error would occur.

To reproduce this bug clearly, given following codes:

```julia
function ()
    function (a :: T) where T
        function ()
            function (b :: T)
                 
            end 
       end    
    end
end
```
We got a 
```julia
ERROR: syntax: local variable T cannot be used in closure declaration
```

Now there is a workaround but I don't know why it works, I reference this here for it might give you developers some crucial information:

If I simply use the type variable referenced by inner scope in any form, the error could be avoided.

```julia
function ()
    function (a :: T) where T
        function ()
            function (b :: T)
                 T
                 nothing
            end 
       end    
    end
end
``` 
In more complex cases(more nested level/hierarchy), this workaround also works.

**Comment by JeffBezanson** [comment]
Thanks. This should be straightforward to fix.
