### ISSUE TITLE
@deprecate macro does not handle functions with kwargs and does not respect maxlog=1

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#30777]
@deprecate f g
will not handle `f(x...; o...)` and prints the warnings more than once.

**Comment by c42f** [comment]
maxlog problem is probably #29878 so probably already fixed in julia-1.0.2?

**Comment by denizyuret** [comment]
@deprecate has somehow avoided that solution. It still repeats the warnings as of Julia 1.1. You can easily try it with:
```
f(x) = x*x
@deprecate g f
```
Then call g(2) a couple of times.

**Comment by vtjnash** [comment]
sounds like people think this isn't hasn't been an issue lately
