### ISSUE TITLE
kron(a::Diagonal, b) ref #24980

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#30770]
Should `kron(::Diagonal, ::Union{SparseVector, SparseMatrix})` (and viceversa) return `SparseMatrixCSC`? (IMHO yes)
Should `kron(::Diagonal, ::Matrix)` (and viceversa) return `SparseMatrixCSC`? (this would be consistent with the recently merged #24980 in which sparse times dense gives sparse -- but currently there is an implementation for `Diagonal` times dense returning dense so I'm not so sure)

**Comment by andreasnoack** [comment]
> Should kron(::Diagonal, ::Union{SparseVector, SparseMatrix}) (and viceversa) return SparseMatrixCSC?


Yes, I definitely think it should.

>  ...but currently there is an implementation for Diagonal times dense returning dense so I'm not so sure)

This case is a bit complicated because of the dependency structure. To return a sparse matrix, `SparseArrays` would have to be a dependency of `LinearAlgebra`.

**Comment by abraunst** [comment]
I will close this since the first issue is resolved, and the second probably won't be,
