### ISSUE TITLE
Version 1.10

### ISSUE THREAD

**Issue by togo59** [JuliaLang/julia#30793]
v1.1 Doesn't find installed packages, needs to `add` them. But I'm suspicious, the speed is very fast, by `add`ing them is it just "finding" them in the .julia/packages directory?

Also, can we update this (e.g. for Rigid Body Dynamics)?

`ERROR: ArgumentError: Package RigidBodyDynamics not found in current path:
- Run `import Pkg; Pkg.add("RigidBodyDynamics")` to install the RigidBodyDynamics package.`

with `]add RigidBodyDynamics`

**Comment by KristofferC** [comment]
> But I'm suspicious, the speed is very fast, by adding them is it just "finding" them in the .julia/packages directory?

Yes.

You can copy the folder `.julia/environments/v1.0` to `.julia/environments/v1.1` to get the same environment as in 1.0.
