### ISSUE TITLE
Bug in `hasmethod(f, Tuple{Union{}})` 

### ISSUE THREAD

**Issue by ettersi** [JuliaLang/julia#30808]
The following should be true: 
```
julia> hasmethod((::Int)->nothing, Tuple{Union{}})
false
```
Note that `hasmethod()` works as expected if the function is defined in terms of an abstract type. 
```
julia> hasmethod((::Integer)->nothing, Tuple{Union{}})
true
```

Related discourse discussion [here](https://discourse.julialang.org/t/determine-whether-any-one-argument-method-exists/19917).

**Comment by JeffBezanson** [comment]
I think this is because these code paths never need to handle `Union{}` because it can't be the type of an object. These things tend to be highly optimized. I guess it would be nice to fix if possible though.

**Comment by tk3369** [comment]
Looks like this issue has been fixed. I've tested on both 1.6.4 and 1.7.0-rc3.

```julia
julia> hasmethod((::Int)->nothing, Tuple{Union{}})
true

julia> hasmethod((::Integer)->nothing, Tuple{Union{}})
true
```
