### ISSUE TITLE
Symmetric(::Hermitian) with bug

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#30814]
For all `X::AbstractMatrix` we should have
1. `Symmetric(X) == Symmetric(Matrix(X))`

Actually we obtain
```
julia> VERSION
v"1.2.0-DEV.212"

julia> A = [1 2; 3 4]*(1+im)
2×2 Array{Complex{Int64},2}:
 1+1im  2+2im
 3+3im  4+4im

julia> X = Hermitian(A)
2×2 Hermitian{Complex{Int64},Array{Complex{Int64},2}}:
 1+0im  2+2im
 2-2im  4+0im

julia> Symmetric(Matrix(X)) == Symmetric(X) # contradicting 1.
false

julia> Symmetric(X)
2×2 Symmetric{Complex{Int64},Array{Complex{Int64},2}}:
 1+1im  2+2im
 2+2im  4+4im

julia> Symmetric(Matrix(X))
2×2 Symmetric{Complex{Int64},Array{Complex{Int64},2}}:
 1+0im  2+2im
 2+2im  4+0im
```

That is a consequence of allowing `A` with `!isreal(diag(A))` as argument for `Hermitian`.
I think, we should throw an exception in the case of `Symmetric(Hermitian(A))`, if  `!isreal(diag(A))`.

**Comment by andreasnoack** [comment]
This is indeed a bug. An alternative (not necessarily a good one) would be just to wrap the `Hermitian` in a `Symmetric`. That would be correct but many layers of nesting aren't nice.

**Comment by KlausC** [comment]
@andreasnoack  I don't understand, can you show code to see what you mean. I just tried to show, that wrapping a `Hermitian` in a `Symmetric` gives rise to errors. I agree, that nesting should be reduced and not proliferated.

**Comment by fredrikekre** [comment]
Double nesting like that basically makes it unusable. To dispatch to nice BLAS routines we need `.data` to be a regular strided array I think, and that is the whole point of these wrappers, no?

**Comment by andreasnoack** [comment]
What are the other options? So far, we have wrapping and throwing.

**Comment by fredrikekre** [comment]
Throwing for non-real diagonal seems fine to me.

**Comment by KlausC** [comment]
I think, we should take a more mathematical less information technical view on those wrappers.
IMO most of the wrapper types can be considered as mappings in the space of square matrices. Nested wrappers are then compositions of such mappings, which form a finite semigroup. That means all however deeply nested combinations of `Symmetric/Hermitian/UpperTriangular/.....` can be represented by relatively few variants of a generic wrapper type...

**Comment by andreasnoack** [comment]
> I think, we should take a more mathematical less information technical view... can be represented by relatively few variants of a generic wrapper type

I assume this is related to https://github.com/KlausC/SparseWrappers.jl but do you have written this more elaborate somewhere? I'd like to read it.

**Comment by KlausC** [comment]
@andreasnoack , you guess right. The mentioned package is my sandbox for some new ideas about my current hobby, the wrapping of sparse matrices. As you may know, I am a retired technical IT person, coming back to my scientific maths youth. So I cannot present you published papers. All I have written about UniversalWrapper you find in  https://github.com/KlausC/SparseWrappers.jl/tree/master/src/universal.jl in the moment.

**Comment by andreasnoack** [comment]
Sounds good. Wasn't looking for a paper. Just something longer than a README.

**Comment by KlausC** [comment]
@andreasnoack, I just wrote this text: [universal matrix wrappers](https://gist.github.com/KlausC/3be3573877f87439e6a42f2c1ed4b607) which might interest you.

ps - are you watching the handball world championship?
