### ISSUE TITLE
Matrix product between a real and a complex matrix

### ISSUE THREAD

**Issue by yanncalec** [JuliaLang/julia#30811]
In Julia >1.0 I observed the product between a real and a complex matrix run very slowly. This does not concern the complex and real matrix product however:
```
M = 2000
C = rand(M,M) + im*rand(M,M)
R = rand(M,M)
@time C * R;
@time R * C;

  0.090447 seconds (11 allocations: 61.036 MiB, 2.09% gc time)
  6.074982 seconds (12 allocations: 61.036 MiB, 0.61% gc time)
```

**Comment by andreasnoack** [comment]
Because of the memory layout, the complex*real product can be reinterpreted as a real BLAS call, see https://github.com/JuliaLang/julia/blob/7c955c4a828af7cb4483f3e98db388b92aa89149/stdlib/LinearAlgebra/src/matmul.jl#L145-L156. That isn't possible in the real*complex case so here we are hitting the Julia fallback instead of using BLAS.

**Comment by yanncalec** [comment]
Uninformed user won't expect such a difference in speed. Is it possible to have a workaround using the trivial identity
```
R * C = (C' * R')'
```
so that we always fall back to the complex real product case?

**Comment by andreasnoack** [comment]
> Why is it closed? This should be considered as a bug and uninformed user won't expect such a difference in speed.

Multiplying real and complex matrices isn't supported by BLAS so it will generally be slow. In one of the cases, the memory layout happens to be such that we can reinterpret the arrays and make a BLAS call but this is not possible in the other case so the only way to avoid the difference is to make the fast version slower. I don't like that solution.

Alternatively, we could consider converting the real matrix to complex. That is tracked in #20060.

>  Is it possible to have a workaround using the trivial identity

No. You'd still traverse the memory in the same way.

**Comment by yanncalec** [comment]
What is the possible reason for this:
```
@time Matrix(C') * R';  # or (real.(C)'-im*imag.(C)') * R'
@time C' * R';

  0.356300 seconds (16 allocations: 122.071 MiB, 60.43% gc time)
  6.083023 seconds (14 allocations: 61.036 MiB, 0.63% gc time)
```
The workaround I found to the problem of real complex product is
```
@time (Matrix(C')*R')'

  0.344454 seconds (17 allocations: 122.071 MiB, 60.94% gc time)
```

**Comment by PetrKryslUCSD** [comment]
If I may make a suggestion, the documentation for `mul!` and its relatives should describe this issue. It is certainly not obvious that the order of the complex and real matrices will have an order of magnitude impact on the performance. In fact, the library code might also try to correct for this with the transpose of the product of transposes as suggested by @yanncalec, but this might have performance costs for large matrices.

**Comment by simonbyrne** [comment]
> What is the possible reason for this:
> 
> ```
> @time Matrix(C') * R';  # or (real.(C)'-im*imag.(C)') * R'
> @time C' * R';
> 
>   0.356300 seconds (16 allocations: 122.071 MiB, 60.43% gc time)
>   6.083023 seconds (14 allocations: 61.036 MiB, 0.63% gc time)
> ```

By realising the transpose you're making it possible to go through the memory in the correct order (the "lazy transpose" version can't do this).

**Comment by PetrKryslUCSD** [comment]
I think a good solution would be to compute `R * real(C) + im * R * imag(C)`. Fast, but still there is the need of a temporary.

**Comment by antoine-levitt** [comment]
Can this be reopened? I think it is possible to do mul!(A, R, C) through BLAS and without allocation with two BLAS calls: stride 2 on A and C, first call with offset 0 on A and C, second call with offset 1. Possibly not ideal because it does lose some memory locality, but should be better than the generic method.

**Comment by antoine-levitt** [comment]
To clarify, it seems that the original issue is fixed: `R * C` and `C * R` take roughly the same time (despite the fact that R gets copied into a complex array, see matmul.jl:158). However, eg `transpose(R) * C` is still horribly slow.
