### ISSUE TITLE
Document effect of const on type stability of type aliases (plus effects on performance)

### ISSUE THREAD

**Issue by mhinsch** [JuliaLang/julia#30824]
Type aliases on the global level lead to type instability and consequently loss of performance unless declared `const`. It makes perfect sense if you think about it but it's very unexpected if you don't and very hard to find (I just spent hours trying to find the reason why I still had a few `Any`s in my code). Furthermore, if you need mutually recursive types you are basically bound to run into this problem, so it's certainly not a rare issue.

As far as I can tell there is no documentation about this (apart from issue #24915), neither in the section on type aliases nor in the performance tips.

**Comment by JeffBezanson** [comment]
https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables-1 ?

**Comment by JeffBezanson** [comment]
That's fair; it would be good to add a sentence clarifying that this also applies to type-valued variables.

**Comment by namanbiyani** [comment]
Hi, I was planning to contribute towards GSoC 2019. I want to contribute to this issue. Please give some guidelines.
