### ISSUE TITLE
Truncation using toms(c::CompoundPeriod) and tons(c::CompoundPeriod)

### ISSUE THREAD

**Issue by virtualgraham** [JuliaLang/julia#30832]
toms(c::CompoundPeriod) and tons(c::CompoundPeriod) should not truncate for small values, according to comments in the periods.jl source file.

> &#35; truncating conversions to milliseconds, nanoseconds and days:
> &#35; overflow can happen for periods longer than ~300,000 years

In practice it seems to truncate nanoseconds for any CompoundPeriod that contains more than just nanoseconds:

```
julia> using Dates

julia> a = Dates.tons(Dates.Second(1) + Dates.Nanosecond(1))
1.0e9

julia> function my_tons(c::Dates.CompoundPeriod)
           s::Float64 = 0.0
           for p in c.periods
               v = Dates.tons(p)
               s += v
           end
           return s
       end
my_tons (generic function with 1 method)

julia> b = my_tons(Dates.Second(1) + Dates.Nanosecond(1))
1.000000001e9

julia> a == b
false

```

I assume the truncation is happening here:

`toms(c::CompoundPeriod) = isempty(c.periods) ? 0.0 : Float64(sum(toms, c.periods))`

but i don't actually know how

I'm using Julia version 1.0.3 on Linux

**Comment by simonbyrne** [comment]
Ah, the problem is `tons` is falling back on `toms`:
https://github.com/JuliaLang/julia/blob/a7fabc91638064ebbad03831881b1459d4b92bd5/stdlib/Dates/src/periods.jl#L460

Also, these are terrible names (why not `nanoseconds` and `milliseconds`?)
