### ISSUE TITLE
Groupby Mean dataframe column with missing data

### ISSUE THREAD

**Issue by DruPlusDru** [JuliaLang/julia#30839]
I'm having a hard time trying to get a grouped mean for a field with missing values.

using JuliaDBMeta
t = @groupby df :Id {
    count = length(_),
    Mean = mean(skipmissing(:Variable))
}

Returns ArgumentError: mean of empty collection undefined: Base.SkipMissing{SubArray{Union{Missing, Float64},1,Array{Union{Missing, Float64},1},Tuple{Array{Int64,1}},false}}(Union{Missing, Float64}[missing, missing, missing, missing, missing, missing])

All I want to do is find the grouped mean for a column with some missing data. I've searched up and down the web and functions always seem to be deprecated. So frustrating.

**Comment by nalimilan** [comment]
This isn't an issue with Julia Base. Please use [the Discourse forum](http://discourse.julialang.org/) for questions or file a bug against JuliaDBMeta.jl. Thanks!
