### ISSUE TITLE
Download versioned, hashed versions of dependencies during build/tests

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#30840]
There are a few places where our infrastructure downloads things from the internet without checking to make sure it's downloading the appropriate object.  We should avoid downloading things that can change (e.g. [arbitrary versions of `busybox.exe`](https://github.com/JuliaLang/julia/blob/341587592daccd144f5653c86cc1e362fe209838/test/spawn.jl#L23)) so that we can add hashes and check the result upon download, ensuring that we're downloading what we intend to.  This should also be a good time to do a pass on everything we download and make sure as much as possible is using HTTPS, where appropriate.

**Comment by staticfloat** [comment]
Hey @EternalLearner42.  I'm glad that you have reached out!  Let me walk you through some of the things you can do to help with this;

- We need to fix the downloading of `busybox.exe` in `test/spawn.jl` to download a version that will not change over time, (e.g. download from the "versioned" URL, I believe it is `https://frippery.org/files/busybox/busybox-w32-FRP-2910-ge92596d0b.exe` right now) and we need to embed the `SHA256` hash into the `test/spawn.jl` file so that after downloading, we read in the file, hash it, and check that the hash matches what we know it should be.
- We need to search through the Julia codebase and find places where we are downloading things over `http://` instead of `https://` and switch to `https://` when possible/appropriate.  Examples where we should be downloading over `https://` is anytime we are downloading code or binary data that is used in the build/test.  An example where we do not need to download over `https://` is [the `httpbin.org` test set](https://github.com/JuliaLang/julia/blob/c44644442949238da70670b547312ca1ae9a9c7d/test/download.jl#L6), where it is very useful for us to be able to intercept those requests to discover why something is not working.  It is perhaps useful to add tests ensuring that `https://` downloading works as well, however, so I would suggest that we add more tests there to double-up on `http` and `https` for those tests in particular.

**Comment by arnavs** [comment]
FYI, I think https://github.com/QuantEcon/InstantiateFromURL.jl could help with this. 

What we do is support versioning TOML files in lightweight GitHub repositories (they really only need the two files), and (optionally) you can download per commit/SHA hash. 

For examples of such repositories, see https://github.com/QuantEcon/QuantEconLecturePackages

**Comment by EternalLearner42** [comment]
This seems interesting, but I think @staticfloat should be the one to voice his opinion on it.

By the way @staticfloat, I am going to submit my PR. Pretty sure it has a lot of mistakes in it (and I suspect my wget has a problem), but I'm willing to do any changes you see fit.

**Comment by ViralBShah** [comment]
Close?
