### ISSUE TITLE
Accidental Version Publish

### ISSUE THREAD

**Issue by haydenfree** [JuliaLang/julia#30844]
Hello,

I work on the CurricularAnalytics package and we accidentally pulled in version 2.2.5 instead of 0.2.5.
Is there any way to remove this version from METADATA? We don't want users to receive it as the "newest" version.

Thank you,
Hayden

**Comment by andreasnoack** [comment]
In this specific case, please comment on the specific PR to METADATA. For general questions about METADATA, please use discourse.julialang.org.

**Comment by fredrikekre** [comment]
Open a PR for reverting in metadata
