### ISSUE TITLE
dense .+ sparse -> sparse?

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#30848]
(reported first on [this thread](https://discourse.julialang.org/t/dense-sparse-sparse/20126?u=abraunst)). I find this counterintuitive:

```julia
julia> using SparseArrays

julia> A=rand(100,100);

julia> B=sprand(100,100,0.01);

julia> typeof(A + B)
Array{Float64,2}

julia> typeof(A .+ B)
SparseMatrixCSC{Float64,Int64}
```

I would have expected the result to be dense. Is there a rationale for this?

**Comment by ViralBShah** [comment]
It should be dense.

**Comment by mbauman** [comment]
Coming up with a general rule here is hard. We want `A .* B` to be sparse, yah? Both that and `A .+ B` and `f.(A, B)` all use the same code path currently (IIRC).

**Comment by ViralBShah** [comment]
Yes, for the `.*`, sparse result makes sense, but if one of the inputs is dense, it is quite likely that the dense output won't blow up the memory.

**Comment by abraunst** [comment]
I have not thought very thoroughly about this, but could it make sense to make it depend on the order of the operands? I.e. 

dense `.op` sparse -> dense
sparse `.op` dense -> sparse

it would be easy to remember because it would follow the behavior of  `.op=`. The only problem I see is that sometimes you can't choose the order (i.e. when the operand is non-commutative).

**Comment by StefanKarpinski** [comment]
Basing it on ordering seems very unJulian.

I think it makes sense to just special case `.*` since it’s one of the few operations where sparse/dense will be sparse.

**Comment by ViralBShah** [comment]
With `./` you get a bunch of `Inf`s. You also have all the functions like `sin`, where sparse -> sparse makes sense, and `cos` where sparse -> dense makes sense. The key test is whether an operation on with a zero yields a zero or not.

**Comment by mbauman** [comment]
It gets hard with combinations of dense and sparse arrays.  We can check if `f(0, 0)` yields a zero quite easily, but what you really want in the case of `f.(dense, sparse)` is to check `f(nonzero, 0)`.  But of course we can't check all nonzero values nor the general behavior and just examining one nonzero value might find the one nonzero value that ends up yielding a zero.

**Comment by ViralBShah** [comment]
Yes, it cannot be value dependent. It should be based on `f(nonzero)`, and ideally, a commutative `f(nonzero,0)`.

**Comment by alegarra** [comment]
I was bitten by this behaviour. If you guys change it would be nice to have something to be able to make sparse+dense=sparse

My case:  Mixed linear Models with a *very large and very sparse* sparse matrix (perhaps 10^6 x 10^6 with 1% non-null elements) and I add a *small* (say 1000 x 1000) matrix. So I prefer it to be sparse.

**Comment by ViralBShah** [comment]
It is unlikely we will change it. The general rule is that we try to preserve the sparsity, and in cases where people don't want it, they should explicitly convert it.
