### ISSUE TITLE
Make shell mode persistent like package mode?

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#30853]
What I like about the package mode is that I can successfully type commands without exiting it:

```julia
]
pkg> st
pkg> up
pkg> add Foo
```

In shell mode, however, I have to re-enter the mode after each command:

```julia
;
shell> ls
;
shell> cd foo
;
shell> git pull
```

Could we have shell mode behave like package mode?

**Comment by fredrikekre** [comment]
#6320, #19202
