### ISSUE TITLE
Nested function + for loop scope difference between 0.7 and 1.0.3

### ISSUE THREAD

**Issue by dfagnan** [JuliaLang/julia#30856]
```
function main(N=10)
	function print_loop_var()
		println(i)
	end
	i = 1
	for i=1:N
		print_loop_var()
	end
end

main()
```

prints a series of 1s on v1.0.3, and 1 through N on 0.7

assume this is a bug on one version since my understanding is they are supposed to be "functionally" the same.

**Comment by dfagnan** [comment]
Nevermind - sounds the same as in infamous existing bug that has already been discussed exhaustively.
https://github.com/JuliaLang/julia/issues/28789

**Comment by JeffBezanson** [comment]
You're right that this is a different issue. The 1.0 behavior is correct; now `for i = ...` always makes `i` a new loop-local variable. 0.7 attempts to give a deprecation warning for cases like this, e.g.
```
julia> function f()
       i = 1
       for i = 2:10
       end
       i
       end
┌ Warning: Use of final value of loop variable `i` around REPL[1]:5 is deprecated. In the future the variable will be local to the loop instead.
```
but the deprecation mechanism misses your example.

**Comment by StefanKarpinski** [comment]
Sounds like there’s not anything to do here then?
