### ISSUE TITLE
Invalid CPU name x86-64 error when building with MARCH=x86-64 on Linux

### ISSUE THREAD

**Issue by Pbellive** [JuliaLang/julia#30850]
See [Discourse thread](https://discourse.julialang.org/t/invalid-cpu-name-x86-64-error-when-building-with-march-x86-64/20115) for a little longer discussion. In summary, I was trying to build julia master from source with `MARCH=x86-64` in Make.user in order to run it on a small linux cluster where the nodes have different CPU types. This failed to build, throwing the following error (with a few extra lines of output for context)
```
LINK usr/lib/libjulia.so.1.2
CC ui/repl.o
LINK usr/bin/julia
JULIA usr/lib/julia/corecompiler.ji
ERROR: Invalid CPU name x86-64 .
sysimage.mk:60: recipe for target '/disk1/common/juliaLang/julia-master/usr/lib/julia/corecompiler.ji' failed
```
Adding `JULIA_CPU_TARGET=x86_64` to my Make.user, in addition to `MARCH=x86-64` fixed the problem. Setting `MARCH=x86_64` crashes for me as gcc doesn't recognize x86_64. The readme in the main julia repo and the comments in Make.inc seem to indicate to me that I should just have to set MARCH and not JULIA_CPU_TARGET. 

I'm not sure if this is a platform specific issue. I was building on a machine running Ubuntu 16.04.5 with gcc 5.4.0. Haven't tested on other platforms.

**Comment by yuyichao** [comment]
Or in another word, does `julia -C <cpu>` with `<cpu>` being `x86-64`, `x86_64` or `generic` all work for you? These should all work on a 64bit intel CPU (being it windows or linux or macOS). You should never set `MARCH` to `x86_64` or anything other than what you can find in the gcc (or other compiler)'s doc (feel free to suggest edit to the readme if that's not what you understand from there).

(Just to be clear, `-C x86-64` and `JULIA_CPU_TARGET=x86-64` should work and at least the `-C x86-64` does work for me.)
