### ISSUE TITLE
`rest` should be type-idempotent

### ISSUE THREAD

**Issue by under-Peter** [JuliaLang/julia#30869]
As in #18533, I think `rest`should be idempotent, i.e.
`typeof(rest(1:3, 2)) ==  typeof(rest(rest(1:3,2),1))`

with e.g.
```
rest(itr::Rest,state) = Rest(itr.itr,state)
```
This helped me in a situation where nested `Rest`s were used which caused type instabilities.

**Comment by martinholters** [comment]
Sounds reasonable. Want to open a PR?

**Comment by under-Peter** [comment]
Sure, I'm currently trying to build julia and once that's done I'll try to take care of it.
