### ISSUE TITLE
inv(::Irrational) errors

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#30882]
Current behaviour:
```julia
julia> inv(π)
ERROR: MethodError: no method matching Irrational{:π}(::Int64)
Closest candidates are:
  Irrational{:π}(::T<:Number) where T<:Number at boot.jl:741
  Irrational{:π}() where sym at irrationals.jl:18
  Irrational{:π}(::Complex) where T<:Real at complex.jl:37
  ...
Stacktrace:
 [1] convert(::Type{Irrational{:π}}, ::Int64) at ./number.jl:7
 [2] one(::Type{Irrational{:π}}) at ./number.jl:297
 [3] one(::Irrational{:π}) at ./number.jl:298
 [4] inv(::Irrational{:π}) at ./number.jl:220
 [5] top-level scope at none:0
```
Probably the ideal behaviour should be 
```julia
inv(x::Irrational) = 1/x
```

**Comment by MasonProtter** [comment]
Looks like at least for `π` and `ℯ`, there is no accuracy advantage to doing a compile time big float inverse. 
```
macro compiletimeinv(T)
       Float64(1/(big(eval(T))))
end

inv(::Irrational{:π}) = @compiletimeinv(π)

inv(::Irrational{:ℯ}) = @compiletimeinv(ℯ)

x = π

julia> @btime inv($x)
  0.024 ns (0 allocations: 0 bytes)
0.3183098861837907

julia> @btime 1/$x
  0.024 ns (0 allocations: 0 bytes)
0.3183098861837907

x = ℯ

julia> @btime inv($x)
  0.024 ns (0 allocations: 0 bytes)
0.36787944117144233

julia> @btime 1/$x
  0.024 ns (0 allocations: 0 bytes)
0.36787944117144233
```

**Comment by stevengj** [comment]
I would suggest `inv(x::AbstractIrrational) = inv(Float64(x))` as a fallback definition.

Individual `Irrational` constants can always override this if needed.

**Comment by StefanKarpinski** [comment]
> why single out `inv` to get extra precision?

It's not about singling out `inv` it's just that we try to be as exact as we can.

**Comment by stevengj** [comment]
> It's not about singling out `inv` it's just that we try to be as exact as we can.

We could also define exactly rounded versions of `exp`, `sqrt`, and many other math functions, but we don't.  So in that sense we are singling out `inv` here.

I guess your argument is that if we have to explicitly define a method for irrational types, then we usually try to be as accurate as we can.  But in fact we don't always do that.  For example, we don't guarantee exact rounding for `pi + e` or similar, even though we have a specialized `+` method for two irrationals.

**Comment by arnavs** [comment]
I opened PR https://github.com/JuliaLang/julia/pull/31068/files to add the following to `base/irrationals.jl`:

```
# inv
inv(x::AbstractIrrational) = 1/x
@test inv(π) ≈ 0.3183098861837907
@inferred inv(π)
```

In terms of accuracy, I agree that it would be ideal for us to implement this in a full-precision way. But, I think defaulting to `1/x` is perfectly reasonable/intuitive behavior. I also think that if people need extremely high accuracy, they'll probably be taking their own precautions for it.
