### ISSUE TITLE
Markdown latex conversion for tilde (~) incompatible with XeLaTeX

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/julia#30894]
On Julia v1.1.0:

```julia
julia> using Markdown

julia> Markdown.latex(Markdown.parse("Hello `~`"))
"Hello \\texttt{{\\sim}}\n\n"
```

which XeLaTeX can't parse. @ChrisRackauckas proposed outputting 

```
\textt{$\sim$}
```

instead

Re: https://github.com/mpastell/Weave.jl/issues/150

**Comment by simonbyrne** [comment]
Typesetting tildes [is one of the hardest things to do in LaTeX](https://tex.stackexchange.com/questions/312/correctly-typesetting-a-tilde).

`$\sim$` will look a bit odd (it is usually wide, and in a different font. I think the technically correct option is `\textasciitilde{}`, but for some reason the default Computer Modern font makes it really high.

For paths and URLs you can use the `\url` from the `url` or `hyperref` packages, but it would be difficult to get that to work.
