### ISSUE TITLE
dirname and @__DIR__ do not behave like bash, but pwd does

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#30891]
a trailing slash is ignored by bash but not julia.  intentional?

```
julia> dirname("/bar/foo")
"/bar"

julia> dirname("/bar/foo/")
"/bar/foo"

shell> dirname /bar/foo
/bar

shell> dirname /bar/foo/
/bar
```

relatedly, a trailing slash is added by julia, but not bash:

```
julia> @__DIR__
"/groups/scicompsoft/home/arthurb/projects/genie/screen/hek/src/"

shell> pwd
/groups/scicompsoft/home/arthurb/projects/genie/screen/hek/src
```

the above is all internally consistent in julia and kind of makes sense (dirs end in slash, files don't).  but then julia's `pwd` is not consistent (with `@__DIR__`) as it omits the trailing slash:

```
julia> pwd()
"/groups/scicompsoft/home/arthurb/projects/genie/screen"
```

why choose to behave like bash for `pwd` but not `dirname` or `@__DIR__` ?

`pwd` and `@__DIR__` both return directories, and so should both either add a trailing slash or not.

**Comment by musm** [comment]
So this is because in a REPL `__source__.file` returns nothing, i.e. `""` so then  `abspath("")` adds the current directory since it converts everything to an absolute path

**Comment by stevengj** [comment]
It is not 100% clear to me what the desired behavior is here.

The POSIX `dirname` function in `libc` also ignores the trailing slash:
```
julia> unsafe_string(ccall(:dirname, Cstring, (Cstring,), "/foo/bar/"))
"/foo"
```
In particular, the [POSIX `dirname` docs say](https://www.unix.com/man-page/POSIX/3posix/dirname/) that `Trailing '/' characters in the path are not counted as part of the path.`.
You can also see this explicitly in the [musl implementation](https://github.com/ifduyue/musl/blob/b4b1e10364c8737a632be61582e05a8d3acf5690/src/misc/dirname.c).  glibc (implemented [here](https://github.com/bminor/glibc/blob/7628a1b05adb1e4c6857b87c6f8b71a1d0b1d72c/misc/dirname.c)) has an [explicit testcase for this](https://github.com/bminor/glibc/blob/7628a1b05adb1e4c6857b87c6f8b71a1d0b1d72c/misc/tst-dirname.c#L54)

However, Python 3.7.2 is similar to Julia's current behavior, and does *not* ignore trailing slashes:
```
>>> from os.path import dirname
>>> dirname("/foo/bar/")
'/foo/bar'
>>> dirname("/foo/bar")
'/foo'
```

**Comment by musm** [comment]
There's also the main inconsistency brought up by this issue that
`pwd` and `@__DIR__`  have different behaviors regarding the trailing  `/`

**Comment by stevengj** [comment]
Omitting the trailing slash for `@__DIR__` seems like a good idea, but it is mostly a cosmetic change.  Changing the behavior of `dirname` requires more thought.

**Comment by tkf** [comment]
FYI it seems Python's [`pathlib`](https://docs.python.org/3/library/pathlib.html) "fixed" the behavior:

```pycon
>>> from pathlib import Path
>>> Path("/foo/bar/")
PosixPath('/foo/bar')
>>> Path("/foo/bar")
PosixPath('/foo/bar')
```

**Comment by oxinabox** [comment]
related: https://github.com/JuliaLang/julia/issues/25973

**Comment by stevengj** [comment]
@oxinabox, that's an unrelated issue.  `realpath` only works for paths that actually exist, whereas `dirname`'s behavior has nothing to do with whether the path exists on the filesystem.

**Comment by StefanKarpinski** [comment]
IIRC, I intentionally matched Python's behavior on this. However, I'm not sure if it's the right behavior. It's a bit bizarre that `/foo/bar` and `/foo/bar/` refer to the same thing if it exists and is a directory, yet `dirname` of them gives different results. We might be able to get away with changing this at this early stage in the game since there's far less of a vast ecosystem of scripts out there that may rely on the current behavior. We might want to audit behaviors of these kinds of operations based on that principle.

**Comment by bjarthur** [comment]
maybe we just tag this with a 2.0 milestone and think about i later?

**Comment by StefanKarpinski** [comment]
Marking to discuss on this week's triage call.

**Comment by StefanKarpinski** [comment]
Triage says: leave `dirname` alone and make `@__DIR__` return the directory without the slash.

**Comment by stevengj** [comment]
Should `@__DIR__` be fixed by changing `abspath("")` to no longer append a slash?  i.e. change the definition to:
```jl
abspath(a::String) = normpath(isabspath(a) ? a : isempty(a) ? pwd() : joinpath(pwd(),a))
```
?

**Comment by musm** [comment]
what about 
https://github.com/JuliaLang/julia/issues/30891#issuecomment-458812669

**Comment by musm** [comment]
This is a little tangential but currently `tempdir()` returns the temporary directory **with** a trailing slash.
