### ISSUE TITLE
`if true [] else nothing end` is invalid but `if false nothing else [] end` is valid?

### ISSUE THREAD

**Issue by virtualgraham** [JuliaLang/julia#30890]
Im using Julia version 1.0.3 on 64bit linux

`if true [] else nothing end` results in 

> ERROR: syntax: space before "[" not allowed in "true ["

and `if false nothing else [] end` works fine

Shouldn't both of these work, or at least shouldn't they both throw the same error?

the workaround is:

`if true Vector([]) else nothing end`

**Comment by abraunst** [comment]
`true []` is confused with `T[]`. Simpler workaround:

```if true; [] else nothing end```

**Comment by StefanKarpinski** [comment]
However, space is not allowed before brackets when indexing:
```jl
julia> true []
ERROR: syntax: space before "[" not allowed in "true ["
```

**Comment by JeffBezanson** [comment]
Right; `true[]` is valid indexing, and spaces aren't allowed there, but `else[]` is not indexing since `else` is a keyword, so that's unambiguous.
