### ISSUE TITLE
Lots of Segmentation Faults in 1.1.0 on OSX

### ISSUE THREAD

**Issue by ianfiske** [JuliaLang/julia#30935]
I have a fresh install of 1.1.0 on a Mac.  I installed from the official binary on the Julia downloads page.  Many different actions are causing segmentation faults. One such example is trying to do `versioninfo()` here:

[julia-version-numbers-in-prompts] added manually for clarity
```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia [1.1.0]> versioninfo()

signal (11): Segmentation fault: 11
in expression starting at no file:0
_platform_memmove$VARIANT$Haswell at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 902097 (Pool: 901884; Big: 213); GC: 0
[1]    45527 segmentation fault  julia
```

To help debug, here's the `versioninfo()` from the earlier v1.0.3:

```
julia [1.0.3]> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by ViralBShah** [comment]
Something seems strange. You should have libLLVM-6.0.1. Do you have some LD_LIBRARY_PATH type thing? I wonder if we should print these environment variables in `versioninfo()`.

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by ViralBShah** [comment]
Any LD_LIBRARY_PATH?

**Comment by ianfiske** [comment]
Nope:
```
 $ echo $LD_LIBRARY_PATH     

```
returns nothing.

**Comment by mbauman** [comment]
What's in your startup file?

**Comment by ianfiske** [comment]
None -- I've already tried commenting out the entire contents of my startup file.

**Comment by ViralBShah** [comment]
Can we force openblas to use Nehalem kernels?

**Comment by ianfiske** [comment]
@ViralBShah Is that something I can try?  Not sure if your question was directed to me.

**Comment by ianfiske** [comment]
I tried
```
➜  ~ julia -C nehalem
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DataFrames
julia(65442,0x7fffa81cc380) malloc: *** error for object 0x7fe402c00400: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
LLVM ERROR: starting new .cfi frame before finishing the previous one
```

**Comment by Keno** [comment]
```
julia [1.1.0]> versioninfo()
```
Out of curiosity, did you edit this manually, or are you using one of the prompt hooks (which might indicate some non-standard code somewhere). FWIW, I don't see this locally on my mac.

**Comment by ianfiske** [comment]
@Keno Apologies I should have noted that was a manual edit.  I did that to emphasize the version that worked vs not.

**Comment by ianfiske** [comment]
@mbauman Thanks for the suggestion -- already tried that one too.

Wondering if I might need to build the debug version of Julia as mentioned in the manual to get a more detailed stacktrace?

**Comment by ianfiske** [comment]
I'm not sure if this is related, but:

I'm trying to compile Julia from source to see if I hit the same issue as above.  However, the compilations hangs for hours at "Generating precompile statements...".  My CPU doesn't show that any work is being done.  I've hit the same issue with downloading the source tarball and also using the git repo source directly.

**Comment by KristofferC** [comment]
You can add a `print(s)` under the line at

https://github.com/JuliaLang/julia/blob/a94f3d19cdd7e42fcd20f27dd72013d56c751cca/contrib/generate_precompile.jl#L104

to get some debug output for the precompilation process. It has been known to deadlock if bad things happen during that step of the build.

**Comment by timholy** [comment]
FYI you can skip that step with `make JULIA_PRECOMPILE=0`. Might be enough to get something off the ground, from which point it may get easier to narrow in on the source of trouble.

**Comment by ianfiske** [comment]
Thank you, @timholy.  That helped me to compile Julia.  However, my compiled version still gives segfaults:

```
➜  julia git:(80516ca202) ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
_platform_memmove$VARIANT$Haswell at /usr/lib/system/libsystem_platform.dylib (unknown line)

atexit hook threw an error: ReadOnlyMemoryError()
signal (11): Segmentation fault: 11
in expression starting at no file:0
_platform_memmove$VARIANT$Haswell at /usr/lib/system/libsystem_platform.dylib (unknown line)
Allocations: 916640 (Pool: 916482; Big: 158); GC: 0
[1]    61851 segmentation fault  ./julia
```

Maybe a `make debug` build will help isolate the issue?

**Comment by ianfiske** [comment]
While I'm waiting on approval from my IT for whitelisting, do any Julia devs know why my anti-virus would report Julia as a threat?  The specific behavior mentioned is a "StackPivot".  Just wondering if this is an indication of some improper memory handling (not malicious I'm sure).

**Comment by Keno** [comment]
It's likely detecting our stack switching code which is part of the asynchronous I/O system.

**Comment by StefanKarpinski** [comment]
Is there a way to register well-known, non-malicious programs with antivirus companies? We could register each official Julia binary if that would prevent this sort of thing from happening?

**Comment by ViralBShah** [comment]
I assume that if enough customers whitelist, then the AV companies receive that information. Good to know if such a thing is possible.

**Comment by ianfiske** [comment]
Not sure if this is a definite fix, but do the Julia executables have "all the proper attributions for application publisher, name, copyright, and if at all possible - sign your executables" as suggested in https://www.reddit.com/r/Cylance/comments/7rb6co/out_of_61_detectors_only_cylance_flags_my_program/?

**Comment by ianfiske** [comment]
This is now fixed for me (and hopefully other users at my company).  I'll leave it open for Julia devs to decide if work is needed, working with AV vendors.  Or maybe just an update to the docs warning users that segfaults might indicate antivirus issues?

**Comment by Tokazama** [comment]
I've been running into this issue with the nightly builds. It just segfaults and blocks it. Never an issue with official releases and my University has cylance on all their computers. I'm confident my University isn't aware of Julia and white listing releases because I once tried something crazy on my computer which segfaulted Julia and had to contact IT to unblock it.

**Comment by ViralBShah** [comment]
@staticfloat or @ararslan might be able to tell us for sure whether nighties are signed the same as releases. I suspect they are not.

**Comment by ViralBShah** [comment]
Perhaps this needs to get documented somewhere. Maybe the FAQ?

**Comment by staticfloat** [comment]
The nightlies are signed exactly the same as the releases.  Most likely your antivirus triggers on some code within Julia that seems "suspicious", but it has whitelists for the release versions; the nightlies are different files (obviously) and they hash to a different value, so they don't get the benefit of the whitelist, despite the fact that they are signed.

You can verify that the `.app` bundle you're trying to run is properly signed by using the `codesign` tool.  To see it really fast, you can just run:

```
$ $ codesign -v --deep --verbose /Volumes/Julia-1.3.0-DEV-7a75753ab8/Julia-1.3.app
/Volumes/Julia-1.3.0-DEV-7a75753ab8/Julia-1.3.app: valid on disk
/Volumes/Julia-1.3.0-DEV-7a75753ab8/Julia-1.3.app: satisfies its Designated Requirement
```

Whereas to get more info, use `--display`:
```
$ codesign -v --deep --verbose --display /Volumes/Julia-1.3.0-DEV-7a75753ab8/Julia-1.3.app
Executable=/Volumes/Julia-1.3.0-DEV-7a75753ab8/Julia-1.3.app/Contents/MacOS/applet
Identifier=org.julialang.launcherapp
Format=app bundle with Mach-O universal (i386 x86_64)
CodeDirectory v=20200 size=281 flags=0x0(none) hashes=3+3 location=embedded
Signature size=8926
Authority=Developer ID Application: Julia Computing LLC (A427R7F42H)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 15, 2019 at 11:56:12 PM
Info.plist entries=15
TeamIdentifier=A427R7F42H
Sealed Resources version=2 rules=12 files=1136
Internal requirements count=1 size=188
```

**Comment by Tokazama** [comment]
This is what I get

```bash
$ codesign -v --deep --verbose /Applications/Julia-1.1.app
/Applications/Julia-1.1.app: a sealed resource is missing or invalid
file modified: /Applications/Julia-1.1.app/Contents/Resources/Scripts/main.scpt
```

**Comment by staticfloat** [comment]
What version of Julia are you using, exactly?  I thought you said you were using a nightly, but if that's the case, you're using a very old nightly.  ;)

**Comment by Tokazama** [comment]
Just downloaded the most recent releases and both the 1.1 and 1.3 have signatures.
```
$ codesign -v --deep --verbose --display /Applications/Julia-1.3.app
Executable=/Applications/Julia-1.3.app/Contents/MacOS/applet
Identifier=org.julialang.launcherapp
Format=app bundle with Mach-O universal (i386 x86_64)
CodeDirectory v=20200 size=281 flags=0x0(none) hashes=3+3 location=embedded
Signature size=8925
Authority=Developer ID Application: Julia Computing LLC (A427R7F42H)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=May 16, 2019 at 12:38:34 PM
Info.plist entries=15
TeamIdentifier=A427R7F42H
Sealed Resources version=2 rules=12 files=1140
Internal requirements count=1 size=188
```

 It still throws a stack pivot error as soon as I loaded up 1.3 though.

**Comment by staticfloat** [comment]
Yeah; so most likely your antivirus has a whitelist signature for 1.1, but doesn't have a whitelist signature for the 1.3 nightlies, which makes sense.

**Comment by Tokazama** [comment]
Thanks for trying. I'll try to push IT for a solution and come back here if I get any new information that may be of help to others.

**Comment by ViralBShah** [comment]
Is there anything further to do here? Can we close?

**Comment by KristofferC** [comment]
I think so, yes.
