### ISSUE TITLE
Flag to run Pkg command from command line

### ISSUE THREAD

**Issue by RatanRSur** [JuliaLang/julia#30943]
Something like:

`julia -P 'update; add foo'`

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/Pkg.jl/issues/168. You can use something like https://gist.github.com/fredrikekre/7b270cd8bfcb2d0f5fdfdaf87b519674 if you want it.

**Comment by KristofferC** [comment]
https://discourse.julialang.org/t/jlpkg-a-command-line-interface-to-pkg/24077/2
