### ISSUE TITLE
default to /usr/bin/curl for download on MacOS?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#30956]
I just ran into an issue where package installation failed on a student's Mac because they had a broken `curl` from an Anaconda installation (it was looking for some `libssl` that didn't exist).   I've seen related issues online from Homebrew installations — typical pattern seems to be that they have a custom `curl` installed via homebrew or conda, and then upgrade to a newer MacOS version that breaks this.

Although we obviously cannot deal with all possible broken systems, we might consider defaulting to `/usr/bin/curl`, at least on MacOS where that should be the `curl` installed by Apple and should be working, rather than whatever `curl` appears in the `PATH`.

i.e. the logic would be
```jl
if @static Sys.isapple() ? Sys.isexecutable("/usr/bin/curl") : false
    run(`/usr/bin/curl -g -L -f -o $filename $url`)
elseif Sys.which("curl") !== nothing
    ....
```

**Comment by vtjnash** [comment]
>  rather than whatever curl appears in the PATH.

I strongly disagree. If the user has intentionally tried to ensure that we don't use Apple's `curl`, we should never be trying to outwit them.

**Comment by bicycle1885** [comment]
This may possibly solve https://github.com/bicycle1885/CodecZlib.jl/issues/38#issuecomment-457280768.

**Comment by vtjnash** [comment]
OK, yeah, I guess it's weird, but I guess I see the point that `download` is itself already weird in that way
