### ISSUE TITLE
No longer able to insert newlines if input is syntactically valid

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#30963]
Consider a REPL input like
```
julia> if true
       # <- Cursor is here
       end
```
We used to allow either alt-enter or shift-enter to insert a newline there rather than accepting the input. That no longer seems to work for me (iTerm2/OS X), both now accept the input.

**Comment by JeffBezanson** [comment]
alt-enter works for me on linux; shift-enter doesn't.

**Comment by StefanKarpinski** [comment]
Cannot repro—maybe an iTerm2 change in a beta? (I use the stable version of iTerm)

**Comment by KristofferC** [comment]
FWIW, I don't think this has ever worked for me. I remember trying it multiple times over the time using Julia.

**Comment by Keno** [comment]
I have iTerm 3.2.7 on OS X 10.13.6. This definitely used to work on 0.3 for me, but that is broken now in both Terminal and iTerm. I wonder whether I broke some sort of OS-global setting.

**Comment by Keno** [comment]
So it works if I enable `Left option Key acts as: +Esc` in the iTerm settings. I wonder if I used to have that set, but it got lost in an upgrade somewhere.
