### ISSUE TITLE
SparseMatrixCSC does not support indexing by arrays of CartesianIndex

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#30981]
With Julia 1.1:

```
julia> using SparseArrays

julia> let r = [1, 2, 3]
           r[findall(r .> 2)]
       end
1-element Array{Int64,1}:
 3

julia> let r = sparse([1, 2, 3])
           r[findall(r .> 2)]
       end
1-element SparseVector{Int64,Int64} with 1 stored entry:
  [1]  =  3

julia> let r = [1 2; 3 4]
           r[findall(r .> 2)]
       end
2-element Array{Int64,1}:
 3
 4

julia> let r = sparse([1 2; 3 4])
           r[findall(r .> 2)]
       end
ERROR: MethodError: no method matching isless(::CartesianIndex{2}, ::Int64)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:70
  isless(::AbstractFloat, ::Real) at operators.jl:150
  isless(::Real, ::Real) at operators.jl:338
  ...
Stacktrace:
 [1] <(::CartesianIndex{2}, ::Int64) at ./operators.jl:260
 [2] getindex(::SparseMatrixCSC{Int64,Int64}, ::Array{CartesianIndex{2},1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/SparseArrays/src/sparsevector.jl:669
 [3] top-level scope at REPL[52]:2
```

**Comment by nicrummel** [comment]
I also am experiencing this issue

**Comment by StefanKarpinski** [comment]
Is this a bug or a missing feature?

**Comment by nicrummel** [comment]
> Is this a bug or a missing feature?

I think this is a missing feature.  Arrays can be accessed at multiple Cartesian Indices through an array, CartesianIndex[], to obtain the same results we would have to use a list comprehension with sparse arrays.

Example Code:
```
idx1 = CartesianIndex(1,2)
idx2 = CartesianIndex(3,4)
a = zeros(5,5)
a[idx1] = rand()
a[idx2] = rand()
@show a[[idx1,idx2]]
import SparseArrays
b = SparseArrays.SparseMatrixCSC(a)
@show b[[idx1,idx2]]
@show [b[i] for i in [idx1,idx2]]
```

Output:

<img width="1075" alt="Screen Shot 2019-03-13 at 4 25 25 PM" src="https://user-images.githubusercontent.com/42044062/54318813-21308f00-45ad-11e9-8b81-8c3a90bea28d.png">

**Comment by mbauman** [comment]
I still lean towards bug because this should work for all array subtypes but no matter.

**Comment by yurivish** [comment]
Yeah, I encountered it as a bug.

In my mind, there is a contract to the array interface by which any dimension can be indexed by an array of elements, each of which is a valid index.

**Comment by nicrummel** [comment]
I believe this would fix the bug/enhancement ...

<img width="1101" alt="Screen Shot 2019-03-14 at 1 45 58 PM" src="https://user-images.githubusercontent.com/42044062/54386841-8775ea00-465f-11e9-8dc0-271971a86818.png">

**Comment by mbauman** [comment]
These indexing definitions are fairly old — there could be some nice gains to be had by using some of the new tools we've developed over the past four years.  In this case, it'd just be simpler (and faster in some cases) to just do a `checkbounds(A, I)` at the top of the function.
