### ISSUE TITLE
Box necessary in closure?

### ISSUE THREAD

**Issue by EQt** [JuliaLang/julia#30980]
On my machine, at the moment I observe the strange effect that in a closure capturing a `Ref{Int}` is faster than accessing an ordinary `Int` because the latter will be boxed. So in the following example, `test_naive` will cause 100 M allocations waisting a lot of memory for nothing:
```julia
function loop(f::Function, n::Int)
    for i = 1:n
        f(i)
    end
end

function test_naive()
    local k::Int = Int(0)
    loop(100_000_000) do i::Int
        k += 1
    end
    return k
end

function test_ref()
    local k::Ref{Int} = Ref{Int}()
    loop(100_000_000) do i::Int
        k[] += 1
    end
    return k[]
end
```
(you can see the boxing by analyzing `@code_warntype test_naive()` )
Is there a particular reason for that? If so, this behavior should be documented, please.

I am running
```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276. And this seems to be one of the very hard case. The type stability of k is not possible to be known before type inference.

**Comment by JeffBezanson** [comment]
A further issue here is that `Box` is unspecialized. We could potentially use a `RefValue{T}` instead of `Box` when the type of a captured variable is declared, as it is here. (Note the type declaration here still does provide a speedup; without it the performance is even worse.)
