### ISSUE TITLE
Issue when Converting object of Type day to year

### ISSUE THREAD

**Issue by Erisme6** [JuliaLang/julia#30999]
Hi,

I think I am having a bug when I want to convert number of days between 2 dates into years:
I have:
DateFinObservation = Dates.Date(2008,12,31)
DateNaiss = Dates.Date.(t.DateNaissance,"mm/dd/yyyy")

test= DateFinObservation - DateNaissance    #will give me number of days between 2 dates in type days
then if I want to make
test2=Dates.year(test)  # I have error message MethodError : no method matching +(::Day,::Int64)

Can you please help?

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by Erisme6** [comment]
forgot to add screenshot
![julia issue](https://user-images.githubusercontent.com/47162055/52437631-614fae00-2ae5-11e9-9b25-735a4cf0d0cc.png)

**Comment by StefanKarpinski** [comment]
GitHub isn't for questions. If you want an answer to your question, post it on discourse.
