### ISSUE TITLE
Dispatch on abstract parametric Varargs functions

### ISSUE THREAD

**Issue by cnaak** [JuliaLang/julia#30994]
Suppose one wants to provide a `Varargs` method to a function `P` that has a `Tuple{Varargs}` definition:

```julia-repl
julia> P(A::Tuple{Vararg{<:Real}}) = promote(A...)
P (generic function with 1 method)

julia> P(A::T...) where T<:Real = promote(A...)
P (generic function with 2 methods)

```

In Julia-1.0.3, the `Tuple{Vararg}` method is dispatched for a tuple of mixed types (all `<:Real`) argument:

```julia-repl
julia> P( (1, 2.0) )
(1.0, 2.0)

```

However, the `Varargs` method is not dispatched for mixed typed arguments (despite all `<:Real`):

```julia-repl
julia> P(1, 2.0)
ERROR: MethodError: no method matching P(::Int64, ::Float64)
Closest candidates are:
  P(::T<:Real...) where T<:Real at REPL[2]:1
Stacktrace:
 [1] top-level scope at none:0

```

Supposedly it wants all arguments to be of the _same_ type `T` (a condition that wasn't enforced for dispatching the `Tuple{Varargs}` method) which doesn't entirely make sense since `T` was declared to be a subtype of an abstract type.

Moreover, the following syntax (which tries to mimic the Tuple argument method definition) is invalid in julia-1.0.3:

```julia-repl
julia> P(A<:Real...) = promote(A...)
ERROR: syntax: "A <: Real..." is not a valid function argument name

```

It seems that a mechanism for specifying whether all arguments of a `Varargs` function should be of the _same type_ of simply _equally subtypes_ of a given abstract type is missing in the language, since either behavior might be desired.

**Comment by JeffBezanson** [comment]
This is due to the special "diagonal rule". The signature you want can be written as
```
P(A::Vararg{<:Real}) = ...
```


> to be of the _same_ type `T` ...  which doesn't entirely make sense since `T` was declared to be a subtype of an abstract type.

It does make sense. `T` can be any concrete subtype of `Real`, of which there are many.

**Comment by cnaak** [comment]
Thank you!

It would be nice to include the signature `P(A::Vararg{<:Real}) = ...` in the Julia Documentation (possibly in the [Functions.Varargs](https://docs.julialang.org/en/v1/manual/functions/#Varargs-Functions-1) section).

Best regards!

**Comment by timholy** [comment]
There's nothing specific to `Vararg` about this, the same is true for `foo(x::T, y::T) where T<:Real`. Covered [here](https://docs.julialang.org/en/v1/manual/methods/#Parametric-Methods-1), and in gory detail [here](https://docs.julialang.org/en/v1/devdocs/types/#Diagonal-types-1).

It is hard to find the right balance between conciseness and making it easy to find stuff. If you have a specific suggestion for improvement, by all means please do submit changes for consideration. See https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation, and you can even make small changes directly in your browser: https://help.github.com/articles/editing-files-in-your-repository/.
