### ISSUE TITLE
BUG: unexpected tail of write(::TTY, ::UInt8)

### ISSUE THREAD

**Issue by cihga39871** [JuliaLang/julia#31003]
I found a bug when execute the following code.
```julia
String([0x32])
#> "2"

write(stdout, 0x32)
#> 21
```
The result should be 2, rather than 21. It happens when write `UInt8` to `stdout` or `stderr`.

It may be a problem of `TTY` rather than `write(::IO, ::UInt8)`, because the following output is correct.
```julia
f = "tmpfile"
write(f, 0x32)
readlines(f)
#> 1-element Array{String,1}:
#> "2"
```

My julia version info:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by Keno** [comment]
```
julia> write(stdout, 0x32);
2
```
Are you sure you're not just seeing the return value of the write on the same line because you're using the REPL?

**Comment by cihga39871** [comment]
Thank you, Keno. It is my fault. BTW, why the behavior of write(::TTY, UInt8) differs from others?
