### ISSUE TITLE
make JULIA_DEPOT_PATH work like JULIA_LOAD_PATH?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#31002]
I'm writing long-overdue docs for how `JULIA_LOAD_PATH` is expanded to populate `LOAD_PATH` (the current docs are woefully inaccurate at this point) and I noticed that `JULIA_DEPOT_PATH` doesn't do the same "empty path means insert the default" thing that `JULIA_LOAD_PATH` does. I really think it should basically for the reasons given [here](https://github.com/JuliaLang/julia/issues/29513#issuecomment-459400287). All the same arguments apply to `JULIA_DEPOT_PATH`. Technically this is a breaking change, but I think it's a good change and I strongly doubt anyone is relying on the current behavior since most people don't seem to understand what the depot path is or do anything to change it in the first place.

**Comment by mgkuhn** [comment]
I agree. The behavior that an empty entry after splitting on the separator is expanded to the default value is already well established in other tools that take search paths in environment variables, most notably [TeX's TEXINPUT variable](https://linux.die.net/man/1/tex), and has withstood the test of time.

Regarding the alternative interpretation of an empty entry as the current working directory, this [POSIX sh](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03) behavior is actually discouraged from being used by the POSIX standard: “A zero-length prefix is a legacy feature that indicates the current working directory. It appears as two adjacent <colon> characters ( "::" ), as an initial <colon> preceding the rest of the list, or as a trailing <colon> following the rest of the list. A strictly conforming application shall use an actual pathname (such as .) to represent the current working directory in PATH.”

**Comment by StefanKarpinski** [comment]
All good points. I was not aware of TEXINPUT using the same convention but it makes sense as a convention. I’m inclined to go ahead with this and see if it breaks PkgEval when we tag 1.2-rc1 or if anyone complains. My guess is no on both counts. Will wait for assent from triage.

**Comment by StefanKarpinski** [comment]
Closed by https://github.com/JuliaLang/julia/pull/31009.
