### ISSUE TITLE
Constructing `CartesianIndices` from `CartesianIndex` range

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#31030]
I was expecting a rectangular region with top left corner at (1,2) and bottom right corner at (4,5). Instead what I get is a rectangular region `1:4 x 1:4`:

```julia
start  = CartesianIndex(1,2)
finish = CartesianIndex(4,5)

region = CartesianIndices(start:finish)
4×4 CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}:
 CartesianIndex(1, 1)  CartesianIndex(1, 2)  CartesianIndex(1, 3)  CartesianIndex(1, 4)
 CartesianIndex(2, 1)  CartesianIndex(2, 2)  CartesianIndex(2, 3)  CartesianIndex(2, 4)
 CartesianIndex(3, 1)  CartesianIndex(3, 2)  CartesianIndex(3, 3)  CartesianIndex(3, 4)
 CartesianIndex(4, 1)  CartesianIndex(4, 2)  CartesianIndex(4, 3)  CartesianIndex(4, 4)
```

Could you please clarify the usage? The expected result I have in mind is obtained with:

```julia
 CartesianIndices(ntuple(i -> start[i]:finish[i], 2))
```

cc: @timholy

**Comment by vchuravy** [comment]
`region = CartesianIndices((start:finish,))` should do the trick. 

Please ask usage questions on discourse or Slack.

**Comment by juliohm** [comment]
But that is the expected syntax for it @vchuravy ? Why do we need an extra comma there?

**Comment by vchuravy** [comment]
Please don't `@` people unecessarily. 

From how I understand it the first version creates an CartesianIndices from the axes of what is being passed to it and the second uses a set of axes given to it. They call different methods. Trips me up sometimes as well.

**Comment by juliohm** [comment]
I opened the issue to discuss the possibility of having the syntax above behave as we expect? Is there a downside in making
```julia
CartesianIndices(start:finish)
```
behave specially? That is, not as an object from which the axes are extracted, but as the axes directly?

**Comment by yurivish** [comment]
This is another simpler way to say it:

```
julia> start  = CartesianIndex(1,2)
CartesianIndex(1, 2)

julia> finish = CartesianIndex(4,5)
CartesianIndex(4, 5)

julia> start:finish
4×4 CartesianIndices{2,Tuple{UnitRange{Int64},UnitRange{Int64}}}:
 CartesianIndex(1, 2)  CartesianIndex(1, 3)  CartesianIndex(1, 4)  CartesianIndex(1, 5)
 CartesianIndex(2, 2)  CartesianIndex(2, 3)  CartesianIndex(2, 4)  CartesianIndex(2, 5)
 CartesianIndex(3, 2)  CartesianIndex(3, 3)  CartesianIndex(3, 4)  CartesianIndex(3, 5)
 CartesianIndex(4, 2)  CartesianIndex(4, 3)  CartesianIndex(4, 4)  CartesianIndex(4, 5)
```

**Comment by juliohm** [comment]
That is great Yuri!
