### ISSUE TITLE
Kronecker product symbol not displayed in PDF of the manual

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#31048]
<img width="1031" alt="screenshot 2019-02-11 at 21 32 27" src="https://user-images.githubusercontent.com/1692009/52613881-8e34f580-2e44-11e9-8331-5f7210e34b2b.png">

https://github.com/JuliaLang/julia/blob/master/doc/src/manual/mathematical-operations.md#vectorized-dot-operatorsid-man-dot-operators

**Comment by simonbyrne** [comment]
Also ticks are missing from the table:
<img width="563" alt="screenshot 2019-02-11 at 21 36 18" src="https://user-images.githubusercontent.com/1692009/52614011-187d5980-2e45-11e9-9c17-b5babfc8fb4a.png">
https://github.com/JuliaLang/julia/blob/master/doc/src/manual/integers-and-floating-point-numbers.md

**Comment by simonbyrne** [comment]
And the `xor` symbol is missing:
<img width="237" alt="screenshot 2019-02-11 at 21 38 09" src="https://user-images.githubusercontent.com/1692009/52614080-58dcd780-2e45-11e9-9de2-892c22223a67.png">

**Comment by fredrikekre** [comment]
Duplicate of https://github.com/JuliaDocs/Documenter.jl/issues/803?

**Comment by StefanKarpinski** [comment]
Also, I would argue that `Bool` is unsigned, although it's not `<: Unsigned` so maybe that's confusing.

**Comment by mortenpi** [comment]
This can be closed. It was fixed quite a while back when we upgraded to Documenter 0.23.
