### ISSUE TITLE
Embedding test failures on FreeBSD CI

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#31045]
Examples:
* https://build.julialang.org/#/builders/68/builds/2700
* https://build.julialang.org/#/builders/68/builds/2702

Looking over the recent builds in https://build.julialang.org/#/builders/68, it appears this is only happening on the FreeBSD 12.0 worker, not the 11.2 worker.

**Comment by ararslan** [comment]
Something to note that @iblis17 found: FreeBSD 12.0 uses the LLVM project linker as `ld`, whereas 11.2 is still using GNU `ld`.

**Comment by staticfloat** [comment]
It would be helpful if someone could ssh in and take a look at the binary object itself.

**Comment by ararslan** [comment]
I can reproduce the failure locally on 12.0 as well as the non-failure on 11.2. On 12.0, `nm` showed the function that `ccall` couldn't find. I'll try `readelf` and whatever else on it the next time I boot into that partition.

**Comment by iblis17** [comment]
I can upload my binary, can it be read from Linux's `readelf`, `nm`?

**Comment by staticfloat** [comment]
I have a FreeBSD-compatible readelf and nm so you can upload it as well.

**Comment by iblis17** [comment]
https://gist.github.com/iblis17/d7147de8965174b1fd815507ad570076

**Comment by iblis17** [comment]
The first failed test case is this:

https://github.com/JuliaLang/julia/blob/300a336f7d7fcfb0964190d816f7cc9c857fb065/test/embedding/embedding.c#L103-L113

output:
```
ccall: could not find function my_c_sqrt
```

**Comment by iblis17** [comment]
but I can get it from `nm`:
```
└─[iblis@Arondight]% nm embedding | grep my_c_sqrt
0000000000202390 T my_c_sqrt
```
`readelf`:
```
└─[iblis@Arondight]% readelf -a embedding | grep my_c
    72: 0000000000202390    20 FUNC    GLOBAL DEFAULT   14 my_c_sqrt
```
