### ISSUE TITLE
Concatenating array and empty array fails with `DimensionMismatch`

### ISSUE THREAD

**Issue by StevenWhitaker** [JuliaLang/julia#31044]
I am confused at why `cat` treats empty arrays differently depending on their dimensions.
```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

julia> cat(rand(2,3), zeros(0,0), dims = 1)
ERROR: DimensionMismatch("mismatch in dimension 2 (expected 3 got 0)")
Stacktrace:
 [1] cat_shape(::Tuple{Bool}, ::Tuple{}, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}) at .\abstractarray.jl:1367
 [2] _cat_t(::Int64, ::Type, ::Array{Float64,2}, ::Vararg{Any,N} where N) at .\abstractarray.jl:1387
 [3] #cat_t#103(::Int64, ::Function, ::Type{Float64}, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N} where N) at .\abstractarray.jl:1384
 [4] (::getfield(Base, Symbol("#kw##cat_t")))(::NamedTuple{(:dims,),Tuple{Int64}}, ::typeof(Base.cat_t), ::Type{Float64}, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N} where N) at .\none:0
 [5] _cat(::Int64, ::Array{Float64,2}, ::Vararg{Array{Float64,2},N} where N) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\sparsevector.jl:1066
 [6] #cat#104(::Int64, ::Function, ::Array{Float64,2}, ::Vararg{Any,N} where N) at .\abstractarray.jl:1511
 [7] (::getfield(Base, Symbol("#kw##cat")))(::NamedTuple{(:dims,),Tuple{Int64}}, ::typeof(cat), ::Array{Float64,2}, ::Vararg{Any,N} where N) at .\none:0
 [8] top-level scope at none:0

julia> cat(rand(2,3), zeros(0,3), dims = 1)
2×3 Array{Float64,2}:
 0.166562  0.872139  0.288845
 0.456852  0.45644   0.605707
```
In the first case, I am concatenating a matrix with nothing (and I mean nothing, not `nothing`), and it fails. In the second case, I am concatenating a matrix with nothing, and it works how I would expect.

I guess the underlying question is does it make sense for an empty array to have dimension? In my mind it makes more sense for an empty array to act kind of like `LinearAlgebra.I`, where the "dimension" of the empty array is whatever it needs to be for the operation to make sense. (You could say that concatenating with nothing is like applying an identity operator.)

To give some context, I have a function where it is logically valid for one of the input arrays to be empty; however, this results in an empty intermediate array that needs to be concatenated with a 2D array, resulting in the (unexpected) error.

**Comment by simonbyrne** [comment]
> I guess the underlying question is does it make sense for an empty array to have dimension?

Personally, I tend toward yes, and we are somewhat consistent with this, e.g.
```
julia> sum(zeros(0,5),dims=1) # sum up each column
1×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0

julia> sum(zeros(0,5),dims=2) # sum up each row
0×1 Array{Float64,2}
```

**Comment by StevenWhitaker** [comment]
I guess dimension makes sense when one considers that empty arrays are treated like non-empty arrays (i.e., they are the same type). I guess I was imagining that there should exist a subtype of `AbstractArray` (or whatever the appropriate supertype would be) that would be a generic empty array that would behave like `LinearAlgebra.I`, at least for concatenation. (I'm not sure what other use cases there would be, and I'm not sure what functions would return a generic empty array instead of a regular empty array with dimension, so it's probably not a good idea.)

Here's (a simplified version) of my code that instigated this thread:
```julia
using Distributions
function foo(
  y, # 2D array
  dists # 1D array of Distributions
)
  N = size(y, 2)
  D = length(dists)
  tmp = map(d -> rand(d, N), dists) # tmp is vector of length D, where each element is a vector of length N
  tmp2 = cat(tmp..., dims = 2) # converts tmp into a N by D array, where each column is an element of tmp
  q = cat(y, transpose(tmp2), dims = 1)
end
```
This works fine when `dists` is not empty, but if it is empty then `tmp` and `tmp2` are 1D empty arrays. It makes sense to me that `map` returns a 1D empty array, but `cat(tmp..., dims = 2)` should at least return a 2D `0x0` array because I am concatenating along the second dimension, implying that the output should have at least two dimensions. But that would still throw an error when computing `q`.

It seems the more I think about this the more I agree with the way it is currently implemented (except that I still think `cat(tmp..., dims = 2)` should return a 2D `0x0` array). I just feel like there should be a way to write my code without having to explicitly check for empty arrays...
