### ISSUE TITLE
@show displays unnecessary parentheses for nested structs

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#31065]
The display using `@show` for nested structs has parentheses, which seems like clutter to me.
I like the v0.6 behavior better.

```
struct Foo3 x::Int end
struct Foo2 x::Foo3 end
struct Foo1 x::Foo2 end

foo1 = Foo1(Foo2(Foo3(42)))
@show foo1.x
@show foo1.x.x
@show foo1.x.x.x
```
For Julia v0.6.4:
```
foo1.x = Foo2(Foo3(42))
foo1.x.x = Foo3(42)
foo1.x.x.x = 42
```
For Julia v0.7.0, v1.0.3, v1.1.0:
```
foo1.x = Foo2(Foo3(42))
(foo1.x).x = Foo3(42)
((foo1.x).x).x = 42
```

**Comment by inkydragon** [comment]
those code make the difference, and it is add by pr #24994 

https://github.com/JuliaLang/julia/blob/a03da7312e1494e81fd31f53af99ad4696762080/base/show.jl#L1123-L1126.

----

<details>
 <summary><strong>How to find this?</strong></summary>

```julia
julia> VERSION
v"0.6.4"

julia> struct Foo3 x::Int end
julia> struct Foo2 x::Foo3 end
julia> struct Foo1 x::Foo2 end
julia> foo1 = Foo1(Foo2(Foo3(42)))
Foo1(Foo2(Foo3(42)))

julia> @show foo1.x.x.x
foo1.x.x.x = 42
42
```

```julia
julia> VERSION
v"1.0.3"

julia> struct Foo3 x::Int end
julia> struct Foo2 x::Foo3 end
julia> struct Foo1 x::Foo2 end
julia> foo1 = Foo1(Foo2(Foo3(42)))
Foo1(Foo2(Foo3(42)))

julia> @show foo1.x.x.x
((foo1.x).x).x = 42
42

julia> @edit @show foo1.x.x.x
```

Then search `macro show` you will find `@show`'s definition.
https://github.com/JuliaLang/julia/blob/a03da7312e1494e81fd31f53af99ad4696762080/base/show.jl#L568-L572

have a look and test code in REPL
```
julia> sprint(Base.show_unquoted, :(foo1.x.x.x))
"((foo1.x).x).x"
```

search `show_unquoted` 
https://github.com/JuliaLang/julia/blob/a03da7312e1494e81fd31f53af99ad4696762080/base/show.jl#L763-L767

continue test
```
julia> Base.show_unquoted(stdout, :(foo1.x.x.x))
((foo1.x).x).x

julia> typeof(:(foo1.x.x.x))
Expr

julia> methods(Base.show_unquoted, (IO, Expr))
# 1 method for generic function "show_unquoted":[1] show_unquoted(io::IO, ex) in Base at show.jl:751
```

The same 
https://github.com/JuliaLang/julia/blob/a03da7312e1494e81fd31f53af99ad4696762080/base/show.jl#L765-L767

```julia
julia> Base.show_unquoted(stdout, :(foo1.x.x.x), 0,0)
((foo1.x).x).x
julia> methods(show_unquoted, (IO, Expr, Int, Int))
# 1 method for generic function "show_unquoted":[1] show_unquoted(io::IO, ex::Expr, indent::Int64, prec::Int64) in Base at show.jl:1096
```

and finally you find those code

https://github.com/JuliaLang/julia/blob/a03da7312e1494e81fd31f53af99ad4696762080/base/show.jl#L1114-L1128

</details>

**Comment by JeffBezanson** [comment]
Thanks! Before the `.` we should allow `.` expressions to be printed without parens. Care to make a PR for that?
