### ISSUE TITLE
Using a plain old `Pair` as a keyword argument

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#31060]
Julia allows the user to specify `Pair`s instead of keyword arguments, meaning that you can specify the details of a function call at run-time. This is great, but the syntax is limiting:

```
function foo(x; y = 5)
    println(y)
end
t = :y => 100
foo(0; :y => 5) # works
foo(0; t) # doesn't work
foo(0; t[1] => t[2]) # works 
```

It's odd that a `Pair` works but only if it is written out `foo(0, t[1] => t[2])`. 

Is this intentional? Would allowing this break current features? Would it be an opaque way to write code?

**Comment by pdeffebach** [comment]
This would be redundant with the use of `NamedTuple`s to specify keyword arguments. 

Maybe what's really needed is an easy way to convert an array of pairs to a named tuple (which doesn't need to exist in Base or standard library)

**Comment by JeffBezanson** [comment]
This is intentional. Passing "computed" keyword argument names like this is fairly rare, and many people want the syntax `f(; t)` to mean `f(; t=t)`, which comes up much more often.

**Comment by pdeffebach** [comment]
Thanks for the reply. 

Part of the motivation for this comes from this issue in DataFramesMeta: https://github.com/JuliaData/DataFramesMeta.jl/issues/117 . Though DataFramesMeta kind of abuses the keyword argument system and the way it inspects the syntax tree might make this evaluation impossible. 

You can close this, unless people have more ideas for how to programmatically work with keyword arguments of arbitrary names.

**Comment by simonbyrne** [comment]
you can splat a collection of pairs:
```
julia> foo(0; [t]...)
100
```

**Comment by pdeffebach** [comment]
That's good for me!

**Comment by pdeffebach** [comment]
Motivated by this I made a PR that was recently merged into NamedTupleTools: https://github.com/JeffreySarnoff/NamedTupleTools.jl/pull/5
