### ISSUE TITLE
Julia 1.1 silently exits

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/julia#31067]
Here is a MWE that leads Julia to silently exit:
```julia
run(`git clone https://github.com/mohamed82008/juliaexits`)
using Pkg
Pkg.activate("juliaexits")
Pkg.instantiate()

using Distributions, LinearAlgebra
A = rand(3, 3); A = Matrix{Real}(A + A' + 3I)
MvNormal(rand(3), A)
```

I am using a custom PDMats.jl. My best guess is that the error happens in this function https://github.com/mohamed82008/PDMats.jl/blob/pdmat_constr/src/pdmat.jl#L9.

**Comment by mohamed82008** [comment]
Can some reproduce this?

**Comment by andreasnoack** [comment]
Did you try with `--check-bounds=yes`?

**Comment by mohamed82008** [comment]
Yes, same result.

**Comment by mohamed82008** [comment]
Bump.

**Comment by mohamed82008** [comment]
Bump.

**Comment by tkluck** [comment]
@mohamed82008 sorry to hear you are running into this. I'm not a Julia maintainer, so I can't help you, but I can advice you that many people will be hesitant to clone + run code from a git repository in this way.

It's not overly paranoid to worry: after all, the Julia maintainers have commit access to this repository, and are able to upload Julia binaries. If those get compromised, that gives access to hundreds of thousands of systems, some of which process sensitive data.

Here's some other things you can do:
 - create a smaller MWE that can more easily be proofread
 - run julia under `gdb` and paste a backtrace (assuming the silent exit is a crash)

Hope that helps!

**Comment by mohamed82008** [comment]
Oh wow, that kind of defeats the purpose of Manifest files for bug reports. I understand the concerns. I will try to reduce this to a MWE. Thanks for your advice.

**Comment by knuesel** [comment]
I can reproduce this in a Docker container with Julia 1.1 (Julia segfaults).

In 1.6.1 the project cannot be instantiated (Arpack 0.3 fails to build), but it works after replacing it with Arpack 0.4 in the manifest and I get the following:

```
julia> using Distributions, LinearAlgebra
[ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]

julia> A = rand(3, 3); A = Matrix{Real}(A + A' + 3I)
3×3 Matrix{Real}:
 4.57667  1.09255  1.06262
 1.09255  4.08851  1.07791
 1.06262  1.07791  4.80418

julia> MvNormal(rand(3), A)
ERROR: StackOverflowError:

```

(no further lines in the error message)

**Comment by ViralBShah** [comment]
Please reopen if still an issue on current release.
