### ISSUE TITLE
AbstractRNG should be a broadcast scalar

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#31071]
As mentioned [on the mailing list](https://discourse.julialang.org/t/is-there-a-reason-a-mersennetwister-value-is-not-broadcastable/20774), we need a
```jl
Base.broadcastable(x::AbstractRNG) = Ref(x)
```
somewhere.

Not breaking since trying to a broadcast an RNG currently gives an error.

**Comment by JeffBezanson** [comment]
I think we have too many of these definitions already. At a certain point it's just better to be explicit. It's not obvious, for example, whether an RNG is iterable.

**Comment by stevengj** [comment]
> It's not obvious, for example, whether an RNG is iterable.

Why would an RNG be iterable?  This seems like one of those things that will never have a `length`.

**Comment by JeffBezanson** [comment]
It's just that an RNG is an obscure enough object that being explicit seems acceptable to me.

**Comment by stevengj** [comment]
My feeling is that every documented type that is unambiguously not a collection should implement `Base.broadcastable(x::Foo) = Ref(x)`
