### ISSUE TITLE
PCRE.ERROR_JIT_BADOPTION can be undefined 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#31081]
https://github.com/JuliaLang/julia/pull/30542 introduced a check `errno == ERROR_JIT_BADOPTION` which seemingly can be an undefined variable in some configurations (leading to https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/35)

```jl
> Base.PCRE.ERROR_JIT_BADOPTION
ERROR: UndefVarError: ERROR_JIT_BADOPTION not defined

> versioninfo()
Julia Version 1.2.0-DEV.321
Commit a03da7312e* (2019-02-14 05:43 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

And the added (commented out) test from the PR also fails:

```jl
> @test_throws ErrorException Base.PCRE.info(C_NULL, Base.PCRE.INFO_NAMECOUNT, UInt32)
Test Failed at REPL[5]:1
  Expression: (Base.PCRE).info(C_NULL, (Base.PCRE).INFO_NAMECOUNT, UInt32)
    Expected: ErrorException
      Thrown: UndefVarError
ERROR: There was an error during testing
```

cc @Keno

**Comment by Keno** [comment]
Is the error present in the pcre headers? If so are we failing to pick it up in the perl script?

**Comment by Keno** [comment]
Actually, are you perhaps running this on an older version of julia that doesn't have the corresponding change from that PR?

**Comment by StefanKarpinski** [comment]
The Julia version appears to be 1.2-DEV so that seems unlikely.

**Comment by KristofferC** [comment]
I posted the julia version but here it is again:

```
Julia Version 1.2.0-DEV.321
Commit a03da7312e* (2019-02-14 05:43 UTC)
```

I have the error in e.g. `julia/usr/include/pcre2.h` as 

```
#define PCRE2_ERROR_JIT_BADOPTION     (-45)
```

so perhaps we are not picking it up?

**Comment by Keno** [comment]
Yeah seems like it. Might be a windows issue?

**Comment by KristofferC** [comment]
The nightly windows seems to have it properly so I guess something is wrong with my local build :/

**Comment by Keno** [comment]
Did you ever figure out what the problem was?
