### ISSUE TITLE
"text/plain" vs "text/html" differences in MethodList

### ISSUE THREAD

**Issue by hamzaelsaawy** [JuliaLang/julia#31098]
Printing method lists in IJulia/"text/html" does not use the `where` clause on `v1.0.0`:

```julia
f(x::T) where {T<:Real} = 5
t = methods(f)
```
![image](https://user-images.githubusercontent.com/22927537/52924747-e48db280-32e2-11e9-9875-153626625bdc.png)

**Comment by JeffBezanson** [comment]
Fixed by #30472.
