### ISSUE TITLE
Imprecision of division operator

### ISSUE THREAD

**Issue by eulerkochy** [JuliaLang/julia#31107]
This is in reference to #28943 
- The problem can't entirely be bypassed by usage of `sinpi` or `cospi` , or user-made implementation of `tanpi` because of the imprecision of the division operator on multiples of `pi` which becomes a separate issue in itself.
![image](https://user-images.githubusercontent.com/33925317/53005041-66ebb300-3458-11e9-8a6d-1d27b06c9736.png)

- version info
![image](https://user-images.githubusercontent.com/33925317/53005702-c72f2480-3459-11e9-99c9-3f69262cc2f4.png)

**Comment by yuyichao** [comment]
This is not a bug, please ask usage questions on discourse.
