### ISSUE TITLE
It should be mentioned in the manual that Rationals are checked for overflow

### ISSUE THREAD

**Issue by jmichel7** [JuliaLang/julia#31143]
I looked in detail at the code for Rationals and it seems that they are in all circumstances checked for
overflow --- actually while reviewing the code I detected one test missing, which indeed allows:

```
julia> 1//typemin(Int)
-1//-9223372036854775808
```
but this should be easily fixable. 

I think it is be important to mention in the manual this safety of Rationals (and perhaps also mention the existence of the package `SaferIntegers`).

**Comment by Moelf** [comment]
@StefanKarpinski can you take a look and merge the PR, thx.
