### ISSUE TITLE
Refactorization of factorization.jl --- problems with StridedMatrix 

### ISSUE THREAD

**Issue by bsxfan** [JuliaLang/julia#3115]
`factorization.jl` is currently undergoing some maintenance (see #3089), but here is another problem that has not been mentioned there. For convenience when reading this, recall that:

    typealias StridedMatrix{T,A<:Array}   Union(Matrix{T} , SubArray{T,2,A})

I find both the documentation (Julia Manual) and code (factorzation.jl) is misleading w.r.t. StridedMatrix. Several in-place method signatures that suggest they handle StridedMatrix arguments, do not really do so (they crash). Mostly one does not notice this, because the in-place methods are invoked via a copy(), which converts SubArray to Matrix.

The Julia Manual claims:

"StridedVector and StridedMatrix are convenient aliases defined to make it possible for Julia to call a wider range of BLAS and LAPACK functions by passing them either Array or SubArray objects, and thus saving inefficiencies from indexing and memory allocation."

This is true only for matrices `M` such that `stride(M,1) ==1`. If a StridedMatrix with `stride(M,1)>1` should reach Julia's LAPACK wrapper methods, they crash (but mostly this does not happen due to copying).  In the BLAS case, sending a StridedMatrix with `stride(M,1)>1` to gemm_wrapper will invoke `generic_matmatmul()` rather than `BLAS.gemm!`.

Let's experiment with the example similar to the one in the manual (http://docs.julialang.org/en/latest/manual/arrays.html?highlight=subarray), which sends a SubArray to qr(). (Also see #3114 for a related problem).

    julia> G = sub(randn(4,2),1:2,1:2)
    2x2 SubArray of 4x2 Float64 Array:
       1.34744   0.250764
      -0.613167  0.365406
    julia> strides(G)
    (1,4) 

So `G` is a 2x2, BLAS/LAPACK-friendly `SubArray`. Notice that `SubArray` does provide a generalization of `Matrix`, because for a standard 2x2 `Matrix`, we would get: `strides(randn(2,2))==(1,2)`.

Now we also create a 2x2 `SubArray` which cannot be handled by BLAS/LAPACK: 

    julia> B = sub(randn(4,2),1:2:3,1:2)
    2x2 SubArray of 4x2 Float64 Array:
     -0.640821    -0.332439
     -0.00194563   0.418922
    julia> strides(B)
    (2,4)    

What happens if we send `G` or `B` to a matrix factorization? Well, it just copies the argument, thereby converting it to Matrix before doing the factorization, for example:

    qrfact{T<:BlasFloat}(A::StridedMatrix{T}) = qrfact!(copy(A))

This sort of defeats the whole prupose of having the StridedMatrix here.

Now let's try harder to send a SubArray to LAPACK. The signatures

    QR{T<:BlasFloat}(A::StridedMatrix{T}) = QR(LAPACK.geqrt3!(A)...)
    qrfact!{T<:BlasFloat}(A::StridedMatrix{T}) = QR(A)

suggest we can do so, but:

    julia> qrfact!(G)
    ERROR: no method QR(SubArray{Float64,2,Array{Float64,2},(Range1{Int32},Range1{In
    t32})},Array{Float64,2})

What has happened here is that `LAPACK.geqrt3!(G)` was in fact succesful, but has returned a SubArray, which cannot be accepted by the constructor `QR(LAPACK.geqrt3!(A)...)`, because the QR type cannot in fact contain SubArrayss---it contains standard Matrices: 

    type QR{S<:BlasFloat} <: Factorization{S}
        vs::Matrix{S}                     
        T::Matrix{S}             
    end

The behaviour of other factorizations is similar. I'm sure a bit of refactorization can generalize the factorization types to contain StridedMatrix rather than Matrix. But it still seems a bit funny that StridedMatrix serves its purpose only in the case stride(M,1)==1. I'm tempted to suggest that SubArrays with stride(M,1)>1 should have a different type.

**Comment by andreasnoack** [comment]
There is probably remaining issues with subarrays, but we should open specific issues about them as they are encountered. The specific issue qith QR has already been fixed.
