### ISSUE TITLE
feature request: roadmap to official conda julia binaries

### ISSUE THREAD

**Issue by kirk86** [JuliaLang/julia#31153]
Hi folks,
thanks for making julia great.
I was wondering if there's any discussion or idea on bringing official julia binaries to anaconda?
ATM there's only some binaries under the `conda-forge` channel but not the main `conda` one.
Those are only compiled with openblas. 
Bringing julia easy install in conda would be much appreciated since it will also resolve any issues with mkl library. 
MKL library has already been in conda for a while now and all deep learning frameworks are using it. When users install a DL framework mkl also gets installed as pre-requisite with everything else necessary.
This ease of usage and installation will allow ppl to test julia more often and report bugs and solutions probably to uncaught errors.

**Comment by ViralBShah** [comment]
I am sure you have seen the discussions here: https://github.com/conda-forge/julia-feedstock

**Comment by ViralBShah** [comment]
The main problem with MKL for us so far has been that SuiteSparse is GPL, and it is unclear whether SuiteSparse distributed with MKL is a licensing issue. 

BinaryBuilder which serves the binaries for Julia packages has many other libraries that depend on BLAS and LAPACK. So all of that would have to be made MKL compatible. Currently, even if Julia could use MKL, the moment you install Julia packages that need a BLAS, they will install OpenBLAS and there will be confusion once again.

The issue of competing BLAS libraries also exists when Julia users install python and matplotlib (for packages like PyPlots.jl) through miniconda, which might install MKL. So this all goes much beyond conda, unfortunately.

**Comment by tkf** [comment]
Conda has a metapackage called `nomkl` to [opt out MKL](https://docs.anaconda.com/mkl-optimizations/#uninstalling-mkl) (see also [Features](https://docs.conda.io/projects/conda-build/en/latest/source/features.html)).  So, I think in principle you can distribute a standard Julia binary with SuiteSparse depending on `nomkl` and also another binary that does not bundle SuiteSparse and is built with MKL.  Was this option considered before?

**Comment by kirk86** [comment]
> n principle you can distribute a standard Julia binary with SuiteSparse depending on `nomkl` and also another binary that does not bundle SuiteSparse and is built with MKL. Was this option considered before?

Very good point. If I may add, learning from python, if julia is to be targeting audience which require speed then offering julia with only blas compiled stuff doesn't hold as an argument of being fast compared to pure linear algebra operations against numpy for instance. Since numpy and python utilized mkl and as a user I don't have to install mkl or any other prerequisite on my system everything comes nicely packaged through conda.

@ViralBShah I understand the complication and that things are not as easy as they seem but this to me seems like a must if we ever want julia to gain in popularity. I'll draw a picture here from my painful experience fiddling around with cuda drivers but now we've reached to a point where as a user I don't have to anymore since I can simply install whichever version from conda and my DL frameworks will still work fine. This hassle free approach is an open invitation to people to try new stuff/frameworks/libraries out. If I had to spend days or hours compiling sth running into errors of missing libraries and whatnot probably that would have been an indicator not to try that new stuff out.

**Comment by ViralBShah** [comment]
@kirk86 I don't disagree with your point that having Julia in conda will reduce friction for the first time user. I suspect that while it makes it easy to get Julia itself, you will still need to use Julia's package manager to install Julia packages and binaries. With Pkg3 and BinaryProvider, I believe we have come a long way and users no longer need to compile things. 

@tkf I didn't know about the `nomkl` option. That is good to know - but perhaps the conda-forge people did know about it.

**Comment by ViralBShah** [comment]
Closing this since it's best to discuss this in the julia-feedstock repo on conda-forge.
