### ISSUE TITLE
_ZSt14__once_functor not located when attempting to embed on windows

### ISSUE THREAD

**Issue by Cyan-h** [JuliaLang/julia#31172]
I've been trying for a while to embed my julia program in a C wrapper on windows and i keep running into this same error no matter what i try. Ive been following the embedding example ([https://docs.julialang.org/en/v1/manual/embedding/index.html](url)) and basically, every time ive managed to compile the c program and run the .exe it gives an error saying "The procedure entry point _ZSt14__once_functor could not be located in the dynamic link library C:\Users\Cian\AppData\Locl\Julia-1.1.0\bin\LLVM.dll". I've done a dumpbin on the dll referred to in the error message and confirmed that the ZSt14 function isnt there. I've tried a few things such as alternative compilers and trying to use libjulia.dll from other languages (including python and C#) and even borrowing a friends laptop in case it was my own system environment causing it but nothing has helped. A more detailed account of my attempts to fix this so far are on my stackoverflow and discourse.julia posts here:
[https://stackoverflow.com/questions/54583487/entry-point-not-found-when-embedding-julia-in-c-with-gcc-on-windows](url)
[https://discourse.julialang.org/t/struggling-to-embed-julia-in-c/20861](url)

I've been trying to figure this out for a while, and ive even posted on stackoverflow and discourse.julia and havent gotten any responses so at this point im thinking maybe its a bug? Or at the very least if its my own idiocy causing this (and apologies for wasting your time if it is!) then somebody here should at least be able to point out what silly thing i'm doing. here's my versioninfo() output:

Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DIR = C:\Users\Cian\AppData\Local\Julia-1.1.0

Im using gcc 7.2.0 as built by MinGW-W64, and am compiling by running the following command in my MinGW64 shell:

gcc ccalltest.c -std=gnu99 -I'C:\Users\Cian\AppData\Local\Julia-1.1.0\include\julia' -DJULIA_ENABLE_THREADING=1 -L'C:\Users\Cian\AppData\Local\Julia-1.1.0\bin' -Wl,--stack,8388608 -ljulia -lopenlibm

Im on windows Version	10.0.17763 Build 17763. Ive attached the c code im attempting to compile (added .txt so i could share it here, i've changed it many ways during all my debugging attempts but this is the current code, at least), the dumpbin outputs i got for on LLVM.dll (mentioned in the error message) and libjulia.dll (in case thats relevant) and an export of my systeminfo in case my hardware is relevant to this issue.

[ccalltest.c.txt](https://github.com/JuliaLang/julia/files/2901643/ccalltest.c.txt)
[dump(LLVM).log](https://github.com/JuliaLang/julia/files/2901647/dump.LLVM.log)
[dump(libjulia).log](https://github.com/JuliaLang/julia/files/2901649/dump.libjulia.log)
[sysinfo.txt](https://github.com/JuliaLang/julia/files/2901655/sysinfo.txt)

Again, im sorry if this is just user error and it my own mistake but i've tried to check in as many normal programming forums as possible before posting here to make sure im not just making some silly obvious mistake.

Also, just while i'm here i want to say thanks to you guys for all your effort in developing this language. As a scientist by trade, having access to multithreaded high performance computing without having to build up years of c programming experience has been an absolute blessing and your language has allowed me to do some things in my research that id probably never have been able to pull off otherwise!

**Comment by vtjnash** [comment]
`gcc` is the wrong compiler/linker. you need to cross-compile everything for the x86_64-w64-mingw32 target

**Comment by Cyan-h** [comment]
Ok so to cross compile for that target i just need to prefix the call to gcc with the target architecture, correct? Ive attempted compilation again using the following command:

x86_64-w64-mingw32-gcc ccalltest.c -std=gnu99 -I'C:\Users\Cian\AppData\Local\Julia-1.1.0\include\julia' -DJULIA_ENABLE_THREADING=1 -L'C:\Users\Cian\AppData\Local\Julia-1.1.0\bin' -Wl,--stack,8388608 -ljulia -lopenlibm

and got the exact same error. Was this what you were suggesting or did i misunderstand? Also, as i said i didnt just try gcc. I started with gcc because its the compiler i already had on my laptop from my occasional dabbling with the C language but I also tried using visual studio following exactly the steps in the guide linked above and got the exact same error.

**Comment by skeetcha** [comment]
I have also gotten this same error and I was using mingw32. Is there something else that I'm missing?

**Comment by ulatekh** [comment]
I just got this while making a MinGW build for a completely different project (in this case, CMake). So it's probably a MinGW issue. There seems to be no public info about what the heck it could mean.

**Comment by vtjnash** [comment]
Probably that the wrong compiler snuck in somewhere for some C++ code

**Comment by vtjnash** [comment]
Closing as this doesn't seem like something we know how to fix for users configurations, and can't reproduce ourselves. Possibly also a version mismatch of some compiler libraries.
