### ISSUE TITLE
Julia show from repl not same as show from file when using ZSH

### ISSUE THREAD

**Issue by robertu94** [JuliaLang/julia#31170]
First of all thanks for all the hard work on Julia, I'm growing quite fond of it.

I find this to be an annoying bug.  If I type the following into the julia REPL:

```julia
a = [1 2 3; 4 5 6]
show(stdout, "text/plain", a)
```

I get output that looks like this:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> a = [1 2 3; 4 5 6]
2×3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> show(stdout, "text/plain", a)
2×3 Array{Int64,2}:
 1  2  3
 4  5  6
julia> 

```

But if I run it from a file with the same lines

```sh
$ julia /tmp/test.jl
```
I only get:

```
2×3 Array{Int64,2}:
 1  2  3
```

My concern is that the second line of the array isn't printed.  As far as I can tell, this only seems to effect ZSH.  I get "correct" output if I use bash, bourn shell, or fish.  I thought this was an issue with flushing output, so I tried sending calling `flush(stdout)`, but that doesn't seem to fix the issue. However If I add a line `print("\n")` then I get output I expect:

```
2×3 Array{Int64,2}:
 1  2  3
 4  5  6
```

I'm happy to add the `print("\n")`, but this seems like more like a hackish bug that would trip up users less familiar with shell buffering.

**Comment by jmkuhn** [comment]
`show()` doesn't append a newline to the value.  Run the following 3 lines in the REPL and from a file.
```
show("hi")
print("hi")
println("hi")
```
From the REPL you have
```
julia> show("hi")
"hi"
julia> print("hi")
hi
julia> println("hi")
hi

julia> 
```
Note that the first 2 don't have a blank line before the julia prompt.  The last does have a blank line before the prompt.  This is how the REPL indicates that the first 2 don't end in a newline but the last does.  When you run these from a file
```
$ julia /tmp/test.jl
```
you will get
```
"hi"hihi
```
Only the last will print a newline.  To get the newline you desire you could use
```
println(repr("text/plain", a))
```

**Comment by StefanKarpinski** [comment]
As indicated by @jmkuhn’s answer, this is not a bug and is the correct behavior.
