### ISSUE TITLE
Anonymous functions created in a function do not have distinct types

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#31181]
The types of the distinct anonymous functions created by the factory function should be different:
```jl
julia> function initialise(x)
           return i->x
       end
initialise (generic function with 1 method)

julia> x = initialise(1)
#5 (generic function with 1 method)

julia> y = initialise(2)
#5 (generic function with 1 method)

julia> typeof(x) == typeof(y)
true

julia> x(1)
1

julia> y(1)
2
```

**Comment by yuyichao** [comment]
So you are asking for type instability?

**Comment by yuyichao** [comment]
And to quote the argument in the discourse thread that you didn't mention.

> the two functions are actually different:
> So they should not be given the same name

Is not valid. This is exactly the property of closures like any other callable types you can create.

**Comment by dpsanders** [comment]
Apologies, I had not seen your reply when I posted the issue.

X-ref
https://discourse.julialang.org/t/distinguishing-anonymous-functions-inside-types/21216/6
