### ISSUE TITLE
Check Dependencies First when installing Julia from source

### ISSUE THREAD

**Issue by astrieanna** [JuliaLang/julia#3118]
Installing Julia from source takes a while. At any point during this first `make`, it could fail due to an unmet dependency. This is frustrating.

The README does seem to document all the dependencies. However, using it to make sure that you actually have all of them installed takes longer and is more frustrating than running `make` and interpreting the error message.

Having a script that runs first and checks that I have all the dependencies would be really nice. It would mean that when I walk away and leave it building, I won't come back to find that it got stuck a minute later because of a missing dependency.

**Comment by ViralBShah** [comment]
The recent BinaryBuilder work pretty much fixes this.
