### ISSUE TITLE
Subtyping of type variables and unions

### ISSUE THREAD

**Issue by BenChung** [JuliaLang/julia#31190]
Using the forall/exists justification for subtyping, the query

       (Tuple{T} where T <: Union{Int,Bool}) <: Union{Tuple{Int}, Tuple{Bool}}

should be true. This follows because `T` may take on `Int`, `Bool`, or `Union{Int,Bool}`, and we can find choices for the RHS that produce successful derivations for each instantiation:

       Tuple{Int} <: Tuple{Int}
       Tuple{Bool} <: Tuple{Bool}
       Tuple{Union{Int,Bool}} <: Union{Tuple{Int}, Tuple{Bool}}

In Julia 0.6.2, this query produced true, as the forall/exists justification would suggest. However, in 0.7.0 and later (incl. 1.1.0), it produces false. Which behaviour is correct?

**Comment by Keno** [comment]
I concur that it should be true. @JeffBezanson is the expert though.

**Comment by ulysses4ever** [comment]
The offending commit is: ff7b6452f8.

**Comment by martinholters** [comment]
```julia
julia> (Tuple{T} where T <: Union{Int,Bool}) <: Union{Tuple{Int}, Tuple{Bool}}
false

julia> (Tuple{T} where T <: Union{Int,Bool}) <: Tuple{Union{Int,Bool}}
true

julia> Union{Tuple{Int}, Tuple{Bool}} == Tuple{Union{Int,Bool}}
true
```
One of these answers has to be wrong; I agree it's the first one.
