### ISSUE TITLE
improve CodeInfo printing

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#31227]
The `CodeInfo` type recently gained several fields for the intent of having better pretty-printing. The various inspection tools (esp. code_warntype) would be nicely served to take advantage of this information when available to show the method signature, sparams, names, etc.

**Comment by narendrakpatel** [comment]
Can you please elaborate? I would like to work on this issue. @vtjnash @ararslan

**Comment by vtjnash** [comment]
The main new field that may be present is `.parent`. Just walking from there experimentally (interactively) and printing anything interesting that you come across, then adding those to the standard printing, I think would be productive, useful, and interesting.

**Comment by narendrakpatel** [comment]
Julia docs do not documentation for these fields of CodeInfo `rettype`, `max_world`, `method_for_inference_limit_heuristics`, `min_world`, `parent`. Shall I file a different issue for this?
