### ISSUE TITLE
Reading first few lines of a data file

### ISSUE THREAD

**Issue by iamsuddhasattwa** [JuliaLang/julia#31233]
Hi, I have a data file with 100 rows of data of the form
1 2
3 4
5 6.1
...

I want to load the first 10 lines as a 10X2 array. However, I do not see any option in readdlm() for doing that, although it should be an easy task.

**Comment by jpsamaroo** [comment]
Please post questions to https://discourse.julialang.org/

**Comment by quinnj** [comment]
Yes, please post usage questions to the discourse forum. In terms of your question, you can use the `CSV.jl` package (can be installed by doing `]add CSV`) and then doing `f = CSV.File(filename; delim=" ", limit=10)`. You can then materialize the structure as a DataFrame (`df = f |> DataFrame`), or Matrix (`m = Tables.matrix(f)`).

**Comment by iamsuddhasattwa** [comment]
Dear Jacob and Julian,
Thank you very much for the information. I really appreciate it.
- - -
Shuddho,
Suddhasattwa Das
