### ISSUE TITLE
What's the purpose of allowing non-binding notations in let binding sections, like `let a end`?

### ISSUE THREAD

**Issue by thautwarm** [JuliaLang/julia#31239]
```julia
let a end # okay
let a, b = (1, 2); a end # a not found, b = (1, 2)
```

Is it expected?

**Comment by yuyichao** [comment]
This is so that you can assign to it later like,

```julia
let a, b
    a = ...
    <extra code>
    b = ...
end
```

So yes this is expected and is not a bug.

I assume you are aware that you want `(a, b) = (1, 2)`. I believe there were already discussion about this "syntax ambiguity" before we settled on this rule so I'm closing this for now...

**Comment by thautwarm** [comment]
Okay, but it's still quite confusing for we support syntax like `let a end`...
Any link about previous discussion?

**Comment by yuyichao** [comment]
The previous discussion was about the parsing of `a, b = ...` in let or const context. Can't find it or I'd have linked it already.

The support for `let a end` is not anything more than that we support `let end` or `begin end` or `(;)`. They are just very legal though not particularly useful syntaxes.
