### ISSUE TITLE
Does julia support dict's dict?

### ISSUE THREAD

**Issue by biofuture** [JuliaLang/julia#31241]
I am trying to find features like hash's hash from perl in  Julia's dict.  HOWEVER, I do not find any document about this feature. 

define like this report errors

dict = Dict{String, Dict{String, Int}()}()

ERROR: TypeError: in Type, in parameter, expected Type, got Dict{String,Int64}
Stacktrace:
 [1] top-level scope at none:0

**Comment by yuyichao** [comment]
Yes it's supported and no the syntax is wrong and please use discourse.julialang.org for all questions.
