### ISSUE TITLE
Mac nightly prints error when starting "could not load library "libcholmod""

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#31259]
For example: https://travis-ci.org/JuliaDebug/Debugger.jl/jobs/502074345#L170-L180.

Was touched in https://github.com/JuliaLang/julia/pull/31196, https://github.com/JuliaLang/julia/pull/31249

**Comment by StefanKarpinski** [comment]
cc @staticfloat

**Comment by staticfloat** [comment]
I believe Jameson's PR #31261 is the right way to solve this, once it's passing CI.
