### ISSUE TITLE
jupyter notebook not installing

### ISSUE THREAD

**Issue by zerocoll9** [JuliaLang/julia#31265]
I tried to install Jupyter Notebook on Julia via Pkg and it not working. 
I'm using windows 10 home, and guess that it is happening cause of the user name of my folder, which is "João Paulo". I tried change it setting a USERPROFILE environment variable as "C:\home" and HOME as "c:\home". But it didn't, tested it on julia versions 1.1.0 e 1.0.3. On 1.0.3 is showing this message 

julia> notebook()
install Jupyter via Conda, y/n? [y]: y
[ Info: Running `conda install -y jupyter` in root environment
failed to create process.
[ Info: running setenv(`'C:\Users\João Paulo\.julia\conda\3\Scripts\jupyter.exe' notebook`,["PATH=C:\\Users\\João Paulo\\.julia\\conda\\3\\Scripts;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files\\dotnet\\;C:\\msys64\\mingw32\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Dart\\dart-sdk\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\gnuplot\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\João Paulo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\CMake\\bin;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;C:\\msys64\\mingw32\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\xampp\\php;C:\\tools\\dart-sdk\\bin;C:\\dart-sdk\\flutter\\bin;C:\\msys64\\mingw32\\bin\\;", "USERDOMAIN_ROAMINGPROFILE=DESKTOP-GMHS1LJ", "HOMEPATH=\\Users\\João Paulo", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "SYSTEMROOT=C:\\WINDOWS", "APPDATA=C:\\Users\\João Paulo\\AppData\\Roaming", "CHOCOLATEYTOOLSLOCATION=C:\\tools", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "PROGRAMDATA=C:\\ProgramData", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-GMHS1LJ", "OS=Windows_NT", "PROCESSOR_REVISION=2a07", "TMP=C:\\Users\\JOOPAU~1\\AppData\\Local\\Temp", "COMSPEC=C:\\WINDOWS\\system32\\cmd.exe", "ALLUSERSPROFILE=C:\\ProgramData", "COMPUTERNAME=DESKTOP-GMHS1LJ", "USERNAME=João Paulo", "DART_SDK=C:\\Program Files\\Dart\\dart-sdk", "ONEDRIVECONSUMER=C:\\Users\\João Paulo\\OneDrive", "USERPROFILE=C:\\Users\\João Paulo", "PROCESSOR_LEVEL=6", "PROGRAMW6432=C:\\Program Files", "HOME=C:\\HOME", "TEMP=C:\\Users\\JOOPAU~1\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "WINDIR=C:\\WINDOWS", "LOCALAPPDATA=C:\\Users\\João Paulo\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel", "NUMBER_OF_PROCESSORS=8", "=::=::\\", "COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files", "MOZ_PLUGIN_PATH=C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\", "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "GNUPLOT_LIB=C:\\Program Files\\gnuplot\\demo;C:\\Program Files\\gnuplot\\demo\\games;C:\\Program Files\\gnuplot\\share", "ONEDRIVE=C:\\Users\\João Paulo\\OneDrive", "CHOCOLATEYINSTALL=C:\\ProgramData\\chocolatey", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "PROGRAMFILES=C:\\Program Files", "CHOCOLATEYLASTPATHUPDATE=Mon Jul  9 22:36:14 2018", "ANDROID_HOME=C:\\Androidsdk\\", "LOGONSERVER=\\\\DESKTOP-GMHS1LJ", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FPS_BROWSER_USER_PROFILE_STRING=Default", "ASL.LOG=Destination=file", "SYSTEMDRIVE=C:", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"])
ERROR: IOError: could not spawn setenv(`'C:\Users\João Paulo\.julia\conda\3\Scripts\jupyter.exe' notebook`,["PATH=C:\\Users\\João Paulo\\.julia\\conda\\3\\Scripts;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files\\dotnet\\;C:\\msys64\\mingw32\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Dart\\dart-sdk\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\gnuplot\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\João Paulo\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\CMake\\bin;C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64;C:\\msys64\\mingw32\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\xampp\\php;C:\\tools\\dart-sdk\\bin;C:\\dart-sdk\\flutter\\bin;C:\\msys64\\mingw32\\bin\\;", "USERDOMAIN_ROAMINGPROFILE=DESKTOP-GMHS1LJ", "HOMEPATH=\\Users\\João Paulo", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "SYSTEMROOT=C:\\WINDOWS", "APPDATA=C:\\Users\\João Paulo\\AppData\\Roaming", "CHOCOLATEYTOOLSLOCATION=C:\\tools", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "PROGRAMDATA=C:\\ProgramData", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-GMHS1LJ", "OS=Windows_NT", "PROCESSOR_REVISION=2a07", "TMP=C:\\Users\\JOOPAU~1\\AppData\\Local\\Temp", "COMSPEC=C:\\WINDOWS\\system32\\cmd.exe", "ALLUSERSPROFILE=C:\\ProgramData", "COMPUTERNAME=DESKTOP-GMHS1LJ", "USERNAME=João Paulo", "DART_SDK=C:\\Program Files\\Dart\\dart-sdk", "ONEDRIVECONSUMER=C:\\Users\\João Paulo\\OneDrive", "USERPROFILE=C:\\Users\\João Paulo", "PROCESSOR_LEVEL=6", "PROGRAMW6432=C:\\Program Files", "HOME=C:\\HOME", "TEMP=C:\\Users\\JOOPAU~1\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "WINDIR=C:\\WINDOWS", "LOCALAPPDATA=C:\\Users\\João Paulo\\AppData\\Local", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel", "NUMBER_OF_PROCESSORS=8", "=::=::\\", "COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files", "MOZ_PLUGIN_PATH=C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\", "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "GNUPLOT_LIB=C:\\Program Files\\gnuplot\\demo;C:\\Program Files\\gnuplot\\demo\\games;C:\\Program Files\\gnuplot\\share", "ONEDRIVE=C:\\Users\\João Paulo\\OneDrive", "CHOCOLATEYINSTALL=C:\\ProgramData\\chocolatey", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "PROGRAMFILES=C:\\Program Files", "CHOCOLATEYLASTPATHUPDATE=Mon Jul  9 22:36:14 2018", "ANDROID_HOME=C:\\Androidsdk\\", "LOGONSERVER=\\\\DESKTOP-GMHS1LJ", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FPS_BROWSER_USER_PROFILE_STRING=Default", "ASL.LOG=Destination=file", "SYSTEMDRIVE=C:", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]; dir="C:\\Users\\João Paulo"): no such file or directory (ENOENT)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{Base.DevNull,Base.DevNull,Base.DevNull}) at .\process.jl:367
 [2] (::getfield(Base, Symbol("##493#494")){Cmd})(::Tuple{Base.DevNull,Base.DevNull,Base.DevNull}) at .\process.jl:509
 [3] setup_stdio(::getfield(Base, Symbol("##493#494")){Cmd}, ::Tuple{Base.DevNull,Base.DevNull,Base.DevNull}) at .\process.jl:490
 [4] #_spawn#492(::Nothing, ::Function, ::Cmd, ::Tuple{Base.DevNull,Base.DevNull,Base.DevNull}) at .\process.jl:508
 [5] _spawn at .\process.jl:504 [inlined]
 [6] #run#503(::Bool, ::Function, ::Cmd) at .\process.jl:665
 [7] #run at .\none:0 [inlined]
 [8] launch(::Cmd, ::String, ::Bool) at C:\Users\João Paulo\.julia\packages\IJulia\4UizY\src\jupyter.jl:46
 [9] #notebook#8 at C:\Users\João Paulo\.julia\packages\IJulia\4UizY\src\jupyter.jl:89 [inlined]
 [10] notebook() at C:\Users\João Paulo\.julia\packages\IJulia\4UizY\src\jupyter.jl:87
 [11] top-level scope at none:0

The error is going on QT package, i guess, and i need it to plot graphs and so on.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
