### ISSUE TITLE
A problem with mapreduce with pre-allocated space for function results

### ISSUE THREAD

**Issue by bsxfan** [JuliaLang/julia#31271]
The following minimal example shows an incorrect summation result using `mapreduce`. The problem occurs when storing each function result into a pre-allocated array:
```
# copy R[:,j] into pre-allocated vector c
function getcolumn!(R,j,c)                 
    for i=1:size(R,1) c[i] = R[i,j] end
    return c
end

#highlight problem
function compareSums(R)
    
    # correct reference
    s0 = sum(R,dims=2)
    
    # this also works
    s1 = mapreduce(j->R[:,j],+,1:size(R,2))
    
    # and this
    c = similar(R[:,1])  # pre-allocate space for function results
    s2 = zeros(size(R,1))
    for j=1:size(R,2) s2 += getcolumn!(R,j,c) end
    
    # but this doesn't
    s3 = mapreduce(j->getcolumn!(R,j,c),+,1:size(R,2))
    
    return [s0 s1 s2 s3]
end
compareSums(randn(2,3))
```
which gives (for example):
```
2×4 Array{Float64,2}:
 -1.12149   -1.12149   -1.12149   -1.96639
  0.432959   0.432959   0.432959   1.61196​

```
where the final column is incorrect---it should have been the same as the other 3 columns.

I'm using Julia 1.1 on Windows.

**Comment by raminammour** [comment]
It is aliasing. Maybe this helps:
```
function getcolumn!(R,j,c)                 
           for i=1:size(R,1) c[i] = R[i,j] end
           @show c;
          return c
end

R=rand(2,3);c=zeros(2);

map(j->(getcolumn!(R,j,c)),1:3)

c = [0.695763, 0.279385]
c = [0.615813, 0.964702]
c = [0.38642, 0.541613]
3-element Array{Array{Float64,1},1}:
 [0.38642, 0.541613]
 [0.38642, 0.541613]
 [0.38642, 0.541613]
```
The result is an `Array{Array}` as you see, all pointing to the same `c` (the last one) and reduction with `sum` produces 3*last column.

`mapreduce` goes through things in a more complicated way but the aliasing produces similar bizarre things. `init` aliases `c` in your example (`init` is the optional parameter). I think something along these lines is happening:
1- ` init=f(1) (=c)`
2- c=f(2)
3- init+f(2)= 2*c = 2*f(2)
4- the rest is as you expect
5- result = `2*R[:,2]+sum(R[:,3:end],dims=2)`
(this was fun to verify :) )

I don't know if there is anything to fix here, or just do a better job at warning against such things in the documentation.

**Comment by mbauman** [comment]
More simply, `mapreduce` needs to perform the operation `f(x[1]) ⨁ f(x[2])`.  We need two results from `f` to call the reduction operator `⨁`.  And we don't know know that calling `f` the second time is going to _modify what it already gave us_ because `f` is just an arbitrary function at this point.  Note, too, that `⨁` might be defined as `(a, b) -> a`, which would propagate this aliasing to the next element.

Seems like a good place for documented restrictions — even just detecting these situations would be tricky and expensive.

**Comment by bsxfan** [comment]
Thank you @raminammour. The optional `init` argument to `mapreduce` can be used to solve the problem. 

My summary of the problem is as follows. When `init` is not supplied, `mapreduce` does the reasonable thing of re-using the first function result as a container for accumulating the sum. Since my mapping function `getcolumn!` identifies its output with the pre-allocaed storage, this causes the observed aliasing.

The problem can be made to go away, by supplying an explicit `init`. By adding one line of code to my example, it now behaves:
```
# copy R[:,j] into pre-allocated vector c
function getcolumn!(R,j,c)                 
    for i=1:size(R,1) c[i] = R[i,j] end
    return c
end

#highlight problem
function compareSums(R)
    
    # correct reference
    s0 = sum(R,dims=2)
    
    # this also works
    s1 = mapreduce(j->R[:,j],+,1:size(R,2))
    
    # and this
    c = similar(R[:,1])  # pre-allocate space for function results
    s2 = zeros(size(R,1))
    for j=1:size(R,2) s2 += getcolumn!(R,j,c) end
    
    # This now works 
    # -- we just need to supply mapreduce with a separate container to accumulate the sum
    s3 = zeros(size(R,1))
    s3 = mapreduce(j->getcolumn!(R,j,c),+,1:size(R,2),init=s3)
    
    return [s0 s1 s2 s3]
end
compareSums(randn(2,3))
```
which gives (for example):
```
2×4 Array{Float64,2}:
 -1.4171    -1.4171    -1.4171    -1.4171  
  0.969922   0.969922   0.969922   0.969922
```
where all colmuns now agree as they should.

**Comment by raminammour** [comment]
@mbauman's point was that:
```
mapreduce(j->getcolumn!(R,j,c),(a,b)->a,1:size(R,2),init=s3)-->s3
mapreduce(j->getcolumn!(R,j,c),(a,b)->a,1:size(R,2)) --> R[:,end]
```
Both results are somewhat unexpected, because you would expect the first column.

While `init` fixes your case, the problem is too difficult/expensive to defend against. Therefore, it must be documented since it is not completely obvious. I will let him decide if the issue should remain open until documented :)

**Comment by bsxfan** [comment]
Thank you @raminammour for your explanation of @mbauman 's example. I now understand that example and I also understand better why `mapreduce` gave the results it did (more on that below). I would argue however, that the first example:
```
mapreduce(j->getcolumn!(R,j,c),(a,b)->a,1:size(R,2),init=s3)-->s3
```
Is not "unexpected", because `init` effectviely serves as the first column and the accumulation function, `(a,b)->a` always ends up keeping the first element of a collection.

In order to understand better the second example, and also my original problem---in both of which `init` was not supplied, it helps to portray the following simplification of what mapreduce (without `init`) does:
```
function mapreduce_noinit(f,reduce,collection)
    acc = f(collection[1])
    for i=2:length(collection)
        y =  f(collection[i])   # my f() has the side effect of modifying acc, before it is used below
        acc = reduce( acc, y )  # the problem occurs only once, because from now on, acc is independent
    end
end
``` 
I can sugggest one way to modify `mapreduce` to defend against this problem by doing:
```
function mapreduce_noinit(f,reduce,collection)
    acc = copy( f(collection[1]) )
    ...
```
but this then requires that `copy()` be defined for the return type of `f`.
