### ISSUE TITLE
Apply LLVM patch for faster AVX512 max operation

### ISSUE THREAD

**Issue by nlw0** [JuliaLang/julia#31289]
This is a request to pull a patch from LLVM into the Julia patches. It solves a performance issue with the vectorized "max" operator in AVX512 machines. This is the bug report:
https://bugs.llvm.org/show_bug.cgi?id=40984

The patch:
https://github.com/llvm/llvm-project/commit/3acc4236b8717bf493b81905194a10e71f526702

Also related:
https://github.com/eschnett/SIMD.jl/issues/47

**Comment by Keno** [comment]
Wanna send a PR to this effect? Just put the patch in `deps/patches` and add it to the list in `deps/llvm.mk`.

**Comment by nlw0** [comment]
I'll try

**Comment by nlw0** [comment]
Created https://github.com/JuliaLang/julia/pull/31292
