### ISSUE TITLE
Feature request: "Build minmal julia" makefile option

### ISSUE THREAD

**Issue by ldgirod** [JuliaLang/julia#3128]
It would be nice to have a target in the makefile that built only the base components of julia required to get to the REPL loop with a minimal set of builtins and dependencies.

This came up because I wanted to find out what the minimal requirements are to port Julia to a new architecture (e.g. arm) or platform (e.g. android).

**Comment by vtjnash** [comment]
closing in favor of #5155

**Comment by timholy** [comment]
For folks working on Julia's core, it might be interesting to be able to build a *really* minimal julia...not something any user would want, but effectively a gdb-like mode for Core.

**Comment by timholy** [comment]
With reference to the above comment, for anyone hacking on `inference.jl`: just go to the `base/` directory and then do `include("coreimg.jl")`. It will replace the current `Core.Inference` with a new one.
