### ISSUE TITLE
Can't seem to define variables 

### ISSUE THREAD

**Issue by joedoewoe2** [JuliaLang/julia#31281]
This has been making me want to pull my hair out. I can't execute basic commands and I'm not sure what I'm doing wrong. Very new to Julia 

Julia>m, n = 5, 5 
 A = Fill(0, (m, n))

ERROR: UndefVarError: Fill not defined
Stacktrace:
 [1] top-level scope at none:0

example 2 : 
Julia > n = 0
while n < 10

           n += 1

               println(n)

               end
ERROR: UndefVarError: n not defined
Stacktrace:
 [1] top-level scope at .\none:3

**Comment by JeffBezanson** [comment]
In the first example, the function `fill` is lowercase. Julia is case-sensitive. The second example is due to scope rules, discussed extensively in #28789. We hope to change that to something more intuitive if possible.

**Comment by JeffBezanson** [comment]
Also please try discourse.julialang.org for help.

**Comment by joedoewoe2** [comment]
thank you!
