### ISSUE TITLE
Error in doc of sprandn

### ISSUE THREAD

**Issue by DNF2** [JuliaLang/julia#31283]
The documentation of `sprand`/`sprandn` appears to have an error in the section https://docs.julialang.org/en/v1/stdlib/SparseArrays/#Correspondence-of-dense-and-sparse-methods-1

The table here: 
<img width="746" alt="screenshot 2019-03-06 at 13 04 08" src="https://user-images.githubusercontent.com/7106412/53880457-4fdcc180-4011-11e9-93fa-ee2b1e7384a3.png"> 
shows that `sprandn` takes a distribution as a final argument, but this is not the case.

The accompanying text also seems to indicate that this should work:
```
sprand(100, 100, 0.3, Uniform(-1,1))
```
while, in fact, you need
```
sprand(100, 100, 0.3, n->rand(Uniform(-1,1),n))
```
Also, the docstring of `sprand` gives the wrong impression:

> Nonzero values are sampled from the distribution specified by `rfn` and have the type `type`.

**Comment by ViralBShah** [comment]
It would be great if you could submit a PR to the docs themselves.

**Comment by ViralBShah** [comment]
> Also, the docstring of `sprand` gives the wrong impression:
> 
> > Nonzero values are sampled from the distribution specified by `rfn` and have the type `type`.

The docs no longer mention this and seem to be in sync with the code.
