### ISSUE TITLE
Feature request: define getproperty for Tuple with integers indexes

### ISSUE THREAD

**Issue by piever** [JuliaLang/julia#31320]
This came out in a slack discussion with @quinnj. The Tables.jl interface uses `getproperty` to access fields of a row of a dataset, `setproperty!` to modify them and `propertynames` to have a list of such names. The IndexedTables package (as well as StructArrays) also consider the case of "nameless tables" where each row is a tuple. It would be handy if:

- `propertynames` of a tuple would return the list of indices, say `propertynames((2, :a)) = (1,2)` (same as `fieldnames(::Type{<:Tuple})`)
- `getproperty(s, i::Integer)` would fallback to `getfield(s, i)` and therefore work on tuples
- optional: `s.1` calls `getproperty(s, 1)` (currently it errors).

EDIT: the first point actually already works.

**Comment by JeffBezanson** [comment]
See #20441 for some discussion of the third point.

**Comment by piever** [comment]
Thanks for the link, I had missed the previous issue. In my mind, compared to #20441 there are two novel perspectives:

1. for tabular data it is reasonably common to want access fields by index (say `map(row -> row.3, table)` to get values from the third column of the data), but I understand that outside tabular data this may be a bit unorthodox, for example for `c::Complex` it'd be strange (and less readable) to use `c.2` instead of `c.im`.

2. If this calls `getproperty(t, s::Int)`, it can actually be overloaded (which I don't think was possible at the time the #20441 was discussed).

I'm not sure whether this is sufficient to shift the consensus against the proposal in #20441.

**Comment by vchuravy** [comment]
I think outside of the syntax issue, it is a bit odd that Tuple break this idempotency `props(a) = map(p->getproperty(a, p), propertynames(a))`

**Comment by vtjnash** [comment]
I don't care much for #2. I think one of the nice properties of the split between getfield/getproperty is that usually you index the former with a Int, while the later always takes a Symbol. I'd be ok with having the more limited `getproperty(s::Tuple, i::Integer)` defined as just an oddball case where propertynames returns same as keys and getproperty is the same as getindex.

**Comment by piever** [comment]
The part that I found most surprising was indeed that `propertynames` is defined for tuples and returns ints, but then `map(p->getproperty(a, p), propertynames(a))` actually errors (to the point that I somehow assumed `propertynames` returned `()` for tuples, hence my confusion about point 1): this is what breaks the Tables interface for tables of tuples. From a practical perspective, the "nameless table" implementation in StructArrays and JuliaDB are with tuples, so a `getproperty(s::Tuple, i::Integer)` method would solve it.

**Comment by StefanKarpinski** [comment]
I'm confused... can't you already write `row[3]` instead of `row.3`?

**Comment by StefanKarpinski** [comment]
Ah, I see, that makes sense. Thanks for explaining.

**Comment by vtjnash** [comment]
Requested feature to define getproperty for Tuple with integers indexes implemented in #31324
