### ISSUE TITLE
"jl_system_image_size" loaded incorrectly in function "jl_load_sysimg_so"

### ISSUE THREAD

**Issue by zyeric** [JuliaLang/julia#31326]
https://github.com/JuliaLang/julia/blob/7e4641da1f353cdb7341a49b0ae00b6e9649e001/src/staticdata.c#L199

Variable **len** stores the pointer to **jl_system_image_size** instead of the value we want.

**Comment by jpsamaroo** [comment]
Can you be a bit more specific? What *should* it store, in your opinion? And have you run into an issue because of this line?

**Comment by zyeric** [comment]
I think **len** shold store the value corresponding to the length of the array **jl_symtem_image_data**. Actually, I can successfully loading sys.so with current code. However, when I use gdb to check the detailed process, I find the value of **len** is strange.
