### ISSUE TITLE
ccall with user defined type on ARM

### ISSUE THREAD

**Issue by jmkuhn** [JuliaLang/julia#31333]
The following works as I expect on x86_64 but not on ARM.

I make a shared lib from the following C
```
typedef unsigned long long T64;

T64 t64_from_uint32(unsigned int x)
{
    return (T64) x;
}
```
Then call from julia
```
using Printf

struct T64
    x::UInt64
end

Base.reinterpret(::Type{T64}, x::UInt64) = T64(x)

function main()
    ui = UInt32(1)
    # this doesn't work on arm
    x = ccall((:t64_from_uint32, "./libmylib"), T64, (UInt32,), ui)
    @printf("%#x\n", x.x)
    # this does work
    x = reinterpret(T64, ccall((:t64_from_uint32, "./libmylib"), UInt64, (UInt32,), ui))
    @printf("%#x\n", x.x)
end

main()
```
Sample output from ARM
```
pi@pi:~/mylib_3$ julia test_mylib.jl 
0x76e65d9000000000
0x1
pi@pi:~/mylib_3$ julia test_mylib.jl 
0x76ec0d9000000000
0x1
```
Note that the output from the first `ccall` is not consistent from run to run.  I am using Julia v1.0.3 Generic Linux Binaries for ARM.

**Comment by yuyichao** [comment]
You do not have a user defined type so don't use a strict in Julia. Use primitive type if you really don't want to use the integer type in Julia.


Your code is wrong on both x86 and arm and the calling convention on x86 is just hiding it.

**Comment by StefanKarpinski** [comment]
Or maybe a type alias if that's more appropriate—of course then you can't add new methods to your type separate from the aliased integer type but if you just want to generically refer to a type that may be different on different systems, a type alias may be sufficient.

**Comment by jmkuhn** [comment]
The DecFP.jl package is where this is an issue.  Perhaps primitive types are the proper solution there.

**Comment by stevengj** [comment]
DecFP used to use primitive types, then switched structs to work around #21216; nowadays it seems time to switch back.

**Comment by yuyichao** [comment]
You can use struct for the user facing/API type. Just make sure you don't let ccall see it.
