### ISSUE TITLE
Unreachable reached: Calling an overloaded AxisArrays constructor

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#31349]
I realize there have been a bunch of other unreachable reached errors, but I couldn't find another issue that matched this error exactly. I appear to be getting this error in some proprietary code and I'm having difficulty narrowing down a minimal working example.

# System info

I'm running a 1.1 binary release on the latest macbook pro.

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /Users/rory/.playground/share/xxxxt/depot
  JULIA_EDITOR = /usr/local/bin/atom -n
  JULIA_HISTORY = /Users/rory/.playground/share/xxxx/.julia_history
  JULIA_PKGDIR = /Users/rory/.playground/share/xxxx/packages
```

# Problem

This issue seems to be with calling an overloaded `AxisArray` constructor in our.

```
AxisArray(data, cnames...; default=missing)
```

In the error condition, the constructor completes normally and creates the expected AxisArray from the `data` (a `KeyedFrame`)... it just seems to be erroring when returning back to the original call site. I've tried saving all relevant data and calling this constructor from the REPL, but that doesn't produce the error. I've also tried adding type assertions and conversions to force an AxisArray return type, but that doesn't change the behaviour.

```
julia> @code_typed AxisArray(data, cnames...; default=missing)
CodeInfo(
1 ──       goto #3 if not false
2 ──       nothing::Nothing
3 ┄─ %3  = π (false, Const(false, false))
│    %4  = (Base.getfield)(#temp#, :default)::Missing
│    %5  = (Base.sle_int)(1, 1)::Bool
└───       goto #5 if not %5
4 ── %7  = (Base.sle_int)(1, 0)::Bool
└───       goto #6
5 ──       nothing::Nothing
6 ┄─ %10 = φ (#4 => %7, #5 => false)::Bool
└───       goto #8 if not %10
7 ──       invoke Base.getindex(()::Tuple, 1::Int64)::Union{}
└───       $(Expr(:unreachable))::Union{}
8 ┄─       goto #9
9 ──       goto #10
10 ─       goto #11
11 ─       goto #12
12 ─       nothing::Nothing
│    %19 = (getfield)(dims, 1)::Symbol
│    %20 = (getfield)(dims, 2)::Symbol
│    %21 = (getfield)(dims, 3)::Symbol
│    %22 = invoke AxisArrayUtils.:(#AxisArray#4)(%3::Bool, %4::Missing, _3::Type, _4::KeyedFrame, _5::Symbol, %19::Symbol, %20::Vararg{Symbol,N} where N, %21)::Any
└───       return %22
) => Any
```

I far as I can tell we're hitting ` $(Expr(:unreachable))::Union{}` when `%10 = φ (#4 => %7, #5 => false)::Bool` returns `true`, but I'm not sure what that check is doing. I realize this isn't a lot to go on, but I'd appreciate any debugging recommendations given that I'm not super familiar with julia internals.

**Comment by Keno** [comment]
Try master. If it still happens, ideally post a Manifest with exact versions to reproduce it. There's nothing wrong with the IR, since `invoke Base.getindex(()::Tuple, 1::Int64)::Union{}` should throw an error. There's likely something else going on.

**Comment by rofinn** [comment]
Looks like this code isn't runnable on master due to a breaking change for OrderedCollections:

```
UndefVarError: show_comma_array not defined
show(::Base.GenericIOBuffer{Array{UInt8,1}}, ::OrderedCollections.OrderedSet{String}) at /Users/rory/.playground/share/xxx/depot/packages/OrderedCollections/Pr9Pa/src/ordered_set.jl:18
```

I'll make a separate issue for that.

**Comment by rofinn** [comment]
Update: I'm still able to reproduce this on the latest master.

**Comment by JeffBezanson** [comment]
> In the error condition, the constructor completes normally and creates the expected AxisArray from the `data` (a `KeyedFrame`)... it just seems to be erroring when returning back to the original call site.

To debug this, look at the IR for the call site and determine the inferred types of the arguments passed to the AxisArray constructor. What usually causes this is an intersection of those types and the constructor signatures is incorrectly empty. If that's the case then we can fix this without a reduced code example.

**Comment by rofinn** [comment]
Okay, so I don't see anything obviously wrong with the types, but I do have some questions. I apologize if there is a very obvious error that I'm missing:

Constructor signature:

```
AxisArrays.AxisArray(AbstractDataFrame, Symbol, Symbol...; sort=false, default=undef)::AxisArray
```

Call-site output of `@which`:
```
(::getfield(Core, Symbol("#kw#Type")))(::Any, ::Type{AxisArrays.AxisArray}, table::DataFrames.AbstractDataFrame, values::Symbol, dims::Symbol...) in AxisArrayUtils
```

The method signature tuple from `@which`:

```
Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArrays.AxisArray},DataFrames.AbstractDataFrame,Symbol,Vararg{Symbol,N} where N}
```

Call-site IR on master
```
CodeInfo(
1 ──       goto #3 if not false
2 ──       nothing::Nothing
3 ┄─       nothing::Nothing
│    %4  = Base.sle_int(1, 1)::Bool
└───       goto #5 if not %4
4 ── %6  = Base.sle_int(1, 0)::Bool
└───       goto #6
5 ──       nothing::Nothing
6 ┄─ %9  = φ (#4 => %6, #5 => false)::Bool
└───       goto #8 if not %9
7 ──       invoke Base.getindex(()::Tuple, 1::Int64)::Union{}
└───       $(Expr(:unreachable))::Union{}
8 ┄─       goto #9
9 ──       goto #10
10 ─       goto #11
11 ─       goto #12
12 ─       nothing::Nothing
│    %18 = (getfield)(dims, 1)::Symbol
│    %19 = (getfield)(dims, 2)::Symbol
│    %20 = (getfield)(dims, 3)::Symbol
│    %21 = invoke AxisArrayUtils.:(#AxisArray#4)(false::Bool, $(QuoteNode(missing))::Missing, _3::Type{AxisArrays.AxisArray}, _4::DataFrames.DataFrame, _5::Symbol, %18::Symbol, %19::Vararg{Symbol,N} where N, %20)::AxisArrays.AxisArray
└───       return %21
) => AxisArrays.AxisArray
```

I'm not entirely familiar with checking type intersections, but when I compared the intersect of the positional arguments it looked reasonable.

```
julia> T = Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArrays.AxisArray},DataFrames.AbstractDataFrame,Symbol,Vararg{Symbol,N} where N}
Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArray},AbstractDataFrame,Symbol,Vararg{Symbol,N} where N}

julia> S = Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArrays.AxisArray}, DataFrames.DataFrame,Symbol,Symbol,Vararg{Symbol,N} where N}
Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArray},DataFrame,Symbol,Symbol,Vararg{Symbol,N} where N}

julia> typeintersect(T, S)
Tuple{getfield(Core, Symbol("#kw#Type")),Any,Type{AxisArray},DataFrame,Symbol,Symbol,Vararg{Symbol,N} where N}
```

Could the keyword arguments be causing problems? The only difference I see between the signature and the IR code is `false::Bool, $(QuoteNode(missing))::Missing` vs `getfield(Core, Symbol("#kw#Type")),Any`. I'm guessing that `getfield(Core, Symbol("#kw#Type"))` is the `undef`?

**Comment by iamed2** [comment]
What's up with `%19::Symbol, %20::Vararg{Symbol,N} where N, %21`? `%20` is supposed to be a `Symbol`, and I thought `Vararg` could only go at the end of a tuple type.

**Comment by vtjnash** [comment]
It's just a printing issue—the new `invoke` method printer format is unaware that it can't represent the target signature in this syntax

**Comment by rofinn** [comment]
Did folks have specific function calls in mind? Outside of using the `@code_*` macros at different levels of the code I'm not really sure what else I should be trying to gather more info.

**Comment by JeffBezanson** [comment]
We need a reproducible example.

**Comment by rofinn** [comment]
Alright, looks like I managed to resolve the issue while trying to generate a MWE. It looks like the constructor `AxisArrays.AxisArray(AbstractDataFrame, Symbol, Symbol...; sort=false, default=undef)::AxisArray` was being called with `AxisArray(df, [:val; [:ax1, :ax2, :ax3]]...; default=missing)`. Change that call to AxisArray(df, :val, [:ax1, :ax2, :ax3]...; default=missing) seems to have solved the problem. I'm still not sure what the exact problem was, but I'm guess the weird call was confusing the compiler? 😕
