### ISSUE TITLE
Lost variable assignment in nested try/catch/finally blocks

### ISSUE THREAD

**Issue by tjgreen** [JuliaLang/julia#31357]
The following yields `(12345, nothing)` instead of the expected `(12345, 12345)`:
```julia
function foo(b::Bool)
    x = nothing
    try
        try
            x = 12345
            if !b
               throw("hi")
            end
        finally
        end
    catch
    end
    return x
end

foo(true),foo(false)    # (12345, nothing)
```
For comparison:
```julia
function bar(b::Bool)
    x = nothing
    try
        x = 12345
        if !b
           throw("hi")
        end
    catch
    end
    return x
end

bar(true),bar(false)    # (12345, 12345)

function baz(b::Bool)
    x = nothing
    try
        try
            x = 12345
            if !b
               throw("hi")
            end
        catch
        finally
        end
    catch
    end
    return x
end

baz(true),baz(false)    # (12345, 12345)
```
Related discussions (thanks @JeffreySarnoff for the pointers):
https://discourse.julialang.org/t/try-catch-question/15190/4
https://discourse.julialang.org/t/catching-exceptions-by-type/5690
https://discourse.julialang.org/t/failure-to-catch-an-exception/12822/2

**Comment by JeffreySarnoff** [comment]
With `foo` you are throwing something in a `try` block that has no `catch` part.  As you throw an error in `try` block, usually you would want to catch it and if this is happening in within a nesting of `try` blocks, then the catch action would be to `rethrow` the error to the next outermost `try catch end` or `try catch finally end` block for handling of the error.  If, in turn, that level cannot handle the error .. it would catch and rethrow it to the next of its outer blocks. 

With `foo` the inner `finally` does nothing so nothing is what it conveys.  The uncaught `throw` does nothing, the `finally` does nothing, so you see the result `foo(false) == nothing`.

**Comment by KristofferC** [comment]
Using https://github.com/JuliaDebug/JuliaInterpreter.jl:

```jl
julia> using JuliaInterpreter

julia> @interpret foo(false)
12345

julia> foo(false)
# nothing
```

Running without the JIT compiler (with the `--compile=no` flag) gives the correct result:

```
julia> Base.JLOptions().compile_enabled
0

julia> foo(false)
12345
```

so probably a bug with the optimizer?

**Comment by JeffreySarnoff** [comment]
While we are here, let's document the in's and out's of `try [catch] [finally] end` blocks, and the use[s] of each part, the purpose of `rethrow` and why one would choose to include or exclude either the `catch` part or the `finally` part or both.  Others know this part of Julia much better than I .. getting the correct info here is reasonable way to migrate it into the docs.  :book:

**Comment by KristofferC** [comment]
Try catch finally is documented here https://docs.julialang.org/en/v1/manual/control-flow/#The-try/catch-statement-1. While I am sure it can be improved it seems a bit orthogonal to the bug in OP?

**Comment by JeffreySarnoff** [comment]
Ok -- I am splitting my comment out into a new thread here.
