### ISSUE TITLE
LU factorization fails for sparse input

### ISSUE THREAD

**Issue by siddMahen** [JuliaLang/julia#31380]
I believe there are some issues with sparse LU factorization:

```
using LinearAlgebra
using SparseArrays

A = spzeros(2,2)
A[1:2, 1:2] = [1 1; -1 1]
F = lu(A)
print(F.L * F.U == A[F.p, :]) # false
```

In this case, `F.L` is correct but `F.U` is off by a factor of two: `print(F.L * (2*F.U) == A[F.p, :])` returns `true`. I believe this fails more spectacularly in other more complex situations.

Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

**Comment by ViralBShah** [comment]
The relationship is described in the documentation for `lu`. Such a question is better suited for discourse.

```
julia> A
2×2 SparseMatrixCSC{Float64,Int64} with 4 stored entries:
  [1, 1]  =  1.0
  [2, 1]  =  -1.0
  [1, 2]  =  1.0
  [2, 2]  =  1.0

julia> F = lu(A, check=true)
UMFPACK LU Factorization of a (2, 2) sparse matrix
Ptr{Nothing} @0x00007fa3a4ca0640

julia> F.L*F.U == (F.Rs .* A)[F.p, F.q]
true
```
