### ISSUE TITLE
Julia builds references source code inside the build location rather than install location

### ISSUE THREAD

**Issue by simonfxr** [JuliaLang/julia#31388]
Pretty much what the description says. This becomes apparent in stacktraces and e.g. using @less to view source code. I imagine rewriting code references at install time might be difficult, maybe an easier solution would be to use a source map which dynamically replaces matching paths at runtime?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/144
