### ISSUE TITLE
ifelse and type stability

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#31394]
We're manipulating unitful vectors with missings, and I'm having trouble achieving type-stability with `ifelse`:
```julia
julia> using Unitful; using Unitful: kA, A

julia> f(x, a, b) = ifelse(x[1], a[1], b[1])
f (generic function with 1 method)

julia> @code_warntype f([true], [1.0, missing], [1.0, missing])   # fine
Body::Union{Missing, Float64}
1 ─ %1 = (Base.arrayref)(true, x, 1)::Bool
│   %2 = (Base.arrayref)(true, a, 1)::Union{Missing, Float64}
│   %3 = (Base.arrayref)(true, b, 1)::Union{Missing, Float64}
│   %4 = (Main.ifelse)(%1, %2, %3)::Union{Missing, Float64}
└──      return %4

julia> @code_warntype f([true], [1.0kA], [1.0A])    # good enough
Body::Union{Quantity{Float64,𝐈,FreeUnits{(kA,),𝐈,nothing}}, Quantity{Float64,𝐈,FreeUnits{(A,),𝐈,nothing}}}
1 ─ %1 = (Base.arrayref)(true, x, 1)::Bool
│   %2 = (Base.arrayref)(true, a, 1)::Quantity{Float64,𝐈,Unitful.FreeUnits{(kA,),𝐈,nothing}}
│   %3 = (Base.arrayref)(true, b, 1)::Quantity{Float64,𝐈,Unitful.FreeUnits{(A,),𝐈,nothing}}
│   %4 = (Main.ifelse)(%1, %2, %3)::Union{Quantity{Float64,𝐈,FreeUnits{(kA,),𝐈,nothing}}, Quantity{Float64,𝐈,FreeUnits{(A,),𝐈,nothing}}}
└──      return %4

julia> @code_warntype f([true], [1.0kA, missing], [1.0A, missing])   # unstable
Body::Union{Missing, Quantity}
1 ─ %1 = (Base.arrayref)(true, x, 1)::Bool
│   %2 = (Base.arrayref)(true, a, 1)::Union{Missing, Quantity{Float64,𝐈,FreeUnits{(kA,),𝐈,nothing}}}
│   %3 = (Base.arrayref)(true, b, 1)::Union{Missing, Quantity{Float64,𝐈,FreeUnits{(A,),𝐈,nothing}}}
│   %4 = (Main.ifelse)(%1, %2, %3)::Union{Missing, Quantity}
└──      return %4
```
This would be fixed if the compiler was less eager to lump the two `Quantity` types together. However, even case #2 doesn't look great, and won't have great performance. `f([true], [1.0], [2.0f0])` has the same issue.

In my use case, the two branches of `ifelse` are returning "the same kind of thing". It would be reasonable to write a `promoting_ifelse` that converts/promotes them to a common type. However, this looks fundamentally impossible, because in `ifelse(true, missing, 0.5A)`, there's no way to know the "counterfactual argument type" of the second argument.

I don't have a solution to offer. For context, we have a complex macro that generates these `ifelse` from user-entered mathematical formulas. We'd like to support mixed units (`km` and `m`).

**Comment by yuyichao** [comment]
`ifelse` is nothing more than an eager branch and is not meant for any promotion.

**Comment by cstjean** [comment]
Right. Then I'd like to be able to write a `promoting_ifelse` (I updated the issue text). Or perhaps there's another solution I didn't think of.

**Comment by JeffBezanson** [comment]
It seems like the other possible kind of solution is to have `f` use the element types of `a` and `b`.

**Comment by cstjean** [comment]
I passed vectors to `f` for the sake of `@code_warntype`. I'll frame it another way. These operations have great performance:

```julia
julia> v = rand(10000) .* kA;

julia> w = rand(10000) .* A;

julia> @btime @. $v + $w;
  7.962 μs (2 allocations: 78.20 KiB)

julia> @btime @. $v * $w;
  7.822 μs (2 allocations: 78.20 KiB)

julia> @btime @. ifelse($v < 0.5kA, $v, $v);
  8.660 μs (3 allocations: 78.23 KiB)
```
This one does not:
```julia
julia> @btime @. ifelse($v < 0.5kA, $v, $w);
  3.899 ms (20016 allocations: 781.59 KiB)
```
I'm letting a not-so-technical user write formulas, and I just stick a `@.` in front (+ some other processing). Maybe you're right: the solution could be to replace `ifelse.(a, b, c)` with a non-broadcasting `vector_ifelse(a, b, c)`, that can promote based on the `eltype`. Thank you for the suggestion.
