### ISSUE TITLE
inv(missing) not defined

### ISSUE THREAD

**Issue by getzze** [JuliaLang/julia#31408]
Julia 1.1.0 
Although `1 ./ ` is defined and working ( and the docs claim that inv(x) is essentially one(x)/x ):
```
a = [1.0, 2.0, missing, 3.0]
1 ./ a
inv.(a)
## MethodError: no method matching inv(::Missing)
inv(missing)
## MethodError: no method matching inv(::Missing)
```

**Comment by JeffBezanson** [comment]
I agree this should be added.

**Comment by Shashi456** [comment]
@JeffBezanson how could i go about adding this?

**Comment by nalimilan** [comment]
You can add it to the list at "Unary operators/functions" in base/missing.jl, and adjust tests in tests/missing.jl.

**Comment by narendrakpatel** [comment]
I am interested in solving this issue. I am going to include the following test: `ismissing(inv(missing))`. I will also update the docs in `missing.md`. Any suggestions?

**Comment by nalimilan** [comment]
Tests are also written using a loop over functions, so you just need to add `inv` to the list. We don't document any of these methods.
