### ISSUE TITLE
Julep: Rewrite Julia Parser in Julia

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#31449]
I love that Julia uses FemtoLisp for parsing code, but I think it could be a real boon if the parser were to be rewritten in pure Julia. We could use a cut down version of the current FemtoLisp parser as something like `Core.parse` to be used during bootstrap and then a `Meta.parse` which is fully implemented in Julia. 

### Why? 

1) It would greatly lower the barrier of entry for people to provide contributions to the parser 

2) Reader macros. Having a Julia parser would make it possible to define a form of macro where code inside the macro scope is parsed according to user defined rules. These macros would essentially be string macros except you would no longer need to wrap the enclosed code in quotation marks, giving you truly arbitrary syntax inside a macro but retaining things like code highlighting, auto indentation, autocompletion, etc. Depending on the design of the Julia parser, it could also potentially offer more support when building reader macros than we currently offer for building string macros. 

Reader macros wouldn't really allow for new features over string macros per se, but I think the fact that string macro code needs to be inside a string substantially hampers their adoption for many potential applications, especially DSL implementation. 

### Reader Macro Syntax
I'm not deadset on any particular syntax to mark a reader macro, but something like `!@` could be used. 

As an example [Py2Jl.jl](https://github.com/JuliaCN/Py2Jl.jl) transpiler interface would go from
```julia
using Py2Jl

py2jl"""
def sum_by(f, seq):
    s = 0
    for e in seq:
        s = s + f(e)
    return s
"""
```
to 
```julia
using Py2Jl

!@py2jl(
def sum_by(f, seq):
    s = 0
    for e in seq:
        s = s + f(e)
    return s
)
```
Obviously, there would have to be certain limitations put on reader macros, ie. if we use parens `!@( ... )` to enclose code, then the parser for the macro *must* respect parenthesis balancing to make sure it doesn't leak out of its scope.

**Comment by JeffBezanson** [comment]
CSTParser.jl already has a very good implementation; we have discussed in the past trying to make it the default, which I think is a good goal. Reader macros are an orthogonal issue; if we really wanted them we could have them now. I think the main objection people have is that they'd like to at least be able to parse julia code without a full julia runtime available.

**Comment by stevengj** [comment]
See also this mailing-list discussion https://discourse.julialang.org/t/the-role-of-femtolisp-in-julia/1902 and https://github.com/JuliaLang/JuliaParser.jl for an older native-Julia parser.

**Comment by ViralBShah** [comment]
@c42f is doing this with [JuliaSyntax.jl](https://github.com/JuliaLang/JuliaSyntax.jl) and he should close this when it gets merged!

**Comment by c42f** [comment]
:+1: will close when #46372 merges.

Reader macros are a separate issue certainly. I feel that they're quite problematic in terms of making Julia parsing impossible without a full Julia runtime. This makes things even more difficult when developing tooling.

Having said that, I feel there's some real problems with raw string escaping being extremely confusing in some cases, for example #39092. I think this is really the only major problem with just putting DSLs into string macros - other than this, I don't see how reader macros would significantly improve anything?
