### ISSUE TITLE
yield does not check events

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#31468]
I am writing a web client that has several HTTP requests in flight. There is also a `while` loop that wait until one of them is available. (Ideally, there would be a `wait` function that could check whether any of a list of conditions is satisfied, but I didn't find such a function.)

I am now using `yield` in this loop. I found that this does not work, because `yield` does not check whether any events occurred. Using `sleep(0.001)` instead works fine.

My `while` loop looks like (see [here](https://github.com/eschnett/DropboxSDK.jl/blob/7327fc9e133b5ec0ddc4277567adb14ce6fcfc6d/src/DropboxCLI.jl#L689)):
```Julia
    while active_tasks >= 4
        yield
        ... check whether any task has completed ...
    end
```

Is this intended? Is there another function that I should call instead of `yield` for this kind of busy-waiting?

**Comment by JeffBezanson** [comment]
Are you using `yield` or `yield()`?

**Comment by eschnett** [comment]
D'oh.
