### ISSUE TITLE
should rounding and real be implied in conversion

### ISSUE THREAD

**Issue by HDictus** [JuliaLang/julia#31467]
in changing the types conv in DSP.jl can handle I'm finding that things would be a lot simpler and more concise if certain aspects of type conversion were handled by the convert operation, rather than needing to be explicitly called. 
Is there a reason that e.g. convert(Int64, 1.001) has to raise an InexactError rather than return 1?
And similarly, why convert(Float64, 1.0 + 1.0im) would need real() to be called on it separately, when it could be implied? 
In cases where a variety of input and output types need to be managed it would save some trouble (with conv for example, I wouldn't have to abstract core function logic to two layers of "private" functions, or impliment nearly as many dispatches, or unnecessarily convert input arguments to change dispatch). It also just seems generally convenient for conversion between common types (especially when working with a variety of potential types, which should happen often if the style guide is being observed).

**Comment by timholy** [comment]
This should *definitely* not be the default, especially since there's a package just for this: https://github.com/JuliaMath/RoundingIntegers.jl.
