### ISSUE TITLE
REPL tab completion of space-containing filename incorrectly escapes space 

### ISSUE THREAD

**Issue by NextTimeJim** [JuliaLang/julia#31478]
Hello,
I think either tab completion in the Julia REPL should not escape filename spaces or this is an issue with `CSV`:

```
julia> using CSV

julia> CSV.read("patient\ samples.csv") # tab completed from `CSV.read("` 
ERROR: syntax: invalid escape sequence

julia> CSV.read("patient samples.csv"); # fine without escape sequence

julia> 
```

`Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
`

**Comment by krrutkow** [comment]
#29304
#27937
