### ISSUE TITLE
unexpected complex output of sqrt for Hermitian matrices

### ISSUE THREAD

**Issue by Marco-Congedo** [JuliaLang/julia#31479]
Hello,

   if you have two symmetric positive definite matrices *A* and *B* (flagged as Hermitian), then sqrt(*AB*) should return the principal square root, which is real with all positive eigenvalues. Instead, i obtain a complex matrix. Is this the expected behavior? Here is an example:

```
julia> using LinearAlgebra

julia> A_=randn(2,2);

julia> A=Hermitian(A_*A_')
2×2 Hermitian{Float64,Array{Float64,2}}:
  0.466231  -0.496549
 -0.496549   5.01204

julia> B_=randn(2,2);

julia> B=Hermitian(B_*B_')
2×2 Hermitian{Float64,Array{Float64,2}}:
  1.84785   -0.196971
 -0.196971   0.385703

julia> sqrt(A*B)
2×2 Array{Complex{Float64},2}:
  0.926667+0.0im  -0.122345+0.0im
 -0.822429+0.0im    1.38937+0.0im

julia> eigvals(A*B)
2-element Array{Float64,1}:
 0.5858484070508339
 2.4044487716272123
```

**Comment by antoine-levitt** [comment]
Your matrix is the product of two symmetric definite matrices, which guarantees real eigenvalues, but julia has no way to know that and falls back to a regular matrix sqrt for non symmetric matrices. If you really, really want to use symmetric routines, you can use AB=SSBSS^-1 where S = sqrt(A), and compute the square root of SBS

**Comment by Marco-Congedo** [comment]
I am taking the real part of the output of sqrt(AB) for now and that is working fine. Thanks for the suggestion :)
