### ISSUE TITLE
Error if there are comments between docstring and function 

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#31470]
According to https://docs.julialang.org/en/v1/manual/documentation/index.html, "... no blank lines or comments may intervene between a docstring and the documented object". At the moment, the docstring is just ignored. Could this be more strictly enforced with an error?

I ran into this with Revise/JuliaDebugger, see https://github.com/timholy/Revise.jl/issues/253.

**Comment by fredrikekre** [comment]
How should you determine that the string is indeed a docstring if it is not directly attached to the object?

**Comment by thofma** [comment]
I thought that the `@doc` macro would indicate this.

**Comment by StefanKarpinski** [comment]
There are no uses of the `@doc` macro in those examples...

**Comment by thofma** [comment]
I think either
```
@doc doc"""
bla
"""
# s
function f() 
  return 1
end
```
is valid julia syntax and there is a bug in JuliaDebugger (timholy/Revise.jl#253), or it is not valid julia syntax but julia is still parsing it. Or there is a third option that I am not aware of.

**Comment by mbauman** [comment]
```
@doc doc"""
bla
"""
```

That's a valid Julia expression.  Without a third argument  `@doc x` just _looks up_ the documentation in `x`.  So I think there's still a bug in JuliaInterpreter — it flags that it a doc expression but then attempts to access a third argument to the macro.  https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/c04924e6c822bdbb059a3ccff7e11192fae4f809/src/construct.jl#L414-L420

**Comment by StefanKarpinski** [comment]
Without the `@doc` it's perfectly valid to just have a string expression that's not attached to anything.
