### ISSUE TITLE
julia ignores $PWD environment variable

### ISSUE THREAD

**Issue by rcurtin** [JuliaLang/julia#31474]
Hi there,

I searched through the (somewhat intimidating :)) list of existing issues and did not find anything like this, so I thought it was worthwhile to open a bug report.

In my work with Julia I would like to manually specify the working directory that Julia is using when I start Julia.  To do this, I do what I might normally do with other programs and, e.g., use the `PWD` environment variable.  However, `pwd()` in Julia still uses the directory I started Julia in.  Here is an easily reproducible example:

```
$ pwd
/home/ryan/some_directory
$ PWD=/home/ryan/ /opt/julia-1.1.0/bin/julia
              _
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
 (_)     | (_) (_)    |
  _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
 | | | | | | |/ _` |  |
 | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> pwd()
"/home/ryan/some_directory"
```

We can even see that Julia does have the correct `PWD`:

```
julia> ENV
Base.EnvDict with 26 entries:
 "PWD"                      => "/home/ryan"
 "SHELL"                    => "/bin/bash"
 ...
```

So, this forces me to do the somewhat head-scratchey line at the top of the script I want to call...

```
cd(ENV["PWD])
```

This seems like a bug to me.  Should there be support for Julia to use `$PWD` to set its directory on startup?

Thanks!

**Comment by yuyichao** [comment]
Afaict nothing respect PWD for this purpose. You should just change the current directory before starting Julia.

**Comment by rcurtin** [comment]
Thanks for the response.  You are right, I had a misconception about how I could use `$PWD`.  In any case, what brought me to this issue was not exactly that but another error in what I was working on, and I am able to get Julia to start with the right working directory.  Sorry for the noise.
