### ISSUE TITLE
Loop vectorization inconsistent after small code change

### ISSUE THREAD

**Issue by ndinsmore** [JuliaLang/julia#31482]
I am finding that what code gets optimized is very fickle, almost to the point of wondering if there is a hidden bug.

Consider the following code which is meant to sum every fourth value gets summed:
There is a function that uses a for loop then there is one that uses a `@goto` and a while loop.   The latter is important because I would argue that this is the pattern that loops that use an `iterate` function which contains it's own inner loop gets lowered to.

The performance is 10x ( `for` better than `while` ) different even though they should be effectivly the same loop on iterate is inlined.
```julia 
using BenchmarkTools
a=collect(1:4000)
b=a.*0
b[(a.%4).==0].=a[(a.%4).==0]   # make everything but every forth element 0
using BenchmarkTools

function simple_for_sum(a::Vector{T}) where T
    L = length(a)
    ret=zero(T)
    v=ret
    for i=1:L
        if @inbounds a[i] != zero(T)
             v = @inbounds a[i]
            ret += v
        end
    end
    return ret
end

function simple_while_sum(a::Vector{T}) where T
    L = length(a)
    ret=zero(T)
    i=0
    v=ret
    @goto loop
    @label action
    v = @inbounds a[i]
    ret += v
    @label loop
    while  i != L # This should be equivalent to the test that the for loop below get inlined to 
        i +=1
        if @inbounds a[i] != zero(T)
            @goto action
        end
    end
    return ret
end
```

results:
```julia 
julia> simple_while_sum(b)
2002000

julia> @benchmark simple_while_sum(b)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     2.872 μs (0.00% GC)
  median time:      3.518 μs (0.00% GC)
  mean time:        4.108 μs (0.00% GC)
  maximum time:     236.942 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     9

julia> simple_for_sum(b)
2002000

julia> @benchmark simple_for_sum(b)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     227.291 ns (0.00% GC)
  median time:      263.107 ns (0.00% GC)
  mean time:        321.243 ns (5.52% GC)
  maximum time:     138.888 μs (99.72% GC)
  --------------
  samples:          10000
  evals/sample:     398
```

Okay so now if we instead embed the`%` check in the function we get a reversal of the perf.
The only thing that has changed is the condition on the if statement. 
Now the while loop is 2x faster than the for loop.
```julia
function simple_for_sum_mod(a::Vector{T},m::T) where T
    L = length(a)
    ret=zero(T)
    v=ret
    for i=1:L
        if (@inbounds a[i] % m) == zero(T)
             v = @inbounds a[i]
            ret += v
        end
    end
    return ret
end

function simple_while_sum_mod(a::Vector{T},m::T) where T
    L = length(a)
    ret=zero(T)
    i=0
    v=ret
    
    @goto loop
    @label action
    v = @inbounds a[i]
    ret += v
    @label loop
    while  i != L
        i +=1
        if (@inbounds a[i] % m) == zero(T)
            @goto action
        end
    end
    return ret
end
```
Results:
```julia
julia> simple_while_sum_mod(a,4)
2002000

julia> @benchmark simple_while_sum_mod(a,4)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     11.061 μs (0.00% GC)
  median time:      15.855 μs (0.00% GC)
  mean time:        16.521 μs (0.00% GC)
  maximum time:     421.601 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> simple_for_sum_mod(a,4)
2002000

julia> @benchmark simple_for_sum_mod(a,4)
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     33.452 μs (0.00% GC)
  median time:      36.921 μs (0.00% GC)
  mean time:        55.951 μs (0.00% GC)
  maximum time:     10.838 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

The finally to take it back to the test case that i was trying to understand in the first place let do the same benchmark but store the values in a dict.
Spoiler the `for` loop is faster than the `while` ~5x

```julia
function iterator_sum_inline_while(iter::Base.ValueIterator{<:Dict})
    ret=0
    # Start
    d=iter.dict
    slots=d.slots
    vals=d.vals
    L=length(slots)

    state=d.idxfloor-1
    v=0
    
    @goto loop
    @label action
    v = @inbounds vals[state]
    ret+=v
    @label loop
    while state != L  # This is writen like this because this is how the for unit range should be inlined
        state  += 1
        if @inbounds slots[state] === 0x1
            @goto action
        end
    end
    return ret
end

function iterator_sum_inline_for(iter::Base.ValueIterator{<:Dict})
    ret=0
    d=iter.dict
    slots=d.slots
    vals=d.vals
    L=length(slots)

    state=d.idxfloor
    v=0
    for i=state:L
        if @inbounds slots[i] === 0x1
            v = @inbounds vals[i]
            ret+=v
        end
    end
    return ret
end

```

Results
```julia
julia> d=Dict(v=>v for v in 4:4:4000);

julia> iterator_sum_inline_while(values(d))
2002000

julia> @benchmark iterator_sum_inline_while(values(d))
BenchmarkTools.Trial: 
  memory estimate:  32 bytes
  allocs estimate:  2
  --------------
  minimum time:     5.040 μs (0.00% GC)
  median time:      6.269 μs (0.00% GC)
  mean time:        7.366 μs (0.00% GC)
  maximum time:     560.676 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     6

julia> iterator_sum_inline_for(values(d))
2002000

julia> @benchmark iterator_sum_inline_for(values(d))
BenchmarkTools.Trial: 
  memory estimate:  32 bytes
  allocs estimate:  2
  --------------
  minimum time:     843.299 ns (0.00% GC)
  median time:      1.333 μs (0.00% GC)
  mean time:        1.309 μs (1.94% GC)
  maximum time:     256.024 μs (99.37% GC)
  --------------
  samples:          10000
  evals/sample:     67
```

**Comment by KristofferC** [comment]
All of these differences is due to the auto-vectorizer in LLVM succeeding or failing. For example (by passing the env variable `-pass-remarks-analysis=loop-vectorize -pass-remarks=vector`:

```
julia> simple_while_sum(bremark: io.jl:618:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: io.jl:618:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: io.jl:618:0: loop not vectorized: value that could not be identified as reduction is used outside the loop
remark: io.jl:618:0: loop not vectorized: loop control flow is not understood by analyzer
remark: io.jl:618:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: io.jl:618:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: io.jl:618:0: loop not vectorized: loop control flow is not understood by analyzer

julia> simple_for_sum(b)
remark: REPL[4]:5:0: vectorized loop (vectorization width: 4, interleaved count: 4)
2002000
```

```
julia> simple_while_sum_mod(a,4)
remark: REPL[8]:12:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: REPL[8]:12:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: array.jl:729:0: loop not vectorized: value cannot be used outside the loop
remark: REPL[8]:12:0: loop not vectorized: loop control flow is not understood by analyzer
remark: REPL[8]:12:0: vectorized loop (vectorization width: 4, interleaved count: 4)
2002000

julia> simple_for_sum_mod(a,4)
remark: REPL[7]:5:0: vectorized loop (vectorization width: 4, interleaved count: 4)
remark: REPL[7]:5:0: vectorized loop (vectorization width: 4, interleaved count: 4)
2002000
```

```
julia> iterator_sum_inline_while(values(d))
remark: REPL[11]:17:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: REPL[11]:17:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: REPL[11]:17:0: loop not vectorized: loop control flow is not understood by analyzer
2002000

julia>  iterator_sum_inline_for(values(d))
remark: REPL[12]:10:0: vectorized loop (vectorization width: 4, interleaved count: 4)
2002000
```

**Comment by ndinsmore** [comment]
Do you have a sense of why `simple_for_sum_mod` is 30x slower than `simple_for_sum`  and emits:
```julia
julia> simple_for_sum_mod(a,4)
remark: REPL[7]:5:0: vectorized loop (vectorization width: 4, interleaved count: 4)
remark: REPL[7]:5:0: vectorized loop (vectorization width: 4, interleaved count: 4)
```
The two loops?

**Comment by ndinsmore** [comment]
Here is another point where a simple loop doesn't seem to be vectorized.  In pr #31452 
I am trying to change `skip_deleted` to look something like this but not so simple.
 d=Dict(v=>v for v in 1:1000);
 function skip_deleted2(h::Dict, i::Int)
     L = length(h.slots)
     slots=h.slots
     for i=i:L
         if @inbounds slots[i]==0x1
             return  i
         end
     end
     return nothing
 end

julia> skip_deleted2(d,1)
remark: none:5:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: none:5:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: none:5:0: loop not vectorized: loop control flow is not understood by analyzer
```

**Comment by yuyichao** [comment]
> `    while  i != L # This should be equivalent to the test that the for loop below get inlined to `

No. The better equivalent is

```
julia> function simple_while_sum(a::Vector{T}) where T
           L = length(a)
           ret=zero(T)
           i=0
           v=ret
           @goto loop
           @label action
           v = @inbounds a[i]
           ret += v
           @goto back; @label loop
           while  i != L # This should be equivalent to the test that the for loop below get inlined to 
               i +=1
               if @inbounds a[i] != zero(T)
                   @goto action; @label back
               end
           end
           return ret
       end
simple_while_sum (generic function with 1 method)
```

Yours is introducing very complicated control flow for LLVM to analyse.

It seems that your problems are all about introducing control flow. Since it's your own control flow, I don't think there's anything else we (julia) could do here, just like the other issue.

It's not to say there's nothing that can be done but it's exclusively LLVM domain (FWIW, I was recently also not super happy about LLVM's vectorizer in some cases that involves local control flow either..........) You are also certainly welcome to talk about llvm's loop vectorizer behavior on discourse.....

**Comment by yuyichao** [comment]
Oh, and for

> Okay so now if we instead embed the `%` check in the function we get a reversal of the perf.

That's also entirely LLVM's problem. The loop actually vectorizes just fine (at least for me for `Int` on 1.1.0 on x64). However, x86 (up to avx2 at least) doesn't seems to have a vectorized version of `%` on `Int64` (i.e. LLVM's `srem`) so LLVM emits a bunch of instructions to shuffle around vector registers and in order to do the operation on the scalar...... This makes the vectorized version do much work than the non-vectorized version so confusing llvm's vectorizer in this case gave you better performance... Oh well....

Still, same as the other one, there's nothing really we can do to help LLVM. It's literally working too hard..... We can try our best (and AFAICT we are) to tell LLVM what hardware we are running on but figuring out if the target has the needed instruction and make optimization decisions based on that is really a LLVM problem.

**Comment by ndinsmore** [comment]
@yuyichao it is still not clear whether the version of `skip_deleted2` above gets vectorized.   I ask because this could have an impact on #31452

**Comment by yuyichao** [comment]
No. That is very hard to vectorize since it's hard to prove that the memory is safe to access past the return point. Now if LLVM can align the loop it could assume the OOB read is benign (can't cross page boundary) but it doesn't.... (both worth fixing, both LLVM's issue).

This also won't be an issue on AArch64+SVE and control flow like this is exactly why they added the first fault load version of their instruction. Maybe masked load can handle this too....
