### ISSUE TITLE
code_llvm outputs invalid Unicode

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#31497]
```jl
julia> 𝔂() = 0

julia> @code_llvm 𝔂()
;  @ REPL[31]:1 within `𝔂'
define i64 @"julia_?\9D\94\82_12754"() {
top:
  ret i64 0
}

julia> isvalid(sprint(InteractiveUtils.code_llvm, 𝔂, ()))
false
```
Reported by @tk3369 in JuliaLang/IJulia.jl#724.

**Comment by stevengj** [comment]
Note that if I name the function `α()` instead then it works fine.   `𝔂` (U+01d502) is different in that it is an "astral plane" (non-BMP) character.

Does LLVM use UTF-16 internally somewhere?  UTF-16 code often screws up non-BMP characters because it forgets that they take up two 16-bit code units.

**Comment by inkydragon** [comment]
It seems like julia 0.6.4/0.7.0/1.0.4/1.1.1/1.2.0-rc3/1.3.0-alpha all works fine in my PC.

```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> 𝔂() = 0
𝔂 (generic function with 1 method)

julia> 𝔂()
0

julia> @code_llvm 𝔂()

;  @ REPL[20]:1 within `𝔂'
; Function Attrs: uwtable
define i64 @"julia_\F0\9D\94\82_12447"() #0 {
top:
  ret i64 0
}

julia> isvalid(sprint(InteractiveUtils.code_llvm, 𝔂, ()))
true

julia> sprint(InteractiveUtils.code_llvm, 𝔂, ())
"\n;  @ REPL[20]:1 within `𝔂'\n; Function Attrs: uwtable\ndefine i64 @\"julia_\\F0\\9D\\94\\82_12449\"() #0 {\ntop:\n  ret i64 0\n}\n"
```

**Comment by KristofferC** [comment]
> `@"julia_\F0\9D\94\82_12447"()`

That doesn't look so fine to me.

**Comment by yuyichao** [comment]
See the sprint results. Those are just ASCII I think.

**Comment by KristofferC** [comment]
Oh, sorry.

Maybe a mac issue then?

```
julia> Sys.isapple()
true

julia> isvalid(sprint(InteractiveUtils.code_llvm, 𝔂, ()))
false
```

**Comment by yuyichao** [comment]
It seems that LLVM is just not escaping the first `\f0` for whatever reason. The logic seems fine and isn't platform dependent. Someone that can reproduce this can probably breakpoint on `void llvm::printLLVMNameWithoutPrefix(raw_ostream &OS, StringRef Name)` to figure out what's happening.

**Comment by inkydragon** [comment]
This issue has been fixed in 1.6.3.

```julia
julia> 𝔂() = 0
𝔂  (generic function with 1 method)

julia> isvalid(sprint(InteractiveUtils.code_llvm, 𝔂, ()))
true

julia> @code_llvm 𝔂()
;  @ REPL[3]:1 within `𝔂'
define i64 @"julia_\F0\9D\94\82_191"() {
top:
  ret i64 0
}

julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4* (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin20.4.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

```

**Comment by stevengj** [comment]
Yes, I'm getting `isvalid == true` nowadays on my machine.

It's still printing a garbled symbol `define i64 @"julia_\F0\9D\94\82_157"() {` from the UTF-8 `codeunits` of that Unicode character:
```jl
julia> codeunits("𝔂")
4-element Base.CodeUnits{UInt8, String}:
 0xf0
 0x9d
 0x94
 0x82
```
Can we output the actual Unicode rather than ASCII escapes?

**Comment by stevengj** [comment]
Closing as the original issue seems to be fixed.
