### ISSUE TITLE
fragile tab-completion of getindex expressions

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#31498]
```jl
import REPL: REPLCompletions
REPLCompletions.completions("x[:\\alpha", 9, Main)
```
gives `(REPL.REPLCompletions.Completion[BslashCompletion("α")], 4:9, true)` as expected.

However, if I do
```jl
using PyCall
x = PyObject(1)
```
then tab-completion of `\alpha` breaks, and I get `(REPL.REPLCompletions.Completion[], 0:-1, false)` (no completions) instead.

From JuliaLang/IJulia.jl#733, cc @cscherrer.

**Comment by stevengj** [comment]
Actually, it happens whenever `x` is anything other than an `Array` or `AbstractDict`, e.g. with `x = 1:10`.

The problem is apparently with the `(true,nothing,nothing)` return branches in the `dict_identifier_key` function of REPLCompletions.  It seems like these should just return `nothing, nothing, nothing`?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/24705?

PR: https://github.com/JuliaLang/julia/pull/25094
