### ISSUE TITLE
seg fault with dlopen

### ISSUE THREAD

**Issue by daviehh** [JuliaLang/julia#31517]
Consider 2 libraries A and B, `dlopen` separately works but open & close A, then open B leads to seg fault. This has recently caused trouble on macOS for Cairo.jl, reported and discussed https://github.com/JuliaGraphics/Cairo.jl/issues/271

Code to reproduce: https://github.com/JuliaGraphics/Cairo.jl/issues/271#issuecomment-477397526
or
https://github.com/daviehh/TestCairo.jl/blob/master/test/runtests.jl

CI: https://travis-ci.org/daviehh/TestCairo.jl/jobs/512297364#L421

**Comment by daviehh** [comment]
reported upstream since it's not an issue with julia, since this segfault can be reproduced with this c code:

```
#include <dlfcn.h>
#include <iostream>

using namespace std;

int main(int argc, char* argv[]) {

    void *handle;

    handle = dlopen("/path/to/libpango-1.0.dylib",RTLD_LAZY);
    cout<<dlclose(handle)<<endl;

    handle = dlopen("/path/to/libgobject-2.0.dylib",RTLD_LAZY);
    cout<<dlclose(handle)<<endl;

    return 0;
}
```

closing this since it's not specific to julia but rather upstream

**Comment by cormullion** [comment]
@daviehh does “upstream” mean it won’t be fixed any time soon? 🙁

**Comment by StefanKarpinski** [comment]
Seems like maybe these versions of `libpango` and `libobject` are just incompatible?

**Comment by daviehh** [comment]
@cormullion not sure...maybe we may use the julia brew repo https://github.com/staticfloat/homebrew-juliadeps to temporary use an older working version of glib (I think last known working is 2.58.3) until it gets sorted out?

you may follow along at https://gitlab.gnome.org/GNOME/pango/issues/363

**Comment by cormullion** [comment]
@daviehh In any case, thanks for investigating this so thoroughly!

**Comment by daviehh** [comment]
@StefanKarpinski Sort of... it only segfaults when one first opens **and closes** `libpango`, then open `libgobject`; things like

```julia
using Homebrew
using Libdl

h = Libdl.dlopen(Homebrew.prefix()*"/lib/libpango-1.0",Libdl.RTLD_LAZY)
# returns Ptr{Nothing} @0x00007fcbef43eba0
g = Libdl.dlopen(Homebrew.prefix()*"/lib/libgobject-2.0.dylib",Libdl.RTLD_LAZY)
#returns Ptr{Nothing} @0x00007fcbef433400

dlclose(h)
dlclose(g)
```

works but

```julia
h = Libdl.dlopen(Homebrew.prefix()*"/lib/libpango-1.0",Libdl.RTLD_LAZY)
dlclose(h)
g = Libdl.dlopen(Homebrew.prefix()*"/lib/libgobject-2.0.dylib",Libdl.RTLD_LAZY)
```
segfaults.

**Comment by StefanKarpinski** [comment]
Would it help then to explicitly make sure that these are closed in order when Julia exits?

**Comment by lobingera** [comment]
@StefanKarpinski If I follow the thread on gnome dev correctly, your proposal - close them in order would help already - especially not closing them after testing. 
Still, as Behad mentions, this should have never really worked, it's strange it works on linux systems, but not on recent macOS (we only see this behaviour since around beginning of March).
I remember .so problems in Cairo (and especially CairoScript and Rsvg), but could never really track them down or reproduce - back then (around 0.6) in linux (my OS of choice).
