### ISSUE TITLE
Possible parsing bug: "unexpected comma in matrix expression"

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaLang/julia#31538]
This is superficially similar but probably unrelated to #29776 (in which digits were parsed as symbols, which is not the case here).
```julia
julia> r = rand(4,4)
4×4 Array{Float64,2}:
 0.710009  0.233203  0.740754  0.821618
 0.423516  0.704788  0.299154  0.292125
 0.706399  0.829231  0.514159  0.874359
 0.388578  0.804967  0.340397  0.114986

julia> 1.+(1:3)   # to avoid this ambiguity (which now throws an error)
ERROR: syntax: invalid syntax "1.+"; add space(s) to clarify

julia> 1 .+(1:3)   # inserting one space is usually sufficient
2:4

julia> 1 .+(1:3), 1 .+(1:3)   # it also works as a tuple
(2:4, 2:4)

julia> r[1 .+(1:3), 1 .+(1:3)]   # but apparently not here
ERROR: syntax: unexpected comma in matrix expression

julia> r[1 .+ (1:3), 1 .+ (1:3)]   # you also need a space before the parentheses, but why?
3×3 Array{Float64,2}:
 0.704788  0.299154  0.292125
 0.829231  0.514159  0.874359
 0.804967  0.340397  0.114986
```

**Comment by JeffBezanson** [comment]
> ```julia
> r[1 .+(1:3), 1 .+(1:3)]
> ```

That is interpreted similarly to `[1 -2, 1 -3]`, where `1 -2` is a matrix row. `.+` and `.-` can also be unary operators. That's why it complains about a comma in a matrix expression. So this is intentional.

**Comment by niclasmattsson** [comment]
Aha, of course. I've never had to broadcast a unary operator so I didn't even consider that. Thanks for explaining and go ahead and close the issue if you want.

**Comment by StefanKarpinski** [comment]
Unfortunate but unavoidable hazard of space-sensitive syntax.
