### ISSUE TITLE
`≔` as infix operator `invalid syntax`

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#31547]
The following code produces a weird error:
```julia
julia> 2 ≔ 3
ERROR: syntax: invalid syntax (≔ 2 3)
```
This happens both with `≔` (`\coloneq`) and `⩴` (`\Coloneq`). This seems like an issue with the parser. Is this supposed to work? If not it should probably throw an error along the lines of `Is not an infix operator`. I've already asked on discourse but didn't get a response, so I thought I would open an issue.
I've tested it with 1.1 as well as the nightly build on 64-bit Linux.

**Comment by JeffBezanson** [comment]
This needs a better error. The situation is that this syntax can be parsed, and these are valid infix operators, but they have no standard meaning and so are basically only for macros at this point.
