### ISSUE TITLE
Build fails on Ubuntu with Nonrepresentable section on output

### ISSUE THREAD

**Issue by josefsachs** [JuliaLang/julia#31555]
With a fresh clone of master.  End of `make` output follows.
```
/usr/bin/ld: libuv_la-uv-common.o: access beyond end of merged section (6837)
/usr/bin/ld: libuv_la-uv-common.o: access beyond end of merged section (4256)
/usr/bin/ld: libuv_la-uv-common.o: access beyond end of merged section (5638)
/usr/bin/ld: /home/sachs/src/julia-master/usr/lib/libuv.a(libuv_la-uv-common.o)(.debug_info+0x10d7): reloc against `.debug_str': error 2
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [/home/sachs/src/julia-master/src/flisp/flisp] Error 1
make[1]: *** [flisp/libflisp.a] Error 2
make: *** [julia_flisp.boot.inc.phony] Error 2
```

**Comment by vchuravy** [comment]
Also recently seen on https://travis-ci.org/JuliaLang/julia/jobs/513419893

cc: @staticfloat

**Comment by staticfloat** [comment]
@josefsachs what kind of system are you running on (OS, architecture, etc...)?  What version of binutils (`ld --version`)?  What is the linker invocation that caused that error?

**Comment by josefsachs** [comment]
```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
$ uname -a
Linux sojaks.com 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by staticfloat** [comment]
This appears to be a bug in old `ld` (version `2.24`).  You have two options:

* Install the `binutils-2.26` package on Ubuntu 14.04, which will provide `ld-2.26`, then just copy `ld-2.26` over your `/usr/bin/ld` executable.  (Note I recommend backing that original linker up before doing this).  I have verified that this does indeed work, and compiles all the way through.

* Don't use BinaryBuilder LibUV, which seems to be the trouble child here triggering the `ld` bug.  You can do this by setting the `USE_BINARYBUILDER_LIBUV=0` make flag when compiling.

**Comment by vchuravy** [comment]
Can we make check the Ubuntu/ld version in the makefile and disable Libuv for that? I suspect there are still plenty of Supercomputer around that are not up to date in that regard

**Comment by josefsachs** [comment]
Works okay after upgrading to `binutils-2.26`. Thanks.

**Comment by owainkenwayucl** [comment]
So I've stumbled across this on RHEL 7.0 and there is an issue that `USE_BINARYBUILDER_LIBUV=0` doesn't work in `Make.user` as it seems to be ignored.

Appending it to `Make.inc` seems to solve the problem.

**Comment by owainkenwayucl** [comment]
I should add that all `USE_BINARYBUILDER` settings in `Make.user` are ignored.
