### ISSUE TITLE
Current master does not compile on ubuntu 16.04

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#31568]
I am trying to compile a freshly cloned julia master on Ubuntu 16.04 and get the following error:

```
/home/me/progs/julia/julia-master/deps/llvm.mk:525: warning: overriding recipe for target '/home/me/progs/julia/julia-master/usr-staging/LLVM.v6.0.1.tgz'
/home/me/progs/julia/julia-master/deps/llvm.mk:525: warning: ignoring old recipe for target '/home/me/progs/julia/julia-master/usr-staging/LLVM.v6.0.1.tgz'
/home/me/progs/julia/julia-master/deps/llvm.mk:525: *** Attempting to use gcc4 LLVM tarball, but compiling with cxx11 string ABI; set "CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" to avoid linker errors.  Stop.
Makefile:60: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

I guess this is because of https://github.com/JuliaLang/julia/commit/297f25aa2301265b8f5db263efb754731cac9959, how do I get julia to compile?

**Comment by fredrikekre** [comment]
Update `gcc`/`gfortran` to >= 7 or do what the error message suggest, `make CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0`.

**Comment by gdkrmr** [comment]
thanks, works now!

**Comment by hcarlsso** [comment]
> Update `gcc`/`gfortran` to >= 7 or do what the error message suggest, `make CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0`.

Can confirm that `make CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0` worked.

**Comment by samfux84** [comment]
Maybe

https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#required-build-tools-and-external-libraries

should be updated as it states that Julia can be built with GCC >= 4.7, which does not seem to be the case.
