### ISSUE TITLE
Breaking change in print(io::IO, f::Function)

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#31564]
#30565 introduced a breaking change (not even mentioned in the `NEWS.md`):

in Julia v1.1:
```julia
julia> using Dates

julia> string(week)
"Dates.week"
```
in `master`:
```julia
julia> using Dates

julia> string(week)
"week"
```

Honestly, I like the new behaviour better, I noticed the change in a code in which I was using a dirty hack to remove the module name (didn't know about `nameof`), but still this change is technically breaking.

**Comment by JeffBezanson** [comment]
I don't think we can do anything about this; as you observe, the presence of the module name was causing more problems than it solved.
