### ISSUE TITLE
make require_one_based_indexing part of the API

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#31582]
#30630 introduced the convenience function `Base.require_one_based_indexing`, which is very useful for conveying intent in assertions.

I propose that this is made part of the official API for, ideally, the 1.2 release. Not necessarily exported (to keep the namespace clean), just documented.

**Comment by tpapp** [comment]
@KristofferC, can you explain why you don't think it is a good idea?

**Comment by KristofferC** [comment]
`has_offset_axes` is already documented and anyone who needs this can just write their own function on top of that. The function has an ugly name, it will likely rarely be used and it doesn't seem worth exposing.

**Comment by mkitti** [comment]
This suggests that we should remove mention of `Base.require_one_based_indexing` from the documentation and prefer `has_offset_axes`.

**Comment by johnnychen94** [comment]
https://github.com/JuliaLang/julia/pull/43263 already documented it during the discussion on Yuri's blog so I figure this should be closed.
