### ISSUE TITLE
Add ohm `Ω` to latex symbols

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/julia#31589]
It would be nice if the symbol for 'OHM SIGN' (U+2126), i.e. Ω were added to [this file](https://github.com/JuliaLang/julia/blob/5a4843ec242fb0c5655fba97b38ea502eed6861d/stdlib/REPL/src/latex_symbols.jl). It's commonly used in electrical engineering for the unit of resistance. The symbol for 'INVERTED OHM SIGN' (U+02127), i.e. ℧ is already in the file and can be accessed using `\mho`, so it'd be best if this were accessible using `\ohm`.

**Comment by stevengj** [comment]
Yes, this seems reasonable to me.  It's easily confusable with Omega Ω (U+2126), but we also tab-complete `\Angstrom` as Å (U+212b) even though it is easily confusable with Å (U+00c5).

**Comment by JeffBezanson** [comment]
We already normalize ohm to Omega, but we might as well add this latex sequence.

**Comment by stevengj** [comment]
Oh, I didn't realize that NFC normalized these characters: I just checked and indeed it normalizes U+2126 (ohm) to U+03A9 (Omega) and U+202b (angstrom) to U+00c5 (A + ring).

**Comment by stevengj** [comment]
@kdheepak, this would be an easy PR if you want to give it a shot.

**Comment by kdheepak** [comment]
I would be happy to! I'll submit a PR in a few hours.
