### ISSUE TITLE
Error While Loading Julia

### ISSUE THREAD

**Issue by ibzananiri** [JuliaLang/julia#31599]
Please have a look at this error, I installed Julia Pro, and this is the error message I am getting.

I cannot figure it out on my own.

Please help.

Regards,

Issa

![image](https://user-images.githubusercontent.com/49239887/55501699-ab6f8e80-5653-11e9-97b9-91a7ff918952.png)

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/31597. Please don't spam new issues. 

Ask for help in discourse.julialang.org instead.

**Comment by ibzananiri** [comment]
KristofferC, 

If you have a serious answer about this issue, then answer it.
If not, do not delete the thread at least.

**Comment by KristofferC** [comment]
This is not the correct place to ask for help. This is for julia bugs. You want discourse.julialang.org.
