### ISSUE TITLE
Unknown Literal

### ISSUE THREAD

**Issue by ibzananiri** [JuliaLang/julia#31597]
Installation of Juloa done, but each time I open the julia I get OS error: unkown literal, something with characters.

I am working on Windows 10.

I am not able to run the simplest code. When I open it, it just puts the error message and I do know how to deal with it.

Regards,

Issa

**Comment by KristofferC** [comment]
Can you at least give us the error message so we have something to go on?

**Comment by ibzananiri** [comment]
![image](https://user-images.githubusercontent.com/49239887/55501781-d1952e80-5653-11e9-9546-19e37ad07de0.png)

**Comment by KristofferC** [comment]
Looks like you have some bad stuff in your `.julia/config/startup.jl` file. Either delete it or open it in a text editor and remove the stuff that causes the error.

Closing since not a julia bug.
