### ISSUE TITLE
binary build config issues

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#31591]
It turns out that if you don't have python installed, the build silently disables binary-builder. That is unhappy. Also, it is not respectful of user choice. It should set options with `?=` and/or common user options should be listed at the top of the Make.inc file.

**Comment by StefanKarpinski** [comment]
I think the right thing is to give a helpful error message telling the user to either install python or change the build options to build from source.

**Comment by vtjnash** [comment]
yeah, I _may_ have written this issue first, but then made the PR before submitting it https://github.com/JuliaLang/julia/pull/31592
