### ISSUE TITLE
uniform API for finding string or char within a string

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#31600]
I noticed a minor usability point that seems to have been lost in the 1.0 search and find shakeup. With the old `search` function, you could write `search(haystack::String, <char or string>)`, but now the syntax for finding a char is `findfirst(isequal(needle), haystack)` (returning an Int) and the syntax for finding a string is `findfirst(needle, haystack)` (returning a range).

The simplest approach seems to be to allow `findfirst(needle::Char, haystack)` --- returning a range for consistency?

**Comment by stevengj** [comment]
`findfirst(needle::Char, haystack)` seems fine to me, but I don't see why it should return a range; returning an index seems a lot easier to use in practice.

**Comment by sostock** [comment]
This was implemented in #31664.
