### ISSUE TITLE
Changing the values of a subvector returned by a function doesn't change the original vector.

### ISSUE THREAD

**Issue by matteoneri** [JuliaLang/julia#31611]
If I modify a subselection af an array, the array itself is modified (I assume the subselection is a reference to the same values. This behaviour is expected.

```julia> v = [1 2 3 4]
1×4 Array{Int64,2}:
 1  2  3  4

julia> v[[1 2]] = [5 5]
1×2 Array{Int64,2}:
 5  5

julia> v
1×4 Array{Int64,2}:
 5  5  3  4
```
If I have a function that has as an argument a vector `a`, modifies a subvector of `a` and returns a subvector `b` of `a`, something unexpected happens:
* the values of `a` are changed as expected
* changing the values of `b` doesn't change `a` anymore [not expected].
Is it wanted?

```julia> v = [1 2 3 4]
1×4 Array{Int64,2}:
 1  2  3  4

julia> function f(a)
           a[[1 2]] = [6 6]
           a[[1 2]]
       end
f (generic function with 1 method)

julia> vv = f(v)
1×2 Array{Int64,2}:
 6  6

julia> v
1×4 Array{Int64,2}:
 6  6  3  4

julia> vv[1] = 1
1

julia> vv
1×2 Array{Int64,2}:
 1  6

julia> v
1×4 Array{Int64,2}:
 6  6  3  4
```

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
