### ISSUE TITLE
Wrong indices of the diagonal of a submatrix

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#31627]
Wrong indices of the diagonal of a submatrix are produced by diagind:
```jl
n = 5
a = rand(n,n);            # matrix with stride(a,2) = n
m = 3
b = view(a,1:m,1:m);  # leading 3x3 submatrix with stride(b,2) = n
diagind(a)                 # the output is 1:6:25  which is correct
diagind(b)                 # the output is 1:4:9   which is incorrect; 
                                # the correct values should be 1:6:13,  to be computed as: 
1:stride(b,2)+1:(m-1)*stride(b,2)+m
                                # instead, the following computation is used in diagind
1:m+1:m*m

versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = "C:\Users\Andreas\AppData\Local\atom\app-1.35.1\atom.exe"  -a
  JULIA_NUM_THREADS = 4
```
[Edited for readability by @StefanKarpinski]

**Comment by mbauman** [comment]
This isn't a bug.

When we talk about indices in Julia, we're talking about the things that go inside the square brackets for a given object.

In this case, `b[diagind(b)]` does indeed return the elements on the diagonal.  In fact, it'll return the elements on the diagonal of `b` _no matter what `b` is_.  It doesn't return indices that refer to either the "parent" array or the memory storage locations.  If you want the strides/storage locations, you have to explicitly ask for them.

```julia
julia> n = 5
       a = rand(n,n)
       m = 3
       b = view(a,1:m,1:m);

julia> a[diagind(a)][1:3] == b[diagind(b)]
true
```

In general, you typically don't need to worry about strides in Julia unless you're doing interop with another language.
