### ISSUE TITLE
leading_zeros(::BigInt) not defined

### ISSUE THREAD

**Issue by narendrakpatel** [JuliaLang/julia#31629]
Julia 1.1.0
```julia
julia> leading_zeros(BigInt(1))
ERROR: MethodError: no method matching leading_zeros(::BigInt)
```
`trailing_zeros(::BigInt)` is defined so I think it makes sense that `leading_zeros(::BigInt)` is also defined.

**Comment by JeffBezanson** [comment]
But what is the correct answer to `leading_zeros(BigInt(1))`?

**Comment by narendrakpatel** [comment]
I was thinking that it should return 63.
i.e. for BigInt x: `leading_zeros(unsafe_load(x.d, abs(x.size)))`
But I am not sure what should be the behavior for -ve BigInts.

**Comment by JeffBezanson** [comment]
I think that's questionable; it feels like leaking an implementation detail (the size of limbs used to represent BigInts).

**Comment by narendrakpatel** [comment]
Agree. I had not considered that before. Shall I close this issue then?
