### ISSUE TITLE
Can't redirect stderr and stdout with & &>file.txt when using multiple cores

### ISSUE THREAD

**Issue by Helveg** [JuliaLang/julia#31628]
When I run a script from the shell as a process (`&`) and redirect stderr and stdout to a file (`&>../output.txt`)
```
> julia -p 24 bootstrap/multicore.jl & &>../output.txt
```
The output is still printed in the shell that I called it in, and when I close that terminal window the julia script crashes the first time it tries to print something. Probably because its stdout stream is closed.

Redirecting the output did work on a single worker:
```
> julia bootstrap/multicore.jl & &>../output.txt
```

Using `addprocs` inside of the script being called also causes the redirection problem.

**Comment by vtjnash** [comment]
What shell is this? In a posix shell, the `&>../output.txt` command shouldn't have any side-effect, and so the behavior described in the title is thus as I would expect for that command line. I have no idea why redirecting output worked for a single worker—with some testing (e.g. `(sleep 2; echo hi) & &>/dev/null`) my shell doesn't seem to have that issue.

**Comment by Helveg** [comment]
Hi! Yes I did the same tests you did and indeed the command that I use doesn't do what I thought it does. My observation that it did redirect on a single worker was most likely incorrect aswell! Sorry
