### ISSUE TITLE
Illegal instruction after ambiguous `convert` method

### ISSUE THREAD

**Issue by HFriberg** [JuliaLang/julia#31649]
A typo in one area of my codebase trigged illegal instructions at another, making it hard to debug. Here is my minimal example:
```
struct sparse_t
    val::Vector{Float64}
    sub::Vector{Int64}
end

# BUGGY SPARSE TO DENSE
# Should have been
#   Base.convert(::Type{Vector}, v::sparse_t) = copy(v.val)
#
Base.convert(Vector, v::sparse_t) = copy(v.val)

spvec = sparse_t(zeros(Float64,5), Vector{Int64}())
println(spvec)                                        # <-- Illegal instruction (core dumped)
```
I am aware that this might be a duplicate of #24499, but also note that this issue was closed without resolution. Is it possible to get proper errors at the print statement, or alternatively errors/warning about Base.convert definitions without explicit type information? Core dumps are scary..

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```

**Comment by KristofferC** [comment]
Likely dup of https://github.com/JuliaLang/julia/issues/29495.

**Comment by Keno** [comment]
This seems less bad of a method definition than overriding convert to a builtin. Maybe we should insert some typeasserts somewhere

**Comment by JeffBezanson** [comment]
I agree; this actually creates an ambiguity for any conversion of `sparse_t`, but I'd like to know why that causes invalid type inference and/or codegen instead of just an internal error as in #29495.

**Comment by Keno** [comment]
I think this might be the same issue as #30118. I'll take a look at fixing that.
