### ISSUE TITLE
Bug in division?

### ISSUE THREAD

**Issue by bencamm001** [JuliaLang/julia#31655]
Hey,

So I was mucking around with some division and noticed something odd when dividing by 1e-5. This seems like a bug?

julia> 5/0.00001
499999.99999999994

I thought it was a rounding error but I checked with:

julia> 5/0.00001 == 5e5
false

It appears to only do it for some integers:

julia> 6/0.00001 == 6e5
true

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by StefanKarpinski** [comment]
https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678
