### ISSUE TITLE
Internal error/MethodError in complex use case

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#31666]
With a certain application (actually in several cases) involving BAT.jl and a host of other packages, I get this error (reproducible):

```
Internal error: encountered unexpected error in runtime:
MethodError(f=typeof(Core.Compiler.fieldindex)(), args=(Random123.Philox4x{T, R} where R where T<:Union{UInt32, UInt64}, :ctr1, false), world=0x0000000000000eb9)
```

Apologies up front: I tried very hard, but wasn't able to create an MWE - as soon as I simplify things too much, the error goes away. On the other hand, I haven't been able to find a workaround that works for the actual (non-reduced) application either.

So here's a script (long, but as reduced as far as I could) "bat_julia_internal_error.jl", together with a Project and Manifest file that reproducibly causes the error: https://gist.github.com/oschulz/d2417a6259684861071ad098e3cafffa

Here's my system info:

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

OS: Ubuntu Linux 16.04, 64-bit

**Comment by vtjnash** [comment]
Did you get a backtrace? I see some problems, but wanted to see if they were likely to be the same as your issue.

**Comment by oschulz** [comment]
Oh, sure - I added a "backtrace.txt" to the gist (https://gist.github.com/oschulz/d2417a6259684861071ad098e3cafffa)

**Comment by oschulz** [comment]
@vtjnash, thanks for looking into this. Does my backtrace match what you see?

I discovered one more thing: The error only occurs if `BAT.unsafe_density_logval` is not type stable (BAT.jl uses it's return type to set type parameters of multiple structs it uses, so this results in a propagation of type-instability). When I change the last line in `BAT.unsafe_density_logval` to `Float64(sum(LL))::Float64`, the Julia-internal error goes away.

Hope this helps tracking down what's happening here ... still haven't been able to do a proper MWE, it seems this error really only occurs when things are quite complex, resp. deeply nested.

**Comment by vtjnash** [comment]
Yes, thanks. I believe #31670 should fix that

**Comment by oschulz** [comment]
Wow that was fast, thanks a lot @vtjnash!

**Comment by oschulz** [comment]
Thanks again!
