### ISSUE TITLE
Building with custom BLAS/LAPACK USE_SYSTEM_*

### ISSUE THREAD

**Issue by zerothi** [JuliaLang/julia#31683]
I am trying to build Julia using system libraries.
I downloaded `julia-1.1.0-full.tar.gz` from the Github repo.

Here is my `Make.user`
```bash
# BBUILD
USEGCC = 1
USEICC = 0
USE_SYSTEM_BLAS = 1
LIBBLAS = -L/opt/generic/build-tools/1.0/lib -L/opt/generic/gcc/8.3.0/lib -L/opt/generic/gcc/8.3.0/lib64 -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/generic/build-tools/1.0/lib -Wl,-rpath=/opt/generic/gcc/8.3.0/lib -Wl,-rpath=/opt/generic/gcc/8.3.0/lib64 -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas_omp
#LIBBLASNAME = libopenblas
USE_SYSTEM_LAPACK = 1
LIBLAPACK = -L/opt/generic/build-tools/1.0/lib -L/opt/generic/gcc/8.3.0/lib -L/opt/generic/gcc/8.3.0/lib64 -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/generic/build-tools/1.0/lib -Wl,-rpath=/opt/generic/gcc/8.3.0/lib -Wl,-rpath=/opt/generic/gcc/8.3.0/lib64 -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib -lopenblas_omp
#LIBLAPACKNAME = liblapack
LDFLAGS += -L/opt/gnu/8.3.0/openblas/0.3.5/lib -Wl,-rpath=/opt/gnu/8.3.0/openblas/0.3.5/lib

prefix = /opt/gnu/8.3.0/julia/1.1.0
```
When building it succeeds until it hits `LIBBLASNAME`.

1. No where in the build system is `LIBBLASNAME` documented on what its actual use is?
My guess is its used as a wrapped library that links to `LIBBLAS`? Same for `LIBLAPACKNAME`?
2. The build `make` fails at this point:
```bash
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
PATH=...very long path...
Discovered traces of libgfortran within . 
Got SONAMES of 
Warning: git information unavailable; versioning information limited
make[1]: *** [Makefile:177: /home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so] Error 1
make: *** [Makefile:63: julia-base] Error 2
```
3. Doing `make -d` I get:
```bash
Removing child 0x5563ff7d3650 PID 7662 from chain.
  Successfully remade target file 'version_git.jl.phony'.
  Considering target file 'symlink_system_libraries'.
   File 'symlink_system_libraries' does not exist.
   Looking for an implicit rule for 'symlink_system_libraries'.
   Trying pattern rule with stem 'symlink_system_libraries'.
   Trying implicit prerequisite 'symlink_system_libraries,v'.
   Trying pattern rule with stem 'symlink_system_libraries'.
   Trying implicit prerequisite 'RCS/symlink_system_libraries,v'.
   Trying pattern rule with stem 'symlink_system_libraries'.
   Trying implicit prerequisite 'RCS/symlink_system_libraries'.
   Trying pattern rule with stem 'symlink_system_libraries'.
   Trying implicit prerequisite 's.symlink_system_libraries'.
   Trying pattern rule with stem 'symlink_system_libraries'.
   Trying implicit prerequisite 'SCCS/s.symlink_system_libraries'.
   No implicit rule found for 'symlink_system_libraries'.
    Considering target file 'symlink_libblas'.
     File 'symlink_libblas' does not exist.
     Looking for an implicit rule for 'symlink_libblas'.
     Trying pattern rule with stem 'symlink_libblas'.
     Trying implicit prerequisite 'symlink_libblas,v'.
     Trying pattern rule with stem 'symlink_libblas'.
     Trying implicit prerequisite 'RCS/symlink_libblas,v'.
     Trying pattern rule with stem 'symlink_libblas'.
     Trying implicit prerequisite 'RCS/symlink_libblas'.
     Trying pattern rule with stem 'symlink_libblas'.
     Trying implicit prerequisite 's.symlink_libblas'.
     Trying pattern rule with stem 'symlink_libblas'.
     Trying implicit prerequisite 'SCCS/s.symlink_libblas'.
     No implicit rule found for 'symlink_libblas'.
      Considering target file '/home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so'.
       File '/home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so' does not exist.
       Finished prerequisites of target file '/home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so'.
      Must remake target '/home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so'.
Putting child 0x5563ff7e3690 (/home/nicpa/installation/bash-build/.compile/julia-1.1.0/usr/lib/julia/libblas.so) PID 7664 on the chain.
```
This makes sense, since no where can I find the target `libblas.so` library. However, if it should be created in case of `USE_SYSTEM_BLAS=1` then something seems off?

4. I have also tried `make -C deps distclean-openblas` and then redo `make`, still same error.
5. Finally I changed `LIBBLASNAME=libopenblas` and `LIBLAPACKNAME=$(LIBBLASNAME)` and ran `make -C deps distclean-openblas`, then `make` (I found #10558). And then it seems to work!

#29221 seems related and points out some of the build-problems that is easy to encounter on systems where you don't have the typical setup.

Well, the problem seems that `LIBBLASNAME` *has* to have some specific values which is not documented anywhere?

**Comment by ararslan** [comment]
Note that regarding `USE_SYSTEM_*` flags, the README states

> Please be aware that this procedure is not officially supported, as it introduces additional variability into the installation and versioning of the dependencies, and is recommended only for system package maintainers. Unexpected compile errors may result, as the build system will do no further checking to ensure the proper packages are installed.

The best course of action here is to not use system libraries, as doing so is not officially supported.

**Comment by ViralBShah** [comment]
You probably want to add a `Make.user` that sets `LIBBLASNAME` to the name of your blas library.

**Comment by zerothi** [comment]
@ararslan although you don't officially support it, it is still vital for e.g. package maintainers and thus is sort of needs to be supported :)
From my perspective I would really favour a build system that enables users to define external libraries as they please.

@ViralBShah yes, this seems to work. But how would you link against e.g. ATLAS which has `N>1` libraries required? That would not work unless you create a wrapper library in the ATLAS lib dir, and then specify that as `LIBBLASNAME`, or would it? It seems the `Makefile` build system in Julia heavily relies on single libraries rather than a suite of libraries.

**Comment by ViralBShah** [comment]
Yes, we do expect a single library. I thought the last I had seen, ATLAS used to be a single library. You can probably put a complete link string in `LIBBLAS` and the library name in `LIBBLASNAME`. Basically as long as you somehow get the right mix of -L and -l flags in there, it should work. Also see the `USE_ATLAS` section in `Make.inc`.

**Comment by ViralBShah** [comment]
I am going to close this as an issue, since there is not much else we will be able to change in the build system. But you should be able to make it work as above.

**Comment by zerothi** [comment]
@ViralBShah atlas provides `satlas`/`tatlas` which is a fat library linking to all 4 libraries, but in principle it comprises 4 libraries, `lapack`, `f77blas`, `cblas` and `atlas`. So in that case it is solved by ATLAS providing a complete library.

Anyway, thanks for your comments.
