### ISSUE TITLE
Package Compatibility Paragraph in Contributing.md is misleading

### ISSUE THREAD

**Issue by felixcremer** [JuliaLang/julia#31685]
The paragraph about [Package Compatibility](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#package-compatibility-across-releases) sounds like Julia is in contrast to Semantic Versioning.

Should this be changed in a paragraph about Semantic Versioning?

**Comment by JeffBezanson** [comment]
Yes. We should perhaps also stop recommending Compat.jl there.

**Comment by ararslan** [comment]
> We should perhaps also stop recommending Compat.jl there.

Someday Compat will be useful again (see https://github.com/JuliaLang/Compat.jl/issues/651), it just requires someone getting it into the proper state such that it serves its purpose again.

Anyway, that's an aside, just thought I'd mention it.
