### ISSUE TITLE
make test with user defined number of threads

### ISSUE THREAD

**Issue by zerothi** [JuliaLang/julia#31684]
I am compiling julia using `julia-1.1.0-full.tar.gz` from the Github repo.

After having build Julia I would like to run the tests.
```bash
export JULIA_NUM_THREADS=2
make test
```
However, I can't seem to control the number of sub-processes it starts which is problematic since it starts 4 julia (and I only have 2 physical cores). Secondly, it would be nice to have this control anyhow.

**Comment by JeffBezanson** [comment]
For multiprocessing (which is what the test suite uses) we use `JULIA_CPU_THREADS`.

**Comment by zerothi** [comment]
Thanks, I only found `JULIA_NUM_THREADS` in the Makefile (at least none of the variables are documented in the makefile/build readme)

Thanks for the swift response!
