### ISSUE TITLE
Source build fails very quickly on osx

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#31711]
![Screen Shot 2019-04-12 at 2 48 10 PM](https://user-images.githubusercontent.com/2896623/56065458-214db700-5d32-11e9-8f24-963066bacb28.png)

Commit: 3e6a8936bdc9dbe2b41156959cbddafdef3c3ef8 (Apr 12, 2019)
OSX 10.14.4

**Comment by vtjnash** [comment]
Looks like you have llvm installed in Homebrew and it's messing up your system configuration.

**Comment by quinnj** [comment]
Hmmm......I didn't explicitly install it; `brew uninstall llvm` fails. How do I figure out where it's coming from?

**Comment by quinnj** [comment]
Oh, nevermind. doing `brew uninstall llvm@4` seems to have solved it.
