### ISSUE TITLE
Elementwise operations .* and ./ are not broadcasting for all argument types

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#3171]
I've added broadcasting methods for `.*` and `./` in #3100 (for `StridedArray` arguments), but since there are other methods lying about that do not broadcast, they do not use broadcasting in all cases yet (and also since broadcasting does not yet work for any `AbstractArray` arguments yet). I've created this issue to track and discuss the cases that need to be taken care of.

Methods that don't broadcast:
- [ ] `range.jl`: `.*` and `./` between two `Ranges` (applies when one of the ranges is length one)
- [ ] `array.jl`:  `.*` and `./` between one `Ranges` and one `StridedArray`
- [ ] `bitarray.jl`: `.*` between `BitArray` and `BitArray` or `Array{Bool}` arguments
- [x] `sparse.jl`: `.*` between `SparseMatrixCSC` arguments (#10843)
- [ ] `array.jl`: `./` between `StridedArray` arguments of (possibly complex) integer element types.

Except for the last one, these all deal with non-`StridedArray` arguments, and are cases where a specialized implementation will probably beat a generic `AbstractArray` fallback. One option would be to teach the broadcast machinery how to do code those special cases with broadcasting once and for all. Or perhaps it might be better to handle them case by case.

The last case deals purely with `StridedArray` arguments; the issue here is with the result type. I'm thinking that we might want to introduce `quotient_type(S, T)` to compute the type of `x::S / y::T`. (The fallback could be `quotient_type(S, T) = promote_type(S, T)`.) Then, it should be straightforward to write a broadcasting `./` that produces the right result type.

Thoughts?

**Comment by ViralBShah** [comment]
It seems that many of these work now. I am closing this - but perhaps someone can find examples that still don't work.
