### ISSUE TITLE
Inconsistency in bool indexing of ranges

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#31726]
We currently have:
```
julia> x = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> x[true]
ERROR: ArgumentError: invalid index: true of type Bool
```

But the same operation for ranges does not throw an error:
```
julia> (1:3)[true]
1
```
and if I understand the intended rules correctly it should.

What is the expected behavior?

CC @nalimilan

**Comment by mbauman** [comment]
Yes, that should probably error.  It's an easy case to forget about when defining indexing with `::Integer` — and ranges in general don't need to convert to `Int` so they don't use the general `to_indices` conversion that would typically throw this error.

**Comment by mbauman** [comment]
I'm curious, did you run into this somewhere?

We disallow indexing by bare `Bool` only because arrays of `Bool` have special behavior (logical indexing) and unlike all other arrays they don't behave like an iterated indexing by their elements.  It's really just to protect against the `(1:3)[Any[true, true, true]]` case.

**Comment by bkamins** [comment]
We design `getindex`/`setindex!` rules for DataFrames.jl to be consistent with Base in 1.0 (so we run checks of Base in the process).

**Comment by bkamins** [comment]
I will make a PR also to fix the following bug:
```
julia> collect((1:2)[false:true:true]) # not OK
2-element Array{Int64,1}:
 0
 1

julia> collect(collect(1:2)[false:true:true]) # OK
1-element Array{Int64,1}:
 2
```

**Comment by bkamins** [comment]
Another problem of similar kind is:
```
julia> Base.OneTo(2)[Integer[true, true, true, true]]
4-element Array{Int64,1}:
 1
 1
 1
 1
```

**Comment by bkamins** [comment]
All issues I raised seem to have been resolved now, so I am closing the issue.
