### ISSUE TITLE
Can't do `using module` after `docstrings` inside a `module`

### ISSUE THREAD

**Issue by frankwswang** [JuliaLang/julia#31723]
Code Example:
```
module myModule1

    export foo1

    function foo1()
        st = "This is myModule1."
    end

end

using Main.myModule1

module myModule2

    """
    This is myModule2.
    """

    using Main.myModule1
    export foo2

    function foo2()
            st = foo1()
            st = replace(st, st[end-1] => '2')
            println(st)
    end
end
```
```
ERROR: cannot document the following expression:

using Main.myModule1
```
However, if I remove the `docstrings` the error also disappears. I don't know if this is a BUG and I haven't found related answers. Thank you!

**Comment by elextr** [comment]
Docstrings precede the thing they apply to, so you are doing what the error says, applying a docstring to the `using` which doesn't make sense.  To apply the docstring to the module it should be before the `module myModule2` line.

**Comment by fredrikekre** [comment]
Seems like this is working as intended.

**Comment by frankwswang** [comment]
> Docstrings precede the thing they apply to, so you are doing what the error says, applying a docstring to the `using` which doesn't make sense. To apply the docstring to the module it should be before the `module myModule2` line.

Okay, thank you for your explanations!
