### ISSUE TITLE
Sum of two Hermitian Matrices is not Hermitian

### ISSUE THREAD

**Issue by Marco-Congedo** [JuliaLang/julia#31731]
Hello,
 the sum of two symmetric matrices should be flagged as Hermitian
and this seems not the case now.
Here is an example (Julia Version 1.1.0).
The same thing happens when P and Q are complex and also for Symmetric matrices.

julia> P
3×3 LinearAlgebra.Hermitian{Float64,Array{Float64,2}}:
  3.69851    -0.0364136   0.004914
 -0.0364136   0.964787   -0.966531
  0.004914   -0.966531    1.7757

julia> Q
3×3 LinearAlgebra.Hermitian{Float64,Array{Float64,2}}:
  3.05221   2.72049   -0.659437
  2.72049   5.69997    0.348603
 -0.659437  0.348603   3.45141

julia> P+Q
3×3 Array{Float64,2}:
  6.75072    2.68407   -0.654523
  2.68407    6.66476   -0.617927
 -0.654523  -0.617927   5.22712

**Comment by fredrikekre** [comment]
Duplicate of #22550
