### ISSUE TITLE
binary output

### ISSUE THREAD

**Issue by mikelehu** [JuliaLang/julia#31757]
If you're dealing with large amounts of data, typically, you don't want to write 
big ASCII files. You want to write things as binary file (it takes less space to do that).
In most programming language that's easy but is there a way to write out (read) the numbers directly as binary in Julia? 

I have development my own functions to do that in C language and they can be called directly from Julia. I ask my self  if it would be interesting to develop package for this purpose and how could i do it.  

Regards,
Mikel

**Comment by KristofferC** [comment]
This is  more appropriate to post at https://discourse.julialang.org/. The Julia issue tracker if for bugs about the julia language itself.
