### ISSUE TITLE
Distribute macOS app and framework 

### ISSUE THREAD

**Issue by slarew** [JuliaLang/julia#31754]
Julia can now be packaged as a macOS framework with the merge of #18594.  This issue is to discuss distributing Julia as a macOS framework.  My proposal is at the bottom.

# macOS Frameworks

The framework directory structure is basically just a reshuffling of the traditional nix hierarchy (bin, lib, include, share, etc...), except macOS is smarter in its handling of frameworks compared to arbitrary directory structures.  Within the framework, symlinks recreate the *nix hier for compatibility.

Frameworks are versioned so multiple versions/variants of Julia can reside within the Julia.framework bundle.

With Apple's increasing strictness regarding codesigning, system integrity protection, and now notarization, the framework mechanism continues to be a supported means of packing executables, libraries, and resources on the macOS platform.

# Distribution

On the Mac, a user typically downloads an application contained in a zip file or dmg.  It's then up to the user if and where to move/install the app.

If the application is more complex, a .pkg file is distributed and the macOS installer machinery guides the user through an installation process.  Behind the scenes, the pkg can place files anywhere on the system (with permission) and run scripts.

# Proposal

Switch the official macOS release of Julia to distribute a macOS pkg installer containing the Julia framework alongside a simple companion app.  The user experience goes like this:

## Download and Install

Download the Julia-vers.pkg file and double-click/run it.  The standard macOS installer pops up and in a few clicks the user has Julia.app and Julia.framework installed.  If the user doesn't have admin/root privileges, the installer allows installation to the user's home directory.  The installer also provides an opportunity to show "tutorial" like instructions to the user.  Or more simply, the installer just gives the user a chance to read some instructions on how to get started.

Power users can do it all from the command line with the `installer` utility or simply unpack the .pkg archive with `xar`.

Uninstall? Just delete `Julia.framework/Versions/x.y` and/or `Julia.app` or have Julia.app do that for you.  Of course, Julia.app will gladly offer to remove MATLAB too. (jk)

## Run Julia

Run Julia.app from your dock, spotlight, etc. and a new Terminal window appears with a Julia REPL.  Perhaps a future Julia.app would natively run julia and host the REPL so Terminal isn't even necessary.  Julia.app lists all detected or provided installations and versions of Julia and enables the user to manage the list (set default version, uninstall versions, etc.).  Julia.app auto-updates (probably with Sparkle like other mac apps) and offers to install new versions when available.

Julia.app also does a few other macOS things like:
* Declare the Julia .jl file type and provide an icon.
* Provide a service to run snippets or .jl files.
* Integrate with AppleScript and system automation. (?)

## Really run Julia

For those who live in a shell (hi!), you simply point your PATH at the `Julia.framework/Versions/1.3/bin` directory and you're set.

Or skip all of this and just install julia with your favorite package manager.

**Comment by ViralBShah** [comment]
I love the general direction of this. Is it easy to have something to try out this experience?

**Comment by slarew** [comment]
In `contrib/mac/frameworkapp` you will find the beginnings of a new Julia.app and the Makefile to create the .pkg installer.  Running `make -C contrib/mac/frameworkapp O=../../../build APPLE_DEVELOPMENT_TEAM="**********"` will produce a Julia-version.pkg to try out.  You need a free Apple developer account since the hardened runtime is enabled in the Xcode project.  If you don't have one or you don't know your team ID (you can find it in the auto-generated certificate in Keychain Utility), I think hardened runtime could be turned off and then it will build without a team ID.

The app finds julia installations with a spotlight search and runs the latest version it finds in Terminal.  In that way, it functions similarly to the current Julia-x.y.app.  Also, the app declares the Julia .jl file type and provides an icon for them.

UI and controllers for managing installations and an auto or manual update mechanism doesn't exist yet.

**Comment by ViralBShah** [comment]
So is the proposal here that we continue having both the current thing and the new framework based thing - giving users an option to pick one?

**Comment by slarew** [comment]
I would advocate for replacing the current distribution method of app (in dmg, with binary-dist stuffed inside the app) with the installer that includes a new Julia.app and Julia.framework.

**Comment by clason** [comment]
Just a note that this will become more relevant with the next version macOS 10.15 (Catalina), probably in August: The (yet again further) restricted system integrity protection prevents julia being run from the terminal. (It is possible to grant security exceptions, but here you need to do this manually *for every single linked .dylib*.)

**Comment by ViralBShah** [comment]
The main downside of that would be that we end up moving away from the nice feature right now that everything goes into one user folder that needs no admin access.

**Comment by slarew** [comment]
I can't remember what the default is right now, but the installer doesn't require admin access if the user's home directory is chosen as the install target.    App gets put in `~/Applications` and framework in `~/Library/Frameworks`.

**Comment by ggggggggg** [comment]
This sounds great, could we have a checkbox to add `julia` to the path during installation?

**Comment by slarew** [comment]
Adding julia to the `PATH` from the installer would be convenient but I don't know of a universally available method for this.

There's `/etc/paths[.d]`([man 8 path_helper](x-man-page://8/path_helper)) but this is system-wide, requires root to modify, and isn't appropriate for a non-admin install to the user's home directory.  Also, `launchctl config user path` requires root. Messing with a user's `~/.bash_profile` or `~/.zprofile` seems risky and error-prone.

IIRC I added a note at the end of the installation that tells the user how to run `julia` and add it to `PATH`.

**Comment by ViralBShah** [comment]
Could do PATH in `~/.bashrc`

**Comment by DilumAluthge** [comment]
I'm a little confused by this proposal, and I apologize if I have misunderstood it.

Would this proposal eliminate the option of downloading a .DMG file that contains a `Julia-1.x.app` file that I can then copy to any location? If so, then I am strongly opposed to it.

Advantages of DMG with a self contained `Julia-1.x.app` :
- I can copy `Julia-1.x.app` to any location that I want
- Copying the `Julia-1.x.app` file to my desired location does not make modifications to other parts of my system

Disadvantages of macOS .pkg installers:
- Installers can run arbitrary scripts before, during, and after the installation process
    - All I want is a binary build of Julia. Why do I need to let an installer do anything to my system?
- Installers will write files to a prespecified set of locations. For example, if the installer is run without admin privileges, applications are installed to `~/Applications` and frameworks are installed to `~/Library/Frameworks`.
    - Shouldn't I be able to decide exactly where I keep my Julia binaries?
- In this proposal, the installer would install a macOS Framework.
    - I've had to deal with Frameworks in the past in the setting of Python. It was not a good experience. I often found that if I deleted, modified, or moved a Framework, then multiple pieces of Python-dependent software on my system would break. Additionally, I often found myself in DLL-hell (or whatever the macOS equivalent is), in which a piece of Python-dependent software had linked itself against one version of a Python Framework, and then when I replaced the Python Framework with a different version, everything broke.

I definitely understand and appreciate that many people would like the option of having a macOS .pkg installer that installs a macOS Framework. It seems like something that would be beneficial to other people, even if I would personally never use it. Thus, I strongly support the idea of distributing BOTH:
1. The current distribution method, i.e. a .DMG disk image, which contains a single file named `Julia-1.x.app`. The `Julia-1.x.app` is completely self contained - I can copy it to any location on my computer, and run it without have it interact with anything else or cause any other modifications to my system or my user profile.
2. The macOS .pkg installer that you describe in this post, which will install a Julia.app and a Julia.framework

So I plead with you to keep the current distribution method as a fully supported option for macOS users, even if you do add the method proposed here.

**Comment by jamie-arcc** [comment]
> Advantages of DMG with a self contained `Julia-1.x.app` :
> 
> * I can copy `Julia-1.x.app` to any location that I want
> * Copying the `Julia-1.x.app` file to my desired location does not make modifications to other parts of my system.
> * The `Julia-1.x.app` is self contained, and it does not interact with the rest of my system (apart from `~/.julia` of course).

The .pkg installer can do all of this still.  It can be an installer option or you can, as suggested, manually extract the app with `xar`
 
> Disadvantages of macOS .pkg installers:
> 
> * Installers can run arbitrary scripts before, during, and after the installation process.

These can be controlled with check boxes, and "arbitrary" isn't all that meaningful here in the context of open source software where you know what the scripts are.
 
>   * All I want is a binary build of Julia. Why do I need to let an installer do anything else to my system?
> * Installers will write files to a prespecified set of locations. For example, if the installer is run without admin privileges, applications are installed to `~/Applications` and frameworks are installed to `~/Library/Frameworks`.
>   
>   * Shouldn't I be able to decide exactly where I keep my Julia binaries?

The user can set these options before installing within the installer

> * In this proposal, the installer would install a macOS Framework.

The proposal is to have installing the framework as an _option_ with a checkbox or whatever in the installer

>   
>   * I've had to deal with Frameworks in the past in the setting of Python. It was not a good experience. I often found that if I deleted, modified, or moved a Framework, then multiple pieces of Python-dependent software on my system would break. Additionally, I often found myself in DLL-hell (or whatever the macOS equivalent is), in which a piece of Python-dependent software had linked itself against one version of a Python Framework, and then when I replaced the Python Framework with a different version, everything broke.
> 
> I definitely understand and appreciate that many people would like the option of having a macOS .pkg installer that installs a macOS Framework. It seems like something that would be beneficial to other people, even if I would personally never use it. Thus, I would suggest the idea of distributing both:
> 
> 1. The macOS .pkg installer that you describe in this post, which will install a Julia.app and a Julia.framework
> 2. A .DMG disk image with a single self-contained `Julia-1.x.app` (the current distribution method)
> 
> I strongly urge that we continue to support the current distribution method for macOS users, even if we do add the method proposed here.

I'm not against maintaining both unless it becomes a significant effort to do so
