### ISSUE TITLE
Integrate mac framework with CI

### ISSUE THREAD

**Issue by slarew** [JuliaLang/julia#31755]
CI needed for the mac framework merged in #18594.

From a quick look at build.julialang.org, it seems the `make app` step should package the framework (and new app?) and upload this instead of the dmg containing julia-x.y.app.  The test step would then need to be [modified to unarchive](https://github.com/JuliaCI/julia-buildbot/blob/bfd97054485407c0bb1f567e27a0c92d36fc282b/master/builder_utils.py#L148) (or install? #31754) the framework and point to the right `julia` binary within the framework.

**Comment by ViralBShah** [comment]
Closing as discussed in https://github.com/JuliaLang/julia/pull/31914#issuecomment-1050388293
