### ISSUE TITLE
Stop CI testing Pkg for every PR

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#31774]
Pkg has tests that semi-frequently fails due to connection issues and we are already running CI on Pkg on its own repo so double running it seems excessive. There is of course a risk that changes to Base breaks Pkg but we can either run the Pkg tests on the buildbots that create the nightlies so we do not upload a nightly with breaking Pkg or we can just fix it if Pkg happens to break (it will be quite obvious when that happens).

**Comment by StefanKarpinski** [comment]
Agree, should stop running Pkg tests on master.

**Comment by JeffBezanson** [comment]
Triage is ok with this.

**Comment by ararslan** [comment]
Triage is still okay with this, 2 weeks later.

**Comment by fredrikekre** [comment]
I think I have a branch for this somewhere
