### ISSUE TITLE
occursin() bug

### ISSUE THREAD

**Issue by Wei-TianHao** [JuliaLang/julia#31798]
occursin function always returns true when there is an empty string in a string array.
```
julia> a = ["a", "b", ""]
3-element Array{String,1}:
 "a"
 "b"
 ""

julia> occursin.(a, "v")
3-element BitArray{1}:
 false
 false
  true
```

**Comment by JeffBezanson** [comment]
This is just because `occursin("", x)` is true for all x, which is correct. Every string contains the empty string as a subsequence.

**Comment by StefanKarpinski** [comment]
Closing since this isn't a bug.
