### ISSUE TITLE
有没有中国人呢？😹，昨晚问了一个清华和一个北大的博士生，没人用 julia，都是用 Python 搞 AI

### ISSUE THREAD

**Issue by keenlovelife** [JuliaLang/julia#31797]
Is there a Chinese? Yesterday, I asked a Tsinghua University and a Peking University doctoral student last night. No one used julia, they all used Python to engage in AI.  —— translate.google

**Comment by ViralBShah** [comment]
You may want to discuss on http://discourse.juliacn.com/
