### ISSUE TITLE
Error in command line arg --project with "~"

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/julia#31793]
As discussed in [Error in command line arg --project with "~"](https://discourse.julialang.org/t/error-in-command-line-arg-project-with/23307), a possibility is to use something like `expanduser` to avoid having this issue. Ideally, the `~` character should only be matched at the beginning of the path.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/28638
