### ISSUE TITLE
Refs don't compare equal

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#31813]
I found this surprising:
```julia
julia> Base.RefValue{Int64}(0) == Base.RefValue{Int64}(0)
false

julia> isequal(Base.RefValue{Int64}(0), Base.RefValue{Int64}(0))
false
```
This seems inconsistent with how we treat other 1D containers, e.g.
```julia
julia> Int64[1] == Int64[1]
true
```
`@which` shows `==` on `Ref`s using the fallback method, which suggests to me that having them not compare equal was not necessarily a specific design choice.

It would be nice to be able to compare `Ref`s conveniently. Implementing it should be as simple as adding
```julia
==(x::Ref, y::Ref) = x[] == y[]
```
Thoughts?

**Comment by JeffBezanson** [comment]
This might be ok, since the explicit purpose of Refs is to create a mutable location. Hard to say though.

**Comment by vtjnash** [comment]
It was an explicit choice at the time, although on the other hand, it wasn’t certain whether they would be contained-like

**Comment by StefanKarpinski** [comment]
The main argument for equality to me is that's how arrays behave and a Ref is very much like a zero-dimensional array.

**Comment by JeffBezanson** [comment]
A Ref is *like* a 0-d array in many ways, but according to the type hierarchy it isn't an array. So I think we have some flexibility here and I'm not sure changing this is for the best.
