### ISSUE TITLE
Both LinearAlgebra and LinearAlgebra.BLAS export dot

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#31838]
This is quite annoying:
```
julia> using LinearAlgebra

julia> using LinearAlgebra.BLAS

julia> dot
WARNING: both BLAS and LinearAlgebra export "dot"; uses of it in module Main must be qualified
ERROR: UndefVarError: dot not defined
```
It seems like BLAS should either extend `dot` from LinearAlgebra or not export its own `dot`.

**Comment by andreasnoack** [comment]
Should we consider not exporting anything from `BLAS` such that you always fully quality uses of `BLAS` functions?

**Comment by ararslan** [comment]
I really like being able to do `using LinearAlgebra.BLAS` and having access to `gemm`, `syrk`, etc. unqualified.

**Comment by StefanKarpinski** [comment]
Let's just unexport the controversial one instead of making this more of a decision.

**Comment by musm** [comment]
Is it really necessary to make a  change here? The `BLAS`  library is a low level wrapper, which, presumably,   mainly library writers are calling and if not, it seems like it would be better to just directly import the  BLAS functions you want instead? 

I do think either keeping the exports or unexporting them all makes the  most sense, and is a  consistent decision.

**Comment by ararslan** [comment]
The way I see it is, if you're saying `using LinearAlgebra.BLAS`, you're explicitly asking for access to the BLAS names. Doing that in general is unlikely to be all that common, but when it is, it's _immensely_ useful. I've run into that multiple times in the past couple of weeks. It quickly becomes really annoying to not be able to use `dot`. It doesn't make sense to me to say "you can't have exports because this is a low-level wrapper."
