### ISSUE TITLE
`eigmax` type constrained differently than `eigmin`

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/julia#31843]
Implementing `eigvals` for an `AbstractMatrix` gets you `eigmin` but not `eigmax`.

I think [the definition for `eigmax`](https://github.com/JuliaLang/julia/blob/f227b9b1feb9a6f41ba24cbfd5508a0acda443bd/stdlib/LinearAlgebra/src/eigen.jl#L275) should change `StridedMatrix` -> `AbstractMatrix` (to match [the definition of `eigmin`](https://github.com/JuliaLang/julia/blob/f227b9b1feb9a6f41ba24cbfd5508a0acda443bd/stdlib/LinearAlgebra/src/eigen.jl#L316))?

Example:
```julia
julia> using LinearAlgebra

julia> struct MyMat{T} <: AbstractMatrix{T}
           data::AbstractMatrix{T}
       end

julia> Base.getindex(m::MyMat, i, j) = getindex(m.data, i, j)

julia> Base.size(m::MyMat) = size(m.data)

julia> LinearAlgebra.eigvals(m::MyMat; kwargs...) = eigvals(m.data; kwargs...)

julia> M = MyMat(rand(3,3))
3×3 MyMat{Float64}:
 0.316192  0.915257  0.559555
 0.153994  0.978667  0.406342
 0.114911  0.249647  0.87979

julia> eigvals(M)
3-element Array{Float64,1}:
 1.4367338354952857
 0.13582144904446486
 0.6020940832444935

julia> eigmin(M)
0.13582144904446486

julia> eigmax(M)
ERROR: MethodError: no method matching eigmax(::MyMat{Float64})
Closest candidates are:
  eigmax(::SymTridiagonal) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/tridiag.jl:227
```

**Comment by andreasnoack** [comment]
I agree. It would be great if you could prepare a PR.

**Comment by nickrobinson251** [comment]
(related https://github.com/JuliaLang/julia/issues/31389)

**Comment by nickrobinson251** [comment]
actually should be fixed by https://github.com/JuliaLang/julia/pull/31117 :D

**Comment by dkarrasch** [comment]
Looks like this is fixed and can be closed? The above code does no longer error.
