### ISSUE TITLE
Docs for how to implement broadcasting for immutable arrays

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#31844]
If an Array type is immutable (like StaticArrays.jl)
or does not allow `setindex!`, like Tracker.jl
then the implementation of broadcasting customisation using `similar`
as described in the docs does not work

Tracker.jl does this by overloading [`materialize`](https://github.com/FluxML/Tracker.jl/blob/1d77f46bfd0d91fde830b4e7208326e666b92821/src/lib/array.jl#L496-L538)

StaticArrays.jl does this by overloading [`copy/copyto`](https://github.com/JuliaArrays/StaticArrays.jl/blob/ec26f0ac48b895c677ce05819ea7c9c58c412e19/src/broadcast.jl#L21-L40)

A documented preferred solution would be good to have

**Comment by mbauman** [comment]
Agree that we need this.  At first glance, I think the "best" place to latch in here would be in `copy(::Broadcasted{StaticStyle})` as StaticArrays does.  Note that the StaticArray's `copyto!` overrides are for copying a broadcasted expression into a mutable array.

**Comment by oxinabox** [comment]
@MikeInnes  do you think switching Tracker to overload `copy!` rather than `materialize` would be good? If so I can make a PR.

**Comment by MikeInnes** [comment]
I guess you mean `copy`? But sure, no objection in principle.

**Comment by oxinabox** [comment]
I don't know when it was done but this was done
