### ISSUE TITLE
build target `getall` fails on mac. Should we keep it or get rid of it?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#31857]
I think with all the pre-built dependencies, it is not as useful to support the `getall` target. We can require that people build on an internet connected computer or use pre-built binaries.

```
~/julia$ make -C deps getall
/Users/viral/julia/deps/tools/jldownload /Users/viral/julia/deps/srccache/LibUnwind.v1.3.1.x86_64-apple-darwin14.tar.gz https://github.com/JuliaPackaging/Yggdrasil/releases/download/LibUnwind-v1.3.1-3/LibUnwind.v1.3.1.x86_64-apple-darwin14.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0    178      0  0:00:02  0:00:02 --:--:--   178
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [/Users/viral/julia/deps/srccache/LibUnwind.v1.3.1.x86_64-apple-darwin14.tar.gz] Error 22
```

**Comment by vtjnash** [comment]
We should probably pass `USE_BINARYBUILDER=0` from `make full-source-dist`, so that we can still create archive files.

And, fwiw, you probably wanted the `make get` target (which downloads just the set for your machine)

**Comment by ViralBShah** [comment]
Ok - the README instructed to do `make getall` for buliding on a disconnected machine - which is not a particularly interesting corner case to support.

**Comment by vtjnash** [comment]
That should perhaps recommend using the full-source tarballs now instead? Or perhaps just note that you need to set `USE_BINARYBUILDER=0`

**Comment by ViralBShah** [comment]
I've removed this from the documentation.
