### ISSUE TITLE
[Dates] size and length not defined for DateTime

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaLang/julia#31868]
`size(Dates.DateTime(2016, 04, 10))`
`ERROR: MethodError: no method matching size(::DateTime)`
should yield
`()`

`length(Dates.DateTime(2016, 04, 10))`
`ERROR: MethodError: no method matching length(::DateTime)`
should yield
`1`

**Comment by oxinabox** [comment]
Why would you expect these to be defined?
What utility do you wish to get out of having this?

Things that are not iterable do not normally define these (infact not even all of them define them [few more rules around that](https://docs.julialang.org/en/v1/manual/interfaces/index.html#man-interface-iteration-1))
Note that `Number`s are iterable, which may have mislead you.

For example `Strings` do not define `size` (though they do length)
```
julia> size("some string")
ERROR: MethodError: no method matching size(::String)
```

**Comment by ohmsweetohm1** [comment]
Coming from MATLAB I wrote a function that checks something on a vector of DateTime and expected it to work with a single DateTime. But it does not.
The workaround I found is to dispatch on Array{DateTime} or DateTime and have to functions.

The actual problem was that indexin(DateTime, Array{DateTime}) does not work because length(DateTime) is not defined.

**Comment by StefanKarpinski** [comment]
What does the function that operates on a vector of DateTime do?

**Comment by ohmsweetohm1** [comment]
It checks what instances are on a holiday. The possible holidays are given by a vector of dates.

**Comment by JeffreySarnoff** [comment]
```
using Dates
isholiday(date::Date, holidays::Vector{Date}) = any(date .== holidays)
isholiday(datetime::DateTime, holidays::Vector{Date}) = isholiday(Date(datetime), holidays)
```

**Comment by StefanKarpinski** [comment]
You could also check `date in holidays` which doesn't need to construct a temporary boolean array.

**Comment by ohmsweetohm1** [comment]
Would such functionality be worthy to include in the Dates module?
Like: https://docs.scipy.org/doc/numpy/reference/generated/numpy.is_busday.html

**Comment by oxinabox** [comment]
We have packages for this. E.g. https://github.com/JuliaFinance/BusinessDays.jl
