### ISSUE TITLE
possible bug in reinterpret?

### ISSUE THREAD

**Issue by sanandak** [JuliaLang/julia#31863]
I have an array with 10 bytes.  I want to cast them into a struct with 3 2-byte and one 4-byte variable.  Code is below.

```
struct p1
    hdr::UInt16
    clid::UInt16
    ulen::UInt16
    iTOW::UInt32
end
xx=[0xb5, 0x62, 0x01, 0x02, 0x1c, 0x00, 0xe8, 0x56, 0xd6, 0x1c]
try
    yy=reinterpret(p1, xx)
catch ex
    println("fail")
end

push!(xx, 0x00)
push!(xx, 0x00)
yy=reinterpret(p1, xx)
println("$yy")

```
Result of running is this.  I have to add 2 bytes (and the reinterpret skips over 2 bytes)  The first 3 (2-byte) vars are fine, but the last 4-byte skips 2 bytes...?
```
julia> include("bug.jl")
fail
p1[p1(0x62b5, 0x0201, 0x001c, 0x00001cd6)]
```

**Comment by yuyichao** [comment]
This is the proper alignment of the type. There's no packed structure support so you need to read each fields separately.

**Comment by Keno** [comment]
FWIW, it is issues like these that make me discourage people from wanting to use the `reinterpret` function. It exposes details of the memory layout that users of julia ordinarily need not be aware of, including things like internal padding.
