### ISSUE TITLE
Icons and exe information are lost on windows installer

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#31876]
For some reason, from a fresh clean build of julia the installers no longer include `.ico` and no  information about the julia binary is attached to the exe.

**Comment by musm** [comment]
BTW I recently refreshed and updated cygwin. Not sure if changes there have impacted julia.

**Comment by musm** [comment]
So I'm not sure why then contrib/windows/julia.rc  is not working, in my configuration setup. `windres` seems to be working. 

```
$ windres --version
GNU windres (GNU Binutils) 2.31.1
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
```

**Comment by musm** [comment]
Any tips to help diagnose what's going on would be appreciated.

Is anyone else seeing this  (to test do `make binary-dist`, and install julia and check that julia.exe)

**Comment by musm** [comment]
Ok this is due to do https://github.com/JuliaLang/julia/pull/18594

**Comment by slarew** [comment]
I just scanned the changes in #18594 and nothing jumped out at me as affecting a Windows build.

**Comment by musm** [comment]
Honestly I'm not sure either. Yeah looking over nothing looks suspicious, yet when I checkout the commit before you change (the first commit making changes to the Makefile)  I see the icon properly installed, and on a master it's no longer present.

**Comment by musm** [comment]
I think I've isolated the issue to changes here
https://github.com/JuliaLang/julia/pull/18594/files#diff-89dd8a8fa41b0f5d42730eeebc7703efL69

**Comment by musm** [comment]
@slarew would you be able to open a PR based on  the  changes I linked above? I.e. removing `$<` is problematic.
