### ISSUE TITLE
error about the ODE solver

### ISSUE THREAD

**Issue by EmreEsenturk** [JuliaLang/julia#31892]
Hi I am a new user,
  I installed Julia version 1.1.0 with Jupyter. 
  I tried to solve a set of differential equations on my new computer but got the following messages

1) First I defined the ode:
…
prob = ODEProblem(exchangeDrivenGrowthRHS,c0,tspan,p)

which gave the notification

ODEProblem with uType Array{Float64,1} and tType Float64. In-place: true
timespan: (0.0, 100.0)
u0: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

which was okay 

2) Then. I tried to solve the ode with the TRBDF2 method defined in Julia

alg=TRBDF2()
sol = solve(prob,alg);
 
BUT I got the following error message:

UndefVarError: TRBDF2 not definedUndefVarError: TRBDF2 not defined

Stacktrace:
 [1] top-level scope at In[21]:1

The same exact code works fine in my other computer. The only difference is that the version that I am using in my other computer is Version 1.0.1. Note that the error has nothing to do with the specific method. Other ODE methods give the same error.

Any ideas why I am getting the error message?
Thanks

**Comment by simonbyrne** [comment]
Hi @EmreEsenturk,

This forum is for discussing issues with the Julia language itself. Questions about using Julia and its packages should be asked on one of the discussion areas, such as https://discourse.julialang.org/. The [DifferentialEquations.jl](https://github.com/JuliaDiffEq/DifferentialEquations.jl) package also has a public gitter chat forum: https://gitter.im/JuliaDiffEq/Lobby
