### ISSUE TITLE
atan(y,x) doesn't work with matrices

### ISSUE THREAD

**Issue by Colosus49** [JuliaLang/julia#31897]
I am trying to use atan on a matrix of complex numbers.
I tried atan(imag(L), real(L)) where L is a matrix of 1024 x 0124 complex number and I get this error:

ERROR: MethodError: no method matching atan(::Array{Float64,2}, ::Array{Float64,2})
Closest candidates are:
  atan(::AbstractArray{T,2} where T) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\dense.jl:1013
Stacktrace:
 [1] top-level scope at none:0

Is this expected?

I am running Julia Version 1.1.0 (2019-01-21)
on Atom 1.36.1x64 in a windows 10 home edition.

Thanks

**Comment by tomaklutfu** [comment]
It is expexted. You can use element-wise `atan2.(....)` (note dot after function name) for element-wise function. Also, please ask questions at https://discourse.julialang.org , here for bug reports only.

**Comment by Colosus49** [comment]
Thanks
