### ISSUE TITLE
REPL ctrl-p and up-arrow inconsistent behavior

### ISSUE THREAD

**Issue by albheim** [JuliaLang/julia#31898]
From the docs it seems up-arrow and ctrl-p should do the same thing.
The behavior I get is that if I have looked something up in help mode, up-arrow scrolls past this entry and continues scrolling in the reverse order. But using ctrl-p it seems to get stuck on whatever term I used help mode on and only scrolls through matching terms. And after using ctrl-p I get the same behavior with up-arrow until I have pressed enter after which up-arrow works like it did before again.

Example:
```
julia> testing=2;
julia> otherstuff=3;
help?> test
    .....
julia>  # here ctrl-p goes to test -> test|ing=2 with the cursor at the position with a |,
             going back with down-arrow will result in the same behavior for up-arrow
julia> # after pressing enter and pressing up-arrow I get test -> otherstuff=3 -> testing=2 and 
            and going back down with down-arrow ctrl-p will also have this behavior until enter is pressed

```

**Comment by albheim** [comment]
Also seems to work the same with pkg mode and shell mode.

**Comment by rfourquet** [comment]
I can't reproduce the inconsistency. In both cases, if the cursor is at the leftmost position, all the history is reachable (i.e. will show `otherstuff=3;`), but if the cursor has a "prefix" on its left, then the history is filtered by this prefix. Can you check again and if you confirm, show a sesion where the behavior diverges between the two combos (ctrl-p vs up-arrow) ?

**Comment by albheim** [comment]
I realized that it only happens when I used OhMyREPL (a tool to give the REPL some colors), so this is most likely an issue I should post there instead. Sorry for the confusion!
