### ISSUE TITLE
Docs: Source link MethodError directs to ./docs/basedocs.jl and not the source

### ISSUE THREAD

**Issue by taqtiqa-mark** [JuliaLang/julia#31905]
Hi,
Thank you for all the thought and effort that has gone into Julia, and for making it open source.

One way of coming to grips with the 'Julian-way' is to look at the source code in base.  
I believe most newcomers would expect a `source` link to take them to the source code for that type/method.

For example, the [`MethodError`](https://docs.julialang.org/en/v1/base/base/#Core.MethodError) documentation has such a source link.... which takes you, not to the source, but a a documentation file.

Is it possible to make such a `source` link take a user to the relevant lines in a source file?

If it is possible is there a reason why this is not done in the example, for instance?

Would this be considered a 'good-first-issue'?

**Comment by fredrikekre** [comment]
These links are intended as docstring-source links. Any further discussion is better suited for https://github.com/JuliaDocs/Documenter.jl
