### ISSUE TITLE
PCRE initialization error on alpine

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#31903]
I get the following error on alpine:
```
WARNING: Error during initialization of module PCRE:
ErrorException("could not load library "libpcre2-8"
Error loading shared library libpcre2-8.so: No such file or directory")
fatal: error thrown and no exception handler available.
InitError(mod=:Sys, error=ErrorException("could not load library "libpcre2-8"
Error loading shared library libpcre2-8.so: No such file or directory"))
rec_backtrace at /julia-source/src/stackwalk.c:94
jl_throw at /julia-source/src/task.c:210
jl_module_run_initializer at /julia-source/src/toplevel.c:81
_julia_init at /julia-source/src/init.c:854
main at /julia-source/ui/repl.c:211
__libc_start_main at /lib/ld-musl-x86_64.so.1 (unknown line)
```
which happens after packing a tarball with `make binary-dist` and then unpacking. Julia runs perfectly fine in the build directory.

Dockerfile:
```
FROM alpine:3.9.3
RUN apk add --update git make tar gcc python gfortran g++ perl
WORKDIR /julia-source
RUN git clone --progress https://github.com/JuliaLang/julia.git .
RUN echo 'override USE_BINARYBUILDER_UNWIND=0' >> Make.user
RUN make -j4
RUN make release
RUN make binary-dist
RUN mkdir -p /julia && tar -C /julia --strip-components=1 -xzf julia*.tar.gz
CMD ["/julia/bin/julia"]
```

**Comment by ararslan** [comment]
I downloaded the BinaryBuilder PCRE2 v10.31 in an Alpine Docker container, and using an old Julia build I had laying around (v1.2.0-DEV.448 from the beginning of March) I was able to `dlopen("libpcre2-8.so")`. That suggests to me that it isn't likely a problem with the library itself or how it was built. Maybe it's being installed in the wrong place so Julia doesn't know where to find it?

**Comment by ararslan** [comment]
Apologies, as this is a bit off topic, but from a clean environment on current master I'm not even able to get the build that far along. It tries to download the LLVM tarball corresponding to the wrong GCC version.
```
~/julia # make -j4 USECCACHE=1
Creating usr/etc/julia/startup.jl
Copying in usr/share/man/man1/julia.1
/root/julia/contrib/install.sh 755 /root/julia/contrib/julia-config.jl /root/julia/usr/share/julia/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0/root/julia/deps/llvm.mk:554: *** Attempting to use gcc4 LLVM tarball, but compiling with cxx11 string ABI; set "CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0" to avoid linker errors.  Stop.
make: *** [Makefile:60: julia-deps] Error 2
make: *** Waiting for unfinished jobs....
100   497  100   497    0     0    498      0 --:--:-- --:--:-- --:--:--   497
100 1871k  100 1871k    0     0   775k      0  0:00:02  0:00:02 --:--:-- 2785k
~/julia # gcc --version
gcc (Alpine 6.4.0) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ararslan** [comment]
I did an identical (or as much so as I could) build in an Ubuntu Docker container to compare `ldd`, `objdump -p`, etc. since I had a hunch that it could be an RPATH issue. Everything seems to be in order there, as far as I can tell...

@staticfloat, do you have any sagely debugging tips for us?

**Comment by fredrikekre** [comment]
Output of strace: https://gist.github.com/fredrikekre/7594317199e8139936e11408af8f2f8a

**Comment by ararslan** [comment]
```
open("/julia/bin/../lib/libpcre2-8", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
That isn't the right directory. You said `WORKDIR /julia-source` and cloned into `.`, so the root of the clone should be `/julia-source`, but it's looking in `/julia`. Furthermore, it should be looking for `libpcre2-8` in `lib/julia` rather than `lib`.

**Comment by fredrikekre** [comment]
I unpacked into `/julia`, but you are right, it should look in `/julia/bin/../julia/lib/libpcre2-8`.

**Comment by staticfloat** [comment]
My best guess here is that the `RPATH` of `julia` itself is `$ORIGIN/../lib`, and the RPATH of `libjulia` is `$ORIGIN:$ORIGIN/julia`.  This works fine on `glibc` (since the `dlopen("libpcre2-8")` is happening within `libjulia`, it uses the library's `RPATH`) but I wonder if `musl` instead pays attention only to the originating executable?  An easy way to test this would be to set the `julia` binary's `RPATH` to be `$ORIGIN/../lib:$ORIGIN/../lib/julia`.
