### ISSUE TITLE
unique() behaves strangely for mutables with custom == function

### ISSUE THREAD

**Issue by MaxPauer** [JuliaLang/julia#31940]
It seems to me like there is some problem with the implementation of unique.
When used on mutables which have a custom == operator implemented, sometimes, the results will differ from what you would expect, if the objectid is used for hashing.

When I run the following example, say a hundred times, it will work around 97 times. In the other 3 times the line marked [3] will error.
If I used the hashing function from line [1], everything will work as you'd expect.
Even more strangely, line [2] will always work.
Note that it does not make a difference if the x -> x predicate is used in line [3] or not.
Note as well, the example needs to be run multiple times from the console to fail, it does not suffice to put a loop around the tests.

```
using Test

mutable struct Mut
	val::Int
end

Base. ==(l::Mut, r::Mut) = true
#Base.hash(m::Mut, h::UInt=zero(UInt)) = hash(m.val, h) # [1] works as expected
Base.hash(m::Mut, h::UInt=zero(UInt)) = objectid(m)

m1 = Mut(1)
m2 = Mut(2)

@testset "unique" begin
	@test m1 == m2
	@test m1 !== m2

	arr = [m1, m1, m2]
	@test unique(x -> objectid(x), arr) == [m1, m2] # [2] always works
	@test unique(x -> x, arr) == [m1, m2] # [3] Sometimes == [m1]
end
```

```
 versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

**Comment by chethega** [comment]
`unique` assumes that `isequal(lhs, rhs)` implies `hash(lhs)==hash(rhs)`. This is needed for subquadratic `unique`. In your case, the correct hash function would be something like `hash(::Mut, h=UInt(0)) = 0xad8177d9dfe6d547`.

**Comment by mbauman** [comment]
Yes, while this is an easy trap to fall into it's not really an actionable bug beyond the existing issue to improve this situation: #12198

If you have further questions about this, I encourage you to use the [discourse message board](https://discourse.julialang.org).
