### ISSUE TITLE
Documentation for where keyword

### ISSUE THREAD

**Issue by Wimmerer** [JuliaLang/julia#32010]
I mentioned this on the Slack, but once I figured it out was told to make an issue here! The `where` keyword documentation is very lacking, and what exists is often quite difficult to find.

In particular while most keywords include some detailed explanation on their introduction in the _Manual_ section of the docs, `where` receives just a few examples with little explanation. From what I can tell where is used only with parametric types to define a set of types based on some expression (subtype being the most obvious/clear instance). It’s not clear to me from some significant searching the following issues:

- What the right hand argument of `where` can be. I know it can be a set of subtype statements, but that’s the extent of it. I have seen it used in many other ways, but with no explanation. I can generally parse it by reading carefully but it’s difficult to use myself and often involves a lot of trial and error.
- Syntax for more complex examples.
- Use with functions
- Finally, why `function foo(x::asdf{T}) where T<:Integer` works while `function foo(x::asdf{T<:Integer})` doesn’t work. The different places to use each syntax isn’t clear here. Sometimes I put the subtype operator in the curly braces next to the function/struct name, sometimes I put it in the `where` expression. 

Some of this is probably being a relatively young ~~grasshopper~~programmer, without much exposure to the languages that influenced Julia and without much use of parametric type systems. But a longer parametric type doc section, and a pile of explained examples would go a long way to helping folks like me.

E: It also doesn’t help that clicking on the keywords in the keyword Doc section brings you to documentation source, not actual code. I’m not sure if that’s desirable or not, but it would be helpful to see the code itself.

**Comment by JeffBezanson** [comment]
> E: It also doesn’t help that clicking on the keywords in the keyword Doc section brings you to documentation source, not actual code. I’m not sure if that’s desirable or not, but it would be helpful to see the code itself.

I don't think we can do anything about this except perhaps just remove the `source` link for keyword documentation. Language keywords don't have implementations you can point to like library functions.

**Comment by Wimmerer** [comment]
I figured that would be difficult/impossible. Is there a way to redirect the links to some explained example files? Maybe 3-4 examples of increasing complexity per keyword. I’d be happy to collect/work on  examples for those keywords I have a firm grasp of.
