### ISSUE TITLE
Tuple indexing sometimes type unstable in iterate(Generator) 

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#32011]
[By request](https://github.com/JuliaLang/julia/commit/4893840e410c65d94ef30de4908a370571c4ab02#commitcomment-33503745)

> 
> Tracked this down via git blame. I'm getting a bizarre error where the inference mixes up the [1] and [2] and just gives me a union of both types in both places. I fixed it by defining
> 
> ```
> @inline key(pair::Tuple{Any, Any}) = pair[1]
> @inline value(pair::Tuple{Any, Any}) = pair[2]
> @inline function iterate(g::Generator, s...)
>     y = iterate(g.iter, s...)
>     y === nothing && return nothing
>     y = y::Tuple{Any, Any} # try to give inference some idea of what to expect about the behavior of the next line
>     return (g.f(key(y)), value(y))
> end
> ```
> 

I wish I had a better way to reproduce this, but I don't. I suspect it will only crop up when inference is under a lot of stress. To reproduce:

1) Checkout the master version of LightQuery
2) Comment out this code at the end of rows.jl

```julia
@inline function iterate(g::Generator, s...)
    y = iterate(g.iter, s...)
    y === nothing && return nothing
    return (g.f(key(y)), value(y))
end
```

3) Run Pkg.test("LightQuery")

You'll get 
1) a bunch of doctests grumbling because of the new Dates printing format
2) This, which is by design

```julia
┌ Warning: Unable to infer the fieldtypes of the Varargs type Tuple{Tuple{Name{:date},Dates.Date},Vararg{Tuple{Name{_A} where _A,Int64},N} where N}, defaulting to `()` for empty iterators
```

3) This, which is unwelcome. 

```julia
┌ Warning: Unable to infer the fieldtypes of the Varargs type Tuple, defaulting to `()` for empty iterators
└ @ LightQuery C:\Users\hp\.julia\dev\LightQuery\src\utilities.jl:46
```

It comes from type instability of this line in the tutorial. `over` is just `Base.Generator` with the argument order reversed.

```julia
data =
        @> weathers_to_flights |>
        over(_, interested_in) |>
        flatten |>
        make_columns |>
        to_rows;
```

**Comment by KristofferC** [comment]
So you are saying that all attempts to minimize this (e.g. by removing the doctests, removing some other tests etc) have failed?

**Comment by bramtayl** [comment]
I could try to minimize it further if I had some clues as to what the underlying problem was.

**Comment by bramtayl** [comment]
But yes I use `over` all over the place and inference only fails for the most complex iterator.

**Comment by KristofferC** [comment]
> I could try to minimize it further if I had some clues as to what the underlying problem was.

This is usually not a requirement for minimizing. I usually just remove random code, see if the problem still occurs, manually inline a function, see if the problem still occurs and so on and so on, until there is nothing I can possibly remove or make simpler without the failure stops occurring.

**Comment by JeffBezanson** [comment]
It looks like this package is depending on the inferred type?

**Comment by bramtayl** [comment]
Only in the case of empty eltype unknown iterators, just like base.

**Comment by bramtayl** [comment]
Ok, thanks for the tip on example reducing. Here's a smaller way to replicated it:

Follow steps 1) and 2) above. Then run the following code:

```julia
@name @> (
    destination = ["ALB", "ANC", "ATL"],
    distance = [143, 3370, 746]
) |>
    to_rows |>
    Group(By(_, (:destination,))) |>
    over(_, @_ transform(key(_),
        number = length(value(_))
    )) |>
    when(_, @_ _.number != 1) |>
    make_columns
```

**Comment by bramtayl** [comment]
Is that helpful?

**Comment by bramtayl** [comment]
Well, I made `Group` more robust so you can't trigger this anymore.
