### ISSUE TITLE
Make stat exception better

### ISSUE THREAD

**Issue by travigd** [JuliaLang/julia#32030]
Currently, when a file fails to be `stat`'d, the error message is very generic:
```IOError: stat: permission denied (EACCES)```

It'd be really nice if this also included the file path for debugging. For example, something like:
```IOError: stat: permission denied (EACCES) for file "/path/to/file"```

Context: I'm getting this message trying to figure out multiple depot dirs so it's not clear which file exactly is failed to be `stat`d.

**Comment by Moelf** [comment]
I can work on this but how can I make `stat` to error? not even `sudo chmod 000 <file>` would make it permission denied it seems.

**Comment by fredrikekre** [comment]
See the linked PR: #32031
