### ISSUE TITLE
Currently the PDF format of the documentation isn't downloadable 

### ISSUE THREAD

**Issue by catastrop** [JuliaLang/julia#32049]

**Comment by fredrikekre** [comment]
This is becuse html docs have been generated for the new tag 1.1.1 (including the link), but there are no official binaries out yet, so https://github.com/JuliaLang/docs.julialang.org have not been able to build the pdf version yet. You can use https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.1.0.pdf for now.
