### ISSUE TITLE
ldiv!(Y, lu(X), I) fails

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#32069]
`ldiv!` doesn't recognize `I` (identity matrix) in the third position:

```julia
julia> Y = zeros(5,5);

julia> ldiv!(Y, lu(X), I)
ERROR: MethodError: no method matching ldiv!(::Array{Float64,2}, ::LU{Float64,Array{Float64,2}}, ::UniformScaling{Bool})
```

**Comment by KristofferC** [comment]
Use `one(Y)`. I don't think we can (or should) aim to support `I` everywhere since that will be an absolute explosion of methods that need to be implemented.
