### ISSUE TITLE
every time

### ISSUE THREAD

**Issue by waweruk2001** [JuliaLang/julia#32064]
every time i try to open a new IJulia notebook i am getting this response...help!!
 notebook()
[ Info: running setenv(`'C:\Users\admin\.julia\conda\3\Scripts\jupyter.exe' notebook`,["=::=::\\", "USERDOMAIN_ROAMINGPROFILE=DESKTOP-391TEVD", "PUBLIC=C:\\Users\\Public", "SYSTEMDRIVE=C:", "USERDOMAIN=DESKTOP-391TEVD", "PROCESSOR_ARCHITEW6432=AMD64", "WINDIR=C:\\WINDOWS", "BABEL_DATADIR=C:\\Users\\admin\\AppData\\Roaming\\OpenBabel-2.4.1\\data", "ONEDRIVE=C:\\Users\\admin\\OneDrive", "PROCESSOR_IDENTIFIER=AMD64 Family 21 Model 96 Stepping 1, AuthenticAMD", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "APPDATA=C:\\Users\\admin\\AppData\\Roaming", "SYSTEMROOT=C:\\WINDOWS", "TEMP=C:\\Users\\admin\\AppData\\Local\\Temp", "OS=Windows_NT", "PROGRAMW6432=C:\\Program Files", "PROCESSOR_REVISION=6001", "USERPROFILE=C:\\Users\\admin", "ONEDRIVECONSUMER=C:\\Users\\admin\\OneDrive", "COMPUTERNAME=DESKTOP-391TEVD", "HOMEDRIVE=C:", "NUMBER_OF_PROCESSORS=4", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "COMSPEC=C:\\WINDOWS\\system32\\cmd.exe", "LOGONSERVER=\\\\DESKTOP-391TEVD", "PSMODULEPATH=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\", "FPS_BROWSER_USER_PROFILE_STRING=Default", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "TMP=C:\\Users\\admin\\AppData\\Local\\Temp", "SESSIONNAME=Console", "COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\", "USERNAME=admin", "PROCESSOR_LEVEL=21", "PATH=C:\\Users\\admin\\.julia\\conda\\3\\Scripts;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files (x86)\\clisp-2.49;C:\\Users\\admin\\Anaconda2;C:\\Users\\admin\\Anaconda2\\Library\\mingw-w64\\bin;C:\\Users\\admin\\Anaconda2\\Library\\usr\\bin;C:\\Users\\admin\\Anaconda2\\Library\\bin;C:\\Users\\admin\\Anaconda2\\Scripts;C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\;C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python37-32\\;C:\\Program Files (x86)\\Mozilla Firefox;C:\\Program Files\\OpenBabel-2.4.1;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps", "OPENBLAS_MAIN_FREE=1", "LOCALAPPDATA=C:\\Users\\admin\\AppData\\Local", "ALLUSERSPROFILE=C:\\ProgramData", "PROGRAMDATA=C:\\ProgramData", "ASL.LOG=Destination=file", "PROCESSOR_ARCHITECTURE=x86", "COMMONPROGRAMFILES=C:\\Program Files (x86)\\Common Files", "PROGRAMFILES=C:\\Program Files (x86)", "HOMEPATH=\\Users\\admin"])

Thanks for contributing to the Julia project!

**Comment by rfourquet** [comment]
Please ask your questions at https://discourse.julialang.org/ (and try to choose a more descriptive title).
