### ISSUE TITLE
repeated threads loop hangs on windows

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#32087]
Calling this function on windows:
```
function f()
    nt = Threads.nthreads()
    for k in 1:5
        v = zeros(32 * nt)
        Threads.@threads for n in 1:nt
            for i in 1:100000000
                v[32 * n] += i
            end
        end
        @show k, v[32 .* (1:nt)]
    end
end
```
with JULIA_NUM_THREADS > 1 ends up hanging, using 100% of one CPU. It sometimes gets through some iterations of the outer loop first. Can anybody reproduce this? Works fine on linux.

**Comment by KristofferC** [comment]
Can repro on windows. On WSL it works fine.

**Comment by JeffBezanson** [comment]
Is it possible to attach a debugger and get the stack trace for each thread?

**Comment by JeffBezanson** [comment]
Did that, and I basically see thread 1 spinning or blocking while trying to `wait` on the thread loop tasks, even though all the tasks should have finished.

**Comment by JeffBezanson** [comment]
I also observe that sometimes when it appears to be hanging, simply attaching and detaching gdb makes it continue and make forward progress (i.e. print another line or two of output).

**Comment by JeffBezanson** [comment]
One theory I have is that this has to do with the delivery of signals from `uv_async_send`. It seems to be less predictable or work differently on windows.

**Comment by JeffBezanson** [comment]
Closed by #32109

**Comment by StefanKarpinski** [comment]
Should a new issue be opened to track fixing this in a better way?

**Comment by vtjnash** [comment]
The PR https://github.com/JuliaLang/julia/pull/32029 was also expected to fix this

**Comment by JeffBezanson** [comment]
I was hoping so, but I tried it and the problem was still there.
