### ISSUE TITLE
Using fill function to create array of dictionaries

### ISSUE THREAD

**Issue by olivier-perso** [JuliaLang/julia#32110]
Hi,

I want to create an array of dictionaries and I initially thought of using the 'fill' function:

`array_of_dict = fill( Dict{ String, Int64 }( ), 10 )`;

This function creates, as intended, an array containing 10 different dictionaries. However, as soon as I make a change to one of the dictionaries, that change seems to be applied to all dictionaries in the array. For instance, when I do:

`array_of_dict[1]["foo"] = 42;`

Although I want only the first dictionary in the array to be updated, every dictionaries in "array_of_dict" now contains the tuple `("foo" => 42)`:

<pre><font color="#8AE234"><b>julia&gt; </b></font>array_of_dict
10-element Array{Dict{String,Int64},1}:
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)
 Dict(&quot;foo&quot;=&gt;42)</pre>

I was able to create an array in a different manner however and it works fine when I update one of the dictionaries, but it is not as elegant:

```
array_of_dict = [];
for i = 1:10
    push!( array_of_dict, Dict{ String, Int64 }( ) );
end
```
I have considered using DataFrames, Arrays of Arrays and Dictionaries of Dictionaries, but I want the code to run as quickly as possible and I wanted to test different alternatives to find the best one. 

This is some information that may be relevant to this issue:

<pre><font color="#8AE234"><b>julia&gt; </b></font>versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
</pre>

**Comment by mbauman** [comment]
This is intentional behavior, and we have an open PR that aims to improve the documentation of fill in cases like these: https://github.com/JuliaLang/julia/pull/31516

The [discourse message board](https://discourse.julialang.org) would be the best place to have a discussion on alternatives.  Check out this thread as a starting point: https://discourse.julialang.org/t/fill-anarray-2-behaviour/22429

**Comment by JeffBezanson** [comment]
I would use a comprehension here: `[ Dict{ String, Int64 }() for _ = 1:10 ]`.
