### ISSUE TITLE
in round function  mistake? round(1.4999999999999999) ==2

### ISSUE THREAD

**Issue by programistawpf** [JuliaLang/julia#32116]
```
julia> round(1.4999999999999999)
2.0
julia> round(1.499999999999999)
1.0
```
julia 1.0.3
julia 0.7
win 7
paul

**Comment by rfourquet** [comment]
That's because `4999999999999999 === 1.5`. There are many discussions on discourse that you can search for on this topic.

**Comment by BartekK2** [comment]
That's because python isnt as much accurate so 1.49999999999999999999999999999 = 1.5 ---> round(1.5) = 2
read more about it there https://docs.python.org/3/tutorial/floatingpoint.html if u want
