### ISSUE TITLE
Bug in particular case of determinant function

### ISSUE THREAD

**Issue by JMmontilla** [JuliaLang/julia#32119]
I was getting a weird Method error when computing the ForwardDiff of the determinant, I have pinned it down to the particular case of the matrix being triangular, in which case the det function tries to convert the value of det before returning it. I have made this example in which I force the error:

```julia
using ForwardDiff, LinearAlgebra

A = zeros(Real,2,2)
function inter(M,x)
    a = x[1]
    b = x[2]
    M[1,1] = a^2-1.0
    M[1,2] = a-b-b^3
    M[2,1] = a*b
    M[2,2] = a-b
    nothing
end
function my_fun(M,x)
    inter(M,x)
    M[2,1] = 0.0 # Modification of M to make it triangular
    return det(M)
end

der = ForwardDiff.gradient(x -> my_fun(A,x), rand(2))
```
This is the method that causes the problem:
```julia
function det(A::AbstractMatrix{T}) where T
    if istriu(A) || istril(A)
        S = typeof((one(T)*zero(T) + zero(T))/one(T))
        return convert(S, det(UpperTriangular(A))) # Error here when trying to convert the Dual
    end
    return det(lu(A; check = false))
end
```

**Comment by KristofferC** [comment]
Just to add to this, the problem is

```
convert(S, det(UpperTriangular(A)))
```

where it assumes that you can convert any element that is a subtype of `T` to `S`. This fails if e.g. `T` is a `Real` because then we have

```
julia> T = Real
Real

julia> S = typeof((one(T)*zero(T) + zero(T))/one(T))
Float64
```

but an arbitrary subtype to `Real` can clearly not be guaranteed to be convertable to `Float64`.

**Comment by andreasnoack** [comment]
I think these type computations need to be something like
```
S = promote_type(T, typeof((one(T)*zero(T) + zero(T))/one(T)))
```
to this kind of wrong narrowing of the type. @JMmontilla it would be great if you could prepare a PR.

**Comment by vtjnash** [comment]
bump?
