### ISSUE TITLE
The sum of two `Array{T, 0}`s should be an `Array{T, 0}`

### ISSUE THREAD

**Issue by bzinberg** [JuliaLang/julia#32115]
Minimal example:
```jldoctest
julia> fill(1) + fill(2)
3
```

This causes pathologies such as
```jldoctest
julia> fill(1) + fill(2) + fill(3)
6

julia> (fill(1) + fill(2)) + fill(3)
ERROR: MethodError: no method matching +(::Int64, ::Array{Int64,0})
```

(In my opinion it should be possible to add an `Int64` to an `Array{Int64, 0}`, but that's a separate issue.)

**Comment by mbauman** [comment]
Thanks for the reminder. This is a dup of #28866, but this prompted me to propose a fix for it in #32122.
