### ISSUE TITLE
Functions are broken

### ISSUE THREAD

**Issue by zenbones** [JuliaLang/julia#32123]
In any other language I've ever worked with first class functions, if you pass the function
as an argument, that function handle is callable from any context running in the same process, period. That's kind of what makes it a first class function. It holds all the necessary information needed to properly call that behavior in the future, given an argument list. You can trust it.

I have some Julia 1.1 code. Module A has a data type which holds a map of function handles, i.e. ::Function. Module B holds an instance of the data type from A. Module B includes code from C.jl, via the include statement. C gets the same instance of the data type from A and registers a function.  C makes calls which end up in a method in B which uses the data type instance to call the function, and all is fine. Later some other code calls a method in B which uses the same instance of the data type to call the function. The function type itself exists and looks proper and has the correct name is it totally uncallable, always throwing MethodError. I have to say, not really a first class function then is it?

Shouldn't the function type hold whatever information it needs to complete that call? Why is the first class function usable from one context in the process, but not another, in the very same process. Not even a thread. Not remote. Just unusable.

Do I have something wrong or is the language this poorly thought out?

**Comment by JeffBezanson** [comment]
Is it possible to provide an executable example that reproduces the problem? This is difficult to evaluate without that. Also please try to use a productive tone; we are quite willing to help and fix things if necessary and phrasing a question or bug report as an attack is not helpful.

**Comment by yuyichao** [comment]
Please ask questions like this on discourse with the full code. You are likely just misusing the language in many of the common ways and the issue you see has nothing to do with function being first class or not.

**Comment by KristofferC** [comment]
Just to give the full link: https://discourse.julialang.org/.
