### ISSUE TITLE
Dividing by large integer numbers gives infinity

### ISSUE THREAD

**Issue by caprilo** [JuliaLang/julia#32136]
The operation `1/10^80` yields `Inf` as result. I believe this behavior is not only mathematically unexpected, but inconsistent with what happens when computing `1/10^18`, which gives `1.0e-18`. I believe it has something to do with precision issues while working with integers (since changing `10` for `10.0` gives a correct result), but anyway, I think `0` would be a much less troublesome result.

Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by JeffBezanson** [comment]
```
julia> 10^80
0
```

https://docs.julialang.org/en/v1/manual/faq/#Why-does-Julia-use-native-machine-integer-arithmetic?-1

**Comment by tomaklutfu** [comment]
This is because integer overflow. Look at `10^80=0`

**Comment by mbauman** [comment]
Welcome!  Yes, this is behaving as expected.  Further questions (and answers) about this behavior can be found on our message board at [discourse.julialang.org](https://discourse.julialang.org).  For example:

https://discourse.julialang.org/t/julia-messes-up-integer-exponents/20773
