### ISSUE TITLE
Type does not equal itself?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#32135]
From https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/737, https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/536089349#L808,

```julia
TypeError: in new, expected NTuple{49,Int64}, got NTuple{49,Int64}
```

Cannot reproduce locally, just on Travis. I am lost, because I used to believe that T == T for all types 😅 .

**Comment by iamed2** [comment]
This is called by https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/convert.jl#L4 so it might be some issue with `Tuple{Vararg{Int64, 49}}` vs `NTuple{49, Int64}`?

**Comment by JeffBezanson** [comment]
`Tuple{Vararg{Int64, 49}}` is `===` to `NTuple{49, Int64}`. This seems more like some kind of data corruption.

**Comment by StephenVavasis** [comment]
This may be unrelated, but I recently encountered an error message that a function expected a `SparseMatrixCSC{Float64,Int}` but received a `SparseMatrixCSC{Float64,Int}` instead.  After some digging, I concluded that the JLD2 package was assigning the wrong type (even though the name was correct) to an object read from a JLD2 file.  The workaround was to issue the commands `using SparseArrays` and `import SparseArrays.SparseMatrixCSC` before loading any modules (i.e., at the beginning of the script).

**Comment by timholy** [comment]
It is unrelated.

JLD2 will create a new type, with the same name, if it doesn't know the official one. That way you can at least load the data. JLD has `addrequire`, adding that to JLD2 might eliminate such problems, as long as the person saving the file remembers to use it.

**Comment by KristofferC** [comment]
Another case where something like this happened (PkgEval for 1.3-RC3):

```jl
history_recorder: Test Failed at /root/.julia/packages/POMDPSimulators/61Pgi/test/test_history_recorder.jl:145
  Expression: exception(exhist) !== nothing
   Evaluated: nothing !== nothing
Stacktrace:
 [1] top-level scope at /root/.julia/packages/POMDPSimulators/61Pgi/test/test_history_recorder.jl:145
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1105
 [4] include(::Module, ::String) at ./Base.jl:31
 [5] include(::String) at ./client.jl:432
 [6] top-level scope at /root/.julia/packages/POMDPSimulators/61Pgi/test/runtests.jl:19
 [7] top-level scope at /workspace/srcdir/julia/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107
 [8] top-level scope at /root/.julia/packages/POMDPSimulators/61Pgi/test/runtests.jl:19
```

**Comment by vtjnash** [comment]
Possibly fixed by https://github.com/JuliaLang/julia/pull/32605
