### ISSUE TITLE
Possible GC issues in LSODA benchmarks

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#32134]
When updating DiffEq's benchmarks to v1.0, we are encountering some odd GC issues that cause a segfault.

```julia
using DiffEqDevTools, LSODA, DiffEqBase

const k1=.35e0
const k2=.266e2
const k3=.123e5
const k4=.86e-3
const k5=.82e-3
const k6=.15e5
const k7=.13e-3
const k8=.24e5
const k9=.165e5
const k10=.9e4
const k11=.22e-1
const k12=.12e5
const k13=.188e1
const k14=.163e5
const k15=.48e7
const k16=.35e-3
const k17=.175e-1
const k18=.1e9
const k19=.444e12
const k20=.124e4
const k21=.21e1
const k22=.578e1
const k23=.474e-1
const k24=.178e4
const k25=.312e1

function f(dy,y,p,t)
 r1  = k1 *y[1]
 r2  = k2 *y[2]*y[4]
 r3  = k3 *y[5]*y[2]
 r4  = k4 *y[7]
 r5  = k5 *y[7]
 r6  = k6 *y[7]*y[6]
 r7  = k7 *y[9]
 r8  = k8 *y[9]*y[6]
 r9  = k9 *y[11]*y[2]
 r10 = k10*y[11]*y[1]
 r11 = k11*y[13]
 r12 = k12*y[10]*y[2]
 r13 = k13*y[14]
 r14 = k14*y[1]*y[6]
 r15 = k15*y[3]
 r16 = k16*y[4]
 r17 = k17*y[4]
 r18 = k18*y[16]
 r19 = k19*y[16]
 r20 = k20*y[17]*y[6]
 r21 = k21*y[19]
 r22 = k22*y[19]
 r23 = k23*y[1]*y[4]
 r24 = k24*y[19]*y[1]
 r25 = k25*y[20]

 dy[1]  = -r1-r10-r14-r23-r24+
          r2+r3+r9+r11+r12+r22+r25
 dy[2]  = -r2-r3-r9-r12+r1+r21
 dy[3]  = -r15+r1+r17+r19+r22
 dy[4]  = -r2-r16-r17-r23+r15
 dy[5]  = -r3+r4+r4+r6+r7+r13+r20
 dy[6]  = -r6-r8-r14-r20+r3+r18+r18
 dy[7]  = -r4-r5-r6+r13
 dy[8]  = r4+r5+r6+r7
 dy[9]  = -r7-r8
 dy[10] = -r12+r7+r9
 dy[11] = -r9-r10+r8+r11
 dy[12] = r9
 dy[13] = -r11+r10
 dy[14] = -r13+r12
 dy[15] = r14
 dy[16] = -r18-r19+r16
 dy[17] = -r20
 dy[18] = r20
 dy[19] = -r21-r22-r24+r23+r25
 dy[20] = -r25+r24
 return
end

u0 = zeros(20)
u0[2]  = 0.2
u0[4]  = 0.04
u0[7]  = 0.1
u0[8]  = 0.3
u0[9]  = 0.01
u0[17] = 0.007
prob = ODEProblem(f,u0,(0.0,60.0))

sol = solve(prob,lsoda(),abstol=1/10^14,reltol=1/10^14)
test_sol = TestSolution(sol)

setups = [Dict(:alg=>lsoda())]

abstols = 1.0 ./ 10.0 .^ (5:8)
reltols = 1.0 ./ 10.0 .^ (1:4);
wp = WorkPrecisionSet(prob,abstols,reltols,setups;appxsol=test_sol)
```

On releases or master of the 3 packages at top. The issue seems to be that https://github.com/rveltz/LSODA.jl/blob/master/src/common.jl#L15 is freed. However, that array is Julia managed, and so it's odd the GC loses track of it. Adding in GC preserve stuff to all functions doesn't even help fix it. Turning off the GC during calls to that function does fix it according to @YingboMa . This only became reproducible when we switched to using BenchmarkTools.jl, specifically using https://github.com/JuliaDiffEq/DiffEqDevTools.jl/blob/master/src/benchmark.jl#L190-L213 seems to be required to make this happen. 

I've been talking to @JeffBezanson about this so I wanted to document it here. This seems to be as much of an MWE as we can make, since if it's a smaller ODE the GC doesn't trigger at the time that would cause a segfault, and if it doesn't have that part of the BenchmarkTools call it can sometimes segfault but not reliably but might be the same thing (?), and it only seems to happen through this route with LSODA.jl.

**Comment by Keno** [comment]
Your context object (the `CommonFunction` one) gets freed. You need to GC preserve it or otherwise root it.

**Comment by Keno** [comment]
Looks like something is additionally doing a stack promotion of CommonFunction. The pointer_from_objref should prevent that.

**Comment by yuyichao** [comment]
By stack promotion you mean stack allocation? Neither pointer_from_objref or GC preserve should affect that.

**Comment by Keno** [comment]
` pointer_from_objref` should definitely prevent stack allocation, since taking it back with unsafe_pointer_to_objref afterwards is bad otherwise.

**Comment by Keno** [comment]
(Unless we can prove that the obtained pointer doesn't ever escape in a way that could be turned back into a reference).

**Comment by yuyichao** [comment]
Well, that has not been the case since the first stack allocation optimization.

`unsafe_ppinter_to_objref` cannot be called on the result for sure. See the definition of cconvert and unsafe convert for the correct way to get a heap pointer. (Unsafe load a pointer field)

**Comment by Keno** [comment]
The value is mutable and concrete though. Even unsafe_convert from a Ref uses pointer_from_objref in that case.

**Comment by yuyichao** [comment]
Yes? And that ref is allows to be stack allocated?

**Comment by Keno** [comment]
We're talking about the value inside the Ref though.

**Comment by yuyichao** [comment]
Correction, the case you need to look at is abstract type

**Comment by yuyichao** [comment]
Do note that for the c convertion using ref, there's no guarantee for heap pointer, you need Any for that. The current implementation simply make it well defined since immutable pointer doesn't survive through Julia reference.

**Comment by Keno** [comment]
Maybe we need to separate out the two concepts. `pointer_from_objref` is traditionally the function we use to get a heap reference to a mutable object.

**Comment by Keno** [comment]
Or maybe we just need to change the user facing `pointer_from_objref` to do the unsafe_load thing instead.

**Comment by Keno** [comment]
I think my suggestion would be to add an `unsafe_data_pointer` that behaves to stack promotion as what `julia.pointer_from_objref` does not and require whatever implements `pointer_from_objref` to preserve heap semantics, since it goes with `unsafe_pointer_to_objref`.

**Comment by yuyichao** [comment]
I'm fine with either, although I don't think we'll necessarily guarantee the unsafe_load thing is long term garanteed either. It's more of a implementation limit right now. (Assuming it's still a limitation). After all, that trick is only to ensure the pointer identity, not to ensure heap allocation.

The only way I can think of right now that is definitely guaranteed is `ccall` with `Any` argument type (for functions that cannot be learnt by codegen of course). This should be the difference between `Any` as argument type and `Ref{Any}` as argument type. `Any` should make sure it's a heap pointer whereas `Ref{Any}` just make sure it's a pointer to the data, stack or heap.

I didn't add anything new since I couldn't think of any need for it in real code. I only see this happen in cfunction's where the conversion from pointer to object is either explicit or implicit. However, in that case, the caller should use `Any` as the argument type in the first place so nothing more is needed. For a load from a field one should just use `Any` as the field type...

**Comment by vtjnash** [comment]
@yichao that seems like a good summary of the intended (and implemented) behaviors. Care to add that to the ccall docs (possible with examples showing how to use GC.preserve to delineate the lifetime)? I think that section is underdeveloped, and would be beneficial to clarify.

**Comment by ChrisRackauckas** [comment]
The PR https://github.com/rveltz/LSODA.jl/pull/60 implements the suggestions and now no longer crashes but uses a lot of memory, possibly leaking memory?

**Comment by ChrisRackauckas** [comment]
@keno's workaround works after a few more memory fixes.
