### ISSUE TITLE
Cross ref `summarysize` from `sizeof` docstring

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#32142]
It seems like a pretty common usecase that someone wanting the recursive behavour of `summarysize` would first call `sizeof` then realize it was too small,
and then go looking at the docsting of `sizeof`

So it would be good if that had a 
```
See also: [`sumarysize`](@ref) for the recursively calculated size of an object.
```

I would make a PR but I can't find where that docstring is.

**Comment by strickek** [comment]
base/strings/basic.jl 143ff

**Comment by laborg** [comment]
Done in https://github.com/JuliaLang/julia/pull/41453
