### ISSUE TITLE
CI succeeds even though doctests fail

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#32165]
For example https://travis-ci.org/JuliaLang/julia/jobs/538061759#L2348-L2444.

Ref: https://github.com/JuliaLang/julia/pull/31934/files/ec1ec94ee1ec3a5dec75aab8ba2ffc058f054839#diff-3bdc1dec4d0bc7efcaee2f72cf5e02e4

**Comment by fredrikekre** [comment]
Probably fixed by updating Documenter, c.f. https://github.com/JuliaDocs/Documenter.jl/pull/1014
