### ISSUE TITLE
Openssl library missing with linux mint

### ISSUE THREAD

**Issue by saersamani** [JuliaLang/julia#32163]
Hi,

I have recently moved my julia codes from a Windows machine to a linux mint one and getting the below error when trying to use a module that I wrote.

“error compiling import_files: error compiling cdf_Import: error compiling readCDF: error compiling getindex: error compiling variable: error compiling nc_inq_varid: could not load library “~/.julia/conda/3/lib/libnetcdf.so”
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_0i’ not found (required by ~/.julia/conda/3/lib/././libssl.so.1.1)
top-level scope at none:0”

I am using julia Version 1.1.1 (2019-05-16) and Python 3.6.7 (default, Oct 22 2018, 11:32:17).

Thanks for your help.

Cheers,
Saer

**Comment by ViralBShah** [comment]
This seems to be a conda issue. Definitely not a Julia issue. Maybe check on discourse or with the conda forums.

**Comment by saersamani** [comment]
I managed to solve the problem by re-installing the Openssl lib and the reinstalling julia. Thanks anyways.
