### ISSUE TITLE
SparseMatrixCSC multiplied by Adjoint

### ISSUE THREAD

**Issue by lanqingy** [JuliaLang/julia#32172]
The implementation of matrix multiplication `A * B` is incomplete when one of the matrices is of the type `SparseMatrixCSC` and the other one is of the type `Adjoint` or `Transpose`.

```julia
julia> A = sprandn(10000, 10000, .0001);

julia> B = randn(10000, 2);

julia> C = randn(2, 10000);
```
Matrices `B` and `C'`are of the same size. But there is a huge difference in performance when multiplying them with `A`.

```julia
julia> @benchmark A * B
BenchmarkTools.Trial: 
  memory estimate:  156.33 KiB
  allocs estimate:  2
  --------------
  minimum time:     131.769 μs (0.00% GC)
  median time:      197.825 μs (0.00% GC)
  mean time:        214.868 μs (8.74% GC)
  maximum time:     31.917 ms (99.32% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark A * C'
BenchmarkTools.Trial: 
  memory estimate:  156.67 KiB
  allocs estimate:  9
  --------------
  minimum time:     481.587 ms (0.00% GC)
  median time:      482.608 ms (0.00% GC)
  mean time:        483.716 ms (0.00% GC)
  maximum time:     489.008 ms (0.00% GC)
  --------------
  samples:          11
  evals/sample:     1


```
When `A` is multiplied by `C'`, a dense matrix multiplication is computed.
```julia
julia> @which A * C'
*(A::AbstractArray{T,2} where T, B::AbstractArray{T,2} where T) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:141

```
An easy but probably inefficient fix will be adding the following methods.
```julia
*(A::SparseMatrixCSC{TA,S}, x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}) where {TA,S,Tx} = A * copy(x)
*(A::Adjoint{<:Any,SparseMatrixCSC{TA,S}}, x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}) where {TA,S,Tx} = (x'A')'
*(x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}, A::SparseMatrixCSC{TA,S}) where {TA,S,Tx} = (A'x')'
*(x::Adjoint{<:Any,<:StridedVecOrMat{Tx}}, A::Adjoint{<:Any,SparseMatrixCSC{TA,S}}) where {TA,S,Tx} = (A'x')'
```
These four methods utilize existing methods and implement `A * C'`, `A' * C'`, `B' * A` and `B' * A'` respectively. The same needs to be done to fix `Transpose`.

```julia
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

```

**Comment by dkarrasch** [comment]
I think we should have `mul!` versions for these, and then send `*(A, B)` to `mul!(C, A, B)` for appropriately sized `C`, otherwise we're missing in-place versions.

**Comment by dkarrasch** [comment]
This can be solved as follows. Define
```julia
Base.:(*)(A::SparseMatrixCSC{TA,S}, B::Adjoint{<:Any,<:StridedMatrix{Tx}}) where {TA,S,Tx} =
    (T = promote_type(TA, Tx); mul!(similar(B, T, (A.m, size(B, 2))), A, B, one(T), zero(T)))
```
Additionally, one would need to expand the existing `mul!`s
https://github.com/JuliaLang/julia/blob/1a3f1f7d98c915a399f895a9035a042fd18d016e/stdlib/SparseArrays/src/linalg.jl#L33
https://github.com/JuliaLang/julia/blob/1a3f1f7d98c915a399f895a9035a042fd18d016e/stdlib/SparseArrays/src/linalg.jl#L57
https://github.com/JuliaLang/julia/blob/1a3f1f7d98c915a399f895a9035a042fd18d016e/stdlib/SparseArrays/src/linalg.jl#L83
to work with
```julia
B::Union{StridedVecOrMat, Adjoint{<:Any,<:StridedVecOrMat}, Transpose{<:Any,<:StridedVecOrMat}}
```
because the exact same code works in all cases, and I don't see how to improve it in each case. This approach would save us making the `copy`s in the OP. Does that have any chance to work? The other `*`s could be easily defined analogously.
