### ISSUE TITLE
NTuple without number parameter not working in master

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#32170]
Julia 1.1:
```julia
julia> NTuple{<:Integer}
Tuple{Vararg{T,#s38}} where T where #s38<:Integer
```
Master:
```julia
julia> NTuple{<:Integer}
ERROR: TypeVar in Vararg length must have bounds Union{} and Any
Stacktrace:
 [1] top-level scope at REPL[2]:1
```
Is this a breaking change or a bug fix because `X` in `NTuple{X}` should always mean the first parameter?

**Comment by JeffBezanson** [comment]
This is a bug fix; in `NTuple{N}`, `N` must *be* an Int; it doesn't make sense to say it's a subtype of Integer. For example
```
julia> NTuple{Int}
ERROR: TypeError: in Vararg, in count, expected Int64, got Type{Int64}
Stacktrace:
 [1] top-level scope at none:0
```
(since about v0.4).

**Comment by giordano** [comment]
Yeah, I had seen `NTuple{Int}` in Julia 1.1, that's why I asked if it was a bug fix.  The change however is making tests in `MLJ.jl` fail, I'm going to fix it.  Thanks!
