### ISSUE TITLE
Continuous integration tests need to be updated

### ISSUE THREAD

**Issue by KilimAnnejaro** [JuliaLang/julia#32183]
In looking over the output of https://github.com/JuliaLang/julia/pull/32086, I noticed that the tests appear to be returning inequality inappropriately, ie e-16 != 0. I'm not sure which version of the integration tests BuildBot is relying on, but I think they should be changed.

**Comment by JeffBezanson** [comment]
That appears to be an issue with the tests added by that PR. `1e-16 != 0` is also correct.
