### ISSUE TITLE
no method `copy(::Missing)`

### ISSUE THREAD

**Issue by denius** [JuliaLang/julia#32189]
`ERROR: MethodError: no method matching copy(::Missing)`

I suppose this can be fixed by adding `copy(::Missing) = missing` somewhere.

I discovered this when trying to use "empty" sparse matrices -- non-zero patterns with no values, like `sparse(transpose(similar(sprand(Bool,3,3,0.2), Missing)))`

**Comment by JeffBezanson** [comment]
Rather, I think the sparse code should not be calling `copy` here; it should not require the elements to have `copy` methods.
