### ISSUE TITLE
Subtyping not transitive with `Type`

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#32190]
Probably not relevant in practice, but
```
julia> Type{2}<:Int, Int<:Integer, Type{2}<:Integer
(true, true, false)
```

**Comment by JeffBezanson** [comment]
Yes, `Type{2}` is not supposed to be valid.

**Comment by adienes** [comment]
FWIW `Type{2} <: Int` now returns `false`

this is probably closable
