### ISSUE TITLE
`open` for processes is different with mode strings vs. keyword args

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#32193]
We allow both mode strings (`"r"` etc.) and keyword arguments (`read=true`) in `open` for both commands and files. Generally the mode strings correspond to equivalent keyword arguments. However they behave differently for processes:

```
julia> open(`ls foo`, read=true) do f
       end

julia> ls: cannot access foo: No such file or directory

julia> open(`ls foo`, "r") do f
       end
ls: cannot access foo: No such file or directory
ERROR: failed process: Process(`ls foo`, ProcessExited(2)) [2]
```

This is because there is a special method for opening a process with a function and mode string (which adds the ProcessFailedException), but the keyword arg form is caught by the fallback that just calls `close` when the function returns. I assume we want them both to give the ProcessFailedException?

**Comment by StefanKarpinski** [comment]
Yes, that sounds better. Probably a "minor change" for the 1.3 release.

**Comment by StefanKarpinski** [comment]
Triage thinks this was probably just a mistake that should be fixed but it's too potentially breaking for point releases.
