### ISSUE TITLE
Column ranges in Julia

### ISSUE THREAD

**Issue by Daniel-Fermoselle** [JuliaLang/julia#32239]
Hello, I am using Julia for my master thesis project and I would like to know if there are any plans for including column ranges in Julia’s base parser?

Thank you in advance for your attention.

**Comment by JeffBezanson** [comment]
Can you give an example of the syntax you'd like to use?

**Comment by Daniel-Fermoselle** [comment]
I would like to be able to highlight specific expressions. For instance, in the image below since I can only access the line number, I can only highlight the entire line. However, I would want to be able to highlight each individual expression separately and I was thinking that it might be possible if I use column ranges. Also, as additional information, I am using the JuliaInterpreter package and accessing the line number through the frame and JuliaInterpreter.whereis(frame).
![1](https://user-images.githubusercontent.com/17110877/58888680-b2f8f580-86df-11e9-852f-1d8f29288056.PNG)

**Comment by JeffBezanson** [comment]
Oh, I see now --- recording column number location information. I thought you might be referring to some kind of new syntax. Try CSTParser.jl, and see #31954 for the work that's been started to use it as the default parser.

**Comment by Keno** [comment]
Closing as dup of those discussions. More precise location information is desirable, but those issues are more concretely actionable.
