### ISSUE TITLE
eps(::Missing)

### ISSUE THREAD

**Issue by francescoalemanno** [JuliaLang/julia#32234]
many times in generic code i use stuff like: x > eps(x), if for some reason x happens to be a missing value, then i get a nasty error unless i define:

```
Base.eps(::Missing) = missing
```

is this a good idea? if so it could be default behavior in Base.

## edit:
Pull Request: [https://github.com/JuliaLang/julia/pull/32235](https://github.com/JuliaLang/julia/pull/32235)

**Comment by Moelf** [comment]
so `x>Missing` is always `true`?

**Comment by JeffBezanson** [comment]
`x > missing` is `missing`. So if that's used in a boolean context, it doesn't help.

**Comment by Moelf** [comment]
I just think it makes sense to throw an error here, maybe just clean the data or check `x===Missing`

**Comment by francescoalemanno** [comment]
I think it still makes sense, 
since ```missing``` already propagates through many unary/binary functions of floats.

**Comment by KristofferC** [comment]
> data cannot always be simply cleaned, for example in a dataframe where a row has only partially missing information, to clean the data i should discard the whole row or coerce the missing to something else.

You just apply the function to the non missing elements.

**Comment by JeffBezanson** [comment]
Also don't forget
```
lift(f) = x -> ismissing(x) ? missing : f(x)
```

**Comment by KristofferC** [comment]
Closing based on discussion in https://github.com/JuliaLang/julia/pull/32235.
