### ISSUE TITLE
vector type inconsistency?!

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#32242]
```
julia> Int64 <: Integer
true

julia> typeof([1,2,3]) <: Vector{Int64}
true
```

however,

```
julia> typeof([1,2,3]) <: Vector{Integer}
false

julia> typeof([1,2,3]) <: Vector{Number}
false
```

is this intended?!

**Comment by ericphanson** [comment]
It is intended; you can read about here in the manual: https://docs.julialang.org/en/v1/manual/types/index.html#Parametric-Composite-Types-1 (the warning block in that section is exactly about this).
