### ISSUE TITLE
1.0 range compile error on arm: `libm.so: cannot open shared object file`

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#32257]
I'm [testing ImageMagick on arm](https://github.com/JuliaIO/ImageMagick.jl/pull/157) and getting the following on arm in julia v1.0 (The error doesn't occur on aarch64 v1.0/1.1, and haven't been able to test v1.1 on arm due to #32256)
```
Got exception outside of a @test
error compiling #range: error compiling _range: error compiling _linspace: error compiling nbitslen: could not load library "libm"
libm.so: cannot open shared object file: No such file or directory
Stacktrace:
[1] macro expansion at /drone/src/test/constructed_images.jl:101 [inlined]
```
The line that triggers it is:
```
reshape(range(0.5, stop=1.5, length=6), 2, 3)
```

**Comment by ianshmean** [comment]
I'm still getting this on the v1.2 ARMv7 image: https://cloud.drone.io/ianshmean/YOLO.jl/3/1/2

**Comment by staticfloat** [comment]
Shoot; looks like https://github.com/JuliaLang/julia/pull/32803 didn't make it into `v1.2`.  Can you try `v1.3` and see if it still has this problem?

Here's [1.3-rc2 for armv7l](https://julialangnightlies.s3.amazonaws.com/pretesting/linux/armv7l/1.3/julia-a04936e3e0-linuxarmv7l.tar.gz).

**Comment by giordano** [comment]
I just tried with Cuba.jl, always failed for the same reason on armv7l, it seems to work: https://cloud.drone.io/giordano/Cuba.jl/31/1/2 :tada:

**Comment by maleadt** [comment]
I guess we can close this? https://github.com/JuliaLang/julia/pull/32803 has a backport label, in case we want to fix it for previous releases.
