### ISSUE TITLE
arm docker images missing C compiler

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#32259]
As experienced in https://github.com/JuliaPackaging/CMake.jl/issues/17 it seems like the arm & aarch64 images don't have a valid C compiler installed.

Might it be worth adding an appropriate C compiler to the docker images?

**Comment by fredrikekre** [comment]
Which docker images are you talking about? These https://hub.docker.com/_/julia ? They are not maintained by people here, maybe better to open the issue here: https://github.com/docker-library/julia

**Comment by ianshmean** [comment]
Thanks for the pointer. I hadn't realized they weren't centrally managed, and it looks like the point is already being discussed over there
