### ISSUE TITLE
Type checking does not work as expected

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaLang/julia#32261]
Why is
` typeof(1) <: Real`
> true

` typeof([1,1]) <: Vector`
> true

but
` typeof([1, 1]) <: Vector{Real}`
> false

Shouldn't it be a valid subtype since `Int64 <: Real`?

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by JeffBezanson** [comment]
See https://docs.julialang.org/en/v1/manual/types/#Parametric-Composite-Types-1
