### ISSUE TITLE
Comparison of LU and Cholesky (type of output matrices and time) 

### ISSUE THREAD

**Issue by hochB** [JuliaLang/julia#32269]
I created a simple SPD matrix.
```
julia> A
3×3 Array{Int64,2}:
 2  1  1
 1  2  1
 1  1  2
```

I tried 2 factorization methods, LU and Cholesky.
The first thing I noticed is that Cholesky returns 2 matrices that are *explicitly* upper and lower.
```
julia> cholesky(A).U
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.41421  0.707107  0.707107
  ⋅       1.22474   0.408248
  ⋅        ⋅        1.1547

julia> cholesky(A).L
3×3 LowerTriangular{Float64,Array{Float64,2}}:
 1.41421    ⋅         ⋅
 0.707107  1.22474    ⋅
 0.707107  0.408248  1.1547
```
OTOH the LU factorization returns 2 matrices that are also triangular but not *explicitly*.
```
julia> lu(A).U
3×3 Array{Float64,2}:
 2.0  1.0  1.0
 0.0  1.5  0.5
 0.0  0.0  1.33333

julia> lu(A).L
3×3 Array{Float64,2}:
 1.0  0.0       0.0
 0.5  1.0       0.0
 0.5  0.333333  1.0
```

Next I wondered about how faster Cholesky was.
Because I learned long ago that Cholesky was faster than LU.
To my surprise LU was faster.

```
julia> @time lu(A)
  0.000008 seconds (7 allocations: 464 bytes)
LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0  0.0       0.0
 0.5  1.0       0.0
 0.5  0.333333  1.0
U factor:
3×3 Array{Float64,2}:
 2.0  1.0  1.0
 0.0  1.5  0.5
 0.0  0.0  1.33333

julia> @time cholesky(A)
  0.000022 seconds (9 allocations: 432 bytes)
Cholesky{Float64,Array{Float64,2}}
U factor:
3×3 UpperTriangular{Float64,Array{Float64,2}}:
 1.41421  0.707107  0.707107
  ⋅       1.22474   0.408248
  ⋅        ⋅        1.1547
```

**Comment by dkarrasch** [comment]
Could be an artifact of the very small matrix:
```julia
julia> using LinearAlgebra

julia> A = rand(100,100);

julia> B = A'A;

julia> using BenchmarkTools

julia> @btime lu($B);
  66.204 μs (4 allocations: 79.11 KiB)

julia> @btime cholesky($B);
  43.771 μs (6 allocations: 78.31 KiB)
```

**Comment by stevengj** [comment]
For such a small matrix you are mostly measuring overhead, not the arithmetic.   You might consider using StaticArrays.jl for 3x3 matrices.

**Comment by hochB** [comment]
You are all correct. With bigger matrices the behavior is just as expected.
No issue here.

Any reasons for the LU returning lower and upper matrices that are of type `Array` while Cholesky returns matrices that are of type `UpperTriangular` and `LowerTriangular`?

**Comment by stevengj** [comment]
> Any reasons for the LU returning lower and upper matrices that are of type Array while Cholesky returns matrices that are of type UpperTriangular and LowerTriangular?

Not sure; maybe file a separate issue to discuss this?
