### ISSUE TITLE
RFC: let `Transpose` & `Adjoint` work on arbitrary dimension

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#32272]
I found this problem while working on a new version of `Batched.jl` (aka `BatchedArrays`), I need to define a custom `Transpose` for `AbstractArray{T, 3}`s instead of using the one in the `LinearAlgebra` because currently the `Transpose` is defined as a Matrix.

However, in general, I believe we can just define `Transpose` as the swap of first 2 dims for arbitrary dimension, and the `Adjoint` to be the swap of first 2 dims and `conj` for arbitrary dimension, then a lot things will just work instead of re-implement a lot same things.

Moreover, I think we should have a `Permutation` that lazy evaluates the permutation so it is consistent with `Transpose` and `Adjoint`, like `Transpose` and `Adjoint`, `Permutation` can be canceled when there are several permutation of the dimensions happens.

And the only thing need to change is to introduce another type parameter `N`, e.g

```julia
struct Adjoint{T, N, S} <: AbstractArray{T, N}
    parent::S
end
```

And let `N` be `2` by default.

**Comment by stevengj** [comment]
> However, in general, I believe we can just define `Transpose` as the swap of first 2 dims for arbitrary dimension, and the `Adjoint` to be the swap of first 2 dims and conj for arbitrary dimension, then a lot things will just work instead of re-implement a lot same things.

This seems somewhat arbitrary to me.  Why the first two dimensions?

If you just want an arbitrary lazy permutation then we already have `PermutedDimsArray`.

**Comment by Roger-luo** [comment]
> Why the first two dimensions?

I think `Transpose` and `Adjoint` can be the special case for `Permutation`, which is the permutation of first 2 dims.

The use case I met here, in in the context of batched arrays, the `Adjoint/Transpose` should make sense on it, e.g a batch of matrices stored as `Array{T, 3}` or `Array{T, 4}`.

Currently, I have to re-define the `tranpose` and `adjoint` with new type named `BatchedTranspose`, `BatchedAdjoint`, if the problem is only rewrite this, then it is fine. Since it is not a lot code anyway. But since this is a new type, the adjoint definition in AD packages won't work without re-defining the adjoint for those new types.

Regarding to the implementation, there're basically two ways:

a) make a wrapper type that looks like a list of arrays, e.g

```julia
struct BatchedArray{T, E, B, N, S <: AbstractArray{T, N}} <: AbstractArray{S, B}
    storage::S
end
```

b) make a wrapper around the array directly

```julia
struct BatchedArray{T, E, B, N, S <: AbstractArray{T, N}} <: AbstractArray{T, N}
    storage::S
end
```

the first solution after I tried it for a few weeks, it seems to make things more complicated, the later is more straight forward, but neither of them can directly use the buildin `Adjoint`. Then I have to then re-define all the method related to `Transpose` and `Adjoint` with new types `BatchedTranspose` and `BatchedAdjoint` in not only the stdlib functions, but also in other related external packages, and the only thing changed here is just an extra type parameter...

**Comment by stevengj** [comment]
> I think Transpose and Adjoint can be the special case for Permutation, which is the permutation of first 2 dims.

They also have an algebraic meaning that is more subtle than just permuting dimensions, especially for the adjoint of an `AbstractVector` producing a dual vector.

**Comment by Roger-luo** [comment]
> They also have an algebraic meaning that is more subtle than just permuting dimensions, especially for the adjoint of an AbstractVector producing a dual vector.

I kinda agree... But it seems I have to implement this `BatchedAdjoint` now. I'll try if I could find other solution for now.
