### ISSUE TITLE
will julia become self-hosted?

### ISSUE THREAD

**Issue by catastrop** [JuliaLang/julia#32282]

**Comment by mbauman** [comment]
Welcome. This question is better asked over at the [discourse mailing list](https://discourse.julialang.org) than here.  As a quick answer: Julia is already largely written in itself.  The vast majority of the standard library and even some of the compiler is indeed written in Julia.  The biggest parts that aren't are the parser (#31449), the interface to LLVM (C++), and a very minimal set of types needed to start the bootstrapping.  [This comment from 2013](https://groups.google.com/d/msg/julia-dev/dOAwcwm5iEA/dJFqob5HfNYJ) is as relevant today as it was six years ago:

> I agree this would be cool, but it can't be the only measure of language maturity --- not every language is designed for writing compilers. 
>
> The main problem is that this involves lots of tedious work, after which you end up with the same thing you started with, just implemented differently. I'm not even sure I want to use LLVM in any language but C++, since that's the language it's documented in and C++ APIs tend to be highly coupled to the language.

**Comment by JeffBezanson** [comment]
I recommend Laurence Tratt's great blog post on this topic: https://tratt.net/laurie/blog/entries/the_bootstrapped_compiler_and_the_damage_done.html
