### ISSUE TITLE
realpath error: The operation completed successfully

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#32298]
```julia
julia> realpath("\\\\.\\C:")
ERROR: SystemError: realpath: The operation completed successfully.
Stacktrace:
 [1] #windowserror#45(::Nothing, ::typeof(Base.windowserror), ::Symbol, ::Bool) at .\error.jl:148
 [2] windowserror at .\error.jl:148 [inlined]
 [3] realpath(::String) at .\path.jl:351
 [4] top-level scope at REPL[39]:1
```

sure it did...

Julia Version 1.3.0-DEV.390
Commit c630477c4e6 (2019-06-11 10:36 UTC)
OS: Windows (i686-w64-mingw32)

**Comment by GregPlowman** [comment]
> sure it did...


Ha Ha. Similar to `mmap` error on Windows:
`ERROR: could not create file mapping: The operation completed successfully.`

**Comment by musm** [comment]
Should we just use uv_fs_realpath ?

**Comment by vtjnash** [comment]
yep, even if it doesn't fix the issue, it may make sense to switch (and/or contribute our implementation to libuv, if ours is better)

**Comment by vtjnash** [comment]
Looks like `uv_fs_realpath` is already very similar to ours, and could readily be enhanced to match ours

**Comment by vtjnash** [comment]
Looks like `uv_fs_realpath` is already very similar to ours, and could readily be enhanced to match ours
