### ISSUE TITLE
Array allocation with negative size should throw a `ArgumentError` not a `ErrorException`

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#32307]
```
julia> try 
       fill('a', -10)
       catch err
       @show typeof(err)
       end

typeof(err) = ErrorException
```

**Comment by Naba7** [comment]
Can I be assigned this?

**Comment by StefanKarpinski** [comment]
There's no way to assign issues to people outside of the org. Just go ahead and make a PR to fix it 👍

**Comment by Naba7** [comment]
I can't find where to change. I checked julia/base/array.jl . Isn't ``fill`` a numpy method?  I don't understand where to make changes,Please help.

**Comment by oxinabox** [comment]
Do `@which fill(-1, -1)` from the REPL.
Which will tell you where it is defined.

**Comment by StefanKarpinski** [comment]
> Isn't fill a numpy method?

There aren’t any NumPy methods in Julia. Unless you’re using PyCall to call NumPy.

**Comment by fredrikekre** [comment]
I don't think this should be fixed in `fill`:
```
julia> Array{Int,2}(undef, -1, -4)
ERROR: invalid Array dimensions
Stacktrace:
 [1] Array{Int64,2}(::UndefInitializer, ::Int64, ::Int64) at ./boot.jl:404
 [2] top-level scope at none:0
```
Fixing it in fill would only fix one of all the functions that use array allocations.
