### ISSUE TITLE
type of LOAD_PATH

### ISSUE THREAD

**Issue by RossBoylan** [JuliaLang/julia#32311]
The discussion of code loading says

> The Julia LOAD_PATH global defines an environment stack

This is with the 1.1.1 documentation, and yet running 1.1.1 I see
```jl
julia> typeof(LOAD_PATH)
Array{String,1}
julia> LOAD_PATH
3-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
```

I was expecting from the docs that the type would be some kind of environment for `LOAD_PATH` and for its elements.

**Comment by StefanKarpinski** [comment]
Not sure I see the contradiction. The strings specify a stack of environments. There are no "environment" objects. They're strings that tell you what's in the environment.

**Comment by RossBoylan** [comment]
Well, that may explain why I'm having trouble getting info about my live environment.  For example, I wanted to see the roots, graph, and paths map and was trying to navigate to them, as well as find the interface for working with environments.

Referring to either a string array or a string as an environment seems misleading. An environment is, among other things, a namespace.  A string might name a namespace, but it's not the namespace itself.

**Comment by StefanKarpinski** [comment]
I would like to expose those things in a more first-class way, but they're currently only latently computed as needed by code loading.

**Comment by RossBoylan** [comment]
Wandering a bit from the initial point about the documentation, the package manager also manipulates environments (and project and packages).  Is all that being done without first-class, explicit, in memory representations of those things?

**Comment by JeffBezanson** [comment]
The doc string for `LOAD_PATH` is pretty clear:
```
An array of paths for using and import statements to consider as project environments or package
  directories when loading code.
...
```
The manual text could be changed to be more similar to that.

Of course the package manager has data structures for these things but exposing them is not the purpose of `LOAD_PATH`. And the particular structures used (as well as *when* they are computed and available) are an implementation detail. It would help to expand on what you'd like to do, and propose an API for it.

**Comment by StefanKarpinski** [comment]
> the package manager also manipulates environments (and project and packages). Is all that being done without first-class, explicit, in memory representations of those things?

The package manager manipulates project files and manifest files, which are a way to define environments, but it does not have a really first class notion of an environment either. An environment is an abstraction with a few different implementations (as described in the Pkg docs). I would like to refactor the code so that the abstraction is made explicit, but I have not done so yet.

**Comment by vtjnash** [comment]
You might be interested in https://github.com/JuliaLang/julia/compare/jn/loading-plus which provides first-class representations of environments (but doesn't really have a way to manipulate them right now). It got hung up for a long time on wanting the refactoring in #29807 and related doc fixes. But someday I assume I'll get back to working on it (to make precompiled and distributed code loading to work more reliably and correctly), but for now it's just a skeleton for reifying the current environment and querying that.

**Comment by StefanKarpinski** [comment]
Doing it for project and manifest file is pretty straightforward, it's doing the same thing for package directories and the load path that's hard. Especially if you want an implementation that's efficient even in the presence of potentially large package directories. Without multiple implementations, it's not much of an abstraction.

**Comment by vtjnash** [comment]
Yeah, `implicit_project_deps_get` was a bit harder to write, since some of the queries seem to be essentially inverted from the normal question (since it needs to map in the other direction: eg from path to name instead of name to path)

**Comment by KristofferC** [comment]
Doesn't seem like anything actionable here.
