### ISSUE TITLE
eigvals() set a limit for zero truncation

### ISSUE THREAD

**Issue by hochB** [JuliaLang/julia#32339]
I noticed that the eigvals() function sometimes returns values that theoretically should be zero as *almost zero*.
A possibility would be to add a check at the end of the function to see if one of the values is below a certain limit and if so truncate to zero.

```
julia> A = [21 25 43; 54 91 98]
2×3 Array{Int64,2}:
 21  25  43
 54  91  98

julia> B = A'*A
3×3 Array{Int64,2}:
 3357  5439   6195
 5439  8906   9993
 6195  9993  11453

julia> eigvals(B)
3-element Array{Float64,1}:
    -2.7314914602888018e-14
   106.9414093878335
 23609.058590612167
```

The -2.73e-14 is in reality zero.

**Comment by fredrikekre** [comment]
See e.g. https://stackoverflow.com/questions/588004/is-floating-point-math-broken and https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678 etc.
