### ISSUE TITLE
Consider exporting `StatsBase.sample` from `Statistics` stdlib

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#32343]
This is a feature request to consider exporting basic names such as `sample` defined in StatsBase` from the `Statistics` stdlib.

Right now whenever we need access to the `sample` function, we need this extra import, which seems suboptimal:

```julia
using Statistics # cool, we load anything related  to stats
using StatsBase # urgh, we still need this for sample, and other functions
```

It seems reasonable to reexport StatsBase from Statistics. That would solve a bunch of name-related issues:

- https://github.com/JuliaLang/julia/issues/29974
- https://github.com/JuliaLang/julia/issues/27140

The long-term solution is to move the code as well, but meanwhile, I think we could just reexport the names.

**Comment by KristofferC** [comment]
StatsBase is not a part of Julia so how can it reexport the names?

**Comment by nickrobinson251** [comment]
> > The long-term solution is to move the code as well
>
> would mean to move the code in Statistics to StatsBase.

I'll note that there's still work on moving things in the direction StatsBase -> Statistics 
- https://github.com/JuliaLang/julia/pull/31395
- https://github.com/JuliaStats/StatsBase.jl/issues/493

**Comment by juliohm** [comment]
I am confused about the names. I thought that `Statistics` would be the de-facto name for anything statistics-related, so users of the language wouldn't need to care about this "*Base" business, and would just get the names with a single import.

There are multiple packages doing slightly different things:

- StatsBase.jl
- Statistics
- StatsKit.jl

I understand that `StatsKit.jl` is broader and will reexport models, dataframes, etc. But the existence of `StatsBase.jl` together with `Statistics` is still confusing to me.

**Comment by juliohm** [comment]
Initially I thought that StatsBase.jl contained the foundations for stats-related work. Including all possible names. Then a package like `Statistics` would reexport all packages that implement the concepts.

Now I learned that StatsBase.jl is not even used by Statistics, I am not sure if these directions are clear to everyone.

**Comment by KristofferC** [comment]
Yeah, since StatsBase isn't used by Statistics there is nothing that can be reexported.

**Comment by nalimilan** [comment]
StatsBase is supposed to be removed at some point, after its features have been moved either to Statistics or to more specific packages. Not sure which applies here.

**Comment by juliohm** [comment]
That sounds like a good plan. Moving the functionality to either Statistics or some other specialized packages seems helpful.
