### ISSUE TITLE
Add an `onlydirs` option to readdir.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#32342]
Could arguably be more convenient to do

```jl
for dir in readdir(maindir; onlydirs=true)
    ...
end
```

instead of

```jl
for dir in readdir(maindir)
    isdir(joinpath(maindir, dir)) && continue
   ...
end
```

or

```jl
for dir in filter!(dir -> isdir(joinpath(maindir, dir)), readdir(maindir))
    ...
end

**Comment by StefanKarpinski** [comment]
What if you only want to iterate files? I feel like there could be some kind of generalization here.

**Comment by jakobnissen** [comment]
One solution could be to have an optional `maxdepth` keyword for `walkdir`. In this way, you could do
```
for (rootdir, dirs, files) in walkdir("dir", maxdepth=1)
    ...
end
```
This would probably also be useful for `walkdir` in general.

**Comment by StefanKarpinski** [comment]
But presumably if you want to walk all the directories or files, you want to walk them at any depth.

**Comment by KristofferC** [comment]
`readdir` could take a filter predicate that is called on the full path but at that generality you can probably just use the `filter` version. Not sure this is needed anymore.
