### ISSUE TITLE
Cannot Juxtapose String Literal 

### ISSUE THREAD

**Issue by anthonyagudelox3** [JuliaLang/julia#32353]
When I attempt to set all_semtypes equal to this string I get the following error message. 
I am currently using Windows 10 and Julia v0.7.0, setting all_semtypes equal to the following string worked on Julia v0.6.2. 

`julia>   all_semtypes = ["aapp","acab","acty","aggp","alga","amas","amph","anab","anim","anst","antb","arch","bacs","bact","bdsu","bdsy","bhvr","biof","bird",
           "blor", "bmod","bodm","bpoc","bsoj","carb","celc","celf","cell","cgab","chem","chvf","chvs","clas","clna","clnd","cnce","comd","crbs","diap",
             "dora", "eehu","eico","elii","emod","emst","enty","enzy","evnt","famg","ffas","fish","fndg","fngs","food","ftcn","genf","geoa","gngm","gora",
               "grpa", "hcro","hlca","hops","horm","humn","idcn","imft","inbe","inch","inpo","inpr","invt","irda","lang","lbpr","lbtr","lipd","mamm","mbrt",
                 "mcha", "mnob","mobd","moft","mosq","neop","nnon","npop","nsba","nusq","ocac",
                   "ocdi","opco","orch","orga","orgf","orgm","orgt","ortf","patf","phob",
                     "phsu","plnt","podg","popg","prog","pros","qlco","rcpt","rept","resa","resd","rich","rnlw","sbst","shro","socb","sosy","spco","strd",
                       "dsyn","edac", "grup","hcpp", "medd","menp", "phpr","phsf""tisu","tmco", "topp","virs","vita","vtbt", "qnco"]

ERROR: syntax: cannot juxtapose string literal`

**Comment by StefanKarpinski** [comment]
You're missing a comma between `"phsf"` and `"tisu"`.
