### ISSUE TITLE
add ‖ \Vert as infix operator.  in geometry it's complementary to ⟂

### ISSUE THREAD

**Issue by Orbots** [JuliaLang/julia#32359]
Would be nice to have ‖ as an infix operator.  I'm ok with the precedence.  I don't mind parens when needed.

Then I can write a couple of functions to express some geometric operations.
u = ⟂(u,v) would give you the rejection of the vector u relative to vector v.  i.e. u is now perpendicular to v.

u = ‖(u,v) would give you a projection of the vector u onto v.  i.e. u is now parallel to v

Now we have this nice relation.

u == (u⟂v) + (u‖v)

**Comment by JeffBezanson** [comment]
We parse U+2225 (`∥`, `\parallel`) as an operator with comparison precedence. Unfortunately confusable with U+2016; we could perhaps normalize it.

**Comment by Orbots** [comment]
Perfect.  I'd leave \Vert alone, could be useful for norm later.  Discoverability of single unicode character functions/operators is a bit tricky!
