### ISSUE TITLE
Using CPU cache Memory Directly with Julia 

### ISSUE THREAD

**Issue by ajsagit** [JuliaLang/julia#32365]
There is Memory Cache in CPU, not too large, from 2Mb to 72Mb mostly.
So is it possible to add some supports on using the CPU Memory Cache, e.g.
1. Some programme in CPU Memory Cache and not in the Memory via memory brand on mainboard on PC or servers.
2. Some data / data sream(Real time data) in CPU Memory Cache and not in the Memory via memory brand on mainboard on PC or servers.
Which means we can set a part of the CPU Cache Memory to store some programme or some data No matter they are missing when power off.
TIA

**Comment by yuyichao** [comment]
No this is not something that is accessible from normal software code.

**Comment by ajsagit** [comment]
> No this is not something that is accessible from normal software code.

I noticed that there is a cooporation between Julia and Intel, maybe helpful?Thanks

**Comment by ajsagit** [comment]
Add I find an adaptation on MS. Can it be helpful?
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms904878(v=msdn.10)
`

Value | Description
-- | --
CACHE_SYNC_WRITEBACK | Write back cached data.
CACHE_SYNC_DISCARD | Write back and discard cached data.
CACHE_SYNC_INSTRUCTIONS | Discard all cached instructions.
CACHE_SYNC_FLUSH_I_TLB | Flush the instruction TLB.
CACHE_SYNC_FLUSH_D_TLB | Flush the data TLB.
CACHE_SYNC_FLUSH_TLB | Flush both the instruction and data TLBs.
CACHE_SYNC_L2_WRITEBACK | Write back the L2 cache.
CACHE_SYNC_L2_DISCARD | Write back and discard the L2 cache.
CACHE_SYNC_ALL | Perform all of the above operations.

`

**Comment by ajsagit** [comment]
Add I find an adaptation on MS. 
https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms904878(v=msdn.10)
`

Value | Description
-- | --
CACHE_SYNC_WRITEBACK | Write back cached data.
CACHE_SYNC_DISCARD | Write back and discard cached data.
CACHE_SYNC_INSTRUCTIONS | Discard all cached instructions.
CACHE_SYNC_FLUSH_I_TLB | Flush the instruction TLB.
CACHE_SYNC_FLUSH_D_TLB | Flush the data TLB.
CACHE_SYNC_FLUSH_TLB | Flush both the instruction and data TLBs.
CACHE_SYNC_L2_WRITEBACK | Write back the L2 cache.
CACHE_SYNC_L2_DISCARD | Write back and discard the L2 cache.
CACHE_SYNC_ALL | Perform all of the above operations.

`

**Comment by yuyichao** [comment]
No, none of them is relevant and no collaboration is going to change that.
Again, as a fact, the cache is not something that's ever going to be directly accessable in your code. If it is, it won't be called a cache anymore.

**Comment by ajsagit** [comment]
Thanks
