### ISSUE TITLE
Cannot add Gitlab registry on Windows using SSH

### ISSUE THREAD

**Issue by bomber8013** [JuliaLang/julia#32367]
When doing the command:
```
(v1.1) pkg> registry add git@gitlab.domain.com:Folder1/folder2/registry.git
   Cloning registry from "git@gitlab.domain.com:Folder1/folder2/registry.git"
ERROR: failed to clone from git@gitlab.domain.com:Folder1/folder2/registry.git, error: GitError(Code:ERROR, Class:SSH, failed to start SSH session: Unable to exchange encryption keys)
```
I have redacted path information.

This worked when I did it on CentOS, but is not working on Windows. I have previously been able to use the https link successfully, but would like to switch to using SSH for both Linux and Windows.

Output of ssh-agent:
```
$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-LaRnIPEc66Qc/agent.1143; export SSH_AUTH_SOCK;
SSH_AGENT_PID=1144; export SSH_AGENT_PID;
echo Agent pid 1144;
```

Output of ssh-add -l:
```
$ ssh-add -l
4096 SHA256:Om2r4mhF0Ghm8ntLDWCOiPIJ5f73+SAcZ0aM18vZrq4 z6-958 (RSA)
```

Output of ssh -T:
```
$ ssh -T git@gitlab.domain.com
Welcome to GitLab, @username!
```

**Comment by ViralBShah** [comment]
Is this still an issue?

**Comment by DilumAluthge** [comment]
I would recommend doing:

```bash
export JULIA_PKG_USE_CLI_GIT=true
```

This will use your system's Git, and then you don't have to worry about any LibGit1 issues.

**Comment by ViralBShah** [comment]
Do we document this somewhere in the `Pkg` documentation?
