### ISSUE TITLE
Implement comparison of CompoundPeriod

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#32389]
Hello,

currently it's not possible to compare `CompoundPeriod`
see discussion https://discourse.julialang.org/t/parsing-string-to-dates-compoundperiod/25484/8

Example:

```julia
julia> Dates.Minute(1) + Dates.Second(1) < Dates.Minute(1) + Dates.Second(2)
ERROR: MethodError: no method matching isless(::Dates.CompoundPeriod, ::Dates.CompoundPeriod)
Closest candidates are:
  isless(::Missing, ::Any) at missing.jl:70
  isless(::Any, ::Missing) at missing.jl:71
Stacktrace:
 [1] <(::Dates.CompoundPeriod, ::Dates.CompoundPeriod) at ./operators.jl:260
 [2] top-level scope at none:0
```

it should also be possible to compare

`Dates.CompoundPeriod` with `Dates.Period`

To my understanding, only "fixed" `CompoundPeriod` can be compared ie `CompoundPeriod` without `Year` nor `Month`

Kind regards

**Comment by wookay** [comment]
something like
```julia
julia> using Dates

julia> Dates.value(x::Dates.CompoundPeriod) = sum(Dates.value.(x.periods))

julia> Base.isless(x::Union{Period,Dates.CompoundPeriod}, y::Union{Period,Dates.CompoundPeriod}) = isless(Dates.value(x), Dates.value(y))

julia> Dates.Minute(1) + Dates.Second(1) < Dates.Minute(1) + Dates.Second(2)
true
```

**Comment by wookay** [comment]
oops. above code has wrong value. it should be with `Dates.tons`

```julia
julia> Base.isless(x::Union{Period,Dates.CompoundPeriod}, y::Union{Period,Dates.CompoundPeriod}) = isless(Dates.tons(x), Dates.tons(y))

julia> Week(1) + Day(1) > Day(3)
true

julia> Week(1) + Day(1) < Day(9)
true
```

**Comment by cfitz25** [comment]
Hello, by any chance has this been added into the library?

**Comment by StefanKarpinski** [comment]
@Quinnj, any chance you could look at this or point out someone else who might be good to look at it?

**Comment by quinnj** [comment]
Hmmmm, this makes me a little nervous to implement, and here are a few things that run through my head looking at it a bit (also, sorry for the slow response; I was on extended vacation when pinged, and am slowing catching back up on emails):
* Using `Dates.tons` might lead to overflow? But I think only for durations > ~300K years, so probably not a problem in practice, but still, do we check for that anyway?
* If you're comparing a CompoundPeriod with month/quarter/year periods, should we throw an error? Technically we define a `Dates.tons` method, but it's more to get an _average_ # of nanoseconds per month; same with `Dates.Quarter` and `Dates.Year`, which don't have exact, precise conversions to nanoseconds. That said, if you were comparing `(Dates.Year(1) + Dates.Day(1)) < (Dates.Year(1) + Dates.Day(2))`, it should obviously be true, even though neither side of the comparison has an _exact_ nanosecond representation. So maybe only throw an error when an imprecise period is used to break a tie?

So overall, I'd say I'm in favor, but I think we should try to be conservative and throw errors when exact comparisons wouldn't be possible. This would be a decent 1st issue, if someone wants to take a stab at it, steps being:
* Implementation of `Base.isless` on `CompoundPeriods` in the `Dates` stdlib `periods.jl` file; either using `Dates.tons` solely, or by "walking" each CompoundPeriods periods and comparing similar periods; the former might run into imprecise issues I mentioned above, the latter might be trickier to implement
* Add some tests for a wide variety of CompoundPeriod configurations in the `Dates` stdlib `test/periods.jl` file; probably in a new `@testset` just for this functionality

**Comment by cfitz25** [comment]
would using the upper and lower limit of those inexact periods be a good way at specifying the grey area of an equality? 
like for you example of Year(1)+Day(1) < Year(1) + Day(2) would return successfully but a Year(1) < Year(1) + Day(1) could be equal assuming a leap year which would be within the grey area.
You could, for addition of compounds types, store the sum of all the grey areas (a year may have one of 1 day) and the exact time types must add to be larger than that sum.
sorry if ive explained this poorly

**Comment by quinnj** [comment]
Yeah, that kind of approach seems like it could work; I assume you know, but `Base.isless` does need to return a `Bool`, `true` or `false`, and then we need to figure out what to do in the "gray area" case. Throw an error?

**Comment by cfitz25** [comment]
yeah i do know that it needs to be bool, was just using ints so i could signify true, false and "other". Id say throwing an error makes sense as no accurate answer could be given

**Comment by cfitz25** [comment]
I was thinking, based off the logic that we put together Year(1) == Year(1) or other OtherPeriods doing similar comparisions should also return an error as it cant be known they are the same.

The rest of the Dates library also uses the average value for days in a year and days in a month.

Would it be a good idea to continue with that same trend of using average values considering it would follow the same pattern in the library?

**Comment by quinnj** [comment]
Yeah, I'm thinking we should just go the `Dates.tons` route and add some docs to the CompoundPeriod about that strategy; the advantage there is it handles the grey areas pretty well.

**Comment by cfitz25** [comment]
Just did it on my branch, should i make a pull request?

**Comment by laborg** [comment]
This has been fixed in https://github.com/JuliaLang/julia/pull/37392
```julia
julia> VERSION
v"1.7.2"

julia> using Dates

julia> Dates.Minute(1) + Dates.Second(1) < Dates.Minute(1) + Dates.Second(2)
true
```
(See PR for more tests)
