### ISSUE TITLE
merging Dicts with boolean values

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#32391]
Boolean's sometimes get converted to Ints.  is this the desired behavior?

```
julia> merge(Dict(:x=>true), Dict(:a=>1))
Dict{Symbol,Int64} with 2 entries:
  :a => 1
  :x => 1

julia> merge(Dict(:x=>true), Dict(:a=>'1'))
Dict{Symbol,Any} with 2 entries:
  :a => '1'
  :x => true
```

**Comment by nalimilan** [comment]
That's promotion, just like `vcat` does.

**Comment by StefanKarpinski** [comment]
It is admittedly weirder in the Boolean case. I don’t think there’s much we can do about this in the 1.x timeframe.

**Comment by KristofferC** [comment]
As said, `Bool` is just another integer type.
