### ISSUE TITLE
request: remove LLVM, become fully self-hosted

### ISSUE THREAD

**Issue by catastrop** [JuliaLang/julia#32399]

**Comment by catastrop** [comment]
This will take time, but once done we all will love it

**Comment by Roger-luo** [comment]
what's the advantage of doing this? if there's no obvious advantage then it is not worth the effort. I don't see how this would benefit practical applications.

**Comment by yuyichao** [comment]
For one, I will not like it at all unless you donate a equivalent or better compiler framework. Even porting to libgccjit or rpython whatever jit backend you can come up with would be a better one.

Also, what you are describing is not self-hosting. Self-hosting is about compiling itself i.e. having the whole language implemented in the language itself. In this case, it means removing the C and flisp part of the code. That is a goal that's more reasonable but is also not all good either.

What you are describing is purely removing external dependencies. Being able to run with minimum dependency for certain application could be useful, and there are open PR on exactly this right now. Removing the dependency completely is very different and the benefit of it (if it exists at all) is not at all self-explanatory.

**Comment by yuyichao** [comment]
Judging from your other issues, you appear to just hate llvm or c++, not sure which one and want people to not use it anymore. There's nothing actionable here and should just be closed.

Also, ref https://github.com/JuliaLang/julia/issues/32282. Please don't open an issue 2 weeks after being told to move the discussion somewhere else.

**Comment by catastrop** [comment]
so C++ also for next few decades. 

I don't understand why Rust and Julia people don't want to leave LLVM and make everything their own. 

Look at Golang.

**Comment by catastrop** [comment]
@Roger-luo, if this is done, no one will blame us for using Julia. ( c++ people )

**Comment by catastrop** [comment]
>Also, what you are describing is not self-hosting. Self-hosting is about compiling itself i.e. having the whole language implemented in the language itself.

@yuyichao , yes like Golang.

**Comment by yuyichao** [comment]
Third time, please stop commenting here.

**Comment by vtjnash** [comment]
> Look at Golang.

We do. LLVM is a better optimizer. Perhaps someday Golang will shed their extra code burden, but that seems unlikely to align with their present goals. For now, LLVM is the best option for our goals.
