### ISSUE TITLE
Poor performance of OpenBLAS matrix-vector multiplication on small sizes

### ISSUE THREAD

**Issue by VHaravy** [JuliaLang/julia#3239]
Consider the two following tests. The first one uses Julia's `A_mul_B` (OpenBLAS's `dgemv`):

``` julia
function test1(n::Int, count::Int)
    A = rand(n, n)
    x = rand(n)
    y = zeros(n)
    tic()
    for i = 1 : count
        A_mul_B(y, A, x)
    end
    toq()
end
```

The second one implements matrix-vector multiplications itself:

``` julia
function naive_A_mul_B(y::Vector{Float64}, A::Matrix{Float64}, x::Vector{Float64})
    m, n = size(A)
    for i = 1 : m
        y[i] = 0.0
        for j = 1 : n
            y[i] += A[i, j] * x[j]
        end
    end
end

function test2(n::Int, count::Int)
    A = rand(n, n)
    x = rand(n)
    y = zeros(n)
    tic()
    for i = 1 : count
        naive_A_mul_B(y, A, x)
    end
    toq()
end
```

The results are (`count = 100 000`)

```
N          OpenBLAS    Naive
4          0.035218    0.005754
5          0.641212    0.008684
8          0.650700    0.019424
9          0.871438    0.024323
16         1.079199    0.077812
17         1.249294    0.085496
32         2.009289    0.322948
33         2.051556    0.339220
64         2.051730    1.342379
65         2.078451    1.416710
```

This is really sad.

P.S. I ran the same test using `dgemv` that comes with MKL and results are even sadder:

```
N          OpenBLAS    Naive       MKL
4          0.026248    0.005759    0.011873
5          0.682821    0.008710    0.012759
8          0.703205    0.022573    0.013530
9          0.918482    0.024350    0.015054
16         1.148282    0.075867    0.020143
17         1.307566    0.085483    0.023182
32         2.035381    0.318547    0.040268
33         2.050683    0.340855    0.047492
64         2.114853    1.342950    0.142106
65         2.101495    1.418431    0.160844
```

**Comment by andyferris** [comment]
This issue is something I noticed while developing *StaticArrays*. For *very* small sizes, there is a lot of overhead coming from Julia, let alone BLAS. For instance, there are specialized 2x2 and 3x3 matrix multiplication code after a *very* quick look through the code it passes through several functions repeatedly checking size matching, checking the character (!!) that describes if its transposed or not, etc before it gets to evaluation.

A lot of this run-time overhead could be eliminated with e.g. `Val{'N'}` instead of `'N'` for the (lack of) transposition, and taking care to only check the dimensions once (and possibly even elided where possible by `@inbounds`, or something). Out of curiosity, is some of this on the roadmap? (e.g. lazy transposition, taking vector transposes ~~slowly~~ seriously, or whatever might force us to re-write the `A_mul_Bc` interface?)

@StefanKarpinski  wrote:

> 2.. Automatic free insertion in loops: if we can know when a temporary created in a loop can be immediately freed at the end of the loop body, then the next iteration can reuse that memory.

That sounds pretty cool, too!

**Comment by GravityAssisted** [comment]
Sorry to resurrect an old thread, but I am also seeing performance issues for small Mat*Vec operations. Is there a fix on the horizon for this  ? Just want to know whats the best way to solve the problem. I am happy with writing my own optimized ```matvec``` function but then I wonder what all other native functions should I re-write. Opens up a can of worms in my head :-) 
Btw: We are taking 3x3 matrices and 3x1 vector operations, common when working with points in cartesian space. 

I am on Julia 0.6 release using openblas.

```
julia> versioninfo()
Julia Version 0.6.1-pre.0
Commit dcf39a1 (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by andreasnoack** [comment]
Please ask questions at discourse.julialang.org.

**Comment by GravityAssisted** [comment]
@andreasnoack Understood. Generally I would, but it was related to this thread so I asked it here.

**Comment by KristofferC** [comment]
Use StaticArrays (they also have mutable versions).

**Comment by ViralBShah** [comment]
StaticArrays.jl is the only real solution for small matvecs above as @KristofferC points out. I am closing this one.

**Comment by andyferris** [comment]
I will note that I don't *quite* agree with that, Viral - there are problems here we can feasibly fix in `LinearAlgebra` even if the result will be slightly slower than with `StaticArrays`. E.g. last time I looked the dispatch pattern for matrix multiplication is quite deep and results in multiple re-checking of sizes and so-on. This would have been written differently if we thought of a native multiplication algorithm for small matrices with an override to call BLAS only for large cases (the code appeared to me to have the opposite philosophy and/or history - we aim to dispatch to BLAS and have a native/generic algorithm implemented later on as an afterthought).

**Comment by ViralBShah** [comment]
My main reason to close this issue was that things won't change in OpenBLAS. Perhaps we should rename this issue for the `LinearAlgebra` fix and not necessarily be about the upstream issue then. I agree that it can at least be made better.

**Comment by ViralBShah** [comment]
BTW, while matrix-matrix multiply has a deep dispatch pattern, I believe matrix-vector is not so deep.
