### ISSUE TITLE
RFC: allow inline export?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#32398]
I find it is pretty comfortable to use [InlineExport.jl](https://github.com/dalum/InlineExports.jl), since this is a very simple change (the package itself is pretty small) and a bit duplicated with the builtin export syntax, I'm wondering if this can be implemented directly in the compiler.

I don't have to write things twice especially for a large file with it, sometimes it is pretty annoying to go back look up what do I want to export in a long file, and it is also annoying to write in the following syntax:

```julia
export foo
function foo(...)
end
```

It feels much drier to have export inline

```julia
export function foo(...)
end

export const x = 1
```

I guess this won't break current syntax anyway, and old things are still compatible.

**Comment by fredrikekre** [comment]
#8005
