### ISSUE TITLE
`intersect` is type-unstable for some types of ranges

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#32410]
In the following examples, `intersect` is not type-stable:
```julia
julia> @code_warntype intersect(1:2:5, 1:5)
Body::Union{StepRange{Int64,Int64}, UnitRange{Int64}}
[...]

julia> @code_warntype intersect(1:2:5, 1//1:1:5//1)
Body::Union{StepRange{Rational{Int64},Int64}, StepRange{Int64,Int64}}
[...]

julia> @code_warntype intersect(1, big(2):big(5))
Body::Union{UnitRange{Int64}, UnitRange{BigInt}}
[...]
```
The type-instabilities also occur if the positions of the arguments are switched.

Edit: added another example

**Comment by c42f** [comment]
The problem is in `intersect(r::AbstractUnitRange{<:Integer}, s::StepRange{<:Integer})` which has some branches which return unit ranges and some which return step ranges. For similar reasons the eltype appears to be uninferrable when ranges based on different integer types are mixed.

**Comment by sostock** [comment]
While preparing a fix for this, I came across a problem with `StepRange{<:Integer}`s with non-integer step (#32419), in which case `intersect(r::AbstractUnitRange{<:Integer}, s::StepRange{<:Integer})` returns a wrong result (it expects the step of `s` to be integer). IMO, the assumption that a `StepRange{<:Integer}` has an integer step is reasonable, so I don’t think this needs to be fixed in `intersect`. I will nevertheless wait for a decision on #32419 before making a PR for this issue.
