### ISSUE TITLE
piping to stdin fails on windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#32416]
On Linux things work fine
```julia
$ echo test | julia -E "readline(stdin)"
"test"
```
The same line on  Windows  never actually reads in the pipe. Pressing enter it then outputs `""`
 
![t2](https://user-images.githubusercontent.com/4319522/60147944-2cdf4480-979d-11e9-9159-32af3e7b0584.gif)

Note  reading from stdin with python works fine on Windows

```
import sys

for line in sys.stdin:
    print(line, end="")
```

**Comment by mbaz** [comment]
Works for me in Windows 10 and Julia 1.1.0. However, the result is `"test "` with one extra space:

```
C:\Users\mbaz>echo test | julia -E "readline(stdin)"
"test "

C:\Users\mxbiee>echo test| julia -E "readline(stdin)"
"test"
```

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

```

**Comment by musm** [comment]
Yes I also see that

-  `cmd.exe`  -- > extra space
 - `powershell.exe` --> works
 - `pwsh.exe` --> doesn't work   (i.e. the latest powershell)

**Comment by mbaz** [comment]
Oh, I didn't know `pwsh.exe` is the latest powershell. I used `cmd.exe`.

**Comment by vtjnash** [comment]
Works for me in {cmd|powershell|pwsh} in {v1.0.1|v1.3.0-DEV.442} on Windows Server 2016 Datacenter v1607 14393.3025 and pwsh v6.2.1

**Comment by musm** [comment]
So it seems like the only bug is the extra space at the in when in  `cmd.exe`. 

But doh, the problem of the original issue  was I had a custom function in my powershell profile to call julia, which was set incorrectly.

**Comment by musm** [comment]
Ah ok on CMD it parses the space before the pipe. E.g. compare: 
```
echo teasdfst | julia.exe -E "readline(stdin)"
echo teasdfst| julia.exe -E "readline(stdin)"
```
I guess powershell fixes this strange behavior

Closing because this issue was just my  fault 😄
