### ISSUE TITLE
Unreachable reached when trying to add method to Base.convert

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#32411]
When executing the following code:
```
module test
for T in (UInt8,)
    Base.convert(Test, x::T) = 1
end
end
```
My Julia session terminates after reaching an unreachable.
This still happens even if the `Test` type is defined, but does not happen if the function I add methods to is any other than `Base.convert`.

Stacktrace:
```
Unreachable reached at 0x121cf34ac

signal (4): Illegal instruction: 4
in expression starting at none:0
fill! at ./array.jl:366
#IOBuffer#318 at ./iobuffer.jl:121
Type at ./none:0
print_to_string at ./strings/io.jl:127
string at ./strings/io.jl:168
stacktrace at ./stacktraces.jl:212
stacktrace at ./stacktraces.jl:198 [inlined]
macro expansion at /Users/jakni/.julia/packages/Atom/cR6bU/src/comm.jl:65 [inlined]
#19 at ./task.jl:268
unknown function (ip: 0x121cf2914)
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1606 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:596
Allocations: 34356636 (Pool: 34351033; Big: 5603); GC: 78
```

Versioninfo:
```
julia> versioninfo()
Julia Version 1.2.0-rc1.0
Commit 7097799 (2019-05-30 02:22 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by KristofferC** [comment]
> This still happens even if the Test type is defined, but does not happen if the function I add methods to is any other than Base.convert.

Did you mean to write

```
    Base.convert(Type{Test}, x::T) = 1
```

?

**Comment by c42f** [comment]
You can get the same effect with the following equivalent definition

```julia
Base.convert(::Any, ::UInt8) = 1
```

which means Julia will consider a `UInt8` convertible to anything. This plays all sorts of havoc with the system and I'm not sure what we can reasonably do about it. Perhaps we could avoid the hard crash though?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/24078#issuecomment-335433642 etc.
