### ISSUE TITLE
REPL tab-completion for \leq

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/julia#32430]
Julia (v1.1.1 anyway) allows use of `\leq`, but the REPL won't tab-complete it:

```julia
julia> 3 ≤ 4
true

julia> \leq
\leqq      \leqqslant  \leqslant
```

It would be great to see this tab-completion added :)

**Comment by JeffBezanson** [comment]
We use `\le`. Are both used in LaTeX?

**Comment by cscherrer** [comment]
> We use \le

Oops, I had missed that. 

> Are both used in LaTeX?

Yes: https://tex.stackexchange.com/questions/182620/why-does-leq-show-up-as-le

**Comment by JeffBezanson** [comment]
Ok, we should add those synonyms.
