### ISSUE TITLE
vfxplatform build

### ISSUE THREAD

**Issue by Orbots** [JuliaLang/julia#32440]
Julia seems to be a very good fit for the Visual FX industry where the two language problem is very apparent.  Maya and Houdini plugin developers often prototype numerically heavy algorithms in python and then rewrite in C++.  

Having a binary build of Julia available that conforms to the vfx reference platform standard would remove a barrier to adoption.  The biggest hassle is the ABI version as one cannot simply link to julia's .so without jumping through a dlopen hoop.
https://vfxplatform.com

**Comment by ViralBShah** [comment]
This is best discussed at discourse.julialang.org.

**Comment by Orbots** [comment]
I incorrectly said that dlopen was related to ABI version.  Although ABI backward compatibility is an issue trying to get stuff built with julia into maya/houdini. 
The dlopen issue is one of namespacing.   Julia dlopens something or other ( sys.so? ) using default namespacing for dlopen.  This is a problem is that you need to create a shim .so ( load an plugin that then dlopen your "real" plugin ).   Already been discussed at discourse.
https://discourse.julialang.org/t/different-behaviours-in-linux-and-macos-with-julia-embedded-in-c/18101/2

If we had the option to build julia so it uses different dlopen flags that could solve this problem.

**Comment by StefanKarpinski** [comment]
> If we had the option to build julia so it uses different dlopen flags that could solve this problem.

A more specific technical issue proposing such a feature would help make it happen :)

**Comment by Orbots** [comment]
Yup.  I'll break this out into specific issues.  I'll be trying again to build julia code into a maya plugin in the next couple of weeks and will open any issues that I can't work around easily.

Cheers
