### ISSUE TITLE
Incorrect rounding for Float16

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#32441]
```
julia> Base.Float32(exp(big(-17.3)))
3.0669412f-8

julia> convert(Float16, Base.Float32(exp(big(-17.3))))
Float16(0.0)

julia> convert(IEEEFloat16.Float16, Base.Float32(exp(big(-17.3))))
6.0e-8
```

The result is `>eps(Float16(0))/2` and we should be rounding to `eps(Float16(0))`.

**Comment by Keno** [comment]
I've looked into this a bit, and if my understanding is correct, every number with exponent -25 should get rounded to `2^-24`, unless the significand is 0, in which case we should run to 0, according to our ties to even rule. Unfortunately, I don't see an easy way to do that in our current table driven setup.

**Comment by Keno** [comment]
In fact, we may want to re-think the whole enterprise. The original function here was a table-based, branch-free round-to-zero implementation, which then got branches when @JeffBezanson tried to change the rounding to round-to-nearest-even in https://github.com/JuliaLang/julia/commit/db1f27f1a02d56ec4b0cb85068fbf8bbf843f052 (but broke nan-payload preservation) and gained even more branches when @StefanKarpinski tried to fix the nan-preservation in https://github.com/JuliaLang/julia/pull/23253. Perhaps we should just once and for all switch to the branchy version everybody else is using.
