### ISSUE TITLE
USE_BINARYBUILDER = 1 still compiles llvm 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#32458]
For some reason I decided to clean the deps cache. Unfortunately this is now causing very long build times since Julia is now building LLVM from scratch 
```
override XC_HOST = x86_64-w64-mingw32
override MARCH = native
USE_BINARYBUILDER = 1
USE_BINARYBUILDER_OPENBLAS = 1

```

**Comment by Moelf** [comment]
LLVM needs special treatment: https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#llvm

**Comment by vchuravy** [comment]
This should no longer be an issue
