### ISSUE TITLE
efficient subset query for ranges

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#32461]
`issubset(1:5,  1:10^18)` gives an OutOfMemoryError() on Julia 1.1, although it works on 0.6.

From the source I see #26198 is the change, which creates a `Set` when the 2nd vector has `length` > 70, and #28871 disables this for objects without a length. I guess the minimal fix is also to disable this for ranges. 

But there is no need to do this by iteration. I assumed that because `intersect(1:10, 1:10^18)` knows to return a range, this would behave similarly. Should we add similar methods to `issubset`?

**Comment by rfourquet** [comment]
In the general case (when the first argument is not a range), this is fixed by #32003.

**Comment by StefanKarpinski** [comment]
Seems like some specialized methods for this would make sense.
