### ISSUE TITLE
filter could perhaps use a specialization for String

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#32460]
Something like

```jl
filter(x -> x != 'ï' && x != '»' && x != '¿', unclean)
```

is using the generically written `filter` on `AbstractString`.

A specialized version of `filter` on String could perhaps do better.

**Comment by KristofferC** [comment]
Here is an attempt

```
function Base.filter(f, s::String)
    out = Base.StringVector(sizeof(s))
    offset = 1
    for c in s
        if f(c)
            offset += Base.__unsafe_string!(out, c, offset)
        end
    end
    resize!(out, offset-1)
    sizehint!(out, offset-1)
    return String(out)
end
```

which seems to be about 4x faster than the generic one.

**Comment by jsulmont** [comment]
hi @KristofferC - I don't see how one could go faster than with your solution 🤔

**Comment by KristofferC** [comment]
Maybe that is a good enough solution then :). Someone could make a PR with it and add some tests etc. Should also make sure that the `filter` on `AbstractString` is still covered after adding this method.

**Comment by jsulmont** [comment]
Right -- I'll get on it :-)

**Comment by jsulmont** [comment]
Hi @KristofferC please see PR #32478

**Comment by fredrikekre** [comment]
#32478 is merged.
