### ISSUE TITLE
ccall library as a variable string

### ISSUE THREAD

**Issue by mikelehu** [JuliaLang/julia#32474]
This works rigth,
ccall((:lwrite, "/home/mikel/mylibraries/libCbin_IO"), void, ())

But if I define a variable to specify the library,  it does not work.
mylib=/home/mikel/mylibraries/libCbin_IO"
ccall((:lwrite,mylib), void, ())

Can someone help me?

Thanks for contributing to the Julia project!

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
