### ISSUE TITLE
excessive gc time with nthreads>1

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#32472]
```
macro par(expr)
    thunk = esc(:(()->($expr)))
    quote
        local task = Task($thunk)
        task.sticky = false
        schedule(task)
        task
    end
end

function pfib(n::Int)
    if n <= 1
        return n
    end
    t = @par pfib(n-2)
    return pfib(n-1) + fetch(t)::Int
end

pfib(10)
@timev pfib(31)
```

Results:
```
jeff@gurren:~/src/julia$ JULIA_NUM_THREADS=1 ./julia pfib.jl
  9.810682 seconds (17.36 M allocations: 3.699 GiB, 38.38% gc time)
elapsed time (ns): 9810681551
gc time (ns):      3765694561
bytes allocated:   3971501936
pool allocs:       16596025
non-pool GC allocs:768692
GC pauses:         11
full collections:  8
jeff@gurren:~/src/julia$ JULIA_NUM_THREADS=2 ./julia pfib.jl
 17.332301 seconds (18.69 M allocations: 3.309 GiB, 82.00% gc time)
elapsed time (ns): 17332301130
gc time (ns):      14212451824
bytes allocated:   3552716592
pool allocs:       18068469
non-pool GC allocs:618944
GC pauses:         65
full collections:  8
```

Something about the way the GC counters are updated with multiple threads is causing GC to run far more often with 2 threads than with 1.

**Comment by JeffBezanson** [comment]
Seems to be fixed by 611d103d396cdf96581363a3b4be058216cbbc9d, but I'm not sure if that's the whole story or if it just hides the problem.

**Comment by JeffBezanson** [comment]
Also, I haven't merged 611d103d396cdf96581363a3b4be058216cbbc9d since in the test case for #28986 it speeds up the fast case but slows down the slow case. Adding the GC root nulling code fixes that, but adds significant code size.

**Comment by JeffBezanson** [comment]
Ok, not fixed in all cases by 611d103. Even with that commit there are strange fluctuations in gc behavior with thread count:
```
jeffbezanson@arctic1:~/src/julia$ JULIA_NUM_THREADS=4 ./julia pfib.jl
 14.046893 seconds (11.59 M allocations: 1.851 GiB, 87.45% gc time)
elapsed time (ns): 14046893287
gc time (ns):      12283641817
bytes allocated:   1987412624
pool allocs:       11278323
non-pool GC allocs:306904
GC pauses:         65
full collections:  8
jeffbezanson@arctic1:~/src/julia$ JULIA_NUM_THREADS=5 ./julia pfib.jl
  4.163113 seconds (11.82 M allocations: 1.518 GiB, 58.39% gc time)
elapsed time (ns): 4163112893
gc time (ns):      2430855327
bytes allocated:   1629729200
pool allocs:       11632765
non-pool GC allocs:187998
GC pauses:         16
full collections:  4
jeffbezanson@arctic1:~/src/julia$ JULIA_NUM_THREADS=6 ./julia pfib.jl
  5.480835 seconds (11.65 M allocations: 1.997 GiB, 63.22% gc time)
elapsed time (ns): 5480834913
gc time (ns):      3465232568
bytes allocated:   2144534592
pool allocs:       11288802
non-pool GC allocs:358535
GC pauses:         10
full collections:  6
jeffbezanson@arctic1:~/src/julia$ JULIA_NUM_THREADS=7 ./julia pfib.jl
  5.865632 seconds (11.87 M allocations: 1.686 GiB, 69.05% gc time)
elapsed time (ns): 5865631884
gc time (ns):      4050311029
bytes allocated:   1810054032
pool allocs:       11620063
non-pool GC allocs:246879
GC pauses:         19
full collections:  7
jeffbezanson@arctic1:~/src/julia$ JULIA_NUM_THREADS=8 ./julia pfib.jl
 11.821276 seconds (11.59 M allocations: 1.831 GiB, 87.50% gc time)
elapsed time (ns): 11821275501
gc time (ns):      10343332200
bytes allocated:   1965589872
pool allocs:       11291717
non-pool GC allocs:300139
GC pauses:         61
full collections:  8
```

**Comment by JeffBezanson** [comment]
Theory: `scanned_bytes` is not getting updated for the buffer used for stack copying (which we sometimes use if we run out of mmap'd stacks).

**Comment by JeffBezanson** [comment]
Ok, I don't think that's quite it, but the problem only kicks in when the Task workload gets big enough that we run out of mmap'd stacks and start allocating stack buffers.

This is actually a pretty interesting workload, because the amount of allocation is genuinely nondeterministic. When `fetch(t)` is called, we only need to suspend (and therefore do a stack copy) if `t` happens not to have finished yet.

Ordinary Task stacks are managed specially, and so don't interact with GC counters. So perhaps the solution is to make copy-stack buffers also not update GC counters?

**Comment by JeffBezanson** [comment]
Question for @yuyichao: why do minor collection pause times seem to be so variable? For example I make this modification to julia 1.1:
```diff
diff --git a/src/gc.c b/src/gc.c
index e5fb03c..a545643 100644
--- a/src/gc.c
+++ b/src/gc.c
@@ -2826,6 +2826,8 @@ static int _jl_gc_collect(jl_ptls_t ptls, int full)
 
     uint64_t gc_end_t = jl_hrtime();
     uint64_t pause = gc_end_t - t0;
+    if (!sweep_full)
+        printf("%g\n", pause/1e9);
```

and run this:
```
    for i = 1:10
        a = zeros(Float64,14,14,1024,32)
        b = Array{Float32}(undef, (14,14,1024,32))
        c = Array{Float32}(undef, (14,14,1024,32))
    end
```
the output is
```
0.00148739
0.00131211
0.0540855
6.8688e-05
4.6511e-05
0.0457451
5.5206e-05
0.0439238
3.8181e-05
0.0435707
3.8377e-05
0.0434532
3.8454e-05
0.0448424
3.872e-05
0.0443461
4.3183e-05
0.0436452
3.721e-05
0.0433761
3.79e-05
```
Many are tiny, but several are over 40ms. Is this expected? Do we know what the source of the variation is?

**Comment by JeffBezanson** [comment]
Ah, the slow ones are the collections right after a major collection. That must have something to do with it but I'm not sure what.

**Comment by yuyichao** [comment]
If by right after a major collection you mean the one after we decided to do a `sweep_full`, it **is** actually the major collection. I can check the code again to confirm later if you want but I'm pretty sure `sweep_full` tells the sweep to basically reset the bits so that all objects appears as young and the **next** marking cycle does a normal marking which is actually a full marking since the whole heap is young as far as it's concern.
