### ISSUE TITLE
Ubuntu apt-get

### ISSUE THREAD

**Issue by pannous** [JuliaLang/julia#32498]
Is there a more official version to install julia via apt-get than this: ?
```
sudo add-apt-repository ppa:staticfloat/juliareleases
sudo apt-get update
sudo apt-cache show julia
sudo apt-get install julia julia-doc -y
julia -E 'Pkg.update()'
julia
```

**Comment by KristofferC** [comment]
The official way to install Julia is by using the official binaries at https://julialang.org/downloads/.

**Comment by StefanKarpinski** [comment]
Please ask questions on the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
