### ISSUE TITLE
Change in, presumably, macro expansion in 1.2 vs 1.1

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#32499]
Opening this as a dedicated issue so it is easier to track.

On the 1.2-RC2 branch, StochasticModels errors and can be reprod with:

```jl
using StochasticModels

farmer_model = @stochastic_model begin
           @stage 1 begin
           end
           @stage 2 begin
               @uncertain ξ::YieldScenario = begin end
           end
       end
```
on the 1.2-RC2 branch it erros with 

```jl
ERROR: UndefVarError: YieldScenario not defined
```

while it runs without error on 1.1.

When I run `@macroexpand1` on this I get

```jl
@scenario YieldScenario = begin
        end
StochasticPrograms.StochasticModel(StageParameters(), StageParameters()) do sp
    @stage 1 sp = begin
            end
    @stage 2 sp = @uncertain(ξ::YieldScenario = begin
                    end)
end
```

and this executes correctly. So not sure what is happening. @JeffBezanson, perhaps you could take a look.

**Comment by JeffBezanson** [comment]
Would be good to bisect this. Any volunteers?

**Comment by JeffBezanson** [comment]
Ok I guess that will be me then :)
