### ISSUE TITLE
indexin for date/time vectors fails

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#32504]
```
indexin(Dates.DateTime(2019, 04, 10), [Dates.DateTime(2019, 04, 10), Dates.DateTime(2019, 04, 11)])
```

fails:

ERROR: MethodError: no method matching length(::Dates.DateTime)
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:561
  length(::Base.MethodList) at reflection.jl:801
  length(::Core.MethodTable) at reflection.jl:875
  ...
Stacktrace:
 [1] indexin(::Dates.DateTime, ::Array{Dates.DateTime,1}) at ./array.jl:2197
 [2] top-level scope at none:0

**Comment by fredrikekre** [comment]
`indexin` expects two collections:
```
julia> indexin([Dates.DateTime(2019, 04, 10)], [Dates.DateTime(2019, 04, 10), Dates.DateTime(2019, 04, 11)])
1-element Array{Union{Nothing, Int64},1}:
 1
```
Please ask questions on https://discourse.julialang.org/.
