### ISSUE TITLE
scoping after try is random

### ISSUE THREAD

**Issue by kulowf** [JuliaLang/julia#32500]
After try the variables using in the try-block are visible or not.
The behaviour switches by little changes in code.
In the example 

- the new value of g is not visible
- the new variable u from c.jl is visible
- the new variable o is not visible
----------

- d.jl:
`g=11`
`try`
`  include("c.jl")`
`  g=5`
`  o=3`
`catch`
`end`
`@show(u,g,o)`
--------------
- c.jl:
`u = 66`
--------------

julia> include("d.jl")
u = 66
g = 11
ERROR: LoadError: UndefVarError: o not defined

----------

Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by JeffBezanson** [comment]
Well, I can assure you it's not random. What do you think this code should do?

**Comment by kulowf** [comment]
sorry, I did not consider scoping of include
