### ISSUE TITLE
Infinite recursion of == operation on mutable struct causes Bus error

### ISSUE THREAD

**Issue by tk3369** [JuliaLang/julia#32516]
A minor error handling issue.  I would expect a `StackOverflowError` but instead it crashed.

```
julia> mutable struct Bar end

julia> Base.:(==)(a::Bar, b::Bar) = a == b

julia> a = Bar(); b = Bar();

julia> a == b
Bus error: 10
```

It works fine for immutable struct:
```
julia> struct Foo end

julia> Base.:(==)(a::Foo, b::Foo) = a == b

julia> a = Foo(); b = Foo();

julia> a == b
ERROR: StackOverflowError:
Stacktrace:
 [1] ==(::Foo, ::Foo) at ./REPL[15]:1 (repeats 80000 times)
```

**Comment by yuyichao** [comment]
Likely dup of https://github.com/JuliaLang/julia/issues/17109

**Comment by yuyichao** [comment]
From the reporter's other post I assume this is on mac and therefore a dup. Feel free to comment if this isn't on a mac.
