### ISSUE TITLE
read!() for subarrays

### ISSUE THREAD

**Issue by mgkuhn** [JuliaLang/julia#32524]
It would be nice if Base in io.jl had a method `read!(s::IO, a::SubArray{...} ...)` that reads values from a file directly into a subarray, just like fill!() already works on subarrays.

Typical use case: a large 3D voxel volume is available on disk as a stack of image files. In Julia 1.1 I have to load these into an intermediate array `tmp` first and then copy that over:
```
img = Array{UInt16,3}(undef,width,height,images);
tmp = Array{UInt16,2}(undef,width,height);
for i=1:images
  read!(filename[i], tmp)
  img[:,:,i] = tmp;
end
```
Desired solution using subarray:
```
img = Array{UInt16,3}(undef,width,height,images);
for i=1:images
  read!(filename[i], view(img, :, :, i))
end
```
See also the Discourse thread [efficient way to read large array from binary file in slices](https://discourse.julialang.org/t/efficient-way-to-read-large-array-from-binary-file-in-slices/6847).

**Comment by JeffBezanson** [comment]
:+1: Makes sense. Just need to take care to read as large contiguous blocks as possible given the subarray layout.

**Comment by giordano** [comment]
There is a pull request at #33046

**Comment by mgkuhn** [comment]
Supporting only `FastContiguousSubArray`, as proposed in #33046, seems fine to me. A well-designed API should probably avoid offering to users more generic methods that go out of their way to quietly do something inefficient under the hood, thereby hiding the fact that what the user really should do instead is to change their memory layout, such that the accessed views are contiguous. That PR seems to aim for exactly that.

`FastContiguousSubArray` probably should be mentioned in the language manual.

**Comment by mgkuhn** [comment]
A related question: how does one perform the same operation (reading a list of 2D binary slice files as a single 3D array) with memory-mapped I/O (`Mmap.mmap`) instead of `read!`? I can mmap a 2D slice file easily into a 2D Array, but is there already a predefined AbstractArray subtype (implemented as a 1D array of references to 2D arrays) to assemble such a collection of memory-mapped 2D slices into a single 3D Array _without copying any data_?

**Comment by tlnagy** [comment]
Now that #33035 is merged, can we close this issue?
