### ISSUE TITLE
Implement norm for tensors

### ISSUE THREAD

**Issue by lsorber** [JuliaLang/julia#3252]
*Related julia-dev discussion: https://groups.google.com/d/msg/julia-dev/GAdcYzmibyo/iOLpyVQc8YIJ*

Currently, norm is only defined for vectors and matrices. If T is a tensor (which could be a vector, matrix or higher-order tensor), `norm(T,"fro")` and `normfro(T)` should return `norm(T[:])`.

**Comment by jiahao** [comment]
```jl
julia> vecnorm(ones(2,2,2,2,2))^2
32.00000000000001
```

Good enough for me.
