### ISSUE TITLE
every time i try to use this function Println i always get this annoying message 

### ISSUE THREAD

**Issue by waweruk2001** [JuliaLang/julia#32526]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by JeffBezanson** [comment]
In julia functions are generally lowercase: `println`. Please use the discourse forum for help getting started.
