### ISSUE TITLE
printf width

### ISSUE THREAD

**Issue by philippe-maincon** [JuliaLang/julia#32538]
Strongly related to #16977:

I get the following unexpected behaviour:
```
Julia> @printf ">%10g<\n" 1e7
>1e+07<

julia> @printf ">%10g<\n" 3.1415
>    3.1415<
```

1e7 is printed in a too narrow field.  I find this to occur with

> versioninfo()
> Julia Version 1.1.0
> Commit 80516ca202 (2019-01-21 21:24 UTC)
> Platform Info:
>   OS: Windows (x86_64-w64-mingw32)
>   CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
> Environment:
>   JULIA_EDITOR = "C:\Users\philippem\AppData\Local\JuliaPro-1.1.0.1\app-1.36.0\atom.exe"  -a
>   JULIA_NUM_THREADS = 2
>   JULIA_PKG_SERVER = https://pkg.juliacomputing.com/
>   JULIA_PKG_TOKEN_PATH = C:\Users\philippem\.juliapro\token.toml

**Comment by StefanKarpinski** [comment]
Is it not exactly the same issue?

**Comment by philippe-maincon** [comment]
Hi Stefan,
I am careful of making any claim - but I have no objection either: this can very well be the same issue.  Any action I should take (close the issue)?

**Comment by KristofferC** [comment]
Closing as dup.
