### ISSUE TITLE
splitdrive errors on strings containing newlines (windows)

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/julia#32542]
```julia
splitdrive("a\nb")
ERROR: type Nothing has no field captures
```
https://github.com/JuliaLang/julia/blob/d309635accb00bd070e8b3f500971ab296eabae8/base/path.jl#L37-L40
The above doesn't handle the case where `match` returns `nothing`, should it return the original `path`? 

Ref: https://github.com/julia-vscode/julia-vscode/issues/780

**Comment by StefanKarpinski** [comment]
It looks like the regex needs an `s` flag so allow `.` to match newlines. With that change, this regex should always match. Would you be willing to make a PR with that fix and add this as a test?

**Comment by ZacLN** [comment]
aye, https://github.com/JuliaLang/julia/pull/32543
