### ISSUE TITLE
NEWS entry for sprand changes

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#32554]
This change https://github.com/JuliaLang/julia/pull/30494 needs NEWS.

**Comment by abraunst** [comment]
something like this?

* The `sprand` function is now 2 to 5 times faster ([#30494]). As a consequence of this change, the random stream of matrices produced with `sprand` and `sprandn` has changed. If you need to reproduce matrices prior to this change, your best bet is to use the old version of the `sprand` function that you can find [here](https://github.com/JuliaLang/julia/blob/a4b32610cf484b99f69e12d0ac1e192ef5c688a9^/stdlib/SparseArrays/src/sparsematrix.jl) .

**Comment by ViralBShah** [comment]
I think this is fine. I think if someone wants to reproduce the old stream, they should use the older released version of Julia. My view is that we don't want to put it in the NEWS.

**Comment by tpapp** [comment]
I think that in general, it could be emphasized somewhere in the docs that unless explicitly stated otherwise, random APIs in Base and the standard libraries can break reproducibility of random streams/bits without deprecation or prior notice.

**Comment by abraunst** [comment]
> I think this is fine. I think if someone wants to reproduce the old stream, they should use the older released version of Julia. My view is that we don't want to put it in the NEWS.

Ermm.. I don't understand if you are ok with the proposed addition to NEWS or not. :confused:

**Comment by StefanKarpinski** [comment]
> My view is that we don't want to put it in the NEWS.

What? Why would we not put changes to random number sequences in NEWS? That is definitely a "minor change".

**Comment by ViralBShah** [comment]
Sorry for the ambiguity. My proposal was to put the following in the NEWS:

The sprand function is now 2 to 5 times faster ([#30494]). As a consequence of this change, the random stream of matrices produced with `sprand` and `sprandn` has changed. If you need to reproduce matrices prior to this change, please use an older release of Julia.

**Comment by abraunst** [comment]
> Sorry for the ambiguity. My proposal was to put the following in the NEWS:
> 
> The sprand function is now 2 to 5 times faster ([#30494]). As a consequence of this change, the random stream of matrices produced with `sprand` and `sprandn` has changed. If you need to reproduce matrices prior to this change, please use an older release of Julia.

It's fine for me either way, but I think it is pretty nice that you can essentially just cut&paste the old code and have a working `oldsprand` in julia 1.2 in no time. The fact that the libraries are written in Julia makes this possible and is a real strength WRT most other languages. I don't see why not pointing the user to the right commit to save him the search (search which is trivial to do if you have the sources installed, less trivial if you installed from binaries BTW). In my opinion, it would be nice if this could be part of julia's RNG policy and be done consistently...

**Comment by ViralBShah** [comment]
Why not mention it in the documentation of the function? That's the place I would look into if I wanted the old behaviour - not in the NEWS. I guess it could be in the NEWS too, but may stop working with 2.0.

**Comment by KristofferC** [comment]
Imo just point out the change. There is no need to say that one can get the old behavior by using the old code for every change, that is always true.

**Comment by jarlebring** [comment]
Another option is to put the link to the blob with the code for the old stream in the description of PR 30494, and not mention how to get the old stream in the news. The interested user would anyway first go to the PR, where further justifications can be found. 

The `sprand` function is now 2 to 5 times faster ([#30494]). As a consequence of this change, the random stream of matrices produced with `sprand` and `sprandn` has changed.

**Comment by abraunst** [comment]
> Another option is to put the link to the blob with the code for the old stream in the description of PR 30494, and not mention how to get the old stream in the news. The interested user would anyway first go to the PR, where you can also find further justifications in the discussion.

Good idea, I did just that.
