### ISSUE TITLE
support IOBuffer in redirect_stdxxx

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#32567]
Currently it's [rather awkward to capture stdout as a string](https://discourse.julialang.org/t/jupyter-notebook-capture-stdout-and-stderr-like-python-capture-magic/26253).  This would be a lot easier if `redirect_stdout` supported an `IOBuffer` stream argument (currently it only supports `Union{IOStream, LibuvStream}`), so that you could do e.g.:
```jl
buf = IOBuffer()
redirect_stdout(buf) do
    ...
end
String(take!(buf))
```
Possible implementation:
```jl
function redirect_stdout(f::Function, buf::GenericIOBuffer)
    old_stdout = stdout
    try
        rd, = redirect_stdout()
        ret = f()
        Libc.flush_cstdio()
        flush(stdout)
        write(buf, readavailable(rd))
        return ret
    finally
        redirect_stdout(old_stdout)
    end
end
```

**Comment by JeffBezanson** [comment]
Dup of #12711

**Comment by stevengj** [comment]
Ah, right.
