### ISSUE TITLE
`=== nothing` is not `== nothing` with `--code-coverage=user`

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#32579]
I just have a very strange bug that cannot be reproduced locally _and_ replacing `=== nothing` with `== nothing` (as below) fixes this bug.

```diff
diff --git a/examples/primes.jl b/examples/primes.jl
index 7dac9d2f..0f194e7f 100644
--- a/examples/primes.jl
+++ b/examples/primes.jl
@@ -11,7 +11,7 @@ using Transducers

 function sieve(xf, x)
     @info "sieve(xf, x=$x)"
-    if (@show mapfoldl(xf, right, (x,), init=nothing)) === nothing
+    if (@show mapfoldl(xf, right, (x,), init=nothing)) == nothing
         @info "$x is NOT prime"
         nothing, xf
     else
```

See: https://travis-ci.com/tkf/Transducers.jl/builds/119090143 (Ref https://github.com/tkf/Transducers.jl/pull/17)

Maybe it's relevant to #32135?

**Comment by tkf** [comment]
I tried other variants:

* `isa Nothing` works https://travis-ci.com/tkf/Transducers.jl/builds/119091015
* `isnothing` works https://travis-ci.com/tkf/Transducers.jl/builds/119092120
* `!== x` where `x` is not a `nothing` works https://travis-ci.com/tkf/Transducers.jl/builds/119092147

**Comment by StefanKarpinski** [comment]
This seems like it shouldn’t happen.

**Comment by vtjnash** [comment]
Seems like someone may have deleted the build log for the OP?

**Comment by Keno** [comment]
I can reproduce this locally if I try using Run.jl as in the travis script for that package.

**Comment by Keno** [comment]
Looks like the difference is the `--code-coverage=user` flag.

**Comment by Keno** [comment]
Looking at the IR, I see:
```
23 ┄ %44  = φ (#21 => false)::Bool
│    %45  = φ (#21 => _3, #22 => nothing)::Union{Nothing, Int64}
└───        goto #25
24 ─        goto #25
25 ┄ %48  = φ (#23 => %44)::Bool
│    %49  = φ (#23 => %45, #24 => nothing)::Union{Nothing, Int64}
└───        goto #26
26 ─ %51  = (isa)(%49, Nothing)::Bool
└───        goto #28 if not %51
27 ─ %53  = π (%49, Nothing)
└───        goto #31
28 ─ %55  = (isa)(%49, Int64)::Bool
└───        goto #30 if not %55
29 ─ %57  = π (%49, Int64)
└───        goto #31
30 ─        Core.throw(ErrorException("fatal error in type inference (type bound)"))::Union{}
└───        $(Expr(:unreachable))::Union{}
31 ┄ %61  = φ (#27 => %48, #29 => %48)::Bool
```
which looks like an optimizer bug, probably in type lifting.

**Comment by tkf** [comment]
> using Run.jl

Ah, I thought I've tried this...  But yes, I can reproduce it with `Run.test()` now.

**Comment by tkoolen** [comment]
Maybe related to https://github.com/JuliaLang/julia/issues/30872?

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/issues/32135#issuecomment-533975397 for another instance of this
