### ISSUE TITLE
mod(n, range)

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#32571]
It would be neat if `mod` understood ranges, especially for things like `mod(n, axes(A,d))`. 

I see now this was already proposed, back in the stone age, when unfortunately it meant something else:  https://github.com/JuliaLang/julia/issues/14431#issuecomment-241242930. Should we revive this, now that it's available?

**Comment by StefanKarpinski** [comment]
So what, generally is the meaning of modding into a range? Does one imagine the range tiling the space of integers repeating and determine which value in the range an integer falls on? What about ranges with other strides than one?

**Comment by mcabbott** [comment]
I was going to restrict to integers, and ranges of step +-1. And then yes, tiling as you say, with `mod1(n,m) == mod(n, 1:m)`. 

While an easy way of having a shifted `mod2pi` may also be neat, a range like `-π:π` is completely the wrong thing. You could allow real numbers with integer ranges `mod(x, 1:4) == mod(x-1, 3) + 1`, but that seems like pretending that `1:4` is an interval.  

Allowing ranges of integer step > 1 wouldn't be crazy, but would need more thought. OffsetArrays only allows step 1, and I found myself writing things equivalent to `mod(n, axes(A,d))` there.

**Comment by ericphanson** [comment]
For the purpose of indexing, it could be really cool to define a `Mod` object like the `Not` of [InvertedIndicies.jl](https://github.com/mbauman/InvertedIndices.jl) so that in the notation of this issue, `x[Mod(5)] == x[mod(5, axes(x,1))]`, etc.

**Comment by ericphanson** [comment]
I made a package for the `Mod` object: https://github.com/ericphanson/ModularIndicies.jl

**Comment by mbauman** [comment]
Closed by #32628
