### ISSUE TITLE
Julia installation with Fish shell not working.

### ISSUE THREAD

**Issue by BBQuercus** [JuliaLang/julia#32577]
I just downloaded the 64-bit version of Julia-1.1.1 via julialang.org. My MacBook Pro (v. 10.14.5, Early 2015) has Fish as default shell. When installing Julia from the .dmg file (or from the Applications folder), terminal opens as intended but nothing happens. Only once I change back to the default login shell / bash, Julia executes.

As it's working now, there's no need for any help resolving the issue. But it may be a bug fix for certain fishy people :)

**Comment by ViralBShah** [comment]
There's a known issue with non-bash shells on mac, but I can't seem to find it.

**Comment by ViralBShah** [comment]
Dup of #32337
