### ISSUE TITLE
Atom/Julia error powershell wrapper path error

### ISSUE THREAD

**Issue by frawas** [JuliaLang/julia#32589]
I tried installing and using Julia through JuliaPro and by separately installing Atom and Juno, I keep getting this error.
We tried to start Julia with the powershell wrapper but could not find powershell or where on your PATH. Please make sure %SYSTEMROOT%\System32\WindowsPowerShell\v1.0 and %SYSTEMROOT%\System32 are on your PATH and restart Juno.

I'm on a windows 7 machine for a corporate, with temporary admin rights to install Julia on my machine. I followed all the instructions regarding Windows 7 WMF 3.0 and quickfix... all up to date, nothing changed with Julia. 

I tested Julia through the Julia command line and I wasn't able to install any packages either. (cannot link to Github...) so the problem is from Julia and not Atom/Juno.

If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by musm** [comment]
Does a regular julia install work, i.e. from  https://julialang.org/downloads/

**Comment by frawas** [comment]
Yes, I installed Julia regularly and tried to work from the command window and it won't install/add any packages the error : failed to clone from https://github..... failed to send request.

**Comment by musm** [comment]
can you post the full error message, that seems like a different error

**Comment by frawas** [comment]
![Atom_Error](https://user-images.githubusercontent.com/47873566/63060294-b4485a80-bea6-11e9-8441-511bbcdac62c.png)

**Comment by frawas** [comment]
![Capture1](https://user-images.githubusercontent.com/47873566/63060456-2d47b200-bea7-11e9-935a-f215871aa16e.PNG)

**Comment by Robuko** [comment]
same error for me on Windows 7.  I have both on my path
