### ISSUE TITLE
Documentation example of SharedArrays fails when using a SlurmManager

### ISSUE THREAD

**Issue by juandarias** [JuliaLang/julia#32583]
The documentation example for SharedArrays in parallel computing fails when using  a SlurmManager:
`using ClusterManagers, Distributed`
`addprocs(SlurmManager(8), topology=:all_to_all)`
`using SharedArrays`

`a = SharedArray{Float64}(100)`
`@distributed for i = 1:100`
`    a[i] = i`
`end`

Returns an empty array. The following code will work:

`using ClusterManagers, Distributed`
`addprocs(8, topology=:all_to_all)`
`using SharedArrays`

`a = SharedArray{Float64}(100)`
`@distributed for i = 1:100`
`    a[i] = i`
`end`

Versions:
Julia 1.1.0
ClusterManagers 0.3.2

**Comment by jpsamaroo** [comment]
This is probably not an error Julia itself; it would be best to report this to the ClusterManagers.jl repository.

**Comment by juandarias** [comment]
[https://github.com/JuliaParallel/ClusterManagers.jl/issues/121#issue-468037993](url)
