### ISSUE TITLE
Make distinction between variable declaration, assignment and re-assignment 

### ISSUE THREAD

**Issue by catastrop** [JuliaLang/julia#32612]

**Comment by JeffBezanson** [comment]
Too drastic a change IMO.

**Comment by Keno** [comment]
@catastrop You appear to have a pattern of filing low-quality issues without descriptions on various popular repositories. While sometimes there is good discussion to be had, triaging these issues is not a good use of the time of the developers of this repository or the other repositories you like to file issues on. I'd ask you to refrain from doing so in the future. If you are genuinely curious about some of these design decisions, I'd ask you to post on discourse instead.
