### ISSUE TITLE
IMHO julia 1 should be able to handle julia 0x packages 

### ISSUE THREAD

**Issue by etaoinbe** [JuliaLang/julia#32611]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by etaoinbe** [comment]
IMHO julia 1 should be able to handle julia 0x packages 
Julia can call python R even java ? but not its own packages from a  previous release. I dont mind installing two versions of julia as long as the latest julia can call through to the lower julia version just like it can call other languages. Having this functionality would make a lot more libraries available, Most libraries I try are not ported to julia 1 ie mxnet requests ...

**Comment by tomaklutfu** [comment]
You'd get better milage if you complained to specific package to support v1.x.

**Comment by KristofferC** [comment]
Julia 1.0+ will not work with many packages written for julia versions 0.6 that have not been upgraded, and this will not change. As you say, either you an older Julia or you can upgrade the packages to 1.0.

Going via 0.7 and using https://github.com/JuliaComputing/FemtoCleaner.jl will likely help upgrading code.
