### ISSUE TITLE
Typo in comment about prod for sum of BigInt

### ISSUE THREAD

**Issue by Peiffap** [JuliaLang/julia#32647]
https://github.com/JuliaLang/julia/blob/d4018df968019d38943cd5009fe469f1e97ba0b6/base/gmp.jl#L553
I feel like it should be ((a1\*a2)\*(a3\*a4))\*(...). If someone can confirm this is sane I'll fix it, but I just wanted to make sure I'm not losing my mind.

**Comment by rfourquet** [comment]
Good catch! Please go ahead with a fix :)
