### ISSUE TITLE
compiler warning in cgmemmgr.cpp

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#32640]
```jl
/Users/stefan/dev/julia/src/cgmemmgr.cpp:99:9: warning: unused variable 'err'
      [-Wunused-variable]
    int err = fcntl(fd, F_SETFD, FD_CLOEXEC);
        ^
1 warning generated.
```

**Comment by StefanKarpinski** [comment]
Context:
```c
    int err = fcntl(fd, F_SETFD, FD_CLOEXEC);
    assert(err == 0);
```
there is no later use of `err` so when asserts are compiled to no-ops the compiler complains about `err` never being used. Note sure what the cleanest way to avoid the warning is.

**Comment by StefanKarpinski** [comment]
Oh, this is on #32600, haven't checked if it happens on master.

**Comment by Keno** [comment]
> Note sure what the cleanest way to avoid the warning is.

`(void)err;`
