### ISSUE TITLE
include and isfile resolve relative paths differently

### ISSUE THREAD

**Issue by kafisatz** [JuliaLang/julia#32646]
In a piece of code of mine, I have relative path `fi` for a file (`isfile(fi)==true`). 
But `include(fi)` fails as the file cannot be found. 

I understand from @frederikekre that this may be the intended behavior. But this seems very inconsistent to me. What is the purpose of the `isfile` function? Why should it resolve a relative path differently than include? 

I would appreciate a second opinion on this (there is also an MWE): 
https://discourse.julialang.org/t/include-command-inconsistent-with-isfile-result/26578/12

**Comment by elextr** [comment]
`isfile()` is a filesystem wide function, it resolves relative paths in accordance with [abspath](https://pkg.julialang.org/docs/julia/THl1k/1.1.1/base/file.html#Base.Filesystem.abspath), that is it uses the current working directory as the base.  This is the intended operation of all filesystem components and is common behaviour of relative filesystem paths across many ecosystems, not just Julia.

`include()` is for including code into another source file, as such it shouldn't behave differently depending on where it is run. So it is resolved relative to the including source file and that makes it independent of the working directory and allows groups of source files to be moved around together and still correctly refer to each other.

**Comment by kafisatz** [comment]
Ok. I guess we can close this then...
