### ISSUE TITLE
Missing method kron(a, b::UniformScaling)

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/julia#32667]
I feel this should be working

```julia
using LinearAlgebra
kron(rand(2,2), I) # currently doesn't work
```

**Comment by simeonschaub** [comment]
What should this return? It would only make sense if the size of `I` was known.

**Comment by crstnbr** [comment]
Wouldn't it be natural to take `I` as `(2,2)` as well?

**Comment by simeonschaub** [comment]
This seems pretty arbitrary because the Kronecker product works on two matrices, each of which can be of any size. It would be equally as valid to assume a is of size `(1,1)` or `(3,3)`.

**Comment by crstnbr** [comment]
Agreed. It's just that I try to use `I` as a lazy dynamically sized replacement for `eye` which unfortunately does not work in many cases, where I still have to (unnecessarily) materialize it.

Anyways, maybe that's just me wanting it to do what I want.
