### ISSUE TITLE
Linear solve A \ v where A and v are sparse fails

### ISSUE THREAD

**Issue by thudso** [JuliaLang/julia#32668]
Linear solves of sparse systems defined using SparseArrays (where both matrix and vector are sparse) currently fail.

Minimal example:
`using SparseArrays;
A = sprand(2,2,0.9);
v = sparsevec([1;2],randn(2));
A \ v`

This produces:
`ERROR: MethodError: no method matching ldiv!(::SuiteSparse.UMFPACK.UmfpackLU{Float64,Int64}, ::SparseVector{Float64,Int64})`

**Comment by andreasnoack** [comment]
Dup of #19102
