### ISSUE TITLE
pairwise comparison of strings

### ISSUE THREAD

**Issue by pdimens** [JuliaLang/julia#32672]
Hello,

I see that issue #8205 requested pairwise() from distances to be added to `Base`, but I believe my request is different which is why I opened this issue. I have written some code for a basic pairwise comparison of strings on a letter-by-letter level and thought perhaps this could be useful for integration into the appropriate area (possibly `Strings.jl`, if anywhere at all). The code below presents a use of having to broadcast over the characters in a string by splitting the strings into substrings with `split()`. The top function can compare two strings of equal length and return a Boolean array of character-by-character comparisons, and the bottom one will return a multidimensional array of the total operation `true` statements between strings in arrays. Does anyone have insights about the broader utility or application of this inside the Julia ecosystem?

```julia
function pairwise(x::String, y::String, op = ==)
    broadcast(op, split(x,""), split(y,""))
end

function pairwise(x::Array{String,1}, y::Array{String,1} = x, op = ==)
    returnArray = []
    for each in x 
        tmp = Array{Int64,1}()
        for other in y
            push!(tmp, count(broadcast(op, split(each,""), split(other,""))))
        end
        push!(returnArray, tmp)
    end
    return returnArray
end
```
```julia
### example ### 
x = "aabbcc" ; y = "ccbbaa"
julia> pairwise(x,y)
6-element BitArray{1}:
 false
 false
  true
  true
 false
 false


### example ###
x = ["aaaaaa","aaattt","aattaa","tttccc","ttggaa"]
y = ["aaabbb","ttaatt","bbaabb","aaacbc","ttaaag"]
julia> pairwise(x)   #compares against itself
5-element Array{Any,1}:
 [6, 3, 4, 0, 2]
 [3, 6, 3, 0, 0]
 [4, 3, 6, 1, 2]
 [0, 0, 1, 6, 2]
 [2, 0, 2, 2, 6]

julia> pairwise(x,y) #compares against another array
5-element Array{Any,1}:
 [3, 2, 2, 3, 3]
 [3, 3, 1, 3, 1]
 [2, 0, 0, 2, 1]
 [0, 2, 0, 2, 2]
 [0, 2, 0, 0, 3]
```

**Comment by StefanKarpinski** [comment]
Any reason why this function needs to be defined in Base?

**Comment by pdimens** [comment]
There's nothing inherently special about it beyond the fact that when you try broadcasting an operation over two strings, as in:
```julia
x = "potato" ; y = "POtaTo"
julia> x .== y
false
```
it doesn't recognize string inputs as decomposable (for lack of a better term) elements. It would seem like the most "natural" expression for `{String}.=={String}` to do what the `pairwise(x::{String}, y::{String})` function above does. And the same for the other `pairwise` method above.
Ideally, these functions wouldn't be defined in `Base` at all, but rather have `.==` extended for broadcasted `String` and `Array{String}` comparisons.

**Comment by StefanKarpinski** [comment]
You can't win. This was changed for Strings because people were unhappy about broadcast comparing strings elementwise.

**Comment by pdimens** [comment]
Well, that's disappointing, but insightful and assuring in its own way. Thanks for the information!

**Comment by StefanKarpinski** [comment]
Yes, Strings were specifically a type that people wanted to behave as scalars in broadcasting, even though they're iterable.

**Comment by pdimens** [comment]
I'm obviously not a fan, but I can understand that.

**Comment by StefanKarpinski** [comment]
A possible solution would be to have a `chars(str)` function that wraps a string in a `CharIterator` type (or some such) that is explicitly collection-like rather than scalar. Then you could write something like `chars(a) .== chars(b)` to get this behavior.

**Comment by pdimens** [comment]
That's a reasonable solution. I don't believe I understand the Julia language enough to implement that, however if you can direct me to some resources that might help me develop that I can try to look into it.

**Comment by pdimens** [comment]
I've tried this:
```julia
function chars(x::String)
    return String.(split(x,""))
end

function chars(x::Array{String,1})
    tmp = []
    for each in x
        push!(
            tmp,
            String.(split(each,""))
        )
    end
    return tmp
end

x = "aabbcc"
y = "aaccbb"

julia> chars(x) .== chars(y)
6-element BitArray{1}:
  true
  true
 false
 false
 false
 false
```
However, but if I do that for an `Array{String,1}`, it doesn't perform the same way.
```julia
z = ["aattcc","aacctt"]
julia> chars(z) .== chars(z)
2-element BitArray{1}:
 true
 true
``` 

Perhaps my attempts were on a higher level of abstraction than you meant?

**Comment by laborg** [comment]
I think it is enough to have:
```julia
julia> Iterators.Stateful("aattcc") .== Iterators.Stateful("aacctt")
6-element BitVector:
 1
 1
 0
 0
 0
 0
```
