### ISSUE TITLE
06.Loops Jupyter Notebook behavior doesn't match REPL behavior due to unexpected behavior in REPL

### ISSUE THREAD

**Issue by justbyoo** [JuliaLang/julia#32686]
The following code works in a Jupyter Notebook (Julia 1.0.3), but not in the REPL:

```
#n = 0
while n < 10
    n += 1
    println(n)
end
n
```

This works as expected in Jupyter Notebook. In REPL, it returns the following:
```

ERROR: UndefVarError: n not defined
Stacktrace:
 [1] top-level scope at ./REPL[2]:2 [inlined]
 [2] top-level scope at ./none:0
```

This unexpected/inconsistent behaviour risks discouraging the new Julia user from trusting Julia for its lack of consistency. Claiming this is a "feature" resulting from "multiple dispatch" is unlikely to un-discourage the discouraged potential new Julia user.

Please make the REPL environment part of the global scope, by default.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/28789.
