### ISSUE TITLE
Problem Loading Mac Application (1.3) on Catalina

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/julia#32680]
Discussed this with @ararslan.

Loading the app gives: 

```
Last login: Thu Jul 25 12:11:46 on ttys000
exec '/Applications/Julia-1.3.app:/Contents/Resources/julia/bin/julia'
arnavsood@mbp:~$ exec '/Applications/Julia-1.3.app:/Contents/Resources/julia/bin/julia'
-bash: /Applications/Julia-1.3.app:/Contents/Resources/julia/bin/julia: No such file or directory
-bash: exec: /Applications/Julia-1.3.app:/Contents/Resources/julia/bin/julia: cannot execute: No such file or directory
arnavsood@mbp:~$ 
```

There shouldn't be a colon. Remove it and it's fine (i.e., the actual binary embedded in the app works fine.)

```
julia> versioninfo()
Julia Version 1.3.0-alpha.1
Commit f2513a8ca6 (2019-07-23 05:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by ararslan** [comment]
I have an unfounded hunch that it could be a change in AppleScript new in Catalina that affects this line: https://github.com/JuliaLang/julia/blob/master/contrib/mac/app/startup.applescript#L3.

**Comment by ararslan** [comment]
cc @simonbyrne, who IIRC has done a fair bit with the .app packaging on macOS.

**Comment by simonbyrne** [comment]
Looks like an applescript bug. [This discussion](https://forum.latenightsw.com/t/in-case-youre-feeling-adventurous/1963/16) suggests it was fixed in the latest beta.

@arnavs it would be great if you could try out the latest beta to confirm.

**Comment by arnavs** [comment]
Thanks @simonbyrne, will update and report back here.

**Comment by arnavs** [comment]
Yeah, this disappears on Beta 4. 

Thanks for investigating.
