### ISSUE TITLE
SSHManager with csh shell 

### ISSUE THREAD

**Issue by DcfGH** [JuliaLang/julia#32690]
Dear Julia team,

Adding workers using SSHManager (so workers are not local) gives me troubles if user default shell is not bash. Using ssh with multi lines command returns an error in csh (need a back slash for multi lines)

I tried a small change in stdlib/Distributed/src/managers.jl
from (lines 187 up to 190)

```julia
    cmds = """
        cd -- $(shell_escape_posixly(dir))
        $(isempty(tval) ? "" : "export JULIA_WORKER_TIMEOUT=$(shell_escape_posixly(tval))")
        $(shell_escape_posixly(exename)) $(shell_escape_posixly(exeflags))"""
to (one line with 2 commands separated by ";")
    cmds = """cd -- $(shell_escape_posixly(dir)) ; $(isempty(tval) ? "" : "export JULIA_WORKER_TIMEOUT=$(shell_escape_posixly(tval))") $(shell_escape_posixly(exename)) $(shell_escape_posixly(exeflags))"""
```

It seems to work in both cases : csh and bash.

Best regards

**Comment by StefanKarpinski** [comment]
Could you make a pull request with that change?

**Comment by DcfGH** [comment]
Hi,
Pull request is 32765
2 tests are not successful : buildbot/tester_macos64 and buildbot/tester_win64
I hope problems do not come from this change
Best regards

**Comment by mgkuhn** [comment]
The change proposed here does not solve the problem that C shells and POSIX shells have different and mutually incompatible quoting rules. The workaround suggested above will break if the strings passed on contain shell meta-characters, such as single or double quotes. PR #41285 adds instead proper C shell support to SSHManager via option `shell=:csh`.
