### ISSUE TITLE
Add ability to attach edges from MethodInstances to MethodTables

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#32704]
This would allow us to have `hasmethod` be depended on at compile-time

(cc @NHDaly, @vchuravy)

**Comment by quinnj** [comment]
I would like this functionality for some pseudo-interface checking code I'm playing around with.

**Comment by NHDaly** [comment]
For clarity, @oxinabox is referring to the extension that allows Generated Functions to return a CodeInfo and set the `.edges` field to point to an array of MethodInstances.

@oxinabox (and I) would like to extend that to also allow the `edges` array to point to MethodTables as well. This mirrors the ability to have backedges on MethodTables.

If we had such a thing, we could define `hasmethod(f, t...)` via one of these generated functions and provide a forward edge to the method table for `f`, so any time a new method is added to `f`, we would recompute our generated function.

**Comment by oxinabox** [comment]
Closed by #32779
