### ISSUE TITLE
@polly does not handle r = x->x^2 

### ISSUE THREAD

**Issue by freemin7** [JuliaLang/julia#32717]
```
@polly r = x->x^2 ## Throws an error
@polly function r(x) x^2 end ## Throws no error
```
(I could not veify that my Julia instance actually calls Polly but this issue is independent of this fact)

Is that behavior on purpose and if so how can i apply `@polly`'s optimization to an anonymous function?

`versioninfo()
Julia Version 1.0.4
Commit 38e9fb7f80 (2019-05-16 03:38 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4`

**Comment by chriselrod** [comment]
I'm fairly sure you need to build Julia with polly (ie, `USE_POLLY=1` in your `Make.user`) for Polly to work. I think the code will need a few updates before that will work.

**Comment by freemin7** [comment]
I am not talking about Polly. I am talking about the `@polly` macro.
The `@polly` macro does not handle anonymous functions.
``` @polly r = x->x^2 
ERROR: LoadError: r = (x->begin
            #= REPL[5]:1 =#
            x ^ 2
        end) is not a function expression
Stacktrace:
 [1] @polly(::LineNumberNode, ::Module, ::Any) at ./expr.jl:241
in expression starting at REPL[5]:1
```
I've also tried this syntax:
```
r = @polly x->x^2
ERROR: LoadError: x->begin
        #= REPL[7]:1 =#
        x ^ 2
    end is not a function expression
```
I found syntax how i could get Polly to work on anonymous functions.

**Comment by KristofferC** [comment]
Could use

```
r = @polly function(x) x^2 end
```

**Comment by freemin7** [comment]
That suites my needs. I feel stupid now for not thinking about that. Anyway thanks.
