### ISSUE TITLE
Add foldersize() function to mirror filesize()?

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/julia#32728]
I recently found myself needing to check the size of the contents of a directory, but `filesize()` reports (correctly, I think) 4096 for every directory. 

```
julia> filesize(folders[1])
4096

shell> du -hs $(folders[1])
14G    C0016-3F-1A_S94_humann2_temp_WRo8cO
```

Would y'all be willing to add a `foldersize()` function to get the size of a folder?

Something like 

```jullia
function foldersize(dir=".")
      size = 0
      for (root, dirs, files) in walkdir(dir)
          size += sum(map(filesize, joinpath.(root, files)))
      end
      return size
 end
```
```
julia> foldersize(folders[1])
14322488249
```

I'm happy to make a PR, but didn't want to start there if this feature is not desired (or if it already exists elsewhere and I couldn't find it. 

If it _would_ be desired, would it be good to behave more like `du` and eg report the sizes of the files and folders in the current directory, with `human readable` and `summary` options?

**Comment by StefanKarpinski** [comment]
One significant objection to a `foldersize` function is that while `filesize` is O(1), `foldersize` while having a seemingly similar API is O(how much many files you have on your hard disk).

**Comment by kescobo** [comment]
True. There's no way around that though, is there? Could have a `maxdepth` option or something, but that doesn't help if you have a billion files in the first directory. 

One other possible objection that this makes me think of that `du` also suffers from is that if there are files one doesn't have read access on, it might fail (does `walkdir` also have this issue?).

**Comment by StefanKarpinski** [comment]
I suspect that `walkdir` does probably have this issue. This all makes me kind of want to just call out to a specialized program like `du` for this instead of having a builtin function that needs to re-implement all the special logic that program has...

**Comment by kescobo** [comment]
>I suspect that walkdir does probably have this issue.

Confirmed:

```
julia> mkdir("restricted")
"restricted"

julia> for i in 1:10; touch(joinpath("restricted", "$i.txt")); end

julia> mkdir("notrestricted")
"notrestricted"

julia> for i in 11:20; touch(joinpath("notrestricted", "$i.txt")); end

shell> sudo chmod -R 200 restricted/

julia> for (root, dirs, files) in walkdir(".")
           println.(files)
       end
11.txt
12.txt
13.txt
14.txt
15.txt
16.txt
17.txt
18.txt
19.txt
20.txt
ERROR: SystemError: unable to read directory ./restricted: Permission denied
Stacktrace:
 [1] check_channel_state at ./channels.jl:125 [inlined]
 [2] take_unbuffered(::Channel{Any}) at ./channels.jl:327
 [3] take! at ./channels.jl:315 [inlined]
 [4] iterate(::Channel{Any}, ::Nothing) at ./channels.jl:395
 [5] top-level scope at ./REPL[18]:2 [inlined]
 [6] top-level scope at ./none:0
```

The good news is, that seems like the behavior I'd want for `foldersize()` 😆 

>This all makes me kind of want to just call out to a specialized program like du

Do you mean something like

```
julia> function diskusage(dir=".")
           s = read(`du -s $dir`, String)
           return parse(Int, split(s)[1])
       end
foldersize (generic function with 2 methods)

julia> diskusage()
du: ./restricted: Permission denied
ERROR: failed process: Process(`du -s .`, ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:785 [inlined]
 [3] read(::Cmd) at ./process.jl:699
 [4] read(::Cmd, ::Type{String}) at ./process.jl:708
 [5] foldersize(::String) at ./REPL[38]:2 (repeats 2 times)
 [6] top-level scope at none:0

julia> diskusage("notrestricted/")
0
```

Or do you mean just leave it to users to roll their own?

**Comment by StefanKarpinski** [comment]
> Or do you mean just leave it to users to roll their own?

This. Or put it in a package where someone can iterate on the API and make it fancy.

**Comment by kescobo** [comment]
Cool. Does that mean I should close the issue?

**Comment by StefanKarpinski** [comment]
I think so. Having it in a package also has the advantage that it will probably
