### ISSUE TITLE
Unexpected MethodError on julia 1.3

### ISSUE THREAD

**Issue by rbvermaa** [JuliaLang/julia#32726]
When testing the julia 1.3 release candidate, we ran into the following issue.

Dispatch (sometimes) fails to match a valid method w/ subtyped type parameters. The following output shows the issue on julia 1.3:
```
julia> VERSION
v"1.3.0-DEV.554"

julia> f(::Type{T}, ::T...) where T = T
f (generic function with 1 method)

julia> f(Any, 1, 2.0, "hi")
ERROR: MethodError: no method matching f(::Type{Any}, ::Int64, ::Float64, ::String)
Closest candidates are:
  f(::Type{T}, ::T...) where T at REPL[2]:1
Stacktrace:
 [1] top-level scope at REPL[3]:1

julia> f(Any, 1, 2.0)
Any

julia> f(Any, 1, 2.0, "hi")
Any
```

The expected output (on v1.1.1):
```
julia> VERSION
v"1.1.1"

julia> f(::Type{T}, ::T...) where T = T
f (generic function with 1 method)

julia> f(Any, 1, 2.0, "hi")
Any

julia> f(Any, 1, 2.0)
Any

julia> f(Any, 1, 2.0, "hi")
Any
```

**Comment by JeffBezanson** [comment]
> julia 1.3 release candidate

Not relevant to the issue of course, but just want to clarify that there is no 1.3 release candidate yet, just an alpha. Release candidates are very close to final releases, while an alpha is an early preview not expected to be stable or feature-complete.

**Comment by rbvermaa** [comment]
> Not relevant to the issue of course, but just want to clarify that there is no 1.3 release candidate yet, just an alpha. Release candidates are very close to final releases, while an alpha is an early preview not expected to be stable or feature-complete.

Whoops, I was mistaken, obviously it is an alpha :-)

**Comment by rbvermaa** [comment]
(and thank you for the fix 👍 )
