### ISSUE TITLE
Download on MacOS consistently fails with official binaries

### ISSUE THREAD

**Issue by asinghvi17** [JuliaLang/julia#32720]
This has been a problem with binaries from v1.1 to v1.3.0-alpha, where `download` consistently fails either with a timeout, like so:
```julia
┌ Error: Download failed: curl: (7) Failed to connect to svs.gsfc.nasa.gov port 443: Operation timed out
└ @ Base download.jl:43
```
or a "Option not recognized" error (even though the same copy-pasted command works perfectly fine in the REPL shell-mode, _and_ the shell).

Using a Julia executable built locally seems to fix this problem.

**Comment by ararslan** [comment]
Is this with a particular URL or with any URL? Doing `download("https://julialang-s3.julialang.org/bin/checksums/julia-1.3.0-alpha.sha256")` as an example works fine for me with the official binaries.

**Comment by asinghvi17** [comment]
I don't think so - downloading the WorldClim data from http://biogeo.ucdavis.edu/data/worldclim/v2.0/tif/base/wc2.0_10m_prec.zip used to fail consistently until I rebuilt Julia - at which point, somehow even the official binary started working.

**Comment by ViralBShah** [comment]
I think we will need a clear way to reproduce. Let's reopen if we need to.
