### ISSUE TITLE
PackageCompiler segfault on compile_incremental second run

### ISSUE THREAD

**Issue by KestutisMa** [JuliaLang/julia#32733]
I use Fezzik.jl (nice API for PackageCompiler). It allows to compile all statements used in REPL, that allows simple snooping, and tries to solve “time to first anything” problem. But I faced issue that it can’t run it on same sysimage second time, it is inconvenient because one can’t compile more statements into existing sysimage. 
segfault happens if I do
```
julia> using Example
julia> Example.hello("aa")
"Hello, aa"
julia> Fezzik.brute_build_julia()
```

after
```
import AbstractPlotting, Makie; const ap = AbstractPlotting; ap.__init__(); s = ap.lines(rand(10))
Fezzik.brute_build_julia()
```
or
```
import Blink; w = Blink.Window();
Fezzik.brute_build_julia()
```
I made post on disclosure: https://discourse.julialang.org/t/packagecompiler-errors-on-compile-incremental-second-run/26932
Also we are discussing issue here: https://github.com/TsurHerman/Fezzik/issues/3

This error probably originates at C side of Julia. But we do not have experience of debugging such errors, maybe somebody could shed some light about causes of such error?

**Comment by ViralBShah** [comment]
Please reopen if still an issue, since a lot has changed.
