### ISSUE TITLE
Compilation fails on Ubuntu 19.04

### ISSUE THREAD

**Issue by jipolanco** [JuliaLang/julia#32746]
I have been unable to build the `master` and `release-1.2` branches on Ubuntu 19.04. The `release-1.1` branch compiles just fine.

By the end of the compilation, I get:

```
    LINK usr/lib/libjulia.so.1.3
    CC ui/repl.o
    LINK usr/bin/julia
    JULIA usr/lib/julia/corecompiler.ji
WARNING: could not import Core.CodeInstance into IR
ERROR: syntax: invalid syntax (splatnew (call (core apply_type) (outerref NamedTuple) names T) args)
make[1]: *** [sysimage.mk:60: /home/jpolanco/src/julia/usr/lib/julia/corecompiler.ji] Error 1
make: *** [Makefile:81: julia-sysimg-ji] Error 2
```

I have tried running make with `USE_BINARYBUILDER=0` but the build fails with the same error. I have also tried different combinations of options in `Make.user`, but the result is always the same.

Here is my `versioninfo()` obtained on Julia 1.1:

```
Julia Version 1.1.1-pre.0
Commit a84cf6f56c* (2019-01-22 04:33 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
What happens if you `make clean` first?

**Comment by jipolanco** [comment]
Same, I tried `make clean`, `make cleanall`, and even `git clean -fdx`.

**Comment by jipolanco** [comment]
I just checked that the `release-1.2` branch correctly builds on a Ubuntu 19.04 Docker image, on the same machine as before.

So I guess it's an issue with my environment, but I don't really see where it comes from...

**Comment by JeffBezanson** [comment]
The `splatnew` form is introduced in 1.2, so it looks to me like an older (1.1) julia binary is trying to load the new version of base/boot.jl. I suspect somewhere a path is pointing to the older version of julia.

**Comment by jipolanco** [comment]
Thanks for the hint.

Now it builds after I unset `LD_LIBRARY_PATH`. In my `LD_LIBRARY_PATH` I had `/usr/local/lib` which contained libraries from a previous installation of Julia 1.1. I checked that just deleting `/usr/local/lib/libjulia.so.1` also does the trick.

I still find it a bit worrying that the build system prefers the version of `libjulia` found in the `LD_LIBRARY_PATH` instead of the locally built version in `BUILDROOT/usr/lib`. Is there a way to avoid such an issue? Perhaps prepending `BUILDROOT/usr/lib` to `LD_LIBRARY_PATH`?
