### ISSUE TITLE
Broadcasted power does not preserve Diagonal and UpperTriangular types

### ISSUE THREAD

**Issue by ghost** [JuliaLang/julia#32759]
It seems many broadcasted operations preserve LinearAlgebra types. For example,

D = Diagonal(rand(3))
abs.(D)
sqrt.(D)

each return a Diagonal type. However, 

.^(D,2)
D.^2 

return a Matrix type. The behavior is similar for UpperTriangular types. I believe this should be fixed.

**Comment by mbauman** [comment]
We try to automatically detect situations where an operation preserves zeros.  Exponentiation fails this automatic test because of:

```julia
julia> D .^ 0
3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
```

It'll be a little tricky to manually green-light this operation in a safe and robust manner.

**Comment by mbauman** [comment]
Oh wait, I'm wrong in my diagnosis.  We are getting it right but `Base.literal_pow` is messing us up.

```
julia> x = 2
2

julia> D .^ x
3×3 Diagonal{Float64,Array{Float64,1}}:
 0.0869414   ⋅         ⋅
  ⋅         0.412076   ⋅
  ⋅          ⋅        0.387
```

This is definitely weird and needs a fix.
