### ISSUE TITLE
Bug in sparse cholesky permutation argument

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#32760]
As reported in https://discourse.julialang.org/t/sparse-cholesky-factorization-with-user-permutation-julia-1-1/27080. It seems that the `perm` argument has an effect but it's unclear what the effect is.
```julia
julia> using LinearAlgebra, SparseArrays, SuiteSparse, Random

julia> Random.seed!(1234);

julia> A = sprandn(10,10,0.1) |> t->t't + I;

julia> [cholesky(A).p cholesky(A, perm=1:10).p]
10×2 Array{Int64,2}:
  2   2
  5   5
  6   6
  7   7
  8   8
  4   1
  1   3
  3   4
 10   9
  9  10
```

**Comment by JuhaHeiskala** [comment]
From what I could gather from SuiteSparse documentation the permutation is done is two steps.
1. Search for the best permutation to minimize the number of non-zero entries in the factorization result F.
2. post ordering (I did not really understand what is achieved by this. step)

The user permutation parameter impacts the first step, i.e. the optimization is not done. The user permutation is used as such. The second step is still done for the user permutation (unless explicitly disabled).
So one simple solution would be add the postorder argument to the sparse cholesky method signature and pass it to fact_ method postorder argument. (in stdlib/SuiteSparse/cholmod.jl)

**Comment by ettersi** [comment]
For what it's worth, I have a CHOLMOD wrapper [here](https://github.com/ettersi/SparseFactorizations.jl/blob/master/perf/CHOLMOD.jl) which allows for more fine-grained control over the factorisation parameters (supernodal vs simplicial, permutations, etc.). The `C_Common` struct could maybe be move into the Base `SuiteSparse.CHOLMOD` package, it greatly simplifies setting the `cholmod_common` parameters compared to the somewhat hackish workaround in https://github.com/JuliaLang/julia/blob/1170206fd246eca9e8f4510edb7b50abaecb40f1/stdlib/SuiteSparse/src/cholmod.jl#L163-L174.

**Comment by andreasnoack** [comment]
Why not upstream those changes to the SuiteSparse stdlib?

**Comment by ettersi** [comment]
I'm working on this now, but I encountered some problems where some expert input would be helpful. 

----

I'm making some changes to https://github.com/JuliaLang/julia/blob/5b241c2aa97b824ff6b87ad0f89ef05fbb309ddf/deps/SuiteSparse_wrapper.c, but these changes seem to get ignored when I run `make`. What is the correct way to rebuild `libsuitesparse_wrapper`?

----

`cholmod_common` has a field 
```
cholmod_method_struct method [CHOLMOD_MAXMETHODS + 1] ;
```
which I mirror in Julia using
```
method::NTuple{10,cholmod_method_struct}
```
The trouble is that `cholmod_method_struct` has to be immutable for this to work as intended, but then it becomes really awkward to change any of its fields. So far, I have been relying on `Setfield` to get around this, but I assume it is not acceptable for a standard library to depend on a non-standard library?

**Comment by andreasnoack** [comment]
> but these changes seem to get ignored when I run make

I think you might need to set https://github.com/JuliaLang/julia/blob/8f6432e39f8f1dfb403f177b671f934991d2dd09/Make.inc#L1431 to use the local version.

> I assume it is not acceptable for a standard library to depend on a non-standard library?

Yeah. That's not possible. One day SuiteSparse might be a normal package and such convenience will become available for now you'd have to handle it differently.

**Comment by ettersi** [comment]
Setting `USE_BINARYBUILDER_SUITESPARSE := 0` kind of works, but I still need to do `make clean; make` to see the changes. Anyway, it kind of works now so I can move on.

**Comment by ettersi** [comment]
Another question: should the `cholmod_common` struct definition go into [`cholmod.jl`](https://github.com/JuliaLang/julia/blob/master/stdlib/SuiteSparse/src/cholmod.jl) or [`cholmod_h.jl`](https://github.com/JuliaLang/julia/blob/master/stdlib/SuiteSparse/src/cholmod_h.jl)?

**Comment by ettersi** [comment]
I'm a bit confused why some functions use the global `common_struct`, some expect it to be passed as an argument, and yet other functions mix the two modes, e.g. 
https://github.com/JuliaLang/julia/blob/3853060e54c4995740df1b4e7247bafddd9dbf0c/stdlib/SuiteSparse/src/cholmod.jl#L1277-L1298

Would it be okay if I tidy up all functions so they only use the global `common_struct`? That would be the most reasonable in my eyes.

**Comment by ettersi** [comment]
Done: https://github.com/JuliaLang/julia/pull/38919

**Comment by ViralBShah** [comment]
@ettersi I now see this:

```
julia> using LinearAlgebra, SparseArrays, SuiteSparse, Random

julia> Random.seed!(1234);

julia> A = sprandn(10,10,0.1) |> t->t't + I;

julia> [cholesky(A).p cholesky(A, perm=1:10).p]
10×2 Matrix{Int64}:
  1   1
  2   2
  3   3
  5   5
  7   7
  8   8
  9   9
  6   4
  4   6
 10  10
```

**Comment by ettersi** [comment]
[@JuhaHeiskala's post](https://discourse.julialang.org/t/sparse-cholesky-factorization-with-user-permutation-julia-1-1/27080) over on discourse describes the issue and fix well. Fixing this particular issue would be quite easy from a purely technical point of view (we just need to turn off postordering in case the user provided a permutation), but I am not sure whether we are allowed to do so because it might break some code. You guys have more experience on this, so I leave it up to you to decide. I'd be happy to give a hand with the PR, though.

**Comment by ViralBShah** [comment]
We should definitely fix the bug and be correct. If it breaks someone's code who is accidentally relying on the bug, it is ok - and they'll be glad it is fixed.

**Comment by ettersi** [comment]
Done: https://github.com/JuliaLang/julia/pull/40560
