### ISSUE TITLE
Default arguments are leaking between methods

### ISSUE THREAD

**Issue by HFriberg** [JuliaLang/julia#32767]
The following function has a default argument of incompatible type. When calling `foo()` it looks for `foo(::String)` which fails with an amusing closest candidate suggestion -- perhaps I meant to call `foo()`? 😃 This is not too bad though..
```
julia> function foo(x::Integer="hello")
         return 13
       end
foo (generic function with 2 methods)

julia> foo()
ERROR: MethodError: no method matching foo(::String)
Closest candidates are:
  foo() at REPL[1]:2
  foo(::Integer) at REPL[1]:2
Stacktrace:
 [1] foo() at ./REPL[1]:2
 [2] top-level scope at none:0
```

What worries me is that the default argument of this method can leak to other methods of `foo`, as when I continue the example from above with this:
```
julia> function foo(x::String)
         return x * " world"
       end
foo (generic function with 3 methods)

julia> foo()
"hello world"
```

This must be a dispatching bug of some sort?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7357
Not a dispatch bug.

**Comment by KristofferC** [comment]
Closing as dup.
