### ISSUE TITLE
Another typeinference issue/reached the unreachable

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#32766]
Bug original discussion on discourse [1], there is a conceptual example. Sorry that there is no minimal example but type inference only fails in a very specific case, tested for Julia 1.0, 1.1, and 1.2. The issue seems fixed on 1.3 alpha and current master.

To reproduce, clone [2] and run [3], the script should crash the Julia session with `Unreachable reached`.

It requires `MLKernels#master` to work properly.

[1] https://discourse.julialang.org/t/when-does-julia-give-up-on-type-inference
[2] https://github.com/gdkrmr/MLKernelsMissing.jl
[3] https://github.com/gdkrmr/MLKernelsMissing.jl/blob/master/test/bug.jl

**Comment by JeffBezanson** [comment]
Willing to do a bisect to see what fixed it between 1.2 and 1.3-alpha?

**Comment by Keno** [comment]
Taking a look.

**Comment by Keno** [comment]
I cannot reproduce this on the backports branch (https://github.com/JuliaLang/julia/pull/32592). Could you check whether you see the issue on that branch to make sure I didn't do that wrong? Otherwise, the fix will come out with the new RC.

**Comment by gdkrmr** [comment]
I can confirm that the bug is gone in 1.2-backports.

**Comment by gdkrmr** [comment]
will this be backported to 1.0?
