### ISSUE TITLE
Cannot install julia snap in Fedora 30 out of the box.

### ISSUE THREAD

**Issue by barrel0luck** [JuliaLang/julia#32768]
Steps to reproduce:
1. Install snapd on Fedora 30. Restart system.
2. Go to the software centre and search for julia snap and try to install.
![Screenshot from 2019-08-02 16-54-52](https://user-images.githubusercontent.com/44344748/62383093-f7213e80-b546-11e9-8da9-63863d730649.png)

**Comment by nalimilan** [comment]
Apparently this is a known limitation of Snap in Fedora, not something that Julia can fix. A workaround is to do `sudo ln -s /var/lib/snapd/snap /snap`. See https://snapcraft.io/docs/installing-snap-on-fedora, https://bugs.launchpad.net/snapd/+bug/1736939, and https://www.reddit.com/r/Fedora/comments/7x63ib/is_there_a_way_to_install_classic_confinement/?st=jyx3luv5&sh=61a2b0b9.

**Comment by barrel0luck** [comment]
Ah..., thanks!
