### ISSUE TITLE
Automatically add threads when calling `@spawn`

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#32770]
When starting Julia with only one thread and calling `@spawn`, no additional thread is created. I know that this is because the number of threads is currently static so take this as a feature request, how I would expect the system to work in an ideal world.

**Comment by mbauman** [comment]
The pre-requisite here is #16134.

**Comment by JeffBezanson** [comment]
This isn't what `@spawn` means; it's not for creating hardware threads but for exposing parallelism to whatever threads are available. I think this can be combined with #16350, as a request for threading features for interactivity.

**Comment by tknopp** [comment]
responded to the `spawn` meaning on discourse: https://discourse.julialang.org/t/threading-1-3-success-story/27111/6

**Comment by mbauman** [comment]
Is not the point here that there are program structures that demand either pre-emptive (software) threads or hardware threads and would otherwise deadlock?  Whether or not we call that `@spawn`, do we want to support this more directly (beyond just `@assert nthreads() > 1`)?

**Comment by StefanKarpinski** [comment]
There's always the radical alternative of using LD_PRELOAD to replace all blocking libc calls with versions that yield back into the Julia scheduler. No threads required.

**Comment by JeffBezanson** [comment]
> Is not the point here that there are program structures that demand either pre-emptive (software) threads or hardware threads and would otherwise deadlock?

Yes, of course such programs exist. Adding a `pthread_create`-style API would take things in a violently different direction, but I suppose it's not out of the question. However I closed this because `@spawn` can't be the interface to that.
