### ISSUE TITLE
Julia calculation error( 3*3333333333333333333)

### ISSUE THREAD

**Issue by zhuzhenping** [JuliaLang/julia#32782]
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> 3*3333333333333333333
-8446744073709551617

**Comment by vchuravy** [comment]
Yes Julia can overflow for `Int64`, for integers arithmetic that doesn't overflow  use `BigInt`

https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/index.html#Overflow-behavior-1
