### ISSUE TITLE
Snap installation issue and failure to build packages

### ISSUE THREAD

**Issue by gabrielgggg** [JuliaLang/julia#32798]
Hello! I've been using the snap-based install of Julia 1.0 on Ubuntu 18.04 LTS and I kept running into package build problems with it. Switching to the downloaded 1.1 version fixed all. For example, for MPI.jl

https://github.com/JuliaParallel/MPI.jl/issues/300

I had similar issued with CUDAnative not detecting the CUDA driver. It also works flawlessly on downloaded 1.1 on the same system.

The snap seems to have a 32 vs 64 bit issue.

**Comment by mhangaard** [comment]
I think I have a related issue with the snap installation and julia 1.0.4. It says my julia is 32-bit. Full log below.
`julia> Pkg.build("PyCall")
  Building Conda ─→ `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building PyCall → `~/.julia/packages/PyCall/ttONZ/deps/build.log`
┌ Error: Error building `PyCall`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100 62.6M  100 62.6M    0     0  26.7M      0  0:00:02  0:00:02 --:--:-- 26.7M
│ PREFIX=/home/mh/.julia/conda/3
│ reinstalling: python-3.7.1-h0371630_7 ...
│ /home/mh/.julia/conda/3/installer.sh: 373: /home/mh/.julia/conda/3/installer.sh: /home/mh/.julia/conda/3/pkgs/python-3.7.1-h0371630_7/bin/python: not found
│ ┌ Info: No system-wide Python was found; got the following error:
│ │ ErrorException("python3 is 64-bit, but Julia is 32-bit")
│ └ using the Python distribution in the Conda package
│ [ Info: Downloading miniconda installer ...
│ [ Info: Installing miniconda ...
│ ERROR: LoadError: failed process: Process(`/home/mh/.julia/conda/3/installer.sh -b -f -p /home/mh/.julia/conda/3`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:705 [inlined]
│  [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:663
│  [4] run at ./process.jl:661 [inlined]
│  [5] _install_conda(::String, ::Bool) at /home/mh/.julia/packages/Conda/kLXeC/src/Conda.jl:165
│  [6] _install_conda(::String) at /home/mh/.julia/packages/Conda/kLXeC/src/Conda.jl:152
│  [7] runconda(::Cmd, ::String) at /home/mh/.julia/packages/Conda/kLXeC/src/Conda.jl:111
│  [8] #add#1(::String, ::Function, ::String, ::String) at /home/mh/.julia/packages/Conda/kLXeC/src/Conda.jl:184
│  [9] add at /home/mh/.julia/packages/Conda/kLXeC/src/Conda.jl:183 [inlined] (repeats 2 times)
│  [10] top-level scope at /home/mh/.julia/packages/PyCall/ttONZ/deps/build.jl:84
│  [11] include at ./boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1044
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:392
│  [15] top-level scope at none:0
│ in expression starting at /home/mh/.julia/packages/PyCall/ttONZ/deps/build.jl:43
└ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096`
I guess Ill give up on snap and switch to the downloaded version.

**Comment by KristofferC** [comment]
The snap is not an official way to get Julia. Issues with the snap should be reported to wherever one reports issues with snaps.
