### ISSUE TITLE
Missing ambiguity warning and/or unsatisfiable type

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/julia#32809]
The single file [1] is a simple Julia module from Nemo/AbstractAlgebra which defines a few types and tries to instantiate them. 

The final function in the outer module can be called from outside the module to exhibit the bug. It manifests in one of two ways:

* Creation of the empty array results in an error that there is no function defined for the given type. But the type appears to be unsatisfiable. At least I have tried many things and can't write a function which accepts that empty array.

* If the line in the final function marked with a big arrow is removed, an ambiguity warning is issued. However, this line should have no bearing on whether there is an ambiguity or not.

Notes
====

* The module contains a submodule. I was unable to replicate the problem without this, but it may be possible to do so.

* Sorry the example is convoluted, but it was a full day of work to reduce it to this example, and many changes will make the bug go away.

* I am aware that one can type the (empty) array. However, this is quite difficult to do in this case, and not something we would expect our users to do, at the REPL or in a downstream package. We'd prefer to just write a function to accept the empty array, but this doesn't seem to be possible.

* The problem isn't reproducible from the REPL; the example is from our test code.

[1] https://github.com/wbhart/AbstractAlgebra.jl/blob/bug3/src/AbstractAlgebra.jl

**Comment by chethega** [comment]
Can you describe more precise reproduction steps? What exact commands are you running on what version, what is your expected behavior, and what is your observed behavior?

I observe `$ julia AbstractAlgebra.jl` without any errors on 1.1.1 / x86_64-pc-linux-gnu.

**Comment by wbhart** [comment]
Sorry if I wasn't clear in my bug report. I did write "The final function in the outer module can be called from outside the module to exhibit the bug", i.e. you call test_submodule().

The easy way to replicate this is to check out that branch (bug3) and do:

```
using AbstractAlgebra

test_submodule()
```

As I stated in my notes, the problem is not reproducible from the REPL.

The problem exists in all Julia versions. But for clarity, I am currently looking at the failure in Julia-1.0.4.

I think the rest of my bug report is sufficiently clear regarding the expected behaviour and how the bug manifests. But if you have any specific questions, I'm happy to answer them.

**Comment by chethega** [comment]
Thanks for the explanation. Can you also post the _precise_ error message?

I have seen three error messages: 
1. with AbstractAlgebra installed, your code file pasted verbatim:
```julia> AbstractAlgebra.test_submodule()
ERROR: MethodError: no method matching Main.AbstractAlgebra.Generic.FreeModule(::Main.AbstractAlgebra.Integers{BigInt}, ::Int64)
Closest candidates are:
  Main.AbstractAlgebra.Generic.FreeModule(::AbstractAlgebra.Ring, ::Int64) at REPL[1]:47
Stacktrace:
 [1] FreeModule(::Main.AbstractAlgebra.Integers{BigInt}, ::Int64) at ./REPL[1]:67
 [2] test_submodule() at ./REPL[1]:83
 [3] top-level scope at none:0
```
2. Without AbstractAlgebra installed, pasting your code verbatim:
```
ERROR: ArgumentError: Package AbstractAlgebra not found in current path:
- Run `import Pkg; Pkg.add("AbstractAlgebra")` to install the AbstractAlgebra package.
```
3. After fixing your presumably incorrect import statements [here](https://gist.github.com/chethega/95c704962976244145af08ffe9d73dec):
```
julia> AbstractAlgebra.test_submodule()
ERROR: MethodError: no method matching Submodule(::Main.AbstractAlgebra.Generic.FreeModule{BigInt}, ::Array{Main.AbstractAlgebra.Generic.Submodule{_A} where _A,1})
Closest candidates are:
  Submodule(::Main.AbstractAlgebra.FPModule{T}, ::Array{#s2,1} where #s2<:Main.AbstractAlgebra.FPModuleElem{T}) where T<:Union{Main.AbstractAlgebra.RingElem, AbstractFloat, Integer, Rational} at REPL[4]:71
  Submodule(::Main.AbstractAlgebra.FPModule{T}, ::Array{#s2,1} where #s2<:Main.AbstractAlgebra.Generic.Submodule{T}) where T<:Union{Main.AbstractAlgebra.RingElem, AbstractFloat, Integer, Rational} at REPL[4]:75
```
You use an empty list comprehension `[Submodule(M, [M(BigInt[1, 2, 3])]) for i in 1:nsubs]` with `nsubs==0` and rely on the return type (the container type, i.e. the `T` in `Vector{T}`) for dispatch. However, the container type of empty comprehensions is undefined by the julia language! 

Type inference makes a best effort at guessing something that sometimes works; this involves speculating what kind of elements could have gone into the vector if the the comprehension had been non-empty, without actually executing such code (must not trigger side effects). 

You should just compute the type of the comprehension:```c_eltype = ....# 5 lines of type gibberrish
subs = c_eltype[Submodule(M, [M(BigInt[1, 2, 3])]) for i in 1:nsubs] ```

**Comment by wbhart** [comment]
Yes, sorry, you don't need to install AbstractAlgebra to reproduce this. This is a single file which happens to have the same name because it was cut down from the original AbstractAlgebra.jl. Perhaps I should have explained that more clearly.

I am not sure what you mean by incorrect import statements. This code works just fine for me when loading using "using". Perhaps you could clarify in case there is something we don't understand.

Anyhow, error 3 is the issue that I'm reporting in my first point in my OP.

I am not 100% sure if I am understanding your comment about empty comprehensions correctly. I have no knowledge of the inner workings of Julia comprehensions. I simply expect that an empty comprehension will lead to an empty array. There's no way that you can predict in general that a comprehension generated in some bizarre way is going to be empty, so clearly the language has to deal with them.

I understand the type inference cannot infer the Array type that would have resulted if the array had not been empty. I am happy to add a function that accepts an empty array (whatever type it might have). But I have been unable to do this, as I explain in my notes. I may have missed something in the documentation about this, but I can't find anything. Also, the error message that results is not helpful in determining what type I should accept if I were to write such a function.

There is also a second issue related to the same code that I mention in my second bullet point in the OP. For this, you have to remove the single line marked with an arrow. Then I get an ambiguity warning. But removing this line surely should not cause this to happen. That seems like a definite bug.

**Comment by wbhart** [comment]
To be more clear about the exact problem in the first bullet point. Consider:

```
julia> typeof([])
Array{Any,1}
```

Thus I would expect my problem to go away by defining:

```
function Submodule(M::FPModule{T}, a::Array{Any, 1}) where T <: RingElement
      # do something
end
```

But this does not work. The type the compiler is expecting does not seem to be a valid Julia type. (I did try just defining a function with that precise type as it reported it in the error message, but that doesn't work either.)

**Comment by chethega** [comment]
Re incorrect imports: You have some `import AbstractAlgebra: ...`. This refers to the global AbstractAlgebra package. If you instead write `import ..AbstractAlgebra: ...` then this refers to the parent module, that happens to be also called AbstractAlgebra. Types in these two modules are entirely distinct and bear no relation at all. I am guessing that the submodule extends its parent's methods, instead of relying on an installed AbstractAlgebra?

Re your actual problem: The fallback you need is
```function Submodule(m::AbstractAlgebra.FPModule{T}, gens::Vector) where T <: RingElement
       @assert length(gens)==0
          return Submodule(m, elem_type(m)[])
       end
```
The types `Vector{Any}` (aka `Vector{T where T}`) and e.g. `Vector{Int}` have no relation to each other, but both are subtypes of `Vector{T} where T`. As I said, the compiler makes a guess for the hypothetical element type of empty comprehensions. You can see the guess from the error message: `Vector{Main.AbstractAlgebra.Generic.Submodule{_A} where _A}`. This is _not_ related to `Vector{Any}`. 


I suggest we move this discussion to discourse?

**Comment by wbhart** [comment]
Thanks very much for your help. I can confirm that defining the following inside the AbstractAlgebra module:

```
function Submodule(m::FPModule{T}, subs::Vector{S}) where {T <: RingElement, S}
   return Submodule(m, elem_type(m)[])
end
```

fixes the issue for us entirely. So I no longer consider this to be a Julia bug. Of course I'd still prefer the error message to be more helpful than it is. But I also accept that error reporting is one of the hard problems of compiler writing.

I will close this issue and (probably) open a separate ticket for the second problem I reported, which seems entirely unrelated. I previously assumed this was simply a different manifestation of the same problem.

**Comment by wbhart** [comment]
Actually, the other problem goes away with this same change. I still consider that bizarre behaviour, but I won't open a ticket for that.
