### ISSUE TITLE
download: add a hook to rewrite URLs

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#32805]
It would often be handy to be able to intercept URLs that are downloaded with Base.download to be able to redirect them elsewhere. Having an official hook mechanism rather than having to monkey patch Base.download would make this easier and less fragile.

**Comment by oxinabox** [comment]
I feel like advanced functionality, is better served by `HTTP.download`.
Though idk that that case is handled there yet.
Maybe worth opening an issue for it?

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaLang/julia/issues/32804. Pkg uses `BinaryProvider.download`, but we want to merge that into `Base.download` and in a controlled environment, it's important to be able to redirect attempts to download things from the internet to internal replacement locations. If we move HTTP into stdlib then we could rely on `HTTP.download` for this, but I don't see why this couldn't be part of `Base.download`.

**Comment by vtjnash** [comment]
triage seems largely OK with proceeding with this as not a big risk and we were convinced it'll be very useful to a small subset of users
