### ISSUE TITLE
readdlm hangs for stream input

### ISSUE THREAD

**Issue by thchr** [JuliaLang/julia#32811]
The [documentation](https://github.com/JuliaLang/julia/blob/314e355975832538b6b965d30c656cebd50bdc83/stdlib/DelimitedFiles/src/DelimitedFiles.jl#L178-L181) suggests that it should be possible to feed `readdlm` with a stream; but if I try that via `IOStream` the function hangs.
```julia
using DelimitedFiles
A = "1,2,3\n4,5,6"
DelimitedFiles.readdlm(IOStream(A))
```

Tested on v1.1.1.

**Comment by JeffBezanson** [comment]
You want `IOBuffer` here instead of `IOStream`.

**Comment by thchr** [comment]
Ah, makes sense; thanks and sorry for the noise.
