### ISSUE TITLE
Inner function override outside function of different types

### ISSUE THREAD

**Issue by unrealwill** [JuliaLang/julia#32828]
Not sure if it's intended or not, but I was hoping the following code would compile.
It does work if the outside method has a different name than the inner one.

```
ΔΔ( a ) = a

function test()
	a = 5
	ΔΔ = ()-> ΔΔ( a )
	res = ΔΔ()
	println( res )
end

test()
```
Fails with : 
ERROR: LoadError: MethodError: no method matching (::getfield(Main, Symbol("##713#714")){Int64})(::Int64)

The intended usage is improved readability.
I'd like to capture locally some extra variable in a mathematical operator but keep the same name as the standard mathematical operator.

Thanks

**Comment by yuyichao** [comment]
Yes this is indended and code like this will not be allowed as is. You are trying to give the same name two different bindings depending on the context in the same scope and that is definitely not going to be allowed.

What you could do, however, is to make sure that you achieve what you want without needing different name bindings. The context you are trying to use is the argument types so you should just use dispatch. You cannot mutate the global function so you need to create a new functional locally, i.e. in another word, you just need to create a local `ΔΔ` and add the additional dispatch rule in it. Sth like.

```julia
ΔΔ(a) = (@__MODULE__).ΔΔ(a)
ΔΔ() = ΔΔ(a)
```

**Comment by unrealwill** [comment]
Thanks !
Using `(@__MODULE__)`  I don't even have to redefine it : 

The following works : ) 
```
ΔΔ( a ) = a

function test()
	a = 5
	ΔΔ() = (@__MODULE__).ΔΔ(a)
	res = ΔΔ()
	println( res )
end
```
