### ISSUE TITLE
oftype is broken?

### ISSUE THREAD

**Issue by tueboesen** [JuliaLang/julia#32833]
I ran into the following problem with oftype
```
println(typeof(dt))
println(typeof(Tracker.data(x[1])))
println(typeof(oftype(dt,Tracker.data(x[1]))))
println(typeof(convert(typeof(Tracker.data(x[1])), dt)))
```
which gives

```
Float64
Float32
Float64
Float32
```

Now I would have expected the third line to produce Float32 as well, but it does not. And what really surprised me is that the 4th line which I thought would be essentially identical to the third line, produces the expected result.

My version of Julia is:

Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\alyfl\AppData\Local\atom\app-1.39.1\atom.exe"  -a
  JULIA_NUM_THREADS = 4

**Comment by quinnj** [comment]
Are you confused about the order of arguments here?
```julia
   oftype(x, y)

  Convert y to the type of x (convert(typeof(x), y)).
```

**Comment by tueboesen** [comment]
Yeah I'm an idiot... Sorry about that.
