### ISSUE TITLE
BLAS number of threads capped to 16

### ISSUE THREAD

**Issue by Fenges** [JuliaLang/julia#32854]
I'm trying to maximize the number of threads to use for matrices computation. However, the number of threads for BLAS is capped to 16. I also tried to modify NUM_THREADS in deps/BLAS.mk before I build julia but this did not solve my problem. 

Is there a way to configure this cap? Is the cap set in julia or in OpenBLAS? Any suggestions will help! Thanks!

**Comment by Fenges** [comment]
I was able to eliminate the cap by building my own OpenBLAS and compiling Julia with it.

**Comment by ViralBShah** [comment]
Right. The default Julia build probably downloads precompiled binaries. Perhaps the default should be upped to 32 now.
