### ISSUE TITLE
Reducer behaviour not consistent over 1-dimensional arrays

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaLang/julia#32878]
I was looking at https://github.com/JuliaLang/julia/issues/16606 this morning and am not 100% on-board with the dropdims solution - as commented by others, I feel like it obfuscates the purpose of the code, which is performing the reduction.

I just noticed that, working with a 1-dimensional array, a reduction gives me a single value, automatically dropping the dimension. This seems inconsistent with behaviour for higher-dimensional arrays. Is this intended?

**Comment by StefanKarpinski** [comment]
It's consistent and has nothing to do with the dimensionality of the input: reducers without the `dims` keyword argument return a scalar. Example:
```jl
julia> A = rand(3, 4)
3×4 Array{Float64,2}:
 0.195413  0.543549  0.63676   0.872648
 0.931781  0.892374  0.233773  0.0597087
 0.48907   0.896954  0.317274  0.676223

julia> sum(A)
6.745528428752973

julia> sum(A, dims=(1,2))
1×1 Array{Float64,2}:
 6.745528428752973

**Comment by mbauman** [comment]
Yes, this is intended.  For the vector case specifically, it's:

```julia
julia> sum(ones(3))
3.0

julia> sum(ones(3), dims=1)
1-element Array{Float64,1}:
 3.0
```
