### ISSUE TITLE
implement degree trig functions on square matrices

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#32876]
See this closed PR: https://github.com/JuliaLang/julia/pull/27254.

**Comment by pmk21** [comment]
I'd like to work on this, I'm new to contributing here and any advice on how to solve this would be helpful.

**Comment by StefanKarpinski** [comment]
A possible implementation was given in the linked PR. It would need tests, NEWS and documentation updates in order to be ready to merge. There was also the possibility raised of generalizing `deg2rad` and `rad2deg` to support any kind of value that can be multiplied by a scalar, which would include arrays (and in particular matrices). I would suggest exploring that approach first and seeing how it plays out.

**Comment by simonbyrne** [comment]
Is there actually a use case for this? Or just for a sense of completeness?

Note that any solution should correctly handle `sind` raison d'etre, e.g. `sind(180) == 0`, `sind(30) == 0.5`

**Comment by StefanKarpinski** [comment]
I don't recall what the original situation for this was. I think I was trying to call some generic code on a matrix instead of a scalar and this was what failed.

**Comment by AtsushiSakai** [comment]
Hi. I created a PR #39758 to fix this issue. I'm happy for someone to review it. Thanks.
