### ISSUE TITLE
Logical or Boolean operators somehow missing in documentation

### ISSUE THREAD

**Issue by oheil** [JuliaLang/julia#32871]
Documentation v1.3-dev
https://docs.julialang.org/en/v1.3-dev/
(and before)

Section "Mathematical Operations and Elementary Functions" is missing a subtopic about boolean or logical operators, like || and &&
https://docs.julialang.org/en/v1.3-dev/manual/mathematical-operations/
but they are refered to in the subsection
Operator Precedence and Associativity
https://docs.julialang.org/en/v1.3-dev/manual/mathematical-operations/#Operator-Precedence-and-Associativity-1

Section "Control Flow" does mention them only in subsection
https://docs.julialang.org/en/v1.3-dev/manual/control-flow/#Short-Circuit-Evaluation-1

Subsection
https://docs.julialang.org/en/v1.3-dev/manual/missing/#Logical-operators-1
talks about 
> Logical (or boolean) operators |, & and xor are another special case, as they only

but uses bitwise operators | and & in the text.

**Comment by laborg** [comment]
Boolean operators have been documented in https://github.com/JuliaLang/julia/pull/35996
@oheil is this enough?

**Comment by vtjnash** [comment]
let's say it is, unless someone wants to add more
