### ISSUE TITLE
Dispatch bug? for `convert(typeof(x), x)` with `x` an `Interval`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#32884]
```jl

(v1.3) pkg> add IntervalArithmetic

julia> using IntervalArithmetic

julia> x = interval(3, 4)
[3, 4]

julia> T = typeof(x)
Interval{Float64}

julia> @which convert(T, x)
convert(::Type{Interval{T}}, x::Interval) where T in IntervalArithmetic at /Users/dpsanders/.julia/dev/IntervalArithmetic/src/intervals/conversion.jl:20
```

This should be calling the previous line instead, which defines the more specific (?) method
```jl
convert(::Type{Interval{T}}, x::Interval{T}) where {T}
```
See
https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/1516c5e1ca8e088aeafa9574072512aa2df241fb/src/intervals/conversion.jl#L19

Reported here: https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/317

Fix here: https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/320
which replaces `convert(::Type{Interval{T}}, x::Interval)` with `convert(::Type{Interval{T}}, x::Interval{S}) where {T, S}`

**Comment by JeffBezanson** [comment]
Sorry about that. This is #6383 again. It's because the type parameter in `Interval` is restricted to `Real`, but in `Interval{T} where T` it's unrestricted.

**Comment by dpsanders** [comment]
Ah I see, thanks a lot!
