### ISSUE TITLE
About .+ 

### ISSUE THREAD

**Issue by hack1nt0** [JuliaLang/julia#32916]
`mapreduce(x->(x,x), .+, 1:10)` produces **ERROR: UndefVarError: .+ not defined**

Isn't **.+** of function type? If not, what type is it ?

**Comment by fredrikekre** [comment]
https://docs.julialang.org/en/v1/manual/arrays/#Broadcasting-1

**Comment by mbauman** [comment]
It's a special syntax.  Please use the [discourse message board](https://discourse.julialang.org) for questions like this.

**Comment by JeffBezanson** [comment]
Now that the deprecations around `.+` are all removed, we could consider making `.+` refer to a function `(x,y) -> x .+ y`. Perhaps that's just confusing though.

**Comment by StefanKarpinski** [comment]
I think that would be good. One occasionally needs this and I don't really see the downside.
