### ISSUE TITLE
Overriding Base methods accidently

### ISSUE THREAD

**Issue by EconometricsBySimulation** [JuliaLang/julia#32945]
Running `Version 1.1.1` and found that I can accidentally override Base methods if I define a function before calling the Base method.

```julia
# New Session
range(x) = x
# returns no error
?range
  search: range LinRange UnitRange StepRange StepRangeLen trailing_zeros AbstractRange trailing_ones OrdinalRange AbstractUnitRange AbstractString

  No documentation found.

  range is a Function.

  # 1 method for generic function "range":
  [1] range(x) in Main at untitled-d4144ac2b0beee0ecce9976f37df72e8:4

# New Session
range(1,stop=5)
range(x) = x
# returns error
```

**Comment by yuyichao** [comment]
This is by design. This way new functions added to base or other package won't affect existing code.

**Comment by StefanKarpinski** [comment]
Also, note that you're not affecting `Base.range` at all, you're shadowing it with your own function called `range`, which is generally how namespaces work. The alternative would be that you cannot have your own thing called `range`, which would be pretty unfortunate.

**Comment by EconometricsBySimulation** [comment]
Thanks for the response.
