### ISSUE TITLE
Arraylike: AbstractArrays without an eltype

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#32940]
Would be useful for many packages, JuliennedArrays, LightQuery, SplitApplyCombine, MappedArrays, Query, etc. Base already has an AbstractEltypelessArray: the lazy broadcast machinery, it would just be a matter of formalizing the interface. Given that traits aren't coming any time soon, it couldn't be `<: AbstractArray`, so we would have to duplicate all of the machinery for `AbstactArrays`. I could try to build a prototype if people are interested?

**Comment by JeffBezanson** [comment]
I think it would be more realistic to use eltype `Any`, and try to get things working as well as possible with such arrays.

**Comment by bramtayl** [comment]
Oh, ok, if that would be easier.

**Comment by bramtayl** [comment]
Ok, while I'm at it, it would be nice to have abstractarray machinery for all sorts of things, zips of arrays, generators of arrays

**Comment by bramtayl** [comment]
Actually, we could just change most AbstractArray functions to be Union{AbstractArray, AbstractEltypelessArray} and nip the problem in the bud, I think.

**Comment by bramtayl** [comment]
Took a shower, came back, and realized that because this is a meaningful subtype relationship, we don't need eltypes or Unions. PR coming.

**Comment by bramtayl** [comment]
```
"""
    abstract type Arraylike{NumberOfDimensions} end

Things that have a shape, but not a compile-time [`eltype`](@ref). Use
[`AbstractArray`] if you know the eltype at compile-time.
"""
abstract type Arraylike{NumberOfDimensions} end

abstract type AbstractArray{Eltype, NumberOfDimensions} <: Arraylike{NumberOfDimensions} end
```

TADA problem solved

**Comment by bramtayl** [comment]
Welp, its not that easy because AbstractArray is implemented in C according to boot.jl. I'll punt on making a PR.

**Comment by JeffBezanson** [comment]
The type is not compile time.

**Comment by tkf** [comment]
:+1: for this direction.  I needed to emulate `Arraylike` using `Union` when implementing mapreduce for Broadcasted #31020.  There was a small discussion in https://github.com/JuliaLang/julia/pull/31020#discussion_r255292414

**Comment by bramtayl** [comment]
@JeffBezanson this is the stickingpoint for adding JuliennedArrays functionality to base. I was looking through src to see how hard it would be to add Arraylike to base. I see that Signed is added in base/boot.jl, and Int64 is added in src/builtins.c, but where is the code that says Int64 <: Signed?

**Comment by bramtayl** [comment]
See discussion in #34196
