### ISSUE TITLE
1.2 can't find packages

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/julia#32976]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by fredrikekre** [comment]
> If you have a question please search or post to our Discourse site: https://discourse.julialang.org.

**Comment by ctkelley** [comment]
Installed 1.2 and ran from terminal 
/Applications/Julia-1.2.app/Contents/Resources/julia/bin/julia
error message was

ERROR: LoadError: ArgumentError: Package AbstractFFTs not found in current path:
- Run `import Pkg; Pkg.add("AbstractFFTs")` to install the AbstractFFTs package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:876
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1094
 [4] include at ./Base.jl:31 [inlined]
 [5] include_ifexists at ./client.jl:219 [inlined]
 [6] load_julia_startup() at ./client.jl:327
 [7] exec_options(::Base.JLOptions) at ./client.jl:266
 [8] _start() at ./client.jl:464
in expression starting at /Users/ctk/.julia/config/startup.jl:4

line 4 of my startup.jl file is

using AbstractFFTs

This was not a problem when I went from 1.0 to 1.1.

**Comment by KristofferC** [comment]
> This was not a problem when I went from 1.0 to 1.1.

Pretty sure it was (or you had already installed it on an 1.1 RC or something).

**Comment by ctkelley** [comment]
OK. What do I need to do? Delete startup.jl and start over?

**Comment by KristofferC** [comment]
If you want the same packages you can just `cp -r ~/.julia/environments/v1.1 cp -r ~/.julia/environments/v1.2`.

**Comment by ctkelley** [comment]
Millie grazie!

C. T. Kelley
Mathematics Department
NCSU
tim_kelley@ncsu.edu
