### ISSUE TITLE
Stray icon-theme.cache file in the 1.2 Linux release

### ISSUE THREAD

**Issue by cafaxo** [JuliaLang/julia#32980]
I downloaded the official Linux release of Julia 1.2 (julia-1.2.0-linux-x86_64.tar.gz). Compared to the 1.1.1 release, there is an additional file **icon-theme.cache** in the extracted archive at **share/icons/hicolor**. This file was probably shipped accidentally.

**Comment by simeonschaub** [comment]
I ran into the same thing. This caused file a problem installing Julia 1.2 on Manjaro for me.

**Comment by fredrikekre** [comment]
8f1479bc1affb4e3216403874623ea92cc4eed6b maybe?

**Comment by ararslan** [comment]
Sure, it'd be good to remove a stray file that isn't needed.

> This file caused a problem installing Julia 1.2 on Manjaro for me.

That doesn't really make sense. How could this cause an installation problem?

**Comment by simeonschaub** [comment]
The problem was that the file already existed on my system and I was trying to unpack the official binary to my root directory, but the script wouldn't overwrite this file. (I was using the `julia-bin` package from the AUR) Manually deleting the file solved the issue, but I wonder if other package managers might run into similar issues

**Comment by aytekinar** [comment]
> That doesn't really make sense. How could this cause an installation problem?

Because of a conflict with an already existing file in the system path, should the package maintainers choose to install under `/usr` rather than `/opt`.

> The problem was that the file already existed on my system and I was trying to unpack the official binary to my root directory, but the script wouldn't overwrite this file. (I was using the julia-bin package from the AUR) Manually deleting the file solved the issue, but I wonder if other package managers might run into similar issues

If you like [my version](https://github.com/aytekinar/PKGBUILDs/blob/master/julia-stable/PKGBUILD), you can use it with:
```
git clone https://github.com/aytekinar/PKGBUILDs /tmp/pkgbuilds
cd /tmp/pkgbuilds/julia-stable
makepkg --syncdeps --clean --cleanbuild --nocheck --install
```

**Comment by o01eg** [comment]
Same issue when installing 1.2.0 on Gentoo.
