### ISSUE TITLE
QRCompactWY documentation is not accurate when minimum(size(A)) > 36

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#32986]
The member matrices of `QRCompactWY` struct are not accurately described by the documentation since the block size passed to `LAPACK.geqrt!` is upper-bounded by 36:

https://github.com/JuliaLang/julia/blob/19a2b2e417fe80e83e2d2964db70451835abb4d4/stdlib/LinearAlgebra/src/qr.jl#L242

For example,

https://github.com/JuliaLang/julia/blob/19a2b2e417fe80e83e2d2964db70451835abb4d4/stdlib/LinearAlgebra/src/qr.jl#L91

is not accurate (it's not square):

```julia
julia> size(qr(ones(37, 37)).T)
(36, 37)
```

ref: https://github.com/JuliaLang/julia/pull/32887#discussion_r315559951

Besides documenting the correct structure of the matrices in the blocked QR case, it'd be nice to quickly mention the rationale behind 36.  AFAICT it's introduced by #4565 but there was no discussion.  (Was it obvious? I guess I'm too LinearAlgebra noob.)

**Comment by andreasnoack** [comment]
Yes. That is indeed not correct. The matrix `T` is a block row matrix where each block is upper triangular. The size of each block depends on compile time constants in LAPACK that you supposed to be chosen to match your cache size for good BLAS-3 performance. In practice, nobody (but possibly supercomputing centers) changes these values but they could have any size.

**Comment by tkf** [comment]
> The size of each block depends on compile time constants in LAPACK that you supposed to be chosen to match your cache size for good BLAS-3 performance.

Do you mean it is desirable to match `36` in the definition of `qr!` with the constant in LAPACK?  It is still the argument of `geqrt!` that decides `size(T, 1)` (= block size), right?

**Comment by andreasnoack** [comment]
My bad. I replied too fast. Most of the other LAPACK routines have the block size fixed at compile time but indeed this routine has the block size as an argument. I don't remember why 36 was chosen. Most likely I tried to find the optimal value for a specific matrix on my computer.

**Comment by tkf** [comment]
Thanks for the clarification. If nobody complained for more than 5 years maybe it's probably a reasonable default?

FYI I just send a PR to document how QRCompactWY works (or at least my understanding of it): #32996
