### ISSUE TITLE
Division of complex finite values by infinite complex values should always return zero

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#32992]
Currently
```julia
julia> complex(1.0) / (Inf + Inf*im)
NaN + NaN*im
```
but the result should be a complex 0.  According to the comments, division between `ComplexF64` is based on https://arxiv.org/abs/1210.4539, but I'm not sure how to fix the algorithm to deal with this.

This is related to #29840 (but that issue has been hidden by using `inv` in PR #32252).  This is not a duplicate of #23134 as that issue was about the case where the numerator is real.

**Comment by DilumAluthge** [comment]
Fascinating. The answer is correct for `Float16`, `Float32`, and `BigFloat`, but wrong for `Float64`.

```julia
julia> complex(Float16(1.0)) / (Float16(Inf) + Float16(Inf)*im)
Float16(0.0) + Float16(0.0)im

julia> complex(Float32(1.0)) / (Float32(Inf) + Float32(Inf)*im)
0.0f0 + 0.0f0im

julia> complex(BigFloat(1.0)) / (BigFloat(Inf) + BigFloat(Inf)*im)
0.0 - 0.0im

julia> complex(Float64(1.0)) / (Float64(Inf) + Float64(Inf)*im)
NaN + NaN*im
```

**Comment by DilumAluthge** [comment]
Fascinating.

```julia
julia> complex(Float16(1.0)) / (Float16(Inf) + Float16(Inf)*im)
Float16(0.0) + Float16(0.0)im

julia> complex(Float32(1.0)) / (Float32(Inf) + Float32(Inf)*im)
0.0f0 + 0.0f0im

julia> complex(BigFloat(1.0)) / (BigFloat(Inf) + BigFloat(Inf)*im)
0.0 - 0.0im

julia> complex(Float64(1.0)) / (Float64(Inf) + Float64(Inf)*im)
NaN + NaN*im
```

**Comment by giordano** [comment]
That's because complex division for `Complex{Union{Float16,Float32}}` is defined as
```julia
/(z::Complex{T}, w::Complex{T}) where {T<:Union{Float16,Float32}} =
    oftype(z, widen(z)*inv(widen(w)))
```
and `inv` can deal with `Inf` denominator since PR #32050.  Division for `Complex{BigFloat}` has yet another method.  Note that the sign of the complex part is different.
