### ISSUE TITLE
Try openblas extensions for copy, transpose, gemm3m etc. 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#32997]
Following on https://github.com/xianyi/openblas/issues/50 and https://github.com/xianyi/openblas/issues/51, there are now [OpenBLAS extensions](https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions) for gemm3m, in place and out of place transposition and copying, and matrix addition.

Might give us better performance in some cases.

**Comment by andreasnoack** [comment]
Is it really expected that BLAS will be faster for transposition, copying, and addition?

**Comment by ViralBShah** [comment]
I think for transpose, one can always do smarter things - there is the whole literature on cache oblivious algorithms. We have had several discussions on faster copying. I doubt addition will be faster - but the simplest thing to do is benchmark and see.

**Comment by staticfloat** [comment]
I would be a little disappointed if OpenBLAS is significantly faster than us for Level 1 BLAS operations.  It seems to me that there shouldn't be that much work to do in optimizing that.  Indeed we should double-check, but I would be surprised if we can't hit peak memory bandwidth in Julia.

**Comment by antoine-levitt** [comment]
Did a PR for `gemm3m`. Unless I'm messing up somewhere in the benchmarking, our (blocked) `transpose!` is ~3x faster than OpenBLAS, at least for square matrices. We don't have in-place transpose, however.

**Comment by StefanKarpinski** [comment]
I’m not surprised about transpose—that’s a tricky operation. The other ones I would think llvm would do fine at.

**Comment by staticfloat** [comment]
I think you read that backwards Stefan; we’re faster with transpose. :)

**Comment by ViralBShah** [comment]
How do rectangular transposes fair?

**Comment by antoine-levitt** [comment]
OK, that's interesting, there isn't much difference between rectangular and square. However, the results are actually strongly machine dependent. On machine 1 (sandybridge), OpenBLAS is consistently 2-3x slower than julia. On machine 2 (haswell), it depends on the matrix size: sometimes OpenBLAS is faster, sometimes julia is. The difference is about 10-20%. That's for an assortment of matrices of sizes between 500 and 1000. Here's the script if anybody wants to try: https://gist.github.com/antoine-levitt/3e263dfe38a4435e02ac558e47a30fa9. Conclusion is that we probably shouldn't switch, and I'm opening an issue for the sandybridge performance.

**Comment by ViralBShah** [comment]
Thanks! If you have the output from the script handy on the different machines, can you post that in the gist too?

**Comment by ViralBShah** [comment]
Closing since the open PRs address all the issues here.

**Comment by antoine-levitt** [comment]
Done.
