### ISSUE TITLE
The test for checking FMA_NATIVE is faulty.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33011]
We currently check for support for FMA (fused multiply add) by doing

```
const FMA_NATIVE = muladd(nextfloat(1.0),nextfloat(1.0),-nextfloat(1.0,2)) != 0
```

From https://github.com/JuliaLang/julia/pull/33010#issuecomment-523493896 @yuyichao said:

> This test is wrong. Llvm has all the freedom it want to return either values for muladd no matter if fma is available. Fwiw, arm / aarch 64 even have fast muladd instruction with intermediate rounding.

**Comment by mbauman** [comment]
More details and a breadcrumb for exposing LLVM support here: https://github.com/JuliaLang/julia/issues/9855.

**Comment by yuyichao** [comment]
We don't really need LLVM support since we have all the information in `src/processor*` now.

It's hard to expose a user-facing generic, flexible and stable API but for now exposing a temperary internal API should do no worse than now (Also note that the check cannot be fixed as is since it's at most reflecting the compiling machine status)

We could simply add a function to `process_*.cpp` `jl_is_fma_native` which will be implemented as `jl_test_cpu_feature(JL_X86_fma) || jl_test_cpu_feature(JL_X86_fma4)` for x86, `jl_test_cpu_feature(JL_AArch32_vfp4)` for arm, `1` for `aarch64` and `0` for `fallback`.

**Comment by yuyichao** [comment]
FWIW, given the target machine people are likely going to run julia on, I feel like setting it to `true` for `x64` should be fine......................... Assuming the user of it doesn't directly emit `fma` instruction of course....

**Comment by chriselrod** [comment]
The Travis Mac doesn't have fma.

Despite compiling locally on a machine where it should be true, it's somehow set to `false` (although running the definition in the REPL returns `true`) . I guess that's because
> Llvm has all the freedom it want to return either values for muladd no matter if fma is available.

**Comment by JeffreySarnoff** [comment]
What if we changed
`const FMA_NATIVE = muladd(nextfloat(1.0),nextfloat(1.0),-nextfloat(1.0,2)) != 0`
to
`const FMA_NATIVE = fma(nextfloat(1.0),nextfloat(1.0),-nextfloat(1.0,2)) != 0`
(at worst) it would be correct much more often

**Comment by oscardssmith** [comment]
Wait, that's our check? That's straight up broken. We absolutely should fix that.

**Comment by JeffreySarnoff** [comment]
https://github.com/JuliaLang/julia/pull/37886

**Comment by simonbyrne** [comment]
To follow up on @yuyichao's [comment](https://github.com/JuliaLang/julia/issues/33011#issuecomment-523505014), we could do:
```julia
import Base.BinaryPlatforms.CPUID

function has_fma()
    CPUID.test_cpu_feature(CPUID.JL_X86_fma) ||
    CPUID.test_cpu_feature(CPUID.JL_X86_fma4) ||
    CPUID.test_cpu_feature(CPUID.JL_AArch32_vfp4) ||
    normalize_arch(String(Sys.ARCH)) == "aarch64"
end
```

This has two problems:
1. It doesn't match the cpu target used by Julia i.e. starting `julia -C "nehalem"` will still give `has_fma() == true`.
2. It won't be constant propagated, so would need to be used with `@static`, i.e.:
```julia
if @static has_fma()
   ...
end
```

In other words, we wouldn't be able to use this for the standard library, as it would simply be reflecting the architecture of the buildbot.

**Comment by simonbyrne** [comment]
Is there a way we can query the cpu_target from within Julia?

**Comment by oscardssmith** [comment]
Theoretically https://github.com/JuliaLang/julia/pull/43085 should take care of this for us.
