### ISSUE TITLE
Exception not catched in a try/catch block

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#33013]
```julia
f(x::Int) = 2x
(try global f; f = 3; finally f end)
```

results in

```
ERROR: invalid redefinition of constant f
Stacktrace:
 [1] top-level scope at REPL[96]:1
```

Shouldn't we able to dismiss this error to the fact we are in a try/catch block ?

**Comment by phlavenk** [comment]
Your problem is the missing catch statement where you can dismis the exception. Try
```julia
(try global f; f = 3; catch e;finally f end)
``` 
where no error is generated.

**Comment by o314** [comment]
My fault. I am still learning Julia,
sometimes feeling it becomes a very beast to tame.

Thanks for your quick answer.

**Comment by StefanKarpinski** [comment]
The try block stuff is a bit confusing but mostly copied from other languages. Try/catch and try/finally are essentially totally different constructs: the former catches errors, the latter does not. The main reason they're both introduced with the `try` keyword is that you often want to use them together in a try/catch/finally construct which catches errors and potentially rethrows them, but always runs the finally clause no matter what. Again, not the most elegantly designed construct, but also not original to Julia.
