### ISSUE TITLE
PDF Manual Symbol Problems

### ISSUE THREAD

**Issue by Ronneesley** [JuliaLang/julia#33017]
Hello, 
          Some symbols in manual ([PDF](https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.2.0.pdf)) isn't appearing. See some the occurrences:

**Function composition and piping**

The symbol: ∘

```julia
(sqrt ∘ +)(3, 6)
```

**Repeated Evaluation: Loops**

The symbol: ∈

```julia
for s ∈ ["foo","bar","baz"]
     println(s)
end
```

It can be trouble for beginners.

**Comment by fredrikekre** [comment]
Can you reopen this at https://github.com/JuliaDocs/Documenter.jl ? It is possible that this was fixed by https://github.com/JuliaDocs/Documenter.jl/pull/1066 but that might not have been deployed yet.
