### ISSUE TITLE
public shell_quote, shell_unquote API

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#33024]
There's a reason that `Base.shell_escape`, `Base.shell_parse` and `Base.shell_split` are not exported: they are kind of a wonky, not-quite right API, with bad names. I've highlighted some of the issues in https://github.com/JuliaLang/julia/pull/31989#issuecomment-523651609, including:

* `Base.shell_escape` does quoting not escaping
* `Base.shell_parse` should be pared with `Base.shell_quote` but it produces a very internal data structure that is not really useful outside of the implementation of backticks
* `Base.shell_split` is actually the rough inverse of `Base.shell_escape` but not quite: `Base.shell_escape` is String --> String while `Base.shell_split` is String --> Vector{String}
* There are also the variations: `Base.shell_escape_posixly` and hypothetically `Base.shell_escape_dosly` and `Base.shell_escape_powerfully` (for PowerShell, presumably, @vtjnash?)

It would be good to have an official shell quoting and unquoting API since as it is people are just using `Base.shell_escape` even though it's internal and unofficial. Maybe it belongs in a packages (or stdlib) but the current situation is a bit of a mess (my mess).

**Comment by JamesWrigley** [comment]
I seem to have inadvertently done this anyway in https://github.com/JuliaLang/julia/pull/53510 :sweat_smile: I guess this can be closed now.
