### ISSUE TITLE
Reductions of Transpose, Adjoint, PermutedDimsArray

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#33029]
Taking the `sum` of a transposed matrix is much slower than summing the parent. Should there perhaps be methods which unwrap this?
```julia
rr = rand(1000,1000);
@btime sum($rr, dims=1) # 284.119 μs (1 allocation: 7.94 KiB)

tt = transpose(rr);
@btime sum($tt, dims=2)' # 1.504 ms (7 allocations: 8.13 KiB)
```
Seems similar on Julia 1.0 to 1.3, and also for `adjoint` & `PermutedDimsArray`.

**Comment by mcabbott** [comment]
A simple idea is this:
```julia
Base.mapreduce(f, op, A::Transpose; dims) = 
    transpose(mapreduce(f, op, A.parent, dims = 3 .- dims))

Base.dropdims(A::Transpose{<:Any, <:Matrix{<:Number}}; dims) = 
    dropdims(A.parent, dims = 3 .- dims)
```
(With thanks but not blame to @antoine-levitt  on slack!) This means `sum(::Transpose; dims)::Transpose`, not sure whether that's a good or a bad idea. Does it count as a breaking change? 

You could replace `transpose` with `permutedims` and it's still much quicker.

The second definition is because `dropdims(transpose(ones(3,1)), dims=1)` gives you an ugly `reshape(::Transpose{Float64,Array...` thing. Perhaps that's something that should be improved independent of this issue, although again it changes the returned type.

**Comment by tkf** [comment]
I guess you need to transpose the element before passing it to `f`?

```julia
Base.mapreduce(f, op, A::Transpose; dims) =
    transpose(mapreduce(f ∘ transpose, op, A.parent, dims = 3 .- dims))
```

Also, I wonder if you can just transpose the result array before passing it to `mapreducedim!`, e.g., here

https://github.com/JuliaLang/julia/blob/19a2b2e417fe80e83e2d2964db70451835abb4d4/base/reducedim.jl#L317-L318

so something like this (untested)

```julia
transpose(mapreducedim!(f ∘ transpose, op, transpose(reducedim_init(f, op, A, dims)), A.parent))
```

The result will be an `Array` (or whatever `reducedim_init` returns).

**Comment by mcabbott** [comment]
I wondered a bit about recursive `transpose`, my test case is that I think these should agree:
```julia
mm = [(10i .+ j .+ [0,1000]) .* ones(Int, 2,2) for i=1:3, j=1:3]
sum(transpose(mm), dims=1)
sum(collect(transpose(mm)), dims=1)
```
I like the `reducedim_init` idea, will see if I can fiddle a bit more to make it work.

**Comment by tkf** [comment]
What I wanted to mention was that just "flipping" `dims` does not help when the `f` passed to `mapreduce` depends on if the element is `transpose`d or not.  For example, consider the case `f = x -> x[1, end]`:

```julia
julia> sum(x -> x[1, end], transpose(mm), dims=1)
1×3 Array{Int64,2}:
 3036  3066  3096

julia> transpose(sum(x -> x[1, end], mm, dims=2))  # "without f ∘ transpose"
1×3 Transpose{Int64,Array{Int64,2}}:
 36  66  96

julia> transpose(sum(x -> transpose(x)[1, end], mm, dims=2))  # "with f ∘ transpose"
1×3 Transpose{Int64,Array{Int64,2}}:
 3036  3066  3096
```

**Comment by mcabbott** [comment]
Good point. So to solve both our tests, you want this:
```julia
Base.mapreduce(f, op, A::Transpose; dims) = 
    transpose(mapreduce(transpose ∘ f ∘ transpose, op, A.parent, dims = 3 .- dims))
```

**Comment by tkf** [comment]
Yep, although it would be great if you can make `mapreducedim!` thing work.

**Comment by mcabbott** [comment]
Bump? #39513 implements this.
