### ISSUE TITLE
Officially end Windows 7 support

### ISSUE THREAD

**Issue by cup** [JuliaLang/julia#33030]
With issues like 32198 being closed, I dont think its fair to say that Julia
supports Windows 7 anymore, as the experience with the default terminal is so
bad as to be unusable.

I think it would be helpful to change the message here:

https://julialang.org/downloads

to reflect that Julia now requires Windows 8 or Windows 10, whatever the case
is.

**Comment by cup** [comment]
https://github.com/JuliaLang/julia/issues/32198

**Comment by vtjnash** [comment]
See discussion at https://github.com/nodejs/node/issues/29269 explaining that the end of Windows 7 support from Microsoft to fix your bugs doesn't mean we are going to immediately break the platform. While most developers don't have Windows 7 (few enough find it worth the hassle to run Windows at all) to test on, the fact is, it still meets the criteria set forth on that page for being tier 1 supported (that Julia builds and passes all tests). We're not beholden to bugs in other software on your system, even software bundled with the operating system.

**Comment by cup** [comment]
@vtjnash it seems maybe you are not too familiar with the Windows ecosystem.

The fix in question:

https://github.com/microsoft/terminal/issues/269

is only available with verion 2 of the terminal, which is not compatible with
Windows 7. So for you or anyone to say, "just upgrade to the newer terminal" is
essentially saying, "just upgrade your operating system".

If thats what you are saying, fine, but you cant say in one breath that you need
to upgrade operating system, then in the next breath say Windows 7 is supported.

Regardless of what tests have been passed, Julia is effectively unuable with the
default terminal in Windows 7. The downloads page should reflect that, else you
are just misleading and upsetting any Windows 7 users that might wish to use
Julia.

**Comment by KristofferC** [comment]
Again, the fact that the OS has a bug that makes the cursor disappears sometimes in the REPL doesn't mean that the OS is not supported.

**Comment by StefanKarpinski** [comment]
I have added a recommendation on various downloads pages that users of legacy Windows versions install and use a better terminal: https://github.com/JuliaLang/www.julialang.org/pull/432.
