### ISSUE TITLE
String interpolation with terminal dot breaking 1.2 -> 1.3

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#33044]
This is more a difference than a bug, but definitely breaking:

1.2:
```julia
julia> var = 3
3
julia> println("Hello from var $var.")
Hello from var 3.
```

1.3-rc1:
```julia
julia> var = 3
3

julia> println("Hello from var $var.")
ERROR: syntax: unexpected ")"
Stacktrace:
 [1] top-level scope at REPL[1]:0
```

From HISTORY.md:
> Non-parenthesized interpolated variables in strings, e.g. "$x", must be followed by a character that will never be an allowed identifier character (currently operators, space/control characters, or common punctuation characters) (#25231).

So this was sort of warned but not erroring before 1.3

## Edit

Going even deeper, the error does not happen with 1-char variable identifiers:
```julia
julia> x = 1
1

julia> "$x."
"1."

julia> println("$x.")
1.
```

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/32948.

Let's not count multiple identical bug reports against a nice feature.

**Comment by matbesancon** [comment]
Ok my initial assumptions were extremely overfitted, thanks all

**Comment by StefanKarpinski** [comment]
Great. I'm glad that it's already fixed!
