### ISSUE TITLE
while loop bug

### ISSUE THREAD

**Issue by ALFLAG** [JuliaLang/julia#33048]
Good evening.

I just started julia training and I want to report a bug.
I tried a while loop in a julia script, and an UndefVarError occur. I'm using julia-1.2-0.

The same problem have been reported in this issue https://github.com/JuliaLang/julia/issues/32686 , but closed before solving because apparently the same issue is present here  https://github.com/JuliaLang/julia/issues/28789, but it has been opened a year ago and still not resolved. So I dig up the subject !

Here the code
```
n = 1
println(n)
while n < 10
    println(n)
    n += 1
end
println(n)
```

and here, the result I get after launching the code in a script mode in Ubuntu 18.04 terminal
```
1
ERROR: LoadError: UndefVarError: n not defined
Stacktrace:
 [1] top-level scope at /home/aflageul/julia/julia-1.2.0/bin/test.jl:7
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1094
 [4] include(::Module, ::String) at ./Base.jl:31
 [5] exec_options(::Base.JLOptions) at ./client.jl:295
 [6] _start() at ./client.jl:464
in expression starting at /home/aflageul/julia/julia-1.2.0/bin/test.jl:6
```

Thank you so much for this new language. Despite this while loop problem, I really think Julia is a promessfull language.

Alex

**Comment by KristofferC** [comment]
You need to use ´global n += 1`. See e.g. https://discourse.julialang.org/t/repl-and-for-loops-scope-behavior-change/13514, https://discourse.julialang.org/t/scope-and-global-in-repl-julia-0-7/10233.
