### ISSUE TITLE
Intersection of CartesianIndices

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#33055]
Hey,
I recently stumbled across the fact, that intersection of CartesianIndices can be quite slow and scales with the size of the ranges that are used. As such I found out that there is no specialized version for the intersection of multiple CartesianIndices. Does this have any reason? If not, if you want and if you tell me where that line
```julia
Base.intersect(a::CartesianIndices, b::CartesianIndices) = CartesianIndices(intersect.(a.indices, b.indices))
```
 would go and what the proper naming conventions here are, I could do a pull request.
EDIT: How to handle intersect(IdentityUnitRange, IdentityUnitRange) and mixed intersect?

https://github.com/JuliaLang/julia/blob/master/base/multidimensional.jl#L385
And while looking into this file, why do you not use a short-circuiting `&&` in this line?

**Comment by mdav2** [comment]
What needs to be done to get this merged? The implementation of `intersect` above cut down my runtime by orders of magnitude, so it seems like a good idea!

**Comment by timholy** [comment]
Submit a pull request with some tests.
