### ISSUE TITLE
`Libdl.dllist` returns module names and not paths on Wine

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#33060]
In cc7fc96c9f4 we add `jl_dllist` which is the implementation of `Libdl.dllist`on Win32. The expectation is that this is the path to the dl.

> Return the paths of dynamic libraries currently loaded in a `Vector{String}`.

To obtain the list of loaded dl's we use [1] and [2]. I couldn't find a place in the docs where it explicitly states
that the `ModuleName` parameter shall be the path to the module. Indeed on Wine it is not. It is the name of the file stripped of it's extension. See https://github.com/wine-mirror/wine/blob/053a7e225c8190fd7416b3f3c3186f1ac230eeb3/dlls/dbghelp/module.c#L938 and https://github.com/wine-mirror/wine/blob/053a7e225c8190fd7416b3f3c3186f1ac230eeb3/dlls/dbghelp/module.c#L122 

This breaks cross-compilation with Wine (after #33059):

```
error during bootstrap:
LoadError("sysimg.jl", 16, LoadError("Z:\\mnt\\build\\usr\\share\\julia\\stdlib\\v1.4\\Pkg\\src\\Pkg.jl", 31, LoadError("Z:\\mnt\\build\\usr\\share\\julia\\stdlib\\v1.4\\Pkg\\src\\BinaryPlatforms.jl", 798, ArgumentError("Invalid dynamic library path 'libgfortran-5'"))))
record_backtrace at /mnt/build/src/mnt/julia/src\task.c:224 [inlined]
jl_throw at /mnt/build/src/mnt/julia/src\task.c:461
parse_dl_name_version at Z:\mnt\build\usr\share\julia\stdlib\v1.4\Pkg\src\BinaryPlatforms.jl:643
detect_libgfortran_version at Z:\mnt\build\usr\share\julia\stdlib\v1.4\Pkg\src\BinaryPlatforms.jl:680
#detect_libgfortran_version#27 at Z:\mnt\build\usr\share\julia\stdlib\v1.4\Pkg\src\BinaryPlatforms.jl:710
#detect_libgfortran_version at .\none:0 [inlined]
detect_compiler_abi at Z:\mnt\build\usr\share\julia\stdlib\v1.4\Pkg\src\BinaryPlatforms.jl:784
jl_fptr_args at /mnt/build/src/mnt/julia/src\gf.c:1934
```

`Libdl.dllist` returns:
```
dll = "julia"
dll = "ntdll"
dll = "kernel32"
dll = "libjulia"
dll = "advapi32"
dll = "dbghelp"
dll = "iphlpapi"
dll = "msvcrt"
dll = "psapi"
dll = "secur32"
dll = "netapi32"
dll = "rpcrt4"
dll = "ws2_32"
dll = "user32"
dll = "gdi32"
dll = "version"
dll = "userenv"
dll = "winmm"
dll = "ole32"
dll = "msacm32"
dll = "libgcc_s_sjlj-1"
dll = "libwinpthread-1"
dll = "libssp-0"
dll = "libstdc++-6"
dll = "llvm"
dll = "shell32"
dll = "shlwapi"
dll = "shcore"
dll = "imm32"
dll = "powrprof"
dll = "libpcre2-8"
dll = "libgmp"
dll = "libmpfr"
dll = "libgmp-10"
dll = "libgit2"
dll = "crypt32"
dll = "bcrypt"
dll = "winhttp"
dll = "jsproxy"
dll = "oleaut32"
dll = "libssh2"
dll = "libdsfmt"
dll = "libopenblas"
dll = "libgfortran-5"
dll = "libquadmath-0"
dll = "libsuitesparse_wrapper"
dll = "libumfpack"
dll = "libcholmod"
dll = "libcamd"
dll = "libsuitesparseconfig"
dll = "libccolamd"
dll = "libcolamd"
dll = "libamd"
```

An alternative might be to use [4] and [5] to obtain handles to all loaded modules and the lookup the path (and not the name) itself. Since the behaviour differs between Wine and Windows I can also file this upstream as a bug, but the behaviour in the docs is ambiguous

[1] https://docs.microsoft.com/en-gb/windows/win32/api/dbghelp/nf-dbghelp-enumerateloadedmodules
[2] https://docs.microsoft.com/en-gb/windows/win32/api/dbghelp/nc-dbghelp-penumloaded_modules_callback#parameters
[4] https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-enumprocessmodules
[5] https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea

**Comment by musm** [comment]
fixed by https://github.com/JuliaLang/julia/pull/33062 ?

**Comment by Keno** [comment]
Did we ever file this as a bug with upstream wine?

**Comment by vtjnash** [comment]
probably not, we just decided to bypass it
