### ISSUE TITLE
String interpolation issue with parsing of parentheses?

### ISSUE THREAD

**Issue by Krastanov** [JuliaLang/julia#33066]
on julia 1.0.3

```
julia> var="foo"; "($var)"
"(foo)"
```

on julia 1.3.0-rc1

```
julia> var="foo"; "($var)"
ERROR: syntax: extra token ")" after end of expression
Stacktrace:
 [1] top-level scope at REPL[4]:0

julia> var="foo"; "($(var))"
"(foo)"
```

The trailing closing parenthesis confuses the parser it seems?

Noticed first in https://github.com/JuliaPy/PyCall.jl/issues/709

**Comment by KristofferC** [comment]
Fixed on master and will be in the next 1.3RC.
