### ISSUE TITLE
make difference between variable initialization and re-initialization

### ISSUE THREAD

**Issue by lithic** [JuliaLang/julia#33074]
like using `:=` operator to initialize a variable and `=` for re-initialization.

**Comment by KristofferC** [comment]
There is no difference. There is just `=` which means assignment. `=` is quite well-documented,

**Comment by lithic** [comment]
@KristofferC, If there is a different syntax that will make codes more readable. we will easily be able to identity the origin of of a variable.

**Comment by KristofferC** [comment]
Please move follow-up discussion to https://discourse.julialang.org.

**Comment by lithic** [comment]
@KristofferC, Can't we do it here?

**Comment by KristofferC** [comment]
The issue tracker is not suitable (or intended) for these type of discussions. The forum where I linked is, so let's please move over there.
