### ISSUE TITLE
SingularException(2) error while doing complex matrix inversion

### ISSUE THREAD

**Issue by mamuniut09** [JuliaLang/julia#33098]
> Hello all,

I wanted to have the inverse of a complex matrix, but it shows SingularException (2) error.
For example: 

> 

`a=[1.0+2.0im 1.0+2.0im; 
    1.0+2.0im 1.0+2.0im];
inv(a)`

It gives the error 
`SingularException(2)`

I was wondering if anybody help me out regarding this.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
