### ISSUE TITLE
Strange result combining range and ternary operation 

### ISSUE THREAD

**Issue by bhalonen** [JuliaLang/julia#33109]
```1: -1 == 1 ? 3 : 2```
results in the integer 2.
as does
```1:-1 == 1 ? 3 : 2```
Similar to #23599.

**Comment by bhalonen** [comment]
The range 1:-1 is being compared to 1, which gives 2.

**Comment by StefanKarpinski** [comment]
What's the issue? Looks correct to me.

**Comment by bhalonen** [comment]
I expected it to form a range, for full context it was.
```a[1: -1 == 1 ? 3 : 2]```
which gives the element `a[2]`
Perhaps this only confused me.

**Comment by StefanKarpinski** [comment]
The range `:` operator has higher precedence than the ternary `?:` operator.
