### ISSUE TITLE
restore type info in `show` of float types?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#33115]
See https://github.com/JuliaLang/julia/pull/32799#issuecomment-525727486.

Before:
```
julia> Any[1.0f0, 1.0]
2-element Array{Any,1}:
 1.0f0
 1.0  
```

after:
```
julia> Any[1.0f0, 1.0]
2-element Array{Any,1}:
 1.0
 1.0
```

**Comment by JeffBezanson** [comment]
Triage concludes we should put back the behavior of `show`.

But, the difference between `1.0`, `1.0f0`, and `Float16(1.0)` is certainly ugly and could use future improvement. Separate issue however.

**Comment by StefanKarpinski** [comment]
Specifically, it would be great to have a generalizable syntax for this in Julia 2.0 but it will likely be breaking because of numeric literal juxtaposition, e.g. `1g0` or `1h0` would be breaking to introduce as new syntax.

**Comment by quinnj** [comment]
Feel free to assign to me

**Comment by quinnj** [comment]
Ok, PR up: https://github.com/JuliaLang/julia/pull/33124

**Comment by quinnj** [comment]
Ok, for the record, the PR that got merged was https://github.com/JuliaLang/julia/pull/33152 (github was really weird w/ the other one).
