### ISSUE TITLE
Nested structs allowed

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#33122]
Via the #helpdesk, tagging @musm . Somehow this is possible:
```
struct A
    a
    struct B
        b::A
    end
    A(a) = B(new(a)).b
end
```

My suspicion is that this is allowed by accident but I am happy to be corrected otherwise. 

(By the way, I played with this and I think it is now truly recursive, because `B` depends on `A` and `A` has `B` in its inner constructor, so you cannot even unwrap that definition. )

**Comment by vchuravy** [comment]
Equivalent to:
```
julia> struct A
           a
           A(a) = B(new(a)).b
       end

julia> struct B
          b::A
       end
```

**Comment by mschauer** [comment]
Ah, I was trying to use it somehow. So it is unintentional and serves no function?

**Comment by StefanKarpinski** [comment]
You can evaluate arbitrary code inside of struct bodies.

**Comment by laborg** [comment]
Dup of https://github.com/JuliaLang/julia/issues/23518
