### ISSUE TITLE
Printing of `AbstractArray{Bool}` changed from 1.1 to 1.2

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#33131]
Julia 1.1:
```julia
julia> [true, false]
2-element Array{Bool,1}:
  true
 false
```

Julia 1.2:
```julia
julia> [true, false]
2-element Array{Bool,1}:
 1
 0
```

Is this intentional? I don’t see it mentioned in the release notes.

**Comment by fredrikekre** [comment]
> Is this intentional?

Yes, see https://github.com/JuliaLang/julia/pull/30575
