### ISSUE TITLE
Potential confusing behaviour with mutable-key Dict

### ISSUE THREAD

**Issue by runapp** [JuliaLang/julia#33176]
I found it confusing when using Vector(Array) with Dict as key type. Basicly I found that there's value comparasion(`isequla`) along with `===` in `ht_keyindex`. But I can do this:

```julia
a,k=Dict(),[1]
a[k]=1
k[1]=2;
display(a);
a[k]=2;
println(a);   # Dict{Any,Any}([2]=>1,[2]=>2)
println(pop!(a,[2]));   # 2
println(a);   # Dict{Any,Any}([2]=>1)
println(a[[2]]);   # KeyError
```
~~which is counterintuitive to me. I've asked [on discourse](https://discourse.julialang.org/t/whats-the-expected-behaviour-when-using-vector-as-dict-hash-key/28431), and thanks to mbauman and tim.holy for replying. ~~
The final line raises a `KeyError`. It might be hard to debug, considering julia doesn't have mature debugger currently, and the problem is not so clear to one when one can only see the final Dict (from the 2nd last line).
I wonder if it'd be better to disable mutable keys for `Dict` and add a seperate `MutableKeyDicts`, which does a copy on the key in `addindex!`.

**Comment by yuyichao** [comment]
The question would be how you determine if the type is (user-)mutable? That is pretty much only a convention. We have types like `BigFloat` that should still be allowed and I don't think you can just special case those.

**Comment by runapp** [comment]
@stevengj has pointed out I forgot about `IdDict`. So I updated the example to turn to the new point.

**Comment by yuyichao** [comment]
> add a seperate `MutableKeyDicts`, which does a copy on the key in `addindex!`.

(I assume you meant `setindex!`). Please don't make that (copying) the only way to do things. Having it be the default with some very easy way to opt-out would be fine. There are many cases where the aliasing doesn't matter since the key won't be used after the `setindex!`. Having to copy in such case would be bad.

**Comment by JeffBezanson** [comment]
Our policy on this so far has just been to tell people not to do it. Personally I don't run into many cases where an object is both mutated and used as a `Dict` key. Did this arise in some real use case, or is it just a theoretical concern?

**Comment by vladium** [comment]
> Personally I don't run into many cases where an object is both mutated and used as a Dict key.

Hashing mutable objects is quite common: when a subset of immutable fields is used as the hash/equality key but the entire struct is the “value”. Think of an AbstractHashSet data structure, with "key" and "value" co-located in memory and lending themselves to highly cache-efficient access. Not allowing structures like such tends to lead to duplication of key fields in two places ('K' and 'V' of a Dict{K, V}).

Of course, the above does not translate in the same way to a language that supports (im)mutability at the level of types only, not fields. Yet Julia seems capable of having an AbstractHashSet{K} if 'K' were allowed to be mutable and the structure accepted functors for hashing and comparing 'K's based on a subset of fields of 'K'.

**Comment by StefanKarpinski** [comment]
The comment above is not about disallowing hashing of mutable values but about the fact that when you use a value as a hash key it is unusual to also mutate it.

**Comment by vladium** [comment]
> I wonder if it'd be better to disable mutable keys for Dict and add a seperate MutableKeyDicts...

**Comment by runapp** [comment]
@yuyichao Yes it's just what I want - a safe but might-be-less-efficient one as default, and offers fine tunings as construction option.

**Comment by StefanKarpinski** [comment]
> For something like
> `mutable struct Customer name::String ssn::Int end`
> could I hash only on (immutable) "ssn" and leave "name" mutable?

Yes, that's fine. As long as you don't mutate anything that contributes to the notion of `isequal` or `hash` then everything is fine. Another reason not to disallow hashing of mutable types.
