### ISSUE TITLE
Segmentation fault causes a deadlock

### ISSUE THREAD

**Issue by tanhevg** [JuliaLang/julia#33179]
The segfault can be triggered by multiple `@inbounds` assignments to an array that are actually out of bounds.

According to [this strace](https://gist.github.com/tanhevg/b2da7ef694dfdd7f00482d82437e7ead), julia 1.2.0. attempts to allocate memory from within the `SIGSEGV` handler, using `malloc`. This is not allowed: according to [this man page](http://man7.org/linux/man-pages/man7/signal-safety.7.html) and [this SO post](https://stackoverflow.com/questions/15477385/segmentation-fault-while-calling-malloc-and-program-in-deadlock-futex), `malloc` is _not_ async-signal-safe. More information about the stack trace, memory map and my system is in [this gist](https://gist.github.com/tanhevg/802946c3bda330ae1fd0da6855e8a774)

**Comment by tanhevg** [comment]
More often than not the segfault does not actually manifest itself in a stacktrace dump, but instead Julia deadlocks: the training loop stops and `top` shows 0% CPU usage. I have captured `pstack` and `strace` of the process here: https://gist.github.com/tanhevg/b2da7ef694dfdd7f00482d82437e7ead. It appears that the deadlock occurs when Julia tries to handle the SIGSEGV by printing an error, when it tries to allocate memory for the message. To reliably get the segfault, run julia with `--handle-signals=no`.

The deadlock occurs inside `glibc`. My `glibc` version on CentOS 7 is 2.17. What is the minimum recommended version to run Julia?

**Comment by JeffBezanson** [comment]
It looks like the allocation is inside `__dcigettext`. Is there a way we can avoid that?

**Comment by tanhevg** [comment]
This is the smoking gun, I think:

https://github.com/JuliaLang/julia/blob/c6da87ff4bc7a855e217856757ad3413cf6d1f79/src/jl_uv.c#L603-L604

I guess it is not safe to do any `printf` flavor from a sighandler; need to do something more primitive, like just `write` to `stderr`. According to the [man](http://man7.org/linux/man-pages/man7/signal-safety.7.html), `write` is async signal safe, so should be fine.

**Comment by vtjnash** [comment]
In principle, it isn't safe to do anything there, but we attempt to print something useful before dying, and we assume the outer container environment is responsible for managing hard kills and restarts, as there's other reasons that those need to be handled elsewhere, for robustness.

However, glibc itself uses this vprintf code when malloc internally fails, and therefore now even includes reasonable attempts to recover and avoid this deadlock (https://github.com/lattera/glibc/commit/fff94fa2245612191123a8015eac94eb04f001e2)
