### ISSUE TITLE
Make contributing link more prominent on the Julia Docs 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#33181]
I think it would be beneficial to have a better `contributing` representation on the Julia Docs. There's currently a singular reference to it tucked away [here](https://docs.julialang.org/en/v1/manual/faq/#Julia-Releases-1). I would suggest it ave its own section with just a copy of the contributing.md file from Github.

**Comment by logankilpatrick** [comment]
In my opinion, contributing.md should be the first thing under "developer docs". It is weird that this section just jumps into low-level details without giving any context.

**Comment by ViralBShah** [comment]
Actually this is shown very prominently in the README on github, which is where new contributors are likely to start. I am comfortable closing.
