### ISSUE TITLE
Julia v1.2.0 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#33188]
Discourse post: https://discourse.julialang.org/t/julia-v1-2-0-on-windows-server-2012-r2

I cannot start Julia v1.2.0 on Windows Server 2012 R2.

The installation seems successful, but when starting Julia the terminal opens momentarily and then exits immediately.

The problem occurs on multiple servers with similar configuration.
Previous versions of Julia (v1.0.4, v1.1.1) run fine on these servers (Windows Server 2012 R2)
Julia v1.2.0 is installed and working on Windows 10 machines.

Unfortunately there’s no error message, it just seems to exit and return to the windows Command prompt:
```
C:\Users\plowman>"C:\Program Files\Julia-1.2.0\bin\julia.exe"

C:\Users\plowman>
```
whereas Julia v1.1.1 starts properly as expected:
```
C:\Users\plowman>"C:\Program Files\Julia-1.1.1\bin\julia.exe"
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

syda-std6af-02 Julia-1.1.1>
```

Same issue reproduced by another user on Discourse.

**Comment by phlavenk** [comment]
Strange - I cannot confirm this is an issue. It's running fine on my WinServer 2012R2 (all security patches up to this Wednesday).
Installed from official binaries as per-user install into the appdata folder, not a global installation.
![Clipboard 4](https://user-images.githubusercontent.com/12131440/64845739-33968e80-d60b-11e9-801d-93789a8da613.png)

**Comment by rvasil** [comment]
Hi, I had same issue on Windows 10 Pro.
However, I still had global **JULIA_BINDIR** environment variable pointing to version 1.1.
After changing JULIA_BINDIR to point to new Julia version, it works fine.
HTH,
Rastislav

**Comment by GregPlowman** [comment]
Just tried with Julia `v1.3.0-rc2` but same issue. Julia does not start. No error message.
No problems on Windows 10 machines.

Do you think it could be related to code signing?
Anyone have tips about how to further diagnose?

**Comment by rvasil** [comment]
I tried 1.2.0 on 2008 R2 and 2016 and it works fine. No 2012 available here.
Maybe check your startup.jl file or remove everything from c:\Users\%username%\.julia\ directory if you have used other versions previously on that server.

On servers, I don't install Julia directly, but copy installation and packages from my dev machine to custom directories.
Then I start Julia like this:
```
set JULIA_BINDIR=E:\lang\Julia-1.2.0\bin
set JULIA_DEPOT_PATH=E:\lang\julia\packages
set PATH=%PATH%;%JULIA_BINDIR%
%JULIA_BINDIR%\julia.exe %*
```

**Comment by ueliwechsler** [comment]
The same problem appears for `julia v1.3.0-rc2`.

I am not sure if this is related to the problem. But for `julia` `>v1.20` the Path that package manager displays when calling `(v1.2) pkg> st` changes from 
`Status \\serveraddress\...\environments\v1.2\Project.toml`
`Status UNC\serveraddress\...\environments\v1.2\Project.toml`
which causes some problems in my setup.

**Comment by GregPlowman** [comment]
Perhaps its something to do with `libopenblas64_.dll`?

In Julia v1.2.0, replacing `libopenblas64_.dll` with the dll from Julia v1.1.1 allows Julia to start. Things seem normal, but I don't really use BLAS.

Julia v1.3.0-rc4 has the same issue and is "fixed" by replacing `libopenblas64_.dll`.

Is there anything I can do to further diagnose the issue?

**Comment by PallHaraldsson** [comment]
See workaround here:
https://github.com/JuliaLang/julia/issues/34097#issuecomment-567631718


https://github.com/JuliaRegistries/General/tree/master/O/OpenBLAS_jll

**Comment by OndWolf** [comment]
I have the same problem with Julia 1.4.1

**Comment by ueliwechsler** [comment]
> I have the same problem with Julia 1.4.1

Same here and the recommended fix with `libopenblas64_.dll` does not work either.

**Comment by vtjnash** [comment]
> set JULIA_BINDIR

Do not set JULIA_BINDIR, unless the default autodetection is failing for your setup (unusual)

> I have the same problem with Julia 1.4.1

The fix for the openblas issue (https://github.com/JuliaLang/julia/issues/34097) was expected in v1.5
