### ISSUE TITLE
Confusing error message when accidentally repeating type parameters

### ISSUE THREAD

**Issue by tjgreen** [JuliaLang/julia#33199]
Maybe this could be related to the legacy curly-brace array syntax?
```julia
julia> struct Foo
       a :: Vector{String}{String}
       end
ERROR: TypeError: in Type{...} expression, expected UnionAll, got Type{Array{String,1}}
Stacktrace:
 [1] top-level scope at none:0
```
The actual problem is glaringly obvious in this example, but this is distilled from a much more complicated example I encountered in the wild involving bad code generation, where the puzzling error message made me briefly want to rage quit this whole programming thing.

I didn't find any reports that appeared directly related to this issue, though #18096 could be tangentially related?

**Comment by yuyichao** [comment]
FYI, the syntax is actually valid.

```julia
julia> Array{String}{1}
Array{String,1}
```

**Comment by JeffBezanson** [comment]
Thanks for reporting. Do you have a suggestion for a better wording? I could propose some, but would be useful to know what you would have found helpful.

**Comment by vtjnash** [comment]
I can't really think of how to make this clearer. We should have slightly more accurate line info now, though we have existing issues about improving that.
