### ISSUE TITLE
export Base.@kwdef

### ISSUE THREAD

**Issue by tk3369** [JuliaLang/julia#33192]
The `Base.@kwdef` is such a useful feature.  I cannot think of any reason why it should not be exported.  Is there any concern doing that?

**Comment by tk3369** [comment]
Come to think of it, another option is to support that syntax directly in the language without using any macro.  Maybe that could be a 2.0 target?

**Comment by CameronBieganek** [comment]
I agree. This would be a nice feature for 1.6, since that will be the new Long-Term Support version.

**Comment by StefanKarpinski** [comment]
I had really always hoped that we'd get a better solution instead of baking `@kwdef` in as official 😞. At the very least it could have a better name.

**Comment by Roger-luo** [comment]
like supporting the syntax that `@kwdef` provides in `struct`s? I guess all `@kwdef` is about having such a syntax?

**Comment by logankilpatrick** [comment]
@stefan-k any updates on this?

**Comment by cocoa1231** [comment]
I would also love to see this as a stable feature

**Comment by czimm79** [comment]
It's been almost a few years since this issue was opened. Any chance this could still happen? :)

**Comment by JeffBezanson** [comment]
From triage: yes we might as well export this. It's unfortunately too expensive to generate keyword constructors for every struct, and I don't see that changing without major changes to the language. We can however support default values for trailing fields in normal struct definitions, just like optional positional arguments. I suspect waiting for that feature (and wondering whether it is actually worthwhile) was part of what held up `@kwdef`.
