### ISSUE TITLE
Discrepancy between Debian/Ubuntu binary Julia package and official one

### ISSUE THREAD

**Issue by cdluminate** [JuliaLang/julia#33208]
Following https://github.com/JuliaLang/julia/issues/32639 . Julia has some special feature requirments on its dependencies, however many of them are not provided by main distributions. Some of these differences could result in a less usable result. Hence, it's difficult for Julia upstream to recommend something that's not guaranteed to work correctly. This issue is opened for tracking the concrete differences in Debian's Julia package. When this issue is resolved, we could start to update the julia website and properly mention Debian packages.

This works for official packages of the whole Debian family, including Ubuntu, etc.

**Comment by cdluminate** [comment]
* [ ] llvm (bugfix patches)
* [ ] openblas (64-bit-indexing feature, ABI with mangled names)
* [ ] suitesparse (64-bit-indexing, linked against libopenblas64_)
* [ ] dsfmt (64-bit-indexing)
* [ ] gmp (bugfix patches)

A portion of these was already done, but I don't remember the detail. I'll check and update this list later.

**Comment by ViralBShah** [comment]
We also need arpack with ILP64 support with the mangled names. Also, it should be prohibited to link against MKL in such builds. 

One short term fix could be to ship with just LP64 BLAS (so the integers are not 64-bit), without mangling names, and that should work - since it won't need patches for all the other packages.
So that work can then progress at a slower pace.

**Comment by ViralBShah** [comment]
I don't think we make any changes to dsfmt. It should be good to use as is.

**Comment by ViralBShah** [comment]
One takeaway here is that it would greatly help distribution packagers, if we had a clear list of all the patches in a release documented. Maybe as simple as simply listing all the `.patch` files.

**Comment by ViralBShah** [comment]
@cdluminate Any thoughts here - on perhaps going with 32-bit BLAS (LP64) and having a simpler route to resolving this? That would allow the focus to be on llvm and the ILP64 BLAS can come later.

**Comment by cdluminate** [comment]
Yes. Indeed we can keep going with the LP64 BLAS for a while. The temporary downside would be the tricky installation process of julia packages such as Arpack.jl

**Comment by cdluminate** [comment]
There are 3 patches related to GMP:

* gmp_alloc_overflow_func.patch is still not merged upstream, hence not applied in the Debian package
* gmp-config-ldflags.patch looks not quite necessary
* gmp-exception.patch Already applied: https://salsa.debian.org/science-team/gmp/blob/master/debian/patches/gmp-exception-sigfpe.patch

**Comment by cdluminate** [comment]
2 patches for DSFMT, which change the array index type from int to the correct ptrdiff_t (It's a pity that fortran didn't have this type -- and the initial BLAS used integer type).
* [x] dSFMT.{c,h}.patch already applied: https://salsa.debian.org/julia-team/dsfmt/blob/master/debian/patches/array-size.patch

**Comment by cdluminate** [comment]
There are significantly shorter patch lists for LLVM7 and LLVM8. Should I patch Debian's LLVM7 or directly jump to LLVM8?

**Comment by ViralBShah** [comment]
@Keno @vchuravy Can you suggest about LLVM?

**Comment by Keno** [comment]
We are in the process of upgrading llvm. The patch list will likely grow before the final release, but as of now the assumption is that Julia 1.4 will use llvm 8 (or 9)

**Comment by cdluminate** [comment]
Updates: I've bundled openblas and suitesparse source tarballs in Debian's julia package. `INTERFACE64=1` for OpenBLAS and `-DSUN64` for SuiteSparse have been enabled already.
https://tracker.debian.org/pkg/julia

Now the only remaining issues are the unmerged gmp patch and Debian's LLVM. I'll start to patch them when 1.3.0 is released.

**Comment by ViralBShah** [comment]
Let's reopen this or file a new one for distro support.
