### ISSUE TITLE
pathof(::Module) doesn't show the path where the module actually got imported from

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33210]
```
julia> using Example

julia> pathof(Example)
"/Users/kristoffer/.julia/packages/Example/aqsx3/src/Example.jl"

(v1.2) pkg> add Example@0.5.1
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
  [7876af07] ↓ Example v0.5.3 ⇒ v0.5.1
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [7876af07] ↓ Example v0.5.3 ⇒ v0.5.1

julia> pathof(Example)
"/Users/kristoffer/.julia/packages/Example/kH44X/src/Example.jl"
```

I would have thought `pathof` should point to the path as it was when the module was imported. Not the file that would have been used if the module was not imported but got imported right now.

**Comment by vtjnash** [comment]
Are you opening this as a self-assignment, or hoping someone else will pick it up? I guess we need to keep around a `Dict{Module => String}` giving the location `require` decided to get it from?

I wonder if we should also deprecate this in favor of just having `rootof(Example) == "/Users/kristoffer/.julia/packages/Example/aqsx3"`?  (although needs the same implementation fix either way)

**Comment by KristofferC** [comment]
> Are you opening this as a self-assignment, or hoping someone else will pick it up?

Both :)

> I guess we need to keep around a Dict{Module => String} giving the location require decided to get it from?

Yeah, that seems simple enough
