### ISSUE TITLE
Type parameters in inner scopes

### ISSUE THREAD

**Issue by thautwarm** [JuliaLang/julia#33240]
Following code fails(produce the following error) for 1.0 and 1.1, and works since 1.2.

```
julia> f(x::T) where T = begin
           T
           g(z::Type{<:T}) = (x, z)
       end
ERROR: UndefVarError: T not defined
```

**Comment by KristofferC** [comment]
If someone can find the commit that fixes it and backporting it doesn't cause other problems then yes it can get backported.

**Comment by brenhinkeller** [comment]
Still working properly as of 1.8.3; looks like enough time has elapsed that backporting is probably no longer relevant.
