### ISSUE TITLE
Accessing the "parent" String from SubString

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/julia#33241]
Is there a way to access the "parent" `[Abstract]String` from a given `SubString`?
If not, should there be a way to do this?

This is available by accessing the `string` filed directly, but in general, but I don't usually think of the fields of a type as public API. Is directly using `s.string` considered public API?

If we were to add this, we'd need a name (obviously `string` is not available). One option would be to borrow the `parent` name from arrays, and define `parent(s::SubString) = s.string`?

(This came up via noticing that given a `RegexMatch`, you have the `regex` and the `match` substring, but no public API for the original String. Ironically, I think `RegexMatch` is one of the few places where fields are considered public API.)

**Comment by KristofferC** [comment]
> Is directly using s.string considered public API?

No.

What is the use-case? A `SubString` is just an `AbstractString`, when does the fact that it is backed by a normal string matter?

**Comment by nickrobinson251** [comment]
I think that the `m::RegexMatch` case is kind of interesting. This object contains the original string, the regex, and the (first) substring that in the original string that matches the regex.

There is a public API for accessing the second two (`m.regex`, `m.match`) but not the first. Well,
`m.match` is public since it is documented [in the manual](https://docs.julialang.org/en/v1/manual/strings/#Regular-Expressions-1), but maybe the field `m.regex` is not considered public? Anyway, this is the context that prompted the thought; getting a SubString from a regex is a case where it may be interesting to recover the original String (which is info the `SubString` contains).

**Comment by KristofferC** [comment]
If it is just about getting the full string out from a `RegexMatch` then adding an API for that seems like a more straight forward way. Without any documentation it is unclear what the parent string is for the substring. It might be some internal thing as well.

**Comment by fredrikekre** [comment]
Don't you typicall already have the string you matched on? E.g. I would think this is a typical code snippet:
```
str = ...
m = match(regex, str)
```
so why do you need to extract the string from `m`?

**Comment by KristofferC** [comment]
If you want the original string from the regex object then adding an API to get that seems ok. If only the substring -> string function is added there needs to be some documentation about what the parent string actually represents. It is not clear that for the `RegexMatch` case that it is the original string.

**Comment by laborg** [comment]
`parent(::SubString)` has been implement in https://github.com/JuliaLang/julia/pull/49511
