### ISSUE TITLE
Inconsistency concerning size(Array)

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaLang/julia#33265]
Hi !  I could not find the explanation of why `size([1;1;1])` returns the wrong answer since julia 0.4 -> 1.2.0 while okay for a sparse matrix ? Look:

```
julia> size([1;1;1]) # Buggy !! Expected to have (3,1)
(3,)

julia> (a,b) = size([1;1;1]) # Nooo please set 1 to b!
ERROR: BoundsError: attempt to access (3,)
  at index [2]
 in indexed_next at tuple.jl:21

julia> size([1 1 1]) # good answer !
(1,3)

julia> size(sparse([1;1;1])) # good answer ! Why different answer from dense array?
(3,1)

julia> size(sparse([1 1 1])) # good answer !
(1,3)

julia> size([1;1;1],1) # good answer !
3

julia> size([1;1;1],2) # good answer ! Finally ... !?
1

julia> size([1;1;1],3) # ... maybe not finally ? Should not throw an OOB error?
1

julia> size([1 1 1],1) # idem for size(sparse([1 1 1]),1)
1

julia> size([1 1 1],2) # idem for size(sparse([1 1 1]),2)
3

julia> size([1 1 1],3) # idem for size(sparse([1 1 1]),3)
1
```

Sad to have to write: `a = size(M, 1); b = size(M, 2)` Julia spirit is to allow writing minimal code, right?

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by Lecrapouille** [comment]
Ok but so just why in this case `size([1;1;1]) != size(sparse([1 1 1]))`. This is definitvely not consistent!

**Comment by fredrikekre** [comment]
> why in this case size([1;1;1]) != size(sparse([1 1 1]))

Why should they be the same? The first is a vector and the second a matrix.
