### ISSUE TITLE
Float32 `print` has too few digits

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#33262]
```
julia> print(Float32(0.5325178404507653))
0.532518
```
Used to give:
```
julia> print(Float32(0.5325178404507653))
0.53251785
```

**Comment by quinnj** [comment]
Is there anybody who could spell out exactly what behavior we'd like for printing between the various combinations of:

* Float16, Float32, Float64
* `:compact` or not
* `print` vs `show` vs `string`

Note the previous behavior is mostly contained [here](https://github.com/JuliaLang/julia/pull/32799/files#diff-716367a1f8b3eb60837a5dce263f76a5). In porting to ryu, I tried to mostly keep the same options, but things don't exactly map one-to-one and there were issues w/ spread out definitions w/ various types that all made it pretty confusing.

**Comment by JeffBezanson** [comment]
`string` is just a string of what `print` would print, so not a separate case.

When `compact` is false there should be enough digits to exactly reproduce the original value for all types and forms of printing.
