### ISSUE TITLE
@cfunction macro need forward declaration to find a function in same module

### ISSUE THREAD

**Issue by pemryan** [JuliaLang/julia#33268]
I am a user of v0.6 in the process of transferring to v1.2 and encountered this problem, where simply add  a '@' before 'cfunction ' doesn't work. I am not sure whether this is an intended change or a bug.

It can be workarounded be adding forward declarations for all functions that are used in the '@cfunction' macro.

Ref: https://discourse.julialang.org/t/cfunction-cannot-find-function-defined-in-the-same-module/28658/4

**Comment by pemryan** [comment]
probably same problem:  @cfunction cannot find argument when used within a function.
test1.jl:
```
function TestCallBackFunc(f::Ptr{Cvoid}, x, y)
    return ccall(f, Cint, (Cint, Cint), x, y)
end

function g(f::Function)
    return TestCallBackFunc(@cfunction(f, Cint, (Cint, Cint)), 1, 2)
end

function f(a::Cint, b::Cint)::Cint
    return (a > b) ? -1 : 1
end
```

when included, it will report that f is not defined:
```
julia> include("test1.jl")
ERROR: LoadError: UndefVarError: f not defined
```

This code snippet will work when a forward declaration is added:

test2.jl:
```
function TestCallBackFunc(f::Ptr{Cvoid}, x, y)
    return ccall(f, Cint, (Cint, Cint), x, y)
end

function f end

function g(f::Function)
    return TestCallBackFunc(@cfunction(f, Cint, (Cint, Cint)), 1, 2)
end

function f(a::Cint, b::Cint)::Cint
    return (a > b) ? -1 : 1
end
```
this works well.
```
julia> include("test2.jl")
f (generic function with 1 method)

julia> g(f)
1
```

another work around is to add  a '$' before 'f' , then use unsafe_convert.
test3.jl
```
function TestCallBackFunc(f::Ptr{Cvoid}, x, y)
    return ccall(f, Cint, (Cint, Cint), x, y)
end

function g(f::Function)
    return TestCallBackFunc(Base.unsafe_convert(Ptr{Cvoid},@cfunction($f, Cint, (Cint, Cint))), 1, 2)
end

function f(a::Cint, b::Cint)::Cint
    return (a > b) ? -1 : 1
end

```
this also works.
```
julia> include("test1.jl")
f (generic function with 1 method)

julia> g(f)
1
```

**Comment by vtjnash** [comment]
Yes, unlike before, the `@cfunction` will protect the function argument from garbage collection, so it needs the forward declaration to create that object to preserve.

> workaround .. use unsafe_convert

You don't seem to understand the meaning of the word "unsafe". These (class of) methods are invalid to `return` from a function.

**Comment by pemryan** [comment]
Thank you for you clarification!
May I ask another question about where to add the forward declaration?

I tried to make the declaration in function g() but it doesn't work:

```
function TestCallBackFunc(f::Ptr{Cvoid}, x, y)
    return ccall(f, Cint, (Cint, Cint), x, y)
end

function g(f::Function)
    function f end
    return TestCallBackFunc(@cfunction(f, Cint, (Cint, Cint)), 1, 2)
end
```
this code snippet cannot be included:
`ERROR: LoadError: syntax: cannot add method to function argument f`

If I made a forward declaration of function f() in the global scope, then I can only call it in function g() under the name of f() as in test2.jl above.  If I understand correctly, when function g(f) is called, the name of its argument should be able to change to another name, g(h), g(l) etc. 

```
function TestCallBackFunc(f::Ptr{Cvoid}, x, y)
    return ccall(f, Cint, (Cint, Cint), x, y)
end

function f end

function g(f::Function)
    return TestCallBackFunc(@cfunction(f, Cint, (Cint, Cint)), 1, 2)
end

function h(a::Cint, b::Cint)::Cint
    return (a > b) ? -1 : 1
end
```
this code snippet could be inclued without error. When called with another augment name, is still looking under the name of `f':
```
julia> g(h)
ERROR: MethodError: no method matching f(::Int32, ::Int32)
```

I have no idea how to define a function that take a julia function as argument and use it in @cfunction,  except that method in test3.jl. Could you please give me some more hint here? Thank you!
