### ISSUE TITLE
Inconsistency with unary `+` for sparse arrays

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#33271]
For dense arrays, the unary `+` operator creates a copy, for sparse arrays it doesn’t:

```julia
julia> using SparseArrays

julia> A = rand(5,5);

julia> B = sprand(5,5,0.5);

julia> +A === A
false

julia> +B === B
true
```
I think this should be made consistent. I prefer the copying behavior, since it matches the behavior of the unary `-` (which obviously can’t return the same object).

**Comment by fredrikekre** [comment]
If we want the copying behavior, then this fallback looks wrong: https://github.com/JuliaLang/julia/blob/9096963894e3f1187b9cb4e520206dcd77be9007/base/abstractarraymath.jl#L97 and is what causes this for sparse arrays.

**Comment by KristofferC** [comment]
Introduced 9 years ago:

https://github.com/JuliaLang/julia/commit/92c4a9336c1211476f2e0fb97708ee3d45a32751#diff-d5617aed44f487eb3267f5951c541314R102-R103

:D

**Comment by StefanKarpinski** [comment]
I'm not entirely sure if we do want the copying behavior here. It's been "unfixed" for a very long time without issues.

**Comment by sostock** [comment]
I’m fine with the non-copying behavior it as well, I just think it should be consistent. I can also make a PR that introduces the non-copying behavior for `Array`s.

**Comment by sostock** [comment]
Another aspect of the current behavior for `Array`s is that `+(::Array{Bool})` returns an `Array{Int}`. Is this desired? It doesn’t happen for other types of `AbstractArray`s. I think this should also be consistent. Of course it would be consistent if we decide on the non-copying behavior.

**Comment by mbauman** [comment]
These methods are linear-algebra-like.  They treat arrays and matrices as algebraic objects in and of themselves.  Thus, I don't find the no-copy behavior objectionable.  If you want to treat them as containers, you can use broadcast.

Perhaps we should indeed special case the 1-arg `Array` method (or generalize it to all `AbstractArray`s):

https://github.com/JuliaLang/julia/blob/6d356db4f04d3a7bad676b3276986e99f0be0568/base/arraymath.jl#L43-L48
