### ISSUE TITLE
Julia REPL is calculating wrongly

### ISSUE THREAD

**Issue by rolfdstoll** [JuliaLang/julia#33294]
For the following calculation Julia REPL gives me the correct result:
-80538738812075974^3 + 80435758145817515^3 + 12602123297335631^3
The result is 42.

But for the following calculation Julia REPL gives a wrong result:
-80538738812075974^3
Julia REPL gives me 8245275391534299688. This is definitely wrong.
The correct result must be -522413599036979150280966144853653247149764362110424

I am working with Julia Version 1.2.0 on Windows 10

**Comment by rfourquet** [comment]
Julia gives the correct answer, in `-80538738812075974^3`, the operands are `Int64` which could be seen as integers modulo `2^64`. For example `mod(-big(80538738812075974)^3, big(2)^64) == 8245275391534299688`. This topic is heavily covered on the discourse forum, for example in https://discourse.julialang.org/t/julia-messes-up-integer-exponents/20773.

**Comment by rolfdstoll** [comment]
Sorry, how is it possible that a negative number in the 3rd power gives a positive result?

**Comment by KristofferC** [comment]
You got it explained to you. Please ask further questions on https://discourse.julialang.org/
