### ISSUE TITLE
Julia 1.3 RC2 installation error on Win64 because of Avast Antivirus

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#33292]
Julia 1.3 RC-2 binary installation error on Windows 10 64bit:
I get this error which happens during the extraction:
![image](https://user-images.githubusercontent.com/16418197/65009332-dda73c80-d8d1-11e9-8087-6c6227f69192.png)

**Comment by aminya** [comment]
OK. Turns out it is Avast Free Antivirus! By disabling the Antivirus this is solved. Is there any way to prevent this?

**Comment by aminya** [comment]
Similar issues: 
https://github.com/JuliaLang/julia/issues/28840
https://github.com/CelestialCartographers/Ahorn/issues/13

**Comment by ViralBShah** [comment]
Yes, closing this as a duplicate.

**Comment by ViralBShah** [comment]
It is possible this is further alleviated with https://github.com/JuliaLang/julia/issues/25730

**Comment by aminya** [comment]
That's great. In that case, we don't need to contact the Antivisur vendors like in https://github.com/JuliaLang/julia/issues/28840#issuecomment-539102030 anymore
