### ISSUE TITLE
Potentially ambiguous rand behaviour

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaLang/julia#33309]
I ran into unexpected behaviour today calling the rand function. I expected `rand((2,))` to interpret the tuple as dimensions, whereas it actually interpreted it as the set of values from which to be drawing from randomly.

In my opinion, a tuple does not (and should not) represent a 'set of values', but rather be a compound data type where each element has an explicit meaning (such as with dims, where each element of the tuple represents the length of specific dimension), and hence, should not be a valid type for S.

Should this be changed?

**Comment by rfourquet** [comment]
It was interpreted as dimensions in the past, and was changed with the new meaning (partily for performance reasons) in Julia 1.1 I think, see #25278.

**Comment by aahaselgrove** [comment]
Fair enough, though possibly this should be clarified in the documentation to make it obvious, as it was a somewhat annoying bug to find. All I can see currently is "Support for S as a tuple requires at least Julia 1.1."
