### ISSUE TITLE
Windows: temp file names too short

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#33321]
From https://build.julialang.org/#/builders/32/builds/4736/steps/2/logs/stdio for example:
```
Error in testset Test:
Error During Test at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win64\build\share\julia\stdlib\v1.4\Test\test\runtests.jl:863
  Got exception outside of a @test
  SystemError: opening file "C:\\cygwin\\tmp\\jl_6E.tmp": No such file or directory
```
With only two characters in the random temp file name, there are going to be a lot of collisions.

**Comment by vtjnash** [comment]
There's actually 4 characters (65k values), but seems like we should take Jeff's advice? from https://github.com/JuliaLang/julia/issues/9053#issuecomment-321617366

**Comment by StefanKarpinski** [comment]
How are there 4 characters? `jl_6E.tmp` has two variable characters as most.

**Comment by JeffBezanson** [comment]
I think this is fixed.
