### ISSUE TITLE
Expose a symbolic LU factorization for sparse matrices

### ISSUE THREAD

**Issue by lkapelevich** [JuliaLang/julia#33323]
It would be useful to have an interface for symbolic LU factorizations with UMFPACK, similar to the CHOLMOD factorizations

**Comment by j-fu** [comment]
Indeed, as this can speed up computations for problems  which repeatedly are solved on the same grid structure.

However, in connection to this, I see at least a couple more options Julia could provide:
- Provide a standard backend interface to sparse matrix solvers allowing to use SuiteSparse as default, but to choose others as well (Pardiso, SuperLU, etc.) which would include an interface to  the symbolic factorization step.  Or, possibly more Julianic one could imagine an AbstractSparseSolver interface. IMHO this seems to be a bit more than just adding a bit of functionality.
- Efficient interface for structure build up. For this purpose I created ExtendableSparse.jl . In C++ I also have a thread parallel variant for this. Behind such an interface one could figure out if the structure changed or only the numerical values and act accordingly.
- Essentially, solvers and preconditioners could be handeled in similar ways.
Would love to contribute, but currently tough in time...

**Comment by lkapelevich** [comment]
>     * Provide a standard backend interface to sparse matrix solvers allowing to use SuiteSparse as default, but to choose others as well (Pardiso, SuperLU, etc.)

That does sound like a lot of work but would be super useful.
