### ISSUE TITLE
isempty() and length() for sparse matrices is not compliant with the documentation

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaLang/julia#33360]
Hi!

The `isempty` function for sparse matrices seems not doing what the documentation says: `Determine whether a collection is empty (has no elements).` It uses the function:
```
isempty(a::AbstractArray) = (length(a) == 0)
```
in `abstractarray.jl` where length means `the number of elements in the array, defaults to the product of its dimensions is zero`  which is not suitable for sparses.

```
julia> A = sparse([1, 2], [1, 2], [0, 0])
2×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  0
  [2, 2]  =  0

julia> length(A)
4

julia> isempty(A)
false

julia> isempty(spzeros(Int64, 2,2))
false

julia> length(spzeros(Int64, 2,2))
4
```

Two options:

1. Change the doc to: isempty(collection) = Determine whether a collection has no dimension.
2.  Change the code to `isempty(s::SparseMatrixCSC) = (length(s.nzval) == 0)` and the documentation to: has no non-zero elements.

I would recommend the option 2. PS: same idea for sparse vectors.

```
julia> isempty(s::SparseMatrixCSC) = (length(s.nzval) == 0)

julia> isempty(A)
false

julia> isempty(spzeros(Int64, 2,2))
true

julia> isempty(sparse([]))
true

julia> Base.:length(t::SparseMatrixCSC) = length(t.nzval)

julia> length(A)
2

julia> length(spzeros(Int64, 2,2))
0
```

This would follow the same principe than Dict for example
```
julia> dict = Dict("a" => 1, "b" => 2, "c" => 3)
Dict{String,Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

julia> isempty(dict)
false

julia> length(dict)
3

julia> dict = Dict()
Dict{Any,Any} with 0 entries

julia> length(dict)
0

julia> isempty(dict)
true
```

**Comment by KristofferC** [comment]
There are multiple problems with the proposal here. It would mean that `isempty(s) != isempty(Array(s))`, changing the definition of `isempty` is breaking, it would make a distinction between stored zeros or not in a generic function. The comparison with `Dict` is also faulty since `spzeros(2,2)` does contain 4 elements (they can even be indexed).

Use `count(!iszero, s)` if you want to count the number of non-zeros.

**Comment by Lecrapouille** [comment]
1. spzeros(2,2) does not contain 4 elements else that would make non-sense because the aim of sparse is to only store non zero() elements in the aim to reduce the memory consumption!
2. Dense matrices are different because they have a fixed number of elements. So this definitively makes sense that `isempty(s) != isempty(Array(s))`.
3. So please update the documentation of isempty() for sparse because this assumption `Determine whether a collection is empty (has no elements)` is false. 
```
julia> spzeros(2,2)
2×2 SparseMatrixCSC{Float64,Int64} with 0 stored entries
```
For me 0 entries == 0 elements

**Comment by KristofferC** [comment]
You are confusing the implementation details of a sparse array with what mathematical object it refers to. A sparse array is just a different way of storing a matrix (that happens to be efficient what the number of zeros are dominating).

Please continue further discussion at https://discourse.julialang.org/.
