### ISSUE TITLE
print, sprint enhancement for context, mime

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#33362]
**CLOSED SINCE IT WAS TOO BADLY EXPLAINED**

`sprint` should be able to

- handle context as a pair, or a vector of pair (may be an union). may be this could be a kwargs splat
- handle a mime keyword argument to pipeline to `show(io, mime, x)` and not only `show(io, x)`              

Possible patch :

```julia
Base.show(io::IO, x; mime::MIME{T}=mime) where T = show(io, mime, x)

function Base.sprint(f::Function, args...; context=nothing, mime=nothing, sizehint::Integer=0)
    iobuf = IOBuffer(sizehint=sizehint)
    local ioctx
    if context !== nothing
        if context isa (Pair{Symbol,T} where T) # Pair is not covariant
            ioctx = IOContext(iobuf, context) 
        elseif context isa (Vector{Pair{Symbol,T}} where T)
            ioctx = IOContext(iobuf, context...)
        else
            throw(ArgumentError(context))
        end
    else
        ioctx = iobuf
    end

    if mime == nothing
        f(ioctx, args...)
    else
        f(ioctx, args..., mime=mime)
    end
    String(resize!(iobuf.data, iobuf.size))
end
```

Derived from stdlib v1.2

```julia
function sprint(f::Function, args...; context=nothing, sizehint::Integer=0)
    s = IOBuffer(sizehint=sizehint)
    if context !== nothing
        f(IOContext(s, context), args...)
    else
        f(s, args...)
    end
    String(resize!(s.data, s.size))
end
```

https://github.com/JuliaLang/julia/blob/v1.2.0/base/strings/io.jl#L79-L110

**Comment by o314** [comment]
An example

```julia
struct RgbColor; r::Int8; g::Int8; b::Int8 end

Base.show(io::IO,c::RgbColor) = print(io, "rgb($(c.r), $(c.g), $(c.b))")        # todo no space if compact
@test sprint(show,RgbColor(16,32,64)) == "rgb(16, 32, 64)"

Base.show(io::IO,c::RgbColor) = begin
    compact = get(io, :compact, false)
    pattern = compact ? 
        "rgb($(c.r),$(c.g),$(c.b))" :   # no space between fields
        "rgb($(c.r), $(c.g), $(c.b))"
    print(io, pattern)
end
@test sprint(show,RgbColor(16,32,64), context=:compact=>true) == "rgb(16,32,64)"
@test sprint(show,RgbColor(16,32,64), context=IOContext(stdout,:compact=>true)) == "rgb(16,32,64)"


Base.show(io::IO, ::MIME"text/plain", c::RgbColor) = print(io,c)
Base.show(io::IO, ::MIME"text/csv", c::RgbColor) = print(io,"$(c.r),$(c.g),$(c.b)")
@test sprint(show,RgbColor(16,32,64), context=:compact=>true) == "rgb(16,32,64)"
@test sprint(show,RgbColor(16,32,64), mime=MIME("text/plain")) == "rgb(16, 32, 64)"
@test sprint(show,RgbColor(16,32,64), mime=MIME("text/csv")) == "16,32,64"

```

**Comment by o314** [comment]
More generally mime should be a keyword argument for show, print, sprint ...

**Comment by stevengj** [comment]
`print` is explicitly for text output; I don't think it makes sense for it to accept a general MIME type.

For `sprint`, you can already do `sprint(show, mimetype, x)`, as well as `repr(mime, x)`, so I'm not sure why we need anything more?

**Comment by o314** [comment]
*For sprint*

Given

```julia
using Test

struct RgbColor; r::Int8; g::Int8; b::Int8 end
Base.show(io::IO,c::RgbColor) = print(io, "rgb($(c.r), $(c.g), $(c.b))")
Base.show(io::IO, ::MIME"text/plain", c::RgbColor) = print(io,c)
Base.show(io::IO, ::MIME"text/csv", c::RgbColor) = print(io,"$(c.r),$(c.g),$(c.b)")
```

We effectively have

```julia
@test sprint(show, MIME("text/csv"), RgbColor(1,2,3)) == "1,2,3"
```

Since

```julia
@test applicable(sprint, show, MIME("text/csv"), RgbColor(1,2,3))

m1 = methods(sprint, Tuple{U,MIME,V} where {U,V}) |> first
@test m1.sig == Tuple{typeof(sprint),Function,Vararg{Any,N} where N}
```

However neither the signature, neitheir the docstring of m1 [in Base at strings/io.jl:103](https://github.com/JuliaLang/julia/blob/v1.2.0/base/strings/io.jl#L103)
mentions the mime handling capacity. So it did not appear in help system, or when calling methods.

May be it could be useful to provide an example in its docstring.

--
*For print*

`"text/*"` is a very large subset of registered mime extension. so print is pertinent.
we work with textual dsl in the lisp spirit and resorting to mime is a natural continuation,
that sometime seems a bit broken with io today.

- It seems not natural to distinguish print vs sprint too.
- No sense to go down to binary w write
- Advantage of display is not clear.

Last
```julia
@test sprint(show, MIME("text/csv"), RgbColor(1,2,3)) |> s -> all(isprint, s)
@test sprint(show, MIME("text/plain"), RgbColor(1,2,3)) |> s -> all(isprint, s)
# will be ok w html, markdown too
```

--
*Finally*

We miss the sprint w mime already present but not explicited. Half of the request can be already done. This request is less meaningful today.

However the any varargs approach is regularly problematic when generalized too much (multidispatch piracy) and context passing is not always complete or consistent with io. 
Keyword argument may still have some advantage in the long run, with some extra rework :)

**Comment by o314** [comment]
Feel free to close this issue or postpone it to a later general io overhaul.

Main points

- text io is many form. print w mime"text/*" is valid for each ones.
- everything is positional today.
- everything but print can get a positional mime.
- print can not handle it since it goes varargs before / do repeat show/1.
- string(print) != sprint is not very convincing

What about nominal someday

**Comment by o314** [comment]
Sorry it is very hard to read, i will clean up and repost later if it is ok.
