### ISSUE TITLE
Don't assume `Int` in `_sametype` in broadcasting

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#33391]
These lines are breaking InfiniteArrays.jl in Julia v1.0.5 (but not other v1.x or v1.0.x):

https://github.com/JuliaLang/julia/blob/3af96bcefcb0aec559d4652fd75e1bc3fcfe99da/base/broadcast.jl#L448

It seems like a bad idea to assume `Int`, as they may be `BigInt`. I can work around it but this should have been considered a breaking change.

**Comment by KristofferC** [comment]
Wasn't this put into 1.0.3?
 https://github.com/JuliaLang/julia/pull/30074

**Comment by dlfivefifty** [comment]
Ah, I only checked 1.0.2 and 1.0.5

**Comment by dlfivefifty** [comment]
I realised the issue is with the call to `UnitRange`, not the use of `Int`. I need to hack around due to the nature of InfiniteArrays.jl, so from my perspective this issue can be closed.

However, I think the hard coding of `Int` is very suspicious, and it seems that it should be
```julia
_sametype(a::OneTo{T}, b::OneTo{V}) where {T,V} = OneTo{promote_type(T,V)}(a) 
```

**Comment by timholy** [comment]
We default to `Int` for all scalar indexing operations:
```julia
julia> to_indices(rand(2), (0x01,))
(1,)
```

**Comment by dlfivefifty** [comment]
OK, fair enough. In any case that code has been removed and I've fixed the issue in InfiniteArrays.jl. So I'll close this.
