### ISSUE TITLE
Inserting global list to a function, change the global list

### ISSUE THREAD

**Issue by tamuzd** [JuliaLang/julia#33411]
I have an information on a global list variables. I want to use this information and make some manipulation with it. But I don't want to change this global list. Right now any manipulation I make change this global list. I have already a long code code with this global list.
The following example represents my bug difficulty:

function Dont_Change_Global_List(L)
    Manipulating_List = L
    deleteat!(Manipulating_List,2)
    return Manipulating_List
end

global s = [1,2,3,4,5]

println("function result: ",Dont_Change_Global_List(s))
println("global list", s)

I get:

function result: [1, 3, 4, 5]
global list[1, 3, 4, 5]

Is there anything I can do without changing the global list s but still make a manipulations?

**Comment by vchuravy** [comment]
Please ask questions on https://discourse.julialang.org
