### ISSUE TITLE
Backslash with SparseMatrixCSC creates full factorisation 

### ISSUE THREAD

**Issue by vincentcp** [JuliaLang/julia#33423]
Backslash creates a full factorisation  
```
julia> using SparseArrays
julia> A = sprand(10,10,.3);
julia> b = rand(10);
julia> A\b;
```
https://github.com/JuliaLang/julia/blob/f696e17edae2cb2d4d096be4a4deec8ee6489866/stdlib/SparseArrays/src/linalg.jl#L1456

Isn't it possible to apply the Householder reflection directly to `b` and to discard them instead of saving them in a factorisation? 

As is described in section 3.3 of `Multifrontal multithreaded rank-revealing sparse QR factorization` of `TIMOTHY A. DAVIS`

**Comment by andreasnoack** [comment]
It might be possible to call a function in SQPR that doesn't store the factorization but the current approach for all `\` definitions is to factorize and solve. I think it makes the code simpler. Would you expect it to be much faster to discard the reflectors?

**Comment by vincentcp** [comment]
Since I was not sure I created following test: 

For the application I have in mind I create sparse matrix systems of increasing size. I did a memory check using following pseudo-code
```
julia> A = createsparsematrix(some_matrix_size);
julia> N = nnz(A);
julia> QRfact = qr(A);
julia> fieldnames(QRfact)
(:factors, :τ, :R, :cpiv, :rpivinv)
julia> Q, t, R, cpiv, rpivinv = map(x->Base.summarysize(getfield(QRfact,x)), fieldnames(typeof(QRfact)));
```

which results in following plot for different matrix sizes
[memorycheck.pdf](https://github.com/JuliaLang/julia/files/3685769/memorycheck.pdf)

All components of the qr factorisation have a memory of `O(N)`, but `Q` contains most of the memory. However, `rpivinv` grows much faster than `O(N)`. This, I don't understand.

**Comment by vincentcp** [comment]
I know that the Matlab routine to solve a sparse system using SPQR is `spqr_solve` but I don't know if this routine is directly available in a c-call.

**Comment by vincentcp** [comment]
For completeness I added a test where I inserted the line 
```
julia> A = sprand(size(A)...,nnz(A)/prod(size(A)))
```
to check how the structure of my matrices influences the test. 

Using random matrices with the same sparsity rate and size the figure becomes 

[memorycheck.pdf](https://github.com/JuliaLang/julia/files/3685946/memorycheck.pdf)

**Comment by vincentcp** [comment]
I found the existence of this template 
```
// X = A\dense(B)
template <typename Entry> cholmod_dense *SuiteSparseQR
(
    int ordering,           // all, except 3:given treated as 0:fixed
    double tol,
    cholmod_sparse *A,      // m-by-n sparse matrix
    cholmod_dense  *B,      // m-by-nrhs
    cholmod_common *cc      // workspace and parameters
) ;
``` 
in 
  https://github.com/PetterS/SuiteSparse/blob/27e5a8516464a6ac40bd3fa0e5b46e51b11f4765/SPQR/Include/SuiteSparseQR.hpp#L341 
which does a solve without explicitly storing the factorisation. 

Can I call this using the functionality in `SparseArrays.jl`

**Comment by vincentcp** [comment]
I can :-) 
``` julia
using SuiteSparse.CHOLMOD, SparseArrays
using SuiteSparse.SPQR: _default_tol, ORDERING_DEFAULT


function spqr_solve(A::SparseMatrixCSC{Tv}, b::Vector{Tv}; tol = _default_tol(A)) where {Tv <: CHOLMOD.VTypes}
    X = Ref{Ptr{CHOLMOD.C_Dense{Tv}}}()
    AA = Sparse(A,0)
    B = Dense(b)

    r = _spqr_solve!(ORDERING_DEFAULT, tol, 0, 2, AA,
        C_NULL, B, C_NULL, X,
        C_NULL, C_NULL, C_NULL, C_NULL, C_NULL)
    Vector(Dense(X[]))
end

function _spqr_solve!(ordering::Integer, tol::Real, econ::Integer, getCTX::Integer,
        A::Sparse{Tv},
        Bsparse::Union{Sparse{Tv}                      , Ptr{Cvoid}} = C_NULL,
        Bdense::Union{Dense{Tv}                        , Ptr{Cvoid}} = C_NULL,
        Zsparse::Union{Ref{Ptr{CHOLMOD.C_Sparse{Tv}}}  , Ptr{Cvoid}} = C_NULL,
        Zdense::Union{Ref{Ptr{CHOLMOD.C_Dense{Tv}}}    , Ptr{Cvoid}} = C_NULL,
        R::Union{Ref{Ptr{CHOLMOD.C_Sparse{Tv}}}        , Ptr{Cvoid}} = C_NULL,
        E::Union{Ref{Ptr{CHOLMOD.SuiteSparse_long}}    , Ptr{Cvoid}} = C_NULL,
        H::Union{Ref{Ptr{CHOLMOD.C_Sparse{Tv}}}        , Ptr{Cvoid}} = C_NULL,
        HPinv::Union{Ref{Ptr{CHOLMOD.SuiteSparse_long}}, Ptr{Cvoid}} = C_NULL,
        HTau::Union{Ref{Ptr{CHOLMOD.C_Dense{Tv}}}      , Ptr{Cvoid}} = C_NULL) where {Tv<:CHOLMOD.VTypes}

    AA   = unsafe_load(pointer(A))
    m, n = AA.nrow, AA.ncol
    rnk  = ccall((:SuiteSparseQR_C, :libspqr), CHOLMOD.SuiteSparse_long,
        (Cint, Cdouble, CHOLMOD.SuiteSparse_long, Cint,
         Ptr{CHOLMOD.C_Sparse{Tv}}, Ptr{CHOLMOD.C_Sparse{Tv}}, Ptr{CHOLMOD.C_Dense{Tv}},
         Ptr{Ptr{CHOLMOD.C_Sparse{Tv}}}, Ptr{Ptr{CHOLMOD.C_Dense{Tv}}}, Ptr{Ptr{CHOLMOD.C_Sparse{Tv}}},
         Ptr{Ptr{CHOLMOD.SuiteSparse_long}}, Ptr{Ptr{CHOLMOD.C_Sparse{Tv}}}, Ptr{Ptr{CHOLMOD.SuiteSparse_long}},
         Ptr{Ptr{CHOLMOD.C_Dense{Tv}}}, Ptr{Cvoid}),
        ordering,       # all, except 3:given treated as 0:fixed
        tol,            # columns with 2-norm <= tol treated as 0
        econ,           # e = max(min(m,econ),rank(A))
        getCTX,         # 0: Z=C (e-by-k), 1: Z=C', 2: Z=X (e-by-k)
        A,              # m-by-n sparse matrix to factorize
        Bsparse,        # sparse m-by-k B
        Bdense,         # dense  m-by-k B
        # /* outputs: */
        Zsparse,        # sparse Z
        Zdense,         # dense Z
        R,              # e-by-n sparse matrix */
        E,              # size n column perm, NULL if identity */
        H,              # m-by-nh Householder vectors
        HPinv,          # size m row permutation
        HTau,           # 1-by-nh Householder coefficients
        CHOLMOD.common_struct) # /* workspace and parameters */
    @show rnk
    if rnk < 0
        error("Sparse QR factorization failed")
    end

    return rnk
end

```

**Comment by vincentcp** [comment]
The `spqr_solve` routine above works a factor 2/3 more efficient than the full factorisation on the problems I need to tackle. 

Any idea why the memory use of the `rpivinv` field is high in the figures I included above?

**Comment by ViralBShah** [comment]
I am not sure if there is a clear next step to do something here that works generally. I am closing this for now, but perhaps reopen if it should stay open.
