### ISSUE TITLE
Backslash with Float32 SparseMatrixCSC fails on qr call

### ISSUE THREAD

**Issue by scottstanie** [JuliaLang/julia#33425]
```julia
julia> using SparseArrays

julia> A = spdiagm(0 => -ones(Float32, 4), 1=>ones(Float32,4))[1:end-1, :]
4×5 SparseMatrixCSC{Float32,Int64} with 8 stored entries:
  [1, 1]  =  -1.0
...

julia> b = rand(Float32, 4);

julia> A \ b
ERROR: MethodError: no method matching qr(::SparseMatrixCSC{Float32,Int64}, ::Type{Val{true}}; tol=3.0345731f-5)
Closest candidates are:
  qr(::AbstractArray{T,2}, ::Any) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:363 got unsupported keyword argument "tol"
  qr(::SparseMatrixCSC; tol) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
  qr(::AbstractArray{T,2}) where T at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/qr.jl:369 got unsupported keyword argument "tol"
Stacktrace:
 [1] #qr#4(::Float32, ::typeof(qr), ::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [2] qr(::SparseMatrixCSC{Float32,Int64}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SuiteSparse/src/spqr.jl:204
 [3] \(::SparseMatrixCSC{Float32,Int64}, ::Array{Float32,1}) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/SparseArrays/src/linalg.jl:1376
 [4] top-level scope at REPL[4]:1
```

This only fails for the float32 version for some reason... my initial digging couldn't find where it is going wrong.

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/issues/25986#issuecomment-364649899. I haven't checked SQPR specifically but it's a limitation in CHOLMOD so I think it's the same for SPQR.

**Comment by dkarrasch** [comment]
Should then the line I quoted above throw an error? The `Float64` method does not run by this one, so it seems anything that is not handled by the operational method is going to run by here... and fail with that cryptic error message. Instead, we could advise the user to up-convert the matrix.
Hm, or up-convert automatically but emit a warning?

**Comment by andreasnoack** [comment]
I think we should avoid automatic promotion to `Float64`. When trying to do computations with `Float32` it can be a bit of work to identify where such promotions happen and you typically try to use `Float32` for a reason.

A more informative error message would be a good idea.

**Comment by dkarrasch** [comment]
I was going to add an error message to the above quoted line, when I realized that I should make SPQR consistent with CHOLMOD and UMFPACK. This is where I realized that we do up-convert in the other two factorizations. We could make the QR consistent with the other two and add a note to the docs as we have in `
```
!!! note
    This method uses the CHOLMOD library from SuiteSparse, which only supports
    doubles or complex doubles. Input matrices not of those element types will
    be converted to `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}`
    as appropriate.

!!! note
    `lu(A::SparseMatrixCSC)` uses the UMFPACK library that is part of
    SuiteSparse. As this library only supports sparse matrices with [`Float64`](@ref) or
    `ComplexF64` elements, `lu` converts `A` into a copy that is of type
    `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.
```
So we could convert via `convert` as we do in UMFPACK (CHOLMOD is a bit special, because it converts via the `Sparse` constructor)?
https://github.com/JuliaLang/julia/blob/beb218621fc75b911dd6c86f19809c3fb07479a7/stdlib/SuiteSparse/src/umfpack.jl#L165-L177
