### ISSUE TITLE
Unexpected error in anonymous functions when all arguments are not type stable

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#33421]
The original problem is described on [SO here](https://stackoverflow.com/questions/58169453/plotting-function-with-respect-to-a-keyword-argument-leads-to-error-in-julia).

This the code that fails to run properly:
```
julia> using HCubature

julia> function func(v, x0, y0; rad=1.)
           L = hcubature(r->r[1]*v(x0+r[1]*cos(r[2]), y0+r[1]*sin(r[2])), [0., π/2], [rad, π])[1]
           R = hcubature(r->r[1]*v(x0+r[1]*cos(r[2]), y0+r[1]*sin(r[2])), [0., 0], [rad, π/2])[1]
           return L, R
       end
func (generic function with 1 method)

julia> v = (x,y) -> x
#27 (generic function with 1 method)

julia> x0_, y0_ = 0, 0
(0, 0)

julia> rad_ = 0.:0.1:9.
0.0:0.1:9.0

julia> func_array_L = [func(v, x0_, y0_; rad = radius)[1] for radius in rad_]
Internal error: encountered unexpected error in runtime:
MethodError(f=typeof(Base.string)(), args=(Expr(:<:, :t, :r),), world=0x0000000000000eec)
```

Replacing a comprehension by a `map` e.g. by `map(radius -> func(v, x0_, y0_; rad = radius)[1], rad_)` does not solve the problem. Interestingly in this case **an error is thrown but a result is produced correctly**, so it is really strange.

The core reason seems to be type inference if **all** arguments passed to `func` are not type stable (i.e. are `global` and not `const`). It is enough that any of them is `const` (in SO answer I have fixed `v` but also fixing `x0_` and `y0_` to by type-stable solves the problem).

**Comment by JeffBezanson** [comment]
> Interestingly in this case **an error is thrown but a result is produced correctly**, so it is really strange.

That happens if there is an internal error during type inference. We catch it and just proceed to run the code without inference.

What version of julia is this?

**Comment by JeffBezanson** [comment]
Have not been able to reproduce this. Could you provide a manifest?

**Comment by bkamins** [comment]
Here it is:
[Manifest.txt](https://github.com/JuliaLang/julia/files/3672733/Manifest.txt)

Now I have checked different version of Julia with the following results:
* Version 1.0.4 (2019-05-16): works
* Version 1.2.0 (2019-08-20), current stable: fails
* Version 1.3.0-rc1.0, Commit 768b25f6a8 (2019-08-18 00:04 UTC): works

**Comment by JeffBezanson** [comment]
Ok I'm going to assume this has been fixed then.
