### ISSUE TITLE
Custom load path confuses code loading

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#33449]
Context: I'm using a custom load path to simplify working across Julia versions.

This issue surfaces on the master branch of Flux which depends (in the manifest) on a specific commit of Zygote. Using Flux without the manifest does not work, because it pulls an older version of Zygote:

```
$ rm -rf .julia
$ julia
(v1.2) pkg> dev Flux
julia> using Flux
[ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
ERROR: LoadError: UndefVarError: pullback not defined
shell> ls ~/.julia/packages/Zygote
bdE6T
```

Instead, instantiating the Manifest gives a working set-up:

```
$ rm -rf .julia
$ mkdir -p .julia/dev
$ cd .julia/dev
$ git clone https://github.com/FluxML/Flux.jl Flux
$ cd Flux
$ julia --project
(Flux) pkg> instantiate
julia> using Flux
[ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
julia> 
shell> ls ~/.julia/packages/Zygote
HErRu
```

If I now go back to the global environment and develop Flux, it will pull the non-compatible version of Flux, but the project environment will still use the correct version:

```
$ julia
(v1.2) pkg> dev Flux
[ Info: Path `/home/tim/.julia/dev/Flux` exists and looks like the correct package, using existing path
shell> ls ~/.julia/packages/Zygote
bdE6T  HErRu

$ julia --project
julia> using Zygote
julia> pathof(Zygote)
"/home/tim/.julia/packages/Zygote/HErRu/src/Zygote.jl"
julia> using Flux
julia>
```

If however I do all this with my custom load path (`JULIA_LOAD_PATH="@common::"`), that last step fails and the wrong version of Zygote is loaded:

```
$ julia --project
julia> using Zygote
julia> pathof(Zygote)
"/home/tim/.julia/packages/Zygote/bdE6T/src/Zygote.jl"
julia> using Flux
ERROR: LoadError: UndefVarError: pullback not defined
```

Reproducer:

```sh
export JULIA_PKG_DEVDIR=$(mktemp -d)
git clone https://github.com/FluxML/Flux.jl $JULIA_PKG_DEVDIR/Flux
cd $JULIA_PKG_DEVDIR/Flux

# working
export JULIA_DEPOT_PATH=$(mktemp -d)
julia --project -e 'using Pkg; pkg"instantiate"; using Flux'
ls $JULIA_DEPOT_PATH/packages/Zygote
julia -e 'using Pkg; pkg"dev Flux"'
ls $JULIA_DEPOT_PATH/packages/Zygote
julia --project -e 'using Zygote; @show pathof(Zygote); using Flux'

# broken
export JULIA_LOAD_PATH="@common::"
export JULIA_DEPOT_PATH=$(mktemp -d)
julia --project -e 'using Pkg; pkg"instantiate"; using Flux'
ls $JULIA_DEPOT_PATH/packages/Zygote
julia -e 'using Pkg; pkg"dev Flux"'
ls $JULIA_DEPOT_PATH/packages/Zygote
julia --project -e 'using Zygote; @show pathof(Zygote); using Flux'
```

Reproduces on 1.2 and 1.3-rc2.

**Comment by KristofferC** [comment]
So to be explicit. Code loading uses the manifest from the first entry in LOAD_PATH even though that is not the active project?

**Comment by maleadt** [comment]
> So to be explicit, code loading uses the manifest from the first entry in LOAD_PATH even though that is not the active project?

Yes, that seems exactly what's happening. A simpler reproducer, adding LLVM and LLVM#master in an active project:

```
$ export JULIA_DEPOT_PATH=$(mktemp -d)
$ julia
(v1.2) pkg> add LLVM
shell> ls /tmp/tmp.gT0zEl3r5C/packages/LLVM
IoThY
(v1.2) pkg> activate .
Activating environment at `/tmp/x/Project.toml`
(x) pkg> add LLVM#master
shell> ls /tmp/tmp.gT0zEl3r5C/packages/LLVM
IoThY  sSzpU
julia> using LLVM
julia> pathof(LLVM)
"/tmp/tmp.gT0zEl3r5C/packages/LLVM/sSzpU/src/LLVM.jl"
```

When setting `JULIA_LOAD_PATH="@common::"` the wrong copy of LLVM is picked up despite activating a project: 

```
$ export JULIA_DEPOT_PATH=$(mktemp -d)
$ export JULIA_LOAD_PATH="@common::"
$ julia
(v1.2) pkg> add LLVM
shell> ls /tmp/tmp.gT0zEl3r5C/packages/LLVM
IoThY
(v1.2) pkg> activate .
Activating environment at `/tmp/x/Project.toml`
(x) pkg> add LLVM#master
shell> ls /tmp/tmp.gT0zEl3r5C/packages/LLVM
IoThY  sSzpU
julia> using LLVM
julia> pathof(LLVM)
"/tmp/tmp.jABm84zVVk/packages/LLVM/IoThY/src/LLVM.jl"
```

**Comment by KristofferC** [comment]
In some sense, this is not a bug. Code loading search things in the order in LOAD_PATH and you will here have `[common, @, @v#.#, @stdlib]` with `common` being more prioritized than the current project (which is denoted by `@`).

**Comment by maleadt** [comment]
> In some sense, this is not a bug.

Yeah, I can see that. I guess I expected the Manifest to be honored more strictly and a request for a specific tree hash not to be fulfilled by a different tree of the same package.

**Comment by StefanKarpinski** [comment]
Each load path entry has both a project and manifest associated with it; earlier manifests win.
