### ISSUE TITLE
Floating point printing bug whack-a-mole

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#33463]
See https://github.com/JuliaLang/julia/issues/33185#issuecomment-538038803:

> The value "0.025621074" is being printed as "0.025621" and not "0.0256211" in the nightly.

**Comment by simonbyrne** [comment]
I’ve been looking over the Ryu code, I think I have an idea for how to do this.

**Comment by simonbyrne** [comment]
Another thing I noticed today is that we need some more checks on Float16 behavior, i.e.
```
julia> Float16(65504)
Float16(65500.0)

julia> sprint(show, Float16(65504); context=:compact => true)
"65500.0"
```

On 1.2
```
julia> Float16(65504)
Float16(6.55e4)

julia> sprint(show, Float16(65504); context=:compact => true)
"65504.0"
```

**Comment by simonbyrne** [comment]
c.f. https://github.com/JuliaLang/julia/pull/24651#issuecomment-345535687
