### ISSUE TITLE
Download issue when trying to install 1.2.0 with tarball with all dependencies

### ISSUE THREAD

**Issue by DBrusson** [JuliaLang/julia#33461]
Hi,

I'm trying to install julia-1.2.0 from the tarball with dependencies (https://julialang.org/downloads/)
It seems that there is an error when trying to download the libuv (and maybe other dependencies, the script doesn't go further). When I'm using the tarball without all the dependencies, I can download Suitesparse and install it and then I have the same error regarding libuv. I guess some links are broken or something like that.

But what's really annoying is that, well, I guess the point of the tarball with all dependencies is that we don't have to download dependencies right ?

_% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   445  100   445    0     0    752      0 --:--:-- --:--:-- --:--:--   751
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make[1]: *** [/tmp/julia-1.2.0/julia/deps/srccache/LibUV.v2.0.0+1.29.1-julia-0..tar.gz] Error 22
make: *** [julia-deps] Error 2_

**Comment by fredrikekre** [comment]
The tarball with dependencies only includes the source code, so you need to set
```
override USE_BINARYBUILDER=0
```
in `Make.user` to build using the source files instead of downloading pre-built binaries for the dependencies.

**Comment by DBrusson** [comment]
Oh yes, it works now, thank you !
I'm closing the issue.
