### ISSUE TITLE
AssertionError: 0 < tid <= length(THREAD_RNGs) compiling Random.shuffle! (e.g. MacroTools) fails on 1.3

### ISSUE THREAD

**Issue by dhazeghi** [JuliaLang/julia#33471]
Seen with 1.3.0rc1, rc2 and rc3.  Seems to work fine on 1.1.  The failing snippet is actually from MacroTools.jl, so any application using MacroTools will fail to compile.  The compilation command was originally generated by PackageCompiler.  Here is a simplified testcase

test.jl
```
using Compat

animals = [ "bear", "penguin", "fish" ]
Compat.Random.shuffle!(animals)

Base.@ccallable function julia_main(ARGS::Vector{String})::Cint
    println("$(animals)")
    return 0
end
```

```
julia> versioninfo()
Julia Version 1.3.0-rc3.0
Commit b5ccd0f2ef (2019-10-04 01:57 UTC)
...
/test/julia-1.3.0-rc3//bin/julia /test/julia-1.3.0-rc3//pkg/packages//PackageCompiler/osIMW/juliac.jl -vae  /tmp/test.jl
...
pushfirst!(Base.DEPOT_PATH, "cache_ji_v1.3.0-rc3.0") # save precompiled modules locally
include("/tmp/test.jl") # include Julia program file
'`
ERROR: LoadError: AssertionError: 0 < tid <= length(THREAD_RNGs)
Stacktrace:
 [1] default_rng(::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Random/src/RNGs.jl:298
 [2] default_rng at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Random/src/RNGs.jl:296 [inlined]
 [3] shuffle!(::Array{String,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Random/src/misc.jl:220
 [4] include at ./boot.jl:328 [inlined]
```

**Comment by JeffBezanson** [comment]
`Random.__init__` is not getting called. It looks like PackageCompiler is generally skipping init methods, and then manually picking a couple to run.

Aside: I greatly enjoy how shuffling an array of animal names seems contrived, but then I check and no, MacroTools *actually shuffles an array of animal names*. :rofl: 

I would suggest one of the following:
- Add Random to the list of packages whose init methods PackageCompiler calls
- Don't bother shuffling the animals in MacroTools

**Comment by dhazeghi** [comment]
Thanks for the quick triage - indeed that is exactly the issue and there is a separate bug already open for PackageCompiler.  As I am partial to animal shuffling, I'll go ahead with the first option!

**Comment by dhazeghi** [comment]
See https://github.com/JuliaLang/PackageCompiler.jl/issues/277
