### ISSUE TITLE
Floating-point error converting floats to strings

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaLang/julia#33485]
I notice that `0.1 + 0.1 + 0.1` evaluates to `0.30000000000000004`  This seems like undesirable behaviour. Clearly it's a result of machine precision, but I see that `(0.1 + 0.1 + 0.1) + 0.1` evaluates to `0.4` and `0.3` evaluates to `0.3`. Could this be managed better?

**Comment by aahaselgrove** [comment]
The obvious solution to me would be reducing the number of significant digits - I notice that MATLAB uses 14, and have never experienced this kind of issue with MATLAB.

**Comment by KristofferC** [comment]
See https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678.

Settings for how to modify the IOContext (to enable printing fewer digits is in progress at https://github.com/JuliaLang/julia/pull/29249).

**Comment by aahaselgrove** [comment]
More background here: https://discourse.julialang.org/t/working-with-machine-precision/29576

I think I'm focusing more on the string representation of numbers than the REPL output specifically (context: https://github.com/JuliaPlots/PlotUtils.jl/issues/66, printing numbers for plots)
