### ISSUE TITLE
IO Problem with Japanese System Locale

### ISSUE THREAD

**Issue by taliegemen** [JuliaLang/julia#33484]
I highly believe there is a problem with how file locations use ¥ instead of \ in command window of computers with Japanese system locale. When I change my system locale to English the code works perfectly well.

The code i want to run:
`img = open("C:\\Users\\myusername\\Desktop\\document1.txt","r")`

The error i get:
> ERROR: LoadError: SystemError: opening file "C:\\Users\\myusername\\Desktop\\document1.txt": No such file or directory
> Stacktrace:
>  [1] #systemerror#44(::Nothing, ::typeof(systemerror), ::String, ::Bool) at .\error.jl:134
>  [2] systemerror at .\error.jl:134 [inlined]
>  [3] #open#311(::Bool, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::typeof(open), ::String) at .\iostream.jl:289
>  [4] #open at .\none:0 [inlined]
>  [5] open(::String, ::String) at .\iostream.jl:345
>  [6] top-level scope at c:\Users\myusername\Desktop\bug.jl:1
>  [7] include_string(::Module, ::String, ::String) at .\loading.jl:1064
>  [8] (::getfield(Main._vscodeserver, Symbol("##9#12")){String,Int64,Int64,String})() at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.12.3\scripts\terminalserver\terminalserver.jl:153   
>  [9] withpath(::getfield(Main._vscodeserver, Symbol("##9#12")){String,Int64,Int64,String}, ::String) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.12.3\scripts\terminalserver\repl.jl:62
>  [10] (::getfield(Main._vscodeserver, Symbol("##8#11")){String,Int64,Int64,String})() at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.12.3\scripts\terminalserver\terminalserver.jl:152  
>  [11] hideprompt(::getfield(Main._vscodeserver, Symbol("##8#11")){String,Int64,Int64,String}) at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.12.3\scripts\terminalserver\repl.jl:28     
>  [12] macro expansion at c:\Users\myusername\.vscode\extensions\julialang.language-julia-0.12.3\scripts\terminalserver\terminalserver.jl:148 [inlined]
>  [13] (::getfield(Main._vscodeserver, Symbol("##7#10")))() at .\task.jl:268
> in expression starting at c:\Users\myusername\Desktop\bug.jl:1

my versioninfo()
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
Can this be reproduced outside VSCode?

**Comment by taliegemen** [comment]
Now i tested with JuliaPro and REPL, everything seems to work fine.

**Comment by ViralBShah** [comment]
Please reopen if reproducible with a recent Julia.
