### ISSUE TITLE
Waiting on a Timer where the callback errored should throw?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33489]
Running a timer where the callback errors:

```jl
julia> t = Timer(1) do _ error() end; wait(t)

julia>
```

does nothing. Would it be better for this to error analogously to

```jl
julia> t = @async error(); wait(t)
ERROR: TaskFailedException:

Stacktrace:
 [1] error() at ./error.jl:42
 [2] (::var"#11#12")() at ./task.jl:333
Stacktrace:
 [1] wait(::Task) at ./task.jl:251
 [2] top-level scope at REPL[5]:1
```

**Comment by JeffBezanson** [comment]
According to the docs, the timer is independent of the callback and can also be waited on by other tasks. The callback erroring does not close the timer.

I noticed one slightly odd behavior though, which is that any timer that has fired at least once allows exactly 1 wait call after it closes:
```
julia> t = Timer(0.1);

julia> wait(t)

julia> wait(t)
ERROR: EOFError: read end of file
```
Arguably, `wait` on a closed timer should always error.

**Comment by KristofferC** [comment]
Alright, I might have misunderstood the abstraction. I just got confused when it seemed like the callback just got stuck, when it in reality errored.

**Comment by vtjnash** [comment]
> Arguably, wait on a closed timer should always error.

It does: the error here is that we report it as being closed (or `!isopen`) before it actually is closed (by the first wait call). Although this is largely identical to how the IO objects report state, so it's unclear if there's anything to be done here.

**Comment by JeffBezanson** [comment]
> it actually is closed (by the first wait call)

I guess this is the part that's not intuitive --- why does `wait` close the timer? Doesn't `close` close the timer? For example
```
julia> t = Timer(1);

julia> close(t)

julia> wait(t)

```
(where I waited a long time between each command). Naively, I wouldn't describe that as "wait on a closed timer always errors".
