### ISSUE TITLE
Any explanation for this ?

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#33497]
Is any explanation for this

```
julia> I == Array{Float64}(undef,0,0)
true

```
?

**Comment by Roger-luo** [comment]
```
A = Array{Float64}(undef,0,0)
```

The `one(A)` of 0-element 2-dim `Array` is itself, thus `A == one(A)` is true. `I` do not mean identity matrix in Julia but `UniformScaling`
