### ISSUE TITLE
Logical inconsystency 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#33496]
In an earlier issue (now closed) I raised the problem to assign the value `true` to `isempty(I)`. 
Another argument for this request is the following logical inconsistency in Julia 1.2:

```
julia> I == I(3)
true

julia> isempty(I(3))
false

julia> isempty(I)
ERROR: MethodError: no method matching iterate(::UniformScaling{Bool})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:604
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:604
  iterate(::ExponentialBackOff) at error.jl:214
  ...
Stacktrace:
 [1] isempty(::UniformScaling{Bool}) at .\essentials.jl:817
 [2] top-level scope at none:0


```

**Comment by KristofferC** [comment]
But a the same time

```
julia> I == I(0)
true

julia> isempty(I(0))
true
```

Please use https://discourse.julialang.org/ for further discussions about this.

**Comment by dkarrasch** [comment]
Where do you see the logical inconsistency? `I == I(3)` is a comparison of objects of different kind. Check with `@which I == I(3)` which method is applied for that comparison. The fact that it returns `true` does not mean that they are exactly and by all means equal, `I === I(3)` yields `false`! Check with `?===` the meaning of identity and the difference to equality comparison `==`. `I(3)` is a matrix of `Diagonal` type, and you learned in your previous post how we determine whether a matrix is empty, check again with `@which isempty(I(3))`.
