### ISSUE TITLE
Nested threads hang or very slow

### ISSUE THREAD

**Issue by ppalmes** [JuliaLang/julia#33507]
here's an example code which works pretty fast in rc1 but hangs in rc3 and nightly after several runs. Removing the two outer `@threads` work and seems as fast as single thread for this small dataset example.

```julia
using DataFrames
using RDatasets
using DecisionTree
using Base.Threads
function threadedperf(xdf::Matrix,ydf::Vector,trials=5,pops::Vector=[10,20,30,50,100,500,900,1000])
    colsize = size(xdf)[2]
    global dfres=DataFrame()
    mtx=SpinLock()
    @threads for trial in 1:trials
        @threads for pop in pops
            @threads for mtry=2:colsize
                println("th=",threadid(),", mtry=",mtry," population=",pop," trial=",trial)
                rfmodel = build_forest(ydf,xdf,mtry,pop,0.7,5)
                res=apply_forest(rfmodel,xdf)
                acc = sum(res .== ydf)/length(res)
                lock(mtx)
                println("update")
                global dfres = vcat(dfres,DataFrame(acc=acc,mtry=mtry,pop=pop,trial=trial,threadid=threadid()))
                unlock(mtx)
            end
        end
    end
    return dfres
end
xydata=dataset("datasets","iris")
xdata = xydata[:,1:4] |> Matrix
ydata = xydata.Species .|> string
threadedperf(xdata,ydata)
```

**Comment by ppalmes** [comment]
Just tested two inner nested `@threads` and has no issue. If you include all `@threads`, the issue occurs after calling the function several times.

**Comment by ppalmes** [comment]
If I changed SpinLock() to Mutex(), all three nested `@threads` work without issues running the function several times.

**Comment by ppalmes** [comment]
Also tested with ReentrantLock() which is the replacement of Mutex() and no issues so far.

**Comment by JeffBezanson** [comment]
For example, what's probably happening is that all threads are spinning waiting for the lock instead of entering the event loop to finish the I/O request.
