### ISSUE TITLE
High allocation size for broadcast comparison

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#33516]
I was profiling my package SimpleANOVA.jl and found a significant fraction of allocations (9 kb of 32 kb) were occuring due to two simple broadcasted equality checks.

Doing the comparison without broadcasting allocated significantly less memory, as shown in the examples below.

In 1.3.0-rc3:
(behavior appears similar back through 1.1.0)

```
a = [1;2;3]
function u()
    b = a .== 1
end
u()
@time u() # 0.000009 seconds (9 allocations: 4.516 KiB)
```

```
a = [1;2;3]
function v()
    b = BitArray(undef, length(a))
    b[1] = a[1] == 1
    b[2] = a[2] == 1
    b[3] = a[3] == 1
    b
end
v()
@time v() # 0.000013 seconds (6 allocations: 288 bytes)
```

```
a = [1;2;3]
function y()
    [x == 1 for x in a]
end
y()
@time y() # 0.000006 seconds (6 allocations: 272 bytes)
# caveat: returns Array, not BitArray
```

```
a = [1;2;3]
function z()
    b = BitArray(undef, length(a))
    for i in eachindex(a)
        b[i] = a[i] == 1
    end
    b
end
z()
@time z() # 0.000015 seconds (9 allocations: 368 bytes)
```

**Comment by yuyichao** [comment]
You are using non const global variable, please ask further questions on discourse.

**Comment by BioTurboNick** [comment]
Excuse me @yuyichao, but the behavior is the same if I put the variable inside the function. Please don't close an issue without considering it fully.

**Comment by BioTurboNick** [comment]
For that matter, @yuyichao, you could easily have asked me to check your suspicion first. If it turned out to be right, I would have closed it myself. Cursorily dismissing someone reporting an issue doesn't create a good culture.

**Comment by KristofferC** [comment]
It is this function that end up getting called:

https://github.com/JuliaLang/julia/blob/e0bdc76b8b8bd0bd7b2c8ca5e5c9cef9ff911f75/base/broadcast.jl#L914-L937

which allocates:

```
julia> @time Vector{Bool}(undef, Base.bitcache_size);
  0.000019 seconds (5 allocations: 4.344 KiB)

julia> Base.bitcache_size
4096
```

**Comment by mbauman** [comment]
So the actionable thing here would be to put a cutoff on using that cache, yeah?  Seems simple enough.

**Comment by BioTurboNick** [comment]
Thanks all!
