### ISSUE TITLE
UndefVarError: UnsetSolver not defined

### ISSUE THREAD

**Issue by parshinshojaee** [JuliaLang/julia#33534]
Hey,
I already installed GLPKMathProgInterface package, but whenever I use
m=model (solver=GLPKSolverLP())
I get this error: UndefVarError: UnsetSolver not defined

Does anybody know that solving syntaxes have changed from Julia 1.1.1 to 1.2.0??

If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by StefanKarpinski** [comment]
Best to ask on discourse in the MathOpt category.
