### ISSUE TITLE
macOS REPL fails to launch

### ISSUE THREAD

**Issue by brilhana** [JuliaLang/julia#33540]
REPL won't launch in macOS Catalina after a fresh Homebrew installation. Possible cause: zsh is now the default shell in Catalina.

```
brilhana@imac ~ % julia
zsh: killed     julia
```

`“Julia-1.2” can’t be opened because Apple cannot check it for malicious software.`

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/33331. You can just right click on julia and select open.
