### ISSUE TITLE
norm(x,1) and opnorm(x,1) may compute differently the 1-norm 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#33541]
The following sequence produces (usually) different 1-norms for a matrix with one column, as in the following example:

```
julia> x = 1.e10*rand(200,1);

julia> opnorm(x,1)-norm(x,1)
0.0003662109375
```

The cause is possibly the employed different order of summation. I wonder if the behaviour of both functions  can be uniformized.

**Comment by StefanKarpinski** [comment]
That's well within typical numerical error bounds:
```jl
julia> abs(norm(x,1)-opnorm(x,1))/norm(x,1)
2.363154564415354e-16

julia> opnorm(x,1) ≈ norm(x,1)
true
```

**Comment by Keno** [comment]
I concur with @StefanKarpinski's assessment. Of course, if there is something actionable where the precision of either could be improved feel free to re-open or open a new issue.
