### ISSUE TITLE
No UndefVarError when broadcasting an empty array

### ISSUE THREAD

**Issue by fverdugo** [JuliaLang/julia#33575]
Is this the expected behavior?

```julia
julia> a = ones(0,0)
0×0 Array{Float64,2}

julia> foo(x) = bar(x)
foo (generic function with 1 method)

julia> foo(1.0)
ERROR: UndefVarError: bar not defined
Stacktrace:
 [1] foo(::Float64) at ./REPL[2]:1
 [2] top-level scope at REPL[3]:1

julia> broadcast(foo,a)
0×0 Array{Any,2}
```
Note that `broadcast` has returned without any error even though `foo` is not fully defined.

I think, this is related with

```julia
julia> Base._return_type(foo,(Float64,))
Any
```
Hope this is useful. Sorry if its a known issue.

**Comment by fverdugo** [comment]
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIAROOT = /home/fverdugo/Apps/julia/julia-1.2.0
```

**Comment by KristofferC** [comment]
It is in general impossible to answer if a function will error when calling it without actually calling it. `bar` could be defined at some later stage and if it is never called before that so why should there be any errors?

**Comment by fverdugo** [comment]
Yes sure, what surprised me is that `Base._return_type(foo,(Float64,))` is able to return even though `bar` is not defined.

It also intrigues me that the behavior depends on the value of `a` and not on its type.

**Comment by KristofferC** [comment]
> Yes sure, what surprised me is that Base._return_type(foo,(Float64,)) is able to return even though `bar` is not defined.

`Base._return_type` probably doesn't do exactly what you think it does.

> It also intrigues me that the behavior depends on the value of a and not on its type.

If `a` is empty then `f` is never called.

**Comment by fverdugo** [comment]
Thanks for the clarification!
