### ISSUE TITLE
`download` fails after package with binary dependency is loaded

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/julia#33585]
On a freshly loaded Julia REPL:

```
julia> download("https://www.google.com/")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14108    0 14108    0     0  93430      0 --:--:-- --:--:-- --:--:-- 92815
"/tmp/juliaXQ9fcC"
```

But download fails once a package that has BinaryProvider executables is loaded:

```
julia> using Openresty
[ Info: Precompiling Openresty [7d4ad63e-389f-5fab-a457-725f5c98637d]

julia> download("https://www.google.com/")
curl: /root/julia/julia-1.1.1/bin/../lib/julia/libcurl.so.4: no version information available (required by curl)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) Error reading ca cert file /etc/pki/tls/certs/ca-bundle.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed
ERROR: failed process: Process(`curl -g -L -f -o /tmp/juliaQDvtTG https://www.google.com/`, ProcessExited(77)) [77]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:705 [inlined]
 [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:663
 [4] run at ./process.jl:661 [inlined]
 [5] download(::String, ::String) at ./download.jl:27
 [6] download(::String) at ./download.jl:45
 [7] top-level scope at none:0
```

This happens with Julia 1.0.5 and 1.1.1. Does not seem to happen with 1.2.0.

**Comment by tanmaykm** [comment]
Setting the `CURL_CA_BUNDLE` environment variable, pointing to a certs file makes download work again, but there's still a warning printed while loading `libcurl.so.4`.

```
julia> ENV["CURL_CA_BUNDLE"]="/etc/ssl/certs/ca-certificates.crt"
"/etc/ssl/certs/ca-certificates.crt"

julia> using Openresty

julia> download("https://www.google.com/")
curl: /root/julia/julia-1.3.0-rc4/bin/../lib/julia/libcurl.so.4: no version information available (required by curl)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14132    0 14132    0     0  61177      0 --:--:-- --:--:-- --:--:-- 60913
"/tmp/juliadany2b"
```

**Comment by StefanKarpinski** [comment]
@staticfloat, any ideas?

**Comment by staticfloat** [comment]
Best guess; something is changing `LD_LIBRARY_PATH`.  What is your `ENV` before and after running `using Openresty`?

**Comment by staticfloat** [comment]
So there's something about the Julia-bundled `libcurl` that the system `curl` executable doesn't like.  That's not something we can really fix, since we need to apply `LD_LIBRARY_PATH` to add in Julia's library directory.

Possible short term solutions:
* Move `libcurl.so.4` away from your Julia installation, copy in the system `libcurl.so`, and see if that works with libssh2 and libgit2.
* Un-set `LD_LIBRARY_PATH` when invoking `curl` inside of `download()`.
* Put a `curl` binary that is compatible with that `libcurl.so` into Julia's `bin` directory

Long term solution: Reduce the number of binaries we ship inside of Julia; continue to sequester things inside of Artifacts so they are more separated from the rest of the system, use `HTTP.jl` for downloading so that we further reduce our possibilities to muck around with the rest of the system.

**Comment by StefanKarpinski** [comment]
> * Un-set `LD_LIBRARY_PATH` when invoking `curl` inside of `download()`.

This seems like the safest, least disruptive option. If system `curl` works, use it, don't mess with it.

**Comment by staticfloat** [comment]
It's annoying though, because there is the chance that the user has set `LD_LIBRARY_PATH` in such a way that `curl` works, and we can't disambiguate Julia-sourced changes versus system-inherited `LD_LIBRARY_PATH` values.  :/

**Comment by tanmaykm** [comment]
Setting it to the system-inherited values could be a solution then? Isn't that known at startup time?

**Comment by StefanKarpinski** [comment]
I think the main concern with that is Julia calling Julia—in that case the system value would be lost unless we stash that in a different environment variable, like `JULIA_SAVED_LD_LIBRARY_PATH`. I would be fine with shipping our own `curl` but I don't want to start a new version of the whole `7z` process this late in the 1.3 release process.

**Comment by vtjnash** [comment]
We want to be careful to never munge `ENV` internally, since it's not threadsafe (may cause the program to become corrupt and hopefully crash), and repeated calls may leak memory. Using `setenv` is recommended though, since that gets passed straight through to execve.

**Comment by StefanKarpinski** [comment]
If modifying `ENV` is not threadsafe, then we should put a global lock on `ENV`. Why do repeated modifications to `ENV` leak memory? That's alarming and not something that's been mentioned before.

**Comment by sylvaticus** [comment]
Just to comment that, contrary to the original report, this seems to happens also in recent versions of Julia. On 1.5:

```
julia> coeffFile = download("https://lef-nancy.org/files/index.php/s/75rg9HwDp6KG6Sy/download")
"/tmp/jl_BENUcC"

julia> using Ipopt

julia> coeffFile = download("https://lef-nancy.org/files/index.php/s/75rg9HwDp6KG6Sy/download")
┌ Error: Download failed: curl: /home/lobianco/lib/julia-1.5.0/bin/../lib/julia/libcurl.so.4: no version information available (required by curl)
└ @ Base download.jl:43
ERROR: failed process: Process(`curl -s -S -g -L -f -o /tmp/jl_NYte6E https://lef-nancy.org/files/index.php/s/75rg9HwDp6KG6Sy/download`, ProcessExited(60)) [60]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] download_curl(::String, ::String, ::String) at ./download.jl:44
 [3] download(::String, ::String) at ./download.jl:62
 [4] download(::String) at ./download.jl:89
 [5] top-level scope at REPL[7]:1
```

**Comment by giordano** [comment]
@sylvaticus That happens because `Ipopt` [globally sets `LD_LIBRARY_PATH`](https://github.com/jump-dev/Ipopt.jl/blob/1402e5b0a8566d7665401786643c18900b17320a/src/Ipopt.jl#L69-L71@), which is an extremely bad idea.  It has nothing to do with Julia itself, it's a bug in that package
