### ISSUE TITLE
Parenthesis in PATH causes build of libgfortran to fail in WSL

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#33581]
I don't know how much this matters per se, but having a parenthesis in the PATH variable (as sometimes occurs on Windows) seems to cause building of libgfortran to fail with 

`/bin/sh: 1: Syntax error: "(" unexpected`

Changing line 267 of Makefile to place PATH in quotation marks appears to resolve the issue:
Current: `-$(CUSTOM_LD_LIBRARY_PATH) PATH=$(PATH):$(build_depsbindir) $(JULIAHOME)/contrib/fixup-libgfortran.sh --verbose $(build_libdir)`
Works(?): `-$(CUSTOM_LD_LIBRARY_PATH) PATH="$(PATH):$(build_depsbindir)" $(JULIAHOME)/contrib/fixup-libgfortran.sh --verbose $(build_libdir)`

This is in Windows Subsystem for Linux (Ubuntu) on Windows 10 x64. I'm not cross-compiling because that gave me other issues and I wanted to keep things simple.

**Comment by StefanKarpinski** [comment]
Is this a Julia issue? It doesn't seem to be.

**Comment by StefanKarpinski** [comment]
I misunderstood, I thought it was just that `/bin/sh` on WSL didn't like some path names, in which case there would be little we could do about it. That line number has changed—I think it's now line 272—but it also looks like this is fixed on master:

https://github.com/JuliaLang/julia/blob/220681f21fc5aaf83b7c3aee0a2b8d6186805b2c/Makefile#L272

Can you check if the latest release candidate has this problem?

**Comment by BioTurboNick** [comment]
Apologies, it was apparently fixed 5 months ago. I'm building from v1.2. Thanks!

**Comment by StefanKarpinski** [comment]
xref-ing issues: https://github.com/JuliaLang/julia/pull/32100
