### ISSUE TITLE
MD5 and SHA256 checksum of Mac OSX DMG does not match published values

### ISSUE THREAD

**Issue by cems2** [JuliaLang/julia#33595]
MD5 checksum on MacOSX does not match published value for  the current stable Julia

Current stable release: v1.2.0 (Aug 20, 2019)
published MD5 from julia lang site: 239d2535a39c27c1d34c09e14d4ba9e8 julia-1.2.0-mac64.dmg
measured MD5 from downloaded file using MD5 in OSX terminal
MD5 (julia-1.2.0-mac64.dmg) = f76780c23cbdbed06ee23223f66f5156

The MD5 checksum DOES match for the longterm support release
Long-term support (LTS) release: v1.0.5 (Sep 9, 2019)
published value:  c973fc571bdf9b0376d92d25e5268e4f julia-1.0.5-mac64.dmg
measured value: MD5 (julia-1.0.5-mac64.dmg) = c973fc571bdf9b0376d92d25e5268e4f

**Comment by cems2** [comment]
MD5 checksum on MacOSX does not match published value


Current stable release: v1.2.0 (Aug 20, 2019)
published MD5 from julia lang site:  239d2535a39c27c1d34c09e14d4ba9e8  julia-1.2.0-mac64.dmg
measured MD5 from downloaded file using MD5 in OSX terminal
 f76780c23cbdbed06ee23223f66f5156

**Comment by cems2** [comment]
I checked the version of  this download for Windows (using the same mac to download and check it) and for that the MD5 matches.

SO it's the MacOSX version of Julia that has the incorrect checksum

**Comment by fredrikekre** [comment]
Maybe because they were re-signed?

**Comment by ararslan** [comment]
> Maybe because they were re-signed and the hashsum files not updated?

Yeah it was probably something like that.

**Comment by ararslan** [comment]
Seems the file was indeed changed in some way on September 13, but the corresponding 1.2-latest was not. @staticfloat, did you reupload something? I don't remember doing that.

**Comment by staticfloat** [comment]
Yes, I did reupload the macOS binaries because signing needed to be redone.  I neglected to update the checksums, and we didn't notice because the signing is the de-facto verification mechanism anyway.

**Comment by ararslan** [comment]
Okay great, thanks for confirming. I'll get the stuff updated.

**Comment by ararslan** [comment]
Should be good now.
