### ISSUE TITLE
Performance regression affecting inference time for plotting

### ISSUE THREAD

**Issue by yhls** [JuliaLang/julia#33598]
I've been looking into inference times for the first plot, and noticed that
```
using Plots
@time code_typed(plot, (Vector{Float64}, Vector{Float64}))
```
says the `code_typed` takes ~12 seconds with 1.2.0, but ~16 seconds with master.

I've bisected this to:
```
commit 06b4af4d57182de8d5c3ea21525924cc62c3bfaa
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Fri Jun 28 12:20:33 2019 -0400

    dispatch: tolerate un-sorted tables and support non-transitive specificity
```

**Comment by JeffBezanson** [comment]
This should be faster now; the method table has been redesigned in a way that should basically fix this.
