### ISSUE TITLE
Question about Pkg.update()

### ISSUE THREAD

**Issue by david830** [JuliaLang/julia#33618]
Hi all,

I wanted to update a package in Julia, so I typed "Pkg.update("DifferentialEquations")".  The problem is the "DifferentialEquations" package did not get updated.

The package only got updated when I updated all packages by typing "Pkg.update()".  Is there a way to update individual packages?

Thanks,

David

**Comment by ChrisRackauckas** [comment]
Xref Discourse

**Comment by dkarrasch** [comment]
Yes, please use https://discourse.julialang.org to discuss questions.
