### ISSUE TITLE
[SEGFAULT] Checking offset axis before for reshaping

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#33614]
In https://github.com/JuliaLang/julia/blob/606420a308d951ab810a05f6f6c50a1b805f2b47/base/reshapedarray.jl#L173-L177 it should be checked whether the requested array has offset axes.
Otherwise we can get segfaults. See #33603 

In the 1D->1D case (`AbstractVector`) there already is such a check:
https://github.com/JuliaLang/julia/blob/606420a308d951ab810a05f6f6c50a1b805f2b47/base/reshapedarray.jl#L165-L171

Sure, in that given Issue #33603 there might also be an error in OffsetArrays.jl but segfaulting should be prevented here aswell as ultimately ReshapedArray didn't check the indices.

MWE:
```julia
using OffsetArrays
reshape(OffsetArray(-1:0, -1:0), :,1) #shows [1,2] (because invalid indexing into UnitRange cannot segfault)
reshape(OffsetArray(-1:0, -1:0), 2,1) #works though
```
If using an Array instead of a UnitRange, one can get segfaults.

**Comment by dkarrasch** [comment]
As #33856 shows, there are tons of tests that do reshaping with OffsetArrays. So it seems like the wrong approach to fix this by requiring one-based indexing. Maybe this should be fixed by a `reshape` overload by `OffsetArrays.jl`?

**Comment by timholy** [comment]
Superseded by #33890

**Comment by timholy** [comment]
Oh shoot, this is the issue not the PR. Reopening until #33890 merges.
