### ISSUE TITLE
Add example of splatting inside quote to metaprogramming docs

### ISSUE THREAD

**Issue by jamesjscully** [JuliaLang/julia#33638]
I have seen a lot of people asking how to do this, and had the question myself, so I figured it would be useful to put a short example in the docs. It's not obvious because splatting doesn't usually work outside of a function call or definition. Something simple would help:

### Splatting Inside of Quoted Expressions
You can also splat a Tuple or an Array into a quoted expression.
```julia
tup = (1,2,3)
:(+($(tup))) # :(+(1,2,3))
```

**Comment by jw3126** [comment]
I believe `:(+($(tup...))) ` is what you want (note the dots)? Also, any iterator can be splatted.

**Comment by jw3126** [comment]
Seems that it is already in the docs https://github.com/JuliaLang/julia/blob/master/doc/src/manual/metaprogramming.md#splatting-interpolation.

**Comment by jamesjscully** [comment]
yes, `:(+($(tup...)))` is what i meant. And yes you are right! somehow I missed that.
