### ISSUE TITLE
Base.LIBDIR and  Base.PRIVATE_LIBDIR wrong on windows?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33639]
AFAIU, `Base.LIBDIR` is supposed to mean that `joinpath(Sys.BINDIR, Base.LIBDIR)` is supposed to point to where `libjulia` is and `Base.PRIVATE_LIBDIR` is supposed to point to where all the internal libraries like `libmpfr` are located.

On Windows, these libraries are all inside `bin` so both `Base.LIBDIR` and `Base.PRIVATE_LIBDIR` should be `""`.

However, this is not the case with the consequence:

```
julia> abspath(joinpath(Sys.BINDIR, Base.LIBDIR))
"C:\\Users\\Kristoffer Carlsson\\AppData\\Local\\Julia-1.3.0-rc4\\lib"

julia> dirname(abspath(Libdl.dlpath("libjulia")))
"C:\\Users\\Kristoffer Carlsson\\AppData\\Local\\Julia-1.3.0-rc4\\bin"
```

**Comment by ViralBShah** [comment]
Is this still an issue?
