### ISSUE TITLE
Performance issue when importing a package multiple times

### ISSUE THREAD

**Issue by petvana** [JuliaLang/julia#33647]
I have noticed that importing a package for the second time takes much greater time that for the 3rd+ time. It seems to be independent to specific Julia 1.x version and the imported package. According to the [documentation](https://docs.julialang.org/en/v1/manual/code-loading/) it should be referenced at the second time:

> If the same X package is imported multiple times in the same Julia session, it is only loaded the first time—on subsequent imports, the importing module gets a reference to the same module.

```julia
julia> @time using PyPlot
  4.638629 seconds (6.90 M allocations: 346.642 MiB, 4.02% gc time)

julia> @time using PyPlot
  1.794451 seconds (3.58 M allocations: 169.720 MiB, 2.01% gc time)

julia> @time using PyPlot
  0.000315 seconds (218 allocations: 11.719 KiB)

julia> @time using PyPlot
  0.000320 seconds (218 allocations: 11.719 KiB)
```

The same behaviour occurs when the package is imported using `import` keyword or is imported into different packages.

Btw, is it realy neccesarry to update modification time (using `touch()`) of precompiled file (~/.julia/compiled/v1.4/PyPlot/oatAj_HtSOS.ji) at the first import every time, even if the package is not changed/pre-compiled?

```julia
julia> versioninfo()
Julia Version 1.4.0-DEV.369
Commit dbad68deb3 (2019-10-23 12:44 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by petvana** [comment]
It seems you are correct. Some of the functions are re-compilated. But I don't understand why they have to be invalidated in the first place.

```julia
julia> @time precompile(Tuple{typeof(Base.require), Module, Symbol})
  0.000051 seconds (11 allocations: 544 bytes)
true

julia> @time using PyPlot
  4.720757 seconds (8.73 M allocations: 455.224 MiB, 3.23% gc time)

julia> @time precompile(Tuple{typeof(Base.require), Module, Symbol})
  1.270191 seconds (2.94 M allocations: 138.201 MiB, 3.14% gc time)
true

julia> @time using PyPlot
  0.080180 seconds (5.70 k allocations: 293.638 KiB)

julia> @time precompile(Tuple{typeof(Base.require), Module, Symbol})
  0.000037 seconds (6 allocations: 304 bytes)
true
```

**Comment by oscardssmith** [comment]
The reason for invalidation is probably in case methods changed.

**Comment by Keno** [comment]
Correct, the julia system needs to validate that none of new methods in `PyPlot` changed how package loading works, which takes a bit of time. Invalidating fewer things is an ongoing project of course, but per se this is not a bug.
