### ISSUE TITLE
convenient constructors for `NamedTuple`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#33648]
It would be nice to have some more constructors for named tuple.  Particularly
```julia
NamedTuple(x) = (;x...)
```
There may be some other good methods as well that I'm not thinking of.  (Thanks to @JeffBezanson for this explicit one.)

**Comment by o314** [comment]
There are upcoming changes from #32330

**Comment by brenhinkeller** [comment]
Not sure how much this has changed, but programmatically generating `NamedTuple`s does seem to be more common nowadays. What do you think @ExpandingMan, has this improved enough to close?

**Comment by ExpandingMan** [comment]
Yeah, there are a lot more `NamedTuple` constructors these days.  I don't know when they were all added exactly, but I certainly don't feel like this issue is relevant any more.
