### ISSUE TITLE
0-element fill! errors on wrong type

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#33645]
Is there a reason, why this has to error? Or could that be changed?
```julia
julia> fill!(Int[], missing)
ERROR: MethodError: Cannot `convert` an object of type Missing to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
  ...
Stacktrace:
 [1] fill!(::Array{Int64,1}, ::Missing) at .\array.jl:307
 [2] top-level scope at REPL[5]:1
```

**Comment by StefanKarpinski** [comment]
Seems a bit questionable: one generally wants to avoid errors that happen or don't happen based on runtime things like how large an array is. This would allow one special case (empty array) when the logic would fail for any other array size.

**Comment by dkarrasch** [comment]
I'm afraid I don't follow here. The error has nothing to do with the size of the array or "0-element `fill!`". This is failing solely due to the non-convertable type, for any size. Why should this not error? Or is the argument that `fill!([], missing)` does not throw? 😕

**Comment by pdeffebach** [comment]
I don't think this is a bug. Please note that Julia doesn't automatically promote types with `fill!`. Note that 

```
fill!(Any[], missing)
```

works, as does 

```
fill(Any[1, 2, 3], missing)
```

OP I think you are looking for 

```
fill!(Union{Int, Missing}[], missing)
```

**Comment by martinholters** [comment]
The point is that `fill!` converts the given value to the array's element type exactly once. It could also do it at most once, i.e. not at all for an empty destination. Perfectly possible, but I don't know whether desirable.
