### ISSUE TITLE
Memoization of vararg functions

### ISSUE THREAD

**Issue by gmoutsin** [JuliaLang/julia#33685]
I tried to memoize a vararg function using Memoize.jl.

```
@memoize function test(a::Vararg{Int})
    return length(a)
end

test(1,2)
```

gives

`TypeError: test: in typeassert, expected Vararg{Int64,N} where N, got Tuple{Int64,Int64}`

I opened an [issue](https://github.com/JuliaCollections/Memoize.jl/issues/40) at Memoize.jl, but I don't think this can be solved there.

As far as I understand the problem is that `Tuple{Int64,Int64}`is not a subtype of `Vararg{Int64,N} where N`. I'm not sure whether it should be a subtype, but I think that memoization of such functions should be possible.

**Comment by yuyichao** [comment]
The subtype relation is fine. Memorize need to handle the special syntax of `Vararg` since it's not really a type.
