### ISSUE TITLE
integer raised to negative power: improve error message

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#33699]
Julia v1.3-rc4.1:
```julia
julia> 2^-4
0.0625

julia> exponent = -4
-4

julia> 2^exponent
ERROR: DomainError with -4:
Cannot raise an integer x to a negative power -4.
Make x or -4 a float by adding a zero decimal (e.g., 2.0^-4 or 2^-4.0 instead of 2^-4), or write 1/x^4, float(x)^-4, x^float(-4) or (x//1)^-4
Stacktrace:
 [1] throw_domerr_powbysq(::Int64, ::Int64) at .\intfuncs.jl:176
 [2] power_by_squaring(::Int64, ::Int64) at .\intfuncs.jl:197
 [3] ^(::Int64, ::Int64) at .\intfuncs.jl:221
 [4] top-level scope at REPL[258]:1
```
Debugger even produces a different output for 2^-4:
```julia
julia> 2^-4
0.0625

julia> @enter 2^-4
In ^(x, p) at intfuncs.jl:221
>221  ^(x::T, p::T) where {T<:Integer} = power_by_squaring(x,p)

About to run: (Base.power_by_squaring)(2, -4)
1|debug> c
ERROR: DomainError with -4:
Cannot raise an integer x to a negative power -4.
Make x or -4 a float by adding a zero decimal (e.g., 2.0^-4 or 2^-4.0 instead of 2^-4), or write 1/x^4, float(x)^-4, x^float(-4) or (x//1)^-4
Stacktrace:
 [1] throw_domerr_powbysq(::Int64, ::Int64) at intfuncs.jl:176
 [2] power_by_squaring(::Int64, ::Int64) at intfuncs.jl:197
 [3] ^(::Int64, ::Int64) at intfuncs.jl:221
```

**Comment by thofma** [comment]
Related: https://github.com/JuliaLang/julia/issues/24699

**Comment by KristofferC** [comment]
> Debugger even produces a different output for 2^-4:

Use a function:

```
julia> f() = 2^-4
f (generic function with 1 method)

julia> @enter f()
In f() at REPL[1]:1
>1  f() = 2^-4

About to run: (Core.apply_type)(Val, -4)
1|debug> se
In f() at REPL[1]:1
>1  f() = 2^-4

About to run: (Val{-4})()
1|debug>
In f() at REPL[1]:1
>1  f() = 2^-4

About to run: (Base.literal_pow)(^, 2, Val{-4}())
1|debug>
In f() at REPL[1]:1
>1  f() = 2^-4

About to run: return 0.0625
1|debug>
0.0625
```

**Comment by KristofferC** [comment]
This is however intended (although I want to state that I really dislike like it).

The error message needs to be improved though since it gives `2^-4` as an example of the non-working case while thatr now works.

**Comment by ngharrison** [comment]
I just ran into this problem today. Can someone explain to me why a variable with type Int would behave differently than a literal with type Int? I expected both of these to be analogous to dividing two Ints becoming a float.

**Comment by rapus95** [comment]
I'm wondering the same since that suggests that there is a behavioral difference between compile time and run time (though that's technically not true, just feels like it because I assume it to happen due to some optimization hooks?)
All sorts of pointers on why that behaviour is good (to educate myself about the possibilities I don't see right now), would be very much appreciated :)

**Comment by LilithHafner** [comment]
Raising an integer to a positive integer power returns a positive integer (this is good because it makes `x^2` equivalent to `x*x`). Raising an integer to a negative integer power can't return an integer. It can either return a floating point value or error. If the compiler knows the sign of the integer, it is possible to efficiently return an integer for positive exponents and a Float64 for negative exponents. If the compiler does not know the sign of the exponent, then this is not possible to do type stably, so we must either always return a Float64 or error on negative inputs. Folks chose to error on negative inputs.

That's the history.
