### ISSUE TITLE
Better printing of `zip` output

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#33695]
The printing of zip is quite unreadable for even simple arguments:
```julia
julia> zip((:a,:b,:c), (1,2,3))
Base.Iterators.Zip{Tuple{Tuple{Symbol,Symbol,Symbol},Tuple{Int64,Int64,Int64}}}(((:a, : :c), (1, 2, 3)))
```
Can we include better printing of `zip` outputs so that for interactive sessions, it's easier to scan?

**Comment by StefanKarpinski** [comment]
Sure, should be easy enough. My suggestion is to print it as it's called, i.e. just
```jl
zip((:a, :b, :c), (1, 2, 3))
```

**Comment by musm** [comment]
Sounds good to me. Do we do that for any other types ?

**Comment by vtjnash** [comment]
Sometimes, c.f. `showarg` & such

**Comment by StefanKarpinski** [comment]
Also `typeof(+)` and so on.

**Comment by sostock** [comment]
Would it be good to do this with all functions from `Base.Iterators`? Or at least the ones that are imported into `Base`?

**Comment by nalimilan** [comment]
`skipmissing` would probably benefit from this too.

**Comment by pdeffebach** [comment]
Relevant issue [here](https://github.com/JuliaLang/julia/pull/34734) regarding best practices for the two argument `show` method.
