### ISSUE TITLE
UndefVarError: T not defined

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#33737]
This test https://github.com/TuringLang/AdvancedHMC.jl/blob/e405155ee93579b06ea0757512b671e36ddbbcdd/test/trajectory.jl#L73 started erroring with
```julia
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] combine(::T, ::T) where T<:ClassicNoUTurn at /Users/andreasnoack/.julia/dev/AdvancedHMC/src/trajectory.jl:214
 [2] top-level scope at REPL[59]:1
```
see https://travis-ci.org/TuringLang/AdvancedHMC.jl/jobs/605892161?utm_medium=notification, after https://github.com/JuliaLang/julia/pull/31807/commits/abda71ec9fad70ddf7abeb58d94922167a799a2f. The failing method is just
```julia
combine(cleft::T, cright::T) where {T<:ClassicNoUTurn} = T()
```
but it's unclear exactly what happens and, so far, I've been unable to reduce the error.

**Comment by vtjnash** [comment]
Was not able to reproduce this either, though it fails an internal assertion error on a debug build (the method sorting order was wrong for some function). Can you retest or provide a Manifest.toml of the failing environment?
