### ISSUE TITLE
Corrupt compilation cache when include_dependency is before includes

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/julia#33769]
This was discovered because a [package of mine](https://github.com/Klepac-Ceraj-Lab/echo_analysis.git) was not `Revise`ing ([see here](https://github.com/timholy/Revise.jl/issues/379) for additional context). @timholy noticed that the package was recompiled on every use, and moving an `include_dependency()` call in `src/ECHOAnalysis.jl` to be after the `include()`s fixed the problem. I'm on julia 1.2.

To reproduce:

```
pkg> dev https://github.com/Klepac-Ceraj-Lab/echo_analysis.git

julia> using ECHOAnalysis
[ Info: Precompiling ECHOAnalysis [39b5b81a-5017-403f-bb48-824a42db2b1c]

julia> id = Base.PkgId(ECHOAnalysis)
ECHOAnalysis [39b5b81a-5017-403f-bb48-824a42db2b1c]

julia> paths = Base.find_all_in_cache_path(id)
1-element Array{String,1}:
 "/home/tim/.julia/compiled/v1.3/ECHOAnalysis/kIyeq_tZjuv.ji"

julia> sourcepath = Base.locate_package(id)
"/home/tim/.julia/dev/ECHOAnalysis/src/ECHOAnalysis.jl"

julia> Base.stale_cachefile(sourcepath, first(paths))
true
```

Note: if you have issues with RCall installing, [this branch](https://github.com/Klepac-Ceraj-Lab/echo_analysis/tree/no-r) can be used instead. I will probably also merge a change with the `include_dependency()` moved at some point (which again fixes the problem), but will maintain this branch in it's current state.

[According](https://github.com/timholy/Revise.jl/issues/379#issuecomment-549854348) [to](https://github.com/timholy/Revise.jl/issues/379#issuecomment-549871141) @timholy:

>It seems that Julia is building a corrupt *.ji precompile file... (It's probably a bug in either src/dump.c or base/loading.jl.)

**Comment by KristofferC** [comment]
It looks like you are mutating `data.toml` during precompilation after including it as a dependency:

https://github.com/Klepac-Ceraj-Lab/echo_analysis/blob/2afe07225086e08f3f8767797dbe213fa663b096/src/startup.jl#L6-L7

and then

https://github.com/Klepac-Ceraj-Lab/echo_analysis/blob/2afe07225086e08f3f8767797dbe213fa663b096/src/notebook_handling.jl#L6-L32.

So the file has been modified after `include_dependency` is called and it seems correct to recompile.

Doing this type of stuff at precompilation time seems quite odd to me.

**Comment by kescobo** [comment]
Ahh, yes, that makes sense. 

>Doing this type of stuff at precompilation time seems quite odd to me.

Yeah, it's probably the wrong choice - it's an expedient solution to a different problem I arrived at, probably makes sense to go back and actually do it right. @timholy does it make sense to you that this is the issue, rather than it being a julia bug? If so, I'll close the issue and find a better solution.

**Comment by vtjnash** [comment]
Sounds like Julia is correctly detecting that the file was changed, and faithfully rebuilding as instructed

**Comment by kescobo** [comment]
Makes sense - sorry for the noise!

**Comment by timholy** [comment]
Yes, that's right, I hadn't noticed that was the source of the trouble! Sorry about that.
