### ISSUE TITLE
replace function doesn't work on Tuples

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#33782]
Just ran into this by chance: `replace()` seems broken for `Tuple`s. It accepts a `Tuple`, but the generic implementation can't handle it:

```
julia> replace([1,2,3,4], 3 => 7)
4-element Array{Int64,1}:
 1
 2
 7
 4

julia> replace((1,2,3,4), 3 => 7)
ERROR: MethodError: no method matching similar(::NTuple{4,Int64}, ::Type{Int64})
[...]
```

Might be useful to add a specialized `replace(::Tuple, ...)` at some point (gen func for high performance?).

**Comment by ali-ramadhan** [comment]
Do we expect `replace()` to work for tuples?

Still an issue on
```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by ali-ramadhan** [comment]
Do we just need to define something like

```julia
_similar_or_copy(x::Tuple) = copy(x)
```

so that the following works?

https://github.com/JuliaLang/julia/blob/8a52ea42877c5d0fe3d9b6c2bc4387bceb7ea9b0/base/set.jl#L555-L564
