### ISSUE TITLE
New method ambiguities with diagnonal dispatch on nightly

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#33789]
These methods in Flatten.jl are using diagonal dispatch, which worked fine up until now but are broken on nightly:
https://travis-ci.org/rafaqz/Flatten.jl/jobs/604222542#L220-L224

The recommendation on line 224 is to define a new method identical to the method listed above - _ie the same one that caused the error_

```julia
MethodError: flatten(::Float32, ::typeof(flattenable), ::Type{Number}, ::Type{Float32}) is ambiguous. Candidates:
    flatten(x::I, ft::Function, use::Type{U}, ignore::Type{I}) where {U, I} in Flatten at /home/travis/build/rafaqz/Flatten.jl/src/Flatten.jl:139
    flatten(x::U, ft::Function, use::Type{U}, ignore::Type{I}) where {U, I} in Flatten at /home/travis/build/rafaqz/Flatten.jl/src/Flatten.jl:140

  Possible fix, define
    flatten(::U, ::Function, ::Type{U}, ::Type{I}) where {U, I}
```

**Comment by JeffBezanson** [comment]
This case is actually ambiguous, but the intersection is something like
```
flatten(x::I, ft::Function, use::Type{U}, ignore::Type{I}) where {U, I<:U}
```
which we are not able to compute. Do you expect one of the methods to be called, or is either ok?

**Comment by rafaqz** [comment]
This is working in 1.0 to 1.2. The first option is always called and the `FLoat32` is ignored. I'm not sure what you mean by it "actually" being ambiguous:

```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Flatten

julia> flatten(1.0f0, flattenable, Number, Float32)
()

julia> flatten(1.0, flattenable, Number, Float32)
(1.0,)
```

Here 1.2 the Float32 is ignored, and the Float64 is returned as it is in Number. It's only broken on nightly, so I think this is a breaking change to dispatch.

**Comment by JeffBezanson** [comment]
> I'm not sure what you mean by it "actually" being ambiguous:

By that I mean both methods are applicable, and our algorithm does not consider either one more specific than the other.

**Comment by rafaqz** [comment]
I was just struggling to see how it was ambiguous but resolved in 1.2 without issue, but load order to was probably the answer.

**Comment by vtjnash** [comment]
I think the actual intersection is:
```
f(::Intersection{T, S}, ::Type{T}, ::Type{S}) where {T, S}
```
which I think should be equivalent (perhaps not exactly type-equal though) to the union I gave previously (corrected below):
```
f(::S, ::Type{T}, ::Type{S}) where {S, T<:S} = (T, S)
f(::T, ::Type{T}, ::Type{S}) where {T, S<:T} = (T, S)
```

aka that
```
Tuple{Intersection{T, S}, Type{T}, Type{S}} where {T, S} ≈≈
Union{Tuple{T, Type{T}, Type{S}} where {T, S<:T},
      Tuple{S, Type{T}, Type{S}} where {S, T<:S}}}
```

**Comment by XVilka** [comment]
Will this be included in 1.3 final release too? Since it is in [1.3 milestone](https://github.com/JuliaLang/julia/milestone/33).

**Comment by XVilka** [comment]
Should be this one moved to [1.4](https://github.com/JuliaLang/julia/milestone/34) then? Since 1.3.0 was already released.

**Comment by JeffBezanson** [comment]
I'm very sorry about this but we haven't found a way to resolve this that meets all the constraints. I will have to close as wontfix.
