### ISSUE TITLE
Possible documentation error: range function docstring at julia/base/range.jl

### ISSUE THREAD

**Issue by 4aHxKzD** [JuliaLang/julia#33798]
The second paragraph states

> If `length` and `stop` are provided and `step` is not, the step size will be computed
automatically such that there are `length` linearly spaced elements in the range (a [`LinRange`](@ref)).

but in this setting I get the following
```
julia> typeof(range(1, length=10,stop=100))
StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}
```
A `StepRangeLen` instead of a `LinRange`.

**Comment by stevengj** [comment]
Yes, I noticed this too.  As far as I can tell, the `range` function *never* produces a `LinRange` anymore — it always produces a `StepRange` (when an integer or rational `step` is provided) or a `StepRangeLen` (when a `length` is provided, or a floating-point `step`).

**Comment by stevengj** [comment]
Actually the `range` function does produce a `LinRange` for arguments that are not simple numeric types:
```
julia> range([1,2], [3,4], length=10)
10-element LinRange{Array{Int64,1}}:
 [1.0, 2.0],[1.22222, 2.22222],…,[2.77778, 3.77778],[3.0, 4.0]
```
cc @timholy, who implemented a lot of this stuff in #18777.

**Comment by stevengj** [comment]
cc @kshyatt who was the last person to touch the `range` docs in #28115.

**Comment by kamalojasv181** [comment]
Hi I just created a PR. Kindly review it. https://github.com/JuliaLang/julia/pull/34467

**Comment by kamalojasv181** [comment]
Revised PR https://github.com/JuliaLang/julia/pull/34475
