### ISSUE TITLE
Bug in show macro

### ISSUE THREAD

**Issue by bhalonen** [JuliaLang/julia#33815]
Unexpected behavior:
```julia
julia> @show b = 45 + 123*45 - 1
b = (45 + 123 * 45) - 1 = 5579
5579

julia> @show b = 45 + 123*45 -1
b = 45 + 123 * 45 = 5580
-1 = -1
-1
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by yuyichao** [comment]
This isn't a bug. It's just normal white space sensitivity of macro parsing.

**Comment by bhalonen** [comment]
it is impossible for code and macros to consistently interpret `-` as a unary or binary operator?

**Comment by yuyichao** [comment]
It is impossible to satisfy the following conditions at the same time.
1. White space sensitive macro parsing, i.e. allow macro arguments to be separated by space
2. White space insensitive normal expression parsing, i.e. allow adding or removing white space to not affect parsisng in most context, which includes allow `a -b` and `a - b` to parse at the same time.

It's not impossible to have macros and normal code to parse consistentlty, but you need to pick which one to error in the ambiguous case.

**Comment by Keno** [comment]
Note that you can get parens to ensure the parsing that you want:
```
 @show(b = 45 + 123*45 -1)
```
Unfortunately, the paren-less version depends on whitespace sensitivity, but it's too nice in general to disallow.
