### ISSUE TITLE
Julia release 1.2 and 1.3 freezes after CSV packge is installed and loaded (using...) 

### ISSUE THREAD

**Issue by gconte75** [JuliaLang/julia#33836]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by gconte75** [comment]
On my work laptop (win 10 64bit) where I am trying Julia 1.2 (same behavior with Julia pro) and on my personal one running Win 8.0 64 bit where I have Julia 1.3.0-rc4.1, Julia freezes/gets stuck soon after installing package CSV.
Once installed, in package mode, I get back to command mode, I issue the using CSV command, then I am able to issue a few commands more but it soon gets stuck. All other programs respond fine when this happens. The only solution I have is to close Julia, restart it and avoiding CSV.

**Comment by JeffBezanson** [comment]
I'm hoping this will be fixed by 1.3-rc5, or if you want you can try master or the backports-release-1.3 branch.

**Comment by gconte75** [comment]
Thank you for your answer. 
For now I'll do this csv stuff (I am interpolating big dataframes - one year or more - where several samples are missing) on python - I was trying to do it in Julia 'cause I believe it might be faster.
I'll try installing Julia on Debian Linux (stretch) when I get the chance.
I'll watch out for the rc5 release.
