### ISSUE TITLE
Buildbot: Julia    ERROR: LoadError: Test run finished with errors

### ISSUE THREAD

**Issue by jaideep-seth** [JuliaLang/julia#33844]
- ERROR: LoadError: Test run finished with errors
in expression starting at /usr/home/julia/buildbot/worker-tabularasa/tester_freebsd64/build/share/julia/test/runtests.jl:67

- My pull request ( #33824 ) failed to clear some tests and the build log asked me to create an issue.

- 2/14 tests failed:

    [failed build test 1](https://build.julialang.org/#/builders/29/builds/5934)
    [failed build test 2](https://build.julialang.org/#/builders/32/builds/6015)

 - Output of versioninfo() on my ubuntu 18.04:

`julia> versioninfo()
Julia Version 1.4.0-DEV.441
Commit 91effa2da4 (2019-11-11 17:28 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> 
`

Please help me get this resolved, its my first attempt at contributing to Julia.
Thank you!

**Comment by dkarrasch** [comment]
I'd say those failing tests are not your fault. Just wait until somebody finds the time to review your PR and asks for changes, or merges it.

**Comment by jaideep-seth** [comment]
Hi @dkarrasch could you help me get the PR merged?
Thanks!
