### ISSUE TITLE
backtrace test issue

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#33877]
Been seeing a lot of this start happening recently: https://build.julialang.org/#/builders/65/builds/5828
```
Error in testset backtrace:
Test Failed at D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\backtrace.jl:239
  Expression: read(#= D:\buildbot\worker-tabularasa\tester_win32\build\share\julia\test\backtrace.jl:239 =# Core.@cmd("\$(Base.julia_cmd()) --startup-file=no --compile=min -e \$code"), String) == "1000 1000"
   Evaluated: "998 1000" == "1000 1000"
```

**Comment by c42f** [comment]
Is this only on the windows buildbots?

**Comment by c42f** [comment]
For the record, Jameson reports on slack that he's only observed this on the windows AWS buildbots so far.

**Comment by c42f** [comment]
Out of curiosity, how did you get to the bottom of this @vtjnash? I hope some info from #33948 may have helped, meager and confusing as it was.

**Comment by vtjnash** [comment]
Eventually I loaded that PR up in a debugger on the CI worker and stepped through the code until I observed the source of the failure.
