### ISSUE TITLE
USE_BINARYBUILDER* has no effect in Make.user

### ISSUE THREAD

**Issue by owainkenwayucl** [JuliaLang/julia#33880]
With Julia 1.2.0 on RHEL 7.x I ran across this issue: https://github.com/JuliaLang/julia/issues/31555

In attempting to resolve it, I determined that setting any of the `USE_BINARYBUILDER*` options (e.g. `USE_BINARYBUILDER`, `USE_BINARYBUILDER_LIBUV` options in `Make.user` had no effect on the build process - `make` still uses the binary versions of the library triggering the bug.  Adding those options to `Make.inc` however does result in them taking effect. 

`Make.user` is being read for other purposes (for example the install location) so it's not an issue that the file has the wrong name/location etc.

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/32044 ? Should work on 1.2 if you use `override` though.

**Comment by owainkenwayucl** [comment]
Possibly.  How did this not make it into 1.2.0?

**Comment by KristofferC** [comment]
The branch for 1.2 was in April and the PR was not marked with the backport label.

**Comment by owainkenwayucl** [comment]
OK - I'll close this on the basis that it'll be resolved in future versions.

**Comment by KristofferC** [comment]
1.3 should be (no jinx plzplz) good to go really soon so shouldn't have to wait long.

**Comment by vchuravy** [comment]
> OK - I'll close this on the basis that it'll be resolved in future versions.

In the mean time you can use `override USE_*`
