### ISSUE TITLE
Union splitting does not update printed type information for code_typed

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#33895]
It seems that inference sometimes ignores types which are statically proven after union splitting (this static information represented as pi nodes).

I discovered this while trying to get good code generated for `eigen()` of static arrays (https://github.com/JuliaArrays/StaticArrays.jl/pull/683), but it also seems to apply to normal arrays as in the following example. Note in particular the pi nodes near the bottom which assert a concrete type such as `Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}`. However when the eigenvalues are extracted with `getfield` on the next line they are still inferred as a `Union`.

```julia
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.467 (2019-11-15)
 _/ |\__'_|_|_|\__'_|  |  Commit 360c10241b* (5 days old master)
|__/                   |

julia> using LinearAlgebra

julia> function foo(M)
           F = eigen(M)
           F.values[1]^2.0
       end
foo (generic function with 1 method)

julia> @code_warntype optimize=true foo(rand(3,3))
Variables
  #self#::Core.Compiler.Const(foo, false)
  M::Array{Float64,2}
  F::Union{Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}, Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}}

Body::Any
1 ─ %1  = Main.eigen::Core.Compiler.Const(LinearAlgebra.eigen, false)
│   %2  = invoke LinearAlgebra.:(var"#eigen#77")(true::Bool, true::Bool, LinearAlgebra.eigsortby::typeof(LinearAlgebra.eigsortby), %1::typeof(eigen), _2::Array{Float64,2})::Union{Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}, Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}}
│   %3  = (isa)(%2, Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}})::Bool
└──       goto #3 if not %3
2 ─ %5  = π (%2, Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}})
│   %6  = Base.getfield(%5, :values)::Union{Array{Complex{Float64},1}, Array{Complex{Float64},2}}
└──       goto #6
3 ─ %8  = (isa)(%2, Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}})::Bool
└──       goto #5 if not %8
4 ─ %10 = π (%2, Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}})
│   %11 = Base.getfield(%10, :values)::Union{Array{Float64,1}, Array{Float64,2}}
└──       goto #6
5 ─       Core.throw(ErrorException("fatal error in type inference (type bound)"))
└──       $(Expr(:unreachable))
6 ┄ %15 = φ (#2 => %6, #4 => %11)::Array
│   %16 = Base.getindex(%15, 1)::Any
│   %17 = (%16 ^ 2.0)::Any
└──       return %17
```

**Comment by Keno** [comment]
This isn't really an optimizer problem. Before inlining, the code looks like:

```
Variables
  #self#::Core.Compiler.Const(foo, false)
  M::Array{Float64,2}
  F::Union{Eigen{Complex{Float64},Complex{Float64},Array{Complex{Float64},2},Array{Complex{Float64},1}}, Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}}

Body::Any
1 ─      (F = Main.eigen(M))
│   %2 = Base.getproperty(F, :values)::Array
│   %3 = Base.getindex(%2, 1)::Any
│   %4 = (%3 ^ 2.0)::Any
└──      return %4
```

We then union-split during inlining, but the inlined function is just the generic `getproperty`. In order to discover the concrete return type, we'd have to re-infer with the split signature, which is not something that we ever do.

**Comment by Keno** [comment]
In other words, it knows the type of the factorization object fine, it just doesn't know what `:values` is other than a `Symbol`.

**Comment by vtjnash** [comment]
Agreed. And even that is a bit of a lie, since we don't update that information before printing because the optimizer doesn't really care about this (this'll happen to eventually get dropped during code_llvm). It's just the red in printing that's making you think it's relevant information.

**Comment by c42f** [comment]
Ok, so a workaround is for the user code to be aware of the problem and pass the union through a function call:

```julia
function foo(M)
    F = eigen(M)
    (F->F.values[1]^2.0)(F)
end
```

I've observed a few more complicated cases where I hoped to get something useful out of union splitting but the generated code wasn't great. The general pattern has been some straight line code where at some stage a variable (let's say `x`) becomes a `Union{A,B}`:

```julia
function bar()
    body1
    x = baz()  # Inferred as Union{A,B}
    body2
end
```

At this point all sorts of things get messy in `body2` if many statements depend on `typeof(x)`.  In particular, if we have a pattern in `body2` such as

```julia
y = f(x)
z = g(x)
w = z + y
```

there's a good chance that the types of `y` and `z` may be correlated but (it seems) the compiler can't reason about this.

The general workaround seems to be to wrap `body2` in a separate function which `x` is passed to. Though it "would be nice" if I didn't need to do this.

```julia
function bar()
    body1
    x = baz()
    ((x)->body2(x))(x)
end
```

**Comment by vtjnash** [comment]
not really a bug, as discussed above, just a feature of how we print it
