### ISSUE TITLE
lcm silently ignores overflows

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#33911]
We currently have the obviously wrong evaluation:
```
julia> lcm(4611686018427387817, 4611686018427387847)
4959
```
The implementation does:
```
checked_abs(a * div(b, gcd(b,a)))
```
using the unchecked `*` is IMO a mistake; it should use one of the following things:
a.   `Base.checked_mul`
b.   `Base.widemul`

**Comment by StefanKarpinski** [comment]
Needs a bit of discussion of whether we want (a) or (b), but after that should be an easy fix.

**Comment by KlausC** [comment]
@StefanKarpinski : surprise regarding the labels;  this is not my first issue.  :+1:

**Comment by rfourquet** [comment]
@KlausC "good first issue" doesn't mean it's the first issue you open, it's to indicate to potentially new contributors that it could be a good first issue for them to tackle.
