### ISSUE TITLE
map over nested structures

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#33920]
I'd like to write something concise to turn

`[(1, 2), ((3, 4), (5, [7, 8]))]`

into

`[(1.0, 2.0), ((3.0, 4.0), (5.0, [7.0, 8.0]))]`

If the structures are "uniformly" nested, one idea from @ssfrr is to e.g. define `fmap(f) = x->map(f,x)`
then

```
x = [(1,2), (3,4)]
fmap(fmap(Float64))(x)
```

You can then use whatever idiom for iterated functions to concisely write deeply but uniformly nested structures.

For non-uniformly nested structures, there's a question about how deep to apply the function. I'm not sure what a good generic API for what I want would be.

Related:
https://github.com/JuliaLang/julia/issues/32081#issuecomment-494648042
https://github.com/JuliaLang/julia/issues/32796
https://github.com/JuliaLang/julia/issues/20502

**Comment by mikan2087** [comment]
```
ffmap(f, x::Int) = f(x)
ffmap(f, x::Union{Tuple, Array}) = map(y -> ffmap(f, y), x)

x = [(1, 2), ((3, 4), (5, [7, 8]))]
ffmap(Float64, x)
```
Like this?

**Comment by mcabbott** [comment]
Sounds like another reason to want  #24990, with which you could write `map(map(f, _), xs)`, I think.

**Comment by brenhinkeller** [comment]
Between the suggestion above and the zillion underscore proposals and PRs out there, I _think_ we can close this but feel free to undo if anyone disagrees!
