### ISSUE TITLE
whos() should print the memory usage of the objects

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#3393]
Currently, whos() prints only the size of the objects in memory. It would be nice to have it print the total memory consumed by an object. This would be really useful for `Array{Any}`, for example. It would also be nice to have total memory utilization of all objects printed as part of the `whos()` output.

Is there a way to get the total memory usage by an object? I faintly remember having something like `getnbytes`, but can't find it any more.

**Comment by samuela** [comment]
+1

**Comment by timholy** [comment]
Cross-referencing #7603, which claims to only need to be turned from a gist into a PR.
