### ISSUE TITLE
Allow choosing what stdlibs to include when creating sys.ji

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33963]
The set of standard libraries are hardcoded into `sysimage.jl`:

https://github.com/JuliaLang/julia/blob/81fb410656acabf93c9152903723ca9bb32f88c5/base/sysimg.jl#L20-L50

In some cases (like when creating "apps"), a subset of these stdlibs might not be needed. Having a more flexible way to chose what stdlibs should be included might be a good idea.

**Comment by DilumAluthge** [comment]
Could this be a configurable option?

I personally would always like all stdlibs available in my images. Perhaps there could be a keyword argument or something that I can specify `include_all_stdlibs = true` that will allow me to include all the stdlibs?

**Comment by KristofferC** [comment]
The default would not change so there is no need for such an option.

**Comment by DilumAluthge** [comment]
> The default would not change so there is no need for such an option.

Perfect!
