### ISSUE TITLE
Julia 1.3 Multiplication result error

### ISSUE THREAD

**Issue by ChangeHg** [JuliaLang/julia#33969]
![julia](https://user-images.githubusercontent.com/26839057/69786944-686fb600-11f6-11ea-9724-be40d2e71091.png)
![julia_1](https://user-images.githubusercontent.com/26839057/69787192-f186ed00-11f6-11ea-871c-e340198c5009.png)

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/. https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678 might interest you.
