### ISSUE TITLE
[Feature Request] Support for nested parametric dispatch

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#33976]
Currently, we can dispatch on patterns like 
```julia
f(::U{Int}) where {U} = ... 
```
and we can also dispatch on patterns like 
```julia
f(::Vector{T}) where {T} = ...
```
 but we are unable to dispatch on patterns like 
```julia
f(::U{T}) where {U, T} = ...
```
I'm not exactly sure what to call this, the best name I have is "nested parametric dispatch". 

This is a pretty niche dispatch pattern, which is likely why I can't find any issues where people complain about it's absence, but I think it does have value. For instance, in the case of re-parameterizing types. A user on slack yesterday was asking how to write a function `f` such that say `f(Float64, Foo{Int}) == Foo{Float64}`. The first method that came to my mind to try to do this was:
```julia
julia> f(::Type{T′}, ::Type{U{T}}) where {U, T, T′} = U{T′}
ERROR: TypeError: in Type{...} expression, expected UnionAll, got TypeVar
Stacktrace:
 [1] top-level scope at REPL[96]:1
```
which of course is not supported. 

I spent some time trying to think about ambiguities or problems with allowing this, but failed to find anything serious so I figured I should submit an issue to be tracked.

**Comment by MasonProtter** [comment]
The main thing about this which is non-obvious would be if I wrote
```julia
f(::Type{U{T}}) where {U, T} = (U, T)
```
what would be the output of `f(Ref{Complex{Float64}})`? I think one could argue that this would preferably be `(Ref, Complex{Float64})`, but it's also not immediately obvious that it shouldn't be `(Ref{Complex}, Float64)`

**Comment by yuyichao** [comment]
> Currently, we can dispatch on patterns like
>
> `f(::U{Int}) where {U} = ... `

I don't believe this is the case and I believe this won't be supported since @JeffBezanson believe this will make dispatch undecidable.

**Comment by MasonProtter** [comment]
My mistake, for some reason I thought I had tested that.

**Comment by yuyichao** [comment]
The previous discussion is in the cryptically named issue https://github.com/JuliaLang/julia/issues/15791 ....

Please see the discussion here. I'll close since I think the conclusion is that using this in dispatch cannot be reasonably added. Using it in field is fine and is partially supported through Jameson's package.

**Comment by MasonProtter** [comment]
I'm not sure I fully grasp the relevance of that discussion to this issue. It seems to focus on defining types whereas I'm concerned about dispatching. 

Furthermore, as far as I can tell, Jeff's concern that 
```
typealias Loop{X} X{X}

Loop{Loop}
```
wouldn't terminate doesn't seem that bad. `f(x) = f(x)` also doesn't terminate, it just hits a stackoverflow. Couldn't we do the same for types that blow up?

**Comment by JeffBezanson** [comment]
I think it really changes the "feel" of Julia types if application might not terminate. As it is, every type has to express some sort of fixed apparent meaning, not a process where the calls use curly braces instead of parens.
