### ISSUE TITLE
 Julia negative Exponentiation conflicts with emitted llvm code [BUG]

### ISSUE THREAD

**Issue by rahulghangas** [JuliaLang/julia#33982]
3^(-5) gives a Float64 of value 0.004115226337448558

while

@code_llvm ^(3, -5) emits the following llvm code 
```
;  @ intfuncs.jl:221 within `^'
define i64 @"julia_^_11097"(i64, i64) {
top:
  %2 = call i64 @julia_power_by_squaring_990(i64 %0, i64 %1)
  ret i64 %2
}
```
which indicates that the function has an integer return type.

The output of versioninfo() is as follows-
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/21014

**Comment by rahulghangas** [comment]
Hi, sorry but I'm having trouble seeing how this is a duplicate of the aforementioned issue. Can you explain?

**Comment by yuyichao** [comment]
The macro isn't showing you the correct function.

**Comment by rahulghangas** [comment]
Right, Thanks
