### ISSUE TITLE
missing tab-completion help for emoji

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#34006]
As reported [on discourse](https://discourse.julialang.org/t/hover-over-latex-unicode-character-to-see-the-latex-sourcecode/31749/3?u=stevengj), the REPL help doesn't show tab completion info for emoji even when it exists, unlike for other Unicode completions:
```jl
help?> α
"α" can be typed by \alpha<tab>
search:

Couldn't find α
Perhaps you meant !, %, &, *, +, -, /, :, <, >, \, ^, |, ~, ÷, π, ℯ, ∈, ∉ or ∋
  No documentation found.

  Binding α does not exist.

help?> 👍
search:

Couldn't find 👍
Perhaps you meant !, %, &, *, +, -, /, :, <, >, \, ^, |, ~, ÷, π, ℯ, ∈, ∉ or ∋
  No documentation found.

  Binding 👍 does not exist.
```
even though `👍` is produced by tab completion of `\:+1:`

**Comment by stevengj** [comment]
The reason for this is that the emoji completions are in a separate list `REPL.REPLCompletions.emoji_symbols` from the latex completions `REPL.REPLCompletions.latex_symbols` for some reason., but the [completions help only uses the latter](https://github.com/JuliaLang/julia/blob/7024cdab3c34e6638c870e655b87f702f99a1d0f/stdlib/REPL/src/docview.jl#L240-L248).

Should be trivial to fix.  For example, just replace [this line](https://github.com/JuliaLang/julia/blob/7024cdab3c34e6638c870e655b87f702f99a1d0f/stdlib/REPL/src/docview.jl#L243) with
```jl
for (k,v) in Iterators.flatten(Base.REPL_MODULE_REF[].REPLCompletions.latex_symbols,
                               Base.REPL_MODULE_REF[].REPLCompletions.emoji_symbols)
```

**Comment by utkarsh2102** [comment]
I'll take a stab at this :taco:
