### ISSUE TITLE
want to be able to run globally julia REPL 

### ISSUE THREAD

**Issue by risa0320** [JuliaLang/julia#34001]
When installing from “Building Julia” on the TOP page of github (https://github.com/JuliaLang/julia),
  It can be started with ./julia in the repository of git cloned julia.
Julia can't be started without choosing the current location that was made when installing with binary.
It would be great for developers to be able to start from any location.
If you already have a way to make this happen, please let me know.

●try install & make

```
$ git clone git://github.com/JuliaLang/julia.git
$ git checkout v1.3.0
$ make
$ cd ~/.julia && ./julia
$ ./julia
              _
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
 (_)     | (_) (_)    |
  _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
 | | | | | | |/ _` |  |
 | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
_/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```

●except

```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0 (2019-11-26)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> 
```

●actually

```
$ julia
-bash: julia: command not found
```

**Comment by KristofferC** [comment]
Like with any program you need to add the folder where the julia executable is to your `PATH` (or alternatively, make a symlink to julia into some folder that already is in `PATH`, like `sudo ln -s /home/user/julia/julia /usr/local/bin/julia`.
