### ISSUE TITLE
Vector instantiation bug

### ISSUE THREAD

**Issue by pdimens** [JuliaLang/julia#34010]
Hello, I posed this question to the Julia Slack channel and @MasonProtter suggested it was a bug and that I open a new issue here. The issue is as follows:

I am attempting to instantiate a vector of empty vectors that are all Typed to be populated later. 
```julia
julia> x = [Vector{String}(),
            Vector{Int}(), 
            Vector{Int8}(), 
            Vector{Union{Missing,Real}}()]
ERROR: UndefVarError: S not defined  
```
In an effort to troubleshoot, I tried instantiating the vectors individually, which was successful, and then I built this vector `x` by adding the internal vectors one at a time.

```julia
julia> x = [Vector{String}()] ;

julia> x = [Vector{String}(),
            Vector{Int}()] ;

# etc.
```
The issue seems to be when adding `Vector{Union{Missing, Real}}()` or `Vector{Union{Missing, T} where T <: Real}()`. If replacing `Real` with a concrete type such as `Float64` or `Int`, the Vector `x` seems to be instantiating successfully. The question is, where does this variable `S` come from and why does it prevent the instantiation of the third vector?

**Comment by GregPlowman** [comment]
This works for me on Julia v1.3.0 (and also v1.2.0, v1.1.1, v1.0.5)
```
Julia-1.3.0> x = [Vector{String}(),
                         Vector{Int}(),
                         Vector{Int8}(),
                         Vector{Union{Missing,Real}}()]
4-element Array{Array{T,1} where T,1}:
 String[]
 Int64[]
 Int8[]
 Union{Missing, Real}[]
```
Have you tried in a fresh REPL?

**Comment by pdimens** [comment]
Thanks for getting back to me so soon, Greg. I just tried it in a fresh REPL via linux terminal and through the Juno REPL and it worked both ways (Julia v1.2). What's odd is that when I had this issue last night, I killed the session and restarted it three times, each time getting that same `S` error. Ultimately, I can't seem to reproduce this same error today.
