### ISSUE TITLE
Non-copying repeat(A::AbstractArray, counts::Integer...)

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#34029]
It would be great to have a version of `repeat(A::AbstractArray, counts::Integer...)` that doesn't copy, and just produces a view to the original with repeated indices. Say `repeatview` i.e.
```
julia> a = zeros(4,1)
4×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
julia> b = repeatview(a, inner=[1,4])
4x4 view(::Array{Float64,2}, ??, ??) with eltype Float64:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
julia> b[1, 4] = 1
4x4 view(::Array{Float64,2}, ??, ??) with eltype Float64:
 1.0  1.0  1.0  1.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
julia> a
4×1 Array{Float64,2}:
 1.0
 0.0
 0.0
 0.0
```
If being able to allocate back to the parent isn't viable at this stage, then at least being able to read would be nice.

cc @timholy given this might be more of an image-family function?

**Comment by mcabbott** [comment]
One solution using packages looks like this:
```julia
julia> using LazyArrays, FillArrays

julia> f14 = Fill(true, 1,4)
1×4 Fill{Bool,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}:
 1  1  1  1

julia> A = rand(3);

julia> LazyArray(@~ A .* f14)
3×4 BroadcastArray{Float64,2,typeof(*),Tuple{Array{Float64,1},Fill{Bool,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}}}:
 0.429907  0.429907  0.429907  0.429907
 0.244365  0.244365  0.244365  0.244365
 0.728861  0.728861  0.728861  0.728861

julia> ans == repeat(A, outer=(1,4))
true
```

**Comment by ianshmean** [comment]
Thanks! That works really well and efficiently
Having something like this is base would be great

**Comment by nalimilan** [comment]
Note that the signature shouldn't conflict with https://github.com/JuliaLang/julia/pull/29560.

**Comment by vtjnash** [comment]
This does sound like a package feature (e.g. LazyArrays). I'm not opposed to including it in base, I just don't think we need the feature request issue open.
