### ISSUE TITLE
Export commands do not give errors when you miss commas

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#34021]
If you do 
```julia
include("file.jl")
export
   test
   test1
```

it doesn't give an error but it doesn't export the 2nd function. This seems weird to me.

**Comment by yuyichao** [comment]
Thus is valid syntax and this kind of issue is the best for a linter.

**Comment by logankilpatrick** [comment]
Why is this valid syntax? That’s my point; Maybe it shouldn’t be valid.

**Comment by yuyichao** [comment]
It's valid syntax because `test1` is valid syntax. I can't check right now but I think if you put everything on the same line it will be an error.

**Comment by ararslan** [comment]
Yichao is right. You can't even finish a module definition at the REPL with this syntax before encountering an error:
```
julia> module M
       export a b
ERROR: syntax: extra token "b" after end of expression
Stacktrace:
 [1] top-level scope at REPL[6]:0
```

**Comment by logankilpatrick** [comment]
right but 
```
module M
       export 
          a 
          b
```
is valid

**Comment by logankilpatrick** [comment]
even though b is not actually exported

**Comment by StefanKarpinski** [comment]
Right, you're evaluating `b` on a line by itself. Not sure there's anything we can do about this.

**Comment by logankilpatrick** [comment]
I am just making things up that may not be possible but why not just do something under the hood to evaluate the exports on the same line

**Comment by logankilpatrick** [comment]
```
julia> module M
       export a,b
       end
Main.M

julia> module M
       export a b
       end
ERROR: syntax: extra token "b" after end of expression
Stacktrace:
 [1] top-level scope at REPL[2]:0

```

**Comment by logankilpatrick** [comment]
that way if there's a missing comma it errors out rather than acts as if all is well

**Comment by StefanKarpinski** [comment]
```jl
export a
b
```
already means something: it means `export a; b` — it exports `a` and then evaluates `b`.

**Comment by logankilpatrick** [comment]
Got it. Just wanted to voice my thought. Thanks for the feedback/time!
