### ISSUE TITLE
Julia segfaults on start

### ISSUE THREAD

**Issue by amca01** [JuliaLang/julia#34028]
I'm following instructions from the docs at https://docs.julialang.org/en/v1/devdocs/backtraces/ here.  So I've run `strace julia` and uploaded the output to 

https://gist.github.com/amca01/9435608999c69042116011dca84d7803

I'm running Julia 1.2.0 under Arch linux.  I suppose I could delete Julia from my system and reinstall it, but that seems a bit of an overkill.  Anyway, I'm hoping that somebody might enlighten me...

**Comment by StefanKarpinski** [comment]
How did you install Julia?

**Comment by PallHaraldsson** [comment]
I would download the generic Linux download for Julia 1.3 (and/or 1.0.x) from https://julialang.org/downloads/

You can have those and Julia 1.2 installed at the same time. But it's strange how this happened. Julia 1.2 is no longer supported, nor by Arch:

https://www.archlinux.org/packages/?name=julia&sort=flag_date

I would be curious also if this actually works:

https://snapcraft.io/install/julia/arch

I see you have LLVM from the system (but Julia uses heavily patched versions). Possibly it's that or other dependency?

$ ls -lrt /home/qwerty/julia-1.3.0-alpha/lib/julia/libLLVM-6.0.so /snap/p7zip-desktop/163/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so*
lrwxrwxrwx 1 root   root         16 jún  7  2018 /snap/p7zip-desktop/163/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so -> libLLVM-6.0.so.1
-rw-r--r-- 1 root   root   60712920 jún  7  2018 /snap/p7zip-desktop/163/usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
-rwxr-xr-x 1 qwerty qwerty 50126624 júl 23 02:17 /home/qwerty/julia-1.3.0-alpha/lib/julia/libLLVM-6.0.so

**Comment by amca01** [comment]
Thanks folks.  In the end I uninstalled Julia (using the package manager) and installed the generic Linux binary from the Julia downloads page.  And now it works fine.  The 1.2.0 version must have been the result of a recent system upgrade.  As to LLVM, `versioninfo()` returns:

    Julia Version 1.3.0
    Commit 46ce4d7933 (2019-11-26 06:09 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

I have no idea whether that's good, bad, or something else.  But at least I now have a working system.

Thank you all again.

**Comment by goggle** [comment]
@amca01 I also have have `julia-1.2.0-2` from Arch Linux installed, but I cannot reproduce this. Did you get that error just by starting julia, i.e. typing
```
$ julia
```
in your terminal emulator? Or did you do something else to trigger that error?
