### ISSUE TITLE
Possible type inference bug in Julia 1.3.0?

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaLang/julia#34032]
@AshtonSBradley reported an issue https://github.com/JuliaApproximation/FastTransforms.jl/issues/95 where tests in FastTransforms.jl were hanging. Tests never hung for me locally nor in CI, but I believe we sidestepped the issue by essentially unrolling a `for T in (Float64, Complex{Float64})` loop over two types.

The issue exists on FastTransforms v0.8.1 with the following `versioninfo()`
```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by MikaelSlevinsky** [comment]
On second thought, my tests had a type instability that didn't need to be there.

**Comment by JeffBezanson** [comment]
A type instability shouldn't cause inference to hang though.
