### ISSUE TITLE
Add Object Oriented programming section to Docs- Manual

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#34036]
I was looking through the manual and it seems like one of the core things that is not in the manual is Object Orientated Programming which Julia seemingly supports through structs. It might be good to talk about it as part of the "Manual" https://github.com/JuliaLang/julia/tree/master/doc/src/manual given other's coming from different languages might look for it.

**Comment by ViralBShah** [comment]
Not sure what should be done here. We have differences from existing languages, and can have something in the FAQ if necessary. Could also be the topic of a blog post.
