### ISSUE TITLE
Document how to use the external Git dependencies for standard libraries (e.g. Pkg, Statistics)

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#34044]
cc: @StefanKarpinski @vtjnash @staticfloat @fredrikekre 

Some snippets from Slack: 

> By default, it only uses the `_SHA1` value.  To use the `_BRANCH` value, you have to set the makevar `DEPS_GIT=1`
> That's all controlled here: https://github.com/JuliaLang/julia/blob/master/deps/tools/git-external.mk

> You need to set the SHA value to ‘master’ to build the HEAD
> Setting DEPS_GIT=Pkg (in addition) is perhaps more ‘standard’ though, since it gives you more tools to edit it (eg all of git)
> BRANCH we just need as the ‘pretty’ name. Eg you’ll notice for most deps it’s the version number as stores in git

> it would be nice if this was documented anywhere, since this has existed for at least five years and I have no idea how to use it except as a really confusing way to include external dependencies

**Comment by StefanKarpinski** [comment]
@vtjnash: since you implemented this, I've assigned you.

**Comment by StefanKarpinski** [comment]
That said, if someone else wants to document their understanding of it and ask @vtjnash for a review, that's a totally acceptable way to get this done as well.

**Comment by DilumAluthge** [comment]
This has been done for a while: https://github.com/JuliaLang/julia/blob/f3d505d957f22a03b973b9f3a49890c00765b2d7/doc/src/devdocs/build/build.md#building-julia-from-source-with-a-git-checkout-of-a-stdlib
