### ISSUE TITLE
Add option to `escape_string` to avoid already escaped characters

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#34042]
Hi!

In PrettyTables.jl, sometimes it happens that a string has already some characters escaped, like `\\cdot`, but others not, like `\n`. However, I need to call `escape_string` every time  to handle the other non-escaped characters (like `\n`), otherwise the output will break badly.

For example, if I try to pass to PrettyTables.jl a cell that has a LaTeX equation:

```julia
data = [ "\$ 10 \\cdot 20$" ]
```

then it will print:

```
$ 10 \\cdot 20 $"
```

because `escape_string` always treat `\\` as two backslashes instead of one escaped backslash.

To solve this problem, I needed to copy the entire `escape_string` function and remove the line that transform `\\` into `\\\\`. It would be nice, IMHO, if Julia's  `escape_string` has a keyword option to assume `\\` as an already escaped backslash.

If this is accepted, I can submit a PR.

**Comment by rohanxyzg** [comment]
Hi, 
I would like to work on this issue.
Thanks

**Comment by ronisbr** [comment]
Hi @rohanxyzg !

I was about to submit a PR addressing this issue :)

**Comment by ronisbr** [comment]
Done!
