### ISSUE TITLE
keyword argument functions and closures

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#34051]
Keyword argument function lowering and closures seem to interact in a surprising way.

```julia
# no surprises
function invocation_counter(f)
    counter = 0
    function g(args...)
        counter = counter + 1
        return f(args...)
    end
    return g
end

rand_count = invocation_counter(rand)
rand_count.counter    # Core.Box(0)


# surprises
function invocation_counter2(f)
    counter = 0
    function g(args...; kwargs...)
        counter = counter + 1
        return f(args...; kwargs...)
    end
    return g
end

rand_count2 = invocation_counter2(rand) 
rand_count2.counter # ERROR: type #g#17 has no field counter
```

I wasn't able to predict this behavior from the description at: https://docs.julialang.org/en/v1/devdocs/functions/#Keyword-arguments-1 

possibly related: https://github.com/JuliaLang/julia/issues/30908

**Comment by JeffBezanson** [comment]
The only public interface of functions you can rely on is calling them. The best thing to do here is either declare your own struct type, or return an accessor function (`()->counter`).
