### ISSUE TITLE
StackOverflowError causing bus error in Julia 1.3

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#34050]
I happened to write a code that will cause `StackOverflowError`. On the official release of Julia 1.0 this is fine, I got an `StackOverFlowError`, but on 1.3
this cause my julia compiler crash. 

My Julia 1.3 versioninfo

```jl
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

You should be able to reproduce this by clone YaoBlocks.jl and checkout the `noise` branch at commit `e220222e1e4a8ee585c57e44cea231d3ae5c8c9b`

or the following command

```jl
https://github.com/QuantumBFS/YaoBlocks.jl.git YaoBlocks
cd YaoBlocks
git checkout noise
git checkout e220222e1e4a8ee585c57e44cea231d3ae5c8c9b
julia --project
```

then

```jl
using YaoBlocks
UnitaryChannel([X, Y, Z])
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/17109

(The fact that it works for you on 1.0 and not 1.3 is just luck AFAICT. The issue has always been there.)
