### ISSUE TITLE
Why is issue #11331 marked as closed when there is no solution

### ISSUE THREAD

**Issue by compleathorseplayer** [JuliaLang/julia#34058]
This happens repeatedly on here... the issues get taken over by developers with a resolution to improve future releases, but meanwhile present users are left without a solution.
I have installed Julia on Ubuntu and can't get it to set the home directory.   I am glad this will be fixed in future but what do I do now???
There seems to be a lively discussion for developers only about the error:
Base.InitError(mod=:Base, error=Base.KeyError(key="HOME"))
What about users?

**Comment by fredrikekre** [comment]
Can you include more information? What Julia version? What is the (full) error message? The issue you are referencing is closed because it was fixed by https://github.com/JuliaLang/julia/pull/19636

**Comment by timholy** [comment]
(and it was released in Julia 0.6 and higher)

**Comment by JeffBezanson** [comment]
Typically we address issue reports by fixing the underlying problem in the software, and eventually releasing a new version containing the fix. If you need to use a specific version and so can't fix the problem by upgrading, it would make sense to go to the original issue report and ask for a workaround. Unfortunately though, workarounds are not always possible.

The discussions here are not for developers only; it's fine for anybody to ask questions or ask for help, though sometimes the discourse forum is more useful for that.

If you haven't already, try installing an official binary from https://julialang.org/downloads/. Sometimes julia installs from other sources are very old versions or don't work.

**Comment by StefanKarpinski** [comment]
The issue in question, so others can just click a link: https://github.com/JuliaLang/julia/issues/11331.

**Comment by compleathorseplayer** [comment]
I managed to find a solution, which was not contained in the previous closed discussions.
The basic issue was that the environment variable $HOME was not set (this may seem obvious to those more experienced, and it was never specifically highlighted in the discussions).   If one uses Julia on an anonymous server (as I was, in this case), one may need to manually, explicitly set $HOME to what is should be as an environment variable each time julia is to be invoked.

**Comment by StefanKarpinski** [comment]
If you use an up-to-date Julia, this shouldn't be an issue. Please let us know if you encounter issues with more recent versions of Julia.
