### ISSUE TITLE
[feature request] @test broadcast over arrays

### ISSUE THREAD

**Issue by kkmann** [JuliaLang/julia#34071]
Hi, 

first of all, thanks for all the work going into the Julia 'infrastructure packages' - might not be the coolest stuff to do but certaily appreciated!

So, I find myself writing a lot of `@test all( f.(x) .== a )` statements and was wondering whether there is already a way of broadcasting test results that I missed (sorry), a reason for not allowing that, or interest in supporting `@test_xyz f.(x) .== a` natively.

Best wishes,

Kevin

**Comment by mbauman** [comment]
In general we shy away from "truthiness" — things are either `Bool` or they're not eligible for use in an `if` branch.  And `@test` currently fits right in with that, simply ensuring that the expression evaluates to `true`.  I don't see that changing, especially as it'd make some tests that _should_ currently fail pass.  I suppose that's technically the opposite of a breaking change, but in the context of a test suite it's not something you want to regress!

As for whether it's worth adding a `@test_all x`, I'm not sure it adds much over `@test all(x)`.

**Comment by kkmann** [comment]
ok thanks for the clarification, @test_all would indeed just save one char, so maybe not quit worth it ;)
