### ISSUE TITLE
Reducing over structs

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#34083]
```Julia
struct A
   f::Vector{Int}
end
as = [A(rand(1:100, 3)) for _ ∈ 1:5]

reduce((x, y) -> x.f ∪ y.f, as)
```
throws an error
```Julia
ERROR: type Array has no field f
```
which to me seems like a bug, especially, given that the following works:
```Julia
mapreduce(x -> x.f, ∪, as)
```
and the two are equivalent to me.

**Comment by fredrikekre** [comment]
The first call returns an `Array` which does not have a `.f` field.
