### ISSUE TITLE
kron(Diagonal, SparseMatrixCSC) is not sparse

### ISSUE THREAD

**Issue by Timeroot** [JuliaLang/julia#34087]
The operations,
`M = sparse([3,5,7],[1,2,4],[7.1,3.2,9.0])`
`M2 = I(20)`
`typeof(kron(M2,M))`
return `Array{Float62,2}`. Since `UniformScaling` is inherently a sparse operator, `M` is a sparse matrix, and the Kronecker product preserves sparseness, the product should also be sparse. Currently, kron(SparseMatrixCSC, SparseMatrixCSC) does produce another SparseMatrixCSC, which is why this was unexpected. Would be nice to not accidentally densify everything like this.

I'm on Julia 1.2.0.

**Comment by ViralBShah** [comment]
Yes, that's right. Maybe we just should convert the Diagonal to sparse and dispatch to kron(sparse,sparse). @Timeroot Want to submit a PR?

**Comment by Timeroot** [comment]
Oops, silly me, it's already in there -- see Pull Request #32793. Closing.
