### ISSUE TITLE
Unindentation in triple-quoted strings affected by explicitly written newline (\n)

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#34105]
```julia
let str = "\n   yoyo"
        println("1: ")
        println("""begin line: interpolate:$str
        begin next line:""")
end

let str = "   yoyo"
        println("2: ")
        println("""begin line: interpolate:\n$str
        begin next line:""")
end
```

produces
```
1: 
begin line: interpolate:
   yoyo
begin next line:
2: 
begin line: interpolate:
   yoyo
        begin next line:
```

But I had expected both blocks of outputs under `1:` and `2:` to be the same. I did not expect `"\n"` (in the string) to be treated the same as `\n` (in the file) within a triple-quoted string.

(kind of dual error of https://github.com/JuliaLang/julia/issues/7165)

**Comment by JeffBezanson** [comment]
Yes, this is a bug. It happens because we do unescaping before unindenting. I ran into this fixing #34967, where the same bug prevents you from using escapes to write an invalid string with triple quotes.
