### ISSUE TITLE
possible wrong use of time()

### ISSUE THREAD

**Issue by nico202** [JuliaLang/julia#34115]
https://github.com/JuliaLang/julia/blob/ba4f858cd0618e209b81a1800005662769cdc1c1/stdlib/Distributed/src/cluster.jl#L1027

Hi! I was trying to add support to [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/). I patched the file /src/support/timefuncs.c, compiled and everything went well. All tests were successful, but they never ended. I saw in julia src many uses of time() like the one above.

However, time() is a wrapper for `gettimeofday`. According to the man page
> The time returned by gettimeofday() is affected by discontinuous jumps in the system time (e.g., if the system administrator manually changes the system time). If you need a monotonically increasing clock, see clock_gettime(2))

there are jumps. Shouldn't julia use in those situations `time_ns()` (wrapper for libuv `uv_hrtime` that has [no drift](http://docs.libuv.org/en/v1.x/misc.html#c.uv_hrtime)?)

@StefanKarpinski this follows the other time-related error #34056 

Thanks, Nicolò

**Comment by Keno** [comment]
Yep, I think you're correct.

**Comment by nico202** [comment]
Couple more (wrong) uses I could find, but sure there are more:
https://github.com/JuliaLang/julia/blob/220681f21fc5aaf83b7c3aee0a2b8d6186805b2c/contrib/generate_precompile.jl#L182
https://github.com/JuliaLang/julia/blob/4f19dc27cc3290f4044e2a50190c5ffec920b0b8/stdlib/Profile/test/runtests.jl#L21
https://github.com/JuliaLang/julia/blob/b580e34b10d01a245ccab88a2d4fa87906540e00/stdlib/Sockets/test/runtests.jl#L386

**Comment by nico202** [comment]
A bit OT, but can somebody with a better understanding of the code caching help me find how julia adds the timestamp to the cache file? I found the place where it is _read_ here:
https://github.com/JuliaLang/julia/blob/3608c84e6093594fe86923339fc315231492484c/base/loading.jl#L1292

But I think it is stored in some C code, right? I suppose it's here
https://github.com/JuliaLang/julia/blob/1e39c69a550c9be945db2ccf1ab6ded02c404ec4/src/dump.c#L1336
But I have difficulties finding back where it is read. It does not seems to be a `time()` call, I'm a bit lost

**Comment by JeffBezanson** [comment]
Thanks, @nico202 . Would you mind opening a PR with your changes?

**Comment by nico202** [comment]
Hi @JeffBezanson, my patch is for fixing reproducibility issues of precompilation (by using the time stored in the env variable SOURCE_DATE_EPOCH, if defined, instead of relying on file's mtime). I also need to check for other sources of non-reproducibility, so my patch isn't ready yet.

But I can submit a PR for time as well
