### ISSUE TITLE
Compatibility for overriding `cld`/`fld`

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#34134]
The implementation on current master (see below) claims to provide compatibility for overriding `cld`/`fld`, but actually doesn’t (at least in the case of [HalfIntegers.jl](https://github.com/sostock/HalfIntegers.jl), which is currently [broken on master](https://travis-ci.com/sostock/HalfIntegers.jl/jobs/267409184#L236) for this reason).

https://github.com/JuliaLang/julia/blob/8707744ae5f778c005d6c29342fe01cb654527af/base/div.jl#L223-L233

HalfIntegers.jl defines `fld(x::T, y::T) where T<:HalfInteger`. Due to the changes on master, this method isn’t called anymore when `fld` is called with two different types of `HalfInteger`s. In order for the above code to fulfill its purpose, the first two and last two methods above could be replaced with
```julia
fld(x::Real, y::Real) = fld(promote(x,y)...)
cld(x::Real, y::Real) = cld(promote(x,y)...)
fld(x::T, y::T) where {T<:Real} = div(x, y, RoundDown)
cld(x::T, y::T) where {T<:Real} = div(x, y, RoundUp)
```

**Comment by Keno** [comment]
Yeah, this fallback doesn't work 100% of the time, but your suggestion doesn't work either, because it would cause dispatch loops due to the reverse fallbacks elsewhere in the code. This is the best I could come up with for the time being. Packages were quite inconsistent about how these methods were being overloaded. I'd recommend additionally defining `fld(x::HalfInteger, y::HalfInteger)` and the three-argument div method in your package.

**Comment by sostock** [comment]
Ok, if compatibility cannot be achieved for all packages, I will update my package and mark old versions as incompatible with Julia 1.4.

However, I came across a problem while updating HalfIntegers. The code now reads like this:
```julia
@static if VERSION < v"1.4.0-DEV.208"
    Base.div(x::T, y::T) where T<:HalfInteger = div(twice(x), twice(y))
    Base.fld(x::T, y::T) where T<:HalfInteger = fld(twice(x), twice(y))
    Base.cld(x::T, y::T) where T<:HalfInteger = cld(twice(x), twice(y))
else
    Base.div(x::T, y::T, r::RoundingMode) where T<:HalfInteger = div(twice(x), twice(y), r)
end
```
When I test this on master, the new `div` method isn’t called:
```
div/fld/fld1/cld/rem/mod: Error During Test at /home/sebastian/Development/HalfIntegers.jl/test/runtests.jl:1042
  Test threw exception
  Expression: fld(HalfInt64(7 / 2), HalfInt64(3 / 2)) == 2
  MethodError: no method matching div(::Half{Int64}, ::Half{Int64}, ::RoundingMode{:Down})
  Closest candidates are:
    div(::T, ::T, ::RoundingMode) where T<:HalfInteger at /home/sebastian/Development/HalfIntegers.jl/src/HalfIntegers.jl:82
    div(::Real, ::Real, ::RoundingMode) at div.jl:237
    div(!Matched::Missing, ::Number, ::RoundingMode) at missing.jl:121
    ...
  Stacktrace:
   [1] fld(::Half{Int64}, ::Half{Int64}) at ./div.jl:232
```
To my understanding, the first method of the “closest candidates” should be called. Do you have an idea what’s wrong here?
