### ISSUE TITLE
Julia 1.3.0 MacOS crash - "pointer being freed was not allocated"

### ISSUE THREAD

**Issue by georgemarrows** [JuliaLang/julia#34133]
When running the Julia 1.3 app downloaded today from https://julialang.org/downloads/, I get:
```
18:18 $ exec '/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia'
julia(12360,0x10c43e5c0) malloc: *** error for object 0x7fd27dd12518: pointer being freed was not allocated
julia(12360,0x10c43e5c0) malloc: *** set a breakpoint in malloc_error_break to debug

[Process completed]
```

The same crash happens when running directly from a shell:
```
18:12 $ /Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia 
julia(12926,0x11872d5c0) malloc: *** error for object 0x7fa32d415168: pointer being freed was not allocated
julia(12926,0x11872d5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

Here's my Mac version:
```
18:29 $ uname -a
Darwin Georges-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
![image](https://user-images.githubusercontent.com/5624098/71100073-67162580-21c5-11ea-9c21-09c7569cf56b.png)

**Comment by StefanKarpinski** [comment]
I'm on 10.14.6 (18G87) and it opens fine for me when run as `/Volumes/Julia-1.3.0/Julia-1.3.app/Contents/Resources/julia/bin/julia`. However, when I double-click the application it doesn't open. Not sure if the issue is related or not. Are you running any anti-virus software?

**Comment by georgemarrows** [comment]
> Are you running any anti-virus software?

No.

**Comment by ViralBShah** [comment]
Can you check your LD_LIBRARY_PATH and equivalents?

**Comment by georgemarrows** [comment]
> Can you check your LD_LIBRARY_PATH and equivalents?

It's not set. To confirm,  if I temporarily reset it and PATH, I still get the same error:
```
LD_LIBRARY_PATH= PATH=  /Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia
```
What other things could I check?

**Comment by georgemarrows** [comment]
Works fine at 1.4 if I reset `DYLD_LIBRARY_PATH` (I've got Rust installed)

```bash
 DYLD_LIBRARY_PATH= /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia
```

**Comment by ViralBShah** [comment]
I almost wonder if we should check for unexpected environment variables and issue a warning.
