### ISSUE TITLE
Race condition in new threading test

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#34141]
As seen in https://build.julialang.org/#/builders/22/builds/7621/steps/2/logs/stdio.

@vtjnash says the test is bad.

**Comment by Keno** [comment]
cc @NHDaly since the test was added in #33119

**Comment by NHDaly** [comment]
Oh yeah, duh, thanks. That is a bad test. I'm testing that the race condition exists without the interpolation, but of course the result of a race condition is .... a race condition, so not a reliable test. Duh. Sorry! :)

I'll fix it by adding some synchronization

**Comment by NHDaly** [comment]
@Keno fixed here: https://github.com/JuliaLang/julia/pull/34142

**Comment by vchuravy** [comment]
Closed in 608567f
