### ISSUE TITLE
Deinstalling Julia - left over files

### ISSUE THREAD

**Issue by Smeargul** [JuliaLang/julia#34153]
I've been updating my Julia version, and therefore used the uninstaller to uninstall the old Julia version. 

During the deinstallation, I had the Julia REPL open. 

The uninstaller however ignored this fact and deleted only a part of the folders from Julia, leaving Julia-1.2.0\bin untouched, as well as the shortcuts.

**Comment by StefanKarpinski** [comment]
I'm not sure if we can do much better than this—Windows won't let you delete files that are in use. If there's a better practice that other installers use, we can certainly implement it.

**Comment by Smeargul** [comment]
I'd be fine with the installer just failing with an error saying "some files are in use. Please close all applications using files in 'whatever_the_path_is' ".

The way it is now, an application might still try to use the (deinstalled) version of Julia, which then might lead to error messages that have you look at the wrong places
(e.g. my IDE for some reason still looked in the deinstalled version, and therefore couldn't find the package LinearAlgebra)

**Comment by vtjnash** [comment]
There's a registry key (HKLM\SYSTEM\ CurrentControlSet\Control\Session Manager\ PendingFileRenameOperations) that implements this, but it's rather dangerous. That's also why many Windows (un)installers need to force you to reboot right away, since delaying it may have unpleasant consequences.
