### ISSUE TITLE
Lower standalone dotted infix operators as anonymous functions

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#34156]
I could've sworn we already had an issue tracking this, but I couldn't find it.  In short, I'd love to have support for standalone `(.+)` and friends to lower to `(args...)->(+).(args...)`.  This would enable their use in higher order functions and generally make them more useful.

They currently parse as identifiers — and can be assigned to! — so this would be a breaking minor change.

**Comment by ararslan** [comment]
Would it be weird to be able to do e.g. `map(.+, a, b)` but not `map(f., a, b)` in general?

**Comment by JeffBezanson** [comment]
It would be nice, at least, to have a non-weird :smile: syntax for that, e.g. `broadcast(f)`. Unfortunately that is already defined to do `f()`, but that is fairly useless.

**Comment by StefanKarpinski** [comment]
Maybe `broadcasted(f)`?

**Comment by mbauman** [comment]
Unfortunately `Base.broadcasted(f)` is simply the lazy version of `broadcast(f)`.  It's similarly varargs and, when materialized, it also means `f()`.
