### ISSUE TITLE
Incorrect link in Compound Expressions documentation

### ISSUE THREAD

**Issue by venuur** [JuliaLang/julia#34158]
The discussion in Compound Expressions

https://docs.julialang.org/en/v1/manual/control-flow/#man-compound-expressions-1

Has a link to Functions but it seems unrelated

https://docs.julialang.org/en/v1/manual/faq/#Functions-1

**Comment by mitra-varuna** [comment]
What should it link to?

**Comment by venuur** [comment]
Looks like it’s referring to this page

https://docs.julialang.org/en/v1/manual/functions/

That page introduces the single line function format very early so it seems appropriate.

**Comment by mitra-varuna** [comment]
Thank you @venuur !
I can work on it; could you please assign it to me.

**Comment by venuur** [comment]
I don't have any permissions on the Julia repo, so tagging @kshyatt .

**Comment by mitra-varuna** [comment]
I submitted a PR to fix this #35546

**Comment by mitra-varuna** [comment]
@kshyatt Do you what are the next steps for getting this into the code line? I see that all this PR has cleared the automated tests.
