### ISSUE TITLE
Problem with download `function` on Windows

### ISSUE THREAD

**Issue by 4nds** [JuliaLang/julia#34178]
Function `download` from base/download.jl doesn't work for me. When I call `download` it tries to use PowerShell to download files so I searched online for solution and found that others have the same problem when using PowerShell to download files in julia but with no solution to the problem. So I looked at source code of download.jl (https://github.com/JuliaLang/julia/blob/master/base/download.jl) and realized that julia can use curl, wget or fetch instead of PowerShell and that actually curl is used as preferred choice. Then I downloaded curl but it still didn't work and when I run `download` function it was still trying to use PowerShell. So I looked at source code:
```julia
function download(url::AbstractString, filename::AbstractString)
    url = download_url(url)
    curl_exe = find_curl()
    if curl_exe !== nothing
        return download_curl(curl_exe, url, filename)
    elseif Sys.iswindows()
        return download_powershell(url, filename)
    elseif Sys.which("wget") !== nothing
        try
            run(`wget -O $filename $url`)
        catch
            rm(filename, force=true)  # wget always creates a file
            rethrow()
        end
    elseif Sys.which("fetch") !== nothing
        run(`fetch -f $filename $url`)
    else
        error("No download agent available; install curl, wget, or fetch.")
    end
    return filename
end
```
Function `download` will call function `find_curl` to get curl path if curl is installed. But there is a problem in `find_curl` function:
```julia
function find_curl()
    if Sys.isapple() && Sys.isexecutable("/usr/bin/curl")
        "/usr/bin/curl"
    elseif Sys.iswindows() && Sys.isexecutable(joinpath(get(ENV, "SYSTEMROOT", "C:\\Windows"), "System32\\curl.exe"))
        joinpath(get(ENV, "SYSTEMROOT", "C:\\Windows"), "System32\\curl.exe")
    elseif !Sys.iswindows() && Sys.which("curl") !== nothing
        "curl"
    else
        nothing
    end
end
```
I have Windows 7 so function will check if there is curl.exe in "C:\Windows\System32\curl.exe" which doesn't work becuse Windows 7 doesn't have curl in System32 path. But when I run `Sys.which("curl")` it works so to fix my problem I just removed `!Sys.iswindows()` in line `elseif !Sys.iswindows() && Sys.which("curl") !== nothing`. 
I asume that creators of this code taught that all windows machines would have curl in System32 path which obviously isn't the case in Windows 7. Also I don't see the problem with runing Sys.which("curl") on Windows computer so I am asking you to remove `!Sys.iswindows()` in line `elseif !Sys.iswindows() && Sys.which("curl") !== nothing`.

**Comment by musm** [comment]
> I asume that creators of this code taught that all windows machines would have curl in System32 path which obviously is the case in Windows 7. Also I don't see the problem with runing Sys.which("curl") on Windows computer so I am asking you to remove !Sys.iswindows() in line elseif !Sys.iswindows() && Sys.which("curl") !== nothing.

Not really. We specified it this way to avoid picking up the  `curl.exe` executable from e.g. cygwin, which has different behavior due to its POSIX interface. 

The `curl.exe` check is  true   on Windows 10 and  the reason we do that is to ensure we get a compliant version of curl.exe.  If a user added `curl.exe` to path from e.g. git or some other posix-like system I believe the download function would then have some problematic behavior which we decided to avoid to ensure when the function works there are not implicit bugs due to this.

**Comment by musm** [comment]
Can you post the powershell error you get when attempting to download?

**Comment by 4nds** [comment]
I solved my problem with copying curl.exe to System32 folder, also after reinstalling powershell, 
`download` function now works with powershell. And obviously I was wrong about `!Sys.iswindows()` being redundant. I got `download` function working and there is nothing wrong with julia code so I will close this issue.

**Comment by musm** [comment]
Do you mind posting the powershell error message? Sounds like there's an issue with that

**Comment by 4nds** [comment]
There is no powershell error message anymore, I reinstalled powershell and now it's working with no errors. I forgot what was powershell error message, but the problem was with powershell itself and not with Julia.
