### ISSUE TITLE
BigFloat(X, precision=0) fails

### ISSUE THREAD

**Issue by Hieronimo** [JuliaLang/julia#34180]
I try
```julia
BigFloat(X, precision=0) # X=1 or X=0.1
```
and it makes a `Segmentation fault (core dumped)`.
I expected some value error for precision.

Version Info:
```
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
```

**Comment by nico202** [comment]
I can confirm this on the older julia 1.1.0
