### ISSUE TITLE
README: Add badges for Buildbot?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#34187]
Currently, the README has the Travis and AppVeyor badges. But we don't run CI on Travis and AppVeyor anymore. Perhaps we could remove the Travis and AppVeyor badges and add some badges for the Buildbot builders?

Unfortunately I'm not sure how to get the URLs for the Buildbot badges. cc: @staticfloat

**Comment by ViralBShah** [comment]
I removed them: f6b5e8ad58d68855a7d9f4d716b8d719726da1ce

**Comment by zdroid** [comment]
Check http://docs.buildbot.net/current/manual/configuration/www.html#badges.

For example, buildername `whitespace_linux32`:
![](https://build.julialang.org/badges/whitespace_linux32.svg)

Other [builders](https://build.julialang.org/#/builders) show mostly "running" as they never finish the jobs.

**Comment by musm** [comment]
We should probably just close this. I personally don't see a benefit to adding it to the Readme, and we  been fine without these badges since Viral removed them.

**Comment by staticfloat** [comment]
Agreed; since buildbot shows the status of the latest build started (not the latest build finished) it's mostly useless for us.
