### ISSUE TITLE
Feature request: better error message for @which a .+ b

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaLang/julia#34192]
```julia
julia> @which [2 3] .+ [1 2]
ERROR: UndefVarError: .+ not defined
```

My intuition is something like `a .+ b` gets changed to `broadcasted_+(a, b)`, and was hoping it would return something like
`broadcasted_+(a::Array{Int64}...)`
but now I see it wouldn’t make sense.

The error message could be made to say something like
`Did you mean '@which broadcast(+, a, b)'?`

**Comment by mbauman** [comment]
Duplicate of #28615
