### ISSUE TITLE
Threads macro fails on non-array indexing

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#34214]
```
julia> Threads.@threads for i in (1,2); println(i); end
ERROR: TaskFailedException:
MethodError: no method matching unsafe_getindex(::Tuple{Int64,Int64}, ::Int64)
```
and same for other types of iteration.

This is because the `@threads` macro uses `Base.unsafe_getindex(r,i)`. Any reason it's not just using regular indexing? Or at least `@inbounds r[i]`?

**Comment by KristofferC** [comment]
I thought this was fixed by https://github.com/JuliaLang/julia/pull/33396

**Comment by antoine-levitt** [comment]
Woops sorry, I tried on 1.3 and searched on github but didn't look on closed PRs

**Comment by antoine-levitt** [comment]
Thanks!
