### ISSUE TITLE
Value type dispatch on constants should be done at compile time

### ISSUE THREAD

**Issue by georgematheos** [JuliaLang/julia#34220]
If we have code along the lines of
```julia
struct Test
  x
end

# default value
_get_index(t::Test, ::Val) = 0

# if given the correct address (:special_symbol), return some value
_get_index(t::Test, ::Val{:special_symbol}) = t.x

Base.getindex(t, address) = _get_index(t, Val(address))

t = Test(5)
t[:special_symbol]
```

One would think that the Julia compiler should be able to compile `t[:special_symbol]` directly to `t.x`.  However, when looking at the `@code_llvm t[:special_symbol]`, this clearly does not happen. (See the discourse link below for an example of the `@code_llvm` outputs; they were running in an old version of julia, but when I run similar experiments in 1.3.0, I get similar outputs.)

In other words, the compiler should be able to propagate the constant `:special_symbol` through the creation of `Val(:special_symbol)` so the value-type dispatch on `_get_index` can be done at compile time rather than runtime.  I am aware that in general Value-type dispatch can slow things down since it requires runtime dispatch (as discussed in the Julia docs), but in the special case where the value is a constant, it seems like it should be able to be done at compile time.

This issue was discussed here a couple years ago, but I'm not aware of it having been addressed: https://discourse.julialang.org/t/value-type-dispatch-on-constants/858

***

I encountered this while working on the probabilistic programming language Gen (https://github.com/probcomp/Gen); in particular, https://github.com/probcomp/Gen/issues/173 .  Gen was trying to use this type of constant Value dispatch at compile time so that we can effectively compile a bunch of special-case `Base.getindex` implementations for indexing into a "trace" generated from a user-defined function which specifies a bunch of addresses.  We want the syntax `trace[:address]` to be compiled into a direct call to the method which gets a value for that specific address.

This compile-time value dispatch on constants could be a very powerful tool for performance-oriented metaprogramming in situations like this.  In Gen, we want the user to be able to define a model where they associate random choices with "addresses".  This is done by using a macro to scan over a function definition and create a bunch of specific functions needed for probabilistic inference on that model.  We would like to use this macro to generate code so that we can have a different method called for each address in the model, ie. `trace[:address1]` and `trace[:address2]` might need to trigger very different calculations. Since this indexing is so frequent, it can be a notable performance improvement to have the dispatch on address be done at compile time (which should be possible, since these addresses will be constants present in the users' inference code at compile time).  We could of course use macros (eg. `@access_trace trace[:address2]`) or make users wrap addresses in `Val`s (eg. `trace[Val(:address2)]`), but these are inelegant solutions.

**Comment by JeffBezanson** [comment]
At present, this should work if you use `getproperty` (`trace.address1`) instead of `getindex`. It should also work if you add `@inline` to the `getindex` method. We try to avoid doing too much constant propagation since it makes compilation more expensive, but we treat `@inline` as a hint that it might be worthwhile.

Also note: `@code_llvm t[:special_symbol]` will not accurately reveal whether constant propagation happens, since it doesn't know what constant propagation logic the rest of the compiler uses, and it is missing important context (e.g. whether the exact value or just the type of `t` is known). This will be more accurate:
```
f(t) = t[:special_symbol]
@code_llvm f(t)
```

**Comment by georgematheos** [comment]
Ah, looks like `@inline` does work.  I'd tried it but hadn't since I was using `@code_llvm` incorrectly, as you pointed out, the generated code didn't reflect this.

For others to reference, if we define `f(t)` as in Jeff's comments, and inline `Base.getindex`, we get
```julia
julia> @code_typed f(t)
CodeInfo(
1 ─ %1 = Base.getfield(t, :x)::Any
└──      return %1
) => Any

julia> @code_typed t[:special_symbol]
CodeInfo(
1 ─ %1 = invoke Main.Val(_3::Symbol)::Val{_A} where _A
│   %2 = (isa)(%1, Val{:special_symbol})::Bool
└──      goto #3 if not %2
2 ─ %4 = Base.getfield(t, :x)::Any
└──      goto #4
3 ─ %6 = Main._get_index(t, %1)::Any
└──      goto #4
4 ┄ %8 = φ (#2 => %4, #3 => %6)::Any
└──      return %8
) => Any
```
so wrapping in the `f(t)` shows us the correctly compiled version.

Thanks for the help!
