### ISSUE TITLE
parsing error: a$b = 3   ...   $ (generic function with 1 method)

### ISSUE THREAD

**Issue by strickek** [JuliaLang/julia#34236]
I had a typo in my code and found this:

> julia> a$() = 3
> $ (generic function with 1 method)

or

> julia> a$b = 3
> $ (generic function with 1 method)

But calling the "function" fails:

> julia> $()
> ERROR: syntax: "$" expression outside quote
> Stacktrace:
>  [1] top-level scope at none:0

Code lowered schows the same result like for `f() = 3`:

> julia> code_lowered($)
> 1-element Array{Core.CodeInfo,1}:
>  CodeInfo(
> 1 ─     return 3
> )

**Comment by fredrikekre** [comment]
#15483
