### ISSUE TITLE
Feature Request: Select thread/threadpool subset for @spawn

### ISSUE THREAD

**Issue by ianshmean** [JuliaLang/julia#34240]
Say you have a gui interface with multiple long-running, yielding background loops, and for example here `JULIA_NUM_THREADS=3`, and you wanted to maintain a responsive gui.
```julia
@spawn gui()
@spawn looper1()
@spawn looper2()
@spawn looper3()
```
In this example, it would be nice to be able to allow a dedicated thread for `gui()`. 

Something like this perhaps:
```julia
@spawn 1 gui()
@spawn 2 looper1()
@spawn 3 looper2()
@spawn 3 looper3()
```
or 
```julia
@spawn 1 gui()
@spawn 2:nthreads() looper1()
@spawn 2:nthreads() looper2()
@spawn 2:nthreads() looper3()
```

An alternative would be to tell spawn not to use a specific thread, but I'm not sure what a good API would be for that

**Comment by JeffBezanson** [comment]
Looks like the same issue as #34267

**Comment by tro3** [comment]
@JeffBezanson is correct. Same issue. I was not planning on adding to ThreadPools (because it is nonconcurrent), but @vtjnash’s `pin` suggestion will do the trick for this.  I’ll add just to cover the case, even though no real Pool is involved.

**Comment by JeffBezanson** [comment]
Closing as duplicate
