### ISSUE TITLE
Improvement needed for inplace arithmetics

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#3424]
Following is a simple benchmark on inplace addition:

``` julia
# Benchmark of inplace add
function add1!(x::Array, y::Array)
    for i in 1 : length(x)
        x[i] += y[i]
    end
    x
end

function add2!(x::Array, y::Array)
    x[:,:] += y
end

function add3!(x::Array, y::Array)
    x += y  # this is not what is desired, 
            # it creates a new array instead of updating
            # I put it here simply for performance comparison
end

x = rand(1000, 1000)
y = rand(1000, 1000)

# warming
add1!(x, y)
add2!(x, y)
add3!(x, y)

# benchmark
@time for i in 1 : 100 add1!(x, y) end  # 0.123 sec
@time for i in 1 : 100 add2!(x, y) end  # 1.036 sec
@time for i in 1 : 100 add3!(x, y) end  # 0.474 sec
```

The Julia expressions in `add2!` and `add3!` are way too slow than they should be. I write several functions like `add!`, `sub!`, and `mul!` in `MLBase.jl` as a stopgap. However, I believe Julia itself should provide an efficient & concise way to do this, instead of forcing people to write loops whenever they want to add a matrix to another.

What about introducing a bunch of inplace arithmetic functions such as `add!`, `subtract!`, `multiply!`, etc into Base?

**Comment by vtjnash** [comment]
this looks like a better candidate for "Arraymaddon" (perhaps cross-ref to https://github.com/JuliaLang/julia/issues/5117)

**Comment by stevengj** [comment]
This should be closed by #17623, at which point `x .+= y` will be fusing and in-place (along with `x .+= sin.(y.^2) .+ 7` etc.).

**Comment by KristofferC** [comment]
Can you do e.g. `x[1:5] += 3` with `.+`? Also @toivoh's comment in https://github.com/JuliaLang/julia/issues/3424#issuecomment-19663871 is scarily similar to what I did in https://github.com/KristofferC/UpdateIndex.jl.

**Comment by stevengj** [comment]
@KristofferC, yes you can.

**Comment by stevengj** [comment]
Or, sorry, no, `x[1:5] .+= 3` will expand to `broadcast!(x -> x + 3, view(x, 1:5), x[1:5])`, which is not yet fully in-place because `x[1:5]` still creates a copy.  Once slicing creates a view, it will be fully in place.

**Comment by StefanKarpinski** [comment]
Will be addressed by https://github.com/JuliaLang/julia/pull/17623, which is on 0.6 already.

**Comment by KristofferC** [comment]
>  Once slicing creates a view, it will be fully in place.

This is likely to be never though, right? Are we giving up on a nice syntax to update just a part of an array?

**Comment by StefanKarpinski** [comment]
I still think this is addressed by the broadcast changes since the LHS of `.=` and co is now defined to be a view. This was a breaking change but already happened in 0.5.

**Comment by stevengj** [comment]
@StefanKarpinski, `x[1:5] .+= z` is defined to be `x[1:5] .= x[1:5] .+ z`.  The left-hand-side is updated in-place, but `x[1:5]` on the right-hand side still creates a copy.

**Comment by stevengj** [comment]
But I think `@view x[1:5] .+= z` should work totally in-place?

**Comment by stevengj** [comment]
>  I wish I could do `@views x[1:5] .+= y[3:7] .* z[7:11]` and have every reference expression converted to a view.

Note to future readers: nowadays, we indeed have a `@views` macro that works exactly like this.
