### ISSUE TITLE
macOS install has offline documentation quarantined

### ISSUE THREAD

**Issue by mgkuhn** [JuliaLang/julia#34275]
When I use Google Chrome 79.0 as my default browser on macOS 10.14.6 Mojave to download the [macOS DMG](https://julialang-s3.julialang.org/bin/mac/x64/1.3/julia-1.3.1-mac64.dmg), then Chrome (like Safari) will attach an `com.apple.quarantine` attribute to the DMG:
```
$ xattr ~/Downloads/julia-1.3.1-mac64.dmg 
com.apple.diskimages.fsck
com.apple.diskimages.recentcksum
com.apple.metadata:kMDItemWhereFroms
com.apple.quarantine
$ xattr -p com.apple.quarantine ~/Downloads/julia-1.3.1-mac64.dmg 
0081;5e10f808;Chrome;A0D56B28-7A75-4D55-A766-B8D29C44E2B8
```
After opening that DMG and installing its content as usual (moving the `Julia-1.3.app` folder into /Applications), if I then try to read the documentation using
```
open /Applications/Julia-1.3.app/Contents/Resources/julia/share/doc/julia/html/en/index.html
```
then although the Google Chrome window comes to the front, it does _not_ load the requested page. There is no warning or error message. This failure to load the documentation appears to be due to the `index.html` file having inherited the `com.apple.quarantine` extended attribute from the DMG:
```
$ xattr -p com.apple.quarantine /Applications/Julia-1.3.app/Contents/Resources/julia/share/doc/julia/html/en/index.html 
0181;5e10f808;Chrome;A0D56B28-7A75-4D55-A766-B8D29C44E2B8
```
The user could of course fix this manually, using
```
$ xattr -dr com.apple.quarantine /Applications/Julia-1.3.app/Contents/Resources/julia/share/doc/julia/html
```
although this stumbles over the four files `html/en/assets/{arrow.svg,documenter.css,documenter.js,search.js}` being read-only (`-r--r--r--@`).

My concern here is that this problem may affect the out-of-the-box experience for new users, who try to read the freshly installed documentation for the first time.

Does anyone here have ideas how the normal installation process for Julia on macOS could be modified to ensure that the included documentation is immediately readable, even for users who have Google Chrome as their default browser?

(I see that the Julia documentation HTML files appear to be signed in `/Applications/Julia-1.3.app/Contents/_CodeSignature/CodeResources`, but Google Chrome does not appear to be affected by this.)

Background: MATLAB has a command `doc` that starts a browser to display the manual. I'm in the process of implementing the equivalent `doc()` function for Julia (#34278), and stumbled across the above problem when testing it on macOS. I could work around is by explicitly calling Safari rather than the default browser, or by calling `xattr -d com.apple.quarantine` in my `doc()` function, but neither seems entirely elegant. Therefore, further ideas or pointers would be much welcome.

**Comment by Keno** [comment]
Did you extract the dmg using finder? I thought the idea of this attribute was that it gets removed when the user hits ok on the confirmation dialog.

**Comment by mgkuhn** [comment]
When I launch the freshly installed Julia application for the first time, [Launch Services](https://developer.apple.com/documentation/coreservices/launch_services) pops up a "... is an application downloaded from the Internet. Are you sure you wanted to open it?" dialog box, and if I then click the "Open" button there, it appears to set a single bit in the first 16-bit hexadecimal word of the com.apple.quarantine attribute of the applet file.
Before clicking "Open":
```
$ xattr -p com.apple.quarantine /Applications/Julia-1.3.app/Contents/MacOS/applet 
0183;5e134294;Safari;C4BEF4BD-2040-497A-BA11-3110769F7627
```
And after:
```
$ xattr -p com.apple.quarantine /Applications/Julia-1.3.app/Contents/MacOS/applet 
01c3;5e134294;Safari;C4BEF4BD-2040-497A-BA11-3110769F7627
  ^
```
This dialog does not appear to affect the HTML file.

I suspect the underlying problem is that Launch Services only worries about the quarantine attribute (and brings up a dialog to mark it as ok in that case) for executable binaries, but Google Chrome is also affected by it if it is just an HTML file. So avoiding Google Chrome as the documentation browser seems the most practical solution so far.

**Comment by Keno** [comment]
I can reproduce the quarantine xattr being present, but I can't reproduce Chrome refusing to open it. I also looked through the Chrome source code and I can't find any place where it would try to query this attribute and refuse showing the page. Are you sure there isn't some other issue (e.g. over agressive ad blocker, etc.)?

**Comment by mgkuhn** [comment]
I have all browser extensions disabled. Have you tried selecting Google Chrome as the default browser and then using the shell command line
```
$ open file:///Applications/Julia-1.3.app/Contents/Resources/julia/share/doc/julia/html/en/index.html
```
?
The page opens fine if I paste the `file:///Applications/Julia-1.3.app/Contents/Resources/julia/share/doc/julia/html/en/index.html` URL into the URL bar of Chrome, but it fails (only brings browser window to front but does not load page) if I open the page via the `open` tool (and the latter is what I wanted Julia to use to activate the user's default browser).

**Comment by Keno** [comment]
> Have you tried selecting Google Chrome as the default browser and then using the shell command line

Yes, this works fine for me. Chrome Version 79.0.3945.88 (Official Build) (64-bit). Did you check if there are any error messages in the browser console?

**Comment by mgkuhn** [comment]
Same browser version here. Two more observations:
* The `open` command works fine if I quit Google Chrome, and it has to start a fresh one. But it fails to load the page if Google Chrome is already running.
* Using the option `open -n file://...` ("open a new instance of the application") appears to fix the problem, so that might be another workaround, but it can cause Safari to open an empty page :-(

**Comment by Keno** [comment]
Sounds like a Chrome bug of some fashion to me then.

**Comment by mgkuhn** [comment]
I've now reported this problem to the Google Chrome developers via Help | Report an issue ...
