### ISSUE TITLE
LineNumberNode file name ignored

### ISSUE THREAD

**Issue by tomyun** [JuliaLang/julia#34290]
```julia
julia> q = Expr(:block,
    LineNumberNode(111, :aaa),
    Int(0),
    LineNumberNode(222, :bbb),
    Expr(:call, :error)
)
quote
    #= aaa:111 =#
    0
    #= bbb:222 =#
    error()
end
```

```julia
julia> eval(q)
ERROR:
Stacktrace:
 [1] error() at ./error.jl:42
 [2] top-level scope at aaa:222
 [3] eval at ./boot.jl:330 [inlined]
 [4] eval(::Expr) at ./client.jl:425
 [5] top-level scope at REPL[2]:1
```

I'd expect `bbb:222` displayed in [2], but got `aaa:222`.

```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

**Comment by JeffBezanson** [comment]
The front end doesn't support the filename changing in the middle of a series of statements. The workaround is to enclose the part with a different filename in another `block` expression, e.g.
```
julia> q = Expr(:block,
           LineNumberNode(111, :aaa),
           Int(0),
           Expr(:block, LineNumberNode(222, :bbb),
           Expr(:call, :error))
       )
```
For example this is used to support macro-expansions (where the macro usually comes from a different file).

**Comment by tomyun** [comment]
I'm also making a macro to expand DSL and wanted to keep some debug information in `file` field of LineNumberNode. Now the problem is that my macro flattens all these blocks at some point, but there should be a workaround too. Thanks for your answer.

**Comment by JeffBezanson** [comment]
I'll close this, assuming the workaround is sufficient.
