### ISSUE TITLE
Sys.free_memory()/total_memory() documentation incorrect (returns bytes, not kbytes)

### ISSUE THREAD

**Issue by torrance** [JuliaLang/julia#34294]
Both Sys.free_memory() and Sys.total_memory() return free memory measured in bytes, not kilobytes as the documentation claims.

This can be verified in the documentation for libuv, eg. http://docs.libuv.org/en/v1.x/misc.html#c.uv_get_free_memory

Both documentation should be amended to read bytes.

**Comment by JeffBezanson** [comment]
Thanks, good catch. Would you be willing to make a PR to fix it?
