### ISSUE TITLE
fieldnames and fieldtypes don't constant fold

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#34292]
When following up on #34283 
I realizes that `fieldnames` and `fieldtypes` don't constant-fold.
Even though they are purely a function of the input type.

Normally `ntuple` constant-folds really well, not sure if it is the issue, or if it is something else.

With the following very silly looking code  we can fix it.

```
function neo_fieldtypes(::Type{T}) where T
    if @generated
        ntuple(i -> fieldtype(T, i), fieldcount(T))
    else
        ntuple(i -> fieldtype(T, i), fieldcount(T))
    end
end

function neo_fieldnames(::Type{T}) where T
    if @generated
        ntuple(i -> fieldname(T, i), fieldcount(T))
    else
        ntuple(i -> fieldname(T, i), fieldcount(T))
    end
end
```

Benchmarks:

```
julia> @btime (()->fieldtypes(Foo))()
  5.463 ns (1 allocation: 16 bytes)
(Float64,)

julia> @btime (()->neo_fieldtypes(Foo))()
  1.247 ns (0 allocations: 0 bytes)
(Float64,)


julia> @btime (()->fieldnames(Foo))()
  146.585 ns (1 allocation: 16 bytes)
(:x,)

julia> @btime (()->neo_fieldnames(Foo))()
  1.248 ns (0 allocations: 0 bytes)
(:x,)
```

However, that code can't go in `base/reflection.jl` as that is loaded before the `@generated` macro is defined.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/issues/29100

**Comment by KristofferC** [comment]
Seems close enough to the linked issue that this can be closed.
