### ISSUE TITLE
Documentation of finalizer: I/O operations suggestion not working

### ISSUE THREAD

**Issue by stefan-m-lenz** [JuliaLang/julia#34310]
I think there is a bug in the documentation of `finalizer`.
The documentation says

>     f must not cause a task switch, which excludes most I/O operations such as println. @schedule
>     println("message") or ccall(:jl_, Void, (Any,), "message") may be helpful for debugging purposes.

But when I type 

    @schedule  println("message")

I get

> ERROR: LoadError: UndefVarError: @schedule not defined

Also with 

    ccall(:jl_, Void, (Any,), "message")

I get an error

> ERROR: UndefVarError: Void not defined

I use Julia Version 1.3.1 on Windows.

**Comment by stefan-m-lenz** [comment]
I stumbled on this when I tried to close a file in a finalizer like

```
mutable struct TestFileWriter
  io::IOStream
end

function TestFileWriter(filename::String)
  t = TestFileWriter(open(filename, "w"))
  finalizer(finalizeTestFileWriter, t)
end

function finalizeTestFileWriter(t::TestFileWriter)
  write(t.io, "2")
  close(t.io)
end

function writeOne(t::TestFileWriter)
  write(t.io, "1")
end
```

This goes a little bit further, but it would be very kind if someone could explain to me how I could do an IO operation such as closing a file in a finalizer.

**Comment by KristofferC** [comment]
It is a typo in the docs, see https://github.com/JuliaLang/julia/pull/34285.
