### ISSUE TITLE
enable color output whenever stdout is a TTY

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#34317]
Running e.g. `./julia -e '@warn "foo"'` there is no color output unless `--color=yes` is passed. That makes sense when stdout is redirected, but arguably color should be the default when stdout is a TTY.
(Originally reported on slack.)

**Comment by karan0299** [comment]
Can I work on this issue?

**Comment by KristofferC** [comment]
Anyone can work on any issue, no need to ask for permission.
