### ISSUE TITLE
Mulitthreading doc on side effects is outdated

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#34312]
The section [Side effects and mutable function arguments](https://github.com/JuliaLang/julia/blob/7afbb05384186457cedd321071fde137880bfaa5/doc/src/manual/parallel-computing.md#side-effects-and-mutable-function-arguments) is out of date as the two motivating examples now work without bugs.  The first example is with `findfirst` the second with `rand`; the latter was made obsolete with #32407.
Presumably the documented problem still exists but not with those two functions.
 
Add labels: doc, multithreading

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/33419

**Comment by mauro3** [comment]
Sorry, I only checked the issues.
