### ISSUE TITLE
`remotecall_fetch` and `CallMsg` don't accept type (constructor) functions

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#34333]
We had a problem trying to use `remotecall_fetch(OurType, worker, args...)` because `OurType` isn't a `Function`.

I'm wondering if the types at https://github.com/JuliaLang/julia/blob/master/stdlib/Distributed/src/messages.jl#L39 are too restrictive? Could this be `Callable`, or `Any`? (Or might this cause any potential problems with remote workers that I'm not aware of?)

**Comment by JeffBezanson** [comment]
The field type should be `Any`, I'd say. The first argument to `remotecall` etc. is already unrestricted, so that looks like an oversight.
