### ISSUE TITLE
Channel is not checked in tight `while` loop unless a `sleep` comand is provided

### ISSUE THREAD

**Issue by goggle** [JuliaLang/julia#34338]
Consider the following Julia program:
```julia
c = Channel{Int}(10)

@async begin
    sleep(1)
    put!(c, 42)
end

while true
    if isready(c)
        println("Hello from channel: ", take!(c))
        break
    end
    #sleep(0.001)
end
```
Running this program in Julia 1.3.1 will let the program run forever without producing any output. Only if you uncomment the line `sleep(0.001)` it will print `Hello from channel: 42` and exit.
I was wondering if this is expected behavior and if so, is this documented somewhere?

For reference, I have created an equivalent `go` program:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	ch := make(chan int, 10)
	go func() {
		time.Sleep(time.Second)
		ch <- 42
	}()
	for {
		select {
		case x, ok := <-ch:
			if ok {
				fmt.Printf("Hello from channel: %d\n", x)
				return
			}
		default:
			continue
		}
	}
}
```
This program produces as expected the output `Hello from channel: 42` after approximately one second and exits. There is no need for a `sleep`-statement in the main loop.

**Comment by Keno** [comment]
This is expected, Julia doesn't automatically insert yield points, so if you're only running with one thread, the other task never gets scheduled.

**Comment by goggle** [comment]
And is having a `sleep` statement a reliable way to make sure that the other task gets scheduled? Or would that be done differently in practice?

**Comment by quinnj** [comment]
```julia
help?> yield
search: yield yieldto

  yield()

  Switch to the scheduler to allow another scheduled task to run. A task that calls this function is still runnable, and
  will be restarted immediately if there are no other runnable tasks.
```

**Comment by goggle** [comment]
@quinnj Thanks!
