### ISSUE TITLE
missing type prefix in display of some nested containers

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#34343]
Some types (e.g. Vector and Dict) are able to rely on their element values to imply the element types in printing. When there are no elements, we can handle it for the outer container but not nested ones. For example Vector:
```
julia> show([[1],Int[]])
[[1], []]
```
or Dict:
```
julia> show([Dict(1=>1),Dict{Int,Int}()])
[Dict(1 => 1), Dict()]
```

**Comment by karan0299** [comment]
I would like to take up this issue!!
It would be quite helpful , if a little more explanation is provided as it would my first issue. Thanks!

**Comment by karan0299** [comment]
Okay, I got it.
