### ISSUE TITLE
describe locking requirement in docs for Threads.Condition

### ISSUE THREAD

**Issue by tro3** [JuliaLang/julia#34351]
Looks as if one cannot `wait` on a Threads.Condition from the same thread.  A very simple example:

```
julia> l = Condition();

julia> @async begin
         wait(l)
         println("Done")
       end
Task (runnable) @0x0000000013eb8e70

julia> notify(l)
Done
1

julia> l = Threads.Condition();

julia> @async begin
         wait(l)
         println("Done")
       end
Task (failed) @0x0000000013eb8b90
concurrency violation detected
error(::String) at .\error.jl:33
concurrency_violation() at .\condition.jl:8
assert_havelock(::ReentrantLock, ::Nothing) at .\condition.jl:29
assert_havelock at .\lock.jl:19 [inlined]
assert_havelock at .\condition.jl:72 [inlined]
wait(::Base.GenericCondition{ReentrantLock}) at .\condition.jl:102
macro expansion at .\REPL[19]:2 [inlined]
(::var"#7#8")() at .\task.jl:333
```

By itself, this implies you have to know ahead of time if you're going to be on the same thread.  But from a quick glance at the code, it looks to me as if any wait on a Threads.Condition will throw the violation, as `assert_havelock(c::GenericCondition)` does not try to find thread info.  Apologies if this is intended behavior, but it's counter-intuitive to me.

versioninfo():
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by JeffBezanson** [comment]
To wait on a potentially multi-threaded Condition you must acquire its lock first. That should be added to its documentation. The older `Condition` type elides the lock requirement since that API was designed before we had threads.
