### ISSUE TITLE
Julia soc idea page gives error 404

### ISSUE THREAD

**Issue by sid21g** [JuliaLang/julia#34359]
Julia's soc/ideas [page](https://julialang.org/soc/ideas-page) gives 404 error, "It appears that you have stumbled upon a page on the Julia website that does not exist."

**Comment by vtjnash** [comment]
Where'd you find that link? The URL should https://julialang.org/jsoc/

**Comment by sid21g** [comment]
Literally the first google search for "julia soc"

**Comment by fredrikekre** [comment]
Can you report it here: https://github.com/JuliaLang/www.julialang.org/issues

**Comment by vtjnash** [comment]
Ah, OK. Yeah seems to be a bad change in https://github.com/JuliaLang/www.julialang.org/pull/544
