### ISSUE TITLE
supertypes(T) function?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#34362]
When trying to understand (or explain) a type `T`, I often find myself typing `supertype(T)`, `supertype(supertype(T))`, `supertype(supertype(supertype(T)))`, etcetera in order to see the type hierarchy.  This is tedious and annoying.  It would be nice to have a function `supertypes(T)` that just returned a tuple of `T` and all its supertypes, e.g.

```jl
julia> supertypes(Int)
(Int64, Signed, Integer, Real, Number, Any)
```

Sample implementation:
```jl
function supertypes(T::Type)
    S = supertype(T)
    return S === T ? (T,) : (T, supertypes(S)...)
end
```
It could be made to execute completely statically (e.g. is adding `@pure` enough?).

**Comment by JeffBezanson** [comment]
Sounds fine to me. I think it could return a `Vector{Any}` like `subtypes`; is there a real use case for evaluating it at compile time?

**Comment by StefanKarpinski** [comment]
What about just adding `supertype(T, n::Integer=1)` to get the nth supertype? Perhaps both.

**Comment by stevengj** [comment]
I guess my feeling is that since it can be static, it should be static, since we can’t make it static later if we return an array. 

In contrast, the subtypes function cannot be static.
