### ISSUE TITLE
Install from source failing on Ubuntu 18 LTS due to `libLLVM-6.0.so`

### ISSUE THREAD

**Issue by mjsteinbaugh** [JuliaLang/julia#34374]
When attempting to build and install Julia from source on Ubuntu 18 LTS, I'm hitting an issue that I can't seem to figure out. I'm following the recommended steps outlined in [build.md](https://github.com/JuliaLang/julia/blob/master/doc/build/build.md).

Here's my current install script, for reference:
https://github.com/acidgenomics/koopa/blob/master/os/linux/bin/install-cellar-julia

The install completes without error using the settings defined below. However, the program is attempting to use system LLVM 6, even when we request not to. I'm only seeing this on Ubuntu; installation works as expected on Fedora/RHEL.

I'm attempting to configure with this `Make.user` file:

```
prefix="/usr/local/cellar/julia/1.3.1"
# > LLVM_ASSERTIONS=1
# > LLVM_DEBUG=Release
# > USE_BINARYBUILDER=0
USE_LLVM_SHLIB=0
USE_SYSTEM_LLVM=0
```

I also include `unset LLVM_CONFIG` prior to installation, which does isolate LLVM, as expected.

The install runs through without error, but when I attempt to load Julia, the program attempts to look for system `libLLVM-6.0.so`, even though this shouldn't be linked.

```sh
julia --version
```

```
# /usr/lib/x86_64-linux-gnu/libLLVM-6.0.so: version `JL_LLVM_6.0' not found
# (required by /usr/local/cellar/julia/1.3.1/bin/../lib/libjulia.so.1)
```

Installation of the [generic binaries](https://julialang.org/downloads/) works on my Ubuntu machine, and that's the current approach I'm using instead of building from source.

See related posts:

- https://github.com/JuliaLang/julia/issues/32665
- https://discourse.julialang.org/t/problem-building-julia-version-jl-llvm-6-0-not-found/11545

Best,
Mike

**Comment by terasakisatoshi** [comment]
This issue is similar to 

https://github.com/JuliaLang/julia/issues/34264 That I report

**Comment by ViralBShah** [comment]
Please reopen if still an issue with a recent release.
