### ISSUE TITLE
Thoughts on adding an "ls()" function

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#34382]
Hey all, thoughts on adding an "ls()" function that simply prints "in Julia, use `readdir()`" or something similar?

**Comment by logankilpatrick** [comment]
I think this is worthwhile given the usability improvement. `cd() and `pwd()` already exist so why not `ls()` as a wrapper of `readdir()`

**Comment by nalimilan** [comment]
The problem with this kind of addition is that there's almost no end to it: anybody coming from another language can come and ask about adding a new function that s/he would expect to find.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/3376

**Comment by logankilpatrick** [comment]
I see the slippery slope mentality, and I agree. My only thought was that given we already have the other two, not having the 3rd doesn’t make much sense to me.

**Comment by StefanKarpinski** [comment]
There's no intention to have a full set of UNIX commands as Julia functions. There is an intention to have a sufficient amount of basic programming tools to build whatever is necessary. When considering what to call a function that provides some such functionality, unless there is an existing widely agreed upon precedent programming languages (like `readdir`) then using the name of a UNIX command with similar functionality is a good mnemonic choice. That is the case for `cd` and `pwd` (which is slightly misnamed, but people kept forgetting `cwd` so clearly it wasn't a memorably name). For reading the entries in a directory, there is already `readdir` which does the same thing as C's function by the same name.

**Comment by KristofferC** [comment]
As @fredrikekre mentions, I think this discussion has already been had and a conclusion reached.
