### ISSUE TITLE
Create crashdumps on CI timeout

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#34381]
We appear to have additional win32 hangs: https://build.julialang.org/#builders/65/builds/6964

To aid in debugging these kinds of issues, we should try to capture crashdumps and upload them to S3. To generate the crashdump, we can use either procdump (https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) or the relevant kernel API directly
(https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump).

**Comment by staticfloat** [comment]
This has been integrated via the [`autodump.jl` script](https://github.com/JuliaCI/julia-buildbot/blob/master/commands/autodump.jl) used on windows CI.  We don't have an analogue on Linux or macOS yet, but we may eventually want it.
