### ISSUE TITLE
Invalid subtype error message could be better

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#34393]
Currently as follows:
```
julia> abstract type Foo{S}; end

julia> struct Bar <: Foo; end
ERROR: invalid subtyping in definition of Bar
Stacktrace:
 [1] top-level scope at REPL[2]:1
```

Ideally it would at least tell you you forgot a type parameter, and maybe if it's extra nice show you the signature of the thing you're trying to subtype to show you what type parameters it has.

**Comment by ShriprajwalK** [comment]
Hey, I'd like to work on this. How do I go about this?

**Comment by kamalojasv181** [comment]
I was working on this issue. Can someone give me a relevant pointer regarding origin of following functions since there is nothing about them in the documentation.
 jl_is_abstracttype
jl_is_datatype
jl_subtype
jl_is_tuple_type
jl_is_namedtuple_type

and the datatypes:
jl_datatype_t
jl_value_t

**Comment by Keno** [comment]
Probably the way to do this is to add a new error type and expose it to C (e.g. search for `jl_undefvarerror_type` and `UndefVarError` to see how this is done). That error struct would then have both the LHS and the RHS of the error. Then in Julia, define a show method for the new error that shows something more intelligent.

> Can someone give me a relevant pointer regarding origin of following

You can search the code for them. They're defined in julia.h.

**Comment by kamalojasv181** [comment]
@Keno do you not recommend studying the above mentioned functions(which trigger the error) and handling each case separately with a better error message?

**Comment by kamalojasv181** [comment]
Can someone give me a pointer to the explanation of the use of jl_subtype. I have tried following the function but there is a never ending chain of functions.

**Comment by timholy** [comment]
It's what gets called by `S<:T`, is that what you mean?

But you probably don't have to dive in there at all. If you search for the `invalid subtyping` error in the `src/` directory you'll see it's in `interpreter.c` in a function called `jl_set_datatype_super`. Rather than calling `jl_errorf`, you could have it craft a new kind of error (`SubtypeError`?) that stores both `tt` and `super`. Then in `base/errorshow.jl` you'd need to come up with a way to display such errors. Keno gave you the other tip you'll probably need, how to share an error between C and Julia.

**Comment by kamalojasv181** [comment]
@timholy jl_set_datatype_super is exactly the place I am at. The reason why I asked about this function is to handle jl_subtype(super, (jl_value_t*)jl_vararg_type) and other conditions that use jl_subtype as I am not sure what this function is doing that is triggering the error.

**Comment by kamalojasv181** [comment]
@timholy jl_set_datatype_super is exactly the place I am at. The reason why I asked about this function is to handle jl_subtype(super, (jl_value_t*)jl_vararg_type) and other conditions that use jl_subtype as I am not sure what this function is doing that is triggering the error.

**Comment by timholy** [comment]
You can check those same conditions in pure Julia, once the error gets returned. Using `Int` as a standin for `tt` and `Foo` for `super`, here are some examples:
```julia
julia> Int isa DataType  # jl_is_datatype
true

julia> isabstracttype(Foo)    # jl_is_abstracttype
true

julia> typeof(Int.name)    # checking the typename
Core.TypeName

julia> Int <: Foo       # subtyping
false
```
The names of those C functions hopefully make it fairly clear what's actually going on.

**Comment by kamalojasv181** [comment]
@timholy i did try looking at several error functions and their c codes and tried googling but couldn't figure out the error sharing part @Keno suggested. Can you please give me a relevant pointer that explains it.

**Comment by kamalojasv181** [comment]
@timholy in errorshow.jl , how do we know what methods does ex in an error has? I think the only thing I am unclear about this issue is how to use tt and super in errorshow.jl and I think knowledge of ex will solve the problem. Please correct me if i am wrong.

**Comment by kamalojasv181** [comment]
I just created a pull request to the issue https://github.com/JuliaLang/julia/pull/34510. Couldn't understand how to create error in Julia therefore I edited the intrepreter.c file.Kindly ignore previous commits as I was not very clear with the concept of branches.

**Comment by ravibitsgoa** [comment]
Hi, Is this issue still open?

**Comment by KristofferC** [comment]
It is open but there has been some work on it over at https://github.com/JuliaLang/julia/pull/34510.

**Comment by vtjnash** [comment]
Closed by https://github.com/JuliaLang/julia/pull/34510
