### ISSUE TITLE
(2.0) Julep: Make `Char` <: `AbstractString`

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#34399]
I have come across issues like the following more frequently than I'd like to admit:

```julia
julia> function count_as(str)
           as = 0
           for c in str
               if c == "a"
                   as += 1
               end
           end
           as
       end
count_as (generic function with 1 method)

julia> count_as("aaa")
0
```

I wonder if it makes sense to just make `Char <: AbstractString`, and then `==`, `isequal`, etc. would be modified accordingly. This is different from treating numbers like arrays because algebraically strings are naturally a monoid generated by the `Char`s, and so this would be algebraically sound. Furthermore:

- The meaning of `isascii`, `Unicode.isnumeric`, `isless`, etc. are compatible between `Char` and strings
- The meaning of `print`, `write`, etc. are compatible between `Char` and strings
- `Char` is already iterable (and indexable) and iterates itself, which is compatible with its interpretation as a length-one string
- We do also already have `"string" * 'c'`, and even `'a' * 'b'`, so these types are essentially already part of the same monoid
- In a lot of languages, strings iterate length-one strings, and in Julia we can do this too without the performance overhead of allocating a full string for what can be represented in 4 bytes

Required changes here would largely be to `isequal` and `hash`, and possibly others. The breaking change here is that `'x' == "x"` will no longer be false, and for example a `Dict{Any, Any}(...)` can no longer contain both `'x'` and `"x"` keys. I feel like these changes are fairly minor and unlikely to be relied on in production code.

**Comment by DilumAluthge** [comment]
A string and a character are (in my mind) very different things.

**Comment by TotalVerb** [comment]
I do respect that opinion, although I do not share it. But they currently do not really behave like different things at all in the language (aside from `isequal`, `hash`, `==`, etc., and prohibition of mixed `isless`/`<`, I have trouble thinking of cases where characters do not behave like length-1 strings do). Do you have any other examples in the language where they functionally behave differently?

**Comment by oscardssmith** [comment]
@JeffBezanson @StefanKarpinski what's the downside of this? I'm sure there is since both of you know way more than me, but I'm not seeing it.

**Comment by StefanKarpinski** [comment]
A string is a collection of characters and a character is also a collection of characters? That's similar to the situation today where numbers are iterable which everyone seems to want to change. Perhaps it's not as bad with strings and chars but having `"a" == 'a'` seems very funny to me. It's worth discussing for 2.0 in any case.

**Comment by KristofferC** [comment]
> That's similar to the situation today where numbers are iterable which everyone seems to want to change. 

In some sense it is worse. Isn't this like if `Int <: AbstractVector{Int}`?
