### ISSUE TITLE
Taking a String from an Array{UInt8} empties the array

### ISSUE THREAD

**Issue by neonlogic** [JuliaLang/julia#34407]
Using the String constructor with an Array{UInt8} as an argument seems to construct the string by interpreting the array's content as ASCII or UTF-8. It is not clear to me whether this is by design - other languages such as Python would never allow this without an explicit specification of the desired encoding.
What is surprising, however, is that the array's contents disappear in the process. This is certainly not intuitive and probably not intended.

```julia
julia> a = [0x30, 0x31]
2-element Array{UInt8,1}:
 0x30
 0x31

julia> String(a)
"01"

julia> a
0-element Array{UInt8,1}
```

Using Julia version 1.3.1 (2019-12-30)

**Comment by yuyichao** [comment]
This is intended, (I believe) documentd but unintuitive.

Dup of https://github.com/JuliaLang/julia/issues/32528
