### ISSUE TITLE
automate bumping of external stdlibs (Pkg, Statistics)

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#34413]

**Comment by StefanKarpinski** [comment]
@vtjnash, any tips on how to make this happen with your git-external gadget?

**Comment by vtjnash** [comment]
It's designed to mimic `git submodule`, so it's not specifically permitted. But you can set `DEPS_GIT=Pkg` and `override PKG_SHA1=master`. Then whenever you `touch stdlib/Pkg.version`, it'll try to update, or otherwise lets you manage it (`stdlib/Pkg/.git`) yourself.

**Comment by StefanKarpinski** [comment]
This seems like it should be the default.

**Comment by vtjnash** [comment]
Why? That has been distinctly not true for any of our other dependency, so this hasn't come up before. What makes Pkg different?

**Comment by StefanKarpinski** [comment]
IMO all stdlibs should all pull from master when building Julia master. The defaults were designed for external dependencies where that doesn't make sense.

**Comment by vchuravy** [comment]
Allowing this would break our ability to `git bisect`, each git commit needs to have a corresponding link to the stdlib commit it supposed to work with. Pulling from master breaks that workflow quite severely.

**Comment by vtjnash** [comment]
Correct. Also, I created this design to manage our internal fork of libuv, not external dependencies. That it was suitable to use for the other dependencies was just a side-benefit.

**Comment by StefanKarpinski** [comment]
That's a good point. Perhaps some automation for updating stdlibs would be called for then?

**Comment by KristofferC** [comment]
> Allowing this would break our ability to git bisect, 

Yeah, that seems to be the nail in the coffin.

**Comment by StefanKarpinski** [comment]
Yes, that has been put to bed, but the motivation still remains: it's already a problem to have to constantly manually bump Pkg (and Statistics), if we're going to move stdlibs out of the main repo, which we've been planning for a long time, we're going to need a solution here. It could be a bot that makes stdlib bump PRs.

**Comment by DilumAluthge** [comment]
> It could be a bot that makes stdlib bump PRs.

Sounds like a good use case for a Gitahuh Action that runs as a cron job.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/34474

**Comment by DilumAluthge** [comment]
> It's designed to mimic `git submodule`, so it's not specifically permitted. But you can set `DEPS_GIT=Pkg` and `override PKG_SHA1=master`. Then whenever you `touch stdlib/Pkg.version`, it'll try to update, or otherwise lets you manage it (`stdlib/Pkg/.git`) yourself.

@vtjnash Could you elaborate a little bit on how this works?

I have created `Make.user` with the following contents:
```
DEPS_GIT=Pkg
```

And I have modified `stdlib/Pkg.version` to have the following contents:
```
PKG_BRANCH = master
override PKG_SHA1 = dpa/mybranchname
```

But whenever I run `make`, it detaches my HEAD at `refs/heads/dpa/mybranchname`, and adds some untracked files (`build-compiled` and `source-extracted`).

Is there a way to get `make` to stop messing with the Git repo?

**Comment by ViralBShah** [comment]
@DilumAluthge I think you just implemented this. Close?
