### ISSUE TITLE
3-digit Millisecond of Dates.Time object is displayed wrongly in Julia 1.3.0

### ISSUE THREAD

**Issue by eisthf** [JuliaLang/julia#34444]
3-digit Millisecond of Dates.Time object is displayed wrongly:

```
using Dates 

julia> t1 = Time("17:14:39.260", "HH:MM:SS.sss")
17:14:39.26  # millisecond part should be displayed as 260

julia> t2 = Time("17:14:39.261", "HH:MM:SS.sss")
17:14:39.261
```

Environment:

> julia> versioninfo(verbose=true)
> Julia Version 1.3.0
> Commit 46ce4d7933 (2019-11-26 06:09 UTC)
> Platform Info:
>   OS: Windows (x86_64-w64-mingw32)
>       Microsoft Windows [Version 10.0.18362.535]
>   CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz: 
>                  speed         user         nice          sys         idle          irq
>        #1-12  2592 MHz   11703417            0     10783402    625299043      1261260  ticks
> 
>   Memory: 31.893779754638672 GB (19099.8203125 MB free)
>   Uptime: 283695.0 sec
>   Load Avg:  0.0  0.0  0.0
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by quinnj** [comment]
I'm not sure I see the issue here. `t1 = Time("17:14:39.260", "HH:MM:SS.sss")` creates a `Dates.Time` object, that, by default, is displayed w/ the least amount of digits needed for accurate representation. If you need a specific output format, use the `Dates.format` function, like:
```julia
julia> df = dateformat"HH:MM:SS.sss"
dateformat"HH:MM:SS.sss"

julia> Dates.format(t1, df)
"17:14:39.260"
```

**Comment by JeffBezanson** [comment]
To clarify, using 3 digits for the millisecond is not an inherent part of the Time object; it's just an input or output format you can select for parsing and printing. If you need a very specific format, it needs to be specified each time the value is printed or parsed.
