### ISSUE TITLE
Tuple covariance bug?

### ISSUE THREAD

**Issue by WenjieZ** [JuliaLang/julia#34462]
```julia
julia> (Tuple{T} where T) == Tuple{Any}
true

julia> (Tuple{T, T} where T) == Tuple{Any, Any}
false

julia> (Tuple{Vararg{T, 1}} where T) == Tuple{Any}
true

julia> (Tuple{Vararg{T, 2}} where T) == Tuple{Any, Any}
false
```

**Comment by tomaklutfu** [comment]
The second and fourth one have the fixed type for both location in lhs but rhs allows different types like `Tuple{Int, UInt} <: Tuple{Any, Any}`

**Comment by jakobnissen** [comment]
This behaviour is correct. `Tuple{T, T} where T` means a tuple with two elements of same type, whereas in `Tuple{Any, Any}` the two arguments can vary. Consider:
```
julia> (1, 1.0) isa Tuple{Any, Any}
true

julia> (1, 1.0) isa Tuple{T, T} where T
false
```
And
```
julia> (Tuple{T1, T2} where {T1, T2}) == Tuple{Any, Any}
true
```

**Comment by WenjieZ** [comment]
Then why
```julia
julia> Union{Tuple{Int, Int}, Tuple{Any, Any}}
Tuple{Any, Any}
```

**Comment by KristofferC** [comment]
https://docs.julialang.org/en/v1/devdocs/types/#Diagonal-types-1 might be useful reading.

Note, `Union{A, B} == B` if `A <: B` and `Tuple{Int, Int} <: Tuple{Any, Any}`.

**Comment by StefanKarpinski** [comment]
These facts may help clarify:
```jl
julia> (1, 2) isa (Tuple{T, T} where T)
true

julia> (1, "abc") isa (Tuple{T, T} where T)
false

julia> (Tuple{T, T} where T) == (Tuple{Vararg{T, 2}} where T)
true
```

**Comment by WenjieZ** [comment]
@KristofferC The link you provided is very enlightening. Thank you!
