### ISSUE TITLE
Difference between latest docs and 1.5-dev docs

### ISSUE THREAD

**Issue by Hieronimo** [JuliaLang/julia#34488]
latest docs show 1.4-dev docs but with "v1.5" label however with v1.4-dev label in bottom-left:

https://docs.julialang.org/en/latest/NEWS/
https://docs.julialang.org/en/v1.5-dev/NEWS/
https://docs.julialang.org/en/v1.4-dev/NEWS/

**Comment by fredrikekre** [comment]
Don't use the `latest` link, where did you get that?

**Comment by Hieronimo** [comment]
I don't remember that, it was doing well until version 1.5-dev.
also `Edit on GitHub` link is broken on NEWS page.

**Comment by Hieronimo** [comment]
Oh, I found it, just go to an invalid link and it says start at `latest` docs.

https://docs.julialang.org/en/v2/
or
https://docs.julialang.org/en/stable/

**Comment by Hieronimo** [comment]
also `file issues or submit pull requests` link on 404 page is go to an archived repository.

**Comment by Hieronimo** [comment]
some other links to `latest` docs:
https://github.com/JuliaLang/julia/search?q=%22docs.julialang.org%2Fen%2Flatest%22&unscoped_q=%22docs.julialang.org%2Fen%2Flatest%22

**Comment by KristofferC** [comment]
Good finds, those should be fixed.
