### ISSUE TITLE
JULIA_DEBUG=logging doesn't work

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#34484]
The example in https://github.com/JuliaLang/julia/blob/c819cde083a8161aebd7bec626527dbec47fed44/stdlib/Logging/docs/src/index.md#environment-variables doesn't work (using `JULIA_DEBUG=all` does work).

It would be good to document what values are valid, and also add it to https://github.com/JuliaLang/julia/blob/master/doc/src/manual/environment-variables.md

**Comment by vtjnash** [comment]
There's not a log of `@debug` statements in the `logging` file (and these look like they'd be inside comments). I don't think we can readily document what files are on your system though.
```
~/julia$ grep '@debug' `find base stdlib/ -name logging.jl`
base/logging.jl:    @debug,
base/logging.jl:    @debug message  [key=value | value ...]
base/logging.jl:logging macros `@debug`, `@info`, `@warn` and `@error` are defined which log at
base/logging.jl:@debug "Verbose debugging information.  Invisible by default"
base/logging.jl:@debug begin
base/logging.jl:    @debug "Algorithm1" i progress=i/10000
base/logging.jl:@eval @doc $_logmsg_docs :(@debug)
stdlib//Test/src/logging.jl:            @debug "Iteration \$i"
```

**Comment by DilumAluthge** [comment]
I'm guessing that @simonbyrne was referring to this example:
```
JULIA_DEBUG=loading julia -e 'using OhMyREPL'`
```

That produces no output, but both of these produce the correct output
```
JULIA_DEBUG=all julia -e 'using OhMyREPL'`
JULIA_DEBUG=Base julia -e 'using OhMyREPL'`
```

Since the file `loading.jl` is part of the `Base` module, this seems like a bug.

**Comment by DilumAluthge** [comment]
Yeah it's definitely a bug.

@simonbyrne Can you try the example (`JULIA_DEBUG=loading julia -e 'using OhMyREPL'`) with https://github.com/JuliaLang/julia/pull/34485?
