### ISSUE TITLE
ClusterManager hangs when worker dies after connection is made but before setup is done

### ISSUE THREAD

**Issue by gaika** [JuliaLang/julia#34486]
ClusterManager [waits](https://github.com/JuliaLang/julia/blob/master/stdlib/Distributed/src/cluster.jl#L658) for a JoinCompleteMsg while holding a [worker_lock](https://github.com/JuliaLang/julia/blob/master/stdlib/Distributed/src/cluster.jl#L439). If the worker dies in the middle of the setup the JoinCompleteMsg is never received. Then the wait is never notified, the lock is not released, and the whole cluster is not able to add new workers any more.

Not sure how to test or fix it properly. As a workaround: instead of plain `wait(rr_ntfy_join)` have a wait with a timeout:
```
timeout = Ref(false);
@async (sleep(10); timeout[] = true; notify(rr_ntfy_join))
wait(rr_ntfy_join)
if timeout[]
     error("timeout waiting for JoinCompleMsg from worker")
end
```

**Comment by JeffBezanson** [comment]
What a coincidence --- I was just looking at exactly this since I believe it is contributing to an occasional hang on mac os CI. Adding a timeout is the only thing I've come up with so far as well.
