### ISSUE TITLE
Default install path changed on 1.4

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#34496]
The default install directory changed compared to the previous version (Julia 1.3).
previous:  `AppData/Local/Julia-####`
on 1.4: `AppData/Local/Programs/Julia/Julia-####`
Was that intended?

**Comment by ViralBShah** [comment]
We do have an updated installer on Windows. I presume this is intended.

**Comment by musm** [comment]
This was intentional so all Julia versions are conveniently in the same folder

**Comment by KristofferC** [comment]
Thanks for confirming!

**Comment by jaakkor2** [comment]
Could the path be `AppData/Local/Julia/Julia-####`, i.e., drop the folder `Programs`?  No-one else is using `AppData/Local/Programs` folder on my Windows installation.

**Comment by KristofferC** [comment]
I think vscode uses it.

**Comment by jaakkor2** [comment]
`By default, VS Code is installed under C:\users\{username}\AppData\Local\Programs\Microsoft VS Code.` according to https://code.visualstudio.com/docs/setup/windows , but that does not mean Julia should hide itself there.

**Comment by StefanKarpinski** [comment]
Right, what do those VS Code devs know about how programs should work on Windows? Seriously, if you want this to be installed somewhere else, make a clear case for it based on official Windows documentation and why some place would be better than another. This decision wasn't made willy nilly or at random. You can't just complain that you don't like it and expect anyone to pay attention. As far as I can tell, there's no one correct place to put programs on Windows and no matter where you put them someone gets cranky about it, so 🤷‍♂

**Comment by jaakkor2** [comment]
Sorry for thinking Julia v1.4.0-rc1 was for collecting feedback, my misunderstanding. My original gripe was on Slack about the discoverability of the installation location. I remember the default now very well, so this decision is fine with me.

Turns out VS Code users have problems locating the installation https://stackoverflow.com/questions/30263459/visual-studio-code-install-location/52121115

**Comment by blacklightpy** [comment]
This was a good update imo. Why was this reverted?
