### ISSUE TITLE
Rename isimmutable trait to ismutable

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#34518]
Based on recent discussions on slack, I noticed that the trait `isimmutable` is an exception to the rule compared to other `is*` traits in the language. For a concept `foo` we usually have `isfoo` as the trait, and `!isfoo` as the negation. However, with the concept `mutable`, we currently have `is(not)mutable` (a.k.a. `isimmutable`) implemented as the trait.

Would it be possible to deprecate `isimmutable` in favor of the more readable `ismutable` trait?

**Comment by Keno** [comment]
I'm in favor. This naming is left over from when immutables where introduced with the `immutable` keyword, so it made a lot of sense to use the same terminology. Now that the keyword is `mutable`, switching over the predicate makes sense too. Of course, we can't actually change it until 2.0.

**Comment by rapus95** [comment]
also, `!isimmutable` feels unnecessarily redundant as it holds a multiple negations

**Comment by stevengj** [comment]
See also the discussion in #18168.

**Comment by JeffBezanson** [comment]
Agree. In fact we can add `ismutable` now and silently deprecate `isimmutable`.

**Comment by vtjnash** [comment]
I think the main reason for the existence of this name might be that they aren't necessarily exact opposites in the type domain (isimmutabletype). In particular, for Abstract and Union, we have that some of the instances might be mutable and others constant. (though also, we have now that `AbstractArray.body.body.mutable === false` which might be misleading in this example)

**Comment by JeffreySarnoff** [comment]
`isimmutabletype` is not all there yet (https://github.com/JuliaLang/julia/issues/30210).
+1 to introducing `ismutable`.

**Comment by ravibitsgoa** [comment]
It seems that this issue is closed now. Is it still open?
I am a beginner, looking for a "good first issue"! :)

**Comment by KristofferC** [comment]
Yes seems to be fixed in #34518
