### ISSUE TITLE
Edit on GitHub link is broken on NEWS page.

### ISSUE THREAD

**Issue by Hieronimo** [JuliaLang/julia#34511]
On [NEWS page](https://docs.julialang.org/en/v1/NEWS/), `Edit on GitHub` link is broken.
It is going to https://github.com/JuliaLang/julia/blob/master/doc/src/NEWS.md but should go to https://github.com/JuliaLang/julia/blob/master/NEWS.md

**Comment by DonRichards** [comment]
Yep this is broken. 
![Screen Shot](https://user-images.githubusercontent.com/2738244/79259095-23bd8200-7e5a-11ea-8cb0-a6aef1926608.png)

**Comment by StefanKarpinski** [comment]
This should be a simple matter of fixing the link in the file.

**Comment by mitra-varuna** [comment]
I tested this on the latest master branch and it seems to be fixed.
