### ISSUE TITLE
FreeBSD binaries on 1.4 and nightly can't load LinearAlgebra

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaLang/julia#34540]
Hello, I've been redirected to file an issue with Julia about FreeBSD binaries on 1.4 and nightly after observing the following error using CirrusCI.jl
```
WARNING: Error during initialization of module LinearAlgebra:
ErrorException("could not load library "libopenblas64_"
Shared object "libgfortran.so.5" not found, required by "libopenblas64_.so"")
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load library "libcholmod"
│    Shared object "libgfortran.so.5" not found, required by "libopenblas64_.so"
│    Stacktrace:
│     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /usr/home/julia/buildbot/worker/package_freebsd64/build/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109
│     [2] dlopen at /usr/home/julia/buildbot/worker/package_freebsd64/build/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
│     [3] __init__() at /usr/home/julia/buildbot/worker/package_freebsd64/build/usr/share/julia/stdlib/v1.4/SuiteSparse/src/cholmod.jl:90
└ @ SuiteSparse.CHOLMOD ~/usr/home/julia/buildbot/worker/package_freebsd64/build/usr/share/julia/stdlib/v1.4/SuiteSparse/src/cholmod.jl:177
```
Please see, e.g. the logs here https://cirrus-ci.com/github/JuliaApproximation/FastTransforms.jl, and/or the original issue https://github.com/ararslan/CirrusCI.jl/issues/4 for further details.

**Comment by giordano** [comment]
This is the issue we discussed a few days ago on slack :slightly_smiling_face:

**Comment by ararslan** [comment]
Whoops. Clearly I've forgotten already... Unfortunately it seems the conversation has since been lost to the Slack sands of time. Can you remind me what the conclusions were from that discussion?

**Comment by giordano** [comment]
> Unfortunately it seems the conversation has since been lost to the Slack sands of time.

It's in #built-system

> Can you remind me what the conclusions were from that discussion?

No clear conclusion, but you opened https://github.com/JuliaLang/julia/pull/34441 as a result :sweat_smile:

**Comment by ararslan** [comment]
> It's in #built-system

Still lost to the paywall, at least for me.

> but you opened #34441 as a result

But that didn't actually address the issue, just something we noticed while investigating the issue, right? My memory is pretty fuzzy on this.

**Comment by giordano** [comment]
> But that didn't actually address the issue, just something we noticed while investigating the issue, right? My memory is pretty fuzzy on this.

No, I don't think this would have solved this particular issue, only the fact that `libklu.so` from SuiteSparse has the wrong OS/ABI.

**Comment by ararslan** [comment]
So it looks like we're going to need https://github.com/JuliaPackaging/Yggdrasil/pull/410 and a bump to the corresponding BB version here.
