### ISSUE TITLE
julia fails to build

### ISSUE THREAD

**Issue by josefsachs** [JuliaLang/julia#34555]
fresh clone from master at b37d094
on Ubuntu 14.04.2
```/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h: In instantiation of ‘unsigned int llvm::countLeadingZeros(T, llvm::ZeroBehavior) [with T = unsigned int]’:
/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h:539:38:   required from here
/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h:191:60: error: ‘static_assert’ was not declared in this scope
                 "Only unsigned integral types are allowed.");
                                                            ^
/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h: In instantiation of ‘unsigned int llvm::countLeadingZeros(T, llvm::ZeroBehavior) [with T = long unsigned int]’:
/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h:545:38:   required from here
/home/sachs/src/julia-master/usr/include/llvm/Support/MathExtras.h:191:60: error: ‘static_assert’ was not declared in this scope
make[1]: *** [runtime_ccall.o] Error 1
make: *** [julia-src-release] Error 2
```

**Comment by JeffBezanson** [comment]
What compiler is this?

**Comment by josefsachs** [comment]
I'm not sure how to determine what compiler `make` is using, but I would guess that it's this.
```
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```

**Comment by josefsachs** [comment]
For what it's worth, the tip of master built successfully for me within the past 24  hours.

**Comment by KristofferC** [comment]
Julia now uses LLVM 9. Maybe it requires a newer compiler?

**Comment by ararslan** [comment]
[This page](https://llvm.org/docs/GettingStarted.html#software) says that building LLVM requires GCC 5.1 or later, but it's not clear which version of LLVM that refers to. At any rate, I think Kristoffer is spot on here.

**Comment by staticfloat** [comment]
To make this explicit; we _just_ merged the upgrade to LLVM 9 a few hours ago.

**Comment by ararslan** [comment]
But prior to the commit that's giving @josefsachs trouble here.

**Comment by ViralBShah** [comment]
Perhaps we need to update the minimum requirements in https://github.com/JuliaLang/julia/blob/master/doc/build/linux.md

**Comment by JeffBezanson** [comment]
I believe this is subsumed by #34570.
