### ISSUE TITLE
NaN * false == 0.0 ?

### ISSUE THREAD

**Issue by hyrodium** [JuliaLang/julia#34550]
I got `NaN * false` as `0.0`.
But, I think it should be `NaN`.

Here's the code:
```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)

julia> NaN * 0.0
NaN

julia> NaN * true
NaN

julia> NaN * false
0.0
```

Thanks in advance.

**Comment by andreasnoack** [comment]
See https://discourse.julialang.org/t/false-nan-0-0/8477. Please ask questions on discourse.julialang.org

**Comment by hyrodium** [comment]
I am sorry for the inconvenience. And thank you for your information.
