### ISSUE TITLE
Provide a julia.bat file in the installation directory of Julia on Windows

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#34552]
Background issue: https://github.com/JuliaLang/www.julialang.org/issues/615.

Basically, to be able to start Julia from the terminal in Windows, one has to add the `Julia-1.x.y/bin` folder to `PATH`  which I have understood is a bad idea because Windows also look in `PATH` for shared libraries to load for all applications (like `LD_LIBRARY_PATH`).

In a similar vein to the `julia.bat` file we create when compiling Julia on Windows, we could also distribute a `julia.bat`-file that is in the Julia installation directory. It would then be enough to add that directory to `PATH` (which doesn't contain any shared libraries).

cc @musm, do you think that is a reasonable idea?

**Comment by visr** [comment]
It would be good to have a directory that is safe to add to the Path. Would be even better if the installer offered to do it for you, just like for instance VS Code and Atom.

Note that I would currently not consider the installation root for safe, since uninstall.exe is also there.

For Anaconda, I now only add the 'condabin' directory to my path for safety, but this is not the standard yet.

**Comment by KristofferC** [comment]
> Note that I would currently not consider the installation root for safe, since uninstall.exe is also there.

Good point.

**Comment by musm** [comment]
I'm not sure I  agree with the suggestion here to ship a  `.bat` file that opens up  `julia.exe`.  

The problem with adding the `.bat` is that it launches the `exe`  from a  cmd session and leads to annoying issues like https://github.com/microsoft/terminal/issues/217 

Python also dumps everything in the same folder like we do, although the don't use a `bin` folder and just dump everything in the root folder. 

Installing Julia through Chocolatey  basically solves this problem and handles the upgrade issues  in https://github.com/JuliaLang/julia/issues/34495   through the use of exe 'shims' (the issues in https://github.com/JuliaLang/julia/issues/34495 are mainly s related to 'package' level configuration). We should still try to improve things for those who don't use chocolatey.

**Comment by rapus95** [comment]
Well, I also could post that at the other issue (#34495) but I think it fits here more nicely as the other issue is more about automation of setup while this one is about better accessibility.
How about adding a new directory to the ~/.julia path, something like "exported_binaries" which will hold references(or executable scripts) to all binaries that should be accessible via the path. That'd have 2 advantages:
a) Once we fully arrive at shared libraries compiled from Julia it fits well into the workflow with artifacts and packages which are also placed in ~/.julia
b) In case you uninstall Julia and have the ~/.julia directory still as a leftover (which currently is the default), we can provide further options. Especially we see that the user doesn't have a runnable julia executable in the common places -> Point to a new download or offer to delete the ~/.julia directory.

**Comment by KristofferC** [comment]
> Python also dumps everything in the same folder like we do, although they don't use a bin folder and just place everything in the root folder.

While true, the only libraries there are `python3.dll`, `python36.dll` and `vcruntime140.dll`, while we have very many more.

> We should still try to improve things for those who don't use chocolatey.

Yeah, that's the point of this issue. I would expect that a very small number of people use chocolatey to install Windows.

**Comment by musm** [comment]
While it seems like a good idea, is the `dll` issue a practical problem?

From https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order?redirectedfrom=MSDN

The search order is as follows:

> The directory from which the application loaded.
> The system directory. Use the GetSystemDirectory function to get the path of this directory.
> The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
> The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
> The current directory.
> The directories that are listed in the PATH environment variable. Note that this does not include the per-application path specified by the App Paths registry key. The App Paths key is not used when computing the DLL search path.

Basically we only search the PATH environment variable for shared libraries as a last resort.

**Comment by musm** [comment]
How hard would it be to have the `julia.exe` or the shared libs in a different folder?
