### ISSUE TITLE
Unintuitive error when assigning to `eval` 

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#34584]
The error references a `MainInclude` module, which does not seem to exist. 

Edit: Ah, it does exist as `Base.MainInclude`. Should the error be changed to say `Base.MainInclude.eval`?

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> eval = 3
ERROR: cannot assign a value to variable MainInclude.eval from module Main
Stacktrace:
 [1] top-level scope at REPL[1]:1

julia> MainInclude.eval
ERROR: UndefVarError: MainInclude not defined

julia> MainInclude
ERROR: UndefVarError: MainInclude not defined
```

**Comment by JeffBezanson** [comment]
`Main` currently hard-imports `eval` and `include`. I guess it could get them via `using` instead, which would allow this assignment.

**Comment by JeffBezanson** [comment]
As of 1.10 the message is `cannot assign a value to imported variable Main.eval`; with #51878 it is `invalid redefinition of constant Main.eval`. Either way I believe this is fixed.
