### ISSUE TITLE
Variable undefined after assignment with compound expression depending on ARGS

### ISSUE THREAD

**Issue by mfherbst** [JuliaLang/julia#34629]
Starting a new julia session (either 1.3 or 1.4.0-rc1.0) I encounter the following strange behaviour:
```julia
julia> const variable = (isempty(ARGS) && return 1; 2)
1

julia> isdefined(Main, :variable)
false
```

I only managed to trigger the bug if `ARGS` is used in the `isempty`. Also the equivalent expression
```julia
const variable = ifelse(isempty(ARGS), 1, 2)
```
works as expected.

**Comment by antoine-levitt** [comment]
I think the `return` just breaks out of whatever expression it's in:
```
julia> 1 + (return 1)
1
```

**Comment by KristofferC** [comment]
Yes, this is the behavior of `return` in toplevel.

**Comment by mfherbst** [comment]
Ok ... my bad, I find that a little unintuitive in this case, but I get why it's done. Thanks for the clearification.
