### ISSUE TITLE
UndefVarError: @get! not defined during Travis CI testing on Julia nightly

### ISSUE THREAD

**Issue by vlandau** [JuliaLang/julia#34649]
I'm getting a failure on Julia nightly that `@get!` is not defined during package testing on Travis CI. I do not use `@get!` directly in my package, so it's something to do with a dependency. The error message occurs before runtests.jl begins.

[Here](https://travis-ci.org/Circuitscape/Omniscape.jl/jobs/645643762#L193-L211) is the relevant output in Travis CI, and [here](https://travis-ci.org/Circuitscape/Omniscape.jl/jobs/645643762#L101-L113) is the info on the Julia version.

Hopefully this was to right place to post this. Please let me know if not and I'll create a new issue in the appropriate repo/forum after this one is closed.

Thanks!

**Comment by KristofferC** [comment]
Yes, it is known. Thanks for the report. https://github.com/JuliaLang/julia/pull/34646
