### ISSUE TITLE
Upload coverage reports even if some CI checks fail

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#34643]
It seems that coverage reports are only getting uploaded if all CI checks pass (unless I'm confused). This seems rare. Is there a way to change the settings so that coverage reports are uploaded just from the runs which succeed? I could make a PR if someone could lead some breadcrumbs to where the code is for uploading coverage reports.

**Comment by DilumAluthge** [comment]
This is a great idea.

I believe you want to look in https://github.com/JuliaCI/julia-buildbot

**Comment by DilumAluthge** [comment]
@staticfloat

**Comment by staticfloat** [comment]
The coverage build itself will fail if the tests don't pass, because the coverage build itself runs the tests.  Do we really want to get incomplete coverage results?  It could be very difficult to understand what is due to your code not working and what is due to some test being broken.

**Comment by DilumAluthge** [comment]
> The coverage build itself will fail if the tests don't pass, because the coverage build itself runs the tests. Do we really want to get incomplete coverage results? It could be very difficult to understand what is due to your code not working and what is due to some test being broken.

Well, it is pretty common for one of the buildbots to fail on something unrelated to your PR, right? So even if 14 buildbots pass, if 1 fails, then you don’t get any coverage information on your PR.

**Comment by bramtayl** [comment]
That was my thought. To give some context, all of my open test PRs (where coverage reports would be particularly helpful) pass on all but or two platforms.

**Comment by vtjnash** [comment]
This isn't the correct place for this question. I assume you're referring to the documentation at https://docs.travis-ci.com/user/languages/julia/#coverage for the default behavior? You can alter your CI script.

**Comment by bramtayl** [comment]
Hmm, nope, I meant the coverage reports for JuliaLang/julia. But I'll try to make a PR

**Comment by bramtayl** [comment]
Ref https://github.com/JuliaCI/julia-buildbot/issues/173
