### ISSUE TITLE
\brokenbar ¦ and \notslash ⌿ should be parsed infix

### ISSUE THREAD

**Issue by zenna** [JuliaLang/julia#34651]
As the title says, unless there is a compelling reason otherwise it seems that \brokenbar ¦ should be parsed infix, for consistency with all the other bars.

 So should \notslash ⌿, perhaps.

**Comment by amCap1712** [comment]
Hi! I am interested in working on this. Any pointers where I should start @JeffBezanson ?

**Comment by stevengj** [comment]
You would just add them to the [operator definitions](https://github.com/JuliaLang/julia/blob/3f7b556bb3b45cfcb2c718e3e5e0f1d912e4272d/src/julia-parser.scm#L6-L33) in `src/julia-parser.scm`.  In particular, `¦` should go in `prec-plus` alongside `|` and `⌿` would go in `prec-times` alongside `/`.
