### ISSUE TITLE
a few kinds of `eltype` seem absent

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#34669]
`eltype(::Type{T}) where {T} = Any` is the default, and the fallthrough definition.  This catches a few cases that are more logically given specific definitions.  Following e.g. `eltype(Int64) === Int64`, these are suggested: 
- the eltype of any singleton type is itself (e.g. `eltype(Nothing) === Nothing`)
- the eltype of `Symbol` is `Symbol`.

**Comment by KristofferC** [comment]
Why are `Nothing` and `Symbol` special over some other types? I am a bit surprised by the

```
eltype(::Type{T}) where {T<:Number} = T
```

definition... Seems like it came from https://github.com/JuliaLang/julia/commit/f955e117228fbee11ae03d82658109c8d17e4658.

**Comment by JeffreySarnoff** [comment]
Granted, this suggestion comes from observing `eltype(::Type{T}) where {T<:Number} = T` and presupposing that had been discussed.  Should that be reverted, this is no longer an issue.

`Nothing` is just given as an example of `eltype(AnySingleton) = AnySingleton`, as it seems clear enough that the element type of `Nothing` should not be `Any` and  `eltype(Nothing) === Nothing` is more reasonable.  `eltype(Missing)` would be `Missing` etc.

`Symbol` is an indivisible sort, like `Int64`, if there are others .. fine.

**Comment by sostock** [comment]
As I understand it, `Number`s have an `eltype` because they are iterable, so
```julia
eltype(::Type{T}) where {T<:Number} = T
```
makes sense. `Nothing` and `Symbol`s are not iterable, so I don’t see why they would have an `eltype`. The fallback
```julia
eltype(::Type{T}) where {T} = Any
```
does not seem useful to me. Or is there a requirement that everything must have an `eltype`?

**Comment by KristofferC** [comment]
> As I understand it, Numbers have an eltype because they are iterable ...

Yeah, I guess it is consistent with e.g. `eltype(Array{T}) == T`.

**Comment by JeffreySarnoff** [comment]
I am persuaded -- closing this issue.

**Comment by sostock** [comment]
Just for reference: there is an open issue for removing the fallback: #34041
