### ISSUE TITLE
build system depends on `python` in PATH for `normalize_triplet.py`

### ISSUE THREAD

**Issue by tkluck** [JuliaLang/julia#34662]
Python version2 reached end-of-life and in the current alpha version of the next LTS Ubuntu, there is no `python` in the path; only `python2` and `python3` with the former deprecated. (It's possible that this is a temporary oversight and that they'll bring back the symlink `python` -> `python2` but I didn't find the appropriate documentation.)

Some of Julia's dependencies depend on python at build time (at least llvm does) but Julia also depends on it directly for the small utility `normalize_triplet.py`. This means Julia currently fails to build on the next Ubuntu.

It's probably good to migrate away from Python 2. The script works without modification in python 3, but I'm not sure whether that's the best solution as it doesn't necessarily have the same install base. Here's some options:
 - replace `python` by `python3` and make `python3` a build-time dependency of Julia
 - support a `make` variable `PYTHON ?= python` and let the user supply a different version
 - re-write the little utility in `sh` or `perl`.

I think a re-write in `perl` is probably the best option as there's already a few `perl` one-liners elsewhere, and `perl` seems better suited to the text munging that `normalize_triplet` is doing.

Thoughts?

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/34483?

**Comment by tkluck** [comment]
@KristofferC yes thank you! Just found out it was fixed by 181050b3b0675da8. Closing.
