### ISSUE TITLE
Julia 1.3.1 documentation pdf talks about 1.3-alpha

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#34671]
This was discussed in #33968, but filing it separately in case it doesn't have the same root cause. The 1.3.1 pdf doc (page 3) refers to this being the documentation for 1.3-alpha.

https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.3.1.pdf

**Comment by ViralBShah** [comment]
Looking through all the related issues, is it accurate to say that the [latex rendering trickiness](https://github.com/JuliaDocs/Documenter.jl/issues/1200) is preventing the build of the latest manuals and we are using an older version until then?

**Comment by fredrikekre** [comment]
> Looking through all the related issues, is it accurate to say that the latex rendering trickiness is preventing the build of the latest manuals and we are using an older version until then?

Yes, so it is the same as https://github.com/JuliaLang/julia/issues/33968
