### ISSUE TITLE
New REPL softscope changed some return values

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#34673]
https://github.com/JuliaLang/julia/pull/34599#issuecomment-580704793

**Comment by StefanKarpinski** [comment]
Doctests have been busted ever since.

**Comment by KristofferC** [comment]
I don't think doctests are busted. They got changed to the new output in https://github.com/JuliaLang/julia/pull/34599 but the issue here is to track the change, I guess.

**Comment by JeffBezanson** [comment]
This isn't really caused by `:softscope` but rather reflects an irregularity in how `:toplevel` exprs (which `@deprecate` returns) behave:
```
julia> @deprecate f() g()
f (generic function with 1 method)

julia> begin
       @deprecate f() g()
       end

julia>
```
I guess we should make those consistent. But, it's more that the return value of `@deprecate` doesn't matter than a problem with softscope.
