### ISSUE TITLE
should symdiff care about item multiplicity?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#34686]
See https://github.com/JuliaLang/julia/pull/34675. It came up that `symdiff([1, 2, 3, 2]) == [1, 3]` which struck me as... unexpected. I'm opening an issue to discuss whether this is a behavior we actually want.

**Comment by pcjentsch** [comment]
I feel like this is a correctness issue that should addressed sooner rather than later. I ran into it back in march. 

At minimum, I think the documentation should address that the results of this function will not be correct if the arguments have duplicates.

**Comment by StefanKarpinski** [comment]
This example is just nonsense, for example:
```jl
julia> symdiff([1, 2, 2], [2, 3, 3, 4])
3-element Vector{Int64}:
 1
 2
 4
```

**Comment by pcjentsch** [comment]
@StefanKarpinski to clarify, you are saying that the behaviour should be:
```
symdiff(a::AbstractVector, b::AbstractVector) = collect(symdiff(Set(a), Set(b)))
```
right?

**Comment by JeffBezanson** [comment]
Yes that is correct. Might be nice for it to preserve order, but that's more of a detail.
