### ISSUE TITLE
Inconsistent behaviour when overshadowing abstract parametric type

### ISSUE THREAD

**Issue by stev47** [JuliaLang/julia#34705]
```julia
module A
    export B
    abstract type B{T} end
end
using .A

# no error using this line
#println(typeof(B))

B() = nothing

struct C <: B{Int} end
```
The declaration of `B()` overshadows the abstract type `A.B` and the last line errors out.
Uncommenting the `println` line leads to `B()` declaring `A.B()` and no error to be thrown.

The beaviour should probably not depend on an access inbetween, which leads to difficult to track down bugs. Any kind of consistent behaviour would be fine or a warning for the overshadowing as a bonus.
```julia
julia> versioninfo()
Julia Version 1.5.0-DEV.251
Commit 1895a292a2 (2020-02-08 11:56 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
This is intended so that adding exports doesn’t break code like this.
