### ISSUE TITLE
Implicit type casts

### ISSUE THREAD

**Issue by KTysch** [JuliaLang/julia#34712]
Is it idiotistic or I am idealistic?
![image](https://user-images.githubusercontent.com/58916236/74102719-caca2880-4b4e-11ea-9af6-3b10c4587fe4.png)

**Comment by fredrikekre** [comment]
See https://docs.julialang.org/en/v1/manual/faq/#faq-domain-errors-1, and please use https://discourse.julialang.org/ for questions.
