### ISSUE TITLE
Change the precedence of ∘ so that f∘g(x) would parse as (f∘g)(x)

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#34714]
One of the main motivations for using `∘` for me is to reduce the brace clutter – I find `f∘g∘h(x)` easier to parse visually then `f(g(h(x)))`. But currently, `f∘g∘h(x)` requires parentheses like `(f∘g∘h)(x)` to parse as desired, so it only reduces parenthesis, when there are more than 2 functions being composed.

Can we change the precedence of `∘` so that `f∘g(x)` would parse as `(f∘g)(x)`?

**Comment by SyxP** [comment]
I think this is more on how one tends to read the expression `f∘g(x)` as I would interpret `g(x)` as returning a function and `f ∘ (g(x))` being the interpretation. This is consistent with the current parsing.

**Comment by JeffBezanson** [comment]
This has a number of downvotes and would be breaking, so I'll close this.
