### ISSUE TITLE
Bad syntax error for bitwise and being used non-infix

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#34748]
```jl
julia> 1 & 2
0

julia> &(1,2)
ERROR: syntax: invalid syntax &(Core.tuple(1, 2))
Stacktrace:
 [1] top-level scope at REPL[9]:1
```

Showing the `Core.tuple` seems potentially confusing?

**Comment by birm** [comment]
I think this is related to & being a syntactic-unary-operators here https://github.com/JuliaLang/julia/blob/48f942bdd659ae55d7d3e34dcf15dbb8bd871d71/src/julia-parser.scm#L118.
I'll add a PR, but I'm unsure if that's there for a reason.
