### ISSUE TITLE
Multi-threading deadlock bug in Windows (Julia 1.3 and 1.4-rc1)

### ISSUE THREAD

**Issue by vlandau** [JuliaLang/julia#34769]
cc @ViralBShah and @Keno

I encountered a bug in Julia that results in a deadlock on Windows. The bug gets triggered by my package tests, but only when running the tests on a CI virtual machine (both Travis Windows and Appveyor). Notably, if I run the tests (via `Pkg.test()`) manually on the Appveyor VM after I RDP into it, everything works. The bug only gets triggered if the tests were initiated by the CI service. Not sure what's going on there.

Some more info and context is available in [this issue](https://github.com/Circuitscape/Omniscape.jl/issues/13) in my Julia package repo.

Here is [google drive link to a minidump](https://drive.google.com/open?id=18SqE_HtlE1UqeNao8soQ-NjWL9iA-ewv) from the Appveyor VM that hopefully has the information needed to debug this. I would happily try to debug it myself if I could, but it is beyond my capabilities.

You can see the backtrace (from an Appveyor VM) confirming that it is a deadlock [here](https://github.com/Circuitscape/Omniscape.jl/issues/13#issuecomment-586377161).

Here's the session info for the Julia version that was used on the Appveyor VM (but note that the bug is also triggered in Julia 1.3.0 and 1.3.1):
```
Julia Version 1.4.0-rc1.0
Commit b0c33b0cf5 (2020-01-23 17:23 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 1
  JULIA_PROJECT = @.
  JULIA_VERSION = 1.4
```
and you can see the Appveyor output [here](https://ci.appveyor.com/project/vlandau/omniscape-jl/builds/30808532).

Thanks, and please let me know if I can provide any additional info.

**Comment by ViralBShah** [comment]
It would be nice to fix this for 1.4, if we can.
