### ISSUE TITLE
Allow splatting in destructuring

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#34776]
I would like the following to work:
```
julia> x, ys... = (1,2,3)
ERROR: syntax: invalid assignment location "ys..."
```

This would also let us write function signatures like:
```
julia> foo((a, bs...), c, ds...) = bs
ERROR: syntax: invalid assignment location "bs..."
```
Which would be useful for e.g. https://github.com/JuliaDiff/ChainRulesCore.jl/issues/128#issuecomment-586716291

**Comment by kmsquire** [comment]
This has been discussed before. On my phone, so it’s hard to look, but there might already be another issue.

**Comment by simeonschaub** [comment]
Yes, seems to be a duplicate of #2626

**Comment by oxinabox** [comment]
Closing in favor of #2626
