### ISSUE TITLE
Need Commit counts from Infosys

### ISSUE THREAD

**Issue by Mohit-Nain** [JuliaLang/julia#34814]
Hello Team, 

Apologies if this is not the right forum to discuss, please brief on how can i get any question answered?
Question: I'm currently working with Infosys and we are focusing on contributing towards Julia. Can you please let me know how many contributions have been made so far from Infosys to Julia and also share the user accounts who have contributed. 

Thanks

**Comment by StefanKarpinski** [comment]
None that I’m aware of. The list of contributors can be found here: https://github.com/JuliaLang/julia/graphs/contributors. For a more complete list, you may want to use the `git shortlog` command.

**Comment by KristofferC** [comment]
Yeah, combing through the git log seems like the best course of action.

**Comment by ViralBShah** [comment]
Note that most people do not list their institutional affiliations on their GitHub account.

Also, contributions can be either to Julia or to one of the many packages. Discourse would be a better place to have this conversation.

**Comment by StefanKarpinski** [comment]
`git shortlog -nes | grep infosys` indicates that one person has authored commits using an infosys email address — you!

**Comment by Mohit-Nain** [comment]
@StefanKarpinski Thank You
