### ISSUE TITLE
isempty for uninitialized RefValue?

### ISSUE THREAD

**Issue by longemen3000** [JuliaLang/julia#34812]
i'm looking for a way to check if a `RefValue `has no values referenced, and the method defined fails on a `Ref{Any}()`. At this moment, the `isempty` function takes the `RefValue `as a iterable, this fails if the Ref has not an initialized value and returns false when it has `one`. the result of isempty is the negation of the already defined function `isassigned` ,so a quick fix would be to do:
```julia
isempty(a::RefValue) = !(isassigned(a))
```

**Comment by KristofferC** [comment]
Just use `!isassigned(a)`? `isempty` doesn't seem fitting for this functionality.

**Comment by longemen3000** [comment]
yeah, it doesn't, but the fact remains that `isempty` is defined for a RefValue. i see 3 possible courses of action:

- Leave the things as-is: `isempty `throws errors on `undef`, returns false otherwise.
- Define `isempty `for `RefValue`,. `true `for undef, false otherwise
- Throw an error on `isempty(a::RefValue) `and refer to `isassigned` on the error message

any thoughts on this?

**Comment by mkitti** [comment]
Might be useful to document `isassigned` to help address this:
https://github.com/JuliaLang/julia/pull/35723

**Comment by mkitti** [comment]
`isempty` should always return false for a `Ref`

Consider an uninitialized array:
```
julia> A = Array{Function}(undef,3)
3-element Array{Function,1}:
 #undef
 #undef
 #undef

julia> isempty(A)
false

julia> length(A)
3

julia> ref = Ref{Any}()
RefValue{Any}(#undef)

julia> length(ref)
1
```

The definition for `isempty` for an array is:
```
isempty(a::AbstractArray) = (length(a) == 0)
```

`isempty` has nothing to do with the array contents. It only has to do with its `length`

The definition of `length` for a `Ref` is
```
length(x::Ref) = 1
```

Therefore, I propose:
```
isempty(a::Ref) = false
```

**Comment by KristofferC** [comment]
I think this can be closed.
