### ISSUE TITLE
funcionloc should return line number of method sign, not line of first statement in func

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#34820]
It seems that `functionloc` returns the line of the first statement in a method, not the line of the method signature (i.e. the `function foo(` part).

Could this be changed, or a function be added that returns the line of the definition? Or is there a workaround right now that we could use to reliably always return the line for the `function foo` part?

We use this in the language server goto definition stuff, and getting the line of the first statement is kind of messing up the UI for us.

**Comment by JeffBezanson** [comment]
Yeah, I think it would make sense to put this in the `file` and `line` fields of a `Method` object, leaving the source locations as they are.

**Comment by davidanthoff** [comment]
Is there any workaround on currently shipping versions that would allow us to get the right line?

**Comment by JeffBezanson** [comment]
I don't believe so; the information is just not available. But backtracking from the first line number to a `function` keyword should work pretty well (with a separate case, of course, for 1-line definitions, so there would be a bit of fiddling to detect that).

**Comment by davidanthoff** [comment]
Ah, ok, I think then we'll just have to wait... The process that is extracting this information right now is super slow already, if we started to load source files to look for the location of the keyword, that would be even worse.

**Comment by fredrikekre** [comment]
See also #1419, #4971. I assume there is some function in the debugger stack that gives you this information?

**Comment by timholy** [comment]
See https://github.com/timholy/CodeTracking.jl

**Comment by davidanthoff** [comment]
@timholy How would I use CodeTracking.jl for this problem? `whereis` also returns the location of the first line of the body, not the location of the definition.

**Comment by KristofferC** [comment]
Use `CodeTracking.definition`. It does exactly the backtracking as described in https://github.com/JuliaLang/julia/issues/34820#issuecomment-588510808.
