### ISSUE TITLE
Crashes on FreeBSD

### ISSUE THREAD

**Issue by dpo** [JuliaLang/julia#34822]
I run CI for a number of repositories on FreeBSD with the help of Cirrus.jl. I'm observing seemingly random failures of this sort: https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/40/checks?check_run_id=456072504. I test with Julia 1.0, 1.1, 1.2 and 1.3 and I've observed those failures at least for 1.1 and 1.2. Can't remember for sure about the other two.

Not sure what causes them but [I was asked to open a bug report here](https://github.com/ararslan/CirrusCI.jl/issues/5#issuecomment-588543399).

**Comment by giordano** [comment]
For reference, the full cirrus log is at https://cirrus-ci.com/task/5424998697402368
