### ISSUE TITLE
Reduce the size of .dSYM files on Mac

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#34823]
We currently bundle `libjulia.1.3.dylib.dSYM` and `sys.dylib.dSYM` for a total of ~70MB in the Mac releases. Are these used for anything in the release builds or can they just be removed?

**Comment by vtjnash** [comment]
Yes, we need these.

**Comment by ViralBShah** [comment]
@vtjnash says we probably could use some linker flags to reduce the size considerably.

**Comment by ViralBShah** [comment]
I am reopening with a modified title.

**Comment by ViralBShah** [comment]
Apparently not by a whole lot, again according to @vtjnash
