### ISSUE TITLE
Unknown hang-up in v1.3.1

### ISSUE THREAD

**Issue by githubtomtom** [JuliaLang/julia#34834]
Julia v1.3.1 hangs when running the following call of `pickvarnames(:(a + b))`:
```
pickvarnames(ex::Symbol) = ex

function pickvarnames(ex::Expr)
    varnames = ()
    if ex.head == :call
        for arg in ex.args[2:end]
            varnames = (varnames..., pickvarnames(arg) )
        end
    end
    return varnames
end

julia> pickvarnames(:a)
:a

julia> pickvarnames(:(a + b) )  # Hangs!
Killed: 9
```
this issue was original discussed in [discourse](https://discourse.julialang.org/t/unknown-hang-up-in-v1-3-1/34912.
so far, the actual cause of hanging is mysterious. knowledge collected so far are:
1. it hangs in v1.3, v1.2, v0.7 and v1.4 master. But v0.6 has no problem.
2. using `Vector{Symbol}` instead of `Tuple` avoids hanging. (i.e. `varnames = []` and `varnames = [varnames..., pickvarnames(arg) ]`.

**Comment by Keno** [comment]
Looks like inference doesn't like this recursion pattern.

**Comment by githubtomtom** [comment]
it’s strange, because there’s no problem if I `@enter` it (from `Debugger.jl`).

**Comment by KristofferC** [comment]
It is not very strange since the debugger execute code in a totally different manner.

**Comment by githubtomtom** [comment]
the other strange thing is doing with `Vector` instead of `Tuple` would have no problem.
