### ISSUE TITLE
Reference Counting Garbage Collector mode

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#34836]
This came up in the ML call a few weeks back.

It may be useful to have multiple different garbage collector implementations, and the ability to chose which to use at startup.
While the current Mark-and-Sweep based-GC is a generally good chose for most use-cases its not ideal for all.
A Reference Counting based-GC has a different set of trade-offs.
In particular when you have hetrogenious memory; from multiproccessing (distributed or otherwise), and especially from GPU or other accellerators, it can be desirable to have very "tight"  lifespans on all memory.

Now, I am in no way saying that we can't make out Mark-and-Sweep do this well.
But I am suggesting it might be simpler to have a second garbage collector that one can manually switch to.

**Comment by JeffBezanson** [comment]
We aren't doing this.

**Comment by Keno** [comment]
That said, I've considered making these kinds of things possible as compiler transforms, so that's probably a more promising direction.

**Comment by JeffBezanson** [comment]
Yes, I agree compile-time memory management is the way to go here.

**Comment by oxinabox** [comment]
Reasonable.

**Comment by AriMKatz** [comment]
How would that work without restricted semantics akin to rust? Or do you only mean for a subset of array code
