### ISSUE TITLE
Specialize ∘ on type arguments?

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#34849]
The following does not infer:
```julia
julia> f(itr) = map(Int∘sign, itr)
f (generic function with 2 methods)

julia> f((1,))
(1,)

julia> @code_warntype f((1,))
Variables
  #self#::Core.Compiler.Const(f, false)
  itr::Tuple{Int64}

Body::Tuple{Any}
1 ─ %1 = (Main.Int ∘ Main.sign)::Core.Compiler.Const(Base.var"#56#57"{DataType,typeof(sign)}(Int64, sign), false)
│   %2 = Main.map(%1, itr)::Tuple{Any}
└──      return %2
```
This occured [here](https://discourse.julialang.org/t/how-can-i-reduce-memory-allocation-and-execution-time-while-ray-tracing-using-voxelraytracers-package/34971).

**Comment by tkf** [comment]
This is because closures capture types as `DataType`s https://github.com/JuliaLang/julia/issues/23618#issuecomment-566130606

It's easy to "fix" this for `∘` but it'd be great if it can be fixed for all closures.

**Comment by jw3126** [comment]
Ok I close this as it is a dup of #23618
