### ISSUE TITLE
; in help mode doesn't return anything

### ISSUE THREAD

**Issue by Hieronimo** [JuliaLang/julia#34842]
```julia
help?> ;
search:

```

**Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)**

**Comment by mbauman** [comment]
Thanks for the report.  We do have this definition, but somehow we're losing the `;` before we get to the lookup.

https://github.com/JuliaLang/julia/blob/835e148ef7b62ac09ff3f5209745796473161d60/base/docs/basedocs.jl#L404-L409

**Comment by JeffBezanson** [comment]
fixed by #34944.
