### ISSUE TITLE
TEMP vs Temp

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#34853]
CI seems to be broken on Windows due to the capitalization of the TEMP folder. See e.g.

https://build.julialang.org/#/builders/32/builds/8615/steps/3/logs/stdio
https://build.julialang.org/#/builders/65/builds/8232/steps/3/logs/stdio

Seems like it might be an issue with `realpath`?

**Comment by KristofferC** [comment]
Rebase the branch so it includes https://github.com/JuliaLang/julia/pull/34506

**Comment by bramtayl** [comment]
Oops. Thanks!
