### ISSUE TITLE
parse(ComplexF64,"1im+1") not work

### ISSUE THREAD

**Issue by mikehui** [JuliaLang/julia#34855]
Why does this happen? 

julia> parse(ComplexF64, "1im+1")
ERROR: ArgumentError: missing imaginary unit
Stacktrace:
 [1] tryparse_internal(::Type{Complex{Float64}}, ::String, ::Int64, ::Int64, ::Bool) at ./parse.jl:334
 [2] parse(::Type{Complex{Float64}}, ::String) at ./parse.jl:378
 [3] top-level scope at REPL[19]:1

julia> parse(ComplexF64, "1+1im")
1.0 + 1.0im

julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by jlapeyre** [comment]
That agrees with the documentation for `parse`:
> `Complex` types are parsed from decimal strings of the form `"R±Iim"`

Perhaps the restriction is for efficiency.

**Comment by StefanKarpinski** [comment]
This is parsing a fixed format as @jlapeyre said, not an arbitrary arithmetic expression.
