### ISSUE TITLE
Unfinished sentence in "Calling C and Fortran Code" documentation

### ISSUE THREAD

**Issue by legendre6891** [JuliaLang/julia#34862]
In [this section](https://docs.julialang.org/en/v1.5-dev/manual/calling-c-and-fortran-code/#C-Wrapper-Examples-1), the manual currently reads:

Here, the input p is declared to be of type Ref{gsl_permutation}, meaning that the memory that p points to may be managed by Julia or by C. A pointer to memory allocated by C should be of type Ptr{gsl_permutation}, but it is convertible using Base.cconvert and therefore

The "punchline" after therefore is missing.

**Comment by jmkuhn** [comment]
Removed with https://github.com/JuliaLang/julia/pull/31700

**Comment by legendre6891** [comment]
@fredrikekre Not sure I understand why this is closed -- what is the resolution? The PR mentioned above introduces the problem rather than providing a fix, it seems.

**Comment by fredrikekre** [comment]
Sorry, thought it meant that the unfinished sentence was removed by the PR.
