### ISSUE TITLE
Windows installer creates start menu group for each Julia version

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#34867]
Now the Windows start menu with multiple Julia versions installed looks like this
![jl_startmenu](https://user-images.githubusercontent.com/7318249/75247416-2bee2f00-57d2-11ea-9fb8-67731a01290e.png)
and the start menu folder like this with folders for old versions of Julia that have been uninstalled
![jl_startfolder](https://user-images.githubusercontent.com/7318249/75247447-39a3b480-57d2-11ea-9b55-5392f28098ab.png)

Better arrangement could be that there was a single Julia-group under which the items would appear, like this
![jl_startmenu_couldbe](https://user-images.githubusercontent.com/7318249/75247532-69eb5300-57d2-11ea-8c9e-094693802900.png)
and expanded
![jl_startmenu_couldbe_open](https://user-images.githubusercontent.com/7318249/75247545-7374bb00-57d2-11ea-91dd-b24d88e07ad0.png)

This is a user visible issue when navigating the Windows start menu. Not a big issue if one has only a couple of Julia versions installed.

Default group menu name seems to be `DefaultGroupName="{#AppName} {#AppVersion}"` defined here
https://github.com/JuliaLang/julia/blob/v1.4.0-rc2/contrib/windows/build-installer.iss#L92

**Comment by musm** [comment]
Microsoft starting with Windows 8, recommends not to install applications to folders/groups. In https://github.com/JuliaLang/julia/pull/35059 we simply install the Julia corresponding Julia icon without the folder structure.
