### ISSUE TITLE
CI failing on master

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#34877]
We have CI failing on master, apparently because https://github.com/JuliaLang/julia/pull/34828 conflicted with https://github.com/JuliaLang/julia/pull/34764. Interestingly it doesn't seem to affect all OSes.

**Comment by Keno** [comment]
> Interestingly it doesn't seem to affect all OSes.

This was a separate bug where the new CI configuration failed to report failures on the windows bots.

**Comment by vtjnash** [comment]
Closed by #34878
