### ISSUE TITLE
Unit range indexing of tuples

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#34884]
Indexing a tuple with a unit range allocates:

```
t = (1,2,3,4,5,6,7,8,9);

julia> @btime t[4:8]
  268.272 ns (2 allocations: 176 bytes)
(4, 5, 6, 7, 8)
```

The likely culprit:
https://github.com/JuliaLang/julia/blob/434c6bbead0edc59f1d8c64c55a979b5898d994e/base/range.jl#L292

I think it would be better to use `ntuple`:

```
function mygetindex(t::Tuple, r::AbstractUnitRange{<:Real})
    n = length(r)
    n == 0 && return ()
    o = first(r) - 1
    ntuple(i -> t[o + i], n)
end

julia> @btime mygetindex(t, 4:8)
  25.175 ns (1 allocation: 48 bytes)
(4, 5, 6, 7, 8)
```

What do you think?

**Comment by cossio** [comment]
With interpolation of `t` the difference is more striking. But maybe there is some compiler elision going on.

```
julia> @btime ($t)[4:8]
  247.025 ns (2 allocations: 176 bytes)
(4, 5, 6, 7, 8)

julia> @btime mygetindex($t, 4:8)
  0.020 ns (0 allocations: 0 bytes)
(4, 5, 6, 7, 8)
```

**Comment by mbauman** [comment]
Would #31138 fix your use-case?  Note that even if we remove this allocation, you'd still have a type-instability downstream.

**Comment by cossio** [comment]
> Would #31138 fix your use-case?

If understand correctly that only works for some particular indexes? Then no, I need a range with general indexes.

> you'd still have a type-instability downstream

Because the length of the output tuple is not inferrable? Still seems like an improvement.

**Comment by chriselrod** [comment]
Constant prop can already make it inferrable:
```julia
julia> function mygetindex(t::Tuple, r::AbstractUnitRange{<:Real})
           n = length(r)
           n == 0 && return ()
           o = first(r) - 1
           ntuple(i -> t[o + i], n)
       end
mygetindex (generic function with 1 method)

julia> t = ntuple(identity, 12);

julia> getval(t, ::Val{R}) where {R} = mygetindex(t, R)
getval (generic function with 1 method)

julia> getval(t, Val(3:8))
(3, 4, 5, 6, 7, 8)

julia> @code_warntype getval(t, Val(3:8))
Variables
  #self#::Core.Compiler.Const(getval, false)
  t::NTuple{12,Int64}
  #unused#::Core.Compiler.Const(Val{3:8}(), false)

Body::NTuple{6,Int64}
1 ─ %1 = Main.mygetindex(t, $(Expr(:static_parameter, 1)))::NTuple{6,Int64}
└──      return %1
```

**Comment by brenhinkeller** [comment]
Looks like no allocations in 1.8.3 or 1.9.0-alpha1, as long as `t` is interpolated into the benchmark:
```
julia> t = (1,2,3,4,5,6,7,8,9);

julia> using BenchmarkTools

julia> @btime ($t)[4:8]
  2.208 ns (0 allocations: 0 bytes)
(4, 5, 6, 7, 8)
```

**Comment by brenhinkeller** [comment]
The lack of allocations seems pretty consistent across different OSs and 1.8+ versions so I _think_ we can close, but please undo if I'm being too hasty!

**Comment by brenhinkeller** [comment]
Yeah it's pretty hard to test for allocations... If anyone can come up with a good way to do this though, that could be a good PR
