### ISSUE TITLE
SegFault at each package installation attempt

### ISSUE THREAD

**Issue by IamOlep** [JuliaLang/julia#34915]
Any time I try to install a new package, I get this error. Never seen before.
I tried to uninstall julia and remove any folder related but with no effect

I'm on Linux, Manjaro-i3. On another machine with same OS I do not experience the same problem.

signal (11): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7efbd0555e73)
http_parser_execute at /usr/bin/../lib/libhttp_parser.so.2.9 (unknown line)
unknown function (ip: 0x7efbd0557390)
unknown function (ip: 0x7efbd0559770)
unknown function (ip: 0x7efbd055bb58)
unknown function (ip: 0x7efbd0559f91)
git_remote_fetch at /usr/bin/../lib/libgit2.so (unknown line)
git_clone at /usr/bin/../lib/libgit2.so (unknown line)
unknown function (ip: 0x7efbf2e6897f)
unknown function (ip: 0x7efbf2e69991)
unknown function (ip: 0x7efbf2e9de5e)
unknown function (ip: 0x7efbf2e9e3b9)
unknown function (ip: 0x7efbf2e9e53e)
unknown function (ip: 0x7efbf2e9edda)
unknown function (ip: 0x7efbf2ea0b39)
unknown function (ip: 0x7efbf2ea19b1)
unknown function (ip: 0x7efbf2eab164)
unknown function (ip: 0x7efbf2f149e1)
unknown function (ip: 0x7efbf2f14c1a)
unknown function (ip: 0x7efbf2e8eaeb)
do_add! at /build/julia/src/julia-1.3.1/usr/share/julia/stdlib/v1.3/Pkg/src/REPLMode.jl:505
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7efbf2e2882b)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7efbf2fa0522)
unknown function (ip: 0x7efbf2f46104)
unknown function (ip: 0x7efbf2f4652d)
unknown function (ip: 0x7efbf2f4a2e8)
unknown function (ip: 0x7efbf2f4a416)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7efbf3028ce1)
unknown function (ip: 0x7efbf303bd9e)
unknown function (ip: 0x7efbf303ccd1)
unknown function (ip: 0x7efbf2e4ed9c)
unknown function (ip: 0x7efbf2e4f358)
jl_f__apply at /usr/bin/../lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7efbf2d62717)
unknown function (ip: 0x7efbf2d68ff2)
unknown function (ip: 0x7efbf2d69512)
unknown function (ip: 0x7efbf2d69655)
unknown function (ip: 0x5655555554fe)
unknown function (ip: 0x5655555550a7)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 0x56555555515d)
Allocations: 944657 (Pool: 944392; Big: 265); GC: 1
Segmentation fault (core dumped)

Thanks for contributing to the Julia project!

**Comment by ignaciocaamanio** [comment]
I'm experimenting the same when I try to add Plots package, seg fault.

**Comment by IamOlep** [comment]
> I'm experimenting the same when I try to add Plots package, seg fault.

I got this with any package, do you have this problem with Plots only?

**Comment by ignaciocaamanio** [comment]
Sorry, I've try with others and is the same, seg fault.

**Comment by fredrikekre** [comment]
Lools like you don’t use offivcial binaries? See e.g. https://discourse.julialang.org/t/installing-packages-leads-to-crash/35268 for the same problem (`http-parser`).

**Comment by IamOlep** [comment]
> Lools like you don’t use offivcial binaries? See e.g. https://discourse.julialang.org/t/installing-packages-leads-to-crash/35268 for the same problem (`http-parser`).

I looked around for similar problems but I haven't found the thread you're linking, sorry.

Thanks!

**Comment by ignaciocaamanio** [comment]
Works well with official binaries, I was using Archlinux binaries. Thanks.
