### ISSUE TITLE
Can't shadow Base variable with a const binding

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#34924]
This used to (and should) work but was broken by 3f05b0d3534af3657a93b662be0030410d1ba1d6 (cc @Keno)
```
$ julia -e 'const LOAD_PATH=1'                                        
ERROR: cannot assign a value to variable Base.LOAD_PATH from module Main
Stacktrace:
 [1] top-level scope at none:1
```

**Comment by jlapeyre** [comment]
?? I get the same error with julia 1.2.0

**Comment by KristofferC** [comment]
Maybe you import LOAD_PATH in your `startup.jl` file or something. Works for me in 1.2, 1.3, 1.4.

**Comment by jlapeyre** [comment]
> Maybe you import LOAD_PATH in your startup.jl

Exactly this.
