### ISSUE TITLE
load libsuitesparse_wrapper.so (i686 CHOLMOD initialization error)

### ISSUE THREAD

**Issue by apparluk** [JuliaLang/julia#34936]
Improper alignment here.

```
bash-4.3$ julia
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load library "libsuitesparse_wrapper"
│    libsuitesparse_wrapper.so: ELF-indlæsningskommandos adresse/tillæg er ikke tilpasset ordentligt
└ @ SuiteSparse.CHOLMOD /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.3/SuiteSparse/src/cholmod.jl:176
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> exit()
bash-4.3$  
```

[Julia](https://nurmi-labs.blogspot.com/2020/02/julia.html) (blog Post)

**Comment by ViralBShah** [comment]
How was this built? Can you point to the build script?

**Comment by apparluk** [comment]
https://julialang.org/downloads/
julia-1.3.1-linux-i686.tar.gz

https://github.com/slackbuilds/julia-1.3.1
julia.SlackBuild

**Comment by apparluk** [comment]
@ViralBShah 

I can try a package creation with another i696 release if you want to suggest a specific pre-compiled version to download.

FWIW, I would prefer if regarding shell messages that Julia would not assume running in a UTF-8 LANG.

**Comment by ViralBShah** [comment]
What version of gcc? Perhaps @staticfloat knows what might be going on.

**Comment by staticfloat** [comment]
@apparluk translating that error message, it looks like it's saying `ELF load command address/offset not properly aligned`; does that seem right?

If that is the case, this seems likely to be a `patchelf` issue where your linux is (for some reason) unhappy with the alignment of something in that image.  What version of `glibc` are you using?

**Comment by apparluk** [comment]
> What version of gcc?

output is from running gcc-5.5.0 / slackware-current would be gcc-9.2.0

> What version of `glibc` are you using?

output is from running glibc-2.23 / slackware-current would be glibc-2.30

@staticfloat 

I though my improper alignment comment was sufficient, here's the English error message running in xterm, which also clarifies what I wrote about Julia messages assuming running in a UTF-8 LANG.

![xterm](https://user-images.githubusercontent.com/52227507/76027451-ee577780-5f30-11ea-9f46-9721cff9a148.png)

**Comment by apparluk** [comment]
> Could you try slackware-current?

My hardware capabilities presently being somewhat limited, I've sent a query on the matter to a Slackware user community member.

**Comment by willysr** [comment]
i tested on slackware64-current and it has the same results

**Comment by ViralBShah** [comment]
How exactly are you building? What is the exact `make` incantation?

**Comment by willysr** [comment]
I'm using the binary version and packaged using this script: https://slackbuilds.org/slackbuilds/14.2/development/julia/julia.SlackBuild (with some changes to build the latest one)

**Comment by ViralBShah** [comment]
Can you try starting Julia from the downloaded tarball directly and see if it gives the same error?

**Comment by willysr** [comment]
if i try to build it manually using make and run usr/bin/julia, it worked fine

i think the static version is the one have problems under slackware-current. probably a mismatch in some part

**Comment by apparluk** [comment]
> starting Julia from the downloaded tarball directly

![uxterm](https://user-images.githubusercontent.com/52227507/76119741-58832180-5ff0-11ea-9235-4695b50d7b19.png)

**Comment by apparluk** [comment]
@willysr If on slackware64-current you move /usr/lib/julia/libsuitesparse_wrapper.so to libsuitesparse_wrapper.so.bak and copy from an extracted tarball the unstripped libsuitesparse_wrapper.so to /usr/lib/julia, do you get any load errors?

**Comment by staticfloat** [comment]
Ah, yes, in the slack build instructions, it unconditionally strips all ELF objects:

```bash
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
```

This unfortunately sounds like a bad interaction between `patchelf` and `strip`, as documented here: https://github.com/NixOS/patchelf/issues/10.  Supposedly that should be fixed (and we do use `patchelf 0.10` within BinaryBuilder, which should contain that fix) so either that `patchelf` fix is insufficient, or there's something else wrong with `strip`.

**Comment by apparluk** [comment]
@staticfloat try `ldd` on the stripped and unstripped `libsuitesparse_wrapper.so`

**Comment by staticfloat** [comment]
We historically don't strip our binaries for precisely this reason; if you download the latest Julia release, those libraries are unstripped.  The only stripping is occuring on the Slackware side.

**Comment by willysr** [comment]
let me  try without stripping then

**Comment by apparluk** [comment]
Which julia version began using patchelf?

A comment not to strip for julia >= version could be added in the .SlackBuild above the commented out strip lines.

**Comment by willysr** [comment]
Yeah, removing stripping makes it work on slackware64-current here. Thanks

**Comment by apparluk** [comment]
@staticfloat I'm inclined to close, with the possibility to reopen if the patchelf code changes.

@willysr I suppose the following would suffice in an eventual SlackBuilds.org update.  

```
# Don't strip for julia >= 1.3.1.
# find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
#  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
```

**Comment by staticfloat** [comment]
> @staticfloat I'm inclined to close

Same.

> Which julia version began using patchelf?

At the very least, since we started using precompiled binaries for most of our dependencies, which would be Julia 1.2+.
