### ISSUE TITLE
deepcopy does no deep copy on Types

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#34945]
``Base.deepcopy`` does not work for types currently
 
```julia
t = Tuple{T, T} where T <: Int
t2 = deepcopy(t)
t2.var.ub = String
@show t  # t = Tuple{T,T} where T<:String
```

using julia 1.3.1

**Comment by schlichtanders** [comment]
the solution seems to be the following addition to ``Base.deepcopy_internal```

```julia
function Base.deepcopy_internal(T::UnionAll, dict::IdDict)
  base, wheres = split_unionall(T)
  wheres_dc = [Base.deepcopy_internal(w, dict) for w in wheres]

  type = base.name.wrapper
  typeparameters = base.parameters
  typeparameters_dc = [Base.deepcopy_internal(p, dict) for p in typeparameters]
  unionall = type{typeparameters_dc...}
  for w in wheres_dc
    unionall = UnionAll(w, unionall)
  end
  unionall
end
```

if this is indeed the correct way to solve the problem,
I would love to make this my first pull-request to the julia code-base

**Comment by JeffBezanson** [comment]
TypeVars are supposed to be conventionally immutable; mutating existing types could cause major problems. We should document that, and perhaps even make this mutation an error. (The only reason they're mutable is to make different TypeVars with the same name distinguishable, which is kind of a wart that should be cleaned up eventually.)

**Comment by vtjnash** [comment]
```
julia> t2.var.ub = String
ERROR: setfield!: const field .ub of type TypeVar cannot be changed
```
