### ISSUE TITLE
REPL doc completion uses its own list of keywords

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#34950]
Here:
https://github.com/JuliaLang/julia/blob/ea067fb221769a43221bf422508f0f5d70fb5fde/stdlib/REPL/src/docview.jl#L579

I believe it should use the keys of `Base.Docs.keywords` instead.

**Comment by monsij** [comment]
Hey @JeffBezanson , should it be put like this:
`const builtins = keywords`

**Comment by JeffBezanson** [comment]
Probably not exactly, since `keywords` is a dictionary and not an array of strings.

**Comment by suraj-shivu** [comment]
Hey @JeffBezanson  , I would like to pick up this issue and I have a small clarification, should the 
`const builtins` be an array of symbols?
