### ISSUE TITLE
Dict doesn't recognize some of its keys.

### ISSUE THREAD

**Issue by Diego---** [JuliaLang/julia#34968]
I wrote a function that produces the following dictionary (called base): 

base=vectores_hash(3,3)
Dict{Any,Any} with 10 entries:
  [1, 0, 2] => 6
  [1, 2, 0] => 4
  [0, 0, 3] => 10
  [2, 0, 1] => 3
  [0, 1, 2] => 9
  [1, 1, 1] => 5
  [2, 1, 0] => 2
  [3, 0, 0] => 1
  [0, 2, 1] => 8
  [0, 3, 0] => 7

But then, after I try to do the following

base=vectores_hash(3,3)
renglones=[] ; columnas=[] ; valores=[]
for elemento in keys(base)
    for indice in 1:length(elemento)
        v_n,valor=creacion_aniquilacion(indice,elemento)            
        if v_n != 0
            push!(renglones,base[v_n])
            push!(columnas,base[elemento])
            push!(valores,-valor)
        end
    end
end

I get KeyError: key [1, 0, 2] not found. Furthermore, I get false when asking vectores_hash(3,3)==base. If I ask for the keys of base I get

keys(base)
Base.KeySet for a Dict{Any,Any} with 10 entries. Keys:
  [0, 1, 2]
  [1, 1, 1]
  [0, 1, 2]
  [1, 1, 1]
  [1, 0, 2]
  [1, 1, 1]
  [2, 1, 0]
  [3, 0, 0]
  [0, 2, 1]
  [0, 3, 0]

So the key that Julia says is missing is actually not missing.

**Comment by yuyichao** [comment]
What's `vectores_hash` ?

It is undefined behavior to mutate duct key.
