### ISSUE TITLE
Generator output with explicit edges not always invalidated

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#34962]
Given an overdub-like function that explicitly sets an edge a la https://github.com/JuliaLang/julia/pull/32237:

```julia
using Core.Compiler: retrieve_code_info, CodeInfo, MethodInstance, SSAValue, SlotNumber
using Base: _methods_by_ftype

@generated function compile(f::Core.Function, tt::Type=Tuple{})
    tt = tt.parameters[1]

    # get a hold of the method and code info of the target function
    sig = Tuple{f, tt.parameters...}
    mthds = _methods_by_ftype(sig, -1, typemax(UInt))
    Base.isdispatchtuple(tt) || return(:(error("$tt is not a dispatch tuple")))
    length(mthds) == 1 || return (:(throw(MethodError(f,tt))))
    mtypes, msp, m = mthds[1]
    mi = ccall(:jl_specializations_get_linfo, Ref{MethodInstance}, (Any, Any, Any), m, mtypes, msp)
    mi.def.isva && return :(error("varargs kernel methods are not supported"))
    ci = retrieve_code_info(mi)
    @assert isa(ci, CodeInfo)

    # prepare a new code info
    new_ci = copy(ci)
    empty!(new_ci.code)
    empty!(new_ci.codelocs)
    empty!(new_ci.linetable)
    empty!(new_ci.ssaflags)
    new_ci.edges = MethodInstance[mi]

    # prepare the slots
    new_ci.slotnames = Symbol[Symbol("#self#"), :f, :tt]
    new_ci.slotflags = UInt8[0x00 for i = 1:5]

    Core.println("generator called")
    append!(new_ci.code, [Expr(:call, println, "function called"),
                          Expr(:return, nothing)])
    append!(new_ci.codelocs, [0, 0])
    new_ci.ssavaluetypes += 2

    return new_ci
end
```

Although this explicitly adds an edge from the code info returned from the generator to the original function, the generator does not get called when anything but the topmost function gets redefined:

```julia
julia> parent() = child()
parent (generic function with 1 method)

julia> child() = 3
child (generic function with 1 method)

julia> compile(parent, Tuple{})
generator called
function called

# let's redefine the child function

julia> child() = 4
child (generic function with 1 method)

julia> compile(parent, Tuple{})
function called

# generator should have been called as its output should have been invalidated!
```

If we do the same, but make sure we _call_ the parent function before redefining the child, everything works as expected (includes output of JL_DEBUG_METHOD_INVALIDATION):

```julia
julia> parent() = child()
parent (generic function with 1 method)

julia> child() = 3
child (generic function with 1 method)

julia> compile(parent, Tuple{})

generator called
function called

# call the parent

julia> parent() 
3

# redefine the child

julia> child() = 4
 parent()
  compile(typeof(Main.parent), Type{Tuple{}})
>> Main.child(...) Tuple{typeof(Main.child)}
child (generic function with 1 method)

julia> compile(parent, Tuple{})
generator called
function called
```

Presumably calling the parent sets an additional edge from the child, and I guess it shouldn't be the generator who should set that edge?

**Comment by maleadt** [comment]
> There is no meaningful sense in which that should ever have an edge to child, since it does not call child.

`parent` does call `child` though, so why wouldn't there be an edge? Are you saying we need explicit edges from the created code instance to `parent` as well as any `child` instead of only `parent` and expecting the recursion to happen automatically?

Taking back a step then: we use this in GPUCompiler.jl to perform automatic invalidation of compilation results. Say you have a function `kernel()`, which you invoke from another function `caller() = @cuda kernel()`. That macro essentially performs the trick I explained above, calling a generated function that has an edge to `kernel()` so that it gets invalidated when `kernel` **or any function it calls** get redefined. What would be the best way to realize this?

**Comment by vtjnash** [comment]
The above calls `empty!(new_ci.code)`, so the code only has edges to `println`. It is complete nonsense to assume they will magically get an edge to something they never call and explicitly don't use in any way.

**Comment by maleadt** [comment]
> It is complete nonsense to assume they will magically get an edge to something they never call and explicitly don't use in any way.

I guess my understanding of invalidation was incorrect then, as I assumed it would be a recursive process (`child` invalidating `parent` which we do have an edge to).

But again, we need something to this effect for invalidating GPU compilation results. So could you please suggest an approach that would allow this?

**Comment by aviatesk** [comment]
Backedges are collected during inference that happens after the generator generates code, that does not contain a call to `child`.
If you want to add backedge to `child` when generating `compile(parent, ...)`, you will need to do something like:
```julia
caller::MethodInstance # method instance for `parent`
callee::MethodInstance # method instance for `child`
ccall(:jl_method_instance_add_backedge, Cvoid, (Any, Any, Any), callee, nothing, caller)
```
during the code generation.

**Comment by maleadt** [comment]
> If you want to add backedge to `child` when generating `compile(parent, ...)`, you will need to do something like:
> 
> ```julia
> caller::MethodInstance # method instance for `parent`
> callee::MethodInstance # method instance for `child`
> ccall(:jl_method_instance_add_backedge, Cvoid, (Any, Any, Any), callee, nothing, caller)
> ```
> 
> during the code generation.

We're just compiling by calling `jl_create_native`, so shouldn't that happen there. Or are you suggesting that our AbsInt should do such a thing?

**Comment by maleadt** [comment]
> I meant to add backedge during code generation by `@generated` function.

We don't have a list of all called child functions during execution of that generator though.

**Comment by aviatesk** [comment]
Then the most straightforward way would be to make inference performed by `GPUInterpreter` see all the child methods.

**Comment by maleadt** [comment]
Could you elaborate? The GPUInterpreter isn't accessible to this generator.

**Comment by aviatesk** [comment]
I would like to have a concrete example where invalidation does not work as expected for GPUCompiler. We probably need some concrete names in order to discuss this issue.

**Comment by maleadt** [comment]
What's missing with the example from this issue? It's a reduced version of GPUCompiler.

**Comment by maleadt** [comment]
For the record: GPUCompiler now uses the TLS world age to trigger a world-intersecting cache lookup, and we only rely on a generator like the one used here to return a MethodInstance, which doesn't require invalidation when child functions are redefined (so the 'bug' here doesn't matter anymore).
