### ISSUE TITLE
Strange code_native output on mac

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#34961]
The `@code_llvm` for this function looks reasonable but the `@code_native` mentions `sincospi` which is quite odd:

```jl
julia> f(u) = u^8

julia> @code_llvm f(2.0)

;  @ REPL[1]:1 within `f'
define double @julia_f_17193(double) {
top:
; ┌ @ intfuncs.jl:265 within `literal_pow'
; │┌ @ math.jl:899 within `^'
    %1 = call double @llvm.pow.f64(double %0, double 8.000000e+00)
; └└
  ret double %1
}

julia> @code_native f(2.0)
        .section        __TEXT,__text,regular,pure_instructions
; ┌ @ REPL[1]:1 within `f'
        movabsq $4669889720, %rax       ## imm = 0x11658DCB8
        vmovsd  (%rax), %xmm1           ## xmm1 = mem[0],zero
        movabsq $__sincospi, %rax
; │┌ @ intfuncs.jl:265 within `literal_pow'
; ││┌ @ math.jl:899 within `^'
        jmpq    *%rax
        nopw    (%rax,%rax)
; └└└
```

**Comment by vtjnash** [comment]
We just symbolicate everything, we don't consider it a bug to print whatever that returns

**Comment by KristofferC** [comment]
Okay, feature request, don't print other random fu crions in code_native output because it is confusing.

**Comment by yuyichao** [comment]
You should attach a debugger and see what the address is and what symbol is it pointing to. It could be missing debug info or sth like that causing the lookup to be wrong and in that case the lookup or the generation of the info is the thing to fix.

I'm 80% sure I've seen cases that almost can't be fixed but I don't remember what exactly it is.

In any case I think it'll also be good to always print the numerical value as well. (That's what gdb does)

**Comment by yuyichao** [comment]
(and I don't think we should stop printing symbol names)

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/29588
