### ISSUE TITLE
Creating an abstract function via eval and specialising it, from a package into another package, leads to segfault

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/julia#35028]
Per the discussion here: 
https://discourse.julialang.org/t/register-and-specialize-a-function-in-a-different-module-package-julia-segfaults/35591/13

Attempting to 

* create a new abstract function 
* in a module 
* within a package 
* from another package 
* and specializing it 

leads to segfault. 

How to reproduce: 
1. dev this package: 
https://www.dropbox.com/s/4y9qp4epqgbidb7/EvalPkgTest.zip?dl=0

2. run 

```julia
module EvalPkgTest

using Revise

Core.eval(Revise, :(function foobar end))

function Revise.foobar() :: String
  "foo bar"
end

end # module
```

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto
```

**Comment by vtjnash** [comment]
What did you think "fatally broken" meant?
```
  ** incremental compilation may be fatally broken for this module **
```

**Comment by StefanKarpinski** [comment]
That seems like a bit too terse of a response, @vtjnash. Can you elaborate. I take it this usage is incompatible with a package being precompilable? So a package should either not do this or if it does do this, opt out of precompilation.

**Comment by essenciary** [comment]
@vtjnash As a language user, the message doesn't tell me anything. And certainly not that I should expect segfaulting. 

Not sure why this issue was closed? Is this behaviour documented and expected? If not, I would appreciate an actionable response given that this behaviour is affecting the design of my APIs and is a pretty big issue. Thanks!

**Comment by KristofferC** [comment]
It is closed because it is documented to not be allowed

https://docs.julialang.org/en/v1/manual/modules/#Module-initialization-and-precompilation-1

> Several additional restrictions are placed on the operations that can be done while precompiling code to help the user avoid other wrong-behavior situations:
> - Calling eval to cause a side-effect in another module. This will also cause a warning to be emitted when the incremental precompile flag is set.

The only actionable response is to not do that.

**Comment by essenciary** [comment]
Thanks, that's helpful! At least I know the behaviour won't change so it's worth refactoring my architecture.
