### ISSUE TITLE
introduce curried form for `startswith` and `endswith`

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#35032]
For some functions, E.g.
 -  `in(item, collection)`   where have `in(collection) = item -> in(item, collection)`
 - `lessthan(a, b)` we have `lessthan(b) = a -> lessthan(a, b)`
 - `isequal(a, b)` we have `isequal(b) = a -> isequal(a, b)`

We have a whole bunch of these implemented via `Base.Fix2`.
They are useful for using with `filter`.

I propose we add a few more:
 - `startswith(haystack, needle)` giving `startswith(needle) -> startswith(haystack, needle)`
 - `endswith(haystack, needle)` giving `endswith(needle) -> endswith(haystack, needle)`

---

This is part of a series of issues relating to  https://github.com/invenia/Wrangling.jl/pull/3
Will link others below for cross referencing.
and removing its type-piracy
https://github.com/JuliaLang/julia/issues/35031
https://github.com/JuliaLang/julia/issues/35033

**Comment by KristofferC** [comment]
Dup of #33193
