### ISSUE TITLE
SPDX license identifiers

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35042]
Should we adopt the SPDX license identifiers in the package registry? I see them in a few projects nowadays and sounds like a good idea generally.

https://spdx.org/licenses/

**Comment by ViralBShah** [comment]
Discussed earlier in https://github.com/JuliaLang/julia/issues/6095. The main reason to use this is in my opinion, is the standard identifiers for licenses.

**Comment by StefanKarpinski** [comment]
Seems like a good idea. Where would we use them? In this LICENSE.md document? There's also apparently a new THIRD_PARTY_SOFTWARE.md file for listing the licenses of dependencies.

**Comment by ViralBShah** [comment]
I see projects using the identifiers in all the source files. E.g. https://git.musl-libc.org/cgit/musl/tree/src/math/log.c

**Comment by ViralBShah** [comment]
Does Github use different identifiers in THIRD_PARTY_SOFTWARE.md than SPDX?

**Comment by ViralBShah** [comment]
Is this better filed in the Pkg.jl repo?

**Comment by StefanKarpinski** [comment]
Maybe. I suspect that this should go into project files in a standardized way. Perhaps having a top-level `license` key whose value should be an SPDX identifier. We could start requiring packages to have that key when they register new versions in order to qualify for automerging. We'd also want to capture the licenses of dependencies somehow using SPDX identifiers.

**Comment by SamuraiAku** [comment]
A good reason to add SPDX is to ease corporate approvals. At my company they insist that every open source software be scanned with automated tools that extract all the license info. If the automated scan is successful it greatly reduces the amount of manpower and time it takes to review and approve.  They will not approve anything for production use unless they are certain that all licenses are acceptable. This includes any new revisions no matter how minor.

So it would make sense to also add SPDX headers to Julia itself, not jus the packages.

**Comment by ViralBShah** [comment]
What's the exact text for these?

**Comment by SamuraiAku** [comment]
I couldn't tell you the text off the top of my head. I'd have to read the specification at https://spdx.dev/ and get back to you.

**Comment by SamuraiAku** [comment]
After reading through the specifications and the SPDX website, I believe that the SPDX short header should be added to the top of the header in all files created by the Julia project. The format of the header is:
`# SPDX-License-Identifier: MIT` 
replacing the # for whatever happens to indicate a comment line in each file type

For a description of the SPDX short header:
[https://spdx.dev/ids/](url)

The exact license that SPDX says is the MIT license can be found here
[https://spdx.org/licenses/MIT.html](url)

There is a very slight difference between the SPDX license and the one Julia uses. On the second line:

> The above copyright notice and this permission notice (including the next paragraph) shall be included in all copies or substantial portions of the Software.

vs.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.


This should probably be cleared up in a future PR, to resolve any ambiguity.

As for other libraries used in Julia, it would be good to go through and see if they have included SPDX headers in their code. If not, consider if it is a good idea/permissible for the Julia program to add them.

An alternative/supplement to modifying the library files would be the creation of an SPDX file. As I read the specification, that can be used to list all of the different libraries contained in Julia plus their licenses and other relevant information in a human-readable and machine-processable format.  It's fairly complicated and not a trivial undertaking. There are supposedly tools out there that could help with the automated generation of such a file. For more information see:
[https://spdx.dev/resources/use/#documents](url)

**Comment by vtjnash** [comment]
I think we have SDPX now
