### ISSUE TITLE
Bug: Base.operator_associativity(:(||))

### ISSUE THREAD

**Issue by llffyy2971** [JuliaLang/julia#35044]
I'm running julia-latest from on Windows 10. When I try `Base.operator_associativity(:(||))`, I got the result:

```julia
julia> Base.operator_associativity(:(||))
:left
```
but
```julia
julia> exp = :(a || b || c || d)
:(a || (b || (c || d)))
```
I think It should be associate to the right. So maybe there is a bug in Base show.jl, maybe at 905: 
`const prec_control_flow = operator_precedence(:(&&))` 
Forget the definition for `:(||)`.
or  927:
```julia{.numberLines}
function operator_associativity(s::Symbol)
    if operator_precedence(s) in (prec_arrow, prec_assignment, prec_control_flow, prec_pair, prec_power) ||
        (isunaryoperator(s) && !is_unary_and_binary_operator(s)) || s === :<|          # || s === :||
        return :right
    elseif operator_precedence(s) in (0, prec_comparison) || s in (:+, :++, :*)
        return :none
    end
    return :left
end
```
Here I add `|| s === :||` at the end of  line three to solve this problem.

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, cannonlake)
```

**Comment by JeffBezanson** [comment]
Yes, you're right. Care to make a PR? I'd also remove the variable `prec_control_flow`; it's confusing since there are 2 precedence levels for && and || separately.

**Comment by llffyy2971** [comment]
Sorry, I'm not a developer and I'm not familiar with github too. So I don't know how to make a PR. Please do it for me,  thank you.

**Comment by FelipeGLopez** [comment]
@llffyy2971 I'll make the PR for you (if you want).

**Comment by llffyy2971** [comment]
@FelipeGLopez Yes, please, Thanks.
