### ISSUE TITLE
slow Schur factorization for Hermitian matrices

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#35054]
For a Hermitian matrix, Schur factorization is equivalent to the eigenvalue decomposition, but it seems to be much slower:
```jl
julia> A = rand(1000,1000); H = Symmetric(A);

julia> @btime eigen($H);
  141.423 ms (15 allocations: 23.25 MiB)

julia> @btime schur($H);
  502.031 ms (13 allocations: 23.16 MiB)
```
Seems like we just need some specialized methods for `schur`?

**Comment by andreasnoack** [comment]
Yes. Currently, `schur` will dispatch to the method for general matrices whereas `eigen` will use a symmetric solver.

**Comment by stevengj** [comment]
Should be pretty trivial to implement a specialized method here, so marking as a good first issue.
