### ISSUE TITLE
Make REPL ask if you want to install a package, rather than throwing error?

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#35062]
Right now if I using a package that is not installed in my current enviroment, julia errors.
It would be nice if the REPL was a bit more friendly and was like "Do you want to install it?"

### Current behavour:

```julia
julia> using Example
ERROR: ArgumentError: Package Example not found in current path:
- Run `import Pkg; Pkg.add("Example")` to install the Example package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:887
```
Not too bad, it tells you want command to run.
But better still would be to just give user option to run it.

### Desired behavour

```
julia> using Example
ERROR: Package Example not found in current path:
Do you want to install the Example package? (Y/N)
> Y 
Running `import Pkg; Pkg.add("Example"); using Example`
...
julia>
```

MikTeX on windows does this (though with a GUI pop-up).
Julia and TeX are similar in that they are batteries not included, install dozens of packages to get things done.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/pull/26469

**Comment by oxinabox** [comment]
Closed by https://github.com/JuliaLang/julia/pull/39026
