### ISSUE TITLE
rename `rand` to `random`

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#35073]
in the julian spirit of not abbreviating things (e.g. https://github.com/JuliaLang/julia/issues/31643).  obviously can't happen before 2.0.  apologies if this has been discussed before and i missed it.

**Comment by JeffBezanson** [comment]
`rand` has been used in many languages and I don't think it's overly obscure. This would be a really spurious change.

**Comment by rfourquet** [comment]
Also, what about related functions? `randomnormal`, `randomexponential`, `sprandomnormal` (or is it `sparserandomnormal` ?) etc. (unless these are suppressed in 2.0 in favor of `rand(om)(Normal())` etc, but this will probably not happen).

**Comment by KristofferC** [comment]
> `rand(om)(Normal())`

![image](https://user-images.githubusercontent.com/1282691/76446057-c0f24a00-63c6-11ea-9b5b-36a71a6f8b68.png)

**Comment by bjarthur** [comment]
i value consistency in naming conventions over conforming to convention in other languages.  two extra letters is not that much more verbose.  julia is a "fresh approach" afterall--  perfect opportunity for change.

**Comment by JeffBezanson** [comment]
Perfect consistency in this regard is not attainable. Are we really going to stop using abbreviations entirely?

**Comment by KristofferC** [comment]
This churn here is unlikely to be worth it. Don'ttthink this needs to be kept open.
