### ISSUE TITLE
Naming of the macOS Julia download

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#35091]
Hey all, I wanted to inquire as to why the name of the Julia 1.3.1 download is Julia 1.3? This always conflicts with the existing 1.3.0 download. Is there a reason for not making the name "Julia 1.3.1"? 

<img width="882" alt="Screen Shot 2020-03-12 at 10 35 14 AM" src="https://user-images.githubusercontent.com/35577566/76532738-6d770f00-644d-11ea-9947-bb066e70557b.png">

@ararslan

**Comment by ViralBShah** [comment]
Pretty sure this was discussed earlier and changed to this.

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/issues/10697

**Comment by logankilpatrick** [comment]
Ah, cool. Thanks!
