### ISSUE TITLE
hash and isequal are not always in sync for Type

### ISSUE THREAD

**Issue by TimSheard** [JuliaLang/julia#35104]
The manual says
hash(x[, h::UInt])
Compute an integer hash code such that isequal(x,y) implies hash(x)==hash(y).

But I ran across an example where that is not the case when x is a Type. Here is a complete transcript of how to reproduce the error.
"""
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> r1 = Array{a,b} where b where a
Array{a,b} where b where a

julia> r2 = Array{a,x} where x where a
Array{a,x} where x where a

julia> isequal(r1,r2)
true

julia> hash(r1)
0x6995f46ceec15d03

julia> hash(r2)
0x1e08ed56ec0c9334
"""

**Comment by yuyichao** [comment]
AFAICT dup of https://github.com/JuliaLang/julia/issues/26105
