### ISSUE TITLE
Unable to increment an int variable inside a simple loop - claims it is undeclared v1.3.0

### ISSUE THREAD

**Issue by semi-cylonator** [JuliaLang/julia#35107]
#!/usr/bin/env julia

# Julia v1.3.0

num = 10
println(num)

num += num			# This works fine.
println(num)

# Can increment `num` inside this construct
if 20 == num
	println(num)
	num += num		# This works fine.
	println(num)
end

# Cannot increment `num` inside this loop
while (num > 0)
	num = num - 1		# Get undefined error
	num += num		# Get undefined error
end

##################################
# PROGRAM OUTPUT
##################################
10
20
20
40
ERROR: LoadError: UndefVarError: num not defined

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
