### ISSUE TITLE
Method definition overwritten warning could be more helpful...

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#35140]
...in the case that a file is included twice. In that case, it shows up as

```julia
WARNING: Method definition (::Type{PseudoArcLengthContinuation.DefaultLS})() in module PseudoArcLengthContinuation at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/LinearSolver.jl:62 overwritten at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/LinearSolver.jl:62.
  ** incremental compilation may be fatally broken for this module **
```

(example from Slack). This is actually really helpful if you know the only way a method at `LinearSolver.jl:62` can overwrite a method at `LinearSolver.jl:62` is if the code is being evaluated twice, i.e., a duplicated `include` statement, but is pretty confusing if you don't realize that is possiblity. I propose adding a check to see if the file path and line number is the same for the two methods, and in that case changing the warning to something like

```julia
WARNING: Method definition (::Type{PseudoArcLengthContinuation.DefaultLS})() in module PseudoArcLengthContinuation at /Users/rveltz/work/prog_gd/julia/dev/dev1/PseudoArcLengthContinuation.jl/src/LinearSolver.jl:62 evaluated twice. Check for duplicate `include` statements.
  ** incremental compilation may be fatally broken for this module **
```

The warning is generated here https://github.com/JuliaLang/julia/blob/3b53f54a5e612cfc402f561d71cdbfb40da3529e/src/gf.c#L1372-L1387 but I don't really know C, so I filed this issue instead of making a PR.

**Comment by vtjnash** [comment]
The risk here (with the proposed change) is that having `f() = 1; f() = 2` on a line would print that same message. I'll make a PR with something similar however
