### ISSUE TITLE
@testset namespace does not copy redefined variables

### ISSUE THREAD

**Issue by Byrth** [JuliaLang/julia#35145]
It is very possible that this is intentional, but I didn't get a reply on Slack and the MVE is simple so I figured I'd drop it here:

~~~julia
using Test
a = 5
@testset begin
    println(a)
    a = 6
end
~~~

This causes an error about a being undefined on the `println(a)` line. The error can be resolved either by removing `@testset`, `println(a)`, or `a = 6`. From that, I infer that `@testset` is setting up some kind of independent namespace/scope to run tests in (makes sense) and copies variables to it, but intentionally avoids copying (instead of deepcopying) variables that are defined inside of the `@testset` block.

I have only two guesses:
1) simple bug
2) intentional due to some kind of variable type leakage concern

Julia v1.3.1

**Comment by KristofferC** [comment]
Same as

```
julia> a = 5
5

julia> let
           println(a)
           a = 3
       end
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope at REPL[2]:2
```

The `a` is local to the scope and has not yet been defined.
