### ISSUE TITLE
Check arguments when constructing a Tridiagonal matrix

### ISSUE THREAD

**Issue by ranocha** [JuliaLang/julia#35167]
When a `Tridiagonal` matrix is constructed, the vectors for the lower and upper diagonal are not checked for equality. This can result in unexpected behavior if inplace factorizations are used.
```julia
julia> using LinearAlgebra

julia> dl = [-1., -1., -1.]; d = [2., 2., 2., 2.]; b = [1, 2, 3, 4];

julia> Tcopy = Tridiagonal(dl, d, copy(dl))
4×4 Tridiagonal{Float64,Array{Float64,1}}:
  2.0  -1.0    ⋅     ⋅ 
 -1.0   2.0  -1.0    ⋅ 
   ⋅   -1.0   2.0  -1.0
   ⋅     ⋅   -1.0   2.0

julia> Tcopy \ b
4-element Array{Float64,1}:
 3.9999999999999987
 6.999999999999997
 7.999999999999997
 5.999999999999999

julia> lu!(Tcopy) \ b # is okay
4-element Array{Float64,1}:
 3.9999999999999987
 6.999999999999997
 7.999999999999997
 5.999999999999999

julia> dl = [-1., -1., -1.]; d = [2., 2., 2., 2.]; b = [1, 2, 3, 4];

julia> Tnocopy = Tridiagonal(dl, d, dl)
4×4 Tridiagonal{Float64,Array{Float64,1}}:
  2.0  -1.0    ⋅     ⋅ 
 -1.0   2.0  -1.0    ⋅ 
   ⋅   -1.0   2.0  -1.0
   ⋅     ⋅   -1.0   2.0

julia> Tnocopy \ b
4-element Array{Float64,1}:
 3.9999999999999987
 6.999999999999997
 7.999999999999997
 5.999999999999999

julia> lu!(Tnocopy) \ b # is not okay
4-element Array{Float64,1}:
 1.1910926043269665
 2.764370417307866
 4.09088440300534
 4.04544220150267
```
Would it be better/reasonable/useful to add a check whether `dl === du` in the constructor `Tridiagonal(dl, d, du)` and give a warning/error?

I'm using Julia version 1.4.0-rc1.0 (2020-01-23).

**Comment by andreasnoack** [comment]
For methods that don't mutate, it's not a problem so maybe such a check should be part of the mutating function. The alternative is to write in the documentation for the mutating methods that the off-diagonals cannot alias.

**Comment by ranocha** [comment]
For me, adding a check for the mutating methods and some additional documentation sounds good. Are other methods besides `lu!` mutating for `Tridiagonal`?

**Comment by andreasnoack** [comment]
> Are other methods besides `lu!` mutating for `Tridiagonal`?

Np. That should be the only one for `Tridiagonal`.

**Comment by ranocha** [comment]
Okay, thanks. I've opened a PR (#35197) to add this check.
