### ISSUE TITLE
skipnan

### ISSUE THREAD

**Issue by mileslucas** [JuliaLang/julia#35162]
# Feature Request: `skipnan`

This would be a wrapper for an iterator similar to [`skipmissing`](https://github.com/JuliaLang/julia/blob/7f28d91b70b43ed948ac0e02c3ebbe78e010e030/base/missing.jl#L183-L382)

My idea for implementation would be almost exactly the same as above, but substituting `missing` for `NaN`. 

This is something I'd love to see in Base, and would allow NaN-math to be much simpler. This is something we use in my field all the time (e.g. masking bad-pixels on a CCD image). For now, the best I can do is
```julia
X = randn(100, 100)
@. X[X < 0] = NaN
d = @view X[X .!== NaN]
```
This works fine for doing math that doesn't care about dimensions (e.g. the median value of a chunk of an image), but having a way to skip the NaNs while maintaining the correct dimensionality would be awesome!

## Example Usage
Simple example (that can be done using boolean mask as above)
```julia
using Statistics
X = randn(100, 100)
@. X[X < 0] = NaN

mean(X)
# output
NaN

mean(skipnan(X))
# output
0.8218980637076255
```
Example that cannot be replicated
```julia
using Statistics
X = [0 1 NaN NaN;
        3 4 2 NaN]

mean(X, dims=1)[1, :]
# output
4-element Array{Float64,1}:
   1.5
   2.5
 NaN  
 NaN

mean(skipnan(X), dims=1)[1, :]
# output
4-element Array{Float64,1}:
   1.5
   2.5
   2.0  
 NaN
```

## Development
If it is as simple as implementing the `skipmissing` code but for `NaN` I can make the PR. If there are more nuanced optimizations/functions I may require assistance. If it is not close at all to what `skipmissing` looks like I may not be able to help, depending on the difficulty of implementation.

**Comment by KristofferC** [comment]
What's wrong with using `Iterators.filter`? It seems excessive to add too many special cases to `skipXXX`.

**Comment by mileslucas** [comment]
That just doesn't work for the example usage I provided.
```julia
julia> X = randn(3, 5)
3×5 Array{Float64,2}:
 -1.05243   -0.522856  -0.463135  -1.30935   0.0347664
 -0.854061  -0.179277   1.08639    1.2135   -0.526978
 -0.236869  -1.43604    0.980726  -1.52754  -0.336259

julia> @. X[X < 0] = NaN
11-element view(::Array{Float64,1}, [1, 2, 3, 4, 5, 6, 7, 10, 12, 14, 15]) with eltype Float64:
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN
 NaN

julia> using Statistics

julia> itr = Iterators.filter(!isnan, X)
Base.Iterators.Filter{Base.var"#58#59"{typeof(isnan)},Array{Float64,2}}(Base.var"#58#59"{typeof(isnan)}(isnan), [NaN NaN … NaN 0.03476643776606024; NaN NaN … 1.213495694678029 NaN; NaN NaN … NaN NaN])

julia> mean(itr, dims=1)
ERROR: MethodError: no method matching mean(::Base.Iterators.Filter{Base.var"#58#59"{typeof(isnan)},Array{Float64,2}}; dims=1)
Closest candidates are:
  mean(::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:42 got unsupported keyword argument "dims"
  mean(::Any, ::AbstractArray; dims) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:98
  mean(::Any, ::Any) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:58 got unsupported keyword argument "dims"
  ...
Stacktrace:
 [1] top-level scope at REPL[5]:1

julia> mean(collect(itr), dims=1)
1-element Array{Float64,1}:
 0.828844905855584
```
when the filtering happens, it always coerces whatever input into a vector.

**Comment by KristofferC** [comment]
That code doesn't work with `skipmissing` either though.

**Comment by tk3369** [comment]
Nothing wrong with `Iterators.filter` except that it's twice as verbose. Given that `NaN` is something that everyone deals with all the time, it seems much nicer if we have `skipnan`:

```
Iterators.filter(!isnan, x)
skipnan(x)
```

As with the `mean` function issue above, it probably needs to be fixed with another kwarg?

**Comment by KristofferC** [comment]
Just define it locally if you need to then? Many times you need to skip 1 and 0 and all kinds of different values.

**Comment by tlienart** [comment]
Maybe a way forward here could be to just add @KristofferC's suggestion to the doc-string of `skipmissing` i.e.

```
"""
    skipmissing(itr)

Return an iterator over the elements in `itr` skipping [`missing`](@ref) values.
The returned object can be indexed using indices of `itr` if the latter is indexable.
Indices corresponding to missing values are not valid: they are skipped by [`keys`](@ref)
and [`eachindex`](@ref), and a `MissingException` is thrown when trying to use them.
Use [`collect`](@ref) to obtain an `Array` containing the non-`missing` values in
`itr`. Note that even if `itr` is a multidimensional array, the result will always
be a `Vector` since it is not possible to remove missings while preserving dimensions
of the input.

To build an iterator that skips over entries not respecting a condition (e.g. skips over
`NaN`), you can use `Iterators.filter(check, itr)` (e.g. `Iterators.filter(!isnan, itr)`).

# Examples
```jldoctest
julia> x = skipmissing([1, missing, 2])
skipmissing(Union{Missing, Int64}[1, missing, 2])

julia> sum(x)
3

julia> x[1]
1

julia> x[2]
ERROR: MissingException: the value at index (2,) is missing
[...]

julia> argmax(x)
3

julia> collect(keys(x))
2-element Vector{Int64}:
 1
 3

julia> collect(skipmissing([1, missing, 2]))
2-element Vector{Int64}:
 1
 2

julia> collect(skipmissing([1 missing; 2 missing]))
2-element Vector{Int64}:
 1
 2
```
"""
```

**Comment by cossio** [comment]
Relevant: https://github.com/JuliaRegistries/General/pull/59081

**Comment by alexriss** [comment]
Thank you for posting the link here.

`skipmissing` actually does more than just being an iterator - for instance it preserves indices. That is why I made this small `skipnan` package that mimics/copies the `skipmissing` functionality.

> Relevant: [JuliaRegistries/General#59081](https://github.com/JuliaRegistries/General/pull/59081)

**Comment by giordano** [comment]
[`Skipper.jl`](https://gitlab.com/aplavin/Skipper.jl) by @aplavin works like that.

**Comment by LilithHafner** [comment]
Lovely! I think `skip(isnan, x)` is what the OP asked for. Feel free to reopen if not.
