### ISSUE TITLE
WeakRef can access finalized object

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#35169]
The following demonstrates that there is a window in time where an object has been finalized/~collected~, but any WeakRef pointing to it hasn't been updated yet (i.e. `weak_ref.value` hasn't been set to `nothing`). This could lead to ~memory corruption~, use of invalid object state, etc:

```julia
# dummy struct that wraps a pointers and sets it to NULL during finalization

julia> mutable struct Dummy
       ptr::Ptr{Cvoid}
         function Dummy()
           obj = new(rand(Int))
           finalizer(obj) do obj
             println("Finalizing $obj")
             obj.ptr = C_NULL
           end
           obj
         end
       end

julia> Base.isequal(obj::Dummy, x) = println("Loading $(obj.ptr)")


julia> a = Dummy()
Dummy(Ptr{Nothing} @0x5d1cba49e4603540)

julia> Base.isequal(a, 1)
Loading Ptr{Nothing} @0x5d1cba49e4603540


julia> b = WeakRef(a)
WeakRef(Dummy(Ptr{Nothing} @0x5d1cba49e4603540))

julia> b == 1
Loading Ptr{Nothing} @0x5d1cba49e4603540


julia> a = nothing

julia> GC.gc(true)
Finalizing Dummy(Ptr{Nothing} @0x5d1cba49e4603540)

# at this point, Dummy is collected but the WeakRef doesn't contain `nothing`
# and operations might use invalid objects or freed memory!

julia> b
WeakRef(Dummy(Ptr{Nothing} @0x0000000000000000))

julia> b == 1
Loading Ptr{Nothing} @0x0000000000000000

# second GC cycle fixes this

julia> GC.gc(true)

julia> b
WeakRef(nothing)
```

I guess this could also be problematic for WeakKeyDict (is why I used isequal as an example here).

**Comment by yuyichao** [comment]
This is the correct and expected behavior. `WeakRef` tells you if the object is freed and finalizer prepares the object before it can be freed. A finalized object is by all mean still valid and since finalizer is a user provided function,  it's basically impossible for the two to agree with each other.

In fact, `WeakRef` is merely another way to access a finalized object, you have access to that object in the finalizer and can even keep it alive in the finalizer.

**Comment by thofma** [comment]
(This has been fixed in https://github.com/JuliaLang/julia/pull/38180)

**Comment by tthsqe12** [comment]
Indeed, and the main point of #38180 should read
The most significant change here is that I'm changing the way Weak*Ref* works:
