### ISSUE TITLE
`only` does not appear in docs search

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#35173]
The docs for `Base.Iterators.only` appear here: https://docs.julialang.org/en/v1.5-dev/base/iterators/#Base.Iterators.only

However, it does not show up in the search results: https://docs.julialang.org/en/v1.5-dev/search/?q=only

Even though `accumulate`, which was added later, does: https://docs.julialang.org/en/v1.5-dev/search/?q=accumulate#

**Comment by visr** [comment]
Ha, that is because `only` appears in the Documenter search stop word filter. I previously already filtered `names(Base)` out of the list, but this is a new export.

Should be fixed by https://github.com/JuliaDocs/Documenter.jl/pull/1264.
