### ISSUE TITLE
Function to combine nested arrays into multidimensional array

### ISSUE THREAD

**Issue by ludwigwinkler** [JuliaLang/julia#35170]
Hi,

is technically feasible to add a function to combine an arbitrary combination of nested, arrays into a single multidimensional array?

Something akin to
`data = [ [ones(13,14) for i in 1:12] for j in 1:11]` -> combine to array of size `(11, 12, 13, 14)`.

**Comment by fredrikekre** [comment]
xref #21672, #27188,  #31636

**Comment by mcabbott** [comment]
Also [on discourse](https://discourse.julialang.org/t/nested-vectors-arrays-to-multidimensional-tensor/36186), where I pushed [LazyStack.jl](https://github.com/mcabbott/LazyStack.jl) as a package for this.

It also tries to cover reductions of generators, for which I now see #31644 too.

**Comment by ludwigwinkler** [comment]
Closing since we migrated to gitlab
