### ISSUE TITLE
ERROR: could not open file boot.jl

### ISSUE THREAD

**Issue by YousefSaber** [JuliaLang/julia#35189]
Ubuntu: 19.10
Julia: 1.3.1
when I try to generate LLVM bitcode I got this error 
```
joseph@joseph-X541UJ:~/Documents/Julia$ julia --output-bc test.jl
ERROR: could not open file boot.jl
```
my `test.jl` file contains 
```
print("Hello World")
```
please show me step by step how to fix this issue I'm very begginer.

**Comment by yuyichao** [comment]
I believe this is a question that belongs to discourse.julialang.org .

**Comment by YousefSaber** [comment]
@yuyichao https://discourse.julialang.org/t/error-could-not-open-file-boot-jl/36277
