### ISSUE TITLE
deepcopy can copy closure state, in spite of what docstring says

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#35190]
The docstring says:

>As a special case, functions can only be actually deep-copied if they are anonymous, otherwise they are just copied. The difference is only relevant in the case of closures, i.e. functions which may contain hidden internal references.

git blame says this is > 3 years old (in a move from helpdb), so it likely predates the closure redesign. Now it works fine:

```julia
julia> function summer()
           start=0
           inc() = start+=1
       end
summer (generic function with 1 method)

julia> s1 = summer()
(::var"#inc#832") (generic function with 1 method)

julia> s2 = deepcopy(s1)
(::var"#inc#832") (generic function with 1 method)

julia> s1()
1

julia> s1()
2

julia> s2()
1
```

**Comment by JeffBezanson** [comment]
Yes; care to make a PR just deleting that paragraph from the docstring?
