### ISSUE TITLE
Separating out Sparse matrix capability into separate repo

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35204]
As was done with `Statistics.jl` in #33399, it would be a good idea to do the same for sparse matrix capabilities. Are there any arguments against doing this? 

I propose moving `stdlib/SparseArrays` and `stdlib/SuiteSparse` into external repos.

**Comment by ViralBShah** [comment]
I am not sure how to provide binary dependencies since those files go into `deps`. Perhaps should also wait for @staticfloat 's work on #35193 which may address some of this.

**Comment by andreasnoack** [comment]
I think we'd have to deprecate some methods in LinearAlgebra before we can do this. E.g.
```julia
julia> similar(Bidiagonal(ones(4), ones(3), :L), (4,3))
4×3 SparseArrays.SparseMatrixCSC{Float64,Int64} with 0 stored entries
```
I also think there are some broadcasting combinations of special LinearAlgebra that produce a `SparseMatrixCSC` but I cannot reproduce an example on top of my head. Somebody should probably just try to remove `SparseArrays` and `SuiteSparse` and run the LinearAlgebra tests to see what fails.

**Comment by KristofferC** [comment]
Note that this issue seems to only be about the place where the code for the SparseArrays stdlib resides.

It doesn't change anything when it comes to what goes into the sysimage.

**Comment by andreasnoack** [comment]
> It doesn't change anything when it comes to what goes into the sysimage.

Thanks for clarifying that. Indeed, I assumed that it would no longer go into the sysimage.

**Comment by ViralBShah** [comment]
> Note that this issue seems to only be about the place where the code for the SparseArrays stdlib resides.
> 
> It doesn't change anything when it comes to what goes into the sysimage.

That's right.

**Comment by ViralBShah** [comment]
We also want to eventually move SparseArrays and SuiteSparse out of the system image, to pave the way for a variety of other sparse matrix improvements.

**Comment by ViralBShah** [comment]
Dup of #22698
