### ISSUE TITLE
Mac binaries need to be notarized for 1.4.0

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35211]
Just filing this as a reminder to re-upload 1.4 mac binaries with notarization.

Cc @staticfloat

**Comment by conradwt** [comment]
@ViralBShah Yes, I tried and I'm getting the following dialog:

![Screen Shot 2020-03-21 at 10 43 53 PM](https://user-images.githubusercontent.com/20219/77243298-b8b7bd00-6bc5-11ea-9dc1-6cc0f83faf56.png)

I would recommend performing the notarization as part of the build process.  If the notarization fails for any reason, one will get an e-mail of the actual status from Apple.

**Comment by ViralBShah** [comment]
@staticfloat is on it. The notarization often takes several hours or days. We probably need to make sure we do it going forward before the binaries are released.

**Comment by ViralBShah** [comment]
Binaries are notarized now.
