### ISSUE TITLE
Broken link for julia-1.4.0.pdf?

### ISSUE THREAD

**Issue by dslate1** [JuliaLang/julia#35212]
On the Julia 1.4 Documentation page, the link to julia-1.4.0.pdf (https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.4.0.pdf) seems to be broken.

**Comment by ViralBShah** [comment]
We had the same issue with 1.3.0.

#33968 is the tracking issue.

**Comment by dslate1** [comment]
Just a thought: perhaps when you post a link like that, someone should actually verify that it works?

**Comment by fredrikekre** [comment]
> Just a thought: perhaps when you post a link like that, someone should actually verify that it works?

Yea, perhaps. We only have so many volunteers. Would be great if you wanted to get involved!

Anyway, I spent the day (literally) fixing the root cause so the pdf is up now.

**Comment by ViralBShah** [comment]
I would second @fredrikekre here. We always need more help. So, even testing these things out in the RC process and opening small PRs to make things polished would be a great help. 

@fredrikekre thanks for chasing this one!

**Comment by dslate1** [comment]
Thanks guys for fixing the link to julia-1.4.0.pdf. Actually, when I first discovered Julia back in 2012 I became fairly active in reporting and discussing issues with your dev group, mostly involving documentation although some about Julia's behavior itself. Then I abandoned Julia for several years, primarily because I got heavily into using R for machine learning purposes, such as Kaggle contests, and I didn't think Julia was ready to replace R in that regard.  Then recently, in my eternal search for better programming languages, I decided to see how Julia had progressed.  So I dusted off some old Julia code I had written and got it working (after a bunch of mods to conform to 8 years of changes to the language).  I also tried out the R package JuliaCall to see if I could combine the versatility of R with the hopefully better execution speed of Julia for low level code.  Although JuliaCall seems to work fairly well (except for some problem involving crashes during parallel processing), I found it a bit too confusing to keep switching my 75 year old brain between the two languages.

I like a lot of the ideas in Julia, such as the type system, multiple dispatch, transparent conversions and promotions, just-in-time compilation, etc., so I hope it continues to progress.  You may yet hear from me again if I encounter issues worth reporting.

**Comment by ViralBShah** [comment]
Thank you for that note, and we would certainly like to hear issues you run into. Avoiding switching between two languages is precisely why we started Julia, so I can certainly sympathize!
