### ISSUE TITLE
[v1.4] "LLVM ERROR: Symbols not found:" when running AccurateArithmetic tests

### ISSUE THREAD

**Issue by helgee** [JuliaLang/julia#35223]
This is not an MWE but I want to get the ball rolling. Running the test suite of ~AstroBase.jl~ AccurateArithmetic.jl fails with this as the only output:
```
LLVM ERROR: Symbols not found: { _llvm.experimental.vector.reduce.v2.fadd.f64.v4f64 }
```
### Steps to reproduce

~- Clone [AstroBase.jl](https://github.com/JuliaAstro/AstroBase.jl) and switch to branch `he/refactor`~
- Run tests of AccurateArithmetic.jl

### Additional Info

- On v1.3 the tests fail because of some `UndefVarError`s. That is the expected behavior.
    - Commenting out those offending tests does not help on v1.4
- The culprit seems to be AccurateArithmetic.jl

CC: @chriselrod, @ffevotte, @JeffreySarnoff

**Comment by ffevotte** [comment]
I can reproduce this, both on my machine and on travis.

What seems strange to me is that tests pass with julia nightly. See for example the last travis test results:
- [v1.4](https://travis-ci.org/github/JuliaMath/AccurateArithmetic.jl/jobs/665593775)
- [nightly](https://travis-ci.org/github/JuliaMath/AccurateArithmetic.jl/jobs/665593778)

**Comment by KristofferC** [comment]
File a bug report with SIMDPirates.jl

**Comment by ffevotte** [comment]
But how come everything works with 1.3 and nightly, but not 1.4?

**Comment by KristofferC** [comment]
Because it is a bug in SIMDPirates.jl...

**Comment by helgee** [comment]
> File a bug report with SIMDPirates.jl (the `v2` experimental reductions are only available on LLVM 9 and later).

Done

**Comment by chriselrod** [comment]
That was my mistake. I checked the [LLVM 8 language reference](https://releases.llvm.org/8.0.1/docs/LangRef.html#llvm-experimental-vector-reduce-fadd-intrinsic), found experimental reduce fadd, and didn't look closely enough to see that it was different from the v2, two-argument, variants present in LLVM 9 and beyond.

Given that AccurateArithmetic has had a few SIMDPirates-related issues before, and SIMDPirates didn't have a test suite, [this](https://github.com/chriselrod/SIMDPirates.jl/blob/master/test/runtests.jl) is its new `runtests.jl`. A bad solution, but still an improvement.
I normally run LoopVectorization's tests on my own computer after every change, but these take a long time on Travis.

They also allowed this (an LLVM 8-bug) to slip through the cracks.
