### ISSUE TITLE
libstdc++ in Julia is outdated compared to the system (Linux) one

### ISSUE THREAD

**Issue by dav2017** [JuliaLang/julia#35224]
`libstdc++.so.6: version `GLIBCXX_3.4.26' not found`

My system: Manjaro Linux
Julia version: both 1.3.1 and 1.4.0

The error is the same described [on Discourse here](https://discourse.julialang.org/t/glibcxx-3-4-26-not-found-in-rcall/29113/11?u=laborg) and can be temporarily solved in the same way.
**The problem**: libstdc++ coming with Julia is outdated compared to the system one.
**A workaround** is to copy (or link) the system libstdc++.so.6 to the Julia folder:
`cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 $JULIA_HOME/lib/julia/`

I recently experienced the problem using PyPlot, which resulted in the following error (I submitted the same issue [here in PyPlot.jl](https://github.com/JuliaPy/PyPlot.jl/issues/469)):
```
ERROR: InitError: PyError (PyImport_ImportModule

The Python package matplotlib could not be found by pyimport. Usually this means
that you did not install matplotlib in the Python version being used by PyCall.
[...]
ImportError("/usr/local/julia-1.4.0/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/python3.8/site-packages/matplotlib/ft2font.cpython-38-x86_64-linux-gnu.so)")
```

**Comment by laborg** [comment]
I think this is a duplicate to: https://github.com/JuliaLang/julia/issues/34276
(I'll link the issue on discourse to make it more accessible)
