### ISSUE TITLE
Doc string for Base.Generator is slightly clumsy

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#35226]
"The syntax `f(x) for  x in iter [if cond(x)::Bool]` is syntax for constructing an instance of this type."

is better written

"The syntax for constructing an instance of this type is `f(x) for  x in iter [if cond(x)::Bool] `."

**Comment by r0cketr1kky** [comment]
I would like to take this up if possible.

**Comment by StefanKarpinski** [comment]
Go for it.
