### ISSUE TITLE
Inaccurate printing of TypeError message

### ISSUE THREAD

**Issue by englhardt** [JuliaLang/julia#35231]
While the examples below are clear cases where the user did not RTFM, they are still confusing and we could improve the error message:

#### `isa`

```
julia> isa(1, Int64)
true
julia> isa(Int64, 1)
ERROR: TypeError: in isa, expected Type, got Int64
Stacktrace:
 [1] top-level scope at REPL[5]:1
```
`Int64` is a Type so we should prompt that the user passed the value `1` instead of a `Type`:
**Expected**: `ERROR: TypeError: in isa, expected Type, got 1.`

#### `Union`
```
julia> Union{Real, nothing}
ERROR: TypeError: in Union, expected Type, got Nothing
Stacktrace:
 [1] top-level scope at REPL[8]:1
```
Similar to `isa(Nothing, nothing)` that yields a similar error.
**Expected**: `ERROR: TypeError: in isa, expected Type, got nothing.`

As far as I can see, this part of the string in the `TypeError` message is generated by the macro [@nospecialize](https://github.com/JuliaLang/julia/blob/6aa0d924ff5431318a6c79c7c9ce3a87297170d0/base/boot.jl#L220) in Base.

```
julia> versioninfo()
Julia Version 1.5.0-DEV.494
Commit 59d7522eae (2020-03-23 03:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by jakobnissen** [comment]
The behaviour is correct, no? In the first case, the function expects a Type for the second argument, and you passed it `1`, which is indeed a `Int64`. In the second case, it expects a type, and gets `nothing`, an instance of `Nothing`.

Maybe it could be phrased better as:
`in Union, expected an instance of Type, got an instance of Nothing`
?

**Comment by StefanKarpinski** [comment]
I think the issue is that the error messages, while accurate, could be clearer.
