### ISSUE TITLE
Navigation issue in docs going from 1.4 to 1.0 and back

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35242]
If you go to docs.julialang.org and then pick the 1.0 documentation, the 1.0 docs load up. However the version picker still shows 1.4, even though the 1.0 manual is shown. From this screen you can't go to the 1.4 docs.

You have to go to some other version then which will then let you pick 1.4 again.

**Comment by fredrikekre** [comment]
Fixed.
