### ISSUE TITLE
FYI: Docs link not working

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#35249]
Link in the corner at docs.julialang.org is not working. I assumed should be reported at julialang.org website Github. Letting know as here seems to be the right place, FYI also other issues:

https://github.com/JuliaLang/www.julialang.org/issues/684

**Comment by fredrikekre** [comment]
Can you specify what 

> link in the corner

means?

**Comment by ViralBShah** [comment]
I meant this:
![77439518-6eae2180-6de7-11ea-8d2c-7075933153b6](https://user-images.githubusercontent.com/744411/77440096-43fba300-6dbe-11ea-8961-47b05e44cb9d.png)

**Comment by StefanKarpinski** [comment]
Not the right repo for this issue.

**Comment by ViralBShah** [comment]
Where should docs issues for the Julia documentation be filed?

**Comment by StefanKarpinski** [comment]
Looks like a website issue to me? Perhaps I’m misunderstanding the issue as files is a bit vague. Either that or a documenter issue?

**Comment by ViralBShah** [comment]
It isn't a julialang.org website issue, and the docs.julialang.org has issues disabled. So I assumed that issues relating to display of julia documentation would be filed here. @fredrikekre may be the right person to suggest.

Of course I am not sure what the actual issue @PallHaraldsson has filed is. Since all the links work for me.

**Comment by PallHaraldsson** [comment]
@fredrikekre

>means?

The "Edit" in the right upper corner, but not on all pages (was explained in the other issue), e.g. at:
https://docs.julialang.org/en/v1/NEWS/

It's still not ok.

Since issue been closed at two places, and either is correct, I doubt I'll file it again.

**Comment by fredrikekre** [comment]
Ok, duplicate of https://github.com/JuliaLang/julia/issues/34511 then.
