### ISSUE TITLE
very long compile time for large testset

### ISSUE THREAD

**Issue by helgee** [JuliaLang/julia#35258]
Adding e.g. an empty `for` loop (or any loop expression) to any `@testset` within the test suite of ERFA.jl ~freezes Julia~ leads to a 40x slowdown on my machine (see versioninfo below). On Travis ~the tests still pass but~ there is a 30x slowdown. I have not been able to condense this further, have a look here for an "MWE": https://github.com/JuliaAstro/ERFA.jl/pull/45/commits/5799bed7e4d0838c63e5d2e38353c9159206fea4#diff-fce720c43af3c52c862fd7451c7374b8R6

EDIT: No freeze, I was just too impatient. Runtime goes from ~10 to ~450 seconds.

Bisection points to this commit: https://github.com/JuliaLang/julia/commit/b9546c8b487364cd998b3ad87d873dc3ef35ac43

## Version info
```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) m7-6Y75 CPU @ 1.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_DEVDIR = /Users/helge/projects/julia
```

**Comment by JeffBezanson** [comment]
We use the presence of a loop as a heuristic to decide to type infer and compile the top-level expression, so that explains the difference.

**Comment by JeffBezanson** [comment]
The time is in LLVM. This is a single very large top-level expression, 3000 lines (82000 IR statements). With -O2 various optimization passes are taking a lot of time. With -O1 it seems to be LateLowerGCFrame:
```
#0  0x00007f0f15e67fb7 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f0f1a4af3e7 in std::_Rb_tree_iterator<std::pair<llvm::Instruction* const, int> >::operator++ (this=<synthetic pointer>) at /usr/include/c++/7/bits/stl_tree.h:287
#2  LateLowerGCFrame::ComputeLiveSets (this=this@entry=0x5586099262a0, S=...)
    at /home/jeff/src/julia/src/llvm-late-gc-lowering.cpp:1810
#3  0x00007f0f1a4b02a2 in LateLowerGCFrame::ComputeLiveness (this=this@entry=0x5586099262a0, 
    S=...) at /home/jeff/src/julia/src/llvm-late-gc-lowering.cpp:1693
#4  0x00007f0f1a4b04f1 in LateLowerGCFrame::runOnFunction (this=0x5586099262a0, F=...)
    at /home/jeff/src/julia/src/llvm-late-gc-lowering.cpp:2416
#5  0x00007f0f16a645f8 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /home/jeff/src/julia/usr/bin/../lib/libLLVM-9jl.so
```

Of course, we shouldn't be compiling this expression at all. Maybe there should be some size limit?

@helgee A good workaround is to remove the outer testset. I don't believe it's necessary for all of a package's test to be wrapped in one testset.

**Comment by helgee** [comment]
> @helgee A good workaround is to remove the outer testset. I don't believe it's necessary for all of a package's test to be wrapped in one testset.

That works, thanks 👍 While not necessary, it is aesthetically pleasing to have one big green number when the test finally pass.

**Comment by helgee** [comment]
What also worked was splitting the monstrous test set into several files and including them within the outer test set.

**Comment by oscardssmith** [comment]
has this been fixed? I know we've improved latelowergc recently...
