### ISSUE TITLE
Use of sendfile leaves files broken on Ceph FS

### ISSUE THREAD

**Issue by Micket** [JuliaLang/julia#35251]
I'm a sysadmin on a cluster using [Ceph FS](https://docs.ceph.com/docs/master/cephfs/) as the primary filesystem, and I see some weird output when users try to install julia packages. It is 100% reproducible, and tested on Julia 1.1 and 1.3.1.
I boiled down the problem to `Base.Filesystem.cp` using `sendfile`.

I don't know if Ceph FS has plans to support `sendfile`, but as it stands, it (quietly) leaves the files completely broken (they end up not being actually written to the ceph server, leaving written unsynchronized in the client cache).

I understand that the blame is probably on CephFS here since it quitely fails, but is sendfile worth it? Considering it's not posix compliant, perhaps not the best option for `Base.Filesystem.cp`.
(I'm also contacting the Ceph for the sendfile problems)

**Comment by Keno** [comment]
We should look into whether there's some error code that we're ignoring somewhere. If so, we could probably put in a fallback.

**Comment by Micket** [comment]
Well, there might be, though it wouldn't make a difference for this issue, since Ceph quietly fails if sendfile is used. I wouldn't be surprised if there are other parallel filesystem like beegfs, on which this doesn't work, considering most just advertise themselves as posix compliant.

For reference; https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/LCU4RDUNI6WDGJGPZGRSMOLYBJ6N2FNT/

**Comment by StefanKarpinski** [comment]
It seems unreasonable that we can't use `sendfile` because some file systems may not implement it correctly. The performance advantage of `sendfile` is really huge. At the very least, if the file system explicitly failed when `sendfile` was used, then we could have a fallback. The fact that this is broken on Ceph FS and silently broken really pushes this towards it's Ceph's problem to fix.

**Comment by ViralBShah** [comment]
I'd never heard of Ceph FS. I edited the issue description up top to add a link to it.

**Comment by Keno** [comment]
The linked thread seems to suggest that this is a known bug in old kernel versions. Given that, I doubt there's something we can do here, but feel free to open a new issue if it turns out we're doing something wrong.

**Comment by Micket** [comment]
Well, it's a present kernel bug in latest CentOS7 (, maybe fixed in upcoming 7.9 if Jeff@RH is correct (which I will spend the evening investigating). Anyway, I'm not arguing that one should reopen this ticket, but I just want to make it searchable that this can be an issue on less "common" filesystems, like any of the parallel filesystems used on clusters, since sendfile is documented as:

> CONFORMING TO
> Not specified in POSIX.1-2001, nor in other standards.
> Other UNIX systems implement sendfile() with different semantics and
> prototypes.  It should not be used in portable programs.

I also found that python 3.8 shutils look like it will also start using sendfile though, so that should help finding potential kernel/filesystem bugs quicker in the future.
