### ISSUE TITLE
setindex for CartesianIndex

### ISSUE THREAD

**Issue by snirgaz** [JuliaLang/julia#35255]
This is a request for adding `setindex` functionality for the CartesianIndex type, similar to a plain tuple.
Currently, it is required to go through tuples explicitly

`julia> I = CartesianIndex(1, 2, 3, 4, 5)
CartesianIndex(1, 2, 3, 4, 5)

julia> I = CartesianIndex(Base.setindex(Tuple(I), 50, 3))
CartesianIndex(1, 2, 50, 4, 5)`

Thanks!

**Comment by mbauman** [comment]
Seems reasonable — and simple enough.  Just needs the obvious implementation (doing the tuple jump) and tests.

**Comment by francescoalemanno** [comment]
> Seems reasonable — and simple enough. Just needs the obvious implementation (doing the tuple conversion, setindex, and back as you have it) and tests.

@mbauman i just sent a super tiny PR for this
