### ISSUE TITLE
reverse searchsorted is inconsistent on 1.3

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#35272]
```julia
julia> searchsortedfirst(10:-1:1, 9.5; rev=true)
1

julia> searchsortedfirst(collect(10:-1:1), 9.5; rev=true)
2

julia> searchsortedlast(10:-1:1, 9.5; rev=true)
2

julia> searchsortedlast(collect(10:-1:1), 9.5; rev=true)
1
```

The range behaviour seems like the correct version, but needless to say it's extremely confusing getting different answers for these.

> searchsortedfirst(a, x; by=<transform>, lt=<comparison>, rev=false)

 > Return the index of the first value in a greater than or equal to x,
  according to the specified order. Return length(a) + 1 if x is greater than
  all values in a. a is assumed to be sorted.

It gets worse if you use all floats, now both the range and the array are wrong:

```julia
julia> searchsortedfirst(10.0:-1.0:1.0, 9.5; rev=true)
2

julia> searchsortedfirst(collect(10.0:-1.0:1.0), 9.5; rev=true)
2

julia> searchsortedlast(10.0:-1.0:1.0, 9.5; rev=true)
1

julia> searchsortedlast(collect(10.0:-1.0:1.0), 9.5; rev=true)
1
```

```julia
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 3
```

**Comment by rfourquet** [comment]
> The range behaviour seems like the correct version

Actually the array version looks correct to me.

**Comment by rafaqz** [comment]
10 is the first value greater than or equal to 9.5. Which has an index of 1. 9 has an index of 2, but its not greater than 9.5.

So 1 is the correct answer for `searchsortedfirst`

**Comment by rfourquet** [comment]
> 10 is the first value greater than or equal to 9.5

Yes with the usual interpretation of "greater than", but with `rev=true`, "greater than" means `<=`, so, in  `10:-1:1`, `9` is the first value `<= 9.5`.

**Comment by rafaqz** [comment]
That's extremely confusing! The doc should be rewritten, it's probably the reason this is broken.

**Comment by rfourquet** [comment]
Sure the docs should be inproved, the meaning of `rev`, `by` and `lt` is underspecified in the docstring. In that of `searchsorted`, it's a bit improved (at least they are mentioned), "... according to the order specified by the by, lt and rev keywords", but you have to know from somewhere else what they mean exactly, it's explained in the docstring of `sort!`, so there should be at least a link to that function to point where to find the information.
