### ISSUE TITLE
Routine non-informative Pkg errors on nightly (non-Linux)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#35297]
It may not be 100% reproducible, but typically nightly is failing on PRs with essentially no explanation:

https://ci.appveyor.com/project/timholy/revise-jl/builds/31786396
https://travis-ci.org/github/timholy/Revise.jl/builds/668050922?utm_source=github_status&utm_medium=notification
https://ci.appveyor.com/project/JuliaArrays/offsetarrays-jl/builds/31797030

AFAICT it only affects non-Linux platforms.

**Comment by fredrikekre** [comment]
Probably https://github.com/JuliaLang/julia/pull/34347 which also broke PkgEval?

**Comment by KristofferC** [comment]
PR was reverted
