### ISSUE TITLE
Old link to cpython hg repo

### ISSUE THREAD

**Issue by Hieronimo** [JuliaLang/julia#35299]
https://github.com/JuliaLang/julia/blob/f0772c5104435a1a2daec6b4dea96803bb51fe7f/src/support/strtod.c#L46

It's now:
https://github.com/python/cpython/blob/master/Python/pystrtod.c

The file is updated, should the link be updated?

**Comment by StefanKarpinski** [comment]
Sure, would be good to have an up-to-date link. Want to make a PR?

**Comment by Hieronimo** [comment]
Yes, I made a PR.
