### ISSUE TITLE
String representation of expressions with quotes in non-standard string literals

### ISSUE THREAD

**Issue by pfarndt** [JuliaLang/julia#35305]
The string representation of an expression that contains quotes `"` in triple-quoted non-standard string literals (or escaped quotes in quoted non-standard string literals) is not faithfully any more. The resulting text does not represent valid Julia code and cannot be `include`d again. in Julia v1.4

```
julia> print(:(r = r"""45 " """))
r = r"45 " "
```

```
julia> print(:(r = r"45 \" "))
r = r"45 " "
```

This does not happen for "normal" strings
```
julia> print(:(r = "45 \" "))
r = "45 \" "
```

and also used to work in Julia v1.3.1. See also https://discourse.julialang.org/t/string-representation-of-expression/36729/3?u=pfarndt

**Comment by StefanKarpinski** [comment]
@JeffBezanson, I don't recall many changes to string literals aside from the recent one you did for multiline string literals. Any possibility that might have affected this?

**Comment by JeffBezanson** [comment]
It's a printing issue; #32423.
