### ISSUE TITLE
Unable to find local packages in directory with Project.toml/Manifest.toml

### ISSUE THREAD

**Issue by sjpet** [JuliaLang/julia#35328]
Since upgrading to v1.4, Julia is unable to find local packages in a directory that has Project.toml and/or Manifest.toml:

    > mkdir Foo && cd Foo
    > julia
                   _
       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
     _/ |\__'_|_|_|\__'_|  |  
    |__/                   |

    (@v1.4) pkg> activate .
     Activating new environment at `~/sandbox/julia/Foo/Project.toml`
    
    (Foo) pkg> add LinearAlgebra
       Updating registry at `~/.julia/registries/General`
       Updating git-repo `https://github.com/JuliaRegistries/General.git`
    ┌ Warning: Some registries failed to update:
    │     — /home/me/.julia/registries/General — failed to fetch from repo
    └ @ Pkg.Types /build/julia/src/julia-1.4.0/usr/share/julia/stdlib/v1.4/Pkg/src/Types.jl:1122
      Resolving package versions...
       Updating `~/sandbox/julia/Foo/Project.toml`
      [37e2e46d] + LinearAlgebra 
       Updating `~/sandbox/julia/Foo/Manifest.toml`
      [8f399da3] + Libdl 
      [37e2e46d] + LinearAlgebra 
    
    julia> push!(LOAD_PATH, pwd())
    4-element Array{String,1}:
     "@"
     "@v#.#"
     "@stdlib"
     "/home/me/sandbox/julia/Foo"
    
    (Foo) pkg> generate Bar
     Generating  project Bar:
        Bar/Project.toml
        Bar/src/Bar.jl
    
    julia> using Bar
    ERROR: ArgumentError: Package Bar not found in current path:
    - Run `import Pkg; Pkg.add("Bar")` to install the Bar package.

**Comment by KristofferC** [comment]
> Since upgrading to v1.4

This seems to be the same on 1.3. Upgrading from what version?

**Comment by StefanKarpinski** [comment]
This is working as intended: a directory is either a project or a package directory, not both. If it has a project file, then it is a project and you can only load dependencies that are declared in the project file. If it doesn't have a project file, then it's a package directory and entry points like `Bar` will work. Note that `push!(LOAD_PATH, pwd())` has no effect on the effective load path since `@` already expands to the same directory. There was a bug in code loading where this previously worked, but that was unintentional and undocumented. If you want to be able to load `Bar` from `Foo` you can do `] add ./Bar`.

**Comment by sjpet** [comment]
I see. So if I have a project that can be divided into several subprojects, each of them requiring some of a number of independent packages which have no relevance outside of the project, what would be the idiomatic way to organize this?

**Comment by StefanKarpinski** [comment]
I'm not quite following what you want to do, but if they all live in the same repo, then `] dev ./Bar` seems like the right way to go. Then whatever code is at that location is what is used. Since that code is included in the top-level package, it's always up-to-date.
