### ISSUE TITLE
On Linux, tempname() ignores the ‘parent’ argument if the TMPDIR environment variable is set

### ISSUE THREAD

**Issue by ivan-timokhin** [JuliaLang/julia#35343]
Because that is [the behaviour of the underlying `tempnam` function](https://linux.die.net/man/3/tempnam). For example, this fails
```julia
withenv("TMPDIR" => tempdir()) do
    mktempdir() do d
        t = tempname(d)
        @test dirname(t) == d
    end
end
```
and, in fact, [an existing test in `file.jl`](https://github.com/JuliaLang/julia/blob/261ad38e17c08ca8399c47cdea05ed9c8eb95eef/test/file.jl#L65-L73) fails if the testsuite is run with `TMPDIR` set (which is how I discovered the issue).

I have tried fixing the issue myself (#35342), but the result ended up thread-unsafe, and I don't have any better ideas.

**Comment by yuyichao** [comment]
Why does this function exist anyway... The document for the C function explicitly says don' use it and the glibc implementation isn't fundamentally safer than the windows one anyway....

**Comment by ivan-timokhin** [comment]
> Why does this function exist anyway...
See also #22949 and #9053.

**Comment by StefanKarpinski** [comment]
Agree, we should probably just have our own implementation of this that doesn't use `tempnam`.

**Comment by laborg** [comment]
This has been fixed on master by https://github.com/JuliaLang/julia/pull/38879
```
#Julia Version 1.8.0-DEV.1440
#Commit e3b681c687 (2022-02-02 01:39 UTC)
julia> withenv("TMPDIR" => tempdir()) do
           mktempdir() do d
               t = tempname(d)
               @test dirname(t) == d
           end
       end
Test Passed
```
