### ISSUE TITLE
Customize @edit to work with VS Code Insiders

### ISSUE THREAD

**Issue by mshseek** [JuliaLang/julia#35357]
I would like to propose changing "code"  to "code-insiders"  in this part of [editless.jl](https://github.com/JuliaLang/julia/blob/b8e9a9ecc62ab49003bd4f1834771bdeb8cb1aa2/stdlib/InteractiveUtils/src/editless.jl#L130) so that the @edit macro would work for people using VS Code Insiders version too.

Is this worth making a PR?

**Comment by ViralBShah** [comment]
I assume you are suggesting adding and not replacing. In that case it should be ok.

**Comment by mshseek** [comment]
I was actually suggesting replacing. 

I expected the pattern `code-insiders` to match `code` too based on the documentation for [define_editor](https://docs.julialang.org/en/v1/stdlib/InteractiveUtils/#InteractiveUtils.define_editor) but after rereading it again I think I got it wrong.

So, instead of adding another call to `define_editor()` to support VS Code Insiders, how about we just replace `"code"` with `["code", "code-insiders"]`?

**Comment by ViralBShah** [comment]
Sure.

**Comment by ViralBShah** [comment]
> So, instead of adding another call to `define_editor()` to support VS Code Insiders, how about we just replace `"code"` with `["code", "code-insiders"]`?

Yes, this sounds good.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/35382
