### ISSUE TITLE
AppVeyor Windows Hands-free installation on Julia 1.4 is broken

### ISSUE THREAD

**Issue by ceandrade** [JuliaLang/julia#35355]
Dear all,

Until Julia 1.3, we could install Julia on Windows via script using:

```terminal
C:\projects\julia-1.3.0-win64.exe /S /D=C:\projects\julia
```

However, this behavior was dropped on version 1.4, and it has broken builds on AppVeyor. It would be nice to bring back that feature, or instruct AppVeyour how to install Julia >= 1.4 without human intervention.

Thanks,

Carlos

**Comment by musm** [comment]
Are you not using https://github.com/JuliaCI/Appveyor.jl ?

We already have a patch for 1.4 that is compatible with the changes: https://github.com/JuliaCI/Appveyor.jl/commit/88bbc7ec0d8eb65f74d44fd35cd12dbc4ac74ed6

**Comment by ceandrade** [comment]
No, I wasn't. Last time I used, appveyor.jl was broken, and I gave up. Following your advise, I gave another try and now it is working for Julia 1.4. Many thanks @musm!

**Comment by musm** [comment]
great
