### ISSUE TITLE
Speed of `copy(::PermutedDimsArray)` vs `permutedims`

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#35361]
While `copy(x::Transpose)` calls a special `transpose!(similar(x, ...), x)`, I think that `copy(x::PermutedDimsArray)` doesn't call a special method. If I try to re-use what `permutedims!` does, then strangely I get something much faster than the original:
```julia
julia> xx = rand(128,128,128);
julia> yy = permutedims(xx, (2,3,1));

julia> @btime copy(PermutedDimsArray($xx, (2,3,1))); 
  17.470 ms (10 allocations: 16.00 MiB) # not sure what version this was, original post.
  22.108 ms (10 allocations: 16.00 MiB) # on Julia 1.3.1
  16.035 ms (10 allocations: 16.00 MiB) # on Julia 1.4.2
  22.730 ms (6 allocations: 16.00 MiB) # on Julia 1.5.2
  26.694 ms (6 allocations: 16.00 MiB) # on Julia 1.6 -- worse!

julia> @btime permutedims($xx, (2,3,1));
  16.195 ms (6 allocations: 16.00 MiB)
  16.040 ms (2 allocations: 16.00 MiB) # on Julia 1.6

julia> function Base.copyto!(dest::AbstractArray{T,N}, src::PermutedDimsArray{T,N,perm,iperm}) where {T,N,perm,iperm}
           checkbounds(dest, axes(src)...)
           P = PermutedDimsArray(dest, iperm)
           Base.PermutedDimsArrays._copy!(P, parent(src))
           dest
       end

julia> @btime copy(PermutedDimsArray($xx, (2,3,1))); # with this new copyto!(similar(xx), xx)
  4.462 ms (22 allocations: 16.00 MiB)
  4.413 ms (13 allocations: 16.00 MiB) # on Julia 1.6

julia> yy == copy(PermutedDimsArray(xx, (2,3,1)))
true

julia> using OMEinsum # for a fast method from TensorOperations, to compare

julia> @btime OMEinsum.tensorpermute($xx, (3,2,1)); # with a different perm, by mistake!
  2.074 ms (48 allocations: 16.00 MiB)

julia> @btime OMEinsum.tensorpermute($xx, (2,3,1)); # added later
  1.972 ms (64 allocations: 16.00 MiB)  # on Julia 1.6
```
Presumably we should add this. But why is `permutedims!` so much slower, when it does the same thing?

https://github.com/JuliaLang/julia/blob/c44644442949238da70670b547312ca1ae9a9c7d/base/permuteddimsarray.jl#L191-L195

**Comment by timholy** [comment]
It's not calling that method, it's calling https://github.com/JuliaLang/julia/blob/c973ad84545e67ce528180c2d072b5e767ed73a3/base/multidimensional.jl#L1434-L1461

Maybe we should just delete that method? Would be nice to have some `permutedims!` benchmarks in BaseBenchmarks and do a nanosoldier run before doing so.

**Comment by mcabbott** [comment]
Ok, thanks! Will look at adding some to BaseBenchmarks if I get a minute.

**Comment by mcabbott** [comment]
I had a quick go at some more timings, on the latest Julia 1.5 (and on a desktop). And the short version is that it's complicated! And size `128^3` might have been a lucky/unlucky choice. 
* "eager" means `permutedims!($y, (2,3,1))`
* "lazy" means `copyto!($y, PermutedDimsArray($x,(2,3,1)))`
* "new" the method I proposed above, calling `_copy!`
```
        (:eager)      (:lazy)       (:new)
   (5)   1.03787e-7    4.86e-7       1.0007e-6
  (10)   6.08699e-7    1.1763e-6     1.5282e-6
  (30)   1.6988e-5     2.0526e-5     1.9719e-5
  (50)   0.000126503   0.000117137   9.7401e-5
 (100)   0.00137034    0.00151149    0.00121594
 (128)   0.00982414    0.010541      0.00362345
 (150)   0.00654121    0.00790958    0.00625269
```
And at small sizes, `permutedims!` is faster. In four dimensions, `perm = (3,4,1,2)`:
```
        (:eager)      (:lazy)       (:new)
   (5)   5.08021e-7    1.3241e-6     1.5686e-6
  (10)   6.252e-6      1.1067e-5     8.98567e-6
  (30)   0.000577655   0.000901198   0.00103728
  (50)   0.0253984     0.0267281     0.0215751
 (100)   0.651683      0.638186      0.431114
 (150)   3.90064       4.04947       2.5109
```

**Comment by mcabbott** [comment]
Some better attempts to time the same 3 options. The tl;dr is that  "lazy" meaning `copyto!($y, PermutedDimsArray($x,(2,3,1)))` is uniformly worse. (All on a 2-core laptop, on Julia nightly, 1.6-minus.)

![permute321](https://user-images.githubusercontent.com/32575566/97092299-5505de80-1643-11eb-84e2-48dc195c7888.png)

![permute213](https://user-images.githubusercontent.com/32575566/97092304-6222cd80-1643-11eb-8980-742f04f4ade0.png)

![permute132](https://user-images.githubusercontent.com/32575566/97092310-66e78180-1643-11eb-8d11-1c60342d531f.png)

<details>
<pre>
using BenchmarkTools, Test, Plots

function sixtime(n, perm) 
    A = randn(Float64, map(_->n, perm))
    B, C, D = similar(A), similar(A), similar(A)

    t1 = @belapsed permutedims!($B, $A, $perm)
    t2 = @belapsed copyto!($C, PermutedDimsArray($A, $perm))
    t3 = @belapsed Base.PermutedDimsArrays._copy!(PermutedDimsArray($D, invperm($perm)), $A)
    @test B == C == D

    sizeA2 = Tuple(map(_->n, perm) .+ (1:length(perm)))
    A2 = randn(Float64, sizeA2)
    B2 = zeros(sizeA2[collect(perm)])
    C2, D2 = similar(B2), similar(B2)

    t4 = @belapsed permutedims!($B2, $A2, $perm)
    t5 = @belapsed copyto!($C2, PermutedDimsArray($A2, $perm))
    t6 = @belapsed Base.PermutedDimsArrays._copy!(PermutedDimsArray($D2, invperm($perm)), $A2)
    @test B2 == C2 == D2

    println("done $n")
    10^-9 .* (length(A)/t1, length(A)/t2, length(D)/t3, 
        length(D)/t4, length(D)/t5, length(D)/t6) # numbers per nanosecond
end

sizes3 = sort(vcat(vec((2 .^ (3:8))' .+ [-1,0,1] ), [25, 50, 100, 150, 200, 300]))
ticks3 = 2 .^ (3:8) 

@time times321 = [sixtime(n, (3,2,1)) for n in sizes3] # 10 minutes
@time times213 = [sixtime(n, (2,1,3)) for n in sizes3]
@time times132 = [sixtime(n, (1,3,2)) for n in sizes3]

plot(sizes3, reinterpret(reshape, Float64, times321)', title="permute (3,2,1)",
    lab=["eager" "lazy" "new" "eager, staggered" "lazy, staggered" "new, staggered"],
    s=[:solid :dash :dashdot :solid :dash :dashdot],
    xaxis=(:log10, "n", (ticks3, ticks3)), yaxis=(:log10, "numbers/ns", ([1/8,0.25,0.5,1,2], ["1/8","1/4","1/2",1,2])),
    legend=:bottomleft)

savefig("permute321")

plot(sizes3, reinterpret(reshape, Float64, times213)', title="permute (2,1,3)",
    lab=["eager" "lazy" "new" "eager, staggered" "lazy, staggered" "new, staggered"],
    s=[:solid :dash :dashdot :solid :dash :dashdot],
    xaxis=(:log10, "n", (ticks3, ticks3)), yaxis=(:log10, "numbers/ns", ([1/8,0.25,0.5,1,2], ["1/8","1/4","1/2",1,2])),
    legend=:bottomleft)

savefig("permute213")

plot(sizes3, reinterpret(reshape, Float64, times132)', title="permute (1,3,2)",
    lab=["eager" "lazy" "new" "eager, staggered" "lazy, staggered" "new, staggered"],
    s=[:solid :dash :dashdot :solid :dash :dashdot],
    xaxis=(:log10, "n", (ticks3, ticks3)), yaxis=(:log10, "numbers/ns", ([1/8,0.25,0.5,1,2], ["1/8","1/4","1/2",1,2])),
    legend=:bottomleft)

savefig("permute132")

</pre>
</details>

**Comment by mcabbott** [comment]
Similar pattern in 4D arrays:

![permute4321](https://user-images.githubusercontent.com/32575566/97104403-e9a82500-16b3-11eb-8a36-2e259d39287b.png)

![permute2143](https://user-images.githubusercontent.com/32575566/97104406-ee6cd900-16b3-11eb-8920-496ddd9f440d.png)

![permute1324](https://user-images.githubusercontent.com/32575566/97104407-f167c980-16b3-11eb-9785-bdcc03e8b826.png)

**Comment by ViralBShah** [comment]
Julia 1.8 matches Julia 1.5 performance, and is 25% faster than Julia 1.6.
