### ISSUE TITLE
Pkg behind Corporate Proxy

### ISSUE THREAD

**Issue by ShoofLLC** [JuliaLang/julia#35373]
This issue has probably been mentioned multiple times but here it is again:
(@v1.4) pkg> add Flux
    Cloning default registries into `~/.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: git repository not found at `https://github.com/JuliaRegistries/General.git`

---
I tried cloning the General Registry to ~/.julia/registries  at which point I get the following:
---
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: Some registries failed to update:
│     — /home/<REDACTED>/.julia/registries/General — failed to fetch from repo
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Types.jl:1122
  Resolving package versions...
    Cloning [9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a] DataAPI from https://github.com/JuliaData/DataAPI.jl.git
ERROR: git repository not found at `https://github.com/JuliaData/DataAPI.jl.git`

---------------
My ENV includes "HTTP_PROXY" and "HTTPS_PROXY" both in small and capital letters. My git config has proxy entries and git works with no issues. 

Curl from bash can access websites with no issues. I also tried switching the protocol from "https" to "http", that didn't help either. I checked and double checked the proxy configuration and I know that it works because it's the exact same configuration that I use for bash (inside my bashrc file) and for git. Python pip also works fine.
--------------

**Comment by fredrikekre** [comment]
Try https://github.com/JuliaLang/julia/issues/33111#issuecomment-541224149 ? xref https://github.com/libgit2/libgit2/issues/5255

**Comment by ShoofLLC** [comment]
> Try [#33111 (comment)](https://github.com/JuliaLang/julia/issues/33111#issuecomment-541224149) ? xref [libgit2/libgit2#5255](https://github.com/libgit2/libgit2/issues/5255)

So that works... I'm closing the issue.
