### ISSUE TITLE
Code blocks within lists do not support language specification (Markdown)

### ISSUE THREAD

**Issue by sloede** [JuliaLang/julia#35375]
If you use a fenced code block inside a list in a Markdown string, the "language" is mistakenly parsed as part of the fenced region:
```julia
julia> using Markdown

julia> md = Markdown.parse("""

       1.  item one
       2.  item two

           ```bash
           git clone ...
           ```
       """)
    1.   item one

    2.   item two
      
        bash  git clone ...

julia> 
```
The expected output would be just `git clone ...` with Bash syntax highlighting enabled.

This is my output of `versioninfo()`:
```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by fredrikekre** [comment]
You just need to align it correctly:
````
julia> Markdown.parse("""
       1. item one
       2. item two
          
          ```bash
          git clone
          ```
       """)
    1.   item one

    2.   item two
      
        git clone

julia> Markdown.parse("""
       1. item one
       2. item two
          ```bash
          git clone
          ```
       """)
    1.   item one

    2.   item two
      
        git clone
````

**Comment by sloede** [comment]
Ah, sorry for the unnecessary work! I was not aware that the Markdown parser is this sensitive to whitespace.
