### ISSUE TITLE
`asyncmap` encounters "Channel is closed"

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#35379]
I ran into this issue on Julia 1.4.0 when using `asyncmap` to read a bunch of files concurrently. We've been running this code in our nightly CI runs and we've never seen this failure on Julia 1.3. 
```
  InvalidStateException("Channel is closed.", :closed)
  Stacktrace:
   [1] maptwice(::Function, ::Channel{Any}, ::Array{Any,1}, ::Array{String,1}) at ./asyncmap.jl:181
   [2] wrap_n_exec_twice at ./asyncmap.jl:154 [inlined]
   [3] async_usemap(::var"#5#10", ::Array{String,1}; ntasks::Int64, batch_size::Nothing) at ./asyncmap.jl:103
   [4] #asyncmap#710 at ./asyncmap.jl:81 [inlined]
   [5] asyncmap at ./asyncmap.jl:81 [inlined]
   ...
```
I've only seen this error once and so far have not been able to reproduce.

Inspecting what has changed between Julia 1.3 to 1.4 makes me thing that possibly #33863 is responsible but that is just speculation on my part.

**Comment by nicoleepp** [comment]
We have continued to see this happen intermittently over the past 7 months

**Comment by nicoleepp** [comment]
To clarify it's happened on Julia  1.3, 1.4, and 1.5

**Comment by StefanKarpinski** [comment]
Any thoughts, @JeffBezanson, given that the change indicated as possible cause was yours?

**Comment by omus** [comment]
Looking over the internal logs with these failures I can say it occurs more often on 32-bit but does still occur on 64-bit.

**Comment by vtjnash** [comment]
does this still happen?

**Comment by vtjnash** [comment]
Not sure what we can do here without more info
