### ISSUE TITLE
Julia is twice as fast to loop if warmed up with math

### ISSUE THREAD

**Issue by peheje** [JuliaLang/julia#35408]
Using the package https://github.com/JuliaMath/Combinatorics.jl
and the words from https://github.com/dwyl/english-words/blob/master/words_alpha.txt

```
using Combinatorics
x = BigInt(factorial(big(370103)) / factorial(big(370103 - 4)))
function main()
    words = readlines("words_alpha.txt")
    words = words[1:12000]
    skip = 10000000
    i = 0
    for comb in combinations(words, 2)
        if i % skip == 0
            println(comb, i)
        end
        i += 1
    end
end
main()
time = @elapsed main()
print(time)
```

Takes about 4.78 seconds on my machine to run, similar to a Nim library.

Remove the `x = BigInt(...) `calculation at the top:

```
using Combinatorics
#x = BigInt(factorial(big(370103)) / factorial(big(370103 - 4)))
function main()
    words = readlines("words_alpha.txt")
    words = words[1:12000]
    skip = 10000000
    i = 0
    for comb in combinations(words, 2)
        if i % skip == 0
            println(comb, i)
        end
        i += 1
    end
end
main()
time = @elapsed main()
print(time)
```
Now takes about 9.34, almost **twice as long.**

I thought it had something to do with --math-mode=fast being turned on by that line, but no running with the flag produces same difference.

What is up and down here?

**Comment by JeffBezanson** [comment]
I have so far not been able to reproduce this. What is the output of `versioninfo()`?

**Comment by yuyichao** [comment]
And at least for Linux, distribution version and glibc version. Last time I saw this it was due to the glibc bug (fixed like two years ago) that messes up the avx register states.

And if you warm up with math after the slow one does it get any faster or slower?

**Comment by peheje** [comment]
Sorry for the lack of more information.
The initial results were from my Windows machine. I tried this on my Macbook, here the difference was much smaller 5.8 vs 6.72, still in favor of factorial warmup.

Let me try my Windows machine again and answer your questions.

**Comment by peheje** [comment]
Back on Windows

JeffBezanson:
`versionInfo `output is 
```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
```

yuyichao:
It pretty much stays the same
```
using Combinatorics
function main()
    words = readlines("words_alpha.txt")
    words = words[1:12000]
    skip = 10000000
    i = 0
    for comb in combinations(words, 2)
        if i % skip == 0
            println(comb, i)
        end
        i += 1
    end
end
time = @elapsed main()
print(time)
x = BigInt(factorial(big(370103)) / factorial(big(370103 - 4)))
time = @elapsed main()
print(time)
```
prints 9.095345155 then 8.989246453

**Comment by mistguy** [comment]
Not able to produce with
```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by peheje** [comment]
Thanks for investigating. Probably a blib on my computer configuration.
