### ISSUE TITLE
Feature request: provide an updateindex! method for SparseMatrixCSC

### ISSUE THREAD

**Issue by j-fu** [JuliaLang/julia#35428]
For A being a `SparseMatrixCSC`, the statement `A[1,2]+=3`  is lowered to
````
%1 = Base.getindex(A, 1, 2)
%2 = %1 + 3
Base.setindex!(A, %2, 1, 2)
````
triggering two index searches, one for `getindex!` and another one for `setindex!`.
By providing a method `updateindex!(A,+,v,i,j)` one of the searches could be avoided.
A possible implementation can be found in [here](https://github.com/j-fu/ExtendableSparse.jl/blob/master/src/sparsematrixcsc.jl).

**Comment by KristofferC** [comment]
Kinda dup of https://github.com/JuliaLang/julia/issues/15630, also see https://github.com/KristofferC/UpdateIndex.jl.

**Comment by j-fu** [comment]
Well, should have looked this up before... So I close this one and chime in into #15630 .
