### ISSUE TITLE
crash with operator overloading

### ISSUE THREAD

**Issue by photor** [JuliaLang/julia#35436]
`julia> import Base.+

julia> +(a::Number...)=Expr(:call, :+, a...)
Error showing value of type typeof(+):

SYSTEM (REPL): showing an error caused an error

SYSTEM (REPL): caught exception of type MethodError while trying to handle a nested exception; giving up

fatal: error thrown and no exception handler available.
MethodError(f=typeof(Base.convert)(), args=(UInt64, Expr(:call, :+, 0xccfd4bc0934b3421, 0x67ea5e049a59a108, 0xfd4bc0934b342100)), world=0x00000000000068b5)
rec_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/stackwalk.c:94
record_backtrace at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:224
jl_throw at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:461
jl_method_error_bare at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1710
jl_method_error at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1728
jl_lookup_generic_ at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2280
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2301
hash_64_64 at ./hashing.jl:31
hash_uint at ./hashing.jl:63
hash at ./hashing.jl:23
unknown function (ip: 0x11c28f746)
hash at ./hashing.jl:18
hashindex at ./dict.jl:168
ht_keyindex at ./dict.jl:282
haskey at ./dict.jl:545
repl_color at ./client.jl:19
error_color at ./client.jl:22
display_error at ./client.jl:101
display_error at ./client.jl:104
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1631 [inlined]
jl_f__apply at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:627
jl_f__apply_latest at /Users/julia/buildbot/worker/package_macos64/build/src/builtins.c:665
#invokelatest#1 at ./essentials.jl:709 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
_start at ./client.jl:462
jfptr__start_2084.clone_1 at /Applications/Julia.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
true_main at /Applications/Julia.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia.app/Contents/Resources/julia/bin/julia (unknown line)`
`julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4`

**Comment by fredrikekre** [comment]
This is expected, everything will break if you break integer addition. Ref #27472 #26311 #24122 #24078 #23605 #22132 #21944 #20945 #29321 #29562 etc.

**Comment by photor** [comment]
> This is expected, everything will break if you break number addition. Ref #27472 #26311 #24122 #24078 #23605 #22132 #21944 #20945 #29321 #29562 etc.

I understand that everything will break if I break number addition, but the following code:
`+(a::Union{Number, Symbol}...)=Expr(:call, :+, a...)`
also crashes REPL, which is not intended to break number addition and should not overwrite the standard function +(a::Number...), so that only when not all of the arguments are numbers the above extended + function should be loaded, am I right?

**Comment by KristofferC** [comment]
I don't think there is a `+(a::Number...)`, there is a `+(a,b,c, xs...)` so for e.g. 1+2+3 your method would be called. In this case it is in `hash_64_64` function.

```
fatal: error thrown and no exception handler available.
MethodError(f=typeof(Base.convert)(), args=(UInt64, Expr(:call, :+, 0xccfd4bc0934b3421, 0x67ea5e049a59a108, 0xfd4bc0934b342100)), world=0x00000000000069fb)
jl_method_error_bare at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1718
jl_method_error at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1736
jl_lookup_generic_ at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2297
jl_apply_generic at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:2318
hash_64_64 at ./hashing.jl:31
hash_uint at ./hashing.jl:63
hash at ./hashing.jl:23
unknown function (ip: 0x128d6c376)
hash at ./hashing.jl:18
hashindex at ./dict.jl:168
```
