### ISSUE TITLE
I have problem in collect(::Iterators.Take) proccess when i want to take the cache in

### ISSUE THREAD

**Issue by nesteiner** [JuliaLang/julia#35434]
here i make a fib collection,which has unlimited length
```julia
struct __Fib
end
fib = __Fib()
function Base.iterate(fib::__Fib)
	BigInt(1),(BigInt(1),BigInt(0))
end

function Base.iterate(fib::__Fib,(a,b)::T) where T
	a+b,(a+b,a)
end

Base.length(fib::__Fib) = typemax(Int)
```

Then I can take any length of fib into collection
` collect(Iterators.take(fib,n))`
but i found when i use the code `collect(Iterators.take(fib,n))` again,it will caculate again,how do i do to take the cache to jump out the caculation part

**Comment by rfourquet** [comment]
Please ask questions at  https://discourse.julialang.org/ or in the Slack or Zulip forums.
