### ISSUE TITLE
Rational array inplace multiplication gives wrong result

### ISSUE THREAD

**Issue by kagalenko-m-b** [JuliaLang/julia#35445]
On AMD64,
```
julia> x=[1//1];x.*=1/5
1-element Array{Rational{Int64},1}:
 3602879701896397//18014398509481984
```
but on i386 works correctly. See [travis build](https://travis-ci.com/github/kagalenko-m-b/RationalDivision/) for this [repo](https://github.com/kagalenko-m-b/RationalDivision/) for behavior on different platforms.

**Comment by Micket** [comment]
Not quite wrong; it's a matter of precision of floating point numbers that get converted back to Rational's

```julia
julia> Rational(0.2)
3602879701896397//18014398509481984
```
since 0.2 can't be represented exactly in base 2.
```julia
julia> @sprintf("%.30f", 0.2)
"0.200000000000000011102230246252"
```

**Comment by kagalenko-m-b** [comment]
On i386,
```
julia> x=[1//1];x .*= 1/5
1-element Array{Rational{Int32},1}:
 1//5
```

**Comment by kagalenko-m-b** [comment]
On any architecture,
```
julia> x=[Int32(1)//Int32(1)];x.*=1/5
1-element Array{Rational{Int32},1}:
 1//5

julia> x=[Int64(1)//Int64(1)];x.*=1/5
1-element Array{Rational{Int64},1}:
 3602879701896397//18014398509481984
```

Seems premature to close this

**Comment by Micket** [comment]
No, it's not a bug. It's a precision issue of `Rational{Int64}` vs `Rational{Int32}`.
```julia
julia> Rational{Int32}(0.2)
1//5

julia> Rational{Int64}(0.2)
3602879701896397//18014398509481984
```

Not a bug, these are simply the closest representations of `0.200000000000000011102230246252... ` that you can get with respective types.

**Comment by kagalenko-m-b** [comment]
Thanks, I see your point
