### ISSUE TITLE
Unicode named groups for regular expressions

### ISSUE THREAD

**Issue by BenjaminGalliot** [JuliaLang/julia#35459]
Hello,

This issue is strongly related to my old (more than 1 year) message [here](https://discourse.julialang.org/t/how-to-use-unicode-characters-in-regex-named-groups/20178/2). 

It is to allow Unicode named groups for regular expressions, it seems it was just related to a limitation of PCRE, which was [updated](https://vcs.pcre.org/pcre2/code/trunk/src/pcre2test.c?r1=1041&r2=1066) to fix it last year.

I remember I tried near the end of last year the latest PCRE2 and it worked, and because I just tried again on the latest Julia 1.4 without success, I read again this topic and it is true they asked me to open an issue here! Done!

Sincerely.

**Comment by Micket** [comment]
Related #35322 ?

**Comment by BenjaminGalliot** [comment]
It is related, yes (I did not see this recent issue, at least I am not alone!), and PCRE was updated last year for this by Philip Hazel. I copy here the mails he sent to me (in January 2019), if it can help.

> Thank you for raising this issue. When names were first invented for
> PCRE, before Perl had them, it seemed sensible to restrict them to
> letters, underscore, and digits. Perl eventually introduced named
> groups, but I didn't make any changes to PCRE, and I haven't thought
> about non-ASCII characters in names. I have just had a quick look at
> Perl's current documentation. It says two things:
> 
> 1. "name must not begin with a number, nor contain hyphens", which isn't
> very helpful.
> 
> 2. "Currently NAME is restricted to simple identifiers only.  In other
> words, it must match "/^[_A-Za-z][_A-Za-z0-9]*\z/" or its Unicode
> extension (see utf8), though it isn't extended by the locale (see
> perllocale)."
> 
> I have yet to find where in the copious Perl documentation it has a
> definition for this extension. However, a quick test indicates that it
> does allow, for example, ABáC as a name. I will do some more research
> and then investigate upgrading PCRE2 in line with Perl. The next PCRE2
> release (10.33) is likely to come out in a couple of months' time. I
> will let you know when there is something to test.
> 
> Regards,
> Philip

> I have just committed a patch that upgrades PCRE2 to be more like Perl.
> If it is running in UTF mode, capture group names are now allowed to
> contain Unicode letters and Unicode decimal digits (and underscore). In
> other words, names must match this pattern:
> 
>   ^[_\p{L}][_\p{L}\p{Nd}]*\z
> 
> The next release (10.33) is likely to happen in a couple of months'
> time. In the meantime, you can check out the the latest code like this:
> 
> svn co svn://vcs.exim.org/pcre2/code/trunk pcre2
> 
> Regards,
> Philip

**Comment by vtjnash** [comment]
Fixed by #39310
