### ISSUE TITLE
Hashes change whenever package is pre-compiled

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#35469]
I have a very simple package I am developing, say defined like this:

```
module MyPkg
struct A
   a::Int
end
end # module
```

Now in a Julia session, I import this package, and compute a hash of an object:

```
julia> using MyPkg # first-usage, precompiles
julia> hash(A(5)) # returns a hash
```

Next, I do some modification of the package source code,

```
module MyPkg
struct A
   a::Int
end
f() = 2 # modification of package source code
end # module
```

So next time I use this package, a precompilation is triggered again:

```
julia> using MyPkg # precompiles again
julia> hash(A(5)) # returns a different hash than before!
```

Even though the type `A` has not changed, I now get a different hash for `A(5)`. This is due to `hash` falling back to `objectid`.

Note that here I am doing "minor" modifications, in that things like the package identity (name, uuid) and the type `A` definition have not changed. So I'd expect a consistent hash value (up to the allowable rare collisions).

On discourse: https://discourse.julialang.org/t/hashes-change-whenever-package-is-pre-compiled/37555

**Comment by KristofferC** [comment]
> This is due to hash falling back to `objectid`.

> So I'd expect a consistent hash value (up to the allowable rare collisions).

I'm trying to understand why you would write the second sentence here, after writing the first one.

**Comment by cossio** [comment]
> > This is due to hash falling back to `objectid`.
> 
> > So I'd expect a consistent hash value (up to the allowable rare collisions).
> 
> I'm trying to understand why you would write the second sentence here, after writing the first one.

As it is currently implemented, `hash` falls back to `objectid`, which returns a different value that changes with pre-compilation.

What I am asking is whether this is indeed the expected behavior that we want from `hash`? If the definition of `A` has not changed, and the package identity has not changed, shouldn't we get a consistent hash in the example above?

**Comment by KristofferC** [comment]
> What I am asking is whether this is indeed the behavior that one should expect

Yes, it is to be expected. The hash function should satisfy `isequal(x,y) => hash(x) == hash(y)` which this does.
