### ISSUE TITLE
dense matrix times adjoint of sparse matrix returns a sparse matrix

### ISSUE THREAD

**Issue by guochu** [JuliaLang/julia#35470]
The result of a dense matrix times a sparse matrix is a dense matrix, which is expected. However a dense matrix times the adjoint of a sparse matrix is a sparse matrix. Is this by design or a bug? 
See the following code for example:
`using SparseArrays: sparse
println(typeof(randn(2,2) * sparse([0. 1; 1 0])))
println(typeof(randn(2,2) * sparse([0. 1; 1 0])' ))`

**Comment by dkarrasch** [comment]
This has been fixed in the Julia v1.3 cycle: https://github.com/JuliaLang/julia/commit/618c9104ba5f4452356746567272e48bbdf489d9

Son, on the current Julia v1.4 both operations return dense matrices.
