### ISSUE TITLE
Bad color (magenta) in REPL

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#35472]
It's very difficult to see on black background.

A. At least for "x \times 2^n." (and "ldexp(x, n)" could also use better color), as seen with:

`help?> ldexp
`

B. I think " \times" should also substitute, as it's LaTeX, while I'm less concerned personally with that.

**Comment by Keno** [comment]
Change your terminal color scheme?

**Comment by Keno** [comment]
(The problem here is that the colors look different for everybody, so if we change it to something that looks fine on your terminal, it'll start looking really bad on somebody else's terminal)

**Comment by JeffBezanson** [comment]
Maybe we just use too many different colors. Does math need to be purple? Maybe bold instead?

**Comment by PallHaraldsson** [comment]
I mean this a bad on a black background, what I have in the terminal, and I think pretty much done (at least default in Ubuntu) and in most editors.

I'm not up to speed on "terminal color scheme" if it's about the background color or something else, and I doubt most users will neither know. I think we should have a sane default for the most common setup, and others can change.

**Comment by Keno** [comment]
The problem is that unless we ship our own terminal emulator on every OS (which I'm not entirely opposed to), there's no way to pick a sane default, because whatever we pick will look different for everybody. For example, the purple is perfectly readable on my terminal, even with a black background:

![Screen Shot 2020-04-15 at 9 45 55 AM](https://user-images.githubusercontent.com/1291671/79344569-00e4a980-7efe-11ea-99af-43eb545afe97.png)
 
Blue isn't particularly readable though.

**Comment by KristofferC** [comment]
Tangentially, windows updated their default colors not too long ago https://devblogs.microsoft.com/commandline/updating-the-windows-console-colors/.

**Comment by PallHaraldsson** [comment]
I would suggest changing to the brighter colors, i.e. from purple ("Palette entry 5") to the lighter purple "Palette entry 13" (and e.g. 6->14). I'm just unsure where to find this in the code to make a PR (I could check).

I first found "Use colors from the system theme" checked (and I don't think I've ever changed it or to more custom) in the terminal, and toggling the switch doesn't make much difference.

Users redefining the palette, might like me first change the lighter purple to no effect, end even with finding the right color seems like a hassle, and not recommend (would screw up other terminal work? or make it better too...).

[Only changing the background to white DID make for readable, while still also an awful (while less so) scheme.]

**Comment by PallHaraldsson** [comment]
>purple is perfectly readable on my terminal, even with a black background [..]
>Blue isn't particularly readable though.

Hmm, I guess it's my eye, and not just the astigmatism. Because the magenta (purple) in your screenshot isn't too readable for me (while a bit better than in my terminal), but your cyan (blue) as actually ok to me. Is the PR with a fix (hopefully, not yet tested for me) ok for you?

**Comment by elextr** [comment]
If at all possible the default needs to be readable by contrast to the background alone, remember nearly 10% of males have a colour deficiency (rather less females).

**Comment by StefanKarpinski** [comment]
The end of this literal debate about what colors to paint the bike shed is that nothing works well everywhere for everyone except for no color. However, if a color scheme is bad for someone, they know that color schemes are a thing and they can change them. If the default is no color then people don’t know that colors are an option and they don’t ever turn color on. It would be fine to make it easy to design color schemes and share them.

**Comment by KristofferC** [comment]
> If at all possible the default needs to be readable by contrast to the background alone, 

See the `--color=no` command line option. Also, note that we don't really have any fine tuning possibilities since we are only using the system colors of which there are 16 (8 + 8 bright versions).

**Comment by KristofferC** [comment]
Solution is to change to a colorscheme where the default colors are not bad.
