### ISSUE TITLE
[Bug] Unable to launch Julia 1.4 App on MacOS Catalina

### ISSUE THREAD

**Issue by madprogramer** [JuliaLang/julia#35480]
Reposting from the [Julia Discourse](https://discourse.julialang.org/t/issue-with-upgrading-to-1-4-on-macos-catalina/36969):

After upgrading the Julia App could just never seem to launch, often resulting in the following error or just hanging:

![](https://aws1.discourse-cdn.com/business5/uploads/julialang/original/2X/c/c1c0b2501352f2b3248bfb40c1ad23207fd83665.png)

Solution:

Launching Julia from the Terminal once will successfully work and "release" all the locked up instances as well. (So you might launch multiple Julia instances if you haven't fully quit the hanging Applications.)

**Comment by ViralBShah** [comment]
Please reopen if you still face this with a recent release.

**Comment by madprogramer** [comment]
This should no longer be an issue 2 years later but here is cormullion's work-around for posteriority:
https://discourse.julialang.org/t/issue-with-upgrading-to-1-4-on-macos-catalina/36969/3
