### ISSUE TITLE
Typo in base/int.jl on line 113

### ISSUE THREAD

**Issue by cjwyett** [JuliaLang/julia#35484]
Return `true` **is** `x` is even (that is, divisible by 2), and `false` otherwise.
Should read:
Return `true` **if** `x` is even (that is, divisible by 2), and `false` otherwise.

**Comment by rfourquet** [comment]
Thanks for reporting the issue, would you like to make a pull request to fix it?

**Comment by cjwyett** [comment]
Yes I'd be delighted too

**Comment by rfourquet** [comment]
Very nice :)

**Comment by rfourquet** [comment]
Fixed in #35491
