### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by aradavid** [JuliaLang/julia#35487]
just tried to download today the Julia 1.4 documentation from your site https://docs.julialang.org/en/v1/ but the link reports Error 404, not found

**Comment by fredrikekre** [comment]
It will be built and published in 2 hours. It is being built by the cronjob here: https://travis-ci.org/github/JuliaLang/docs.julialang.org/builds

**Comment by fkoschier** [comment]
However, the link for 1.4.1 works and downloads the file (although it still prints 404 not found):
https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.4.1.pdf
