### ISSUE TITLE
Duplicated example in document of Multi-dimensional Arrays.

### ISSUE THREAD

**Issue by newptcai** [JuliaLang/julia#35503]
There is a duplicated example here

https://github.com/JuliaLang/julia/blame/master/doc/src/manual/arrays.md#L139

https://github.com/JuliaLang/julia/blame/master/doc/src/manual/arrays.md#L146

**Comment by OkonSamuel** [comment]
@StefanKarpinski  or @fredrikekre  since this has been resolved. I belive this can be closed
