### ISSUE TITLE
Feature request: Quarter

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#35517]
Could there be a `Quarter <:  DatePeriod` type in Dates?

**Comment by StefanKarpinski** [comment]
Would that be different from 3 months in any way? My understanding of a quarter is that it's not a duration so much as a fixed splitting of each year. I.e. it's weird to say "a quarter later" if you mean "three months from today"; rather, you refer to the first, second, third and fourth quarters of a given year to refer to a period of time.

**Comment by matthieugomez** [comment]
Public firms must report earnings every quarter — they do say "next quarter/last quarter".
Not all quarters start in January (for instance Costco's first quarter for their fiscal year starts in September). A lot of accounting datasets are at a quarterly frequency, so defining `Quarter` makes it easier to work with these datasets (for instance: what is the growth of earnings between this quarter and next quarter etc...)

It is true that a quarter is exactly three months. But then a week is exactly seven days, and we still define  `Week <: TimePeriod` as a period.

**Comment by StefanKarpinski** [comment]
👍 The PR looks non-trivial enough to make sense.

**Comment by matthieugomez** [comment]
Solved by https://github.com/JuliaLang/julia/pull/36364
