### ISSUE TITLE
Add Julia API for SuiteSparseQR

### ISSUE THREAD

**Issue by kbatseli** [JuliaLang/julia#3554]
But needs to be called via its C interface.

It would be nice if it would be possible to just type spqr(A) in Julia to call the SuiteSparseQR command. Or alternatively the command qr(A), where Julia would internally call spqr for when the argument A is a sparse matrix.

**Comment by ViralBShah** [comment]
@andreasnoack implements this in #10180.

**Comment by ViralBShah** [comment]
Closed by #10180
