### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by kendrawu** [JuliaLang/julia#35541]
I've found a bug in sample. Result gives duplicate elements, c, despite replace=false.
Example code:
`c = sample(a, b, replace=false, ordered=true)`

Using JuliaPro-Juno-1.3.1.0 and JuliaPro-Juno-1.3.1.1.

**Comment by rfourquet** [comment]
Thanks for the report, but `sample` doesn't belong in this repository, I believe it comes from the `StatsBase` package, consider opening the issues at https://github.com/JuliaStats/StatsBase.jl/. Also, if you do, include more information as one can't reproduce the bug without knowing what the values of `a` or `b` are. For example, `sample([1, 1, 2], 3, replace=false, ordered=true)` returns an array with duplicate elements but this is not a bug in this case, as the input `[1, 1, 2]` also has duplicate elements.
