### ISSUE TITLE
Modifying Base functions to use IntelVectorMath

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/julia#35540]
Hi,

Currently, there seems to be no way to make use of functions in https://github.com/JuliaMath/IntelVectorMath.jl to speed up arbitrary Julia code without pirating `map(f, x)` where `f` is a function supported in IVM. It would be nice to have a way to speed up `map` for these functions automatically much like how MKL.jl replaces OpenBLAS by just building it.

**Comment by JeffBezanson** [comment]
This might be a case where type piracy is appropriate. (Our BLAS wrappers use type piracy for basically this reason.)

**Comment by mohamed82008** [comment]
Alright, I guess I will make a PR to IVM then, thanks!
