### ISSUE TITLE
within `for` loop, invalid `if` condition is ignored when `if` body is empty 

### ISSUE THREAD

**Issue by blegat** [JuliaLang/julia#35549]
Consider the invalid code `if true &&`. The behavior is a bit surprising.
First, if a printing is inside the `if` statement, the `println` statement is printed before the error is thrown. Second, if the `if` statement is inside a `for`-loop, no error is thrown and `&&` are just ignored.
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

julia> if true &&
           println("*")
       end
*
ERROR: TypeError: non-boolean (Nothing) used in boolean context
Stacktrace:
 [1] top-level scope at REPL[50]:1

julia> for i in 1:2
           if true &&
               println("*")
           end
       end
*
*
```

**Comment by rfourquet** [comment]
The first case (simple `if`) is expected, the syntax is not invalid, a `&&` can be at the end of the line and the control flow continues on next line. The case of the for loop is indeed a bit surprising, it is equivalent to 
```julia
for i=1:2
    if nothing end
end
```
It looks as if the whole `if` block is eliminated as dead code, but errors as expected if the code inside it has a side-effect.

**Comment by adienes** [comment]
was curious about / poking around older-listed bugs. the original issue here does not reproduce for me on 1.9.0
