### ISSUE TITLE
Is there a change of Libdl.find_library between 1.3 and 1.4

### ISSUE THREAD

**Issue by shipengcheng1230** [JuliaLang/julia#35548]
Hello, I encounter this problem when loading the same Gmsh SDK (download at [here](http://gmsh.info/bin/Windows/gmsh-4.5.6-Windows64-sdk.zip)) on windows platform. See MWE below:

Start with everything fresh, it works on **v1.3.1**:

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

julia> cd(raw"C:\Users\User\Downloads\gmsh-4.5.6-Windows64-sdk\gmsh-4.5.6-Windows64-sdk\lib")

julia> include("gmsh.jl")
Main.gmsh

julia> gmsh.initialize()

julia> gmsh.model.mesh.getElementProperties(5)
("Hexahedron 8", 3, 1, 8, [-1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0  …  1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0], 8)

```

but failed on **v1.4.1**:

```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

julia> pwd()
"C:\\Users\\User\\AppData\\Local\\Programs\\Julia\\Julia-1.4.1"

julia> cd(raw"C:\Users\User\Downloads\gmsh-4.5.6-Windows64-sdk\gmsh-4.5.6-Windows64-sdk\lib")

julia> cd(readdir, ".")
4-element Array{String,1}:
 "gmsh-4.5.dll"
 "gmsh.jl"
 "gmsh.lib"
 "gmsh.py"

julia> include("gmsh.jl")
Main.gmsh

julia> gmsh.initialize()
ERROR: could not load library ""
The parameter is incorrect.
Stacktrace:
 [1] initialize(::Array{String,1}, ::Bool) at C:\Users\User\Downloads\gmsh-4.5.6-Windows64-sdk\gmsh-4.5.6-Windows64-sdk\lib\gmsh.jl:39
 [2] initialize() at C:\Users\User\Downloads\gmsh-4.5.6-Windows64-sdk\gmsh-4.5.6-Windows64-sdk\lib\gmsh.jl:38
 [3] top-level scope at REPL[7]:1

julia> dlopen("gmsh-4.5.dll") # works!
Ptr{Nothing} @0x00000000365b0000

julia> find_library(["gmsh-4.5"], [pwd()]) # this is what `include` calls under the hood
""
```

It seems to me something must be changed here but I couldn't find any docs related to this behavior. Is it a bug or am I missing something?

Thanks!

**Comment by Micket** [comment]
Works fine under linux. I see no recent code changes. I'm interested in knowing what you get from
```julia
dlopen(joinpath(pwd(), "gmsh-4.5"), RTLD_LAZY)
```

**Comment by shipengcheng1230** [comment]
@Micket  This is only problematic under windows. Below the error:
```julia
julia> cd(readdir, ".")
4-element Array{String,1}:
 "gmsh-4.5.dll"
 "gmsh.jl"
 "gmsh.lib"
 "gmsh.py"

julia> dlopen(joinpath(pwd(), "gmsh-4.5"), RTLD_LAZY)
ERROR: could not load library "C:\Users\User\Downloads\gmsh-4.5.6-Windows64-sdk\gmsh-4.5.6-Windows64-sdk\lib\gmsh-4.5"
The specified module could not be found.
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
 [2] dlopen(::String, ::UInt32) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Libdl\src\Libdl.jl:109
 [3] top-level scope at REPL[22]:1
```

**Comment by Micket** [comment]
I think I found the bug and the commit there it was introduced:
https://github.com/JuliaLang/julia/commit/f593456f886c93eefd132fbe6d97ebb5475a7e3c#diff-546cd044e18fcec4eed66dcdac75bfa2R193-R202
with a comment that claims:
```c
// LoadLibrary already tested the extensions, we just need to check the `stat` result
```
but according to https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw

> If the string specifies a module name **without a path** and the file name extension is omitted, and the module name does not contain any point character (.), then the function appends the default library extension .dll to the module name.

which means https://github.com/JuliaLang/julia/commit/f593456f886c93eefd132fbe6d97ebb5475a7e3c did indeed break this in windows.

**Comment by shipengcheng1230** [comment]
So it looks the `4.5` in the name hits the exception here, doesn't it?

**Comment by Micket** [comment]
@shipengcheng1230 I'm not sure, both the dot and the full path would count towards that exception. Without being able to test, i would think that
```julia
dlopen("/path/to/dll/gmsh-4.5.dll")  # works?
dlopen("/path/to/dll/gmsh-4_5")  # broken
dlopen("/path/to/dll/gmsh-4.5")  # doubly broken
dlopen("gmsh-4.5")  # probably also broken
dlopen("gmsh-4.5.dll")  # works
```
comment in julia code seems like it assumes LoadLibrary has the same behaviour as it's own loop over extensions, which it actually doesn't.

So, if you wish to have a quick fix for gmsh, just add the `.dll` extension.
I can kinda see what LoadLibrary is going for here; if you just specify the full path, then it expects you to to include the fileextension yourself, makes sense. I don't know if this should be considered a bug in julia or not (but it definitely is inconsistent across platforms right now)

**Comment by shipengcheng1230** [comment]
@Micket That's true, I agree there isn't sufficient reason to consider it as a bug but it certainly can cause people some time and effort should they encounter a similar one, where `libname` would presumably append `libext` itself but failed due to some non-standard naming scheme.

@vtjnash What do you think about this issue?

**Comment by simonbyrne** [comment]
I'm seeing a similar issue with 1.4 on Mac: `dlopen` no longer seems to search `/usr/local/lib`:
```
├ julia13 -e 'using Libdl; @show dlpath(dlopen("libmpi"))'
dlpath(dlopen("libmpi")) = "/usr/local/lib/libmpi.dylib"

├ julia14 -e 'using Libdl; @show dlpath(dlopen("libmpi"))'
ERROR: could not load library "libmpi"
dlopen(libmpi.dylib, 1): image not found
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109
 [2] dlopen at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
 [3] top-level scope at show.jl:613
```

**Comment by simonbyrne** [comment]
According to @staticfloat, the Mac issue is
> has to do with building against the hardened runtime, required for notarization
> Note that this is not documented ANYWHERE
