### ISSUE TITLE
`isa` fails for re-exported module types

### ISSUE THREAD

**Issue by ktsakas** [JuliaLang/julia#35550]
The bellow seems to be a bug in type equality when types are re-exported between modules.
I have three modules in the same folder.
The first one defines a type, the second one has a function that returns a variable of that type and the third one uses the other two:
```
# first module
module PokerHand
export Card

struct Card
    rank::Char
end
end
```
```
# second module
include("./PokerHand.jl")

module PokerGameRules
using Main.PokerHand
export get_card

get_card() = Card('A')
end
```
```
# third module
include("./PokerGameRules.jl")
include("./PokerHand.jl")

module MonteCarlo
using Main.PokerGameRules, Main.PokerHand

println(PokerGameRules.Card('A') isa PokerHand.Card)
println(get_card() isa Card)
println(get_card() isa PokerGameRules.Card)
end
```
This is the output when running the third module:
```
WARNING: replacing module PokerHand.
false
false
true
[Finished in 0.381s]
```

Shouldn't all print statements print true, since **the second module doesn't change the type in any way**?
Seems like type assertion is broken here.

**Comment by KristofferC** [comment]
You are including the same file multiple times which causes multiple separate definitions (that happen to have the same name). In general, each file should only be included once.

Feel free to discuss this further at https://discourse.julialang.org.
