### ISSUE TITLE
docs.julialang.org/en/latest not updated?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#35559]
The news page in https://docs.julialang.org/en/latest/NEWS/ is almost empty while there are many items in https://docs.julialang.org/en/v1.5-dev/NEWS/.  Is docs.julialang.org/en/latest still supposed to show the latest dev version?

**Comment by fredrikekre** [comment]
>  Is docs.julialang.org/en/latest still supposed to show the latest dev version?

No, not since a year or so, where did you get the `latest` link from?

**Comment by tkf** [comment]
Thanks for the clarification. It's been working until recently so I thought it was meant to be updated.

> where did you get the `latest` link from?

It's been in my bookmark.
