### ISSUE TITLE
[FR] Add option to display not to elide output

### ISSUE THREAD

**Issue by NightMachinary** [JuliaLang/julia#35551]
Per [this](https://stackoverflow.com/questions/37107133/how-to-show-all-output-in-julia), there is currently no way to use the pretty printing `display` to show all the output. As this is a fairly common usecase, adding it is a low-hanging fruit.

**Comment by rfourquet** [comment]
In the linked example, you can do:
```
show(IOContext(stdout, :limit=>false), MIME("text/plain"), subtypes(Any))
```
