### ISSUE TITLE
”contrib/julia.svg" has different color scheme and layout from other resources

### ISSUE THREAD

**Issue by kimikage** [JuliaLang/julia#35568]
The Julia logo was updated about a year ago.

Round 1 (https://github.com/JuliaLang/www.julialang.org/pull/372)
https://github.com/JuliaLang/www.julialang.org/blob/9c2ffde0233da26f7d5f1e07408823825860d46b/_includes/logo.svg

Round 2 (https://github.com/JuliaLang/julia/pull/32038)
https://github.com/JuliaLang/julia/blob/b5a4601bbe8a6f1b8ce8f4e307543850c08adb8e/contrib/julia.svg

Although there are some differences in numerical representation, the round 1 logo uses the color scheme defined in [julia-logo-graphics](https://github.com/JuliaLang/julia-logo-graphics/blob/79a3522cf1aa5e4a3a733620ef4dcb7d0d0c7d36/README.md).
However, the round 2 logo(i.e. julia.svg in this repository), has a slightly different color scheme. (see the "blue" dot.)

![julialogo](https://user-images.githubusercontent.com/12679384/80086369-90402b80-8594-11ea-858a-1b9703f0916a.gif)

WRT the layout, I can not exactly make sure the original intent, but WRT the color schemes, "contrib/julia.svg" is different from the original intent.

The original discussion: https://github.com/JuliaGraphics/Colors.jl/pull/418
cc: @cormullion

**Comment by StefanKarpinski** [comment]
The contrib/julia.svg image is definitely off here: the colors are off, the placement of the dots is off. It should either be deleted or replaced with an SVG that matches julia-logo-graphics. Unclear if the file used for anything? cc @ViralBShah

**Comment by cormullion** [comment]
😰I’m very sorry, I must have committed the wrong version (too many files with the same name floating around combined with my poor git skills).

**Comment by ViralBShah** [comment]
The contrib file should just be deleted.

**Comment by ViralBShah** [comment]
In fact `contrib` is the wrong name for what that directory contains.

**Comment by StefanKarpinski** [comment]
No worries, @cormullion! Just good to get it sorted out.

**Comment by kimikage** [comment]
Although we should clean [the table](https://github.com/JuliaLang/julia/commit/a8275e544abbccf39faece64d89f80e4fa8f068c#commitcomment-38698504), this problem is resolved, and the PR in Colors.jl can also be resolved. Thanks!
