### ISSUE TITLE
printf fails to install in JuliaPro as well as Julia

### ISSUE THREAD

**Issue by OrbitalMechanic** [JuliaLang/julia#35567]
I have version 1.4.1-1 of JuliaPro and Julia on a MacPro (2019).  I attempted to install the function printf. The installation failed.

Two files have been attached to this note. A PDF has been attached that contains the source code. The second file is a text file that contains the results of the installation attempt.

Please advise.

Sam Dupree.

[printf_installation_failure.txt](https://github.com/JuliaLang/julia/files/4520466/printf_installation_failure.txt)

[MySIR-2.1.pdf](https://github.com/JuliaLang/julia/files/4520483/MySIR-2.1.pdf)

**Comment by KristofferC** [comment]
The standard library is called `Printf` (note the capitalization).
