### ISSUE TITLE
replace() allows invalid parameters

### ISSUE THREAD

**Issue by chrstphrbrns** [JuliaLang/julia#35573]
`> applicable(replace, 1, 2 => 3)`
`true`

`> replace(1, 2 => 3)`
`no method matching similar(...)`

**Comment by yuyichao** [comment]
`applicable` never means no error. There are constraints (or in general semantics) that's impossible to express in the type signature in a way that gives the desire outcome and `applicable` will not be able to reflect those.

**Comment by chrstphrbrns** [comment]
Good to know, but in this case, `replace` is simply allowing more than it should, as it indirectly calls a function that is type-constrained (`_replace!`)

**Comment by rfourquet** [comment]
> replace is simply allowing more than it should, as it indirectly calls a function that is type-constrained (_replace!)

In this particular case, `replace` is the surface API and could accept any collection, for which there is no all-encompassing generic supertype. The "backend" `_replace!` is implemented only for some types in `Base`, but package authors can hook into the `replace` (semi-official) API simply by implementing `_replace!(x::X, ...)`, and `replace(::X, pairs...)` will work automatically.

But as Yichao said, the first argument of `replace` being not constrained is no promise that it accepts anything, this is just how programming in Julia works. Another example among countless, `applicable(rand, 'a')` returns `true` and this is simply not practical to prevent that.
