### ISSUE TITLE
BUG unexpected result of function call using same name as struct

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#35588]
Reported by Dhairya in https://julialang.slack.com/archives/C6A044SQH/p1587743056401800

This can be observed in v"1.5.0-DEV.676", v"1.4.1" and v"1.0.5".
The function has the same name as the parmeterized struct. Obviously the rhs of the function definition is ignored, while the default constructor for the struct is called.

```
julia> struct MWE2{T}
         a::T
         b::T
       end

julia> MWE2(a = 1, b = 2) = (MWE(a, b), a)
MWE2

julia> MWE2()
MWE2{Int64}(1, 2)

julia> MWE2(a = 1, b = 2) = a + b
MWE2

julia> MWE2()
MWE2{Int64}(1, 2)

julia> struct MWE3{T}
         a::T
         b::T
       end

julia> MWE3()
ERROR: MethodError: no method matching MWE3()
Closest candidates are:
  MWE3(::T, ::T) where T at REPL[6]:2
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7357

**Comment by yuyichao** [comment]
Fwiw I thought Jeff had a problem that fixes this and I even thought it was merged already. Am I imagining that?

**Comment by JeffBezanson** [comment]
This isn't a bug, it's the intended behavior. #7357 has a long discussion. In any case, changing it would be hugely breaking.

**Comment by yuyichao** [comment]
Yeah now it's not the time to change it. I thought you made the change in 0.7 but apparently not.....

**Comment by KlausC** [comment]
It was not obvious at the first sight what happened here. Especially when considering the counter-example with a struct that was not parmeterized. I try to explain it this way:
It is a consequence of how default values of arguments are handled. What happens is:

1. The struct definition defines method `MWE2(a::T, b::T) where T`
2. The method definition extends to 
     `MWE2(a, b) = (MWE....)`
     `MWE2(a) = MWE2(a, 2)`
     `MWE2() = MWE2(1, 2)`
3. There are now 4 different methods for function `MWE2`. Calling `MWE2()` calls `MWE2(1, 2)` and that dispatches to the first (constructor) method, because that is more specific than the intended second one.
4. You can call the second method by
     `MWE2(1.0)` or `MWE(3, 4.0)`
5. If you give the method definition the same signature or a more specific signature than the constructor, for example `MWE2(a::Int=1, b::Int=2) = 1` that one would have been called. `MWE2(a::T=1,b::T=2) where T = 2` would also work, this time invalidating the constructor completely.
To analyze the situation, you can use `methods(MWE2)` before and after the definitions you make.
