### ISSUE TITLE
Bound version of BugReporting.jl?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#35602]
Currently, `--bug-report` installs any version of BugReporting.jl

https://github.com/JuliaLang/julia/blob/ecc0c434fae2438c05093b0fb1443b21c5463825/stdlib/InteractiveUtils/src/InteractiveUtils.jl#L370-L371

It may be better to pass `version = "0.1"` to `PackageSpec` so that older `julia` works even after BugReporting.jl API is updated.  (Or use `version = "1"` after releasing BugReporting.jl 1.0?)

**Comment by Keno** [comment]
The idea was to let the package evolve rapidly such that we can get newer improvements even on older julia versions if compatible. If not compatible, we should set appropriate bounds on the julia version in the registry.

**Comment by tkf** [comment]
I find that relying on mutating global datastore like the General registry is somewhat ugly, personally.  Though I suppose practicality beats purity here.
