### ISSUE TITLE
Feature Request: REPL Pasting for Package, Shell Modes

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/julia#35605]
Based on a Slack gripe. Would be quite nice to have REPL pasting for these modes. 

One place where this comes up is giving people setup instructions to copy/paste (which doesn't currently work, because they need to manually hit `]`).

**Comment by kimikage** [comment]
I cannot find the Slack gripe, but the new feature will determine the mode based on  the `julia> `/`pkg> `/`shell> ` in the line head, and strip them (and the REPL outputs). Is my understanding correct?

**Comment by EthanAnderes** [comment]
I've wanted this type of thing for a long time.
I don't know the Slack reference either but anyway it 
would be great to be able to paste a whole block 
like this into the REPL.

```
julia> ENV["JULIA_FFTW_PROVIDER"] = "MKL"
shell> git clone ... classdir
shell> cd classdir
pkg>   activate . # activates classdir
pkg>   add FFTW
pkg>   activate # returns to default env
```

Not only would it be useful for me, but also 
for sending students and colleagues instructions. 

I would be willing to do some work to help it get done, but 
need some tips on how to do it (I took a look a while back but 
realized it was over my head).

**Comment by pbouffard** [comment]
`pkg>` and `shell>` pasting actually works as of 1.9, I just happened to discover accidentally. It seems to be undocumented, or rather explicitly documented as not supported: https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/docs/src/index.md?plain=1#L47

> In Julia mode, the REPL supports something called *prompt pasting*. This activates when pasting
text that starts with `julia> ` into the REPL. In that case, only expressions starting with
`julia> ` are parsed, others are removed.

**Comment by arnavs** [comment]
Good catch! Closing this issue.
