### ISSUE TITLE
Multiplying triangular sparse matrix with sparse matrix fails to return sparse matrix

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#35610]
Multiplying an `UpperTriangular{SparseMatrixCSC}` with a `SparseMatrixCSC` should return a sparse matrix. It returns a dense matrix as of version 1.2.
Computational effort should be approximately 1/2 of sparse multiplication of SparseMatrixCSC.

```
julia> VERSION
v"1.4.1" # same for v"1.2.0"
julia> X = UpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> typeof(X * Y)
Array{Float64,2}
```
With version 1, we have the same error as in #35609
```
julia> VERSION
v"1.0.5"
julia> X = UnitUpperTriangular(sprand(100, 100, 10*1e-2));
julia> Y = sprand(100, 10, 10*1e-2);
julia> X * Y;
ERROR: MethodError: no method matching lmul!(::UnitUpperTriangular{Float64,SparseMatrixCSC{Float64,Int64}}, ::SparseMatrixCSC{Float64,Int64})
```

**Comment by Micket** [comment]
https://github.com/JuliaLang/julia/blob/2f90dded2ac6577197285fd48e20edbbd8732561/stdlib/SparseArrays/src/linalg.jl#L767-L768

Looks to me that there was some type of attempt to treat `*` and `\` similarly, though, I can't think of any case where you actually would want to do that. 

Y*X actually does the right thing there, and just reverts to calling
https://github.com/JuliaLang/julia/blob/2f90dded2ac6577197285fd48e20edbbd8732561/stdlib/SparseArrays/src/linalg.jl#L49-L50
and, as far as I can see, this methods exists
https://github.com/JuliaLang/julia/blob/2f90dded2ac6577197285fd48e20edbbd8732561/stdlib/SparseArrays/src/linalg.jl#L128-L129
and already does the correct thing.

So, i think this should simply be removed:
```julia
(*)(L::TriangularSparse, B::AbstractSparseMatrixCSC) = lmul!(L, Array(B))
```

**Comment by KlausC** [comment]
> Y*X actually does the right thing there;

The point of `T * A` is the return type, which should be sparse, not dense.

> as far as I can see, this methods exists and does the right thing already

The problem with `A * T` is the execution efficiency. `mul!` is using a generic implementation here, which does not take much advantage of the sparsity.

The pending PR fixed both cases using the famous Gustafson multiplication algorithm.
