### ISSUE TITLE
Failed to compile on Fedora 32

### ISSUE THREAD

**Issue by xijiang** [JuliaLang/julia#35638]
Fedora 32 (just upgraded)
Pulled here a few hours ago.
Compile stopped after two errors:
1. julia/contrib/normalize_triplet.py", line 112, in <module>
    libgfortran_version = {
    KeyError: '1'
2. curl: (22) The requested URL returned error: 404 Not Found
    julia/deps/suitesparse.mk:144: 
    julia/deps/srccache/SuiteSparse.v5.4.0-6..tar.gz] Error 22

**Comment by fredrikekre** [comment]
What `gfortran` version do you have installed?

**Comment by xijiang** [comment]
GNU Fortran (GCC) 10.0.1 20200328 (Red Hat 10.0.1-0.11)

**Comment by fredrikekre** [comment]
I guess https://github.com/JuliaLang/julia/blob/18674303bdfb5670f3bd36dd0e6ba0e6cf2bcd8b/contrib/normalize_triplet.py#L113-L118 has to be extended to include version 10.

**Comment by xijiang** [comment]
I pulled this morning. It still has the same errors.

> Traceback (most recent call last):
  File "/home/xijiang/Music/julia/contrib/normalize_triplet.py", line 112, in <module>
    libgfortran_version = {
KeyError: '1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   453  100   453    0     0   1043      0 --:--:-- --:--:-- --:--:--  1043
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make[1]: *** [/home/xijiang/Music/julia/deps/suitesparse.mk:144: /home/xijiang/Music/julia/deps/srccache/SuiteSparse.v5.4.0-6..tar.gz] Error 22
make: *** [Makefile:60: julia-deps] Error 2

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/35653 has not been merged yet
