### ISSUE TITLE
docstring for the ternary operator

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#35636]
I wonder if it would be possible to have a docstring for the ternary operator (`?`). Currently help mode for `?` gives the [general help intro](https://github.com/JuliaLang/julia/blob/51484175dee4b0566b270fd62356b1198afdba22/base/docs/basedocs.jl#L27). Would it make sense to special-case `?` and shoehorn eg the following in there:

> `a ? b : c` 
>
> Short form for conditionals, also known as the ternary operator. Equivalent to
> ```julia
> if a
>     b
> else
>     c
> end

**Comment by c42f** [comment]
I think I know how to do this fairly easily, hold on.

**Comment by c42f** [comment]
See #35637
