### ISSUE TITLE
Error downloading 1.4.1 for Linux x86

### ISSUE THREAD

**Issue by sbacelar** [JuliaLang/julia#35639]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by sbacelar** [comment]
I tried to install `v.1.4.1` for `Linux x86 64bits` and when I try to run it shows `v.1.0.4`.

**Comment by fredrikekre** [comment]
https://julialang.org/downloads/#current_stable_release

**Comment by sbacelar** [comment]
I downloaded it again from this address but the problem still remains.

**Comment by KristofferC** [comment]
Then you are not running the version you downloaded.

**Comment by sbacelar** [comment]
Sorry, you're right.
