### ISSUE TITLE
julia 1.4.1 LibGit2 tests fails on NixOS

### ISSUE THREAD

**Issue by cstich** [JuliaLang/julia#35640]
`@test LibGit2.credential_helpers(cfg, mygit_cred) == expected[2:2]` introduced at this commit (https://github.com/JuliaLang/julia/commit/f1593e1db479e90033e2ce96e31cf2333ea85413) does not work properly on NixOS. When I try to compile 1.4.1 and then run the tests, I get the following error:

>Error in testset file:
Test Failed at /tmp/nix-build-julia-1.4.1.drv-0/source/test/file.jl:70
  Expression: dirname(t) == d
   Evaluated: "/tmp/nix-build-julia-1.4.1.drv-0" == "/tmp/nix-build-julia-1.4.1.drv-0/jl_aPXajU"
Error in testset LibGit2/libgit2:
Test Failed at /tmp/nix-build-julia-1.4.1.drv-0/source/usr/share/julia/stdlib/v1.4/LibGit2/test/libgit2.jl:1983
  Expression: LibGit2.credential_helpers(cfg, mygit_cred) == expected[2:2]
   Evaluated: LibGit2.GitCredentialHelper[LibGit2.GitCredentialHelper(`echo first`), LibGit2.GitCredentialHelper(`echo second`)] == LibGit2.GitCredentialHelper[LibGit2.GitCredentialHelper(`echo second`)]
ERROR: LoadError: Test run finished with errors
in expression starting at /tmp/nix-build-julia-1.4.1.drv-0/source/test/runtests.jl:67
make[1]: *** [Makefile:25: all] Error 1
make[1]: Leaving directory '/tmp/nix-build-julia-1.4.1.drv-0/source/test'
make: *** [Makefile:577: testall] Error 2
builder for '/nix/store/10xkbc3ahq406a3s2rdy226ppc69qa4y-julia-1.4.1.drv' failed with exit code 2
error: build of '/nix/store/10xkbc3ahq406a3s2rdy226ppc69qa4y-julia-1.4.1.drv' failed

Any chance anyone knows whether this is a bug in julia or actually a nix issue? Although I am using the provided `LibGit2` library to compile 1.4.1 (at least I think I am).

**Comment by omus** [comment]
I suspect that the libgit2 library isn't respecting ordering for iterators. Can you try running:
```julia
using LibGit2, Test

mktempdir() do dir
    config_path = joinpath(dir, "gitconfig")
    open(config_path, "w+") do fp
        write(fp, """
            [credential]
                helper = !echo first
            [credential "https://mygithost"]
                helper = ""
            [credential]
                helper = !echo second
            """)
    end

    LibGit2.with(LibGit2.GitConfig(config_path, LibGit2.Consts.CONFIG_LEVEL_APP)) do cfg
        @test LibGit2.split_cfg_entry.(LibGit2.GitConfigIter(cfg, r"credential.*")) == [
            ("credential", "", "helper", "!echo first"),
            ("credential", "https://mygithost", "helper", ""),
            ("credential", "", "helper", "!echo second"),
        ]
    end
end
```

**Comment by cstich** [comment]
That actually works.

**Comment by omus** [comment]
Okay, I've gone over the rest of the code and nothing else jumps out at me. Here's a more exhaustive test suite which hopefully provides some insight:
```julia
using LibGit2, Test

mktempdir() do dir
    @testset "Debug" begin
        config_path = joinpath(dir, "gitconfig")
        open(config_path, "w+") do fp
            write(fp, """
                [credential]
                    helper = !echo first
                [credential "https://mygithost"]
                    helper = ""
                [credential]
                    helper = !echo second
                """)
        end

        LibGit2.with(LibGit2.GitConfig(config_path, LibGit2.Consts.CONFIG_LEVEL_APP)) do cfg
            @test LibGit2.split_cfg_entry.(LibGit2.GitConfigIter(cfg, r"credential.*\.helper")) == [
                ("credential", "", "helper", "!echo first"),
                ("credential", "https://mygithost", "helper", ""),
                ("credential", "", "helper", "!echo second"),
            ]

            expected = [
                LibGit2.GitCredentialHelper(`echo first`),
                LibGit2.GitCredentialHelper(`echo second`),
            ]

            github_cred = LibGit2.GitCredential("https", "github.com")
            mygit_cred = LibGit2.GitCredential("https", "mygithost")

            @test LibGit2.ismatch("", github_cred)
            @test !LibGit2.ismatch("https://mygithost", github_cred)
            @test LibGit2.ismatch("", mygit_cred)
            @test LibGit2.ismatch("https://mygithost", mygit_cred)

            @test LibGit2.credential_helpers(cfg, github_cred) == expected
            @test LibGit2.credential_helpers(cfg, mygit_cred) == expected[2:2]

            Base.shred!(github_cred)
            Base.shred!(mygit_cred)
        end
    end
end
```
If you could also execute these tests on the version before the changes you mentioned (`f1593e1^`) I think we'll have a better idea as to what is going on.

**Comment by cstich** [comment]
On julia 1.4.1 I get

> Test Summary: | Pass  Total
Debug         |    7      7
Test.DefaultTestSet("Debug", Any[], 7, false)

and on julia 1.3.1

>Debug: Test Failed at REPL[2]:16
  Expression: LibGit2.split_cfg_entry.(LibGit2.GitConfigIter(cfg, #= REPL[2]:16 =# @r_str("credential.*\\.helper"))) == [("credential", "", "helper", "!echo first"), ("credential", "https://mygithost", "helper", ""), ("credential", "", "helper", "!echo second")]
   Evaluated: Tuple{SubString{String},SubString{String},SubString{String},String}[("credential", "https://mygithost", "helper", ""), ("credential", "", "helper", "!echo first"), ("credential", "", "helper", "!echo second")] == NTuple{4,String}[("credential", "", "helper", "!echo first"), ("credential", "https://mygithost", "helper", ""), ("credential", "", "helper", "!echo second")]
Stacktrace:
 [1] (::var"#5#8")(::GitConfig) at ./REPL[2]:16
 [2] with(::var"#5#8", ::GitConfig) at /tmp/nix-build-julia-1.3.1.drv-0/source/usr/share/julia/stdlib/v1.3/LibGit2/src/types.jl:1125
 [3] macro expansion at ./REPL[2]:15 [inlined]
 [4] macro expansion at /tmp/nix-build-julia-1.3.1.drv-0/source/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107 [inlined]
 [5] (::var"#3#6")(::String) at ./REPL[2]:3
┌ Warning: Resetting the helper list is currently unsupported:
│ ignoring all git credential helpers
└ @ LibGit2 /tmp/nix-build-julia-1.3.1.drv-0/source/usr/share/julia/stdlib/v1.3/LibGit2/src/gitcredential.jl:234
Debug: Test Failed at REPL[2]:36
  Expression: LibGit2.credential_helpers(cfg, mygit_cred) == expected[2:2]
   Evaluated: LibGit2.GitCredentialHelper[] == LibGit2.GitCredentialHelper[LibGit2.GitCredentialHelper(`echo second`)]
Stacktrace:
 [1] (::var"#5#8")(::GitConfig) at ./REPL[2]:36
 [2] with(::var"#5#8", ::GitConfig) at /tmp/nix-build-julia-1.3.1.drv-0/source/usr/share/julia/stdlib/v1.3/LibGit2/src/types.jl:1125
 [3] macro expansion at ./REPL[2]:15 [inlined]
 [4] macro expansion at /tmp/nix-build-julia-1.3.1.drv-0/source/usr/share/julia/stdlib/v1.3/Test/src/Test.jl:1107 [inlined]
 [5] (::var"#3#6")(::String) at ./REPL[2]:3
Test Summary: | Pass  Fail  Total
Debug         |    5     2      7
ERROR: Some tests did not pass: 5 passed, 2 failed, 0 errored, 0 broken.

Now I was definitely not expecting that result. However, I would not be too surprised, if this eventually turns out to be an artifact of how nix compiles binaries and runs the test suite after compilation. If that is the conclusion, then I am happy to close this issue and work around this issue when I try to package 1.4.1 for nix.

**Comment by omus** [comment]
I appreciate you checking. The failure on Julia 1.3.1 is expected with the test suite I provided. At this point the issues does appear to be unrelated to the Julia LibGit2 stdlib or its tests.

You may want to try `Base.runtests("LibGit2")` on Julia 1.4.1 for good measure.

**Comment by fingolfin** [comment]
@cstich Is this issue still present in Julia 1.5.2?

**Comment by cstich** [comment]
@fingolfin Actually no. So we can close this
