### ISSUE TITLE
Compile openblas with openmp

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35652]
We have been compiling a bunch of libraries in BB with openmp support. Given that we now have all our toolchains reasonably well sorted out, it should be easy for us to build openblas with openmp support.

Does anyone have experience with using openblas with openmp, and if there are any performance issues?

**Comment by ViralBShah** [comment]
Also, as per the OpenBLAS FAQ, starting 0.3.7, we should be using `USE_LOCKING=1` if we multiple threads call OpenBLAS. I don't think we are doing that.

**Comment by ViralBShah** [comment]
@giordano @staticfloat FYI.

**Comment by ViralBShah** [comment]
This is a bit of a tangent, but I was looking into BLIS.

BLIS is safe with multi-threading: https://github.com/flame/blis/blob/master/docs/Multithreading.md

Also, these appear 6 months old, but does BLIS outperform OpenBLAS? Anyone here with experience?
https://github.com/flame/blis/blob/master/docs/Performance.md

**Comment by ViralBShah** [comment]
Closing as dup of #32786 (sort of)

**Comment by chriscoey** [comment]
@ViralBShah are you aware of any attempts at using BLIS from Julia? The progress on https://github.com/JuliaLang/julia/issues/32786 seems slow so I'm wondering if Julia needs to look at more alternatives for multithreading and linear algebra

**Comment by ViralBShah** [comment]
There was an effort a while ago. I should note that it should be straightforward, because BLIS offers a BLAS-compatible API. 

The other alterative is to only use the low-level kernels, and build the multi-threaded BLAS and LAPACK in Julia itself. It is not too hard to do such a thing nowadays, but it needs a concerted community effort in that direction.

**Comment by ViralBShah** [comment]
@chriscoey @YingboMa and others have explored the possibility of a Julia-native BLAS.
