### ISSUE TITLE
Use of python in the build system

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#35662]
Is `contrib/normalize_triplet.py` the only python-based build dependency for building Julia when using BB binaries? If so, maybe we can replace it. If we use python in other places, the it doesn't really matter.

**Comment by StefanKarpinski** [comment]
cc @staticfloat

**Comment by fredrikekre** [comment]
#35193 adds a couple of thousand lines of python too, so I think it is needed.

**Comment by staticfloat** [comment]
Yeah, we're using python more and more because we're doing more and more complicated things inside of the build system.
