### ISSUE TITLE
make register_error_hint experimental

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#35671]
In discussing https://github.com/JuliaLang/julia/pull/35094 on this last triage call before the 1.5 feature freeze, it was felt that this should be an experimental feature for a while. The concern is that the current form may have bad consequences for compilation time and that it may need changing if that turns out to be the case. There are two things to be done:

1. export the new exports from the `Experimental` submodule instead of directly from `Base`
2. document that it is experimental.

**Comment by timholy** [comment]
I did not export them at all from Experimental, is that OK?
