### ISSUE TITLE
Adding `@info` line removes error

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#35682]
In trying to debug a MakieLayout issue (https://github.com/jkrumbiegel/MakieLayout.jl/issues/69), I `@eval`'d in an extra logging line and the error went away. This seemed really odd, and I could reproduce it on 1.4 and master. I thought maybe the `@info` could change the inlining heuristics and somehow that could cause the bug to appear or not, but adding `@noinline` did not change things.

The code is as follows:

```julia
using MakieLayout, Makie, AbstractPlotting

# Modify the source to add `@info maxlen`
@eval AbstractPlotting begin
    function broadcast_foreach(f, args...)
        lengths = bs_length.(args)
        maxlen = maximum(lengths)
        # all non scalars should have same length
        if any(x-> !(x in (0, 1, maxlen)), lengths)
            error("All non scalars need same length, Found lengths for each argument: $lengths, $(typeof.(args))")
        end
        @info maxlen # This was added
        for i in 1:maxlen
            f(bs_getindex.(args, i)...)
        end
        return
    end
end

function mwe(series)
    scene, layout = layoutscene()
    axs = [LAxis(scene), LAxis(scene)]
    linkxaxes!(axs...)
    for i = 1:2
        ax = axs[i]
        ax.xticklabelsvisible = false
        lines!(ax, 1:length(series), series)
        layout[i, 1] = ax
    end

    scene
end

# s = rand(2)
s = [0.6735411040113073, 0.7751331011468388]

@info "When we log `maxlen`, it does not error"
mwe(s) # does not error
@info "Finished 1"


@eval AbstractPlotting begin
    function broadcast_foreach(f, args...)
        lengths = bs_length.(args)
        maxlen = maximum(lengths)
        # all non scalars should have same length
        if any(x-> !(x in (0, 1, maxlen)), lengths)
            error("All non scalars need same length, Found lengths for each argument: $lengths, $(typeof.(args))")
        end
        # Now we comment out the logging
        # @info maxlen 
        for i in 1:maxlen
            f(bs_getindex.(args, i)...)
        end
        return
    end
end

@info "When we don't log `maxlen`, it errors!"

mwe(s) # error

@info "Finished 2"
```

I've created a gist with this code and a Project and Manifest to help reproduce it: https://gist.github.com/ericphanson/2471832c9875bfd29469a6de13eff8c0. I imagine it would be a lot nicer to show the bug without package dependencies but I'm not really sure how to isolate it (the `mwe` function was supposed to be minimal for tracking down the original MakieLayout bug, not minimal for the `@info` Julia bug).

**Comment by fredrikekre** [comment]
Maybe try with `julia --inline=no`?

**Comment by ericphanson** [comment]
I get the same behavior with `--inline=no`.

**Comment by ericphanson** [comment]
It [sounds like](https://github.com/jkrumbiegel/MakieLayout.jl/issues/69#issuecomment-624247255) this is a race condition between async code and blocking on io allows other code to run in time which prevents in the error. So not a Julia issue.
