### ISSUE TITLE
Reducing estimated cost of `not_int` to zero for more reasonable inlining

### ISSUE THREAD

**Issue by kimikage** [JuliaLang/julia#35697]
Surprisingly(?), there is a non-trivial difference between the two functions below:
```julia
f(x) = x == zero(x) ? "zero" : "non-zero"

g(x) = x != zero(x) ? "non-zero" : "zero"
```
The estimated cost of `g(x::Int)` is 1 higher than `f(x::Int)` due to the extra `Base.not_int`.
https://github.com/JuliaLang/julia/blob/f2fa6cf665ce078cd46f8ce0d139bf6b644884ad/base/compiler/tfuncs.jl#L146

Although you might think the difference is trivial, this can cause speed differences of ~10 times depending on the SIMD vectorization. (For example, https://github.com/JuliaGraphics/Colors.jl/pull/407)

As you know, the cost model of inlining has room for improvement, and the modeling is "extremely" difficult. However my suggestion is just to change one character on the line shown above.

I think we seldom use `Base.not_int(::Int64)`, and often use `Base.not_int(::Bool)`. It is usually required in conditional expressions, and in most CPU instruction sets there are instructions or special operands for negative conditions (e.g. "not equal", "not less than"). Therefore, IMO, the cost `0` is reasonable.

**Comment by StefanKarpinski** [comment]
Makes sense: negating a condition basically never increases the instruction count.
