### ISSUE TITLE
Markdown: interpolate `Markdown.Link` url

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#35694]
Feature request!

You can interpolate a string for the `text` field, but not for the `url` field of a `Markdown.Link`:
```julia
julia> using Markdown

julia> a, b = "👋", "julialang.org";

julia> md"Go to [$a]($b)".content[1]
Markdown.Paragraph(Any["Go to ", Markdown.Link(Any["👋"], "\$b")])

julia> Markdown.parse("Go to [$a]($b)").content[1]
Markdown.Paragraph(Any["Go to ", Markdown.Link(Any["👋"], "julialang.org")])
```

The same problem with `url` and `alt` fields for images, and some others. Looking at the [source code](https://github.com/JuliaLang/julia/blob/c44644442949238da70670b547312ca1ae9a9c7d/stdlib/Markdown/src/Common/inline.jl), the different treatment makes sense - these fields are `String`s, and not `MD` trees, hence this is a _feature request_. It seems more consistent to interpolate, and err when the result is not a string.

**Comment by fredrikekre** [comment]
#16194

**Comment by fonsp** [comment]
Whoops, thank you!
