### ISSUE TITLE
`readdlm` has no option to read specific columns from file

### ISSUE THREAD

**Issue by HTofi** [JuliaLang/julia#35701]
Hi,

This is a feature request concerning the `DelimitedFiles.readdlm` function. I would like to have an option to specify the columns to read in a file, in a similar way to `numpy.loadtxt` in Python. For example:
`julia> x, y = readdlm("data.txt", columns=(1, 4), unpack=true)`.

In my opinion, this is a very useful option that one uses often times when reading data.

Thank you.

**Comment by quinnj** [comment]
You should check out the CSV.jl package for more generalized and feature-rich file reading; in particular, it supports selecting/dropping specific columns when reading: https://juliadata.github.io/CSV.jl/stable/#Select/Drop-Columns-From-File-1
