### ISSUE TITLE
SIGINT un-catchable without an I/O?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#35713]
Suppose I have `script.jl`

```julia
Base.exit_on_sigint(false)
c = Channel()
try
    println("Hit Ctrl-C")  # commenting this out makes InterruptException un-catchable
    take!(c)
catch err
    @show err
end
```

This works as expected:

```console
$ julia-dev --startup-file=no script.jl
Hit Ctrl-C
^Cerr = InterruptException()
```

But if I comment out `println`, I can't catch `InterruptException`:

```console
$ julia-dev --startup-file=no script.jl
^C^Cfatal: error thrown and no exception handler available.
InterruptException()
jl_mutex_unlock at /home/takafumi/repos/watch/julia/src/locks.h:143 [inlined]
jl_task_get_next at /home/takafumi/repos/watch/julia/src/partr.c:476
poptask at ./task.jl:706
wait at ./task.jl:714 [inlined]
task_done_hook at ./task.jl:444
jl_apply at /home/takafumi/repos/watch/julia/src/julia.h:1692 [inlined]
jl_finish_task at /home/takafumi/repos/watch/julia/src/task.c:198
start_task at /home/takafumi/repos/watch/julia/src/task.c:717
unknown function (ip: (nil))
```

I checked it with 8ab87d2205559b783b461bc90078826f7fb022c1

**Comment by tkf** [comment]
Sometimes, SIGINT is not catchable even with some I/Os: https://github.com/JuliaLang/BugReporting.jl/pull/13

**Comment by JeffBezanson** [comment]
I believe this is the same as #25790. What's happening is that the interrupt exception is thrown to whichever task last blocked. So it's not the I/O itself that makes the difference, just that the I/O changes the task order. In this case, without the I/O the last task to block is ... the `gc_msgs_task` in Distributed.

**Comment by tkf** [comment]
Thanks, it makes sense that I/O itself is not the factor here. Closing as a dup.
