### ISSUE TITLE
range(0, length=Uint(0)) throws InexactError

### ISSUE THREAD

**Issue by ethomag** [JuliaLang/julia#35711]
```julia
julia> range(0, length=UInt(0))
ERROR: InexactError: check_top_bit(Int64, 18446744073709551615)
```
Due to the fact that empty ranges are represented by n:n-1, which breaks with n=0 and unsigned types.

I think the `range` expression is a valid one that ought to be supported and the error message is not very helpful.

Could not find anything related on discourse, the closest one is:
https://github.com/JuliaLang/julia/issues/26608

**Comment by Micket** [comment]
So, problem seems to stem from promotion of Int -> UInt (which then underflows) on
https://github.com/JuliaLang/julia/blob/master/base/range.jl#L107

Possible fix
```julia
_range(a::Real, ::Nothing, ::Nothing, len::Integer) = UnitRange{typeof(a)}(a, a+oftype(a, len)-1)
```

**Comment by mbauman** [comment]
This is strongly related to #10554; we should figure out a way to do the promotion that solves both cases (the MWE for that one is now `range(1,length=typemax(Int128))`).

**Comment by Micket** [comment]
At least `range(1,length=typemax(Int128))` throws an error.
There are cases which are just kinda silently "broken"
```julia
julia> range(UInt(0),length=0)
0x0000000000000000:0xffffffffffffffff
```
```julia
julia> range(2,length=typemax(Int64))
2:1
```
Though, surely there is some responsibility of the caller to ensure the datatypes used don't overflow/underflow (unless
