### ISSUE TITLE
DelimitedFiles readdlm is externally slow for Complex{Float64} 

### ISSUE THREAD

**Issue by yzcj105** [JuliaLang/julia#35721]
```
 using DelimitedFiles
A = randn(Complex{Float64},300,30)
B = randn(Float64,300,30)
writedlm("A.csv",A,',')
writedlm("B.csv",B,',')
 @time readdlm("A.csv",',',Complex{Float64},'\n')
 10.645386 seconds (67.52 k allocations: 3.250 GiB, 2.68% gc time)
@time readdlm("B.csv",',',Float64,'\n')
  0.005304 seconds (18.00 k allocations: 878.875 KiB)
``` 
The readdlm for Complex{Float64} is much much slower and memory requiring compared to real numbers.  
I've also compared the time consuming of pandas.read_csv in python,  pandas is very fast every for complex numbers.

**Comment by yzcj105** [comment]
For Complex 300*300 matrix, the result has never come out after waiting for minutes.

**Comment by yzcj105** [comment]
alternative ways to read complex matrix from csv files
A is 300*300 matrix.
```
julia> @time df = CSV.read("A.csv";header=0,delim=',')
  0.006457 seconds (22.12 k allocations: 3.413 MiB)
# return 300×300 DataFrames.DataFrame. Omitted printing of 298 columns
....
....
 A = convert(Matrix,df) .|> x->parse(Complex{Float64},x)
# return. 300×300 Array{Complex{Float64},2}:
```
Which is much much faster compared to readdlm

**Comment by stevengj** [comment]
Should be fixed by #35742.

**Comment by yzcj105** [comment]
Thank you!

**Comment by KristofferC** [comment]
Let's not close until that merges (it will close automatically)
