### ISSUE TITLE
Would it be possible to remove the space in the name of the DEV Julia?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#35720]
On Windows C:\Users\PKrysl\AppData\Local\Programs\Julia 1.5.0-DEV\bin 
is not as convenient as
C:\Users\PKrysl\AppData\Local\Programs\Julia-1.5.0-DEV\bin
In other words, no spaces is in the path. Would that be possible?

**Comment by musm** [comment]
It's possible, but I wonder why it's more convenient?

**Comment by PetrKryslUCSD** [comment]
Because some editors require some hoops to be jumped through  in order for configuration of paths to include spaces.

In general I think it would be better to be consistent between regular versions of Julia in the development version. The regular versions do not have spaces in the paths.

**Comment by musm** [comment]
> The regular versions do not have spaces in the paths.

Strange, for some reason I thought none of them had spaces. Will look into it.

**Comment by musm** [comment]
I now remember, I'm pretty sure I changed this to always include a space for consistency.
I'm pretty sure when 1.5 is released  it will be called
`Julia 1.5` and the dev version `Julia 1.5-dev`

**Comment by PetrKryslUCSD** [comment]
On my system
![image](https://user-images.githubusercontent.com/9855832/80983210-3126b600-8de1-11ea-8185-e45be6eb9bcf.png)
![image](https://user-images.githubusercontent.com/9855832/80983258-3b48b480-8de1-11ea-895a-b8ce17297c00.png)

**Comment by musm** [comment]
That's my point, we changes this after 1.4 to always use a space instead of a dash.

**Comment by musm** [comment]
We removed the extra `Julia` folder and all the Julia versions are held in the master folder.

---

We don't want to change this to use a 'dash'. It should just be `Julia VERSION` and that's the folder name. As is done for e.g. Sublime Text 3 and other software (like MiKTeX 2.9). That is until we have an 'auto-update' mechanism that can update things in place. 

> Because some editors require some hoops to be jumped through in order for configuration of paths to include spaces.

Not really, just need to escape things correctly as you always have to do when you have spaces.

**Comment by PetrKryslUCSD** [comment]
I see. Thanks for looking into it. Even though in my opinion it is more intuitive to have paths without spaces in them.

**Comment by musm** [comment]
It does make it easier when the paths don't have spaces, but that can hide bugs because it's possible to have user names with spaces, in which case %APPDATA% needs to be properly escaped.

**Comment by PetrKryslUCSD** [comment]
Case in point: in Sublime Text 3 I have the following configuration
![image](https://user-images.githubusercontent.com/9855832/80984028-2e789080-8de2-11ea-8efd-f8a8ea6a1dc5.png)
The nightly Julia command is incorrectly interpreted as
![image](https://user-images.githubusercontent.com/9855832/80984083-418b6080-8de2-11ea-85d7-6a491688c255.png)

**Comment by musm** [comment]
That's because `shell_cmd` hasn't properly escaped the Julia path.
It should be
```
"shell_cmd": "\"%LOCALAPPDATA%\\Programs\\Julia 1.5.0-DEV\\bin\\julia.exe\""
```

Again, this is a common thing in Windows, you always have to properly escape paths because of spaces.

**Comment by musm** [comment]
Closing since there isn't anything we should change here. Hope the above change worked for you!

**Comment by fredrikekre** [comment]
Personally I think `Julia-1.5` is better than `Julia 1.5` though.

**Comment by PetrKryslUCSD** [comment]
No, that does NOT work.
Petr Krysl

**Comment by musm** [comment]
Can you double check, because I tested it on Sublime Text 3 and Terminus and it works correctly after enclosing things in quotes as in:
```
"shell_cmd":  "\"THE PATH NAME\""
```

note this type of escaping we also have to do in in VS Code and I also had to do it when I point Sumatra pdf to sublime text for inverse search because it's path also contains spaces.

**Comment by PetrKryslUCSD** [comment]
It is strange, but no, it does not work.

**Comment by musm** [comment]
What's the error? Have you updated Terminus?

**Comment by PetrKryslUCSD** [comment]
The error is
```
'C:\Users\PKrysl\AppData\Local/Programs/Julia' is not recognized as an internal or external command,                                                                                            
operable program or batch file.                                                                 
process is terminated with return code 1.
```
when setting
`"shell_cmd": "\"%LOCALAPPDATA%/Programs/Julia\\ 1.5.0-DEV/bin/julia.exe\"",`

**Comment by PetrKryslUCSD** [comment]
Perhaps it has something to do with running ST3 from a git bash?

**Comment by musm** [comment]
Change to
```
"shell_cmd": "\"%LOCALAPPDATA%\\Programs\\Julia 1.5.0-DEV\\bi\\julia.exe\"",

```

**Comment by PetrKryslUCSD** [comment]
Sorry, no go. I've tried that before as well.

**Comment by PetrKryslUCSD** [comment]
The magic was `"shell_cmd": "%LOCALAPPDATA%\\Programs\\\"Julia 1.5.0-DEV\"\\bin\\julia.exe",`.
See what I mean by having spaces being inconvenient? :(

**Comment by musm** [comment]
I see the `\"` prevents expansion of the env variable probably.

> See what I mean by having spaces being inconvenient?

You would have had the same problem with Python or any other program that includes a space between the version and the program name.

**Comment by fredrikekre** [comment]
Reopening because clearly the space is annoying. Whats wrong with a dash?

**Comment by musm** [comment]
@fredrikekre   It was an incorrect user configuration. Multiple other programs include a space between the version and the program name that reside in the same installation directory. 


Other instances where this would also have cropped up include: 

For example @PetrKryslUCSD  would have had the same program if his Windows username had a space in it.

**Comment by PetrKryslUCSD** [comment]
Possible. But should not user convenience trump aesthetics considerations? NOT including a space would make things EASIER for users. (Of course, there might be those who need to mess with the escaping  because of a poor choice  in some other name, such as the username.) But if you can make a positive difference, why not?

**Comment by musm** [comment]
I see where you are coming from, but I would respectfully disagree. 

With the same train of thought should I file a bug with Microsoft VS Code because they do the same
![image](https://user-images.githubusercontent.com/4319522/80997860-fa1bc900-8e0f-11ea-8399-06faad3af0ea.png)
or Sublime Text 3
![image](https://user-images.githubusercontent.com/4319522/80997918-13247a00-8e10-11ea-9310-17eb4ff64fce.png)

The reality is that spaces are valid. Another points include  that it probably  assists in search indexing to have the space and it also guard against incorrect configurations/invocations.

**Comment by musm** [comment]
In any case:
My longer term goal is to think about an auto-update mechanism for the `Julia` installer, which would eliminate this 'problem', since we would simply call the folder `Julia`.

**Comment by PetrKryslUCSD** [comment]
These are valid arguments. Anyhow, thank you for trying to help me. :)

**Comment by musm** [comment]
> These are valid arguments. Anyhow, thank you for trying to help me. :)

No problem. Glad we figured it out!

**Comment by musm** [comment]
@fredrikekre Do you think we could close this now? Main issue is resolved, and hopefully I provided enough motivation and rationale that this isn't really a "bug"

**Comment by musm** [comment]
Ok opened a PR to close this issue out https://github.com/JuliaLang/julia/pull/36693

**Comment by PetrKryslUCSD** [comment]
Super!
