### ISSUE TITLE
docs site search does not find "punctuation"

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#35724]
The docs site search functionality at does not find the punctuation page (https://docs.julialang.org/en/latest/base/punctuation/) when searching for "punctuation" (https://docs.julialang.org/en/latest/search/?q=punctuation).

*(I could not find an existing issue, and I am not totally sure this is the best place to report it, but the [docs repo](https://github.com/JuliaLang/docs.julialang.org) has issues disabled.)*

**Comment by fredrikekre** [comment]
Probably Documenters fault somehow, @mortenpi?

**Comment by mortenpi** [comment]
Yep, almost certainly. Something must be going wrong with the way we're using lunr, but not sure what's going on. The page is definitely in the index (e.g. if you search "exclamation"). Would need someone to dig into the JS (specifically `assets/search.js`) to debug this.

**Comment by visr** [comment]
Will be fixed in https://github.com/JuliaDocs/Documenter.jl/pull/1311.

It was using the stemmer to normalize `punctuation` to `punctuat`, and then it was more than the max edit distance of 2 removed from the correct title :)
