### ISSUE TITLE
FIXME: Invalid matmul code

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#35731]
I found this comment in the matrix multiplication implementation while debugging some code:

https://github.com/JuliaLang/julia/blob/3df889910690a81552d069967c87e945d8d2b7c7/stdlib/LinearAlgebra/src/matmul.jl#L753

I don't know if this is wrong but that comment is scary. Why is it there?

**Comment by Liozou** [comment]
Dup of https://github.com/JuliaLang/julia/issues/26008?

**Comment by mbauman** [comment]
Yeah, this is from https://github.com/JuliaLang/julia/pull/23914 and well-tracked in #26008; it's a misuse of `unsafe_wrap` that is theoretically problematic.
