### ISSUE TITLE
Inconsistent matrix sizes using diagm() and spdiagm()

### ISSUE THREAD

**Issue by rafreeman** [JuliaLang/julia#35776]
If you use `diagm` with index/vector pairs to create a matrix and do not specify a size, then the matrix will be square and at least as big as the absolute value of largest diagonal index you provide.  The same is not true for `spdiagm`:

```julia
julia> using LinearAlgebra, SparseArrays

julia> diagm(1 => ones(0))
1×1 Array{Float64,2}:
 0.0

julia> spdiagm(1 => ones(0))
0×0 SparseMatrixCSC{Float64,Int64} with 0 stored entries
```
The documentation does not specify which of these behaviors is correct, only that `its size is inferred from kv`.  I prefer the behavior of `diagm` because
```julia
julia> [size(diagm(1 => zeros(n))) for n=0:3]
4-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 2)
 (3, 3)
 (4, 4)
```
seems more correct than
```julia
julia> [size(spdiagm(1 => zeros(n))) for n=0:3]
4-element Array{Tuple{Int64,Int64},1}:
 (0, 0)
 (2, 2)
 (3, 3)
 (4, 4)
```
In any case, I believe the behavior should be consistent between `diagm` and `spdiagm`.

```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 6
```

**Comment by laborg** [comment]
I couldn't find a specific PR that fixed this but on 1.7.1 and on master this works as expected:
```julia
julia> diagm(1 => ones(0))
1×1 Matrix{Float64}:
 0.0

julia> spdiagm(1 => ones(0))
1×1 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅ 
```
