### ISSUE TITLE
nthread limit when running in taskset/cpuset

### ISSUE THREAD

**Issue by sgaure** [JuliaLang/julia#35787]
The number of threads available for multiprocessing is capped by the number of cpus. This, I believe, is done to avoid running more threads than cpus.  However, when the process has access to fewer cpus because of bindings in the OS (via taskset/cpuset/numactl on linux. I suppose similar mechanisms are available in other OSs), the nthread-cap is still the number of cpus in the computer.

For consistency, the actual limit should be honored:
Here is an example on a 16-cpu linux machine:

```
$ julia -t 24 -E 'Threads.nthreads()'
16
$ taskset -c 0-3 julia -t 24 -E 'Threads.nthreads()'
16
```
To be consistent the last command should output 4.

Certain batch-systems will only give the user the number of cpus asked for, and if the user script tells julia to use more there will be contention in julia.

This could also be combined with allowing `all` as a thread-specification, meaning all cpus you can get hold of, to yield something like this:
```
$ taskset -c 0-3 julia -t all -E 'Threads.nthreads()'
4
```

Even if I can't come up with a good example, I might possibly imagine cases where you actually want more threads than cpus, so there should perhaps be a way to override the automatic cap (`-T` in place of `-t`?).

**Comment by JeffBezanson** [comment]
What's the right call to determine this --- `sched_getaffinity`? Seems like a good idea.

**Comment by sgaure** [comment]
Yes, it is `sched_getaffinity`, and it is a bit messy for large systems, which is precisely where this kind of functionality is likely to be used.

**Comment by Keno** [comment]
`sched_getaffinity` is advisory. To get mandatory limits you need to parse the active cgroup. That said, we should probably respect `sched_getaffinity` here.

**Comment by tkf** [comment]
Yeah, it'd be nice to parse cgroup. IIUC it's what libuv does for other CPU things in Linux.

Related issues: https://github.com/JuliaLang/julia/issues/33409, https://github.com/JuliaLang/julia/issues/13901

**Comment by sgaure** [comment]
Perhaps one should have an option for restricting the individual threads to a single cpu to avoid cache misses due to cpu migration? This is nice for cpu bound work on an otherwise idle system, or one with some spare cpus. It can, however, stall a thread if there is other activity on the machine which is not tucked away in a disjoint cpuset, depending on the kernel's thread scheduler.

**Comment by JeffBezanson** [comment]
We have that via the `JULIA_EXCLUSIVE` environment variable.

**Comment by bartoldeman** [comment]
Looking at the source code Julia's max number of threads is obtained via `sysconf(SC_NPROCESSORS_ONLN)`
https://github.com/JuliaLang/julia/blob/95c023b58aa5d5331d2e07829485311dff600042/src/sys.c#L377

If you look at libgomp (GCC OpenMP implementation) it also looks at
https://linux.die.net/man/3/pthread_getaffinity_np
see
https://gcc.gnu.org/git?p=gcc.git;a=blob;f=libgomp/config/linux/proc.c;h=d7b65d93609ebb16c9be2e9a2431a14762afdb24;hb=HEAD#l155
to determine the default number of threads (ie. if you do not set `OMP_NUM_THREADS` explicitly)

It will still use the same sysconf call as a fallback if `pthread_getaffinity_np` is not available.

So in principle that code from libgomp could be ported to Julia?
