### ISSUE TITLE
Feature request: Multithreaded sparse matrix vector product

### ISSUE THREAD

**Issue by lesshaste** [JuliaLang/julia#35798]
I have a large sparse matrix which I need to multiply with dense vectors.  The types of the elements in the vectors are UInt256 and UInt8 in the matrix.  Currently each product takes about 45 seconds using SparseArrays.  

It would be great if this could be sped up using multithreading.  As far as I can see no such library exists currently.

**Comment by jebej** [comment]
#29525

**Comment by lesshaste** [comment]
That PR seems to have become stuck sadly. Is there any way to unstick it?

**Comment by ViralBShah** [comment]
Closing in favour of #29525.
