### ISSUE TITLE
Compile MPFR and GMP to be thread safe

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#35796]
This issue stems from [issue #10040](https://github.com/JuliaLang/julia/issues/10040#issuecomment-625551668).

MPFR has a configuration option `--enable-thread-safe` that we should use by default.

MPFR has a configuration option`--enable-gmp-internals` that we should use iff library versioning works (or is irrelevant) for our binaries:

> --enable-gmp-internals  allows the MPFR build to use GMP's undocumented
functions (not from the public API). Note that library versioning is not guaranteed to work if this option is used. Thus it must not be used in binary distributions.

**Comment by ViralBShah** [comment]
@giordano @staticfloat Do you know what this means? Since we distribute all of these ourselves, it seems we can carefully compile for higher performance.

**Comment by giordano** [comment]
To be honest, I'm not sure what they mean by "library versioning" in this context, but I agree that since we have control over both GMP and MPFR, we might be able to compile with this flag, if it doesn't break anything.

**Comment by JeffreySarnoff** [comment]
> MPFR internal data such as flags, the exponent range, the default precision and rounding mode, and caches (i.e., data that are not accessed via parameters) are either global (if MPFR has not been compiled as thread safe) or per-thread (thread local storage, TLS).

With this change we would also want to rework handling BigFloat precisions so that the precision of the arg[s] determines the precision of the result unless that is precision is explicitly supplanted. We would also want to have much easier local (at the op level) control of rounding.  [How to handle the precision of BigFloats](https://github.com/JuliaLang/julia/issues/10040)

**Comment by ViralBShah** [comment]
@JeffreySarnoff Is the precision related to how MPFR is compiled, or how the Julia wrappers call it and use it. If it is the latter, we should open a separate issue for it. Getting it compiled thread-safe will happen fairly quickly, and I'd like to get it into 1.5.

**Comment by ViralBShah** [comment]
Hopefully fixing this will fix https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/376

**Comment by ViralBShah** [comment]
For someone familiar with BinaryBuilder, this should be an easy issue to contribute to.

**Comment by ViralBShah** [comment]
Should probably also ensure that GMP is compiled to be thread safe. 

https://gmplib.org/manual/Reentrancy.html

**Comment by staticfloat** [comment]
WRT to `--enable-gmp-internals`, I think we would need to start providing much more precise version bounds on `MPFR`.  Then it should be safe.
