### ISSUE TITLE
assertion failure in codegen with union of singletons

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#35793]
```
julia> struct X
       x::Union{Nothing,Missing}
       end

julia> X(nothing)
julia: /home/jeff/src/julia/src/cgutils.cpp:705: llvm::Type* _julia_struct_to_llvm(jl_codegen_params_t*, jl_value_t*, jl_unionall_t*, bool*, bool): Assertion `NumATy > 0' failed.
```

The assertion is new in 1.5. It looks to me like the assertion can possibly just be removed, but I'm not sure. cc @vtjnash

**Comment by vtjnash** [comment]
Yeah, it should be fixed, or just removed. It's trying to express that if `al > 1`, we need to emit at least one copy of `AlignmentType` for the logic there to be correct.
