### ISSUE TITLE
rm(path, force=true): try chmod if necessary?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#35805]
There's a number of situations where `rm(path, recursive=true)` can fail if the path or something inside of it is not writable by the user. When the user owns the files, this can be fixed by modifying the permissions first and then removing the files. It's possible that the lack of write bit is intentional to prevent just this sort of thing, or it could be, say because you've extracted a tarball with those permissions and you just want to delete it. When the `force=true` flag is passed, it seems reasonable to me to change the permissions first if necessary in order to delete the path.

cc @staticfloat

**Comment by jpsamaroo** [comment]
Maybe a new flag, like `hardforce=true`, could be used to differentiate between current behavior and the proposed (rather risky) behavior?

**Comment by StefanKarpinski** [comment]
The `rm` commands `-f | --force` option has the same effect, and I think mirroring that makes sense.

**Comment by laborg** [comment]
According to some quick tests setting various permission this should now be the case with https://github.com/JuliaLang/julia/pull/39906
