### ISSUE TITLE
Cache rejected, but the file is the same

### ISSUE THREAD

**Issue by nico202** [JuliaLang/julia#35811]
https://github.com/JuliaLang/julia/blob/84d7e67aa82f3a3348a84a5a5659e03e2ebd6bcf/base/loading.jl#L1465

Should this run realpath() ? In systems like Guix&NixOS where profiles are created with symlinks, this check assume the files are different

Can I submit a PR for this? Do you think there's a better place where the path is normalized?

Thanks

**Comment by vtjnash** [comment]
`samefile` is a vastly more efficient and accurate way to normalize a path (Indeed, it's part of the underlying libc implementation of realpath, iirc). What issue are you seeing?

**Comment by nico202** [comment]
@vtjnash Thanks, didn't know of samefile, that's exactly what's needed.

Long story short: Guix keeps all program data under folder: /gnu/store/hash-program-version/, for example:
```
ls /gnu/store/y3v6dx107xpk3p209vvzjr2xg47abmlw-julia-1.4.1/
bin/  etc/  include/  lib/  libexec/  share/
```

Then, it creates "profiles" (folders) with installed programs symlinked to it:
which julia -> /home/nixo/.guix-profile/bin/julia
realpath $(which julia) -> /gnu/store/y3v6dx107xpk3p209vvzjr2xg47abmlw-julia-1.4.1/bin/julia

The same happens for julia packages.  When the precompile cache is created, the path used is the absolute one.  Then, when you create a profile, julia thinks the precompile cache is stale, as it's refer to the absolute path, while the symlink is loaded: the cache is invalidated and built again.

I'll try with samefile

**Comment by nico202** [comment]
Sorry for the noise, I made a big mess. I didn't realize a patch wasn't applied, run the loading manually and passed the folder in stead of the ji file.
Thanks again
