### ISSUE TITLE
Float rounding issue

### ISSUE THREAD

**Issue by plashchynski** [JuliaLang/julia#35810]
The expression
```
(2/6)^5 == 2^5 / 6^5
```
is false? This language is intended to be good at Math. Ruby and Python both evaluated it to true.

version 1.4.1

**Comment by StefanKarpinski** [comment]
Standard floating-point behavior. Python3:
```
>>> (2/6)**5
0.004115226337448558
>>> 2**5 / 6**5
0.00411522633744856
>>>
```
In both Python2 and Ruby 2/6 == 0 because this is integer division.

**Comment by simonbyrne** [comment]
Use rationals:
```
julia> (2//6)^5 == 2^5 // 6^5
true
```
