### ISSUE TITLE
Deterministic memory management

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#35815]
For performance-critical and real-time applications such as Control Systems, Robotics, Automotive, Audio VST, etc, having a deterministic memory management approach is necessary. 

I want to propose an optional memory management feature that works without garbage collection. This should be an **optional** feature that is added on top of the current behavior and should be fully backward compatible.

_This is just an initial idea, so let me know your suggestions._ 

# Named Scope:

`@let(scope_name, definition)` and `@scope(scope_name, code)`: 

The variables defined using this type should only exist in that scope. For example,
```jl
function fun()

	# this keeps x in the memory only inside the :Foo scope:

	x = @let :Foo rand(3)  	
	return x
end

function main()
	
    @scope :Foo begin
		xout = fun()
    end
    # xout will be deleted once the :Foo scope is finished

end
```

# Local variables:
When the scope is not specified in `@let`, it should be considered as `local` and should be removed once the function is executed.
```jl
function fun()

	# this keeps x in the memory only inside the `fun` function
	x = @let rand(3)   	
	
	return nothing
end
```
These local variables should not be returned (or leak will happen unless `@delete`d manually).

# Global variables:
Variables that are defined using `global` should be deleted manually by the user.

```jl
function fun()
	global x = rand(3) 	
	return x
end

xout = fun()
@delete xout
```

Garbage collection can help in all of these cases unless disabled by the user.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/7721?

**Comment by aminya** [comment]
> Dup of #7721?

That doesn't seem to offer a syntax/solution.

**Comment by KristofferC** [comment]
There are many syntax suggestions there. The `!` after function call, the `defer` keyword, using a macro etc. You could add yours there perhaps.

**Comment by aminya** [comment]
Sure. I can do that.
