### ISSUE TITLE
Option -p scales badly and adds a lot of time to startup

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#35830]
On my machine -p100 add 100 sec. to startup, and even -p1 adds time (a low-hanging fruit to fix, while most wouldn't use that, some scripts?).

See how it affect: https://discourse.julialang.org/t/benchmarks-game/38544/9?u=palli

**Comment by mbauman** [comment]
I wouldn't expect `-p100` to "scale well" on a system with significantly fewer than 100 cores (as I'm guessing you're using).

**Comment by JeffBezanson** [comment]
I believe we recently discovered some `sleep` calls that make adding processors much slower than necessary.

**Comment by PallHaraldsson** [comment]
@mbauman, it scales badly up to 16, and to clarify, yes, I shouldn't be doing this on a 16 (virtual) CPU machine, but still the time--for an empty program--seems excessive:

```
$ time ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O3 --cpu-target=core2 -p160 -e ""

real	0m28,772s
user	5m51,637s
sys	0m20,771s

$ time ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O3 --cpu-target=core2 -e ""

real	0m0,212s

$ time ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O3 --cpu-target=core2 -p16 -e ""

real	0m3,832s
user	0m36,614s

$ time ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia -O3 --cpu-target=core2 -p8 -e ""

real	0m2,698s
user	0m14,502s
```

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/35425.

**Comment by PallHaraldsson** [comment]
I doubt Jeff's "`sleep` calls" hypothesis, such should be as fast independent of optimization(?). It seems to be separate processes are opened of course, but to do so, code gets compiled in all of them (can't code be compiled only on master then distributed? at least this startup code, while maybe issues to do so in general?).
