### ISSUE TITLE
Style guide should not recommend rational numbers for literals

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#35858]
The style guide https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-using-floats-for-numeric-literals-in-generic-code-when-possible-1 recommends ("[...] use Int literals when possible, with Rational{Int} for literal non-integer numbers [...]") using rational numbers. This is dangerous.

Take this example:
```Julia
f(x) = (3/2)*x
```
When I replace the fraction `3/2` by a rational number `3//2`, then a call `f(1)` will return a rational number instead of a floating-point number. In (almost?) all cases, Julia converts from `Int` to `Float64` when a result is not integer (e.g. `/`, `sqrt`). Returning a rational number instead is much more expensive, and would certainly be unexpected.

Instead I would recommend
```Julia
f(x) = 3*one(x)/2*x
```
which works for both rational and floating-point numbers without losing precision, and defaults to returning `Float64` for integers as expected.

**Comment by kimikage** [comment]
Using `zero(x)`, `one(x)`, `oneunit(x)` is one useful technique, but I don't think it is the best practice "in that section". 

The issues with `Rational` literals are also mentioned in that section. I don't think the quote says to use `Rational{Int}`. I think the quote says that if you use `Float64` for literal non-integer numbers, using `Int` doesn't make sense.

**Comment by eschnett** [comment]
The full sentence is "Thus, use Int literals when possible, with Rational{Int} for literal non-integer numbers, in order to make it easier to use your code." This suggests to use rational numbers for non-integer literals such as 1/2, i.e. to use `1//2`.

Another sentence is "Rational literals are less type disruptive than Float64 literals". Whether that is true depends on the context. If I want to calculate with rationals, then it's true. When I want to do number crunching, then I can't have suddenly rationals pop up because that would kill efficiency. I don't see this fact mentioned in this section.

I think that using `one(x)` etc. is the only way for type-generic functions.

**Comment by kimikage** [comment]
> This suggests to use rational numbers for non-integer literals such as 1/2, i.e. to use `1//2`.

I don't think so. The sentence clearly says "use Int literals when possible".:confused:

Note that the section title is "Avoid using floats for numeric literals in generic code when possible".

**Comment by mbauman** [comment]
The fact that `base` code itself only uses `//` in three contexts is quite telling:

* documentation examples
* implementation of `Rational` itself
* `cbrt` is `x^(1//3)` <- this is perhaps the only instance of this in `base`

If we add in the stdlibs, Statistics.jl adds a another idiom in several places, which is interesting because the type of `A` was already computed but this still apparently behaves better (dates to #23285):

```
    b = 1//(size(x, vardim) - corrected)
    A .= A .* b
```

I think it could perhaps be weakened a bit, but I think the fact that rationals promote a little more equitably (and losslessly) to more more numeric datatypes is worth mentioning.

**Comment by eschnett** [comment]
@mbauman The general goal is to be type-stable with both floats and rationals, but convert integers to floats when a division occurs. The latter (using floats instead of rationals) is a choice Julia made, as witnessed by the return type of `1/2`.

The example you show above would behave strangely if `A` has element type `Int`. In this case, it would be converted to `Rational{Int}`, which (so I argue) is unexpected in Julia.

In case of the pull request you mention, the context (the expression `typeof(first(C) / 1)` above) ensures that this doesn't happen; the result type of this division is only a rational number if `first(C)` is a rational number. So that change is fine. But in general, rational numbers need to be avoided unless one has considered the consequences. Rationals are not a good default choice.

**Comment by mbauman** [comment]
> The general goal is to be type-stable with both floats and rationals, but convert integers to floats when a division occurs.

Is that the general goal?  I could similarly say using floating point numbers is dangerous because they might round to a lower precision than expected, or that using integers is dangerous because they use modular arithmetic.  Instead of 

```Julia
f(x) = 3*one(x)/2*x
```

I think I'd recommend

```julia
f(x) = 3x/2
```

My read on that section is that floating point _constants_ are more opinionated than you might want, and that rationals are _somewhat_ less opinionated.

**Comment by eschnett** [comment]
These two versions behave identically type-wise, but (without `@fastmath`) the second requires both a multiplication and a division at run time. The first version requires only a single multiplication. I don't know whether this is relevant for the style guide.

**Comment by mbauman** [comment]
Yes, and the second also overflows.  It gets into the nitty gritty real quick, with recommendations being very hard to make in the abstract.

**Comment by vtjnash** [comment]
Discussion seems to have stalled on whether any doc update should be made
