### ISSUE TITLE
Syntax highlighting for function names with certain unicode characters seems broken

### ISSUE THREAD

**Issue by janbruedigam** [JuliaLang/julia#35866]
Syntax highlighting for function names with a \partial symbol "∂" (and some other unicode characters) seems to be broken:
```julia
# broken:
function ∂f∂var() end # only var is highlighted 
function ∑vars() end # ∑ is not highlighted
function is⊥() end # nothing is highlighted

# works:
function ΔfΔvar() end
function δfδvar() end
function dfdvar() end
```
GitHub apparently also has some issues highlighting correctly, but for me using VS code and Julia 1.4 ```ΔfΔvar``` is highlighted correctly whereas ```∂f∂var``` is not. I had the same issue before when using Atom. 
Let me know if this is an editor issue, then I'll post the issue there.

**Comment by StefanKarpinski** [comment]
There's no syntax highlighting code in this repo—as you mention, this would have to be fixed in each editor. There is an org for https://github.com/JuliaEditorSupport and probably a few larger editor projects like VS Code might have their own orgs.
