### ISSUE TITLE
Feature Request: Block of comments

### ISSUE THREAD

**Issue by yordiak** [JuliaLang/julia#35864]
Hello,

It could be nice if we were able to use blocks of comments instead of inline comments. For instance, `GAMS` treats everything inside `onText...offText` as a comment. This feature will avoid  the extensive use of `#` at each line when you want to add a description of your  code.

**Comment by rfourquet** [comment]
Do you mean this?
```julia
f(x #= the variable =#) = #= block comment
   comment contined
=# 2*x
```

**Comment by yordiak** [comment]
@rfourquet yes exactly! I wasn't aware of this option
