### ISSUE TITLE
ImmutableDict doesn't have nice constructors

### ISSUE THREAD

**Issue by cmcaine** [JuliaLang/julia#35863]
Base.ImmutableDict is fast and useful, but it doesn't have nice constructors like `Dict`. If I open a PR adding some, is it likely to be accepted?

I'd write it with a for loop instead to be nice to iterables like `eachline`, but these are the constructors I'm thinking of:

```julia
using Base.Iterators: drop
import Base: ImmutableDict

ImmutableDict(pairs) =
    foldl(
          (acc, kv) -> ImmutableDict(acc, kv),
          drop(pairs, 1),
          init = ImmutableDict(first(pairs))
         )

ImmutableDict(pairs...) = ImmutableDict(pairs)
```

These still don't work with e.g. a tuple of 2-tuples, but it's still an improvement.

**Comment by simeonschaub** [comment]
See #34297. Should already work on master and the upcoming 1.5 RC

**Comment by cmcaine** [comment]
Woops, I must have only searched issues rather than PRs!

Thanks

**Comment by goerz** [comment]
https://github.com/JuliaLang/julia/pull/34297 added `ImmutableDict(pairs...)` but not `ImmutableDict{K,V}(pairs...)`. Is that an oversight, or something that's deliberate for some reason?

It's very unfortunate that there is no clear specification of what constitutes the `AbstractDict` interface, i.e., which constructors for an `AbstractDict` can be relied upon.

This came to bite us in https://github.com/JuliaCollections/Bijections.jl/issues/43
