### ISSUE TITLE
Missing tags in this repository

### ISSUE THREAD

**Issue by zdroid** [JuliaLang/julia#35865]
Currently listed tags:

julia-language
programming-language
scientific-computing
high-performance-computing
numerical-computation
machine-learning

1. Since https://github.com/topics/julia is more popular than julia-language, I think it should be added too.

2. Julia is missing some tags from popular topics (https://github.com/topics) that it is supposed to do very well. It's definitely missing https://github.com/topics/deep-learning, which can bring this repository a lot of views.

Maybe more tags can be added, but those two are a good start.

**Comment by StefanKarpinski** [comment]
I tweaked the tags a bit, using more highly suggested tags with similar meanings. I'm not so sure about tagging this with `deep-learning` or even `machine-learning`: there's nothing in this repo that's inherently about machine learning or deep learning and if anyone come here for those topics, it seems like they'd be a bit disappointed.

**Comment by KristofferC** [comment]
> I'm not so sure about tagging this with deep-learning or even machine-learning: there's nothing in this repo that's inherently about machine learning or deep learning

💯, the machine learning tag has always looked pretty weird to me. Feels like it is there purely for the AI hype.

**Comment by zdroid** [comment]
@StefanKarpinski Can you change `programming-languages` to `programming-language`? That's the tag other popular projects like Go and Kotlin use.

Hype or not, it's good marketing. Top [Julia repositories](https://github.com/search?q=stars%3A%3E100+language%3Ajulia) include high-quality machine/deep learning software. Julia is a very suitable language for the task, as you can write your own models even only with core libraries.

Someone who's disappointed in the current way machine/deep learning is done, i.e. the mesh of Python of C++, may find Julia very appeasing. I don't think this repository itself is ML or deep learning material, but the language has to be promoted somehow.

**Comment by zdroid** [comment]
@StefanKarpinski One more thing. `science` is more popular than `scientific`, so maybe change it too?
