### ISSUE TITLE
Use RandomDevice in UUIDs instead of default_rng?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#35860]
@c42f commented on https://github.com/JuliaLang/julia/pull/35833#discussion_r424052968

> Actually this would suggest that the global RNG from `Random` isn't a great choice for `UUIDs` anyway because the user may control the seeding for reasons unrelated to UUIDs.

Maybe we should use `Random.RandomDevice()` instead of `Random.default_rng()` in UUIDs?

See also https://github.com/JuliaLang/julia/issues/32954#issuecomment-526580532

**Comment by StefanKarpinski** [comment]
Yes, I think that's a good idea.

**Comment by c42f** [comment]
Thanks so much @tkf for boldly making coherent issues out of my random side remarks :sweat_smile:
