### ISSUE TITLE
spread rest

### ISSUE THREAD

**Issue by cindRoberta** [JuliaLang/julia#35892]
is it possible in Julia?

'''julia
a, b, c[3:4] = [1, 2, 3, 4];

#a= 1
#b= 2
#c= [3, 4]

**Comment by yuyichao** [comment]
That's valid syntax already so no.

```julia
julia> c = [1, 2, 3, 4]
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> a, b, c[3:4] = [1, 2, [3, 4]]
3-element Array{Any,1}:
 1
 2
  [3, 4]
```

Otherwise, dup of https://github.com/JuliaLang/julia/issues/2626.
