### ISSUE TITLE
Error in evaluating large numbers

### ISSUE THREAD

**Issue by HTofi** [JuliaLang/julia#35908]
It seems that my installation of Julia has a problem in interpreting large floats. For example, if I type Avogadro's number into the shell:

```
julia> 6.0221415 * 10^23
1.2066951576390968e18
``` 
You can see that the number returned is totally not the one I entered. However, things work correctly for smaller numbers:

```
julia> 1.0221415*10^14
1.0221415e14
```
Here is the version info:

```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_PKG_SERVER = pkg.julialang.org
```

**Comment by yuyichao** [comment]
Integer overflow.
