### ISSUE TITLE
Julia 1.4.1 suddenly won't start, with a "Invalid instruction" crash

### ISSUE THREAD

**Issue by zhopan77** [JuliaLang/julia#35912]
Windows 10 64-bit
Julia 1.4.1

I was using Julia regularly. Today, out of nowhere, when I try to start Julia in command line I got the following error message:

`zpan@RM-ZPAN1-LT C:\Users\zpan
$ julia

Invalid instruction at 000000000279669D: 0x3f, 0xe6, 0xff, 0xff, 0x84, 0xc0, 0x75, 0x2b, 0x48, 0x8b, 0x43, 0xe8, 0x48, 0x85, 0xc0

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x279669d -- _ZN4llvm12PatternMatch14BinaryOp_matchINS0_7bind_tyINS_5ValueEEENS1_IS4_NS0_11cst_pred_tyINS0_11is_all_onesEEELj29ELb1EEELj27ELb1EE5matchIS3_EEbPT_ at C:\Julia-1.4.1\bin\LLVM.dll (unknown line)
in expression starting at none:0
_ZN4llvm12PatternMatch14BinaryOp_matchINS0_7bind_tyINS_5ValueEEENS1_IS4_NS0_11cst_pred_tyINS0_11is_all_onesEEELj29ELb1EEELj27ELb1EE5matchIS3_EEbPT_ at C:\Julia-1.4.1\bin\LLVM.dll (unknown line)
unknown function (ip: 0000000000CAE84F)
Allocations: 2505 (Pool: 2494; Big: 11); GC: 0`

The only relevant thing I can think of is recently I updated Rust, which also uses LLVM. 

I will try rebooting and see if it can solve the problem.

**Comment by zhopan77** [comment]
OK after a reboot of the computer, Julia works again. 

Still it looks pretty scary when Julia crashed just like that. I'll keep this issue open for now. Thanks.

**Comment by jtappin** [comment]
I've seen a very similar issue on Linux (Manjaro):
````
$ julia
Invalid instruction at 0x7f63141ad9f8: 0x66, 0x0f, 0x3a, 0x0f, 0xc0, 0x08, 0x0f, 0x83, 0x61, 0x05, 0x00, 0x00, 0x48, 0xc1, 0xe0

signal (4): Illegal instruction
in expression starting at none:0
_ZN4llvm13LexicalScopes23assignInstructionRangesERNS_15SmallVectorImplISt4pairIPKNS_12MachineInstrES5_EEERNS_8DenseMapIS5_PNS_12LexicalScopeENS_12DenseMapInfoIS5_EENS_6detail12DenseMapPairIS5_SB_EEEE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
_ZN4llvm13LexicalScopes10initializeERKNS_15MachineFunctionE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
unknown function (ip: 0x7f63141c5e71)
_ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/julia/libLLVM-8jl.so (unknown line)
unknown function (ip: 0x7f6316d9912e)
unknown function (ip: 0x7f6316d9d665)
unknown function (ip: 0x7f6316d9de4a)
unknown function (ip: 0x7f6316ca3a0b)
unknown function (ip: 0x7f6316cf6eb3)
unknown function (ip: 0x7f6316d2147e)
jl_apply_generic at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f6309e2a942)
unknown function (ip: 0x7f6309e2b308)
unknown function (ip: 0x7f6316d2dea4)
jl_f__apply_latest at /usr/bin/../lib/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f6309d2d0df)
unknown function (ip: 0x7f6309d332d3)
unknown function (ip: 0x7f6309d337e2)
unknown function (ip: 0x7f6309d33925)
unknown function (ip: 0x560692a844fe)
unknown function (ip: 0x560692a840a7)
__libc_start_main at /usr/bin/../lib/libc.so.6 (unknown line)
unknown function (ip: 0x560692a8415d)
Allocations: 2504 (Pool: 2495; Big: 9); GC: 0
Illegal instruction (core dumped)
````
The package version is 1.4.1-2, but I also see the same (or very similar) error message during the build process if I try to build the current GIT from the AUR recipes.

**Comment by ViralBShah** [comment]
How old is the CPU?

**Comment by jtappin** [comment]
@ViralBShah  I'm not absolutely sure, about 8 years I think, from /proc/cpuinfo:
````
AMD Phenom(tm) II X6 1055T Processor
````

**Comment by ViralBShah** [comment]
@jtappin Your issue is #35215

**Comment by ViralBShah** [comment]
@zhopan77 Please reopen if this if you can reproduce.
