### ISSUE TITLE
Potential memory leakage in function definition using multiple threads in linux?

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaLang/julia#35918]
Please feel free to close if this is considered normal.(I posted it on discourse but didn't get a response)
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4

julia> @sync for i in 1:100
                  Threads.@spawn begin
                    function foo()
                      [fill(1.0, 2_00_000) for _ in 1:1000]
                      nothing
                    end
                    foo()
              end
              end
```
When i ran the above code which consumed 6.9G of ram (not the issue) after execution running `GC.gc()` multiple times only releases about (2.5G). I found a related github issue https://github.com/JuliaLang/julia/issues/30653 6 which appears to have been fixed. When ran with a single thread I can free up a significant portion of my memory. Is this a memory leak?

**Comment by JeffBezanson** [comment]
I'm able to run this repeatedly without memory use continuing to go up, so I suspect it's not a real leak but just a matter of when memory is released to the kernel. If you run it multiple times in the same session, does it reach a steady state?

**Comment by OkonSamuel** [comment]
@JeffBezanson. Thanks for taking the time to check this. I only have 8GB of Ram so i reduced the problem size.
```julia
@sync for i in 1:100
                  Threads.@spawn begin
                    function foo()
                      [fill(1.0, 2_0000) for _ in 1:1000]
                      nothing
                    end
                    foo()
              end
              end
```
Yes when this is ran multiple times the memory use reaches steady state in the same session so it may just be the kernel. My concern is that if i run something like `rand(10000000)` and call `GC.gc()` i get immediate memory collection so i guessed that should have happened here.
The real issue for me is after running the code above and i run `rand(10000000)` (this increases memory use further). Then if i call `GC` only the memory that was allocated when i called `rand` gets freed. Is this the norm??

**Comment by JeffBezanson** [comment]
Yes, I think so, because a single large allocation will be done by directly calling `mmap`, and freed by `munmap`. But smaller objects share mapped regions.

**Comment by OkonSamuel** [comment]
Okay. I just noticed i can free up everything by calling `malloc`. It seems this issue doesn't occur on windows. Thanks

**Comment by ViralBShah** [comment]
Should we close this?

**Comment by OkonSamuel** [comment]
I okay calling `malloc`. 
So you may close this for now if you wish to.
