### ISSUE TITLE
Both sizeof and Base.summarysize inaccurate for non-power of two width ints

### ISSUE THREAD

**Issue by lesshaste** [JuliaLang/julia#35920]
I am using https://github.com/rfourquet/BitIntegers.jl as follows.

```
using BitIntegers
BitIntegers.@define_integers 40
v = ones(UInt40, 10^6)
```

Now I do the following:

```
Base.summarysize(v) 
5000040
sizeof(v)
5000000
```

Both of these are wrong I believe as each 40-bit integer takes 64-bit of memory (i.e. one word). 

The correct answer should be 8000000 (plus whatever overheads).

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/35900?

**Comment by JeffBezanson** [comment]
Yes, dup of #35884.
