### ISSUE TITLE
contrib: purge & rename

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#35924]
The `contrib` directory is old and crufty. It was once where we put Julia packages before we had a package manager! Now it seems to contain a combination of bit-rotted unnecessary random files that we should delete and essential utilities for building Julia and/or binaries. We should get rid of all of the former and rename the directory to `utils` or something like that.

@staticfloat, I feel like a lot of the things in here are used by you, so perhaps you can look at this? Otherwise, I may write a script to try deleting each file and rebuilding Julia and if the build succeeds committing the deletion.

**Comment by vchuravy** [comment]
Doing a cursory check most of these files are used in the build process. 

### Actively used:
- `check-whitespace.sh`
- `commit-name.sh`
- `normalize_triplet.py`
- `refresh_bb_tarballs.sh`
- `generate_precompile.jl`
- `fixup-libstdc++.sh`
- `fixup-rpath.sh`
- `fixup-libgfortran.sh`
- `install.sh`
- `julia.appdata.xml`
- `julia-config.jl`
- `julia.desktop`
- `mac`
- `relative_path.py`
- `stringreplace`
- `windows`

### Used by mac/framework
- `delete-all-rpaths.sh`

### Release process
- `add_license_to_files.jl`
- `prepare_release.sh`

### Maybe unused?
- `debug_bootstap.gdb`
- `filterArgs.sh`
- `travis_fastfail.sh`
- `valgrind-julia.supp`

### Convenience
- `download_cmake.sh`

**Comment by ararslan** [comment]
FWIW I've never used `prepare_release.sh`.

**Comment by staticfloat** [comment]
We can get rid of `prepare_release.sh`, if Alex doesn't use it.  I believe that everything else in the `Maybe unused?` section can be deleted as well.

**Comment by ararslan** [comment]
`prepare_release.sh` might be useful if it were updated to reflect the current release process, it just isn't that useful as it stands.

**Comment by ViralBShah** [comment]
A lot of the cruft in `contrib` has been removed over time. What largely remains is stuff for building and releasing julia, so perhaps best to rename it `build` when we are done. However, buildbots and CI systems may all need updating in quick order when we do this.

**Comment by ViralBShah** [comment]
I believe this is not necessary anymore and am closing it. At this point it would just create a lot of work to rename the directory, but all the misc stuff has been moved to external repos and such.
