### ISSUE TITLE
a couple ignored method ambiguities

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#35933]
Our algorithm for `Base.isambiguous` has been a bit wrong, I think, so we've been excluding many possible ambiguities from printing. (in particular, any method pair for which typeintersect couldn't be computed precisely, I think we just ignored completely)

https://gist.github.com/vtjnash/143e20c7f639bc015772092a7ef9dba1

**Comment by Peiffap** [comment]
Related: #35893.
