### ISSUE TITLE
Modify variable in for loop

### ISSUE THREAD

**Issue by romprakhun** [JuliaLang/julia#35953]
Variable that shouldn't be change (a1) is changed when another variable (a2) is modified by a for loop
`global a2
N = 5
a1 = zeros(3,N)
a2 = a1
println("Value of a1 before")
display(a1)
for i in 1:N-1
    a2[:,i+1] = a2[:,i]+[1;1;1]
end
println("Value of a1 after modifying a2 by for loop")
display(a1)`
![image](https://user-images.githubusercontent.com/1549726/82427692-65c68d00-9ac4-11ea-98e4-86bbddcaeb30.png)

**Comment by KristofferC** [comment]
You need to use `a2 = copy(a1)` if you want them to not point to the same array. Please ask further questions on https://discourse.julialang.org/.
