### ISSUE TITLE
Linux home path with tilde

### ISSUE THREAD

**Issue by bryanlougheed** [JuliaLang/julia#35958]
Hi, 

Using Julia 1.4.1 on Ubuntu 20.04 (kernel 5.4.0-29-generic)

Doing the following:
`include("~/somefolder/file.jl")`

attempts to access the following incorrectly parsed filepath: 
`"/home/myusername/~/somefolder/file.jl"`

Correct filepath should be:
`"/home/myusername/somefolder/file.jl"`

Apologies if this bug has been highlighted already, I did do a search for it first.

Kind regards,
Bryan

**Comment by fredrikekre** [comment]
I don't think Julia expands `~` anywhere, and I believe that is intended.

**Comment by StefanKarpinski** [comment]
You want to use the `expanduser` function.

**Comment by bryanlougheed** [comment]
Still somewhat confused by the behaviour, if ~ is not designed to expand by default, then why did it attempt to when I did 
`include("~/somefolder/file.jl")`

Either it shouldn't expand at all, or it should expand correctly.

**Comment by fredrikekre** [comment]
It just interprets it as a relative path (relative to your pwd).

**Comment by bryanlougheed** [comment]
Aha, yeah, I can't replicate it now. I guess /home/myusername/ must have indeed been the working directory at the time.
