### ISSUE TITLE
GC error + segfault when mucking with Base

### ISSUE THREAD

**Issue by Timeroot** [JuliaLang/julia#35968]
I'm not certain that this is Julia's fault and not my own, but I was extending some `Base` functions to do string operations, trying to do a demo of how you could make `collect("foo" : "foobar")` work. It ended up causing GC corruption and segfaults. I've attached two logs showing how it failed in two separate runs, below is the minimal example.

```
julia> import Base.-, Base.convert, Base.oftype, Base.zero, Base.div, Base.+

julia> convert(A::Type{String}, B::Int) = string(B)
convert (generic function with 183 methods)

julia> zero(::String) = ""
zero (generic function with 17 methods)

julia> A::String-B::String = A[length(B)+1:end]
- (generic function with 175 methods)

julia> A::String+B::String = A*B
+ (generic function with 167 methods)

julia> div(A::String, B::String) = length(A)/length(B)
div (generic function with 55 methods)

julia> collect("hi" : "hello")
```
...and at that point the garbage collector crashes. Admittedly my code was "wrong" in that it starts creating excessively long strings, like `"hi111...[100 more of these]...111". But it's not running out of memory or anything, it's getting corrupted. Note in particular that when it dies, some of the string had already been overwritten by garbage data. My `versioninfo()`:

```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

Logs: 
[julia_log1.txt](https://github.com/JuliaLang/julia/files/4659523/julia_log1.txt)
[julia_log2.txt](https://github.com/JuliaLang/julia/files/4659524/julia_log2.txt)

**Comment by JeffBezanson** [comment]
You're right, this looks interesting.

**Comment by JeffBezanson** [comment]
Ah, try running it with `--check-bounds=yes`. That reveals the problem, which is that the string range reports its length incorrectly as `1` when in fact it goes on forever. There are probably several places in Base that assume lengths are correct. This has come up a couple of times, but I'm not sure what if anything to do about it. It's a tough sell to give up performance to make debugging invalid objects easier, when `--check-bounds` is already available. Maybe we should add a FAQ entry on this.

**Comment by Timeroot** [comment]
Ah, that's definitely my mistake then. Thanks.
