### ISSUE TITLE
proposal: differ between variable declaration and re-assignment

### ISSUE THREAD

**Issue by kolokd** [JuliaLang/julia#35963]
from
```
x = 5

x = 10
```
to 
```
x := 5

x = 10

```

**Comment by kolokd** [comment]
please don't close this issue without discussion.

**Comment by mbauman** [comment]
This is a major breaking change that wouldn't be possible until Julia 2.0 at the earliest and is (in my estimation) unlikely to occur. Asking us to expend effort into discussion of such a speculative issue when you've not expended much effort yourself isn't very compelling.

**Comment by Keno** [comment]
Hi @kolokd, welcome. However, this is not the right place for this issue. As @mbauman indicated this is unlikely to be possible. However, if you would like to discuss the design considerations around, this, please feel free to create a thread on https://discourse.julialang.org/. Do note that this kind of thing has been discussed several times in the past there, so I would suggest you find those discussions, link to them in your opening post so others interested can quickly see the background and then make specific actionable points. With that discussion, I'm gonna close this as non-actionable :).

**Comment by kolokd** [comment]
thanks. 
I have created a thread https://discourse.julialang.org/t/proposal-differ-between-variable-declaration-and-re-assignment/39893
