### ISSUE TITLE
I would love to contribute. .

### ISSUE THREAD

**Issue by Excalibur-Proto** [JuliaLang/julia#35978]
Hi!

I'm a third-year university student majoring in neuroscience with a focus on the pathophysiology of neurodegenerative diseases.
I've recently begun teaching myself python and have gotten fairly comfortable with it - and I would love to contribute to datasciencemasters as it looks like something I would be interested working on!

Only issue is, I've never contributed to anything on github - I know enough git to help myself, but am a fair beginner outside of that.
Could someone point me in the right direction as to a) what needs work and b) in what manner?

General advice is also more than welcome!

Cheers =)

**Comment by fredrikekre** [comment]
This is better suited for the discussion forum: https://discourse.julialang.org/
