### ISSUE TITLE
Drop Windows 7 official support

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#35974]
Windows 7 isn't even supported by Microsoft and has reached EOL https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information  as of early this year.

What does this mean:
- It does NOT mean Julia won't work on Windows 7, it simply means we don't have to support this configuration officially. 

What about Windows 8? Well I'm sure Microsoft wishes you didn't remember this even existed, so we can either also do the same or wait until it's official EOL which happens in Jan 2023.

CF https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

**Comment by PallHaraldsson** [comment]
"has reached EOL", yes and no, they do have extra paid support to 2023. I'm not sure what we should do as a matter of policy on such, e.g. Ubuntu has 5 years LTS support plus extra 5 paid.

I think we shouldn't be more strict than Python at least for Julia (not just Julia LTS); and should go by market share, and Windows 7 is still very common.

If actually works, what's to downside of saying it's officially supported?

I looked at what Python does, at their download page, they state, for latest and back to (but not for 2.7.x) I see:
>""Note that Python 3.5.0 cannot be used on Windows XP or earlier.""

implying Windows 7 works, as it should.

This may be outdated:
https://pythondev.readthedocs.io/platforms.html
>Well supported platforms on Python 3.7 and 2.7:
>[..] Windows Vista and newer for Python 3.7, Windows XP and newer for Python 2.7

I could care less about Vista and Windows 8 support (8.1 however is supported by Microsoft), as have almost no use.

For latest and back to (but not for 2.7.x) I see:
""Note that Python 3.5.0 cannot be used on Windows XP or earlier.""

Mentioned on Wikipedia and:

https://www.microsoft.com/en-us/microsoft-365/blog/2018/09/06/helping-customers-shift-to-a-modern-desktop/

>'''Windows 7 Extended Security Updates'''
>As previously announced, Windows 7 extended support is ending January 14, 2020. [..]
With that in mind, today we are announcing that we will offer paid Windows 7 Extended Security Updates (ESU) through January 2023

**Comment by Excalibur-Proto** [comment]
While that is valid, if new push requests break something on win7 then does the onus of creating new fixes just to accomodate win7 fall on julia developers? Think that's something worthy of consideration.

**Comment by musm** [comment]
> While that is valid, if new push requests break something on win7 then does the onus of creating new fixes just to accomodate win7 fall on julia developers? Think that's something worthy of consideration.

Yes, officially supported means it's under Tier 1 and the onus is to ensure 100% operability.  

>Tier 1: Julia is guaranteed to build from source and pass all tests on these platforms when built with the default options. Official binaries are always available and CI is run on every commit to ensure support is actively maintained.



> Note that Python 3.5.0 cannot be used on Windows XP or earlier.

> implying Windows 7 works, as it should.


Implying it works is different from official support.

**Comment by PallHaraldsson** [comment]
>Implying it works is different from official support.

Right, and I really tried to find something official, and I only found Windows 2000 had been dropped.

**Comment by StefanKarpinski** [comment]
> "has reached EOL", **yes and no**, they do have extra paid support to 2023. I'm **not sure what we should do as a matter of policy on paid-support**, e.g. Ubuntu has 5 years LTS support plus extra 5 paid.

Anyone paying Microsoft for Windows 7 support who wants to run Julia on Windows 7 can pay to have Julia supported on Windows 7 as well. If you're interested in paying for Windows 7 support, you can contact info@juliacomputing.com. As an open source project that has limited resources, I definitely think we should stop officially supporting Windows 7.

**Comment by stahta01** [comment]
If you have "Tier 1 level"; could you just move it down to a lower Tier?

Tim S.

**Comment by PallHaraldsson** [comment]
>Anyone paying Microsoft for Windows 7 support who wants to run Julia on Windows 7 can pay to have Julia supported on Windows 7 as well.

That's sensible, and you have the final word. You're not supporting any Windows for me, I don't use any Windows. I'm just stating it's still popular, and I guess many will continue to use (and not pay, not illegal), while they really shouldn't. Most important is that it will not break Win7 (soon), and I guess tier 2 should do.

**Comment by PallHaraldsson** [comment]
"Tier 2: Julia is guaranteed to build from source using the default build options, but may or may not pass all tests."

This language will be off-putting to Win7 uses I'm sure, who most are not used to building from source. At least consider having tier 1 for latest LTS, currently only 1.0.5. As we know it works, and no reason to break in a minor version, I see no downside to that. Since 1.4 will soon get unsupported, I'm not sure what you want to say on it. We however know 1.4 and 1.5 (and I guess 1.6) still work, so I reccommend stating somehow we know 1.4+ works.

**Comment by ViralBShah** [comment]
What about the various Windows Server releases?

Can someone chime in on which version of Windows do we run our CI infrastructure for and buildbots? It seems that Windows 7 works fine - but if we don't test it, and we are certainly not going to fix issues, moving to Tier 2 is perfectly reasonable.

**Comment by PallHaraldsson** [comment]
>Note we only mention architectures in Support tiers, and not Operating Systems at the moment.

That is not obvious to me, with "Platform" taken as arch plus OS combination:

https://julialang.org/downloads/

**Comment by ViralBShah** [comment]
Never mind the noise. We do mention OS in there. So should be fairly easy to change.

**Comment by ViralBShah** [comment]
This is also a part of https://github.com/JuliaLang/julia/issues/34570

**Comment by ViralBShah** [comment]
Any thoughts on Windows 32-bit? Are there people who use it?

**Comment by ViralBShah** [comment]
This PR makes Windows 10 the minimum. In the documentation, we can mention that older versions may work, but are not supported - your mileage may vary.

https://github.com/JuliaLang/www.julialang.org/pull/838

**Comment by ZenLiuCN** [comment]
so that means  `officially`  not support for many people for try to learn and use this language for they just NOT paid for some newer company product as other language just still do?

**Comment by ViralBShah** [comment]
Merged https://github.com/JuliaLang/www.julialang.org/pull/838

**Comment by i486** [comment]
If anyone stumbled upon this discussion while searching for solutions, try [VXKex](https://github.com/vxiiduu/VxKex/issues/151) a shot. LosslessCut latest version (3.59.1 at the time of writing) appears to be working fine on Windows 7 with VxKex.
