### ISSUE TITLE
Current exit code in `atexit`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#35981]
For MPI.jl we register an exit hook that finalizes the MPI environment. We realized that this can cause apparent hangs if the process exits due to an exception,
so we would like to differentiate between different exitcodes. 

One potential way I found was to look at `jl_current_exception`, but I am worried that this might be fragile.

```
function main()
    error("Goodbye")
end

atexit() do
    exc = ccall(:jl_current_exception, Any, ())
    ccall(:jl_, Cvoid, (Any,), exc)
end

main()
```

cc: @simonbyrne

**Comment by simonbyrne** [comment]
One option would be to change `atexit` to pass an argument, which would either be the error thrown, or `nothing` if no error is thrown (assuming people aren't doing `throw(nothing)`).

```
atexit() do e
    if e === nothing
        # exit gracefully
    end
end
```
we could make this backward compatible with some `hasmethod` trickiness.

**Comment by vchuravy** [comment]
There might not be an exception, but you still are doing an `exit(1)`. So I think getting the exit code as an argument to the function registered with `atexit` would be best.
