### ISSUE TITLE
Bug defining function f taking argument of type f

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#36001]
```jl
julia> N(x::N) where {N} = 3
N (generic function with 0 methods)
```

(This is a MWE reduced from a real situation that had me scratching my head for a while.)

This should either error (probably) or actually define the method.

**Comment by dpsanders** [comment]
This extends to less obvious situations (where it originally arose) such as
```jl
julia> N(x::Array{N,T}) where {N,T} = 3
N (generic function with 0 methods)
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/32531
