### ISSUE TITLE
readavailable is not working for IOStream on a file

### ISSUE THREAD

**Issue by HidemotoNakada** [JuliaLang/julia#36004]
I believe readavailable does not work properly for IOStream on a file.
```
julia> open("tmpfile", "w") do io 
           write(io, "Hello world!")
       end
12

julia> f = open("tmpfile", "r")
IOStream(<file tmpfile>)

julia> readavailable(f)
0-element Array{UInt8,1}
```

While the file obviously has 12 bytes, 'readavailable' does not return any byte. 

Version info is the following.
```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```
'readavailable' works fine for stdio.

Thank you in advance.

**Comment by JeffBezanson** [comment]
`readavailable` can return whatever it finds convenient. In this case, it returns whatever happens to be buffered already. This is not a very good function, because there's no particular guarantee on what it will return. To read the whole file, just use `read`.

**Comment by HidemotoNakada** [comment]
Thank you, but at least, the documents should explicitly define the specification of the function.

**Comment by StefanKarpinski** [comment]
It’s true: the readavailable doc claims to block if no data is available, which is incorrect.

**Comment by strickek** [comment]
Not new: #16821

**Comment by KristofferC** [comment]
Yeah, closing as dup.

**Comment by JeffBezanson** [comment]
Wait a minute, looking at this again, it is a bug in this particular method. All the other methods make sure to return at least one byte.
