### ISSUE TITLE
regex captures documentation

### ISSUE THREAD

**Issue by muv1** [JuliaLang/julia#36014]
If I have some code like this:

~~~jl
o = match(r"e(..)", "Wednesday")
a = o.captures
println(a)
~~~

I get this result:

~~~jl
Union{Nothing, SubString{String}}["dn"]
~~~

I was a little confused by all the decoration on the result. So I went to look
at the documentation, but then I realized there wasnt any. The only mention of
this `struct` is here:

> The matching substring can be retrieved by accessing `m.match` and the
> captured sequences can be retrieved by accessing `m.captures`

<https://docs.julialang.org/en/v1/base/strings#Base.match>

So I went searching and found the `struct` definition in the code:

<https://github.com/JuliaLang/julia/blob/40a8b42d45a274a0f91565693830360faa12081c/base/regex.jl#L134-L140>

I think more detail should be given about what is being returned, and what
properties are available with the return `struct`. Compare with Python:

~~~py
import re
o = re.search('e(..)', 'Wednesday')
a = o.groups()
# ('dn',)
~~~

> Return a tuple containing all the subgroups of the match, from 1 up to however
> many groups are in the pattern.

<https://docs.python.org/library/re.html#re.Match.groups>

Or Go:

~~~go
package main
import (
   "fmt"
   "regexp"
)
func main() {
   o := regexp.MustCompile("e(..)")
   a := o.FindStringSubmatch("Wednesday")
   fmt.Println(a)
   // [edn dn]
}
~~~

> `FindStringSubmatch` returns a slice of strings holding the text of the
> leftmost match of the regular expression in `s` and the matches, if any, of
> its subexpressions, as defined by the `Submatch` description in the package
> comment. A return value of `nil` indicates no match.

<https://golang.org/pkg/regexp#Regexp.FindStringSubmatch>

Or Rust:

~~~rust
use regex::Regex;
use std::error::Error;
fn main() -> Result<(), Box<dyn Error>> {
   let o = Regex::new("e(..)")?;
   let a = o.captures("Wednesday").ok_or("Err")?;
   println!("{:?}", a);
   // Captures({0: Some("edn"), 1: Some("dn")})
   Ok(())
}
~~~

> Returns the capture groups corresponding to the leftmost-first match in
> `text`. Capture group `0` always corresponds to the entire match. If no match
> is found, then `None` is returned.

<https://docs.rs/regex/1.3.7/regex/struct.Regex.html#method.captures>

Then if you click through, you get an entire page just about the return
`struct`:

<https://docs.rs/regex/1.3.7/regex/struct.Captures.html>

**Comment by kimikage** [comment]
cf. https://docs.julialang.org/en/v1/manual/strings/#Regular-Expressions-1

**Comment by muv1** [comment]
Hm, I didnt see that before, thanks.

I see that the Strings Manual is also linked in the sidebar. It might be helpful to add the link youve put in context in the `base/strings` page, so people dont have to hunt for it.
