### ISSUE TITLE
Missing lmul!(::Diagonal, ::AbstractVector)

### ISSUE THREAD

**Issue by jagot** [JuliaLang/julia#36011]
I made the following discovery:
```julia
julia> using LinearAlgebra

julia> a = rand(5)
5-element Array{Float64,1}:
 0.6631204139014786
 0.6203407887742025
 0.6477234121797579
 0.034575343863902486
 0.12155195110829498

julia> lmul!(Diagonal(rand(5)), a)
ERROR: MethodError: no method matching lmul!(::Diagonal{Float64,Array{Float64,1}}, ::Array{Float64,1})
Closest candidates are:
  lmul!(::Number, ::AbstractArray) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generi
```

| `typeof(A)` | `lmul!` | `ldiv!`|
|-|- |-|
| `Number` | [x] | [x] |
| `Diagonal` | [ ] | [x] |
| `UpperTriangular` | [x] | [x] |
| `LowerTriangular` | [x] | [x] |

Y no ❤️ for `lmul!(::Diagonal, ::AbstractVector)`?

**Comment by mcabbott** [comment]
It also fails for `lmul!(rand(5,5), rand(5))`, should that also be fixed?

**Comment by jagot** [comment]
I don't think that's possible to compute in-place; multiplication/solution by `Number` and `Diagonal` is trivial, and for triangular matrices it can be done by forward and backwards sweeps. For a dense matrix I don't think you can compute the matrix–vector product without temporaries.

**Comment by mcabbott** [comment]
Oh right, good point.
