### ISSUE TITLE
Remove enforcal of printing exceptions as red

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#36015]
The code here

https://github.com/JuliaLang/julia/blob/0413ef0e4de83b41b637ba02cc63314da45fe56b/base/errorshow.jl#L87-L95

tries its best to ensure that the `showerror` code an exception implement gets printed in red. This can mess up custom coloring that the exception itself tries to do in `showerror`. For example, here is some code that defines an exception text using colors:

```
julia> struct CustomException end

julia> function Base.showerror(io::IO, ce::CustomException)
           printstyled(io, "This is in red\n"; color=:light_red)
           println(io, "This is in white")
       end
```

Trying with the normal two arg `showerror` and things look ok. But when the error would actually be shown in REPL, the second line would have "magically" also turned red, ruining the formatting.

![bild](https://user-images.githubusercontent.com/1282691/82759899-675bc200-9df0-11ea-99ab-cc93697e773f.png)

If an exception wants to print its text in red, it can just implement that with `printstyled`.

**Comment by JeffBezanson** [comment]
I guess just printing `ERROR:` in red is enough to call attention to it, so I'm fine with that.

**Comment by kimikage** [comment]
Although I don't feel strongly about it, the fully red messages are somewhat useful when the log is slightly long, and the color is no longer helpful when the log is "very" long.

The coloration is auxiliary function, so I don't think designers of exceptions should specify the colors actively. If desired, you can specify the `:normal` color 

```julia
function Base.showerror(io::IO, ce::CustomException)
    printstyled(io, "This is in red\n"; color=:light_red)
    printstyled(io, "This is in white(?)\n"; color=:normal)
end
```

**Comment by KristofferC** [comment]
> The coloration is auxiliary function, so I don't think designers of exceptions should specify the colors actively. 

Why not? Colors can be very useful to improve the clarity of error messages. 

> If desired, you can specify the :normal color

I know how to work around it. I am saying that trying to color the whole exception message in red is just a bad idea because you don't know how the one that made the error message wants to format it.

**Comment by kimikage** [comment]
> Why not?

Encouraging you to customize the color of error messages spoils the simple rule of "red means error".
Unfortunately, I don't think many users read error messages as carefully as you do. :sweat_smile:

**Comment by KristofferC** [comment]
> Unfortunately, I don't think many users read error messages as carefully as you do. sweat_smile

That seems like an argument to make them better so that peoiple will start reading them? The context this comes up in was when doing error messages for a TOML parser:

![bild](https://user-images.githubusercontent.com/1282691/82793069-9dd92180-9e70-11ea-81c0-c8d18a5c687a.png)

compare that with

![bild](https://user-images.githubusercontent.com/1282691/82793318-fb6d6e00-9e70-11ea-9b81-e06417d9bde3.png)
