### ISSUE TITLE
Speed of ERROR: LoadError

### ISSUE THREAD

**Issue by muv1** [JuliaLang/julia#36016]
If I have a file like this:

~~~jl
println("Sunday")
~~~

Julia works fine:

~~~
$ time julia a.jl
Sunday

real    0m0.170s
~~~

With a file like this:

~~~
a()
~~~

The error process seems to be very slow:

~~~
$ time julia b.jl
ERROR: LoadError: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope at D:\Desktop\etc\b.jl:1
 [2] include(::Module, ::String) at .\Base.jl:377
 [3] exec_options(::Base.JLOptions) at .\client.jl:288
 [4] _start() at .\client.jl:484
in expression starting at D:\Desktop\etc\b.jl:1

real    0m0.990s
~~~

The `--compile` flag helps significantly:

~~~
$ time julia --compile=min b.jl
ERROR: LoadError: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope at D:\Desktop\etc\b.jl:1
 [2] include(::Module, ::String) at .\Base.jl:377
 [3] exec_options(::Base.JLOptions) at .\client.jl:288
 [4] _start() at .\client.jl:484
in expression starting at D:\Desktop\etc\b.jl:1

real    0m0.290s
~~~

but still seems to be quite slow compared to other options, like Python:

~~~
$ cat a.py
a()

$ time python a.py
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    a()
NameError: name 'a' is not defined

real    0m0.060s
~~~

PHP:

~~~
$ cat a.php
<?php
a();

$ time php a.php
Fatal error: Uncaught Error: Call to undefined function a() in C:\a.php:2
Stack trace:
#0 {main}
  thrown in C:\a.php on line 2

real    0m0.060s
~~~

Dart:

~~~
$ cat a.dart
main() {
   a();
}

$ time dart a.dart
a.dart:2:4: Error: Method not found: 'a'.
   a();
   ^

real    0m0.160s
~~~

**Comment by fredrikekre** [comment]
I believe this is not specific to speed of error pahts, just about Julias latency and startup timing. `println` is explicitly precompiled so thats why that part is fast.

**Comment by JeffBezanson** [comment]
Yes, this is just the usual latency problem; see the "latency" label. I think we have enough issues covering this.

**Comment by StefanKarpinski** [comment]
In particular, printing unusual error types can take a long time because they have printing methods that are very unlikely to have been compiled already (since they're errors). Might make sense for error code to always be interpreted or not compiled for performance, but I think the compiler folks are well aware of that consideration.
