### ISSUE TITLE
Should failure on (recent) 1.6 nightly be reported?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#36034]
I got some garbled output, adding a package, then ok...:

https://github.com/JuliaAstro/ERFA.jl/issues/48

I've also had some cases where 1.6 doesn't work, but works on older version. Those older failures were not garbled. I've reported to those package(s).

Both happen to be wrappers, might be important detail (and for that one useful commit info for bisect): https://github.com/heliosdrm/GRUtils.jl/issues/61#issuecomment-633313799

Error (not a wrapper): https://github.com/timholy/ProfileView.jl/issues/149

**Comment by fredrikekre** [comment]
Yes, if they are Julia issues. The linked issues seems to be issues with packages.

**Comment by PallHaraldsson** [comment]
No as I said, work in older version.

And he top error was very strange, as pkg> add PACKAGE doesn't trigger its source code that I know of. Can it be other than a bug in Julia?

**Comment by KristofferC** [comment]
Having Revise loaded when upgrading loaded packages can cause weird issues to occur (although it should mostly work fine). Can  you repro it without Revise loaded?

**Comment by PallHaraldsson** [comment]
At least the one for GR.jl is something that works on my older Julia 1.4.0 (in 5.5 sec), is a bug in Julia (and/or latest version of GR, or its dependenciese), a hang, for at least a minute:

```
$ ~/julia-1.6.0-DEV-8f512f3f6d/bin/julia --startup-file=no
(@v1.6) pkg> up GR
julia> using GR
julia> @time (x = LinRange(0, 10, 500); y = sin.(x.^2) .* exp.(-x); plot(x, y))
^C
^C
```

**Comment by JeffBezanson** [comment]
In the future, please report bugs in the format (1) exactly what you did, (2) exactly what happened, (3) why it is wrong (if not obvious). Reading this and clicking through things for several minutes I can't find that information, which is probably why this was closed.

**Comment by PallHaraldsson** [comment]
You want me to refile that one? In full (in link from the top, where I edited):

```
(@v1.6) pkg> add ERFA
[..]
Updating `~/.julia/environments/v1.6/Project.toml`
 Revise [944b1d66] .↓ CodecZlib v0.7.0 ⇒ v0.6.0LogRecord
( Error [17511681] , + ERFA v0.6.3evaluation error starting at /home/pharaldsson_sym/.julia/packages/Plots/FYxdA/src/utils.jl:153
,  lowered [91a5bcdd] , ↑ Plots v1.3.2 ⇒ v1.3.3Revise_e943ed8b

[..]

 [91a5bcdd]         ↑ Plots v1.3.2 ⇒ v1.3.3#= 
/home/pharaldsson_sym/.julia/packages/Plots/FYxdA/src/utils.jl : [df47a6cb] 153↑ RData v0.6.3 ⇒ v0.7.1 =#

          [3161d3a3] #= ↑ Zstd_jll v1.4.4+1 ⇒ v1.4.5+0/home/pharaldsson_sym/.julia/packages/Plots/FYxdA/src/utils.jl
:   Building153 =# @eval begin
                #= /home/pharaldsson_sym/.julia/packages/Plots/FYxdA/src/utils.jl:154 =#
                RecipesPipeline.unzip(v::Union{AVec{<:Tuple{Vararg{T, $i} where T}}, AVec{<:GeometryTypes.Point{$i}}}) = begin
                        #= /home/pharaldsson_sym/.julia/packages/Plots/FYxdA/src/utils.jl:155 =#
                        $(Expr(:tuple, (:([t[$j] for t = v]) for j = 1:i)...))
                    end
            end
    end
end) MethodError: no method matching (::Plots.var"#530#531")(::Int64)
The applicable method may be too new: running in world age 27766, while current world is 29222.
Closest candidates are:
  #530(::Any) at none:0 (method too new to be called from this world context.)ERFA ─→ `~/.julia/packages/ERFA/2XJBu/deps/build.log`
Stacktrace:

```

I thought it was obvious "garbled" is always an error (and the package maintainer closed, fairly I think, as not about his package). I'm not to up-to-speed in this "too new: running in world age" I failed to mention here.
