### ISSUE TITLE
Random number generation: randn changed behavior on master

### ISSUE THREAD

**Issue by daviehh** [JuliaLang/julia#36052]
On master, the random number generator no longer acts correctly after seeding. With a fresh seed, 
`y = randn(MersenneTwister(1), Float64, 20)`
will diverge from 
`x = randn(MersenneTwister(1), Float64, 10)`
beginning with the 8th element, causing `y[1:10]` to be different from `x`

Test script:
```
using Random

@info "1st call"
rng = MersenneTwister(1)
x = randn(rng, Float64, 10)
display(x)

println("\n"*"-"^6)
@info "2nd call"
rng = MersenneTwister(1)
y = randn(rng, Float64, 20)
display(y)

println("\n"*"-"^6)
println(isapprox(x, y[1:10]))
```

gives `true` on  Release/correct version: Julia 1.4.2 but `false` on master; on master, 
`display(x - y[1:10])` is
```
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 -1.5094533110800028
  0.3009560212569654
  2.698507875223443
```

**Expected behavior**: with the same fresh seed, generating, say 20 `randn` should be the same as generating 10 and then another 10, or one-by-one:
```
using Random

rng = MersenneTwister(1)
x = randn(rng, Float64, 20)

rng = MersenneTwister(1)
a = randn(rng, Float64, 10)
b = randn(rng, Float64, 10)

rng = MersenneTwister(1)
y = [randn(rng, Float64) for i = 1:20]


@assert isapprox([a;b], x)
@assert isapprox(y, x)
```

julia versioninfo:
```
Julia Version 1.6.0-DEV.82
Commit 852ff2bdab* (2020-05-23 14:33 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.4.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

maybe related to https://github.com/JuliaLang/julia/pull/35078

btw, generating e.g. 20 random numbers with `randn(MersenneTwister(1), Float64, 20)` gives different result on Julia 1.4.2 vs master: the master differs from the released version after the 8th element. (sort-of ok/documented, noticed in news.md).

**Comment by KristofferC** [comment]
What do you mean by wrong behavior? I don't think you should assume that `randn(n)` is implemented the same way as calling `randn` `n` times, nor that `randn(m)` must give you the same numbers for `1:n` as `randn(n)` where `m > n`.

The change is from:

https://github.com/JuliaLang/julia/pull/35078#issue-386858628

> There is a threshold on the length of the array between 10-20 below which this refined algorithm is less performant, so we switch the algorithm depending on that length.

**Comment by rfourquet** [comment]
Yes as Kristoffer said we don't guarantee the behavior that you expected. The same behavior happens already with `rand(Float64)` (i.e. not `randn`) since at least Julia 1.0.

I will leave this open as a documentation issue, might be worth putting what can't be expected in the docstring or in the manual. 

As a side note, if you need this behavior for tests, the `StableRNGs` package might help (it guarantees what you expected). But disclaimer: I would not trust it fully for production software or publishing a scientific result, just for tests.

**Comment by daviehh** [comment]
Understood. Thanks a lot!
