### ISSUE TITLE
Integer to the power of integer is too slower than converting everything to floats and then rounding at the end

### ISSUE THREAD

**Issue by s-baumann** [JuliaLang/julia#36051]
In a test case I get it to be about 4 times faster to convert an integer to a float, raise them to a power and then round them back to integers rather than use the inbuiltin integer to power of integer code.

```
using BenchmarkTools
@benchmark 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2 * 2
# Median times excluding compilation run
# 1.501 ns
# 1.501 ns
# 1.200 ns
@benchmark 2^20
# Median times excluding compilation run
# 5.499 ns
# 6.600 ns
# 6.699 ns
@benchmark round(Float64(2)^Float64(20))
# Median times excluding compilation run
# 1.600 ns
# 1.800 ns
# 1.600 ns
```

Debugging it the Float version goes into a c function ccall("llvm.pow.f64"...). On the other hand the integer version goes into power_by_squaring(x_, p::Integer) which is in intfuncs.jl

I think the issue is that power_by_squaring refactors the problem to instead solve ((2^2)^2)^5)). It uses the trailing_zeros function as part of this refactorisation - potentially that is very slow.

If I remove that and just calculated (2^20) in the usual way I get the same speed as the other implementations. So potentially there is a speed issue in trailing_zeros or it is overly expensive for this function.
```
import Base._return_type
to_power_type(x) = convert(Base._return_type(*, Tuple{typeof(x), typeof(x)}), x)
function power_by_squaring(x_, p::Integer)
    x = to_power_type(x_)
    if p == 1
        return copy(x)
    elseif p == 0
        return one(x)
    elseif p < 0
        isone(x) && return copy(x)
        isone(-x) && return iseven(p) ? one(x) : copy(x)
        throw_domerr_powbysq(x, p)
    end
    res = zero(x_)
    for i in 1:p res *= x_ end
    return res
end

@benchmark power_by_squaring(2, 20)
# Median times
# 1.501 ns
# 1.499 ns
# 1.499 ns

```

**Comment by mbauman** [comment]
Welcome!

You're not benchmarking what you think you're benchmarking.  When using BenchmarkTools, you want to be careful about flagging certain portions of your code as being _arguments_ to the benchmark kernel; otherwise it will use them as literal constants and allow Julia to do lots of compile-time magic.  Do this with a `$`:

```Julia
julia> @benchmark $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2 * $2
  median time:      55.829 ns (0.00% GC)

julia> @benchmark $2^$20
  median time:      5.385 ns (0.00% GC)

julia> @benchmark round(Float64($2)^Float64($20))
  median time:      18.275 ns (0.00% GC)
```

In other words, I think in normal (non-literal) circumstances, you'll see the performance you want.  So the key isn't that `power_by_squaring` is slow, rather it's just complicated enough that it's not possible to do quite as much compile-time preprocessing as is possible in the other cases.

**Comment by s-baumann** [comment]
Ah ok. So in the first and third cases I guess it ran the code to get a constant. And the benchmark was measuring how fast that constant could be reported. That makes sense. Cheers.
