### ISSUE TITLE
Your product does not work - dyld: Symbol not found: __ZN4llvm3orc15SymbolStringPtr9TombstoneE

### ISSUE THREAD

**Issue by davidmontgom** [JuliaLang/julia#36060]
This deal with the below?    This error leaves me nowhere to go.  If I have a choice between rust and Julia I choose rust since more stable. I mean wow I install the dmg for a mac..lastest version and I get the below error?  

 exec '/Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia'
dyld: Symbol not found: __ZN4llvm3orc15SymbolStringPtr9TombstoneE
  Referenced from: /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
  Expected in: /Users/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libLLVM.dylib
 in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../lib/libjulia.dylib

**Comment by vtjnash** [comment]
Looks like installing rust has broken your system/user configuration. I'd guess you have a `DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH` variable now set, which is usually a sign of badly configured software or a misunderstanding.

**Comment by JeffBezanson** [comment]
@davidmontgom We always appreciate bug reports but please approach them with a more constructive tone.

**Comment by StefanKarpinski** [comment]
"Product" implies that you paid us for it.

**Comment by davidmontgom** [comment]
Well considering that I  pay over 10K a year for sas (and when I say I mean
I) I would have zero issues paying for Julia if it worked.  I can't fathom
how a working rust setup interferes with Julia. So I willl never get to get
to a paid version.  Spending hours dealing with julia when I have zero
issues with c++, rust, python is very very concerning.  I was
very much looking forward to using the tutorial with Thomas Sergeant with
Juila and maybe using code in production and can't fathom how when I
can't even install on mac with a DMG

**Comment by vtjnash** [comment]
You and/or rust have corrupted your computer setup. That's not our fault. (Though yours is a common enough problem that we've seen from people blindly following bad advice or using bad installation programs. So it's generally easy to diagnose.)

**Comment by KristofferC** [comment]
>  I can't fathom how a working rust setup interferes with Julia. 

You see that it is trying to use the Rust LLVM library:

>  `Expected in: /Users/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libLLVM.dylib
in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../lib/libjulia.dylib`

As you got told, this happens when you interfere with the normal way that the dynamic linker loads libraries (by e.g. setting `DYLD_LIBRARY_PATH`). It is impossible for Julia to do anything about this.

So something about installing Rust (or a manual tweak you did to Rust work) have messed up your system. Maybe open a bug report on the Rust repo if this happens with a normal Rust install?
