### ISSUE TITLE
Error if ° in a comment

### ISSUE THREAD

**Issue by AlexisRenchon** [JuliaLang/julia#36063]
New error in julia 1.5 (works in all versions of 1.4)

I have a script which contain a comment line with a °, as below

#Mechanistic model of heterotrophic soil respiration as a function of soil temperature (Tsoil, °C)  and soil moisture (Msoil, m3 m-3)

running that script itself works, but opening it from another file with include() return the error 

julia> include("DAMM.jl");
ERROR: LoadError: syntax: invalid UTF-8 sequence

If the comment does not contain the °, no error is returned

#Mechanistic model of heterotrophic soil respiration as a function of soil temperature (Tsoil, C)  and soil moisture (Msoil, m3 m-3)

**Comment by StefanKarpinski** [comment]
Seems like your source file is likely invalid UTF-8. Can you upload a copy? Alternately, do `isvalid(read(path, String))`. If that returns false, your file is not valid UTF-8.

**Comment by StefanKarpinski** [comment]
We did make a change to actively reject any source file that is not valid UTF-8 This release, so this is likely not a big.

**Comment by AlexisRenchon** [comment]
The file is https://github.com/Land-atmosphere-interface-heterogeneity/GIF-TEROS11-Julia/blob/master/DAMM.jl

julia> mypath = "C:\\Users\\arenc\\Documents\\GitHub\\GIF-TEROS11-Julia\\DAMM.jl"
"C:\\Users\\arenc\\Documents\\GitHub\\GIF-TEROS11-Julia\\DAMM.jl"

#no ° in line 2

julia> isvalid(read(mypath, String))
true

#° in line 2

julia> isvalid(read(mypath, String))
false

(this is not really a problem for me, and I could write the ° as a unicode instead of just typing it)

**Comment by PallHaraldsson** [comment]
I couldn't even reproduce by copy pasting from your file (somthing seems to fix, at least in my terminal in Linux), until I did:

```
$ wget https://raw.githubusercontent.com/Land-atmosphere-interface-heterogeneity/GIF-TEROS11-Julia/master/DAMM.jl

shell> diff DAMM.jl DAMM.jl_ok
2c2
< # Mechanistic model of heterotrophic soil respiration as a function of soil temperature (Tsoil, �C)  and soil moisture (Msoil, m3 m-3)
---
> # Mechanistic model of heterotrophic soil respiration as a function of soil temperature (Tsoil, °C)  and soil moisture (Msoil, m3 m-3)
```

**Comment by AlexisRenchon** [comment]
I use VIM in windows
I agree that this is probably a problem from my editor. 
I think we can close this issue
