### ISSUE TITLE
 issue in PiGPIO.jl. 

### ISSUE THREAD

**Issue by gpapalambrou** [JuliaLang/julia#36109]
# Julia script for GPIO in Raspberry 4, operate servo with PWM
# Julia version 1.0.3 / Raspbian julia/1.0.3+dfsg-4+rpi1

using PiGPIO
red_pin = 17 # GPIO17 = :11
p=Pi()
PiGPIO.set_PWM_frequency(p, red_pin, 50) # assume sample rate = 5 microsec.
PiGPIO.set_PWM_dutycycle(p, red_pin, 128 )
PiGPIO.set_servo_pulsewidth(p,red_pin,0)
PiGPIO.set_servo_pulsewidth(p,red_pin,1000)

The above script fails with output:
ERROR: LoadError: UndefVarError: int not defined
Stacktrace:
[1] set_servo_pulsewidth(::Pi, ::Int32, ::Int32) at /home/pi/.julia/packages/PiGPIO/zdssl/src/pi.jl:674
[2] top-level scope at none:0
[3] include at ./boot.jl:317 [inlined]
[4] include_relative(::Module, ::String) at ./loading.jl:1044

SOLUTION with success: this is a typo in PiGPIO/src/pi.jl:675 2. That int should be Int, try changing that on local copy and restarting Julia.

**Comment by gpapalambrou** [comment]
SOLUTION with success: this is a typo in PiGPIO/src/pi.jl:675 2. That int should be Int, try changing that on local copy and restarting Julia.

**Comment by StefanKarpinski** [comment]
It would be great if you could file an issue with the PiGPIO package so that they are aware and can fix this.
