### ISSUE TITLE
In-place broadcasting into non-broadcastable things

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#36105]
So we have the syntax `A .= x`, broadcasting `x` into `A`'s shape and mutating `A` to those new values.  I've always thought of this syntax only supporting broadcastable LHSes, but prior to #35620 this wasn't actually necessary... the default broadcast machinery seamlessly transformed this into a call to `copyto!(A, x)` without requiring much of `A` at all.

### Version 1.4

```Julia
julia> struct Foo end
       Base.size(::Foo) = ()
       Base.copyto!(::Foo, x) = "custom .= implementation"

julia> Foo() .= 1
"custom .= implementation"
```

### Version 1.5-beta.1

```Julia
julia> struct Foo end
       Base.size(::Foo) = ()
       Base.copyto!(::Foo, x) = "custom .= implementation"

julia> Foo() .= 1
ERROR: MethodError: no method matching ndims(::Type{Foo})

julia> Base.ndims(::Type{Foo}) = 1

julia> Foo() .= 1
"custom .= implementation"
```

This snagged several packages:

* [HomotopyContinuation](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl) defines a `WeightedNorm` that wraps a vector but isn't itself a vector or even iterable.  It does, however, [support `copyto!` and `size`](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/blob/f37076e420b157d84d5d94728f7b1724890ef3d3/src/norm.jl#L92-L93), and its tests use `.=` to simply change the wrapped vector.  It is currently not possible to use a WeightedNorm in any other broadcast expression.
* [DataFrames](https://github.com/JuliaData/DataFrames.jl) also got snagged by this, but they [already fixed it](https://github.com/JuliaData/DataFrames.jl/commit/15385f60d9c3b660a9f9114810d3a9cc68525157) and tagged a new version.  Two other packages haven't updated to version 0.21 yet and thus hit this themselves — but will be fixed upon upgrading to the new version ([Diversity.jl](https://github.com/richardreeve/Diversity.jl/blob/26a8b5c22859815d35b98c8d563500cbd11285a8/Project.toml#L20) and [RevealedPreferences](https://github.com/EliasBcd/RevealedPreferences.jl/blob/a0089a3723a622e21f9f1ebf315799136598c438/Project.toml#L15).

-----

So the question is: are we ok with this change?  I'm inclined to say that the existing usages are incomplete specifications.

**Comment by mbauman** [comment]
Both packages snagged by this agreed they had an incomplete specification and have already fixed it themselves.  I think the gain in functionality is worth this very minor change, and I would advocate for no additional changes here.

**Comment by tkf** [comment]
I suppose 1.4-like behavior is still possible by overloading `materialize!` and taking over the style promotion?  If so, I guess nothing is essentially lost?

(Of course, opening up `materialize!` as a public API or not is another question.)

**Comment by mbauman** [comment]
Yes, that would work, but the better way (and the way both those packages pursued) is simply to "finish" implementing the broadcastable interface.

**Comment by tkf** [comment]
Yeah, I agree that's the right move, e.g., for the packages you listed in the OP.

I was thinking about extending the semantics of broadcasting where `axes` makes less sense. Something like nested arrays and dictionaries (like Python's [awkward-array](https://github.com/scikit-hep/awkward-array); Related discussion with @andyferris in https://github.com/andyferris/Dictionaries.jl/issues/19).

**Comment by andyferris** [comment]
I agree that the awkward-array style operations are good target.

For nested things @tkf I wonder if we could using nested dot-getindices operations to detangle it on the LHS, as it seems (to me) you might need to do anyway on the RHS?

```julia
A.[2:4].[end] .= B.[1:3].[begin]
```

**Comment by tkf** [comment]
(Just a quick response, but maybe #30845 is the best place to continue the discussion?)

**Comment by mbauman** [comment]
Yes, and I think this issue can be closed.
