### ISSUE TITLE
StackOverflow when testing == of a circular dict with itself

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#36101]
```jl
julia> d = Dict{String, Any}();

julia> d["foo"] = d;

julia> d == d
# Boom
```

Probably caused by https://github.com/JuliaLang/julia/pull/34809.

**Comment by JeffBezanson** [comment]
I don't think this is expected to work. We don't promise terminating `==` on circular structures (this isn't R6RS scheme :smile:).

**Comment by KristofferC** [comment]
Fixed the package in https://github.com/fredo-dedup/JSONSchema.jl/pull/16. Perhaps this can be closed.
