### ISSUE TITLE
Alter `CodeInfo.linetable` to store relative, not absolute, line numbers

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#36110]
If we make the `CodeInfo.linetable` encode relative offsets from `(m::Method).line`, perhaps we could eliminate [two](https://github.com/JuliaLang/julia/blob/147d5b101cea8c845b81c80943a8089bd59f5e1a/base/errorshow.jl#L554-L563) [callbacks](https://github.com/JuliaLang/julia/blob/147d5b101cea8c845b81c80943a8089bd59f5e1a/base/methodshow.jl#L122-L125). When code moves, Revise could just set `m.line` and everything else would follow. A potential concern is that if you only have the `src::CodeInfo` and don't know which `Method` it came from, you couldn't compute the absolute line number.

**Comment by Keno** [comment]
After inlining, we also store inlined frames in the line table, at which point it's not just an offset.

**Comment by timholy** [comment]
Oof, yes, that won't work. I guess you'd need to link to the inlined methods, and that starts to be a lot of pointer relocation...
