### ISSUE TITLE
Suggest vcat and hcat derive from cat

### ISSUE THREAD

**Issue by ablaom** [JuliaLang/julia#36112]
I've just implemented an new AbstractArray type and after overloading `Base.cat` for my new type, discovered that `vcat` also needed to be overloaded. Is there a reason `vcat(A...)` does not fall back to `cat(A..., dims=1)`?

**Comment by strickek** [comment]
#31183

**Comment by vtjnash** [comment]
It is somewhat unclear how to overload cat properly (https://github.com/JuliaLang/julia/issues/2326) but I believe this should generally now be true:
```
   1 # The specializations for 1 and 2 inputs are important
   2 vcat(A::AbstractArray) = cat(A; dims=Val(1))
   3 vcat(A::AbstractArray, B::AbstractArray) = cat(A, B; dims=Val(1))
   4 vcat(A::AbstractArray...) = cat(A...; dims=Val(1))
   5 vcat(A::Union{AbstractArray,Number}...) = cat(A...; dims=Val(1))
   6 hcat(A::AbstractArray) = cat(A; dims=Val(2))
   7 hcat(A::AbstractArray, B::AbstractArray) = cat(A, B; dims=Val(2))
   8 hcat(A::AbstractArray...) = cat(A...; dims=Val(2))
   9 hcat(A::Union{AbstractArray,Number}...) = cat(A...; dims=Val(2))
```

**Comment by ablaom** [comment]
Thanks @vtjnash. But to be clear, are these fallbacks that have been added since I opened the issue, or recommendations for explicit overloadings?

**Comment by vtjnash** [comment]
It is generally new now
