### ISSUE TITLE
Can we prettify how methods are printed as in #36026?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#36129]
The current output of `ClearStacktrace.jl` is pretty good. I just wonder if the same technique discussed in #36026 can be used on how methods are printed in `methods` and `methodswith`? Considering the different result types of them, maybe we need to redefine how methods are shown?

```julia
julia> methodswith(Int) |> typeof
Array{Method,1}

julia> methods(Int) |> typeof
Base.MethodList
```

**Comment by thofma** [comment]
Related: https://github.com/chris-b1/MethodsFor.jl

**Comment by singularitti** [comment]
> Related: https://github.com/chris-b1/MethodsFor.jl

Thank you, cool package! Though it still does not solve my concern: its printed message is not detailed, no types, no locations, etc.

**Comment by Matthew-D-Dwyer** [comment]
Thanks for raising this issue. 

The output is still as you described in Julia 1.6.2, is there a useful label you could apply to the issue to help more people find it? 

Matt.

**Comment by laborg** [comment]
In a sense a duplicate of https://github.com/JuliaLang/julia/issues/30110

**Comment by vtjnash** [comment]
Will be closed by https://github.com/JuliaLang/julia/pull/40251
