### ISSUE TITLE
Display of array elements seems to use ::Mime:text/plain in juia1.5.0-beta1

### ISSUE THREAD

**Issue by jmichel7** [JuliaLang/julia#36149]
I feel issue #36072 is not closed, because checking `:compact` still gives a different behaviour for vectors compared to 1.4.2:
```
julia> [Mod{19}(1), Mod{19}(2)] # in 1.5.0-beta1
2-element Array{Mod{19},1}:
 Mod{19}: 1
 Mod{19}: 2

julia> [Mod{19}(1), Mod{19}(2)] # in 1.4.2
2-element Array{Mod{19},1}:
 1
 2
```

I want to show the type only if it has not been shown already. Actually, exploring the `io.dict` I found that the following does the job:
```
julia> function Base.show(io::IO, ::MIME"text/plain", x::Mod{p}) where p
  if !haskey(io,:typeinfo) print(io,typeof(x),": ") end
  print(io,x.val)
end
```

so this leaves me confused, because the role of `:compact` seems to make a distinction between 1-dimensional and higher-dimensional arrays rather than telling the type has been displayed.

**Comment by KristofferC** [comment]
Please keep the discussion in the original issue which has all the context and previous discussion in place.

**Comment by KristofferC** [comment]
Closing as dup of #36072

**Comment by jmichel7** [comment]
________________________________
>De : Kristoffer Carlsson [notifications@github.com]
>Envoyé : jeudi 4 juin 2020 19:50
>À : JuliaLang/julia
>Cc : MICHEL Jean; Author
>Objet : Re: [JuliaLang/julia] Display of array elements seems to use ::Mime:text/plain in juia1.5.0-beta1 (#36149)


>Please keep the discussion in the original issue which has all the context and previous discussion in place.


Sorry. I opened a new issue beacuse this is what Github recommends for people who do not have the right to reopen their own issue.

**Comment by jmichel7** [comment]
________________________________
>De : Kristoffer Carlsson [notifications@github.com]
>Envoyé : jeudi 4 juin 2020 19:50
>À : JuliaLang/julia
>Cc : MICHEL Jean; Author
>Objet : Re: [JuliaLang/julia] Display of array elements seems to use ::Mime:text/plain in juia1.5.0-beta1 (#36149)


>Closing as dup of #36072<https://github.com/JuliaLang/julia/issues/36072>


Can you reopen for me #36072?
