### ISSUE TITLE
How Julia call Pybind11 code?

### ISSUE THREAD

**Issue by agdkyang** [JuliaLang/julia#36154]
Pybind11 code :
```c++
#include <pybind11/embed.h> 
#include <iostream> 
namespace py = pybind11; 
extern "C"{
int init() { 
    py::scoped_interpreter python; 
   auto math = py::module::import("math"); 
    double root_two = math.attr("sqrt")(2.0).cast<double>(); 
    std::cout << "The square root of 2 is: " << root_two << "\n"; 
} }
```
I will generate a dynamic library libtest.so by using the above code and link to libpython3.7m.so. However, I Julia call libtest.so, math.cpython-37m-x86_64-linux-gnu.so cannot link to libpython3.7m.so  and occured error like this undefined symbol: PyArg_Parse. But when c language call libtest.so ,there is no problem. I don't know why math.cpython-37m-x86_64-linux-gnu.so cannot link to libpython3.7m.so directly when using julia language. And how to solve this problem?

**Comment by yuyichao** [comment]
Please ask questions on http://discourse.julialang.org/ and please make sure your code is quoted (see edit).
