### ISSUE TITLE
Multiprocessing reduction on CPUs with different speeds 

### ISSUE THREAD

**Issue by hcarlsso** [JuliaLang/julia#36171]
Following up my question on [discourse.julialang.org](https://discourse.julialang.org/t/parallel-reductions-on-cpus-with-different-speeds/40722), I basically want to do mapreduce on multiple nodes with different CPU speeds. For this problem [one should use](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.@distributed) 
```jula
@distributed [reducer] for var = range
    body
end
```
However, in the implementation of the  [`preduce`](https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/stdlib/Distributed/src/macros.jl#L263) function, the input range is split evenly over the workers before the execution. Thus, if one worker is slow, or a computation of the input range takes longer time, other workers are idle while that worker is struggling with its pre-allocated input. 

Another approach would be to use [Channels](https://docs.julialang.org/en/v1/manual/parallel-computing/#Channels-1), which almost have the solution in the manual. Here, each worker takes an  input when it is ready, reduces locally, and sends it back when everything is done. 
```julia
using Distributed
addprocs(3)

@everywhere function do_work(f, op, jobs, res)
    args = try
        take!(jobs)
    catch InvalidStateException
        # No work to do
        return nothing
    end

    v = f(args...)

    while true
        args = try
            take!(jobs)
        catch InvalidStateException
            # We are done
            break
        end
        v = op(v, f(args...))
    end
    put!(res, v)
end
function pmapreduce(f, op, itr; nbuf::Int = 100)

    jobs = RemoteChannel(()-> Channel(length(itr)))
    all_w = workers()[1:min(nworkers(), length(itr))]
    res = RemoteChannel(()-> Channel(length(all_w)))

    for pid in all_w
        remotecall(do_work, pid, f, op, jobs, res)
    end

    # Make jobs
    for job_arg in itr
        put!(jobs, job_arg)
    end
    close(jobs)

    # Collect results
    v = take!(res)
    if length(all_w) > 1
        for n in 2:length(all_w)
            v = op(v, take!(res))
        end
    end
    close(res)
    return v
end
@everywhere function f(n)
    println("Task sleeping: $(n) s")
    sleep(n)
    n
end

input = vcat([10], ones(8))
res = @time pmapreduce(f, +,  input)
```

Is there any specific reason for the even split of input in the current implementation? Otherwise, it would be nice to have a multiprocessing `mapreduce` that works as above.

**Comment by GregPlowman** [comment]
Similar issue: #23909

**Comment by hcarlsso** [comment]
> Similar issue: #23909

So it seems that there is a need for a function such as `pmapreduce`? Since non-parallel versions of the functions [`map`](https://docs.julialang.org/en/v1/base/collections/#Base.map), [`reduce`](https://docs.julialang.org/en/v1/base/collections/#Base.reduce-Tuple{Any,Any}), and [`mapreduce`](https://docs.julialang.org/en/v1/base/collections/#Base.mapreduce-Tuple{Any,Any,Any}) exists in the standard library, for me it would make sense to have parallel versions of these functions as well, and [`pmap`](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.pmap) is indeed implemented, as well  as `preduce`.

**Comment by hcarlsso** [comment]
> > Similar issue: #23909
> 
> So it seems that there is a need for a function such as `pmapreduce`? Since non-parallel versions of the functions [`map`](https://docs.julialang.org/en/v1/base/collections/#Base.map), [`reduce`](https://docs.julialang.org/en/v1/base/collections/#Base.reduce-Tuple%7BAny,Any%7D), and [`mapreduce`](https://docs.julialang.org/en/v1/base/collections/#Base.mapreduce-Tuple%7BAny,Any,Any%7D) exist in the standard library, for me it would make sense to have parallel versions of these functions as well, and [`pmap`](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.pmap) is indeed implemented, as well as `preduce`.

As an alternative to a pull request, I collected code for different implementations (see [here](https://github.com/JuliaLang/julia/issues/23909#issuecomment-338559523) and [here](https://stackoverflow.com/questions/51228889/how-do-i-do-parallel-mapreduce-in-julia)) of a potential `pmapreduce` in [ParallelMapReduce.jl](https://github.com/hcarlsso/ParallelMapReduce.jl).

**Comment by vtjnash** [comment]
Seems to be mostly a usage question, and already posted on discourse, so nothing left here to do
