### ISSUE TITLE
New "@optlevel 1" isn't (always) effective

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#36179]
For e.g. FFMPEG.jl or even `using FFMPEG_jll` only, and starting with `-O1` does make for faster startup, but when I add the equivalent lines (what I've been promoting...) I do not get any speedup:

```
(@v1.6) pkg> st
Status `~/.julia/environments/v1.6/Project.toml`
[..]
  [c87230d0] FFMPEG v0.3.0 `~/.julia/dev/FFMPEG`
  [b22a6f82] FFMPEG_jll v4.1.0+3 `~/.julia/dev/FFMPEG_jll`

module FFMPEG

if isdefined(Base, :Experimental) && isdefined(Base.Experimental, Symbol("@optlevel"))
    @eval Base.Experimental.@optlevel 1
end

println("Test")
```

**Comment by PallHaraldsson** [comment]
I see it now, even FFPMEG_jll has lots of dependencies, and e.g. one of is https://github.com/JuliaBinaryWrappers/x265_jll.jl that also benefits from the opt. treatment. It seems applying it to all PLL packages could help (I'll look more into it).

**Comment by KristofferC** [comment]
It does what it does. The effectiveness might vary among packages.
