### ISSUE TITLE
 Julia just exit without leaving any error message in the middle of package installation

### ISSUE THREAD

**Issue by eisthf** [JuliaLang/julia#36195]
All of sudden, I can't install any package.
If I try installing, Julia just exit in the middle without leaving any error message.
The following is all I see from the terminal.
```
E:\>julia
(@v1.4) pkg> add CSV
   Updating registry at `E:\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
```

I uninstalled Julia, deleted everything under .julia and restarted but the problem persists.

The symptom seems to be identical to this issue:
https://github.com/JuliaLang/julia/issues/29027

fbryandavies somehow managed to solve the issue, but I have no idea how to proceed. 

I tried other builds and found pkg installation is ok only with Julia 1.0.5. Other versions after that such as 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0-beta1 all fail.

It used to work well until a few days ago. It seems the issue occurs only on Windows PCs at the company office. Since these PCs' system configurations are remotely managed by IT department time to time, I suspect somehow some recent changes are conflicting with Julia; Pkg install works well on Windows PC at home. 

Here is my environment (since REPL or Pkg does not produce any output I can't give further detail):
```
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = E:\.julia
  JULIA_NUM_THREADS = 6
```

**Comment by AstraL777** [comment]
Im too dellet access after tomorrow, it's my fool, I'm so sorry

**Comment by eisthf** [comment]
This issue seems only related to Pkg.jl.
