### ISSUE TITLE
GenericIOBuffer seekend do not respect `seakable`flag

### ISSUE THREAD

**Issue by Arkoniak** [JuliaLang/julia#36204]
I am not sure whether it's a bug or intended behavior, but it looks like `seekend` function does not respect `seekable` flag: https://github.com/JuliaLang/julia/blob/master/base/iobuffer.jl#L263-L266

`seekstart` and `seek` throw errors if seekable is `false` as it can be seen from previous lines https://github.com/JuliaLang/julia/blob/master/base/iobuffer.jl#L250-L261

May be it is more consistent to define `seekend` for `IOBuffer` in the same way as `seekstart?
```julia
seekend(io::GenericIOBuffer) = seek(io, io.size+1)
```

**Comment by vtjnash** [comment]
It's intended, in that it's well-defined what it means to seek (skip really) to the (current) end of the stream. Not sure if anyone really needs that though.

**Comment by Arkoniak** [comment]
Thank you.
