### ISSUE TITLE
clean out .gitignore

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#36203]
I've noticed that there's a lot of junk in .gitignore that really shouldn't be there:

* `/*.tar.gz` 
* `/dist`
* `/dist-extras`
* `/julia.bat`
* `/oprofile_data`
* `/source-dist.tmp`
* `/source-dist.tmp1`
* `/perf*`
* `.DS_Store`
* `.idea/*`

A lot of this just doesn't make sense, some of it should be in people's global `.gitignore` files. It's hard to know though since different platforms generate different files that should be ignored. There's also a lot of `*.ext` type patterns that should be scoped more strictly inside of `src`, e.g.

**Comment by Keno** [comment]
> some of it should be in people's global `.gitignore` files

While I agree with this, what's the harm in keeping it? Might just make life slightly easier for a newcomer.

**Comment by TorchedSammy** [comment]
macos makes `.DS_Store` for (almost) every directory, i would keep it

**Comment by StefanKarpinski** [comment]
Yeah, I don’t mind those so much but why the heck are we ignoring `*.tar.gz` files?

**Comment by ViralBShah** [comment]
tar.gz files are created when you do `make binary-dist` and are fudging around with the build system. You can end up having a few of those around, and having them in `.gitignore` is quite nice.

I think the `.gitignore` looks ok, but feel free to reopen if necessary.
