### ISSUE TITLE
Grisu issue

### ISSUE THREAD

**Issue by isentropic** [JuliaLang/julia#36228]
@JeffBezanson perhaps could help.
I'm coming a long way from Plots.jl
https://github.com/JuliaPlots/Plots.jl/issues/1792 -> 
https://github.com/JuliaGraphics/Showoff.jl/issues/18 -> 

@michakraus figured out an MWE, I got it down to Grisu issue

I cannot tell if this is the intended behavior or not, but both of these packages would love to receive some help from more experienced users.

```
Base.Grisu.grisu(2.99999999999999956E-16/10.0^-16, Base.Grisu.FIXED, 18)
(19, 1, false)
Base.Grisu.grisu(2.9999999999999999E-16/10.0^-16, Base.Grisu.FIXED, 18)
(1, 1, false)
``

**Comment by isentropic** [comment]
Should the packages even use grisu?
Or are we supposed to use `round(x, sigdigits=5)`?

**Comment by JeffBezanson** [comment]
You should use grisu (now ryu) or printf if you want output with a specific number of digits. `round` just does a computation, and cannot by itself control how a value is printed.

These results don't look wrong to me --- if you want 2 or 4 digits, why are you passing 18 as the number of digits?

To make this more portable, I would switch to using printf, or at least switch to the new Ryu code so we can remove Grisu from Base. @quinnj Are you able to help with that?

**Comment by quinnj** [comment]
Help with removing grisu from Base? Yes. We just need to actually review https://github.com/JuliaLang/julia/pull/32859, which coincidentally makes the printf functionality _loads_ faster and would remove any need for packages to use float-printing internals directly (which I believe is why some packages reached into grisu in the past). cc: @StefanKarpinski for review.
