### ISSUE TITLE
a URL that stores the current nightly `VERSION`

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#36221]
I want to write a function that connects to the internet on a certain day and gets the latest nightly version. For that, I need a URL that stores this version in it.

Something like (which can run from any julia):
```julia
JuliaVersionNumber(v::VersionNumber) = v
function JuliaVersionNumber(v::String)
	if v == "nightly" || v == "latest"
		# return the VERSION from that URL
	end
end
```
```julia
julia> JuliaVersionNumber("nightly")
v"1.6.0-DEV.192"
```

Is there a way to add this to the nightly build-script?

One way is to program a cron job using `julia-setup` GitHub action, and run it using `nightly` option and then run `VERSION` and then upload that to a URL. But depending on the time of the day that the cron job runs, the nightly `VERSION` may get outdated after some hours. 

This is why I think it should be part of the same script that uploads the nightly binaries.

**Comment by yuyichao** [comment]
Just use, for example, https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz ?

**Comment by aminya** [comment]
I want to know the `VERSION`.

**Comment by yuyichao** [comment]
Why do you need it for

> gets the latest nightly version

? The hash is available in the tarball as the directory name so if you want to know which commit it is you can just use that, or even just run the binary you downloaded...

**Comment by aminya** [comment]
> Why do you need it for
>

In SnoopCompile, I have written a code that accepts different Julia versions and generates a file based on that. 
https://github.com/aminya/SnoopCompile.jl/blob/multios/docs/src/bot.md#2---call-snoop_bot-function

In my case, knowing up to the second decimal would suffice (like 1.6). This allows me to write something like the following:
```julia
 @static if v"1.2.0" <= VERSION <= v"1.2.9"
                        include("$precompiles_rootpath_rel/linux/1.2/precompile_TestPackage0.jl")
                        _precompile_()
#...
```
https://github.com/aminya/SnoopCompile.jl/blob/f859488367a8b1f5e070a9d7eaf6e4b601977d03/test/bot/bot.jl#L291

Currently, I only accept `VersionNumber`, but I want to allow user to say `nightly`.

**Comment by yuyichao** [comment]
> The code will run from some arbitrary Julia version. Downloading the tarball takes quite some time.

The goal of knowing the version is to download and run it right? So why is dowloading speed an issue? Don't you need to download the binary (that's the tarball I was talking about) and run it anyway?

**Comment by aminya** [comment]
> The goal of knowing the version is to download and run it right? So why is dowloading speed an issue? Don't you need to download the binary (that's the tarball I was talking about) and run it anyway?

No, the Julia code will not run try to download the nightly. It generates a Julia file based on the user input.

**Comment by aminya** [comment]
One way is to program a cron job using `julia-setup` GitHub action, and run it using `nightly` option and then run `VERSION` and then upload that to a URL. But depending on the time of the day that the cron job runs, the nightly `VERSION` may get outdated after some hours. 

This is why I think it should be part of the same script that uploads the nightly binaries.

**Comment by vtjnash** [comment]
We now have CI upload manifest files with this information. See PkgEval.jl for an API
