### ISSUE TITLE
`copyto!` breaking change in v1.5

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#36220]
```julia
using OffsetArrays

oa = fill(1, (3:5, 3:5))
copyto!(Array{Int,2}(undef, size(oa)), oa)

```

On v1.4: 
```
ERROR: BoundsError: attempt to access 3×3 Array{Int64,2} at index [3:5, 3:5]
Stacktrace:
 [1] throw_boundserror(::Array{Int64,2}, ::Tuple{OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}},OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}}}) at ./abstractarray.jl:537
 [2] checkbounds at ./abstractarray.jl:502 [inlined]
 [3] copyto!(::Array{Int64,2}, ::OffsetArray{Int64,2,Array{Int64,2}}) at ./multidimensional.jl:959
 [4] top-level scope at none:0
```
via a dispatch to https://github.com/JuliaLang/julia/blob/44fa15b1502a45eac76c9017af94332d4557b251/base/multidimensional.jl#L958-L965

whereas on v1.5 it does not throw.

https://github.com/JuliaLang/julia/commit/f345c5f3f81291989e80822b86710de712018069 may be the cause.

**Comment by timholy** [comment]
The new behavior is correct according to `copyto!`'s docstring, which is typically the authoritative source. I haven't dug into the other issue, but it indeed looks like a bug.

**Comment by JeffBezanson** [comment]
From triage: this is ok for `copyto!`, but not for `convert`, since an `OffsetArray` is not `==` to the same data inside an `Array`. We need to add a check to `convert`.

**Comment by KristofferC** [comment]
Bump, anyone looking at this?

**Comment by timholy** [comment]
The hard question is whether `Array(OA)` should throw an error or just `convert(Array, OA)`. I favor throwing an error for both, but it is not obvious.
