### ISSUE TITLE
`similar` to take array type and not array instance for first argument

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#36241]
`Array{Int64}(undef, 3)` is a great way to construct an uninitialized `Array` of length 3.
If there were a definition that allowed e.g. `undef(Int64, Base.OneTo(3))` to mean the same thing, then `OffsetArrays.jl` could define a method to allow `undef(Int64, 0:2)`

Currently, as far as I know, there's no shorter way than https://github.com/JuliaArrays/OffsetArrays.jl/blob/7294f3dcab6e6117b15eea3b98ce2c2175d08194/src/OffsetArrays.jl#L129 to accomplish this.

**Comment by mcabbott** [comment]
You can write `similar(1:1, 2:4)` and `similar(1:1, Float64, Base.OneTo(3))`.

**Comment by goretkin** [comment]
Ah, so there is a short way. Thank you!

Now I'm being greedy, but I don't really like the `1:1`. And if I wanted to back it by another array, e.g. `similar(BitArray([false]), Bool, (2:4,))`, I don't really like that a value of the array type needs to be constructed.

Is there a reason not to define e.g.
`similar(::Type{BitArray}, T::Type{Bool}, dims::Dims) = BitArray(undef, dims)`
instead of (or maybe in addition to)
`similar(B::BitArray, T::Type{Bool}, dims::Dims) = BitArray(undef, dims)`

I didn't look at every method, but it seems like the value of the first argument might not be needed for this specific signature.

**Comment by mcabbott** [comment]
Yes I'm not sure why `similar` needs an example not the type. I guess you can write `similar(1:2 .== 3, 4:5)` but the intention is less and less obvious.

**Comment by goretkin** [comment]
looks like there are definitions of this already. wonderful!

```julia
julia> similar(BitArray, Base.OneTo(3))
3-element BitArray{1}:
 0
 0
 0

julia> similar(Array{Int64}, (Base.OneTo(3),))
3-element Array{Int64,1}:
 4550507152
 4578859488
 4550507184

julia> similar(BitArray, (2:4,))
3-element OffsetArray(::BitArray{1}, 2:4) with eltype Bool with indices 2:4:
 0
 0
 0

julia> similar(Array{Int64}, (2:4,))
3-element OffsetArray(::Array{Int64,1}, 2:4) with eltype Int64 with indices 2:4:
          0
 4294967296
          0
```
