### ISSUE TITLE
1.4.2 slower than 1.5, 1.6. What happened?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#36258]
Is there an explanation? https://discourse.julialang.org/t/comparison-of-windows-10-and-linux-julia/41227

And why does the Windows version perform better than x86 Linux?

Thanks.

P

**Comment by KristofferC** [comment]
Perhaps some. OpenBLAS version bump helped this case. Not sure what use an issue about this is. We make things faster all the time :p

**Comment by PetrKryslUCSD** [comment]
Well, the thing is it'll be good to understand why it happened. Knowing that might allow us to do more optimization. So, is there a bump in the OpenBLAS version between 1.4.2 and 1.5?

Also, why is the Windows solve faster than on Linux?

**Comment by KristofferC** [comment]
Bisecting julia to find where the performance change happened is probably  like the best way to figure out what caused it.

**Comment by PetrKryslUCSD** [comment]
Right. Don't these changes occur at the same time in Julia on all platforms? Why would the speed up on Windows be so large whereas it is modest on Linux?
https://discourse.julialang.org/t/comparison-of-windows-10-and-linux-julia/41227/3

**Comment by StefanKarpinski** [comment]
Unless the performance on 1.4.2 is a regression from 1.4.1 or 1.4.0 this seems like not an issue, but if there was a performance regression from those earlier 1.4.x release, it would be good to know.

**Comment by PetrKryslUCSD** [comment]
I can test it, but I don't have access to anything other than 1.3.1 (https://julialang.org/downloads/oldreleases/). Is that relevant?

**Comment by StefanKarpinski** [comment]
It's not a regression unless there was an earlier version that was faster.

**Comment by PetrKryslUCSD** [comment]
Understood. It is just that you called for 1.4.0 or 1.4.1. I thought there was a reason.

**Comment by PetrKryslUCSD** [comment]
Sparse solve: 1.3.1 Windows 10 is around 29 seconds, so roughly the same speed as 1.4.2. WSL2 runs at 24 seconds, which is also roughly the same speed is 1.4.2. So, for some reason the sparse solve runs at twice the speed on 1.6 compared to 1.4.2, and there is no regression between those versions.

Nevertheless, it might be worthwhile to figure out why this is so. If this was not an isolated spot that was slow in 1.4.2, there could be potentially another place that could be sped up.

**Comment by timholy** [comment]
Have you profiled? That's usually one of the first things to do when looking for performance opportunities.

**Comment by PetrKryslUCSD** [comment]
Hi Tim. Not yet, so far I've only run the comparisons.
