### ISSUE TITLE
Error with optional argument in anonymous function defined in macro

### ISSUE THREAD

**Issue by zsunberg** [JuliaLang/julia#36272]
In Julia 1.5.0 beta 1, the following fails:
```julia
macro m()
    :((a, b=1) -> a*b)
end
@m()(1)
```
with
```
ERROR: UndefVarError: b not defined
Stacktrace:
 [1] (::var"#1#2")(::Int64, ::Int64) at ./REPL[1]:3 (repeats 2 times)
 [2] top-level scope at REPL[1]:3
```

The reason I want to do this is here: https://github.com/JuliaPOMDP/POMDPs.jl/blob/609fe87094d4b1b01993deb0514565450266547f/src/generative.jl#L189. A workaround is to name the function.

**Comment by zsunberg** [comment]
Does not fail in julia 1.0.3. Fails in Julia 1.4.1

**Comment by simeonschaub** [comment]
That's definitely a bug with macro hygiene:
```
julia> @macroexpand @m
:((var"#14#a", b = 1)->begin
          #= REPL[1]:2 =#
          var"#14#a" * Main.b
      end)
```
Seems like hygiene is not aware of the optional argument `b` and so the `b` in the function body is interpreted as a global.
