### ISSUE TITLE
Coverage misses on macros that work on functions

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#36283]
Coverage data generated by Julia misses the first line of the head of the function definition:
```jl
using TypeTransform
@transform function foo(a, b::allsubtypes(A))
    println("a new method")
end
```

Other examples:
https://codecov.io/gh/aminya/AcuteML.jl/src/master/src/xmlutils/findcontent.jl#L45
https://github.com/JuliaCI/Coverage.jl/issues/269

**Comment by vtjnash** [comment]
Possibly fixed now, this issue is > 18 months old

**Comment by kellertuer** [comment]
I still have the same problem for example here:
https://codecov.io/gh/JuliaManifolds/Manifolds.jl/src/kellertuer%2Fdecorator-adaptions/src/groups/group.jl#L470
One can see that the function itself is run but the macro line is still be marked as uncovered.
