### ISSUE TITLE
Pkg.add("IJulia") fails on clone

### ISSUE THREAD

**Issue by iisharankov** [JuliaLang/julia#36295]
Trying to install Julia for the first time to use withing a Jupyter Notebook. Installed via package manager on Manjaro KDE, and ran Julia. The repo clone fails and I can't seem to find a  forum that has a viable solution.

```
julia> import Pkg

julia> Pkg.add("IJulia")
    Cloning default registries into `~/.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:SSH, error authenticating: no auth sock variable)
Stacktrace:
 [1] top-level scope at REPL[2]:1
caused by [exception 1]
GitError(Code:ERROR, Class:SSH, error authenticating: no auth sock variable)
Stacktrace:
 [1] top-level scope at REPL[2]:1
```

Firewall shouldn't be an issue, on home network and I know it's not blocked.

**Comment by Micket** [comment]
Sounds like this https://github.com/ropensci/git2r/issues/296 ?

**Comment by fingolfin** [comment]
Can this be closed now?
