### ISSUE TITLE
Strange race condition while running conjugate gradients in multithreaded code

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#36297]
I've been trying to debug the following race condition for a while now with little success, and I'm posting here just in case this unconvers a bug in the threading runtime. 

Here's how to reproduce it on Julia 1.4 (same behaviour on master):
1. Add the package Circuitscape with the branch "RA/mt" 
2. Start Julia with multiple threads

Then run: 
```julia
foo = Vector{Any}()
buzz = Ref{Any}()
using Base.Threads
@show nthreads() # shows threads
using Circuitscape
cd("~/.julia/dev/Circuitscape/test")
compute(test_problem("sgVerify1.ini"))
```

Now, if you enter `fetch.(buzz[])` at the REPL, you should see a few vectors, some of which have NaN's in them, which is incorrect. If you do the above steps but with single threaded julia, you should see proper floating point values, which are expected.

I've tried to obtain an `rr` recording as well, but for some puzzling reason, I cannot reproduce this race condition using `rr`. The command I've been running: 
`JULIA_NUM_THREADS=4 /opt/rr/bin/rr record --chaos --num-cores=4 /data/ranjanan/julia/usr/bin/julia-debug`

Any help with this to understand the underlying issue would be greatly appreciated. 

cc: @Keno @vchuravy

**Comment by Keno** [comment]
```
typeof(cmap) = [ Info: 2020-06-15 15:49:29 : Time taken to write voltage maps = 0.000110052 seconds
type GraphData has no field cumArray{Float64,2}
Stacktrace:
```

Can you provide an exact Project/manifest?

**Comment by ranjanan** [comment]
Yes, that error is expected. You should still be able to look at `fetch.(buzz[])` and see NaN's. 
Project.toml: 
```
[deps]
Circuitscape = "2b7a1792-8151-5239-925d-e2b8fdfa3201"
```

**Comment by Keno** [comment]
Ok, I can reproduce this. Looks like a data race. I'm thinking ThreadSanitizer might be the next step.

**Comment by ViralBShah** [comment]
@ranjanan Can you point to where the threaded part of the code is?

**Comment by antoine-levitt** [comment]
Does this use FFTs? https://github.com/JuliaMath/FFTW.jl/issues/141 and comments in it might be relevant

**Comment by ViralBShah** [comment]
No FFTs in here. It's all sparse matrix stuff.

**Comment by ranjanan** [comment]
The multi-threaded code in question is [here.](https://github.com/Circuitscape/Circuitscape.jl/blob/RA/mt/src/core.jl#L175-L200)

**Comment by ViralBShah** [comment]
@Keno Is this an issue in the user code or an issue in our multi-threading system? If @ranjanan has to use ThreadSanitizer, is there any documentation on how one might go about doing it?

**Comment by Keno** [comment]
Probably an issue in the user code. ThreadSanitizer can be turned on in Make.user (see here: https://github.com/JuliaLang/julia/pull/36929). Note though that any external libraries that could be participating in the data race need to be built with tsan enabled also, which we currently don't really have a good way to do.

**Comment by ViralBShah** [comment]
This codebase is primarily native Julia stuff.

**Comment by ViralBShah** [comment]
I believe we debugged this to a race condition in the user code in AlgebraicMultigrid.jl.
