### ISSUE TITLE
1[end, end] errors: no multiarg lastindex for Numbers

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#36311]
while silly, we should be constistent
```julia
julia> 1[1,1]
1

julia> 1[end]
1

julia> [1][end, end]
1

julia> 1[end, end]
ERROR: MethodError: no method matching lastindex(::Int64, ::Int64)
```

**Comment by mgautam98** [comment]
I would like to work on this issue

**Comment by simeonschaub** [comment]
You would just have to add a method `lastindex(::Number, ::Int)` [here](https://github.com/JuliaLang/julia/blob/2749582ad43b70e6103c837a0949948b380cc61e/base/number.jl#L71), probably adopt the bounds check from `size` and `axes` right above and then just return `1`. Probably also a good idea to add a method to `firstindex` with the same defintion.

**Comment by mgautam98** [comment]
Thanks for the pointer @simeonschaub
