### ISSUE TITLE
Feature Request: Spack spec for Julia

### ISSUE THREAD

**Issue by JBlaschke** [JuliaLang/julia#36316]
NERSC is switching to Spack (https://github.com/spack/spack) to provide a lot of its software. Naturally, I think that this is a great opportunity to build the latest version of Julia for NERSC users -- but I've been seeing mixed results so far (cf. also: https://github.com/spack/spack/issues?q=is%3Aissue+is%3Aopen+julia)

One solution would be for the Julia developers to build a Julia spack "spec" (https://spack.readthedocs.io/en/latest/basic_usage.html#specs-dependencies), which different HPC centers could derive from, for their specific systems. This will decrease the friction associated with configuring Julia builds for HPC systems, hopefully increasing the uptake of Julia among leading HPC centers.

I'm available as a NERSC contact to any Julia devs who want to give this a shot.

**Comment by Keno** [comment]
I would recommend just repackaging the generic binaries for now. They are built quite carefully and are known to run well on Cori.

**Comment by JBlaschke** [comment]
Thanks @Keno  -- when you say that they are known to "run well on Cori" can you point me to the tests? I wouldn't mind replicating this on Cori as a validation step durin our software upgrades.

Also can you point me to documentation how they where built? I am particularly concerned with if the build uses MKL -- I can worry about things like MPI myself.

**Comment by Keno** [comment]
Maybe get in touch with @rcthomas for the history of Julia installations at NERSC. We're fairly close to having microarchitecture specific native dependencies, which should be the last part you need. Building from source won't help with that though.

**Comment by JBlaschke** [comment]
Now that's fancy! OK I just spoke with @rcthomas and we're gonna use the binaries. Thanks very much @Keno

**Comment by Keno** [comment]
> Now that's fancy!

https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/4 is the issue to follow for that work.

**Comment by JBlaschke** [comment]
Thanks! I'll keep an eye on that.
