### ISSUE TITLE
LLVM-9.0.1 doesn't recognize AVX-512 in macOS

### ISSUE THREAD

**Issue by YingboMa** [JuliaLang/julia#36329]
See https://github.com/SciML/DifferentialEquations.jl/issues/623#issuecomment-644739630

@maleadt mentioned that https://github.com/llvm/llvm-project/commit/82921bf2baed96b700f90b090d5dc2530223d9c0 might fix it. I wonder if we can patch Julia's LLVM to make it generate more efficient code for new Apple hardware.

**Comment by yuyichao** [comment]
We are not using that code. You need to conditionally make https://github.com/JuliaLang/julia/blob/43fd66c8ac9010a193fbcf870ce731b99dd38b4f/src/processor_x86.cpp#L548 `bool hasavx512save = hasavx;` instead on mac. You'll also need to patch openblas similarly.
