### ISSUE TITLE
Ctrl+Q stopped working for stack traces etc.

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#36340]
After #35556, Ctrl+Q works only if the method table is shown via `display(d::REPLDisplay, mime::MIME"text/plain", x)`.  So, for example, Ctrl+Q still works with `methods(Base._in)` but not with `?Base._in`.  Ctrl+Q also does not work with stacktraces anymore.

I still think #35556 is a good approach because it makes `show` on method table thread-safe.  So, I'd suggest to keep #35556 and somehow find a way to use the display system for the cases where Ctrl+Q does not work.  But I'm also OK with reverting #35556 if Ctrl+Q on, e.g., stacktraces is essential for people and the fix is hard.

cc @simeonschaub

**Comment by KristofferC** [comment]
> if Ctrl+Q on, e.g., stacktraces is essential for people and the fix is hard.

well "essential" is maybe a bit too much but I like it...

**Comment by tkf** [comment]
Right, "essential" was probably a bit too strong. I just wanted to mention that it makes sense to consider across multiple dimensions like usability, how easy the fix would be, thread-safety, and so on.

**Comment by tkf** [comment]
> it makes `show` on method table thread-safe

Actually, I just realized that this is not entirely correct since I can pass `IOContext` across threads.  But we can make it so by using one array per-thread and avoiding global state still helps.

**Comment by simeonschaub** [comment]
I think I have a fix for this

**Comment by simeonschaub** [comment]
The helpmode case is a bit difficult, because right now, the methods get written into an `IOBuffer` first, so they are not aware of the `IOContext`.
