### ISSUE TITLE
Weirdness (bug) in kernel function `jl_new_task`

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#36361]
In [src/task.c](https://github.com/JuliaLang/julia/blob/master/src/task.c), function [`jl_new_task`](https://github.com/JuliaLang/julia/blob/d6d5208d66be637543232bec4b0c79b2811ea1c6/src/task.c#L546) does the following:
```C
...
    if (ssize == 0) {
        ...
    }
    else {
        // user requested dedicated stack of a certain size
        if (ssize < MINSTKSZ)
            ssize = MINSTKSZ;
        t->bufsz = ssize;
        t->stkbuf = jl_alloc_fiber(&t->ctx, &t->bufsz, t);
        if (t->stkbuf == NULL)
            jl_throw(jl_memory_exception);
    }
...
    t->stkbuf = NULL;
```

So if `ssize != 0` then `t->stkbuf` is allocated and care is taken to ensure it's non-zero, but then later it gets zeroed out unconditionally (no `return` or conditional statement statement comes in between, so I really think this is what happens).

This looks like a bug, presumably `t->stkbuf`. Even if it is intentional, then I'd think the first use of `t->stkbuf` inside the `else {...}` block should be rather replaced by a local variable, and a comment should be added why this makes sense.

**Comment by sgaure** [comment]
The pointer is stored in the context structure by jl_alloc_fiber(), so a local variable could have been used. It is merely slightly confusing, perhaps a leftover from an earlier version.

**Comment by fingolfin** [comment]
@sgaure Hmm, OK, but then something still doesn't up for me, perhaps you can clear it up for me: `jl_alloc_fiber` unconditionally allocates a new stack, right? Now these are all places I could find that set `stkbuf`:

1. in `save_stack`
```C
    if (lastt->bufsz < nb) {
        buf = (void*)jl_gc_alloc_buf(ptls, nb);
        lastt->stkbuf = buf;
        lastt->bufsz = nb;
    }
```

2. in `jl_finish_task`
```C
    if (t->copy_stack) // early free of stkbuf
        t->stkbuf = NULL;
```

3. in `ctx_switch`:
```C
        if (t->stkbuf == NULL) {
            t->stkbuf = jl_alloc_fiber(&t->ctx, &t->bufsz, t);
```

4. in `jl_new_task` the two I listed at the top of this issue

5. in `jl_init_root_task`:
```C
    if (always_copy_stacks) {
        ptls->current_task->copy_stack = 1;
        ptls->current_task->stkbuf = NULL;
        ptls->current_task->bufsz = 0;
    }
    else {
        ptls->current_task->copy_stack = 0;
        ptls->current_task->stkbuf = stack;
        ptls->current_task->bufsz = ssize;
    }
```

6. in `jl_release_task_stack` and `sweep_stack_pools` inside `src/gc-stacks.c` there is code which may reset it to `NULL`


Looking at these, it seems that `task->stkbuf` will never point at the stack allocated in that particular instance (except perhaps for root tasks, via the code in `jl_init_root_task` listed under 5, for which I did not analyze the callers). So, wouldn't `ctx_switch` then allocate *another* stack, because `t->stkbuf` would still be `NULL`?

What am I missing?


While at it, I am also wondering whether it is OK that `save_stack` uses `jl_gc_alloc_buf` instead of `jl_malloc_stack` (which is what the various `jl_alloc_fiber` implementations all seem to use)? (Clearly I don't understand this code, so my apologies if this is a really stupid question. It just stood out to me while collecting the snippets listed above)
