### ISSUE TITLE
Passing a parameter from a parametric parameter to an abstract parametric type

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/julia#36377]
Hi,

This issue stems from a question I asked on Julia Slack and @jakobnissen, who was helping me (thanks again!), thought it was worth submitting an issue about it.

I have an existing parametric type of the form `E{S,C}` and an abstract parametric type of the form `I{S,C}`.

I was trying to define a new parametric subtype `CS` of `I`. I initially implemented it like

```julia
struct CS{ES,EC,S} <: I{S,EC}
```

where `ES` and `EC` are parameters of the existing `E`. 

Then, I felt it would be logically more clear if instead of sticking `ES` and `EC` from `E` directly as parameters of `CS`, if I just made `E{ES,EC}` a parameter of `CS`. Something like

```julia
struct CS{E{ES,EC},S} where {ES,EC,S} <: I{S,EC}
```

Unfortunately, it seems this syntax is unavailable.

@jakobnissen commented:

> I think thatt's impossible. A shame, it would make type signatures for things like static arrays and subarrays much more concise.

He couldn't find an issue related to this and, after asking if it made sense, he said it would make sense to submit an issue so here you go :)

I don't know the ramifications to static arrays or subarrays, but it would make my code a little cleaner I think if this syntax were available. Are there any existing issues related to this that we've missed?

Edit: The more I look at it, the more I think 

```julia
struct CS{E{ES,EC},S} where {ES,EC,S} <: I{S,EC}
```

should be valid syntax so I'm almost certain this has been discussed. To my eye, it seems perfectly consistent with what we do with methods.

Edit^2: Or maybe

```julia
struct CS{E{ES,EC},S} <: I{S,EC}
```

could just work without the `where` 🤔

**Comment by JeffBezanson** [comment]
This would probably be difficult to implement, since it breaks fundamental assumptions about the structure of types. For field types, it can be implemented on top of #18466 (by calling a function to pull the parameter out of `E` when the first parameter to `CS` becomes known), but the supertype is trickier.
