### ISSUE TITLE
NFC normalisation of identifiers prevents some latex hints

### ISSUE THREAD

**Issue by knuesel** [JuliaLang/julia#36378]
For example `?ẋ` doesn't print the expected message `"ẋ" can be typed by x\dot<tab>`, because the combining mark is normalized to u1e8b.

I think a possible fix would be to use `Unicode.normalize(s, :NFD)` here:
https://github.com/JuliaLang/julia/blob/f6d34c3c32c535422491bfe980b1ebdb6bc123db/stdlib/REPL/src/docview.jl#L336

**Comment by StefanKarpinski** [comment]
cc @stevengj

**Comment by stevengj** [comment]
Yes, I think we should definitely do `s = Unicode.normalize_string(s, :NFD)`  in `repl_latex`.

**Comment by knuesel** [comment]
@stevengj gladly, I'll do it later in the day.

**Comment by knuesel** [comment]
@stevengj is there anything else to do on my side?
