### ISSUE TITLE
Incorrect compiler optimizations

### ISSUE THREAD

**Issue by antonpeshkov** [JuliaLang/julia#36388]
I assume this is a highly critical bug as it produce incorrect results without any crash in the program, and as such will pass undetected in a lot of cases.

I tried to reduce the size of my code as much as possible for this bug report, it could probably be reduced more, but the bug is very clear and reproducible. The bug appears both on the LTS Julia version 1.0.5 and the latest available Julia version on my compute cluster 1.3.1.

The submitted files include the main program “rattlers_adjusted_pressure_bug_report.jl” which should be run. Two associated functions in separate files “contacts_stresses.jl” and “remove_rattlers.jl”. The bad things mostly happening in the latter function. The first function is non-important for this bug report. Also included a data file “dump3000000.dat” from which data is read at the beginning of the program.

[Julia_bug_report.zip](https://github.com/JuliaLang/julia/files/4815770/Julia_bug_report.zip)

Nothing important to this bug report happens before line 45 of the main program.

The function “contact_stresses” produce an array “num_contacts” on line 41 of the main program. I make a copy “temp_contacts” of this array, which I pass to the function “remove_rattlers” on line 56 of the main program. Inside the “remove_rattlers” program I make another copy “num_contacts_nr” of this array. For this last copy I change both the values (line 44-45 of “remove_rattlers”) of the array and the size of the array (line 66 of “remove_rattlers”). However, the original arrays “num_contacts” and “temp_contacts” should never change; nor the size nor the values.

To show that the compiler perform incorrect optimizations I ask to input a variable “mv” on the terminal.

First, you should comment line 53 of the main program and uncomment line 54. In this way compiler, optimizations are not prohibited and the compiler will apparently falsely assign “num_contacts”, “temp_contacts” and “num_contacts_nr” to the same memory pointer. The entered value of “mv” does not matter. You will see that after the run of “remove_rattlers” function, both “num_contacts” and “temp_contacts” will have their values changed to the same as “num_contacts_nr”. While this should of course not happen. Interestingly the size of the arrays is not changed (I naively assume that this happens because all three copies of the array are pointing to the same chunk of memory until the moment when “num_contacts_nr” is reduced in size, at which time a new memory chunk is allocated).

By commenting line 54 and uncommenting line 53 I prevent the compiler from performing the optimization of “temp_contacts” by forcing it to assign new memory for it. When prompted for variable input, just enter “1” which in theory should not change the output of the program. However, we now see that “num_contacts” is not changed at all as it should. “temp_contacts” have its values changed as before without any change in size.

versioninfo()
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)

**Comment by Keno** [comment]
> Inside the “remove_rattlers” program I make another copy “num_contacts_nr” of this array

That's not how copies work in Julia. You're just creating another reference to the same array. You can use `copy` to make an explicit copy, or you can use `.=` to assign into the space that you allocated on the previous line. Since you're making this assumption, I assume you're coming from a MATLAB background. If so, I recommend checking out the noteworthy differences section of the manual: https://docs.julialang.org/en/v1/manual/noteworthy-differences/. This confusion is item #2 in the MATLAB section.

**Comment by antonpeshkov** [comment]
Thanks, I understand now. Though, using the equal sign for a pointer assignment make no sense to me, hope there is some reason behind this strange syntax.

**Comment by StefanKarpinski** [comment]
That’s the syntax used in most programming languages.

**Comment by antonpeshkov** [comment]
Well may be. As a scientist for me "most languages" are Fortran and Matlab. But, it is what it is, no point of discussing it now. Thank you for help.
