### ISSUE TITLE
1.5: Surprising new pointer behaviour with adjoints and views

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#36402]
This seems wrong to me:
```julia
julia> A = randn(5,3);

julia> V = view(A',:,2:4)
3×3 view(::Adjoint{Float64,Array{Float64,2}}, :, 2:4) with eltype Float64:
 -0.6594    -0.124149   0.492452
  1.20338    0.224742  -0.0431509
 -0.425888   0.725104   0.976229

julia> Base.unsafe_load(pointer(V))
0.49245221105087544
```

I expected it to return the pointer to `V[1,1]`, not `V[1,end]`. 

Related to https://github.com/JuliaLang/julia/pull/35929 

@mbauman

**Comment by mbauman** [comment]
Ah, yes.  Our `SubArray` is implicitly assuming strided parents are both contiguous and column-major:

https://github.com/JuliaLang/julia/blob/b59417235f56f251a74fb2878267238155b19f75/base/subarray.jl#L401-L402

That needs to be doing a strides computation.
