### ISSUE TITLE
`sinpi` errors for some `Rational{<:Unsigned}` values

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#36410]
For noticed this for some values of type `Rational{UInt64}` and `Rational{UInt128}`:
```julia
julia> sinpi(Rational{UInt64}(3,2))
ERROR: OverflowError: 3 - 4 overflowed for type UInt64
[...]

julia> sinpi(Rational{UInt128}(3,2))
ERROR: OverflowError: 3 - 4 overflowed for type UInt128
[...]
```

**Comment by simeonschaub** [comment]
It's probably easiest to just promote to `Rational{signed(T)}` for `Rational{T} where T<:Unsigned`, as the current algorithm reduces the domain to `[-1, 1]` and I don't think we want to change our kernels for `sin` and `cos`. (We should probably have a `Base.Checked.checked_signed` and maybe also implement `signed` for `Rational`s for that.)

**Comment by simeonschaub** [comment]
It turns out, it's not quite as simple, but I will take a crack at it tomorrow.

**Comment by simeonschaub** [comment]
This also doesn't just affect `Rational{<:Unsigned}`, for example:
```
julia> sinpi(1//typemax(Int))
ERROR: OverflowError: 2 * 9223372036854775807 overflowed for type Int64
[...]
```
We probably should widen the integer types then during reduction, if we want to keep all the accuracy.

**Comment by adienes** [comment]
seems fixed on master now
