### ISSUE TITLE
Generate random numbers with non-integer type dimensions 

### ISSUE THREAD

**Issue by azev77** [JuliaLang/julia#36417]
When we use: `rand([rng=GLOBAL_RNG], [S], [dims...])`
```julia
rand(10)             # works 
rand(Int(200/20))    # works
rand(200/20)         # "ArgumentError: Sampler for this object is not defined"
``` 
The issue is that the dimension type needs to be an integer.  
Would it be possible to convert dimension from from `Float64` to `Int64`? 

So: `rand(S, dims) = rand(S, Int.(dims) )`

For example:
```julia 
rand(-2:.5:3.5, (3,7.0) )  # currently gives error 
# would become
rand(-2:.5:3.5, Int.((3,7.0)) )
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/35969. Use `÷` in your case and you won't have any floating point to start with.
