### ISSUE TITLE
Inconsistency with BigFloat

### ISSUE THREAD

**Issue by mgautam98** [JuliaLang/julia#36419]
There is some inconsistency with BigFloat when given NaN
```

julia> Float16(NaN) === Float16(NaN)
true
julia> Float32(NaN) === Float32(NaN)
true
julia> Float64(NaN) === Float64(NaN)
true
```
But 
```
julia> BigFloat(NaN) === BigFloat(NaN)
false
```

**Comment by simeonschaub** [comment]
This is only because `BigFloat` contains a pointer, and therefore separately constructed `BigFloat` instances are always distinct under `===`. This doesn't just affect `NaN`, but any `BigFloat` values, for example:
```
julia> BigFloat(42) === BigFloat(42)
false
```

**Comment by mgautam98** [comment]
Okay 👍 Its not an issue then. I am closing it.

**Comment by mgautam98** [comment]
So there is no way to compare NaNs for BigFloat?

**Comment by simeonschaub** [comment]
There is `isequal` for that:
```
julia> isequal(BigFloat(NaN), BigFloat(NaN))
true
```

**Comment by KristofferC** [comment]
Better to use `isnan`.

**Comment by mgautam98** [comment]
Isn't `isequal(Float16(NaN), Float64(NaN))` too flexible.

**Comment by KristofferC** [comment]
No, that is intended.

> `isequal` treats all floating-point NaN values as equal to each other,
