### ISSUE TITLE
Feature Request: Add `map!(f, x)` to work as `map!(f, x, x)`

### ISSUE THREAD

**Issue by Ellipse0934** [JuliaLang/julia#36432]
Currently we have `map(f, c...)` which applies map to a collection and when the map is supposed to store to a container rather than returning a new one we use `map!(f, dest, c...)`. However, when we have a single container over which we are supposed to apply map, `map!(f, x)` syntax makes sense. Currently, we do `map!(f, x, x)`.

Example
```julia
julia> x = [1., 2, 3]
julia> map!(sqrt, x)
3-element Array{Float64,1}:
 1.0
 1.4142135623730951
 1.7320508075688772
```

**Comment by rfourquet** [comment]
Dup of #31677. `map!(f, x)` was deprecated, and `map!(f, x)` could also mean fill destination `x` with repeated applications of "nullary" `f()` (call of `f` with 0 arguments).

**Comment by Albert55554** [comment]
Like to notice my features
