### ISSUE TITLE
Inference discards bounds on abstract parameters

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#36454]
Apologies, I'm sure this must have been reported before but a search didn't pick it up.

There appear to be cases where it would be "easy" to preserve bounds on abstract types. One that comes up a lot in my invalidation-squashing is `Iterators.Stateful`:

```julia
julia> code_typed(Iterators.Stateful, (AbstractString,))
1-element Array{Any,1}:
 CodeInfo(
1 ─ %1 = invoke Base.Iterators.approx_iter_type($(Expr(:static_parameter, 1))::Type{T} where T)::Type
│   %2 = Core.apply_type(Base.Iterators.Stateful, $(Expr(:static_parameter, 1)), %1)::Type{Base.Iterators.Stateful{_A,_B}} where _B where _A
│   %3 = Base.convert($(Expr(:static_parameter, 1)), itr)::Any
│   %4 = Core.fieldtype(%2, 2)::Type{var"#s428"} where var"#s428"<:(Union{Nothing, _B} where _B)
│   %5 = Base.Iterators.iterate(itr)::Any
│        Core.typeassert(%5, %1)::Any
│   %7 = Base.convert(%4, %5)::Any
│   %8 = %new(%2, %3, %7, 0)::Base.Iterators.Stateful{_A,_B} where _B where _A
└──      return %8
) => Base.Iterators.Stateful{_A,_B} where _B where _A
```
Given the definition https://github.com/JuliaLang/julia/blob/d762e8c23538d745389a9ca959a90a769c864ce7/base/iterators.jl#L1243-L1246 it would naively seem fairly straightforward to retain `_A<:AbstractString`.

**Comment by martinholters** [comment]
The code to fix this is all there it seems, just disabled:

https://github.com/JuliaLang/julia/blob/6185d24ac34a6b586ce6894b39a537cd333f9364/base/compiler/tfuncs.jl#L1100-L1123

If this came up in your invalidation hunt, maybe it's time to reconsider this?

**Comment by timholy** [comment]
Nice find. It's a difficult design decision; on one hand, doing more accurate inference makes inference slower. On the other hand, doing more accurate inference reduces the "vulnerability" of code to invalidation because fewer MethodInstances end up having `mt_backedges` to `Any`-instances of their dependent methods. Thereby, investing in better inference at the outset might save inference in the long run.

It's quite difficult to come up with reasonable benchmarks for these things, since it depends entirely on what new methods you define. Therefore what works in practice is a bit of a cultural issue of which packages often get used in which combinations.

**Comment by ChrisRackauckas** [comment]
Bump this up to triage to reconsider given the many changes to precompilation and the increased cost of invalidations?

**Comment by timholy** [comment]
I think that's a good idea, but probably first someone should collect some data to bring to the discussion.

**Comment by gbaraldi** [comment]
Triage thinks that, as Tim said, this probably needs more data for a more informed decision.

**Comment by vtjnash** [comment]
code is enabled now
```
julia> code_typed(Iterators.Stateful, (AbstractString,))

1-element Vector{Any}:
 CodeInfo(
    @ iterators.jl:1452 within `Stateful`
1 ─ %1  = $(Expr(:static_parameter, 1))::Type{T} where T<:AbstractString
│   %2  = invoke Base.Iterators.approx_iter_type(%1::Type)::Type
│   @ iterators.jl:1453 within `Stateful`
│   %3  = $(Expr(:static_parameter, 1))::Type{T} where T<:AbstractString
│   %4  = Core.apply_type(Base.Iterators.Stateful, %3, %2)::Type{Base.Iterators.Stateful{T, T1}} where {T<:AbstractString, T1}
│   %5  = $(Expr(:static_parameter, 1))::Type{T} where T<:AbstractString
│   %6  = (itr isa %5)::Bool
└──       goto #3 if not %6
2 ─       goto #4
3 ─ %9  = $(Expr(:static_parameter, 1))::Type{T} where T<:AbstractString
└── %10 = Base.convert(%9, itr)::Any
4 ┄ %11 = φ (#2 => itr, #3 => %10)::Any
│   %12 = Core.fieldtype(%4, 2)::Type{<:Union{Nothing, T} where T}
│   %13 = Base.Iterators.iterate(itr)::Any
│         Core.typeassert(%13, %2)::Any
│   %15 = (%13 isa %12)::Bool
└──       goto #6 if not %15
5 ─       goto #7
6 ─ %18 = Base.convert(%12, %13)::Any
7 ┄ %19 = φ (#5 => %13, #6 => %18)::Any
│   %20 = %new(%4, %11, %19)::Base.Iterators.Stateful{T} where T<:AbstractString
└──       return %20
) => Base.Iterators.Stateful{T} where T<:AbstractString
```
