### ISSUE TITLE
Performance regression in Julia v1.5-rc1

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#36465]
I've downloaded the release candidate today while preparing a tutorial and realized that there was a visible slowdown in one of my functions. The `@time` call below takes 13s in Julia v1.4.2 and 18s in the release candidate:

```julia
using GeoStats
using GeoStatsImages

K = geostatsimage("Ketton")
S = sample(K, 1_000_000, replace=false)
P = partition(S, PlanePartitioner((0.,0.,1.)))

@time EmpiricalVariogram(P, :grain)
```

Environment:
- GeoStats v0.13.0
- GeoStatsImages v0.4.2

Is this something related to type inference? I didn't have time to replace the usage of `OrderedDict` by a real Tables.jl type in my packages, and I know `OrderedDict` has rough corners.

I should mention that the function `EmpiricalVariogram` uses a threaded map-reduce from Transducers.jl and I am running it with 8 threads on my machine.

**Comment by juliohm** [comment]
Will try to produce a MWE with a smaller part of the code. In the meantime, I appreciate if someone can reproduce the issue.

**Comment by juliohm** [comment]
The times I am getting:

Julia 1.4.2:
- 14.382953 seconds (1.42 G allocations: 26.099 GiB, 28.17% gc time)

Julia 1.5-rc1:
- 20.673383 seconds (1.85 G allocations: 57.982 GiB, 40.28% gc time)

More memory is being allocated in the release candidate as you can see.

**Comment by juliohm** [comment]
Nailed down the code to a smaller method:

```julia
using GeoStats
using GeoStatsImages

K = geostatsimage("Ketton")
S = sample(K, 100_000, replace=false)

@time EmpiricalVariogram(S, :grain)
```

And the corresponding slowdown:

Julia 1.4.2:
- 34.842866 seconds (1.15 G allocations: 21.550 GiB, 2.84% gc time)
Julia 1.5-rc1:
- 46.935104 seconds (1.50 G allocations: 47.726 GiB, 7.14% gc time)

**Comment by KristofferC** [comment]
I can repro. Seems like there is a regression even in the single-threaded case. A nice MWE (perhaps from profiling) is pretty crucial here though.

**Comment by juliohm** [comment]
I've inspected the output of the profiler with ProfileView.jl and couldn't spot major differences. However, I saw that there is a lot of time spent in indexing in both versions of Julia (probably because of OrderedDict instabilities). Even though I am not sure the slowdown is only caused by indexing, I could reduce the code to a simple getindex that is slower in the release candidate:

```julia
using GeoStats
using GeoStatsImages
using BenchmarkTools

K = geostatsimage("Ketton")
S = sample(K, 100_000, replace=false)

@btime S[1,:grain]
```

Julia v1.4.2:
- 45.307 ns (2 allocations: 32 bytes)

Julia v1.5-rc1:
- 54.663 ns (3 allocations: 112 bytes)

Is this a sensible difference in nanoseconds? If I have 1_000_000 points, there will be a lot of indexing going on and that adds up to seconds of difference.

**Comment by KristofferC** [comment]
There is quite a lot of type instability going on

```
julia> @code_warntype S.data[S.inds[1], :grain]
Variables
  #self#::Core.Compiler.Const(getindex, false)
  sdata::RegularGridData{Float64,3}
  ind::Int64
  var::Symbol

Body::Any
1 ─ %1 = Base.getproperty(sdata, :data)::OrderedDict{Symbol,#s15} where #s15<:AbstractArray
│   %2 = Base.getindex(%1, var)::AbstractArray
│   %3 = Base.getindex(%2, ind)::Any
└──      return %3
```

so it is possible that dynamic dispatch got a bit slower in this case. Perhaps a type annotation somewhere could help out?

**Comment by juliohm** [comment]
Yes, I am trying to get rid of OrderedDict in the codebase right now. I delayed this issue for too long.

**Comment by juliohm** [comment]
Ok, I finally updated the entire codebase to remove OrderedDict in favor of a Tables.jl type. The timings for the first snippet in this issue with DataFrame are a bit higher but consistent from Julia v1.4 to Julia v1.5, they are around 16s now.
