### ISSUE TITLE
Code coverage user mode regression in 1.2.0 for inlined code

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#36462]
At some point in 1.2.0 the coverage decision on whether a code is user mode ignores the module the code is inlined from.

Running
```julia
mutable struct A
    b::Int
end

@inline function Base.deepcopy_internal(a::A, d::IdDict)
    a2 = A(a.b)
    d[a] = a2
    return a2
end

deepcopy(A(2))
```

on 1.1.1 produces the same coverage result for user and all mode but on 1.2.0 the user mode misses one constructor call and all lines in `deepcopy_internal`.

`@code_typed deepcopy(A(2))` and `@code_llvm deepcopy(A(2))` confirms that the `deepcopy_internal` method is correctly inlined and that on 1.2.0 with user mode the store for coverage is missing for `deepcopy_internal`.

**Comment by fredrikekre** [comment]
A similar example that came up on Slack, looks like same issue, and it is still an issue in Julia 1.5 and master (3d04d15c316fd93aef213ae366dff883c74e01ba):
````
$ cat src/Hash.jl 
module Hash

struct X end
function Base.hash(::X, u::UInt)
    println("I was called")
    return hash(123, u)
end

end # module

$ cat test/runtests.jl 
import Hash
hash(Hash.X())

$ jlpkg test --coverage
    Testing Hash
Status `/tmp/jl_qmzAe8/Project.toml`
  [574b4e5d] Hash v0.1.0 `/tmp/tmp.GrIRHL3yAz/Hash`
Status `/tmp/jl_qmzAe8/Manifest.toml`
  [574b4e5d] Hash v0.1.0 `/tmp/tmp.GrIRHL3yAz/Hash`
I was called                                          <------ !!!
    Testing Hash tests passed 

$ cat src/Hash.jl.29362.cov 
        - module Hash
        - 
        1 struct X end
        - function Base.hash(::X, u::UInt)
        -     println("I was called")
        -     return hash(123, u)
        - end
        - 
        - end # module
````

**Comment by racinmat** [comment]
Here is the example with travis and codecov https://github.com/racinmat/CoveragePackage https://codecov.io/gh/racinmat/CoveragePackage/src/master/src/CoveragePackage.jl

**Comment by yuyichao** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/37243. The commit didn't have the correct keyword to close this.
