### ISSUE TITLE
gcd() in OurRational() constructor example does not behave as described (documentation issue/minor)

### ISSUE THREAD

**Issue by malbert137** [JuliaLang/julia#36466]
In the chapter on constructors, in the example OurRational:

"gcd returns the greatest common divisor of its arguments with sign matching the first argument "

But...

julia> gcd(-10,15)
5

julia> gcd(-10,-15)
5

So the code example doesn't quite handle negative denominators properly.
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

Thanks!  Very nice programming language!

**Comment by StefanKarpinski** [comment]
If I recall correctly, this change was intentional and the docs are just outdated.
