### ISSUE TITLE
Large generated function takes very long to compile on Linux

### ISSUE THREAD

**Issue by sjoelund** [JuliaLang/julia#36483]
The following fragment of a generated lexer (based on Automa.jl) takes very long to compile on Linux compared to Windows on Julia 1.4.2:

https://gist.github.com/sjoelund/af90649890dec720cb9d7aab58c3a196

Some measurements:

```
[martin@mega src]$ time julia-1.4.2 -O0 test.jl 
Any[2]

real    0m1,148s
user    0m1,155s
sys     0m0,367s
[martin@mega src]$ time julia-1.4.2 -O1 test.jl 
Any[2]

real    0m37,918s
user    0m37,624s
sys     0m0,475s

$ time julia-1.4.2 test.jl  
Any[2]

real    12m6,189s
user    11m53,341s
sys     0m1,267s
```

```
arupa54@win00085 MINGW64 /c/OPENMODELICAGIT/OpenModelica/OMJulia.jl/src (master)
$ time julia -O0 lexertest.jl
Any[2]
  0.000160 seconds (21 allocations: 130.945 KiB)
real    0m1.093s
user    0m0.015s
sys     0m0.015s
arupa54@win00085 MINGW64 /c/OPENMODELICAGIT/OpenModelica/OMJulia.jl/src (master)
$ time julia -O1 lexertest.jl
Any[2]
  0.000114 seconds (21 allocations: 130.945 KiB)
real    0m3.868s
user    0m0.000s
sys     0m0.015s
arupa54@win00085 MINGW64 /c/OPENMODELICAGIT/OpenModelica/OMJulia.jl/src (master)
$ time julia lexertest.jl
Any[2]
  0.000145 seconds (21 allocations: 130.945 KiB)
real    0m3.976s
user    0m0.015s
sys     0m0.015s
```

Obviously there is some compiler optimization on Linux that just wrecks performance (even on -O1). Waiting 12 minutes to compile a 172 lines of code function is not ideal. I thought to disable optimization of this function in our production code, but that's an experimental feature in 1.5. And I guess fixing the underlying problem is better anyway.

```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, sandybridge)
```

**Comment by KristofferC** [comment]
> Waiting 12 minutes to compile a 172 lines of code function is not ideal

Is it reasonable to talk about number of lines of code when one line is 30 000 characters? :P

**Comment by sjoelund** [comment]
> Is it reasonable to talk about number of lines of code when one line is 30 000 characters? :P

In this case, yes. It's just a constant array anyway.

> As a side note, it seems expensive (from a runtime perspective) to re-create the huge arrays duck, cs etc in every iteration of the loop, just to then take out a single element from them.

Probably. Automa.jl might not have generated the best of code. So Julia doesn't optimize constant arrays in this case? I'm pretty used to it just being a literal and generating fast code :)

**Comment by KristofferC** [comment]
> So Julia doesn't optimize constant arrays in this case? 

No, it should be hoisted out of the loop.

I can't seem to repo the big timing on Linux:

```
❯ time ~/Applications/julia-1.4.2/bin/julia lexertest.jl
Any[2]
~/Applications/julia-1.4.2/bin/julia lexertest.jl  2.78s user 0.24s system 120% cpu 2.521 total
```

**Comment by sjoelund** [comment]
It's faster in 1.5, but still slow (same machine as above, my Intel 3820):
```
[martin@mega src]$ time julia-1.5.0-rc1 lexertest.jl 
Any[2]
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 74.5765 seconds (74.5792 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  68.7447 ( 92.5%)   0.0183 (  7.6%)  68.7630 ( 92.2%)  68.7656 ( 92.2%)  X86 DAG->DAG Instruction Selection
   4.6500 (  6.3%)   0.1123 ( 46.7%)   4.7622 (  6.4%)   4.7624 (  6.4%)  Machine Instruction Scheduler
   0.4944 (  0.7%)   0.0413 ( 17.2%)   0.5357 (  0.7%)   0.5358 (  0.7%)  Greedy Register Allocator
   0.1129 (  0.2%)   0.0595 ( 24.8%)   0.1724 (  0.2%)   0.1724 (  0.2%)  X86 Assembly Printer
   0.0570 (  0.1%)   0.0006 (  0.2%)   0.0575 (  0.1%)   0.0575 (  0.1%)  CodeGen Prepare
   0.0437 (  0.1%)   0.0001 (  0.0%)   0.0437 (  0.1%)   0.0437 (  0.1%)  Dead Store Elimination
   0.0251 (  0.0%)   0.0003 (  0.1%)   0.0254 (  0.0%)   0.0254 (  0.0%)  Combine redundant instructions
   0.0110 (  0.0%)   0.0003 (  0.1%)   0.0113 (  0.0%)   0.0112 (  0.0%)  Global Value Numbering
```

On another machine with an Intel 3930K:
```
real    1m15.935s
user    1m15.876s
sys     0m0.608s
```

On another machine with an Intel 5820K:
```
real    0m3.279s
user    0m3.430s
sys     0m0.402s
```

On another machine with an AMD Ryzen Threadripper 1950X:
```
real    0m7.536s
user    0m7.605s
sys     0m0.462s
```

**Comment by KristofferC** [comment]
Thanks for trying. It's surprising to me that the Intel 3930K is 25x slower than the Intel 5820K for this... I can't really say why.

**Comment by sjoelund** [comment]
I'm guessing because it has a different instruction set LLVM or something tries to optimize that extremely heavily?

On the 3820 limiting the instructions doesn't hurt much:
```
$ time julia-1.5.0-rc1 lexertest.jl
real    1m17,821s
user    1m17,683s
sys     0m0,579s

$ time julia-1.5.0-rc1 lexertest.jl -C athlon64
real    1m16,674s
user    1m16,587s
sys     0m0,556s
```

But on the 5820K, it does:
```
ubuntu@intel1:~$ time julia-1.5.0-rc1/bin/julia -C athlon64 lexertest.jl 
Any[2]

real    0m17.545s
user    0m17.356s
sys     0m0.465s

ubuntu@intel1:~$ time julia-1.5.0-rc1/bin/julia -C broadwell lexertest.jl 
Any[2]

real    0m6.203s
user    0m6.251s
sys     0m0.279s
```

Julia 1.2 was quite a lot faster on this machine, and I think my more modern laptop CPU also had performance issues with Julia 1.4. I could test that tomorrow if needed.

All machines are running Ubuntu 18.04.

**Comment by JKRT** [comment]
I have been following the discussion on the sidelines. 
There are some customs passes running on the generated LLVM-code such as 
[muladd ](https://github.com/JuliaLang/julia/blob/731126df8861b97382862617acc1028f22254c15/src/llvm-muladd.cpp)

Are they always executed regardless of what optimization level the user selects? Or is the -O flags just for running the standard LLVM passes? 

If not is there any known issues using LLVM on these architectures?

**Comment by ViralBShah** [comment]
This takes about 1s now.
