### ISSUE TITLE
cfunction segfault, possible world age related

### ISSUE THREAD

**Issue by ancapdev** [JuliaLang/julia#36505]
Working on some types akin to ```Observable``` with type erased and allocation free handlers.

Have built these before succesfully with [FunctionWrappers.jl](https://github.com/yuyichao/FunctionWrappers.jl), but wanted to try with ```@cfunction``` as I understand this now supports closures (via LLVM trampolines -- which incidentally I wish there was a better approach, since this will generate a new branch target per instance rather than per type of closure, but I digress).

With the following code:

```Julia
module Foo
using FunctionWrappers
null_handler(x) = nothing
mutable struct A1{T}
    value::T
    h::Base.CFunction
    function A1(value::T) where {T}
        new{T}(value, @cfunction $(null_handler) Nothing (T,))
    end
end
function Base.setindex!(a::A1{T}, x::T) where {T}
    a.value = x
    ccall(Base.unsafe_convert(Ptr{Cvoid}, a.h), Nothing, (T,), x)
end
mutable struct A2{T}
    value::T
    h::FunctionWrappers.FunctionWrapper{Nothing, Tuple{T}}
    function A2(value::T) where {T}
        new{T}(value, FunctionWrappers.FunctionWrapper{Nothing, Tuple{T}}(null_handler))
    end
end
function Base.setindex!(a::A2{T}, x::T) where {T}
    a.value = x
    a.h(x)
end
bar(a, x) = a[] = x
barl(a, x) = Base.invokelatest(setindex!, a, x)
end
```

I can generate a segfault with
```
julia> a = Foo.A1(0)
Main.Foo.A1{Int64}(0, Base.CFunction(Ptr{Nothing} @0x000000002cea6560, Main.Foo.null_handler, Ptr{Nothing} @0x0000000000000000, Ptr{Nothing} @0x0000000000000000))

julia> Foo.bar(a, 1)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x668b7fa0 -- jl_typemap_entry_assoc_exact at /cygdrive/d/buildbot/worker/package_win64/build/src\typemap.c:775
in expression starting at REPL[3]:1
jl_typemap_entry_assoc_exact at /cygdrive/d/buildbot/worker/package_win64/build/src\typemap.c:775
jl_typemap_assoc_exact at /cygdrive/d/buildbot/worker/package_win64/build/src\julia_internal.h:1021 [inlined]
jl_lookup_generic_ at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2269
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2318
unknown function (ip: 000000002CEA65E8)
setindex! at .\REPL[1]:13 [inlined]
bar at .\REPL[1]:26
unknown function (ip: 000000002CEAA621)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:369
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:458
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:409 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:799
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:911
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:764
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:823 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:843
eval at .\boot.jl:331
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:86
macro expansion at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:118 [inlined]
#26 at .\task.jl:358
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1700 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:687
Allocations: 853525 (Pool: 853350; Big: 175); GC: 1
```

Using the ```A2``` ```FunctionWrappers``` based implementation suffers no issues, and calling through ```Base.invokelatest()``` with ```Foo.barl()``` also resolves the problem. That's not a viable workaround for me, but made me wonder if it's a world age issue.

### Edit
Tested with Julia 1.4.1 on Windows.
```
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```
Originally found the issue on Linux, tested on 1.4.1 and 1.4.2, but worked up this MWE on Windows.

**Comment by Keno** [comment]
This sort of thing is better suited for https://discourse.julialang.org/, along with a complete reproducer that others can execute. If it turns out to be a bug in Julia, it can always be brought back here. FWIW, I tried to briefly run your code and it didn't crash for me, but any additional rounds of debugging are better suited for discourse.

**Comment by ancapdev** [comment]
I'm happy to post it on discourse to discuss, but I thought I'd done my due diligence, and this is a complete reproducible. It crashes reliably for me on Windows, Linux, AMD, Intel, Julia 1.4.1, and 1.4.2.

**Comment by ancapdev** [comment]
Discussion here: https://discourse.julialang.org/t/segfault-with-cfunction-possibly-world-age-related/42417

Confirmed on 1.4.1 and 1.4.2, and appears fixed in 1.5.0-rc1.

@Keno Is it worth re-opening as a bug against 1.4.x?

**Comment by KristofferC** [comment]
> Is it worth re-opening as a bug against 1.4.x?

Probably not.

**Comment by Keno** [comment]
> I'm happy to post it on discourse to discuss, but I thought I'd done my due diligence, and this is a complete reproducible. It crashes reliably for me on Windows, Linux, AMD, Intel, Julia 1.4.1, and 1.4.2.

Use of `cfunction` and `unsafe_*` is always a bit of a red flag and usually indicate something funky is going on. Discourse is just usually a better avenue to get these kinds of things addressed, since more people read it. If there's a segfault in regular julia code that doesn't use anything unsafe, that's usually automatically, a bug and belongs here, but for use of the unsafe APIs, it's often not. It's just a matter of keeping the issue tracker focused on actionable issues, and as presented there didn't seem to be one (since it doesn't segfault on 1.5 and there likely won't be another 1.4.x release).
