### ISSUE TITLE
Single iterator argument `map!(f, a)`

### ISSUE THREAD

**Issue by dalum** [JuliaLang/julia#36513]
Just ran into a case where I thought `map!(f, a)` was a thing.  It also seems like `map!(f, a, a)` is unreasonably slow:
```julia
julia> function map_single!(f, a)
           @inbounds for i in eachindex(a)
               a[i] = f(a[i])
           end
           return a
       end
map_single! (generic function with 1 method)

julia> a = rand(100);

julia> @btime map!($(x -> x + 1), $a, $a);
  44.070 ns (0 allocations: 0 bytes)

julia> @btime map_single!($(x -> x + 1), $a);
  14.602 ns (0 allocations: 0 bytes)
```
I guess there is a reason for the generic version not being defined in Base, except for dictionaries, but I couldn't find an issue for it, so opening this one.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/31677
