### ISSUE TITLE
@fastmath interprets `end` as a variable

### ISSUE THREAD

**Issue by pwstokes225** [JuliaLang/julia#36523]
Possibly a moot issue if `@fastmath` is going away, but currently the following throws an `UndefVarError`:
```
julia> x = [1,2,3];

julia> @fastmath x[end] += 1
ERROR: UndefVarError: end not defined
```
Same for `begin` in this context.

**Comment by ViralBShah** [comment]
Dup of #44596 - which is a more general version of this.
