### ISSUE TITLE
eigen/LAPACK.syev! fails for Hermitian matrices with N>=10002

### ISSUE THREAD

**Issue by caoyuan96421** [JuliaLang/julia#36522]
The following code reproducibly generates error and quits Julia:

```Julia
using LinearAlgebra
using LinearAlgebra.LAPACK

A = Hermitian(rand(10002,10002)+rand(10002,10002)*im) |> Array
@timev LinearAlgebra.LAPACK.syev!('N', 'L', A)
```

Same for
```Julia
using LinearAlgebra

A = Hermitian(rand(10002,10002)+rand(10002,10002)*im) |> Array
@timev eigen(A)
```

No error if using 10001 instead of 10002, which takes about 1.5min to finish.

Error message is as following:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception:
Please submit a bug repor at 0x1bc57280 --  at 0x1bc57280 --  g report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1bc57280 -- unknown function (ip: 000000001BC57280)
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1bc57280 -- dcabs164_ at C:\Users\caoyu\AppData\Local\Programs\Julia 1.5.0-rc1\bin\libopenblas64_.DLL (unknown line)
 ir entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1bc57280 --  OLATION \AppData\Locain expression starting at D:\calculation\eigenH.jl:6
 openblas64_.DLL (unknown line)
 ir entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1bc57280 --  OLATION oyu\AppData\Local\Programs\Julia 1.5.0-rc1\bin\libopenblas64_.DLL (unknown linin expression starting at D:\calculation\eigenH.jl:6
in expression starting at D:\calculation\eigenH.jl:6
```

The text is obviously scrambled due to multi-thread issue (?). Seems to be some low-level error from OpenBLAS.

FYI, my PC has 32GB memory, so it shouldn't be an OOM problem. Julia version 1.5.0-rc1.0 is being tested.
```bash
julia> versioninfo()
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\caoyu\AppData\Local\atom\app-1.48.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2
```

Just tested the error also has nothing to do with JULIA_NUM_THREADS being 1 or 2.

**Comment by dkarrasch** [comment]
I can't seem to be able to reproduce this:
```julia
julia> @timev LinearAlgebra.LAPACK.syev!('N', 'L', A)
138.094894 seconds (77.36 k allocations: 9.562 MiB)
elapsed time (ns): 138094894250
bytes allocated:   10026077
pool allocs:       77339
non-pool GC allocs:19
malloc() calls:    3
10002-element Array{Float64,1}:
 -2123.589055123486
...
```
on
```julia
julia> versioninfo()
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.4.0)
  CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by andreasnoack** [comment]
@caoyuan96421 What's the output from `BLAS.openblas_get_config()`?

**Comment by caoyuan96421** [comment]
> @caoyuan96421 What's the output from `BLAS.openblas_get_config()`?

```bash
julia> BLAS.openblas_get_config()
"OpenBLAS 0.3.5  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16"
```

**Comment by caoyuan96421** [comment]
> I can't seem to be able to reproduce this:
> 
> ```julia
> julia> @timev LinearAlgebra.LAPACK.syev!('N', 'L', A)
> 138.094894 seconds (77.36 k allocations: 9.562 MiB)
> elapsed time (ns): 138094894250
> bytes allocated:   10026077
> pool allocs:       77339
> non-pool GC allocs:19
> malloc() calls:    3
> 10002-element Array{Float64,1}:
>  -2123.589055123486
> ...
> ```
> 
> on
> 
> ```julia
> julia> versioninfo()
> Julia Version 1.5.0-rc1.0
> Commit 24f033c951 (2020-06-26 20:13 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin19.4.0)
>   CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
> ```

Just tried the same code in Julia 1.3.0, it seem to have no problem. 
```bash
julia> @timev eigen(A)
195.934803 seconds (1.43 M allocations: 4.550 GiB, 0.20% gc time)
elapsed time (ns): 195934803399
gc time (ns):      392345101
bytes allocated:   4885690121
pool allocs:       1429852
non-pool GC allocs:215
malloc() calls:    8
GC pauses:         3
```

So it seems like this is a problem specific to Windows and only in 1.5.0-rc1. Is there any suggestion what changed in Windows OpenBLAS between these versions?

**Comment by caoyuan96421** [comment]
@andreasnoack @dkarrasch Any more thoughts on this issue?

**Comment by andreasnoack** [comment]
Are you sure you are using version 0.3.5 of OpenBLAS in 1.5.0? It is supposed to be 0.3.9
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using LinearAlgebra

julia> BLAS.openblas_get_config()
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=32"
```
Could you please fill out the 2x2 matrix where one axis is (default threading, `BLAS.set_num_threads(1)`) the other is (default settings, 'load julia with OPENBLAS_CORETYPE="Penryn"') and the elements are works/fails?

**Comment by masuday** [comment]
I tested it.

|-      |Default|`BLAS.set_num_threads(1)`|
|--|--|--|
|Default|Failed|OK|
|`OPENBLAS_CORETYPE=Penryn`|OK|OK|

It seems like the same issue as #36976, i.e. complex numbers, Julia 1.5, OpenBLAS 0.3.9, Windows only. The above matrix is applied to #36976. It happens on AMD CPUs as well.

```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 PRO 2400GE w/ Radeon Vega Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

**Comment by andreasnoack** [comment]
Yes. I think we can close this as a dup of #36976
