### ISSUE TITLE
Visibility of `using`ed names in a module

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#36529]
```julia
julia> module A
       module B
       f(x) = 1
       end
       using .B: f
       end
Main.A

julia> names(A; all=true, imported=true)
6-element Array{Symbol,1}:
 Symbol("#eval")
 Symbol("#include")
 :A
 :B
 :eval
 :include
```

Is there a way to discover ~what `f` refers to inside `A`~ that `A` also has a meaning for `f`? If you change `using .B: f` to `import .B: f`, then it's visible.

This appears to be related to a significant performance issue for SymbolServer (which is used by vscode's languageserver indexing machinery), see https://github.com/julia-vscode/SymbolServer.jl/pull/177.

**Comment by aviatesk** [comment]
This would also help REPL completions improve a lot:
https://github.com/JuliaLang/julia/blob/fedde78fe610b4f1fad25b723091489b4604c3ab/stdlib/REPL/src/REPLCompletions.jl#L86

**Comment by NHDaly** [comment]
Any update to this? is there any mechanism to do this? If not, should we design one?

**Comment by NHDaly** [comment]
Okay never mind: after searching, I don't believe a mechanism exists, and I've added a PR to expose this in #42092.



> This would also help REPL completions improve a lot:
> https://github.com/JuliaLang/julia/blob/fedde78fe610b4f1fad25b723091489b4604c3ab/stdlib/REPL/src/REPLCompletions.jl#L86

@aviatesk: Completely agreed! I'll put up a _separate_ PR that comes after this one that changes the REPL to also set `usings = true`.
I'm excited for the way this will improve the REPL experience ❤️
