### ISSUE TITLE
Ensure telemetry is fully shaken-out prior to releasing 1.5

### ISSUE THREAD

**Issue by alhirzel** [JuliaLang/julia#36548]
This is a meta-issue which reflects the following concern: excitement and adoption of Julia 1.5 may be stifled by the inclusion of an immature telemetry system with the base installation/official binaries.

My concern is a parallel to what happened with packages at the 1.0 release, where user experience was degraded by many packages not being ready for the transition. In this case, I feel there is a risk that the telemetry system could negatively alter the perception of Julia. Additionally, I feel there will be legitimate concern when Julia is used in commercial environments, especially when internal packages on an internal registry use external/public dependencies.

Specifically, I feel and think the release of Julia 1.5 should be delayed until the telemetry system is shored up. I have filed the following issues to reflect my personal concerns (which I hope are seen as legitimate!).

* Legal notice should have opt-out information: https://github.com/JuliaLang/Pkg.jl/issues/1898
* Disabling telemetry for a specific package: https://github.com/JuliaLang/Pkg.jl/issues/1899
* Disabling telemetry for a specific set of installations: https://github.com/JuliaLang/Pkg.jl/issues/1900

I invite others to brainstorm how we can ensure the 1.5 release with telemetry has no face-pie right out of the gate.

**Comment by JeffBezanson** [comment]
I think the wording of this issue might be misleading to some readers: there isn't really a "telemetry system", just some headers sent with package server requests.

It's important to note what we are actually talking about here, which is the very minimal data explained in detail here: https://julialang.org/legal/data/
And again, this is only about package server requests, not something that is in the base language e.g. collecting "usage stats" or sending crash reports, etc. that some software does nowadays.

**Comment by KristofferC** [comment]
Thanks for opening this issue. There is however no need for a "meta"-issue like this. Targeted issues work best and keeps the comments focused. Also, this is kit the right repo for this issue since this is purely a thing for the package manager.

**Comment by alhirzel** [comment]
Jeff, thanks for your reply, and I agree I should have included a little more detail in case there are readers who are just hearing of this now. I personally agree with many that the current design is pretty innocuous, and I agree that the set of collected usage data will do a lot of good for the community iso funding and direction-setting (can't manage what can't be measured). I also think and feel that a great job has been done so far to document what has been done.

I do consider the telemetry to be a "system" in the sense that it has a set of features, can be disabled, and because there's also back-end stuff receiving the data that some people will invariably be suspicious of (and indeed, this has already been acknowledged because the ability to disable it has been built-in). I am just trying to express a few concerns, and I hope that readers are not distracted by my sloppy wording... :)  This issue is against Julia itself because I want to make sure it has adequate visibility, and I strongly feel it affects the Julia project as a whole, especially from a perception standpoint.

**Comment by alhirzel** [comment]
[Jinx](https://en.wikipedia.org/wiki/Jinx), @KristofferC! Do you agree that this issue relates to the perception of the Julia project as a whole?

**Comment by KristofferC** [comment]
All components of Julia does to different extent. 

The best way for things like this is still (just like you have already done) to open targeted issues. For more general "discussion" type of conversations, using the discourse forum works best.

**Comment by alhirzel** [comment]
Ok, thank you for clarifying! For future readers, this is the canonical thread: https://discourse.julialang.org/t/pkg-jl-telemetry-should-be-opt-in/42209/193
