### ISSUE TITLE
"To edit a specific method, type the corresponding number into the REPL and press Ctrl+Q" is annoying

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#36575]
I think printing this message once is a good idea, but every time is overkill. Could this simply be printed once (with a message saying that this message will not be printed after this, so that users pay attention the first time)? Eg by writing a file in .julia.

**Comment by KristofferC** [comment]
Heh, was just opening an issue about this as well. Yeah, getting constant reminders about shortcuts is really annoying. Something that is only useful to read once should really not be printed over and over during correct usage (it's more ok in e.g. an error message).
