### ISSUE TITLE
Julia segfault on Travis with v1.5 and nightly under certain conditions

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#36571]
When changing my Travis config for BAT.jl to use Julia v1.5 for docs generation (just to check I was ready for the v1.5 release), I ran into a segfault. However, I couldn't reproduce the segfault on any of my local systems. After many, many, many iterations of stripping BAT.jl down to nothing, I created an MWE that causes the segfault:

```julia
function all_lteq(A::AbstractArray, B::AbstractArray, C::AbstractArray)
    axes(A) == axes(B) == axes(C) || throw(DimensionMismatch("A, B and C must have the same indices"))
    result::Int = 0
    @inbounds for i in eachindex(A, B, C)
        result += ifelse(A[i] <= B[i] <= C[i], 1, 0)
    end
    result == length(eachindex(A))
end

A = Float32[-1.0, -1.0]
B = [0.0, 0.0]
C = Float32[1.0, 1.0]
all_lteq(A, B, C)
```

It's a stripped down version of code that has been in BAT.jl for ages and never caused trouble before. It normally gets called during processing of a tutorial that's part of docs generation. The weird thing is that the segfault on Travis is perfectly reproducible - but *only* when I call the code via `julia docs/make.jl` in the documentation stage.

I've prepared a branch of BAT.jl that's basically empty (no package code left), except for a "docs/make.jl" containing the piece of code above, and a "test/runtests.jl" which now just includes "docs/make.jl": https://github.com/bat/BAT.jl/tree/travis-segfault-1.5

On Travis, the tests pass on Julia v1.4, v1.5 and nightly, but the documentation stage passes on v1.4 and fails on v1.5 and nightly: https://travis-ci.com/github/bat/BAT.jl/builds/174730125

When I remove the `@inbounds` (https://github.com/bat/BAT.jl/tree/travis-nosegfault-1.5) everything passes: https://travis-ci.com/github/bat/BAT.jl/builds/174730344

So I'm pretty sure the segfault originates from Julia - but since it doesn't happen when I run `julia make.jl` locally, I'm not sure how drill down on this further. Of course segfaults often do tend to appear/disappear depending on the environment the code is run in.

I'm reporting this before v1.5 gets released, in the hope that more expert hands can track it down to it's source.

**Comment by Keno** [comment]
Stack trace:
```
signal (11): Segmentation fault
in expression starting at REPL[5]:1
_ZNK4llvm3EVT23isExtendedScalarIntegerEv at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZL14combineBitcastPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoERKNS_12X86SubtargetE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZNK4llvm17X86TargetLowering17PerformDAGCombineEPNS_6SDNodeERNS_14TargetLowering15DAGCombinerInfoE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN12_GLOBAL__N_111DAGCombiner7combineEPN4llvm6SDNodeE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm12SelectionDAG7CombineENS_12CombineLevelEPNS_9AAResultsENS_10CodeGenOpt5LevelE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
```
Probably feeding in bad LLVM IR somewhere.

**Comment by Keno** [comment]
Fails an assertion in the much the same place if enabled, but no verifier errors anywhere:
```
julia> all_lteq(A, B, C)
julia: /home/keno/julia-comparison/deps/srccache/llvm-9.0.1/include/llvm/Support/Casting.h:105: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::IntegerType; From = llvm::Type]: Assertion `Val && "isa<> used on a null pointer"' failed.

signal (6): Aborted
in expression starting at REPL[6]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f9fc2f15728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN4llvm3isaINS_11IntegerTypeEPNS_4TypeEEEbRKT0_.isra.0.part.0 at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZNK4llvm3EVT21getExtendedSizeInBitsEv at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm12SelectionDAG7getNodeEjRKNS_5SDLocENS_3EVTENS_7SDValueENS_11SDNodeFlagsE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZN4llvm12SelectionDAG10getBitcastENS_3EVTENS_7SDValueE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZL13combineSelectPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoERKNS_12X86SubtargetE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
_ZNK4llvm17X86TargetLowering17PerformDAGCombineEPNS_6SDNodeERNS_14TargetLowering15DAGCombinerInfoE at /home/keno/julia-comparison/usr/bin/../lib/libLLVM-9jl.so (unknown line)
```

**Comment by oschulz** [comment]
Thanks for confirming, @Keno! Took me hours to run this through Travis again and again, to make sure it was real and where it was ... just for the future - how did you reproduce it locally? I didn't manage to make this happen anywhere except on Travis.

**Comment by oschulz** [comment]
This doesn't seem to happen with Julia v1.4 - I'm not sure if it's due to the irregular behavior of segfaults or if it's a true regression.

**Comment by oschulz** [comment]
Just tried to re-test this with v1.5.0-rc2, but Travis seems to use rc1, currently, and I still didn't manage to reproduce the problem locally.

**Comment by oschulz** [comment]
Still fails on Julia nightly on Travis though, so I assume v1.5.0-rc2 is affected as well.

**Comment by ViralBShah** [comment]
Let's reopen if still an issue.

**Comment by JosePereiraUA** [comment]
Hi, I think I'm having a similar issue on Julia 1.7.2, I get the following error when making documentation on Travis CI:

```
signal (6): Aborted
in expression starting at none:0
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fa23fecb836)
unknown function (ip: 0x7fa23fed28b9)
cfree at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_ZN4llvm2cl3optINS_15FunctionSummary23ForceSummaryHotnessTypeELb1ENS0_6parserIS3_EEED2Ev at /home/travis/julia/bin/../lib/julia/libLLVM-12jl.so (unknown line)
__cxa_finalize at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
__do_global_dtors_aux at /home/travis/julia/bin/../lib/julia/libLLVM-12jl.so (unknown line)
_fini at /home/travis/julia/bin/../lib/julia/libLLVM-12jl.so (unknown line)
unknown function (ip: 0x7fa23fe85030)
exit at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
main at julia (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x400808)
Allocations: 194024687 (Pool: 193970160; Big: 54527); GC: 170
/home/travis/.travis/functions: line 109:  7205 Aborted                 julia --project=docs/ docs/make.jl
The command "julia --project=docs/ docs/make.jl" exited with 134.
```

Do we have an update on how you solved your issue?
Thanks!
