### ISSUE TITLE
[FR] add link to local copy of docs in `?`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaLang/julia#36574]
Context: https://discourse.julialang.org/t/documentation-feature-request/42711

This would possibly belong in `basedocs.jl`, right after:
```
**Welcome to Julia $(string(VERSION)).** The full manual is available at
    https://docs.julialang.org
```

A link to the `index.html` in the local copy of the docs would be useful.

**Comment by heliosdrm** [comment]
An alternative approach is proposed in #34278

**Comment by ViralBShah** [comment]
Newer discussion #44537.
