### ISSUE TITLE
Functions in @testset leak local variables

### ISSUE THREAD

**Issue by arturgower** [JuliaLang/julia#36593]
The leaking of a local variable in the block below is unexpected: 

```julia
@testset "MyTest" begin

    function myfun(m)
        n = m
        return n
    end

    n = myfun(1)

    println("n = ", n)

    myfun(3) # <-- changes n to 3

    println("n = ", n)

end
```
The output is: 

```
n = 1
n = 3
Test Summary: |
MyTest        | No tests
```

Having `n` change value is unexpected. This error seems to be unique to `@testset` blocks.

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by StefanKarpinski** [comment]
This is the documented way that local variables work: if `n` is already a local variable in an outer local scope, then any assignment to `n` updates that local. In this case `n = myfun(1)` causes `n` to be local to the test set. The assignment inside of `myfun` assigns that same local variable. The fact that the definition of `myfun` comes before the assignment to `n` doesn't affect the logic or behavior. The documentation of variable scope was significantly overhauled in the soon-to-be-released 1.5 version, which may be clearer:

https://docs.julialang.org/en/v1.6-dev/manual/variables-and-scoping/#Local-Scope-1.

**Comment by arturgower** [comment]
Thanks @StefanKarpinski that is very clear. 

For reference, I had wrongly associated `begin` .. `end` blocks with `@testset begin` .. `end`. However `begin` .. `end` do not introduce a new scope.

To avoid this behaviour we can just explicitly declare local variables:
```julia
@testset "MyTest" begin

    function myfun(m)
        local n = m
        return n
    end

    n = myfun(1)

    println("n = ", n)

    myfun(3) # <-- changes n to 3

    println("n = ", n)

end
```

```
n = 1
n = 1
Test Summary: |
MyTest        | No tests
Test.DefaultTestSet("MyTest", Any[], 0, false)
```

**Comment by StefanKarpinski** [comment]
> I had wrongly associated `begin` .. `end` blocks with `@testset begin` .. `end`. However `begin` .. `end` do not introduce a new scope.

Right, the fact that test sets introduce scope is an essential part of this.
