### ISSUE TITLE
FYI: tar-2.gz on Nightly

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#36594]
At least on nightly for some time now it's a two step process to extract Julia, because of "tar-2", where "-2" is probably an unintentional addition.

I can manage, but not all know tar too well. With tar.gz the extractor does all the work for you.

**Comment by StefanKarpinski** [comment]
The download location hasn't changed, it's still `https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz` which, as you can see has the expected extension. This is likely your download agent renaming the download because the file already exists.

**Comment by PallHaraldsson** [comment]
Yes it was... seems like a bug for the download agent, or something, as the GUI archive manager only extract then for you a "tar-2" file... Still could be confusing for users.

**Comment by StefanKarpinski** [comment]
There's nothing we can do about how your download agent chooses to save files.
