### ISSUE TITLE
the `-full` source tarball doesn't contain all dependencies and the build system could be better

### ISSUE THREAD

**Issue by doronbehar** [JuliaLang/julia#36604]
I'm trying to help my distro (NixOS) build Julia in the best possible manner and I have some comments. Our build system doesn't allow internet access during the build of packages. https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#source-distributions-of-releases says that e.g [this tarball](https://github.com/JuliaLang/julia/releases/download/v1.4.2/julia-1.4.2-full.tar.gz) should contain all dependencies needed to build Julia with all the deps' patches, but I get this error when trying to build with that tarball:

```
Could not find working curl, wget, or fetch.
You need to install one of these to download dependencies.
make[1]: *** [/build/julia-1.4.2/deps/suitesparse.mk:144: /build/julia-1.4.2/deps/srccache/SuiteSparse.v5.4.0-2.x86_64-linux-gnu.tar.gz] Error 1
```

Another paper-cut I experienced:

```
/nix/store/ypag3bh7y7i15xf24zihr343wi6x5i6g-bash-4.4-p23/bin/bash: --: invalid option
Usage:  /nix/store/ypag3bh7y7i15xf24zihr343wi6x5i6g-bash-4.4-p23/bin/bash [GNU long option] [option] ...
        /nix/store/ypag3bh7y7i15xf24zihr343wi6x5i6g-bash-4.4-p23/bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
/build/julia-1.4.2/Make.inc:653: *** "please install either GNU tar or bsdtar".  Stop.
```

And it's because of this:

https://github.com/JuliaLang/julia/blob/ff174120aad91e1a838b5cf99bd2b97c14aab2f5/Make.inc#L685-L691

Meaning you rely on `which` to exist on the system and that's totally unclear from that weird bash error. It all made me wonder why don't you use a real build system like cmake / autoconf to find all dependencies? From what I've heard, these build systems have been proven as very reliable for the most exotic systems such as Windows' WSL and obscure Unix like systems such as NixOS and Guix.

I haven't tried Julia yet but it makes a good impression and I'd love to try it out so I hope this feedback will help you improve the experience for more people.

Regards.

**Comment by doronbehar** [comment]
Also, for example `suitesparse` is available I think on many distribution as a library package. So I ask: Why not try to detect the system's suitesparse by default? Considering the suitesparse you require is not patched like llvm? Unless [suitesparse is also patched](https://github.com/JuliaLang/julia/blob/master/deps/suitesparse.mk#L44)? Are these patches not merged upstream / not released upstream?

**Comment by doronbehar** [comment]
I missed the instruction in the docs saying I should `USE_BINARYBUILDER=0` at https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#building-julia .

Sorry for the noise.

**Comment by doronbehar** [comment]
Perhaps there's more in this issue besides the fact I missed `USE_BINARYBUILDER`. I'll leave you the decision to close it.

**Comment by 62f** [comment]
Being directed here is the equivalent of ‘RtFM’. Death of a thousand paper-cuts. Welcome, Cenobyte. What’s your pleasure?

**Comment by StefanKarpinski** [comment]
What are you trying to do, @62f? You've opened a number of issues displaying various problems, but it's not clear from any of them what your situation is and why you're having these problems. In one you seem to have network problems but insist that you don't have network problems. In another you are encountering an error with busybox `rm` not accepting the `-d` option which only seems to be passed to `rm` in a make target for uninstalling. Perhaps try giving a clearer description of what you were trying to do and how you got to the problem you're seeing.

**Comment by ifelsefi** [comment]
Hello

I have the full version of Julia 1.5.3.   It tries to download `LibUV.v2.0.0-9.x86_64-linux-gnu.tar.gz` though I do not have internet access.   Can this be added to the full tarball?

**Comment by vtjnash** [comment]
The user may need to add USE_BINARYBUILDER=0 to disable downloading pre-built binaries even if you have all of the source code. Maybe the `full-source-dist` target should create a Make.user file with that line already present for the user, but someone would need to make a PR to add that line.
