### ISSUE TITLE
Package manager has problems with drive letters on Windows

### ISSUE THREAD

**Issue by nhabedi** [JuliaLang/julia#36613]
This is Julia 1.4.2 on Windows, see detailed version info below.  It seems I can't register my packages with the package manager if they aren't on drive C, see example session below.  "C:\\" is preprended to the correct path.  Somehow reminds me of Windows programs with hard-coded drive letters from the 90s... :)

Is there a fix for this or am I forced to work on drive C?

Thanks,
Edi

```
julia> pwd()
"C:\\Users\\edi"
julia> cd("E:\\Desktop")
julia> pwd()
"E:\\Desktop"
(@v1.4) pkg> generate Foo
 Generating  project Foo:
    Foo\Project.toml
    Foo\src/Foo.jl
(@v1.4) pkg> dev Foo
[ Info: Resolving package identifier `Foo` as a directory at `E:\Desktop\Foo`.
Path `Foo` exists and looks like the correct package. Using existing path.
  Resolving package versions...
ERROR: expected package `Foo [94ed899b]` to exist at path `C:\E:\Desktop\Foo`
```

```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
This is a dup of https://github.com/JuliaLang/Pkg.jl/issues/1796.

**Comment by StefanKarpinski** [comment]
Wanted: someone with a Windows system to do a little debugging here.

**Comment by nhabedi** [comment]
> Wanted: someone with a Windows system to do a little debugging here.

What would that entail?  I'm pretty new to Julia and I'm also not sure I'd be able to build Julia from source if that's what is needed.  Otherwise, I'd be happy to help.

**Comment by StefanKarpinski** [comment]
May not be a beginner issue. Just the usual debugging stuff. Poke around until one figures out what's wrong 😬

**Comment by nhabedi** [comment]
OK, I stared at the source code of the Pkg module for quite some time and my guess is that the function `relpath` is the culprit or rather the fact that the module tries to work with relative paths.

* `Operations.develop` calls `_resolve`
* `_resolve` might call `targeted_resolve`
* `targeted_resolve` calls `resolve_versions!`
* `resolve_versions!` calls `collect_developed`
* `collect_developed` calls `collect_developed!`
* `collect_developed!` calls `relative_project_path`
* `relative_project_path` eventually calls `relpath`

However, as far as I understand relative paths don't work across drives on Windows.  `relpath` will happily do something like this:

```
julia> relpath("E:/Desktop", "C:/Users/edi")
"..\\..\\..\\E:\\Desktop"
```

But that won't work.  I guess the fix would be that `relpath` checks drive letters on Windows and either throws an error or returns an absolute path if the drives of the arguments are different.  There are probably also issues with network drives...

**Comment by StefanKarpinski** [comment]
Thanks for the digging! Hopefully that helps someone figure out the rest.
