### ISSUE TITLE
ArgumentError: `C:\..\compiled\..\_.ji' exists.

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#36621]
I am getting this error frequently as I edit a development branch on github and then `pkg> add ErrorfreeArithmetic#fix` and then (in a new REPL) `using` it. The very good news is that the message is helpfully specific (see below) so I can remedy the situation.  The issue is that Julia appears to know what needs to be done and the only file in jeopardy is a `.ji` file which autoregenerates if missing.  

Why not rename (somehow move) that file to `_.ji.1` or whatever and proceed without involving me? If the old file is kept, then `Pkg.gc()` pbly should cull it.
  
```julia
julia> using ErrorfreeArithmetic
[ Info: Precompiling ErrorfreeArithmetic [90fa49ef-747e-5e6f-a989-263ba693cf1a]
ERROR: ArgumentError: 'C:\Users\jas\.julia\compiled\v1.6\ErrorfreeArithmetic\nMLcX_1H60c.ji' exists. `force=true` is required to remove 'C:\Users\jas\.julia\compiled\v1.6\ErrorfreeArithmetic\nMLcX_1H60c.ji' before copying.
Stacktrace:
 [1] checkfor_mv_cp_cptree(src::String, dst::String, txt::String; force::Bool)
   @ Base.Filesystem .\file.jl:308
 [2] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
   @ Base.Filesystem .\file.jl:345
 [3] rename(src::String, dst::String)
   @ Base.Filesystem .\file.jl:898
 [4] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1341
 [5] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1030
 [6] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:928
 [7] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923
```

```juliah
julia> versioninfo()
Julia Version 1.6.0-DEV.378
Commit c76960224f (2020-07-06 08:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by musm** [comment]
I've also been seeing this error https://github.com/JuliaLang/Pkg.jl/issues/1920

**Comment by KristofferC** [comment]
My guess is that this comes from https://github.com/JuliaLang/julia/pull/36416. Cc @kpamnany

**Comment by kpamnany** [comment]
I cannot work out why `rename()` would be failing -- none of the potential errors listed [here](https://linux.die.net/man/2/rename) should apply. Presumably this is not happening to everyone, or there would be a lot more noise?

After a close look, I think @musm's fix is fine.

**Comment by StefanKarpinski** [comment]
Windows is _super_ fussy about the deleting things. If anyone has an open reference to it, it fails. Very annoying.

**Comment by kpamnany** [comment]
So you think this is an `EBUSY` error? But who else could have opened the cache file? It seems like these folks are not running distributed...

**Comment by StefanKarpinski** [comment]
Maybe? If there's another Julia process running at the same time using that same `.ji` file, that would do it.

**Comment by musm** [comment]
> Maybe? If there's another Julia process running at the same time using that same .ji file, that would do it.

Does Pkg launch julia processes during precompilation and normal operation? Note, I run into this error when I only have a single Julia process running and it occurs when launch Julia and try to precompile a stale package because of julia has been modified.

**Comment by StefanKarpinski** [comment]
Yes, it does. Precompilation (necessarily) has to happen in a child process, so it's possible that there's contention between different children or between a child and parent.

**Comment by StefanKarpinski** [comment]
@musm, did you mean to close this?

**Comment by StefanKarpinski** [comment]
No, that's fine, just checking!
