### ISSUE TITLE
Random freezing/sleeping of programs

### ISSUE THREAD

**Issue by cfitz25** [JuliaLang/julia#36632]
Hello, i noticed that when i was running my programs they would occasionally lock up or freeze and no longer print output, this is extremely random and there doesnt appear to be anything similar between the two as neither have any similar code.
I dont have anything that can reproduce it reliably because of that.
I did get the stacktrace of where one of my programs were during this freeze however, which i hope may be of use. From what im seeing it looks like it is my program never being given control back to it after it gives it away.
```
epoll_pwait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv__io_poll at /workspace/srcdir/libuv/src/unix/linux-core.c:270
uv_run at /workspace/srcdir/libuv/src/unix/core.c:359
jl_task_get_next at /buildworker/worker/package_linux64/build/src/partr.c:449
poptaskref at ./task.jl:702
wait at ./task.jl:709 [inlined]
wait at ./condition.jl:106
_trywait at ./asyncevent.jl:110
wait at ./asyncevent.jl:128 [inlined]
sleep at ./asyncevent.jl:213 [inlined]
_add_require at /home/cupiditas/.julia/packages/Revise/tV8FE/src/pkgs.jl:325
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:643
TaskThunk at /home/cupiditas/.julia/packages/Revise/tV8FE/src/types.jl:229
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2145 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2323
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1700 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:687
unknown function (ip: (nil))
unknown function (ip: (nil))
```

------------------
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

**Comment by KristofferC** [comment]
Looks like Revise is stuck here: https://github.com/timholy/Revise.jl/blob/8336b10a5e7d0e4b1bb0726cf426469c8f866d2e/src/pkgs.jl#L324-L326.

I don't think this is a Julia issue. Perhaps open this at Revise.jl.
