### ISSUE TITLE
Mod doesn't work on at least this one example

### ISSUE THREAD

**Issue by IsaacRudich** [JuliaLang/julia#36648]
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

When I type 24%1.6 into the REPL I get 1.599999999998 instead of 0. I feel like I am going insane, but it is replicable here
https://www.tutorialspoint.com/execute_julia_online.php if you add the line:
println(24%1.6) or println(mod(24,1.6))

**Comment by yuyichao** [comment]
`1.6` is not exactly representable with double precision floating point. `1.6` is actually slightly larger than exactly 1.6 and the difference appears to be large enough to be representable when multipled by 15.

```julia
julia> 1.6 + Float64(24 - big(1.6) * 15)
1.5999999999999988
```

This is not a bug. Please ask further questions on discourse.julialang.org instead.
