### ISSUE TITLE
Define +(::UniformScaling{Bool})

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#36668]
In Julia, we can use `-I`:

```julia
julia> -I
UniformScaling{Int64}
-1*I
```

which is exactly the same as `-1*I`. However, `+I` is not defined:

```julia
julia> +I
ERROR: MethodError: no method matching +(::UniformScaling{Bool})
Closest candidates are:
  +(::UniformScaling, ::Number) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/uniformscaling.jl:109
  +(::UniformScaling, ::UniformScaling) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/uniformscaling.jl:114
  +(::UniformScaling, ::BitArray{2}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/uniformscaling.jl:116
  ...
Stacktrace:
 [1] top-level scope at REPL[136]:1
```

This seems confusing at first glance. Hence, I propose that we define `+I` as `+1*I` to keep consistency.

If this is approved, then I can do a PR.

**Comment by dkarrasch** [comment]
Why not have
```julia
(+)(J::UniformScaling) = J
```
to avoid unnecessary promotion of `J.λ`?

**Comment by mbauman** [comment]
I think I'd do:

```Julia
(+)(J::UniformScaling) = UniformScaling(+J.λ)
```

**Comment by ronisbr** [comment]
> Why not have
> 
> ```julia
> (+)(J::UniformScaling) = J
> ```
> 
> to avoid unnecessary promotion of `J.λ`?

The only problem here is that we will have a different behavior between `-` and `+`:

```julia
julia> import Base: +

julia> (+)(J::UniformScaling) = J
+ (generic function with 290 methods)

julia> -I
UniformScaling{Int64}
-1*I

julia> +I
UniformScaling{Bool}
true*I
```



> I think I'd do:
> 
> ```julia
> (+)(J::UniformScaling) = UniformScaling(+J.λ)
> ```

This seems to be fine since it replicates that same behavior of `-`:

```julia
julia> import Base: +

julia> (+)(J::UniformScaling) = UniformScaling(+J.λ)
+ (generic function with 167 methods)

julia> -I
UniformScaling{Int64}
-1*I

julia> +I
UniformScaling{Int64}
1*I
```

I will wait a couple of days for any new ideas and then I submit the PR.

**Comment by ronisbr** [comment]
Done! In Brazil, couple of days === 8 days 😅  (sorry for the delay, completely forgot about this...)
