### ISSUE TITLE
Atomic File Write API

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#36664]
From @StefanKarpinski on Slack:

> Stefan Karpinski 
one API we should arguably have is an “atomic write” API which writes to temp file that’s in the same directory as the ultimate output file and then replaces the destination file at the end if everything worked

> Stefan Karpinski
in that case, you could just implement this with a normal open and “atomic” write

> Stefan Karpinski
open_write_atomic seems very awkward

> Stefan Karpinski
one possible API would be to add an atomic flag to open which changes the behavior of write to do that but you’d want it to mean something useful in other modes as well

> Stefan Karpinski
in read mode it could mean move the file to a temp path first and then open it for read so that if someone writes to it, it doesn’t affect the read

I do believe that an API like this could be quite useful. I think Stefan also mentioned that this is already used in Pkg.

**Comment by vtjnash** [comment]
xref https://github.com/JuliaLang/julia/issues/39892
