### ISSUE TITLE
Juliaup version manager

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#36672]
EDIT: The information at the top here is outdated, I'll try to rewrite this initial issue to catch folks up. For now, look at the bottom of the thread :)

I've created a MSIX installer for Julia, with the eventual goal to put Julia into the Windows Store. The whole thing is very experimental at this stage, has major gaps, needs a lot of feedback from the whole core team and if we think this is overall a good idea will take quite a bit more work to bring over the finishing line.

This will be a slightly longer post, so bear with me :)

# Background

[MSIX](https://docs.microsoft.com/en-us/windows/msix/overview) packages are the type of installer that is used by the Windows Store. In general, it seems to be where MS is going with setup technology.

At a very high level, a MSIX package is a file format for packaging up applications. There are two ways in which you can install MSIX packages: a) you submit them to the Windows store and then it gets distributed via that, b) you use AppInstaller (part of Windows)  to install a MSIX package from a URL, file share etc. In both scenarios you get auto-updating of your application.

MSIX also has a notion of optional packages. Think main package for an app, and then optional packages to install additional features on-demand for an application. This is used say in games where you have an in-app purchase option to add features, those typically come as optional MSIX packages. I'll describe a little later how I'm using optional packages in my prototype.

# Benefits

Here are some major benefits one gets from packaging an app in an MSIX installer:

## Auto updating

This one is easy enough: one gets a fully automated updating experience for the app :)

## Windows Store

Also easy enough: MSIX installers are the only way to get an app into the Windows Store. I think having Julia in the Windows Store would be a major, major simplification for beginner users.

## Putting Julia.exe on the PATH

MSIX installers provide a simple and elegant way to add commands to the `PATH`. The way this works is that the `PATH` environment variable is actually _not_ modified at all. Instead, by default, the folder `~\AppData\Local\Microsoft\WindowsApps` on Windows is listed in the `PATH` env variable, and then AppInstaller or the Windows Store can automatically add a symbolic link to our Julia.exe in that folder. All we have to do is declare in our MSIX installer that we want `julia.exe` on the PATH, and then the rest works by itself.

This is better than modifying the PATH itself for a number of reasons: 1) it all works without any restarts at all: if you have a shell open, then install Julia, you don't even have to restart the shell to pick up some new PATH configuration, once Julia is installed, it just works. 2) there is no risk that things get left on the system with respect to the PATH if the package is uninstalled, 3) no worries about PATH becoming too long, 4) we can julia.exe on the PATH, without putting the folder with various DLLs on the PATH.

This would also mean that novice users don't have to do any manual configuration to get julia onto the PATH, which at least in my experience has been a major hassle in a teaching environment.

# Multiple Julia versions

One concern with an auto-updating installer is that one loses control over what Julia version one is using. Forced auto-updating to the latest Julia version seems a bad idea. So this is where my little project went a bit out of control... I ended up with the following design:

The main Julia MSIX installer package delivers two binaries: 1) a julia.exe that gets put onto the PATH, but really is just a launcher for the "real" julia.exe, and 2) a juliaup.exe (in the spirit of rustup) that one can use to manage which Julia versions are installed on a system.

So the main Julia MSIX installer package actually does _not_ contain any real Julia version. Instead, each Julia version is an optional MSIX package. So we have a Julia-1.4.0, a Julia 1.4.1 etc. optional package. The juliaup.exe is used to install and uninstall these optional packages. It supports commands like `juliaup add 1.4.2` (installs Julia 1.4.2), `juliaup rm 1.4.2` (removes Julia 1.4.2) etc. Another command is `juliaup setdefault 1.4.2`. This command configures which of the many installed Julia versions should currently be used.

Starting `julia.exe` now simply looks at the default configuration for the Julia version, checks whether that is installed, and then launches that specific Julia version.

The final piece in this is that the Julia MSIX installer (that only includes the launcher and juliaup.exe) also, by default, installs one of the optional Julia packages, currently Julia 1.6.1. So if a user installs the main package, then Julia 1.4.2 is automatically installed and configured as the default. So at first install one does not have to start `juliaup` at all to install an initial version or configure anything.

# Major problems

There are a bunch! Some of them I think have the potential to be deal breakers, unless we find some way around them. I have ideas for most of them, but here we go:

- [IJulia doesn't work](https://github.com/davidanthoff/winjulia/issues/2). There is a lot more information in that linked issue. Short version is that I think we could get around this if we put the installer into the Windows Store _and_ MS gives us some capabilities that installers normally don't have. The infrastructure for that is all in place, this really depends on a policy decision by MS. I'm fairly optimistic that this might work, I've been working with an engineer at MS and he has been really incredibly helpful, so the general vibe I'm getting from MS is very supportive. I don't think there is any way to solve this for the AppInstaller case, though.
- [Updates are broken](https://github.com/davidanthoff/winjulia/issues/3). There is a bug in the currently shipping version of the AppInstaller that makes the auto-update feature only work after a system restart... MS is aware of that and I assume they will fix this with an upcoming patch, so one option is to just wait. This would also be solved if we put the whole thing in the Windows Store, because then the AppInstaller part (where the bug is) doesn't come into play.
- Some random other issues that we can probably work around, see [here](https://github.com/davidanthoff/winjulia/issues) for my current list.

# Major design decisions

I think the biggest design decision is whether we are generally ok with the whole `juliaup` design and whether we are ok that `juliaup` uses a Windows only technology under the hood.

I think if we were to go with this solution, the eventual goal would probably have to be that on other platforms we try to create a similar experience, i.e. that `juliaup` is also available on at least Mac and probably all platforms. Under the hood it might use a different mechanism to actually deliver Julia versions (i.e. not MSIX but either a platform specific tech for Mac and Linux, or something home grown).

I _do_ think there are major benefits to using the optional package feature from the MSIX stack on Windows. For one, it makes everything incredibly simple. There is hardly any code at all to get the whole `juliaup` story going, most of the complexity of such a solution is handled by the MSIX engine. We also get a really nice integration with the Windows UI. For example, the app part in the settings will show the optional packages as optional packages for the main Julia package, and users can uninstall them from there directly. There is also a ton of deployment tools on Windows that all work with MSIX packages, so I think this might be the easiest way to e.g. deploy Julia on say on university managed Windows machines for students etc.

But, I feel this part really needs a lot of thinking.

Another thing to keep in mind is that this is Windows 10 only, so we would need to keep the existing installer around for older platforms. I'm not too worried about that, but others might feel differently.

# Try it out

You can give the current version of all of this a test run. It is not in the store, but uses the AppInstaller way of distributing things. Here is how you do it:

1. Make sure no julia.exe is on your PATH.
2. Head over to https://winjulia.david-anthoff.com.
3. Click install and follow the instructions.
4. Once everything is installed, you should be able to run `julia` and `juliaup` from any shell. `juliaup` should output instructions on how to use it.

The code for the whole MSIX installer is at https://github.com/davidanthoff/winjulia.

# Next steps

I think this will all require time to sort out. So right now I'm mainly keen to hear what others and the core think. Is this a good direction? Is there interest in pursuing this? Oh, and of course it would be good to hear whether things work for folks :)

If we feel that is worth following up with, we can figure out the next steps. I think it would probably entail me continuing to work with the engineer at MS to bring this whole thing into the Windows Store.

**Comment by ViralBShah** [comment]
Is this different from winget?

**Comment by musm** [comment]
> Is this different from winget?

Completely different.
winget is just a MSFT  sanctioned chocolatey 'clone' with a better design.

**Comment by ViralBShah** [comment]
Ok, but is it then useful to have both?

**Comment by musm** [comment]
The two are not mutually exclusive. julia is already on winget https://github.com/microsoft/winget-pkgs/pull/2418

**Comment by davidanthoff** [comment]
You'll be able to install store apps with winget, I believe that is one of the next features they are adding right now.

If we do go with a Windows Store story/MSIX, it would make sense to have winget install julia via the store app, not via the inno setup. Would be trivial to switch that over.

**Comment by ViralBShah** [comment]
Ok, makes sense. If we get this all going, then perhaps we can drop the inno setup and only distribute the portable binaries on the website.

**Comment by musm** [comment]
> Ok, makes sense. If we get this all going, then perhaps we can drop the inno setup and only distribute the portable binaries on the website.

Eventually yes that would make the most sense.  In the meantime, we would promote the MSIX installer and  portable  .zip package for special cases and leave the Inno for legacy systems.

**Comment by rapus95** [comment]
> I think if we were to go with this solution, the eventual goal would probably have to be that on other platforms we try to create a similar experience, i.e. that juliaup is also available on at least Mac and probably all platforms. Under the hood it might use a different mechanism to actually deliver Julia versions (i.e. not MSIX but either a platform specific tech for Mac and Linux, or something home grown).

As I'm obsessed with trying to solve every Julia related problem in Julia itself, I thought about creating a julia based updater multiple times. The obvious advantage would be the independency of the platform. For the current state of the idea I would also need a non-julian file (a proxying julia.exe) that works the same as yours, i.e. that it reads from a config which version to start (presumably support some command line arguments like `--version=1.4.1`) and passes all other arguments straight through to the actual julia.exe. For updating I imagine a Julia script which simply downloads the new version (maybe even via a new pkg server sub path) and simply updates the config file the proxy julia.exe relies on. In general, I mean, what's the problem with having the whole update functionality accessible from within Julia? (maybe in Pkg.jl)

**Comment by musm** [comment]
With the MSIX installer, you need to call Windows API which are easiest to access through c++and c#. It might be possible to have some of the `juliaup` core code in a julia package and call them through  c++. I'm not sure how hard or easy it is to do that. One tricky thing would be that the `juliaup` core would   have to be in-place update.  It might also make the whole `juliaup` process slower due to precompilation, unless we could precompile things.

**Comment by rapus95** [comment]
@musm as we intend to support having multiple versions installed at the same time I'm not sure if we even need to upgrade inplace. Instead we can just install the new version, triggering the new version and from there delete the old one. Alternatively though, there's an easy way in windows to upgrade inplace: Just move the original files away into some OS-managed temp directory for example (that's possible even while the file is locked) and put in the new files.
As the general question, is there anything against shipping new versions over the julia package server? (And at some point maybe even have it integrated with BinaryBuilder) (as I said, very julia centric xD)

**Comment by davidanthoff** [comment]
How do we move forward with this?

I think the next step would be to try to get this version into the Windows Store and start testing how things work with that environment. That will require sorting out who should appear as the publisher of the app in the store, my best guess right now is NumFOCUS maybe? It needs to be a legal entity that can get a code signing certificate. There are also next steps on the code for e.g. `juliaup`, but I think it would make more sense to first try whether the current prototype works in the store before we invest more time in fine tuning things.

I'd be happy to push this forward and see the whole store submission through, but only after we have come to some broad agreement whether the approach here is something that is acceptable and the core team is on board with it. Or to say it differently, I wouldn't want to spend a lot of time on the store submission process (which I expect to be somewhat painful and involved because we need various exceptions) only to have a discussion after that whether the design of `juliaup` here is ok or not. I think we should be able to come to a decision on that based on what exists today and before the store submission.

This is obviously not a niche question and probably would need a nod from many of the core folks? Who would that be? @StefanKarpinski could you help me manage that process, as the official "I get binary files onto user machines"-guru?

**Comment by StefanKarpinski** [comment]
> @StefanKarpinski could you help me manage that process, as the official "I get binary files onto user machines"-guru?

I think you have me confused with someone else 😬. @staticfloat maybe?

I don't know squat about Windows and have gotten pretty frustrated over the years with the seemingly endless discussions about how to improve Windows things that never seem to actually go anywhere. The first and only Julia issue that I've muted is the one about bundling a better terminal. If Windows is going to be better, Windows users need to step up and improve things. @musm has been doing great work, but he needs some help.

**Comment by staticfloat** [comment]
I don't have strong feelings on this; my gut instinct is to just empower people who are dealing with the rough edges of windows installation (e.g. @davidanthoff and @musm) to do what they think is best.  In fact, I would actually push against the assertion that we need a consistent `juliaup` experience across OS's and would say just build something fantastic on Windows, and if it works well and people really like it and Linux/MacOS get jealous, then we'll build something analogous on those systems.

The only constraints are:

* Windows installation from standalone .exe and .zip file will continue to work for the foreseeable future.  That will always be the best-tested method from my perspective, since it's what will continue to be used by CI and such.
* Packages should avoid depending too heavily on aspects of installation.  E.g. if we were to start bundling a small stand-alone Jupyter installation to ease IJulia installation on windows, I would want that to be done in such a way that it could auto-download whatever was bundled in the event that a user installs through a different mechanism.

Other than that, I see this kind of like another distribution packaging effort like the RPMs that nalimilan has built since forever.  I say go wild, and if there are roadblocks in your way on our end, (like that codesigning issue) continue to make noise so that it stays on our radar and we can get stuff fixed for you.

**Comment by staticfloat** [comment]
@davidanthoff can you verify that the latest nightlies are being signed more thoroughly, and will work for your purposes here?

**Comment by staticfloat** [comment]
Ah, I think I should have posted that message here instead: https://github.com/JuliaLang/julia/issues/25730

**Comment by davidanthoff** [comment]
I'm under water with teaching stuff right now. I've put it onto my todo list :)

**Comment by davidanthoff** [comment]
Alright, I won't have much time for actual coding on this until the end of the year, but the next steps are all logistics in any case, and I think we can try to move that forward. I think we should try to just get this into the store next because all of the problems we've still had were related to the non-store setup story, and I think those should go mostly away once this ships via the store. Only way to find that out, of course, is to actually put it into the store.

Here are the steps we need to do next:
- [ ] Get NumFocus in on this, when we last chatted about the plan we said they would be the "publisher" of Julia in the apps store.
- [ ] NumFocus will need to get a code signing certificate in their name and I need access to that so that I can sign things.
- [ ] NumFocus will have to create MS Partner Account and sign up as a app publisher for the Windows Store in their name.
- [ ] I need access to the MS Partner Account for app publishing.

@aviks, could you maybe introduce me to the right NumFocus folks to discuss this?

**Comment by musm** [comment]
Why does NumFocus have to get involved? We can just create a Julia publisher and manage that ourselves. I don't see why their sponsorship would warrant them to be the publisher?

**Comment by davidanthoff** [comment]
We need an official, legal entity that is the publisher. Both the code signing authority and the MS store will check whether the entity we submit exists in a legal sense. So if we wanted to submit this as "Julialang", we would probably have to start a non-profit organization, get the tax exempt status and all of that. That is a lot of work, and when @aviks and I chatted about this last time we came to the conclusion that NumFocus would be the much easier route here, if they are on board.

**Comment by musm** [comment]
There's so Julia Computing as an option?

**Comment by davidanthoff** [comment]
Yes, but when I talked with @aviks about this we both felt that it would not be appropriate for a private company like Julia Computing to "own" the store version of Julia.

**Comment by Keno** [comment]
Julia Computing is already the code signing entity for all Julia releases on all platforms and has been for years. I don't have anything against the NumFocus plan, but that just seems like extra effort when it sounds like all we have to do is for somebody to sign up for the MS account.

**Comment by davidanthoff** [comment]
Alright, I have a bit of time now and would like to finish this. Lets go with the Julia Computing idea that @Keno mentioned, just so that we can move forward. If everything works and is up and running _and_ someone at that point wants to migrate things over to some non profit, we can still do that.

@Keno, @staticfloat, @ViralBShah or @aviks I think the next step would be that you create a user account for me in your Azure AD tenant that is connected to the MS Partner Center, so that I can start the app creation process there. I think it would be easiest if I had an account where I can go through all the app submission things for now?

**Comment by aviks** [comment]
That sounds good, @davidanthoff . Happy to add you to the Azure AD account, but I don't believe that is connected to the partner center. I think our signing certificates are separately managed -- I'll try and find out.  I find the Microsoft identity services really confusing, we've had a lot of trouble with it. I'll connect with you separately to see what needs doing. If you have any documentation links of the windows store publishing process, that might help.

**Comment by davidanthoff** [comment]
I made some progress with this:
1. The updating story now seems to work in App Installer. In general, I made some changes that seem to make things a lot more robust.
2. I added full support for multiple binary platforms. So one now automatically gets the proper binary depending whether one is on x86 or x64 Windows, and if one is on x64 Windows one can also install x86 versions of Julia: `juliaup add 1.5.4-x86` etc. work now.
3. I added full support for numbered channels. So one can say `juliaup setdefault 1.5`, and that means "I want to use the latest build in 1.5.x". If a new build is released, one gets a notification "there is a new build in your channel, run `juliaup update` to install the latest build in your channel." The default channel is now `1`, i.e. 1.x.y. We also have 32 bit channels, so `juliaup setdefault 1.6-x86` for example also works if one wants a 32 build on a 64 bit OS.
4. I changed the set of support Julia versions to 1.5.1-1.6.1. I can't get earlier versions to work because the official binaries all have faulty code sign signatures on them, and then I can't package them into a MSIX. I think we would either have to somehow remove these faulty signatures from the official builds, or recompile everything...

So the next step is really just to get this into the Windows Store, I think other than that it is in pretty good shape. 

I also updated the links in the original post in this issue to point to the latest hosted build if anyone wants to try it out.

**Comment by davidanthoff** [comment]
Just a quick update: we now managed to create the necessary accounts for a Windows Store submission :) And I just submitted this to the store!

Now, this will still take a while because the current submission cannot work, we need to get various permissions from MS to use advanced features of the MSIX tech stack that are normally disabled for store apps. So, this might still all not come together, but I am making progress.

**Comment by davidanthoff** [comment]
Just a quick FYI: my MSIX installer is in the Windows Store now! I still have it unlisted because it is so WIP and many things don't work at the moment, but you can still try it via the link in the README at https://github.com/davidanthoff/winjulia.

The design now is quite a bit different than what I had described earlier, in particular I am no longer using MSIX optional packages at all. I think that might actually make it much easier to eventually port the julia version manager part of this (`juliaup`) to other platforms as well.

**Comment by davidanthoff** [comment]
So this has developed very nicely over the last weeks, and I think it is probably time to start a discussion whether this should become the default installer on Windows and how the road to that would look. For those of you who don't care about Windows: please also take a look, there is a secret hope to make all of this available on other platforms as well eventually.

A quick update on where we are now:
- The entire solution has been up in the Windows Store and public for a couple of weeks. As of today 307 people are using the Windows Store installer.
- There are no known bugs, I think from my end this is ready.
- Feedback in general has been very positive (mostly [here](https://discourse.julialang.org/t/ann-juliaup-preview-julia-version-manager-and-windows-store-installer/61920) but also on Slack and some other channels). We had one bug report, that issue is fixed now, other than that it seems to all work.
- The source code for all of this is at https://github.com/julialang/juliaup. The release process is completely automated with GitHub Actions, including support for pushing out test builds to a smaller group of testers etc.
- The quickest way to get a sense about the user experience and functionality is probably to watch my Juliacon talk [here](https://www.youtube.com/watch?v=rFlbjWC6zYA). I don't demo all features, but many.

I think the next steps should probably look something like this:
1. The core Julia team takes a look at the design. Do the `juliaup` commands make sense? Is the channel idea solid? I developed all of this pretty much by myself, but I think before we could even consider making this the default we need a very thorough round of feedback/buy-in/design iteration from the core Julia team. I think one crucial point there is that we should look at the current design as a blue print for other platforms as well, not just the current Windows version. I think if we do make this the default installer on Windows, we should also consider making `juliaup` and the entire design available on MacOS and Linux down the road as well.
2. Once we are done with 1, I think we probably would want to have a phase where the Store installer is highlighted on the homepage, but maybe not yet as the default? Not sure... But we could have something like: "Try the new experimental store installer" for a few weeks/months or something like that, before we switch fully over.
3. Another question is what happens with the old-style Windows installer? I think it would probably be best if in the end we have the Windows Store installer and a zip portable installer, and maybe we just retire the old installer on Windows? Not sure about this, though...

In general I think we should not rush anything here, because obviously we really don't want to end up with a setup story that is in any sense not functional :)

CC @staticfloat, @musm, @keno, @StefanKarpinski, @JeffBezanson, @ViralBShah, @aviks. Not sure who else should see this.

**Comment by KristofferC** [comment]
I tried it out and it worked well! The only annoyance was how many times Windows tried to get me to login... What is the advantage of installing the whole thing via Windows store instead of via a normal installer?

**Comment by ViralBShah** [comment]
Advantage through the store presumably is automatic updates. But does that mean that it always replaces the version of Julia you are running with the latest one? Or will it allow you to have multiple Julia releases installed at the same time?

**Comment by KristofferC** [comment]
> Or will it allow you to have multiple Julia releases installed at the same time?

Updating juliaup does not update julia AFAIU, you do that via the juliaup interface.

**Comment by ViralBShah** [comment]
I just watched @davidanthoff 's video, and this is perfect. I think this should be the default way to install Julia (`juliaup` does all the multiple versions and everything). Of course we'll have to keep the standalone installer for people who need it.

If I were a Windows user (I actually have a Windows laptop), I would exclusively use the store. And I would love to have this on the mac too, although I don't know how easy it is to get Julia into the Mac App Store.

**Comment by davidanthoff** [comment]
> The only annoyance was how many times Windows tried to get me to login... What is the advantage of installing the whole thing via Windows store instead of via a normal installer?

The store handles the automatic update of `juliaup.exe` and the `julialauncher.exe` for us (those are continually updated, without an option to opt-out), does the `PATH` management and all the other integration points etc. Was it bugging you to login with a Microsoft Account, like your Windows login? That is annoying... I think the store might also not work on Windows Server?

I started rewriting `juliaup` in Rust over the weekend. No, no joke :) It is almost done. I think that will make the cross-platform story much, much easier, and essentially we can just follow the `rustup` way of installing on Linux and Mac, and also use a similar strategy on Windows for folks that don't want to use the store, say on Windows Server. I have a more or less complete design in my head and I think it will be simple and not that much work actually. I'll ping here once I have a version that is ready to be tried out.

**Comment by StefanKarpinski** [comment]
> I started rewriting `juliaup` in Rust over the weekend. No, no joke :)

😬😭😂

**Comment by davidanthoff** [comment]
So the Rust rewrite is done and it works on Linux now :)

Who is our Mac deployment expert? I think it should not be difficult at all to make it work there as well, but I have some questions. In particular, if that person could chime in [here](https://github.com/JuliaLang/juliaup/issues/37) it would be great.

Also, I'm renaming this issue to `Juliaup` because this is no longer Windows or MSIX specific.

**Comment by davidanthoff** [comment]
And thanks to @staticfloat it now all works on Mac as well.

**Comment by ViralBShah** [comment]
Linking @davidanthoff 's JuliaCon talk here which shows a lot of the stuff discussed here: https://www.youtube.com/watch?v=rFlbjWC6zYA

**Comment by ViralBShah** [comment]
Once `juliaup` is ready to go, we should also request all the distro package managers to include it. Then you can download juliaup through the OS package manager, and use it to manage the various Julia versions.

**Comment by davidanthoff** [comment]
Yep, indeed! We've done that on arch linux already.

In my ideal world, `sudo apt install julia` would just pull down `juliaup` (even an old and outdated version) and then you can use that to get the latest version of Julia, or any other one for that matter. We're still some distance away from that, but if this could be a vehicle that allows us to get around slow distro cycles it would be great.

**Comment by ViralBShah** [comment]
The bigger problem with distros is that distro policies end up leading to them using their own LLVM which often doesn't carry our patches. We also do a lot of careful versioning in our package ecosystem to ensure correctness. So `juliaup` is a way around all of that.

I would have thought that the recipe would be `sudo apt install juliaup && juliaup <args>`. That way, we document very clearly that people are using their native package managers to install the julia installer.

**Comment by ViralBShah** [comment]
I just tried `juliaup` and it works great. Do we still need to leave this open?

**Comment by davidanthoff** [comment]
Agreed, we can close this here and track all remaining issues over at https://github.com/julialang/juliaup.
