### ISSUE TITLE
`10^10` gives 1410065488

### ISSUE THREAD

**Issue by rakesh4real** [JuliaLang/julia#36724]
```
>> 10^10
1410065488
```

`10^10` gives 1410065488 in my linux machine instead of 10000000000

**Comment by tomaklutfu** [comment]
If `Int===Int32` it is expected result of machine integer arithmetic. For reference [in the documentation](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/), the available maximum 32 bit signed number (`2^31-1 = 2147483647`) is less than absolute `10^10`.

**Comment by vchuravy** [comment]
See https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/ 

Julia uses machine integers with by default. It looks like you are on a 32-bit machine, or using a 32-bit variant.
Use 64 bit integers or big numbers.

```
julia> big(10)^10
10000000000

julia> Int32(10)^Int32(10)
1410065408

julia> Int64(10)^Int64(10)
10000000000
```

**Comment by rakesh4real** [comment]
Thanks @tomaklutfu and @vchuravy.
@rajesh-asapanna
