### ISSUE TITLE
RFC: style guide for documentation

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#36723]
Style questions arise frequently when writing documentation. For example,

1. `eg`, `eg.`, or `e.g.`?
2. footnotes before or after punctutation (eg `things,[^1]` or `things[^1],`)?
3. period before or after a closing parenthesis?

I would like to initiate discussion about whether we want to at least suggest a style guide for the manual (and to a smaller extent, docstrings) in CONTRIBUTING.md.

This would help contributors who are not native speakers of English and/or were not exposed to courses that discuss these issues (personally, English is my second language, and I find guides like these very helpful). It would also help in making the manual more consistent (for all the examples above, multiple alternatives exist in the docs) and reviews of docs PRs easier.

There are various alternatives for style guides:

1. The venerable [Chicago Manual of Style](https://www.chicagomanualofstyle.org/). Non-free, subscription required, but otherwise the most comprehensive (and frankly, probably overkill for Julia docs).
2. [Red Hat Style Guide](https://stylepedia.net/style/#resources). Maintained, CC SA-3.0, but only a fraction is relevant for our purposes.
3. [Microsoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/). License is unclear, seems to be free for personal & non-commercial use. Also has a lot of sections that are not relevant for us.
4. [Google Developers Docs Style Guide](https://developers.google.com/style). CC A-4.0 license, comprehensive, searchable and succinct.
5. [Apple Style Guide](https://help.apple.com/applestyleguide). Available online, but I don't think the license is free.

After looking at each of these, 

1. I would recommend the Google one because of the clear license, online availability, and the overlap with what we need,
2. probably mention the Chicago Manual as a suggestion for further reading if someone is interested (may be helpful in some corner cases).

**Comment by StefanKarpinski** [comment]
Is it awful that my reaction is that it doesn't matter at all if the manual is consistent about this? It's not a professionally published book, after all, it just needs to be understandable so that people can read it.

**Comment by tpapp** [comment]
Of course not, it's totally fine not to care about this.

However, some people *do* care, as evidenced by eg discussions of PRs. This could all be done in a nice friendly way, so that people who don't care can continue to do so, and people who do care and want to work on this have some guidelines so everyone is in agreement.

Eg minor style issues should of course not block a docs PR, but when people make suggestion for a correction it would be reasonable to accept it (especially if it is done via Github's suggested correction feature, then it is just a click).
