### ISSUE TITLE
add curried `isa`

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#36736]
I think, it would be nice to define `isa(T)` to return a curried version, because it's consistent with similar functions like `in` and often useful in `any` or `all`. It's a builtin function, so this would probably require some small changes, but it's already possible to shadow `isa` locally, so I believe this should be doable.

**Comment by jakobnissen** [comment]
It might be useful to read discussion in https://github.com/JuliaLang/julia/issues/33193 and in https://github.com/JuliaLang/julia/pull/24990.

In this case, `isa(T)` fits well with the criteria for adding curried methods mentioned in #33193, so there's that.

While you're right it would be nice in some circumstances, it quickly becomes a neverending discussion about which functions deserve currying, and which do not, similar to the endless joy we get from the ongoing discussion on `Missing`. Worse still, with every function we curry, we lay claim to a method that then cannot be defined in the future.

I think we should think hard about currying and not just do what's easy right now (namely to add curried versions of methods haphazardly).

**Comment by mcabbott** [comment]
I think this is a duplicate of #32018. Would be nice to have.

**Comment by simeonschaub** [comment]
Oops! I searched for issues, but somehow that escaped me.
