### ISSUE TITLE
Mention flag in nonstandard string literals docs

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#36773]
You can define code like this:
```
macro foo_str(str, flag)
    # do stuff
end
```
And "call" this macro with the following syntax: `foo"str"flag`. The feature of the `flag` is not documented in the [section of the docs mentioning string literals](https://docs.julialang.org/en/v1.6-dev/manual/metaprogramming/#Non-Standard-String-Literals-1). But it would be nice if it was.

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. I am new to contributing to Open Source projects some guidance would be helpful.

**Comment by jakobnissen** [comment]
@pret3nti0u5 That's great! There is a good tutorial for making a PR to Julia here: https://kshyatt.github.io/post/firstjuliapr/ . The tutorial covers adding new tests to Julia, but amending the docs is very similar. The file you want to change is `doc/src/manual/metaprogramming.md`.

Please ping me here on GitHub or PM me on the Julia slack if you need help :)

**Comment by pret3nti0u5** [comment]
Here's the [PR](https://github.com/JuliaLang/julia/pull/36881).

**Comment by JeffBezanson** [comment]
Fixed by #36881
