### ISSUE TITLE
Socket status and blocking

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/julia#36779]
I noticed that on Linux it's possible to determine whether a `TCPSocket` `read` will block by inspecting the socket status:
* `StatusOpen`: data available, `read` won't block
* `StatusPaused`: no data, `read` will block

On the other hand, on Windows the socket status remains `StatusOpen` in both cases.
Is this expected? 
Any similar hack that works on Windows?

**Comment by vtjnash** [comment]
`bytesavailable(s) != 0` on all platforms
