### ISSUE TITLE
Feature Request: even less safe `round`

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/julia#36788]
In my quest to implement a faster `exp` function, I discovered that to round floats between -2^52 and 2^52, you can simply perform

```
# magic rounding constant: 1.5*2^52 Adding, then subtracting it from a float rounds it to an Int.
MAGIC_ROUND_CONST(::Type{Float64}) = 6755399441055744.0
very_unsafe_round(x::T) where T<:Float64 =  (x+MAGIC_ROUND_CONST(T))-MAGIC_ROUND_CONST(T)
```
Note that similar functions can turn Float64 to `Int`, as well as round 32 bit floats.
The downside of this is that it works for an even smaller range of `Float` than `unsafe_round`.

Despite that, I think this might be a good function to have in Base Julia. (maybe spelled `unsafe_round(x;small=true)`?) Thoughts?

**Comment by FedericoStra** [comment]
Of course this does not work with `--math-mode=fast`:
```julia
julia> very_unsafe_round(4.5)
4.5
```
```julia
julia> @code_llvm very_unsafe_round(4.5)

;  @ REPL[2]:1 within `very_unsafe_round'
define double @julia_very_unsafe_round_17231(double) {
top:
  ret double %0
}
```
```julia
julia> @code_native very_unsafe_round(4.5)
	.text
; ┌ @ REPL[2]:1 within `very_unsafe_round'
	retq
	nopw	%cs:(%rax,%rax)
	nopl	(%rax,%rax)
; └
```

**Comment by FedericoStra** [comment]
It fails also in other cases, even with `--math-mode=ieee`:
```julia
julia> very_unsafe_round(4503599627370493.1)
4.503599627370492e15
```
Notice that `4503599627370493.1 < 4503599627370496 = 2^52`, so the correct answer should be `4.503599627370492e15`.
