### ISSUE TITLE
julia REPL exits instantly after startup with no error message

### ISSUE THREAD

**Issue by lindnemi** [JuliaLang/julia#36791]
I can run scripts but the REPL immediately exits with no indication why.

julia version 1.5.0-rc1

https://gist.github.com/lindnemi/995ae4d9a02a61b64094eec67b666fe0

**Comment by lindnemi** [comment]
This is what i get in a terminal
```user@machine:~> strace --output=gist.txt julia
using Revise...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0-rc1.0 (2020-06-26)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> user@machine::~> ```

**Comment by lindnemi** [comment]
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by StefanKarpinski** [comment]
What is in your startup.jl file?

**Comment by lindnemi** [comment]
My startup.jl used some Julia <=1.4 guidelines
```
println("using Revise...")
atreplinit() do repl
# deprecated
#=
    try
        @eval using Pkg
        haskey(Pkg.installed(), "Revise") || @eval Pkg.add("Revise")
    catch
    end
=#
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
    catch
    end
end
```

Replacing this by `using Revise` solved the problem.

**Comment by timholy** [comment]
See https://discourse.julialang.org/t/psa-pin-revise-at-2/44412
