### ISSUE TITLE
defining functions kills the julia interpreter

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#36804]
Hi,
I just stumbled upon a pecularity when defining certain functions. I am not sure, whether this is expected, but it looks quite frightening from a user perspective.

The following code will kill my julia repl (actually sometimes it resulted in a StackOverflow instead, however now it is always killing it immediately)
Copy paste
```julia
const Either{L, R} = Union{Some{L}, Ref{R}}
f(::Type{Either{L2, R}}, ::Type{Either{L1, R}}) where {L1, R, L2 <: L1} = Either{L1, R}
f(::Type{Either{L, R1}}, ::Type{Either{L, R2}}) where {L, R1, R2 <: R1} = Either{L, R1}
```
and boom.

my versions:
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by fredrikekre** [comment]
Probably it breaks some internal functions similar to  #35436 and linked issues?

**Comment by thofma** [comment]
He is not overloading a Base function though. All the linked issues overloaded a Base functions.

**Comment by vtjnash** [comment]
Yeah, this is a type system bug

**Comment by JeffBezanson** [comment]
Looks similar to #36185 and #36544, possibly same issue.

**Comment by zdroid** [comment]
I believe re-ordering the 2nd and 3rd declarations solves your issue:
```julia
const Either{L, R} = Union{Some{L}, Ref{R}}
f(::Type{Either{L, R1}}, ::Type{Either{L, R2}}) where {L, R1, R2 <: R1} = Either{L, R1}
f(::Type{Either{L2, R}}, ::Type{Either{L1, R}}) where {L1, R, L2 <: L1} = Either{L1, R}
```
But I have no clue why does it solve your issue, though.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/38423 might be a dup of this.
