### ISSUE TITLE
Undefined modules on remote results in a hanging remote call on the caller. 

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#3680]
Running the below code results in worker 2 exiting.

```
module MFoo
    function foo(f, args...)
        remotecall_fetch(2, () -> f(args...))
    end
end

addprocs(1)

MFoo.foo(myid)
```

Related to https://github.com/JuliaLang/julia/issues/3674

edit : Jump to https://github.com/JuliaLang/julia/issues/3680#issuecomment-229683913

**Comment by IainNZ** [comment]
@amitmurthy is this still an issue?

**Comment by amitmurthy** [comment]
Yes. May not affect typical use cases, but still an open issue.

**Comment by andreasnoack** [comment]
Is it possible to do anything here? It's really a bad experience to see all your workers die.

**Comment by amitmurthy** [comment]
Currently we cannot recover after a partial deserialization from the stream. An alternative could be:

In script mode, this is really a fatal error and I don't see how one can proceed after this. We can send back a proper error message, say `RemoteErrorMsg`, from the worker before termination. It will not be associated with any remote reference but will just be printed out to STDERR on the master.

In interactive mode, the worker does not terminate, but waits(with a timeout) for a reconnection from the master. Both `SSHManager` and `LocalManager` will automatically reconnect on worker disconnect (after receiving a `RemoteErrorMsg`) if `isinteractive()` is `true`. Other ClusterManagers will have to be updated to perform a reconnect for this event. Any messages sent (but not received) in the previous connection will be lost. It is upto the user to redo the previous command(s) as the case may be.

**Comment by andreasnoack** [comment]
Actually, I think the main issue here is #3674. If that was fixed then this wouldn't really be a problem. Continuing there...

**Comment by amitmurthy** [comment]
https://github.com/JuliaLang/julia/pull/13795 fixes the worker death issue. But for the specific examples mentioned here, the remote call does not return and we need to do a Ctrl-C to get back the prompt. Subsequent remote calls go through fine, which indicates that the stream state has been recovered properly - the issue remaining is one of notifying waiting tasks on the caller in certain cases. 

Changing the title of this issue to reflect the same.
