### ISSUE TITLE
BitArray contains random bits on initialization

### ISSUE THREAD

**Issue by Ferroman** [JuliaLang/julia#36800]
I'm not sure is its intended, but I expect to have all bits set to `0` on initialization of BitArray. Feels like a bug to me. 

```
~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> BitArray(undef, 128)
128-element BitArray{1}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1 <- ?
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
```

**Comment by rfourquet** [comment]
This is intended behavior, as specified by `undef`, whose docstring says:

> `undef`

>  Alias for UndefInitializer(), which constructs an instance of the singleton type UndefInitializer, used in array initialization to indicate the array-constructor-caller would like an uninitialized array.

Use `falses` or `trues` for initialized `BitArray`s.

**Comment by KristofferC** [comment]
The `undef` constructor will not initialize memory. That is intended.
