### ISSUE TITLE
Define adjoint for nothing ?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaLang/julia#36816]
When you have nothing in a matrix and you take its transpose any code that touch the nothing will throw an error, e.g.

```
julia> filter(isnothing, [1 2; nothing 4]')
ERROR: MethodError: no method matching adjoint(::Nothing)
Closest candidates are:
  adjoint(::Missing) at missing.jl:100
  adjoint(::Number) at number.jl:169
  adjoint(::LinearAlgebra.Adjoint) at /Users/sabae/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/adjtrans.jl:164
  ...
```

Since we have `adjoint(::Missing) = missing` I feel like we should have the same thing for Nothing, or is there issues with that ?

https://github.com/JuliaLang/julia/blob/de9c371e0f663132d526d6180e144a0fabd8c958/base/missing.jl#L97

```
julia> versioninfo()
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.4.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
`nothing` is not supposed to propagate like that. It seems you should be using `permutedims` which is just an array operation, as opposed to adjoint which is a mathematical one.

**Comment by jonathanBieler** [comment]
Why is it defined for Missing though ? It doesn't seems much more mathematical than Nothing.

**Comment by KristofferC** [comment]
The docstrings for missing says that it propagates its value for various mathematical operators. I guess `adjoint` is included in that list. But yes, it's pretty arbitrary.

**Comment by jonathanBieler** [comment]
I see, to give a bit of context this can lead to some surprising results, since the error doesn't occur when taking the adjoint but later on when you try to access a nothing element, it can be pretty random and it took me a while to understand what was going on. Also displaying the matrix in the REPL crashes depending on the position of the nothing in the matrix, so your matrix call look fine when you look at it even though it's in a unusable state.

But looking at the list of methods it's true that adjoint is defined mostly for matrices and numbers, it would be a bit weird to have nothing in there.
