### ISSUE TITLE
Union splitting performance issue

### ISSUE THREAD

**Issue by kwdye** [JuliaLang/julia#36822]
I ran into what seems to be an issue with how the compiler is handling union splitting.  
```
using BenchmarkTools

struct Foo
    a::Int
    b::Int
end

struct Bar
    a::Int
    b::Int
end

function compute(v::Foo)
    return v.a + v.b
end

function compute(v::Bar)
    return v.a - v.b
end

function compute_x_isa(t, x, kinds)
    if t[x] isa Foo
        return compute(t[x])
    else
        return compute(t[x])
    end
end

function compute_x_assert(t, x, kinds)
    if kinds[x] == 0
        f::Foo = t[x]
        return compute(f)
    else        
        b::Bar = t[x]
        return compute(b)
    end
end

function compute_many_isa(t)
    kinds = [0;1]
    idxs = rand([1;2],100)
    s = 0
    for ii in 1:100
        s += compute_x_isa(t, idxs[ii], kinds)
    end
    s
end

function compute_many_assert(t)
    kinds = [0;1]
    idxs = rand([1;2],100)
    s = 0
    for ii in 1:100
        s += compute_x_assert(t, idxs[ii], kinds)
    end
    s
end

let 
    ff = Foo(1,2)
    bb = Bar(2,1)
    tt = (ff,bb)
    kinds = [0;1]

    @btime compute_x_isa($tt, 1, $kinds)
    @btime compute_x_isa($tt, 2, $kinds)
    @btime compute_many_isa($tt)
    @btime compute_x_assert($tt, 1, $kinds)
    @btime compute_x_assert($tt, 2, $kinds)
    @btime compute_many_assert($tt)
end

output:
  0.020 ns (0 allocations: 0 bytes)
  0.020 ns (0 allocations: 0 bytes)
  4.682 μs (403 allocations: 16.69 KiB)
  22.704 ns (2 allocations: 80 bytes)
  22.751 ns (2 allocations: 80 bytes)
  3.066 μs (203 allocations: 8.88 KiB)
```
So compute_x_isa works() as expected, creating compile-time dispatch to compute().  In a tight loop (compute_many_isa())   it appears to no longer be able to do this optimization.  compute_x_assert() has much worse performance even though, since f and b's types are asserted, the compiler seems like it should have enough information to do compile-time dispatch to compute().  And then mysteriously compute_many_assert() performs better than compute_many_isa().  

After a discussion on slack it seems like there may be an issue here.  Or perhaps I am doing something wrong with my code or the testing setup?   This was done on 1.5.0-rc2

Edit: the discrepancy between compute_x_isa and compute_many_isa makes me think that the good performance of compute_x_isa by itself is due to constant propagation not union splitting.

**Comment by vtjnash** [comment]
I'm not sure you are getting anything related to what you expect. In the first couple, your measured processor speed reported is something well in excess of 50 GHz, so that must just be . You also aren't using the `isa` information (you're branching on the type of `t[x]`, then using the \*unrelated\* value `t[x]`), nor have you written a type-assert on `f` and `b` (by putting it on the LHS, you've written a call to `convert` instead).

The performance cost of dynamic dispatch also just isn't very large:
```
function compute_x_isa(t, x, kinds)
    tx = t[x]
    return tx isa Foo ? compute(tx) : compute(tx::Bar)
end
```
vs.
```
compute_x_isa(t, x, kinds) = compute(t[x])
```
with
```
tt = Any[ff,bb]
```
gives just 4.099 ns vs 17.829 ns

**Comment by vtjnash** [comment]
> mysteriously compute_many_assert() performs better than compute_many_isa().

I'm not sure about this effect fully either, but note that the loop you're interesting in testing should not need to contribute any significant portion to the measurement time, since this loop is so much faster than random number generation.

**Comment by kwdye** [comment]
I think maybe I wasn't clear about what my concerns were with these results.  Im most concerned about not time but tiny allocations (in this case they are a result of runtime dispatch I believe).  I'm not sure what you mean by "You also aren't using the isa information (you're branching on the type of t[x], then using the *unrelated* value t[x])" but whatever compute_x_isa() is doing, it is causing the compiler to do the call to compute() at compile time, which is great.  And the issue with compute_x_assert() is that, even though Im doing a conversion not a type assert, shouldnt the compiler know the type of the argumentsto compute() and therefore be able to do compile time dispatch?  The fact that compute_x_assert() allocates makes me think it is doing runtime dispatch.  

You're right the performance difference isn't that much in terms of time, but Im more worried about the small allocations because of threaded work Im doing.  I filed this issue because Im trying to understand how to reliably do union-splitting so I can avoid runtime dispatch-related allocations.

**Comment by vtjnash** [comment]
The compiler is just outwitting you here, and causing you to measure things in your benchmarks completely unrelated to your stated goals (of understanding union splitting)—often just artifacts of the test harness. You gave it a little bit of information you probably didn't mean to by using a tuple, and then asked it to do simple things that it realized it could just ignore. The `compute_many` test isn't a tight loop—it's just a benchmark of `rand` performance.
