### ISSUE TITLE
Export tuple type length function

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#36820]
_Originally posted by @NHDaly in https://github.com/JuliaLang/julia/pull/32427#discussion_r454551823_

#32427 added an unexported function, `_counttuple(::Type{<:Tuple})` which returns the number of elements in the tuple type.

Can we name this something not private and export it? This is something we use all the time in our code at RelationalAI, where we do a lot of stuff with tuples. It also seems like something that other code will use a lot, like DataFrames, CSV, etc.

In that other comment I suggested `arity(::Type{<:Tuple})` as one suggestion. I still like that best, but open to others!
- `arity()`
- `tupletypewidth()` / `tuple_type_width()`
- `tupletypecount()` / `tuple_type_count()`
- `tuplearity()`
- `tupletypelength()` / `tuple_type_length()`

**Comment by NHDaly** [comment]
This was originally proposed as a fast implementation for `fieldcount(::Type{<:Tuple})`, but it was deemed that adding methods to `fieldcount` isn't worth the cost for potential dynamic dispatches: https://github.com/JuliaLang/julia/pull/32495.

**Comment by kahanikaar** [comment]
Can I work in this issue? @NHDaly

**Comment by NHDaly** [comment]
@vtjnash - what do you say? Do you have a preference on any of the names proposed above? ❤️ 

It would be great to allow @kahanikaar to pick this up :)

**Comment by NHDaly** [comment]
@kahanikaar - Thanks for offering to help! Welcome to the community! 😁
I may have been a bit over-zealous in adding the `good first issue` label: I think it _would_ be a good first issue, but it's slightly blocked on a decision to pick a name. 😊

That said, if you want to give this a shot and open a PR, we can always work-shop the name in the PR!

I think resolving this issue would involve starting from this function:
https://github.com/JuliaLang/julia/blob/11cbaf67b6fb5973f95d704a7a372cb43d770d62/base/tuple.jl#L17-L20

and _renaming_ it to one of the above choices, and then adding a nice docstring to it! :)

We might also want to add it to the `export`ed names, here:
https://github.com/JuliaLang/julia/blob/master/base/exports.jl

And finally depending on if there are already people relying on the existing name, `_counttuple` maybe keeping that name as an _alias_ to the new name (i.e. `const _counttuple = <new name here>`).

Let me know if you have questions!

**Comment by kahanikaar** [comment]
Initial PR made. Do review @NHDaly @vtjnash

**Comment by NHDaly** [comment]
Closing this, as `fieldcount` is now statically inferred in the compiler:
https://github.com/JuliaLang/julia/pull/39755#issuecomment-797011828
https://github.com/JuliaLang/julia/pull/39755#issuecomment-797013808
