### ISSUE TITLE
Support for Renoir Zen 2 CPUs

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#36826]
On a laptop with a Ryzen 7 4700U CPU running Windows 10, this is what is being reported (also reported on [Discourse](https://discourse.julialang.org/t/how-to-correctly-install-julia-in-renoir-platform/43756/1) under WSL2):

```
julia> versioninfo()
Julia Version 1.5.0-rc2.0
Commit 7f0ee122d7 (2020-07-27 15:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)

julia> LinearAlgebra.versioninfo()
BLAS: libopenblas (OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=32)
LAPACK: libopenblas64_
```

As far as I can tell, LLVM 9 should support `znver2`, and OpenBLAS should as well.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/36502

**Comment by jebej** [comment]
This patch seems to have been included in rc2, which was the version I tried...

**Comment by yuyichao** [comment]
No it's not. Only the bug fix part of it was.

**Comment by jebej** [comment]
I see, so support will only come in 1.6 then?

**Comment by yuyichao** [comment]
It should be **in** 1.6.

**Comment by jebej** [comment]
I tried a nighly and got this:
```
julia> versioninfo()
Julia Version 1.6.0-DEV.548
Commit 9267bbf1fc (2020-07-27 16:57 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, btver1)

julia> LinearAlgebra.versioninfo()
BLAS: libopenblas (OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=32)
LAPACK: libopenblas64_
```

**Comment by yuyichao** [comment]
AFAICT our detection code is identical to LLVM's. And previously you saw a "better" result since the detection code misidentify it as zen1 and bypassing LLVM ones. If you can find out your CPUID it'll be pretty easy to add it to the list of znver2 ones.

Also, for the openblas issue, you should report to https://github.com/xianyi/OpenBLAS instead. AFAICT we are using a version witht identical AMD CPU detectiton as the latest master there.

**Comment by jebej** [comment]
CPUID:
```
CPUID signature: 860F01
Family: 23 (017h)
Model: 96 (060h)
Stepping: 1 (01h)
```

Full info uploaded to cpu-world: http://www.cpu-world.com/cgi-bin/CPUID.pl?CPUID=71632

**Comment by jebej** [comment]
Regarding OpenBLAS, that might not necessarily be their fault, on Discourse, the OP installed the package from AUR and the architecture got detected properly:

> Update: I reinstalled and reconfigured the libopenblas from AUR, now the system Julia has:
> 
> julia> LinearAlgebra.versioninfo()
> BLAS: libopenblas (OpenBLAS 0.3.10 NO_AFFINITY USE_OPENMP ZEN MAX_THREADS=12)
> LAPACK: liblapack

**Comment by jebej** [comment]
Thanks! Do you think the fix could be backported to 1.5?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/pull/36831 is for master only so it won't be backported unless is. And you aren't missing out much on 1.5. It's identified as zen 1 which affects the scheduling module a little bit but none of the feature detection are affected.

**Comment by stillyslalom** [comment]
I have a Renoir processor that's correctly detected as `znver2` by `versioninfo()`, but it's still described as `Prescott` in `LinearAlgebra.versioninfo()` on latest nightly, which leads to terrible BLAS performance:
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.580 (2020-08-04)
 _/ |\__'_|_|_|\__'_|  |  Commit 8a6656016b (0 days old master)
|__/

julia> versioninfo()
Julia Version 1.6.0-DEV.580
Commit 8a6656016b (2020-08-04 16:02 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 9 4900HS with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 8

julia> using LinearAlgebra

julia> LinearAlgebra.versioninfo()
BLAS: libopenblas (OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=32)

julia> BLAS.set_num_threads(1)

julia> peakflops()/1e9
18.47128632768085
```

**Comment by yuyichao** [comment]
Yes, that's OpenBLAS issue. Ref https://github.com/xianyi/OpenBLAS/issues/2738 . We need to carry patch and/or bump openblas version.

Also, openblas is in general way too conservative on the dispatch. It appears to never dispatch based on features and only look for exact uarch match without a gental fallback...

**Comment by jebej** [comment]
In the meantime you can use an environment variable as explained on discourse: `OPENBLAS_CORETYPE=ZEN`.

**Comment by stillyslalom** [comment]
Can confirm, I'm seeing (roughly) expected speeds now:
```
julia> BLAS.set_num_threads(1)

julia> peakflops(4000)/1e9
61.15865161036225

julia> BLAS.set_num_threads(8)

julia> peakflops(4000)/1e9
225.9833945035955

julia> BLAS.set_num_threads(16)

julia> peakflops(4000)/1e9
239.07667095448187
```
