### ISSUE TITLE
Broken test coverage of functions inside functions 

### ISSUE THREAD

**Issue by guyvdbroeck** [JuliaLang/julia#36825]
I'm having some trouble getting Julia to properly compute my test coverage. 

A simple example of what goes wrong is in https://codecov.io/gh/Juice-jl/LogicCircuits.jl/src/257b9a792cb506329c7bb27e2ddfdedb1a097af7/src/LoadSave/vtree_line_compiler.jl
As you can see, there are functions defined inside of another function, and these are not accounted for properly. The code on line 45-48 is clearly not dead, and is actually executed in the unit tests, but not accounted for. Meanwhile the function headers on lines 44 and 50 are marked as not covered, even though they are executed during test.

Similar issues can be seen in other parts of my code that have a similar pattern: https://codecov.io/gh/Juice-jl/LogicCircuits.jl/src/257b9a792cb506329c7bb27e2ddfdedb1a097af7/src/LoadSave/circuit_line_compiler.jl
What's obviously a bug here is that some function bodies are covered, while their headers are not, which should be impossible.

**Comment by vtjnash** [comment]
It's a bit of a bigger bug, but I'm going to close this for at least the cases that aren't explicitly evil:
```
julia> @eval function f()
           $(Expr(:line, 6))
           nothing
       end
f (generic function with 1 method)

julia> @code_lowered f()
CodeInfo(
    @ REPL[1]:3 within `f'
1 ─     return Main.nothing
)

julia> ans.linetable
3-element Vector{Any}:
 Core.LineInfoNode(Main, :f, Symbol("REPL[1]"), 2, 0)
 Core.LineInfoNode(Main, :f, Symbol("REPL[1]"), 6, 0)
 Core.LineInfoNode(Main, :f, Symbol("REPL[1]"), 3, 0)

julia> f()
```
