### ISSUE TITLE
Can we add an inverse mod function?

### ISSUE THREAD

**Issue by jakewilliami** [JuliaLang/julia#36833]
e.g., 

```julia
function invmod(a::Integer, m::Integer)
    g, x, y = gcdx(a, m)
    if isone(g)
        return mod(x, m)
    else
        error("Modulo inverse of ", a, " modulo ", m, " does not exist")
        return
    end
end
```

It feels like this would be easy to implement.  Let me know if you think not enough people would benefit from having this in base.

**Comment by JeffBezanson** [comment]
This function already exists.

**Comment by jakewilliami** [comment]
Oh, really?  Couldn’t seem to find it in the docs.  I had no idea, sorry about this.

**Comment by yuyichao** [comment]
https://docs.julialang.org/en/v1/search/?q=invmod
https://docs.julialang.org/en/v1/base/math/#Base.invmod

while the doc search still misses a lot of stuff, function name search seems fine.

**Comment by jakewilliami** [comment]
@yuyichao I searched “inverse mod” and couldn’t find it in the Base.mod section (which I thought it would have reference to).  I see now that is I scrolled down quite a bit I would have found it.  That’s my bad

**Comment by yuyichao** [comment]
Nah, searching free words is still not so good. I'm just amused that you come up with the exact function name that is actually searchable easily in the doc...

**Comment by jakewilliami** [comment]
Oh right haha, yeah, in the function that I wrote for this I called it inverseModulo, but renamed the function for this “issue”
