### ISSUE TITLE
A power z^n of a complex number z is well defined  only when n is an integer, but cis function does not obey this rule

### ISSUE THREAD

**Issue by scaevola** [JuliaLang/julia#36839]
Here is the test code:
```julia
angles=[4,3,2,1,1/2,1/3,1/4,1/16]
print_e_over_i(x::Real)=begin
    res=cis(x)^(x)
    println("x: $x: $res")
end
print_e_over_i.(angles)
```

**Comment by fredrikekre** [comment]
What is the issue? Code runs fine for me.

**Comment by scaevola** [comment]
Power of a complex number is **only** well defined for integer n. It should give an error for 1/2.

**Comment by fredrikekre** [comment]
I think it is pretty standard behavior to compute the one with the smalles phase angle, you get the same results in e.g. python, octave etc.

**Comment by yuyichao** [comment]
> Power of a complex number is well defined only for integer n

No. It is only single value for integer n but I believe it is well defined for all other values. There's branch cut for all the rest.

**Comment by scaevola** [comment]
if this is true, Euler's Formula is wrong. Here are results for e^i :
```
x: 4.0: -0.9576594803233847 - 0.2879033166650651im
x: 3.0: -0.9111302618846769 + 0.41211848524175654im
x: 2.0: -0.6536436208636119 - 0.7568024953079283im
x: 1.0: 0.5403023058681398 + 0.8414709848078965im
x: 0.5: 0.9689124217106447 + 0.24740395925452294im
x: 0.3333333333333333: 0.993833508538892 + 0.11088262850995298im
x: 0.25: 0.9980475107000991 + 0.0624593178423802im
x: 0.0625: 0.99999237061517 + 0.0039062400659001166im
```

**Comment by yuyichao** [comment]
No you need `cis(x)^(1/x)`. (Also you are calculating i over e not e over i). And then it'll only work in a certain range when there's no "wrap around" and you pick the correct branch cut annd within rounding errors.
