### ISSUE TITLE
Docs (Manual): Add missing types of blocks  in scoping-table

### ISSUE THREAD

**Issue by dojt** [JuliaLang/julia#36837]
The table has no entries for functions and `do`-blocks. Functions are explained in the text, but should also be in the table.

https://github.com/JuliaLang/julia/blob/master/doc/src/manual/variables-and-scoping.md#scope-constructsid-man-scope-table

**Comment by StefanKarpinski** [comment]
Since `do` blocks are entirely normal function bodies, they are implicitly included here, but I suppose it wouldn't hurt to spell it out.
