### ISSUE TITLE
Automatically use sysimages located in project dirs?

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#36840]
The Julia VSCode extension automatically activates a sysimage (if named "JuliaSysimage.{dll,so}") in the active Julia project directory: https://www.julia-vscode.org/docs/stable/userguide/compilesysimage/

Maybe this would be a neat default behavior for Julia itself? Since Julia sysimages are tightly coupled to the package versions that were used in their creation, it makes sense to keep them together with "Project.toml" and "Manifest.toml". Loading them automatically would help avoid user errors (combining the wrong sysimage and project), especially for less experience users. 

Now that PackageCompiler has become quite easy to use, I think automatic sysimage loading could motivate users to use them more (and reduce complaints about load/first-plot times).

IJulia would automatically profit from this as well, as it already activates projects if find in the notebook's path automatically.

CC @davidanthoff 

My apologies in case this has already been suggested.

**Comment by oschulz** [comment]
Would this be allowable in principle (since it would add behavior to `--project` that `Pkg.activate` can't support inside of a running Julia session)?

**Comment by marius311** [comment]
Just want to second this idea. Have been using VSCode's PackageCompiler integration for a while now, and PackageCompiler has been impressively robust and the integration is incredibly convenient. On the Julia side, I can imaging having a flag like `JULIA_USE_PROJECT_SYSIMAGE=true` or something which makes it so on startup, Julia loads a `JuliaSysimage.so` file if it exists in the environment which is activated at startup, and if its up-to-date (or if its there but its out of date, issues a warning).

**Comment by KristofferC** [comment]
See https://github.com/JuliaLang/Pkg.jl/issues/2008, https://github.com/JuliaLang/julia/pull/35794 for some more info regarding thios.

**Comment by oschulz** [comment]
Oh, nice - should we close this issue here, then?

**Comment by KristofferC** [comment]
Can keep it open, always fun to close issues when merging PRs.

**Comment by oschulz** [comment]
Good point! :-)

**Comment by oschulz** [comment]
We can definitely close this, pkgimages are so much better.
