### ISSUE TITLE
mkpath() timing problem 

### ISSUE THREAD

**Issue by eloop** [JuliaLang/julia#36848]
mkpath() can have a timing problem such that if the directory(s) is created by another program while mkpath is running you can end up with this error. Is it up to the user to catch this or should mkpath() handle it?

ERROR: LoadError: IOError: mkdir: file already exists (EEXIST)
Stacktrace:
 [1] uv_error at ./libuv.jl:97 [inlined]
 [2] mkdir(::String; mode::UInt16) at ./file.jl:177
 [3] mkpath(::String; mode::UInt16) at ./file.jl:227
 [4] mkpath at ./file.jl:222 [inlined]

Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel Core Processor (Skylake, IBRS)
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)

**Comment by simonbyrne** [comment]
This should be fixed by #36126.
