### ISSUE TITLE
Date function converting string to date incorrect

### ISSUE THREAD

**Issue by ma010** [JuliaLang/julia#36846]
I had a date in string formate, e.g., `dt = "2020-05-29 23:02:36.406"`. I applied the following:
`using Dates`
`Date(dt, Dates.DateFormat("yyyy-mm-dd HH:MM:SS.ms")`

The result was `2020-04-29` instead of `2020-05-29`.

**Comment by fredrikekre** [comment]
`"yyyy-mm-dd HH:MM:SS.ms"` should be `"yyyy-mm-dd HH:MM:SS.s"` otherwise you parse the month (4) from the first two digits of the milliseconds.

Perhaps formats with e.g. `m` in multiple positions like that should error?

**Comment by ma010** [comment]
Ah, I see. Changing to `.s` at the microseconds level did solve my issue. Thank you for the prompt response!
