### ISSUE TITLE
@async error() isn't being printed

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#36854]
From searching, I thought there were fixes for this, but I'm still seeing no printed error on a current nightly:

```
julia> versioninfo()
Julia Version 1.6.0-DEV.551
Commit 470dfa6302 (2020-07-29 07:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 4700U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, btver1)
Environment:
  JULIA_NUM_THREADS = 8

julia> function f()
        @async error()
        println("done")
       end
f (generic function with 1 method)

julia> f()
done
```

**Comment by StefanKarpinski** [comment]
By design. If you don't wait for the result, then it vanishes. Either wait on the result or wrap this in `@sync`.
```jl
julia> function f()
           @sync begin
               @async error()
               println("done")
           end
       end
f (generic function with 1 method)

julia> f()
done
ERROR: TaskFailedException:
```

**Comment by robsmith11** [comment]
My actual code has two async thread that should be long-running.  Is there no way to get an exception from one thread when the other thread never finishes?

Example:
```
@sync begin
        @async error()
        @async while true
         sleep(1)
        end
       end
```

**Comment by JeffBezanson** [comment]
I recommend wrapping the task in a "monitor" task for debugging:
```
macro monitored_async(expr)
    quote
        t = @async $(esc(expr))
        try
            wait(t)
        catch
            display(t)
        end
    end
end

@sync begin
    @monitored_async error()
    @async while true
        sleep(1)
    end
end
```

**Comment by JeffBezanson** [comment]
Or, if you want the entire `@sync` block to propagate an exception as soon as one of the enclosed tasks errors, see `Experimental.@sync`.

**Comment by robsmith11** [comment]
Thanks!  `Experimental.@sync` is exactly what I want.

Selecting on multiple tasks had also worked:
https://github.com/NHDaly/Select.jl
