### ISSUE TITLE
Cannot transpose sparse matrix of Nothing 

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#36871]
This fails (Julia 1.5.0-rc2):

```Julia
julia> using SparseArrays
julia> sparse(sparse([1],[1],[nothing])')
ERROR: MethodError: no method matching copy(::Nothing)
```

I create a sparse matrix with `nothing` entries. I do so because I only need this to store adjacency information, I don't need to store actual data. Transposing such a matrix fails. (I want to actually do the in-memory transposition because this will make later access patterns more efficient.)

One solution would be adding a method `copy(::Nothing)`.

**Comment by fredrikekre** [comment]
Same as https://github.com/JuliaLang/julia/issues/36816

**Comment by fredrikekre** [comment]
Btw, you can/should use `permutedims`:
```julia
julia> A = sparse([1, 2],[1, 3],[nothing, nothing], 3, 3)
3×3 SparseMatrixCSC{Nothing,Int64} with 2 stored entries:
  [1, 1]  =  nothing
  [2, 3]  =  nothing

julia> permutedims(A)
3×3 SparseMatrixCSC{Nothing,Int64} with 2 stored entries:
  [1, 1]  =  nothing
  [3, 2]  =  nothing
```

**Comment by eschnett** [comment]
Thanks!
