### ISSUE TITLE
Microsoft C type aliases (DWORD, etc.) in Base

### ISSUE THREAD

**Issue by mgkuhn** [JuliaLang/julia#36884]
Julia currently defines in [`base/ctypes.jl`](https://github.com/JuliaLang/julia/blob/master/base/ctypes.jl) useful type aliases such as `Cint`, `Cuint`, `Clong`, etc. to make it easy for `ccall` users to refer to the types commonly used in the definition of standard C functions.

Unfortunately, Microsoft does not use these standard C types in its Win32 APIs. They have instead defined in [Appendix A of [MS-DTYPE]](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/24637f2d-238b-4d22-b44d-fe54b024280c) their own list of C types, such as `BOOL`, `PBOOL`, `DWORD`, `PDWORD`, `LPDWORD`, `DWORD32`, `DWORD64`, `PDWORD64`, `ULONGLONG`, etc. These [Windows Data Types](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) aliases are used pervasively throughout the [Windows API documentation](https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-api-list), as in
```
BOOL GetSystemTimeAdjustment(
  PDWORD lpTimeAdjustment,
  PDWORD lpTimeIncrement,
  PBOOL  lpTimeAdjustmentDisabled
);
```
Users who try to call such a Win32 function (like the [above example](https://docs.microsoft.com/en-gb/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimeadjustment?redirectedfrom=MSDN)) with `ccall` would find the task of telling `ccall` the function's types significantly easier if Julia came with a module (say `Base.Win32.types`) that can be included such that these type names can be copied from Microsoft's documentation.

Would there be any interest to include such a Win32 type-alias module in Base and mention it in the manual section [Calling C and Fortran Code](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/), along with providing there an example of calling a Win32 function?

Something like:
```
const BYTE = Cuchar
const BOOL = Cint
const BOOLEAN = BYTE
const DOUBLE = Cdouble
const DWORD = Culong
```
etc.

Some of these may already be fund in Julia, e.g.
`stdlib/Mmap/src/Mmap.jl: const DWORD = Culong`

I'm less sure about adding the pointer aliases, such as
```
const PDWORD = Ptr{DWORD}
const LPDWORD = Ptr{DWORD}
```
because of the difference between `Ptr{}` and `Ref{}`.

**Comment by musm** [comment]
Have you seen my package https://github.com/musm/WinTypes.jl it basically does this

**Comment by stevengj** [comment]
The main reason to include things like `Clong` in Base is that they are potentially system-dependent — you need an alias that refers to that type *on your system*.

In contrast, `DWORD` etcetera are pretty much set in stone, no?

**Comment by JeffBezanson** [comment]
I think just having the WinTypes package is a good solution for this.

**Comment by Keno** [comment]
Yeah, `WinTypes` sounds like a good solution to me as well. If we ever need to make more extensive use of windows APIs in Base, we can always merge it in, but for now that seems like the right way to do it.

**Comment by musm** [comment]
Close this in favor of the package https://github.com/musm/WinTypes.jl ? If there is a real need in the future we can revisit.
