### ISSUE TITLE
Doc of @kwdef doesn't show up in Julia doc

### ISSUE THREAD

**Issue by dojt** [JuliaLang/julia#36889]
https://github.com/JuliaLang/julia/blob/91bb52449c98b3dd965e800ae876b9188376da1a/base/util.jl#L390

I'm probably not searching properly -- it seems to me that while `@kwdef` is mention once in the Julia documentation (in the release notes for v1.1), but the docstring from util.jl doesn't seem to show up anywhere: https://www.google.com/search?q=%22kwdef%22+site%3Adocs.julialang.org

Or maybe it's deprecated somehow?

**Comment by fredrikekre** [comment]
#32659, #33192
