### ISSUE TITLE
Julia v1.5.0 JULIA_HISTORY with line not starting with # or \t hangs at startup due to MethodError

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/julia#36895]
When upgrading the cluster from v1.3.1 to v1.5.0 at startup it will hang unresponsive after
```
MethodError: objects of type Bool are not callable
```
It seems to have also occurred to @ianshmean 

In my case, I thought it might have been related to Revise or having startup.jl but commenting those out didn't resolve the issue. I was able to get it working by deleting `~/.julia` and then Julia started up normally. From the Slack conversation, it seems the issue is with Julia trying to create some directory that fails when it already exists and then runs into a `MethodError`.

CC: @giordano

**Comment by JeffBezanson** [comment]
Is there any more output, e.g. stacktrace?

**Comment by Nosferican** [comment]
It just hangs unresponsive.

**Comment by giordano** [comment]
On Slack (https://julialang.slack.com/archives/C6A044SQH/p1596398523190000) @ianshmean pointed to `setup_interface` in `REPL/src/REPL.jl:869` with Julia v1.4.2

**Comment by ianshmean** [comment]
For me I had a rogue setting of env var `TEMP` to a nonexistant path, which threw a `mktempdir()` error on 1.4.2, but on 1.5 & master I got the same hanging with `MethodError: objects of type Bool are not callable`,  until I fixed that.

I can't promise that that's not a red-herring though.. I can't replicate this with `TMP=/nonexistant julia`

**Comment by KristofferC** [comment]
If this is a general issue, let's hope someone figures out a way to replicate it. Until then, I don't think there is much that can be done here though.  I also tried various combinations of deleting `.julia` and setting the environment variable but nothing replicated it.

**Comment by Nosferican** [comment]
I was able to get this stacktrace now when connecting to a computing node (login node works fine).
```
~MethodError: ERROR: objects of type MethodError: objects of type Bool are not callableBool
Stacktrace: are not callable

 [1] setup_interface(::REPL.LineEditREPL, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:964
 [2] setup_interface(::REPL.LineEditREPL; hascolor::Bool, extra_repl_keymap::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:872
 [3] setup_interface at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:872 [inlined]
 [4] hook_repl at /home/jbs3hp/.vscode-server/extensions/julialang.language-julia-1.0.2/scripts/packages/VSCodeServer/src/repl.jl:66 [inlined]
 [5] (::VSCodeServer.var"#2#4"{REPL.LineEditREPL})() at ./task.jl:356
```

**Comment by Nosferican** [comment]
I tracked down the issue. The culprit is related to `~/.julia/logs`.

**Comment by KristofferC** [comment]
It's a confusion between a local variable called `hascolor` (which is a Bool) and a function called `hascolor`.

**Comment by ianshmean** [comment]
> It's a confusion between a local variable called hascolor (which is a Bool) and a function called hascolor.

Is there a workaround for this in 1.5.0? I just hit it in a system that wasn't erroring with 1.5.0 previously

**Comment by ianshmean** [comment]
Deleting `.julia/logs/repl_history.jl` works as a workaround

**Comment by Nosferican** [comment]
Yes, but you have to do so every time the file gets corrupted which is a bit annoying. I tried putting a run command with sed which does execute before hitting the bug but it was a pain to get it escaped given all the special characters for deleting lines which don’t start with # or \s{4}

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by montyvesselinov** [comment]
The file `.julia/logs/repl_history.jl` get damages frequently; This is error is extremely annoying. The file is damaged frequently especially when the home dir is shared by multiple machines running julia. there is a need for a clear message which line in the file are bad. Even better will be to have a tool /mechanism to remove / ignore bad lines in .julia/logs/repl_history.jl.

**Comment by Nosferican** [comment]
Aye. This was especially bad in v1.3 on clusters. At least the method error that stops Julia from starting up has been patched.

**Comment by montyvesselinov** [comment]
here is is a simple script to fix it; i think this should be done automatically at julia start:

```
egrep  "^(#|\t)" ~/.julia/logs/repl_history.jl > ~/.julia/logs/repl_history_fix.jl
mv ~/.julia/logs/repl_history.jl ~/.julia/logs/repl_history_old.jl
mv ~/.julia/logs/repl_history_fix.jl ~/.julia/logs/repl_history.jl
```

**Comment by StefanKarpinski** [comment]
People should certainly feel free to put that in their `startup.jl` scripts (although is that run before or after loading history?), but we shouldn't just settle for letting the history file get corrupted and then doing something hacky to try to patch up the damage.
