### ISSUE TITLE
LLVM Error when attempting to use PyPlot

### ISSUE THREAD

**Issue by fundamental** [JuliaLang/julia#36901]
I just saw the new release notes mentioning the efforts put into the first plot problem and figured I'd try out a new build of julia  on my rebuilt dev system. Unfortunately, the 1.5.0 release as well as the git HEAD appear to error out when trying to show the first plot. Let me know what other information would be needed to identify the source of the issue.

Minimal test from new build: (the show() is not needed if run from the REPL)
```
using Pkg
Pkg.add("PyPlot")
using PyPlot
plot([1,0])
show()
```

Output: (at first glance the RDRND issue appears to be unrelated, though I should look into the microcode update needed to resolve that one)
```
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
julia exits with code '1'.

Version info
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-slackware-linux)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

**Comment by yuyichao** [comment]
The second error is usually caused by loading more than one llvm

**Comment by fundamental** [comment]
Looks like that was the case. I couldn't think of why pyplot would end up loading LLVM, but sure enough it was in strace.
matplotlib->the new qt backend->looking for GL->mesa->nouveau_dri.so->libLLVM*.so.10 . Odd that noveau_dri links to LLVM, but that's the case on my system. Anyhow, the USE_SYSTEM_LLVM setup is broken on my machine as base/Makefile:218..223 barfs, but after hacking the makefiles somewhat and having to restart make a few times to convince it to do the full build I do have a julia binary which runs through the test case just fine.

So I guess this one is resolved, though it would be nice if USE_SYSTEM_LLVM worked without the fuss. I'm guessing alternative resolutions would be to get matplotlib to disable the qt backend, or install the proprietary nvidia driver which would avoid (I think) noveau_dri.so and thus the LLVM link.

Thanks for the pointer.

**Comment by yuyichao** [comment]
> USE_SYSTEM_LLVM worked without the fuss

You need a patched LLVM to get it working, in additional to specifying the right make flags to get it compile.

**Comment by fundamental** [comment]
Mind elaborating? I've got LLVM 10.0.1 on my system and julia/deps/patches/llvm-10* seems to only have changes relevant to non-x86_64 architectures. To get julia to compile I just subbed out the broken libLLVM.so creation with a dummy file and then added llvm-config --libs onto LD_FLAGS in Make.inc

**Comment by yuyichao** [comment]
No there are many patches that applies to all architectures including x86
