### ISSUE TITLE
For loop uses 2-4x memory allocation

### ISSUE THREAD

**Issue by Cvikli** [JuliaLang/julia#36913]
Dear Julianers,

I am trieing to parse arbitrary dimensions of arrays but I see interesting memory allocation out of nowhere.
 
I don't understand how to make this code to avoid memory allocations:

```
# gen test data
arbitrary_1d_array_from_file(arr_size) = size(arr_size,1)>1 ? [arbitrary_1d_array_from_file(arr_size[2:end]) for _ in 1:arr_size[1]] : convert(Array{Any,1},[1:arr_size[1];])::Array{Any,1}

# test 
a,b,c,d,e=10,200,784,6,10
meret=[a,b,c,d]
data=arbitrary_1d_array_from_file(meret)

@time out = zeros(Float32, meret...)


# Flatten Assign #1 list comprehension
flattenND(y) = [y[ii][jj][kk][mm] for ii=1:a, jj=1:b, kk=1:c, mm=1:d] 
@time out .= flattenND(data)

# Flatten Assign #2 for loop
function for_loop(out,dd)
  for i=1:a::Int, j=1:b::Int, k=1:c::Int, m=1:d::Int
   out[i,j,k,m]=dd[i][j][k][m]
  end
end
@time for_loop(out,data)
```
The run results:
 ```
  0.011053 seconds (6 allocations: 35.889 MiB)   <--- the raw size of the dataset: 10x200x784x6 X4 ~ 37.632.000 byte
  0.612946 seconds (174.37 k allocations: 80.450 MiB)
  1.190116 seconds (9.43 M allocations: 144.866 MiB)
```
I tried: tuples, flattening, different indexing and broadcasting but I just can't get rid of this memory allocation that is 2X at "#1 list comprehension" and 4X bigger than the whole dataset in a "#2 for loop".  

Can someone help me?

**Comment by mbauman** [comment]
This is a question for the mailing list at discourse.julialang.org.  Please ask there.  (Quick answer is that this is a type instability as your innermost vector is a `Vector{Any}`).

**Comment by yuyichao** [comment]
Please ask for help on http://discourse.julialang.org/ .

Your allocation all comes from your `Any` array.
