### ISSUE TITLE
Uninstaller for previous version disappears after Julia upgrades on Windows

### ISSUE THREAD

**Issue by tomyun** [JuliaLang/julia#36933]
1. Install Julia 1.4.2 -- I have uninstaller named "Julia 1.4.2" in control panel.
2. Install Julia 1.5.0 -- Now I have uninstaller named "Julia 1.5.0", but "Julia 1.4.2" no longer exists.
3. Trying to remove old version..

At this point, I still have Julia 1.4.2 fully working and it's visible on Start Menu, but there's no way to call uninstaller since it's presumably overwritten/removed during installation of new version. Right-clicking "Uninstall" on Julia 1.4.2 start menu item brings up a list of installed programs which now only contains Julia 1.5. Running the installer, of course, uninstalls only 1.5.

I believe uninstaller for old versions should remain after upgrades. I tested it with official installers (64-bit) on Windows 10, version 1903.

**Comment by musm** [comment]
Yeah, the way it should work is for the installer to prompt uninstalling the old version then installing the new one.

**Comment by datalifenyc** [comment]
To clarify, does this mean I should uninstall the older version of Julia before installing the latest version?

**Comment by musm** [comment]
> To clarify, does this mean I should uninstall the older version of Julia before installing the latest version?

If you don't plan on using the older version of Julia, then yes. There's no issues in having multiple version installed alongside since they are treated as seperate programs.
