### ISSUE TITLE
Julia 1.5.0 fails to build against musl when USE_BINARYBUILDER=0

### ISSUE THREAD

**Issue by non-Jedi** [JuliaLang/julia#36943]
With no Make.user, invoking:

```sh
make -j3 prefix=/usr sysconfdir=/etc datarootdir=/usr/share \
 USE_LLVM_SHLIB=1 USE_BINARYBUILDER=0 \
 USE_SYSTEM_LIBUV=0 USE_SYSTEM_LIBUNWIND=0 USE_SYSTEM_PATCHELF=1 USE_SYSTEM_LIBM=0 \
 USE_SYSTEM_DSFMT=0 USE_SYSTEM_LLVM=0 USE_SYSTEM_PCRE=1 USE_SYSTEM_BLAS=0 \
 USE_SYSTEM_GMP=1 USE_SYSTEM_LIBGIT2=1 USE_SYSTEM_MBEDTLS=1 USE_SYSTEM_LIBSSH2=1 \
 USE_SYSTEM_CURL=1 USE_SYSTEM_MPFR=1 USE_SYSTEM_SUITESPARSE=0 USE_SYSTEM_UTF8PROC=0 \
 USE_SYSTEM_ZLIB=1 USE_SYSTEM_P7ZIP=1 USE_SYSTEM_LAPACK=0
```

results eventually in the error:

>     /usr/bin/ld: /builddir/julia-1.5.0/usr/lib/libunwind.a(Ltrace.o): relocation R_X86_64_TPOFF32 against `tls_cache_destroyed' can not be used when making a shared object; recompile with -fPIC`

I'm attempting to use [the fat 1.5.0 release tarball with dependency sources bundled](https://github.com/JuliaLang/julia/releases/download/v1.5.0/julia-1.5.0-full.tar.gz).

I don't know much about linking, but I don't think my `make` invocation is doing anything that should cause this error. Is BINARYBUILDER the only way to get musl-based julia to build?

Build log: https://gist.github.com/non-Jedi/ba54f6e8f4756da2e9f80e8ccd90b70b

**Comment by vtjnash** [comment]
That seems like libunwind is not getting built correctly. I think this may be fixed as of https://github.com/JuliaLang/julia/pull/36697, but I'm not sure why the same error wouldn't have already shown up while trying to build that library.

**Comment by non-Jedi** [comment]
Can confirm that applying #36697 (minus the portions updating libosxunwind) fixes this. Should that PR be backported?

**Comment by fingolfin** [comment]
Is this still an issue in 1.5.2?

**Comment by non-Jedi** [comment]
Nope!
