### ISSUE TITLE
Need an adjoint for constructor Pair

### ISSUE THREAD

**Issue by Yansf677** [JuliaLang/julia#36987]
I use diagm in my function, the following error will raise when I try to calculate the gradient of the function. How can I add the adjoint method for the constructor Pair? Many thanks!
`ERROR: Need an adjoint for constructor Pair{Int64,Array{Float64,1}}`

**Comment by KristofferC** [comment]
This seems to be an issue with a package (maybe Zygote?) and not a Julia issue.
