### ISSUE TITLE
julialang2 bucket permission denied when syncing from downstream mirror sites

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/julia#36985]
[The BFSU mirror](https://mirrors.bfsu.edu.cn/julia-releases/) has mirrored `s3://julialang2` for Chinese users, and it recently has failed to sync the data due to permission error

```
download failed: s3://julialang2/bin/mac/x64/1.5/julia-1.5.0-mac64.tar.gz to julia-releases/bin/mac/x64/1.5/julia-1.5.0-mac64.tar.gz An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

`s3://julialang2/bin/mac/x64/1.5/julia-1.5.0-mac64.tar.gz` seems the only file that has problems.

cc: @staticfloat @ararslan @z4yx

**Comment by staticfloat** [comment]
Please try again now!

**Comment by johnnychen94** [comment]
It now succeeds.
