### ISSUE TITLE
Macro `__source__` information lost in Cmd interpolation

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#37005]
The `__source__` macro meta-argument seems to lose its bearing when used inside of `Cmd` interpolation.  Example:

```
$ cat test.jl
z = `$(@__FILE__)`
@show z
$ julia test.jl
z = `none`
```

This is particularly an issue for macros like `Pkg.Artifacts.@artifact_str` which use the `__source__.file` attribute to look up the location of the appropriate `Artifacts.toml` file.

**Comment by fredrikekre** [comment]
Duplicate of #28188
