### ISSUE TITLE
=== is incorrect for strings

### ISSUE THREAD

**Issue by cjdoris** [JuliaLang/julia#37001]
The documentation says that `x === y` determines "whether x and y are identical, in the sense that no program could distinguish them", but here is a program that distinguishes two "identical" strings:
```
julia> x = "hello"
"hello"

julia> y = "hello"
"hello"

julia> x === y
true

julia> pointer(x) === pointer(y)
false
```

This occurs at least for v1.1.1 to v1.5.0.

**Comment by yuyichao** [comment]
They are indistinguishable since the pointer values are not guaranteed to be stable and the pointer cannot be used for mutations. This is the same for all immutables, where the address is not a property of the object.
