### ISSUE TITLE
FFTW planned 2D real ldiv! unexpectedly overwrites input

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#37000]
All versions of Julia back to at least 1.0 have the following unexpected behavior:

```julia
using FFTW, LinearAlgebra
y = rand(4,4)
p = plan_rfft(y)
x = p * y
x_orig = copy(x)
ldiv!(y,p,x)
x == x_orig # unexpectedly returns false
```

This only happens with FFTW and not MKL, only with 2D and real FFTs, and only with `ldiv!` not `mul!`.

**Comment by KristofferC** [comment]
Isn't this an FFTW issue?

**Comment by marius311** [comment]
Oops I think I somehow forgot that's not in Base... as of several years. Will open there!
