### ISSUE TITLE
`--` is removed from ARGS

### ISSUE THREAD

**Issue by xitology** [JuliaLang/julia#37009]
Create an executable Julia script that shows its arguments:
```console
$ cat >showargs.jl <<EOF
#!/usr/bin/env julia
@show ARGS
EOF
$ chmod a+x showargs.jl
```
Now try to pass `--` as a command-line argument:
```console
$ ./showargs.jl --foo --bar
ARGS = ["--foo", "--bar"]
$ ./showargs.jl -- --foo --bar
ARGS = ["--foo", "--bar"]
$ ./showargs.jl --foo -- --bar
ARGS = ["--foo", "--bar"]
$ ./showargs.jl -- --foo -- --bar
ARGS = ["--foo", "--", "--bar"]
```
See how the first `--` does not appear in the list.

Note that all `--` are preserved if the script is invoked with `julia -- showargs.jl`:
```console
$ julia -- showargs.jl -- --foo -- --bar
ARGS = ["--", "--foo", "--", "--bar"]
```

The expected behaviour for `showargs.jl` is to display its arguments as is:
```console
$ ./showargs.jl --foo --bar
ARGS = ["--foo", "--bar"]
$ ./showargs.jl -- --foo --bar
ARGS = ["--", "--foo", "--bar"]
$ ./showargs.jl --foo -- --bar
ARGS = ["--foo", "--", "--bar"]
$ ./showargs.jl -- --foo -- --bar
ARGS = ["--", "--foo", "--", "--bar"]
$ julia -- showargs.jl -- --foo -- --bar
ARGS = ["--", "--foo", "--", "--bar"]
```
Indeed, a Julia script may need to implement its own command-line processing and use `--` as a customary separator between options and regular arguments, which is impossible if `--` is removed from `ARGS`.

It also doesn't match how other interpreters handle `--`. For instance, Python:
```console
$ cat >showargs.py <<EOF
#!/usr/bin/env python3
import sys
print(sys.argv[1:])
EOF
$ chmod a+x showargs.py
$ ./showargs.py -- --foo -- --bar
['--', '--foo', '--', '--bar']
$ python -- showargs.py -- --foo -- --bar
['--', '--foo', '--', '--bar']
```
I also checked Bash, Perl, and Ruby, and they all preserve `--`.

It appears that Julia tries to bypass `getopt()` and handle `--` manually since #10226. But this is unnecessary because `getopt()` with `+` in optstring does the right thing.

**Comment by brenhinkeller** [comment]
Looks like the linked pull requiest has been successfully merged (just didn't auto-close the issue because of the way it was linked), so I think we can close this!
