### ISSUE TITLE
`show` crashes when using type aliases (on master)

### ISSUE THREAD

**Issue by mhauru** [JuliaLang/julia#37012]
As discussed at https://github.com/JuliaLang/julia/pull/36107, the new feature of displaying type aliases causes this:
```
struct ZNIrrep{N} end
abstract type VectorSpace end
struct ProductSpace{S<:VectorSpace} end
const TensorSpace{S} = Union{S, ProductSpace{S}}
show(ZNIrrep{2})
```
to produce
```
ERROR: TypeError: in ProductSpace, in S, expected S<:VectorSpace, got Type{
Stacktrace:
 [1] make_typealias(x::Type)
   @ Base ./show.jl:563
...
```
(@Jutho, since this originally came up in his TensorKit package.)

**Comment by Jutho** [comment]
Copied here from #36107 : 

> I think I traced it down to this definition:
> ```julia
> const TensorSpace{S} = Union{S, ProductSpace{S}}
> ```
> where `S` is unconstrained in the first part of the union, and thus matches basically any type, but then it is constrained as a type parameter in `ProductSpace`. In `make_alias`, type intersection of `TensorSpace` basically matches with any type `S`, but make_alias then tries to construct `ProductSpace{S}` with a type `S` not matching the constraint, the error occurs.

**Comment by mhauru** [comment]
So the issue here really is that the bug that is in the definition of `TensorSpace` shows up when calling `show` on an entirely unrelated type in the same module, along with a very confusing and misleading stacktrace.

**Comment by vtjnash** [comment]
Yeah, I wasn't expecting that type-intersection (and subtyping) would be permitted to ignore this constraint while apply_type is not:
```
julia> (ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), Int, TensorSpace)
svec(Int64, svec(Int64))

julia> TensorSpace{Int}
ERROR: TypeError: in ProductSpace, in S, expected S<:VectorSpace, got Type{Int64}
```

**Comment by Jutho** [comment]
Well, I am not sure type intersection ignores this constraint; the first element in the `Union` has no constraint on `S`, and so the type intersection is correct. Is the behavior of shared type parameters in `Union`s fully specified and/or documented? In a union where the arguments share a type parameter, i.e. `Union{A{T}, B{T}} where {T}`, should `T` be allowed to take any value allowed by the specific type `A` or `B` that matches something, or should it be constrained by the intersection of the constraints imposed on it by `A`, `B`, ...  ?

At first sight, the logical choice of a union is the first choice, `Union{A{T}, B{T}} ` should be the union of all possible `A`, and all possible `B`. However, it then becomes hard to instantiate `T` while keeping the union, if its value is only incompatible with some of the arguments. Furthermore, this can lead to ambiguities. 

Using only Base types, consider `Union{T, Complex{T}}`, where `T` is free, but of course, in `Complex` there is the constraint `T<:Real`.
```
julia> ccall(:jl_type_intersection_with_env, Any, (Any, Any), Float64, Union{T,Complex{T}} where T)
svec(Float64, svec(Float64)) # no problem here

julia> ccall(:jl_type_intersection_with_env, Any, (Any, Any), Char, Union{T,Complex{T}} where T)
svec(Char, svec(Char)) # T = Char is compatible with the first argument of the `Union`, even though `Complex{Char}` does not exist

julia> ccall(:jl_type_intersection_with_env, Any, (Any, Any), ComplexF64, Union{T,Complex{T}} where T)
svec(ComplexF64, svec(Float64)) # seems fine, however, one could also say that another solution is to just choose T = ComplexF64
```

I know there are many related open and closed issues about type `Union`s, so I have to admit not spending any effort trying to find if this came up before.
