### ISSUE TITLE
Missing function: MethodError: no method matching days(::Nanosecond)

### ISSUE THREAD

**Issue by cfitz25** [JuliaLang/julia#37023]
Hello, recently i was doing some stuff with dates and i ran into the issue that the days value function has nothing for nanoseconds. I had to find a way around that which seemed sort of unnecessary as i feel it should have that implemented. Is there a reason it is not?
Its in Periods.jl of the Dates library

**Comment by ViralBShah** [comment]
Please reopen with more information and a code snippet, or discuss on discourse.
