### ISSUE TITLE
Wrong printing of method leads to misleading MethodError

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#37037]
```julia
julia> Union{UInt8, Int8}[1]
ERROR: MethodError: no method matching Union{Int8, UInt8}(::Int64)
Closest candidates are:
  Union{Int8, UInt8}(::T) where T<:Number at boot.jl:715
```
What happens here? The listed "closest candidate" clearly matches the attempted call, so why did it raise a MethodError?
The real definition of the closest candidate is `(::Type{T})(x::T) where {T <: Number} = x`. Notably, that method requires `x` to be of type `T`. But that is not clear in the stack trace!

So the method should really be printed `T(::T) where T<:Number`, or else `Union{Int8, UInt8}(::Union{Int8, UInt8})`

**Comment by yuyichao** [comment]
On 1 day old master master,

```
julia> Union{Int8,UInt8}(1)
ERROR: MethodError: no method matching Union{Int8, UInt8}(::Int64)
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:745
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number, ComplexF16, ComplexF32, Comp
  (::Type{T})(::Complex) where T<:Real at complex.jl:37
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

**Comment by jakobnissen** [comment]
You are right, it appears it has already been fixed. I also see the right behaviour on master. Closing the issue.

**Comment by StefanKarpinski** [comment]
Is there something that needs to be backported to the 1.5 release branch?

**Comment by jakobnissen** [comment]
@StefanKarpinski It depends how much this behaviour is considered buggy. The fix was https://github.com/JuliaLang/julia/pull/35862
