### ISSUE TITLE
Can we provide something like statfs()? Get free disk space / disk utilization?

### ISSUE THREAD

**Issue by rai-nhdaly** [JuliaLang/julia#37038]
According to this Discourse thread (https://discourse.julialang.org/t/is-there-a-way-to-find-out-free-disk-space-equivalent-to-psutil-disk-usage-in-python/16918), apparently libuv 1.31 added [`uv_fs_statfs()`](http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_statfs), but we're still on libuv 1.29.

Do we have plans to upgrade?

If not, can we add support for a cross-platform way to access current disk usage, how much free space is available, etc?

From this thread, it sounds like there aren't any available julia packages that provide this yet. Python seems to provide something like this: https://stackoverflow.com/a/2372171/751061.

**Comment by vtjnash** [comment]
We plan to upgrade for v1.6.x (LTS), at which point we will be able to take PRs to add it.

**Comment by rai-nhdaly** [comment]
Thanks Jameson! :)
