### ISSUE TITLE
Ability to record llvm optimization timings per method instance / specailization

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#37039]
https://github.com/timholy/SnoopCompile.jl currently provides tools to see how much time julia spends in Inference, and how much time it spends compiling a method specialization overall. It would be really nice to get per-method-specialization how much time was spent during LLVM optimization.

(I'm now realizing that maybe we can just subtract the inference time from the total time? Would the remainder be the LLVM time?)

I'm opening this issue to track this ability, since the PR we started for this last year (https://github.com/JuliaLang/julia/pull/31616) has stalled.

**Comment by NHDaly** [comment]
Although, hmm, somehow the timings from `@snoopc` on SnoopCompile.jl are smaller than the timings from `@snoopi`, so maybe i'm misunderstanding those? Is `@snoopc` already _excluding_ inference?

**Comment by NHDaly** [comment]
CC: @timholy  :) Thanks in advance for any help here!

**Comment by NHDaly** [comment]
@vtjnash you mentioned yesterday that this is probably pretty straightforward to add now. How should we go about it? Does it make the most sense to

**Comment by NHDaly** [comment]
Oops, accidentally closed from my phone >.<

**Comment by NHDaly** [comment]
Also it'd maybe be useful to collect other metrics, like the size of the code object being passed to LLVM? Boy, i really wish https://github.com/JuliaLang/julia/pull/31616 had worked out, because then one would be able to implement their own abitrary data collections. :(

**Comment by NHDaly** [comment]
This was fixed in #37136! :)

**Comment by oscardssmith** [comment]
Is it possible to add tests for this?

**Comment by NHDaly** [comment]
Thanks Oscar; good call. Finally added tests in #43634.
