### ISSUE TITLE
Bug in Julia LinearAlgebra.LAPACK.geev! function

### ISSUE THREAD

**Issue by JuanVargas** [JuliaLang/julia#37056]
Julia's LinearAlgebra.LAPACK.geev! function, which is supposed to return the eigenvalues and the (left and right) eigenvectors of a square matrix.

Since GoLang and Python also use LAPACK to obtain the eigenvalues and the eigenvectors, I compared the results in Julia versus Python and GoLang.  In Golang and Python the results are correct and are compatible with results you find in books and using "R".

In Julia the call is supposed to be like:

w, l, r = LinearAlgebra.LAPACK.geev!('V','V', tMatrix)

where w is the matrix with the eigenvalues, l is the left vector and r is the right vector.

The issue is that Julia returns in the right vector the values that should be in the left vector. Julia returns the left vector empty, which should not be empty.

**Comment by stevengj** [comment]
No, for [real matrices the call is](https://github.com/JuliaLang/julia/blob/58febaaf2fe38d90d41c170bc2f416a76eac46f5/stdlib/LinearAlgebra/src/lapack.jl#L1592) `WR, WI, VL, VR = geev!(...)`, where the eigenvalues are then `Complex.(WR, WI)`.

(Some post-processing is then required to get the eigenvectors corresponding to complex eigenvalues, as explained in the [LAPACK `dgeev` docs](http://www.netlib.org/lapack/explore-html/d9/d8e/group__double_g_eeigen_ga66e19253344358f5dee1e60502b9e96f.html).)
