### ISSUE TITLE
[Feature Request] Set the default values for `code_native` etc. to the previous values

### ISSUE THREAD

**Issue by kimikage** [JuliaLang/julia#37068]
For example, the default value of `syntax` kwarg of `code_native` is `:att`. This is annoying for developers who always prefer `:intel`. On the other hand, you may want to toggle `debuginfo` kwarg, for example, at times. I sometimes see people griping about these default values.

A direct solution to this issue is to define a new API to set the default values. However, I don't think calling such an API is much better than setting the kwargs manually.

By changing the default values to the value used in the last function (or macro) call, you can achieve almost the same functionality without adding a new API.

**Comment by yuyichao** [comment]
A implicit state like that is really bad. An API to change the default is much better.

**Comment by kimikage** [comment]
That was a concern of mine as well. I didn't think it was critical in the `code_*` family. However, I'm not going to force this request over the objection.
