### ISSUE TITLE
Feature Request: Type assertion in struct parameters

### ISSUE THREAD

**Issue by jpthalman** [JuliaLang/julia#37066]
I would like the ability to assert on the type of a struct parameter before the creation of the type:

```julia
struct Array{Size::Int32} ... end
struct LBounded{T<:Real, Min::T} ... end
```

This is currently possible at construction time via type assertions for the parameters to `new`, but I think that written code would be more expressive if non-type parameters (constexpr instances) could be explicitly defined. Below are examples of the best way to implement this I've found so far:

```julia
struct Array{Size}
    Array{Size}() = new{Size::Int32}()
end

struct LBounded{T<:Real, Min}
    LBounded{T, Min}() = new{T, Min::T}()
end
```

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/9580
