### ISSUE TITLE
Segfault with `unsafe_pointer_to_objref`

### ISSUE THREAD

**Issue by pazner** [JuliaLang/julia#37083]
The following code results in a segfault:
```julia
mutable struct A a::Int end
function f()
    x = Ref{A}(A(42))
    p = Base.unsafe_convert(Ptr{A}, x)
    @GC.preserve x println(unsafe_pointer_to_objref(p))
end
f()
```
I would expect this to work since the mutable object should have a stable memory address. The segfault still occurs with the garbage collector disabled. If `unsafe_load` instead of `unsafe_pointer_to_objref` is used, then the code works.

Version info:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

**Comment by yuyichao** [comment]
> I would expect this to work since the mutable object should have a stable memory address.

No that is not the case. Nothing is guaranteeing you that x is heap allocated here. You are only guaranteed that the content of `x` is valid.

**Comment by pazner** [comment]
Thanks for the explanation.

> (and if you've requested a pointer to it, the pointer will be valid as well, but only the content of the pointer, not metadata that comes with the object)

I think this is what I was missing. So is it safe to use `unsafe_load` on a pointer to a Julia object as long as I can guarantee that it hasn't been GC'd (even if it isn't heap allocated/has a stable memory address)?

And it sounds like it is not safe to use `unsafe_pointer_to_objref` unless I can guarantee that it has been heap allocated? Can I reliably make such a guarantee? Does the same hold for `pointer_from_objref`?

**Comment by yuyichao** [comment]
> So is it safe to use unsafe_load on a pointer to a Julia object as long as I can guarantee that it hasn't been GC'd

Yes, you are guaranteed that the pointer is pointing to something valid as long as it's used within a `GC.@preserve` block with the correct arguments. "hasn't been GC'd" isn't the condition though and it may not make sense. The object may not be allocated in a way that the GC is aware of and will therefore never be GC'd.

> And it sounds like it is not safe to use unsafe_pointer_to_objref unless I can guarantee that it has been heap allocated?

Yes. See [the document](https://docs.julialang.org/en/v1/base/c/#Base.unsafe_pointer_to_objref)

> Assumes the pointer refers to a valid heap-allocated Julia object.

> Can I reliably make such a guarantee?

There are some ways but it should not be needed for almost all the cases.

> Does the same hold for pointer_from_objref?

What do you mean "the same". (btw, you are already using `pointer_from_objref`).
`pointer_from_objref` does not take a pointer as input so it doesn't care anything about the validity of the pointer. As a related property, it does not guarantee the argument to be heap allocated.

**Comment by pazner** [comment]
> What do you mean "the same". (btw, you are already using `pointer_from_objref`).
> `pointer_from_objref` does not take a pointer as input so it doesn't care anything about the validity of the pointer. As a related property, it does not guarantee the argument to be heap allocated.

My understanding now from the documentation and your replies is that `pointer_from_objref` will work for any immutable object, and I can safely use `unsafe_load` on the resulting pointer (within a `GC.@preserve` block). Whether the object is heap allocated or not should not matter in this case.

I wanted to confirm that `pointer_from_objref` does not require the object to be heap allocated (the docs mention "stable memory address", which I had conflated with "heap allocated", but I suppose that is not true). Part of my confusion is because of the perceived symmetry (because of their names) between `pointer_from_objref` and `unsafe_pointer_to_objref`.

**Comment by yuyichao** [comment]
> `pointer_from_objref` will work for any immutable object

No. You can not get a pointer from an immutable object. I did not mention this above since it is something you were aware of and is unrelated to the reason your code didn't work.

> I wanted to confirm that pointer_from_objref does not require the object to be heap allocated

Allocation is not a property of the object. `pointer_from_objref` takes a mutable object as input and that's the only requirement. Use of the resulting pointer will have additional requirement depending on how it is used.

**Comment by yuyichao** [comment]
And stable address just mean that the address you get from the object is going to be the same one within the lifetime of the object. It doesn't mean the address is anything usable if you look at it anywhere out of the lifetime of the object and it doesn't mean where the address is. In fact, it doesn't even mean the address has to exist but just that your code using the address within the lifetime of the mutable object will work.

**Comment by pazner** [comment]
> > `pointer_from_objref` will work for any immutable object
> 
> No. You can not get a pointer from an immutable object. I did not mention this above since it is something you were aware of and is unrelated to the reason your code didn't work.

Yeah, sorry that was a bad typo. I meant **mutable** object.

I think it's clear now. Seems better to just avoid `unsafe_pointer_to_objref` if possible. Thanks for the clarifications.
