### ISSUE TITLE
global cache

### ISSUE THREAD

**Issue by apparluk** [JuliaLang/julia#37097]
Slackware Linux (version 14.2)
Julia (version 1.5.0)

I presume this is currently not implemented so it can be labeled a proposal.

<hr>

Can one implement something like this in Julia?

[CPAN](https://github.com/nurmi-labs/blogger/wiki/CPAN) (search for 'wheel' on the Wiki page)
```
bash-4.3$ tree -L 2 /var/cache/cpan/sources
/var/cache/cpan/sources
|-- authors
|   |-- 01mailrc.txt.gz
|   `-- id
`-- modules
    |-- 02packages.details.txt.gz
    `-- 03modlist.data.gz

3 directories, 3 files
bash-4.3$ 
```
[CRAN](https://github.com/nurmi-labs/blogger/wiki/CRAN)
[Hackage](https://github.com/nurmi-labs/blogger/wiki/Hackage)

```
bash-4.3$ ls /var/cache/cabal/hackage.haskell.org | grep index
01-index.cache
01-index.tar
01-index.tar.gz
01-index.tar.idx
01-index.timestamp
bash-4.3$ ls /var/cache/cabal/hackage.haskell.org | grep lock
hackage-security-lock
bash-4.3$ ls /var/cache/cabal/hackage.haskell.org | grep json
mirrors.json
root.json
snapshot.json
timestamp.json
bash-4.3$ 
```
<hr>

The Hackage page is reproduced below.

If you want a global directory for downloaded packages.

```
bash-4.3# usermod -a -G wheel eric
bash-4.3# mkdir -p /var/cache/cabal
bash-4.3# chown -R root:wheel /var/cache/cabal
bash-4.3# chmod -R 770 /var/cache/cabalbash-4.3# usermod -a -G wheel eric
bash-4.3# mkdir -p /var/cache/cabal
bash-4.3# chown -R root:wheel /var/cache/cabal
bash-4.3# chmod -R 770 /var/cache/cabal
bash-4.3#
bash-4.3# 
```

And modify your `~/.cabal/config` file.

```
bash-4.3$ grep cache ~/.cabal/config
remote-repo-cache: /home/eric/.cabal/packages
bash-4.3$ sed -i 's#cache: .*#cache: /var/cache/cabal#' ~/.cabal/config
bash-4.3$ 
```

**Comment by StefanKarpinski** [comment]
It's unclear to me what you're asking for. What do you mean by "gobal cache"? Linking to examples in other systems isn't that helpful since I don't know what the examples are supposed to do or convey.

**Comment by apparluk** [comment]
Can users on the same machine who are members of the group 'wheel' share the registries?

Cpan and Hackage co-locate in the same directory tree registries and source files (downloaded as .tar.gz).

```
bash-4.3$ grep var ~/.cabal/config
remote-repo-cache: /var/cache/cabal
bash-4.3$ grep var ~/.cpan/CPAN/MyConfig.pm
  'cpan_home' => q[/var/lib/cpan],
  'keep_source_where' => q[/var/cache/cpan/sources],
  'prefs_dir' => q[/var/lib/cpan/prefs],
bash-4.3$ 
```

Equivalent user customisations would go in `~/.julia/config/startup.jl`.

With `cpan` you can directly specify for installation a .tar.gz file.

Haskell's `cabal` with the arguments  `install`, `fetch`, and `get`, locate .tar.gz files in `remote-repo-cache`.

My `sed` command replaced `/home/eric/.cabal/packages` with `/var/cache/cabal`.

The `~/.julia/packages` subdirectories of course are neither used for registries nor .tar.gz files.

**Comment by StefanKarpinski** [comment]
Yes, the default `DEPOT_PATH` includes one personal directory and two shared directories, one architecture-specific and one architecture independent. It should look something like this on a system-installed Julia:
```
~/.julia
/usr/local/share/julia
/usr/share/julia"
```
Any packages, artifacts, registries, preferences, etc. that are installed here are visible to any users with those shared directories in their depot path. To install things there, you can run as root and pop root's home directory off the `DEPOT_PATH` and then install whatever packages you want in these shared depots. They will then be available to all users on the system (read-only). This process should probably be documented better, ideally by someone who actually does it on a shared machine (I do not).

**Comment by fredrikekre** [comment]
There are a number of topics on https://discourse.julialang.org about this, e.g. https://discourse.julialang.org/t/how-does-one-set-up-a-centralized-julia-installation/13922

**Comment by apparluk** [comment]
I was familiar with `DEPOT_PATH` prior to opening this issue.

FWIW, members of the group 'wheel' could share registries via a symbolic link.

```
bash-4.3# mkdir -p /var/cache/julia/registries
bash-4.3# chown -R root:wheel /var/cache/julia
bash-4.3# chmod -R 770 /var/cache/julia
bash-4.3# 
```

```
bash-4.3$ ln -sf /var/cache/julia/registries ~/.julia/registries
bash-4.3$ 
```

If the documentation doesn't cover that `~/.julia/environments/v1.5/` files need to be present for example to `Pkg.add("CSV")` in `~/.julia`, where DataFrames (a CSV dependency) is already present in `/usr/local/share/julia`, perhaps that might expanded upon.

The links weren't all that interesting.

I suppose the use of source files (transmitted and/or stored as .tar.gz) for the installation of  Julia packages has not been among Julia users' prior feature requests, so I'll consider the proposal rejected by the developers.

By the way tar.lz has better compression than tar.gz.

**Comment by fredrikekre** [comment]
I mean, it is still pretty unclear to me what your proposal is? Do you want a local cache of the tarballs?

**Comment by apparluk** [comment]
This month I installed Perl Data Language ([PDL](https://nurmi-labs.blogspot.com/2020/08/pdl.html)) using local::lib (installs into `~/perl5`) and I omitted the optional Devel::REPL owing to the number of dependencies. However, another user (member of the group 'wheel') on the same machine, the fact that the Perl .tar.gz modules are cached, factually under `/var/cache/cpan`, the `/tmp/cpan/build` directory could be cleaned out, could offline install PDL using local::lib, with their preferred customisations/modifications.

That being said Julialang caching of tarballs and moreover installation via tarballs as an option would be welcomed.

**Comment by StefanKarpinski** [comment]
What is the problem that you're trying to address?

**Comment by apparluk** [comment]
@StefanKarpinski

The proposal was to ease the tasks of the software maintainer.

If implemented it might not necessarily need to be written in Julia.

Command-line and dialog-based tools [slackpkg](https://docs.slackware.com/slackware:slackpkg) and [sbopkg](https://docs.slackware.com/howtos:slackware_admin:building_packages_with_sbopkg) have been authored.

Those tools use the /var subdirectories cache, log, and lib.

The sbopkg tool can use queue files regarding package prerequisites.

[slackpkg](https://slackpkg.org/), [sbopkg](https://sbopkg.org/)

This issue pertains to user fetched/installed Julia packages, not system installed packages. 

<hr>

By the way Haskell's `cabal get` does a dependency resolution check.
