### ISSUE TITLE
calculating Factorial leeds to weird convert nothing to BigInt Error

### ISSUE THREAD

**Issue by boris-mb** [JuliaLang/julia#37090]
Im running the following Code: 

function fact(  n::Integer)::Integer
	if n < 0 print( "error:n must be positive! "); return -1 end
	erg = one(n)
	for i in 2:n
		erg *= i
	end
	return erg
end
fact( big(10))

Expected: 3628800
getting the following Error: 
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type BigInt
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23

**Comment by KristofferC** [comment]
Does this still happen if you restart Julia?

**Comment by JeffBezanson** [comment]
I can't reproduce this.

**Comment by boris-mb** [comment]
Startet Julia today and problem didn’t happen again. 

Sorry for the false alert! – Something must have messed up my Julia-Repl,

Thanks,

Boris

 

Von: Kristoffer Carlsson <notifications@github.com> 
Gesendet: Montag, 17. August 2020 22:16
An: JuliaLang/julia <julia@noreply.github.com>
Cc: boris-mb <boris.moebus@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [JuliaLang/julia] calculating Factorial leeds to weird convert nothing to BigInt Error (#37090)

 

Does this still happen if you restart Julia?
