### ISSUE TITLE
Julia launcher for managing multiple versions

### ISSUE THREAD

**Issue by blacklightpy** [JuliaLang/julia#37099]
Python has a launcher that can run the required version by typing py -2, py -2.7, py -3 etc.
I'm suggesting a similar implementation for Julia like ju -1.4, ju -1.5.0, ju -1.6.0
Thoughts?

**Comment by PallHaraldsson** [comment]
Juliaup is an installer, but may also have what you need and is now in version 1.2.0:

https://discourse.julialang.org/t/ann-juliaup-preview-julia-version-manager-and-windows-store-installer/61920

**Comment by ViralBShah** [comment]
`juliaup` pretty much solves this. Closing in favour of #36672.
