### ISSUE TITLE
Missed optimization: constant array selector

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#37112]
In Julia 1.5.0, I was working with a pure Julia implementation of Scrypt (Scrypt.jl: https://github.com/BioTurboNick/Scrypt.jl), to get performance down to C++ levels.

In the inner loop, there is a shuffle operation on a 4x4 UInt32 matrix (MMatrix from StaticArrays.jl, but I saw the same effect before moving to StaticArrays.jl), as such:

```
function salsatranspose!(block)
    toline3 = block[[2, 3, 4, 1], 1]
    block[:, 1] = block[[4, 1, 2, 3], 3]
    block[:, 3] = toline3
    block[:, 4] = block[[3, 4, 1, 2], 4]
    ()
end
```

(aside: the block has been arranged so that diagonals are along columns, so this is equivalent to a transpose of the original configuration)

```
@btime scrypt(ScryptParameters(8, 1024*16, 1), Vector{UInt8}(b"password"), Vector{UInt8}(b"NaCl"), 64)
# 1.613 s (29292970 allocations: 2.76 GiB)
```

If I move the array indexes to a constant global, I find that it is ~30% faster, 40% fewer allocations, and ~50% less allocated memory.

```
const line3selector = [2, 3, 4, 1]
const line1selector = [4, 1, 2, 3]
const line4selector = [3, 4, 1, 2]

function salsatranspose!(block)
    toline3 = block[line3selector, 1]
    block[:, 1] = block[line1selector, 3]
    block[:, 3] = toline3
    block[:, 4] = block[line4selector, 4]
    ()
end

@btime scrypt(ScryptParameters(8, 1024*16, 1), Vector{UInt8}(b"password"), Vector{UInt8}(b"NaCl"), 64)
# 1.130 s (17234346 allocations: 1.48 GiB)
```

Sukera on Discourse (https://discourse.julialang.org/t/scrypt-jl-key-derivation-algorithm-unregistered/45067/7) suggested that I open an issue, in case it is something that Julia can easily optimize.

**Comment by Keno** [comment]
We don't currently track values of mutable types (like Arrays) in the compiler at all, because that would require a legality analysis to make sure that the value isn't mutated before it's used. Since the index is constant, why not use an SVector or a tuple?

**Comment by BioTurboNick** [comment]
I could, just wasn't aware of that distinction, thanks!

I was thinking it wouldn't be hard to tell that the code was acting like a constant and, not being assigned to a variable, wouldn't be mutated. But I suppose that couldn't be guaranteed given that slicing is just another method that could itself mutate an array used as indexes?

I'll close this then.
