### ISSUE TITLE
Type declaration on anonymous function arguments in macro not working on 1.5

### ISSUE THREAD

**Issue by raminammour** [JuliaLang/julia#37134]
Hello, 

Originally broke `DistributedArrays`, filed [here](https://github.com/JuliaParallel/DistributedArrays.jl/issues/223). It turns out it is about type declaration of an anonymous function argument inside a macro (that was a mouthful :P).

```
julia> macro bla()
       :(x :: Int -> 62)
       end
@bla (macro with 1 method)

julia> @bla
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at REPL[2]:1
```

This stopped working on version 1.5, was working as of 1.4 (works without the type declaration `::Int`). Curiously, `eval(:(x::Int -> 62))` works too.

Cheers!

**Comment by martinholters** [comment]
Likely hygiene-related, as this works:
```julia
macro bla()
    :($(esc(:x))::Int -> 62)
end
```
