### ISSUE TITLE
collect on a Adjoint{T,Array{T,1}} should return a Adjoint{T,Array{T,1}}

### ISSUE THREAD

**Issue by roelstappers** [JuliaLang/julia#37189]
The documentation of `collect` states that it will return an object with the same shape and number of dimensions. However currently calling collect on objects of type `Adjoint{T,Array{T,1}}` returns a `1xn` matrix and these have different behaviour. An `Adjoint` of a vector in julia is a linear operator that maps vectors to scalars (as it should be) but this is not equivalent to a `1xn` matrix which maps vectors to 1-element vectors. e.g.
```
julia> a = [1,2,3]; b = [1,2,3];

julia> a'*b
14

julia> collect(a')*b
1-element Array{Int64,1}:
 14
```

One solution would be to let `collect` on a  `Adjoint{T,Array{T,1}}` return a `Adjoint{T,Array{T,1}}`.

~~Also calling `size` on objects of type `Adjoint{T,Array{T,1}}` returns `(1,n)` indicating that it is an `1xn` matrix instead this should return e.g. `(0,n)` or `(nothing,n)`~~

**Comment by yuyichao** [comment]
The size return value is correct. A zero or nothing as the first dimension does not make any sense.

And for exactly this reason, the returned type from collect is also correct. There’s no guarantee that operates on the returned value is exactly he same as the input, that is simply impossible.

**Comment by roelstappers** [comment]
Can you elaborate a bit more? How can the return value of size be correct when the adjoint of a vector is not a map from vectors to vectors but from vectors to scalars. Having size return `(1,n)` would mean that it is a linear map from vectors with n-elements to vectors with 1-element. Am I missing something?

For your second point. The proposal would exactly provide that guarantee as the return value of collect would be identical to it's input value.

**Comment by mbauman** [comment]
This was the compromise that was achieved through #4774: adjoint vectors participate in the linear algebra of matrices largely behaving _as though_ they were `1×N` matrices, but with special behaviors upon multiplication and such.

`collect` is rather under-defined as it currently stands (and behaves).

**Comment by yuyichao** [comment]
> How can the return value of size be correct when the adjoint of a vector is not a map from vectors to vectors but from vectors to scalars.

Because scalar does not have dimension 0 or nothing.

```julia
julia> size(1, 1)
1
```

> Having size return (1,n) would mean that it is a linear map from vectors with n-elements to vectors with 1-element.

No, it just mean the returned value should have a dimension of `1`, which it does.

> For your second point. The proposal would exactly provide that guarantee as the return value of collect would be identical to it's input value.

No it doesn't. What I'm talking about is that this is a property that's impossible to achieve for all input type and it is not at all the goal of this function. If you want a function that maintains all properties of a type, the correct function to use is `identity`.

> collect is rather under-defined as it currently stands (and behaves).

While I think there are probably things that are less than well defined but I think the matching of the shape is pretty well define here.

**Comment by roelstappers** [comment]
The size of a scalar is current an empty tuple

```
julia> size(1)
()
```

**Comment by yuyichao** [comment]
> The size of a scalar is current an empty tuple

Correct, but it does have a size 1. What I was saying is that returning `0` or a non-number doesn't make any sense.

**Comment by mbauman** [comment]
That's correct — it behaves like a 0-dimensional array.  Just like zero-dimensional arrays, though, you can ask for the length of the "missing" dimensions and it'll return 1.

**Comment by roelstappers** [comment]
Sorry for asking so many questions but I don't understand why it would it be a problem to return 0? Does it have to do with numbers being iterable in Julia? e.g. in this issue #11769 Jeff mentions numbers to be zero-dimensional so why couldn't size just return 0? 

And I guess for the missing dimensions returning 0 instead of 1 could make sense but that is a bit out of scope of the current issue.

**Comment by mbauman** [comment]
These are better questions for the [discourse mailing list](https://discourse.julialang.org).  `0×N` already has a very well-defined meaning (it's an empty matrix with 0 rows).

**Comment by roelstappers** [comment]
I removed the last sentence from the original issue to keep the discussion focused on the behavior of `collect`

**Comment by Moelf** [comment]
This should be closed, `collect` is not `identity`. When the object is "lazy" wrapper, I lean towards the `collect` materialize something, in this case, makes a matrix.

An analogy can be drawn from a lazy vector that is `<:AbstractVector{T}`, although it behaves like a vector in all possible ways, `collect()` should materialize it.

**Comment by Moelf** [comment]
how come? It's pretty common for textbooks to write something like:
> <a, b> = a^T b

or wikipedia:
>if vectors are identified with row matrices, a b^T
