### ISSUE TITLE
secretbuffer test error

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#37218]
```
secretbuffer                       (5) |        started at 2020-08-26T08:30:12.705
      From worker 5:	error in running finalizer: ErrorException("task switch not allowed from inside gc finalizer")
```
https://build.julialang.org/#/builders/79/builds/2768/steps/5/logs/stdio

**Comment by Keno** [comment]
I was able to reproduce this locally by tweaking the collection interval. rr trace: https://s3.amazonaws.com/julialang-dumps/reports/2020-10-30T20-25-53-Keno.tar.zst

**Comment by Keno** [comment]
I have a fix.
