### ISSUE TITLE
sinc and cosc inaccuracy and type-instability

### ISSUE THREAD

**Issue by petvana** [JuliaLang/julia#37227]
The main motivation to use sinc function is its nice and smooth behavior around zero. However, the current implementation can produce results greater than 1 close to zero, and the results are not even monotonous. 

``` julia
julia> sinc(1e-20)
1.0
julia> sinc(1e-30)
1.0
julia> sinc(1e-40)
1.0000000000000002
julia> sinc(1e-50)
1.0
julia> sinc(1e-60)
1.0000000000000002
julia> sinc(1e-70)
1.0
julia> sinc(1e-80)
1.0000000000000002
julia> sinc(1e-90)
1.0
```

Possible solution is simple: 

``` julia
sinc(x::Real) = abs(x) < 1e-10 ? one(x) : isinf(x) ? zero(x) : sinpi(x)/(pi*x)
```

However, this is not general enough for various data types, because the constant 1e-10 does not work for more precise data types.

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by stevengj** [comment]
Technically, this is not a numerical "instability".   But it is not giving an exactly rounded result, and I agree that it should be possible to do better here.

**Comment by stevengj** [comment]
Another problem is that the [current implementation](https://github.com/JuliaLang/julia/blob/e0cc82bc2277685d1b71f7acb1e13fc65a0ed1dc/base/special/trig.jl#L1056-L1065) is not always type-stable:
```jl
julia> sinc(3//4)
0.3001054387190354

julia> sinc(0//4)
1//1
```

**Comment by stevengj** [comment]
More generally, as long as we are computing a precision-dependent threshold, one could switch to the Taylor expansion for sufficiently small `x`, since this is probably slightly faster than `sinpi(x)/(pi*x)`.
```
sinc(x) = abs(x) < sincthreshold(x) ? @evalpoly(x^2, 1, -pi^2/6, pi^4/120) : isinf(x) ? zero(x) : sinpi(x)/(pi*x)
```
with some modifications to make this type stable.   As you say, determining the threshold is a bit annoying to do in a generic way.  For floating-point `x`, it is determined by `abs(x)^6  * pi^6/5040 < eps(typeof(x))`.   I suppose we could use a generated function for `sincthreshold`.

**Comment by petvana** [comment]
This is exactly what I was thinking of but I don't know yet how to write a generated and generic-enough function for that. Notice the problem seems to be common also for cosc function (also defined a as division).

**Comment by oscardssmith** [comment]
Note that a minimax function will likely work for a larger range at acceptable accuracy than a taylor expansion.

**Comment by stevengj** [comment]
You mean, something like `sinc(x) = ifelse(iszero(x), one(x), min(one(x), sinpi(x)/(pi*x)))`

**Comment by stevengj** [comment]
@petvana, I didn't even realize that we had `cosc` function.    The [current implementation of `cosc`](https://github.com/JuliaLang/julia/blob/7c4809122126b22d993da0b8f82636882b828328/base/special/trig.jl#L1067-L1077) is much worse — it really *is* numerically unstable, suffering from catastrophic cancellation near zero:
```
julia> cosc(1e-20)
0.0

julia> cosc(big(1e-20))
-3.289868133696452692506325852996527191782335372598840071672408487965980404206592e-20
```
i.e. it lost *all* of the significant digits.

**Comment by stevengj** [comment]
In @JeffBezanson's defense, this `cosc` implementation was added way back in 1917197353051c65929126b7afd2b0c38dbb93ea when Julia files still ended with `.j`; I think floating-point arithmetic hadn't been invented yet 😉 .

**Comment by oscardssmith** [comment]
@stevengj sorry that was unclear. I meanta minimax polynomial. Check out remez.jl for more details, but basically given a range and degree, they give the polynomial which had least error over the entire range.

**Comment by stevengj** [comment]
@oscardssmith, ah yes, I see.  Yes, I'm familiar with minimax polynomials — more generally one can use minimax rational functions — from other special functions that I've implemented.   The main difficulty with a minimax polynomial, however, is that then the whole polynomial is precision-dependent, whereas with a Taylor series only the cutoff is precision dependent (and alternatively for arbitrary precision you can loop until the terms decay sufficiently).     Also, in cases like `cosc` where you are approaching a zero of the function you almost always want a Taylor series in order to maintain a small relative error arbitrarily close to the zero.

 In the case of `sinc` and `cosh`, therefore, where we only need to improve accuracy near `x=0`, I suspect that a Taylor-series approach is more important.

**Comment by petvana** [comment]
Btw, `function sinc(x)::Float64` is utilized (by a happy coincidence) as an example in the documentation [types.md](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/types.md). I would select a better one after this discussion ...

**Comment by stevengj** [comment]
I think
```jl
sinc(x::Number) = iszero(x) ? one(float(x)) : sinpi(x)/(pi*x)
sinc(x::Integer) = iszero(x) ? one(x) : zero(x)
sinc(x::Real) = iszero(x) ? one(float(x)) : isinf(x) ? zero(float(x)) : min(one(float(x)), sinpi(x)/(pi*x))
```
should probably suffice for `sinc`, though it wouldn't hurt to add optimized `FloatXX` methods.

**Comment by stevengj** [comment]
Here's an implementation that speeds up the `Float32` and `Float64` cases by a factor of 2 or more for small arguments, while remaining type stable and (and ≤ 1) for other well-behaved types.
```jl
sinc(x::Number) = _sinc(float(x))
sinc(x::Integer) = iszero(x) ? one(x) : zero(x)
_sinc(x::Real) = iszero(x) ? one(x) : isinf(x) ? zero(x) : min(one(x), sinpi(x)/(pi*x))
_sinc(x::Number) = iszero(x) ? one(x) : sinpi(x)/(pi*x)
_sinc_threshold(::Type{Float64}) = 0.001
_sinc_threshold(::Type{Float32}) = 0.05
@inline function _sinc(x::Union{T,Complex{T}}) where {T<:Union{Float32,Float64}}
    a = abs(real(x)) + abs(imag(x))
    return a < _sinc_threshold(T) ? @evalpoly(x^2, T(1), -T(pi)^2/6, T(pi)^4/120) : isinf(a) ? zero(x) : sinpi(x)/(pi*x)
end
```

**Comment by oscardssmith** [comment]
for cosc, `-xpi^2/3+x^3pi^4/30-x^5pi^6/840` works for `Float32` in `(-.08,.08)` and for `Float64` in `(-.004,.004)`. Dropping a degree from the `Float32` version probably isn't worth it as it significantly decreases the convergence radius.

**Comment by stevengj** [comment]
> This is still problematic because it returns incorrect value for very small values.

It's still "correct" in the sense of having a small relative error, it's just not exactly rounded.   So it still seems fine to me as a fallback, but obviously it's better to use the Taylor-series version for the common cases of single and double precision.

**Comment by stevengj** [comment]
> for cosc, `-x*pi^2/3+x^3*pi^4/30-x^5*pi^6/840` works for `Float32` in `(-.08,.08)` and for `Float64` in `(-.003,.003)`.

For `0.004` the current `cosc` implementation still has an error a bit larger than I would like:
```
julia> Float64((cosc(0.004) - cosc(big(0.004))) / cosc(big(0.004)))
-5.645431816105822e-13
```
so I suspect we'll need to go to one higher degree for `Float64`.

**Comment by oscardssmith** [comment]
Then the next in the series is `x^7*pi^8/45360` The full sequence for denominators is https://oeis.org/A174549 (`(2*n-1)! + (2*n)!`) if we want to do fancy dynamic stuff.

**Comment by stevengj** [comment]
Here is a generic routine that should work (albeit relatively slowly) for any type, including `BigFloat`:
```jl
cosc(x::Number) = _cosc(float(x))
function _cosc(x::Number)
    if abs(x) < 0.5
        # generic Taylor series: π ∑ (-πx)^{2n-1}/a(n) where
        # a(n) = (1+2n)*(2n-1)! (= OEIS A174549)
        s = (term = -(π*x))/3
        π²x² = term^2
        ε = eps(abs(term)) # error threshold to stop sum
        n = 1
        while true
            n += 1
            term *= π²x²/((1-2n)*(2n-2))
            s += (δs = term/(1+2n))
            abs(δs) ≤ ε && break
        end
        return π*s
    else
        return x isa Real && isinf(x) ? zero(x) : ((pi*x)*cospi(x)-sinpi(x))/((pi*x)*x)
    end
end
```

**Comment by stevengj** [comment]
Here are the Float32 and Float64 optimized versions:
```jl
# hard-code Float64/Float32 Taylor series, with coefficients
#  Float64.([(-1)^n*big(pi)^(2n)/((2n+1)*factorial(2n-1)) for n = 1:6])
_cosc(x::Union{Float64,ComplexF64}) =
    abs(real(x))+abs(imag(x)) < 0.14 ? x*@evalpoly(x^2, -3.289868133696453, 3.2469697011334144, -1.1445109447325053, 0.2091827825412384, -0.023460810354558236, 0.001781145516372852) : 
    x isa Real && isinf(x) ? zero(x) : ((pi*x)*cospi(x)-sinpi(x))/((pi*x)*x)
_cosc(x::Union{Float32,ComplexF32}) =
    abs(real(x))+abs(imag(x)) < 0.26 ? x*@evalpoly(x^2, -3.289868, 3.2469697, -1.144511, 0.20918278) : 
    x isa Real && isinf(x) ? zero(x) : ((pi*x)*cospi(x)-sinpi(x))/((pi*x)*x)
```

**Comment by stevengj** [comment]
I'll try to put together a PR this weekend.

**Comment by N3N5** [comment]
Then move the original implement to FastMath?

**Comment by petvana** [comment]
> Then move the original implement to FastMath?

I wouldn't do so. The speed-up of `sinc` is not so significant, and `cosc` seems to be even faster than the original (Base) version. Notice also, the original version is significantly faster only nearby zero.

``` julia
julia> x = rand(10000);

julia> @btime sinc.(x);
  177.529 μs (5 allocations: 78.27 KiB)
julia> @btime Base.sinc.(x);
  171.738 μs (5 allocations: 78.27 KiB)

julia> @btime cosc.(x);
  252.226 μs (5 allocations: 78.27 KiB)
julia> @btime Base.cosc.(x);
  292.728 μs (5 allocations: 78.27 KiB)

julia> @btime sin.(x);
  69.210 μs (5 allocations: 78.27 KiB)
```

**Comment by stevengj** [comment]
> the original version is significantly faster only nearby zero.

Sorry if I wasn't clear — near zero the *new* implementation is faster for both `sinc` and `cosc`:
```jl
julia> x = rand(Float64, 100)/1000; xf = Float32.(x);

julia> @btime sum(Base.sinc, $x); @btime sum(sinc, $x);
  1.278 μs (0 allocations: 0 bytes)
  403.865 ns (0 allocations: 0 bytes)

julia> @btime sum(Base.sinc, $xf); @btime sum(sinc, $xf);
  992.455 ns (0 allocations: 0 bytes)
  407.615 ns (0 allocations: 0 bytes)

julia> @btime sum(Base.cosc, $x); @btime sum(cosc, $x);
  2.655 μs (0 allocations: 0 bytes)
  425.477 ns (0 allocations: 0 bytes)

julia> @btime sum(Base.cosc, $xf); @btime sum(cosc, $xf);
  2.131 μs (0 allocations: 0 bytes)
  405.568 ns (0 allocations: 0 bytes)

```

**Comment by stevengj** [comment]
I have to admit that the "`cosc` function" is new to me, and I wonder how widespread this terminology is?

So far, the only reference I can find for our definition of `cosc` are [these 1999 seminar notes](https://old.cescg.org/CESCG99/TTheussl/node2.html).  Are there any other references?  @JeffBezanson, where did you take this definition from when you added it in 2010?

Other definitions include:

* [This 2014 paper](https://www.sciencedirect.com/science/article/pii/S1063520313000687) defines `cosc(x)` as the Hilbert transform of `sinc(x)`, i.e. `cosc(x) = (1-cospi(x))/(π*x) = 2sinpi(x/2)^2 / (π*x)` (where the latter formulation is free from cancellation error), citing a [1989 paper](https://doi.org/10.1109/29.31288) (that also defines a "zinc" function).

* [This paper](http://fs.unm.edu/ScArt/CardinalIntegralFunctions.pdf) defines `cosc(x)` as the obvious but uninteresting `cos(x)/x`.

On the other hand, the `d(sinc)/dx` definition seems pretty useful, especially now that differentiable programming is all the rate, and especially because the naive derivative implementation is numerically unstable.

**Comment by JeffBezanson** [comment]
I don't remember, but it's possible I got it from those very notes --- I probably learned about it in the context of windowing functions for image reconstruction. I'm pretty sure we used the derivative definition in the MRI lab.

**Comment by petvana** [comment]
Just for the record, I found `sinc` first in a recent paper [A novel formalisation of the Markov-Dubins problem](https://ieeexplore.ieee.org/abstract/document/9143597) published robotic conference this year. It enables to model both straight and turn trajectory segments by a single equation.

**Comment by stevengj** [comment]
@petvana, the `sinc` function is totally standard (modulo two conventions about π factors), it's `cosc` that I was wondering about.
