### ISSUE TITLE
Parallel loading of packages (at least JLLs)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#37259]
Loading packages has gotten much faster (more than 50% faster), but still not as fast as I would like with the brand-new master.

I'm not sure if this been proposed (or know of a good way to search through issues) but I'm sure parallel loading could help, with packages having a big tree of dependencies.

For general packages this could be a breaking change, as in theory `using` some package could e.g. print something (I've e.g. used for debug reasons, but side-effects not sensible otherwise?), while at least I wouldn't mind about non-deterministic order (given the potential large speedup) as long as in the end all the packages gets loaded with the end-state the same. I'm also thinking, could the start loading dependent packages as soon as the Projects file has been parsed?

Since we know the code for JLL packages, the code is autogenerated, we could start with applying such parallelism to those only, at least to see how viable this idea is. I foresee we could have a flag in the Projects file (for non-JLL at least) packages, "allow-loading-in-parallel" (or maybe less conservatively, a flag to disallow that), if people are worried about "technically breaking".

**Comment by KristofferC** [comment]
Issues like these are really too vague to be actionable. Parallelizing things can theoretically improve performance, yes, but it is often technically very hard, and unless the issue has done some legwork of looking into these difficulties it doesn't really serve a purpose. 

Also, regarding JLL packages, I know @staticfloat is working on some stuff that will make them significantly faster to load.

**Comment by PallHaraldsson** [comment]
I thought his work was already in, but good to know something more being worked on. Yes, the idea is general, and only an idea. I had some specific ones though. I was also adding some background, just as you closed.
