### ISSUE TITLE
disallow replacement characters?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#37267]
I just noticed that U+FFFC (object replacement character) and U+FFFD (replacement character) are allowed to begin identifiers, since they are in category Symbol - other (So). They should be invalid characters instead. (I would almost say "So" seems like the wrong category for them, but no point in having an opinion on that!)

**Comment by StefanKarpinski** [comment]
This seems like a pretty unlikely character for anyone to be using intentionally. The fact that it may be possible to be using it accidentally and in a broken way at that is good reason to disallow it.
