### ISSUE TITLE
walkdir no longer errors if it is called on a non-existing folder

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#37260]
master:

```jl
julia> i = walkdir("non-existing")
Channel{Tuple{String,Vector{String},Vector{String}}}(0) (closed)

julia> iterate(i)
ERROR: IOError: readdir: no such file or directory (ENOENT) with "non-existing"
```

1.5:

```jl
julia> i = walkdir("non-existing")
ERROR: SystemError: unable to read directory non-existing: No such file or directory
```

Broke some tests of people that did `@test_throws ... walkdir("non-existing")`. Why they did that? I don't know..

This feels like a bit like if a tree falls in the forest and no one is around to hear it... Marking it for 1.6 so that a decision can be made. I think @vtjnash did some work on `walkdir` so pinging him.

**Comment by StefanKarpinski** [comment]
This seems like it might be the same underlying issue as https://github.com/JuliaLang/julia/issues/36605?

**Comment by KristofferC** [comment]
I don't think so. `walkdir` is an iterator so the "issue" here just comes from that fact that it doesn't consume anything on creation which the old implementation did. But this seems more like a feature than a bug, for example, why shouldn't

```
i = walkdir("foo")
mkdir("foo")
iterate(i)
```

work?


I would say this is different from `open` (as in #36605?) which does an actual file system operation when you call it and doesn't just create a lazy object.

**Comment by vtjnash** [comment]
That still isn't expected to (and doesn't) work. The question is just whether we want to preserve the asymmetry here, which may require some extra work from both the caller and callee:
```diff
diff --git a/base/file.jl b/base/file.jl
index a844f06d0c..1822c73e77 100644
--- a/base/file.jl
+++ b/base/file.jl
@@ -869,5 +869,5 @@ julia> (root, dirs, files) = first(itr)
 """
 function walkdir(root; topdown=true, follow_symlinks=false, onerror=throw)
-    function _walkdir(chnl, root)
+    function _walkdir(chnl, root, content)
         tryf(f, p) = try
                 f(p)
@@ -881,5 +881,4 @@ function walkdir(root; topdown=true, follow_symlinks=false, onerror=throw)
                 return
             end
-        content = tryf(readdir, root)
         content === nothing && return
         dirs = Vector{eltype(content)}()
@@ -900,5 +899,5 @@ function walkdir(root; topdown=true, follow_symlinks=false, onerror=throw)
         end
         for dir in dirs
-            _walkdir(chnl, joinpath(root, dir))
+            _walkdir(chnl, joinpath(root, dir), tryf(readdir, root))
         end
         if !topdown
@@ -907,5 +906,12 @@ function walkdir(root; topdown=true, follow_symlinks=false, onerror=throw)
         nothing
     end
-    return Channel{Tuple{String,Vector{String},Vector{String}}}(chnl -> _walkdir(chnl, root))
+    content = try
+            readdir(root)
+        catch err
+            isa(err, IOError) || rethrow()
+            onerror(err)
+            nothing
+        end
+    return Channel{Tuple{String,Vector{String},Vector{String}}}(chnl -> _walkdir(chnl, root, content))
 end

```
...and even so, the type of the error is not stable for that test.

**Comment by vtjnash** [comment]
I'm going to recommend closing this as the next triage session. Happen to listen to counter arguments as I'm not invested, just feels like this is the better behavior, and not actually breaking (other than of bad tests).

**Comment by JeffBezanson** [comment]
Python os.walk("nonexistent") doesn't error, and when you try to iterate it you just get no items, with no error either. A bit dubious. But, it does work (giving you the entries) if you create the directory in between creating the iterator and using it. In contrast, we actually do read the directory eagerly, we just defer the error until later.

Triage also observes that passing a nonexistent directory to this function is pretty much the only failure mode (aside from e.g. hardware errors), so it might make sense to error eagerly.

**Comment by vtjnash** [comment]
FWIW, there are other failure modes. This previously also failed eagerly if `x` (readdir) or `r` (islink) access is missing from the argument, or fails lazily with those same errors if they're missing from any of the children.

**Comment by vtjnash** [comment]
Seems like this was for release 1.6, which is final now
