### ISSUE TITLE
Zero-dimensional views of AbstractVectors assume that the parent is 1-indexed

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#37274]
This is the same issue reported in [OffsetArrays](https://github.com/JuliaArrays/OffsetArrays.jl/issues/128), but I'm posting it here as I'm not sure if the fix should go into `Base`. Please close this if it's more appropriate for the fix to be in `OffsetArrays`.

For a zero-dimensional array `a` we usually expect `a[] == a[1]`. However this does not work with zero-D views of `OffsetVector`s

```julia
julia> using OffsetArrays

julia> a = OffsetArray(1:3, 0:2);

julia> b = @view a[0]
0-dimensional view(OffsetArray(::UnitRange{Int64}, 0:2), 0) with eltype Int64:
1

julia> b[]
1

julia> b[1]
2
```

**Comment by stevengj** [comment]
I've traced it down to [this line](https://github.com/JuliaLang/julia/blob/41e603e5836bebf447f14c82fb2671b3567fc3bf/base/subarray.jl#L386), which seems like it incorrectly assumes that linear indices start at `1`.

@timholy, it seems that you wrote that code back in #16260, can you comment?

**Comment by timholy** [comment]
> @timholy, it seems that you wrote that code back in #16260, can you comment?

I often struggle to remember last Tuesday, so I don't recall anything useful, but that looks like it predates offset axes (going by [the blog post](https://julialang.org/blog/2017/04/offset-arrays/) date). Thanks for catching this use case, @jishnub.

@stevengj, that line enacts [the "linear indexing starts at 1" policy](https://docs.julialang.org/en/latest/devdocs/offset-arrays/#Linear-indexing-(LinearIndices)-1) with the exemption for 1d arrays on https://github.com/JuliaLang/julia/blob/41e603e5836bebf447f14c82fb2671b3567fc3bf/base/subarray.jl#L377-L378
I'm guessing we need a 0-dimensional exemption as well?

**Comment by stevengj** [comment]
> I'm guessing we need a 0-dimensional exemption as well?

The underlying array is 1d in this case, and since this is computing an offset index into the original array shouldn't the 1d exemption apply?

**Comment by fghorow** [comment]
A question: would this bug affect the ordering of an OffsetArray (I_Ωpp) being written out via a Numpy call of the form `np.save("./I_Omega_pp_R_interpolated.npy",I_Ωpp)`?
If so, I've been chasing problems caused by this for weeks! :-(
