### ISSUE TITLE
change generate_precompile assertion threshold

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#37279]
Failed here: https://build.julialang.org/#/builders/38/builds/3034
In that case we executed 1482 instead of 1500 statements. Is it possible that indicates a real issue, or is this test just too brittle?

**Comment by KristofferC** [comment]
I think the new invalidation work has just pushed it down. We could just remove the assertion?

**Comment by timholy** [comment]
For the record I think we were at about 1950 precompile statements when the inference-quality arm of the invalidation work started. The ones we lost were good riddance. There are still some to go, though.

**Comment by timholy** [comment]
But of course if a PR breaks some stuff (e.g., Julia can't find a method for a call) then that can make the number drop even further, and in those cases it does indicate an error. I haven't yet seen it fail on a working build of Julia, but I've had my eye on needing to lower this threshold.
