### ISSUE TITLE
Ambiguity between the representation of Expr containing hexadecimal literals and juxtaposing of a variable starting with 'x'

### ISSUE THREAD

**Issue by AFatNiBBa** [JuliaLang/julia#37282]
The two Expr "a" and "b" have two very different meanings but are represented in the same way by the "string" function.
The problem is fortunately only of the representation since both of the Expr get evaluated correctly.
```julia
x01 = 5
#output: 
# 5
a = :((0)x01 + 9)
#output: 
# :(0x01 + 9)
b = :(0x01 + 9)
#output: 
# :(0x01 + 9)
@eval $a
#output: 
# 9
@eval $b
#output: 
# 10

#=
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
=#
```

**Comment by petvana** [comment]
Is this really a `display and printing` problem? I am suprised that such multiplication is allowed at the first place. Sometimes the rules are very confising:

``` julia
x = 1

# This is OK
1(2)
(2)1
(1)(2)
(1)x    # Depricate this?
(x)x    # Depricate this?

# This is not allowed
(x)1       # Why not allowed once even (x)x is allowed?
(1+x)(x) 
x(1) # This is obvious - function call
(x)(x) # This may be seen also as a function call
```

**Comment by JeffBezanson** [comment]
Yes, it's a printing problem because we're printing something in a way that is not parsed back correctly. If you don't like the syntax to begin with, ok, but that's a separate issue.

**Comment by AFatNiBBa** [comment]
I'm personally ok with the syntax, just pointing out the problem
