### ISSUE TITLE
Document how to use `@test_logs` to test for no messages

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/julia#37307]
The docs for `@test_nowarn` say
> Note: The absence of warnings generated by `@warn` cannot be tested with this macro. Use `@test_logs expr` instead.

But the `@test_logs` docs don't mention how to test the absence of (warning) messages.

The answer is to pass no arguments to `@test_logs` (and to set the `min_level` accordingly) e.g.
```julia
julia> using Test, Logging

julia> f() = 1;

julia> g() = (@info "It's a 2"; 2);

julia> @test_logs f()  # test `f` logs no messages
1

julia> @test_logs g()  
Log Test Failed at REPL[5]:1
  Expression: g()
  Log Pattern:
  Captured Logs:
    Test.LogRecord(Info, "It's a 2", Main, Symbol("REPL[3]"), :Main_ecb0a5a5, "REPL[3]", 1, Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}())

ERROR: There was an error during testing

julia> @test_logs min_level=Logging.Warn g()  # test `g` logs no messages at `Warn` or higher
2
```

It would be useful to mention something along these lines in the `@test_logs` docs.

**Comment by sheetalojha** [comment]
@nickrobinson251  is it okay if I work on this issue? 
I'd very much like to

**Comment by StefanKarpinski** [comment]
Sure.
