### ISSUE TITLE
upstream SuiteSparse shlib patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37323]
https://github.com/JuliaLang/julia/blob/master/deps/patches/SuiteSparse-shlib.patch

This patch should be upstreamed at https://github.com/DrTimothyAldenDavis/SuiteSparse

**Comment by ViralBShah** [comment]
Closed by https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/111
