### ISSUE TITLE
upstream libgit2 ssh-agent non-fatal patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37329]
https://github.com/JuliaLang/julia/blob/master/deps/patches/libgit2-agent-nonfatal.patch

This patch should be upstreamed at https://github.com/libgit2/libgit2

**Comment by vtjnash** [comment]
Libgit2 issue is https://github.com/libgit2/libgit2/issues/3866

**Comment by giordano** [comment]
Patch upstreamed (and accepted) by https://github.com/libgit2/libgit2/pull/6497
