### ISSUE TITLE
upstream SuiteSparse winclang patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37322]
https://github.com/JuliaLang/julia/blob/master/deps/patches/SuiteSparse-winclang.patch

Should be upstreamed here: https://github.com/DrTimothyAldenDavis/SuiteSparse

**Comment by ViralBShah** [comment]
@vtjnash @keno Do we still need this winclang patch? We are not carrying it on Yggdrasil, and there haven't been any complaints.

**Comment by vtjnash** [comment]
We don’t build with clang (which is what this patch apparently was for)

**Comment by ViralBShah** [comment]
While we do not apply it in Yggdrasil, we are still applying it in `deps`: https://github.com/JuliaLang/julia/blob/6f71de4193717f9267e98b4188aa6e4547146375/deps/suitesparse.mk#L45

Should we remove it?
