### ISSUE TITLE
Markdown: footnote and admonition only allow spaces, not tabs

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#37335]
The syntax for [footnote definitions](https://docs.julialang.org/en/v1/stdlib/Markdown/#Footnotes) and [admonitions](https://docs.julialang.org/en/v1/stdlib/Markdown/#Admonitions) is based on indentation, but only 3-4 spaces are interpreted, tabs are ignored and treated as the start of a new code block.

<img src="https://user-images.githubusercontent.com/6933510/91904855-ebea9600-eca5-11ea-8f1b-668149b78999.png" width="50%"><img src="https://user-images.githubusercontent.com/6933510/91904830-e2612e00-eca5-11ea-901d-1dccc07eef0a.png" width="50%">

**Comment by fredrikekre** [comment]
Don't you typically write it as
```
Have a look at [^this]

[^this]: asdf
```

**Comment by fonsp** [comment]
True, I mostly included it for completeness

**Comment by fonsp** [comment]
I will try to fix this myself!
