### ISSUE TITLE
upstream libunwind prefer extbl patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37330]
https://github.com/JuliaLang/julia/blob/master/deps/patches/libunwind-prefer-extbl.patch

This should be upstreamed at https://github.com/libunwind/libunwind

If someone could please assign @yuyichao to this issue, that would be helpful. (I can't because he has for some reason blocked me on GitHub.)

**Comment by vtjnash** [comment]
Closed by https://github.com/libunwind/libunwind/pull/297
