### ISSUE TITLE
Markdown: Interpolating $ inside **bold** can become LaTeX

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#37336]
![image](https://user-images.githubusercontent.com/6933510/91905461-dd50ae80-eca6-11ea-870f-8c349b713051.png)

The code that failed is:
```julia
md"Hi, $planet **$planet**"
```

My guesswork: detecting the LaTeX sequence `$planet **$` is wrongly prioritized over the bold sequence `**$planet**`.

**Comment by simeonschaub** [comment]
Should have been fixed by #37130?

**Comment by fonsp** [comment]
Thanks for checking 👍

**Comment by fredrikekre** [comment]
> detecting the LaTeX sequence $planet **$ is wrongly prioritized over the bold sequence **$planet**

Isn't it ambiguous since the two environments interlapping?

**Comment by fonsp** [comment]
It is - I guess my request is to implement a priority system to disambiguate? I have time in a couple of weeks to look at this myself

**Comment by fredrikekre** [comment]
Since we support ``` `` ```for inline math, and since `$` is used for interpolation, maybe we should just deprecate `$` and `$$` for math environments.

**Comment by fredrikekre** [comment]
#36946
