### ISSUE TITLE
upstream libunwind static ARM patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37331]
https://github.com/JuliaLang/julia/blob/master/deps/patches/libunwind-static-arm.patch

This patch should be upstreamed at https://github.com/libunwind/libunwind

**Comment by vtjnash** [comment]
Closed by https://github.com/libunwind/libunwind/commit/1dd0b64fa9d0be66252f7f66e530fffbd59dde86
