### ISSUE TITLE
Adding madvise to the Mmap stdlib

### ISSUE THREAD

**Issue by jmert** [JuliaLang/julia#37353]
I've got a use case where I _think_ being able to `madvise` a memory-mapped array with the `MADV_WILLNEED` flag will help me with a computation/program I'm working on.

I've prototyped an implementation of a new `Mmap.madvise!` function, but before making a PR for it, I'd like to ask for feedback on whether it is desired. Right now, the `Mmap.mmap` and `Mmap.sync!` functions work on *nix & Windows, but as far as I can tell, Windows doesn't have any good equivalent of `madvise`. Therefore, my prototype `Mmap.madvise!` is only exposed on Unix system.

Is that an OK direction for a function in the standard library to take, or should this function live elsewhere?

**Comment by quinnj** [comment]
I think that'd be fine to add to `Mmap` module; there are already a few other functions/constants that are platform-specific, so you can just put the definition in those if-else blocks. If anyone's doing advanced mmap stuff like this, they pretty much have to get into OS-specific details.
