### ISSUE TITLE
Return value for non-static functions not treated as use by static analyser

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#37364]
The following C code added in any clangsa scanned source file should trigger an error but doesn't. The issue seems to be that the return value isn't treated as a use. Replacing the return by `jl_typeof` triggers an error correctly.

Since the analyser is smart enough about control flow, not error about unused return value from static functions should be fine (though still worth a warning unless suppressed with some marking). However, all return values from non-static function, especially exported function should certainly be treated as used...

```julia
JL_DLLEXPORT jl_value_t *jl_totally_used_function(int i)
{
    jl_value_t *v = jl_box_int32(i);
    jl_safepoint();
    return v; // jl_typeof(v);
}
```

**Comment by Keno** [comment]
This code is technically not a problem if nobody ever looks at the return value of that function. It's not hard to make an error though by just having the analyzer visit the ReturnNode and do the use analysis.
