### ISSUE TITLE
Unions with static type parameters are problematic

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#3738]
This works:
```julia
julia> f(x::Int; y::Union(Symbol, Int)=:foo) = println(y)
# methods for generic function f
f(x::Int64) at none:1

julia> f(1)
foo

julia> f(1, y=:bar)
bar

julia> f(1, y=3)
3
```
A parametric version instead fails with a cryptic message:
```julia
julia> g{T}(x::T; y::Union(Symbol, T)=:foo) = println(y)
# methods for generic function g
g{T}(x::T) at none:1

julia> g(1)
ERROR: no method g#g2(Symbol,Int64)

julia> g(1, y=:bar)
ERROR: no method g#g2(Symbol,Int64)

julia> g(1, y=3)
3
```
Possibly related, this should be an error but less cryptic and preferrably when the function is defined rather than used.
```julia
julia> h(x::Int; y::Int=0.0) = println(y)
# methods for generic function h
h(x::Int64) at none:1

julia> h(1)
ERROR: no method h#g3(Float64,Int64)
```

**Comment by mbauman** [comment]
As Jeff alludes to, this isn't unique to keyword arguments.  I've updated the title to make it a bit more obvious for future searchers.

The following modification to the above keyword case is a nice reduced example:

```julia
julia> type Foo{T} x::T end

julia> g{T}(x::Foo{T}, y::Union(Symbol, T)) = println(y)
g (generic function with 1 method)

julia> g(Foo(1), :bar)
ERROR: MethodError: `g` has no method matching g(::Foo{Int64}, ::Symbol)
Closest candidates are:
  g{T}(::Foo{T}, ::Union(Symbol,T))

julia> g(Foo(1), 1)
1

julia> g(Foo(:baz), :qux)
qux
```

**Comment by nalimilan** [comment]
@JeffBezanson Does the partial solution suggested by @mbauman sound reasonable to you?

**Comment by mbauman** [comment]
That doesn't quite work since a common use for type-parameter matching within unions is `*{T<:BlasFloat}(A::StridedArray{T,2}, x::StridedArray{T,1})`, where `StridedArray` is actually a typealias for a Union with type parameters.

An alternate solution I played with a few weeks ago is disallowing Unions whose components are non-orthoganol in method signatures… but I didn't manage to see it the whole way through.

**Comment by timholy** [comment]
All of these examples are fixed on master.

**Comment by tkelman** [comment]
> All of these examples are fixed on master.

Do we know what fixed them? Are there corresponding tests?
