### ISSUE TITLE
Mini julep: Add `defaultvalue(T)` method for getting a default value for a type

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#37399]
Proposal: Add a `defaultvalue(T)` or `emptyvalue(T)` generic function to Base that allows specifying a "default", "empty", or "zero" value for a given type.

Motivation: There are scenarios like parsing or serialization/deserialization where a "default" value of a type is desired as a placeholder or to accompany an additional "flag" variable to indicate success/failure of parsing/deserializing a given type. Base provides a `zero(T)` function that works for `Real` types, and `similar` that works for collections/`AbstractArray` types, but nothing more higher-level that would be applicable to all types.

Implementation:

```julia
function defaultvalue end

defaultvalue(x::T) = defaultvalue(T)
defaultvalue(::Type{T}) where {T <: Real} = zero(T)
defaultvalue(::Type{T}) where {T <: AbstractArray} = similar(T, 0)
# additional methods for other types
```

Concrete needs:
* Parsers.jl has internal methods that desire type stability in returning a requested type, even if parsing fails; so the desired return type is `::Tuple{T, Flag}`, where `Flag` will signal whether parsing succeeded or not
* Arrow.jl: when serializing arrow arrays, missing values are stored in a separate "validity bitmap" and the full array is serialized with missing slots having "undefined" values; in the implementation, you could carry the bitmap around and "skip" writing a missing slot in the full array, but it's much more convenient and performant to just be able to write a "zero" element to the slot.

Personally, I feel the need for this isn't _incredibly_ strong, but it would make several scenarios much more convenient; instead of needing to special-case another type each time a bug reports comes up, it'd be nice to just use `Base.defaultvalue(T)` and not worry about it (or at least tell the custom type to just overload it). I say that because I understand if there's pushback here, but I wanted to bring it up and let others chime in if they've run into a need for this as well.

**Comment by KristofferC** [comment]
Is this something you can really decide on for the type once and for all or does it not have to be in the context of where you are using the type?

**Comment by JeffBezanson** [comment]
Yes, I was going to ask whether returning e.g. `Union{Some{T}, Flag}` works. Or maybe
```
struct Result{T}
    val::Union{Some{T},Nothing}
    flag;:Flag
end
```

**Comment by KristofferC** [comment]
For example in the TOML parser I have

https://github.com/JuliaLang/julia/blob/d2daa81b5f3227210bbd0827d2c2f172c83d9ab1/base/toml_parser.jl#L463

where

https://github.com/JuliaLang/julia/blob/d2daa81b5f3227210bbd0827d2c2f172c83d9ab1/base/toml_parser.jl#L276

and I haven't seen bad performance / allocations from that.

**Comment by quinnj** [comment]
Thanks for the pointers; the original issue has been resolved.
