### ISSUE TITLE
unnecessarily complicated doc example?  or am i confused??

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#37428]
in the [@distributed](https://docs.julialang.org/en/v1.5/manual/distributed-computing/#Parallel-Map-and-Loops) section there is a line which instructs the user to load a file on each process using `include_string`:

```
julia> @everywhere include_string(Main, $(read("count_heads.jl", String)), "count_heads.jl")
```

while that works for me, so does the much simpler `@everywhere include("count_heads.jl")`.  am i missing something?

```
julia> using Distributed

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @everywhere include("count_heads.jl")

julia> a = @spawnat :any count_heads(100000000)
Future(2, 1, 8, nothing)

julia> b = @spawnat :any count_heads(100000000)
Future(3, 1, 9, nothing)

julia> fetch(a)+fetch(b)
99989334
```

**Comment by fredrikekre** [comment]
Your example assumes the file is existing everywhere.

**Comment by bjarthur** [comment]
doesn't the example in the docs assume a file exists as well?

**Comment by KristofferC** [comment]
It sends the string over to the workers.

**Comment by bjarthur** [comment]
oh i see, so the file has to exist on the master process, but not necessarily on the workers.  got it.
