### ISSUE TITLE
Exported convenience function to get a callstack

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#3744]
Currently, in case of errors, the callstack is only printed and displayed by the REPL.

It will be good to have an exported function(s) that can a) print the callstack when called and b) return a stringified version of the same.

See https://groups.google.com/d/topic/julia-users/S485_5jG2Nw/discussion

**Comment by spurll** [comment]
Happened upon this while debugging this PR. Seems relevant: https://github.com/JuliaLang/julia/pull/14469

**Comment by KristofferC** [comment]
I think this is fixed with the `stacktrace()` function that gets printed as:

```
julia> stacktrace()
4-element Array{StackFrame,1}:
 eval(::Module, ::Expr) at REPL.jl:3                                             
 eval_user_input(::Any, ::Base.REPL.REPLBackend) at REPL.jl:69                   
 macro expansion at REPL.jl:100 [inlined]                                        
 (::getfield(Base.REPL, Symbol("##1#2")){Base.REPL.REPLBackend})() at event.jl:9
```
