### ISSUE TITLE
Please help me to find a easiest Algorithm for this case

### ISSUE THREAD

**Issue by xp-gamer** [JuliaLang/julia#37446]
I am working on strings on Julia language. I working on a function where input string format is need to be converted to respective output mentioned below, please help me in finding a easier algorithm for this condition.  

**Input example:**<br />
"aaa[fffff[kkkkk;lllll];ooooo;gggg[nnnnnnn;bbbbbbb]]"<br />
<br />
**Output should be:**<br />
<br />
Array{}<br />
[<br />
    "aaafffffkkkkk",<br />
    "aaaffffflllll",<br />
    "aaaooooo",<br />
    "aaaggggnnnnnnn",<br />
    "aaaggggbbbbbbb"<br />
]<br />

Thanks

**Comment by KristofferC** [comment]
Please use https://discourse.julialang.org/ for questions.
