### ISSUE TITLE
--project stopped working with --output-o in 1.6-DEV?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#37441]
When I run `julia --startup-file=no --sysimage=PATH/TO/sys.so --project=. --output-o=dummy -e 'Base.reinit_stdio(); @eval Sys BINDIR = ccall(:jl_get_julia_bindir, Any, ())::String; Base.init_load_path(); @show Base.load_path()'` (as would be executed via `PackageCompiler.create_sysimage`), Julia 1.5.0 prints something like

> `Base.load_path() = ["$PWD/Project.toml", "/buildworker/worker/package_linux64/build/usr/bin/../share/julia/stdlib/v1.5"]`

while Julia 1.6.0-DEV.851 prints

> `Base.load_path() = [""]`

I think this is causing recent failures in system image build tests in PyCall (e.g., https://travis-ci.org/github/JuliaPy/PyCall.jl/jobs/722001094#L738).

Perhaps an easier way to observe this is to edit PackageCompiler.jl

```diff
diff --git a/src/PackageCompiler.jl b/src/PackageCompiler.jl
index 3d1a177..32daec1 100644
--- a/src/PackageCompiler.jl
+++ b/src/PackageCompiler.jl
@@ -238,6 +238,7 @@ function create_sysimg_object_file(object_file::String, packages::Vector{String}
         @eval Sys BINDIR = ccall(:jl_get_julia_bindir, Any, ())::String
         Base.init_load_path()
         Base.init_depot_path()
+        @show Base.load_path()
         """

     # Ensure packages to be put into sysimage are precompiled by loading them in a
```

and then run `create_sysimg` *with non-default `project` path*.

cc @KristofferC

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/36434 requires us to call  `Base.init_active_project()`. 

Should be fixed by https://github.com/JuliaLang/PackageCompiler.jl/pull/460.
