### ISSUE TITLE
REPL (shells)

### ISSUE THREAD

**Issue by apparluk** [JuliaLang/julia#37455]
Noting [REPLMaker](https://github.com/MasonProtter/ReplMaker.jl) is used by the [LispSyntax](https://github.com/swadey/LispSyntax.jl) package.

Would there be any interest in implementing in Julia an es or xs(C++) shell syntax translator?

At this time my thinking on such proposal is limited to the function writing syntax in those shells.

[es-shell](https://github.com/wryun/es-shell)
[XS](https://github.com/TieDyedDevil/XS)

**Comment by KristofferC** [comment]
This is not really suitable for the issue tracker, I suggest bringing it up at https://discourse.julialang.org/
