### ISSUE TITLE
cross-reference logical operators and short-circuit operators

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37468]
https://discourse.julialang.org/t/and-or-bitwise-or-shortcircuit-what-we-get-searching-docs/46263/25

Specifically cross-reference between `&` and `|` and `&&` and `||`.

**Comment by lmiq** [comment]
Seems that the page https://github.com/JuliaLang/julia/blob/master/doc/src/manual/mathematical-operations.md

was already updated to include the definition of Boolean operators (https://github.com/JuliaLang/julia/commit/2e77a0220dd4673d3949459c061793c89be78a2d#diff-f09e2276d81bfa81e74c5fee8de0e7e8), yet that is still not in the published docs. That part solves this side of the possible misunderstandings.

**Comment by tpapp** [comment]
@lmiq: the context was #35996, which is merged and it is in the published docs for master, which should be in the next release, see

https://docs.julialang.org/en/v1.6-dev/manual/mathematical-operations/#Boolean-Operators

**Comment by simeonschaub** [comment]
I still think it would be useful to cross-link them and shortly explain the differences between the short-circuiting and regular boolean operators.

**Comment by lmiq** [comment]
> I still think it would be useful to cross-link them and shortly explain the differences between the short-circuiting and regular boolean operators.

I am not sure about that. I feel that people who know about the existence of bitwise operators will not run in any confusion with this. Thus, I think the bitwise page should point to this one, but this one should not enter into details of this difference. Anyway, I will add a sentence there, in the direction of what I think could be reasonable.

**Comment by lmiq** [comment]
Actually the operators *without* short-circuit are already mentioned later in the same section, with the appropriate reference. I think adding anything there would be a repetition.

**Comment by jakobnissen** [comment]
Fixed in commit 2435f96 and can be closed
