### ISSUE TITLE
Explain printf format in Julia docs

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#37466]
Currently, the [docs for the Printf standardlib](https://docs.julialang.org/en/v1/stdlib/Printf/) simply mentions it uses "C `printf` style format specification", but does not specify what that is, nor provides a link to the C printf format.

It would be nice to explain it in the docs.

**Comment by apparluk** [comment]
> what that is

`man printf`

`man 3 printf`

**Comment by apparluk** [comment]
```
bash-4.3$ man printf | tail

SEE ALSO
       printf(3)

       Full documentation at: <http://www.gnu.org/software/coreutils/printf>
       or available locally via: info '(coreutils) printf invocation'



GNU coreutils 8.25               January 2016                        PRINTF(1)
bash-4.3$ 
```

I mistakenly clicked the +1 emoji on this ticket.

**Comment by timholy** [comment]
I clicked the +1 deliberately! I've known this format for a long time, but this is precisely the kind of issue that can trip up a newbie. Inserting a link to an external resource is a small step that could make a big difference to users.

@jakobnissen, since you're just learning it, do you want to browse a few sources and pick one you find especially helpful? Then you can use the GitHub pencil icon and submit a pull request and become a Julia contributor!

**Comment by apparluk** [comment]
@samuelcolvin Care to chip in on this ticket?

**Comment by apparluk** [comment]
https://stackoverflow.com/questions/19783030/in-julia-why-is-printf-a-macro-instead-of-a-function

https://github.com/JuliaLang/julia/pull/11941#issuecomment-129966921

**Comment by samuelcolvin** [comment]
@apparluk sorry, maybe I'm missing something but I'm not clear why I'm being asked to chip in?

**Comment by apparluk** [comment]
@samuelcolvin as per [examples](https://github.com/samuelcolvin/JuliaByExample) might you have an opinion on the subject of this ticket?

**Comment by Pramodh-G** [comment]
Hey Guys!

I'd Like to work on this issue, can I go ahead??

**Comment by Pramodh-G** [comment]
@timholy @jakobnissen is it okay if I work on this issue ? I'd very much like to

**Comment by jakobnissen** [comment]
Yes please @Pramodh-G . That would be much appreciated.

**Comment by Pramodh-G** [comment]
@jakobnissen is a link to an explanation enough, or shoud I also put in some words of my own?

**Comment by jakobnissen** [comment]
@Pramodh-G I would say an explanation is ideal, but a link to some authoritative source would also be a real improvement

**Comment by apparluk** [comment]
What about adding a **Noteworthy printing differences** section at the end of this page?

https://docs.julialang.org/en/v1/manual/noteworthy-differences/

**Comment by Pramodh-G** [comment]
@jakobnissen  I'm thinking of linking [this](https://alvinalexander.com/programming/printf-format-cheat-sheet/) or [this](https://www.tutorialspoint.com/c_standard_library/c_function_printf.html).

For the explanation, I have a couple of ideas :

- I could give a very simple intro on how the formats are written, (not including the specifiers as I feel that would make the docstring way too huge) and then ask the user to visit the above sites to get more info on the identifiers and such.

- I could go all out and make a table inside the docstring to show all the specifiers and their usage.

I also plan to add a few doctests to showcase various formats than just floats, as it is in the docs.

Any suggestions/criticsms ?

**Comment by Pramodh-G** [comment]
@apparluk do you mean illustrating why `@printf` is a  macro than a function and more difference in between other languages?? I think that would be better if they added it [here](https://docs.julialang.org/en/v1/manual/noteworthy-differences/) instead of writing it in the `printf` module itself.

May be if @timholy or @jakobnissen  thinks it's a good idea, we can throw in an one liner and then add a link to [noteworthy differences](https://docs.julialang.org/en/v1/manual/noteworthy-differences/)

**Comment by apparluk** [comment]
@jakobnissen until this issue is resolved.

[Wikibooks](https://en.wikibooks.org/wiki/C_Programming/stdio.h/Function_reference#printf) (C function reference)

**Comment by apparluk** [comment]
https://docs.julialang.org/en/v1/stdlib/Printf/

```julia
@printf([io::IOStream], "%Fmt", args...)
```

It would be preferable if the Examples would follow the macro's description.

```julia
julia> @printf("%.0f %.1f %f\n", 0.5, 0.025, -0.0078125)
1 0.0 -0.007813

julia> s = @sprintf("this is a %s %15.1f", "test", 34.567);

julia> println(s)
this is a test            34.6

julia> 
```

_cf_: https://github.com/JuliaLang/julia/issues/37466#issuecomment-691654487 [a **Printing in Julia** section]

Early proponents of Perl were from the Unix sysadmin community.

It's easy enough to setup cpan and install [tinyrepl](https://github.com/nurmi-labs/blogger/wiki/tinyrepl).

[![metacpan](https://user-images.githubusercontent.com/52227507/93169531-92627c80-f725-11ea-85ff-2cd3ec9a7e61.png)](https://metacpan.org/pod/Eval::WithLexicals)

I'd suggest to compile a list of most used Julia `printf` conversions and run these in tinyrepl.

```perl
re.pl$ printf("%.0f %.1f %f\n", 0.5, 0.025, -0.0078125)
0 0.0 -0.007812
1
re.pl$ 
```

Where in Julia the conversion is different, _e.g._, `%c`, after the tinyrepl shell output explain the Julia implementation.

```perl
re.pl$ printf("%c\n", 65)
A
1
re.pl$  
```

> do you mean illustrating why `@printf` is a macro than a function?

_cf_: https://github.com/JuliaLang/julia/issues/37466#issuecomment-689901945

I think whether any content at the end of the [Noteworthy Differences from other Languages](https://docs.julialang.org/en/v1/manual/noteworthy-differences/) page in a proposed new **Printing in Julia** section regarding why a Julia `@printf` macro was implemented, is a decision best left to the authors of that macro.

See [this](https://perldoc.perl.org/functions/sprintf.html) Perl 5 version 32.0 documentation page for the following. 

- universally-known conversions
- widely-supported conversions
- backward (and we do mean "backward") compatibility

**Comment by apparluk** [comment]
Would a man 3 C Library Functions page suffice?

An `ls /usr/man/man3` returns for example curl_mprintf.

Then the [Printf](https://docs.julialang.org/en/v1/stdlib/Printf/) page would read.
 
See also: julia(3), [`@sprintf`](https://docs.julialang.org/en/v1/stdlib/Printf/#Printf.@sprintf)

**Comment by Jswinney117** [comment]
Hi there everyone

**Comment by apparluk** [comment]
> See [this](https://perldoc.perl.org/functions/sprintf.html) Perl 5 version 32.0 documentation page for the following.
>
>- backward (and we do mean "backward") compatibility

Why did https://github.com/JuliaLang/julia/pull/37980 contain the output specifier `%i` instead of `%d`?
