### ISSUE TITLE
"https://docs.julialang.org/en/latest/" points to 1.4

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#37460]
the big text says 1.5-dev, and in the lower left pull-down menu it says 1.4-dev:

<img width="1182" alt="Screen Shot 2020-09-08 at 7 33 28 AM" src="https://user-images.githubusercontent.com/1538268/92471262-a21e1600-f1a5-11ea-9cde-f51e5af643bf.png">

to get to 1.5.1 i have to either go to "https://docs.julialang.org/en/v1/" (which is what is linked to from julialang.org/Documentation", or to "https://docs.julialang.org/en/v1.5/" (which is where i'm sent when
i choose 1.5 in the aforementioned pull-down menu).

seems that "en/latest" needs to be updated?

**Comment by KristofferC** [comment]
Where did you get that link?

**Comment by bjarthur** [comment]
in my history!  :) must have been a valid link at one point.

**Comment by KristofferC** [comment]
I don't think it is anymore. Should probably be removed.

**Comment by fredrikekre** [comment]
> Should probably be removed.

Done.

**Comment by bjarthur** [comment]
could've pointed "latest" to "v1" too
