### ISSUE TITLE
make: *** [Makefile:60: julia-deps] Error 2

### ISSUE THREAD

**Issue by 62f** [JuliaLang/julia#37475]
bash-5.0# pwd
/root/julia
bash-5.0# sudo make -j 8 USE_BINARYBUILDER=0 
Copying in usr/share/man/man1/julia.1
/root/julia/contrib/install.sh 755 /root/julia/contrib/julia-config.jl /root/julia/usr/share/julia/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0/root/julia/deps/tools/uninstallers.mk:22: warning: overriding recipe for target 'uninstall-suitesparse'
/root/julia/deps/suitesparse.mk:88: warning: ignoring old recipe for target 'uninstall-suitesparse'
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   497  100   497    0     0    112      0  0:00:04  0:00:04 --:--:--   120
100   497  100   497    0     0    109      0  0:00:04  0:00:04 --:--:--   116
100   497  100   497    0     0     93      0  0:00:05  0:00:05 --:--:--    93
100   461  100   461    0     0     88      0  0:00:05  0:00:05 --:--:--    89
100   497  100   497    0     0     91      0  0:00:05  0:00:05 --:--:--    92
100   497  100   497    0     0     93      0  0:00:05  0:00:05 --:--:--    94
100   461  100   461    0     0     70      0  0:00:06  0:00:06 --:--:--    71
:- - :-0-       00: 0 0: 1 10  - - : - -0: - -    0      0  0      0      0 --:--:--  100 18378  100 18378    0     0   1423      0  0:00:12  0:00:12 --:--:--  4131
0 - - :0- -: -  -  0   0: 0 00: 0 9   - -0: - -: - -0          00      0      0 --:--:  8  388k    8 33202    0     0   2509      0  0:02:38  0:00:13  0:02:25  6661  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0     43      0  0:00:10  0:00:10 --:--:--   123
0      5  0   28 4 k0       5   106 9 0 6  0      0    0         00    6 9 7        0   0  782k    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
  1 1540k    1 26434    0     0    999      0  0:26:18  0:00:26  0:25:52  1787  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    0   0       0    0    0  1 8 4 6  0         00     1 :5 00: 0 3     0 :000 : 3 7        0  0 1 1. 6 M0        0  08 5 4 2 30        0  0         0  0    2 2 2 3  0   -   0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
curl: (28) Operation timed out after 15002 milliseconds with 0 out of 0 bytes received
make[1]: *** [/root/julia/deps/unwind.mk:8: /root/julia/deps/srccache/libunwind-1.3.1.tar.gz] Error 28
make[1]: *** Waiting for unfinished jobs....
 14  357k   14 51656    0     0    742      0  0:08:13  0:01:09  0:07:04     0
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
 65  388k   65  254k    0     0   3579      0  0:01:51  0:01:12  0:00:39  3207  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
   59 70   3 1 .05 M    59 7  0     106 9k       0  0        2 90       2 1 706  - - :02 :109 9 15 40:00k   19  297k0 : 1 5  0  3 4 5 1 0   2357      0  0:11:09  0:02:09  0  9956    238848kk      9956    237713kk        00          00      22088075          100  284k  100  284k    0     0   2133      0  0:02:16  0:02:16 --:--:--  6845
100  388k  100  388k    0     0   2817      0  0:02:21  0:02:21 --:--:--  3939
1 00     1 404 k   2506        0  144 k0     0 :01 0: 2 9   0  0 :0 21:82594       0 -:0 1 :12 3 31-.-5:M- - :- -  1  3 439723k    0     0   2672      0  3:26:03  0:02:23  :57 1 0:02:48  0:07:09  344000  214k    0  214k    0     0   2232      0 --:--:--  0:0    3 20  1 5 4 0 k0      3321 12  5 0   1 0k    1 : 0   0 5 :01 7    207:8073 : 0 4     100 0    3217741k      0     2 704 k  1 : 0 40: 04      00: 0 3 :20461 4  1 : 0 0 :100  357k    0  357k    0     0   2586      0 --:--:--  0:02:21 --:--:--  3330
 36 31.5M    3 1155k    0    8 0   1 534808k0     6 8    100 61 k2 : 21 : 504     0  0.6 M  4   311.05 M1 3 08 k  4  1342k    0    0      0    0  3 9 24      0  0:54153  1 100 1540k  100 1540k    0     0   3678      0  0:07:08  0:07:08 --:--:--  8535
0     7   03 1 . 54M3 9 2     7    202 77k    0   0 : 4 60: 1 5  4 907:30 7 : 5 9    0   2 65 51915. 6     0  1:3M 8 :2 42 6  03:11708:k1  8    01 :2 8 : 0 60    6 8591270  11 31.5M   11 3 705 k0: 2 6: 2 00  1 0 4 9 50   5697      0  1:36:38  0:11:05  1:25:3:3 71 5  0:1341:.151M    0: 2105: 264 9 719175k    0     0   6085      0  1:30:28  0:18  3419. 51M1 . 6M  1 8  4690 005k9 4 9k    0   0        0  0    6 26613     4 40      51 1 1 . 60M      65219 2 6 15 3 k    0  0     1 : 207 : 3 06 19 0:16:463    1 : 1 0  52 11.6M   52 6238k  1 0 :01 8     7 002 7  6211      0  0:32:42  0:17:08  0:15:34  7 1: 056:22 7 1 17.562M1   62 7393k    0     0   6408      0  0:31:42  0:19:41  0:12:01 9 63 51 13.16.M5 M    9 63 51 11.12.M1 M      0  0     0     6 7 808      6 7 9 90   100 11.6M  100 11.6M    0     0   6812      0  0:29:49  0:29:49 --:--:--  7963
100 31.5M  100 31.5M    0     0  10480      0  0:52:32  0:52:32 --:--:-- 15874
make: *** [Makefile:60: julia-deps] Error 2

**Comment by yuyichao** [comment]
Seems like you have a network issue.

**Comment by 62f** [comment]
bash-5.0# sudo make -j 8  
/root/julia/contrib/install.sh 755 /root/julia/contrib/julia-config.jl /root/julia/usr/share/julia/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   507  100   507    0     0    110      0  0:00:04  0:00:04 --:--:--   123
100   519  100   519    0     0    113      0  0:00:04  0:00:04 --:--:--   113
100   459  100   459    0     0    100      0  0:00:04  0:00:04 --:--:--   100
100   493  100   493    0     0    105      0  0:00:04  0:00:04 --:--:--   105
100   485  100   485    0     0    103      0  0:00:04  0:00:04 --:--:--   103
100   483  100   483    0     0    101      0  0:00:04  0:00:04 --:--:--   101
  0  520k    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0/usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /root/julia/deps/srccache/libuv-35b1504507a7a4168caae3d78db54d1121b121e1/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... i586-alpine-linux-musl
checking host system type... i586-alpine-linux-musl
checking for gcc... gcc -march=pentium4 -m32
  0  781k    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0checking  0  520k    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0yes
checking for C compiler default output file name... a.out
  0  218k    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
  0  781k    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0checking  0  781k    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0no
  3  520k    3 16854    0     0   1037      0  0:08:33  0:00:16  0:08:17  3612o
  0  781k    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0yes
checking whether gcc -march=pentium4 -m32 accepts -g... yes
  6  520k    6 33214    0     0   1816      0  0:04:53  0:00:18  0:04:35  7078none needed
  0  154M    0 50592    0     0   2582      0 17:26:43  0:00:19 17:26:24  6912yes
  0 7113k    0 16825    0     0    859      0  2:21:20  0:00:19  2:21:01  3366GNU
  0  781k    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0gcc3
  0  218k    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0yes
  0  787k    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0-Werror
checking if gcc -march=pentium4 -m32 supports -fvisibility=hidden... yes
  0  781k    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0yes
  9  520k    9 51670    0     0   2373      0  0:03:44  0:00:21  0:03:23  6302yes
  0  218k    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0yes
checking if gcc -march=pentium4 -m32 supports -Wextra flag... yes
  0  154M    0 51640    0     0   2187      0 20:35:46  0:00:23 20:35:23  3562yes
  0  218k    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  781k    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
curl: (28) Operation too slow. Less than 1 bytes/sec transferred the last 15 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 12  520k   12 69078    0     0   2902      0  0:03:03  0:00:23  0:02:40  6512yes
checking for ar... ar
  0  154M    0 51640    0     0   2098      0 21:28:11  0:00:24 21:27:47   208ar
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
  2  787k    2 16840    0     0    681      0  0:19:44  0:00:24  0:19:20  3338/bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc -march=pentium4 -m32... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  0 7113k    0 34233    0     0   1337      0  1:30:48  0:00:25  1:30:23  3469BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 98304
checking how to convert i586-alpine-linux-musl file names to i586-alpine-linux-musl format... func_convert_file_noop
checking how to convert i586-alpine-linux-musl file names to toolchain format... func_convert_file_noop
checking for ld option to reload object files... -r
  2  787k    2 16840    0     0    655      0  0:20:31  0:00:25  0:20:06  3351checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
  2  787k    2 16840    0     0    630      0  0:21:20  0:00:26  0:20:54    92@
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -march=pentium4 -m32 object..  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0ok
checking for sysroot... no
  4  787k    4 34248    0     0   1209      0  0:11:07  0:00:28  0:10:39  3688/bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
  0  154M    0 51640    0     0   1803      0 24:58:57  0:00:28 24:58:29     0checking  0 7113k    0 51641    0     0   1804      0  1:07:17  0:00:28  1:06:49  3469gcc -march=pentium4 -m32 -E
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0checking100   660  100   660    0     0    106      0  0:00:06  0:00:06 --:--:--   160
  4  787k    4 34248    0     0   1082      0  0:12:25  0:00:31  0:11:54  3536yes
 19  520k   19  101k    0     0   3217      0  0:02:45  0:00:32  0:02:13  3890yes
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0yes
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0yes
 19  520k   19  101k    0     0   3070      0  0:02:53  0:00:33  0:02:20  3466checking 22  520k   22  117k    0     0   3486      0  0:02:32  0:00:34  0:01:58  7230yes
  1 7113k    1 86457    0     0   2443      0  0:49:41  0:00:35  0:49:06  3653yes
  0  154M    0 86456    0     0   2424      0 18:34:56  0:00:35 18:34:21  6822checking  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0yes
  0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0yes
  6  787k    6 51656    0     0   1368      0  0:09:49  0:00:37  0:09:12  3464yes
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
curl: (28) Operation timed out after 15000 milliseconds with 0 out of 0 bytes received
make[1]: *** [/root/julia/deps/libgit2.mk:111: /root/julia/deps/srccache/cacert-2020-01-01.pem] Error 28
make[1]: *** Waiting for unfinished jobs....
  6  787k    6 51656    0     0   1332      0  0:10:05  0:00:38  0:09:27  3462yes
  1 7113k    1  101k    0     0   2619      0  0:46:21  0:00:39  0:45:42  3322yes
checking for objdir... .libs
 26  520k   26  135k    0     0   3393      0  0:02:37  0:00:40  0:01:57  3232checking  0  154M    0  101k    0     0   2491      0 18:04:57  0:00:41 18:04:16  3469no
checking for gcc -march=pentium4 -m32 option to produce PIC... -fPIC -DPIC
  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0yes
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0no
checking if gcc -march=pentium4 -m32 supports -c -o file.o... yes
checking if gcc -march=pentium4 -m32 supports -c -o file.o... (cached) yes
checking whether the gcc -march=pentium4 -m32 linker (ld) supports shared libraries... yes
 26  520k   26  135k    0     0   3160      0  0:02:48  0:00:43  0:02:05   208no
  0  781k    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
  0  781k    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0yes
 29  520k   29  152k    0     0   3328      0  0:02:40  0:00:46  0:01:54  3094no
 29  520k   29  152k    0     0   3259      0  0:02:43  0:00:47  0:01:56  3074no
  0  781k    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0no
 29  520k   29  152k    0     0   3150      0  0:02:49  0:00:49  0:02:00  3422yes
 29  520k   29  152k    0     0   3078      0  0:02:53  0:00:50  0:02:03     0yes
  0  154M    0  118k    0     0   2344      0 19:13:00  0:00:51 19:12:09     0no
  4  781k    4 34364    0     0   1205      0  0:11:04  0:00:28  0:10:36  7154no
checking for special C compiler options needed for large files... no
  0  154M    0  118k    0     0   2267      0 19:52:09  0:00:53 19:51:16     0no
 29  520k   29  152k    0     0   2894      0  0:03:04  0:00:53  0:02:11     0no
checking sys/ahafs_evProds.h presence... no
checking for sys/ahafs_evProds.h... no
 15  787k   15  118k    0     0   2212      0  0:06:04  0:00:54  0:05:10  3194checking that generated files are newer than configure... done
configure: creating ./config.status
  2 7113k    2  152k    0     0   2751      0  0:44:07  0:00:56  0:43:11  3466config.status: creating Makefile
 17  787k   17  135k    0     0   2214      0  0:06:04  0:01:02  0:05:02  3478config.status: creating libuv.pc
  2 7113k    2  168k    0     0   2749      0  0:44:09  0:01:02  0:43:07  3282config.status: linking /root/julia/deps/srccache/libuv-35b1504507a7a4168caae3d78db54d1121b121e1/test/fixtures/empty_file to test/fixtures/empty_file
config.status: linking /root/julia/deps/srccache/libuv-35b1504507a7a4168caae3d78db54d1121b121e1/test/fixtures/load_error.node to test/fixtures/load_error.node
config.status: executing depfiles commands
 10  781k   10 86588    0     0   1955      0  0:06:49  0:00:44  0:06:05  3009config.status: executing libtool commands
 4 78 1  7 8572k0 k    4 78 1  3 7432k4 k      0  0        0  0    2 527922 5         1   8 4     502 01k7 : 43 :8346    04:4012k: 3 0   107 : 4 1 : 006     33405068      0100  520k  100  520k    0     0   2979      0  0:02:58  0:02:58 --:--:--  7093
  05 7 71k5 4 M    0    0     500 9 k  3 6 1 00          0  0   0: 0237:7471     0 : 0100  781k  100  781k    0     0   3900      0  0:03:25  0:03:25 --:--:--  7466
0  1942: 5 17:8379k    0 :9024 :1 27 301k4 : 47 : 207     3 7 200   2964      0  0:04:100  787k  100  787k    0     0   3098      0  0:04:20  0:04:20 --:--:--  6284
60 1770   7113 k     0  7 07 :2590:4089k    0 : 103 :4 0     07 : 1 56:32091    3 2 6 13 k  3    9145 4M6 7 48 k  3   5 905 7 k       00      6 8 406      6 0 4 30     0 :     9650 4751 1 3 k      950   6778:22k7 : 0 5  0  0 : 16:54    70: 1 0 :61814 6   64 100 7113k  100 7113k    0     0   6939      0  0:17:29  0:17:29 --:--:-- 10041
100  154M  100  154M    0     0  14366      0  3:08:07  3:08:07 --:--:-- 16918
make: *** [Makefile:60: julia-deps] Error 2

**Comment by yuyichao** [comment]
Yes the error message is still pretty clearly about network issue. Since the download is using `curl` and the error message is pretty clear (apart from the usual caveat from parallel make) I don't think there's anything we can do about it.

If you are building from a git checkout, then network connection is a requirement. If you are downloading tarball and want no-network build, it's a dup of https://github.com/JuliaLang/julia/issues/36604. You probably should also avoid using root.

**Comment by 62f** [comment]
No. Don’t presume that since I used the same attempt as #36604 that it is the same issue.
1) I got no message about missing curl, etc.
2) My error: is listed as 2, not 1.
3) I’m not using the same bash, did not get an error because of “—“. My version of bash as you can deduce is 5.0, not ‘4.4-p23’.
4) I have not seen “ Make.inc:653: *** "please install either GNU tar or bsdtar".  Stop.”
5) My ‘which’ binary works fine.
6) If the cause of network connectivity loss is from “not using a version which is ‘packaged”, then why does that solution not close the bug, and why are no steps listed to perform such a solution? If they do not exist, which would be one reason for leaving THAT issue open, then why was THIS issue closed instead? Yet if such steps DO exist and is relevant, then why was issue #36604 left open, unless those steps are actually unrelated to the problem I referenced in my title- in which case the irrelevant response from the other bug should now be removed?

**Comment by yuyichao** [comment]
I did not presume it's the same issue. I told you it's a dup under certain condition.

Also, none of the observation from 1 to 5 or the title of this issue has any sigificance in determining whether the two issues are the same.

> If the cause of network connectivity loss is from “not using a version which is ‘packaged”

No, the reason you see the error you have is because you have a broken network (as far as building julia is concerned) and that's not something julia can fix for you and that's why this issue is closed. It's not about julia at all. Please actually read the error messages you have, e.g.

> curl: (28) Operation timed out after 15002 milliseconds with 0 out of 0 bytes received

I also already did that part for you and told you that you have a network problem.

-----

I mentioned https://github.com/JuliaLang/julia/issues/36604 only for the very minimal chance that you are running a special build environment without network access. Otherwise it's not a solution for you. That issue, unlike this one is actually about julia and is left open as a doc issue.

Please ask further questions on http://discourse.julialang.org/ .

**Comment by 62f** [comment]
Yes, @ post 1, I was using the only remaining solution from #36604 which is:
USE_BINARYBUILDER=0
^  already trying to fix this issue in post 1.
For post 2, I removed it from the command line and placed it in Make.inc, which to my shock and horror, produces a 3x larger download; yes indeed, I WILL be taking that up with the people  at discourse.julialang.org
* gcc/cc/clang/ld always errors with “cannot create binary” without sudo, or what you called “root”; so if I ever do get as far as using make install, that one command shall NOT be sudo.

**Comment by 62f** [comment]
> how can curl even hang when it behaves so impatiently in times of unresponsiveness?: [JuliaLang/julia#37475 (comment)](https://github.com/JuliaLang/julia/issues/37475#issue-696104021)

That's unrelated. It looks like the transfer went below a minimum speed limit that was set, and probably some other timeouts were set as well.

_Originally posted by @jay in https://github.com/curl/curl/issues/5780#issuecomment-691388671_

It seems to me that the julia repository is not configured to work reliably with people who use 125Kb/s metered connections. Plus I don’t understand why curl was prevented from failing over to wget.

**Comment by StefanKarpinski** [comment]
We don't configure this. Dependencies are hosted by whatever projects are being downloaded. If you can't download dependencies, then you'll need to figure out some other way of acquiring them. If your connection is metered, I would suggest not using `make -j8` since that will try to download eight dependencies at a time, which will cause contention on your limited bandwidth connection.

**Comment by 62f** [comment]
Eureka, “-deps” is julia-shorthand for ‘dependencies’! That’s the clue I was missing. I would’ve expected to see an apostrophe or the standard period at the end of an abbreviation. I’m now well-fooled once; shame-on-you.

**Comment by StefanKarpinski** [comment]
Yes, as spelled out in the [README](https://github.com/JuliaLang/julia/blob/master/README.md#source-code-organization) for the project:

| Directory         | Contents                                                           |
| -                 | -                                                                  |
| `base/`           | source code for the Base module (part of Julia's standard library) |
| `stdlib/`         | source code for other standard library packages                    |
| `contrib/`        | editor support for Julia source, miscellaneous scripts             |
| `deps/`           | external dependencies                                              |
| `doc/src/manual/` | source for the user manual                                         |
| `doc/build/`      | detailed notes for building Julia                                  |
| `src/`            | source for Julia language core                                     |
| `test/`           | test suites                                                        |
| `ui/`             | source for various front ends                                      |
| `usr/`            | binaries and shared libraries loaded by Julia's standard libraries |
