### ISSUE TITLE
cumsum ERROR: LoadError: UndefKeywordError: keyword argument dims not assigned

### ISSUE THREAD

**Issue by jobdiogenes** [JuliaLang/julia#37500]
in a function while call cumsum over array:

 X = P[:]
 X = X / colsum(X)
 C = cumsum(X)

cumsum ERROR: LoadError: UndefKeywordError: keyword argument dims not assigned

**Comment by martinholters** [comment]
`cumsum` only supports summing along one dimension which must be explicitly given with the `dims` keyword, e.g. `cumsum(X, dims=1)`. (There is an open issue somewhere about supporting summing along multiple dimensions; then a default of summing along all dimensions could be considered.) One-dimensional inputs are the exception, where `dims=1` is quietly assumed. So unless `X` is one-dimensional here (which is hard to guess from your post), this is not a bug.

**Comment by jobdiogenes** [comment]
Yes its a matrix. Its bizarre support only one dimension and has dims parameter.
Well, I need to make my own cumsum. 

Thanks
