### ISSUE TITLE
x, y = 1, 2, 3 does not fail

### ISSUE THREAD

**Issue by twolodzko** [JuliaLang/julia#37502]
In Julia 1.5.1 (and earlier) the following code does not fail with error

```julia
julia> x, y = 1, 2, 3
(1, 2, 3)
julia> x, y
(1, 2)
```

I would expect this to fail, so that it prevents me from writing buggy code. Silently dropping values in assignments can lead to some ugly and hard to trace bugs.

**Comment by thofma** [comment]
Dup of https://github.com/JuliaLang/julia/issues/37132
