### ISSUE TITLE
Putting `precompile` inside a version check eliminates the benefits

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#37509]
On 1.6, if you add this diff to [Gaston.jl](https://github.com/mbaz/Gaston.jl):
```diff
diff --git a/src/Gaston.jl b/src/Gaston.jl
index 2731d24..c7ccb7b 100644
--- a/src/Gaston.jl
+++ b/src/Gaston.jl
@@ -91,4 +91,7 @@ function __init__()
     return nothing
 end
 
+@assert precompile(plot, (UnitRange{Int},))
+@assert precompile(display, (Figure,))
+
 end
```
then you shave about 0.4s off TTFP (note `juliamns` is an alias for `julia-master --startup-file=no`):
```julia
tim@diva:~/.julia/dev/Gaston$ juliamns -q -e 'using Gaston'
tim@diva:~/.julia/dev/Gaston$ juliamns -q
julia> @time (using Gaston; display(plot(1:10)))
  1.617487 seconds (3.32 M allocations: 230.368 MiB, 2.88% gc time)

julia> 
tim@diva:~/.julia/dev/Gaston$ git stash
Saved working directory and index state WIP on master: eed6704 Update stable documentation link
tim@diva:~/.julia/dev/Gaston$ juliamns -q -e 'using Gaston'
tim@diva:~/.julia/dev/Gaston$ juliamns -q
julia> @time (using Gaston; display(plot(1:10)))
  2.123158 seconds (6.28 M allocations: 399.833 MiB, 4.39% gc time)
```

But now put those `precompile` statements inside a conditional (to circumvent #29859):
```diff
diff --git a/src/Gaston.jl b/src/Gaston.jl
index 2731d24..457a463 100644
--- a/src/Gaston.jl
+++ b/src/Gaston.jl
@@ -91,4 +91,9 @@ function __init__()
     return nothing
 end
 
+if VERSION >= v"1.4.2"
+    @assert precompile(plot, (UnitRange{Int},))
+    @assert precompile(display, (Figure,))
+end
+
 end
```
and you get no benefit:
```julia
tim@diva:~/.julia/dev/Gaston$ juliamns -q -e 'using Gaston'
tim@diva:~/.julia/dev/Gaston$ juliamns -q
julia> @time (using Gaston; display(plot(1:10)))
  2.126315 seconds (6.28 M allocations: 399.802 MiB, 4.27% gc time)

julia> VERSION >= v"1.4.2"
true
```

**Comment by timholy** [comment]
And it really seems to be the version-check: this diff
```diff
diff --git a/src/Gaston.jl b/src/Gaston.jl
index 2731d24..4dc30fe 100644
--- a/src/Gaston.jl
+++ b/src/Gaston.jl
@@ -91,4 +91,12 @@ function __init__()
     return nothing
 end
 
+function _precompile_()
+    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
+    # VERSION >= v"1.4.2" || return nothing
+    @assert precompile(plot, (UnitRange{Int},))
+    @assert precompile(display, (Figure,))
+end
+_precompile_()
+
 end
```
works fine until you uncomment the VERSION check. It fails to deliver a benefit even if you put it in `@static`.

**Comment by timholy** [comment]
CC @daschw

**Comment by KristofferC** [comment]
While precomping, `VERSION` is `v"1.0.2"` for me... Wat?

**Comment by timholy** [comment]
:open_mouth:  I get the same version.

**Comment by timholy** [comment]
Probably explains some of https://github.com/JuliaPlots/Plots.jl/issues/2838#issuecomment-683279027

See https://github.com/JuliaPlots/Plots.jl/blob/76429cde7af1111e190c43c4720cade519257be8/src/precompile_includer.jl

**Comment by KristofferC** [comment]
It is set in the top of the file!!!!

https://github.com/mbaz/Gaston.jl/blob/eed6704ac5faefb5e178aa7d0fa4376705a7e11e/src/Gaston.jl#L20

**Comment by timholy** [comment]
Oh my god that is funny...took me like a minute to stop laughing. How could I not have thought to check that?

**Comment by KristofferC** [comment]
I would be lying if I said I didn't re-build julia a couple of times with various `@show VERSION` in `version.jl`, grepping through the julia source code after `1.0.2` etc...

**Comment by mbaz** [comment]
LOL! Seriously, sorry for causing such confusion guys! I'll make sure to change that variable name in the next release.

**Comment by yuyichao** [comment]
That is a totally reasonable variable name to use as long as it's not exported. You just need to use `Base.VERSION` within your package.

**Comment by KristofferC** [comment]
Yes, I think we all know. But apparently it is quite easy to mess up while doing so.

**Comment by yuyichao** [comment]
I'm just recommand agains breaking the package API because of this.

**Comment by timholy** [comment]
Either way, no worries @mbaz: as of today, 1.0.2 is my new favorite number!

**Comment by aminya** [comment]
I used `@static` checks in SnoopCompileBot. That should be different.

**Comment by KristofferC** [comment]
No, it was just a namespace problem.
