### ISSUE TITLE
Regression in @sprintf

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#37507]
Version 1.5
```
using Printf
@sprintf("%d", 25.5)
"26"
```

Version 1.6
```
using Printf
@sprintf("%d", 25.5)
"25"
```

```
versioninfo()
Julia Version 1.6.0-DEV.882
Commit c7b17fe3a6 (2020-09-09 22:41 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by DilumAluthge** [comment]
@quinnj ^

**Comment by quinnj** [comment]
Fix to use `round` instead of `trunc`: https://github.com/JuliaLang/julia/pull/37512. Note that this is undefined in C, so I'd be a little worried relying on the behavior in julia. As @fredrikekre mentioned, I think the better format string is `"%.0f"`.

**Comment by joa-quim** [comment]
Well, yes ``".0f"`` is more appropriate, but this came out from a test that failed in 1.6

**Comment by yuyichao** [comment]
> Note that this is undefined in C, so I'd be a little worried relying on the behavior in julia.

Undefined behavior in C has little significance here. It has to be undefined in C because how vararg arguments works in C. Strongly typed C++ equivalent and other strongly typed languages (python, matlab) all provide guaranteed behavior.

**Comment by yuyichao** [comment]
Yes, they don't necessarily have the same behavior and for that the more important thing is backward compatibility for ourselves. C and C++ also does truncation by default for floating point to integer conversion. MATLAB seems to ignore the format specifier and simply print a floating point number instead... Whatever the behavior is, it is well defined and not undefined...

**Comment by joa-quim** [comment]
BUT
v1.5
```
@sprintf("%.0f", 76.5)
"77"
```

v1.6
```
@sprintf("%.0f", 76.5)
"76"
```

**Comment by quinnj** [comment]
I think we're just running into standard floating point precision here:
```julia
julia> round(76.5)
76.0
```

**Comment by joa-quim** [comment]
This is v1.5  
```
julia> @sprintf("%.0f", 76.5)
"77"

julia> round(76.5)
76.0
```

This is an older v1.6 in a Linux machine (same result)
```
julia> @sprintf("%.0f", 76.5)
"77"

julia> round(76.5)
76.0
```

```
julia> versioninfo()
Julia Version 1.6.0-DEV.465
Commit 77487611fd (2020-07-15 09:47 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

**Comment by quinnj** [comment]
So this comes down to a difference in the Grisu vs. Ryu floating point printing algorithms:

Grisu
```
(remainders of exactly .5 round upwards)
```

while Ryu does:
```
Round to nearest, ties to even – rounds to the nearest value; if the number falls midway, it is rounded to the nearest value with an even least significant digit; this is the default for binary floating point and the recommended default for decimal.
```

I don't personally have a good sense for whether one rounding mode is more expected or standard than the other: @simonbyrne ?

**Comment by joa-quim** [comment]
I updated my nightly build and it stil
```
julia> @sprintf("%.0f", 76.5)
"76"
```
while v1.5
```
julia> @sprintf("%.0f", 76.5)
"77"
```

I agree that it's more logical to follow the result of ``round()`` but this represents a backward compat breaking.

**Comment by quinnj** [comment]
> but this represents a backward compat breaking.

Yeah......I guess. I'm just not sure what level of "breaking" this really is; i.e. I'm pretty sure we don't have a guarantee that the default rounding mode of printf formatting won't ever change. The only reason I hesitate to support the previous default rounding mode is that it seems like a non-trivial amount of work for uncertain amount of value.

**Comment by simonbyrne** [comment]
> Maybe we should enhance the Ryu printing code to check the rounding mode and adjust accordingly? @simonbyrne, thoughts?

Probably not worth it at the moment: running julia in a non-default rounding mode breaks a lot of things, also `RoundNearestTiesUp` isn't a hardware-supported rounding mode.

I think the newer behaviour is correct, and it matches C spec which states that the results should be correctly rounded. While it is breaking, I would class it more as a bug fix.

**Comment by StefanKarpinski** [comment]
We can consider this to be a "minor change": technically breaking but acceptable in a minor release.
