### ISSUE TITLE
[docs] A bit oversimplified statement about performance loss in abstract types

### ISSUE THREAD

**Issue by racinmat** [JuliaLang/julia#37513]
https://docs.julialang.org/en/v1/manual/types/#Type-Declarations states
```
An important point to note is that there is no loss in performance if the programmer relies on a function whose arguments are abstract types, because it is recompiled for each tuple of argument concrete types with which it is invoked. (There may be a performance issue, however, in the case of function arguments that are containers of abstract types; see Performance Tips.)
```
but for the first time, when functions are compiled, there is a performance loss, which is why you should run the code at least once before benchmarking, right?

**Comment by yuyichao** [comment]
Compilation time has nothing to do with abstract types.

**Comment by racinmat** [comment]
For concrete types it can be precompiled, but for abstract types not.

**Comment by yuyichao** [comment]
It can be precompiled for when the type in the argument is specified to be abstract type.

> Thus if I'll have program with only specific types, and program with abstract types, the one with abstract types will take some small time to compile even after precompilation.

No. First of all, you cannot have a program with abstract types. Objects always have concrete types. If you just mean that the types in the argument list then no,

```julia
f(a, b) = ...
precompile(f, (Int,Int))
```

and

```julia
f(a::Int, b::Int) = ...
precompile(f, (Int,Int))
```

should have exactly the same performance regarding precompilation. Also it has nothing to do with this section of the document and should not be mentioned here.

**Comment by racinmat** [comment]
Oh, I see.
