### ISSUE TITLE
Add a few Julian examples in the manual

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#37527]
It would be awesome to be able to include some examples in the docs of code that works and then corresponding "Julian" code that takes full advantage of Julia.

(In line with the idea of writing pythonic code) 

Cc @alanedelman

**Comment by JeffBezanson** [comment]
The question is, is Alan the most Julian [Edelman](https://en.wikipedia.org/wiki/Julian_Edelman)?

**Comment by KristofferC** [comment]
I don't really understand what this means. Like random pieces of runnable Julia code that are well written? Feels a bit like https://rosettacode.org/wiki/Category:Julia.

**Comment by bramtayl** [comment]
If they don't already exist, I think some examples illustrating alternatives to common patterns in other languages that are not so useful in Julia (R-style vectorization, object oriented programming patterns) might be nice.

**Comment by logankilpatrick** [comment]
@KristofferC the idea is to have some comparative examples like: "Here's how you might write a for loop but this is the Julian way to do it that takes full advantage of the languages features" (that might be a bad example but that's the idea).

**Comment by alanedelman** [comment]
Students in our class have reported that when they write code, they feel there are a few ways they could write them, and there is no guidance as to best practices.  Think about learning to write English -- students learn from experiencing good examples.

**Comment by alanedelman** [comment]
and by the way, people ask me all the time if I'm related to Julian Edelman
![image](https://user-images.githubusercontent.com/862530/93594234-7b20ca80-f983-11ea-924f-ae4b29ff233c.png)

**Comment by ViralBShah** [comment]
This feels like a very open ended issue and unclear what actually needs doing. It would be best to close this and just open specific PRs. Also, this sort of thing may better belong outside the Julia manual.

**Comment by logankilpatrick** [comment]
Sure, if you think that's best.
