### ISSUE TITLE
julia crashes  when “ using Plots ” in REPL  in Juno IDE

### ISSUE THREAD

**Issue by prehonor** [JuliaLang/julia#37529]
Press Enter to start a new session.
Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

signal (11): Segmentation fault
in expression starting at /home/prehonor/.julia/packages/PlotThemes/4DCOG/src/juno_smart.jl:3
jl_compile_linfo at /usr/lib/libjulia.so.1 (unknown line)
_ZL11emit_invokeR12jl_codectx_tP9jl_expr_tP11_jl_value_t.isra.0 at /usr/lib/libjulia.so.1 (unknown line)
_ZL9emit_exprR12jl_codectx_tP11_jl_value_tl at /usr/lib/libjulia.so.1 (unknown line)
_ZL18emit_ssaval_assignR12jl_codectx_tlP11_jl_value_t at /usr/lib/libjulia.so.1 (unknown line)
_ZL13emit_functionP21_jl_method_instance_tP15_jl_code_info_tmP20_jl_llvm_functions_tPK13jl_cgparams_t.isra.0 at /usr/lib/libjulia.so.1 (unknown line)
jl_compile_linfo at /usr/lib/libjulia.so.1 (unknown line)
_ZL11emit_invokeR12jl_codectx_tP9jl_expr_tP11_jl_value_t.isra.0 at /usr/lib/libjulia.so.1 (unknown line)
_ZL9emit_exprR12jl_codectx_tP11_jl_value_tl at /usr/lib/libjulia.so.1 (unknown line)
_ZL18emit_ssaval_assignR12jl_codectx_tlP11_jl_value_t at /usr/lib/libjulia.so.1 (unknown line)
_ZL13emit_functionP21_jl_method_instance_tP15_jl_code_info_tmP20_jl_llvm_functions_tPK13jl_cgparams_t.isra.0 at /usr/lib/libjulia.so.1 (unknown line)
jl_compile_linfo at /usr/lib/libjulia.so.1 (unknown line)
jl_compile_method_internal at /usr/lib/libjulia.so.1 (unknown line)
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_invoke at /usr/lib/libjulia.so.1 (unknown line)
#distinguishable_colors at ./none:0
unknown function (ip: 0x7fa85bf4077e)
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
#expand_palette#3 at /home/prehonor/.julia/packages/PlotThemes/4DCOG/src/PlotThemes.jl:14
#expand_palette at ./none:0
unknown function (ip: 0x7fa85bf3e95d)
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
do_call at /usr/lib/libjulia.so.1 (unknown line)
eval_value at /usr/lib/libjulia.so.1 (unknown line)
eval_body at /usr/lib/libjulia.so.1 (unknown line)
jl_interpret_toplevel_thunk_callback at /usr/lib/libjulia.so.1 (unknown line)
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fa85d717b6f)
unknown function (ip: 0x72)
jl_interpret_toplevel_thunk at /usr/lib/libjulia.so.1 (unknown line)
jl_toplevel_eval_flex at /usr/lib/libjulia.so.1 (unknown line)
jl_parse_eval_all at /usr/lib/libjulia.so.1 (unknown line)
jl_load at /usr/lib/libjulia.so.1 (unknown line)
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29 [inlined]
include at /home/prehonor/.julia/packages/PlotThemes/4DCOG/src/PlotThemes.jl:3
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
do_call at /usr/lib/libjulia.so.1 (unknown line)
eval_value at /usr/lib/libjulia.so.1 (unknown line)
eval_body at /usr/lib/libjulia.so.1 (unknown line)
jl_interpret_toplevel_thunk_callback at /usr/lib/libjulia.so.1 (unknown line)
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fa882c8cc3f)
unknown function (ip: 0x7)
jl_interpret_toplevel_thunk at /usr/lib/libjulia.so.1 (unknown line)
jl_toplevel_eval_flex at /usr/lib/libjulia.so.1 (unknown line)
jl_toplevel_eval_in at /usr/lib/libjulia.so.1 (unknown line)
eval at ./boot.jl:328 [inlined]
eval at /home/prehonor/.julia/packages/PlotThemes/4DCOG/src/PlotThemes.jl:3 [inlined]
#16 at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:85
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
err at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:42
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_invoke at /usr/lib/libjulia.so.1 (unknown line)
#15 at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:84
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
withpath at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:32
#14 at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:83
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
listenpkg at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:15
macro expansion at /home/prehonor/.julia/packages/Requires/QnsKK/src/require.jl:81 [inlined]
__init__ at /home/prehonor/.julia/packages/PlotThemes/4DCOG/src/PlotThemes.jl:62
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
jl_module_run_initializer at /usr/lib/libjulia.so.1 (unknown line)
jl_init_restored_modules at /usr/lib/libjulia.so.1 (unknown line)
_include_from_serialized at ./loading.jl:633
_require_search_from_serialized at ./loading.jl:713
_tryrequire_from_serialized at ./loading.jl:648
_require_search_from_serialized at ./loading.jl:702
_require at ./loading.jl:937
require at ./loading.jl:858
require at ./loading.jl:853
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
eval_import_path.isra.0.constprop.0 at /usr/lib/libjulia.so.1 (unknown line)
jl_toplevel_eval_flex at /usr/lib/libjulia.so.1 (unknown line)
jl_parse_eval_all at /usr/lib/libjulia.so.1 (unknown line)
include_string at /nix/store/dka6d11qx64h5qwa26mjkyy5v6mjgiks-julia-1.1.1/lib/julia/sys.so (unknown line)
include_string at /home/prehonor/.julia/packages/CodeTools/VsjEq/src/eval.jl:30
unknown function (ip: 0x7fa876fe04d3)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
#202 at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:119
withpath at /home/prehonor/.julia/packages/CodeTools/VsjEq/src/utils.jl:30
jl_invoke at /usr/lib/libjulia.so.1 (unknown line)
withpath at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:9 [inlined]
#201 at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:118 [inlined]
with_logstate at ./logging.jl:395
jl_invoke at /usr/lib/libjulia.so.1 (unknown line)
with_logger at ./logging.jl:491 [inlined]
#200 at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:117 [inlined]
hideprompt at /home/prehonor/.julia/packages/Atom/ZeFbA/src/repl.jl:127
macro expansion at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:116 [inlined]
eval at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:113
unknown function (ip: 0x7fa876fd016b)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
jl_f__apply at /usr/lib/libjulia.so.1 (unknown line)
jl_f__apply_latest at /usr/lib/libjulia.so.1 (unknown line)
#invokelatest#1 at /nix/store/dka6d11qx64h5qwa26mjkyy5v6mjgiks-julia-1.1.1/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
jl_f__apply at /usr/lib/libjulia.so.1 (unknown line)
invokelatest at /nix/store/dka6d11qx64h5qwa26mjkyy5v6mjgiks-julia-1.1.1/lib/julia/sys.so (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
jl_f__apply at /usr/lib/libjulia.so.1 (unknown line)
#184 at /home/prehonor/.julia/packages/Atom/ZeFbA/src/eval.jl:41
jl_fptr_trampoline at /usr/lib/libjulia.so.1 (unknown line)
jl_apply_generic at /usr/lib/libjulia.so.1 (unknown line)
start_task at /usr/lib/libjulia.so.1 (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 71245396 (Pool: 71234902; Big: 10494); GC: 139

**Comment by KristofferC** [comment]
Try with the latest release version (1.5.1). Also, make sure you are using the official version downloaded from https://julialang.org/downloads/
