### ISSUE TITLE
@printf formats 0.999 as !0.0e-1

### ISSUE THREAD

**Issue by olof3** [JuliaLang/julia#37539]
On nightly (it works fine in v1.5.1)

```julia
julia> Printf.@printf(" %.1e\n", 0.999)
!0.0e-01
```

I guess this is unintended?

If the space before `%` is removed it works.

```julia
julia> Printf.@printf("%.1e\n", 0.999)
1.0e+00
```

**Comment by quinnj** [comment]
Thanks @olof3 for reporting! Fix is up: https://github.com/JuliaLang/julia/pull/37546
