### ISSUE TITLE
Export of win32_SystemFunction036! from Random.DSFMT

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#37541]
`win32_SystemFunction036!` is exported in line https://github.com/JuliaLang/julia/blob/master/stdlib/Random/src/DSFMT.jl#L11
but it seems to me that it is undefined (tested on Win10):
```
julia> Random.DSFMT.win32_SystemFunction036!
ERROR: UndefVarError: win32_SystemFunction036! not defined
```
Should this line be removed as it is some leftover or there is some deeper reason (e.g. platform specific) for this export?

This name does not seem to be used anywhere else in the repository.

**Comment by rfourquet** [comment]
Good catch! This was my mistake to not remove the export.
