### ISSUE TITLE
Macro hygiene broken for interpolation into quoted expressions

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#37540]
MWE:
```julia
julia> macro foo()
           quote
               x = 1
               :($x)
           end
       end
@foo (macro with 1 method)

julia> @macroexpand @foo
quote
    #= REPL[40]:3 =#
    var"#58#x" = 1
    #= REPL[40]:4 =#
    x
end
```

**Comment by vtjnash** [comment]
This was intentional at the time (https://github.com/JuliaLang/julia/commit/7ec9b1857e029d4307fa0968512f828481611440#diff-c4aa3af56687ca52d73d3de5e0734726R494-R495), but I definitely didn't realize how little it would break to fix it
