### ISSUE TITLE
Its possible to use all cores or parallel cores to do some project/calculations?

### ISSUE THREAD

**Issue by leaoshark** [JuliaLang/julia#37585]
I have three different and independent task/calculation to do.

calculation 1 - x
calculation 2 - y
calculation 3 - z

How can i use all cores or do the three tasks at the same time ?

**Comment by jakobnissen** [comment]
@leaoshark Please direct usage questions to [Julia Discourse](https://discourse.julialang.org/) or [Julia Slack](http://julialang.slack.com/), where people will be happy to help you. GitHub is mostly used for bug reports and discussions about how to develop the language.
