### ISSUE TITLE
The new stacktrace printing is missing "repeated N times" info for some StackOverflows

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#37587]
On 1.5:
```julia
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
ERROR: StackOverflowError:
Stacktrace:
 [1] foo() at ./REPL[2]:1 (repeats 79984 times)
```

On master:
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.816
Commit 21ff6ee256 (2020-09-02 04:52 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
ERROR:
StackOverflowError:
Stacktrace:
 [1] foo()
   @ Main ./REPL[4]:1
```

With a real, more interesting stack, this makes it difficult to tell where the cycle is occurring!

Note that it does _sometimes_ work, as shown in this example:
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.816
Commit 21ff6ee256 (2020-09-02 04:52 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> foo() = bar()
foo (generic function with 1 method)

julia> bar() = foo()
bar (generic function with 1 method)

julia> foo()
ERROR: StackOverflowError:
Stacktrace:
     [1] foo()
       @ Main ./REPL[1]:1
     [2] bar()
       @ Main ./REPL[2]:1--- the last 2 lines are repeated 13329 more times ---
```

------

😮 And i tried pulling a later master and re-building to see if the problem is still there before filing an issue, but now it's segfaulting! 😮 
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.917
Commit a0a68a54d6 (2020-09-14 20:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
[1]    88563 segmentation fault  ~/builds/julia-1.6/julia
```
When I ran inside LLDB it somehow _didn't_ segfault, and indeed still suffers from the under-reporting of the repeated frames:
```julia
(lldb) r
Process 89582 launched: '/Users/nathandaly/builds/julia-1.6/julia' (x86_64)
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.917 (2020-09-14)
 _/ |\__'_|_|_|\__'_|  |  Commit a0a68a54d6 (0 days old master)
|__/                   |

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
ERROR: StackOverflowError:
Stacktrace:
 [1] foo()
   @ Main ./REPL[1]:1

julia> versioninfo()
Julia Version 1.6.0-DEV.917
Commit a0a68a54d6 (2020-09-14 20:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by NHDaly** [comment]
(Also, i did a make clean and git pull and rebuilt master and it's not segfaulting anymore, so i hope that was just a false alarm? Still missing the "repeated N times" info of course)
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.917
Commit a0a68a54d6 (2020-09-14 20:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
ERROR: StackOverflowError:
Stacktrace:
 [1] foo()
   @ Main ./REPL[3]:1
```

**Comment by NHDaly** [comment]
(simplified the title)

**Comment by NHDaly** [comment]
This bug is still present as of julia 1.6 alpha:
```julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1780
Commit de69b02a48* (2020-12-19 19:43 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)

julia> foo() = foo()
foo (generic function with 1 method)

julia> foo()
ERROR: StackOverflowError:
Stacktrace:
 [1] foo()
   @ Main ./REPL[2]:1
```

**Comment by NHDaly** [comment]
@c42f: I know that you've made a lot of awesome improvements to exception stack trace printing this release! :) Do you have any idea what might have broken this?

Thanks!

**Comment by NHDaly** [comment]
I've checked, and the cycle detection still worked as of 97e3fe88d7, so the breakage is somewhere between 97e3fe88d7 and a0a68a54d6.

**Comment by NHDaly** [comment]
```
$ git log --oneline 97e3fe88d7..a0a68a54d6 -- base/errorshow.jl  | wc -l
      16
```

Looks like these are the possibilities:
```
$ git log --oneline 97e3fe88d7..a0a68a54d6 -- base/errorshow.jl
```
294e5ae423 Improve inference for paths leading to `similar` (#37163)
4c027678cc support full exception stacks in Task error reporting (#37224)
6aee988223 Avoid several bad `show_default` invalidations (#37125)
81597635c4 Improve inference on some type-, Expr-, and error operations (#37086)
4c7026c434 Reduce reliance on promotion operations via container typing (#37088)
29826c2c08 Improve exception stack printing (#36606)
114e581d30 Fix Ctrl+Q for stack traces (#36344)
30b09dfd2b [WIP] include ClearStacktrace.jl in Base (#36134)
92197a71c1 Merge pull request #36166 from JuliaLang/jn/ml-matches-leaf-cache
2749582ad4 Fix more invalidations from overloading `==` (#36282)
13b07fcc57 mention methodtable Ctrl+Q trick in methodshow (#35556)
6b2ffd3913 Fix some invalidations from extending `==(::Any, ::SomeType)` (#36255)
166031c06c improve code quality
186c3bbe61 remove unnecessary newline when printing BoundsError (#36138)
c974bc65f9 no longer color the exception provided error message as red (#36024)
cb2e8c82d2 fix #34824, improve various cases of showing method signatures (#35862)

**Comment by NHDaly** [comment]
EDIT: Okay, i've tracked down the failure to #36134. That's where it was introduced 👍
See here for a before/after:
https://github.com/JuliaLang/julia/pull/36134#issuecomment-748683683

**Comment by c42f** [comment]
Great sleuthing Nathan! I can't take credit for the great aesthetic improvements, those were all @jkrumbiegel's design work.

@jkrumbiegel do you have time to look at this? I'm pretty snowed under.

**Comment by NHDaly** [comment]
@jkrumbiegel: any chance you have time to look at this? :) hopefully it's not too much work to resolve?

**Comment by NHDaly** [comment]
@c42f i've managed to track down the problem, and fixed it here:
https://github.com/JuliaLang/julia/pull/39378

it'd be great if we can also backport this into 1.6, once it's been exercised for a little while, so that stackoverflow printing isn't broken! :)
