### ISSUE TITLE
No `Revise.track` recipe for module `LibCURL`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#37619]
When attempting to run `make test-revise-Artifacts`, I found that the revise stuff is unhappy about newly-added stdlibs.  What do we need to do to fix those?

**Comment by KristofferC** [comment]
Add them to Revise I think.

**Comment by timholy** [comment]
It's already in Revise 3 and seems to work for me. (`pkg> up`)

**Comment by timholy** [comment]
Oh, wait, I looked at the comment re Artifacts and didn't notice that you were talking about LibCURL, which is even newer. Wait for https://github.com/timholy/Revise.jl/pull/534, I'll tag once that merges.
