### ISSUE TITLE
Timer should stop when the callback throws an exception?

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#3762]
```
rr = RemoteRef()
function timercb(aw, status)
    # user code throws an exception
    error("Foo")
    put(rr, :ok)
end

t = TimeoutAsyncWork(timercb)
start_timer(t, 1.0, 1.0)
fetch(rr)
stop_timer(t)
```

In the above contrived example, in case the user code throws an exception, the timer never gets cancelled. 

Suggest stopping the timer if the callback ever throws an exception.

**Comment by Keno** [comment]
We discourage using the callback interface, so I don't think we need to do anything here.

**Comment by JeffBezanson** [comment]
`start_timer` does still document a callback interface. Could we deprecate `start_timer` and `stop_timer` and tell people to `sleep` in a loop in a task instead?

**Comment by JeffBezanson** [comment]
Interestingly, I believe sleeping in a loop and interrupting the sleeping task to stop the timer has the behavior requested in this issue.
