### ISSUE TITLE
Timer objects are not being gc'ed

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#3763]
```
function timercb(aw, status)
    println("Called")
end

t = TimeoutAsyncWork(timercb)
start_timer(t, 1.0, 1.0)
t = 1
gc()
```

I think it is better to treat timer objects as any other regular objects and clean them up as soon as any reference to them from user code is lost. 

Same issue as https://github.com/JuliaLang/julia/issues/3567 I guess - just creating a new issue so that it is tracked.

**Comment by JeffBezanson** [comment]
I think this was settled by #11669. Now timers just run until you call `close` on them, end of story.
