### ISSUE TITLE
Inference fails for closure

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#37647]
James Cook of slack came up with an interesting problem of inference:
```
function foo(scale)
    output(x) = scale + x
    output(::Float64) = output("")
    return output
end

bar(x) = foo(5)(x)
baz = foo(5)
```
Here, `bar(3)` is inferred to `Any`, but `baz(3)` is correctly inferred. Is there any reason for this? Shouldn't both be inferred completely?

**Comment by KristofferC** [comment]
> Here, bar(3) is inferred to Any, but baz(3) is correctly inferred. Is there any reason for this? 

The call to `foo` is not inferred, but if you introduce a function barrier or go via global scope then that's not a problem. It's like asking why in

```
julia> f() = Any[1][1]
f (generic function with 1 method)

julia> g() = sin(f())
g (generic function with 1 method)

julia> i = f()
1

julia> sin(i)
```

the `sin` call is inferred but not the `g` call.

**Comment by vtjnash** [comment]
Duplicate of #15276

**Comment by jakobnissen** [comment]
Aha, I see. Closing.

**Comment by vtjnash** [comment]
To expand upon that, `output` is a local variable, so it is getting closure-captured to be able do the call in the second method. (this is possibly a slightly easier case, where we could introduce the function binding itself as a local variable in the function of the same name, avoiding this problem—but I've worried that might be breaking, so haven't yet attempted it)

**Comment by jwscook** [comment]
Thanks all
