### ISSUE TITLE
How is this conditional a syntax error?

### ISSUE THREAD

**Issue by alok** [JuliaLang/julia#37656]
This behavior seems odd to me:

```julia
if true 'a' else 1 end # syntax error
if true "a" else 1 end # returns "a"
if true 1 else 'a' end # returns 1
```

The backtrace is:

```
ERROR: syntax: space not allowed before "'"
Stacktrace:
 [1] top-level scope at none:1
```

**Comment by yuyichao** [comment]
the parser thought you are doing

`julia> if true'a' else 1 end`, i.e. `julia> if true' a' else 1 end`

Changing either of these cases will be breaking. Changing `if true 'a' else 1 end` shouldn't be breaking.
