### ISSUE TITLE
Segmentation fault in `uv_write_2`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#37666]
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/ApproxBayes/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/Autologistic/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/BifurcationKit/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/BundleMethod/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/CMAEvolutionStrategy/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/COSMO/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/Clustering/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/DiffEqBayes/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/DifferentialDynamicProgramming/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/DiscreteValueIteration/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/Dolo/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/DotTestSets/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/DualDecomposition/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/GCMAES/1.6.0-DEV-e476b33821.log

and more....

**Comment by vtjnash** [comment]
And https://github.com/JuliaLang/julia/issues/37665

**Comment by vtjnash** [comment]
Bug in Printf, fixed by #37810
