### ISSUE TITLE
segfault from printf

### ISSUE THREAD

**Issue by lkapelevich** [JuliaLang/julia#37665]
I'm getting segfaults from calls to `@printf` on master from inside a repository, though I haven't managed to get an example from Main.
Gist: https://gist.github.com/lkapelevich/d3ef17e4729148fcaf54608d0564e6ff
Edit: doesn't happen in v1.5.1

**Comment by mtanneau** [comment]
Same here, only happens on Julia nightly.

The smallest MWE I can get to is when a call to `@printf` happens from inside a package.

For instance, the following works
```julia
julia> using Printf
julia> @printf "Hello, world"
Hello, world
```
This also works
```julia
julia> module Foo

using Printf
foobar() = @printf "Hello, world"

end  # module

julia> Foo.foobar()
Hello, world
```

But, if I generate a package `HelloWorld`, and edit `HelloWorld.jl` as follows
```julia
module HelloWorld

using Printf

foobar() = @printf "Hello, world!"

end # module
```
then, from the REPL:
```julia
julia> import HelloWorld
julia> HelloWorld.foobar()

signal (11): Segmentation fault
in expression starting at REPL[8]:1
uv_write2 at /workspace/srcdir/libuv/src/unix/stream.c:1402
uv_write at /workspace/srcdir/libuv/src/unix/stream.c:1497
jl_uv_write at /buildworker/worker/package_linux64/build/src/jl_uv.c:471
uv_write_async at ./stream.jl:1024
uv_write at ./stream.jl:981
unsafe_write at ./stream.jl:1064
unsafe_write at ./io.jl:646 [inlined]
write at ./io.jl:669 [inlined]
format at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:729
foobar at /mnt/c/Users/mathi/Git/Tulip.jl/HelloWorld/src/HelloWorld.jl:5
unknown function (ip: 0x7f98036405ac)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:837
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:785
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:880
eval at ./boot.jl:360
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
#run_repl#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:316
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:304
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
#852 at ./client.jl:387
jfptr_YY.852_42524.clone_1 at /home/mtanneau/julia-93bbe0833b/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:672
jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:722
#invokelatest#2 at ./essentials.jl:709 [inlined]
invokelatest at ./essentials.jl:708 [inlined]
run_main_repl at ./client.jl:372
exec_options at ./client.jl:302
_start at ./client.jl:485
jfptr__start_22675.clone_1 at /home/mtanneau/julia-93bbe0833b/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:553
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:672
main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:46
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/mtanneau/julia-93bbe0833b/bin/julia (unknown line)
Allocations: 1555916 (Pool: 1555379; Big: 537); GC: 2
Segmentation fault (core dumped)
```

And yet, finally, this works (with the **same** file `HelloWorld.jl`):
```julia
$ julia
julia> include("HelloWorld")
julia> HelloWorld.foobar()
Hello, world
```
Note that, contrary to the above case, here the module `HelloWorld` is loaded via an `include`, not a package `import`.
This seems to be the difference as to when things break.

**Comment by phykos** [comment]
> Same here, only happens on Julia nightly.
> 
> The smallest MWE I can get to is when a call to `@printf` happens from inside a package.
> 
> For instance, the following works
> ```julia
> julia> using Printf
> julia> @printf "Hello, world"
> Hello, world
> ```
> This also works
> ```julia
> julia> module Foo
> 
> using Printf
> foobar() = @printf "Hello, world"
> 
> end  # module
> 
> julia> Foo.foobar()
> Hello, world
> ```
> 
> But, if I generate a package `HelloWorld`, and edit `HelloWorld.jl` as follows
> ```julia
> module HelloWorld
> 
> using Printf
> 
> foobar() = @printf "Hello, world!"
> 
> end # module
> ```
> then, from the REPL:
> ```julia
> julia> import HelloWorld
> julia> HelloWorld.foobar()
> 
> signal (11): Segmentation fault
> in expression starting at REPL[8]:1
> uv_write2 at /workspace/srcdir/libuv/src/unix/stream.c:1402
> uv_write at /workspace/srcdir/libuv/src/unix/stream.c:1497
> jl_uv_write at /buildworker/worker/package_linux64/build/src/jl_uv.c:471
> uv_write_async at ./stream.jl:1024
> uv_write at ./stream.jl:981
> unsafe_write at ./stream.jl:1064
> unsafe_write at ./io.jl:646 [inlined]
> write at ./io.jl:669 [inlined]
> format at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Printf/src/Printf.jl:729
> foobar at /mnt/c/Users/mathi/Git/Tulip.jl/HelloWorld/src/HelloWorld.jl:5
> unknown function (ip: 0x7f98036405ac)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
> do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
> eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
> eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
> eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
> jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
> jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:837
> jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:785
> jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:880
> eval at ./boot.jl:360
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
> eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
> repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
> start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
> #run_repl#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:316
> run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:304
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
> #852 at ./client.jl:387
> jfptr_YY.852_42524.clone_1 at /home/mtanneau/julia-93bbe0833b/lib/julia/sys.so (unknown line)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
> do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:672
> jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:722
> #invokelatest#2 at ./essentials.jl:709 [inlined]
> invokelatest at ./essentials.jl:708 [inlined]
> run_main_repl at ./client.jl:372
> exec_options at ./client.jl:302
> _start at ./client.jl:485
> jfptr__start_22675.clone_1 at /home/mtanneau/julia-93bbe0833b/lib/julia/sys.so (unknown line)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2192 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2374
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1687 [inlined]
> true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:553
> repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:672
> main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:46
> __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
> _start at /home/mtanneau/julia-93bbe0833b/bin/julia (unknown line)
> Allocations: 1555916 (Pool: 1555379; Big: 537); GC: 2
> Segmentation fault (core dumped)
> ```
> 
> And yet, finally, this works (with the **same** file `HelloWorld.jl`):
> ```julia
> $ julia
> julia> include("HelloWorld")
> julia> HelloWorld.foobar()
> Hello, world
> ```
> Note that, contrary to the above case, here the module `HelloWorld` is loaded via an `include`, not a package `import`.
> This seems to be the difference as to when things break.

From the trace I'd say it's something which has to do with libuv, but the second snippet runs fine, so I don't have an idea...

**Comment by quinnj** [comment]
Sorry about the non-response here; I think I had typed up a response, but it was on a wonky computer and didn't get posted. There doesn't seem to be anything Printf-specific here on the Julia side; there's something weird because we have the definition:
```julia
macro printf(io_or_fmt, args...)
    if io_or_fmt isa String
        io = stdout
        fmt = Format(io_or_fmt)
        return esc(:($Printf.format($io, $fmt, $(args...))))
    else
        io = io_or_fmt
        isempty(args) && throw(ArgumentError("must provide required format string"))
        fmt = Format(args[1])
        return esc(:($Printf.format($io, $fmt, $(Base.tail(args)...))))
    end
end
```
and it's the `io = stdout` part that is somehow getting messed up in precompilation. Is there a better way we should write/express that the default should be `stdout` here? Should this just work? cc: @vtjnash

**Comment by KristofferC** [comment]
Can you really interpolate the io object like that when it is stdout? What if the stdout binding changes?

**Comment by quinnj** [comment]
I mean, it seems to work fine when everything is compiled into the sysimg? That's certainly one of my questions is whether this is actually a no-no that happens to work sometimes

**Comment by quinnj** [comment]
Oh, actually maybe it wouldn't work in stdlibs even; i.e. I'm not sure we're actually _precompiling_ any `Printf.@printf` statements, so it seems like we could easily have the same problem. Let me see if there's a better way to rearrange the code.

**Comment by quinnj** [comment]
Ok, fix is up: https://github.com/JuliaLang/julia/pull/37810
