### ISSUE TITLE
Block comments between code are parsed to unexpected expression

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#37664]
```
julia> a = 3
3

julia> a a
ERROR: syntax: extra token "a" after end of expression
Stacktrace:
 [1] top-level scope at none:1

julia> a#==#a
9

julia> Meta.parse("a#==#a")
:(a * a)
```

should probably be parsed as `:(a a)` instead

**Comment by belamenso** [comment]
Hi, I am new to Julia development and would be interested in fixing this issue as my first contribution.
If I understand correctly, any syntax "A#= multi-line comment =#B" should parse as "A B", that is any multi-line comment is equivalent to a single space, like for example [in C++](https://en.cppreference.com/w/c/comment)?
