### ISSUE TITLE
MbedTLS error

### ISSUE THREAD

**Issue by Piyush-97** [JuliaLang/julia#37676]
![16006305190243275238218087667760](https://user-images.githubusercontent.com/63279364/93720439-a3d4da00-fba6-11ea-86c6-ad3cdf738a8d.jpg)

**Comment by Piyush-97** [comment]
How to solve this problem

**Comment by johnnychen94** [comment]
This is a Windows 7 TLS issue, please follow the instructions in https://julialang.org/downloads/platform/#windows_7_windows_server_2012_installation_notes

For the record, it is better to ask such kind of questions in [discourse](https://discourse.julialang.org/). The issue board in julialang/julia is preserved to track bugs and features, which is mostly for developers and not for users.
