### ISSUE TITLE
Segmentation fault during deserialize_value_array

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#37672]
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/SemanticModels/1.6.0-DEV-e476b33821.log
- https://github.com/JuliaCI/NanosoldierReports/blob/b21cde0b76dd9a02959c518877b8f7dc77f57e8e/pkgeval/by_hash/ace08d8/logs/QBase/1.6.0-DEV-e476b33821.log

**Comment by vtjnash** [comment]
Should be https://github.com/JuliaLang/julia/pull/37594

**Comment by JeffBezanson** [comment]
Presumed fixed by #37594.
