### ISSUE TITLE
`collect(graphemes("🤦🏼‍♂️"))` results in ERROR: ArgumentError: destination has fewer elements than required

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/julia#37680]
I believe there's an issue with the implementation of `iterate` on the result of `graphemes("🤦🏼‍♂️")`.

The following works as expected:

```julia
julia> s = "🤦🏼‍♂️"
"🤦🏼\u200d♂️"

julia> length(s) == 5
true

julia> [s[i] for i in eachindex(s)]
5-element Array{Char,1}:
 '🤦': Unicode U+1F926 (category So: Symbol, other)
 '🏼': Unicode U+1F3FC (category Sk: Symbol, modifier)
 '\u200d': Unicode U+200D (category Cf: Other, format)
 '♂': Unicode U+2642 (category So: Symbol, other)
 '️': Unicode U+FE0F (category Mn: Mark, nonspacing)

julia> using Unicode

julia> length(graphemes(s)) == 1
true
```

However, this is the error I get when I try to collect the result of the Iterator in the latest stable release of Julia (v1.5.1).

```julia
julia> collect(graphemes(s))
ERROR: ArgumentError: destination has fewer elements than required
Stacktrace:
 [1] copyto!(::Array{SubString{String},1}, ::Base.Unicode.GraphemeIterator{String}) at ./abstractarray.jl:734
 [2] _collect at ./array.jl:630 [inlined]
 [3] collect(::Base.Unicode.GraphemeIterator{String}) at ./array.jl:624
 [4] top-level scope at REPL[5]:1
```

The implementation of [`length`](https://github.com/JuliaLang/julia/blob/f13e11c130a59a5d69d17d1e205b13c0564d89d7/base/strings/unicode.jl#L663-L672
) appears to be correct, but I think there's a bug in the implementation of [`iterate`](https://github.com/JuliaLang/julia/blob/f13e11c130a59a5d69d17d1e205b13c0564d89d7/base/strings/unicode.jl#L674-L690):

```julia
julia> for (i, c) in enumerate(graphemes(s))
       println(i, " ", c)
       end
1 🤦🏼‍
2 ♂️
```

I believe the correct behavior in this case is to return just the first element. `iterate` seems to be returning the Symbol `♂` as well.

**Comment by simeonschaub** [comment]
I can reproduce this on master.

**Comment by simeonschaub** [comment]
I think the problem is that the `state` passed to `isgraphemebreak!` needs to be initialized on the first iteration with the null character. The following fixes the issue for me. Is this the correct way to do it?
```julia
diff --git a/base/strings/unicode.jl b/base/strings/unicode.jl
index 235f85184d..029787b3c1 100644
--- a/base/strings/unicode.jl
+++ b/base/strings/unicode.jl
@@ -671,7 +671,7 @@ function length(g::GraphemeIterator{S}) where {S}
     return n
 end
 
-function iterate(g::GraphemeIterator, i_=(Int32(0),firstindex(g.s)))
+function iterate(g::GraphemeIterator{S}, i_=(Int32(0),firstindex(g.s))) where {S}
     s = g.s
     statei, i = i_
     state = Ref{Int32}(statei)
@@ -679,6 +679,7 @@ function iterate(g::GraphemeIterator, i_=(Int32(0),firstindex(g.s)))
     y = iterate(s, i)
     y === nothing && return nothing
     c0, k = y
+    i == firstindex(g.s) && isgraphemebreak!(state, eltype(S)(0x00000000), c0)
     while k <= ncodeunits(s) # loop until next grapheme is s[i:j]
         c, ℓ = iterate(s, k)
         isgraphemebreak!(state, c0, c) && break
```

**Comment by Keno** [comment]
I don't think that should be required. If it is, that potentially seems like a bug in utf8proc

**Comment by simeonschaub** [comment]
No, it seems to be documented: https://juliastrings.github.io/utf8proc/doc/utf8proc_8h.html#aae83bdcabf3a97c1046c0700ba353640. Apparently, we don't need to pass the state around though, we can just always set it to zero initially.

**Comment by Keno** [comment]
I wrote that documentation :). Yes, we don't need to pass the state around. Setting it to zero is fine. If that's required though that's a bug in utf8proc where it should reset the state by itself.

**Comment by simeonschaub** [comment]
I just thought this was intended because that's how it's done in `length(::GraphemeIterator)`, but perhaps that was just a workaround.

**Comment by Keno** [comment]
It's definitely not supposed to be needed because `eltype(S)(0x00000000)` is not a character that occurs in the source. Something else is wrong (maybe a missing reset of the state in utf8proc). And of course it should be refactored to not need to useless carry around the state.

**Comment by kdheepak** [comment]
Thanks for the comment @Keno. I am going through the source of `utf8proc.c` and `utf8proc.h` to see if I can narrow it down. 

UAX#29 defines the [grapheme cluster boundary rules in this section](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) and specifically there's this rule: http://www.unicode.org/reports/tr29/#GB11

>     Do not break within emoji modifier 					sequences or emoji zwj sequences.
>     --
>     GB11 | \p{Extended_Pictographic} 						Extend* ZWJ | × | \p{Extended_Pictographic}

[These lines in `grapheme_break_simple` manage the rule for this](https://github.com/JuliaStrings/utf8proc/blob/5622a0a51be80234b4464ee100bc26272e3d5210/utf8proc.c#L284-L285):

    (lbc == UTF8PROC_BOUNDCLASS_E_ZWG &&              // GB11 (requires additional handling below)
     tbc == UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) ? false : // ----

My understanding is that this is implemented as a state machine.
The `grapheme_break_simple` function that contains the code above is called from `grapheme_break_extended` which manages the state machine. 

I think it is this part of the ["state machine"](https://github.com/JuliaStrings/utf8proc/blob/5622a0a51be80234b4464ee100bc26272e3d5210/utf8proc.c#L305-L312) that is causing the issue.


    else if (*state == UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) {
      if (tbc == UTF8PROC_BOUNDCLASS_EXTEND) // fold EXTEND codepoints into emoji
        *state = UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC;
      else if (tbc == UTF8PROC_BOUNDCLASS_ZWJ)
        *state = UTF8PROC_BOUNDCLASS_E_ZWG; // state to record emoji+zwg combo
      else
        *state = tbc;
    }


I did some print style debugging to figure out what is going on.

Here is the state machine transition in the following format:

```
tbc (tbc -> boundclass) : from_state -> to_state = break_permitted
```

```
'🤦'     (UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) : UTF8PROC_BOUNDCLASS_START                 -> UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC = true
'🏼'     (UTF8PROC_BOUNDCLASS_EXTEND)                : UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC -> UTF8PROC_BOUNDCLASS_EXTEND                = false
'\u200d' (UTF8PROC_BOUNDCLASS_ZWJ)                   : UTF8PROC_BOUNDCLASS_EXTEND                -> UTF8PROC_BOUNDCLASS_ZWJ                   = false
'♂'      (UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) : UTF8PROC_BOUNDCLASS_ZWJ                   -> UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC = true
'️'       (UTF8PROC_BOUNDCLASS_EXTEND)                : UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC -> UTF8PROC_BOUNDCLASS_EXTEND                = false
```

You can see that when the boundclass is `UTF8PROC_BOUNDCLASS_ZWJ` and the state goes from `UTF8PROC_BOUNDCLASS_EXTEND` to `UTF8PROC_BOUNDCLASS_ZWJ`. I believe this state should be `UTF8PROC_BOUNDCLASS_E_ZWG` instead. The current implementation of the state machine "loses" the information that it was part of the extension.

I made the following change

```
    if (*state == tbc && tbc == UTF8PROC_BOUNDCLASS_REGIONAL_INDICATOR)
      *state = UTF8PROC_BOUNDCLASS_OTHER;
    // Special support for GB11 (emoji extend* zwj / emoji)
    else if (*state == UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) {
      if (tbc == UTF8PROC_BOUNDCLASS_EXTEND) // fold EXTEND codepoints into emoji
        *state = UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC;
      else if (tbc == UTF8PROC_BOUNDCLASS_ZWJ)
        *state = UTF8PROC_BOUNDCLASS_E_ZWG; // state to record emoji+zwg combo
      else
        *state = tbc;
    }
+   else if (*state == UTF8PROC_BOUNDCLASS_EXTEND && tbc == UTF8PROC_BOUNDCLASS_ZWJ)
+       *state = UTF8PROC_BOUNDCLASS_E_ZWG;       
    else
      *state = tbc;
```

And now the state machine behaves the way I expect it to. I ran `make check` and tests that are run all all.

However, I am still getting behavior that doesn't make sense.

Specifically, there's [this rule](http://www.unicode.org/reports/tr29/#GB1) that says:

> Break at the start and end of text, unless the text is empty.

I don't understand why the specification says "break at the start" or what "unless the text" is empty means.

[This is the implementation for this](https://github.com/JuliaStrings/utf8proc/blob/5622a0a51be80234b4464ee100bc26272e3d5210/utf8proc.c#L263)

    (lbc == UTF8PROC_BOUNDCLASS_START) ? true :       // GB1

This returns `true` at every `UTF8PROC_BOUNDCLASS_START`. Is that a correct? Maybe I'm misinterpreting the specification but that doesn't seem like what it should do, right?

I changed that line to the following:


    (lbc == UTF8PROC_BOUNDCLASS_START) ? false 

This is obviously a violation of the specification and with this change (`make check`) also fails.

But with this change and with the fix to the state machine that I mentioned above I'm getting the behavior I expect. This also seems to work for every other case I experiment with. I didn't run a full test suite though and this is my first foray into the Unicode specification and I've only read this section.

Any suggestions here would be very welcome.

**Comment by kdheepak** [comment]
I took a second stab at this just to explore again what is going on. I had a bug in my implementation! 

    if (*state == tbc && tbc == UTF8PROC_BOUNDCLASS_REGIONAL_INDICATOR)
      *state = UTF8PROC_BOUNDCLASS_OTHER;
    // Special support for GB11 (emoji extend* zwj / emoji)
    else if (*state == UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) {
      if (tbc == UTF8PROC_BOUNDCLASS_EXTEND) // fold EXTEND codepoints into emoji
        *state = UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC;
      else if (tbc == UTF8PROC_BOUNDCLASS_ZWJ)
        *state = UTF8PROC_BOUNDCLASS_E_ZWG; // state to record emoji+zwg combo
      else
        *state = tbc;
    }
+   else if (*state == UTF8PROC_BOUNDCLASS_EXTEND && tbc == UTF8PROC_BOUNDCLASS_ZWJ)
+       *state = UTF8PROC_BOUNDCLASS_E_ZWG;       
    else
      *state = tbc;


I only need to make this one change and this issue is resolved. 

The only question I have is what other states should transition to `UTF8PROC_BOUNDCLASS_E_ZWG`?

**Comment by archermarx** [comment]
I've been experimenting with this to solve a similar problem, and it seems that all of these cases are only broken if the emoji cluster appears at the beginning of the string

For example:

```
julia> collect(graphemes("🤦🏼‍♂️"))
ERROR: ArgumentError: destination has fewer elements than required
Stacktrace:
 [1] copyto!(::Array{SubString{String},1}, ::Base.Unicode.GraphemeIterator{String}) at ./abstractarray.jl:734
 [2] _collect at ./array.jl:630 [inlined]
 [3] collect(::Base.Unicode.GraphemeIterator{String}) at ./array.jl:624
 [4] top-level scope at REPL[3]:1

julia> collect(graphemes("a" * "🤦🏼‍♂️"))
2-element Array{SubString{String},1}:
 "a"
 "🤦🏼\u200d♂️"

julia> collect(graphemes("🇸🇪🇸🇪"))
2-element Array{SubString{String},1}:
 "🇸🇪🇸"
 "🇪"

julia> collect(graphemes("a"*"🇸🇪🇸🇪"))
3-element Array{SubString{String},1}:
 "a"
 "🇸🇪"
 "🇸🇪"

julia> collect(graphemes("👨🏻‍🤝‍👨🏽"))
ERROR: ArgumentError: destination has fewer elements than required
Stacktrace:
 [1] copyto!(::Array{SubString{String},1}, ::Base.Unicode.GraphemeIterator{String}) at ./abstractarray.jl:734
 [2] _collect at ./array.jl:630 [inlined]
 [3] collect(::Base.Unicode.GraphemeIterator{String}) at ./array.jl:624
 [4] top-level scope at REPL[4]:1

julia> collect(graphemes("a"*"👨🏻‍🤝‍👨🏽"))
2-element Array{SubString{String},1}:
 "a"
 "👨🏻\u200d🤝\u200d👨🏽"
```

**Comment by kdheepak** [comment]
Thanks for looking into it and submitting the patch! Does it fail even with the patch?

**Comment by archermarx** [comment]
Just did some more tests. The patch fixes "🤦🏼‍♂️" and ""👨🏻‍🤝‍👨🏽" but not "🇸🇪🇸🇪", while prepending a letter or something fixes all three test cases.

**Comment by kdheepak** [comment]
I have a patch for this that fixes the two (or multiple flags) case `🇸🇪🇸🇪`:

```
diff --git a/utf8proc.c b/utf8proc.c
index 6591976..086f430 100644
--- a/utf8proc.c
+++ b/utf8proc.c
@@ -301,6 +301,8 @@ static utf8proc_bool grapheme_break_extended(int lbc, int tbc, utf8proc_int32_t
     // forbidden by a different rule such as GB9).
     if (*state == tbc && tbc == UTF8PROC_BOUNDCLASS_REGIONAL_INDICATOR)
       *state = UTF8PROC_BOUNDCLASS_OTHER;
+    else if (*state == UTF8PROC_BOUNDCLASS_START && tbc == UTF8PROC_BOUNDCLASS_REGIONAL_INDICATOR)
+      *state = UTF8PROC_BOUNDCLASS_OTHER;
     // Special support for GB11 (emoji extend* zwj / emoji)
     else if (*state == UTF8PROC_BOUNDCLASS_EXTENDED_PICTOGRAPHIC) {
       if (tbc == UTF8PROC_BOUNDCLASS_EXTEND) // fold EXTEND codepoints into emoji
```

This patch essentially special cases when there's a regional indicator in the start.

**Comment by archermarx** [comment]
Oh sick. I can add that to my fork and submit a PR. I've got some additional tests added to the graphemetest.c file

**Comment by kdheepak** [comment]
Thanks for pushing it along!

**Comment by stevengj** [comment]
Update: the underlying bug here was that the initial `state = 0` needs to be converted internally to the bound class of the first character.   That was already done by `utf8proc_map`, which is why we passed the Unicode grapheme tests, but it wasn't being done when you called `isgraphemebreak!` (`utf8proc_grapheme_break_stateful`) manually.   (Our updated tests now check both APIs.)

One the tests on the latest utf8proc PR are green, I'll merge and then post a PR to make Julia use the updated utf8proc.
