### ISSUE TITLE
@which macro broken hyperlink for non base methods

### ISSUE THREAD

**Issue by waltsims** [JuliaLang/julia#37697]
As discussed [here](https://github.com/fonsp/Pluto.jl/issues/451), the `@which` macro does not have a correct hyperlink to the github project if the method is not found in base.

The following snippet can reproduce the issue:

```
using LinearAlgebra;
repr(MIME"text/html"(), @which Diagonal([1 2 3]))
```

**Comment by stevengj** [comment]
The relevant code is here: https://github.com/JuliaLang/julia/blob/bcad8403734380064486450438b88524b1c8543c/base/methodshow.jl#L314-L352

**Comment by stevengj** [comment]
It seems like it needs another case to handle modules in the standard library.

**Comment by stevengj** [comment]
For that matter, the branch to find the git repo also seems broken, since the package source tree is no longer a git repo?  cc @KristofferC.
