### ISSUE TITLE
Prefer collect(a:b) over [a:b;] in tests

### ISSUE THREAD

**Issue by remi-garcia** [JuliaLang/julia#37698]
As discussed [here](https://discourse.julialang.org/t/collect-a-vs-a/47055/7) the use of `[a:b;]` is not as natural as `collect(a:b)` and it might be good to prefer `collect` in tests.
Here for example:
https://github.com/JuliaLang/julia/blob/46cf572773b05d8f4ab74705b139f7a921227c02/test/sorting.jl#L36

CC @oheil @ericphanson @tpapp

**Comment by tpapp** [comment]
I would also prefer `collect`, but this may not be worth a PR if we are talking about test code.

I would suggest you wait for the core devs to chime in before investing the effort.

**Comment by timholy** [comment]
I don't personally see a big advantage to `collect`, and the semicolon notation is widely used (e.g., you see `A = [1 2; 3 4]` all the time).

**Comment by tpapp** [comment]
Of course the syntax for `hvcat` is widely used and perfectly fine in general, but using it just for `collect` is a minor style abuse IMO. But not a big deal, this is a matter of taste.

**Comment by KristofferC** [comment]
There's no need to go through all the tests and change this. Probably best to leave it to the discretion of the test writer.
