### ISSUE TITLE
Julia crash with OnlineStats and Observables

### ISSUE THREAD

**Issue by theogf** [JuliaLang/julia#37695]
Running an example with `OnlineStats` and `Observables` with `Makie`, julia ends up crashing with the following error : 
```
Unreachable reached at 0x7fbd9a6e8aa0
signal (4): Illegal instruction
```
Here is a MWE : https://gist.github.com/theogf/9069bacc7038ad6fae37d622acd2a7ec
Here is the rr report : https://s3.amazonaws.com/julialang-dumps/reports/2020-09-22T10-24-24-theogf.tar.zst
And here my `versioninfo()`
```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by theogf** [comment]
Note that this can solved by getting the `OnlineStat` object out of the observables : https://gist.github.com/theogf/7b20b7dedc98f5bc3b3028cdb9068d1a

**Comment by ViralBShah** [comment]
Closing this as old - since the attached code no longer runs. I'm quite sure this is no longer an issue, but if it is, please update the example.
