### ISSUE TITLE
Downloads.jl tests sometimes fail

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#37709]
https://build.julialang.org/#/builders/34/builds/4010/steps/5/logs/stdio

```
Error in testset Downloads:
Test Failed at /buildworker/worker/tester_linux64/build/share/julia/stdlib/v1.6/Downloads/test/runtests.jl:82
  Expression: 2t < count * delay
   Evaluated: 39.462654792 < 20
```

**Comment by StefanKarpinski** [comment]
It's a bit hard to dial this down and still test that downloads are happening concurrently at all. Here `t = 19.731327396` and it would take 20 seconds to do the downloads sequentially. I guess I could loosen the test to `t < count*delay` which is literally the loosest test that ensures that some concurrency occurred.

**Comment by StefanKarpinski** [comment]
This may also be improved by using our own `httpbingo` server, which just happened the other day.
