### ISSUE TITLE
Socket becomes unwritable after first read with (cat file | nc) client

### ISSUE THREAD

**Issue by julbinb** [JuliaLang/julia#37721]
The problem is reproducible in Julia 1.4.2 and 1.5.

### Minimal example

Server code:

```julia
using Sockets

port = 2023
server = listen(port)
sock = accept(server)

@show isopen(sock) # true
if isopen(sock) && !eof(sock)
  n = read(sock, Int)
  @show iswritable(sock) #false
  @show isopen(sock) # false
  write(sock, n) # ERROR: IOError stream is closed or unusable
end
```

Client code:

```
$ cat input.txt | nc localhost 2023
```

or, for newer version of netcat,

```
$ cat input.txt | nc -N localhost 2023
```

where `input.txt` is `5 7`.

### Problem

Socket `sock` becomes unwritable after the first call to `read`. 

What _should_ happen (and happends with sockets in other languages, e.g. Java and Python):
netcat sends data from `input.txt` and closes the connection in one direction; the server writes a reply back to netcat;
the server terminates, and then netcat terminates.

It seems that Julia does not have a notion of "closing in one direction", so after the input closes, it's impossible to write back.

**Comment by Keno** [comment]
This might be the same as https://github.com/JuliaLang/julia/issues/35442?

**Comment by julbinb** [comment]
Indeed, it seems so!
