### ISSUE TITLE
No method for lmul!(::Diagonal, ::AbstractVector)

### ISSUE THREAD

**Issue by Mankka** [JuliaLang/julia#37726]
The following code fails on v1.5.2 with
`MethodError: no method matching lmul!(::Diagonal{Float64,Array{Float64,1}}, ::Array{Float64,1})`:
```
using LinearAlgebra
M = Diagonal(randn(3))
x = randn(3)
lmul!(M, x)
```
in `stdlib/v1.5/LinearAlgebra/src/diagonal.jl` there is a method `function lmul!(D::Diagonal, B::AbstractMatrix)`. Should it simply be changed to `function lmul!(D::Diagonal, B::AbstractVecOrMat)`?

**Comment by dkarrasch** [comment]
That has already been done in https://github.com/JuliaLang/julia/pull/36012, to fix #36011. It's going to be in v1.6, and is available in the nightly version.
