### ISSUE TITLE
Have `reinterpret` return a scalar when reinterpreting an array

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#37732]
Currently when using `reinterpret` with a scalar type and a vector, a vector is returned:
```julia
julia> reinterpret(Float32, UInt32[1 2 3 4 5])
1×5 reinterpret(Float32, ::Array{UInt32,2}):
 1.0f-45  3.0f-45  4.0f-45  6.0f-45  7.0f-45
```
Although, useful for reinterpreting each element of an array the behaviour of returning a vector is a bit strange when reinterpreting a vector into single scalar:
```julia
julia> reinterpret(UInt32, [0x01, 0x00, 0x00, 0x00])  # Ideally just the scalar is returned
1-element reinterpret(UInt32, ::Array{UInt8,1}):
 0x00000001
```
I would propose that we use the broadcasting syntax to perform the first call (`reinterpret.(Float32, UInt32[1 2 3 4 5])`) and have the non-broadcasted version return a scalar.

**Comment by yuyichao** [comment]
No they do completely different things. Reinterpret of an array is not at all an per-element operation, i.e. `reinterpret(UInt32, [0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00])` cannot be replaced by broadcasting and must not return a scalar. Also, returning a scalar is just wrong as well, since there's no way to mutate the scalar and have it reflect on the original array.

**Comment by PhilipVinc** [comment]
Wouldn't it also be type unstable, because you can't know the length of the input at inference time?

**Comment by yuyichao** [comment]
Requiring the return value to be scalar would not be type unstable (it'll be an error instead) but as I said, it does not do the right thing and the right thing to do cannot be replaced by broadcast.

I feel like this is basically coming from the desire to reinterpret complex struct or between bytes and larger scalar values. I think they should be implemented via other API instead.

**Comment by omus** [comment]
> i.e. `reinterpret(UInt32, [0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00])`

A good point. Broadcasting probably wouldn't be the right approach but something like `ReinterpretArray{UInt32}([0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00])` would probably be sensible.

**Comment by omus** [comment]
> I feel like this is basically coming from the desire to reinterpret complex struct or between bytes and larger scalar values. I think they should be implemented via other API instead.

My desire to see this changed was brought on by being surprised by the behaviour of `reinterpret(UInt32, [0x01, 0x00, 0x00, 0x00])` and then being concerned about performance about allocations with `ReinterpretArray` when I don't care about mutating the original array.

**Comment by yuyichao** [comment]
If you already have an array then that access should be possible to optimize out, after proper bounds check and such. It's definately not something that worth breaking the API for.

**Comment by yuyichao** [comment]
AFAICT,

```julia
f(a) = reinterpret(UInt32, a)[]
```

does not allocate for `Vector{UInt8}` input so there should be no performance concern. If there's any other case that is still allocating, feel free to open a separate issue to track that.

**Comment by omus** [comment]
I still maintain that the API is a bit strange here and can be improved to be clearer. Would it be reasonable to keep this open and add the 2.0 milestone for future consideration?

**Comment by KristofferC** [comment]
FWIW, SIMD.jl has this: https://github.com/eschnett/SIMD.jl/blob/e57acee4bb6425df155d229db98fb4fc96d0bb22/src/simdvec.jl#L115

**Comment by yuyichao** [comment]
> I still maintain that the API is a bit strange here

What's strange about reinterpret an array as an array? It's in fact very strange if reinterpret returns a scalar from array input given that it'll be the same return type as scalar input.

Having other scalar input to be reinterpreted as scalar do not have this concern and I personally don't have much issue with it either. The one in simd is exactly one example of that.

**Comment by yuyichao** [comment]
> Maybe the scalar version could be used when the second type is a Tuple or more generally a bitstype of the correct size (unless that has a meaning already)

Yes that's the one I mentioned based in my guess for the motivation above. I'm 90% sure there's an issue for that already. In any case, that's a feature addition that is not breaking so it is completely different from this issue.

Such a function can basically only work for non pointer (and maybe also no bitsunon fields) types and you can already implementate it using unsafe load on refs.

**Comment by KristofferC** [comment]
IIRC, the discussion was about padding but not sure.

**Comment by yuyichao** [comment]
> IIRC, the discussion was about padding but not sure.

You mean to allow more bits types? Yeah, I think it was about uninitialized values and breaking the invariant in the contructor, either due to padding or simply just values not controlled by constructors. OTOH, bits types can in general be constructed uninitialized, i.e. `Ref{T}()[]`, so at least now I don't think it's **that** critical to protect people from shooting themselves. It'll be OK calling it unsafe, though it's not really that much less safe than the current reinterpret (you can still have constructor and may still want to maintain some invariance for primitive types) and also the `Ref` syntax is basically always shorter so I'm not sure if it's necessary to call it unsafe either...
