### ISSUE TITLE
~/.julia/config/startup.jl is accessed while building `julia`

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#37737]
Since somewhere between 2a36f83ce9bdfd17c572472f60b830aedcf181f0 and 3b55daef61c728f2dab2973db953111d0a6a6ca9, it seems that `generate_precompile.jl` started to accidentally load `~/.julia/config/startup.jl`. Here is an MWE:

```sh
rm ~/.julia/config/startup.jl &&
echo oops > ~/.julia/config/startup.jl &&
rm -v usr/lib/julia/sys* &&
make
```

then I get

```
....
Sysimage built. Summary:
Total ───────  51.493338 seconds
Base: ───────  21.010576 seconds 40.8025%
Stdlibs: ────  30.481181 seconds 59.1944%
    JULIA usr/lib/julia/sys-o.a
ERROR: LoadError: UndefVarError: oops not defined
in expression starting at /home/takafumi/.julia/config/startup.jl:1
...
```

I'm running a brute-force search here: https://github.com/tkf/julia/actions/runs/271800886

@staticfloat Can we have something like

```julia
error("startup.jl is accessed while building `julia`")
```

in `~/.julia/config/startup.jl` during the build process to avoid regression like this?

**Comment by KristofferC** [comment]
Yeah, that was probably my new thing. Will fix
