### ISSUE TITLE
multiple definition of `_U_dyn_info_list'

### ISSUE THREAD

**Issue by gdkrmr** [JuliaLang/julia#37742]
I am trying to build the release-1.5 branch from source without binary builder on Manjaro and get the following error:

```
    LINK usr/lib/libjulia.so.1.5
/usr/bin/ld: /home/gkraemer/progs/julia/julia-1.5/usr/lib/libunwind.a(dyn-info-list.o):(.bss+0x0): multiple definition of `_U_dyn_info_list'; /home/gkraemer/progs/julia/julia-1.5/usr/lib/libunwind.a(Linit.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:333: /home/gkraemer/progs/julia/julia-1.5/usr/lib/libjulia.so.1.5] Error 1
make: *** [Makefile:75: julia-src-release] Error 2
```

Searching the internet I could find this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248699

**Comment by inkydragon** [comment]
Fixed by https://github.com/libunwind/libunwind/pull/166
We are using libunwind v1.5.0 which already includes that patch.

**Comment by KristofferC** [comment]
I guess this can be closed then
