### ISSUE TITLE
Symbol("a,b") in method signatures should be displayed as var"a,b"

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#37743]
The issue was pointed out in [this discourse discussion](https://discourse.julialang.org/t/why-cant-i-generate-a-function-with-multiple-arguments-using-symbol-arg1-arg2/47254). The display appears to be incorrect here:

```julia
julia> for TA in [Symbol("a,b")]
       @eval f($TA) = a + b
       end

julia> methods(f)
# 1 method for generic function "f":
[1] f(a,b) in Main at REPL[1]:2
```

There is no method `f(a,b)` that is generated, and the method arguments should probably be displayed as `var"a,b"`. For example:

```julia
julia> f(1,2)
ERROR: MethodError: no method matching f(::Int64, ::Int64)
```

**Comment by simeonschaub** [comment]
It seems like we are using `print` and `string` in `show(::Method)`, whereas we probably should be using `Base.show_unquoted` instead.
