### ISSUE TITLE
Incremental compilation error with @doc on a submodule

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#37771]
In recent versions of Julia 1.6-DEV, this MWE (https://github.com/tkf/MyPlayground.jl/pull/38)

```julia
module MyPlayground

module Extras end

@doc "Extras docstring" Extras

end # module
```

fails to precompile with error

> ```ERROR: LoadError: Evaluation into the closed module `Extras` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Extras` with `eval` during precompilation - don't do this.```
>
> --- https://travis-ci.com/github/tkf/MyPlayground.jl/builds/186853140#L228

**Comment by tkf** [comment]
It looks like 382627946dc4868cba4df52a93be6e34b349cb15 (#37626) introduced the bug. See the brute-force search here: https://github.com/tkf/julia/actions/runs/274646833

cc @timholy

**Comment by tkf** [comment]
I implemented a workaround in my package affected by this.

Depending on how hard it is to solve this, I think it might be reasonable to treat #37626 as a "minor change" and leave it as-is.

**Comment by vtjnash** [comment]
That eval is supposed to be permitted
