### ISSUE TITLE
`ccall` codgen for `Base.RefValue` differs from `Base.Ref`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#37778]
Using `Base.RefValue` as part of a `ccall` signature leads to the double value contained in the reference to be passed as value.

```
julia> g(thunk, x) = ccall(thunk, Float64, (Base.RefValue{Float64}, ), x)
g (generic function with 1 method)

julia> code_llvm(g, Tuple{Ptr{Cvoid}, Base.RefValue{Float64}})

;  @ REPL[5]:1 within `g'
define double @julia_g_142(i64, %jl_value_t* nonnull align 8 dereferenceable(8)) {
top:
  %2 = icmp eq i64 %0, 0
  br i1 %2, label %fail, label %pass

fail:                                             ; preds = %top
  call void @jl_throw(%jl_value_t* inttoptr (i64 139920140033760 to %jl_value_t*))
  unreachable

pass:                                             ; preds = %top
  %3 = bitcast %jl_value_t* %1 to double*
  %.unpack = load double, double* %3, align 8
  %4 = inttoptr i64 %0 to double (double)*
  %5 = call double %4(double %.unpack)
  ret double %5
}
```

What I expected was the behaviour for `Ref{Float64}`.

```
julia> f(thunk, x) = ccall(thunk, Float64, (Ref{Float64}, ), x)
f (generic function with 1 method)

julia> code_llvm(f, Tuple{Ptr{Cvoid}, Base.RefValue{Float64}})

;  @ REPL[1]:1 within `f'
define double @julia_f_132(i64, %jl_value_t* nonnull align 8 dereferenceable(8)) {
top:
  %2 = icmp eq i64 %0, 0
  br i1 %2, label %fail, label %pass

fail:                                             ; preds = %top
  call void @jl_throw(%jl_value_t* inttoptr (i64 139920140033760 to %jl_value_t*))
  unreachable

pass:                                             ; preds = %top
  %3 = bitcast %jl_value_t* %1 to i8*
  %4 = inttoptr i64 %0 to double (i8*)*
  %5 = call double %4(i8* %3)
  ret double %5
}
```

Observed this on Julia 1.5.1, 1.4.2, and master.

**Comment by yuyichao** [comment]
RefValue is a concrete type so you are passing the struct by value.

**Comment by vchuravy** [comment]
That I would have understood, but I am not passing the struct by value. Codegen dereferences the RefValue and passes the content by value. 

Is this behaviour documented anywhere? I couldn't find anything.

**Comment by yuyichao** [comment]
I can check but I assume it's simply the calling convention for a struct with a single floating point member.

**Comment by yuyichao** [comment]
Yes, it's the same lowering clang does,

```c++
struct A {
    double a;
};

void f(struct A);

void g()
{
    struct A a = {0};
    f(a);
}
```

compiles to

```llvm
define dso_local void @g() local_unnamed_addr #0 {
  tail call void @f(double 0.000000e+00) #2
  ret void
}
```

by clang.

**Comment by yuyichao** [comment]
> Is this behaviour documented anywhere? I couldn't find anything.

And since this is the mapping between the llvm calling convention and the C calling convention, I would also like to find a formal document somewhere and I wasn't able to find any...... The AArch64 one I wrote was purely based on looking at clang output, reading aapcs64, testing edge cases and assume llvm behaves in a sane way...

**Comment by vchuravy** [comment]
Thanks Yichao for the info.
