### ISSUE TITLE
bug with the package SymEngine

### ISSUE THREAD

**Issue by Myrddinlefou** [JuliaLang/julia#37770]
Hello evryone,

I have a bug with the package SymEngine : 

The code :  

``using SymEngine
@vars Uin, Iin, Il, Ul, Id, Uc, Ic, Uout, Iout, Rout, C, L

dUc1 = subs(Ic/C,Ic=>Il-Iout,Iout=>Rout*Uout, Uout=>Uc)

SymEngine.get_name(dUc1)
``
The error : 

> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff84df460f -- memcpy at C:\WINDOWS\System32\msvcrt.dll (unknown line)
in expression starting at none:1
memcpy at C:\WINDOWS\System32\msvcrt.dll (unknown line)
_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPcEEvT_S7_St20forward_iterator_tag.isra.492 at C:\Users\Florian\.julia\artifacts\9bfc40fb727d9f2c01da7590b6edf5d4d27f7275\bin\libsymengine-0.6.dll (unknown line)
function_symbol_get_name at C:\Users\Florian\.julia\artifacts\9bfc40fb727d9f2c01da7590b6edf5d4d27f7275\bin\libsymengine-0.6.dll (unknown line)
get_name at C:\Users\Florian\.julia\packages\SymEngine\lLmHe\src\types.jl:260
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331 [inlined]
repleval at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:196
#242 at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:223
unknown function (ip: 00000000269E3D43)
with_logstate at .\logging.jl:408
with_logger at .\logging.jl:514 [inlined]
evalrepl at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:214
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:134
repl_backend_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:195
start_repl_backend at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:180
#run_repl#37 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:292
run_repl at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:288
#806 at .\client.jl:399
jfptr_YY.806_45542.clone_1 at C:\Users\Florian\AppData\Local\Programs\Julia 1.5.1\lib\julia\sys.dll (unknown line)

And the versioninfo :

>Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 2700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "C:\Users\Florian\AppData\Local\atom\app-1.51.0\atom.exe"  -a
  JULIA_NUM_THREADS = 16

Thank's a lot 

Myrddin

**Comment by KristofferC** [comment]
The latest released version is 1.5.2. It's a good idea to try to always be on the latest version in general but especially when submitting bug reports, the bug might have been fixed.

**Comment by Myrddinlefou** [comment]
I am sorry. The bug is also here with the newest version of Julia :
>Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 2700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "C:\Users\Florian\AppData\Local\atom\app-1.51.0\atom.exe"  -a
  JULIA_NUM_THREADS = 16

and the new error :
>Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff84df460f -- memcpy at C:\WINDOWS\System32\msvcrt.dll (unknown line)
in expression starting at none:1
memcpy at C:\WINDOWS\System32\msvcrt.dll (unknown line)
_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPcEEvT_S7_St20forward_iterator_tag.isra.492 at C:\Users\Florian\.julia\artifacts\9bfc40fb727d9f2c01da7590b6edf5d4d27f7275\bin\libsymengine-0.6.dll (unknown line)
function_symbol_get_name at C:\Users\Florian\.julia\artifacts\9bfc40fb727d9f2c01da7590b6edf5d4d27f7275\bin\libsymengine-0.6.dll (unknown line)
get_name at C:\Users\Florian\.julia\packages\SymEngine\lLmHe\src\types.jl:260
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331 [inlined]
repleval at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:196
#242 at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:223
unknown function (ip: 000000000142C753)
with_logstate at .\logging.jl:408
with_logger at .\logging.jl:514 [inlined]
evalrepl at C:\Users\Florian\.julia\packages\Atom\ZeFbA\src\repl.jl:214
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_call at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:117
eval_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:206
eval_stmt_value at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:157 [inlined]
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:548
jl_interpret_toplevel_thunk at /cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:660
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:840
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:849 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:883
eval at .\boot.jl:331
eval_user_input at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:134
repl_backend_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:195
start_repl_backend at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:180
#run_repl#37 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:292
run_repl at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\REPL\src\REPL.jl:288
#807 at .\client.jl:399
jfptr_YY.807_44712.clone_1 at C:\Users\Florian\AppData\Local\Programs\Julia 1.5.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709 [inlined]
run_main_repl at .\client.jl:383
exec_options at .\client.jl:313
_start at .\client.jl:506
jfptr__start_46405.clone_1 at C:\Users\Florian\AppData\Local\Programs\Julia 1.5.2\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
true_main at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:106
wmain at /cygdrive/d/buildbot/worker/package_win64/build/ui\repl.c:227
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:334
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-7.0.0-1/crt\crtexe.c:223
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 66584948 (Pool: 66505160; Big: 79788); GC: 84

**Comment by yuyichao** [comment]
From a very rough look, the package is not managing the memory correctly. (At least all the `.ptr` in `src/types.jl` are wrong). Given that the crash is in the library used by the package, this is likely a package bug. Please define the proper methods for `unsafe_convert` for `C*Basic` and possibly other types to see if that fixes the issue. If not, feel free to comment back for reopening.
