### ISSUE TITLE
Missing output whilst using Tasks

### ISSUE THREAD

**Issue by kismet-kah** [JuliaLang/julia#37796]
Whilst trying to understand task scheduling, I tried the following example: 

```function test36()
    function f()
        println("A1")
        println("A2")
        println("A3")
        println("A4")
        println("A5")
    end
    t = Task(f)
    schedule(t)
    println("B1")
    println("B2")
    sum(sin, 1:10000000)
end
```

I got the following output: 

```julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER = pkg.juliahub.com
  JULIA_DEPOT_PATH = /Users/keithharrison/.julia:/Applications/JuliaPro-1.5.1-1.app/Contents/Resources/julia/Contents/Resources/julia/local/share/julia:/Applications/JuliaPro-1.5.1-1.app/Contents/Resources/julia/Contents/Resources/julia/share/julia
  JULIA_LOAD_PATH = @:@v#.#:@stdlib

julia> test36()
B1
B2
A1
1.9558914085409347A2


julia> 
julia> 
A5
```

I seem to be missing two lines of output. Namely "A3", "A4". (The sum is there to give a busy wait. And I know there is no explicit yield ...)

**Comment by KristofferC** [comment]
What happens if you put a semicolon after the last `end`. The REPL showing the output might clear out other things.

**Comment by kismet-kah** [comment]
My apologies. I inadvertently missed the first line of the code:

```
function test36()
    function f()
        println("A1")
        println("A2")
        println("A3")
        println("A4")
        println("A5")
    end
    t = Task(f)
    schedule(t)
    println("B1")
    println("B2")
    sum(sin, 1:10000000)
end
```

I now get ... 

```
julia> test36();
B1
B2
A1

julia> A2
julia> A3
A4
A5
```

So, yes, the REPL is clearing out. I enter the test36() and the rest of the output, including the multiple prompts, is outputted. It surprised me that some of the output was dropped.

**Comment by KristofferC** [comment]
Just `wait` on `t` before returning. If you have multiple things writing to the terminal where one of them among other things clears lines then it is natural for some things to not show.
