### ISSUE TITLE
Floating point hash bug

### ISSUE THREAD

**Issue by jmkuhn** [JuliaLang/julia#37800]
```
using InteractiveUtils
using Printf

function myhash(x)
    # the following is valid for x == Inf
    h = UInt(0)
    num, pow, den = Base.decompose(x)
    den == 0 && return hash(ifelse(num > 0, Inf, -Inf), h)
    return nothing
end

versioninfo()
h = hash(Inf)
@printf("%#x\n", h)
h = myhash(Inf)
@printf("%#x\n", h)
```
With LLVM 9 I get the expected output:
```
Julia Version 1.6.0-DEV.1014
Commit 2a36f83ce9 (2020-09-22 20:52 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
0x807bb202c9cbfc6f
0x807bb202c9cbfc6f
```
With LLVM 10 I get:
```
Julia Version 1.6.0-DEV.1015
Commit 9adcdd42a0 (2020-09-23 03:04 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)
0x807bb202c9cbfc6f
0x15d7d083d04ecb90
```
Edit:
`0x15d7d083d04ecb90` is the correct hash for `NaN`

**Comment by yuyichao** [comment]
```
julia> function myhash(b)
           return hash(ifelse(b, Inf, -Inf), UInt(0))
       end
myhash (generic function with 1 method)

julia> myhash(false)
0x15d7d083d04ecb90

julia> myhash(true)
0x15d7d083d04ecb90

julia> hash(-Inf, UInt(0))
0x96e782fc7639e1bc

julia> hash(Inf, UInt(0))
0x807bb202c9cbfc6f
```

**Comment by yuyichao** [comment]
Seems as if it evaluated `Inf == Inf` to `false` and used the `NaN` hash value instead...

**Comment by yuyichao** [comment]
And it seems like a julia bug. The implementation of [`hash`](https://github.com/JuliaLang/julia/blob/4f0145b7b0e8766d6a7b9d8f51f7e0ba184b383b/base/float.jl#L559) relies on `fptoui` of the floating point value which produces a [poison value](https://llvm.org/docs/LangRef.html#fptoui-to-instruction) if the fp value couldn't fit. It is therefore perfectly legal for LLVM to produce any result for `hash(Inf)`. The implementation was previously relying on `fptoui` to return a fixed value which is wrong. In fact, it doesn't even return the same result on, say AArch64.

**Comment by yuyichao** [comment]
Ref https://github.com/JuliaLang/julia/commit/36969687fb9bbd936b3adc0baa6cf0a408d2ccb7 which was an incomplete fix with an incorrect explaination.

**Comment by KristofferC** [comment]
Did some archeology and found https://github.com/JuliaLang/julia/commit/36969687fb9bbd936b3adc0baa6cf0a408d2ccb7. Kinda funny how this comes back 6 years later.

**Comment by KristofferC** [comment]
Sniped...
