### ISSUE TITLE
x.<tab><tab> in the REPL sometimes prints the entire list of Base exports

### ISSUE THREAD

**Issue by jonniedie** [JuliaLang/julia#37815]
Example to reproduce:
```julia
julia> x=1
1

julia> x.<tab><tab>
```

versioninfo:
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment]
I think it is the same as if you just press tab twice with nothing in the REPL.

**Comment by jonniedie** [comment]
You're right with the two tabs. I updated it accordingly. But it is still behavior that I don't think anyone wants when they are trying to get the property names of a variable. I can't picture a situation where you'd want `julia> x.<tab><tab>` to do the same thing as `julia> <tab><tab>`.

**Comment by shashankp** [comment]
Related feature request https://github.com/JuliaLang/julia/issues/36698

**Comment by BioTurboNick** [comment]
Uncovered this issue when trying to copy over indented code from a Pluto.jl notebook, which uses tabs to indent.
