### ISSUE TITLE
First run of Julia can result in corrupt state

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#37833]
I'm posting for this new user:
https://discourse.julialang.org/t/unable-to-install-ijulia/47160

see the error message there. It was likely because of a temporary internet problem, even at the Julia server, but that's a separate issue.

I was trying to help, and eventually it was as simple as deleting the .julia folder, and running Julia again.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/issues/1667
