### ISSUE TITLE
ed and nvi unsupported

### ISSUE THREAD

**Issue by apparluk** [JuliaLang/julia#37862]
Proposed clarification in the manual about unsupported editors.

CHAPTER 71. INTERACTIVE UTILITIES

current

Edit a file or directory optionally providing a line number to edit the file at. Return to the julia prompt when you quit the editor. The editor can be changed by setting JULIA_EDITOR, VISUAL or EDITOR as an environment variable.

proposed

Edit a file or directory optionally providing a line number to edit the file at. Return to the julia prompt when you quit the editor. The editor can be changed by setting JULIA_EDITOR, VISUAL (nvi unsupported) or EDITOR (ed and ex unsupported) as an environment variable.

**Comment by StefanKarpinski** [comment]
Why would we call out two specific editors as being unsupported like this? It would be fine to make a PR to add support for those editors in the default list.

**Comment by PallHaraldsson** [comment]
A PR is probably simple, note my first code PR to Julia was for vi, see here: https://github.com/JuliaLang/julia/pull/10771/files

I even did the change through the GitHub editor.

**Comment by apparluk** [comment]
BSD purportedly uses nvi.

**Comment by apparluk** [comment]
> make a PR

not for ed it can't open files on a specified line number

**Comment by StefanKarpinski** [comment]
What is the goal here? Are you asking for support to be added for specific editors? Or are you requesting that we list every editor ever created that we don't support? The former is possible and if you want to make pull requests adding support for specific editors, that would be welcomed. The latter is not reasonable because there are an unbounded number of editors that we do not support.

**Comment by PallHaraldsson** [comment]
FYI: If you want to make a PR, the file has moved and changed: https://github.com/JuliaLang/julia/blob/master/stdlib/InteractiveUtils/src/editless.jl

I looked a bit into adding nvi support, but it's not a priority to me, and it seems like it could be added dynamically (but I was doing something wrong):

Revise.track(Base)

ENV["EDITOR"] = "nvi"

InteractiveUtils.define_editor(
               r"nvi", wait=true) do cmd, path, line
               `\$cmd +\$line \$path`
           end

@edit println("Palli")
```

**Comment by apparluk** [comment]
On Linux running bash starting julia and changing to shell mode is <kbd>C-x C-e</kbd> expected to work?

@PallHaraldsson

I suppose there are Julia coders running BSD.

@StefanKarpinski 

Line editors should be started from Julia shell mode.

For legacy reasons one should probably document this.

The _Open_ Group ([ed](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ed.html), [ex](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html))

**Comment by apparluk** [comment]
@PallHaraldsson

Borrowing Jakob Nybo Nissen's code from a recently closed topic.

```
bash-4.3$ VISUAL=nvi julia --banner=no
julia> InteractiveUtils.define_editor("nvi", wait=true) do cmd, path, line
       `$cmd +$line $path`
       end
1-element Array{Function,1}:
 #2 (generic function with 1 method)

julia> edit("/home/eric/.julia/config/startup.jl", 2)

julia> exit()
bash-4.3$ 
```

If you don't give it a line number it outputs this.

```
-c option, 1: The p command doesn't permit an address of 0
Press Enter to continue:  
```

**Comment by apparluk** [comment]
@keithbostic

Is there is a simple work around?

**Comment by apparluk** [comment]
FreeBSD changed to an nvi fork in 2013.

I'll be closing unless there is any more comments on mentioning line editors in the manual.
