### ISSUE TITLE
Julia stewards harm other open source projects

### ISSUE THREAD

**Issue by chakravala** [JuliaLang/julia#37871]
The Julia stewards are harming open source by denying third parties such as myself and my random users to coordinate bug fixes via the julia community.

For example, I was immediately banned when I tried to respond to a bug report of one of my packages with a fix. Even as a new account with a generic statement like "the bug has been fixed, did you try it?" results in an immediate ban.

When I try to explain how this is harming open source, that also is an immediate ban. The julia stewards do not facilitate an inclusive collaborative environment for open source projects in the Julia language

Not all of my interactions in the past may have been ideally done, but my only goal at any point has been to coordinate on the development of free software.

I just only want to collaborate on open source free software and help improve things, but I am being denied this ability by the Julia stewards.

I recommend that the Julia stewards become more inclusive towards third party bug report/fix interactions in their platform . These julia stewards are highly paid people harming the open source projects of people struggling with life, they don't understand the harmful consequences.

Whatever stupid behavior I may have had before, it was at worst expressing an intellectual perspective or feeling.
I have not harmed anyone.

Meanwhile, the Julia stewards are causing actual harm to open source collaboration and bug fix coordination among third parties and other users depending on me.

The harm the Julia stewards are engaging in towards free software is not justifiable.

The Julia stewards are also unwilling to work to resolve the situation to improve open source for everyone.

**Comment by fredrikekre** [comment]
Please stop.
