### ISSUE TITLE
print/println should block write final output 

### ISSUE THREAD

**Issue by amitmurthy** [JuliaLang/julia#3787]
As folks start working with more parallel constructs, it will be good to have print/println do a block write of the final string. 

```
julia> @sync begin
           for i in 1:3
               @async begin
                   println("Getting garbled")
               end
           end
       end
Getting garbledGetting garbledGetting garbled



```

The newline is written separately.

```
julia> @sync begin
           for i in 1:3
               @async begin
                   println(`Getting garbled`)
               end
           end
       end
```GGGeeettttttiiinnnggg   gggaaarrrbbbllleeeddd```

```

**Comment by amitmurthy** [comment]
Regression in https://github.com/JuliaLang/julia/commit/334a2be705fb0a742508cb05c22b37cd5956888c

**Comment by Sisyphuss** [comment]
Is the third post in #12600 a related issue?

**Comment by amitmurthy** [comment]
@Sisyphuss , #12600 is not related and not a bug. `for` introduces a new scope as documented. `global x = i` will result in the behavior you are looking for.

**Comment by Sisyphuss** [comment]
@amitmurthy no I meant the output format: the output "0" is between the print "x:1" and "x:2, x:3".

**Comment by KristofferC** [comment]
I also get a lot of interleaved printing in my Jupyter notebooks.

**Comment by amitmurthy** [comment]
@KristofferC can you post examples? Currently only `println` to asynchronous streams is locked. If you are using `print` statements, you will need to manage it manually - http://docs.julialang.org/en/latest/manual/faq/#asynchronous-io-and-concurrent-synchronous-writes
