### ISSUE TITLE
resize! for multidimensional arrays 

### ISSUE THREAD

**Issue by ranocha** [JuliaLang/julia#37900]
It would be really nice to be able to `resize!` multidimensional `Array`s, even if restricted to the last dimension (because of memory layout), similarly to [ElasticArrays.jl](https://github.com/JuliaArrays/ElasticArrays.jl).

### Background 

We want to make use of adaptive mesh refinement (AMR) for our hyperbolic PDE solver package [Trixi.jl](https://github.com/trixi-framework/Trixi.jl). For us, the most natural data layout is given by multidimensional arrays. To use AMR, we need to `resize!` the last dimension of these arrays.

Needing to use `ElasticArray` doesn't feel completely good to me, since we also want to experiment with other array types such as [PaddedMatrices.jl](https://github.com/chriselrod/PaddedMatrices.jl), see https://github.com/trixi-framework/Trixi.jl/issues/166. Then, we would need to wrap an `Array` inside something from PaddedMatrices.jl inside something from ElasticArrays.jl - or the other way round? Is that possible at all? If we go further, this looks like it could easily explode.

**Comment by JeffBezanson** [comment]
This is a very tall order, since the possibility of the array moving (and hence pointers changing) can inhibit a lot of compiler optimizations. So I think the best approach is to make `Array` as efficient as possible, and use wrappers like ElasticArray around it to add more features. If `Array` is slow we're stuck and can't get the lost performance back.

**Comment by ranocha** [comment]
Would it be possible to basically use `jl_array_grow_at_end` also for multidimensional arrays (https://github.com/JuliaLang/julia/blob/7d3dac44dc917a215607bfa1a6054a21846f02a7/src/array.c#L875)? I am willing to invest some work in this but would like to get your feedback whether that's a) possible at all and b) acceptable for Base Julia?

**Comment by timholy** [comment]
What Jeff is saying is that if you do this then we have to disable other optimizations and everyone else suffers performance-wise because of it.

**Comment by ranocha** [comment]
Okay, I see. Thanks a lot for your feedback. Feel free to close this issue in that case.

**Comment by jebej** [comment]
> This is a very tall order, since the possibility of the array moving (and hence pointers changing) can inhibit a lot of compiler optimizations

Is this not the case for 1D arrays currently then?

It seems like if 1D arrays can be resized, then multidimensional arrays should be able to be resized in the last dimension too. If that's not true, would you mind quickly explaining the difference?
