### ISSUE TITLE
nextind not defined for NamedTuples

### ISSUE THREAD

**Issue by jonalm** [JuliaLang/julia#37926]
```
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA = /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 3

julia> a = (b=2,)
(b = 2,)

julia> nextind(a,1)
ERROR: MethodError: no method matching nextind(::NamedTuple{(:b,),Tuple{Int64}}, ::Int64)
Closest candidates are:
  nextind(::SubString{String}, ::Int64) at strings/substring.jl:96
  nextind(::String, ::Int64) at strings/string.jl:137
  nextind(::Tuple, ::Integer) at tuple.jl:67
  ...
Stacktrace:
 [1] top-level scope at REPL[14]:1
```

Same issue for `prevind`

**Comment by jonalm** [comment]
Is the solution is as simple as adding
```julia
prevind(@nospecialize(t::NamedTuple), i::Integer) = Int(i)-1
nextind(@nospecialize(t::NamedTuple), i::Integer) = Int(i)+1
```
(modified versions of https://github.com/JuliaLang/julia/blob/master/base/tuple.jl#L71)

to base/namedtuples.jl?

I would happily contribute with a PR :)

**Comment by KristofferC** [comment]
I thought these were only for strings (that's what they are documented before) but it seems they have been added to `AbstractArray` as well.

**Comment by jonalm** [comment]
The reason I stumbled upon this was essentially this
```julia
julia> using AbstractTrees
julia> a = (b=(c=(d=1,), e=(f=2,),),g=3)
(b = (c = (d = 1,), e = (f = 2,)), g = 3)
julia> AbstractTrees.Leaves(a) |> collect
ERROR: MethodError: no method matching nextind(::NamedTuple{(:d,),Tuple{Int64}}, ::Int64)
...
julia> Base.nextind(@nospecialize(t::NamedTuple), i::Integer) = Int(i)+1
julia> AbstractTrees.Leaves(a) |> collect
3-element Array{Int64,1}:
 1
 2
 3
```
Since `AbstractTrees` uses and extends `nextind` (https://github.com/JuliaCollections/AbstractTrees.jl/blob/a9c2121fa1913117388621d617b2b55c10d478ed/src/iteration.jl#L127). I thought that this would belong  in Base as `nextind` is already defined for `Tuple`.

**Comment by KristofferC** [comment]
> I thought that this would belong in Base as nextind is already defined for Tuple.

It's probably reasonable that it is defined for `NamedTuple`s as well then, I was just surprised it was defined for anything else than string when the docs say:

```
help?> nextind
search: nextind IndexCartesian MissingException InterruptException InvalidStateException

  nextind(str::AbstractString, i::Integer, n::Integer=1) -> Int
...
```

**Comment by dkarrasch** [comment]
Closed by https://github.com/JuliaLang/julia/commit/9405bf51a726a6383e6911eeb4235ba21ab3daee.
