### ISSUE TITLE
`sign(pi)` errors

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#37931]
Didn't find an existing issue
```
julia> sign(pi)
ERROR: InexactError: Bool(-1)
```
https://discourse.julialang.org/t/problem-with-sign-pi/47801/

**Comment by JeffBezanson** [comment]
What type should it return? Float64?

**Comment by Moelf** [comment]
that's the real question. I would say `Float64` since if one is using a `Real` number probably they are not dealing with integers in the rest of the expression anyways.

**Comment by PallHaraldsson** [comment]
Can you fix this with:
```
julia> import Base.sign

julia> sign(:Irrational{:π}) = true
```

i.e. why not with Bool?

I tried to fix for all (only two?) such constants, and all future ones:

```
julia> Revise.track(Base)

julia> sign(AbstractIrrational) = true
┌ Error: Failed to revise /home/pharaldsson_sym/julia-1.6-a0a68a54d6/share/julia/base/Base.jl
```

without the Revise command it ran, while ineffective, since Real is checked first? It there no way for it to be checked later?

**Comment by Moelf** [comment]
@PallHaraldsson you mean:
```
julia> sign(x::AbstractIrrational) = true
sign (generic function with 10 methods)
```

yeah, that could work actually

**Comment by simeonschaub** [comment]
> What type should it return? Float64?

Since `signed(true)` returns an `Int`, that seems like the most intuitive answer to me.

@Moelf Since `AbstractIrrational`s are also defined by packages like Tau.jl, I don't think it's safe to assume that an `AbstractIrrational` is always positive.

**Comment by Moelf** [comment]
@simeonschaub I see that's true, but in terms of Julia's representation, we can't really represent a negative irrational number. `-irr` will send it to `Float64`.

**Comment by simeonschaub** [comment]
I am not sure I follow. For example, you can do the following:
```
julia> Base.@irrational negpi -3.141592653589793 -big(pi)

julia> negpi
negpi = -3.141592653589...
```

**Comment by Moelf** [comment]
I'm saying that:
```
julia> dump(-3//5)
Rational{Int64}
  num: Int64 -3
  den: Int64 5
```
the sign is encoded in `num`, but the irrational number are "just" symbols.

**Comment by petvana** [comment]
As a user, I would expect that the following test is satisfied for any type. 
```julia
@test sign(pi) === -sign(-pi)
```

**Comment by PallHaraldsson** [comment]
Is this also bad? I'm just not sure:
```
julia> one(pi) === one(-pi)
false
```

**Comment by Moelf** [comment]
more reason to make everything about irrational just `Float64` because of:
```
-(x::AbstractIrrational) = -Float64(x)
```

**Comment by petvana** [comment]
This is also counterintuitive.
``` julia
julia> pi == one(pi) * pi
false

julia> zero(pi) == one(pi) * pi - pi
true
```

**Comment by PallHaraldsson** [comment]
The former is probably by design. Note:
```
julia> one(pi)*pi ≈ pi
true
```

**Comment by petvana** [comment]
> The former is probably by design. Note:

I have found in docs of `one()` 
``` julia
Return a multiplicative identity for `x`: a value such that
`one(x)*x == x*one(x) == x`.
```
So I have opened a separate issue for that.

**Comment by StefanKarpinski** [comment]
The only solutions to most of these complaints are to delete the `Irrational` type entirely or to turn it into a full blown symbolic system. These things are only meant to allow you to use `pi` with different precisions easily, not to do computer algebra.

**Comment by oscardssmith** [comment]
So what you're saying is that the only 1.0 compatible fix is adding a basic CAS? Should good to me :)
