### ISSUE TITLE
14 tests fail on AIX

### ISSUE THREAD

**Issue by trex58** [JuliaLang/julia#37953]
Version 1.40.0 

On AIX 7.2 TL3, compiling with GCC v8.4.0, both with 32bit and 64bit, there are 14 tests failing out of 388.
Though, on Fedora32/x86_64 and Fedora32/PPC64LE, 100% of 389 tests are OK.

Failing tests on AIX are:
  not ok 33 - fork_fs_events_child
  not ok 49 - fs_event_close_in_callback
  not ok 50 - fs_event_close_with_pending_event
  not ok 52 - fs_event_getpath
  not ok 53 - fs_event_immediate_close
  not ok 54 - fs_event_no_callback_after_close
  not ok 55 - fs_event_no_callback_on_close
  not ok 57 - fs_event_start_and_close
  not ok 58 - fs_event_watch_dir
  not ok 60 - fs_event_watch_file
  not ok 61 - fs_event_watch_file_current_dir
  not ok 62 - fs_event_watch_file_exact_path
  not ok 63 - fs_event_watch_file_twice
  not ok 140 - ip6_addr_link_local

**Comment by fredrikekre** [comment]
Wrong repo? https://github.com/libuv/libuv maybe?

**Comment by trex58** [comment]
Oh Yes !!
My fault. Sorry. Too many things in //.
I was talking of libuv.
