### ISSUE TITLE
Feature request: regex on byte vectors

### ISSUE THREAD

**Issue by kernelmethod** [JuliaLang/julia#37956]
(As discussed on https://discourse.julialang.org/t/regex-on-byte-vector/47754?u=kernelmethod)

Currently there isn't a great way for Julia to perform regular expressions against binary data; e.g. there isn't an implementation of `occursin(r::Regex, x::AbstractVector{UInt8})` or `match(r::Regex, x::AbstractVector{UInt8})` in the standard library that doesn't require either (i) mutating `x` by calling `String(x)` or (ii) creating a copy of `x`. In theory it should be possible to implement this, since it's supported by PCRE, and it's probably generally useful functionality for a variety of applications.

**Comment by kernelmethod** [comment]
If this is something y'all are okay with putting into the standard library, I'd be happy to take a stab at implementing it and opening a PR :)

**Comment by mgkuhn** [comment]
I think this feature request is a symptom of a far more wide-ranging problem that should be solved instead: namely that Julia stdlib still lacks a version of `String` suitable for processing binary and other non-UTF-8 string data, with all the facilities that `String` offers, including, but by far not limited to, regular expressions. I would therefore suggest that instead feature request #37979 is a more generic solution the the same problem, namely making the entire `AbstractString` API (including regex) easily available for processing byte sequences where Unicode is not of interest, by adding a binary sibling of `String` which could be called `BString`. Basically a 1 byte = 1 character version of `String` without a UTF-8 decoder running behind the scenes all the time. `Vector{UInt8}` (mutable) seems more a workaround for the lack of an immutable binary string type.

**Comment by stevengj** [comment]
Closed by https://github.com/JuliaStrings/StringViews.jl
