### ISSUE TITLE
some primitive-type objects of non-power-of-two size are not printed when even

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#37974]
```julia
julia> primitive type UInt24 24 end

julia> a = reinterpret(UInt24, UInt8[1, 0, 0, 2, 0, 0, 3, 0, 0, 4, 0, 0])
4-element reinterpret(UInt24, ::Vector{UInt8}):
 UInt24(0x000001)
 UInt24(0x000002)
 UInt24(0x000003)
 UInt24(0x000004)

julia> a[1]
UInt24(0x000001)

julia> a[2]

julia> a[3]
UInt24(0x000003)

julia> a[4]
```
One surprising thing is that if you re-eval a [`REPL.print_response`](https://github.com/JuliaLang/julia/blob/7f7ab69fd30e7ea57ffc1c6a8c803826bf02f838/stdlib/REPL/src/REPL.jl#L234) method, then everything is again printed as expected:
```julia
julia> @eval REPL function print_response(errio::IO, @nospecialize(response), show_value::Bool, have_color::Bool, specialdisplay::Union{AbstractDisplay,Nothing}=nothing)
 # ... cf. link above
end;

julia> a[2]
UInt24(0x000002)
```

This was not an issue in Julia 1.5.

**Comment by JeffBezanson** [comment]
Seems to be caused by the type `Tuple{UInt24, Bool}`, which we think is 4 bytes (with the Bool at offset 3), but LLVM thinks is 8 bytes (with the Bool at offset 4).

**Comment by vtjnash** [comment]
I think we need to go with LLVM here, though they are perhaps a bit inconsistent about it. In load/store it is exactly 3 bytes (https://llvm.org/docs/LangRef.html#store-instruction), but in struct layout, it is aligned by integer size class https://llvm.org/doxygen/DataLayout_8cpp_source.html#l00555, then the field size is padded out to that length.
