### ISSUE TITLE
no trunc/round/floor/ceil(T, x) for Real T

### ISSUE THREAD

**Issue by tomyun** [JuliaLang/julia#37984]
Not sure if this was intended, but there is no conversion allowed to Float64 (Float32 and maybe other Real) after applying `trunc()` with the type explicitly specified in the call arguments.

```
julia> trunc(Float64, 1.5)
ERROR: MethodError: no method matching trunc(::Type{Float64}, ::Float64)
Closest candidates are:
  trunc(::Type{UInt128}, ::Float64) at float.jl:678
  trunc(::Type{Int8}, ::Float64) at float.jl:678
  trunc(::Type{UInt32}, ::Float64) at float.jl:678
  ...
Stacktrace:
 [1] top-level scope at REPL[72]:1
```

The same goes for `round`, `ceil`, and `floor` and I think this behavior is inconsistent considering other similar uses.

```
julia> trunc(1.5)
1.0
```

```
julia> trunc(Float64, 3//2)
1.0
```

**Comment by Moelf** [comment]
so essentially there should be a:
```
Base.trunc(::Type{T}, x::T) where T<:Real = Base.trunc(x)
```
?

**Comment by vtjnash** [comment]
I think at some point we had `setrounding`, but that required LLVM support, which is currently limited. I think it could be implemented though as:
```
julia> function floor(::Type{T}, x) where T<:AbstractFloat
           y = convert(T, x)
           return y > x ? prevfloat(y) : y
       end
```
etc.

**Comment by Moelf** [comment]
I agree with: https://github.com/JuliaLang/julia/pull/45402#issuecomment-1135093515

`floor / ceil` should always go to integer (value), this is too confusing

**Comment by johnnychen94** [comment]
Close this since there's an agreement on this feature could introduce further confusion. But we could possibly mention `prevfloat` and `nextfloat` in the docstring as ref links.
