### ISSUE TITLE
Segmentation Fault while trying to install julia packages

### ISSUE THREAD

**Issue by tipanverella** [JuliaLang/julia#37996]
I am having some trouble using `julia` on this new linux machine (`kernel 2.6.32-754.33.1.1.e16.x86_64`, couple hundred GB of RAM, enough hard drive space) on which I have **limited** privileges, but do have `Anaconda` installed.  For instances, I am getting a **Segmentation Fault** while trying to install a simple package.  As you can see, I am able to update the installation, getting the `toml` files from github, but the later instruction to install `Pluto` fails in a less then verbose way.

```bash
(py3+) [nuwjtv5@rh6-rd-ho-cloudera-07 ~]$ bat packages.jl
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: packages.jl
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ using Pkg
   2   │ Pkg.update()
   3   │ Pkg.add("Pluto")
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
(py3+) [nuwjtv5@rh6-rd-ho-cloudera-07 ~]$ julia --version
julia version 1.5.2
(py3+) [nuwjtv5@rh6-rd-ho-cloudera-07 ~]$ julia packages.jl
 Installing known registries into `~/.julia`
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
   Updating registry at `~/.julia/registries/General`
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`
  Resolving package versions...
julia: /buildworker/worker/package_linux64/build/src/cgmemmgr.cpp:831: virtual uint8_t* {anonymous}::RTDyldMemoryManagerJL::allocateCodeSection(uintptr_t, unsigned int, unsigned int, llvm::StringRef): Assertion `!code_allocated' failed.

signal (11): Segmentation fault
in expression starting at /export/home/nuwjtv5/packages.jl:3
Segmentation fault
```

I don't know if this information will help but, I should also mention that **I can't get the REPL to launch. It just displays the banner and hangs!**

PS: I initially posted this as [a question on stackoverflow](https://stackoverflow.com/questions/64288941/segmentation-fault-while-trying-to-install-julia-packages)

**Comment by JeffBezanson** [comment]
It looks like the trick we use in the JIT memory manager to write code for later execution is not working. It could be related to running with a very old linux kernel, or maybe a permissions issue as you guessed.

**Comment by tipanverella** [comment]
1. Is there a way for me to turn on some verbose version of julia in order to get more information, perhaps before it gets to whatever is causing the Segmentation Fault?
2. Would it be possible to leverage Anaconda to circumvent the old kernel?

**Comment by tipanverella** [comment]
any updates on this issue?

**Comment by StefanKarpinski** [comment]
There's not really enough information here to diagnose. What Linux kernel are you running? The output `uname -a` would be helpful. There are not any verbose flags that I'm aware of that would help. You could try compiling a debug build of Julia, but if this is a page fault problem, that's unlikely to produce useful info. You could try producing an rr trace with `julia --bug-report=rr`.
