### ISSUE TITLE
Shadowing of base methods is allowed in functions with no warning/error

### ISSUE THREAD

**Issue by RomansWorks** [JuliaLang/julia#38022]
Hello and thank you for the great work on Julia! 

I'm a new user, so hopefully not re-raising old issues. I've tried looking for the exact issue in github / discourse but found that most reports seem to address the shadowing of a method by a variable in the global scope, which indeed immediately produces an error:

```
julia> values = [1,2,3]
ERROR: cannot assign a value to variable Base.values from module Main
Stacktrace:
 [1] top-level scope at REPL[31]:1
```

But if we're within a function then shadowing is allowed, and in the best case we get a confusing (to a new user) error only later, on first application:
```
function SurprisingFunc(values::Vector{Int64})
       counts = Dict()
       # ...
       values(counts)
end
SurprisingFunc([1,2]) 
```
Results in:
```
ERROR: MethodError: objects of type Array{Int64,1} are not callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] SurprisingFunc(::Array{Int64,1}) at ./REPL[1]:4
 [2] top-level scope at REPL[2]:1
```

Why the different behaviour inside and outside of functions?

IMHO it'd be very helpful if this caused an error or a warning immediately on definition.

If it's expected to work, is there something like a *strict mode* in Julia that I can turn on to weed these kind of situations? 

Julia Version 1.5.2

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
