### ISSUE TITLE
Show rodata values in code_native

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#38035]
When running

```julia
julia> @code_native debuginfo=:none ((x,y) -> muladd(3.0, x, y))(1.0, 2.0)
	.text
	movabsq	$.rodata.cst8, %rax
	vfmadd132sd	(%rax), %xmm1, %xmm0 # xmm0 = (xmm0 * mem) + xmm1
	retq
```

would it be possible to print the value of `$.rodata.cst8` in a comment, similar to how a comment is generated to explain the fma instruction?

**Comment by vchuravy** [comment]
I think we are using the LLVM infrastructure to print the assembly so the change would need to happen there first,

**Comment by vtjnash** [comment]
There is some code in our system there to print it out, but currently it's only the fallback case if disassembly fails. I'd like to make it the default at some point, but it doesn't currently allow us to print line number information at the same time.

**Comment by mkitti** [comment]
I am really interested in seeing the rodata values as well. Could you point to 

>  some code in our system there to print it out

?
