### ISSUE TITLE
Should Julia Unicode normalize strings, for Dicts (and Sets)?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#38040]
```
julia> Dict("Páll" => 1, "Pa\u0301ll" =>2)  # My name, and with postcomposed:
Dict{String, Int64} with 2 entries:
  "Páll" => 2    # also gets confused about alignment, counts as one more letter, why two spaces on next line...:
  "Páll"  => 1
```

I'm thinking isn't really desirable to allow both, for the "same" string. Would disallowing prevent a bug, or allowing, the status quo be a bug (maybe a potential security bug?)?

I see we're in good (bad?) company with my (non-latest) Python 3.6.9 (maybe in Python it's more common to normalize text on I/O?):

```
>>> {"Páll": 1, "Pa\u0301ll": 2}
{'Páll': 1, 'Páll': 2}
```

This could be done by a new hash just for Dicts and Sets (or change hash itself?), in effect doing:

```
julia> using Unicode
julia> hash(Unicode.normalize("Páll"))  # to get same hash as for "Páll"
0x2dc1e803e8f852f4
```

Does normalize allocate, and if, would it be possible to do the hash (fast) on the fly while normalizing, without allocating?

B.
This might be an error, not allowing those valid strings:
```
julia> Dict("Åström" => 3, "Åström" = 4)
ERROR: syntax: invalid keyword argument name ""Åström"" around REPL[6]:1
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1
```

FYI: I wasn't aware there's a "Julia Language Pedia", at: https://julia-lang.programmingpedia.net/en/tutorial/7612/string-normalization

**Comment by yuyichao** [comment]
`"Páll" == "Pa\u0301ll"` so neither `Dict` nor `Set` should behave differently without changing this.

`ERROR: syntax: invalid keyword argument name ""Åström"" around REPL[6]:1` Not sure what you want to show here, or if you missed a ">".

**Comment by KristofferC** [comment]
>This might be an error, not allowing those valid strings:
>
>```jl
>julia> Dict("Åström" => 3, "Åström" = 4)
> ERROR: syntax: invalid keyword argument name ""Åström"" around REPL[6]:1
>```

Why do you think this is an error? Did you mean to do `=>` in the last one as well?

**Comment by PallHaraldsson** [comment]
>"Páll" == "Pa\u0301ll"

I think you mean:

"Páll" != "Pa\u0301ll", an argument against normalizing. Or is it not? Maybe it can't be a security bug (then I'm less worried), just a bug. You consider it a bug to introduce normalization? It could be documented intended behaviour. And you could always do differently in a package, in case you want old behaviour.

B.
I just had a typo in part B. so it's not the error I thought it was (while the message could be improved).

**Comment by yuyichao** [comment]
> "Páll" != "Pa\u0301ll"

Yes I meant to include the return value `false` = = ...

> an argument against normalizing

It's not an argument for either but the two **must** be consistent. If you want to normalize it for `Dict` the only way is to make the strings equal.

> You consider it a bug to introduce normalization?

No, but it's a bug to do one (`Dict`) but not the other (`==`) and it's a breaking change to do either.

> while the message could be improved

= = .... It's pretty clearly stating that you are trying to use a keyword argument. I don't really see how it can reliably guess what error you make...

**Comment by KristofferC** [comment]
And doing normalization on strings for Julia is on the wrong level. If people want to normalize, they can create a string type that normalizes or calls normalization at suitable points.
