### ISSUE TITLE
pdf manual 1.5.2 links

### ISSUE THREAD

**Issue by gsigut** [JuliaLang/julia#38054]
It seems that the links to chapters / paragraphs are pointing to the last page instead of the relevant chapter.

**Comment by apparluk** [comment]
File name: julia-1.5.2.pdf
File size: 4.41 MB (4,626,453 bytes)
Title: -
Author: -
Subject: -
Keywords: -
Creation Date: 9/24/2020, 6:57:03 PM
Modification Date: 9/24/2020, 6:57:03 PM
Creator: LaTeX with hyperref package
PDF Producer: LuaTeX-1.0.4
PDF Version: 1.5
Page Count: 1335
Page Size: 215.9 × 279.4 mm (Letter, portrait)
Fast Web View: No

**Comment by strickek** [comment]
Yes, e.g. in [Multi-Threading](https://raw.githubusercontent.com/JuliaLang/julia/master/doc/src/manual/multi-threading.md)
there is a link to the environment variable
[\`JULIA_NUM_THREADS\`](@ref JULIA_NUM_THREADS)
pointing to page 1315 instead of 324.
