### ISSUE TITLE
zero is not recursive

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#38064]
An array of arrays is a valid vector space.
Even an array of arrays of different sizes.

This is why we define `transpose`, `adjoint`, `dot` and `+` recursively

However we do not do the same for `zero`, which is a fundermental vector space operation.

```julia
julia> zero([2,2])
2-element Array{Int64,1}:
 0
 0

julia> zero([[2,2], [3,3,3]])
ERROR: MethodError: no method matching zero(::Type{Array{Int64,1}})
```

This is a problem for AD purposes.
Types that are used to represent a tangent/cotangent need to have the basic vector space operations defined on them.
So if we want to say that the cotangent of an array of arrays of numbers is an an array of arrays of numbers then we should really have `zero` on it

**Comment by Jutho** [comment]
It would be great to have a formal vector space interface for generic julia types. In a different context than AD, over at KrylovKit.jl, I also tried to formalize the set of methods that a type needs to satisfy in order for it to be used in the KrylovKit.jl methods. I there chose to use `*(scalar::Number, v::SomeTypeWithVectorBehavior)` to create new zero vectors (i.e. by multiplying with the scalar `0`), where possibly promotion of the underlying scalar type goes on. Do the AD packages have such an interface specified?

**Comment by oxinabox** [comment]
This is the wrong venue for that discussion.
Let's talk on Zulip

**Comment by Jutho** [comment]
You are absolutely right, my apologies for sidetracking. I'll try to find you on Zulip.

**Comment by martinholters** [comment]
Just
```julia
zero(x::AbstractArray{T}) where {T} = map!(zero, similar(x), x)
```
? Some very brief benchmarking indicates that this might be around 10% slower for `x` being a numerical array, so keeping the old version (which uses `fill!`) around for `T<:Number` could be considered, but needs a bit more thorough benchmarking to make that call.
