### ISSUE TITLE
Install JuliaPro

### ISSUE THREAD

**Issue by ardsatcg** [JuliaLang/julia#38084]
I'got this warning, even  i deleted all previous file

![Screenshot 2020-10-18 105055](https://user-images.githubusercontent.com/71117550/96357804-f3211280-1132-11eb-8753-f3fb021be397.png)

#38084

**Comment by Keno** [comment]
Hi there, this is the issue tracker for open source Julia. For JuliaPro, please either contact Julia Computing support if you have a support contract or alternatively, you want to file an issue here: https://github.com/JuliaComputing/JuliaProIssues. However, we'll likely need some more info to debug your issue, so please include more information on what you tried. In this case, I assume you tried to delete JuliaPro, but the installation information is still in the registry (as is common for windows software), but it's hard to debug from just the screenshot,.

**Comment by ardsatcg** [comment]
> Hi there, this is the issue tracker for open source Julia. For JuliaPro, please either contact Julia Computing support if you have a support contract or alternatively, you want to file an issue here: https://github.com/JuliaComputing/JuliaProIssues. However, we'll likely need some more info to debug your issue, so please include more information on what you tried. In this case, I assume you tried to delete JuliaPro, but the installation information is still in the registry (as is common for windows software), but it's hard to debug from just the screenshot,.

This has been solve with regedit ( registry editor )
