### ISSUE TITLE
Julia corruption, maybe implicating Unicode handling and/or VS Code

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#38082]
Hi,

I'm not sure were/if I should report such a strange corruption. It's in my master from the 10th, maybe fixed now. I'll keep the REPL open, in case there something to do. @Keno you're good with debugging, I read your recent blog, but you can't run rr retroactively? Is it helpful to force a coredump and some way of reading that? See screenshot here, with much more details:

https://github.com/timholy/Revise.jl/issues/561#issuecomment-711095495

E.g. what's NOT expected (and e.g. the screen corruption):
```
julia> 1+1

julia> 2+2
577
```

@stevengj You're the main Unicode guy? That's the main thing I was doing differently than before, see link.

@davidanthoff You're the main VS Code guy? I thought you would like to see this, since it affects the VS Code user interface, or the REPL part of it. What does that mean if anything for VS Code or Julia's extension for it? Probably nothing. They share adress space, why this is even possible.

**Comment by PallHaraldsson** [comment]
It might be related to running:
```
length(""> < >= ≥ <= ≤ == === ≡ != ≠ !== ≢ ∈ ∉ ∋ ∌ ⊆ ⊈ ⊂ ⊄ ⊊ ∝ ∊ ∍ ∥ ∦ ∷ ∺ ∻ ∽ ∾ ≁ ≃ ≂ ≄ ≅ ≆ ≇ ≈ ≉ ≊ ≋ ≌ ≍ ≎ ≐ ≑ ≒ ≓ ≖ ≗ ≘ ≙ ≚ ≛ ≜ ≝ ≞ ≟ ≣ ≦ ≧ ≨ ≩ ≪ ≫ ≬ ≭ ≮ ≯ ≰ ≱ ≲ ≳ ≴ ≵ ≶ ≷ ≸ ≹ ≺ ≻ ≼ ≽ ≾ ≿ ⊀ ⊁ ⊃ ⊅ ⊇ ⊉ ⊋ ⊏ ⊐ ⊑ ⊒ ⊜ ⊩ ⊬ ⊮ ⊰ ⊱ ⊲ ⊳ ⊴ ⊵ ⊶ ⊷ ⋍ ⋐ ⋑ ⋕ ⋖ ⋗ ⋘ ⋙ ⋚ ⋛ ⋜ ⋝ ⋞ ⋟ ⋠ ⋡ ⋢ ⋣ ⋤ ⋥ ⋦ ⋧ ⋨ ⋩ ⋪ ⋫ ⋬ ⋭ ⋲ ⋳ ⋴ ⋵ ⋶ ⋷ ⋸ ⋹ ⋺ ⋻ ⋼ ⋽ ⋾ ⋿ ⟈ ⟉ ⟒ ⦷ ⧀ ⧁ ⧡ ⧣ ⧤ ⧥ ⩦ ⩧ ⩪ ⩫ ⩬ ⩭ ⩮ ⩯ ⩰ ⩱ ⩲ ⩳ ⩵ ⩶ ⩷ ⩸ ⩹ ⩺ ⩻ ⩼ ⩽ ⩾ ⩿ ⪀ ⪁ ⪂ ⪃ ⪄ ⪅ ⪆ ⪇ ⪈ ⪉ ⪊ ⪋ ⪌ ⪍ ⪎ ⪏ ⪐ ⪑ ⪒ ⪓ ⪔ ⪕ ⪖ ⪗ ⪘ ⪙ ⪚ ⪛ ⪜ ⪝ ⪞ ⪟ ⪠ ⪡ ⪢ ⪣ ⪤ ⪥ ⪦ ⪧ ⪨ ⪩ ⪪ ⪫ ⪬ ⪭ ⪮ ⪯ ⪰ ⪱ ⪲ ⪳ ⪴ ⪵ ⪶ ⪷ ⪸ ⪹ ⪺ ⪻ ⪼ ⪽ ⪾ ⪿ ⫀ ⫁ ⫂ ⫃ ⫄ ⫅ ⫆ ⫇ ⫈ ⫉ ⫊ ⫋ ⫌ ⫍ ⫎ ⫏ ⫐ ⫑ ⫒ ⫓ ⫔ ⫕ ⫖ ⫗ ⫘ ⫙ ⫷ ⫸ ⫹ ⫺ ⊢ ⊣ ⟂ <: >:")
```

I strongly implicate this line or the similar one without the extra quote and thus no syntax error, as the pattern matches the "dead pixel pattern" on the screen.

**Comment by KristofferC** [comment]
577 is exactly the result of the length of that string (after changing the double `""`) so it looks like some display issue. Have you reproduced this in a normal julia session? Until that, I think we can chalk it up to perhaps some terminal weirdness in VSCode. Nothing seems to indicate a Julia bug at least. Feel free to provide more info and how to reproduce and the issue can be reopened.

**Comment by Keno** [comment]
Revise messes with the REPL and has been known to cause this behavior (answers not showing up until later evaluations) before.

**Comment by timholy** [comment]
> Revise messes with the REPL and has been known to cause this behavior (answers not showing up until later evaluations) before.

It doesn't anymore: https://github.com/timholy/Revise.jl/blob/7ccd9c0ee0e80168eca9a17c6723e92c9df2d782/src/packagedef.jl#L1292-L1297

But if folks are still calling the `_steal_backend` methods from their `startup.jl` files, that could explain it.

**Comment by PallHaraldsson** [comment]
>577 is exactly the result of the length of that string

That's very good insight I didn't notice, and puts this partially into perspective.

>Revise messes with the REPL and has been known to cause this behavior

Yes, the out of order part. So I'm going to assume Revise is at fault until proven otherwise, BUT only for that part. I doubt it can, alone, affect the "dead pixel" issue. I'm posting the screenshot again here, in case people didn't click the link:

![image](https://user-images.githubusercontent.com/8005416/96355749-de159680-10d4-11eb-8f84-3cfc367d5ef4.png)

>But if folks are still calling the _steal_backend methods from their startup.jl files, that could explain it.

I'm not, directly at least, I'm first now hearing about "_steal_backend methods". Could Atom be doing this (note, I did put VS Code in the title, meaning to put Atom/Juno... only the latter is implicated) wih some interaction with Revise?

My startup file:
```
atreplinit() do repl
    try
        @eval @time using Revise
    catch e
        @warn "error while importing Revise" e
    end
end
atreplinit() do repl
    try
        @eval @time using OhMyREPL
    catch e
        @warn "error while importing OhMyREPL" e
    end
end
```

**Comment by timholy** [comment]
You don't need the `atreplinit` part, but I don't think it hurts either.

If you used Revise before 1.5, and had it start up automatically, you *had* to be using one of the `_steal_backend` methods. See, for example, Revise's docs for the 2.0 release: https://timholy.github.io/Revise.jl/v2.0/config/

**Comment by PallHaraldsson** [comment]
I do have:
```
(@v1.6) pkg> st Revise
Status `~/.julia/environments/v1.6/Project.toml`
  [295af30f] Revise v3.1.2 `~/.julia/dev/Revise`
```

I meant to keep Juno open, in case helpful for debugging, but I accidentally closed its REPL, since I was getting no answer:

![image](https://user-images.githubusercontent.com/8005416/96453874-9bee7100-120a-11eb-96af-696b66d087da.png)

Tim, what do you think about the "imprint"? I can still scroll for REPL history, but the imprint doesn't move with it, and for me at least it implicates the Unicode stuff I typed in way earlier. I just doubt Revise alone can have this effect?!

**Comment by pfitzseb** [comment]
Please open an issue over at https://github.com/JunoLab/Juno.jl (and https://github.com/julia-vscode/julia-vscode if applicable) about this.

**Comment by yha** [comment]
> 577 is exactly the result of the length of that string (after changing the double `""`) so it looks like some display issue.

Perhaps that means it's the same issue as https://github.com/JuliaLang/julia/issues/34598?
