### ISSUE TITLE
Transposes and adjoints of triangular matrices

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaLang/julia#38093]
Is there a reason why in `LinearAlgebra` transposes and adjoints of triangular matrices are not triangular matrices themselves? For example why transpose of an `UpperTriangular` matrix is not a `LowerTriangular` matrix that wraps transpose of the original matrix. 

`StaticArrays` does commute these two wrappers as the issue was raised here: https://github.com/JuliaArrays/StaticArrays.jl/pull/837#discussion_r506040427 . Essentially all algorithms that work on triangular matrices could also work on transposes and adjoints of them but not commuting these two wrappers makes it harder to dispatch on matrices with triangular structure.

**Comment by dkarrasch** [comment]
As it turns out, this is what it used to be and got changed in #25364. In that gigantic PR, this was just a small detail and I believe there was no deeper reason to flip the order of the two lazy wrappers. I started changing it, so hopefully will have a PR soon.
