### ISSUE TITLE
Base.compilecache_path is misbehaving

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#38101]
As a pure function of the inputs, I'm not sure why this is no longer giving the same answers:
```julia
julia> Base.compilecache_path(Base.identify_package("Pkg"))
"/home/vtjnash/.julia/compiled/v1.6/Pkg/tUTdb_75wtU.ji"

julia> Base.compilecache_path(Base.identify_package("Pkg"))
"/home/vtjnash/.julia/compiled/v1.6/Pkg/tUTdb_Y4Mh0.ji"
```

**Comment by KristofferC** [comment]
Could you put some `@show` around https://github.com/JuliaLang/julia/blob/b08ad36f159d0dfc24a872e00a7805d72d78b63d/base/loading.jl#L1286-L1291 to see what is different between the invocations?

**Comment by KristofferC** [comment]
```
julia> Base._crc32c(0x6635934445471676, 0x5202ff58)
0x8b058d60

julia> Base._crc32c(0x6635934445471676, 0x5202ff58)
0x2bcaa1e5

julia> Base._crc32c(0x6635934445471676, 0x5202ff58)
0xdc2d7c70
```

https://github.com/JuliaLang/julia/blob/7efae4b2f3217b5e7ecd3051dd85758795f8600b/base/util.jl#L390-L391 might be bugged?

cc @staticfloat
