### ISSUE TITLE
Make it easier to use "inner type parameters" in wrapper types.

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#38111]
This might be a duplicate of https://github.com/JuliaLang/julia/issues/36377, not sure.

Suppose I want to make a type
```
struct Foo{I <: Integer}
    v::Vector{Complex{I}}
end
``` 
Now, at runtime, I have a vector of integer `Complex`, but I don't know *which* integer type, so I can just make an abstractly typed array:
```
julia> v = Complex{<:Integer}[Complex{Int}(1, 1)]
1-element Array{Complex{var"#s16"} where var"#s16"<:Integer,1}:
 1 + 1im
```
But now, how do I wrap `v` in a `Foo`?
```
julia> Foo{<:Integer}(v)
ERROR: MethodError: no method matching Foo{var"#s12"} where var"#s12"<:Integer(::Array{Complex{var"#s16"} where var"#s16"<:Integer,1})
```
One workaround is to instead define
```
struct Foo{C <: Complex{<:Integer}}
    v::Vector{C}
end
```
But I think having `Complex` as part of `Foo`'s signature is unnecessary. Would it be possible to enable the "direct" use of `<:Integer` in this case?

**Comment by JeffBezanson** [comment]
Basically, no --- it's possible to define a constructor for `Foo{<:Integer}(v)`, but that constructor would still have to return an instance of a concrete type, so it would still have to pick a specific value for `I`.

**Comment by jakobnissen** [comment]
Ah, I see. So the reason for having to have the wrapper type `Complex` in `Foo{C <: Complex{<:Integer}}` is that `Foo{<:Integer}` is a UnionAll type whereas `Foo{Complex{<:Integer}}` is concrete.

Thanks for answering this, closing the issue.
