### ISSUE TITLE
Precompile fails when multiple methods fit the supplied signature

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#38149]
This is a more in-depth explanation of the precompile failures seen in `Case 4` in https://github.com/JuliaLang/julia/issues/28808#issuecomment-712472418.

`precompile(f, (Any,...))` fails incorrectly for methods marked `@nospecialize` when the function in question has other, more specific methods defined.

An explanation follows.

-----

As you can see, here, `precompile` works correctly for `@nospecialize` functions, when there is only one method:
```julia
julia> using MethodAnalysis

julia> module M
       @nospecialize
       foo(x, y) = x+y
       end
Main.M

julia> precompile(M.foo, (Any,Any))  # returns `true`, as expected.
true

julia> MethodAnalysis.methodinstances(M.foo)  # the new MethodInstance has been specialized and compiled:
1-element Array{Core.MethodInstance,1}:
 MethodInstance for foo(::Any, ::Any)

julia> M.foo(2.0, 3)  # you can call it with some arguments, and it works, and...
5.0

julia> MethodAnalysis.methodinstances(M.foo)   # ... doesn't create a new specialization
1-element Array{Core.MethodInstance,1}:
 MethodInstance for foo(::Any, ::Any)
```

However, when the function contains _multiple methods_, with one more specific than the other, `precompile(foo, (Any,Any))` *fails*, incorrectly:

```julia
julia> using MethodAnalysis

julia> module M
       @nospecialize
       foo(x, y) = x+y         # (::Any, ::Any)
       foo(a::Int, b) = a+b    # (::Int, ::Any)
       end
Main.M

julia> precompile(M.foo, (Int,Any))  # This one specializes correctly ✔️
true

julia> precompile(M.foo, (Any,Any))  # 😱 But this one fails incorrectly! 😱 
false

julia> MethodAnalysis.methodinstances(M.foo)  # And we can see it failed to create a new MethodInstance for (Any,Any)
1-element Vector{Core.MethodInstance}:
 MethodInstance for foo(::Int64, ::Any)

julia> M.foo(2.0, 3)  # Even though when we actually _call_ it, it of course must create the MethodInstance:
5.0

julia> MethodAnalysis.methodinstances(M.foo)  # Now it's there, indeed.
2-element Vector{Core.MethodInstance}:
 MethodInstance for foo(::Int64, ::Any)
 MethodInstance for foo(::Any, ::Any)
```

This causes several static compilation failures in our production binary, meaning we end up compiling them again in production. 

I tried stepping through the function in GDB to identify what's going on, and `precompile(M.foo, (Any,Any))` ends up returning false on 2928, here:
https://github.com/JuliaLang/julia/blob/12328e272fbdf904d1a45d704891a3b0831cf477/src/gf.c#L2924-L2931

Hopefully this helps someone make sense of the failure? I couldn't quite make sense of it myself.

Thanks!

**Comment by timholy** [comment]
You can force both to be cached using the pattern in #41958

**Comment by NHDaly** [comment]
@timholy, I guess this doesn't exactly solve the issue here, because currently the `trace-compile` Precompile statement emitter emits precompile statements that look like the one I described in the issue.

So I guess we could either:
- Change the precompile statement emitter to emit statements that use a non-matching type, as you've done in #41958. But this seems fragile, because the other methods be defined _later_ in the package compilation process, and it might end up colliding with one of those. I guess we could make up a type internal to the precompile statement emitter and use that?
- Fix the implementation of `precompile()` so that it works for the case currently emitted.


Do you have a sense for which one of those would be easier? I'm going to re-open the issue for now, since I think the suggestion you've provided won't help until we do one of the above.

**Comment by timholy** [comment]
Probably the most robust approach would be to pick the least-specific method. Start checking here: https://github.com/JuliaLang/julia/blob/8987bc270cb0c0e0265ff265ba9cf6b3f697c14c/src/precompile.c#L390

**Comment by NHDaly** [comment]
Thanks Tim. Just to confirm my understanding: that would be the approach to fix it in `precompile()` itself?

**Comment by vtjnash** [comment]
In principle, we should probably just iterate all matches, rather than getting exactly one match from jl_get_specialization1
