### ISSUE TITLE
[FR] MPTCP-awareness and FastCGI in Sockets.jl / HTTP.jl

### ISSUE THREAD

**Issue by mkschulze** [JuliaLang/julia#38166]
Hello,

I currently learn terminology about network I/O and stumbled on two concepts, that might be an interesting addition to the Julia Web and/or Network stack.

1. Multipath TCP 
2. FastCGI

I collected some sources over at discourse: https://discourse.julialang.org/t/multipath-tcp-awareness-in-sockets-jl/48952

I'm not really able to contribute more with my current skill level, but maybe this could lead to further discussion or evaluation. 

thx

**Comment by yuyichao** [comment]
IIRC (ref https://github.com/multipath-tcp/mptcp/issues/217) the API is identical to that of a normal socket. You just need to change either a global option or a socket spcific option and no API change is needed.

**Comment by StefanKarpinski** [comment]
FastCGI is very much outside of the scope of Base Julia.

**Comment by StefanKarpinski** [comment]
I'm going to close this since:

* MPTCP is too low level to be relevant: it is a kernel-level network stack feature — if you have an OS kernel that supports it, nothing else needs to change.
* FastCGI is too high level to be relevant: it is an application-level protocol for letting programs handle HTTP requests, which can be implemented in a package, if someone wants it.

**Comment by mkschulze** [comment]
well, judging by the [RFC 6897](https://www.rfc-editor.org/info/rfc6897) Multipath TCP (MPTCP) Application Interface Considerations, the applications also need to be made aware of this underlying network extension. As long as the TCP server listens only to a single adress or interface it is not aware. The Kernel must provide the extension and the application needs to be made aware of it.

As far as I understand the connect and accept method in sockets.jl only handles single adresses.

> 
> REQ1:  Turn on/off MPTCP: An application should be able to request to
>           turn on or turn off the usage of MPTCP.  This means that an
>           application should be able to explicitly request the use of
>           MPTCP if this is possible.  Applications should also be able
>           to request not to enable MPTCP and to use regular TCP
>           transport instead.  This can be implicit in many cases, since
>           MPTCP must be disabled by the use of binding to a specific
>           address.  MPTCP may also be enabled if an application uses a
>           dedicated multipath address family (such as AF_MULTIPATH
>           [20]).

> Cited from that RFC document:
> The de facto standard API for TCP/IP applications is the "sockets"
>    interface [8].  This document provides an abstract definition of
>    MPTCP-specific extensions to this interface.  **It is up to the applications, high-
>    level programming languages, or libraries to decide whether to use
>    these optional extensions.**

**Comment by StefanKarpinski** [comment]
Once there's good kernel support, the next step would be for libuv to add support for it. Once that's one, it would be straightforward to add multi-IP methods in Sockets. If someone wants to support this, the next step would be to look at whether there has been and discussion of / work towards multipath support in libuv.
