### ISSUE TITLE
Confusing Julia & JuliaPro Environment Variables

### ISSUE THREAD

**Issue by ardsatcg** [JuliaLang/julia#38170]
Sorry for ask this, in the docs.julialang.org, the environment variables is too complex for me to understand, what should i add for Julia & JuliaPro for  Environment Variables  ( in windows 10 ) ?

"The languange is nice, but the docs is too complex to eats ( just env. variables )"
#38169

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
