### ISSUE TITLE
Code coverage stopped working?

### ISSUE THREAD

**Issue by dkarrasch** [JuliaLang/julia#38173]
It seems like on both coverage sites, the last commit on which coverage was tracked is https://github.com/JuliaLang/julia/commit/62eda52b39c95f4fd61b002afb4177eaf4271f4b 20 days ago, and the first untracked one is https://github.com/JuliaLang/julia/commit/08a233ddac2c0bcb07ca8a66792e8305a6124d3c, but I don't see how any of the two could have affected the transmission of coverage reports.

**Comment by KristofferC** [comment]
I think there was some change to the coverage buildbot not too long ago.

**Comment by DilumAluthge** [comment]
@staticfloat @vtjnash

**Comment by laborg** [comment]
I guess this has just been forgotten.
