### ISSUE TITLE
Markdown parser fails for tables with no first entry

### ISSUE THREAD

**Issue by Ellipse0934** [JuliaLang/julia#38189]
```
julia> using Markdown

julia> md"""|   | 1 | 2 |    # fails to parse as table
            |:-:|:--|--:|
            |3  |4  |5  |"""
  | | 1 | 2 | |:-:|:–|–:| |3 |4 |5 |

julia> md"""| 0 |   |   |
            |:-:|:--|--:|
            |3  |4  |5  |"""
  0    
  – – –
  3 4 5

julia> md"""| 0 |   |   |
            |:-:|:--|--:|
            |   |4  |5  |"""
  0    
  – – –
    4 5
```

**Comment by p1scescom** [comment]
Tables which have empty first column of markdown fail. Its reason is this line.

https://github.com/JuliaLang/julia/blob/b00802bc5ff96e5eb059578b2188196e05fef70f/stdlib/Markdown/src/GitHub/table.jl#L48

I sought this line's blame. But I cannot find why it fails.
Maybe it has to fail in this case, but I think this line isn't necessary.
