### ISSUE TITLE
Julia documentation search feature needs to be improved

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#38238]
The search function on https://docs.julialang.org is IMHO not very good. Some examples:
- searching for operators like `^` or `&&`  simply does not give any useful results at all
- OK, maybe I have to search for `Base.^` or `Base.:^`? Nope, does not work either
- Interestingly, searching for `Base.!=` gives me a correct hit, but at about position 15 or so of the search results (number 1 is for some reason `Base.fd`?)
- but what I really wanted to find is `Base.literal_pow`, which is mentioned in the documentation for `Base.:^`, so let's search for that; oh yeah, that gives the right result -- but again only at position 10 or so of the search results
- though searching for `literal_pow` *does* work right, at least something.

I'll try to add more concrete examples as I come across them; but I've really struggled many times to find stuff in the Julia manual, even when I *know* it is there.

**Comment by fredrikekre** [comment]
I don't think there is anything actionable here, seems like a Documenter issue?

**Comment by KristofferC** [comment]
Yep, please reopen at Documenter.jl (also look if there is an existing issue open about it).

**Comment by fingolfin** [comment]
From my perspective it's a Julia issue in so far as it makes the already relatively sparse and incomplete Julia documentation even less accessible. But OK, I'll reopen at Documenter.jl

**Comment by fingolfin** [comment]
See https://github.com/JuliaDocs/Documenter.jl/issues/1457
