### ISSUE TITLE
Improve Base.^ documentation to state that `x^N` may be transformed into `inv(x)^N` and how to prevent it

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#38230]
By default, expressions of the form `x^-N` with `N` an integer literal are transformed via `literal_pow` into `inv(x)^N`. I've stumbled over this before when implementing arithmetic for non-number types (e.g. group elements) where this can be undesirable (even in cases where it is a valid transformation it may lead to less efficient code). Just today my PhD student also learned about it the hard way (luckily at some point he mentioned it to me and so I could help him along with what I learned in the past).

As it is, the documentation for Base.^ already mentions `literal_pow`, but not that `literal_pow` performs this transformation by default. It would be nice if it was explicitly mentioned there and ideally perhaps there could even be a hint on how to disable it for a given type.

**Comment by fingolfin** [comment]
Of course it would also be nice if `literal_pow` was documented (see issue #28685) but this is IMHO orthogonal: I'd really prefer if the `Base.^` documentation mentioned this "feature". But of course if `literal_pow` was documented, then Base.^ could refer there for "the full details".

**Comment by DebadityaPal** [comment]
I would like to work on this.
