### ISSUE TITLE
getproperty and sum on missing

### ISSUE THREAD

**Issue by babaq** [JuliaLang/julia#38243]
when I do DataFrame manipulation(Julia v1.5.2), I found that `getproperty(x, f)` and `sum(x)`, if `x` is missing, are not defined(throw error).
I could easily add methods to handle these situations(return missing), but out of curiosity, I am wandering if this kinds of behavior are general enough to be included in the Base.

**Comment by pdeffebach** [comment]
This kind of feature probably won't get added to Base, but Missings.jl has the function `passmissing`. `passmissing(getproperty)(missing, :t)` will return `missing`.

**Comment by babaq** [comment]
I see, `passmissing` is the general solution for any function, I just really like the convenient of dot(getproperty), for my use case, `A.B.C`

**Comment by KristofferC** [comment]
You can write a macro for it, e.g. `@propagate A.B.C`. `getproperty` is too low level for something like missing propagation.
