### ISSUE TITLE
add message when the broken precompilation could be caused by including a file twice or more

### ISSUE THREAD

**Issue by longemen3000** [JuliaLang/julia#38248]
when compiling a package, there is a precompilation error if a method is defined twice in different parts of the package:

```julia
f(x::Float64) = 2x
....
f(x::Float64) = 3x
```

but there is other case that i've seen commonly, and that is when a file is included twice or more:
```julia
include("file1.jl")
...
include("file1.jl")
```
in this case, the precompilation warning shows that the overwriting method is in the same location. this error message doent help diagnose the problem, specially for novice users that don't know about the precompilation process. It is possible to add a message about informing the possibility of that file included more than one time?

**Comment by timholy** [comment]
Sounds like a fine idea. Do you have a suggestion for how it should read?

**Comment by ericphanson** [comment]
This should be improved on master: https://github.com/JuliaLang/julia/pull/36609/files#diff-9a718f382a240acdbe9d0bdbc3ffb521f67af0e62b2ba8c8594b8faa65c78014R1321
