### ISSUE TITLE
Should lpad/rpad be defined in terms of textwidth instead of code units or have the option to do so?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#38256]
One of the main use cases of `lpad` and `rpad` is, at least for me personally, to align things in the terminal. However, `lpad` and `rpad` are defined (and documented) to work in terms of code units (i.e. they call `length` on the input string) which means that when `length` and `textwidth` disagree, you get unaligned output:

```
julia> s1 = "⟨k|H₁|k̃⟩"
"⟨k|H₁|k̃⟩"
julia> s2 = "⟨k|H₁|k⟩"
"⟨k|H₁|k⟩"
julia> textwidth(s1), textwidth(s2)
(8, 8)
julia> rpad(s1, 12) |> textwidth
11
julia> rpad(s2, 12) |> textwidth
12
```

This can cause bugs like https://github.com/KristofferC/TimerOutputs.jl/issues/94.

Two points of discussions:

- Should the default be changed to use `textwidth` instead of `length`? Perhaps too much of a breaking change.
- Should there be an option to use `textwidth`, e.g. with a kwarg?

**Comment by rfourquet** [comment]
I have seen functions like `mylpad` in a package to workaround this behavior... So yeah, at least providing an option to use `textwidth` would be great.

Does someone know the usecase for using `length` instead of `textwidth` ?

**Comment by vtjnash** [comment]
Triage said `textwidth` sounds best here

**Comment by JeffBezanson** [comment]
From triage: we can't think of a use case where you would want `length`.

**Comment by rohanxyzg** [comment]
Hey,
I would like to work on this issue.
Thanks!

**Comment by StefanKarpinski** [comment]
Go for it!

**Comment by KristofferC** [comment]
@rohanxyzg, Just a heads up since you post this in a few "good first issue" posts, there is generally no need to "claim" an issue, you can just start working on it and submit a PR when it is finished :).

**Comment by guptatanmay8** [comment]
Hi, can you help me out with how should I approach this issue!
