### ISSUE TITLE
Build error using Clang-11 and thread sanitizer

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#38251]
I'm trying to build julia with Clang-11 with thread sanitizer enabled. I made the following make file. I get a build error in the corecompiler.ji file. I've attached a log of build below along with my Make.user. (I downloaded a binary for clang-11 from the website). 

[log.txt](https://github.com/JuliaLang/julia/files/5469858/log.txt)

Make.user: 
```
USECLANG=1
BUILD_LLVM_CLANG=1
SANITIZE=1
SANITIZE_THREAD=1
override CXX=/data/ranjanan/CS/sanitize/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang++
override CC=/data/ranjanan/CS/sanitize/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang
```

**Comment by ranjanan** [comment]
Perhaps I missed the flag to not precompile julia. Now, I'm trying the Make.user in https://github.com/JuliaLang/julia/pull/36929#issue-463577472

**Comment by ranjanan** [comment]
Still getting a build error: 

Make.user:
```
  1 USECLANG=1
  2 BUILD_LLVM_CLANG=1
  3 SANITIZE=1
  4 SANITIZE_THREAD=1
  5 override CXX=/data/ranjanan/CS/sanitize/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang++
  6 override CC=/data/ranjanan/CS/sanitize/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang
  7 JULIA_PRECOMPILE=0
  8 USE_BINARYBUILDER_LLVM=0
```
Logs:

[log.txt](https://github.com/JuliaLang/julia/files/5541243/log.txt)

**Comment by ranjanan** [comment]
@Keno I'm trying to build julia with thread sanitizer. Does the above Make.user look wrong to you?

**Comment by ViralBShah** [comment]
Maybe @vchuravy might also be able to help.
