### ISSUE TITLE
Re-name `cumsum` to `cumulativesum`

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#38262]
Per this thread: https://twitter.com/code_report/status/1322656492735127556?s=20 It seems worth it to try and re-name this in 1.6. Not sure if re-naming this is a breaking change and thus would need to be pushed back to 2.0 but it's definitely something we should do.

**Comment by KristofferC** [comment]
>  It seems worth it to try and re-name this in 1.6. Not sure if re-naming this is a breaking change and thus would need to be pushed back to 1.0 

I guess you mean 2.0? 

> but it's definitely something we should do.

Hmm, Matlab, numpy, R, tensorflow, octave, pyTorch all use the same name for this function so there is a strong argument for familiarity to keep using that name. Personally, it seems a bit of an overreaction to rename it based on some immature twitter post.

**Comment by logankilpatrick** [comment]
Sounds good!
