### ISSUE TITLE
Feature request: Markdown images should accept optional parameters like height and width

### ISSUE THREAD

**Issue by Ellipse0934** [JuliaLang/julia#38273]
In my Julia markdown file I would like to scale certain images by specifying their height and width. 
For example `![my-image](/path/to/image height=150% width=75%)`
Currently optional parameters are not accepted.

**Comment by MichaelHatherly** [comment]
`Markdown` aims to follow the commonmark spec, see here for current discussions regarding image attributes https://talk.commonmark.org/t/support-for-image-dimensions/148/44. If you need this feature now in Julia you *can* use https://github.com/MichaelHatherly/CommonMark.jl which does support the syntax mentioned at the very end of that discussion. The long-term plan is to replace `Markdown` with `CommonMark`, see https://github.com/JuliaLang/julia/issues/37337 for details.

**Comment by ardsatcg** [comment]
> In my Julia markdown file I would like to scale certain images by specifying their height and width.
> For example `![my-image](/path/to/image height=150% width=75%)`
> Currently optional parameters are not accepted.

See this video https://www.youtube.com/watch?v=DGojI9xcCfg&list=WL&index=9&t=595s in min 6:44 or open file PlutoUI.jl on Pluto notebook, idk wheater this help you

**Comment by brenhinkeller** [comment]
Closing this as superseded by #37337; if your use-case is something more like literate programming you may also consider something like Weave.jl or Pluto.jl
