### ISSUE TITLE
Skip nothing in mapfoldl

### ISSUE THREAD

**Issue by alligatorme** [JuliaLang/julia#38294]
During data process using mapfoldl(f, op, itr; [init]), sometimes f() will return nothing that is not desired. Is it possible to skip the nothing return in the loop?
of course, it can be solved by multiple dispatch op(a,::Nothing)=a

**Comment by KristofferC** [comment]
> of course, it can be solved by multiple dispatch op(a,::Nothing)=a

I think this is the correct way of doing it. You can easily create a function that takes an arbitrary `op` and returns another function that does what you want. If you want, you can then make a `mapfoldl_ignore_missing` that calls that one. Doesn't feel like anything has to be added to Julia itself to do this, or?

**Comment by alligatorme** [comment]
Good idea! Actually, I wish to add a new argument to mapfoldl, such as "skip", to skip certain f() return value.

**Comment by JeffBezanson** [comment]
Adding a feature to mapfoldl for this violates orthogonality, since this can already be accomplished by passing a different function. It's too complex and, for example, makes it harder to add new methods to `mapfoldl`.
