### ISSUE TITLE
improve help search for string macros

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#38334]
If you want to know about e.g. the raw string macro, `?raw` does successfully turn up `@raw_str`. However, that is a bit obscure, so we should perhaps include `raw""` in the results as well.

**Comment by Moelf** [comment]
is it acceptable solution to `insert` a `blah""` if `@blah_str` shows up in `REPL.doc_completions("blah")`? (called by `REPL.repl_search()`)
