### ISSUE TITLE
LinearAlgebra: eigen decomposition of Symmetric Matrix containing NaNs never throws. It just runs forever.

### ISSUE THREAD

**Issue by s-baumann** [JuliaLang/julia#38346]
On my (Windows) PC the following runs forever without ever throwing or finishing. The error seems to come from inside LAPACK. The key elements seems to be that the matrix is Symmetric and contains a NaN.
``
using LinearAlgebra
aa = [1 2      3;
         2 NaN 4;
         3 4       5]
bb = Symmetric(aa)
eigen(bb)
``

**Comment by s-baumann** [comment]
`using LinearAlgebra`
`aa = [1 2 3; 2 NaN 4; 3 4 5]`
`bb = Symmetric(aa) `
`eigen(bb)`

**Comment by antoine-levitt** [comment]
Can't reproduce here (using MKL). Probably an OpenBLAS issue.

**Comment by KlausC** [comment]
Could reproduce on  Linux. Produced the following stack trace, when interrupted:
```
eigen(bb)
^C^C^C^C^C^CWARNING: Force throwing a SIGINT
ERROR: InterruptException:
Stacktrace:
 [1] syevr!(jobz::Char, range::Char, uplo::Char, A::Matrix{Float64}, vl::Float64, vu::Float64, il::Int64, iu::Int64, abstol::Float64)
   @ LinearAlgebra.LAPACK /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:5055
 [2] #eigen!#95
   @ /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:672 [inlined]
 [3] #eigen#96
   @ /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:677 [inlined]
 [4] eigen(A::Symmetric{Float64, Matrix{Float64}})
   @ LinearAlgebra /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:675
 [5] top-level scope
   @ REPL[5]:1
```
There seems missing a call to `ckfinite` or analogous in `syevr!`, as can be seen here:
```
julia> eigen(aa)
ERROR: ArgumentError: matrix contains Infs or NaNs
Stacktrace:
 [1] chkfinite(A::Matrix{Float64})
   @ LinearAlgebra.LAPACK /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:92
 [2] geevx!(balanc::Char, jobvl::Char, jobvr::Char, sense::Char, A::Matrix{Float64})
   @ LinearAlgebra.LAPACK /home/julia/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:2025
 [3] eigen!(A::Matrix{Float64}; permute::Bool, scale::Bool, sortby::typeof(LinearAlgebra.eigsortby))
```

**Comment by s-baumann** [comment]
This is also a problem with Hermitian matrices. No issue with Diagonal matrices though.

`diag = Diagonal(aa)`
`eigen(diag) # This is fine.`
`herm = Hermitian(aa)`
`eigen(herm) # This runs forever`

**Comment by andreasnoack** [comment]
The LAPACK world is free from `Inf`s and `NaN`s. It is assumed that the inputs don't include these values and LAPACK promises not to produce them. Instead, LAPACK returns non-zero `info` values.
