### ISSUE TITLE
Julia/JuMP crashes in very small model

### ISSUE THREAD

**Issue by Aiko-ewl** [JuliaLang/julia#38340]
Hey there,

I'm currently working with Julia/JuMP, and this is a strange thing that happens all the time:

I created a very small LP-JuMP model (see below). Whenever I run this model, Julia crashes after a few seconds and advises me to create a bug report with steps to reproduce this bug (see below). Since, it seems to be a jl_compile problem I didn't report it to JuMP so far. However, when extending the code the problem vanishes some times without a reason :/

Looking forward to hear from you :)
Aiko

**Model:**
> using JuMP, GLPK
> 
> phi = [10 30 50]; Q = [80; 60; 40]; x_p = [0 0 0]; x_n = [70 70 70]
> H = [ 0.3056	-0.5853 0; 0.3056	0.4147 0; 0.6944	0.5853 0];
> H_max = [5 5 5];  G, L = 3, 3;
> 
> m = Model(GLPK.Optimizer)
> @variable(m, x_n[n] <= x[n=1:G] <= x_p[n] )
> @variable(m, y[n=1:G] )
> @objective(m, Min, sum(phi*x) )
> @constraint(m, con_1[j=1:L],       H[j,:]'*y   <=  H_max[j])
> @constraint(m, con_2[j=1:L],       H[j,:]'*y   >= -H_max[j])
> @constraint(m, con_3[n=1:L],   (x[n]-Q[n])     ==  y[n])
> @constraint(m, con_4,               sum(y)     == 0)
> optimize!(m)
> 

**Error message:**
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x6b6496af -- jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1191
> in expression starting at no file:0
> jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1191
> emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
> emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
> emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
> emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
> emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
> jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
> emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
> emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
> emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
> emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
> emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
> jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
> emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
> emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
> emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
> emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
> emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
> jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
> emit_invoke at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3094
> emit_expr at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3893
> emit_ssaval_assign at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3615
> emit_stmtpos at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:3801 [inlined]
> emit_function at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:6262
> jl_compile_linfo at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\codegen.cpp:1159
> jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1774
> jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
> #289 at C:\Users\Aiko\.julia\packages\Atom\LBufP\src\goto.jl:15
> jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1809
> jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
> handlemsg at C:\Users\Aiko\.julia\packages\Atom\LBufP\src\comm.jl:169
> unknown function (ip: 000000001C4543E3)
> jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2162
> jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
> jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:556
> #31 at .\task.jl:259
> unknown function (ip: 00000000328F6EFA)

**Comment by ViralBShah** [comment]
Which versions of Julia and JuMP is this with?

**Comment by Aiko-ewl** [comment]
Thanks for the quick feedback.

When you mentioned your versions, I found out that there are two Julia versions running on my systems (one in …\AppData\Local\Julia… and one in …\AppData\Local\Programs\Julia…). So I updated my Julia path in the Julia client (via the juno settings in atom). Since then I run my models on Julia 1.4.1 and there is no crash occurring anymore.

Thanks again anyway
