### ISSUE TITLE
Allow `∘` usage with kwargs 

### ISSUE THREAD

**Issue by alecloudenback** [JuliaLang/julia#38351]
Would allowing `∘` to compose functions with keyword arguments be a possible update?

E.g. update the current definition of

```julia
∘(f, g) = (x...)->f(g(x...))
```

To 

```
∘(f, g) = (x...; kw...)->f(g(x...; kw...))
```

Stackoverflow question where @bkamins suggested the above solution: https://stackoverflow.com/questions/64740010/how-to-alias-composite-function-with-keyword-arguments

If people are open to this, it seems to have a low surface area in the code (at first glance) and thus PR I could work on.

**Comment by bkamins** [comment]
In particular note that:
```
∘(f) = f
```
already allows kwargs

**Comment by jw3126** [comment]
Yes I think this would be a great and simple PR @alecloudenback

**Comment by gustaphe** [comment]
Nice idea.

Should one consider keyword arguments for `f` as well?

**Comment by jw3126** [comment]
@gustaphe I think if you want to specify keywords for f, it is better to just write out the composition manually.
