### ISSUE TITLE
REPL help for unicode character typing doesn't work for combined characters

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#38366]
Working out how to type things which used combining characters is hard.
So it would be good if REPL help mode worked on them
```

help?> Ȳ
search:

Couldn't find Ȳ
...
```

Contrast to:
```
help?> δ
"δ" can be typed by \delta<tab>

search: ...
```

I think the thing to do would be to extend it so that it applies characterwise to whole strings?
if they contain any thing that is hard to type.

So that would be:
```
help?> Ȳ
"Ȳ" can be typed by `Y` `\bar<tab>`
...
```

**Comment by stevengj** [comment]
Already works in 1.6:
```jl
help?> Ȳ
"Ȳ" can be typed by Y\bar<tab>
```
