### ISSUE TITLE
Method resolution issue for `rdiv!`

### ISSUE THREAD

**Issue by palday** [JuliaLang/julia#38378]
The change in #38168 causes MixedModels to fail on Julia master with a method resolution error for `rdiv!`:

```julia
  MethodError: no method matching rdiv!(::BlockedSparse{Float64, 1, 2}, ::UpperTriangular{Float64, Adjoint{Float64, UniformBlo
ckDiagonal{Float64}}})                                         
  Closest candidates are:
    rdiv!(::StridedMatrix{T} where T, ::UpperTriangular{var"#s814", var"#s813"} where var"#s813"<:Adjoint where var"#s814") at  ~/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:1430
    rdiv!(::StridedMatrix{T} where T, ::UpperTriangular) at ~/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra
/src/triangular.jl:1327
    rdiv!(::AbstractMatrix{T} where T, ::Transpose{var"#s826", var"#s825"} where var"#s825"<:LU where var"#s826") at ~/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:689
```

Tests pass again after reverting this change in a local build.

`BlockedSparse` is a wrapper around `SparseMatrixCSC` with a particular sparsity pattern. Note that this does **not** fall back to the generic multiplication method -- the change in order means that the second argument doesn't match the second argument in the last of the closest candidates.

**Comment by dkarrasch** [comment]
#38168 requires package maintainers to follow with swapping the wrappers. As I suspected in #38168, I guess we should have done some kind of package evaluation before merging. Related error messages may look different though, depending on the specific context.

**Comment by palday** [comment]
If package evaluation passes, I'm happy to close this issue.
