### ISSUE TITLE
Julia (Pkg) doesn't work with system build of 7z anymore.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#38375]
Opening the issue here for visibility and so a decision for 1.6 can be made.

@yuyichao reported in https://github.com/JuliaLang/Pkg.jl/pull/2147#issuecomment-719841641 that a change to Pkg to use Tar.jl broke Pkg (and thus the building of Julia) when the 7z system build option is used.

I don't know the details myself, so, again, just opening this so a decicsion is made.

**Comment by staticfloat** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2198

**Comment by JeffBezanson** [comment]
Triage: since this is easy to fix, we'll do it.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/2210
