### ISSUE TITLE
crash while in @profile

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/julia#38385]
Crash while profiling, on Julia 1.5.0, Win10-64, from installer:
```
julia> @profile computation(data)
Forming covariance matrix ...
computing eigenvalue decomposition ...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x668f9a05 -- jl_unw_step at /cygdrive/d/buildbot/worker/package_win64/build/src\stackwalk.c:531 [inlined]
jl_unw_stepn at /cygdrive/d/buildbot/worker/package_win64/build/src\stackwalk.c:99
in expression starting at REPL[6]:1
```
Computation is a pretty complex function - can be shared privately (zipped project, self-contained as julia project with manifest) as code is not open.
I've seen similar crash in #17386 with a smaller mwe. This crashes are not so uncommon on larger codebases, rarely seen on smaller functions.

**Comment by ViralBShah** [comment]
This needs more information for reproducing, if still an issue.
