### ISSUE TITLE
Strange behaviour of try-catch scheme in error free case

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#38391]
I came across this issue while testing software calling matrix equation solvers. The following sequence usually works after a new booting of my Windows 10 computer:

```
using MatrixEquations
function test()
   try 
      x, _,y, = gared(zeros(1,1),ones(1,1),ones(1,1),ones(1,1),ones(1,1),zeros(1,1))  
      #      x = 1; y = 2;
     println("xc = $x")
     println("yc = $y")
   catch err
      println("$err")
   end
   println("x = $x")
   println("y = $y")
   return x, y
end

```
```
julia> x, y = test()
xc = [1.0]
yc = [-0.0]
x = [1.0]
y = [-0.0]
([1.0], [-0.0])

```

During the testing process, something triggers an event, which leads to the following behaviour:
```
julia> x, y = test()
xc = [1.0]
yc = [-0.0]
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] test() at .\REPL[2]:10
 [2] top-level scope at REPL[3]:1

julia> VERSION
v"1.5.2"

```
After trigering once this error, it continues to occur even if the function simply sets x = 1 and y = 1:
```
function test()
   try 
      #x, _,y, = gared(zeros(1,1),ones(1,1),ones(1,1),ones(1,1),ones(1,1),zeros(1,1))  
      x = 1; y = 2;
      println("xc = $x")
      println("yc = $y")
   catch err
      println("$err")
   end
   println("x = $x")
   println("y = $y")
   return x, y
end

```
julia> x, y = test()
xc = 1
yc = 2
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] test() at .\REPL[5]:10
 [2] top-level scope at REPL[6]:1

I have also  Julia 1.2.1 and Julia 1.3.1 installed on my computer, which both show the same behaviour.

**Comment by StefanKarpinski** [comment]
This is expected: `try` blocks introduce scope.

**Comment by andreasvarga** [comment]
Thanks for the reply. In the meantime, I learnt more of the scoping restrictions within try-catch. My understanding is that the last evaluated variable is still visible outside the try-catch block (so the scoping is only partial). Unfortunately,  if after the `try`, I am calling  a function with 4 (four) output parameters, then three of them will not be visible outside the try-catch block. To make them visible, probably I have either to declare them global or to pack all parameters of interest in a structure (or tuple).  Is any other way to avoid the usage of such tricks?

PS. For me the ideal try-catch construct would be one which can be added/removed to a code without altering any line of the original code, and by no way its logic. I see no reasons for hiding variables in this construct (at least not in a function).

**Comment by KristofferC** [comment]
> My understanding is that the last evaluated variable is still visible outside the try-catch block (so the scoping is only partial). 

The expression evaluates to the last evaluated statement, for example:

```jl
julia> a, b = try 1, 2 catch end
(1, 2)

julia> a
1

julia> b
2
```

**Comment by andreasvarga** [comment]
Nice solution. I thank you a lot!

**Comment by StefanKarpinski** [comment]
> My understanding is that the last evaluated variable is still visible outside the try-catch block (so the scoping is only partial).

There's no such thing as "partial scope" — scope applies to variables, not values. Hopefully @KristofferC's answer cleared things up for you. If you have any further questions, please don't hesitate to ask on the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
