### ISSUE TITLE
weird behavior of __source__

### ISSUE THREAD

**Issue by rfourquet** [JuliaLang/julia#38439]
Can you guess what calling these macros will return?

```julia
macro source1()
    __source__
end

macro source2()
    __source__, 1
end

macro source3()
    :($__source__)
end

macro source4()
    lnn = LineNumberNode(__source__.line, __source__.file)
    :($lnn)
end

struct LNN # exactly like LineNumberNode
    line::Int
    file::Union{Nothing,Symbol}
end

macro source5()
    lnn = LNN(__source__.line, __source__.file)
    :($lnn)
end

macro source6()
    :($(QuoteNode(__source__)))
end
```
Here it is:
```julia
julia> @source1

julia> @source2
(:(#= REPL[95]:1 =#), 1)

julia> @source3

julia> @source4

julia> @source5
LNN(1, Symbol("REPL[98]"))

julia> @source6
:(#= REPL[99]:1 =#)
```
The `@source1` vs `@source2` difference looks like a bug to me. I can't understand why `@source3()` returns nothing, nor how to explain the difference between `@source4` and `@source5`. Finally, it seems that what I needed was `@source6`... There might be a logicat explanation to all these behaviors, but I could hardly predict all of that from reading the manual on metaprogramming (so this might be only a documentation issue).

**Comment by yuyichao** [comment]
1. macros returns expression, not the value. source1 simply returned a line number expression that evaluates to nothing. Use `macroexpand` to see the expression.
2. source3 and source1 are exactly the same thing and source4 isn't much different.
3. source5 returns a non expression

**Comment by rfourquet** [comment]
Still, I couldn't find in the manual the information needed to predict this behavior. So I would appreciate a pointer to relevant parts of the documentation, or that we keep this issue open until it's documented. I'm fine to change the title of the issue though, as it amounts to the fact that a `LineNumberNode` object `eval`uates to `nothing`, unlike most other objects AFAIK.

**Comment by yuyichao** [comment]
> unlike most other objects

It's the property of *all* expressions.

**Comment by rfourquet** [comment]
> It's the property of all expressions.

Sorry for the naive question, but what makes a `LineNumberNode` object an "expression", which doesn't make objects of my `LNN` type above also an expression?

And what do you define as "expression"? I assume not `Expr` object, as these can evaluate to non-`nothing`...

**Comment by yuyichao** [comment]
Expressions are whatever has special meanings in the AST. You can find a lot of document on this when you [search AST in the doc](https://docs.julialang.org/en/v1/search/?q=AST). A few of the pages mentions `LineNumberNode`.

> I assume not Expr object,

Expr object counds. These are the objects that may not evaluate to itself, not evaluating to `nothing`. `LineNumberNode` isn't even supposed to be evaluated and it evaluates to `nothing` pretty much just to give a fairly safe value for something that is not supposed to do anything.
