### ISSUE TITLE
Make `CartesianIndex`s broadcast like scalars?

### ISSUE THREAD

**Issue by Sleort** [JuliaLang/julia#38432]
Following [this](https://discourse.julialang.org/t/tuples-of-cartesianindex-and-broadcasting/50093) Discourse discussion, I'd like to propose to make `CartesianIndex`s broadcast like scalars. That is, since
```julia
julia> 1 .+ (2, 3)
(3, 4)
```
works, so should
```julia
julia> CartesianIndex(1,1) .+ (CartesianIndex(2,2), CartesianIndex(3,3))
```
(which currently errors, but should, in my opinion, result in `(CartesianIndex(3, 3), CartesianIndex(4, 4))`)

**Comment by mbauman** [comment]
Notably, this works if the collection being broadcast over a `CartesianIndices` (https://github.com/JuliaLang/julia/pull/29890) — so this is on the path towards greater consistency.

This is as simple as adding a definition like [@mcabbott proposed ](https://discourse.julialang.org/t/tuples-of-cartesianindex-and-broadcasting/50093/4?u=mbauman) and a few tests:

```
Broadcast.broadcastable(I::CartesianIndex) = Ref(I)
```
