### ISSUE TITLE
Complex{Integer} >: Complex{Int64} 

### ISSUE THREAD

**Issue by RocketRoss** [JuliaLang/julia#38448]
I typed an argument for a function to be `Complex{Integer}`, and found that calling it with an inline complex number on my 64bit machine resulted in no suitable function being found. There is an unexpected lack of type hierarchy.. `Complex{Int64/32/16/8}` is not a subtype of `Complex{Integer}`, but only a subtype of `Complex`. Could someone please explain/rectify?

```
julia> Complex >: Complex{Int64}
true

julia> Complex{Integer} >: Complex{Int64}
false
```

**Comment by simeonschaub** [comment]
This is expected, see the manual on parametric types: https://docs.julialang.org/en/v1/manual/types/#Parametric-Composite-Types
