### ISSUE TITLE
Inconsistency in 1-arg and 3-arg names in `:method` Exprs

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#38451]
This is a re-post of https://github.com/timholy/Revise.jl/issues/568:
```julia
module MyModule

function my_fun end

macro some_macro(value)
    return esc(:($MyModule.my_fun() = $value))
end

end
```

And then:
```julia
julia> Base.Meta.lower(MyModule, :(@some_macro 20))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1 = Base.getproperty(Main.MyModule, :my_fun)
│   %2 = Core.Typeof(%1)
│   %3 = Core.svec(%2)
│   %4 = Core.svec()
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= REPL[1]:6 =#))))
│        $(Expr(:method, nothing, :(%5), CodeInfo(
    @ REPL[1]:6 within `none'
1 ─     return 20
)))
└──      return nothing
))))
```
I was surprised by the `nothing` used for argument 1 of the 3-arg `:method` `Expr`; shouldn't it be `:my_fun`?

**Comment by cstjean** [comment]
Perhaps that's obvious from context, but FWIW this is on 1.6. 1.5 yields

```julia
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= REPL[2]:8 =#))))
│        $(Expr(:method, :(Base.getproperty(Main.MyModule, :my_fun)), :(%5), CodeInfo(quote
    return 20
end)))
```

**Comment by Keno** [comment]
This was changed in https://github.com/JuliaLang/julia/pull/37287. The difference is whether or not the method can create an entirely new method or not (i.e. whether it's interpreted as an identifier or an expression).

**Comment by timholy** [comment]
To make sure I understand, you're saying this is how it should work and not a bug? If so, perhaps we should update https://docs.julialang.org/en/v1.6-dev/devdocs/ast/#Expr-types. I can do that, but I'd need to know a bit more about the conditions under which it uses `nothing`. I always assumed that was for anonymous functions.

**Comment by JeffBezanson** [comment]
Yes, this is how it should work. As Keno said, the difference is that `f(x) = x` can start with `f` being undefined, and assign a value to it. But `M.f(x) = x` requires `M.f` to be defined already, evaluates that expression, and uses it to determine the type to add the method to, so there is no assigned name.
