### ISSUE TITLE
Weird bug of dlopen to load custom built msys2-mingw64 dll on Windows

### ISSUE THREAD

**Issue by metab0t** [JuliaLang/julia#38456]
Recently I want to use my custom Ipopt built with mingw64 toolchain in msys2 to use with Julia.
However, I find that my built .dll files cannot be loaded by `Libdl.dlopen` function.
I use official Julia v1.5.3 on Windows now.
I will use `libcoinmumps-2.dll` as an example.
Firstly, I use Dependencies GUI to look at the dependent dlls and they are all loaded successfully.
![图片](https://user-images.githubusercontent.com/10501166/99252775-75901580-284a-11eb-8a56-e5a8e7eea2e2.png)
Next, I write a small c file (replicating `dlload.c`) and julia file (replicating `libdl.jl`) in [my gist](https://gist.github.com/metab0t/f0cc1a908a557757c686ad79b3bddb32) and they give different result.
The c version says that dll is loaded successfully and the julia version reports:
```
ERROR: LoadError: could not load library "C:\msys64\home\meta\dist\bin\libcoinmumps-2.dll"
The specified procedure could not be found.
```

To reproduce the issue, I upload my built `libcoinmumps-2.dll`. It is the product of building Ipopt with coinbrew on windows. 

1. Extract the dll to some directory.

[libcoinmumps-2.zip](https://github.com/JuliaLang/julia/files/5546198/libcoinmumps-2.zip)

2. Install following packages in msys2, add `c:\msys64\mingw64\bin` to path
```
pacman -S mingw-w64-x86_64-openblas mingw-w64-x86_64-lapack mingw-w64-x86_64-metis mingw-w64-x86_64-toolchain
```

3. compile and run the c file, run the julia file in my gist link (change the path of dll in source file). They give different results of loading the same dll.

In theory, the c file replicates the behaviour of `jl_load_dynamic_library` and julia code calls this function directly and they should give the same result.

Is this a bug of Julia or problem with my mingw64 built dll?

**Comment by metab0t** [comment]
I replace the `libgfortran-5.dll` in `$juliadir/bin` with `libgfortran-5.dll` in `msys64/mingw64/bin` directory and `dlopen` succeeds.
It seems that two `libgfortran-5.dll` have differences. The one comes bundled with julia lacks some function.

**Comment by ViralBShah** [comment]
We now have `CompilerSupportLibs_jll` that should be doing a better job at this. Please reopen if still an issue.
