### ISSUE TITLE
Undefined behavior on 1 << 31 in gc-pages.c

### ISSUE THREAD

**Issue by vzecca** [JuliaLang/julia#38454]
On a sanitized version of julia 1.5.3 built with gnu gcc  -fsanitize=undefined option
running just ./julia the ubsan real time detects undefined behavior at gc-pages.c lines 145, 244, and 245
because the code attempts to compute 1 << 31
This is undefined when type int is 32 bits wide.
I suggest changing computation to 1u << 31

**Comment by JeffBezanson** [comment]
Thanks for finding this. Would you be willing to open a PR with this change?

**Comment by vzecca** [comment]
Could you do that for me?

By the way there are more similar 1<<31 at subtype.c lines 120, 127, and 129.

**Comment by fingolfin** [comment]
See https://github.com/JuliaLang/julia/pull/38503
