### ISSUE TITLE
missing documentation index file for new stdlibs

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#38462]
The stdlibs that are missing documentation are:
 - [x] [ArgTools](https://github.com/JuliaIO/ArgTools.jl/issues/18)
 - [x] Artifacts (this issue)
 - [x] LazyArtifacts (inherited defect from Artifacts when splitting them in #37844)
 - [x] LibCURL
 - [x] [NetworkOptions](https://github.com/JuliaLang/NetworkOptions.jl/issues/5)
 - [x] [Tar](https://github.com/JuliaIO/Tar.jl/issues/81)

**Comment by fingolfin** [comment]
See also https://github.com/JuliaIO/ArgTools.jl/issues/18

**Comment by fingolfin** [comment]
I wonder: for artifacts, should it be minimal and then point to https://julialang.github.io/Pkg.jl/dev/artifacts/ ; or should the content of the latter be migrated to the Artifacts stdlib?

**Comment by KristofferC** [comment]
Bump. With all the recent problems with package/artifact downloads, it would be useful to have e.g. NetworkOptions.jl in the manual so that it can be cross-referenced from e.g. the Pkg documentation. @StefanKarpinski

**Comment by StefanKarpinski** [comment]
This would be an easy issue for anyone to tackle.

**Comment by StefanKarpinski** [comment]
Thank you so much, @inkydragon! Seems like this can be closed now.
