### ISSUE TITLE
Testing For Equalities Between A Rational Number and It's Decimal Value

### ISSUE THREAD

**Issue by DonovanEdge** [JuliaLang/julia#38471]
I am not sure this is a bug, or expected behavior.  If it is expected behavior, a brief explanation would be appreciated.

Why does the test for equality return a false when the two values, under test, are mathematically the same?  For example ...

**julia>** 8//5 == 1.6
false

**julia>** 2 + 1/(-3 + 1/2) == 8//5
false

**julia>** isequal(8/5, rationalize(2 + 1/(-3 + 1/2)))
false

**Test environment:**
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\*\AppData\Local\atom\app-1.53.0\atom.exe"  -a
  JULIA_NUM_THREADS = 2

Thank you!
DonovanEdge

**Comment by yuyichao** [comment]
8//5 is not representable by binary floating point number so this is impossible.

**Comment by DonovanEdge** [comment]
@yuyichao Thank you for replying so quickly, but I'm failing to understand your explanation. Can you please elaborate, or point me in the right direction?

**Comment by StefanKarpinski** [comment]
Best to ask questions on [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
