### ISSUE TITLE
splitdrive doesn't respect UNC sharepoints when the path is constructed with forward slashes 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#38492]
```julia
julia> splitdrive("//host/computer/dir")
("", "//host/computer/dir")
```
This should return

```julia
("//host/computer", "/dir")
```

Edit: the correct answer is obtained if you use backslashes...

**Comment by musm** [comment]
I guess we should probably normalize before the regex search.

**Comment by GunnarFarneback** [comment]
I don't think `splitdrive` should make slash normalization; there are other functions for that. Ironically this bug breaks `normpath` as well:
```
julia> normpath("//server/share/dir")
"\\server\\share\\dir"
```
(In some situations `realpath` is an effective workaround for the latter.)
