### ISSUE TITLE
Is this change in exp10 expected?

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#38509]
in Julia 1.5.2
```julia
julia> exp10(23)
1.0e23
```
current master
```julia
julia> exp10(23)
1.0000000000000001e23
```

In https://github.com/JuliaLang/julia/pull/36761, it was stated that exp10 should be strictly more accurate, I'm just checking that this result is expected. It's [causing failures](https://travis-ci.com/github/JuliaData/Parsers.jl/jobs/444143544) in Parsers.jl nightly float parsing tests.

**Comment by quinnj** [comment]
cc: @oscardssmith

**Comment by oscardssmith** [comment]
As I understand it, `exp10` isn't expected to be exact for integer arguments. One possible solution would be to define `exp10` and `exp2` to use power by squaring which are guaranteed to produce perfectly accurate results (although for values that overflow `Int` that doesn't work). Interestingly, this appears to be a place where the new method is exactly 1ULP off, which was not found by testing due to the impossibility of testing every `Float64`. I'm not exactly sure why this happens when all the nearby floating point numbers are exact.

**Comment by chriselrod** [comment]
Power by squaring should be exact for positive integer exponents (given integer base), but we may lose exactness for negative exponents when inverting (see `myexp(-23)` below).
```julia
julia> myexp10(x::Integer) = x ≥ 0 ? Base.power_by_squaring(10.0, x) : inv(Base.power_by_squaring(10.0, -x))
myexp10 (generic function with 1 method)

julia> myexp2(x::Integer) = x ≥ 0 ? Base.uitofp(Float64, 1 << x) : inv(Base.uitofp(Float64, 1 << (-x)))
myexp2 (generic function with 1 method)

julia> @btime myexp10($(Ref(23))[])
  5.509 ns (0 allocations: 0 bytes)
1.0e23

julia> @btime exp10($(Ref(23))[])
  11.676 ns (0 allocations: 0 bytes)
1.0000000000000001e23

julia> @btime myexp10($(Ref(-23))[])
  5.736 ns (0 allocations: 0 bytes)
1.0000000000000001e-23

julia> @btime exp10($(Ref(-23))[])
  11.676 ns (0 allocations: 0 bytes)
1.0e-23

julia> @btime myexp2($(Ref(23))[])
  1.207 ns (0 allocations: 0 bytes)
8.388608e6

julia> @btime exp2($(Ref(23))[])
  1.446 ns (0 allocations: 0 bytes)
8.388608e6

julia> @btime myexp2($(Ref(-23))[])
  4.297 ns (0 allocations: 0 bytes)
1.1920928955078125e-7

julia> @btime exp2($(Ref(-23))[])
  1.446 ns (0 allocations: 0 bytes)
1.1920928955078125e-7
```
The bitshift-based `myexp2` is fast.
Note that these all have limited range, though, so an extra check would be needed:
```julia
julia> exp2(65)
3.6893488147419103e19

julia> myexp2(65)
0.0
```

**Comment by chriselrod** [comment]
How about
```julia
julia> exp2_integer(x::Integer) = reinterpret(Float64, ((1 << 11) + x+x - 2) << 51)
exp2_integer (generic function with 1 method)

julia> @btime exp2_integer($(Ref(-23))[])
  1.207 ns (0 allocations: 0 bytes)
1.1920928955078125e-7

julia> @btime exp2_integer($(Ref(23))[])
  1.207 ns (0 allocations: 0 bytes)
8.388608e6

julia> @btime exp2_integer($(Ref(-65))[])
  1.206 ns (0 allocations: 0 bytes)
2.710505431213761e-20

julia> @btime exp2_integer($(Ref(65))[])
  1.443 ns (0 allocations: 0 bytes)
3.6893488147419103e19

julia> @btime exp2_integer($(Ref(-130))[])
  1.206 ns (0 allocations: 0 bytes)
7.346839692639297e-40

julia> @btime exp2_integer($(Ref(130))[])
  1.207 ns (0 allocations: 0 bytes)
1.361129467683754e39
```

**Comment by stevengj** [comment]
`1.0e23` is not exactly representable as `Float64` (it is `> 2^53 ≈ 1e16`)— you are seeing it as "exact" purely as an artifact of the `show` algorithm:
```
julia> big(1.0e23)
9.9999999999999991611392e+22

julia> Float64((big(1.0e23) - big"1.0e23") / big"1.0e23") # relative error
-8.388608e-17
```
versus
```
julia> Float64((big(1.0000000000000001e23) - big"1.0e23") / big"1.0e23")
8.388608e-17
```
So, the new and old errors are exactly the same here, just of opposite signs.

**Comment by oscardssmith** [comment]
Cool. Good to know this isn't a regression.

**Comment by quinnj** [comment]
Well, it still unexpectedly changed program behavior that was relying on a specific error sign, so that seems like a regression to me?

**Comment by KristofferC** [comment]
Any change affects program behavior that is relying on the changed thing behaving a certain way, so that cannot really be used to identify a regression.

**Comment by quinnj** [comment]
Ok fine; I actually don't really care what we call it, but I would appreciate a suggestion from someone on what they think I should do? Do we think this can be "fixed" to bring back the old behavior? Is there an easy workaround to get the previous behavior? Should I generate hard-coded lookups for powers of 10?

**Comment by stevengj** [comment]
Generally you should use `≈` with some tolerance for floating-point tests — especially for tests with results like `1e20` that *can't* be exact — rather than exact equality, except under very narrow circumstances where you are maintaining stronger guarantees about the rounding…

**Comment by stevengj** [comment]
But since this is for parsing tests in your case, it seems like you should be able ensure exact equality, as long as you generate the string to be parse from the same floating-point number that you compare to.   Can you give an example of a failing test?   I looked at https://github.com/JuliaData/Parsers.jl/blob/master/test/floats.jl but it was too long for me to see where the problem was.

**Comment by stevengj** [comment]
Is the problem [this code](https://github.com/JuliaData/Parsers.jl/blob/67b641a2510835cdecce1418b5229aade383f2b6/src/floats.jl#L308)? Maybe you want:
```jl
const F64_SHORT_POWERS = [parse(Float64, "1e$x") for x = 0:2ceillog5(Float64)-1]
```
so that this table is independent of the rounding returned by `exp10`?

**Comment by stevengj** [comment]
(Also, if you need to test very specific values because they are edge cases of some sort, I would write them as `9.0e-265` rather than `9.0 * exp10(-265)`.)

**Comment by JeffBezanson** [comment]
Looks to me like this can be closed?

**Comment by quinnj** [comment]
The only failing test is `Parsers.parse(Float64, "1e23")`, where we eventually try to compute it as `x = v * exp10(V(exp))`, where `v = 1` and `exp = 23`. Which used to give `1e23` as the answer and now gives `1.0000000000000001e23`

**Comment by stevengj** [comment]
Since you only need a limited range of integer powers of 10 and need to guarantee a specific rounding, probably you need a lookup table.

**Comment by stevengj** [comment]
However, even with a lookup table, I don't see how this strategy can guarantee that your parser will produce the same rounding as Julia's parser.  Here is a counterexample:
```jl
julia> 4.039822479702418e54
4.039822479702418e54

julia> 4.039822479702418 * 1e54 
4.039822479702419e54
```

**Comment by stevengj** [comment]
(Interestingly, there are only 5 integers `n` where `exp10(n) ≠ parse(Float64, string("1e$n"))`: -192, 23, 210, 250, 304.)

**Comment by quinnj** [comment]
Thanks for the comments @stevengj; I should clarify that Parsers.jl doesn't use the `v * exp10(exp)` for the vast majority of values in the parsing algorithm; it's actually a fallback if other conditions aren't met. Comparing the integer values for 1.5/1.6, it looks like `N = 23` is the _only_ case in either version where the change 1) is affected by this rounding change and 2) ends up hitting this fallback code path. So maybe we just need to special-case the case specifically and move on.
