### ISSUE TITLE
flisp nested quasiquote is not evaluated correctly

### ISSUE THREAD

**Issue by rgobbel** [JuliaLang/julia#38507]
Femtolisp seems to do the wrong thing for nested quasiquotes:

```
`(a `(b c))
```
gives
```
(a (list 'b 'c))
```
the correct result would be
```
(a (quasiquote (b c))
```

Typing `quasiquote` instead of using backquotes gives the same incorrect result.

I tripped over this in the course of making a femtolisp plugin for IntelliJ, in the course of fixing up the existing Julia IntelliJ plugin.

**Comment by JeffBezanson** [comment]
I believe this is already fixed in https://github.com/JeffBezanson/femtolisp. I can bring the new code over.

**Comment by rgobbel** [comment]
Definitely fixed in the main femtolisp repository, I've tested it there and it seemed fine.
