### ISSUE TITLE
svdvals can be extremely slow for matrix types that do not support rapid indexing

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#38529]
Currently `svdvals` is defined as 

https://github.com/JuliaLang/julia/blob/b166d0d15f616f4a025ac5905a115399cc932ddc/stdlib/LinearAlgebra/src/svd.jl#L193

The performance of `svdvals` therefore depends on that of `copy`. However certain array types --- for example the matrix Q from a QR decomposition --- do not support rapid indexing, therefore `copy(Q)` can be extremely slow for large matrices and require gigabytes of allocation. One way around this for this specific type is to evaluate `svdvals(Array(Q))`, that is by explicitly materializing the matrix before the singular values are evaluated. In this case `Array(Q)` is evaluated through a matrix multiplication instead of indexing, and is therefore quite fast. I wonder if something like this might be automatically done by `svdvals` so that a copy might not be necessary? 

A performance comparison is:

```julia
julia> A = ones(500, 500);

julia> f = qr(A);

julia> svdvals(f.Q); @time svdvals(f.Q);
112.684044 seconds (750.01 k allocations: 2.908 GiB, 0.14% gc time)

julia> svdvals(Array(f.Q)); @time svdvals(Array(f.Q));
  0.079534 seconds (17 allocations: 7.920 MiB)
```

Of course certain types might not permit conversion to an `Array` but support copying, therefore this approach is not universally valid and suggestions are welcome

**Comment by stevengj** [comment]
One option would be to just define a few more `copy` methods for these types along the lines of `copy(a) = Matrix(a)`, since they already have a fast `Matrix` conversion.

**Comment by jishnub** [comment]
That would certainly fix this, and --- given that it's likely that only a handful of types would suffer from this --- it's possible to define such methods wherever we encounter this. This leads to a different question though --- should `copy` preserve the type of the `AbstractMatrix`? I suppose it doesn't need to, as it relies on `similar` to produce the destination array, and `similar` is not guaranteed to preserve the type.

**Comment by stevengj** [comment]
> should copy preserve the type of the AbstractMatrix

In cases like this where we need a mutable copy, we should arguably be calling `Base.copymutable` (which *does* call `similar` to get a mutable copy, whereas `copy` may not):

```
julia> copy(1:10)
1:10

julia> Base.copymutable(1:10)
10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
```

**Comment by ViralBShah** [comment]
The provided example is no longer an issue. Perhaps not a completely general fix, but can always reopen if necessary.

```
julia> using LinearAlgebra

julia> A = ones(500, 500);

julia> f = qr(A);

julia> svdvals(f.Q); @time svdvals(f.Q);
  0.029067 seconds (12 allocations: 4.105 MiB)
```
