### ISSUE TITLE
Multiplialtion of unsigned intieger with coplex rational gives error.

### ISSUE THREAD

**Issue by fremling** [JuliaLang/julia#38538]
I found what to me is an error. If i divide (or multiply) an unsidged interg by a complex rational i get and error.

julia> 0x0000000000000002 // im
ERROR: InexactError: check_top_bit(Int64, -1)

If i however do the same with a signed integer it wokrs as expected
julia> 2 // im
0//1 - 2//1*im

###
julia> versioninfo()
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by yuyichao** [comment]
You realized that the number you are trying to create has a negative imaginary part that is not representable by a unsigned fraction right?

Creating an unsigned fraction with non-negative real and imaginary part works as expected.

```julia
julia> 0x0000000000000002//0x1 * im
0x0000000000000000//0x0000000000000001 + 0x0000000000000002//0x0000000000000001*im
```

So is using divide and not fraction

```julia
julia> 0x0000000000000002 / im
0.0 - 2.0im
```

**Comment by fremling** [comment]
After writing it in i realized that that was the case. I think the real rror in my thinking was that multiplication of an unsigned integer by a negative number would give a negative signed integer.  This is true sometimes but now always....

julia> -1*0x00000002
-2

julia> -1*0x0000000002



 -1*0x0000000000000002

**Comment by StefanKarpinski** [comment]
When multiplying different types of integers, the result is the larger of the two argument types; if they are the same size, one signed and one unsigned, then the result is the unsigned type. I believe this is documented in the chapter on built-in numeric types.
