### ISSUE TITLE
Profile test timeout

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#38547]
https://build.julialang.org/#/builders/52/builds/5599/steps/5/logs/stdio

We fairly often get the `KILLING BY PROFILE TEST WATCHDOG` failure mode. Maybe there is still a deadlock?

**Comment by vtjnash** [comment]
Is it mostly linux? The new fast aarch64 machines are taking over a minute to run the Profile test now, and I see linux64 even now taking 90-150 seconds. While locally (and on macOS and Win64), they take 10-15 seconds. So it might not be surprising they are exceeding the 120s budget for the final test.

The plan (from triage) is to try changing the timer strategy to exclude the time taken by the profiler itself.

**Comment by vtjnash** [comment]
Not a timeout specifically, but a failure again https://build.julialang.org/#/builders/34/builds/6521/steps/5/logs/stdio
