### ISSUE TITLE
`eigen!(A::StridedMatrix{ComplexF64})` returns wrong results for particular example

### ISSUE THREAD

**Issue by jlbosse** [JuliaLang/julia#38542]
I found a complex, symmetric matrix where `eigen(A)` does not return a correct 
decomposition, even though the matrix should have one. See the following code:

```julia
julia> using LinearAlgebra
julia> A = [0.764842-0.644218im     7.37816e-18-3.41255e-18im
         7.37816e-18-3.41255e-18im     0.764842-0.644218im]
julia> AA = LinearAlgebra.copy_oftype(A, LinearAlgebra.eigtype(eltype(A))
julia> vals, vecs = eigen!(AA) 
julia> abs.(vecs * diagm(vals) * vecs' - AA)
2×2 Array{Float64,2}:
0.000674614  0.0259646
0.0259646    0.000674614
```
where the expected output is 

```julia
julia> abs.(vecs * diagm(vals) * vecs' - AA)
2×2 Array{Float64,2}:
0.0  0.0
0.0  0.0
```
.

The third and fourth line are copied from the definition of `eigen` in `share/julia/stdlib/v1.5/LinearAlgebra/src/eigen.jl:234`. Replacing them with `vals, vecs = eigen(A)` and the `AA` in the last line with `A` does not change anything.

**Julia Version:** I am on julia 1.5.3 on Linux (x68_64)

**Edit:** Made the example simpler

**Comment by dkarrasch** [comment]
No. What you expect would hold if the matrix was Hermitian... and it does, if you change the sign of the imaginary part in either of the off-diagonal entries. For the general case, you would expect
```julia
abs.(vecs * diagm(vals) / vecs - A) # you should compare to the original A, because you overwrote AA via eigen!
```
to vanish (up to small floating point errors), and it does for your example. See also the discussion in #38335.

**Comment by jlbosse** [comment]
I had a closer look. The fact that `A` is complex symmetric is indeed not enough to guarantee, that it can be unitarily diagonalized. But it also is of the form `A = transpose(U) * U` for a unitary `U`. And it is straightforward to verify
that such `A` are not only complex symmetric, but also normal. And [normality implies unitary diagonalizability](https://en.wikipedia.org/wiki/Normal_matrix).

I believe, that the errors instead arise from the very small off-diagonal entries. Setting e.g. their imaginary part 
to a larger value (but still keeping the matrix complex symmetric) we get

```julia
julia> using LinearAlgebra
julia> A = [0.764842-0.644218im     7.37816e-18-3.41255e-2im
         7.37816e-18-3.41255e-2im     0.764842-0.644218im]
julia> vals, vecs = eigen(A) 
julia> abs.(vecs * diagm(vals) * vecs' - A)
2×2 Array{Float64,2}:
 2.9873e-15   2.68556e-15
 2.72357e-15  2.31821e-15
```

which looks much better.

But since the original matrix was diagonally dominated, `eigen` should IMHO still be able to find the correct eigendecomposition.

**Comment by dkarrasch** [comment]
> And [normality implies unitary diagonalizability](https://en.wikipedia.org/wiki/Normal_matrix).

While that's true mathematically, it's not guaranteed from the output of the function, cf. #38335. For the OP's example, check the unitarity of the eigenvectors, and you get
```julia
julia> vecs'vecs
2×2 Array{Complex{Float64},2}:
        1.0+0.0im        -0.0235739-0.0109034im
 -0.0235739+0.0109034im         1.0+0.0im
```
something far from the identity.
