### ISSUE TITLE
Windows CI runs out of committed memory

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38556]
https://build.julialang.org/#/builders/21/builds/6540/steps/15/logs/stdio
```
ERROR: LoadError: failed process: Process(`git rev-parse HEAD`, ProcessExited(3221225773)) [3221225773]
```

That error code indicates a segfault.

**Comment by Keno** [comment]
@staticfloat and I have diagnosed this. The Windows VMs are running out of committed memory. Our suspicious is that OpenBLAS is allocating large per-CPU buffers using committed memory, but we'll just add a big pagefile for now.

**Comment by Keno** [comment]
Need @christopher-dG to resize the disks, so we can add a larger pagefile. Ideally we'd be able to re-use the linux swap as a page file, but I'm not sure how to configure that.

**Comment by vtjnash** [comment]
I think you'd mount a new tmpfs (or just literally use /tmp), give a view on that mount to the VM, then go through the GUI to configure Windows to use that disk instead

**Comment by Keno** [comment]
I think just putting it in the disk image is fine. Swapping to a ramdisk is a bit of an odd thing to do. Not that is matters much because we don't ever actually use the space anyway, we just need it to be available or windows won't commit it.

**Comment by christopher-dG** [comment]
I've added 64GB to each Windows VM.

**Comment by staticfloat** [comment]
I've bumped the page files up to 32GB, so we should have ~64GB of committable memory space now.  Let's see if the builds stop failing now.

**Comment by Keno** [comment]
This appears to be resolved.

**Comment by BoundaryValueProblems** [comment]
I got this `OutOfMemoryError()` for CI / Julia nightly - windows-latest - x64 - push for my package: https://github.com/UCD4IDS/MultiscaleGraphSignalTransforms.jl  The other ones, i.e., CI / Julia nightly - ubuntu-latest -x64 - push and CI / Julia nightly - macOS-latest -x64 - push do not generate any errors and passes the CI without any problem.

**Comment by christopher-dG** [comment]
@BoundaryValueProblems this issue is about CI for Julia itself, package CI runs on other machines hosted by GitHub.

**Comment by BoundaryValueProblems** [comment]
@christopher-dG, thanks. So, we cannot do anything about this at this point, correct? Or should I report this to GitHub?
