### ISSUE TITLE
"fork: Resource temporarily unavailable" in ci

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#38550]
https://build.julialang.org/#/builders/38/builds/6484

I've seen this a couple times now.

**Comment by JeffBezanson** [comment]
https://build.julialang.org/#/builders/39/builds/5381

**Comment by Keno** [comment]
This happens when one of the global soft limits is exceeded:

```

              *  the RLIMIT_NPROC soft resource limit (set via
                 setrlimit(2)), which limits the number of processes and
                 threads for a real user ID, was reached;

              *  the kernel's system-wide limit on the number of processes
                 and threads, /proc/sys/kernel/threads-max, was reached (see
                 proc(5));

              *  the maximum number of PIDs, /proc/sys/kernel/pid_max, was
                 reached (see proc(5)); or

              *  the PID limit (pids.max) imposed by the cgroup "process
                 number" (PIDs) controller was reached.
```

We should figure out which one and raise it.

**Comment by Keno** [comment]
FWIW, the global limits are pretty high on this system:
```
ubuntu@aarch64bot1:~$ cat /proc/sys/kernel/threads-max 
2057599
ubuntu@aarch64bot1:~$ cat /proc/sys/kernel/pid_max 
4194304
ubuntu@aarch64bot1:~$ cat /proc/sys/fs/file-max
9223372036854775807
```

**Comment by Keno** [comment]
@staticfloat says he already bumped the pid limit in the docker config, so let's keep an eye on it.

**Comment by Keno** [comment]
Action item: If this happens again, check the various `pids.events` files in `/sys/fs/cgroup/pids` to see if any of them report having tripped.

**Comment by Keno** [comment]
@staticfloat and I looked into this more and the problem was using the docker `ulimits` option, which docker warns: "Be careful setting nproc with the ulimit flag as nproc is designed by Linux to set the maximum number of processes available to a user, not to a container", so it was the wrong setting. We wanted `--pids-limit` instead, which sets the limit in the pids cgroup controller.

**Comment by Keno** [comment]
I believe this is fixed. Re-open if not.
