### ISSUE TITLE
Pkg REPL blue color is too dark on Windows

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#38576]
With the default terminal on Windows, the Pkg REPL is very hard to read, especially after video compression on a screen capture or live stream. 

![image](https://user-images.githubusercontent.com/6933510/100279975-c0570f00-2f67-11eb-9122-769433ca9377.png)

We could change the color to cyan (like `@info`), but this would "break tradition".

---

I found that the new Windows Terminal uses a different shade of blue, which is readable:

![image](https://user-images.githubusercontent.com/6933510/100279347-a537cf80-2f66-11eb-8615-cb9ecd7fb3c8.png)

The Julia download instructions [highly recommend that users install the new terminal](https://julialang.org/downloads/platform/#windows), but Julia still launches in powershell, even if it is installed. The average Windows user will not know how to launch the .exe from a terminal -- this is very uncommon on Windows, and the .exe is in a tricky location. And even if you do, it is much easier to just double click the Julia icon on your desktop.

(Sorry for opening a nitpicky windows issue!)

**Comment by KristofferC** [comment]
I thought this was fixed via https://devblogs.microsoft.com/commandline/updating-the-windows-console-colors/

**Comment by fonsp** [comment]
Thanks! From the link you sent:

> ## Where Will I See these Changes?
> If you clean-install a new build of Windows 10 >= 16257, you’ll get the new colors as the default Console scheme.
>
> If you upgraded to this new build of Windows, you will still see the original legacy colors, not the new defaults! This is because we do NOT want to* *overwrite any of your existing custom color settings. 

Ugh windows
