### ISSUE TITLE
Debug macro pull request

### ISSUE THREAD

**Issue by Volker-Weissmann** [JuliaLang/julia#38589]
Hello,
This issue should have been a PR, but I'm not sure which file this should go into.

The macro below has proven to be handy for debugging and should be part of the Julia standard library.

Inspired from [the rust dbg! macro](https://doc.rust-lang.org/std/macro.dbg.html).

Note: I had to add "\" in front of the 4 "```" to get the formatting on github right. Remove those for "\" before inserting the code into the julia standard library.

```julia

"""
    @dbg

Displays all arguments and the current linenumber and filename.

Useful for debugging.

Example:
\```julia
x = 123
y = 321
@dbg(x, y)
@dbg()
\```
would output:
\```
[main.jl:3] x = 123
[main.jl:3] y = 321
[main.jl:4] 
\```
"""
macro dbg(vars...)
    cmds = []
    pref = "[" * Base.Filesystem.relpath(string(__source__.file)) * ":" * string(__source__.line) * "] "
    if length(vars) == 0
        push!(cmds, :(println($pref)))
    end
    push!(cmds, :(temp = []))
    for var in vars
        push!(cmds, :(push!(temp, $(esc(var)))))
    end
    for i in 1:length(vars)
        var = vars[i]
        push!(cmds, :(print($pref)))
        push!(cmds, :(print($(string(var)))))
        push!(cmds, :(print(" = ")))
        push!(cmds, :(display(temp[$i])))
    end
    Expr(:block, cmds...)
end
```

**Comment by FedericoStra** [comment]
Since it is a debugging macro, it should probably at least direct its output to `stderr` with `print(stderr, ...)`.

**Comment by FedericoStra** [comment]
As a matter of fact, the macro can be reduced down to just
```julia
macro dbg(exprs...)
    location = "$(__module__):$(__source__.file):$(__source__.line)"
    quote
        $((:(println(stderr, $location, " ", $(string(ex)), " = ", repr($ex))) for ex in exprs)...)
    end
end
```
You can check that
```julia
i, s, m = 12, "hello", [1 2; 3 4]
@macroexpand @dbg i s m
```
generates the very clean code
```
Main.println(Main.stderr, "Main:REPL[58]:1", " ", "i", " = ", Main.repr(Main.i))
Main.println(Main.stderr, "Main:REPL[58]:1", " ", "s", " = ", Main.repr(Main.s))
Main.println(Main.stderr, "Main:REPL[58]:1", " ", "m", " = ", Main.repr(Main.m))
```
without any temporary arrays.

**Comment by FedericoStra** [comment]
If you are interested, have a look at [this quick implementation I made](https://github.com/FedericoStra/Dbg.jl), which correctly handles arguments which are symbols, strings or expressions (`@dbg var 1+2 "Hello" ...`).

**Comment by mcabbott** [comment]
Are you aware of the existing `@debug` macro?
```julia
julia> @show x y;
x = 1
y = 'β'

julia> ENV["JULIA_DEBUG"] = Main;

julia> @debug "msg" x y
┌ Debug: msg
│   x = 1
│   y = 'β': Unicode U+03B2 (category Ll: Letter, lowercase)
└ @ Main REPL[30]:1
```

**Comment by Volker-Weissmann** [comment]
> Since it is a debugging macro, it should probably at least direct its output to stderr

Ok.

>  Also, the code generation is not quite the cleanest possible.

To be fair, it is litterally the first Julia macro I ever wrote

> without any temporary arrays.

The temporary arrays are there for a reason. If you run `@dbg(3, func())` and func() itself outputs something you wouldn't want this output to be in the middle of the debug output

> If you are interested, have a look at this quick implementation I made, 

It fails if there is no argument provided, mine does not

> Are you aware of the existing @debug macro?

I wish I knew this before I wrote my dbg macro. Closing this issue now.
