### ISSUE TITLE
Unnecesary allocation in mul! with Bidiagonal

### ISSUE THREAD

**Issue by danielwe** [JuliaLang/julia#38585]
This line allocates an unnecessary zero vector when doing matrix multiplication with a `Bidiagonal`:

https://github.com/JuliaLang/julia/blob/377aa809eba31edbf9d73d22b85e801cd4664151/stdlib/LinearAlgebra/src/bidiag.jl#L431

Example:

```julia
using LinearAlgebra
using BenchmarkTools

N = 10
A = rand(N, N)
B = Bidiagonal(rand(N), rand(N - 1), :U)
C = Array{eltype(A)}(undef, N, N)

@btime mul!($C, $A, $B)

# Output:
  139.628 ns (1 allocation: 160 bytes)
```

The allocation could be eliminated without splitting up the combined bidiagonal/tridiagonal multiplication routines by instead returning a dummy zero vector that works something like this:

```julia
struct ZeroVector{T} end

Base.getindex(::ZeroVector{T}, ::Integer) where {T} = zero(T)
```

Is this an acceptable solution?

**Comment by dkarrasch** [comment]
One potential issue I see could be that the code then becomes type-unstable, IIUC. Depending on the value of the `uplo` field, the (off-)diagonal vectors could be a Vector, or a ZeroVector. Not sure if that's an issue, maybe worth benchmarking and seeing the difference.

**Comment by danielwe** [comment]
You're right, this would make `_diag` type unstable. Probably not a good idea then.

Another option could be to write specialized A_mul_B methods for bidiagonal rather than using the same ones for bi&tridiagonal, but with the.combinatorial explosion of methods that's a lot of code. Or, one could store bidiagonals as tridiagonals such that they always carry with them the required zero vector.

In any case, this is probably not anyone's performance bottleneck, I just came across it while tracking down the allocations in my code.
