### ISSUE TITLE
Different behavior of `] activate` command on Windows and Linux

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaLang/julia#38587]
# Ver Info
## Windows
```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
## Linux 
```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

# MWE
1. Create an environment in the current directory and add some package to instantiate.
2. Run `$ julia`
3. Run `] activate`

# Issue
On linux, it activates the environment in the local directory
On Windows, it activates the `v1.5` env

# Expected behaviour
Both behave the same.

I would prefer the linux way, as that makes sense, and to quickly activate `v1.5`, `] activate --shared` should do it.

**Comment by fredrikekre** [comment]
`] activate` like this is a no-op. My guess is that you already had activated the project on your testing on Linux. I assume you can not reproduce if you try
```
$ env -u JULIA_PROJECT -u JULIA_LOAD_PATH julia
```
?

**Comment by DhruvaSambrani** [comment]
Hi @fredrikekre 
Yeah, so I checked it again on Linux, and you are right. I used `julia --project=@.` to start on Linux, but just `julia` on windows, hence the difference.

Its just that `] activate` isn't exactly _noop_, it reactivates the project I started Julia with. Is _this_ expected behaviour?

**Comment by fredrikekre** [comment]
Yes
