### ISSUE TITLE
Base.replace() does not remove spaces for numbers with thousands separator

### ISSUE THREAD

**Issue by Mephistophiles** [JuliaLang/julia#38582]
Julia version: `1.5.3 (2020-11-09)`
OS: `Arch Linux`

How to reproduce:
```julia
replace("5 5 5", ' ' => "") # works
"555"

replace("56 368 016", ' ' => "") # does not works
"56 368 016"
```

**Comment by KristofferC** [comment]
So you want some normalization to happen?

**Comment by ninjin** [comment]
```
julia> c = ' '
' ': Unicode U+202F (category Zs: Separator, space)

julia> replace("56 368 016", c => "")
"56368016"
```

Works as expected, no?

**Comment by ninjin** [comment]
If you want normalisation, the regular expressions are Unicode-aware:

```
julia> replace("56 368 016", r"\s+" => "")
"56368016"
```

**Comment by Mephistophiles** [comment]
> "56 368 016", c => ""

Hmmm, On my julia-build not working


```
julia> c = ' '
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)

julia> replace("56 368 016", c => "")
"56 368 016"
```

**Comment by Mephistophiles** [comment]
> If you want normalisation, the regular expressions are Unicode-aware:
Yep, this variant are works

**Comment by Mephistophiles** [comment]
Oh, I see, In my case space is ASCII character.

**Comment by Mephistophiles** [comment]
Thanks for all! I will use regexp.

**Comment by rfourquet** [comment]
> Thanks for all! I will use regexp.

You can also use a function, e.g. `replace("56 368 016", isspace => "")`

**Comment by Mephistophiles** [comment]
> You can also use a function, e.g. replace("56 368 016", isspace => "")

Thanks! It looks cool!
