### ISSUE TITLE
Distributed.addprocs gives unexpected number of process per machine

### ISSUE THREAD

**Issue by Ankur-deDev** [JuliaLang/julia#38594]
Hi,

I am trying to spawn Julia (v1.5.2) processes on a Kubernetes cluster using the Distributed.addprocs function.
My goal is to have one and only one process per pod and one pod per machine. Everything works as expected when using only one remote machine, but I get the wrong number of processes per machine on for example 12 machines.

Here is my vector of machine specifications, I use a count of 1 process per node:
```
julia> machines
12-element Array{Tuple{String,Int64},1}:
 ("root@172.31.108.104:31036", 1)
 ("root@172.31.111.50:31036", 1)
 ("root@172.31.113.222:31036", 1)
 ("root@172.31.123.184:31036", 1)
 ("root@172.31.139.184:31036", 1)
 ("root@172.31.141.233:31036", 1)
 ("root@172.31.142.0:31036", 1)
 ("root@172.31.154.91:31036", 1)
 ("root@172.31.67.72:31036", 1)
 ("root@172.31.75.41:31036", 1)
 ("root@172.31.76.63:31036", 1)
 ("root@172.31.89.123:31036", 1)
```

Using this, I summon the processes as follow:
```
addprocs( machines
        ; tunnel=true
        , sshflags=["-oStrictHostKeyChecking=no","-i/home/user/.ssh/cluster_rsa"]
        )
```

I do get 12 warnings which indicates that the master process is logging in each of the nodes:

> Warning: Permanently added '[172.31.139.184]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.75.41]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.67.72]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.76.63]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.89.123]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.142.0]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.111.50]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.123.184]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.108.104]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.154.91]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.141.233]:31036' (ECDSA) to the list of known hosts.
> Warning: Permanently added '[172.31.113.222]:31036' (ECDSA) to the list of known hosts.

I do get 12 workers:

```
julia> nworkers()
12
```

Then I use a simple bash script to log in each pod and run the `pgrep julia` command:

> ip["172.31.139.184"]	julia pids[38]
> ip["172.31.142.0"]	julia pids[]
> ip["172.31.154.91"]	julia pids[39]
> ip["172.31.75.41"]	julia pids[41 62]
> ip["172.31.76.63"]	julia pids[39]
> ip["172.31.108.104"]	julia pids[]
> ip["172.31.111.50"]	julia pids[41 45]
> ip["172.31.67.72"]	julia pids[]
> ip["172.31.89.123"]	julia pids[44 51 85 111]
> ip["172.31.113.222"]	julia pids[]
> ip["172.31.123.184"]	julia pids[37]
> ip["172.31.141.233"]	julia pids[]

As you can see, one machine get 4 processes, while some other don't get any.
Based on the documentation, my understanding is that specifying the machines vector with a count of one per machine would achieve the desired goal of one process per machine. I do not get any other warnings on the REPL than the one above.
In what kind of situation would this behavior be expected?

**Comment by Ankur-deDev** [comment]
After investigating more, I get the same behavior if run the ssh command spawning the workers in a shell, so this has nothing to do with Julia. Sorry for that.

**Comment by StefanKarpinski** [comment]
That's good because I had no idea how this could be happening 😬
