### ISSUE TITLE
Is there a julia icon in Windows installation files?

### ISSUE THREAD

**Issue by arisliang** [JuliaLang/julia#38598]
I try to configure to launch julia in Windows terminal in Windows 10. It can point to an icon to make the julia entry in the terminal looks nicer. However I can't find one, like the official triangle 3 dots. Is it anywhere in icon format that Windows terminal can point to?

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/blob/master/contrib/windows/julia.ico
