### ISSUE TITLE
404 link in the docs

### ISSUE THREAD

**Issue by Volker-Weissmann** [JuliaLang/julia#38605]
In the  [docs](https://julia-doc.readthedocs.io/en/latest/manual/performance-tips/) there is the line

>  ... can be used for in-place operations with fused loops and no temporary arrays (see the dot syntax for vectorizing functions).

This link goes to https://julia-doc.readthedocs.io/en/latest/manual/@ref%20man-vectorized , which is 404 not found.

Consider using software to automatically check for 404 links.

**Comment by fredrikekre** [comment]
This is the documentation: https://docs.julialang.org/en/v1/.

**Comment by StefanKarpinski** [comment]
Unfortunately (or fortunately?) we cannot control who hosts unofficial copies of the Julia docs, but readthedocs is not the official location and we can't really help it if they host a broken copy. If you know someone over there you could try to contact them and ask them to try to fix it or take it down.

**Comment by Volker-Weissmann** [comment]
Oh, sorry, I thought that was the official documentation.
Unfortunately I don't know how to contact them. Their github link is also 404.

**Comment by StefanKarpinski** [comment]
How did you end up reading Julia docs on readthedocs? For me that's page two of Google search results on "julia docs" in incognito mode (and logged in).

**Comment by Volker-Weissmann** [comment]
> How did you end up reading Julia docs on readthedocs? For me that's page two of Google search results on "julia docs" in incognito mode (and logged in).

I'm not sure, maybe
https://www.google.com/search?safe=active&client=firefox-b-d&ei=7gTEX5eTI86bkwX53qaYBg&q=julia+array+performance+&oq=julia+array+performance+&gs_lcp=CgZwc3ktYWIQAzIGCAAQCBAeOgQIABBHOgIIADoGCAAQFhAeOgQIABANOggIABAIEAcQHjoGCAAQDRAeOgYIABAHEB5Q5hhY2zBghTJoAXAFeACAAXKIAdYHkgEDNS41mAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwiXwoWizKjtAhXOzaQKHXmvCWMQ4dUDCAw&uact=5

**Comment by StefanKarpinski** [comment]
I have filed an issue on a totally unrelated repo belonging to the GitHub user who create that unofficial readthedocs project over here: https://github.com/rsaladocid/java-util/issues/1
