### ISSUE TITLE
Signature file sometimes fails to be uploaded by CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38602]
In build https://build.julialang.org/#/builders/56/builds/6664/steps/26/logs/stdio the .asc signature file was not found locally, which then caused https://build.julialang.org/#/builders/79/builds/6311 to fail, when it tried to promote this signature file to nightly.

**Comment by staticfloat** [comment]
Should be fixed by https://github.com/JuliaCI/julia-buildbot/commit/23544ccc23caf887d62d6716a8c53af2850b09c0
