### ISSUE TITLE
Precompiled files in system depot not being picked up

### ISSUE THREAD

**Issue by thomasjm** [JuliaLang/julia#38616]
I *think* this is a bug, but please let me know if it's actually expected behavior.

I'm trying to create a Docker image where some Julia packages are preinstalled in a system-wide depot, but the user can also install their own packages in their home folder depot. `JULIA_DEPOT_PATH` is thus set to `/home/user/.julia:/path/to/system/depot`.

When I build the system-wide depot, I call `Pkg.precompile()`. I can see that this produces a bunch of `.ji` files under `[depot path]/compiled/[julia version]`.

However, when I launch Julia and try to use one of the packages, like `using DataFrames`, I get a log message with `Info: Precompiling DataFrames` and a long wait. So it seems like the precompiled files in my system-wide depot aren't being used.

Is using the system-wide precompiled files expected to work? It would be nice to have a snappy user experience when using system-wide packages. Thanks!

(In case it helps, I'm building this system-wide depot using a tool I'm working on for Nix: https://github.com/thomasjm/julia2nix)

**Comment by maleadt** [comment]
> Is using the system-wide precompiled files expected to work?

I created a container that did this a while back, and it does work on Julia 1.5: https://github.com/JuliaGPU/julia-ngc/blob/0b00996a17b3be523a12b2a7a58f7171924dd6d3/Dockerfile#L26-L44
What version of Julia are you using?

**Comment by thomasjm** [comment]
I'm using Julia 1.5.

I notice you're setting some files under `/usr/local/share` to have 644 permissions. I don't want to have anything writable under a system directory so all the write bits are off for mine. Could that be significant?

**Comment by maleadt** [comment]
That's GPUCompiler-specific. and doesn't matter for regular precompilation files.

**Comment by thomasjm** [comment]
I looked at the `.ji` files generated by `using Plots` and they are slightly different:

```
# Depot version
/nix_frozen/store/0822gaypahvqq0l9hq8gmf4z9aa2vkrw-julia-depot/compiled/v1.5/Plots/ld3vC_GBDRr.ji
# Home folder version
/home/user/.julia/compiled/v1.5/Plots/ld3vC_dGa4q.ji
```

It looks like the name consists of two slugs, where the first one matches and the second one is different...

**Comment by thomasjm** [comment]
Oh, I figured it out. By launching with `JULIA_DEBUG=loading` I was able to see that my system `.ji` files were being rejected because the mtime had changed from the source file. Thanks @maleadt !
