### ISSUE TITLE
Business Logic Error or Logical Error 

### ISSUE THREAD

**Issue by Kshitish555** [JuliaLang/julia#38617]
I found a logical error vulnerability on your lang. Julia lang gives the wrong output. This lang does not understand the mathematical problem. 

println(10 > 3 && 87622897 ^ 7833884848*100 <= 1000000 * 10000000 )

This argument should be true but it prints false. This is the logical error vulnerability. Try this code in another language too. You find out they print true because the argument is true but unfortunately Julia prints false. Because Julia does not understand this. 

Thank you & happy hacking

**Comment by tomaklutfu** [comment]
Why do younthink it is true? Have you try it in C or any machine bits dependent language? It is false because of that large exponentiation. It is not vulnerability or bug. It is simply modulus operations of CPU type integers. If you'd like to have big numbers represented exactly make base or exponent a big number.

**Comment by KristofferC** [comment]
See https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior.

**Comment by Kshitish555** [comment]
Thank you for response. But you are wrong here. This is not a CPU type integers. This simple mathematical problem problem and every programming lang easy give the answer of these questions.  Mathematic is base of any lang. Let try this python: 
<img width="960" alt="In the Python " src="https://user-images.githubusercontent.com/62928712/100586431-2996a380-3315-11eb-948b-6377f8152c01.png"> Look this image

**Comment by Kshitish555** [comment]
> See https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior.

Why you close this issue without understanding it properly. Reopen it

**Comment by timholy** [comment]
We understand it very well. Try it in C.

In building a language, you have to choose: fast arithmetic or arbitrary-precision arithmetic. C and Julia have chosen fast by default, other languages choose arbitrary precision by default. It's just a choice you have to make. Machines are called "64-bit" for a reason.https://en.wikipedia.org/wiki/Integer_overflow

**Comment by Kshitish555** [comment]
Thank you all of you

**Comment by Kkshitish** [comment]
My friend you doing good job and I hope near future you will find new bug on the Julia. I also working same type of problem on Julia. It is right Julia give wrong output. I will report about this  very soon.

**Comment by Kkshitish222** [comment]
Yes my friend, this is a very good job. I noticed this problem too Julia give not right output. It is simple math every lang should be able to do it.

**Comment by timholy** [comment]
Please stop. Python can't solve this problem either:
```
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 87622897 ** 7833884848
(waiting for many minutes, then hits Ctrl-C to avoid frying my CPU unnecessarily...)
```

Or are you confused about the fact that `^` is bitwise `xor` in python and exponentiation in Julia? In Julia, the xor is `⊻`, which you can get with `\xorTAB`.
