### ISSUE TITLE
XOR 

### ISSUE THREAD

**Issue by Kshitish555** [JuliaLang/julia#38618]
a = 10
b = 10

if (a == 10 && xor(b == a) && b ==10)
   println("yes")

else
   println("no")

end

The output of this code is yes. I just want know XOR keyword execute here or not. If it execute then tell me. Why answer is not affecting by this. XOR is working or not. Please share your important answer. Look I want answer of this question, I do not know this is the bug or not. The Result: 
<img width="960" alt="Screenshot 2020-11-30 143107" src="https://user-images.githubusercontent.com/62928712/100589511-387f5500-3319-11eb-95b8-aabe692fd4ec.png">

**Comment by KristofferC** [comment]
Please ask questions at https://discourse.julialang.org/
