### ISSUE TITLE
slower than R when calculate `exp.(a)` where a is an `Array{Float64,1}` with many elements.

### ISSUE THREAD

**Issue by Neutron3529** [JuliaLang/julia#38629]
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.ustc.edu.cn/julia
```
I found that Julia is slower computing `exp`,`log`for an Array object.
with R code, I have:
```
> system.time({a=rnorm(20000000)});system.time({b=exp(a)})
   user  system elapsed 
  0.943   0.038   0.982 
   user  system elapsed 
  0.137   0.030   0.167 
> system.time({a=rnorm(200000000)});system.time({b=exp(a)})
   user  system elapsed 
  9.523   0.296   9.825 
   user  system elapsed 
  1.243   0.320   1.564 
```
but with Julia:
```
julia> using Distributions;

julia> d=Normal();

julia> GC.gc();@time a=rand(d,20000000);
  0.242169 seconds (64.54 k allocations: 155.807 MiB, 4.22% gc time)

julia> GC.gc();@time a=rand(d,20000000);
  0.231776 seconds (2 allocations: 152.588 MiB, 15.22% gc time)

julia> GC.gc();@time a=rand(d,20000000);
  0.197419 seconds (2 allocations: 152.588 MiB)

julia> GC.gc();@time exp.(a);
  0.275906 seconds (139.76 k allocations: 160.017 MiB, 2.51% gc time)

julia> GC.gc();@time exp.(a);
  0.235892 seconds (4 allocations: 152.588 MiB)

julia> GC.gc();@time exp.(a);
  0.237129 seconds (4 allocations: 152.588 MiB)

julia> GC.gc();@time b=exp.(a);
  0.236192 seconds (4 allocations: 152.588 MiB)

julia> GC.gc();@time b=exp.(a);
  0.236897 seconds (4 allocations: 152.588 MiB)

julia> GC.gc();@time b=exp.(a);
  0.237033 seconds (4 allocations: 152.588 MiB)
```
There is no suprise that rnorm is quite slower compare to Julia, but, if we want to calculate things in a vector, R is faster than Julia(even with `julia -O3 --math-mode=fast --check-bounds=no --cpu-target skylake`, things not changed.)
```
julia> GC.gc();@time b=sin.(log.(abs.(a)));
  0.465077 seconds (8 allocations: 152.588 MiB)

julia> GC.gc();@time b=sin.(log.(abs.(a)));
  0.464735 seconds (8 allocations: 152.588 MiB)

> system.time({a=rnorm(20000000)});system.time({b=sin(log(abs(a)))})
   user  system elapsed 
  0.919   0.050   0.970 
   user  system elapsed 
  0.367   0.033   0.400 
```
I tried `map`,`for`-loop and `exp.()`, found `exp.()` is the fastest way among these methods.
but it is still slower than R.
Are there any improvement available?

**Comment by oscardssmith** [comment]
Yep! Julia 1.6 is already much faster at this. https://github.com/JuliaLang/julia/pull/36761

**Comment by Neutron3529** [comment]
> Yep! Julia 1.6 is already much faster at this. #36761

Thank you for both your reply and your PR.
I tried replace `math.jl` in `/usr/share/julia/base/` to the current one, but nothing(include the docstring)changed.
How can I re-compile base?
or I have to compiling the whole Julia?

**Comment by Neutron3529** [comment]
Is an AVX version for Array worth a PR?

I'm new to Julia so that I don't know how to write a plantform specific version of these functions.
Will you work on it?

**Comment by oscardssmith** [comment]
This version already vectorizes under certain conditions. Also, `LoopVectorization` provides a macro which makes this even more robust.

**Comment by Neutron3529** [comment]
> This version already vectorizes under certain conditions. Also, `LoopVectorization` provides a macro which makes this even more robust.

Thanks for your reply.
I waste 2 hours and finally realized that SIMD instructions gain no performance here.
