### ISSUE TITLE
Issues with modifying immutable structures

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#38622]
I encountered this behaviour working with immutable structures and it took (for me) a lot of time to trace it back to what happened behind the scenes.
 
I am confused with the following behaviour when working with immutable structures, for which I found no explanation in any documentation.

The first example illustrates the expected behaviour:

```
julia> a = ones(1,1); b = ones(1,1);

julia> s = (a = a, b = b)  # define named tuple s 
(a = [1.0], b = [1.0])

julia> s.a = zeros(1,1)  # this  produces an error because the structure is immutable
ERROR: setfield! immutable struct of type NamedTuple cannot be changed
Stacktrace:
 [1] setproperty!(::NamedTuple{(:a, :b),Tuple{Array{Float64,2},Array{Float64,2}}}, ::Symbol, ::Array{Float64,2}) at .\Base.jl:34 
 [2] top-level scope at REPL[77]:1

julia> s.a[:,:] = -ones(1,1)  # this modifies the muttable array s.a of the immutable structure s
1×1 Array{Float64,2}:
 -1.0
julia> s   # the modification of s.a indeed happened
(a = [-1.0], b = [1.0])

```
Now, the following unexpected behaviour (at least for me), led to unexpected errors in my software:

```
julia> a = ones(1,1); b = ones(1,1);

julia> s = (a = a, b = b)  # define named tuple s 
(a = [1.0], b = [1.0])

julia> a[:,:] = -ones(1,1)  # change array a (should have no effect on s)
1×1 Array{Float64,2}:
 -1.0

julia> s     # surprise (to me), the array s.a has been changed
(a = [-1.0], b = [1.0])

```

In my opinion, this modification of `s.a` should not happen. 

To be safe in avoiding such effects,  the only remedy seems to always make copies when defining `s`:
`
 s = (a = copy(a), b = copy(b))
`
Certainly, I would prefer to avoid making always copies of arrays when constructing structures !

**Comment by KristofferC** [comment]
Questions are better off at https://discourse.julialang.org/.

What happens here is that you create two bindings to the same array, both `a` and `s.a` point to the same object so any mutation of the object will be visible no matter through what binding (label) you reach that object. The fact that assignment (`=`) does not do any copying is quite fundamental in Julia.
