### ISSUE TITLE
Wrong Output

### ISSUE THREAD

**Issue by Kkshitish** [JuliaLang/julia#38635]
I found a logical error vulnerability on your lang. Julia language gives the wrong output. This language does not understand the mathematical problem.

println(5 + 2 == 7 && 10 <= 1232 && 100 ^ 1000 >= 128)

This argument should be true but it prints false. This is the logical error vulnerability. Try this code in another language too. You find out they print true because the argument is true but unfortunately Julia prints false. Because Julia does not understand this. Even in C language if you do same thing then the output is true.

**Comment by fredrikekre** [comment]
Didn't you just open #38617? This is not a bug, and please direct further questions to https://discourse.julialang.org/.

**Comment by timholy** [comment]
You're also just wrong:
```c
#include <stdio.h>

int main() {
    // C doesn't have an integer exponetiation operator, so let's write one
    int i = 1;
    for (int j = 0; j < 1000; j++)
        i *= 100;
    printf("answer is: %d\n", i);
}
```
```sh
tim@diva:/tmp$ gcc math.c -o math
tim@diva:/tmp$ ./math
answer is: 0
```

**Comment by StefanKarpinski** [comment]
@Kkshitish / @Kkshitish222 / @Kshitish555: you and all your sock puppet accounts are very close to getting blocked by the @JuliaLang org. Cut it out.
