### ISSUE TITLE
[PPC] Misscompilation due to pointer comparision

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#38641]
```
julia> div(-11, 2, RoundUp)
-4
```

Julia 1.5 works correctly so I suspect an LLVM bug.

**Comment by vchuravy** [comment]
Fixed by #38686

**Comment by JeffBezanson** [comment]
It's great, but how did that PR fix this? I thought it would only affect performance.

**Comment by vchuravy** [comment]
Filed upstream as https://bugs.llvm.org/show_bug.cgi?id=48388

**Comment by vchuravy** [comment]
Let's keep this open so that I don't loose track of it.

**Comment by JeffBezanson** [comment]
Wow that's a pretty crazy bug.

**Comment by vchuravy** [comment]
Proposed fix upstream https://reviews.llvm.org/D93092
