### ISSUE TITLE
"killing by quick kill watchdog" failure in threads test

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#38640]
https://build.julialang.org/#/builders/52/builds/5907/steps/5/logs/stdio

https://build.julialang.org/#/builders/34/builds/6420/steps/5/logs/stdio

**Comment by KristofferC** [comment]
"quick kill watchdog" is so scary :scream:

**Comment by vtjnash** [comment]
We haven't seen this again since we turned on `rr`

**Comment by vtjnash** [comment]
(though I think there may still be an upstream bug in libunwind-gnu, we've also improved our unwinder info, so hopefully we aren't hitting that bug as frequently anymore)
