### ISSUE TITLE
Hang in Artifacts test on ci

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38670]
https://build.julialang.org/#/builders/34/builds/6551/steps/5/logs/stdio
https://build.julialang.org/#/builders/33/builds/5920/steps/5/logs/stdio

These tests hung at the same time, so quite possibly the package server had a hickup, but if so, we're probably missing some fallback or error path.

**Comment by vtjnash** [comment]
Don't know how to repro this, since we haven't been seeing it recur
