### ISSUE TITLE
Out-of-tree build broken

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#38676]
```
$ git clone https://github.com/JuliaLang/julia
$ cd julia
$ make O=build configure
$ make -j5
make[1]: *** No rule to make target 'jl_exports.h', needed by 'loader_exe.o'.  Stop.
make: *** [/home/tim/Julia/tmp/julia/Makefile:79: julia-cli-release] Error 2
```

Probable cause: https://github.com/JuliaLang/julia/pull/38160

**Comment by vchuravy** [comment]
The headers here need their prefix added https://github.com/JuliaLang/julia/blob/96a45ae486afba79efe69ab89c17b9397b13523e/cli/Makefile#L9 (Didn't get to it yesterday evening)
