### ISSUE TITLE
change @__FILE__, @__DIR__, etc. to give right runtime answer

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#38682]
Currently these macros are expanded at build time to an absolute path based on the source location at build time. This means that any use of them in precompilable packages causes the resulting `.ji` files to be non-relocatable. It also means that any use of them in a stdlib will break the resulting Julia sysimg by causing it to be non-relocatable. I would propose that instead of expanding to a static path, these macros be changed to expand to code that will give the correct path at runtime. This is a technically breaking change, but I suspect that 99% of uses won't notice and changing this will silently make people's code do what they thought it was doing already.

**Comment by KristofferC** [comment]
> This means that any use of them in precompilable packages causes the resulting .ji files to be non-relocatable.

FWIW, if they use `@__DIR__` at runtime they are likely to be non-relocatable anyway since if you transfer something as a sysimage or .ji file, it is unlikely the original files exist anyway.

**Comment by StefanKarpinski** [comment]
True, but `pathof` and `pkgdir` at least give a somewhat correct answer at runtime. Maybe there's just no way to do this correctly if we anticipate that packages might be loaded directly from `.ji` files with the source files gone.

**Comment by KristofferC** [comment]
`pathof` and `pkgdir` also "freeze" but instead of when the package is precompiled it is when the package is loaded. So if you put them in a sysimage, those will also give the old values.

**Comment by vtjnash** [comment]
Perhaps we could reserve a special path representation to represent a pkgdir in a path, which becomes an absolute path when calling `realpath` or `expanduser`, such as `@NetworkOptions/data/config.toml`

But closing in favor of #38696, which seems slightly less speculative and relatively straightforward

**Comment by omus** [comment]
As this is the only issue to mention both `pkgdir` and "sysimage" I just wanted to mention that the following code works better in sysimages that are relocated:
```julia
pkg = Base.identify_package(...)
pkg_dir = dirname(dirname(Base.locate_package(pkg)))  # Naive logic here, could be improved for extensions
```
This was used in https://github.com/JuliaTime/TimeZones.jl/pull/479 as a work around

**Comment by DilumAluthge** [comment]
The best long-term solution is probably something like https://github.com/JuliaLang/julia/pull/56053
