### ISSUE TITLE
throw BoundsError could be more descriptive for Bool array indexing

### ISSUE THREAD

**Issue by JeffFessler** [JuliaLang/julia#38685]
The error message for a `BoundsError` with a `BitArray` is somewhat verbose yet missing key info:

```julia
julia-1.5.3> ones(9,9)[trues(8,8)]
ERROR: BoundsError: attempt to access 9×9 Array{Float64,2} at index [Bool[1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1]]
```
Because a size mismatch is the most likely (perhaps only?) cause of an error for this type of indexing, it would be more informative for the error message to report the *size* of the Bool array, something like this:
```
ERROR: BoundsError: attempt to access 9×9 Array{Float64,2} with 8×8 BitArray{2}
```

In contrast, for linear array indexing the error is quite helpful:
```julia
julia-1.5.3> ones(4)[5]
ERROR: BoundsError: attempt to access 4-element Array{Float64,1} at index [5]
```

I would have submitted a PR but I could not find the code where this message is generated.  Somewhere in the `throw` code perhaps?  Where is that code?

**Comment by mbauman** [comment]
That'd be great!  The change would go as another branch here:

https://github.com/JuliaLang/julia/blob/49b8e61a80b8108ca0a23f8075a0d0508b6947c7/base/errorshow.jl#L46-L50

**Comment by JeffFessler** [comment]
Great - I'll work on a PR soon - thanks!
