### ISSUE TITLE
Do you guys know, how to using this languages in spaces (not just space, but importantly spaces)?

### ISSUE THREAD

**Issue by bahasalien** [JuliaLang/julia#38697]
I will prefer if the community having answer for that,.. so our country can used to.
maybe do some method or whatever it takes to growing the community for us.

Thank you.

**Comment by KristofferC** [comment]
Hello, questions are better off at discourse.julialang.org/.

**Comment by bahasalien** [comment]
I want here not there.

**Comment by KristofferC** [comment]
This is for bug reports. For community discussions and questions, use https://discourse.julialang.org/ :)
