### ISSUE TITLE
julia crashes on very simple code in REPL

### ISSUE THREAD

**Issue by zbartab** [JuliaLang/julia#38706]
Dear Developers,

When I am running these in the REPL there is no problem.

julia> include("good.jl")
probak (generic function with 2 methods)

julia> c,f = probak()
([[1, 2, 3]], [1.0954451150103321])

On the other hand, running these crashes julia:

julia> include("bad.jl")
probak (generic function with 2 methods)

julia> c,f = probak()

The only difference between good.jl and bad.jl is this line (both attached):
	randn() < 0.0 && return [4,5,6], 1.233
vs
	randn() < 0.0 && return [4,5,6]

Runing at the command line, (e.g. `julia bad.jl`) runs without problems.

Here are the crash report:

julia> include("bad.jl")
probak (generic function with 2 methods)

julia> c,f = probak()
Illegal inttoptr
          %23 = ptrtoint %jl_value_t addrspace(10)* %20 to i64, !dbg !19
Illegal inttoptr
          %24 = inttoptr i64 %23 to i64 addrspace(13)*, !dbg !19

signal (6): Aborted
in expression starting at REPL[2]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f8bd56a42f0)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-10.so.1 (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-10.so.1 (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-10.so.1 (unknown line)
unknown function (ip: 0x7f8bd5797537)
unknown function (ip: 0x7f8bd579a004)
unknown function (ip: 0x7f8bd579acce)
unknown function (ip: 0x7f8bd579c12a)
unknown function (ip: 0x7f8bd579cefd)
unknown function (ip: 0x7f8bd579dec8)
unknown function (ip: 0x7f8bd572d0cb)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f8bd5741854)
unknown function (ip: 0x7f8bd57414f5)
unknown function (ip: 0x7f8bd5742087)
unknown function (ip: 0x7f8bd5742b1e)
unknown function (ip: 0x7f8bd575b028)
unknown function (ip: 0x7f8bd575b5e8)
jl_toplevel_eval_in at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
eval at ./boot.jl:331
eval_user_input at /build/julia-g9LvxD/julia-1.5.3+dfsg/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
repl_backend_loop at /build/julia-g9LvxD/julia-1.5.3+dfsg/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
start_repl_backend at /build/julia-g9LvxD/julia-1.5.3+dfsg/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
#run_repl#37 at /build/julia-g9LvxD/julia-1.5.3+dfsg/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
run_repl at /build/julia-g9LvxD/julia-1.5.3+dfsg/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
#807 at ./client.jl:399
jfptr_YY.807_67558.clone_1 at /usr/lib/x86_64-linux-gnu/julia/sys.so (unknown line)
unknown function (ip: 0x7f8bd5738a8f)
jl_f__apply_latest at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
run_main_repl at ./client.jl:383
exec_options at ./client.jl:313
_start at ./client.jl:506
jfptr__start_56896.clone_1 at /usr/lib/x86_64-linux-gnu/julia/sys.so (unknown line)
unknown function (ip: 0x55b617ea8755)
unknown function (ip: 0x55b617ea8332)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x55b617ea83d9)
Allocations: 771279 (Pool: 771191; Big: 88); GC: 1
Aborted

And here is versioninfo()
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3
 _/ |\__'_|_|_|\__'_|  |  Debian ⛬  julia/1.5.3+dfsg-2
|__/                   |

julia> using InteractiveUtils

julia> versioninfo()
Julia Version 1.5.3
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)

Best wishes,
Zoltan

###################################
good.jl:

function proba(;α = 0.1)
	randn() < 0.0 && return [4,5,6], 1.233
	return [1,2,3], 1.2^α
end

function probak(α = 0.5)
	kont1 = Array{Array{Int,1},1}()
	kont2 = Array{Float64, 1}()
	k1, k2 = proba(α = α)
	push!(kont1, k1)
	push!(kont2, k2)
	return kont1, kont2
end
###################################

###################################
bad.jl

function proba(;α = 0.1)
	randn() < 0.0 && return [4,5,6]
	return [1,2,3], 1.2^α
end

function probak(α = 0.5)
	kont1 = Array{Array{Int,1},1}()
	kont2 = Array{Float64, 1}()
	k1, k2 = proba(α = α)
	push!(kont1, k1)
	push!(kont2, k2)
	return kont1, kont2
end
###################################

**Comment by KristofferC** [comment]
> Debian ⛬ julia/1.5.3+dfsg-2

Does thus happen with the official binaries at https://julialang.org/downloads/?

**Comment by zbartab** [comment]
With the official version this goes away. Should I turn with this to the debian maintainer?

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> include("/home/apa/tmp/bad.jl")
probak (generic function with 2 methods)

julia> c,f = probak()
([[1, 2, 3]], [1.0954451150103321])

julia> using InteractiveUtils

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by KristofferC** [comment]
> Should I turn with this to the debian maintainer?

Yes, that seems reasonable to me. We don't have much control over the way repos pacakge Julia.
