### ISSUE TITLE
Unicode conversion from Symbol to String yields a string different from intended string

### ISSUE THREAD

**Issue by JinraeKim** [JuliaLang/julia#38718]
I’m often use a conversion from Symbol to String. For example,
```julia
String(:a) == "a" # true
```
However, when adding \dot, it yields a string which is different from intended string. For example,
```julia
String(:ȧ) == "ȧ"  # false
```
I have no idea how to result in the intended result. If it's not intended, I would recommend to fix it.

Note: Here's [the discussion](https://discourse.julialang.org/t/string-conversion-from-symbol-with-unicode-does-not-yield-a-string-which-is-intended-to-be-the-same/51289/3) in JuliaDiscourse.

**Comment by StefanKarpinski** [comment]
Julia symbols are Unicode normalized:
```jl
julia> Unicode.normalize(String(:ȧ)) == Unicode.normalize("ȧ")
true
```
