### ISSUE TITLE
Error on ignored type parameter in left-hand side of type alias

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#38715]
```julia
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1653 (2020-12-04)
 _/ |\__'_|_|_|\__'_|  |  Commit 0db72ee7d2* (1 day old master)
|__/                   |

julia> MyType{K, T} = Set{T}
Set
```

Not mentioned in https://docs.julialang.org/en/v1/manual/types/#UnionAll-Types

Sorry in advance if this is a duplicate issue.

**Comment by Seelengrab** [comment]
Since they're equivalent, superfluos type parameters are no longer printed on 1.6.

```
julia> Set === Set{T} where T
true
```

**Comment by vtjnash** [comment]
The LHS is syntax for
```
julia> MyType = Set{T} where {K, T}
Set
```

And the unused `K` gets dropped, so you end up with `MyType === Set`

**Comment by goretkin** [comment]
@Seelengrab I think you misunderstood my concern

@vtjnash Thanks for the explanation. I'm not readily finding another conversation about unused type parameters, and that seems to be the reason underlying the non-error on what I want to error. As a side note, I wish you would not close the issues _so_ quickly. Perhaps we want to improve the documentation. Or we want to acknowledge there may be something going on, but still won't fix it, in which case we definitely want to document it. In any case, I know a closed issue doesn't mean there can't be a discussion, so:

Currently, `MyType = Set{T} where {K, T}` and `MyType{K, T} = Set{T}` lower slightly differently. Using a simpler example:

```julia
julia> Meta.@lower MyType{K} = Int64
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─      const MyType
│        K = Core.TypeVar(:K)
│   %3 = Core.UnionAll(K, Int64)
│        MyType = %3
└──      return %3
))))

julia> Meta.@lower MyType = Int64 where {K}
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─      K = Core.TypeVar(:K)
│   %2 = Core.UnionAll(K, Int64)
│        MyType = %2
└──      return %2
))))
```

so even if `Int64 where {K}` does not error, that doesn't seem to force `MyType{K} = Int64` to not error as well.

**Comment by vtjnash** [comment]
Closing issues helps others focus on other work. It's an aspect of triage and email management. We almost never lock them, since continued discussion and PR are welcome.

Yes, more precisely, there's a `const` decl also, but that didn't seem relevant to your question. To which, what is your question?

**Comment by goretkin** [comment]
The question is: Can we raise an error on `MyType{K, T} = Set{T}`?
