### ISSUE TITLE
CI Hang in UDP test

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38711]
https://build.julialang.org/#/builders/33/builds/6026/steps/5/logs/stdio

**Comment by Keno** [comment]
https://build.julialang.org/#/builders/52/builds/6358/steps/5/logs/stdio

**Comment by Keno** [comment]
https://build.julialang.org/#builders/4/builds/7332

**Comment by Keno** [comment]
https://build.julialang.org/#/builders/34/builds/7454/steps/5/logs/stdio

**Comment by ViralBShah** [comment]
Close this?

**Comment by Keno** [comment]
Still happening https://buildkite.com/julialang/julia-master/builds/49732/steps/canvas?jid=01988a7b-7fb8-4c7a-ab1d-ecc1c492a617

**Comment by xal-0** [comment]
On v1.13 rc2 FreeBSD: https://buildkite.com/organizations/julialang/pipelines/julia-ci/builds/253/jobs/019fef45-ca26-4422-81be-83ec5cb8a291/log
