### ISSUE TITLE
Timeout error in mac Distributed test

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38712]
https://build.julialang.org/#/builders/79/builds/6612/steps/5/logs/stdio

I moved this to node 1, so it's not an overload condition

**Comment by Keno** [comment]
Also https://build.julialang.org/#/builders/79/builds/6613/steps/5/logs/stdio, which looks slightly different.

**Comment by Keno** [comment]
And https://build.julialang.org/#/builders/79/builds/6616/steps/5/logs/stdio

**Comment by Keno** [comment]
One thing I'm wondering is when does ETIMEDOUT happen? That's a kernel error on the receive side. Would we be seeing that if the server doesn't get around to `accept`'ing the connection in time?

**Comment by Keno** [comment]
Looks like this may not be mac specific. Here's similar issues in win32:
https://build.julialang.org/#/builders/61/builds/6242
https://build.julialang.org/#/builders/61/builds/6236

**Comment by Keno** [comment]
If I'm reading this correctly, the message handler loop is stuck waiting for the uv_write of the result of the take! to complete.

**Comment by Keno** [comment]
I may have a lead:
```
Distributed.RemoteException(pid=3, captured=Base.CapturedException(ex=AssertionError(msg="id > 0"), processed_bt=Array{Any, (12,)}[
  (Base.StackTraces.StackFrame(func=:Worker, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl"), line=132, linfo=nothing, from_c=false, inlined=false, pointer=0x00000001253dc951), 1),
  (Base.StackTraces.StackFrame(func=:Worker, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl"), line=130, linfo=nothing, from_c=false, inlined=true, pointer=0x00000001253dcbaa), 1),
  (Base.StackTraces.StackFrame(func=:worker_from_id, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl"), line=1089, linfo=nothing, from_c=false, inlined=false, pointer=0x00000001253dcbaa), 1),
  (Base.StackTraces.StackFrame(func=:worker_from_id, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/cluster.jl"), line=1079, linfo=nothing, from_c=false, inlined=true, pointer=0x000000012541ed8d), 1),
  (Base.StackTraces.StackFrame(func=Symbol("#remotecall_fetch#146"), file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl"), line=421, linfo=nothing, from_c=false, inlined=true, pointer=0x000000012541ed8d), 1),
  (Base.StackTraces.StackFrame(func=:remotecall_fetch, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl"), line=421, linfo=nothing, from_c=false, inlined=true, pointer=0x000000012541ed8d), 1),
  (Base.StackTraces.StackFrame(func=:call_on_owner, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl"), line=494, linfo=nothing, from_c=false, inlined=true, pointer=0x000000012541ed8d), 1),
  (Base.StackTraces.StackFrame(func=:take!, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl"), line=626, linfo=nothing, from_c=false, inlined=false, pointer=0x000000012541ed8d), 1),
  (Base.StackTraces.StackFrame(func=Symbol("#106"), file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl"), line=278, linfo=nothing, from_c=false, inlined=false, pointer=0x000000012540b7ef), 1),
  (Base.StackTraces.StackFrame(func=:run_work_thunk, file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl"), line=63, linfo=nothing, from_c=false, inlined=false, pointer=0x000000012540ba58), 1),
  (Base.StackTraces.StackFrame(func=Symbol("macro expansion"), file=Symbol("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl"), line=278, linfo=nothing, from_c=false, inlined=true, pointer=0x000000012540bcc5), 1),
  (Base.StackTraces.StackFrame(func=Symbol("#105"), file=Symbol("./task.jl"), line=406, linfo=nothing, from_c=false, inlined=false, pointer=0x000000012540bcc5), 1)]))
```

**Comment by Keno** [comment]
Sample network traffic with the worker that errored: https://gist.github.com/Keno/a71901e5303d8391ce440bd74b524aff

**Comment by Keno** [comment]
Alright, I believe the issue is that WeakKeyDict is unsound. I have an idea how to patch it.

**Comment by vtjnash** [comment]
It does need some significant work (https://github.com/JuliaLang/julia/pull/38180), but had felt risky trying to change it and merge it that near to a release. Should I try to push that forward?

**Comment by Keno** [comment]
Ok, bingo. I understand what the issue here is now. But, man, let me tell you tracking this down was a bear. I probably spent a good 10-12 hours on this yesterday. This is the kind of issue that I usually need rr for. What's happening is the following:

As seen in the network trace, we send the same `take!(::RemoteChannel)` request twice to the same worker, which then deserializes it, and uniques it using a WeakKeyDict. The first time around, the table is empty and we just insert it. However, the second time around, we run into an unsoundness in WeakKeyDict, where it can return a value from `getkey`, but have it be finalized in between the time that it is retrieved from the table and that the new root is established for the return value of `getkey`. The window of opportunity for this to happen is very small: The value needs to be GC'ed after the WeakRef is taken out of the underlying dict, but before it is taken out of the WeakRef itself. This doesn't usually happen at all, because the `getkey` function doesn't have any allocations. However, what's happening here is that during the second time around, we need to compare the new key to the old key, which triggers compilation of `Tuple{typeof(Base.isequal), Distributed.RemoteChannel{Base.Channel{Any}}, WeakRef}`, which then allocates and triggers a GC run. The original value gets GC'd and gets scheduled for finalization. However, because we are in a critical section finalizers are inhibited, so the finalizer doesn't actually run. Then, we take the value out of the WeakRef, re-establishing a root for it, but it's still in the finalizer list, so as soon as we leave the critical section, the finalizer runs, and deletes the value we just looked up.

**Comment by Keno** [comment]
> It does need some significant work (#38180),

I came up with mostly the same change since I didn't remember that PR. Let me review it closely, since I understand the issues now.

**Comment by Keno** [comment]
We believe at least one of the underlying root causes here to be fixed. I'm closing this issue and if we see it again, we should open another issue with a new collection of logs to avoid being misled by an old issue for which the root cause was fixed.
