### ISSUE TITLE
Regex doesn't appear in online docs search

### ISSUE THREAD

**Issue by lbilli** [JuliaLang/julia#38739]
Many times I've found myself searching for `Regex` in the Julia online docs hoping to find an entry for `Base.Regex` or something similar, but always in vain. 
It looks like `Regex` docstring is unreachable from within the online docs.
What does it need to be done to have it included?

**Comment by mgkuhn** [comment]
Presumably a line `Base.Regex` needs to be added to [doc/src/base/strings.md](https://github.com/JuliaLang/julia/blob/master/doc/src/base/strings.md), probably near `Base.@r_str`.
See [Documenter syntax](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/).
