### ISSUE TITLE
Locating Gurobi installation

### ISSUE THREAD

**Issue by alexjacq** [JuliaLang/julia#38759]
Hi,

I tried to update my version of Gurobi but cannot install it into Julia. I get the following message. I am confused because the path is correct, Julia can clearly see the correct files (they are listed) but then it says that it cannot find the required files. Any help would be much appreciated. Thank you!

Pkg.build("Gurobi")
   Building Gurobi → `~/.julia/packages/Gurobi/7YNJV/deps/build.log`
┌ Error: Error building `Gurobi`: 
│ ERROR: LoadError: Unable to locate Gurobi installation. If the advice above did not help,
│ open an issue at https://github.com/JuliaOpt/Gurobi.jl and post the full
│ print-out of this diagnostic attempt.
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/alexandre/.julia/packages/Gurobi/7YNJV/deps/build.jl:154
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /Users/alexandre/.julia/packages/Gurobi/7YNJV/deps/build.jl:152
│ Unable to locate Gurobi installation. Running some common diagnostics.
│ 
│ Gurobi.jl only supports the following versions:
│ 
│  - gurobi90
│  - gurobi81
│  - gurobi80
│  - gurobi75
│  - gurobi70
│ 
│ Did you download and install one of these versions from gurobi.com?
│ 
│ 
│ Found GUROBI_HOME =  /Library/gurobi910/mac64
│ 
│ Does this point to the correct install location?
│ - on Windows, this might be `C:\Program Files\gurobi810\win64\`
│ - alternatively, on Windows, this might be `C:/Program Files/gurobi810/win64/`
│ - on OSX, this might be `/Library/gurobi810/mac64/`
│ - on Unix, this might be `/home/my_user/gurobi810/linux64/`
│ 
│ Note: this has to be a full path, not a path relative to your current
│ directory or your home directory.
│ 
│ We're going to look for the Gurobi library in this directory:
│     /Library/gurobi910/mac64/lib
│ 
│ That directory has the following files:
│ 
│  - /Library/gurobi910/mac64/lib/gurobi-javadoc.jar
│  - /Library/gurobi910/mac64/lib/gurobi.jar
│  - /Library/gurobi910/mac64/lib/gurobi.py
│  - /Library/gurobi910/mac64/lib/gurobi91.netstandard20.dll
│  - /Library/gurobi910/mac64/lib/gurobi91.netstandard20.xml
│  - /Library/gurobi910/mac64/lib/libGurobiJni91.jnilib
│  - /Library/gurobi910/mac64/lib/libgurobi91.dylib
│  - /Library/gurobi910/mac64/lib/libgurobi91_light.dylib
│  - /Library/gurobi910/mac64/lib/libgurobi_c++.a
│  - /Library/gurobi910/mac64/lib/libgurobi_g++4.2.a
│  - /Library/gurobi910/mac64/lib/python2.7
│  - /Library/gurobi910/mac64/lib/python3.6
│  - /Library/gurobi910/mac64/lib/python3.7
│  - /Library/gurobi910/mac64/lib/python3.8
│  - /Library/gurobi910/mac64/lib/python3.9
│  - /Library/gurobi910/mac64/lib/rootcert.pem
│ 
│ We were looking for (but could not find) a file named like
│ `libgurobiXXX.so`, `libgurobiXXX.dylib`, or `gurobiXXX.dll`. You
│ should update your GUROBI_HOME environment variable to point to the
│ correct location.

**Comment by vchuravy** [comment]
Hello @alexjacq this issue tracker is for the Julia base languages. I recommend opening an issue on https://github.com/jump-dev/Gurobi.jl or asking for help on https://discourse.julialang.org
