### ISSUE TITLE
Win32 nightly has some problems downloading the General registry via git

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#38763]
Some example:

Failed to get registry on package CI: https://github.com/JuliaLang/Example.jl/runs/1516688269?check_suite_focus=true

Failed to get registry on BuildBot Julia CI: https://build.julialang.org/#/builders/77/builds/7053/steps/15/logs/stdio

```
ERROR: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:Zlib, error inflating zlib stream)
```

Looking at the recent commits, not sure what could have caused this.

**Comment by StefanKarpinski** [comment]
That is puzzling. It's not hitting the pkg server and it's a CA root error or a known hosts issue.

**Comment by KristofferC** [comment]
Maybe GitHub is being flaky... :man_shrugging:

**Comment by Keno** [comment]
Dup of #39617, which as more info.
