### ISSUE TITLE
Build error on macOS Big Sur

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#38799]
I cloned the `release-1.6` branch of the Julia repo and built it from scratch. This is macOS Big Sur 11.01. I have GCC 10 and GNU Make 4.3 installed via MacPorts. My build command was

```sh
make -j12 all docs
```

and this failed with

```
ERROR: Unable to load dependent library /Users/eschnett/src/julia-1.6/usr/lib/libjulia-internal-debug.1.6.dylib
Message:dlopen(/Users/eschnett/src/julia-1.6/usr/lib/libjulia-internal-debug.1.6.dylib, 10): image not found
make[1]: *** [sysimage.mk:87: /Users/eschnett/src/julia-1.6/usr/lib/julia/sys-debug-o.a] Error 1
make: *** [Makefile:88: julia-sysimg-debug] Error 2
```
Indeed this library was not present.

When I continued the build with `make -j12` and `make -j12 debug`, there were no further errors reported, and the missing library was created.

This looks like a makefile problem to me. It might be that some dependencies are not declared correctly for the `debug` build.

**Comment by chriscoey** [comment]
I had the same issue, with Julia master and Big Sur 11.1 (even after recloning the Julia repo)

**Comment by eschnett** [comment]
This also happens without the `-j12`, but seems to happen only when I use the `all` target.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
