### ISSUE TITLE
JupyterLab: Trying to install a new Pkg and received an error

### ISSUE THREAD

**Issue by TJLSmith0831** [JuliaLang/julia#38805]
I am starting a new project and want to use Julia, but I have run into some issues. I'm trying to import PyCall using Pkg.add(), but this error has appeared.

<img width="1107" alt="Screen Shot 2020-12-09 at 5 52 58 PM" src="https://user-images.githubusercontent.com/67556218/101698388-623a2980-3a47-11eb-8b09-3b422ad6b9a4.png">

I do not know how to resolve this issue. I'm using Julia 1.3.1 kernel. If needed, I'm willing to uninstall that and install 1.5. However, I'm unsure of how to do so.

**Comment by TJLSmith0831** [comment]
<img width="554" alt="Screen Shot 2020-12-09 at 5 59 29 PM" src="https://user-images.githubusercontent.com/67556218/101698891-497e4380-3a48-11eb-9bc5-ca4ae561404a.png">
When I try to install Julia 1.5 this error is what pops up

**Comment by KristofferC** [comment]
It seems you have some permission problems with the julia directory (commonly `~/.julia/`). The second error is a permission error when trying to create the `.julia/logs` folder to put the REPL logs into.

**Comment by TJLSmith0831** [comment]
Okay. Any advice how to fix those issues on a MacOS?

**Comment by StefanKarpinski** [comment]
Hard to say without more info. You first need to make sure you own all the files; if you don't you'll need to use `sudo chown` to fix that. Then you need to make sure that you can appropriately read and write all the files. This is a little trickier, but `chmod -R u=rwX ~/.julia` might work. Probably resulted from running something as root.
