### ISSUE TITLE
Devdocs for Slot mentions MethodInstance.slottypes which does not exist

### ISSUE THREAD

**Issue by ulysses4ever** [JuliaLang/julia#38840]
[The devdocs about the `Slot`](https://github.com/JuliaLang/julia/blob/2403796d5b89c90a00b12b01b91cfb62e4fd8554/doc/src/devdocs/ast.md) type mentions:

>  The types of these slots are found in the `slottypes` field of their `MethodInstance` object. 

But the [`MethodInstance` type](https://github.com/JuliaLang/julia/blob/2e3364e02f1dc3777926590c5484e7342bc0285d/src/jltypes.c#L2216) doesn't have the `slottypes` field (at least, not currently). Is it a bug in the docs?

**Comment by timholy** [comment]
Yes, it should be `CodeInfo`, not `MethodInstance`. Care to submit a fix?

**Comment by ulysses4ever** [comment]
@timholy thanks! with pleasure, see PR [38843](https://github.com/JuliaLang/julia/pull/38843).
