### ISSUE TITLE
`pointer` returns the incorrect pointer type

### ISSUE THREAD

**Issue by FedericoStra** [JuliaLang/julia#38848]
### What's wrong

Consider the following code:
```julia
struct S x::Int end
v = S.(1:5)
ptrs = [pointer(v, i) for i in eachindex(v)]
unsafe_load.(ptrs)
```
Everything works as expected, because `pointer(v, i)` returns a pointer `Ptr{S}` to the `i`-th elements of type `S` stored inline in the vector `v`.

Consider now this other code:
```julia
mutable struct M x::Int end
v = M.(1:5)
ptrs = [pointer(v, i) for i in eachindex(v)]
unsafe_load.(ptrs) # garbage
```
The behavior is complete nonsense, because `pointer(v, i)` returns a pointer `Ptr{M}`, but elements of type `M` are not stored inline in the vector, so the actual return type should be `Ptr{Ptr{M}}` and then two `unsafe_load`s will be required to get to the actual object of type `M`.

### How it should probably be

I believe `pointer` should behave as the following `truepointer`, which correctly returns a `Ptr{Ptr{M}}` in the last example, and then `unsafe_full_load` recursively loads iterated pointers:
```julia
truepointer(a::AbstractArray{T}, i::Integer) where T =
    Base.allocatedinline(T) ? Ptr{Ptr{T}}(pointer(a, i)) : pointer(a, i)

unsafe_full_load(p::Ptr{<:Ptr}) = unsafe_full_load(unsafe_load(p))
unsafe_full_load(p::Ptr) = unsafe_load(p)

v = M.(1:5)
ptrs = [truepointer(v, i) for i in eachindex(v)]
unsafe_load.(ptrs) # pointers to the `M` objects
unsafe_full_load.(ptrs) # the `M` objects
```

### How to solve it

The problem appears to be in [abstractarray.jl:1113](https://github.com/JuliaLang/julia/blob/master/base/abstractarray.jl#L1113), which unconditionally returns a `Ptr{T}`, instead of checking whether it should return a `Ptr{Ptr{T}}`.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/30276?

**Comment by stevengj** [comment]
Closing as dup.
