### ISSUE TITLE
Bump openblas to a newer version (0.3.13)

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#38865]
OpenBLAS 0.3.12 is already available in Yggdrasil, and 0.3.13 was just released yesterday.

It would be nice to get a more recent version in, and if it is stable, perhaps even backport it to 1.6. There's a lot of nice accumulated fixes from 0.3.10, which is what we currently ship:

https://github.com/xianyi/OpenBLAS/releases

**Comment by Keno** [comment]
OpenBLAS 0.3.12 has known issues causing exit to hang on Windows. I'm not sure we have the bandwidth to look into it before the 1.6 release.

**Comment by ViralBShah** [comment]
Yeah, not worth it then.

**Comment by omus** [comment]
Closed by: https://github.com/JuliaLang/julia/pull/39216
