### ISSUE TITLE
`parse(DateTime, x, dateformat"HH:MM:ss")` returns Year 1, not Year 0

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#38870]
While working around https://github.com/JuliaLang/julia/issues/38869
I ran into this, which I found unexpected.

Consider this code:
```
julia> parse(DateTime, "00:15:00", dateformat"HH:MM:SS")
0001-01-01T00:15:00
```

My expectation was that the Year field would default to 0, and (and the Month and Day to 1).
Such that i could find the `Period` that is represented by subtracting `DateTime(0)`
But that does not work (instead i need to subtract `DateTime(1)`)
```
julia> DateTime(0)
0000-01-01T00:00:00

julia> k = parse(DateTime, "0:15:00", dateformat"HH:MM:SS") - DateTime(0)
31623300000 milliseconds

julia> canonicalize(Dates.CompoundPeriod(k))
52 weeks, 2 days, 15 minutes
```

**Comment by jakobnissen** [comment]
Not sure what the correct behaviour here is, but do note that [year zero](https://en.wikipedia.org/wiki/Year_zero) does not exist historically. According to the `Dates` docs, an ISO 8601 year of `0000` represents the year 1 BC, which would also be confusing as a default value, in my opinion.
