### ISSUE TITLE
Documentation for broadcasted addition assignment not matching implementation

### ISSUE THREAD

**Issue by albheim** [JuliaLang/julia#38897]
The docstring for `.+=` says that it is a synonym for `x = x .+ y` but seems to rather be a synonym for `x .= x .+ y`. I'm not sure what I think the correct way should be (leaning towards the implementation being correct), but either implementation or documentation should be updated to match behavior and description.

Ran this on Julia 1.5.3

Example with array:
```julia
a = b = [1, 2]
c = [3, 4]
a .+= c # a and b both change
a .= a .+ c # a and b both change
a = a .+ c # only a change
```
Example with tuple:
```julia
(a, b) = (2, 3)
(a, b) = (a, b) .+ (1, 2) # Works as expected
(a, b) .+= (1, 2) # Error copyto!(::Tuple...)
(a, b) .= (a, b) .+ (1, 2) # Error copyto!(::Tuple...)
```

**Comment by mbauman** [comment]
Thanks; you're right the implementation is what we want. Doc fix in #38898.
