### ISSUE TITLE
Add a warning that HTML should not be used

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#38909]
Reference: https://github.com/JuliaLang/julia/pull/38892#issuecomment-746607119

We accidentally exported `HTML` and we should warn users to avoid them.

**Comment by mortenpi** [comment]
Should `Text` get the same treatment as well (ref #29841)?

**Comment by musm** [comment]
Certainly the whole utils.jl file should be deleted

**Comment by javedbaig** [comment]
What we have to do, to fix this issue?

**Comment by josemanuel22** [comment]
@musm  I have added the required documentation for both html and text. I hope I did well

**Comment by stevengj** [comment]
Wouldn't it have been better to say to use `Docs.Text`, i.e. to not assume it is exported?

Right now, there's not really any alternative (other than writing your own equivalent type) if you want to have a string that is displayed as `text/html` (for `Docs.HTML`) or `text/plain` (for `Docs.Text`).
