### ISSUE TITLE
lambda 3% slower in 1.6 pre-release vs 1.5.3

### ISSUE THREAD

**Issue by clarkevans** [JuliaLang/julia#38911]
For much of the code I'm working with Julia 1.6 seems a good 10-20% faster.  For a [HypertextLiteral.jl](https://github.com/clarkevans/HypertextLiteral.jl) [benchmark](https://github.com/clarkevans/HypertextLiteral.jl/blob/master/test/benchmark.jl), I've simulated the construction of a 65K HTML report. In this case, there is a repeatable 6-7% performance drop (~`685μs` to `735μs` on my last run). Upon asking on Slack, Valentin Churavy asked if I could try to find a minimal, repeatable test case. 

The following test case that simulates a critical section, there is an increased runtime of about 3% (`36.2μs` to `34.9μs` on my last run) from Julia 1.5.3 (788b2c77c1) to Julia 1.6.0-DEV.1722 (599d3299c9).  

```
using BenchmarkTools
BenchmarkTools.DEFAULT_PARAMETERS.seconds = 20

mutable struct SText{T}
    content::T
end

Base.print(io::IO, t::SText) = t.content(io)
    
stext(idx::Int) =
    return SText() do io::IO
             print(io, "<html><body><span>Womble #")
             print(io, idx)
             print(io, " reporting for duty!</span></body</html>")
          end

function srun()
    io = IOBuffer()
    for i in 1:100
       print(io, stext(i))
    end
end

println("stext ", @benchmark srun())
```

```
julia> versioninfo()
Julia Version 1.6.0-DEV.1722
Commit 599d3299c9 (2020-12-09 09:00 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, goldmont)
```

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, goldmont)
```

If `SText` looks familiar -- it's because it is a replica of `Docs.Text`. I've got a secondary question... why is `{T}` needed here, if I remove it and use `content::Function` the performance hit is substantial.  Moreover, when I delete only `mutable` in my broader test case... performance drops almost 2% (on same version of Julia).  With this test case, swapping out `{T}` gives a good 5% or more drop in performance.  It's hard to see the drop in performance when `mutable` is removed... but I'm pretty sure it's there, just tiny. I don't know what I'm actually doing here... am I making a brand new function for each request?  Is that bad?

Anyway.  I hope this is useful. Julia is awesome.  The slow-down is also quite acceptable.  It was just an outlier in otherwise amazing speedups and I thought 'yall might want to know about it.

**Comment by JeffBezanson** [comment]
> I remove it and use `content::Function` the performance hit is substantial

That's because the `t.content()` call inside `print` becomes a dynamic dispatch; we no longer specialize on it.

This does make a new function object for each request, but that does not have much overhead, since they can all share the same code (i.e. there is only a single "type" of function, with multiple instances).

**Comment by clarkevans** [comment]
@JeffBezanson Unfortunately, the behavior of this code snippet doesn't fully reflect the behavior of the broader application -- it just demonstrates a case where code is slower on Julia 1.6 development branch.  

> That's because the `t.content()` call inside `print` becomes a dynamic dispatch; we no longer specialize on it.

In the application, I just [committed](https://github.com/clarkevans/HypertextLiteral.jl/commit/1bb40e33239a9a8facf9028df3a52404709f28db) the change that implements `content::Function` and it doesn't slow things down.  In the broader code base, I was already doing something akin to `return SText{Function}() do ...  end` before this change, and when I dropped the `{Function}`, the runtime was 30% worse.

In the current HypertextLiteral code base, if you want to really slow it down by **40%**... all you have to do is remove the "_mutable_" on this class that holds the closure.

```
~/HypertextLiteral.jl$ julia test/benchmark.jl 
HypertextLiteral: Trial(674.216 μs)
HTL (Attributes): Trial(976.910 μs)
~/HypertextLiteral.jl$ git diff
~/HypertextLiteral.jl$ vim src/utils.jl 
~/HypertextLiteral.jl$ git diff
diff --git a/src/utils.jl b/src/utils.jl
index 4178676..14eb31a 100644
--- a/src/utils.jl
+++ b/src/utils.jl
@@ -1,7 +1,7 @@
 """
     Reprint(fn) -- apply the lambda function when printed
 """
-mutable struct Reprint
+struct Reprint
     content::Function
 end
 
~/HypertextLiteral.jl$ julia test/benchmark.jl 
HypertextLiteral: Trial(948.814 μs)
HTL (Attributes): Trial(1.245 ms)
```

I would never have thought that telling the compiler something is static and not mutable would cause such a large performance decrease.

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, goldmont)
```

**Comment by clarkevans** [comment]
@oscardssmith Observed on Slack that this particular example might be of interest to https://github.com/JuliaLang/julia/pull/37849

**Comment by clarkevans** [comment]
@JeffBezanson I posted a separate, perhaps simpler issue #38936 regarding mutable structs.  I think it's intimately related to this one.  So, it's OK if this one is closed.

**Comment by clarkevans** [comment]
I'm closing this ticket since I think #38936 is a more concrete example.  Thank you.
