### ISSUE TITLE
Invalid certificate error in downloads test

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38912]
E.g. https://build.julialang.org/#/builders/79/builds/7112/steps/5/logs/stdio

**Comment by KlausC** [comment]
Maybe related to this one: https://github.com/JuliaMatrices/MatrixDepot.jl/issues/71.
I mean the root cause, related to CA certificates.

**Comment by StefanKarpinski** [comment]
I think I saw this once before as well. The strange part is that it only happens sometimes. Maybe a sign of memory corruption rather than certificates being misconfigured?

**Comment by StefanKarpinski** [comment]
Seems unlikely to be the same issue: the MatrixDepot report is from an older version of Julia, using an external system `curl` whereas master now uses `libcurl` that ships with Julia. The buildbots should always be configured the same in terms of CA roots, so the mystery here is why it works most of the time and fails occasionally. The mystery in the MatrixDepot report is why calling the (apparently) same `curl` binary on the same system works in one context and not in another one.

**Comment by StefanKarpinski** [comment]
Have we seen this recently? If not it may be good to close unless we see it again.
