### ISSUE TITLE
explain @cfunction in Embedding Julia manual

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#38932]
For people wanting to call Julia from C/C++, I would generally recommend doing all of the type conversions on the Julia side, and then use `jl_unbox_voidpointer(jl_eval_string("@cfunction(....)"))` to compile and extract a C function pointer that you can then call normally.   This is vastly easier than constructing/unboxing Julia types from the C/C++ side.

It would be good to document this in the [Embedding Julia](https://docs.julialang.org/en/v1/manual/embedding/) manual, which currently doesn't mention `@cfunction` at all.

(For example, this [came up on stackoverflow](https://scicomp.stackexchange.com/questions/23194/i-am-searching-for-a-c-code-implementing-the-complex-polygamma-function/23733#23733) in a [question](https://stackoverflow.com/questions/65322339/how-to-use-julia-special-functions-inside-c) about calling the Julia `SpecialFunctions.polygamma` function from C++.)

**Comment by pemryan** [comment]
I also figured a way to call julia functions in C++ via jl_function_ptr:
https://discourse.julialang.org/t/calling-julia-functions-using-cfunction/9032

**Comment by danilo-bc** [comment]
Bumping this thread because it's still relevant, specially with some welcome changes in Julia 1.6 and 1.7

**Comment by mhnsn** [comment]
Bumping this thread also, because serious support and documentation for C/C++ integration with Julia would be game-changing for next-generation Edge AI applications.
