### ISSUE TITLE
aarch64 release binary for 1.5.3 uses the git hash, "julia-788b2c77c1/" for the folder

### ISSUE THREAD

**Issue by microe** [JuliaLang/julia#38946]
The aarch64 build at 
https://julialang-s3.julialang.org/bin/linux/aarch64/1.5/julia-1.5.3-linux-aarch64.tar.gz when untarred has a directory named "julia-788b2c77c1/" when things like AUR julia-bin expect it to have the version number ("julia-1.5.3/"). Could we please get a build for aarch64 that uses that directory name format?

**Comment by vtjnash** [comment]
@staticfloat Did we promote the wrong build on https://julialang.org/downloads/? From spot checking most others (including the rest of v1.5.x aarch64 series), we have the release version in the folder name.

**Comment by staticfloat** [comment]
For some reason, that build thinks it wasn't tagged.  That's weird.  I'll try rebuilding it.

**Comment by staticfloat** [comment]
Alright, there must have been a race condition with the tagging; I've uploaded a new build that has a better naming structure, and it also self-identifies as an official build.

@SaschaMann how do we re-generate `versions.json` again?

**Comment by microe** [comment]
Looks great! Thanks for the quick turnaround.

**Comment by SaschaMann** [comment]
> @SaschaMann how do we re-generate versions.json again?

Click the run workflow button in https://github.com/SaschaMann/Julia-versions.json/actions?query=workflow%3A%22Build+versions.json%22 (looking into moving it elsewhere now with the new GH environments) - I just started a new build, it should be updated in ~30 min when it finishes.
