### ISSUE TITLE
have problem using plot in Jupyter notebook on MacOs

### ISSUE THREAD

**Issue by PKUFlyingPig** [JuliaLang/julia#38944]
when I try to use the plot function, it complains that 
```
could not load library "libGR.so"
dlopen(libGR.so.dylib, 1): image not found
```
How can I fix this ?

**Comment by mgkuhn** [comment]
Can you please provide a reproducible problem report:

Start with which exact Julia version are you using, on what exact OS version.

Then temporarily move your existing ~/.julia folder out of the way (e.g., `mv ~/.julia ~/.julia.old`), so your package depot starts from a clean state. Then add the packages you need (e.g., Plots, GR, and IJulia) from scratch. Paste here from your terminal a complete list of all keyboard entry that you used to get to this point, along with any version numbers, warnings, and other output that we might be able to compare, such that we then can try to reproduce exactly, keystroke for keystroke, how you got there (assuming you can reproduce it when beginning from a fresh ~/.julia folder)?

Also, have you set/changed any environment variables that might affect where Julia looks for shared libraries?

**Comment by ViralBShah** [comment]
This is clearly a GR.jl issue. I would suggest following the steps prescribed by @mgkuhn above and filing the issue in the GR.jl repo.
