### ISSUE TITLE
REPL: ends_with_semicolon evaluation is not what one would expect

### ISSUE THREAD

**Issue by oskarddfa** [JuliaLang/julia#38964]
Evaluation of `";#"` or similar things like `a=2 # ;` are not evaluated correctly, i.e. in both cases the REPL does not return an answer as it thinks that the last important character was a semicolon. 
Also something like this is not parsed correctly:
```
a=2 ; #= ;# =# h=2
```
The `ends_with_semicolon` function does not parse the input correctly, as it looks only at characters that are after the semicolon and not before it.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/28743
