### ISSUE TITLE
Stuck when updating registry on Windows

### ISSUE THREAD

**Issue by adsick** [JuliaLang/julia#38989]
Version 1.7.0-DEV.132 (2020-12-21)

add Makie
    Updating registry at `C:\Users\vadim\.julia\registries\General`

*and it freezes for long minutes, can even take 20-30 minutes and no output, then I do Ctrl+C*

the weird thing is that after I interrupt it and then repeat the command it actually starts to downloading stuff from Git.

**Comment by fredrikekre** [comment]
Probably a combination of https://github.com/JuliaLang/Pkg.jl/issues/2014/windows beeing slow with unpacking/moving the files and broken PkgServer.
