### ISSUE TITLE
Feature Request: eval stacktraces

### ISSUE THREAD

**Issue by Volker-Weissmann** [JuliaLang/julia#38988]
Currently, this code
```julia
function inner()
    eval(:abc)
end
function outer()
    inner()
end
outer()
```
outputs

> ERROR: LoadError: UndefVarError: abc not defined
> Stacktrace:
>  [1] top-level scope
>  [2] eval at ./boot.jl:331 [inlined]
> in expression starting at /path/to/file.jl:7

Would it possible for this to output  something like

> ERROR: LoadError: UndefVarError: abc not defined
> Stacktrace:
>  [1] inner at /path/to/file.jl:2
>  [2] outer at /path/to/file.jl:5
> in expression starting at /path/to/file.jl:7

**Comment by vtjnash** [comment]
It works for me on master. Looks like you're using an older (release?) version?
```
julia> outer()
ERROR: UndefVarError: abc not defined
Stacktrace:
 [1] top-level scope
   @ :0
 [2] eval
   @ ./boot.jl:369 [inlined]
 [3] eval(x::Symbol)
   @ Base.MainInclude ./client.jl:446
 [4] inner
   @ ./REPL[1]:2 [inlined]
 [5] outer()
   @ Main ./REPL[2]:2
 [6] top-level scope
   @ REPL[3]:1
```

**Comment by Volker-Weissmann** [comment]
I just tried the newest julia version and it works if I run it from the REPL or if I run it using the "Julia: Execute Code Cell" command in vscode, but it does not work if I run it using `julia file.jl`. But that's fine I guess.
