### ISSUE TITLE
"hard kill repl test" error on CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38996]
e.g. in https://build.julialang.org/#/builders/52/builds/6903/steps/5/logs/stdio. @vtjnash and I had discussed this and thought it might have to do with the timing of switching the TTY to raw mode. I recall discussing this before, since in one of the line discipline modes the TTY happily drops input bytes, but unfortunately, I couldn't find this discussion, though I do believe it's on this issue tracker.

**Comment by Keno** [comment]
https://build.julialang.org/#builders/52/builds/6901

**Comment by Keno** [comment]
https://build.julialang.org/#/builders/52/builds/6902/steps/5/logs/stdio

**Comment by vtjnash** [comment]
Hopefully fixed by https://github.com/JuliaLang/julia/pull/39482, reopen if encountered again

**Comment by vtjnash** [comment]
Not quite fixed yet
