### ISSUE TITLE
`setprecision` deserves a new home

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#38995]
This follows some prior consideration [#2576](https://github.com/JuliaLang/julia/issues/25716).

`setprecison` is exported from `MPFR.jl`. That overly constrains best practice.

At one time, `BigFloat` was the only client of `setprecision`.  The early `setprecision` was a unary function used to set an internal "global register" holding the number of the significand bits comprising each new BigFloat.
 
`setprecision` became dispatchable over other Types.
```
help?> setprecision
            setprecision([T=BigFloat,] precision::Int)
  Set the precision (in bits) to be used for T arithmetic.
```
Other packages export extensible numeric types .. currently we
 _import `MPFR: setprecision` to export `AnotherType: setprecision`_.

Moving `setprecision` to `floatfuncs.jl` lets us this:
`Base.setprecision(::Type{AnotherType}, precision)`,

**Comment by stevengj** [comment]
You can already define new methods via `Base.setprecision(::Type{MyType}, precision) = ...`; there is no need to `import MPFR: setprecision` as far as I can tell?
```jl
julia> Base.setprecision(::Type{Int}, precision) = "foo"

julia> setprecision(Int, 3)
"foo"

julia> setprecision(BigFloat, 3)
3

julia> precision(BigFloat)
3
```

**Comment by JeffreySarnoff** [comment]
I did not know that.  Closing. Thanks!
