### ISSUE TITLE
Inconsistent results from @ccall and ccall

### ISSUE THREAD

**Issue by MarcoVela** [JuliaLang/julia#39039]
I found a case where the ```@ccall``` macro may be inconsistent with ```ccall```
In Windows, when using the macro to call a Windows functions it returns a different result than the ccall equivalent
```
julia> @ccall :user32.FindWindowA(C_NULL::Ptr{Nothing},)::Int32
65920

julia> ccall((:FindWindowA, :user32), Int32, (Ptr{Nothing},), C_NULL)
855386
```

versioninfo:
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by Keno** [comment]
The signature you're using is incorrect. The function is probably stdcall and also takes two pointer arguments. Without the correct signature, it's quite possible for these things to just return garbage.
