### ISSUE TITLE
Re-direct from Julia v1.0 to v1.5.3 in Atom

### ISSUE THREAD

**Issue by jjdegruijter** [JuliaLang/julia#39043]
Hi
I've been using Julia 1.0 via Atom, but into weird problems related to "Segmentation fault 11".
To get rid of that I downloaded Julia version 1.5.3. How can I change the Julia version in Atom? 
Thanks

**Comment by StefanKarpinski** [comment]
Please ask questions on https://discourse.julialang.org.
