### ISSUE TITLE
Profile test failure/segfault on CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#39040]
https://build.julialang.org/#/builders/34/builds/7611/steps/5/logs/stdio

We have an rr trace

**Comment by vtjnash** [comment]
Link to rr trace was lost (should copy that here next time). Closing as not reproducible anymore.

**Comment by fredrikekre** [comment]
> uploading rr-run_517-gitsha_843713b695-2021-02-09_03_40_29.tar.zst to https://julialang-dumps.s3.amazonaws.com/linux64/517/rr-run_517-gitsha_843713b695-2021-02-09_03_40_29.tar.zst

^ that one is from https://github.com/JuliaLang/julia/pull/39579 but I am not sure it is the same issue.

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/39553
