### ISSUE TITLE
Vector is to Array as XX is to SubArray

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/julia#39059]
`SubVector` doesn't currently exist in Julia, would the following definition make sense?

```julia
const SubVector{T} = SubArray{T, 1}
```

similar to https://github.com/JuliaLang/julia/blob/676ccf4eaa9b6e6c6a53f75abb4bf3e1a2457426/base/array.jl#L58 

This could maybe be added there: https://github.com/JuliaLang/julia/blob/056be22e9450b55666602481fc22b2dbdd224af0/base/subarray.jl#L40 

happy to open a PR for this if people think this is useful? (there's this old issue: https://github.com/JuliaLang/julia/pull/3224 but I'm not sure it's relevant)

**Comment by oscardssmith** [comment]
I don't think this is especially useful. It's hard to think of any code that should be dispatching on `SubVector`. As such, I think this would probably just be clutter. That said I totally could be missing something here.

**Comment by simeonschaub** [comment]
One thing to note here is that `SubArray{T, 1}` is not a concrete type, so the parallels with `Array` and `Vector` may be a bit misleading, if you want to use it for annotating types in a struct. It would still work for things like dispatch though, so I don't have a strong opinion either way.

**Comment by tlienart** [comment]
One (possibly poor) reason why I find it useful personally to define this is that I like to use typing in some function signatures as I think it sometimes helps understand what the function does (I know this is not necessarily a shared opinion). In that sense, I prefer to annotate `foo(sv::SubVector{Int})` than `foo(sv::SubArray{Int,1})`. 

Also there's the symmetry argument (Array/Vector, SubArray/SubVector) though @simeonschaub's argument makes sense.

Anyway, I'm happy with this issue being closed if no one else find this interesting :)

**Comment by KristofferC** [comment]
> `foo(sv::SubVector{Int})`

Why not use `AbstractVector`?

**Comment by tlienart** [comment]
Yes all these are working alternatives, this was merely out of expecting a SubVector to be there and not finding it.

I'll close this as it seems people don't see this as particularly useful, thanks for the comments!
