### ISSUE TITLE
Lazy artifacts pre and post Julia 1.6

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#39067]
Based on HISTORY.md, it is my understanding that in Julia 1.6 and later, package using lazy artifacts must list `LazyArtifacts.jl` in their `Project.toml`. But `LazyArtifacts.jl` is not available in Julia <= 1.5; so to my understanding, that means package using lazy artifacts right now cannot support both Julia < 1.6 and >= 1.6, which is a pity.

The solution seems simple, there must be a proper `LazyArtifacts.jl` package, which does nothing in Julia <= 1.5, and does not get installed in Julia >= 1.6. I think @giordano already made such a package (?) but it's not yet in the general registry.

**Comment by giordano** [comment]
Related: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/982

**Comment by fingolfin** [comment]
Now that I think about it: do we also need a dummy `Artifacts.jl` for older Julia versions? Or are we supposed / "allowed" to keep using `Pkg.Artifacts` in our packages?

**Comment by giordano** [comment]
It already exists and it's registered: https://github.com/JuliaPackaging/Artifacts.jl

**Comment by StefanKarpinski** [comment]
Anything else to be done here?
