### ISSUE TITLE
type stability of merge! ( dic1, dic2 )

### ISSUE THREAD

**Issue by algorithmx** [JuliaLang/julia#39085]
https://github.com/JuliaLang/julia/blob/8c014445a7e6ba515286e38fe4585510cc93d300/base/abstractdict.jl#L181

dear Julia developers,

I have encountered a catastrophic failure with my code and nailed down the cause to be this function.

My testing example is
`merge(Dict("nbnd"=>8), Dict("cd"=>12.0))`

which should, intuitively give 
`Dict("nbnd"=>8, "cd"=>12.0)`

but Julia gave me
````
julia> merge(Dict("nbnd"=>8), Dict("cd"=>12.0))
Dict{String,Float64} with 2 entries:
  "cd"   => 12.0
  "nbnd" => 8.0
````

Is it a bug in the code or a bug in my mind ?

**Comment by stillyslalom** [comment]
This behavior is described in the docstring for `merge`:
 
>  merge(d::AbstractDict, others::AbstractDict...)
> 
> Construct a merged collection from the given collections. *If necessary, the types of the resulting collection will*
>  *be promoted to accommodate the types of the merged collections*. If the same key is present in another collection,
>  the value for that key will be the value it has in the last collection listed.

You can check promotion behavior like so:
```
julia> promote(8, 12.0)
(8.0, 12.0)
```

**Comment by mgkuhn** [comment]
The given example exactly matches the documented behaviour of `merge(::AbstractDict, others::AbstractDict)`, so I see no Julia issue here.

**Comment by algorithmx** [comment]
> This behavior is described in the docstring for `merge`:
> 
> > merge(d::AbstractDict, others::AbstractDict...)
> > Construct a merged collection from the given collections. _If necessary, the types of the resulting collection will_
> > _be promoted to accommodate the types of the merged collections_. If the same key is present in another collection,
> > the value for that key will be the value it has in the last collection listed.
> 
> You can check promotion behavior like so:
> 
> ```
> julia> promote(8, 12.0)
> (8.0, 12.0)
> ```
> 
> If you want to allow the resultant dict to have both `Int` and `Float64` values, you can provide an explicit `Union` for the dict constructor:
> 
> ```
> julia> merge(Dict{String, Union{Int, Float64}}("nbnd" => 8), Dict("cd" => 12.0))
> Dict{String,Union{Float64, Int64}} with 2 entries:
>   "cd"   => 12.0
>   "nbnd" => 8
> ```

thank you @stillyslalom 
I think this is probably not an issue but rather a counter-intuitive example. If I am to write merge!(), I need to make a decision about the type promotion of values. Apparently promoting types gives more benefits than loosely union all value types. 

But is there a general principle for such behaviour of type promotion in Julia functions ? I want to prevent further errors. This error really cost me time and money (to use a supercomputer) ....

**Comment by stillyslalom** [comment]
The general principle is that Julia will aggressively promote a function's arguments to a type that can represent all the arguments, unless otherwise specified. The benefit is that concrete types (or small unions of a few concrete types) allow for efficient storage and generation of fast, deterministic machine code. 

As an example, let's compare summing the values of dicts with 10^6 entries whose values are of type `Any`, `Union{Float64, Int}`, and `Float64`, respectively.

```
julia> using BenchmarkTools

julia> d1 = Dict{String, Any}(string(gensym()) => rand((8, 12.0)) for i = 1:10^6)
Dict{String,Any} with 1000000 entries:
  "##175515" => 12.0
  "##367070" => 12.0
  "##357342" => 8
  ⋮          => ⋮

julia> d2 = Dict{String, Union{Float64, Int}}(string(gensym()) => rand((8, 12.0)) for i = 1:10^6)
Dict{String,Union{Float64, Int64}} with 1000000 entries:
  "##1569580" => 8
  "##1890151" => 12.0
  "##1284012" => 12.0
  ⋮          => ⋮

julia> d3 = Dict{String, Float64}(string(gensym()) => rand((8, 12.0)) for i = 1:10^6)
Dict{String,Float64} with 1000000 entries:
  "##2152647" => 12.0
  "##2037186" => 8.0
  "##2176913" => 12.0
  ⋮          => ⋮
```
```
julia> @btime sum(values($d1)); # Any
  69.419 ms (999999 allocations: 15.26 MiB)

julia> @btime sum(values($d2)); # Union{Float64, Int}
  9.980 ms (0 allocations: 0 bytes)

julia> @btime sum(values($d3)); # Float64
  6.517 ms (0 allocations: 0 bytes)
```

For this simple operation, concrete types reduce runtime by an order of magnitude. For more-complicated operations, the speedup can be several orders of magnitude.
