### ISSUE TITLE
Internal error: encountered unexpected error in runtime: TypeError...

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#39082]
Our packages [AbstractAlgebra](https://github.com/Nemocas/AbstractAlgebra.jl), [Hecke](https://github.com/thofma/Hecke.jl), etc. started failing on master. I could reduce the error to the following MWE:

```julia
julia> struct Q end

julia> Base.typed_hvcat(a::Q, b, c...) = hvcat(b, c...)

julia> Q()[1//1 0; 0 1//1]
Internal error: encountered unexpected error in runtime:
TypeError(func=:<:, context="", expected=Type, got=T<:(Base.Rational{T} where T<:Integer))
[...]
```
(full backtrace: https://gist.github.com/thofma/23a37bd230758994871b42686de507ca)

```julia
julia> versioninfo()
Julia Version 1.7.0-DEV.205
Commit 5ee2d601ed* (2021-01-01 10:48 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, ivybridge)
```

This is working fine on 1.5.1 and on the release1.6 branch, so this is a regression on the master branch.

**Comment by simeonschaub** [comment]
Reduced to:
```julia
julia> f(x::Vararg{T}) where {T <: Number} = x[1]
f (generic function with 1 method)

julia> code_typed(f, Tuple{Rational, Vararg{Rational}}; optimize=false)
ERROR: TypeError: in <:, expected Type, got a value of type TypeVar
[...]
```
Seems to have been caused by https://github.com/JuliaLang/julia/pull/38136. @Keno

**Comment by thofma** [comment]
Yes, my bisect finished and I can confirm that this is due to #38136.

**Comment by Sacha0** [comment]
(Crossreferencing the possibly related https://github.com/JuliaLang/julia/issues/38999.)

**Comment by vtjnash** [comment]
Hard to say precisely how we should handle this, but it happens when an invalid type tries to get handled as an argument type:
```
julia> code_typed(getproperty, (Tuple{Int32, Vararg{T}}, Int)) where T
ERROR: TypeError: in <:, expected Type, got a value of type TypeVar
```

**Comment by vtjnash** [comment]
MWE. There was a normalization missed in #38136 when constructing argtypes.
```
julia> f(x, y...) = y[x]

julia> code_typed(f, Tuple{T, Int, Vararg{T}} where T<:Integer)
ERROR: TypeError: in <:, expected Type, got a value of type TypeVar
```
