### ISSUE TITLE
Enhancement: new icon for macOS

### ISSUE THREAD

**Issue by s-valent** [JuliaLang/julia#39083]
In macOS Big Sur Apple switched to [different app icon style](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/), so it would be great if Julia would include a different icon.

I made this one as a proposition:
<img src="https://user-images.githubusercontent.com/46625993/103519899-5e9f9400-4e87-11eb-9898-7117369f44a1.png" width="128"/>
[Julia.png](https://user-images.githubusercontent.com/46625993/103519899-5e9f9400-4e87-11eb-9898-7117369f44a1.png)
[Julia.icns.zip](https://github.com/JuliaLang/julia/files/5763947/Julia.icns.zip)

Although I don't insist on choosing exactly this one.

**Comment by PallHaraldsson** [comment]
I have no authority here, but I want to say the icon looks fine to me. I couldn't open the icns file and note (I guess easily convertible to PNG):

"Don’t provide app icons in ICNS or JPEG format. [..] For best results, add deinterlaced PNG files to the app icon fields of your Xcode project’s asset catalog."

I was just scanning the new guidelines, and they seemed contradictory:

"In macOS 11, app icons share a common set of visual attributes, including the rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow.
[..]
Attribute | Value
[..]
Shape | Square with no rounded corners"

Also intriguing how huge they want the icons:
"provide it in the following sizes:
512x512 pt (512x512 px @1x, 1024x1024 px @2x)
[down to 16x16]"

**Comment by mgkuhn** [comment]
I also got the impression that ICNS is a deprecated icon file format. @cormullion

**Comment by s-valent** [comment]
@mgkuhn I uncluded icns file for convenience, the original 1024x1024 png is available by tapping on image.

**Comment by cormullion** [comment]
I've not upgraded to Big Sur yet, so haven't thought about anything like updating the ICNS file... The code to make them (https://github.com/JuliaLang/julia-logo-graphics#finder-application-icons-macos-only) is two years old now, so might well be due for an upgrade. XCode is a bit too complex for me... 😂

I'll watch the discussion about the new logo with interest...

**Comment by s-valent** [comment]
@cormullion I don't really think that app icon fully represents "brand identity", and it's probably not always identical to the actual logo. Although I tried to keep the general look, may be the first time it was too detailed and too distinct from other platforms.

On the other hand, just putting current logo on the general white shape seems a little bit boring, so maybe it would be nice to add at least some more details...
<img src="https://user-images.githubusercontent.com/46625993/103666406-a73d7700-4f85-11eb-8502-8af4a86ebdd4.png" width="128"/>

Also the average user will probably only see this icon once - when he is installing it (zero times if he's using brew cask), that brings us to the question that julia is not really an app, but a terminal program (so it's probably shouldn't try to be an app and start being a framework instead, but that's not really a point of this current issue).

**Comment by StefanKarpinski** [comment]
This simpler version is definitely preferable. Light and dark versions of that would be good.

**Comment by s-valent** [comment]
@StefanKarpinski as far as I know you cannot change icon depending on light/dark theme, so I'm not sure what to do with both of them...

light:
<img src="https://user-images.githubusercontent.com/46625993/103797544-a37b2480-5059-11eb-8019-75e46b54ab8a.png" width="128"/>
[light.icns.zip](https://github.com/JuliaLang/julia/files/5777083/light.icns.zip)

dark:
<img src="https://user-images.githubusercontent.com/46625993/103798395-b0e4de80-505a-11eb-9d8d-9c6fe03af6bf.png" width="128"/>
[dark.icns.zip](https://github.com/JuliaLang/julia/files/5777108/dark.icns.zip)

**Comment by cormullion** [comment]
Does Finder have a Dark Mode?

**Comment by s-valent** [comment]
@cormullion Not only Big Sur, it was introduced in Mojave.
It slightly changed on Big Sur though

<img width="841" alt="finder" src="https://user-images.githubusercontent.com/46625993/103806476-2b672b80-5066-11eb-840f-04695dda6d0f.png">

**Comment by cormullion** [comment]
Ah, yes - I had set all my Finder windows to white backgrounds :).  Are there any app icons that change depending on mode?

**Comment by s-valent** [comment]
@cormullion I don't know any apps like that.
