### ISSUE TITLE
Error about non-existent fields is not using the correct type

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#39102]
```
julia> struct A; end

julia> getfield(A, :b)
ERROR: type DataType has no field b
Stacktrace:
 [1] top-level scope at REPL[11]:1
```

I think this should be 

```
julia> struct A; end

julia> getfield(A, :b)
ERROR: type A has no field b # or even Main.A?
Stacktrace:
 [1] top-level scope at REPL[11]:1
```

I think this stems from `datatype.c:1004`. At least that's where I think the errors is thrown in 1.5.3, since grepping for `"type .+ has no field"` only leads this as a possible construction.

**Comment by simeonschaub** [comment]
Why is that wrong? `A` is represented as a `DataType` and if you call `getfield` on it, you are asking for a field of the `DataType` `A`, not of `Type{A}`.

**Comment by rfourquet** [comment]
Indeed `getfield` applies on values. Following your example: 
```
julia> struct A; b; end

julia> getfield(A, :b)
ERROR: type DataType has no field b
Stacktrace:
 [1] top-level scope
   @ REPL[108]:1

julia> getfield(A(1), :b)
1
```

**Comment by Seelengrab** [comment]
Ah, of course! Bad mixup on my part, sorry for the noise.
