### ISSUE TITLE
Enhancement Request: Show instruction size in code_native output. 

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#39108]
It was pointed out on [this zulip thread](https://julialang.zulipchat.com/#narrow/stream/137791-general/topic/stack.20allocated.20arrays/near/221686213) that the equivalent of `code_native` in Common Lisp tells you the size in bytes of the native code, i.e. difference between the initial address and final address. The asker gave this example output:
```
; Size: 62 bytes. Origin: #x52D9BFAA                          ; FOO!
; AA:       F30F105701       MOVSS XMM2, [RDI+1]
; AF:       0F28DA           MOVAPS XMM3, XMM2
; B2:       F30F58D9         ADDSS XMM3, XMM1
; B6:       F30F105705       MOVSS XMM2, [RDI+5]
; BB:       0F28E2           MOVAPS XMM4, XMM2
; BE:       F30F58E1         ADDSS XMM4, XMM1
; C2:       F30F105709       MOVSS XMM2, [RDI+9]
; C7:       F30F58CA         ADDSS XMM1, XMM2
; CB:       F30F115A01       MOVSS [RDX+1], XMM3
; D0:       0F28EB           MOVAPS XMM5, XMM3
; D3:       F30F116205       MOVSS [RDX+5], XMM4
; D8:       0F28EC           MOVAPS XMM5, XMM4
; DB:       F30F114A09       MOVSS [RDX+9], XMM1
; E0:       488BE5           MOV RSP, RBP
; E3:       F8               CLC
; E4:       5D               POP RBP
; E5:       C3               RET
```
Perhaps this would be useful information for our own `code_native` to provide?

**Comment by Keno** [comment]
I'm not really sure what the utility of this information is. Code size is only very loosely correlated with performance.

**Comment by bicycle1885** [comment]
@MasonProtter FYI, I'm now working on this feature at #40220. Feedback is welcomed.
