### ISSUE TITLE
Incorrect parsing of hard line break in markdown

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#39103]
Both the spec for [Github Flavoured Markdown](https://github.github.com/gfm/#hard-line-breaks) and [CommonMark](https://spec.commonmark.org/0.29/#hard-line-break) state:

> A line break (not in a code span or HTML tag) that is preceded by two or more spaces and does not occur at the end of a block is parsed as a hard line break (rendered in HTML as a <br /> tag):

But if you write such code in Julia, that new line is just replaced with a space; as if it were not preceded by two spaces in the source.

```julia
julia> md"foo
       bar".content
1-element Vector{Any}:
 Markdown.Paragraph(Any["foo   bar"])
 ```
 
 The correct output would be
 ```
 1-element Vector{Any}:
 Markdown.Paragraph(Any["foo\nbar"])
 ```
 
 This forces extra line breaks in #39093 as there is no way to have a linebreak without inserting a full blank line (i.e. making two `Markdown.Paragraphs`)

**Comment by mgkuhn** [comment]
Git diff (by highlighting them in red) and many programming style guidelines discourage trailing whitespace in source code. Many authors will use editor functions (such as `M-x delete-trailing-whitespace` in emacs) to remove trailing whitespace, as most of it is added accidentally and considered bad style. Supporting trailing whitespace as part of the Julia source-code syntax seems like a bad idea to me. It will get removed by accident very frequently.

**Comment by oxinabox** [comment]
This is true, I am not at all a fan of this part of the markdown; but i didn't write it.
We do need a way to insert hardline break.
We could allow `<br>` /`<br/>` to be used.
which is what i normally do when using markdown engines that suppprt HTML

**Comment by MichaelHatherly** [comment]
Related: https://github.com/JuliaLang/julia/issues/16004

**Comment by oxinabox** [comment]
>  Related: #16004

seems like this is an outright duplicate
