### ISSUE TITLE
Add a (second) newline character after tab completion in the REPL

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/julia#39105]
Usually when things are printed at the REPL, the printing ends with two newline characters. However, when you do tab completion at the REPL, only one newline character is printed:

```julia
julia> unsafe_
unsafe_copyto!           unsafe_load               unsafe_pointer_to_objref  unsafe_read               unsafe_store!             unsafe_string             unsafe_trunc              unsafe_wrap               unsafe_write
julia> unsafe_
```

So, it seems to me like that should print like this:

```julia
julia> unsafe_
unsafe_copyto!           unsafe_load               unsafe_pointer_to_objref  unsafe_read               unsafe_store!             unsafe_string             unsafe_trunc              unsafe_wrap               unsafe_write

julia> unsafe_
```

**Comment by vtjnash** [comment]
I would say this is intentional, and matches how other REPLs typically work. In particular, we have that `display` adds an extra newline, but that normally there is no extra line between the output and the prompt:
```
julia> show(unsafe_load)
unsafe_load
julia> display(unsafe_load)
unsafe_load (generic function with 2 methods)

julia> unsafe_load
unsafe_load (generic function with 2 methods)

julia>
```

**Comment by CameronBieganek** [comment]
@vtjnash I don't think this issue should be closed. I think this is pretty inconsistent with the way that things are normally displayed in the Julia REPL. Furthermore, here's a [section of the Julia manual](https://docs.julialang.org/en/v1/stdlib/REPL/#Tab-completion) that erroneously shows an extra newline after the tab completion suggestions:

![image](https://user-images.githubusercontent.com/8310743/117161507-93fdb500-ad87-11eb-969d-98f02e5300fa.png)
 
(Not to mention you actually have to hit TAB twice, not just once.) So I suspect that at some point in the past there actually was an empty line after the tab completions...

And if we're comparing to other REPLs, here's a couple examples:

### IPython

![image](https://user-images.githubusercontent.com/8310743/117162120-1f774600-ad88-11eb-9ebe-9408034f7134.png)

### Matlab

![image](https://user-images.githubusercontent.com/8310743/117162875-c65be200-ad88-11eb-83d6-75533d51cb9f.png)

In my opinion, having one empty line after outputs makes things a lot easier to read.

**Comment by Moelf** [comment]
I agree
