### ISSUE TITLE
Docs: include top-level module documentation in helpdb.jl

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#3911]
Top-level documentation exists for a number of modules in `Base`, including `Sort`, `Profile`, `Collections`, and `Test`, but that documentation does not appear in `helpdb.jl` (cf. #2242).  It would be nice to include it.  

(Hopefully this issue will be superseded by an upgraded documentation system.)

**Edit:** To clarify, the submodule *function* documentation is included, but no help is available for the modules themselves:

```julia
julia> help(Profile)
No help information found.

julia> help(Base.Profile)
No help information found.
```

**Comment by jakebolewski** [comment]
This doesn't seem relevant anymore.
