### ISSUE TITLE
rr intermittendly crashes with EBADF during execve

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#39145]
https://build.julialang.org/#/builders/34/builds/7873/steps/5/logs/stdio

```
[FATAL /workspace/srcdir/rr/src/AutoRemoteSyscalls.cc:592:check_syscall_result()] 
 (task 61975 (rec:61975) at time 843722)
 -> Assertion `false' failed to hold. Syscall munmap failed with errno EBADF
Tail of trace dump:
{
```

**Comment by Keno** [comment]
https://build.julialang.org/#/builders/34/builds/7811/steps/5/logs/stdio

**Comment by Keno** [comment]
It looks like one task is exec'ing, so it wants to do some clean up using one of the threads remaining in the old address space. The thread it selects is currently in a futex call that got interrupted just in time for the exec to pick it as the task to use for running the munmap operation. Something like the following produces a trace that look similar to what I observe in the failure case:
```
#include "util.h"

static void uv__signal_handler(int signum) {
  (void)signum;
  return;
}

static int register_signal_handler(int signum) {
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sigfillset(&sa.sa_mask)
  sa.sa_handler = uv__signal_handler;
  sa.sa_flags = SA_RESTART;
  test_assert(sigaction(signum, &sa, NULL) == 0);
  return 0;
}

uintptr_t futex_word = 0x0;

void *thread_func(void *arg) {
    (void)arg;
    int err = syscall(SYS_futex, &futex_word, FUTEX_WAIT_PRIVATE,
        0x0, NULL);
    test_assert(err == 0);
    return NULL;
}

int main(void) {
    register_signal_handler(SIGCHLD);
    pthread_t thread;
    int err = pthread_create(&thread, NULL, thread_func, NULL);
    test_assert(err == 0);

    for (int i = 0; i < 100; ++i) {
        if (vfork() == 0) {
            int err = execl("/bin/true", "/bin/true", (char*)NULL);
            test_assert(err == 0);
        }
    }
    atomic_puts("EXIT-SUCCESS");
}
```

Unfortunately, I haven't been able to observe this test case failing, so I'm definitely still missing something. I also don't understand where the `EBADF` could be coming from, so mysteries abound.

**Comment by Keno** [comment]
cc @rocallahan @khuey in case you guys have any idea how that EBADF may sneak in there. I'm a bit stumped

**Comment by khuey** [comment]
Getting EBADF out of a munmap is pretty odd.

Can you catch this with rr logging enabled?

**Comment by Keno** [comment]
https://github.com/JuliaCI/julia-buildbot/pull/182 to turn on `RR_LOG_BUFFER`, we'll see if that works. Hopefully it doesn't slow things down too much.

**Comment by Keno** [comment]
We have a trace with log this morning, which makes it clear what's going on: https://build.julialang.org/#builders/34/builds/7989. The task in question reached a seccomp event that hadn't been processed yet, but AutoRemoteSyscalls doesn't work if the tracee is at an entry or seccomp trap, so it ends up running the syscall twice, the second time around with the return value of the munmap as rax, which is zero, i.e. SYS_read. Will work on a patch.

**Comment by Keno** [comment]
There's still something I don't understand though. Why do we end up seeing a SECCOMP event on this task? I would have expected a SYSCALL event when the futex syscall exits. Unfortunately our log is not long enough to answer that question. I'll bump it to see if that leads to more insight.

**Comment by Keno** [comment]
Actually, maybe I do. Since we're about to restart the syscall, rr will try to use the ptrace entry trap rather than the seccomp trap for its entry processing. Then it expects to ignore the subsequent seccomp trap, but it is definitely possible that the kernel just won't get back to the kernel thread until after the execve, which would cause that execve to show up here.

**Comment by Keno** [comment]
Should be fixed with the rr bump just merged.
