### ISSUE TITLE
Multi-threading non-deterministic output

### ISSUE THREAD

**Issue by mileslucas** [JuliaLang/julia#39144]
I'm experiencing what I believe is a bug with `Threads.@threads` which causes non-deterministic output.

---
## Version info
```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

## Steps to Reproduce

```julia
pkg> add ADI#ml/framewise
julia> cube = randn(30, 101, 101) .+ 100;
julia> angles = sort!(10 .* rand(30) .+ 43);
julia> using ADI
julia> av = AnnulusView(cube, inner=10, outer=20);
julia> S1 = reconstruct(Framewise(PCA(5)), av; angles=angles, fwhm=5);
julia> S2 = reconstruct(Framewise(PCA(5)), av; angles=angles, fwhm=5);
julia> S1 ≈ S2
false
```

upon visual inspection, the difference between `S1` and `S2` is usually some slices will be different, ie
```julia
julia> findall(i -> S1[i, :, :] ≉ S2[i, :, :], axes(S1, 1))
4-element Array{Int64,1}:
  1
  9
 17
 24
```

## The code

The code in question is [here](https://github.com/JuliaHCI/ADI.jl/blob/2b1892c3af84775ba310ba79e200c11a9fd94f52/src/framewise.jl#L30-L49). If I remove the `Threads.@threads` from [this line](https://github.com/JuliaHCI/ADI.jl/blob/2b1892c3af84775ba310ba79e200c11a9fd94f52/src/framewise.jl#L37) the problem disappears. I know this is buried inside my module code, so I'm happy to clarify anything.

**Comment by johnnychen94** [comment]
Your code depends on the execution order of the for loop (e.g., `S[i:i, :]`), while almost all parallel implementation(simd, threads, distributed) will mutate the execution order in a non-deterministic way.

```julia
julia> Threads.@threads for i in 1:10
           println(i)
       end
10
3
8
9
6
4
5
1
2
7
```

**Comment by KristofferC** [comment]
Pretty much needs an MWE. Are you sure you don't have any race conditions?

**Comment by mileslucas** [comment]
I am not sure I don't have race conditions and I don't really know how to debug them. I can't seem to get a MWE besides what I've posted above. I've tried writing functions that are nearly the same and they don't have this issue. (in the package code there are 4 of these similar for-loops, but only the one using `AnnulusView` has this issue)

In this testing I've also noticed that if I add something like `@show i` inside the the loop, the problem disappears.

**Comment by simeonschaub** [comment]
In that code snippet, there's no lock around `n`, so this will not be thread safe. Feel free to ask further questions on https://discourse.julialang.org/

**Comment by mileslucas** [comment]
after removing the logging lines (including the `n` that did not have a lock) the problem persists, I don't understand what has to be locked or not, the `Threads.@threads` api doesn't mention having to manually do atomic operations on arrays

**Comment by mileslucas** [comment]
So I figured out the problem, I think. This must be a parsing problem in the `Threads.@threads` macro.

my function signature is
```julia
function reconstruct(alg::Framewise, cube::AnnulusView; ref=cube, angles, fwhm, r=_radius(cube), kwargs...)
```

and inside the for loop I have this-

```julia

@view Threads.@threads for i in axes(S, 1)
    # ...
    ref = data[inds, :]
    # ...
end
```

Within the loop, I added this test-
```julia
@view Threads.@threads for i in axes(S, 1)
    # ...
    ref = data[inds, :]
    rc = deepcopy(ref)
    @show rc == ref
    # ...
end
```

what was happening is `rc == ref` would _sometimes_ be `false`, which is nonsense.

If I change the loop to use 
```julia
@view Threads.@threads for i in axes(S, 1)
    # ...
    refer = data[inds, :]
    rc = deepcopy(refer)
    @show rc == refer
    # ...
end
```

there is no problem at all. This leads me to believe there is something confounding the `ref` keyword argument with the `ref` variable local to the loop.

**Comment by simeonschaub** [comment]
Ah, I see. I am pretty sure that's the expected behavior, since `ref` lives in the scope of the function `reconstruct`, so multiple threads are assigning to the same `ref` at the same time, which is why this causes a race conditions.
