### ISSUE TITLE
Julia ReadOnlyMemoryBug

### ISSUE THREAD

**Issue by dragon18456** [JuliaLang/julia#39157]
OS: Windows 10
Julia version: Version 1.5.3 (2020-11-09)

I was trying to run a tutorial notebook located here: https://computationalthinking.mit.edu/Fall20/hw8/
in a Pluto notebook. I just loaded it up and now, nothing will run. 

The error message that I get in the Pluto notebook is in the second block: 

```
Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to C:\Users\drago\.julia\compiled\v1.5\Plots\ld3vC_0zlvn.ji.

error(::String)@error.jl:33
compilecache(::Base.PkgId, ::String)@loading.jl:1305
_require(::Base.PkgId)@loading.jl:1030
require(::Base.PkgId)@loading.jl:928
require(::Module, ::Symbol)@loading.jl:923
top-level scope@Local: 10
```

I went to the terminal to see what went wrong, and I found a huge stacktrace that just vaguely asked me to submit a bug report, so I guess I will put it here?

https://pastebin.com/i19KAYvd

The main error is some unspecified ReadOnlyMemory error.

I put it in a pastebin because it is literally 1300 lines.

**Comment by ViralBShah** [comment]
cc @shashi 

Which notebook is this?

**Comment by dragon18456** [comment]
The notebook in the second link of this link: https://computationalthinking.mit.edu/Fall20/hw8/

It is also the first link on my first post.

**Comment by StefanKarpinski** [comment]
Does this still happen on Julia 1.6?

**Comment by ViralBShah** [comment]
Reopen if still a 1.6 issue. Also cc @fonsp since it is the computational thinking class.
