### ISSUE TITLE
sum for tuples uses +

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#39182]
sum for tuples uses `+` which has the following two consequences:

1. when a 1-element collection is passed `+` errors, while standard `sum` silently accepts the value:
```
julia> sum(["a"])
"a"
julia> sum(("a",))
ERROR: MethodError: no method matching +(::String)
```
2. no promotion happens (as standard `sum` uses `add_sum`):
```
julia> sum([0xe1, 0x1f])
0x0000000000000100
julia> sum((0xe1, 0x1f))
0x00
```

**Comment by NHDaly** [comment]
Just to confirm, indeed the docstring says this is supposed to be promoting to an Int:
```julia
 sum(itr)

  Returns the sum of all elements in a collection.

  The return type is Int for signed integers of less than system word size, and UInt for unsigned integers of less than system word size. For all other
  arguments, a common return type is found to which all arguments are promoted.
```

**Comment by NHDaly** [comment]
Here's the PR that left this behavior as a TODO:
https://github.com/JuliaLang/julia/pull/22825

It's not clear to me from reading that why this was left unimplemented, whether there are any particular pitfalls or gotchas, or if it was just not finished yet. Does anyone know whether this could just be changed?
