### ISSUE TITLE
Problems with generated functions

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/julia#39196]
There seem to be some breaking changes with the compilation of generated functions. Is this intentional?

In @thautwarm 's GeneralizedGenerated, 1.6 now requires calls to `@gg` to be below any functions used in the definition (this had been more flexible in 1.5)

In @MasonProtter and @shashi 's SymbolicUtils, `istree` now breaks, and the way it breaks makes me think issues with generated functions might be behind it:
https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/159

**Comment by vtjnash** [comment]
Incorrect use of generated functions is undefined behavior in all versions of Julia. Note the (non-exhaustive) long list of prohibited code https://docs.julialang.org/en/v1/manual/metaprogramming/#Generated-functions. Please give an MWE if you think there's an issue.

**Comment by simeonschaub** [comment]
Can be closed?
