### ISSUE TITLE
Stuck installing registries

### ISSUE THREAD

**Issue by queenbedding35** [JuliaLang/julia#39205]
I have been trying to download a software called ahorn for about 2 hours because of this screen that I am stuck on. 
![Screenshot (632)](https://user-images.githubusercontent.com/77312801/104266454-e15abd00-544c-11eb-8ea0-f175c4e10b3f.png)

**Comment by StefanKarpinski** [comment]
What were you doing when you got to this?

**Comment by mbauman** [comment]
Looks like it's coming from here:

https://github.com/CelestialCartographers/Ahorn/blob/16d36418488e4b9251bdb22cd3b7365521d59f88/ahorn.bat#L192

**Comment by queenbedding35** [comment]
> Looks like it's coming from here:
> 
> https://github.com/CelestialCartographers/Ahorn/blob/16d36418488e4b9251bdb22cd3b7365521d59f88/ahorn.bat#L192

do you know how I can fix the error in the coding?

**Comment by queenbedding35** [comment]
> What were you doing when you got to this?

It kept crashing when I was trying to download a software called ahorn, and this is the furthest I've gotten without it crashing, but it has been stuck like that for at least 2 hours when it's not supposed to. So I was told to report this problem to the Julia github because no one knew how to fix it properly in a discord server that I was in that specializes in this issue. Apparently one of them said that Julia was the one that was causing this bug.

**Comment by ViralBShah** [comment]
Please reopen if still an issue
