### ISSUE TITLE
using Downloads: download in a test

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaLang/julia#39200]
I'm checking my projects against 1.6.0-beta1.0 by running the test sets.  (Love the new (beta-)release!!!!:smiley:)  One project requires about 25 MB of as test data.   I used to use Base.download(...) to download the data into an Artifact so the data is only downloaded once.  With 1.6, I'd like to use Downloads.download(...) instead of Base.download(...).

This works great if I run the test using 

    > include("mytest.jl")

However when I run

    > ] test mypackage

which includes "mytest.jl", the code fails at "using Downloads: download" with the error message

    ERROR: LoadError: LoadError: ArgumentError: Package Downloads not found in current path:
    - Run `import Pkg; Pkg.add("Downloads")` to install the Downloads package.

If I don't include "using Downloads: download", the code fails while looking for Downloads.

Seems odd to me that the same code works when included but not within the test environment.  Is the Downloads package not available in the test environment?

**Comment by fredrikekre** [comment]
You need to include it as a dependency. Please ask questions on https://discourse.julialang.org/.
