### ISSUE TITLE
Unintuitive findmin and findmax

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#39203]
`argmin(collection)` will return the index of the smallest element in the collection, however, with the newly added:
```
argmin(f, collection)
```
it returns the value of the minimal element (with evaluation) instead:
```
julia> argmin([1,2,-3,5])
3

julia> argmin(identity, [1,2,-3,5])
-3
```

And this is not even useful since it's just taking the second element from the returned value of `findmin(f, collection)`:
https://github.com/JuliaLang/julia/blob/3d922e44ad868a9f39a10d47b55e3325e5422743/base/reduce.jl#L956

We should have argmin/argmax to return index instead.

**Comment by aplavin** [comment]
For the record, `argmin(f, collection)` and friends are added in #35316.

**Comment by JeffBezanson** [comment]
This was discussed quite a bit. What's implemented is the mathematical definition of argmin/argmax. It's slightly more general than returning an index, since not all collections have indices, e.g. sets or iterators.

**Comment by Moelf** [comment]
I think it's very unintuitive that in one case it returned the index of max/min, in another case, it returns the value of evaluation.

And currently, we don't have a way to get the index of max/min within an array giving a `by=` function.

**Comment by nalimilan** [comment]
The discussion happened at https://github.com/JuliaLang/julia/issues/27613. I agree it's confusing. For consistency with `findfirst`/`findall`/etc., ideally `findmin` and `findmax` would return a single index as discussed at https://github.com/JuliaLang/julia/issues/24865, replacing `argmax(x)`, and other functions would be used to get both the maximum and its index. But that would break a lot of code.

**Comment by aplavin** [comment]
As I understand, there are multiple subissues here, and not all of them are about consistency by itself.

1. First, obtaining index of min/max/first/etc value in array is more fundamental than obtaining the corresponding value: one can go from index to value by `arr[ix]`, but not the other way around. So findmin/findmax functions that return both are basically just optimizations when one needs them.
Currently (both before #35316 and after it) it is possible to obtain index of maximal element with `argmax(A)`, minimal with `argmin(A)`, and first matching item by `findfirst(A)`/`findfirst(f, A)`. However, it is **not** possible to get index of the element with maximal `f(a)`, as `argmax(f, A)` returns `a` and not its index.

2. Second, there is consistency. Finding max and min is related to both finding first matching element (`findfirst()`) and to sorting (`sort`, `partialsort`, etc).

2.1. As for comparison with `findfirst(A)`: it is similar to `argmax(A)` as both return the index. So, it's just the naming scheme that differs here. There is no analogy to `findfirst(f, A)`, and this is not just the lack of functionality as I wrote above, but inconsistency as well:
```julia
julia> findfirst([false, false, true])
3

julia> findfirst(identity, [false, false, true])
3  # same as above

julia> argmax([false, false, true])
3

julia> argmax(identity, [false, false, true])
true  # ...
```
2.2. Now let's compare finding maximum and sorting. They are both similar as both require that ordering is specified, and maximum is just a common and optimized special case for partial sort.
Both `sort`/`partialsort` and their cousins that return indices `sortperm`/... allow to specify ordering in two ways: either with key function `by=...`, or with comparator function `lt=...` (the latter is likely way way less commonly used).
For max/min everything is very different: there are actually three functions to find max in different ways - `maximum`, `argmax`, and `findmax`. And none of them let the user to specify the custom ordering in any way!

I don't have a perfect solution for these issues. But it seems reasonable to do some of the following (non-breaking!):
- Add `by=` argument to `maximum()`/`argmax`/`findmax`.
- Add function that returns index of `a` in `A` that gives the maximal `f(a)`. This could be called `argmax(f, A)`, but seems like there is a certain ambiguity with what it should mean. So, maybe `indmax(f, A)`? Reads very clear.
- Deprecate/remove `argmax(f, A)` that is to be introduced in julia 1.7. I personally would never guess apriori that it returns `a` from `A` and not its index. If talking about mathematical definition of argmax for functions, does it mean that optimization packages are encouraged to overload `Base.argmax` as e.g. `argmax(f)` for global maximum? And maybe `argmax` just isn't the best function for finding index in an array? `indmax` again...

**Comment by chelate** [comment]
+1 for just a by keyword, really would be nice for all min/max functions.

**Comment by lassepe** [comment]
Unpopular opinion: maybe the single-argument version of `argmin` should not exist in the first place? I think that it makes sense to have `argmin` behave as close as possible to the mathematical definition. If one wants to find the minimizing index one can always do `armin(i -> itr[i], eachindex(itr))`.

**Comment by haampie** [comment]
`argmax` needs to accept two things: (1) a set and (2) a partial order on that set. So I would expect an API similar to `sort!`,  which allows the user to specify the partial order with `lt`, `rev`, `by` and `order` kwargs. Another issue is that sort!'s api is terrible

**Comment by antoine-levitt** [comment]
The problem here is that reducers use `reduce(f,  arr)` for `reduce(fx for x in arr)` and this breaks that pattern. There are clearly two different things one could reasonably expect `argmin(f, x)` depending on one's priors and so it seems unwise to define it at all. The small added convenience isn't worth the large potential confusion.

**Comment by BioTurboNick** [comment]
I'll just add my voice here that it would probably be worthwhile to do something to prevent the surprise that these forms break the established pattern for when there are array first, and function first/array second forms of the same function.

Perhaps another solution is for the function domain forms to return different values.

For the array forms:
`argmin`/`argmax` returns the index into the array.
`findmin`/`findmax` returns the array value and the index into the array.

What if the function domain forms did this?
`argmin`/`argmax` returns the array value and the index into the array.
`findmin`/`findmax` returns the output value, the array value, and index into the array.

That way the output is a different type and mistakes would be more obvious. And easy enough to discard the other arguments.

**Comment by BioTurboNick** [comment]
Or, seen another way:
`argmin(A)`
is shorthand for
`argmin(x -> getindex(A, x), eachindex(A))`
and one could imagine a generalization of `argmin` to
`argmin(f, g, h, A) == argmin(x -> f(g(h(x))), A)`
such that the natural, expected extension is 
`argmin(f, x -> getindex(A, x), eachindex(A))`
or
`argmin(x -> f(getindex(A, x)), eachindex(A))`

By that logic, maybe the function/array forms **should** always return the index into the array.

**Comment by oscardssmith** [comment]
triage thinks 1 arg `argmax` is correct, but `findmin` with a function is broken and needs to be fixed before 1.7.

**Comment by vtjnash** [comment]
Who's "assigned" to work on this for the milestone? Do we need to rebase https://github.com/JuliaLang/julia/pull/7327 for this?

**Comment by aplavin** [comment]
This issue is marked "closed", but is fixed only partially: for `findmax` + `findmin`, not for `argmax` + `argmin`.
The triage comment by @oscardssmith does not address the `argmax(f, A)` issue at all.
It would be really unfortunate if Julia is stuck with this error-prone behaviour "forever":
```
val, ix = findmax(A)
ix = argmax(A)

val, ix = findmax(f, A)
ix = argmax(f, A)  # No! Can easily lead to errors that are hard to find.
```
Why introduce `argmax(f, A)` at all? Currently this is a simple function `argmax(A)` to find index of the maximum. There are lots of people surprised and confused by `argmax(f, A)` being defined but not equivalent to `argmax(f.(A))`: see this thread, https://discourse.julialang.org/t/findmax-and-friends-confusing-behaviour-to-be-introduced-in-1-7, and there were multiple questions on slack.

**Comment by aplavin** [comment]
Wow, even a cursory search on JuliaHub and GitHub revealed lots of packages that effectively define `argmax(f, A)` to correspond `argmax(f.(A))`! There are no packages (excluding `Compat.jl`) that define it to mean what is planned for 1.7.
I believe this a very strong argument *not* to introduce `argmax(f, A)` as currently planned!
For reference, putting the links below.

Most widely-used package: https://github.com/JuliaData/SentinelArrays.jl/blob/v1.3.3/src/chainedvector.jl#L771
Others:
https://github.com/tkluck/PolynomialRings.jl/blob/v0.7.3/src/MonomialOrderings.jl#L101
https://github.com/SebastianAment/CompressedSensing.jl/blob/e2de401f6e7be531603090cb55f9b7e06ba02468/src/util.jl#L179
https://github.com/lstagner/ConcaveHull.jl/blob/70840d3670df62e258a4994e874ac9c24d6e4fb6/src/concave_hull.jl#L39
https://github.com/wsshin/SALTBase.jl/blob/0add870b8df4105c63bfcc589ddc806a8b39d712/src/base.jl#L2
