### ISSUE TITLE
Compiling LibCURL dependency from source fails lib check

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#39229]
When compiling Julia (6c1824d997) and its dependencies from source (not BB) I sometimes run into an error when configuring LibCURL:
```
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lnghttp2 -lssh2 -lssh2 -lz
make[1]: *** [scratch/curl-7.73.0/build-configured] Error 1
make: *** [julia-deps] Error 2
```
Looking at the build log (deps/scratch/curl-7.73.0/config.log) I found this:
```
configure:31496: ./conftest
dyld: Library not loaded: libmbedx509.1.dylib
  Referenced from: /Users/omus/Development/Julia/x86/llvm-libunwind-src/usr/lib/libmbedtls.2.24.0.dylib
  Reason: image not found
/Users/omus/Development/Julia/x86/llvm-libunwind-src/deps/srccache/curl-7.73.0//configure: line 2396: 71927 Abort trap: 6           ./conftest$ac_exeext
configure:31496: $? = 134
configure: program exited with status 134
```
I run into this issue when I run:
```
make distcleanall
make -j8
```
After I encounter the failure I can continue to reproduce the problem with:
```
make -C deps configure-curl  # fails
```
And I can fix the problem by running:
```
make -C deps distclean-mbedtls
make -C deps install-mbedtls
make -C deps configure-curl  # works
```
I suspect that a dependency requirement is not being explicitly declared somewhere and the `make -j8` sometimes compiles the dependencies in a different order.

**Comment by omus** [comment]
Possibly https://github.com/JuliaLang/julia/pull/39234 may fix this issue. Maybe the missing distclean rule was causing not all dependencies to be cleaned which is why `distclean-mbedtls` would fix the issue?

**Comment by ViralBShah** [comment]
Closing, but please reopen if still an issue.
