### ISSUE TITLE
typeof(f::function) returns (typeof(f)

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/julia#39225]
MWE:
```
julia> f(x)=1
f (generic function with 1 method)

julia> f isa Function
true

julia> typeof(f)
typeof(f)

julia> typeof(ans)
DataType
```

So in essence, the `typeof` function does not return the type `Function` when given a function. This was discovered when trying to find a root with Roots.jl, and the `find_zero` function returned `ERROR: MethodError: no method matching find_zero(::typeof(f))`

I have defined a few different functions, all mathematical in nature, and I have used both the `f(x)=expr` and 
```
function f(x)
    expr
end
```
syntax, but the behaviour is very consistent. I have tried is both the REPL and in VSCode.

It seems to me like this behaviour should mess up any function that dispatches on a function, which should have been noticed very fast. Are anyone else able to reproduce this?

Output from `versioninfo()`:
```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER =
```

**Comment by timholy** [comment]
This is How It Should Be.

```julia
julia> typeof(sin)
typeof(sin)

julia> supertype(typeof(sin))
Function
```

Each function has to have its own type if you want them to be fast in higher-order functions.

**Comment by giordano** [comment]
It's unclear what the issue is, since `Function` is an abstract type and `typeof(f)` is correctly the the type of `f`: each function has its own type.

**Comment by simeonschaub** [comment]
@KronosTheLate I am curious to know whether the printing I proposed in #39176 would have cleared this up for you a bit, since this seems to come up quite often.

**Comment by KronosTheLate** [comment]
Oh. Cool, no problem then. My bad. Thanks for the quick responses.

I second @simeonschaub in that adding some explanatory printing would have been helpful to a newbie like me. The type `typeof(f)` does not seem like a proper type, but an un-evaluated function call, at first glance (to me).
