### ISSUE TITLE
Reporting rounding differences in Julia 1.5 and Julia 1.6

### ISSUE THREAD

**Issue by lbenet** [JuliaLang/julia#39230]
Testing `TaylorSeries.jl` (v0.10.10) in Julia v1.6.0-beta1 yields an (unexpected) error. This issue is intended to report the difference, which may be important for reproducibility; feel free to close the issue.

The following MWE illustrates the issue with `sinh`, which I think is related to some subtle differences in rounding:

```julia
# Julia 1.5.2
julia> sinh(0.2)
0.20133600254109402

# Julia 1.6.0-beta1
julia> sinh(0.2)
0.201336002541094
```

As far as I have checked (with `BigFloat`s and `ArbFloat`s), Julia v1.6.0-beta1 yields a more precise result.

cc @oscardssmith

**Comment by simeonschaub** [comment]
We generally don't guarantee 0.5 ulps of accuracy for elementary functions, so users should not rely on exact floating point results. As this particular case also seems to be a strict improvement, I don't think it makes sense to keep an issue open for this.

**Comment by dpsanders** [comment]
Ideally we should guarantee *faithful rounding*, i.e. that the returned result is one of the two neighbouring floats to the true result.

**Comment by oscardssmith** [comment]
I believe our current practice is .5 ULP for basic operations (ie `+-*/`) 1 ULP for basic special functions (`sin, exp, log` etc) and 1.5 ULP for more exotic functions (hyperbolic trig, `hypot` etc). The main reason for this is that getting accurate special functions requires significant computation at higher precision and would be noticeably slower.

**Comment by oscardssmith** [comment]
Those are the same. I just generally like phrasing in terms of ULP.
