### ISSUE TITLE
Path to Julia-1.6.0-beta1-linux-x86_64 loads Title for Version 1.0.4

### ISSUE THREAD

**Issue by BrettKnoss** [JuliaLang/julia#39244]
From my Ubuntu dast terminal.
```
@PC:~$ export PATH="$PATH:$HOME/Julia/julia-1.6.0-beta1-linux-x86_64/julia-1.6.0-beta1/bin"
@PC:~$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.4 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

```
It either loaded 1.0.4 from the link for 1.6, or I loaded 1.6, and the title card is wrong.

**Comment by Keno** [comment]
Presumably you have Julia 1.0.4 on the path somewhere?
`export PATH="$PATH:$HOME/Julia/julia-1.6.0-beta1-linux-x86_64/julia-1.6.0-beta1/bin"`, will first search your existing path.

**Comment by BrettKnoss** [comment]
I have a Julia folder under snaps, which is the version from the Ubuntu repository, but this path leads to two folders, 1.6 and 1.5.3.  If you think this is a support issue, let's talk here. [https://discourse.julialang.org/t/path-to-1-6-0-beta-x86-64-linux-opens-to-what-it-says-is-1-0-4/53316](url)     https://discourse.julialang.org/t/path-to-1-6-0-beta-x86-64-linux-opens-to-what-it-says-is-1-0-4/53316

**Comment by BrettKnoss** [comment]
Sorry this was not a bug.
