### ISSUE TITLE
Make eachline(::String) and countlines(::String) actually operate on Strings

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#39254]
I was a little dismayed today to find that it was not possible to iterate over each line of a String by doing `eachline(::String)`. Worse, the method is already taken, and essentially just does `eachline(open(::String))`. Same with `countlines(::String)`.

It's one thing that strings are implicitly treated as paths - that's discussed in other issues. But I think it's problematic that functions which so obviously should be able to work on strings now can't, because the methods have been implemented to work on paths instead. 

Changing this is obviously breaking, but it's worth thinking about for a hypothetical breaking Julia release in the future.

**Comment by JeffBezanson** [comment]
All you need to do is `eachline(IOBuffer(str))`, so I'm not sure it's worth changing.

**Comment by stevengj** [comment]
Might be worth mentioning the `IOBuffer` technique in the docstring.
