### ISSUE TITLE
Logical indexing: Better error when Bool array index is wrong size

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#39261]
Currently (1.5.3) if you try to access an array with a logical test of the wrong size, the error is:

```
[1;2;3][[true, false]]
ERROR: BoundsError: attempt to access 3-element Array{Int64,1} at index [Bool[1, 0]]
```

For small arrays, this may be clear enough. For larger arrays, much less clear.

Suggest something like:

```
ERROR: BoundsError: attempt to access 3-element Array{Int64,1} with mismatched Bool array of length 2.
```

I'm willing to do the PR if that seems okay.

**Comment by mbauman** [comment]
This has recently changed on master:

```
julia> [1;2;3][[true, false]]
ERROR: BoundsError: attempt to access 3-element Vector{Int64} at index [2-element Vector{Bool}]
```

This was #38689.
