### ISSUE TITLE
Open IOStream not reflecting changes on disk on Linux and macOS

### ISSUE THREAD

**Issue by tlnagy** [JuliaLang/julia#39266]
An open IOStream does not reflect external changes. It's only if the IOStream is closed and re-opened that the changes are reflected. 

```julia
julia> filepath = "test.txt";

julia> io = open(filepath, read=true, append=true);

julia> write(io, "test")
4

julia> flush(io)

julia> seekstart(io);

julia> read(io, String)
"test"
shell> cat test.txt
test
```

Now if I edit the file on disk:
```julia
shell> vim test.txt

shell> cat test.txt
test123
```
Reading from the IOStream still has the old data:
```
julia> seekstart(io); read(io, String)
"test"
```

I have reproduced this is on both a Fedora 33 machine and an Ubuntu 20.04.01 machine. 

```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

@sethaxen also reproduced it on macOS (https://discourse.julialang.org/t/changing-file-on-disk-not-affecting-iostream-data-is-this-a-bug/53359/6?u=tlnagy)

**Comment by DilumAluthge** [comment]
Can you reproduce this on Julia master?

**Comment by Keno** [comment]
IOStream is a buffered stream. You need to explicitly flush it to reflect written changes and there is no way to discard the read buffer.

**Comment by tlnagy** [comment]
I believe that @oheil on Discourse identified the reason for this behavior (https://discourse.julialang.org/t/changing-file-on-disk-not-affecting-iostream-data-is-this-a-bug/53359/8) and it seems like this is due to how (some) Linux distros handle file deletion where the pointer to a deleted file is persisted until all connections to it are closed. Therefore, the file isn't truly deleted until I close/re-open the IOStream in Julia. Therefore, my understanding is that this is the expected behavior on the Julia side.
