### ISSUE TITLE
splatting for type parameters

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#39298]
This works:

```julia
julia> Tuple{(Int64, String)...}
Tuple{Int64,String}
```

But this doesn't:

```julia
julia> foo(::Tuple{T1, TS...}) where {T1, TS}  = (T1, TS)
ERROR: MethodError: no method matching iterate(::TypeVar)
```

If it were to work, I'd expect `foo((0, "", 0))  == (Int64, (String, Int64))`.

I can't ever remember how to get the type parameters of `Tuple` as a `Tuple` itself. That is, how to go from `Tuple{A, B}` to `(A, B)`, without mucking with the internal fields of `DataType` (e.g. getting an `svec` from the `parameters` field). If the splatting operator ( `...`) worked in type parameters, then I would always remember.

**Comment by JeffBezanson** [comment]
`fieldtype` is the best way to get these type parameters.

**Comment by goretkin** [comment]
But what if all I have is e.g. `Tuple{Bool, String}` and I am trying to get `(Bool, String)`?

What is the best way to express something like the following?

`foo(::Type{Tuple{TS...}}) where {TS} = TS` 

e.g. `foo(Tuple{Bool, String}) == (Bool, String)`

Here is one false-start:
```julia
foo(::Type{<:Tuple{T, Vararg{Any}}}) where {T} = T
```

**Comment by martinholters** [comment]
```julia
julia> fieldtypes(Tuple{Bool, String})
(Bool, String)
```
?

**Comment by goretkin** [comment]
Oh, thanks. I understand now.

I think it would be fine to close this issue. I think I was a bit surprised that the splatting worked in the type parameter list in the first place, and it doesn't seem that useful to allow the destructuring.

**Comment by goretkin** [comment]
There's an edge case:

`fieldtypes(Tuple{Vararg{Any, N} where N})` doesn't give `(Vararg{Any, N} where N, )`

Is there a way to get a tuple of the types including in this instance?
