### ISSUE TITLE
Dispatch `ndigits` for AbstractFloat

### ISSUE THREAD

**Issue by jakewilliami** [JuliaLang/julia#39302]
### Idea

Would it make sense to do this?  I am happy to close the issue if anybody thinks this is a bad idea, but this is how I imagine the behaviour:

```julia
ndigits(0.1) == 2
ndigits(0.00000001) == 9
ndigits(1.01) == 3
ndigits(1234.01) == 6
ndigits(1.0) == 2
ndigits(1.000) == 4
```

---

### First draft at an implementation
```julia
Base.ndigits(m::AbstractFloat) = abs(last(Base.Ryu.reduce_shortest(m))) + ndigits(Int(last(modf(m))))
# or more simply by requires conversion
Base.ndigits(m::AbstractFloat) = length(string(m)) - 1 # we will be using the above in the next section, however, as I am not sure this is a good way to do this
```

### *Caveats*
_UNEXPECTED BEHAVIOUR; IDEA NEEDS WORK_

  - `ndigits(0.0)` produces the incorrect output:
     ```julia
     julia> ndigits(0.0) # expected output: 2
     326
     ```
    - Partial solution: 
       ```julia
       _ndigits_zero(m::AbstractFloat) = !iszero(m) ? error("Only use with m = 0") : ... # What if the number has more than one zero at the end??  See next
       _ndigits(m::AbstractFloat) = abs(last(Base.Ryu.reduce_shortest(m))) + ndigits(Int(last(modf(m))))
       Base.ndigits(m::AbstractFloat) = iszero(m) ? 1 : _ndigits(m)
       ```
  - `ndigits(1.0)` produces incorrect output (arbitrary number of trailing zeros):
    ```julia
    julia> ndigits(1.00) # expected 3
    1
    
    julia> ndigits(1.0000) # expected 5
    1
    ```
  - `ndigits(1.)`: What should this return???  Should this return 1 or 2?  How does Julia interpret this?

---
Once again, I am happy to close this if it isn't worth implementing.  I also have a funny feeling that this is actually a lot harder than it first might appear, due to the edge cases outlined above.

See also the discussion on a similar problem [here](https://discourse.julialang.org/t/find-number-of-digits-in-a-non-integer-number/37445/16).

EDIT: Similarly, I would love a `digits` method dispatched for `Float`s, but I have no suggestions how to do that...

**Comment by thofma** [comment]
I think what propose cannot work, since you basically want to return the number of digits in the input string, but this is unrelated to the value of the floating pointer number. For example, since `1.0 == 1.00`, there is no way to make `ndigits(1.0)` and `ndigits(1.00)` return different things. Also `1.00000000000000009 == 1.0`.

**Comment by jakewilliami** [comment]
@thofma Yes, good point and fair enough.  I think I will close this now.  Thank you for your time :-)
