### ISSUE TITLE
Allow for "nosep" in REPL

### ISSUE THREAD

**Issue by vegabook** [JuliaLang/julia#39326]
Some people such as myself prefer to maximise vertical screen information at the expense of legibility, and therefore prefer not to have blank lines between input/output pairs in the REPL. IPython recognises this with its `nosep` parameter. Can this be built for the Julia REPL?
![image](https://user-images.githubusercontent.com/3780883/105108624-8cedb800-5ab2-11eb-89e1-d633a908694c.png)

**Comment by simeonschaub** [comment]
A quick hack to do this would be to redefine:
```julia
julia> using REPL

julia> REPL.prepare_next(::REPL.LineEditREPL) = nothing

julia> sqrt(10)
3.1622776601683795
julia> [1, 2, 3] + [4, 5, 6]
3-element Array{Int64,1}:
 5
 7
 9
```
which you could just put into your `startup.jl`. It would probably be easy enough to add a proper option for this as well, but not sure it's really worth it.

**Comment by vegabook** [comment]
Think this satisfactorily sorts out my problem. Perfectly acceptable.
