### ISSUE TITLE
Contents of BitArray padding shouldn't influence ==(A, B)

### ISSUE THREAD

**Issue by stillyslalom** [JuliaLang/julia#39328]
Because `==(A::BitArray, B::BitArray)` [compares](https://github.com/JuliaLang/julia/blob/68133407404f3e1221385d495b47eb8585b258af/base/bitarray.jl#L1156-L1159) the UInt64 packed chunks comprising the argument arrays, modifying the contents of the padding in the last chunks causes `==` to return `false`, even though the arrays are element-wise equal:
```
julia> v1 = BitVector([true, false])
2-element BitVector:
 1
 0

julia> v2 = copy(v1);

julia> v1 == v2
true

julia> v2.chunks[1] += 16
0x0000000000000011

julia> v1 == v2
false

julia> all(v1 .== v2)
true
```

**Comment by stillyslalom** [comment]
I ran into it with LoopVectorization.jl, which vectorizes the overhanging bits to avoid bit-twiddling logic.

**Comment by simeonschaub** [comment]
Messing with internal fields of types is generally not something we make any guarantees about. I think in this case, a better solution would be for `LoopVectorization` to make sure that it always zeros trailing bits afterwards.

**Comment by chriselrod** [comment]
This goes for Julia Base and not Julia LoopVectorization: why pessimize every function writing into BitArrays for the sake of optimizing `==`?

**Comment by stillyslalom** [comment]
Regardless of guarantees, my linked PR adds a few clock cycles to mask out the trailing bits of the last chunk when checking equality. Is that worth doing, or no?

**Comment by simeonschaub** [comment]
> Is there other code that relies on the assumption of `0`s in the trailing bits? E.g. indexing code?

I am not sure. If we wanted to allow non-zero trailing bits as valid `BitArrays`, someone would have to go through the codebase, check that and add appropriate tests for this. Would also need to run PkgEval to check whether any packages rely on this. There definitely could be some performance advantages in some places, so I am not generally opposed to loosening this requirement.

> Regardless of guarantees, my linked PR adds a few clock cycles to mask out the trailing bits of the last chunk when checking equality. Is that worth doing, or no?

My point is that it doesn't make much sense to just fix this in one place, if we don't know what else this might effect. If we decide that we want to allow this, we would need to fix this everywhere else as well.

**Comment by mbauman** [comment]
Reductions are indeed gonna be where this will most likely occur.  E.g., `sum`/`count`/`any`/equality/etc.  A quick scan also shows we also depend upon this in the `find` family.  IIRC `BitSet`s depend on this property even more strongly.

We do guard against this in `all`... but I think that's the only one that's garbage-safe:

https://github.com/JuliaLang/julia/blob/814945c34f125e12f66c37605b67eb348d4b9cd2/base/bitarray.jl#L1672

**Comment by chriselrod** [comment]
Thanks for taking a look! Sounds like the assumption is used a lot -- and that it's not particularly likely we'd be able to actually win any performance by lifting that assumption.
