### ISSUE TITLE
Uninstalling julia v1.5.3

### ISSUE THREAD

**Issue by vlederer** [JuliaLang/julia#39323]

**Comment by vlederer** [comment]
$ rm -rf ~/julia leads to a non-empty dir:
$ ~/julia/usr/{bin|lib} with the following message:
rm: impossible de supprimer « julia/usr/bin/.nfs00000007c02baf15000002aa »: Périphérique ou ressource occupé
rm: impossible de supprimer « julia/usr/lib/julia/.nfs0000000140534db0000002a9 »: Périphérique ou ressource occupé

How to solve it?

**Comment by vlederer** [comment]
This error is due to my pc, those nfs... files refer to memory or tmp files, and because of my system latency, they couldn't benn remove, i guess.

**Comment by KristofferC** [comment]
Please ask questions on https://discourse.julialang.org. 

See https://www.ibm.com/support/pages/what-are-nfs-files-accumulate-and-why-cant-they-be-deleted-even-after-stopping-cognos-8.
