### ISSUE TITLE
Memory issue in pmap?

### ISSUE THREAD

**Issue by Philipp-Neubauer** [JuliaLang/julia#3934]
I've been running parallel MCMC sampling algorithms using pmap, but with my most recent snapshot (b6b4f02 Jul 31st) there seems to be a memory leak in pmap - the sampler works fine when called locally, or with pmap on just a local julia instance. As soon as I add a process with addprocs(1) and run the sampler with pmap, memory roof goes through the roof (more than my 8gb laptop can handle...).

**Comment by timholy** [comment]
May be fixed in master? See #10818

**Comment by jakebolewski** [comment]
I think we can close this issue.

**Comment by tkelman** [comment]
We have been getting a lot of randomly terminating Travis workers, may be related to the recent pmap changes?
