### ISSUE TITLE
Regression for iteration over Vector{Int} wrapper types

### ISSUE THREAD

**Issue by thchr** [JuliaLang/julia#39354]
Iteration over thin wrappers of certain `Vector{T}`s seems to have regressed on 1.6.0-beta1.0 vs. 1.5.1:

By way of example: defining a thin wrapper over a `Vector{T}`:
```jl
import Base: size, getindex, IndexStyle

struct V{T} <: AbstractVector{T} # wrapper type over a vector
    x::Vector{T}
end
size(v::V) = size(v.x)
Base.@propagate_inbounds getindex(v::V, i::Int) = v.x[i]
IndexStyle(::Type{<:V{T}}) where T = IndexStyle(Vector{T}) # ... IndexLinear()
```
and then doing a simple `sum` implementation for that:
```jl
function f(v)
    s = zero(eltype(v))
    for vᵢ in v
        s += vᵢ
    end
    return s
end
```

I see a performance regression on 1.6.0-beta1 vs. 1.5.1 when the wrapped vector is a `Vector{Int}` (but not when it is a `Vector{Float64}`):

**On 1.5.1:**
```jl
using BenchmarkTools
v_int   = V(rand(1:10, 100000)) # wrapped Vector{Int}
v_float = V(rand(100000))       # wrapped Vector{Float64}

@btime f($v_int)   # 40.499 μs
@btime f($v_float) # 117.999 μs
```

**On 1.6.0-beta1.0**
```jl
@btime f($v_int)   # 88.500 μs <-- 2x regression
@btime f($v_float) # 117.999 μs
```

There's a possibly related issue (albeit probably not related to the regression per se) where it is significantly faster to iterate over the wrapped vector itself when it is a `Vector{Int}`, as I noted in this [Discourse post](https://discourse.julialang.org/t/iteration-getindex-performance-of-abstractarray-wrapper-types/53729).

**Comment by Seelengrab** [comment]
Possibly related: Adding `@propagate_inbounds` to the default `iterate(A::AbstractArray, state=(eachindex(A),))` in abstractarray.jl and `@inbounds` to the loop recovers the performance without having to define forwarding definitions for `iterate` on `V` (as is done in the discourse thread). Though simply forwarding `iterate` to the wrapped array also achieves the same performance, even without `@inbounds`.

**Comment by mbauman** [comment]
Interestingly I cannot reproduce on a macOS i7-9750H.

1.5.0:
```
julia> @btime f($v_int)
  31.387 μs (0 allocations: 0 bytes)
550573

julia> @btime f($v_float)
  91.173 μs (0 allocations: 0 bytes)
50098.219763165755
```

1.6.0-beta1
```
julia> @btime f($v_int)
  30.341 μs (0 allocations: 0 bytes)
549753

julia> @btime f($v_float)
  91.176 μs (0 allocations: 0 bytes)
49961.80781681213
```

Does the following resolve the issue?

```
@eval Base @inline function iterate(A::AbstractArray, state=(eachindex(A),))
    y = iterate(state...)
    y === nothing && return nothing
    A[y[1]], (state[1], tail(y)...)
end
```

**Comment by thchr** [comment]
Trying on 1.5.1 including the `@eval Base ...` doesn't change anything; on 1.6.0-beta1.0, it does remove the noted performance regression. 

The performance gap between iterating over the wrapper and over the wrapped array remains though.

For context, my system info is:
```
julia> versioninfo()
Julia Version 1.6.0-beta1.0
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 1
```

**Comment by Seelengrab** [comment]
```
julia> versioninfo()
Julia Version 1.6.0-beta1.1
Commit 8240225853* (2021-01-11 19:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER =
  JULIA_NUM_THREADS = 4
```

**Comment by vtjnash** [comment]
I cannot reproduce this on my system
```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 64 × AMD EPYC 7513 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 1 on 64 virtual cores
Environment:
  JULIA_PKG_PRECOMPILE_AUTO = 0
```
