### ISSUE TITLE
Allow U+2AEB (⫫) as binary operator

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaLang/julia#39350]
I have a few questions, but as soon as they are done, I can do a PR:

1. Which operator preference would be best? I lean towards [`prec-comparison`](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm).
2. Which "tab completion" should it have? I like `\indep`.
3. How do I implement this completion?

**Comment by JeffBezanson** [comment]
This is category Sm so it seems like a good candidate. Also U+2AEA since they're a pair. How is this used? It's described as a "tack", so indeed that to me would indicate a relation, but I'm curious.

Character names go in REPL/src/latex_symbols.jl. Is there an existing latex name for this?

**Comment by jonas-schulze** [comment]
I use it in probability theory to denote the independence of events or random variables. There doesn't seem to be a commonly used latex name for it (see [here](https://math.stackexchange.com/q/702191) and [here](https://tex.stackexchange.com/q/79434/95100)). I've seen:

* `\indep`, `\independent`, or `\CI` from personal scripts, usually defined via `\perp\!\!\!\perp`
* `\upmodels` from [MnSymbol](https://www.ctan.org/pkg/mnsymbol)
* `\upvDash` and `\Vbar` from [fdsymbol](https://www.ctan.org/pkg/fdsymbol)

However, `\upmodels` from `fdsymbols` is a different glyph. It seems to be a rotated `\models`.

I would go for both `\upvDash` and `\indep` for `⫫` as well as `\downvDash` for `⫪` to be in line with the existing [`\vDash`](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl#L673) (longer double stroked line).

**Comment by mcabbott** [comment]
These would be nice to have. 

Re names, I like `⫫ \indep`, but `⫫ \upvDash` and `⫪ \downvDash` seem odd to me. `‖ \Vert` being double `\vert` is the pattern followed by `⊩ \Vdash`, and then `⊨ \vDash` has the dash not the vertical doubled. But once rotated they seem a bit confusing, the vertical isn't.

The single-line versions of these are `⊤ \top` and `⊥ \bot == \perp`. Googling around there seems to be some precedent for `⫪ \Top` and `⫫ \Perp \Bot` (these work with `txfonts` which is widely used) and perhaps also for `\barV` & `\Vbar` (not sure which packages).

**Comment by jonas-schulze** [comment]
I like `\Top` and `\Bot` as they complement one another. Though I'm not convinced of `\Perp` since `\perp` and `\bot` are different symbols in Julia:

```
julia> perp = '⟂'
'⟂': Unicode U+27C2 (category Sm: Symbol, math)

julia> bot = '⊥'
'⊥': Unicode U+22A5 (category Sm: Symbol, math)
```

I don't think `\upmodels` and `\downmodels` are a good fit for Julia either, since `\models` produces a glyph with a shorter double stroke compared to `\vDash`:

```
julia> models = '⊧'
'⊧': Unicode U+22A7 (category Sm: Symbol, math)

julia> vDash = '⊨'
'⊨': Unicode U+22A8 (category Sm: Symbol, math)
```

We could also add all of them for better discoverability:

* `⫪`: `\downvDash`, `\Top`
* `⫫`: `\upvDash`, `\Bot`, `\indep`

**Comment by mcabbott** [comment]
Interesting that `\perp \neq \bot` here, `:⟂ != :⊥` in Julia. In latex `\perp` is the operator while I think you need `\mathrel{\bot}` to get the same spacing. But here there is no such distinction. Should those be added to the list of unicode equivalences? They seem to be visually indistinguishable in all the fonts I tried. 

Agree that `\upmodels` etc aren't desirable. 

I can't see `\downvDash` being the first thing that pops into anyone's head, so would vote that those don't increase discoverability. (`\downvdash` appears to be an invention of the `MnSymbol` package, to give `\mathrel{\top}` a name?)

**Comment by jonas-schulze** [comment]
What list of Unicode equivalences?

**Comment by mcabbott** [comment]
Demonstration is:
```
julia> mumu = ['µ', 'μ']
2-element Vector{Char}:
 'µ': Unicode U+00B5 (category Ll: Letter, lowercase)  # micro?
 'μ': Unicode U+03BC (category Ll: Letter, lowercase)  # \mu<tab>, or μ on keyboard

julia> Symbol(mumu[1]) == Symbol(mumu[2])
false

julia> eval(Meta.parse(":$(mumu[1]) == :$(mumu[2])"))
true
```
Maybe the link is https://docs.julialang.org/en/v1/stdlib/Unicode/#Unicode.normalize . Somehow I thought Julia maintained a list of these, but that might be wrong.

**Comment by jonas-schulze** [comment]
Interesting, I didn't know about that. I've created a separate issue over there, as it is beyond the scope of this issue.

**Comment by jonas-schulze** [comment]
@JeffBezanson what do you think of `*vDash` as aliases? I am happy to be outvoted and update #39403, if that helps to get it merged faster. 🙂
