### ISSUE TITLE
`Array{Missing}` breaks matrix multiplication in some cases

### ISSUE THREAD

**Issue by henriquebecker91** [JuliaLang/julia#39362]
Based on [this discourse thread](https://discourse.julialang.org/t/inexacterror-when-multiplying-entirely-missing-matrices/53749).

In Julia 1.5.3:

```julia
julia> omega = randn(10,10)
10×10 Array{Float64,2}:
...
julia> a = Array{Missing}(missing, 10, 1)
10×1 Array{Missing,2}:
...
julia> result = a' * omega * a
ERROR: InexactError: trunc(Int64, Inf)
Stacktrace:
...
julia> result =  (omega * a)
10×1 Array{Missing,2}:
...
julia> result =  (a' * omega)
1×10 Array{Missing,2}:
...
julia> a = Array{Union{Missing, Float64}}(missing, 10, 1)
10×1 Array{Union{Missing, Float64},2}:
...
julia> result = a' * omega * a
1×1 Array{Union{Missing, Float64},2}:
 missing
```

Not sure of a bug or using `Array{Missing, 2}` is something to be avoided, but it seems inconsistent that it works on some cases and not in others. If `Array{Union{Missing, Float64}}` is used it always seem to work.

**Comment by simeonschaub** [comment]
No, this should definitely work. Just looks like our generic matmul currently assumes one of the element types is not of size zero, which fails if you multiply to arrays of `missing`: https://github.com/JuliaLang/julia/blob/770d0d5757c3192a82cd0f37579becd013a867af/stdlib/LinearAlgebra/src/matmul.jl#L826. Probably easy enough to fix though.
