### ISSUE TITLE
Odd Behavior: Neural network hybrid differential equation example

### ISSUE THREAD

**Issue by FishStat-DG** [JuliaLang/julia#39376]
Hi folks,

I'm getting into some ODE solving with Julia and am seeing some odd behavior in the scripted example found [here](https://diffeqflux.sciml.ai/dev/examples/hybrid_diffeq/) and [here](https://diffeqflux.sciml.ai/stable/examples/hybrid_diffeq/). On my laptop it performs as it should (i.e. predicted data shows increasing fit to the measured). However, on my desktop the performance is very strange. Both the measured and predicted values change, with the measured and most predicted values all declining to (or close to) zero, and one or two of the measured trends skewing heavily downward to somewhere between -300 and -800.

From what I can tell from some previous conversations with a developer, the issue appears to be stemming from updates to the DiffEqFlux and/or DiffEqSensitivity packages, as the current installations across the machines are as follows (both being run in Windows 10 using Julia 1.5.3 through Juno in Atom using the current releases of uber-juno (v0.3.0), julia-client (v0.12.6), language-julia (v0.20.2), and ink (v0.12.5)):

Desktop -

Julia v1.5.3
DiffEqFlux v1.31.0
DiffEqSensitivity v6.40.0 -

Laptop:

Julia v1.5.3
DiffEqFlux v1.24.0
DiffEqSensitivity v6.34.0

**Comment by oscardssmith** [comment]
Is this an issue with Base? Based on what you've said, this looks like the issue should either be with `DiffEqFlux` or `DiffEqSensitivity`.

**Comment by FishStat-DG** [comment]
I don't believe so, as I have the same version of Julia installed on both machines.
