### ISSUE TITLE
Could 3-arg Base.show on Types forward the MIME type through to parameters?

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#39377]
I wanted to implement 3-arg `Base.show` for `MIME"text/plain"` for a heavily parameterized datatype in our system, to provide nicer, indented display of the type.

For example, for a simple type like `struct MyType{A,B} end`, instead of printing it like this:
```julia
julia> T
MyType{Tuple{MyType{MyType{Tuple{Tuple{Int64},Int64,Float32},MyType{Int64,3}},10},MyType{MyType{Tuple{Int64,Int64},2},10},Int64},5}
```
I wanted to print it more like this:
```julia
julia> T
MyType{
    Tuple{MyType{
        MyType{
            Tuple{Tuple{Int64},Int64,Float32},
            MyType{
                Int64,
                3,
            },
        },
        10,
    },MyType{
        MyType{
            Tuple{Int64,Int64},
            2,
        },
        10,
    },Int64},
    5,
}
```

----------

This works fine if I override two-arg show, since each type will recursively call two-arg show on _its_ parameters. I produced the above via this definition:
```julia
julia> function Base.show(io::IO, ::Type{T}) where T<:MyType
           print(io, "MyType{\n")
           for p in T.parameters
               print(io, "    ")
               print(io, replace(repr(p), "\n"=>"\n    "))
               print(io, ",\n")
           end
           print(io, "}")
       end
```

However, since this indented version is quite verbose, I would like to only print like this when _displaying_ at the REPL. To achieve this, I want to be able to define 3-arg show for MIME"text/plain", but this doesn't work.

It stops at the `Tuple{}`, because the `Type{<:Tuple}` doesn't have a definition of 3-arg show:

```julia
julia> function Base.show(io::IO, ::MIME"text/plain", ::Type{T}) where T<:MyType
           print(io, "MyType{\n")
           for p in T.parameters
               print(io, "    ")
               print(io, replace(repr(p), "\n"=>"\n    "))
               print(io, ",\n")
           end
           print(io, "}")
       end

julia> T
MyType{
    Tuple{MyType{MyType{Tuple{Tuple{Int64},Int64,Float32},MyType{Int64,3}},10},MyType{MyType{Tuple{Int64,Int64},2},10},Int64},
    5,
}
```

----------------------------

Could we define a 3-arg show for types, which is identical to the current two-arg show, but recursively calls 3-arg show on each of its parameters, passing through the mime type, so that **if** you have a parameter that has a 3-arg show defined, it will be displayed with it at the REPL?

**Comment by vtjnash** [comment]
closing, since overloading show for Type is piracy

**Comment by NHDaly** [comment]
Hrmmm.... I see, yeah, i guess it technically is piracy, yeah.. 🤔 So is Type{MyType} not a special-case, since user code owns `MyType`, and therefore you don't need to worry about conflicting definitions in other packages? I'd previously been assuming that it was okay to treat ownership of `::Type{MyType}` the same as the ownership for `::MyType`?

**Comment by NHDaly** [comment]
Genuine question that only occurred to me later: is defining `typemax(::Type{MyCustomType})` considered piracy? I assume it isn't, right?

How do I as a user distinguish between those? Is the reason that typemax isn't piracy because there isn't a default implementation for it, so `typemax(MyCustomType)` would just be an error otherwise? Whereas for `show(::IO, ::MyType)`, there already is a default behavior? Thanks Jameson

**Comment by vtjnash** [comment]
In the `typemax` example, it would be refining the implementation (since otherwise it is an error) but keeping the behavior the same. That is generally when overloading is warranted.

**Comment by NHDaly** [comment]
gotcha. thanks, makes sense. Tricky! 👍
