### ISSUE TITLE
Incorrect warning in the documentation for @boundscheck

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#39370]
The [warning](https://docs.julialang.org/en/v1/base/base/#Base.@boundscheck) states that

> For indexing into your AbstractArray subclasses, for example, this involves checking the indices against its `size`. Therefore, `@boundscheck` annotations should only be added to a getindex or setindex! implementation after you are certain its behavior is correct.

I think this isn't right; the check involves checking indices against an array's `axes`, not their `size`.

**Comment by AtsushiSakai** [comment]
I think this issue can be closed by #41087
