### ISSUE TITLE
Proposal: extension of clamp for one side clamping

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#39384]
Hi!

`clamp` is a very useful function. However, a lot of time I find myself wanting to clamp only in one side. For example:

```julia
    crop_num_lines_at_beginning < 0 && (crop_num_lines_at_beginning = 0)
```

Hence, I would like to propose an extension to `clamp` so that we can have such one side clamping. My idea is to create two new functions `lclamp` and `rclamp` so that the value can be clamped in the left or right, respectively.

P.S.: If this is approved, then I can implement it.

**Comment by yurivish** [comment]
Do these correspond to the `min` and `max` functions?

**Comment by ronisbr** [comment]
Yes, I think this can be replicated with `max(crop_num_lines_at_beginning, 0)`.
