### ISSUE TITLE
Use if-else block instead of ifelse function.

### ISSUE THREAD

**Issue by A1-Mathematik** [JuliaLang/julia#39383]
https://github.com/JuliaLang/julia/blob/9028130434c5fb55e00c65e73aaf13cf0afde380/base/complex.jl#L179

Use if-else block instead of the ifelse function, because the ifelse function evals all three args. The `-(x)` could be expensive.

Use:
```
flipsign(x::Complex, y::Real) = if signbit(y) 
    -x 
else 
    x
end # and not ifelse(signbit(y), -x, x)
```

**Comment by simeonschaub** [comment]
This is intentional, since `-x` is cheap and `ifelse` avoids a branch, which is usually more expensive on modern CPUs.

**Comment by vtjnash** [comment]
The issue text is correct, as execution of if-else blocks should nearly always be more efficient (post optimizations). Any case where ifelse function is slower is probably a bug. Though it is uncertain if we need to fix this case, and doesn't need an open issue, PRs are not unwelcome.

**Comment by A1-Mathematik** [comment]
For an strange number type `-x` could be expensive. But that's true I didn't thought about branching. But how is ifelse implemented without branching? Is the ternery `con?true:false` operator as well branchless?

**Comment by StefanKarpinski** [comment]
`ifelse` is a function, so it evaluates all its arguments first. Then it picks one, which can be done with a machine instruction that doesn't branch, such as `cmoveq`.

**Comment by A1-Mathematik** [comment]
And an `if else` block gets compiled to this machine instruction if the compiler optimizes it well, but no guarantees there.
