### ISSUE TITLE
Wrong parsing of raw strings ending with \

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/julia#39415]
works well:
```
raw"c:\foo\a"
"c:\\foo\\a"
```
does not work:
```
julia> raw"c:\foo\"

ERROR: syntax: incomplete: invalid string syntax
Stacktrace:
 [1] top-level scope at REPL[27]:1
```
the ending `\`  conflicts with general-purpose "    \"    " (to insert " without ending the string constant definition).
Seen in all versions including 1.6-beta.

**Comment by Seelengrab** [comment]
This is intended behaviour. Ref. https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals:

> The exception is that quotation marks still must be escaped, e.g. raw"\"" is equivalent to "\"". To make it possible to express all strings, backslashes then also must be escaped, but only when appearing right before a quote character

**Comment by phlavenk** [comment]
Makes sense, closing.

**Comment by mgkuhn** [comment]
To escape a raw string, you (among other things) need to double the number of trailing backslashes, as is also documented e.g. in

>`help?> Base.escape_raw_string`
>`escape_raw_string(s::AbstractString)`
>
>Escape a string in the manner used for parsing raw string literals. For each double-quote (`"`) character in input string `s`, this function counts the number _n_ of preceeding backslash (`\`) characters, and then increases there the number of backslashes from _n_ to 2 _n_ + 1 (even for _n_ = 0). It also doubles a sequence of backslashes at the end of the string.
>
>This escaping convention is used in raw strings and other non-standard string literals. (It also happens to be the escaping convention expected by the Microsoft C/C++ compiler runtime when it parses a command-line string into the argv[] array.)

Is that description somewhat clearer than [the current one in the manual](https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals)?

If your concern is specifically Windows paths: Windows accepts [both `\` and `/`](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#path-normalization) as the directory separator character. If you want to hard-code a directory separator, [Microsoft recommends](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=net-5.0) to just use `/` in programs that run on multiple platforms, as that will also work on Unix. So you can just write: `"c:/foo/"`.

**Comment by phlavenk** [comment]
I think now I'm aware of the specific behavior, all the explanation are clear. I just didn't know I should be looking for this behavior in the manual.
I agree the best way of writing paths is to use `/` but usually when copy-pasting paths I have to replace the `\` manually. Just my laziness...
