### ISSUE TITLE
Lower keyword-body methods with tighter signature

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#39419]
Every method defined like `f(arg; kwargs...) = g(arg; kwargs...)` ends up having `kwargs` untyped in the body method, and so the conversion to `Symbol` is not inferrable. We've addressed this by adding a type-annotation to `merge(nt::NamedTuple, itr)`, but this is in a sense more fragile than it needs to be: it requires `itr` to have keys of specific types.

An alternative fix would be to change lowering. Specifically, in
```julia
julia> Meta.lower(Main, :(f(x; kwargs...) = g(x; kwargs...)))
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─       $(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─     return $(Expr(:method, :f))
)))
│         $(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─     return $(Expr(:method, Symbol("#f#5")))
)))
│         $(Expr(:method, :f))
│         $(Expr(:method, Symbol("#f#5")))
│   %5  = Core.typeof(var"#f#5")
│   %6  = Core.Typeof(f)
│   %7  = Core.svec(%5, Core.Any, %6, Core.Any)
│   %8  = Core.svec()
│   %9  = Core.svec(%7, %8, $(QuoteNode(:(#= REPL[1]:1 =#))))
│         $(Expr(:method, Symbol("#f#5"), :(%9), CodeInfo(
```
is there any reason to have `%7` not be `Core.svec(%5, Base.Iterators.Pairs{Symbol}, %6, Core.Any)`?

**Comment by JeffBezanson** [comment]
This makes sense. I think the main barrier is that `Base.Iterators.Pairs` is not always defined; I guess we could move the type definition to Core?

**Comment by timholy** [comment]
Since `AbstractDict` is defined in `"essentials.jl"` that seems pretty reasonable.
