### ISSUE TITLE
`:=` doc string seems wrong

### ISSUE THREAD

**Issue by YingboMa** [JuliaLang/julia#39427]
```
help?> :=
search:

  x := y is a synonym for x = x : y

julia> x = 2
2

julia> x := 10
ERROR: syntax: unsupported assignment operator ":="
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

**Comment by Liozou** [comment]
This comes from
https://github.com/JuliaLang/julia/blob/5cd1e3e1f2e6d79bdeeb2b1bfbdbe9081074bd23/stdlib/REPL/src/docview.jl#L220-L226
and I guess the condition `Base.operator_precedence(ex) == Base.prec_assignment` (https://github.com/JuliaLang/julia/pull/35277) should be updated to exclude this case. Any idea if there other similar cases to remove?

**Comment by Liozou** [comment]
Thanks for reminding me! It had completely skipped my mind. PR at #39975.
