### ISSUE TITLE
last n elements of an array

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaLang/julia#39423]
Define `last(arr::Array, n::Int)` to return the last `n` elements of `arr` like the implementation for `AbstractString`
```julia
last(arr::Array, n::Int) = @view arr[(end-n+1):end]
```

Only discussion to be had is whether to error if `length(arr)` < `n` or return as much as possible. I'm in favor of erroring, as it allows for write-time surety of the length of the returned array.

**Comment by mbauman** [comment]
This already exists in Julia 1.6 (but not as a view):

https://github.com/JuliaLang/julia/blob/527d6b69f6bca2598bea20e1cc4ccbdb77461517/base/abstractarray.jl#L457-L461
