### ISSUE TITLE
Regression in performance of sum on Broadcasted with small Union eltype

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#39425]
The performance of `sum(Base.Broadcast.Broadcasted(*, (x, z)))` when `z` has eltype `Union{Float64, Missing}` regressed dramatically between Julia 1.3 and 1.4. It improved again in 1.5 but it's still much slower on master than on 1.3.

On Julia 1.3.1:
```julia
julia> using BenchmarkTools

julia> using LinearAlgebra

julia> x = rand(10_000);

julia> z = Vector{Union{Float64, Missing}}(x);

julia> f(A, w) = sum(Base.Broadcast.Broadcasted(*, (A, w)))
f (generic function with 1 method)

julia> @btime f(x, z);
  31.150 μs (11 allocations: 240 bytes)
```

On 1.4.2:
```julia
julia> @btime f(x, z);
  2.070 ms (40004 allocations: 1.07 MiB)
```

On master:
```julia
julia> @btime f(x, z);
  941.751 μs (40002 allocations: 1.07 MiB)
```

Cc: @tkf. Found while investigating https://github.com/JuliaStats/StatsBase.jl/issues/518#issuecomment-551007729.

**Comment by nalimilan** [comment]
Though after calling `instantiate` everything is very fast on master:
```julia
julia> g(A, w) = sum(Base.Broadcast.instantiate(Base.Broadcast.Broadcasted(*, (A, w))));

julia> @btime g(x, z);
  23.826 μs (1 allocation: 16 bytes)
```

**Comment by vtjnash** [comment]
From that observation, I suspect this is also due to an excess usage of `@inline` in broadcast.jl. We've observed that those may hurt performance more often than they help, so as a rough cut, we may just want to remove all of them to solve all these performance regressions, then slowly bring them back more carefully, if necessary.

**Comment by inkydragon** [comment]
test code
```jl
x = rand(10_000);
z = Vector{Union{Float64, Missing}}(x);
f(A, w) = sum(Base.Broadcast.Broadcasted(*, (A, w)))
@time f(x, z);
@time f(x, z);
@time f(x, z);
```

- ✔️ 1.3.1 (2019-12-30): (15 allocations: 400 bytes)
- ✔️ 1.4.0-DEV.559 (2019-12-04) 7642e2ba91: (11 allocations: 240 bytes)
- ❌ 1.4.0-DEV.560 (2019-12-04) 3c182bc5c2: (40.00 k allocations: 1.068 MiB)
    #33526 cc: @tkf 
- ❌ 1.4.0-rc1 (2020-01-23): (40.00 k allocations: 1.068 MiB)
- ❌ 1.4.2 (2020-05-23): (40.00 k allocations: 1.068 MiB)
- ❌ 1.6.4 (2021-11-19)

**Comment by vtjnash** [comment]
This still reproduces on master

**Comment by Tortar** [comment]
This doesn't reproduce anymore on 1.11 and nightly
