### ISSUE TITLE
Segfault in jl_f_tuple->typekeyvalue_hash

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#39438]
Segmentation fault as encountered on Julia 1.6 (the RC1 backports branch):

```
signal (11): Segmentation fault
in expression starting at REPL[1]:1
typekeyvalue_hash at /home/tim/Julia/src/julia/src/jltypes.c:1014
lookup_typevalue at /home/tim/Julia/src/julia/src/jltypes.c:600
jl_inst_arg_tuple_type at /home/tim/Julia/src/julia/src/jltypes.c:1403
jl_f_tuple at /home/tim/Julia/src/julia/src/builtins.c:752
check_ir! at /home/tim/Julia/pkg/GPUCompiler/src/validation.jl:207
check_ir! at /home/tim/Julia/pkg/GPUCompiler/src/validation.jl:140
check_ir! at /home/tim/Julia/pkg/GPUCompiler/src/validation.jl:131
check_ir at /home/tim/Julia/pkg/GPUCompiler/src/validation.jl:120
unknown function (ip: 0x7f1b881c40f5)
```

rr recordings with a regular Julia: https://s3.amazonaws.com/julialang-dumps/reports/2021-01-28T14-18-39-maleadt.tar.zst
And with a debug build: https://s3.amazonaws.com/julialang-dumps/reports/2021-01-28T14-23-17-maleadt.tar.zst

Originates from several CUDA packages, and CUDA isn't rr-compatible, so I had to hack a little to get a recording (so it's not easy to reproduce).

**Comment by vtjnash** [comment]
Is this still an issue? (the links above are gone, but I still have local copies of them)

**Comment by maleadt** [comment]
Probably not? I haven't seen this in a while.
