### ISSUE TITLE
Julia and BLAS integer sizes differ on ARM

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#39436]
```julia
julia> versioninfo()
Julia Version 1.7.0-DEV.398
Commit 5cd1e3e1f2* (2021-01-27 22:13 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tsv110)


julia> using LinearAlgebra

julia> Int
Int64

julia> LinearAlgebra.BlasInt
Int32
```

This leads to bugs when calling BLAS functions
```julia
julia> v = rand(typemax(Int32) + 2);

julia> norm(v);
ERROR: InexactError: trunc(Int32, 2147483649)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, #unused#::Type{Int32}, val::Int64)
    @ Core ./boot.jl:605
  [2] checked_trunc_sint
    @ ./boot.jl:627 [inlined]
  [3] toInt32
    @ ./boot.jl:664 [inlined]
  [4] Int32
    @ ./boot.jl:754 [inlined]
  [5] convert
    @ ./number.jl:7 [inlined]
  [6] RefValue
    @ ./refvalue.jl:8 [inlined]
  [7] convert
    @ ./refpointer.jl:104 [inlined]
  [8] cconvert
    @ ./essentials.jl:398 [inlined]
  [9] nrm2
    @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/blas.jl:487 [inlined]
 [10] nrm2
    @ /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/blas.jl:493 [inlined]
 [11] norm2(x::Vector{Float64})
    @ LinearAlgebra /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:105
 [12] norm(itr::Vector{Float64}, p::Int64)
    @ LinearAlgebra /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:627
 [13] norm(itr::Vector{Float64})
    @ LinearAlgebra /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:625
```

**Comment by staticfloat** [comment]
This is because we do not use an ILP64 build of OpenBLAS on `aarch64`.  I don't remember why, but this is purposeful:  https://github.com/JuliaPackaging/Yggdrasil/commit/ee0693f151c8f0d6ab91ce5b1c0784547278a1ac

@ViralBShah @keno can either of you think of a reason why this is?  Should we switch `aarch64` BLAS to be ILP64 in the future?

**Comment by ViralBShah** [comment]
I don't remember why - but it is purposeful. Could be as simple as perhaps openblas not supporting it back then. In fact, a lot of Yggdrasil packages have conditionals for this as well. Good to revisit it and clean it up.

**Comment by matbesancon** [comment]
Should we try again to open a PR on Yggdrasil to build it? I can open it, but I doubt I'll of much use beyond "change random characters until CI says green"

**Comment by staticfloat** [comment]
>  I doubt I'll of much use beyond "change random characters until CI says green"

**Comment by staticfloat** [comment]
If Yggdrasil builds well, the next step is to try out a Julia build with that new configuration; you'll need to:

* Change which BB tarball gets downloaded by changing [this `version` field](https://github.com/JuliaLang/julia/blob/master/stdlib/OpenBLAS_jll/Project.toml#L3)

* add `USE_BLAS64:=1` in [this block](https://github.com/JuliaLang/julia/blob/master/Make.inc#L928-L933)

That should be enough for you to locally test and see if it works.  To actually merge this into Julia, we'd also need to:

* Update [the source tarball version](https://github.com/JuliaLang/julia/blob/master/deps/Versions.make#L74) we install if not using BB-built binaries.

* Synchronize the Yggdrasil source build flags with what we use in Julia itself, in particular, [the set of patches applied](https://github.com/JuliaLang/julia/blob/master/deps/blas.mk#L96-L104).

* Update checksums by running `make -f contrib/refresh_checksums.mk openblas`.

**Comment by matbesancon** [comment]
> add USE_BLAS64:=1 in this block

Why will this be necessary? If we are already on a 64-bits machine won't BLAS use 64 by default?

**Comment by staticfloat** [comment]
The way the build system works, you need to set `USE_BLAS64=1` explicitly on all platforms you want it to be the case on.

https://github.com/JuliaLang/julia/blob/master/deps/blas.mk#L43

**Comment by ViralBShah** [comment]
FWIW, whenever I am ready to land a blastrampoline PR, we will be able to remove all that complex BLAS stuff in `Make.inc`. I'll be opening it soon-ish, but it will take a long time to merge. 

Irrespective, if we can have 64-bit blas on aarch64, the work discussed here still needs to get done.

**Comment by ViralBShah** [comment]
Fixed in #39455.

**Comment by ViralBShah** [comment]
I suppose this should be left open until the functionality is actually merged.

**Comment by dkarrasch** [comment]
#39455 got merged. Can we close this?

**Comment by matbesancon** [comment]
Yes definitely
