### ISSUE TITLE
Look for and suggest close package names 

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#39468]
```jl
julia> using PLuto
ERROR: ArgumentError: Package PLuto not found in current path:
- Run `import Pkg; Pkg.add("PLuto")` to install the PLuto package.
```
It would be more helpful to suggest that I meant the `Pluto` package and offer to load that instead.
The given error message is actively unhelpful, since following that suggested course of action will not help and will leave the user more confused.

**Comment by strickek** [comment]
require (using, import): give a hint in error message if typo in modul name #38724

**Comment by dpsanders** [comment]
Dup of https://github.com/JuliaLang/julia/issues/38604
