### ISSUE TITLE
SparseMatrixCSC times BitVector falls back to dense multiplication

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#39474]
I apologize if this is already known (couldn't find it) but on 1.6

```julia
using SparseArrays, BenchmarkTools
N=10000
x=rand(Bool, N) .!= 0
M=sprand(N,N,10/N)
@btime $M*$x
@btime $M*Vector($x)
```

gives

```
  1.365 s (2 allocations: 78.20 KiB)
  296.739 μs (3 allocations: 88.14 KiB)
```

Maybe it may be sensible to use the second version by default? (or of course, better an ad-hoc implementation)

**Comment by abraunst** [comment]
Looking a bit more about this, it seems to me that the correct way would be to extend 
```SparseArrays.mul!``` to accept `BitArray`s as input array and to define `Base.:*(A::SparseArrays.SparseMatrixCSCUnion{TA}, x::BitArray{K})` 
with those changes in `SparseArrays/src/linalg.jl` I get no exta allocations and the same performance of the second case. Would there be interest in a PR?

```julia
julia> using SparseArrays, BenchmarkTools
julia> function SparseArrays.mul!(C::StridedVecOrMat, A::SparseArrays.AbstractSparseMatrixCSC, B::Union{BitArray,StridedVector,SparseArrays.AdjOrTransStridedOrTriangularMatrix}, α::Number, β::Number)
           size(A, 2) == size(B, 1) || throw(DimensionMismatch()) 
           size(A, 1) == size(C, 1) || throw(DimensionMismatch())
           size(B, 2) == size(C, 2) || throw(DimensionMismatch())
           nzv = nonzeros(A)
           rv = rowvals(A)
           if β != 1
               β != 0 ? rmul!(C, β) : fill!(C, zero(eltype(C)))
           end
           for k = 1:size(C, 2)
               @inbounds for col = 1:size(A, 2)
                   αxj = B[col,k] * α
                   for j = nzrange(A,col)
                       C[rv[j], k] += nzv[j]*αxj
                   end
               end
           end 
           C   
       end
julia> Base.:*(A::SparseArrays.SparseMatrixCSCUnion{TA}, x::BitArray{K}) where {TA,K} = (T = Base.promote_op(SparseArrays.matprod, TA, Bool); SparseArrays.mul!(Array{T,K}(x), A, x, true, false));
julia> N=1000; M=sprand(Bool,N,N,10/N); x=rand(N) .> 0.5; y=Vector(x);
julia> @btime $M*$x;
  18.118 μs (1 allocation: 7.94 KiB)
julia> @btime $M*$y;
  16.586 μs (1 allocation: 7.94 KiB)
```

**Comment by mbauman** [comment]
Seems like that could get widened the whole way to `B::AbstractVecOrMat`.  We only ask for its `size` and `getindex`.

**Comment by abraunst** [comment]
I get the following abiguity if I widen it to `AbstractVecOrMat`:

```julia
ERROR: MethodError: mul!(::Vector{Int64}, ::SparseMatrixCSC{Bool, Int64}, ::BitVector, ::Bool, ::Bool) is ambiguous. Candidates:
  mul!(C::StridedVecOrMat{T} where T, A::SparseArrays.AbstractSparseMatrixCSC, B::AbstractVecOrMat{T} where T, α::Number, β::Number) in Main at REPL[4]:1
  mul!(y::AbstractVector{T} where T, A::AbstractVecOrMat{T} where T, x::AbstractVector{T} where T, alpha::Number, beta::Number) in LinearAlgebra at /home/ab/src/julia/build1.6/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/matmul.jl:81
Possible fix, define
  mul!(::StridedVector{T} where T, ::SparseArrays.AbstractSparseMatrixCSC, ::AbstractVector{T} where T, ::Number, ::Number)
```

there is no ambiguity when multiplying with `x::BitMatrix`, so the suggestion probably works. I have no idea what is the "correct" fix though!

**Comment by mbauman** [comment]
Yeah, `mul!` is a bit of an ambiguity minefield.

**Comment by abraunst** [comment]
Ok, I had a little more time to look at it, and I think that widening the type to `AbstractVecOrMat` (or for that matters, to `AbstractVector` and `AbstractMatrix` separately) would not be a good idea. The reason is that when a new matrix type comes along, it will be impossible to define the generic product with `AbstractMatrix` without summoning abiguities in a product with `SparseArrayCSC` (as the new product would be more specific with respect to the new type and the sparse product would be more specific wrt the sparse matrix). 

Instead, a very simple shortcut to solve the problem at hand and also having the definition of matrix product in the inverse order, plus adjoint and transposes of `BitArray`s is to include `BitArray` (or both `BitVector` and `BitMatrix`) into the `StridedOrTriangularMatrix` union. Should I prepare a PR to see how it looks?
