### ISSUE TITLE
compilation error with julia-1.5.3 atomic.h

### ISSUE THREAD

**Issue by hahntas** [JuliaLang/julia#39472]
By compiling a external c++ library the following error occurs

d:\third_party\julia-1.5.3\include\julia\atomics.h(269): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\third_party\julia-1.5.3\include\julia\atomics.h(269): error C2143: syntax error: missing ',' before '*'
d:\third_party\julia-1.5.3\include\julia\atomics.h(271): error C2065: 'obj': undeclared identifier
d:\third_party\julia-1.5.3\include\julia\atomics.h(271): error C2146: syntax error: missing ';' before identifier 'val'
d:\third_party\julia-1.5.3\include\julia\atomics.h(271): error C2065: 'val': undeclared identifier

**Comment by StefanKarpinski** [comment]
This appears to be an MSVC error. Julia does not support compilation with MSVC. You can compile it with clang or gcc.
