### ISSUE TITLE
Using ∑ as a binding to Base.sum

### ISSUE THREAD

**Issue by Cc618** [JuliaLang/julia#39486]
#### Hi !

Some functions like **sqrt** have bindings with special characters (**√** refers to sqrt for example).
Why not using **∑** (which can be typed by *\sum\<tab\>*) for the **Base.sum** function ?

This special character can make an equation easier to read and provides more similarity with maths.

What do you think ?
I can implement this feature if it makes sense.

**Comment by jishnub** [comment]
Looks like several packages [use it in different contexts](https://juliahub.com/ui/CodeSearch?q=%CE%A3&u=all&t=all). It might be breaking. In particular `Σ` is often used to denote a covariance matrix, so this might be confusing.

**Comment by Cc618** [comment]
OK, thanks for your feedback! This is true that sigma and the sum symbol are too close and can lead to ambiguity. I'm closing the issue
