### ISSUE TITLE
value types in get!() 

### ISSUE THREAD

**Issue by HJW019** [JuliaLang/julia#39489]
`get!(collection, key, default)` would return the value stored for the given key, or if no mapping for the key is present, store key => default, and return default.

However, I found that if the `collection` does not already have the type of values I want to store, `get!()` would fail to add in another value. Here are some examples.

Eg. Trying to add a string-type value to the dictionary where the existing values are type Int64. Fail. Perhaps because `w` is defined as type Int64 by the first line of the code.
```
julia>    w = Dict("a" => 1, "b" => 2);
julia>    get!(w, "c", "test_c")
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Int64
```

Eg. Trying to add a Int64 value to the dictionary where the exiting values are all type String. Fail. Perhaps because `w` is defined as type String by the first line of the code.
```
julia>  w = Dict("a" => "test_a", "b" => "test_b");
julia>  get!(w, "c", 3)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type String  
```

The following two examples, however, are fine, perhaps because the existing dictionary already has both type String and type In64 values.
```
julia> w = Dict("a" => 1, "b" => "test_b");
julia> get!(w, "c", "test_c")
"test_c"
julia> w
Dict{String,Any} with 3 entries:
  "c" => "test_c"
  "b" => "test_b"
  "a" => 1
```  
```
julia>  w = Dict("a" => 1, "b" => "test_b");
julia>  get!(w, "c", 3)
3
julia>  w
Dict{String,Any} with 3 entries:  
  "c" => 3
  "b" => "test_b"
  "a" => 1
```

Is this a bug or a design feature?

**Comment by KristofferC** [comment]
> However, I found that if the collection does not already have the type of values I want to store, get!() would fail to add in another value. 

This is because the type of the created dictionary is different:

```
julia> w = Dict("a" => 1, "b" => 2);

julia> typeof(w)
Dict{String, Int64}

julia> w = Dict("a" => 1, "b" => "test_b");

julia> typeof(w)
Dict{String, Any}
``` 

So yes, this is expected. In general, questions are better of at https://discourse.julialang.org/.
