### ISSUE TITLE
GC.@preserve does not handle abstract types

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#39501]
The following crashes during codegen of `gc_preserve_begin` because of calling `emit_unbox` on an abstract value:

```julia
function main()
    val = if rand()<0.5
        1
    else
        1f0
    end

    GC.@preserve val begin
        println("here we go")
    end

    val
end
```

```
julia: /buildworker/worker/package_linux64/build/src/cgutils.cpp:406: unsigned int julia_alignment(jl_value_t*): Assertion `(((jl_value_t*)(((jl_taggedvalue_t*)((char*)(jt) - sizeof(jl_taggedvalue_t)))->header & ~(uintptr_t)15))==(jl_value_t*)(jl_datatype_type)) && ((jl_datatype_t*)jt)->layout' failed.

signal (6): Aborted
in expression starting at /tmp/wip.jl:15
gsignal at /usr/bin/../lib/libc.so.6 (unknown line)
abort at /usr/bin/../lib/libc.so.6 (unknown line)
__assert_fail_base.cold at /usr/bin/../lib/libc.so.6 (unknown line)
__assert_fail at /usr/bin/../lib/libc.so.6 (unknown line)
julia_alignment at /buildworker/worker/package_linux64/build/src/cgutils.cpp:406
emit_unbox at /buildworker/worker/package_linux64/build/src/intrinsics.cpp:375
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3858
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3339
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3576 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6110
```

Reproduces on 1.5 and 1.6, and seems introduced by https://github.com/JuliaLang/julia/pull/34241.

@vtjnash @Keno Thoughts on a fix?

FWIW, I encountered this in CUDA.jl where we `GC.@preserve` all arguments passed to `@cuda`.

**Comment by Keno** [comment]
`GC.@preserve` isn't particularly meaningful on immutable objects. We should probably just ignore them in codegen.

**Comment by StefanKarpinski** [comment]
While you're at it, maybe allow `GC.@preserve f(...) expr` to work with the semantics that whatever object `f(...)` evaluates to is preserved. I've occasionally wanted that to work. It's possible to work around by assigning the expression value to a local variable, but it seems unnecessary to require that.

**Comment by maleadt** [comment]
> allow `GC.@preserve f(...) expr` to work with the semantics that whatever object `f(...)` evaluates to is preserved

How do you use that object then? It seems strange to have `f(...)` return something new you couldn't have used to, e.g., derive a pointer from for use in `expr`.

**Comment by vtjnash** [comment]
You might be forbidden from taking a pointer to it anyways, but sometimes the result is still useful to preserve (usually as a container of other pointers)
