### ISSUE TITLE
Out of tree builds failure

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#39523]
As noted at https://github.com/JuliaLang/julia/pull/38160#issuecomment-773489735, it seems that out of tree builds and/or setting custom install directories are broken on 1.6.0-beta1. I discovered this when trying to make the Fedora RPM package.

```julia
cd /tmp
wget https://github.com/JuliaLang/julia/releases/download/v1.6.0-beta1/julia-1.6.0-beta1.tar.gz
tar xf julia-1.6.0-beta1.tar.gz
mkdir mybuild
cd julia-b84990e1ac
make -j2 prefix=/usr bindir=/usr/bin libdir=/usr/lib64 libexecdir=/usr/libexec datarootdir=/usr/share includedir=/usr/include sysconfdir=/etc build_prefix=/tmp/mybuild/usr build_bindir=/tmp/mybuild/usr/bin build_libdir=/tmp/mybuild/usr/lib64 build_private_libdir=/tmp/mybuild/usr/lib64/julia build_libexecdir=/tmp/mybuild/usr/libexec build_datarootdir=/tmp/mybuild/usr/share build_includedir=/tmp/mybuild/usr/include build_sysconfdir=/tmp/mybuild/etc release

[...]
make[1]: *** No rule to make target '/tmp/mybuild/usr/lib64/libuv.a', needed by '/tmp/mybuild/usr/lib64/libjulia-internal.so.1.6'.  Stop.
make[1]: *** Waiting for unfinished jobs....
    CC src/llvm-demote-float16.o
make: *** [Makefile:76: julia-src-release] Error 2
```

Using `USE_BINARYBUILDER_LIBUV=0` (as in the RPM package I do that anyway), I get a different error:
```
make -j2 USE_BINARYBUILDER_LIBUV=0 prefix=/usr bindir=/usr/bin libdir=/usr/lib64 libexecdir=/usr/libexec datarootdir=/usr/share includedir=/usr/include sysconfdir=/etc build_prefix=/tmp/mybuild/usr build_bindir=/tmp/mybuild/usr/bin build_libdir=/tmp/mybuild/usr/lib64 build_private_libdir=/tmp/mybuild/usr/lib64/julia build_libexecdir=/tmp/mybuild/usr/libexec build_datarootdir=/tmp/mybuild/usr/share build_includedir=/tmp/mybuild/usr/include build_sysconfdir=/tmp/mybuild/etc release
[...]
   LINK /tmp/mybuild/usr/lib64/libjulia-internal.so.1.6
Warning: git information unavailable; versioning information limited
    JULIA /tmp/mybuild/usr/lib64/julia/corecompiler.ji
ERROR: Unable to load dependent library /tmp/mybuild/usr/bin/../lib64/libopenlibm.so
Message:/tmp/mybuild/usr/bin/../lib64/libopenlibm.so: cannot open shared object file: No such file or directory
make[1]: *** [sysimage.mk:61: /tmp/mybuild/usr/lib64/julia/corecompiler.ji] Error 1
make: *** [Makefile:82: julia-sysimg-ji] Error 2
```

Cc: @staticfloat

**Comment by staticfloat** [comment]
Here's the fix that I found necessary: https://github.com/JuliaLang/julia/pull/39567

**Comment by nalimilan** [comment]
Thanks! Indeed that fixes the examples I posted above.

Unfortunately I still get a failure when building the RPM after applying the patch and removing `${build_prefix}/lib`. Looks like it's due to `USE_SYSTEM_OPENLIBM=1`. Here's a reproducer:
```julia
make -j2 USE_SYSTEM_OPENLIBM=1 prefix=/usr bindir=/usr/bin libdir=/usr/lib64 libexecdir=/usr/libexec datarootdir=/usr/share includedir=/usr/include sysconfdir=/etc build_prefix=/tmp/mybuild/usr
[...]
    JULIA /tmp/mybuild/usr/lib/julia/corecompiler.ji
ERROR: Unable to load dependent library /tmp/mybuild/usr/bin/../lib/libopenlibm.so
Message:/tmp/mybuild/usr/bin/../lib/libopenlibm.so: cannot open shared object file: No such file or directory
```

**Comment by staticfloat** [comment]
After re-learning how our out-of-tree build system works, I don't think we're using it quite right. I think you should be setting `O=/tmp/mybuild`, and calling `make configure` before doing any building.

I believe what you're seeing is that there are stale cached files in your source checkout (such as `cli/loader_lib.o`) that are hanging around from an old build and interfering with things.

**Comment by nalimilan** [comment]
> After re-learning how our out-of-tree build system works, I don't think we're using it quite right. I think you should be setting `O=/tmp/mybuild`, and calling `make configure` before doing any building.

Hmm, I have no idea what this should do, but running that doesn't fix the failure.

> I believe what you're seeing is that there are stale cached files in your source checkout (such as `cli/loader_lib.o`) that are hanging around from an old build and interfering with things.

Unfortunately no. I just ran the example above after removing everything and it still fails. Also RPM builds always start from a clean system.

Actually I've just realized that `make -j2 USE_SYSTEM_OPENLIBM=1 libdir=/usr/lib64` is enough to reproduce the failure. So it's a different problem from the one I originally reported. Maybe it's simpler to fix also: a symlink might just be missing.

**Comment by staticfloat** [comment]
> Actually I've just realized that make -j2 USE_SYSTEM_OPENLIBM=1 libdir=/usr/lib64 is enough to reproduce the failure.

Does it still occur if you don't override `libdir`?

**Comment by nalimilan** [comment]
Woops, yes, it does. I started with so many settings that I didn't hope to find such a simple MWE. :-D

The problem seems to be that the symlink is created at /tmp/julia-b84990e1ac/usr/bin/../lib/julia/libopenlibm.so but Julia is looking at it at /tmp/julia-b84990e1ac/usr/bin/../lib/libopenlibm.so.

**Comment by nalimilan** [comment]
Is it expected that neither julia nor libjulia.so nor libjulia-internal.so link to libopenlibm according to ldd? Wouldn't that help?

**Comment by staticfloat** [comment]
Are you _certain_ that there are no `.o` files in your `cli/` directory?  If you are certain of that, can you print out the following:

```
$ eval $(make USE_SYSTEM_OPENLIBM=1 print-LOADER_BUILD_DEP_LIBS); echo ${LOADER_BUILD_DEP_LIBS}
libgcc_s.so.1:julia/libopenlibm.so:libjulia-internal.so.1
```

If there is a `.o` file in your `cli/` directory, look to see if it has a path embedded within it:
```
$ strings cli/loader_lib.o | grep libm
libgcc_s.so.1:julia/libopenlibm.so:libjulia-internal.so.1
```

If that exists, clear it out and try the `make` command again.

> Also RPM builds always start from a clean system.

Is it possible that you're running a `make` command that builds the files in `cli` without setting `USE_SYSTEM_OPENLIBM=1`, then later you invoke `make` and those `.o` files have already been built?

**Comment by staticfloat** [comment]
> Is it expected that neither julia nor libjulia.so nor libjulia-internal.so link to libopenlibm according to ldd? Wouldn't that help?

Yes, we don't link to it with `ldd`, we open it via `dlopen()`.

**Comment by nalimilan** [comment]
I'm certain because I removed the whole source and build folder between each run. ;-)

```julia
eval $(make USE_SYSTEM_OPENLIBM=1 print-LOADER_BUILD_DEP_LIBS); echo ${LOADER_BUILD_DEP_LIBS}
Warning: git information unavailable; versioning information limited
libgcc_s.so.1:libopenlibm.so:libjulia-internal.so.1

```

**Comment by nalimilan** [comment]
And after running `make USE_SYSTEM_OPENBLIM=1`:
```
$ strings cli/loader_lib.o | grep libm
libgcc_s.so.1:libopenlibm.so:libjulia-internal.so.1
```

**Comment by staticfloat** [comment]
`make USE_SYSTEM_OPENBLIM=1`

🤔  what happens if you clean and then do `make USE_SYSTEM_OPENLIBM=1`?

**Comment by nalimilan** [comment]
You mean `make clean` or deleting the folders?

**Comment by staticfloat** [comment]
Just `make -C cli clean`

**Comment by nalimilan** [comment]
I get:
```
$ eval $(make USE_SYSTEM_OPENLIBM=1 print-LOADER_BUILD_DEP_LIBS); echo ${LOADER_BUILD_DEP_LIBS}
Warning: git information unavailable; versioning information limited
libgcc_s.so.1:libopenlibm.so:libjulia-internal.so.1
$ ls cli/*.o
ls: cannot access 'cli/*.o': No such file or directory
```

**Comment by staticfloat** [comment]
Ah!  I bet you're using `release-1.6` and not master.  In that case, I bet it's because https://github.com/JuliaLang/julia/pull/38997/files wasn't backported.  Can you carry that patch and see if that fixes things for you?

**Comment by nalimilan** [comment]
Yes, that was it! Too bad I kept using 1.6... :-/ Thanks for your help.

I'll retry the RPM tomorrow, let's hope I don't get a third error!
