### ISSUE TITLE
Varargs-related subtype abort

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#39521]
```
Tuple{Type{Base.PermutedDimsArrays.PermutedDimsArray{Float32, 3, _A, _B, Array{Float32, 3}}} where _B where _A, DataType, DataType} <: Tuple{Vararg{V, N}} where V where N

julia: /home/tim/Julia/src/julia/src/subtype.c:1887: jl_subtype_env: Assertion `obvious_subtype == 3 || obvious_subtype == subtype || jl_has_free_typevars(x) || jl_has_free_typevars(y)' failed.

signal (6): Aborted
in expression starting at none:1
jl_subtype_env at /home/tim/Julia/src/julia/src/subtype.c:1887
jl_f_issubtype at /home/tim/Julia/src/julia/src/builtins.c:444
```

Reproduces on `release-1.6` branch ~~(e.g., https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.6/julia-8ceeb68753-linux64.tar.gz) but not on master (e.g., https://s3.amazonaws.com/julialangnightlies/pretesting/linux/x64/1.7/julia-20224a6686-linux64.tar.gz). Are we missing a backport? cc @KristofferC; I'll see about bisecting this~~, and also on `master`.

**Comment by maleadt** [comment]
Slightly shorter:
`Tuple{Type{PermutedDimsArray{Int, 1, A, B, Array}} where B where A, DataType, DataType} <: Tuple{Vararg{V}} where V`

This happens as part of the CUDA.jl test suite, and didn't on 1.5, so tentatively adding to the milestone.

**Comment by vtjnash** [comment]
FWIW, we have:
```
(lldb) p obvious_subtype
(int) $0 = 0
(lldb) p subtype
(int) $1 = 1
```

**Comment by jagot** [comment]
This is amazing, I had just jumped ship from the beta (where I encountered no problems) to the RC-1 (where I crashed with this) and thought to myself "oh )*(*#%, how will I ever produce a MWE from this?" because it crashed without any stacktrace, somewhere in my solver. Then I find that you've already fixed it 😍 and it works on the latest nightly.
