### ISSUE TITLE
Doc improvement - rem docstring example

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#39554]
Hello,

`rem` docstring example shows

```
  rem(x, y)
  %(x, y)

  Remainder from Euclidean division, returning a value of the same sign as x, and smaller in magnitude than y. This value is
  always exact.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> x = 15; y = 4;

  julia> x % y
  3

  julia> x == div(x, y) * y + rem(x, y)
  true
```

That's probably not the best example because 

```
julia> div(x, y)
3

julia> rem(x, y)
3
```

which could lead to confusion.

So maybe it should be replaced by

```
julia> x = 9; y = 4;

julia> x % y  # same as rem(x, y)
1

julia> x ÷ y  # same as div(x, y)
2

julia> x == div(x, y) * y + rem(x, y)
true
```

Any opinion about that?

Kind regards

**Comment by scls19fr** [comment]
Master version of rem docstring seems to be slightly different and doesn't show currently any example.
PR https://github.com/JuliaLang/julia/pull/39555 provides an example

**Comment by mcabbott** [comment]
Perhaps worth linking #38606, which hopes to add an example like this to div/rem/fld/etc:

```julia
julia> rem.(-5:5, 3)'
1×11 adjoint(::Vector{Int64}) with eltype Int64:
 -2  -1  0  -2  -1  0  1  2  0  1  2
```
https://github.com/JuliaLang/julia/pull/38606/files#diff-12e7a6522633012a408b1bdee7639e8cb722617fe1a8ed6a3881bf4ad1ebdbbdR781-R783
