### ISSUE TITLE
`return` in `begin ... end` block

### ISSUE THREAD

**Issue by ettersi** [JuliaLang/julia#39558]
This works as intended:
```
julia> x = 1
       begin
           return x
       end
1
```
This gives an error:
```
julia> [begin
           return x
       end for x = 1:3]
ERROR: syntax: "return" not allowed inside comprehension or generator
```
I'm aware of [this discussion](https://discourse.julialang.org/t/possible-bug-return-inside-an-array-comprehension/4193/) pointing out that `return` in a generator can be confusing, but maybe disallowing `return` in a `begin ... end` block inside a generator overshoots the target?

I'm pointing this out because my students often find it difficult to understand which part of the `begin ... end` block produces the array values in code like the following. 
```
[begin
    y = x^2
    y
end for x = 1:3]
```
I believe adding a `return` would make this much clearer if only it was allowed.
```
[begin
    y = x^2
    return y
end for x = 1:3]
```

**Comment by simeonschaub** [comment]
> but maybe disallowing return in a begin ... end block inside a generator overshoots the target?

I don't see why `begin ... end` would make a difference here. `return ` refers to the innermost enclosing function regardless of other blocks, that it also works at the toplevel is mostly an edge case. The reason we disallow this is that the fact that comprehensions are implemented in terms of closures should really be more of an implementation detail, so it is reasonable to expect the `return` inside the comprehension to immediately return from an enclosing function, but instead it previously refered to the closure created for the generator.

**Comment by ettersi** [comment]
I guess I had a misconception about how `return` would work inside a `begin ... end` block. Basically, I would have hoped that the following function would have returned `2`, but instead it returns `1`:
```
function foo()
    begin
        return 1
    end
    return 2
end
```
Maybe changing the meaning of `return` inside `begin ... end` is something to think about, but clearly that is a much, much bigger change than what I initially had in mind. I am therefore closing this issue, but please do let me know if you have any ideas regarding how to more clearly indicate what is the "array value" in a list comprehension.
