### ISSUE TITLE
In v2, Iterators.peel could return `nothing` when iterator is empty

### ISSUE THREAD

**Issue by cmcaine** [JuliaLang/julia#39569]
`Iterators.peel` is a lazy version of `h, t... = collection`, which is a very common pattern in recursive code. I think it would be good if it were more ergonomic to use. If `h, t... = collection` will still be eager in v2, I think the simplest improvement would be to have `Iterators.peel` pass through `nothing` if the iterator is empty so that we don't need to do exception handling.

Current behaviour:
```jl
try
    h, t = Iterators.peel(itr)
    # do something with h and t
catch e
    if e isa BoundsError
        # itr was probably empty
    else
        rethrow()
    end
end
```

New proposal:
```jl
x = Iterators.peel(itr)
if isnothing(x)
    # itr was empty
end
h, t = x
# do something with h, t
```

**Comment by vtjnash** [comment]
Care to make a PR? Looks like it should be non-breaking, since an attempt later to index or splat that `nothing` would still fail.

**Comment by cmcaine** [comment]
Sure. If for some reason you do iterators.peel and pass the object along without looking at it, this would move the location of the exception quite a lot, but if that's okay I can do a PR.

**Comment by cmcaine** [comment]
Submitted a PR. It passes tests, but I think the change should probably be run against the wider ecosystem.

**Comment by cmcaine** [comment]
Just did a code search on GitHub, and none of the 140 matches for Iterators.peel would be broken by this change.
