### ISSUE TITLE
Type inference problem with `getproperty`

### ISSUE THREAD

**Issue by drbassett** [JuliaLang/julia#39563]
I was recently tripped up by a performance problem with a custom implementation of `getproperty`. In summary, the problem is that using the dot operator within `getproperty` invokes `getproperty` recursively, which complicates the job of the type inference system in Julia, and causes type-instability. See the issue I posted to discourse for more details: https://discourse.julialang.org/t/type-inference-problem-with-getproperty/54585.

I am guessing this will be a difficult problem to fix, since `getproperty` is a very free-form function. However, I am no expert on the Julia backend, so maybe it is a possibility. In case this turns out to be an intractable problem, I created a PR adding a warning to the documentation for `getproperty`: https://github.com/JuliaLang/julia/pull/39551.

**Comment by simeonschaub** [comment]
This seems to be fixed now
