### ISSUE TITLE
CartesianIndices (breaking?) change in 1.6.0-rc1

### ISSUE THREAD

**Issue by akosuas** [JuliaLang/julia#39589]
Something has changed here:
```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_PKG_SERVER = pkg.julialang.org
julia> CartesianIndices((3, 1:3))
1×3 CartesianIndices{2,Tuple{UnitRange{Int64},UnitRange{Int64}}}:
 CartesianIndex(3, 1)  CartesianIndex(3, 2)  CartesianIndex(3, 3)
 ```

```
julia> versioninfo()
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_PKG_SERVER = pkg.julialang.org
julia> CartesianIndices((3, 1:3,))
3×3 CartesianIndices{2, Tuple{Base.OneTo{Int64}, UnitRange{Int64}}}:
 CartesianIndex(1, 1)  CartesianIndex(1, 2)  CartesianIndex(1, 3)
 CartesianIndex(2, 1)  CartesianIndex(2, 2)  CartesianIndex(2, 3)
 CartesianIndex(3, 1)  CartesianIndex(3, 2)  CartesianIndex(3, 3)
julia> versioninfo()
```

Is this expected? It is breaking some of my code, and I can't find anything obvious in NEWS that describes this.

**Comment by akosuas** [comment]
Reading a bit more closely, looks likely to be caused by https://github.com/JuliaLang/julia/pull/37829. I wonder if my single-integer usage of CartesianIndices was "supported" in the first place?

**Comment by simeonschaub** [comment]
Is this breaking any code? `CartesianIndex((Base.OneTo(3), 1:3))` does seem more correct to me here than `CartesianIndex((1:3, 1:3))`. It should behave exactly the same , but IIUC this change was necessary to improve performance of `CartesianIndices`.

**Comment by JeffBezanson** [comment]
The 1.5 behavior seems to have been inconsistent:
```
julia> CartesianIndices((2,3))
2×3 CartesianIndices{2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}:
 CartesianIndex(1, 1)  CartesianIndex(1, 2)  CartesianIndex(1, 3)
 CartesianIndex(2, 1)  CartesianIndex(2, 2)  CartesianIndex(2, 3)

julia> CartesianIndices((2,1:3))
1×3 CartesianIndices{2,Tuple{UnitRange{Int64},UnitRange{Int64}}}:
 CartesianIndex(2, 1)  CartesianIndex(2, 2)  CartesianIndex(2, 3)
```
That can't be right, but I'm not sure what was intended.

**Comment by akosuas** [comment]
Thanks for investigating guys. 

If I was relying on some dodgy / broken behaviour in 1.5, I'm happy to switch to an explicit one-element range, i.e. `CartesianIndices((3:3, 1:3))` instead of `CartesianIndices((3, 1:3)`.

**Comment by mbauman** [comment]
Yes, that behavior was definitely unintentional and buggy.  Integers should always describe 1-based lengths; ranges should always specify indices.  Sorry this caught you out — perhaps we should indeed add a NEWS item.

**Comment by johnnychen94** [comment]
FYI, I made that change intentionally in https://github.com/JuliaLang/julia/pull/37829#discussion_r498015243, and also to `LinearIndices` in #37928.

**Comment by akosuas** [comment]
> 
> 
> FYI, I made that change intentionally in [#37829 (comment)](https://github.com/JuliaLang/julia/pull/37829#discussion_r498015243), and also to `LinearIndices` in #37928.

Ah, nicely done, I hadn't spotted that.

**Comment by sostock** [comment]
I have added a NEWS/HISTORY item for the change: #39784

**Comment by johnnychen94** [comment]
Close since this is already solved: this change is considered a bug fix with associated NEWS entry.
