### ISSUE TITLE
Inconsistent printing of booleans with and without missings

### ISSUE THREAD

**Issue by racinmat** [JuliaLang/julia#39590]
Applicable in versions of Julia:
1.5.3, 1.6.0-rc1

```julia
julia> rand([true,missing], 2, 2)
2×2 Array{Union{Missing, Bool},2}:
 true         missing
     missing  missing

julia> rand([true, false], 2, 2)
2×2 Array{Bool,2}:
 0  0
 0  1
```

when missing values are present, booleans are printed in a different way than without missing values, it should be consistent, either true/false or 0/1 all the times.

This was created based on the discussion in https://julialang.slack.com/archives/C67910KEH/p1612874306319500

**Comment by JeffBezanson** [comment]
I suppose we could add a special case for `Union{Bool,Missing}`, but this isn't a bug in general, since there is no simple way to know whether `T` is specific enough for `convert(T, 0) === false` to hold.

**Comment by racinmat** [comment]
That would be great. This also happens with Nothing.
