### ISSUE TITLE
type constraints from multiple `||` conditions don't propagate well

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#39611]
Originally posted at https://github.com/JuliaLang/julia/pull/39549/files#r571434978

Constraints don't propagate well in the following case:
```julia
julia> Base.return_types((Union{Int,Nothing},)) do x
           if x === nothing || x < 0
               return 0
           end
           x # x::Int, ideally
       end
1-element Vector{Any}:
 Union{Nothing, Int64}
```

Ideas to fix are quoted from [@vtjnash 's response](https://github.com/JuliaLang/julia/pull/39549/files#r573995564):
> It is the lowering structure. For ``&&`` it is lowered to a nested `if` block, but not so for `||`. So for entry to `#4`, we have the tmerge for `[x = Nothing, _3 = Conditional(:x, Nothing, Int)]` and `[x = Int, _3 = Bool]`. Instead, lowering could fuse the `goto #4` into the next line (jump-threading), and do `goto #5` there to fix this. Or we should narrow the later `_3 = Bool` to the equivalent `_3 = Conditional(x, Int, Int)` before the corresponding tmerge. Either way, a good update to consider for later:
> ```
> julia> code_typed((Union{Int,Nothing},), optimize=false) do x
>            if x === nothing || x < 0
>                return 0
>            end
>            x # x::Int, ideally
>        end
> 1-element Vector{Any}:
>  CodeInfo(
>     @ REPL[6]:2 within `#13'
> 1 ─ %1 = (x === Main.nothing)::Bool
> └──      goto #3 if not %1
> 2 ─      (@_3 = %1)::Bool
> └──      goto #4
> 3 ─      (@_3 = x::Int64 < 0)::Bool
> 4 ┄      goto #6 if not @_3
>     @ REPL[6]:3 within `#13'
> 5 ─      return 0
>     @ REPL[6]:5 within `#13'
> 6 ─      return x
> ) => Union{Nothing, Int64}
> ```

**Comment by vtjnash** [comment]
We still might want to do the inference improvement too, since that should handle the case where the user wrote it out rather verbosely (like below). It might however be odd that `Conditional` would get a better tmerge result than `Const(true)` however, so also perhaps not.
```julia
julia> function f(x)
         x = x[]
         y = x === nothing
         if y
           z = y
         else
           z = x < 0
         end
         if z
           return 0
         end
         return x
       end
```
