### ISSUE TITLE
BINARY=64 not set on aarch64

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#39612]
I'm not certain if this is an unintentional oversight or something more profound, but our `Makefile` system does not set `BINARY=64` on `aarch64`.  This, in turn, causes OpenBLAS to be built (from source) as an LP64 (e.g. not an ILP64) build, which in turn causes us to build OpenBLAS as LP64 in Yggdrasil, which is not in line with our other 64-bit platforms such as `x86_64` and `powerpc64le`.

I think we probably want to build OpenBLAS as ILP64 and set BINARY=64 on aarch64.

**Comment by staticfloat** [comment]
Pinging a randomized subset of the linear algebra crew to see if there is any reason ILP64 might be disabled on aarch64.

@ViralBShah @andreasnoack @simonbyrne

**Comment by simonbyrne** [comment]
Need to contact this guy: https://github.com/JuliaLang/julia/pull/31399

**Comment by staticfloat** [comment]
I knew there was a reason I pinged you Simon.

**Comment by ViralBShah** [comment]
Yeah, we should probably go to ILP64 on aarch64. It will also require a bunch of BB stuff to be rebuilt.

**Comment by matbesancon** [comment]
So this will be blocking https://github.com/JuliaLang/julia/issues/39436 if I understand correctly?

**Comment by ViralBShah** [comment]
My understanding is - we merge this one first - and then make the corresponding change on the Julia side (almost simultaneously) so that we don't have CI breakage.

**Comment by ViralBShah** [comment]
#39455 turns on ILP64 BLAS for aarch64, and passes all tests, so this does not block #39436 (surprisingly). I do wonder if `BINARY=64` should be turned on as well (assuming `-m64` can be accepted by gcc/clang on aarch64).

**Comment by ViralBShah** [comment]
Note that this will only really pick ILP64 for openblas (which we are already doing in Yggdrasil now). Currently, the `-m64` flag only gets passed on `x86_64`: https://github.com/JuliaLang/julia/blob/6fe0827ba48a135caa5bc32308aa7e1ffb43486e/Make.inc#L950

Do we want it on `aarch64` and `ppc64le`?

**Comment by ViralBShah** [comment]
`-m64` is not accepted by GCC on arm. So nothing else to be done here.
