### ISSUE TITLE
sort! changes array elements when sorting arrays of mutable Integer subtypes (such as BigInt)

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#39620]
Sorting an array in place with `sort!` rearranges its elements into sorted order. Only order should change; the individual array elements should stay the same.

Arrays of mutable `Integer` subtypes can violate this invariant due to an [incorrect optimization](https://github.com/JuliaLang/julia/blob/master/base/sort.jl#L736) for arrays with repeated integer values.

Due to the optimization, `sort!` on such arrays will return the same array filled with entirely new objects. This allocates memory and can cause differences in program behavior. The elements of the sorted array are no longer `===` to elements of the original array and repeated values are all `===` to each other.

One example of a mutable `Integer` subtype is `BigInt`:

```
julia> a = BigInt.([2, 2, 2, 1, 1, 1]);

julia> IdDict(a .=> a)
IdDict{BigInt, BigInt} with 6 entries:
  1 => 1
  1 => 1
  2 => 2
  2 => 2
  1 => 1
  2 => 2

julia> sort!(a)
6-element Vector{BigInt}:
 1
 1
 1
 2
 2
 2

julia> IdDict(a .=> a)
IdDict{BigInt, BigInt} with 2 entries:
  2 => 2
  1 => 1
```

Another example of an issue with this behavior is if one uses a package that implements [in place arithmetic](https://github.com/tkluck/InPlace.jl) for `BigInt`s. Sorting an array then mutating an element will mutate all repeats since they are replaced with the same object. While this specific package uses Julia internals, the same issue would arise with any mutable integer type where mutation is allowed by the API.

**Comment by KristofferC** [comment]
Open a bug with the package? The fact that BigInts are mutable is an implementation detail and if any package uses the internals of Bigint it is up to it to handle it correctly.

**Comment by yurivish** [comment]
The `IdDict` example does not rely on `BigInt` internals. What are your thoughts on that example?

**Comment by thofma** [comment]
(You might want to edit the OP to not include the statement that this breaks packages which are relying on `BigInt` being mutable.)

Apparently this branch of sort! assumes that subtypes of `Integer` are immutable. This problem is unrelated to BigInt. n quick and easy fix would be to add the ismutable type check.

**Comment by yurivish** [comment]
Hi @thofma, I did not mean to suggest that this breaks packages which are relying on `BigInt` being mutable. If there is a bug here, it is in `sort!`. What my comment referred to was behavior like the following, where sorting an array of six distinct `BigInt`s and then adding to the first one actually adds to all of the first three since they refer to the same (new) object.

```julia
julia> using InPlace

julia> a = sort!(BigInt.([1, 2, 1, 2, 1, 2]));

julia> @inplace a[1] += 100
101

julia> a
6-element Vector{BigInt}:
 101
 101
 101
   2
   2
   2
```

**Comment by thofma** [comment]
Sorry for the misunderstanding. I meant that people will (rightfully) note that the mutabilty of `BigInt` is an implementation detail and use of it is at own risk. But the issue you raise has nothing to do with this.

The method for `sort!` is broken for all mutable subtypes of `Integer`. BigInt is just one (bad) example.

**Comment by yurivish** [comment]
sort! changes array elements when sorting arrays of mutable Integer subtypes (such as BigInt)

**Comment by timholy** [comment]
Really, being a subtype of `Integer` should *imply* immutability. It's just a bug of BigInt that it isn't.

**Comment by thofma** [comment]
Where is that documented or discussed?

**Comment by JeffBezanson** [comment]
I don't mind adding an ismutable check so much; the question is whether it's ok to lose the performance of counting sort for BigInt and other mutable types. I think mutable Integers are a marginal enough use case that you should have to manually specify a sorting algorithm. Maybe we should add an official CountingSort alg, and also be sure not to use it if another algorithm is requested?

**Comment by timholy** [comment]
> Where is that documented or discussed?

Not sure, but it would bother me just a bit if `3 = 4` worked and changed the value of 3 in future computations. Likewise if I could change a vector into a matrix by converting `Array{Int,1}` into `Array{Int,2}`. If you view Integer as a mathematical concept and all of its subtypes simply as an unfortunate necessity of the fact that math is imperfectly captured on computer hardware, then all Integers should have the same fundamental properties.

**Comment by fingolfin** [comment]
Many algorithms in abstract algebra dealing with arbitrary sized integers require in place operations on integers. To give a simple example is an accumulator where you compute `x += c` many times: if you create new integer objects each time, you wreck the asymptotic performance due to the severe memory / GC stress.

Of course one can also handle this by having a separate type MutableBigInt or BigIntAccumulator. But that comes with its own set if awkwardness. Also, BigInt and MutableBigInt would share 95% of their code, I guess?

**Comment by timholy** [comment]
Isn't that essentially a reference to an integer and not the number itself?

**Comment by fingolfin** [comment]
no, you want to modify the value in place, to avoid allocations as much as possible. Of course whenever the bigint needs a new limb, you still may have to allocate, but that's much rarer than doing it with ever single change.

**Comment by timholy** [comment]
My point is that we distinguish `r = Ref('c')` from `'c'`. You can mutate `r[]` even though `Char` is immutable. What we're currently calling `BigInt` might more accurately be thought of as a *container* for a "big integer."

I'm not proposing we change this any time soon, mind you, it's a big project that probably requires a lot of compiler optimization.

**Comment by kimikage** [comment]
I'm a little confused, isn't this simply a stability issue with the sort?

**Comment by kimikage** [comment]
Until I read the source code, I had assumed that the `alg` kwarg would take precedence. So does this mean that implementing a user-defined algorithm may not apply to integer arrays? (We can give `by=x->x` as a dummy, though.)
