### ISSUE TITLE
libgit2 fails to initialize when SSL_CERT_DIR contains multiple paths

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#39622]
I'm not sure whether to report the issue here, or in libgit2, given I've found earlier reports of a similar issue already.

libssl and boringssl support multiple directories separated by a colon in ``SSL_CERT_DIR``. I'm using multiple paths to prepend my custom CAs before the system ones.

libgit2 on my system is using mbedtls which apparently doesn't support this feature.
It attempts (and fails) to access the path containing a colon, failing to initialize.

Would it be possible to support this feature?

**Comment by StefanKarpinski** [comment]
No, there's nothing we can do about this — that's how the libgit2 API works:

https://github.com/libgit2/libgit2/blob/v0.24.2/include/git2/common.h#L246-L255

It is also how the libcurl API works — you can only set one path:

https://curl.se/libcurl/c/CURLOPT_CAINFO.html

A file or directory will work and you can put as many CA roots in either as you want to.
