### ISSUE TITLE
`timedwait` timeout exceeded on Mac CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#39652]
https://build.julialang.org/#/builders/11/builds/670/steps/5/logs/stdio

```
Error in testset channels:
Test Failed at /Users/julia/buildbot/worker-tabularasa/tester_macos64/build/share/julia/test/channels.jl:297
  Expression: ≈(duration, 1, atol = 0.4)
   Evaluated: 1.614929538 ≈ 1 (atol=0.4)
```

I'm not sure we can really ask for a max duration here. The mac kernel is certainly happy to preempt applications for seconds at a time if it needs to handle page compression or gets too hot. We could play with process priorities to try to get tighter deadlines, but in the end, we may have to just test `duration >= 1`, since that's the only thing we actually guarantee.

cc @omus who added these tests.

**Comment by omus** [comment]
I agree with your assessment. I'll adjust the tests to only specify a minimum.

**Comment by vtjnash** [comment]
`timedwait` is still just broken at a conceptual level (it rejects the concepts of data-races and ordering of dependent operations), and so here we now fail a different test that timers expire in some guaranteed order expeditiously:
```
channels                                         (4) |        started at 2022-10-13T11:53:40.604
channels                                         (4) |         failed at 2022-10-13T11:58:23.978
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-5.0/build/default-macmini-aarch64-5-0/julialang/julia-master/julia-40346e1e5e/share/julia/test/channels.jl:314
  Expression: isready(rr1)
```
https://github.com/JuliaLang/julia/blob/master/test/channels.jl#L307
https://buildkite.com/julialang/julia-master/builds/16941#0183d1e0-801e-4127-a14a-648fb9cb8b58
