### ISSUE TITLE
openblas threads slow for small matrices

### ISSUE THREAD

**Issue by guolas** [JuliaLang/julia#3965]
Hi,

I have just downloaded the latest version available on Github, and I have compiled it in two different systems:

- MacOS, Intel Core i5- @ 1.7GHz, with 4GB of memory.
- Linux, Intel Core i7-3960X CPU @ 3.30GHz, with 32GB of memory.

In both systems I have compiled the following version:

    Version 0.2.0-prerelease+3005
    Commit 0d39c66 2013-08-06 17:44:39 UTC

After executing the same Julia code, I have that the execution times are as follows:

- ~100s on the Mac.
- ~135s on the Linux.

Does it really make any sense?

I mean, the Linux computer is way more powerful, with 12 cores, each of which almost double the clock speed. And as it is executing, I can see, using `top` that all the CPUs are being used in the Linux machine, and still, it takes longer to finish the execution.

I have tried this several times, and it consistently yields the same execution times.

Thank you for any comment on this.

Regards,

Juanjo.

**Comment by ViralBShah** [comment]
We do pass `GEMM_MULTITHREADING_THRESHOLD=50` now, so perhaps this is no longer an issue. Please open if it still is.

**Comment by axsk** [comment]
I was experiencing a similar problem running some code first on my PC and later on cluster, launching 32 julia instances on 32 cores. Then I was surprised how much slower (per process) the cluster was.

Weeks later I discovered this here, and indeed forcing `export OPENBLAS_NUM_THREADS=1` lead to a 3x speed-up on the cluster.

Maybe this should be mentioned somewhere in the documentation.

**Comment by ViralBShah** [comment]
I believe it is mentioned, but if not, we certainly should.

**Comment by ViralBShah** [comment]
https://github.com/xianyi/OpenBLAS/issues/2587
