### ISSUE TITLE
Sum with init doesn't work for empty iterable

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#39669]
Documentation for `sum` says that `The value returned for empty itr can be specified by init.`. However, `sum(i for i in 1:0, init=0)` throws an error: `ArgumentError: reducing over an empty collection is not allowed`.
Same with `sum(identity, i for i in 1:0, init=0)`.
This happens on both 1.6 and nightly. As I understand, empty collections were the whole point of introducing `init=` argument, is it just not implemented yet?

**Comment by kimikage** [comment]
Interestingly, it works with a semicolon.
```julia
julia> sum(i for i in 1:0; init=0)
0
```

**Comment by simeonschaub** [comment]
`(i for i in 1:0, init=0)` creates a two-dimensional generator, i.e. it's the same as `(i for i in 1:0, init in 0)`, so `init=0` is parsed as part of the generator, not as a keyword argument.
