### ISSUE TITLE
Specialization for `BigInt(x::Integer)` on 64-bit Windows

### ISSUE THREAD

**Issue by kimikage** [JuliaLang/julia#39666]
In 64-bit Windows (or MinGW), the [LLP64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) data model is used. This means the following type aliases:
```julia
julia> Int
Int64

julia> Clong
Int32
```
`BigInt` has the specialized constructors below:
https://github.com/JuliaLang/julia/blob/2eeef2e231a55cac770543b6dd673e349adfd797/base/gmp.jl#L291-L292
However, since `Clong === Int32 && Culong === UInt32`, `BigInt(100)` will fall back to `BigInt(x::Integer)`.

https://github.com/JuliaLang/julia/blob/2eeef2e231a55cac770543b6dd673e349adfd797/base/gmp.jl#L310-L327

This method is somewhat expensive because it involves `realloc`. Therefore, I think we can specialize not only `0`, but also all numbers in the range of `Clong` and `Culong`, e.g.:
```julia
using Base.GMP
using Base.GMP: Limb, MPZ

function Base.GMP.BigInt(x::Integer)
    # 0 <= x <= typemax(Culong) && return BigInt(x % Culong) # specialization
    # typemin(Clong) <= x <= 0  && return BigInt(x % Clong) # specialization
    typemin(Clong) <= x <= typemax(Clong) && return BigInt(x % Clong) # less impact
    nd = ndigits(x, base=2)
    z = MPZ.realloc2(nd)
    s = sign(x)
    s == -1 && (x = -x)
    x = unsigned(x)
    size = 0
    limbnbits = sizeof(Limb) << 3
    while nd > 0
        size += 1
        unsafe_store!(z.d, x % Limb, size)
        x >>>= limbnbits
        nd -= limbnbits
    end
    z.size = s*size
    z
end
```

**Comment by kimikage** [comment]
I noticed this issue while doing some research on #39605.

```julia
julia> versioninfo()
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

julia> fib(n) = n < 2 ? n : fib(n-1)+fib(n-2)

julia> @btime fib(n) setup=(n=big"30");
  1.993 s (24232827 allocations: 390.31 MiB) # original
  1.429 s (18847754 allocations: 390.31 MiB) # with the specialization above
```
Of course it's still slow, but the specialization seems to be effective.

**Comment by jebej** [comment]
> In 64-bit Windows (or MinGW), the [LLP64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) data model is used. This means the following type aliases:

Does this mean that internally GMP uses `Int32` for its various storage needs? 

If so, does that difference explain why Windows is so much slower than Linus here (even after this patch)? Couldn't we compile GMP it to use `Int64` on Windows?

**Comment by kimikage** [comment]
> Does this mean that internally GMP uses Int32 for its various storage needs?

Strictly speaking, no. Internal storage is managed by `Base.GMP.BITS_PER_LIMB` units. Even on 64-bit Windows, the default is `64`.

GMP (MPZ) provides some special APIs for `signed long`/`unsigned long`. We should not change the API definition of GMP. That may cause inconsistencies with other libraries and packages.

However, we can still use the same technique as PR #39682 to specialize operations with `Int64`/`UInt64`. For example:
```julia
Base.:-(x::BigInt, y::Int64) = typemin(Clong) <= y <= typemax(Clong) ? x - unsafe_trunc(Clong, y) : x - BigInt(y)
```

**Comment by jebej** [comment]
I see. It's a bit disappointing that we can't directly use those APIs with `Int64` on Windows. Thanks for figuring this out!

**Comment by kimikage** [comment]
I proposed PR #39682 because it is an improvement with only one line of code change. If we want to make drastic improvements, I think there are several other approaches.

Porting GMP's C code to Julia is one of them. :smile:

**Comment by jebej** [comment]
Should we open an other issue for the rest of the operations being slower on Windows with `Int64` because they can't use the `Clong`/`Int32` API?
