### ISSUE TITLE
type inference precision regression on nightly

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#39673]
LightGraphs tests against nightly have been failing with type inference issues for the past several months.

Here's an example - this PR changes no code. Tests on stable pass; tests on nightly fail:

https://github.com/JuliaGraphs/LightGraphs.jl/pull/1517

(nightly)
https://github.com/JuliaGraphs/LightGraphs.jl/pull/1517/checks?check_run_id=1763058221

(stable)
https://github.com/JuliaGraphs/LightGraphs.jl/pull/1517/checks?check_run_id=1763058213

I know there are lots of upcoming changes, but is there something fundamental with type inference that would result in these new errors?

**Comment by sbromberger** [comment]
See also earlier effort to fix within LightGraphs: https://github.com/JuliaGraphs/LightGraphs.jl/pull/1510

**Comment by vtjnash** [comment]
tightening an inference result is always a feature, not a bug

**Comment by sbromberger** [comment]
I'm not convinced that this is a tightening, though. The code itself was inferring correctly in all our test cases in 1.5, and now it's not.

**Comment by sbromberger** [comment]
Give me a few minutes to run tests using a fresh copy of 1.6.0. Perhaps this was resolved somewhere along the way.

**Comment by sbromberger** [comment]
This problem is resolved in 1.6.0 - there are no inference errors reported anymore. This suggests to me that whatever was causing the inference errors was corrected or reverted. I'll go ahead and close this out.
