### ISSUE TITLE
`parse` is broken for parsing negatives in 2s compliment

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/julia#39683]
`parse(Int8, "11111111")` returns
```
ERROR: OverflowError: overflow parsing "11111111"
Stacktrace:
 [1] tryparse_internal(::Type{IInt8}, ::String, ::Int64, ::Int64, ::Int64, ::Bool) at ./parse.jl:160
 [2] parse(::Type{IInt8}, ::String; base::Nothing) at ./parse.jl:238
 [3] parse(::Type{IInt8}, ::String) at ./parse.jl:238
 [4] top-level scope at REPL[2]:1
 ```
 This means that `parse` currently can't return negative numbers for `Signed` datatypes. This appears in 1.5.3 and 1.6.

**Comment by Keno** [comment]
I'm confused. That is larger than typemax(UInt8). Did you mean to parse in base 2?
```
julia> parse(UInt8, "11111111", base=2)
0xff
```

**Comment by oscardssmith** [comment]
oops. I got screwed up by a slack question.

**Comment by oscardssmith** [comment]
Oops, the error I meant to show was  `parse(Int8, "11111111"; base=2)` which should return `-1` but overflows.

**Comment by Keno** [comment]
> Oops, the error I meant to show was `c` which should return `-1` but overflows.

I don't think that's right either. Parsing from base 2 doesn't mean parsing 2-complement representations, e.g.
```
julia> parse(Int8, "-1111111"; base=2)
-127
```

**Comment by oscardssmith** [comment]
The argument for this is that it's relatively unambiguous, and it allows round-trips with `bitstring`. `parse(T, bitstring(x))` is an identity for positive numbers, and this would make it one for negatives as well.

**Comment by Keno** [comment]
It would break what I would argue is a stronger invariant though, which is that `parse(T, x) == parse(S, x)` for two integer types `S` and `T`. We could have a separate `parsebits(T, x)` function that is bitwidth dependent.
