### ISSUE TITLE
Segfault when compiling Julia if type in method signature not defined

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#39692]
If this function is included somewhere Base (e.g. abstractarray.jl), compilation of Julia fails in the `corecompiler.ji` step.

```
function f1(::TDOESNOTEXIST)
    println("1")
end
```

If you try to define the function at the REPL, Julia will gracefully provide an UndefVarError. An error that points to the problem line would presumably be preferred?

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/39606
