### ISSUE TITLE
Add `permutedims` for Bidiagonal/Tridiagonal/SymTridiagonal

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#39703]
At the moment we have `permutedims` for `Bidiagonal/Tridiagonal/SymTridiagonal` returning a `SparseMatrixCSC`:
```julia
julia> permutedims(SymTridiagonal(1:5, 1:4))
5×5 SparseMatrixCSC{Int64, Int64} with 13 stored entries:
 1  1  ⋅  ⋅  ⋅
 1  2  2  ⋅  ⋅
 ⋅  2  3  3  ⋅
 ⋅  ⋅  3  4  4
 ⋅  ⋅  ⋅  4  5

julia> permutedims(Tridiagonal(2:5, 1:5, 1:4))
5×5 SparseMatrixCSC{Int64, Int64} with 13 stored entries:
 1  2  ⋅  ⋅  ⋅
 1  2  3  ⋅  ⋅
 ⋅  2  3  4  ⋅
 ⋅  ⋅  3  4  5
 ⋅  ⋅  ⋅  4  5

julia> permutedims(Bidiagonal(1:5, 1:4, :U))
5×5 SparseMatrixCSC{Int64, Int64} with 9 stored entries:
 1  ⋅  ⋅  ⋅  ⋅
 1  2  ⋅  ⋅  ⋅
 ⋅  2  3  ⋅  ⋅
 ⋅  ⋅  3  4  ⋅
 ⋅  ⋅  ⋅  4  5
```
I propose the following would be better:
```julia
permutedims(S::SymTridiagonal) = S
permutedims(T::Tridiagonal) = Tridiagonal(T.du, T.d, T.dl)
permutedims(B::Bidiagonal) = Bidiagonal(B.dv, B.ev, B.uplo == 'U' ? 'L' : 'U')
```

I'm not sure if this counts as a  breaking change. If not, I can prepare a PR.

**Comment by dkarrasch** [comment]
Is this meant to be used as a non-recursive transpose?

**Comment by dlfivefifty** [comment]
Yes that’s what ` permutedims ` does

**Comment by dkarrasch** [comment]
IIUC, this saves storage and preserves more structure, so I think everybody who uses that should be grateful. It's hard to imagine someone would specifically rely on the `SparseMatrixCSC` return type. So I'd be in favour of this change.

**Comment by dlfivefifty** [comment]
Yes I agree. Since it's not in Base I believe breaking changes are allowed, anyways.

**Comment by dkarrasch** [comment]
After making LinearAlgebra independent from SparseArrays, these now return dense matrices, so I believe your proposal would be a worthwhile post-optimization.
