### ISSUE TITLE
Add shorthand for single file modules

### ISSUE THREAD

**Issue by savq** [JuliaLang/julia#39718]
As you know, Julia doesn't have a 1 to 1 correspondence between files and modules. However, most programming languages define modules to be files, since both concepts indicate a separation of concerns. Currently, Julia doesn't have a shorthand for this "common case" pattern.

For example, in Rust, another language where modules ≠ files, declaring a module without a body will load the module from an external file with the same name (this is a very common way to declare modules).

I'd like to propose adding a similar way to declare single file modules. In Julia syntax, instead of writing:

```julia
module Foo include("Foo.jl") end
import Foo
```

You would write:

```julia
import module "Foo.jl"
```

Where `Foo.jl` may or may not contain an `export` statement, and becomes available as a module named `Foo` wherever the import happens.

Additionally:

- If the name of the file (without an extension) cannot be parsed into an identifier, the runtime should raise an error. For example, `kebab-case.jl` wouldn't be a valid module name.

- If two `import module` statements refer to the same file, they should also refer to the same module.

- `using module`, and `using module ... as ...` should behave similarly.

This is just an idea. I know there's already _a lot_ of discussion around how modules and imports should behave, but I think that having this shorthand would be very convenient for internal modules within a single package. It would also make it easier to teach Julia to users of other languages, without altering the flexibility that explicit module blocks may provide.

**Comment by kimikage** [comment]
cf: https://github.com/JuliaLang/julia/issues/39235

**Comment by savq** [comment]
Stumbled upon #4600, which seems more relevant. Although some of the good suggestions are kind of buried in the thread. Some others kind of them resemble this one, so I'll close this issue if requested.
