### ISSUE TITLE
Profiling specific threads?

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#39743]
Are there any plans for configuring the `Profile` profiler to only collect profiles for a specific threadid?

It would be nice to e.g. only profile what's happening on threadid 1.

The use case I have in mind is that we're starting an `HTTP.jl` HTTP Server on thread 1, via `HTTP.serve(server=tcp) do http_request ; ... end`, which from what I understand uses `@async` to schedule the provided callback on new Tasks, _on the current thread_. I am interested in profiling the performance and utilization of just that one thread.

Is this something that could be easily supported and added to `Profile`? Or maybe something that could be performed in post-processing of the collected profile data? Do we record a thread id in the traces we collect? (I think we don't, but maybe i'm missing something?)

Thanks! 🙂 ❤️ 📈

**Comment by vchuravy** [comment]
Looking at https://github.com/JuliaLang/julia/blob/0d47bfe79fa1c48d24a4422e6c3917208c87c6b4/src/signals-unix.c#L677-L724 we currently record from which thread the backtrace is coming from.

**Comment by NHDaly** [comment]
Do we? I don't see it in there. :) did you mean to type "we currently _don't_ record"?

But I see that we _could_ record it!

**Comment by NHDaly** [comment]
Thanks for linking me to the right spot to look ❤️

**Comment by NHDaly** [comment]
@vchuravy - per your suggestion, i gave this a shot here:
https://github.com/JuliaLang/julia/compare/master...NHDaly:nhd-profile-threadid_mask

It seems like it should be pretty straightforward, actually, but the code I wrote doesn't seem to affect anything. Even the `exit(1)` i've added in the second commit doesn't have any effect. Is this not the right place to be looking (for macOS)?

https://github.com/JuliaLang/julia/blob/57cab582d753f86de842bda6a1f858ca7c82eed9/src/signals-unix.c#L675

**Comment by vchuravy** [comment]
> did you mean to type "we currently _don't_ record"?

Yes...

>  Is this not the right place to be looking (for macOS)?

Ah yes if you are on that other operating system, that only pretends to be unix.

https://github.com/JuliaLang/julia/blob/0d47bfe79fa1c48d24a4422e6c3917208c87c6b4/src/signals-mach.c#L494-L542

**Comment by NHDaly** [comment]
> > did you mean to type "we currently _don't_ record"?
> 
> Yes...
> 

Haha 🙈 it didn't seem like a likely typo, but i read the code over a few times to be sure 😋 

Cool, thanks again for the second link! 😁

**Comment by NHDaly** [comment]
What does "mach" refer to? I see it all the time, but i have never actually asked.

**Comment by vchuravy** [comment]
> What does "mach" refer to? I see it all the time, but i have never actually asked.

[Mach](https://en.wikipedia.org/wiki/Mach_(kernel)) -> [XNU](https://en.wikipedia.org/wiki/XNU) IIUC Mach is the microkernel basis of XNU which is the kernel for Darwin/MacOS

**Comment by NHDaly** [comment]
Thanks! that explains that for me. :)

------

haha okay, so thanks to your pointers, this was easy enough that i just did it myself:
https://github.com/JuliaLang/julia/pull/39746

😁 Interested to hear what you and @vtjnash have to say! ❤️ night!

**Comment by NHDaly** [comment]
Closed by https://github.com/JuliaLang/julia/pull/41742.
