### ISSUE TITLE
Compact function definition throws unexpected UndefVarError

### ISSUE THREAD

**Issue by szbernat** [JuliaLang/julia#39741]
I was messing around with type parameters and came across this behavior:
`foo(::T)::Bar where {T} = nothing`
throws:
`ERROR: UndefVarError: T not defined`
But:
```
function foo(::T)::Bar where {T}
    nothing
end
```
produces the intended:
`foo (generic function with 1 method)`

If this is the expected behavior then probably a better suited error message should be displayed in the first case.

I am using:
```
julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, skylake)
```

**Comment by Keno** [comment]
Dup of #21847, so I'll close this, but maybe @JeffBezanson has some further thoughts.
