### ISSUE TITLE
`@allocated` and `@time` inconsistant results

### ISSUE THREAD

**Issue by melonedo** [JuliaLang/julia#39757]
MWE
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-DEV.581 (2021-02-19)
 _/ |\__'_|_|_|\__'_|  |  Commit d524f21917 (0 days old master)
|__/                   |

julia> @time Ref(1234)
  0.000000 seconds (1 allocation: 16 bytes)
Base.RefValue{Int64}(1234)

julia> @allocated Ref(1234)
0
```
I suppose this is because `@allocated` uses a `Ref{Int64}` in the top level. In contrast, all other timing macros use `Base.gc_num()` and then `Base.GC_Diff()`.

**Comment by vtjnash** [comment]
It is fine, and entirely consistent, you're just measuring completely different things. I can swap that for you if you like:
```
# first, we make `@time` return 0, like `@allocated`
julia> @time (Ref(1234); 0)
  0.000000 seconds
0

# then we make `@allocated` return the Ref, like `@time`
julia> @allocated x = Ref(1234)
16
```

(though you're also right that the difference in implementation means that `@allocated` can be a little more precise in certain cases, this just doesn't happen to be one of them)

**Comment by melonedo** [comment]
Thanks, I did not notice the difference in return value. I'll close this.
