### ISSUE TITLE
New downloading issues in 1.6-rc1

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#39789]
Multiple users are reporting issues downloading registries with the new Downloads.jl curl approach, for example:

```
(DosingApp) pkg> up
    Updating registry at `~/.julia/registries/General`
^C┌ Error: curl_multi_remove_handle: 1================>   ]  92.3 %
└ @ Downloads.Curl ~/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
```

This is well-tracked upstream at ~~JuliaLang/Downloads.jl#95 and~~ JuliaLang/Downloads.jl#99, but I'm submitting this here to suggest it be a 1.6-blocker.

**Comment by fredrikekre** [comment]
Worked around in https://github.com/JuliaLang/Downloads.jl/pull/96 which is included in https://github.com/JuliaLang/julia/pull/39615 and backported in https://github.com/JuliaLang/julia/pull/39614.

**Comment by KristofferC** [comment]
I don't think so, see: https://github.com/JuliaLang/Downloads.jl/issues/99#issue-809982138

> ested on the latest backports-1.6, so it includes JuliaLang/Downloads.jl#96.

**Comment by fredrikekre** [comment]
Ah okay, https://github.com/JuliaLang/Downloads.jl/issues/95 is worked around though.
