### ISSUE TITLE
Complex arithmetic error in outer product computation

### ISSUE THREAD

**Issue by MxAR** [JuliaLang/julia#39787]
I believe that I have found a bug but I am not sure. The following example gives a quick summary of the issue:
```julia
julia> v = fill(Complex(0, 1), 1)
1-element Array{Complex{Int64},1}:
 0 + 1im

julia> (v*v')[1]
1 + 0im

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1* (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```
The value returned is `1 + 0im` but it should be `-1 + 0im` if my understanding is correct.

**Comment by simeonschaub** [comment]
`'` is equivalent to `adjoint`, which performs complex conjugation. Use `transpose` for a non-conjugate transpose.
