### ISSUE TITLE
Feature request: Syntax highlighting for `methods`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#39782]
In 1.6, stack traces got syntax highlighting in the REPL, but `methods` did not.
Syntax highlighting would help with readability. Presumably the code can be reused.

**Comment by kahanikaar** [comment]
I would like to work on this issue, will be grateful for guidance to approach this. @dpsanders @JeffBezanson

**Comment by JeffBezanson** [comment]
Duplicate of #40913. Closing this one, since that has more discussion.
