### ISSUE TITLE
Inconsistent errors raised by range() function

### ISSUE THREAD

**Issue by Hasnep** [JuliaLang/julia#39798]
I asked a [question on the Julia Zulip](https://juliacommunity.github.io/zulip-archive/stream/274208-helpdesk-(published)/topic/range().20with.20two.20equal.20Int32s.html) about the `range()` function. When the `start` and `stop` arguments are equal the function often raises a `MethodError` like:

```
julia> range(Int32(1), Int32(1); length = 10)
ERROR: MethodError: Cannot `convert` an object of type Tuple{Int32,Int64} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...
```

This does not happen when both input arguments are equal and `Int64`:

```
julia> range(Int64(1), Int64(1); length = 10)
1.0:0.0:1.0
```

It also does not happen with `Float64` or `Float32`:

```
julia> range(Float64(1), Float64(1); length = 10)
1.0:0.0:1.0

julia> range(Float32(1), Float32(1); length = 10)
1.0f0:0.0f0:1.0f0
```

If one of the input arguments is an `Int64`, this error is not raised, except for when the other argument is an `Int128`:

```
julia> range(Int64(1), Int32(1); length = 10)
1.0:0.0:1.0

julia> range(Int64(1), Int8(1); length = 10)
1.0:0.0:1.0

julia> range(Int64(1), Int128(1); length = 10)
ERROR: MethodError: Cannot `convert` an object of type Tuple{Int128,Int64} to an object of type Float64
```

If the `length` argument is set to 1, this error is not raised.

```
julia> range(Int32(1), Int32(1); length = 1)
1.0:0.0:1.0
```

If the `step` argument is used the error is not raised.

```
julia> range(Int32(1), Int32(1); step = 10)
1:10:1
```

If the colon syntax is used this error is not raised.

```
julia> Int64(1):Int64(1)
1:1

julia> Int32(1):Int32(1)
1:1
```

From my quick searching through the Julia source code, there seems to be [an explicit check](https://github.com/JuliaLang/julia/blob/4af2b9f36aa45646f947a4e62e56ade205ee3c18/base/range.jl#L488) for equal `start` and `stop` arguments, so it seems the intended behaviour is to return something instead of raising the error.

<details>
<summary>Version info</summary>

```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "/usr/share/code/code"
  JULIA_NUM_THREADS = 
```

And I get the same result with `julia 1.7-dev`:

```
Julia Version 1.7.0-DEV.582
Commit 3129a5bef5 (2021-02-20 22:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

</details>

**Comment by mkitti** [comment]
Can we add a `bug` label here?

**Comment by mkitti** [comment]
I am concerned that we do not have a milestone or timeline to resolve this bug despite having multiple fixes available.
