### ISSUE TITLE
Segfault in Catlab tests on v1.6.0-rc1 but pass on 1.7.0-DEV.599

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaLang/julia#39804]
When testing 1.6.0-rc1 with the Catlab library, we get a segfault in one test case and an undefined reference error in another (see https://github.com/AlgebraicJulia/Catlab.jl/issues/385). Both tests pass on Julia Version 1.7.0-DEV.599 (2021-02-23)

**Comment by JeffBezanson** [comment]
In either case it looks like something that's supposed to be an object reference is actually a NULL pointer. Possibly involves FunctionWrappers.jl.

**Comment by jpfairbanks** [comment]
Thanks for looking in to it Jeff! Should we investigate this further before 1.6.0 is finalized, or is there way to test whether it has been fixed between 1.6.0-rc1 and 1.6.0? I figured that nightly was the easiest way to get an approximate answer to that question.

**Comment by vtjnash** [comment]
Probably this: https://github.com/JuliaLang/julia/issues/28669 ?
