### ISSUE TITLE
GC failure in Gtk (1.6)

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#39811]
1.6-specific failure described in https://github.com/JuliaGraphics/Gtk.jl/issues/562, which includes a reproducible test case.

`git bisect` identifies #38180.

**Comment by timholy** [comment]
TODO: if #38180 is being kept, https://github.com/JuliaGraphics/Gtk.jl/issues/562#issuecomment-785302898 seems to suggest this is a minor breaking change (for the sake of a bugfix, which is acceptable). But it requires a NEWS entry that summarizes the change and what mitigation strategies need to be pursued in packages. Assigning @vtjnash.

**Comment by JeffBezanson** [comment]
I believe this is fixed by https://github.com/JuliaGraphics/Gtk.jl/pull/569
