### ISSUE TITLE
\in\not vs \notin

### ISSUE THREAD

**Issue by OliverEvans96** [JuliaLang/julia#39814]
Hello,

I've found a discrepancy between two ways to write ∉ at the REPL Julia v1.6.0-beta1 on Arch Linux.

Both are recognized at the `help?>` prompt and suggested to be typed the same way, but only `\notin` has methods - `\in\not` is undefined.

Here's a summary of the differences

Typed | Displayed | Raw bytes (`Vector{UInt8}`) | `help?>` typing hint | Number of methods 
--- | --- | --- | --- | ---
`\notin<tab>` | ∉ | [0xe2, 0x88, 0x89] | `"∉" can be typed by \in<tab>\not<tab>` | 2
`\in<tab>\not<tab>` | ∉ | [0xe2, 0x88, 0x88, 0xcc, 0xb8] | `"∉" can be typed by \in<tab>\not<tab>` | 0

I'm curious whether others observe the same issue on other systems or Julia versions.

Cheers,
Oliver

**Comment by JeffBezanson** [comment]
These are considered different names under the unicode normalization that we use. Is there a normalization form that equates them?

**Comment by mbauman** [comment]
Either way, it looks like our help hint is wrong for `\notin`.  I'm guessing that's how you stumbled across this issue?

**Comment by OliverEvans96** [comment]
Yes, I suppose it was. I didn't know how to type that character, so I pasted it in `help?>` and got bad advice

**Comment by OliverEvans96** [comment]
All of the above also seems to apply to other "not" symbols. e.g.

```julia
help?> ≠ #\ne
"≠" can be typed by =\not<tab>

help?> ≉ #\napprox
"≉" can be typed by \approx<tab>\not<tab>
```

**Comment by clason** [comment]
Hmm, it works here (julia 1.6.0-rc1 as well as 1.7.0-DEV.606, macOS Intel, iTerm2)

**Comment by clason** [comment]
@OliverEvans96 ☝️  

(I forgot that editing doesn't notify people...)

**Comment by OliverEvans96** [comment]
I'm using `gnome-terminal`

**Comment by clason** [comment]
Can you test a different one (kitty, alacritty, pangoterm)?

**Comment by mbauman** [comment]
Hunh, that's odd.  Here's what I see on 1.6.0-rc1 and 1.7.0-DEV.606, macOS/x86/iTerm2:

```julia-repl
help?> ∉ # \notin
"∉" can be typed by \in<tab>\not<tab>

search: ∉

  ∉(item, collection) -> Bool
...
julia> ∉ # \in\not
ERROR: UndefVarError: ∉ not defined
```

On 1.5 the hints match how I wrote it.

**Comment by clason** [comment]
Oh, I also get the `not defined`; I assumed that was intentional. This indicates that these are two different unicode chars (single vs. composite, with not all terminals understanding the latter).

**Comment by mbauman** [comment]
Aha, I bet the hints changed in #36382, where we use **NFD** normalization to look up the latex completion.  Watch out, it's what GitHub apparently uses, too.  Julia source code uses **NFC**.  The former normalizes `\notin` to the combining characters, the latter does not.

```julia
julia> codeunits(REPL.REPLCompletions.latex_symbols["\\notin"])
3-element Base.CodeUnits{UInt8,String}:
 0xe2
 0x88
 0x89

julia> codeunits(Unicode.normalize(String([0xe2, 0x88, 0x89]), :NFC))
3-element Base.CodeUnits{UInt8,String}:
 0xe2
 0x88
 0x89

julia> codeunits(Unicode.normalize(String([0xe2, 0x88, 0x89]), :NFD))
5-element Base.CodeUnits{UInt8,String}:
 0xe2
 0x88
 0x88
 0xcc
 0xb8
```
