### ISSUE TITLE
InexactError inconsistency

### ISSUE THREAD

**Issue by azev77** [JuliaLang/julia#39824]
The following gives an error. (Got no feedback on [discourse](https://discourse.julialang.org/t/inexacterror-in-learnxiny/55967).)
```julia
julia> y1 = [1:3;]
3-element Array{Int64,1}:
 1
 2
 3
julia> y1[3] = y1[3] + 5.0
8.0
julia> y1[3] = y1[3] + 4.99
ERROR: InexactError: Int64(12.99)
Stacktrace:
 [1] Int64 at ./float.jl:710 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] setindex!(::Array{Int64,1}, ::Float64, ::Int64) at ./array.jl:847
 [4] top-level scope at REPL[187]:1
```
The following works
```julia
julia> y1 = [1.0:3.0;]
3-element Array{Float64,1}:
 1.0
 2.0
 3.0
julia> y1[3] = y1[3] + 5.0
8.0
julia> y1[3] = y1[3] + 4.99
12.99
```

**Comment by mbauman** [comment]
This is intended.  Assigning into arrays always tries to convert to the element type, and conversions must be exact.  You need to explicitly choose how you want to `round` your value (up/down/nearest/whatever) to an exact integer value.

**Comment by azev77** [comment]
Sorry, I'm confused. 
Why does this work:
```julia
julia> y1 = [1:3;];
julia> y1[3] = y1[3] + 5.0
8.0
julia> y1
3-element Array{Int64,1}:
 1
 2
 8
```
But this does not:
```julia
julia> y1 = [1:3;];
julia> y1[3] = y1[3] + 4.99
ERROR: InexactError: Int64(7.99)
Stacktrace:
 [1] Int64 at ./float.jl:710 [inlined]
 [2] convert at ./number.jl:7 [inlined]
 [3] setindex!(::Array{Int64,1}, ::Float64, ::Int64) at ./array.jl:847
 [4] top-level scope at REPL[8]:1
```

In both cases we are adding a float to an array of Int. 
In the first case it remains an Int, in the second case I get an error. 

I'm guessing it's bc it auto converts `5.0` to `Int(5.0)`. 
Whereas `Int(4.99)` gives `ERROR: InexactError: Int64(4.99)`. 
If so the error message & docs are not helpful here. 
Maybe an error message w/ a simple example like: 
```julia
ERROR: InexactError: Int64(4.99) cannot be converted to type Int64. 
Int64(17.0) converts from 17.0 (type Float64) to 17 (type Int64)
```
