### ISSUE TITLE
Build failure due to MINSIGSTKSZ with glibc 2.33

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#39822]
glibc 2.33 deprecated the `MINSIGSTKSZ` constant in favor of `sysconf (_SC_MINSIGSTKSZ)`:
https://sourceware.org/git/?p=glibc.git;a=commit;h=6c57d320484988e87e446e2e60ce42816bf51d53

This makes the build fail on Fedora Rawhide due to these lines (both on 1.6.0-rc1 and master):
https://github.com/JuliaLang/julia/blob/a12d0ff63a187ca165f9eb50c00c0b127734ca6b/src/task.c#L67-L73

```
make -j2
[...]
    CC src/task.o
In file included from /usr/include/signal.h:315,
                 from /home/fedora/nalimilan/julia/src/task.c:31:
/home/fedora/nalimilan/julia/src/task.c:69:29: error: missing binary operator before token "("
   69 | #if defined(MINSIGSTKSZ) && MINSIGSTKSZ > 131072
      |                             ^~~~~~~~~~~
```

FWIW, this only happens with `-D_GNU_SOURCE`, but AFAICT Julia needs it.

(See also https://bugzilla.redhat.com/show_bug.cgi?id=1928696.)

Cc: @vtjnash who touched these lines last.

**Comment by tpapp** [comment]
I am getting this error on Ubuntu 21.10, is there a workaround?

**Comment by tpapp** [comment]
I think that #41860 fixes this but it wasn't backported into `release-1.7`, which I was trying to compile.

**Comment by nalimilan** [comment]
Cool. https://github.com/JuliaLang/julia/issues/39822 has been marked for backport, so closing.
