### ISSUE TITLE
Worlds test can fail

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#39828]
Seen locally:
```
worlds                            (11) |         failed at 2021-02-25T16:43:08.239
Error During Test at /Users/julia/julia-master/test/testdefs.jl:21
  Got exception outside of a @test
  LoadError: MethodError: no method matching worlds(::Nothing)
  Closest candidates are:
    worlds(!Matched::Core.MethodInstance) at /Users/julia/julia-master/test/worlds.jl:240
  Stacktrace:
   [1] top-level scope
     @ ~/julia-master/test/worlds.jl:317
  in expression starting at /Users/julia/julia-master/test/worlds.jl:317
```
This test relies on a specialization existing for `+(::AbstractChar, ::UInt8)`, which seems like a bit of a random thing to ask for and it appears that in this particular run it didn't. I noticed that the original test had a call to `Printf.gen`, which I guess was supposed to force that specialization to exist. However, that was removed by @quinnj  in https://github.com/JuliaLang/julia/commit/31d72108acd8f5145389d6c15bc81741cb4acc07#diff-04a7474effdd5d726f96ff8ea1287744ee7258d4543d89571c76f3f5074c8bdc. Perhaps this should just literally use `Core.Compiler.specialize_method`?

**Comment by timholy** [comment]
The method must have been invalidated since it's there in a fresh session:
```julia
$ ./julia --startup-file=no -q
julia> m = which(+, (Char, UInt8))
+(x::T, y::Integer) where T<:AbstractChar in Base at char.jl:235

julia> m.specializations
svec(MethodInstance for +(::Char, ::Int64), MethodInstance for +(::Char, ::UInt8), MethodInstance for +(::AbstractChar, ::UInt8), #undef, #undef, #undef, #undef, #undef)
```
That's a bit interesting in and of itself. At any rate, it's an excellent suggested fix, see #39830.
