### ISSUE TITLE
Bug in @testset?

### ISSUE THREAD

**Issue by mzgubic** [JuliaLang/julia#39835]
Consider:
```
julia> @testset "is this expected" begin
           @test 1 == 1
           y = return 1 # or return 1
           @test 1 == 2
       end
Test Summary:    | Pass  Total
is this expected |    1      1
1
```
whereas
```
julia> @test 1 == 1
Test Passed

julia> y = return 1
1

julia> @test 1 == 2
Test Failed at REPL[110]:1
  Expression: 1 == 2
   Evaluated: 1 == 2
ERROR: There was an error during testing
```

Is this expected behaviour? I guess returning from `@testset` is unexpected itself?

**Comment by giordano** [comment]
Returning outside of a function doesn't make much sense, see #30499

**Comment by mzgubic** [comment]
Yeah, that's fair enough. I encountered this when writing a macro and used `return result` instead of `result` as the last line in the quoted block. Was kind of hard to debug and I still haven't figured out a way to test it

**Comment by simeonschaub** [comment]
`@testset` wraps the body in a `let` block, so this difference to toplevel expressions is expected.
