### ISSUE TITLE
ccall execution results in segmentation fault

### ISSUE THREAD

**Issue by narger-ef** [JuliaLang/julia#39844]
Hello everyone, I've got a serious problem with ccall.

I'm trying to update an existent package ([SEAL.jl](https://github.com/JuliaCrypto/SEAL.jl)), that wraps Microsoft SEAL ([Microsoft SEAL](https://github.com/microsoft/SEAL)), a C++ library.

The new SEAL version (3.6) changed some APIs, therefore I had to change some ccall.

The particular API that changed is essentially:

`PublicKey &public_key() `

to

`inline void create_public_key(PublicKey &destination)`

This is a part of _keygenerator.h_ :

```
...

inline void create_public_key(PublicKey &destination) const
        {
            destination = generate_pk(false);
        }


SEAL_NODISCARD inline Serializable<PublicKey> create_public_key() const
        {
            return generate_pk(true);
        }

...
```

Whenever I try to call the first of the two methods (the one that takes _destination_ argument) in _keygenerator.jl_, like this:

```
function create_public_key!(destination::PublicKey, keygen::KeyGenerator)
    ccall((:KeyGenerator_CreatePublicKey, libsealc), Clong,
                 (Ptr{Cvoid}, Ptr{Cvoid}),
                 keygen, destination)
    return destination
end
```

Julia crashes, giving me a segmentation fault.

I think that he's trying to call the wrong method, even in the dylib file there is only one "T _KeyGenerator_CreatePublicKey" even if there is an overload (but this could be normal I guess)

To reproduce it: 

Just run 'add SEAL' in pkg mode, 

then in SEAL.jl change:
```
include("keygenerator.jl")
export KeyGenerator, public_key, secret_key, relin_keys_local, relin_keys, galois_keys_local
```

to: 

```
include("keygenerator.jl")
export KeyGenerator, create_public_key!, secret_key, relin_keys_local, relin_keys, galois_keys_local
```
and substitute the old function public_key() in _keygenerator.jl_ with the one that I wrote before

Then run this basic commands:
```
using SEAL

parms = EncryptionParameters(SchemeType.bfv)

poly_modulus_degree = 4096

set_poly_modulus_degree!(parms, poly_modulus_degree)

set_coeff_modulus!(parms, coeff_modulus_bfv_default(poly_modulus_degree))

set_plain_modulus!(parms, 1024)

context = SEALContext(parms)

keygen = KeyGenerator(context) 

public_key_ = PublicKey() 

create_public_key!(public_key_, keygen)   # CRASH!
```

My Julia instance:
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: AMD Ryzen 5 3600 6-Core Processor              
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 1

I hope it was clear enough,
Thank you!

**Comment by vtjnash** [comment]
This method seems to have a different list of arguments that you are accounting for
https://github.com/microsoft/SEAL/blob/5c586e2480dc0a43fb76a23a3dcc3daecb3764e8/native/src/seal/c/keygenerator.h#L32

**Comment by narger-ef** [comment]
Oh that's the issue! I was looking at the C++ source and not the original C.

Thank you so much, I think that it would be cool for Julia to catch this kind of errors, if possible, and report them (even though I admit that it was my mistake)
