### ISSUE TITLE
Confusion about time_ns macro docs 

### ISSUE THREAD

**Issue by jtrakk** [JuliaLang/julia#39853]
The [hygiene](https://docs.julialang.org/en/v1/manual/metaprogramming/#Hygiene) docs say 

> Here, we want t0, t1, and val to be private temporary variables, and we want `time` to refer to the `time` function in Julia Base, not to any `time` variable the user might have (the same applies to println).

But the code snippet doesn't actually use a `time` function -- it uses `time_ns`, which makes the section confusing.

**Comment by Heisenberg403** [comment]
Hi, I would like to work on this issue.

**Comment by Pramodh-G** [comment]
Hi! @KristofferC,  I think you could close this issue, it's been fixed. Hopefully it doesn't lure in anymore first time contributors :stuck_out_tongue: . Thanks for all the work you do!

**Comment by musm** [comment]
Closed as this is already fixed on master

**Comment by musm** [comment]
Thanks @Pramodh-G for checking
