### ISSUE TITLE
Indexing an Array with a single AbstractUnitRange might use contiguity of elements to run faster

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#39858]
Currently there is a fast `getindex` method defined for `(::Array)[::UnitRange{Int}]` that assumes a contiguous layout of elements. Something similar should also be possible for `Base.OneTo{Int}` (and perhaps with other `AbstractUnitRange{Int}` in general).

Currently:

```julia
julia> a = ones(20000);

julia> ax = axes(a,1)
Base.OneTo(20000)

julia> @btime $a[$ax];
  24.166 μs (2 allocations: 156.33 KiB)

julia> @btime $a[UnitRange($ax)];
  17.697 μs (2 allocations: 156.33 KiB)
```

The first operation is effectively equivalent to the second, and its performance should be comparable. However, `a[ax]` ends up calling 

```
julia> @which a[ax]
getindex(A::Array{S, N} where N, I::AbstractRange{Int64}) where S in Base at array.jl:826
```

which is 

https://github.com/JuliaLang/julia/blob/c79309bffa2842f7864d06fc2b135e79da1daec1/base/array.jl#L825-L828

This is presumably slower.

**Comment by kahanikaar** [comment]
I would like to contribute to this issue, will be grateful for guidance to approach this. @sostock @jishnub

**Comment by jishnub** [comment]
A simple solution might be adding a method to convert an `AbstractUnitRange{Int}` to an `UnitRange{Int}` in the indexing operation, although I'm not sure if that's safe or performant in general.

```julia
julia> Base.getindex(A::Array, I::AbstractUnitRange{Int}) = getindex(A, UnitRange{Int}(I))

julia> @btime $a[$ax];
  18.858 μs (2 allocations: 156.33 KiB)

julia> @btime $a[$(UnitRange(ax))];
  17.671 μs (2 allocations: 156.33 KiB)
```

Perhaps someone with a better knowledge about the internals and the variety of `AbstractUnitRange`s might be able to suggest the best approach

**Comment by sostock** [comment]
I would just relax the signature of the `getindex(A::Array, I::UnitRange{Int})` method, changing the second argument to `AbstractUnitRange{Int}` or even `AbstractUnitRange{<:Integer}`. That should be enough (it might lead to new method ambiguities which would have to be fixed, but otherwise I don’t see how it could go wrong).

**Comment by jishnub** [comment]
> I would like to contribute to this issue, will be grateful for guidance to approach this. @sostock @jishnub 

Mind making a PR? You could start with the suggestion here to relax the type signature in the method

**Comment by kahanikaar** [comment]
Relaxed the method signature. Draft PR created. Do review. @jishnub @sostock
