### ISSUE TITLE
libopenblas: illegal instruction on master

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#39865]
On my computer, the `LinearAlgebra` tests fail on master due to illegal instructions in openblas:
```
Test         (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/lq  (1) |        started at 2021-03-01T12:34:19.198
Invalid instruction at 0x7f5b03e90e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8

signal (4): Illegal instruction
in expression starting at /home/sebastian/Development/julia/usr/share/julia/stdlib/v1.7/LinearAlgebra/test/lq.jl:20
zgemm_kernel_n_SANDYBRIDGE at /home/sebastian/Development/julia/usr/bin/../lib/libopenblas64_.so (unknown line)
Allocations: 122985676 (Pool: 122813719; Big: 171957); GC: 204
```
```
Julia Version 1.7.0-DEV.627
Commit e784dd010a (2021-02-28 18:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)
```

**Comment by nalimilan** [comment]
Cc: @ViralBShah

**Comment by ViralBShah** [comment]
@staticfloat Might this be LBT related?

**Comment by staticfloat** [comment]
@sostock Are you running inside of any kind of virtualization environment, or do you somehow have AVX turned off in the BIOS or something like that?  I see that your CPU is listed as `Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz`, which according to [this table](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) should support AVX, and the instruction it's dying on (`66 c5 f0 57 c9`) is a valid AVX `vxorpd` instruction:

```
$ objdump --disassemble=zgemm_kernel_n_SANDYBRIDGE libopenblas64_.so
...
  9a2e96:       49 83 ec c0             sub    $0xffffffffffffffc0,%r12
  9a2e9a:       4c 89 c6                mov    %r8,%rsi         
  9a2e9d:       66 c5 f0 57 c9          vxorpd %xmm1,%xmm1,%xmm1
  9a2ea2:       c5 e8 57 d2             vxorps %xmm2,%xmm2,%xmm2
  9a2ea6:       c5 e0 57 db             vxorps %xmm3,%xmm3,%xmm3
  9a2eaa:       c5 d8 57 e4             vxorps %xmm4,%xmm4,%xmm4
  9a2eae:       c4 41 38 57 c0          vxorps %xmm8,%xmm8,%xmm8
  9a2eb3:       0f 18 4b 08             prefetcht0 0x8(%rbx)
...
```

According to [this reference page](https://www.felixcloutier.com/x86/xorpd) this form of `vxorpd` should be valid on AVX so I don't think this is an OpenBLAS miscompile, it seems more like your CPU is advertising the ability to run AVX instructions, but then SIGILL'ing when it encounters them.

If you can't figure out why your CPU is doing this, you may be able to work around this by defining `OPENBLAS_CORETYPE=NEHALEM` to force OpenBLAS to jump back a generation and not use AVX instructions (here's [the full list](https://github.com/xianyi/OpenBLAS/blob/e34d57ca90626db3268b66e5f984e1fb3b132888/TargetList.txt#L20-L21) of valid core types), but (a) you'll get worse performance than you otherwise would and (b) there are other pieces of software that try to use `cpuid` (such as Julia itself!) that won't listen to the environment variable.

**Comment by sostock** [comment]
I can’t figure out why my CPU behaves this way. Maybe something’s just broken. Thanks for investigating, I’m closing this for now.

**Comment by ViralBShah** [comment]
Out of curiosity, can you try with `using MKL` and seeing if that does any better? That should be sufficient to replace openblas with MKL on current master.

**Comment by sostock** [comment]
It works with MKL.

**Comment by maleadt** [comment]
I'm running into this on GPU CI:

```
Julia Version 1.7.0-DEV.1108
Commit b1a4129338 (2021-05-16 22:39 UTC)
Platform Info:
OS: Linux (x86_64-pc-linux-gnu)
CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-11.0.1 (ORCJIT, ivybridge)
```

```
      From worker 4:	Invalid instruction at 0x7f40ab1f0e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8
      From worker 4:
      From worker 4:	signal (4): Illegal instruction
      From worker 4:	in expression starting at /var/lib/buildkite-agent/builds/gtx1080-hydor-elis-ugent-be/julialang/cuda-dot-jl/test/cublas.jl:83
      From worker 4:	zgemm_kernel_n_SANDYBRIDGE at /root/.cache/julia-buildkite-plugin/julia_installs/bin/linux/x64/julia-latest-linux64/bin/../lib/julia/libopenblas64_.so (unknown line)
      From worker 4:	Allocations: 543552700 (Pool: 543187700; Big: 365000); GC: 469
Worker 4 terminated.
```

Also happened in `ztrmm_kernel_LC_SANDYBRIDGE`, `zgemm_kernel_r_SANDYBRIDGE`, `zgemm_kernel_l_SANDYBRIDGE`, listing the same instruction bytes. I haven't been able to reproduce though, so I'm not sure whether this was a strange transient error, or whether this has anything to do with last month's OpenLibm artifact updates (I only recently re-enabled GPU CI for 1.7).

Those bytes can be disassembled as:

```
0:  66 c5 f0 57 c9          vxorpd xmm1,xmm1,xmm1
5:  c5 e8 57 d2             vxorps xmm2,xmm2,xmm2
9:  c5 e0 57 db             vxorps xmm3,xmm3,xmm3
d:  c5                      .byte 0xc5
e:  d8                      .byte 0xd8 
```

... which seem like AVX instructions that this E5-2637 v2 (ivy bridge) should support...

GPU CI runs in Docker, but I can't imagine how that would matter here.

Finally, `cpuinfo`:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz
stepping        : 4
microcode       : 0x42e
cpu MHz         : 3614.209
cache size      : 15360 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 7025.75
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by ViralBShah** [comment]
Presumably we need an openblas patch.

**Comment by staticfloat** [comment]
This is really strange; the CPU should be fine running these instructions.  I think we need a reliable reproducer before we can do anything about this.

**Comment by maleadt** [comment]
The reproducer is as simple as `rand(ComplexF64, 4, 4) * rand(ComplexF64, 4, 4)`:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.59 (2021-06-20)
 _/ |\__'_|_|_|\__'_|  |  Commit df1150c3ea (0 days old master)
|__/                   |

julia> versioninfo(verbose=true)
Julia Version 1.8.0-DEV.59
Commit df1150c3ea (2021-06-20 18:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Debian GNU/Linux 10 (buster)
  uname: Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 unknown
  CPU: Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz: 
                 speed         user         nice          sys         idle          irq
       #1-16  1466 MHz   17795436 s      82863 s     783297 s  149461842 s          0 s
       
  Memory: 62.86309814453125 GB (27212.03515625 MB free)
  Uptime: 1.053132e6 sec
  Load Avg:  1.18  1.49  2.57
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, ivybridge)
Environment:
  JULIA_VERSION = nightly
  HOME = /home/tbesard
  TERM = xterm-256color
  CUDA_HOME = /opt/cuda
  PATH = /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
```
julia> rand(ComplexF64, 4, 4) * rand(ComplexF64, 4, 4)
Invalid instruction at 0x7f44e4d37e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8

signal (4): Illegal instruction
in expression starting at REPL[2]:1
zgemm_kernel_n_SANDYBRIDGE at /home/tbesard/.cache/jl/installs/bin/linux/x64/julia-latest-linux64/bin/../lib/julia/libopenblas64_.so (unknown line)
Allocations: 6812473 (Pool: 6808585; Big: 3888); GC: 9
zsh: illegal hardware instruction
```

**Comment by ViralBShah** [comment]
Is this running in some kind of virtualization? Should we be filing something upstream if we have a reproducer on another system?

**Comment by maleadt** [comment]
No, this is running natively on a 64-bit Debian Buster.

**Comment by giordano** [comment]
It may be worth trying to reproduce in OpenBLAS directly, to rule out/confirm an upstream bug?  The fact that it can't be reproduced with MKL may be relevant.

**Comment by maleadt** [comment]
FWIW, the BLAS-level library function that fails is `LinearAlgebra.BLAS.gemm!('N', 'N', true, rand(ComplexF64,4,4), rand(ComplexF64,4,4), false, rand(ComplexF64,4,4))`.

**Comment by yuyichao** [comment]
So is this in a docker or not? (though I don't feel like it should affect things too much...)

What do you get from `jl_dump_host_cpu()`. Is `avx` in there?

And what if you just run a simple C program/function with that instruction? You can get it fairly trivially with

```c++
double f(void)
{
    return 0;
}
```

With optimization and `-mavx` on.

**Comment by maleadt** [comment]
> So is this in a docker or not? (though I don't feel like it should affect things too much...)

Nope, just natively.



> What do you get from `jl_dump_host_cpu()`. Is `avx` in there?

Yes:

```
julia> ccall(:jl_dump_host_cpu, Cvoid, ());
CPU: ivybridge
Features: sse3, pclmul, ssse3, cx16, sse4.1, sse4.2, popcnt, aes, xsave, avx, f16c, rdrnd, fsgsbase, sahf, xsaveopt

# just to confirm

julia> LinearAlgebra.BLAS.gemm!('N', 'N', true, rand(ComplexF64,4,4), rand(ComplexF64,4,4), false, rand(ComplexF64,4,4))
Invalid instruction at 0x7f5d02fa3e9d: 0x66, 0xc5, 0xf0, 0x57, 0xc9, 0xc5, 0xe8, 0x57, 0xd2, 0xc5, 0xe0, 0x57, 0xdb, 0xc5, 0xd8

signal (4): Illegal instruction
in expression starting at REPL[5]:1
zgemm_kernel_n_SANDYBRIDGE at /home/tbesard/.cache/jl/installs/bin/linux/x64/1.7/julia-latest-linux64/bin/../lib/julia/libopenblas64_.so (unknown line)
Allocations: 695326 (Pool: 695059; Big: 267); GC: 1
```



> And what if you just run a simple C program/function with that instruction?

That works:

```
$ gcc -O2 -mavx -shared -fPIC -o /tmp/libtest.so /tmp/test.c

$ julia

julia> using Libdl

julia> lib = Libdl.dlopen("/tmp/libtest.so")

julia> fun = Libdl.dlsym(lib, "f")

julia> ccall(fun, Cdouble, ())
0.0
```

That instruction is there:

```
$ objdump -d /tmp/libtest.so

0000000000001100 <f>:
    1100:       c5 f9 57 c0             vxorpd %xmm0,%xmm0,%xmm0
    1104:       c3                      retq   
```

Although encoded differently (xmm0 vs of xmm1).

**Comment by yuyichao** [comment]
What did you use for disassembling the illegal instruction?

`objdump` (2.36.1) disassembles it as

```
    1024:       66 c5 f0 57 c9          data16 vxorps %xmm1,%xmm1,%xmm1
```

which seems like an illegal instruction and indeed it also fail on my computer.

OTOH, `llvm-mc` does disassemble it without complaining.

What's the disassemble of the whole function? `zgemm_kernel_n_SANDYBRIDGE`?

**Comment by maleadt** [comment]
> What did you use for disassembling the illegal instruction?

```
objdump --version                                                                                                                                                                           
GNU objdump (GNU Binutils for Debian) 2.31.1
```

The same file, on my Arch's 2.36.1 objdump, disassembles it as you see.



> What's the disassemble of the whole function? `zgemm_kernel_n_SANDYBRIDGE`?

https://gist.github.com/maleadt/3663461e8232c1db6695f71c41804525



> Also, what's the source file corresponding to that function?

All frames point to `/buildworker/worker/package_linux64/build/cli/loader_exe.c`; this is an official build from the buildbots.

**Comment by yuyichao** [comment]
> All frames point to /buildworker/worker/package_linux64/build/cli/loader_exe.c; this is an official build from the buildbots.

The `list *$pc` when you are in that function should not point to the loader.

**Comment by yuyichao** [comment]
It just seems like using the wrong encoding for the instruction. (Never really understand all the prefixes in the x86 encoding but) it seems that `0x66` prefix is used to turn `xorps` into `xorpd` whereas the `VEX` version encodes that differently.

The question is of course who emits that encoding and that's why I don't understand why your assembly code looks exactly like mine (which is the same as the assembly source) but has all the SSE instructions replaced with AVX ones. What are the compile versions/options/other tools used?

**Comment by yuyichao** [comment]
I suspect this is https://github.com/xianyi/OpenBLAS/issues/3226

**Comment by ViralBShah** [comment]
We could backport https://github.com/xianyi/OpenBLAS/pull/3228 (which is the fix to https://github.com/xianyi/OpenBLAS/issues/3226) to our openblas build - if we can verify it is the right fix.

**Comment by ViralBShah** [comment]
Is it possible to fix by using a newer GCC?

**Comment by yuyichao** [comment]
It should. I have not been able to reproduce the invalid instruction but I have only observed GCC "upgrading" the instruction (which IMHO isn't super valid) on older GCC versions (7.2.0 and not on 11.*). I think backporting is safer though.
