### ISSUE TITLE
associating data with functions, modules, and globals

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#3988]
There are a number of issues discussing documentation for Julia code (#762, #1619, #3407), but I'd like to separate this problem into two very distinct issues:

1. Associating text from source files – both comments and source code – with functions, methods, modules, and global bindings.
2. Interpreting and presenting this data to the world.

We keep getting bogged down in the combination of these two issues, but they can be tackled separately, and should, imo, remain decoupled – that is, the infrastructure for (1) should be reusable with different approaches to interpreting comments and different mechanisms for presenting documentation (help, sphinx, dexy, jocco, etc.).

This issue is for discussion of (1):

- What we want to be able to associate with run-time objects like functions, methods, modules, and global bindings? It would be nice to have easy, queryable access to source code for things as well as inline comments associated with that source code.
- How to associate that data with run-time objects? While it may be reasonable to have this kind of overhead in interactive situations, we also must be able to run programs non-interactively without paying that price.

Let's solve this first and *then* figure out how to interpret and present things.

**Comment by mauro3** [comment]
close this

**Comment by pao** [comment]
@ViralBShah looks like you performed a drive-by tag removal, but you didn't close--what is the remaining work here?
