### ISSUE TITLE
Precompile bug

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#39907]
Today FileIO and Revise stopped building due to some changes in the behavior of precompile directives. For Revise, I thought I had commented the problematic lines in https://github.com/timholy/Revise.jl/pull/612, thinking that it didn't happen on Linux (and indeed the Ubuntu workers for GitHub Actions passed), but then a user reported that it happens even on Fedora: https://github.com/timholy/Revise.jl/issues/613. Moreover, others have seen this in other repos, e.g., FileIO: https://github.com/tlnagy/TiffImages.jl/pull/35#issuecomment-789625207

Since I'm on Ubuntu I can't replicate this easily but a guess at a MWE might be something like this:

```julia
julia> foo(x; kwargs...) = x
foo (generic function with 1 method)

julia> m = @which foo(1)
foo(x; kwargs...) in Main at REPL[2]:1

julia> fbody = Base.bodyfunction(m)
#foo#5 (generic function with 1 method)

julia> methods(fbody)
# 1 method for generic function "#foo#5":
[1] var"#foo#5"(kwargs, ::typeof(foo), x) in Main at REPL[2]:1

julia> using MethodAnalysis

julia> foo(1)
1

julia> methodinstances(fbody)
1-element Vector{Core.MethodInstance}:
 MethodInstance for var"#foo#5"(::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, ::typeof(foo), ::Int64)

julia> precompile(fbody, (Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(foo), Int64) )
true
```
I'm guessing that returns `false` for some people.

EDIT: actually this has nothing to do with the platform, other than the fact that the nightlies came out at different times.

**Comment by simeonschaub** [comment]
Ref https://github.com/JuliaLang/julia/commit/c0f9666d0b94b213c7ff9e64a7b4e5268aa0e18b#commitcomment-47798892

**Comment by vtjnash** [comment]
Closed by https://github.com/JuliaLang/julia/pull/39905
