### ISSUE TITLE
Pairs could just be 2 length tuples?

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#39911]
I sometimes wonder too how useful having a pair type really is...it's really not that much different from a two length tuple. So maybe

`"a" => 1` going to `("a", 1)` could be good idea?

I can see the following advantages:

- It could remove the need for `Pair` as a separate type
- With some clever aliasing and `getproperty` overloading, I think it could be done in a mostly backwards compatible way

I can see the following disadvantages:

- One of the nice things about `Pair` is the syntax (less parentheses). We could certainly keep `=>` as a syntax for writing two length tuples, but printing two length tuples with `=>`, on the other hand, is maybe too much of a special case?

**Comment by bramtayl** [comment]
@KristofferC better?

**Comment by Keno** [comment]
The primary advantage of Pair is that isn't not covariant in its type parameters, so it can carry type information that's not in the fields themselves.

**Comment by bramtayl** [comment]
Right, but I'm not sure how that would be useful in practice? Or it is, maybe it would be better to focus on making tuples covariant?

**Comment by JeffBezanson** [comment]
We introduced `Pair` to disambiguate the idea of a single key-value element from a 2-element collection. For example is `((1,2), (3,4))` two mappings `1=>2, 3=>4`, or the mapping `(1,2) => (3,4)`?

**Comment by bramtayl** [comment]
Oh I'd never thought about that!

> two mappings `1=>2, 3=>4`

>  mapping `(1,2) => (3,4)`

Those seem like... kind of the same thing? I suppose there must have been a use-case for distinguishing them at some point, but I can't think of one.
