### ISSUE TITLE
Different NamedTuple internals proposal

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#39910]
I think it might be a good idea if we revised the NamedTuple internals to be something like this:

`(; a = 1, b = 2)` goes to `(name"a" => 1, name"b" => 2)`, where the name string macro would pull the symbol into the type domain. I can see the following advantages

- It would allow mixing unnamed and named entries in the same tuple
- It would allow for much easier programmatic construction of named tuples
- It would unify the tuple and the NamedTuple internals
- It would remove the need for generated functions in the NamedTuple code (these kind of types are much easier to handle with recursion)

I can see the following disadvantages:

- NamedTuple construction automatically checks for duplicate keys, but this syntax would allow duplicate keys, perhaps only throwing an error when `getproperty` is called (although just returning the first match could also be a valid option)

**Comment by bramtayl** [comment]
@KristofferC better?

**Comment by bramtayl** [comment]
I'm seeing some confused faces...let me know if there's something I can clarify

**Comment by quinnj** [comment]
At least for me, it's unclear what 

> where the name string macro would pull the symbol into the type domain

mean. Your syntax seems to suggest NamedTuples would become `NamedTuple{Pair{Name{:a}, Int}, Pair{Name{:b}, Int}}`? But it's also unclear what an "unnamed entry" would be.

**Comment by mbauman** [comment]
I don't understand how a syntax change would change any of the internals.  How does this allow for a mixed tuple with some positional elements and some named elements?  How would this unify NamedTuple and Tuple internals?  How would it change how you handle named tuples at all?  Why are any of these things advantageous?

For the other listed advantage, how is this different from the existing `(; :a => 1, :b => 2)`?  That's _already_ type stable through constant propagation.

```Julia
julia> f(x) = (; x => 1, :b => 2)
f (generic function with 3 methods)

julia> g() = f(:a)
g (generic function with 1 method)

julia> @code_warntype g()
Variables
  #self#::Core.Compiler.Const(g, false)

Body::NamedTuple{(:a, :b),Tuple{Int64,Int64}}
1 ─ %1 = Main.f(:a)::Core.Compiler.Const((a = 1, b = 2), false)
└──      return %1
```

**Comment by JeffBezanson** [comment]
> * It would allow mixing unnamed and named entries in the same tuple

This looks like the primary feature being proposed here? Would be interesting to see an example use case. If it's really useful I think we could add this to the current design by e.g. allowing both numbers (or `nothing` or some other sentinel) and symbols in the NamedTuple names parameter.

NamedTuple and Tuple internals are already fairly unified --- they're both just structs with fields. One point of confusion here is that you mention "internals" but I only see a proposed syntax. quinnj's above question is a good one: what would the type and its representation be in this proposal? Is the idea to make `NamedTuple` a subtype of `Tuple`?

**Comment by bramtayl** [comment]
@quinnj

> Your syntax seems to suggest NamedTuples would become `NamedTuple{Pair{Name{:a}, Int}, Pair{Name{:b}, Int}}`? But it's also unclear what an "unnamed entry" would be.

That's pretty close to what I was thinking. I was thinking more

`Tuple{Pair{Name{:a}, Int}, Pair{Name{:b}, Int}}`

and adding an unnamed entry:

`Tuple{Pair{Name{:a}, Int}, Pair{Name{:b}, Int}, Int}`

So NamedTuples would be essentially tuples that just happen to have named pairs in them.

I'm hoping that the above might help answer some @mbauman and @JeffBezanson 's questions too? If not, I can try to reword. For the rest:

> Why are any of these things advantageous?

In order of the four points I listed above, I see the advantages as:

- Hmm, to be fair, maybe this one isn't that useful. But it's certainly something that you cannot currently do.
- Programmatic construction of named tuples can be helpful, for example, when you're doing surgery on rows of tables
- Mostly just code reduction and Occam's razor
- Isn't there something about generated functions causing problems for precompilation? Not 100% sure about this.

> For the other listed advantage, how is this different from the existing `(; :a => 1, :b => 2)`? That's already type stable through constant propagation.

Yes, definitely that is almost good enough. The issue with `(; :a => 1, :b => 2)`, I think, is that it will set off recursion detection and disable constant propagation, because repeated elements have the same type.

**Comment by bramtayl** [comment]
Oh also, one advantage of being able to mix unnamed and named arguments as part of the same tuple is that arguments and keywords could potentially be merged into the same tuple. That would potentially allow things like e.g. dispatching on keyword arguments. I'm actually not sure that would be the best idea, though; there's something nice about keyword arguments not being involved in dispatch.

**Comment by JeffBezanson** [comment]
> So NamedTuples would be essentially tuples that just happen to have named pairs in them.

I think that is a deal breaker --- it means every consumer of tuples has to look at every element to see if it's named or not. Part of the point of a NamedTuple is to be able to add names on top of a tuple without otherwise changing how it works.

But, `getproperty(::Tuple, ::Symbol)` is currently not defined, so it's certainly possible to define that to search for a pair with the given name.

If there are missing cases of programmatic construction of named tuples, or compiler issues, we should dig into them and see if they can be fixed.

**Comment by bramtayl** [comment]
> it means every consumer of tuples has to look at every element to see if it's named or not.

Yes, I suppose that's true. Part and parcel of the added flexibility.

> missing cases of programmatic construction of named tuples

Hmm, just as an example, subset a `NamedTuple` by selecting the first, third, and fourth items, keeping the names?

> compiler issues

Maybe I'll open a separate issue about recursion disabling constant propagation then? It's a super annoying problem, and almost as annoying to try to explain.

**Comment by bramtayl** [comment]
Ref #39915

**Comment by bramtayl** [comment]
If #39918 goes through, using plain symbols as names could potentially be feasible (but maybe still a bit brittle).

> every consumer of tuples has to look at every element to see if it's named or not

I think there's a pretty simple way to work around this: just have an `unname` function which will extract the item out of a named pair if it exists, but default to identity for regular items. Then, code already written for tuples will continue to work as long as named pairs aren't passed to it, and if you want to iterate tuples and named tuples interchangeably, just use `unname`

**Comment by JeffreySarnoff** [comment]
This proposal is vaguely reminiscent of the desire to provide a new level of discernment to floating point processing with NaNs.
754 went overboard.  To provide this advancement entails derezzing (de-resolution-ing) the simplicity with which a NamedTuple type can be modified selectively -- because half of those selections occur through the medium of the field's names.  And all of the goes-really-fast therewith is predicated upon this:  istepping through the field names steps over, on, or in each of the fields.

**Comment by bramtayl** [comment]
Hmm, well, ideally, that would all happen just once at compile time, so that at run time there wouldn't be any iterating at all for selecting just one field

**Comment by JeffreySarnoff** [comment]
Subsetting may, and often does, select for multiple fields. There are both inclusive (of all the fields, use these) and exclusive (use all except these) modalities.  Compile time is not limited to one time for some of the manners of programming I spend time (today) facilitating for others ease of use (tomorrow).  Dynamic selection for multiple fields aor constructive application of multifield sets become practical only if the specifics are readily grasped and virtually transparent in their performance.

**Comment by JeffreySarnoff** [comment]
otoh, if you are offering a perfect world ... which one is it?

**Comment by bramtayl** [comment]
Maybe we could have a `split` function which will split a named tuple into this kind of design, and `NamedTuple` to pull it back together again?

**Comment by bramtayl** [comment]
> Maybe we could have a nest function which will split a named tuple into this kind of design, and NamedTuple to pull it back together again?

I think this is a nice compromise, and could be more broadly applicable. I could make a PR if people would be open to it?

**Comment by simeonschaub** [comment]
We already have that:
```julia
julia> Tuple(pairs((a=1, b=2)))
(:a => 1, :b => 2)

julia> NamedTuple(ans)
(a = 1, b = 2)
```
I don't really see anything actionable here.

**Comment by bramtayl** [comment]
Yes, I suppose that could work for my purposes, as long as constant propagation kicks in consistently
