### ISSUE TITLE
Meta.parse is using byte index, not character index as implied by the docs

### ISSUE THREAD

**Issue by gaika** [JuliaLang/julia#39928]
```
julia> str = "Γ=1\nΓ"
"Γ=1\nΓ"

julia> length(str), length(Vector{UInt8}(str))
(5, 7)

julia> Meta.parse(str, 1)
(:(Γ = 1), 6)

julia> Meta.parse(str, 6)
(:Γ, 8)
```

Very easy to make a mistake assuming that returned index will be a character position, see for example https://github.com/ChrisRackauckas/ParallelDataTransfer.jl/blob/master/src/ParallelDataTransfer.jl#L84
that will fail with unicode characters:
```
while s <= length(text)
      ex, s = Meta.parse(text, s)
      ....
end
 ```

**Comment by vtjnash** [comment]
Using `length` instead of `sizeof` is an easy mistake (and `O(n^2)` 😨). However, that `s` _is_ the index

**Comment by StefanKarpinski** [comment]
Unclear what to do here. Can you propose a clarification to the docs, @gaika?
