### ISSUE TITLE
hcat with zero-dim array makes Julia hang

### ISSUE THREAD

**Issue by knuesel** [JuliaLang/julia#39920]
This hangs instead of raising an error in Julia 1.6-rc1:

```
hcat([1,2], fill(1))
```

**Comment by sostock** [comment]
It is fixed on master (throws a `DimensionMismatch`). Might be good to bisect it so it can be backported to 1.6.

It also hangs on Julia 1.0 and 1.5.

**Comment by mbauman** [comment]
It's https://github.com/JuliaLang/julia/pull/39608 and is slated for back porting into RC2.
