### ISSUE TITLE
Add a documentation page summarising syntax

### ISSUE THREAD

**Issue by pxeger** [JuliaLang/julia#39927]
For a new user seeking a quick introduction to the syntax of the language ([*learn X in Y minutes*](https://learnxinyminutes.com/docs/julia/)-style), there doesn't seem to be any page with an overview of the actual syntax of the language geared at new users; it all seems to be scattered in the pages describing the features that the syntax represents.

So far I have found these pages:
- [Syntax](https://docs.julialang.org/en/v1/base/base/#Syntax), which doesn't seem to actually have anything to do with syntax?
- [Keywords](https://docs.julialang.org/en/v1/base/base/#Keywords), which lists only the keywords and not operators, literals, etc. or an overview to how the syntax even works
- [AST](https://docs.julialang.org/en/v1/devdocs/ast/), which is not very friendly for a new user and doesn't give much detail
- [Operator Precedence and Associativity](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Operator-Precedence-and-Associativity), which is only about the operators, and isn't even complete in that (it defers to telling you to read source code, which isn't user-friendly - "For a complete list of every Julia operator's precedence, see the top of this file: `src/julia-parser.scm`")

It would be great to have something to allow experienced programmers but who are new to Julia to get up-and-running quickly like [learn X in Y minutes](https://learnxinyminutes.com/docs/julia/) but official and always kept up-to-date.

Perhaps also a full formal grammar specification akin to [Python's](https://docs.python.org/3/reference/grammar.html) would be useful for, e.g. people who want to develop tools interacting with Julia source code (where they can't use the AST directly because they're not written in Julia)

**Comment by mgkuhn** [comment]
See also #4144

**Comment by ViralBShah** [comment]
I feel this is too broad to be an issue. We could convert it to a discussion or use discourse, but I'm closing here for now.
