### ISSUE TITLE
Core.box in closures when symbol gets reassigned even with let blocks!

### ISSUE THREAD

**Issue by Sixzero** [JuliaLang/julia#39939]
I noticed allocation issues when I write my closure based on the guidelines stated here: 
https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-captured

Example:
```
closure_test() = begin
	r = 1
	let t_r= r; () -> begin
			t_r += 1
			t_r
		end 
	end
end
@time test()()
#  0.000003 seconds (3 allocations: 48 bytes) # should be zero allocation
@code_warntype test()
...
  r::Int64
  #9::var"#9#10"
  t_r::Core.Box
...
```

As far as I know about the "let" block: "The let block creates a new variable `r` whose scope is only the inner function."
So in case we would change the value it shouldn't get Core.box-ed since it is only for the inner function.

It is incredibly crucial in many julia codes written all around the world.

Either we need to correct the documentation, or find out why it is getting Core.box-ed.

**Comment by simeonschaub** [comment]
The documentation is right, but you are assigning to `t_r` multiple times in the inner scope, so boxing is still necessary here. This is due to the way closed over variables behave:
```julia
julia> f = closure_test()
#1 (generic function with 1 method)

julia> f()
2

julia> f()
3
```
Feel free to propose a PR if you feel like this could be explained a bit clearer in the docs though. Eventually we should really have better analysis here to be able to still infer the type of the boxed variable in cases like this. Until then, a workaround would be using a `Ref` instead.

**Comment by Sixzero** [comment]
Maybe we could add that, reassigning to a variable in the closure creates a Core.Box could be added, but if there is a solution incoming, then I think I just close the issue. 

What would be a Ref solution to this problem?

**Comment by simeonschaub** [comment]
> if there is a solution incoming, then I think I just close the issue.

I don't expect this particular issue to be fixed very soon. Opaque closures circumvent this, but they are not one-for-one replacements for regular closures.

> What would be a Ref solution to this problem?

What I mean is doing something like this instead if you still want the closure semantics:
```julia
julia> f = closure_test()
#3 (generic function with 1 method)

julia> f()
2

julia> f()
3

julia> @code_warntype f()
MethodInstance for (::var"#3#4"{Base.RefValue{Int64}})()
  from (::var"#3#4")() in Main at REPL[5]:3
Arguments
  #self#::var"#3#4"{Base.RefValue{Int64}}
Body::Int64
1 ─ %1 = Core.getfield(#self#, :t_r)::Base.RefValue{Int64}
│   %2 = Base.getindex(%1)::Int64
│   %3 = (%2 + 1)::Int64
│   %4 = Core.getfield(#self#, :t_r)::Base.RefValue{Int64}
│        Base.setindex!(%4, %3)
│   %6 = Core.getfield(#self#, :t_r)::Base.RefValue{Int64}
│   %7 = Base.getindex(%6)::Int64
└──      return %7
```
If you don't care about this behavior, the easiest solution is of course to not reassign variables outside the scope of the closure, but just using a different name or even a `let tr=tr ... end` inside the closure instead.

**Comment by Sixzero** [comment]
Thank you for your example! Going to check this direction out!
