### ISSUE TITLE
`JULIA_EXCLUSIVE` docs do not correctly describe the actual behavior?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#39947]
The docs for the `JULIA_EXCLUSIVE` environment variable say:
https://github.com/JuliaLang/julia/blob/5fab42ac868f70d1edc6fe85b65a2df6442722b7/doc/src/manual/environment-variables.md#L232-L236

However, this does not seem to be correct. If I set `export JULIA_EXCLUSIVE=1`, everything seems to work correctly. But if I set `export JULIA_EXCLUSIVE=true`, it behaves the same as if I had set `export JULIA_EXCLUSIVE=0`.

```bash
$ export JULIA_EXCLUSIVE=1
$ julia -t 99
ERROR: Too many threads requested for JULIA_EXCLUSIVE option.
$ export JULIA_EXCLUSIVE=true
$ julia -t 99
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-DEV.664 (2021-03-06)
 _/ |\__'_|_|_|\__'_|  |  Commit 5fab42ac86* (1 day old master)
|__/                   |

julia>
```

**Comment by KristofferC** [comment]
It gets handled here:

https://github.com/JuliaLang/julia/blob/6fb355885e96c40af119f7d360945021ab03f7d7/src/threading.c#L426-L429

So basically, any integer not equal to 0 will cause exclusive, but anything else will make it non-exclusive. Perhaps it should error if the env var is not an integer?

**Comment by DilumAluthge** [comment]
Yeah either of those sounds fine.

**Comment by DilumAluthge** [comment]
We could also just change the docs to say the input must be an integer.

**Comment by DilumAluthge** [comment]
I don't feel strongly either way.

**Comment by KristofferC** [comment]
The other env variables that has the same wording use this structure:

https://github.com/JuliaLang/julia/blob/970edc7d7734ce0175177699e474ffc8f7b9eb27/src/gc-debug.c#L987-L988

Could change to that?
