### ISSUE TITLE
Error when using Iterative Solvers for lazy linear maps composed from Kronecker products  of sparse matrices

### ISSUE THREAD

**Issue by MKAbdElrahman** [JuliaLang/julia#39941]
I'm solving a linear system Ax  = b where A is a lazy linear map defined from Kronecker products  of sparse matrices  and the identity map. I got the following  error.  Can you help me fix this? Thanks
 

ERROR: MethodError: no method matching cholesky(::Hermitian{Complex{Float64},Base.ReshapedArray{Complex{Float64},2,SubArray{Complex{Float64},1,Base.ReshapedArray{Complex{Float64},2,SubArray{Complex{Float64},1,Array{Complex{Float64},2},Tuple{UnitRange{Int64},Int64},true},Tuple{}},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Tuple{}}}; check=false)
Closest candidates are:
  cholesky(::Union{Hermitian{Complex{T},SparseArrays.SparseMatrixCSC{Complex{T},Int64}}, Hermitian{T,SparseArrays.SparseMatrixCSC{T,Int64}}, Symmetric{T,SparseArrays.SparseMatrixCSC{T,Int64}}, SparseArrays.SparseMatrixCSC{T,Ti} where Ti<:Integer, SparseArrays.SparseMatrixCSC{Complex{T},Ti} where Ti<:Integer}; kws...) where T<:Real at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:1458
  cholesky(::Union{StridedArray{T, 2} where T, Union{Hermitian{var"#s823",var"#s822"}, Hermitian{Complex{var"#s823"},var"#s822"}, Symmetric{var"#s823",var"#s822"}} where var"#s822"<:(StridedArray{T, 2} where T) where var"#s823"<:Real}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/cholesky.jl:344 got unsupported keyword argument "check"
  cholesky(::Union{StridedArray{T, 2} where T, Union{Hermitian{var"#s821",var"#s820"}, Hermitian{Complex{var"#s821"},var"#s820"}, Symmetric{var"#s821",var"#s820"}} where var"#s820"<:(StridedArray{T, 2} where T) where var"#s821"<:Real}, ::Val{false}; check) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/cholesky.jl:344
  ...

**Comment by dkarrasch** [comment]
Welcome to the Julia community. Questions like yours are better posed on https://discourse.julialang.org/ and, second, to provide a MWE (see https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757/31 for further advice).

**Comment by MKAbdElrahman** [comment]
Thanks for letting me know!
