### ISSUE TITLE
Making intersection of Iterators.ProductIterator of AbstractRange a ProductIterator

### ISSUE THREAD

**Issue by OlivierHnt** [JuliaLang/julia#39943]
Follow-up of [this discourse thread](https://discourse.julialang.org/t/intersection-of-productiterator/53357).

Would it be reasonable to have `intersect(::Iterators.ProductIterator{<:NTuple{N,AbstractRange}}, ::Iterators.ProductIterator{<:NTuple{N,AbstractRange}})  where {N}` returning a `ProductIterator` instead of generating all the elements in a `Vector`.

For instance:

```Julia
foo(a::Iterators.ProductIterator{<:NTuple{N,UnitRange}}, b::Iterators.ProductIterator{<:NTuple{N,UnitRange}}) where {N} =
    Iterators.product(map(intersect, a.iterators, b.iterators))
```

Note: I noticed that on v1.6 `intersect` on `CartesianIndices` now has this feature.

**Comment by kahanikaar** [comment]
I would like to contribute to this issue, will be grateful for guidance to approach this. @OlivierHnt

**Comment by OlivierHnt** [comment]
Great, thanks :) What I had in mind is to match the behaviour of `intersect` for  `ProductIterator` with the one of `CartesianIndices` in Julia v1.6.

So in the file iterators.jl you could simply add

```julia
Base.intersect(a::ProductIterator{<:NTuple{N,AbstractRange}}, b::ProductIterator{<:NTuple{N,AbstractRange}}) where {N} =
        ProductIterator(intersect.(a.iterators, b.iterators))
```

and make a pull request with it.

Does this seem reasonable? The restriction `NTuple{N,AbstractRange}` is meant for "safety".

**Comment by kahanikaar** [comment]
Initial PR made. Do review. @OlivierHnt
