### ISSUE TITLE
Export typename(x).wrapper as a Base function

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#39952]
About once every 14 days, I see this question on the Julia Slack:
```
I have an object of `Array{MyType, 2}`. How do I get `Array` from that?
```
The answer is `Base.typename(T).wrapper`, but that's completely un-findable, and gets into the internals by reading field types from the `TypeName`. I don't understand why people want this, but it keeps coming up. Most of the time, the usage seems legitimate, in the sense that other people on Slack can't tell that they should really be solving the problem in another way - though it's hard to know if they should just from a Slack conversation.

Maybe there should be a `basetype` function exported from Base, defined as `basetype(::Type{T}) where T = typename(T).wrapper`?

**Comment by kimikage** [comment]
BTW, I think the idiom is often used with `@pure`.  is it generally safe?

**Comment by kimikage** [comment]
Dup of #35543?

**Comment by vtjnash** [comment]
Yeah, looks like it
