### ISSUE TITLE
Stack traces short/missing on Darwin/ARM64

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#39986]
I'm seeing stack traces with only a few layers, or none, on an M1 mac, with yesterday's master. @staticfloat suggests this is related to the "Unwinding from JIT frames doesn't work" item of https://github.com/JuliaLang/julia/issues/36617

```julia
julia> sqrt(-1)
ERROR: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33

julia> Matrix{Int}([1 2; 3 4.5])
ERROR: InexactError: Int64(4.5)

julia> versioninfo()
Julia Version 1.7.0-DEV.685
Commit f3c66b3f9d (2021-03-10 18:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.3.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
```

**Comment by Keno** [comment]
> @staticfloat suggests this is related to the "Unwinding from JIT frames doesn't work" item of #36617

Yes, that is that item.

**Comment by hahnjo** [comment]
Hi @Keno, I think the unwinding problems are related to what I describe in https://bugs.llvm.org/show_bug.cgi?id=49692#c8: M1 uses pointer authentication, and `libunwind` has to strip the tag from the upper bits before doing anything with the instruction pointer. Apparently Apple's `libunwind` does that, but the version available from opensource.apple.com doesn't have the necessary code, nor LLVM upstream. The comment I linked has a hacky workaround that you may want to include in your own `libunwind` (at least it's my understanding that you distribute your own and don't use the system library?).

A question in that regard: Is Julia using exception unwinding as well? That's what the bug report is about and what we're interested in for the ROOT framework (developed at CERN). In the latest comment, I suggest that there may be a bug in Apple's `libunwind` so we're looking who else might be affected...

**Comment by vchuravy** [comment]
Can someone test this with #41421?

**Comment by mcabbott** [comment]
This seems to work here, thanks!
```
julia> sqrt(-1)
ERROR: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] sqrt
   @ ./math.jl:567 [inlined]
 [3] sqrt(x::Int64)
   @ Base.Math ./math.jl:1221
 [4] top-level scope
   @ REPL[5]:1

julia> using Plots

julia> plot(rand(20), c=:nope)
ERROR: Unknown color: nope
Stacktrace:
  [1] error(::String, ::String)
    @ Base ./error.jl:42
  [2] _parse_colorant(desc::String)
    @ Colors ~/.julia/packages/Colors/yDxFN/src/parse.jl:151
  [3] parse(#unused#::Type{RGBA{Float64}}, desc::String)
    @ Colors ~/.julia/packages/Colors/yDxFN/src/parse.jl:207
... etc
 ```

**Comment by mcabbott** [comment]
This problem seems to have returned:
```
 _/ |\__'_|_|_|\__'_|  |  Commit 294b0dfcd3 (0 days old master)
|__/                   |

julia> log(-1)
ERROR: DomainError with -1.0:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(f::Symbol, x::Float64)
   @ Base.Math ./math.jl:33
 [2] _log(x::Float64, base::Val{:ℯ}, func::Symbol)
   @ Base.Math ./special/log.jl:292

julia> 
```
On 1.7 that prints 5 lines.

This was fine on master from 10 days ago.
