### ISSUE TITLE
Cursor progress indicator artefact in REPL

### ISSUE THREAD

**Issue by knuesel** [JuliaLang/julia#39982]
On master (bb5a0130) there is a visual artefact in the REPL when typing text in front of a character, not present in 1.6-rc1:

https://user-images.githubusercontent.com/2412819/110826693-9f57c700-8295-11eb-9f92-f4eaf0108db0.mp4

The video looks slowed-down, it's not so clear in real life but it does look weird.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/39538 probably.

**Comment by vtjnash** [comment]
yes, it's only there for 15ms or so (greatly depending on the performance of your terminal) to visually indicate some characters are being inserted, until we can refresh the whole screen to show them

**Comment by vtjnash** [comment]
I guess what we should do though is optimistically insert the user's character first on the first key press, then start the spinner on the 2nd key press, to minimize visual tearing

**Comment by KristofferC** [comment]
Or maybe just not have the spinner?

**Comment by JeffBezanson** [comment]
I also find this change not so great, on linux at least. In addition to this issue, when holding down a key it looks like text is being overwritten even though it's not, which is disconcerting.
