### ISSUE TITLE
Usage of assert in asyncevent

### ISSUE THREAD

**Issue by Arkoniak** [JuliaLang/julia#39991]
Sorry, if this is a false alarm.

`@assert` doc string says

```
help?> @assert
  @assert cond [text]

  Throw an AssertionError if cond is false. Preferred syntax for writing assertions. Message text is optionally displayed upon assertion failure.

  │ Warning
  │
  │  An assert might be disabled at various optimization levels. Assert should therefore only be used as a debugging tool and not used for authentication verification (e.g.,
  │  verifying passwords), nor should side effects needed for the function to work correctly be used inside of asserts.
```

With main emphasize on the fact that `@assert` might be disabled. When I was browsing julia source code, I've stumbled on this
 https://github.com/JuliaLang/julia/blob/master/base/asyncevent.jl#L85 and other `@assert` line nearby.

It looks to me, that in this code, `@assert` is not used as a debugging tool and bad things could happen if it is turned off.

If it is really the case, I can make a PR, with `@assert` changed to something like
```
res == 0 || throw("Unable to initiate Timer")
```

**Comment by DilumAluthge** [comment]
Good catch. Yeah we should not be using `@assert` in this way. Want to make that PR?

**Comment by vtjnash** [comment]
Neither function call can fail, the return code is just in the libuv API for consistency
