### ISSUE TITLE
Add propagate_inbounds to new getindex method

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#39996]
MWE:
```julia
struct TextKmerIterator
    data::Vector{UInt8}
    stop::UInt # inclusive
end

function foo(x::TextKmerIterator)
    kmer, i, k = UInt(0), UInt(1), UInt(0)
    @inbounds while i ≤ x.stop
        byte = x.data[i]
        k += one(UInt)
        i += 1
        kmer = ((kmer << 2) & UInt(0x3f)) | 0x01
        if k == 3
            return kmer, (kmer, i, k-one(UInt))
        end
    end
    return nothing
end
```
And then
```julia
julia> it = TextKmerIterator(collect(codeunits("T")), 4)
Main.TextKmerIterator(UInt8[0x54], 0x0000000000000004)

julia> foo(it)
ERROR: BoundsError: attempt to access 1-element Vector{UInt8} at index [2]
```
According to Nicholas Bauer on Slack, the culprit is https://github.com/JuliaLang/julia/blob/0b554250ce4838cb34c4b5975d9f49e1c6aae19d/base/abstractarray.jl#L1051 

added in #36427 which lacks propagate inbounds.

**Comment by simeonschaub** [comment]
Ah, that looks like it was missed. Note however that reading arrays out of bounds should always be avoided nevertheless and can lead to segfaults.

**Comment by kahanikaar** [comment]
I would like to contribute to this issue. Do guide me on approaching this @simeonschaub @jakobnissen

**Comment by jakobnissen** [comment]
@kahanikaar Nice! You would need to clone the Julia repo. Then go to the relevant file and add `@_propagate_inbounds_meta` right before the function call. I think that should do the trick.

To verify it worked, you can run my test code. If you don't see a BoundsError, it probably worked. To be sure, you can run `@code_native foo(it)` and check that there is no boundschecking branch.

**Comment by kahanikaar** [comment]
Initial PR made. Do review. @jakobnissen @simeonschaub

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/julia/pull/40281?

**Comment by jakobnissen** [comment]
Yes, looks like it! Thanks for your PR anyway, @kahanikaar
