### ISSUE TITLE
Reconsider stance on forward progress guarantees

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#40009]
Our longstanding policy on forward progress guarantees has basically been that
we expose the LLVM behavior and follow the C/C++ world by considering infinite
loops to be undefined behavior, leading to behavior like:
```
julia> f(x) = x ? true : while true; end
f (generic function with 1 method)

julia> f(true)
true

julia> f(false)
true
```

This might not seem to bad, but it can lead to unsoundness and security vulnerabilities ("nice error check you have there, would be a shame if somebody were to see the UB before it")
```
julia> @noinline function my_checkbounds(Alen::Int, i::Int)
               if i < 0 || i > Alen
                       while true; end # A bad error path, maybe inlined from somewhere
                       return false
               end
               return true
       end
my_checkbounds (generic function with 2 methods)

julia> function my_getindex(A::Vector{Int}, i::Int)
               my_checkbounds(length(A), i) || error("Out of bounds!")
               @inbounds A[i]
       end
my_getindex (generic function with 1 method)

julia> my_getindex(Int[1], 100000000)

signal (11): Segmentation fault
```

For this reason, more modern languages tend to not make forward progress assumptions. The Rust folks in particular took this quite seriously and recently changed LLVM to require the `mustprogress` attribute in order to top into forward progress guarantees (https://reviews.llvm.org/D85393). We should carefully chose what to do here. Since we don't set the new LLVM attribute, LLVM actually no longer makes these forward progress assumptions on our code. However, we do still make such assumptions in our own inference code.

Now that LLVM is fixed, my preference would be to follow Rust here and stop making any forward progress assumptions.

**Comment by nsajko** [comment]
I'd just like to note that I think some things above are possibly misleading. This is the relevant part of the example:

```
while true; end
return false
```

In the context of the rest of the example, probably everybody would prefer the infinite loop to stay where it is and keep the `return` from executing and it's true that the forward progress guarantee could cause the loop to be eliminated, but ...

... I think the loop could also be eliminated by much more basic semantics: `return false` has no dependency on the loop; so I suppose a compiler for basically any compiled programming language could reorder the two lines, putting the loop after the `return`, thus making the loop unreachable anyway.

AFAIK, Julia has no memory model or specifications for stuff like observability, volatile reads or volatile writes (I think it's not even possible to do volatile reads or writes from Julia?); it seems like this discussion could lack essence until Julia is better specified in those regards.

(BTW, it's possible I made some mistakes here because I'm new to Julia, but I tried to talk about programming language stuff in general.)

**Comment by Keno** [comment]
> I'd just like to note that I think some things above are possibly misleading.

The point was to illustrate that undefined behavior can lead to soundness violations that are otherwise unexpected. I'm not sure what's misleading about that.

> ... I think the loop could also be eliminated by much more basic semantics: `return false` has no dependency on the loop; so I suppose a compiler for basically any compiled programming language could reorder the two lines, putting the loop after the `return`, thus making the loop unreachable anyway.

C/C++ explicitly make this undefined behavior, but I don't really know of any compiler that reasons this way. You can usually move probably pure statements between sequence points, but a return is usually a terminal sequence point and you cannot commute things past it. Of course you can eliminate pure statements that have an unused result, but that gets back to the definition of purity here.

**Comment by martinholters** [comment]
Given that `f(false)` now hangs, can you provide an example which exposes the problem on the Julia rather than the LLVM side?

**Comment by stevengj** [comment]
This loop doesn't hang (in either 1.7 or 1.9-dev):
```jl
julia> f(x) = while x end
f (generic function with 1 method)

julia> f(true) # doesn't hang
```

**Comment by brenhinkeller** [comment]
Since #47664 is closed as dup, I'll just note here that it might be nice if the solution ensures this 
```
julia> all(Iterators.repeated(true))
false

julia> any(Iterators.repeated(false))
true
```
doesn't happen one way or another 😀

**Comment by gbaraldi** [comment]
https://isocpp.org/files/papers/P2809R3.html C++ just changed their side of this so probably a useful reference

**Comment by Keno** [comment]
Reopening this, so someone remembers to write NEWS about this.

**Comment by LilithHafner** [comment]
The issue itself is fixed
```julia
x@fedora:~$ julia +nightly --startup-file=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.344 (2024-04-15)
 _/ |\__'_|_|_|\__'_|  |  Commit 7ba1b332f87 (0 days old master)
|__/                   |

julia> f(x) = x ? true : while true; end
f (generic function with 1 method)

julia> f(true)
true

julia> f(false)
^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C^CERROR: InterruptException:
Stacktrace:
 [1] f(x::Bool)
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[3]:1

julia> @noinline function my_checkbounds(Alen::Int, i::Int)
               if i < 0 || i > Alen
                       while true; end # A bad error path, maybe inlined from somewhere
                       return false
               end
               return true
       end
my_checkbounds (generic function with 1 method)

julia> function my_getindex(A::Vector{Int}, i::Int)
               my_checkbounds(length(A), i) || error("Out of bounds!")
               @inbounds A[i]
       end
my_getindex (generic function with 1 method)

julia> my_getindex(Int[1], 100000000)
^C^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^CERROR: InterruptException:
Stacktrace:
 [1] my_checkbounds(Alen::Int64, i::Int64)
   @ Main ./REPL[4]:3
 [2] my_getindex(A::Vector{Int64}, i::Int64)
   @ Main ./REPL[5]:2
 [3] top-level scope
   @ REPL[6]:1

julia> f(x) = while x end
f (generic function with 2 methods)

julia> f(true) # doesn't hang
^C^C^C^C^CWARNING: Force throwing a SIGINT
^CERROR: InterruptException:
Stacktrace:
 [1] f(x::Bool)
   @ Main ./REPL[7]:0
 [2] top-level scope
   @ REPL[8]:1

julia> ^C

julia> ^C

julia> all(Iterators.repeated(true))
^C^C^C^C^C^CWARNING: Force throwing a SIGINT
ERROR: InterruptException:
Stacktrace:
 [1] all(itr::Base.Iterators.Repeated{Bool})
   @ Base ./reduce.jl:0
 [2] top-level scope
   @ REPL[9]:1

julia> any(Iterators.repeated(false))
^C^C^C^C^CWARNING: Force throwing a SIGINT
ERROR: InterruptException:
Stacktrace:
 [1] _any
   @ ./reduce.jl:0 [inlined]
 [2] any
   @ ./reduce.jl:1220 [inlined]
 [3] any(itr::Base.Iterators.Repeated{Bool})
   @ Base ./reduce.jl:1146
 [4] top-level scope
   @ REPL[10]:1
```
