### ISSUE TITLE
Tests failures when USE_SYSTEM_7ZIP=1

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#40011]
When building with `USE_SYSTEM_7ZIP=1` and running tests from the build directory (rather than from the final directory where `make install` will put the `julia` executable), tests fail in several places (e.g. InteractiveUtils and commandlineargs), as Julia fails to start when run with no environment variables. This is because `PATH` is needed for `Sys.which()` to find where `7z` lives.

The problem is more general though: when `PATH` isn't set, Julia will fail to start if `7z` cannot be found in `Sys.BINDIR` or `Sys.LIBEXECDIR`.

A solution would be to create a `7z` symlink in `Sys.BINDIR` that would point to the place where `7z` lives in `PATH` during build. That wouldn't allow using a `7z` living in a different directory, but that's probably OK (and possibly safer that the current approach as it would avoid using a different `7z` version accidentally).

This failure is new in 1.6.0-rc2, as in rc1 Julia didn't seem to load p7zip_jll on startup.

Cc: @staticfloat

Minimal reproducer:
```julia
julia> exename = `$(Base.julia_cmd()) --startup-file=no`
`/home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/bin/julia -Cnative -J/home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/lib/julia/sys.so -g1 --startup-file=no`

julia> run(setenv(`$exename -e 'using p7zip_jll'`, String[]))
fatal: error thrown and no exception handler available.
InitError(mod=:p7zip_jll, error=MethodError(f=Base.Filesystem.dirname, args=(nothing,), world=0x00000000000073a5))
jl_method_error_bare at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/gf.c:1812
jl_method_error at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/gf.c:1830
jl_lookup_generic_ at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/gf.c:2400 [inlined]
jl_apply_generic at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/gf.c:2415
__init__ at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/share/julia/stdlib/v1.6/p7zip_jll/src/p7zip_jll.jl:86
jl_apply at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/julia.h:1703 [inlined]
jl_module_run_initializer at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/toplevel.c:72
_julia_init at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/init.c:794
repl_entrypoint at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/src/jlapi.c:696
main at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/cli/loader_exe.c:51
__libc_start_main at /lib64/libc.so.6 (unknown line)
_start at /home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/bin/julia (unknown line)
ERROR: failed process: Process(setenv(`/home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/bin/julia -Cnative -J/home/milan/Dev/rpmbuild/BUILD/julia-1.6.0-rc2/build/usr/lib/julia/sys.so -g1 --startup-file=no -e 'using p7zip_jll'`,String[]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run(::Cmd)
   @ Base ./process.jl:438
 [4] top-level scope
   @ REPL[8]:1
""

**Comment by staticfloat** [comment]
Thanks for the report Milan, can you try out https://github.com/JuliaLang/julia/pull/40045 and see if it helps at all?

**Comment by ViralBShah** [comment]
Is it possible to check if #40045 fixed it?

**Comment by nalimilan** [comment]
I noted at https://github.com/JuliaLang/julia/pull/40045#pullrequestreview-612684413 that it indeed fixes the issue. Sorry for not closing it.
