### ISSUE TITLE
@edit macro cannot find source on Manjaro Linux

### ISSUE THREAD

**Issue by pgagarinov** [JuliaLang/julia#40036]
@which macro works while @edit macro doesn't.

```
julia> @which min(1,2)
min(x::T, y::T) where T<:Real in Base at promotion.jl:410

julia> @edit min(1,2)
ERROR: could not find source file for function
Stacktrace:
 [1] edit(::Nothing, ::Int32) at /build/julia/src/julia-1.5.3/usr/share/julia/stdlib/v1.5/InteractiveUtils/src/editless.jl:224
 [2] edit(::Function, ::Any) at /build/julia/src/julia-1.5.3/usr/share/julia/stdlib/v1.5/InteractiveUtils/src/editless.jl:223
 [3] top-level scope at REPL[2]:1
 [4] run_repl(::REPL.AbstractREPL, ::Any) at /build/julia/src/julia-1.5.3/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288

julia> 
```

Julia is installed from the standard repo via `sudo pacman -S julia`

**Comment by Seelengrab** [comment]
Does this also occur with an official install from e.g. source or via the tarballs provided on https://julialang.org/downloads/?

Note that versions packaged by various distributions are not supported, so if the issue turns out to be specific to the version packaged by Manjaro, please contact them instead.

**Comment by pgagarinov** [comment]
> Does this also occur with an official install from e.g. source or via the tarballs provided on https://julialang.org/downloads/?

I've just checked - everything works with the official binaries installed from AUR via `yay -S julia-bin`.

@Seelengrab 
> Note that versions packaged by various distributions are not supported, so if the issue turns out to be specific to the version packaged by Manjaro, please contact them instead.

I agree that it is the Linux distribution vendor who should make sure nothing breaks. However, what confuses me is that `@which` macro can find the source and even shows the line number, why can't `@edit` macro use the same mechanism so that it works regardless of whether Julia is installed from the official binary manually or from the Linux distribution official repo? Thanks.

**Comment by KristofferC** [comment]
> However, what confuses me is that @which macro can find the source and even shows the line number, why can't @edit macro use the same mechanism so that it works regardless of whether Julia is installed from the official binary manually or from the Linux distribution official repo?

`@which` just shows the data stored in Julia where the function should be located. `@edit` actually has to find that file and open it in an editor.

**Comment by pgagarinov** [comment]
For those who will face the same problem - the issue seems to be Manjaro Linux-specific, the same package from the community repo
```
community/julia 2:1.5.3-2 [installed]
    High-level, high-performance, dynamic programming language
```

 on pure Arch Linux is not broken.

**Comment by xyzhou-1** [comment]
@pgagarinov see: https://github.com/archlinux/svntogit-community/commit/9acd9c726660400f93e22b3ec9dcda3ec28a4bba#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422

The PKGBUILD of v1.5.3 did not specify `prefix=/usr` so julia get wrong path : `/build/julia/src/julia-1.5.3/usr/share/julia/stdlib/v1.5`.

The PKGBUILD of v1.5.4 fix this, so Arch Linux is not broken.
So you can fix this by:
- switch manjaro branch to unstable or testing to get julia v1.5.4
- AUR 
- install it manually from Arch Linux repo https://archlinux.org/packages/community/x86_64/julia/download/

**Comment by KristofferC** [comment]
I assume this is considered fixed then.
