### ISSUE TITLE
Possible breakage in 1.6.0-rc2 and nightly in evaluating CartesianIndices for OffsetArrays with BigInt parent ranges

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#40035]
Unfortunately there's a bug on master in `OffsetArrays` currently, so [this PR](https://github.com/JuliaArrays/OffsetArrays.jl/pull/227) is necessary to see the issue:

on 1.5.4:
```julia
julia> using OffsetArrays

julia> a = OffsetArray(big(1):big(2), 0);

julia> CartesianIndices(a)
2-element CartesianIndices{1,Tuple{OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}}}} with indices 1:2:
 CartesianIndex(1,)
 CartesianIndex(2,)
```
on 1.6.0-rc2 and nightly:
```julia
julia> CartesianIndices(a)
ERROR: MethodError: no method matching OrdinalRange{Int64, Int64}(::OffsetArrays.IdOffsetRange{BigInt, Base.OneTo{BigInt}})
Closest candidates are:
  OrdinalRange{T1, T2}(::AbstractUnitRange{T1}) where {T1, T2<:Integer} at range.jl:1133
  OrdinalRange{T1, T2}(::StepRange) where {T1, T2<:Integer} at range.jl:1132
  OrdinalRange{T1, T2}(::UnitRange) where {T1, T2<:Integer} at range.jl:1134
  ...
Stacktrace:
 [1] convert(#unused#::Type{OrdinalRange{Int64, Int64}}, r::OffsetArrays.IdOffsetRange{BigInt, Base.OneTo{BigInt}})
   @ Base ./range.jl:215
 [2] (::Base.IteratorsMD.var"#7#8")(r::OffsetArrays.IdOffsetRange{BigInt, Base.OneTo{BigInt}})
   @ Base.IteratorsMD ./multidimensional.jl:271
 [3] map
   @ ./tuple.jl:213 [inlined]
 [4] CartesianIndices(inds::Tuple{OffsetArrays.IdOffsetRange{BigInt, Base.OneTo{BigInt}}})
   @ Base.IteratorsMD ./multidimensional.jl:271
 [5] CartesianIndices(A::OffsetVector{BigInt, UnitRange{BigInt}})
   @ Base.IteratorsMD ./multidimensional.jl:279
 [6] top-level scope
   @ REPL[4]:1

julia> VERSION
v"1.7.0-DEV.707"
```

This is due to a missing method for the `IdOffsetRange` axis type defined in `OffsetArrays`, but this conversion is not used in 1.5.4. The conversion carried out by `CartesianIndices` appears to have changed from an `AbstractUnitRange{Int}` in 1.5.4  to an `OrdinalRange{Int,Int}` in 1.6.

**Comment by jishnub** [comment]
Looks like this was introduced by https://github.com/JuliaLang/julia/pull/37829

**Comment by KristofferC** [comment]
Related to https://github.com/JuliaLang/julia/issues/39589?

**Comment by jishnub** [comment]
It's not unrelated as the same constructor is called eventually, but this seems to be a different issue (the other one is primarily due to what `_convert2ind` seems to be doing). This issue can be fixed by adding a specialized constructor for `AbstractUnitRange`s, so perhaps I will make a PR.

**Comment by laborg** [comment]
This works on 1.6.5, on 1.7.2 and on master - Is there any reason not to close this (and https://github.com/JuliaLang/julia/pull/40038)?

**Comment by KristofferC** [comment]
If it works on those releases, it seems indeed a good idea to close.

**Comment by vtjnash** [comment]
Whoops, I tested that PR and it is still needed. Left a comment there about how we could finish that.
