### ISSUE TITLE
How about contribution from Bangladesh? 

### ISSUE THREAD

**Issue by FahimFBA** [JuliaLang/julia#40033]
**I want to write a complete book/static site on GitHub about Julia Language**, from the basics to the advanced gradually. I have also planned to make tutorial videos for this amazing programming language on YouTube too. My target is to make learning this amazing language easy and implementing this frequently for those people whose mother tongue is Bengali, and they can start their journey with their native language. I would appreciate your thought regarding this.

**Comment by KristofferC** [comment]
That sounds like a great idea! However, the issue tracker here is for issues with the language, for more conversation type of discussion please use https://discourse.julialang.org/. Good luck!

**Comment by FahimFBA** [comment]
Thanks a lot, and I am sorry for that inconvenience. I will use [this](https://discourse.julialang.org/) for that purpose from now on.
