### ISSUE TITLE
Unable to unpack JuliaPro Package Mac

### ISSUE THREAD

**Issue by stevecrossan** [JuliaLang/julia#40043]
Hello,

After downloading from https://juliacomputing.com/products/juliapro/ I am unable to unpack the package with the following error:

“JuliaPro-1.0.5-2_build-54.pkg” can’t be opened because Apple cannot check it for malicious software.

**Comment by KristofferC** [comment]
JuliaPro is a product from JuliaComputing while this is the issue tracker for the Julia language. I would suggest mailing Julia Computing with the problem.
