### ISSUE TITLE
SparseArrays: in-place column-only permutation

### ISSUE THREAD

**Issue by severinson** [JuliaLang/julia#40078]
I've implemented a function `permute!(X, A, q)` for permuting the columns of an `AbstractSparseMatrixCSC` in-place. Are you interested in merging this code?

There's already a function `permute!(X, A, p, q)` in the standard library for permuting both the rows and columns of a `AbstractSparseMatrixCSC` in-place (see [sparsematrix.jl](https://github.com/JuliaLang/julia/blob/master/stdlib/SparseArrays/src/sparsematrix.jl)). Because this function permutes both the rows and columns it needs to store the intermediate result `transpose(A[:, q])`. Hence, it needs twice as much memory as the function I'm proposing, which doesn't need any storage other than what is passed in.

For my use case I only need to permute the columns, and I don't have enough memory to store the matrix in memory 3 times. The proposed code is written in style used in `sparsematrix.jl` and uses the same checks.

**Comment by Seelengrab** [comment]
You can just create a PR, if it's useful and doesn't have problems/implications, it'll probably be merged.

**Comment by ViralBShah** [comment]
Agree - best is to just create a PR and then take it from there.
