### ISSUE TITLE
What to do about ZWJ emoji sequences

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#40071]
Some emojis are composed of sequences of other emoji, combined by ZWJ. At the moment, ZWJ is disallowed in the parser, so these emoji, cannot be used, e.g.:
```
julia> 🏳️‍🌈
ERROR: syntax: invisible character \u200d near column 2
Stacktrace:
 [1] top-level scope
   @ none:1
```

This is because `🏳️‍🌈` is really `🏳️‍[ZWJ]🌈`. We should decide what to do here, since use of these sequences is likely to expand in future Unicode versions. One option is of course to just do nothing and continue to disallow these. Another option may be to just normalize out the ZWJ in emoji sequences and treat that equivalently to the constituent emoji next to each other (since that's what they look like if ZWJ sequences are not supported by the font renderer.

**Comment by JeffBezanson** [comment]
Just allowing ZWJ as a (non-initial) identifier character is not a bad option. Sequences of emoji with and without the ZWJ are distinct, so to the extent we allow emoji it seems we should simply allow it.

**Comment by Keno** [comment]
What about ZWJ outside of emoji sequences? Unicode doesn't specify what emoji sequences are valid to join, but we could look at the character class to disallow it if what's being joined is not an emoji.

**Comment by JeffBezanson** [comment]
Sounds good to me.

**Comment by mgkuhn** [comment]
See also [Unicode Standard Annex #31](https://www.unicode.org/reports/tr31/) [Section 2.3](https://www.unicode.org/reports/tr31/#Layout_and_Format_Control_Characters):
>Implementations that allow emoji characters in identifiers should also normally allow emoji sequences. These are defined in [ED-17, emoji sequence](https://www.unicode.org/reports/tr51/#def_emoji_sequence) in [UTS51](https://www.unicode.org/reports/tr51/). In particular, that means allowing ZWJ characters, emoji presentation selector (U+FE0F), and TAG characters, but only in the particular defined contexts described in [UTS51](https://www.unicode.org/reports/tr51/).

**Comment by stevengj** [comment]
Allowing ZWG/U+200D as a non-initial character would be the simplest option, but if you allow it between arbitrary characters then it does allow a whole new type of obfuscated code, e.g. `"a\u200dweird\u200didentifier"` displays as `a‍weird‍identifier` in some software (and as `a weird identifier` in some other terminals).

And if you only allow it in emoji sequences it makes the parser more complicated, though not insurmountably so.

**Comment by stevengj** [comment]
I just had a brainwave — what we really want here is to not break identifiers within graphemes.   So, an improved rule for identifiers would be:

* identifier consists of a sequence of *graphemes*, each of which may begin with one of the currently allowed characters (i.e. same allowed characters at the start of the identifier, and same allowed characters afterwards).

This way we only need one more bit of state during parsing, for the grapheme-break state in utf8proc, and it will handle all of the emoji rules etcetera for us, and won't allow ZWJ in non-emoji sequences.
