### ISSUE TITLE
Pkg errors when installing ModelingToolkit on 1.6.0-rc2

### ISSUE THREAD

**Issue by crlaugh** [JuliaLang/julia#40086]
I ran into some problems with Pkg today when I tried adding ModelingToolkit on a clean install of 1.6.0-rc2.  I first installed 1.6.0-rc2 on a clean Win10-64 laptop (no .julia directory, no other Julia binaries installed), then opened up a Julia command terminal and typed  `]add ModelingToolkit`, and got error messages along the lines of the attached image:

![image (1)](https://user-images.githubusercontent.com/9616147/111562956-75a71000-876d-11eb-9fd5-a54ac00ba27e.png)  

When I uninstalled rc2 and reinstalled rc1, everything worked fine.  

Apologies for not providing better error information - I ran into problems with ModelingToolkit and was just trying to get Julia reinstalled to do some work, and quickly deleted rc2 without logging the errors so that I could try rc1 in an act of desperation.

**Comment by KristofferC** [comment]
Should be fixed in the released RC3.
