### ISSUE TITLE
Diagonal of Diagonal throws MethodError

### ISSUE THREAD

**Issue by SebastianAment** [JuliaLang/julia#40082]
Accessing the off-diagonals of a Diagonal with Diagonal elements throws a MethodError because [this line ](https://github.com/JuliaLang/julia/blob/7838e0973ba3183735cca6485a65ae9e708f0c1d/stdlib/LinearAlgebra/src/diagonal.jl#L93) is called instead of [this one](https://github.com/JuliaLang/julia/blob/7838e0973ba3183735cca6485a65ae9e708f0c1d/stdlib/LinearAlgebra/src/diagonal.jl#L94), despite `Diagonal{<:Diagonal} <: Diagonal{<:AbstractMatrix}`. I was able to circumvent the issue for my own use case by extending `diagzero` specifically for `Diagonal{<:Diagonal}` but am curious why the current `LinearAlgebra` implementation fails and believe this should be fixed. The following highlights the problem and shows that the same code works for a `Diagonal` with `Matrix` elements. 
```
using LinearAlgebra
A = randn(2, 2)
B = Diagonal([A, A])
println(B isa Diagonal{<:AbstractMatrix}) # this is true
display(B) # this works

C = Diagonal(randn(2))
D = Diagonal([C, C])
println(D isa Diagonal{<:AbstractMatrix}) # this is true
display(D) # this fails
```

**Comment by jishnub** [comment]
This appears fixed on nightly:

```julia
julia> using LinearAlgebra

julia> C = Diagonal(randn(2))
2×2 Diagonal{Float64, Vector{Float64}}:
 -0.123692    ⋅ 
   ⋅        -1.25551

julia> D = Diagonal([C, C])
2×2 Diagonal{Diagonal{Float64, Vector{Float64}}, Vector{Diagonal{Float64, Vector{Float64}}}}:
 [-0.123692 0.0; 0.0 -1.25551]          ⋅         
         ⋅                      [-0.123692 0.0; 0.0 -1.25551]

julia> display(D)
2×2 Diagonal{Diagonal{Float64, Vector{Float64}}, Vector{Diagonal{Float64, Vector{Float64}}}}:
 [-0.123692 0.0; 0.0 -1.25551]          ⋅         
         ⋅                      [-0.123692 0.0; 0.0 -1.25551]
```
