### ISSUE TITLE
1.6-rc3: ERROR: Unexpected end of data

### ISSUE THREAD

**Issue by lmiq** [JuliaLang/julia#40107]
I installed Julia 1.6-rc3 from the site, and when installing Plots (`] add Plots`) I got this error message:

```
   Installed MacroTools ─────────────────── v0.5.6
ERROR: Unexpected end of data : jl_wZO253LayoRw~====>]  107/109
┌ Warning: failed to extract archive downloaded from https://pkg.julialang.org/package/35d6a980-a343-548e-a6ea-1d62b119f2f4/3141757b5832ee7a0386db87997ee5a23ff20f4d
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:590
```

Installation continued and finished.

I could reproduce the error by simply removing the `.julia` directory and installing Plots again.

**Comment by reumle** [comment]
Hi, I just tried the same thing (install, add Plots) on my windows 10 desktop, There was no error. Hope it helps.
