### ISSUE TITLE
Integer-matrix determinants are not computed exactly

### ISSUE THREAD

**Issue by step135** [JuliaLang/julia#40128]
```julia
julia> using LinearAlgebra
julia> a = [4 7 8;5 1 0; 6 0 1]
julia> A = [1 2 3; 4 1 6; 7 8 1]
julia> det(a)
-78.99999999999999
julia> det(A)
104.0
```
There shouldn't be any reason for that behaviour.

**Comment by oscardssmith** [comment]
This happens because `det` uses an `LU` factorization which ends up converting the matrix to `Float64`. I'm not aware of any efficient algorithms for computing `Integer` determinants, but I'll look to see if any exist.

**Comment by oscardssmith** [comment]
The following is an `Integer` only `det`, but it is a bit slower, and has integer overflow problems.
```
function Base.det(M::AbstractMatrix{<:Integer})
    M = copy(M)
    n, sign, prev = size(M,1), 1, 1
    for i in 1:n-1
        if M[i,i] == 0 # swap with another row having nonzero i's elem
            swapto = findfirst(x->x!=0, @view M[i+1:N,i])
            isnothing(swapto) && return 0
            M[i,:], M[swapto,:], sign = M[swapto,:], M[i,:], -sign
        end
        for j in i+1:n
            for k in i+1:n
                M[j,k] = div(M[j,k]*M[i,i] - M[j,i]*M[i,k], prev)
            end
        end
        prev = M[i,i]
	end
    return sign * M[end,end]
end
```

**Comment by stevengj** [comment]
This comes up on discourse from time to time.  See my comment here:  https://discourse.julialang.org/t/possible-bug-in-determinant-calculation/20323/8?u=stevengj

**Comment by stevengj** [comment]
It might be reasonable to include a Dodgson condensation algorithm in Base, at least for `BigInt` matrices; that algorithm is simple to implement, not too expensive, and seems to be widely used in practice.

**Comment by oscardssmith** [comment]
How does the performance of that compare to the Bareiss algorithm version I gave above? I didn't see a runtime for Dodgson from a quick look around. Bareiss is n^3 arithmetic operations.

**Comment by stevengj** [comment]
The Dodgson is Θ(m³).

However, Dodgson is not as easy as I thought.  Here is a simple implementation of Dodgson condensation:
```jl
divide(a,b) = a / b
divide(a::Integer, b::Integer) = div(a, b)

function dodgson!(A::AbstractMatrix{T}, B::AbstractMatrix{T}) where {T<:Number}
    m,n = size(A)
    m == n > 0 || throw(ArgumentError("det requires a square matrix"))
    size(B,1) ≥ m-1 && size(B,2) ≥ m-1 || throw(DimensionMismatch())
    B .= 1
    while m > 1
        for j=1:m-1, i=1:m-1
            B[i,j] = A[i,j]
            A[i,j] = divide(A[i,j]*A[i+1,j+1] - A[i+1,j]*A[i,j+1], B[i+1,j+1])
        end
        m -= 1
    end
    return A[1,1]
end

dodgson(A::AbstractMatrix{<:Number}) = dodgson!(Base.copymutable(A), Base.copymutable(A))
```
However, this function may fail with a division by zero if a zero entry is encountered at an intermediate step.  There are workarounds, but the ones I've found seem complicated.  (e.g. [this paper](https://arxiv.org/abs/0906.3840) gives a workaround that works in "many" but not all cases.  [This paper](https://arxiv.org/abs/1907.12010) requires a symbolic-algebra package.)

**Comment by stevengj** [comment]
For implementing Bareiss, it might be a good idea to swap columns rather than rows.  Then you can use the `Base.swapcols!` function to swap the columns in-place.

**Comment by oscardssmith** [comment]
Yeah those changes make a bunch of sense. I was using a stackoverflow post with python code, hence the weird ordering. I'm still seeing that this is much slower (4x for 100x100) than `det` which is probably to be expected given that it is actually getting an exact result. Most of the time seems to be caused by 3.5 million allocations and `BigInt` division.

**Comment by jmichel7** [comment]
I would argue that if bareiss make it to `LinearAlgebra`, the signature should not restrict the input to `<:Integer`, since the program works over any integral domain. For instance, it works fine for polynomials or any other ring where `Base.div` has been defined.
Another thing is that it would be very useful to have a function like `divide` in the post above. I needed a function like that (which I called `exactdiv` in my package `Gapjm` to be able to write code which works as well with elements of fields as elements of rings.
It is a pity that `div` has been given a meaning different from `divide` for the rationals so it cannot play this role.

**Comment by oscardssmith** [comment]
The problem with using this for other rings is that this will overflow for pretty much anything other than `BigInt` or `Rational{BigInt}`. Furthermore, `det` (like `inv`) is a function that should be avoided for real work, as it is inherently inefficient and has bad conditioning problems.

**Comment by jmichel7** [comment]
- This algorithm is not needed for `Rational`s or element of a field, the ordinary `det` algorithm works fine.
  -  I have used this algorithms in my package for determinants of matrices of polynomials, cyclotomics and other ring elements and it works fine (no overflows of the polynomial coefficients)

**Comment by jmichel7** [comment]
- This algorithm is not needed for `Rational`s or elements of a field, the ordinary `det` algorithm works fine.
  -  I have used this algorithm in my package for determinants of matrices of polynomials, cyclotomics and other ring elements and it works fine (no overflows of the polynomial coefficients)

**Comment by stevengj** [comment]
My suggestion would be to have a non-exported `LinearAlgebra.bareiss` function that accepts any element type, and calls something like `exactdiv(a,b)=a/b; exactdiv(a::Integer,b::Integer) = div(a,b)`.

Then define only `det(A::AbstractMatrix{BigInt}) = bareiss(A)`, but packages that define other ring types can define additional `det` methods as appropriate or call `bareiss` directly.

**Comment by stevengj** [comment]
(I checked, and the LU-based `det` seems to be faster than the `bareiss` algorithm for `Rational{BigInt}` matrices, so it's only for `AbstractMatrix{BigInt}` where we should default to the Bareiss method.)

**Comment by stevengj** [comment]
Marking as "good first issue" since you basically just need to take the code above modulo minor changes [as explained here](https://github.com/JuliaLang/julia/issues/40128#issuecomment-804275635) and add it to LinearAlgebra + tests.

**Comment by Pramodh-G** [comment]
Hi @stevengj , I'd like to work on this issue; but before I add the code, should [the above](https://github.com/JuliaLang/julia/issues/40128#issuecomment-803685287) code go to [generic.jl](https://github.com/JuliaLang/julia/blob/2435f96f92ebe8635fd3c43efc93c94cc0ed291a/stdlib/LinearAlgebra/src/generic.jl)? 

If not, It would be helpful to me if you could suggest which file it should go to.
Thanks!

**Comment by stevengj** [comment]
Yes, `generic.jl` seems as good a place as any for this.
