### ISSUE TITLE
Doc's PDF returns `404 error` 

### ISSUE THREAD

**Issue by ApolloDev0** [JuliaLang/julia#40123]
The link for the PDF version of the docs is broken and returns a 404 Error when i click it.
👇
[link to pdf docs](https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.5.4.pdf)

**Comment by oscardssmith** [comment]
What page links to this?

**Comment by zhangcx93** [comment]
https://docs.julialang.org/en/v1/

**Comment by ApolloDev0** [comment]
> What page links to this?

the link i sent goes to the "Supposed" pdf file, but i think it's broken but the origin of the error came from the docs website link

**Comment by felixcremer** [comment]
The PDFs are build and deployed here:
https://github.com/JuliaLang/docs.julialang.org/tree/assets 

It seems that there haven't been a build after tagging julia 1.5.4.

**Comment by fredrikekre** [comment]
GitHub disables workflows for repos that have been inactive for > 60 days. I have activated it again so should run within 24 hours (https://github.com/JuliaLang/docs.julialang.org/actions).
