### ISSUE TITLE
isstructype reports that an array is a struct

### ISSUE THREAD

**Issue by jplGitPractice** [JuliaLang/julia#40134]
From help on isstructype:

> isstructtype

  Determine whether type T was declared as a struct type (i.e. using the struct or mutable struct
  keyword).

So, I interpret this to mean that an array should produce "false" here...

julia> x = rand(2)
2-element Vector{Float64}:
 0.6912011923742296
 0.7180487686264916

julia> isstructtype(typeof(x))
true

I believe issue lies in reflection.jl, last line of isstructtype contains
an "or" statement with

t.size != 0 ...  but with t=typeof(x) above, we have t.size==0 ... this causes
an array to be reported "true" with isstructtype

**Comment by vtjnash** [comment]
It is a struct type (declared as `mutable struct Array{T,N}; end`), there just aren't any fields

**Comment by JeffBezanson** [comment]
Correct; for example one can imagine that `Array` is defined in julia (which it probably will be at some point), which would look like
```
mutable struct Array{T,N}
    buffer:...
    dims::...
    ...
end
```
so that is what `isstructtype` refers to. It's just a very low-level function; in fact every concrete type is either a struct type or a bits type.
