### ISSUE TITLE
Document `_` as an lvalue

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#40133]
These uses of `_` seem to be quite common, are they mentioned in the manual somewhere?
```julia
s, _ = size(x)
map(_ -> 1, x)
```
Perhaps:
* https://docs.julialang.org/en/v1/manual/variables/#Allowed-Variable-Names should mention that all-underscore names aren't valid variable names, but can be assigned to. 
* `help?> _` could print something helpful?

**Comment by stevengj** [comment]
Technically, `_` is valid as an [L-value](https://en.wikipedia.org/wiki/Value_(computer_science)#lrvalue) but not as an [R-value](https://en.wikipedia.org/wiki/R-value).

**Comment by Pramodh-G** [comment]
Hey @stevengj, does this still need documentation? I'm a first time contributor and I could take a shot at it!

**Comment by stevengj** [comment]
Yes.
