### ISSUE TITLE
Example in documentation of isless not showing properly

### ISSUE THREAD

**Issue by lucasondel** [JuliaLang/julia#40137]
Hello, 

The example in the documentation of the [isless function](https://docs.julialang.org/en/v1/base/base/#Base.isless) is not showing properly. Looking at the [docstring](https://github.com/JuliaLang/julia/blob/69fcb5745bda8a5588c089f7b65831787cffc366/base/operators.jl#L154) I think there is a column of extra space preventing the proper display of the sample code. 

If needed, I can make the fix myself.

**Comment by KristofferC** [comment]
> If needed, I can make the fix myself.

That would be great!

**Comment by lucasondel** [comment]
Ok, then I'll take care of it.

**Comment by lucasondel** [comment]
Oops, that was a duplicate of #37659 so everything is fixed. I suppose the change will take effect whenever there is a new release. I'm closing the issue.
