### ISSUE TITLE
Compile error if I use more than one of `USE_INTEL_JITEVENTS`, `USE_OPROFILE_JITEVENTS`, or `USE_PERF_JITEVENTS`

### ISSUE THREAD

**Issue by ali-ramadhan** [JuliaLang/julia#40146]
The [external profiling section](https://docs.julialang.org/en/v1.6.0-rc3/manual/profile/#External-Profiling) of the Julia manual says that multiple external profiling flags are supported but when I tried to compile Julia 1.6.0-rc3 with `USE_INTEL_JITEVENTS = 1` in my `Make.user` it failed to compile:

```
/home/alir/julia-1.6.0-rc3/src/init.c: In function ‘_julia_init’:
/home/alir/julia-1.6.0-rc3/src/init.c:705:17: error: redefinition of ‘jit_profiling’
     const char *jit_profiling = getenv("ENABLE_JITPROFILING");
                 ^~~~~~~~~~~~~
/home/alir/julia-1.6.0-rc3/src/init.c:691:17: note: previous definition of ‘jit_profiling’ was here
     const char *jit_profiling = getenv("ENABLE_JITPROFILING");
                 ^~~~~~~~~~~~~
```

It seems that you can only enable one of `USE_INTEL_JITEVENTS`, `USE_OPROFILE_JITEVENTS`, or `USE_PERF_JITEVENTS` since enabling any one of them tries to define a `const char *jit_profiling`:

https://github.com/JuliaLang/julia/blob/5945f4d659cc02f887602eaa281b1f2dd0cee263/src/init.c#L690-L709

On Linux it seems that `USE_PERF_JITEVENTS` is set by default so compiling will fail unless you explicitly disable it in `Make.user`:

https://github.com/JuliaLang/julia/blob/23267f0d4686d0566a07fe9cd681d414fc3a915b/Make.inc#L438-L442

It seems like either `init.c` should support enabling more than one of these flags, or the documentation should be updated to say that only one flag may be set (and that `USE_PERF_JITEVENTS=1` by default on Linux).

**Comment by vchuravy** [comment]
Attempted fix is/was #38741

**Comment by ali-ramadhan** [comment]
Ah thanks for the link, I missed that PR while searching.

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/38741
