### ISSUE TITLE
Add < for NamedTuple

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#40142]
I think we should add:

```
<(a::NamedTuple{n}, b::NamedTuple{n}) where {n} = Tuple(a) < Tuple(b)
```

as now we fall back to `isless` which means that comparing `NamedTuple`s with `missing` values does not produce `missing`, so the following happens:
```
julia> (a=1,b=missing) <= (a=1, b=missing)
missing

julia> (a=1,b=missing) < (a=1, b=missing)
false

julia> (a=1,b=missing) > (a=1, b=missing)
false

julia> (a=1,b=missing) >= (a=1, b=missing)
missing

julia> (a=1,b=missing) == (a=1, b=missing)
missing
```

This is probably for 2.0 release, but maybe it should be considered a bug?

**Comment by bkamins** [comment]
I am now fully convinced this should be classified as a bug because:
```
julia> (a=-0.0,) < (a=0.0,)
true

julia> (a=-0.0,) == (a=0.0,)
true
```

**Comment by Seelengrab** [comment]
The NamedTuple version simply calls `isless(Tuple(a), Tuple(b))`, right?

This ends up calling `isless(-0.0, 0.0)`, which is inconsistent with `<`:

```
1|julia> -0.0 < 0.0       
false                     
                          
1|julia> isless(-0.0, 0.0)
true                      
```

Should they be consistent?

**Comment by bkamins** [comment]
Yes - they should be made consistent. As shown above otherwise we have two objects `a` and `b` for which `a == b` and `a < b` is `true` which should happen.

The reason for this is that `<` by default falls back to `isless`. So if someone defines a custom `==` then a custom `<` should be also defined if `isless` if defined for some type.

**Comment by Seelengrab** [comment]
>  So if someone defines a custom == then a custom < should be also defined if isless if defined for some type.

The docstring for `==` doesn't mention `<` right now, same goes for the other way round. I'll open another issue to track this seperately, as it's not directly related to this but rather a doc change.

**Comment by bkamins** [comment]
I think the reason why `<` is not mentioned is that having `==` defined does not require you to define `<`.

Currently the documentation of `isless` states:

> Types with a partial order should implement `<`.

but probably this is not explicit enough.

Also the docstring of `<` currently seems to have some some random expression in the line https://github.com/JuliaLang/julia/blob/master/base/operators.jl#L322. I will propose the documentation changes in this PR.

**Comment by bkamins** [comment]
It only requires it if you also define `isequal` that is different from `==`, as by default `isequal` falls back to `==`. I have updated the #40147 to reflect this relationship.
