### ISSUE TITLE
eigvals(::SymTridiagonal) errors if off-diagonal has wrong length

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#40154]
The following errors. I can prepare a fix but I don't understand why `SymTridiagonal(randn(5), randn(5))` works: I would expect it to require a length `4` off-diagonal vector. The docs don't clarify anything...

```julia
julia> A = SymTridiagonal(randn(5), randn(5))
5×5 SymTridiagonal{Float64, Vector{Float64}}:
 1.54728  1.29122     ⋅          ⋅          ⋅ 
 1.29122  1.7491     0.820245    ⋅          ⋅ 
  ⋅       0.820245  -0.933958   0.816364    ⋅ 
  ⋅        ⋅         0.816364  -0.2896    -0.552447
  ⋅        ⋅          ⋅        -0.552447   0.669905

julia> eigvals(A)
ERROR: DimensionMismatch("ev has length 5 but needs one less than dv's length, 5)")
Stacktrace:
 [1] stev!(job::Char, dv::Vector{Float64}, ev::Vector{Float64})
   @ LinearAlgebra.LAPACK ~/Projects/julia-1.6/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lapack.jl:3774
 [2] eigvals!
   @ ~/Projects/julia-1.6/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/tridiag.jl:293 [inlined]
 [3] eigvals(A::SymTridiagonal{Float64, Vector{Float64}})
   @ LinearAlgebra ~/Projects/julia-1.6/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/tridiag.jl:294
 [4] top-level scope
   @ REPL[3]:1
```

**Comment by fredrikekre** [comment]
6b954c968c8800f67eb1ebd66d3aa67b658f55e4 864737320144549dca453fc3e9a977e5dc912091 for why `SymTridiagonal(randn(5), randn(5))` works (cc @andreasnoack).

**Comment by dlfivefifty** [comment]
Ha the issue was predicted: https://github.com/JuliaLang/julia/commit/6b954c968c8800f67eb1ebd66d3aa67b658f55e4#commitcomment-8013969

**Comment by andreasnoack** [comment]
I don't see why we should error in the call to `eigvals`. We should just ignore that last element.

**Comment by dlfivefifty** [comment]
Do you mean allow `ev` to have one extra entry in the `stev!` call, changing

https://github.com/JuliaLang/julia/blob/cc639ec7eadf3c8db1c6ae01ad0edbfdece1bc32/stdlib/LinearAlgebra/src/lapack.jl#L3774

That's an easy fix

**Comment by andreasnoack** [comment]
Yes exactly.
