### ISSUE TITLE
Set_zero_subnormals ineffective for Float16

### ISSUE THREAD

**Issue by milankl** [JuliaLang/julia#40151]
The [`set_zero_subnormals` function](https://github.com/JuliaLang/julia/blob/3071f34b16059ea7279c2af5694f902155d0806e/base/rounding.jl#L235) is working fine for `Float32/Float64` on x86 and ARM (aarch64) in Julia 1.6-rc3 but has no effect for `Float16`
```julia
julia> set_zero_subnormals(true)
true
julia> floatmin(Float64)/4
0.0
julia> floatmin(Float32)/4
0.0f0
julia> floatmin(Float16)/4
Float16(1.526e-5)
```
This is an issue as a64fx (tested on [Isambard](https://gw4.ac.uk/isambard/) and Fugaku) considerably slows down with subnormals:
```julia
julia> A = floatmin(Float16)*rand(Float16,1000,1000)
julia> B = floatmin(Float16)*rand(Float16,1000,1000)
julia> @btime +($A,$B);
  7.116 ms (2 allocations: 1.91 MiB)
```
compared to computations without subnormals
```julia
julia> A = rand(Float16,1000,1000)
julia> B = rand(Float16,1000,1000)
julia> @btime +($A,$B);
  274.681 μs (2 allocations: 1.91 MiB)
```

(@vchuravy I believe you've switched julia's Float16 to LLVM's half for 1.6?) @samhatfield

**Comment by vchuravy** [comment]
Switching to Float16 was a joint effort with @maleadt 

Can you post the `code_llvm` on A64fx?

**Comment by milankl** [comment]
@vchuravy was right, official arm builds convert Float16 to Float32 for arithmetics. A solution is proposed in #40216. Nevertheless the subnormal issue persits:

Without subnormals
```julia
julia> a,b = rand(Float16,100_000),rand(Float16,100_000);

julia> @btime +($a,$b);
  24.740 μs (2 allocations: 195.39 KiB)

**Comment by vchuravy** [comment]
Couple notes:
1. `set_zero_subnormals` is implemented here https://github.com/JuliaLang/julia/blob/514426d3fd2723c6ddfc33444bfc23891c55454d/src/processor_arm.cpp#L1833-L1839
2. Instead of manually changing the processor flag we should set the LLVM function attribute: `denormal-fp-math`, for that it would be great to have a generic function attribute interface like `Expr(:loopinfo)`.

**Comment by milankl** [comment]
I'd be happy to test if changing manually the processor flag actually flushes subnormals to zero on a64fx, but I don't know how to do this. So if someone posts this here, then I'd be happy to build julia on an a64fx and test it.

**Comment by vchuravy** [comment]
Looking at: https://developer.arm.com/documentation/100403/0201/register-descriptions/advanced-simd-and-floating-point-registers/aarch64-register-descriptions/fpcr--floating-point-control-register

There seems to be a second control register for fp16 flush to zero. PR incoming
