### ISSUE TITLE
Inconsistent results between sparse and dense matrix-vector multiplication

### ISSUE THREAD

**Issue by lucasondel** [JuliaLang/julia#40157]
Hello! 

I'm implementing an algorithm that operates in a specific [semi-field](https://en.wikipedia.org/wiki/Semifield) different from the natural one. Practically, I am using the idea in [this post](https://discourse.julialang.org/t/sparse-with-default-value-inf/35110/8). The problem is that matrix-vector multiplication gives different results  wether I use sparse or dense matrix. 

Here is an example:
```julia
julia> b = MarkovModels.LogSemifield{Float64}[0.0, -Inf, -Inf]
3-element Array{MarkovModels.Semifield{Float64,StatsFuns.logaddexp,+,-,-Inf,0.0},1}:
  0.0
 -Inf
 -Inf

# Sparse matrix in the LogSemifield 
julia> A # A is already defined
3×3 SparseMatrixCSC{MarkovModels.Semifield{Float64,StatsFuns.logaddexp,+,-,-Inf,0.0},Int64} with 5 stored entries:
  [1, 1]  =  -0.693147
  [3, 1]  =  -0.693147
  [2, 2]  =  -0.693147
  [2, 3]  =  -0.693147
  [3, 3]  =  -0.693147

# Dense form:
julia> Matrix(A)
3×3 Array{MarkovModels.Semifield{Float64,StatsFuns.logaddexp,+,-,-Inf,0.0},2}:
 -0.693147       -Inf       -Inf
      -Inf  -0.693147  -0.693147
 -0.693147       -Inf  -0.693147

# Dense matrix-vector multiplication (the results is what I want to obtain so everything is good)
julia> Matrix(cfsm.A) * b
3-element Array{MarkovModels.Semifield{Float64,StatsFuns.logaddexp,+,-,-Inf,0.0},1}:
 -0.6931471805599453
                -Inf
 -0.6931471805599453

# Sparse matrix-vector multiplication:
julia> A * b
3-element Array{MarkovModels.Semifield{Float64,StatsFuns.logaddexp,+,-,-Inf,0.0},1}:
 0.3068528194400547
               -Inf
 0.3068528194400547
```

After investigation I found that the issue comes from [here](https://github.com/JuliaLang/julia/blob/master/stdlib/SparseArrays/src/linalg.jl#L51) and [here](https://github.com/JuliaLang/julia/blob/master/stdlib/SparseArrays/src/linalg.jl#L36). Internally, `alpha` and `beta` arguments given to the `mul!` function are not of the defined type `MarkovModels.LogSemifield` but hard-coded numerical values. 

I think the problem could be avoided if instead of passing `true` and `false` to `mul!` we pass `one(T)` and `zero(T)` and changing `mul!` accordingly.

If what I am proposing sounds reasonable I'll be happy to volunteer to make the change.

**Comment by eschnett** [comment]
This seems reasonable to me (I'm not a maintainer and can't approve pull requests).

One important thing – make sure that the case where these arguments are not there are still handled efficiently by the compiler, i.e. that the respective operations `false + x` or `true * x` are optimized away and don't lead to additional operations.

**Comment by lucasondel** [comment]
Thanks for your feedback. I'll try to  get it working and let's see if the PR will be accepted.

**Comment by MartinKocour** [comment]
Any update on this issue?

**Comment by lucasondel** [comment]
I overestimated my disponibility and I didn't have time to address this issue so I don't think anything as changed. 

I have noticed that the SparseArrays package has been relocated to a separate repository: https://github.com/JuliaSparse/SparseArrays.jl.  

I will close this issue here because it does not depends  of this repository anymore and re-open it on the SparseArrays.jl
