### ISSUE TITLE
show fails on the transpose of a rational matrix

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#40168]
In the [DescriptorSystems](https://github.com/andreasvarga/DescriptorSystems.jl) package I defined a new object: the _rational transfer function_, which basically contains the numerator and denominator polynomials of a rational function and additionally a constant (representing a sampling time). Using this object, it is possible to define matrices with elements rational transfer functions. For example, such a matrix can be obtained using the following sequence 

```
using DescriptorSystems
z = rtf('z');
G = [z^2 z/(z-2); 0 1/z];
show(G)
```

where the last line produces
```
julia> show(G)
RationalTransferFunction{Int64,:z}[RationalTransferFunction{Int64,:z}(Polynomials.Polynomial(z^2), Polynomials.Polynomial(1), -1) RationalTransferFunction{Int64,:z}(Polynomials.Polynomial(z), Polynomials.Polynomial(-2 + z), -1); RationalTransferFunction{Int64,:z}(Polynomials.Polynomial(0), Polynomials.Polynomial(1), -1) RationalTransferFunction{Int64,:z}(Polynomials.Polynomial(1), Polynomials.Polynomial(z), -1)]
```
However `show` is not able to produce the string which corresponds to the transposed matrix `G` and exits with the following error
```
julia> show(transpose(G))
Union{}[ERROR: MethodError: no method matching transpose(::RationalTransferFunction{Int64,:z})
Closest candidates are:
  transpose(::Missing) at missing.jl:100
  transpose(::Number) at number.jl:168
  transpose(::LinearAlgebra.Transpose) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\adjtrans.jl:165     
  ...
Stacktrace:
 [1] getindex at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\adjtrans.jl:190 [inlined]
 [2] isassigned(::LinearAlgebra.Transpose{Union{},Array{RationalTransferFunction{Int64,:z},2}}, ::Int64, ::Int64) at .\abstractarray.jl:408        
 [3] _show_nonempty(::IOContext{Base.TTY}, ::LinearAlgebra.Transpose{Union{},Array{RationalTransferFunction{Int64,:z},2}}, ::String) at .\arrayshow.jl:396
 [4] show(::Base.TTY, ::LinearAlgebra.Transpose{Union{},Array{RationalTransferFunction{Int64,:z},2}}) at .\arrayshow.jl:437
 [5] show(::LinearAlgebra.Transpose{Union{},Array{RationalTransferFunction{Int64,:z},2}}) at .\show.jl:386
```

The transpose is correctly formed, since 
```
julia> transpose(transpose(G)) == G
true
```
`show` works correctly on the transpose of a polynomial matrix, as constructed using the[ Polynomials](https://github.com/JuliaMath/Polynomials.jl) package, so I assume it should produce a similar output for a rational matrix as well.

**Comment by mbauman** [comment]
You just need to define `transpose(::RationalTransferFunction{Int64,:z})` in your package? That's why Polynomials [works](https://github.com/JuliaMath/Polynomials.jl/blob/4f7c5662218e1a2a79980c0891204665c132d0a0/src/common.jl#L417). `transpose` is a linear algebraic operation and is recursive, calling it on all the elements.  If you just want to treat the array like a box and swap its dimensions, use `permutedims`.

**Comment by andreasvarga** [comment]
Thanks, very helpful!
