### ISSUE TITLE
`prod()` over zero-length tuple generator should just return `1`?

### ISSUE THREAD

**Issue by davidavdav** [JuliaLang/julia#40160]
Hello, 

This might be related to #28028, #36262 and similar issues. 

Observing the following statements:
```julia
## These all work as expected
julia> collect(i for i in Int[]) == Int[]
true
julia> sum(i for i in Int[]) == 0
true
julia> prod(i for i in Int[]) == 1
true
julia> collect(i for (i, j) in zip(Int[], Int[])) == Int[]
true
## but here I would expect result `1`
julia> prod(i for (i, j) in zip(Int[], Int[]))
ERROR: ArgumentError: reducing over an empty collection is not allowed
...
```
I can't really say where this goes wrong, whether it is in the zip generator or in the reduction in `prod()`. 

The following "identity" function `id(n)` evaluates for all integers except 1:
```julia
import Primes
id(n::Integer) = prod(prime^power for (prime, power) in Primes.factor(n))
```
Of course such functions could check for cases where `n==1` but that is somewhat clumsy, I think.  My actual use is in a function computing the sum of the divisors of a positive natural number:
```julia
sigma(n::Integer) = prod((prime ^ (power + 1 ) - 1 ) ÷ (prime - 1) for (prime, power) in Primes.factor(n))
sigma(28) == 2 * 28
sigma(1)
ERROR: ArgumentError: reducing over an empty collection is not allowed
```

**Comment by JeffBezanson** [comment]
The difficulty with this is that without any elements, we don't know what the domain is, so we don't know if `1` is the correct identity element.

(We have `prod(()) == 1` but it's a legacy thing that's not ideal.)

**Comment by davidavdav** [comment]
Is `prod(())` what `prod(i for i in Int[])` in the end evaluates to?   I can imagine it is difficult to deduce the type of the argument from an empty generator expression, but julia is still able to do this for the non-tuple cases
```julia
prod(i for i in Int[]) === 1
prod(i for i in Float64[]) === 1.0
```
but tuples start to make a difference between `collect` and `prod`
```julia
collect(i for (i,j) in NTuple{2, Int}[]) == Int[]
collect(j for (i,j) in Tuple{Int, Float64}[]) == Float64[]
prod(i for (i,j) in NTuple{2, Int}[]) ## Error
```

Thanks, anyways, I can definitely live with the current behavior, I just wondered if this is intended or just hard to solve case.

**Comment by StefanKarpinski** [comment]
For products and sums, I feel like using `true` and `false` as "weak" identities would be ok, but it's a fairly big decision. And even if it works computationally, people will be surprised and complain about it, so 🤷🏻‍♂️

**Comment by JeffBezanson** [comment]
> Is `prod(())` what `prod(i for i in Int[])` in the end evaluates to?

Not exactly, we just have some special cases for the `identity` function, allowing `i for i in ...` to work.

**Comment by vtjnash** [comment]
similar to https://github.com/JuliaLang/julia/issues/36262 we have `init` now for this. See also triage's rationale at https://github.com/JuliaLang/julia/pull/29919#issuecomment-973252990
