### ISSUE TITLE
Anonymous or temporary module syntax

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#40189]
Use case: tests including and running a bunch of script-like files like examples.

The easiest (only?) way to have each file in its own namespace and avoid leaks is to put each one in a separate module.
One could `@eval` to give them random names, but it would be better to have either:
```julia
# anonymous modules
module
f() = ...
v = 3
end
# alternative anonymous modules
module _
f() = ...
v = 3
end

# throw-away name
module @__tempmodule__
f() = ...
v = 3
end
```

**Comment by matbesancon** [comment]
The idea is a bit related to https://github.com/YingboMa/SafeTestsets.jl

**Comment by StefanKarpinski** [comment]
Does this qualify:
```jl
@eval Module() begin
    # put code here
end
```
Using an `_` for the module name does seem like a cute syntax which would presumably do this.

**Comment by matbesancon** [comment]
just to be sure, does the current snippet work on the current version?

**Comment by StefanKarpinski** [comment]
Yes:
```jl
julia> @eval Module() begin
           x = 123
           @show(x)
           @__MODULE__
       end
x = 123
Main.anonymous

julia> x
ERROR: UndefVarError: x not defined
```
Is that what you meant?

**Comment by matbesancon** [comment]
Indeed this fits my use case. For anyone finding this later, this requires interpolating even the builtin functions:
```julia
for file  in example_files
    @eval Module() begin
        $include($file)
    end
end
```

**Comment by matbesancon** [comment]
on another note: this did not as planned separate the namespaces and needed extra tweaking: 

```julia
s1 = """
const xp = 3
"""

s2 = """
const xp = [3]
"""

for s in [s1,s2]
    @eval Module() begin
        $include_string($@__MODULE__, $s)
    end
end
```

This however does not work if one of the inner scripts contains an include

Furthermore, I didn't manage to make this work with standard include

**Comment by matbesancon** [comment]
The use case I had was a bunch of files that need to be run in isolated namespaces, so each module would be:
```julia
@eval Module() begin
    $include($myfile)
end
```

**Comment by fredrikekre** [comment]
See https://github.com/JuliaDocs/Documenter.jl/blob/c942201b745abbdf155c880e1231cb8240507b41/src/Utilities/Utilities.jl#L677-L678

You probably don't want to interpolate the `include` function, since you will then include to the wrong module (the module which the interpolated `include` function belongs to):
```
shell> cat test.jl
println("hello from module ", @__MODULE__)

julia> @eval Module() begin
           $include("test.jl")
       end
hello from module Main

julia> @eval Module() begin
           Base.include(@__MODULE__, "test.jl")
       end
hello from module Main.anonymous
```
