### ISSUE TITLE
1.6 gets stuck on ] add Plots

### ISSUE THREAD

**Issue by ghost** [JuliaLang/julia#40193]
It takes a lot of time to clone the https://github.com/JuliaRegistries/General.git. 

Then, after that, it seems to get stuck at: 

```
  Installed IniFile ────────────────────── v0.5.0
   Installed Formatting ─────────────────── v0.4.2
   Installed GeometryBasics ─────────────── v0.3.11
   Installed Gettext_jll ────────────────── v0.20.1+7
   Installed Xorg_libxcb_jll ────────────── v1.13.0+3
   Installed Libgcrypt_jll ──────────────── v1.8.5+4
   Installed StaticArrays ───────────────── v1.0.1
   Installed Xorg_xkbcomp_jll ───────────── v1.4.2+4
   Installed Adapt ──────────────────────── v3.2.0
   Installed XSLT_jll ───────────────────── v1.1.33+4
   Installed Zstd_jll ───────────────────── v1.4.8+0
   Installed Xorg_libXfixes_jll ─────────── v5.0.3+4
   Installed Xorg_xkeyboard_config_jll ──── v2.27.0+4
   Installed Contour ────────────────────── v0.5.7
   Installed Colors ─────────────────────── v0.12.6
```

And finally, 
```
ERROR: Unexpected end of data : jl_LrPqJa9nfhAWgbfV~>]  107/109
┌ Warning: failed to extract archive downloaded from https://pkg.julialang.org/package/35d6a980-a343-548e-a6ea-1d62b119f2f4/3141757b5832ee7a0386db87997ee5a23ff20f4d
└ @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:590
```

I don't know what to expect, if it is normal for the cloning step to take this long (much longer than just doing a git clone). 

I haven't tried to figure out why the pkg add failed. 

At this step, I'm not particularly inclined to _try again until it works_. 

I'll add more information if necessary. 

@StefanKarpinski You asked me to open this issue ...

Edit: 

I thought the installer had just ended, but after a few minutes it continued spitting things: 

```
Installed GR ─────────────────────────── v0.55.0
   Installed ColorSchemes ───────────────── v3.10.2
 Downloading artifact: GR
    Downloading [====>                                    ]  9.6 %
```

At this point I closed the terminal window.

**Comment by phgmacedo** [comment]
Git cloning the JuliaRegistries/General.git seems to be much faster, though it is still slow:

```
PS C:\Users\phg> git clone https://github.com/JuliaRegistries/General.git
Cloning into 'General'...
remote: Enumerating objects: 391, done.
remote: Counting objects: 100% (391/391), done.
remote: Compressing objects: 100% (275/275), done.
remote: Total 415057 (delta 132), reused 311 (delta 109), pack-reused 414666 eceReceiving objects: 100% (415057/415057), 125.56 MiB | 131.00 KiB/s, done.

Resolving deltas: 100% (231882/231882), done.
Updating files: 100% (21211/21211), done.
PS C:\Users\phg>
```

I don't know if it's related to my location.

**Comment by fredrikekre** [comment]
libgit2 operations are for some reason very slow on Windows. As a workaround you can `git clone` it to the expected location directly.

**Comment by phgmacedo** [comment]
> libgit2 operations are for some reason very slow on Windows. As a workaround you can `git clone` it to the expected location directly.

I'm not in a rush to use Julia. I can happily wait until this gets sorted out.

**Comment by StefanKarpinski** [comment]
Thank you for filing an issue with details. Sorry for the difficulty.

**Comment by ViralBShah** [comment]
Please reopen if this is still an issue.
