### ISSUE TITLE
Outer variable shadowed when defining a function inside a `for` loop

### ISSUE THREAD

**Issue by banx** [JuliaLang/julia#40197]
Consider the following code block
```julia
begin
	h = 0
	s = 2
	for i in 1:10
		y(t) = t^s+i
		h += 1
	end
	h
end
```
Upon execution, the interpreter spits the following error: `UndefVarError: h not defined`
Regardless of what is the function, the error persists (e.g. defining `y(t) = 0` will results with the same error). Using the short form or with `function` keyword gives the same error.
Of course, the expected execution in this example should give a result `h = 10`.

**Comment by KristofferC** [comment]
You need to use `global` if you want to reassign a global variable. See https://docs.julialang.org/en/v1/manual/variables-and-scoping/#On-Soft-Scope. Also, note that warning:

```
julia> include("foo.jl")
┌ Warning: Assignment to `h` in soft scope is ambiguous because a global variable by the same name exists: `h` will be treated as a new local. Disambiguate by using `local h` to suppress this warning or `global h` to assign to the existing global variable.
└ @ ~/julia/foo.jl:6
ERROR: LoadError: UndefVarError: h not defined
```

Pasting this in the REPL will work though (see the discussion in the manual about it).

**Comment by banx** [comment]
What's bothering me in this approach is that it increases ambiguity instead of readability.
Why would the interpreter fires *only* a warning when the function definition is absent, whereas it raises an error when it is present, knowing that it didn't interact with the outer variable at all? Shouldn't it be more consistent?
Moreover, the use of the `local` and `global` keyword will turn pointless when dealing with 3 nested scopes, where the innermost scope tries to access the variable in the middle scope.

**Comment by KristofferC** [comment]
>  Why would the interpreter fires only a warning when the function definition is absent, whereas it raises an error when it is present, knowing that it didn't interact with the outer variable at all? Shouldn't it be more consistent?

I get an error if the function definition is there or not.

**Comment by banx** [comment]
> I get an error if the function definition is there or not.

Sorry, I should've mentioned earlier that I was trying this code in **Pluto**. I get an error there when the function is defined, but no error when it is absent!

**Comment by KristofferC** [comment]
Well, in the Julia REPL I get no error and when I put it in a file I get an error no matter if `y` is there or not. If Pluto does differently then it does indeed look like an issue there.

**Comment by banx** [comment]
> If Pluto does it differently then it does indeed look like an issue there.
I [opened this issue](https://github.com/fonsp/Pluto.jl/issues/1031) in [Pluto.jl](https://github.com/fonsp/Pluto.jl)
Would you help me understand the rationale behind the different outcomes between the REPL, and having the code in a separate file?

**Comment by KristofferC** [comment]
See the end of the section here https://docs.julialang.org/en/v1/manual/variables-and-scoping/#On-Soft-Scope

**Comment by KristofferC** [comment]
I will close this since it no longer seems to be about a Julia issue. Further discussion of Julia's scope rules can be had at https://discourse.julialang.org/.
