### ISSUE TITLE
v1.6.0 doc pdf missing

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#40190]
The link on the top of the manual points to a [404](https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.6.0.pdf).

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/docs.julialang.org/runs/2196972845?check_suite_focus=true

**Comment by mbauman** [comment]
Thanks! 404 no more.
