### ISSUE TITLE
Missing symlink in /usr/lib/julia when using system openblas

### ISSUE THREAD

**Issue by antonio-rojas** [JuliaLang/julia#40202]
When using some system library, the build system generally adds a symlink from lib/julia, but that's not the case for libopenblas64_.so (which is hardcoded in OpenBLAS_jll). Only a libblas.so symlink is created.

**Comment by ViralBShah** [comment]
This is completely overhauled with LBT. Please reopen if still relevant.

**Comment by antonio-rojas** [comment]
So IIRC, every package that tries to open libopenblas64_.so should be told to use LBT instead?

**Comment by ViralBShah** [comment]
Yes, we want to move towards that model - and that way users can then pick the BLAS and LAPACK of their choice.
