### ISSUE TITLE
Julia 1.6 compiler crash on OSX

### ISSUE THREAD

**Issue by thisrod** [JuliaLang/julia#40200]
It looks like something went wrong with linking the Julia 1.6 release.  I'm not sure how to reduce this to a minimal example.

I'm on OSX version 10.10.3, which is ancient; if this doesn't reproduce on more recent OSXs, the answer might be for me to get a newer machine.

The method redefinition in `DifferentialEquations` is a long standing error, and seems harmless.

       _       _ _(_)_     |  Documentation: https://docs.julialang.org
      (_)     | (_) (_)    |
       _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
     _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
    |__/                   |
    
    julia> cd(mktempdir())
    
    julia> using Pkg
    
    julia> Pkg.activate(".")
      Activating new environment at `/private/var/folders/n6/wzhrxrfj7dddk08cp3l4jp_80000gn/T/jl_Gxa7wT/Project.toml`
    
    julia> Pkg.add("Superfluids")
    ...
    
    
    julia> using Superfluids
    [ Info: Precompiling Superfluids [01347403-e5cf-4a60-9350-9edf4e6960f2]
    WARNING: Method definition *(Number, SciMLBase.AbstractDiffEqLinearOperator{T}) where {T} in module SciMLBase at /Users/rpolkinghorne/.julia/packages/SciMLBase/4HgSI/src/operators/common_defaults.jl:15 overwritten in module DiffEqOperators at /Users/rpolkinghorne/.julia/packages/DiffEqOperators/5mEx8/src/composite_operators.jl:20.
      ** incremental compilation may be fatally broken for this module **
    
    JIT session error: Symbols not found: [ ___extendhfsf2, ___truncsfhf2 ]
    Failure value returned from cantFail wrapped call
    Failed to materialize symbols: { (JuliaOJIT, { _jfptr_collect_to_with_first!_45, _julia_collect_to_with_first!_44 }) }
    UNREACHABLE executed at /Users/julia/buildbot/worker/package_macos64/build/usr/include/llvm/Support/Error.h:749!
    
    signal (6): Abort trap: 6
    in expression starting at /Users/rpolkinghorne/.julia/packages/Parsers/rIikS/src/floats.jl:385
    __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
    Allocations: 2649 (Pool: 2640; Big: 9); GC: 0
    ERROR: LoadError: LoadError: Failed to precompile Parsers [69de0a69-1ddd-5017-9359-2bf0b02dc9f0] to /Users/rpolkinghorne/.julia/compiled/v1.6/Parsers/jl_nfYama.
    ...

**Comment by felipenoris** [comment]
I couldn't reproduce this on macOS 10.14.6 (Mojave).

**Comment by ViralBShah** [comment]
Reopen if still an issue.
