### ISSUE TITLE
Julia 1.6 odd behaviour on parametric types

### ISSUE THREAD

**Issue by Deduction42** [JuliaLang/julia#40219]
I defined a parametric type for myself
```
mutable struct ProcessStream{T} <: AbstractConnector{T}
    id :: Symbol
    subclass :: DataType
    temperature :: T
    pressure  :: T
    components :: Vector{T}
    specs :: StreamSpecs
end
```
In Julia 1.5.4 and earlier, I could define ProcessStream{:T} to get symbol values of {:T}
```
fieldtypes(ProcessStream{:T})
(Symbol, DataType, :T, :T, Vector{:T}, StreamSpecs)
```
This was useful in metaprogramming. Now in Julia 1.6.0 however, I'm getting
```
fieldtypes(ProcessStream{:T})
(Symbol, DataType, Union{}, Union{}, Vector{:T}, StreamSpecs)
```
Is there any particular reason why this is happening? Is there another way that I'm supposed to generate expression pairs of an arbitrary ProcessStream that allow me to replace "T" with any symbol of my choosing?

**Comment by Deduction42** [comment]
So after digging through UnionAll types, it looks like you're supposed to put a TypeVar inside a parametric type to get back what you want. So going that route produces something I can work with
```
typevar(x::Symbol) = TypeVar(x, Union{}, Any)
fieldtypes( ProcessStream{typevar(:X)} )
(Symbol, DataType, X, X, Array{X, 1}, StreamSpecs)
```
Since this isn't broken, I'm sure that this is probably more the intended route I should go. However, I'm not sure if the change in behavior I mentioned in the opening statement was a bugfix or something breaking.

**Comment by JeffBezanson** [comment]
We changed this to the empty type (`Union{}`) since there can't be any value whose type is a Symbol. If the TypeVar workaround is sufficient I'll consider this closed.

**Comment by Deduction42** [comment]
I'd call it closed. I think it breaks something that was never meant to work in the first place. Using TypeVar not only fixed my problem, it eliminated a few other workarounds I had to do in order to make it work. I only wished I learned about it sooner.
