### ISSUE TITLE
New bug (wrong behavior) in regex (script) properties in Julia 1.6

### ISSUE THREAD

**Issue by BenjaminGalliot** [JuliaLang/julia#40231]
Hello.

It seems the latest Julia release (nice job, by the way!) introduced a bug for regex properties, especially with scripts…

```julia
text = "aa bb"
text |> collect
# 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
# 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
# ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
# 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
# 'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

pattern = r"\p{Ll}+"
eachmatch(pattern, text) |> collect
# Good : 2-element Vector{RegexMatch}: RegexMatch("aa") RegexMatch("bb")

pattern = r"[\p{Ll}\p{Zs}]+"
eachmatch(pattern, text) |> collect
# Good : 1-element Vector{RegexMatch}: RegexMatch("aa bb")

text = "壹貳 叁"
text |> collect
# '壹': Unicode U+58F9 (category Lo: Letter, other)
# '貳': Unicode U+8CB3 (category Lo: Letter, other)
# ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
# '叁': Unicode U+53C1 (category Lo: Letter, other)

pattern = r"[\p{Han}]+"
eachmatch(pattern, text) |> collect
# Good 2-element Vector{RegexMatch}: RegexMatch("壹貳") RegexMatch("叁")

pattern = r"[\p{Han}\p{Zs}]+"
eachmatch(pattern, text) |> collect
# Good on Julia 1.5 and 1.7 dev: 1-element Vector{RegexMatch}: RegexMatch("壹貳 叁")
# Bad on Julia 1.6: 2-element Vector{RegexMatch}: RegexMatch("壹貳") RegexMatch("叁")

pattern = r"[\p{Han} ]+"
eachmatch(pattern, text) |> collect
# Good: 1-element Vector{RegexMatch}: RegexMatch("壹貳 叁")

text = "カ メ"
text |> collect
# 'カ': Unicode U+30AB (category Lo: Letter, other)
# ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
# 'メ': Unicode U+30E1 (category Lo: Letter, other)

pattern = r"[\p{L}\p{Zs}]+"
eachmatch(pattern, text) |> collect
# Good: 1-element Vector{RegexMatch}: RegexMatch("カ メ")

pattern = r"[\p{Katakana} ]+"
eachmatch(pattern, text) |> collect
# Good: 1-element Vector{RegexMatch}: RegexMatch("カ メ")

pattern = r"[\p{Katakana}\s]+"
eachmatch(pattern, text) |> collect
# Good on Julia 1.5 and 1.7 dev: 1-element Vector{RegexMatch}: RegexMatch("カ メ")
# Bad on Julia 1.6: 2-element Vector{RegexMatch}: RegexMatch("カ") RegexMatch("メ")

pattern = r"[\p{Katakana}\p{Zs}]+"
eachmatch(pattern, text) |> collect
# Good on Julia 1.5 and 1.7 dev: 1-element Vector{RegexMatch}: RegexMatch("カ メ")
# Bad on Julia 1.6: 2-element Vector{RegexMatch}: RegexMatch("カ") RegexMatch("メ")
```
The Letter property works fine, but the script properties (like Han, Katakana, etc.) have a hard time mixed with Spaces property, contrary to the simple space character…

It seems it comes from Julia, not from PCRE2, because using directly [PCRE2](https://www.pcre.org/current/doc/html/pcre2syntax.html) 10.35 (the same version Julia 1.6 seems to use) works fine:

```bash
PCRE2 version 10.35 2020-05-09
  re> "[\p{Ll}\p{Zs}]+"
data> "aa bb"
 0: aa bb

PCRE2 version 10.35 2020-05-09
  re> "(*UTF)[\p{Han}\p{Zs}]+"
data> "壹貳 叁"
 0: \x{58f9}\x{8cb3} \x{53c1}
data> "(*UTF)壹貳 叁"
 0: \x{58f9}\x{8cb3} \x{53c1}
```

I struggle to understand where this problem comes from (which commit), but I am glad it works well on Julia 1.7 (at least for the moment). I did not find if this problem was found and fixed directly on the Julia repository (or if it was solved indirectly…).

Even if it works on 1.7 (master), it is a real breaking change as it can generate bugs on preexisting codes after the upgrade to 1.6, because this behavior is wrong and unexpected.

Understanding what is/was the problem could allow a more accurate set of tests to prevent a future similar breaking change…

Sincerely.

[Discourse link](https://discourse.julialang.org/t/did-julia-1-6-introduced-a-regression-for-regex-properties/58076).

**Comment by simonbyrne** [comment]
This might be fixed by backporting #39310, which upgraded PCRE from 10.35 (used on 1.6) to 10.36 (used on master)?

**Comment by BenjaminGalliot** [comment]
These numbers (3 and 7) seem to be the last code units of the matches (these kanas are 3 code units each).

```julia
str = "カ メ"
str |> eachindex |> collect
# 3-element Vector{Int64}: 1 4 5
str |> ncodeunits
# 7
```
If in Julia 1.5 and 1.7 it shows 7 (last code unit of the full string), it confirms it works (one match), but in Julia 1.6, it shows 3, which is the last code unit of the first character (it is the first match of the string), it also confirms it is wrong…

I don’t know if upgrading to PCRE2 10.36 would solve it, because in Julia 1.6, we already have a unexpected behavior compared to PCRE2 10.35, but it can help us if to understand…

**Comment by KristofferC** [comment]
A bisect would probably pinpoint this if someone is up for it.

**Comment by simonbyrne** [comment]
Backporting #39310 does fix the issue: i'll tag it for the next patch release. Not sure why it doesn't show up in the PCRE REPL: it might be a bug in the C API?

**Comment by BenjaminGalliot** [comment]
I did not manage to do the `git bisect`, I am not used enough to this tool on a big project with many so branches…

I can just say that it seems the first beta of v1.6 (commit b84990e1acee72ea3c3b05487996f9bb8be0db2f, PR #39120) seemed to already have this bug. Same for the commit 9528ac2785f214cdc188a835deed3d93e0b012c6 (PR #38655).


```julia                            
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-beta1 (2021-01-08)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> eachmatch(r"[\p{Han}\p{Zs}]+", "壹貳 叁") |> collect
2-element Vector{RegexMatch}:
 RegexMatch("壹貳")
 RegexMatch("叁")

julia> VERSION
v"1.6.0-beta1"

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1640 (2020-12-02)
 _/ |\__'_|_|_|\__'_|  |  Commit 9528ac2785* (118 days old master)
|__/                   |

julia> eachmatch(r"[\p{Han}\p{Zs}]+", "壹貳 叁") |> collect
2-element Vector{RegexMatch}:
 RegexMatch("壹貳")
 RegexMatch("叁")

julia> VERSION
v"1.6.0-DEV.1640"
```

And I just tried the C API and it also seems to work:

```bash
➜  pcre2-10.35 cc -Wall src/pcre2demo.c -lpcre2-8 -o pcre2demo
➜  pcre2-10.35 ./pcre2demo "(*UTF)[\p{Han}\p{Zs}]+" "壹貳 叁"
Match succeeded at offset 0
 0: 壹貳 叁
No named substrings
```

**Comment by AnAverageHuman** [comment]
Bisect says 2eccd8e086ba1b08dd8b4d04e86b548fcf8ec5e5 is the first bad commit. This commit upgraded PCRE from 10.31 to 10.35. The changelog for 10.36 says
> Fixed a bug in character set matching when JIT is enabled and both unicode scripts and unicode classes are present at the same time."

Maybe that was the issue?

**Comment by BenjaminGalliot** [comment]
Hello!

I have seen this changelog message 2 days ago and I thought it could be related, but I did not take time to go further (the bisect was really too annoying, one day I should learn it better…).

Your present message made me think I could check again this PCRE script:

```bash
➜  pcre2-10.35 export CFLAGS='-mshstk' && ./configure --enable-unicode --enable-jit --enable-pcre2-16 --enable-pcre2-32 --disable-static && make
[…]

➜  pcre2-10.35 ./pcre2test                                    
PCRE2 version 10.35 2020-05-09
  re> "(*UTF)[\p{Han}\p{Zs}]+"
data> "壹貳 叁"
 0: \x{58f9}\x{8cb3} \x{53c1}

➜  pcre2-10.35 ./pcre2test -C jit
1

➜  pcre2-10.35 ./pcre2test -jit  
PCRE2 version 10.35 2020-05-09
  re> "(*UTF)[\p{Han}\p{Zs}]+"
data> "壹貳 叁"
 0: \x{58f9}\x{8cb3}
data> 
  re> "(*UTF)[\p{Han} ]+"
data> "壹貳 叁"
 0: \x{58f9}\x{8cb3} \x{53c1}
data>
  re> "(*UTF)[\p{Latin}\p{Zs}]+"
data> "Ça alors !"
 0: \x{c7}a
data> 
  re> "(*UTF)[\p{Latin} ]+"
data> "Ça alors !"
 0: \x{c7}a alors 
data> 
  re> "(*UTF)[\p{L}\p{Zs}]+"
data> "Ça alors !"
 0: \x{c7}a alors 
```

I could say this is what they were talking about in changelog! The mystery is solved, thank you for this bisect!
