### ISSUE TITLE
`make USE_BINARYBUILDER_CSL=0` fails with static libraries

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#40234]
To build software that requires recent compilers on Centos/RHEL 7, it is common to use the devtoolset. These are packages that provide newer toolchains, and that are only used at build time: since users are not supposed to install them to run the compiled executables, they only provide static libraries. It turns out that since Julia 1.6, this makes the build fail when `USE_BINARYBUILDER_CSL=0`, as the build process looks for dynamic .so libraries, and since they are not found it ends up using the "standard" system libraries, which are too old and do not match the compiler that is used. I could confirm that usr/bin/libstdc++.so.6 and similar files are copied from /lib64. This used to work fine in Julia 1.5.

```
. /opt/rh/devtoolset-9/enable # This modifies PATH to ensure newer toolchain is used
make USE_BINARYBUILDER_CSL=0
[...]
    JULIA usr/lib/julia/corecompiler.ji
ERROR: Unable to load dependent library /home/milan/julia-1.6.0/usr/bin/../lib/libjulia-internal.so.1
Message:/home/milan/julia-1.6.0/usr/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/milan/julia-1.6.0/usr/bin/../lib/libLLVM-11jl.so)
make[1]: *** [/home/milan/julia-1.6.0/usr/lib/julia/corecompiler.ji] Erreur 1
```

Cc: @staticfloat

**Comment by staticfloat** [comment]
This should be fixed by https://github.com/JuliaLang/julia/pull/40217

**Comment by nalimilan** [comment]
Thanks. Unfortunately, I've just tried that branch and I get the same failure. AFAICT the problem is that when looking e.g. for libstdc++.so.6, the only file that matches is the one in `/lib64`, but it's not the one used by the compiler. What's tricky is that `gfortran` includes `/lib64` in its search path, at the end. It seems that the build script would need to detect that a static library with a higher precedence exists, just like the compiler does to choose the right library.
```
$ gfortran -print-search-dirs
install: /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/
programs: =/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../x86_64-redhat-linux/bin/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../x86_64-redhat-linux/bin/
libraries: =/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../x86_64-redhat-linux/lib/x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../x86_64-redhat-linux/lib/../lib64/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../x86_64-redhat-linux/8/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/:/lib/x86_64-redhat-linux/8/:/lib/../lib64/:/usr/lib/x86_64-redhat-linux/8/:/usr/lib/../lib64/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../../x86_64-redhat-linux/lib/:/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/../../../:/lib/:/usr/lib/
```

**Comment by staticfloat** [comment]
> AFAICT the problem is that when looking e.g. for libstdc++.so.6, the only file that matches is the one in /lib64, but it's not the one used by the compiler.

I built a docker container that installs the devtoolset, and it looks to me like the `libstdc++` that is used by the devtoolset is the same as what is used by the system overall; e.g. it doesn't try to mix-and-match libstdc++ versions, it just compiles against the old version that ships with CentOS.  I don't know how they support newer features with older libstdc++, but I can't find any newer `libstdc++` libraries in the devtoolset that gets installed.

This means that the fundamental issue is that the libstdc++ on the system is too old to support our Yggdrasil-built binaries.  So you must not use  e.g. BB-built LLVM; you must either built it yourself, or install the CSL from BB.

**Comment by nalimilan** [comment]
Thanks for checking. Indeed it seems things are quite complex. In the [gcc-c++ package](http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/d/devtoolset-9-gcc-c++-9.3.1-2.el7.x86_64.rpm), there's a libstdc++.so file which is just a text file containing this:
```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
INPUT ( /usr/lib64/libstdc++.so.6 -lstdc++_nonshared )
```
Next to it there's a libstdc++.a link to the libstdc++.a provided by the [libstdc++-devel package](http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/d/devtoolset-9-libstdc++-devel-9.3.1-2.el7.x86_64.rpm). So AFAICT a mix of the devtoolset and of the system libstdc++ is used. I think it's supposed to support new C++ features, otherwise it would be almost useless.

I've searched a bit and I could find many examples of people who had `version 'GLIBCXX_X.Y.Z' not found` errors which were fixed by moving to a recent enough devtoolset or by using it properly. So I think there's hope!

(BTW using `USE_BINARYBUILDER_CSL=1` would be OK for me but I got other failures. I'll file more issues. :-)

**Comment by vtjnash** [comment]
As the message suggests, this is solved by `USE_BINARYBUILDER=0` to avoid the requirement on compiler and glibc version. Though note that we now require C11 standard atomics, so older compilers may be broken anyways already, and are generally unsupported.
