### ISSUE TITLE
Mutiple matches on string

### ISSUE THREAD

**Issue by Jejulia** [JuliaLang/julia#40270]
Currently, `match` using regular expression only returns the first match. Although there's `eachmatch`, the elements are of type `RegexMatch`. To get the matched strings, we need to call `.match` additionally. This is kind of redundant and causes a little performance problem. 

For example: 
A string `s = "234ghkh566ghh"`.
Both `[i.match for i in eachmatch(r"\d+", s)]` and `filter!(!isempty, split(r"[a-z]+", s))`
return `["234", "566"]`, but the former one is slightly slower with more allocation. The later one is okay, but it is not as intuitive or direct as using `eachmatch`, and requires an additional `filter`. Is it possible to define a new function for this purpose and work as efficient as `split`?

**Comment by stevengj** [comment]
> Currently, `match` using regular expression only returns the first match. 

You can pass a starting index to get additional matches.

**Comment by stevengj** [comment]
This works:
```jl
function matches(s::AbstractString, pattern)
    m = SubString{typeof(s)}[]
    r = findfirst(pattern, s)
    while !isnothing(r)
        push!(m, SubString(s, r))
        r = findnext(pattern, s, nextind(s, last(r)))
    end
    return m
end
```

**Comment by stevengj** [comment]
You can also do `SubString.(s, findall(r"\d+", s))`, which is a lot simpler and nearly as fast.
