### ISSUE TITLE
error when use * in external command.

### ISSUE THREAD

**Issue by panxiaoguang** [JuliaLang/julia#40291]
In linux, we can use ```ls *.png```to filter files end with "png",but in julia, 
when I input ```run(`ls '*.png'`) ```or ```run(`ls \*.png`)```, an error happend 

```julia
ls: *.png: No such file or directory
ERROR: failed process: Process(`ls '*.png'`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
```
maybe it's a bug.Because in windows, I didn't find the same error.

**Comment by KristofferC** [comment]
The expansion by `*` is a shell feature. `run` just executes a command. You can use e.g. https://github.com/vtjnash/Glob.jl.

**Comment by panxiaoguang** [comment]
> https://github.com/vtjnash/Glob.jl

Thank you very much!
