### ISSUE TITLE
Default address family for `Sockets.getaddrinfo` changed in Julia 1.6

### ISSUE THREAD

**Issue by david-macmahon** [JuliaLang/julia#40306]
The default address family for `Sockets.getaddrinfo` seems to have changed in Julia 1.6:

```bash
$ julia15 -e 'using Sockets; @show getaddrinfo("localhost")'
getaddrinfo("localhost") = ip"127.0.0.1"

$ julia16 -e 'using Sockets; @show getaddrinfo("localhost")'
getaddrinfo("localhost") = ip"::1"
```

Not sure whether this is intentional, but it doesn't match [the docs](https://docs.julialang.org/en/v1.6.0/stdlib/Sockets/#Sockets.getaddrinfo):

> `getaddrinfo(host::AbstractString, IPAddr=IPv4) -> IPAddr`

**Comment by vtjnash** [comment]
Seems like #36029 was merged without NEWs or docs. Note that you might have wanted the variable `Sockets.localhost`, for the IPv4 loopback adapter.

**Comment by david-macmahon** [comment]
I want to resolve a user-supplied string (that can be `localhost`) to an IPv4 address.  I can pass `IPv4` now that I know it's no longer the default, but a NEWS and/or docs update might save others some time/trouble.

**Comment by david-macmahon** [comment]
As mentioned in #36029, the new behavior defaults to the first address/address family returned by `getalladdrinfo`, which mirrors the order returned by the system `getaddrinfo()` call.  Some (all?) systems allow the local administrator to control this order if desired, so this new behavior is better in that it doesn't try to second guess the local administrator.

Since this change is intentional, this issue is a documentation issue (doc string and NEWS).
