### ISSUE TITLE
Control coverage output location

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#40305]
There are often times it might be useful to save coverage output to a different directory.  The most common being when we don't have permissions to modify the directories the source code is stored in.  This can be due to depots higher in the chain of our depot path being owned by some staff user, or because we're mounted in some docker container as a different user, etc...

One possibility is to allow setting a prefix such that we write out to `$(JL_CODECOV_PREFIX)/path/to/foo.jl.cov`, settable by an environment variable.  This has the obvious benefit of being simple, and code coverage processing tools can be altered to attempt to look up `$(PREFIX)/$(file).cov` for all `file`'s they're trying to process rather easily.

**Comment by vtjnash** [comment]
You mean like `--code-coverage=path/to/foo-%p.info` does?

**Comment by staticfloat** [comment]
I didn't know about that option; I don't see people use it much, cool!  Can I use that with `Coverage.jl`?  How do I specify to only track user code or track all code?

**Comment by vtjnash** [comment]
I believe both of those questions are in the first paragraph of https://github.com/JuliaCI/Coverage.jl#code-coverage 😂

**Comment by IanButterworth** [comment]
Indeed, both can be declared. 
And it is now possible to do this to track only files under the working directory
```
--code-coverage=path/to/foo-%p.info --code-coverage=@
```
or `@path` for another path to a directory or specific file

Also, `Pkg.test` on master (1.9) now uses directory-specific code coverage, so CI with code coverage should see a speed bump
