### ISSUE TITLE
Broadcasting and zero-step ranges

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#40317]
```julia
julia> 0 .* collect(1:3) .+ (1:4)'
3×4 Matrix{Int64}:
 1  2  3  4
 1  2  3  4
 1  2  3  4

julia> 0 .* (1:3) .+ (1:4)'
ERROR: ArgumentError: step cannot be zero
```
This fails because it eagerly evaluates `0 .* (1:3)` without waiting to see the rest of the broadcast:

https://github.com/JuliaLang/julia/blob/b7b0a634d8fab9e94dec7177b3853c3c46e3e7dd/base/broadcast.jl#L1141

However, it works fine for floating point ranges:
```julia
julia> 0 .* (1:1.0:3) .+ (1:4)'
3×4 Matrix{Float64}:
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0

julia> 0 .* (1:1.0:3)  # not great printing, BTW!
0.0:0.0:0.0

julia> typeof(ans)
StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}
```
To fix this, if `broadcasted` is still going to return a range, then perhaps `2 .* (1:3)` needs to return `StepRangeLen(2,2,3)`. 

Xref #15218 about zero step, pre-1.0.

**Comment by mbauman** [comment]
I really don't think it makes much sense to address this independently of #15218 / #10391.  The result of `0 * (1:3)` shouldn't be different from `0 .* (1:3)`.

**Comment by mcabbott** [comment]
OK, it looks like `0 * (1:3)` calls broadcasting, while `(1:3) .- (1:3)` calls ordinary subtraction, and all of these give errors. Sorry I didn't fully untangle this before posting. 

Might it be acceptable to route both cases to the existing `StepRangeLen`, without the rest of #15218? Taking on "unifying LinSpace, StepRange, and StepRangeLen" sounds like a much bigger project. And ways to type them largely orthogonal.

**Comment by mbauman** [comment]
Right, I think we can "just" make arithmetic on `StepRange{<:Integer}`s return `StepRangeLen{<:Integer}`s everywhere.  Not sure how well trod/performant that particular parameterization of the type is, though, or what downstream effects it'll have but on its face it seems simple.
