### ISSUE TITLE
Re-name "Master" to "Main"

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#40316]
Hey folks, what needs to be done to switch the default branch over from "Master" to "Main"?

**Comment by quinnj** [comment]
GitHub provides some helpful information: https://github.com/github/renaming

**Comment by KristofferC** [comment]
There is no way to do this without breaking any script and configuration out there that has the assumption of the current branch name or that the default branch name does not change.

**Comment by quinnj** [comment]
Do we have an idea on the potential surface area of those kinds of scripts; do we rely on that in buildbots or other CI-related things? Do things like auto-built docker images perhaps rely on those? Would things like PkgEval.jl or Nanosoldier.jl be affected?

**Comment by logankilpatrick** [comment]
What sort of scrips are you referring to? We could do the transition for scrips in this repo and GitHub does auto re-directs after we re-name the branch.

**Comment by oscardssmith** [comment]
If I'm reading correctly, the website auto-redirects but the API throws an error. 
"Return a "Moved Permanently" response in API requests for the old branch name". Is that a correct reading?

**Comment by KristofferC** [comment]
There are an unknowable number of scripts out there doing things with the julia repo (just like we there is an unknowable amount of code or there using Julia).

**Comment by oscardssmith** [comment]
The good news is that any script that's broken by this should be pretty easy to fix. If we make this change, it will probably break a decent amount, but nothing that a few find and replaces wouldn't fix.

**Comment by logankilpatrick** [comment]
Yeah, personally willing to offer up some of my time to track down and help fix these issues when they come up. Did something similar when we changed the Slack invite URL and I had to open like 100 PRs to fix these.

**Comment by KristofferC** [comment]
> . If we make this change, it will probably break a decent amount, but nothing that a few find and replaces wouldn't fix.

We try our very best to absolutely not "break a decent amount".

**Comment by logankilpatrick** [comment]
I would be interested to see/hear what sort of things this would actually break in practice. It's unclear what scripts are running on the repo that we are trying to keep alive which we can't switch to "Main" ourselves. Any examples that come to mind?

**Comment by DilumAluthge** [comment]
We will continue this discussion offline among members of the JuliaLang organization.

**Comment by KristofferC** [comment]
For people that are interested in working on things that would hypothetically make this easier, making sure that tools figure out the default branch on their own instead of hard coding branch names into the source code, as done in https://github.com/JuliaDocs/Documenter.jl/pull/1751, would be useful.

**Comment by LilithHafner** [comment]
From triage: Hi @KristofferC, we know that you're the one who will have to do most of the work to clean this up, and we know you don't want to do it, but Stefan & Jeff and other contributors will chip in to buy you something nice.

**Comment by KristofferC** [comment]
Is that some kind of a joke I fail to understand? Anyway, assuming this was discussed in triage, this did not have the triage label so the people interested in discussing it did not have the proper opportunity to do so.

**Comment by staticfloat** [comment]
@LilithHafner If we're going to do this, can we hold off on making a `main` branch on the `JuliaLang/julia` repository until it's actually the one to use?  I personally have many scripts that do things like `if branch_exists("main"); rebase_target = "main"; else; rebase_target = "master"; end`, and so if `main` exists but isn't actually the source of truth, it kind of screws things up.

**Comment by staticfloat** [comment]
Given that you 👍'ed my message, I have deleted the `main` branch, because it being out of date is screwing things up.

**Comment by LilithHafner** [comment]
Oops! I didn't even realize that I created that branch; I created it in a mistake unrelated to this issue. Thank you for cleaning it up.

**Comment by charleskawczynski** [comment]
I just read through this, and I'm surprised that this issue is closed, yet the issue doesn't seem addressed. Should it be reopened? Or re-closed as not planned?

**Comment by ViralBShah** [comment]
Closed as not planned
