### ISSUE TITLE
Should views of CartesianIndices produce CartesianIndices?

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#40314]
Currently

```julia
julia> a = ones(1000, 1000);

julia> c = CartesianIndices(a);

julia> cv = @view c[:,:];

julia> @btime $a[$c];
  1.673 ms (2 allocations: 7.63 MiB)

julia> @btime $a[$cv];
  8.094 ms (2 allocations: 7.63 MiB)
```

This gap might be bridged if `cv` is another `CartesianIndices`.

This is not always possible of course, eg. in logical indexing, but there might be a few common cases involving Cartesian indexing of `CartesianIndices` that might be optimized.

**Comment by mbauman** [comment]
This matches what we do with ranges since 1.5.  Seems sensible.
