### ISSUE TITLE
Much memory used for 2×2 matrix multiplication

### ISSUE THREAD

**Issue by LRjunior** [JuliaLang/julia#40322]
```               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time A = [1 2; 3 4]
  0.000011 seconds (2 allocations: 160 bytes)
2×2 Matrix{Int64}:
 1  2
 3  4

julia> @time A'
  0.003028 seconds (6.78 k allocations: 484.415 KiB, 99.13% compilation time)
2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

julia> @time A = [1 2; 3 4] * A'
  0.473526 seconds (2.26 M allocations: 120.757 MiB, 4.95% gc time, 99.93% compilation time)
2×2 Matrix{Int64}:
  5  11
 11  25

julia> @time [1 2; 3 4] * [1 3; 2 4]
  0.000003 seconds (5 allocations: 432 bytes)
2×2 Matrix{Int64}:
  5  11
 11  25

julia>
```
Much memory ~120MiB and allocations are used for 2×2 matrix multiplication.

**Comment by oscardssmith** [comment]
Notice `99.13% compilation time`. That means you're measuring the memory of compilation. If you run it a second time, you would see `0.000009 seconds (4 allocations: 288 bytes)`. Almost all of this time and allocation are due to the cost of assigning to a global variable.

**Comment by KristofferC** [comment]
And see for example the manual: https://docs.julialang.org/en/v1/manual/performance-tips/#Measure-performance-with-[@time](@ref)-and-pay-attention-to-memory-allocation

> On the first call (`@time sum_global()`) the function gets compiled. (If you've not yet used `@time` in this session, it will also compile functions needed for timing.) You should not take the results of this run seriously.
