### ISSUE TITLE
Document retrieving capture group names from `Regex` or `RegexMatch`

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/julia#40347]
The Regex docs provide indexing with Symbol, where the symbol is the name of the capture group. 

What is lacking is a way to retrieve the capture group names from either a Match or just the Regex itself (from the docs).

```julia
s = "aaa bbb ccc"
r = r"(?<a>.*) (?<b>.*) (?<c>.*)"
m = match(r, s) # I don't think there is a way to retrieve the symbols [:a, :b, :c] from this or `r`
```
One has to know about `Base.PCRE.capture_names(m.regex.regex)`.

The context in which this arose was wanting to easily construct a `DataFrame` from a `Vector{RegexMatch}` where the capture group names become the column names. Thanks to @pdeffebach for finding the `capture_names` function for me. 

This should be a simple PR to add a line to https://docs.julialang.org/en/v1/manual/strings/#Regular-Expressions mentioning it. 

I may get to it, I may not xd

**Comment by BenjaminGalliot** [comment]
Related to #37299?

From the master branch, we now have a `keys` method.

**Comment by anandijain** [comment]
beautiful, indeed this is a duplicate. i will leave it open for documenting `keys`, as that PR just updated NEWS.md

**Comment by regier21** [comment]
I was looking into doing this and I noticed that none of the ```RegexMatch``` functions (or ```RegexMatch``` itself) are documented. Should I go ahead and add documentation for all of these?
