### ISSUE TITLE
Base.rand() produces too many collisions for `Float32`s

### ISSUE THREAD

**Issue by simsurace** [JuliaLang/julia#40355]
**Minimal working example** (Tested on Julia 1.5 and 1.6.)
```julia
julia> A = rand(Float32, 2^20);
julia> length(A)-length(unique(A))
```
**Expected behavior**
The expected number of duplicates when drawing `n` times at random from a set of `N` elements with replacement is equal to (see e.g. [Proposition 4.1 in this paper](https://arxiv.org/pdf/2003.08009.pdf))
```julia
expected_number_of_duplicates(N, n) = n - N * (1 - (1 - 1/N)^n)
```
For drawing a uniform `Float32`, we therefore expect
```julia
julia> expected_number_of_duplicates(2^32, 2^20)
127.98946189880371
```
**Actual behavior**
I obtain numbers that are on the order of `60000`.

**Comment by sostock** [comment]
But the set doesn’t have `2^32` elements, since only numbers in the interval `[0,1)` are returned by `rand`.

**Comment by oscardssmith** [comment]
Also, `rand` doesn't generate all numbers in `[0,1)`. It generates only numbers from `[1,2).-1`. As such, there are `2^23` different possible return values. As such,
```
expected_number_of_duplicates(2^23, 2^20)
62888.521840296686
```
which seems in line with the number you're seeing. Given that, should this be closed?

**Comment by simsurace** [comment]
Oh yes, of course! Apologies and thanks for clearing this up.
