### ISSUE TITLE
Export Base.RefValue

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#40369]
`RefValue` is really useful - not just to create mutable `const` objects, but also to create mutable fields in large immutable structs. However, that requires importing `Base.RefValue` - which is not exported.

So what's the deal with `RefValue`? Is the type simply an internal implementation of `Ref`, not to be relied on in user code? If not, can we export it from Base? If so, can we have some exported type that can be used for a similar purpose?

**Comment by vtjnash** [comment]
It is a very inefficient (slow) way to create a mutable field in a large mutable struct (the efficient way is to make the whole struct mutable), so we try to dissuade people from using it directly. I believe there's old issues discussing this, but can't quickly find them.

**Comment by cscherrer** [comment]
I don't have the code any more, but I did some benchmarks about a year ago (using Julia 1.5 IIRC) and saw that immutable structs can be much faster than mutable. If you have an immutable struct with a single `Ref` field, wouldn't this only introduce over head to that particular field, so the others would still be faster?

If this is correct, then what's preferable would seem to depend strongly on the access patterns, even if accessing a single `Ref` is slower than accessing a field in a mutable struct. But maybe I'm missing something?

**Comment by vtjnash** [comment]
Using `Ref` / `RefValue` will nearly always be worse than choosing `mutable struct` when applicable. The general rule of thumb is that you *want* to put `mutable` at the outermost container that you can. This implies that most types will be `struct`, but that avoiding writing `mutable` when it is actually applicable would also cost significant performance. And that you should almost never use `Ref` (or subtypes), as that gets this exactly backwards.

**Comment by cscherrer** [comment]
Thanks @vtjnash . I don't understand how this can be, and it entirely breaks my mental model. But your understanding of this is a lot deeper than mine, so I'll just trust you and keep an eye out for ways to resolve the cognitive dissonance :)

**Comment by jakobnissen** [comment]
I'm closing this issue, as the original use case (including it as fields of a struct) is not as useful as I thought.
