### ISSUE TITLE
Underscores in big_str macro for floats

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#40368]
```
julia> 0.123_456
0.123456

julia> big"0.123_456"
ERROR: ArgumentError: invalid number format 0.123_456 for BigInt or BigFloat
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

It was mentioned in https://github.com/JuliaLang/julia/pull/24834#issuecomment-348708899, but I didn't find a dedicated issue. There used to be issue (https://github.com/JuliaLang/julia/issues/21092), but that was closed when the integer case was implemented.

**Comment by JeffreySarnoff** [comment]
yes absolutely (a thorn too long unpared)
