### ISSUE TITLE
Cut & Paste '~\.julia\dev' folder to a Windows MyDocuments folder

### ISSUE THREAD

**Issue by johntrinder** [JuliaLang/julia#40374]
I have cut&pasted the '~\.julia\dev' folder on the C: drive into Windows10 'MyDocuments' so that I can perform a daily synchronized backup of any changes.
To accommodate this I added the following line to my 'startup.jl' file:
        pushfirst!(DEPOT_PATH, "D:\\My Documents\\JULIA\\LIBRARY")

Now, when I create a package using   (@v1.5) pkg> dev .
I get the following error report: 

[ Info: Resolving package identifier `.` as a directory at `D:\My Documents\JULIA\LIBRARY\dev\MyExtraTwo\`.
Path `.` exists and looks like the correct package. Using existing path.
  Resolving package versions...
ERROR: expected package `MyExtraTwo [4fbb7824]` to exist at path `C:\D:\My Documents\JULIA\LIBRARY\dev\MyExtraTwo`

As can be seen 'C:\' is prepended to the '~\dev\MyExtraTwo' path; so presumably this is a bug.

**Comment by KristofferC** [comment]
Should be fixed in 1.6 (by https://github.com/JuliaLang/julia/pull/38259).
