### ISSUE TITLE
openblas 0.3.13 uses `clock_gettime` that is only available macOS 10.12 onwards

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#40375]
This version starts fine
https://julialangnightlies-s3.julialang.org/bin/mac/x64/1.7/julia-95a34a9020-mac64.dmg
https://github.com/JuliaLang/julia/commit/95a34a902061699205d0d116878e766f1e338d20
```
julia> versioninfo()
Julia Version 1.7.0-DEV.609
Commit 95a34a9020 (2021-02-25 17:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, penryn)
```

This does not start
https://julialangnightlies-s3.julialang.org/bin/mac/x64/1.7/julia-dc81980e0b-mac64.dmg
https://github.com/JuliaLang/julia/commit/dc81980e0b9ea4f817fc1a36139867469da0f594
```
$ exec '/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia'
ERROR: Unable to load dependent library /Applications/Julia-1.7.app/Contents/Resources/julia/bin/../lib/julia/libopenblas64_.dylib
Message: dlopen(/Applications/Julia-1.7.app/Contents/Resources/julia/bin/../lib/julia/libopenblas64_.dylib, 6): Symbol not found: _clock_gettime
  Referenced from: /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia//libgfortran.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia//libgfortran.5.dylib
Unable to load "/Applications/Julia-1.7.app/Contents/Resources/julia/bin/../lib/julia/libopenblas64_.dylib"
┌ Error: No loaded BLAS libraries were built with ILP64 support
└ @ LinearAlgebra.BLAS /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/blas.jl:154
Quitting.

[Process completed]
```

I believe this is a separate issue from https://github.com/JuliaLang/julia/issues/40361 and I created a new issue.

**Comment by jaakkor2** [comment]
Recent https://julialangnightlies-s3.julialang.org/bin/mac/x64/1.7/julia-89fff18d59-mac64.dmg  https://github.com/JuliaLang/julia/commit/89fff18d590db9be84598e0045003b903d48d2df failed to start as well.

**Comment by vtjnash** [comment]
Seems to work for me, but I have an older kernel. What do you get with verbose=true?
```
julia> versioninfo(verbose=true)
Julia Version 1.7.0-DEV.847
Commit fedefe913a (2021-04-06 03:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  uname: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz: 
              speed         user         nice          sys         idle          irq
       #1  2700 MHz     350469 s          0 s     196643 s    2802132 s          0 s
       #2  2700 MHz      43470 s          0 s      22382 s    3283181 s          0 s
       #3  2700 MHz     299995 s          0 s     137052 s    2911989 s          0 s
       #4  2700 MHz      39964 s          0 s      16206 s    3292862 s          0 s
       #5  2700 MHz     253623 s          0 s     106665 s    2988747 s          0 s
       #6  2700 MHz      39651 s          0 s      14653 s    3294728 s          0 s
       #7  2700 MHz     204878 s          0 s      74921 s    3069236 s          0 s
       #8  2700 MHz      40513 s          0 s      13205 s    3295313 s          0 s
       
  Memory: 16.0 GB (438.875 MB free)
  Uptime: 651112.0 sec
  Load Avg:  1.5791015625  1.568359375  2.31005859375
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  XPC_FLAGS = 0x0
  HOME = /Users/jameson
  TERM = xterm-256color
  PATH = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMwareFusion.app/Contents/Public:/opt/X11/bin:/Users/jameson/.rvm/bin

```

**Comment by jaakkor2** [comment]
```
julia> versioninfo(verbose=true)
Julia Version 1.7.0-DEV.609
Commit 95a34a9020 (2021-02-25 17:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  uname: Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz: 
              speed         user         nice          sys         idle          irq
       #1  2000 MHz       4022 s          0 s       5172 s     176147 s          0 s
       #2  2000 MHz       4236 s          0 s       3494 s     176298 s          0 s
       
  Memory: 8.0 GB (2885.98046875 MB free)
  Uptime: 30591.0 sec
  Load Avg:  51.3974609375  17.18359375  7.8505859375
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, penryn)
Environment:
  MANPATH = /opt/local/share/man:/opt/local/share/man:
  TERM = xterm-256color
  PATH = /Users/jaakko/anaconda/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
  XPC_FLAGS = 0x0
  HOME = /Users/jaakko
```
This is on OS X 10.11.6.  OS in platform info seems to be the version of kernel where the compilation was done.

**Comment by vtjnash** [comment]
ah, right, I skimmed that too quickly (I was confused that penryn could run the latest version, so I should have double-checked).

We compile libjulia with `-mmacosx-version-min=10.9`, but looks here like gfortran might be missing that flag on https://github.com/JuliaPackaging/Yggdrasil / https://github.com/JuliaPackaging/BinaryBuilder.jl (@staticfloat)

**Comment by staticfloat** [comment]
We are setting `-mmacosx-version-min=10.10` on Yggdrasil.  Not great that it doesn't match Julia itself, but we had to bump for some software package at some point, I don't remember quite which one; perhaps something to do with GTK.

**Comment by ViralBShah** [comment]
We should probably bump it on Julia to 10.10 ([which released in 2014](https://en.wikipedia.org/wiki/OS_X_Yosemite)), so hopefully that is still old enough to support users.

**Comment by staticfloat** [comment]
Can someone impacted by this try building with Julia set to `10.10` to verify that it fixes the issue?

**Comment by ViralBShah** [comment]
Perhaps relevant? https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

**Comment by jaakkor2** [comment]
https://github.com/JuliaLang/julia/pull/40396 did not fix this issue for me.

I created https://github.com/JuliaLang/julia/pull/40400 to be able to download a binary with `-mmacosx-version-min=10.10`.

**Comment by jaakkor2** [comment]
`-mmacosx-version-min=10.10` on Julia side does not fix this, tested with #40400.

https://github.com/xianyi/OpenBLAS/issues/2814#issuecomment-752751563 and the linked issue https://github.com/pocoproject/poco/issues/1453 show many similar issues about `_clock_gettime`.

**Comment by Keno** [comment]
The compiler can do OS x version detection. OpenBlas should not be using those symbols without checking that.

**Comment by vtjnash** [comment]
Those issues are pretty closely related to this: it seems that the Apple headers are broken, so gcc/gfortran/openblas mis-detect the symbol as existing, when it should not (the ability to compile this header correctly is predicated on the existence of the clang extension `#if __has_extension(enumerator_attributes)`)

**Comment by staticfloat** [comment]
I have identified the issue, and I have a fix making its way through the ecosystem: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/134
