### ISSUE TITLE
continue/break-with-value & else clauses in loops

### ISSUE THREAD

**Issue by jakobjpeters** [JuliaLang/julia#40372]
These are a couple of ideas to extend those proposed in #22891.

- As a natural extension to `break`-with-value in a loop, I propose `continue` to append a value to a returned array.

- I had initially thought `default` would be more descriptive than `else` and may lessen objections to it (https://github.com/JuliaLang/julia/pull/23260#issuecomment-463768852). However, @tkluck pointed out (https://github.com/JuliaLang/julia/pull/23260#issuecomment-813968476) that this would not be backwards compatible because 'default' is not a keyword. What about `finally`? It makes sense in context with loops; after iteration it is the final block of code to run.

- The `return` keyword could be used to explicitly exit the `finally` block.

- Are there any issues with using a type declaration on the assigned variable that would need to be addressed as well?

```Julia
values = rand(1:100, 10)

evens::Array{Int64} = for i in values # optional return type
    if iseven(i)
        continue i # append to returned array
    elseif i == 13
        continue "not Int64" # throw an exception
    end
finally # or `else`
    newvalues = values * 2
    return newvalues # explicit return
end
```

P.S. This is my first foray into github, I welcome constructive criticism/feedback :)

**Comment by tkluck** [comment]
Thanks for sharing the ideas! FYI I'm not a committer to Julia but I'll share some thoughts that are hopefully helpful.

 - **Backwards compatibility.** New syntax has to be a *syntax* error in current versions of Julia -- that way you can be sure it doesn't already have a meaning. This was the problem with `default` and it's the same with `events::Array{Int64} = for ...`: this is currently valid syntax that will throw a runtime error when trying to assign the loop expression's value (`nothing`) to the variable.

 - **Selling point.** What gap in the language does this fill? For example, for `for/else` we could find applications in the standard library (https://github.com/JuliaLang/julia/pull/23260#discussion_r136054243). Maybe you can do the same? It's up to you to prove that you have "product/market fit". If you're able to point at other languages that have a feature like this, even better.

For comparison here's a way of achieving what you want in current Julia:
```
mapreduce((a,b) -> push!(a,b...), values, init=Int64[]) do i
    if iseven(i)
        return (i,)
    elseif i == 13
        throw("not Int64")
    else
        return ()
    end
end
```
It's a little bit more cumbersome, but on the other hand it's able to push several values in a single iteration (which is incidentally a shortcoming of using `continue` for accumulation).

- **`finally`.** I don't get your proposal -- what's the case in which this block would run? There's no `break` so clearly you mean something different from #23260.

Hope that's helpful! And to set expectations, the chances of something like this being merged are very small -- #23260 also didn't make the triage. You could have a look at https://github.com/JuliaLang/julia/labels/good%20first%20issue so you can start with rewarding experiences before sinking your teeth in the big ones :)
