### ISSUE TITLE
Inconsistent behavior when indexing into arrays by (1, 1, ...)

### ISSUE THREAD

**Issue by foldl** [JuliaLang/julia#40388]
## Test Code

```shell
julia> [1,2,3][1,1]
1

julia> [1,2,3][1,2]
ERROR: BoundsError: attempt to access 3-element Vector{Int64} at index [1, 2]
...
```

## Analysis

In `array_nd_index`, we can see that when `nidxs > nd`, a BoundsError is always reported, except
when all indices equal to `1` (``ii == 0``).

https://github.com/JuliaLang/julia/blob/8fc52931fca94f4247f2b0e8f69447f8417d70ab/src/builtins.c#L1209

IMHO it can hardly be called as a feature.

**Comment by antoine-levitt** [comment]
Yes, it's a strange quirk of julia, which some other languages have as well: https://docs.julialang.org/en/v1/manual/arrays/#Omitted-and-extra-indices. It is pretty weird but it does make a number of things much easier to write.

**Comment by foldl** [comment]
> This allows vectors to be indexed like one-column matrices..

This is really a nice feature. 
But I can't see why `[1,2,3][1, 1, 1, 1, 1, 1, 1]` is allowed and evaluated to `1`.

**Comment by antoine-levitt** [comment]
It's the same principle, only generalized to dimensions > 2.
