### ISSUE TITLE
bug-report=rr pollutes the user's environment

### ISSUE THREAD

**Issue by GlenHertz** [JuliaLang/julia#40398]
When running julia 1.6.0 on Linux like:

```
julia --bug-report=rr --project=@. runtests.jl
```

It will modify the project's environment:

```
[ Info: Loading BugReporting package...
[ Info: Package `BugReporting` not found - attempting temporary installation
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General`
   Resolving package versions...
    Updating `~/JC/pkgs/MyProject.jl/Project.toml`
  [bcf9a6e7] + BugReporting v0.1.3
    Updating `~/JC/pkgs/SPICEFrontend.jl/Manifest.toml`
  [4f1ea46c] + AWSCore v0.6.17
  [1c724243] + AWSS3 v0.6.12
  [bcf9a6e7] + BugReporting v0.1.3
...
```

while it should create a temporary environment and not modify the user's project environment.

**Comment by Keno** [comment]
I originally had a `Pkg.activate` here to avoid this, but looks like that got dropped in https://github.com/JuliaLang/julia/commit/43d8a285d3f0a0a432692cbdb78f1be2ea871f81 (cc @fredrikekre). @fredrikekre can you suggest a fix?

**Comment by fredrikekre** [comment]
I believe it was correct after https://github.com/JuliaLang/julia/commit/43d8a285d3f0a0a432692cbdb78f1be2ea871f81 but https://github.com/JuliaLang/julia/commit/6d3ff11e49a926c0398b6ddfdb3b7da34692ed51#diff-b5a3d517bf443d59c5cfe08a30886d887e477b9681c91ffdf258a8e8229266bc removed some logic there.

**Comment by fredrikekre** [comment]
Should be fixed by https://github.com/JuliaLang/julia/pull/40403, but note that BugReporting does not respect the `--project` flag (but that should be fixed in that package).
