### ISSUE TITLE
Vararg subtyping is inconsistent between 1.0 and 1.6

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#40405]
on 1.0, 1.2, 1.3, 1.4

```julia
julia> Vararg{Any} <: Vararg
false
```

on 1.6, 1.5

```julia
julia> Vararg{Any} <: Vararg
true
```

I guess if it's a bug on 1.0 should be backported? if not 1.6 should be updated instead then?

**Comment by Roger-luo** [comment]
on current nightly this errors

```julia
julia> Vararg{Any} <: Vararg
ERROR: TypeError: in <:, expected Type, got Vararg{Any}
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

**Comment by JeffBezanson** [comment]
`Vararg` is not really a type; it's only part of the structure of a tuple type. The current behavior is correct, and 1.6 is more correct than 1.0.
