### ISSUE TITLE
Problem with NamedTuple, T and Union{T, Tuple{Vararg{T}}

### ISSUE THREAD

**Issue by johntrinder** [JuliaLang/julia#40404]
Julia v1.6
I'm having an issue that I don't know if it's me or a bug; it's best detailed in the following simplified code:

T = NamedTuple{(:a, :b), Tuple{Char, Int64}}
S = Union{Tuple{Vararg{T}}, T}

function foo() :: S
        return ((a='3', b=5), (a='5', b=7)) # OK
        # return (a='3', b=5) # OK
end

foo() # works fine

T = NamedTuple{(:a, :b), Tuple{Union{Char, Nothing}, Int64}}
S = Union{Tuple{Vararg{T}}, T}

function foo2() :: S
        # return ((a='3', b=5), (a='5', b=7)) # error
        return (a='3', b=5) # error
end

foo2() # get the following error:
"""
ERROR: LoadError: MethodError: Cannot `convert` an object of type 
  Tuple{NamedTuple{(:a, :b), Tuple{Char, Int64}}, NamedTuple{(:a, :b), Tuple{Char, Int64}}} to an object of type 
  Union{NamedTuple{(:a, :b), Tuple{Union{Nothing, Char}, Int64}}, Tuple{Vararg{NamedTuple{(:a, :b), Tuple{Union{Nothing, Char}, Int64}}, N} where 
N}}

Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:205
Stacktrace:
 [1] foo2()
"""
Regards and thankyou for Julia!

**Comment by vtjnash** [comment]
This basically boils down to not having a way to convert type in a Union to a different one in the Union:
```julia
julia> convert(Union{NamedTuple{(:a,), Tuple{Union{Nothing, Char}}}, Int}, (a='1',))
ERROR: MethodError: Cannot `convert` an object of type 
  NamedTuple{(:a,), Tuple{Char}} to an object of type 
  Union{Int64, NamedTuple{(:a,), Tuple{Union{Nothing, Char}}}}
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:225
```
I'm not sure what we can do here

**Comment by johntrinder** [comment]
No it's me - there's no bug. Doing the following works:

T = NamedTuple{(:a, :b), Tuple{Char, Int64}}
T = Union{T, NamedTuple{(:a, :b), Tuple{Nothing, Int64}}}
S = Union{Tuple{Vararg{T}}, T}

function foo() :: S
        return ((a='3', b=5), (a=nothing, b=7)) # OK
        # return (a=nothing, b=5) # OK
end

foo() # works fine

**Comment by johntrinder** [comment]
Another way is probably better:

`T = NamedTuple{(:a, :b), Tuple{Union{Char, Nothing}, Int64}}
function foo2() :: Union{T, Tuple{Vararg{T}}}
    v = Vector{T}()
    push!(v, (a='3', b=5), (a=nothing, b=7))
    # return Tuple(L)
    return v[1]
end

foo2()
`

**Comment by johntrinder** [comment]
typo in the above, L should be vector v
