### ISSUE TITLE
Install on MacOS 11.2.3 does not work.

### ISSUE THREAD

**Issue by ZiCog** [JuliaLang/julia#40418]
I install Julia 1.6 as per the instructions for MacOS here: https://julialang.org/downloads/platform/
I have MacOS 11.2.3 on a MacBook Pro M1.

On opening the Julia app from the applications folder in Finder or Launchpad a terminal opens containing the following error:
```
Last login: Fri Apr  9 16:26:59 on ttys000
[oh-my-zsh] Would you like to update? [Y/n] exec '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia'

➜  ~ xec '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia'
zsh: command not found: xec
```
Clearly the "e" from "exec" has gone missing somewhere. I presume the "Would you like to update?" prompt shown is expecting a single character "Y/n" and gets the "e" instead.

I can only start Julia by manually running the command show "exec '/Applications/Julia-1.6.app/Contents/Resources/julia/bin/Julia'".

**Comment by adamslc** [comment]
I am not up to date on how well Julia is running on M1, but this looks like a different issue. It looks like oh my zsh is asking you to update everytime you launch a new terminal window. What happens if you open a new terminal (not using the julia application), and answer the question (e.g. type n<enter>)?

**Comment by ViralBShah** [comment]
Right, that is exactly what is going on and interfering with the Julia startup, since the `e` from `exec` is being consumed by oh-my-zsh.

**Comment by ZiCog** [comment]
The problem went away. I don't recall zsh asking for an update, I use the terminal a lot, but I guess that is what it must have been.

Sorry the bother. Thanks.
