### ISSUE TITLE
Missing docstring for ->

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#40424]

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please guide me , where do i need to make changes?

**Comment by aramirezreyes** [comment]
I just learned in the Slack that /julia/base/docs/basedocs.jl would be a good place to start.

**Comment by fredrikekre** [comment]
Yes, something like
```
"""
    ->

Insert descriptive text here.
"""
kw"->"
```

**Comment by fredrikekre** [comment]
#40470
