### ISSUE TITLE
:typed_comprehension parser doesn't parse the what :comprehension expression does

### ISSUE THREAD

**Issue by Cvikli** [JuliaLang/julia#40431]
Hey Julianners,

I have to parse the julia syntax tree and generate new code in a macro and I faced with an issue where if I parse the `:typed_comprehension` and generate a new code I got into many unhandled cases while `:comprehension` case can understand the generated code correctly. 
A minimal example to reproduce:
```
works() = begin
	x= [begin
		a = sum([2,3,4.f0])
		a
	end * i for i = 10:20]
	println(x)
	println(typeof(x))
end
works()
fails() = begin
	y= Float32[begin 
			a = sum([2,3,4.f0])
			a
		end * i for i = 10:20]
	println(y)
end
fails()
```

I don't know if it is the case but the :comprehension and the :typed_comprehension julia parser has different parsing mechanism? 

Is it possible to solve this issue?

**Comment by simeonschaub** [comment]
Yes, `begin` and `end` have special meaning inside indexing expressions to allow for syntax like `A[end]`, so this is expected. You can use `(a = sum(...); a; ...)` for blocks instead though.

**Comment by Cvikli** [comment]
Sorry to reopen, but the problem is that I have bigger block in those. 

Also, this doesn't explain why is this works with :comprehension. So the first one works perfectly, only the second one doesn't. That is why I can't port the typed_comprehension to work.

**Comment by simeonschaub** [comment]
> Sorry to reopen, but the problem is that I have bigger block in those, this is a simplified version and can't be rewritten like you suggest.

You can still put newlines in there, so I don't quite understand why this wouldn't be possible.

> Also, this doesn't explain why is this works with :comprehension. So the first one works perfectly, only the second one doesn't. That is why I can't port the typed_comprehension to create a library.

The parser treats anything that looks like `A[...]` like an indexing expression, where `begin` and `end` have a special meaning. Expressions that look like `[...]` don't have these special semantics.

**Comment by Cvikli** [comment]
A[...] looks different as the AST showed for me that I have to handle. So I have to transpose cases like this:
```
"T[y for y in z]"	         # expr = (:typed_comprehension, :T, (:generator, :y, (:(=), :y, :z)))
"T[i,b]"			 # expr = (ref T i b)
```

Sadly I don't know how to generate newline. By the way I have a pretty complex begin end part, if I can generate newlines there I could test if it is possible to make it work. But I have to add `:comprehension` parses correctly, so in case like this, it handles everything properly: `"[y for y in z]"		# expr = (comprehension (generator y (= y z)))`
