### ISSUE TITLE
Base.significand_mask wrongly named

### ISSUE THREAD

**Issue by goualard-f** [JuliaLang/julia#40442]
According to the IEEE 754 standard, a floating-point number is represented by a triplet (sign, exponent, significand) and its value is (-1)^sign * b^exponent * significand [p. 17 of IEEE Std. 754-2019]. For the Float64 type, the significand of a normal number has then 53 bits. 

By contrast, the method Base.significand_mask in float.jl is only a mask for what the standard calls the _trailing significand field_ [p. 15, IEEE Std. 754-2019]; for the Float64 type, it is then a mask for the 52 lower bits of the significand only.

It might be better to rename Base.significand_mask to something else to avoid confusion.

**Comment by oscardssmith** [comment]
Given that this is an internal function, we are allowed to change the name, but I'm not sure if this confusion is worth a game change.

**Comment by goualard-f** [comment]
I understand it is a fringe issue. The effort to _do the right thing_ seems pretty low, though.

**Comment by oscardssmith** [comment]
Fixing it in `Base` would be pretty easy. The question is how many packages use this that would also have to be fixed. If you have a specific name in mind, feel free to create a PR, and we can run a package eval to see how much this breaks. If it's not much, this might be worth doing.

**Comment by JeffBezanson** [comment]
This does in fact select all bits related to the significand, so I don't think the name is so wrong.

**Comment by goualard-f** [comment]
@JeffBezanson Actually, all the bits it selects are related to the significand, which is not the same thing. As per the IEEE 754 standard, the significand includes the hidden bit, while what is selected by Base.significand_mask is the _trailing significand field_.

**Comment by JeffBezanson** [comment]
Yes, true, but there's nothing else `significand_mask` could mean --- there is no other possible actual bit mask for the significand. Since this is an internal name, it's understood to be a bit casual.
