### ISSUE TITLE
Does `fastabs(z::Complex)` mean something different than faster computation of `abs(z::Complex)`?

### ISSUE THREAD

**Issue by chenspc** [JuliaLang/julia#40440]
I came across the `fastabs` function [here](https://github.com/JuliaMath/SpecialFunctions.jl/blob/d24f19ea0549f12f8c77a8d7ccbef4413edb4836/src/SpecialFunctions.jl#L91-L98) in SpecialFunctions.jl and [here](https://github.com/JuliaLang/julia/blob/93fb785831dcfcc442f82fab8746f0244c5274ae/base/special/trig.jl#L1057-L1065) in Base.Math. I'm confused by its definition. 
```julia
julia> z = 3 + 4im
3 + 4im

julia> abs(z)
5.0

julia> Base.Math.fastabs(z)
7
```
Shouldn't it be something like below?
```julia
julia> fastabs(z::Complex) = √(abs2(real(z)) + abs2(imag(z)))
fastabs (generic function with 1 method)

julia> fastabs(z)
5.0
```
Or does it mean something else?

**Comment by Roger-luo** [comment]
according to docs

>  Faster abs-like function for rough magnitude comparisons. fastabs is
>   equivalent to abs(x) for most x, but for complex x it computes
>   abs(real(x))+abs(imag(x)) rather than requiring hypot.

where `hypot` is implemented as


>   Compute the hypotenuse \sqrt{|x|^2+|y|^2} avoiding overflow and underflow.
> 
>   This code is an implementation of the algorithm described in: An Improved
>   Algorithm for hypot(a,b) by Carlos F. Borges The article is available online
>   at ArXiv at the link https://arxiv.org/abs/1904.09481

IMO, this should be a discourse question.

**Comment by oscardssmith** [comment]
Note that if this was an issue, it would be an issue with `SpecialFunctions.jl` not Base.

**Comment by chenspc** [comment]
Sorry, but my question wasn't about the implementation or speed, it's the value of `fastabs(3+4im)` gives `7` rather than `5`.

@oscardssmith In `SpecialFunctions.jl`, it seems that the author plan to use the `fastabs` from the `Base.Math` in the near future. My concern is that this is a bug in both places.

**Comment by chenspc** [comment]
I'm not sure what this `intended behaviour` is but I guess that's a question for discourse. In the document, it says
> ...rather than requiring hypot.
which seems to suggest it would give the same result (`hypot(3+4im)` gives `5`) just not calling the it.

**Comment by oscardssmith** [comment]
I think 
> for complex x it computes abs(real(x))+abs(imag(x))
makes it pretty clear what it's supposed to do. If there's a way to make this clearer we might consider it, but we aren't changing the behavior of the function.
