### ISSUE TITLE
evalpoly with OffsetArrays

### ISSUE THREAD

**Issue by DNF2** [JuliaLang/julia#40454]
`evalpoly` iterates over its input coefficients assuming 1-based indexing. For zero-based arrays this silently produces surprising results, and errors out for other indexing-schemes:

```
using OffsetArrays
x = 0.73
a = [7, 2, 4]
a0 = OffsetArray(a, 0:2)
a_1 = OffsetArray(a, -1:1)
```
```
jl> evalpoly(x, a)
10.5916

jl> evalpoly(x, a0)
7.0516

jl> evalpoly(x, a_1)
ERROR: BoundsError: attempt to access 3-element OffsetArray(::Vector{Int64}, -1:1) with eltype Int64 with indices -1:1 at index [2]
```
This behaviour is documented:
> Evaluate the polynomial \sum_k x^{k-1} p[k] for the coefficients p[1], p[2], ...;

but seems pretty unfortunate, given the goal of making Julia agnostic to indexing.

Should this behaviour be 
1. changed, by using `eachindex`
2. emphasized in the documentation that zero-based indexing may lead to surprising results
3. guarded against by testing the input with `firstindex(a) == 1`
4. left as is
?

**Comment by johnnychen94** [comment]
OffsetArrays provides a very similar example to this, where `eachindex` is used. https://juliaarrays.github.io/OffsetArrays.jl/dev/#Example:-Polynomials

**Comment by martinholters** [comment]
But for an `OffsetArray` one would want the terms to be `a[i]*x^i`, while `Array`s really need the shifted index in `a[i-1]*x^i`. Having them differ seems very error-prone (also on what criterium to distinguish exactly?), having the shifted index for `OffsetArray`s also looks like a solid foot-gun. Is there any way out of that?

**Comment by LilithHafner** [comment]
This is currently buggy. We should make offset arrays error or give them a well-defined meaning. We can make them error for now and then support offset polynomials in base later if a strong case for it emerges.
