### ISSUE TITLE
Help understanding nested string interpolation

### ISSUE THREAD

**Issue by msavael** [JuliaLang/julia#40465]
```
julia> "$("$(1)")"
"1"

julia> "$("a$(1)")"
"a"
```

The above has confused me - could someone please help me understand how the two are being parsed? I expected the second one to evaluate to `"a1"`. 

Perhaps nested string interpolation is not supported in the first place, and this is always to break? I can't see anything in the documentation about it, though.

**Comment by vtjnash** [comment]
fixed by https://github.com/JuliaLang/julia/pull/40261

**Comment by msavael** [comment]
Thanks! I missed that when I searched - I think I only searched open issue by mistake.

**Comment by vtjnash** [comment]
Not to worry. Maintainers are in a better situation typically to find past issues, since we've read all of them
