### ISSUE TITLE
peakflops on 1.6.0 on Comet Lake i7-10850H 4x lower than on 1.7.0-DEV

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#40497]
`peakflops()` shows 4x slower values on Comet Lake i7-10850H on Julia v1.6.0 than on v1.7.0-DEV.  Likely difference OpenBLAS v0.3.10 vs v0.3.13.  

(Pre-)release v0.3.11 https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.11 
> Added autodetection of Intel Comet Lake cpus
```
julia> peakflops()
5.342836458447425e10

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```
```
julia> peakflops()
2.0629004121932886e11

julia> versioninfo()
Julia Version 1.7.0-DEV.847
Commit fedefe913a (2021-04-06 03:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by fredrikekre** [comment]
What's the issue here? Request to backport the openblas upgrade?

**Comment by jaakkor2** [comment]
This issue is to motivate the backport of the OpenBLAS that has been on and off in https://github.com/JuliaLang/julia/pull/40209 . Admittedly processors launched in Q2 of 2020 are relatively new, but would be nice to get reasonable performance from a new Julia version coming one year later.

**Comment by ViralBShah** [comment]
We are back with timed releases, and 1.7 is not too far away. OpenBLAS 0.3.13 had several issues that had to be addressed in the last few weeks on master, as a result of which I don't feel comfortable backporting it to 1.6. Also, with 1.7, MKL is going to be very easy to swap in for folks needing support for the newest processors - so hopefully things will be much better going forward.
