### ISSUE TITLE
julia "ERROR: UndefVarError: K not defined"

### ISSUE THREAD

**Issue by sjcushas** [JuliaLang/julia#40494]
i am trying to sketch a  contour lines plot by the code, but it shows "ERROR: UndefVarError: K not defined"

xvec = GradientDescent([1;1])
plot!(xvec[1,1:1:K], xvec[2,1:1:K], lw = 2, label = "iterates")
ERROR: UndefVarError: K not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1

**Comment by simeonschaub** [comment]
Welcome! Questions like this are usually better suited to discourse.julialang.org, where people are happy to help. In this case it just looks like you forgot to define the variable `K`.

**Comment by sjcushas** [comment]
> Welcome! Questions like this are usually better suited to https://discourse.julialang.org, where people are happy to help. In this case it just looks like you forgot to define the variable `K`.

thanks! I already posted a new question on the julia discourse. Do you happen to know how should I defind the K like K=3?
