### ISSUE TITLE
get! on Vector full of undef?

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#40493]
Would it make sense to defined `get!` on Vectors that contrain `undef` ?
On the one hand it kind of likes up with the docstring:

>   get!(collection, key, default)
>
> Return the value stored for the given key, or if no mapping for the key is present, store key => default, and return 

Though not completely, since `keys(::Vector)` returns a full list of all indicies even if it has `undefs`

Counter argument is we don't want to encourage mode uses of `undef` than are requires, since it makes for problematic code, since most interactions with it error and you can't set something back to undef, and people forget that it doesn't work the same for bitstypes.

Right now:
```julia
julia> data = Vector{String}(undef, 10);

julia> get!(_->randstring(), data, 5)
ERROR: MethodError: no method matching get!(::var"#11#12", ::Vector{String}, ::Int64)
```

**Comment by KristofferC** [comment]
I think it becomes a bit strange when `get!` would do something different for a `Vector{T}(undef, 5)` depending on if `T` is a bitstype or not.

**Comment by oxinabox** [comment]
I am convinced

**Comment by mgkuhn** [comment]
So the suggestion is basically to define
```
import Base.get!
function get!(a::AbstractArray, inds, default)
    if isassigned(a, inds...)
        a[inds...]
    else
        a[inds...] = default
    end
end
function get!(f::Function, a::AbstractArray, inds)
    if isassigned(a, inds...)
        a[inds...]
    else
        a[inds...] = f()
    end
end
```
such that
```
julia> a = Vector{String}(undef, 3)
3-element Vector{String}:
 #undef
 #undef
 #undef

julia> get!(a, 1, "hello")
"hello"

julia> get!(()->"world", a, 2)
"world"

julia> a
3-element Vector{String}:
    "hello"
    "world"
 #undef
```
?
