### ISSUE TITLE
julia cx16 error

### ISSUE THREAD

**Issue by Sofie8** [JuliaLang/julia#40503]
Hi,

For a workshop, participants are installing julia in a virtualbox (ubuntu64), but 3/150 receive the CPU not compatible, cx16 error.

**This solution was not working, as it was already enabled:**
You can enable this in the Virtualbox UI in Machine -> Settings -> System -> Acceleration -> Enable Nested Paging. You can also use the VBoxManage vmmodify command in the terminal to set --nestedpaging on.

**And for this solution, I have not idea how to run it**
Alternatively [2] mentions that Julia can be built with the -cx16 flag, which might make it work on even older CPUs / lower capabilities (we did not test this).

Like this was not doing it:
sudo apt-get install julia -cx16

Can you give us some advice please?

Thanks!
Sofie

**Comment by oscardssmith** [comment]
https://github.com/JuliaLang/julia/pull/15219 seems possibly related.

**Comment by vtjnash** [comment]
Discussed in https://discourse.julialang.org/t/julia-in-a-vm/12781/11 too. Apparently VirtualBox needs you to set an internal flag to fix this (assuming the underlying CPU isn't one of the old ones without this feature). I suggest continuing the discussion there. (though perhaps we should clarify better in the docs that "can be built" means that you must follow the source-build instructions?)

**Comment by Sofie8** [comment]
Ok I continued [here](https://discourse.julialang.org/t/julia-in-a-vm/12781/12).
Is the fix implemented if we run: 
git clone git://github.com/JuliaLang/julia.git
git checkout v1.6.0
make
./julia

or where to add the '-cx16 flag', make -cx16 ?

Thanks
