### ISSUE TITLE
Avoid memory allocation in tuple slicing

### ISSUE THREAD

**Issue by Marlin-Na** [JuliaLang/julia#40516]
Currently tuple slicing will likely to allocate a temporary vector except for some specific optimization, i.e. `1:end`, `1:end-1` and `1:end-2`.

https://github.com/JuliaLang/julia/blob/3a6b2a1071563adba1d3760a589421d3ff7a17bd/base/range.jl#L382

See the following performance drops when changing index from `1:end-3` to `1:end-2`.

```
function test(a, n)
    x = 0
    for t in a
        x += sum(t[1:n])
    end
    x
end

const a = repeat([(1,2,3,4,5)], 100000)

julia> @btime test(a, 3)
  82.567 μs (0 allocations: 0 bytes)

julia> @btime test(a, 2)
  14.154 ms (299830 allocations: 13.73 MiB)
```

**Comment by simeonschaub** [comment]
Should have been fixed by #39074, but that didn't make it into 1.6. Please reopen this, if it's still a problem on the main branch.
