### ISSUE TITLE
Overflow error warning needed 

### ISSUE THREAD

**Issue by marodriguezs** [JuliaLang/julia#40522]
Missing Overflow Error warning in:
julia>
p=1; for i in 1:13  
       p=p*i
       end;  println(p)
julia> 1932053504
(is an incorrect value)

same in:
13*12*11*10*9*8*7*6*5*4*3*2*1
returns incorrect value: 1932053504

Warning must be like:
julia> factorial(13)
ERROR: OverflowError: 13 is too large to look up in the table; consider using `factorial(big(13))` instead

julia> factorial(big(13))
6227020800

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by fredrikekre** [comment]
#855
