### ISSUE TITLE
Bug of edit

### ISSUE THREAD

**Issue by Jejulia** [JuliaLang/julia#40529]
In repl:
```
julia> @edit 2*3
ERROR: SystemError: edit: No error
Stacktrace:
 [1] systemerror(p::Symbol, errno::Int32; extrainfo::Nothing)
   @ Base .\error.jl:168
 [2] #systemerror#62
   @ .\error.jl:167 [inlined]
 [3] systemerror
   @ .\error.jl:167 [inlined]
 [4] (::InteractiveUtils.var"#14#24")(cmd::Cmd, path::String, line::Int32)
   @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:152
 [5] edit(path::String, line::Int32)
   @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:203
 [6] edit(f::Function, t::Any)
   @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:224
 [7] top-level scope
   @ REPL[3]:1
```
In VScode:
```
julia> @edit 2*3
ERROR: IOError: could not spawn `code -g 'C:\Users\sciph\AppData\Local\Programs\Julia-1.6.0\share\julia\base\int.jl:88'`: no such file or directory (ENOENT)
Stacktrace:
  [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
    @ Base .\process.jl:99
  [2] #637
    @ .\process.jl:112 [inlined]
  [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
    @ Base .\process.jl:196
  [4] _spawn
    @ .\process.jl:111 [inlined]
  [5] _spawn(::Base.CmdRedirect, ::Vector{Any})
    @ Base .\process.jl:139
  [6] run(::Base.CmdRedirect; wait::Bool)
    @ Base .\process.jl:443
  [7] (::InteractiveUtils.var"#2#3"{Bool, InteractiveUtils.var"#11#21", Vector{String}})(cmd::Cmd, path::String, line::Int32)
    @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:96
  [8] edit(path::String, line::Int32)
    @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:203
  [9] edit(f::Function, t::Any)
    @ InteractiveUtils C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\InteractiveUtils\src\editless.jl:224
 [10] top-level scope
    @ REPL[6]:1
```
I'm using Windows 10.
Both julia 1.5.4 and 1.6.0 return errors.
I've checked that in `edit`, `find_source_file` returns the correct path( eg `C:\Users\sciph\AppData\Local\Programs\Julia-1.6.0\share\julia\base\int.jl`) but `callback` in the for loop returns the error.

**Comment by gustaphe** [comment]
What is returned by `InteractiveUtils.editor()`? Does `@edit` work with any other functions, like your own functions?

Can not reproduce on Arch Linux, julia 1.7.

**Comment by vtjnash** [comment]
The legacy ShellExecuteW API doesn't return systemerrors (as that code seems to assume). The "modern" ShellExecuteExW is required for that.

**Comment by Jejulia** [comment]
@gustaphe it returns `open`
`@edit` returns the same error for my own function and function from third-party packages.

**Comment by gustaphe** [comment]
And does `open somefile.txt` work in a terminal?

**Comment by Jejulia** [comment]
No
```
shell> open .\\code\\Julia\\sudoku.txt
ERROR: IOError: could not spawn `open '.\code\Julia\sudoku.txt'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
   @ Base .\process.jl:99
 [2] #637
   @ .\process.jl:112 [inlined]
 [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
   @ Base .\process.jl:196
 [4] _spawn
   @ .\process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool)
   @ Base .\process.jl:439
 [6] run
   @ .\process.jl:438 [inlined]
 [7] repl_cmd(cmd::Cmd, out::Base.TTY)
   @ Base .\client.jl:69
 [8] top-level scope
   @ none:1
```

**Comment by gustaphe** [comment]
Okay, I would guess you need to somehow set a default (cli) editor. Unfortunately it seems Windows doesn't have (/respect) any environment variable for this. `open` is a mac command, so I don't know why it tried that.

**Comment by vtjnash** [comment]
`open` is a shell command, so it is the same as double-click, or `cmd /c open a.jl`

**Comment by musm** [comment]
It's not entirely clear to me what the core issue is here? It seems like edit works fine in the REPL, but not VS Code? 
If you are wanting to use VS Code as the Julia editor: I have the  `JULIA_EDITOR`  environment variable set to `code.cmd`:
![image](https://user-images.githubusercontent.com/4319522/115789424-23bc6000-a393-11eb-8154-23618170afe2.png)
Which works from VS Code and the REPL.

**Comment by Jejulia** [comment]
@musm @edit did not work in either REPL or VS Code. After setting the environmental variable, it works in REPL but still not in VS Code.

**Comment by musm** [comment]
What exactly do you mean it doesn't work in VS Code? Like when you run `@edit` in the VS Code terminal, which is presumably launched from a powershell shell?

**Comment by Jejulia** [comment]
I mean running @edit in REPL from VS Code tetminal returned error (see above)

**Comment by musm** [comment]
Hard to tell what's going on but it certainly seems like something is  misconfigured on the VS Code side and I have doubts it's on the Julia end.
