### ISSUE TITLE
get(::Dict{DataType,T}, key, default) fails to get the right value

### ISSUE THREAD

**Issue by yeesian** [JuliaLang/julia#40521]
The following command fails on the macOS binary for Julia 1.6:

```julia
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> get(Dict{DataType,Integer}(
           Any         => 0,
           UInt8       => 1), UInt8, error("Unknown DataType"))
ERROR: Unknown DataType
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ REPL[1]:1
```

It works if it's indexed directly (per https://discourse.julialang.org/t/using-datatype-as-key-in-dict ):

```julia
julia> Dict{DataType,Integer}(
                  Any         => 0,
                  UInt8       => 1)[UInt8]
1
```

If it helps for motivation/context: I was looking into not using the indexing behavior due to https://github.com/yeesian/ArchGDAL.jl/issues/178.

**Comment by simeonschaub** [comment]
The arguments to any function call are always evaluated first, so this behavior is expected. `get` does have a method accepting a function as the first argument though for exactly this use case: https://docs.julialang.org/en/v1/base/collections/#Base.get

**Comment by yeesian** [comment]
> The arguments to any function call are always evaluated first, so this behavior is expected.

That makes sense, thanks for the explanation!
