### ISSUE TITLE
InexactError for operations involving Matrix{Number}

### ISSUE THREAD

**Issue by weiyang607** [JuliaLang/julia#40527]
When performing operations such as, `eigvals`, `qr(A)`, on a matrix `A` of type `Matrix{Number}`  but with complex entries.  An inexact Error will pop-up
![image](https://user-images.githubusercontent.com/26447348/115273918-22c6cc80-a10e-11eb-8d5f-62a89771ab9f.png)
```julia
using LinearAlgebra
A = zeros(Number,5,5)

for i in 1:5,j in i:5
    A[i,j] = rand(ComplexF64)
end

print(typeof(A))
eigvals(A)
# A^(-1)
# qr(A)
```

But this can be walk around by converting the matrix type to `Matrix{ComplexF64}`
![image](https://user-images.githubusercontent.com/26447348/115274197-6c171c00-a10e-11eb-8efe-67e407d25abb.png)
```julia
eigvals(convert(Matrix{ComplexF64},A))
```

Maybe we should be able to handle the computations without converting the type of the matrix.

I'm using 
> Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by dkarrasch** [comment]
This is due to the following definition:
```julia
eigtype(T) = promote_type(Float32, typeof(zero(T)/sqrt(abs2(one(T)))))
```
which returns `Float64` for `T = Number`. Why do you need such an abstract number type? Have you tried `GenericLinearAlgebra.jl`?

**Comment by weiyang607** [comment]
@dkarrasch 
This happens for example: when we have a initial matrix 
```julia
A=zeros(5,5)
5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
```
Then at a future time, we want to update some of the entries by a complex number.

```julia
 A[1,1] = 1+im
ERROR: InexactError: Float64(1 + 1im)
```

If we choose to initialize our matrix with `ComplexF64`, the output is quiet ugly (my opinion) when now of the entries are actually zero. 

```
 A = zeros(ComplexF64,5,5); A[1,1] = 1 ; A
5×5 Matrix{ComplexF64}:
 1.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im  0.0+0.0im
```

Initialize with `Number` appear to be cleaner
```julia
 A = zeros(Number,5,5); A[1,1] = 1 ; A[1,2] = im; A
5×5 Matrix{Number}:
 1  im  0  0  0
 0   0  0  0  0
 0   0  0  0  0
 0   0  0  0  0
 0   0  0  0  0
```

**Comment by dkarrasch** [comment]
> the output is quiet ugly (my opinion)

Is this your only issue with the ComplexF64 type? If so, then just don't look at it. 😛  Picking an abstract type for the purpose of generating nicer visual output is not a good idea. You will pay a major performance price even for simple things like matrix-matrix-multiplication.

**Comment by oscardssmith** [comment]
Re-opening. This specific use case probably isn't a good usage of Julia, but it's not that hard to imagine this causing harder to avoid problems.

**Comment by weiyang607** [comment]
🤣 Perhaps a better specific case is in Random Matrix Theory
```julia
A = zeros(5,5)

for i in 1:5, j in i:5
     A[i,j] = rand([1,im])
end

eigvals(A)
```
At some point, error will happen with positive probability.

**Comment by dkarrasch** [comment]
Just for my own understanding: do you have a good reason not to initialize `A = zeros(ComplexF64, 5, 5)`? I mean, of course, you can't write a complex number into a real matrix.

**Comment by weiyang607** [comment]
I don't really have a good reason for it.

The best thing to hope is `A=zero(n,n)` can work.

But this will be difficult I imagine, as the following matrix of type `Matrix{Float64}` not `Matrix{Int64}` 
```julia
A=zeros(5,5)
5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
```

**Comment by dkarrasch** [comment]
The `zeros` function is documented:
```julia
help?> zeros
search: zeros count_zeros set_zero_subnormals get_zero_subnormals leading_zeros trailing_zeros zero ZeroPivotException iszero RoundToZero RoundFromZero

  zeros([T=Float64,] dims::Tuple)
  zeros([T=Float64,] dims...)

  Create an Array, with element type T, of all zeros with size specified by dims. See also fill, ones.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> zeros(1)
  1-element Vector{Float64}:
   0.0
  
  julia> zeros(Int8, 2, 3)
  2×3 Matrix{Int8}:
   0  0  0
   0  0  0
```
And, of course, you can't write a non-integer number into an integer array. These are not "problems in the design of the language". You initialize the array with the type that you're planning to write into it, that's it. I suggest to move the discussion to https://discourse.julialang.org/.
