### ISSUE TITLE
Inconsistency in allowed precision for `BigFloat`

### ISSUE THREAD

**Issue by goualard-f** [JuliaLang/julia#40538]
The `setprecision` method forbids using a precision strictly less than 2 for `BigFloat`s. On the other hand, the constructor for `BigFloat` allows choosing a precision down to 1:

```julia
julia> setprecision(1)
ERROR: DomainError with 1:
`precision` cannot be less than 2.
Stacktrace:
 [1] setprecision
   @ ./mpfr.jl:819 [inlined]
 [2] setprecision(precision::Int64)
   @ Base.MPFR ./mpfr.jl:825
 [3] top-level scope
   @ REPL[78]:1

julia> precision(BigFloat(0.1,1))
1
```

**Comment by stevengj** [comment]
Seems like a one-line fix to [here](https://github.com/JuliaLang/julia/blob/39caf28d64ec17e4957f0c437e7970b0b11d98cc/base/mpfr.jl#L818).
