### ISSUE TITLE
ERROR: The following package names could not be resolved:  * DataFrames (not found in project, manifest or registry) Please specify by known `name=uuid`.

### ISSUE THREAD

**Issue by paschok** [JuliaLang/julia#40531]
Hi! I'm new to Julia and this is my first issue ever. First of all, I'd like to say that I encountered this problem as I installed **Julia-Pro** (specifically Current stable release v1.5.4-1), which led to the following problem. The thing is, that before I installed **Julia-Pro** I could install packages just fine.

I tried to install a package like this: (the issue is not in the DataFrames package, I tried a lot of packages and non of them managed to get installed)

`Pkg.add("DataFrames")`

and received this error:

_ERROR: The following package names could not be resolved:  * DataFrames (not found in project, manifest or registry) Please specify by known `name=uuid`._

#### But I wanted to point out my solution, which I found:
As you install Julia-Pro, you are asked to enter a url from where packages will be installed or you can leave the field blank, which they say means "use default registry". On my first run with Julia-Pro I left that field blank and had that errors. Then I deleted it and installed again. On my second install, I copied an example url from that exact popup window and entered in the field. After that everything worked fine. 

My guess is that this is something to do with Julia-Pro, not Julia itself and I just wanted to point such issue in case anyone finds it helpful

**Comment by bmharsha** [comment]
Hello,

This issue is not related to Julia, you can contact juliapro@juliacomputing.com for issues related to JuliaPro in future. Your original issue might have been caused due to lack of or corrupted `General` registry, if you're still facing this issue, I would suggest you to manually delete following folder
 
If you're using Mac or Linux then delete
```
~/.julia/registries/General
```

In case of Windows
```
<HOME-DIRECTORY>\.julia\registries\General
``` 

Once General registry is deleted, you can execute following command in JuliaPro REPL to fix this issue

```
Pkg.Registry.add(Pkg.RegistrySpec(url = "$(Pkg.pkg_server())/registry/General", uuid = "23338594-aafe-5451-b93e-139f81909106"))
```

**Comment by paschok** [comment]
@bmharsha thank you so much! I recently encountered this error here : _ERROR: The following package names could not be resolved:  * CSV (not found in project, manifest or registry)_ and your solution worked for me!

**Comment by rezabayani** [comment]
@bmharsha You saved my day. Had the exact issue with JuliaPro and your fix solved it.

**Comment by lacorreia65** [comment]
I had the same problem and followed the procedure. After deleting the <>\.julia\registries\General directory, when running the "Pkg.Registry.Add(..." command on Julia REPL I am getting the following error:
"ERROR: Could not determine command" - maybe I am doing something wrong but I really don't know what is wrong b/c I copied the exact command.

I am using Julia 1.5.3, does it has something to do with this error?

Thank you.

**Comment by KristofferC** [comment]
It seems you are in the Pkg REPL mode. You should execute that in the normal Julia mode. Press Ctrl+C in the Pkg REPL to go back to the Julia REPL.

**Comment by lacorreia65** [comment]
Thank you for the update. 
I installed the last version 1.6.2 with Anaconda to use Jupyter Notebook, apparently the issue was resolved as I am able to install packages inside the notebook. :)

**Comment by garfield-gray** [comment]
> Hello,
> 
> This issue is not related to Julia, you can contact [juliapro@juliacomputing.com](mailto:juliapro@juliacomputing.com) for issues related to JuliaPro in future. Your original issue might have been caused due to lack of or corrupted `General` registry, if you're still facing this issue, I would suggest you to manually delete following folder
> 
> If you're using Mac or Linux then delete
> 
> ```
> ~/.julia/registries/General
> ```
> 
> In case of Windows
> 
> ```
> <HOME-DIRECTORY>\.julia\registries\General
> ```
> 
> Once General registry is deleted, you can execute following command in JuliaPro REPL to fix this issue
> 
> ```
> Pkg.Registry.add(Pkg.RegistrySpec(url = "$(Pkg.pkg_server())/registry/General", uuid = "23338594-aafe-5451-b93e-139f81909106"))
> ```

@bmharsha 

I wanted to add GLVisualize & ran to the same error
I deleted the directory and ran the command but the error's still there
I'm using ubuntu by the way
thanks
