### ISSUE TITLE
[Request] add dropdims!(A;  dims) to base

### ISSUE THREAD

**Issue by emirojaseng** [JuliaLang/julia#40536]
Hello,
I would like to propose adding an equivalent to `A=dropdims(A; dims)` that modifies its argument in-place.

I believe a function like  `dropdims!(A; dims)` would allow for clearer code since it's the same use case as `sort `vs `sort!`

**Comment by bicycle1885** [comment]
I think it is impossible to implement a function that changes the type of its argument in-place. Since the dimension of an array is encoded in its type, the in-place version of `dropdims` cannot be implemented.

**Comment by dkarrasch** [comment]
Also, I think it is unnecessary, since the original and the `dropdims`ed array share memory:
```julia
julia> A = rand(3,3,1)
3×3×1 Array{Float64, 3}:
[:, :, 1] =
 0.439824  0.0904852  0.424923
 0.120593  0.615044   0.48804
 0.162919  0.769726   0.653181

julia> B = dropdims(A, dims=3)
3×3 Matrix{Float64}:
 0.439824  0.0904852  0.424923
 0.120593  0.615044   0.48804
 0.162919  0.769726   0.653181

julia> B[1,1] = 1;

julia> A
3×3×1 Array{Float64, 3}:
[:, :, 1] =
 1.0       0.0904852  0.424923
 0.120593  0.615044   0.48804
 0.162919  0.769726   0.653181
```
so there is no loss in "not being in-place".

**Comment by fredrikekre** [comment]
> the original and the dropdimsed array share memory

Would be good to document this. (cf. docstring of `reshape`)
