### ISSUE TITLE
Float32(sqrt(2)) = 1.4142135f0 ?

### ISSUE THREAD

**Issue by louiev** [JuliaLang/julia#40548]
Julia 1.6.0 on Windows 10:

julia> Float32(sqrt(2))
1.4142135f0

Why is there an "f" in the result?

**Comment by sostock** [comment]
It signifies that the value is a `Float32` (as opposed to a `Float64`). `Float32` values are printed with an `f` instead of an `e` before the exponent. In order to distinguish `Float64`s from `Float32`s, the exponent is printed even when it is `0`:
```julia
julia> Float32(1_000_000), Float64(1_000_000)
(1.0f6, 1.0e6)

julia> Float32(1), Float64(1)
(1.0f0, 1.0)

```

**Comment by StefanKarpinski** [comment]
For future reference, it's better to ask questions like this on https://discourse.julialang.org.
