### ISSUE TITLE
Use tagged pointers in non-isbits Unions

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#40550]
In Julia [isbits Union fields have an optimized memory layout](https://docs.julialang.org/en/v1/devdocs/isbitsunionarrays/), but that is not the case for non-isbits (let's call them pointer-unions).
I propose that pointer-unions are implemented with [tagged pointers](https://en.wikipedia.org/wiki/Tagged_pointer)

For example:

```julia
julia> struct Foo
           x::Union{String, Nothing}
       end
```
Currently, a Foo has the following (internal) layout:
```
Stack                            Heap
                                 Address   Content
Foo:                             X-8       Ptr to String or Nothing
    x: Ptr to address X ------>  X...      String data
```
If you have a `Foo` containing `nothing`, Julia needs to follow the pointer in `Foo` to the heap, get the pointer at address `X-8`, and follow that to `Nothing`, after which Julia can return the content.

Instead, an all-zero bitpattern could be used to signify the singleton type. In that case, the content of the `Foo` containing `nothing` can be read directly from the `Foo`. Also, fields containing a `String` would still save one pointer load. Furthermore, uninitialized memory with `Foo`s would contain `Foo(nothing)` instead of `#undef`. While I realize no promises can be made in terms of what uninitialized memory contains, at least it's nicer to have it implemented as returning a fully formed, valid `Foo`.

__Advantages__
* Faster access to pointer-union fields
* (slightly) less memory usage on the heap
* Avoid `#undef` fields

__Disadvantages__
I have no idea, maybe it's hard to implement or will create nasty edge cases.

**Comment by vtjnash** [comment]
> needs to follow the pointer in Foo to the heap

I'm not sure what this means. Foo isn't a pointer, so there's nothing to follow. `Nothing` / `nothing` isn't in the heap (it is in the system image) so nothing is accessed in the heap in this case. Using a particular random bit pattern (which happens to also be a pointer) instead of all-zeros is a behavioral design decision, and isn't related to the presence of #undef fields (though it does simplify the implementation).

**Comment by jakobnissen** [comment]
I must have seriously misunderstood how some of these things work. 😅, so closing this issue.
