### ISSUE TITLE
.. docstring incorrect unless qualified by module name

### ISSUE THREAD

**Issue by anowacki** [JuliaLang/julia#40563]
Attempting to get the docstring for the `..` function always erroneously returns an auto-generated docstring for the (nonexistent) dotted-`.` operator, unless it is qualified with the module in which it is defined/imported:

```julia
julia> ..
ERROR: UndefVarError: .. not defined

julia> "Docstring for `..`"
       ..(a, b) = a + b

..

julia> 

help?> ..
search: .. ...

  x .. y is akin to broadcast(., x, y). See broadcast.

help?> Main.:..
  Docstring for ..
```

Ideally, getting the docstring for `..` (`help?> ..` or `@doc ..`) would give the standard `No documentation found.\n\nBinding .. does not exist.` string until it is defined, then give the docstring of the function when it is.

This undesired behaviour occurs on Julia v1.5.3 and v1.6.0, but not on Julia v1.0.5, where it works as expected.  I have not tested on v1.1 to v1.4.

(I have looked for issues here as well as in [Intervals.jl](https://github.com/invenia/Intervals.jl) and [IntervalSets.jl](https://github.com/JuliaMath/IntervalSets.jl) which export `..`, but not found anything related to this.  Apologies if I have missed it.)

**Comment by simeonschaub** [comment]
If anyone is interested in tackling this, see https://github.com/JuliaLang/julia/pull/39975, which fixed a very similar issue.

**Comment by RohitRathore1** [comment]
@simeonschaub In which file I can find?

**Comment by simeonschaub** [comment]
Take a look at the diff in https://github.com/JuliaLang/julia/pull/39975. You would need to change the `elseif isdotted` right below.

**Comment by RohitRathore1** [comment]
> Take a look at the diff in #39975. You would need to change the `elseif isdotted` right below.

Okay, thanks.

**Comment by Pramodh-G** [comment]
> If anyone is interested in tackling this, see #39975, which fixed a very similar issue.

Hi @simeonschaub ! Is this essentially a mirror of #39975 ? More specifically, would I just need to add the following lines?

at `elseif isdotted`, I add the following
```julia
elseif isdotted && ex !== :(..)
```
and I add tests as normal?

**Comment by simeonschaub** [comment]
Yes, that looks right. Further details can always be discussed after a PR has been opened.
