### ISSUE TITLE
Sparse matrix scalar multiplication: type inference problem

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#40568]
I encounter a case where scaling a sparse matrix (i.e. multiplying it with a scalar) does not properly infer the result type, and returns a sparse matrix with element type `Any`.

```Julia
julia> using SparseArrays
julia> using StaticArrays

julia> A = SMatrix{1,1}([1])
julia> B = SMatrix{1,1}([A])
julia> Bs = sparse([1], [1], [B], 1, 1)
julia> 1*Bs
1×1 SparseMatrixCSC{SMatrix{1, 1, SMatrix{1, 1, Int64, 1}, 1}, Int64} with 1 stored entry:
 [[1]]

julia> 1.0*Bs
1×1 SparseMatrixCSC{Any, Int64} with 1 stored entry:
 SMatrix{1, 1, Float64, 1}[[1.0]]
```

The element type is essentially `SMatrix{SMatrix{Int}}`, i.e. not trivial. Multiplying a sparse matrix with this element type by `1` (an `Int`) works fine. Multiplying it by `1.0`, i.e. creating a new matrix with element type `Float64`, doesn't infer the new element type properly.

The multiplication of the underlying sparse matrix elements works fine:
```Julia
julia> 1.0*B
1×1 SMatrix{1, 1, SMatrix{1, 1, Float64, 1}, 1} with indices SOneTo(1)×SOneTo(1):
 [1.0]
```

I had a look at the code in `linalg.jl` of the `SparseArrays` package, but I couldn't figure out which function implements this multiplication. Any pointers?

**Comment by simeonschaub** [comment]
The underlying problem here is that scalar multiplication of nested SMatrices is not type stable:
```julia
julia> @code_warntype 1. * B
MethodInstance for *(::Float64, ::SMatrix{1, 1, SMatrix{1, 1, Int64, 1}, 1})
  from *(a::Number, b::StaticArray) in StaticArrays at /home/simeon/.julia/packages/StaticArrays/rKBnO/src/linalg.jl:20
Arguments
  #self#::Core.Const(*)
  a::Float64
  b::SMatrix{1, 1, SMatrix{1, 1, Int64, 1}, 1}
Body::SMatrix{1, 1, _A, 1} where _A
1 ─      nothing
│   %2 = StaticArrays.broadcast(StaticArrays.:*, a, b)::SMatrix{1, 1, _A, 1} where _A
└──      return %2
```
This is likely something that needs to be fixed in StaticArrays.
