### ISSUE TITLE
UndefRefError accessing field of Box'ed object

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#40576]
Ran into this working on Memoization.jl's closure functionality. A simple MWE on Julia 1.0 - 1.6:

```julia
let
    foo() = foo
    typeof(foo).instance
end # UndefRefError
```

If we make `foo` not get boxed (which happened above apparently because of the circular reference), there's no error:

```julia
let
    foo() = 1
    typeof(foo).instance
end # (::var"#foo#126") (generic function with 1 method)
```

**Comment by simeonschaub** [comment]
The error you are getting is unrelated to any variables getting boxed, it's just that `foo` is a captured variable of the closure. The `typeof(foo).instance` trick will only work if `foo` does not have any captured fields, so this is not a reliable way to reconstruct closures from their type. In general, you will need to know the values a closure captures to reconstruct it.

**Comment by marius311** [comment]
> it's just that foo is a captured variable of the closure

Ah right, good point, thanks. 

However, maybe this inconsistency seems like it could be considered a bona-fide bug? 

```julia
let
    foo() = foo
    @show hasproperty(typeof(foo), :instance) # shows true
    typeof(foo).instance # UndefRefError
end 
```

**Comment by simeonschaub** [comment]
That's expected. `hasproperty` falls back to `hasfield` by default, which doesn't check if fields are actuallly defined or not. This is also just an implementation detail of `DataType`s, so users should typically not rely on these fields.
