### ISSUE TITLE
Issue with compiling on archlinux

### ISSUE THREAD

**Issue by InfRandomness** [JuliaLang/julia#40577]
Hello;

I am trying to compile Julia on archlinux using [this guide](https://github.com/JuliaLang/julia#building-julia) but somehow it is failing with the following error whenever I try to run either make or make release
![image](https://user-images.githubusercontent.com/43730933/115797303-e62bf700-a3d3-11eb-9043-e259adb103c3.png)

I have checked multiple times if all the required components (sh, python, bsdtar AND gnu tar, they're all here, I do not understand why this is failing)
This is happening on master and I assume every other commits/releases; I have tried checking out the v1.6.0 but the same happens.
What's even weirder is that this works perfectly fine on another computer that also runs archlinux :thinking: 

This system that is having that error rocks : 
LVM 11.1.0
tar (GNU tar) 1.34
bsdtar 3.5.1 (- libarchive 3.5.1 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.5)
GNU Make 4.3
NOTE : /bin/sh is a symlink to bash
GNU bash, version 5.1.4
Python 2.7.18
Python 3.9.3
(the python binary links to python3)

Please let me know if you need more informations about this

**Comment by adamslc** [comment]
Is `tar` in your path? Also, it is helpful to include the text of errors rather than a screenshot.

**Comment by InfRandomness** [comment]
yes, tar is in my path
```
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: line 1: {python|python3|python2} not found: command not found
/bin/sh: --: invalid option
Usage:  /bin/sh [GNU long option] [option] ...
        /bin/sh [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --pretty-print
        --rcfile
        --restricted
        --verbose
        --version
Shell options:
        -ilrsD or -c command or -O shopt_option         (invocation only)
        -abefhkmnptuvxBCHP or -o option
/home/build-testing/src/julia/Make.inc:753: *** "please install either GNU tar or bsdtar".  Stop.
```

**Comment by simeonschaub** [comment]
It looks like the Makefile can't find a Python binary on your system. Can you double check that either of `python`, `python3` or `python2` is available in your PATH?

**Comment by InfRandomness** [comment]
I just checked, they are in /usr/bin and /usr/bin is in my PATH

**Comment by mgkuhn** [comment]
Could you capture the complete output of `make` with
```
make 2>&1 | tee build.log
```
and then attach the resulting `build.log` file here, such that we can scroll through all of it?

**Comment by InfRandomness** [comment]
hum... one kernel update and 5 reboot later, I just relaunched the compiling process to give you the log file but now it works ...
I have no idea what happened there :thinking:;
Fixed!
