### ISSUE TITLE
DataFrames.jl not updating to latest version 1.0 unless I delete all my packages

### ISSUE THREAD

**Issue by azev77** [JuliaLang/julia#40588]
```julia
(@v1.6) pkg> status DataFrames
      Status `~/.julia/environments/v1.6/Project.toml`
  [a93c6f00] DataFrames v0.22.7

(@v1.6) pkg> update DataFrames
    Updating registry at `~/.julia/registries/General`
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`
```

**Comment by KristofferC** [comment]
You probably have some other package installed in the environment that is not compatible with it. You can try `pkg> add DataFrames@1` and see what it says.

**Comment by azev77** [comment]
- After I deleted all my packages, I added DataFrames.jl and it installed the latest version. 
- Should the package manager give a warning if `update DataFrames` doesn't install the latest version?

**Comment by KristofferC** [comment]
> After I deleted all my packages, I added DataFrames.jl and it installed the latest version.

Yeah, because then no other package restricts the compatibility.

> Should the package manager give a warning if update DataFrames doesn't install the latest version?

Some kind of information might be good, I did some experiments in https://github.com/JuliaLang/Pkg.jl/pull/2284.
