### ISSUE TITLE
bytesavailable returns zero for pipe created with redirect_stdout/redirect_stderr, even when bytes are available

### ISSUE THREAD

**Issue by toivoh** [JuliaLang/julia#40597]
In Julia 1.6.0:

	julia> (rd, wr) = redirect_stderr()
	(Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x000000000000029c) open, 0 bytes waiting), Base.PipeEndpoint(Base.Libc.WindowsRawSocket(0x0000000000000294) open, 0 bytes waiting))

	julia> println(wr, "Hello")

	julia> bytesavailable(rd)
	0

	julia> readavailable(rd)
	6-element Vector{UInt8}:
	 0x48
	 0x65
	 0x6c
	 0x6c
	 0x6f
	 0x0a

As you can see `bytesavailable(rd)` returns zero even though there is data to be read. `flush(wr)` doesn't seem to help.

What I want is a non-blocking way to read the data that is available from the pipe. But `bytesavailable` doesn't tell me if there is any data available and all ways to read it that I have tried block if there is no data, including `readavailable`. Either way, I'd like to be able to call a blocking read function to read the actual number of bytes available, if there are any.

**Comment by captchanjack** [comment]
Seeing the same with `TCPSocket`:

```
ulia> using Sockets

julia> socket = TCPSocket()
TCPSocket(RawFD(0xffffffff) init, 0 bytes waiting)

julia> connect(socket, 6379)
TCPSocket(RawFD(0x00000017) open, 0 bytes waiting)

julia> write(socket, "nobytes")
7

julia> bytesavailable(socket)
0
```

**Comment by vtjnash** [comment]
I think this question has already been answered elsewhere.

**Comment by toivoh** [comment]
I'm sorry, but where has this already been answered? I tried to search, but I did not come up with anything.
Is it supposed to be like this? The documentation for `bytesavailable says`

"Return the number of bytes available for reading before a read from this stream or buffer will block."

As demonstrated above, this is not always the case. In my example, it returned zero, but there was 6 bytes available to read without the read blocking.

**Comment by mbaz** [comment]
This is my understanding:

* The best option would be to use `read(rd, nb, all=false)`, which returns up to `nb` bytes, but this is not supported for all streams:
```
julia> (rd, wr) = redirect_stderr()
(Base.PipeEndpoint(RawFD(21) open, 0 bytes waiting), Base.PipeEndpoint(RawFD(22) open, 0 bytes waiting))

julia> println(wr, "Hello")

julia> read(rd, 100, all=false)
ERROR: MethodError: no method matching read(::Base.PipeEndpoint, ::Int64; all=false)
```
* If you know that the stream contains an "end of message" sequence, you can use `readuntil`:
```
julia> (rd, wr) = redirect_stderr()
(Base.PipeEndpoint(RawFD(21) open, 0 bytes waiting), Base.PipeEndpoint(RawFD(22) open, 0 bytes waiting))

julia> println(wr, "Hello\nENDOFMESSAGE")

julia> readuntil(rd, "ENDOFMESSAGE\n")
"Hello\n"
```
* The final alternative is to wrap `read` in a task, read byte by byte, and use a channel to communicate with the task:
```
julia> ch = Channel{Char}(100)
Channel{Char}(100) (empty)

julia> reader = @async begin
                         while true
                           c = read(rd, Char)
                           put!(ch, c)
                         end
                       end
Task (runnable) @0x00007f67d8c34e80

julia> isready(ch)
false

julia> println(wr, "Hello")

julia> isready(ch)
true

julia> while isready(ch)
       println(take!(ch))
       end
H
e
l
l
o



julia>
```
