### ISSUE TITLE
:= Returns Incorrect Documentation

### ISSUE THREAD

**Issue by Closed-Limelike-Curves** [JuliaLang/julia#40600]
Using `help?> :=` returns the following (Incorrect) information:

```x := y is a synonym for x = x : y```

However, `:=` is not currently valid syntax. This should be fixed, and should probably also be made to do something. `:=` is currently recognized as an assignment operator, but is not actually usable, which can cause confusion for programmers coming from languages like Pascal where `:=` is the assignment operator, or for programmers coming from Python where `:=` has a distinct meaning.

My own suggestion would be to make `:=` an alias for `=`, and additionally make `=?` an alias for `==`, so that people interested in writing more readable code can do so (although maintaining the traditional `=` and `==` for programmers who are used to them).

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/39427

**Comment by Closed-Limelike-Curves** [comment]
> #39427

Not sure this fixed it -- the error is still appearing on Julia 1.6.1, and the merge seems to have been done prior to 1.6.1?

**Comment by simeonschaub** [comment]
The fix has been merged after 1.6 was branched and was never backported. I have marked it to be backported to the next 1.6 patch release.
