### ISSUE TITLE
~2x slowdown from 1.5.4 -> 1.6

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#40619]
Taking the following code, which measures iteration over `ChainecVector`, I see a ~2x slowdown from Julia 1.5.4 -> 1.6 on macOS.

```julia
using SentinelArrays, BenchmarkTools
A = ChainedVector([[j for j = 1:1000] for i = 1:8])
function eachind2(A)
    x = 0
    for y in A
        x += y
    end
    return x
end
```

1.5.4:
```julia
julia> @btime eachind2(A)
  11.285 μs (1 allocation: 16 bytes)
4004000
```

1.6:
```julia
julia> @btime eachind2(A)
  20.675 μs (1 allocation: 16 bytes)
4004000
```

**Comment by oscardssmith** [comment]
for my own sanity, I've updated the mwe so the variable names match.

**Comment by johnnychen94** [comment]
I believe this is related to #38073 (due to my notorious #37829 commit)...

But probably is CPU-dependent? (I can't reproduce it and is not capable of figuring out the root issue)

```julia
julia> @btime eachind2($A)
  4.288 μs (0 allocations: 0 bytes) # Julia 1.6.1
  4.285 μs (0 allocations: 0 bytes) # Julia 1.5.4

julia> versioninfo()
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by quinnj** [comment]
Hmmm, `ChainedVector` [iteration](https://github.com/JuliaData/SentinelArrays.jl/blob/fe14a82b815438ee2e04b59bf7f337feb1ffd022/src/chainedvector.jl#L91) doesn't use CartesianIndices at all though, so at first glance, I'd say unrelated?

**Comment by KristofferC** [comment]
I can not repro on my linux desktop, nor my mac laptop (16''). Both have pretty much the exact same performance in 1.5.4 and 1.6.1.

**Comment by MarcMush** [comment]
maybe `SentinelArrays` or another package is not the same version in your 1.5 and 1.6 installations ?

**Comment by KristofferC** [comment]
1.2.16 in both cases.

**Comment by MarcMush** [comment]
I meant @quinnj

**Comment by quinnj** [comment]
My bad; it turns out I had removed the `@inline` on the first `function Base.iterate(x::ChainedVector)` and that somehow totally blew up performance.
