### ISSUE TITLE
Can you remove GC（garbage collection）?

### ISSUE THREAD

**Issue by zhuxiujia** [JuliaLang/julia#40629]
Can you remove GC（garbage collection）?

Except for complex reference scenarios, most scenarios can be replaced by counting references or RAII。
At the same time do not change Julia's grammar rules。

If encounter circular references or complex scenarios, use traditional GC

Benefits: Low memory overhead, greatly reduced pauses, better suited for embedded devices。
More importantly, it will provide performance

**Comment by KristofferC** [comment]
This discussion is not useful to have on this level. Feel free to open an post at https://discourse.julialang.org/ to discuss it.
