### ISSUE TITLE
Println doesn't print content of Array{Set,1} correctly in Julia 1.6

### ISSUE THREAD

**Issue by pgagarinov** [JuliaLang/julia#40622]
The following code

```
arr = Array{Set,1}(undef, 3);
println("$arr")
arr
```
prints

```
Set[#undef, #undef, #undef]

3-element Vector{Set}:
 #undef
 #undef
 #undef
```

which seems strange as I would expect `println("$arr")` to produce `[#undef, #undef, #undef]` instead of `Set[#undef, #undef, #undef]`. After all, arr is an array, not a set.

**Comment by fredrikekre** [comment]
`Set` is the element type, the printing looks correct to me.
