### ISSUE TITLE
Parsing issue for "test$i" format in documenter section

### ISSUE THREAD

**Issue by walra356** [JuliaLang/julia#40625]
I have a parsing issue the lines below:
"""
```
["a$i" for i=1:5]
```
"""
ans:  UndefVarError: i not defined

An obvious workaround is:
"""
```
["a" * string(i) for i=1:5]
```
"""
ans: "```\n[\"a\" * string(i) for i=1:5]\n```\n"

This solves my problem but I wanted to report the issue.
Thanks for creating JULIA.

**Comment by KristofferC** [comment]
`$` is string interpolation. Maybe you meant `\$i` to escape the `$`?

**Comment by walra356** [comment]
Super! fast and appropriate. Thanks for the fast response!
