### ISSUE TITLE
Mod  and Order Calculation issues

### ISSUE THREAD

**Issue by jdvalderra** [JuliaLang/julia#40639]
I've noticed what seems like errors with both the built in mod calculator and the Mods package. When I look for the order of certain numbers, say 71, the order calculator that comes up from google (http://www.numbertheory.org/php/order.html) says its 35, but when I try either mod(10^(35), 71) or Mod{71}(10^(35))  I get 24. Further, if I try mod(10^(70), 71) or Mod{71}(10^(70)) I get 0, which according to my understanding doesn't make sense since 70 is the totient and should be equivalent to 1(mod 71). Can someone please explain what's going on?

**Comment by oscardssmith** [comment]
As I've explained to you https://github.com/JuliaLang/julia/issues/37376#issuecomment-828022274 Github is not the place to ask questions Discourse, StackOverflow, or Slack are. As I've also explained, the problem is integer overflow.

**Comment by jdvalderra** [comment]
Thank you so much, I'm still very new.
