### ISSUE TITLE
Confusing dispatch

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#40641]
Can someone help me understand if I’m just missing something here, or if it’s some kind of bug? I’m confused at:
```julia
julia> U = Union{Missing, Float64, Int}
Union{Missing, Float64, Int64}
julia> @which convert(U, 1)
convert(::Type{T}, x::T) where T>:Missing in Base at missing.jl:67
```
Why is it dispatching to that convert method where `T >: Missing`? `typeof(1) >: Missing` is false, so I don’t understand why this method is coming up?

**Comment by DilumAluthge** [comment]
`T` is `Union{Missing, Float64, Int}`, right? So then `1 isa T`. And `Missing <: T`.

**Comment by Seelengrab** [comment]
`T >: Missing` is equivalent to `Union{T, Missing}` (if you want to be stylish https://youtu.be/TPuJsgyu87U?t=848), so the convert you end up at is `convert(::Type{Union{T, Missing}}, x::Union{T, Missing}) where T`. `Union{Missing, Union{Missing, Float64, Int}}` is of course just `Union{Missing, Float64, Int64}` again.

**Comment by vtjnash** [comment]
You can also print out `U` next time in the method body
