### ISSUE TITLE
how to set codegen options?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#40655]
Should we have a mechanism for setting codegen options from the command line (in addition to `-O`)? This would potentially make it much harder to cache code, but options such as `JL_DISABLE_FPO` (aka `-fno-omit-frame-pointer`) can just be *so* critical to getting an accurate profile (c.f. https://julialang.org/blog/2019/09/profilers/), and needing a source build to get this is very inconvenient.

**Comment by vchuravy** [comment]
Agreed in particular we should do something about FPO. System profilers are much happier with it.
