### ISSUE TITLE
`@printf` does not accept `*` for passing precision or width as argument

### ISSUE THREAD

**Issue by Maxpxt** [JuliaLang/julia#40654]
The [docs on `@printf`](https://docs.julialang.org/en/v1/stdlib/Printf/#Printf.@printf) state that it follows C-style formatting as specified [here](https://www.cplusplus.com/reference/cstdio/printf/). This spec allows for `*` to be used in the precision and/or width positions to indicate that the precision and/or width will be passed as additional arguments preceding the value to be formatted. Example (in C):

```c
printf("%.*f", 2, 3.141);   // prints "3.14"
printf("%.*f", 4, 3.141);   // prints "3.1410"
```

Currently (Julia 1.6.1), `@pritnf` does not recognize such format specifiers. `@printf "%.*f" 2 3.141` fails with `ArgumentError: invalid format string: '%.*f', invalid type specifier: '*'`.

I don't know whether not supporting this is intended behavior or not. If it is, the docs should be updated to say how Julia's `@printf` differs from the C-style spec.

Here is an example where having this would be useful:

```julia
function format_float_without_trailing_zeros(x, precision)
    rstrip(rstrip((@sprintf "%.*f" precision x), '0'), '.')
end

format_float_without_trailing_zeros(3.1415, 2)  # "3.14"
format_float_without_trailing_zeros(3.0, 2)     # "3"
```

**Comment by bicycle1885** [comment]
#40105 addresses this issue ([Fmt.jl](https://github.com/bicycle1885/Fmt.jl) supports that feature, btw).

**Comment by Maxpxt** [comment]
Oh, I did not think to search the PRs. Should the issue be left open? (Thanks for tip!)

**Comment by bicycle1885** [comment]
> Should the issue be left open?

Yes, I think it should.
