### ISSUE TITLE
Some questions about manual/methods.md

### ISSUE THREAD

**Issue by ptoche** [JuliaLang/julia#40650]
After reading sections of the docs, I still have a few questions. Perhaps the docs could be expanded or some reference could be given to clarify these points. 

line 265

Attempt to clarify what is being said:

The order in which the methods are executed does not matter as methods do not overwrite each other. If you wish to modify a method, you need to restart Julia and re-create all methods. There is no way to "undo" method creation. Not even the last added method. [IS ANY OF THIS TRUE?] However Julia does retain a record of the order in which the methods were created:  ``Base.invokelatest`` allows you to see the last method that was added. 

line 338:

It would be useful to have a verbal interpretation of ``myappend(v::Vector{T}, x::T) where {T} = [v..., x]`` to explain the use of the splat here.

The method ``myappend`` takes two arguments, a vector of elements of type ``T`` (mixing types in this vector will result in an error) and a single element of type ``T`` (Does a single element have a dedicated name? some languages abusively say "scalar"), where the type ``T`` is allowed to be one of ``v`` or ``x``. What does ``...`` do here?

line 824:

Why do I not need a semi-colon to "activate" keyword arguments in this method? As in the following:

```julia
f(;a=1,b=2) = a+2b
```

The [reference given at the start of the paragraph](@ref man-functions) states "Functions with keyword arguments are defined using a semicolon in the signature" and here we are not doing that. 

Tried to fork and edit the docs but it didn't let me save my branch. It would have been easier to see in context. So I copied the current line numbers above.

**Comment by Seelengrab** [comment]
> Does a single element have a dedicated name?

I'd call this an instance of type `T`.

> where the type T is allowed to be one of v or x. What does ... do here?

No. `v` will always be a vector whose elements have type T and the method forces the types of `x` and the type of the elements of `v` to be the exact same. `...` is the regular splatting operator - here it iterates over the vector `v` and unpacks the vector into its individual elements. See the FAQ question on [slurping and splatting](https://docs.julialang.org/en/v1/manual/faq/#The-two-uses-of-the-...-operator:-slurping-and-splatting).

> Why do I not need a semi-colon to "activate" keyword arguments in this method?

Not sure what you mean here - you _do_ need the semi-colon for keyword arguments? `f(a=1,b=2,c=4)`  are just regular positional arguments with default values, whereas keyword arguments (those after the `;`) have no order associated with them.

**Comment by ptoche** [comment]
Thanks a lot Seelengrab!

From the docs, the meaning of ``v::Vector{T}, x::T``  is understandable, and much clarified by your description: "x and every element of v must be the same type T." But the second part is still unclear to me.  How would you verbally read this: ``where {T} = [v..., x]`` ?  

I don't suppose the curly brackets have anything to do with set notation... then do the square brackets have anything to do with vector notation ...? I guess I expected something shorter like ``where T = v``, because we want to constrain the new vector to be of type ``T``.  It confused me to see the ``x`` in there, since it's an argument, not the method's output (or am I mistaken about that too?) 

The manual has another example ``where {T} = true``, but all it says about it is (rephrased for clarity) "type parameter T qualifies the signature". Elsewhere the docs have ``where T`` with no curly bracket. Do the curly brackets have a special meaning? Like singleton?

IMHO a short version of the above clarifications would be useful to make the docs clearer, near the line numbers I have marked. 

The point about the semi-colon is that it's not in the manual. If you're right then it must be a typo.

**Comment by elextr** [comment]
The part of the definition after the `=` is the definition of the method, ie its return value which is simply a vector made of the elements of `v` with `x` appended and its specified using the normal literal syntax for a vector `[ ]`, see https://docs.julialang.org/en/v1/manual/arrays/#man-array-literals

**Comment by ptoche** [comment]
I believe I understand some critical things now. Thanks to Seelengrab and elextr for your help!

I made a pull request where I added some explanations that hopefully can serve to clarify the docs for newbies like myself.

https://github.com/JuliaLang/julia/pull/40667
