### ISSUE TITLE
Make install should automatically install julia in /usr/local

### ISSUE THREAD

**Issue by xgupta** [JuliaLang/julia#40676]
An extra step is needed to run julia from anywhere i.e. create a Make.user file in the root directory. 
That is not feel good.

**Comment by ViralBShah** [comment]
It is by design that Julia does not install files all over the system. You need to just add `julia` to the path or symlink it.

**Comment by oscardssmith** [comment]
I think there should be an easy way in the make file to get this behavior. While it's great that Julia doesn't require putting files in various places to run, installing to /usr/local is really common (especially for people that aren't modifying Julia), and should probably be easier.

**Comment by DilumAluthge** [comment]
Does this work?

```
make prefix=/usr/local install
```

**Comment by oscardssmith** [comment]
if it does, then I think the only thing to do is document it in the readme.

**Comment by ViralBShah** [comment]
We explain this for the binaries, iirc and can even be in the docs.I don't think we should be doing this in the README.

**Comment by xgupta** [comment]
> I think there should be an easy way in the make file to get this behavior. While it's great that Julia doesn't require putting files in various places to run, installing to /usr/local is really common (especially for people that aren't modifying Julia), and should probably be easier.

+1 on "common thing". This is first project I have found that does not install binaries in the system path using `make install`. 

( note that I have built 100+ different project )

**Comment by xgupta** [comment]
> Does this work?
> 
> ```
> make prefix=/usr/local install
> ```
Yeah it will work I think.

**Comment by xgupta** [comment]
> +1 on "common thing". This is first project I have found that does not install binaries in the system path using `make install`.
> 
> ( note that I have built 100+ different project )

(Yeah but chapel does not have "make install" target. but they also moving to use CMake build system generator and will want to support out of tree build.)

**Comment by xgupta** [comment]
> (Yeah but chapel does not have "make install" target. but they also moving to use CMake build system generator and will want to support out of tree build.)

Oops they have make install https://chapel-lang.org/docs/usingchapel/building.html#makefile-targets. I forget ...
