### ISSUE TITLE
Feature: support variable name sandboxing of jl_eval_string

### ISSUE THREAD

**Issue by clickingbuttons** [JuliaLang/julia#40673]
I'm implementing an HTTP server that uses the C ABI to run a Julia payload:
```c
jl_eval_string("a = 4"); // Some user input
...
jl_eval_string("a"); // Another user's input... I'd like for `a` not to be defined!
```

Is there a way to reinitialize Julia or clear variables (similar to the deceased `workspace()`) without having to restart the entire webserver's process for each request?

I've brainstormed a following possibilities:
1. Support calling `jl_atexit_hook(0)` -> `jl_init__threading()` after each request (this currently segfaults)
2. Support a new `jl_unset_global` to run on non-default variables defined in `names(Main)`
3. Support redefining the entire main module (unfortunately `jl_set_const(jl_core_module, jl_symbol("Main"), (jl_value_t*)jl_main_module);` throws `ErrorException("invalid redefinition of constant Main")`)
4. Run each user's request in a uniquely generated `Module` and then support unloading those modules

I know to get true sandboxing I'll have to restart the process, but I'm content with some fake sandboxing for now since I trust this server's users to be well-behaved.

**Comment by clickingbuttons** [comment]
After reading through some docs I've found a 5th possibility which works:
```c
jl_eval_string(sprintf("module Test %s end", "a = 4")); // Some user input that they don't know is going to be wrapped in a module. Error messages on the first line will be off by 12 characters.
...
jl_eval_string(sprintf("module Test %s end", "a")); // Another user's input which since using the same module name unloads the old module (I hope!). `a` is not defined at the cost of some `WARNING: replacing module Test.` stdout spam!
...

but I'd still love to hear from a maintainer!

**Comment by vtjnash** [comment]
It sounds like you want a `let` block?

**Comment by clickingbuttons** [comment]
I didn't know `let` blocks existed! Let me better clarify what my HTTP server is doing:
```c
while (1) {
  char[] user_string = read(socket); // Something like "a = 0; f(n::Vector{Float32}) = a+= sum(n)"
  jl_value_t* user_fn = jl_eval_string(user_string);
  jl_value_t* ans;
  for (auto partition : partitions) {
    jl_array_t* shared_array = jl_ptr_to_array_1d(partition.type, partition.data, partition.len, 0)
    ans = jl_call1(user_fn, shared_array);
  }
  write(socket, serialize(ans));
}
```
Cleanup and performance wise what's the difference between reloading a module and executing a new `let` block?

**Comment by JeffBezanson** [comment]
Do you want a user to have a session that keeps state? E.g. I can assign a variable in one request, and use it again in the next? If so, a module per user session is probably the right thing. If not, then a `let` block might be the right thing: all variables will be local and thrown away after it's evaluated.

**Comment by clickingbuttons** [comment]
I don't want any session state so a `let` block seems like the way to go! However, I do rather like that with a module I can tell my users to define a `main` function and then I can grab it with `jl_value_t* user_fn = jl_eval_string("Test.main");`. Is there an equivalent for a `let` block @JeffBezanson or will it always return the last expression inside of it?

**Comment by clickingbuttons** [comment]
The module method works great for me. Closing.

**Comment by vtjnash** [comment]
> Cleanup and performance wise what's the difference between reloading a module

**Comment by vtjnash** [comment]
> Cleanup and performance wise what's the difference between reloading a module

Modules are never cleaned up, let blocks are cleaned up when the return
