### ISSUE TITLE
Unbound type parameters make functions slow

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#40681]
Minimal working example:

```
julia> f() where T = 1;
julia> @code_native f()
```
That one is not too bad, but this one is:
```
julia> f(x::Union{Vector{T}, NTuple{N, T}}) where {N, T} = x[1]
julia> @code_native f([1])
```

The issue is unbound type parameters. It's well know apparently, but I couldn't find any existing issue.

**Comment by johnnychen94** [comment]
I believe this is duplicated to #29393
