### ISSUE TITLE
Sockets Library issue: write delays until program ends

### ISSUE THREAD

**Issue by cfitz25** [JuliaLang/julia#40705]
Hello, for some reason the Sockets library is only writing to sockets after some amount of delay, typically until the program ends.
It appears to sometimes not occur if it is not the first transmission.
```
Julia Version 1.6.1
Commit 6aaedecc44* (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.1.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```
Here is some code that ive found reproduces the issue:
TestClient.jl
```
using Sockets
client=Sockets.connect(8080)
write(client,"Hello")
println(read(client))
```
TestServer.jl
```
using Sockets
server = Sockets.listen(8080)
while true
    conn = Sockets.accept(server)
    data = read(conn)
    println(data)
    write(conn,data)
end
```

**Comment by Seelengrab** [comment]
You'll want to `flush` your stream (or `close`, which also flushes, but sadly closes both read & write ends at the moment).

**Comment by fredrikekre** [comment]
Let's use https://discourse.julialang.org/t/using-the-sockets-library/60448 for further discussions.

**Comment by cfitz25** [comment]
so id want to flush after writing? i think its freezing on the write for me and not allowing a flush to happen
