### ISSUE TITLE
varinfo doesn't take an `io` argument

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#40710]
most functions that display things take an IO argument.
Usually as the first argument, e.g. `code_native` and `versioninfo` do this (which is good cos it makes them compatible with `sprint`)
Sometimes as a keyword argument. e.g. `Pkg.status` does this.
`varinfo` doesn't take on at all, so if you want to get its output into a file, you need to use `redirect_stdout`.

Related to https://github.com/JuliaLang/julia/issues/40709

**Comment by KristofferC** [comment]
What would the `io` argument do? `varinfo` returns a `Markdown.MD` object which is displayed by the REPL. If you want it to display some other way just do that:

```
julia> m = varinfo();

julia> io = IOBuffer();

julia> show(io, MIME("text/plain"), m);

julia> print(String(take!(io)))
  name                    size summary
  –––––––––––––––– ––––––––––– –––––––––––
  Base                         Module
  Core                         Module
  InteractiveUtils 282.343 KiB Module
  Main                         Module
  ans                1.496 KiB Markdown.MD
  b                  1.271 KiB Markdown.MD
  m                  1.496 KiB Markdown.MD
```

**Comment by oxinabox** [comment]
> varinfo returns a Markdown.MD object which is displayed by the REPL. If you want it to display some other way just do that:

Ah, I thought it was printing straight to stdout.
Yeah, an `io` arugment doens't make sense.
