### ISSUE TITLE
Being able to query what module threw an exception

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#40734]
I have been thinking about this for a while, but never written it up.

It would be really useful to be able to track what module threw an exception.
Motivation is the same as https://github.com/JuliaLang/julia/issues/7026
and I will quote from that

> A of the major issues with try/catch is that it's possible to catch the wrong error and think that you are handling a mundane, expected problem, when in fact something far worse is wrong and the problem is an unexpected one that should terminate your program. 
>
> ...only catch errors of that type under certain circumstances in a way that's designed to avoid the problem of accidentally catching errors from an unexpected location that really should terminate the program.
> ...
> Although this [rethrowing based on `isa`] does limit the kinds of errors one might catch, it fundamentally doesn't solve the problem, which is that while there are some places where you may be expecting a BazError to be thrown, other code that you're calling inside the try block might also throw a BazError where you didn't expect it.
> ...
> The problem with typed exceptions is that they give you a sense of precision, but they're not really precise at all.

now #7026 is a pretty bulky (but nonbreaking) change to the language.
I propose here an alternative/supplementary behavour.
It is pragmatic, rather than conclusive.

The problem as states is that types don't tell you where it came from.
Especially since most julia programmers just use a ton of `ErrorException` and `ArgumentError`.
(that has problems beyond this to do with loss of rich information, but that is another discussion).
Conveniently the vast majority of julia modules are small and do one thing.
So knowing which module an exception comes from actually tells us a lot.

Consider:
```julia
try
    Foo.foo()
catch err
    err isa ArgumentError && originating_module(err) == Foo || rethrow()
    ...
end
```

So we are only handling `ArgumentErrors` from `Foo` not any that bubbled up from anything it called.

Implementing this in a nonbreaking way seems hard.
If we were willing to make some things into macros and add fields to exceptions to hold their originating module it isn't, but that is breaking (and kinda annoying).
But perhaps we can pull it out from the backtrace or something.
Maybe we actually an easy way to inspect the backtrace for a list of modules (and functions?) and not touch the exception at all.

**Comment by JeffBezanson** [comment]
Yes, this is part of the backtrace --- in fact you can already see a module for each frame in the standard stack trace printing. Looking at the module doesn't seem like the right abstraction for this to me though. It only very vaguely tells you "who" or why the error was thrown, and is broken for example by calling a convenience function in another module that wraps `throw`.

**Comment by oxinabox** [comment]
> Yes, this is part of the backtrace --- in fact you can already see a module for each frame in the standard stack trace printing. 

Cool, I cna probably just write a little function to do this and play around with it myself.

> It only very vaguely tells you "who" or why the error was thrown, 

Yeah, I agree it is definately not a perfect or complete solution, but I think it might be a useful pragmatic one.
I am however happy to be wrong about this.
Or for there to be a better complete solution just around the corner

> and is broken for example by calling a convenience function in another module that wraps throw.

would `rethrow` be correct still? I guess not since the exception might never even exist, if the helper some that checks a condition (like matching dimension sizes or somehting) and then throws an exception
