### ISSUE TITLE
Version numbers in Windows binaries are incorrect

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#40739]
I think there is a mix-up between the patch and build part of the version number in the Windows binaries. For example, the `julia.exe` shows this:

![image](https://user-images.githubusercontent.com/1036561/117379301-0d7ecb80-ae8c-11eb-8cf9-6866fbb0dd08.png)

Note how the file version is `1.6.0.1`, but I think it should really be `1.6.1.0`.

**Comment by ViralBShah** [comment]
@musm may know.

**Comment by musm** [comment]
Seems like a bug that should be fixed by https://github.com/JuliaLang/julia/pull/40752 I'm not sure why the current code wants to put a zero between the patch
