### ISSUE TITLE
bug: function names does not reported imported variables

### ISSUE THREAD

**Issue by poldavezac** [JuliaLang/julia#40759]
Judging from its docstring, the `names` method should be able  to report imported names as well as others, given the right keyword arguments. I find this is not the cast either in version 1.5.3 or 1.6.1

In the following the array should contain a `:A`.

```julia
julia> module X
       module Y
       struct A end
       export A
       end
       using Main.X.Y: A
       end
Main.X

julia> names(X; all = true, imported = true)
6-element Array{Symbol,1}:
 Symbol("#eval")
 Symbol("#include")
 :X
 :Y
 :eval
 :include
```

**Comment by poldavezac** [comment]
Thank-you for your explanations. I must I find this `import` and `using` business not very easy to keep in mind. A rephrasing of the doc could be useful. Another keyword would have the advantage of documenting the behavior explicitely

**Comment by StefanKarpinski** [comment]
This is all documented in the docstring for `names`. If anyone has a specific wording improvement, please make a pull request.
