### ISSUE TITLE
Survey on globally distributed software engineering

### ISSUE THREAD

**Issue by AsWali** [JuliaLang/julia#40762]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by fredrikekre** [comment]
This seems like a topic for the forum, https://discourse.julialang.org/.
