### ISSUE TITLE
Base.summarysize not properly accounting for Vectors containing certain types

### ISSUE THREAD

**Issue by millerjoey** [JuliaLang/julia#40773]
Hey all. On Julia 1.5.3:
```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

it seems that `Base.summarysize` doesn't recurse deeply enough for `Vector`s containing `Set`s (as well as for our own user-defined type).

```julia
julia> s = Set(1:100)
Set{Int64} with 100 elements:
  2
  89
  11
  29
  74
  57
  31
  78
  70
  33
  96
  ⋮ 
julia> c = [s]
1-element Array{Set{Int64},1}:
 Set([2, 89, 11, 29, 74, 57, 31, 78, 70, 33  …  19, 51, 22, 6, 24, 73, 53, 23, 27, 56])
julia> Base.summarysize(c)
48
julia> Base.summarysize(s)
4800
```
`Array{Array{Int64}}`, `Array{Dict{Int64,Int64}}`, and a few other permutations seem to work fine.

I dug a little bit and I think this has something to do with it and is preventing the function from accessing the set:
```julia
julia> Base.allocatedinline(Dict{Int,Int})
false

julia> Base.allocatedinline(Vector{Int})
false

julia> Base.allocatedinline(Set{Int})
true
```

which is defined here
https://github.com/JuliaLang/julia/blob/e4f79b7167312dab649218b53b84c0829ea0c103/base/array.jl#L157

**Comment by millerjoey** [comment]
I think this has something to do with it:
```julia
julia> Base.allocatedinline(Dict{Int,Int})
false

julia> Base.allocatedinline(Vector{Int})
false

julia> Base.allocatedinline(Set{Int})
true
```

which is defined here
https://github.com/JuliaLang/julia/blob/e4f79b7167312dab649218b53b84c0829ea0c103/base/array.jl#L157

**Comment by JeffBezanson** [comment]
Great catch, you're right --- `allocatedinline` used to mean something didn't contain references, but that's no longer true.

**Comment by ederag** [comment]
To help others who might search for `varinfo` issues: it is affected as well, since `varinfo` uses `summarysize`.

**Comment by ddtarjan** [comment]
As a quickfix, I copied this function replacing "SimpleVector" with "Vector" so it will have a specialization for Vectors also. It helps.
May be this would be the fix for this issue?

```julia
function (ss::SummarySize)(obj::SimpleVector)
    key = pointer_from_objref(obj)
    haskey(ss.seen, key) ? (return 0) : (ss.seen[key] = true)
    size::Int = Core.sizeof(obj)
    if !isempty(obj)
        push!(ss.frontier_x, obj)
        push!(ss.frontier_i, 1)
    end
    return size
```
