### ISSUE TITLE
zero and one methods inconsistent return type

### ISSUE THREAD

**Issue by albheim** [JuliaLang/julia#40796]
My specific case was that I was taking matrix powers of large `CuArrays` and when taking `A^0` it did not return a `CuArray`.

```julia
using CUDA
A = CUDA.randn(2, 2)
B = A^0 # Does not result in a CuArray
C = one(A) # Does not result in a CuArray
```

Filed an issue in with the CUDA.jl package [here](https://github.com/JuliaGPU/CUDA.jl/issues/897) but was told it would be best for this to be fixed upstream if possible.

So the issue comes from calling the `power_by_squaring(x, p)` method which calculates the integer power of a matrix, and for `p==0` it returns `one(x)`.
https://github.com/JuliaLang/julia/blob/dd122918ceb84dad9063a0866fc7b1262a38d273/base/intfuncs.jl#L259

It seems like the problem is from here in the `_one` method where the returned array is created using `zeros(T, m, m)`.
https://github.com/JuliaLang/julia/blob/09d6a03234a1e8fe53d9380fa4bf7d9a01c7fa3d/base/array.jl#L542

I thought I could fix it by just replacing `zeros(T, m, m)` with `zero(x)` (cause `zero(::CuArray)` seems to return the correct thing), but then it complained about scalar operations on the GPU. Tried changing the loop to `I[CartesianIndex.(zip(1:m, 1:m))] .= unit` just to see if something along those lines could work, and it seems okay but slower on the CPU.

I'm not sure if you prefer it being handled here or if it should be CUDA.jl who specifies their own version of `one`. But it seems a bit inconsistent that `zero` will return the same array type (it dispatches to `fill!(similar(x), zero(T))`) while `one` does not, so I would say that it makes sense to fix it here if possible.

Checked the original issue both on julia 1.6.0 and 1.7.0-DEV.1088 with the same results. The updates were only tested on the dev version.

**Comment by albheim** [comment]
>   Return a multiplicative identity for x: a value such that one(x)*x == x*one(x) == x. Alternatively one(T) can take a type T, in which case one returns a
>  multiplicative identity for any x of type T.

I think that allowing scalar operations on the GPU is not good practice and commonly you would want to run with `CUDA.allowscalar(false)` which would make this error. So maybe it can be a pretty bad multiplicative one, but not the one we would like.

It would be a lot easier to just add a specific dispatch in CUDA.jl that could be specialized there for the `CuArray` type, but I feel that if the base implementation could be made to be more general that might be a cleaner solution and it would also be nice for other specialized implementations. But maybe that is not worth it.

**Comment by JeffBezanson** [comment]
@maleadt is there a way to write this more generically that works well for CuArray?

**Comment by mcabbott** [comment]
I believe you can do this with linear indexing, like `LinearAlgebra.diagind`:
```
function _one(unit::T, x::AbstractMatrix) where T
    require_one_based_indexing(x)
    m,n = size(x)
    m==n || throw(DimensionMismatch("multiplicative identity defined only for square matrices"))
    I = fill!(similar(x), zero(T))
    I[1:m+1:end] .= unit
    I
end
```

**Comment by albheim** [comment]
> I believe you can do this with linear indexing, like `LinearAlgebra.diagind`:
> 
> ```
> function _one(unit::T, x::AbstractMatrix) where T
>     require_one_based_indexing(x)
>     m,n = size(x)
>     m==n || throw(DimensionMismatch("multiplicative identity defined only for square matrices"))
>     I = fill!(similar(x, T), zero(T))
>     I[1:m+1:end] .= unit
>     I
> end
> ```

I also went through this alternative when looking for a good fix, and it seems to work fine for both normal arrays and CuArrays, but it is allocating slightly more than the original version when I tried it. For small arrays this results in a performance difference, while for larger arrays it seems to be very similar. But reducing the efficiency on normal arrays seems less optimal than having to create a specific method in CUDA in my opinion.

**Comment by mcabbott** [comment]
Oh right. Why does this allocate?
```
julia> @btime ($(zeros(3,3))[1:4:9].=0; nothing)
  26.146 ns (2 allocations: 80 bytes)

julia> @btime ($(zeros(3,3))[1,:].=0; nothing)
  3.041 ns (0 allocations: 0 bytes)
```

**Comment by maleadt** [comment]
A generic version would be nice, but I don't mind carrying a CuArray-specific version in CUDA.jl to make `one(::CuMatrix)` work. I can put one of these alternative in GPUArrays.jl, so that the Base version doesn't need to regress.

The reason I pointed to Base in https://github.com/JuliaGPU/CUDA.jl/issues/897, is that I read the code too quickly and thought `ones` was being called. Those methods are more of a problem, because we can't override them (there's no `ones(::AbstractArray, dims...)`). Same problems with `zeros`, and scalar code that calls `one`/`zero`. But that doesn't apply here.

**Comment by stevengj** [comment]
I think the root issue here is that `one(::AbstractMatrix)` always returns a `Matrix`: 

https://github.com/JuliaLang/julia/blob/39caf28d64ec17e4957f0c437e7970b0b11d98cc/base/array.jl#L537-L547

So, packages that define their own matrix types should really override this if they want a different type here.

**Comment by JeffBezanson** [comment]
Yes if we were doing this over I wouldn't define `one(::AbstractMatrix)`, only `one(::Matrix)`, as it seems this really does need to be defined for every new array type. Should we change it for now to call `similar` or `copymutable` instead of `zeros`?

**Comment by stevengj** [comment]
> Should we change it for now to call `similar` or `copymutable` instead of zeros?

Possibly — I guess we could do `A .= 0` to initialize it to zero before setting the diagonal entries to 1.
