### ISSUE TITLE
Typo in the manual - Interfaces section, AbstractArrays

### ISSUE THREAD

**Issue by daanhb** [JuliaLang/julia#40805]
In the description of the interface of [AbstractArrays](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array), somewhere near the end of that section just before the interface of [StridedArrays](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-strided-arrays), there is an example about the indexing of an array wrapper. After that example it says:

"In this example it is accomplished by defining `Base.similar{T}(A::SparseArray, ::Type{T}, dims::Dims)` to create the wrapped array".

That `similar{T}` call seems like a relic from old times. It should just be `Base.similar(A::SparseArray, ::Type{T}, dims::Dims)` here?
Probably better even with S because that's how it is denoted in the table above: `Base.similar(A::SparseArray, ::Type{S}, dims::Dims)`.

**Comment by simeonschaub** [comment]
Yes, seems like this was just never updated. Want to make a PR?
