### ISSUE TITLE
[Feature Requests] Tab-autocompletion should be like zsh instead of bash on Julia prompt

### ISSUE THREAD

**Issue by xgupta** [JuliaLang/julia#40801]
When we <TAB> on Julia prompt, it would be nice if autocompletion happens like in zsh where we dynamically travel the available options. 
In the current situation, this tab completion is work like bash. for example:

`julia> HelloWorld.greet<TAB>`

will only show 

`greet`       `greet_alien`

What I want is if the user press <TAB> at the same position greet and greet_alien will automatically complete on the actual command prompt instead of writing another letter to complete it.

**Comment by xgupta** [comment]
In case Julia developers have a solution I will happy to work on it ...

**Comment by mgkuhn** [comment]
Bash has [readline-configuration commands](http://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html) such as
```
bind 'set show-all-if-ambiguous on'
bind 'TAB:menu-complete'
```
to change this behaviour. Does Julia have anything equivalent?

**Comment by xgupta** [comment]
I guess the answer is no. I think tab completion in REPL is implemented here stdlib/REPL/src/REPLCompletions.jl , don't how difficult this to support it?

CC expert @aviatesk

**Comment by xgupta** [comment]
closing, I don't like open issues on my GitHub dashboard :(

**Comment by KristofferC** [comment]
> closing, I don't like open issues on my GitHub dashboard :(

Please don't open issues if you are going to close them for arbitrary reasons like this. It is rude to the people that have added comments and spent time on the issue.
