### ISSUE TITLE
Should `get` work for tuples?

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#40809]
This seems surprising:
```julia
julia> get([1,2,3], 4, 5)
5

julia> get((1,2,3), 4, 5)
ERROR: MethodError: no method matching get(::Tuple{Int64, Int64, Int64}, ::Int64, ::Int64)

julia> get((a=1,b=2,c=3), :d, 5)
5

julia> get((a=1,b=2,c=3), 4, 5)
5
```

**Comment by xgupta** [comment]
Would like to take it if it is a good first issue.

**Comment by xgupta** [comment]
`get` function is define in `base/dict.jl` and testcase is in?

**Comment by simeonschaub** [comment]
Typically files in `base` have a corresponding file in `test` with the same name, so `test/dict.jl` seems reasonable.

**Comment by simeonschaub** [comment]
Typically files in `base` have a corresponding file in `test` with the same name, so `test/dict.jl` seems reasonable.

**Comment by mcabbott** [comment]
I think `dict.jl` has the implementation for dictionaries, but not for other types, so would guess `base/tuple.jl` for this? 
```
julia> @which get(Dict("a"=>1, "b"=>2), "a", 3)
get(h::Dict{K, V}, key, default) where {K, V} in Base at dict.jl:504

julia> @which get((a=1,b=2,c=3), :d, 5)
get(nt::NamedTuple, key::Union{Integer, Symbol}, default) in Base at namedtuple.jl:309

julia> @which get([1,2,3], 4, 5)
get(A::AbstractArray, i::Integer, default) in Base at abstractarray.jl:1469
```
The NamedTuple one is almost exactly what's needed. 
 
Note that there's another method `get(f, xs, i)`, which also seems to be missing for arrays:
```
julia> get(() -> println("runs"), (a=1,b=2,c=3), 3)
3

julia> get(() -> println("runs"), [1,2,3], 3)
ERROR: MethodError: no method matching get(::var"#17#18", ::Vector{Int64}, ::Int64)
```

**Comment by xgupta** [comment]
Thanks, I understand the issue, I will send a PR soon. 

Currently, I am reading the manual but now jump to [Dict@Collections and Data Structures documentation](https://docs.julialang.org/en/v1/base/collections/#Dictionaries) to understand get and dict.

**Comment by xgupta** [comment]
> I think `dict.jl` has the implementation for dictionaries, but not for other types, so would guess `base/tuple.jl` for this?

Ah, now I understand the meaning of this, previous comment is correct.
