### ISSUE TITLE
`sparse(::Adjoint{SparseMatrix{Tv,Ti}})` loses Integer type

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#40823]
```julia
julia> using SparseArrays

julia> x = sparse(Int32.(1:5), Int32.(1:5), trues(5))
5×5 SparseMatrixCSC{Bool, Int32} with 5 stored entries:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1

julia> sparse(x')
5×5 SparseMatrixCSC{Bool, Int64} with 5 stored entries:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1
```

I would have expected `typeof(sparse(x')) == typeof(x)`. Both `permutedims(x)` and `typeof(x)(x')` work as expected of course.

**Comment by dkarrasch** [comment]
Not sure what to do with general wrappers, but this could simply do (not sure the alias exists)
```julia
sparse(x::AdjOrTransSparseMatrix) = copy(x)
```
The general difficulty for multiply wrapped sparse arrays is to extract the `Ti` type. And in fact, custom sparse matrix types may not have that type in the first place.

**Comment by abraunst** [comment]
Seems reasonable! :+1:

**Comment by dkarrasch** [comment]
I have a different fix, will push in a minute.
