### ISSUE TITLE
Error with Float64 * StepRange{Int,Int} with negative step

### ISSUE THREAD

**Issue by jdeldre** [JuliaLang/julia#40846]
With the nightly build, I am getting an error when I multiply a StepRange with negative step and a float:

```
julia> ar = 10:-1:1
10:-1:1

julia> arf = 0.1*ar;

julia> arf[1]
1.0

julia> arf[2]
1.1
```

I would have gotten `arf[2] = 0.9` with previous versions. Note that this only seems to arise with floats multiplying StepRange{Int,Int}. I get expected behavior with, e.g., `0.1*(10.0:-1.0:1.0)` and `2*(10:-1:1)`.

Julia Version 1.7.0-DEV.1109
Commit 0bae193188 (2021-05-17 14:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)

**Comment by mcabbott** [comment]
That's a bug in #40320 , sorry! 

Fix should be simple I think, at https://github.com/JuliaLang/julia/pull/40320/files#diff-d86efa14f136d64b4e87e75251b7164c34a1deb688aa08cf3de54c4ef661bf39R1161-R1162:
```
julia> 0.1 .* (10:-1:1)
1.0:0.1:1.9

julia> @eval Base.Broadcast broadcasted(::DefaultArrayStyle{1}, ::typeof(*), x::AbstractFloat, r::OrdinalRange) =
            Base.range_start_step_length(x*first(r), x*step(r), length(r));

julia> 0.1 .* (10:-1:1)
1.0:-0.1:0.1
```
