### ISSUE TITLE
API suggestion for a findnz like function (sparse matrices)

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaLang/julia#40853]
Hi ! Concerning sparse matrices, may I suggest an alternative way of returning values for `findnz(S::SparseMatrixCSC)` ? Instead of returning a tuple of vectors, why not simply returning a vector of tuples ? I guess this is will be more friendly for math guys (I'm not one :)

```
julia> using SparseArrays, Printf

julia> S = sparse([1; 2], [1; 2], [42.0; 43.0])
2×2 SparseMatrixCSC{Float64, Int64} with 2 stored entries:
 42.0    ⋅ 
   ⋅   43.0

# Current Julia implementation
julia> sp = findnz(S)
([1, 2], [1, 2], [42.0, 43.0])

julia> typeof(sp)
Tuple{Vector{Int64}, Vector{Int64}, Vector{Float64}}

# Simulate the output of the suggested alternative to findnz().
julia> sp = [(1,1,42.0); (2,2,43.0)]
2-element Vector{Tuple{Int64, Int64, Float64}}:
 (1, 1, 42.0)
 (2, 2, 43.0)

# Example of iteration (simple loop instead of two)
julia> for i in 1:size(sp,1)
          I,J,D = sp[i]
          (@printf "S[%d,%d]=%f\n" I J D)
       end

S[1,1]=42.000000
S[2,2]=43.000000
```

The same idea could be applied to `sparse` function :

```
julia> newsparse([(1,1,42.0); (2,2,43.0)])
2×2 SparseMatrixCSC{Float64, Int64} with 2 stored entries:
 42.0    ⋅ 
   ⋅   43.0
```

while this could conflict with closed notation `sparse([1;2;3])`

**Comment by ViralBShah** [comment]
While I have not actually benchmarked it - I would expect expect a vector of tuples to be slower. It is also likely to be breaking for existing codebases. These are the sort of ideas that should be tried out in external sparse matrix packages that are not closely tied to the 1.0 API.

**Comment by Lecrapouille** [comment]
@ViralBShah sorry for my english I did not ask to change the output of this function but could be made by another function. For the benchmark, I guess a tuple is implemented as an anonymous struct. So here the eternal question from any langage: should we use array of struct or struct of array :)

**Comment by ViralBShah** [comment]
That is the eternal question!

**Comment by abraunst** [comment]
note that you can easily do `zip(findnz(S)...)` for what you want.

**Comment by ViralBShah** [comment]
Can get pretty expensive for large matrices I would think - but yes that's how I would start.

**Comment by abraunst** [comment]
You mean if you `collect` it? I tried to compare with a  lazy `findnz`:
```julia
lazy_findnz(x) = rowvals(x), Iterators.flatten(Iterators.repeated(i,length(nzrange(x,i))) for i=1:size(x,2)), nonzeros(x)
```
A lazy iterator returning triplets would be:
```julia
findnz3(x) = @inbounds ((rowvals(x)[k],c,nonzeros(x)[k]) for c=1:size(x,2) for k=nzrange(x,c))
```
Performance using `zip(lazy_findnz(x)...)` and  `findnz3` seems comparable... maybe `findnz` should be always lazy?

```
julia> x=sprand(10000,10000,0.001);

julia> @btime sum(i*j*v for (i,j,v) in zip(lazy_findnz($x)...))
  255.326 μs (0 allocations: 0 bytes)
1.2506760645386436e12

julia> @btime sum(i*j*v for (i,j,v) in findnz3($x))
  258.376 μs (0 allocations: 0 bytes)
1.2506760645386436e12

julia> @btime sum(i*j*v for (i,j,v) in zip(findnz($x)...))
  483.891 μs (6 allocations: 2.29 MiB)
1.2506760645386436e12

```
