### ISSUE TITLE
FeatureRequest:C-type macro

### ISSUE THREAD

**Issue by Rratic** [JuliaLang/julia#40857]
There's already`macro`,`@isdefined`and`isdefined` in julia.
But I think we need a different macro system.
For example,we sometimes see this C/C++ code
```cpp
#define __cplusplus 201402L
#define foo 5
#undef foo

#ifndef foo
;
#endif

#if __cplusplus < 201103L // This is the main feature I suggest
;
#endif
```
I know that using `if` is fast enough,but I think there are two adventages for using this:
1. static-compiling will not generate extra code
2. it _may_ be even faster

the code may look like this:
```
%define hundred 100
%if x > hundred
function bar()
end
%else
function bar()
end
%end
%undef hundred # `const` can't do this!
```

**Comment by vchuravy** [comment]
You can use `@static if` to statically evaluate the condition during parsing. Note that this is only needed inside functions.

**Comment by Rratic** [comment]
sorry,I haven't read thoroughly
