### ISSUE TITLE
`axes` not defined for `NamedTuple`

### ISSUE THREAD

**Issue by ianqsong** [JuliaLang/julia#40874]
`axes` is defined for `Tuple`, but not for `NamedTuple` yet.
```julia
julia> t
("cc", 1)

julia> axes(t)
(Base.OneTo(2),)

julia> nt
(a = "cc", b = 1)

julia> axes(nt)
ERROR: MethodError: no method matching size(::NamedTuple{(:a, :b), Tuple{String, Int64}})
```

**Comment by goretkin** [comment]
Do you have an example of code that is using `axes` and would be generic across e.g. `Array`, `Tuple`, and `NamedTuple` with a suitable definition of `axes`?

**Comment by goretkin** [comment]
I don't disagree, but who knows if there should be some range-like object that would represent the indices *and* names of the `NamedTuple`. It would be easier to figure out the requirements on a definition if there's an actual use case. For example, how did you notice that this was missing?

**Comment by goretkin** [comment]
>     2\. Although it's not hard for users to extend `Base`, it wouldn't hurt to add just one line in `Base`

It would be type piracy to extend `Base` like this, so if this definition is the right one, then it would be important to include it in `Base`. The harm is if it's not the right definition.

Also, 
```julia
julia> keys((1, 2))
Base.OneTo(2)

julia> keys((a=1, b=2))
(:a, :b)
```

**Comment by ianqsong** [comment]
Thanks for the hint. I would use `axes(keys(x))` instead of `axes(x)`. However, when it comes to `axes` of `(a=1, b=2)` my intuition is the `axes` of `(1,2)`, i.e., the `values((a=1, b=2))` not the keys. 
Aslo, after testing the following
```julia
julia> axes(keys(1))
(Base.OneTo(1),)

julia> axes(keys([1]))
(Base.OneTo(1),)

julia> axes(1) == axes(values(1))
true

julia> axes([1]) == axes(values([1]))
true
```
I will use `axes(values(x))` when possible ( and no complaint about completeness of `Base`).

**Comment by goretkin** [comment]
It sounds like `axes(values(x))` would do the trick in your case. It is still possible that there should be a definition of `axes(::NamedTuple)` (in `Base`). Possible definitions are

`axes(x::NamedTuple) = axes(values(x))`

or

`axes(x::NamedTuple) = keys(x)`

Making a choice would clarify the relation between `keys` and `axes`, especially for 1D collections.
