### ISSUE TITLE
Clearly show a warning when attempting to use BLAS.vendor()

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#40882]
With the move to using LBT, we should mark `BLAS.vendor()` as deprecated for 1.7. It is practically not used across the package ecosystem (discussed in https://github.com/JuliaLang/julia/pull/39455). And since it is a private API, we should then be able to remove it altogether in 1.8.

Otherwise, having it creates confusion: https://github.com/JuliaLang/julia/issues/33691#issuecomment-840473446, https://github.com/JuliaLinearAlgebra/MKL.jl/issues/76

**Comment by giordano** [comment]
It is already deprecated:
https://github.com/JuliaLang/julia/blob/c3a31804a88beb4b05c8fd4b0981e76d14058311/stdlib/LinearAlgebra/src/blas.jl#L94
The problem is probably that deprecation warnings are hidden by default?

**Comment by ViralBShah** [comment]
That is indeed the problem. Maybe we need to throw in a warning anyways to make sure that people see the warning? It's largely used interactively by users rather than in packages, based on a pkgeval run.

**Comment by simeonschaub** [comment]
I think we could just pass `force=true` to `Base.depwarn`, which should cause the warning to always show up.

**Comment by ViralBShah** [comment]
That would certainly solve the problem.
