### ISSUE TITLE
rdiv!(randn(4,4), I(4)) fails

### ISSUE THREAD

**Issue by olof3** [JuliaLang/julia#40887]
```julia
julia> rdiv!(randn(4,4), I(4))
ERROR: MethodError: no method matching rdiv!(::Matrix{Float64}, ::Diagonal{Bool, Vector{Bool}})
```

There is an `rdiv!` method but it requires the arguments to have the same `eltype`, i.e.,
`rdiv!(randn(4,4), 1.0I(4))` works

~~I also noticed that there are two `ldiv!` methods for `Diagonal` and `Matrix`. `ldiv!(D::Diagonal, B::StridedVecOrMat)` and 
`ldiv!(D::Diagonal{T}, V::AbstractMatrix{T})`. This seems redundant?~~

**Comment by dkarrasch** [comment]
> I also noticed that there are two `ldiv!` methods for `Diagonal` and `Matrix`.

This might have been resolved meanwhile (#38484 ?).

**Comment by olof3** [comment]
Great, yes the redundancy issue seems to have been resolved.

**Comment by Pramodh-G** [comment]
Can this issue be closed then?

**Comment by olof3** [comment]
> Can this issue be closed then?

No, the main issue has not been resolved.

**Comment by ArunSanganal** [comment]
> > Can this issue be closed then?
> 
> No, the main issue has not been resolved.

is this to be solved in diagonal.jl file?

**Comment by olof3** [comment]
> is this to be solved in diagonal.jl file?

I would say that's the place. I guess it should be made consistent with `ldiv!` https://github.com/mcognetta/julia/blob/2dbedeb047ae8b322fd97d3725d5170d497b1ff3/stdlib/LinearAlgebra/src/diagonal.jl#L590

Would probably also be a good idea to move the `ldiv!` and `rdiv!` methods to the same place in that file.
