### ISSUE TITLE
Doc: Pointer value of reassigned const

### ISSUE THREAD

**Issue by greschd** [JuliaLang/julia#40894]
Hi! :wave:

I believe the following is a minor error in the documentation. Since I'm fairly (actually, very!) new to Julia, this may of course be a misunderstanding on my side.

The [Constants section](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Constants) in the manual contains
```julia
julia> const s1 = "1"
"1"

julia> s2 = "1"
"1"

julia> pointer.([s1, s2], 1)
2-element Array{Ptr{UInt8},1}:
 Ptr{UInt8} @0x00000000132c9638
 Ptr{UInt8} @0x0000000013dd3d18

julia> s1 = s2
"1"

julia> pointer.([s1, s2], 1)
2-element Array{Ptr{UInt8},1}:
 Ptr{UInt8} @0x0000000013dd3d18
 Ptr{UInt8} @0x0000000013dd3d18
```

Notice that the pointer value for `s1` changes to the value of `s2`. 

Trying the same in a REPL (Julia version 1.6.1), I get:

```julia
julia> const s1 = "1"
"1"

julia> s2 = "1"
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x00007f5f2fb7c4f8
 Ptr{UInt8} @0x00007f5f2fb7e1f8

julia> s1 = s2
"1"

julia> pointer.([s1, s2], 1)
2-element Vector{Ptr{UInt8}}:
 Ptr{UInt8} @0x00007f5f2fb7c4f8
 Ptr{UInt8} @0x00007f5f2fb7e1f8
```
Here, the pointer value for `s1` has _not_ changed.

Trying the same thing with versions `1.4.1` and `1.5.4`, `1.4.1` is consistent with the docs, whereas `1.5.4` has the same behavior as `1.6.1`. It seems the behavior changed somewhere between `1.4.1` and `1.5.4`, and the docs didn't get updated.

Should the doc be updated to match the new behavior, or is this an implementation detail that may change with any release?

Similar issue: #38584 - difference being that it discusses reassigning with another `const`, not the kind where the value doesn't change.

Happy to make a (fairly trivial) PR that changes the docs if that's desired.

**Comment by melonedo** [comment]
I think the address is just implementation detail. The documentation states that even if the global variable may be reassigned (change the binding a.k.a. address), no warning is given if the new and old values are equal (in the sense of `==`). And the example verifies this statement. 
But the example no longer matches the real situation, I think we should find a new example where the address changes to replace it. If this is impossible.

**Comment by simeonschaub** [comment]
Yes, redefining constants is not defined behavior, it's only allowed for convenience. Also note that there is not really any point in looking at the pointers here, since bindings in Julia are only names, not references.
