### ISSUE TITLE
Raise RLIMIT_NOFILE at startup

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#40891]
> nodejs/node@6820054 is how Node.js raises the file descriptor limit. Afterwards, soft limit == hard limit; there's no way for libuv retrieve the old soft limit again. Defaulting to 256 or 1024, depending on the platform, is the only way.

> FWIW, Node.js has been doing that for 8 years and I don't recall a single bug report. I recently added similar logic to Deno (denoland/deno@d46b37f), again to no ill effect. I suspect the select() bug with fds > 1023 is pretty much theoretical nowadays.

Refs https://github.com/libuv/libuv/issues/3181

**Comment by ArunSanganal** [comment]
@vtjnash in which file should this be implemented?

**Comment by vtjnash** [comment]
Perhaps src/support/libsupportinit.c? I think we have some other similar code in `libsupport_init()` already

**Comment by PallHaraldsson** [comment]
Does the limit also needs to be raised on Windows (doesn't seem done in Julia nor node)? At least on Windows 7 (which Julia still supports) is seems to be a limit (for stream I/O) of 512 files handles (not general handle limit), and can be raised to 8192 as shown there with one line of code:

https://stackoverflow.com/questions/31108693/increasing-no-of-file-handles-in-windows-7-64-bit

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-140

i.e.
```
_setmaxstdio(8192)
```
