### ISSUE TITLE
Using multithreading to make compilation faster

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#40907]
I haven’t find anything about using multiple processors for compiling code faster during the first run. Is there a flag or option that I  an use? Is it even possible?

Maybe something like MAKEFLAGS=-j4 in C?
I have tried to use JULIA_NUM_THREADS but I believe it for code only not for compilation?

Thank you

**Comment by jpsamaroo** [comment]
There is not currently any multithreading used for compilation (as far as I know).

**Comment by gitboy16** [comment]
Any idea if it is something complicated to do? In case it  is something easy to do it could be an easy win for the community. I would be happy to spend so time trying to implement that if it is possible.I am trying to get people to use Julia but the fact that we always have to recompile our code everytime we  want to do a bit of data analysis or scripting is a no go for people around me. I really would like to help improve Julia because I believe it has so much potential...If someone would be able to guide or show me where I can start it would be great.

**Comment by xgupta** [comment]
Julian, you have a nice name :)

**Comment by jpsamaroo** [comment]
This is potentially a rather complicated feature to add, even for a seasoned Julia compiler developer. You would probably have to start with replacing the internal codegen/typeinf locking with a lock-free approach, which would imply possibly restructuring internal data structures. Then you'd need to determine where and when multithreading can be applied - maybe you could parallelize compiling independent, pure expressions at the toplevel after running typeinf on each expression independently? I'm not really sure of the best way to do this, but suffice to say, it will be quite the challenge!

**Comment by martincornejo** [comment]
> ... but the fact that we always have to recompile our code everytime we  want to do a bit of data analysis or scripting is a no go for people around me.

For now maybe the best solution might be changing your workflow. Instead of each time running code in the form of scripts `julia file.jl`, which is usual for example in python but can be expensive for julia, a better option might be to continuosly work on the same interactive julia session. 

Here is a section of the documentation that explains how this can be done easier with the `Revise` package.

https://docs.julialang.org/en/v1/manual/workflow-tips/#Revise-based-workflows

**Comment by ViralBShah** [comment]
We have multi-threaded precompilation, and more multi-threading within the compiler is always an ongoing process. Closing since this is better suited for discourse.

**Comment by gitboy16** [comment]
Is multi-threaded precompilation done by default or is there a way to turn it on? Thank you

**Comment by johnnychen94** [comment]
It's available since Julia 1.6, turned on by default: https://julialang.org/blog/2021/03/julia-1.6-highlights/#parallel_precompilation
