### ISSUE TITLE
Feature request: methods for maximum, minimum, findmin, and findmax to return n elements

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaLang/julia#40905]
It looks like these functions can only return the single largest or smallest element in a collection. I'd like the option to return the n largest or n smallest. Searching the web, it looks like either a [Priority Queue](https://en.wikipedia.org/wiki/Priority_queue) or [Selection Algorithm](https://en.wikipedia.org/wiki/Selection_algorithm) should be used to find the results quickly rather than sorting the entire collection first. I would be willing to try implementing this, but I would need some time and help. Let me know if this is something I should work on, or if there already exists a fast method for doing this.

**Comment by ParadaCarleton** [comment]
Try [DataStructures.jl](https://github.com/JuliaCollections/DataStructures.jl) for priority queues.

**Comment by nathanrboyer** [comment]
Thanks! `partialsort` and `partialsortperm` are exactly what I was looking for. I will close this issue.
