### ISSUE TITLE
Feature request: Lazy @something macro

### ISSUE THREAD

**Issue by jeffreyesun** [JuliaLang/julia#40933]
For performance reasons, we usually do not need to evaluate the second argument of the `something` function. For example, in this pattern I sometimes use for propagating default arguments:
```
function foo(; bar=nothing)
   bar = something(bar, defaultbar())
   ...
end
```
I propose a lazy version of this, `@something`:
```
macro something(valornothing, ex)
    return valornothing == :nothing ? ex : valornothing
end
```
to be used as follows:
```
function foo(; bar=nothing)
   bar = @something(bar, defaultbar())
   ...
end
```
so that `defaultbar()` need not be called when it is not needed.

**Comment by DilumAluthge** [comment]
Don't we already have this on `master`?

https://docs.julialang.org/en/v1.7-dev/base/base/#Base.@something

Or are you requesting something different from the `Base.@something` macro on `master`?

**Comment by jeffreyesun** [comment]
My bad, this is indeed already going to be in 1.7. Sorry for wasting your time.
