### ISSUE TITLE
add Matlab-like meshgrid function

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#4093]
I've always found Matlib's [meshgrid](http://www.mathworks.com/help/matlab/ref/meshgrid.html) function to be very useful for plotting and for working with data on Cartesian grids.

Would be nice to have this in Julia, and is trivial to implement.  It could even return an `AbstractArray` type that avoided allocating the full matrices of (redundant) numbers, although to be honest it's probably not worth it (if you look at cases where `meshgrid` is used, in my experience the memory usage is rarely an issue — you always do some computations with the meshgrid that requires comparable storage, so a compressed format for the meshgrid will at best save you a small constant factor in memory usage).

**Comment by ihnorton** [comment]
(please re-open and tag decision or up-for-grabs if this needs further discussion...)

**Comment by pluskid** [comment]
Sometimes I still need to generate grid points explicitly, because I need to manipulate those points via some procedures that does not support this kind of broadcasting. It would be great if a convenient meshgrid like function is available.

**Comment by ViralBShah** [comment]
Won't a comprehension do it? Slightly longer at best. Maybe you could have it as a convenience function in your own code?

**Comment by pluskid** [comment]
@ViralBShah Can you show me how to do it with comprehension? I'm currently doing it with a simple and dumb way like this:
```julia
  a = linspace(0, pi, n)
  b = linspace(0, 2pi, 2n)
  grid_a = vec(broadcast((x,y) -> x, a, b'))
  grid_b = vec(broadcast((x,y) -> y, a, b'))
```

**Comment by IainNZ** [comment]
```
grid_a = [i for i in a, j in b]
grid_b = [j for i in a, j in b]
```

**Comment by pluskid** [comment]
@IainNZ Thanks!

**Comment by lkuper** [comment]
Any chance of releasing the `examples/ndgrid.jl` implementation of `ndgrid` as part of a library?  (I'm asking because we have a ParallelAccelerator example that relies on it, and to release that example it seems like we'd need to copy that file into our own project and make a note in our license file that we are redistributing a file that's part of Julia.)

**Comment by stevengj** [comment]
Wouldn't it be better to rewrite your ParallelAccelerator example to use broadcasting?

**Comment by lkuper** [comment]
@stevengj It might be!  We're benchmarking it against a Matlab version that calls Matlab's `meshgrid` (I meant to say `meshgrid` above, not `ndgrid`), and I'm trying to strike a balance between doing what is idiomatic for Julia and doing something that would be familiar to a Matlab programmer.

**Comment by SimonEnsemble** [comment]
Yes, not having a meshgrid function has caused difficulty multiple times for me (a user) when trying to make visualizations.

**Comment by pengwyn** [comment]
I also have come across a different use case. There appears to be no broadcast equivalent to `pmap`, so it is necessary to grid my vectors across into same-sized n-dimensional arrays. It would be much nicer to instead write `pmap(func, x', y)`.

Alternatively, a different function could solve my problem. Maybe #10438 is relevant here?

**Comment by johnnychen94** [comment]
We could implement a [`np.ix_`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ix_.html) thing

```julia
# a simple implementation
function xvec(vs::AbstractVector...)
    n = length(vs)
    map(enumerate(vs)) do (i, v)
        p = collect(1:n)
        p[1], p[i] = i, 1
        permutedims(reshape(v, :, ones(Int, n-1)...), p)
    end
end
```

this is useful to take advantages of broadcasting in the sense that you don't need to generate a dense `meshgrid` array

```julia
julia> X = collect(1:1:10);

julia> Y = collect(-5:1:5);

julia> g(x::Number, y::Number) = x+y
g (generic function with 1 method)

julia> g.(xvec(X, Y)...)
10×11 Array{Int64,2}:
 -4  -3  -2  -1  0   1   2   3   4   5   6
 -3  -2  -1   0  1   2   3   4   5   6   7
 -2  -1   0   1  2   3   4   5   6   7   8
 -1   0   1   2  3   4   5   6   7   8   9
  0   1   2   3  4   5   6   7   8   9  10
  1   2   3   4  5   6   7   8   9  10  11
  2   3   4   5  6   7   8   9  10  11  12
  3   4   5   6  7   8   9  10  11  12  13
  4   5   6   7  8   9  10  11  12  13  14
  5   6   7   8  9  10  11  12  13  14  15
```

P.S. `Iterators.product` almost does this except that I need to define a tuple version of `g`:

```julia
g(args::Tuple) = g(args...)
g.(Iterators.product(X, Y))
```

**Comment by johnnychen94** [comment]
Sorry for the noise, actually the comprehension list is a faster version:

```julia
julia> g.(xvec(X, Y)...) == [g(x,y) for x in X, y in Y]
true

julia> @btime g.(xvec($X, $X)...);
  549.074 μs (19 allocations: 7.65 MiB)

julia> @btime [g(x,y) for x in X, y in Y];
  8.609 μs (5 allocations: 86.20 KiB)
```
