### ISSUE TITLE
Merge libjulia-debug into libjulia?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#40946]
In julia-release I think we could unconditionally enable the assert macro (never set NDEBUG), but then always wrap it in a runtime check as: `char GLOBAL_DEBUG_ENABLED; #define jlassert(x) if (GLOBAL_DEBUG_ENABLED) assert(x)`. This should cost almost nothing in performance (since it should be well-predicted and hot), but allow us to ship both `./julia` and `./julia-debug` binaries without any size penalty for having both (which previously only really differed in the name of the libjulia-internal library that they are linking to).

**Comment by JeffBezanson** [comment]
Don't they also differ in optimization level?

**Comment by vtjnash** [comment]
True. On linux that doesn't matter because we have better information from `rr` than from julia-debug. But perhaps we want to keep both, and just enable the option of assertions in the release build?

**Comment by ViralBShah** [comment]
Close?
