### ISSUE TITLE
Decoupling docstrings from their function

### ISSUE THREAD

**Issue by Lecrapouille** [JuliaLang/julia#40945]
Julia lang is great because it allows to write very compact code but as far as I understand and tested it's not possible to write the docstring of functions separated from them. This makes the code source bigger and less easy to read or find function (... I mean visually ... with human eyes) because you have two languages mixed in a single file (markdown and Julia). 

Making the separation comment/code possible will allow making the code be more compact while still allowing literate programming (Literate.jl) and doc generation (Documenter.jl) still possible. I always liked the idea of literate programming http://www.literateprogramming.com/cweb_download.html where you're coding in the same way you'll write a book instead of writing function in the order imposed by the compiler. I come from C/C++ world and Donald Knuth idea is interesting but mixing two languages (his macro code and C code) in a single file makes the reading not possible (for me). For example, https://github.com/fredrikekre/Literate.jl/blob/master/examples/example.jl find where is hiding the Julia code :)

Here what I suggest :

Instead of  `f1.jl`:
```
"""
   foo()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""
foo() = ....

"""
   bar()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""
bar() = ....
```

Simply write `f1.jl` as:
```
include doc.jl

foo() = ....
bar() = ....
```

We now ~2 lines versus ~20 lines. And in separated `doc.jl` file:
```
"""
   foo()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""

"""
   bar()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""
```

We can mimic the C world where header files (.h) have their documentation for exported functions. So why not combined docstring with the `export` keyword:

f1.jl
```
module FooBar
include export.jl

  foo() = ....
  bar() = ....
end
```

export.jl:
```
"""
   foo()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""
export foo

"""
   bar()
Long algorithm description,
Long arguments description
Many examples
make the code not visible
"""
export bar
```

This first step is done, we can reuse the idea Documenter.jl allowing us to read markdown files and searching the comment of a function `@docs foo()` we can add another macro `@code foo()` to past the code content to make literate programming:

literate.md:

    Bla Bla without md" comment"
    ```
    @code foo
    ```

In addition, in my personal project currently I modifying the show() function and therefore I have to rework all my examples, this is boring so why not using meta-programming idea `@repl bar()` to execute `bar and help generating examples ? :

```
"""
   bar()
Long algorithm description,
Long arguments description
# Examples
  @repl bar()
"""
export bar
```

```
julia> ?bar

   bar()
Long algorithm description,
Long arguments description
Eamples
  julia> bar()
    the answer
```

**Comment by MichaelHatherly** [comment]
See https://docs.julialang.org/en/v1/manual/documentation/#Functions-and-Methods-2 for the syntax for this.

**Comment by mbauman** [comment]
Further discussion here is probably best suited for the [discourse message board](https://discourse.julialang.org).

**Comment by Lecrapouille** [comment]
@MichaelHatherly @mbauman Both of you did not get my point. I was not talking about if """ should be glue to function or f for cosmetic reason but a request to allow separating comments apart from the code (ie in a separate file) to make it more compact to read.

**Comment by mbauman** [comment]
You can already do that as described in section that Michael linked above.  In those example syntaxes the method(s) for `f` were already defined elsewhere, potentially in a different file.  We do this [in Julia itself](https://github.com/JuliaLang/julia/blob/829d7e090f2cadfe1b1d506394f416b2938b3e7e/base/docs/basedocs.jl#L1895-L1914).

**Comment by Lecrapouille** [comment]
Thanks I did not get the point :)
