### ISSUE TITLE
No method for `schur(A', B)`

### ISSUE THREAD

**Issue by olof3** [JuliaLang/julia#40941]
This one seems to have been forgotten in #28714.

```julia
julia> schur(randn(3,3)', randn(3,3))
ERROR: MethodError: no method matching schur(::Adjoint{Float64, Matrix{Float64}}, ::Matrix{Float64})
```

I guess one should just add a method similarly to
```julia
function eigen(A::AbstractMatrix{TA}, B::AbstractMatrix{TB}; kws...) where {TA,TB}
    S = promote_type(eigtype(TA),TB)
    eigen!(copy_oftype(A, S), copy_oftype(B, S); kws...)
end
```

Not sure why it's `promote_type(eigtype(TA),TB)` and why the eigtype of `TB` that isn't used?

**Comment by andreasnoack** [comment]
I don't think the `!` version should have such a method. If you call then `!` version then you should pass appropriate inputs.

**Comment by olof3** [comment]
> I don't think the ! version should have such a method.

Sorry, must have copied the wrong thing. The problem is for the non `!` method, as indicated in the title. Which I guess should work? I have updated the original post now.

**Comment by olof3** [comment]
I had a closer look to see what needed to be done, but found some more issues

I guess that the fallback that one wants for `schur(A,B)` should be similar to
 ```julia
schur(A::AbstractMatrix{T}) where {T} = schur!(copyto!(Matrix{eigtype(T)}(undef, size(A)...), A))
```
rather than as for `eigen(A, B)` as I posted above, where `copy_oftype` is used, since

```julia
julia> eigen(I(5), I(5))
ERROR: MethodError: no method matching eigen!(::Diagonal{Float64, Vector{Float64}}, ::Diagonal{Float64, Vector{Float64}})
```

I guess that also this method for `eigen` should be modified?

Is `copyto!(Matrix{eigtype(T)}(undef, size(A)...), A)` the right approach? And in that case, could it be written in a less verbose way?

Should it be `T = promote_type(eigtype(TA),TB)` or `T = promote_type(eigtype(TA),eigtype(TB))`? The latter seems like what one would want, although I'm not sure that there is an example where they would be different?
