### ISSUE TITLE
Better error message for `convert(Type{Union{}}, ...)`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#40951]
I received this error message:
```
  MethodError: convert(::Type{Union{}}, ::Vector{Float32}) is ambiguous. Candidates:
    convert(::Type{T}, a::AbstractArray) where T<:Array in Base at array.jl:532
    convert(T::Type{var"#s79"} where var"#s79"<:BitArray, a::AbstractArray) in Base at bitarray.jl:577
    convert(T::Type{var"#s832"} where var"#s832"<:SparseArrays.SparseVector, m::AbstractVector{T} where T) in SparseArrays at /Users/eschnett/julia-1.6/share/julia/stdlib/v1.6/SparseArrays/src/sparsevector.jl:453
    convert(T::Type{var"#s832"} where var"#s832"<:SharedArrays.SharedArray, a::Array) in SharedArrays at /Users/eschnett/julia-1.6/share/julia/stdlib/v1.6/SharedArrays/src/SharedArrays.jl:377
    convert(::Type{Union{}}, x) in Base at essentials.jl:203
    convert(::Type{T}, arg) where T<:VecElement in Base at baseext.jl:8
  Possible fix, define
    convert(::Type{Union{}}, ::Vector{T} where T)
```

This is a confusing error message. Would it be possible to catch this as a special case in the definition of `convert`, and emit an error such as "Converting to `Union{}`" does not make sense; check your call site"?

**Comment by JeffBezanson** [comment]
Yes, we already have a function `show_convert_error` to give better printing of method errors involving `convert`. This case can be added there.

**Comment by jakobnissen** [comment]
Ref https://github.com/JuliaLang/julia/issues/36706

**Comment by kahanikaar** [comment]
I would like to contribute to this issue, will be grateful for guidance to approach this. @JeffBezanson @eschnett @jakobnissen

**Comment by ArunSanganal** [comment]
@kahanikaar are you working on this issue?

**Comment by Pramodh-G** [comment]
Hi @eschnett, thanks for filing the issue. Could you please help  me by providing a MWE to reproduce it? It would help me understand what's going on behind the scenes here.

**Comment by eschnett** [comment]
Try this:
```Julia
convert(Union{}, Float32[])
```

**Comment by ArunSanganal** [comment]
Not quite sure but does fixing this issue start with modifying this?https://github.com/JuliaLang/julia/blob/87e08d94a99ea17e7f72493947595eb6b63e0f09/base/essentials.jl#L216
I am kinda new to error handling so any help would be appreciated. Logic says whenever this is encountered, we need to redirect it to `show_convert_error` function as @JeffBezanson mentioned.
