### ISSUE TITLE
Hint or helper at REPL for using/importing non-package modules

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#40959]
```
module Foo
    a = 5
    export a
end
using Foo
#=
ERROR: ArgumentError: Package Foo not found in current path:
- Run `import Pkg; Pkg.add("Foo")` to install the Foo package.
=#
```

I think the reasonable approach, as discussed with @StefanKarpinski and @DilumAluthge, would be:
 - If package not present and not in registry but a module is defined in Main, hint that the user needs to have the dot in front: `using .Foo`
 - If package is in registry and a module is defined in Main, offer to install package. Possibly also note that a module with the same name is defined in Main, and provide hint. Or install package and then provide hint after.
 - If package is already added and a module is defined in Main, import the package and provide hint.
 
This could potentially be done extending the hooks created for #39026

**Comment by DilumAluthge** [comment]
@IanButterworth as the author of #39026, any thoughts?

**Comment by KristofferC** [comment]
> If package not present and not in registry but a module is defined in Main, hint that the user needs to have the dot in front: using .Foo

This seems fine except it shouldn't be in Main but in the module the `require` call happens.

> If package is already added and a module is defined in Main, import the package and provide hint.

I don't think this should happen. `using Foo` has a specific meaning and that is to load a package from the project. Imo the hint is enough.
