### ISSUE TITLE
Deadlock in Profile on MacOS with multithreaded program

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#40972]
The following simple multithreaded program ~deadlocks~ hangs (I don't actually know why it's hanging):

```julia
julia> Threads.nthreads()
4

julia> using Profile

julia> const b = Threads.Atomic{Bool}(true)
Base.Threads.Atomic{Bool}(true)

julia> const out = rand(2,2)
2×2 Matrix{Float64}:
 0.0811545  0.0654667
 0.850495   0.684218

julia> @profile peakflops()
1.501919194588322e11

julia> t = Threads.@spawn while b[] out[1] = out[1] + 1 end
Task (runnable) @0x0000000112478340

julia> t
Task (runnable) @0x0000000112478340

julia> Profile.clear() ; Profile.init(n=Int(5e7), delay=0.0001) ; @profile peakflops()
^C^C^C^C
```

Same with this even simpler final line:
```julia
julia> Profile.clear() ; Profile.init(n=Int(5e7), delay=0.0001) ; @profile sleep(1)
```

BUT, interestingly, this _doesn't_ get stuck if you change the final line to actually _stop_ the infinite loop thread before finishing the profiling:
```julia
julia> Profile.clear() ; Profile.init(n=Int(5e7), delay=0.0001) ; @profile (sleep(1) ; b[] = false)
```

So my _guess_ is it has something to do with resuming the program after finishing profiling while there is a thread sitting in a loop?

---------

Also, i thought maybe this was because after the profiling, the GC tried to pause-the-world for GC, but because the thread has no yield-points, everything is stuck waiting for that thread to yield? But I tried adding a yield-point to the while loop, and it still hangs:

```julia
julia> using Profile

julia> const b = Threads.Atomic{Bool}(true)
Base.Threads.Atomic{Bool}(true)

julia> const out = rand(2,2)
2×2 Matrix{Float64}:
 0.342338  0.339537
 0.854418  0.0590949

julia> @profile peakflops()
1.2399335606400201e11

julia> t = Threads.@spawn while b[] out[1] = out[1] + 1 ; yield() end
Task (runnable) @0x0000000114378340

julia> t
Task (runnable) @0x0000000114378340

julia> Profile.clear() ; Profile.init(n=Int(5e7), delay=0.0001) ; @profile peakflops()
^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C
```

-------

I see this currently on julia 1.6.1 and on julia master. Here's my versioninfo for 1.6:
```julia
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by JeffBezanson** [comment]
> Also, i thought maybe this was because after the profiling, the GC tried to pause-the-world for GC, but because the thread has no yield-points, everything is stuck waiting for that thread to yield?

I think this is exactly what's happening; adding `yield()` or `GC.safepoint()` fixes the hang for me on linux.

**Comment by NHDaly** [comment]
Weird, where did you add the `yield()`? I saw (in my last example) that it still hung with a yield.

**Comment by NHDaly** [comment]
Here it is one more time, but I've formatted the while-loop line a bit better so the yield is clearer:
```julia
julia> Threads.nthreads()
4

julia> using Profile

julia> const b = Threads.Atomic{Bool}(true)
Base.Threads.Atomic{Bool}(true)

julia> const out = rand(2,2)
2×2 Matrix{Float64}:
 0.667892  0.0973639
 0.899577  0.441376

julia> @profile peakflops()
1.3850780366383786e11

julia> t = Threads.@spawn while b[]
            out[1] = out[1] + 1
            yield()
       end
Task (runnable) @0x000000011790c340

julia> t
Task (runnable) @0x000000011790c340

julia> Profile.clear() ; Profile.init(n=Int(5e7), delay=0.0001) ; @profile peakflops()
^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CWARNING: Force throwing a SIGINT
^C^C^C^C^C^C
```

Does this not hang for you on linux?

**Comment by NHDaly** [comment]
Ah yeah, you're right: Using `GC.safepoint()` does indeed fix the hang, and also disabling GC externally does as well. 👍 👍 

But oh - it turns out that `yield()` doesn't itself contain a `GC.safepoint()`... 🤦 That really surprised me! Shouldn't `yield()` also be a GC yield? The GC yield should be really cheap, and the concurrency `yield()` is relatively more expensive, so we'd probably want to also GC yield in there? Or am I wrong about that?

**Comment by vilterp** [comment]
Even simpler example, which shows that this has nothing to do with profiling, just GC:

```julia
julia> Threads.nthreads()
4

julia> const b = Threads.Atomic{Bool}(true)
Base.Threads.Atomic{Bool}(true)

julia> const out = rand(2,2)
2×2 Matrix{Float64}:
 0.667892  0.0973639
 0.899577  0.441376
 
julia> GC.gc()

julia> t = Threads.@spawn while b[]
            out[1] = out[1] + 1
            yield()
       end
Task (runnable) @0x000000011790c340

julia> t
Task (runnable) @0x000000011790c340

julia> GC.gc()  # Hangs here
^C^C^C^C
```
