### ISSUE TITLE
should error hints only be shown in the REPL?

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#40986]
ref https://github.com/JuliaLang/julia/pull/40545#discussion_r617840453. We should come to a decision and make this behavior consistent before we release 1.7. cc @vtjnash

**Comment by stevengj** [comment]
There should also be a way to get them in other interactive environments, e.g. IJulia.

**Comment by simeonschaub** [comment]
That's a good point! I guess we could also add them to InteractiveUtils though.

**Comment by stevengj** [comment]
Note that IJulia etc. can (and does) import the REPL module, so they can still live there.  I'm less concerned with where the functions live than in ensuring that the API is designed to be callable outside of a REPL environment.

**Comment by vtjnash** [comment]
The design here is that they are intended to be extensible, so REPL seems like a good place for this one (triage said this on Thursday), though others can live in their applicable modules.
