### ISSUE TITLE
RFC: custom type lattice and more generic abstract interpreter

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#40992]
Hi, I'm just starting this issue to keep track of some useful discussion happened in various places about custom type lattice and more generic abstract interpreter.
recently a few people including find that we might need custom type lattice (or insert custom type lattice into existing Julia ones) to enhance inference. So I think it
would be better to collect these scatter thoughts together here.

(please feel free to update the following)

# use cases
## quantum compilation (YaoCompiler.jl)

The recent progress of quantum hardware raise the need of high level eDSL that help people program this type of hardware, and compiler optimization
on such programs also opens a few new questions on the implementation. We recently find that by inferring if a number is multiple of pi, or pi/2 etc. Temporary
workaround can be defining a custom type for pi and overload everything, but this sounds like a huge engineering work.

we will be able to optimize hybrid (quantum + normal) programs better, and by inferring the measurement result type we can check if some of the non-cloning
errors by using abstract interpreter. However, this seems to require custom lattice type. For reference of how would the type lattices look like in other implementations,
one could refer to the Silq paper: https://files.sri.inf.ethz.ch/website/papers/pldi20-silq.pdf

On the other hand, there is a new paper about quantum abstract
interpretation (which is the distinguished paper in PLDI 2021): http://web.cs.ucla.edu/~palsberg/paper/pldi21-quantum.pdf
It might be a use case for generalizing the Julia abstract interpreter API (or at least make it possible to work with an indepdent eDSL abstract interpreter?)

## Static Linter (JET.jl)

I posted an idea about checking numerical error a while ago here (https://github.com/aviatesk/JET.jl/issues/141) and @aviatesk mentioned to support this
type of error we will also need custom lattice type to enhance the checking. Some of the detailed use cases and required elements have been disscussed in that issue.

On the other hand, previously there is https://github.com/FluxML/Mjolnir.jl that kinda implements some customized inference, I think some of them is still hard to implement with the current
abstract interpreter API.

I think @femtomc has some more use cases, but I'm not sure, please feel free to add.

cc: @femtomc @Keno @aviatesk @Keno

**Comment by AriMKatz** [comment]
Another use case is verifying array shapes for numerical/ML programming, and offloading to restricted accelerators like TPUs. 

Prior art: https://arxiv.org/abs/2102.13254

**Comment by alok** [comment]
i'd also like this: i can see a future where symbolics.jl and julia's compiler slowly converge to allow for really impressive symbolic programming basically built in to the language.

also being able to write a bunch of pluggable type checkers would be the next level of linting. being able to add herbie would be killer

**Comment by Keno** [comment]
I played with this a bit. Core.Compiler changes are on the kf/customlattice branch and the user code is in
https://github.com/JuliaLang/julia/commit/3bc77e1f86a13a35c841a2655cd52aa0edd878b5. It creates a lattice element that represents symbolic array shapes as Symbolics.jl values and infers the transfer functions. Of course for the ML use case, you probably care more about the weakest precondition case that assures nothrow, which isn't really something we infer at the moment, but I thought it'd be an interesting example.

**Comment by aviatesk** [comment]
We started to support lattice extension based on #46526. There will be more works to support a full extension (I proposed some directions [here](https://github.com/JuliaLang/julia/pull/46526#issuecomment-1234399390)) though.
