### ISSUE TITLE
Remove the type constraint on `sincosd`?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#41017]
There is a `sincos` for `Any`, but no one for `sincosd`. And it's causing some problems for me. See https://github.com/PainterQubits/Unitful.jl/issues/450

**Comment by KristofferC** [comment]
Makes sense to me that these should be equivalent in what types they accept. Perhaps you could make a PR for it?

**Comment by singularitti** [comment]
Sure.
