### ISSUE TITLE
Leading colon in indexing expressions (`v[:3]`)  is allowed and gives unexpected (?) result

### ISSUE THREAD

**Issue by olof3** [JuliaLang/julia#41025]
```julia
v = [1,2,3,4,5]
v[:3] # returns 3
```

Made a typo and it worked. I think that I would have preferred an error. Is the behavior intentional?

I guess the result is a bit surprising compared to Python for example.

The leading colon is similarly ignored for non-unit ranges, i.e., `:2:4` <-> `2:4`

**Comment by KristofferC** [comment]
`:3` is equivalent to writing `3` (this is called "quoting", see https://docs.julialang.org/en/v1/manual/metaprogramming/#Quoting):

```
julia> dump(:3)
Int64 3

julia> dump(3)
Int64 3
```

So you are simply evaluating `v[3]`.
