### ISSUE TITLE
Unicode String Indexing Bug

### ISSUE THREAD

**Issue by chelseas** [JuliaLang/julia#41033]
A string index error appears when a string ends in unicode then space but not with a roman character then space:

```
julia> "asd ξ "[1:end-1]
ERROR: StringIndexError("asd ξ ", 6)
Stacktrace:
 [1] string_index_err(::String, ::Int64) at ./strings/string.jl:12
 [2] getindex(::String, ::UnitRange{Int64}) at ./strings/string.jl:250
 [3] top-level scope at REPL[1]:1

julia> "asd e "[1:end-1]
"asd e"
```

Other info:
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/40974#issuecomment-849865549

**Comment by KristofferC** [comment]
As a note, the error has improved in Julia 1.6:

```
julia> "asd ξ "[1:end-1]
ERROR: StringIndexError: invalid index [6], valid nearby indices [5]=>'ξ', [7]=>' '
```
