### ISSUE TITLE
Computation Error Report(0.3-0.1)

### ISSUE THREAD

**Issue by ZhangNanXi** [JuliaLang/julia#41038]
I want to dynamically generate a series of ranges with the same interval using the following code:
`delta = 0.1`
 `action = 0.3`
`end_point = action - delta`
` series = collect(Float64, 0:delta:largest_state)`
I expect it give me the array [0,0.1,0.2] when `action` is given the value 0.3. However, the output is [0,0.1]. After checking, I found when I use Julia to calculate 0.3-0.1, the answer is 0.19999999999999998. That's why 0.2 is not included in the output. I think the reason might be 0.3 cannot be represented precisely in a binary system. To be honest, I found Python gives exactly the same answer as Julia, while C++ can output 0.2. 
In my case, I can skip the problem by adding some small numbers to the `end_point`.  But if I did not notice the issue, it will actually cause element loss in my code.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
