### ISSUE TITLE
`Base.has_fast_linear_indexing` needs a method for `Ref`

### ISSUE THREAD

**Issue by chengchingwen** [JuliaLang/julia#41055]
`has_fast_linear_indexing`for `Broadcasted` check all the arguments, 

https://github.com/JuliaLang/julia/blob/58ffe7e3ed3a93a9d816097548e785284f57fbd4/base/reducedim.jl#L194-L198

but broadcasting `literal_pow` has `Base.RefValue{typeof(^)}(^)` and `Base.RefValue{Val{2}}(Val{2}())` in its argument, which cause `MethodError`

MWE:
```jl
using LazyArrays
bc = @~ x .^ 2 # use LazyArrays to get the Broadcasted object
sum(bc, dims=1) # MethodError for has_fast_linear_indexing(::Base.RefValue{typeof(^)})
```

versioninfo:
```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by stevengj** [comment]
Sounds like it need a method for `RefValue()`?

(Note that if I change it to `bc = @~ x .+ 2` then `sum(bc, dims=1)` gives me a different `MethodError`, this time for `reducedim_init`.)

**Comment by stevengj** [comment]
(It doesn't seem related to `literal_pow` specifically, so I changed the issue title.)
