### ISSUE TITLE
[PR Proposal] Adding Functionality for `isweekday` or `isweekend` to Dates.

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaLang/julia#41058]
In the `Dates` package, there exist methods for `ismonday`, `istuesday`, etc. May I open a PR to add functionality to `Dates` to check for whether or not a given date falls on a weekday or weekend? There may be some localization differences I could account for (i.e. does a weekday start Sunday or Monday for people) but I thought this might be a reasonable PR to add as this is a functionality I could use.

Thoughts? Thank you!

**Comment by lobingera** [comment]
Is Dates.dayofweek not enough?

**Comment by TheCedarPrince** [comment]
In this case @lobingera , I am actually looking to have something that returns a Boolean of true or false in a terse function call like this:

```julia
isweekday(date::Date) = in(Dates.dayabbr(date), ["Mon", "Tues", "Wed", "Thurs", "Fri"])

isweekend(date::Date) = in(Dates.dayabbr(date), ["Sat", "Sun"])
```

I am sure this can be optimized some, but if the others are in the base Dates package, I don't see why this would be rejected as a feature off the top of my head.

**Comment by sostock** [comment]
One possible problem might be that it is not clearly defined whether saturday is part of the weekend or not. For example, Merriam-Webster defines “weekday” as
> any day of the week except Sunday or now usually except Saturday and Sunday

However, I think it is fine to define saturday as part of the weekend, since otherwise you could just use `issunday`.

**Comment by thofma** [comment]
Doesn't this depend on the culture? In a large part of the world weekend is Friday and Saturday.

**Comment by lobingera** [comment]
that's what i mean above:  Dates.dayofweek returns a day number and you can check with your local preference about the weekend. Including the predicate into Dates would mean at least an additional configuration step.
