### ISSUE TITLE
Copying code using tabs to indent causes REPL to dump all Base exports

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#41052]
This is relevant to Pluto.jl, which uses tabs to indent.

If you copy over multiple lines of code into the REPL from a Pluto notebook, it dumps the list of Base exports.

I suggest that tabs at the beginning of input should be ignored.

Example (copy whitespace):
```
		range1 = 1:5
```

Related to #37815

**Comment by KristofferC** [comment]
Windows I guess?

**Comment by BioTurboNick** [comment]
Yes, it seems to only affect the Windows Terminal and console, not when running in WSL.

**Comment by BioTurboNick** [comment]
Actually pressing tab twice in WSL does trigger it, but pasting doesn't.

**Comment by manuelbb-upb** [comment]
I experience the same issue in VSCode under Linux (KDE Neon/Ubuntu) with the “Send Current Line or Selection to REPL” command.

**Comment by vtjnash** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/53763
