### ISSUE TITLE
Coverage stats are broken (but coverage is fine)

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#41098]
The recent addition of 12k autogenerated and untested lines of code to SuiteSparse are the reason coverage stats are down 10% recently. We need to hide it from reporting, so that the stats are correct: https://github.com/JuliaCI/CoverageBase.jl/issues/36

**Comment by DilumAluthge** [comment]
I think https://github.com/JuliaCI/julia-buildbot/pull/207 is actually going to be the best fix for this solution, since it does not require that we hard-code a list of external stdlibs.
