### ISSUE TITLE
Precompile errors should attach the underlying exception

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#41109]
Currently, failed precompile just uses `error` when it encounters an exception. Probably better for it to attach the underlying exception that caused it to fail?

https://github.com/JuliaLang/julia/blob/66c3375bcad74630a031301f145ee88b9de28c87/base/loading.jl#L1430-L1467

**Comment by DilumAluthge** [comment]
I believe you can just get the exception directly by doing e.g. `import Foo`, right?

**Comment by BioTurboNick** [comment]
Possibly, though I believe it's proper exception handling to propagate originating errors. Once #40642 is merged, which allows the previous error to be re-displayed, this will become more apparent as only the stack trace from `compilecache` would be accessible, and not the trace from the actual problem.

**Comment by KristofferC** [comment]
> I believe you can just get the exception directly by doing e.g. import Foo, right?

I think this issue is in fact about normal precompilation that occurs during `import Foo` and not Pkg parallel precompilation.

**Comment by vtjnash** [comment]
There is no distinct error there though, since it is just a failed precompile process, and that is all it knows. Also that outer packages should not be trying to delve into recursively generated errors, and just treat is as: using failed.
