### ISSUE TITLE
Floating point vararg functions are not handled correctly in `@ccall`

### ISSUE THREAD

**Issue by melonedo** [JuliaLang/julia#41104]
I am testing the C's `printf` via `ccall` in julia, however, the "%f" format did not work as expected. 
```julia
foo(x) = ccall(:printf, Cint, (Cstring, Cfloat), "%f\n", x) # helper function
foo(12.3) => 0.000000
```
The output is "0.000000" on x64 windows and arm64 linux, but not on x64 linux.
Poring through `@code_llvm`, printf is called as:
```
%17 = call i32 inttoptr (i64 140719310539600 to i32 (i64, float)*)(i64 441151672, float %16)
```
but printf is called as below if I use `clang -o - -S -emit-llvm` (on arm64 linux and x64 linux):
```
%2 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i32 0, i32 0), double 1.230000e+01)
```
I have not figured out how vararg is passed on arm64, but [Microsoft document on x64 calling convention](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#varargs) says that vararg floating-point argument must be duplicated in both integer and floating-point registers, which I guess is the reason why "0.00000" is printed.

**Comment by Gnimuc** [comment]
The correct syntax for calling vararg functions is `T...`:
```
julia> foo(x) = ccall(:printf, Cint, (Cstring, Cfloat...), "%f\n", x)
foo (generic function with 1 method)

julia> foo(12.3)
12.300000
10
```
