### ISSUE TITLE
undefined _Debug_ in examples of @test_logs of module Test (Julia 1.6.1) 

### ISSUE THREAD

**Issue by ajalexei** [JuliaLang/julia#41117]
versioninfo(): 
Julia Version 1.6.1 
Commit 6aaedecc44 (2021-04-23 05:59 UTC) 
Platform Info: 
  OS: Linux (aarch64-unknown-linux-gnu) 
  CPU: unknown
  WORD_SIZE: 64 
  LIBM: libopenlibm 
  LLVM: libLLVM-11.0.1 (ORCJIT, cortex-a73)

This is a minor bug (I believe) on the webpage: [Unit Testing](https://docs.julialang.org/en/v1/stdlib/Test/#Other-Test-Macros) -- [Test.@test_logs
— Macro](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_logs). The two examples for @test_logs involving _min_level=Debug_ complain that _Debug_ is undefined if executed in the REPL/Jupyter, -- indeed it needs to be imported: _import Logging: Debug_. This is not mentioned anywhere on the _Unit Testing_ webpage. I suggest adding this missing import statement to the examples.

**Comment by fredrikekre** [comment]
Somewhat fixed by https://github.com/JuliaLang/julia/pull/40980 but the examples could use a `using Logging` I guess.
