### ISSUE TITLE
Semicolons inside parentheses other than named tuple `(1 ; 2)`: valid syntax?

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#41121]
```
[(1 ; 2)]
1-element Vector{Int64}:
 2
```

I don't know what I expected would happen here, was just curious and tried it.

I understand it's evaluating "1 ; 2" as a multi-line expression and the last value of that is what it evaluates to. It also happens outside array expressions.

But should it? Either generally or just within an array?

This is not valid, so it isn't equivalent to `begin ... end`:
```
(1
 2)
```

**Comment by simeonschaub** [comment]
Yes, this is often useful for writing blocks in a concise way. Especially since you can't write `begin ... end` inside indexing expressions.
