### ISSUE TITLE
`pwd` or `homedir` does not generate a `path` that passes `isdirpath(path) == true`?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#41128]
It is interesting that `pwd` generate a `path` that `isdir` but not `isdirpath`:

```julia
julia> pwd() |> isdirpath
false

julia> pwd() |> isdir
true
```

I don't find a simple way using the functions provided in `Base.Filesystem` that can make it a real `dirpath`. The only way seems to be `pwd() * '/'`. However, this method is somehow ugly. Can we let `pwd` return a valid `dirpath`?

The same argument applies to `homedir`:

```julia
julia> homedir() |> isdirpath
false
```

**Comment by DilumAluthge** [comment]
How about `joinpath(pwd(), "")` and `joinpath(homedir(), "")`?

```julia
julia> joinpath(pwd(), "") |> isdir
true

julia> joinpath(pwd(), "") |> isdirpath
true

julia> joinpath(homedir(), "") |> isdir
true

julia> joinpath(homedir(), "") |> isdirpath
true
```

**Comment by singularitti** [comment]
I think it's fine. I just wish `pwd` & `homedir` could already do that. Maybe in Julia 2.0?

**Comment by giordano** [comment]
Do you actually have a use case where `isdirpath` is important?  I find myself more frequently needing to strip the trailing path separator, rather than adding it: `basename("/path/to/directory/")` would get the name wrong for example

**Comment by singularitti** [comment]
In my code [here](https://github.com/MineralsCloud/AbInitioSoftwareBase.jl/blob/1feb35f32d4bfe339081c8c5a26143dc59296954/src/fileops.jl#L111-L117), I found that `dirname` returns an empty string if users do not write `"./"` in the `path` in the same directory where I am running REPL. This will cause an error in `tempname`. But it is OK if you write a `./` before the file's name.

```julia
julia> tempname(dirname(".zshrc"))
ERROR: ArgumentError: "" is not a directory
Stacktrace:
 [1] tempname(parent::String; cleanup::Bool)
   @ Base.Filesystem ./file.jl:580
 [2] tempname(parent::String)
   @ Base.Filesystem ./file.jl:580
 [3] top-level scope
   @ REPL[3]:1

julia> tempname(dirname("./.zshrc"))
"./jl_casqr1"
```

So I wrote that `parentdir` function to return a valid path even if no `./` is prepended. But if still gives different result

```julia
parentdir("test.yaml") == pwd()  # true
parentdir("./test.yaml") == pwd() * '/'  # true
```

**Comment by giordano** [comment]
Well, I think you should be using [`abspath`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.abspath) instead of coming up with a custom function

**Comment by DilumAluthge** [comment]
The way that `pwd()` behaves is similar to how

**Comment by DilumAluthge** [comment]
If you run the GNU `pwd` (i.e. the `pwd` that is part of GNU coreutils), it will print the current working directory without a trailing slash. This is consistent with how the Julia `pwd()` function currently works.

So I think it's unlikely that we'll change the behavior of `pwd()` or `homedir()`, even in Julia 2.0.

**Comment by StefanKarpinski** [comment]
The `isdirpath` function probably should never have been exported. I did export it when I originally introduced it in 2077d1ab3f5d24a586753b9476b5541aab72697a, but that was long pre-1.0 when we were pretty fast an loose with what we exported.
