### ISSUE TITLE
Speed of ERROR: LoadError

### ISSUE THREAD

**Issue by 89z** [JuliaLang/julia#41138]
If I have a file like this:

~~~jl
println("south north")
~~~

Julia works fine:

~~~
PS C:\julia-1.6.1> Measure-Command { bin\julia one.jl }
Milliseconds      : 155
~~~

With a file like this:

~~~
notDef()
~~~

The error process seems much slower:

~~~
PS C:\julia-1.6.1> Measure-Command { bin\julia two.jl }
ERROR: LoadError: UndefVarError: notDef not defined
Stacktrace:
 [1] top-level scope
   @ C:\julia-1.6.1\two.jl:1
in expression starting at C:\julia-1.6.1\two.jl:1

Milliseconds      : 433
~~~

The `--compile` flag helps somewhat:

~~~
PS C:\julia-1.6.1> Measure-Command { bin\julia --compile=min two.jl }
ERROR: LoadError: UndefVarError: notDef not defined
Stacktrace:
 [1] top-level scope
   @ C:\julia-1.6.1\two.jl:1
in expression starting at C:\julia-1.6.1\two.jl:1

Milliseconds      : 322
~~~

but still seems to be quite slow compared to other options, like PHP:

~~~
PS C:\php> Get-Content one.php
<?php
notDef();

PS C:\php> Measure-Command { php one.php }
Fatal error: Uncaught Error: Call to undefined function notDef() in
C:\php\one.php:2
Stack trace:
#0 {main}
  thrown in C:\php\one.php on line 2

Milliseconds      : 23
~~~

Python:

~~~
PS C:\python> Get-Content one.py
notDef()

PS C:\> Measure-Command { python one.py }
Traceback (most recent call last):
  File "C:\python\one.py", line 1, in <module>
    notDef()
NameError: name 'notDef' is not defined

Milliseconds      : 25
~~~

Ruby:

~~~
PS C:\ruby> Get-Content one.rb
notDef()

PS C:\ruby> Measure-Command { ruby one.rb }
one.rb:1:in `<main>': undefined method `notDef' for main:Object (NoMethodError)

Milliseconds      : 121
~~~

**Comment by JeffBezanson** [comment]
This is really one of many examples of general latency issues, see for example #28092. Of course we want to improve this situation, but I don't think there is a specific bug here. The time difference is due to whatever happens to be pre-compiled in the system image we're using.

**Comment by 89z** [comment]
The linked issue is closed. So are you essentially saying "yeah, compared to these other languages it's significantly worse, and it wont get better (again, comparitively)"?

**Comment by JeffBezanson** [comment]
I'm saying this is a duplicate of many other issues, and just another example of a phenomenon we're well aware of, and therefore doesn't need its own issue. We very much want to improve this, but it is a fairly deep problem and will take some time.

**Comment by 89z** [comment]
Can you point to a single open issue on the topic? Otherwise it gives the impression that you're against fixing it, or at a minimum indifferent.

**Comment by JeffBezanson** [comment]
Sure, look at the "latency" label: https://github.com/JuliaLang/julia/issues?q=is%3Aopen+is%3Aissue+label%3Alatency

**Comment by 89z** [comment]
I apoligize, I think I am not being clear.

My goal is, to subscribe to a single issue, such that when that issue is closed, I know my problem has been fixed, or as least significantly improved. Up until one hour ago, that was this issue.

So you pointing me to a closed issue, doesnt help with that goal. Neither does pointing me to a list of 28 open issue, as being a Julia novice, I dont know which one would most closely match with my concern.

So can you please, point me to a single open issue?

**Comment by JeffBezanson** [comment]
#33333 is a good umbrella issue for this.

Just to check, is it general startup time you're concerned about, or is the error case particularly important for some reason?

**Comment by 89z** [comment]
general startup time
