### ISSUE TITLE
Adding `:-` as an operator to make logic DSLs nicer

### ISSUE THREAD

**Issue by saolof** [JuliaLang/julia#41147]
Suggestion: add `:-` as an operator with the explicit intention of facilitating logic eDSL's in Julia without having to resort to string macros.

To enable this, it should have a low precedence, and it should be counted as an assignment operator so that `p(x,y) :- a(x,z) , b(y,z) ` on its own line would parse as `p(x,y) :- (a(x,z) , b(y,z)) ` .

**Comment by saolof** [comment]
The main downside of this seems to be that the `-` operator becomes harder to quote. The upside of it is that `:-` is a fairly commonly occuring operator in some contexts and as such is valuable for DSL's.

**Comment by kimikage** [comment]
`:-` is ambiguouswith the pair of range operator and unary minus.  :-(

```julia
julia> p(x,y) = 1; a(x,z) = -2; b(y,z) = 3;

julia> x = 0; y = 0; z = 0;

julia> p(x,y) :- a(x,z) , b(y,z)
(1:2, 3)
```

**Comment by saolof** [comment]
> 
> 
> `:-` is ambiguous with the pair of range operator and unary minus. :-(
> 
> ```julia
> julia> p(x,y) = 1; a(x,z) = -2; b(y,z) = 3;
> 
> julia> x = 0; y = 0; z = 0;
> 
> julia> p(x,y) :- a(x,z) , b(y,z)
> (1:2, 3)
> ```

Right. On that topic, isn't that technically also true for the <-- operator, which seems to be listed in the prec-arrow list at https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm ?
