### ISSUE TITLE
Julia on M1 iPad Pro?

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#41210]
Hey folks, given we can now run Julia on the M1 MacBook Pro, any ideas on what steps would required to get it to run on the M1 iPad Pro?

**Comment by logankilpatrick** [comment]
Related to: #36617

**Comment by ArunSanganal** [comment]
I think it all boils down to OS now. M1 macs can run iPad/iPhone apps too but the other way round sounds like a tough task.

**Comment by ViralBShah** [comment]
We don't have a port for the OS on those devices, which is a significant undertaking - and the App store has restrictions on distributing compilers and such. Definitely a discussion for discourse.
