### ISSUE TITLE
Question on Threads.@threads

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#41231]
Hi,
Let's say i have started julia with `JULIA_NUM_THREADS=4`, however in one of my loop I only want to use 2 threads because it gives better performance. How do I do that with `Threads.@threads` ?
Thank you

**Comment by vchuravy** [comment]
Please ask questions like this on https://discourse.julialang.org or one of the other community platforms like Slack or Zulip.

You can have a bit more fine-grained control with `Threads.@spawn` or `Floops.jl` https://juliafolds.github.io/data-parallelism/howto/faq/#set-nthreads-at-run-time

**Comment by gitboy16** [comment]
Thank you for the link. I did as k on discourse but did not get any feedback. So the answer to my question is: it is not possible to do that with `Threads.@threads`. Can it be a feature request or is it unreasonable?

**Comment by gitboy16** [comment]
@vchuravy  the links you provided does not explain how the number of threads can set before a loop. Could you please re-open this issue? Thank you
