### ISSUE TITLE
Code coverage is no longer being submitted on `master`?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#41230]
E.g. if you look at https://app.codecov.io/github/JuliaLang/julia/commits?page=1, the last commit with coverage information was 12 days ago.

**Comment by DilumAluthge** [comment]
Maybe something is going wrong when the buildbot tries to upload coverage reports to Codecov and Coveralls.

@staticfloat Do you know where in the buildbot logs I would find the part that uploads coverage reports?

**Comment by vtjnash** [comment]
Seems like someone changed the build script? Here's the log: https://build.julialang.org/#/builders/77/builds/6/steps/10/logs/stdio

**Comment by DilumAluthge** [comment]
> Seems like someone changed the build script? Here's the log: https://build.julialang.org/#/builders/77/builds/6/steps/10/logs/stdio

Yes that somebody was me, I think. https://github.com/JuliaCI/julia-buildbot/pull/207

Let me take a look and see what's going wrong.

**Comment by DilumAluthge** [comment]
That error is strange. It says that it can't find the `stdlib` directory.... but the preceding lines suggest that it indeed is finding the `stdlib` directory.

**Comment by DilumAluthge** [comment]
Is there an easy way I can debug the build script?

We don't submit coverage from PRs anymore, so I can't just open a dummy PR and look at the logs.

**Comment by DilumAluthge** [comment]
Okay, I think I see the issue. It looks like the coverage buildbot doesn't actually have a copy of the original source code. Unfortunately, in order to automatically generate the list of external stdlibs, we need a copy of the source code (because we look for files of the form `stdlib/*.version` to identify external stdlibs).

Is there a way to get a checkout of the source code on the coverage buildbot.

**Comment by DilumAluthge** [comment]
Alright, here's a short-term fix: https://github.com/JuliaCI/julia-buildbot/pull/208

Long-term, I do want to get the automatic feature working.

Anyway, https://github.com/JuliaCI/julia-buildbot/pull/208 should fix coverage submission.

Right now, coverage is at:
- Codecov: 75%
- Coveralls: 75%

Once https://github.com/JuliaCI/julia-buildbot/pull/208 is merged, those numbers should go up, since we will be excluding all the external stdlibs.

**Comment by DilumAluthge** [comment]
Alright, here is an update.

I merged https://github.com/JuliaCI/julia-buildbot/pull/208, which hard-codes the list of external stdlibs. Now the coverage jobs seem to be passing again. Example log that passed: https://build.julialang.org/#/builders/77/builds/7

And coverage is being submitted again: https://app.codecov.io/gh/JuliaLang/julia/commits?page=1

And the coverage statistics are up:
- Codecov: 88%
- Coveralls: 88%

**Comment by DilumAluthge** [comment]
I'm going to leave this issue open until I figure out how we can auto-generate the list of external stdlibs, instead of hard-coding it.

**Comment by DilumAluthge** [comment]
> Seems like someone changed the build script?

![5A3D6010-F4DB-4F18-A06E-6CCB090497FF](https://user-images.githubusercontent.com/5619885/122471259-0b308680-cf8d-11eb-93ba-bf93d0488d0b.jpeg)

**Comment by DilumAluthge** [comment]
Anyway, code coverage looks to be fixed now.
