### ISSUE TITLE
error when static parameter is used in ccall

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#41278]
E.g.
```julia
julia> f(x::T) where T = ccall(:printf, Cvoid, (Cstring, T), "%.3f\n", x)
ERROR: TypeError: in ccall method definition, expected Type, got a value of type TypeVar
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```
See https://github.com/JuliaGraphics/Gtk.jl/issues/573. The lowered code still looks fine, so this seems to happen somewhere inside the interpreter.

Git bisect blames 5dbf45a2997acd26e0f72abaa320c9d0d54956a1.

**Comment by simeonschaub** [comment]
Looks like this "fixes" it:
```julia
diff --git a/src/method.c b/src/method.c
index 48b074e800..2e989c8fdb 100644
--- a/src/method.c
+++ b/src/method.c
@@ -23,6 +23,7 @@ jl_method_t *jl_make_opaque_closure_method(jl_module_t *module, jl_value_t *name
 
 static void check_c_types(const char *where, jl_value_t *rt, jl_value_t *at)
 {
+    return;
     if (jl_is_svec(rt))
         jl_errorf("%s: missing return type", where);
     JL_TYPECHKS(where, type, rt);
```
Is `check_c_types` too strict here? Or is there a way not erroring in this case could lead to corruption or other nasty problems?

**Comment by vtjnash** [comment]
The C language has no idea what a TypeVar is, so we cannot pass those to C. I cannot specifically comment what should be there instead. `Ref{T}` is a very common choice though. Or possibly `Ptr{Void}` there?

**Comment by jonathanBieler** [comment]
@vtjnash Would this be a valid solution ? tests pass but not too sure if it's a dirty hack or not.

```julia
@generated function uv_dispatch(src::Ptr{Nothing}, callback::Ptr{Nothing}, data) 
    :( return ccall(callback, Cint, ($(data),), data) )
end
```

I tried `Ptr{Void}` but that doesn't work. I think `callback` can expect any kind of parameters (e.g. sometimes it's just Int64) so a fixed signature doesn't do.

**Comment by vtjnash** [comment]
In the Gtk API guide, it is listed as a void*, which in Julia is a Ptr{T} or Ptr{Cvoid} (since we always pass C_NULL), which is close enough to a UInt. It is not a T, so the original code author was apparently wrong there.

**Comment by jonathanBieler** [comment]
The Int64 I see actually comes from that line :

https://github.com/JuliaGraphics/Gtk.jl/blob/7e463f728e0f5b34a9caf9a40151f1c20e093ac3/src/GLib/signals.jl#L358

But if I print the type of `data` I also see GObjects (like GtkWindowLeaf). 

You're the one that wrote that code btw ;) (in 2014!)

**Comment by vtjnash** [comment]
That is the only place I see it, so if you are seeing anything else, that sounds like memory corruption of some sort

**Comment by JeffBezanson** [comment]
https://github.com/JuliaGraphics/Gtk.jl/pull/577

**Comment by JeffBezanson** [comment]
This is supposed to be an error, so let's fix it in Gtk for now and revisit if more instances of this appear in the wild.

**Comment by ronisbr** [comment]
Hi!

I was using this kind of construction in BaremetalPi.jl. I was working fine, but returns an error in v1.7.0. Can anyone advice me, please, what is the best solution for my case?

https://github.com/ronisbr/BaremetalPi.jl/blob/master/src/ioctl.jl
