### ISSUE TITLE
Inference gives up for a function involving `eval`ed code

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#41306]
Inference seems to give up for a function `g` defined in terms of another function `f` defined by `eval`ing code.

MWE reduced from an actual use case:
```jl

julia> code = :(x -> 2x)
:(x->begin
          #= REPL[38]:1 =#
          2x
      end)

julia> f = eval(code)
#1 (generic function with 1 method)

julia> @code_warntype f(1)    # correctly inferred
Variables
  #self#::Core.Const(var"#1#2"())
  x::Int64

Body::Int64
1 ─ %1 = (2 * x)::Int64
└──      return %1

julia> g(x) = f(x) + 1;

julia> @code_warntype g(1)    # not inferred
Variables
  #self#::Core.Const(g)
  x::Int64

Body::Any
1 ─ %1 = Main.f(x)::Any
│   %2 = (%1 + 1)::Any
└──      return %2
```

**Comment by simeonschaub** [comment]
`f` is a non-constant global, that's why it infers to `Any`. If you declare `f` as `const`, it should be type stable again.

**Comment by dpsanders** [comment]
Thanks, but `f` on its own is inferring correctly?

**Comment by simeonschaub** [comment]
Yes, `@code_warntype` always assumes the function and all arguments are concretely typed.
