### ISSUE TITLE
should @sync unwrap TaskFailedExceptions when constructing CompositeException?

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#41301]
Right now we take any exception that occurs in a `@sync` block and just put it straight into a `Composite` exception
https://github.com/JuliaLang/julia/blob/b46df09eb651eba97776fe73e8044e0456e81320/base/task.jl#L359-L363
However large parts of `@sync` blocks are in turn `@async` statements, and any exception thrown from a `@async` statement will be a `TaskFailedException`.

There is a case to be made for unwrapping them.
(Arguably the same for `CapturedExceptions` with distributed)
Upside of unwrapping them is that this is probably what people want, it is the useful information.
Downside is it is a loss of information, someone might want the task.

I lean towards not doing this, and just doing https://github.com/JuliaLang/julia/issues/41300
at least at first, which should solve most of the pain.

**Comment by JeffBezanson** [comment]
> Downside is it is a loss of information, someone might want the task.

Yes, this loses a lot of information, I don't think we should do it.

**Comment by nalimilan** [comment]
See also https://github.com/JuliaLang/julia/issues/38931.
