### ISSUE TITLE
Equality of parametric types

### ISSUE THREAD

**Issue by jmichel7** [JuliaLang/julia#41314]
I have used a parametric type for modular arithmetic for some time, and
it seemed to work well

```
struct Mod{p}<:Number
  n::Int
  function Mod{p}(a::Integer) where {p}
    new(mod(a,p))
  end
end

Base.zero(::Type{Mod{p}}) where p = Mod{p}(0)
Base.:(==)(x::Mod,y::Mod) = x.n==y.n
Base.:+(x::Mod{p}, y::Mod{p}) where p = Mod{p}(x.n+y.n)
Base.:*(x::Mod{p}, y::Mod{p}) where p = Mod{p}(x.n*y.n)
Base.:-(x::Mod{p}, y::Mod{p}) where p = Mod{p}(x.n-y.n)
Base.:-(x::Mod{p}) where {p} = Mod{p}(-x.n)
Base.inv(x::Mod{p}) where p = Mod{p}(invmod(x.n,p))
Base.:/(x::Mod{p}, y::Mod{p}) where p = x * inv(y)
```

with that I can do:

```
julia> m=Mod{3}.([1 2;3 4])
2×2 Matrix{Mod{3}}:
 Mod{3}(1)  Mod{3}(2)
 Mod{3}(0)  Mod{3}(1)

julia> m*m
2×2 Matrix{Mod{3}}:
 Mod{3}(1)  Mod{3}(1)
 Mod{3}(0)  Mod{3}(1)
```

but I found the following problem. If I build an element of the type `Mod{3}`
in an indirect way:

```
struct foo
  p::Int16
end

x=Mod{foo(3).p}(1)
```

then I get problems

```
julia> x+Mod{3}(1)
ERROR: promotion of types Mod{3} and Mod{3} failed to change any arguments
Stacktrace:
 [1] error(::String, ::String, ::String)
   @ Base ./error.jl:42
 [2] sametype_error(input::Tuple{Mod{3}, Mod{3}})
   @ Base ./promotion.jl:316
 [3] not_sametype(x::Tuple{Mod{3}, Mod{3}}, y::Tuple{Mod{3}, Mod{3}})
   @ Base ./promotion.jl:310
 [4] promote
   @ ./promotion.jl:293 [inlined]
 [5] +(x::Mod{3}, y::Mod{3})
   @ Base ./promotion.jl:321
 [6] top-level scope
   @ REPL[8]:1
```

this is due to

```
julia> typeof(x)==Mod{3}
false
```
which  makes Julia go to  the default code to  add numbers, not to my code.
This  is annoying! What should I do?

**Comment by simeonschaub** [comment]
> If I build an element of the type Mod{3} in an indirect way:

You are converting 3 to an `Int16`, so it is expected that they are different types. Please use https://discourse.julialang.org for questions.

**Comment by jmichel7** [comment]
On Tue, Jun 22, 2021 at 08:38:22AM -0700, Simeon Schaub wrote:
> You are converting 3 to an `Int16`, so it is expected that they are different types.

Sorry to have been silly, this escaped me. Is there a way to coerce
implicitely the argument p in `Mod{p}` to an Int to avoid such mistakes?
------------------------------------------------------------------------------
Jean MICHEL, Groupes et representations, IMJ-PRG UMR7586 tel.(33)157279144
Bureau 639 Bat. Sophie Germain Case 7012 - 75205 PARIS Cedex 13
