### ISSUE TITLE
Display of Bool vectors as true/false instead of 0/1

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#41337]
I think it is some design decision to display Bool vectors as 1 (true) or 0 (false) like in 

```
julia> x = ones(Bool,5)
5-element Vector{Bool}:
 1
 1
 1
 1
 1

julia> x[1]
true

julia> y = zeros(Bool,5)
5-element Vector{Bool}:
 0
 0
 0
 0
 0

julia> y[1]
false

```
Nonetheless, there is a little inconsistency when displaying individual entries of the same vectors as true/false.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/30575
