### ISSUE TITLE
start new tasks in the parent world?

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#41332]
Currently Tasks always launch in the newest world age. This blocks inference, and some optimizations. Would anyone's code break if we instead launched them in the parent world of the task that allocated it?

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/issues/35690

**Comment by JeffBezanson** [comment]
Yes we should definitely do this. It's a no-brainer for inference as well as a general cilk-like view of the world where parallel execution is an implementation detail of a serial program. Easy to get the current behavior with `@spawn @invokelatest ...`.
