### ISSUE TITLE
certain recursive type definitions are not allocated inline

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#41349]
In this example, Julia does not realize that `B` can be allocated inline, which leads to `B` being boxed when used inside other types:
```julia
julia> struct A{T}
           x::Ptr{T}
       end

julia> struct B
           x::A{B}
       end

julia> B.name.flags
0x00
```

**Comment by JeffBezanson** [comment]
There happens to be a test_broken for just this case: https://github.com/JuliaLang/julia/blob/ed4c44fbafbbace523ebdc9440bf1f542157048a/test/core.jl#L7223
