### ISSUE TITLE
zero(::Vector{DateTime}) is wrong (and inconsistent with zero(DateTime})

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#41348]
`zero` is supposed to return the additive identity.
`zero(::DateTime)` does:
```julia
julia> zero(DateTime(2021))
0 milliseconds
```

But for a `zero(::Vector{DateTime})` it does not
```julia
julia> zero([DateTime(2020), DateTime(2021)])
2-element Vector{DateTime}:
 0000-12-31T00:00:00
 0000-12-31T00:00:00
```

**Comment by jishnub** [comment]
Given that `zero(DateTIme)` is not a `DateTime`, perhaps we need a specialized `zero` implementation for `Array`s here? The default implementation uses `similar` which does not result in the correct type. Perhaps something like this might work:

```julia
julia> Base.zero(v::Array{DateTime}) = fill(zero(DateTime), size(v))

julia> a
2-element Vector{DateTime}:
 2020-01-01T00:00:00
 2021-01-01T00:00:00

julia> zero(a)
2-element Vector{Millisecond}:
 0 milliseconds
 0 milliseconds

julia> a + zero(a) == a
true
```

except this should be made more general.

**Comment by oxinabox** [comment]
`similar` takes an `eltype` arg.
It needs to take the `eltype` from the step of the range, or from the type of `start-finish`, or from `zero(start)`.
any would work
