### ISSUE TITLE
unexpected precompile warning in 1.7.0-beta2

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#41355]
This is originally reported by @fonsp here: https://github.com/Roger-luo/Configurations.jl/issues/45

while trying to debug it I find this seems to be a regression, since I cannot reproduce it in previous julia versions.

**Comment by Roger-luo** [comment]
seems this happens on DocumenterTools as well

```
julia> using GarishPrint, DocumenterTools
[ Info: Precompiling DocumenterTools [35a29f4d-8980-5a13-9543-d66fff28ecb8]
WARNING: Method definition Any(Any...) in module DOM at /home/roger/.julia/packages/Documenter/f5jts/src/Utilities/DOM.jl:191 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Any(Any...) in module DOM at /home/roger/.julia/packages/Documenter/f5jts/src/Utilities/DOM.jl:192 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **

```

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/41277

**Comment by jaakkor2** [comment]
I see this with `using JSON3` and  `using NearestNeighbors` when I have removed `.julia\compiled\v1.7`-folder completely.  After the first `using`, warnings do not show up anymore.
