### ISSUE TITLE
Compute release checksums on the buildbots

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#41364]
We should have the buildbots that build our release binaries compute the checksums and upload them to S3 alongside the binaries. So for example, we'd have:
- julia-1.6.1-freebsd-x86_64.tar.gz
- julia-1.6.1-freebsd-x86_64.tar.gz.asc
- julia-1.6.1-freebsd-x86_64.sha256
- julia-1.6.1-freebsd-x86_64.md5

Then we can change the linking structure on the website to have checksums available for each individual download rather than one file that lists all of them. That would negate needing to download all of the binaries for all of the platforms for each release just to compute checksums.

(Issue opened here on request, as this is where the buildkite config will live)

**Comment by vtjnash** [comment]
Moved to https://github.com/JuliaCI/julia-buildkite/issues/193
