### ISSUE TITLE
Gtk.jl fails to precompile with Julia v1.7.0-beta2

### ISSUE THREAD

**Issue by magister-ludi** [JuliaLang/julia#41379]
See the [discourse topic](https://discourse.julialang.org/t/gtk-jl-fails-to-precompile-with-julia-v1-7-0-beta2/63603) with the same title.

On Windows (Win10) and Linux (OpenSUSE Leap 15.2) precompilation fails, flagging the function
```
function uv_dispatch(src::Ptr{Nothing}, callback::Ptr{Nothing}, data::T) where T
    return ccall(callback, Cint, (T,), data)
end
```
with the error
```
Failed to precompile Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44] to C:\Users\xxx\.julia\compiled\v1.7\Gtk\jl_7ACB.tmp.
ERROR: LoadError: TypeError: in ccall method definition, expected Type, got a value of type TypeVar
Stacktrace:
  [1] top-level scope
    @ C:\Users\xxx\.julia\packages\Gtk\3TfRG\src\GLib\signals.jl:331
```
Line 331 of `signals.jl` is the first line of the function definition above. Advice from @sostock on discourse is that this is an error on 1.7, and on master.

**Comment by fredrikekre** [comment]
#41278
