### ISSUE TITLE
syntax for creating empty n-dimensional arrays

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#41389]
These currently throw an error:

```julia
julia> [;]
ERROR: syntax: unexpected ";"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> [;;]
ERROR: syntax: unexpected ";"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> [;;;]
ERROR: syntax: unexpected ";"
Stacktrace:
 [1] top-level scope
   @ none:1
```

I think it would make sense for them to return an empty vector/0×0 matrix/0×0×0 array respectively.

**Comment by BioTurboNick** [comment]
I don't have time to implement it myself right now, but I looked into it:

`[;]` makes it into `parse-cat` and then the token stream is sent into `parse-eq` to determine the first value. The error originates inside `parse-eq`. Perhaps just need to check if the first value is a semicolon? Could set `first` to null, send it into `parse-array`. I'm not sure what `parse-array` would do when `first` is null, but I'm guessing it might generate (or could be made to generate) the syntax `vect`, `ncat 2`, `ncat 3`, with no contents. Then `expand-ncat` in `julia-syntax.scm` may need to check if `a` is null, or the helper functions all need to be made aware of the potential for `a` could be null (`hasrows-flatten`, `is-1d`). `is-1d` should return true, which would lower into `hvncat(2)`, `hvncat(3)`, which with #41197 will produce the desired output.

**Comment by StefanKarpinski** [comment]
Nice idea. This would "only" leave us with no literal syntax for zero-dimensional arrays, but fortunately there is no such thing!
