### ISSUE TITLE
edit(::Method) doesn't work in 1.7-beta2

### ISSUE THREAD

**Issue by rashidrafeek** [JuliaLang/julia#41408]
For eg,
```julia
edit(methods(match).ms[1])
```
doesn't work in 1.7-beta2 and it returns `nothing`.

This was due to #39481 which changed `edit(::Function)` to return the method list instead of showing an error. It suggests using a shortcut, num-(ctrl-q) to go to the specific method from the list. But this doesn't seem to work for me (Maybe I am not doing it correctly, but didn't find any docs regarding this shortcut). Even though, I think the above code block not working was not intended in that PR.

**Comment by JeffBezanson** [comment]
Oops :grimacing: Thanks, good catch. We need to add an explicit `edit(::Method)` method now. Would you be willing to make a PR for it?

**Comment by rashidrafeek** [comment]
@JeffBezanson Done :) .

**Comment by rashidrafeek** [comment]
Just an opinion on #39481. Shouldn't there be an indication on what to do with the method list, when showing a method list. Like telling to use `edit(f,id)` where `id` is the index of the method instead of `edit(f)`. Otherwise it seems like the function is doing something unrelated to the function call.
