### ISSUE TITLE
Error in testset mpfr

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#41417]
From https://build.julialang.org/#/builders/65/builds/674/steps/5/logs/stdio

```
Error in testset mpfr:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\mpfr.jl:609
  Expression: log2(x) == log2(42)
   Evaluated: 5.3923174227787607 == 5.39231742277876
```

**Comment by fredrikekre** [comment]
Happens on every win64 run.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/41383#issuecomment-872040502

**Comment by thofma** [comment]
Because `BigFloat` with `53` bits precision should be the same as `double`:
> In particular, with a precision of 53 bits and in any of the four standard rounding modes,
> MPFR is able to exactly reproduce all computations with double-precision machine floatingpoint numbers

(See page 2 of https://www.mpfr.org/mpfr-current/mpfr.pdf)

**Comment by aviatesk** [comment]
Thanks, I see.

With the help from Slack, I confirmed the error is caused by the change of `log2(::Float64)`'s behavior:
```
julia> versioninfo()
Julia Version 1.8.0-DEV.94
Commit db71a65985 (2021-06-29 21:40 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, znver2)
julia> log2(42)
5.392317422778761
julia> setprecision(53) do; log2(BigFloat(42)); end
5.3923174227787607
```

`log2` internally uses `@horner`, which is certainly affected by the PR.
