### ISSUE TITLE
Clicking on another docs version should point to the equivalent page

### ISSUE THREAD

**Issue by jtrakk** [JuliaLang/julia#41429]
If I'm on the [v1.5 Filesystem docs](https://docs.julialang.org/en/v1.5/base/file/) and I click on the v1.6 link in the bottom-left corner, it goes to the home page https://docs.julialang.org/en/v1.6/, not the Filesystem page, which is annoying. I want to go to the equivalent page of the other version.

**Comment by fredrikekre** [comment]
Can you reopen here: https://github.com/JuliaDocs/Documenter.jl ?

For the Julia manual you should **always** be on the `v1` version though, it is valid for all of Julia 1.X.
