### ISSUE TITLE
Disallow if (a = b) that is different from if a = b

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#41422]
```
if (a = b)
```

is a bug waiting to happen, and serves not good purpose. I'm not proposing disallowing parenthesis, just in that context, i.e. ok with == what was meant. Longer story:

https://discourse.julialang.org/t/my-brain-is-hard-wired-against-help-me-julia/63532/64?u=palli

This would be a (technically) breaking change. Can it still be done in pre-2.0?

**Comment by simeonschaub** [comment]
> is a bug waiting to happen, and serves not good purpose.

It's a perfectly valid thing to do and assigning in if-clauses can definitely be useful. Something like this could be pointed out by a linter, but it is not something the language should disallow.

**Comment by PallHaraldsson** [comment]
Ok, can be useful, while I recall it most often (always?) a bug in C. Would it be done like that in Julia most often, or by more complex expression? At least that one is disallowed without parentheses and I'm trying to think of a good counterexample.
