### ISSUE TITLE
incorrect spacing of 1-wide colored unicode characters

### ISSUE THREAD

**Issue by MarcMush** [JuliaLang/julia#41458]
A change of color after some unicode characters produces aditionnal spaces after the change of color

I guess it's yet another issue with windows, I can reproduce in cmd and powershell, in WSL too. But it works as intended in the Git Bash terminal.

```julia
PS C:\Users\Marc> julia --startup-file=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

julia> print("\e[31m🂡🂥🂳🃂🃔XYZ\e[32mABC")
🂡🂥🂳🃂🃔XYZ     ABC
```

![image](https://user-images.githubusercontent.com/35898736/124368114-05f65b80-dc5e-11eb-81d9-6e3e767bf904.png)

**Comment by simeonschaub** [comment]
This seems to be an issue with how your terminal renders these characters, so I don't think there is anything we can do here.

**Comment by MarcMush** [comment]
I get that it is a problem with windows, but it doesn't mean there's nothing to be done (I don't know anything about the internals of this issue, so feel free to correct me)

It happens also *sometimes* without colors, and here with a more common character, `\bbE`:
![image](https://user-images.githubusercontent.com/35898736/125174650-275bc800-e1c7-11eb-82d4-b271d9410df4.png)

It's especially annoying with `OhMyREPL`, where the caret position is offset (note that on this last line, there is no space character and the caret is actually at the end of the line, not between `r` and `d`)

**Comment by StefanKarpinski** [comment]
What would you suggest doing?

**Comment by MarcMush** [comment]
since it doesn't happen all the time, it feels like there could be a way to fix it

but I honestly don't know anything about it, I have no idea

it's a bit frustrating to have these kind of bugs with the lastest versions of Powershell and Windows Terminal

**Comment by StefanKarpinski** [comment]
Julia just prints bytes to the terminal and then it's entirely up to the terminal what to do with that. If the Windows terminal doesn't handle ANSI escapes and/or Unicode characters correctly, I don't see how we can do anything about it. I would suggest opening issues on the appropriate Microsoft repos or support forums.
