### ISSUE TITLE
Typo in Functions standard documentation

### ISSUE THREAD

**Issue by smigniot** [JuliaLang/julia#41456]
On the standard documentation, in the "Functions" chapter, please

* Replace "Julia keyword but a only singleton object of type Nothing"
* By "Julia keyword but only a singleton object of type Nothing"

**Comment by Keno** [comment]
The source for the documentation is here: https://github.com/JuliaLang/julia/blob/master/doc/src/manual/functions.md. If you submit a pull request with your changes, it'll be easier for a reviewer to evaluate and approve your suggestion.

**Comment by smigniot** [comment]
Done.

I know I should have done the pull request  right away. I was on mobile and didn't want the correction to be lost.


Le 3 juillet 2021 23:59:10 GMT+02:00, Keno Fischer ***@***.***> a écrit :
>The source for the documentation is here: https://github.com/JuliaLang/julia/blob/master/doc/src/manual/functions.md. If you submit a pull request with your changes, it'll be easier for a reviewer to evaluate and approve your suggestion.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JuliaLang/julia/issues/41456#issuecomment-873475998
-- 
***@***.*** - https://www.migniot.com/EF3C2B2A.pub.asc
