### ISSUE TITLE
Allow clamp!(x::AbstractVector, lo::AbstractVector, hi::AbstractVector)

### ISSUE THREAD

**Issue by noil-reed** [JuliaLang/julia#41467]
Currently clamp! only allows lo and hi to be number. Will be cool if lo and hi could be vector as well, that lo[i] and hi[i] are corresponding box constraint of x[i].

**Comment by andreasnoack** [comment]
I'm not sure why we have `clamp!` defined for arrays in the first place. For most operations such behavior is delegated to broadcasting, i.e. `x .= clamp.(x, lower, upper)` which would also handle the case you are asking for here.

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/22247

**Comment by noil-reed** [comment]
> I'm not sure why we have `clamp!` defined for arrays in the first place. For most operations such behavior is delegated to broadcasting, i.e. `x .= clamp.(x, lower, upper)` which would also handle the case you are asking for here.

Just in some cases I need to directly truncate values in memory, instead of assign a new object. Looks like it's already deprecated feature.

**Comment by noil-reed** [comment]
I guess better to keep consistency, better either deprecate clamp!(x:AbstractVector, a, b) as well, or reactivate this feature?

**Comment by andreasnoack** [comment]
> Just in some cases I need to directly truncate values in memory, instead of assign a new object.

Notice that `x .= clamp.(x, lower, upper)` truncates the array `x` in-place.
```julia
julia> pointer(x)
Ptr{Float64} @0x00000001167a1770

julia> x .= clamp.(x, -2.0, 2.0);

julia> pointer(x)
Ptr{Float64} @0x00000001167a1770
```

> I guess to keep consistency, better either deprecate `clamp!(x:AbstractVector, a, b)` as well, or reactivate this feature?

That was discussed in the linked PR and, to my surprise, it was decided that `clamp!` should stay.

**Comment by noil-reed** [comment]
> > Just in some cases I need to directly truncate values in memory, instead of assign a new object.
> 
> Notice that `x .= clamp.(x, lower, upper)` truncates the array `x` in-place.
> 
> ```julia
> julia> pointer(x)
> Ptr{Float64} @0x00000001167a1770
> 
> julia> x .= clamp.(x, -2.0, 2.0);
> 
> julia> pointer(x)
> Ptr{Float64} @0x00000001167a1770
> ```
> 
> > I guess to keep consistency, better either deprecate `clamp!(x:AbstractVector, a, b)` as well, or reactivate this feature?
> 
> That was discussed in the linked PR and, to my surprise, it was decided that `clamp!` should stay.

Oh, thanks!
