### ISSUE TITLE
1.7 allocates where 1.6 doesn't

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/julia#41488]
In [KeywordCalls.jl](https://github.com/cscherrer/KeywordCalls.jl) we have some tests like this:

```julia
struct Foo{N,T}
    nt::NamedTuple{N,T}
end

@kwstruct Foo(a,b)
@test 0 == @ballocated Foo((b=1,a=2))
```

The `@kwstruct Foo(a,b)` expands to

```julia
julia> @macroexpand @kwstruct Foo(a,b)
quote
    function _call_in_default_order(::Type{Foo}, nt::NamedTuple{(:a, :b)})
        return Foo(NamedTuple{(:a, :b)}(nt))
    end

    function Foo(nt::NamedTuple)
        $(Expr(:meta, :inline))
        aliased = (alias)(Foo, nt)
        merged = merge((;), aliased)
        sorted = _sort(merged)
        return _call_in_default_order(Foo, sorted)
    end

    Foo(; kw...) = Foo(NamedTuple(kw))

    has_kwargs(::typeof(Foo)) = true

    Foo(nt::NamedTuple{(:a, :b), T}) where T = Foo{(:a, :b), T}(nt)

    build(::Type{Foo}, ::NamedTuple{(:a, :b), T}) where T = true
end
```

where `_sort` is like this:
```julia
@generated _sort(nt::NamedTuple{K}) where {K} = :(NamedTuple{($(QuoteNode.(sort(collect(K)))...),)}(nt))
```

The `aliased` bit doesn't really apply here (no aliases, so it defaults to `identity`. But just in case, it's

```julia
@inline alias(f,::Val{k}) where {k} = k

alias(f, tup::Tuple) = alias.(f, tup)

function alias(f, nt::NamedTuple{K}) where {K} 
    newnames = alias(f, Val.(K))
    NamedTuple{newnames}(values(nt))
end
```

These are passing in 1.6 but failing in the `nightly` build, and also failing in 1.7-beta. Some details [here](https://github.com/cscherrer/KeywordCalls.jl/runs/2994514715?check_suite_focus=true).

Here's the result in my terminal for 1.7-beta:
```julia
Precompiling project...
  12 dependencies successfully precompiled in 6 seconds
     Testing Running tests...
No Allocation: Test Failed at /home/chad/git/KeywordCalls.jl/test/runtests.jl:66
  Expression: 0 == #= /home/chad/git/KeywordCalls.jl/test/runtests.jl:66 =# @ballocated(Foo((b = 1, a = 2)))
   Evaluated: 0 == 32
Stacktrace:
 [1] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] macro expansion
   @ ~/git/KeywordCalls.jl/test/runtests.jl:66 [inlined]
 [3] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [4] macro expansion
   @ ~/git/KeywordCalls.jl/test/runtests.jl:64 [inlined]
 [5] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
 [6] top-level scope
   @ ~/git/KeywordCalls.jl/test/runtests.jl:35
```

Also...
```julia
julia> versioninfo()
Julia Version 1.7.0-beta2
Commit b570546b68 (2021-06-20 06:31 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
```

Also... @simeonschaub you're familiar with this code, would you have time to have a look?

**Comment by KristofferC** [comment]
What is `f`? It would be helpful to provide a fuller example that can be reproduced without having to dig too much inte the test files etc.

**Comment by JeffBezanson** [comment]
Would also be helpful to bisect if you can.

**Comment by cscherrer** [comment]
Good point. I think I can narrow it down a little. I'll edit the OP in a minute...

**Comment by cscherrer** [comment]
I've never thought about bisecting such a big codebase. I assume each step takes a while? Are there utilities to help with this? Or maybe it's just a little one-off script each time?

**Comment by mauro3** [comment]
Not sure this is what you asked for: git-bisect can help, e.g.: https://git-scm.com/docs/git-bisect

**Comment by cscherrer** [comment]
Thanks, I've used `git bisect`, just not in this context. I'll post something in the Zulip rather than clutter this issue.

**Comment by JeffBezanson** [comment]
This is interesting: `@allocated` gives 0; `@ballocated` gives 32. It can be difficult to exclude 100% of allocations that may happen around testing something.

**Comment by JeffBezanson** [comment]
Also code_llvm confirms there are no heap allocations in the generated code.

**Comment by cscherrer** [comment]
Oh, that's very weird. It's strange that 1.6 consistently gives 0 and 1.7 gives 32, but maybe it's a non-issue, and I should just change it to `@allocated`?

**Comment by vtjnash** [comment]
We changed the `@allocated` macro in v1.7 to attempt to be a bit more reliable and consistent–though possibly not actually a more useful number

**Comment by cscherrer** [comment]
Good to know, thanks @vtjnash
