### ISSUE TITLE
CI: Issue to track which CI jobs have been migrated to Buildkite

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#41509]
## 1. Packaging (building Julia from source)

- [ ] package_freebsd64
- [x] package_linux32
- [x] package_linux64
- [x] package_linuxaarch64
- [ ] package_linuxarmv7l
- [x] package_linuxppc64le
- [x] package_macos64
- [x] package_macosaarch64
- [x] package_musl64
- [ ] package_win32
- [ ] package_win64

## 2. Testing (running the Julia test suite)

- [ ] tester_freebsd64
- [x] tester_linux32
- [x] tester_linux64 (single-threaded)
- [x] tester_linux64 (multi-threaded)
- [x] tester_linux64 (under `rr`)
- [x] tester_linuxaarch64
- [ ] tester_linuxarmv7l
- [x] tester_linuxppc64le
- [x] tester_macos64
- [x] tester_macosaarch64
- [x] tester_musl64
- [ ] tester_win32
- [ ] tester_win64

## 3. Miscellaneous

- [x] analyzegc
- [x] doctest
- [x] embedding
- [x] llvmpasses
- [x] sanitizers
- [x] whitespace

## 4. Scheduled
- [x] coverage
- [ ] docdeploy
- [x] package_linux64 (with `USE_BINARYBUILDER=0`)
- [x] tester_linux64 (with `USE_BINARYBUILDER=0`)

**Comment by vtjnash** [comment]
Should this issue be migrated to https://github.com/JuliaCI/julia-buildkite/issues/?

**Comment by DilumAluthge** [comment]
Yes. But you can't transfer issues between different organizations 😭
