### ISSUE TITLE
Collision symbol $ for avoid broadcast and convert to Function

### ISSUE THREAD

**Issue by KirillZubov** [JuliaLang/julia#41500]
There’s used  symbol $ for avoiding broadcast
https://github.com/JuliaLang/julia/blob/460e981de68169acea23cbe768ea4f8be50d7b85/base/broadcast.jl#L1295
but also it is symbol is used for convert in Function.
This leads to a collision - one operator does two things.

```julia
f(x) =x
s = :(f(x))
julia> dump(s)
Expr
  head: Symbol call
  args: Array{Any}((2,))
    1: Symbol f
    2: Symbol x

julia> Broadcast.__dot__(s)
:(f.(x))

s_ = :($f(x))
julia> dump(s_)
Expr
  head: Symbol call
  args: Array{Any}((2,))
    1: f (function of type typeof(f))
    2: Symbol x

julia> Broadcast.__dot__(s_)
:((f)(x))
```
It looks like it needs to unique symbol/operator to avoiding broadcast.
 
mention @ChrisRackauckas

**Comment by simeonschaub** [comment]
`Broadcast.__dot__` is not meant to be called directly. It is only an implementation detail of the `@.` macro and inside a macro `$f` will be quoted correctly. If you really need to construct this expression manually, you can use  `:($(Expr(:$, :f))(x))`.
