### ISSUE TITLE
Simple debug http endpoint

### ISSUE THREAD

**Issue by janrous-rai** [JuliaLang/julia#41514]
For long-running production servers written in julia, we have built http server functionality for both request handling as well as diagnostic purposes. Unfortunately, due to thread starvation (http server may be scheduled on an os thread that is occupied by long-running non-yielding task) the diagnostic features may be unresponsive when we most need them.

It seems like it may be very useful to offer lightweight http debug endpoint built into the julia that could be used for interacting with the running julia runtime. Such endpoint could support features such as:
- triggering profiling (start, stop, grab profile, control profiling frequency)
- exposing system metrics (compilation times, task statistics, gc statistics) via `/metrics` - this could be periodically scraped with prometheus monitoring infrastructure)
- task diagnostics (look at stack traces of currently scheduled or queued tasks via `jl_live_tasks()`)
- ...

This could be an optional (off by default) feature that can be triggered with `--debug-port $x` command-line flag.

**Comment by vtjnash** [comment]
@kpamnany

**Comment by JeffBezanson** [comment]
I think what we really need here is #16350 (a dedicated interactive thread) so the system can always remain responsive, then a debugging server can be provided by a package.

**Comment by kpamnany** [comment]
I agree that a REPL thread solves responsiveness issues, but I'm not sure I understand the original issue -- why not just run with an extra thread?

**Comment by JeffBezanson** [comment]
`@spawn` and threaded for loops use all available threads by default, and even if you manage to avoid that, a package you call might use them.

**Comment by kpamnany** [comment]
Yes, true, but if you want a responsive service, then even without a Julia-designated dedicated thread, you should be able to spawn a task that spin-waits and thereby doesn't release its thread to other tasks.

**Comment by janrous-rai** [comment]
Yep. This proposal generally works around the current scheduling issues where variety of situations can block julia tasks from executing (long running, non-yielding tasks, stop the world garbage collection, ...). 

Having some basic ways of inspecting the state of the running server in these situations when julia code itself is not responsive/reliable would allow us to debug these situations more effectively.

Right now (with all the instrumentation/debugging written in julia) we are occasionally experiencing server that is operational but unresponsive for up to 90 minutes and we have no way of figuring out what is happening.

Lightweight debug http server that would expose some basic functionality and expose some metrics that can be periodically scraped would provide useful insights into these situations.

**Comment by janrous-rai** [comment]
> Yes, true, but if you want a responsive service, then even without a Julia-designated dedicated thread, you should be able to spawn a task that spin-waits and thereby doesn't release its thread to other tasks.

@kpamnany - one of the theoretical workarounds for scheduling issues we contemplates is somewhat similar to this proposal. Basically we would like to have a way to launch julia task on a newly created (dedicated) os thread such that this won't be considered by julia task scheduler (os thread will only run that one task and will get destroyed once the task finishes).

In effect, this would hand off the scheduling responsibility to the kernel (preemptive) scheduler. Assuming the amount of critical work is limited, this would be an acceptable overhead (potentially over-committing physical cores somewhat)

**Comment by janrous-rai** [comment]
> Yes, true, but if you want a responsive service, then even without a Julia-designated dedicated thread, you should be able to spawn a task that spin-waits and thereby doesn't release its thread to other tasks.

I'm also not sure whether you can guarantee this as there may be hidden non-explicit yield-points you might inadvertently trigger (e.g. when doing io).

**Comment by notinaboat** [comment]
To have a thread that does not yield but does not burn CPU, you could `@ccall` to `usleep` (see below).

You will still have the problem that other code using `@spawn` or `@threads` can try to assign a task to your never yielding thread. It would be really nice to have a way to request a lock on a particular thread that would stop the scheduler from assigning tasks to it.

If you want the thread to be externally wake-able while it is sleeping you could use OS IPC APIs directly.
I'm playing with code that uses a [`pipe(2)`](https://github.com/notinaboat/UnixIO.jl/blob/edf8e989ce2ceb21b2e46b7c61bd648e7b5ffc11/src/poll.jl#L53) to wake up a thread sleeping in [`poll(2)`](https://github.com/notinaboat/UnixIO.jl/blob/edf8e989ce2ceb21b2e46b7c61bd648e7b5ffc11/src/poll.jl#L191) by [`write(2)`-ing a byte](https://github.com/notinaboat/UnixIO.jl/blob/edf8e989ce2ceb21b2e46b7c61bd648e7b5ffc11/src/poll.jl#L65) to the pipe. This code uses unix file descriptors directly, so it does not interact with libuv or the Julia scheduler.

```julia
usleep_without_yield(us) = @gc_safe @ccall usleep(us::Cuint)::Cint
sleep_without_yield(seconds) = usleep_without_yield(round(Cuint, seconds * 1_000_000))

"""
    @gc_safe @ccall f(arg::Type, ...)::Type

Wrap a `@ccall` with `jl_gc_safe_[enter|leave]`.

This allows the GC to run during the `@ccall`.
Without this all threads will be blocked if the GC tries to run
during the `@ccall`.

The `@ccall` must not call back into Julia.
"""
macro gc_safe(ex)
    quote
        old_state = @ccall jl_gc_safe_enter()::Int8
        n = $(esc(ex))
        @ccall jl_gc_safe_leave(old_state::Int8)::Cvoid
        n
    end
end
```

**Comment by vtjnash** [comment]
With the interactive threads, I think this can be a package now

**Comment by quinnj** [comment]
Indeed, HTTP.jl by default will use the interactive thread to run the server event loop as of a few releases ago
