### ISSUE TITLE
Scoping for @distributed inside modules

### ISSUE THREAD

**Issue by Uroc327** [JuliaLang/julia#41529]
##### Background
This is from [slack](https://julialang.slack.com/archives/C6E78Q2NT/p1622650097031100?thread_ts=1622650097.031100&cid=C6E78Q2NT) (and also [discourse](https://discourse.julialang.org/t/distributed-code-loading-inside-modules/62334)).

I am writing a module, where I'd like to provide a function that uses the available workers to compute something. It appears that julia's `@distributed` (and also `@everything` which is required to set the distributed for loops up) does not work well when called from inside a module.

##### Question
What is the correct way to write a function inside a module, which uses `@distributed` for loops. The for loop as well as the code setting up the for loop will use other functions from the same module as well as from dependencies of this module.

##### Example
Let's say I have the following code in a normal script (the `map([x])` part is a placeholder for DrWatson.jl's `produce_or_load`):
```julia
x = <...> # Set up simulation, this may also be a struct

map([x]) do info
    @everywhere using Distributions

    @everywhere begin
        s = $(info)
        d = Categorical([0.25, 0.25, 0.25, 0.25])
    end

    @everywhere accum(lhs, rhs) = sum(lhs) + sum(rhs)

    m = @distributed accum for b = 1:100
        rand(d, s)
    end
end
```
This works completely fine. Moving the code into a function, so that I can execute the simulation with multiple parameters from the REPL without needing to edit the script also works fine:
```julia
function foo(x)
    map([x]) do info
        eval(macroexpand(Distributed, quote @everywhere using Distributions end))

        @everywhere begin
            s = $(info)
            d = Categorical([0.25, 0.25, 0.25, 0.25])
        end

        @everywhere accum(lhs, rhs) = sum(lhs) + sum(rhs)

        m = @distributed accum for b = 1:100
            rand(d, s)
        end
    end
end
```
To call the function, I can `include()` the script defining the function and just call it as a normal function.

When I move this exact function from a script that I `include()` into my module, the function fails:
```
$ julia --project
julia> using MyModule

julia> using Distributed

julia> foo(3)
ERROR: UndefVarError: accum not defined
Stacktrace:
 [1] (::RungePolarDPC.var"#124#126")(info::Int64)
   @ RungePolarDPC /data/projects/uni/RungePolarDPC.jl/src/SimulationData.jl:89
 [2] iterate
   @ ./generator.jl:47 [inlined]
 [3] _collect(c::Vector{Int64}, itr::Base.Generator{Vector{Int64}, RungePolarDPC.var"#124#126"}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
   @ Base ./array.jl:691
 [4] collect_similar
   @ ./array.jl:606 [inlined]
 [5] map
   @ ./abstractarray.jl:2294 [inlined]
 [6] test(x::Int64)
   @ RungePolarDPC /data/projects/uni/RungePolarDPC.jl/src/SimulationData.jl:79
 [7] top-level scope
   @ REPL[3]:1
```

I believe, the error is due to some scoping problems. `@everywhere` seems to set up the variables in a different scope, than `@distributed` is looking in. When I define `accum` in the local workspace again, it still doesn't work as it still has issues to find all variables defined and preallocated in the `@everywhere` block.

**Comment by vtjnash** [comment]
The `@everywhere` function is the same as `eval`, so I am guessing you probably did not mean to call that in a loop or inside a function. Usually, tools such as `@spawnat :any` or `pmap` are used to distribute the work units after `@everywhere` starts all of the nodes and configures their environment.

**Comment by mbauman** [comment]
I think further discussion can be on the linked discourse thread.
