### ISSUE TITLE
Segfault in jl_datatype_isinlinealloc in 1.7 beta

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#41532]
See here for a trace: https://github.com/JuliaMolSim/DFTK.jl/runs/3035339708?check_suite_focus=true#step:7:453. Can be reproduced by adding and testing DFTK.jl on 1.7 beta.
The issue appears to happen when we run a computation in Float64 precision then run it again in Float32.
I hesitated to post this since this is pretty far from a MWE, but I have zero idea how to reduce this and since 1.7 is in beta I figured it could be of interest.
Downstream issue https://github.com/JuliaMolSim/DFTK.jl/issues/480

**Comment by Sacha0** [comment]
Looks like a duplicate of https://github.com/JuliaLang/julia/issues/41503. Perhaps give the patch in https://github.com/JuliaLang/julia/pull/41516 a whirl? :)

**Comment by antoine-levitt** [comment]
Thanks! Looks indeed like the same. Closing this issue for now, I'll test the patch when it gets into a nightly and reopen if it doesn't fix it
