### ISSUE TITLE
Use shift based DFA for utf8 validation

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#41533]
There's a post going around on Twitter for how to write a super fast DFA, e.g. for UTF8 validation: https://twitter.com/_rsc/status/1413843059972923394?s=19. We have a UTF8 validation function, so we should try this technique. Should be reasonably simple to do.

**Comment by Keno** [comment]
I guess there's also this: https://lemire.me/blog/2020/10/20/ridiculously-fast-unicode-utf-8-validation/, which may be implemented elsewhere in the ecosystem.

**Comment by StefanKarpinski** [comment]
I read through the Lemire paper for inspiration on vectorized string length that handles our way of counting invalid data as characters correctly. Can't find the issue now.

**Comment by RohitRathore1** [comment]
> Can't find the issue now.
So, it means it has been resolved now?

**Comment by jakobnissen** [comment]
It's this: https://github.com/JuliaLang/julia/issues/33988 .

**Comment by StefanKarpinski** [comment]
No, it literally means I was not able to find the issue on GitHub. Thanks for the link, @jakobnissen.

**Comment by StefanKarpinski** [comment]
For what it's worth, UTF-8 validation is rarely a bottleneck in Julia since we don't do it unless the user explicitly asks for validation.

**Comment by StefanKarpinski** [comment]
It's fine to leave the flisp UTF-8 validation alone and use it for validating Julia source and have a separate pure Julia implementation for validating Julia strings. Validating source code is definitely not a bottleneck, so making that faster doesn't matter. So all someone has to do is replace [this stuff](https://github.com/JuliaLang/julia/blob/7d41d1eb610cad490cbaece8887f9bbd2a775021/base/strings/string.jl#L179-L186) with whatever fast vectorized implementation they want.

**Comment by ndinsmore** [comment]
This is completed in #47880
