### ISSUE TITLE
Broadcasted addition of one CarteseanIndex to an array of them emits cryptic error

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#41540]
```julia
julia> a = CartesianIndex(1, 2, 3)

julia> b = [a, a, a]
3-element Vector{CartesianIndex{3}}:
 CartesianIndex(1, 2, 3)
 CartesianIndex(1, 2, 3)
 CartesianIndex(1, 2, 3)

julia> b .+ a
ERROR: iteration is deliberately unsupported for CartesianIndex. Use `I` rather than `I...`, or use `Tuple(I)...`

# works
julia> b .+ Ref(a)
3-element Vector{CartesianIndex{3}}:
 CartesianIndex(2, 4, 6)
 CartesianIndex(2, 4, 6)
 CartesianIndex(2, 4, 6)

# works
julia> [c + a for c in b]
3-element Vector{CartesianIndex{3}}:
 CartesianIndex(2, 4, 6)
 CartesianIndex(2, 4, 6)
 CartesianIndex(2, 4, 6)
```

If iteration across the values of CarteseanIndex is not supported, shouldn't it just treat it as an atomic value in the broadcast without the need to wrap it in `Ref()`?

**Comment by JeffBezanson** [comment]
![American chopper meme of this](https://i.imgflip.com/5g92tt.jpg)

**Comment by BioTurboNick** [comment]
Hah! But seriously, `Use `I` rather than `I...`, or use `Tuple(I)...` is a bit opaque.

Does something depend on this code path emitting an error?

**Comment by JeffBezanson** [comment]
I doubt it is actually necessary; i think it was just to avoid possible confusion about whether a CartesianIndex is container-like.

**Comment by BioTurboNick** [comment]
So would this change be fine then?

```julia
broadcastable(x::Union{Symbol,AbstractString,Function,UndefInitializer,Nothing,RoundingMode,Missing,Val,Ptr,AbstractPattern,Pair}) = Ref(x)

# to

broadcastable(x::Union{Symbol,AbstractString,Function,UndefInitializer,Nothing,RoundingMode,Missing,Val,Ptr,AbstractPattern,Pair,AbstractCartesianIndex}) = Ref(x)
```

Since it doesn't support iteration, this seems to match what `broadcastable` says should happen.

**Comment by JeffBezanson** [comment]
Yeah I'm fine with that; maybe @timholy or @mbauman would want to weigh in.

**Comment by MasonProtter** [comment]
This would be fixed by https://github.com/JuliaLang/julia/pull/48404
