### ISSUE TITLE
Typeassert checks type before assignment

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#41557]
I was highly surprised by this behaviour. I'm not sure it's a bug, but it's certainly clumsy:

```
julia> function f()
           x = nothing
           x::Int = tryparse(Int, "1")
       end
f (generic function with 1 method)

julia> f()
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type Int64
```

It seems Julia checks the typeassert _before_ it evaluates the right hand side.

**Comment by JeffBezanson** [comment]
When you use the syntax `x::T = ...`, it's a type declaration on the variable, not just a type assert --- i.e. it means `x` must always have that type, so the first assignment `x = nothing` is an error.

**Comment by jakobnissen** [comment]
That is not consistent with actual behaviour:
```
julia> function g()
                  x = nothing
                  x = 0
                  x::Int
                  return x
              end
g (generic function with 1 method)

julia> g()
0
```
If `x::Int` asserted that `x` should always be an `Int` in the scope, I would also expect `g` to error.

**Comment by JeffBezanson** [comment]
That's a different syntax. Only `x::T = ...` and `local x::T` are declarations. The difference is based on whether `x` is being evaluated for its value --- just `x` by itself means "read the value of x", but on the left side of an assignment or in a `local` declaration the value is not read.

**Comment by jakobnissen** [comment]
Aha, I see - that is also what the documentation states. Thanks!
