### ISSUE TITLE
_simplify_include_frames throws bounds error

### ISSUE THREAD

**Issue by fredcallaway** [JuliaLang/julia#41566]
Original issue: https://github.com/JuliaLang/PackageCompiler.jl/issues/517

When using a sysimage, `_simplify_include_frames` throws a bounds error at line 804 because `i` is 0. 

https://github.com/JuliaLang/julia/blob/d7329038feb207997b9a6d969c5c8f11d37680d5/base/errorshow.jl#L804

The immediate fix is to move the decrement to the top of the loop and start at `i = length(trace) + 1`. I can make a pull request for this.

This still gives really verbose stack traces when using a sysimage. I'd like to take a shot at improving that as well, but perhaps this should be done in a separate issue/pull request since it might require further discussion.

Thanks to @KristofferC for identifying the problem.

**Comment by c42f** [comment]
Yes this is a bug, thanks for the report.

> I can make a pull request for this.

Perfect, please do. Two separate PRs seems fine.

Looking back at this code, I'm not sure why I wrote it as a `while` loop!  It looks like it could be a for loop and you can just use `kept_frames[1:first_ignored] .= false` after the loop as it doesn't terminate early?

**Comment by fredcallaway** [comment]
Sorry, quick question: Is there a standard way to develop/test Base code (ideally using Revise.jl)? Normally I would do e.g. `] dev Base` but that doesn't work. Didn't see anything about this in dev docs, but might have missed it.

**Comment by c42f** [comment]
TBH I haven't done this for a while. But you should be able to build Julia from source and use `Revise.track(Base)` to update Base while you edit the source (see https://timholy.github.io/Revise.jl/stable/#What-Revise-can-track-1)
