### ISSUE TITLE
Autocomplete error in REPL with `@Module.macro` syntax in 1.6.1

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#41569]
See screenshon; I got the error after hitting 'tab' after `@Threads.n`.
![Screenshot from 2021-07-13 10-38-15](https://user-images.githubusercontent.com/987837/125500013-ed16a89e-212e-4f9a-ac69-0a31c770cbf0.png)

**Comment by KristofferC** [comment]
This might have been fixed on 1.7. Could you try with the 1.7 beta?

**Comment by malmaud** [comment]
Ah ya, it does work in 1.7 beta 3. I'll close this.
