### ISSUE TITLE
Reimplement Git using libgit2

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#4158]
Right now, when a large number of packages are installed, updating is sloooowww.  The bottleneck seems to be the frequent calls to git.  It would be nice if Git were reimplemented using libgit2 (http://libgit2.github.com/, source at https://github.com/libgit2/libgit2).

The only possible issue concerns licensing: libgit2 is a GPL2, with a linking exception that states:

> In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to link the compiled
 version of this library into combinations with other programs,
 and to distribute those combinations without any restriction
 coming from the use of this file.

See: https://github.com/libgit2/libgit2/blob/development/COPYING

Is this permissive enough to include with Julia?

cc: @StefanKarpinski

**Comment by tkelman** [comment]
closing, being implemented by #11196
