### ISSUE TITLE
A *(foo, bar) B was deprecated

### ISSUE THREAD

**Issue by Wimmerer** [JuliaLang/julia#41588]
The paper Novel Algebras for Advanced Analytics in Julia makes use of the syntax `A *(foo, bar) B`. It looks like this was deprecated at some point.

Is it possible for this syntax to make a return?

**Comment by mbauman** [comment]
I don't believe this ever worked; the Julia syntax in that paper is `*(foo, bar)(A, B)` (nb distinct from LaTeX math).  General infix syntax for `A f B` is #16985; supporting `A f() B` is a further case of that issue.

**Comment by Wimmerer** [comment]
@mbauman @ViralBShah disagrees. The paper http://math.mit.edu/~edelman/publications/novel_algebras.pdf explicitly references the capability. I am aware of the previous issue, but I have my doubts about any of the proposals there being implemented in the near future.

**Comment by Wimmerer** [comment]
Specifically this line https://github.com/JuliaComputing/SemiringAlgebra.jl/blob/9852149c4c09a343c63bf073f6f00a62a9a997ef/src/SemiringAlgebra.jl#L37

**Comment by ViralBShah** [comment]
There was a funny infix version that did work back then, but this was all pre 1.0.

**Comment by ViralBShah** [comment]
You had to do `A *(max,+)B` IIRC, and looking at the paper. The missing space was the key back then.

**Comment by Wimmerer** [comment]
Ah the space. It parses to multiplication by juxtaposition now or something to that effect if you don't have the second space.

**Comment by mbauman** [comment]
Even in Julia 0.1.2 (Mar 7, 2013) this parsed the way it does today:

```julia
julia> VERSION
v"0.1.2+113667293.r7252"

julia> :(A *(max,+)B)
:(*(A,*((max,+),B)))

julia> :(A *(max,+) B)
ERROR: syntax: missing separator in tuple
```

This predates me, and yes, I now see it in that figure caption, but I'd _still_ be surprised if this ever worked (without some crazy `*(::Tuple{Function, Function}, ::Matrix)` lazy thing).

**Comment by ViralBShah** [comment]
I distinctly remember Alan showing that it works. There were no other hacks. I am now curious and will try to dig this up.

**Comment by ViralBShah** [comment]
In any case, just to be clear, this is only of historical interest. I am not proposing reopening the issue.
