### ISSUE TITLE
don't apply `@fastmath` to inlined function bodies

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#41582]
As discussed [on discourse](https://discourse.julialang.org/t/whats-going-on-with-exp-and-math-mode-fast/64619/11?u=stevengj), the fast that `@fastmath` applies even to inlined functions like `exp(x)` can lead to very surprising results and makes the macro extremely difficult to use.

It's basically impossible to reason about the floating-point behavior of code that you can't even see (because it was inlined from elsewhere).   Can we not propagate `@fastmath` to inlined code?

cc @KristofferC @oscardssmith

**Comment by KristofferC** [comment]
I don't think `@fastmath` applies to inline code. It just rewrites e.g `exp` to `exp_fast` and then you have the option of overloading `exp_fast`.

**Comment by vtjnash** [comment]
I don't think it does? The discourse post seems to be running with `--math-mode=fast`, and then complaining that it is running too fast by getting worse answers–which is exactly the definition of "fast" (however badly named that is, it is a legacy name from older compilers)

**Comment by stevengj** [comment]
Oh, I misread the thread — you're right, `@fastmath` is not a problem here.
