### ISSUE TITLE
BigInt code hangs with larger numbers

### ISSUE THREAD

**Issue by nhabedi** [JuliaLang/julia#41621]
The following code was written for my personal amusement and is probably not very clever, but I'm hoping that it is legal Julia code.  The idea is to generate the Collatz sequence with FRACTRAN:

    using Base.Iterators
    collatzSeq = [1//7, 104//33, 2//11, 11//13, 38//153, 1//17, 17//19, 63//4, 33//2, 17//1];
    intLog(n,m) = n==1 ? 0 : n%m == 0 ? 1+intLog(n÷m,m) : -Inf
    next(n,L) = (seq = dropwhile(!isinteger, (n*f for f in L)); isempty(seq) ? nothing : first(seq))
    struct fracProg
        prog::Array{Rational{BigInt},1}
        mem::BigInt
    end
    Base.iterate(f::fracProg, s=-1) = (n = next(s > 0 ? s : f.mem,f.prog); isnothing(n) ? nothing : (n,n))
    Base.IteratorSize(fracProg) = Base.SizeUnknown()
    collatz(s,n) = collect(take(Iterators.filter(x->x>0,(intLog(i,2) for i in fracProg(collatzSeq,2^s))),n))

With `collatz(10,10)` or `collatz(20,5)` it works as expected, but with `collatz(63,5)` it simply hangs and I get no response.  I see this behavior with Julia 1.4 on Linux and with Julia 1.5 on Windows - see below.  I suspect this is has to do with `BigInt` and memory allocation due to `collect`, but I'm not an expert.  FWIW, similar code in Python runs fine and in no time.

    Julia Version 1.5.0
    Commit 96786e22cc (2020-08-01 23:44 UTC)
    Platform Info:
      OS: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

    Julia Version 1.4.0
    Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
    Platform Info:
      OS: Linux (x86_64-pc-linux-gnu)
      CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
      WORD_SIZE: 64
      LIBM: libopenlibm
      LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
    Environment:
      JULIA_DEPOT_PATH = /opt/julia
      JULIA_PKGDIR = /opt/julia
      JULIA_VERSION = 1.4.0

**Comment by sostock** [comment]
FYI, `collatz(big(63), 5)` works without problems. The difference is that `2^63 == -9223372036854775808` (`Int` overflows) while `2^big(63) == 9223372036854775808` (`BigInt` doesn’t overflow).

**Comment by sostock** [comment]
For negative `mem`, iterating `fracProg` produces the same value forever, in this case `big(2^63) * 63//4`:
```julia
julia> collect(take(fracProg(collatzSeq, -9223372036854775808), 5))
5-element Vector{Any}:
 -145268109580462718976//1
 -145268109580462718976//1
 -145268109580462718976//1
 -145268109580462718976//1
 -145268109580462718976//1
```
And `intLog(-145268109580462718976//1, 2) == -Inf`, so you iterate forever, always getting `-Inf` and never getting a positive value to collect.

The code seems to work correctly, it just iterates forever because `(intLog(i,2) for i in fracProg(collatzSeq, -9223372036854775808))` never produces a positive number to collect.

To me, this does not seem to be a bug, but rather a program that works as expected (it iterates forever and discards all the values), so I am closing this issue. Feel free to reopen it if you think I have misunderstood something.

**Comment by nhabedi** [comment]
Thanks!  And sorry for the noise.  In translating prototype code from Common Lisp or Python I always seem to forget that promotion from Int to BigInt isn't automatic in Julia... :(

**Comment by PallHaraldsson** [comment]
For you it might be good to know of:

https://github.com/rfourquet/SafeREPL.jl

https://github.com/JeffreySarnoff/SaferIntegers.jl

then you would have found out:

>FYI, collatz(big(63), 5) works without problems

and seen you could rather do:

```
collatz(s,n) = collect(take(Iterators.filter(x->x>0,(intLog(i,2) for i in fracProg(collatzSeq,2^big(s)))), big(n)))
```

**Comment by nhabedi** [comment]
Ah, good to know!  I wasn't aware of these packages.
