### ISSUE TITLE
TestLogger does not respect `maxlog`

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#41625]
The `TestLogger` (defined in https://github.com/JuliaLang/julia/blob/master/stdlib/Test/src/logging.jl) does not take into account the `maxlog` parameter when logging. Loggers do not have to respect the parameter, but (most of?) the built-in ones do, and the fact that TestLogger does not makes it hard to check correct usage of `_id` and `maxlog` in tests. This came up in https://github.com/JuliaData/Arrow.jl/pull/225 where we want to log a warning once for each type that Arrow.jl did not understand.

**Comment by timholy** [comment]
Demo:
```julia
julia> erronce() = @error "an error" maxlog=1
erronce (generic function with 1 method)

julia> erronce()
┌ Error: an error
└ @ Main REPL[1]:1

julia> erronce()

julia> erronce() = @error "an error" maxlog=1
erronce (generic function with 1 method)

julia> using Test

julia> @test_logs (:error, "an error") erronce()

julia> @test_logs (:error, "an error") erronce()

julia> erronce()
┌ Error: an error
└ @ Main REPL[2]:1

julia> erronce()
```
