### ISSUE TITLE
Performance regression with tuple tail recursion in v1.7

### ISSUE THREAD

**Issue by jfeist** [JuliaLang/julia#41637]
I noticed a quite significant performance regression in tuple tail recursion from julia 1.6 to 1.7. Version 1.6 already had a regression for a specific case compared to 1.5, but in 1.7 it's even worse, and shows up for all the cases I checked. Full details in this thread: https://discourse.julialang.org/t/strange-performance-characteristics-and-regression-with-tuple-recursion/64888/2

**Comment by KristofferC** [comment]
Running a `git bisect` might be a good way to find the place where it regressed.

**Comment by simeonschaub** [comment]
Ref #40814. I suspect c2ec70c is the culprit here as well.

**Comment by vtjnash** [comment]
Seems to be an LLVM optimization prediction heuristic that we cannot really guarantee. But seems to do well at M=2 again
```
M = 1:   2.729 ns (0 allocations: 0 bytes)
M = 2:   68.319 ns (0 allocations: 0 bytes)
M = 3:   7.410 μs (0 allocations: 0 bytes)
M = 4:   173.518 μs (0 allocations: 0 bytes)
```
