### ISSUE TITLE
tidy up dump and xdump

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#4163]
These functions have become a basket of odd behaviors, and their implementation is quite complex.

There are differences like this:

```
julia> dump(Int)
Int64

julia> xdump(Int)
Int64::DataType  <: Signed
```

Then there is this:

```
julia> dump(1+2im)
Complex{Int64} 
  re: Int64 1
  im: Int64 2

julia> dump((1+2im,{}))
(Complex{Int64},Array{Any,1}) (1 + 2im,{})
```

The first output was fine, but put it inside a tuple and something else happens.

Also `xdump` is not documented. If the current behavior does actually make sense, then the task here is to explain it by documenting `dump` and `xdump` better.

But I propose that we should only have `dump`, and it should simply traverse a structure and show everything about it.

**Comment by StefanKarpinski** [comment]
Solution could be as simple as deleting `xdump` and deprecating it in favor of `dump`. If anyone complains we can fix up various broken corner cases in `dump`.

**Comment by ScottPJones** [comment]
But would the `dump` behave as `xdump` currently does (which seems to supply more information)?
I might take care of this, if nobody else does, since I was just in this code yesterday (#12072) fixing a bug.

**Comment by StefanKarpinski** [comment]
There should only be one and it should give you all of the information in a somewhat readable form. Currently sometimes `dump` gives you the information you need while sometimes `xdump` does. The only way to know seems to be trying it out. It would be great if you fixe that. I suspect no one really depends on this output format, so feel free to change and improve it as you see fit.

**Comment by ScottPJones** [comment]
Ok, thanks!  I've been using dump and xdump a lot lately, so I'll try to come up with something to everybody's satisfaction.

**Comment by mauro3** [comment]
Buggy with function arguments (similar on jb/functions):
```
julia> xdump(x->x)
ERROR: ArgumentError: invalid arguments to xdump
 in xdump at show.jl:936

julia> dump(x->x)
(anonymous function)

julia> f(x)=1
f (generic function with 1 method)

julia> xdump(f)
ERROR: ArgumentError: invalid arguments to xdump
 in xdump at show.jl:936

julia> dump(f)
f
```

**Comment by pkofod** [comment]
on master `Version 0.5.0-dev+2750 (2016-02-19 04:59 UTC)`
```julia
julia> dump(x->x)
#1
julia> dump(x->x)
#3
julia> dump(x->x)
#5
```
Is this supposed to say `anonymous function` as above?
