### ISSUE TITLE
Document magic numbers in Printf for Floats

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#41649]
For Ints and Chars (in the code above the one I link) it's somewhat more straightforward what the numbers mean and why they're chosen, but for Floats it's kind of guesswork unless you already know what they mean. This came up while investigating #41631

https://github.com/JuliaLang/julia/blob/6279f3b8c4a7e7a669cc7222642ae20824292855/stdlib/Printf/src/Printf.jl#L779-L782

**Comment by Seelengrab** [comment]
Just thought of looking at `git blame` for who to best ask about this, seems @quinnj may know?

**Comment by quinnj** [comment]
Hmmm, I'm not sure I quite remember where those exact numbers came from; roughly it's the total number of significant digits we're willing to print/allow for precision for floats.
