### ISSUE TITLE
Cannot define `isempty` in Main

### ISSUE THREAD

**Issue by bicycle1885** [JuliaLang/julia#41656]
I found a confusing behavior when I tried to define a function named `isempty` in the `Main` module:
```
julia> isempty(x) = true
ERROR: error in method definition: function Base.isempty must be explicitly imported to be extended
Stacktrace:
 [1] top-level scope
   @ none:0
 [2] top-level scope
   @ REPL[1]:1
```

**Comment by KristofferC** [comment]
Probably from https://github.com/JuliaLang/julia/blob/d26dc9e8f79d344c7f457b7f00540fc24264fbaa/contrib/generate_precompile.jl#L3

**Comment by StefanKarpinski** [comment]
Would it make sense to wrap that whole logic in an anonymous module instead? Prefixing everything with base seems annoying.

**Comment by KristofferC** [comment]
Most of it is already in an anonymous function so https://github.com/JuliaLang/julia/blob/d26dc9e8f79d344c7f457b7f00540fc24264fbaa/contrib/generate_precompile.jl#L6 could probably just be moved up a few lines as well.
