### ISSUE TITLE
loops inhibit constant prop

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#41694]
Minimal example:
```julia
julia> function fact(x)
           res = 1
           while x > 1
               res *= x
               x -= 1
           end
           return res
       end
fact (generic function with 1 method)

julia> code_typed() do
           fact(1)
       end
1-element Vector{Any}:
 CodeInfo(
1 ─     return 1
) => Int64

julia> code_typed() do
           fact(2)
       end
1-element Vector{Any}:
 CodeInfo(
1 ─      nothing::Nothing
2 ┄ %2 = φ (#1 => 1, #3 => %6)::Int64
│   %3 = φ (#1 => 2, #3 => %7)::Int64
│   %4 = Base.slt_int(1, %3)::Bool
└──      goto #4 if not %4
3 ─ %6 = Base.mul_int(%2, %3)::Int64
│   %7 = Base.sub_int(%3, 1)::Int64
└──      goto #2
4 ─      goto #5
5 ─      return %2
) => Int64
```

**Comment by jakobnissen** [comment]
Could be the cause of https://github.com/JuliaLang/julia/issues/30126 ?

**Comment by simeonschaub** [comment]
Yes, most likely.

**Comment by Keno** [comment]
Probably the easiest way to make this happen would be to have inference realize that the function is pure and be able to run it at inference time as a result. We don't do that currently and it also intersects with #40009.

**Comment by aviatesk** [comment]
As a short-term solution `@assume_effects` provides a way to constant fold function call with a loop.

**Comment by KristofferC** [comment]
Is that really enough to consider this issue properly fixed?

**Comment by aviatesk** [comment]
I think constant folding of loop with automatic termination proof can be achieved as a general long-term compiler objective along with other loop optimizations like loop unrolling and such (, which will require some tough work). I think `Base.@assume_effects` is very enough for this specific problem though.
