### ISSUE TITLE
When Julia doesn't recognize long file name.

### ISSUE THREAD

**Issue by andyname** [JuliaLang/julia#41735]
Hello.
I've made file storage system by Julia. It is to save DataFrame format as a file. It's being saved through Serialize. However, Serialize makes an error when the file name is long.  I think save and load sytem of JuliaDB has same problem. Long file name error. Here is an example. I'm using Julia 1.5.4 and 1.6.2 on windows 10.

```
#############
using Serialization

df=DataFrame(c1=[5,6,7])

folderName="C:\\ChamGo\\ADGOIMMUGYUL2_2_OIL_STS_SL01_WONCHEON\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000"

mkpath(folderName)

fileName="C:\\ChamGo\\ADGOIMMUGYUL2_2_OIL_STS_SL01_WONCHEON\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000.jls"

serialize(fileName,df)   ## It makes an error.

#############

fileName="C:\\ChamGo\\shortName.jls"

serialize(fileName,df)   ## It's not.
```

**Comment by barucden** [comment]
I suspect this is not an issue with Julia, but with Windows. Have you tried to create the file manually (e.g., from command line)? Did it work?

Windows defines [the maximum length of a path](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd) and it is 260 characters. It should be possible to [remove this limitation on Windows 10](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later).

**Comment by andyname** [comment]
I've made a path on windows 10 manually by GUI interface and CMD as well. It works. 

C:\> mkdir C:\ChamGo1\ADGOIMMUGYUL2_2_OIL_STS_SL01_WONCHEON\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000

What I have tried.

**Comment by barucden** [comment]
This path has only 208 characters. The one that you included in the original code snippet had 264 (exceeding the windows limitation). 
Try:
```cmd
mkdir C:\ChamGo1\ADGOIMMUGYUL2_2_OIL_STS_SL01_WONCHEON\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000
\WON_IDv1v36869vEPOCHMSv63602211600000v63602985600000jls
```

**Comment by Seelengrab** [comment]
Related to #39774 - maximum allowable file name length is system dependent. 

You seem to be on windows, which limits path lengths to 260 characters (see [here](https://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista) and [here](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd) for more info).

**Comment by andyname** [comment]
Thank you Guys! I've solved this problem. It was not a Julia issue. It was Windows. I've followed the links that you give to me, so I could edit registry. Now my Julia system recognize long file name.
