### ISSUE TITLE
overflow?

### ISSUE THREAD

**Issue by unhandyandy** [JuliaLang/julia#41747]
I'm running Julia 1.6.2 and got this:
```
julia> 2^63
-9223372036854775808
```
Shouldn't this produce `Inf` or an overflow error instead?

**Comment by Seelengrab** [comment]
No, `Int` has defined wraparound behavior and doesn't automatically convert to `Float64`.

See [Integers and floating point numbers - Overflow behavior](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior) from the docs.

**Comment by unhandyandy** [comment]
OK, but this is not end-user friendly behavior.  Julia is targeted at nonprogrammers who won't necessarily be familiar with "wraparound behavior".  This is the kind of bug that could go unnoticed for a while.

**Comment by Seelengrab** [comment]
This has been a part of julia for a number of years now and is extremely unlikely to (dare I say "won't"?) change (even in a potential 2.0 release, which would allow breakage). If you'd like to discuss why this choice was made, that's fine, but please note that an issue is not necessarily the best place for this. Instead, consider opening a thread on [discourse](https://discourse.julialang.org) inquiring into the design choices behind this behaviour.

Also, please note that [Julia is not at "that" stage of development anymore.](https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872)

**Comment by unhandyandy** [comment]
OK, thanks.

**Comment by StefanKarpinski** [comment]
There's also an FAQ entry about this: https://docs.julialang.org/en/v1/manual/faq/#faq-integer-arithmetic

**Comment by unhandyandy** [comment]
Ah, thanks, that explains a lot
