### ISSUE TITLE
Download URL not working.

### ISSUE THREAD

**Issue by jayanthbagare** [JuliaLang/julia#41765]
Hi,
I've tried to download from the Download URL
https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.2-linux-x86_64.tar.gz

It doesn't seem to be working.
Could you please check if the S3 bucket is still valid?

Warm Regards,
Jayanth

**Comment by cc13ny** [comment]
It's working now, at least for me.

**Comment by jayanthbagare** [comment]
working now thanks

**Comment by jayanthbagare** [comment]
Works now
