### ISSUE TITLE
`in(x, ::StepRangeLen)` fails when step is zero

### ISSUE THREAD

**Issue by barucden** [JuliaLang/julia#41784]
Working on #41769, I found an error:

```julia
julia> r = StepRangeLen(3, 0, 5)
StepRangeLen(3, 0, 5)

julia> 3 in r
ERROR: DivideError: integer division error
Stacktrace:
 [1] div
   @ ./int.jl:278 [inlined]
 [2] div
   @ ./div.jl:257 [inlined]
 [3] div
   @ ./div.jl:302 [inlined]
 [4] fld
   @ ./div.jl:268 [inlined]
 [5] mod
   @ ./int.jl:270 [inlined]
 [6] in(x::Int64, r::StepRangeLen{Int64, Int64, Int64, Int64})
   @ Base ./range.jl:1346
 [7] top-level scope
   @ REPL[23]:1
```
This is because 3 is inside the range, and `step(r) == 0` makes `mod` on [this line](https://github.com/JuliaLang/julia/blob/master/base/range.jl#L1338) fail.

*Slightly* related is #41402, which deals with a completely different problem, but eventually sees division error in `mod`. Perhaps `mod` should check the modulo and throw a better error too?

**Comment by martinholters** [comment]
Just inserting a `step(r) == 0` before the call to `mod` should do the trick. Similar for the `AbstractChar` method (`'a' in StepRangeLen('a', 0, 5)` fails, too.)

**Comment by mohilkhare1708** [comment]
I would like to work on this issue, kindly assign me this.

**Comment by mohilkhare1708** [comment]
@martinholters I would like to work on this issue, kindly assign me this.

**Comment by martinholters** [comment]
Just go ahead, no assignment needed.
