### ISSUE TITLE
Provide entry point for color customization

### ISSUE THREAD

**Issue by Arkoniak** [JuliaLang/julia#41791]
Julia uses hardcoded colors for generating output (for example stacktraces) and unfortunately color choice is not always suitable for all users for various reasons.

I propose to use the following approach instead of colors hardcoding:

```julia
# define somewhere at the beginning

const COLOR = Ref((; foo = :red, bar = :green))

# and later in the code, when color is needed
printstyled("what you need to print", COLOR[].foo)
```

This simple change does not provide full-fledged color theme switching by itself (this probably should be implemented JuliaLang/julia#41435), but it provides an entry point for all future color theme related stuff. I.e. all user level convenience functions would just modify this variable one way or another. And anyway this proposal allows color customization right here and now (maybe slightly cumbersome) unlike the current situation.

Implementing this feature looks like a good beginner PR, doesn't require large modifications of the code base and it solves color issues.

**Comment by simeonschaub** [comment]
Is that different from the current mechanism where you can modify `Base.text_colors`? E.g. the following already works:

```
julia> Base.text_colors[:red] = Base.text_colors[:blue]
"\e[34m"

julia> printstyled("Foobar"; color=:red) # displays as blue
Foobar
```

**Comment by KristofferC** [comment]
Could be discussed in https://github.com/JuliaLang/julia/issues/41435?

**Comment by Arkoniak** [comment]
Yes it could, but this proposal can be implemented before #41435 is fully resolved. As far as I understand #41435 is mostly about proper way of defining configuration, like TOML format and whether to use hex colors or meaningful names. But at some point somebody have to go through the code base and change all hardcoded values to config references. This proposal can be considered as low-level implementation config-agnostic detail.  You can have any config setup you want and translate it to `COLOR` variable at some point.

**Comment by Arkoniak** [comment]
> Is that different from the current mechanism where you can modify `Base.text_colors`? E.g. the following already works:
> 
> ```
> julia> Base.text_colors[:red] = Base.text_colors[:blue]
> "\e[34m"
> 
> julia> printstyled("Foobar"; color=:red) # displays as blue
> Foobar
> ```

No, it is not the same. Changing `Base.text_color` affects all colors everywhere. It may not always be the case, though. For example it could be possible that the user wants to change the red color in some random message (if he does not think that in this particular message red color should be used), but he still may need red color in error message.

**Comment by KristofferC** [comment]
What we have now is https://docs.julialang.org/en/v1/manual/environment-variables/#REPL-formatting.
