### ISSUE TITLE
Strange or wrong float number computing results

### ISSUE THREAD

**Issue by craiklee** [JuliaLang/julia#41818]
For some float number computing, julia will give strange results. 

julia> 8.2*100
819.9999999999999

julia> 9.2*100
919.9999999999999

julia> 10.2*100
1019.9999999999999

julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client)

**Comment by Seelengrab** [comment]
https://0.30000000000000004.com

**Comment by Seelengrab** [comment]
This is how floating point works, `8.2` is not exactly representable by Float64:

```
julia> big"8.2"                                                                 
8.199999999999999999999999999999999999999999999999999999999999999999999999999972
```

See also https://0.30000000000000004.com

**Comment by craiklee** [comment]
But many other numbers are OK, such as:

julia> 6.2*100
620.0

julia> 7.2*100
720.0

julia> 11.2*100
1120.0

julia> big"7.2"
7.199999999999999999999999999999999999999999999999999999999999999999999999999972

julia> big"6.2"
6.199999999999999999999999999999999999999999999999999999999999999999999999999972

julia> big"11.2"
11.19999999999999999999999999999999999999999999999999999999999999999999999999997

**Comment by craiklee** [comment]
> This is how floating point works, `8.2`, `9.2` and `10.2` are not exactly representable by Float64:
> 
> ```
> julia> big"8.2"                                                                 
> 8.199999999999999999999999999999999999999999999999999999999999999999999999999972
>                                                                                 
> julia> big"9.2"                                                                 
> 9.199999999999999999999999999999999999999999999999999999999999999999999999999972
>                                                                                 
> julia> big"10.2"                                                                
> 10.19999999999999999999999999999999999999999999999999999999999999999999999999997
> ```
> 
> See also https://0.30000000000000004.com for more information.

But many other numbers are OK, such as:

julia> 6.2*100
620.0

julia> 7.2*100
720.0

julia> 11.2*100
1120.0

julia> big"7.2"
7.199999999999999999999999999999999999999999999999999999999999999999999999999972

julia> big"6.2"
6.199999999999999999999999999999999999999999999999999999999999999999999999999972

julia> big"11.2"
11.19999999999999999999999999999999999999999999999999999999999999999999999999997

**Comment by kimikage** [comment]
Perhaps `big"8.2"` was intended to be `big(8.2)`.
```julia
julia> big(8.2) - big"8.2"
-7.105427357601001858711242675781249999999999999999999999999999723642606236977772e-16

julia> big(7.2) - big"7.2"
1.776356839400250464677810668945312500000000000000000000000000276357393763022228e-16
```

**Comment by KristofferC** [comment]
See https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678
