### ISSUE TITLE
Garbled error/help messages in the REPL

### ISSUE THREAD

**Issue by lamorton** [JuliaLang/julia#41823]
I hit a weird bug where the `?` help output and error messages get delayed & chopped up.  I'm having trouble reproducing it, it cropped up in a long-running session so there's a ton happening, unfortunately.  But, it's not the first time it's happened, it cropped up once maybe a year ago.  It might be related to LaTexify or GR, because I had just started working with them in the session before it went bad, and I hadn't been using them in other sessions with the same environment & wasn't having this.

This is what it looks like. Messages from previous errors and help messages are getting chopped up and spit out later. 

<img width="1319" alt="Screen Shot 2021-08-07 at 7 07 45 PM" src="https://user-images.githubusercontent.com/23484003/128619113-68a1c765-fabe-4620-b637-0858a81b7acf.png">

This seems to be where it started:

<img width="1309" alt="Screen Shot 2021-08-07 at 7 25 03 PM" src="https://user-images.githubusercontent.com/23484003/128619051-906d499c-1109-427d-b549-845434250022.png">

Or maybe this:

<img width="1313" alt="Screen Shot 2021-08-07 at 7 23 34 PM" src="https://user-images.githubusercontent.com/23484003/128619222-7c788dcf-d6dd-4ce7-902a-008f39fcc8e1.png">

I can't put the full session log here b/c of length limits, but I saved it so I can upload it somewhere & link it here if there's interest.  

Packages potentially involved:
```julia
using DifferentialEquations, Plots, DiffEqFlux, Unitful, AxisArrays, HDF5, DataInterpolations, GridInterpolations, GalacticOptim, ModelingToolkit, Zygote, BlackBoxOptim, IfElse

(Julia) pkg> st
      Status `~/Code/Julia/Project.toml`
  [39de3d68] AxisArrays v0.4.4
  [a134a8b2] BlackBoxOptim v0.6.0
  [82cc6244] DataInterpolations v3.6.0
  [aae7a2af] DiffEqFlux v1.42.0
  [0c46a032] DifferentialEquations v6.18.0
  [587475ba] Flux v0.12.6
  [f6369f11] ForwardDiff v0.10.19
  [a75be94c] GalacticOptim v2.0.3
  [bb4c363b] GridInterpolations v1.1.2
  [f67ccb44] HDF5 v0.15.6
  [615f187c] IfElse v0.1.0
  [b964fa9f] LaTeXStrings v1.2.1
  [2ee39098] LabelledArrays v1.6.3
  [23fbe1c1] Latexify v0.15.6
  [961ee093] ModelingToolkit v5.26.0 `~/Code/Jdev/ModelingToolkit`
  [8913a72c] NonlinearSolve v0.3.8
  [429524aa] Optim v1.4.1
  [1dea7af3] OrdinaryDiffEq v5.60.2
  [a03496cd] PlotlyBase v0.8.4
  [91a5bcdd] Plots v1.19.4
  [438e738f] PyCall v1.92.3
  [d330b81b] PyPlot v2.9.0
  [0bca4576] SciMLBase v1.18.2
  [0c5d862f] Symbolics v1.4.2
  [1986cc42] Unitful v1.9.0
  [e88e6eb3] Zygote v0.6.17
  [700de1a5] ZygoteRules v0.2.1
```

My Julia version is 1.6.1.  I'm on Big Sur.  I'm working in VSCode 1.59 

I also have in my `startup.jl`:

```julia
using Pkg
using Revise
using Debugger
break_on(:error)
using AbstractTrees
```

**Comment by Seelengrab** [comment]
Possibly related/similar to https://github.com/timholy/Revise.jl/issues/195 and #30727?

**Comment by KristofferC** [comment]
This I need look like the revise bug. Feel free to open a new issue if you can get it to repro without revise.

**Comment by timholy** [comment]
...or in Revise if it's necessary.
