### ISSUE TITLE
Docstring for ';' does not cover all of it possible uses.

### ISSUE THREAD

**Issue by aramirezreyes** [JuliaLang/julia#41848]
Looking for ";" in the help REPL shows a docstring that describes its use as the end of statement and as output suppressor but it doesn't mention its use as a separator between positional and keyword arguments in function definitions and calls, nor about its role for building arrays or about its usage to access the shell REPL mode. 
This is the same in v1.6 and master (August 8 2021).

```
help?> ;
search: ;

  ;

  ; has a similar role in Julia as in many C-like languages, and is used to
  delimit the end of the previous statement. ; is not necessary after new
  lines, but can be used to separate statements on a single line or to join
  statements into a single expression. ; is also used to suppress output
  printing in the REPL and similar interfaces.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> function foo()
             x = "Hello, "; x *= "World!"
             return x
         end
  foo (generic function with 1 method)

  julia> bar() = (x = "Hello, Mars!"; return x)
  bar (generic function with 1 method)

  julia> foo();

  julia> bar()
  "Hello, Mars!" 
```

**Comment by annjc** [comment]
Hi, I'm interested in working on this issue. I'm new to open source contributions. Can you guide me a bit about what needs to be done? Should I add in the above mentioned uses of ';' with examples?

**Comment by Chandu-4444** [comment]
I think this issue can be closed? It might confuse someone like me looking for good first issues. Or if there's still something to do, I'll try to complete it.
