### ISSUE TITLE
copyto!(x,false) does not make x all zeros?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#41868]
```julia
x = rand(20)
x .= false # all zeros
x = rand(20)
copyto!(x,false) # not all zeros?
```

I would've assumed the two mutating operations would be the same.

**Comment by DilumAluthge** [comment]
>   Copy all elements from collection src to array dest, whose length must be greater than or equal to the length n of src. The first n elements of dest are overwritten, the other elements are left untouched.

I wonder if it is treating `false` as an "iterable collection" with length 1.

**Comment by ArchieCall** [comment]
copyto!(dest::AbstractArray, src) -> dest

  Copy all elements from collection src to array dest, whose length must be greater than or equal to the length n of
  src. The first n elements of dest are overwritten, the other elements are left untouched.

**Comment by KristofferC** [comment]
Yep, this is behaving as documented. `fill!` is what to use if you want to fill with a value.
