### ISSUE TITLE
Cpu feature detection issues M1 mac

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#41895]
Julia currently doesn't detect any cpu features when calling `Base.BinaryPlatforms.CPUID.cpu_isa` on an M1 mac. Julia isn't the only one if issues with runtime feature detection in the ARM-Apple space.
Go had this issue and has an implementation https://github.com/golang/go/issues/42747. 
I haven't checked, but reading the code we try to check the features via `getauxval()`, which isn't available on the darwin libc, and the fallback is a hardcoded name, which isn't available.

https://github.com/JuliaLang/julia/blob/a08a3ff1f957f6bd570ff5756dff4290eb6f43da/src/processor_arm.cpp#L1184-L1308

LLVM does use the features since it has a separate flag `-mcpu=apple-a12` so it isn't something very urgent.

Using something like https://developer.apple.com/documentation/kernel/1387446-sysctlbyname seems like an option in other not to hardcode it, for future apple silicon CPUs.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/40876

**Comment by gbaraldi** [comment]
I'm not that familiar, is this the same codepath for feature detection that LLVM uses for codegen?
