### ISSUE TITLE
Uninitialized `Union` field handling is inconsistent with `@atomic`

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#41940]
```julia
julia> mutable struct A{T}
           @atomic x::T
           A{T}() where {T} = new{T}()
       end

julia> mutable struct B{T}
           x::T
           B{T}() where {T} = new{T}()
       end

julia> A{Union{Nothing,Int}}()
A{Union{Nothing, Int64}}(#undef)

julia> B{Union{Nothing,Int}}()
B{Union{Nothing, Int64}}(nothing)
```

I think `#undef` for `A{Union{Nothing,Int}}()` is unexpected?

**Comment by vtjnash** [comment]
We formally state that the behavior of uninitialized fields is unspecified. There are certain types of values we will never invent (mutable objects, or objects of a different type), while we only permit it to create bitstypes out-of-thin-air. There is nothing that says these need to agree.

**Comment by tkf** [comment]
Thanks. It makes sense!
