### ISSUE TITLE
Add details on how search mode queries old commands

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#41969]
I just found out search mode exists: https://docs.julialang.org/en/v1/stdlib/REPL/#Search-modes, I think we should add some context as to how it queries old commands such that someone might have a better idea of if it will accomplish what they want.

Example: I just nuked my Julia 1.6 env but want to go back and find some old commands I ran. Will this work? Or is the history related to the env?

**Comment by vtjnash** [comment]
They are stored in `~/.julia/logs/repl_history.jl`. Seems like we don't mention `--history-file={yes,no}` there either?
