### ISSUE TITLE
IJulia not working in Julia 1.6.2

### ISSUE THREAD

**Issue by harneetslamba** [JuliaLang/julia#41981]
Unable to run Jupyter notebook with Julia 1.6.2

**Comment by logankilpatrick** [comment]
Hey, Please open an issue here: https://github.com/JuliaLang/IJulia.jl with as much detail as possible. What were you trying to do, why is it not able to run? Are you seeing an error message? Etc. 

Please ping me in the issue on IJulia and I will be. happy to take a look. Thanks again!
