### ISSUE TITLE
Different results with same data but different view types

### ISSUE THREAD

**Issue by JockLawrie** [JuliaLang/julia#41996]
Hi there,

I'm getting different results calculating a dot product using LinearAlgebra's `dot` function, depending on the _type_ of `view` that I use. Version info below, MWE below that.

```julia
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

In the MWE below I am selecting a row of one `Matrix` using a view, and a column of another matrix using another view, and taking their dot product. The issue surfaces when I:
1. Use a `Vector{Int}` as the column indices, and
2. Use the `dot` function from the `LinearAlgebra` stdlib package.

The MWE works fine if I use a `UnitRange{Int}` as column indices, or use a naive implementation of the dot function (see `mydot` in the MWE). Also, using a vector to select row indices doesn't cause any problems either.

Although the errors are small, O(10-16), they lead to errors of O(10-2) in some multinomial regression code I've written - see [here](https://github.com/JockLawrie/MultinomialRegression.jl/issues/3) for a reproducible example of the accumulated effect of this issue.

The MWE also shows that there input data is the same in each example (`row_error .== 0`), it is only the type of the view that makes a difference. Why does this happen? Can this be fixed?

```julia
function mydot(x, y)
    result = 0.0
    for i = 1:length(x)
        result += x[i] * y[i]
    end
    result
end

function test1(ntrials, dotfunc)
    row_error2 = Float64[]
    dot_error2 = Float64[]
    row_error3 = Float64[]
    dot_error3 = Float64[]
    for i = 1:ntrials
        # Parameter matrix
        B = rand(5, 2)

        # Data
        X  = reshape(rand(20), 4, 5)
        X2 = view(X, :, 1:5)
        X3 = view(X, :, [1,2,3,4,5])  # Problem seems to arise here

        # 2nd row of data
        r  = view(X,  2, :)
        r2 = view(X2, 2, :)
        r3 = view(X3, 2, :)

        # Calculate result = dot(Xrow2, Bcol2)
        col = view(B, :, 2)
        d   = dotfunc(r, col)
        d2  = dotfunc(r2, col)
        d3  = dotfunc(r3, col)

        # Collect errors if they exist
        if d2 != d
            push!(row_error2, sum(abs.(r2 .- r)))
            push!(dot_error2, abs(d2 - d))
        end
        if d3 != d
            push!(row_error3, sum(abs.(r3 .- r)))
            push!(dot_error3, abs(d3 - d))
        end
    end
    row_error2, dot_error2, row_error3, dot_error3
end

using LinearAlgebra

test1(100, mydot)  # ok
test1(100, dot)  # small numerical errors some of the time
```

**Comment by JockLawrie** [comment]
A simpler MWE below.


```julia
using LinearAlgebra

X  = reshape(rand(20), 4, 5);
X2 = view(X, :, 1:5);
X3 = view(X, :, [1,2,3,4,5]);
Y  = reshape(rand(20), 5, 4);
X * Y == X2 * Y  # ok
X * Y .- X3 * Y  # not ok
```

**Comment by Seelengrab** [comment]
Since the error is on the order of `10e-16` (or about `eps(Float64)`), my guess would be that these are "normal" floating point shenanigans having to do with being able to SIMD or not etc. I think this is "caused" by the multiplication of `X3 * Y` having to fall back to the generic matmul implementation due to now knowing statically that the columns from the given vector will be continous, whereas the other multiplications are both dispatched to BLAS. You can follow the callstack along with

```
julia> using Debugger

julia> @enter *(X2, Y)   # or *(X,Y) or *(X3,Y)
```

I admit though that I haven't investigated deeper than this - I don't think exact binary reproducibility of the generic matmul with any given BLAS is the goal though, especially since it's quite likely that different BLAS will produce different numerical errors here. Could be that this is a bug in our generic matmul, though I doubt it.

**Comment by vtjnash** [comment]
Sounds like it. You could also check the condition number with `cond(X)` to see if it looks the the answer may be particularly numerically unstable, but this sounds like it is within the expected error bounds of the computation.
