### ISSUE TITLE
`⊼` and `⊽` can't be used in `⊼=`/`⊽=`

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#42037]
I think this was just missed as part of the infix expansions, or is there a reason these don't allow for their setindex variant? Looks like a parser failure to me.

MWE:

```julia
julia> a = [1]               
1-element Vector{Int64}:     
 1                           
                             
julia> a[1] ⊽= 2             
ERROR: syntax: unexpected "="
Stacktrace:                  
 [1] top-level scope         
   @ none:1                  
                             
julia> a[1] ⊼= 2             
ERROR: syntax: unexpected "="
Stacktrace:                  
 [1] top-level scope         
   @ none:1                  
```

**Comment by GregPlowman** [comment]
Ref #15964

**Comment by Seelengrab** [comment]
Ah. Well, this is a duplicate then. Thanks for the reference! Looks like this takes more work though.. Maybe I should get on that [pika](https://arxiv.org/abs/2005.06444) julia parser I keep wanting to write..
