### ISSUE TITLE
`T >: Missing` no longer stylish

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#42048]
[I wanted to be stylish](https://youtu.be/TPuJsgyu87U?t=846) as suggested by @JeffBezanson, but I can't anymore (was I ever even able to be?). I've checked this on both 1.7 and 1.6.1. I don't really know how to title this better - maybe "Can't dispatch properly on `Type{>:Missing}`"?

```julia
julia> Type{>:Missing} == Type{Union{T,Missing}} where T          
true                                                              
                                                                  
julia> g(t::Type{T}) where T >: Missing = println("dispatch: $t") 
g (generic function with 1 method)                                
                                                                  
julia> g(Missing)                                                 
dispatch: Missing                                                 
                                                                  
julia> g(Int)                                                     
ERROR: MethodError: no method matching g(::Type{Int64})           
Closest candidates are:                                           
  g(::Type{T}) where T>:Missing at REPL[2]:1                      
Stacktrace:                                                       
 [1] top-level scope                                              
   @ REPL[4]:1                                                    
                                                                  
julia> g(Any)                                                     
dispatch: Any                                                     
                                                                  
julia> g(t::Type{Union{T,Missing}}) where T = println("union: $t")
g (generic function with 1 method)                                
                                                                  
julia> methods(g)                                                 
# 1 method for generic function "g":                              
[1] g(t::Type{Union{Missing, T}}) where T in Main at REPL[6]:1    
                                                                  
julia> g(Int)                                                     
ERROR: MethodError: no method matching g(::Type{Int64})           
Closest candidates are:                                           
  g(::Type{Union{Missing, T}}) where T at REPL[6]:1               
Stacktrace:                                                       
 [1] top-level scope                                              
   @ REPL[8]:1                                                    
                                                                  
julia> g(Any)                                                     
union: Any                                                        
                                                                  
julia> g(Missing)                                                 
union: Missing                                                    

julia> Type{Missing} <: Type{>:Missing}
true                                   
                                       
julia> Type{Int} <: Type{>:Missing}    
false                                  
                                       
julia> Type{Any} <: Type{>:Missing}    
true                                   
```

Not sure if this is even useful, just played around a little with old talks :) If it's just noise, feel free to close.

**Comment by vtjnash** [comment]
What is the question? You seemed to show the two types are equal, and thus have the same dispatch for your examples

**Comment by Seelengrab** [comment]
The question, if you can call it that, was that `T >: Missing` was at some point (or at least during that talk by jeff) understood to be the same as being able to dispatch on `Union{T, Missing}`, but written more stylish. Maybe that was always wrong though, I don't know - in effect, I'm kind of confused why this was showcased at all, it's not a really useful thing if it just collapses to "we have a way to dispatch to anything and `Any`, but nothing else! It certainly doesn't behave the same as directly dispatching `Union{T, Missing}`, as was mentioned in the video.

Or maybe the example is nonsensical either way and this is just noise - if that's the case, feel free to close! I guess I just wanted to know whether this behavior was what jeff meant all along or not.

**Comment by vtjnash** [comment]
I am confused. You don't have any example of calling it with `g(Union{Int,Missing})`, except for `Any`, which worked as told. And you are showing them as dispatching the same way.

**Comment by Seelengrab** [comment]
Yes, they're dispatching the same, I'm confused by what jeff said in the talk originally. He seems to be implying that it was meant to accept anything at all ("some type T greater than `Missing`, which is just anything, even `Any`"). So from that POV, it would seem this doesn't behave as intended though it is consistent (and indeed would be very stylish for documentation purposes).

I guess having something like 

```
function f(t::Type{T}) where T >: Missing
      Vector{t}(undef, 5)
end
```

and returning a `Vector{Union{Missing, T}` (for given values of `T`) was the idea behind that? Not too sure this even makes sense though, given the type bounds vanish inside the function 🤷‍♂️

---

A curious sideeffect of this is `T >: Any`, which will _only_ accept literal `Any` (as e.g. obtained by `eltype(Any[1,2,3])`). An easy way to detect unwanted `Any` typed containers for code analysis tools?

**Comment by martinholters** [comment]
I'm not sure what the confusion is, exactly, but maybe it becomes a bit clearer if not used with `Type`, e.g.
```julia
foo(v::Vector) = ... # general implementation, cannot handle missings
foo(v::Vector{>:Missing}) = ... # special handling of missings
```
The latter could also be written
```julia
foo(v::Vector{Union{T, Missing}}) where T = ... # special handling of missings
```
but that would be less stylish.

---

> A curious sideeffect of this is T >: Any, which will only accept literal Any (as e.g. obtained by eltype(Any[1,2,3])). 

Not sure what you're getting at here, but `>:Any` should be equal to just `Any` (as opposed to `<:Any`).

**Comment by Seelengrab** [comment]
Thanks, that cleared up my confusion!

The only thing left is why the first method is considered more specific here:

```
julia> f(v::Vector{>:Missing}) = sum(skipmissing(v))
f (generic function with 1 method)                  
                                                    
julia> f(v::Vector{T}) where T = sum(v)             
f (generic function with 2 methods)                 
                                                    
julia> methods(f, (typeof(Any[1,2,3]),))            
# 1 method for generic function "f":                
[1] f(v::Vector{>:Missing}) in Main at REPL[1]:1    
``` 

Is it because the type bound is tighter, though technically irrelevant?

**Comment by Seelengrab** [comment]
There is one place where stylishness doesn't work though:

```
julia> f(v::Vector{<:Union{T, Missing}}) where T = "union"
f (generic function with 3 methods)                       
                                                          
julia> f(v::Vector{<:(>:Missing)}) = "missing"            
ERROR: MethodError: no method matching >:(::Type{Missing})
Closest candidates are:                                   
  >:(::Any, ::Any) at operators.jl:30                     
Stacktrace:                                               
 [1] top-level scope                                      
   @ REPL[21]:1                                           
```

though I doubt the usefullness of that

**Comment by martinholters** [comment]
> that last one should just collapse to f(v::Vector) in the first place (though it doesn't right now):

It's not normalized, but they are recognized as equivalent, so can replace each other:
```julia
julia> f(v::Vector{<:T}) where T >: Missing = "where"
f (generic function with 1 method)

julia> methods(f)
# 1 method for generic function "f":
[1] f(v::Vector{<:T}) where T>:Missing in Main at REPL[1]:1

julia> f(v::Vector)= "nowhere"
f (generic function with 1 method)

julia> methods(f)
# 1 method for generic function "f":
[1] f(v::Vector) in Main at REPL[3]:1
```
