### ISSUE TITLE
Type boxed unexpectedly

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#42052]
From: https://github.com/JuliaPlots/PlotUtils.jl/pull/119

Changing `i = findlast(t -> t < x, v)` to `i = findlast(<(x), v)` here greatly improved performance because the former caused the function to box `x`.

Seems like they should be equivalent?

**Comment by simeonschaub** [comment]
`x` is assigned to multiple times, so this is another instance of https://github.com/JuliaLang/julia/issues/15276.
