### ISSUE TITLE
Trivial code crash (put into a global channel from a function)

### ISSUE THREAD

**Issue by orenbenkiki** [JuliaLang/julia#42066]
This is with Julia version 1.6.2.

With the trivial code file `Crash.jl`:

```julia
channel = Channel{Int}(100)

function crashes()::Nothing
    put!(channel, 0)  # Crashes on ambiguous convert
end

put!(channel, 0)  # Works
crashes()  # Crashes
```

Running `julia Crash.jl` gives me:
```
ERROR: LoadError: MethodError: convert(::Type{Union{}}, ::Int64) is ambiguous. Candidates:
  convert(::Type{T}, x::Number) where T<:AbstractChar in Base at char.jl:179
  convert(::Type{T}, x::Number) where T<:Number in Base at number.jl:7
  convert(::Type{Union{}}, x) in Base at essentials.jl:203
  convert(::Type{T}, arg) where T<:VecElement in Base at baseext.jl:8
Possible fix, define
  convert(::Type{Union{}}, ::Number)
Stacktrace:
 [1] convert(#unused#::Type{Nothing}, x::Int64)
   @ Base ./some.jl:36
 [2] crashes()
   @ Main ~/Crash.jl:4
 [3] top-level scope
   @ ~/Crash.jl:8
in expression starting at /home/obk/Crash.jl:8
```

For fun and giggles, if I change this to the `Works.jl` file:
```julia
channel = Channel{Int}(100)

function works()::Nothing
    println("will put in function")
    put!(channel, 0)  # Works
    println("did put in function")
end

println("will put in top level")
put!(channel, 0)  # Works
println("did put in top level")
works()
```

Then running `Julia Works.jl`, it gives me the expected output:
```
will put in top level
did put in top level
will put in function
did put in function
```

Am I doing something wrong here or is this a Julia runtime/compiler bug?

**Comment by Seelengrab** [comment]
`put!` returns the value that you put and you have a type assertion of `::Nothing` on crashes. The last value in a julia function will also be returned from that function, so it tries to convert the `Int` returned by `put!` to `Nothing`, which fails.

```
julia> channel = Channel{Int}(100)                         
Channel{Int64}(100) (empty)                                

julia> function no_crashes()::Nothing                      
           put!(channel, 0)
           nothing                                         
       end                                                 
no_crashes (generic function with 1 method)                
                                                           
julia> no_crashes()                                        
                                                           
julia> take!(channel)                                      
0                                                          
```

**Comment by orenbenkiki** [comment]
Ouch. I get the reasoning but that is one truly opaque error message... a tiny hint saying "return value" somewhere in the message would have done wonders.

At any rate, thanks for the clarification!

**Comment by Seelengrab** [comment]
The lowered code doesn't know anything about it being the last `convert` in the function, it's just like you had called convert 
 and asserted the type yourself:

```julia
julia> function also_crashes() # no type assertion                                                  
           convert(Nothing, put!(channel, 0))::Nothing # we assert it inside of the function instead
       end                                                                                          
also_crashes (generic function with 1 method)                                                       
                                                                                                    
julia> @code_lowered also_crashes()                                                                 
CodeInfo(                                                                                           
1 ─ %1 = Main.put!(Main.channel, 0)                                                                 
│   %2 = Main.convert(Main.Nothing, %1)                                                             
│   %3 = Core.typeassert(%2, Main.Nothing)                                                          
└──      return %3                                                                                  
)                                                                                                   
                                                                                                    
julia> @code_lowered crashes()                                                                      
CodeInfo(                                                                                           
1 ─ %1 = Main.Nothing                                                                               
│   %2 = Main.put!(Main.channel, 0)                                                                 
│   %3 = Base.convert(%1, %2)                                                                       
│   %4 = Core.typeassert(%3, %1)                                                                    
└──      return %4                                                                                  
)                                                                                                   
```

While there could be an argument made about handling that specially in lowering, I think the general consensus was that making lowering more special isn't wanted (not an authority on this though).

There are also a bunch of issues about similar confusions stemming from weird errors 😓 Sadly it's not always clear cut how to implement better error messages because often the message that would have helped one user would confuse another, because the error truly is ambigous.

**Comment by orenbenkiki** [comment]
I agree this doesn't warrant a special case - that is, I can see now why the crash is justified. And there's no argument that creating good error messages is hard.

Still, in general I found it difficult to figure out what was the actual target of the convert when seeing conversion errors - was it converting something into a function parameter? Into the target of an assignment? The return value from a function (as in my case above)?

E.g. if one has `v = f(g(a), h(b, c))` good luck figuring out what a convert error refers to - there are at least 6 possibilities. Presumably this information is available (not necessarily easily) - it "knows" the conversion error was, say, when converting the return value of `h` into the 2nd parameter of `f`. It would be "very nice indeed" if the error message said "converting into the 2nd parameter of `f`" (or in my case above, "into the return value of `crashes`").

Again, I've no idea how difficult it would be in the implementation of the error message - just saying that if someone wants to improve the error messages, this would be a good place.

**Comment by Seelengrab** [comment]
> E.g. if one has v = f(g(a), h(b, c)) good luck figuring out what a convert error refers to - there are at least 6 possibilities.

It's fewer than that, because for some of those you'll get a different error, a `MethodError`. I'll assume `f` has argument types specified and either `g` or `h` or both assert their return type (which isn't really needed except if the compiler can't figure out the return type on its own and you can, which is really rare and shouldn't be the case anymore for type stable functions).

 * If the conversion done by either `g` or `h` or both succeds but the resulting type doesn't match the requested type for any method of `f`, julia will throw a `MethodError` for `f`, notifying you that the given types don't have a method for `f` to apply to.
 * If the conversion done by either `g` or `h` fails (whichever fails first), you'll get a stacktrace similar to the one you got above:

```
Stacktrace:
 [1] convert(#unused#::Type{Nothing}, x::Int64)
   @ Base ./some.jl:36
 [2] h()
   @ Main ~/Crash.jl:4
```

Since the conversion happens inside the function in question, you'll know exactly where to look - in this example, it's the one in `h` that failed.

**Comment by Seelengrab** [comment]
> Presumably, whenever the compiler injects such an implicit convert, it could tag it with a description of the target of the convert, and then if there's an error message, include the target information from that tag. 

Such a "tag" is what I was referring to with `try`/`catch` above, to specialize the error message in case an error is thrown.
