### ISSUE TITLE
Some tests in my package is failing with Julia-nightly

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#42087]
Hi!

I am not sure if this is expected, but a set of tests in SatelliteToolbox.jl started to fail in Julia-nightly.

The test line is:

```julia
            Ba = @test_logs (:warn, "The magnetic field computed with this IGRF version may be of reduced accuracy for years greater than 2025.") #=
                 =# igrf(date, r*1000, (90-colat)*pi/180, elong*pi/180)
```

which is returning this:

```
   Test.LogRecord(Warn, "`@_inline_meta` is deprecated, use `@inline` instead.", Core.Compiler, :depwarn, (Ptr{Nothing} @0x00007fc3dfed00e3, Symbol("@_inline_meta")), "./compiler/utilities.jl", 111, Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:caller, :maxlog), Tuple{Base.StackTraces.StackFrame, Int64}}}(:caller => get_staged(mi::Core.MethodInstance) at utilities.jl:111, :maxlog => 1))
```

Is it expected?

**Comment by oscardssmith** [comment]
To clarify, does `SatelliteToolbox` call `@_inline_meta` directly ever?

**Comment by Seelengrab** [comment]
Doesn't look like it:

```
:SatelliteToolbox.jl $ rg "@_inline_meta" | wc -l
0                                                          
:SatelliteToolbox.jl $ rg "@inline" | wc -l 
135                                                        
```

**Comment by ronisbr** [comment]
> To clarify, does `SatelliteToolbox` call `@_inline_meta` directly ever?

No, I do not use!

**Comment by vtjnash** [comment]
The backtrace above shows it is from an `@generated` function

**Comment by KristofferC** [comment]
https://juliahub.com/ui/Search?q=%40_inline_meta&type=code

**Comment by vtjnash** [comment]
Can we make this a silent deprecation? It is hard to support both otherwise

**Comment by timholy** [comment]
What about a `Compat.@inline`? And then we should ping all the package maintainers in that search. (It's not really so many.)

**Comment by moble** [comment]
@ronisbr This seems to be resolved for me.  Can this issue be closed?

**Comment by ronisbr** [comment]
Sorry for the lat response, I totally missed the notification. Yes, thank you very much! The issue is fixed.
