### ISSUE TITLE
inference: need to invalidate stale `Conditional` wrapped in `PartialStruct`

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#42090]
MRE:
```julia
# should invalidate old constraint wrapped in PartialStruct when the subject of condition has changed
let M = Module()
    @eval M begin
        struct BePartialStruct
            val::Int
            cond
        end
    end

    rt = @eval M begin
        Base.return_types((Union{Nothing,Int},)) do a
            cond = a === nothing
            obj = $(Expr(:new, M.BePartialStruct, 42, :cond))
            r1 = getfield(obj, :cond) ? 0 : a # r1::Int
            a = $(gensym(:anyvar))::Any
            r2 = getfield(obj, :cond) ? a : nothing # r2::Any, not r2::Const(nothing)
            return r1, r2 # ::Tuple{Int,Any}
        end |> only
    end
    @test rt == Tuple{Int,Any}
end
```

I encountered `Conditional` wrapped in `PartialStruct` when the `Conditional` is captured in a closure.

Solutions:
- (dirty, but more accurate) we can add another special case as like `LimitedAccuracy`: https://github.com/JuliaLang/julia/blob/3aada5982c368f075dd0014dd9bdd5b8d2947b51/base/compiler/typelattice.jl#L366
- (simple, but less accurate) disallow `PartialStruct` to wrap `Conditional`

Which one do we want ?

**Comment by vtjnash** [comment]
I would prefer the simpler solution. There is typically no value in forwarding Conditional too far (widenreturn often strips it too).
