### ISSUE TITLE
`@inbounds` isn't propagated for `CartesianIndices`

### ISSUE THREAD

**Issue by Tokazama** [JuliaLang/julia#42115]
Recent discussion in ArrayInterface.jl demonstrated that `@inbounds` isn't fully propagated when using `CartesianIndices` to convert an integer to a `CartesianIndex`.
Examples across multiple versions and hardware are more fully demonstrated here https://github.com/JuliaArrays/ArrayInterface.jl/pull/199). 

I think the offending line is the missing `@propagate_inbounds` here:

https://github.com/JuliaLang/julia/blob/027071f0fe1a4313ddba5a0909b6f851dff96452/base/abstractarray.jl#L1254

This could probably be fixed here also:

https://github.com/JuliaLang/julia/blob/027071f0fe1a4313ddba5a0909b6f851dff96452/base/abstractarray.jl#L1242

I think @timholy and @mbauman wrote the original code here.
Can we just put `@propagate_inbounds` in front of these?

**Comment by mbauman** [comment]
Those implementations look ok to me; `@propagate_inbounds` might possibly be needed on their _caller_ function, but they will appropriately skip the boundscheck if called with `@inbounds` as written.  Hard for me to quickly identify where the problem is in the linked issue.  Note that `@propagate_inbounds` is only needed if you _aren't_ using `@inbounds` in the implementation and want to rely upon the caller's inbounds state.

**Comment by Tokazama** [comment]
K. Trying with this `inbounds_getindex(x, i) = @inbounds(x[i])` produces the following errors when something is out of bounds.
```julia
ERROR: BoundsError: attempt to access 2-element Base.OneTo{Int64} at index [3]
Stacktrace:
  [1] throw_boundserror(A::Base.OneTo{Int64}, I::Int64)
    @ Base ./abstractarray.jl:691
  [2] getindex
    @ ./range.jl:863 [inlined]
  [3] _broadcast_getindex_evalf
    @ ./broadcast.jl:670 [inlined]
  [4] _broadcast_getindex
    @ ./broadcast.jl:643 [inlined]
  [5] #29
    @ ./broadcast.jl:1119 [inlined]
  [6] ntuple
    @ ./ntuple.jl:49 [inlined]
  [7] copy
    @ ./broadcast.jl:1119 [inlined]
  [8] materialize
    @ ./broadcast.jl:904 [inlined]
  [9] getindex
    @ ./multidimensional.jl:357 [inlined]
 [10] inbounds_getindex(x::CartesianIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, i1::Int64, i2::Int64)
    @ Main ./REPL[8]:1
 [11] top-level scope
    @ REPL[10]:1
```
This doesn't happen with `--check-bounds=no`.

I'm assuming that once we get into the broadcasting machinery there's a big risk of inadvertently messing things up, so could we just avoid broadcasting here:
https://github.com/JuliaLang/julia/blob/027071f0fe1a4313ddba5a0909b6f851dff96452/base/multidimensional.jl#L361

and instead just call `CartesianIndex(I)`
