### ISSUE TITLE
[Q] system design in julia

### ISSUE THREAD

**Issue by INF800** [JuliaLang/julia#42114]
Hi,

I need some resources to learn system design (by building stuff) in Julia so that I can learn both the language itself and core principles of system design.

Can anyone help me with it?

**Comment by KristofferC** [comment]
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!
