### ISSUE TITLE
map is not defined on sets/dictionaries, but it should be

### ISSUE THREAD

**Issue by VikoRifeo** [JuliaLang/julia#42132]
```
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

Attempting to `Base.map` a set or dictionary gives the specialized error messages "map is not defined on sets" and "map is not defined on dictionaries" respectively, even though map _is_ (or at least should be) defined on any iterable, including DataStructures.jl's OrderedDict, OrderedSet, and their Sorted counterparts. `Base.collect` works on them, anyway (and provides a workaround).

**Comment by jakobnissen** [comment]
`map` is currently not defined for sets and dicts because there is no agreement about what it should return. You can find the issue here: https://github.com/JuliaLang/julia/issues/5794
