### ISSUE TITLE
varinfo killed

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#42143]
a)

```
julia> using MLStyle

julia> varinfo(MLStyle, all=true, recursive=true, imported=true);
Killed
```

I'm not sure why, I'm on 1.7.0-beta3.0, and just discovered this function (that seems to work otherwise; with other packages).

b)
Is there a reason only Regex allowed?

It seemed better to allow Strings too (or intentional to disallow?), but I'm not sure why this doesn't work (otherwise could be a PR):

```
julia> import InteractiveUtils.varinfo

julia> varinfo(m::Module=Main, pattern::String=""; all::Bool = false, imported::Bool = false, sortby::Symbol = :name, recursive::Bool = false) = varinfo(m, Regex(pattern), all, imported, sortby, recursive)
varinfo (generic function with 5 methods)

julia> varinfo("m")
ERROR: MethodError: no method matching varinfo(::String)
```

**Comment by jakobnissen** [comment]
Possible dup of https://github.com/JuliaLang/julia/issues/42045 ?

**Comment by KristofferC** [comment]
Confirmed fixed.
