### ISSUE TITLE
xoshiro256++ implementation in task.c

### ISSUE THREAD

**Issue by stefan-zobel** [JuliaLang/julia#42150]
https://github.com/JuliaLang/julia/blob/272eaf97bdd4364cae149c99128613023b24af42/src/task.c#L670

Shouldn't this be `s1` as in

`uint64_t t = s1 << 17;` ?

Note: `s1`, not **s0**

See Fig. 5 ("C code for a xoshiro256+/xoshiro256++/xoshiro256** generator") on page 6 in the Blackman / Vigna paper : https://arxiv.org/pdf/1805.01407.pdf

**Comment by stevengj** [comment]
cc @chethega and @rfourquet, who wrote this code.

**Comment by GregPlowman** [comment]
Also, implementation in `task.c` seems inconsistent with `stdlib` version:

https://github.com/JuliaLang/julia/blob/272eaf97bdd4364cae149c99128613023b24af42/src/task.c#L672

https://github.com/JuliaLang/julia/blob/3a4198e91644a66b33d82921348ce4e050fae633/stdlib/Random/src/Xoshiro.jl#L57

Shouldn't this be: 
```
res = (tmp << 23 | tmp >> 41) + s0
```

**Comment by PallHaraldsson** [comment]
It seems obvious that both the implementations are wrong, so this needs to be added to 1.7 milestone.

**Comment by bjarthur** [comment]
possibly related??  https://discourse.julialang.org/t/same-random-sequence-on-gpu-and-cpu/67881/4

**Comment by vtjnash** [comment]
This is not undefined behavior, so unrelated. There is perhaps a fast-fill array method that is vectorized for longer arrays? I am not sure if it was supposed to show a difference for simple sequences like that.
