### ISSUE TITLE
first elements of random Array depend on length

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#42165]
```
julia> using Random

julia> sz = 3; a = Vector{Float64}(undef, sz); Random.seed!(1); Random.rand!(a)
3-element Vector{Float64}:
 0.12187431157074147
 0.6644047635643547
 0.927097461598609

julia> sz = 8; a = Vector{Float64}(undef, sz); Random.seed!(1); Random.rand!(a)
8-element Vector{Float64}:
 0.8701349878780872
 0.006457014103689707
 0.773618934964177
 0.28204319051637505
 0.5531597766343656
 0.08793093987132328
 0.9123350298255161
 0.4730983492512397
```

this is on 1.7.0-beta4.  for 1.6.1 they are the same.  a bug, right?

**Comment by KristofferC** [comment]
Why would it be a bug though?

**Comment by vtjnash** [comment]
The same random seed is giving different numbers, which is unintuitive

**Comment by vtjnash** [comment]
On second thought, this may be related to https://github.com/JuliaLang/julia/pull/42158, if the vectorized code is diverging from the scalar code (due to bugs in each)

**Comment by oscardssmith** [comment]
I don't think this is a bug, but it definitely is weird.

**Comment by KristofferC** [comment]
If it is a bug with the implementation then it is a bug with the implementation, but the behavior in itself doesn't seem very weird. It is not uncommon you can do things faster if you know you will do a lot of that thing (SIMD).

**Comment by bjarthur** [comment]
unless there is a benefit to not being intuitive (ie faster, more random), then i'd say it's a bug

**Comment by maleadt** [comment]
What adds to the un-intuitiveness is that using a wrapper that (presumably) breaks the optimization gives the 'expected' results:

```
julia> sz = 3; a = Vector{Float64}(undef, sz); Random.seed!(1); Random.rand!(view(a, :))
3-element view(::Vector{Float64}, :) with eltype Float64:
 0.12187431157074147
 0.6644047635643547
 0.927097461598609

julia> sz = 8; a = Vector{Float64}(undef, sz); Random.seed!(1); Random.rand!(view(a, :))
8-element view(::Vector{Float64}, :) with eltype Float64:
 0.12187431157074147
 0.6644047635643547
 0.927097461598609
 0.02155985966702112
 0.823003041206761
 0.9864191953343232
 0.6825847490017343
 0.16307852197722794
```

**Comment by JeffBezanson** [comment]
I believe this is because of the SIMD implementation, which over a certain size forks the random stream into separate streams for each vector lane.

**Comment by KristofferC** [comment]
Explicitly:

https://github.com/JuliaLang/julia/blob/e5884e74a5fb15b11d5e116efa05d186ebe2a74a/stdlib/Random/src/XoshiroSimd.jl#L139-L147

so I think this can be closed and the disparity is intended.
