### ISSUE TITLE
Parsing CLI Args in Julia Scripts

### ISSUE THREAD

**Issue by lfenzo** [JuliaLang/julia#42174]
I have some background in Python and I recently started learning Julia. My first instinct was to learn the basics for scripting so I could follow my usual workflow as if I was using Python.

However, I was surprised to know that Julia's Standard Library doesn't have something like [argparse](https://docs.python.org/3/library/argparse.html) in Python for CLI argument parsing. I'm aware of packages like [ArgParse.jl](https://github.com/carlobaldassi/ArgParse.jl) and [ArgParse2.jl](https://github.com/kmsquire/ArgParse2.jl) that implement such functionalities but I wonder if this could ever be added to the SL. I think It would make more sense to have argument parsing embedded to the "language core" than having it done by third party packages.

I imagine that having these different third party options would allow more frequent updates, fixes and, to some extent, customization as it doesn't depend directly on the Julia version updates. But even though, I feel that this should be a part of the SL and would prefer to use it rather than the other packages.

Is this something that could be easily done? What do you think?

Thanks!!

**Comment by simeonschaub** [comment]
> I imagine that having these different third party options would allow more frequent updates, fixes and, to some extent, customization as it doesn't depend directly on the Julia version updates.

Exactly that. There are no good reason to move something to a stdlib unless Base or Pkg depends on it. The fact that there are already multiple packages for this out there would also suggest that there might not be a "one size fits all" solution, so with external packages users have the choice depending on their particular needs.
