### ISSUE TITLE
Add support for IEEE 754-2019 e.g. asinpi and "augmented arithmetic operations"

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#42183]
https://en.wikipedia.org/wiki/IEEE_754#Recommended_operations

What more is missing from this list?

Seemingly n-th root, or how is it done for other than n=2 or 3?   

Intriguing: "the formerly required minNum, maxNum, minNumMag, and maxNumMag in IEEE 754-2008 are now deleted due to their non-associativity.#

**Comment by StefanKarpinski** [comment]
Any intention to work on this?
