### ISSUE TITLE
Faster `zlib` stdlib with zlib-ng

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#42218]
https://github.com/zlib-ng/zlib-ng

has shown to be 20%-30% faster (compiled with `ZLIB_COMPAT` so we don't need to change any code from our side), we should consider testing it.

**Comment by oscardssmith** [comment]
The only reason not to is if we think we can do a better job in Julia.

**Comment by Moelf** [comment]
that would be cool but given the lack of activity in the `CodecX` collection, I doubt people find this an issue. It's funny because recently, https://github.com/Moelf/UnROOT_RDataFrame_MiniBenchmark/tree/master/simple_benchmarks#results we found that calling `transcode()` is where we're losing time we gained in other places with respect to C++ ROOT (see the lead in `uncompressed` row, where we're not calling these decompression libraries).

**Comment by quinnj** [comment]
Note that @Drvi and I built this out in https://github.com/Drvi/CodecZlibNG.jl
