### ISSUE TITLE
compiler hang in julia 1.7 on Gridap tutorial

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#42236]
See the following issue in Gridap.jl — one of the tutorials that worked in Julia 1.6 now causes the compiler to hang in 1.7-beta4

https://github.com/gridap/Tutorials/issues/118

cc @fverdugo

**Comment by stevengj** [comment]
Note: `git clone https://github.com/gridap/Tutorials`, then run `julia --project=Tutorial`, `cd` to `Tutorial/test` and `include("../src/emscatter.jl")`.

I tried to reproduce in `master` (1.8), but I'm getting
```
julia> include("../src/emscatter.jl")
[ Info: Precompiling Gridap [56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e]
ERROR: LoadError: UndefVarError: @aggressive_constprop not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Static/SG32r/src/Static.jl:10
 [2] include
   @ ./Base.jl:416 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1329
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:368 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [7] top-level scope
   @ none:1
in expression starting at /Users/stevenj/.julia/packages/Static/SG32r/src/Static.jl:1
```

**Comment by stevengj** [comment]
@fverdugo, it's taking an awfully long time to run this on Julia 1.6 for me — can you check for which version of Julia this script was working?

**Comment by fverdugo** [comment]
@stevengj I have not run it locally (as far as I can remember), but it seems to take a long time also in the CI: https://github.com/gridap/Tutorials/runs/3433911309?check_suite_focus=true

**Comment by KristofferC** [comment]
If it is something with type intersection it should repro even with a smaller mesh, so maybe try that and get the 1.6 time into something reasonable.

**Comment by stevengj** [comment]
The mesh is small enough that the actual solver should take seconds, no? I think most of the time is compilation even on 1.6.

**Comment by KristofferC** [comment]
I didn't look at the mesh size, I just assumed that the problem didn't take 20 minutes to compile on 1.6.

**Comment by WenjieYao** [comment]
@stevengj My julia version is just 1.6.0. I think one reason that it takes long is the analytical solution. For each element it requires (40+40+1=) 81 summation of the bessel/hankel functions. That is indeed the most time consuming part when I run the code in a jupyter notebook. However, when I run the code from command line with `julia --emscatter.jl‘, it takes awfully long compared to the jupyter noteook....

**Comment by stevengj** [comment]
(We can just comment out the analytical part for checking the compiler.)

**Comment by stevengj** [comment]
In particular, you can execute this line instead of `include("../src/emscatter.jl")` in order to skip the expensive semi-analytical calculation:
```jl
@time include_string(Main, join(first(eachline("../src/emscatter.jl"), 188), '\n'))
```
It takes about 78 seconds on my machine with Julia 1.6.2.

**Comment by fverdugo** [comment]
On my side, I have launched a run (full tutorial) with a mesh with 10x larger element size: https://github.com/gridap/Tutorials/runs/3589499691

Let's see if the times go significantly down or not

**Comment by stevengj** [comment]
The same 
```jl
include_string(Main, join(first(eachline("../src/emscatter.jl"), 188), '\n'))
```
indeed hangs in 1.7.0-beta4 — it's been running on my machine for an hour now.

**Comment by vchuravy** [comment]
Is it hanging or just taking a very long time?

Can you take a profile?

**Comment by stevengj** [comment]
It ran for over an hour when on 1.6 it takes a minute, so it’s either hanging or there is a > 100x slowdown. Do you mean gcc-based profiling?

**Comment by JeffBezanson** [comment]
In a debug build there is also:
```
Unbound GlobalRef not allowed in value position
Internal error: encountered unexpected error in runtime:
ErrorException("")
error at ./error.jl:33
check_op at ./compiler/ssair/verify.jl:41
verify_ir at ./compiler/ssair/verify.jl:217
verify_ir at ./compiler/ssair/verify.jl:67 [inlined]
run_passes at ./compiler/optimize.jl:338
optimize at ./compiler/optimize.jl:314 [inlined]
```
but probably a separate issue?

**Comment by JeffBezanson** [comment]
Looks like these arguments to subtype are taking an extremely long time:
```
Tuple{typeof(Base.eltype), Union{Type{var"#s521"} where var"#s521"<:Tuple{E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, Vararg{E, N}} where N, Type{var"#s78"} where var"#s78"<:(Tuple{E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, E, Vararg{E, N}} where N)}} where E<:Function
Tuple{typeof(Base.eltype), Type{var"#s521"} where var"#s521"<:Tuple{Function, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Union{Gridap.CellData.CellField, Function}, Vararg{Union{Gridap.CellData.CellField, Function}, N}} where N}
```

**Comment by JeffBezanson** [comment]
The "good news" is that that subtype query takes forever in 1.6 as well; the change seems to be that inlining is now trying to union those types, which didn't occur in 1.6.

**Comment by fverdugo** [comment]
Hi @JeffBezanson, 

one of our users was able to find a MWE https://github.com/gridap/Gridap.jl/issues/657 (here the code crashes with an internal error instead of hanging)

I have been able to reproduce the crash in my machine.

**Comment by KristofferC** [comment]
> one of our users was able to find a MWE gridap/Gridap.jl#657 (here the code crashes with an internal error instead of hanging)

Are you sure that is the same issue? 

Also, out of curiosity, why are you generating such huge types as shown in https://github.com/JuliaLang/julia/issues/42236#issuecomment-919540178. It is always possible to generate big enough types that the type system can't handle it and it seems you are on the border now.

**Comment by stevengj** [comment]
> Also, out of curiosity, why are you generating such huge types

As I understand it, the types essentially represent the AST of a symbolic expression for the weak form of a PDE — this is represented in the type domain for performance, to force the compiler to specialize finite-element assembly code that is generated from this AST.

**Comment by fverdugo** [comment]
> As I understand it, the types essentially represent the AST of a symbolic expression for the weak form of a PDE — this is represented in the type domain for performance, to force the compiler to specialize finite-element assembly code that is generated from this AST.

Yes, in Gridap we build some complex and large types and this is the main reason.

In any case, we build complex types by nesting structs and the number of type params in each of those structs is usually less than 4. I am not aware of any part of the code that would lead to a tuple of 31 entries in this tutorial (see the Tuple{E,E,E,...,E} above), but I can be wrong of course...

**Comment by JeffBezanson** [comment]
So the 32-element tuple comes from changing `Any16` to `Any32` in base/tuple.jl. These types are hazardous and we should probably stop using them in favor of simple length checks.

**Comment by JeffBezanson** [comment]
> one of our users was able to find a MWE [gridap/Gridap.jl#657](https://github.com/gridap/Gridap.jl/issues/657) (here the code crashes with an internal error instead of hanging)

This definitely looks like a separate issue; could you file one?

**Comment by fverdugo** [comment]
> This definitely looks like a separate issue; could you file one?

Sure! https://github.com/JuliaLang/julia/issues/42264
