### ISSUE TITLE
Implement "The Eisel-Lemire ParseNumberF64 Algorithm": "Number Parsing at a Gigabyte per Second"

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#42243]
Something to consider. <s>I realize the older Ryu was recently implemented.</s>

https://nigeltao.github.io/blog/2020/eisel-lemire.html
"9 times faster than the C standard library’s strtod [..]
This blog post is much, much longer than the actual source code. The core function is about 80 lines of C/C++ code, excluding comments and the powers-of-10 table. lemire/fast_double_parser is the original C++ implementation. [..] There are also Julia and Rust re-implementations."

https://lemire.me/blog/2020/03/10/fast-float-parsing-in-practice/
"Michael Eisel kept insisting that it should be possible to both follow the standard and achieve great speed."

https://arxiv.org/pdf/2101.11408.pdf
"Our work is available as open source software used by major systems such as Apache Arrow and Yandex ClickHouse. The Go standard library has adopted a version of our approach."

https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html
"The standard library's implementation of float parsing has been updated to use the Eisel-Lemire algorithm, which brings both speed improvements and improved correctness."

**Comment by quinnj** [comment]
A version of the eisel-lemire algorithm is already implemented in the [Parsers.jl](https://github.com/JuliaData/Parsers.jl/blob/main/src/floats.jl) package. Ryu is about _writing_ floats, not parsing.

**Comment by PallHaraldsson** [comment]
Yes, Ryu doesn't parse, but Julia does and not with (that) fastest algorithm.

Julia can and maybe should use it, take pure Julia code from that package, and drop C code, which I'm not even sure is correct... should it use e.g. strtod_l?

https://github.com/JuliaLang/julia/blob/b790cf8f0c54b17d19c482073bde4d7e6db5c553/src/support/strtod.c#L32

https://github.com/JuliaLang/julia/blob/b790cf8f0c54b17d19c482073bde4d7e6db5c553/src/rtutils.c#L488

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/45301
