### ISSUE TITLE
startswith function doesn't work as expected

### ISSUE THREAD

**Issue by ggsoft** [JuliaLang/julia#42244]
Hi! It seems the **startswith** function works right only in example: startswith("JuliaLang", "Julia")
![Julia-startswith-bug](https://user-images.githubusercontent.com/790314/133180214-78c79a8a-9258-4411-a01b-ff394e6d7006.jpg)

**Comment by DilumAluthge** [comment]
Yes, the order of the arguments matters.

```
help?> startswith
search: startswith

  startswith(s::AbstractString, prefix::AbstractString)

  Return true if s starts with prefix. If prefix is a vector or set of characters, test
  whether the first character of s belongs to that set.
```

Please ask questions on Julia Discourse: https://discourse.julialang.org

**Comment by timholy** [comment]
Notice the implicit language: `a startswith b` (bigger string is first, smaller string is second) vs `a occursin b` (smaller string is first, bigger string is second). It would be completely wrong to make it work the other way.

**Comment by ggsoft** [comment]
Sorry, my mistake. Wrong order of arguments.
