### ISSUE TITLE
"Internal error" crash in Julia 1.7.0-beta4 when using the Gridap FEM library.

### ISSUE THREAD

**Issue by fverdugo** [JuliaLang/julia#42264]
We are experiencing a crash in Julia 1.7.0-beta4 with a simple MWE written with code from the Gridap FEM library.

See this issue for full details: https://github.com/gridap/Gridap.jl/issues/657

If you need further help to dig deeper into the issue, just let me know.

Thanks for the help and the amazing Julia lang!

**Comment by JeffBezanson** [comment]
Bisect picks 3635f0473dea7c7254d611e3eaa939e0f6dd9484, which doesn't seem to directly make sense. It might be due to forming more union types, leading to more union splitting, eventually triggering this.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/commit/3635f0473dea7c7254d611e3eaa939e0f6dd9484 also caused https://github.com/JuliaLang/julia/issues/42007.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/42347
