### ISSUE TITLE
Online documentation/help("...") for keywords and other language constructs.

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#4226]
I think, help texts for keywords could be useful for beginners, `help("using")` comes to mind.

**Comment by one-more-minute** [comment]
You can hardly say we're not responsive, even if the turnaround time is on the order of a couple years.

Anyway, you can even get help for the splat operator (`...`) in 0.4 now :)

**Comment by mschauer** [comment]
...the mills grind slowly, yet they grind exceeding fine.
