### ISSUE TITLE
 Better documentation for properties vs. fields

### ISSUE THREAD

**Issue by nandoconde** [JuliaLang/julia#42273]
# Background
## Weird pattern for accessing fields
I found myself often using the quite uncomfortable
```julia
fieldnames(typeof(x))
```
Searching for something unrelated, I found in an old Discourse thread this magic:
```julia
propertynames(x)
```
Which turns out to be a fantastic alternative, without so much boilerplate, and also the recommended way to override `fieldnames` functionality for those situations in which you want to keep attributes private, extend functionality, etc. 

The thing is, **this is poorly documented**.

## How well documented are both alternatives
A quick search in the docs shows that [`fieldnames`](https://docs.julialang.org/en/v1/search/?q=fieldnames):
- is referenced more times across the docs (8 times)
- is referenced within "more important sources", i.e., [Essentials](https://docs.julialang.org/en/v1/base/base/) and [Types](https://docs.julialang.org/en/v1/manual/types/) pages
- is referenced twice within devdocs, [Reflection](https://docs.julialang.org/en/v1/devdocs/reflection/) and [ASTs](https://docs.julialang.org/en/v1/devdocs/ast/)

Whereas [`propertynames`](https://docs.julialang.org/en/v1/search/?q=propertynames):
- is less referenced (only 4 times)
- only shows up in one "important" page,  [Essentials](https://docs.julialang.org/en/v1/base/base/), which is the least self-explanatory source of information, because it is just a collection of `Base`

# Discussion
Two points can be extracted from above:

## Increase documentation coverage for `propertynames`

As seen in the previous part, it is clearly insufficient, and difficult for a beginner to learn of this method, except searching for very specific things in Discourse or reading one by one the functions available in `Base`.

## Properly documenting the distinction between properties and fields

Several programming patterns depend upon exposing some fields of an struct and hiding others, or discouraging direct access to struct fields and rather use "getters"/"setters" (or any *ad hoc* method). This is the nature of the difference between fields and properties, and should be explained somewhere.

**Comment by thazhemadam** [comment]
This has been addressed in https://github.com/JuliaLang/julia/pull/45293. Can this issue be closed?
