### ISSUE TITLE
Add Julia equivalent of "nargout" to docs

### ISSUE THREAD

**Issue by lsorber** [JuliaLang/julia#4227]
What are the best ways of translating MATLAB functions to Julia of which the output and its computations are based on nargout?

In my case, I would like to know the best workaround for a hypothetical optimization suite written in Julia in which the user is asked to supply a function which computes an objective function value, and as an optional second output a derivative. The advantage of a nargout approach is that the user need only write one function and, importantly, that in many cases some of the computation between the objective function and its derivative may be shared.

**Comment by ViralBShah** [comment]
Updated URL: http://docs.julialang.org/en/latest/manual/noteworthy-differences/#noteworthy-differences-from-matlab

**Comment by tkelman** [comment]
backported (squashed along with the formatting fix) in 4baf8e4e87a3214c5e4eadd1cb5d3eacce2d3f38
