### ISSUE TITLE
Inferior performance of cld vs ceil for floating-point arguments

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#42294]
See the [discourse discussion](https://discourse.julialang.org/t/performance-of-cld-vs-ceil/68309)

The issue is
```julia
julia> x = 5.5; y = 2.2;

julia> @btime cld($(Ref(x))[], $(Ref(y))[])
  23.836 ns (0 allocations: 0 bytes)
3.0

julia> @btime ceil(($(Ref(x))[] / $(Ref(y))[]))
  2.682 ns (0 allocations: 0 bytes)
3.0
```

It appears that `cld` is much slower than `ceil`, which is evidently because, as @oscardssmith states,

> It looks like we are calling the wrong method for it accidentally. We are currently calling cld(x::T, y::T) where T<:AbstractFloat in Base at float.jl:422, but we should be calling cld(a::T, b::T) where T<:Union{AbstractFloat, Integer} in Base at div.jl:269. I’m not sure what caused this.

Creating an issue so that this isn't forgotten

**Comment by N5N3** [comment]
The slow dispatch was first introduced in PR#8111.
It seems fine to remove it.

**Comment by nsajko** [comment]
Seems fixed:

```julia-repl
julia> @btime cld(x, y) setup=(x=5.5;y=2.2;)
  1.292 ns (0 allocations: 0 bytes)
3.0

julia> @btime ceil(x/y) setup=(x=5.5;y=2.2;)
  1.302 ns (0 allocations: 0 bytes)
3.0
```

**Comment by oscardssmith** [comment]
yay!
