### ISSUE TITLE
UnitRange in 1.7-rc1

### ISSUE THREAD

**Issue by PaulSoderlind** [JuliaLang/julia#42291]
`x = (1:5) .- 1/7` in 1.7-rc1 gives `0.8571428571428572:1.0:3.857142857142857` and `length(x) = 4`

This is different from 1.6.2, and it also differs from what `collect(1:5) .- 1/7` would give.

See [Discourse](https://discourse.julialang.org/t/unitrange-in-1-7-rc1-bug/68327/7) for more details.

**Comment by mcabbott** [comment]
I believe it goes to this line: https://github.com/JuliaLang/julia/blob/master/base/broadcast.jl#L1106
```
broadcasted(::DefaultArrayStyle{1}, ::typeof(-), r::AbstractUnitRange, x::Real) = range(first(r) - x, last(r) - x)
```
last changed in https://github.com/JuliaLang/julia/pull/41619. And `length(range(1 - 1/7, 5 - 1/7)) == 4` due to rounding.

**Comment by PaulSoderlind** [comment]
Since there are few comments here, let me just add this: I am pretty sure that most users interpret `(1:5) .- 1/7` as being the same as `range(1,5,length=5) .- 1/7`. Motivation: the explicit `(1:5)`.
