### ISSUE TITLE
undef alias should be protected from overwriting?

### ISSUE THREAD

**Issue by stakaz** [JuliaLang/julia#42318]
Hello, I just realized that it is possible to simple redefine `undef` and by this destroy the possibility to use `Array{T}(undef, N)` as a generator. While I understand that it is still possible with `UndefInitializer()` since a lot of examples online and also the code in the Base apparently uses `undef`, would it be a good think to reserve it and disallow reassignment?

**Comment by KristofferC** [comment]
What's the difference between `undef` and every other variable exported by Julia?

**Comment by stakaz** [comment]
Technically of course there is no difference. However, the common way of defining an uninitialized array with `Array{T}(undef, N)` suggests that undef has a "reserved" meaning here for a newcomer. It looks similar to cases like `fill(false, N)` and `fill(missing, N)`.

Maybe using `const` would be an option?

**Comment by stakaz** [comment]
```julia
julia> missing = 4
ERROR: cannot assign a value to variable Base.missing from module Main
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```

**Comment by KristofferC** [comment]
> However, the common way of defining an uninitialized array with Array{T}(undef, N) suggests that undef has a "reserved" meaning here for a newcomer. 

```julia
julia> Array = 3
3

julia> Array{Float64}(undef, 3)
ERROR: TypeError: in Type{...} expression, expected UnionAll, got a value of type Int64
```

> and `fill(missing, N)`

```julia
julia> missing = 3
3

julia> fill(missing, 5)
5-element Vector{Int64}:
 3
 3
 3
 3
 3
```

> Maybe using const would be an option?

`undef` is already `const`:

https://github.com/JuliaLang/julia/blob/6893f21a896e51989c40b0b6de5cb2512b8afc97/base/boot.jl#L450

> `ERROR: cannot assign a value to variable Base.missing from module Main`

That is if you have already used the  variable as `Base.missing`. The same is true for `undef`:

```
julia> undef
UndefInitializer(): array initializer with undefined values

julia> undef = 5
ERROR: cannot assign a value to variable Core.undef from module Main
```

Closing this since this is just how the language works.
