### ISSUE TITLE
osutils macros: `@unix`, `@osx`, etc.

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4233]
The stuff in base/osutils.jl that implements

```julia
@osx? 1 : 2
```

strikes me as a bit too cute. It took me a minute screwing around with the syntax to figure out what was even going on with this macro. Cute as the resulting usage may be, this strikes me as an abuse of syntax. If we do keep it, the documentation needs to be improved to include how you actually call these things and ideally, it would tell you the same information when you inevitably use it incorrectly.

Also, why does the implementation do syntax structure checking at run-time? That should be done during macro expansion.

cc: @vtjnash, @loladiro, @johnmyleswhite (people who touched this file).

**Comment by aviks** [comment]
A few more issues with this, for the record. 

1. The behaviour has changed between 0.3 and 0.4 . In 0.4, a space after the `?` is mandatory. 

In v0.3
```julia
julia> @osx? print("A"):print("B")
A
```

  In v0.4
```julia
julia> @osx?print("!"):print("B")
ERROR: wrong number of arguments

julia> @osx? print("A"):print("B")
A
```

2. Error location information is missing for parsing errors for this macro. Although, is this true of all macros?

```julia
julia> function f()
          println(1)
          println(2)
          @osx?print("Y"):print("N")
       end
ERROR: wrong number of arguments
```

**Comment by vtjnash** [comment]
OT: the parser is fine with this expression, the error happens later when starting to evaluate it.

**Comment by tkelman** [comment]
I said this in a different issue but can't find it right now, this fake ternary would be better replaced by a conditional macro `@if` or `@cond` for the times this os-dependent code selection has to happen at parse time.

**Comment by StefanKarpinski** [comment]
+1 to `@if`

**Comment by tkelman** [comment]
@vtjnash also suggests the possibility of a `@static` modifier, so we could do `@static if` - or something similar to force parse-time evaluation of a pure condition
