### ISSUE TITLE
`exp(::Matrix{Complex{BigFloat}})` not supported

### ISSUE THREAD

**Issue by foldfelis** [JuliaLang/julia#42359]
API [exp(A::AbstractMatrix)](https://github.com/JuliaLang/julia/blob/c4f0d8b2f6853507ab779e5146cfc6793fa959c1/stdlib/LinearAlgebra/src/dense.jl#L534) not support `Matrix{Complex{BigFloat}}`

**Comment by dkarrasch** [comment]
I'm closing this in favor of #48098 which contains a discussion of potential future developments regarding `BigFloat` linear algebra.
