### ISSUE TITLE
`jl_options` no longer exported by `libjulia.so`

### ISSUE THREAD

**Issue by dalekj** [JuliaLang/julia#42411]
In order to call some Julia code from MATLAB, I have a c program with Julia embedded which gets compiled as a MEX function. Because MATLAB (or JVM) do weird things with signals, I have to turn off Julia's signal handling by incorporating the following line in my c program.
```
jl_options.handle_signals = JL_OPTIONS_HANDLE_SIGNALS_OFF;
```

For Julia versions through `v1.5.x`, `jl_options` was exported by `libjulia.so`, supporting this. However, with the library split into `libjulia.so` and `libjulia-internal.so` that occurred in `v1.6`, `jl_options` is no longer exported by `libjulia.so`, although it is exported by `libjulia-internal.so`. If I link to both of the libraries, things work as expected, but it is my understanding that this is not the supported interface to embedding Julia; `libjulia.so` is the supported entry point for embedding Julia.

Could `jl_options` be added to the `libjulia.so` re-export list for future versions?
Or if there is a good reason not to provide access to `jl_options`, is there an alternative way to turn off Julia's signal handling?

**Comment by vtjnash** [comment]
Yes, we should export a pointer to `jl_options`, for external consumers

**Comment by JeffBezanson** [comment]
I have a fix for this in #41936; can separate and backport it.

**Comment by dalekj** [comment]
Thanks for fixing this.
@JeffBezanson is it possible to get the fix backported to 1.6.x since that is the new LTS?
