### ISSUE TITLE
Make isa(T) to return a function x -> isa(x, T)

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#42485]
Just like `isequal(x)` returns a function which compares to `x`, it would be nice that `isa(T)` returned a function which can be used to test if a value is of type `T`, that is:

```julia
isa(::Type{T}) where {T} = x -> isa(x, T)
```

(A user cannot define this method since `isa` is a built-in function).

**Comment by mcognetta** [comment]
This should also probably be done for `<:`, which is also a builtin.

**Comment by KristofferC** [comment]
This was discussed before and rejected based on the fact that the reason `isa` can be understood well by the compiler is because it is not a generic overloadable function. Maybe that has changed @aviatesk?

**Comment by simeonschaub** [comment]
Duplicate of #32018.

**Comment by simeonschaub** [comment]
In particular, https://github.com/JuliaLang/julia/pull/36759#issuecomment-662585813 is likely relevant
