### ISSUE TITLE
`hash(::UnitRange)` falls back to `AbstractArray` method; is insanely slow

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/julia#42522]
Hashing of `UnitRange` (and probably all `AbstractUnitRange`, maybe others) from  `Base` is incredibly slow because it is iterating over the entire thing.  Suggest we define
```julia
Base.hash(r::UnitRange) = foldr(hash, (r.start, r.stop), init=hash(typeof(r)))
```
Note that I have only tested this on 1.6.3, but these methods seem to be missing from `master` as well.

Any concerns, things I'm missing before opening a PR for this?  If I do that I will take a look in the `AbstractRange` type tree to find other methods that may need defining.

**Comment by vtjnash** [comment]
The hash of UnitRange must be equal to that of any other AbstractArray to which the value is equal. I don't think it iterates the whole range, just a few key points within it?

**Comment by ExpandingMan** [comment]
🤦 oh man, I didn't think of that.... yeah, I guess that makes sense.  Ouch, that hurts.  Guess we just need a lib with other types.

**Comment by vtjnash** [comment]
In particular, I recall that it examines `O(log(n))` values (from fibonacci), which can end up tending to approximate constant time, for most physically representable values of `n`.

**Comment by ExpandingMan** [comment]
Yup, yup.  It's perfectly reasonable, I was just blinded by my particular needs at the moment.  Just need new types that are easily hashable, maybe will make it into a package at some point.  Thanks.
