### ISSUE TITLE
Error during the `asan` CI job: "LLVM ERROR: inconsistency in registered CommandLine options"

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#42540]
This issue is to track the progress on fixing the "LLVM ERROR: inconsistency in registered CommandLine options" error seen in the `asan` CI job.

```
    LINK tmp/test-asan/asan/usr/lib/libjulia-codegen-debug.so.1
    LINK tmp/test-asan/asan/usr/lib/libjulia-codegen-debug.so
make[1]: Leaving directory '/cache/build/amdci8-0/julialang/julia-master/tmp/test-asan/asan/src'
make[1]: Entering directory '/cache/build/amdci8-0/julialang/julia-master/tmp/test-asan/asan'
    JULIA tmp/test-asan/asan/usr/lib/julia/corecompiler.ji
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted
make[1]: *** [/cache/build/amdci8-0/julialang/julia-master/sysimage.mk:61: /cache/build/amdci8-0/julialang/julia-master/tmp/test-asan/asan/usr/lib/julia/corecompiler.ji] Error 134
make[1]: Leaving directory '/cache/build/amdci8-0/julialang/julia-master/tmp/test-asan/asan'
make: *** [/cache/build/amdci8-0/julialang/julia-master/Makefile:82: julia-sysimg-ji] Error 2
make: Leaving directory '/cache/build/amdci8-0/julialang/julia-master/tmp/test-asan/asan'
🚨 Error: The command exited with status 2
```

Example log: https://buildkite.com/julialang/julia-master/builds/4455#3d8f2204-c0ae-43b8-a232-cfeb2a5be0c6

Introduced in https://github.com/JuliaLang/julia/pull/41936

**Comment by vchuravy** [comment]
So what this feel like is like we load two different LLVM libraries with the symbol versions being equal. When someone looks into it, I would be curious to see a backtraces on that error.

**Comment by vtjnash** [comment]
@JeffBezanson I think we either need to fix this or revert the codegen-split PR. We've already gone more than a month with CI disabeld due to this.

**Comment by DilumAluthge** [comment]
Just to clarify, it's only the `asan` CI job that has been marked as "allow failures". All of the other Buildkite CI jobs are running normally (with failures disallowed).

That being said, I do think it would be nice to fix this failure so that we can switch the `asan` CI job to run normally.

**Comment by tkf** [comment]
> this feel like is like we load two different LLVM libraries with the symbol versions being equal

I tried `LD_DEBUG=all ../usr/bin/julia-debug -C "native" --output-ji ../usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl 2>&1 | grep -v 'trying file=' | grep -Eo '/[^ ]*/libLLVM[^ ]*.so' | sort -u` to see if this is true. But it prints a single path `/home/arakaki/repos/watch/_wt/julia/llvm-asan-debug/usr/bin/../lib/libLLVM-12jl.so` which indicates that we only load one libLLVM?

Also, @vtjnash mentioned that LLVM 13 may fix it #42602

So maybe we are hitting an edge case in LLVM 12? I'll be happy if 13 fixes it anyway though :)

**Comment by tkf** [comment]
It seems #43685 improved ASAN but we still have

> ```LoadError("sysimg.jl", 19, LoadError("/cache/build/default-amdci4-1/julialang/julia-master/tmp/test-asan/asan/usr/share/julia/stdlib/v1.8/Random/src/Random.jl", 3, LoadError("/cache/build/default-amdci4-1/julialang/julia-master/tmp/test-asan/asan/usr/share/julia/stdlib/v1.8/Random/src/DSFMT.jl", 3, InexactError(:trunc, Int64, Inf))))```

which seems to be quite reproducible. I just checked four recent builds on `master` and of them failed with the same error:

https://buildkite.com/julialang/julia-master/builds/8121#179ccdd4-0691-496c-97cd-26c1039be38c/148-942
https://buildkite.com/julialang/julia-master/builds/8113#6f1c55e4-9e3b-4206-9c33-217cf3683eca/146-940
https://buildkite.com/julialang/julia-master/builds/8112#30b7be5d-b949-4018-9d73-e7e97a595b31/157-951
https://buildkite.com/julialang/julia-master/builds/8111#8200fe2a-6891-4ed0-a87b-9422b5defa4d/160-954

I don't know why ASAN triggers this though

**Comment by vtjnash** [comment]
It is an LLVM assertion error, but you are not running with assertions so it does not report it with complete information

**Comment by DilumAluthge** [comment]
For the `asan` CI job, we should probably build with assertions enabled:.

**Comment by tkf** [comment]
Do you mean to build (and cache) LLVM with assertion turned on?

**Comment by DilumAluthge** [comment]
IIUC, if you set `LLVM_ASSERTIONS=1`, we don't actually have to build LLVM from source; it will automatically download and use `LLVM_assert_jll`.
