### ISSUE TITLE
SparseArrays.nzrange could benefit from a Base.@propagate_inbounds

### ISSUE THREAD

**Issue by tomhaber** [JuliaLang/julia#42553]
When doing the following type of iteration over SparseArrays, I was expecting that no bound checks would be added.
However `nzrange` does add some because it doesn't have `Base.@propagate_inbounds`

```julia
@inbounds for j = 1:n
  @inbounds for idx in nzrange(X,j)
  end
end
```

The exact semantics of `@inbounds` here is somewhat unclear: my intuitive feeling is that the `@inbounds` of the inner loop doesn't include the `nzrange(X,j)` and only the loop body. This is not how `@inbounds` is implemented however.

**Comment by ViralBShah** [comment]
Should be moved to SparseArrays.jl
