### ISSUE TITLE
Easily reproducable thread crash under windows

### ISSUE THREAD

**Issue by aachrisg** [JuliaLang/julia#42599]
Running Julia on a 128 core/256 thread Windows box with dual AMD chips

Julia correctly autodetects it as having 256 threads, if asked to do so.

However, any threaded code will instantly crash julia under windows with this many threads. There seems to be a limit slightly under this that avoids the crash. To repro is simple:

> set JULIA_NUMTHREADS=256
> julia
julia> Threads.@threads for i = 1:1200
       end
**Julia instantly crashes with no message**

However:
> set JULIA_NUMTHREADS=200
> julia
julia> Threads.@threads for i = 1:1200
       end
**runs fine**

**Comment by inkydragon** [comment]
This will also happen on intel CPUs.

```julia
PS D:\> julia -t 250
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.3 (2021-09-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> Threads.nthreads()
250

julia> Threads.@threads for i = 1:12 end

julia> exit()
PS D:\> julia -t 251
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.3 (2021-09-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

julia> Threads.nthreads()
251

julia> Threads.@threads for i = 1:12 end
# crashes with no message
PS D:\>
```

**Comment by inkydragon** [comment]
I've updated the comment above.

1. Forward debugging stops at:
https://github.com/JuliaLang/julia/blob/ae8452a9e0b973991c30f27beb2201db1b0ea0d3/base/threadingconstructs.jl#L93
Maybe you can try some other debugging methods.

2. Crashed on `jl_setcontext`
https://github.com/JuliaLang/julia/blob/ae8452a9e0b973991c30f27beb2201db1b0ea0d3/src/support/_setjmp.win64.S#L144
You can combine the code and use WinDBG to set breakpoints to find out which function is calling `jl_setcontext`.

**Comment by askhari139** [comment]
Is there any update on this issue?

**Comment by vtjnash** [comment]
You may be exceeding various internal limits in the Windows NT kernel. We might not be able to circumvent that, except by suggesting using a different operating system without this limitations.

**Comment by vtjnash** [comment]
I think I added an error message that would have help here, though cannot exactly say that it applied here without an error message having been shown in the past
