### ISSUE TITLE
display of `Rational`s in containers

### ISSUE THREAD

**Issue by jmichel7** [JuliaLang/julia#42626]
In  my work, I often  have to work with  `Rational` matrices resulting from
simple mathematical operations on integer matrices, like:

```
julia> m=cartan(:A,3)
3×3 Matrix{Int64}:
  2  -1   0
 -1   2  -1
  0  -1   2

julia> n=schur_functor(m,[2,2])
6×6 Matrix{Rational{Int64}}:
   9//1   -6//1    4//1   3//2   -2//1    1//1
 -12//1   16//1  -16//1  -4//1    8//1   -4//1
   4//1   -8//1   16//1   2//1   -8//1    4//1
  12//1  -16//1   16//1  10//1  -16//1   12//1
  -4//1    8//1  -16//1  -4//1   16//1  -12//1
   1//1   -2//1    4//1   3//2   -6//1    9//1
```

I  find the display rather hard  to read. I tried for  a long time to think
what  could be the  least disruptive and  least controversial change to the
display  of rational numbers  which could improve  the situation. I came up
with the following

```
function Base.show(io::IO, x::Rational)
   show(io, numerator(x))
   if haskey(io,:typeinfo) && isone(denominator(x)) return end
   print(io, "//")
   show(io, denominator(x))
end
```

here  the only change is the `if` line, which says if the `Rational` number
is  actually an  integer, display  it as  an integer,  *if* the type of the
current  container has  already been  printed. I  think this would cause no
problem:  I  cannot  think  of  a  situation  where  a `Rational` `Vector`,
`Matrix`  or `Array` would be wrongly read/interpreted because of this. And
it already considerably improves the display. In the example above we get

```
julia> n
6×6 Matrix{Rational{Int64}}:
   9   -6    4  3//2   -2    1
 -12   16  -16  -4      8   -4
   4   -8   16   2     -8    4
  12  -16   16  10    -16   12
  -4    8  -16  -4     16  -12
   1   -2    4  3//2   -6    9
```

even in matrices which do not contain many integers, the simple fact that `0`
displays as `0` and not `0//1` makes things better.

What do you think about that?

**Comment by timholy** [comment]
Another thought might be to display
```julia
julia> [1//2 1//4]
1×2 Matrix{Rational{Int64}}:
 1//2  1//4
```
as something along the lines of
```julia
[2 1] // 4
```
There are numerous challenges, though, such as when the `lcm` would overflow.

**Comment by ParadaCarleton** [comment]
Relevant: Unicode has a fraction slash (`U+2044`, `⁄`) that can be used for pretty fractions like 1⁄4.

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/45396
