### ISSUE TITLE
MultivariateStats: LoadError: UndefVarError: transform not defined

### ISSUE THREAD

**Issue by JuanVargas** [JuliaLang/julia#42627]
I spent quite some time trying to use the Julia pkg MultivariateStats but I am not getting anywhere, even if I follow verbatim the instructions given in the docs.:

using MultivariateStats, RDatasets, Plots
plotly() # using plotly for graphing

# load iris dataset
iris = dataset("datasets", "iris")

# split half to training set
Xtr = convert(Matrix, iris[1:2:end,1:4])'
Xtr_labels = convert(Vector, iris[1:2:end,5])

# split other half to testing set
Xte = convert(Matrix, iris[2:2:end,1:4])'
Xte_labels = convert(Vector, iris[2:2:end,5])

# suppose Xtr and Xte are training and testing data matrix,
# with each observation in a column

# train a PCA model, allowing up to 3 dimensions
M = fit(PCA, Xtr; maxoutdim=3)

# apply PCA model to testing set
Yte = transform(M, Xte)
# ERROR: LoadError: UndefVarError: transform not defined

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
