### ISSUE TITLE
Current CI outages

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#42644]
There are currently no known CI outages.

If one or more CI checks are failing on a pull request, I recommend that you do not merge the pull request. Instead, I recommend going to the `#ci-failures-help` channel on the Julia Slack and asking about the CI failures.

**Comment by vtjnash** [comment]
Seems to be no current issues, so no issues to fix. The list of known issues should be accessible also from https://github.com/JuliaLang/julia/issues?q=is%3Aopen+is%3Aissue+label%3Aci+-label%3Afeature+ in the future
