### ISSUE TITLE
gemv speed regression on Windows on nightly

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#42680]
```
using LinearAlgebra, BenchmarkTools
n,m=1000,100; A=rand(n,m); x=rand(m); y=A*x; @btime mul!(y,A,x);
```
On nightly, the performance is 50% slower than on 1.6 or 1.7. Using Windows 10, i7-10750H, I get 
```
54.300 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.709
52.500 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.761
35.200 μs (0 allocations: 0 bytes) # Version 1.6.3
35.600 μs (0 allocations: 0 bytes) # Version 1.7.0-rc1
```
The performance was already really bad compared to running the Linux binary under WSL2 on the same machine
```
4.100 μs (0 allocations: 0 bytes) # Version 1.8.0-DEV.761
5.667 μs (0 allocations: 0 bytes) # Version 1.7.0-rc1
```
All tested binaries are from https://julialang.org/downloads/ .

**Comment by ViralBShah** [comment]
I see - so this is mainly a Windows issue. @staticfloat @DilumAluthge @giordano may be the right folks to ping.

**Comment by ViralBShah** [comment]
Is this performance regression also present in other linear algebra routines?

**Comment by staticfloat** [comment]
Well, I've been able to identify that this is in fact due to OpenBLAS and not anything else.  On my Windows VM, I can see a slowdown when directly `ccall()'ing` `dgemv_64_`.  Here's my test suite (which also bypasses LBT to ensure that that's not the source of the difference:

```
using Libdl, LinearAlgebra, BenchmarkTools
n,m=1000,100
A=rand(n,m)
x=rand(m)
y=A*x

libopenblas = Libdl.dlopen(only(filter(l -> occursin("libopenblas64_", l), Libdl.dllist())))
dgemv = Libdl.dlsym(libopenblas, "dgemv_64_")
@btime ccall(dgemv, Cvoid, (Ref{UInt8}, Ref{Int64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}, Ptr{Float64}, Ref{Int64}, Ref{Float64}, Ptr{Float64}, Ref{Int64}, Clong), 'N', size(A,1), size(A,2), 1.0, A, 1000, pointer(x, 1), 1, 0.0, pointer(y, 1), 1, 1)
```

Getting the OpenBLAS config, there's a lot of space for changes here, as my two test setups return the following:
```
# Slow julia
julia> unsafe_string(ccall(Libdl.dlsym(libopenblas, "openblas_get_config64_"), Cstring, ()))
"OpenBLAS 0.3.17  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=512" 
```

```
# Fast julia
julia> unsafe_string(ccall(Libdl.dlsym(libopenblas, "openblas_get_config64_"), Cstring, ()))
"OpenBLAS 0.3.10  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=32"
```

So my guesses right now are that this is either a regression somewhere from OpenBLAS `0.3.10` -> `0.3.17`, or it's a consequence of `MAX_THREADS` going from `32` -> `512`.

**Comment by giordano** [comment]
> or it's a consequence of MAX_THREADS going from 32 -> 512.

You could do a 0.3.17 build with 32 threads to rule this out (or confirm it)?

**Comment by jaakkor2** [comment]
All these numbers are on Windows, and performance consistently looks like the number of threads is 8.
In the first post above, on Julia nightly, the number of threads is 12 causing the regression.

Seems like the slow performance on Windows is really due to OpenBLAS.

Julia 1.5.4
38.000 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=32"

Julia 1.6.4
36.800 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.10  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott MAX_THREADS=4096"

Julia 1.7.0
38.900 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.13  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=4096"

Then the version from Conda
`C:\Users\jaakkor2\.julia\conda\3\Library\bin\openblas.dll`
 37.600 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=128"

And with the official asset from https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip
38.900 μs (9 allocations: 144 bytes)
"OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64"

In the two last cases, `dgemv_64_`->`dgemv_` and `openblas_get_config64_`->`openblas_get_config`.

**Comment by jaakkor2** [comment]
On my machine with Intel i7-107850H (6 cores) on Windows on Julia 1.8.0-rc1, `LinearAlgebra.BLAS.get_num_threads()`  gives 6, whereas Julia 1.7.3 gives 8.

`using BenchmarkTools, LinearAlgebra; n,m=1000,100;A=rand(n,m); x=rand(m);y=A*x; @btime mul!(y,A,x);`

gives
* 1.8.0-rc1: 24.900 μs (0 allocations: 0 bytes)
* 1.7.3:  35.200 μs (0 allocations: 0 bytes)

The regression is now gone due to number of threads setting.  Still GEMV is 10x slower than MKL, but that is not the issue here.
