### ISSUE TITLE
Tracking issue for updating the `TOML` stdlib with the latest code from the `JuliaLang/TOML.jl` repo

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#42700]
See also: https://github.com/JuliaLang/TOML.jl/issues/36

---

In theory, all of this could be done in a single pull request. However, this would make the diff very difficult to read. So instead I broke it up into multiple smaller pull requests:
- [ ] #42699
- [ ] #42698
- [ ] #42694

**Comment by martinholters** [comment]
If it's just about the diff being difficult to read, sensible commits within one PR would be sufficient.
