### ISSUE TITLE
Sorting Numerics with a non-total order is unstable by default.

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#42713]
This is unfortunate:
```
julia> sort(collect(1:22), by=x->0)
22-element Vector{Int64}:
 12
 21
 20
 19
 18
 17
 16
 15
 14
 13
  1
 11
 10
  9
  8
  7
  6
  5
  4
  3
  2
 22
```
We have
https://github.com/JuliaLang/julia/blob/792c026946af5830c537338ab830abcc78b625e7/base/sort.jl#L658
because we assume that stable and unstable are indistinguishable when sorting numeric data. Unfortunately, this is only true for [total](https://en.wikipedia.org/wiki/Total_order) orderings.

**Comment by simeonschaub** [comment]
This could probably be better documented, but it is the intended behavior. If you want a stable algorithm, you need to explicitly request it:
```julia
julia> sort([1:22;]; by=x->0, alg=Base.DEFAULT_STABLE)
22-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
```
