### ISSUE TITLE
Why does NaN considered different from NaN? This is so wrong.

### ISSUE THREAD

**Issue by Leon6j** [JuliaLang/julia#42734]
julia> NaN == NaN
false

**Comment by Leon6j** [comment]
This question was asked there and I'm just forwarding it here as a bug report, so that the Julia developers can fix this bug. Thanks.

**Comment by KristofferC** [comment]
It is not a bug. Julia follows the IEEE standard for floating-point which says that NaN is not equal to itself, see the table in https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN.

This is also the same in most other programming languages, take Python for example:

```py
>>> float("nan") == float("nan")
False
```

In Julia, use:

```jl
julia> isequal(NaN, NaN)
true

julia> isnan(NaN)
true
```

**Comment by Leon6j** [comment]
Many thanks for the explanation!
