### ISSUE TITLE
Unable to sum `::SparseVector{Num,Int}` s

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#42730]
From https://discourse.julialang.org/t/is-there-a-defined-minimal-interface-for-a-type-to-work-with-sparsearrays/69602/2

```julia
using Symbolics, SparseArrays

@variables a
v = sparsevec([1], [a])
v+v #  throws 
```

**Comment by jlapeyre** [comment]
I can't find this addressed directly in the Symbolics.jl repo. But [this blog post](https://www.stochasticlifestyle.com/useful-algorithms-that-are-not-optimized-by-jax-pytorch-or-tensorflow/) suggests that the behavior of the code in my comment above is desirable for something other than facilitating generic programming (you can read about it there). At any rate, it is a conscious decision. At first glance, I would have said it's better to construct an equation expression with a different function (not `==`), leaving `==` free to follow documented semantics.  At any rate it is still better to clean up `SparseArrays` with reference to standard Julia. If this allows it to work with `Symbolics`, fine. That's a bonus.

**Comment by ViralBShah** [comment]
Should be moved to SparseArrays.jl
