### ISSUE TITLE
Task migration in docs 1.7.0-rc2

### ISSUE THREAD

**Issue by nielsls** [JuliaLang/julia#42767]
The [NEWS file](https://github.com/JuliaLang/julia/blob/v1.7.0-rc2/NEWS.md) states that:

_Tasks can now migrate among threads when they are re-scheduled. Previously, a Task would always run on whichever thread executed it first (#40715)._

But the docs do not seem to be updated accordingly. They still say, that:

_After a task starts running on a certain thread (e.g. via @spawn), it will always be restarted on the same thread after blocking. In the future this limitation will be removed, and tasks will migrate between threads._

I guess the future is now?

**Comment by KristofferC** [comment]
The part in the docs is at https://github.com/JuliaLang/julia/blob/1867b428c630b907428bc477f6cf6429361e79c7/doc/src/manual/multi-threading.md?plain=1#L309-L311

**Comment by nielsls** [comment]
Resolved by #43496
