### ISSUE TITLE
Feature Request: go-like struct composition with splatting syntax?

### ISSUE THREAD

**Issue by AstroFloof** [JuliaLang/julia#42777]
The Go language has this cool feature for struct composition where if you put one struct after another's values, its values are inherited into the other.
```go
type foo1 struct {
    bar   string
}
type foo2 struct {
    baz   string
    foo1  // foo2 now also has the field "bar" inherited from foo1
}
```

This seems like it would fit well into Julia.

My suggested implementation would be:
```julia
struct foo1
    bar::String
end

struct foo2
    baz::String
    foo1...
end
```

Thanks for taking the time to read this! It would be yet another pretty nifty trick that Julia could use.

**Comment by vtjnash** [comment]
If the goal is discussion, I recommend converting this to a Discussion or posting on Discourse, since that is not the general purpose of an issue tracker.

In your example, Julia does not inherit methods (which was the point of the issue I linked as duplicate), only the fields.

**Comment by AstroFloof** [comment]
Oh sweet! I'd forgotten about this but that package is great! I'll close this now in favour of just using that then.

**Comment by mhinsch** [comment]
> Oh sweet! I'd forgotten about this but that package is great! I'll close this now in favour of just using that then.

One thing to keep in mind, though, while the package works well for straightforward use, there are corner cases where it breaks (all of those I have encountered so far seem fixable, though). Plus, using it in combination with `@kwdef` leads to duplicate creation of objects. As far as I can tell fixing this one would require either lifting the behaviour to language level or providing full reflection access to the default values of keyword parameters.
Altogether I think it's a good solution, but having it as a language feature would be much cleaner.
