### ISSUE TITLE
expr((:≔, :⩴, :≕, :≕), _...) input / output do not match as Expr(:(=), _...) does

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#42774]
```julia
using Test
@test :(1 = 2) |> repr == Expr(:(=), 1, 2) |> repr == ":(1 = 2)"
```

but others (reserved) assignment ops are not shown as they are typed, eg in infix form but in prefix one.

```julia
@test :(1 := 2) |> repr == ":($(Expr(:(:=), 1, 2)))"
```

a small annoyance, but one that may easily be fixed by adding them to `expr_infix_wide` @ https://github.com/JuliaLang/julia/blob/v1.6.2/base/show.jl#L1196 (to verify)

SEE
- show_unquoted/5 / elseif (head in expr_infix_any && nargs==2) ... @ https://github.com/JuliaLang/julia/blob/v1.6.2/base/show.jl#L1656SEE
- https://github.com/JuliaLang/julia/issues/31547
- https://github.com/JuliaLang/julia/pull/33694
- https://discourse.julialang.org/t/are-operators-still-supported/68846

**Comment by edith007** [comment]
Hi @JeffBezanson! 👋🏻 
is this something I can get to work on? If so I'd like to get to work on it. 🙇🏻

**Comment by simeonschaub** [comment]
Sure, just go for it! There's no need to ask, people usually just start working on an issue.
