### ISSUE TITLE
Julia v1.7.0-rc2 is broken on FreeBSD

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#42781]
```
$ ./julia-1.7.0-rc2/bin/julia
ERROR: Unable to load dependent library /usr/home/alex/julia-1.7.0-rc2/bin/../lib/julia/libjulia-internal.so.1
Message:Shared object "libz.so.1" not found, required by "libLLVM-12jl.so"

$ ./julia-1.7.0-rc1/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-rc1 (2021-09-12)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```
Seems this issue had been noted prior but the FreeBSD test failures on master tricked us: https://github.com/JuliaLang/julia/pull/42535#issuecomment-938697534. (AFAIK, FreeBSD tests should be green on 1.6 and 1.7, just not master.)

**Comment by ararslan** [comment]
I've confirmed locally that reverting all of the commits associated with #42535 results in a working FreeBSD 12 build that passes all tests.

**Comment by DilumAluthge** [comment]
@ararslan Can you try building the `backports-release-1.7` branch and see if the bug is fixed on that branch?

**Comment by ararslan** [comment]
I have confirmed that it is. I'm hitting https://github.com/JuliaLang/julia/issues/41943 in the tests though. :confused:
