### ISSUE TITLE
length(::TwicePrecision) not defined leads to broadcasting failing

### ISSUE THREAD

**Issue by imyxh** [JuliaLang/julia#42857]
Hi, I ran into what seems to be a bug(?) while implementing a simple Euler's method solution generator for systems of differential equations. At some point in my code I had written something like `dfs[i-1,:] .* trange.step` and I ran into this bug.

Simple reproduction:

```julia
julia> [1, 2] .* (0:1:2).step
2-element Vector{Int64}:
 1
 2

julia> [1, 2] .* (0:0.5:2).step
ERROR: MethodError: no method matching length(::Base.TwicePrecision{Float64})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at /build/julia/src/julia-1.6.3/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/adjtrans.jl:195
  length(::Base.OneTo{T}) where T<:Int64 at range.jl:588
  ...
Stacktrace:
 [1] _similar_for(c::UnitRange{Int64}, #unused#::Type{Float64}, itr::Base.TwicePrecision{Float64}, #unused#::Base.HasLength)
   @ Base ./array.jl:575
 [2] _collect(cont::UnitRange{Int64}, itr::Base.TwicePrecision{Float64}, #unused#::Base.HasEltype, isz::Base.HasLength)
   @ Base ./array.jl:608
 [3] collect(itr::Base.TwicePrecision{Float64})
   @ Base ./array.jl:602
 [4] broadcastable(x::Base.TwicePrecision{Float64})
   @ Base.Broadcast ./broadcast.jl:682
 [5] broadcasted(::Function, ::Vector{Int64}, ::Base.TwicePrecision{Float64})
   @ Base.Broadcast ./broadcast.jl:1313
 [6] top-level scope
   @ REPL[146]:1
```

Let me know if there's anything I can do to help. Thank you!

**Comment by imyxh** [comment]
Fix: @ScottPJones suggested that "Line 174 in twiceprecision.jl needs `<: Number` added"

We have `convert(::Number)` so that should fix things.

**Comment by longemen3000** [comment]
maybe `Real` instead? are there any cases where a non-real step is used?

**Comment by imyxh** [comment]
> maybe `Real` instead? are there any cases where a non-real step is used?

Interesting, I had assumed that complex steps would be okay, but there I've discovered something else:

```julia
julia> (1:0.1:2) .* im
0.0 + 1.0im:0.0 + 0.1im:0.0 + 2.0im

julia> 0.0 + 1.0im:0.0 + 0.1im:0.0 + 2.0im
ERROR: MethodError: no method matching isless(::ComplexF64, ::ComplexF64)
Closest candidates are:
  isless(::Any, ::Missing) at missing.jl:88
  isless(::Missing, ::Any) at missing.jl:87
Stacktrace:
 [1] <(x::ComplexF64, y::ComplexF64)
   @ Base ./operators.jl:279
 [2] >(x::ComplexF64, y::ComplexF64)
   @ Base ./operators.jl:305
 [3] steprange_last
   @ ./range.jl:226 [inlined]
 [4] StepRange
   @ ./range.jl:208 [inlined]
 [5] StepRange
   @ ./range.jl:263 [inlined]
 [6] _colon
   @ ./range.jl:46 [inlined]
 [7] (::Colon)(start::ComplexF64, step::ComplexF64, stop::ComplexF64)
   @ Base ./range.jl:40
 [8] top-level scope
   @ REPL[219]:1
```

Are complex ranges not supported?

**Comment by timholy** [comment]
`TwicePrecision` is an internal type used to magically hit endpoints even in the face of floating point roundoff. It shouldn't "escape," and so you should consider the fields of ranges as private data. Please use `[1, 2] .* step(0:0.5:2)`.

And yes, complex numbers aren't ordered. With regular ranges, you can do `0:5:7` and it works despite the fact that `7` isn't a multiple of 5. So what should `0+0im : 1+1im : 7` return?

**Comment by timholy** [comment]
I'll reopen this because I see it's not clear in the docs.

**Comment by vtjnash** [comment]
Some complex ranges do happen to work, such as linrange, since it defines the length to be a real number.
