### ISSUE TITLE
`sortby` keywords not supported in `eigvals()` with `Symmetric` matrices

### ISSUE THREAD

**Issue by Weiyu-USTC** [JuliaLang/julia#42865]
I am trying to sort the eigenvalues of a symmetric matrix in a different order. Then with the `Symmetric` type of matrices, the keyword `sortby` can work for the function `eigen()` but not `eigvals()`. An example:

```Julia
M = Symmetric([1 2 3; 2 3 4; 3 4 5])
eigen(M, sortby = x -> -x)
```

The above one-line code can work and output the eigens in descending order:

> Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
  9.623475382979782
 -7.771561172376096e-16
 -0.6234753829797993
vectors:
3×3 Matrix{Float64}:
 0.38509    0.408248   0.827671
 0.55951   -0.816497   0.142414
 0.733931   0.408248  -0.542844

However, for 
```Julia
M = Symmetric([1 2 3; 2 3 4; 3 4 5])
eigvals(M, sortby = x -> -x)
```

an error shows up:
>MethodError: no method matching eigvals!(::LinearAlgebra.Symmetric{Float64, Matrix{Float64}}; sortby=var"#60#62"{typeof(-)}(-))

**Comment by Chandu-4444** [comment]
Can you please format the code a bit more elegantly? 

You can use : 
\```Julia
print("Hello world!")
\```
This formats to:
```Julia
print("Hello world!")
```

**Comment by Weiyu-USTC** [comment]
> Can you please format the code a bit more elegantly?
> 
> You can use : ```Julia print("Hello world!") ``` This formats to:
> 
> ```julia
> print("Hello world!")
> ```

Thanks, done.
