### ISSUE TITLE
Use `safe_isfile` in `isfile_casesensitive` to improve relocatability of sysimages

### ISSUE THREAD

**Issue by ven-k** [JuliaLang/julia#42876]
[isfile_casesensitive](https://github.com/JuliaLang/julia/blob/master/base/loading.jl#L10-L81) relies on `isfile` which throws error if the path can't be found. Wouldn't it be better to use a `safe_isfile` which would treat the non-existent paths same as the faulty ones
```
function safe_isfile(file)
    return try
        isfile(file)
    catch err
        err isa IOError || rethrow()
        false
    end
end
```
like [here in RelocatableFolders](https://github.com/JuliaPackaging/RelocatableFolders.jl/blob/main/src/RelocatableFolders.jl#L7) and [here in `current_project` when no `dir` is specified](https://github.com/JuliaLang/julia/blob/dc627e7bec000fdae5c32d34340c167303b193c3/base/initdefs.jl#L189-L196)

The direct use would be while **creating scratchspaces on relocated sysimage**.
 The paths that include `@__DIR__` can be made relocatable by using `RelocatableFolders.@path`. But
The `Scratch.get_scratch!` internally [calls](https://github.com/JuliaPackaging/Scratch.jl/blob/df4d65620ea65816ba4c2f586d3d790db3dc99c6/src/Scratch.jl#L217) `track_scratch_access` which [calls](https://github.com/JuliaPackaging/Scratch.jl/blob/df4d65620ea65816ba4c2f586d3d790db3dc99c6/src/Scratch.jl#L120) Base.current_project, which [calls](https://github.com/JuliaLang/julia/blob/b2d15f05698ba78ac2493ec2624a0ee1c9a042a3/base/initdefs.jl#L180) `isfile_casesensitive` and that uses `isfile`.
This leads to error messages like:
```
ERROR: IOError: stat("<non-existent-package-path-after-relocating-the-sysimage>/src/JuliaProject.toml"): permission denied (EACCES)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:97 [inlined]
  [2] stat(path::String)
    @ Base.Filesystem ./stat.jl:69
  [3] isfile
    @ ./stat.jl:311 [inlined]
  [4] isfile_casesensitive
    @ ./loading.jl:9 [inlined]
  [5] current_project(dir::String)
    @ Base ./initdefs.jl:181
  [6] (::Scratch.var"#find_project_file#2")(pkg_uuid::Base.UUID)
    @ Scratch <non-existent-package-path-after-relocating-the-sysimage>/src/Scratch.jl:120
  [7] track_scratch_access(pkg_uuid::Base.UUID, scratch_path::String)
    @ Scratch <non-existent-package-path-after-relocating-the-sysimage>/src/Scratch.jl:139
  [8] get_scratch!(parent_pkg::Module, key::String, calling_pkg::Module)
    @ Scratch <non-existent-package-path-after-relocating-the-sysimage>/src/Scratch.jl:217
  [9] get_scratch!
    @ <non-existent-package-path-after-relocating-the-sysimage>/src/Scratch.jl:205 [inlined]
 [10] getpath(f::RelocatableFolders.Path)
    @ RelocatableFolders <non-existent-package-path-after-relocating-the-sysimage>/RelocatableFolders/2eEye/src/RelocatableFolders.jl:78
 [11] String
    @ <non-existent-package-path-after-relocating-the-sysimage>/RelocatableFolders/2eEye/src/RelocatableFolders.jl:74 [inlined]
 [12] cconvert
    @ ./c.jl:197 [inlined]
 [13] cd(dir::RelocatableFolders.Path)
    @ Base.Filesystem ./file.jl:84
```

An easy workaround for this would be wrapping `track_access_package` in Scratch.jl with a try/catch block. But this would make it improssible for GC to track these scratchspaces.

Secondly, as we move towards making Julia (add sysimages) more relocatable I wanted to know if this is something that can go to base Julia. (Would be happy to open a PR if so)

**Comment by KristofferC** [comment]
I think it is fine to add this to loading.jl since an error is not really useful for the functions being called there.

**Comment by stevengj** [comment]
> `isfile` which throws error if the path can't be found

I'm confused, under what circumstances does `isfile` throw an error for a non-existent path?
```jl
julia> isfile("/this/path/doesn't/exist")
false
```

**Comment by KristofferC** [comment]
Whenever `stat` fails on such a directory. It's a very common source of bugs. Python returns false in cases like that https://docs.python.org/3/library/os.path.html#os.path.exists:

> On some platforms, this function may return False if permission is not granted to execute os.stat() on the requested file, even if the path physically exists.

**Comment by stevengj** [comment]
I see, then isn't the proposed functionality in this issue more of an `unsafe_isfile` than a "safe" `isfile`?

**Comment by KristofferC** [comment]
It protects you from the buggy behavior that no one wants so I would say it is a safer version than the original one.
