### ISSUE TITLE
Certain commands that should be working are causing the terminal to crash, full details of an example in report. The same or similar has happened to me on other occasions with other files and commands.

### ISSUE THREAD

**Issue by nr4418** [JuliaLang/julia#42893]
Quite new to julia, using vs code for the most part. I've encountered this issue or similar when I try to run certain commands. I ran the following file in the REPL
`
using ApproxFun, Plots, SingularIntegralEquations
x = Fun(0 .. 1)
f = x

a = cauchy(f,5+2im)
`
Which caused the terminal to crash with exit code 1. The exact text was:

`
The terminal process "julia.exe '-i', '--banner=no', '--project=C:\Users\nicrd\.julia\environments\v1.6', 'c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-ff3868b3-25df-437b-b9f8-3a9e3359ed35', '\\.\pipe\vsc-jl-cr-d34f6402-2c41-4504-8711-23b548162907', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'DEBUG_MODE=false'" terminated with exit code: 1.
`

I ran the same file in the debugger, the report was:

`
Invalid instruction at 0a63240d: 0xc5, 0xf8, 0x77, 0xeb, 0x02, 0xdd, 0xd8, 0x8d, 0x65, 0xf4, 0x5b, 0x5e, 0x5f, 
0x5d, 0xc3

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0xa63240d -- _ft_scale_columns_tb_eigen_FMM at C:\Users\nicrd\.julia\artifacts\42ba55a514f374aee88ffa6183988fdd2c2d7fd9\bin\libfasttransforms.dll (unknown line)
in expression starting at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\debugger\run_debugger.jl:9
_ft_scale_columns_tb_eigen_FMM at C:\Users\nicrd\.julia\artifacts\42ba55a514f374aee88ffa6183988fdd2c2d7fd9\bin\libfasttransforms.dll (unknown line)
_ft_plan_chebyshev_to_jacobi at C:\Users\nicrd\.julia\artifacts\42ba55a514f374aee88ffa6183988fdd2c2d7fd9\bin\libfasttransforms.dll (unknown line)
##compiledcall#257 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\optimize.jl:382
unknown function (ip: 2daf0180)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2237 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
jl_f__call_latest at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:714
jl_fptr_args at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2006
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:670
jl_f__apply_iterate at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:678
#invokelatest#2 at .\essentials.jl:708
jl_fptr_args at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2006
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:670
jl_f__apply_iterate at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:678
invokelatest at .\essentials.jl:706
jl_fptr_args at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2006
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:670
jl_f__apply_iterate at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:678
bypass_builtins at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:178
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:202
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:474
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:474
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:561
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30 [inlined]
#evaluate_call_recurse!#59 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:240
evaluate_call_recurse! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:201 [inlined]
eval_rhs at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:400
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:556
step_expr! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\interpret.jl:611
finish! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:14
finish_and_return! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:30
unknown function (ip: 2dae846f)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
finish_stack! at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:60
unknown function (ip: 2dae83df)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
#debug_command#83 at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:474
debug_command at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\JuliaInterpreter\src\commands.jl:416
unknown function (ip: 2dae6ecf)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
jl_f__call_latest at /cygdrive/c/buildbot/worker/package_win32/build/src\builtins.c:714
#invokelatest#2 at .\essentials.jl:708 [inlined]
invokelatest at .\essentials.jl:706 [inlined]
our_debug_command at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\DebugAdapter\src\debugger_core.jl:67
startdebug at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\DebugAdapter\src\packagedef.jl:106
startdebugger at c:\Users\nicrd\.vscode\extensions\julialang.language-julia-1.4.3\scripts\packages\VSCodeDebugger\src\VSCodeDebugger.jl:38
unknown function (ip: 2da8334d)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2237 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
do_call at /cygdrive/c/buildbot/worker/package_win32/build/src\interpreter.c:115
eval_value at /cygdrive/c/buildbot/worker/package_win32/build/src\interpreter.c:204
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win32/build/src\interpreter.c:155 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win32/build/src\interpreter.c:558
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win32/build/src\interpreter.c:670
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win32/build/src\toplevel.c:877
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win32/build/src\toplevel.c:825
jl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win32/build/src\toplevel.c:886 [inlined]
jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win32/build/src\toplevel.c:929
eval at .\boot.jl:360 [inlined]
include_string at .\loading.jl:1116
jl_fptr_args at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2006
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
_include at .\loading.jl:1170
include at .\Base.jl:386
jl_fptr_args at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2006
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
exec_options at .\client.jl:285
_start at .\client.jl:485
_jfptr__start_44729 at C:\Users\nicrd\AppData\Local\Programs\Julia-1.6.3\lib\julia\sys.dll (unknown line)      
_jl_invoke at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2218 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win32/build/src\gf.c:2419
jl_apply at /cygdrive/c/buildbot/worker/package_win32/build/src\julia.h:1703 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win32/build/src\jlapi.c:560
repl_entrypoint at /cygdrive/c/buildbot/worker/package_win32/build/src\jlapi.c:702
jl_load_repl at /cygdrive/c/buildbot/worker/package_win32/build/cli\loader_lib.c:214
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win32/build/cli\loader_exe.c:51
timeGetTime at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
Allocations: 72463163 (Pool: 72458719; Big: 4444); GC: 60

Julia debuggee finished. Press ENTER to close this terminal.

`

In case it is my system, see:

`
julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)        
  CPU: Snapdragon (TM) 850 @ 2.96 GHz   
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, generic)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
`

**Comment by vtjnash** [comment]
> Windows (i686-w64-mingw32)
> CPU: ARM (Snapdragon 850)

That is quite a combination. Do we know what x86 chipset it is attempting to emulate?

(https://defuse.ca/online-x86-assembler.htm#disassembly2 thought this assembly was gibberish, but LLVM says it is AVX)
```
echo '0xc5, 0xf8, 0x77, 0xeb, 0x02, 0xdd, 0xd8, 0x8d, 0x65, 0xf4, 0x5b, 0x5e, 0x5f, 0x5d, 0xc3' | ./usr/tools/llvm-mc -disassemble -triple=i686-w64-mingw32
        .text
        vzeroupper
        jmp     2
        fstp    %st(0)
        leal    -12(%ebp), %esp
        popl    %ebx
        popl    %esi
        popl    %edi
        popl    %ebp
        retl
```

I don't think Julia normally requires AVX support (only SSE), but it seems like libfasttransforms.dll may be incorrectly compiled to expect it.

**Comment by vtjnash** [comment]
Ah, yes, apparently the compile flags are written to explicitly force it to build with them, even if not supported by the target cpu, per https://github.com/JuliaPackaging/Yggdrasil/pull/230 at  https://github.com/JuliaPackaging/Yggdrasil/blob/438e2744e2b98ba00af99a2501e5c3e9d315729d/F/FastTransforms/build_tarballs.jl#L14-L24

**Comment by nr4418** [comment]
It's an ARM chipset, so I tend to be blocked from downloading quite a few apps, but it can run 32-bit programmes through emulation in the architecture. The version of Julia I have downloaded, as well as my copy of vs code, are both downloaded a 32-bit programmes.

**Comment by vtjnash** [comment]
We should move this to Yggdrasil, since it is a bug there with FastTransforms. I don't have permissions to transfer this issue directly though.

**Comment by vchuravy** [comment]
> We should move this to Yggdrasil, since it is a bug there with FastTransforms. I don't have permissions to transfer this issue directly though.

> You can only transfer issues between repositories owned by the same user or organization account.

**Comment by nr4418** [comment]
I can't transfer it either. Though I will copy and paste the issue over there, and I shall add your comments etc...
