### ISSUE TITLE
Use FlexiBLAS to pick a BLAS and LAPACK at runtime.

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#4290]
It would be neat to attempt switching BLAS backends by creating a `libblas.{so,dylib,dll}` symlink in `JULIA_HOME/lib/julia` and linking to that instead of directly to a system library or `OpenBLAS`.  Using this method, we could then select a BLAS library to dynamically link against at startup time.  (Unfortunately, I don't think this would allow us to switch BLAS implementations after we've already started up, but correct me if there's some strange dynamic "unlinking" magic I don't know about!)

A good way to test this is to install `ATLAS`, `OpenBLAS` and Reference BLAS on a Linux computer and symlink to one of them in the Julia build directory, while overriding the Makefile variables for which BLAS library to use to point to that symlink.  If you can change the symlink to point to different BLAS implementations, we have a winner.

There's some added complexity involved with LAPACK, to start with I think we can just always compile our own and have it link to our symlinked BLAS implementation.  If whoever wants to tackle this happens to have access to an MKL installation, that would be great to test as well.

**Comment by staticfloat** [comment]
I'm closing this as, between the dimensions of specialty BLAS calls, ILP64, and different LAPACK implementations, it's best to not pull the rug out from under Julia by changing the linked BLAS library willy-nilly.  We have good support for building against different BLAS implementations, let's leave it at that until we have a compelling use case for something else.

**Comment by tkelman** [comment]
At a minimum it requires rebuilding the system image because the threading API's vary quite a bit between different implementations. Now if rebuilding the system image incrementally didn't take quite so long, that would be satisfactory I think. I've written a few helper routines somewhere for doing this.

**Comment by gramian** [comment]
Maybe the FlexiBLAS project ( https://github.com/mpimd-csc/flexiblas ) helps with this as well as issue #30707 .

**Comment by ViralBShah** [comment]
This looks nice. We'll still need to rebuild the system image like we do in MKL.jl, when we switch, but this would allow a more general solution.

**Comment by ViralBShah** [comment]
cc @andreasnoack

**Comment by ViralBShah** [comment]
@gramian Does FlexiBLAS work with Windows too? I have been reading a bit more about it - and I always wished something like this existed. Thanks for putting it together. We probably want to get it working in BinaryBuilder and then bring it into the Julia source build.

**Comment by gramian** [comment]
Hi,
first of all, I am a mere contributor, and I guess we should add the lead developer @grisuthedragon to this discussion.
As far as I know, FlexiBLAS is not compatible to Windows, only to Linux and likely BSD. I am not sure if the WSL is changing the game in this regard.
In response to the LAPACK question:
FlexiBLAS provides the reference LAPACK functions as a fall-back in case the selected LAPACK implementation does not provide the called function. So, if for example MKL is set as FlexiBLAS backend, all MKL LAPACK functions are used.
If this can be misunderstood, we will update the README in this regard.
@grisuthedragon please correct me or expand if necessary.

**Comment by StefanKarpinski** [comment]
We can't rely on WSL on Windows — anything we use has to work on Windows natively. However, BinaryBuilder allows us to cross-compile from Linux to any other platform, which can often be easier than getting something to compile on Windows using MSVC. So it might not be that hard to BinaryBuild FlexiBLAS for all platforms.

**Comment by ViralBShah** [comment]
Things are going to also get a bit complicated on Macs with the new processors and the current state of Fortran.

**Comment by ViralBShah** [comment]
Various flexiblas issues opened as part of my experimentation to see if we can adopt it: mpimd-csc/flexiblas#9, mpimd-csc/flexiblas#10, mpimd-csc/flexiblas#11

**Comment by ViralBShah** [comment]
With LBT, we now have a solution in place for 1.7 onwards.
