### ISSUE TITLE
Julia 1.7.0-rc2 and Unicode

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#42917]
I am using Julia 1.7.0-rc2 on Mac Monterey (Intel). For some reason, Julia no longer responds when I do the following in the REPL
```julia
α = 1
1 + α
```
Not sure if this is linked to https://github.com/JuliaLang/julia/issues/42875

**Comment by staticfloat** [comment]
Can you show the output of `using Libdl; filter(f -> occursin("/usr/local", f), Libdl.dllist())`?  That should tell us if #42875 is related.

**Comment by matthieugomez** [comment]
Looks like it is.
```julia
using Libdl; filter(f -> occursin("/usr/local", f), Libdl.dllist())
1-element Vector{String}:
 "/usr/local/Cellar/pcre2/10.34/lib/libpcre2-8.0.dylib"
```
 I'm closing the issue then.
