### ISSUE TITLE
Printing objects with `print(e::Error)`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#42924]
Motivated by [this Discourse post](https://discourse.julialang.org/t/error-message-prints-entire-dataframe/70883/2) and originall filed in DataFrames.jl [here](https://github.com/JuliaData/DataFrames.jl/issues/2925). 

When users do `try...catch` and print the captured error, Julia prints the entire captured object. 

```
julia> function foo(x::Int)
           1
       end;

julia> x = [1, 2, 3];

julia> try 
           foo(x)
       catch e
           println(e)
       end
MethodError(foo, ([1, 2, 3],), 0x00000000000073cb)
```

If you make `x` a very big vector, this can fill up an entire screen. 

Perhaps we should change the default printing to be more like the default printing for arbitrary structs. 

```
julia> struct X{T}
           x::T
       end;

julia> t = X(rand(10_000))
X{Vector{Float64}}([0.1507616803819849, 0.2518347044992346, 0.5285708829554654, 0.6319099010428701, 0.8761741799032663, 0.5184622021209326, 0.4917931049956563, 0.789505121215861, 0.958371752298314, 0.4252151136065152  …  0.8441319114077026, 0.1686837918134807, 0.6160132113960224, 0.1645091543893218, 0.9826459171076514, 0.30966360113886493, 0.7084033713812063, 0.776956747153762, 0.6623796714492838, 0.47224655898049317])
```

Thank you!

**Comment by fredrikekre** [comment]
You can use `showerror` for pretty printing of exceptions:
```
julia> try; foo([1, 2, 3, 4, 5,]); catch e; showerror(stdout, e); end
MethodError: no method matching foo(::Vector{Int64})
Closest candidates are:
  foo(::Int64) at REPL[2]:1
```

**Comment by pdeffebach** [comment]
Thanks. 

Do you think we should still change the default printing or suggest people use `showerror`?

Maybe improve the documentation of `try...catch` [here](https://docs.julialang.org/en/v1/base/base/#try)?

**Comment by JeffBezanson** [comment]
Changing the default printing would be very breaking, as it changes the output of every program that prints things. I also don't believe the default printing should omit data in any case.

Agree that the docs for try/catch should mention showerror, and also how to show a backtrace.

Another good option is to call `display(x)`, which will show to the REPL if it is available, which will use the REPL formatting settings, which includes limited output.

**Comment by pdeffebach** [comment]
Ah you are correct, `display` fixes this. I thought I had tested it earlier and `display` had printed too much, but I was wrong. 

I think it's fine, then. We should just update the docs to mention `showerror`.

**Comment by vtjnash** [comment]
`println(current_exceptions())` now works as expected / requested here
