### ISSUE TITLE
Error using pyplot

### ISSUE THREAD

**Issue by senji77** [JuliaLang/julia#42934]
Hi guys, I tried to run a simple plot using pyplot. But I got the below error messages. Does anyone know about this issue?

julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)

julia> using PyPlot

julia> plot(rand(10));show()

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffa0bf887f7 -- FT_Trace_Set_Default_Level at C:\Users\senji\.julia\conda\3\Library\bin\freetype.dll (unknown line)
in expression starting at none:0
FT_Trace_Set_Default_Level at C:\Users\senji\.julia\conda\3\Library\bin\freetype.dll (unknown line)
FT_Trace_Set_Default_Level at C:\Users\senji\.julia\conda\3\Library\bin\freetype.dll (unknown line)
FT_Load_Glyph at C:\Users\senji\.julia\conda\3\Library\bin\freetype.dll (unknown line)
unknown function (ip: 00007ffa18504de1)
PyInit_ft2font at C:\Users\senji\.julia\conda\3\lib\site-packages\matplotlib\ft2font.cp39-win_amd64.pyd (unknown line)
PyArg_CheckPositional at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyType_GenericAlloc at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyType_GenericAlloc at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
Py_NewReference at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyFunction_Vectorcall at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyType_GenericAlloc at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyVectorcall_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyInit_QtCore at C:\Users\senji\.julia\conda\3\lib\site-packages\PyQt5\QtCore.pyd (unknown line)
PyInit_QtCore at C:\Users\senji\.julia\conda\3\lib\site-packages\PyQt5\QtCore.pyd (unknown line)
PyInit_QtCore at C:\Users\senji\.julia\conda\3\lib\site-packages\PyQt5\QtCore.pyd (unknown line)
PyInit_QtCore at C:\Users\senji\.julia\conda\3\lib\site-packages\PyQt5\QtCore.pyd (unknown line)
QObject::event at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
QApplicationPrivate::notify_helper at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Widgets.dll (unknown line)
QApplication::notify at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Widgets.dll (unknown line)
unknown function (ip: 00007ff9dea569d4)
QCoreApplication::notifyInternal2 at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
QCoreApplicationPrivate::sendPostedEvents at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
qt_plugin_query_metadata at C:\Users\senji\.julia\conda\3\Library\plugins\platforms\qwindows.dll (unknown line)
QEventDispatcherWin32::processEvents at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
CallWindowProcW at C:\Windows\System32\USER32.dll (unknown line)
DispatchMessageW at C:\Windows\System32\USER32.dll (unknown line)
QEventDispatcherWin32::processEvents at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
qt_plugin_query_metadata at C:\Users\senji\.julia\conda\3\Library\plugins\platforms\qwindows.dll (unknown line)
QCoreApplication::processEvents at C:\Users\senji\.julia\conda\3\Library\bin\Qt5Core.dll (unknown line)
unknown function (ip: 00007ff9f9a50192)
PyArg_CheckPositional at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
PyObject_Call at C:\Users\senji\.julia\conda\3\python39.dll (unknown line)
macro expansion at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\exception.jl:95 [inlined]
#107 at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:43 [inlined]
disable_sigint at .\c.jl:458 [inlined]
__pycall! at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:42 [inlined]
_pycall! at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:29
_pycall! at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:11 [inlined]
#pycall#112 at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:80 [inlined]
pycall at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\pyfncall.jl:80 [inlined]
#3 at C:\Users\senji\.julia\packages\PyCall\3fwVL\src\gui.jl:151
macro expansion at .\asyncevent.jl:252 [inlined]
#583 at .\task.jl:411
unknown function (ip: 0000000056f8f383)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1703 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:833
Allocations: 7317493 (Pool: 7314727; Big: 2766); GC: 10

**Comment by KristofferC** [comment]
I would open an issue on the PyPlot repo (https://github.com/JuliaPy/PyPlot.jl). It is unlikely this is an issue with Julia itself.
