### ISSUE TITLE
Show `Tuple{:A,:B}` displays as `Tuple{A,B}` on 1.7

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#42931]
A `Tuple` with symbol contents no longer displays the contents as symbols with `show`, but as variable names - without the colon. `Val` still prints symbols with colons.

Julia 1.6:
```julia
julia> Tuple{:A,:B}
Tuple{:A, :B}

julia> Val{:A}
Val{:A}
```

Julia 1.7
```julia
julia> Tuple{:A,:B}
Tuple{A, B} # << This has no colons

julia> Val{:A}
Val{:A}
```

Probably we want the 1.6 behavior?

This is happening on both rc1 and rc2. It likely occurred with the new [`show_typeparams`](https://github.com/JuliaLang/julia/blob/master/base/show.jl#L604-L648) method.

**Comment by inkydragon** [comment]
master
https://github.com/JuliaLang/julia/blob/236523ffc2b0493e8e519a721ec030b7c3a64f83/base/show.jl#L998-L1000

v1.6.3
https://github.com/JuliaLang/julia/blob/ae8452a9e0b973991c30f27beb2201db1b0ea0d3/base/show.jl#L925-L931

```
julia> show(stdout, Tuple{:A,:B})
Tuple{A, B}
julia> join(stdout, Tuple{:A,:B}.parameters, ", ")
A, B
julia> join(stdout, [:A, :B], ", ")
A, B

julia> print(:a)
a
julia> show(stdout, :a)
:a
```

**Comment by simeonschaub** [comment]
Yes, that should be using `repr` instead of `string` for printing parameters. @inkydragon Want to make a PR?
