### ISSUE TITLE
Level 1 BLAS functions (except for `dot`) dont handle inputs with negetive stride correctly

### ISSUE THREAD

**Issue by N5N3** [JuliaLang/julia#42948]
Similar to #30765.
An eazy example:
```julia
julia> a = collect(1.0:5.0)
5-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0

julia> v = view(a, 3:-1:1)
3-element view(::Vector{Float64}, 3:-1:1) with eltype Float64:
 3.0
 2.0
 1.0

julia> BLAS.nrm2(v)
7.0710678118654755

julia> BLAS.nrm2(collect(v))
3.7416573867739413
```

**Comment by oscardssmith** [comment]
is it worth keeping level one blas around? I don't think it's faster than regular broadcasting...

**Comment by N5N3** [comment]
At present, `norm(::StridedVector, 1)` and `norm(::StridedVector, 2)` call `BLAS.asum` and `BLAS.nrm2` for long enough inputs (and return wrong result for negetive stride).
So we'd better to ensure correctness?

**Comment by sostock** [comment]
Duplicate of #39836.
