### ISSUE TITLE
Regex match that shouldn't be a match

### ISSUE THREAD

**Issue by rjdverbeek-tud** [JuliaLang/julia#42952]
I did the following regex match:

```
r = r"aa"
b = "aaa"
m = match(r,b)
````

The output is:
RegexMatch("aa")

Which should be:
nothing

(When I test this in regex101.com I get the correct result.)

Julia v1.6.3 / Windows 10

**Comment by fredrikekre** [comment]
Why shouldn't it match? Same happens here: https://regex101.com/r/cAd20s/1

**Comment by rjdverbeek-tud** [comment]
Don't send in issues to late in the evening...
