### ISSUE TITLE
Are channels thread safe? Please answer this question in Documentation clearly. 

### ISSUE THREAD

**Issue by benibilme** [JuliaLang/julia#42974]
Hello, 

I was digging the usage of task, async, synch at Julia Discord  [Task&Threads Question](https://discourse.julialang.org/t/sync-is-not-working/70846). One of replies stated `Although you have to be cautious when communicating between threads using channels. They are not threadsafe and although the official Julia docs are not very clear on this topic, it seems that using channels should be reserved for asynchronous programming using @async only.` which really surprised me.

Please make this issue clear in the documentation.

If the comment is indeed really correct, by nature aren't the Channels  supposed to be thread safe? Aren't they solely created for the minimizing the complexity thread programming. Aren't those like Erlang like structures?

**Comment by vtjnash** [comment]
Channels have been fully thread safe for a couple years now

**Comment by benibilme** [comment]
It would be better to state that channel thread safe firmly in the documentation. I do not remember reading it. I took it for granted. However, it would be better to state in the documentation clearly.
