### ISSUE TITLE
hcat/vcat/hvcat bug 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#42989]
The following simple matrix construction fails (joint finding with John Verzani [#364](https://github.com/JuliaMath/Polynomials.jl/issues/365)):

```
julia> using LinearAlgebra

julia> [1 2; I]
ERROR: ArgumentError: number of columns of each array must match (got (2, 1))
Stacktrace:
 [1] _typed_vcat(#unused#::Type{Any}, A::Tuple{Matrix{Any}, Matrix{Any}})
   @ Base .\abstractarray.jl:1553
 [2] typed_vcat(::Type{Any}, ::Matrix{Any}, ::Matrix{Any})
   @ Base .\abstractarray.jl:1567
 [3] typed_hvcat(::Type{Any}, ::Tuple{Int64, Int64}, ::Int64, ::Vararg{Any, N} where N)
   @ Base .\abstractarray.jl:1957
 [4] hvcat(::Tuple{Int64, Int64}, ::Int64, ::Vararg{Any, N} where N)
   @ Base .\abstractarray.jl:1932
 [5] top-level scope
   @ REPL[9]:1
```
but [[1] [2]; I] and [[1 2]; I] work correctly:
```
julia> [[1] [2]; I]
3×2 Matrix{Int64}:
 1  2
 1  0
 0  1

julia>  [[1 2]; I]
3×2 Matrix{Int64}:
 1  2
 1  0
 0  1
```
I think, a simple fix would be to replace line 393 of `LinearAlgebra.UniformScaling` 
`promote_to_arrays_(n::Int, ::Type, a::Number) = a`
with
`promote_to_arrays_(n::Int, ::Type, a::Number) = [a]`

**Comment by ViralBShah** [comment]
Can you submit a PR? Seems like it would be good to fix.

**Comment by dkarrasch** [comment]
> I think, a simple fix would be to replace line 393 of `LinearAlgebra.UniformScaling`
> `promote_to_arrays_(n::Int, ::Type, a::Number) = a`
> with
> `promote_to_arrays_(n::Int, ::Type, a::Number) = [a]`

That was my very first attempt in the extension of `*cat` to numbers, but was considered unfortunate because it creates an (unnecessary) array for each number... which gets eventually included in the concatenated matrix. The issue seems to be that the size of the uniform scaling is deduced incorrectly?

**Comment by martinholters** [comment]
Fixed on master?
```julia
julia> [1 2; I]
3×2 Matrix{Int64}:
 1  2
 1  0
 0  1
```

**Comment by dkarrasch** [comment]
> Fixed on master?
> 
> ```julia
> julia> [1 2; I]
> 3×2 Matrix{Int64}:
>  1  2
>  1  0
>  0  1
> ```

True. I thought https://github.com/JuliaLang/julia/commit/18f2f9fabf638b108a3f522bdb9162f7929bd869 might have been included earlier, but it's going to be released with v1.8.

**Comment by andreasvarga** [comment]
The following wrong outputs are hopefully also fixed:
```
julia> [1 I]
1×2 Matrix{Any}:
 1  UniformScaling{Bool}(true)

julia> [1; I]
2-element Vector{Any}:
 1
  UniformScaling{Bool}(true)

julia> [1 1; 1 I]
2×2 Matrix{Any}:
 1  1
 1   UniformScaling{Bool}(true)
```

**Comment by martinholters** [comment]
Yes:
```julia
julia> [1 I]
1×2 Matrix{Int64}:
 1  1

julia> [1; I]
2×1 Matrix{Int64}:
 1
 1

julia> [1 1; 1 I]
2×2 Matrix{Int64}:
 1  1
 1  1
```
