### ISSUE TITLE
Slow compilation of element-wise function on NTuple

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaLang/julia#42982]
Here is a minimum reproducible example:
```
julia> x = randn(5000);

julia> y = (x...,);

julia> @time float.(y);
 46.906307 seconds (34.33 M allocations: 2.370 GiB, 1.51% gc time, 100.00% compilation time)

julia> @time float.(y);
  0.000029 seconds (3 allocations: 117.375 KiB)
```

For larger tuples, the compilation crashes (with `x = randn(10000)`, my machine freezes).  This seems to happen for any function, not just `float`. Version info:
```
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)
```
Please also see [this related thread on Julia Discourse](https://discourse.julialang.org/t/splatting-a-vector-into-hypot/71049). Thanks!

**Comment by KristofferC** [comment]
This is known and there are already a few similar issues open, https://github.com/JuliaLang/julia/issues/38364. For now the solution is to not splat things with a large number of elements.
