### ISSUE TITLE
Having problem running Julia in Google Collab

### ISSUE THREAD

**Issue by starboyvarun** [JuliaLang/julia#43026]
I tried using this template : [url](https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_Colab_Notebook_Template.ipynb#scrollTo=anFDxaHWczIb)
When I use it as gist  it works.But when I try running the same template from my googledrive it give error.Says Julia not installed in runtime type.
Can you please tell me how I can run the same template  from my googledrive.
Thank You!.

**Comment by KristofferC** [comment]
Please use [discourse.julialang.org/](https://discourse.julialang.org/) for questions.
