### ISSUE TITLE
Array pointer ignores offset

### ISSUE THREAD

**Issue by baumgold** [JuliaLang/julia#43056]
When getting a pointer from an array (via the [pointer function](https://github.com/JuliaLang/julia/blob/v1.6.3/base/abstractarray.jl#L1116)) the resulting memory address describes the beginning of the array, but ignores the array's [offset](https://github.com/JuliaLang/julia/blob/v1.6.3/src/julia.h#L197).  AFAIK the offset is used to efficiently "soft" delete objects at the beginning of the array ([here](https://github.com/JuliaLang/julia/blob/v1.6.3/src/array.c#L1060-L1107)).  If this is in-fact the case, then the offset should be taken into account when returning the memory address of the start of the array ([here](https://github.com/JuliaLang/julia/blob/v1.6.3/src/rtutils.c#L346)).  Specifically, instead of having `jl_array_ptr` return `a->data` we might want to return `a->data + a->offset`.

A reproducible example follows below.  Note that the memory-address doesn't change even after calling `popfirst!()`.  I expect that the memory-address would increment after the call to `popfirst!()`.

```
julia> v = [1,2]
2-element Vector{Int64}:
 1
 2

julia> pointer(v)
Ptr{Int64} @0x00007fffdef09d30

julia> popfirst!(v)
1

julia> pointer(v)
Ptr{Int64} @0x00007fffdef09d30

julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by matbesancon** [comment]
was playing around with this, the interesting part is that `unsafe_load` from the pointer produces the correct value (the updated one)

**Comment by baumgold** [comment]
@matbesancon - Thanks for picking this up and helping out.

> was playing around with this, the interesting part is that `unsafe_load` from the pointer produces the correct value (the updated one)

Agreed, that's surprising and a bit magical.  I don't understand how/why that works.  Do you?

**Comment by matbesancon** [comment]
no, there is definitely something fishy somewhere

**Comment by baumgold** [comment]
On second thought I think this may not be a bug but rather a feature.  The [jl_array_del_at_beg](https://github.com/JuliaLang/julia/blob/v1.6.3/src/array.c#L1060-L1107) function calls [jl_array_limit_offset](https://github.com/JuliaLang/julia/blob/v1.6.3/src/array.c#L1046-L1058) to "make sure offset doesn't grow forever due to deleting at beginning and growing at end".  It accomplishes this by reducing the offset (and subsequently calling memmove) when `offset >= 13 * maxsize / 20`.  This explains the behavior that I've noticed.  Closing this issue.
