### ISSUE TITLE
Memory not released or resused under Linux

### ISSUE THREAD

**Issue by freemin7** [JuliaLang/julia#43063]
When running `@btime length($rand(100000000))` repeatedly Julia allocates around 0.8G of memory (almost) each time and doesn't release it even if the system starts swapping. Unlike [here](https://github.com/JuliaLang/julia/issues/42566#issuecomment-941179065) the memory is not reused for the next call. #29085 might be related but that doesn't involve interpolation ($ stuff). The issue does not exist for `@time length(rand(100000000))`

I could reproduce the issue on x86_64 and AARCH 64 in 1.6.1 and 1.7.0-rc2 on two Linux variants. The repeated allocation of 0.8 Gigabytes does not happen under Windows and a GC.gc() call frees the 0.8G too which doesn't happen under Linux.

 `@btime length(x) setup=(x = rand(100000000))` on Linux behaves nicely under Linux including GC.gc() working.

**Comment by KristofferC** [comment]
An interpolated value in BenchmarkTools will never be released (based in how BenchmarkTools uses it) . I'm pretty sure there is an issue about this sonmewhere in the BenchmarkTools repo but can't find it now.

**Comment by freemin7** [comment]
I didn't find anything like that either.

**Comment by KristofferC** [comment]
It was in a PR https://github.com/JuliaCI/BenchmarkTools.jl/pull/247. Anyway this is not a julia issue but a BenchmarkTools one.
