### ISSUE TITLE
JULIA_LLVM_ARGS="--aarch64-sve-vector-bits-min=" LLVM SegFault creating ntuple of VecElement of passed vector length

### ISSUE THREAD

**Issue by freemin7** [JuliaLang/julia#43069]
When running Julia with JULIA_LLVM_ARGS="--aarch64-sve-vector-bits-min=512" precompiling `VectorizationBase` causes the error below without the LLVM this error does not appear.
```
[ Info: Precompiling VectorizationBase [3d5dd08c-fd9d-11e8-17fa-ed2836048c2f]

signal (11): Segmentation fault
in expression starting at /lustre/home/guest19/.julia/packages/VectorizationBase/xHOp9/src/special/exp.jl:200
_ZNK4llvm3EVT16isExtendedVectorEv at /lustre/home/guest19/julia-1.7.0-rc2/bin/../lib/julia/libLLVM-12jl.so (unknown line)
_ZNK4llvm3EVT21isExtended64BitVectorEv at /lustre/home/guest19/julia-1.7.0-rc2/bin/../lib/julia/libLLVM-12jl.so (unknown line)
Allocations: 18783400 (Pool: 18782916; Big: 484); GC: 38
ERROR: Failed to precompile VectorizationBase [3d5dd08c-fd9d-11e8-17fa-ed2836048c2f] to /lustre/home/guest19/.julia/compiled/v1.7/VectorizationBase/jl_k42v0A.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
```

This weekend A64FX instances are easily accessible via the OOKAMI which provides access via the ARM HPC User group. See page 14 and 15 of these [slides](https://drive.google.com/file/d/1xSCpOBARCxTTK334cNDhI_wGYFMPTOdG/view) for login data. So anyone can reproduce it.

```
julia> versioninfo()
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, a64fx)
Environment:
  JULIA_LLVM_ARGS = -aarch64-sve-vector-bits-min=512
```
**The MWE is** `ntuple(j -> Core.VecElement(j), n)` where 9>n>2. For example 3,4 or 8.

Other observations:
`JULIA_LLVM_ARGS="-aarch64-sve-vector-bits-min=512" ./julia-1.7.0-rc2/bin/julia -e 'ntuple(j -> Core.VecElement(j), 8)'`  doesn't trigger it.
When changing the -aarch64-sve-vector-bits-min= 256 causes crashes 2<n<5 and 1024 causes crashes with 2<n<17.

**Comment by chriselrod** [comment]
For reference, the offending line within VectorizationBase is:
```julia
const TABLE_EXP_64_0= Vec(ntuple(j -> Core.VecElement(Float64(2.0^(big(j-1)/16))), Val(8)))
```
Which doesn't look like it should be problematic.

I wonder if this is similar to?
https://github.com/JuliaLang/julia/issues/30426

Maybe some alignment assumptions differ on this platform?
For example, the A64fx has 256 byte cachelines.

It's easy enough to work around within VectorizationBase, because that code is specifically for AVX512, where you can use shuffle instructions for a small-but-fast lookup table.

**Comment by freemin7** [comment]
I find it unlikely that this crash's is related to hardware features as the area of the parameters with which that crash occurs is related the SVE size passed via environmental variable.

**Comment by vchuravy** [comment]
If you can get the LLVM IR from the Module, that would help.

**Comment by freemin7** [comment]
I only got core dumps now. I had access to the machine the weekend I created the issue. Would those be helpful and how could I get them to you?

**Comment by giordano** [comment]
Precompilation of `VectorizationBase` is now successful (tested with Julia v1.7.2), but now I get a runtime crash (signal 6) when running functions with `@turbo`.

**Comment by giordano** [comment]
Actually, nightly build of Julia works also at runtime:
```
$ JULIA_LLVM_ARGS="-aarch64-sve-vector-bits-min=512" ./julia-7889b2a6a2/bin/julia -q
julia> versioninfo()
Julia Version 1.8.0-DEV.1572
Commit 7889b2a6a2 (2022-02-16 21:17 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: 48 × unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, a64fx)
  Threads: 1 on 48 virtual cores

julia> using LoopVectorization, BenchmarkTools

julia> function mydotavx(a, b)
          s = 0.0
          @turbo for i ∈ eachindex(a,b)
              s += a[i]*b[i]
          end
          s
       end
mydotavx (generic function with 1 method)

julia> @btime mydotavx(a, b) setup=(a=fill(2.0, 256); b=fill(3.14, 256))
  209.311 ns (0 allocations: 0 bytes)
1607.68
```
Closing the issue.
