### ISSUE TITLE
Segmentation fault when plotting with Gadfly after JuMP calculation

### ISSUE THREAD

**Issue by jyscao** [JuliaLang/julia#43079]
I'm doing some fairly typical numerical computations on time series data of various stock prices, such as plotting price graphs using Gadfly, and also added in an integer linear programming model fitting using JuMP and Cbc. The program I'm running is largely represented by the following function:

```julia
function main()
    args_dict   = parse_commandline()
    df          = load_csv_to_df(args_dict)
    df_min      = get_df_minimums(df)
    df_max      = get_df_maximums(df, df_min)
    df_combined = outerjoin(outerjoin(df, df_min, on=:Date), df_max, on=:Date)

    perc_drops  = calc_percent_drops(df_min, df_max)
    loss, n_vec = solve_ILP_for_ω(perc_drops, 10.0)

    stock_name = get_stock_name(args_dict["CSV-data-file"])
    plt = plot_data(df_combined, stock_name)
    println("plot generated...")

    n_mins = size(df_min) |> first
    img    = PDF("$stock_name (N_mins=$n_mins).pdf", 48cm, 30cm)
    draw(img, plt)   # FIXME: this line produces - signal (11): Segmentation fault: 11
end
```

This line `loss, n_vec = solve_ILP_for_ω(perc_drops, 10.0)` runs the integer linear programming model fitting. And the lines `plt = plot_data(df_combined, stock_name)` and `draw(img, plt)` are what generates the plot using Gadfly and saves it to a file respectively.

Both functionalities work well and appear to be correct when executed alone. However if `solve_ILP_for_ω` is executed before the `draw`, then the entire program exits with error: `signal (11): Segmentation fault: 11` at the `draw(img, plt)` line; everything else before that runs correctly. If I comment out the `solve_ILP_for_ω` call, then `draw(img, plt)` runs normally and creates the PDF plot file.

I believe the bug might be related to the Julia GC as is mentioned in the end of the stacktrace below:

```
signal (11): Segmentation fault: 11
in expression starting at /Users/jyscao/trading/omega-analyzer/main.jl:160
_show_components at /Users/jyscao/.julia/packages/ColorTypes/6m8P7/src/show.jl:0
show at /Users/jyscao/.julia/packages/ColorTypes/6m8P7/src/show.jl:13 [inlined]
showoff at /Users/jyscao/.julia/packages/Showoff/ZtTt9/src/Showoff.jl:23
showoff at /Users/jyscao/.julia/packages/Showoff/ZtTt9/src/Showoff.jl:20
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
render at /Users/jyscao/.julia/packages/Gadfly/B5yQc/src/geom/line.jl:152
render at /Users/jyscao/.julia/packages/Gadfly/B5yQc/src/geometry.jl:45
...
... [truncated]
...
Allocations: 214751381 (Pool: 214687780; Big: 63601); GC: 88
```

I'm able to work around this issue by simply moving the `solve_ILP_for_ω(perc_drops, 10.0)` line to be after the `draw(img, plt)` line. But thought I'd report this behavior as a bug anyway in case it points to a more significant underlying problem.

This is the setup I'm using BTW:

```
julia> versioninfo()
Julia Version 1.7.0-rc2
Commit f23fc0d27a (2021-10-20 12:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

**Comment by giordano** [comment]
A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be most useful. I've experienced some segfaults on the M1, some of them are easy to fix at the package level, others require work on the Julia side, but having a _**small**_ example that can be run by anyone (instead of a partial snippet from larger program) could help us identify what case is this

**Comment by jyscao** [comment]
I'm having a difficult time minimizing the code. It might be some race condition. When I simply printed a small integer vector (but not an empty one), e.g. `println(Vector(1:2:100))`, right after the `solve_ILP_for_ω` call, the segfault goes away. Very strange.

I'll close the ticket for now.

**Comment by giordano** [comment]
It may be the same as #41440 and #42295 (also because the stacktrace points to line 0 of a file).  The segfault I reported in https://github.com/JuliaStats/Distributions.jl/issues/1344 (which is again the same as #41440) is non-deterministic, it happens often but not always, which is also similar to what you're seeing.

But again, a more useful bug report would include complete and minimal code that people can actually run, the example above wasn't really enough.

**Comment by jyscao** [comment]
I tried to get a minimal code example going. Unfortunately there are many dependencies I'm using, as well as quite large data input files, and when I removed them and put in hardcoded dummy data, the bug disappeared.

I may give it another shot at reproducing a bit later. But for the time being, I'll just workaround it.
