### ISSUE TITLE
Unusual/Inconsistent Behavior for 1-element Comprehensions

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#43080]
Comprehensions with 1 element are considered 0-dimensional arrays: 
```
julia> [x for x in 1]
0-dimensional Array{Int64, 0}:
1
```

What's unusual about this is the behavior is different from the behavior when creating a 1-element array directly:
```
julia> [1]
1-element Vector{Int64}:
 1
```

Unsure if this is desired behavior.

**Comment by simeonschaub** [comment]
This is expected because:
```julia
julia> size(1)
()
```
so we consider numbers 0-dimensional containers. `[x for x in [1]]` will indeed create a 1-dimensional array.
