### ISSUE TITLE
Linear Algebra - cholesky factorization for inverted matrices

### ISSUE THREAD

**Issue by blixi** [JuliaLang/julia#43091]
Dear Developer Team,

if I compute a Hermitian matrix, I can compute the Cholesky factorisation without declaring the matrix as Hermitian.
If I invert that said Hermitian matrix it will still be Hermitian, but in order to compute the Cholesky factorisation I now need to declare it as Hermitian first.

Minimal code example:
```julia
using LinearAlgebra

vec = randn(3,3)
foo = vec*vec'
cholesky(foo)

fooinv = foo^-1
cholesky(fooinv) #ERROR: PosDefException: matrix is not Hermitian; Cholesky factorization failed.
cholesky(Hermitian(fooinv)) #Can compute the cholesky factorization
```

Output:

```julia
julia> cholesky(foo)
Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.52562  -0.45884   3.00925
  ⋅        1.94349  -0.587403
  ⋅         ⋅        0.334203

julia> 

julia> fooinv = foo^-1
3×3 Matrix{Float64}:
  32.1511   -5.01199  -16.8462
  -5.01199   1.08262    2.70603
 -16.8462    2.70603    8.95321

julia> cholesky(fooinv)
ERROR: PosDefException: matrix is not Hermitian; Cholesky factorization failed.
Stacktrace:
 [1] checkpositivedefinite(info::Int64)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\factorization.jl:18
 [2] cholesky!(A::Matrix{Float64}, ::Val{false}; check::Bool)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:282
 [3] #cholesky#130
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:378 [inlined]
 [4] cholesky (repeats 2 times)
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:378 [inlined]
 [5] top-level scope
   @ REPL[37]:1

julia> cholesky(Hermitian(fooinv))
Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 5.6702  -0.883918  -2.97101
  ⋅       0.548917   0.145556
  ⋅        ⋅         0.324232

julia> cholesky(fooinv)
ERROR: PosDefException: matrix is not Hermitian; Cholesky factorization failed.
Stacktrace:
 [1] checkpositivedefinite(info::Int64)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\factorization.jl:18
 [2] cholesky!(A::Matrix{Float64}, ::Val{false}; check::Bool)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:282
 [3] #cholesky#130
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:378 [inlined]
 [4] cholesky (repeats 2 times)
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\cholesky.jl:378 [inlined]
 [5] top-level scope
   @ REPL[39]:1

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by oscardssmith** [comment]
The problem is that due to floating point math, `inv(foo)` isn't actually positive definite.

**Comment by blixi** [comment]
But then it should also not be possible to make it positive definite by using `Hermitian(inv(foo))`. Besides, this is not an issue in e.g. Matlab or Python, so it should be fixable.

**Comment by oscardssmith** [comment]
It would be really bad if `cholesky` gave you the factorization of a different matrix than the one you called it on. What should happen for matrices that aren't at all positive definite?

**Comment by blixi** [comment]
I totally agree with your first point, that would indeed be really bad if `cholesky()` would return the factorization for a different matrix than the one I called it on.

But for some reasons, the floating point math doesn't seem to be an issue in for example Matlab. If I define a Hermitian matrix `A` in Matlab, I can call `chol(A^-1)` without a problem. I don't see this as giving me the factorization of a different matrix than the one I called it on, but rather as the ability of Matlab to conserve the properties of Hermitian matrices. And I believe it would be nice if Julia would also have this ability.

**Comment by oscardssmith** [comment]
One thing you should look at using `inv(chol(A))` which will both always work (assuming A is posdef), and be faster and more accurate.

**Comment by blixi** [comment]
Right, didn't consider that since this issue is in fact spread out across multiple functions. So this wasn't obvious at first glance :)

**Comment by blixi** [comment]
inv

**Comment by oscardssmith** [comment]
How different are they? My guess would be floating point error. Different implementations will give different results due to rounding.

**Comment by blixi** [comment]
Here is my testcase:
```
A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
isposdef(A) #true
inv(cholesky(A).U)
cholesky(Hermitian(inv(A)))
```

and here are the outputs:
```

3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

true    

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 0.5  -3.0   6.33333
  ⋅    1.0  -1.66667
  ⋅     ⋅    0.333333

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 7.02575  -1.92941   0.300482
  ⋅        0.234839  0.103041
  ⋅         ⋅        0.101015
```

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/pull/22686#issuecomment-314480839 for some more details on this issue. In short, things are a bit complicated, and, as you can see in the linked comment, Matlab has silently been changing behavior over time.

As a side comment, I'd recommend that you avoid computing the Cholesky of the inverse since computing the inverse requires factorizing the matrix in the first place so you'd end up computing two factorization where only one is required.

**Comment by blixi** [comment]
Thanks for the link posted @andreasnoack! But that sitll doesn't explain the results above.

**Comment by andreasnoack** [comment]
The inverse of a the usual (forward) Cholesky `◣*◥` is the less standard (backward) Cholesky `◥*◣`

```julia
cholesky(Hermitian(inv(A))) = ◣*◥

inv(cholesky(A)) = inv( ◣*◥) =  ◥*◣
```
so
```julia
julia> cholesky(Hermitian(inv(A))).U |> t -> t't
3×3 Matrix{Float64}:
  49.3611   -13.5556     2.11111
 -13.5556     3.77778   -0.555556
   2.11111   -0.555556   0.111111

julia> inv(cholesky(A).U) |> t -> t*t'
3×3 Matrix{Float64}:
  49.3611   -13.5556     2.11111
 -13.5556     3.77778   -0.555556
   2.11111   -0.555556   0.111111
```

**Comment by blixi** [comment]
@andreasnoack Yes, thank you very much. I am familiar with these properties of the cholesky factorization. That doesn't answer my question though:

For a positive definite matrix A, the Cholesky factorization A = U^TU, where U is a upper triangular matrix with positive and real entries on the diagonal, is unique.

Thus, I do not understand, why for the matrix
 
```
A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
```
the outputs of the two following lines give such different results. 
```
inv(cholesky(A).U)
cholesky(Hermitian(inv(A)))
```

```
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 0.5  -3.0   6.33333
  ⋅    1.0  -1.66667
  ⋅     ⋅    0.333333

Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 7.02575  -1.92941   0.300482
  ⋅        0.234839  0.103041
  ⋅         ⋅        0.101015
```

Do you have an explanation why this is happening?

**Comment by oscardssmith** [comment]
The LU factorization is unique, but what's happening here is that `inv(cholesky)` is a UL matrix rather than an LU matrix.

**Comment by andreasnoack** [comment]
You can compute a Cholesky starting from the upper left. That is the usual one and the one you are referring to. You can store it as a lower triangle (`L*L'`) or an upper triangle (`U'U`) but in either case, the shapes multiplied are `◣*◥`. You can also compute a Cholesky starting from the lower right. It's not common to do so and LAPACK doesn't support it, but it's the same algorithm just with the indices reversed.  In this case the shapes multiplied are`◥* ◣` but you can again store and upper or a lower triangular matrix. When you invert a forward Cholesky, you get a backward Cholesky. So for your example

```julia
julia> U_forward = cholesky(inv(Hermitian(A))).U
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 7.02575  -1.92941   0.300482
  ⋅        0.234839  0.103041
  ⋅         ⋅        0.101015

julia> U_backward = inv(cholesky(Hermitian(A)).U)
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 0.5  -3.0   6.33333
  ⋅    1.0  -1.66667
  ⋅     ⋅    0.333333

julia> inv(A) ≈ U_forward'U_forward
true

julia> inv(A) ≈ U_backward*U_backward'
true
```
even though both are upper triangles. To see that one starts from the top and the other from the bottom, maybe it's helpful to note that
```julia
julia> U_forward[1,1]^2 ≈ inv(A)[1,1]
true

julia> U_backward[3,3]^2 ≈ inv(A)[3,3]
true
```

**Comment by andreasnoack** [comment]
Let's continue the conversation on Discourse if needed.
