### ISSUE TITLE
Tests for Distributed.jl with custom stream types

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#43109]
In #42481 we ran into problems using custom stream types to transport messages for Distributed due to world age issues.

It wasn't clear to me how to make a reliable test for that particular bug (at least, not without more invasive changes to the way that the `flush_gc_msgs` task is launched). But regardless of that, it would be good to have a test of Distributed with custom stream types for the message transport.

**Comment by vtjnash** [comment]
Doesn't really seem like something that can be tested in any guaranteed way
