### ISSUE TITLE
[Bug] User can redefine `setfield!`

### ISSUE THREAD

**Issue by 0xD3ADBEEF** [JuliaLang/julia#43108]
When I redefine the `setfield!` for a particular type, I should be getting an error. Yet, in this particular example it works:

```julia
julia> mutable struct Test
       a::Integer
       lock::Bool
       end

julia> function setfield!(a::Test, s::Symbol, val)
           if a.lock
              error("Object is locked!")
           else
              setfield!(Ref(a), s, val)
           end
       end
setfield! (generic function with 1 method)
```

Doesn't work after calling/referring to it for the first time though:
```julia
julia> setfield!
setfield! (built-in function)

julia> mutable struct Test
       a::Integer
       lock::Bool
       end

julia> function setfield!(a::Test, s::Symbol, val)
           if a.lock
              error("Object is locked!")
           else
              setfield!(Ref(a), s, val)
           end
       end
ERROR: error in method definition: function Core.setfield! must be explicitly imported to be extended
Stacktrace:
 [1] top-level scope
   @ none:0
```

This however is ok:
```julia
julia> setfield!
setfield! (built-in function)

julia> mutable struct Test
       a::Integer
       lock::Bool
       end

julia> function Core.setfield!(a::Test, s::Symbol, val)
           if a.lock
              error("Object is locked!")
           else
              setfield!(Ref(a), s, val)
           end
       end
ERROR: cannot add methods to a builtin function
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
Note: all of these examples are executed in freshly started Julia instances. 

For a bit of context, I am trying to "lock" a mutable type from user access, after I'm done working with it.

Version info:
```julia
julia> versioninfo()
Julia Version 1.6.3
Commit ae8452a9e0* (2021-09-23 17:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by simeonschaub** [comment]
This is expected. In the first case you aren't overloading `Core.setfield!`, you are just defining a new function that also happens to be called `setfield!`.

**Comment by 0xD3ADBEEF** [comment]
If that is indeed the case, then I should always be getting ```ERROR: error in method definition: function Core.setfield! must be explicitly imported to be extended```, or not. In this sense, the behavior of redefining said function is undefined.

**Comment by simeonschaub** [comment]
Like I said, you are not redefining the function. Any further discussion is probably better suited for discourse.julialang.org

**Comment by 0xD3ADBEEF** [comment]
Yes, my bad, I meant to say "defining". Doesn't change the fact that one should always be getting an error when a function with this name (or any function whose name coincides with a the name of a core function) is defined, or not getting an error at all. Having this error only in certain contexts is not imho "expected" behavior, but fair I can bring that to the discourse.
