### ISSUE TITLE
Higher precedence for rocket operator over pipe operator

### ISSUE THREAD

**Issue by essenciary** [JuliaLang/julia#43118]
Per the discussion in Slack, the current behaviour in the following snippet does not confirm to most user's expectations, which can cause issues in some mainstream packages like DataFrames: 

```julia
julia> :a => "b" |> typeof
:a => String
```

Following the suggestion in the thread, I'm opening this issue to propose that in v2 the compiler priorities the creation of the Pair data structure.

**Comment by vtjnash** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/38761
