### ISSUE TITLE
The `contrib/refresh_checksums.mk` script does not delete old checksums

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#43140]
This has been discussed before, but I couldn't find an open issue for it.

Currently, the `contrib/refresh_checksums.mk` script will add any new checksums if they are missing, but it will not delete the old checksums. Therefore, the user has to manually delete the old checksums.

It would be much more convenient if the `contrib/refresh_checksums.mk` script also deleted the old checksums.

---

Of course, the script should only delete old checksums for the requested dependencies.

For example, if I run the script as `make -f contrib/refresh_checksums.mk libuv`, I want the script to delete any old checksums for libuv. However, I don't want it to delete any checksums for dependencies other than libuv.

**Comment by vtjnash** [comment]
The fix is still stuck in https://github.com/JuliaLang/julia/pull/42311

**Comment by DilumAluthge** [comment]
Let me try to pull the fix out into a standalone PR, and test it locally to make sure it works. Then I'll open a PR and ping you.
