### ISSUE TITLE
MLJBase.jl tests pass (in 20 minutes) with multithreading on Julia 1.6.3 but hang indefinitely (with a 6 hour timeout) with multithreading on Julia nightly

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#43167]
The MLJBase.jl tests pass (in 20 minutes) with multithreading on Julia 1.6.3 but hang indefinitely (with a 6 hour timeout) with multithreading on Julia nightly.

I do not have an MWE. I do, however, have an `rr` trace. The trace is too large to upload to GitHub; if you want me to send it to you, just DM me on Slack.

Here are the steps that I used to reproduce the hang and generate the `rr` trace:
```
export JULIA_DEPOT_PATH=$(mktemp -d)
cd $(mktemp -d)
git clone https://github.com/JuliaAI/MLJBase.jl.git
cd MLJBase.jl
git checkout dev
wget https://raw.githubusercontent.com/JuliaLang/julia/master/.buildkite/utilities/rr/rr_capture.jl
julia --project -e 'import Pkg; Pkg.instantiate()'
time julia --project -e 'import MLJBase'
time julia --project -e 'import MLJBase'
export JULIA_TEST_RR_TIMEOUT="360" # 360 minutes = 6 hours
export TEST_MLJBASE="true"
export JULIA_NUM_THREADS="2"
time julia rr_capture.jl julia --project -e 'import Pkg; Pkg.test()'
```

**Comment by DilumAluthge** [comment]
cc: @ablaom @rikhuijzer

**Comment by vtjnash** [comment]
Assuming this is old. Please indicate if not.

**Comment by DilumAluthge** [comment]
With the latest `MLJBase#dev` and the latest Julia nightly, I'm able to get the MLJBase.jl tests to pass on CI (takes about 20 minutes). See e.g. https://github.com/JuliaAI/MLJBase.jl/pull/822

So it looks like this has indeed been resolved!
