### ISSUE TITLE
Handling of `err` and `ans` global variables in REPL

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#43172]
Copying this from @mcabbott in merged #40642 to a new issue so it doesn't get lost.

===================
Is it possible that `err`, and in fact `ans`, should have a value on startup? This would prevent this:
```
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> ans(x) = "function";

julia> 1+1
ERROR: invalid redefinition of constant ans

julia> 2;
ERROR: invalid redefinition of constant ans
```
in favour of this:
```
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 1+1
2

julia> ans(x) = "function";
ERROR: cannot define function ans; it already has a value
```

=======================

**Comment by JeffBezanson** [comment]
Yes, I think it would be reasonable to initialize them to `nothing`.

**Comment by StefanKarpinski** [comment]
Doesn't that turn the introduction of `err` into a breaking change? (Albeit only in the REPL.)

**Comment by BioTurboNick** [comment]
Could an alternative be to set a global inside the REPL module and export it only if not already in Main?

**Comment by JeffBezanson** [comment]
We have changed behavior in the repl before, e.g. the scope change. Fortunately may not need to in this case.

> Could an alternative be to set a global inside the REPL module and export it only if not already in Main?

Yes I think that works --- if you define it first, you just get your variable and the REPL modifies its own variable which you can't see. But if you request `ans` or `err` without defining them, the `using` logic kicks in to import the variables. Good idea!

**Comment by vtjnash** [comment]
I made this version of the change, but I don't think I like it https://github.com/JuliaLang/julia/compare/master...vtjnash:jn/MainInclude-ans-err

In particular, it means that `ans` gets hidden from `names(Main)`

So possibly we want to just declare `global ans = nothing; global err = nothing` early in REPL startup instead

**Comment by JeffBezanson** [comment]
Or the most benign version would be to check whether `ans` is a constant before trying to set it in the REPL, and just skipping it in that case to avoid the error/warning.
