### ISSUE TITLE
Some links to source in the stdlib documentation broken

### ISSUE THREAD

**Issue by alexandrebouchard** [JuliaLang/julia#43199]
E.g.: this leads to 404 error:

- got to https://docs.julialang.org/en/v1/stdlib/Statistics/
- mouse over bottom right of the box Statistics.std
- click 'Source'

**Comment by inkydragon** [comment]
Statistics.jl is located in a separate repo: https://github.com/JuliaLang/Statistics.jl

**Comment by dkarrasch** [comment]
This is also broken for the "outsourced" SuiteSparse.jl. @fredrikekre Is it enough to put corresponding `repo` keywords to the `Documenter.makedocs()` call in those two stdlibs? I see they have a `repo` in `deploydocs`, but not in `makedocs`, but I'm only roughly familiar with the specifics of Documenter.jl.

**Comment by fredrikekre** [comment]
That would set it for base docstrings too, so I think you have to do some post-processing.
