### ISSUE TITLE
Bracketed paste mode parsing issue in VSCode REPL

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#43201]
Following on: https://github.com/microsoft/vscode/issues/112831 and https://github.com/julia-vscode/julia-vscode/issues/2501

It appears the issue is in the Julia REPL itself, somehow parsing the bracketed paste mode is occurring incorrectly.

Windows Terminal apparently doesn't support bracketed paste mode, so it doesn't show up there. Only inside the VSCode prompt on Windows.

Paste "combinednormalizedmontecarlomeasurementsc" at prompt (right click, excluding quote marks), and extra characters are appended from the bracket. The number of extra characters is sensitive to the length of the input.

May or may not be relevant, but xTerm.js logging shows it parses the input in two chunks.

**Comment by Keno** [comment]
My best guess would be that the initial `\e[200~` isn't being written into the input buffer atomically. We distinguish between escape sequences and literal presses of the escape key that happen to be followed by `[` by whether or not they appear in the buffer atomically. That's a bit of a hack, but e.g. readline uses a timeout, which just somehow seems worse. You might want to write out a log file that logs what chunks julia reads from the input buffer.

**Comment by BioTurboNick** [comment]
I think you're right, I put some test code in the brackets paste methods and nothing is being hit. Though I'm having trouble figuring out which function is doing the keymap checking. What's the first function in Julia that receives pasted input?

**Comment by BioTurboNick** [comment]
Found it: `prompt!`, which runs `match_input`.

This is what I see in Linux on WSL:

```
matching input:
MI State ("Prompt(\"julia> \",...)" active)
['\e', '[', '2', '0', '0', '~']
julia> combinednormalizedmontecarlomeasurementsc
```

Now just to figure out how to build for Windows...

**Comment by BioTurboNick** [comment]
It seems like the first bracket of the bracketed paste is just not present. The Debug console in VSCode shows it's in the data being sent from xterm.js. But by the time it is consumed in `prompt!` it's gone.

I tried writing a test for it, but the phenomenon isn't occurring if I just provide the string all at once to `write()`.

**Comment by BioTurboNick** [comment]
After a lot of poking around, I'm fairly convinced that the data being provided to Julia from a bracketed paste is being corrupted between xTerm (which wraps and sends the data) and the Julia REPL. Thus, I shall close this.
