### ISSUE TITLE
REPL `shell` does not work in Win11

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#43216]
v1.7.0-rc2

```
shell> ls
ERROR: IOError: could not spawn `ls`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
   @ Base .\process.jl:100
 [2] #690
   @ .\process.jl:113 [inlined]
 [3] setup_stdios(f::Base.var"#690#691"{Cmd}, stdios::Vector{Any})
   @ Base .\process.jl:197
 [4] _spawn
   @ .\process.jl:112 [inlined]
 [5] run(::Cmd; wait::Bool)
   @ Base .\process.jl:445
 [6] run
   @ .\process.jl:444 [inlined]
 [7] repl_cmd(cmd::Cmd, out::Base.TTY)
   @ Base .\client.jl:69
 [8] top-level scope
   @ none:1
```

**Comment by logankilpatrick** [comment]
Does this also occur on 1.7 RC3?

**Comment by JeffreySarnoff** [comment]
I assume so -- it occurs on 1.8-Dev

**Comment by JeffreySarnoff** [comment]
Yes the same problem exists with 1.7 RC3.

**Comment by inkydragon** [comment]
How about `; cmd /c dir`

cmd does not support the `ls` command.

ref: https://github.com/JuliaLang/julia/issues/23597, https://github.com/JuliaLang/julia/issues/23597#issuecomment-421079812

**Comment by JeffreySarnoff** [comment]
that works .  On Win10 `; ls` does work with 1.7 RC3.

**Comment by PallHaraldsson** [comment]
I'm just guessing here, Windows has WSL2 but dropped the original WSL. I assume you're using WSL with Windows, knowingly or not.

**Comment by JeffreySarnoff** [comment]
I have WSL2 on Win10 and on Win11.  I ran Julia without first explicitly loading a shell (just clicked on the installation's icon).

**Comment by MarcMush** [comment]
win10 user here, `; ls` and `; dir` don't work for me

**Comment by JeffreySarnoff** [comment]
well then .. nevermind

**Comment by PallHaraldsson** [comment]
https://github.com/JuliaLang/julia/issues/23597#issuecomment-327344974
>Powershell was also an option but IIUC availability was not as clear.

I'm not sure, I think PowerShell might fix if used by default, and it seems supported on all Windows versions Julia now officially support, so maybe revisit that decision.
