### ISSUE TITLE
inference: regression on constraint propagation with `!(a || b)` pattern

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#43224]
It seems like #43142 introduced a regression on the following kind of code:
```julia
julia> code_typed((Any,); optimize=false) do nv
           if !(isa(nv, Symbol) || isa(nv, Int))
               return 0
           end
           return nv
       end |> only
 CodeInfo(
1 ─ %1 = (nv isa Main.Symbol)::Bool
└──      goto #3 if not %1
2 ─      (@_3 = true)::Core.Const(true)
└──      goto #4
3 ─      (@_3 = nv isa Main.Int)::Bool
4 ┄ %6 = @_3::Bool
│   %7 = !%6::Bool
└──      goto #6 if not %7
5 ─      return 0
6 ─      return nv
) => Any
```
If we revert `2c057f8`, then we can get:
```julia
 CodeInfo(
1 ─ %1 = (nv isa Main.Symbol)::Bool
└──      goto #3 if not %1
2 ─      (@_3 = %1)::Bool
└──      goto #4
3 ─      (@_3 = nv isa Main.Int)::Bool
4 ┄ %6 = @_3::Bool
│   %7 = !%6::Bool
└──      goto #6 if not %7
5 ─      return 0
6 ─      return nv::Union{Int64, Symbol}
) => Union{Int64, Symbol}
```

Previously, inference sees `(@_3 = %1)` as `Conditional(nv, Symbol, Any)` so the constraint propagation worked.
I wonder we can just remove `@_3 = true` and set `@_3 = (nv isa Main.Symbol)` instead here?

/cc @simeonschaub @vtjnash

**Comment by simeonschaub** [comment]
Hmm, that's unfortunate! I am happy to revert #43142 for now until we figure this out. We can maybe special-case `||` if it's inside `&&` expressions in lowering, but I am wondering whether we might be able to teach inference to refine the `Const(true)` to a `Conditional` here, or do you recon that's complicated?

**Comment by vtjnash** [comment]
We don't use this lowering for `&&`, so why do we use it for `||`?
