### ISSUE TITLE
LoadError: IOError: stream is closed or unusable with libgit2 1.3.0

### ISSUE THREAD

**Issue by ignatenkobrain** [JuliaLang/julia#43249]
Hello,

I'm updating libgit2 stack in Fedora from 1.1.0 to 1.3.0 and we compile Julia with USE_SYSTEM_LIBGIT2=1.

Sadly after libgit2 update, Julia tests (or some data generation for the?) fails with following stack trace:

```
Generating REPL precompile statements... 26/36ERROR: LoadError: IOError: stream is closed or unusable
Stacktrace:
  [1] check_open
    @ ./stream.jl:386 [inlined]
  [2] uv_write_async(s::Base.TTY, p::Ptr{UInt8}, n::UInt32)
    @ Base ./stream.jl:1018
  [3] uv_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt32)
    @ Base ./stream.jl:981
  [4] unsafe_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt32)
    @ Base ./stream.jl:1064
  [5] write
    @ ./strings/io.jl:244 [inlined]
  [6] write
    @ ./io.jl:639 [inlined]
  [7] (::Main.anonymous.var"#2#6"{Set{String}, String, Base.DevNull})(precompile_file::String, precompile_file_h::IOStream)
    @ Main.anonymous ~/build/BUILD/julia-1.7.0-rc3/contrib/generate_precompile.jl:326
  [8] mktemp(fn::Main.anonymous.var"#2#6"{Set{String}, String, Base.DevNull}, parent::String)
    @ Base.Filesystem ./file.jl:722
  [9] mktemp
    @ ./file.jl:720 [inlined]
 [10] generate_precompile_statements()
    @ Main.anonymous ~/build/BUILD/julia-1.7.0-rc3/contrib/generate_precompile.jl:270
 [11] top-level scope
    @ ~/build/BUILD/julia-1.7.0-rc3/contrib/generate_precompile.jl:416
 [12] eval(m::Module, e::Any)
    @ Core ./boot.jl:373
 [13] top-level scope
    @ ~/build/BUILD/julia-1.7.0-rc3/contrib/generate_precompile.jl:6
in expression starting at /builddir/build/BUILD/julia-1.7.0-rc3/contrib/generate_precompile.jl:3
```

While it does not seem to be an issue with libgit2 from the stacktrace, I've tried to build in almost the same environment (just with newer libgit2) and it does not fail on this error.

The issue is reproducible (I've tried to rebuild it ~5 times and it always fails like this).

here's the failing build log: https://kojipkgs.fedoraproject.org//work/tasks/2694/79372694/build.log
here's the successful build log: https://kojipkgs.fedoraproject.org//work/tasks/7535/79377535/build.log

---

I'm very happy to test out any patches or provide any more information, just let me know.

Thanks in advance!

**Comment by ignatenkobrain** [comment]
FTR, I think https://github.com/archlinux/svntogit-community/blob/packages/julia/trunk/julia-libgit-1.2.patch fixes it for me. I'm not sure what's the correct way to send you this patch…

**Comment by KristofferC** [comment]
>  I'm not sure what's the correct way to send you this patch…

Looks to be incorporated in https://github.com/JuliaLang/julia/pull/43250
