### ISSUE TITLE
Bug: Length of iterators.Stateful can be wrong

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#43245]
MWE:
```julia
julia> collect(Iterators.Stateful(Iterators.Stateful(1:1)))
ERROR: ArgumentError: destination has fewer elements than required
```
What happens is that the inner constructor for `Stateful` calls `iterate` on its argument, while at the same time setting `taken = 0`. I don't know why it does that.

**Comment by Moelf** [comment]
do we just need
```julia
Iterators.Stateful(x::Iterators.Stateful) = x
```
?

**Comment by jakobnissen** [comment]
No, this will not be sufficient to fix this bug.

**Comment by Moelf** [comment]
what makes you say so?
```julia
julia> collect(Iterators.Stateful(Iterators.Stateful(1:1)))
ERROR: ArgumentError: destination has fewer elements than required
Stacktrace:
 [1] copyto!(dest::Vector{Int64}, src::Base.Iterators.Stateful{Base.Iterators.Stateful{UnitRange{Int64}, Union{Nothing, Tuple{Int64, Int64}}}, Union{Nothing, Tuple{Int64, Nothing}}})
   @ Base ./abstractarray.jl:903
 [2] _collect
   @ ./array.jl:718 [inlined]
 [3] collect(itr::Base.Iterators.Stateful{Base.Iterators.Stateful{UnitRange{Int64}, Union{Nothing, Tuple{Int64, Int64}}}, Union{Nothing, Tuple{Int64, Nothing}}})
   @ Base ./array.jl:712
 [4] top-level scope
   @ REPL[1]:1

julia> Iterators.Stateful(x::Iterators.Stateful) = x

julia> collect(Iterators.Stateful(Iterators.Stateful(1:1)))
1-element Vector{Int64}:
 1
```

**Comment by Moelf** [comment]
well, in any case I think this is a good method to have, making a PR now

**Comment by jakobnissen** [comment]
Because the bug happens when the inner iterator is any stateful iterator with a known length:
```
julia> mutable struct CountDown
           x::Int
       end

julia> function Base.iterate(x::CountDown, state::Nothing=nothing)
           iszero(x.x) ? nothing : (x.x -= 1; (x.x, nothing))
       end

julia> Base.length(x::CountDown) = x.x

julia> collect(Iterators.Stateful(CountDown(2)))
ERROR: ArgumentError: destination has fewer elements than required
```

**Comment by Moelf** [comment]
that's not how you use `Base.Stateful` though, because `CountDown` is already a stateful iterator, why would you wrap it again with `Stateful`?

**Comment by jakobnissen** [comment]
IMO that's irrelevant - `Stateful` should behave correctly either way. But it might not be possible for me to know the nature of the iterator I am wrapping.

**Comment by Moelf** [comment]
Stateful is not an interface, it's a very concrete wrapper to do one thing:
>  There are several different ways to think about this iterator wrapper:
    1. It provides a mutable wrapper around an iterator and its iteration state.
    2. ...
    3. ...

You can raise the point that Stateful is a stupid name or we should have had a formal interface for the stateful iterator, but the truth is Julia's iteration interface concerns stateless, and `Stateful` is not a parallel iterator interface, `Stateful` is a very specific, narrow wrapper for you to turn an iterator (again, stateless because Julia iterators are stateless unless mentioned otherwise)

**Comment by jakobnissen** [comment]
Can you please show where it is defined that all Julia iterators are stateless? I can come with a counterexample: `eachline`.

**Comment by Moelf** [comment]
we certainly have stateful iterable object, but I'm talking about the fact that our "interface" concerns only stateless iterator:
https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration

so I was simply saying `Iterators.Stateful` is **just** one of the stateful iterable object, it's not an **iteraton interface**, and the iteration interface talks about things assuming the state is explicitly tracked/passed back to `iterate()`

**Comment by Moelf** [comment]
In fact, if you look, the top-level `EachLine` is not stateful:
https://github.com/JuliaLang/julia/blob/05eb1530bbfe2db0dd6c9a13ea065f17cb9730cf/base/io.jl#L996-L1000

**Comment by Moelf** [comment]
and if you want to work the same way as `EachLine`:
```julia

julia> mutable struct CountDown
           x::Int
       end

julia> function Base.iterate(x::CountDown, state::Nothing=nothing)
           iszero(x.x) ? nothing : (x.x -= 1; (x.x, nothing))
       end

julia> Base.length(x::CountDown) = x.x

julia> Base.IteratorSize(::Type{<:CountDown}) = Base.SizeUnknown()

julia> collect(Iterators.Stateful(CountDown(2)))
2-element Vector{Any}:
 1
 0
```
