### ISSUE TITLE
Internal error: encountered unexpected error in runtime: StackOverflowError() in has_safe_def

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#43254]
One of our packages started to produce the following error:
```julia
Internal error: encountered unexpected error in runtime:
StackOverflowError()
has_safe_def at ./compiler/ssair/passes.jl:98
has_safe_def at ./compiler/ssair/passes.jl:113
[...]
has_safe_def at ./compiler/ssair/passes.jl:101 [inlined]
sroa_mutables! at ./compiler/ssair/passes.jl:873
[...]
```
see https://github.com/oscar-system/Oscar.jl/runs/4352506233?check_suite_focus=true#step:5:426.

This is with master I built a few minutes ago:
```julia
julia> versioninfo()
Julia Version 1.8.0-DEV.1081
Commit 43bc48b1f8 (2021-11-29 13:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```
I have not done a bisect yet, but there are some obvious commits to look at.

**Comment by thofma** [comment]
And the winner is 1a1f3d70739020de705af7d611ee2c78d5630c7a, congratulations @aviatesk :)

**Comment by aviatesk** [comment]
Agh, is it possible to reduce the reproducer a bit further?

**Comment by vtjnash** [comment]
That code is just walking the predecessor list recursively?? The predecessor list is not a DAG, it is cyclic.
