### ISSUE TITLE
FR: add `dot(missing, missing)` fallback

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#43268]
We are in the process of generalizing some code from scalar fields to vector spaces, and some algorithms that use `*` can be rewritten in terms of `⋅` (LinearAlgebra.dot). These algorithms support `missing` values in the scalar case because `missing * missing` is implemented in `Base`. Can we also have a `dot(::Missing, ::Missing) = missing` in the next release of the language?

**Comment by fredrikekre** [comment]
#40743
