### ISSUE TITLE
Windows Terminal not Rendering ANSI Escapes Properly

### ISSUE THREAD

**Issue by andrewraddatz** [JuliaLang/julia#43273]
When I launch julia inside of Windows Terminal, it does not render the escapes properly, which makes it very difficult to use as a REPL.

![image](https://user-images.githubusercontent.com/58223683/144129224-73a2806a-7c00-42dc-8abb-db1ece69a624.png)

Launching julia with `--color=no` makes the output substantially tamer, but there are still issues on the initial line of output.

![image](https://user-images.githubusercontent.com/58223683/144129518-3b0e4f69-68cc-4cbd-b552-6ecd64c91392.png)

Julia has the same issue when launched directly while [Legacy Console Mode](https://docs.microsoft.com/en-us/windows/console/legacymode) is disabled (for both color and no-color modes):

![image](https://user-images.githubusercontent.com/58223683/144129618-fba6c6fa-bd82-43e5-b2eb-64cce5cffdc0.png)

But renders fine with Legacy Console Mode enabled:

![image](https://user-images.githubusercontent.com/58223683/144129714-18b8a0f9-de42-404c-99f3-2db532763706.png)

**Comment by oscardssmith** [comment]
imo, it's not our fault that windows terminal is broken.

**Comment by andrewraddatz** [comment]
I'm not trying to play the blame game, but in the past I was able to launch julia in Windows Terminal, but now I can't use it.

Older versions of julia render properly in the current version of Windows Terminal:
![image](https://user-images.githubusercontent.com/58223683/144134810-ed992ff7-1993-4245-8c90-e5834cd50741.png)

I don't remember when exactly it broke, but I think it was in the 1.5.X series.

**Comment by zadjii-msft** [comment]
This might also be related to https://github.com/JuliaLang/julia/issues/40016?

**Comment by andrewraddatz** [comment]
After the problem magically resolving itself when i moved my ~/.julia directory, I did some more digging. It looks like the issue is tied to a macro that I created to clear the screen which was called in a different macro in my startup script.

replacing the macro with its content removes the ANSI character issue.
