### ISSUE TITLE
Error during initialization of module GMP

### ISSUE THREAD

**Issue by OrbitalMechanic** [JuliaLang/julia#43288]
I’ve just installed Julia-1.7 onto a Mac Pro desktop (2019) running Mac OSX Monterey (ver. 12.0.1). When I start up Julia I get the following message:

```
exec '/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia'
(base) user@Mac-Pro ~ % exec '/Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia'
WARNING: Error during initialization of module GMP:
ErrorException("could not load symbol "__gmp_version":
dlsym(0x21ee689e0, __gmp_version): symbol not found")
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

Any suggestions on how correct the error during the initialization of module GMP?

Samuel Dupree.

**Comment by ViralBShah** [comment]
Are you using the official binaries? Do you have any LD_LIBRARY_PATH or equivalent set in your `.bashrc`?

**Comment by OrbitalMechanic** [comment]
See my responses in bold red below.
 



On Wed, 01 Dec 2021 21:19:33 -0800, "Viral B. Shah" ***@***.***> wrote:
 
 

Are you using the official binaries? Yes Do you have any LD_LIBRARY_PATH No or equivalent set in your .bashrc No?
For the most part, I use the zsh.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ViralBShah** [comment]
I can't see your responses.

**Comment by OrbitalMechanic** [comment]
My responses are below in *bold red*:

**Comment by vtjnash** [comment]
There is no text below. Note that GitHub email server strips the contents of the old issue when posting your replies.

**Comment by OrbitalMechanic** [comment]
My responses:

Are you using the official binaries? Yes 

Do you have any LD_LIBRARY_PATH No or equivalent set in your .bashrc No?

For the most part, I use the zsh.

**Comment by ViralBShah** [comment]
Please reopen if this is still happening with the most recent binaries.
