### ISSUE TITLE
Cannot round Time to Period

### ISSUE THREAD

**Issue by knuesel** [JuliaLang/julia#43284]
The documentation for `round` says

>   `round(dt::TimeType, p::Period, [r::RoundingMode]) -> TimeType`
> 
>  Return the `Date` or `DateTime` nearest to `dt` at resolution `p`. [...] For convenience, `p` may be a type instead of a value: `round(dt, Dates.Hour)` is a shortcut for `round(dt, Dates.Hour(1))`.

However it seems `Time` values (which are `TimeType`) cannot be rounded to `Period` values:

```julia
julia> round(Time(now()), Second)
ERROR: MethodError: no method matching floor(::Time, ::Second)
Closest candidates are:
  floor(::Union{Day, Week, TimePeriod}, ::T) where T<:Union{Day, Week, TimePeriod} at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:110
  floor(::Union{Day, Week, TimePeriod, TimeType}, ::Type{P}) where P<:Period at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:285
  floor(::DateTime, ::TimePeriod) at ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:81
  ...
Stacktrace:
 [1] floorceil(dt::Time, p::Second)
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:196
 [2] round(dt::Time, p::Second, r::RoundingMode{:NearestTiesUp})
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:235
 [3] round(x::Time, ::Type{Second}, r::RoundingMode{:NearestTiesUp}) (repeats 2 times)
   @ Dates ~/repos/julia-1.7.0/share/julia/stdlib/v1.7/Dates/src/rounding.jl:291
 [4] top-level scope
   @ REPL[4]:1
```

This seems related to https://github.com/JuliaLang/julia/issues/37738 but it's not clear to me what that issue is about.

**Comment by TheLostLambda** [comment]
This definitely feels like a bug in the Julia stdlib (if rounding times isn't supposed to be supported, then it should fail at `round` and certainly shouldn't make it all the way down to `floor` in `floorceil`!)

I'll try to fix this! I suppose it's the perfect excuse for my first Julia PR!
