### ISSUE TITLE
Inference regression in julia 1.7

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#43296]
The following snipped infers in 1.6 and even 1.7-rc1 but does not anymore. Came up [here](https://github.com/JuliaObjects/Accessors.jl/pull/38):
```julia
using Accessors
using Test
struct TT{A,B}
    a::A
    b::B
end
lens = @optic(_.b.a.b[2])
obj = TT(2, TT(TT(3,(4,4)), 2))
@inferred modify(identity, obj, lens)
```

**Comment by JeffBezanson** [comment]
Could you try bisecting this?

**Comment by jw3126** [comment]
@JeffBezanson bisected to e8caa2750969b1f4e8e41431ca8d1840aa8ac51b

**Comment by maleadt** [comment]
MWE:

```julia
r(b) = r(typeof(b))
r(::Type) = nothing
r(::Nothing) = nonexistent

struct C{t,I} end
r(::Type{C{c,d}}) where {c,d} = f(r(c), e)
f(::Nothing, :) = nothing
f(g, :) = h

k(b, j, :) = l
k(b, j, ::Nothing) = b

i(b, j) = k(b, j, r(j))
struct A{d} end
Base.return_types(i, (Int64, C{C{C{A, Tuple}, Tuple}}))
```

**Comment by vtjnash** [comment]
`i`, `k`, and `f` there are unrelated, and are just playing the role of a type-unstable conditional

This is now explicitly disallowed in inference:
```
r(::Type{C{c,d}}) where {c,d} = f(r(c), e)
```

Since it is inferring / calling:
```
r(::Type{C{C{C{A}}}}) -> r(::Type{C{C{A}}}) -> r(::Type{C{A}}) -> r(::Type{C{A}}) -> r(::Type{A}) -> nothing
```

And we decided (https://github.com/JuliaLang/julia/commit/e8caa2750969b1f4e8e41431ca8d1840aa8ac51b) that this pattern is not something we care about, relative to other patterns.

**Comment by jw3126** [comment]
> And we decided (e8caa27) that this pattern is not something we care about, relative to other patterns.

Does this mean this bug won't be fixed?

**Comment by jw3126** [comment]
> And we decided (e8caa27) that this pattern is not something we care about, relative to other patterns.

This pattern can arise in the wild, when you combine trait based dispatch with recursion. This is the cause in Accessors.jl:
```julia
OpticStyle(optic) = OpticStyle(typeof(optic))
OpticStyle(::Type{MyOptic}) = ...
doit(optic) = _doit(optic, OpticStyle(optic))
function _doit(optic::ComposedOptic, ::SomeStyle)
    x1 = doit(optic.inner)
    ...
    x2 = doit(optic.outer)
    ...
end
```
A workaround is to replace
```julia
OpticStyle(::Type{MyOptic}) = ...
```
by
```julia
OpticStyle(::MyOptic) = ...
```

**Comment by vtjnash** [comment]
Ah, interesting. I wonder if we can do something about that too.

**Comment by cscherrer** [comment]
Maybe try
```julia
@generated OpticStyle(optic::T) = OpticStyle(T)
```
This worked for me in a similar situation.

**Comment by jw3126** [comment]
> Maybe try
> 
> ```julia
> @generated function OpticStyle(optic::T) where {T}
>     OpticStyle(T)
> end
> ```
> 
> This worked for me in a similar situation.

If I do this, it seems dispatch selects the wrong method in some situations. I thought 
```julia
@generated function OpticStyle(optic::T) where {T}
    OpticStyle(T)
end
```
and
```julia
function OpticStyle(optic::T) where {T}
    OpticStyle(T)
end
``` 
have exactly the same semantics, but seems not to be the case.
```julia
Base.@pure OpticStyle(obj) = OpticStyle(typeof(obj)) 
```
solves the problem, but will probably lead to bugs.
