### ISSUE TITLE
docs.julialang.org: source link for some linear algebra functions are broken for 1.7

### ISSUE THREAD

**Issue by daviehh** [JuliaLang/julia#43307]
For example the first source link under [lu](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.lu) gets redirected to https://github.com/JuliaLang/LinearAlgebra/src/lu.jl#L209-L276, which does not exist; not sure if there are other links that got sent to the wrong place.

<img width="1170" alt="Screen Shot 2021-12-02 at 2 37 23 PM" src="https://user-images.githubusercontent.com/25255906/144491219-9fd98c62-ea5e-479e-8052-f60919cdf744.png">

**Comment by ViralBShah** [comment]
I believe we no longer have the `source` there. Please reopen if still an issue.
