### ISSUE TITLE
Slowdown since 1.5.4

### ISSUE THREAD

**Issue by fab4ap** [JuliaLang/julia#43302]
I wanted to report this issue that may be important. I have been running a script that uses FFTW, PaddedViews and RCall. This is implementing a point spread function using FFT on a very large matrix that uses nested for loops. I noticed a significant slowdown on Windows 10 platform in the newer versions. The script takes ~ 35 mins to run on  versions 1.4.2 and 1.5.4, but ~ 48 mins on versions 1.6.4 and 1.7.0. I tested this using the same script and inputs on all four versions in succession making sure the background conditions were the same (I reinstalled versions from scratch each time). The details of the script should not matter since I'm comparing versions using the same conditions. I am now forced to go back to version 1.5.4. If you want me to provide further details I can.
Thanks.

**Comment by KristofferC** [comment]
> If you want me to provide further details I can.

That's pretty much required. Also it would help to reduce the runtime and amount of code as much as possible. Results from profiling can also be useful.

**Comment by fab4ap** [comment]
Well, I can provide the script and inputs and reduce runtime. Not sure
about profiling - I'm in research with not much time/expertise to do that.
From what I gather the issue could be in FFTW or more likely in somethings
that have changed in the base julia implementation on windows since version
1.5.4. Rcall and PaddedViews are superficial. RCall just converts a spatial
GeoTiff file to matrix and is peripheral. I can send a zipped version of
the inputs if that's helpful.

**Comment by Seelengrab** [comment]
It's literally impossible to investigate what caused the slowdown without knowing what code was involved :shrug: A lot of people here are volunteers here, any help you can give us in indicating _what_ is slower is immensely helpful in figuring out what caused the slowdown.

**Comment by fab4ap** [comment]
I understand - and do appreciate all your efforts. I'm rather stymied because the same code with the same inputs runs slower from 1.6.4 onwards in Windows. Also, I can only have one version at a time, making it quite difficult to do more testing. So, it's a difficult beast - I'll try to see what more I can do to shed light on the issue. Perhaps for now, a red-flag is sufficient - others may uncover this from different angles. I'm happy to switch back to 1.5.4 in the meantime.

**Comment by oscardssmith** [comment]
Why can you only have 1 version at a time? You can pretty easily have multiple versions of Julia on your system.

**Comment by fab4ap** [comment]
OK, I did some profiling. I attach the runnable script with the Profile results. Hope this is sufficient to uncover performance degradation. Than
[SpeedTst.zip](https://github.com/JuliaLang/julia/files/7644801/SpeedTst.zip)
ks

**Comment by fab4ap** [comment]
In case it is helpful, Pkg version of FFTW in Julia 1.5.4 is v1.3.2 and in Julia 1.6.4 it is v1.4.5.

**Comment by ViralBShah** [comment]
Please reopen if still an issue with a reproducer example.
