### ISSUE TITLE
Julia 1.7 possibly corrupting .julia folder

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#43315]
I was debugging something, I thought related to Julia 1.7, and decided to try with an empty .julia folder (as I often do):

```
  548  mv ~/.julia .julia_bak
  549  ~/julia-1.7.0/bin/julia
  550  ~/julia-1.7.0/bin/julia
  551  ~/julia-1.7.0/bin/julia
  552  ~/julia-1.7.0/bin/julia
  553  rm -Rf ./julia
  554  mv ~/.julia_bak .julia
  555  ~/julia-1.7.0/bin/julia
```

then starting julia, the folder isn't the same.

```
(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [c43c736e] Genie v4.4.1
  [98e50ef6] JuliaFormatter v0.15.11
```

I had lots more there, and .julia/environments/ only has v1.7 and the old environment for 1.6 is completely gone.

**Comment by fredrikekre** [comment]
Probably you removed the wrong folder. No julia version have ever removed environment files and I have never seen it happen.
