### ISSUE TITLE
Link to Julia 1.7 Docs PDF 404's 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#43317]
Per a discussion in Discorse, the link to the PDF of the docs 404s: https://docs.julialang.org/en/v1/

It looks like this is due to a CI failure: https://github.com/JuliaLang/docs.julialang.org/runs/4402414711?check_suite_focus=true

**Comment by logankilpatrick** [comment]
This is the last releases build that passed: https://github.com/JuliaLang/docs.julialang.org/actions/runs/1518462133 (3 days ago)

**Comment by logankilpatrick** [comment]
One possible issue, a dep version bump. The repo does not have a Project.toml file so it installs the latest versions it needs which could be breaking

**Comment by logankilpatrick** [comment]
@KristofferC @fredrikekre any ideas here?

**Comment by fredrikekre** [comment]
Most likely some new part of the doc doesn't compile in tex. (I believe this happened months ago so I don't think it is useful to just look at recent commits.)

**Comment by ViralBShah** [comment]
We should test the existence of the pdf as part of the release process, if possible.

**Comment by ViralBShah** [comment]
I tried the `make pdf`, but it's quite difficult to debug the output. I'm uploading the generated log file here.

[TheJuliaLanguage.log](https://github.com/JuliaLang/julia/files/7657311/TheJuliaLanguage.log)

**Comment by ViralBShah** [comment]
Might this be a possible culprit? 

https://github.com/JuliaLang/julia/issues/43342

**Comment by DilumAluthge** [comment]
> We should test the existence of the pdf as part of the release process, if possible. I am wondering if we can detect that the pdf generation failed and not include the pdf link in the documentation.

How long does the PDF take to build? Should we add a Buildkite job (https://github.com/JuliaCI/julia-buildkite) for it?

Normally, I would never recommend that we add a Buildkite job if the same thing can be accomplished with GitHub Actions. However, in this specific case, the job (PDF docs for Base Julia) is very much within the scope of Base Julia CI, so I would not object to adding this to Buildkite.

**Comment by ViralBShah** [comment]
A few minutes, I think.

**Comment by DilumAluthge** [comment]
> needs tons of tex packages installed on the system

We would just build a rootfs image (https://github.com/JuliaCI/rootfs-images) with the necessary dependencies.

> A few minutes, I think.

A few minutes is quick enough that we can just add this to the doctests and run it on every PR.

**Comment by DilumAluthge** [comment]
Is it actually just a few minutes, though? Looks like the last successful run took more than 30 minutes: https://github.com/JuliaLang/docs.julialang.org/actions/runs/576633576

**Comment by DilumAluthge** [comment]
Also, note that the last time the nightly PDF built successfully was 10 months ago, so that's probably where you would want to look to find the breakage.

**Comment by shayandavoodii** [comment]
> **Warning**
> Again there is an error `404: Not Found` after clicking on the link to get `1.7.3.pdf`:

![image](https://user-images.githubusercontent.com/52105833/169686250-0048a35a-06d0-4dc0-adcb-6bf89ff4a49b.png)

**Comment by ViralBShah** [comment]
I see the PDF is for 1.7.2. It shouldn't matter but would be nice to have the correct one.

**Comment by shayandavoodii** [comment]
> I see the PDF is available but it is for 1.7.2. It shouldn't matter but would be nice to have the correct one.

They fixed the `404 Error` according to [this](https://github.com/JuliaLang/julia/discussions/45418#discussioncomment-2798935).
