### ISSUE TITLE
`logabsdet` behavior inconsistent with `log ∘ abs ∘ det`

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#43316]
`logabsdet(x::Real)` throws an error, while `log(abs(det(x::Real)))` happily returns `log(abs(x))`. Is this intentional?

**Comment by simeonschaub** [comment]
I think this would be reasonable to add.

**Comment by ankur12-1610** [comment]
Can I work on this issue?

**Comment by oscardssmith** [comment]
the answer to that question is always yes.

**Comment by ankur12-1610** [comment]
Can anyone help which files should change:sweat_smile:? I'm new to the Julia and don't much about it.

**Comment by oscardssmith** [comment]
wait, on master, logabsdet is defined for numbers.

**Comment by ankur12-1610** [comment]
> wait, on master, logabsdet is defined for numbers.

I didn't get it, is this issue already solved?

**Comment by cafaxo** [comment]
Yes. This issue is a duplicate of #42911, which was closed by #42912.

**Comment by ParadaCarleton** [comment]
Continue to be amazed by the quick turnaround of the Julia team -- bug fixes often take negative time after I file a bug report
