### ISSUE TITLE
The doc/ Manifest.toml is missing the julia version

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#43344]
Specifically, it is missing the julia version entry.
```
┌ Warning: The active manifest file is missing a julia version entry. Dependencies may have been resolved with a different julia version.
└ @ ~/julia/doc/Manifest.toml:0
```

**Comment by IanButterworth** [comment]
It's has the new format, it just needs re-resolving to store the julia version i.e. `pkg> resolve` or if there are resolve conflicts `pkg> up`

**Comment by ViralBShah** [comment]
Perhaps we need this on 1.7 (and perhaps 1.6 also, if the manifest format is backported to LTS).

**Comment by fredrikekre** [comment]
Doesn't seem necessary.
