### ISSUE TITLE
 jl_setjmp is not exported on Windows by the LTS version

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaLang/julia#43340]
Sorry for not noticing this sooner despite opening an issue about it before, but on Windows `jl_setjmp`  is not exported by the LTS version. As a result the `JL_TRY` and `JL_CATCH` macros can't be used when embedding Julia.

https://github.com/JuliaLang/julia/issues/42245

**Comment by IanButterworth** [comment]
There are also some `jl_setjmp` redefinition warnings on master.

**Comment by JeffBezanson** [comment]
#42267 should be backported
