### ISSUE TITLE
Punctuation page contains broken markdown

### ISSUE THREAD

**Issue by rben01** [JuliaLang/julia#43342]
The second-to-last row of the table on https://docs.julialang.org/en/v1/base/punctuation/ has what appears to be a markdown bug in how `|>` was parsed/rendered, causing malformed + missing content in that row.

That page:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/766670/144766138-dcb95c11-02d5-40b4-8f7b-018a5ce77cf9.png">

On GitHub (https://github.com/JuliaLang/julia/blob/master/doc/src/base/punctuation.md)
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/766670/144766157-5fa42493-1bda-414e-ae49-5bdeac580bac.png">

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/41167
