### ISSUE TITLE
StackOverflowError: When Using julia Matrix Divide A/B

### ISSUE THREAD

**Issue by phystry** [JuliaLang/julia#43358]
Simply Get This Error by

`rand(2,720)/rand(720,720)`
ERROR: StackOverflowError:

When change it to

`rand(2,120)/rand(120,120)`
Get correct result:
2×120 Matrix{Float64}: -3.98568 4.0549 4.30112 0.767333 5.25419 1.03845 5.14592 0.236119 -1.46789 -1.83912 3.9814 1.09028 3.04451 0.618902 -4.33044 … -5.36532 0.0215027 -9.72819 1.14866 -4.12121 2.24605 4.32528 -4.59007 -2.28853 -3.28813 1.13299 -1.2411 0.378753
-2.89095 2.27448 2.22753 1.13359 3.01714 0.929562 2.67707 1.18504 -1.02976 -0.569199 2.62177 0.517625 1.10433 0.294882 -2.43448 -2.79622 0.483641 -5.94725 0.903424 -1.92138 1.80968 3.08397 -1.97155 -1.31307 -0.971027 0.624244 -0.159086 0.249652

changing 120 to 130:

`rand(2,130)/rand(130,130)`
ERROR: StackOverflowError:

**Comment by fredrikekre** [comment]
#43242

**Comment by phystry** [comment]
> #43242

This occurs only in VScode
Codes works fine in Julia official REPL application.
