### ISSUE TITLE
sincos slower than (sin, cos)

### ISSUE THREAD

**Issue by Mo8it** [JuliaLang/julia#43365]
Calling sincos(x) is slower than calling (sin(x), cos(x)) although sincos exists to be faster.

```julia
using BenchmarkTools: @btime

function f()
    r = rand()
    @btime sincos($r)
    @btime (sin($r), cos($r))
    return nothing
end

f()
```

Output:
6.762 ns (0 allocations: 0 bytes)
5.189 ns (0 allocations: 0 bytes)

---

I did try SLEEFPirates. It is slower than the Julia version but sincos is faster than (sin, cos) as expected.

```julia
using BenchmarkTools: @btime
using SLEEFPirates

function f()
    r = rand()
    @btime SLEEFPirates.sincos($r)
    @btime (SLEEFPirates.sin($r), SLEEFPirates.cos($r))
    return nothing
end

f()
```

Output:
15.720 ns (0 allocations: 0 bytes)
24.111 ns (0 allocations: 0 bytes)

---

julia> versioninfo()
Julia Version 1.7.0-rc3
Commit 3348de4ea6 (2021-11-15 08:22 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: AMD Ryzen 7 5800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)

**Comment by oscardssmith** [comment]
I think this is a benchmarking artifact, but I'm not sure how. If I time as follows, I don't see this (also sincos does pretty much strictly less work).
```
julia> @btime sincos(Ref($r)[]);
  9.590 ns (0 allocations: 0 bytes)

julia> @btime (sin(Ref($r)[]), cos(Ref($r)[]));
  10.230 ns (0 allocations: 0 bytes)
```

**Comment by N5N3** [comment]
Maybe `r` is too small to bench this?
I thought the reused `rem_pio2_kernel` is the key to accelerate `sincos`

**Comment by oscardssmith** [comment]
It also reuses a bunch of the checks (ie Inf/Nan/0, and which branch). The benchmark I showed is roughly what I would expect with them having similar times, but slightly better for `sincos`.

**Comment by N5N3** [comment]
1. For large inputs: `sincos` is faster (Not supprising):
```julia
julia> r = collect(range(-10pi,10pi,101)); a = sincos.(r);
julia> f(x) = sin(x), cos(x);
julia> @btime $a .= sincos.($r);
  1.070 μs (0 allocations: 0 bytes)
julia> @btime $a .= f.($r);
  1.520 μs (0 allocations: 0 bytes)
```

2. For small inputs: `sin, cos` seems faster (Might machine dependent):
```julia
julia> r = collect(range(-pi/4,pi/4,101)); a = sincos.(r);
julia> @btime $a .= sincos.($r);
  795.833 ns (0 allocations: 0 bytes)
julia> @btime $a .= f.($r);
  726.718 ns (0 allocations: 0 bytes)
```

**Comment by oscardssmith** [comment]
I think this is an inlining issue. I believe what's happening is that `sincos` doesn't inline so the tuple doesn't get destructured. @aviatesk's recent work on better SROA theoretically might help here. We also might be able to make it do smarter things so that it would inline (and thus remove) the creation of the tuple, while not inlining the computaiton...

**Comment by KristofferC** [comment]
> On my Desktop...

If I re-write it like

```jl
function h(x)
    n = 0.0
    for i in x
        s, c = sincos(i)
        n += s + c
    end
    return n
end

function h2(x)
    n = 0.0
    for i in x
        s, c = (sin(i), cos(i))
        n += s + c
    end
    return n
end

r = collect(range(-10pi,10pi,101));
 
@btime h($r)
@btime h2($r)

r = collect(range(-pi/4,pi/4,101));

@btime h($r)
@btime h2($r)
```

to avoid invoking the whole broadcast machinery, then I get that `sincos` is faster in both cases.

**Comment by giordano** [comment]
```
julia> @benchmark sincos(x) setup=(x=randn())
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
 Range (min … max):  10.042 ns … 38.486 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     10.632 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   12.050 ns ±  2.672 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▆█▆      ▂ ▆ █▃▅                                            ▂
  ████▄▄▁▃██▆██████▃▄▃▇▆▅▄▄▄▅█▄█▄▃▄▅▃▁▄▄█▆▅▆██▇▇██▅▄▄▅▅▃▆▇▇▆▆ █
  10 ns        Histogram: log(frequency) by time      23.7 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark (sin(x), cos(x)) setup=(x=randn())
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
 Range (min … max):  10.583 ns … 45.658 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     11.254 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   13.607 ns ±  3.221 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    █                                                          
  █▅█▂▂▁▂▂▂▂▂▂▂▁▁▂▂▂▄▂▃▇▃▄▂▇▃▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▁▁▂▁▂▁▁▂▂▁▂▂▂▂ ▂
  10.6 ns         Histogram: frequency by time        25.5 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark sincos(x) setup=(x=100randn())
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
 Range (min … max):  10.335 ns … 121.138 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     14.378 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   14.771 ns ±   2.914 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▁     ▁ ▁  ▂▂▂▆▇█▆▂                                          ▂
  ██▁▄▁▃█▄█▃██████████▇▇▄▄▁▃▄▃▁▄▆▆▇▄▃▅▁▄▃▃▃▃▁▁▃▃▄▁▃▄▅▆▇██▇▇██▇ █
  10.3 ns       Histogram: log(frequency) by time      25.4 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark (sin(x), cos(x)) setup=(x=100randn())
BenchmarkTools.Trial: 10000 samples with 999 evaluations.
 Range (min … max):  10.611 ns … 67.278 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     19.774 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   20.251 ns ±  3.357 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

             ▂▃▂  ▄▆██▅▁                ▁▁▁                   ▂
  ██▄▁▁▁▁▃▁▆█████▄███████▇▃▅▇▆▄▇▆▆▅▅▅▄▆████▆▄▃▅▁▄▁▃▄▄▅▅▅▃▃▄▄▆ █
  10.6 ns      Histogram: log(frequency) by time      39.6 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
They look comparable to me, with `sincos` just slightly faster.  I'm using `randn()` vs `100randn()` to probe different scales.

**Comment by caseykneale** [comment]
I'm on Julia 1.7 and running the first test I get the same time for both
```
  0.018 ns (0 allocations: 0 bytes)
  0.018 ns (0 allocations: 0 bytes)
 ```
Using KristofferC's test I get the following outputs
```
  1.285 μs (0 allocations: 0 bytes)
  1.780 μs (0 allocations: 0 bytes)
  712.094 ns (0 allocations: 0 bytes)
  848.529 ns (0 allocations: 0 bytes)
 ```
Looks like sincos is faster and when its not its immeasurably similar. Can provide hardware or OS information if requested.

**Comment by Mo8it** [comment]
I can confirm that the test of @KrisofferC proves that sincos is in general faster. But my code from the issue description still has a problem somehow. If I run `f()` for many times, then only in some cases, sincos is faster. But in all other cases, cos, sin is faster.
```julia
julia> f()
  6.775 ns (0 allocations: 0 bytes)
  5.168 ns (0 allocations: 0 bytes)

julia> f()
  7.900 ns (0 allocations: 0 bytes)
  8.530 ns (0 allocations: 0 bytes)

julia> f()
  6.635 ns (0 allocations: 0 bytes)
  5.238 ns (0 allocations: 0 bytes)

julia> f()
  6.705 ns (0 allocations: 0 bytes)
  5.098 ns (0 allocations: 0 bytes)
```

**Comment by Mo8it** [comment]
@vtjnash the issue does still exist. Please see my last comment.

**Comment by vtjnash** [comment]
yeah, it just turns out that it cannot be adequately measured at that level. Your cpu is too good at predicting work when run repeatedly (like a benchmark).
