### ISSUE TITLE
Regex constructor regression on 1.7 and master

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#43393]
On 1.6
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.3 (2021-09-23)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> Base.Regex("\xff", Base.PCRE.COMPILE_MASK, Base.PCRE.EXECUTE_MASK)
Regex("\xff",0xe00f25bf)
```
while on 1.7
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> Base.Regex("\xff", Base.PCRE.COMPILE_MASK, Base.PCRE.EXECUTE_MASK)
ERROR: PCRE compilation error: invalid option bits with PCRE2_LITERAL at offset 0
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compile(pattern::String, options::UInt32)
   @ Base.PCRE ./pcre.jl:155
 [3] compile(regex::Regex)
   @ Base ./regex.jl:82
 [4] Regex(pattern::String, compile_options::UInt32, match_options::UInt32)
   @ Base ./regex.jl:47
 [5] top-level scope
   @ REPL[1]:1
```
and master
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.988 (2021-11-15)
 _/ |\__'_|_|_|\__'_|  |  Commit 4b99bc8443* (25 days old master)
|__/                   |

julia> Base.Regex("\xff", Base.PCRE.COMPILE_MASK, Base.PCRE.EXECUTE_MASK)
ERROR: PCRE compilation error: invalid option bits with PCRE2_LITERAL at offset 0
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compile(pattern::String, options::UInt32)
   @ Base.PCRE ./pcre.jl:155
 [3] compile(regex::Regex)
   @ Base ./regex.jl:82
 [4] Regex(pattern::String, compile_options::UInt32, match_options::UInt32)
   @ Base ./regex.jl:47
 [5] top-level scope
   @ REPL[1]:1
```
I suspect https://github.com/JuliaLang/julia/pull/39524 cc @vtjnash

**Comment by vtjnash** [comment]
What are you trying to do? That is not a valid regex string, as it is not a valid string (https://stackoverflow.com/questions/5657467/is-byte-0xff-valid-in-a-utf-8-encoded-string), and we now disallow reading undefined memory with your regex patterns.

**Comment by Sacha0** [comment]
> What are you trying to do?

Make code that functioned on 1.6 function on 1.7 and master.

> That is not a valid regex string, as it is not a valid string (https://stackoverflow.com/questions/5657467/is-byte-0xff-valid-in-a-utf-8-encoded-string), and we now disallow reading undefined memory with your regex patterns.

Ah, I see! Thanks for pointing that out Jameson. We'll figure how to adapt the code on our end. Thanks!

**Comment by Sacha0** [comment]
> What are you trying to do?

To expand a little, `Base.Regex("\xff", Base.PCRE.COMPILE_MASK, Base.PCRE.EXECUTE_MASK)` was being used as a sort of "type max" for `Regex`, with \xff purposely invalid to match nothing real IIUC. Not sure what the best approach is now. Thoughts welcome :).

**Comment by vtjnash** [comment]
Like "$." or ".^" ?

**Comment by Sacha0** [comment]
Hah, clever! Love it :). Thank you!

**Comment by Sacha0** [comment]
Hm, I suppose those patterns don't have the same nice string-sort properties of "\xff", but it looks like we can rely upon the other aspects of our (hopefully adequate) solution for to get around that. Thanks again!

**Comment by Sacha0** [comment]
Regrets, it turns out that the invalid UTF-8 is not the whole or proximal issue (as with benefit of hindsight the particular failure mode reported above indicates). Note:
```
julia> Base.Regex("pattern", Base.PCRE.COMPILE_MASK, Base.PCRE.EXECUTE_MASK)
ERROR: PCRE compilation error: invalid option bits with PCRE2_LITERAL at offset 0
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compile(pattern::String, options::UInt32)
   @ Base.PCRE ./pcre.jl:155
 [3] compile(regex::Regex)
   @ Base ./regex.jl:82
 [4] Regex(pattern::String, compile_options::UInt32, match_options::UInt32)
   @ Base ./regex.jl:47
 [5] top-level scope
   @ REPL[11]:1
```

**Comment by vtjnash** [comment]
ah, I didn't see what mask you were using there. Some of the options of PCRE are contradictory, so you can't, for example, both set it to ignore UTF8 markers and require that it be UTF8.
```
julia> Regex("\xff", Base.PCRE.COMPILE_MASK & ~(Base.PCRE.NEVER_UTF | Base.PCRE.NEVER_UCP | Base.PCRE.LITERAL), 0)
```

**Comment by Sacha0** [comment]
> Some of the options of PCRE are contradictory, so you can't, for example, both set it to ignore UTF8 markers and require that it be UTF8.

Oh my 😄. @hall-alex, given the above I think the approach that worked under 1.6 will need more revision for 1.7+. I reviewed the implementation a little more carefully and think I have a solution.

**Comment by Sacha0** [comment]
In any case, the options changes seem like something that need be adapted to on RAI's end rather than a regression, so closing. Thanks again Jameson, much appreciated!
