### ISSUE TITLE
Memory allocation regression with Ref

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#43390]
The following snippet fails on Julia 1.7 but worked before:
```julia
using Accessors
using Test
function ref_alloc_test()
    ref = Ref((UInt(10), 100))
    ref2 = @set ref[][1] *= -1
    ref2[]
end

_ = ref_alloc_test()
@test @allocated(ref_alloc_test()) == 0
```

**Comment by vchuravy** [comment]
Could not reproduce on 1.7.0-rc2, or 1.7.0

**Comment by jw3126** [comment]
@vchuravy sorry you are right. I accidentally ran different versions of Accessors on 1.7.0 and 1.6.1. In the current version.
