### ISSUE TITLE
New PkgEval failures after merging #42339 ([Distributed] Worker local race condition between put! and fetch for Futures)

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#43396]
Putting this on the 1.8 milestone so it is not forgotten.

https://github.com/JuliaLang/julia/pull/42339#issuecomment-991502580

**Comment by krynju** [comment]
Seems like some issue with unwrapping `nothing` values specifically.
I'll try to investigate/fix it this weekend

Here's an MWE:

```julia
julia> using Distributed

julia> addprocs(1)
1-element Vector{Int64}:
 2

julia> fetch(remotecall(() -> 10, 2))
10

julia> fetch(remotecall(() -> nothing, 2))
ERROR: ArgumentError: No value arguments present
Stacktrace:
 [1] something()
   @ Base .\some.jl:99   
 [2] something(::Nothing)
   @ Base .\some.jl:100  
 [3] fetch(r::Future)    
   @ Distributed C:\cygwin64\home\krynjupc\julia\usr\share\julia\stdlib\v1.8\Distributed\src\remotecall.jl:638
 [4] top-level scope
   @ REPL[3]:1
```

**Comment by krynju** [comment]
Ok this was actually a simple one. I overlooked the return logic in fetch and was attempting to do `something(nothing)` at some point in code

Here's the PR https://github.com/JuliaLang/julia/pull/43398

**Comment by Sacha0** [comment]
Thanks Krystian! :)
