### ISSUE TITLE
LLVM missing constants in a loop

### ISSUE THREAD

**Issue by bardo84** [JuliaLang/julia#43400]
See [Why is LLVM missing this constant in a loop?](https://discourse.julialang.org/t/why-is-llvm-missing-this-constant-in-a-loop/72941)

Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = code.cmd
  JULIA_NUM_THREADS =

**Comment by KristofferC** [comment]
Arrays are not tracked to the level where they can be removed or hoisted. There is work going on to improve this. I don't think this requires a dedicated issue.
