### ISSUE TITLE
Add `ARGS` to `include()` when running scripts from the REPL

### ISSUE THREAD

**Issue by lfenzo** [JuliaLang/julia#43401]
In the context to passing arguments (`ARGS`) to `include()` when running scripts from the REPL, is [this suggestion](https://discourse.julialang.org/t/how-to-pass-command-line-arguments-to-include-julia-file/4731/6?u=lfenzo) still being considered?  

While the (in)famous time to first plot issue is still noticeable, this feature allows one to avoid redundant code compilation when executing scripts that accept CLI arguments. The execution time is not really relevant once the script is finished but development can be sped up by avoiding long compile times.

**Comment by JeffBezanson** [comment]
I don't think this feature makes sense. The concept of `ARGS` is inherently a process-global unix thing. If it is local to an `include` script, that is just a very inefficient form of calling a function with arguments. The right way to handle this is probably something like

```
function main(ARGS)
    # actual code goes here
end

if PROGRAM_FILE == @__FILE__
    main(ARGS)
end
```

Then you can reload the file and call `main` with the args you want.
