### ISSUE TITLE
Allow ... in non-final assignment location

### ISSUE THREAD

**Issue by adkabo** [JuliaLang/julia#43413]
It would be convenient to have more iterable unpacking.

Julia 1.7:

```jl
julia> x, (ys...) = (1,2,3,4);
julia> x, ys
(1, (2, 3, 4))
julia> x, (ys...), z = (1,2,3,4)
ERROR: syntax: invalid "..." on non-final assignment location "ys" around REPL[2]:1
```

Python ([feature specification](https://www.python.org/dev/peps/pep-3132/#specification)):

```py
In [1]: x, *y, z = [1,2,3,4]

In [2]: x, y, z
Out[2]: (1, [2, 3], 4)
```

**Comment by adkabo** [comment]
Maybe https://github.com/JuliaLang/julia/issues/42036 can be for function signatures and this issue can have the smaller scope of only unpacking assignment.

```jl
# first position
(a..., b) = _
# interior position
(a, b..., c) = _
```

**Comment by simeonschaub** [comment]
This is addressed by https://github.com/JuliaLang/julia/pull/42902, but that still needs to be finished up.
