### ISSUE TITLE
FAQ on difference between "using" and "import" misleading?

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#43425]
The [FAQ referenced in the title](https://docs.julialang.org/en/v1/manual/faq/#What-is-the-difference-between-%22using%22-and-%22import%22?) says:
> There is only one difference [...].

It then proceeds to explain that they do "soft" versus "hard" bindings (to use the terminology from issue #39235).

But surely there are other differences? E.g.:
- `using` honors the export lists, while `import` does not
- `import Foo.bar` is the same as `import Foo: bar`, but `using Foo.bar` is different from `using Foo: bar` (at least when `Foo.bar` isn't a module)
- ... ?

It'd be great if that FAQ could be improved to explain this better. While at it, perhaps it could also get a link to https://docs.julialang.org/en/v1/manual/modules "for further details".

(I might take a stab at doing this, but I am not sure when I might find the time; but since I stumbled over this before, I thought I should at least log an issue about it.)

**Comment by AUSt-in** [comment]
Can I work on this issue

**Comment by oscardssmith** [comment]
always.
