### ISSUE TITLE
Repetitive method definitions for Float arithmetic

### ISSUE THREAD

**Issue by julbinb** [JuliaLang/julia#43431]
It seems that arithmetic operations for `Float16`, `Float32`, and `Float64` are identical:
https://github.com/JuliaLang/julia/blob/bf8b91d3e04396355b658ab02624651168cad635/base/float.jl#L393-L412

Perhaps the code would be cleaner if written in the same fashion as for `Int` types, with  `T<:Union{Float16,Float32,Float64}`:
https://github.com/JuliaLang/julia/blob/bf8b91d3e04396355b658ab02624651168cad635/base/int.jl#L86-L88

**Comment by imciner2** [comment]
> Perhaps the code would be cleaner if written in the same fashion as for Int types, with T<:Union{Float16,Float32,Float64}:

Or using the `IEEEFloat` type union that contains those three types (which is what is already done for the `bswap` function)
https://github.com/JuliaLang/julia/blob/bf8b91d3e04396355b658ab02624651168cad635/base/float.jl#L993
