### ISSUE TITLE
Is unpacking into method definition intended behavior?

### ISSUE THREAD

**Issue by grahamas** [JuliaLang/julia#43432]
I'm not sure that this qualifies as a bug, but it's potentially dangerous behavior that I wanted to confirm is intentional.  Here's an illustration of this behavior causing unexpected and difficult-to-diagnose problems:

```julia
julia> my_fn(; kwargs...) = "default behavior ($(string(kwargs)))"
my_fn (generic function with 1 method)

julia> my_fn()
"default behavior (Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())"

julia> a = my_fn(a = 1); b = my_fn(b=2)
"default behavior (Base.Pairs(:b => 2))"

julia> my_fn()
"default behavior (Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}())"

julia> a = my_fn(a = 1), b = my_fn(b=2)
"default behavior (Base.Pairs(:b => 2))"

julia> my_fn()
'd': ASCII/Unicode U+0064 (category Ll: Letter, lowercase)
```
Certainly the second-to-last command was a user error (notice the comma instead of the semicolon), but it's a very common beginner user error, and there's no real indication that anything went wrong. The errors that can come from this are wildly misleading. 

I couldn't find any indication that this behavior was intentional, and it feels like something that just popped out of the recent (very awesome) return unpacking work. If this is the desired behavior (intended or accidental), then fair enough. Generally this kind of feature is something I'm in favor of, I just happened to be burned by it this time.

**Comment by JeffBezanson** [comment]
This isn't intentional in the sense that we really want or need this feature, but intentional in the sense that the assignment rules simply work recursively (i.e. `a, b = c` turns into `a = c[1]; b = c[2]` (sort of) which are then processed recursively). This isn't recent either, but has been around for about as long as I can remember. It arguably gets even wilder, too:
```
julia> for f() = 1:5
        @show f()
       end
f() = 1
f() = 2
f() = 3
f() = 4
f() = 5
```

It's quite possible we should give an error for one or both of these cases; I just naturally shy away from doing more work to add somewhat-arbitrary restrictions :)

**Comment by grahamas** [comment]
Yeah, I would definitely agree any restriction would be pretty arbitrary. 

I suppose this is just the confluence of a bunch of mildly surprising features, which together produce an unexpected behavior (the definition of a corner case):  1) a = (b, c) = d; 2) a(b=1) = 'c'; 3) a, b = "cd"; 4) a, b = "cdefg"; 5) a = (b, c) = "defg": produces a == "defg" and b == 'd' and c == 'e'

I hesitate to call 1-3 surprising, it's more like they're.... fancy? 4 is surprising, but I think I knew about it. 5 is really weird. What's up with that?

In any case, fair enough.
