### ISSUE TITLE
`using xxx` badly interacts with `eval`ed expressions

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#43446]
MRE:
```julia
julia> using JET                        # JET is in the current environment

julia> @eval JET using JuliaInterpreter # JuliaInterpreter is not listed in the current environment, but is a dependency of JET
 │ Package JuliaInterpreter not found, but a package named JuliaInterpreter is available from a registry. 
 │ Install package?
 │   (@v1.8) pkg> add JuliaInterpreter 
 └ (y/n/o) [y]: n
```

Since `using JuliaInterpreter` doesn't require package installation inside the module context of `JET`,
we ideally want to avoid the package installation suggestion in above.

**Comment by JeffBezanson** [comment]
I don't think this is intended to work. We should only switch package environments during loading, not for every `eval`.

**Comment by IanButterworth** [comment]
Even if code loading like this is not guaranteed, I think the way this is behaving is unhelpful.

https://github.com/JuliaLang/julia/pull/43457 is a suggested fix
