### ISSUE TITLE
Inference failure in `maximum` / `minimum`

### ISSUE THREAD

**Issue by mcabbott** [JuliaLang/julia#43461]
Should this be able to infer the type?
```julia
julia> @inferred maximum([1 2; 3 4]; dims=1)
ERROR: return type Matrix{Int64} does not match inferred return type Union{Matrix{Float64}, Matrix{Int64}}
```
The instability is in `Base.reducedim_init(identity, max, [1 2; 3 4], 1)`

**Comment by N5N3** [comment]
Looks like a regression. There's no such instablity on 1.6.4.

**Comment by mcabbott** [comment]
Oh right, this one first appears on 1.7.

My initial example was this, which fails at least from 1.4 onwards:
```
@inferred Base.reducedim_init(norm, max, [1 2; 3 4], 1)
```

**Comment by N5N3** [comment]
This commit fix both case on master. eb472755f30b92f2282daeeb1a8f544dff9e8c6d.
But still don't know where cause another inference regression...
