### ISSUE TITLE
`filter` a `NamedTuple`

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#43473]
`filter` currently does not have a method for `NamedTuple`. Given such a method does exist for dictionaries, maybe it makes sense to extend it in the same way?

**Comment by jakobnissen** [comment]
A problem with this is that it's type unstable, since there is no way to statically know how many elements it should return

**Comment by N5N3** [comment]
Considering we aready have #32968, extend that to `NamedTuple` seems make sense.

**Comment by ParadaCarleton** [comment]
> A problem with this is that it's type unstable, since there is no way to statically know how many elements it should return

How is this solved for tuples (if it is)?

**Comment by N5N3** [comment]
Well `filter(::Tuple)` is stable only if the return type could be infered at compile time, like `filter(i -> i isa Int,(1.0,2,3))`.

**Comment by mcabbott** [comment]
What's the proposed behaviour? Does it follow iteration and work on values, or follow dictionaries and work on pairs?

**Comment by adkabo** [comment]
`filter` should agree with `iterate` in general, and NamedTuple's `filter` should agree with Tuple's `filter`. So, values, I would think.

**Comment by N5N3** [comment]
Our documents says "Return a copy of collection a, removing elements for which `f` is false. The function `f` is passed one argument."
So I prefer `result::NamedTuple` as it keeps `filter(Returns(true), a) == copy(a)`

**Comment by N5N3** [comment]
Dictionaries's `filter` also agree with `iterate`:
```julia
iterate(Dict(1=>1, 2=>:w)) #(Pair{Int64, Any}(2, :w), 6)
```
So I think there's no reason for us to break that?
