### ISSUE TITLE
`isnothing` documentation mentions function that isn't available

### ISSUE THREAD

**Issue by numbermaniac** [JuliaLang/julia#43478]
In a REPL if you use `?isnothing` to get its documentation:
```julia
help?> isnothing
search: isnothing

  isnothing(x)

  Return true if x === nothing, and return false if not.

  │ Julia 1.1
  │
  │  This function requires at least Julia 1.1.

  See also something, notnothing, ismissing.
```

One of the "see also" functions mentioned is `notnothing`. However if you try to get help on that function:

```julia
help?> notnothing
search:

Couldn't find notnothing
Perhaps you meant nothing, isnothing or Nothing
  No documentation found.

  Binding notnothing does not exist.
```
The function doesn't seem to exist.

I discovered that you *can* get it if you put `Base.` in front:
```julia
help?> Base.notnothing
  notnothing(x)

  Throw an error if x === nothing, and return x if not.
```
but this isn't obvious to the end user - they might not know that you have to put `Base.` in front to find the function.

I think either `notnothing` should be exported so it can be found without needing to get to it through `Base`, or the mention of `notnothing` should be removed from `isnothing`'s documentation string. At the moment, this seems like rather unintuitive behaviour.

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
```

**Comment by garrison** [comment]
It sounds to me like `Base.notnothing(x)` is equivalent in behavior to `something(x)`: both expressions raise an ArgumentError if `x === nothing` and return `x` otherwise.  My personal opinion would be to remove it from `isnothing`'s documentation string, rather than export it, given that it is redundant.
