### ISSUE TITLE
better way to reverse a reverse iterator?

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#43482]
According to the documentation, if `itr` is an iterator and `r = reverse(itr)`, then the original iterator `itr` is obtained via `r.itr`.  This API (of retrieving `itr` by querying the field `.itr`) is not very Julian and also limits the possible implementations available to a package-writer.   Could I suggest instead that the original iterator `itr` be obtained via `reverse(r)`?

**Comment by mcabbott** [comment]
Doesn't this already work?
```
julia> Iterators.Reverse(1:3)
Base.Iterators.Reverse{UnitRange{Int64}}(1:3)

julia> Iterators.reverse(ans)
1:3
```
I think that line in the documentation of `Iterators.reverse` is a hint on how to write implementations, maybe it should be removed. What this function returns may not have a field `.itr` at all, so that certainly isn't the recommended way to un-do it:
```
julia> Iterators.reverse(1:3)
3:-1:1

julia> Iterators.reverse(x for x in 1:3)
Base.Generator{StepRange{Int64, Int64}, typeof(identity)}(identity, 3:-1:1)
```

**Comment by stevengj** [comment]
> I think that line in the documentation of Iterators.reverse is a hint on how to write implementations, maybe it should be removed.

Yes, I think it was intended as documentation for people writing methods for `iterate(foo::Iterators.Reverse{Foo})`

**Comment by stevengj** [comment]
Note that `Iterators.reverse(foo)` does *not* need to return an `Iterators.Reverse` object.  e.g.
```jl
julia> Iterators.reverse(1:2)
2:-1:1
```
so the docs should be clarified.
