### ISSUE TITLE
New multithreading segfault in RayTracingWeekend.jl

### ISSUE THREAD

**Issue by claforte** [JuliaLang/julia#43485]
For full context, see https://discourse.julialang.org/t/ray-tracing-in-a-week-end-julia-vs-simd-optimized-c/72958/60

versioninfo():
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 3700X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
Environment:
  JULIA_DEPOT_PATH = ~/.julia/depot
```

Reproduction steps:
1. `git clone https://github.com/claforte/RayTracingWeekend.jl`
2. `cd RayTracingWeekend.jl/`
2. `git checkout claforte/threads_crash1`
3. `cd src/proto`
4. Start Julia with some threads, e.g. 
   `julia --project=. --threads=8 repro_crash.jl`

I commented out the call to @threads, so you can first verify that it runs normally. (And if you open it in vscode or juno and run through each line, you'll see that the last line produces a small raytraced image, like this:

![image](https://user-images.githubusercontent.com/5090329/146690268-4cf70364-418a-46fe-8b60-4384ffd2a1dc.png)

5. To trigger the crash, uncomment the `Thread.@threads` in `src/RayTracingWeekend.jl`, i.e. replace:
```
#Threads.@threads # claforte: uncomment for CRASH?!
	for i in 1:image_height
```
by 
```
Threads.@threads for i in 1:image_height
```
6. Re-run step 4. I consistently get this kind of segmentation fault:

```
claforte@ub-claforte:~/.julia/depot/dev/RayTracingWeekend/src/proto$ julia --project=. --threads=8 repro_crash.jl 

signal (11): Segmentation fault
in expression starting at /home/claforte/.julia/depot/dev/RayTracingWeekend/src/proto/repro_crash.jl:6
jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2347 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2415
wait at ./task.jl:322 [inlined]
threading_run at ./threadingconstructs.jl:34
macro expansion at ./threadingconstructs.jl:93 [inlined]
render at /home/claforte/.julia/depot/dev/RayTracingWeekend/src/RayTracingWeekend.jl:331
unknown function (ip: 0x7ff85b9985f7)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:562
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./Base.jl:386
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
exec_options at ./client.jl:285
_start at ./client.jl:485
jfptr__start_34289.clone_1 at /home/claforte/.julia/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at julia (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4007d8)
Allocations: 12282419 (Pool: 12278054; Big: 4365); GC: 5
Segmentation fault (core dumped)
```

**Comment by claforte** [comment]
I verified that the problem is somehow tied to my recent splitting of classes/functions from one monolithic file (src/old_proto.jl) into:
1. reusable stuff that went in `src/RayTracingWeekend.jl`
2. tests, e.g. `src/proto/repro_crash.jl`

If I run the old code (that defines classes/functions and runs tests along the way) `src/old_proto.jl` with the same environment (or with the `RayTracingWeekend` environment), it still works fine.

**Comment by paulmelis** [comment]
Might be caused by accessing the image array from multiple threads simultaneously?

**Comment by claforte** [comment]
I captured a `rr` trace after applying the zen_workaround.py: https://s3.amazonaws.com/julialang-dumps/reports/2021-12-19T21-16-29-claforte.tar.zst

I thought that'd be a lot harder! :-)

**Comment by claforte** [comment]
> Might be caused by accessing the image array from multiple threads simultaneously?

Maybe, but then, why does it work when everything is the one big old_proto.jl file?
BTW, I suspected that it might have to do with my resetting the RNG seed across each thread (`reseed!()`) but that didn't seem to matter.

**Comment by claforte** [comment]
As an extra experiment (in case I messed up when I extracted the functions), I cut-and-pasted the entire body of `RayTracingWeekend.jl` (except the module/export) at the start of `repro_crash.jl`, and removed the `using RaytracingWeekend` statement there. The crash doesn't occur then. So it's clearly specific to the separation of the code between files.

**Comment by claforte** [comment]
I pinpointed in part the reason for the multithreading crash... see branch `claforte/threads_crash2`:

I:
    - cut-and-pasted whole source code from RayTracingWeekend.jl
      - crash doesn't occur then
    - Commented out redefinitions that make no difference on the crash
    - **The problems seems related to the initialization of `TRNG` and its use in related functions, and my aggressive use of @inline...**
    - search for `claforte CRASH` for my debugging notes

**Comment by claforte** [comment]
I found a work-around. Instead of:
```
# Instantiate 1 RNG (Random Number Generator) per thread, for performance
# Fix the random seeds, to make it easier to benchmark changes.
# Work-around segmentation fault caused by nthreads() returning 1 during precompilation. 
const TRNG = [Xoroshiro128Plus(i) for i = 1:Threads.nthreads()] 
```

... which somehow seems to only allocate 1 item in TRNG, I initialize it to 128 elements...

```
# Assume <=128 threads
const TRNG = [Xoroshiro128Plus(i) for i = 1:128] 
```

I vaguely remember that there's a way to prevent the precompilation from being applied on some global variables? If so could that offer a cleaner approach?

**Comment by vchuravy** [comment]
You should initialize the TRNG from within your `__init__` method.

**Comment by claforte** [comment]
Thanks... unfortunately I couldn't figure out a way to initialize it from __init__ and still get the benefit of @inline for functions that depend on it, etc. So for now, pre-allocating 256 RNGs seems like the practical work-around...

**Comment by vchuravy** [comment]
I am not sure I understand?

I would allocate an empty const array as a global. Then within init resize it, to the current number of threads and initialize it.

**Comment by claforte** [comment]
Thanks, I'll try that! However, IMHO there should be better "guard rails" or at least documentation to prevent this kind of segmentation fault. In this case, this was a toy program so it wasn't particularly hard to debug and work-around... but imagine if this were a 1000-files system... Surely there's a reasonably simple way to prevent others from bumping into the same problem?

1. e.g. make a mention in https://docs.julialang.org/en/v1/manual/multi-threading/ that nthreads isn't reliable during pre-compilation. Or better yet, include a safe and fast example of per-thread RNG initialization. (Since that's what lead me to this problem...)
2. or during pre-compilation, if there's an easy way (?) to identify that nthreads is used in an allocation, print a warning?

**Comment by KristofferC** [comment]
There are guard rails. You just sawed them off: https://github.com/claforte/RayTracingWeekend.jl/blob/6b53e5433cc6591992bfebf9f078c6c2e1b955e7/src/RayTracingWeekend.jl#L52.

Run with `--check-bounds=yes` to force the guard rails back and then you see the error.

**Comment by claforte** [comment]
OK, point taken. So I guess my take-away is, whenever there's a seg fault, turn off all optimizations and run again. Thanks for pointing it out!

**Comment by claforte** [comment]
BTW someone might add this suggestion at the top of this page: https://docs.julialang.org/en/v1/devdocs/backtraces/

**Comment by vchuravy** [comment]
> I recommend someone

Always happy to take PRs :)
