### ISSUE TITLE
Accessing float arrays allocates memory

### ISSUE THREAD

**Issue by yadayadaydadaa** [JuliaLang/julia#43492]
Accessing Float arrays allocates memory, specifically 16 bytes per access, but accessing integer arrays works correctly. 
```console
$ julia -e 'function test(T ::Type) b=Array{T,1}(undef, 100); b.=0; local z=b[1]; a=@allocated for i=1:100 z=b[i] end; println(T, " ", a, " bytes"); end; test(Float64), test(Int64);'
Float64 1600 bytes
Int64 0 bytes
```
The `local z=b[1]` before the `@allocated` loop avoids any compilation-related allocs from being measured, that I get otherwise.
This in Julia 1.7 on macOS 12.0.1, Intel hardware.
Observed the same problem in a bigger program with `--track-allocation=user`.

**Comment by KristofferC** [comment]
Boxes for integers up to a certain number are preallocated. You can see if you take a bigger number, they also start to allocate:

```
❯  julia -e 'function test(T ::Type) b=Array{T,1}(undef, 1000); b.=0; local z=b[1]; a=@allocated for i=1:1000 z=b[i] end; println(T, " ", a, " bytes"); end; test(Float64), test(Int64);'
Float64 23824 bytes
Int64 7824 bytes
```

The solution is to use functions and not global scope.

**Comment by yadayadaydadaa** [comment]
This is something weirder, no problem with type parameters in the test, but I have problems with even no type parameters in. my bigger program.

```
julia -e 'function test(x::T) where T b=Array{T,1}(undef, 10000); b.=0; local z=b[1]; a=@allocated for i=1:10000 z=b[i] end; println(T, " ", a, " bytes"); end; test(1.0), test(1);'
Float64 0 bytes
Int64 0 bytes
```

**Comment by KristofferC** [comment]
(See the updated answer above).

**Comment by yadayadaydadaa** [comment]
fuck youy code formatting idiot no help here

**Comment by KristofferC** [comment]
Locking due to abusive comments.
