### ISSUE TITLE
Complex{Float64} array division receive killed:9 when the length of array is sufficiently large

### ISSUE THREAD

**Issue by Cuda-Chen** [JuliaLang/julia#43503]
I am running into a `killed:9` error when using Julia 1.7.0 on my 2017 iMac (Intel i7) on macOS 10.15. Here are the steps to reproduce :
```julia
n = 90000
T = Complex{Float64}
a = ones(T, n)
b = ones(T, n)
a / b # receive killed:9
```

**Comment by oscardssmith** [comment]
I believe this is a dup of https://github.com/JuliaLang/julia/issues/43008 and https://github.com/JuliaLang/julia/issues/43301. It should be fixed in 1.7.1
