### ISSUE TITLE
`eltype(::Base.Generator)` is too wide

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/julia#43508]
There are lots of instances of `eltype`, but this one is conspicuously missing:
```julia
julia> eltype((x^2 for x in 1:4))
Any
```

This seems to work well:
```julia
julia> function Base.eltype(::Type{Base.Generator{I,F}}) where {F<:Function,I}
           f = F.instance
           Core.Compiler.return_type(f, Tuple{eltype(I)})
       end
```

Then for example,
```julia
julia> eltype((x^2 for x in 1:4))
Int64
```

**Comment by simeonschaub** [comment]
This is intentional. Base has an internal macro `@default_eltype` that's used in this case specifically, so `eltype` does not have to rely on the compiler to figure out types. Also note that `F.instance` is not sufficient in general, since `F` may have fields.

**Comment by cscherrer** [comment]
Thanks @simeonschaub . I don't understand, since the `Any` result above shows that `eltype` **isn't** figuring out types in this case. We can discuss in Zulip, since you say this is intentional.

**Comment by matthias314** [comment]
(Sorry for commenting after such a long time.)

> Base has an internal macro `@default_eltype` that's used in this case specifically

@simeonschaub If `@default_eltype` is the intended solution, would it be a good idea to document that macro? In my experience, it's not uncommon that one wants to figure out the element type of a `Generator`.
