### ISSUE TITLE
RTS 1.6.5 Download link on homepage is broken

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaLang/julia#43504]
See here: https://julialang.org/downloads
<img width="1111" alt="Screen Shot 2021-12-21 at 10 47 54" src="https://user-images.githubusercontent.com/4462211/146967580-f0a823a0-5c95-4c59-a5aa-ddc3376abf0d.png">
/

**Comment by ViralBShah** [comment]
Fixed now.
