### ISSUE TITLE
Cannot push to a vector after applying a 3-arg ldiv!

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#43507]
```julia
using LinearAlgebra
u = rand(2)
A = rand(2,2)
b = rand(2)

push!(b,3.0) # works
u = rand(3)
A = rand(3,3)
ldiv!(u,lu(A),b)

push!(b,4.0) # Error: cannot resize array with shared data
```

_Originally posted by @ChrisRackauckas in https://github.com/JuliaLang/julia/issues/33143#issuecomment-999020297_

**Comment by KristofferC** [comment]
3-arg `ldiv!`, right?

**Comment by simonbyrne** [comment]
The problem are the views, which trigger #33143:
https://github.com/JuliaLang/julia/blob/4b0d6c9407e337c249498185b146f80141c492ca/stdlib/LinearAlgebra/src/factorization.jl#L117-L128

The rationale was to handle factorizations of non-square matrices (#25810).

**Comment by simonbyrne** [comment]
Honestly, by putting a `copy` in the first branch, it seems a bit self-defeating to define the 3-arg `ldiv!` to begin with (you might as well use `/`). But I don't get the rationale for the `view` in the 2nd branch (which is what triggers the problem above)? @andreasnoack any ideas?

**Comment by simonbyrne** [comment]
ah, it seems to be for matrix args: in that case, it probably makes sense to split them out into separate methods.
