### ISSUE TITLE
Dynamic typing whack-a-mole with memory allocations (continued)

### ISSUE THREAD

**Issue by yadayadaydadaa** [JuliaLang/julia#43512]
Continuation to https://github.com/JuliaLang/julia/issues/43492.

```console
Julia> struct Foo a :: Int end; Bar=Foo; function f() return Foo(1); end; function g() return Bar(1); end; af=@allocated f(); ag=@allocated g(); println(af, "; ", ag)
0; 768
```

Figure it out. I'm not wasting more of my time on this memory allocate whack-a-mole. That includes formatting that quick test according to same loser's wishes. My next project will use a statically typed language.

**Comment by Drvi** [comment]
You are missing a `const` when defining `Bar`, non-const globals are giving the compiler hard time, see the relevant [Performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables) section of docs.

**Comment by vchuravy** [comment]
@yadayadaydadaa please be professional. You are welcome to ask for help, but the tone of this post and your previous one is not acceptable.
