### ISSUE TITLE
Update libunwind to 1.6

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/julia#43520]
This is an issue collecting information about a ABI break in libunwind 1.6.x.

https://abi-laboratory.pro/index.php?view=compat_report&l=libunwind&v1=1.5.0&v2=1.6.0&obj=8ee57&kind=abi

A field `load_offset` was added to `unw_dyn_info_t` in https://github.com/libunwind/libunwind/commit/a4014f33775321b4106a1134b89020a7774902dd breaking the ABI.

This affects the use of the symbol `_U_dyn_register` in debuginfo.cpp: https://github.com/JuliaLang/julia/blob/9bb0aeb86090975f54a15082edd76ec19725ebc0/src/debuginfo.cpp#L289
https://github.com/JuliaLang/julia/blob/9bb0aeb86090975f54a15082edd76ec19725ebc0/src/debuginfo.cpp#L1623

**Comment by imciner2** [comment]
We seem to be using 1.7.2 now, so I don't think this tracker is needed anymore.

**Comment by mbauman** [comment]
Implemented by https://github.com/JuliaLang/julia/pull/51424
