### ISSUE TITLE
Skiperator?

### ISSUE THREAD

**Issue by caseykneale** [JuliaLang/julia#43534]
Not sure if this has or hasn't been suggested yet. I was looking for an iterator to just skip the first `N` elements of an iterable. So something like this(note this is a quick hack)
```julia
struct Skip{T}
    xs::T
    offset::Int
end
eltype(::Type{Skip{T}}) where {T} = eltype(T)
Base.length(s::Skip) = length(s.xs) - s.offset
Base.size(s::Skip) = size(s.xs) 
Base.IteratorSize(::Type{<:Skip}) = Base.SizeUnknown()
Base.IteratorEltype(::Type{Skip{T}}) where {T} = Base.IteratorEltype(T)

function skip(xs, offset)
    @assert length(xs) > offset "Iterable has insufficient length for the given Skip Iterator offset."
    @assert offset >= 0 "Offset of a Skip Iterator must be a positive whole number value."
    Skip(xs, offset + 1)
end

function Base.iterate(s::Skip{<:AbstractArray}, state=(1, s.offset))
    n, rest = state[1], Base.tail(state)
    (n - s.offset) >= length(s) && return nothing
    y = iterate(s.xs, rest...)
    y === nothing && return nothing
    return y[1], (n + 1, y[2])
end
```
Would something like this be nice to have in Base? the reason why I think it might belong in here is we already have a skip function for IO streams: https://docs.julialang.org/en/v1/base/io-network/#Base.skip, and having an iterator makes the idea a little more generic. Maybe in a bad way? Not sure, opinions welcome, if it's a "yes" I'll happily clean this up and write up the unit range iterator version(think this breaks on AbstractRanges).

**Comment by jakobnissen** [comment]
This already exists:
```julia
julia> collect(Iterators.drop(1:6, 4))
2-element Vector{Int64}:
 5
 6
```

**Comment by caseykneale** [comment]
woops
