### ISSUE TITLE
const annotate ALL the fields?

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#43550]
A recent PR to Julia allowed fields of mutable structs to be marked as `const`. The advantage of this is that it enables optimizations, and also prevents some bugs by making  it explicit what should be mutated and what shouldn't be.

There are about a dozen mutable types in Base where some fields are not really meant to be replaced - like for example, the vector field of a `BitSet`. Would it be a good idea to go through each type and const annotate the constant fields?

The relevant types are
- [ ] BigFloat
- [ ] BigInt
- [ ] BitArray (#43554)
- [x] BitSet (#43553)
- [ ] Channel
- [ ] Dict
- [ ] Base.Event
- [ ] IOBuffer
- [ ] IOStream
- [ ] IdDict
- [ ] Pipe
- [ ] ReentrantLock
- [ ] Regex
- [ ] Iterators.Stateful
- [ ] Timer
- [ ] WeakKeyDict

**Comment by oscardssmith** [comment]
bigint is interesting in that users often do mutate the value for performance reasons. it would be great if they didn't have to, but it would be a slightly rough and somewhat breaking transition.

**Comment by KristofferC** [comment]
> bigint is interesting in that users often do mutate the value for performance reasons.

Do they really re-bind the fields? Which one of them? I thought they mostly changed the value that the pointer poits to but that doesn't require rebinding the field and is not influenced by `const`.

**Comment by jakobnissen** [comment]
I think the main downside is that const annotating a field does actually take some power away from end-users. There are situations where the easiest solution to a problem is to overwrite some field that is normally supposed to be immutable.
Of course that would be messing with Base's internals, but having the ability to mess with internals at your own risk is generally a good think, in my opinion.

**Comment by KristofferC** [comment]
Same could be said about every struct that is currently not mutable, no?

**Comment by jakobnissen** [comment]
No, because for non-mutable structs, the user can just make a new instance, and it will be semantically indistinguishable from changing the field. For mutable structs, you can have a situation where you need to modify an existing object.

**Comment by rfourquet** [comment]
> Do they really re-bind the fields? Which one of them? 

In a package I rebind all of the fields (though rebinding the `.alloc` field is probably not necessary). This package reuses multiple times a given `BigInt`, by making it wrap independent vectors of limbs representing integers, in order to call GMP routines on it. I hope to get rid of this trick and anyway there would be workarounds if `BigInt` fields were made `const`.

**Comment by jakobnissen** [comment]
From triage comment on the BitArray PR:

> future such changes need to be done on a case-by-case basis as well.

Concerns were raised about causing potential breakage for no clear benefit - for structs where there is a concrete need, just make PRs and it'll be evaluated by itself.

**Comment by vtjnash** [comment]
If you come across a case where it is an obvious benefit, do make a PR. Many on the list above appear somewhat unlikely to benefit.
