### ISSUE TITLE
Windows - lost stack frames in certain situations

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#43582]
MWE:
```
using DataFrames

a = [1, 2, 3]
b = [3, 4]
c() = DataFrame(:a => a, :b => b)
c()
#=
ERROR: DimensionMismatch("column :a has length 3 and column :b has length 2")
Stacktrace:
 [1] DataFrame(columns::Vector{Any}, colindex::DataFrames.Index; copycols::Bool)
   @ DataFrames C:\Users\nicho\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:192
=#

Should be:
#=
ERROR: DimensionMismatch("column :a has length 3 and column :b has length 2")
Stacktrace:
 [1] DataFrame(columns::Vector{Any}, colindex::DataFrames.Index; copycols::Bool)
   @ DataFrames C:\Users\nicho\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:192
 [2] DataFrame(::Pair{Symbol, Vector{Int64}}, ::Vararg{Pair{Symbol, Vector{Int64}}}; makeunique::Bool, copycols::Bool)
   @ DataFrames C:\Users\nicho\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:247
 [3] DataFrame(::Pair{Symbol, Vector{Int64}}, ::Vararg{Pair{Symbol, Vector{Int64}}})
   @ DataFrames C:\Users\nicho\.julia\packages\DataFrames\BM4OQ\src\dataframe\dataframe.jl:245
 [4] c()
   @ Main .\REPL[5]:1
 [5] top-level scope
   @ REPL[6]:1
=#
```

I've been trying to trace this issue, but I'm having trouble building the Windows executables. Windows 1.5, 1.6, and 1.7 builds all have this problem. It works on Nightly. Linux versions (on WSL) do not have the problem.

If it's intentionally or incidentally fixed in 1.8, that's good. Though I don't know if there are differences between a Nightly build and final release build? And I was curious about tracking it down to see if it could/should be backported.

**Comment by BioTurboNick** [comment]
Looking at older DataFrames versions, it appears that the issue was introduced with version 1.0; the previous release, 0.22.7, did not have the issue.

**Comment by vtjnash** [comment]
Probably 2f1f2f6eb6f4060d2e5125c28014cc7c8dc1f740 then?

**Comment by BioTurboNick** [comment]
Hmm... the issue is still present on 1.6.6 though.

**Comment by BioTurboNick** [comment]
Closing because it's fixed.
