### ISSUE TITLE
Performance issue when creating UnitRange

### ISSUE THREAD

**Issue by putianyi889** [JuliaLang/julia#43592]
`UnitRange(start, stop)` checks if `stop>=start` and sets `stop=start-1` otherwise. This process is done by
```julia
unitrange_last(start::T, stop::T) where {T<:Integer} =
    ifelse(stop >= start, stop, convert(T,start-oneunit(stop-start)))
```
No matter if `stop>=start`, the last argument which has two subtractions is computed anyway. It hurts performance when I have to repeatedly create many unitranges where I can guarantee that `stop>start`.

**Comment by N5N3** [comment]
But we need this for safey, and it should not be the bottleneck for most cases.
If this does hurt for your use case. Define somthing like  `UnSafeUnitRange{T} <: AbstractUnitRange{T}` seems a better choise.

**Comment by putianyi889** [comment]
Thanks for the suggestion. The following codes do the trick.
```julia
struct UnsafeUnitRange{T<:Real} <: AbstractUnitRange{T}
    start::T
    stop::T
end
UnsafeUnitRange(start::T, stop::U) where {T,U} = UnsafeUnitRange{promote_type(T,U)}(start,stop)
UnsafeUnitRange(start::T, stop::T) where {T} = UnsafeUnitRange{T}(start,stop)
```

**Comment by vtjnash** [comment]
I looked into this a lot recently, and concluded that if we don't do this on creation, then we need to do it on many accesses, which can be strictly worse, and thus in practice is not better.

**Comment by putianyi889** [comment]
This is true for randomly created ranges which may have bad boundaries such as 3:3.5 or 4:0. However, most of the times we create good ones. If I do `[n-1:n+1 for n in 1:1000000]` then the boundary check is just waste of time. I believe we need something working like `@inbounds` for range creation.
