### ISSUE TITLE
Shorter non-assigning for loop syntax

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#43598]
Would it be a reasonable idea & non-breaking to introduce
```julia
for 1:4
   ...
end
```
as shorthand for a non-assigning for loop?
```julia
for _ in 1:4
    ...
end
```

**Comment by lobingera** [comment]
what is the use case and what do you save here?

**Comment by Keno** [comment]
I'm somewhat sympathetic to the request, but it makes
```
for a in b
end
```
and
```
for (a in b)
end
```
different and the latter quite unexpected I'd guess. I'm not sure saving two characters is worth the hassle.

**Comment by JeffBezanson** [comment]
I believe this has come up before; I agree the potential syntactic ambiguity and potential hiding of bugs don't seem worth it.

**Comment by IanButterworth** [comment]
Ok! Yeah that's reasonable
