### ISSUE TITLE
. 1+.2

### ISSUE THREAD

**Issue by 8G6** [JuliaLang/julia#43590]

**Comment by KristofferC** [comment]
https://0.30000000000000004.com

**Comment by 8G6** [comment]
Yea I know this issue but can we fix that Issue by implementing other representations floating points. Julia is great for faster computation. If that issue is fixed in Julia like in GoLang it will be more precise in mathematical calculations. If we are continuously multiplying a number over a loop the error will get amplified. This happened to me when I was calculating the Routh’s array for a problem in Control Systems. So it will be efficient in scientific computation

**Comment by oscardssmith** [comment]
Julia has bigfloats and decimal numbers.

**Comment by 8G6** [comment]
Can it solve 0.1+0.2 error

**Comment by timholy** [comment]
https://github.com/JuliaMath/Decimals.jl#operations

**Comment by 8G6** [comment]
Ok
