### ISSUE TITLE
use of `/` in LinearAlgebra not documented

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#43607]
Left division using `\` has a nice docstring in LinearAlgebra describing what it does for different linear systems. It would be nice to add a similar explanation for `/`, since the current docstring only describes its behavior for scalar arguments.

**Comment by abhisky2001** [comment]
Hi, can I work on this ? I am new to Open Source and would like to contribute.

**Comment by simeonschaub** [comment]
Welcome! Yes, absolutely, go ahead! You don't need to ask first.

**Comment by abhisky2001** [comment]
Thank you ! Could you please guide me on where can I find the ` \ ` method to update the docstring. 
Using **help** in Julia shell, I could descriptions on the following for `\` :  `\(x, y)`, `\(A, B)` and `(\)(F::QRSparse, B::StridedVecOrMat)` but for `/`, only `/(x, y)` was available. Please correct me if I am wrong, my understanding is I have to add similar explanations for `/` too.

**Comment by huskhi** [comment]
I would like to work on this issue if it hasn't been resolved
