### ISSUE TITLE
Regression in Regex construction (and thereby DateFormat) performance on 1.7

### ISSUE THREAD

**Issue by Sacha0** [JuliaLang/julia#43610]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.5 (2021-12-19)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> using Dates

julia> using BenchmarkTools

julia> letters = String(collect(keys(Dates.CONVERSION_SPECIFIERS)))
"MIHdEepmSUYyus"

julia> pattern = "(?<!\\\\)([\\Q$letters\\E])\\1*"
"(?<!\\\\)([\\QMIHdEepmSUYyus\\E])\\1*"

julia> @benchmark Regex($pattern)
BenchmarkTools.Trial: 10000 samples with 6 evaluations.
 Range (min … max):  4.743 μs … 42.846 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.925 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   5.273 μs ±  1.469 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▇█▅▃▃▁▄▆▅▂▁                                                ▂
  ███████████▇▆▆▆▅▄▅▆▆▄▅▄▃▃▄▃▄▃▄▅▃▃▅▃▃▄▅▄▄▃▄▁▄▄▄▄▄▃▄▅▅▅▅▅▆▇▆ █
  4.74 μs      Histogram: log(frequency) by time     11.4 μs <

 Memory estimate: 32 bytes, allocs estimate: 1.
```
while
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> using Dates

julia> using BenchmarkTools

julia> letters = String(collect(keys(Dates.CONVERSION_SPECIFIERS)))
"MIHdEepmSUYyus"

julia> pattern = "(?<!\\\\)([\\Q$letters\\E])\\1*"
"(?<!\\\\)([\\QMIHdEepmSUYyus\\E])\\1*"

julia> @benchmark Regex($pattern)
BenchmarkTools.Trial: 10000 samples with 5 evaluations.
 Range (min … max):   5.517 μs … 202.124 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.872 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   20.625 μs ±  13.905 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▁   █▆▃▁▂   ▄▅
  █▇▃▅██████▂▄██▇▆▄▃▅▃▄▃▅▄▅▆▄▃▂▂▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁ ▃
  5.52 μs         Histogram: frequency by time         57.9 μs <

 Memory estimate: 32 bytes, allocs estimate: 1.
```
The particular `Regex` comes from the body of `DateFormat(f::AbstractString, locale::DateLocale=ENGLISH)` https://github.com/JuliaLang/julia/blob/28b47b860fab1c0315ca77804fb73dbe344ed4e1/stdlib/Dates/src/io.jl#L382-L383 through with the regression was observed.

Profiling a function that runs the `Regex` constructor call above many times in a loop reveals that expansion of `sljit_malloc_exec` accounts for the difference in time. The first profile below is on 1.6, and the second on 1.7. (Note that for the 1.7 profile, the constructor was called about a quarter the number of times as for the 1.6 profile, yielding a similar number of samples.)

![](https://user-images.githubusercontent.com/5799177/147779424-92e79dd5-b375-484e-b9d1-31f1998153d1.png)

![](https://user-images.githubusercontent.com/5799177/147779427-3680d07e-ac58-46d5-bdf6-acdb97d5d510.png)

**Comment by maleadt** [comment]
Bisected to d336d485466a78826871a7bb1fa2c582730db775, https://github.com/JuliaLang/julia/pull/39524, ref https://github.com/JuliaLang/julia/issues/25997. So I guess this is on purpose. cc @vtjnash

**Comment by JeffBezanson** [comment]
I thought `DateFormat(...)` is not really expected to be super fast. But, it would be really nice to cache the Regex it uses somehow. It might be enough to quickly check whether anything has been added to `CONVERSION_SPECIFIERS`.

**Comment by Sacha0** [comment]
@JeffBezanson meanwhile https://github.com/JuliaLang/julia/pull/43647 😄

**Comment by kpamnany** [comment]
This one seems as well resolved as it's going to be, right @Sacha0?
