### ISSUE TITLE
Julia 1.7 crashes

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/julia#43611]
I have a program that crashes with Julia 1.7, but not with Julia 1.6. If you checkout this commit:
https://github.com/ufechner7/KiteViewer/commit/c1d6c5eec1080a0e0e4e46e49632b4be2d538dc5

and run ./kiteviewer.sh and then click on the button "PLAY" the program will crash on Julia 1.7, but not on 1.6.5.

This code fails:
```
 log = load_log(7, logfile)
```
This works:
```
  log = load_log(7, logfile)
  dummy = log.syslog[1]
```
My assumption: If I create a variable of type struct in Julia 1.7 the members get garbage collected unless accessed at least once in the main program.

For more details see: https://discourse.julialang.org/t/random-crashes-with-julia-1-7/73821/6

**Comment by KristofferC** [comment]
Where is ´load_log` defined?

**Comment by ufechner7** [comment]
Line 477 in this file: https://github.com/ufechner7/KiteUtils.jl/blob/main/src/KiteUtils.jl

**Comment by garrison** [comment]
If you are determined to track this down, I would suggest using [git-bisect](https://git-scm.com/docs/git-bisect) from a known bad 1.7 commit, with 599d3299c9666d8aae13843c3551eaeb2d25f07d as the "good" commit (i.e., the last commit before 1.6 was branched off).

BTW, when I attempt to reproduce, I get the following error:

```
Importing file "data/log_8700W_8ms.csv.xz" ...
LoadError: type QuatRotation has no field w
Stacktrace:
 [1] getproperty(x::QuatRotation{Float64}, f::Symbol)
   @ Base ./Base.jl:42
 [2] df2syslog(P::Int64, df::DataFrames.DataFrame)
   @ Main.Importer ~/src/KiteViewer/src/Importer.jl:54
 [3] import_log()
   @ Main.Importer ~/src/KiteViewer/src/Importer.jl:77
 [4] top-level scope
   @ ~/src/KiteViewer/src/Importer.jl:85
 [5] include
   @ ./client.jl:451 [inlined]
 [6] macro expansion
   @ ~/src/KiteViewer/src/KiteViewer.jl:304 [inlined]
 [7] (::var"#21#34")()
   @ Main ./task.jl:423
in expression starting at /home/garrison/src/KiteViewer/src/Importer.jl:8
```

**Comment by ufechner7** [comment]
@garrison Thanks a lot for testing!

I created a new branch with the name "bug" for reproducing this issue. Reproducible test case (well, on Linux):

```
mkdir tmp
cd tmp
git clone https://github.com/ufechner7/KiteViewer.git
cd KiteViewer
git checkout bug
./kiteviewer_pure.sh 
   - after 1 min GUI appears
   - after one more minute the log file is imported
   - click on the PLAY button
     => program crashes with segfault
```
If you uncomment line 325 of src/KiteViewerPure.jl it doesn't crash on Julia 1.7.
It never crashes on Julia 1.6.

I intend to bisect the commit that caused this bug, but probably not before the weekend...

**Comment by vchuravy** [comment]
If you are on Linux you can also try to use `rr` to create a capture of the issue e.g. `julia --bug-report=rr`

**Comment by ufechner7** [comment]
I found a way to let it ALWAYS crash when using Julia 1.7.1
```
mkdir tmp
git clone -b bug https://github.com/ufechner7/KiteViewer.git
cd KiteViewer
./create_sys_image.sh
    - wait 8 minutes
./kiteviewer_pure.sh 
   - after 12s min GUI appears
   - after one more minute the log file is imported
   - click on the PLAY button
     => program crashes with segfault
```
But that it always crashes happens only when using a custom system image, created with the script create_sys_image.sh .

**Comment by ViralBShah** [comment]
Please reopen if still reoccuring with 1.9.x
