### ISSUE TITLE
@vectorize_2arg should use broadcast

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#4363]
It seems like the `@vectorize_2arg` macro should really be broadcasting.

e.g. I expected this to work and be equivalent to `broadcast(atan2, y, x)`:

```
y = linspace(-1,1,50)
x = y'
theta = atan2(y, x)
```

but it gives `ERROR: argument dimensions must match`.

**Comment by omus** [comment]
Looks like this should be closed.
