### ISSUE TITLE
HMAC functionality needs to be added in SHA.jl documentation

### ISSUE THREAD

**Issue by amirali7e** [JuliaLang/julia#43630]
Minor but needed to point out. SHA.jl does have all the SAH1-3 HMAC functions and if you search in terminal help you can find the functions (some of them) listed below but there is no documentation about them in SHA.jl
hmac_sha1, hmac_sha512, hmac_sha384, hmac_sha256, hmac_sha224
hmac_sha2_512 ,hmac_sha2_384 ,hmac_sha2_256 ,hmac_sha2_224
hmac_sha3_512 ,hmac_sha3_384 ,hmac_sha3_256 ,hmac_sha3_224

**Comment by KristofferC** [comment]
Should be opened at https://github.com/JuliaCrypto/SHA.jl I think.

**Comment by amirali7e** [comment]
Yes, my bad.

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/JuliaCrypto/SHA.jl/issues/82
