### ISSUE TITLE
`rethrow()` -> `throw()`

### ISSUE THREAD

**Issue by adigitoleo** [JuliaLang/julia#43669]
Unless I'm missing something, there is no use of the zero-argument `throw()` at the moment. Also, `?rethrow` discourages using `rethrow(e)` in favour of `throw(e)`. This is a suggestion to delete/deprecate `rethrow` and use a zero-argument form of `throw()` for rethrowing the current error. The motivation is simplification, and to avoid immediately presenting new Julians with caveats (`?rethrow`). Personally I seem to forget about rethrow every time I return to Julia, because I'm thinking in terms of multiple dispatch and `throw()` seems more natural. Python's raise also behaves in a similar way: https://docs.python.org/3/reference/simple_stmts.html#index-27

**Comment by adigitoleo** [comment]
@pcm135 Best to wait on some more opinions for this one. This is not a bug but a feature request.

**Comment by JeffBezanson** [comment]
This is a reasonable idea, but I think there is a further distinction between `throw` and `rethrow`: `throw` creates a new nested exception, while `rethrow` continues as if the exception had not been caught. It's technically possible to have `throw() = rethrow()`, but it's arguably cleaner to give different names to those different behaviors.

**Comment by adigitoleo** [comment]
> arguably cleaner to give different names to those different behaviors

Fair enough. Maybe its a docs issue, probably `?throw` should point people to `rethrow()` in that case.

**Comment by DilumAluthge** [comment]
It seems reasonable to have the docstring for `throw` point to `rethrow`, and also vice versa.

**Comment by adigitoleo** [comment]
Check PR, rethrow already mentions throw so I haven't added it again.
