### ISSUE TITLE
allocs profiler: extend to record Types for all allocations - (fix `UnknownType` in allocations results)

### ISSUE THREAD

**Issue by vilterp** [JuliaLang/julia#43688]
The allocation profiler in https://github.com/JuliaLang/julia/pull/42768 doesn't provide _Types_ for all allocations. There are two types of codepaths which allocations go through:
1. generated code calling `jl_gc_alloc_(jl_ptls_t ptls, size_t sz, void *ty)` or `jl_gc_alloc_string` in `julia_internal.h`: these functions know the _type_ of the object being allocated.
    * which then (sometimes) calls `jl_gc_pool_alloc` / `jl_gc_big_alloc`
2. generated code calling `jl_gc_pool_alloc` or `jl_gc_big_alloc` in `gc.c` directly: these functions do _not_ know the type of the object being allocated.

The latter paths make it difficult to record the type of the allocation, since the type is not passed in — code is generated which calls it with just the size, and then sets the type later.

Another previous profiler PR, https://github.com/JuliaLang/julia/pull/33467, refactored the second codepath to take the type, and modifies the codegen to call the modified codepath, but hasn't been finished. For now, julia's Profile.Allocs functionality (introduced in https://github.com/JuliaLang/julia/pull/42768, https://github.com/JuliaLang/julia/pull/43868, https://github.com/JuliaLang/julia/pull/44043) doesn't do this.

Instead, for those types, we emit the type as `Profile.Allocs.UnknownType` in the allocations profile.

Experiments on a large codebase seem to show around ~40% of allocations have UnknownType, so the tool was still mostly useful. Still, getting the rest would be great!

-------

Fixing this would require either passing the type of the allocation through to those functions by changing the codegen, or removing the instrumentation from those functions and instead emitting the instrumentation directly in the codegen.

**Comment by NHDaly** [comment]
Just as an update: we are currently thinking that there would already be a lot of value in getting just the stacktraces, even if we can't yet get the types for those allocations. So @vilterp has been giving this a stab in https://github.com/vilterp/julia/pull/17.

Even if we solve that, though, we'll probably leave this issue open to cover future work to add the _types_ for all allocation paths.

**Comment by NHDaly** [comment]
I'm going to adjust this Issue to reflect that the _Types_ are missing for some codepaths still.
(And some stack traces are still missing until #44043 is merged)

**Comment by ojwoodford** [comment]
I'm having trouble understanding if this has been addressed yet. I'm using Julia 1.8.2. I've been profiling the allocations of my code, and now 100% (of 160k allocations totalling 2.5MB) of them are UnknownType. Is this expected or not?

**Comment by vilterp** [comment]
Nope, hasn't been addressed yet. Need help from someone who knows the LLVM codegen stuff better. Will close the issue when it is addressed.

We usually see less than 100% UnknownType, but it does depend on the code being profiled 🤷‍♂️
