### ISSUE TITLE
MethodError from base/version_git.sh

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/julia#43716]
This default `GitVersionInfo` does not align with the definition of the struct.

https://github.com/JuliaLang/julia/blob/acb6e16b5b941cd3efc7ddec2217a4497120f8bb/base/version_git.sh#L27

The struct is defined here:
https://github.com/JuliaLang/julia/blob/acb6e16b5b941cd3efc7ddec2217a4497120f8bb/base/version_git.sh#L7-L18

We are missing arguments for the `build_system_commit` and `build_system_commit_short` fields.

The build thus fails when passing arguments to make when trying to build from the source tarball that is not a git repository.

**Comment by DilumAluthge** [comment]
Might be easiest to just switch to using `Base.@kwdef` to provide the default constructor.
