### ISSUE TITLE
Should PriorityQueue allow duplicates?

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/julia#4372]
My understanding of priority queues is that they should allow duplicate keys: this is, for example, how the STL and Java priority queue implementations work as far as I can tell (cf. http://stackoverflow.com/questions/251438/stl-priority-queue-with-duplicate-keys-is-it-possible, http://stackoverflow.com/questions/10469701/how-to-configure-java-priority-queue-to-ignore-duplicates). Right now, our implementation doesn't do this because it acts more like a Dict than a queue.

Could we possibly rename our current implementation to PriorityQueueDict and then implement a more standard PriorityQueue that behaves like a queue/array?

**Comment by tkelman** [comment]
to be reopened at DataStructures.jl

**Comment by ararslan** [comment]
The issue has been reopened at DataStructures: https://github.com/JuliaLang/DataStructures.jl/issues/246
