### ISSUE TITLE
GC Corruption on master

### ISSUE THREAD

**Issue by pchintalapudi** [JuliaLang/julia#43751]
GC Corruption was detected during a recent nanosoldier test run on the Theta v0.1.2 package.

Nanosoldier Commit: JuliaLang/julia@7b628965395f70ea5f7fad84f30a02eaf367df46

Nanosoldier log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/12b9a1b_vs_7b62896/Theta.1.8.0-DEV-7b628965395.log

**Comment by JeffBezanson** [comment]
Tried locally with --check-bounds=yes and it worked, so the problem must be something else.

**Comment by KristofferC** [comment]
It's an old nlopt version. Does it include https://github.com/JuliaOpt/NLopt.jl/pull/142?

**Comment by vchuravy** [comment]
No, the oldest version of NLOpt that contains that is 0.6 https://github.com/JuliaOpt/NLopt.jl/commit/9e6daa0e47e0264e40646ea62fbeabd9e68302b5
