### ISSUE TITLE
Similar function inconsistency

### ISSUE THREAD

**Issue by Hoser00** [JuliaLang/julia#43762]
startswith(url,"/wiki/") && ! occursin(":",url) && ....

The above is a snippet from a book teaching Julia. I'm just starting that book. Julia is new to me, but I've been programming for many decades.

1) These two functions have very similar purposes, but they don't have the same input parameter format. Why? I don't mind memorizing, but I don't also want to memorize exceptions. Related functions should have the same input format, as much as possible. This is why I usually wait to pick up languages after they have worked out nonsense like this, but I'm very excited by Julia.

2) If the second function above has the input parameters reversed, there is a silent error in which everything passes. This type of error is hard to catch without test cases. That suggests it would be helpful to most developers to keep the input parameter order consistent, since they may not be doing careful testing.

I suspect there are many more cases like this. I would take time to gather all the cases that can be found and make the necessary decisions to ensure at least all basic functions are consistent upon release of Julia 2.0. Encourage package developers to adopt standards.

**Comment by mbauman** [comment]
This is a better discussion to be had on [discourse](https://discourse.julialang.org).  The short version is that you can use `contains` to get similar argument ordering, and all three read consistently with the function name placed in between the two args.
