### ISSUE TITLE
clang checksums are missing

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#43768]
4ebca2ffdfa8ad808a4395612383b3bf23ab3cc1 deleted the deps/checksums/clang file, so we see:
```
WARNING: sha512 checksum for Clang.v13.0.0+3.x86_64-linux-gnu-cxx11.tar.gz not found in deps/checksums/, autogenerating...
```

**Comment by DilumAluthge** [comment]
CI should have caught this.... We do a check at the end of CI (both Buildbot and Buildkite) to make sure the working directory is not dirty.

@staticfloat Any idea why CI didn't catch this?

**Comment by DilumAluthge** [comment]
For example, here's one of the Buildbot runs from that PR:

https://build.julialang.org/#/builders/66/builds/1151

> INFO: The working directory is clean.

**Comment by staticfloat** [comment]
We don't normally download clang on CI, that's why it didn't show up.

**Comment by DilumAluthge** [comment]
Okay phew.
