### ISSUE TITLE
Immutable AbstractArray types have different sums

### ISSUE THREAD

**Issue by ianatol** [JuliaLang/julia#43772]
I found this while testing ImmutableArrays (#42465), but its applicable to StaticArrays and presumably other immutable AbstractArray types. I would guess there is some sort of fallback that's responsible for this, will take another look when I have more time

MWE on master:
```
julia> using StaticArrays

julia> a = rand(Float64, 100, 10);

julia> sa = SMatrix{100, 10}(a);

julia> a == sa
true

julia> sum(a) == sum(sa)
false

julia> sum(a)
488.8312263857838

julia> sum(sa)
488.83122638578436
```

**Comment by oscardssmith** [comment]
This is just summation in different order to get better vectorization.

**Comment by ianatol** [comment]
Seems like the result should be the same regardless of order?

**Comment by oscardssmith** [comment]
https://0.30000000000000004.com/

**Comment by ianatol** [comment]
Ok, but this still seems like an issue. Precision is tied to summation order, but why is summation order tied to mutability?

```
julia> a = rand(Float64, 100, 10);

julia> ima = Core.ImmutableArray(a);

julia> using StaticArrays

julia> sa = SMatrix{100,10}(a);

julia> sum(ima) == sum(sa)
true

julia> sum(ima) == sum(a)
false
```

**Comment by N5N3** [comment]
`StaticArrays.jl` defines its own `mapreduce`. So it won't use `Base.mapreduce_impl`.
We have the following in doc
 >   The associativity of the reduction is implementation-dependent. Additionally, some implementations may reuse the
  return value of f for elements that appear multiple times in itr. Use mapfoldl or mapfoldr instead for guaranteed
  left or right associativity and invocation of f for every value.
So I think this is not a problem.
