### ISSUE TITLE
`eachindex(A; dims)` method

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#43801]
Something possibly useful -- the ability to iterate along `eachindex(x; dim=n)`, so that for instance I could iterate through the columns of a matrix using `for index in eachindex(x; dim=1)`.

**Comment by ParadaCarleton** [comment]
[Apparently, this functionality used to be part of the beta, but it was removed.](https://github.com/JuliaLang/julia/blob/d386e40c17d43b79fc89d3e579fc04547241787c/base/abstractarray.jl#L33-L44) I'm not sure why.

**Comment by mcabbott** [comment]
If it's just an index for that dimension, not for a whole slice, then this is `axes(x, dim)`.

**Comment by mcabbott** [comment]
It's possible that the docstring for `eachindex` should mention this, "see also". An easy PR...
