### ISSUE TITLE
error on powers of 2 results

### ISSUE THREAD

**Issue by manuelcaeiro** [JuliaLang/julia#43825]
This is rather weird, but here it goes:
julia> 2^64
0
julia> 2^63
-9223372036854775808
julia> 2^62
4611686018427387904

The only output correct ends at 2^62 (checked with Python).
Thought that was a version specific error - I was using 1.4.x - installed version 1.7.x and got the same result.
Thought that could be a terminal error, changed terminal and got the same result.

**Comment by oscardssmith** [comment]
https://discourse.julialang.org/t/discussion-about-integer-overflow/69627
