### ISSUE TITLE
exponentiation error

### ISSUE THREAD

**Issue by manuelcaeiro** [JuliaLang/julia#43826]
From my Julia repl:

julia> 2^62
4611686018427387904

julia> 2^63
-9223372036854775808

julia> 2^64
0

The last good output is 2^62 (verified with Python).
Thought that could be a version error and updated to version 1.7.1 and got the same result.
Thought that could be terminal related error and changed the terminal and got the same output.

**Comment by johnmyleswhite** [comment]
https://docs.julialang.org/en/v1/manual/faq/#faq-integer-arithmetic

**Comment by oscardssmith** [comment]
This is the second time today you have posted this. GitHub is only meant for bugs. This is intended and clearly documented behavior. don't open another issue about it.

**Comment by manuelcaeiro** [comment]
Thank you @johnmyleswhite
