### ISSUE TITLE
"for z in zip()" doesn't terminate

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#43821]
```jl
for z in zip()
    @show z
end
```
is an infinite loop, printing `z = ()` over and over.

Arguably, it should execute once with `z = ()`, or maybe throw an error, or maybe execute zero times (like Python), but in any case the current behavior seems bad.

**Comment by tkf** [comment]
I'd say that the behavior of `zip` is correct. Observe that `zip` is a monoid in the sense that `zip(a, zip(b, c))` and `zip(zip(a, b), c)` are equivalent modulo how the elements are nested in the resulting element tuples (it's possible to write define an equivalence relation `==′` by ignoring the difference between `(x, (y, z))` and `((x, y), z)`). Furthermore, like other monoids, it defines the vararg method satisfying `zip(args...) ==′ reduce(zip, args)` when `args` is nonempty. From this observation, `zip()` should be the identity element; i.e., `zip(zip(), a) ==′ zip(a)`. An empty stream of `()`s satisfies this. Indeed,

```julia
julia> for (_, x) in zip(zip(), 1:3)  # this is like `0 + 3`
           @show x
       end
x = 1
x = 2
x = 3
```

From this point of view, the definition `foreach(f) = (f(); nothing)` is wrong. It would have been OK if the vararg extension of `foreach` used `product` and not `zip`.

**Comment by Moelf** [comment]
@tkf ehh... why would 99.9% of the user care if `zip` is a monoid? I'm not saying what you're saying is wrong / irrelevant, just asking from a normal user perspective. If you have a user of Julia asking (e.g. a grad student from not CS) "why does empty zip have infinite length", would you give them the above speech?

**Comment by rafaqz** [comment]
Maybe a simpler grad-student ready explanation is "`zip()` is like a functional `while true`".

**Comment by Moelf** [comment]
and what is `zip(a,b)`?.... this doesn't make sense with the "zip things together" metaphor, zip(something, something) is finite length but zip nothing is infinite length?

**Comment by jariji** [comment]
`zip(xss...)`  stops when any of its inputs stops. If `xss` is empty, then none of its inputs ever stops, so the overall expression doesn't terminate. 

Adding inputs can only make it stop sooner. For the opposite behavior, see [`zip_longest`](https://github.com/JuliaCollections/IterTools.jl/issues/57).

This is the same kind of reasoning that explains 

```jl
julia> all(!isempty, Vector[])
true
```

**Comment by Moelf** [comment]
> If xss is empty, then none of its inputs ever stops, 

by this logic `for x in 1:1` should infinite loop

**Comment by Moelf** [comment]
> zip() throw in 2.0, 

I'm 99% sure nobody actually relies on this, we can fix this as a minor change in 1.x

**Comment by jariji** [comment]
`for x in ()` iterates `length(())` times and `for x in 1:1` iterates `length(1:1)` times. I don't see why either would be infinite?

**Comment by LilithHafner** [comment]
> I'm 99% sure nobody actually relies on this producing infinite loop, we can fix this as a minor change in 1.x

Feel free to make a PR; we can check with PkgEval.

**Comment by jariji** [comment]
I've added a PR to document the behavior. This change will reduce the risk of surprise, while retaining the composability.

**Comment by Moelf** [comment]
Is C++ viewed::zip a zip?
