### ISSUE TITLE
Base.merge! does not update input collection if its empty

### ISSUE THREAD

**Issue by Rucksack94** [JuliaLang/julia#43863]
Hey, 

I recognized that the Base.merge! does not update the input dictionary if it is empty.

**MWE**
_This works:_
`
julia> a = Dict(1 => 1.0) <br/>
Dict{Int64, Float64} with 1 entry:
  1 => 1.0
julia> merge!(a, Dict(2 => 2.0))
Dict{Int64, Float64} with 2 entries: 
  2 => 2.0 
  1 => 1.0 
julia> a
Dict{Int64, Float64} with 2 entries:
  2 => 2.0
  1 => 1.0
`

_This does not work:_
`
julia> a = Dict{Int64,Float64}
Dict{Int64, Float64}
julia> merge!(a, Dict(2 => 2.0))
Dict{Int64, Float64} with 1 entry:
  2 => 2.0
julia> a
Dict{Int64, Float64}
`

I expected the output of the second code snippet to be:
`
julia> a
Dict{Int64, Float64} with 1 entry:
  2 => 2.0
`

Is this intentionally or did I missed anything ?

`
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
`
Problem also occurs on my Linux workstation.

**Comment by fredrikekre** [comment]
`Dict{Int64,Float64}` is a type, not a dictionary. You probably wanted `Dict{Int64,Float64}()`. Questions are better for discourse.julialang.org.
