### ISSUE TITLE
IOBuffer `HasLength()` but no `length`

### ISSUE THREAD

**Issue by li1** [JuliaLang/julia#43873]
Hey, while implementing an iterator interface based on https://docs.julialang.org/en/v1/manual/interfaces/, I stumbled over the following:
```
x = IOBuffer()
@assert Base.IteratorSize(x) == Base.HasLength() # true
length(x) # ERROR: MethodError: no method matching length(::IOBuffer)
```

From the docs it sounds like if you implement `HasLength()`, you should also implement `length(iter)`:
```
Value returned by IteratorSize(IterType)       Required Methods
HasLength()	                                   length(iter)
...
```

Is that a conscious Julia design choice or a bug?

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/issues/22279
