### ISSUE TITLE
PCRE2 source address

### ISSUE THREAD

**Issue by einzigsue** [JuliaLang/julia#43917]
Would you please update the source url in deps/pcre.mk to https://sourceforge.net/projects/pcre/files/pcre2/10.36/pcre2-$(PCRE_VER).tar.bz2 or the GitHub one like in the master branch?
I think the ftp one used here https://github.com/JuliaLang/julia/blob/ac5cc99908d463582e66db3368b9b48fae1e2525/deps/pcre.mk#L9 in v1.7.1 is now out-dated. When I tried to compile Julia from source it times out when it fetches pcre2 source code.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaLang/julia/pull/43884 Is already marked for backport to 1.6 and 1.7.
