### ISSUE TITLE
The readme has a dead link

### ISSUE THREAD

**Issue by samfux84** [JuliaLang/julia#43929]
In the readme, there is a paragraph "Building Julia" about building Julia from source. In the first sentence, there is a link "required dependencies" that points to the page

https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#required-build-tools-and-external-libraries

The link does not work, as there is the page

https://github.com/JuliaLang/julia/blob/master/doc/build/build.md

does not exist in this github repository.

**Comment by samfux84** [comment]
Is there any other place, where I can find a list of required dependencies?

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/42568, the link in the readme on the master branch works for me.
