### ISSUE TITLE
Weird outputs of concatenated arrays

### ISSUE THREAD

**Issue by MilkshakeForReal** [JuliaLang/julia#43933]
Hello,

I'm not sure if it is a bug but how should I understand this?

julia> [[1 1]; 2 ;; 3; [3 4]]
2×3 Matrix{Int64}:
 1  3  257641728
 2  3          4

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

**Comment by BioTurboNick** [comment]
Yikes! Since I'm mostly responsible for this feature I can look into it.

Definitely a bug.

**Comment by BioTurboNick** [comment]
This should throw an error. It would be interpreted as equivalent to `[[[1 1]; 2] ;; [3 ; [3 4]]]`

`_typed_hvncat_dims` just needs better validation.
