### ISSUE TITLE
`Timer` requires yield to update

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#43954]
I assume this is expected behavior, but I wanted to check.

This will run indefinitely, not return after 1 second. 
```
julia> begin
           t = Timer(1)
           while isopen(t)
           end
       end
```
Add a yield in the loop and it returns as expected. 

If that is expected, I think adding a note to the `Timer` docstring would be helpful.

**Comment by IanButterworth** [comment]
Perhaps `isopen` should yield to the timer?

**Comment by tkf** [comment]
I think `isopen` should be a non-synchronizing "racy" check. So, yes, I'd say it's expected.
