### ISSUE TITLE
mkpath if a file with the dirname exists throws a confusing error

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/julia#43964]
```
$> mkdir tmp; cd tmp; touch foo
$> julia -e 'mkpath("foo/1")'
ERROR: IOError: mkdir("foo"; mode=0o777): file already exists (EEXIST)
Stacktrace:
 [1] uv_error
   @ ./libuv.jl:97 [inlined]
 [2] mkdir(path::String; mode::UInt16)
   @ Base.Filesystem ./file.jl:183
 [3] mkpath(path::String; mode::UInt16)
   @ Base.Filesystem ./file.jl:234
 [4] mkpath(path::String; mode::UInt16)
   @ Base.Filesystem ./file.jl:232
 [5] mkpath(path::String)
   @ Base.Filesystem ./file.jl:229
 [6] top-level scope
   @ none:1
```

The docstring says

```
help?> mkpath
search: mkpath

  mkpath(path::AbstractString; mode::Unsigned = 0o777)

  Create all directories in the given path, with permissions mode. mode defaults to 0o777, modified by the current file
  creation mask. Unlike mkdir, mkpath does not error if path (or parts of it) already exists. Return path.
```

Of course I understand that the problem here is that `foo` is a **file** but I thought that the error is confusing in this case.

### Suggestion

One way around this could be to iteratively check whether the path given to `mkpath` is a file at some point i.e. add 

```julia
sp = splitpath(path)
for i in 2:length(sp)
  cand = joinpath(sp[1:i]
  if isfile(cand)
      # throw an error indicating there's a file in the path error + break
  end
  isdir(cand) || break
end
```

anyway this is probably a bit clunky, but I was wondering how this particular situation could be caught cleanly and indicated to the user rather than just rethrow the error from `mkdir`

### Alternative suggestion

Just add an indication in the docstring that if there's a file in the way, it will cause an error?

(happy to open a PR either way, just wanted to gather a bit of feedback first, maybe it's just me who finds this problematic)

**Comment by vtjnash** [comment]
There is already code there to determine which parts of the path need to be created, so we might only need to better document that this can fail for other reasons, but just not if the rest of the path needs to be created.
