### ISSUE TITLE
Make `Test.TestLogger` and `Test.LogRecord` part of the public API

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#44016]
This can make writing tests that interact with functions that log a lot easier. The `@test_logs` macros are useful, but work better for small short functions that log one or two things. For end-to-end tests of larger applications, one might want to test things differently, and having access to the actual `LogRecord`s to inspect and test against is very useful. Moreover, one can do something like
```julia
using Test, Logging

function relog(r)
    return Logging.handle_message(global_logger(), r.level, r.message, r._module, r.group,
                                  r.id, r.file, r.line; r.kwargs...)
end

test_logger = Test.TestLogger()
try
    with_logger(test_logger) do
        my_complicated_function_with_a_lot_of_logging()
    end
catch
    println("Caught exception, so dumping logs:")
    foreach(relog, test_logger.logs)
    rethrow()
end
# test against `test_logger.logs`...
```
The benefit of this is you can suppress logs except when an error occurs, in which case being able to see the logs might be useful in understanding the error.

This is all doable already, but it's not part of the public API. My proposal is to simply document and export `Testlogger` and `LogRecord`, to make the above usage not-involving-internals. We could also provide an accessor for the `logs` field if we don't want the field itself to be public API.

xref https://github.com/JuliaLang/julia/pull/43641#issuecomment-1008208484

**Comment by fredrikekre** [comment]
Seems like a good idea. I think it would be nice if it caught all log messages so https://github.com/JuliaLang/julia/pull/43641 was probably not a good idea? It should be a logger for testing the events, not testing the logger itself.

**Comment by ericphanson** [comment]
Yeah, maybe we can revert that and do this instead, because this way gives more access to directly test keywords and things like that.
