### ISSUE TITLE
Default error for `throw`

### ISSUE THREAD

**Issue by adigitoleo** [JuliaLang/julia#44028]
It is currently possible to `throw` anything:

```
julia> try
       throw("yeet")
       catch e
       print(typeof(e))
       end
String
julia> try
       throw(42)
       catch e
       print(typeof(e))
       end
Int64
julia> try
       throw(Matrix{Float64}(undef, 3,3))
       catch e
       print(typeof(e))
       end
Matrix{Float64}
```

I don't think that's a problem in general, but it could be nice to have a method for `throw(e::AbstractString)` that uses a generic error by default. This exception type might also need to be introduced, because the current types are fairly specific. The main use case I have in mind is throwing errors from unpackaged/throwaway code or command line scripts. From this point of view, it could be interesting if it also `exit`ed by default, but I'm not sure if that would be too confusing.

**Comment by jakobnissen** [comment]
We have that already: `error("MyString")`, which throws an `ErrorException`

**Comment by adigitoleo** [comment]
Ah, forgot about that one. Oops.
