### ISSUE TITLE
Mention @ccall in "Calling C and Fortran Code"

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/julia#44038]
In the [Calling C and Fortran Code](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/) section of the documentation, `ccall` is mentioned 64 times, but `@ccall` is mentioned 2 times. Based on very quick attempts, I was not able to use `ccall`, but `@ccall` worked - so it seems easier to me.

Should `@ccall` not be mentioned more? In particular, a pointer to it in one of the first paraphs strikes me as a good idea, to make the user aware of it's existance.

**Comment by vtjnash** [comment]
Yep, would be good. Does not need an issue, just submit a PR to make the docs clearer

**Comment by KronosTheLate** [comment]
That is just the problem - I barely know how to use it, so I don't feel capable of documenting it - I would not know what to write about it xD

**Comment by mkitti** [comment]
I will consider writing this doc.
