### ISSUE TITLE
`has_offset_axes` has some performance regression on master.

### ISSUE THREAD

**Issue by N5N3** [JuliaLang/julia#44040]
MWE:
```julia
julia> tc = reinterpret(Float64,randn(ComplexF64, 100));

julia> @code_warntype Base.has_offset_axes(tc, tc)  # the result is infered as a Const on 1.7.1 and master.
MethodInstance for Base.has_offset_axes(::Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}, ::Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false})
  from has_offset_axes(A...) in Base at abstractarray.jl:107
Arguments
  #self#::Core.Const(Base.has_offset_axes)
  A::Tuple{Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}, Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}}
Body::Bool
1 ─ %1 = Base._tuple_any(Base.has_offset_axes, A)::Core.Const(false)
└──      return %1

julia> @code_typed Base.has_offset_axes(tc, tc)  # But code_typed on master shows `%1::Bool`
CodeInfo(
1 ─ %1 = invoke Base._tuple_any(Base.has_offset_axes::Function, A::Tuple{Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}, Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}})::Bool
└──      return %1
) => Bool

julia> @code_typed Base.has_offset_axes(tc,tc)  # 1.7.1 is much better (although not fully eliminated)
CodeInfo(
1 ─ %1 = Core.getfield(A, 1)::Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}
│   %2 = Core.getfield(A, 2)::Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}
│   %3 = Base.getfield(%1, :parent)::Vector{ComplexF64}
│        Base.arraysize(%3, 1)::Int64
│   %5 = Base.getfield(%2, :parent)::Vector{ComplexF64}
│        Base.arraysize(%5, 1)::Int64
└──      return false
) => Bool
```

**Comment by N5N3** [comment]
I'm a little bit supprised for the bitsect result:
```julia
da437a47d68b01d3c576dabbe18ba023c3f4a634 is the first bad commit
commit da437a47d68b01d3c576dabbe18ba023c3f4a634
Author: Sukera <11753998+Seelengrab@users.noreply.github.com>
Date:   Wed Oct 13 09:29:07 2021 +0200

    Make unitrange_last not assume non-throwing behavior on subtraction, fixes #42528 (#42603)

    This also fixes the behavior for unconstrained ranges.

    Co-authored-by: Sukera <Seelengrab@users.noreply.github.com>

 base/range.jl  |  6 +++---
 test/ranges.jl | 20 ++++++++++++++++++++
 2 files changed, 23 insertions(+), 3 deletions(-)
```

**Comment by Seelengrab** [comment]
Well, with `ifelse`, the test added in that commit fails though because the `else` branch may throw :shrug: How bad is the regression? Maybe there's some other way this can be fixed?

**Comment by N5N3** [comment]
I found this when benching complex matrix times real vector.
For 100 * 100 size, the cost of `Base.require_one_based_indexing` is about 300ns. while `BLAS.gemv!` (without `Base.require_one_based_indexing`) is about 1.7us.

It looks like our optimizer refuse to eliminate some thing like
```julia
───       goto #3 if not %10
2 ──       goto #4
3 ──       goto #4
```
and the calculation of  %10 could not be eliminated. (Thus `_tuple_any` is not inlined anymore.)

I believe future optimizer improvement could solve this problem.
As a temporary fix, I think we'd better replace `first(axes(A, i))` in `has_offset_axes ` with `firstindex(A, i)`.
And define some thing like 
```julia
firstindex(a::NonReshapedReinterpretArray, i::Integer) = firstindex(a.parent, i)
firstindex(S::SubArray, i::Integer) = i <= ndims(S) ? firstindex(S.indices[i]) : 1
```

**Comment by Seelengrab** [comment]
Yeah, that whole `goto` stack seems pretty suspect to me already :thinking: 

The `firstindex` fix sounds good to me, if it does indeed fix your regression and keeps the true branch in `unitrange_last` :)

**Comment by vtjnash** [comment]
Perhaps we should just update our inlining cost to ignore branches that land on another branch instruction. We know that pattern will be folded away, but just don't currently enable the logic to do it early.

**Comment by vtjnash** [comment]
oh, nevermind, the cost is already zero. And no, that is not worth it (costs too much to update the domtree)

**Comment by vtjnash** [comment]
@aviatesk thought you might be a bit interested in the effects computed here. Currently we have that arraysize taints the consistency of this call, so we cannot eliminate the `firstindex` call, which is defined as `first(first(axes))`:
```
[(!c,+e,+n,+t,+s,+m)]size(a::Vector) @ Base array.jl:149
Variables
  #self#::Core.Const(size)
  a::Vector{ComplexF64}

│ ─ %-1  = invoke size(::Vector{ComplexF64})::Tuple{Int64}
1 ─ %1 = Base.arraysize(a, 1)::Int64
│   %2 = Core.tuple(%1)::Tuple{Int64}
└──      return %2
```

**Comment by aviatesk** [comment]
I think `arraysize` can be `:consistent` as far as the input array is non-global (so technically we can mark `arraysize` as `CONSISTENT_IF_INACCESSIBLEMEMONLY`). But still we won't be eligible for concrete-eval it, as we never form `Const` for local mutable allocations anyway.
