### ISSUE TITLE
Windows getenv does not see ENV changes

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/julia#44054]
As previously noted in #11215, Windows tracks two environmental variable tables. Some libraries using `getenv` may not see changes made by manipulating `ENV` in Julia. For example, the HDF5 library uses `getenv` on Windows.

Julia sets environment variables using `SetEnvironmentVariableW`:
https://github.com/JuliaLang/julia/blob/7ecbfa9c926bdf380f824766b9d165ec9b133eaa/base/env.jl#L23-L30

```julia
julia> ENV["HDF5_PLUGIN_PATH"]
"C:\\quantum\\powered\\plugins"

julia> unsafe_string(ccall(:getenv, Cstring, (Cstring,), "HDF5_PLUGIN_PATH"))
"C:\\quantum\\powered\\plugins"

julia> ENV["HDF5_PLUGIN_PATH"] = raw"C:\plugins"
"C:\\plugins"

julia> ENV["HDF5_PLUGIN_PATH"]
"C:\\plugins"

julia> unsafe_string(ccall(:getenv, Cstring, (Cstring,), "HDF5_PLUGIN_PATH"))
"C:\\quantum\\powered\\plugins"

julia> ccall(:_putenv_s, Cint, (Cstring,Cstring), "HDF5_PLUGIN_PATH", raw"C:\julia_plugins")
0

julia> ENV["HDF5_PLUGIN_PATH"]
"C:\\julia_plugins"

julia> unsafe_string(ccall(:getenv, Cstring, (Cstring,), "HDF5_PLUGIN_PATH"))
"C:\\julia_plugins"

julia> ccall(:_wputenv_s, Cint, (Cwstring,Cwstring), "HDF5_PLUGIN_PATH", raw"C:\plugins\for\HDF5_jl")
0

julia> ENV["HDF5_PLUGIN_PATH"]
"C:\\plugins\\for\\HDF5_jl"

julia> unsafe_string(ccall(:getenv, Cstring, (Cstring,), "HDF5_PLUGIN_PATH"))
"C:\\plugins\\for\\HDF5_jl"
```

To facilitate the use of Julia with the use of standard C (C99, C11) software on Windows, we should consider using `_wputenv_s` where possible or provide an alternative facility to facilitate interop.

# References (via [cppreference.com](https://en.cppreference.com/w/c/program/getenv))
C11 standard (ISO/IEC 9899:2011):
* 7.22.4.6 The getenv function (p: 352-353)
* K.3.6.2.1 The getenv_s function (p: 606-607)

C99 standard (ISO/IEC 9899:1999):
* 7.20.4.5 The getenv function (p: 317)

C89/C90 standard (ISO/IEC 9899:1990):
* 4.10.4.4 The getenv function

Windows documentation
* [`_putenv_s`, and `_wputenv_s`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-s-wputenv-s?view=msvc-170)
* [`_putenv` and `_wputenv`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-wputenv?view=msvc-170)
* [`getenv` and `_wgetenv`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-wgetenv?view=ms`vc-170)
* [`getenv_s` and `_wgetenv_s`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-s-wgetenv-s?view=msvc-170)

**Comment by mkitti** [comment]
Cross reference to similar issue encountered by Python:
https://bugs.python.org/issue39406

**Comment by musm** [comment]
Interesting find. 

I found this comment insightful from the  linked  Python thread

> `_wputenv` keeps Python's copy of the environment block in sync with CRT's copy, which in turn calls `SetEnvironmentVariableW` to sync with process environment block. The CRT's copy of the environment excludes and disallows variable names that start with "=". Because the interpreter initializes `os.environ` from the CRT environment, Python has never included or allowed 'hidden' variables such as "=C:".

**Comment by mkitti** [comment]
Here is the current code reference from cpython main:
https://github.com/python/cpython/blob/06b8f1615b09099fae5c5393334b8716a4144d20/Modules/posixmodule.c#L10964-L10970

It echoes the comment above:

```
    /* _wputenv() and SetEnvironmentVariableW() update the environment in the
       Process Environment Block (PEB). _wputenv() also updates CRT 'environ'
       and '_wenviron' variables, whereas SetEnvironmentVariableW() does not.

       Prefer _wputenv() to be compatible with C libraries using CRT
       variables and CRT functions using these variables (ex: getenv()). */
    int err = _wputenv(env);
```

**Comment by mkitti** [comment]
> It sounds like we switched over in #4240 due to Unicode compliance issues with `_wputenv_s `

I think we switched from `SetEnvironmentVariableA` to `SetEnvironmentVariableW` via that issue and related pull requests. I do not see `_wputenv_s` or `_wputenv` anywhere in the code base or history.

**Comment by mkitti** [comment]
Looks like RCall.jl also needs this.

https://github.com/JuliaInterop/RCall.jl/blob/65cd62e5bf54f2214042bcaac7697440600e2881/src/setup.jl#L68-L80

```
        # TODO: Use direct Windows interface, see §8.2.2 "Calling R.dll directly"
        # of "Writing R Extensions" (aka R-exts)


        Ruser_ptr = ccall((:getRUser,libR),Ptr{UInt8},())
        Ruser = unsafe_string(Ruser_ptr)


        ccall(:_wputenv,Cint,(Cwstring,),"PATH="*ENV["PATH"]*";"*dirname(libR))
        ccall(:_wputenv,Cint,(Cwstring,),"R_USER="*Ruser)


        # otherwise R will set it itself, which can be wrong on Windows
        if !("HOME" in keys(ENV))
            ccall(:_wputenv,Cint,(Cwstring,),"HOME="*homedir())
        end
```

**Comment by mkitti** [comment]
ReactOS implementation:

https://github.com/reactos/reactos/blob/c23ce9dfad8e4a3a104c9b95b993e9872e84e243/sdk/lib/crt/misc/environ.c#L198-L210

Essentially it does some extra work, and at the end calls `SetEnvironmentVariableW`.

**Comment by musm** [comment]
@vtjnash  is there any reason why we can't use `_wputenv_s` ?

**Comment by vtjnash** [comment]
We just really don't like to use `msvcrt`, since many other libraries won't use it either and will be incompatible with it. It is also MT-unsafe. If you want to set environment variables, you really should be setting the before the process starts.

**Comment by mkitti** [comment]
While I agree that environmental variables are problematic and thread safety is an issue, is the situation any different for `putenv` for POSIX-compliant systems?

**Comment by vtjnash** [comment]
Yes, it is very rare for POSIX systems to be as MT-unsafe or to load multiple copies of this library. Both are very common situations on Windows, as noted in #11215

**Comment by mkitti** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/functions/setenv.html

> The setenv() function need not be thread-safe.

**Comment by mkitti** [comment]
I will close this with a new plan to address the specific HDF5 issue in HDF5.jl.

This is similar to the matter reported here:
https://forum.hdfgroup.org/t/setting-plugin-path-programmatically/3970/6

HDF Group addressed this in HDFFV-10143 by adding the H5PL interface:
https://github.com/HDFGroup/hdf5/blob/01092658a3095c31d7dc1ed1beebbd965095c244/release_docs/HISTORY-1_8.txt#L1202-L1221
