### ISSUE TITLE
Cholesky fails for `Hermitian{.., Diagonal}`

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#44053]
There appears to be some missing method that handles Hermitian/Symmetric wrappers around special matrices. 
```julia
julia> cholesky((1.0I(3)))
Cholesky{Float64, Diagonal{Float64, Vector{Float64}}}
U factor:
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> cholesky(Hermitian(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Hermitian{Float64, Diagonal{Float64, Vector{Float64}}})

julia> cholesky(Symmetric(1.0I(3)))
ERROR: MethodError: no method matching cholesky(::Symmetric{Float64, Diagonal{Float64, Vector{Float64}}})
```
I assume the pattern `cholesky(Hermitian(Σ))`, i.e., automatically wrapping symmetric matrices in a `Hermitian` wrapper is quite common, so it would be great if it worked for all `AbstractMatrix`.

Tested on Julia v1.7.1

**Comment by dkarrasch** [comment]
The simplest solution is perhaps to remove the restriction to `StridedMatrix`s in out-of-place `cholesky` methods that form a `cholcopy` anyway, and make that cholcopy form a mutable copy via 3-arg `similar`, and specialize some structured matrix types to improve memory consumption.
