### ISSUE TITLE
Julia 1.7.2 documentation error

### ISSUE THREAD

**Issue by MichailVestnik** [JuliaLang/julia#44051]
H!

I want to download the documentation in PDF, but the link error 404.

https://docs.julialang.org/en/v1/
https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.7.2.pdf

Спасибо!

**Comment by ViralBShah** [comment]
Is this just waiting for the latest CI run to generate the PDF?

https://github.com/JuliaLang/docs.julialang.org/tree/assets

@fredrikekre @DilumAluthge May either of you know?
