### ISSUE TITLE
Interpolation using `$` with `@cfunction` in a macro reported as a closure and won't precompile on an M1 Mac.

### ISSUE THREAD

**Issue by jackbeagley** [JuliaLang/julia#44069]
Interpolation using `$` with `@cfunction` inside of a macro reported as a closure and won't precompile on an M1 Mac.

To reproduce:
`using ArchGDAL` on an M1 Mac.

Alternatively:
```
macro cplprogress(progressfunc)
    @cfunction($(esc(progressfunc)), Cint, (Cdouble, Cstring, Ptr{Cvoid}))
end

progressfunc = x -> x

@cplprogress(progressfunc)
```

Computer: M1 Pro Macbook
Julia: 1.7.1 darwin-aarch64
OS: 12.1 Monterey

Just getting my head around `@cfunction`, closures and macros but from what I can tell, `@cfunction($(esc(progressfunc)), Cint, (Cdouble, Cstring, Ptr{Cvoid}))` is not in fact a closure, but simply interpolation. Please let me know if I'm wrong, but if not I believe this would be a bug in "closure detection"?

**Comment by vtjnash** [comment]
The [Discourse forum](http://discourse.julialang.org) is a better place for getting help on usage questions. It'll be easier to answer your question over there, where there are better controls for message formatting and threading.
