### ISSUE TITLE
MacBook Pro M1 Max doesn't give correct number of threads with `--threads=auto`

### ISSUE THREAD

**Issue by navidcy** [JuliaLang/julia#44067]
I get different results for `Threads.nthreads()` on a Macbook Pro M1 Max using the latest version of julia and the tagged v1.7.1.

In particular, with latest Julia version I get 6! But when I look at System Info I see 8?

<img width="389" alt="Screen Shot 2022-02-08 at 7 27 47 am" src="https://user-images.githubusercontent.com/7112768/152866462-29e497c4-c45c-4c58-aae6-8b629cffd0dc.png">

For `julia#master` at e0a4b7727c
```
navid:~/ $ /Users/navid/julia/julia --threads=auto
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.1455 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  Commit e0a4b7727c (0 days old master)
|__/                   |

julia> versioninfo()
Julia Version 1.8.0-DEV.1455
Commit e0a4b7727c (2022-02-06 12:55 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, cyclone)
Environment:
  JULIA_EDITOR = vim

julia> Threads.nthreads()
6
```
while on Julia v1.7
```Julia
navid:~/ $ /Users/navid/julia-1.7/julia --threads=auto
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_EDITOR = vim

julia> Threads.nthreads()
10
```

Probably the fix is related to this bit?
https://github.com/JuliaLang/julia/blob/546a77474bf730569e651b60415a187da769fb64/src/sys.c#L598-L630

@glwagner, @sandreza

**Comment by mkitti** [comment]
See https://github.com/JuliaLang/julia/pull/42099
Ping @staticfloat 
![image](https://user-images.githubusercontent.com/8062771/152888979-694b8d9e-3cac-404d-b528-fa358932c7f3.png)
No, Picard, there seem to be only 2.

**Comment by mkitti** [comment]
Since reference [0] got cut off, here it is again.

[0] https://github.com/pytorch/cpuinfo/blob/8ab2db2d405436f1014ed603021545b3b6b6f1ae/src/arm/mach/init.c#L161-L163

**Comment by navidcy** [comment]
@mkitti, that's relevant. But on Apple M1 Max processor one needs to subtract only 2 (not 4, as done in https://github.com/JuliaLang/julia/blob/546a77474bf730569e651b60415a187da769fb64/src/sys.c#L628). Right?

**Comment by mkitti** [comment]
Right. See this comment: https://github.com/JuliaLang/julia/pull/42099#issuecomment-912707126 .

There appears to be a way to query this information rather than hard code it.

**Comment by gbaraldi** [comment]
@navidcy Could you kindly build the following C script and say what it prints for you.
```c
#include <sys/sysctl.h>
#include <stdio.h>

int main()
{
    char str[7];
    size_t len = 7;
    sysctlbyname("kern.osrelease", str, &len, NULL, 0);
    printf("%s\n", str);
    if (str[0] > 1 && str[1] > 0)
    {
        len = 4;
        int ncpus;
        sysctlbyname("hw.perflevel0.physicalcpu", &ncpus, &len, NULL, 0);
        printf("%d\n", ncpus);
    }
}
```

**Comment by navidcy** [comment]
Sure, but I'd like some help with C.

How do I build this?

**Comment by gbaraldi** [comment]
It should be enough to put it into a file called `test.c` somewhere in your computer, navigate to that place with your terminal and do `clang test.c -o test` after that do `./test` and it should print two lines.

**Comment by navidcy** [comment]
```
21.3.0
8
```

**Comment by gbaraldi** [comment]
Thanks for the help. I will open a PR that will make it detect the correct number of threads.
