### ISSUE TITLE
allocation profiler not threadsafe

### ISSUE THREAD

**Issue by vilterp** [JuliaLang/julia#44099]
@vtjnash pointed out this thread safety bug not caught by our tests: https://github.com/JuliaLang/julia/pull/42768#discussion_r803097408

This can result in multiple threads corrupting the stack traces from each others' allocs, leading to a corrupted profile.

Fix involves keeping a buffer per thread.
EDIT: And/or maybe reusing the existing backtrace buffer in the `ptls` object. (See the linked thread, above)

cc @NHDaly

**Comment by Sacha0** [comment]
(Assigned to Pete at Pete's request :).)
