### ISSUE TITLE
load behaviour is different with/without begin...end

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#44104]
I come originally from https://discourse.julialang.org/t/from-from-fromfile-does-not-work-inside-begin-en-for-local-module-workflow/76100/2

MWE

```julia
julia> begin
       using LinearAlgebra
       LinearAlgebra.@commutative
       end
ERROR: LoadError: UndefVarError: LinearAlgebra not defined
in expression starting at REPL[1]:3
```

I think Pluto users put every commands inside `begin ... end` so this should be considered equivalent to have the following directly in REPL

```julia
using LinearAlgebra
LinearAlgebra.@commutative
```

I'm not sure why the module followed with a macro is somehow evaluated before the module is loaded? I think most people would expect this to work.

**Comment by simeonschaub** [comment]
Those two aren't equivalent. Macro expansion will always happen on the whole top-level expression before any code is evaluated.
