### ISSUE TITLE
The `Sockets` tests frequently fail non-deterministically on CI

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#44124]

**Comment by Keno** [comment]
Do we have an example log with rr trace?

**Comment by DilumAluthge** [comment]
The `tester_linux64_g1_rrst` job on this run: https://buildkite.com/julialang/julia-master/builds/6515#7c5a141b-1998-4c35-8fd1-2cc218e2db15

**Comment by Keno** [comment]
Excellent, we can look at the rr trace.

**Comment by DilumAluthge** [comment]
Full disclosure: I don't know if all these Sockets failures are always the same bug, or if there are multiple different bugs. It's kind of hard to tell just from reading the CI logs.

**Comment by vtjnash** [comment]
This log was actually
```
      From worker 7:	KILLING BY SOCKETS TEST WATCHDOG
```
Which happened because we kept adding a iptables rule to drop localhost6 traffic
