### ISSUE TITLE
Inconsistent behavior of indeterminate forms

### ISSUE THREAD

**Issue by agnius-vasiliauskas** [JuliaLang/julia#44133]
At first I want to express a joy that finally arrived a programming language which doesn't torture a developer with hundreds of nested for loops, i.e. Julia has a very nice short syntax of defining nested for loops :-) Overall it feels like Julia language respects developer feelings in day-to-day tasks, keep it up !

Now about issue. Mathematically there's 7 [indeterminate forms](https://en.wikipedia.org/wiki/Indeterminate_form), of which 3 cases in Julia returns '1' instead of 'NaN' as it should be, namely the cases :

> 0 ^ 0 = 1 → FAIL, must be NaN
1 ^ ∞ = 1.0 → FAIL, must be NaN
∞ ^ 0 = 1.0 → FAIL, must be NaN

Minimal code for reproducing error :
```
∞=Inf
indeterminate_forms = [:(0/0),:(∞/∞),:(0*∞),:(∞-∞),:(0^0),:(1^∞),:(∞^0)]
for f = indeterminate_forms
    println(f," = ",(res=eval(f);res),isnan(res) ? " → Ok" : " → FAIL, must be NaN")
end
```

Debug info:

> Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

Rationale for it would be that if Julia is scientifically-oriented and has started to correctly return **Inf** for x/0, instead of division by zero error,- then ALL indeterminate forms must be processed correctly as math rules states.

**Comment by oscardssmith** [comment]
I'm pretty sure we're following ieee here

**Comment by agnius-vasiliauskas** [comment]
> I'm pretty sure we're following ieee here

So this mathematical inconsistency doesn't bothers you ? I find it strange that 4/7 indeterminate forms are mathematically correct, while the rest 3/7 - are not. Whatever IEEE or other standard you are following it's a bug, because in one way or the other Julia is closer to the math and numerical computations, so must respect math more than "classical programming languages", isn't it ?

**Comment by oscardssmith** [comment]
The short answer is no. IEEE specifies these definitions because although they aren't necessarily strictly correct mathematically, they are very useful empirically (and have relatively reasonable mathematical justification).
