### ISSUE TITLE
wrong order of source registers in at&n code_native

### ISSUE THREAD

**Issue by mchristianl** [JuliaLang/julia#44146]
Hello,

It might be that the source registers are printed in wrong order for some instructions in the AT&T syntax on x86 assembly when [we have](http://web.mit.edu/rhel-doc/3/rhel-as-en-3/i386-syntax.html)
- Intel: mnemonic dest source1 source2
- AT&T: mnemonic source1 source2 dest

(or is this a [known bug](http://web.mit.edu/rhel-doc/3/rhel-as-en-3/i386-bugs.html)?)

E.g. in the following example

```julia
using SIMD
f(a,b) = (a,b,a-b)
code_native(f,(Vec{4,Int64},Vec{4,Int64}); debuginfo=:none)
```
the intel syntax for `ymm2 = ymm0 - ymm1` is `vpsubq dest, source1, source2`

```asm
...
vpsubq  ymm2, ymm0, ymm1             ; ymm2 = ymm0 - ymm1 = a-b
vmovdqa ymmword ptr [rdi     ], ymm0 ; store a
vmovdqa ymmword ptr [rdi + 32], ymm1 ; store b
vmovdqa ymmword ptr [rdi + 64], ymm2 ; store a-b
...
```
but the AT&T syntax is `vpsubq source2, source1, dest`

```asm
...
vpsubq  %ymm1, %ymm0, %ymm2 ; ymm2 = ymm0 - ymm1 = a-b
vmovdqa %ymm0,   (%rdi)     ; store a
vmovdqa %ymm1, 32(%rdi)     ; store b
vmovdqa %ymm2, 64(%rdi)     ; store a-b
...
```

where it should be `vpsubq source1, source2, dest` instead.

This is on
```
Julia Version 1.7.1
Commit ac5cc99908* (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, skylake)
Environment:
  JULIA_LOAD_PATH = /usr/share/gmsh/api/julia/:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

**Comment by vtjnash** [comment]
That is only for the 80386 instructions. For floating point instructions, the convention is frequently different. You will need to consult a reference source for each instruction to know the source and dest.
