### ISSUE TITLE
`which("julia")` causes seg fault

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#44153]
problem:
```
julia> which("julia")

signal (11): Segmentation fault
```
This should throw an error instead.

Version 1.8.0-DEV.1501 (2022-02-12)

**Comment by simeonschaub** [comment]
@aviatesk You removed the input type annotations in #43087. Is there a way to achieve the same behavior wrt specialization while also keeping the annotations? We could manually throw errors, but that seems cumbersome. Or should we just revert #43087?

**Comment by giordano** [comment]
@jlapeyre did you mean `Sys.which("julia")`?

> this is a regression since 1.6

In v1.6 it returned a `MethodError` because he's likely trying to call the wrong function.

**Comment by jlapeyre** [comment]
Yes, I did mean to say `Sys.which("julia")`. I tried to call the wrong function, so it should throw an error, not segfault.
It looks like such an obvious mistake that I'm surprised it wasn't found. I guess this is the first issue. I searched for it.

**Comment by giordano** [comment]
Sure, the segfault isn't nice and should be fixed anyway, but I just want to stress that no working code should be affected by this issues, since `which(::String)` isn't supposed to work.

**Comment by jlapeyre** [comment]
> I just want to stress that no working code should be affected

Oh yes, important distinction.
