### ISSUE TITLE
add `Base.url(::Method)` result to `show(io, ::Method)`

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#44151]
I'd like to know if people support this.

now:
```julia
julia> @which sum(1:3)
sum(r::AbstractRange{<:Real}) in Base at range.jl:1312
```

proposed:
```julia
julia> @which sum(1:3)
# https://github.com/JuliaLang/julia/tree/bf534986350a991e4a1b29126de0342ffd76205e/base/range.jl#L1312
sum(r::AbstractRange{<:Real}) in Base at range.jl:1312
```
many terminals have the ability to "open URL in browser". Besides, assuming you're sharing the result to other people, it's nice to have a perm github url than trying to go to the file and look around the line number.

**Comment by giordano** [comment]
> it's nice to have a perm github url than trying to go to the file and look around the line number.

Isn't that what `@less` and `@edit` are for?

**Comment by Moelf** [comment]
I want to point it to someone on Discord or Slack and presumably they want to look around for a bit to gain insight without me pasting the whole file content.

They may not have a local Julia and editor configured and/or not the same Julia version

**Comment by vtjnash** [comment]
I think there is something elegant about saying the code is a particular URL, and not just a copy of that file on your local machine.

**Comment by Moelf** [comment]
https://github.com/adrhill/BrowserMacros.jl
