### ISSUE TITLE
Win 7 compatable in VScode and Atom from Julia 1.7.x

### ISSUE THREAD

**Issue by ajsagit** [JuliaLang/julia#44171]
Julia 1.7.x can not be started from VScode and Atom on Win 7.
But no problem on Win 10 or Win11.
Julia 1.6.x no problem.

VScode err
`Could not start the Julia language server. Make sure the configuration setting julia.executablePath points to the Julia binary.`
Atom err
`Julia could not be started.`

**Comment by vtjnash** [comment]
Win 7 is well past consumer EOL (more than 2 years). Unless you have an (expensive) support contract from Microsoft, it is unsupported and a security risk to use. https://julialang.org/downloads/#supported_platforms
