### ISSUE TITLE
Support AVX2 and BMI2 instructions

### ISSUE THREAD

**Issue by ihnorton** [JuliaLang/julia#4418]
Reminder  to revert the [temporary fix](https://github.com/JuliaLang/julia/commit/d5dc2262564beeea6d0269904c3e6aee3a7d8a58) for #4362.

Related LLVM bug: http://llvm.org/bugs/show_bug.cgi?id=17422

This would likely be subsumed by [switching to MCJIT](https://github.com/JuliaLang/julia/issues/3922).

See also a [similar bug](http://llvm.org/bugs/show_bug.cgi?id=13349) in AVX support, resolved by backporting some functionality from MCJIT.

**Comment by JeffBezanson** [comment]
Bump. Can we remove the workaround now?

**Comment by vtjnash** [comment]
it's been conditional on the llvm version for a long time, I just don't feel like doing blame to check which commit did it

**Comment by kmsquire** [comment]
Just for documentation: workaround is here: https://github.com/JuliaLang/julia/blob/master/src/codegen.cpp#L5635-L5639

I don't see a condition on LLVM version, but maybe I missed it...?

**Comment by vtjnash** [comment]
`#ifndef USE_MCJIT` is a fake-version test since it is always false for llvm < 3.4 and always true for llvm > 3.4 (that excludes 3.4, but it's JIT options were broken anyhow)
