### ISSUE TITLE
`*(Bidiagonal(:L), Bidiagonal(:U))` should give `Tridiagonal`

### ISSUE THREAD

**Issue by putianyi889** [JuliaLang/julia#44187]
Currently this multiplication is super slow and gives a `SparseCSC`.

**Comment by dkarrasch** [comment]
On current master, this gives a dense matrix. The problem is with type stability here. What should `Bidiagonal(U)*Bidiagonal(U)` give? Or both `:L` ones? Your best option might be to turn both matrices into sparse ones, I guess.

**Comment by putianyi889** [comment]
> What should Bidiagonal(U)*Bidiagonal(U) give?
For current `Base` implementation, this should give sparse. However even in this case, `Bidiagonal` should still have proprietary implementation.

I would recommend `BandedMatrices.jl`. Either banded implementations in `Base` are integrated into that package or that package is integrated into `Base`.

**Comment by dkarrasch** [comment]
I'm not sure if there are any plans to integrate `BandedMatrices.jl` into `LinearAlgebra`. @dlfivefifty 

How about switching to BandedMatrices.jl for that use case? I'm not sure if there is anything (realistically) actionable here.
