### ISSUE TITLE
Bundled html docs not searchable, lacking `search_index.js`

### ISSUE THREAD

**Issue by complyue** [JuliaLang/julia#44226]
Julia 1.7.2 bundles with html docs, but the `share/doc/julia/html/en/` root directory lacks `search_index.js` (also `siteinfo.js` `versions.js` etc. but those are less critical), effectively rendered it not searchable.

I managed to bringup a local http server for the static files, to make the browser happy in supporting offline doc reading, it works well otherwise than the searchability issue.

https://gist.github.com/complyue/32cf456a21d471fd7fcdfbcb42c7f23b

**Comment by complyue** [comment]
I'd gotten the official MacOS build from https://julialang-s3.julialang.org/bin/mac/x64/1.7/julia-1.7.2-mac64.dmg

```log
$ ls /Applications/Julia-1.7.app/Contents/Resources/julia/share/doc/julia/html/en 
NEWS.html	assets		base		devdocs		index.html	manual		search.html	stdlib
```
 
So it's MacOS only I guess.

**Comment by ViralBShah** [comment]
My 1.7.2 install that is from the official binaries has `search_index.js`:

```
ls ~/Desktop/Julia/Julia-1.7.app/Contents/Resources/julia/share/doc/julia/html/en/
NEWS.html       base            index.html      search.html     stdlib
assets          devdocs         manual          search_index.js

```
