### ISSUE TITLE
pinv bug: matrix misdiagnosed as diagonal

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#44234]
The code
```
A = [1.0 0.0;0.0 1.0;0.0 0.0]
A1 = pinv(A):
```
produces
```
[1.0 0.0 1.0;0.0 0.0 0.0]
```
An incorrect answer, which is due to the identification of `A` as diagonal on line
https://github.com/JuliaLang/julia/blob/bf534986350a991e4a1b29126de0342ffd76205e/stdlib/LinearAlgebra/src/dense.jl#L1433

I think the solution could be to check that the matrix is square and `isdiag` returns true.

Or, perhaps `isdiag` does not work correctly, and the solution is to fix that function to identify matrix as diagonal only if it is square? 

The `svd` code below the if block would have worked correctly.
https://discourse.julialang.org/t/bug-in-linearalgebra-pinv/76663/2

**Comment by martinholters** [comment]
I think the problem is the indexing operation in
https://github.com/JuliaLang/julia/blob/bf534986350a991e4a1b29126de0342ffd76205e/stdlib/LinearAlgebra/src/dense.jl#L1439
Using `PermutedDimsArray(B, (2,1))[ind]` on the LHS might do the trick.

**Comment by PetrKryslUCSD** [comment]
That might work.

**Comment by hyrodium** [comment]
Note that this bug doesn't exist on Julia v1.6.6.

**v1.6.6**
```julia
julia> A = [1.0 0.0;0.0 1.0;0.0 0.0]
3×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
 0.0  0.0

julia> A1 = pinv(A)
2×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
```

**v1.7.2**
```julia
julia> A = [1.0 0.0;0.0 1.0;0.0 0.0]
3×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
 0.0  0.0

julia> A1 = pinv(A)
2×3 Matrix{Float64}:
 1.0  0.0  1.0
 0.0  0.0  0.0
```

Maybe #39756 is related?
