### ISSUE TITLE
Performance of nested functions

### ISSUE THREAD

**Issue by magistere** [JuliaLang/julia#4428]
I've found that nested functions usage cause significant performance degrade. In the following sample script I got increasing run time from 0.4s to 2.6s on my machine.

```julia
g(n) = 1.0/n

function f(n)
  sum = 0.0
  g1(n) = 1.0/n
  for i = 1:n
    sum += g(i) # change to g1 to use nested function
  end
  sum
end

tic()
println(f(10_000_000))
toc()
```

**Comment by jakebolewski** [comment]
closing as a dup of  #1864
