### ISSUE TITLE
5-arg `mul!` with complex view storage allocates a lot

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#44290]
The following code makes quite a large amount of allocations. If the view is removed, all but one allocation is removed
```julia
julia> R = zeros(ComplexF64, 2,2); C = zeros(2,2); Bc = zeros(ComplexF64, 2,2);

julia> @time mul!(@view(R[:,:]), C, Bc, -1, 1); # warmup

julia> @time mul!(@view(R[:,:]), C, Bc, -1, 1);
  0.000011 seconds (7 allocations: 288 bytes)

julia> @time mul!(R, C, Bc, -1, 1); # Without view
  0.000009 seconds (1 allocation: 32 bytes)
```

Additionally, there appears to be a large delay each time the code `@time mul!(@view(R[:,:]), C, Bc, -1, 1);` is called, even after compilation, much larger than the reported time.

Tested on julia v1.8.0-DEV.1505

**Comment by pablosanjose** [comment]
Reproduced also on v1.7.1

**Comment by dkarrasch** [comment]
Which methods are called, respectively?

**Comment by baggepinnen** [comment]
```julia
julia> @which mul!(@view(R[:,:]), C, Bc, -1, 1)
mul!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, B::StridedVecOrMat{T}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /tmp/julia-e422590151/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:159

julia> @which mul!(R, C, Bc, -1, 1)
mul!(C::StridedMatrix{T}, A::StridedVecOrMat{T}, B::StridedVecOrMat{T}, alpha::Number, beta::Number) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} in LinearAlgebra at /tmp/julia-e422590151/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:159
```

**Comment by dkarrasch** [comment]
Constructing the view adds 1 allocation of 48 bytes. With real eltype of C this ends up in `generic_matmatmul!` and due to the specific size eventually in `matmul2x2!`. But it's unclear (to me) what causes the extra allocations, and where it's relevant whether the output is a view or the full matrix.

**Comment by baggepinnen** [comment]
When `C::Matrix{Float64}`, the view appears relevant:
```julia
julia> @time mul!(R, C, Bc, -1, 1)
  0.000006 seconds (1 allocation: 32 bytes)

julia> @time mul!(@view(R[:,:]), C, Bc, -1, 1)
  0.000010 seconds (7 allocations: 288 bytes)
```

**Comment by jishnub** [comment]
```julia
julia> @time mul!(@view(R[:,:]), C, Bc, -1, 1);
  0.000019 seconds (7 allocations: 288 bytes)

julia> @btime mul!(@view($R[:,:]), $C, $Bc, -1, 1);
  77.736 ns (0 allocations: 0 bytes)
```

Maybe a timing artifact?

**Comment by baggepinnen** [comment]
Interesting, I can also eliminate the allocations by putting the code inside a function, but the original problem that lead to me finding this issue saw a tremendous change from changing the eltype of `C` from FLoat64 to ComplexF64. But yeah, 
```julia
function foo()
       R = zeros(ComplexF64, 2,2); C = zeros(ComplexF64, 2,2); Bc = zeros(ComplexF64, 2,2);
       @allocated mul!(@view(R[:,:]), C, Bc, -1, 1);
end
```
clearly outputs 0 so I guess this is a non-issue. Thanks everyone for looking into it!

**Comment by dkarrasch** [comment]
> saw a tremendous change from changing the eltype of `C` from FLoat64 to ComplexF64

Of course. As you found yourself, in the latter a `mul!` method gets called that leads to BLAS, whereas the Float64 version leads to `generic_matmatmul!`. We don't promote eltypes in `mul!` to make it fit BLAS (to avoid the allocation of potentially huge matrices), but we do so in `*`.

**Comment by baggepinnen** [comment]
I did however see an enormous difference in allocations as well, so for some reason the real valued C matrix caused allocations that made me look into this. My test cases were all tiny, so I don't think my speedup were due to BLAS, rather the reduced allocations are likely the key change.

**Comment by dkarrasch** [comment]
Hm, due to promotion of matrix elements? Hard to say.

**Comment by baggepinnen** [comment]
I revisited the code and performed my original benchmark again, removing the call to `complex` on the line
https://github.com/JuliaControl/ControlSystems.jl/blob/4012c106ccfe87f016bcf61086c5538f02e6debb/src/freqresp.jl#L87
changes the benchmark from
```
11.361 ms (16 allocations: 35.33 KiB)      # With complex
97.590 ms (100015 allocations: 732.46 MiB) # Without complex
```
The benchmark code sets up a tiny statespace system where no matrix is larger than 3x3:
```julia
using ControlSystems # requires the very latest release
w = exp10.(LinRange(-2, 2, 50000))
G = ssrand(2,2,3)
R = freqresp(G, w).parent;
@btime ControlSystems.freqresp!($R, $G, $w);
```
