### ISSUE TITLE
Expand VersionNumber to allow for a fourth field

### ISSUE THREAD

**Issue by jakewilliami** [JuliaLang/julia#44302]
Many version numbers are of the form `major.minor.build.revision`.  I understand this does not adhere to the semantic versioning standards, but I wonder if `VersionNumber` should support this as well.

An argument for this is that this versioning is actually quite common (e.g., Chrome, and a lot of Microsoft products, use this kind of versioning).  However, an argument against this would be that if `VersionNumber` exists mostly for `Pkg`, then this is an unnecessary feature.

**Comment by fredrikekre** [comment]
See https://github.com/JuliaInterop/VersionParsing.jl
