### ISSUE TITLE
Feature Request: nameof(::Enum)

### ISSUE THREAD

**Issue by Ellipse0934** [JuliaLang/julia#44323]
When I define an Enum. Say `@enum Fruit apple=15 banana=27`. Given the value I would like to get the name of the the enumerated type. One way to get this is.
```julia
julia> Base.Enums.namemap(Fruit)
Dict{Int32, Symbol} with 2 entries:
  5  => :apple
  19 => :banana
```
It would be convenient to have a method dedicated to this. I think `nameof` is suitable here. The resultant behaviour being
`nameof(Fruit(5)) == :apple`

I'm happy to implement it if this makes sense.

**Comment by simeonschaub** [comment]
You can already use `Symbol(Fruit(5))` for this. Could perhaps be documented better.
