### ISSUE TITLE
`let` block not allowed on lhs of `.+=`

### ISSUE THREAD

**Issue by goulart-paul** [JuliaLang/julia#44356]
Best explained by an example : 
```julia 
struct Foo{T}
    a::Vector{T}
end

n = 10
x = Foo(ones(n))
y = ones(n)

@views x.a[2:end] .+= y[2:end]  # <--- error 
```

The reported error is `ERROR: syntax: invalid let syntax`.  

Confirmed on v1.7 and v1.5.   Further discussion and a possible solution may be found on discourse [here](https://discourse.julialang.org/t/views-throws-an-error-in-combination-with-a-struct/77090).

**Comment by JeffBezanson** [comment]
No, I don't think we can or should support `let` blocks (or other blocks) as assignment left-hand sides. `@views` should be able to support this though.

**Comment by simeonschaub** [comment]
It's not an actual assignment though, It's an inplace broadcast. It actually works if you use `<let> .= <let> .+ foo` instead.

**Comment by JeffBezanson** [comment]
Ah I guess it's a problem with broadcast lowering then?

**Comment by vtjnash** [comment]
```julia
julia> @macroexpand @views x.a[2:end] .+= y[2:end]  # <--- error
:(let var"##S#292" = x.a
          (Base.maybeview)(var"##S#292", 2:(lastindex)(var"##S#292"))
      end .+= (Base.maybeview)(y, 2:(lastindex)(y)))
```
