### ISSUE TITLE
`widenconst` of a Const(::Type) can be quite slow

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#44402]
Currently a lot of our code is written with the assumption that `widenconst(::Const)` is extremely fast. However, this is not true if the value inside the Const happens to be a Type. There, it can be very slow:

```
c1 = Core.Const(Base.RefValue)
c2 = Core.Const(2)
```

```
julia> @btime Core.Compiler.widenconst(c1)
  4.540 μs (0 allocations: 0 bytes)
Type{Base.RefValue}

julia> @btime Core.Compiler.widenconst(c2)
  40.162 ns (0 allocations: 0 bytes)
Int64
```

**Comment by vtjnash** [comment]
Refs https://github.com/JuliaLang/julia/pull/42596?

**Comment by Keno** [comment]
Perhaps, but I think even a single type cache lookup can be quite problematic for these. I'm playing with just remembering the pointer in the types itself.

**Comment by Keno** [comment]
In fact, as it stands, this issue might make #42596 problematic, because it might force computation of the `widenconst` value even when it isn't otherwise required.

**Comment by vtjnash** [comment]
I think that change might see widenconst return the kind instead, with the type-level information tracked elsewhere with consistency instead
