### ISSUE TITLE
@time slow down

### ISSUE THREAD

**Issue by bradcarman** [JuliaLang/julia#44430]
I have a case where I am getting a major slowdown when using `@time`.  Here is my MWE

case1.jl
```julia
params = Parameters();
nothing
```

case2.jl
```julia
@time params = Parameters();
nothing
```

case3.jl
```julia
@time (params = Parameters(); nothing)
```

With the result
```
julia> @time include("case1.jl")
  0.000782 seconds (813 allocations: 63.094 KiB)

julia> @time include("case2.jl")
  0.000062 seconds (687 allocations: 55.688 KiB)
  6.109373 seconds (13.63 k allocations: 743.914 KiB, 99.96% compilation time)

julia> @time include("case3.jl")
  0.000036 seconds (687 allocations: 55.688 KiB)
  0.010787 seconds (12.34 k allocations: 655.883 KiB, 82.14% compilation time)
```

Notice that `case2.jl` takes over 6 seconds!!!!

My `Parameters()` immutable struct is made up of 327 fields that are the same simple struct...

```
struct ParameterValue
	header::Symbol
	key::Symbol
	description::String
	value::Vector{Float64}
	unit::Unit
end
```

Why does case2.jl take over 6 seconds?  It seems related to the final returned value in the `@time` statement, as `case3.jl` proves.

Current Julia version:
```
julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Xeon(R) W-11855M CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 12 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```

**Comment by bradcarman** [comment]
I am running this example after code was compiled (i.e. I’m showing the second run).  Also why does case2.jl report anything different from case1.jl?  This doesn’t make sense

**Comment by giordano** [comment]
> Here is my MWE

This isn't very W(orking): the code you shared doesn't work at all.

**Comment by bradcarman** [comment]
You're right, my apologies, let me give an actual MWE

```julia
code = """
    @Base.kwdef struct Parameters
        $(join(["f$i::Symbol = :f$i" for i =1:1000], '\n'))
    end
    """

include_string(Main, code)

#compile
include_string(Main, "@time \"--compile--\" params = Parameters(); \n nothing");

println("--------------------")

@time "case 1" include_string(Main, "params = Parameters(); \n nothing");
@time "case 2" include_string(Main, "@time \"--inside case 2--\" params = Parameters(); \n nothing");
@time "case 3" include_string(Main, "@time \"--inside case 3--\" (params = Parameters(); nothing)");
```

Which gives the output:

```
--compile--: 0.000038 seconds (1 allocation: 7.875 KiB)
--------------------

case 1: 0.000266 seconds (62 allocations: 10.812 KiB)

--inside case 2--: 0.000028 seconds (1 allocation: 7.875 KiB)
case 2: 2.247535 seconds (25.11 k allocations: 1006.664 KiB, 99.92% compilation time)

--inside case 3--: 0.000007 seconds (1 allocation: 7.875 KiB)
case 3: 0.169222 seconds (24.63 k allocations: 966.312 KiB, 99.06% compilation time)
```

My question is, why does case 2 take so long???  It's several orders of magnitude slower then it should be.  And why is case 3 faster?

The reason why I discovered this is because if I run the below code in the REPL, the reported time (0.000042s) does not match the real execution time (approximately 2s).  Therefore, after `@time` completes, there are several seconds of something happening.  Either `@time` is missing this, or something else is happening with Julia that I'm not aware of.  

```julia
julia> @time params = Parameters();
  0.000042 seconds (1 allocation: 7.875 KiB)
```

**Comment by oscardssmith** [comment]
for measuring compilation time, you generally want to use `@time @eval` instead of just `@time`.

**Comment by KristofferC** [comment]
From the (1.8) docs on `@time`:

>   In some cases the system will look inside the `@time` expression and compile some of the called code before execution of the
  top-level expression begins. When that happens, some compilation time will not be counted. To include this time you can run
  `@time @eval` ....

**Comment by bradcarman** [comment]
OK, I think that makes sense.  Julia is compiling the full @time generated code, then evaluating it.  The correct timing is captured, but the user may need to wait for the generated code to compile, which in this example can be quite significant.  And part of the compilation appears to be related to handling the return of the expression, which is why case 3 with the return of `nothing` is faster.  

So in the end, there aren't any bugs here, but I think it would be good to provide additional user feedback in the REPL if significant compile time occurs, like a spinner or message.  Otherwise it's quite confusing to the user of `@time` to get a reported execution time of microseconds when clearly several seconds have passed.  Is this worth a feature request?
