### ISSUE TITLE
Regression in floating point power

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#44452]
1.7:

```jl
julia> (-1.0)^(1.0e63)
1.0
```

1.8:

```jl
julia> (-1.0)^(1.0e63)
ERROR: DomainError with -1.0:
Exponentiation yielding a complex result requires a complex argument.
```

Causes SpecialFunctions to fail tests.

**Comment by oscardssmith** [comment]
Good catch. `pow` has a lot of edge cases.

**Comment by oscardssmith** [comment]
fixed by https://github.com/JuliaLang/julia/pull/44456

**Comment by giordano** [comment]
It's Friday and perhaps I'm tired, but am I missing something or throwing an error is more sensible than returning wrong numbers?

**Comment by giordano** [comment]
With #44456
```julia
julia> (-1.0)^(1.0e63)
-1.0
```
which would still make SpecialFunctions tests fail, and reinforce my conviction that this is just wrong.

**Comment by oscardssmith** [comment]
this (at least theoretically) returns right numbers

**Comment by giordano** [comment]
Assuming that all numbers larger than `2*inv(eps())` are integers and have the same parity as `typemax(Int64)` doesn't look much right to me: https://github.com/JuliaLang/julia/pull/44456#discussion_r819977613.

**Comment by oscardssmith** [comment]
yeah. I got it backwards. it needed to be typemax-1
