### ISSUE TITLE
Build failure due to missing patch llvm-libunwind-prologue-epilogue.patch

### ISSUE THREAD

**Issue by fxcoudert** [JuliaLang/julia#44499]
Trying to build julia master branch on macOS:

```
$ make VERBOSE=1 prefix=/tmp/toto PYTHON=python3 MACOSX_VERSION_MIN=12 USE_BINARYBUILDER=0 USE_SYSTEM_LLVM=1 PYTHON=python3 MACOSX_VERSION_MIN=12
[…lots of output…]
cd /private/tmp/julia/deps/srccache/ && /usr/bin/tar xf /private/tmp/julia/deps/srccache/llvmunwind-12.0.1.tar.xz
mv /private/tmp/julia/deps/srccache/libunwind-12.0.1.src /private/tmp/julia/deps/srccache/llvmunwind-12.0.1
echo 1 > /private/tmp/julia/deps/srccache/llvmunwind-12.0.1/source-extracted
cd /private/tmp/julia/deps/srccache/llvmunwind-12.0.1 && patch -p2 -f < /private/tmp/julia/deps/patches/llvm-libunwind-prologue-epilogue.patch
/bin/sh: /private/tmp/julia/deps/patches/llvm-libunwind-prologue-epilogue.patch: No such file or directory
make[1]: *** [/private/tmp/julia/deps/srccache/llvmunwind-12.0.1/llvm-libunwind-prologue-epilogue.patch-applied] Error 1
make: *** [julia-deps] Error 2
```

This patch file is referenced here: https://github.com/JuliaLang/julia/blob/811e534ca7398b4856149938995539f77078939d/deps/unwind.mk#L91

It was introduced in https://github.com/JuliaLang/julia/pull/39127
but the patch file was removed in https://github.com/JuliaLang/julia/pull/42436

**Comment by fxcoudert** [comment]
Using `USE_BINARYBUILDER=0` leads to a different number of failures. This one is the first, but I find others (like, wrong arguments passed to lapack, etc). Should I report all those failures, or is `USE_BINARYBUILDER=0` considered not really supported? @giordano

**Comment by DilumAluthge** [comment]
> can we add at nightly build for `USE_BINARYBUILDER=0`? Using `ccache` it should still be reasonable.

Yep, we actually have that already, it's just disabled currently while we transition things. We should be able to re-enable it soon. @staticfloat

**Comment by fxcoudert** [comment]
I've tried to restore `llvm-libunwind-prologue-epilogue.patch` and `llvm-libunwind-force-dwarf.patch` by partially reverting https://github.com/JuliaLang/julia/pull/42436

The problem is that `llvm-libunwind-force-dwarf.patch` does not apply cleanly:

```
cd /private/tmp/julia/deps/srccache/llvmunwind-12.0.1 && patch -p2 -f < /private/tmp/julia/deps/patches/llvm-libunwind-force-dwarf.patch
patching file include/libunwind.h
Hunk #1 succeeded at 108 (offset 6 lines).
patching file src/UnwindCursor.hpp
Hunk #1 succeeded at 437 (offset 1 line).
Hunk #2 succeeded at 897 (offset 3 lines).
Hunk #3 succeeded at 967 (offset 25 lines).
Hunk #4 FAILED at 1202.
Hunk #5 succeeded at 1222 (offset 30 lines).
Hunk #6 succeeded at 1279 (offset 30 lines).
Hunk #7 succeeded at 1951 (offset 46 lines).
1 out of 7 hunks FAILED -- saving rejects to file src/UnwindCursor.hpp.rej
patching file src/libunwind.cpp
Hunk #1 succeeded at 71 (offset 2 lines).
Hunk #2 succeeded at 80 (offset 2 lines).
patching file src/libunwind_ext.h
```

**Comment by ViralBShah** [comment]
> @DilumAluthge can we add at nightly build for `USE_BINARYBUILDER=0`? Using `ccache` it should still be reasonable.

Would we run this on every commit, or just once a day or something? Wouldn't it be quite wasteful?

**Comment by DilumAluthge** [comment]
Just once every 24 gours

**Comment by fxcoudert** [comment]
This error still exist on julia-1.8.0-beta3. Could the patch be backported please?

**Comment by fxcoudert** [comment]
Actually I think this was never fixed :(

**Comment by fxcoudert** [comment]
@vchuravy could you please restore the needed patches to master and 1.8 branch?
