### ISSUE TITLE
Difference (regression?) in floating point pow on 1.8

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#44525]
Looking at some PkgEval logs a failure that occurs comes up from a changed result for `2^111.94`. This used to be computed as

```jl
julia> v = 2^111.94
4.9807840732777406e33
```

which is in agreement with e.g. Python. The current value is

```jl
julia> 2^111.94
4.980784073277717e33
```

which to my naive eye seems to be significantly worse:

```jl
julia> v = 2^111.94; bv = big"2"^111.94; (v - bv) / bv # 1.7
2.09394118307...e-17

julia> v = 2^111.94; bv = big"2"^111.94; (v - bv) / bv # 1.8
-4.72427549745...e-15
```

**Comment by KristofferC** [comment]
Here is another one from another PkgEval failure:

```
julia> 10.0^-3 # 1.7
0.001

julia> 10.0^-3 # 1.8
0.0010000000000000002
```

**Comment by oscardssmith** [comment]
confirmed. I had apparently not tested this thoroughly enough. Funnily enough, both the `log` and `exp` used are accurate enough, but I screwed up computing `(x+xlo)*hi` fix incoming.
