### ISSUE TITLE
`matmul` outcome changed between Julia 1.7 and 1.8-beta1

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaLang/julia#44536]
In `ArrayLayouts.jl`, there is a test comparing their implementation of `muladd` to base `muladd`:

```julia
julia> rng = StableRNG(1);

julia> X = randn(rng, ComplexF64, 8, 4);

julia> Y = randn(rng, 8, 2);
        
julia> @test all(mul(Y',X) .=== Y'X)
```
This test fails on Julia 1.8-beta1 and passes on earlier versions. I've narrowed it down to a change in outcome of `Y'X`:

## Julia 1.7.2

```julia
julia> (Y'X)[1]
-1.3154858319870038 - 0.8411677016058232im
```

## Julia 1.8-beta1

```julia
julia> (Y'X)[1]
-1.315485831987004 - 0.8411677016058232im
```

Is this change in outcome expected?

EDIT: This is probably related to https://github.com/JuliaLang/julia/pull/44529.

**Comment by KristofferC** [comment]
I think this is https://github.com/JuliaLang/julia/pull/43435. It is using BLAS now instead of a generic Julia method. Small differences are expected.

**Comment by rikhuijzer** [comment]
> I think this is #43435. It is using BLAS now instead of a generic Julia method. Small differences are expected.

Okay thank you, Kristoffer 🙂 I‘ll close this
