### ISSUE TITLE
Broadcasting over `UnitRange`

### ISSUE THREAD

**Issue by cscherrer** [JuliaLang/julia#44624]
In 1.8.0-beta1:
```julia
julia> 1:10 .^ 2
1:100
```

This seems to be treating `1:10` as a generic data structure, rather than an object with array semantics. Even stranger, a user might come to expect this unusual REPL behavior to behave consistently within a function. But it doesn't: 
```julia
julia> square_each(x::AbstractArray) = x .^ 2
square_each (generic function with 1 method)

julia> square_each(1:10)
10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100
```

So this seems to be a bug specific to the REPL.

**Comment by vtjnash** [comment]
operator precedence strikes again
```
julia> (1:10) .^ 2
10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100
```
