### ISSUE TITLE
Cannot add new packages.

### ISSUE THREAD

**Issue by Photonico** [JuliaLang/julia#44621]
### Discussed in https://github.com/JuliaLang/julia/discussions/44620

<div type='discussions-op-text'>

<sup>Originally posted by **Photonico** March 15, 2022</sup>
Hi,

I cannot install new packages with error: `curl_multi_socket_action: 8`
It's bothering me. How can I fix this problem?

Julia Version: 1.6.3
OS: openSUSE TW

Sincerely,
Lu</div>

**Comment by rfourquet** [comment]
Github issues and conversations are not used for Julia questions, please ask them on slack or on https://discourse.julialang.org/.
