### ISSUE TITLE
Extended Callstack in perf disassembly

### ISSUE THREAD

**Issue by Uroc327** [JuliaLang/julia#44627]
When performing `@code_native` on a function, the code is not only annotated with source comments, but with complete call stacks.

It seems that the disassembly shown by `perf report` (created according to [this](https://docs.julialang.org/en/v1/manual/profile/#External-Profiling) on the other hand only knows the innermost function. I'd love to have the source locations including the whole (static) julia callstack added to the disassembly shown by `perf report` or `perf annotate`.

Example:
```
; ││││┌ @ simdloop.jl:77 within `macro expansion' @ broadcast.jl:984
; │││││┌ @ broadcast.jl:575 within `getindex'
; ││││││┌ @ broadcast.jl:620 within `_broadcast_getindex'
; │││││││┌ @ broadcast.jl:645 within `_getindex'
; ││││││││┌ @ broadcast.jl:614 within `_broadcast_getindex'
; │││││││││┌ @ array.jl:801 within `getindex'
            %5465 = getelementptr inbounds double, double* %5427, i64 %value_phi7569384
```
instead of just
```
;  @ array.jl:801 within `getindex'
            %5465 = getelementptr inbounds double, double* %5427, i64 %value_phi7569384
```

**Comment by vchuravy** [comment]
I don't think there is anything we can do here. We provide the DWARF callstack to `perf` and it is responsible for the rendering. Julia is not involved in the processing and visualization of the `perf.jit.data`

**Comment by Uroc327** [comment]
Does `@code_native` work (solely) on the same dwarf data? On further inspection, the code locations in perf report (presumably from objdump) and the code locations in `@code_native` don't really match.

**Comment by vchuravy** [comment]
> Does `@code_native` work (solely) on the same dwarf data?

It works on the debug-information we emit to LLVM. LLVM then emits DWARF from that and perf parses it.
