### ISSUE TITLE
literals for invalid characters?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#44646]
This seems weird:
```jl
julia> "\x94"[1]
'\x94': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> '\x94'
ERROR: syntax: invalid empty character literal
```
Shouldn't you be able to enter `'\x...'` for such characters, so that the literal format matches the `repr`?

cc @StefanKarpinski, who designed `Char` in #24999.

**Comment by simeonschaub** [comment]
Duplicate of #25072?

**Comment by stevengj** [comment]
Thanks!

**Comment by stevengj** [comment]
Actually, it's not quite the same.  That issue is about overlong `Char`, which a bit different from `''\x94'`.

**Comment by simeonschaub** [comment]
Yeah, maybe we can keep both open, but it seems to be the same underlying issue

**Comment by StefanKarpinski** [comment]
I did mention later in that issue supporting straight up invalid character literals. Jeff had some tips on where to start hacking it into the parser but I never got around to it. This would be nice to have.

**Comment by stevengj** [comment]
Fair enough, we can close this one.
