### ISSUE TITLE
Add Pluto.jl to the Browser-Based Workflow

### ISSUE THREAD

**Issue by oviedorodolfo** [JuliaLang/julia#44640]
I suggest adding Pluto.jl to the browser-based workflow: https://docs.julialang.org/en/v1/manual/workflow-tips/#Browser-based-workflow

**Comment by simeonschaub** [comment]
Want to make a quick PR?

**Comment by SamarthMayya** [comment]
@simeonschaub The issue here is to add Pluto.jl documentation to the Browser-based workflow right?

**Comment by SamarthMayya** [comment]
If there is no one else working on this, may I work on the same?
