### ISSUE TITLE
REPL unicode leftover

### ISSUE THREAD

**Issue by paulmelis** [JuliaLang/julia#44647]
Really minor thing I found when I mistakenly used `\u\ddot<tab>` in the REPL to get a `ü` character. This results in 

![image](https://user-images.githubusercontent.com/1408287/158673608-714068c0-418a-41b6-b55f-c0b5adf33618.png)

If I then move the cursor left two characters and press delete twice the REPL prompt becomes:

![image](https://user-images.githubusercontent.com/1408287/158673978-f3a5ce71-bcb9-4f75-8df0-83f271858068.png)

Using backspace then doesn't manage to get rid of the `"` (although delete does).

```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```

**Comment by vtjnash** [comment]
As that is the unicode behavior of the ddot character, I am not certain there is anything to do here. Should we attempt to kill both characters?

**Comment by paulmelis** [comment]
Ah, I see what you mean, I thought my initial `\` was causing this. I guess then the only thing that's a bit weird is that the space after `julia>` goes missing, but that's then also understandable. Maybe this then isn't worthy of some kind of attention.
