### ISSUE TITLE
Move DelimitedFiles to a separate external package

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#44663]
Can we move DelimitedFiles to an external package and also perhaps remove it from the system image?

Now that we are considering moving sparse out of the system image, I thought I would ask that about DelimitedFiles as well.  https://github.com/JuliaLang/julia/pull/44247#issuecomment-1071226278

Is Dates.jl worth considering moving out? Any others?

**Comment by DilumAluthge** [comment]
The sharpest constraint we have is that we cannot remove any stdlibs that are direct or indirect dependencies of Pkg. Everything else seems like fair game.

The full list of direct and indirect dependencies of Pkg is:

1. ArgTools
2. Artifacts
3. Base64
4. Dates
5. Downloads
6. InteractiveUtils
7. LibCURL
8. LibCURL_jll
9. LibGit2
10. LibSSH2_jll
11. Libdl
12. Logging
13. Markdown
14. MbedTLS_jll
15. MozillaCACerts_jll
16. NetworkOptions
17. Pkg
18. Printf
19. REPL
20. Random
21. SHA
22. Serialization
23. Sockets
24. TOML
25. Tar
26. UUIDs
27. Unicode
28. Zlib_jll
29. nghttp2_jll
30. p7zip_jll

**Comment by DilumAluthge** [comment]
Dates.jl is currently a direct dependency of Pkg.jl, so we can't move it out.

However, if we can remove Pkg's dependency on Dates, then Dates becomes fair game.

**Comment by ViralBShah** [comment]
Yikes, will we really move LinearAlgebra or Random out. Technically, they will just work like regular packages, but the annoyance level may be quite high.

**Comment by DilumAluthge** [comment]
> Yikes, will we really move `LinearAlgebra` or `Random` out? Technically, they will just work like regular packages, but the annoyance level (due to type piracy issues) may be quite high.

Fair enough 😂.

In addition to the direct and indirect dependencies of Pkg, I suppose that we should make a list (a very short list) of stdlibs that would be very annoying to move out (and would cause a lot of user backlash if we did move them out).

**Comment by giordano** [comment]
> 17. Pkg

Pkg indirectly depends on itself?

**Comment by DilumAluthge** [comment]
> > 33\. Pkg
> 
> Pkg indirectly depends on itself?

Serves me right for auto-generating the list 😂

**Comment by adkabo** [comment]
For Pkg.jl, I checked a few usages
- `Unicode` afaict isn't used
- `Serialization` is barely used and could easily be replaced with TOML
- `Dates` is barely used and could easily be replaced with Libc

Perhaps some of the others could be removed if Pkg.jl were split into pieces, where the dependencies needed for installing other packages can be retained.

**Comment by LilithHafner** [comment]
> I suppose that we should make a list (a very short list) of stdlibs that (1) would be very annoying to move out and (2) would cause a lot of user backlash if we did move them out.

How frequently packages are used should be a factor in (2) because of the small but nonzero cost of `pkg> add` (e.g. `LinearAlgebra`, `Test`)

**Comment by ViralBShah** [comment]
Note that should be a non-issue if using Project.toml or Manifest.toml, and in any case, there's the autodetection of uninstalled packages and Julia offering to install it for you.

**Comment by adkabo** [comment]
To quantify the installation cost of a small package:

```jl
% JULIA_LOAD_PATH=@:@stdlib julia --project=. --startup-file=no --quiet
julia> import Pkg

julia> @time Pkg.add("IterTools")
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/tmp/tmp.gmAhldmGp9/Project.toml`
  [c8e1da08] + IterTools v1.4.0
    Updating `/tmp/tmp.gmAhldmGp9/Manifest.toml`
  [c8e1da08] + IterTools v1.4.0
  3.437964 seconds (2.66 M allocations: 163.276 MiB, 1.66% gc time, 33.38% compilation time)
```

This will depend on internet speed etc. It could be worth profiling to find out where the time is going.

**Comment by LilithHafner** [comment]
In my currently running session
```jl
(@v1.9) pkg> activate --temp
  Activating new project at `/var/folders/hc/fn82kz1j5vl8w7lwd4l079y80000gn/T/jl_ZsugUQ`

julia> import Pkg

julia> @time Pkg.add("IterTools")
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/private/var/folders/hc/fn82kz1j5vl8w7lwd4l079y80000gn/T/jl_ZsugUQ/Project.toml`
  [c8e1da08] + IterTools v1.4.0
    Updating `/private/var/folders/hc/fn82kz1j5vl8w7lwd4l079y80000gn/T/jl_ZsugUQ/Manifest.toml`
  [c8e1da08] + IterTools v1.4.0
Precompiling project...
  1 dependency successfully precompiled in 2 seconds
 16.597010 seconds (6.17 M allocations: 382.854 MiB, 0.82% gc time, 67.02% compilation time)
```
My internet speed is 218.9 Mbps download 23.2 Mbps upload 18 ms latency to google.com.

**Comment by JeffBezanson** [comment]
I say yes, let's move DelimitedFiles out of the stdlib and out of the system image (unless of course there is some kind of unforeseen breakage). The rest need to be taken on a case-by-case basis.

**Comment by ViralBShah** [comment]
Recipe for moving thing out while retaining history: https://github.com/JuliaAI/MLJOpenML.jl/issues/1

**Comment by ViralBShah** [comment]
https://github.com/JuliaLang/julia/pull/45121 moves it to an external package and out of the sysimage. However, it is still an stdlib at the moment (and that will be addressed by #45540).

**Comment by A-childs-encyclopedia** [comment]
Why is it being removed?

**Comment by StefanKarpinski** [comment]
There's no reason for it to be built into every Julia binary. It makes the binary larger, slower to load, causes there to be more precompiled code to be potentially invalidated when other packages are loaded. It also makes it harder than necessary to develop and improve the DelimitedFiles package.
