### ISSUE TITLE
performance of cat of scalars of mixed types

### ISSUE THREAD

**Issue by rwgardner** [JuliaLang/julia#4467]
The performance of

```
ar = [a, b, c, d, e]
```

is much worse than the performance of

```
ar = Array(Float64, 5)
ar[1]=a
ar[2]=b
ar[3]=c
ar[4]=d
ar[5]=e
```

where a-e are Float64's because the former syntax uses the cat operation (for a good reason, as explained by @JeffBezanson - a-e could be many things including arrays etc., which makes the "bracket" syntax require an extremely dynamic operation (i.e., cat) in the general case).

This is a request to analyze constructs in the "bracket" notation (i.e., the first example above) and optimize the creation of the array in cases where the types of the elements can be determined statically.  For example, translate the first block of code to the second internally, or do something more optimal.

(Changing the [ ] code to manually declare and assign arrays as above in our code increases speed by about 25% currently.  However, the syntax is undesirable in our context from a readability standpoint.)

**Comment by KristofferC** [comment]
These now both take the same time (30 ns) using the function below

```jl
function f()
	a, b, c, d, e = 1.0, 2.0, 3.0, 4.0, 5.0
	println(@benchmark ar = [$a, $b, $c, $d, $e])
	println(@benchmark begin ar = Array{Float64}(5)
	ar[1]=$a
	ar[2]=$b
	ar[3]=$c
	ar[4]=$d
	ar[5]=$e
	end)
end
```
