### ISSUE TITLE
Official 1.8 binaries fail to open in macos

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#44690]
The official 1.8 beta1 binaries downloaded from julialang.org/downloads fail to open in macos 12.3. They worked fine in 12.2. Both the Apple Silicon (on an M1 Macbook Pro) and the Intel (on an Intel iMac) binaries fail with the same error if Terminal was already running: `The application “Terminal” can’t be opened. -1703`. If Terminal was not running, it will launch, but will not initiate a Julia session.

Launching julia from the command line instead of the .app works fine. 

This problem does not occur with v1.7.

(Thanks Sven-Erik Ekström for reproducing on Slack)

**Comment by pablosanjose** [comment]
Possibly related: https://github.com/JuliaLang/julia/pull/43111

**Comment by gbaraldi** [comment]
This is a macos bug on applescript, https://forum.keyboardmaestro.com/t/open-with-finder-applescript-bug-in-macos-12-3/26971?page=2, has other people with the same issue, we could fix it by changing our code or wait for apple to fix theirs.

**Comment by ViralBShah** [comment]
Maybe easiest to change our code - since it will keep popping up.

**Comment by gbaraldi** [comment]
If there is someone more familiar with applescript this thread seems to offer a solution https://forum.latenightsw.com/t/macos-12-3-introduces-serious-fundamental-applescript-bug/3666. I'm not sure how I would adapt it. We could also just revert #43111 for now.

**Comment by ViralBShah** [comment]
Pinging @Evian-Zhang in case they know what to do here. It should be ok to revert as well.

**Comment by Evian-Zhang** [comment]
> Pinging @Evian-Zhang in case they know what to do here. It should be ok to revert as well.

I think reverting is a better solution, since the former code did not depend on open command, which may be more robust.

**Comment by pablosanjose** [comment]
This seems to be fixed for me with the official 1.8 beta3. I'll close. If someone still has this issue we can reopen.

**Comment by mkitti** [comment]
I just experienced this with 1.8.0-rc1.

```julia
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

The work around is to invoke `/Applications/Julia-1.8.app/Contents/Resources/julia/bin/Julia` directly from a terminal.

**Comment by f-ij** [comment]
Got a new Macbook with M1 Max and encountered this issue on RC3, didn't have this on my old MacBook Pro M1.

**Comment by gbaraldi** [comment]
@f-ij Check if you have the latest macos? it might be that

**Comment by f-ij** [comment]
@gbaraldi Thanks, that indeed turned out the be the problem!

**Comment by pablosanjose** [comment]
The released version of 1.8.0 is again failing to open in latest macos (12.5.1) on an M1 Macbook Pro, due this time to an issue with code signing.

Can anybody reproduce?

<img width="256" alt="Screenshot 2022-09-08 at 12 49 19" src="https://user-images.githubusercontent.com/4310809/189103903-897a43f5-5b5b-4571-8095-4d7bd079febd.png">

**Comment by pablosanjose** [comment]
The newly released v1.8.1 macos ARM binary seems to have fixed this. Closing.

**Comment by helpjulia** [comment]
I have same problem! M1 macbook pro macos monterey 12.3 failed to install julia. I am really new to mac, just bought it 3 days ago and I have no clue at all. Please help!!!! thank you

**Comment by helpjulia** [comment]
> The newly released v1.8.1 macos ARM binary seems to have fixed this. Closing.

could you explain to me how to get v1.8.1 macos ARM binary and how to install it? thanks

**Comment by mkitti** [comment]
Download the file next to "macOS ARM (M-series Processor)" on the following page.

https://julialang.org/downloads/

Here is a direct link:
https://julialang-s3.julialang.org/bin/mac/aarch64/1.8/julia-1.8.1-macaarch64.dmg

**Comment by cbaretzky** [comment]
Still a problem with 1.8.2 from 2022-09-29 on m1. Needs to be allowed manually in MacOS.

**Comment by pablosanjose** [comment]
Cannot reproduce in macos 12.6.1 in m1 max macbook pro. The official Julia 1.8.2 just asks "This is an app downloaded from the Internet. Do you want to open it?", but it allows to click "yes".

**Comment by mkitti** [comment]
> Cannot reproduce in macos 12.6.1 in an m1-max macbook pro. The official Julia 1.8.2 just asks "This is an app downloaded from the Internet. Do you want to open it?", but it allows to click "yes".

This was also my recent experience.

**Comment by ymer** [comment]
I have the problem too. When I click yes to opening it, it opens a bunch of text with TextEdit.app. Mac M1 Ventura 13.1

**Comment by pablosanjose** [comment]
Again, I cannot reproduce. Ventura 13.2.1, M1 Max. Might you perhaps have an issue with the configuration of your Terminal.app?

**Comment by pablosanjose** [comment]
Since the original error "-1703" was resolved I will close this now. Feel free to open another issue with more details about your case.
