### ISSUE TITLE
Generalized comprehension syntax

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#4470]
What about the following?
```julia
(f(x) for x in a)   
# this may be some indexable view of a special type that can be 
# passed as arguments, such that we can do

sum(f(x) for x in a) 
```
In this way, statistics can be easily implemented in an efficient way, for example
```julia
var(a) = sum(abs2(x - mean(x)) for x in a) / (length(a) - 1)
```
This is a one-liner, but it does not create any temporary arrays. 

If the Cartesian iteration discussed in #1917 can be implemented, this would become even more powerful:
```julia
# weighted mean
wmean(a, ws) = dot(a, ws) / sum(ws)

# weighted variance
wvar(a, ws) = sum(abs2(x - mean(x)) * w for (x, w) in (a, ws)...)
```

**Comment by diegozea** [comment]
About #1457 and #550... Could the output be preallocated and resized to its final length?
Maybe... 
```
T[ f(a) for a in A  if g(a) ]
```
Can be something like...
```
N = length(A)
out = Array(T,N)
j = 0
for i in 1:N
  if g( A[i] )
    j += 1
    out[j] = f( A[i] )
  end
end
resize!(out, j)
```
