### ISSUE TITLE
Regression in `===` (caused by #43658?)

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#44712]
Running the following:

```jl
using TensorKit, TensorKitManifolds, StableRNGs
V = ℂ^4
T = Float64
rng = StableRNG(0)
W, = leftorth(TensorMap((x...)-> randn(rng, x...), T, V*V*V, V*V); alg = Polar())
X = TensorMap((x...)-> randn(rng, x...), T, space(W))
Y = TensorMap((x...)-> randn(rng, x...), T, space(W))
Δ = Unitary.project(X, W)
Θ = Unitary.project(Y, W)

Δ === Θ
```

we get `false`on 1.7, while on 1.8 this returns `true` 

Here is a proof they are not `===`:

```jl
julia> Θ.A.data |> sum
1.1102230246251565e-15

julia> Δ.A.data |> sum
-4.6074255521944e-15
```

Reverting https://github.com/JuliaLang/julia/pull/43658 makes it go away so I guess the bug is from there.

cc @NHDaly

**Comment by NHDaly** [comment]
> https://github.com/JuliaLang/julia/blob/62e0729dbc5f9d5d93d14dcd49457f02a0c6d3a7/src/builtins.c#L110
> 
> 
> 😱

😮 
Interestingly, I didn't change that line in my PR #43658. Was #43658 somehow not the original cause of the bug, then? It maybe just exposed this existing bug more often due to the changed order we check things in?

**Comment by Moelf** [comment]
Yeah I think if that happens last it's not a problem
