### ISSUE TITLE
Showing `Dict`s with `printstyled` elements can color-bleed when truncated

### ISSUE THREAD

**Issue by thchr** [JuliaLang/julia#44718]
The problem is best illustrated by example: define a type and overload `Base.show` for it, using `printstyled` to get some color in the print out:
```jl
struct StyledType
    x::Vector{Int}
end

function Base.show(io::IO, ct::StyledType)
    print(io, ct.x)
    printstyled(io, " +color", color=:red)
end

ct = StyledType(1:3)
```
where `ct` then prints as:
![image](https://user-images.githubusercontent.com/26799210/159786117-34eeb82d-a7c5-4e56-b9ef-a012803022c9.png)

But if we now put `ct` elements into a `Dict`, we get issues with the color when the `Dict` entries' display are truncated:
```jl
d = Dict(n => fill(StyledType(1:n), n) for n = 1:5)
```
![image](https://user-images.githubusercontent.com/26799210/159786302-1868c686-0cda-40d9-9be5-6c501da5b58b.png)

**Comment by KristofferC** [comment]
I started fixing this here: https://github.com/JuliaLang/julia/pull/37568.
