### ISSUE TITLE
typeintersect Vararg aborts

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#44735]
this is not good:
```
julia> typeintersect(Vararg{Int}, Int)
julia: /data/vtjnash/julia/src/subtype.c:1261: subtype: Assertion `!jl_is_vararg(x) && !jl_is_vararg(y)' failed.

signal (6): Aborted
```
and other mild oddities (I think these are correct, since they can appear as type parameters, they should be valid as arguments also)
```
julia> typeintersect(1, 2)
Union{}

julia> typeintersect(1, 1)
1

julia> typeintersect(1, Any)
1

julia> typeintersect(Any, 1)
1
```

**Comment by Keno** [comment]
Well, `Vararg{Int}` isn't really a type. We've been moving away from just allowing arbitrary values in `typeintersect`. I mean, it probably shouldn't abort, but passing in `Vararg{Int}` is probably a bug in the caller.

**Comment by aviatesk** [comment]
Maybe we want to do some assertions on Julia level?

**Comment by Moelf** [comment]
looks like it no longer crashes on master
```julia
julia> typeintersect(Vararg{Int}, Int)
Union{}
```

**Comment by aviatesk** [comment]
You need to have [assert build](https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/build.md#building-an-assert-build-of-julia) to repro this.

**Comment by Moelf** [comment]
I see. as for adding checks in Julia, is this too naive/hacky?
```julia
function typeintersect(@nospecialize(a), @nospecialize(b))
    @_pure_meta
    if typeof(a) !== DataType
        throw(TypeError(:typeintersect, DataType, a))
    elseif typeof(b) !== DataType
        throw(TypeError(:typeintersect, DataType, b))
    end
    ccall(:jl_type_intersection, Any, (Any, Any), a, b)
emd
```

**Comment by JeffBezanson** [comment]
Checking `a isa Type` might be ok.

**Comment by Moelf** [comment]
😅 right
