### ISSUE TITLE
!foo should use (!) ∘ foo

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#44748]
As [discussed on Discourse](https://discourse.julialang.org/t/base-including-notnan-notnothing/78458/7), it would be nice to have `!foo` return a `ComposedFunction`, which would

1. allow dispatch and specialized methods for `!foo`
2. allow nicer pretty printing of `!foo` as `"!foo"` rather than as `"#xx (generic function with 1 method)"` (by overloading `show` for `ComposedFunction{typeof(!)}`)
3. allow `!!foo === foo`

Although `!foo` and `f ∘ g` were introduced at the same time in #17155, when `∘` was subsequently updated in Julia 1.6 to return a special `ComposedFunction` type (#37517), the `!` implementation was not correspondingly updated, which seems like an oversight.

On a related note, it would also be good to fix the `ComposedFunction` show method to put parentheses around operators (or other composed functions), as this is currently broken:
```jl
julia> (!) ∘ isnan
! ∘ isnan

julia> ! ∘ isnan
ERROR: syntax: "∘" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1
```

Should be a fairly easy PR.

**Comment by markmbaum** [comment]
I can try to do this if that's alright. Wanted to contribute for a while and seems like a good opportunity.
