### ISSUE TITLE
julia v1.6.5: unitialized variables in threading.c

### ISSUE THREAD

**Issue by brianmoose** [JuliaLang/julia#44796]
Julia v1.6.5
Running valgrind on `test/embedding/embedding` gives a bunch of errors.
Seems to be a couple of issues, both in `src/threading.c:jl_init_threading()`.

1. `jl_measure_compile_time` and `jl_cumulative_compile_time` never get initialized. Doing a `memset` on the newly created arrays seems to fix this.
2. `codegen_lock` and `typecache_lock` don't seem to be initialized anywhere causing problems when the `count` variable is used. Sticking a `JL_MUTEX_INIT(&codegen_lock)` (and one for `typecache_lock`) in `jl_init_threading()` seems to fix it.

This fixes the valgrind errors (apart from some ones in libunwinding).

I am not all that familiar with julia, I was just tracking down some valgrind errors in our C++ code that embeds julia and noticed
that the julia embedding test exhibited the same errors.

It seems julia uses the `generic` sysimage when in valgrind? So maybe it isn't a problem with other ones? I don't know how any of that works.

Just wanted to check if those are reasonable fixes. Not sure if v1.6 is going to continue to be updated and our code can't update to v1.7 or v1.8 right now so we will probably just patch v1.6.5.

**Comment by KristofferC** [comment]
> Not sure if v1.6 is going to continue to be updated

Since 1.6 is the LTS it will get updated.
