### ISSUE TITLE
zeros(Int64, 2, 3) rather than zeros(Int8, 2, 3) as an example to induce better practices

### ISSUE THREAD

**Issue by oviedorodolfo** [JuliaLang/julia#44809]
Would it be better to change the example `zeros(Int8, 2, 3)` to `zeros(Int64, 2, 3)`? Would the current version induce less than optimal practices?

**Comment by rfourquet** [comment]
It would be useful that you give context on the example you are referring to (e.g. include a link to it).

**Comment by Seelengrab** [comment]
I'm not sure I understand how/why `Int8` is preferrable/better than `Int64`? In what regard is this a "better practice"?

**Comment by oviedorodolfo** [comment]
@rfourquet    The example appears here: `https://docs.julialang.org/en/v1/base/arrays/`
Sorry. I thought that by clicking the link [Edit on GitHub](https://github.com/JuliaLang/julia/blob/master/doc/src/base/arrays.md) I would be giving the information on the web page where the zeros(Int8, 2, 3) could be found.

**Comment by rfourquet** [comment]
Ok it's in the docstring of `zeros` (I should have guessed :) )

**Comment by oviedorodolfo** [comment]
@rfourquet     I am suggesting the reverse of what you say, i.e., that Int64 could be better than Int8.
I got this impression from reading https://discourse.julialang.org/t/is-it-possible-to-force-use-int32-instead-of-int64/41179.

**Comment by fredrikekre** [comment]
"Optimal" depends on what you want to use it for. If you want an array of `Int8`s, then `Int8` is "optimal". The example just shows how to create zeros with a specific type which could be any type. In this case the author chose `Int8`.
