### ISSUE TITLE
Profile Regression: KeyError starting in julia 1.8

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#44818]
I'm not sure exactly what's happening but this simple test has started failing on julia 1.8, which succeeded prior to 1.8:
https://github.com/JuliaPerf/PProf.jl/issues/57

```julia
julia> using Profile

julia> using PProf

julia> @profile peakflops()
9.141912495979059e10

julia> pprof()
ERROR: KeyError: key 0x0000000000000001 not found
Stacktrace:
 [1] getindex
   @ ./dict.jl:499 [inlined]
 [2] pprof(data::Nothing, lidict::Nothing; sampling_delay::Nothing, web::Bool, webhost::String, webport::Int64, out::String, from_c::Bool, full_signatures::Bool, drop_frames::Nothing, keep_frames::Nothing, ui_relative_percentages::Bool)
   @ PProf ~/.julia/packages/PProf/ZEiZQ/src/PProf.jl:199
 [3] pprof (repeats 2 times)
   @ ~/.julia/packages/PProf/ZEiZQ/src/PProf.jl:105 [inlined]
 [4] top-level scope
   @ REPL[4]:1
```

This issue reports that StatProfilerHTML is seeing the same issue:
https://github.com/JuliaPerf/PProf.jl/issues/57#issuecomment-1076515103

Has something in the Profile's export interface changed that these packages were relying on? Thanks!

**Comment by ianatol** [comment]
Bisecting shows https://github.com/JuliaLang/julia/commit/e6fa3ec44e065b8589feb09cba82938fe36aa86d is the culprit.

CC: @IanButterworth (great name btw 😉 )

**Comment by IanButterworth** [comment]
Consumers that want to manually process the profile info need to filter out metadata https://github.com/JuliaPerf/PProf.jl/pull/59

**Comment by NHDaly** [comment]
ahhh gotcha, makes sense! :) Thanks @IanButterworth. 👍 👍 😁 i'm excited to _use it_ instead!

**Comment by NHDaly** [comment]
i forgot about integrating the multithreading features into PProf! Looking forward to that! I've filed https://github.com/JuliaPerf/PProf.jl/issues/60 to track that. Thanks both.

**Comment by IanButterworth** [comment]
I think this can be closed
