### ISSUE TITLE
julia build problems with libgit2 1.4.2 or 1.5.0

### ISSUE THREAD

**Issue by domr2695** [JuliaLang/julia#44811]
Even julia 1.9.0-DEV supports libgit2 v 1.3.0 from Sep 27, 2021.
Is it possible to support libgit2 v 1.4.2 from Feb 26, 2022 ?
Or maybe even libgit2 v 1.5.0 from Feb 26, 2022 commit:db4461d556ddb7915349d094ba74ef01d7a2d701.
Otherwise, the julia + libgit2 v 1.4.2 or v 1.5.0 build never completes.

**Comment by vtjnash** [comment]
I think there is relevant discussion here: https://github.com/JuliaLang/julia/pull/42311, where we have been waiting for libssh2 to make a security-critical release for several months

**Comment by ViralBShah** [comment]
I believe we are already vendoring the libssh2 security patch ourselves. Maybe someone just needs to provide a PR to bump libgit2 (and work through the issues that show up)?

**Comment by fxcoudert** [comment]
From the libgit2 release notes for 1.4.0:

> Deprecated APIs
> - git_index_checksum is deprecated; this information is now internal to the library and there is no replacement
> - git_indexer_hash is deprecated; callers should use git_indexer_name to retrieve the filename
> - git_packbuilder_hash is deprecated; callers should use git_packbuilder_name to retrieve the filename
>
> ABI changes
> - git_fetch_options now includes the follow_redirects value
> - git_push_options now includes the follow_redirects value
> - git_status_options now includes the rename_threshold value
> - git_transport contains several changed function pointer signatures

From a quick check of the julia codebase, I think the `git_fetch_options` and `git_push_options` types need to change. I would be willing to try to add these new types, if you can give some guidance.

**Comment by fxcoudert** [comment]
I've opened a PR to fix the issue: https://github.com/JuliaLang/julia/pull/45411
