### ISSUE TITLE
Mixed Type promotion in a Vector regression on nightly

### ISSUE THREAD

**Issue by evetion** [JuliaLang/julia#44821]
On all recent nightlies ArchGDAL (see https://github.com/yeesian/ArchGDAL.jl/issues/285) started failing.

On Julia 1.8 and below the following `[a::ArchGDAL.RasterBand{UInt8}, b::ArchGDAL.IRasterBand{UInt8}]` will promote to a `Vector{ArchGDAL.AbstractRasterBand{UInt8}}` (note the `I`, the types differ).

The type hierarchy is `(I)RasterBand <: ArchGDAL.AbstractRasterBand <: AbstractDiskArray{T,2} <: AbstractArray{T,N}`.

On Julia 1.9 however the same is promoted all the way up the hierarchy to a
`Vector{Matrix{UInt8}}`.

**Comment by evetion** [comment]
Thanks for the reference! But the fix is only a workaround, right? 

In this case, by converting to a Matrix, the in between disk array, normally only lazy loaded, is unintentionally materialized. There are probably other packages with useful in between types that will be impacted by this breaking change.

**Comment by thchr** [comment]
I'm not sure I understand; my suggestion was just to change `[A, B]` to `(A, B)` which will give you a heterogeneous tuple with type `Tuple{ArchGDAL.RasterBand{UInt8}, ArchGDAL.IRasterBand{UInt8}}`. I can't see how this could affect materialization/laziness?

**Comment by evetion** [comment]
Sorry for the confusion, the tuple does indeed work and won't affect laziness.

My point was about the apparent design decision about this promotion of types, the one that led you to close your referenced issue, that seems like a unintentionally breaking change.

**Comment by vtjnash** [comment]
The [] syntax means vcat promotion. Always has. Seen the linked issues above for other syntax which mean something else (such as T[]).

**Comment by evetion** [comment]
Quoting @vtjnash here from #44096 for visbility
> [a, b] is a general pattern for changing a and b to ***a*** common type. If you do not want that, you must specify the type of the array you want (usually Any[...])

(*emphasis mine to indicate the common type is not stable*)

So we either need to explicitly define the type we want in using `[]` or define `promotion_rule`s (see [docs](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Defining-Promotion-Rules)) for our custom types.
