### ISSUE TITLE
Imprecise answer subtracting two floating point numbers

### ISSUE THREAD

**Issue by SamuraiAku** [JuliaLang/julia#44833]
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)

julia> 155.07-138.73
16.340000000000003
```

**Comment by Seelengrab** [comment]
This is expected, documented & correct behavior. Julia uses IEEE754 floating point arithmetic. You can check these for some more information:

 * https://0.30000000000000004.com
 * https://discourse.julialang.org/t/psa-floating-point-arithmetic/8678
