### ISSUE TITLE
LinearAlgebra.normalize(x) should work for scalars

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#44835]
Currently, this is defined only for arrays, but it seems like we should have
```jl
normalize(x::Number) = x / abs(x)
```
(I just came across this when trying to implement [this algorithm](https://arxiv.org/abs/math-ph/0609050) for random unitary matrices, which is basically `Q * Diagonal(normalize.(diag(R))`, but I discovered that `normalize` didn't work.)

**Comment by Seelengrab** [comment]
Is this the same as `sign(x)` for numbers?

**Comment by oscardssmith** [comment]
it's very similar, but has different behavior for zero.

**Comment by Seelengrab** [comment]
Does that matter for this case? If I'm reading the paper right, `R` should be invertible, so no zeros on the main diagonal :thinking:

**Comment by stevengj** [comment]
Yes, in this particular case, you're right that I could have used `sign`.

However, it still doesn't make sense to me that the `normalize` function isn't defined for scalars.

**Comment by Seelengrab** [comment]
If you're fine with getting `fill(NaN, size(x))` on `all(iszero, x)`, sure - seems like a good addition, maybe in addition to a `normalize!` function as well?

**Comment by mikerouleau** [comment]
I've been meaning to get more involved and this looks like a good first issue. I should have a PR ready later today.
