### ISSUE TITLE
ldlt EXTREMELY slow: wrong method called?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#44847]
Issue described here:
https://discourse.julialang.org/t/is-suitesparse-cholmod-ldlt-working-correctly/78951

For a sparse matrix (CSC) ldlt is extremely slow (~170 slower than cholesky). I can't believe that the problem is fallback to dense linear algebra: the matrix is too large for this to go through. But go through it does: correct solution is returned.

**Comment by fredrikekre** [comment]
https://github.com/JuliaSparse/SparseArrays.jl
