### ISSUE TITLE
SuiteSparse wastes memory: duplication of sparse matrix storage

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#44848]
The issue is https://discourse.julialang.org/t/problem-with-suitesparse-memory-duplication/78977

Due to the duplication of the sparse matrix storage when it is converted to `Sparse`, use of the library leads to wasteful memory management. 

I think we need a Julia-only library for this purpose.

**Comment by fredrikekre** [comment]
https://github.com/JuliaSparse/SparseArrays.jl
