### ISSUE TITLE
Some builds for tester_linux32 has been sitting in the queue about a week

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#44859]
https://build.julialang.org/#/builders/17 shows that some build requests on tester_linux32 are submitted 6 days ago. Strangely, tester_linux32 still has been processing more recent builds.

![image](https://user-images.githubusercontent.com/29282/161677269-a02567b2-c4fb-4ea1-8a47-db2df16e66e9.png)

Only one out of seven most recently merged PRs have tester_linux32 build finished:

https://github.com/JuliaLang/julia/pull/44853
https://github.com/JuliaLang/julia/pull/44855
https://github.com/JuliaLang/julia/pull/44854
https://github.com/JuliaLang/julia/pull/44854
https://github.com/JuliaLang/julia/pull/44810
https://github.com/JuliaLang/julia/pull/44717 https://build.julialang.org/#/builders/17/builds/2062
https://github.com/JuliaLang/julia/pull/44577

**Comment by vtjnash** [comment]
tester_linux32 is gone / buildkite works
