### ISSUE TITLE
Source links in the documentation for 1.7.2 are broken

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#44863]
As an example: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.cholesky!.
The link is https://github.com/JuliaLang/LinearAlgebra/src/cholesky.jl#L271-L291 -- Not found.

**Comment by dkarrasch** [comment]
Indeed, and there are more cases nearby. One `cholesky!` docstring referring to the method from SuiteSparse.jl is also broken. But I fail to find a difference between the correctly working links for `cholesky` and some of the broken ones for `cholesky!`. The exact same behavior is observed when switching to the nightly branch of the docs.

**Comment by fredrikekre** [comment]
#43307
