### ISSUE TITLE
Feature request: Make REPL sessions recordable in code

### ISSUE THREAD

**Issue by feanor12** [JuliaLang/julia#44872]
Currently only a global history file is saved. By passing `--history-file=` a session can be saved, but often I don't know I want this when I start the session. 
As the session is recorded by default anyway it would be good to be able to save the current session without the use of a special flag at the beginning.
Therefore a function to save the history of the current session would be good to have.

* start_recording(file or IOBuffer or collection?)
* reset_recording() # reset current history content
* stop_recording() # return current history in case it is used otherwise
* continue_recording()
* save_session(filename, output=true/false)

With that a session could be recorded an discarded afterwards. Maybe an updated index to the entries in the global history file would also be enough. Using this index the history could be extracted for the specific session.

**Comment by giordano** [comment]
Mostly a duplicate of #44681 (once you have an ID, you can more easily export the entire session).

**Comment by feanor12** [comment]
The other issue suggested to move the index to the global log file. This would require a public function that can provide the current uuid of the session. I think it is an easier solution to implement.
