### ISSUE TITLE
Running additional local processes affects behavior of inv()

### ISSUE THREAD

**Issue by sbos** [JuliaLang/julia#4488]
The following code prints different numbers depending on were the "-p N" option passed to Julia interpreter or not.

```julia
function bug(N)
    A = zeros(N, N) 

    for i=1:N 
        A[i, i] = 1. 
        for j=i-1:-1:1 
            if i-j < 6 
                A[i, j] = -exp( (j-i) / 3. ) 
            end 
        end 
        A[i, i-1:-1:1] /= -(sum(A[i, i-1:-1:1]) - 0.5) 
    end 

    return sum(inv(A) .< 0)
end

for N=1:110
    println(N, " ", bug(N))
end
```

On my machine "-p 1" causes non-zero negative counts starting from N=65. What is especially funny is that even "-p 0" reproduces this bug (?).

My version of Julia is:
```
Julia Version 0.2.0-prerelease+3986
Commit 2e5242a* 2013-10-09 23:17:29 UTC
Platform Info:
  System: Darwin (x86_64-apple-darwin11.4.2)
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm
```

CPU is Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz, Mac OS 10.7.5. Julia was installed from homebrew.

Discussion in the mailing list: https://groups.google.com/forum/#!topic/julia-users/zT9cVrWQ5t4

**Comment by andreasnoack** [comment]
@staticfloat Do you still have the machine on which this happened and are you still able to reproduce it?

**Comment by staticfloat** [comment]
On my macbook pro, running the 0.3.10 (homebrew) binaries, I'm able to synthesize a case that is about as bad as the one shown above:

```
begin
	srand(41)
	N = 80
	A = randn(N,N)
	B = inv(A)
	Base.disable_threaded_libs()
	C = inv(A)

	println("Infinity norm of difference: $(maximum(abs(B - C)))")
	println("L-1 norm of difference: $(sum(abs(B - C)))")
end
```

Running the above yields:
```
Infinity norm of difference: 1.3468479664879851e-9
L-1 norm of difference: 6.526577266130484e-7
```

Here's my `versioninfo()`:

```
julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Running on the 0.3.10 (Homebrew) binaries on my Mac Mini, I get similar results:
```
Infinity norm of difference: 1.3468479664879851e-9
L-1 norm of difference: 6.526577266130484e-7

julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef* (2015-06-24 13:54 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Running on the 0.3.10 Ubuntu binaries, I also get similar results:
```
Infinity norm of difference: 2.3602524379384704e-9
L-1 norm of difference: 1.1441235184808315e-6

julia> versioninfo()
Julia Version 0.3.10
Commit c8ceeef (2015-06-24 13:54 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by andreasnoack** [comment]
@staticfloat Would you try the original test again to see if that is still an issue? I don't think the errors you show are larger than can be justified by theory and if I compare to an inverse computed in `BigFloat`s they are similar.

**Comment by staticfloat** [comment]
I can no longer reproduce the original bug on 0.4.1.  Yay!  @sbos, I'm going to close this, if you still run into the issue feel free to comment here and we can continue the discussion.

**Comment by sbos** [comment]
Yes, it seems that bug is fixed now.
