### ISSUE TITLE
Bug with range() and unsigned indices

### ISSUE THREAD

**Issue by gerw** [JuliaLang/julia#44895]
The snippet
````julia
x = range(-1,1,length=11)
x[UInt(1)]
````
gives `3.6893488147419105e18` instead of the expected `-1.0`. 

The problem seems to be https://github.com/JuliaLang/julia/blob/0d2971216ff903c47de98918e7b100de4607e012/base/range.jl#L939, since `UInt(1) - 6` underflows.

````
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

````

**Comment by Seelengrab** [comment]
Can confirm on (somewhat recent) master. I think there are more places out there hiding like that, like #42528 in the past.. Finding those will be a little bit of a challenge :/

**Comment by gbaraldi** [comment]
I wonder how we could fix this. Casting it to an integer means that there would be indices that aren't representible. But ranges currently assume that you can have a negative index. I guess adding a special dispatch for unsigned integers that does some checking while leaving the normal integer one alone could work.

**Comment by Seelengrab** [comment]
Yeah, special casing `Unsigned` vs. `Signed` is sadly necessary, because of those assumptions about underflow on `<: Integer`.

Note that negative indices are still fine here, they can live happily in the `Signed` path, since there can't ever be a negative `UInt` anyway.

The same fix should be applied to 

https://github.com/JuliaLang/julia/blob/0d2971216ff903c47de98918e7b100de4607e012/base/range.jl#L943-L947

as well.

**Comment by gbaraldi** [comment]
I was giving this a stab, the same functions in twiceprecision.jl also have to changed.
I had two ideas one is simply :
```julia
function unsafe_getindex(r::StepRangeLen{T}, i::Unsigned) where T
    i = Int(i)
    u = i - r.offset
    T(r.ref + u*r.step)
end
```
It does mean that very large unsigned ints will fail. Another idea is to put the type cast behind an if statement. But that would be type unstable.

**Comment by vtjnash** [comment]
My untested recommendation is (after bitter experience dealing with similar questions for computing length haha) is to force inbounds math via a branch here:
```julia
function unsafe_getindex(r::StepRangeLen{T}, i::Integer) where T
    i isa Bool && throw(ArgumentError("invalid index: $i of type Bool"))
    if i < r.offset # 1 <= offset <= len && 1 <= i <= len
        u = r.offset - i
        return T(r.ref - u*r.step)
    else
        u = i - r.offset
        return T(r.ref + u*r.step)
    end
end
```

and also needs to apply to
```
function getindex(r::StepRangeLen{T}, s::OrdinalRange{S}) where {T, S<:Integer}
```

**Comment by gbaraldi** [comment]
Would keeping the dispatch separated be better to avoid a branch on signed integers? Or would the performance difference not be that significant?

**Comment by gbaraldi** [comment]
There are a lot of cases where the same error happens. I will open a PR to get started.

**Comment by adienes** [comment]
could this possibly be tagged for 1.10? it's pretty easy to encounter; many combinations of `range(x, y, z)[m]` for `x < 0`, `y > 0`, and unsigned `m` will silently return undef values
