### ISSUE TITLE
change ill-considered @invoke behavior

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#44902]
https://github.com/JuliaLang/julia/pull/38438 introduced this unfortunate behavior:
```jl
abstract type Foo end
struct Bar <: Foo end

f(x::Foo, y) = 1
f(x::Foo, ::Nothing) = 2
f(x::Bar, y) = 3
f(x::Bar, ::Nothing) = 4

x = Bar()
Base.@invoke f(x::Foo, nothing)  # should return 2, returns 1
```
Example due to @danielwe. I really think we should reconsider this. Yes, it's technically breaking. But man, this was really introduced and merged without enough discussion 😞. There were several objections to this behavior right after the PR was merged but then nothing was done about it.

**Comment by fredrikekre** [comment]
`@invoke` is not exported and have no docs, so I think it is fair game to change (and perhaps export it in the process).

**Comment by adkabo** [comment]
https://docs.julialang.org/en/v1/base/base/#Base.@invoke
