### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by AnimalStudioOfficial** [JuliaLang/julia#44904]
I run make and got:

process_begin: CreateProcess(NULL, uname, ...) failed.
C:/julia-master/julia-master/Make.inc:113: pipe: Bad file descriptor
Warning: git information unavailable; versioning information limited
process_begin: CreateProcess(NULL, cat C:/julia-master/julia-master/VERSION, ...) failed.
C:/julia-master/julia-master/Make.inc:191: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, uname, ...) failed.
C:/julia-master/julia-master/Make.inc:378: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, cc --version, ...) failed.
C:/julia-master/julia-master/Make.inc:463: pipe: Bad file descriptor
Makefile:40: *** target pattern contains no '%'.  Stop.

**Comment by vtjnash** [comment]
Seems like your build environment is broken. Try cygwin rather than other (native) environments or gnulib tools

**Comment by AnimalStudioOfficial** [comment]
> Seems like your build environment is broken. Try cygwin rather than other (native) environments or gnulib tools

How do you do that

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/windows.md

**Comment by AnimalStudioOfficial** [comment]
> https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/windows.md

TYSM it worked and I did get a warning:

 /cygdrive/c/julia-master/julia-master/src/jitlayers.cpp: In lambda function:
/cygdrive/c/julia-master/julia-master/src/jitlayers.cpp:503:73: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'long long int' [-Wformat=]
  503 |                 jl_printf(dump_llvm_opt_stream, "        basicblocks: %lu\n", countBasicBlocks(F));
      |                                                                       ~~^     ~~~~~~~~~~~~~~~~~~~
      |                                                                         |                     |
      |                                                                         long unsigned int     long long int
      |                                                                       %llu
/cygdrive/c/julia-master/julia-master/src/jitlayers.cpp:531:73: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'long long int' [-Wformat=]
  531 |                 jl_printf(dump_llvm_opt_stream, "        basicblocks: %lu\n", countBasicBlocks(F));
      |                                                                       ~~^     ~~~~~~~~~~~~~~~~~~~
      |                                                                         |                     |
      |                                                                         long unsigned int     long long int
      |                                                                       %llu
