### ISSUE TITLE
[Feature] Remove the syntax `for i = 1:10` in julia

### ISSUE THREAD

**Issue by hungpham3112** [JuliaLang/julia#44919]
As the official document in julia 1.7.2, the syntax `for i = 1:10` and `for i in 1:10` are equivalent. But the former seems weird and doesn't make sense. 

```
julia> i = 1:10
1:10

julia> typeof(i)
UnitRange{Int64}

julia> x = UnitRange{Int64}(1, 10)
1:10

julia> i == x
true
```

Type of  `i` is `UnitRange{Int64}` and it's ok. Same like python `for i in range(1, 10)`, it's clear, concise and readable. But if you read in julia:

```
for i = 1:10                                           for UnitRange{Int64}(1, 10)
   print(i)                         ==                     print(where is i)
end                                                    end
``` 

I'm new with julia but still want to contribute for this language. If I have something wrong or misunderstood about this syntax, help me to understand that. Thanks.

**Comment by jishnub** [comment]
While I'm not familiar with the historical context, the `i = 1:10` syntax overlaps with MATLAB, and might make the transition to julia easier for MATLAB users. The other way to write the loop --- with `in` --- makes the transition from python easy. Personally, I prefer the latter as well, but I don't really see what is to be gained by removing the former altogether, at the expense of breaking existing codes. Ultimately, it's a matter of style that may be enforced in a particular project.

**Comment by johnnychen94** [comment]
https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872 is also worth reading.

> That means no more changing existing syntax. ... We can add new syntax, new functions, new names, new methods, etc. but we can’t change the existing ones (at least not the ones that are exported and documented).

Removing `for i = 1:10` syntax is breaking so it has to be at least 2.0. TBH I doubt people want to pay such efforts only to make MATLAB users unhappy; usually, we only change the existing syntax when there's a practical need.

**Comment by hungpham3112** [comment]
> While I'm not familiar with the historical context, the `i = 1:10` syntax overlaps with MATLAB, and might make the transition to julia easier for MATLAB users. The other way to write the loop --- with `in` --- makes the transition from python easy. Personally, I prefer the latter as well, but I don't really see what is to be gained by removing the former altogether, at the expense of breaking existing codes. Ultimately, it's a matter of style that may be enforced in a particular project.

Yes, I agree with you to keep this syntax in this version of Julia to make it familiar with MATLAB users. I understand that Julia focus on  numerical analysis and computational science and want the syntax more convenient with Python, MATLAB, R.. users. IMO if Julia want to win in the long-run, it really need to keep syntax clean as much as possible, no more "cruft" thing like that. Look how Rust syntax is the reason why people love it. 

https://stackoverflow.blog/2020/06/05/why-the-developers-who-use-rust-love-it-so-much/

> Last but not least, the batteries which are included: the small and concise syntax, the small number of features the language provides, the integrity of the standard library as well as its consistency and the quality of its documentation, including the learning materials for both beginners and advanced users are all contributing factors.”

When Julia 2.0 come out, maybe I will open this issue again.

**Comment by StefanKarpinski** [comment]
> when Julia 2.0 comes out, maybe I'll reopen this issue.

If this syntax is still in the language when Julia 2.0 comes out it will be too late until Julia 3.0.
