### ISSUE TITLE
Copy script to the julia REPL look weird.

### ISSUE THREAD

**Issue by hungpham3112** [JuliaLang/julia#44927]
https://user-images.githubusercontent.com/75968004/162595753-fc22f364-22a1-4693-8934-d1a81179ac49.mp4

I'm using Julia latest with scoop on Windows 11.

**Comment by inkydragon** [comment]
Maybe related:  [Pasting in multiline code terminal regression · Issue #25186 · JuliaLang/julia](https://github.com/JuliaLang/julia/issues/25186)

**Comment by hungpham3112** [comment]
> Maybe related: [Pasting in multiline code terminal regression · Issue #25186 · JuliaLang/julia](https://github.com/JuliaLang/julia/issues/25186)

This is exactly issue what I'm facing.

![image](https://user-images.githubusercontent.com/75968004/164708782-f369a61e-845d-40d3-82c7-f3847ea65b14.png)

**Comment by vtjnash** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/53763
