### ISSUE TITLE
blink parameter in printstyled ignored in VS Code terminal

### ISSUE THREAD

**Issue by aerdely** [JuliaLang/julia#44928]
`blink = true` in `printstyled` is ignored when the REPL is opened through VS Code, but it does work if I open a julia terminal out of VS Code (Windows OS).
```
printstyled("Azul", underline = true, blink = true, color = :blue)

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
```

**Comment by simeonschaub** [comment]
Seems like the VS Code terminal just doesn't support the specific ANSII sequence. This isn't specific to Julia. Ref https://stackoverflow.com/questions/68926235/vscode-and-idle-not-outputting-blinking-text-appropriately

**Comment by johnzoet** [comment]
Not working in DOS shell on Windows 10 either.
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab7 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

**Comment by vtjnash** [comment]
It is not unusual for `blink` to be disabled in the terminal settings on *nix systems. Might be true on yours also?

**Comment by johnzoet** [comment]
Have blink issue on Windows 10.
Edition     Windows 10 Pro
Version     21H2
Installed on      ‎7/‎03/‎2021
OS build    19044.1889
Experience  Windows Feature Experience Pack 120.2212.4180.0

________________________________
