### ISSUE TITLE
CI: non-deterministic failures in `cmdlineargs`, `spawn` on both Intel macOS and Apple Silicon macOS

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#44947]
Here are some examples of `cmdlineargs` failing on macOS x86_64:
1. https://buildkite.com/julialang/julia-master/builds/11163#d4f443e0-f55b-4d56-ad5c-ad3b35ce943b
2. https://buildkite.com/julialang/julia-master/builds/11162#493281b1-84b7-495f-b73b-19da937e7f12

Here are some examples of `spawn` failing on macOS x86_64:
1. https://buildkite.com/julialang/julia-master/builds/11162#c33f71cc-cedc-4fc0-8d63-510890ce121a

**Comment by maleadt** [comment]
Probably https://github.com/JuliaLang/julia/issues/44562? That happens during process teardown, and the cmdlineargs test there spawns a Julia process.
