### ISSUE TITLE
ldiv! has incorrect behavior for BunchKaufman factorizations with different vector types

### ISSUE THREAD

**Issue by dgleich** [JuliaLang/julia#44973]
Here is a minimal example of what is wrong when using ldiv! with BunchKaufman factorizations where the vector type differs from the factorization type. 

```
using Test, LinearAlgebra
@testset "BunchKaufman multitype conversion" begin 
  n = 100
  B = Matrix(SymTridiagonal(4*ones(n),ones(n-1))).*(1/(6*(n+1)))
  S = bunchkaufman(Symmetric(B)) # this is what factorize does on this matrix

  x = ones(n)
  ldiv!(S,x)
  @test B*x ≈ ones(n)

  y = ones(Float32,n)
  ldiv!(S,y)
  @test B*y ≈ ones(n)

  z = ones(ComplexF64,n) # this is correct because 
  ldiv!(S,z)
  @test B*z ≈ ones(n)
end
```

The expected behavior is that `y` should have the solution, like `x`, `z`. But that doesn't happen. 
Looking at the code in <https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/bunchkaufman.jl> on master shows the function.

```
# There is no fallback solver for Bunch-Kaufman so we'll have to promote to same element type
function ldiv!(B::BunchKaufman{T}, R::StridedVecOrMat{S}) where {T,S}
    TS = promote_type(T,S)
    return ldiv!(convert(BunchKaufman{TS}, B), convert(AbstractArray{TS}, R))
end
```

This has the subtle bug that the solution is written into the _converted_ array, which is then returned. But the original input that ought to be mutated `R` is not changed.  Note that it works in the `ComplexF64` case because the vector isn't promoted there. 

One fix for the `T = Float64, R = Float32` case just involves copyto. Although, I'm not sure how general that behavior is. 
```
import LinearAlgebra: ldiv!
function ldiv!(B::LinearAlgebra.BunchKaufman{T}, R::LinearAlgebra.StridedVecOrMat{S}) where {T,S}
  TS = promote_type(T,S)
  R_with_TS = convert(AbstractArray{TS}, R)
  ldiv!(convert(BunchKaufman{TS}, B), R_with_TS)
  if R_with_TS !== R
    copyto!(R, RTS)
  end 
end
```

This behavior occurs on the following two versions of Julia. 

```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake-avx512)

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, haswell)
```

**Comment by dkarrasch** [comment]
The `BunchKaufman` solver needs both element types to match, so there really is no point in providing such a function. Even the workaround is bad because it allocates another copy of the rhs, which goes against the expectation of `ldiv!`. This function was removed in v1.9 (it was also untested), so users will need to take care of matching eltypes.
