### ISSUE TITLE
argmin / findmin incorrect behaviour on SparseVector on 1.8

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#44978]
This behaviour is incorrect, I'm not sure there is documentation on which case would produce nothing for findmin

On 1.8.0-beta3
```julia
julia> v = zeros(3)

julia> argmin(v)
1

julia> v[1] = 2

julia> argmin(v) 
2

# incorrect on sparse
julia> v = spzeros(3)
3-element SparseVector{Float64, Int64} with 0 stored entries

julia> v[1] = 2
2

julia> argmin(v) === nothing
true
```

**Comment by matbesancon** [comment]
Yeah I tripled-checked the doc before, thought I had missed an expected behaviour

**Comment by matbesancon** [comment]
the issue is still there on 1.8 released
```julia
julia> using SparseArrays
julia> direction = spzeros(3); direction[1] = 2

julia> argmin(direction) === nothing
true
```

**Comment by KristofferC** [comment]
SparseArrays.jl (https://github.com/JuliaSparse/SparseArrays.jl) need to create a backport 1.8 branch where they backport the fix for this and it can be put into 1.8.

**Comment by matbesancon** [comment]
Linking the corresponding issue:
https://github.com/JuliaSparse/SparseArrays.jl/issues/239

**Comment by matbesancon** [comment]
@KristofferC is the backport planned for 1.8.1? It is a pretty serious regression to have lying around IMO and can break a lot of user code (as it broke at least one registered package)
