### ISSUE TITLE
Inconsistent slurping of NamedTuple

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#44981]
```julia
julia> (a,b,c...) = (; x=1,y=2,z=3,w=4)
(x = 1, y = 2, z = 3, w = 4)

julia> a
1

julia> b
2

julia> c
(z = 3, w = 4)
```

Shouldn't `c` be `(3, 4)`?

**Comment by JeffBezanson** [comment]
Slurping is defined in terms of `rest`, because it does not need to iterate all the values eagerly. The result `(z = 3, w = 4)` iterates the same as `(3, 4)` so I think it's correct.

**Comment by cstjean** [comment]
Agreed, makes sense!
