### ISSUE TITLE
Feature request: a variant of `@cfunction` that returns a functions pointer and a data pointer

### ISSUE THREAD

**Issue by melonedo** [JuliaLang/julia#45006]
Currently, `@cfunction` wraps the given function, and returns a normal function pointer for it. This works very well for pure functions that preserves no data. However, if it is passed a closure, it relies on LLVM trampolines, which is not available for all platforms. 

A de facto standard for passing closures in C is to use a function pointer **and** a data pointer, that is, when we need closure functions, (In both C and Julia) we do the following to manually implement a closure:

1. Define a type that stores needed data.
2. Define a function that interprets the data pointer as captured data.
3. The pair of pointers is passed to the C library for callbacks.

So I request a variant of `@cfunction` that makes use of this interface, arbitrarily named `@cclosure`, which:

- Accepts the same arguments as `@cfunction`: 

```julia
@cclosure $closure_function return_type (arg1_type, arg2_type, __closure_data__)
```

- In case of a pure function, return a function pointer and `C_NULL`
- In case of a closure, return a function pointer and a function pointer to the closure data.
- The pointer to the closure data serves as a root for captured variables.

The implementation could be either
- trivialyl, the function pointer is merely a stub that `unsafe_pointer_to_objref` the data pointer and execute it; 
- or more type stably, the function pointer is the body of the Julia closure, and the data pointer points to the closure.

The reason this functionality should be in Base is that I am not sure whether the latter implementation could be done without a lot of 

With this feature, [the closure function example](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Closure-cfunctions) from the manual can be implement in more platforms with `qsort_r`:

```julia
# with qsort
function qsort(a::Vector{T}, cmp) where T
    isbits(T) || throw(ArgumentError("this method can only qsort isbits arrays"))
    callback = @cfunction $cmp Cint (Ref{T}, Ref{T})
    ccall(:qsort, Cvoid, (Ptr{T}, Csize_t, Csize_t, Ptr{Cvoid}),
        a, length(a), Base.elsize(a), callback)
    return a
end
# with qsort_r
function qsort_r(a::Vector{T}, cmp) where T
    isbits(T) || throw(ArgumentError("this method can only qsort isbits arrays"))
    callback, data = @cclosure $cmp Cint (__closure_data__, Ref{T}, Ref{T})
    ccall(:qsort_r, Cvoid, (Ptr{T}, Csize_t, Csize_t, Any, Ptr{Cvoid}),
        a, length(a), Base.elsize(a), data, callback)
    return a
end
```

**Comment by vtjnash** [comment]
You could implement this in a package quite easily, since `data` is always just the function object and the callback is just trivially this:
```julia
function qsort_r(a::Vector{T}, cmp::Cmp) where T where Cmp
    isbits(T) || throw(ArgumentError("this method can only qsort isbits arrays"))
    callback = @cfunction (cmp, a, b) -> cmp(a, b) Cint (Ref{Cmp}, Ref{T}, Ref{T})
    ccall(:qsort_r, Cvoid, (Ptr{T}, Csize_t, Csize_t, Ref{Cmp}, Ptr{Cvoid}),
        a, length(a), Base.elsize(a), cmp, callback)
    return a
end
```
I thought we had some examples of this already (outside of Gtk and PyCall where I know we use this), but don't see them.

**Comment by vchuravy** [comment]
I think the bigger issue is that `@cfunction($f)` can not work on aarch64 since they are missing a register in the ABI for the thunk calling convention
and that `-fno-trampoline` (e.g. descriptors) requires recompilation of the C library. Thus an alternative interface where we explicitly pass the data pointer has some charm.

**Comment by vtjnash** [comment]
> the -ftrampolines and -fno-trampolines options currently have no effect
?

Why couldn't it push a value onto the stack? There is no precise requirement that the trampoline target have the same calling convention as the caller assumed (just the original stack offset does need to be recoverable)
