### ISSUE TITLE
CI: Non-deterministic timeouts of the macOS x86_64 tester

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#45014]
| CI log                                                                                                | Architecture | Timeout    | Worker that was running | Test set that was running | 
| ----------------------------------------------------------------------------------------------------- | ------------ | ---------- | ----------------------- | ------------------------- |
| [log](https://buildkite.com/julialang/julia-master/builds/11184#aa444357-751e-4fd1-8b9d-d4616f91700e) | x86_64       | 90 minutes | 12                      | `iostream`                |

Note: our test suite proceeds as follows:
1. We start 13 worker processes, since the Intel Mac machines have 12 physical cores.
2. In the parallel portion of the test suite, we don't run tests on worker 1; we only run tests on workers 2 through 13.
3. In the serial portion of the test suite, we only run tests on worker 1.

**Comment by vtjnash** [comment]
I think we added some new coredump abilities, so we can make a new issue if this repeats now
