### ISSUE TITLE
Should honor IOContext in showing Array type name

### ISSUE THREAD

**Issue by complyue** [JuliaLang/julia#45066]
https://github.com/JuliaLang/julia/blob/3cff21e725097673f969c19f8f0992c9a0838ab3/base/arrayshow.jl#L584

Seems the following change is reasonable:

```diff
-            sprint(show_type_name, unwrap_unionall(eltype_X).name), false # Print "Array" rather than "Array{T,N}"
+            sprint(show_type_name, unwrap_unionall(eltype_X).name; context=io), false # Print "Array" rather than "Array{T,N}"
```

Or qualified (with module path) Array type name will be printed even if `:compact => true` is requested from the far out.

**Comment by sagnik3** [comment]
Hello, this is my first time contributing to open source. I have opened a pull request https://github.com/JuliaLang/julia/pull/45277 that tries to fix this issue. If anybody could give me any review on what should I do after this it would be awesome!

**Comment by vmpyr** [comment]
This issue seems to have been solved. If there is some work still left, please let me know, I can start work

**Comment by vtjnash** [comment]
AFAIK, https://patch-diff.githubusercontent.com/raw/JuliaLang/julia/pull/45277.patch is not merged yet

**Comment by vmpyr** [comment]
Can you please review and merge it then @vtjnash? If there are still problems I can take up this issue

**Comment by vtjnash** [comment]
I have reviewed it, and it needs someone to add a test (https://github.com/JuliaLang/julia/pull/45277#issuecomment-1139250945) and open a new PR with it.

**Comment by vmpyr** [comment]
I can try adding a test if currently no one is on it. I'm a bit of a beginner though and might need some help.
