### ISSUE TITLE
`Cmd` doc ref in `Running external Programs` is broken

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#45060]
![screenshot_2022-04-22_13-21-50_680770093](https://user-images.githubusercontent.com/11753998/164705204-6e2cb7f8-decf-4c98-81b3-29f88b9f9c8d.png)

This is at the bottom of https://docs.julialang.org/en/v1/manual/running-external-programs/. Weirdly enough, the source looks perfectly fine and is exactly the same as for the `setenv` and `addenv`, so there's no indication of why it's broken. This is the 1.7.2 docs.

**Comment by fredrikekre** [comment]
Fixed by #41838.

**Comment by Seelengrab** [comment]
Ah, right! Should have checked on a more recent doc version as well, my bad. Sorry for the noise.
