### ISSUE TITLE
Include docs for in-progress release on docs.julialang.org

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#45073]
Currently, we have 1.7 released, 1.8 branched but being prepared, and 1.9-DEV. docs.julialang.org shows only 1.7 and 1.9-dev. It would be really handy to have the in-progress release being prepared (1.8-dev) on docs.julialang.org as well, along with the PDF.

**Comment by fredrikekre** [comment]
Documentation for release candidates are shown (https://github.com/JuliaLang/julia/pull/36859). In any case, the best documentation for any Julia 1.X is really the one built from the master branch.

**Comment by ViralBShah** [comment]
I don't see it on docs.julialang.org. My main point is that it is confusing for people who may wonder why a particular release number is being skipped. I also sometimes want to check what the RC documentation looks like, but don't find it in the obvious place I look.

<img width="283" alt="Screen Shot 2022-04-24 at 10 03 19 AM" src="https://user-images.githubusercontent.com/744411/164980329-83af59a0-2b41-44b9-8af5-93d458012833.png">

**Comment by fredrikekre** [comment]
There haven't been a rc for 1.8 yet.

**Comment by ViralBShah** [comment]
Oh, so we only do it for RCs and not betas and such. Would be nice to have the betas as well.

**Comment by fredrikekre** [comment]
Yea, shouldn't be difficult to modify the code from the PR I linked above.
