### ISSUE TITLE
foldr on zip of different lengths

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#45085]
It's unclear to me whether this is a bug or intended behavior. I expected `foldr(f, collect(x))` to be the same as `foldr(f, x)`.
```julia
help?> zip
search: zip

  zip(iters...)

  Run multiple iterators at the same time, until any of them is exhausted.[...]

julia> foldr(println, zip(1:3, 1:4), init=nothing)
(3, 4)nothing
(2, 3)nothing
(1, 2)nothing

julia> foldr(println, collect(zip(1:3, 1:4)), init=nothing)
(3, 3)nothing
(2, 2)nothing
(1, 1)nothing
```

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/blob/9d14cb147d489093a99a6b763d75729174a8860e/base/iterators.jl#L425

**Comment by oscardssmith** [comment]
IMO, this assumption is buggy.

**Comment by Moelf** [comment]
```julia
julia> reverse(collect(zip(1:3, 1:4)))
3-element Vector{Tuple{Int64, Int64}}:
 (3, 3)
 (2, 2)
 (1, 1)

julia> collect(Iterators.reverse(zip(1:3, 1:4)))
3-element Vector{Tuple{Int64, Int64}}:
 (3, 4)
 (2, 3)
 (1, 2)
```

both of these should return the first one?

**Comment by LilithHafner** [comment]
> do we agree both of these should return the first result?

I do

**Comment by elextr** [comment]
Its understandable why the results are different.

Because `zip()` is lazy, it hasn't iterated its sub-iterators when it is reversed, which causes it to reverse the sub-iterators, then when collected the second sub-iterator will start at 4.

**Comment by Moelf** [comment]
I honestly don't know what to do with this. An iterator may only be defined to have the forward order, for example, when its length is undetermined.

So in general we can't reverse count `N` and just take them. What we can do is to throw an error when:
- all iterators has `length()`
- lengths are not the same

**Comment by elextr** [comment]
> What we can do is to throw an error when:

Which operation are you proposing this for?  

If `zip()`, it is explicitly defined to work for unequal iterators, even a mix of finite and infinite ones, and would be a loss of capability if it required equal length iterators.

**Comment by Moelf** [comment]
reverse(::Zip)

**Comment by elextr** [comment]
> reverse(::Zip)

Ahh, ok, now makes sense.
