### ISSUE TITLE
memory usage for fetch

### ISSUE THREAD

**Issue by hisq** [JuliaLang/julia#4508]
This is a comment about fetch() for large arrays. Memory measurements are simplified for the discussion. (Hopefully the simplifications are not misleading.)

```
W = first(addprocs(1))
# P0

rr = remotecall(W,rand,10^8)
A = fetch(rr)
# P1: +3200 MByte relative to P0

remotecall(W,gc)
# P2: +2400 MByte relative to P0

gc()
# P3: +2400 MByte relative to P0
```

Here sizeof(A) is 800 MByte. At P1, there are four copies of the array. Of these four, only two are useful.

I think the four copies at P1 are

C1: on W, the obj that rr refers to
C2: on W, the .data of an IOBuffer, namely Base.worker_from_id(1).sendbuf
C3: on 1, the .data of an IOBuffer, namely .buffer of some TcpSocket
C4: on 1, the obj that A refers to

Copies C1 and C4 are the useful ones. Copy C2 is dereferenced when the data is transmitted, see enq_send_req() in multi.jl and takebuf_array() in iobuffer.jl, which accounts for the drop between P1 and P2. [*]

On the receiver side, C3 seems to not be dereferenced, possibly forever if there is no traffic. Hence no drop between P2 and P3. Question: Could one modify read(from::IOBuffer, p::Ptr, nb::Int) in iobuffer.jl by adding something like:

```
if from.writable && !from.seekable
  compact(from) # actually, apply heuristics to see if this is worth doing
end
```

This would go...

```
function read(from::IOBuffer, p::Ptr, nb::Int)
    if !from.readable error("read failed") end
    if nb > nb_available(from)
        throw(EOFError())
    end
    ccall(:memcpy, Ptr{Void}, (Ptr{Void}, Ptr{Void}, Uint), p, pointer(from.data,from.ptr), nb)
    from.ptr += nb
    ####
    #### ...here
    ####
    p
end
```

This modification seems to work in this particular case, but I don't know if it is valid in general.

More generally, should one consider other ways to reduce memory usage, say by transmitting smaller chunks of data?

Note that for remotecall_fetch, the ratio between useless and useful memory is even bigger. In this case, since there is no remote ref, only one copy of the array is useful. Yet also in this case, there may be four simultaneous copies in memory.

[*] Memory is not freed automatically at P1, because the two gc's do not talk to each other, I think. That could be a problem in practice, if one of the procs goes idle, because the gc will then not be triggered. In such a case, the user may have to call gc() manually. I will probably have a separate question about that.

**Comment by vtjnash** [comment]
Addressed by https://github.com/JuliaLang/julia/pull/10073, IIUC (and probably additionally improved by others subsequently too)
