### ISSUE TITLE
`methods` with type restriction documentation

### ISSUE THREAD

**Issue by projekter** [JuliaLang/julia#45105]
The documentation for `methods` says that "if [the second argument] `types` is specified, return an array of methods whose types match." I did not realize that this explanation is actually not as clear as it sounds until I encountered some behavior that I found strange and did some experiments. I would suggest that the meaning of "match" is expanded, as there are multiple ways to explain this:
- First attempt. Return only the (single) method that has exactly the same type signature - no subtype checks are performed, possibly return empty array. The most narrow definition of "match".
    ```Julia
    > function match1(::Integer) end;
    > methods(match1, (Int,))
    # 1 method for generic function match1:
    * match1(::Integer) in Main at In[1]:1
    ```
    Apparently, this is not meant, as `Int != Integer`, but `Int <: Integer`.
- Second attempt. Return all methods which, when looked at in isolation, would be callable using the argument types (though there might be more specific ones which could be called instead). This interpretation is supported by the documentation for `Base.invoke`, which contains the sentence "This method allows invoking a method other than the most specific matching method" and hence implies that there are other "matching methods" than the "most specific" one.
    ```Julia
    > function match2(::Integer) end;
    > function match2(::Int) end;
    > methods(match2, (Int,))
    # 1 method for generic function match2:
    * match2(::Int64) in Main at In[2]:2
    ```
    So this also does not seem to be the case, the first method is not listed although it matches according to this definition.
- Third attempt. Return only the most specific method that would be called with these types, or an empty vector if there is no one. This is already supported by the first two code examples. What could make this different from `which` is that in the case of ambiguities, we could get all possible "matching" methods.
    ```Julia
    > abstract type type3A end;
    > abstract type type3B <: type3A end;
    > abstract type type3C <: type3A end;
    > function match3(::type3B) end;
    > function match3(::type3C) end;
    > methods(match3, (type3A,))
    # 2 methods for generic function match3:
    * match3(::type3B) in Main at In[3]:4
    * match3(::type3C) in Main at In[3]:5
    ```
    And indeed, in this case `which` throws an error: "no unique matching method found for the specified argument types". So this seems to be the correct interpretation - which can lead to the (surprising) fact that adding a more specific method can reduce the number of methods listed, and that deleting a more specific method can in fact increase the number of methods (the last case what brought this to my attention).

I checked the implementation using
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
```

**Comment by chunjiw** [comment]
Personally I find these quite reasonable :)

**Comment by vtjnash** [comment]
Details discussed at https://live.juliacon.org/talk/RQZBFB xD

**Comment by ulysses4ever** [comment]
@vtjnash is there a commit that addresses it, besides the juliacon talk? The video shows 8cc544543 but its contents I see on the slide are different from what I see in the repo.

**Comment by vtjnash** [comment]
no, only in video form
