### ISSUE TITLE
An error showing error of REPL

### ISSUE THREAD

**Issue by GoldenSnitchD** [JuliaLang/julia#45113]
After opening REPL, I try
```jldoctest
julia> import Base.:(==)

julia> ==(a, b) = a + b
Error showing value of type typeof(==):

SYSTEM (REPL): showing an error caused an error

SYSTEM (REPL): caught exception of type MethodError while trying to handle a nested exception; giving up

julia> 
```
Then I found that the REPL is broken and I can't type code normally unless I press Enter key without inputting anything.
Even Ctrl-C can't solve the problem.

**Comment by KristofferC** [comment]
You basically killed the `==`l function so it isn't so weird that Julia is corrupted after that.
