### ISSUE TITLE
incorrect paths in macOS stacktraces with references to standard libraries

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/julia#45112]
I was almost positive that this got fixed but I got this warning. I tried finding the original but can't seem to
```julia

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/sabae/src/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl:661

julia> versioninfo()
Julia Version 1.8.0-beta1
Commit 7b711ce699 (2022-02-23 15:09 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = code
```

on 1.7
```julia 
julia> Pkg.installed();
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/administrator/src/julia/usr/share/julia/stdlib/v1.7/Pkg/src/Pkg.jl:595

julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_NUM_THREADS = 8
```
Neither `/Users/sabae/src/julia/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl` or `/Users/administrator/src/julia/usr/share/julia/stdlib/v1.7/Pkg/src/Pkg.jl` is real. Makes it a little annoying since you can't click to open it in vscode.

**Comment by KristofferC** [comment]
```
julia> Pkg.installed()
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl:661

julia> Base.fixup_stdlib_path("/Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl")
"/Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Pkg.jl"
```

So a call to `fixup_stdlib_path` could be added to `filepath` at https://github.com/JuliaLang/julia/blob/ce5909ceca8e0df00407ad39bd0e2763890b185d/base/logging.jl#L687.

**Comment by affans** [comment]
I am trying to work on this as my first PR, but the fix doesn't seem to be working. I change the source code as suggested by @KristofferC and to test it, I do 
```
using Base.CoreLogging 
using Pkg 
@eval CoreLogging [copy paste entire function here with updated code] 
Pkg.installed() # shows the warning but dosn't reflect the change I made.
```
Is there a more easier to test these small code changes? Perhaps with Revise?

**Comment by KristofferC** [comment]
> I even tried @eval Base.CoreLogging [function pasted] but did not work.

I think that is because that the function here is what a macro will expand to and existing function will already have had their logging macros expanded.

Looking back at the suggestion here, this change will only fix it for the default terminal logger. It would probably be better to fix it at an earlier point than where it gets printed.

**Comment by fredrikekre** [comment]
Probably here: https://github.com/JuliaLang/julia/blob/b9d82808b8a3bd383b01d85ba3038b56e18c74e0/base/logging.jl#L251 or here: https://github.com/JuliaLang/julia/blob/b9d82808b8a3bd383b01d85ba3038b56e18c74e0/base/logging.jl#L382
