### ISSUE TITLE
A precompiled closed channel isopen.

### ISSUE THREAD

**Issue by peteristhegreat** [JuliaLang/julia#45170]
A channel initialized as `closed` misbehaves if initialized in open code.

Create a quick environment for seeing the issue:
```
]generate ChannelTest
open("ChannelTest/src/ChannelTest.jl", "w") do f
       write(f, """
           module ChannelTest
    
           global ch1 = Channel(x->nothing)
    
           function __init__()
               global ch2 = Channel(x->nothing)
           end

           end # module
       """)
end
]activate ChannelTest
```

Here is the demonstration of the behavior
```
julia> using ChannelTest
[ Info: Precompiling ChannelTest [faef8667-0211-41c9-aee8-e4c24749ae0b]

julia> isopen(ChannelTest.ch1)
true                                              # This is the one initialized in open code in the module

julia> isopen(ChannelTest.ch2)
false                                             # This is the one initialized in the __init__ function
```

(We have been moving away from creating anything besides functions and references in open code.)

Can you please:
 - Either fix the behavior for this specific kind of use of Channels, or 
 - Add big warning to the user about how it won't behave the way they expect.

**Comment by JeffBezanson** [comment]
This is tricky. We spawn a second task to handle closing the channel, and that task doesn't get a chance to run in the precompiling process. Then the process exits and the scheduler queue is dropped. There could easily be other variations of this if you spawn tasks at load time. I don't think we can do anything about it in general, but we could go back to closing the channel immediately on task exit instead of spawning another task to do that.

**Comment by JeffBezanson** [comment]
Jameson and I think a good fix for this would be to provide a way (e.g. a command line argument) to wait until there are no runnable tasks at process exit. Precompiling and image building would enable that flag. It could even be the default, but might break some use cases.

**Comment by peteristhegreat** [comment]
Thanks @JeffBezanson for the replies.

For now we just initialize the channel at runtime.  But there ought to be some kind of warning for delayed channel close in open code.

I don't know the answer or what would be best for our use case, since we have opted to avoid the situation if possible.

Some other possible ideas from what you described...

a default exit task handler (during the precompiling process)
 - prints a warning and line of code that caused it, and continues with the drop of the task
 
an alternative exit task handler (during the precompiling process)
 - waits until a timeout or all tasks have exited, if a timeout exit occurs, print the warning

Or maybe just tuning a timeout value may be enough? `--precompile-task-exit-timeout` 
 - `-1` never timeout, let the tasks complete
 - `0` exit tasks immediately
 - `XX` number of seconds to wait before exiting still open tasks
 
If a warning about an exited task ought to have a silent mode, then that could be another argument.
 - `--precompile-task-exit-warning=true`
 - `--precompile-task-exit-warning=false`
