### ISSUE TITLE
filter should be type stable

### ISSUE THREAD

**Issue by cmcaine** [JuliaLang/julia#45197]
```jl
julia> filter(_ -> true, [[1], [2]])
2-element Vector{Vector{Int64}}:
 [1]
 [2]

julia> filter(_ -> false, [[1], [2]])
Vector{Int64}[]

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, ivybridge)

```

The return type of `filter(f, x::Vector{T})` should be `Vector{T}`, right?

I'd say the signature should be `filter(f, x::T)::T`, but I'm sure there are probably some weird types where that's a bad idea.

**Comment by simeonschaub** [comment]
> The return type of `filter(f, x::Vector{T})` should be `Vector{T}`, right?

That's exactly what you get, no?

**Comment by JeffBezanson** [comment]
In `T[]`, `T` is the element type, not the type of the overall vector.

**Comment by DilumAluthge** [comment]
🤦
