### ISSUE TITLE
Avoid printing values of keyword arguments while displaying a MethodError

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#45219]
Related to [this discourse thread](https://discourse.julialang.org/t/why-are-kwargs-printed-in-full-in-a-methoderror/80592)

MWE:

```julia
julia> f(a::Int; b = nothing) = a
f (generic function with 1 method)

julia> f(2.0, b = zeros(10))
ERROR: MethodError: no method matching f(::Float64; b=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
Closest candidates are:
  f(::Int64; b) at REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```

The value of the keyword argument has nothing to do with the error, and only adds visual clutter. In some cases, displaying the keyword arguments might take up considerable screen space and be time-consuming.

In case there is a mismatch in the type of the keyword argument, the error thrown is a `TypeError`, which doesn't show the value of the argument. Arguably, this is the case that might benefit from the values being displayed.

```julia
julia> h(a::Int; b::Float64 = 0.0) = a
h (generic function with 1 method)

julia> h(2, b = 4)
ERROR: TypeError: in keyword argument b, expected Float64, got a value of type Int64
Stacktrace:
 [1] top-level scope
   @ REPL[9]:1
```

**Comment by JeffBezanson** [comment]
Agree; it doesn't make sense to show the values for keyword arguments and not positional arguments.

**Comment by skleinbo** [comment]
FWIW, https://github.com/JuliaLang/julia/pull/16669 introduced the behavior.

https://github.com/JuliaLang/julia/blob/59d1d54d1cfdcc1ef2057baa97aeea62c8bc027f/base/errorshow.jl#L274-L276

**Comment by KristofferC** [comment]
The behavior is explicitly discussed here https://github.com/JuliaLang/julia/pull/16669#issuecomment-222812733. Possible fix https://github.com/JuliaLang/julia/pull/45255.
