### ISSUE TITLE
Multithreading crashes Julia

### ISSUE THREAD

**Issue by styrix560** [JuliaLang/julia#45226]
A bug occured when testing multithreading with the following code 
`function fun(n)
    primes = []
    Threads.@threads for i in 2:n
            push!(primes, i)
    end
    return primes
end
fun(10^6)`
error message: RtlGetCurrentServiceSessionId at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFreeHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
free at C:\WINDOWS\System32\msvcrt.dll (unknown line)
aligned_offset_realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
jl_realloc_aligned at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:221 [inlined]
gc_managed_realloc_ at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3540
jl_gc_managed_realloc at /cygdrive/c/buildbot/worker/package_win64/build/src\gc.c:3557
array_resize_buffer at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:681
jl_array_grow_at_end at /cygdrive/c/buildbot/worker/package_win64/build/src\array.c:904
_growend! at .\array.jl:948 [inlined]
push! at .\array.jl:1001 [inlined]
macro expansion at C:\Users\Guenn\Desktop\test\multithreading_test.jl:17 [inlined]
#3#threadsfor_fun at .\threadingconstructs.jl:85
#3#threadsfor_fun at .\threadingconstructs.jl:52
unknown function (ip: 00000000602b1ec3)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:877
Allocations: 2721 (Pool: 2713; Big: 8); GC: 0

Interestingly enough, this issue only occurs when calling fun with 10^6, not with 10^5. If f(10^6) is called, Julia crashes without any error message. If Julia is started and the program is run again, the above error message gets produced. Here is the code i used to start the file
`julia -t 2
include("path/to/file.jl")`

and my version info:
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8

**Comment by giordano** [comment]
Your function isn't thread-safe: your pushing to the same array from all threads at the same time
