### ISSUE TITLE
`jl_options` is not exported by the LTS version

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaLang/julia#45298]
I think solving this issue only requires adding  `XX(jl_options, jl_options_t)` to `jl_exported_data.inc`. I'd be happy to provide a PR with that change (and a fix for #43340), but I don't know how to provide a PR for the LTS version.

**Comment by JeffBezanson** [comment]
That can be done by backporting #42416. Make a new branch with release-1.6 as its start point, then `cherry-pick -x` that commit onto it, then open a PR with release-1.6 as the base branch.

**Comment by inkydragon** [comment]
Closed by #45308
