### ISSUE TITLE
Stackframe paths to Stdlib files incorrect

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#45294]
Raising this comment on #33065 to a full issue because I just encountered it and realized it was leading to a weird bit of logic in my AbbreviatedStackTraces.jl package.

Base file paths all start with `./` or `.\`, but Stdlib paths all point to an absolute path that was present on the build machine. For consistency, if `base` is considered the working directory for stack traces, this could be `../stdlib/v1.8/`.

> In version 1.3.0 on Win_64 platform, I get this:
> ```
> ERROR: MethodError: no method matching randstring(::Int64, ::String)
> Closest candidates are:
>   randstring(::AbstractRNG, ::Any) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Random\src\misc.jl:74
> ```
> It must be a hard-coded path since this machine does not even contain a D drive. 
> The actual path is `AppData\Local\`

_Originally posted by @K-Kent in https://github.com/JuliaLang/julia/issues/33065#issuecomment-568340229_

**Comment by BioTurboNick** [comment]
I can try to address it myself, but would need input on the proper path to use instead.

**Comment by KristofferC** [comment]
Call `Base.fixup_stdlib_path` on the path before showing it.

**Comment by BioTurboNick** [comment]
Oh, thanks! I guess it was fixed in Base but I was overriding it.
