### ISSUE TITLE
InteractiveUtils crashed on CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#45310]
https://buildkite.com/julialang/julia-master/builds/11964#6454de35-bceb-4fdb-b92c-6f6acd92e377

An rr trace is available.

**Comment by DilumAluthge** [comment]
@Keno Is that the right link? That link doesn't have an rr trace attached, because rr failed to cleanup within 1 hour, so we SIGKILLed it.

**Comment by Keno** [comment]
> @Keno Is that the right link? That link doesn't have an rr trace attached, because rr failed to cleanup within 1 hour, so we SIGKILLed it.

Oh, you are correct. My bad. Do we know what that happens?

**Comment by Keno** [comment]
Can we see if we can reproduce this locally. Basically throw `unsafe_load(Ptr{Int}(1))` in a few places in the tests and see if we can get this to happen? We may need to more aggressively send SIGTERM to the entire process tree rather than just the toplevel rr.

**Comment by vtjnash** [comment]
This was introduced by https://github.com/JuliaLang/julia/pull/44548, which was merged earlier that week, and changed the Julia definition of struct without changing the C representation. Sometimes that means we do an OOB value and use that to do an OOB read on an array.
