### ISSUE TITLE
'search docs' failure in Julia 1.7.2 documentation manual 

### ISSUE THREAD

**Issue by walra356** [JuliaLang/julia#45327]
For fresh download of manual from https://docs.julialang.org/en/v1/manual/getting-started/ the search function hangs on the message
`Loading search...`

**Comment by fredrikekre** [comment]
What do you mean with a download of the manual?

**Comment by walra356** [comment]
I get the manual at  https://docs.julialang.org/en/v1/manual/getting-started/ (or at the Julia download page). Typing a search command in the search box, for instance I type "array". The search starts with the message `Loading search' (as is usual) but then the search stalls (i.e., it does not give any output). This is the case for any search command. Does the search command work for you?

**Comment by walra356** [comment]
After a reboot all is OK. Sorry for bothering you.
