### ISSUE TITLE
Inconsistent behavior of `Base.floatrange`

### ISSUE THREAD

**Issue by metab0t** [JuliaLang/julia#45336]
When digging into a bug in `StatsBase.fit`:
- https://github.com/JuliaStats/StatsBase.jl/issues/667
- https://github.com/JuliaStats/StatsBase.jl/issues/616

I find that the core issue happens in usage of [`Base.floatrange`]( https://github.com/JuliaStats/StatsBase.jl/blob/d9cb8f8d6198e5813562e1efffe74fe3614d047e/src/hist.jl#L99)

I try the following code:
```julia-repl
julia> Base.floatrange(1.05 , 1.0 , 2, 1.0)
2.05:2.0:4.05

julia> Base.floatrange(1.0  , 1.0 , 2, 1.0)
1.0:1.0:2.0
```

In `twiceprecision.jl`, `ref` in two `steprangelen_hp` definitions has different meanings.

- In the [integer case](https://github.com/JuliaLang/julia/blob/45ab66452ef08cfcb62aa091037ce0a78367a762/base/twiceprecision.jl#L343), it means `TwicePrecision{Float64}(ref)`
- In the [float case](https://github.com/JuliaLang/julia/blob/45ab66452ef08cfcb62aa091037ce0a78367a762/base/twiceprecision.jl#L361), it means `TwicePrecision{Float64}(ref...)` (it should align with integer case)

However, `TwicePrecision{Float64}(1.0, 1.0)` and `TwicePrecision{Float64}((1.0, 1.0))`are totally different.

Therefore, two `floatrange` definitions return different results
- https://github.com/JuliaLang/julia/blob/45ab66452ef08cfcb62aa091037ce0a78367a762/base/twiceprecision.jl#L381 (correct)
- https://github.com/JuliaLang/julia/blob/45ab66452ef08cfcb62aa091037ce0a78367a762/base/twiceprecision.jl#L395 (if it hits [steprangelen_hp](https://github.com/JuliaLang/julia/blob/45ab66452ef08cfcb62aa091037ce0a78367a762/base/twiceprecision.jl#L408) of the float case, result is wrong)

Code examples:
```julia-repl
julia> Base.floatrange(Float64, 11, 10, 2, 1)
11.0:10.0:21.0

julia> Base.floatrange(11.0, 10.0, 2, 1.0) # fallback to use floatrange(Float64, ::Integer, ::Integer, ::Integer, ::Integer)
11.0:10.0:21.0

julia> Base.floatrange(11.1, 10.0, 2, 1.0) # use float case of steprangelen_hp
12.1:11.0:23.1
```

Version info:
```julia-repl
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 5800H with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
Environment:
  JULIA_NUM_THREADS = auto
  JULIA_PKG_USE_CLI_GIT = true
```

**Comment by oscardssmith** [comment]
wow. That is awful.

**Comment by N5N3** [comment]
Do we have a MWE to reproduce this bug with public API? (`Base.floatrange` is not documented)

**Comment by metab0t** [comment]
https://github.com/search?l=Julia&p=1&q=Base.floatrange&type=Code

After code search on GitHub, we can almost conclude that the only widely user of `Base.floatrange` is `StatsBase/src/hist.jl`.
So maybe we should remove it and fix `StatsBase`?

**Comment by metab0t** [comment]
Maybe we can remove it because StatsBase.jl does not depend on it anymore.

**Comment by Moelf** [comment]
@metab0t feel free to make a PR implementing it and we can PkgEval it

**Comment by metab0t** [comment]
@Moelf I have opened a PR to remove the inconsistent instance of `Base.floatrange`.
