### ISSUE TITLE
Pluto seg fault for plots MacOS

### ISSUE THREAD

**Issue by xaviergonzalez** [JuliaLang/julia#45334]
Hi I wanted to make you aware of this known bug: https://discourse.julialang.org/t/pluto-process-exited-due-to-segmentation-fault-on-macos/74558

Basically, plotting using Julia (v 1.7.2) in Pluto with a macOS Monterey on M1 Chip is a nightmare, there was does not seem to be any rhyme or reason as to when a plot will appear and when there will be a seg fault. This error basically makes Julia+Pluto unusable on M1 chip.

**Comment by giordano** [comment]
Julia v1.7 on M1 is known to have many problems, including frequent segmentation faults: #41440. However these have been fixed already in `master` and will be available in v1.8. I'm going to close this ticket, but feel free to reopen it if you have problems with v1.8 or later versions.
