### ISSUE TITLE
Julia --sysimage flag does not play nicely with tilde expansions in shells.

### ISSUE THREAD

**Issue by hewhocannotbetamed** [JuliaLang/julia#45360]
[versioninfo()](https://pasteboard.co/hL6UVFmhxJmE.png)

[Picture *  FPS * time = more then a thousand words. ](https://asciinema.org/a/5wu0c9ilCOQObt9lAOn9GGlAG)

[Helpful strace excerpt (strace -i julia --sysimage='~/.local/lib/sharedlibs/julia/OMR-sysimage.so')](https://pasteboard.co/NCjxX3Hzw1Pr.png)
Yes to it being repeatable across **Fish**, **Bash**, and **Zsh**. It is not an issue at that level, trust.

I'm not familiar yet with the codebase, as I came across this literally trying to set up a reasonable environment to work with. I surmise the issue to be related to how julia proc gets passed arguments from the shell, as no actual expansion is apparently occuring. Julia repl proggie simply doesn't handle the tilde expansion char, and therefore interprets the entire thing as a relative path, hence the prepending.

Resolution? Probably just handle this strange edge case. Monkey patch prob.

Real solution? Let's all collaborate to figure out how to eliminate the need for using PackageCompiler.jl to facilitate a reasonable, incremental workflow. "Time to plot" is a new, and very annoying concept.

**Comment by rfourquet** [comment]
The two first links in the OP lead to "image not found". Also, while a picture can explain a lot, it doesn't always replace a verbal formulation of the problem, which we prefer to have in julia issues. Closing for now, as I have no idea what this is about. Please re-open if needed, but then insert as much information as possible within this issue itself without forcing readers to click on links.
