### ISSUE TITLE
Source build: llvmunwind should be compiled after llvm

### ISSUE THREAD

**Issue by fxcoudert** [JuliaLang/julia#45379]
This was first reported in a comment in this PR: https://github.com/JuliaLang/julia/pull/45189#issuecomment-1117868670
I'm creating its own issue, now that the PR is merged.

I'm building from master source on macOS (`make USE_BINARYBUILDER=0 VERBOSE=1 CFLAGS='-Wno-implicit-function-declaration'`; CFLAGS is there to avoid this other bug: https://github.com/JuliaLang/julia/issues/45200)

I get:

```
mkdir -p scratch/llvmunwind-12.0.1/
cd scratch/llvmunwind-12.0.1/ && \
	cmake /private/tmp/julia/deps/srccache/llvmunwind-12.0.1/ -DCMAKE_INSTALL_PREFIX:PATH=/private/tmp/julia/usr -DCMAKE_PREFIX_PATH=/private/tmp/julia/usr -DCMAKE_INSTALL_LIBDIR=/private/tmp/julia/usr/lib -DCMAKE_INSTALL_BINDIR=/private/tmp/julia/usr/bin -DLIB_INSTALL_DIR=/private/tmp/julia/usr/lib -DCMAKE_MACOSX_RPATH=1 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER="$(which clang)" -DCMAKE_C_COMPILER_ARG1="-mmacosx-version-min=11.0" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_COMPILER_ARG1="-mmacosx-version-min=11.0" -DCMAKE_LINKER="$(which ld)" -DCMAKE_AR="$(which ar)" -DCMAKE_RANLIB="$(which ranlib)" -DCMAKE_BUILD_TYPE=MinSizeRel -DLIBUNWIND_ENABLE_PEDANTIC=OFF -DLLVM_CONFIG_PATH=/private/tmp/julia/usr/tools/llvm-config
Re-run cmake no build system arguments
-- Found LLVM_CONFIG_PATH as /private/tmp/julia/usr/tools/llvm-config
-- /private/tmp/julia/usr/tools/llvm-config --includedir --prefix --src-root
CMake Error at CMakeLists.txt:39 (message):
  llvm-config failed with status No such file or directory


-- Configuring incomplete, errors occurred!
See also "/tmp/julia/deps/scratch/llvmunwind-12.0.1/CMakeFiles/CMakeOutput.log".
See also "/tmp/julia/deps/scratch/llvmunwind-12.0.1/CMakeFiles/CMakeError.log".
make[1]: *** [scratch/llvmunwind-12.0.1/build-configured] Error 1
```

because it's trying to build llvmunwind before it's built llvm, and therefore `llvm-config` cannot be found. There needs to be something in the makefiles that enforces that, and there isn't.

**Comment by fxcoudert** [comment]
Solution I've tried: In `deps/unwind.mk` I can add to the target `$(BUILDDIR)/llvmunwind-$(LLVMUNWIND_VER)/build-configured` a dependency on `$(LLVM_BUILDDIR_withtype)/build-compiled`. I hoped this dependency would allow to install llvm before llvmunwind is configured:

```
ifeq ($(USE_SYSTEM_LLVM),0)
 $(BUILDDIR)/llvmunwind-$(LLVMUNWIND_VER)/build-configured: | $(LLVM_BUILDDIR_withtype)/build-compiled
 endif
```

but it does not work reliably: it builds llvmunwind after llvm is **built**, but not necessarily **installed** (so `llvm-config` is not present). Can someone suggest a way to add the dependency to installed llvm? @giordano I cannot figure it out.

**Comment by vtjnash** [comment]
It should add a dependency on the manifest/llvm file

**Comment by giordano** [comment]
yes, like this: https://github.com/JuliaLang/julia/blob/0f2ed77dca88785c9ae0fb1cf1a77593d1527c18/deps/curl.mk#L3-L5

**Comment by fxcoudert** [comment]
Tested, and it works locally. PR opened at https://github.com/JuliaLang/julia/pull/45380/files
