### ISSUE TITLE
Question about A' when A is a complex matrix?

### ISSUE THREAD

**Issue by zdlspace0528** [JuliaLang/julia#45372]
Dear all,
`julia> A = [1 + 0.2im, 2 + 0.6im]
2-element Vector{ComplexF64}:
 1.0 + 0.2im
 2.0 + 0.6im

julia> A'
1×2 adjoint(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0-0.2im  2.0-0.6im

julia> Transpose(A)
1×2 transpose(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0+0.2im  2.0+0.6im

julia> A' == Transpose(A)
false`

What's wrong with this? Why A' != A?

**Comment by oscardssmith** [comment]
`A'` is the adjoint. Also, please ask questions on discourse, stackoverflow, or slack. Github issues are only for bugs.
