### ISSUE TITLE
question about A'?

### ISSUE THREAD

**Issue by zdlspace0528** [JuliaLang/julia#45373]
Dear all,
`julia> A = [1 + 0.2im, 2 + 0.6im]
2-element Vector{ComplexF64}:
 1.0 + 0.2im
 2.0 + 0.6im

julia> A'
1×2 adjoint(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0-0.2im  2.0-0.6im

julia> Transpose(A)
1×2 transpose(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0+0.2im  2.0+0.6im

julia> A' == Transpose(A)
false`

What's wrong with this? Why A' != A?

**Comment by zdlspace0528** [comment]
Dear all,
`julia> A = [1 + 0.2im, 2 + 0.6im]
2-element Vector{ComplexF64}:
 1.0 + 0.2im
 2.0 + 0.6im

julia> A'
1×2 adjoint(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0-0.2im  2.0-0.6im

julia> Transpose(A)
1×2 transpose(::Vector{ComplexF64}) with eltype ComplexF64:
 1.0+0.2im  2.0+0.6im

julia> A' == Transpose(A)
false`

What's wrong with this? Why A' != A?
`

**Comment by zdlspace0528** [comment]
`julia> A = [1 + 0.2im, 2 + 0.6im]
2-element Vector{ComplexF64}:
1.0 + 0.2im
2.0 + 0.6im`

**Comment by zdlspace0528** [comment]
```
julia> A = [1 + 0.2im, 2 + 0.6im]
2-element Vector{ComplexF64}:
1.0 + 0.2im
2.0 + 0.6im
```

**Comment by oscardssmith** [comment]
dup of https://github.com/JuliaLang/julia/issues/45372. Don't spam.
