### ISSUE TITLE
String search operations needlessly allocate

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#45393]
For example, `findfirst("abc", "ab")` eventually ends up calling:

```julia
function _searchindex(s::String, t::String, i::Integer)
    # Check for fast case of a single byte
    lastindex(t) == 1 && return something(findnext(isequal(t[1]), s, i), 0)
    _searchindex(unsafe_wrap(Vector{UInt8},s), unsafe_wrap(Vector{UInt8},t), i)
end
```
The `unsafe_wrap` allocates, which slows down string search.
However, when I tried replacing the `unsafe_wrap(Vector{UInt8}, ::String)` with `codeunits(::String)`, Julia failed to bootstrap.

There are a number of similar `unsafe_wrap` calls in the same file.

It would be nice to remove this allocation, somehow.

**Comment by Moelf** [comment]
I would have thought the easier thing to do is to replace
```julia
_searchindex(unsafe_wrap(Vector{UInt8},s), unsafe_wrap(Vector{UInt8},t), i)
```
with
```julia
_searchindex(codeunits(s), codeunits(t), i)
```

but this didn't remove allocation

**Comment by bicycle1885** [comment]
Actually, I have noticed and solved this in #40120 by rewriting the whole code.

**Comment by stevengj** [comment]
Since #40120 is breaking and is marked as "Julia 2.0", we need another solution here.

**Comment by jakobnissen** [comment]
That would be a good idea, but Julia fails to build when I try to do that.

**Comment by KristofferC** [comment]
I tried it and it worked fine and it seemed to remove the allocation... So what error do you get?

**Comment by jakobnissen** [comment]
It build for me just fine on master (0c3b950) with that diff. Don't know what happened last time. Let me make a PR!
