### ISSUE TITLE
Missing Download Julia v1.7.3 Apple Silicon

### ISSUE THREAD

**Issue by conradwt** [JuliaLang/julia#45457]
**Issue**

The download page appears to be missing Julia v1.7.3 for Apple Silicon.

**Recommendation**

I recommend creating a unified binary executable by using the following reference documentation:

https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by gbaraldi** [comment]
It was probably removed because 1.7 on apple silicon was very broken.

**Comment by Keno** [comment]
Yes, there will be no further releases for Apple Silicon in the 1.7 series. The 1.7.2 release was experimental and quite broken on Apple Silicon. 1.8 will have stable Apple Silicon support.

**Comment by conradwt** [comment]
@Keno Thanks for the information and I appreciate it.
