### ISSUE TITLE
Copy from clipboard to REPL auto add bracket.

### ISSUE THREAD

**Issue by hungpham3112** [JuliaLang/julia#45453]
![image](https://user-images.githubusercontent.com/75968004/170242197-5edf826c-9c48-46a0-9250-0fcd5e32ace9.png)

Tried to copy this line to julia REPL

```
G = ([x, sqrt(x), x^2] for x in 1:100 if iseven(x))
```
and see new `]` and `)` at the end of line.
![image](https://user-images.githubusercontent.com/75968004/170242597-9c19a846-2f0e-4dfe-859f-531255bb6ece.png)

I'm using REPL with OhMyREPL.jl.

**Comment by KristofferC** [comment]
Related to https://github.com/KristofferC/OhMyREPL.jl/issues/166. This is not a julia issue but an OMR issue.
