### ISSUE TITLE
doc: documentations for `getglobal`/`setglobal!`

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#45480]
Those new builtins are added in #44231 and will be exported at v1.9,
but currently it seems like we don't have documentations for them.

/cc @simeonschaub

**Comment by wolthom** [comment]
@aviatesk Is this issue still relevant? If so, are there tests I should refer to regarding the functionality / edge cases?

**Comment by theWiseAman** [comment]
Okay I would like to author the documentation for this. Give me some time to understand the codebase as I am new to open source.
