### ISSUE TITLE
[BUG] incorrect matrix type casting in concatenation

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaLang/julia#45498]
This is a bug in nightly, which breaks multiple tests.

```julia
julia> using SparseArrays

julia> ds = rand(ComplexF64, 4, 4);

julia> sp = sprand(ComplexF64, 4, 4, 0.5);

julia> vs = [sp, ds];

julia> typeof.(vs)
2-element Vector{DataType}:
 Matrix{ComplexF64} (alias for Array{Complex{Float64}, 2})
 Matrix{ComplexF64} (alias for Array{Complex{Float64}, 2})
```

In Julia1.7, it does not cast a sparse matrix to a dense matrix.

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/julia/pull/44096 and in particular discussion in https://github.com/JuliaLang/julia/pull/44096#discussion_r817634348. See also https://github.com/JuliaLang/julia/pull/43127, which is mentioned in NEWS for release 1.8. Maybe want to use the `sparse_cat` functions.

**Comment by fredrikekre** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/44821.
