### ISSUE TITLE
`@nospecialize` has no effect on all-underscore identifiers

### ISSUE THREAD

**Issue by vyu** [JuliaLang/julia#45500]
```julia
julia> using MethodAnalysis

julia> f(@nospecialize _) = 0;

julia> g(@nospecialize x) = 0;

julia> f(0);

julia> g(0);

julia> methodinstances(f)
1-element Vector{Core.MethodInstance}:
 MethodInstance for f(::Int64)

julia> methodinstances(g)
1-element Vector{Core.MethodInstance}:
 MethodInstance for g(::Any)

julia> versioninfo()
Julia Version 1.9.0-DEV.672
Commit eb230a55d2 (2022-05-29 00:23 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 8 on 8 virtual cores
```

Also tested on Julia 1.6.6 with the same result. A [couple of packages use this pattern](https://juliahub.com/ui/Search?type=code&q=%40nospecialize%28%20%7C%5C%28%29_%2B%5CW&r=true).

Also, since `@nospecialize(_)` lowers to `Expr(:meta, :nospecialize, :_)`, an ambiguity arises after lowering when it is used in functions with multiple `_` arguments. E.g., `h(@nospecialize(_), _) = 0`. A potential resolution is to always nospecialize `_` (or unused) arguments, as suggested by quinnj in https://github.com/JuliaLang/julia/issues/32727#issuecomment-516195355.

**Comment by aviatesk** [comment]
Dup of 44428.
