### ISSUE TITLE
Yellow color of @code_warntype should not override red color

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#45501]
MWE:
```julia
julia> @code_warntype iterate(Any[])
MethodInstance for iterate(::Vector{Any})
  from iterate(A::Array) in Base at array.jl:835
Arguments
  #self#::Core.Const(iterate)
  A::Vector{Any}
Body::Union{Nothing, Tuple{Any, Int64}}
1 ─      nothing
│   %2 = (#self#)(A, 1)::Union{Nothing, Tuple{Any, Int64}}
└──      return %2
```
Here, the `Union{Nothing, Tuple{Any, Int64}}` is colored yellow because it's a union type with `Nothing`.
Shouldn't the "redness" of the `Any` override the "yellowness", though? Practically speaking, a user uses the colors to figure out if something is well inferred or not. And I would argue that this union is not well inferred and should be red.

**Comment by KristofferC** [comment]
Or only the `Union{Nothing, ` part is yellow while the other element is red.
