### ISSUE TITLE
@code_warntype should display unproblematic unions in yellow, not red

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#45502]
For example:
```julia
julia> struct Foo end

julia> @code_warntype first(Union{Foo, Int}[1])
MethodInstance for first(::Vector{Union{Foo, Int64}})
  from first(a::AbstractArray) in Base at abstractarray.jl:398
Arguments
  #self#::Core.Const(first)
  a::Vector{Union{Foo, Int64}}
Body::Union{Foo, Int64}
1 ─ %1 = Base.eachindex(a)::Base.OneTo{Int64}
│   %2 = Base.first(%1)::Core.Const(1)
│   %3 = Base.getindex(a, %2)::Union{Foo, Int64}
└──      return %3
```
Here, the `Union{Foo, Int64}` is colored red, but it makes more sense for it to be colored yellow.

Now, it would be best if the coloring of `@code_warntype` followed the compiler's capabilities such that it only highlighted what was actually problematic from an inference/performance perspective, but I realize that may not be practical because the compiler changes all the time, and also it might not be a good idea to have people rely on the exact behaviour of the compiler.

But I think the current situation could be markedly improved even while staying conservative about the compiler's capabilities. For example, all concrete unions with 2-3 types could be colored yellow.

**Comment by Moelf** [comment]
![image](https://user-images.githubusercontent.com/5306213/170888906-05e50696-5cd5-4904-a885-0a02339a3c4d.png)


something special going on here?

**Comment by KristofferC** [comment]
`Nothing` is special cased in the printer.

**Comment by Moelf** [comment]
other than removing the special case in printer, do we need to be more careful? IIRC there is indeed something special about Nothing and Missing in other parts of Julia (even compiler?)

**Comment by jakobnissen** [comment]
@Moelf see the associated PR made yesterday. As far as I know, there is nothing special about these two types from a compiler perspective. They are special-cased because unions with these types are expected to show up frequently: Unions with `Missing` show up whenever `missing` is being used, and unions with `Nothing` is a common idiom in Julia and shows up in every for-loop.
