### ISSUE TITLE
Broadcasting for nested structs

### ISSUE THREAD

**Issue by Xlin0mu** [JuliaLang/julia#45519]
When I'm dealing with a nested structure, I have to use many circle structure if I wanna traverse more than a layer in a nested structure.
I mean, do we need a new operater like "dot dot"  which's similar to the dot operater, to implement multi-layer
nested structure  traversing?
For example:
"""
a = b = c = h = rand(10, 1)
d = e = f = [a, b, c]
g = [d, e, f]
ar = Array{Any, 1}(undef, 3)
"""
Usually I do this:
"""
for i in 1 : length(g)
    ar[i] = g[i] .* h
end
"""
Could we make a "dot dot" operater working like this:
"""
ar = g ..* h
"""
or some forms look more scientific.
Actually I don't have a nice idea on forming this operater, if you think it's a good idea as well, I believe you can struct a great operater for us.
Sorry for bothering.

**Comment by fredrikekre** [comment]
See https://github.com/JuliaLang/julia/issues/20502
