### ISSUE TITLE
Conversion from Float64 to Float16 is incorrect

### ISSUE THREAD

**Issue by zsoerenm** [JuliaLang/julia#45528]
Today I observed something unusual:
```julia
julia> Float16(4.0)
Float16(0.0)

julia> Float16(4.0f0)
Float16(4.0)

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```
This might be related:
https://github.com/JuliaLang/julia/issues/45433
https://github.com/JuliaLang/julia/issues/44829

**Comment by oscardssmith** [comment]
How did you download Julia?

**Comment by oscardssmith** [comment]
wait, I'm pretty sure this is just a dup of https://github.com/JuliaLang/julia/issues/45433

**Comment by oscardssmith** [comment]
For some reason, most linux distros don't listen to us when we say that they shouldn't link against system LLVM, which leads to a lot of people ending up with broken versions of Julia.

**Comment by zsoerenm** [comment]
I'm sorry, it was not an error from the AUR package.
I had to `LD_PRELOAD=/usr/lib64/libstdc++.so.6 /bin/julia` because of this issue:
https://github.com/JuliaGL/GLFW.jl/issues/198
With this pre load `Float16` returns wrong results.

**Comment by zsoerenm** [comment]
Unfortunately this was not the case.
It looks like it is necessary each time Julias version and System version are out of sync: https://github.com/JuliaGL/GLFW.jl/issues/198#issuecomment-852387301

**Comment by zsoerenm** [comment]
I upgraded to Julia v1.8.0beta3 and the error is gone even with LD_PRELOAD of libstdc++.so.6.
