### ISSUE TITLE
Distributions uses an old version of Rmath

### ISSUE THREAD

**Issue by StatsMan1953** [JuliaLang/julia#45539]
R v-4.1.3 (released 10 March 2022) improved accuracy of distribution quantile functions, but Julia 1.8.0-rc1 continues to use an older version of Rmath.

Example:
  quantile(Beta(0.01,0.1),0.92)
returns 1.0 instead of 0.780301421091985
R at least throws a warning "full precision may not have been achieved in 'qbeta'", but Julia gives no indication that the result is completely wrong.

**Comment by oscardssmith** [comment]
Julia doesn't use any version of Rmath. Do you mean to file this under Distributions?

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaStats/StatsFuns.jl/issues/145
