### ISSUE TITLE
[Feature] Use symbol as a mathematical expression

### ISSUE THREAD

**Issue by hungpham3112** [JuliaLang/julia#45554]
Hi there. Is there any way to use x\^2 as x^2 in function. I mean when I create a function :

![image](https://user-images.githubusercontent.com/75968004/171618345-4bb1f18b-2f5a-44a8-a7a5-13e98c5bc114.png)

and use that, it raised an error.

![image](https://user-images.githubusercontent.com/75968004/171618684-5c94a573-9caf-4acb-a794-db4e4c26323e.png)

But if I change it to `f(x) = x^2 + 2x +1` it can calculate normal. Maybe I'm missing something in here. Sorry if my question is bad.

**Comment by KristofferC** [comment]
No, it gets parsed as a `Symbol`:

```
julia> Meta.parse("x² + x") |> dump
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol +
    2: Symbol x²
    3: Symbol x
```
