### ISSUE TITLE
PDF of 1.8.0 rc1 hasn't got built

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#45579]
This link is a 404: https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.8.0-rc1.pdf

**Comment by ViralBShah** [comment]
Bump - how does one debug this? @DilumAluthge @inkydragon

**Comment by DilumAluthge** [comment]
We build the PDF on a once daily cron job. It looks like it has been passing: https://github.com/JuliaLang/docs.julialang.org/actions/workflows/PDFs.yml

Although that may just be for nightly and not for 1.8.

cc: @mortenpi @fredrikekre @staticfloat

**Comment by ViralBShah** [comment]
Right the 1.9-dev file does get built.
