### ISSUE TITLE
Something is broken with Pkg/Downloads or PkgServer

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#45599]
There are cases where Pkg has problems downloading registries/packages in some CI scenarios I've seen.

For example https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ad7a5d1_vs_c4effda/BaytesMCMC.primary.log

```
   Installed DiffRules ─────────────── v1.11.0
   Installed IRTools ───────────────── v0.4.6
   Installed Bijectors ─────────────── v0.10.2
     Cloning [49dc2e85-a5d0-5ad3-a950-438e2897f1b9] Calculus from https://github.com/JuliaMath/Calculus.jl.git
   Installed Calculus ──────────────── v0.5.1
     Cloning [92d709cd-6900-40b7-9082-c6be49f344b6] IrrationalConstants from https://github.com/JuliaMath/IrrationalConstants.jl.git
   Installed IrrationalConstants ───── v0.1.1
     Cloning [79e6a3ab-5dfb-504d-930d-738a2a938a0e] Adapt from https://github.com/JuliaGPU/Adapt.jl.git
   Installed Adapt ─────────────────── v3.3.3
```

Pkg installed 3 packages using `download` using the pkg server but then fell back to cloning via git.

Another example, a recent CI run: https://buildkite.com/julialang/julia-master/builds/12646#01813d61-880e-4593-b7cb-4ccb3d6fd302

```

Updating the registry | 35s
-- | --
  | ┌ Warning: could not download https://pkg.julialang.org/registries
  | └ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:997
  | Cloning registry from "https://github.com/JuliaRegistries/General.git"
  | Added registry `General` to `/cache/julia-buildkite-plugin/depots/53de1ea5-6dd3-4008-b976-161c9f34b0ad/registries/General`
```

Failure to download registry from Pkg server fell back to git.

Would be good to figure out what the root cause of this is.

**Comment by KristofferC** [comment]
I think this has been fixed now.

**Comment by StefanKarpinski** [comment]
Any idea what it was? Don't like issues that come and go like this.

**Comment by KristofferC** [comment]
There was an infrastructure with the MIT PkgServers. IIRC @staticfloat said that they have been fixed now in some slack channel a while ago.
