### ISSUE TITLE
system image slower to create with 1.8.0-rc1 than with 1.7.3

### ISSUE THREAD

**Issue by mcreel** [JuliaLang/julia#45614]
Precompiling a system image for a project takes approximately 16m30s with 1.8.0-rc1, while with 1.7.3, it takes about 11m. This is on linux 64bit glibc, using the generic binaries.  The times are approximately the same in repeated runs. PackageCompiler is v2.0.6. The list of packages compiled in the image is https://github.com/mcreel/Econometrics/blob/main/Manifest.toml and the precompilation script that can be used to reproduce the issue is https://github.com/mcreel/Econometrics/blob/main/MakeSysimage.jl

For 1.8.0-rc1, versioninfo() gives
```
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc656 (2022-05-27 18:33 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```
For 1.7.3, it gives 
```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
``

**Comment by KristofferC** [comment]
I think julia has also gotten better at finding stuff to compile so it might (partly) be that it just compiles more.

**Comment by oscardssmith** [comment]
Has the sysimage size grown?

**Comment by mcreel** [comment]
With 1.7.3, the image size is 484M, with 1.8.0-rc1, it is 591M, so it seems plausible that more is being compiled.

**Comment by vtjnash** [comment]
That seems like somewhat of a severe regression. That is a really hefty amount of data to impose upon the GC, with seemingly negligible benefit to show for it.

**Comment by ViralBShah** [comment]
Is there something we can do here (in terms of a regression from 1.7.3), or should we close?

**Comment by mcreel** [comment]
With 1.8.2, and running with 4 threads, time is down to 9 min, so closing,
