### ISSUE TITLE
Clarify rules for admonitions in Markdown

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#45622]
Julia's `Markdown` module supports [admonitions](https://docs.julialang.org/en/v1/stdlib/Markdown/#Admonitions) as a syntax extension of markdown.

However, the rules are not really explained. It just gives two examples and expects the reader to infer the rest.

But it's not at all clear what is allowed and what not. E.g.:
1. Must there be an empty line after the line containing `!!!`?
2. Must the text of the admonition intended by exactly 4 spaces? are more/fewer OK? can tabs be used?

It would be nice if these could be clarified.

(Of course in general the same problem affects most of the Markdown.jl documentation, but for the standard things, one can at least reference other existing Markdown guide for details, and then hope Julia is standard compliant; not so here)

**Comment by mgkurtz** [comment]
>     1. Must there be an empty line after the line containing `!!!`?

No. An empty line has no effect on the rendered result.

>     2. Must the text of the admonition intended by exactly 4 spaces? are more/fewer OK? can tabs be used?

Yes, 4 spaces or one tab. (Though a few additional spaces will not hurt.) This is now clarified, see [the current docs](https://docs.julialang.org/en/v1.11-dev/stdlib/Markdown/#Admonitions).
