### ISSUE TITLE
`isassigned` should accept `CartesianIndex` arguments

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#45633]
While `isassigned(::Array, ::Integer..)` works, `isassigned(::Array, ::CartesianIndex)` does not. It would be nice to add that method.

(I am aware of https://github.com/JuliaLang/julia/issues/18843. Although the title of that issue seems promising, the discussion in that issue is about `isdefined` and a misunderstanding what that function should do.)

**Comment by N5N3** [comment]
We have `isassigned(::Array, ::CartesianIndex)` on `master`.
See https://github.com/JuliaLang/julia/pull/43394
