### ISSUE TITLE
Excessive using statements in Sort.jl

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#45654]
[This](https://github.com/JuliaLang/julia/blob/a9e3cc79fc57ec2fded8f622255d6309db494249/base/sort.jl#L8) smells bad:
```julia
import ..@__MODULE__, ..parentmodule
const Base = parentmodule(@__MODULE__)
using .Base.Order
using .Base: copymutable, LinearIndices, length, (:), iterate, elsize,
    eachindex, axes, first, last, similar, zip, OrdinalRange, firstindex, lastindex,
    AbstractVector, @inbounds, AbstractRange, @eval, @inline, Vector, @noinline,
    AbstractMatrix, AbstractUnitRange, isless, identity, eltype, >, <, <=, >=, |, +, -, *, !,
    extrema, sub_with_overflow, add_with_overflow, oneunit, div, getindex, setindex!,
    length, resize!, fill, Missing, require_one_based_indexing, keytype, UnitRange,
    min, max, reinterpret, signed, unsigned, Signed, Unsigned, typemin, xor, Type, BitSigned

using .Base: >>>, !==
```

There are two many symbols to read.
What's special about `>>>` and `!==`?
`length` is listed twice.
Are all these really used? Probably not.
Roughly all but 4 of these 62 symbols are imported automatical by `using Base`

**Comment by N5N3** [comment]
But `Core.Compiler` exports none of them?

**Comment by LilithHafner** [comment]
I don't think so, because when I type `using Core.Compiler` and then try `first` I don't get "WARNING: both Core.Compiler and Base export "first"; uses of it in module Main must be qualified"

**Comment by N5N3** [comment]
On master, I get
```julia
julia> baremodule TT
       using Core.Compiler
       end
Main.TT

julia> TT.first
ERROR: UndefVarError: first not defined
```

**Comment by LilithHafner** [comment]
I think we are in agreement, I edited my reply to try to clarify that.

**Comment by N5N3** [comment]
Opps, my fault.
> But Core.Compiler exports none of them?

What I mean is
```julia
julia> Core.Compiler.Sort.Base
Core.Compiler

julia> Base.Sort.Base
Base
```
And the long list above seems unavoidable? (Of course we can remove `using` which is repetitive or unnecessary )

**Comment by LilithHafner** [comment]
> And the long list above seems unavoidable?

I'm also not sure how to avoid it

> Of course we can remove repetitive/unnecessary `using`

I slip that into #45222

**Comment by JeffBezanson** [comment]
Yes, this weirdness is due to Sort being included in both Base and Core.Compiler. We might be able to remove all or most of it in the future with better separate compilation support. Removing the duplicates is of course welcome. Other than that I will close this since it's not a significant problem and it will be a while before we can really address it.
