### ISSUE TITLE
Dates missing Semester (would a PR be welcome?)

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#45660]
I need to support Semesters in my use case ([Dynare](https://github.com/DynareJulia/Dynare.jl)). If folks think it would be worth supporting Semesters directly in Dates, I'd like to make a PR here to do that, but I don't want to go to the trouble if folks think Semesters are too uncommon to support in a stdlib.
```juila
using Dates
subtypes(DatePeriod)
5-element Vector{Any}:
 Day
 Month
 Quarter
 Week
 Year
```

**Comment by vchuravy** [comment]
Semester is a half year? Term is slightly ambiguous in an academic context.

**Comment by LilithHafner** [comment]
> Semester is a half year?

Yes, defined as 6 months in the same way as Quarter is defined as 3 months.

**Comment by KristofferC** [comment]
Personally, I think this is a bit too ambiguous to be an obviously good idea.

**Comment by LilithHafner** [comment]
Thanks for the feedback, y'all! I'm glad I opened an issue instead of a PR.
