### ISSUE TITLE
build julia on Annapurna Labs AL324 failed (arm64)

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#45681]
bulid julia on Annapurna Labs AL324 (cortex-a57 quad core 1.7Ghz) failed, OS is archlinuxarm , gcc is 

```
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-unknown-linux-gnu/12.1.0/lto-wrapper
Target: aarch64-unknown-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://github.com/archlinuxarm/PKGBUILDs/issues --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-multilib --disable-werror --host=aarch64-unknown-linux-gnu --build=aarch64-unknown-linux-gnu --with-arch=armv8-a --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (GCC)
```
cpu info is:
```
processor       : 3
model name      : Annapurna Labs Alpine AL324 Quad-core ARM Cortex-A57 CPU @ 1.70GHz
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 3
```
edit Make.user  and add  `march=armv8-a` or `MCPU=cortex-a57` to it, but both failed and report 
```
  LINK usr/lib/libjulia-codegen.so.1.9
  LINK usr/lib/libjulia-codegen.so.1
  LINK usr/lib/libjulia-codegen.so
  JULIA usr/lib/julia/corecompiler.ji
ERROR: rethrow() not allowed outside a catch block
make[1]: *** [sysimage.mk:58: /hdd/src/julia/usr/lib/julia/corecompiler.ji] Error 1
make: *** [Makefile:82: julia-sysimg-ji] Error 2
```

**Comment by armgong** [comment]
try further 
1. download julia 1.8rc1 arm64 pre-build binary from `julialang.org`  ,
 ~~~
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |


SYSTEM: caught exception of type
~~~
2. used archlinuxarm virtual machine on macbook air m1 to build with ~~~march=armv8-a or MCPU=cortex-a57~~~ , run ok on the VM ,but still fail on Annapurna Labs AL324.
~~~
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.771 (2022-06-14)
 _/ |\__'_|_|_|\__'_|  |  Commit 6dae654e91* (2 days old master)
|__/                   |

julia> versioninfo()
fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
__aarch64_sync_cache_range at /workspace/srcdir/gcc-11.1.0/libgcc/config/aarch64/sync-cache.c:61
_ZN4llvm3sys6Memory26InvalidateInstructionCacheEPKvm at /hdd/src/julia/usr/bin/../lib/libLLVM-13jl.so (unknown line)
~~~

**Comment by oschulz** [comment]
I get the same "SYSTEM: caught exception of type" (and then stall) on an aarch64 Chromebook with the official v1.7.3 and v1.8.0-rc1 build.

The aarch64 nightly build (1.9.0-DEV.834) starts, but crashes on `versioninfo()`.

Julia v1.7.2 runs fine on the same device, even complex applications involving large packages.

**Comment by inkydragon** [comment]
`aarch64` build with: https://buildkite.com/julialang/julia-master/builds/14883#0182b509-752d-4561-82e0-3bdf42f0b984/531-532
```
Make Options:
 -> --output-sync
 -> -j10
 -> VERBOSE=1
 -> TAGGED_RELEASE_BANNER=Official https://julialang.org/ release
 -> JULIA_CPU_TARGET=generic;cortex-a57;thunderx2t99;carmel
```

I've build with `JULIA_CPU_TARGET=` locally, seems works for me.

**Comment by vchuravy** [comment]
What's the 1.7.3 error message?

The 1.8 message means that `libjulia-compiler.so` couldn't be loaded at startup.

**Comment by vchuravy** [comment]
If anyone could try running the LLVM self-tests on the platform (v14 and v15) that would be helpful.

We might need https://github.com/JuliaLang/julia/pull/45859

**Comment by inkydragon** [comment]
> What's the 1.7.3 error message?

Oh, that's my fault. 1.7.3 has NO problem. (I even used the output of 1.7.3 as version information)

**Comment by oschulz** [comment]
> If anyone could try running the LLVM self-tests on the platform (v14 and v15) that would be helpful

Can I do this with the Julia-included LLVM somehow?

**Comment by oschulz** [comment]
On Chromebook-Linux (aarch64-unknown-linux-gnu) I currently get (official Julia binaries)

* Julia v1.6.0: works
* Julia v1.6.7: stalls on startup
* Julia v1.7.0: works
* Julia v1.7.3: `SYSTEM: caught exception of type ` (that's all of it, doesn't say what type)
* Julia v1.8.0: `SYSTEM: caught exception of type ` (that's all of it, doesn't say what type)

**Comment by giordano** [comment]
For what is worth, build of the `v1.8.0` tag is successful for me on a MacBook M1:
```
~/repo/julia$ ./julia -q    
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab7 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: 8 × unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

> The 1.8 message means that libjulia-compiler.so couldn't be loaded at startup.

That sounds related to #46409, and #46464 should help with that if `LD_LIBRARY_PATH` is the issue also here

**Comment by ViralBShah** [comment]
We have been building on aarch64 recently and successfully. Please reopen if still an issue.

**Comment by sprig** [comment]
Sorry, a bit unrelated - @armgong , how do you get arch to run on annapurna al324?

Thanks in advance!

**Comment by sprig** [comment]
I understand, so not a full independant kernel.
Thanks!
