### ISSUE TITLE
ComposedFunction type inference regression from v1.6 LTS

### ISSUE THREAD

**Issue by oschulz** [JuliaLang/julia#45715]
Julia v1.6 type inference has no trouble with this:

```julia
julia> VERSION
v"1.6.6"

julia> using Test

julia> @inferred ((-) ∘ (-) ∘ (-) ∘ (-) ∘ (-) ∘ (-))(0)
0
```

Julia v1.7 and v1.8-rc1 can't type-infer even a three-element composition anymore:

```
julia> VERSION  # same for v"1.8.0-rc1"
v"1.7.3"

julia> using Test

julia> @inferred ((-) ∘ (-) ∘ (-))(0)
ERROR: return type Int64 does not match inferred return type Any
```

This makes function composition very unattractive in performance-critical code.

**Comment by oschulz** [comment]
The reason seems to be that from

```julia
(c::ComposedFunction)(x...) = c.outer(c.inner(x...))
```

in Julia v1.6 it changed to

```julia
(c::ComposedFunction)(x...; kw...) = c.outer(c.inner(x...; kw...))
```

in v1.7. This apparently kills type inference here as soon as things get nested.

**Comment by oschulz** [comment]
Something like this seems to fix it:

```julia
@inline (c::ComposedFunction)(x...; kw...) = call_composed(c, x, kw)
call_composed(c::F, x, kw) where {F<:ComposedFunction} = call_composed(c.outer, c.inner(x...; kw...))
call_composed(c::F, x) where {F<:ComposedFunction} = call_composed(c.outer, c.inner(x...))
call_composed(c::F, x) where {F} = c(x)
```

```julia
julia> VERSION
v"1.8.0-rc1"

julia> @inferred ((-) ∘ (-) ∘ (-) ∘ (-) ∘ (-) ∘ (-))(0)
0
```

Would a change like that be acceptable?

**Comment by oscardssmith** [comment]
looks reasonable to me

**Comment by vtjnash** [comment]
I don’t see why that helps fully. It looks like you just rearranged some of the symbols until you didn’t know how to reproduce anymore. Pretty sure we may have an open issue about this recursion pattern already though? Not exactly clear why this one is failing currently.

**Comment by oschulz** [comment]
> It looks like you just rearranged some of the symbols until you didn’t know how to reproduce anymore.

Well, there was some method to my rearranging, though I definitly don't know what happens on the compiler side exactly. What I was going for with that approach was getting the (empty) keywords out of the subsequent function evaluations, so that `c_outer` (and outer-outer and so on) will not be called with an empty `kw...`.

**Comment by oschulz** [comment]
So I'm effectively replacing ```(c::ComposedFunction)(x...; kw...) = c.outer(c.inner(x...; kw...))``` with ```(c::ComposedFunction)(x...) = c.outer(c.inner(x...))``` for all outer function calls.

**Comment by martinholters** [comment]
Here's a breadcrumb for looking at what's happening in the compiler: We hit
https://github.com/JuliaLang/julia/blob/4c39647aed7d2a36e38bd6c8c04469e22bbf5c33/base/compiler/abstractinterpretation.jl#L559
with 
```julia
sig == Tuple{Base.var"##_#95", Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Base.ComposedFunction{typeof(Base.:(-)), typeof(Base.:(-))}, Int64}
comparison == Tuple{Base.var"##_#95", Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where T<:Tuple{Vararg{Any, N}} where names where N where V, Base.ComposedFunction{O, I} where I where O, Vararg{Any}}
```
which results in
```julia
newsig == Tuple{Base.var"##_#95", Base.Pairs{K, V, I, A} where A where I where V where K, Base.ComposedFunction{typeof(Base.:(-)), typeof(Base.:(-))}, Int64}
```
which is used as widened signature to force convergence of the recursion.

IIUC correctly, for a direct recursion (a method calling itself dierectly), we might not widen as aggressively by choosing a different `comparison`, but with the kwarg stuff, we get another indirection, leading to the observed behavior. That explains why getting rid of the kwargs before recursing helps. @vtjnash does that analysis make sense?

**Comment by N5N3** [comment]
Your version will change the behavior if the `inner` returns something like `(1, 2)` (Doc said we should call `outer((1, 2))`, not `outer(1, 2)`.)
Can't we just
```julia
(c::ComposedFunction)(x...; kw...) = call_composed(c.outer, c.inner(x...; kw...))
call_composed(c::ComposedFunction, x) = call_composed(c.outer, c.inner(x))
call_composed(c, x) = c(x)
```

**Comment by N5N3** [comment]
At a second think, the above solution also might fail if the returned type of `inner` become more and more complex.
If we want to make sure our compiler would do eager inference on nested  `ComposedFunction`, some trick similar to #45789 seems reasonable.
```julia
(c::ComposedFunction)(x...; kw...) = c.outer(c.inner(x...; kw...))
(c::ComposedFunction)(x) = call_composed(x, unwrap_composed(c)...)
unwrap_composed(c::ComposedFunction) = (c.inner, unwrap_composed(c.outer)...)
unwrap_composed(c) = (c,)
call_composed(x, f, fs...) = call_composed(f(x), fs...)
call_composed(x, f) = f(x)
```

**Comment by oschulz** [comment]
Good point, @N5N3 - should we start a PR for the details?

**Comment by N5N3** [comment]
I have put them together into #45789. (`Base._xfadjoint` could fuse `call_composed` and the test case there could also be used to test `ComposedFunction`'s inference)

**Comment by oschulz** [comment]
Neat, thanks @N5N3 !
