### ISSUE TITLE
Base.tail not exported?

### ISSUE THREAD

**Issue by braamvandyk** [JuliaLang/julia#45749]
Julia Version 1.7.3

This is a really minor issue, but I noticed that while

```
julia> first((1, 2, 3))
1
```

works just fine, 

```
julia> tail((1, 2, 3))
ERROR: UndefVarError: tail not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

and

```
julia> Base.tail((1, 2, 3))
(2, 3)
```

Would it not, for the sake of consistency, make sense to export Base.tail()?

**Comment by giordano** [comment]
Note that the complementary of `Base.tail` is `Base.front`, not `Base.first`, and `front` isn't exported either.  So everything is already consistent?
