### ISSUE TITLE
Error: The following package names could not be resolved.

### ISSUE THREAD

**Issue by rickmoua** [JuliaLang/julia#45762]
I'm trying to create a MVC web app, I'm stuck at this point - the point of interacting with the movies data.
Please advise.

julia>using Pkg
julia>Pkg.add("Movies")
ERROR: The following package names cold not be resolved:
*Movies (not found in project, manifest, or registry)

**Comment by KristofferC** [comment]
There is no Movies package in the General registry. Please ask further questions at http://discourse.julialang.org

**Comment by DilumAluthge** [comment]
This issue tracker is specifically for the development of the Julia language itself. Please ask questions on https://discourse.julialang.org
