### ISSUE TITLE
IJulia notebooks for documentation?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4579]
I'm really keen on the idea of writing Julia docs using IJulia notebooks. Notebooks support Markdown text formatting with embedded math equations using MathJax, and of course, if you run a notebook locally, you can execute all the code yourself, which I think will help people learn more effectively and making it easy to step through examples will help keep the examples up-to-date and catch cases where code changes breaks the examples more quickly. I've also found that IJulia notebooks are a great way to write documentation in the first place.

However, it would be nice if the source format, rather than the not-very-human-readable .ipynb JSON format, were something more like Markdown with embedded code examples (and output) that could be transformed – via code execution – to notebook form. This would be a bi-directional transformation:

- markdown w/ code and output + IJulia kernel ⟹ IJulia notebook
- IJulia notebook ⟹ markdown w/ code and output

The first transformation occurs via code execution; the second by just outputting the content of the notebook to markdown format, with input and output cells included as embedded code. Or maybe this process is too complicated and .ipynb should just be the source format.

So what are the features that we need from IPython notebook to support this? Obviously, we need the ability to link from one notebook to another. What else?

**Comment by mauro3** [comment]
Should this be closed or is this still relevant?

**Comment by stevengj** [comment]
I think it can be closed.

**Comment by simonbyrne** [comment]
Why is it no longer relevant?

**Comment by stevengj** [comment]
Because we've gone in another direction for documentation of Julia itself.   It still might be interesting for someone to do a notebook/manual conversion package, but that's more an issue for `nbconvert` or something else than for Julia Base.
