### ISSUE TITLE
`max_parallel` kwarg throwing error

### ISSUE THREAD

**Issue by lautcjc** [JuliaLang/julia#45811]
`versioninfo()`
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 15

I noticed that when I use 
```
addprocs(Sys.CPU_THREADS; max_parallel = 15, enable_threaded_blas=true)
```

it throws an error: `ERROR: ArgumentError: Invalid keyword argument max_parallel`

I think this is an error.

**Comment by Seelengrab** [comment]
According to the docstrings, `max_parallel` is only supported when specifying the remote machines as a vector, not when specifying just a number of local processes to spawn.
