### ISSUE TITLE
rr assertion on CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#45828]
https://buildkite.com/julialang/julia-master/builds/13205#01819650-deec-4c5a-8828-67240eee4c48

Filed upstream as https://github.com/rr-debugger/rr/issues/3289. This issue will track both that issue as well as any eventual rr upgrade that may be required.

The relevant error message is:
```
  | [FATAL src/RecordSession.cc:1424:preinject_signal()]
  | (task 3989 (rec:3989) at time 6536798)
  | -> Assertion `t->stop_sig() == t->session().syscallbuf_desched_sig()' failed to hold. Expected SYSCALLBUF_DESCHED_SIGNAL, got 0x80057f (GROUP-STOP-SIGTRAP)
  | [INFO log_pending_events()] SIGNAL_DELIVERY: SIGCHLD(async)
  | [INFO log_pending_events()] SYSCALL_INTERRUPTION: futex
  | [INFO log_pending_events()] (none)
  | === Start rr backtrace:
```

**Comment by Keno** [comment]
@staticfloat @DilumAluthge For this one, I would have liked to inspect the incomplete rr trace. Can we change CI to make sure to tar this up?

**Comment by DilumAluthge** [comment]
Sure. What are the steps to do so?

**Comment by DilumAluthge** [comment]
Here's what we currently do: https://github.com/JuliaCI/julia-buildkite/blob/main/utilities/rr/rr_capture.jl

**Comment by Keno** [comment]
Just tar up the traces directory. I guess the issue here was that rr failed and then expected somebody to connect via GDB, which obviously won't happen. We probably should just have rr exit cleanly there instead and then the existing logic would have tar'ed up the trace.

**Comment by Keno** [comment]
Upstream fix pending in https://github.com/rr-debugger/rr/pull/3290.

**Comment by ViralBShah** [comment]
Upstream has merged. Close?
