### ISSUE TITLE
Separate comments from sysimage

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#45863]
It has lots of comments (I was greping for 1:length), and found about by accident.

$ strings ./usr/lib/julia/sys.so |wc
1566928 1829012 13980543

$ strings ./usr/lib/julia/sys.ji |wc
 607938  823226 5801001

unclear why the former (what's used), has so much more. I suppose this applies to PackageCompiler too. At least it should be an option.

**Comment by JeffBezanson** [comment]
There are actually a lot of common x86 instruction sequences that get picked up by `strings`; that probably explains the difference.

We don't save comments from source code, but doc strings, source locations, and variable names can be stripped using `--strip-metadata`.
