### ISSUE TITLE
Possible faulty AbstractArray code (for e.g. OffsetArray)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#45866]
It was suggested greping for `@inbounds` so I (started) looking at all of Julia. I ignored looking at stuff I don't know enough about e.g. `@propagate_inbounds` and I didn't (yet) grep for AbstractVector, nor AbstractTuple (since it doesn't exists yet, only mentioned in one issue).

function reverse!(v::AbstractVector, start::Integer, stop::Integer=lastindex(v))

seems wrong.

function collect_to!(dest::AbstractArray{T}, itr, offs, st) where T

might be wrong and (then?) more in that file.

function getindex(V::FastSubArray, i::Int)
function getindex(V::FastContiguousSubArray, i::Int)

made me think, do regular AbstractArrays (and AbstractVectors) need to be contiguous, if not then this doesn't make sense and is wrong... (otherwise its file seems ok, and I marked it as such):

function searchsorted(v::AbstractVector, x, ilo::T, ihi::T, o::Ordering)::UnitRange{keytype(v)} where T<:Integer

Not sure:
function _maybe_reindex(V, I, ::Tuple{})

This one is interesting, ok for all arrays, e.g. OffsetArray?
```
function unsafe_getindex(A::AbstractArray, I...)
    @inline
    @inbounds r = getindex(A, I...)
    r
end

if not then neither: 
function unsafe_setindex!(A::AbstractArray, v, I...)

function _getindex(::IndexLinear, A::AbstractArray, I::Vararg{Int,M}) where M

is likely ok.
```

Unsure about these functions:
```
function copyto!(dest::AbstractArray, dstart::Integer, src, sstart::Integer, n::Integer)

function nonzeros(x::SparseColumnView)
    rowidx, colidx = parentindices(x)
    A = parent(x)
    @inbounds y = view(nonzeros(A), nzrange(A, colidx))
    return y
end
nonzeros(x::SparseVectorView) = nonzeros(parent(x))

nonzeroinds(x::SparseVector) = getfield(x, :nzind)
function nonzeroinds(x::SparseColumnView)
    rowidx, colidx = parentindices(x)
    A = parent(x)
    @inbounds y = view(rowvals(A), nzrange(A, colidx))
    return y
end
```

Too complex for me to judge:
```
@generated function _unique_dims(A::AbstractArray{T,N}, dim::Integer) where {T,N}
```

All the relevant files (and I believe I ruled out the marked files as problematic, unless for problems mentioned above):
* ./base/abstractarray.jl
./base/compiler/abstractinterpretation.jl
./base/subarray.jl
* ./base/views.jl
* ./base/indices.jl
* ./base/sort.jl
* ./base/bitarray.jl
./base/essentials.jl
* ./base/array.jl
./base/tuple.jl
* ./base/multidimensional.jl
./base/broadcast.jl
./base/io.jl
./base/accumulate.jl
./base/reflection.jl
./base/reduce.jl
./base/range.jl
./base/intfuncs.jl

./usr/lib/julia/corecompiler.ji

./stdlib/Random/src/generation.jl
./stdlib/Random/src/RNGs.jl
./stdlib/SharedArrays/src/SharedArrays.jl
./stdlib/LinearAlgebra/src/givens.jl
./stdlib/LinearAlgebra/src/diagonal.jl
./stdlib/LinearAlgebra/src/lapack.jl
./stdlib/LinearAlgebra/src/qr.jl
./stdlib/LinearAlgebra/src/lu.jl
./stdlib/SuiteSparse-f63732c1c6adecb277d8f2981cc8c1883c321bcc/src/spqr.jl
./stdlib/SuiteSparse-f63732c1c6adecb277d8f2981cc8c1883c321bcc/src/cholmod.jl
./stdlib/SparseArrays-aa51c9b82d952502139213715c9b077ec36c4623/src/sparsevector.jl
./stdlib/SparseArrays-aa51c9b82d952502139213715c9b077ec36c4623/src/higherorderfns.jl
./stdlib/SparseArrays-aa51c9b82d952502139213715c9b077ec36c4623/src/sparsematrix.jl

I.e. this gives the possibly problematic files:
find . |xargs grep -l 'AbstractArray' |xargs grep -l 'inbounds' |xargs grep -l '1:l' >OA_trouble

**Comment by JeffBezanson** [comment]
I think we have to distinguish here between `::AbstractArray` functions that are only wrong if the passed array is implemented incorrectly, vs. ones that are wrong even on a correctly implemented OffsetArray. The latter are far more important.

> function searchsorted(v::AbstractVector, x, ilo::T, ihi::T, o::Ordering)::UnitRange{keytype(v)} where T<:Integer

I think this was not intended to be a public method (it's not documented) and should have had an underscore. We are probably keeping it for compatibility.

**Comment by jishnub** [comment]
Thanks for looking into this! However, you're looking at various non-public methods that are not meant to be called by users. These are internal methods that are only called after appropriate bounds checking has already taken place. Perhaps the focus should be on documented methods, and see if these fail for some `OffsetArray`-like argument, or if there is an integer overflow. The functions such as `reverse!` fall in this category, so it would be interesting to see where these fail. 

Could you also provide an example for which these produce incorrect results? This makes it much easier to diagnose the issue.

**Comment by N5N3** [comment]
`./base/broadcast.jl` deserves a problematic mark. (See #43414 for more deftials.)

**Comment by KristofferC** [comment]
It's very hard to have any structure in this when there are a bunch of different functions talked about in the first post. I suggest opening an issue for the specific case with a concrete example that shows how it is wrong for OffsetArray and then it can be dealt with on a case-by-case basis.
