### ISSUE TITLE
Incorrect behavior of logical indexing

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#45867]
The documentation for [logical indexing](https://docs.julialang.org/en/v1/manual/arrays/#Logical-indexing) says that indexing by a N-dimensional boolean array is effectively the same as indexing by the vector of `CartesianIndex{N}`s where its values are `true`.

However, this does not appear to behave correctly in Julia’s current implementation.

In the simple example below, indexing `array` with a vector of `CartesianIndex{2}` succeeds, while indexing it with the equivalent two-dimensional logical index fails:

```jl
julia> array = [1];

julia> index = [true;;];

julia> findall(index)
1-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)

julia> array[findall(index)] # correct
1-element Vector{Int64}:
 1

julia> array[index] # incorrect?
ERROR: BoundsError: attempt to access 1-element Vector{Int64} at index [1×1 Matrix{Bool}]
Stacktrace:
 [1] throw_boundserror(A::Vector{Int64}, I::Tuple{Base.LogicalIndex{Int64, Matrix{Bool}}})
   @ Base ./abstractarray.jl:691
 [2] checkbounds
   @ ./abstractarray.jl:656 [inlined]
 [3] _getindex
   @ ./multidimensional.jl:838 [inlined]
 [4] getindex(A::Vector{Int64}, I::Matrix{Bool})
   @ Base ./abstractarray.jl:1218
 [5] top-level scope
   @ REPL[5]:1
```

**Update:** The docs additionally say that

> A logical index must be a vector of the same length as the dimension it indexes into, or it must be the only index provided and match the size and dimensionality of the array it indexes into.

In the above case, neither condition applies, so it seems that this is a documented edge case. 

It might also be the explanation for a confusing behavior [encountered](https://discourse.julialang.org/t/slicing-and-boolean-indexing-in-multidimensional-arrays/83522) earlier by a Julia user, but I don't understand well enough to say.

This test was run on Julia 1.7.3.

```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by N5N3** [comment]
I'm not sure what's the desired behavior. But the [example on discourse](https://discourse.julialang.org/t/slicing-and-boolean-indexing-in-multidimensional-) should be a (unrelated) bug.
```julia
julia> getindex(randn(2,3,4), 1, view(rand(Bool,3,4),:,:)); # success with a wrapper

julia> getindex(randn(2,3,4), 1, rand(Bool,3,4));
ERROR: BoundsError: attempt to access 2×3×4 Array{Float64, 3} at index [1, 3×4 Matrix{Bool}]
```
