### ISSUE TITLE
Strange `cld` behaviour

### ISSUE THREAD

**Issue by michakraus** [JuliaLang/julia#45875]
According to the documentation `cld(x,y)` gives the  "Smallest integer larger than or equal to `x/y`. Equivalent to `div(x, y, RoundUp)`."

In practice, I find:
```
julia> cld(1.1, 0.1)
12.0

julia> div(1.1, 0.1, RoundUp)
11.0
```
This is on
```
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by jmkuhn** [comment]
As I see it the discrepancy is:
```
julia> div(big(1.1), big(0.1), RoundUp)    # expect 12.0
12.0

julia> div(1.1, 0.1, RoundUp)    # expect 12.0?
11.0

julia> div(1.1, 0.1, RoundDown)
11.0

julia> div(-1.1, 0.1, RoundUp)
-11.0

julia> div(-1.1, 0.1, RoundDown)
-12.0
```

**Comment by oscardssmith** [comment]
I'm sorry, I misread this, this does appear to be an issue.

**Comment by t-bltg** [comment]
I believe `div(1.1, 0.1, RoundUp)`returning `11.0` is correct since `1.1 / 0.1 = 11.0` is exact in IEEE 754 double-precision format (with signbit `0`, biased exponent `10000000010` and mantissa `0110000000000000000000000000000000000000000000000000`).

```julia
julia> using Printf
julia> @printf "%.20f" 1.1 / 0.1
11.00000000000000000000
julia> bitstring(1.1 / 0.1)
"0100000000100110000000000000000000000000000000000000000000000000"
```

So `cld(1.1, 0.1)` should return `11.0` according to the docs "Smallest integer larger than or **equal to x/y**".

**Comment by martinholters** [comment]
> `1.1 / 0.1 = 11.0` is exact

No? Note that neither `1.1` nor `0.1` are exact in the sense that they're exactly equal to the real numbers they look like. In fact they both happen to be slightly larger. So `1.1 / 0.1` in floating point numbers is not the same as 1.1/0.1 in reals. The exact result for the former again is slightly larger than 11, but is rounded to exactly `11.0` as the nearest floating point number, as [shown above](https://github.com/JuliaLang/julia/issues/45875#issuecomment-1171403973). Also
```julia
julia> big(11) * 0.1 < 1.1
true
```

**Comment by t-bltg** [comment]
I think we mean the same thing. What I meant, to be more clearer is that as long as you are working with `1.1 / 0.1` in double prec, you are using `11.0` hence rounding after this op is a noop.

**Comment by martinholters** [comment]
Right, but the `div` docstring says "without any intermediate rounding". Which I'd take as `1.1` / `0.1` is slightly larger than 11 (before any rounding), so if rounding is `RoundUp` the result should be 12.

**Comment by t-bltg** [comment]
> without any intermediate rounding

That's a lie since the `1.1 / 0.1` op seems to occur here, in the ceil(...) call:
https://github.com/JuliaLang/julia/blob/f4801ff2b50594568f0bb66a1b4d8ee9181d76bf/base/div.jl#L370.

**Comment by martinholters** [comment]
> That's a lie

That's exactly the point I was trying to make. The docstring and the behavior are in disagreement.

**Comment by t-bltg** [comment]
Thanks for the comments @martinholters.

I've updated the PR, and get the expected values mentioned in https://github.com/JuliaLang/julia/issues/45875#issuecomment-1171482362.

Two tests marked broken before are now passing at https://github.com/JuliaLang/julia/blob/f4801ff2b50594568f0bb66a1b4d8ee9181d76bf/test/numbers.jl#L2554
One test had its sign modified (`0.0` -> `-0.0`): `isequal(rem(nextfloat(typemin(T)), T(2), RoundUp), -0.0)`.
