### ISSUE TITLE
DemoteFloat16 pass ignores vectors of Float16

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#45881]
As noticed by @giordano in https://github.com/JuliaLang/julia/issues/40308#issuecomment-1160945816, when LLVM decided to vectorize, the demote Float16 pass doesn't trigger. Presumably this is due to https://github.com/JuliaLang/julia/blob/fec6951a8b2e11a2560d13c1b995874bff561aa5/src/llvm-demote-float16.cpp#L82 only checking if it is a `T_float16` and not a vector of `Float16`. 

While it is nice that it currently "accidentally" works, since we want on A64FX to trigger the emission of native Float16 operations,
we should fix this bug and simultaneously address https://github.com/JuliaLang/julia/issues/40216

**Comment by vtjnash** [comment]
This was fixed in https://github.com/JuliaLang/julia/pull/45249, until we decided to say that performance was more important than correctness and reverted it

**Comment by vtjnash** [comment]
They aren't co-mingled really, you just have to pick a name for the function (or intrinsic) to call here https://github.com/JuliaLang/julia/pull/45249/files#diff-d6a6d037fdf95b0875b7d800187abc42b7ef9abf7004e36ad3ef392655144631R140

**Comment by vtjnash** [comment]
The point of `fastmath` is to return less correct answers, so this pass isn't needed

**Comment by gbaraldi** [comment]
I thought generating float16 instructions when not available was bad, but it seems llvm just adds the conversions if necessary when generating native code

**Comment by giordano** [comment]
> but it seems llvm just adds the conversions if necessary when generating native code

Then why we have the demotion pass in Julia again? 😬

**Comment by gbaraldi** [comment]
I don't know :)
