### ISSUE TITLE
We have an error in the round function of Rational{BigInt}

### ISSUE THREAD

**Issue by Anton-Orekhov** [JuliaLang/julia#45906]
Good day.
We talk about the round function to `Rational{BigInt}` at Julia 1.6.6.
Example:
julia> round(Rational{BigInt}(-5000000//63),digits=2)
-79365.07999999999999999999999999999999999999999999999999999999999999999999999995
It is an error in fact.

**Comment by cafaxo** [comment]
Where is the error? It seems to work as expected:
```
julia> round(Rational{BigInt}(-5000000//63),digits=2) == BigFloat("-79365.08")
true
```
The number `-79365.08` cannot exactly be represented by `BigFloat`. [The documentation](https://docs.julialang.org/en/v1/base/math/#Base.round-Tuple{Type,%20Any}) also explains this.

The printing of `BigFloat` and `Float64` behaves a bit differently:
```
julia> BigFloat("-79365.08")
-79365.07999999999999999999999999999999999999999999999999999999999999999999999995

julia> -79365.08
-79365.08

julia> @printf "%.20f" -79365.08
-79365.08000000000174622983
```
Julia abbreviates the printing for `Float64`.

**Comment by JeffBezanson** [comment]
We could in theory use the same printing trick for BigFloat, but AFAIK it's difficult to implement and confounded by the fact that different BigFloats can have different precision, so unless we somehow printed the precision as well it would be misleading. So I think I will close this for now.
