### ISSUE TITLE
Make (again) length type match index type in sparse vectors

### ISSUE THREAD

**Issue by dpinol** [JuliaLang/julia#45937]
In julia 1.6, `typeof(length(SparseArray))`always returned an Int64.
But in julia 1.7, after https://github.com/JuliaLang/julia/pull/39645 it returned the same type as the index type.
Now in julia 1.8rc1, the type is again always an Int64.
The regression was introduced by https://github.com/JuliaLang/julia/pull/41510, since length(array) is calculated through prod. 

On the other hand, I understand that the promotion may be necessary for n-dimensional arrays, since the length may overflow the type of the individual dimensions. So, if we want to stick to Int64, maybe we could document it in the julia 1.8 release notes?

thanks

**Comment by PallHaraldsson** [comment]
v1.7.3 was released May 6, 2022, and back then I thought 1.8 imminent, and it would be the last 1.7 release.

I realize 1.8 isn't released, so if understand correctly you want 1.7 to be fixed. If 1.8 is released (soon), does it then matter?

Julia 1.7 will then no longer be the stable supported version (unless if made LTS...).

**Comment by dpinol** [comment]
If we commit to returning Int64, I'm happy to have it written somewhere,  in the documentation or the release notes. 
At least to avoid that developers get confused since according to https://github.com/JuliaLang/julia/pull/39645 it looks like the correct behaviour is returning the type of the index. thanks

**Comment by dkarrasch** [comment]
https://github.com/JuliaLang/julia/pull/39645 addresses `SparseVector`s only, right, so I think we should just specialize

```julia
Base.length(x::SparseVector) = x.n
```

Then the return type of `length` will be fully inferrable. Such a change is fairly specific and shouldn't have "undesired" side-effects, so should be backportable.

**Comment by dkarrasch** [comment]
Wait, can you provide an example of what you think changed or regressed? On v1.8rc1 I get

```julia
julia> using SparseArrays, Test

julia> y = SparseVector(Int128(8), Int128[4], [5])
8-element SparseVector{Int64, Int128} with 1 stored entry:
  [4]  =  5

julia> @test y isa SparseVector{Int,Int128}
Test Passed

julia> @test @inferred size(y) == (@inferred(length(y))::Int128,)
Test Passed

julia> typeof(length(y))
Int128
```

Note that https://github.com/JuliaLang/julia/pull/39645 did not touch any `SparseMatrixCSC` stuff.

**Comment by dpinol** [comment]
@dkarrasch The regression is only when the size of the index is smaller than 64 bit (probably due to `prod`'s type promotion)

Julia 1.8
```
julia> y = SparseVector(8, Int32[4], [5])
8-element SparseVector{Int64, Int32} with 1 stored entry:
  [4]  =  5

julia> typeof(length(y))
Int64
```

Julia 1.7
```
julia> y = SparseVector(8, Int32[4], [5])
8-element SparseVector{Int64, Int32} with 1 stored entry:
  [4]  =  5

julia> typeof(length(y))
Int32
```

**Comment by dkarrasch** [comment]
Thanks, then my proposal above should work.
