### ISSUE TITLE
Partial evaluation internal closure

### ISSUE THREAD

**Issue by bkalpert** [JuliaLang/julia#45940]
In a new session in julia-1.7.3, the code

julia> foo(a,b,c,d,e) = a*c*e + b*d
foo (generic function with 1 method)

julia> bar(a,b,c,d,e) = (foo(a,b) = foo(a,b,c,d,e); foo(a,b))
bar (generic function with 1 method)

has an internal, two-argument  foo  intended to reflect partial evaluation of the external five-argument  foo.  Calling  bar  as

julia> bar(1,2,3,4,5)
ERROR: MethodError: no method matching (::var"#foo#1"{Int64, Int64, Int64})(::Int64, ::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
  (::var"#foo#1")(::Any, ::Any) at REPL[2]:1
Stacktrace:
 [1] (::var"#foo#1"{Int64, Int64, Int64})(a::Int64, b::Int64)
   @ Main ./REPL[2]:1
 [2] bar(a::Int64, b::Int64, c::Int64, d::Int64, e::Int64)
   @ Main ./REPL[2]:1
 [3] top-level scope
   @ REPL[3]:1

produces the (to me surprising) error as shown.  Is this code intentionally unsupported?

**Comment by KristofferC** [comment]
Yes, you are shadowing the outer function. You can give it another name.

**Comment by bkalpert** [comment]
Okay: good to know this distinction.
