### ISSUE TITLE
Ordered collection segfaults when deleting nothing

### ISSUE THREAD

**Issue by mforets** [JuliaLang/julia#45959]
The following segfaults with any command after `delete!`:

```julia
  _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using OrderedCollections

julia> x = OrderedDict(2 => 0.1, nothing => 0.2)
OrderedDict{Union{Nothing, Int64}, Float64} with 2 entries:
  2       => 0.1
  nothing => 0.2

julia> delete!(x, nothing)
OrderedDict{Union{Nothing, Int64}, Float64} with 1 entry:
signal (11): Segmentation fault
```

PS: I ran it with `--bug-report=rr` but uploading the trace directory fails with "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". I can still upload the directory generated locally if it helps (though it's 160MB).

**Comment by jakobnissen** [comment]
This is an issue of OrderedCollections, which uses an `@inbounds` annotation incorrectly. Running Julia with `--check-bounds=yes` turns this into an ordinary bounds error.
