### ISSUE TITLE
Unhelpful sentence in `objectid`'s docstring

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#45950]
"`objectid(x) == objectid(y)` if `x === y`" is a very weak statement. It should be strengthened to "`objectid(x) == objectid(y)` if and only if `x === y`" if possible and otherwise eliminated. Is it true that `objectid(x) == objectid(y)` if and only if `x === y`?

Context:
```
help?> objectid
search: objectid

  objectid(x) -> UInt

  Get a hash value for x based on object identity. objectid(x)==objectid(y) if x === y.

  See also hash, IdDict.
```

**Comment by vtjnash** [comment]
The statement as written is correct

**Comment by LilithHafner** [comment]
I agree that it is correct. Is "if and only if" also correct?

**Comment by jakobnissen** [comment]
@LilithHafner  It can't be - since an objectID is a UInt, there are only 2^64 objectids, but 2^65 instances of `Union{Int, UInt}`. Hence some different objects must have the same id.

**Comment by LilithHafner** [comment]
Thanks, for example `objectid(19536114) == objectid(0x638ea192fc1b40a1)`.

CPython gets around this by defining `id` based on memory address, but I see we do not because `objectid` is a pure function for integers.

The trouble I see with the statement `objectid(x)==objectid(y) if x === y` is that it holds for any pure function. But I guess in this case while the statement is formally fairly vaccuous, it still conveys accurate information about the behavior of the function, albiet infromally. I'll try to come up with a better wording.
