### ISSUE TITLE
Why is `⥺` not an operator?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#45962]
I can see `⭄` (Rightwards Arrow Through Superset) is recognized as an operator in the [parser](https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm). But why is `⥺` not?

**Comment by singularitti** [comment]
Also, I can find `⭃` (Rightwards Arrow Through Greater-Than) but not `⥷` ([Leftwards Arrow Through Less-Than](https://unicode-table.com/en/2977/)), can we add them both?

**Comment by Moelf** [comment]
just pattern match this PR: https://github.com/JuliaLang/julia/pull/39403

 and you should be good to go

**Comment by singularitti** [comment]
Since #49623 is merged and v1.10.0 already has this feature, I will close this issue as resolved.
