### ISSUE TITLE
allow addenv to delete environment variables

### ISSUE THREAD

**Issue by mgkuhn** [JuliaLang/julia#45960]
The existing [`Base.withenv()`](https://docs.julialang.org/en/v1/base/base/#Base.withenv) function allows users to delete environment variables by mapping them to `nothing`.

Example (from https://github.com/JuliaGraphics/Gtk.jl/issues/647):
```
GTK_ORIG_ENV = ["GDK_PIXBUF_MODULE_FILE" => nothing]
withenv(GTK_ORIG_ENV...) do ; run(`emacs`) ; end
```
It would be nice if the same facility also existed in [`Base.addenv`](https://docs.julialang.org/en/v1/base/base/#Base.addenv), such that the above line could be written in a more thread-safe (side-effect free) way as
```
run(addenv(`emacs`, GTK_ORIG_ENV...; inherit=true))
```

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/43271
