### ISSUE TITLE
`Threads.nthreads()` returns the wrong number cores on M1 Pro using `auto`

### ISSUE THREAD

**Issue by samo76** [JuliaLang/julia#45974]
Using the number of threads in Julia, I get the following:
```shell
$ julia -t auto -e "println(Threads.nthreads())"
8
```

Using `sysctl`:
```shell
$ sysctl -n hw.ncpu
10
```

version info:
```julia
julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = auto
```

This might be a design decision to only use the 8 performance code (virtual cores) instead of all 10 cores available on the M1 Pro. That being said, Is there a way for `auto` to be interpreted as 10 instead of 8?

**Comment by giordano** [comment]
> This might be a design decision to only use the 8 performance code (virtual cores) 

It is: #44072

> That being said, Is there a way for auto to be interpreted as 10 instead of 8?

You mean besides not using `auto`? What's your use case for oversubscribing the CPU?

**Comment by samo76** [comment]
> It is: https://github.com/JuliaLang/julia/pull/44072
Got it. Thank you. I was certain someone else would pick up on this issue before me.
> You mean besides not using auto? What's your use case for oversubscribing the CPU?
How is this oversubscribe the CPU? Does not the M1 pro have 10 cores (8P + 2E)? If `auto` is to set the maximum number of available CPU resources then 10 should be the sweet spot.
P.S.: I am not a CPU architecture expert so I might be missing something here. 🙂

**Comment by giordano** [comment]
> How is this oversubscribe the CPU?

The performance-efficiency cores architecture used by Apple is similar to the [ARM big.LITTLE](https://en.wikipedia.org/wiki/ARM_big.LITTLE) architecture, trying to use more cores than the performance ones is effectively akin to oversubscribing all CPUs.  Many users reported general slowdown when using more cores than the performance ones, which is precisely the reason why `auto` uses only those ones.  See for example https://github.com/JuliaLang/julia/issues/36617#issuecomment-853374195
