### ISSUE TITLE
Wrong version of package can get up getting loaded if environment is not fully instantiated

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#45977]
Code loading contains two steps.:

- Identify the UUID of the package getting loaded. For example, if `Parsers` is loaded into Main, we check that there is a `[deps]` entry with `Parsers` in the current project and we find the UUID from there.
- Find the location of the package. This goes through all the environments and looks for a manifest that contains the UUID from above and computes the path.

The issue occurs when (for some reason) the source files of the package are not present for the package in the active environment. Code loading will then keep looking into manifests lower into the stacked env, and if it finds one, it breaks reproducibility. Here is an example:

```
using Pkg
using TOML
getversion(pkgpath) = TOML.parsefile(abspath(pkgpath, "..", "..", "Project.toml"))["version"]

# Add Parsers at version 1.0 in the global env
Pkg.add(name = "Parsers", version = "1.0")
@show getversion(Base.find_package("Parsers"))

# Add Parsers at version 2.0 in a temp env
Pkg.activate(; temp=true)
Pkg.add(name = "Parsers", version = "2.0")
@show getversion(Base.find_package("Parsers"))

# Now, remove the Parsers version 2.0 from the file system, this is equivalent to not having a fully instantiated manifest
# which `Pkg.status` shows:
rm(abspath(Base.find_package("Parsers"), "..", ".."); recursive=true)
Pkg.status()

# At this point, `find_package´ finds the Parsers.jl in the global environment which is at the wrong version
# Doing a `using Parsers` would load an inconsistent version with the current manifest.
@show getversion(Base.find_package("Parsers"))
using Parsers # now loads the wrong version
```

Note that this is not the same as when we load something like a dev-package from the shared env where it ends up loading dependencies at versions of the currently active environment. It is more the opposite.

So the bug here is that the package that ends up getting loaded depends on what happens to be installed in the depot.

**Comment by DilumAluthge** [comment]
This only occurs when `length(Base.LOAD_PATH) != 1`, right?

**Comment by KristofferC** [comment]
Yes, there needs to be another environment to find the package in.

I think a possible tweak to code loading to fix this could be that a package cannot be `locate`d in an environment that is lower in the load path than where it was `identify`ied.

**Comment by KristofferC** [comment]
Here is another slightly related issue. If you edit the Project.toml file by hand (e.g. by adding a package) then you might load a package at a lower environment until you have updated the manifest:

```
# Add Parsers at version 1.0 in the global env
Pkg.add(name = "Parsers", version = "1.0")

Pkg.activate(; temp=true)

# Manually add Parsers as a dep (with some compat)
write(Base.active_project(),
       """
       [deps]
       Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"

       [compat]
       Parsers = "2.0"
       """
)

# The manifest is not updated but code loading will find Parser 1.0 in the global env and load that.
using Parsers
```

**Comment by DilumAluthge** [comment]
> If you edit the Project.toml file by hand (e.g. by adding a package) then you might load a package at a lower environment until you have updated the manifest:

IIRC, on the latest Pkg master, the manifest file stores a hash of the project file, right? So perhaps code loading could check for a hash mismatch? This would catch the cases where the project file and the manifest file are out of sync.
