### ISSUE TITLE
presence of unreachable code causes macro created variables to become undefined

### ISSUE THREAD

**Issue by mind6** [JuliaLang/julia#45989]
I found an issue that may not be serious for most users, but perhaps it's pointing to compiler behavior that can result in more serious problems.  The error is reproducible in versions 1.7.3 and 1.8RC1.

This is the minimal example I made.

```julia
module A
    macro define(var)
        quote
            local sym = Symbol($var)
            $(__module__).eval(:($sym = 1234))
        end
    end
end

module B
    import ..A
    function run_succeed()
        A.@define "x"
        println("x in B is: ", x)
    end

    function run_succeed2()
        if false x = 6789 end
        A.@define "x"
        println("B.x is: ", B.x)
    end

    function run_fail()
        if false x = 6789 end
        A.@define "x"
        println("x in B is now: ", x)
    end
end
# versioninfo()
B.run_succeed()
B.run_succeed2()
B.run_fail()
```
`A.@define` takes a String, and defines a variable of that name in the caller's global module scope. This is the output I get:

```
x in B is: 1234
B.x is: 1234
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] run_fail()
   @ Main.B ellided...\bug_varundef.jl:26
 [2] top-level scope
   @ ellided...\bug_varundef.jl:32
```

The presence of the line `if false x = 6789 end` caused `x` to be undefined when accessing it without the module qualifier. But access is okay when qualified as `B.x`.

The reason I have the unreachable code is to help the vscode linter avoid warnings. There are simple workarounds for this issue, but I wonder why the compiler is being influenced by the presence of unreachable code?

**Comment by vtjnash** [comment]
That is simply how normal eval and scope rules works, and not anything to do with macros. You could use a function instead of a macro there, and your program would be much clearer

**Comment by mind6** [comment]
> That is simply how normal eval and scope rules works, and not anything to do with macros. You could use a function instead of a macro there, and your program would be much clearer

But `B.run_succeed()` works. The only difference is the one unreachable line of code from `B.run_fail()`. You can try to use differently names variables for each function, and see the same behavior.  Having `if false x = 6789 end` either before or after the `A.@define` call, causes x to be invisible.

**Comment by vchuravy** [comment]
Take a look at https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Local-Scope especially the `sum_to_def_closure(n)` example.

> The entire enclosing local scope is parsed and its locals determined before inner local meanings are resolved.


You can use `@macroexpand` to understand the effect of your macro. 

```
function run_succeed2()
        if false x = 6789 end
        local x = x
    end
```

By assigning to `x` in your branch you create a new local scope variable x that shadows the global one, then your `x = x` finds that shadowed definition instead of using the global scope one.
