### ISSUE TITLE
Translate Julia Doc To Persian

### ISSUE THREAD

**Issue by MahanBi** [JuliaLang/julia#45995]
### Discussed in https://github.com/JuliaLang/julia/discussions/45994

<div type='discussions-op-text'>

<sup>Originally posted by **MahanBi** July 11, 2022</sup>
Hello.
I want to translate Julia's document into Farsi language.
I wanted to know if it is possible for the translation to be available on the original document?
Or otherwise, how can I make it available to those interested?</div>

**Comment by MahanBi** [comment]
Thank you for replying.
The Persian translation is old. And I want to create a complete and updated translation and I will also register a domain for it.
Hopefully one day I can contribute to the main repository.

**Comment by ViralBShah** [comment]
I believe you should be able to pick up from the work that had been done in the other repo and submit a PR to the julia website when you have an updated version.

For now, we'll close this issue.

**Comment by fredrikekre** [comment]
See also #43098, https://github.com/JuliaDocs/Documenter.jl/issues/297, https://github.com/JuliaDocs/Documenter.jl/issues/658, https://github.com/JuliaDocs/Documenter.jl/issues/977.

Note that the current English documentation are hosted in a `/en` subdirectory already, so translations can be included into docs.julialang.org.

**Comment by ViralBShah** [comment]
The challenge has always been keeping the translations in sync with new releases. In the case of Chinese, for example, we have https://cn.julialang.org.
