### ISSUE TITLE
Peer inside an abstract parametric type

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#46047]
In the master branch of `DataStructures.jl`, the constructors for `SortedDict` and `SortedMultiDict` need to copy the data three times in order to deduce the key and value types in the case that the caller does not explicitly specify them.  Here is the relevant code from https://github.com/JuliaCollections/DataStructures.jl/blob/master/src/sorted_dict.jl :
```
function SortedDict(o::Ordering, kv)
    c = collect(kv)
    if eltype(c) <: Pair
        c2 = collect((t.first, t.second) for t in c)
    elseif eltype(c) <: Tuple
        c2 = collect((t[1], t[2]) for t in c)
    else
        throw(ArgumentError("In SortedDict(o,kv), kv should contain either pairs or 2-tuples"))
    end
    SortedDict{eltype(c2).parameters[1], eltype(c2).parameters[2], typeof(o)}(o, c2)
end
```
The reason for copying three times is as follows.  Suppose the routine is called with an iterable of `Pair` types, e.g., a tuple of them:  `SortedDict((1=>"a", 2=>7))`.  Here is what comes out for `c` and `c2`:
```
julia> c = collect((1=>"a", 2=>7))
2-element Vector{Pair{Int64}}:
 1 => "a"
 2 => 7

julia> c2 = collect((t.first, t.second) for t in c)
2-element Vector{Tuple{Int64, Any}}:
 (1, "a")
 (2, 7)

```
The issue is that `c` is a vector of an abstract parametric type `Pair{Int}`, so there is no documented method to discover its eltype's parameters.  So the code has to copy the data again into `c2` in order to get a vector of a nonabstract parametric type `Pair{Int,Any}` from which the parameters can be discovered using the documented `parameters` field.

Thus, I could elide one copy operation if I knew how to extract the parameters from `eltype(c)`.  Or, alternatively, my issue would be solved if `collect` applied to an iterable of `Pairs` always returned a vector of a nonabstract parametric type (like `Vector{Pair{Int64,Any}}`).  Possibly the reader may think of another way to elide the extra copy operation.

**Comment by JeffBezanson** [comment]
See the `dict_with_eltype` function in Base for an example of what we do there. Also, I think the first `collect` can be dropped right away, i.e. the first part of the function can be replaced with
```
c2 = collect((t[1], t[2]) for t in kv)
```
since Pairs also support indexing. In Base, we then elide this copy by checking `eltype(kv)` first. If that gives you a concrete Pair or Tuple type you can skip the `collect` entirely.
