### ISSUE TITLE
julialang2 bucket permission denied when syncing from downstream mirror sites

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [JuliaLang/julia#46070]
[Some mirror sites](https://mirrorz.org/list/julia-releases) have mirrored `s3://julialang2` and they recently failed to sync the data due to permission error

```
download failed: s3://julialang2/bin/musl/x64/1.8/julia-1.8.0-rc2-musl-x86_64.tar.gz to julia-releases/bin/musl/x64/1.8/julia-1.8.0-rc2-musl-x86_64.tar.gz An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

`s3://julialang2/bin/musl/x64/1.8/julia-1.8.0-rc2-musl-x86_64.tar.gz` seems the only file that has problems.

cc: @staticfloat @ararslan @johnnychen94

Ref to #36985

**Comment by staticfloat** [comment]
Should be fixed now!

**Comment by ZenithalHourlyRate** [comment]
> Should be fixed now!

Confirmed, thanks!

**Comment by ararslan** [comment]
Sorry about that. Since v1.8.0-rc2 was never actually released, the binaries weren't fully set up in terms of permissions and whatnot.

**Comment by ZenithalHourlyRate** [comment]
Hi, the same kind of problem happened again

```
download failed: s3://julialang2/bin/winnt/x86/1.9/julia-1.9.0-beta1-win32.tar.gz to ../../data/mirrors/julia-releases/bin/winnt/x86/1.9/julia-1.9.0-beta1-win32.tar.gz An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

**Comment by DilumAluthge** [comment]
Yeah, we never actually finished releasing 1.9-beta1 due to some issues with it. So you can skip 1.9-beta1 and go straight to 1.9-beta2.

**Comment by ZenithalHourlyRate** [comment]
> Yeah, we never actually finished releasing 1.9-beta1 due to some issues with it. So you can skip 1.9-beta1 and go straight to 1.9-beta2.

We downstream mirrors actually just call `s3 sync` in our [syncing script](https://github.com/tuna/tunasync-scripts/blob/e9ba23c25885bf18afe64146e9e8e4d3920b292b/s3.sh#L11). It is inconvenient for us to add exclude list every time this kind of issues happen.

**Comment by giordano** [comment]
It is also inconvenient for other people to change in-place existing tags.  There are [discussions](https://github.com/JuliaLang/julia/issues/48025) to avoid skipping tags because publishing failed at a later stage, but you'll have to live with the possiblity not all tags will have an actually "published" version.

**Comment by johnnychen94** [comment]
> Yeah, we never actually finished releasing 1.9-beta1 due to some issues with it. So you can skip 1.9-beta1 and go straight to 1.9-beta2.

This doesn't seem like an atomic operation to me; the public s3 bucket should contain either a public readable object, or it doesn't contain it.

Let's say, manually modifying the permission of these broken release binaries as a fixup. Is there any problem doing this?

**Comment by staticfloat** [comment]
I've updated that file to have readable permissions.  Sorry for the wait on this.

I agree, we should keep the S3 bucket all readable.

**Comment by ZenithalHourlyRate** [comment]
> I've updated that file to have readable permissions.

Confirmed, thanks!
