### ISSUE TITLE
Ability to turn on and off scalar indexing for sparse matrices?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#46080]
`A[i,j] = ...` is very slow if `A isa SparseMatrixCSC`. In the wild, there's another case like this with CUDA.jl. In that package, it allows for doing `CUDA.allowscalar(false)` so that any `A[i,j]` operation (`getindex` and `setindex!`) causes an error to be thrown. This is helpful for finding unoptimized fallbacks which would otherwise "work" given the AbstractArray interface, but would be detrimental to performance. Without this, finding out which CUDA codes are hitting unwanted fallbacks can only be done by profiling.

It would be nice to have similar functionality available on SparseMatrixCSC. I am not sure I like the idea of having it global though, since then it's global, but if it's not global you need rules for how to carry it forward with broadcast etc. which might be hard to do in general and so the global is the easy option.

**Comment by ViralBShah** [comment]
Should be filed in SparseArrays.jl

**Comment by ChrisRackauckas** [comment]
Can you do a transfer? I didn't know that was a separate repo now.

**Comment by ChrisRackauckas** [comment]
Oh it's a different org, so it can't transfer the issue?

**Comment by ViralBShah** [comment]
Moved to https://github.com/JuliaSparse/SparseArrays.jl/issues/189
