### ISSUE TITLE
P.k.g. phone home

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4609]
It would be nice to have some way of knowing what packages people are using and some way of estimating Julia installs. We could potentially achieve this by having `Pkg` phone home when doing `Pkg.update` – i.e. send a list of installed packages and system version info to a server for logging. I wouldn't want to do that in any underhanded, sneaky sort of way, but opt-in doesn't seem likely to generate much data. Any thoughts on this? Good idea, bad idea? How would we do it in a way that's transparent and not sneaky but is likely to get us a reasonable amount of representative data? Note that while we don't currently have any way of getting this information, GitHub already does since they know what users and IP addresses are doing `git pull` against `METADATA.jl`. So in principle, this is already information users are sharing – just not with us.

**Comment by tkelman** [comment]
@StefanKarpinski why was this closed? Incorporating some form of usage analytics in Pkg3 would be a good idea if possible.

**Comment by StefanKarpinski** [comment]
Sure, but I don't we need an issue for that. We can reopen if you like.

**Comment by tkelman** [comment]
If Pkg3 ends up being developed primarily in a separate repo we can move it to a new issue there.
