### ISSUE TITLE
`lu!` for `Tridiagonal` incurs allocations

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaLang/julia#46099]
It seems that `lu!` for `Tridiagonal` incurs allocations [here](https://github.com/JuliaLang/julia/blob/808ad85ba1e48cdc549d00aebfe4b75063d1eb5b/stdlib/LinearAlgebra/src/lu.jl#L526).

Can we cache this vector to make `lu!` allocation-free? Discovered [here](https://github.com/CliMA/ClimaAtmos.jl/issues/648).

**Comment by stevengj** [comment]
Maybe we could add a method `lu!(F::LU, A::AbstractMatrix)` that takes a pre-existing factorization object `F` and overwrites it with the factorization of `A` (a matrix of the same size).   That way we could re-use all of the storage.
