### ISSUE TITLE
Nested generator captures binding for infinite recursion

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#46106]
MWE:

```julia
julia> function foo(f) 
          f = (Symbol(x, y) for x in f for y in f)
          return collect(f)
       end
foo (generic function with 1 method)

julia> foo((1,2,3,4))
ERROR: StackOverflowError:
Stacktrace:
      [1] (::var"#18#19")(x::Int64)
        @ Main ./none:0
      [2] iterate
        @ ./generator.jl:47 [inlined]
      [3] iterate
        @ ./iterators.jl:1176 [inlined]
      [4] iterate(f::Base.Iterators.Flatten{Base.Generator{NTuple{4, Int64}, var"#18#19"}})
        @ Base.Iterators ./iterators.jl:1172
      [5] iterate
        @ ./generator.jl:44 [inlined]
      [6] iterate
        @ ./iterators.jl:1178 [inlined]
--- the last 3 lines are repeated 37388 more times ---
 [112171] iterate
        @ ./iterators.jl:1172 [inlined]
 [112172] grow_to!(dest::Vector{Symbol}, itr::Base.Iterators.Flatten{Base.Generator{NTuple{4, Int64}, var"#18#19"}})
        @ Base ./array.jl:857
 [112173] _collect
        @ ./array.jl:761 [inlined]
 [112174] collect(itr::Base.Iterators.Flatten{Base.Generator{NTuple{4, Int64}, var"#18#19"}})
        @ Base ./array.jl:709
 [112175] foo(f::NTuple{4, Int64})
        @ Main ./REPL[8]:3
```

I would have expected this to return

```julia
julia> foo((1,2,3,4))
16-element Vector{Symbol}:
 Symbol("11")
 Symbol("12")
 Symbol("13")
 Symbol("14")
 Symbol("21")
 Symbol("22")
 Symbol("23")
 Symbol("24")
 Symbol("31")
 Symbol("32")
 Symbol("33")
 Symbol("34")
 Symbol("41")
 Symbol("42")
 Symbol("43")
 Symbol("44")
```

Notably, this does not happen with something like this:

```julia
julia> f(f) = (Symbol(x, y) for x in f for y in f)
f (generic function with 1 method)
```

which is why I think it happens due to the shadowing. My versioninfo is

```
julia> versioninfo()
Julia Version 1.9.0-DEV.991
Commit 707f59b980 (2022-07-17 18:14 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

but it's been [reported](https://julialang.zulipchat.com/#narrow/stream/330470-graphics-programming/topic/graphics.20math.20library/near/290135769) to have the same behavior on 1.8-rc3.

**Comment by Seelengrab** [comment]
This is correct behavior; capturing always works based on the binding, not the object. In this case, this results in the generator capturing itself, resulting in the stackoverflow.

**Comment by JeffBezanson** [comment]
I thought this was correct, but I guess the weird thing is that e.g. `(Symbol(x) for x in f)` works as the OP expects, since it just constructs a Generator object that captures the current value of `f`. But if you nest it in another Generator (plus Flatten), it gets wrapped in a function and one of the accesses to `f` is deferred. I'm not sure we can do anything about it, since the inner loop does need to be evaluated inside the scope of the outer loop.

**Comment by Seelengrab** [comment]
My reasoning for why I think this shouldn't stackoverflow is that at the time either function for the generators is created/the anonymous function is instantiated, `f` is not yet reassigned. So both should capture the value of `f` before either generator is defined, instead of capturing the intermediate.
