### ISSUE TITLE
Effect override for `@ccall` is broken on master

### ISSUE THREAD

**Issue by N5N3** [JuliaLang/julia#46122]
MWE
```julia
julia> get_ptr(a) = Base.@assume_effects :effect_free @ccall jl_array_ptr(a::Any)::Ptr{Int}
get_ptr (generic function with 1 method)

julia> get_ptr([])
Internal error: encountered unexpected error in runtime:
ErrorException("type Effects has no field terminates_globally")
......
```
Should be introduced in #46034.
https://github.com/JuliaLang/julia/blob/76d56ff59a6d356e1885ab970e0a7483d29a9ccb/base/compiler/abstractinterpretation.jl#L2068-L2076

**Comment by Keno** [comment]
That should just be `effects.terminates` rather than `effects.terminates_globally` (only the overrides distinguish between global and local, for effects, it always means global). Want to submit a PR and a test?
