### ISSUE TITLE
Round number issues

### ISSUE THREAD

**Issue by Jacky-lim-data-analyst** [JuliaLang/julia#46142]
![round_number](https://user-images.githubusercontent.com/84822819/180458343-14c7958a-cae7-44d9-936a-70c314292fa7.PNG)

**Comment by oscardssmith** [comment]
this is correct. Julia by default uses rounding with ties rounded to even.

**Comment by mikmoore** [comment]
For additional info, see [Julia's supported rounding modes](https://docs.julialang.org/en/v1/base/math/#Base.Rounding.RoundingMode). As was stated, the default is `RoundNearest` (with ties to even). It sounds like you want either `RoundNearestTiesAway` or `RoundNearestTiesUp`, e.g.
```
julia> round(6.5,RoundNearestTiesAway)
7.0
```
