### ISSUE TITLE
CI: New Intermittent segfault

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#46152]
We appear to have a new intermittent segfault on CI. I regularly see `ProcessExited(139)` on macos builders, but it's possible that failures on various other systems are also related. See below for a table of recent macos logs that failed with this error. Looks like this might have started around Jul 4 or so.

<details>
  <summary>Table of recent ProcessExited(139) failures</summary>
  

<div class="data-frame"><p>12 rows × 9 columns</p><table class="data-frame"><thead><tr><th></th><th>agent</th><th>commit</th><th>date</th><th>elapsed</th><th>key</th><th>log_url</th><th>state</th><th>uuid</th><th>web_url</th></tr><tr><th></th><th title="String">String</th><th title="String">String</th><th title="DateTime">DateTime</th><th title="Float64">Float64</th><th title="String">String</th><th title="String">String</th><th title="String">String</th><th title="UUID">UUID</th><th title="String">String</th></tr></thead><tbody><tr><th>1</th><td>default-macmini-x64-5.0</td><td>743578abb10fdda7d0087748f648a455d7643e88</td><td>2022-07-22T05:11:28.008</td><td>4911.28</td><td>test_x86_64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/14170/jobs/01822451-f8cd-43a7-a4b4-83d37d4236e4/log.txt</td><td>failed</td><td>01822451-f8cd-43a7-a4b4-83d37d4236e4</td><td>https://buildkite.com/julialang/julia-master/builds/14170#01822451-f8cd-43a7-a4b4-83d37d4236e4</td></tr><tr><th>2</th><td>default-macmini-x64-5.0</td><td>028e9ff8d39a48aee5f4db1cd255af7fe729e3bb</td><td>2022-07-20T15:15:51.024</td><td>8267.88</td><td>test_x86_64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/14094/jobs/01821c2e-dd00-4443-89d2-a1f346cf8bda/log.txt</td><td>failed</td><td>01821c2e-dd00-4443-89d2-a1f346cf8bda</td><td>https://buildkite.com/julialang/julia-master/builds/14094#01821c2e-dd00-4443-89d2-a1f346cf8bda</td></tr><tr><th>3</th><td>default-macmini-aarch64-1.0</td><td>e96b19d096c45fec5e5d3f0d62a9b5f2a7b2428b</td><td>2022-07-14T18:22:37.245</td><td>4810.07</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13912/jobs/0181fdf3-8b9c-4341-b2a6-2301ec77ce8f/log.txt</td><td>failed</td><td>0181fdf3-8b9c-4341-b2a6-2301ec77ce8f</td><td>https://buildkite.com/julialang/julia-master/builds/13912#0181fdf3-8b9c-4341-b2a6-2301ec77ce8f</td></tr><tr><th>4</th><td>default-macmini-aarch64-1.0</td><td>9815a8ebccda13694685ba6f16667b6c89461c0b</td><td>2022-07-13T15:43:51.353</td><td>3703.01</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13836/jobs/0181f95e-1f7d-420f-b0c6-86a38d2872ad/log.txt</td><td>failed</td><td>0181f95e-1f7d-420f-b0c6-86a38d2872ad</td><td>https://buildkite.com/julialang/julia-master/builds/13836#0181f95e-1f7d-420f-b0c6-86a38d2872ad</td></tr><tr><th>5</th><td>default-macmini-aarch64-1.0</td><td>201d4f6715c908b736d8552d27afd1aaf6cfd400</td><td>2022-07-13T09:02:25.148</td><td>3797.28</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13824/jobs/0181f6cc-1f9e-40df-98e4-9858799342a9/log.txt</td><td>failed</td><td>0181f6cc-1f9e-40df-98e4-9858799342a9</td><td>https://buildkite.com/julialang/julia-master/builds/13824#0181f6cc-1f9e-40df-98e4-9858799342a9</td></tr><tr><th>6</th><td>default-macmini-x64-2.0</td><td>201d4f6715c908b736d8552d27afd1aaf6cfd400</td><td>2022-07-13T09:02:25.148</td><td>5804.43</td><td>test_x86_64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13824/jobs/0181f6cc-1dd9-4c19-a21b-8c1115c7933a/log.txt</td><td>failed</td><td>0181f6cc-1dd9-4c19-a21b-8c1115c7933a</td><td>https://buildkite.com/julialang/julia-master/builds/13824#0181f6cc-1dd9-4c19-a21b-8c1115c7933a</td></tr><tr><th>7</th><td>default-macmini-x64-2.0</td><td>c1d21e11a276ebf71b677076a064b5144c2e8f46</td><td>2022-07-13T07:32:31.174</td><td>5450.19</td><td>test_x86_64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13821/jobs/0181f679-cd57-41c5-b95e-853529344ad5/log.txt</td><td>failed</td><td>0181f679-cd57-41c5-b95e-853529344ad5</td><td>https://buildkite.com/julialang/julia-master/builds/13821#0181f679-cd57-41c5-b95e-853529344ad5</td></tr><tr><th>8</th><td>default-macmini-aarch64-2.0</td><td>87558f6da06beb3812cc72c2398ab2f854701d59</td><td>2022-07-08T19:40:26.457</td><td>4463.86</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13634/jobs/0181df54-7655-4fcd-97ec-5df1b9421462/log.txt</td><td>failed</td><td>0181df54-7655-4fcd-97ec-5df1b9421462</td><td>https://buildkite.com/julialang/julia-master/builds/13634#0181df54-7655-4fcd-97ec-5df1b9421462</td></tr><tr><th>9</th><td>default-macmini-aarch64-1.0</td><td>da13d78f9f689e7d761e3c149462c0a2b0dad54f</td><td>2022-07-07T08:37:50.394</td><td>2840.45</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13599/jobs/0181d7cf-7da6-4f17-8de0-b0a49c6ff550/log.txt</td><td>failed</td><td>0181d7cf-7da6-4f17-8de0-b0a49c6ff550</td><td>https://buildkite.com/julialang/julia-master/builds/13599#0181d7cf-7da6-4f17-8de0-b0a49c6ff550</td></tr><tr><th>10</th><td>default-macmini-aarch64-3.0</td><td>4d50ff87fac20ada6f32041927dd55907796bde3</td><td>2022-07-06T12:35:07.440</td><td>6386.15</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13567/jobs/0181d385-141c-436f-bfb9-4eb9af26a3d4/log.txt</td><td>failed</td><td>0181d385-141c-436f-bfb9-4eb9af26a3d4</td><td>https://buildkite.com/julialang/julia-master/builds/13567#0181d385-141c-436f-bfb9-4eb9af26a3d4</td></tr><tr><th>11</th><td>default-macmini-aarch64-4.0</td><td>438bde4b8cd85188e71da585324e280b7b5b43ad</td><td>2022-07-04T19:45:11.110</td><td>5068.01</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13491/jobs/0181cac1-34d3-4c25-9a6c-c7a7d39352fc/log.txt</td><td>failed</td><td>0181cac1-34d3-4c25-9a6c-c7a7d39352fc</td><td>https://buildkite.com/julialang/julia-master/builds/13491#0181cac1-34d3-4c25-9a6c-c7a7d39352fc</td></tr><tr><th>12</th><td>default-macmini-aarch64-5.0</td><td>fec6951a8b2e11a2560d13c1b995874bff561aa5</td><td>2022-06-30T17:21:33.759</td><td>4715.9</td><td>test_aarch64-apple-darwin</td><td>https://api.buildkite.com/v2/organizations/julialang/pipelines/julia-master/builds/13360/jobs/0181b5a2-791b-4ec9-a4fe-6c7aec87d849/log.txt</td><td>failed</td><td>0181b5a2-791b-4ec9-a4fe-6c7aec87d849</td><td>https://buildkite.com/julialang/julia-master/builds/13360#0181b5a2-791b-4ec9-a4fe-6c7aec87d849</td></tr></tbody></table></div>
</details>

**Comment by Keno** [comment]
The commit before that first failure was the merge of #45861. @vtjnash any chance that's related?

**Comment by vtjnash** [comment]
Is that the `atexit` hook test failing? I think someone did change that recently (https://github.com/JuliaLang/julia/pull/45765). I think that test pattern might be still expected to fail sometimes if you are running if threads are forced on, so can we please stop doing that in CI?

**Comment by giordano** [comment]
> I think someone did change that recently (https://github.com/JuliaLang/julia/pull/45765).

That'd match the the fact the first failing job was found on June 30th: the PR was merged the day before.

**Comment by Keno** [comment]
The test that's failing is not the one that was added in that PR though. It's usually either the `sysimg-code-native=no` test or one of the LibGit2 tests.

**Comment by vtjnash** [comment]
Both would be very likely to fail if the PR was incompletely fixing the issue, and if people keep configuring CI to run with threads (which is not supported yet)

**Comment by DilumAluthge** [comment]
> and if people keep configuring CI to run with threads (which is not supported yet)

https://github.com/JuliaCI/julia-buildkite/pull/185

**Comment by Keno** [comment]
Appears to have been resolved by turning off threading.
