### ISSUE TITLE
[improper @assume_effects usage] is segfaulting ok as undefined behaviour?

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#46155]
MWE for my case:
```julia
struct Construct end
Construct(o) = checkcompliance(typeof(o))

Base.@assume_effects :foldable checkcompliance(::Type{T}) where T = hasmethod(Base.iterate, Tuple{T}) || error()

struct Empty end
try
    Construct(Empty())
catch
end
Base.iterate(iter::Empty) = nothing
Construct(Empty()) #result
```
further testing made me understand that hasmethod/checkcompliance won't get an update when Base.iterate changes. So it should still error. Without the assume_effects the (correct) result is `true`. But I don't get why, instead of wrongly but "gracefully" erroring, it just segfaults.

**Comment by Keno** [comment]
> is segfaulting ok as undefined behaviour?

Yes

```
  │ Warning
  │
  │  Improper use of this macro causes undefined behavior (including crashes, incorrect answers, or other hard to
  │  track bugs). Use with care and only if absolutely required.
```

> further testing made me understand that hasmethod/checkcompliance won't get an update when Base.iterate changes

Yes, this in particular violates `:consitent`-cy. There could be a version of `hasmethod` that is fixed to the executing world-age, but you'd still need to get the backedge in somehow.

**Comment by rapus95** [comment]
@Keno so world age does only increase if there are backedges and `hasmethod` doesn't create such a backedge and thus defining the new method doesn't update the world age and thus consistency is violated. Is that right?

**Comment by Keno** [comment]
hasmethod has an implicit query about the current most recent world age:
```
hasmethod(f, t::Type{<:Tuple}[, kwnames]; world=get_world_counter())
```
However, even if that were fixed, there's some subtleties around the interaction of the :consistent annotation with backedges (#46156).
