### ISSUE TITLE
get rid of test_approx_eq_*

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4615]
These are not really fundamental testing primitives and should be replaced with `@test isapprox(...)` or something similar.

**Comment by stevengj** [comment]
Given #12472, you can now do `@test foo ≈ bar` and you will get the nice test output, as long as you are happy with the default tolerance.

It would be easy to update the `@test` macro to look for `@test isapprox(...)` too, for the cases where a non-default tolerance is used.

**Comment by kshyatt** [comment]
@StefanKarpinski didn't your great Regex-fest (mostly) do this?

**Comment by tkelman** [comment]
They're not used much in base any more, but they should be deprecated to really close this if we want to finish getting rid of them all the way.

**Comment by timholy** [comment]
Related: #15477

**Comment by IainNZ** [comment]
I really did want to kill these during the at-testset change, but failed to find a solution I liked at the time.

**Comment by StefanKarpinski** [comment]
Bump?

**Comment by stevengj** [comment]
A good solution would be to recognize `@test isapprox(...)` and give extra output for it (e.g. the two things being compared, and the relative error encountered vs. the error tolerance requested).

**Comment by StefanKarpinski** [comment]
I have a PR for most of this (https://github.com/JuliaLang/julia/pull/19901), the remaining special printing of failures for `@test a ≈ b` is split out into https://github.com/JuliaLang/julia/issues/19898, which can be handled whenever since it's just a display improvement.

**Comment by KristofferC** [comment]
This is done
