### ISSUE TITLE
something strange in LinearAlgebra.LAPACK

### ISSUE THREAD

**Issue by liushang0322** [JuliaLang/julia#46160]
first of all,here is my version information:
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = C:\Users\Public\TongYuan\.julia;D:\内核技术组\julia\Syslab基础数学库负责\015-内部
事项\版本测试\.julia;
  JULIA_DIR = D:\MWorks.Syslab 2022\Tools\julia-1.7.0
  JULIA_NUM_THREADS = 6
  TY_JULIA_DEPOT_PATH = C:\Users\Public\TongYuan\.julia;D:\内核技术组\julia\Syslab基础数学库负责\015- 
内部事项\版本测试\.julia;
  JULIA_EDITOR = code

I am using the LinearAlgebra.LAPACK.gelsy! function to try to benchmark lsqminnorm in MATLAB. The following is the code I wrote, but when faced with the second example in the matlab help document, it has changed dramatically. May I ask this What's causing it, I don't think gelsy! will give me such an undesired result, is there a problem, please let me know

function lsqminnorm(A, B, tol = nothing; rankWarn::String = "nowarn")
    if isa(A, Number)
        A = [A]
    end
    if isa(B, Number)
        B = [B]
    end
    if eltype(A) <: Integer
        A = A .* 1.0
    end
    if eltype(B) <: Integer
        B = B .* 1.0
    end

    if rankWarn == "warn"
        rankA = rank(A)
        if rankA < minimum(size(A))
            @warn "Warning: Rank deficient, rank = $rankA, tol =  $tol."
        end
    end
    b = copy(B)
    if isnothing(tol)
        return LAPACK.gelsy!(A, b)[1]
        # return B
    else
        return LAPACK.gelsy!(A,b,tol)[1]
        
    end
end

here is the example ：https://www.mathworks.com/help/releases/R2022a/matlab/ref/lsqminnorm.html

**Comment by N5N3** [comment]
`LAPACK.gelsy!` will overwrite `A` to store the QR result. You need to `copy(A)` manually for float input.

**Comment by liushang0322** [comment]
> `LAPACK.gelsy!` will overwrite `A` to store the QR result. You need to `copy(A)` manually for float input.

It may be that I have no knowledge and do not understand what you mean. Could you please modify my code and tell me how to get the correct solution?

**Comment by N5N3** [comment]
You didn't provide a complete julia MWE and the expected result. So I can only guess what you tested.
Just as mentioned above, your `lsqminnorm` will modify the input `A`.
```julia
A = [1. 2.; 3. 4.]
lsqminnorm(A, randn(2))
A == [1. 2.; 3. 4.] # false
```
you need call `LAPACK.gelsy!(copy(A), b)[1]` to avoid that.

**Comment by dkarrasch** [comment]
Is there anything actionable here, or can we close this? Perhaps a discussion over at [discourse](https://discourse.julialang.org/) is more appropriate?
