### ISSUE TITLE
Add a pass pipeline that runs only non-semantic passes

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#46181]
[On twitter](https://twitter.com/KenoFischer/status/1551691014146064384) there was a discussion that it would be useful to run our system image through Alive2 to detect any possible LLVM mis-optimizations (since our IR looks quite a bit different from clang). To this end, we would need a way to run only the passes that are non-semantic, i.e. preserve LLVM IR semantics.

@pchintalapudi could you take a look at this after/as part of the NewPM transition work? Should be fairly quick I imagine.

**Comment by pchintalapudi** [comment]
How different is this from just running with a default optimization level of -O0? Judging by the pass pipelines the only non-required pass at O0 that we run is a single round of simplifycfg early on in the pipeline.

**Comment by Keno** [comment]
I guess we already have the `lower_intrinsics` options, which is basically what I want, except that it still runs the `createRemoveNIPass` and `createLowerSimdLoopPass`, except that I also want it exposed as a pass option that I can pass to `opt` (which it currently isn't). The use case here is to verify LLVM itself using Alive2. For this, we cannot run any passes (e.g. the ones I mentioned, but more prominently things like GC lowering), that would not be legal for LLVM to perform directly in the optimizer (i.e. passes that require frontend-specific knowledge). What I need is basically a pass ordering that I can pass to `opt`, but that does not run any of the passes that come from Julia. Of course that IR won't be legal to generate assembly for, but it'll be good enough to run Alive2 on.

**Comment by pchintalapudi** [comment]
If we're looking for just LLVM passes, then could we work with just dumping the totally unoptimized sysimg module? I see `jl_dump_native` has an unopt_bc_filename argument, which will throw all of the raw codegen-ed modules into a bitcode file without running any of our passes on it. If we then provide just a string list of passes to opt, would that meet the alive2 use-case?

Side note, at some point I was exploring how this sysimg was generated and discovered it's primarily a module with ~50k functions in it. Is alive2 capable of handling that kind of massive module?

**Comment by Keno** [comment]
> If we're looking for just LLVM passes, then could we work with just dumping the totally unoptimized sysimg module?

Yes, the workflow here would be dumping the unoptimized module, and then running `opt -load libjulia.so -julia-nonsematnic` (like we would do with `-julia`, but dropping the semantic passes). Obviously this could be done with a string list of passes, but that doesn't necessarily reproduce what the julia pass pipeline actually does, and we have the plugin infrastructure, so we might as well use it. The action item here is to expose that pass list to opt (as we do with "julia", "juliaO2", etc right now).

> Side note, at some point I was exploring how this sysimg was generated and discovered it's primarily a module with ~50k functions in it. Is alive2 capable of handling that kind of massive module?

I don't know, but I'll let that be the Alive2 developers' problem :)
