### ISSUE TITLE
`b"\\\\" == b"\\"`, is this intended?

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#46243]
Currently, we have
```
julia> b"\\\\" == b"\\"
true
```

Which I can't understand. Something adjecant is mentioned in the manual here: https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals,
but this does not really cover why `length(b"\\\\") == 1`.

**Comment by simeonschaub** [comment]
Looks like backslashes here get unescaped twice, once in the parser and once when `unescape_string` is called inside `@b_str`. Somewhat related to #41041

**Comment by mgkuhn** [comment]
Duplicate of #39092, where I provide a detailed explanation of what happens.

**Comment by vtjnash** [comment]
It would probably be good to fix this, but breaking
