### ISSUE TITLE
use \ to solve A*x = b maybe something strange?

### ISSUE THREAD

**Issue by liushang0322** [JuliaLang/julia#46265]
Sorry to bother you, I am trying to use \ to solve the following problem
A = [16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]
b = [34;34;34;34]
x = A\b
The solution I get is
4-element Vector{Float64}:
  1.6527777777777778
  2.9583333333333335
 -0.9583333333333334
  0.3472222222222223

Below is my version

Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = C:\Users\Public\TongYuan\.julia
  JULIA_DIR = D:\MWorks.Syslab 2022\Tools\julia-1.7.0
  JULIA_NUM_THREADS--= 0x00000000000000001

The point is that my friends and I are getting different results

Their result is

4-element Vector{Float64}:
  1.5
  2.5000000000000004
 -0.5000000000000004
  0.5

Of course I understand very well that this is all true, what I want to know is why

Please let me know if it is convenient for you, thank you very much

**Comment by oscardssmith** [comment]
These are both correct answers. For both of them, `A*x=b` (up to floating point precision).

**Comment by liushang0322** [comment]
> These are both correct answers. For both of them, `A*x=b` (up to floating point precision).

I understand that they are all correct answers, but I am more curious about why there are different results, on almost the same machine

**Comment by oscardssmith** [comment]
Github is for bugs. Questions are better directed to other channels such as slack or discourse.
