### ISSUE TITLE
Calling external library with ccall issue

### ISSUE THREAD

**Issue by bakernp** [JuliaLang/julia#46263]
Hello,
I have written a Julia code that needs to perform a ccall to an external library. I have tried to produce such library in different ways, i.e. implementing it both in C and in Julia, and compiling it both on Windows (.dll) and on Linux (.so). However, I am getting always the same error: 

On Linux:
```
signal (11): Segmentation fault
in expression starting at none:0
unknown function (ip: (nil))
Allocations: 13865196 (Pool: 13860690; Big: 4506); GC: 14
```

On Windows:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
in expression starting at [...]\test.jl:39
unknown function (ip: 0000000000000000)
external_function at [...]\external_lib.dll (unknown line)
top-level scope at [...]\test.jl:39
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:876
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:830
jl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\toplevel.c:944
eval at .\boot.jl:373 [inlined]
include_string at .\loading.jl:1196
_include at .\loading.jl:1253
include at .\Base.jl:418
exec_options at .\client.jl:292
_start at .\client.jl:495
jfptr__start_34800.clone_1 at [...]\sys.dll (unknown line)   
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1788 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:559
jl_repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:701
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe.c:42
BaseThreadInitThunk at C:\windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 3171965 (Pool: 3170059; Big: 1906); GC: 3
```

Focusing on the external library written in Julia and built on Windows, I compiled it using Julia PackageCompiler, through the function create_library, as follows:
```
 create_library("path\\to\\project", "path\\to\\target_folder"; lib_name="external_lib", force=true)
```

In my Julia code, I then use the following lines to call it:
```
lib = Base.Libc.Libdl.dlopen("abs_path_to_external_library.dll")
const lib_sym = Base.Libc.Libdl.dlsym(lib, :external_function)
...
ccall(lib_sym, Tuple{Cdouble,Cdouble,Cdouble,Cdouble}, 
                (Cint, Cint, Cdouble, Cdouble, Cdouble, Cdouble), 
                in1, in2, in3, in4, in5, in6)
```

Hoping this is useful, I also printed lib and lib_sym values (it looks like the relative address between the two is correct):
```
lib = Ptr{Nothing} @0x0000000075240000
lib_sym = Ptr{Nothing} @0x00000000752413b0
```

I found some similar issues online (also on Julia Discours) but none of those were helpful (in particular, what I tried to do was to disable the garbage collector, to make the external library void and play with input types, and to add the input flags RTLD_NOW|RTLD_GLOBAL to dlopen). I also tried to investigate environment configuration issues but didn't find a solution.

Could you please look into this issue? 
Thanks a lot!

**Comment by mgkuhn** [comment]
I think you will have to give us a complete minimally working example of the C function that you call before we can give any advice. Something as small as possible that we can compile ourselves to reproduce your problem exactly.

Does your C function really return a struct containing four 64-bit float variables?

**Comment by Seelengrab** [comment]
Usage questions/help getting started is best directed to discourse.julialang.org first, until it's clear that an actual bug/issue is happening. As it stands, this is neither reproducible nor debuggable, so would go nowhere.
