### ISSUE TITLE
Installation issue: could not load library "libcholmod" - libblas.so.3

### ISSUE THREAD

**Issue by keflavich** [JuliaLang/julia#46287]
This failure prevents me from starting IJulia:

```
$ julia
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load library "libcholmod"
│    libblas.so.3: cannot open shared object file: No such file or directory
│    Stacktrace:
│     [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
│       @ Base.Libc.Libdl ./libdl.jl:117
│     [2] dlopen (repeats 2 times)
│       @ ./libdl.jl:117 [inlined]
│     [3] __init__()
│       @ SuiteSparse.CHOLMOD /blue/adamginsburg/adamginsburg/miniconda3/envs/python39/share/julia/stdlib/v1.7/SuiteSparse/src/cholmod.jl:161
└ @ SuiteSparse.CHOLMOD /home/conda/feedstock_root/build_artifacts/julia_1657861505506/work/usr/share/julia/stdlib/v1.7/SuiteSparse/src/cholmod.jl:245
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  https://github.com/conda-forge/julia-feedstock
|__/                   |

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d* (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-conda-linux-gnu)
  CPU: AMD EPYC 75F3 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
Environment:
  JULIA_SSL_CA_ROOTS_PATH = /orange/adamginsburg/miniconda3/envs/python39/ssl/cacert.pem
  JULIA_DEPOT_PATH = /orange/adamginsburg/miniconda3/envs/python39/share/julia:
  JULIA_PROJECT = @python39
  JULIA_PROJECT_BACKUP =
  JULIA_LOAD_PATH = @:@python39:@stdlib
  JULIA_DEPOT_PATH_BACKUP =
  JULIA_LOAD_PATH_BACKUP =
  JULIA_SSL_CA_ROOTS_PATH_BACKUP =

julia>
```
running on `Red Hat Enterprise Linux Server release 7.7 (Maipo)`

I originally got the error from doing
```julia
Pkg.add("IJulia")
```
but now see it every time at startup.

Based on [issue 32545](https://github.com/JuliaLang/julia/issues/32545), I checked that `LD_LIBRARY_PATH` (and other LD environmental variables) are not set.

I installed julia through conda using the conda-forge channel.

Is there some other missing set of libraries, or some other environmental variable, I should be checking?  Is it possible I've created this problem by trying to install incompatible packages?

**Comment by gbaraldi** [comment]
I will say it's quite likely related to being the conda install but I'm not super familiar how that build is arranged. @mkitti I believe is the one that made them work.
For now I would try using the official binaries to see if they work.

**Comment by keflavich** [comment]
Yeah, I'm afraid this might be a red herring - I hadn't realized, but installing julia with conda broke my python install - it appears to have deleted the lapack libraries.  I'm still hunting down that issue; I'll update this if I figure it out.

**Comment by keflavich** [comment]
OK, it looks like this was just a weird case of conda eating itself (probably because I tried to switch to mamba...)

This fixed it for me:
`conda install -c conda-forge -n python39 lapack liblapack libblas libcblas --force-reinstall`
the `--force-reinstall` was required as conda thought all of these were installed even though all of the `.so` files were missing.

I still can't get IJulia to work, but I think that's not this issue any more, so I'll post something over in IJulia.

**Comment by mkitti** [comment]
For Julia installed via conda-forge, please create an issue here:
https://github.com/conda-forge/julia-feedstock

Frankly, the first diagnostic step would always be to see if Julia works when you directly download it or use `juliaup` which should also be available via conda-forge.

conda-forge does not give us great control over dependencies, so it's a bit of an experiment.
