### ISSUE TITLE
`Threads.@threads` freezing on Apple M1 Pro Rosetta

### ISSUE THREAD

**Issue by efaulhaber** [JuliaLang/julia#46308]
I started Julia as
```
julia --threads=8
```
and ran this minimal example
```julia
n = 2000
Threads.@threads for _ in 1:20
    for x in 1:n, i in rand(x)
        nothing
    end
end
println("done")
```
on several builds on an Apple M1 Pro chip:
Setup 1:
```
julia> versioninfo()
Julia Version 1.8.0-rc4
Commit 7853436ccd7 (2022-08-08 07:55 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores

julia> include("examples/minimal_example.jl");
done
```
Setup 3:
```
julia> versioninfo()
Julia Version 1.8.0-rc4
Commit 7853436ccd7 (2022-08-08 07:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 8 on 10 virtual cores

julia> include("minimal_example.jl")
```
Setup 4:
```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)

julia> include("minimal_example.jl")
```

Setups 1 (ARM build) is working as expected.
Setups 2 and 3 (Rosetta builds) are freezing entirely and not showing any output. Keyboard interrupts also don't work then.

**Comment by oscardssmith** [comment]
I believe this is a known issue. The problem is that the M1 isn't able to schedule code on big and little cores at the same time.

**Comment by oscardssmith** [comment]
Yeah. The workaround is to set `julia --threads=4` which is all the M1 can use anyway.

**Comment by efaulhaber** [comment]
Interesting, with up to 7 threads, the example is running fine on Rosetta. With 8 threads or more, it's blocking.
This is the M1 Pro chip, which has 8 high-performance cores. Why can't all 8 be used in Rosetta?

Also, I found out that the "lagging problem" is probably nonsense. It seems like output is synchronized between threads, so all threads print their time together, and then there is a short break while all threads are calculating again.
The lagging issues that I have in larger simulations are then probably due to Polyester.jl. I will delete the "lagging problem" from this issue and create another in Polyester.jl.

**Comment by oscardssmith** [comment]
oh, wait, if it's an M1 pro, then all 8 threads should be usable. Ignore me.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
