### ISSUE TITLE
Uninformative error message in `mapreduce` with missing second function argument 

### ISSUE THREAD

**Issue by bvdmitri** [JuliaLang/julia#46314]
Consider the following MWE: 

```
collection = ones(2)  # Collection is not empty 
mapreduce(+, collection) # Throws collection is empty error
```

```
MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
```

Furthermore `init = 0.0` keyword argument does not help and `mapreduce(+, collection; init = 0.0)` throws the same error. The real issue here that some forgot a second function argument. 

It should be 
```
mapreduce(prod, +, collection) # works
```

The error message is bad, suggestion to supply `init` is misleading and un-informative in this case.

**Comment by mgkuhn** [comment]
Looks like a case where an insufficiently tight function signature for `mapreduce` is causing an unhelpful error message:

Perhaps
```
mapreduce(f, op, A::AbstractArrayOrBroadcasted...; kw...) =
    reduce(op, map(f, A...); kw...)
```
in [base/reducedim.jl:359](base/reducedim.jl) should be changed to
```
mapreduce(f::Function, op::Function, A::AbstractArrayOrBroadcasted...; kw...) =
    reduce(op, map(f, A...); kw...)
```
as you can prototype in the REPL with
```
julia> import Base.reduce, Base.AbstractArrayOrBroadcasted
julia> newmapreduce(f::Function, op::Function, A::AbstractArrayOrBroadcasted...; kw...) =
    reduce(op, map(f, A...); kw...)
julia> collection = ones(2);
julia> newmapreduce(+, collection)
ERROR: MethodError: no method matching newmapreduce(::typeof(+), ::Vector{Float64})
Closest candidates are:
  newmapreduce(::Function, ::Function, ::Union{Base.AbstractBroadcasted, AbstractArray}...; kw...) at REPL[2]:1
```

**Comment by mgkuhn** [comment]
But adding a `::Function` assertion might prevent use of `mapreduce` with [function-like objects](https://docs.julialang.org/en/v1/manual/methods/#Function-like-objects). Stricter type annotations help preventing mistakes, but also limit composability.

It's one of those areas, where Julia's highly composeable type system, and absence of a full-featured trait system (we can't say in the type signature that “f must have the trait of offering a single-argument method” and “op must offer a two-argument method”), interferes with our ability to catch some pretty obvious errors with meaningful error messages.

**Comment by bvdmitri** [comment]
Well trait system would be useful, but what about just adding a specific error-method for 2-arguments version of mapreduce? Now Julia indeed treats "collection" as a callable-functor object, and at the same time treats missing 3-argument as an empty collection.

**Comment by N5N3** [comment]
We have `map(f) = f()`, it's clear that `mapredcude(f, op) = reduce(op, f())`.
Your example failed at `+()`, if you run this with a fresh REPL, you should get
```julia
julia> mapreduce(+, collection) # Throws collection is empty error
ERROR: MethodError: no method matching +()

Closest candidates are:
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
   @ Base int.jl:87
  +(::T, ::T) where T<:Union{Float16, Float32, Float64}
   @ Base float.jl:383
  +(::Union{UInt16, UInt32, UInt8}, ::BigInt)
   @ Base gmp.jl:531
  ...

Stacktrace:
 [1] map(f::typeof(+))
   @ Base .\abstractarray.jl:2985
 [2] mapreduce(::Function, ::Vector{Float64}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Base .\reducedim.jl:334
 [3] mapreduce(::Function, ::Vector{Float64})
   @ Base .\reducedim.jl:334
 [4] top-level scope
   @ REPL[2]:1
```
I guess you loaded a package which change the dispatch. Can you check which package do this (We should fix on that side.)

**Comment by bvdmitri** [comment]
@N5N3 Your guess is correct. Fresh Julia session gives another error. The uninformative error appears when I do `using Distributions.jl`. But the real issue seems indeed to be introduced by `FillArrays.jl`:

```julia
julia> using FillArrays

julia> mapreduce(+, zeros(2))
ERROR: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
Stacktrace:
  [1] reduce_empty(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(min)}}, #unused#::Type{Union{}})
    @ Base ./reduce.jl:348
  [2] reduce_empty_iter(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(min)}}, itr::Tuple{}, #unused#::Base.HasEltype)
    @ Base ./reduce.jl:371
  [3] reduce_empty_iter(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(min)}}, itr::Tuple{})
    @ Base ./reduce.jl:370
  [4] foldl_impl(op::Base.MappingRF{typeof(length), Base.BottomRF{typeof(min)}}, nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:49
  [5] mapfoldl_impl(f::typeof(length), op::typeof(min), nt::Base._InitialValue, itr::Tuple{})
    @ Base ./reduce.jl:44
  [6] mapfoldl(f::Function, op::Function, itr::Tuple{}; init::Base._InitialValue)
    @ Base ./reduce.jl:162
  [7] mapfoldl
    @ ./reduce.jl:162 [inlined]
  [8] #mapreduce#262
    @ ./reduce.jl:294 [inlined]
  [9] mapreduce(f::Function, op::Function, itr::Tuple{})
    @ Base ./reduce.jl:294
 [10] map(::Function)
    @ FillArrays ~/.julia/packages/FillArrays/5Arin/src/fillbroadcast.jl:6
 [11] mapreduce(::Function, ::Vector{Float64}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./reducedim.jl:359
 [12] mapreduce(::Function, ::Vector{Float64})
    @ Base ./reducedim.jl:359
 [13] top-level scope
    @ REPL[3]:1
```

**Comment by mbauman** [comment]
I think we can close this as the upstream issue https://github.com/JuliaArrays/FillArrays.jl/issues/179.

We've not (yet) chosen to implement `mapreduce(f, op) = reduce(op, f())`, and it's not clear to me that we should.
