### ISSUE TITLE
Would like numbered REPL prompts

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#46310]
Sometimes it would be convenient if the REPL prompts (`julia>`) were numbered, starting from 1 when the session begins.

For example, when I receive a large output in the Julia REPL, I might need to scroll back to find the previous prompt. Numbered prompts would help here.

**Comment by jakobnissen** [comment]
Perhaps this could be provided in a package like OhMyREPL?

**Comment by rfourquet** [comment]
Duplicate of #38333, there is also a short snippet achieving this which can be put in startup.jl.
