### ISSUE TITLE
Support for unicode subscripts from A to Z

### ISSUE THREAD

**Issue by tapyu** [JuliaLang/julia#46347]
If am not wrong, [Julia only has support for some subscript letters](https://docs.julialang.org/en/v1/manual/unicode-input/). It is very important to have all letters available in subscript, uppercase and lowercase.

Has `julia` some schedule to provide such feature?

**Comment by oscardssmith** [comment]
not all letters have Unicode subscript versions.

**Comment by DNF2** [comment]
Just to clarify: This isn't a Julia issue, but an issue with the Unicode standard.

There exists a (draft?) proposal for adding more subscripts to the standard, but I don't know what the status is for that proposal: https://github.com/stevengj/subsuper-proposal

This is something that is wanted by many in the Julia community, but it is outside of their control.

**Comment by tapyu** [comment]
Thank you for the reference.
