### ISSUE TITLE
Documentation of Arrays should be improved

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/julia#46344]
If I look at the documentation of Arrays at https://docs.julialang.org/en/v1/base/arrays/ I would be frustrated if I start to use Julia and want to use arrays. 

It would be good to add an section **Introduction** that explains the most frequent use cases by giving examples. 

Perhaps similar to https://en.wikibooks.org/wiki/Introducing_Julia/Arrays_and_tuples#Storage:_Arrays_and_Tuples, but shorter.

**Comment by bvdmitri** [comment]
Hasn't it already been written here: https://docs.julialang.org/en/v1/manual/arrays/ ?

**Comment by ufechner7** [comment]
Well, the link you shared looks indeed good... :)

The problem is, if I google julia+array I get the link I shared... So I think it would be good to add a sentence to that page like:
For a general introduction on arrays in Julia see https://docs.julialang.org/en/v1/manual/arrays/ .

What do you think?
