### ISSUE TITLE
What is the replacement for jl_set_global

### ISSUE THREAD

**Issue by robertu94** [JuliaLang/julia#46361]
```
Julia Version 1.9.0-DEV.unknown
Commit df84643* (2022-08-03 13:41 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.0 (ORCJIT, tigerlake)
  Threads: 1 on 16 virtual cores
```

It appears as though one of the embedding APIs `jl_set_global` has been removed (`grep -R "jl_set_global"` in julia's include directory returns no results), but there hasn't been an increment to the major version number.  I tried to find the history of this change, but have so far been unsuccessful, I'm sure it was made for a good reason.  Since there are codes (i.e. JLuna see https://github.com/Clemapfel/jluna/issues/34 ) that use this API, should there be either some deprecation period, or a replacement that can be used?

... Yes, I know this is a pre-release version and breakages should be expected.  Thanks for all your work on a great language.

**Comment by Taaitaaiger** [comment]
It was removed by #44753. As another user of the C API it would be really nice to have header file with a stable interface that isn't broken regularly.

**Comment by gbaraldi** [comment]
The C API isn't considered stable.
 Check https://github.com/JuliaLang/PackageCompiler.jl/issues/708 and https://github.com/JuliaLang/PackageCompiler.jl/pull/709 for possible solutions

**Comment by Taaitaaiger** [comment]
It would be nice then if the embedding guide included a warning to make that clear.

**Comment by JeffBezanson** [comment]
As far as I can tell it should be ok to add this entry point back. Just because the C API *can* technically change, does not mean we intend to randomly break it for no good reason.

**Comment by Clemapfel** [comment]
'm also trying to find a C-API-based replacement that works for both 1.7, 1.8 and 1.9, if it's going to get removed in 1.9.

Am I correct under the assumption that the following are functionally equivalent?

```c
jl_set_global(jl_main_module, jl_symbol("var"), jl_box_int64(64));
```
```c
jl_binding_t* binding = jl_get_binding_wr(jl_main_module, jl_symbol("var"), 1);
binding->value = jl_box_int64(64);
```

I am unsure of how `jl_set_global` works exactly, I assume these are not equivalent because of how the GC is not made aware of this assignment but maybe I'm wrong.
