### ISSUE TITLE
Bug：start Julia.exe error

### ISSUE THREAD

**Issue by TongYuanRuanKong** [JuliaLang/julia#46374]
platform : win10
julia version : julia-1.7.3
step1：When the installation path is selected as a Chinese path and there are more than 8 Chinese characters, it fails to start julia.exe，as shown in Figure 1
step2:  When the installation path is selected as Chinese path, less than 8 Chinese characters, start julia.exe successfully, as shown in Figure 2
![image](https://user-images.githubusercontent.com/98097166/185104720-5e8b0ff9-24be-424f-a5cf-af7c1e8bf210.png)
![image](https://user-images.githubusercontent.com/98097166/185104909-aa62b8c1-e0d5-4c77-acd8-df7b45863e94.png)

**Comment by inkydragon** [comment]
Confirmed. 

8 chinese chars
```
PS V:\一二三四五六七八\julia-1.7.3\bin> .\julia.exe
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```

9 chinese chars
```
PS V:\一二三四五六七八九\julia-1.7.3\bin> .\julia.exe
ERROR: could not load library "V:\一二三四五六七八九\lib\julia\sys.dll"
The specified module could not be found.
```

**Comment by ViralBShah** [comment]
I feel like there has already is an issue for this, but can't find it.

**Comment by inkydragon** [comment]
Related: julia.exe starting error with Korean path-name. #33486
It's an upstream issue (libuv)

**Comment by ViralBShah** [comment]
Closing as dup of #33486
