### ISSUE TITLE
"Edit on GitHub" of `Command-line Options` page is broken

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#46389]
The "Edit on GitHub" button in the [Command-line Options](https://docs.julialang.org/en/v1/manual/command-line-options/) page is broken. It goes to
`https://github.com/JuliaLang/julia/blob/master/doc/src/manual/command-line-options.md`
instead of
`https://github.com/JuliaLang/julia/blob/master/doc/src/manual/command-line-interface.md`

**Comment by ViralBShah** [comment]
Presumably, this is a documenter issue.
