### ISSUE TITLE
link to PDF documentation broken for 1.8.0

### ISSUE THREAD

**Issue by matthias314** [JuliaLang/julia#46402]
The link to the PDF documentation on the [Julia 1.8 Documentation](https://docs.julialang.org/en/v1.8/) page results in "404: Not Found".

**Comment by mortenpi** [comment]
The PDF build for 1.8 needs #45290 and so didn't deploy automatically. I pushed a manual build instead and it's available now: https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.8.0.pdf
