### ISSUE TITLE
Add parse error for comma in struct definition

### ISSUE THREAD

**Issue by oscardssmith** [JuliaLang/julia#46419]
Currently
```
julia> struct d
               a::Int
               b::Float64,
               c::Int
       end
ERROR: UndefVarError: b not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```
This is a roughly once a month mistake for me that currently gives a very opaque error. If we made it a parser error to have a tuple in a struct, we could actually give a good error message here. (Jeff agrees that this is a good idea).

**Comment by giordano** [comment]
Duplicate of #46283?

**Comment by oscardssmith** [comment]
oops. yes.
