### ISSUE TITLE
`Float64^Int` can return incorrectly signed `Inf`

### ISSUE THREAD

**Issue by flin2** [JuliaLang/julia#46435]
I noticed a potential malfunction related to `Inf`. The minimal reproducible example is as follows:
```
julia> (1*1e-19)^(-20)
Inf
julia> (3*1e-19)^(-20)
-Inf
```
The second result should also be `Inf`.

The output from `versioninfo()` is as follows:
```
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```
Thank you!

**Comment by oscardssmith** [comment]
Good catch. I'd made an implicit assumption that the rounding errors are finite, which isn't always true. The reproducer can be simplified to `3e18^20` (negative exponents have some complications that aren't relevant here).

**Comment by oscardssmith** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/46436
