### ISSUE TITLE
Define islowercase for String

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#46444]
In 1.7 `islowercase` is defined for characters but not strings. It would be useful to have for strings.

([From discourse](https://discourse.julialang.org/t/why-doesnt-islowercase-work-on-string/86173).)

**Comment by PallHaraldsson** [comment]
FYI:

```
julia> all(islowercase, "Páll")
false

julia> all(islowercase, "páll")
true

first I thought it might be
julia> islowercase.("Páll")
ERROR: MethodError: no method matching islowercase(::String)

since non-obvious feel free to make a PR for:
julia> import Unicode.islowercase

julia> islowercase(s::AbstractString) = all(islowercase, s)
```

**Comment by KristofferC** [comment]
I also think lowercase has to do with a character and not a string. Using `all` together with `islowercase` is therefore the natural way of expressing this.

**Comment by oscardssmith** [comment]
IMO, it's very odd that `lowercase("Hi")` works but `islower("Hi")` doesn't. Adding to triage to decide what we want to do about this.

**Comment by stevengj** [comment]
I agree that since we have `lowercase` for strings, it is odd that we don't also have `islowercase`.   `islowercase(lowercase(s))` should `=== true`.

**Comment by stevengj** [comment]
Moreover, contrary to the assertions above, it is nontrivial to implement this using `all`:
```jl
julia> all(islowercase, "ax̂e")
false

julia> "ax̂e" == lowercase("ax̂e")
true
```

**Comment by stevengj** [comment]
Consider
```jl
julia> "élan" == lowercase("élan")
true

julia> all(c -> c == lowercase(c), "élan")
true

julia> all(islowercase, "élan")
false
```
If you are confused by this, realize that `"élan"` includes the unicode combining character [U+0301](https://www.fileformat.info/info/unicode/char/0301/index.htm).   On the other hand, if you use the NFC normalization `"élan"` of the same string (which uses the accented character [U+00E9](https://www.fileformat.info/info/unicode/char/e9/index.htm)), you get:
```jl
julia> all(islowercase, "élan")
true
```
(But if you define `islowercase(s::String) = s == lowercase(s)`, then it will be inconsistent with the definition of `islowercase` for characters.)

**Comment by gbaraldi** [comment]
While yeah that definition is wrong it's more of unicode semantics then what people expect.
```julia
julia> all(islowercase, "élan")
false
```
is probably a wrong result for most people.

**Comment by stevengj** [comment]
@gbaraldi, is this the "correct" result:
```jl
julia> all(islowercase, "1")
false

julia> all(islowercase, "̂") # "\hat"
false
```

**Comment by JeffBezanson** [comment]
We explicitly decided to remove these kinds of predicates for strings in v0.6.

**Comment by stevengj** [comment]
> We explicitly decided to remove these kinds of predicates for strings in v0.6.

In particular, this was done in #20342, following the discussion in #14156.

> Does it make sense to rather define as (and vise versa): `islowercase(s::AbstractString) = any(!isuppercase, s)`

No, because then `islowercase("1")` will return `true` and `islowercase('1')` will return `false`, which seems inconsistent.

**Comment by JeffBezanson** [comment]
I think this can be closed. I don't see an overwhelmingly convincing reason to revisit this decision.
