### ISSUE TITLE
`kron` unnecessarily converts to dense matrices

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#46456]
`kron` returns dense matrices from some inputs types where this is not necessary:
```
julia> using LinearAlgebra
julia> A = kron(Diagonal([1,1,1]), Tridiagonal([2,2], [3,3,3], [4,4]))
9×9 Matrix{Int64}:
 3  4  0  0  0  0  0  0  0
 2  3  4  0  0  0  0  0  0
 0  2  3  0  0  0  0  0  0
 0  0  0  3  4  0  0  0  0
 0  0  0  2  3  4  0  0  0
 0  0  0  0  2  3  0  0  0
 0  0  0  0  0  0  3  4  0
 0  0  0  0  0  0  2  3  4
 0  0  0  0  0  0  0  2  3

julia> A == Tridiagonal(A)
true
```

That is, `kron` could return a `Tridiagonal` matrix here, but doesn't. The same is true for `Bidiagonal` and `SymTridiagonal` matrices. The condition here is that `kron`'s first argument is a `Diagonal` matrix.

Similarly (but less important), `kron` could return upper or lower triangular matrices in some cases:
```Julia
julia> A = kron(Bidiagonal([3,3,3], [4,4], :U), Diagonal([1,1,1]))
9×9 Matrix{Int64}:
 3  0  0  4  0  0  0  0  0
 0  3  0  0  4  0  0  0  0
 0  0  3  0  0  4  0  0  0
 0  0  0  3  0  0  4  0  0
 0  0  0  0  3  0  0  4  0
 0  0  0  0  0  3  0  0  4
 0  0  0  0  0  0  3  0  0
 0  0  0  0  0  0  0  3  0
 0  0  0  0  0  0  0  0  3

julia> A == UpperTriangular(A)
true
```

The condition here is that all input types are respective `Diagonal`, `Bidiagonal`, or `Triangular` matrices.

**Comment by dkarrasch** [comment]
Specializing `kron(::Bidiagonal, ::Diagonal)` will make it type-unstable, due to the `uplo` _value_, so that "optimization" may not be worth it, considering also that you need to back it up by full matrix anyway. But besides the optimizations in #46463, 
```julia
kron(::Diagonal, ::[Unit]*Triangular) -> *Triangular
```
makes sense.

**Comment by eschnett** [comment]
Yes, I'm unsure about the second half. The only optimization would be a tighter output type, there would be no storage or computing improvements. I'll probably skip the second part.

**Comment by dkarrasch** [comment]
Then #46463 closes this issue, right?

**Comment by eschnett** [comment]
Yes it will.
