### ISSUE TITLE
performance regression for `Core.Intrinsicts.rem_float` in 1.8/1.9

### ISSUE THREAD

**Issue by lmiq** [JuliaLang/julia#46467]
I noticed this in the use of `mod`, but it seems that the issue can be tracked down to `Core.Intrinsics.rem_float`:

On 1.8.0:

```julia
julia> @btime Core.Intrinsics.rem_float(x, 1.0) setup=(x=rand())
  7.422 ns (0 allocations: 0 bytes)
0.11718355488076748
```

On 1.7.3:

```julia
julia> @btime Core.Intrinsics.rem_float(x, 1.0) setup=(x=rand())
  2.208 ns (0 allocations: 0 bytes)
0.21209837479215266
```

This is causing a significant performance regression in a package of mine which uses `mod` many many times.

system info:

Linux m3g 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

edit: on the nightly build:
```julia
julia> @btime Core.Intrinsics.rem_float(x, 1.0) setup=(x=rand())
  7.414 ns (0 allocations: 0 bytes)
0.2578476302582853
```

**Comment by oscardssmith** [comment]
Is this a difference in which libm we call?

**Comment by lmiq** [comment]
I noticed now that similar performance regressions can be felt in the `floor`, `trunc` and other functions of this family.

**Comment by oscardssmith** [comment]
that's unsurprising but quite bad.

**Comment by oscardssmith** [comment]
Also, this affects 1.9 as well.

**Comment by gbaraldi** [comment]
Was this a change in our side? Did we change from system libm to Openlibm or something like it?

**Comment by oscardssmith** [comment]
yeah we're hitting the openlibm one now. The ideal fix would be to move this to pure Julia but I doubt I'll get around to it.

**Comment by oscardssmith** [comment]
want to take a crack at it?

**Comment by gbaraldi** [comment]
Sure, I'll try it out, see how it compares :)
