### ISSUE TITLE
Syntax `1:0` doesn't work in a very rare situation

### ISSUE THREAD

**Issue by GoldenSnitchD** [JuliaLang/julia#46475]
Maybe my English is not good, but thanks for your reading! I'm doing a project called [FamilyTrees.jl](GoldenSnitchD/FamilyTrees.jl) to record information about relatives. [This commit](https://github.com/GoldenSnitchD/FamilyTrees.jl/tree/7ea76d197030beacf18e84112fdbe8a62c5073f1) is the point I seemed to find a bug.

In `Base.read(io::IO, ::Type{Person})` at line 107 in src/persons.jl, I wrote code to read a person's information from `io`, but the test at test/runtests.jl:9 doesn't pass and reports an EOF error. To debug, I add a function called `showlned`, that show the parameter, new line, and return the parameter. Here is the result during the tests: (I don't know other way to show the png)

https://github.com/GoldenSnitchD/FamilyTrees.jl/blob/main/截屏2022-08-24%20下午9.26.43.png

It seems that `1:0` is -1? How could that be possible? Moreover, the `for i = 1:0` below shows that it's just a common UnitRange that would not be iterated.

I've tried my best to find the key point of the bug but I really have no idea, so I shows my whole project. I hope the issue would be solved soon! Thanks!

p.s. The code could be a bit complex because I call python functions to get get 'pinyin' of Chinese characters ('pinyin' is just a kind of pronunciation for Chinese), as I want to sort them by the pronunciation later, but that doesn't seem to have something to do with the issue, in fact, so just ignore the module `Names` inside the module `FamilyTrees`

I use Julia 1.8.0, macOS Catalina 10.15.7, MacBook Pro (13-inch, Mid 2012), the processor is "2.9 GHz 双核Intel Core i7" (I don't dare to translate that myself)

**Comment by GoldenSnitchD** [comment]
I'll remove that photo in future commit, If the photo is not available, try this

https://github.com/GoldenSnitchD/FamilyTrees.jl/blob/d374da00fda746713f0a15ed977be9adce79f5fb/截屏2022-08-24%20下午9.26.43.png

I won't delete this commit

**Comment by GoldenSnitchD** [comment]
Oh my! Another similar situation found! Is this the key?
```
$ julia    
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0 (2022-08-17)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> function showlned(x)
           show(x)
           println()
           x
       end
showlned (generic function with 1 method)

julia> for i = showlned(1:0)
           print(i)
           end
1:0

julia> for i = showlned(1:0)
           print(i)
           end
1:0

julia> for i in showlned(1:0)
           print(i)
           end
1:0

julia> showlned(1:0) === 1:0
1:0
true

julia> showlned(1:0)::UnitRange{Int} === (1:0)::UnitRange{Int}
1:0
true

julia> for i in 1:0
           print(i)
           end

julia> 
```

**Comment by oscardssmith** [comment]
This needs a MWE. What precisely is the code you are running (as simple as possible) that shows the error?

**Comment by Seelengrab** [comment]
I *think* you're referring to `1:0` being empty, i.e. not having any elements? In Julia, constructing ranges like that will try to *increment* the first value until the second value is reached - to get a range that counts down, explicitly give the step:

```
julia> for i = 1:-1:0
         println(i)
       end
1
0
```

**Comment by GoldenSnitchD** [comment]
Well, just ignore that comment with a Julia REPL interface. That's right. It's a mistake of mine.

However, the issue above is real. MWE may be difficult. I'll do that, but the issue has been closed, so where should I submit that after finishing?

**Comment by oscardssmith** [comment]
it's unclear what you are saying is a bug, but if you get a mwe that makes it clear, you can add it to this issue.

**Comment by GoldenSnitchD** [comment]
I've gotten a mwe at [a new repository](https://github.com/GoldenSnitchD/SimplfiedFamilyTrees.jl) and add some comments in the code.

**Comment by GoldenSnitchD** [comment]
Is that clear enough?

**Comment by Seelengrab** [comment]
https://github.com/GoldenSnitchD/SimplfiedFamilyTrees.jl/blob/623d14418f02f62d3ca550ca0667bf80fd3f56a0/src/SimplfiedFamilyTrees.jl#L19

This is the culprit. You're defining a new `:`, overwriting the one from `Base`, which just returns `-1`.

```
julia> SimplfiedFamilyTrees.:(:) === Base.:(:)
false

julia> SimplfiedFamilyTrees.:(:)
: (generic function with 1 method)

julia> SimplfiedFamilyTrees.:(:) |> methods
# 1 method for generic function ":" from SimplfiedFamilyTrees:
 [1] :(UNKNOWN_PERSON_ID, PersonID)
     @ ~/.julia/packages/SimplfiedFamilyTrees/2GorM/src/SimplfiedFamilyTrees.jl:19
```

**Comment by GoldenSnitchD** [comment]
Oh! I mistake '::' and ':' again! All right. You know, ':' means type assertion in many languages like Python, Swift, Rust, etc. Thank you very much.
