### ISSUE TITLE
newlines break `let`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#46482]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.1171 (2022-08-23)
 _/ |\__'_|_|_|\__'_|  |  Commit df3da0582a7 (2 days old master)
|__/                   |

julia> let a = 1, b = 2  # works
         0
       end
0

julia> let  # works
         (a = 1,),
         (b = 2,)
         0
       end
0

julia> let  # works
         (a = 1),
         (b = 2)
         0
       end
0

julia> let  # fails
         a = 1,
         b = 2
         0
       end
ERROR: syntax: invalid assignment location "1" around REPL[4]:2
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```

1.8.0 behaves the same.

**Comment by nsajko** [comment]
Perhaps related to https://github.com/JuliaLang/julia/issues/45719

**Comment by nsajko** [comment]
Also:
```
julia> let
         a = one(Int),
         b = zero(Int)
         5
       end
ERROR: BoundsError: attempt to access Int64 at index [2]
Stacktrace:
 [1] indexed_iterate(I::Int64, i::Int64, state::Nothing)
   @ Base ./tuple.jl:97
 [2] top-level scope
   @ REPL[7]:2
```

**Comment by nsajko** [comment]
The original post above was inaccurate with the "works" comment:
```
julia> let
         (a = 3),
         (b = 2)
         a * b
       end
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:4

julia> let
         (a = 3,),
         (b = 2,)
         a * b
       end
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:4
```

**Comment by nsajko** [comment]
Another, different, error message:
```
julia> let
         a = first((2,)),
         b = first((3,))
         a * b
       end
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1
```

**Comment by nsajko** [comment]
Can anyone think of a workaround?
The nicest thing I can think of is nesting `let`s, but that's not very nice at all.

**Comment by Keno** [comment]
> julia> let  # works
>          (a = 1,),
>          (b = 2,)
>          0
>        end
> 0
> 
> julia> let  # works
>          (a = 1),
>          (b = 2)
>          0
>        end
> 0

These are let expressions without assignments and then a void construction of a tuple of named tuples, not let expressions.

**Comment by digital-carver** [comment]
```
julia> let  # fails
         a = 1,
         b = 2
         0
       end
ERROR: syntax: invalid assignment location "1" around REPL[4]:2
```

Similarly, this is a let expression without assignments, followed by   `a = 1, b = 2`. Because this is not part of the let expression, it's seen as `a = (1, b) = 2` i.e. an attempt to assign to `(1, b)`, hence the error. 

---
```
julia> let
         a = one(Int),
         b = zero(Int)
         5
       end
ERROR: BoundsError: attempt to access Int64 at index [2]
```
Same as above, except `one(Int), b = zero(Int)` has valid LHS locations, but `zero(Int)` on the RHS doesn't have two values to supply, so the the access fails there. 

---
```
julia> let
         (a = 3),
         (b = 2)
         a * b
       end
```
Again, because the second and third lines are not part of the let expression, they're seen as the  named tuple construction equivalent to 
```
julia> (a = 3), (b = 2)
(a = 3, b = 2)
```
so `a` and `b` are keys in that named tuple and not being defined as variables. 

---
```
julia> let
         a = first((2,)),
         b = first((3,))
         a * b
       end
ERROR: syntax: malformed expression
```
Equivalent to `a = (first((2,)), b) = first((3,))`, which also returns a `malformed expression` syntax error.

**Comment by nsajko** [comment]
Regarding workarounds, I guess that these two are equivalent:
```
julia> let a = 3,
           b = 4
         a + b
       end
7

julia> let a = 3, b = 4
         a + b
       end
7
```
