### ISSUE TITLE
Add the feature for go-lang like `Defer` 

### ISSUE THREAD

**Issue by kylincaster** [JuliaLang/julia#46485]
The `Defer` function refers to take some operation on the exit of the section or the function, which is very convinient for case with resouce need to be released afterwards.
For example in the function with the multiple exit like.
```
function connect(...)
f = open(file)

if condition
	close(f)
	return ...
else
	close(f)
	return xxx
```
if the defer feature is added, the code could be simplied  as
```
function connect(...)
f = open(file)
@defer close(f)
if condition
	return ...
else
	return xxx
```
I suggest to implement `@defer` as 

```
macro defer(f(x...))
	ccall(:jt_func_defer, f, x...)
end
```

where `:jt_func_defer` is some julia C-interface which invokes the expression f(x...) at the exit of function.

**Comment by gbaraldi** [comment]
I believe there is https://github.com/adambrewster/Defer.jl which kinda does this.

**Comment by kylincaster** [comment]
> I believe there is https://github.com/adambrewster/Defer.jl which kinda does this.

Thank you I have a try on Defer, which works exactly as I expected.

**Comment by KristofferC** [comment]
See also the long discussion in https://github.com/JuliaLang/julia/issues/7721.
