### ISSUE TITLE
18x increase in compile time on v1.8

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#46492]
The following snippet takes 
```
7.833256 seconds (36.60 M allocations: 1.727 GiB, 7.05% gc time, 100.00% compilation time
```
on julia v1.7.3
but 
```
146.158104 seconds (474.09 M allocations: 79.036 GiB, 4.20% gc time, 100.00% compilation time)
```
on julia v1.8
```julia
using ControlSystems
a_2 = [-5 -3; 2 -9]
C_212 = ss(a_2, [1; 2], [1 0; 0 1], [0; 0])
@time norm(C_212)
```
an `@profile` is available in [html format here](https://drive.google.com/file/d/13MOr_mJzAqDkSaTtAPTTZdIKd5HMPkAA/view?usp=sharing).

![image](https://user-images.githubusercontent.com/3797491/186884574-6287e0bf-27d7-421d-8c43-1f0ed3dc581e.png)

**Comment by KristofferC** [comment]
There are at least two regressions I think. Bisecting I see at one time it goes from ~10 seconds to

```
 39.839046 seconds (102.91 M allocations: 9.583 GiB, 9.93% gc time, 100.00% compilation time)
```

**Comment by ianatol** [comment]
> There are at least two regressions I think. Bisecting I see at one time it goes from ~10 seconds to
> 
> ```
>  39.839046 seconds (102.91 M allocations: 9.583 GiB, 9.93% gc time, 100.00% compilation time)
> ```

Any particularly guilty commits? @KristofferC

**Comment by KristofferC** [comment]
Few more steps left :)

**Comment by KristofferC** [comment]
First 4x regression is 2c0e1bccb, cc @JeffBezanson

**Comment by KristofferC** [comment]
The second big regression (30s -> 200s) comes from 26b0b6e408, cc @aviatesk
