### ISSUE TITLE
Segfault on precompilation in 1.8.0

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#46527]
I'm experiencing segfaults when precompiling my workload on Julia 1.8.0, which I've not experienced using other versions.
After it having failed three times, I have not been able to reproduce the issue, presumably because the issue is related to something stateful regarding the precompilation cache.

The error message is attached

[iterative.log](https://github.com/JuliaLang/julia/files/9442032/iterative.log)

**Comment by gbaraldi** [comment]
There were a few segfaults during precompile time that @maleadt fixed and should be out for 1.8.1. In any case could you build a version of julia with assertions to maybe see if it trips any of them

**Comment by jakobnissen** [comment]
I'll try, but I haven't been able to reproduce it locally.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
