### ISSUE TITLE
`evalpoly` wrong for `OffsetArray`s

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#46539]
```julia-repl
julia> poly = OffsetArray([7, 5, 3], -1)
3-element OffsetArray(::Vector{Int64}, 0:2) with eltype Int64 with indices 0:2:
 7
 5
 3

julia> evalpoly(100, poly)
30305
```

This should be `305.07` or an error (or maybe `30507`).

**Comment by oscardssmith** [comment]
I vote error.

**Comment by LilithHafner** [comment]
I concur in this case, but `evalpoly(100.0, poly) == 305.07` and `evalpoly(100, OffsetArray([7, 5, 3], 1)) == 3050700` seem reasonable

**Comment by oscardssmith** [comment]
if `OffsetArrays` wants to define those overloads, that seems reasonable to me.

**Comment by LilithHafner** [comment]
What about offset arrays other than OffsetArrays.OffsetArray?

**Comment by gbaraldi** [comment]
I think the same thing, if someone wants to define evalpoly do it explicitily

**Comment by LilithHafner** [comment]
I don't see how to composably define this in a package
```julia
function evalpoly(x, p)
    ex = ...
    firstindex(p) == 1 ? ex : ex * x ^ (firstindex(p) - 1)
end
```

**Comment by jishnub** [comment]
Related: https://github.com/JuliaLang/julia/issues/40454

**Comment by LilithHafner** [comment]
Moving discussion to https://github.com/JuliaLang/julia/issues/40454
