### ISSUE TITLE
Markdown: Inconsistent interpolation into codeblock

### ISSUE THREAD

**Issue by alecloudenback** [JuliaLang/julia#46565]
Interpolation doesn't work inside codeblocks with `@md_str`, but it does with `Markdown.parse`. Should these be different?

```julia-repl
julia> using Markdown

julia> x = 10
10

julia> md"test `$x`"
  test $x

julia> Markdown.parse("test `$x`")
  test 10
```

**Comment by giordano** [comment]
> but it does with `Markdown.parse`

It isn't `Markdown.parse` which is doing the interpolation, but the string you're passing as argument.  String macros don't do interpolation by default, you have to implement manually yourself if you want it.
