### ISSUE TITLE
const in local scope?

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#46562]
Currently one cannot declare local variables const:
```julia
julia> function f()
           const x = 1
       end
ERROR: syntax: unsupported `const` declaration on local variable around REPL[1]:2
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```
From time to time I wish this was possible.
* Would it be hard to implement that?
* Are there subtle questions about the semantics of this?

**Comment by fredrikekre** [comment]
#5148
