### ISSUE TITLE
macOS ARM USE_BINARYBUILDER_OPENBLAS=0: julia/user/tools/objconv: No such file or directory

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/julia#46579]
On a Mac Studio (M1 arm64) I recently compiled Julia master at cb5f401aaadcd17fbe366a64afdbf7e6fc71ac69 and got the following error:

```
$ make -j10 USE_BINARYBUILDER_OPENBLAS=0
...
 cblas_zsyr2k PASSED THE COLUMN-MAJOR COMPUTATIONAL TESTS (  1764 CALLS)
 cblas_zsyr2k PASSED THE ROW-MAJOR    COMPUTATIONAL TESTS (  1764 CALLS)

 END OF TESTS
make[3]: /Users/kittisopikulm/Documents/src/julia/usr/tools/objconv: No such file or directory
make[3]: *** [../libopenblas64__armv8p-r0.3.20.a.osx.renamed] Error 1
make[2]: *** [shared] Error 2
*** Clean the OpenBLAS build with 'make -C deps clean-openblas'. Rebuild with 'make OPENBLAS_USE_THREAD=0' if OpenBLAS had trouble linking libpthread.so, and with 'make OPENBLAS_TARGET_ARCH=NEHALEM' if there were errors building SandyBridge support. Both these options can also be used simultaneously. ***
make[1]: *** [scratch/openblas-0b678b19dc03f2a999d6e038814c4c50b9640a4e/build-compiled] Error 1
make: *** [julia-deps] Error
```

**Comment by mkitti** [comment]
Looking for objconv, it appears to be in `julia/usr/bin/objconv` when installing from BinaryBuilder

```
julia % find . -iname objconv
./usr/bin/objconv
./usr/manifest/objconv
./deps/checksums/objconv
```

**Comment by carlocab** [comment]
Note that `objconv` works only on [x64 mach-o objects](https://www.agner.org/optimize/#objconv). (Not sure how this works in BinaryBuilder.)

**Comment by mkitti** [comment]
@carlocab, are you sure? We seem to be using it just fine via the binarybuilder.org process:
https://github.com/JuliaPackaging/Yggdrasil/blob/3e7bf19bee50e2b845eb31076980e5e5aed17c02/O/Objconv/build_tarballs.jl

See https://github.com/staticfloat/objconv/blob/ae54df67e0c4ac2c78f3a7ece486ed4e92d098af/src/macho.h#L50-L55

**Comment by mkitti** [comment]
xref:
#42538 
#44517
#45391

**Comment by carlocab** [comment]
Well, that's what the description says.

I also wrote the author via email a while ago to ask a question, and they, too, said

> The program supports only x86 and x86-64 systems, it will not work on ARM based Mac.

**Comment by carlocab** [comment]
Though, I suppose you don't have to take my word for it. Building `objconv` is easy: just run `./build.sh` after extracting the source.

Then, run
```
echo "int foo() { return 0; }" >> foo.c
make foo.o
./objconv -nr:_foo:_main foo.o bar.o
make bar
./bar
```
On an Intel Mac this produces no errors.

**Comment by mkitti** [comment]
Hmm, could it be that it only works in a cross compilation scenario?

That's how BB works, and that's also what we seem to be doing over at https://github.com/conda-forge/openblas-feedstock/pull/146

@staticfloat @giordano , this is an intriguing twist.

**Comment by carlocab** [comment]
Though, having tried that on an M1 Mac, the above exercise seems to work, so 🤷

**Comment by mkitti** [comment]
Without reverting anything `make -j10 USE_BINARYBUILDER_OPENBLAS=0 USE_BINARYBUILDER_OBJCONV=0` seems to work.

**Comment by mkitti** [comment]
Reverting https://github.com/JuliaLang/julia/commit/434d340afc7e4cc4d18b09c3858a6c6bc47ba85b from #45391 seems to resolve the `objconv` location issue, so we need to reconcile non-binarybuilder builds and binarybuilder builds it seems.

**Comment by ViralBShah** [comment]
A simple thing to do here may be to set `USE_BINARYBUILDER_OBJCONV=0` when the user sets `USE_BINARYBUILDER_OPENBLAS=0`.
