### ISSUE TITLE
support `diff(::Tuple)` ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaLang/julia#46575]
Currently, on any julia version:

```julia
julia> (1, 2, 10) |> extrema |> diff |> first
ERROR: MethodError: no method matching diff(::Tuple{Int64, Int64})
Closest candidates are:
  diff(::AbstractRange{T}; dims) where T at multidimensional.jl:1007
  diff(::SparseArrays.AbstractSparseMatrixCSC; dims) at [...]/share/julia/stdlib/v1.8/SparseArrays/src/linalg.jl:1099
  diff(::AbstractVector) at multidimensional.jl:965

# obvious workaround
julia> (1, 2, 10) |> extrema |> collect |> diff |> first
9
```

Would it make sense to support `diff(::Tuple)` in `Base` ?

I couldn't find any discussions on discourse or in the issues db.

Using `extrema |> diff` is a very common pattern for computing a `Δ = max - min`.

If so, should it go into `base/tuple.jl` (with obvious implementation restrictions, since `tuple.jl` is loaded early for `base/compiler`) or in `base/multidimensional.jl` ?

**Comment by vtjnash** [comment]
A tuple is generally not considered to be like an array, with a mathematically relation existing between the elements. That is what StaticArrays is for, and I assume it would already define this.
