### ISSUE TITLE
Missing font issue in pdf version of docs

### ISSUE THREAD

**Issue by braamvandyk** [JuliaLang/julia#46595]
A minor issue, but at the bottom of p6 of the pdf version of the v1.8.0 docs, there is a missing font problem resulting in the Chinese(?) characters being displayed as boxes, both in Acrobat and Edge.

It displays fine on the web page and if I copy the text and paste it anywhere in Windows (including the run dialog!), it displays in the appropriate font.

Perhaps the font should be embedded in the pdf?

**Comment by fredrikekre** [comment]
Can you open this issue for Documenter instead? https://github.com/JuliaDocs/Documenter.jl
