### ISSUE TITLE
Build-time warning about `egrep`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#46649]
When building Julia on macOS with MacPorts installed, I have been seeing this warning for the past few days:
```
egrep: warning: egrep is obsolescent; using ggrep -E
```
This warning appears many times when building Julia

Julia uses `egrep` in `Make.inc`:
```Makefile
TAR_TEST := $(shell $(TAR) --help 2>&1  | egrep 'bsdtar|strip-components')
```

**Comment by nsajko** [comment]
FTR `egrep` is the traditional but nonstandard solution, while `grep -E` is the POSIX-compliant way to use the old egrep features.
