### ISSUE TITLE
string_concatenation_hint_handler fails tests

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#46655]
Apparent regression in tests from merging #45823 recently?
```
      From worker 10:	┌ Error: Hint-handler string_concatenation_hint_handler for MethodError in Base caused an error
      From worker 10:	└ @ Base.Experimental experimental.jl:321
missing                                         (10) |    42.50 |   0.30 |  0.7 |     704.53 |  2004.57
```

These `register_error_hint` should probably be going into REPL or InteractiveUtils; they probably should not be going into Base.

_Originally posted by @vtjnash in https://github.com/JuliaLang/julia/issues/45823#issuecomment-1238385975_

**Comment by KristofferC** [comment]
cc @merryhime, maybe you can look at this?

**Comment by merryhime** [comment]
hey, will do when i can.
