### ISSUE TITLE
Update manual concerning global typed variables

### ISSUE THREAD

**Issue by Eulertin** [JuliaLang/julia#46682]
The manual states on its page on types that "type declarations cannot be used in global scope, e.g. in the REPL, since Julia does not yet have constant-type globals." If I got that right that is no longer true since Julia 1.8. (see: manual-scope of variables-typed globals) 

Don't really know how to fix that myself, so I just filed this issue. Hope that is the right way to go.

**Comment by udohjeremiah** [comment]
> The manual states on its page on types that "type declarations cannot be used in global scope, e.g. in the REPL, since Julia does not yet have constant-type globals." If I got that right that is no longer true since Julia 1.8. (see: manual-scope of variables-typed globals)
> 
> Don't really know how to fix that myself, so I just filed this issue. Hope that is the right way to go.

That's great. Thank you so much for your contribution.

Let me use this opportunity to pass you through the step on fixing it so you become more connected to Julia and fix other issues in the future:

This is the doc section where you caught the issue:
**`https://docs.julialang.org/en/v1/manual/types/`**

Now on every doc section in the top right-hand corner is a button named:
**`Edit on Github`**.

Click on **`Edit on Github`** and it will take you to this link:
**`https://github.com/JuliaLang/julia/blob/master/doc/src/manual/types.md)`**

On the top right corner of the file, there is **`Raw`**, **`Blame`** and then a **`✎`** object. Click on that **`✎`** object, and then it will open up the file.

Edit it as appropriate to the correct details and then `Commit Changes` and `Create a pull request`.


Above all, on Julia's README.md, it provides a section on **Source Code Organisation**. Read that to get a better overview.
