### ISSUE TITLE
Proposal: Better linear algebra benchmarks

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#4668]
Continuing from the discussion in #4651 with @staticfloat:
- [ ] The benchmarks currently report everything relative to the C timings. This is useful for many of the reported tests, but less so for the linear algebra benchmarks. For these tests, it is customary to report effective FLOPS, e.g.
  - [NCSA BLAS Performance Comparison](http://www.ncsa.illinois.edu/UserInfo/Perf/BLAS/) (2003)
    ![DGEMM benchmark](http://www.ncsa.illinois.edu/UserInfo/Perf/BLAS/img/ia64_2-dgemm.png)
  - [nVidia CUBLAS](https://developer.nvidia.com/cublas) (2011)
    ![CUBLAS batched GEMM](https://developer.nvidia.com/sites/default/files/akamai/cuda/images/CUDALibs/cublas_41_matrix.jpg)
  
  We should probably report our linear algebra benchmarks in effective FLOPS.
- [ ] Benchmarks results should be rendered nicely using Julia and packages such as [Gadfly](https://github.com/dcjones/Gadfly.jl). (@StefanKarpinski)

**Comment by KristofferC** [comment]
This seems to be mostly general discussion about benchmarking strategies which we now have a good system for with Nanosoldier. This also includes a number of different linear algebra benchmarks.
