### ISSUE TITLE
Version 1.8.1 running issues

### ISSUE THREAD

**Issue by ProfLeao** [JuliaLang/julia#46699]
I just tried to run version 1.8.1 and came across the following message.

`ERROR: Unable to load dependent library /home/reginaldo/JuliaLanguage/julia-1.8.1/bin/../lib/julia/libopenlibm.so
Message:/home/reginaldo/JuliaLanguage/julia-1.8.1/bin/../lib/julia/libopenlibm.so: cannot open shared object file: No such file or directory
`

I use the following execution method:

`export PATH="$PATH:/home/reginaldo/JuliaLanguage/julia-1.8.1/bin"
`

My system is:
 `Linux reginaldo-desktop 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by ViralBShah** [comment]
You probably have something in your LD_LIBRARY_PATH that is interfering.

**Comment by mgkuhn** [comment]
Does the file `/home/reginaldo/JuliaLanguage/julia-1.8.1/lib/julia/libopenlibm.so` exist on your system?

**Comment by ProfLeao** [comment]
> Does the file `/home/reginaldo/JuliaLanguage/julia-1.8.1/lib/julia/libopenlibm.so` exist on your system?

Does not!

**Comment by ProfLeao** [comment]
That's weird! I redownloaded the 64-bit (glibc) and then it worked normally. Have there been any changes to the content of julia-1.8.1-linux-x86_64.tar.gz?

**Comment by ViralBShah** [comment]
Could be a local filesystem error when installing or something the first time.
