### ISSUE TITLE
Upgrade julia version from the REPL

### ISSUE THREAD

**Issue by curio-sitas** [JuliaLang/julia#46698]
It would be nice and clean to have a way to upgrade julia to a new version (or even switch between them) directly from the REPL.
The package environment may be transfered and updated at the same time.

One may implement this as a julia command or a `Pkg.jl` REPL command.

For example one could implement a command :
```
] switch 1.7.3
```

**Comment by giordano** [comment]
Do you know [juliaup](https://github.com/JuliaLang/juliaup)? It doesn't work from the Julia REPL, but you can always run the commands you want from the shell mode of the REPL

**Comment by curio-sitas** [comment]
I knew it existed. But wouldn't it be nice to have these capabilities natively ?

**Comment by ufechner7** [comment]
Even better if a compatible Julia version would automatically be launched depending on the compat entry of Project.toml...

**Comment by mgkuhn** [comment]
This would basically involve
- trying to detect how the currently running julia binary was installed and deciding if the current user has permissions to rerun that installation procedure
- running a little shell command line as a detached background process that tries to start that installation procedure after having waited for the current julia process to terminate
- terminating the current julia process (or even all julia processes running the same binary), especially on Windows, where mandatory file locking does not permit applications to run while they are being replaced

The practical problem is that there are many different ways of installing Julia, and these are quite platform dependent.

It's doable, in some circumstances, on some platforms, with lots of restrictions, but I'm not convinced it is worth the effort.

**Comment by KristofferC** [comment]
Using juliaup is the intended solution to this. Issues using it can be opened on that repo.
