### ISSUE TITLE
power operator "^" gives wrong answer.

### ISSUE THREAD

**Issue by fedeinthemix** [JuliaLang/julia#46711]
The Julia manual states that `x^y` raises `x` to the `y`th power. Yet
```julia
julia> 2^2^2^2^2
0
```
An overflow should not silently produce a result, but signal a problem!

**Comment by DilumAluthge** [comment]
https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior

Please ask further questions on the Julia Discourse: https://discourse.julialang.org/

**Comment by PallHaraldsson** [comment]
FYI: There's https://github.com/JuliaMath/CheckedArithmetic.jl

and maybe Julia's docs should point to it (make a PR?).

another way is:
```
julia> big(2)^2^2^2^2 # results in very large value (more than a screenful), likely not useful to you.
```

**Comment by fedeinthemix** [comment]
The example that I gave is just a random one, not a particularly interesting one. I missed the section (quite separate from the list of numerical operators) stating that by default Julia is working with modulo arithmetic. I'm surprised as, with this strategy, overflow can be difficult to detect.

Thanks for the pointers! I will check them out.

**Comment by jakobnissen** [comment]
@fedeinthemix yeah it can be a nasty surprise and it's understandable that one might think Julia should detect overflow. See the Julia FAQ for why it's not practically feasible in a high-performance language: https://docs.julialang.org/en/v1/manual/faq/#faq-integer-arithmetic

**Comment by PallHaraldsson** [comment]
>it's understandable that one might think Julia should detect overflow. See the Julia FAQ for why it's not practically feasible in a high-performance language

It's actually possible, if you use floating-point, then it is detected, and you get an Inf. Not an exception right away though. I believe checking can be done fast though for integers, but that's another story.

**Comment by DilumAluthge** [comment]
Please continue this discussion on Discourse.
