### ISSUE TITLE
`extrema([3,7,4]')` throws

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#46714]
In Julia 1.8 and master:
```julia
ulia> extrema([3,7,4]')
ERROR: MethodError: no method matching adjoint(::Tuple{Int64, Int64})
  ...
```
whereas in 1.7 as expected:
```
julia> extrema([3,7,4]')
(3, 7)
```

I guess in the new `extrema` implementation the transpose somehow is propagated through the computation and then applied to the result-tuple.

**Comment by mcabbott** [comment]
Caused by #39513, sorry.

**Comment by mauro3** [comment]
No worries!  Monkey-patching with `Base.extrema(a::LinearAlgebra.Adjoint) = extrema(a')` is an easy band-aid.
