### ISSUE TITLE
Add usage details for Base.eachsplit

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#46751]
I am reading through the docs for `[Base.eachsplit](https://docs.julialang.org/en/v1/base/strings/#Base.eachsplit)` and right now its use case is not clear to me. I see that the type it returns is different than `split`, but the current example does not make it clear why I would want to use it instead of just `split`:

```julia
julia> split(a, ".")
2-element Vector{SubString{String}}:
 "Ma"
 "rch"

julia> collect(eachsplit(a, "."))
2-element Vector{SubString}:
 "Ma"
 "rch"
```

**Comment by jakobjpeters** [comment]
It looks like ```split``` primarily calls ```collect``` on ```eachsplit```. https://github.com/JuliaLang/julia/blob/afb6c60d69a38e8a2442a0c7e87c47b8880ad294/base/strings/util.jl#L592-L596
The example for [```eachsplit```](https://docs.julialang.org/en/v1/base/strings/#Base.eachsplit) could be made to match that for [```eachmatch```](https://docs.julialang.org/en/v1/base/strings/#Base.eachmatch).

``` julia
julia> a = "Ma.rch"
"Ma.rch"

julia> b = eachsplit(a, ".")
Base.SplitIterator{String, String}("Ma.rch", ".", 0, true)

julia> collect(b)
2-element Vector{SubString}:
 "Ma"
 "rch"
```
