### ISSUE TITLE
CI: Intermittent failure in SparseArrays/linalg_solvers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#46782]
https://buildkite.com/julialang/julia-master/builds/15844#01833fe4-8c0b-4337-8a04-a9201cf2be28
```
Error in testset SparseArrays/linalg_solvers:
--
  | Test Failed at /cache/build/default-amdci4-2/julialang/julia-master/julia-eff8db6237/share/julia/stdlib/v1.9/SparseArrays/test/linalg_solvers.jl:134
  | Expression: 0.99 <= (cond(Ar, 1) \ opnorm(Ar, 1)) * opnorm(inv(Array(Ar)), 1) < 3
  | Evaluated: 0.99 <= 3.044118633846665 < 3
```

@Wimmerer could you take a look at what the test is doing? Looks like it's just barely exceeding the upper bound. We do have an rr trace available if we need it, but maybe it's easy to fix, just by looking at the test.

**Comment by Wimmerer** [comment]
@andreasnoack is it acceptable to adjust the upper bound on the tolerance here slightly? It looks like this was discussed in https://github.com/JuliaLang/julia/issues/14778 a bit. 

I'm not sure why this hasn't occurred before though, there shouldn't have been any changes to that code path as far as I'm aware.

**Comment by ViralBShah** [comment]
It's easy to reproduce this one - by running in a loop. However, extracting the failing example and running again does not produce the same value. So, probably some solver corruption or bug.

Try:
```
julia> x=[];
          try; for i=1:100000
           A = sparse(reshape([1.0], 1, 1))
           Ac = sprandn(20, 20,.5) + im*sprandn(20, 20,.5)
           Ar = sprandn(20, 20,.5) + eps()*I
           @test cond(A, 1) == 1.0
           # For a discussion of the tolerance, see #14778                                                              
           @test 0.99 <= cond(Ar, 1) \ opnorm(Ar, 1) * opnorm(inv(Array(Ar)), 1) < 3
           @test 0.99 <= cond(Ac, 1) \ opnorm(Ac, 1) * opnorm(inv(Array(Ac)), 1) < 3
           @test 0.99 <= cond(Ar, Inf) \ opnorm(Ar, Inf) * opnorm(inv(Array(Ar)), Inf) < 3
           @test 0.99 <= cond(Ac, Inf) \ opnorm(Ac, Inf) * opnorm(inv(Array(Ac)), Inf) < 3
       end; 
       catch; 
          x = Ar; 
       end
Test Failed at REPL[64]:7
  Expression: 0.99 <= (cond(Ar, 1) \ opnorm(Ar, 1)) * opnorm(inv(Array(Ar)), 1) < 3
   Evaluated: 0.99 <= 3.5395191135821635 < 3
20×20 SparseMatrixCSC{Float64, Int64} with 195 stored entries:

julia> (cond(x, 1) \ opnorm(x, 1)) * opnorm(inv(Array(x)), 1)
1.0000000000000009
```

**Comment by ViralBShah** [comment]
The issue is with sparse versions of `cond(Ar, 1)` and `cond(Ar, Inf)`. I have seen both fail. Running on the same `Ar` matrix repeatedly leads to about 2% of the cases giving the wrong value.

**Comment by Wimmerer** [comment]
Okay, I'll run some tests. How wrong were the values on average?

**Comment by ViralBShah** [comment]
I got various different wrong values across runs. I am guessing the issue is the solve in `opnormestinv`.

**Comment by ViralBShah** [comment]
Is this still an issue?
