### ISSUE TITLE
Printing recursive structures results in infinite loop

### ISSUE THREAD

**Issue by stefkuypers** [JuliaLang/julia#46798]
I wonder whether auto detection of recursive structure instances could be integrated in the core printing functions of those structures.
Currently, if I have struct A referring to an instance of struct B and struct B refers to an instance of struct A and I want to print the result I get stuck in an infinite loop.
Having to write a new Base.show() function for each of those structures seems to be rather cumbersome and I can not see a reason why this should be necessary.

**Comment by KristofferC** [comment]
> Currently, if I have struct A referring to an instance of struct B and struct B refers to an instance of struct A and I want to print the result I get stuck in an infinite loop.

```
julia> mutable struct A a end

julia> mutable struct B b end

julia> a = A("foo")
A("foo")

julia> b = B(a)
B(A("foo"))

julia> a.a = b
B(A(B(#= circular reference @-2 =#)))
```
Maybe you can elaborate

**Comment by stefkuypers** [comment]
Seems I was jumping to conclusions. It took forever to print a structure and I thought it had to do with circular references. Severely reducing the size does produce a print though. My apologies.
