### ISSUE TITLE
REPL History is not shown when there is a blank line in the history file

### ISSUE THREAD

**Issue by felixcremer** [JuliaLang/julia#46873]
If you have a fully blank line in the REPL history file like in the example below, the repl history is still written to the history file, but it is not displayed in the REPL anymore. 
Only the REPL history up to the first blank line is shown. 
If you use the below code as your repl_history file you will only get `a=1` and `a=2` as entries by hitting the up arrow. 
The `a=2` line seems to be shown, because the line after `a=1` is not empty but is having a tab and therefore is shown in the REPL as a new line. 

This is a regression which was first introduced in Julia 1.6 and is still happening on the current master. 

Content of the repl_history.jl file:

```julia
# time: 2022-09-23 16:39:57 CEST
# mode: julia
	a = 1 
	
# time: 2022-09-23 16:44:31 CEST
# mode: julia
	a = 2

# time: 2022-09-23 16:45:47 CEST
# mode: julia
	b = 5
```

**Comment by KristofferC** [comment]
Could potentially have something to do with https://github.com/JuliaLang/julia/pull/37437.

**Comment by felixcremer** [comment]
When I first encountered this, I was using the Diary.jl package, so this might be involved in putting the empty lines in the history file. The history is still not fully shown after removing Diary.jl from the startup.

**Comment by KristofferC** [comment]
> When I first encountered this, I was using the Diary.jl package, so this might be involved in putting the empty lines in the history file.The history is still not fully shown after removing Diary.jl from the startup.

If Diary.jl corrupts the history file, removing loading it will not help, you need to repair the file.
