### ISSUE TITLE
Parsing of `.field` and `.property` syntax allows space

### ISSUE THREAD

**Issue by thchr** [JuliaLang/julia#46875]
I was surprised to see that this is allowed:
```jl
julia> struct A
           a :: Int
       end

julia> A(1).             a
1
```
I.e., the lowered code just disregards the spaces:
```jl
julia> @code_lowered A(1).            a
CodeInfo(
1 ─      nothing
│   %2 = Base.getfield(x, f)
└──      return %2
)
```
A similar thing happens for `getproperty`.

I imagine that it is not a good idea to fix/change this in Julia v1.x, since there could well be plenty of typos out there that implicitly depend on this - but I was suggested to file an issue for it anyway; at least there's a record of the thought this way.

**Comment by mbauman** [comment]
It looks like we talked about deprecating this in #11891, but perhaps its error message wasn't good enough to make the final cut?

**Comment by thchr** [comment]
Ah, okay: those are clearly overlapping. One of the linked threads also had this comment https://github.com/JuliaLang/julia/issues/29781#issuecomment-432912126, which is a reasonable argument for allowing this.

Since this has already been discussed at some length, there is probably little need for another issue: I'll close this.
