### ISSUE TITLE
Internal errors slipping through PkgEval

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#46904]
Some internal errors do not make julia crash/error, but just print out thousands of lines of backtrace and then julia proceeds as if nothing happened. I have no opinion on whether this is desirable for normal users, but it unfortunately makes these errors also slip through PkgEval. For example, according to https://raw.githubusercontent.com/JuliaCI/NanosoldierReports/master/pkgeval/by_date/2022-09/21/report.md, Hecke passed it tests, but looking at the specific log at https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-09/21/Hecke.primary.log, one sees that an internal error occurred (which was quickly fixed in https://github.com/JuliaLang/julia/pull/46877).

**Comment by DilumAluthge** [comment]
For PkgEval, in theory we could automatically grep the log for messages like that.

**Comment by maleadt** [comment]
Coincidentally, I just added detection for these errors to PkgEval a couple of days ago: https://github.com/JuliaCI/PkgEval.jl/commit/05a9a17e8efd9b3822035bb4fcbac772fbce9f17. However, this only triggers when the tests fail, which isn't the case here. I'll fix this in PkgEval.jl (which would also be a better place to file such issues).
