### ISSUE TITLE
Request: Julia warn on use (*access of*) global variables (as a debug mode)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#46924]
The feature request should of course go here.

I think it should be a simple CLI feature to do with either:
```
julia --globals=off
```
and/or:

```
julia --debug
```
I have more ideas for the --debug flag, so possibly start with the other, see here:
https://discourse.julialang.org/t/request-julia-debug-mode/87832
>Such as disable `@inbounds`, `@inline` and run with `-O0`. You could also call it a scripting mode.

I'm not sure, maybe I even uncovered a bug in Julia, see on discourse, otherwise unclear about use of global keyword.

**Comment by oscardssmith** [comment]
what about `const` globals and globals in Base? Do you want an error when you call `exp`?

**Comment by PallHaraldsson** [comment]
>what about const globals and globals in Base? Do you want an error when you call exp?

No, I rather NOT want to error (or even warn) on exp... And to error would mean changing the code of exp, so when I think about it, maybe as a lesser option it should only warn when a function is defined. Then the option could be the default for the REPL:

```
julia> sum(a, B) = a + b
[IN RED] b is not defined as a local variable, likely bug, will fail at runtime or access global variable. sum (generic function with 1 method)
```

The compiler must figure out already that b isn't a local variable, a likely typo (or intended), so it shouldn't cost much, even only having a flag telling you there's some such variable, or keep count, showing first such name and count of more if there are would be helpful.

**Comment by JeffBezanson** [comment]
It's quite normal to define functions that access globals (often other functions) that aren't defined yet. It does make sense to have a tool to find potential uses of undefined variables, but that is the domain of linting tools and I don't think we are going to build this in.
