### ISSUE TITLE
Make variables defined in `try` visible from `else`

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#46928]
In a `try`/`else` I usually want to refer to a variable defined in the `try` but it's not available unless I put `local x` before the `try`.

```jl
julia> try
         x = 1
       catch 
         nothing
       else
         println(x)
       end
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:5
```

**Comment by petvana** [comment]
I'd like to mention that `try`/`catch`/`else` seems undocumented now in Julia.

**Comment by jpsamaroo** [comment]
One could also argue that the same should be done for `catch` and `finally`; however doing so might lead to very confusing behavior for users when variables may not have become defined (because an exception was encountered) partway through the `try` block.

**Comment by petvana** [comment]
Btw, [Python's docs](https://docs.python.org/3/tutorial/errors.html) provides an explicit example of a new local variable `f`
``` python


for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except OSError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

**Comment by jariji** [comment]
In Python the variable escapes all the way, which we might not want.

```py

In [2]: try:
   ...:     x = 1
   ...: except:
   ...:     pass
   ...: 

In [3]: x
Out[3]: 1
```

**Comment by IanButterworth** [comment]
@simeonschaub bump on this, and the documentation.

I tried to come up with a definitive example for the docs to PR but couldn't decide on a brief one.

**Comment by simeonschaub** [comment]
`try`, `catch` and `finally` have always introduced new scope blocks, so this is too late to change now without causing silently wrong results in existing code. Declaring `x` local to the surrounding scope is the correct way to achieve this.

I will try to come up with some docs for this
