### ISSUE TITLE
Have same to GC options of Go, i.e. the missing GOGC

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#46949]
I.e. this one (also as CLI and/or ENV var):
https://pkg.go.dev/runtime/debug#SetGCPercent
>SetGCPercent sets the garbage collection target percentage: a collection is triggered when the ratio of freshly allocated data to live data remaining after the previous collection reaches this percentage. SetGCPercent returns the previous setting

https://discourse.julialang.org/t/gc-settings-go-now-has-2-adopted-ours-we-should-adopt-theirs-go-runtime-4-years-later/87843

@chflood, you are doing good work on the GC. Do you think it makes sense to add their other option (their first), and can it be done before the feature freeze? I'm not sure I'm up-to-speed to do it, but it seems like a simple thing, so maybe someone can, or I can with some guidance.

**Comment by JeffBezanson** [comment]
This one I assume: https://pkg.go.dev/runtime/debug#SetGCPercent ?

**Comment by JeffBezanson** [comment]
IIUC, this basically sets what we would call the default collection interval, or young generation size. I'm not sure that would be useful for us. Minor collections are very fast. When they are effective, I don't believe they consume enough run time for it to be worth it to try to do them less often. When they are not effective, we grow the interval automatically. So we would need some compelling evidence that you really need to set this manually sometimes.

**Comment by JeffBezanson** [comment]
Also, in the future, please try to make issues self-contained. Don't just link to something and assume somebody else will read through it to figure out what is being proposed.

**Comment by PallHaraldsson** [comment]
Sorry, yes of course. I just thought GOGC well known (at least to GC the experts), since Go's GC best in-class, and GOGC previously its own knob. I edited the issue.

**Comment by PallHaraldsson** [comment]
>When they are not effective, we grow the interval automatically

Is that related to GC issues we DO have? I know we have issues, I think mainly with threads (solved on master?).

**Comment by oscardssmith** [comment]
we have a number of issues currently. the first is that our gc is relatively slow. the second is that it isn't multithreaded, so in multi threaded programs gc can be bad. the third problem is that our allocators are slower then they should be. I might be forgetting some other problems, but those are the big ones.

**Comment by JeffBezanson** [comment]
> Is that related to GC issues we DO have?

By "not effective" I mean when they don't free anything because there is no young garbage.

**Comment by d-netto** [comment]
We've been moving in the direction of automating our "GC intervals computation" -- how much we can allocate between Nth and (N+1)th GC -- as much as possible, as opposed to providing GC tuning knows.

The 1.10 heuristics and the MemBalancer-based 1.11 heuristics do that.

I assume this issue can be closed?
