### ISSUE TITLE
chop bug with String7

### ISSUE THREAD

**Issue by rsturley** [JuliaLang/julia#46964]
`chop`  returns an incorrect result in some cases when working with String7 types from the CSV package.
The issue appears to be incorrect handling of multibyte UTF-8 data at the end of the string.

Here is a program that illustrates the problem:
```
using CSV
function ShowBug()
    x::String7 = "Bü\n"
    dump(x)
    dump(chop(x))
end
ShowBug()
```
This returns the following:
```
String7 "Bü\n"
String7 "B\xc3"
```
Running the program with a String data type instead of String7 works fine. It returns
```
String "Bü\n"
SubString{String}
  string: String "Bü\n"
  offset: Int64 0
  ncodeunits: Int64 3
```

```
versioninfo()
Julia Version 1.8.1
Commit afb6c60d69 (2022-09-06 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, icelake-client)
  Threads: 1 on 8 virtual cores
```

**Comment by KristofferC** [comment]
Should this have been opened at https://github.com/JuliaStrings/InlineStrings.jl?
