### ISSUE TITLE
Incorrect env computed for trivial UnionAll over Union

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#46970]
subtyping forgets to incorporate TypeVar-matched parameters from a Union into the env:
```
julia> (ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), Union{S, AbstractMatrix{Int}} where S<:AbstractMatrix, AbstractMatrix); env
svec(Int64) # should be svec(T)
```
```
julia> T = ccall(:jl_new_structv, Any, (Any, Ptr{Cvoid}, UInt32), Union, [S, S], 2) where S<:AbstractMatrix;

julia> (ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), T, AbstractMatrix); env
svec(#undef) # should be svec(T)
```

**Comment by N5N3** [comment]
The first example looks similar to #41096. Deserve to check if this comes from
https://github.com/JuliaLang/julia/blob/9fd408723aab0974f399b8ffc952af4b4d20b6f7/src/subtype.c#L2155-L2165
where the env change is not restored between 2 `intersect_all`.

**Comment by vtjnash** [comment]
I think `u` has_free_typevars here, so maybe similar, but not exactly?

**Comment by N5N3** [comment]
You are right.
Just notice that `Union{S, AbstractMatrix{Int}} where S<:AbstractMatrix` <: `AbstractMatrix`. So `intersect_all` would not be hitted anyway.

**Comment by vtjnash** [comment]
In this case, I think it sees that they are `==` as jl_value_t* pointers, and then fails to copy the env right then (we have code much later to fix up these cases just before returning)

**Comment by N5N3** [comment]
Exactly, we hit this branch
https://github.com/JuliaLang/julia/blob/e6d99792e6dd0cffe41e98b8d642cf07e64364c5/src/subtype.c#L563-L566
where `x === y === AbstractMatrix`, thus `subtype_unionall` would not be called for `S <: AbstractMatrix`
Remove this fast-path for `y <: Unionall` should fix the examples above.

**Comment by vtjnash** [comment]
I guess that should still be fast, since it will stop when it reaches the inside of the UnionAll, and in the meantime will fill out the env (exactly as we want)?

**Comment by N5N3** [comment]
I tried to bench this extreme case with the above patch
```julia
@eval abstract type A{$((Symbol(:T,i) for i in 1:1000)...)} end
B = @eval A{$((:Int for i in 1:1000)...)}

@eval abstract type C{$((Symbol(:T,i) for i in 1:10)...)} end
D = @eval C{$((:Int for i in 1:10)...)}

julia> @btime typeintersect($(Union{S, D} where S<:C), $C)
  23.600 μs (212 allocations: 24.31 KiB) # 14.600 μs (117 allocations: 15.25 KiB) on master

julia> @btime typeintersect($Union{S, B} where S<:A, $A)
  1.737 s (505503 allocations: 92.04 MiB) # 25.128 ms (1003 allocations: 23.01 MiB) on master
```
But the regression should be rare. I think we can revist it if it does have a pratical usecase
