### ISSUE TITLE
`clamp` returns wrong result if lower > upper

### ISSUE THREAD

**Issue by biona001** [JuliaLang/julia#46992]
When lower and upper bounds are ill-specified, e.g. `lower > upper`, `clamp` does something that seems unintuitive to me
```julia
lower = 2
upper = 1
clamp(0, lower, upper) # returns 2
```
Maybe it makes more sense to throw an error or a `NaN`?

This behavior is true on Julia 1.6 and 1.7

**Comment by bvdmitri** [comment]
That is the documented behaviour:

```
clamp(x, lo, hi)

  Return x if lo <= x <= hi. If x > hi, return hi. If x < lo, return lo. Arguments are promoted to a common type.
```

in your example `0 < 2` (`x < lo`) and `0 < 1` (not `x > hi`) so according to the docs it returns `2`.

**Comment by biona001** [comment]
Alright, I don't insist on change, it just seems quite unintuitive behavior..

**Comment by oscardssmith** [comment]
it would be reasonable to put an assert here, but IMO, status quo is fine.
