### ISSUE TITLE
Predicate version of allequal

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#47005]
Like some other functions, e.g. `all`, `findall`, I sometimes want the predicate version of allequal:

`allequal(f, itr) = isempty(itr) ? true : all(x -> isequal(f(x), f(first(itr))), itr)`

Ref: https://github.com/JuliaLang/julia/issues/43353#issuecomment-1264357512

Cc: @CameronBieganek

**Comment by jlapeyre** [comment]
I worked on this for myself, then found this issue. So I'll post it here.

* There are some efficiency gains, eg using `peel` that would help even with the current implementation
* I also added an argument that specifies returning the common value. I'm thinking of common tasks similar to `LinearAlgebra.check_square`. This would take some thought to do in a uniform way across Julia. Some things like this are in the ecosystme. Really, what would be convenient is to get the common string length an array of strings and throw an error if they differ.
* The methods with `Val{true}` might need to use `Some` or something like that.

```julia
# peel is significantly faster for short itr and early exit from all
function Base.allequal(func, itr)
    isempty(itr) && return true
    itr1, itr_rest = Iterators.peel(itr)
    val = func(itr1) # faster if we lift this from loop, even without peel
    return all(x -> isequal(func(x), val), itr_rest)
end

# Return the common value if all are equal, otherwise false
function Base.allequal(itr, ::Val{true})
    isempty(itr) && return nothing
    itr1, itr_rest = Iterators.peel(itr)
    return all(x -> isequal(x, itr1), itr_rest) ? itr1 : false
end

function Base.allequal(func, itr, ::Val{true})
    isempty(itr) && return nothing
    itr1, itr_rest = Iterators.peel(itr)
    val = func(itr1)
    return all(x -> isequal(func(x), val), itr_rest) ? val : false
end

Base.allequal(func, itr, ::Val{false}) = allequal(func, itr)
```

I think this is very common
```julia
common_property = allequal_throw(some_property, itr)  # throw error if not all equal,
```
Maybe we need to allow passing a function to call that throws.

**Comment by jlapeyre** [comment]
That's close. But `only(unique(length, ["a", "b", "c"])) == "a"`. I want it to return `1`.

**Comment by GregPlowman** [comment]
I guess you want `only(unique(length(x) for x in ["a", "b", "c"]))`

**Comment by jlapeyre** [comment]
That has to call the function on every element. The implementation of `Base.allequal(func, itr, ::Val{true})` will exit at the first element that differs from the first.
