### ISSUE TITLE
Inconsistent behavior of `map!` with regard to source and destination shapes

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/julia#47002]
According to the [docstring for `map!`](https://docs.julialang.org/en/v1/base/collections/#Base.map!), the destination must be at least as large as the smallest input collection. However, this is not enforced for some array types:

```julia
julia> x = zeros(2);

julia> map!(sqrt, x, 1:3)
2-element Vector{Float64}:
 1.0
 1.4142135623730951

julia> map!(+, x, 1:3, 1:3)
2-element Vector{Float64}:
 2.0
 4.0
```

Meanwhile, for `BitArray` the actual rule is that the destination and all the inputs must have the same shape:

```julia
julia> a = BitVector([0, 0])
2-element BitVector:
 0
 0

julia> map!(&, a, BitVector([1, 0, 1]), BitVector([1, 1, 1]))
ERROR: DimensionMismatch: sizes of dest, A, and B must all match
```

Based on the docstring, this should work, but it doesn't:

```julia
julia> b = BitVector([0, 0, 0])
3-element BitVector:
 0
 0
 0

julia> map!(&, b, BitVector([1, 0]), BitVector([1, 1, 1]))
ERROR: DimensionMismatch: sizes of dest, A, and B must all match
```

**Comment by mcabbott** [comment]
Duplicate of #46707?

**Comment by CameronBieganek** [comment]
Yeah, looks like a dup, except for the last part about `BitVector`. I'll close this and open a new issue, since it's cleaner than editing.

**Comment by CameronBieganek** [comment]
The new `BitVector` issue is #47011.
