### ISSUE TITLE
Nightly build crash when runing some GMT tests that call functions in the GDAL lib

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#47003]
Hi,

This is not very easy to demonstrate but I' try. Julia nightly now (since some weeks, don't know more) crash when I run the GMT.jl tests. 
Digging around I could find a patch that simply consist in accessing the pointer before sending it to the crashing ``ccall`` call. An example of such is provided in this [line ](https://github.com/GenericMappingTools/GMT.jl/blob/master/src/gdal.jl#L1763). With that line commented, on Windows I can reproduce the crash with
```
julia> ds_point = GMT.Gdal.read(joinpath(dirname(pathof(GMT)), "..", "test")*"\\point.geojson")
GDAL Dataset (Driver: GeoJSON/GeoJSON)
File(s):
  C:\Users\joaqu\.julia\dev\GMT\src\..\test\point.geojson

Number of feature layers: 1
  Layer 0: point (Point)


julia> layer = GMT.Gdal.getlayer(ds_point, 0);

julia> layer
Layer: point (1)
  Geometry 0 (`1�f�): [1], POINT (100 0), POINT (100.2785 0.0893), ...

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff66fa1440 -- OGR_Fld_GetType at C:\programs\compa_libs\DLLs_VC14_64\gdal_w64.dll (unknown line)
in expression starting at none:0
OGR_Fld_GetType at C:\programs\compa_libs\DLLs_VC14_64\gdal_w64.dll (unknown line)
Allocations: 6857399 (Pool: 6853216; Big: 4183); GC: 8
```
Uncomment that line and the above works. But this is not a Windows only problem. This linux nightly build failed for the same reason, whilst [this one](https://github.com/GenericMappingTools/GMT.jl/actions/runs/3165572016/jobs/5154693157) with julia 1.7 completed successfully (the linux build failed in this run but for a totally different reason).

**Comment by jmkuhn** [comment]
I think this is the first commit that displays this issue is: 62ac26a4b061d829567fe4d77879bb591e874c41 https://github.com/JuliaLang/julia/pull/46651

**Comment by vtjnash** [comment]
There are no `@GC.preserve`s in that file, so the GC is allowed to delete the object as soon as it concludes that the only field used is `.ptr`, and thus it (correctly) deletes the object immediately (as instructed)

**Comment by joa-quim** [comment]
Thanks. Very helpful.
