### ISSUE TITLE
Request for removing 'end' in conditional statements

### ISSUE THREAD

**Issue by anmolspace** [JuliaLang/julia#47047]
Was requiring 'end' at the end of each conditional statement really necessary? If Python can get around without using them then why can't Julia? What meaningful purpose does it serves? If it doesn't then will it be possible to remove it in Julia 2.0 ?

Similarly, why single inverted commas reserved for single characters ('a') and double inverted commas for strings ("abc")? How is it useful, and what purpose does it serve?  If it doesn't then will it be possible remove such distinction it in Julia 2.0 ?

**Comment by PallHaraldsson** [comment]
Julia took end syntax from MATLAB. In Python indenting is meaningful. Many people dislike that, so it's not happening in Julia. FYI: https://github.com/TotalVerb/PythonSyntax.jl

You can also do, if number of lines is your problem:
```
cond ? if_true() : else_false_code()

or:

cond && if_true()
```

**Comment by StefanKarpinski** [comment]
Please ask questions on the [Julia discourse](https://discourse.julialang.org/) discussion forum.
