### ISSUE TITLE
`@timed` does not report compile/recompile times whereas `@time` does.

### ISSUE THREAD

**Issue by iago-lito** [JuliaLang/julia#47056]
I'm interested in collecting compile/recompile time of the expressions I'm evaluating because they happen to be large and automatically generated.

I can read compilation time from my screen when using `@time`, but when I attempt to collect this information as data for later use with `@timed` instead, the compilation/recompilation times seem not to appear within the resulting `NamedTuple`.

As a workaround, I'm using `Base.cumulative_compile_tim*` functions because I've found in the sources that this is what `@time` is using under the hood. But they are not documented and I'm unsure how or whether I'm supposed to do this.

Can the compilation/recompilation times be added to the output of `@timed`?  
As an alternative, will the `Base.cumulative_compile_tim*` functions be eventually documented and/or exported?

**Comment by ericphanson** [comment]
it seems to me that `@time` and `@timev` should be implemented by printing results from `@timed`, instead of all 3 having separate implementations. Then `@timed` would always have all the programmatic info. (Prompted by #52883)
