### ISSUE TITLE
Non-Mutating Product of arbitrarily many `Givens` or `Rotation`s

### ISSUE THREAD

**Issue by manuelbb-upb** [JuliaLang/julia#47082]
# Summary
I sometimes want to apply multiple consecutive Givens rotations and noticed that many product operations are not supported as of yet. I am not sure whether or not this is intentional to enforce certain good practices, but I feel it is a bit counterintuitive.

# System Information
1. The output of `versioninfo()`: 
    ```
    Julia Version 1.8.2
    Commit 36034abf260 (2022-09-29 15:21 UTC)
    Platform Info:
        OS: Linux (x86_64-linux-gnu)
        CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
        WORD_SIZE: 64
        LIBM: libopenlibm
        LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
        Threads: 4 on 8 virtual cores
    Environment:
        JULIA_REVISE_WORKER_ONLY = 1
    ```
2. How you installed Julia: By downloading the current stable from [the official website](https://julialang.org/downloads/) and extracting the binary file.

# Examples

## Non-Associative Product of Multiple Givens Matrices with Array
```julia
d = rand(3)
l = d[1]
# eliminate third element:
g3, l = givens(l, d[3], 1, 3)
# eliminate second element from result:
g2, l = givens(l, d[2], 1, 2)
```
Now, `g2*(g3*d)` works as expected, but `g2*g3*d = (g2*g3)*d` gives
```
MethodError: no method matching lmul!(::LinearAlgebra.Rotation{Float64}, ::Vector{Float64})
```
I guess, the fix for this should be relatively simple, as `lmul!(R::Rotation, A::AbstractMatrix)` is defined (and `(g2*g3)*reshape(d,3,:)` works).
Can we simply change `AbstractMatrix` to `AbstractVecOrMat` in the signature?

## Non-Mutating Product of Rotation and Givens Operations
This issues also encapsulates the case of multiplying more than two Givens operations.
```julia
d = rand(4)
l = d[1]
# eliminate 4th element:
g4, l = givens(l, d[4], 1, 4)
# eliminate 3rd and 2nd element from result:
g3, l = givens(l, d[3], 1, 3)
g2, l = givens(l, d[2], 1, 2)

g2*g3*g4
```
This gives
```
MethodError: no method matching *(::LinearAlgebra.Rotation{Float64}, ::LinearAlgebra.Givens{Float64})
```
Likewise, `g2*(g3*g4)` gives
```
MethodError: no method matching *(::LinearAlgebra.Givens{Float64}, ::LinearAlgebra.Rotation{Float64})
```
Similar to the mutating method `lmul!(G::Givens, R::Rotation)` (I don't see `rmul!`), we could define
```julia
*(G::Givens, R::Rotation) = Rotation(vcat(R.rotations, G))
*(R::Rotation, G::Givens) = Rotation(vcat(G, R.rotations))
```

**Comment by dkarrasch** [comment]
> Can we simply change `AbstractMatrix` to `AbstractVecOrMat` in the signature?

I think so, yes, since it just calls consecutively `lmul!(G::Givens, A::AbstractVecOrMat)`.

> Similar to the mutating method lmul!(G::Givens, R::Rotation) (I don't see rmul!), we could define

Yes. And `*(G::Givens...) = Rotation([G...,])` (or `[reverse(G)...,]`, but that should be the same).
