### ISSUE TITLE
improve inference of `keys(::Dict{String})` to fix invalidations

### ISSUE THREAD

**Issue by ranocha** [JuliaLang/julia#47089]
Can we improve inference of the following snippet?

```julia
julia> code_warntype(keys, (Dict{String},))
MethodInstance for keys(::Dict{String})
  from keys(a::AbstractDict) in Base at abstractdict.jl:105
Arguments
  #self#::Core.Const(keys)
  a::Dict{String}
Body::Base.KeySet{String, _A} where _A<:(AbstractDict{String})
1 ─ %1 = Base.KeySet(a)::Base.KeySet{String, _A} where _A<:(AbstractDict{String})
└──      return %1
```

I am using Julia v1.8.2. I think the return type should be inferred more concretely, with `_A<:(Dict{String})` and not `_A<:(AbstractDict{String})`. This would fix a big amount of invalidations, e.g.,

```julia
julia> import Pkg; Pkg.activate(temp=true); Pkg.add("DataStructures")

julia> using SnoopCompileCore; invalidations = @snoopr(using DataStructures); using SnoopCompile

julia> length(uinvalidated(invalidations))
482

julia> trees = invalidation_trees(invalidations)
...
 inserting iterate(v::Union{Base.KeySet{<:Any, <:SwissDict}, Base.ValueIterator{<:SwissDict}}, state) in DataStructures at ~/.julia/packages/DataStructures/59MD0/src/swiss_dict.jl:646 invalidated:
...

julia> ascend(root)
Choose a call for analysis (q to quit):
     iterate(::Base.KeySet{String, _A} where _A<:(Dict{String}), ::Int64)
       iterate(::T) where T<:(Base.KeySet{String, _A} where _A<:(Dict{String}))
         copyto!(::Vector{String}, ::Base.KeySet{String, _A} where _A<:(AbstractDict{String}))
           _collect(::UnitRange{Int64}, ::Base.KeySet{String, _A} where _A<:(AbstractDict{String}), ::Base.HasElt
             collect(::Base.KeySet{String, _A} where _A<:(AbstractDict{String}))
 >             #_print#10(::Int64, ::Bool, ::Bool, ::Function, ::typeof(TOML.Internals.Printer._print), ::Nothing
...
```

The relevant part is 
https://github.com/JuliaLang/julia/blob/d498d36ef881c1989b9041bd3911a16a854e64fc/stdlib/TOML/src/print.jl#L101-L104

In the first line, `akeys` is inferred as `Base.KeySet{String, _A} where _A<:(AbstractDict{String})`. If inference gave `Dict{String}` here, the invalidations would be gone. I also don't see a nice way to fix these invalidations since `_print` accepts `a::AbstractDict` and some comments suggest that `AbstractDict` is really required, not just `Dict`
https://github.com/JuliaLang/julia/blob/d498d36ef881c1989b9041bd3911a16a854e64fc/stdlib/TOML/src/print.jl#L146

**Comment by KristofferC** [comment]
>  I also don't see a nice way to fix these invalidations 

Hiding the `keys` call from inference could work around it I guess?

**Comment by ranocha** [comment]
Could you please give a hint how to do this?

**Comment by KristofferC** [comment]
`invokelatest` (as is done in other places in this file)

**Comment by ranocha** [comment]
Just to confirm I understand correctly: You propose to use

```julia
akeys = @invokelatest keys(a)
```

instead, correct? Then, `akeys` would be inferred as `Any` and we would get a lot more dynamic dispatch here, which could reduce runtime performance (not critical here) and lead to more invalidations (would need to be checked). That sounds like a reasonable workaround for now if we don't get new invalidations from it.

**Comment by Keno** [comment]
`invokelatest` is pretty expensive. Use `inferencebarrier` to hide things from inference.

**Comment by Keno** [comment]
Regardless, the original request is also reasonable. We should be able to squeeze a bit more precision out of `apply_type_tfunc`.

**Comment by Keno** [comment]
I think the commented out code here would do it actually: https://github.com/JuliaLang/julia/blob/f927d25f21fd336b1b459369d7f59f1c7cb8d4d6/base/compiler/tfuncs.jl#L1530

That code has been commented out for many years, so probably worth revisiting the benchmark (probably needs to be updated though)

**Comment by ranocha** [comment]
It looks like this part hasn't been touched in >5 years, so yes, I think it would be great to revisit it :+1:

**Comment by ranocha** [comment]
It looks like the parts have been added in https://github.com/JuliaLang/julia/pull/20115 - but I cannot really find good benchmarks there.

**Comment by aviatesk** [comment]
Now we have a proper benchmark for Julia level compilation, so we can just comment in that code and see what "@-nanosoldier `runbenchmarks("inference", vs=":master")`" says.

**Comment by aviatesk** [comment]
@ranocha do you want to open a PR?

**Comment by aviatesk** [comment]
`apply_type_tfunc` got improved on master (#48329 ), but @staticfloat bisected that it was a source of the package loading time regression reported at #48811.

**Comment by vtjnash** [comment]
looks close to optimal now
```
julia> code_warntype(keys, (Dict{String},))
MethodInstance for keys(::Dict{String})
  from keys(a::AbstractDict) @ Base abstractdict.jl:105
Arguments
  #self#::Core.Const(keys)
  a::Dict{String}
Body::Base.KeySet{String, T} where T<:(Dict{String})
1 ─ %1 = Base.KeySet(a)::Base.KeySet{String, T} where T<:(Dict{String})
└──      return %1
```
