### ISSUE TITLE
LLVM 14 error? `error: no matching function for call to 'llvm::AttrBuilder::AttrBuilder()`

### ISSUE THREAD

**Issue by xgqt** [JuliaLang/julia#47113]
Julia fails to compile for me with LLVM 14.0.6 on Gentoo Linux.

```
/home/xy/Downloads/Julia/julia-1.8.2/src/cgutils.cpp:343:17: error: no matching function for call to 'llvm::AttrBuilder::AttrBuilder()'
  343 |     AttrBuilder B;
      |                 ^
In file included from /usr/lib/llvm/14/include/llvm/IR/Argument.h:18,
                 from /usr/lib/llvm/14/include/llvm/IR/Function.h:25,
                 from /usr/lib/llvm/14/include/llvm/IR/IntrinsicInst.h:30,
                 from /home/xy/Downloads/Julia/julia-1.8.2/src/codegen.cpp:46:
```

My build config:
```make
LOCALBASE:="/usr"
override prefix:="/usr"
override libdir:="$(prefix)/lib64"
override CC:=x86_64-pc-linux-gnu-gcc
override CXX:=x86_64-pc-linux-gnu-g++
override AR:=x86_64-pc-linux-gnu-ar

BUNDLE_DEBUG_LIBS:=0
USE_BINARYBUILDER:=0
USE_SYSTEM_CSL:=1
USE_SYSTEM_LLVM:=1
USE_SYSTEM_LIBUNWIND:=1
USE_SYSTEM_PCRE:=1
USE_SYSTEM_LIBM:=0
USE_SYSTEM_OPENLIBM:=1
USE_SYSTEM_DSFMT:=1
USE_SYSTEM_BLAS:=1
USE_SYSTEM_LAPACK:=1
USE_SYSTEM_LIBBLASTRAMPOLINE:=0
USE_SYSTEM_GMP:=1
USE_SYSTEM_MPFR:=1
USE_SYSTEM_LIBSUITESPARSE:=1
USE_SYSTEM_LIBUV:=0
USE_SYSTEM_UTF8PROC:=1
USE_SYSTEM_MBEDTLS:=1
USE_SYSTEM_LIBSSH2:=1
USE_SYSTEM_NGHTTP2:=1
USE_SYSTEM_CURL:=1
USE_SYSTEM_LIBGIT2:=1
USE_SYSTEM_PATCHELF:=1
USE_SYSTEM_ZLIB:=1
USE_SYSTEM_P7ZIP:=1
VERBOSE:=1
```

Build log:

[build.log](https://github.com/JuliaLang/julia/files/9740114/build.log)

**Comment by vchuravy** [comment]
It looks like you are trying to build Julia 1.8.2? Julia 1.8.x does not support LLVM 14. It only supports LLVM 13.

We also strongly recommend that you use the Julia specific patch set and do not build Julia against a system LLVM.
https://github.com/JuliaLang/llvm-project/compare/llvmorg-13.0.1...julia-13.0.1-3

**Comment by xgqt** [comment]
> It looks like you are trying to build Julia 1.8.2? Julia 1.8.x does not support LLVM 14. It only supports LLVM 13.
> 
> We also strongly recommend that you use the Julia specific patch set and do not build Julia against a system LLVM. [JuliaLang/llvm-project@llvmorg-13.0.1...julia-13.0.1-3](https://github.com/JuliaLang/llvm-project/compare/llvmorg-13.0.1...julia-13.0.1-3)

Thanks a lot of quick response!
