### ISSUE TITLE
Simd regression with AoS dest on master.

### ISSUE THREAD

**Issue by N5N3** [JuliaLang/julia#47138]
Suddenly find that `a .= complex.(b, c)` could not be vectorlized on master.
I thought it might be caused by different LLVM version but bisect points to 7f2bb7df8e3bf06f81d6984c1663a61705f3b579(#45606) cc @vtjnash.
(So looks like LLVM dislikes `memcpy` for field stores in some cases?)

MWE:
```julia
julia> a = randn(ComplexF32, 1000); b = real(a); c = imag(a);        

julia> @btime $a .= complex.($b, $c)
  825.641 ns (0 allocations: 0 bytes) # 180ns before #45606
```

**Comment by gbaraldi** [comment]
After some debugging the issue seems to be that the tbaa tag on the generated memcpy is too general which then makes future optimizations not legal.
Not sure if there is much we can do right now

**Comment by topolarity** [comment]
Looked into this one briefly this morning.

Unfortunately `llvm.memcpy` only supports a single TBAA node for dst/src, and LLVM's TBAA hierarchy cannot represent unions of types (see https://lists.llvm.org/pipermail/llvm-dev/2017-March/110653.html). The end result is that it's impossible to provide good TBAA metadata to memcpy when src/dst are disparate types.

Assuming we don't want to open the can of worms of trying to enhance the memcpy TBAA metadata upstream, the only solutions that occur to me here are either (a) to partially roll back https://github.com/JuliaLang/julia/commit/7f2bb7df8e3bf06f81d6984c1663a61705f3b579 and split some of these memcpys to loads/stores or (b) to try to add custom passes/metadata to better inform LLVM's alias analyses

**Comment by gbaraldi** [comment]
Yeah, you came to the same conclusion I did, we either do a decent refactor to our TBBA/alias analysis metadata, or special case the memcpy emission to things over the size of a SIMD array, not sure if we can check at runtime, but defaulting to 64 bytes might be a good choice.

**Comment by topolarity** [comment]
After reviewing this one with @gbaraldi and @vtjnash, we'd like to explore fixing this by re-encoding the existing TBAA lattice into the set-based `noalias` and `alias.scope` metadata (kudos to @vtjnash for the proposal)

The `noalias`/`alias.scope` domains are able to represent precisely the merge of `dst`/`src`, so we should be able to conclude non-aliasing here and make LICM/vectorization work again.

It might also be worth working with LLVM to allow AA-related metadata for `llvm.memcpy` to be split between dst and src, which would still bring precision benefits for both TBAA and AliasScoped analyses. That initiative can be taken up in parallel, though.

**Comment by N5N3** [comment]
If we can't finish that change before 1.9. Should we partially roll back https://github.com/JuliaLang/julia/commit/7f2bb7df8e3bf06f81d6984c1663a61705f3b579 for 1.9 to avoid possible regression?

**Comment by topolarity** [comment]
Unfortunately the motivating use case for https://github.com/JuliaLang/julia/commit/7f2bb7df8e3bf06f81d6984c1663a61705f3b579 overlaps almost exactly with this regression (it's a memcpy with bad TBAA operating on a small, 2-4 element homogeneous array of int/float), so even a partial roll back would also undo the improvements for the examples given in that PR
