### ISSUE TITLE
`CmdRedirect` constructor throwing `TypeError`

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#47180]
[`BinaryBuilderBase.jl`](https://github.com/JuliaPackaging/BinaryBuilderBase.jl) tests are failing on https://github.com/JuliaLang/julia/commit/532125d51d23f22c3fd117fe8a37c158fe16ac62.  A smaller reproducer cooked up with the help of https://github.com/maleadt/creduce_julia is:
```julia
function a(b; stdout )
    c = setenv(b, b.env)
    if true
        c = pipeline(c, stdout)
    end
    c
end
a(``; stdout)
```
The output is
```
ERROR: LoadError: TypeError: in new, expected Base.AbstractCmd, got a value of type Nothing
Stacktrace:
 [1] CmdRedirect
   @ ./cmd.jl:186 [inlined]
 [2] CmdRedirect
   @ ./cmd.jl:191 [inlined]
 [3] redir_out
   @ ./cmd.jl:355 [inlined]
 [4] #pipeline#761
   @ ./cmd.jl:389 [inlined]
 [5] pipeline
   @ ./cmd.jl:397 [inlined]
 [6] #a#3
   @ /tmp/foo.jl:4 [inlined]
 [7] top-level scope
   @ /tmp/foo.jl:8
in expression starting at /tmp/foo.jl:8
```
I don't see how you can enter https://github.com/JuliaLang/julia/blob/d89b96b3fc7ac13ed29ac1508ba302dc4f758d33/base/cmd.jl#L355 where `src::AbstractCmd` and then the `CmdRedirect` constructor complains `src` isn't `AbstractCmd`.

Last time tests passed was on https://github.com/JuliaLang/julia/commit/7f507e64aa14dbbd7e0c9b51a0ee72e7ea97bb19.

**Comment by giordano** [comment]
`git bisect` blames https://github.com/JuliaLang/julia/commit/06203616d5285ae4b5af6fc29c8585341bb833b7 (from #47080).  CC: @Keno

**Comment by Keno** [comment]
That commit itself is probably not bad, but if there's another unrelated bug that commit would have stopped hiding it. I'll turn on the oracle check and take a look.
