### ISSUE TITLE
`TypeError: in <:, expected Type, got a value of type Core.PartialStruct` when testing Bonsai

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#47267]
PkgEval log https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c6440b9_vs_d0156b5/Bonsai.primary.log

```
Bonsai.write: Error During Test at /home/kc/.julia/packages/Bonsai/ogViD/test/io.jl:111
  Test threw exception
  Expression: all(map((x->begin
                x[2] == 201
            end), Bonsai.handler_writes(g)))
  TypeError: in <:, expected Type, got a value of type Core.PartialStruct
  Stacktrace:
   [1] handler_writes(handler::Any)
     @ Bonsai ~/.julia/packages/Bonsai/ogViD/src/io.jl:295
   [2] macro expansion
     @ ~/julia/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:477 [inlined]
   [3] macro expansion
     @ ~/.julia/packages/Bonsai/ogViD/test/io.jl:111 [inlined]
   [4] macro expansion
     @ ~/julia/usr/share/julia/stdlib/v1.10/Test/src/Test.jl:1496 [inlined]
   [5] top-level scope
     @ ~/.julia/packages/Bonsai/ogViD/test/io.jl:74
```

Seems to occur at https://github.com/onetonfoot/Bonsai.jl/blob/ba9bf9f3207f1e98c0b573d06b910e04567e0cfa/src/io.jl#L295. Seems weird that such an internal type would "leak out".

**Comment by gbaraldi** [comment]
Bonsai internals touch a lot of JET code and compiler code so it's not super odd that internals leak out. I wonder if one of the refactors broke it.

**Comment by KristofferC** [comment]
> Bonsai internals touch a lot of JET code and compiler code

Ah, feel free to close if they should handle it themselves.

**Comment by gbaraldi** [comment]
This is probably makes more sense in Bonsai.jl. I opened https://github.com/onetonfoot/Bonsai.jl/issues/26
