### ISSUE TITLE
Comparison of self refferential arrays using == does not work

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#47290]
Examples:
```
julia> v = Any[1, 2]
2-element Vector{Any}:
 1
 2

julia> v[1] = v
2-element Vector{Any}:
  2-element Vector{Any}:#= circular reference @-1 =#
 2

julia> v == v
ERROR: StackOverflowError:
```
and
```
julia> m = Any[1 2]
1×2 Matrix{Any}:
 1  2

julia> m[1] = m;

julia> m == m
ERROR: StackOverflowError:
```
(maybe the decision is that nothing can be done about it with a reasonably good performance then the issue should be closed)

**Comment by gbaraldi** [comment]
Maybe a dupe of https://github.com/JuliaLang/julia/issues/46725?

**Comment by bkamins** [comment]
Ah - yes. I remembered I reported similar, but I thought it was different, but now I see that in the discussion we have the same cases mentioned also.
