### ISSUE TITLE
Add LAPACK functions for Nonsymmetric Eigenvalues Problems

### ISSUE THREAD

**Issue by albertomercurio** [JuliaLang/julia#47291]
Hello,

I think it could be great to add some of the LAPACK functions for [Nonsymmetric Eigenvalues Problems](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem/lapack-least-square-eigenvalue-problem-computation/nonsymm-eigenvalue-problems-lapack-computation.html). 

Most of them [are yet implemented](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.LAPACK.gehrd!), but I noticed that for example `hseqr` (which finds the eigenvalues and Schur factorization of an Hesenber matrix) is not yet present.

**Comment by albertomercurio** [comment]
I think it is not so difficult to implement. The KrylovKit package did it on his own.

https://github.com/Jutho/KrylovKit.jl/blob/dee29fe34c724e4c9532ea22dfb6e0464263b8c1/src/dense/linalg.jl#L499

**Comment by ViralBShah** [comment]
If you could, please submit a PR. Happy to accept.
