### ISSUE TITLE
Unnecessary add operations performed when multiplying in-place by diagonal matrix

### ISSUE THREAD

**Issue by tristanmontoya** [JuliaLang/julia#47312]
Left-multiplication of a vector of length _N_ by an _N_-by-_N_ diagonal matrix should require a total of _N_ multiplications. However, there are certain cases when (at least according to [GFlops.jl](https://github.com/triscale-innov/GFlops.jl)) Julia appears to perform an additional _N_ additions, effectively doubling the cost of such an operation. For example, the following code, which uses an out-of-place matrix-vector multiplication,

```julia
using LinearAlgebra, GFlops
A = Diagonal(rand(10))
x = rand(10)
@count_ops y = A * x
```
produces the following output:
```
Flop Counter: 10 flop
┌─────┬─────────┐
│     │ Float64 │
├─────┼─────────┤
│ mul │      10 │
└─────┴─────────┘
```
However, the equivalent in-place operation,

```julia
y = similar(x)
@count_ops mul!(y, A, x)
```
returns the following:
```
Flop Counter: 20 flop
┌─────┬─────────┐
│     │ Float64 │
├─────┼─────────┤
│ add │      10 │
│ mul │      10 │
└─────┴─────────┘
```

It seems like these additions are not necessary; the same operation could be done without any addition as follows:
```julia
function LinearAlgebra.mul!(y::AbstractVector, 
    A::Diagonal, x::AbstractVector)
    y[:] = A.diag .* x
    return y
end
```

Is this an oversight or is there a reason for such behaviour?

**Comment by mcabbott** [comment]
What version is this on? GFlops.jl appears not to work on 1.9.

This might have been fixed by https://github.com/JuliaLang/julia/pull/44651, as the present code seems to check β and not add if it is zero:
https://github.com/JuliaLang/julia/blob/25e3809ea4c309f7d0d9d5db85c5107aa63877b5/stdlib/LinearAlgebra/src/diagonal.jl#L274

**Comment by tristanmontoya** [comment]
@mcabbott - you are right, this was fixed by that PR. My tests were on 1.7 but it's all fine on 1.8. Thanks!
