### ISSUE TITLE
@kwdef should infer types from default values

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#47333]
I incorrectly assumed that `@kwdef` would infer the field types based on their default values and ended up with very slow code that allocated every time I accessed the struct's fields.

It seems to me that it would make for much cleaner code (and cause less newcomers to run into performance problems) if the following resulted in a type-stable struct:
```
@kwdef struct Foo
    x = 1.0
    y = "bar"
end
```

**Comment by KristofferC** [comment]
```
@kwdef struct Foo
    x = foo()
end
```

what type should `x` have?

**Comment by robsmith11** [comment]
> ```
> @kwdef struct Foo
>     x = foo()
> end
> ```
> 
> what type should `x` have?

I guess not ideal, but maybe something like
`Base.return_types(foo) |> x -> ifelse(length(x) == 1, x[1], Any)`

**Comment by KristofferC** [comment]
`foo` might not even be defined at that point and using inference to determine the type of fields seems like a bad idea since inference can become better/worse between releases.

**Comment by robsmith11** [comment]
Perhaps automatic type parameters would be a better solution, as suggested here:
https://github.com/JuliaLang/julia/issues/31231

**Comment by robsmith11** [comment]
As discussed there, it sounds like a macro is a better idea than changing the base behavior.
