### ISSUE TITLE
LinearAlgebra/lapack error on CI in sygvd

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#47376]
```
LinearAlgebra/lapack                             (2) |         failed at 2022-10-28T14:23:53.339
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-2.0/build/default-macmini-aarch64-2-0/julialang/julia-master/julia-aee41e1c57/share/julia/stdlib/v1.9/LinearAlgebra/test/lapack.jl:30
  Expression: LAPACK.sygvd!(1, 'V', 'U', copy(Asym), Matrix{elty}(undef, 6, 6))
    Expected: DimensionMismatch
      Thrown: ArgumentError
LinearAlgebra/svd                                (3) |    26.26 |   1.40 |  5.3 |    3490.46 |  1671.30
```
https://buildkite.com/julialang/julia-master/builds/17588#01841fc9-4176-4a2c-875f-a3fba6343de2

**Comment by Keno** [comment]
I thought we already had an issue about this somewhere since msan was complaining about this too. But basically, this test is trying to do an SVD of uninitialized memory - to check an error path sure, but it's not guaranteed to always hit that error path.

**Comment by vtjnash** [comment]
Maybe it was in the msan tracking issue? I couldn't find one, so I made this. Seems a straightforward fix then, to make that some random, zeros, or other pattern array instead
