### ISSUE TITLE
Should x/pi, x/2pi, and x/4pi use multiply?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#47380]
In some cases / is special-cased, e.g 1/2, 1/4 avoids division, or if `@fastmath` is used (which people might be ignorant of). Since pi is irrational it feels like it could be special-cased, I'm not sure if accuracy needs to suffer, and it might be important enough for physics.

**Comment by antoine-levitt** [comment]
Try code native on f() = 2/pi: constant propagation already moves the computation to compile time, so for literals it doesn't matter much whether multiplication or division is used

**Comment by PallHaraldsson** [comment]
Sorry, I actually had more real-word code in mind i.e. x/pi, x could be 1... but literal denominator, could apply more generally to e.g. h/4pi for [Heisenberg's uncertainty principle](https://en.wikipedia.org/wiki/Uncertainty_principle) or others here:

https://en.wikipedia.org/wiki/List_of_formulae_involving_%CF%80

and in principle:

[Kepler's third law of planetary motion](https://en.wikipedia.org/wiki/Kepler%27s_laws_of_planetary_motion#Third_law_of_Kepler):

GM/4pi²

**Comment by giordano** [comment]
I don't think we want to make a whole new algebra on `Irrational` numbers: this has been rejected several times already, shifting computation from runtime to compile time has its own cost, it doesn't make everything go away. Antoine also showed that when the compiler can quickly do the computation for you it's already happy to do so, making this proposal unnecessary.

**Comment by KristofferC** [comment]
What @giordano said, there are many good CAS for Julia in packages though.

**Comment by PallHaraldsson** [comment]
>I don't think we want to make a whole new algebra on Irrational numbers: this has been rejected several times already, shifting computation from runtime to compile time has its own cost, it doesn't make everything go away.

@oscardssmith I'm curious if using multiply for e.g. x/pi can be as accurate, otherwise just close as this can't be the default. But I'm only thinking what can be easy to do, not slow at compile time, similar to literal powers. That might mean x/pi possible but not x/2pi, since 2pi no longer irrational.
