### ISSUE TITLE
.+ not defined in metaprogramming

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#47408]
I am working on debugging [this issue](https://github.com/JuliaData/DataFramesMeta.jl/issues/328) in DataFramesMeta.jl. I believe there is inconsistency with parsing. 

1. At the macro-call site, there is inconsistent parsing were `.+` can become either a `Expr(:., :+)` *or* becomes `Symbol(".+")`. 
2. When a `Symbol(".+")` is passed to the expression evaluated, sometimes it works and sometimes I get a `ERROR: UndefVarError: .+ not defined`

Here is an MWE that captures the error

```
julia> function exec(p::Pair)
           fun = p[2]
           val = p[1]
           fun(val)
       end;

julia> macro make_exec(x)
           @show b = x.args[1]
           @show a = x.args[2]
           t = quote
               $(exec)($a => $b)
           end
           dump(t)
           esc(t)
       end;

julia> x = [1];

julia> @make_exec .+(x)
b = x.args[1] = :.+
a = x.args[2] = :x
Expr
  head: Symbol block
  args: Array{Any}((2,))
    1: LineNumberNode
      line: Int64 5
      file: Symbol REPL[75]
    2: Expr
      head: Symbol call
      args: Array{Any}((2,))
        1: exec (function of type typeof(exec))
        2: Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Symbol =>
            2: Symbol x
            3: Symbol .+
ERROR: UndefVarError: .+ not defined
Stacktrace:
 [1] top-level scope
   @ REPL[75]:5
```

Proof sometimes `.+` becomes `Expr(:., :+)` (this made debugging hard sometimes)

```
julia> macro donothing(t)
           dump(t)
           esc(t)
       end
@donothing (macro with 1 method)

julia> @donothing x => .+
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol =>
    2: Symbol x
    3: Expr
      head: Symbol .
      args: Array{Any}((1,))
        1: Symbol +
[1] => Base.Broadcast.BroadcastFunction(+)
```

Proof that sometimes `.+` as a `Symbol` works fine sometimes

```
julia> @donothing .+(x)
Expr
  head: Symbol call
  args: Array{Any}((2,))
    1: Symbol .+
    2: Symbol x
1-element Vector{Int64}:
 1
```

The important difference seems to be the `Pair` syntax in the 2nd example. Because the `make_exec` macro makes an expression with a `Pair`, Julia assumes that the RHS of the `Pair` looks as it would if parsed directly by the parser. Example 2 confirms it creates the `Expr` form. 

When it doesn't encounter that... it errors in some way. 

My current fix is to take all `Symbol(".+")` and de-structure them into the `Expr` form. Does that make sense?

Thank you

**Comment by PallHaraldsson** [comment]
>I believe there is inconsistency with parsing.

Is it ok with JuliaSyntax.jl? I would at least look into that too (since it will be the default later, hopefully landing soon in 1.9, though likely off by default then).

**Comment by KristofferC** [comment]
> Is it ok with JuliaSyntax.jl? 

JuliaSyntax.jl will produce the same AST as to not be breaking.

**Comment by pdeffebach** [comment]
@simeonschaub thanks. 

So this is an inconsistency (maybe bug), that can't be changed because people rely on the parsing? 

Do you know what I should do in DataFramesMeta.jl? I'm thinking I should change all `Symbol(".+")` to the expression version. Or maybe `Base.BroadcastFunction`. Does that sound right?

**Comment by c42f** [comment]
> JuliaSyntax.jl will produce the same AST as to not be breaking

That's right, JuliaSyntax will produce `Expr` which is compatible with the reference parser (minor exceptions to fix bugs in the in the reference parser, but even then on a case-by-case basis considering compatibility)

However, JuliaSyntax does produce a "green tree", which differs in various ways from `Expr`. Some such differences are being worked on in https://github.com/JuliaLang/JuliaSyntax.jl/issues/88.

The green tree is lowered to a compatible `Expr` before handing to the Julia runtime.

The inconsistencies of dot-call syntax have been on my mind for a while and I'm reworking this at some point soon in https://github.com/JuliaLang/JuliaSyntax.jl/issues/90.  Current plan is to parse things like `a .+ b` into a tree like `(dotcall-i a + b)` and likewise parse `f.(a,b)` as `(dotcall f a b)`.

Naturally this won't help you in the medium term! Any change to Expr is extremely breaking and we can't really do that. But I feel there's a possibility of having opt-in "new style macros" at some point in the future (still Julia 1.x) and tackling several of the problems we have with the current system.
