### ISSUE TITLE
strptime() on Windows 'ERROR: ccall: could not find function strptime'

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#4740]
Attempts to use strptime() from a 64-bit Windows 7 box are yield a ccall error.  Googling indicates strptime() may not be part of libc on Windows.  In Python, the developers have created a native version (in Lib\\_strptime.py). Perhaps something similar is needed by Julia?

Version and session details:

  Version 0.2.0-rc2
  Commit (no branch)/b372a68 2013-10-26 02:06:56 UTC
  x86_64-w64-mingw32

```
julia> strptime("%Y/%m/%d","2013/11/4")
symbol could not be found strptime (-1): The specified procedure could not be fo
und.

ERROR: ccall: could not find function strptime
 in strptime at libc.jl:51
WARNING: backtraces on your platform are often misleading or partially incorrect
```

**Comment by ihnorton** [comment]
Can this be closed (#7654)?

**Comment by JeffBezanson** [comment]
We'd have to either remove `strptime`, or add a replacement based on Dates.

**Comment by quinnj** [comment]
I think it's generally useful to have the standard, core C functions available. I know it was mentioned we could get rid of a bunch of C time-related functions with `Dates`, but I think there are enough C folks and compatibility cases where it's useful to have those, even if somewhat hidden or non-advertised.

The BSD-licensed version seems like it would be a quick inclusion?

**Comment by vtjnash** [comment]
alternatively, we can use C++ `std::get_time` (http://stackoverflow.com/a/33542189)
