### ISSUE TITLE
`map` with an invalid function body returns `Union{}[]`

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#47415]
In 1.8.2:

```
using NearestNeighbors
map([]) do f
	knn(BallTree(), [])
end # Union{}[]
```

This inner method call is invalid and will never work for non-empty input, but for consistency, shouldn't the return type for the empty case either be `Nothing[]` or `Any[]`?

```
map([]) do f
end # Nothing[]

map([]) do f
    knn(BallTree([1.0; 2.0]), [1.0; 2.0], 1)
end # Any[]
```

**Comment by mcabbott** [comment]
This is the smallest type, while Any is the largest. I think that ensures it can be composed with anything, like so:
```julia
julia> map(_ -> error(), [])
Union{}[]

julia> collect(Iterators.flatten(()))
Union{}[]

julia> vcat(ans, [true])  # 1st arg never widens the type
1-element Vector{Bool}:
 1

julia> vcat(Nothing[], [true])
1-element Vector{Union{Nothing, Bool}}:
 true
```

**Comment by vtjnash** [comment]
Closing as not planned, since I think this is per-design. But feel free to make an argument why it is not right however!

**Comment by BioTurboNick** [comment]
Thanks! I don't know if I have one, other than it being unusual.

For context, the reason I noticed was that in Pluto (via Colors), when it tried to show the object, it encountered a type ambiguity which to me seemed nonintuitive:

```
ERROR: MethodError: show(::Base.TTY, ::MIME{Symbol("image/svg+xml")}, ::Vector{Union{}}) is ambiguous. Candidates:
  show(io::IO, mime::MIME{Symbol("image/svg+xml")}, cs::AbstractVector{T}; max_swatches) where T<:TransparentColor in Colors at /Users/fons/.julia/packages/Colors/yDxFN/src/display.jl:41
  show(io::IO, mime::MIME{Symbol("image/svg+xml")}, cs::AbstractVector{T}; max_swatches) where T<:Color in Colors at /Users/fons/.julia/packages/Colors/yDxFN/src/display.jl:35
Possible fix, define
  show(::IO, ::MIME{Symbol("image/svg+xml")}, ::AbstractVector{Union{}})
```

https://github.com/JuliaGraphics/Colors.jl/issues/526

Should methods need to guard against `Union{}` inputs causing ambiguity?
