### ISSUE TITLE
Full source build failing

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#47414]
Recent master is failing the full source build: https://buildkite.com/julialang/julia-master-scheduled/builds/141#01842c63-d05a-41c9-aea4-237e2d402f83

History of full source builds: https://buildkite.com/julialang/julia-master-scheduled 

cc @DilumAluthge

**Comment by vtjnash** [comment]
PR https://github.com/JuliaLang/julia/pull/47400
