### ISSUE TITLE
Inferred effects when comparing symbols

### ISSUE THREAD

**Issue by Tokazama** [JuliaLang/julia#47424]
I discovered that comparison operations on symbols (with the exception of `==`) end up removing all inferred effects. I narrowed the problem down to `ccall(:strcmp, Int32, (Cstring, Cstring), x, y)` found [here](https://github.com/JuliaLang/julia/blob/abf2afbcc4f6689809363410aa11bddcfabed540/base/strings/basic.jl#L348). I'm assuming this is because it is converted to a `String` but would it be appropriate to specify any effects since it's an interned string?

**Comment by Keno** [comment]
It should be legal to annotate that strcmp `:total`.
