### ISSUE TITLE
`relpath` confusing error message

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#47443]
```julia
julia> relpath("")
ERROR: ArgumentError: `path` must be specified
Stacktrace:
 [1] relpath(path::String, startpath::String) (repeats 2 times)
   @ Base.Filesystem ./path.jl:541
 [2] top-level scope
   @ REPL[1]:1
```
this is confusing because the path is being passed, it is just empty. E.g. this can happen with
```julia
ulia> relpath(dirname("README.md"))
ERROR: ArgumentError: `path` must be specified
Stacktrace:
 [1] relpath(path::String, startpath::String) (repeats 2 times)
   @ Base.Filesystem ./path.jl:541
 [2] top-level scope
   @ REPL[5]:1
```
I think the error should be "`path` must be non-empty" instead.

Code:
https://github.com/JuliaLang/julia/blob/d0ba259f63c379f6e00755dc4f217a1b12991540/base/path.jl#L555

**Comment by the-lazy-learner** [comment]
I'm trying to learn Julia. Is it possible that I could work on this issue?
I'm not really sue if what I feel seems an ok way to do it, is actually the way to do it.
I was just thinking of modifying the argument to ArgumentError.  Would try to understand and proceed, am I thinking in the right direction @KristofferC ?

**Comment by the-lazy-learner** [comment]
Making a new PR in a few minutes because of CI issues
