### ISSUE TITLE
Bug(?) when initializing a `Matrix(undef, ::Tuple)`

### ISSUE THREAD

**Issue by KwatMDPhD** [JuliaLang/julia#47442]
<img width="1412" alt="Screen Shot 2022-11-03 at 13 24 00" src="https://user-images.githubusercontent.com/7741548/199815615-b73df7ca-b2ac-449b-982d-4cd203df4a8e.png">

Why can't I use a `Tuple` to specify the dimensions of a `Matrix` when `eltype` is not specified? This must be a bug?

macOS
Julia 1.8.2

**Comment by KwatMDPhD** [comment]
When I explicitly type `{Any}`, the error disasters. Strange.

<img width="321" alt="Screen Shot 2022-11-03 at 13 29 55" src="https://user-images.githubusercontent.com/7741548/199816644-a3b77130-73dd-442b-8453-6694dc2cddf1.png">

**Comment by JeffBezanson** [comment]
Yes I think these methods could be added.
