### ISSUE TITLE
error running fibonacci recursion function; from "Think Julia" book

### ISSUE THREAD

**Issue by doolingdavidrs21** [JuliaLang/julia#47455]
i am running Julia 1.8.2 and following along with the examples in the book _Think Julia_

This code for calculating numbers in the fibonacci squence works for small n, but gives nonsensical results for larger n. Sometimes the results are just incorrect when compared with tables, and sometimes they are even negative!

Ah! all is good if you wrap thiings in BigInt:

```
known = Dict(0 => BigInt(0), 1 => BigInt(1))

function fibonacci(n)
    if n ∈ keys(known)
        return known[n]
    end
    res = BigInt(fibonacci(n-1)) + BigInt(fibonacci(n-2))
    known[n] = res
    res
end
```

fibonacci(99)
-2437933049959450366

I don't understand what is going on, but I think it has poked at something seriously amiss.
David Dooling

**Comment by DilumAluthge** [comment]
This is intentional behavior: https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Overflow-behavior

Please ask further questions on Discourse: discourse.julialang.org
