### ISSUE TITLE
Information about the behavior of lowercase

### ISSUE THREAD

**Issue by rossati** [JuliaLang/julia#47478]
hello
debugging a my programs I ran into lowercasing a string with mixed latin and greek character, below the case:
```
julia> Greek = "Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"
"Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"

julia> lowercase(Greek)
"α:alfa|β:beta|δ:delta|γ:gamma"

julia>
```
It is correct? why only A and B followed by a colon they have been modified?
Thanks
Giovanni Rossati

**Comment by barucden** [comment]
All the capitalized characters were modified, right? `Α` => `α`, `A` => `a`, ...

Note that (the first) `Α` is capital *alpha*, while (the second) `A` is capital *a*:
```
julia> Greek = "Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"
"Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"

julia> for i in eachindex(Greek)
           @info i Greek[i]
       end
┌ Info: 1
└   Greek[i] = 'Α': Unicode U+0391 (category Lu: Letter, uppercase)
┌ Info: 3
└   Greek[i] = ':': ASCII/Unicode U+003A (category Po: Punctuation, other)
┌ Info: 4
└   Greek[i] = 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
[...]
```

Similarly for `Β` (*beta*) and `B` (*b*). 

Was that the source of confusion, or am I missing something?

**Comment by rossati** [comment]
Hello
here are some examples.
**Correct**
```
julia> lowercase("A:Alfa|Γ:Gamma|Δ:Delta|B:Beta")
"a:alfa|γ:gamma|δ:delta|b:beta"
julia> lowercase("A:Alfa|Γ:Gamma|Δ:Delta")
"a:alfa|γ:gamma|δ:delta"
```
**Uncorrect**
```
julia> lowercase("Γ:Gamma|Α:Alfa|Β:Beta")
"γ:gamma|α:alfa|β:beta"
```

**Comment by vtjnash** [comment]
As @barucden  said, there still does not appear to be anything incorrect about those examples

**Comment by rfourquet** [comment]
Please state specifiacly what you think is incorrect, if possible restricting your example to a one-character string.

**Comment by rossati** [comment]
Hi
I expect that the lower case of 
**Γ**:Gamma|**Α**:Alfa|**Β**:Beta 

must be **γ**:gamma|**a**:alfa|**b**:beta and not 

γ:gamma|**_α_**:alfa|**_β_**:beta

**Comment by barucden** [comment]
Check my first response again. The letter that looks like capital *a* is in fact capital *alpha*, and the one that looks like capital *b* is in fact capital *beta*.
```
julia> Alpha = 'Α'
'Α': Unicode U+0391 (category Lu: Letter, uppercase)

julia> Beta = 'Β'
'Β': Unicode U+0392 (category Lu: Letter, uppercase)

julia> A = 'A'
'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

julia> B = 'B'
'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)

julia> Alpha == A
false

julia> Beta == B
false

julia> lowercase(Alpha)
'α': Unicode U+03B1 (category Ll: Letter, lowercase)

julia> lowercase(A)
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> lowercase(Beta)
'β': Unicode U+03B2 (category Ll: Letter, lowercase)

julia> lowercase(B)
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
```

**Comment by rossati** [comment]
Thanks barucden
I have tried your example and I had the same results.
But the question is why The firs A is a uppercase alfa?
in any case on the second attempt the string of characters was found to be correct.
```
julia> Greek = "A:Alfa|B:Beta|Γ:Gamma|Δ:Delta"
"A:Alfa|B:Beta|Γ:Gamma|Δ:Delta"

julia> for i in eachindex(Greek)
           @info i Greek[i]
       end
┌ Info: 1
└   Greek[i] = 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
┌ Info: 2
└   Greek[i] = ':': ASCII/Unicode U+003A (category Po: Punctuation, other)
┌ Info: 3
└   Greek[i] = 'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
┌ Info: 4
└   Greek[i] = 'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)
┌ Info: 5
└   Greek[i] = 'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)
┌ Info: 6
└   Greek[i] = 'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
┌ Info: 7
└   Greek[i] = '|': ASCII/Unicode U+007C (category Sm: Symbol, math)
┌ Info: 8
└   Greek[i] = 'B': ASCII/Unicode U+0042 (category Lu: Letter, uppercase)
...

```
Finally, the script below provides the two different results

```
Greek = "A:Alfa|B:Beta|Γ:Gamma|Δ:Delta"
for i in eachindex(Greek)
    @info i Greek[i]
end
println(lowercase(Greek))
Greek = "A:Alfa|B:Beta|Γ:Gamma|Δ:Delta"
for i in eachindex(Greek)
    @info i Greek[i]
end

```

**Comment by vtjnash** [comment]
It is an Alpha because you typed the Alpha character there, not the A character. You most recent examples all print the same output for me (not different results), since your input strings are `==` in that case
```
julia> "Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"[1]
'Α': Unicode U+0391 (category Lu: Letter, uppercase)
```

**Comment by rossati** [comment]
Hi vtJnash 
thanks
I havn't typed the Alpha character I only inverted Gamma/Delta
```
julia> "A:Alfa|B:Beta|Γ:Gamma|Δ:Delta"[1]
'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
julia> "Α:Alfa|Β:Beta|Δ:Delta|Γ:Gamma"[1]
'Α': Unicode U+0391 (category Lu: Letter, uppercase)
```
Best regards

**Comment by vtjnash** [comment]
Your output shows otherwise, since the first one printed the character info of latin A, and the second printed greek Alpha
