### ISSUE TITLE
`dims` kwarg to `mad`

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#47483]
`mean`, `median`, `std`, all have a keyword argument `dims`, but not `mad`.  is there a technical reason for this, or just a lack on manpower?

**Comment by DilumAluthge** [comment]
Where is `mad` defined?

**Comment by bjarthur** [comment]
StatsBase

**Comment by giordano** [comment]
> StatsBase

So what does it have to do with this repository?

**Comment by LilithHafner** [comment]
It seems that you have [already filed this issue](https://github.com/JuliaStats/StatsBase.jl/issues/724) at StatsBase.jl. If an issue you care about isn't getting much attention you can always make a pr for it, and in the Julia community, I believe it is fairly widely accepted to bump the issue if it is still bothering you.

It's typically not good form to cross-post in a different repository for increased visibility (unless it's an upstream issue that actually belongs in the other repo), especially without linking the original.

**Comment by bjarthur** [comment]
my bad.  i forgot stats wasn't a stdlib, and also forgot that i'd already issued about it.  brain fart.  sorry!

**Comment by LilithHafner** [comment]
No worries! Mistakes happen

**Comment by bjarthur** [comment]
@LilithHafner i enjoyed you julia con talk on sorting btw.  nice work!
