### ISSUE TITLE
GC callback defined in Julia hangs

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#47525]
In Julia 1.8 and earlier I can install a GC callback defined in Julia, e.g.
```julia
function gc_cb_pre(::Int32)
    nothing
end
ccall(:jl_gc_set_cb_pre_gc, Cvoid, (Ptr{Cvoid}, Cint),
    @cfunction(gc_cb_pre, Cvoid, (Cint,)),1)

# trigger callback
GC.gc()
```
This appeared to work as long as the callback didn't allocate memory.

On the current nightly this hangs.

I use this in NVTX.jl for instrumenting the Julia GC: https://github.com/simonbyrne/NVTX.jl/blob/0262cf89465b1bc3a60acfd24ed1fdb0b67e29c9/src/julia.jl#L60

**Comment by vtjnash** [comment]
GC callbacks are forbidden from re-entering Julia

**Comment by maleadt** [comment]
The invoked function here (`gc_cb_pre`) doesn't do anything but `ret void`; how come it still hangs?

**Comment by vchuravy** [comment]
Thread adoption requires `cfunction` to interact with the runtime and then Safepoint on entry. So we made it legal to call Julia functions from foreign threads, but that prohibits them being called from the GC (which was questionable to begin with)
