### ISSUE TITLE
Type jump, help cannot execute

### ISSUE THREAD

**Issue by deahhh** [JuliaLang/julia#47526]
julia 1.8.2
```
help?> .&&
search:

  x .&& y is akin to broadcast(&&, x, y). See broadcast.

julia> broadcast(&&, rand(Bool, 3), rand(Bool,3))
ERROR: syntax: invalid identifier name "&&"
Stacktrace:
 [1] top-level scope
   @ none:1

julia> typeof(rand(Bool,3))
Vector{Bool} (alias for Array{Bool, 1})

julia> rand(Bool,3) .&& rand(Bool, 3)
3-element BitVector:
 0
 0
 0

julia> 
```

1.  output of `Vector{Bool} .&& Vector{Bool}` is `BitVector`
2.  `broadcast(&&, x, y)` throw an error.
3.  Cannot find the function define for &&

**Comment by jakobnissen** [comment]
The function is called `Base.andand`. In general, if you have some Julia syntax you do not understand, try to use `Meta.@lower`:
```julia
julia> Meta.@lower rand(Bool,3) .&& rand(Bool, 3)
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = rand(Bool, 3)
│   %2 = rand(Bool, 3)
│   %3 = Base.broadcasted(Base.andand, %1, %2)
│   %4 = Base.materialize(%3)
└──      return %4
))))
```

@deahhh In the future, please seek help in the [Julia discourse forum](https://discourse.julialang.org/) or on the JuliaLang Slack space in the #helpdesk channel. This repo is for bug reports / development of the Julia codebase.

**Comment by deahhh** [comment]
@jakobnissen 
Thanks ! `Meta.@lower` is usefull.
Maybe the Inconsistency on type between input and output is just nothing.

**Comment by jakobnissen** [comment]
The help message is very unhelpful, since `broadcast(&&, x, y)` is not valid Julia code. This should be improved.
Broadcast by design returns `BitArray` when the element type is `Bool`, for efficiency.

**Comment by deahhh** [comment]
@jakobnissen 
Thanks again!
I see now that `BitVector` is better. I should improve my code.
Thanks!
