### ISSUE TITLE
Blue `source` button disappeared for part of the documentation

### ISSUE THREAD

**Issue by biona001** [JuliaLang/julia#47568]
This is a repost of [this discourse questions](https://discourse.julialang.org/t/why-did-the-source-button-in-julia-docs-disappear/90205). 

Basically, parts of the documentation no longer have the blue `source` button that takes you directly to the source code for that function. For example, the triple argument `dot(x, A, y)` 
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.dot-Tuple%7BAny,%20Any,%20Any%7D

But parts of the docs still do: e.g. `occursin` https://docs.julialang.org/en/v1/base/strings/#Base.occursin

**Comment by fredrikekre** [comment]
#47553
