### ISSUE TITLE
convert on named tuple can give "T not defined" error

### ISSUE THREAD

**Issue by knuesel** [JuliaLang/julia#47604]
This came up on [discourse](https://discourse.julialang.org/t/why-cant-this-named-tuple-be-converted-to-a-supertype/90329), the operation itself doesn't make sense  (it's "converting" to an abstract type that is already a supertype of the value so there's nothing to do) but it seems to have uncovered a bug:

```julia
julia> convert(@NamedTuple{a::S} where S, (; a=1))
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] convert(#unused#::Type{NamedTuple{(:a,), Tuple{S}} where S}, nt::NamedTuple{(:a,), Tuple{Int64}})
   @ Base ./namedtuple.jl:152
 [2] top-level scope
   @ REPL[2]:1
```

while for example the following works:

```julia
julia> convert(@NamedTuple{a::Vector{S}} where S, (; a=[1]))
(a = [1],)
```

```
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by jakobnissen** [comment]
It's the `convert` methods for `NamedTuple` which look to be a bit of a mess. It seem like they don't precisely convey the intention, namely:
* For namedtuples with the same names, if `T1 <: T2`, then `convert(Type{NamedTuple{names, T1}}, x::NamedTuple{names, T2}}) = x`. Ideally, this should just use the fallback `convert(::Type{T}, x::T) = x`
* Else, if `!(T1 <: T2)`, do `NamedTuple{names, T1}(T1(x))`

That's it. Ideally it could be done with one method, but I find it gets really tricky trying to define the right method signatures to do that.

**Comment by vtjnash** [comment]
```
julia> ccall(:jl_type_intersection_with_env, Any, (Any, Any), Type{NamedTuple{(:a,),Tuple{S}} where S}, Type{NamedTuple{names,T}} where {names,T})
svec(Type{NamedTuple{(:a,), Tuple{S}} where S}, svec((:a,), T<:(Union{Tuple{S1}, Tuple{S}} where {S, S1})))
```

This is vaguely really an intersection issue, where it does not compute T exactly. It should have concluded that `Tuple{Any}<:T<:Tuple{Any}`, and thus defined, but it got tripped up by the unidentified Union there and instead widened that to `T<:Tuple{Any}`

**Comment by vtjnash** [comment]
Actually, maybe it is a bit sketchier than that since there actually does not exist a value for `T` which should make this subtyping valid, but yet it still returns true.
```
julia> (Type{NamedTuple{(:a,),Tuple{S}} where S}) <: (Type{NamedTuple{names,T}} where {names,T})
true

julia> (NamedTuple{(:a,),Tuple{S}} where S) <: (NamedTuple{names,T} where {names,T})
true

julia> (NamedTuple{(:a,),Tuple{S}} where S) >: (NamedTuple{names,T} where {names,T})
false
```
