### ISSUE TITLE
nth_methtable：variable n may be 0, we will get the index value of tuple as -1

### ISSUE THREAD

**Issue by awfeequdng** [JuliaLang/julia#47625]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/8253416/202620376-51ed85a9-a09f-45ca-b477-83e6186eed3f.png">

in latest master method.c, in function nth_methtable, variable n may be 0, we will get the index value of tuple as -1

**Comment by vtjnash** [comment]
Looking closer, I realized that `jl_is_tuple_type(a)` implies `a->name == jl_tuple_typename` and `jl_tuple_typename->mt != NULL`, so this was not truly ever able to be reached. But better to be clear about that intent in the code (#47666).
