### ISSUE TITLE
Error 404 in installing julia?

### ISSUE THREAD

**Issue by adrianor** [JuliaLang/julia#47629]
I would like to install an older version of julia in order to do some comparisons with an old program I have. The version I'm trying to install is 1.3.0. For some reason, I get the following error

`julia]$ make`
`egrep: warning: egrep is obsolescent; using grep -E`
`egrep: warning: egrep is obsolescent; using grep -E`
`egrep: warning: egrep is obsolescent; using grep -E`
`Traceback (most recent call last):`
`  File "/home/jivifair/julia2/julia/contrib/normalize_triplet.py", line 113, in <module>`
`    gcc_version = {`
`KeyError: '1'`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`100   405  100   405    0     0    625      0 --:--:-- --:--:-- --:--:--   626`
`  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`curl: (22) The requested URL returned error: 404`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                Dload  Upload   Total   Spent    Left  Speed`
`  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`curl: (22) The requested URL returned error: 404`
`make[1]: *** [/home/user/julia2/julia/deps/suitesparse.mk:144: /home/user/julia2/julia/deps/srccache/SuiteSparse.v5.4.0-2..tar.gz] Error 22`
`make: *** [Makefile:60: julia-deps] Error 2`

Is there a reason why this should fail? I'm not behind any firewall or have connection problems. Indeed a couple of months back I installed 1.7.0 without problems.

**Comment by fredrikekre** [comment]
Probably https://github.com/JuliaLang/julia/blob/46ce4d79337bdd257ee2e3d2f4bb1c55ff0a5030/contrib/normalize_triplet.py#L34-L40 doesn't contain your gfortran version -- what is the output of `gfortran --version`?. I believe this is only needed when using prebuild binaries for the dependencies, so perhaps the easiest is to compile them yourself instead, IIRC you set the Make-variable `USE_BINARYBUILDER=0`. This will disable all prebuilt ones, probably you can filter this more granularly, I don't think all of them depend on the gfortran version.

As you probably know, Julia 1.3 is not supported anymore, but it is of course unfortunate that it doesn't build.

**Comment by adrianor** [comment]
Ok so the output is

`julia]$ gfortran --version`
`GNU Fortran (GCC) 12.2.0`

About the file you mention I indeed have

`gcc_version_mapping = {`
`    'blank_gcc': "",`
`    'gcc4': "-gcc4",`
`    'gcc7': "-gcc7",`
`    'gcc8': "-gcc8",`
`    'gcc9': "-gcc8",`
`}`

**Comment by apaz-cli** [comment]
@adrianor What version (git hash) of Julia are you building? In particular, does the version you're building include the changes from https://github.com/JuliaLang/julia/pull/47352?

**Comment by vtjnash** [comment]
He already said v1.3.0.

@adrianor You will probably need to patch that file to deal with gcc > 10 (aka '1') and map it to `-gcc8`, to attempt to get the right downloads, or set `USE_BINARYBUILDER=0` or `USE_SYSTEM_XXX=1` to get the dependencies locally

Alternatively, all of our old releases v0.3.1!) are still available on the downloads page (https://julialang.org/downloads/oldreleases/)

**Comment by adrianor** [comment]
@apaz-cli I'm not sure what is the git hash of Julia, how do I get it?

@vtjnash I guess `USE_BINARYBUILDER=0` needs to be added to one of the makefiles or config, which one of them has to go? (Thanks in advance.)

**Comment by vtjnash** [comment]
Make.user is a good place to add it (create that file)

**Comment by adrianor** [comment]
Ok, it didn't work the option `USE_BINARYBUILDER=0` but I downloaded the version from the linked webpage and it seems to be running fine.
