### ISSUE TITLE
Windows portable executables not digitally signed for 1.8.3

### ISSUE THREAD

**Issue by pwstokes225** [JuliaLang/julia#47639]
Noticed after I was unable to access pkg.julialang.org from within my organisation. (Fortunately the installer versions are unaffected).

**Comment by DilumAluthge** [comment]
@staticfloat @inkydragon Seems like a bug we introduced when we migrated Windows to Buildkite?

**Comment by inkydragon** [comment]
Closed as it was fixed in the new version.

A quick check shows that both v1.10.6-x64 and v1.11.1-x64 have valid digital signatures.
