### ISSUE TITLE
How to launch julia 1.9 alpha1 with multithreads 

### ISSUE THREAD

**Issue by MrBenzWorld** [JuliaLang/julia#47642]
I have installed julia 1.8.3 and julia 1.9 alpha1. 

when i enter "julia -t auto",  julia 1.8.3 is running.
Please tell me , how to launch julia 1.9 alpha1 with mulithreads.

Also, vs code is not supporting julia 1.9 alpha1

**Comment by DilumAluthge** [comment]
Please ask usage questions on Discourse: https://discourse.julialang.org
