### ISSUE TITLE
bug Julia 1.9. alpha1

### ISSUE THREAD

**Issue by MrBenzWorld** [JuliaLang/julia#47641]
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.

```
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffcaebb57ff -- jl_object_id__cold at C:/workdir/src\builtins.c:417

Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffcaeba47e6 --  at 0x7ffcaeba47e6 -- ION at 0x7ffcaeba4712 --  at 0x7ffcaeba4712 -- ION with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: UNKNOWN at 0x7ffd3f719680 --  at 0x7ffd3f719680 -- ION at 0x7ffcaeba47e6 -- EXCEPTION_ACCESS_VIOLATION at 0x7ffcaeba47e6 --  at 0x7ffcaeba47e6 -- IONEXCEPTION_ACCESS_VIOLATIONmemcpy at C:\WINDOWS\Smemcpy at C:\WINDOWS\System32\msvcrt.dll (unknown line)
in expression starting at none:1
jl_lookup_generic_ at C:/workdir/src\gf.c:2560
```

**Comment by KristofferC** [comment]
> Please submit a bug report with steps to reproduce this fault

Could you also ass that please.

**Comment by brenhinkeller** [comment]
@MrBenzWorld what were you doing when this error occurred? (i.e., steps to reproduce)

**Comment by MrBenzWorld** [comment]
it is crashing when I'm running SymbolicRegression.jl with more than 10000

**Comment by brenhinkeller** [comment]
Can you provide an MWE?

**Comment by MrBenzWorld** [comment]
Julia 1.9. alpha1  ,it is crashing when I'm running SymbolicRegression.jl with more than 10000 @ViralBShah @KristofferC @brenhinkeller

**Comment by brenhinkeller** [comment]
Yes, can you provide an [MWE](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=A%20minimal%20reproducible%20example%20may,short%20self%2Dcontained%20correct%20example) please. I.e., source code that can be exactly pasted into a terminal to produce the same error

**Comment by MrBenzWorld** [comment]
using SymbolicRegression, SymbolicUtils

import XLSX
xf = XLSX.readxlsx("BB.xlsx")

X=xf["Sheet1!A1:GV7"];
y=xf["Sheet1!A8:GV8"];
X=Float32.(X);
y=y[:];
y=Float32.(y);


options = SymbolicRegression.Options(
                                        binary_operators=(+, *, /, -,^),
                                        unary_operators=(cos,exp,sqrt),
                                        npopulations=10,
                                        maxsize=25,
                                        #complexity_of_operators=3,
                                        #complexity_of_constants=nothing,
                                        complexity_of_variables=2,
                                        #loss=L2DistLoss(),
                                        #enable_autodiff=true
                                    )

hall_of_fame = EquationSearch( X, y, niterations=10000, options=options)       #parallelism=:multithreading

dominating = calculate_pareto_frontier(X, y, hall_of_fame,options)


trees = [member.tree for member in dominating]

tree = trees[end]
output, did_succeed = eval_tree_array(tree, X, options)


eqn = node_to_symbolic(dominating[end].tree, options)
println(simplify(eqn*5 + 3))

**Comment by MrBenzWorld** [comment]
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffd2ec457ff -- jl_object_id__cold at C:/workdir/src\builtins.c:417
in expression starting at E:\YandexDisk\Learning new things\Julia\SymbolicRegression\NewNov196.jl:25
jl_object_id__cold at C:/workdir/src\builtins.c:417
type_hash at C:/workdir/src\jltypes.c:1171
typekey_hash at C:/workdir/src\jltypes.c:1183
jl_precompute_memoized_dt at C:/workdir/src\jltypes.c:1248
inst_datatype_inner at C:/workdir/src\jltypes.c:1570
jl_inst_arg_tuple_type at C:/workdir/src\jltypes.c:1665
arg_type_tuple at C:/workdir/src\gf.c:1966 [inlined]
jl_lookup_generic_ at C:/workdir/src\gf.c:2576
ijl_apply_generic at C:/workdir/src\gf.c:2628
do_apply at C:/workdir/src\builtins.c:703
min at .\operators.jl:578
jl_apply at C:/workdir/src\julia.h:1868 [inlined]
do_apply at C:/workdir/src\builtins.c:730
move_window! at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\AdaptiveParsimony.jl:74
#_EquationSearch#23 at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:850
_EquationSearch at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:392 [inlined]
#EquationSearch#22 at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:379
EquationSearch at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:344 [inlined]
#EquationSearch#17 at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:316
EquationSearch at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:282 [inlined]
#EquationSearch#21 at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:341 [inlined]
EquationSearch at C:\Users\Mr.Benz\.julia\packages\SymbolicRegression\kmBnt\src\SymbolicRegression.jl:338
unknown function (ip: 0000025e64900662)
jl_apply at C:/workdir/src\julia.h:1868 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:226
eval_stmt_value at C:/workdir/src\interpreter.c:177 [inlined]
eval_body at C:/workdir/src\interpreter.c:624
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:762
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:912
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:856
ijl_toplevel_eval at C:/workdir/src\toplevel.c:921 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:971
eval at .\boot.jl:370 [inlined]
include_string at .\loading.jl:1522
_include at .\loading.jl:1582
include at .\client.jl:478
unknown function (ip: 0000025e64829006)
jl_apply at C:/workdir/src\julia.h:1868 [inlined]
do_call at C:/workdir/src\interpreter.c:126
eval_value at C:/workdir/src\interpreter.c:226
eval_stmt_value at C:/workdir/src\interpreter.c:177 [inlined]
eval_body at C:/workdir/src\interpreter.c:624
jl_interpret_toplevel_thunk at C:/workdir/src\interpreter.c:762
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:912
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:856
ijl_toplevel_eval at C:/workdir/src\toplevel.c:921 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:971
eval at .\boot.jl:370 [inlined]
eval_user_input at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:152
repl_backend_loop at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:248
#start_repl_backend#46 at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:233
start_repl_backend at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:230 [inlined]
#run_repl#59 at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:376
run_repl at C:\workdir\usr\share\julia\stdlib\v1.9\REPL\src\REPL.jl:362
jfptr_run_repl_57687.clone_1 at C:\Users\Mr.Benz\AppData\Local\julias\julia-1.9\lib\julia\sys.dll (unknown line)
#1016 at .\client.jl:421
jfptr_YY.1016_35907.clone_1 at C:\Users\Mr.Benz\AppData\Local\julias\julia-1.9\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1868 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:774
#invokelatest#2 at .\essentials.jl:816 [inlined]
invokelatest at .\essentials.jl:813 [inlined]
run_main_repl at .\client.jl:405
exec_options at .\client.jl:322
_start at .\client.jl:522
jfptr__start_28329.clone_1 at C:\Users\Mr.Benz\AppData\Local\julias\julia-1.9\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:1868 [inlined]
true_main at C:/workdir/src\jlapi.c:573
jl_repl_entrypoint at C:/workdir/src\jlapi.c:717
mainCRTStartup at C:/workdir/cli\loader_exe.c:59
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 1168415476 (Pool: 1165722462; Big: 2693014); GC: 295

**Comment by MrBenzWorld** [comment]
I have used JILL.py to install Julia 1.8.3 and 1.9.alpha1

, do you think, it is the reason ?

"jfptr__start_28329.clone_1 at C:\Users\Mr.Benz\AppData\Local\julias\julia-1.9\lib\julia\sys.dll (unknown line)"

**Comment by brenhinkeller** [comment]
Ok thanks, that helps. Looks like to run this will also need the file "BB.xlsx", or a way of generating equivalent data that also produces the fault

**Comment by MrBenzWorld** [comment]
[BBcopy.xlsx](https://github.com/JuliaLang/julia/files/10110251/BBcopy.xlsx)

**Comment by brenhinkeller** [comment]
Awesome, that runs now. 

On Mac with Julia started with 8 threads this runs without error on 1.8.3, whereas it appears to hang indefinitely during the `EquationSearch` on 1.9.0-alpha1. 

Someone with access to a windows machine should be able to attempt to reproduce the exact error you report now.

**Comment by MrBenzWorld** [comment]
yes, there is now problem with 1.8.3 , only problem with 1.9.0-alpha1 on windows 11

**Comment by ViralBShah** [comment]
Please reopen if still an issue with the latest 1.9.x.
