### ISSUE TITLE
Opposite core function to isa()

### ISSUE THREAD

**Issue by mgg39** [JuliaLang/julia#47653]
I feel like an opposite function to isa() would be useful. Something that ran: 
`
if isa(a,type) 
    false
else
    true
end
`
and could be called as isnot(a,type). Would this be useful? Is there any reason why it wouldn't work?

**Comment by Keno** [comment]
What's wrong with `!isa`?

**Comment by mgg39** [comment]
didn't know that was an option, thanks!
