### ISSUE TITLE
USE_BINARYBUILDER=0 on `master`

### ISSUE THREAD

**Issue by smartalecH** [JuliaLang/julia#47656]
Does `USE_BINARYBUILDER=0` only work for "full" release tarballs, and not for the `git` master branch? From the [docs](https://github.com/JuliaLang/julia/blob/master/doc/src/devdocs/build/build.md), it sounds like it should indeed work... however the current `master` branch ignores the flag and always attempts to download the binaries.

**Comment by DilumAluthge** [comment]
It is intended to work on master; if it doesn't, then it's a bug.

Can you provide:
1. Your operating system
2. Your CPU architecture
3. The exact commit of `master` that you tried to build
4. The exact `make` invocation that you used
5. Did you have a `Make.user` file? If so, can you post the contents of it?

**Comment by smartalecH** [comment]
Got it, thanks!

> Your operating system

CentOS 8 (CentOS 7 also fails)

> Your CPU architecture

x86_64, Intel Broadwell

> The exact commit of master that you tried to build

`ab262e73104994e05c149d5b21f1ba71139b6fca`

> The exact make invocation that you used

I tired `make` with a `Make.user`. That didn't work, so I tried `make USE_BINARYBUILDER=0`. That didn't work either.

> Did you have a Make.user file? If so, can you post the contents of it?

Yes,

```
USE_BINARYBUILDER=0
```

**Comment by smartalecH** [comment]
> so I also had to disable the builds for CSL, LLD, ZLIB, and P7ZIP to get anywhere after downloading the sources:

So that's indeed problematic. But I think I also misunderstood something -- are the deps sources themselves not bundled? I was under the impression that with `USE_BINARYBUILDER=0`, I shouldn't need to download _anything_?

**Comment by StefanKarpinski** [comment]
No, we don't bundle any dependency sources. If you disable BB, then the makefiles will download all dependency sources from their origin locations and build them for you.

**Comment by smartalecH** [comment]
Great, thanks @StefanKarpinski!

In the docs, I'm looking at the following:

https://github.com/JuliaLang/julia/blob/23160a109dd9dff845ef8670b7545ab6ad23ae18/doc/src/devdocs/build/build.md?plain=1#L19-L26

I'm on a system that doesn't have access to the internet. But I want to build from `master`, so that I can leverage a recent bugfix not yet backported to the release tarballs (#46976). I was under the impression that `USE_BINARYBUILDER=0` would take care of this for me, per the above blurb. Do I have a workaround?

Thanks for the help!

**Comment by smartalecH** [comment]
>  Perhaps a command that can fetch the sources beforehand (while I do have network access) and then build as if this were a "full" release?

I found this useful command:

https://github.com/JuliaLang/julia/blob/67b8ac020833a14d98e8a147b8aae5caf2288a41/Makefile#L537

which can be used to fetch all the dependency sources before I start the build process (where I lose network access). While it fetches most sources, it does throw the following error:

```
make: *** No rule to make target 'get-lld', needed by 'getall'.  Stop.
```

Although it looks like #47589 fixes this?

**Comment by ViralBShah** [comment]
I believe this works now. Please reopen if still broken.
