### ISSUE TITLE
Bug in subtyping resolution

### ISSUE THREAD

**Issue by olynch** [JuliaLang/julia#47654]
This bug is succinctly described by the following code:

```julia
const NullableVec{T} = Union{AbstractVector{T}, AbstractVector{Union{T,Nothing}}}

struct NullableVecWrapper{T, V<:NullableVec{T}}
  v::V
end

abstract type P{A} end

NV = NullableVecWrapper{P, Vector{Union{P,Nothing}}}

NV <: NullableVecWrapper
> false
```

My julia version is 1.8.3, and I installed it through nix: https://github.com/olynch/scientific-fhs. Julia 1.7 and 1.6 do not have this bug.

**Comment by brenhinkeller** [comment]
Can reproduce on 1.8.3 and 1.9.0-alpha1 official binaries

**Comment by vtjnash** [comment]
You are allowed to create types that are not subtypes of the original, as long as they remain abstract. What remains interesting about this example though is that it remains reproducible after considerable simplification:
```julia
julia> abstract type P{A} end

julia> struct P2{A} end

julia> struct NullableVecWrapper{T, V<:Vector{Union{T,Nothing}}} end

julia> NullableVecWrapper{P} <: NullableVecWrapper # or AbstractRange, Ref, etc.
false

julia> NullableVecWrapper{P2} <: NullableVecWrapper # or Complex, Rational, Val, etc.
false
```

**Comment by N5N3** [comment]
The above looks quite similar to the example in https://github.com/JuliaLang/julia/issues/45874#issuecomment-1172384954

**Comment by jpfairbanks** [comment]
I just tested on 1.9.0-beta2 and it still reproduces.

**Comment by vtjnash** [comment]
@JeffBezanson This returns the right answer now. Can you close it?

**Comment by brenhinkeller** [comment]
Can confirm the fix on nightly!
```
julia> abstract type P{A} end

julia> struct P2{A} end

julia> struct NullableVecWrapper{T, V<:Vector{Union{T,Nothing}}} end

julia> NullableVecWrapper{P} <: NullableVecWrapper # or AbstractRange, Ref, etc.
true

julia> NullableVecWrapper{P2} <: NullableVecWrapper # or Complex, Rational, Val, etc.
true
```

**Comment by oscardssmith** [comment]
Should we add a test?
