### ISSUE TITLE
`truncate` removes file contents

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#47663]
When calling `truncate` on an `IOStream`, the contents of the file are replaced with null bytes:

```julia
julia> cd(mktempdir())

julia> write("test.foo", "This is a long string of more than 10 bytes")
43

shell> cat test.foo
This is a long string of more than 10 bytes
julia> f = open("test.foo", "w+")
IOStream(<file test.foo>)

julia> truncate(f, 10)
IOStream(<file test.foo>)

julia> flush(f)

julia> close(f)

shell> cat test.foo

julia> read("test.foo", String) |> length
10

julia> read("test.foo", String)
"\0\0\0\0\0\0\0\0\0\0"

julia> versioninfo()
Julia Version 1.10.0-DEV.6
Commit 4cf077cd9a (2022-11-14 21:07 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by brenhinkeller** [comment]
Can reproduce on 1.8.3. Was this different at some point in the past?

**Comment by brenhinkeller** [comment]
It does seem nonideal

**Comment by brenhinkeller** [comment]
Reproduces on 1.0.5 as well! So I won't call it a regression, but could be a bug (or just a weird design decision)...

**Comment by brenhinkeller** [comment]
For context the docstring
```
help?> truncate
search: truncate

  truncate(file, n)

  Resize the file or buffer given by the first argument to exactly n bytes, filling
  previously unallocated space with '\0' if the file or buffer is grown.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> io = IOBuffer();

  julia> write(io, "JuliaLang is a GitHub organization.")
  35

  julia> truncate(io, 15)
  IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=15, maxsize=Inf, ptr=16, mark=-1)

  julia> String(take!(io))
  "JuliaLang is a "

  julia> io = IOBuffer();

  julia> write(io, "JuliaLang is a GitHub organization.");

  julia> truncate(io, 40);

  julia> String(take!(io))
  "JuliaLang is a GitHub organization.\0\0\0\0\0"
```

**Comment by vtjnash** [comment]
You might be confused here by this: ```f = open("test.foo", "w+")```. The mode `w+` means open-and-delete-file. You probably wanted `r+` there from your description?

**Comment by brenhinkeller** [comment]
Ah yeah. Here are the results under some different modes for comparison
```
julia> cd(mktempdir())

julia> write("test.foo", "This is a long string of more than 10 bytes")
43

shell> cat test.foo
This is a long string of more than 10 bytes
julia> f = open("test.foo", "r+")
IOStream(<file test.foo>)

julia> flush(f)

julia> close(f)

shell> cat test.foo
This is a long string of more than 10 bytes
shell>

julia> f = open("test.foo", "a+")
IOStream(<file test.foo>)

julia> truncate(f, 10)
IOStream(<file test.foo>)

julia> flush(f)

julia> close(f)

shell> cat test.foo
This is a

julia> read("test.foo", String) |> length
10

julia> read("test.foo", String)
"This is a "
```
Mode "r+" looks all good, and mode "a+" is actually not in the docstring for `open` so maybe not valid?

**Comment by Seelengrab** [comment]
> The mode w+ means open-and-delete-file. You probably wanted r+ there from your description?

Well that would mean the docstring for `open` is wrong:

> w+   read, write, create, truncate truncate = true, read = true

`r+` in contrast does not mention `truncate` at all..

**Comment by vtjnash** [comment]
Yes, truncate = delete-file-contents

**Comment by Seelengrab** [comment]
Yeah, but all of them and overwrite/replace with a `\0` filled file of the requested size? Is that also what `ftruncate` does?

**Comment by vtjnash** [comment]
the `truncate=true` flag is equivalent to `truncate(f, 0)`, in the absence of race conditions

**Comment by Seelengrab** [comment]
I'm not sure I understand that comment or why this was closed. This issue is about the `truncate` function replacing a file longer than the requested size with a file filled entirely with `\0`. The expectation would be that the existing contents of the file are preserved, as is the case for `IOBuffer`. It's not related to the behavior of the `truncate=true` keyword.

**Comment by Seelengrab** [comment]
Ah I see the issue now - due to `w+`, the file got immediately truncated to 0 bytes, and the subsequent call to `truncate` then "grew" the file to 10 bytes, filling with `\0`.
