### ISSUE TITLE
Issue when using non integer exponents on Float64 Vectors that contain "-Inf" 

### ISSUE THREAD

**Issue by JonaHammer** [JuliaLang/julia#47669]
Hey, 

I found a bug when using non integer exponents on Float64 Vectors that contain -Inf as value. 
Below you find an example and Version info. 

Kind regards and many thanks for your time and effort. 

Example: 
```
> [1,2,Inf].^3.5 #Working
3-element Vector{Float64}:
  1.0
 11.313708498984761
 Inf
```
```
> [1,2,-Inf].^3 #Working
3-element Vector{Float64}:
   1.0
   8.0
 -Inf
```
```
> -Inf^3.5 #Working
 -Inf
```
```
>  [1,2,-Inf].^3.5 #Error 
DomainError with -Inf:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
```

Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 256 × AMD EPYC 7702 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 256 virtual cores

**Comment by giordano** [comment]
I don't think

> ```
> > -Inf^3.5 #Working
>  -Inf
> ```

is doing what you think:

```julia
julia> Meta.@lower -Inf^3.5
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = Inf ^ 3.5
│   %2 = -%1
└──      return %2
))))
```

That's equivalent to `-(Inf^3.5)`, not `(-Inf)^3.5`:
```julia
julia> (-Inf) ^ 3.5
ERROR: DomainError with -Inf:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(x::Float64)
   @ Base.Math ./math.jl:37
 [2] ^(x::Float64, y::Float64)
   @ Base.Math ./math.jl:1008
 [3] top-level scope
   @ REPL[11]:1
```

I don't see any bugs and the problem is described in the error message: if you want to raise a negative number to a fractional power, you need to make the base complex:
```julia
julia> complex(-Inf) ^ 3.5
NaN - Inf*im
```

**Comment by JonaHammer** [comment]
Ok, thanks for the prompt response. But why does the elementwise operation on the vector behave different from the operation on a single Float64 value? This confused me.

**Comment by giordano** [comment]
What are you referring to specifically?

**Comment by JonaHammer** [comment]
See the examples bellow. If the second throws an error. Why doesnt the first one?
`-Inf^3.5 #Working
 -Inf`

` [1,2,-Inf].^3.5 #Error 
DomainError with -Inf:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.`

**Comment by giordano** [comment]
I already answered in my [previous message](https://github.com/JuliaLang/julia/issues/47669#issuecomment-1324169888): 

> That's equivalent to `-(Inf^3.5)`, not `(-Inf)^3.5`
