### ISSUE TITLE
ASAN: debug build fails

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#47698]
Trying to make a debug build of Julia under ASAN I'm running into:

```
ERROR: Unable to load dependent library libjulia-internal-debug.so.1
Message: libjulia-internal-debug.so.1: undefined symbol: __libc_siglongjmp
```

Use of this symbol was introduced by @keno in https://github.com/JuliaLang/julia/pull/46336, and is intended to bypass the ASAN hook and directly call siglongjmp from glibc. I'm not sure why it isn't working; @vtjnash commented that this symbol has been named like that for 25 years. Disabling the redefinition and just using `siglongjmp` works around the compilation error.

`objdump` output:
```
objdump -t libjulia-internal-debug.so.1 | grep siglong
0000000000000000       F *UND*  0000000000000000              siglongjmp@GLIBC_2.2.5
0000000000000000         *UND*  0000000000000000              __libc_siglongjmp
```

**Comment by topolarity** [comment]
On my system (Ubuntu 22.04), the symbol is still present in libc (you can see it in the objdump output of `libc.so.6`) but it's not published to the symbol tables.

I expect it's intended not to be exported, and we need to find another way to bypass the interceptor for `siglongjmp`
