### ISSUE TITLE
dot product wrong result

### ISSUE THREAD

**Issue by ropewe56** [JuliaLang/julia#47702]
Hi,

using the dot product of LinearAlgebra I encounter a problem regarding the exactness of the results.

versioninfo():
```
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
```
Installation:
I downloaded and unpacked julia-1.8.2-linux-x86_64.tar.gz

The problem is as follows:
```julia
using LinearAlgebra

mydot(a, b) = sqrt(a[1]*b[1] + a[2]*b[2] + a[3]*b[3])

a = normalize(ones(Float64, 3))
b = normalize(ones(Float64, 3))
println(norm(a) <= 1.0)
println(norm(b) <= 1.0)

println("mydot")
ab = mydot(a, b)
println(ab <= 1.0)
println(acos(ab))

println("dot")
ab = dot(a, b)
println(ab <= 1.0)
acos(ab)
```

Output:
```
true
true
mydot
true
0.00000e+00
dot
false
ERROR: DomainError with 1.00000e+00:
acos(x) not defined for |x| > 1
Stacktrace:
 [1] acos_domain_error(x::Float64)
   @ Base.Math ./special/trig.jl:669
 [2] acos(x::Float64)
   @ Base.Math ./special/trig.jl:699
 [3] top-level scope
   @ ~/dot_test.jl:18
```

I'm using dot products in my optical ray tracing code, where high high precision is required. My workaround is to define my own dot function. But I think this is an issue others may struggle with too.

Rolf Wester

**Comment by ropewe56** [comment]
Sorry my fault.

```julia
mydot(a, b) = a[1]*b[1] + a[2]*b[2] + a[3]*b[3]
```

**Comment by KristofferC** [comment]
Floating point arithmetic is not exact. If you know you have normalized `a` and `b` you can just `clamp` the result to be within the proper range.

As a side note, for vectors of size 3 (like in a ray tracer you should really really be using the StaticArrays package):

```julia
julia> using StaticArrays

julia> a = ones(SVector{3});

julia> b = ones(SVector{3});
```

etc
