### ISSUE TITLE
in gf.c jl_type_infer: why not define in_reference as atomic

### ISSUE THREAD

**Issue by awfeequdng** [JuliaLang/julia#47712]
in master branch, file gf.c, function jl_type_infer: why not define in_reference as atomic
<img width="819" alt="image" src="https://user-images.githubusercontent.com/8253416/204083523-b62c4c62-a574-4d14-9930-833752130438.png">

**Comment by fingolfin** [comment]
The code in there was only run if a lock was held, so no need for atomics.

But it also was replaced by different code in PR #46825.

So I think this can be closed?
