### ISSUE TITLE
`*.dSYM` files are missing on apple in installations / releases

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#47744]
We ship (the equivalent of) `.dSYM` files on all other platforms, so it is weird for these to be missing from just Apple platforms, and can significantly hurt the debugging experience there when using releases (it is the moral equivalent to passing `objcopy --strip-debug` during `make install` on all other platforms)

**Comment by KristofferC** [comment]
>  can significantly hurt the debugging experience there when using releases

Out of curiosity, is there a concrete example where you can see the difference in error info between the platforms? I'm just thinking since no one seems to have complained.

**Comment by fingolfin** [comment]
Shipping `*.dSYM` files in releases seems unusual. Not aware of anything else doing that? (That said, "nobody else doing that" isn't a particular good argument; just wondering)

**Comment by gbaraldi** [comment]
IIRC, we do generate the files, we are probably just not copying them to the release.

**Comment by vtjnash** [comment]
Most platforms ship them in some form. Often as optional packages with the suffix `-dbg` on the installed name, split out from the build when packaging it (with `objcopy --strip-debug`–we even do that automatically in our build tests with JULIA_SPLITDEBUG to run some specific tests of the functionality). We also ship them on all other platforms, so it is weird for us to not ship this info specifically just on Apple.

@KristofferC Users probably just don't know what is broken relative to what it could do. You have to take a little extra effort to look at `C=true` info in stacktraces, profiling, or lldb. It took me a bit to realize what Elliot meant when he was screensharing with me debugging something in an installation and asked me why the backtraces were wonky. And I realized I had mentally filtered out the bad stuff because it was not currently relevant, and I knew my local build didn't have that issue.

**Comment by ViralBShah** [comment]
If it improves the user experience, I suppose we should copy them. What's the size impact?
