### ISSUE TITLE
Providing a non-Int64 N parameter to NTuple within a struct does not throw error

### ISSUE THREAD

**Issue by mkitti** [JuliaLang/julia#47748]
I provide a `Int8` or `UInt8` value as the first parameter to a `NTuple` within a struct, I get a `Union{}` for its type with `fieldtype`. I would have expected an error similar to the one received when trying to construct a `NTuple` directly. 

```
julia> struct S{P}
           x::NTuple{P,UInt32}
       end

julia> fieldtype(S{2},1)
Tuple{UInt32, UInt32}

julia> fieldtype(S{0x2},1)
Union{}

julia> fieldtype(S{Int8(2)},1)
Union{}

julia> fieldtype(S{Int16(2)},1)
Union{}

julia> fieldtype(S{Int32(2)},1)
Union{}

julia> fieldtype(S{Int64(2)},1)
Tuple{UInt32, UInt32}

julia> fieldtype(S{Int128(2)},1)
Union{}

julia> NTuple{0x2, UInt32}
ERROR: TypeError: in Vararg, in count, expected Int64, got a value of type UInt8
Stacktrace:
 [1] top-level scope
   @ REPL[15]:1
```

**Comment by vtjnash** [comment]
`fieldtypes` are not part of the identity of a type, so construction of it is legal, though this may be a bit of a surprise that could be better documented to be google-searchable (c.f. https://github.com/JuliaLang/julia/pull/31877)
