### ISSUE TITLE
RNG is uninitialized on foreign threads

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#47757]
If we examine the rngState of a foreign thread after launch, we see it is uninitialized (set to zero explicitly)
```julia
$ ./julia -t1 -q
julia> threadwork = @cfunction ()->UInt(current_task().rngState0 == current_task().rngState1 == current_task().rngState2 == current_task().rngState3 == 0) UInt ()
Ptr{Nothing} @0x0000000116b88760

julia> tid = UInt[0]; @ccall pthread_create(tid::Ptr{UInt}, C_NULL::Ptr{Cvoid}, threadwork::Ptr{Cvoid}, C_NULL::Ptr{Cvoid})::Cint; result = UInt[0]; @ccall pthread_join(tid[]::UInt, result::Ptr{Cvoid})::Cint; Bool(result[])
true
```

**Comment by JeffBezanson** [comment]
It seems to me we can't "fork" these from any other thread in the usual way, and we can't repeat initialization of `Random`, so my only idea is to initialize the state with `jl_rand`.

**Comment by vtjnash** [comment]
`jl_rand` could be okay (though is weak randomness), or we can use `uv_random` (which is where `jl_rand` got its seed from), or we could split from `finalizer_rngState`. Many fine choices.

**Comment by StefanKarpinski** [comment]
Importantly: this isn't consistent so we can change how we initialize this late if we decide something else is better.
