### ISSUE TITLE
Matrix exponential missing for triangular matrices

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#47787]
For some reason, matrix exponentials don't work with upper-triangular matrices, which I find very weird.
```
julia> using Random, LinearAlgebra

julia> exp(UpperTriangular(randn(10, 10)))
ERROR: MethodError: no method matching exp(::UpperTriangular{Float64, Matrix{Float64}})
Closest candidates are:
  exp(::Union{Float16, Float32, Float64}) at special/exp.jl:326
  exp(::StridedMatrix{var"#s885"} where var"#s885"<:Union{Float32, Float64, ComplexF32, ComplexF64}) at ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/dense.jl:569
  exp(::StridedMatrix{var"#s885"} where var"#s885"<:Union{Integer, Complex{<:Integer}}) at ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/dense.jl:570
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[296]:1
```

**Comment by mikmoore** [comment]
We're missing a generic matrix exponential. `exp(A::StridedMatrix{<:BlasFloat})` is the most general matrix exponential we offer. That method eventually calls to `exp!(A::StridedMatrix{T}) where T<:BlasFloat`. The parts that depend on `StridedMatrix{<:BlasFloat}` appear to mostly be some pre- and post-processing that improve the efficiency and conditioning of the calculation but that are not strictly required (I think?). There is also a `LAPACK.gesv!` call that could be replaced by a more generic alternative. It seems that it should be possible to separate the core of that function into a routine that we could use for any matrix.
