### ISSUE TITLE
`mod1` documentation unclear

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#47784]
```julia
  mod(x, y)
  rem(x, y, RoundDown)


  The reduction of x modulo y, or equivalently,

help?> mod1
search: mod1 fldmod1 @macroexpand1 modf mod module mod2pi Module modifyfield! modifyproperty! chmod __module__ invmod fldmod

  mod1(x, y)


  Modulus after flooring division,
```

it's unclear to me what part of `mod1` uses `fld` (in the code it doesn't, it just maps 0 result of mod -> y).

This also raises a second question, why `mod1` is implemented like this? Originally I thought `mod1(x,y) = mod(x,y) + 1` because that would allow me to translate some 0-index code to Julia, but with the current `mod1` it's not a shift:
```julia
julia> @. mod(30:34, 5)
5-element Vector{Int64}:
 0
 1
 2
 3
 4

julia> @. mod(30:34, 5) + 1
5-element Vector{Int64}:
 1
 2
 3
 4
 5

julia> @. mod1(30:34, 5)
5-element Vector{Int64}:
 5
 1
 2
 3
 4
```

**Comment by StefanKarpinski** [comment]
The idea of `mod1` is that it should map your values into the range `1:n` like indices into a 1-based array.

**Comment by Moelf** [comment]
yeah, but why is `mod1` not `mod() + 1`? which would preserve the ordering and accomplish the same thing (i.e map into `1:n` instead of `0:n-1`), as you can see from the example above, `mod1` has the "wrong ordering"

**Comment by Moelf** [comment]
`mod() + 1` has the nice feature that if you have an array of length n you index into, `mod(x, n)`  would be 0-based index, and `mod(x,n) + 1` would be your 1-based index, that maps the same n into the same object in your array

**Comment by StefanKarpinski** [comment]
What `mod1(i, n)` is supposed to give you is a value `j` such that `1 ≤ j ≤ n` and `mod(i, n) == mod(j, n)`. If that's not the function you want, writing `mod(i, n) + 1` is easy to write and will always give you a value in `1:n`. You seem to imagine that the function is for translating 0-based indices to 1-based indices, but that's not the case: it's for translating 1-based indices into 1-based modular indices.

**Comment by StefanKarpinski** [comment]
What concerns me more is the behavior of `mod1(i, n)` for negative `n`. It seems to give values in `n:-1` which doesn't seem like an obviously useful or correct behavior, but then again I'm not sure what the model for useful or correct behavior is for negative `n`.
