### ISSUE TITLE
Revise sort.md

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#47789]
There have been lots of changes to sorting in 1.9. We should make sure that sort.md reflects those changes (excluding those that we want to remain internal)

**Comment by mohit-marathe** [comment]
Hello @LilithHafner, I would like to work on this issue. Can you tell me what the changes are in sorting, that you want to see in sort.md?

**Comment by LilithHafner** [comment]
I'm glad you want to help! There have been quite a few changes between 1.8 and 1.9, centered on adding radix sort and a new stable QuickerSort and adjusting the default algorithms to utilize these algorithms when they are faster.

This is a [full list of changes](https://github.com/JuliaLang/julia/pulls?page=1&q=is%3Apr+is%3Amerged+label%3Asort); everything since #42674 is new in 1.9.

The most relevant ones are #44230, #45211, #45222, #45330 (but this is intentionally undocumented because it is not polished enough to commit to a public API), #47191, #47309, #47383, #47579, and #47788.

**Comment by KristofferC** [comment]
@LilithHafner, are you planning on doing this?

**Comment by LilithHafner** [comment]
Yes; currently traveling but likely within a week or two

**Comment by gbaraldi** [comment]
Bump!

**Comment by KristofferC** [comment]
I'll take this off the milestone, I don't think we will delay the release for a set of docs about sorting.
