### ISSUE TITLE
The isdisjoint function is much worse than isempty(a ∩ b) on ranges.

### ISSUE THREAD

**Issue by nikola-benes** [JuliaLang/julia#47796]
The documentation for `isdisjoint` states: “Determine whether the collections a and b are disjoint. Equivalent to `isempty(a ∩ b)` but more efficient when possible.”

However, this is not true for ranges. Consider

    r1 = 1:2^60
    r2 = 2^60:2^62

Now, `isempty(r1 ∩ r2)` computes almost instantly, while `isdisjoint(r1, r2)` takes longer than I am willing to wait (the complexity seems to be linear in the size of the smaller range). Perhaps there should be a specialisation of `isdisjoint` for ranges?

The output of `versioninfo()`:
```
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by jakobnissen** [comment]
See also: https://github.com/JuliaLang/julia/pull/46356 (which could provide a fast implementation)

**Comment by halleysfifthinc** [comment]
Also note that `isempty(r1 ∩ r2)` (`isempty(intersect(r1,r2))`) will not always be correct due to a bug (#47577) in `intersect`.
