### ISSUE TITLE
Different processes return slightly different results when calculating A\b

### ISSUE THREAD

**Issue by jacobadenbaum** [JuliaLang/julia#47818]
It looks as though julia is producing slightly different results when inverting a linear system depending on which process the calculation is run on.  I know that this difference is small, but it is larger than machine precision, and I ran into this bug in a larger problem where the errors seemed to propagate to cause much larger discrepancies in the final results.  

Moreover, I would have expected that these two calculations would return _exactly_ the same value, given that the only difference is which cpu it is executed on.  

Note: this example is on an M1 macbook pro running the native binary, although we ran into a similar issue when running it through rosetta.  

```julia
julia> using Distributed; addprocs();

julia> using Random; Random.seed!(42);

julia> A = randn(300,300); b = randn(300,1);

julia> x1 = remotecall_fetch((A,b) -> sum(A\b), 1, A, b)
-4.413352831325809

julia> x2 = remotecall_fetch((A,b) -> sum(A\b), 2, A, b)
-4.413352831325543

julia> x1 - x2
-2.6556534749033744e-13
```

System information:
```julia
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by oscardssmith** [comment]
This is expected do to differences in vectorization.
