### ISSUE TITLE
Julia repl process with even `--color=no` outputs certain control sequence which is causing prompt to disappear when used in `emacs comint`

### ISSUE THREAD

**Issue by Inc0n** [JuliaLang/julia#47837]
## versioninfo()

```
Julia Version 1.8.3
Commit 0434deb161* (2022-11-14 20:14 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

## MWE

This is done in emacs
1. use `run-julia` command to start the julia repl  (Use `--color=no`)
2. Evaluate the following
```
(defvar inf-julia-kept-output nil)
  ;; (setq inf-julia-kept-output nil)
  (let* ((buf (get-buffer "*Julia*"))
		 (process (get-buffer-process buf)))
	(set-process-filter (get-process "Julia")
						(lambda (process output)
						  (push output inf-julia-kept-output))))
```
3. Simply press return in `julia repl`
4. inspect `(car inf-julia-kept-output)`, i.e. evaluate it. The value is (`^M` has become newlines here):
```
"^[[?2004h
^[[0Kjulia> 
^[[7C
^[[7C"
```
This is werid, I would like to know, what is the name for this behaviour in julia, therefore, can this be configured to not output these control sequence. 

See https://github.com/JuliaEditorSupport/julia-emacs/issues/144 for some demonstration on this behaviour in `emacs comint`.

https://github.com/JuliaLang/julia/issues/29632 is relevant.

**Comment by KristofferC** [comment]
Ref https://discourse.julialang.org/t/julia-output-without-escape-sequences/65515

**Comment by Inc0n** [comment]
I see, so `TERM=dumb` is the solution.... 
Now I have used `(setenv "TERM" "dumb")`, `process-environment` these different means to set TERM=dumb, but in julia TERM is `vt50`.
So it must be something to do in Emacs then.

**Comment by Inc0n** [comment]
It was indeed an emacs problem, but thanks @KristofferC for the pointer and the help! 

The culprit is comint-terminfo-terminal, see my comment here for a bit more information: https://github.com/JuliaEditorSupport/julia-emacs/issues/144#issuecomment-1343722278
