### ISSUE TITLE
Julia Docs for Dates github points to wrong location, returing 404 error

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaLang/julia#47879]
Julia Docs for Dates github https://docs.julialang.org/en/v1/stdlib/Dates/ points to wrong location https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.8/Dates/docs/src/index.md... I believe the correct location should be https://github.com/JuliaLang/julia/blob/master/stdlib/Dates/docs/src/index.md

**Comment by brenhinkeller** [comment]
Can confirm https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.8/Dates/docs/src/index.md is a broken link. Where on the Dates page did you find that link?

**Comment by alex-s-gardner** [comment]
![Screen Shot 2022-12-19 at 9 54 27 AM](https://user-images.githubusercontent.com/32276930/208489797-e6cc23fa-46b8-4d1b-893d-3c1cbb8db4fe.jpg)

**Comment by brenhinkeller** [comment]
Ah gotcha, yeap looks broken to me too

**Comment by Kaushik-Iyer** [comment]
Is this issue still open?

**Comment by inkydragon** [comment]
- ✔ v1.6 https://github.com/JuliaLang/julia/blob/master/stdlib/Base64/docs/src/index.md
- ✔ v1.7 https://github.com/JuliaLang/julia/blob/master/stdlib/Base64/docs/src/index.md
- ❌ v1.8 https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.8/Base64/docs/src/index.md
- ❌ v1.10 https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.10/Base64/docs/src/index.md
