### ISSUE TITLE
BitArray initializing randomly

### ISSUE THREAD

**Issue by mlinegar** [JuliaLang/julia#47883]
This may be expected behavior, but I haven't found any documentation of it if so. Also haven't seen any discussion on Github or Discourse. 

When running `BitArray`, there seem to be ones randomly inserted. For example, running `sum(BitArray(undef, (10, 10)))` multiple times gives many different results. I've tried this on two different machines and versions (macOS: 1.8.2, linux: 1.7.2), one where I installed julia with `brew`, the other on a server (I'm not the administrator so I'm not sure how it was installed). 

Info for local instance: 

```
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin20.6.0)
  CPU: 8 × Apple M2
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

julia> sum(BitArray(undef, (10, 10)))
15

julia> sum(BitArray(undef, (10, 10)))
1

julia> sum(BitArray(undef, (10, 10)))
13

julia> sum(BitArray(undef, (10, 10)))
13
```

Info for server instance: 

```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, broadwell)

julia> 

julia> sum(BitArray(undef, (10, 10)))
1

julia> sum(BitArray(undef, (10, 10)))
23

julia> sum(BitArray(undef, (10, 10)))
23

julia> sum(BitArray(undef, (10, 10)))
23

julia> sum(BitArray(undef, (10, 10)))
23

julia> sum(BitArray(undef, (10, 10)))
26

julia> sum(BitArray(undef, (10, 10)))
1

julia> sum(BitArray(undef, (10, 10)))
1
```

**Comment by DilumAluthge** [comment]
This is the expected behavior when you use `undef`.

If you want all zeros, you can use e.g. `falses(10, 10)`, which will return a `BitArray` of all zeros.

**Comment by mlinegar** [comment]
@DilumAluthge understood, thanks for the quick response. It might be helpful to note this in the help file for `BitArray`, which made me think this was unexpected behavior. The following is from the help file:

```
 julia> BitArray(undef, 2, 2)
  2×2 BitMatrix:
   0  0
   0  0
  
  julia> BitArray(undef, (3, 1))
  3×1 BitMatrix:
   0
   0
   0
```
