### ISSUE TITLE
Argument destructuring with Named Tuple

### ISSUE THREAD

**Issue by NeilW** [JuliaLang/julia#47905]
julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 3 × Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 3 virtual cores

According to the documentation argument destructuring is the same as adding the assignment

```
(a, b, c) = argument
```

However when the argument is a NamedTuple rather than a Tuple it still uses positional destructuring rather than property destructuring - contrary to the equivalent assignment statement. 

```
julia> journal((a, b, c)) = (a=a, b=b, c=c)
journal (generic function with 1 method)

julia> journal((a=1, c=3, b=2))
(a = 1, b = 3, c = 2)

julia> (a, b, c) = (a=1, c=3, b=2)
(a = 1, c = 3, b = 2)
```

If this is as expected then perhaps the 'inserted assignment' should be documented as

```
(a, b, c) = Tuple(argument)
```

**Comment by vtjnash** [comment]
you possibly meant `(; a, b, c) = argument`, since otherwise NamedTuple and Tuple are the same
