### ISSUE TITLE
Questions on buidling Julia from source

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#47918]
Hi,

I have posted these questions on discourse but thought I would post them here as maybe someone else would be able to help.

1/ Is there a way to build a light version of Julia, i.e. excluding some components like the documentation or the REPL (I only have these in mind but can be others)? This is for example to test a new feature that would be added, and reduce time test it before makingba PR to Julia.

2/ Now more on the "other side of the spectrum", when building Julia from source, is there a way to include libraries like let's say DataFrames, CSV or HTTP, in order to reduce compilation and TTFX?

If it is not too hard to implement these features and if someone is willing to give me some guidance, I would be happy to do it.

Thank you
Kind regards

Link to discourse: https://discourse.julialang.org/t/building-julia-from-source/91747

**Comment by vchuravy** [comment]
Discourse is the right platform for these questions

**Comment by gitboy16** [comment]
Discourse does not seem to be the right platform to get a proper answer or help. I believe these questions could help some people understand how Julia is built. Especially the ones that would like to contribute like me but do not understand how it is built. From the provided build documentation, it is not explained how the various part of Julia are built from the ground up. Sure there is the make file but it is not like it is documented to understand what is going on. I would be happy to document this part of the process if someone is willing to help or guide me.
Of course, all this is assuming that the core developers are willing to share their knowledge and attract more contributions, if it is not the case, please ignore my request. Thank you.
