### ISSUE TITLE
When pasting multiple lines including `using` of new packages, install prompt clobbered

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#47944]
```
julia> using DataFrames, Plots, Statistics, RDatasets
 │ Package RDatasets not found, but a package named RDatasets is available from a registry.
 │ Install package?
 │   (@v1.8) pkg> add RDatasets
 └ (y/n/o) [y]: 10Plots.mm,
  aspect_ratio=:equal,
Selection not recognized
ERROR: ArgumentError: Package RDatasets not found in current path.
```

When pasting a large block of code starting with `using`s that you don't have installed, the prompt for action gets clobbered by the subsequent paste input.

Before the prompt existed, the `using` line would fail, but the remaining pasted lines would still go to the Julia prompt and execute up until the missing package is hit. Now it breaks.

In my ideal world, a REPL session would be a temporary environment by default and so it could just install these packages without intervention.

In my second-best ideal world, the paste operation would be interrupted so that the prompt could be answered before resuming.

In my third-best ideal world, the unrecognized input to the prompt would be passed through intact to the REPL, retaining the behavior prior to the existence of the prompt.

**Comment by IanButterworth** [comment]
This appears to be fixed on master

Pasting
```
using CSV
x = 1
@show x
```

1.8
```
julia> using CSV
using CSV
x = 1
@show x
 │ Package CSV not found, but a package named CSV is available from a registry. 
 │ Install package?
 │   (@v1.8) pkg> add CSV 
 └ (y/n/o) [y]: Selection not recognized
ERROR: ArgumentError: Package CSV not found in current path.
- Run `import Pkg; Pkg.add("CSV")` to install the CSV package.
Stacktrace:
 [1] macro expansion
   @ ./loading.jl:1163 [inlined]
 [2] macro expansion
   @ ./lock.jl:223 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144

julia> x = 1
1

julia> @show x
x = 1
1

julia> x = 1
1

julia> @show x
x = 1
1
```

master (where the prompt waited for me to type `y`)
```
julia> using CSV
 │ Package CSV not found, but a package named CSV is available from a registry. 
 │ Install package?
 │   (@v1.10) pkg> add CSV 
 └ (y/n/o) [y]: y
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.10/Project.toml`
  [336ed68f] + CSV v0.10.8
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [336ed68f] + CSV v0.10.8
  [944b1d66] + CodecZlib v0.7.0
  [48062228] + FilePathsBase v0.9.20
  [842dd82b] + InlineStrings v1.3.2
  [69de0a69] + Parsers v2.5.2
  [2dfb63ee] + PooledArrays v1.4.2
  [91c51154] + SentinelArrays v1.3.16
  [66db9d55] + SnoopPrecompile v1.0.1
  [3bb67fe8] + TranscodingStreams v0.9.10
  [ea10d353] + WeakRefStrings v1.4.2
  [76eceee3] + WorkerUtilities v1.6.1
Precompiling environment...
  ✓ Revise
  107 dependencies successfully precompiled in 83 seconds. 4 already precompiled.
  1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version

julia> x = 1
1

julia> @show x
x = 1
1
```

I seem to recall recent a PR by Jeff that did something with prompt pasting, but I might be wrong as I can't find it.

**Comment by BioTurboNick** [comment]
Hmm I wonder if it's a Windows issue. On `1.10.0-DEV.164` nightly I'm still seeing a failure here.

**Comment by vtjnash** [comment]
The Windows platform does not have this feature, while most other platforms do

**Comment by IanButterworth** [comment]
I'm wondering if we can pause that emulated sequence of keypresses until the install prompt has exited?

**Comment by vtjnash** [comment]
We can't. Unlike most platforms, Windows doesn't have that feature.
