### ISSUE TITLE
Re-inference where there shouldn't be

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#47960]
I'm looking into why some of the savings from native-code precompilation (#47184) are not as good as I think they should be. I have evidence that some things are being re-inferred, and I'm unclear on why. 

First, the easiest issue to analyze is probably #48048, so I would start there.

To reproduce this more complicated example, create an environment where you:

- ~build #47184 and run this demo with it~ use `master`
- `dev` [PkgCacheInspector](https://github.com/timholy/PkgCacheInspector.jl) (make sure you're on the very latest)
- `dev` the `teh/snoop_pc` branch on SnoopCompile, and also `dev` SnoopPrecompile (which is in the same repo). This branch adds some additional "precompilation effort"---it tries really, really hard to make sure everything gets precompiled---and also adds some debugging utilities. In particular, it adds `@time_precompiled` to enable copy/pasting the `@precompile_setup`/`@precompile_all_calls` workload and time (or make other measurements of) just the portion inside `@precompile_all_calls`. (It also breaks Plots, among other packages, because of https://github.com/JuliaLang/julia/issues/47902#issuecomment-1353030342, but for our debugging purposes here I think that's temporarily OK.)
- `add MethodAnalysis`
- `add` DataFrames. Note that DataFrames has [this precompile workload](https://github.com/JuliaData/DataFrames.jl/blob/b240458aca1681e74a94e979a0141b2b16f1a3e0/src/other/precompile.jl), and we'll use the exact same reproducer workload.

Now, here's a reproducer script. In brief, it:
- loads the cache file
- collects all MethodInstances that are stored in the cache
- verifies that one particular "test" MethodInstance is indeed stored in the cache, and that its corresponding CodeInstance is valid
- re-runs the precompilation workload of DataFrames, while "snooping" on any new inferences
- checks that the "test" MethodInstance is indeed among the new inferences 😢 . To be clear, we don't want that.

```julia
using PkgCacheInspector, MethodAnalysis, UUIDs

# It's necessary to have this compiled, and useful to see some of the debugging output from SnoopPrecompile
# But only need to do this once (can comment out)
Base.compilecache(Base.PkgId(UUID(0xa93c6f00e57d5684b7b6d8193f3e46c0), "DataFrames"))

cf = info_cachefile("DataFrames")
# Make visible the names that will be needed to run the workload
# Note this should *not* reload the cache file; if you install Debugger.jl, you can verify this
# with `@enter Base.require(Base.PkgId(UUID(0xa93c6f00e57d5684b7b6d8193f3e46c0), "DataFrames"))`
using DataFrames
using DataFrames.PooledArrays: PooledArrays, PooledArray
using Statistics

# Collect all the MethodInstances stored in the cache file
mis = methodinstances(cf)

# Here's a "non-owned" MethodInstance that should be inferred via the `thunk` created
# by SnoopPrecompile
mi = methodinstance(Base.vect, (Int, Int, Int, Int, Int))
# If you don't like that one, here's another one:
# mi = methodinstance(Tuple{typeof(Broadcast.materialize), Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(string), Tuple{SubArray{Symbol, 1, Vector{Symbol}, Tuple{UnitRange{Int64}}, true}}}})
# Check that it was cached
@assert mi ∈ mis

## Now we're going to re-run the workload, and we'll discover that `mi` gets inferred *again*

using SnoopPrecompile, SnoopCompileCore
# Check that the CodeInstance is still valid
@assert mi.cache.max_world == typemax(UInt)

# Monitor the fresh inferences when running the precompile workload
tinf = @time_precompiled @snoopi_deep begin
    SnoopPrecompile.@precompile_all_calls begin
        df = DataFrame(a=[2, 5, 3, 1, 0], b=["a", "b", "c", "a", "b"], c=1:5,
                       p=PooledArray(["a", "b", "c", "a", "b"]),
                       q=[true, false, true, false, true],
                       f=Float64[2, 5, 3, 1, 0])
        describe(df)
        names(df[1, 1:2])
        sort(df, :a)
        combine(df, :c, [:c :f] .=> [sum, mean, std], :c => :d, [:a, :c] => cor)
        transform(df, :c, [:c :f] .=> [sum, mean, std], :c => :d, [:a, :c] => cor)
        groupby(df, :a)
        groupby(df, :q)
        groupby(df, :p)
        gdf = groupby(df, :b)
        combine(gdf, :c, [:c :f] .=> [sum, mean, std], :c => :d, [:a, :c] => cor)
        transform(gdf, :c, [:c :f] .=> [sum, mean, std], :c => :d, [:a, :c] => cor)
        innerjoin(df, df, on=:a, makeunique=true)
        innerjoin(df, df, on=:b, makeunique=true)
        innerjoin(df, df, on=:c, makeunique=true)
        outerjoin(df, df, on=:a, makeunique=true)
        outerjoin(df, df, on=:b, makeunique=true)
        outerjoin(df, df, on=:c, makeunique=true)
        semijoin(df, df, on=:a)
        semijoin(df, df, on=:b)
        semijoin(df, df, on=:c)
        leftjoin!(df, DataFrame(a=[2, 5, 3, 1, 0]), on=:a)
        leftjoin!(df, DataFrame(b=["a", "b", "c", "d", "e"]), on=:b)
        leftjoin!(df, DataFrame(c=1:5), on=:c)
        reduce(vcat, [df, df])
        show(IOBuffer(), df)
        subset(df, :q)
        @view df[1:3, :]
        @view df[:, 1:2]
        transform!(df, :c, [:c :f] .=> [sum, mean, std], :c => :d, [:a, :c] => cor)
    end
end;

using SnoopCompile
# Get the mis that were newly-inferred by `thunk`
misnew = Core.MethodInstance.(SnoopCompile.flatten(tinf))
# Why did this appear in the newly-inferred list?
@assert mi ∈ misnew
```

I've tried basically everything I can think of, and looked at quite a few different MethodInstances (I suggested an alternate one above, but any child of `tinf.children[1].children` should do). I've been particularly concerned about constant-propagation and tried to turn it off on the `thunk`, but nothing I've done has made any difference.

**Comment by timholy** [comment]
https://github.com/JuliaLang/julia/pull/47184#discussion_r1055878262 is another culprit. Hopefully much easier to fix. I don't think that would trigger re-inference (?) but worth being aware of just in case it's the culprit of this issue, too.

**Comment by vtjnash** [comment]
Tried to run that script, but got a lot of errors, so gave up. We made a lot of changes to this in the past year
