### ISSUE TITLE
Line by line code coverage is missing

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#47971]
I cannot view the line by line coverage report online, either through codecov or coveralls:
https://app.codecov.io/gh/julialang/julia/blob/master/sort.jl
https://app.codecov.io/gh/julialang/julia/blob/master/compiler/abstractinterpretation.jl
https://coveralls.io/builds/55396332/source?filename=sort.jl
https://coveralls.io/builds/55396332/source?filename=compiler%2Fabstractinterpretation.jl

Packages work fine, though
https://app.codecov.io/gh/julialang/Pkg.jl/blob/master/src/API.jl

Cross posted from [discourse](https://discourse.julialang.org/t/code-coverage-in-base/76809/2) because I think this is a configuration issue.

**Comment by vtjnash** [comment]
https://github.com/JuliaCI/julia-buildkite/issues/188
