### ISSUE TITLE
What to do about new functions `get_extension` and `retry_load_extensions`?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#47982]
The new extension system comes with two functions that have docstrings but are not in the manual to allow them to be bike shedded. These are:

- `get_extension(m::Module, extension_name::Symbol)`. This can be used to retrieve a given extension of a package. In my view, this should mostly be used as a debugging tool and should not be something that is part of the public API of a package. But it is pretty useful if you want to examine stuff in the extension when you are developing it. There might also be some uses for a package to get that module during runtime to perhaps inspect some variables in it.
- `retry_load_extensions()`. If an extension fails to load (due to e.g. a syntax error), it will not try to be automatically loaded again. But it can be annoying having to restart the whole Julia session just to get the extension to load after it has been fixed. With `retry_load_extensions()` all extensions that have failed to load will be attempted to be loaded again. 

The bike shedding to be done about the above functions are the standard:

- Name
- Function arguments
- Export?

**Comment by gbaraldi** [comment]
Triage thinks the names are fine, and that the functions shouldn't be exported. If we want to add more granularity to this i.e reload a single module, we can do that later :).

**Comment by KristofferC** [comment]
🙇
