### ISSUE TITLE
`sizeof` without padding

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#47985]
the documentation for `sizeof` says:
```julia
  sizeof(T::DataType)
  sizeof(obj)


  Size, in bytes, of the canonical binary representation of the given
  DataType T,


julia> struct blah2
           fCheckSum::Int32 #4
           fVersion::UInt32 #4
           fSize::UInt32 #4
           fSeekHeader::UInt64 #8
           fNBytesHeader::UInt32 #4
       end

# 16+8 = 24
julia> sizeof(blah2)
32
```

and turns out "canonical binary representation" doesn't mean "as defined by source code without padding", it actually means "however the language decided to pad it". 

1. I think this is intended
2. is there a way to get `sizeof` a bit-struct without padding?

**Comment by oscardssmith** [comment]
Why do you care about the size without padding?

**Comment by Moelf** [comment]
Because I'm reading a spec that obviously can't tell me the size after padded: https://github.com/root-project/root/blob/master/tree/ntuple/v7/doc/specifications.md

After I make the corresponding struct, and during the dynamic and recursive parsing and `getfield` the struct by name, I need to figure out how many bytes I need to read from the source (on-disk file, through internet etc.)

**Comment by giordano** [comment]
> is there a way to get `sizeof` a bit-struct without padding?

```julia
julia> struct blah2
           fCheckSum::Int32 #4
           fVersion::UInt32 #4
           fSize::UInt32 #4
           fSeekHeader::UInt64 #8
           fNBytesHeader::UInt32 #4
       end

julia> sum(sizeof.(fieldtypes(blah2)))
24
```
?

**Comment by BioTurboNick** [comment]
#47116 has a `packedsize` function that probably would do this. Not sure on the ETA on that, though.

**Comment by giordano** [comment]
Contrary to that `packedsize`, the `sizeof_without_padding` function I suggested above works with any versions of julia v1.1+, it doesn't fiddle with internals (it's just a combination of `sizeof` and `fieldtypes`, so it should keep working for some time), it doesn't have to hack `@assume_effects` and it just returns a constant:
```julia
julia> Base.infer_effects(sizeof_without_padding, (Type{blah3},))
(+c,+e,+n,+t,+s,+m)

julia> code_llvm(sizeof_without_padding, (Type{blah3},))
;  @ REPL[52]:1 within `sizeof_without_padding`
define i64 @julia_sizeof_without_padding_1465() #0 {
top:
  %0 = call {}*** inttoptr (i64 6492074236 to {}*** (i64)*)(i64 262) #1
  %ptls_field3 = getelementptr inbounds {}**, {}*** %0, i64 2
  %1 = bitcast {}*** %ptls_field3 to i64***
  %ptls_load45 = load i64**, i64*** %1, align 8
  fence syncscope("singlethread") seq_cst
  %2 = getelementptr inbounds i64*, i64** %ptls_load45, i64 2
  %safepoint = load i64*, i64** %2, align 8
  %3 = load volatile i64, i64* %safepoint, align 8
  fence syncscope("singlethread") seq_cst
  ret i64 26
}
```
If you need it, you can use it straight away 🙂

**Comment by Moelf** [comment]
Since it can be solved by implementing live @giordano showed, closing issue now.
