### ISSUE TITLE
Overview of Julia internals for new developers?

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#4800]
Is there any introductory documentation for developers who want to experiment with modifying the internals of Julia, particularly experimenting with its use of LLVM?  I've been poking around and collecting notes on basic use of gdb on Julia, and feel like I'm retreading ground many others must have covered.  I'm looking for a high-level view, but with specific names of functions attached, and perhaps "10 popular places to set breakpoints".

A specific question I have not figured out yet: from gdb, how can I force rejitting of a function, so I can repeatedly follow what LLVM is doing with it?

**Comment by JeffBezanson** [comment]
c1e7ed8d9cf8b978ad3f565d2b0c1f5fbcab096a also helps here.

**Comment by jakebolewski** [comment]
This can always be better, but there has been significant improvements on this issue and now a dedicated section in the manual.
