### ISSUE TITLE
Options for separate optimization and inference accuracy level during precompilation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#48021]
Precompilation has evolved a ton in Julia in recent years, but the controls for it have not. It would be nice if there was a way for example to have different optimization levels during precompilation vs standard compilation, in a way that packages can control at the module level, since a lot of the times the -O1 choice is for latency that is not seen if the package is using a precompiled call. Additionally, this would allow for higher optimization levels that really optimize, doing things like more SLP vectorization or something, if one is okay with the precompilation cost.

This could also allow for more inference controls, for example, enabling https://github.com/JuliaLang/julia/issues/36454 during precompilation if one is okay with the higher latency (to decrease invalidations).

**Comment by KristofferC** [comment]
As a note, for now, I think the stuff in pkgimages are ignoring module level optimization level and just compiles it with the same optimization level as Julia is started with. @timholy or @vchuravy can probably confirm.

**Comment by vchuravy** [comment]
It's a bit tricky. If you start Julia with `-O3` it will be propagated to the pkgimage. If you then start Julia with `-O0` we will load the pkgimage compiled under `O3`. If on the otherhand you compile at `O0` and then load at `O3` we will reject that pkgimage and generate a new one.
