### ISSUE TITLE
Invalid private key path causing windows CI failure

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#48046]
Windows CI failed after 1 second with:
"Secret private key path 'C:\secrets/agent.key' is not a valid private RSA key!"
[[link](https://buildkite.com/julialang/julia-master/builds/19619)]

**Comment by vchuravy** [comment]
I took the agent out of rotation. Probably needs @staticfloat to fix when he is back from vacation.

**Comment by DilumAluthge** [comment]
This isn't actually an issue with a single agent, but an overall problem with our Windows setup.

After each job, we reboot the Windows VM

This error message means that the Buildkite agent somehow decided to start a new job before we had the chance to reboot the Windows VM. This is never supposed to happen.

https://github.com/JuliaCI/sandboxed-buildkite-agent/issues/42

**Comment by vchuravy** [comment]
It has been reproducible the same agent. So something is up with that one in particular.
