### ISSUE TITLE
Failing boundscheck tests aren't running

### ISSUE THREAD

**Issue by shlemas** [JuliaLang/julia#48099]
[boundscheck.jl](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck.jl) spawns Julia processes to execute [boundscheck_exec.jl](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck_exec.jl) with different values for the `--check-bounds` flag.

For the `--check-bounds=auto` case, it omits the `--check-bounds` flag since it's the default value:
https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/boundscheck.jl#L5

The problem is the command returned by `Base.julia_cmd()` includes flags that were used to spawn the current Julia process. Since all the test processes are [run with `--check-bounds=yes`](https://github.com/JuliaLang/julia/blob/79e29e3cb9ef34f7ab613657c0f480d81b1402b7/test/Makefile#L26), that means this process is actually running with `--check-bounds=yes` instead of `auto`.

It's easy to fix by explicitly adding `--check-bounds=auto` to the command. Doing that uncovers some failing tests:
```
Test Failed at test/boundscheck_exec.jl:35
  Expression: A1_wrap() == 0
   Evaluated: 1 == 0
```

There are a few other failures in there too. Don't know yet what the proper fixes are.

Original thread from another issue: https://github.com/JuliaLang/julia/pull/48003#discussion_r1060247756

**Comment by gbaraldi** [comment]
Could you open a PR fixing the tests themselves? So that more people can diagnose the underlying failures :)

**Comment by shlemas** [comment]
Opened #48100

**Comment by KristofferC** [comment]
Good find!

**Comment by shlemas** [comment]
It looks like something either in 1.8.0-beta1 (I'm unable to run) or 1.8.0-beta2 broke these tests. They run fine on 1.7.3.

**Comment by shlemas** [comment]
This is a misbehaving function from one of the failing tests. It's expected to return 0 but always returns 1:
```julia
function A1_inbounds()
    r = 0
    @inbounds begin
        @boundscheck r += 1
    end
    return r
end
```

Adding something like a `println` to the `@inbounds begin` block fixes it for whatever reason:
```julia
function A1_inbounds()
    r = 0
    @inbounds begin
        println("hello")
        @boundscheck r += 1
    end
    return r
end
```

Now `A1_inbounds()` returns 0.

Seems like one of these commits would be the cause:
```
gitk --no-merges v1.8.0-beta1 ^v1.7.3 -- base
```

I'm out of my depth at this point though especially since I can't bisect.

I guess worst case scenario is some bounds checks aren't actually being skipped out there in the world.

**Comment by vtjnash** [comment]
It is expected to always return 1 (unless run with `check-bounds=no`), and I see it always return 1, so I don't see the issue there

**Comment by vtjnash** [comment]
This is an effect system bug (@aviatesk), since the `@boundscheck` is failing to taint the consistency, so we fail to realize that that Expr's value is not a constant, and concrete eval is forbidden here because of the inbounds annotation in the context:
```julia
A1_wrap() @ Main REPL[1]:1
Variables
  #self#::Core.Const(A1_wrap)
  val::Union{}

∘ ─ %0 = invoke A1_wrap()::Core.Const(1) (+c,+e,+n,+t,+s,+m)
    @ REPL[1]:1 within `A1_wrap`
1 ─      Core.NewvarNode(:(val))::Any
│        nothing::Core.Const(nothing)
│   %3 = Main.A1_inbounds()::Core.Const(1) (+c,+e,+n,+t,+s,+m)
└──      return %3
2 ─      Core.Const(nothing)::Union{}
Select a call to descend into or ↩ to ascend. [q]uit. [b]ookmark.
 • %3 = < concrete eval > A1_inbounds()::Core.Const(1) (+c,+e,+n,+t,+s,+m)
```

**Comment by shlemas** [comment]
My bad, I mixed a couple things up in my last comment and updated it.
