### ISSUE TITLE
Test starts error in GFlops.jl between julia 1.9.0-alpha1 and 1.9.0-beta2

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#48094]
PkgEval log https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/05c8182_vs_258fa32/GFlops.primary.log.

 The difference is

```
julia> cnt = @count_ops fma(1.0, 2.0, 3.0)
Flop Counter: 24 flop
┌─────┬─────────┐
│     │ Float64 │
├─────┼─────────┤
│ add │       6 │
│ sub │       9 │
│ mul │       6 │
│ abs │       3 │
└─────┴─────────┘
```

vs

```
julia> cnt = @count_ops fma(1.0, 2.0, 3.0)
Flop Counter: 2 flop
┌─────┬─────────┐
│     │ Float64 │
├─────┼─────────┤
│ fma │       1 │
└─────┴─────────┘
```

Maybe `Core.Intrinsics.have_fma(Float64)` returns false now for the Cassette overdub pass GFlops uses?

https://github.com/JuliaLang/julia/blob/87b1f2f5d76a48f0b13d342c1201cfaed4cec603/base/floatfuncs.jl#L426

cc @ffevotte

**Comment by gbaraldi** [comment]
I can't reproduce on x86 linux? What platform was this?

**Comment by gbaraldi** [comment]
The pkgeval failure is one related to `rem`, which makes sense since we switched to a native implementation. https://github.com/triscale-innov/GFlops.jl/issues/42. The fma failure I haven't been able to reproduce just yet.

**Comment by KristofferC** [comment]
Probably something with FMA on mac. I think it can be closed.
