### ISSUE TITLE
Visual REPL behaviour in pkg mode with long environment name

### ISSUE THREAD

**Issue by albheim** [JuliaLang/julia#48115]
So I sometimes create folder names that are ridiculously long, containing the description of main parameters used to generate data for the contained experiment. I happened to want to analyze some data and wanted to just create a quick environment in that folder, and add some packages, and ran into some visual behaviour of the REPL that seemed like it could be made nicer. 

This can also be achieved by just reducing the width of the terminal window to small enough that you get a linebreak in the mode part of the prompt, long folder name is not the important part, but it is where it might actually more likely happen to people.

Before writing (with "normal" terminal, as well as how it looks if I resize the terminal to "wide enough")
```julia
(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter
minal_of_normalish_size) pkg> 

(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_terminal_of_normalish_size) pkg>
```

Writing `a`
```julia
(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter
minal_of_normalish_size) pkg>                                                          a

(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_terminal_of_normalish_size) pkg>                                                          a
```

Writing `d`
```julia
(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter
minal_of_normalish_size) pkg>                                                          a
d

(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_terminal_of_normalish_size) pkg>                                                          ad
```

Writing another `d`, now it starts duplicating the part before the first wrap
```julia
(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter
(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter
minal_of_normalish_size) pkg>                                                          a
dd

(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_ter(this_is_a_long_folder_name_with_a_lot_of_stuff_so_it_will_generate_a_linebreak_on_a_terminal_of_normalish_size) pkg>                                                          add
```

It seems like it is something weird with where the cursor ends up, adding a bunch of white-space between the prompt and the input, and it also seems to redraw the full line after the second wrap without erasing the part before the first wrap. 
It only seems to happen in the pkg mode, with the other standard modes it behaved more or less like I would expect (characters were printed without some whitespace, and no spamming of the part before the first wrap).

Though it all works when running the actual command in the end, so no real problem, just a bit annoying visually.

**Comment by KristofferC** [comment]
We could detect when the prompt is excessively long and truncate it `this_is_a_long_folder... pkg>

**Comment by ArunSanganal** [comment]
> We could detect when the prompt is excessively long and truncate it `this_is_a_long_folder... pkg> `
Can you direct me to exactly where should I modify this in REPL.jl?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/blob/5ae866151e0cfd0536d0bfbb66e7f14ea026bd31/src/REPLMode/REPLMode.jl#L527

`prefix` could be limited in length there.
