### ISSUE TITLE
Remove Period constructors from Date/DateTime

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#48181]
```jl
julia> today()
2023-01-08
julia> Day(today())
8 days
```
This constructor takes the day component out of the date, and turns it into a duration in `Day`s. I think this is silly and shouldn't exist. It's breaking, so I propose removing in 2.0 but deprecating sooner.

Likewise

```jl
julia> Minute(now())
39 minutes
```

If anybody thinks "it's unambiguous, what else could it mean", I'm not sure that's the right question -- it shouldn't really mean anything -- but, if we're stretching anyway, it could mean "minutes from the epoch".

**Comment by andrewjradcliffe** [comment]
The docstrings for `Day`, `Minute`, etc. are unambiguous. The constructors from `Date` and `DateTime` exist as the internal representation of both is `Int64`. How else might one get the unit-ful version? `Day(day(today()))`, `Minute(minute(now()))`? Not only would that be verbose, it makes parameterization of functions with `Day`, `Minute`, etc. fraught as one must now specify a composed function.

> I think this is silly and shouldn't exist.

Subjective judgment is never logical justification.

**Comment by jariji** [comment]
What is the use case for retrieving the "minute part" of a datetime in unitful `Minute`s?
