### ISSUE TITLE
packedQ from svd?

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#4818]
qrfact provides a QRPackedQ 
  which I love because it muliplies matrices with m rows or n rows

svdfact should do the same (and I don't think it is)

Maybe a better name is PackedQ rather than QRPackedQ
as other routines can pack a Q

**Comment by ViralBShah** [comment]
Please reopen if necessary. Looks like LAPACK doesn't give us a packed Q from SVD.

I do like the idea of efficient `*` with `U` and `V`.
