### ISSUE TITLE
Seems like a bug. Where is the `to` defined?

### ISSUE THREAD

**Issue by lgeissbauer-btig** [JuliaLang/julia#48180]
https://github.com/JuliaLang/julia/blob/708d1bdb36e962b2eb8b2040777f5dea272c40c7/base/iobuffer.jl#L206

Got it from JET.jl
```│┌ @ io.jl:1000 nr = readbytes!(s, b, nb)
││┌ @ stream.jl:889 readbytes!(s, a, Base.Int(nb))
│││┌ @ stream.jl:911 nread = readbytes!(sbuf, a, nb)
││││┌ @ iobuffer.jl:463 Base.read_sub(io, b, 1, nr)
│││││┌ @ iobuffer.jl:206 read(Base.to, T)
││││││ `Base.to` is not defined
│││││└───────────────────
```

**Comment by vchuravy** [comment]
Do you have a test for this? But yeah this probably should have been `from`. `git praise` shows @vtjnash circa 2015

**Comment by Seelengrab** [comment]
Fortunately, the only use of that internal function in Base hardcodes `UInt8`:

https://github.com/JuliaLang/julia/blob/708d1bdb36e962b2eb8b2040777f5dea272c40c7/base/iobuffer.jl#L458-L465

Should probably still be fixed, at least to remove that noise in JET and safeguard against future failure.

**Comment by lgeissbauer-btig** [comment]
@vchuravy What do you mean by test?
The following is the calling code
```
function read_pipe(pipe::Base.PipeEndpoint)::String
    l = read(pipe, Int32)
    bytes = read(pipe, l) 
    return String(bytes)
end
```
