### ISSUE TITLE
Define tanPi (and more required from latest IEEE), even maybe only for BigFloat

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#48226]
tanPi is available in latest MPFR, so rather trivial to add, if wanted for only BigFloat:

https://github.com/JuliaLang/julia/pull/48165#issuecomment-1374927783

See there about possible solution for e.g. Float64.

**Comment by bobcassels** [comment]
This issue can be closed. At least the `tanpi` part. I did not (and don't plan to) implement "more required from latest IEEE".

**Comment by bobcassels** [comment]
I see #32877, which talks about the other IEEE functions. So you should close this issue.
