### ISSUE TITLE
`@inbounds` in dead code taints consistency

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#48243]
```
function foo()
      false && @inbounds (1,2,3)[1]
      return 1
end
```

```
julia> Base.infer_effects(foo)
(!c,+e,+n,+t,+s,+m)
```

This likely regressed in #48158

**Comment by Keno** [comment]
On further thought, I'm not sure `:inbounds` actually needs to taint consistency at all. The thing that taints consistency is `:boundscheck`. If we didn't have `--check-bounds=yes` it would make a difference, but given that we have all the options, I'm not sure it does.

**Comment by gbaraldi** [comment]
In fact `:inbounds` might make it more consistent, since it won't give a bounds error ever, it will either segfault or return garbage, but indexing out of bounds is undefined anyway.

**Comment by Keno** [comment]
Consistency needs to be true for all argument values, since the compiler is allowed to invent them.

**Comment by gbaraldi** [comment]
But if we access outside of bounds and into potentially undefined memory, how can the compiler know what to put there?

**Comment by Keno** [comment]
The compiler doesn't, we need to prevent trying to concrete eval something that might invoke undefined behavior or in other words, undefined behavior taints :consistent.

**Comment by oscardssmith** [comment]
Could we make it so that indexing out of bounds at compile time semantically returned zero?

**Comment by gbaraldi** [comment]
If we knew at compile time that were indexing out of bounds we probably want to throw an error at compile time no?

**Comment by Keno** [comment]
You'd have to compile a separate copy of all functions, which is unlikely to be worth it. Also in general, you can't really do much with the results, because it's no longer a faithful model of the function being analyzed.
