### ISSUE TITLE
`using` should trigger Pkg's parallel precompilation

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#48259]
I think Base should add a hook so that when Pkg is loaded, `using PkgX` triggers parallel precompilation instead of serial. It's not intuitive for that there's different precompilation modes with hugely different runtimes, and I think it's a common footgun to accidentally use the non-parallel version.

**Comment by Roger-luo** [comment]
Or can we have this by default, and have a flag to turn it off?

**Comment by IanButterworth** [comment]
I think to do this Pkg.precompile needs to start showing the precompile warnings that are currently only shown in code load precompilation. Proposal here: https://github.com/JuliaLang/Pkg.jl/pull/3319
