### ISSUE TITLE
Double-dash argument gets lost

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#48269]
MWE:

```julia
❯ julia -e '@show ARGS' foo - bar
ARGS = ["foo", "-", "bar"]

❯ julia -e '@show ARGS' foo -- bar
ARGS = ["foo", "bar"]

❯ julia -e '@show ARGS' foo --- bar
ARGS = ["foo", "---", "bar"]
```

I was trying to write a Julia script that launches another process, for which the `--` argument is convenient to separate arguments to the parent from argument to the latter.

FWIW, this doesn't seem to be caused by my shell:

```
julia> run(`/home/tim/Julia/depot/juliaup/julia-1.8.5+0.x64.linux.gnu/bin/julia -e '@show ARGS' foo -- bar`)
ARGS = ["foo", "bar"]
```

**Comment by KristofferC** [comment]
I think this is fixed on 1.9.

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/45335

**Comment by maleadt** [comment]
Ah, GitHub search failed me. Thanks!
