### ISSUE TITLE
Dot product with the adjoint ' operator gives wrong results.

### ISSUE THREAD

**Issue by sadish-d** [JuliaLang/julia#48288]
These give inconsistent/incorrect dot products:
`a=[1,2]; a'a` gives `5` but `[1,2]'[1,2]` gives `2`.
`a=[1,2]; adjoint(a)a` gives `5` but `adjoint([1,2])[1,2]` gives `2`.

These give the correct dot product 5:
`using LinearAlgebra; dot([1,2],[1,2])` and `a=[1,2]; using LinearAlgebra; dot(a,a)` both give `5`.
`a=[1,2]; a \cdot a` and `[1,2] \cdot [1,2]` both give `5`.

This reproduced on my system as well as replit.

My installation from conda-forge. Following are the details:

```Julia Version 1.8.5
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_DEPOT_PATH_BACKUP = 
  JULIA_PROJECT_BACKUP = 
  JULIA_LOAD_PATH_BACKUP = 
  JULIA_DEPOT_PATH = /Users/sadish/opt/miniconda3/envs/0/share/julia:
  JULIA_PROJECT = @0
  JULIA_LOAD_PATH = @:@0:@stdlib
  JULIA_SSL_CA_ROOTS_PATH_BACKUP = 
  JULIA_CONDAPKG_BACKEND_BACKUP = 
  JULIA_CONDAPKG_BACKEND = System
  JULIA_CONDAPKG_EXE_BACKUP = 
  JULIA_CONDAPKG_EXE = /Users/sadish/opt/miniconda3/bin/conda
```

**Comment by oscardssmith** [comment]
I believe this is a parsing bug somehow. I can reproduce this on linux with Julia built from source.
```
[1,2]'*[1,2] == 5
[1,2]'[1,2] == 2
```

**Comment by giordano** [comment]
What bug?  You're indexing the element `(1, 2)` of
```
julia> [1, 2]'
1×2 adjoint(::Vector{Int64}) with eltype Int64:
 1  2
```
which is 2.  See also
```
julia> Meta.@lower [1,2]'[1,2]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = Base.vect(1, 2)
│   %2 = var"'"(%1)
│   %3 = Base.getindex(%2, 1, 2)
└──      return %3
))))
```
I wouldn't really expect `[1,2]'[1,2]` to be a dot product.

**Comment by sadish-d** [comment]
I see. `[1,2]'vec([1,2])` gives me the dot product. For sure going to stay away from implicit multiplication.
