### ISSUE TITLE
Function returns different values dependent on optimization level (in conjuction with StaticArrays)

### ISSUE THREAD

**Issue by skleinbo** [JuliaLang/julia#48285]
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```
and
```
Julia Version 1.9.0-beta2
Commit 7daffeecb8c (2022-12-29 07:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  DYLD_LIBRARY_PATH = /Developer/NVIDIA/CUDA-9.1/lib
  JULIA_EDITOR = code
```

__MWE:__ https://gist.github.com/skleinbo/b25e10ffeef086b88ebb1f1c2c545d5d

Defined is a struct containing four elements of the same type meant to represent an origin and three axes. A function `isvalid` checks if the axes are orthonormal. If the elements are `StaticArrays`, this function yields different results dependent on the compiler optimization level. Below -O2, it yields the expected results, while at -O2 and above some tests fail. Using standard vectors always yields the expected result. The test cases defined in `geometrytests.jl` showcase the behavior.

**Comment by KristofferC** [comment]
The difference is probably if the function uses SIMD or not. You have to opt into auto vectorization precisely because it changes the result.

**Comment by skleinbo** [comment]
Ah, my bad. I should have expect that the following can happen
```
u = normalize(@SVector [1,1,1])
v = (@SVector [1,2,1])
v = normalize(v - dot(u,v)*u)
w = cross(u,v)

dot(u,w), dot(v,w)
(0.0, 0.0)

f(u,v,w) = dot(u,w), dot(v,w)

f(u,v,w)
(1.7796192843178415e-17, 1.1045003975154697e-17)
```
The two calls to `dot` are inlined, loops get fused, operations reordered. Fine. 

But what I have a hard time coming to terms with are the optimizations that go into
```
g(u,v,w) = norm(w)≉ 1.0 || norm(u)≉ 1.0 || dot(u,w)≉ 0.0
h(u,v,w) = norm(w)≉ 1.0 || norm(u)≉ 1.0 || dot(u,w)≉ 0.0 || dot(v,w)≉ 0.0

g(u,v,w)
true
h(u,v,w)
false
```
I should learn to read assembly 😄 

It is of no practical consequence though, because `==0.0` is a bad idea anyway.

Issue closed because it's not a bug. Thanks for your comment!
