### ISSUE TITLE
username() function (analogous to homedir())

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#48302]
As recently commented [on discourse](https://discourse.julialang.org/t/how-to-get-username/93023?u=stevengj), it would be nice to have a `username()` function analogous to `homedir()`, similar to Python's [getpass.getuser](https://docs.python.org/3/library/getpass.html#getpass.getuser).

Just as `homedir()` checks environment variables like `HOME` before calling `getpwuid`, Python's `getpass.getuser` checks several environment variables before interrogating the `passwd` struct.

We can do the same thing in Julia.  An example implementation is [here](https://discourse.julialang.org/t/how-to-get-username/93023/6?u=stevengj).   Note also that we already have `Libc.getpwuid(Libc.getuid(), true).username` to extract the passwd data.

It's not entirely clear to me if Python's sequence of environment variables `("LOGNAME", "USER", "LNAME",  "USERNAME")` is the right choice, or if it's some legacy thing that they implemented in 1993 and can no longer change.  Would be good to investigate this carefully.   Would be good to survey some other modern languages too.  We might also want a flag to tell it to ignore the environment variables.

Since we already basically have this functionality, but it requires low-level knowledge to call correctly, it seems like a good candidate for something to have a better API for in Base.  Marking as "good first issue" since coding-wise it should be easy (most of the work is already done) once we decide whether we want this and precisely what we want.

**Comment by stevengj** [comment]
Relevant links:

* https://stackoverflow.com/questions/47444178/difference-between-os-getlogin-and-os-environ-for-getting-username
* Ruby has [`Etc.getlogin`](https://ruby-doc.org/stdlib-2.5.1/libdoc/etc/rdoc/Etc.html#method-c-getlogin) and [`Etc.getpwuid`](https://ruby-doc.org/stdlib-2.5.1/libdoc/etc/rdoc/Etc.html#method-c-getpwuid)
* Golang has [`user.Current()`](https://pkg.go.dev/os/user#Current)
* Rust has [`whoami::username`](https://docs.rs/whoami/0.2.0/whoami/fn.username.html)
* Environment variables: [`USERNAME` is for Windows, while `USER` is on Unix](https://stackoverflow.com/questions/4432549/whats-the-difference-between-the-user-and-username-environment-variables)?  [`LOGNAME` is allegedly required by POSIX while `USER`](https://lists.ubuntu.com/archives/ubuntu-users/2015-July/281503.html) is not(?), but [one `USER` might be changed by `su` while `LOGNAME` is not?](https://knowledge.broadcom.com/external/article/37575/user-vs-logname-environment-variables.html).  Not sure where `LNAME` comes from.

**Comment by Seelengrab** [comment]
It should be noted that the current username and the location of `homedir` don't necessarily have to match.

**Comment by tp2750** [comment]
Thank you for looking into this @stevengj 

I did a bit of testing on Ubuntu 22.04 and Julia version 1.8.3 to see how the function you propose works in different situations and compare to R and python.

The conclusion is that the function you propose works as expected in the cases I have tested. Not that is is surprising, but now it is documented :smile:

The method was to call the following script in different ways:

```
cat /tmp/username.jl
#!/opt/julia/julia-1.8.3/bin/julia
function username_env()
    for varname in ("LOGNAME", "USER", "LNAME",  "USERNAME")
        username = get(ENV, varname, "")
        @info "$varname: $username"
#        !isempty(username) && return username
    end
end
struct uv_passwd
    username::Cstring
    uid::Clong
    gid::Clong
    shell::Cstring
    homedir::Cstring
end
function username_libc()
    p = Ref{uv_passwd}()
    ret = @ccall uv_os_get_passwd(p::Ref{uv_passwd})::Cint
    Base.uv_error("get_passwd", ret)
    username = unsafe_string(p[].username)
    @ccall uv_os_free_passwd(p::Ref{uv_passwd})::Cvoid
    return username
end
username_env()
@info "libc: $(username_libc())"
@info "homedir: $(homedir())"
```

The script was run as the logged in user (tp) or by shifting user in different ways: using `su user1`, `su - user1`, and by running the script under `sudo -u user1 `.

The result is summarized in the table below:

| pre command     | command                        | LOGNAME | USER  | LNAME | USERNAME | libc  | R: login | R: user | R: effective_user | os.getlogin() | getpass.getuser() |
|-----------------|--------------------------------|---------|-------|-------|----------|-------|----------|---------|-------------------|---------------|-------------------|
|                 | /tmp/username.jl               | tp      | tp    |       | tp       | tp    | tp       | tp      | tp                | tp            | tp                |
| su user1        | /tmp/username.jl               | user1   | user1 |       | tp       | user1 | tp       | user1   | user1             | tp            | user1             |
| su - user1      | /tmp/username.jl               | user1   | user1 |       |          | user1 | tp       | user1   | user1             | tp            | user1             |
|                 | sudo -u user1 /tmp/username.jl | user1   | user1 |       |          | user1 | tp       | user1   | user1             | tp            | user1             |

The results for R was obtained calling `R -q -e "Sys.info()"`, and for python using this script:

```
cat /tmp/username.py
#!/usr/bin/python3
import os
import getpass
print("os: " + os.getlogin())
print("getpass: " + getpass.getuser())
```

**Comment by mhetrerajat** [comment]
Hey @stevengj, @tp2750 @Seelengrab  ,
Is anybody working on it ? If not, I would love to work on it.

**Comment by tp2750** [comment]
@mhetrerajat wrote:

> I would love to work on it.

That would be great!

**Comment by mhetrerajat** [comment]
Thanks, @tp2750. Feel free to assign it to me; I will start working on it.

**Comment by Seelengrab** [comment]
You can just start working on a PR and we'll review it :)

**Comment by TakshDhabalia** [comment]
is anyone actively working on it ? I would like to contribute.
Thanks!

**Comment by tp2750** [comment]
I'm not.

**Comment by mhetrerajat** [comment]
> is anyone actively working on it ? I would like to contribute. Thanks!

I am working on it.

**Comment by TakshDhabalia** [comment]
Hey @mhetrerajat , as you are working on the issue, can I come contribute into the same as I am interested in the same and having looked at modern language components of the same function I think I would be helpful. 
Thanks!

**Comment by mhetrerajat** [comment]
Hi @TakshDhabalia.
I appreciate your willingness to contribute, and your expertise in modern language components could certainly be helpful. Would you be willing to review my pull request when it's ready? I am almost done with it and just need to write some tests before opening it up. Your feedback would be very helpful, and I would be grateful for any comments or suggestions you may have. Thank you in advance for your time and support!

**Comment by tp2750** [comment]
Great work @mhetrerajat . I look forward to testing it.

**Comment by TakshDhabalia** [comment]
Thanks for the reply @mhetrerajat and also I would love to work and test the new feature and contribute to the same .
Also great work on the same , appreciate it !
Thanks.
