### ISSUE TITLE
Drop support for Windows 7 since EOLed?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#48306]
It still has 10% share, but does Windows 10 have any API we like to use and blocked by needing to support Windows 7?
https://gs.statcounter.com/windows-version-market-share/desktop/worldwide/#monthly-201701-202301

Windows 11 is already double the share of Windows 10. If there's nothing we need from newer Windows then please keep 7 supported or a little longer...

**Comment by PallHaraldsson** [comment]
I see you can as of Windows 10:
"Create symbolic links" "Microsoft has implemented symbolic links to function just like UNIX links. Warning:   This privilege should only be given to trusted users."

and also maybe relevant:
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
> Enable Long Paths in Windows 10, Version 1607, and Later
>
> Starting in Windows 10, version 1607, MAX_PATH limitations have been removed from common Win32 file and directory functions. However, you must opt-in to the new behavior.

**Comment by giordano** [comment]
The minimum requirement is already Windows 10 according to https://julialang.org/downloads/#supported_platforms

**Comment by PallHaraldsson** [comment]
Oh, I missed that. I see however 8.1+ (for tier 2) so the question about APIs still stands. 8.1 isn't EOLed yet, but has a tiny share, lower than 7, so I don't mind dropping it. Closing since the issue title is irrelevant now. Feel free to answer about APIs though or possibly open issue/change title?
