### ISSUE TITLE
closing around `ans` or using it as an lvalue in the REPL should emit a warning

### ISSUE THREAD

**Issue by adienes** [JuliaLang/julia#48323]
I know `ans` can be convenient in REPL-mode to get the result of the previous expression. Nonetheless I find the following behavior pretty dangerous:

```
julia> my_calculation(x) = 2x-1
my_calculation (generic function with 1 method)

julia> ans = my_calculation(10)
19

julia> y = my_calculation(0)
-1

julia> ans
-1
```

or

```
julia> ans = 10
10

julia> my_closure(x) = ans*x
my_closure (generic function with 1 method)

julia> my_closure(5)
ERROR: MethodError: no method matching *(::typeof(my_closure), ::Int64)
```

In my opinion, `ans` should only be available as a reference to previous expression in lines which are literally pasted or typed into the REPL, and not available to be closed over in functions. At the very least, I think both of these cases should give the user a warning that something wicked is brewing.

**Comment by vtjnash** [comment]
Would be solved by https://github.com/JuliaLang/julia/pull/48308
