### ISSUE TITLE
Suggestion: Use `actions/labeler`

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#48341]
Use [`actions/labeler`](https://github.com/actions/labeler), It labels PRs by path of updated files.

**Comment by ViralBShah** [comment]
@DilumAluthge Is this something we should do? Or close otherwise?

**Comment by DilumAluthge** [comment]
I don't feel strongly either way, but it doesn't seem like PR labels are a big problem for us right now, so this feels like a solution without a problem.
