### ISSUE TITLE
Clean up LAPACK error handling

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#4836]
As part of #4830:

Error handling in the LAPACK wrappers is inconsistent and rather messy, and could use a serious overhaul.
# [LAPACK's internal error handling](http://www.netlib.org/lapack/lug/node119.html)

Almost all LAPACK routines return an `info::BlasInt` argument which is one of:
- 0 if everything went smoothly, 
- a negative number `-n` specifying that the `n`th argument was invalid,
- a positive number whose meaning depends on the routine being called.

For some routines, additional error information is encoded in arrays, often in allocated `work`, `lwork` or `rwork` arrays.

The default error handling behavior in LAPACK is to check within the routine if `info` is nonzero and if so, spit out an error message to the console like this:

```
 ** On entry to DSFRK  parameter number  1 had an illegal value
```
# Issues
1. **Input validation.** Some, but not all, LAPACK wrappers do additional input validation on mode specifiers (e.g. `UPLO = 'U' or 'L'`) before running the actual calculation. Choices:
   a. Declare these checks redundant and eliminate them from the Julia wrappers
   b. Do this consistently for all such wrappers and wrap them with nicer error messages like `invalid argument: uplo = $uplo (valid choices: 'U' (upper) , 'L' (lower))`
   
   Update: As of #4830:
   - there is now a `@chkuplo` macro that does this for `uplo`. There are other mode specifiers that should be validated.
   - almost all other `error` throws are deprecated for appropriate `Exception`s. The major exceptions are
     - [ ] `DomainError`s, which do not take a message field and hence will have to be changed in `Base` to be able to throw them usefully.
     - [ ] `DimensionMismatch`es, whose error messages are inconsistently generated. I'm thinking that a macro should be wriiten of the form `@wrongsize A B` that would throw `DimensionMismatch` with a programmatically generated error message like "incompatible dimensions: A (10,10), B (9,)". However, my macro fu is not up to the challenge.
2. [x] **Negative info codes.** In many (but not all) of the wrappers, a negative `info` code triggers a `LAPACKException`. While `LAPACKException` takes an error code, it is sometimes set to `info`, encoding the position of the invalid argument, and at other times to `0`. Choices:
   a. Consistently throw `LAPACKException(0)` (but why?)
   b. Consistently throw `LAPACKException(info)`
   c. Replace all `LAPACKException` throws for this case with native Julian `ArgumentError`s with a message string like `invalid argument: $argname = $argval` with the correct argument inserted programmatically.
   
   Update: As of #4830, the lapack wrappers now use the `@assertargsok` macro to handle all negative error codes, which throw `ArgumentError`s.
3. **Positive info codes.** Routine-specific errors are handled inconsistently. Many times `LAPACKException(info)` is thrown. Sometimes, the `info` code is returned to the calling routine elsewhere in `LinAlg` and an appropriate Julian `Exception` is thrown (e.g. `PosDefException`s in the Cholesky factorizations.) Other times (e.g. in `gesvx!`), the wrapper interprets the `info` code and throws an appropriate Julian `Exception`. Choices:
   a. Consistently throw `LAPACKException(info)`
   b. Consistently throw native Julian `Exception`s in the function calling the LAPACK wrapper.
   c. Consistently throw native Julian `Exception`s in the LAPACK wrapper.
   
   Update: As of #4830, the lapack wrappers contain some helper macros
4. `@lapackerror`, which handles all nonzero info codes as a placeholder for proper error handling.
5. `@assertnonsingular` and `@assertposdef`, which throw `SingularError`s and `PosDefException`s.

I'm in favor of the last option in each case. Since some of this mess is my own doing, I'm willing to clean this up. But we need to agree upon a consistent way to deal with all of this.

Related: general error handling discussion in #4816

**Comment by andreasnoack** [comment]
I don't know how much more is needed here. We try to check all input to the LAPACK wrappers so users should never see a LAPACK error with a negative error code. Generally, we shouldn't throw on positive error codes. Instead, they should be handled by the calling routine on a case by case basis so maybe we should just close this issue.
