### ISSUE TITLE
Does length(::String) return the correct length?

### ISSUE THREAD

**Issue by ndinsmore** [JuliaLang/julia#48362]
`length(::String)` currently does not return a length that makes sense for malformed strings. 

For example a string with only a continuation bytes returns length of 1:
```julia

julia> length("\x93")
1

julia> bitstring(0x93)
"10010011"
```

I think that this is all related to `thisind(s,i)` returning `i` in unknow conditions.
But the question is what is right?

**Comment by jakobnissen** [comment]
This is correct behaviour. There is some Unicode standard (I forget which) that recommends counting every invalid byte as a character.

**Comment by JeffBezanson** [comment]
That is correct. If anyone finds a case where `length` disagrees with the number of Chars iterated, please reopen.
