### ISSUE TITLE
libcurl breaks tons of applications

### ISSUE THREAD

**Issue by gvanuxem** [JuliaLang/julia#48377]
Just downloaded. Same thing several days ago.

Message: 
gdb
gdb: symbol lookup error: /lib/x86_64-linux-gnu/libcurl-gnutls.so.4: undefined symbol: nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation

git too.  And others for sure.

Git version of Julia from ~11:00 am - Timezone Paris
Julia installed in /usr/local via a 'sudo cp -Rf usr/* /usr/local/'

Julia Version 1.10.0-DEV.unknown
Commit 7630606* (2023-01-22 05:37 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 4 virtual cores

Debian-like system (Kali on WSL2)

Regards,

Greg

PS : Yes I know, it's better not to install it  but I'm doing some modifications for something I'm working on and I need to  bypass signals handling with libjulia.so i.e. at runtime (for SBCL/C calling Julia - jl_init). And I need to check.

**Comment by gvanuxem** [comment]
Removing libcurl* in /usr/local/lib of course seems to cure  the problem.

**Comment by KristofferC** [comment]
> /usr/local via a 'sudo cp -Rf usr/* /usr/local/'

Wouldn't that have overwritten all your local libraries with the ones julia bundle (which might be at incompatible versions)

**Comment by gvanuxem** [comment]
No. And same versions I think:
┌──(greg㉿ellipse)-[~/tmp/julia]
└─$ ls -l /lib/x86_64-linux-gnu/libcurl*
lrwxrwxrwx 1 root root     19 23 déc.  21:36
/lib/x86_64-linux-gnu/libcurl-gnutls.so.3 -> libcurl-gnutls.so.4
lrwxrwxrwx 1 root root     23 23 déc.  21:36
/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.8.0
-rw-r--r-- 1 root root 665336 23 déc.  21:36
/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.8.0
lrwxrwxrwx 1 root root     16 23 déc.  21:36
/lib/x86_64-linux-gnu/libcurl.so.4 -> libcurl.so.4.8.0
-rw-r--r-- 1 root root 685832 23 déc.  21:36
/lib/x86_64-linux-gnu/libcurl.so.4.8.0

┌──(greg㉿ellipse)-[~/tmp/julia]
└─$ ls -l /usr/local/lib/libcurl.so*
lrwxrwxrwx 1 root root     16 22 janv. 11:18 /usr/local/lib/libcurl.so ->
libcurl.so.4.8.0
lrwxrwxrwx 1 root root     16 22 janv. 11:18 /usr/local/lib/libcurl.so.4 ->
libcurl.so.4.8.0
-rwxr-xr-x 1 root root 653232 22 janv. 11:18
/usr/local/lib/libcurl.so.4.8.0No

**Comment by vtjnash** [comment]
Looks like the compiler flags are different and incompatible between those

**Comment by giordano** [comment]
How did you install julia?  I don't think it's expected to have libcurl in a default loader search path.  They should be in `${prefix}/lib/julia`, not `${prefix}/lib`.

**Comment by vchuravy** [comment]
I think you missed a `make install` step which will create a directory `julia-...` that has the libraries in the subdir that Mose described

**Comment by gvanuxem** [comment]
> I think you missed a `make install` step which will create a directory `julia-...` that has the libraries in the subdir that Mose described

Yes, you're right. I'm used to 1.8.* binary packages, they haven't install scripts, so I thought the julia_src/usr directory was the one to install even though I knew Julia uses its own library versions.

Thanks, all is right now. My fault.

**Comment by AmirF194** [comment]
conda config --set auto_activate_base false
did the trick for me.
