### ISSUE TITLE
segmentation fault during installing packages

### ISSUE THREAD

**Issue by DieselDriver** [JuliaLang/julia#48386]
Hello,

I always get segmentation faults when I try to enter any invalid command or installing some packages.

![This is an image](https://i.ibb.co/Q8pVTbR/julia.png)

On computer 1 it does not work, on the second it works fine.
The only difference is that computer 1 has two CPUs and the computer 2 only has one CPU.

Is there a verbose mode available?

The logfile on computer does not contain useable information. The directory ~/.julia only contains the logfile. On computer 2 the directory ~./juilia contains more subfolders.

Has anyone an idea how to fix this issue?
Thanks, a lot.

**Comment by maleadt** [comment]
Julia 1.5 is an old and unsupported version, so you should probably upgrade to (at the least) Julia 1.6, which is the long-term supported version. In addition, you seem to be using a build of Julia packages by Debian, which is another unsupported configuration; it's better to download Julia binaries from the home page: https://julialang.org/downloads/

**Comment by StefanKarpinski** [comment]
You should really upgrade to the latest stable release, which is 1.8.5 (currently).
