### ISSUE TITLE
Make julia_exename public API?

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#48393]
[`Base.julia_cmd`](https://github.com/JuliaLang/julia/blob/b8adb2ede505e2d9eb2cfcd03caa64da643c9f22/base/util.jl#L155) is public API, but [`Base.julia_exename`](https://github.com/JuliaLang/julia/blob/b8adb2ede505e2d9eb2cfcd03caa64da643c9f22/base/util.jl#L237-L243) is not (it has no docstring). 

Many packages already use `julia_exename`: https://juliahub.com/ui/Search?q=julia_exename&type=code

`julia_exename` is also used in the documentation of `julia_cmd`:

```
help?> Base.julia_cmd
  Base.julia_cmd(juliapath=joinpath(Sys.BINDIR, julia_exename()); cpu_target)

  Return a julia command similar to the one of the running process. Propagates
  any of the --cpu-target, --sysimage, ...
```

**Comment by Seelengrab** [comment]
Almost all of these seem to be of the form

```
joinpath(Sys.BINDIR, Base.julia_exename())
```

Would it make more sense to have that available instead?

**Comment by giordano** [comment]
You probably want to use `julia_cmd`:  #48039. And the first element of `julia_cmd` is the executable path, if you really only want that one.

**Comment by fonsp** [comment]
Thanks for the suggestions! Indeed, I think some of the uses found by https://juliahub.com/ui/Search?q=julia_exename&type=code could just use `julia_cmd()` instead.

But for some, like `PackageCompiler`, you actually want the flags to **not** be propagated, right? When you are not doing distributed computing, but launching a sandboxed Julia process for a dedicated task.

Perhaps we could make propagation configurable with a kwarg of `julia_cmd`?

**Comment by giordano** [comment]
As I said above, you can use `julia_cmd()[1]`.

**Comment by fonsp** [comment]
I see, thanks! Feel free to close then.
