### ISSUE TITLE
Dependencies versions used by Julia no longer exists

### ISSUE THREAD

**Issue by mboisson** [JuliaLang/julia#48396]
The version of DSFMT which Julia attempts to download (2.2.4) is not available on Github: 
https://github.com/MersenneTwister-Lab/dSFMT/releases

causing the build to fail. 

Any reason why it is using this version instead of 2.2.5 which was released in 2021 ?

**Comment by mboisson** [comment]
The same happens with P7ZIP. The repository no longer has any release: https://github.com/jinfeihan57/p7zip

**Comment by vchuravy** [comment]
> The version of DSFMT which Julia attempts to download (2.2.4) is not available on Github:

I see https://github.com/MersenneTwister-Lab/dSFMT/releases/tag/v2.2.4 ? 

> The same happens with P7ZIP. The repository no longer has any release: https://github.com/jinfeihan57/p7zip

The URL should be https://github.com/p7zip-project/p7zip/releases.

Can you expand on what version of Julia you are trying to build and what your configuration is?

**Comment by mboisson** [comment]
I am trying to build version 1.8.1, from source, using
https://github.com/JuliaLangjulia/releases/download/v1.8.1/julia-1.8.1.tar.gz

For dSFMT, it is not there
https://github.com/MersenneTwister-Lab/dSFMT/releases
and I did have an error that said `dsfmt-2.2.4` did not exist, but now it seems to go past that, maybe it was transient 🤷 

for P7ZIP, it is trying to download
 https://github.com/jinfeihan57/p7zip/archive/refs/tags/v$(P7ZIP_VER).tar.gz
