### ISSUE TITLE
Using `ifelse` instead of `? :` might be faster

### ISSUE THREAD

**Issue by getzdan** [JuliaLang/julia#48401]
Having stumbled into `slicearray` it seems the following could use `ifelse` instead of `? :` to avoid possible brances:

https://github.com/JuliaLang/julia/blob/9b1ffbbe1bce1eaf3327535ae3e46e923e8d9aff/base/slicearray.jl#L232

There are 3 other cases of similar nature in the file, but this one looks to be the most time-critical as it is used in `getindex` and `setindex!`.

Stumbled here because of @mcabbott answer here:
[https://stackoverflow.com/questions/75221937/julia-reshaping-a-4d-array-into-a-matrix-of-matrices](https://stackoverflow.com/questions/75221937/julia-reshaping-a-4d-array-into-a-matrix-of-matrices)

**Comment by vtjnash** [comment]
branches are good, they avoid running code, which is slow
