### ISSUE TITLE
Change in ComplexF64 division

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#48457]
https://github.com/JuliaLang/julia/pull/47255 caused the following:

```julia
julia> inv(0.2 + 0.0im)
4.999999999999999 - 0.0im
```

In 1.8 this was:

```julia
julia> inv(0.2 + 0.0im)
5.0 - 0.0im
```

I don't know what the guarantees are for this operation but it seems kind of silly to stop being able to do this.

**Comment by gbaraldi** [comment]
Yeah it seems odd. I would imagine we guarantee that a complex number with no imaginary part would behave the same as a normal Float and it here it doesn't.

**Comment by oscardssmith** [comment]
We could add a branch for zero imaginary part, but IMO it's not worth it (it would be a noticeable slowdown)

**Comment by KristofferC** [comment]
> We could add a branch for zero imaginary part, but IMO it's not worth it (it would be a noticeable slowdown)

I am not sure about that:

```
julia> using GFlops

julia> @count_ops inv(1.0+2.0im) 
Flop Counter: 13 flop
┌────────┬─────────┐
│        │ Float64 │
├────────┼─────────┤
│ muladd │       1 │
│    add │       1 │
│    mul │       1 │
│    div │       4 │
│    abs │       2 │
│    neg │       1 │
│   sqrt │       2 │
└────────┴─────────┘
```

Feels like a well predicted branch should be not very noticeable among that?

**Comment by oscardssmith** [comment]
The actual count after const-prop is much lower since none of the sqrts and half of the divisions aren't real.

**Comment by KristofferC** [comment]
Tried first benchmark in https://github.com/JuliaLang/julia/pull/47255#issue-1416873836 and it went from `1.933 μs` to `
2.037 μs`. That feels worth it to me.

**Comment by oscardssmith** [comment]
fair enough. One thing to be wary of is that that benchmark will look better for this change since with that benchmark the cpu will learn that the imaginary part is never 0, and if you care about this you are probably in the case where the branch is harder to predict.

**Comment by KristofferC** [comment]
But if you have a lot of zero imaginary numbers, shouldn't the new implementation be faster since it only has to do a single fp division?
