### ISSUE TITLE
Broken inside Google Colab

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#48461]
It has historically been possible to install Julia in the background of Google Colab VMs (https://colab.research.google.com/), since it's literally just an Ubuntu 20.04 virtual machine. Others like @johnnychen94 (https://github.com/johnnychen94/colab-julia-bootstrap) and @ageron (https://github.com/ageron/julia_notebooks) have even built ways to swap the Jupyter kernel with a Julia one, letting the user use full Julia within Colab notebooks.

However, Julia seems to be completely broken on the latest update of Colab, over all Julia versions I have tested. Even just calling Julia from shell – without hacking the jupyter kernel – produces various segfaults and pointer errors.

Here's a MWE (colab [here](https://colab.research.google.com/drive/17gVS2_h5SIlORg6sWuFSdR29SMaGvvbl?usp=sharing))

```shell
%%shell
set -x

wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz -O /tmp/julia.tar.gz
tar -xzf /tmp/julia.tar.gz -C /usr/local/ --strip-components 1
rm /tmp/julia.tar.gz
```

followed by

```shell
!julia -e 'print("Hello World!")'
```

This generates the following output:

```shell
Hello World!munmap_chunk(): invalid pointer

signal (6): Aborted
in expression starting at none:0
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f49062b426d)
unknown function (ip: 0x7f49062bc2fb)
unknown function (ip: 0x7f49062bc54b)
close_unit_1 at /workspace/srcdir/gcc-12.1.0/libgfortran/io/unit.c:742
close_units at /workspace/srcdir/gcc-12.1.0/libgfortran/io/unit.c:800
unknown function (ip: 0x7f4906669f6a)
unknown function (ip: 0x7f490626d8a6)
exit at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
main at julia (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 2909 (Pool: 2895; Big: 14); GC: 0
```

Discourse thread: https://discourse.julialang.org/t/google-colab-compatibility-broken/93004/9

cc @giordano @Moelf

**Comment by Dsantra92** [comment]
Completed via https://github.com/googlecolab/colabtools/issues/3385?
