### ISSUE TITLE
Error reporting in `@async` blocks

### ISSUE THREAD

**Issue by ettersi** [JuliaLang/julia#48493]
Errors in `@async` blocks are currently too easy to get lost. 

```
julia> @async (sleep(1.0); error("bla"))
Task (runnable) @0x000000010eb23880

# No error message!
```

This is a massive foot gun for async newbies like myself (see e.g. [this](https://discourse.julialang.org/t/how-to-get-backtrace-of-async-task/18170) or [this](https://discourse.julialang.org/t/how-do-i-see-errors-encountered-in-async-coroutines-tasks/44134) discourse discussion), and I'm assuming it's quite a nuisance also for seasoned async programmers.

**Comment by fredrikekre** [comment]
You can use [`errormonitor`](https://docs.julialang.org/en/v1/base/parallel/#Base.errormonitor).
```
julia> errormonitor(@async (sleep(1.0); error("bla")))
Task (runnable) @0x00007fbe2ae5bb70

julia> Unhandled Task ERROR: bla
Stacktrace:
 [1] error(s::String)
```
