### ISSUE TITLE
Different behavior of `&&` and `||` in short-curcuit evaluation

### ISSUE THREAD

**Issue by jacobxk** [JuliaLang/julia#48516]
In @bkamins 's _Julia for Data Analysis_, in page 30, there is an example about the short-curcuit evaluation.

```julia
julia> x = -7
-7

julia> x < 0 && println(x^2)
49

julia> iseven(x) || println("x is odd")
x is odd
```

for the `&&`, only if the first statement is true then implement the `println(x^2)`, otherwise, just return `false`; for the `||`, only if the first statement is false then implement the `println("x is odd")`, otherwise, just return `true`.

```julia
julia> x = -7
-7

julia> x > 0 && println(x^2)
false

julia> isodd(x) || println("x is odd")
true
```

May I know a bit more why the Julia's short-curcuit designed like this? I think it might introduce confusion at sometimes.

**Comment by oscardssmith** [comment]
Hi! Welcome to Julia, for questions you should use https://discourse.julialang.org/ or stackoverflow.com (github is for bug reports/pull requests), but the TLDR is that this is intended behavior. `&&` short circuits on a `false` first input since `false && x == false` while `||` short circuits on `true` because `true || x == true`.

**Comment by jacobxk** [comment]
> Hi! Welcome to Julia, for questions you should use https://discourse.julialang.org/ or stackoverflow.com (github is for bug reports/pull requests), but the TLDR is that this is intended behavior. `&&` short circuits on a `false` first input since `false && x == false` while `||` short circuits on `true` because `true || x == true`.

Got it and thanks. I am firstly treat it as a bug, but after I test the codes again I realized that its behavior are consistent. However, I cannot delete this issue and I modified the original question to something like a question. Sorry for that.

**Comment by oscardssmith** [comment]
no problem
