### ISSUE TITLE
The last `Next` button in Windows installer should say `Install` instead

### ISSUE THREAD

**Issue by kdheepak** [JuliaLang/julia#48521]
Right now the `Next` button in the `Select additional tasks` screen is not clear that it is going to install Julia when you hit `Next`.

![image](https://user-images.githubusercontent.com/1813121/216769410-7931d5ed-5c94-4892-a2da-c67326309e62.png)

I think it'd be a better UX if it said `Install` instead.

For reference, this is what `git` does on the very last screen of its options:

![image](https://user-images.githubusercontent.com/1813121/216769613-766e25f8-6ccb-47c5-a67a-13c5626140e9.png)

`vscode` goes on step further and summarizes all the "additional tasks" that were selected in the previous screen.

![image](https://user-images.githubusercontent.com/1813121/216769709-84bec21a-a959-4489-9271-7f48ee7e2703.png)

**Comment by inkydragon** [comment]
I guess reopening the "Ready page" would be enough.

https://github.com/JuliaLang/julia/blob/07c4244caa8cd6611f42296891ac74f9d6ae25ff/contrib/windows/build-installer.iss#L79

```patch
-DisableReadyPage=yes
+DisableReadyPage=no
```
