### ISSUE TITLE
Precompile reverse-i-search for faster REPL history first-access

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#48532]
This is a minor annoyance, but I'm guessing it could be an easy fix.  I frequently start a new Julia REPL session and want to rerun a command from history, so I type `Ctrl-r` to search for it, but there's always a ~1 second pause the first time I run `Ctrl-r`, which I assume is from the required functions being compiled.

My (possibly flawed) understanding is that most REPL required functions are precompiled and bundled in the default system image in order to reduce the latency of interactive use on first run.  Could the required functions for `reverse-i-search` simply be added to the system image as well?

I'm using a 1.10 Nightly on amd64 Linux.  My recollection is that this behavior didn't exist a year or so ago, but I don't remember when the behavior changed, so it's possibly a regression.

**Comment by giordano** [comment]
I don't see any lag:

https://user-images.githubusercontent.com/765740/216796163-b3ac5f2f-03a3-4dca-a42e-f3de46a7a4d5.mp4

```
julia> versioninfo()
Julia Version 1.10.0-DEV.484
Commit 532643d6392* (2023-02-03 12:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
```

**Comment by robsmith11** [comment]
Does it not feel slower than subsequent times you press `ctrl-r`?

I found the debug flag that I was looking for before.  Aren't these functions all being compiled on each first run?
```
$ JULIA_DEPOT_PATH=/tmp/new /me/julia/bin/julia --trace-compile=/tmp/out.jl
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0-DEV.294 (2023-01-07)
 _/ |\__'_|_|_|\__'_|  |  Commit de73c26fbff (28 days old master)
|__/                   |

julia> ^C

julia>
$ cat /tmp/out.jl
precompile(Tuple{REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#79#110"{REPL.LineEdit.HistoryPrompt}, String}, Any, Any})
precompile(Tuple{typeof(Base.ntuple), Base.Returns{Base.OneTo{Int64}}, Base.Val{1}})
precompile(Tuple{typeof(Base.:(<=)), Int64, UInt8})
precompile(Tuple{typeof(Base.:(<=)), UInt8, Int64})
precompile(Tuple{typeof(Base.rem), UInt8, Type{Int64}})
precompile(Tuple{REPL.LineEdit.var"#79#110"{REPL.LineEdit.HistoryPrompt}, REPL.LineEdit.MIState, Any, Vararg{Any}})
precompile(Tuple{REPL.LineEdit.var"#46#47"{REPL.LineEdit.MIState, REPL.LineEdit.HistoryPrompt, Bool, REPL.LineEdit.Prompt, Base.GenericIOBuffer{Array{UInt8, 1}}}})
precompile(Tuple{typeof(Base.setproperty!), REPL.LineEdit.SearchState, Symbol, REPL.LineEdit.Prompt})
precompile(Tuple{typeof(Base.truncate), Base.GenericIOBuffer{Array{UInt8, 1}}, Int64})
precompile(Tuple{REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#58#89", String}, Any, Any})
precompile(Tuple{REPL.LineEdit.var"#58#89", REPL.LineEdit.MIState, REPL.LineEdit.ModeState, Any})
precompile(Tuple{REPL.LineEdit.var"#27#28"{REPL.LineEdit.var"#119#175", String}, Any, Any})
precompile(Tuple{REPL.LineEdit.var"#119#175", REPL.LineEdit.MIState, Any, Vararg{Any}})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Nothing, Int64}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{Nothing, Int64}, Int64, Int64})
precompile(Tuple{REPL.var"#60#66"{REPL.REPLBackendRef}})
```
(I used a new depot path to eliminate the possibility that loading a large history file was the problem.)

**Comment by KristofferC** [comment]
Can be added to https://github.com/JuliaLang/julia/blob/07c4244caa8cd6611f42296891ac74f9d6ae25ff/contrib/generate_precompile.jl#L63-L83.

**Comment by robsmith11** [comment]
Thanks @KristofferC .  Adding CTRL_R there makes a big improvement for me.

I tried making a pull request (first time, so hopefully did it right):
https://github.com/JuliaLang/julia/pull/48539

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/48539
