### ISSUE TITLE
Override functionality for Artifacts seems to be untested

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#48551]
Looking at hhttps://app.codecov.io/gh/JuliaLang/julia/blob/master/stdlib%2FArtifacts%2Fsrc%2FArtifacts.jl#L121 it seems the override functionality (`Overrides.toml`) is not tested. Would be good to have that done.

**Comment by u7581147** [comment]
Hi @KristofferC, I'd love to work on this issue and add tests for `Artifacts.jl`. Could you assign this issue to me? Thanks.

**Comment by KristofferC** [comment]
We generally don't assign issues to people to prevent "cookie licking" (https://www.redhat.com/en/blog/dont-lick-cookie). You can just start working on it anyway if you wish :)

**Comment by u7581147** [comment]
Thanks, Kristoffer. I'll try my best to complete it but cannot guarantee anything.

**Comment by u7581147** [comment]
Hi @KristofferC, I added tests for the `artifacts_hash()` in `Artifacts.jl`. Am I doing it the right way? 
Of course, I'm happy to add tests for other functions if it's on the right track.

**Comment by u7581147** [comment]
Hi @KristofferC, following your comment in  #51815, I added tests for `load_overrides()` in `Artifacts.jl` in #51833.

Does it do the right thing?

Thanks.

**Comment by u7581147** [comment]
It basically tests in three steps:
1. Create an `Overrides.toml` file.
2. Test `load_overrides()` using the created file.
3. Delete any created file, so that the system behaves like the test never happened.
