### ISSUE TITLE
Allow AbstractVector in PipeBuffer

### ISSUE THREAD

**Issue by LlewellynS96** [JuliaLang/julia#48585]
I have a use case for calling PipeBuffer with an AbstractVector{UInt8}, but currently it explicitly expects a Vector{UInt8}. I can't see a good reason why this cannot be changed since GenericIOBuffer has no problem accepting any AbstractVector{UInt8}.

If anyone will approve this, then I will submit a PR.

https://github.com/JuliaLang/julia/blob/3a92d385c46164618c23def8203d372c0ad8adf2/base/iobuffer.jl#L136

**Comment by vtjnash** [comment]
I approve
