### ISSUE TITLE
Interactive threads in Julia v1.9.0-beta do not give expected results

### ISSUE THREAD

**Issue by simsurace** [JuliaLang/julia#48580]
Isn't this behavior contradicting the docs?

```julia
$ julia +beta -t 1,1

julia> fetch(Threads.@spawn :interactive Threads.threadpool())
:default # expecting :interactive

julia> Threads.nthreads()
1 # expecting 2
```

**Comment by simsurace** [comment]
Ok, but what about spawning an interactive thread?
What is `-t 1,1` saying, if not "give me two threads, one of them interactive"? 
I think the docs are still not correct then.

```

-t, --threads {auto|N[,auto|M]}
                          Enable N[+M] threads; N threads are assigned to the `default`
                          threadpool, and if M is specified, M threads are assigned to the
                          `interactive` threadpool; "auto" tries to infer a useful
                          default number of threads to use but the exact behavior might change
                          in the future. Currently sets N to the number of CPUs assigned to
                          this Julia process based on the OS-specific affinity assignment
                          interface if supported (Linux and Windows) or to the number of CPU
                          threads if not supported (MacOS) or if process affinity is not
                          configured, and sets M to 1.
```

**Comment by oscardssmith** [comment]
The problem with is that while spawning with 1 normal and 1 interactive thread, users of `nthreads` generally use it to determine "how many threads can I schedule my heavy computation on" and then the answer to that question shouldn't include the interactive thread(s). The real problem as @vtjnash said is that `nthreads` is no longer a function that really makes sense to ask.

**Comment by simsurace** [comment]
Thanks, I get this part. My remaining problems are
- The docs seem to be wrong then. The [page on threads](https://docs.julialang.org/en/v1.10-dev/manual/multi-threading/#man-threadpools) says that `nthreads()` should be 2 here. 
- I would still expect to be able to spawn the single interactive thread that I asked for here:

```julia

$ julia +beta -t 1,1

julia> fetch(Threads.@spawn :interactive Threads.threadpool())
:default # expecting :interactive```

**Comment by IanButterworth** [comment]
Perhaps a maxlog=1 warning would help https://github.com/JuliaLang/julia/pull/48589

**Comment by jakobnissen** [comment]
If `nthreads` is being deprecated, what mechanism should be used to determine the number of threads that can run at a given time? This information is needed in many threaded programs.

**Comment by simsurace** [comment]
I'll open a new issue for the inability to spawn an interactive thread as it does not get enough attention IMHO.
