### ISSUE TITLE
thisind & nextind not consistent with handleing non UTF-8 standard codepoints

### ISSUE THREAD

**Issue by ndinsmore** [JuliaLang/julia#48581]
To make the handling of non utf-8 strings consistent in Julia, I believe that the current assumption is that the bad codepoint should either contain the extent of the valid codeunits or 1 invalid codeunit.  Right now both thisind & nextind assume that all valid continuation bytes are valid.   Which if you look at the table below is not correct for a first byte = `E0,ED,F0,F4`.

So that begs the question for those sequences should for example `0xE08080` be allowed to be one code point, or should it be broken up into `0xE0,0x80,0x80`?
 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/45537276/217309344-d5c04871-bd73-44cb-82f5-d7bedf22549a.png">

**Comment by StefanKarpinski** [comment]
Where's this table from? Is this in the Unicode standard?

**Comment by StefanKarpinski** [comment]
In any case, I think that breaking overlong encoding into multiple invalid characters seems actively bad even though you already know that an encoding is overlong by the time you see the first `0x80` byte.

**Comment by StefanKarpinski** [comment]
To be clear, I'm not advocating for using encodings like MUTF-8 and CESU-8, which are kind of horrible (WTF-8, otoh, is kind of genius, imo). But they do occur and if you want to detect/handle them, then having the right notion of what an invalid character is helps a lot. Otherwise you're left trying to piece together individual bytes and figure out what's happening, instead of being able to just do things like `Base.isoverlong(c) && Base.decode_overlong(c) == 0` which is way more informative when you encounter this kind of thing.

**Comment by ndinsmore** [comment]
The table is from https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf

So to add some formality to the implementation julia is essentially using WTF-8 or maybe you could call it a IUTF-8 for InvalidUTF-8.

But the need for formality comes from work I am doing on speeding up length and potentially iteration.  Also it could help with verification, even though there are a lot of tests for string already.

For formalities sake would you say that the state diagram below is correct for julia's intendened implimentation?
```julia
#=
 ┌─────────────────────────────────────────────────────────────────────┐
 │                                                                     │
 │                               ┌──────────────2──────────────┐       │
 │              ┌─────────────┐  │                             │       │
 │              │             │  ├────────3────────┐           │       │
 │   ASCII      │    WTF-8    │  │                 │           │       │
 │              │             │  │                 │           │       │
 │              │   ┌──0──┐   │  │                 │           │       │
 │   ┌─0─┐      │   │     │   │  │     ┌─┐        ┌▼┐         ┌▼┐      │
 │   │   │      │  ┌▼─────┴┐  │  ├─4──►│4├───1────►3├────1────►2├────┐ │
 │  ┌▼───┴┐     │  │       │  ▼  │     └─┘        └─┘         └─┘    │ │
 │  │  0  ├─2:4─┘  │   1   ├─► ──┘   Needs 3    Needs 2     Needs 1  │ │
 │  └─────┘        │       │        ContBytes  ContBytes   ContBytes │ │
 │                 └──▲──▲─┘                                         │ │
 │                    │  │           ContByte=Transition 1           │ │
 │                    │  │                                           │ │
 │                    │  └─────────────────────1─────────────────────┘ │
 │                    │                                                │
 │                    └──All undefined transitions result in state 1   │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘
=#
```
With the character encodings:
```julia
byte_class = [  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x00:0x0F      00000000:00001111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x10:0x1F      00010000:00011111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x20:0x2F      00100000:00101111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x30:0x3F      00110000:00111111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x40:0x4F      01000000:01001111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x50:0x5F      01010000:01011111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x60:0x6F      01100000:01101111
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,    #  0x70:0x7F      01110000:01111111
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,    #  0x80:0x8F      10000000:10001111
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,    #  0x90:0x9F      10010000:10011111
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,    #  0xA0:0xAF      10100000:10101111
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,    #  0xB0:0xBF      10110000:10111111
                2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,    #  0xC0:0xCF      11000000:11001111
                2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,    #  0xD0:0xDF      11010000:11011111
                3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,    #  0xE0:0xEF      11100000:11101111
                4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5  ]  #  0xF0:0xFF      11110000:11111111
```

With this defination you can say that a codepoint ends when ever the state machine transitions back to state 1 or 2.

**Comment by ndinsmore** [comment]
Thank you for that I think we are in agreement now that I understand.
I can say with confidence that the table you just described is equivalent (If it is equivalent to the current `thisind` & `nextind` implementation ) to:
```

 ┌─────────────────────────────────────────────────────┐
 │               ┌──────────────2──────────────┐       │
 │  IUTF-8       ├────────3────────┐           │       │
 │  ┌──0──┐      │     ┌─┐        ┌▼┐         ┌▼┐      │
 │ ┌▼─────┴┐     ├─4──►│3├───1────►2├────1────►1├────┐ │
 │ │       │     │     └─┘        └─┘         └─┘    │ │
 │ │   0   ├─────┘   Needs 3    Needs 2     Needs 1  │ │
 │ │       │        ContBytes  ContBytes   ContBytes │ │
 │ └──▲──▲─┘                                         │ │
 │    │  │           ContByte=Transition 1           │ │
 │    │  └─────────────────────1─────────────────────┘ │
 │    └──All undefined transitions result in state 0   │
 └─────────────────────────────────────────────────────┘

```
With a transition table that looks like

|state => |1 |2|3|4|
|-|-|-|-|-|
|0x00:0x7f |0|  0|  0|  0|
|0x80:0xbf |0|  0|  1|  2|
|0xc0:0xdf |1|  0|  0|  0|
|0xe0:0xef |2|  0|  0|  0|
|0xf0:0xf7 |3|  0|  0|  0|
|0xf8:0xff |0|  0|  0|  0|

The incredible thing is when you run it in reverse as you would in `thisind` the table looks like this:
|state => |1 |2|3|4|
|-|-|-|-|-|
|0x00:0x7f |0|  0|  0|  0|
|0x80:0xbf |1|  2|  3|  0|
|0xc0:0xdf |0|  0|  0|  0|
|0xe0:0xef |0|  0|  0|  0|
|0xf0:0xf7 |0|  0|  0|  0|
|0xf8:0xff |0|  0|  0|  0|

**Comment by StefanKarpinski** [comment]
Glad we're in agreement, and yes, that state diagram looks correct to me, as does the forward transition table, except it seems to me the state labels need to be 0-3. Otherwise how do you ever get into state 4? I'm going to assume 0-3 is what's intended. I'm trying to wrap my head around the backward transition table. I think what it's saying is that, starting at the end of a string in state 0, you look at each byte backwards:

- if it's not a continuation byte, then go to state 0
- if it's a continuation byte, then increase your state count by one modulo 4, i.e.
    - 0 => 1 => 2 => 3 => 0

But these tables don't include where you insert the character breaks, so I feel like there's some complexity that's swept under the rug here. Thinking about implementing it by hand, the tricky part about iterating backwards is figuring out where in a string of continuation bytes to insert the character break.

**Comment by ndinsmore** [comment]
You were correct with the state labels at the top.   It has been corrected.

The character breaks are when ever the state machine returns to state 0.  In the forward direction, as soon state machine has consumed a byte and returned to 0 the next byte is a new character. In the reverse direction consuming a byte and returning to 0 means that this byte is the start of a character.

**Comment by StefanKarpinski** [comment]
Unfortunately, it's easy to come up with examples where this backwards scan produces the wrong number of characters as well as the wrong split. E.g. just add another continuation byte to the last example: `\xDF\xBF\xBF\xBF` would get split as `\xDF`, `\xBF\xBF\xBF` but should be split as `\xDF\xBF`, `\xBF`, `\xBF`.

**Comment by ndinsmore** [comment]
Yeah, having now worked through it again it is clear that while the forward state machine can have accept and invalid be the same state and still get the right answer.   The reverse machine does need a fifth state to do that.
