### ISSUE TITLE
Simple type-unstable code: 150x regression wrt 1.8

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#48612]
See MWE below. Results are the same for beta3 and beta4.
```julia
# 1.8
julia> @btime NamedTuple{k[]}(v[])  setup=(k=Ref((:a,)); v=Ref((1,)))
  337.324 ns (6 allocations: 192 bytes)
(a = 1,)
```

```julia
# 1.9
julia> @btime NamedTuple{k[]}(v[])  setup=(k=Ref((:a,)); v=Ref((1,)))
  52.048 μs (44 allocations: 2.16 KiB)
(a = 1,)
```

Ref slack thread just in case: https://julialang.slack.com/archives/C67910KEH/p1675970292526539.

**Comment by Seelengrab** [comment]
For the record, I cannot reproduce on master:

```
julia> @btime NamedTuple{k[]}(v[])  setup=(k=Ref((:a,)); v=Ref((1,)))
  64.902 ns (2 allocations: 32 bytes)
(a = 1,)

julia> versioninfo()
Julia Version 1.10.0-DEV.546
Commit d72a9a1d2a (2023-02-09 17:01 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 24 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 24
```

and also cannot reproduce on a 4 day old master:

```
julia> @btime NamedTuple{k[]}(v[])  setup=(k=Ref((:a,)); v=Ref((1,)))
  66.036 ns (2 allocations: 32 bytes)
(a = 1,)

julia> versioninfo()
Julia Version 1.10.0-DEV.496
Commit 07c4244caa (2023-02-05 01:47 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 24 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 24
```

**Comment by vtjnash** [comment]
Sounds fixed then

**Comment by t-bltg** [comment]
> Sounds fixed then

It'd be nice to identify the PR fixing this on master, so that it can be backported to 1.9, no ?

**Comment by Seelengrab** [comment]
> Sounds fixed then

_However_, I can reproduce on a local build of beta4:

```
julia> @btime NamedTuple{k[]}(v[])  setup=(k=Ref((:a,)); v=Ref((1,)))
  20.130 μs (45 allocations: 2.22 KiB)
(a = 1,)

julia> versioninfo()
Julia Version 1.9.0-beta4
Commit b75ddb787f (2023-02-07 21:53 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 24 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 24
```

**Comment by martinholters** [comment]
Bisection led me to 1508425368171c6d6b1da98d50095da5b8e7e42a (#48144) as the fix. Don't know whether that is backport-eligible.

**Comment by KristofferC** [comment]
It is fixed on master but it hasn't been put into 1.9, see the discussion in https://github.com/JuliaLang/julia/pull/48144#issuecomment-1425963315.

**Comment by Seelengrab** [comment]
Not every change is backportable, even if it fixes a regression. There's just not enough hands to go around to fix every possible case, sadly enough. In this particular case it seems that the fix is due to a change deep in the compiler, possibly relying on other changes that happened since the branching of 1.9.

**Comment by timholy** [comment]
Your code still runs and returns the same answers. If we weren't allowed to improve the compiler, Julia would be frozen which would be bad. But as you've noticed, some improvements come with corner-case regressions. Sorry. In the fullness of time we tend to get the benefits while eventually eliminating the harms, so the net progress is very positive.

The compiler team is stretched thin; unless you're proposing to do the work yourself, there are limits to what's possible, and going to heroics in a corner case takes away from progress that may be more impactful. You can continue to use Julia 1.8 until Julia 1.10 gets released.

**Comment by t-bltg** [comment]
I've bisected the regression to https://github.com/JuliaLang/julia/pull/45062.

On https://github.com/JuliaLang/julia/commit/36aab14a97a6ae6fb937577601e44134c24a0e37, 192 bytes.
On https://github.com/JuliaLang/julia/commit/19f44b661254cccca94ba11b7b6d0482470ed2bb, 2320 bytes.
We roughly have a 12x allocated bytes regression between `1.8.5` and `1.9.0-beta3`.

The following sequence was used in the `git bisect run` script:
```julia
f(k, v) = NamedTuple{k[]}(v[])
k, v = Ref((:a,)), Ref((1,))
f(k, v)  # warmup
stats = @timed f(k, v)
print(stats.bytes)
```

I can help notice that there only are a few allocations tests in the julia testsuite.
Should there be more of these tests (with an obvious tolerance for different OSs, ...) to catch these kind of regressions ?

**Comment by Seelengrab** [comment]
Most allocation benchmarks/statistics are tracked in https://github.com/JuliaCI/GCBenchmarks

**Comment by BioTurboNick** [comment]
> Your code still runs and returns the same answers. If we weren't allowed to improve the compiler, Julia would be frozen which would be bad. But as you've noticed, some improvements come with corner-case regressions. Sorry. In the fullness of time we tend to get the benefits while eventually eliminating the harms, so the net progress is very positive.
> 
> The compiler team is stretched thin; unless you're proposing to do the work yourself, there are limits to what's possible, and going to heroics in a corner case takes away from progress that may be more impactful. You can continue to use Julia 1.8 until Julia 1.10 gets released.

Arguably not *that* much of a corner case if existing optimized code depends on the behavior. Though to be clear, for my case the overall code is still faster in 1.9, even if one critical part is slower.

At a minimum, this family of regressions should be documented in the release notes. With any workaround, if available.

It would be also nice to know if it is at all possible to hack in a patch for this behavior that isn't a full solution, just gets specific situations closer to normal.

Or if a warning could be emitted if this situation is detected, so users of 1.9 know what specifically is wrong without having to dig around.


If significant performance regressions are deemed necessary for a release, can we find ways to reduce the surprise factor?
