### ISSUE TITLE
Hash on array fails to produce different hashes for small changes

### ISSUE THREAD

**Issue by trwilliams79** [JuliaLang/julia#48610]
I recently resolved an issue in a project I am working in with file hashes. Previously, files were read in and hashed via `hash(read("filename.xml"))`. There were multiple instances of files that were different producing the same hash, but not all the time, so I started looking into things a little deeper.

In my testing I've found that it is quite easy to generate the same hash from an array with only minor changes to the array data. The larger the array, the easier it is for one minor change to generate the same hash.

I've attached some test code that generates a 10000 index array of integers, 0 through 9 repeated 1000 times. The code then walks through the array changing one value at a time and checking the resulting hash against the original. It fails to generate a different hash 29.52% of the time. If the data is converted to a string, instead of an array of integers, it produces a different hash every time.

```
source = repeat([0:9;], 1000)
sourcelength = length(source)

array_failures = 0
string_failures = 0

for index in eachindex(source)
    # Copy the source data and set one value +1 or -1
    modified = copy(source)
    modified[index] = modified[index] == 9 ? modified[index] - 1 : modified[index] + 1

    # Test as array
    if hash(modified) == hash(source)
        array_failures += 1
    end

    # Test as string
    if hash(join(string.(modified))) == hash(join(string.(source)))
        string_failures += 1
    end
end

if array_failures == 0
    @info "No array hashes matched in $(sourcelength) iterations"
else
    @warn "$(array_failures) array hashes matched out of $(sourcelength) iterations [$((array_failures / sourcelength) * 100.)% failure rate]"
end

if string_failures == 0
    @info "No string hashes matched in $(sourcelength) iterations"
else
    @warn "$(array_failures) string hashes matched out of $(sourcelength) iterations [$((array_failures / sourcelength) * 100.)% failure rate]"
end
```

At this time, our team is running Julia 1.6.5. However, I have downloaded and replicated the issue in 1.8.5.
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 16 on 20 virtual cores
Environment:
  JULIA_PKG_DEVDIR = /home/twilliams/julia-projects
  JULIA_REGISTRY_UTILS = /home/twilliams/Projects/Julia/sgrRegistryUtils.jl
  JULIA_HOME = /home/twilliams/Downloads/julia-1.8.5/bin
  JULIA_BINDIR = /home/twilliams/Downloads/julia-1.8.5/bin
  JULIA_LIBRARY_DIR = /home/twilliams/Downloads/julia-1.8.5/bin
  JULIA_NUM_THREADS = 16
```

I'm not entirely sure how Julia 1.6.5 was installed on my system, as our IT department did it during the imaging process. Julia 1.8.5 was downloaded from https://julialang.org/downloads/ and extracted into a directory.

I was able to fix the immediate issue on our end by replacing `hash(read("filename.xml"))` with `crc32c(read("filename.xml"))`.

**Comment by gbaraldi** [comment]
This is kind of known since we sample the array when hashing it https://github.com/JuliaLang/julia/blob/d72a9a1d2a2bd181cabd5294f21ef3242dd09efd/base/abstractarray.jl#L3404-L3420

**Comment by vtjnash** [comment]
Hash is not required to change because of. `crc32c` is often not expected to change either (since it is common to put a crc32 value at the end of the file, which reset the crc32c to 0 at that place). The SHA package is more appropriate to use for content-based hashes.
