### ISSUE TITLE
Generators as "Array Initializers" 

### ISSUE THREAD

**Issue by uniment** [JuliaLang/julia#48623]
(Related [Discourse discussion](https://discourse.julialang.org/t/generator-as-an-array-initializer/93379))

This would be nice:

```julia
y = Array{Float64}(i+j for i=1:m, j=1:n)
y == Float64[i+j for i=1:m, j=1:n] # true
```

Would passing generators to the `Array` constructor be redundant with comprehensions? Yes. Why request it then? Because a) it'd create consistency with the fact that other similar constructors also accept generators (e.g. `Tuple`, `NamedTuple`, `Dict`, etc.), and b) it creates an idiom for non-standard arrays to be constructed with generators.

**Comment by rfourquet** [comment]
I would hope to not limit this feature to only generators, but any iterators. It would also provide an idiomatic solution to #47777: `Vector{Float64}(rand(2, 2))`, or `Vector(rand(2, 2))`, is probably the most stragithforward way to say "give me a vector out of this matrix".

**Comment by uniment** [comment]
> any iterators

This seems like a disjoint feature, but maybe not a bad idea? Can you open a separate issue for it?

**Comment by vtjnash** [comment]
Yes, this is redundant with the definition of `collect` also, and also that yes we should finally implement this, as we already did for other constructors as you noted

**Comment by nsajko** [comment]
dup of #16029
