### ISSUE TITLE
`TerminalMenus` restricted to old `Compat`

### ISSUE THREAD

**Issue by jonniediegelman** [JuliaLang/julia#48646]
`TerminalMenus` is upper bound to a version of `Compat` from a year and a half ago. This makes it incompatible with a lot of different packages with a lower bound on `Compat` ([this issue](https://github.com/JuliaIO/HDF5.jl/issues/1050), for example).

```
(@v1.8) pkg> activate --temp
...

(jl_EtiLjH) pkg> add Compat TerminalMenus
...

(jl_EtiLjH) pkg> st --outdated
Status `/private/var/folders/c_/6fjxlc6d2gl2hf2hdzl004q80000gp/T/jl_EtiLjH/Project.toml`
⌅ [34da2185] Compat v2.2.1 (<v4.6.0): TerminalMenus

(jl_EtiLjH) pkg> add Compat@4.6
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Compat [34da2185]:
 Compat [34da2185] log:
 ├─possible versions are: 1.0.0-4.6.0 or uninstalled
 ├─restricted to versions 4.6 by an explicit requirement, leaving only versions 4.6.0
 └─restricted by compatibility requirements with TerminalMenus [dc548174] to versions: 1.0.0-2.2.1 — no versions left
   └─TerminalMenus [dc548174] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0
```

**Comment by DilumAluthge** [comment]
This is an issue with the TerminalMenus.jl package, and should be opened there: https://github.com/nick-paul/TerminalMenus.jl

Note: there is no stdlib named `TerminalMenus`, as can be seen here: https://github.com/JuliaLang/julia/tree/master/stdlib

Therefore, if you do `] add TerminalMenus`, this is going to give you the TerminalMenus.jl package.

**Comment by DilumAluthge** [comment]
There is a submodule named `REPL.TerminalMenus`, but this is not its own stdlib, but rather a submodule of the `REPL` stdlib.
