### ISSUE TITLE
Cannot spawn task on interactive thread after starting Julia 1.9.0-beta4 with `-t1,1`

### ISSUE THREAD

**Issue by simsurace** [JuliaLang/julia#48644]
The CLI help for `-t` states:
```
-t, --threads {auto|N[,auto|M]}
       Enable N[+M] threads; N threads are assigned to the `default`
       threadpool, and if M is specified, M threads are assigned to the
       `interactive` threadpool...
```
So I would expect to be able to spawn a task on the interactive thread when starting Julia with `-t1,1` (one default and one interactive thread). But this fails on Julia 1.9.0-beta4:

```
$ julia +beta -q -t1,1

julia> fetch(Threads.@spawn :interactive Threads.threadpool())
:default
```
It works when starting Julia with `-t2,1` (two default and one interactive thread):
```
$ julia +beta -q -t2,1

julia> fetch(Threads.@spawn :interactive Threads.threadpool())
:interactive
```
I think this is a bug.
```julia
julia> versioninfo()
Julia Version 1.9.0-beta4
Commit b75ddb787ff (2023-02-07 21:53 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 2 on 8 virtual cores
```

**Comment by simsurace** [comment]
I did some digging and I believe there is a bug in https://github.com/JuliaLang/julia/blob/45b7e7ab2b6ec90dfa4b4f156c5c5d77ebe28b8b/src/partr.c#L71-L77

Setting the threadpool does not work, but setting the thread id works:
```
$ julia +beta -q -t1,1

julia> test(set_threadpoolid!)
:default

julia> test(set_threadid!)
:interactive
```

where

```julia
set_threadpoolid!(task) = ccall(:jl_set_task_threadpoolid, Cint, (Any, Int8), task, Int8(1))
set_threadid!(task) = ccall(:jl_set_task_tid, Cint, (Any, Int16), task, Int16(1))

function test(f)
    task = @task Threads.threadpool()
    task.sticky = false
    f(task)
    schedule(task)
    return fetch(task)
end
```

**Comment by simsurace** [comment]
@jpsamaroo You might be able to help.

**Comment by jpsamaroo** [comment]
@kpamnany

**Comment by kpamnany** [comment]
This is a bug introduced by https://github.com/JuliaLang/julia/pull/46609, [here](https://github.com/JuliaLang/julia/commit/b7201d6b460df74f024a6f19f837437a2c0613d1#diff-32f72b7e244562a3772085ca0dedcd4b717dd0be3535f73959b31e841f46d0aaL770-R770). Previously, `nthreads()` returned the total number of threads in all the threadpools, so the `if` check would fail. Now, `threadpoolsize()` returns the number of threads in the default thread pool only, which is 1 for the breaking case.

Looks like `nthreads()` was deprecated _and_ changed to mean `nthreads(:default)` (which seems like a bad change) which is presumably why it was replaced with `threadpoolsize()`, but it probably should have been replaced with `maxthreadid()`?

Cc: @vtjnash and @vchuravy

**Comment by simsurace** [comment]
See related discussions https://github.com/JuliaLang/julia/pull/48589 and https://github.com/JuliaLang/julia/pull/48643

**Comment by simsurace** [comment]
I do not know how best to fix this, but I would think it is important to
- Put this on the 1.9 milestone
- Add a test workflow to the CI to detect this type of bug

I could contribute the second item, but I'm unfamiliar with this project's CI pipelines. Where are they defined? Where would such a workflow go (e.g. starting Julia with different thread configurations and checking for correct behavior)?

**Comment by kpamnany** [comment]
Thanks for the good report @simsurace.

**Comment by simsurace** [comment]
My pleasure
