### ISSUE TITLE
Unable to add any package

### ISSUE THREAD

**Issue by pranphy** [JuliaLang/julia#48647]
When trying to install any julia packages I get segfault error. This happened to me for  three different versions of julia I tried.  From popos repository (1.8.4), the julia 1.8.5 binary I got from julia download website and the fresh compilation of julia from here at github. Since this happened with three different versions of julia, I doubt that it might be issue with my system library rather than julia itself but I am not sure where else to ask this. Also the error message is not terribly helpful.
```
myuser@hots:~ $ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.5 (2023-01-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.8) pkg> add Plots
  Installing known registries into `~/.julia`

signal (11): Segmentation fault
in expression starting at none:0
__pthread_mutex_init at /usr/lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fd45f108203)
mbedtls_entropy_init at /usr/lib/x86_64-linux-gnu/libmbedcrypto.so.7 (unknown line)
mbed_connect_common at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
Curl_ssl_connect_nonblocking at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
https_connecting at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
Curl_http_connect at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
multi_runsingle at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
multi_socket at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
curl_multi_socket_action at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
curl_multi_socket_action at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:48 [inlined]
curl_multi_socket_action at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:56 [inlined]
macro expansion at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28 [inlined]
#41 at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:176
lock at ./lock.jl:185
macro expansion at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:174 [inlined]
#40 at ./task.jl:484
jfptr_YY.40_66974.clone_1 at /home/pranphy/st/opt/julia-1.8.5/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2559
jl_apply at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
start_task at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/task.c:931
Allocations: 2909 (Pool: 2895; Big: 14); GC: 0
Segmentation fault (core dumped)

myuser@hots:~ $
```

**Comment by giordano** [comment]
> Since this happened with three different versions of julia, I doubt that it might be issue with my system library rather than julia itself but I am not sure where else to ask this.

I think that's the issue because the segfault happens in `/usr/lib/x86_64-linux-gnu/libmbedcrypto.so.7`. Do you have any of the `LD_*` environment variables set, like `LD_LIBRARY_PATH` or `LD_PRELOAD`?

**Comment by x0samnan** [comment]
@pranphy Can you let me know, which linux distro are you using and if you have changed the kernel, let me know that too.

**Comment by x0samnan** [comment]
> When trying to install any julia packages I get segfault error. This happened to me for three different versions of julia I tried. From popos repository (1.8.4), the julia 1.8.5 binary I got from julia download website and the fresh compilation of julia from here at github. Since this happened with three different versions of julia, I doubt that it might be issue with my system library rather than julia itself but I am not sure where else to ask this. Also the error message is not terribly helpful.
> 
> ```
> myuser@hots:~ $ julia
>                _
>    _       _ _(_)_     |  Documentation: https://docs.julialang.org
>   (_)     | (_) (_)    |
>    _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 1.8.5 (2023-01-08)
>  _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
> |__/                   |
> 
> (@v1.8) pkg> add Plots
>   Installing known registries into `~/.julia`
> 
> signal (11): Segmentation fault
> in expression starting at none:0
> __pthread_mutex_init at /usr/lib/x86_64-linux-gnu/libc.so.6 (unknown line)
> unknown function (ip: 0x7fd45f108203)
> mbedtls_entropy_init at /usr/lib/x86_64-linux-gnu/libmbedcrypto.so.7 (unknown line)
> mbed_connect_common at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> Curl_ssl_connect_nonblocking at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> https_connecting at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> Curl_http_connect at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> multi_runsingle at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> multi_socket at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> curl_multi_socket_action at /home/pranphy/st/opt/julia-1.8.5/bin/../lib/julia/libcurl.so (unknown line)
> curl_multi_socket_action at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:48 [inlined]
> curl_multi_socket_action at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:56 [inlined]
> macro expansion at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28 [inlined]
> #41 at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:176
> lock at ./lock.jl:185
> macro expansion at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:174 [inlined]
> #40 at ./task.jl:484
> jfptr_YY.40_66974.clone_1 at /home/pranphy/st/opt/julia-1.8.5/lib/julia/sys.so (unknown line)
> _jl_invoke at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2377 [inlined]
> ijl_apply_generic at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/gf.c:2559
> jl_apply at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/julia.h:1843 [inlined]
> start_task at /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/src/task.c:931
> Allocations: 2909 (Pool: 2895; Big: 14); GC: 0
> Segmentation fault (core dumped)
> 
> myuser@hots:~ $
> ```

@pranphy Can you let me know, which linux distro are you using and if you have changed the kernel, let me know that too.

**Comment by pranphy** [comment]
@giordano  Emptying my  `LD_LIBRARY_PATH=""` solved the issue. 
@x0samnan I am on Pop!_OS 22.04 LTS x86_64  and haven't modified my kernel or anything.
