### ISSUE TITLE
Carry patch to avoid excessive LLVM time

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#48681]
We should carry the patch in https://github.com/llvm/llvm-project/issues/60132. It doesn't look like there's a good patch forthcoming any time soon and the optimization that gets disabled there is minor. @vchuravy can you do this with the next LLVM bump?

**Comment by gbaraldi** [comment]
There's a comment here 
> hasPredecessorHelper already takes an optional MaxSteps limit that we could make use of
Could we keep the optimization put not be pathological about it? Or is the case that even with limiting that we still get bad performance?

**Comment by vchuravy** [comment]
Do you need this backported to 1.9?

**Comment by oscardssmith** [comment]
no.

**Comment by pepijndevos** [comment]
Is this just a matter of dunking the patch in the right folder or more involved? We can't really run some tests in CI until this gets done.

**Comment by staticfloat** [comment]
X-ref: https://github.com/JuliaLang/llvm-project/pull/14
