### ISSUE TITLE
Clearer error message when unable to determine exact type parameter value in a method

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#48731]
It is possible to define methods where Julia is unable to determine a concrete value for a type parameter, leading to a `UndefVarError`:

```julia
julia> foo(::Ref{<:T}) where T = T
foo (generic function with 1 method)

julia> foo(Ref{String}())
String

julia> foo(Ref{AbstractString}())
ERROR: UndefVarError: `T` not defined
```

The error is confusing since, from a user's perspective, `T` is very much defined/declared in the `where` part of the method definition.

Rather, could we throw a dedicated `AmbiguousTypeParameter` error here (bikeshed, please)? Preferably with a docstring that would explain that it's possible to construct signatures where you can't uniquely figure out a type. And would also probably suggest avoiding unnecessary subtyping in method signature (like in the `Ref{<:T}` example above), since that is most likely an error on the user's part.

A couple of related issues I was able to find: https://github.com/JuliaLang/julia/issues/25307, https://github.com/JuliaLang/julia/issues/39277, https://github.com/JuliaLang/julia/issues/39280, https://github.com/JuliaLang/julia/issues/41841, https://github.com/JuliaLang/julia/issues/41728. It also caused some discussion [on Zulip recently](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/.E2.9C.94.20Spooky.20error.20with.20parametric.20types.20in.20tuples).

_While for a different issue, the hints in https://github.com/JuliaLang/julia/issues/34393 might also help with the implementation here._

**Comment by vtjnash** [comment]
Also related to #25263
