### ISSUE TITLE
Uninformative Error Message for mistyped function name

### ISSUE THREAD

**Issue by marcosmolla** [JuliaLang/julia#48754]
Hi, 

I've just recently moved back to coding in Julia and I am battling a bit with decoding Error messages. I wanted to share this one because it really kept me searching for about 15 minutes what the actual problem was:

```julia
julia> dict(1 => [1 6])
ERROR: MethodError: objects of type Dict{Int64, Matrix{Int64}} are not callable
Stacktrace:
 [1] top-level scope
   @ REPL[20]:1

julia> Dict(1 => [1 6])
Dict{Int64, Matrix{Int64}} with 1 entry:
  1 => [1 6]
```

Above is the code I started with and the error message that appeared. I thought I am doing something wrong with the values I supplied to the key. But that wasn't the issue at all. It should be `Dict` and not `dict`. It would have been plenty useful to have an error message like `Could not find function "dict"`

Using Julia Version 1.8.5 (2023-01-08). Installed with Homebrew. 

I'll get used to error messages from Julia, probably. I am just saying that it could be easier for the beginner if the error message was more informative. 

All the best wishes!

PS: Why is the `Dict` function capitalised anyway? Aren't most functions lower case?

**Comment by sostock** [comment]
> ```julia
> julia> dict(1 => [1 6])
> ERROR: MethodError: objects of type Dict{Int64, Matrix{Int64}} are not callable
> ```

This error message only appears if you previously defined a variable with the name `dict` (in this case, a variable of type `Dict{Int64, Matrix{Int64}}`). In a new session, the following error is thrown instead (quite similar to the error message you are proposing):
```julia
julia> dict(1 => [1 6])
ERROR: UndefVarError: dict not defined
[...]
```

> PS: Why is the `Dict` function capitalised anyway? Aren't most functions lower case?

`Dict` is a type, and types are capitalised. When you call `Dict(1 => [1 6])`, you are calling a constructor of the `Dict` type.

**Comment by marcosmolla** [comment]
Hi sostock,
Thanks for the speedy reply! 
You are absolutely right, I did create that variable before. In that case, julia couldn't just say that it doesn't exist (as a function) because I created it as a variable before. Alright, I hope I'll catch that in the future. 
And thanks for the reminder that this is a type, like `Int()`. Makes sense! 
Thank you!
