### ISSUE TITLE
Pkg: migrate versioned package directory after version update

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#4876]
After the update from v0.2 to v0.3, the few of us (?) who have versioned package directories suddenly can't see our packages (because we don't have a `.julia/v0.3` directory).

When running an updated version of julia for the first time, it would be nice to have a way create and migrate packages from the previous version.

**Comment by IainNZ** [comment]
:-1: on this feature. @kmsquire, do you still want this?

**Comment by jakebolewski** [comment]
I don't think we want to support this feature.

**Comment by tkelman** [comment]
I think the time-saving way to do this is by copying `~/.julia/v0.3/REQUIRE` to `~/.julia/v0.4/REQUIRE` then doing a resolve or update.

**Comment by kmsquire** [comment]
Something like @tkelman's suggestion would be nice, although it should be opt-in--maybe some function in Pkg?  Maybe `Pkg.migrate()` (with a flock of ascii birds on the screen as it does its thing)?
