### ISSUE TITLE
`Float` arguments for `Rational`

### ISSUE THREAD

**Issue by vmpyr** [JuliaLang/julia#48770]
Currently `Rational` declarations don't work for `Floats` arguments. Something like this doesn't work:
```julia
julia> 2.2//3
ERROR: MethodError: no method matching //(::Float64, ::Int64)

Closest candidates are:
  //(::Integer, ::Integer)
   @ Base rational.jl:62
  //(::Rational, ::Integer)
   @ Base rational.jl:64
  //(::Complex, ::Real)
   @ Base rational.jl:78
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```

As far as I can understand, the reason for this is because we will need the rational representation of the float in order to accomplish this. Maybe we can do that for terminating decimals numbers? Maybe we can `rationalize` the float value before passing it as an argument as illustrated [here](https://stackoverflow.com/a/35414995).

**Comment by petvana** [comment]
Xref https://discourse.julialang.org/t/float-rational-numbers/37856

**Comment by vmpyr** [comment]
@petvana
Makes sense. For anyone else interested, please refer to the discourse discussion link in the previous comment. I'll close this issue now.
