### ISSUE TITLE
Buggy interaction between `@eval` and `delete_method`

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#48802]
I could be missing something, but this seems bad to me:
```julia
julia> function track()
           @eval function Base.getindex(A::Array{Int}, i1::Int)
               println("A")
               invoke(getindex, Tuple{Array, Int}, A, i1)
           end
       end
track (generic function with 1 method)

julia> function cleanup()
           Base.delete_method(which(getindex, Tuple{Array{Int},Int}))
       end
cleanup (generic function with 1 method)

julia> [1,7,3][2]
7

julia> track()

julia> [1,7,3][2]
A
7

julia> cleanup()

julia> [1,7,3][2]
7

julia> track()

julia> [1,7,3][2]
7
```
I would expect to be able to resume tracking again after cleanup. I.e. the final output should also include "A". Replacing `getindex` with `sin` does not reproduce this issue.

**Comment by LilithHafner** [comment]
This bug is present on 1.9.0-beta4 but not on 1.8.5.

**Comment by vtjnash** [comment]
Apparently code got added in dd375e199b6 which prohibits replacing any method which has been called via `invoke`. That prohibition should not be there. Will make a fix.
