### ISSUE TITLE
installing julia through conda on Windows

### ISSUE THREAD

**Issue by ericqu** [JuliaLang/julia#48825]
Apologies if there is a better place to post this issue; please indicate where this should be directed if incorrect.

It is an enhancement request.

I need to install Julia through anaconda while on a windows platform ([julia on anaconda](https://anaconda.org/conda-forge/julia)), but it does not include the win-64 label.

Ideally, it would be like the rust entry (with regards to the win-64 label): [rust on anaconda](https://anaconda.org/conda-forge/rust).

**Comment by inkydragon** [comment]
You may want to file an issue in https://github.com/conda-forge/julia-feedstock
Note: conda is not the recommended way to install Julia.

**Comment by ericqu** [comment]
Thanks, I will do that. 
Yes, I know it is not recommended, but while I don't want to, I need to install it this way.
