### ISSUE TITLE
Ref{Array} has inconsistent behavior depending on the position of its arguments.

### ISSUE THREAD

**Issue by nahaharo** [JuliaLang/julia#48823]
## Minimum working example
This works
```julia
function prod1(x,y)
    return map(f -> f(y), x)
end
x = Ref([r->r,r->2*r,r->3*r])
prod1.(x,[1,2,3])
```
This fails
```julia
function prod2(y;x)
    return map(f -> f(y), x)
end
x = Ref([r->r,r->2*r,r->3*r])
prod2.([1,2,3];x=x)
```

## Version Info
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen Threadripper PRO 3955WX 16-Cores
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 32 virtual cores
Environment:
  LD_LIBRARY_PATH = /usr/local/nvidia/lib:/usr/local/nvidia/lib64

**Comment by pablosanjose** [comment]
But this is expected. Broadcast works over positional arguments. This has nothing to do with Ref, I think.
```julia
julia> myplus(x, y) = x + y; myplus2(x; y) = x + y;

julia> myplus.([1,2,3], [2,3,4])
3-element Vector{Int64}:
 3
 5
 7

julia> myplus2.([1,2,3], y = [2,3,4])
ERROR: MethodError: no method matching +(::Int64, ::Vector{Int64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
```
