### ISSUE TITLE
broadcast picking incorrect result type

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#4883]
The following code fails with an `InexactError()`:
```
X = [1,2,3]
Y = [4 5]
broadcast(atan2, X, Y)
```
whereas
```
[atan2(x,y) for x in X, y in Y ]
```
(albeit producing an array of type `Any`), while
```
atan2([1,2,3],[4,5,6])
```
produces an array of `Float64`.

Can we improve the type inference so that all three cases can generate `Float64` arrays?  Note that this is needed for #4363 (for `@vectorize_2arg` to use `broadcast`).

**Comment by stevengj** [comment]
Duplicate of #16164

**Comment by stevengj** [comment]
As I commented in #16164, it seems that `map` is now able to do the right thing, so we need to adapt the `map` algorithm to `broadcast`.

**Comment by StefanKarpinski** [comment]
I hate to add an issue to the 0.5 milestone, but introducing a new syntax and encouraging its use, while it's this broken seems like a bad idea. See https://github.com/JuliaLang/julia/issues/16896; possibly fixed by https://github.com/JuliaLang/julia/pull/16260?

**Comment by timholy** [comment]
#16260 cleans up broadcast (gets rid of the "stash eval-ed functions in dictionaries", aka fake `@generated` functions), but unfortunately doesn't address the eltype.

**Comment by StefanKarpinski** [comment]
Broadcasting, map and comprehensions should all pick the same element type and succeed/fail in the same cases, except that broadcast handles more combinations of argument shapes.

**Comment by Sacha0** [comment]
> map is now able to do the right thing, so we need to adapt the map algorithm to broadcast.

Ref. peripherally related julia-users thread https://groups.google.com/forum/#!searchin/julia-users/broadcast$20map/julia-users/IAZSOCZg1ww/TOvwOZBEAwAJ

**Comment by pabloferz** [comment]
AFAICT, the first example works now on master.

```
X = [1,2,3]
Y = [4 5]

julia> broadcast(atan2, X, Y)
3×2 Array{Float64,2}:
 0.244979  0.197396
 0.463648  0.380506
 0.643501  0.54042
```

**Comment by JeffBezanson** [comment]
Ah, that appears to be due to which `promote_op` definitions exist.

**Comment by pabloferz** [comment]
Exactly, I'm trying to complete and organize them on  #16986.

**Comment by stevengj** [comment]
`broadcast(sin, [1,2,3])` still fails with an `InexactError` (because it erroneously thinks the array is an `Int` array), whereas `map(sin, [1,2,3])` succeeds.

**Comment by stevengj** [comment]
(Other good test cases are `broadcast(length, ["foo", "bar"])` or `broadcast(length, [[1,2,3], [5]])`.   We need to make sure that the solution is as general as in `map`, not restricted to numeric types.)
