### ISSUE TITLE
Poor performance of `vcat`/`hcat`/`hvcat` on mixed input types

### ISSUE THREAD

**Issue by mikmoore** [JuliaLang/julia#48850]
From [this Discourse thread](https://discourse.julialang.org/t/switching-two-elements-in-array-vcat-getting-flagged-as-runtime-dispatch/95407).

On version 1.8.0 (sorry it's what i have handy, but the offending method appears unchanged on current `master`):
```julia-repl
julia> using BenchmarkTools

julia> x = 1; y = 2:2;

julia> @btime vcat($x, $x);
  26.506 ns (1 allocation: 80 bytes)

julia> @btime vcat($y, $y);
  28.744 ns (1 allocation: 80 bytes)

julia> @btime vcat($x, $y);
  2.667 μs (35 allocations: 1.05 KiB)
```
with similar results for `hcat` and `hvcat`.

An initial inspection suggests that the offending methods for `vcat`/`hcat` are `LinearAlgebra._vcat(A::Union{Number, LinearAlgebra.UniformScaling, AbstractVecOrMat}...; array_type)` and the matching `_hcat`, which are (as of this writing) defined at [uniformscaling.jl#L426](https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/uniformscaling.jl#L426). A loop over the input vararg tuple appears to cause dynamic dispatch.

`hvcat` has the same problem, likely arising from a similar loop in [uniformscaling.jl#446](https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/uniformscaling.jl#L446).

**Comment by dkarrasch** [comment]
I guess I'm and #41394 are to blame. GitHub says that will only released as v1.9, but I do find the corresponding code in v1.8.x. I think I have a solution to this, will make a PR soon.
