### ISSUE TITLE
bug in closure capture boxing logic

### ISSUE THREAD

**Issue by uniment** [JuliaLang/julia#48889]
Notice that `foo()` returns `3`.
```julia
julia> VERSION
v"1.9.0-beta4"

julia> foo=let j=0, f, i
           while j < 3
               i = j + 1
               println("i == ", i)
               if j==0;  f = ()->i  end
               j += 1
           end
           i
           f
       end;
i == 1
i == 2
i == 3

julia> foo()
3
```
Comment out the line that says `i`, and `foo()` instead returns `1` (and its capture is not in a `Core.Box` anymore).

(ref: [Discourse thread](https://discourse.julialang.org/t/rfc-some-ideas-to-tackle-15276-performance-of-captured-variables-in-closures/95260/42?u=uniment))

**Comment by uniment** [comment]
Worth noting that this was first observed using `@goto`:

```julia
julia> baz = let j=0
           @label upper
           i = j + 1
           println("i == ", i)
           if j != 0; @goto lower end
           f = ()->i
           @label lower
           j += 1
           if j < 3; @goto upper end
           #i
           f
       end;
i == 1
i == 2
i == 3

julia> baz()
1
```

**Comment by simeonschaub** [comment]
3 is the correct answer here, since the binding `i` exists outside the scope of the while loop as well. What I'm slightly surprised by is that `let i; ... end` is not enough to make `i` an outer binding if you comment out the `i` line.
