### ISSUE TITLE
Profiling: Provide better visibility into CPU/data usage for pkgimages

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#48921]
We'd like to break down precompilation time by method/instance and to break down timings among the various precompilation pipeline steps (inference, codegen, etc.). Motivating case: 5-10min precompilation for OrdinaryDiffEq that we desperately want to fix.

For data, PkgCacheInspector provides a very helpful summary:
```
Contents of /Users/chrisrackauckas/.julia/compiled/v1.9/OrdinaryDiffEq/DlSvy_JtLlA.dylib:
  modules: Any[OrdinaryDiffEq]
  2986 external methods
  14390 new specializations of external methods (Base 60.2%, Base.Broadcast 16.4%, SciMLBase 10.8%, ...)
  765 external methods with new roots
  25884 external targets
  29517 edges
  file size:   125486880 (119.674 MiB)
  Segment sizes (bytes):
  system:      27186976 ( 24.28%)
  isbits:      81631571 ( 72.92%)
  symbols:       140328 (  0.13%)
  tags:          381105 (  0.34%)
  relocations:  2529014 (  2.26%)
  gvars:          22712 (  0.02%)
  fptrs:          61648 (  0.06%)
```
but we'd like a convenient view that breaks down the `system`/`isbits` portions of the pkgimage into their component entities, sorted by size.

**Comment by topolarity** [comment]
For now, I'm also going to track here my efforts with @YingboMa to profile run-time compilation (and re-compilation), as well.

Many of the CPU needs are already partially covered by `@snoopl`, `@snoopi`, `@snoopc` and family.

The main task here is to (1) figure out how to make these measurements available for precompilation without manual instrumentation, (2) make sure that we are covering all major parts of the pipeline to account for the full OrdinaryDiffEq precompilation time, and optionally (3) to provide a unified view of the CPU during precompilation and/or integrate with a timeline profiler like Tracy.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/julia/pull/49140
