### ISSUE TITLE
GC: Large amounts of GC time spent scanning permanent pkgimage allocations

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#48923]
On current Julia master, 40% of our time in `using DeepPumas` is spent in GC:
```
114.447107 seconds (144.80 M allocations: 11.006 GiB, 43.24% gc time, 24.67% compilation time: 61% of which was recompilation)
```

OmniPackage similarly spends ~30% of its time in the GC, and the GC mark phase seems to be the primary culprit.

@vtjnash suspects that this GC time is largely spent scanning over the pkgimage objects, and that we might be able to reduce it.

**Comment by vchuravy** [comment]
Do you have a profile to share? PProf or Vtunes?

**Comment by gbaraldi** [comment]
Loading https://github.com/JuliaComputing/OmniPackage.jl has very similar results just for reference.

**Comment by chriselrod** [comment]
Yes, OmniPackage is almost as big as DeepPumas, and should therefore should be able to serve as an open source reproducer.

**Comment by JeffBezanson** [comment]
Iterating over the list of loaded package images for ~every object mark is totally unacceptable. We cannot just casually tank GC performance like this.

**Comment by KristofferC** [comment]
Can someone explain why we need to iterate over the loaded package images in 1.9 but we didn't need to do the equivalent on 1.8? Naively, it doesn't feel like the precompile format should change the work the GC has to do.

**Comment by JeffBezanson** [comment]
Could we just not treat package image data as permanent for now? It does not seem to be worth the cost (though an experiment might be in order).

**Comment by vchuravy** [comment]
Just packages or also sysimg?

**Comment by JeffBezanson** [comment]
Same question applies to both of course, but making the sysimg permanent is cheap since checking for that is O(1).

**Comment by KristofferC** [comment]
Looking at https://github.com/JuliaLang/julia/pull/49185#issuecomment-1490172521, this seems fixed.
