### ISSUE TITLE
Cannot see `Out` prompt in REPL in v1.9.0-rc1 after setting code in startup.jl

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#48945]
Sorry, I put the following lines in my `startup.jl` as suggested in #46474 and [docs](https://github.com/JuliaLang/julia/blob/v1.9.0-rc1/stdlib/REPL/docs/src/index.md) but I do not see `Out[1]` printed:

```julia
using REPL
atreplinit() do repl
    if !isdefined(repl, :interface)
        repl.interface = REPL.setup_interface(repl)
    end
    REPL.ipython_mode!(repl)
end
```

<img width="262" alt="image" src="https://user-images.githubusercontent.com/25192197/220806641-9c6e01e4-10f6-41de-bfc1-f7d0c84e3cce.png">

Am I using it wrongly?

```julia
julia> versioninfo()
Julia Version 1.9.0-rc1
Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by singularitti** [comment]
OK, it turns out that I have the following lines also in my `startup.jl` and they change how prompt is displayed:

```julia
using OhMyREPL
colorscheme!("Monokai16")
enable_autocomplete_brackets(false)
```

Could this be avoided @KristofferC? I want to have them both in my `startup.jl`.

**Comment by KristofferC** [comment]
Yeah, this is an OhMyREPL.jl issue. We can follow up there.
