### ISSUE TITLE
Tests passing on julia v1.9.0-rc1 - push to General?

### ISSUE THREAD

**Issue by pat-alt** [JuliaLang/julia#48952]
More of a question than an issue, but still opening here as per the [post](https://discourse.julialang.org/t/julia-v1-9-0-rc1-is-now-available/95691) on Discourse.

I've just bumped up the Julia version entry for some of my Julia packages added `~1.9.0-0` to my GitHub CI. I then pushed changes and it appears that all tests are passing (see [here](https://github.com/JuliaTrustworthyAI/ConformalPrediction.jl/actions/runs/4364450911/jobs/7631784344)). 

Two questions: 

1. Is this the right way to try out the candidate release? 
2. Can I now safely push this to General (and should I)?

Thanks in advance for your help!

**Comment by KristofferC** [comment]
1. Yes
2. You don't have to "push" anything to General just because you test your package on a new Julia version. But now you know that it works on the upcoming Julia version.
