### ISSUE TITLE
Docs on `JULIA_NUM_THREADS` env var should mention threadpools

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/julia#48960]
i was looking for docs on what `JULIA_NUM_THREADS=8,1` means, and navigated to https://docs.julialang.org/en/v1.9.0-rc1/manual/environment-variables/#JULIA_NUM_THREADS where i expected this is be explained

It _is_ explained over in the multi-threading part of the manual at https://docs.julialang.org/en/v1.9.0-rc1/manual/multi-threading/#man-threadpools (and i also found https://github.com/JuliaLang/julia/pull/42302#issuecomment-1072785204), but it'd be good to mention on the env vars page too i think

**Comment by TakshDhabalia** [comment]
made a small PR , open to some suggestions and comments on the same
