### ISSUE TITLE
Change in Documentation for Conversion-and-Promotion.md 

### ISSUE THREAD

**Issue by TakshDhabalia** [JuliaLang/julia#48972]
As mentioned on Slack (https://julialang.slack.com/archives/C6A044SQH/p1678531853842819) by Robert has opened a small change which could be to add some changes from the Issue (https://github.com/JuliaLang/julia/issues/9292#issuecomment-943740160) (courtesy - Valentin (NOT vchuravy) )

It is to add that the 
The result type is the larger of the two argument types
If both argument types are the same size and differ in signdness, then the unsigned type wins
and also to add that the two argument largness is the import factor in the above

**Comment by TakshDhabalia** [comment]
If approved , I will start work on the issue right away

**Comment by robertfeldt** [comment]
Thanks. I already did a PR, here:

https://github.com/JuliaLang/julia/pull/48973

**Comment by TakshDhabalia** [comment]
Closed as PR done
