### ISSUE TITLE
`isequal(0.0, 0im) && isequal(0im, -0.0)`: problem with isequal on Complex zero

### ISSUE THREAD

**Issue by grahamgill** [JuliaLang/julia#48987]
In the `isequal` doc:
> `isequal` is an equivalence relation - it is ... transitive

and
> `isequal(x,y)` must imply that `hash(x) == hash(y)`

But 
`hash(0.0) == hash(0im) != hash(-0.0)`,
whereas
`!isequal(0.0, -0.0) && isequal(0.0, 0im) && isequal(0im, -0.0)`.

By way of contrast, `!isequal(0, -0.0)`.

Sorry if this has already been submitted. Reading about why `!isequal(0.0, -0.0)` but `isequal` is `true` on different `NaN` representations took me down a real (interesting) rabbit hole, but I didn't see the problem above mentioned anywhere.

**Comment by Seelengrab** [comment]
Note that you're mixing floating point and integer `Complex`:

```
julia> typeof(0im)
Complex{Int64}

julia> typeof(0.0im)
ComplexF64 (alias for Complex{Float64})
```

**Comment by martinholters** [comment]
That's a red herring, the problem also manifests itself using only `Float64`:
```julia
julia> isequal(0.0, 0.0im) && isequal(0.0im, -0.0)
true

julia> isequal(0.0, -0.0) # should be true by transitivity
false

julia> hash(0.0im) == hash(-0.0) # should be true as isequal(0.0im, -0.0) is
false
```

**Comment by Seelengrab** [comment]
Why? `isequal(0.0, -0.0)` is documented to be `false`:

> help?> isequal
> search: isequal issetequal
> 
>   isequal(x, y)
> 
>   Similar to ==, except for the treatment of floating point numbers and of missing values. isequal treats all
>   floating-point NaN values as equal to each other, **treats -0.0 as unequal to 0.0**, and missing as equal to
>   missing. Always returns a Bool value.

(emphasis mine)

If anything, that suggests `isequal(0.0im, -0.0)` should be `false`, not `true`.

**Comment by martinholters** [comment]
Ah, sorry, I wasn't clear. I meant to say that if `isequal(0.0, 0.0im) && isequal(0.0im, -0.0)`, then `isequal(0.0, -0.0)` should hold; and if `isequal(0.0im, -0.0)`, then `hash(0.0im) == hash(-0.0)` should hold. But I agree that `isequal(0.0, -0.0)` being `false` is probably the right decision, so making `isequal(0.0im, -0.0)` give `false` might be the best way to resolve this, also considering that
```julia
julia> isequal(0.0im, -0.0)
true

julia> isequal(promote(0.0im, -0.0)...)
false
```

Note also that the current behavior has some unfortunate consequences like:
```julia
julia> allequal(Number[0.0im, 0.0, -0.0])
true

julia> allequal(Number[       0.0, -0.0])
false

**Comment by oscardssmith** [comment]
should be fixed by https://github.com/JuliaLang/julia/pull/48997
