### ISSUE TITLE
optimized reverse(::CartesianIndices, dims=...)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#49021]
`reverse` of `CartesianIndices` should produce another `CartesianIndices`.  Right now it does this for `reverse(I)`, but not if you use a `dims` keyword:
```jl
julia> I = CartesianIndices((3,4))
CartesianIndices((3, 4))

julia> reverse(I) # good!
CartesianIndices((3:-1:1, 4:-1:1))

julia> reverse(I, dims=1) # bad!
3×4 Matrix{CartesianIndex{2}}:
 CartesianIndex(3, 1)  CartesianIndex(3, 2)  …  CartesianIndex(3, 4)
 CartesianIndex(2, 1)  CartesianIndex(2, 2)     CartesianIndex(2, 4)
 CartesianIndex(1, 1)  CartesianIndex(1, 2)     CartesianIndex(1, 4)
```
Unfortunate, because this would be a [clean way to create reversed array views](https://discourse.julialang.org/t/reverse-view-of-an-array/9657/11).  (Although #37412 would be even more convenient.)

Seems like it should be really easy to add a specialized method here.

**Comment by TakshDhabalia** [comment]
I would dive in this straight away

**Comment by divyaS09** [comment]
I would like to contribute to resolving this issue. Please assign this issue to me.

**Comment by stevengj** [comment]
There is no assignment process.  You simply submit a PR.
