### ISSUE TITLE
ios.c fails to set errno

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#49038]
there is an error check in ios.c that read or write must be set, but it fails to set errno, so the message printed will be wrong
```
julia> open("VERSION", read=false, write=false)
ERROR: SystemError: opening file "VERSION": Undefined error: 0
```

**Comment by inkydragon** [comment]
julia & C code:
https://github.com/JuliaLang/julia/blob/0a9abc1919a69b7b4d668e3f841b53b186448e41/base/iostream.jl#L293-L296
https://github.com/JuliaLang/julia/blob/0a9abc1919a69b7b4d668e3f841b53b186448e41/src/support/ios.c#L934-L973
