### ISSUE TITLE
Add methods(fun) to the documentation of functions in Base

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#4903]
When I read the julia documentation I often have to switch to the terminal get the methods list for a function. Could this information be made available in a hidden form, so that i can just click/hoover something in the documentation to see `methods(myfunc)`.

It should preferably be automatically generated like the doctest functionality in https://github.com/JuliaLang/julia/pull/4897

This might also be useful https://github.com/JuliaLang/julia/issues/4902

**Comment by kshyatt** [comment]
Is this something we want to do? @MichaelHatherly?

**Comment by MichaelHatherly** [comment]
This kind of thing has some support in https://github.com/JuliaDocs/DocStringExtensions.jl, probably doesn't need to be part of base at the moment. Let's close this for now.
