### ISSUE TITLE
Option for turnning off pkgimage at package level

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#49040]
this is probably a quite specific case for the package MLStyle, but the latency cause by loading is huge

on 1.9-rc1

```julia
julia> @time using MLStyle
  0.158701 seconds (207.37 k allocations: 14.353 MiB, 27.57% gc time)
```

on 1.8

```julia
julia> @time using MLStyle
  0.051110 seconds (142.72 k allocations: 10.178 MiB, 12.49% gc time)
```

I think for MLStyle, it doesn't really need much compilation since most of the functions are just generating Julia `Expr`, we actually use things `@nospecialize` for certain functions in this package, so it'd be nice to have an option to turn off pkgimage for a certain package so we can be faster on loading, which is something actually matter for MLStyle because the code it generates is usually dependency free.

**Comment by timholy** [comment]
This does not seem feasible to implement. When you're using pkgimages, each package is stored as a compact blob in memory and cross-package references to individual objects are encoded via pointer-offsets. There's no good way to have a mixed system unless there are exactly zero interactions among the packages of each type.

The better way to handle this is just make loading faster. Folks are already working on that and making good progress.
