### ISSUE TITLE
Pkg: support common open source licenses

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4908]
See http://opensource.org/licenses. I don't think we should extend the list any further than this since I'm not keen on having packages with licenses outside of this set of fairly standard ones. Even some of these are a bit annoying – e.g. Apache 2 is incompatible with GPL 2. Perhaps we should only support GPL 2-compatible licenses. In any case, the keywords should be something along these lines:

- **Apache2**: Apache License 2.0
- **BSD3**: BSD 3-Clause "New" or "Revised" license
- **BSD2**: BSD 2-Clause "Simplified" or "FreeBSD" license
- **GPL2**, **GPL3**: GNU General Public License (GPL)
- **LGPL2**, **LGPL3**: GNU Library or "Lesser" General Public License (LGPL)
- **MIT**: MIT license
- **MPL2**: Mozilla Public License 2.0
- **CDDL1**: Common Development and Distribution License
- **EPL1**: Eclipse Public License

**Comment by tkelman** [comment]
`Pkg.generate` has been moved to PkgDev, closing here in favor of https://github.com/JuliaLang/PkgDev.jl/issues/46
