### ISSUE TITLE
Linear Algebra eigvals & eigvecs give answers in different orders

### ISSUE THREAD

**Issue by ejmeitz** [JuliaLang/julia#49157]
Hello,

I was using the LinearAlgebra package and noticed that eigvals() and eigvecs() do not necessarily report answers in the same order. e.g. eigenvalue 1 does not correspond to eigenvector 1. There's nothing in the documentation that says I should expect that to be the case, but in my opinion it makes much more sense to have it be that way. Or provide a function that returns both the eigenvalues and eigenvectors (sorry if I missed this I did not see one in the API).

Thanks,
Ethan

**Comment by ejmeitz** [comment]
scrolling more I found eigen()....I still think it would be useful for eigvals and eigvecs to always return in order of ascending eigenvalues though just to avoid random bugs.

**Comment by stevengj** [comment]
Can you give an example where this occurs?  I can't reproduce with a random matrix:
```jl
julia> using LinearAlgebra

julia> A = randn(1000,1000);

julia> F = eigen(A);

julia> F.values ≈ eigvals(A)
true

julia> F.vectors ≈ eigvecs(A)
true
```

**Comment by ejmeitz** [comment]
Yeah I cant reproduce it either, must have been hallucinating. 

Sorry to waste y'alls time.
