### ISSUE TITLE
variable numbers of keyword arguments as dict

### ISSUE THREAD

**Issue by WestleyArgentum** [JuliaLang/julia#4916]
``` julia
foo(; args...)
```

Inside of a function with this signature, `args` will be an array of tuples containing symbols and values. Cool, but the array will be unordered, so I pretty much have to loop over it trying to match symbols.

I think it would be really cool if `args` came in as a dictionary. I'm guessing there would be some overhead involved in that, and that's perhaps why it has not been done. But I wonder if the overhead involved in looping over symbols and doing a bunch of string comparisons (I think that's what's happening, could be wrong) might even outweigh the dict creation.

I didn't see an issue, but has this been considered?

**Comment by StefanKarpinski** [comment]
Varargs keywords will either be immutable dicts or named tuples, so this will be fixed in 1.0 one way or another.

**Comment by micklat** [comment]
Whatever you do, please preserve the argument order (so either a tuple or an ordered dictionary would keep me happy).

**Comment by ViralBShah** [comment]
Would be great to have an update on if this is happening by feature freeze. A PR exists in https://github.com/JuliaLang/julia/pull/21915, but that is not marked 1.0.

**Comment by JeffBezanson** [comment]
I'll update that PR to use named tuples.

**Comment by oscardssmith** [comment]
Doesn't that mean that every time you use a function with a different ordering of keyword arguments it will have to create a new specialization of Tupple? Is there any way around this?

**Comment by JeffBezanson** [comment]
Basically yes, but that won't necessarily be a problem in practice. We'll find out.
