### ISSUE TITLE
Add max_args specialization escape hatch

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#49172]
We currently have a heuristic

https://github.com/JuliaLang/julia/blob/6b934f91d1b9c50c5b783b6aa36cf2648999461c/src/gf.c#L1227

that decides how many specializations to generate for a varargs functions. It basically works as follows:

1. If this is one method of some generic functions, look at all the other methods for the same generic function and specialize up to two more than the maximum number of arguments to any other method of this generic function.
2. If not (e.g. it's some `(::Foo)(args...)` method), specialize up to vararg length of two.

There are several problems with this scheme:

1. It's somewhat ad-hoc and not always applicable. For example, we forcibly override the max_args for `invoke` here:
https://github.com/JuliaLang/julia/blob/6b934f91d1b9c50c5b783b6aa36cf2648999461c/base/Base.jl#L115

and for `afoldl` here:

https://github.com/JuliaLang/julia/blob/6b934f91d1b9c50c5b783b6aa36cf2648999461c/base/operators.jl#L578

2. Our general direction has been towards a single unified method table, in which case the per-mt `max_args` heuristic doesn't work anymore.

3. There's a bit of "spooky action at a distance" going on here where defining additional unrelated methods for a generic function can dramatically affect the performance of a different part of the code.

We should revisit this heuristic and see if we can come up with something that just look at the method itself (to start with, we could try just doing `nargs+1` for everything and see what happens) or maybe derives some information from an abstract inference of the function. In addition, we should an escape hatch to the `Method` object itself that allows overriding the max_method heuristic for use in some of the cases mentioned above.

**Comment by topolarity** [comment]
I've hit a bit of weirdness with how we specialize Varargs right now. For two arguments, we specialize over the following cases:
```
foo(::T, ::U) where {T,U}
foo(::T, ::Vararg{T}) where {T}
foo(::T, ::Vararg{Any}) where {T}
```

This includes quadratically-many methods (due to the first pattern), but if we have any past-the-end elements that get rolled into a Varargs, they are specialized only based on the preceding argument.

This is a little strange to me, but we can keep that behavior if we'd like. The question for this issue is how we want to define `max_varargs < 2`, where there is no preceding argument. Here's one possible behavior:

```julia
# max_varargs = 0
foo() 
foo(::Vararg{Any})
# max_varargs = 1
foo()
foo(T) where {T}
foo(Vararg{Any})
# max_varargs = 2
foo()
foo(T) where {T}
foo(T, U) where {T,U}
foo(T, Vararg{T}) where {T}
foo(T, Vararg{Any})
```

@Keno any preferences here?

**Comment by topolarity** [comment]
Never mind. I mis-understood how we were expanding Varargs currently. I believe the correct description is:
```julia
foo()
foo(::T) where {T}
foo(::T, ::Vararg{T}) where {T}
foo(::T, ::Vararg{Any}) where {T}
```

This corresponds to `max_varargs = 1`. Meanwhile, `max_varargs = 0` would just be:
```julia
foo()
foo(::Vararg{Any})
```

**Comment by staticfloat** [comment]
Should this be closed, now that https://github.com/JuliaLang/julia/pull/49320 was merged?
