### ISSUE TITLE
; broken when using Fish shell

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#4918]
With fish as my default shell, I get the below error. Presumably that is because in Fish, (x) is like $x in bash and not a grouping operator. 

julia> ;ls
fish: Illegal command name '(ls)'
Standard input: (ls) && true
                ^
ERROR: failed process: Process(`/usr/local/bin/fish -i -c '(ls) && true'`, ProcessExited(127)) [127]
 in pipeline_error at process.jl:476
 in run at process.jl:453
 in repl_cmd at client.jl:62

**Comment by iamed2** [comment]
May I ask why the subshells are necessary for Julia's shell integration?

**Comment by StefanKarpinski** [comment]
Relevant code is here: https://github.com/JuliaLang/julia/blob/cfac61d88625e3d58b9f0dbd4d9959e640b2a9f0/base/client.jl#L91-L126. It seems like it's so that we can do `(...) && true` to suppress failures, but we're also ignoring the status of the shell command, so maybe we don't need that anymore.

**Comment by iamed2** [comment]
In fish you could also use `begin; ...; true; end` to get an unconditional true status.

**Comment by StefanKarpinski** [comment]
Good to know. If anyone's using fish shell and wants to make a PR for this, that would be great 👍

**Comment by KristofferC** [comment]
Closed by https://github.com/JuliaLang/julia/pull/19984

**Comment by KristofferC** [comment]
But someone who uses it might want to confirm.

**Comment by iamed2** [comment]
Attempting now

**Comment by iamed2** [comment]
Tests pass for me; I suggest closing as fixed.
