### ISSUE TITLE
string(::Symbol) converts symbol with modifier (e.g. \hat) to wrong string

### ISSUE THREAD

**Issue by wsshin** [JuliaLang/julia#49201]
In REPL, we can use characters with a modifier such as `â` and `ȧ`.  These are entered by `a\hat[tab]` and `a\dot[tab]`.  However, symbols corresponding to these characters are converted by `string()` into strings that are different from those entered by the same method.  Here is an example:
```julia-repl
julia> string(:â)  # â is entered by a\hat[tab]
"â"
```
The resulting string looks exactly like the character entered by `a\hat[tab]`, which is used to enter the symbol.  However, their byte representations are different:
```julia-repl
julia> codeunits(string(:â))  # â is entered by a\hat[tab]
2-element Base.CodeUnits{UInt8, String}:
 0xc3
 0xa2

julia> codeunits("â")  # again, â is entered by a\hat[tab]
3-element Base.CodeUnits{UInt8, String}:
 0x61
 0xcc
 0x82

julia> isequal(string(:â), "â")
false
```
I observe a similar result for `ȧ` entered by `a\dot[tab]`.  

This is causing a problem like https://github.com/JuliaIO/JLD2.jl/issues/466#issuecomment-1490923546.

Here is the version info:
```julia-repl
julia> VERSION
v"1.9.0-rc1"
```

**Comment by oscardssmith** [comment]
This is expected behavior. Strings in Julia aren't normalized, but symbols are.
