### ISSUE TITLE
The new marking loop has a regression when marking arrays of pointers

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#49205]
When looking into https://github.com/JuliaLang/julia/issues/49120, it seems the regression seen there was hiding a part of the new mark loop where it's slower when marking a very large array of pointers. 

```julia
using Random: seed!
seed!(1)

abstract type Cell end

struct CellA<:Cell
    a::Int
end

struct CellB<:Cell
    b::String
end

function fillcells!(mc::Array{Cell})
    for ind in eachindex(mc)
        mc[ind] = ifelse(rand() > 0.5, CellA(ind), CellB(string(ind)))
    end
    return mc
end

mcells = Array{Cell}(undef, 5000, 5000 )
t1 = @elapsed fillcells!(mcells)
t2 = @elapsed fillcells!(mcells)

println("filling: $t1 s\nfilling again: $t2 s")

@time GC.gc()
@time GC.gc()
```
One of the GCs after will do a full mark of the array and take a long time to do it. This probably wasn't seen before because arrays of many pointers had really bad GC behaviour overall, but with https://github.com/JuliaLang/julia/pull/49185 it's quite clear.

**Comment by d-netto** [comment]
Seems like #49185 is adding a GC bit to encode whether an object is in the image.

Why could that potentially highlight a regression when marking large arrays of pointers?

**Comment by gbaraldi** [comment]
That PR is doing two different GC fixes, I haven't updated the title. It also fixes a behaviour where we stopped increasing the interval size when encountering many pointers which led to the regression in #49120

**Comment by gbaraldi** [comment]
I think the chunking itself is fine, if you look it's all in the hot loop of the function.

**Comment by d-netto** [comment]
I'm inclined to say it's coming from chunking. After increasing the batch size `MAX_REFS_AT_ONCE` from 2^16 to 2^20, the pathological full mark goes down from 20s to 3s.

This is not necessarily a solution, but could suggest that our chunking algorithm may need some adjustments.

**Comment by d-netto** [comment]
CC: @vchuravy
