### ISSUE TITLE
Should `run` mark streams as not-writable after using them?

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#49233]
```julia
julia> io=IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> iswritable(io)
true

julia> isopen(io)
true

julia> run(pipeline(`echo "hi"`, stdout=io))
Process(`echo hi`, ProcessExited(0))

julia> iswritable(io) # this is the interesting part
false

julia> isopen(io)
true
```
came up in https://github.com/JuliaLang/Pkg.jl/issues/3430#issuecomment-1494078824

**Comment by vtjnash** [comment]
`IOBuffer` is supposed to be disallowed here entirely, but I keep being too busy to implement the error https://github.com/JuliaLang/julia/issues/46768

**Comment by ericphanson** [comment]
in that case, could you comment in https://github.com/JuliaLang/Pkg.jl/issues/3430 with how `Pkg.test(; io)` should work? (it internally calls `run` twice, directing `stdout` to `io`). It sounds like it is meant to support `IOBuffer` at least.
