### ISSUE TITLE
parse_json regression in String allocations

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#49249]
[This commit](https://github.com/JuliaLang/julia/commit/56950e270863c0225b860e313451f70defa82c6d) (https://github.com/JuliaLang/julia/pull/48996) caused a regression in parse_json. Maybe related to https://github.com/JuliaLang/julia/issues/49241? @oscardssmith

**Comment by oscardssmith** [comment]
is there a known mechanism by which improving effects could regress performance?

**Comment by vtjnash** [comment]
https://github.com/JuliaLang/julia/issues/49241 is the only mechanism I know of currently, which is why I linked to that. Depends on what was changed in that commit though

**Comment by gbaraldi** [comment]
We went from
![image](https://github.com/JuliaLang/julia/assets/28694980/09189ca1-886e-4c49-93d9-948c4ac61661)
to
![image](https://github.com/JuliaLang/julia/assets/28694980/e7e27f6c-a91d-43bf-b9dd-6056a886fd9d)

So we are boxing a lot of ints and tuples that we didn't before.

**Comment by oscardssmith** [comment]
Is this fixed by https://github.com/JuliaLang/julia/pull/50444?

**Comment by gbaraldi** [comment]
No

**Comment by oscardssmith** [comment]
Why not? was this issue not caused by #49241? If not, do we have another potential reason why improving effects would regress performance?

**Comment by gbaraldi** [comment]
This is a separate issue that was just triggered by that change. But @aviatesk looked into it and I think it's something due to results not being inlineable and fun.

**Comment by JeffBezanson** [comment]
duplicate of #50458.
