### ISSUE TITLE
getproperty for the factor of LDLt is not working correctly

### ISSUE THREAD

**Issue by masuday** [JuliaLang/julia#49256]
Please see the following example.

```julia
julia> using LinearAlgebra

julia> A = [4 2 1; 2 9 4; 1 4 8]
3×3 Matrix{Int64}:
 4  2  1
 2  9  4
 1  4  8

julia> LDLt(A)
LDLt{Int64, Matrix{Int64}}
L factor:
3×3 UnitLowerTriangular{Int64, Matrix{Int64}}:
 1  ⋅  ⋅
 2  1  ⋅
 1  4  1
D factor:
Error showing value of type LDLt{Int64, Matrix{Int64}}:
ERROR: type Array has no field dv
Stacktrace:
  [1] getproperty
    @ .\Base.jl:37 [inlined]
  [2] getproperty(F::LDLt{Int64, Matrix{Int64}}, d::Symbol)
    @ LinearAlgebra C:\Users\yutaka\AppData\Local\Programs\Julia-1.10.0-DEV\share\julia\stdlib\v1.10\LinearAlgebra\src\ldlt.jl:70
  [3] show(io::IOContext{Base.TTY}, mime::MIME{Symbol("text/plain")}, F::LDLt{Int64, Matrix{Int64}})
    @ LinearAlgebra C:\Users\yutaka\AppData\Local\Programs\Julia-1.10.0-DEV\share\julia\stdlib\v1.10\LinearAlgebra\src\ldlt.jl:88
...
```

It happens with v1.8.5, v1.9.0-rc1, and the latest nightly build.

EDIT: I confirmed v1.6.7 has the same problem.

```julia
julia> versioninfo()
Julia Version 1.10.0-DEV.949
Commit 96812bdedd (2023-04-04 20:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 20 × Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 20 virtual cores
```

**Comment by barucden** [comment]
The docs suggest that users should use the function `ldlt` instead of constructing the `LDLt` structure directly:
>The main use of an LDLt factorization F = ldlt(S) is [...]. This is the return type of ldlt, the corresponding matrix factorization function.

Nevertheless, some methods for `LDLt` seem to assume that its `data` matrix is of type `SymTridiagonal`. Shouldn't we restrict the type then?
```julia
struct LDLt{T,S<:AbstractMatrix{T}}  # current
struct LDLt{T,S<:SymTridiagonal{T}}  # proposed
```

**Comment by KlausC** [comment]
Also note, that `LDLt` does not actually perform a factorization. It is intented exclusively to store the output of `ldlt(::SymTridiagonal)`.
The functionality you probable desire is `bunchkaufman` for dense symmetric/hermitian matrices and `ldlt` for sparse symmetric/hermitian matrices.
