### ISSUE TITLE
Why am I getting: "Error: there is no registered task type 'julia-proc'"

### ISSUE THREAD

**Issue by CBrauer** [JuliaLang/julia#49326]

**Comment by elextr** [comment]
As the question asks, did you install the Julia language support extension from the VScode marketplace into VScode?

Language support (and other) extensions need to be installed in VScode, its not automatic.

**Comment by mikmoore** [comment]
If it's unclear that a specific issue exists and requires fixing at a language level, you should begin by asking your questions at https://discourse.julialang.org/. It's a much more appropriate and widely-read venue for these sorts of questions and will be more likely to yield the assistance you need.

**Comment by CBrauer** [comment]
Hi elextr,

Thank you for responding.

I have installed the following extensions: "Judy", "Julia", Julia Light", "JuliaHub",
"Jupyter", Jupyter Cell Tag", Jupyter Keymap", and "Jupyter Notebook".

Isn't that enough?  Could you show me where to find the missing extension?

Charles

**Comment by maleadt** [comment]
This is not an issue with Julia itself, but probably with the vscode integration. There already seems to be an issue filed upstream: https://github.com/julia-vscode/julia-vscode/issues/3168
