### ISSUE TITLE
Return value from single-assignment `let`

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#49328]
I'm writing a `let` statement one line at a time interactively and I want to check what I get after each line to make sure it's right. 

Line 1:
```jl
julia> let x = rand(2,3,4) 
end

```
returns `nothing` , so I have to put `x` on the next line in order to see the result, 

```jl
julia> let x = rand(2,3,4)
           x
       end
2×3×4 Array{Float64, 3}:
```

only to delete it when I add the next line

```jl
julia> let x = rand(2,3,4)
           y = rand()
       end
```

which doesn't need an extra `y` line below.

Why not return the value `x` from the single-line `let`?

**Comment by JeffBezanson** [comment]
I don't think we can change this; it is consistent with empty blocks elsewhere returning `nothing`. For example this would be like
```
function f(x)
end
```
returning `x`, which would be surprising.
I understand the inconvenience here but the change is hard to justify.
