### ISSUE TITLE
apparent compilation hang in 1.9.0+rc2

### ISSUE THREAD

**Issue by lmiq** [JuliaLang/julia#49323]
Maybe related to: https://github.com/JuliaLang/julia/issues/49321

Apparently compilation is hanging when I'm trying to use the `JSON3` package in Julia `1.9.0-rc2`.

The minimal script to reproduce the bug is:

```julia
import Pkg
Pkg.activate(temp=true)
Pkg.add("ComplexMixtures")
using ComplexMixtures
ComplexMixtures.load("./test.txt")
```

where the input file is: [test.txt](https://github.com/JuliaLang/julia/files/11203964/test.txt)

I have installed `1.9.0-rc1` and `1.9.0-rc2` using `juliaup`, and I run:

```
julia +1.9.0-rc1 script.jl
#or
julia +1.9.0-rc2 script.jl
```

in `rc2` the execution hangs (it works in 1.6, 1.8.5 and 1.9.0-rc1).

If I kill the execution I get the following stack trace: [stacktrace.txt](https://github.com/JuliaLang/julia/files/11204003/stacktrace.txt)

The function in case is this one: https://github.com/m3g/ComplexMixtures.jl/blob/ea0d48880c08b6178034fa7c603ec03eefa186eb/src/results.jl#L679 

but I don't think it has anything to do with the bug.

I suspect that the problem is compilation because if I add `@show` statements in that function, even in the first line, they don't get immediately printed.

**Comment by lmiq** [comment]
Here is a "more minimal" example. 

The script hangs, as above.

**it does not hang if I replace `@with_kw` from `Paramters.jl` by the base `@kwdef`.**

Thus, this bug may be related to `Parameters.jl`, in association with some change in `rc1`. 

Run the example with: 

```
julia +1.9.0-rc2 minimal1.jl
```

with `test.txt` in the directory. The files are available in the `zip`:  [minimal1.zip](https://github.com/JuliaLang/julia/files/11204580/minimal1.zip)

I will try to make the example shorter.

**Comment by maleadt** [comment]
```
2a2068d2677eae3fe2101c89f9ed6c98e51f3a62 is the first bad commit
commit 2a2068d2677eae3fe2101c89f9ed6c98e51f3a62
Author: N5N3 <2642243996@qq.com>
Date:   Thu Feb 2 11:41:26 2023 +0800

    Subtype: avoid false alarm caused by eager `forall_exists_subtype`. (#48441)
```

ref #48441, cc @N5N3

Doesn't happen on master, so let's see if I can bisect a fix.
