### ISSUE TITLE
Regression: `mul!` of views allocates in v1.9+ for arrays of 4 or higher dimension, not in v1.8.5

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#49332]
This seems like a regression: in Julia v1.9-rc2 and master
```julia
julia> using LinearAlgebra, BenchmarkTools

julia> A = rand(ComplexF64,4,4,1000,1000);

julia> B = similar(A);

julia> a,b = (view(B,:,:,1,1),view(A,:,:,1,1));

julia> @btime mul!($b,$a,$a);
  321.792 ns (10 allocations: 608 bytes)
```
This is on an M1 Max
```julia
julia> versioninfo()
Julia Version 1.9.0-rc2
Commit 72aec423c2a (2023-04-01 10:41 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
```

But in v1.8.5 we don't allocate
```julia
julia> using LinearAlgebra, BenchmarkTools

julia> A = rand(ComplexF64,4,4,1000,1000);

julia> B = similar(A);

julia> a,b = (view(B,:,:,1,1),view(A,:,:,1,1));

julia> @btime mul!($b,$a,$a);
  97.076 ns (0 allocations: 0 bytes)
```
Note that if A has dimensions 3 or less, this issue does not arise.

**Comment by KristofferC** [comment]
I haven't benchmarked this but one difference is the following:

```julia
julia> A = rand(ComplexF64,4,4,1000,1000);

julia> B = similar(A);

julia> a,b = (view(B,:,:,1,1),view(A,:,:,1,1));

julia> f(A,B,C) = Base.require_one_based_indexing(A,B,C)
f (generic function with 1 method)

julia> @code_warntype optimize=true f(a, a, b)
```

This used to constant fold in 1.8 to `true` but on 1.9 it calls:

```julia
1 ─ %1  = invoke Base._any_tuple(Base.has_offset_axes::typeof(Base.has_offset_axes), false::Bool, A::SubArray{ComplexF64, 2, Array{ComplexF64, 4}, ...
```

**Comment by KristofferC** [comment]
Seems to be f718238af297f5179fe113ff76236

**Comment by KristofferC** [comment]
Seems to be f718238af297f5179fe113ff76236 cc @vtjnash

**Comment by pablosanjose** [comment]
Is it clear to anyone what would be the good strategy to fix this?

**Comment by pablosanjose** [comment]
Friendly bump, in case anyone with some available time knows what could be done here.

This is a fairly severe regression that has our simulation code stuck on 1.8.5 because we need views of 5-dimensional arrays, and the runtime penalty is too large. With current nightly it's become even worse:
```julia
julia> @btime mul!($b,$a,$a);
  493.124 ns (10 allocations: 608 bytes)
```

**Comment by pablosanjose** [comment]
It seems the root cause of this is the following
```
julia> A = view(rand(ComplexF64, 4, 4, 4, 4), :, :, 1, 1);

julia> @allocations Base.require_one_based_indexing(A,A,A)  # second run
11
```
This should be 1. So `require_one_based_indexing` is sometimes not elided as expected. The PR #45260 turns out to be insufficient for this particular combination of views of high-dimensional arrays.
