### ISSUE TITLE
SubString: parentindices don't work

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#49341]
For array views, `parentindices` return the view indices in the parent. However, this function doesn't work for string views:
```julia
julia> view([1,2,3], 2:3) |> parentindices
(2:3,)

julia> view("abc", 2:3) |> parentindices
ERROR: MethodError: no method matching parentindices(::SubString{String})
```
Would be very useful to support it too. For example, to retrieve substring locations after string functions like `split`.

`parentindices` should be computable from `SubString`, though it doesn't directly contain the range and I'm not sure how to compute it correctly given how strings are indexed:
```julia
julia> view("abc", 2:3) |> dump
SubString{String}
  string: String "abc"
  offset: Int64 1
  ncodeunits: Int64 2
```

**Comment by jakobnissen** [comment]
I think this will work:
```julia
function parentindices(s::SubString{String})
    s.offset + 1 : thisind(s.string, s.offset + s.ncodeunits)
end
```
