### ISSUE TITLE
Package negligence.

### ISSUE THREAD

**Issue by CBrauer** [JuliaLang/julia#49346]
Hello.

I’m a 25-year veteran of Microsoft’s C#, and I’ve become very discouraged by the status of the Machine Learning (ML.NET) project at Microsoft. It seems to be dying, and developers are left holding an empty bag.

So, I’ve come over to Julia to see if life is better.  My early experience was both good and bad.  

Let me talk about the bad side of Julia.  Like Python, Package neglect is a problem.  For example, being interested in Smoothing Splines, I naturally looked at “SmoothingSplines.jl”.  The GitHub REPO shows that this package has not been maintained in two years, and it can no longer be compiled by Julia 1.8.5.

My question to the Julia community is: “What is your policy on Package neglect”?

Charles

**Comment by ufechner7** [comment]
This is more a question than a bug report or a feature request. I think it would be better to ask this at https://discourse.julialang.org/
