### ISSUE TITLE
Nightly libcurl breakes build with an artifact jll

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#49361]
For more details see this [forum post](https://discourse.julialang.org/t/what-should-i-do-with-these-building-errors/97467)
As shown there 1.9rc builds fine but nightly

![image](https://user-images.githubusercontent.com/537321/232100569-0986b838-af37-4ec9-a1ab-9f81c4ed9a17.png)

**Comment by giordano** [comment]
This isn't a problem in Julia, you have to allow libcurl in https://github.com/JuliaRegistries/General/blob/1d8693ddc2c2f06b637747805c2c53fb452e1393/jll/G/GMT_jll/Compat.toml#L4 and https://github.com/JuliaPackaging/Yggdrasil/blob/536eed1805108f3faa69260bcfd6d7238266e52a/G/GMT/build_tarballs.jl#L73. And thank the curl developer for having changed the major version for absolutely no good reason, this also [broke the R build system](https://github.com/spack/spack/pull/36256#issuecomment-1477516692).

**Comment by joa-quim** [comment]
But then wouldn't it break the build for Julia versions <= 1.9 that still use libcurl 7.x?

**Comment by giordano** [comment]
"it" being _what_?

**Comment by joa-quim** [comment]
"it" being the changes you said *you have to allow libcurl 8 in ...*

**Comment by giordano** [comment]
Then the answer is "no". I specifically said "allow", not "require".

**Comment by joa-quim** [comment]
How will that make a difference since the libcurl dependency comes (also) from GDAL_jll and there only version 7.73 is *allowed*?

**Comment by giordano** [comment]
This is why you have to fix that in the registry, as I already said above.

**Comment by joa-quim** [comment]
Really, how is this thing supposed to work? How do we set a compat range? 

``compat="7.73.0, 8.0.1"``
or
``compat="7.73.0 - 8.0.1"``

``"7.73.0, 8.0.1"`` was accepted in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil/pull/6586#event-9014438186
)

but now I'm getting an error of overlapping ranges ``LibCURL_jll`` in https://github.com/JuliaRegistries/General/actions/runs/4708257635/jobs/8350587717?pr=81659

![image](https://user-images.githubusercontent.com/537321/232230993-104a2f74-d1a1-40cc-a55a-07176261738d.png)

**Comment by giordano** [comment]
> Really, how is this thing supposed to work?

There's way and way to ask for help, constantly complaining isn't one of them.

**Comment by joa-quim** [comment]
Sorry, I complain because I try and try and can't make a sense out of this. And one thing is trying on our own computers, another is to depend on the output of some automatic script.

Thank you for your help.

**Comment by giordano** [comment]
For what is worth, you hit https://github.com/JuliaLang/Pkg.jl/issues/1568, where Pkg generates broken registry entries if something changes between versions which only differ by the build number. Which is also the reason why I suggested fixing this first in the registry and then in Yggdrasil.

**Comment by joa-quim** [comment]
Looks like the problem now moved to GDAL

![image](https://user-images.githubusercontent.com/537321/232325874-50de6890-4f9f-411e-ac18-8e2fe4d33019.png)

**Comment by giordano** [comment]
Am I missing something or you [have opened a PR](https://github.com/JuliaRegistries/General/pull/81657), I [made a suggestion](https://github.com/JuliaRegistries/General/pull/81657#discussion_r1167569954) and you still haven't implemented it yet? Who's to blame here?

**Comment by joa-quim** [comment]
That PR is [merged on master](https://github.com/JuliaRegistries/General/blob/master/jll/G/GMT_jll/Compat.toml). Meanwhile I've opened an [issue ](https://github.com/JuliaGeo/GDAL.jl/issues/152) in GDAL
