### ISSUE TITLE
[proposal] new ijoin function , an iterable join

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#49373]
One can add ijoin to Iterators
```julia
import Base.Iterators as _I

struct _IJoin
    s
    delim
end

ijoin(s, delim) = _isijoinable(s) ? _IJoin(s, delim) : throw(ArgumentError("s = $s"))
_isijoinable(s) = _isijoinable(Base.IteratorSize(s))
_isijoinable(::Base.HasLength) = true
_isijoinable(::Base.HasShape{N}) where {N} = N==1
_isijoinable(::Base.IteratorSize) = true

Base.IteratorSize(a::_IJoin) = Base.IteratorSize(a.s)
Base.length(a::_IJoin) = 2*length(a.s)-1
Base.size(a::_IJoin) = let (s1,)=size(a.s); 2*s1-1 end

Base.iterate(a::_IJoin) =
    let y=iterate(a.s); y!==nothing ? (y[1], (:yld2,y[2])) : nothing end
Base.iterate(a::_IJoin, (st,sst)) = _iterate(a, Val(st), sst)
_iterate(a::_IJoin, ::Val{:yld2}, sst) =
    let y=iterate(a.s, sst); y!==nothing ? (a.delim, (:yld3,sst)) : nothing end
_iterate(a::_IJoin, ::Val{:yld3}, sst) =
    let y=iterate(a.s, sst); y!==nothing ? (y[1], (:yld2,y[2])) : nothing end
```

```julia
using Test
@test ijoin([1,2,3,4,5],0) |> collect == [1,0,2,0,3,0,4,0,5]
@test ijoin((1,2,3,4,5),0) |> collect == [1,0,2,0,3,0,4,0,5]
@test ijoin(1:5,0) |> collect == [1,0,2,0,3,0,4,0,5]
@test _I.dropwhile(<(3),1:5) |> s->ijoin(s,0) |> collect == [3,0,4,0,5]
@test map(ijoin(1:5, 0)) do e; 2e end == [2,0,4,0,6,0,8,0,10]
@test_throws ArgumentError ijoin(fill(1,2,3),0)
```

This will be useful to work on collections

*and i dont like `s -> _I.append!([first(s)], _I.flatten(zip(_I.cycle(0), _I.tail(s))))` .* :)

**Comment by StefanKarpinski** [comment]
I'm not really getting the motivation here. Can you say something about what this does and why we would want it (especially in Base)?

**Comment by StefanKarpinski** [comment]
I'm not really getting the motivation here. Can you say something about what this does and why we would want it (especially in Base)?

**Comment by o314** [comment]
Hello. It basically allows you do join in functional programming with collections like you do with IO and String.
Nowadays it relies on IO in julia, a very shallow foundation IMO. There you can use it with any kind of collections

*About Base* ; Effectively, while python gathers a lot of things in itertools distributed in stdlib
julia has both Base.Iterators and IterTools.jl and (upto there?) is quite conservative about maintaining this for now. So

- there should be a boundary with (more or less natural) matches and continuations
```julia
# from itertools
@deprecate chain(xss...) Iterators.flatten(xss)
@deprecate product(xss...) Iterators.product(xss...)
```
- that's a computational marketplace, there should be some measurement somewhere
- maybe julia today is too much conservative about base (see https://docs.python.org/3/library/itertools.html) ?
- some more commons utilities than ijoin are in IterTools, and should remain there .

So i think it should go to itertools.jl (sorry for having forgetting it first).
If everything is ok, i will close this one and reopen it there.

**Comment by o314** [comment]
The proposal has been move to itertools.jl
It should be closed there.

**Comment by o314** [comment]
The proposal has been move to itertools.jl
It should be closed there.
