### ISSUE TITLE
Should `allequal` use `==` instead of `isequal`?

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/julia#49372]
When I worked on the PR to add `allequal` (#43353), I used `isequal` instead of `==`, because `unique` and `allunique` use `isequal`. However, in retrospect that seems like the wrong choice. It seems to me that users looking for `allequal` functionality will generally want to compare values with `==`. In particular, it is unfortunate that `allequal` does not follow three-valued logic. So, we currently have the following behavior, which seems undesirable to me:

```julia
julia> allequal([NaN, NaN])
true

julia> allequal([missing, missing])
true

julia> allequal([1, missing])
false
```

I think for most use cases it would be better for those to return `false`, `missing`, and `missing`, respectively.

In the PR discussion, I [mentioned the difference](https://github.com/JuliaLang/julia/pull/43354#issuecomment-988359411) between using `isequal` and using `==`, but nobody objected to using `isequal`. 😅 

Unfortunately this would be a breaking change. I would almost consider the failure to propagate missingness a bug, but technically it's not a bug since the docstring does say that comparisons are made using `isequal`.

Would this qualify as one of those "technically breaking" changes that we could slip into a minor release?

**Comment by ericphanson** [comment]
To me, it makes sense that `allequal` uses `isequal`, and those answers look reasonable. Do you have examples/situations where the other behavior would be better?

**Comment by CameronBieganek** [comment]
I don't have a particular use case in mind. I just have a gut feeling that comparison with `==` is more generally useful, especially since it propagates missingness.

Here's an example inspired by a [question on Discourse](https://discourse.julialang.org/t/how-do-i-get-the-indexes-for-matrix-columns-whose-elements-are-all-the-same/97402). Suppose we have the following matrix:

```julia
m = [1        missing  NaN  3  4
     missing  missing  NaN  3  5]
```

And then we want to call `findall(allequal, eachcol(m))`. The problem is, there is no obvious right way to do it. It depends on what the user is looking for. We probably shouldn't have added `allequal`, because it's hard to predict which version of equality the user is looking for, whether it be `==`, `isequal`, or something in between, like

```julia
function myequals(x, y)
    isnan(x) && isnan(y) && return true
    x == y
end
``` 

When I opened the [issue](https://github.com/JuliaLang/julia/issues/43353) and [the PR](https://github.com/JuliaLang/julia/pull/43354), there were some objections to expanding the Base namespace, but I don't think anyone brought up the issue of ambiguity over the type of equality comparison to use.

**Comment by ericphanson** [comment]
The way I’ve used it is for sanity-checking data, as a complement to `allunique`. E.g. check the `id` column is all unique, check some supposedly constant column is `allequal` (or all-equal per group after grouping), etc. In this case, `isequal` semantics are generally what I want and are consistent with `allunique`. But I agree in general different uses will need different semantics.

**Comment by CameronBieganek** [comment]
> First of all, it would be extremely weird if a function named `allequal` used something other than `isequal` for comparisons.

`all==` is not a syntactically valid identifier, so what else could `all(==(first(A)), A)` possibly be named? The `==` symbol is read as "equals", after all. Also, many beginner Julia programmers are not even aware of `isequal`.

> Next is probably a matter of opinion, but would be nice not to pollute more and more fundamentally boolean function results with missings.

`all` itself already propagates `missing`, so it shouldn't be too surprising if `allequal` also propagates missing.

```julia
julia> all([true, missing])
missing
```

Once you buy in to three-valued logic at the language level, it's hard to justify *not* using three-valued logic.

**Comment by StefanKarpinski** [comment]
I think this is a non-starter because `==` is not an equivalence relation, specifically for values like `NaN` it's non-reflexive. The only equality predicates that this can behave sanely with and be implemented efficiently with are the ones that are true equivalence relations and compatible with hashing, so `isequal` and `===`.

**Comment by mikmoore** [comment]
Would there be room for keyword arguments like our sorting functions have? I.e.,
```julia
allequal([(+0.0,1), (-0.0,2)]; by=first, eq=(==)) == true
allequal([(+0.0,1), (-0.0,2)]; by=first, eq=isequal) == false
```
I suppose this would also involve expanding `isequal` with matching keywords.

**Comment by LilithHafner** [comment]
This seems like a large API for a small feature. Is `allequal(x; eq=(==))` that much better than `all(==(first(x)), x)`?

**Comment by CameronBieganek** [comment]
No, it's not much better. But it's a slippery slope. Once you have `allequal`, it starts to make sense to have an `eq` keyword argument.

I think I'm now of the opinion that we (I) shouldn't have added `allequal` to Base in the first place. 😬

**Comment by ericphanson** [comment]
This might not be very helpful, but I like `allequal` and didn't comment on the PR about which comparison because I thought `isequal` was obviously the right one to use, and I assume others did the same.

**Comment by CameronBieganek** [comment]
Ok, at least this issue has verified that some people prefer it the way it is now, which is good to know.
