### ISSUE TITLE
Ctrl+D should exit okly pkg mode and return to main REPL; instead, it exits entire REPL

### ISSUE THREAD

**Issue by tgross35** [JuliaLang/julia#49381]
Version info:

```
Julia Version 1.8.5
Commit 17cfb8e65e* (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.6.0)
  CPU: 4 × Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 on 4 virtual cores
```

Installed via homebrew

When entering package mode with `]`, it would make sense for ctrl+D (EOF) to exit the sub-repl. This is common behavior for other nested shells: ctrl+d will gracefully exit e.g. SQL or Python consoles, whereas ctrl+c is a more aggressive process termination signal.

**Comment by giordano** [comment]
> whereas ctrl+c is a more aggressive process termination signal.

I don't think that's true, definitely not in python nor ipython.

**Comment by Keno** [comment]
The current behavior is standard for shells. ^D exits the shell, ^C interrupts the foreground work. The sub-shell exit in julia is backspace, which is something you have to know, but it quite intuitive once you do. I don't think there's anything to do here.
