### ISSUE TITLE
Const should overload == 

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#49410]
I am writing some tests for some constant folding stuff.
And I run into my tests failing because Const equality uses default equality, not the equality of the type it is a constant of.
Which is a problem for floats.
```julia
julia> Core.Const(0.0) == Core.Const(-0.0)
false
```

Perhaps we need to do it like this since, something might rely on it really being the same, not just mathematically equal.
But in that case shouldn't our code relying on that be using `===` ?

**Comment by Keno** [comment]
I don't think overloading `==` makes sense. There's basically never a situation where `==` of the Const's contents is the correct query.
