### ISSUE TITLE
Date should auto convert to DateTime

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#49436]
Would it be reasonable to add an auto conversion from `DateTime` to `Date` since there is no loss in precision?

Then things like this would work without having to manually convert to `DateTime` first:

```
julia> Dates.datetime2unix(Dates.Date("2022-10-20"))
ERROR: MethodError: no method matching datetime2unix(::Date)

Closest candidates are:
  datetime2unix(::DateTime)
   @ Dates /me/julia/share/julia/stdlib/v1.10/Dates/src/conversions.jl:58

Stacktrace:
 [1] top-level scope
   @ REPL[89]:1
```

**Comment by KristofferC** [comment]
> Would it be reasonable to add an auto conversion from DateTime to Date since there is no loss in precision?


Julis doesn't have such a thing when it comes to calling methods. So for this, you would have to add a `datetime2unix(::Date)` function.

**Comment by Seelengrab** [comment]
> there is no loss in precision?

There may not be loss of precision, but that's still a decision point - defaulting to midnight for such a conversion seems odd to me.

**Comment by robsmith11** [comment]
I was thinking that an absence of time would be considered "zero", just like converting an int (nothing to the tight of the decimal point) to floating point with zero fractional value.  That same decision is already implicitly being made when passing a Date to the DateTime constructor.
