### ISSUE TITLE
Julia hanging with extensions + Distributed on latest backports-release-1.9

### ISSUE THREAD

**Issue by marius311** [JuliaLang/julia#49437]
Sorry if I'm jumping the gun but haven't seen it mentioned and no one on Slack seemed to know about this, but a consequence of https://github.com/JuliaLang/julia/pull/49257 (slated to be included in 1.9.0-rc3) appears to be that Julia hangs when loading extension modules in sessions with multiple processes. I have a tiny MWE repo which reproduces this:

```bash
gh repo clone marius311/julia19_distributed_extension_hang_mwe
cd julia19_distributed_extension_hang_mwe
julia +1.9.0-rc2 mwe.jl # ok
julia +1.9.0-rc1 mwe.jl # hangs
julia +dev mwe.jl # hangs, where dev == after this PR
```

The code is just two dummy modules, one with an extension for the other, and code:
```julia
using Distributed
addprocs(2)
using Foo, Bar
```

Not sure the solution since https://github.com/JuliaLang/julia/pull/49257 *is* important for fixing https://github.com/JuliaLang/julia/issues/49250 (which I had also run into hence why I was running backports-release-1.9 when I noticed this)

**Comment by KristofferC** [comment]
On master we get:

```
      From worker 2:    │    ConcurrencyViolationError("deadlock detected in loading BarFooExt -> BarFooExt")
```

So the question is, why is BarFooExt trying to load itself?
