### ISSUE TITLE
Recent commit introduced a failure in analyzegc

### ISSUE THREAD

**Issue by d-netto** [JuliaLang/julia#49453]
Seems like it was introduced a few commits ago. For example, see the test page of latest commit of master (which shows this failure, but doesn't seems to have introduced it) https://buildkite.com/julialang/julia-master/builds/23064#0187a476-57f1-4b10-8d88-f4f99034ad4d.

**Comment by d-netto** [comment]
Seems to have been introduced by https://github.com/JuliaLang/julia/pull/49349.

CC: @vtjnash

**Comment by KristofferC** [comment]
Reverted

**Comment by DilumAluthge** [comment]
Reverted in https://github.com/JuliaLang/julia/pull/49457
