### ISSUE TITLE
Debugger broke on "Symbol()"

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#49452]
The image bellow shows the problem

![image](https://user-images.githubusercontent.com/537321/233632845-82a275f9-7d32-4495-a292-e3dbbf1cc06d.png)

**Comment by oscardssmith** [comment]
this is a bug in debugger. jl or Juliainterpreter not Julia

**Comment by oscardssmith** [comment]
https://github.com/JuliaDebug/JuliaInterpreter.jl probably.

**Comment by KristofferC** [comment]
Can reopen at JuliaInterpreter but please also give Julia version etc.

**Comment by joa-quim** [comment]
[Done ](https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/571)
