### ISSUE TITLE
Julia fails to start on Fedora 38

### ISSUE THREAD

**Issue by ingframin** [JuliaLang/julia#49468]
I just installed Julia on a fresh install of Fedora 38 using "sudo dnf install julia".
By default, Fedora installs julia 1.9.0-beta 

I get the following error:

`$ julia
fatal: error thrown and no exception handler available.
InitError(mod=:OpenBLAS_jll, error=ErrorException("could not load library "libopenblas64_.so"
libopenblas64_.so: cannot open shared object file: No such file or directory"))
ijl_errorf at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
ijl_load_dynamic_library at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
unknown function (ip: 0x7f58c7f9ce78)
unknown function (ip: 0x7f58c7940602)
unknown function (ip: 0x7f58c7940888)
unknown function (ip: 0x7f58e947f9ff)
unknown function (ip: 0x7f58e94692eb)
jl_repl_entrypoint at /usr/bin/../lib64/julia/libjulia-internal.so.1 (unknown line)
main at julia (unknown line)
__libc_start_call_main at /usr/bin/../lib64/libc.so.6 (unknown line)
__libc_start_main at /usr/bin/../lib64/libc.so.6 (unknown line)
_start at julia (unknown line)`

The issue is that the packages in the Fedora repository do not depend on openblas. 

**Installing openblas fixes the issues.** 

Is this a Fedora error or is the .rpm package not packaged properly?

**Comment by giordano** [comment]
> Is this a Fedora error or is the .rpm package not packaged properly?

Sounds like it, CC: @nalimilan.  In the meantime, I recommend installing the [official binaries of Julia](https://julialang.org/downloads/), perhaps using [juliaup](https://github.com/JuliaLang/juliaup) if you want to use multiple versions or have easy upgrades in the future, instead of being limited to the single version your distribution will provide at a time.

**Comment by ViralBShah** [comment]
Hopefully the 1.9 released version fixes it. But if not, perhaps use discourse to bring this up - since the Fedora builds are not driven through this repo.

**Comment by nalimilan** [comment]
Yes it's been fixed in Fedora.
