### ISSUE TITLE
REPL.fuzzyscore heuristics could be better

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#49466]
The heuristics don't work very well in practise, partly because a mismatch near the beginning of the string completely messes up the algorithm, whereas numerous insertions/deletions don't do much.

For example
```julia
julia> REPL.fuzzyscore("bupercalifragilisticexpialidocious", "supercalifragilisticexpialidocious")
-68.0

julia> REPL.fuzzyscore("parasid", "supercalifragilisticexpialidocious")
6.59
```
Or
```julia
julia> REPL.fuzzyscore("IJilia", "IJulia")
-3.0933333333333337

julia> REPL.fuzzyscore("IJilia", "MotionCaptureJointCalibration")
5.5633333333333335
```
Maybe it would be better to use something like Lehvenstein by default with some slight heuristics on top?

**Comment by tecosaur** [comment]
For reference, I've just used *Optimal String Alignment Distance* in a project of mine, and it seems to work rather well.

![image](https://user-images.githubusercontent.com/20903656/233832898-4dde20d2-5039-4997-b84f-5bbb6e4942c6.png)

I'm also considering using the *Longest Common Subsequence* to highlight "this bit looks similar" in the match.

**Comment by vortex73** [comment]
Could you tell me how to reproduce this issue? And direct me to any related src .

**Comment by jakobnissen** [comment]
@vortex73 You can reproduce it like this:
```julia
julia> using REPL

julia> REPL.fuzzyscore("IJilia", "IJulia")
-3.0933333333333337

julia> REPL.fuzzyscore("IJilia", "MotionCaptureJointCalibration")
5.5633333333333335
```
The code is in `stdlib/REPL/src/docview.jl`. Search for "Fuzzy Search Algorithm" - it's the set of functions immediately following.

**Comment by tecosaur** [comment]
It would probably be worth giving some more examples of what OSA-based scores looks like in practice:

```julia

julia> DataToolkitBase.stringsimilarity("bupercalifragilisticexpialidocious", "supercalifragilisticexpialidocious")
0.9705882352941176

julia> DataToolkitBase.stringsimilarity("parasid", "supercalifragilisticexpialidocious")
0.20588235294117652

julia> DataToolkitBase.stringsimilarity("IJilia", "IJulia")
0.8333333333333334

julia> DataToolkitBase.stringsimilarity("IJilia", "MotionCaptureJointCalibration")
0.1724137931034483

julia> @btime DataToolkitBase.stringsimilarity("IJilia", "MotionCaptureJointCalibration")
  282.022 ns (2 allocations: 576 bytes)
0.1724137931034483
```

**Comment by tecosaur** [comment]
Also: for helpful "did you mean?"-type messages, I think having that work well well could be useful across a fair few other places in the Julia code base, perhaps it could be worth having a 'private'/not-part-of-the-API `Base.stringsimilarity` for that purpose?

**Comment by vortex73** [comment]
https://github.com/JuliaLang/julia/blob/4d3607a53bf4cc2f4ece12dc331fe8691f655768/stdlib/REPL/src/docview.jl#L627-L629
In this particular function isn't the value always equating to zero? I feel I'm missing something here.

**Comment by vortex73** [comment]
I've understood the code base and the problem. @jakobnissen had asked for a lehvenstein's approach, but doesn't even that fall prey to the mismatch at the starting? Please correct me as i'm new to this and guidance would be helpful.

**Comment by jakobnissen** [comment]
> a lehvenstein's approach, but doesn't even that fall prey to the mismatch at the starting?

No, that works fine.

```julia
julia> using REPL

julia> REPL.levenshtein("bupercalifragilisticexpialidocious", "supercalifragilisticexpialidocious")
1
```
