### ISSUE TITLE
Documentation for DelimitedFiles doesn't show that it's now a separate package

### ISSUE THREAD

**Issue by wgmitchener** [JuliaLang/julia#49479]
In the online documentation, versions [1.9.0-rc2](https://docs.julialang.org/en/v1.9.0-rc2/) and [1.10-dev](https://docs.julialang.org/en/v1.10-dev/), the [DelimitedFiles](https://docs.julialang.org/en/v1.9.0-rc2/stdlib/DelimitedFiles/) module is still listed under the standard library.
However, according to the [release notes](https://docs.julialang.org/en/v1.9.0-rc2/NEWS/), this module is now in a separate package and must be installed separately.
Some explanation should be added to the documentation under the standard library, or perhaps the whole section on DelimitedFiles should be removed.

FYI: I just upgraded a machine from Fedora 37 to 38, and that upgraded julia from 1.8 to 1.9. It took me a few minutes to figure out that this change to DelimitedFiles is why my program suddenly wasn't working.

**Comment by KristofferC** [comment]
> this module is now in a separate package and must be installed separately.

This was changed in https://github.com/JuliaLang/julia/pull/48671 so it can be loaded without explicitly installing it. The release notes should be updated.
