### ISSUE TITLE
Parsing to wrap Level 3 BLAS routines syr2k/her2k

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#4950]
PR #4813 provides a BLAS wrapper to the symmetric rank _2k_ update function `syr2k`, which provides the updates:

```
C := alpha*A*B' + alpha*B*A' + beta*C,
C := alpha*A'*B + alpha*B'*A + beta*C,
```

Is it worth parsing Julia expressions of this form and turning them into calls to `syr2k`/`her2k`?

**Comment by andreasnoack** [comment]
@JeffBezanson do you think anything like https://github.com/JuliaLang/julia/issues/4950#issuecomment-29405295 will ever happen? If not, we should probably close this issue.

**Comment by KristofferC** [comment]
Adding this to the parser seems quite unlikely due to how dynamic Julia has become.
