### ISSUE TITLE
Nightly hangs on arrays of structs of BigFloat

### ISSUE THREAD

**Issue by moble** [JuliaLang/julia#49501]
I've run into a problem where Julia very consistently hangs when setting values in an array (greater than a certain size) of structs with `BigFloat` fields.  The CPU usage goes to 100% and stays there.  (I've left it running for up to a couple hours.)  Memory usage stays pretty much constant and quite reasonable.  I can't interrupt, and have to kill the process.  I've tested that this happens on both macOS and linux with the nightlies, but doesn't happen on 1.9-rc2.

I happened to run into this problem [testing Quaternionic.jl on the latest nightly](https://github.com/moble/Quaternionic.jl/actions/runs/4792457832/jobs/8534361982#step:6:350) — specifically when calling `randn` with a struct containing `SVector{4, BigFloat}`.  But I've cut it down to the following MWE, which doesn't even use `StaticArrays`:
```julia
N = 98_304  # or larger
T = BigFloat

struct Q{T}
    a::T
    b::T
end
A = Array{Q{T}}(undef, N);
for i in eachindex(A)
    #@show i; flush(stdout)
    A[i] = Q(rand(T), rand(T))
end
```
Using `N=98_303` seems to succeed consistently — in well under a second.  Using just one field in `Q` (or avoiding a struct entirely and just using a bare `Array{BigFloat}`) seems to succeed consistently, even with `N=10_000_000`.  Using `N=100_000_000; T=Float64` seems to succeed consistently.

This weird `N=98_304` value is the dividing line between quick success and seemingly interminable hanging on both my laptop and desktop, but may not be the same for everyone. 🤷 

If I uncomment the `@show` line, I see that the loop seems to run just fine up to a point.  But then it stops suddenly, with the CPU pegged at 100%, never taking another step.  The point where it stops is never precisely consistent, but is fairly so — around 1/8 of the way on my mac laptop and 1/4 of the way on my linux desktop.

---

I believe this is the same issue that originally turned up in a github action running as `Julia nightly - ubuntu-latest - x64`.  

But for my local testing, I downloaded the nightly builds from [the official page](https://julialang.org/downloads/nightlies/), and tried both on my macbook
```julia
julia> versioninfo()
Julia Version 1.10.0-DEV.1107
Commit cb1cc273e2d (2023-04-24 22:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
```
and on linux
```julia
julia> versioninfo()
Julia Version 1.10.0-DEV.1110
Commit 86b819c3f79 (2023-04-25 06:49 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, sandybridge)
  Threads: 1 on 8 virtual cores
```

**Comment by vtjnash** [comment]
This is the gc_chunkqueue_push problem fixed recently
