### ISSUE TITLE
Base.download marked as deprecated

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#49514]
`Base.download` is marked as deprecated:

```
➜  ~ julia --depwarn=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.3 (2022-11-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> download("http://julialang.org")
┌ Warning: Base.download is deprecated; use Downloads.download instead
│   caller = top-level scope at REPL[1]:1
└ @ Core REPL[1]:1

```

But what does it mean for an exported Base function to be deprecated? It does not mean that it will be removed in a 1.x release: https://github.com/JuliaLang/julia/pull/45853 And I don't think it makes sense to already help people "migrate their code to Julia 2.0".

It's not a big issue, but it seems like one of those small technical things that makes programming difficult for newcomers. They suddenly need to figure out what "deprecated" means, what `Downloads` is and whether there are any differences in API.

**Comment by jakobnissen** [comment]
Even if it's not removed, it may still be worse than `Downloads.download`, such that it's recommended for all users to stop using it. To me it makes perfect sense to deprecate functionality even if one does not intend to remove it any time soon.

**Comment by KristofferC** [comment]
And you only see this when you explicitly opt into dep warnings so I am not sure

> it seems like one of those small technical things that makes programming difficult for newcomers

applies.
