### ISSUE TITLE
IOBuffer/fileIO Memory leak with Threads.@spawn

### ISSUE THREAD

**Issue by louisponet** [JuliaLang/julia#49545]
I managed to isolate a memory leak that caused runaway memory usage for long running processes due to some logging I was doing. 

MWE:

```julia
function explode(lck, buffer, path, message; kwargs...)
    lock(buffer) do
        println(buffer, message)
        open(path, append = true) do f
            write(f, take!(buffer))
        end
    end
end

let
    lck = ReentrantLock()
    buffer = IOBuffer()
    path = "test.log"
    while true
        Threads.@spawn begin
            explode(lck, buffer, path, "blabla")
        end
    end
end
```

versioninfo():
```
Julia Version 1.9.0-rc2
Commit 72aec423c2 (2023-04-01 10:41 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = /opt/intel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin
  JULIA_NUM_THREADS = 8
```

Compiled from source. Also tested on downloaded binaries of julia `1.8.2` , `1.6.7`

**Comment by louisponet** [comment]
So in my real code this execute much slower ofcourse, but it still keeps accumulating memory that never gets garbage collected. What would be the way out?

**Comment by louisponet** [comment]
I have tested the memory consumption with the following code, to also not to do the fork bombing, i.e. making it closer to my real world example:

```julia
function meminfo_julia!(d)
  push!(d["GC Live"], Base.gc_live_bytes()/2^20)
  push!(d["Max. RSS"], Sys.maxrss()/2^20)
end

function meminfo_procfs(d)
    pid=getpid()
  smaps = "/proc/$pid/smaps_rollup"
  if !isfile(smaps)
    error("`$smaps` not found. Maybe you are using an OS without procfs support or with an old kernel.")
  end

  rss = pss = shared = private = 0
  for line in eachline(smaps)
    s = split(line)
    if s[1] == "Rss:"
      rss += parse(Int64, s[2])
    elseif s[1] == "Pss:"
      pss += parse(Int64, s[2])
    end
  end

  push!(d["RSS"], rss/2^10)
  push!(d["PSS"], pss/2^10)
end

function explode(buffer = IOBuffer())
    lck = ReentrantLock()
    path = "test.log"
    @sync for _ in 1:1000000
        Threads.@spawn begin
            lock(lck) do
                println(buffer, "blabla")
                open(path, append=true) do f
                    write(f, take!(buffer))
                end
            end
        end
    end
end

memdict = Dict("GC Live" => Float64[],
               "Max. RSS" => Float64[],
               "RSS" => Float64[],
               "PSS" => Float64[])
t = Threads.@spawn let
    buffer = IOBuffer()
    for i = 1:200
        explode(buffer)
        meminfo_julia!(memdict)
        meminfo_procfs(memdict)
    end
end
```
If I plot the results I get:

![image](https://user-images.githubusercontent.com/21249513/234995216-747f33ff-f7a0-4d1e-afe1-56f3ac493443.png)

While it seems like it stabilizes, over time it keeps trending upwards and I think this is exactly what's causing the long term leak. Would you have any idea what might be causing this trend?

**Comment by louisponet** [comment]
I've done some more digging, I think I have isolated the issue in the above piece of code to the `write(f, take!(buffer))` part, which can be recreated with much less threads and simply a larger message like:

```julia
const MSG = String(rand(UInt8, Int(10e6)))
function explode(buffer = IOBuffer())
    lck = ReentrantLock()
    out = ""
    @sync for _ in 1:2
        Threads.@spawn begin
            lock(lck) do
                println(buffer, MSG)
                out *= String(take!(buffer))
            end
        end
    end
    
    return out
end
```

I have done the above test in a loop which leads to:
![explode](https://user-images.githubusercontent.com/21249513/235197521-e27a098f-99b0-47d8-8181-926df8a6c14f.png)

In the case of writing to a file, I could fix it by simply writing the `buffer.data` directly and manually setting `buffer.size=0`, `buffer.ptr=1`. But I don't think that this behavior is expected...

**Comment by louisponet** [comment]
Ok, if I run it with `-t 1` or `-t 2`, it stays fine, at `-t 3` it starts going up like in the graph

**Comment by louisponet** [comment]
I just tested it on 1.8.5, there this particular issue is not present. It is on 1.9-rc4 and master

**Comment by gbaraldi** [comment]
On linux I wasn't able to reproduce this but on macos I do see the resident set grow and grow until we start swapping.

**Comment by louisponet** [comment]
So I must say i was quite on the wrong path in the beginning thinking it was just iobuffers, now i think it's about how Strings are allocated during locked (?) Conversion from UInt8 vectors... It's also very weird that it only shows up when the number of threads is bigger than 2

**Comment by louisponet** [comment]
Tested it again today on julia v1.9.0-rc3 and it's still present.

**Comment by KristofferC** [comment]
You could try a bisect to see what commit introduced the problem.

**Comment by louisponet** [comment]
Oh, you're right I'll have a try. I also tried the Profile.take_heap_snapshot() after seeing your workflow video, but it doesn't seem very illuminating (can still supply it if helpful)

**Comment by louisponet** [comment]
Success! The bisect points at commit 80346c1cc0625ed988c158072587ab2fdf191e86 as the first bad one.

**Comment by Moelf** [comment]
what's the perspective on fixing this?
