### ISSUE TITLE
`@time` inhibits optimisation on 1.9

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#49554]
This bug occurs on Julia 1.9 (current release branch, commit 1853b90 tagged 1.9.0-rc3), but not on master, nor on LTS.
Discovered by kimuh in https://discourse.julialang.org/t/simple-code-run-time-1-7-1-8-1-9-difference/98026/1

The following function:
```julia
function sum_n(n)
    s = 0
    for i in 1:n
          s += i
    end
    return s
end
```
is optimised by LLVM to the analytical solution, essentially `div(n*(n+1), 2)`. Hence, running `sum_n(100000000000)` returns instantly.

However, `@time sum_n(100000000000)` takes about 2 seconds:
```julia
julia> @time sum_n(1000000000)
  2.782994 seconds
500000000500000000
```
On master and 1.6.7 it returns instantly. Thus, the timing is misleading and does not reflect how long the code actually takes to run.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/47561?

**Comment by jakobnissen** [comment]
You are right, and it seems to be closed if https://github.com/JuliaLang/julia/pull/49411 gets merged. Should we keep this issue open (or re-open the old one) until #49411 is backported?
