### ISSUE TITLE
detect_ambiguities reports false positive with Varargs methods

### ISSUE THREAD

**Issue by schillic** [JuliaLang/julia#49571]
Below are two `foo` methods with different `Vararg` types. Method dispatch can perfectly distinguish between them. But `Test.detect_ambiguities` disagrees.

```julia
julia> module Detect
    foo(x::Int...) = 1
    foo(x::Float64...) = 2
end;

# Julia can distinguish between the methods

julia> Detect.foo(0)
1

julia> Detect.foo(0.0)
2

# detect_ambiguities complains

julia> using Test

julia> detect_ambiguities(Detect)
1-element Vector{Tuple{Method, Method}}:
 (foo(x::Int64...) in Main.Detect at REPL[1]:2, foo(x::Float64...) in Main.Detect at REPL[1]:3)

```

Tested with v1.8.5 and 1.9.0-rc2

```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by vtjnash** [comment]
Ambiguous for foo(). Use typeintersect to see the failure case

**Comment by schillic** [comment]
Oh, that was unexpected. Thanks!

In my application, the first `foo` method lives in package `A` and I wanted to define the second method in package `B`. I guess I have to also define `foo()` in package `B` then.

**Comment by KristofferC** [comment]
You can define `foo(x::Float64, z::Float64...)` maybe.

**Comment by schillic** [comment]
Yes, that is the solution I chose in the end because `foo()` in my case does not make sense.
