### ISSUE TITLE
Julia 1.8.5 ignores the libdir variable for searching sys.so

### ISSUE THREAD

**Issue by xgqt** [JuliaLang/julia#49574]
Setting the following has no effect on produced binary:
```
LOCALBASE:=${EPREFIX}/usr
override prefix:=${EPREFIX}/usr
override libdir:=\$(prefix)/$(get_libdir)
```

It fails to load `sys.so`:
```
ERROR: could not load library "/usr/bin/../lib/julia/sys.so"
/usr/bin/../lib/julia/sys.so: cannot open shared object file: No such file or directory
```

Expectations:
`sys.so` is loaded from the desired `libdir`.

This is crucial to installing Julia on Gentoo systems as 64-bit libraries are installed into `/usr/lib64`.
See also: https://bugs.gentoo.org/905153

**Comment by brenhinkeller** [comment]
Do such problems occur when using the official binaries, or only when using Julia built from source?

**Comment by vchuravy** [comment]
The `sys.so` is not a normal shared library, it's the system image with is the serialized state of a Julia session. It should **not** be located in libdir.
