### ISSUE TITLE
Julia 1.9.0-rc2 segmetation fault on Fedora 38

### ISSUE THREAD

**Issue by nuitlejour** [JuliaLang/julia#49609]
I am using Julia 1.9.0-rc2 on Fedora 38, simple julia> versioninfo() will produce a segmetation fault.

![snap](https://user-images.githubusercontent.com/20106317/235887481-b219f955-2bf1-4114-8bf7-592e68114273.png)

**Comment by KristofferC** [comment]
Try the official build. If that also fails please add a comment. Otherwise, report it to the Fedora maintainers.

**Comment by nuitlejour** [comment]
@KristofferC I have tried the official1.85 version, same segmentation fault error. I think it's fedora 38 bug, will will report to Fedora maintainers.

**Comment by nuitlejour** [comment]
fedora bug report page:
https://bugzilla.redhat.com/show_bug.cgi?id=2100447
