### ISSUE TITLE
`hash(::Type)` inconsistent with some signature tuples (sometimes)

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#49620]
Bit of an heisenbug, but in some cases, the `hash()` function for signature tuples yields inconsistent hashes. @ararslan was able to see this in a clean Julia session:

```
julia> t1 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> t2 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> hash(t1)
0x6460a2e89083289a

julia> hash(t2)
0x7c27d9754fb7224a
```

I couldn't actually precisely replicate this, but the issue definitely exists, since it causes Documenter to relatively consistently fail when checking missing docstrings in https://github.com/JuliaStats/StatsBase.jl/pull/863. However, even that is not 100% consistent -- it did seem to depend on whether I included Revise or not at some point.

In a nutshell, Documenter needs to do a `signature in existing_signatures` check (where `existing_signatures :: Set{Type}`). But the `in` doesn't work properly. The bad hashing leads to:

```
julia> t1 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}}
Tuple{AbstractArray, AbstractArray{<:Integer}, UnitRange{<:Integer}}

julia> t2 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}}
Tuple{AbstractArray, AbstractArray{<:Integer}, UnitRange{<:Integer}}

julia> t1 == t2
true

julia> s = Set{Type}([t1, t2])
Set{Type} with 2 elements:
  Tuple{AbstractArray, AbstractArray{<:Integer}, UnitRange{<:Integer}}
  Tuple{AbstractArray, AbstractArray{<:Integer}, UnitRange{<:Integer}}
```

I checked the StatsBase docs build failure on 1.8.5 and 1.9.0-rc3. 

X-ref: https://julialang.slack.com/archives/C66L48G1X/p1683135789756359

**Comment by ararslan** [comment]
On current master, it seems that the `objectid` of the first definition differs from all subsequent definitions, which are equal to one another.
```
julia> t1 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> t2 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> t3 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> t4 = Tuple{AbstractArray,AbstractArray{<:Integer},UnitRange{<:Integer}};

julia> objectid.([t1, t2, t3, t4])
4-element Vector{UInt64}:
 0xed23fe44110a2d2c
 0x6663357f3c298ad5
 0x6663357f3c298ad5
 0x6663357f3c298ad5
```

**Comment by vtjnash** [comment]
We eventually need to swap objectid for the actual hash function that agrees with ==

It is implemented in jltypes.c, because the runtime needs it, but it never got exported to Julia so that Dict would work correctly (only IdDict)

**Comment by vtjnash** [comment]
That implementation of `typehash` for `hash(::Type, ::UInt)` SGTM

**Comment by ararslan** [comment]
> That is not a problem for `objectid` / `IdDict`, since we also observe that those keys are `!==`

The fact that they're `!==` is the heart of this issue though, isn't it? 😄 AFAICT, there's no reason why `t1` and `t2` should have differing object IDs. (That said, defining `hash(::Type, ::UInt)` as you suggest does fix the `Set` case noted in the OP).
