### ISSUE TITLE
`x=A\b` by `qr(A, ColumnNorm()) \ B`,  Matrix division does not yield `Ax=b`

### ISSUE THREAD

**Issue by maxchendt** [JuliaLang/julia#49625]
see the example in https://discourse.julialang.org/t/matrix-division-vs-compute-by-hand-why-such-big-difference/98288

**Comment by aravindh-krishnamoorthy** [comment]
Your matrix `H` is rank deficient.

**Comment by cafaxo** [comment]
The question is if the two solutions
```
G = qr(H', ColumnNorm())
z = G.P*inv(G.R)*Matrix(G.Q)'*v
display(norm(H'*z-v, Inf))  #4.755666482359269e-12

z1 = G\v
display(norm(H'*z1-v, Inf)) #0.00010237343843657264
```
 are equally good. To find that out, we check how badly `norm(H'*z - v)` could be affected by a small relative perturbation of `z`. This can be crudely estimated by `opnorm(H')*norm(z) ≈ 4e10`. Under this simple analysis, it seems that both solutions are indeed equally good.

**Comment by aravindh-krishnamoorthy** [comment]
I could take a detailed look at this and provide my analysis below. Kindly note that I've deleted my earlier comment and incorporated the observation into this post.

It seems that the supplied matrix `H` (dimension $110 \times 73$) has a condition number of `H` is $2.35\cdot 10^{14}$ and minimum singular value $10^{-9}.$ 

Julia's algorithm for `\` is based on LAPACK's XGELSY and is implemented in [qr.jl](https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/qr.jl), see `ldiv!`. The default value of `rcond`, which influences rank detection, is set to `min(size(A)...)*eps(real(T))`, and, in your case, is $1.62\cdot 10^{-14}.$

This default value seems to be suboptimal for `H`, as it leads to XGELSY inferring a rank of $72$ for `H`.

Nevertheless, Julia can be forced to utilize `rcond = 0` via following definition:
```julia
LinearAlgebra.ldiv!(A::QRPivoted{T,<:StridedMatrix}, B::AbstractMatrix{T}) where {T<:LinearAlgebra.BlasFloat} = ldiv!(A, B, 0)[1]
```
which is essentially your "by hand" (full rank) algorithm, along with the numerical tricks from LAPACK. The overriding definition needs to be added just above `main` in your script.

Upon executing your script with the definition incorporated, we obtain:
```julia
julia> include("maxchendt.jl")
3.21210389377572e-12
46000.16481540046
1.3835660378303895e-13
46000.16481538737
```
which shows that the numerical tricks indeed have had a (minor) impact.

This was a lucky case. There are other matrices, surely, for which `rcond = 0` would make the result worse. So, the figuring out the "right" value of `rcond` is probably difficult. Either that, or perhaps expose `rcond` to experienced users in a cleaner way. HTH.

**Comment by maxchendt** [comment]
```Julia
F = lq(H)
z2 = F'\v
display(norm(H'*z2-v, Inf))  #1.1368683772161603e-13
```
informed by https://discourse.julialang.org/t/julia-linear-system-solver-mldivide/33447/2 , using `lq` is a good idea.

**Comment by aravindh-krishnamoorthy** [comment]
> ```julia
> F = lq(H)
> z2 = F'\v
> display(norm(H'*z2-v, Inf))  #1.1368683772161603e-13
> ```
> 
> informed by https://discourse.julialang.org/t/julia-linear-system-solver-mldivide/33447/2 , using `lq` is a good idea.

Unfortunately, there is no silver bullet. `lq` and your by-hand methods work so long as the numerical error in `inv(H)` can be tolerated. If the condition number of `H` increases, e.g., the smallest singular value drops further (or there are several small singular values), then `lq` and your by-hand methods will have a poorer performance compared to LAPACK's XGELSY. It's a trade off. This is also stated in the post.

If your `H` maintains this structure, then `lq` and your by-hand methods indeed work well. However, for a robust implementation, it seems that you're better off estimating `rcond` yourself and passing it to the algorithm, see the documentation of `rcond` here: https://netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga385713b8bcdf85663ff9a45926fac423.html

**Comment by dkarrasch** [comment]
I'm closing this and suggest to continue the discussion on discourse, as it seems that there is nothing actionable at the moment, but please feel free to reopen if something occurs.
