### ISSUE TITLE
Result of adding a scalar to a `LinRange` changes if said `LinRange` is collected first.

### ISSUE THREAD

**Issue by dafred94** [JuliaLang/julia#49621]
1. versioninfo()
> Julia Version 1.8.1
> Commit afb6c60d69 (2022-09-06 15:09 UTC)
> Platform Info:
>   OS: Windows (x86_64-w64-mingw32)
>   CPU: 12 × Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
>   Threads: 6 on 12 virtual cores
> Environment:
>   JULIA_EDITOR = code
>   JULIA_NUM_THREADS = 6
2. I Installed Julia using an installer downloaded from julialang.org
3. MWE
```
r = LinRange(Float16(0.0), Float16(20.0*pi), 1024)
h = Float16(0.01)

id_no_collect = findfirst((r .+ h) .== r)        # 253
id_collect = findfirst((collect(r) .+ h) .== r)  # 522
```

As indicated above, the result of adding a scalar to a `LinRange` depends on whether `collect` is applied to it first. Is this desired/expected behaviour?

**Comment by barucden** [comment]
I am not sure if the behavior is desired but [it is known](https://github.com/JuliaLang/julia/pull/45947#issuecomment-1422309467).

The result of `r .+ h` is a range again:
```julia
julia> typeof(r .+ h)
LinRange{Float16, Int64}
```
and I believe that the computation is done as follows:
```julia
result = LinRange(first(r) + h, last(r) + h, 1024);
# result == (r .+ h) is true
```
which is theoretically correct but not equivalent to `collect(r) .+ h` due to numerical inaccuracies.

**Comment by StefanKarpinski** [comment]
The operation of adding a scalar to a range giving a range back is both more efficient and more accurate; when you do the collection first, you lose accuracy and use more memory. I'll give an example. First, let's compute the true range in fully accurate 64-bit precision:
```jl
Y = Float64[(i-1)*20big(pi)/(1024-1) + h for i=1:1024]
```
Using that we can see that in some individual cases doing `r[i] + h` is less accurate than doing `(r .+ h)[i]`:
```jl
julia> i = 505
505

julia> Y[i]
30.965284588024325

julia> r[i] + h
Float16(30.98)

julia> (r .+ h)[i]
Float16(30.97)

julia> (r[i] + h) - Y[i]
0.01909041197567518

julia> (r .+ h)[i] - Y[i]
0.003465411975675181
```
But what about overall? I'm going to define a little helper function that checks if its second argument is closer to its first argument than it's third argument is:
```jl
closer(v, a, b) = abs(v - a) < abs(v - b)
```
With this we can check which approximation of `Y` is better:
```
julia> mean(closer.(Y, collect(r) .+ h, r .+ h))
0.01953125

julia> mean(closer.(Y, r .+ h, collect(r) .+ h))
0.2255859375
```
So less than 2% of the time collecting first is better whereas `r .+ h` is better 22.5% of the time.

Anyway, all that is to say that what the `r .+ h` is doing is correct and the only way to make it match `collect(r) .+ h` would be to make that its implementation, which would be less efficient and less accurate.
