### ISSUE TITLE
Documentation inference blog posts links broken

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#49677]
The links to the blog posts are broken

> Julia's approach to inference has been described in blog posts (1, 2).

https://docs.julialang.org/en/v1/devdocs/inference/

**Comment by giordano** [comment]
* https://info.juliahub.com/inference-convergence-algorithm-in-julia
* https://info.juliahub.com/inference-convergence-algorithm-in-julia-revisited

**Comment by ViralBShah** [comment]
Fixed in #49031
