### ISSUE TITLE
Float literal `17.328679084777833f0` is not correctly rounded

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#49689]
`17.328679084777833f0` is not correctly rounded when parsed by the Julia parser:

```julia
julia> [big"17.328679084777833" - 17.328679084777833f0
        big"17.328679084777833" - nextfloat(17.328679084777833f0)]
2-element Vector{BigFloat}:
  9.536743173750000000000000000000000000000000000000000000000000000000000819773977e-07
 -9.536743154374999999999999999999999999999999999999999999999999999999999180226023e-07
```

Noticed over at https://github.com/JuliaLang/JuliaSyntax.jl/issues/134#issuecomment-1357134061

I haven't dug deep into whatever the problem is here (likely in the flisp `read` code), but the float literal parsing in JuliaSyntax.jl avoids whatever it is by calling `jl_strtof_c` directly. We see:

```
julia> (@ccall jl_strtof_c("17.328679084777833"::Ptr{UInt8}, C_NULL::Ptr{Ptr{UInt8}})::Cfloat) - 17.328679084777833f0
1.9073486f-6
```

CC @oscardssmith

**Comment by inkydragon** [comment]
This is probably due to the fact that we performed rounding twice.

https://github.com/JuliaLang/julia/blob/7ef78e45b3aa7fb523919fe6c6dd3182b88d5b6c/src/support/strtod.c#L278-L281

```c
#include <stdlib.h>  
#include <stdio.h>  

int main()
{
    const char* str;
    char* stopstring;
    float ff;
    double dd;

    str = "17.328679084777833";
    ff = strtof(str, &stopstring);
    dd = strtod(str, &stopstring);
    printf("string = %s\n", str);
    printf("strtod = %f\n", dd);
    printf("strtof = %f\n", ff);
    printf("  d->f = %f\n", (float)dd);
}
```

*out*
```
string = 17.328679084777833
strtod = 17.328679
strtof = 17.328680
  d->f = 17.328678
```

test with 
- win10 + MSVC 2019 
- win10 + gcc 12.2.0 (mingw64)
- Ubuntu 20.04.6 + gcc 9.4.0 (WSL2)

**Comment by oscardssmith** [comment]
yeah, that's just broken. why do we do it that way?

**Comment by vtjnash** [comment]
That seems more-or-less what everyone does. For example, here's the source for gdtoa-strtof from Apple (gdtoa is the upstream distribution that most *nix seem to use): https://opensource.apple.com/source/Libc/Libc-391/gdtoa/FreeBSD/gdtoa-strtof.c.auto.html

**Comment by oscardssmith** [comment]
Closing now that JuliaSyntax is the default parser (which rounds this correctly).
