### ISSUE TITLE
1.8.5 -> 1.9 regression in number of allocations from `getproperty`

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#49697]
The execution time is similar for this small example, but there are 10x more allocations on 1.9-rc3.

```
using BenchmarkTools
using Plots
const xx = randn(20, 3000)
@btime plot(xx; color = :blue, label = nothing);

# 1.8.5
# 1.214 s (392640 allocations: 31.88 MiB)

# 1.9-rc3
# 1.166 s (3964617 allocations: 86.43 MiB)
```

From https://github.com/JuliaPlots/Plots.jl/issues/4742

**Comment by KristofferC** [comment]
This needs more of a reduction for this to be actionable over just a `@btime plot`.

**Comment by BioTurboNick** [comment]
Working on it

**Comment by BioTurboNick** [comment]
The allocations are almost entirely originating from `getproperty` with `UnknownType`, according to `@profview_allocs`.
![Screenshot 2023-05-09 105936](https://github.com/JuliaLang/julia/assets/1438610/c5b1e707-155f-4f0d-96cd-e3fc5850c52c)

Specifically, this method: https://github.com/JuliaLang/julia/blob/master/base/Base.jl#L37

**Comment by BioTurboNick** [comment]
Possibly related: #49241

**Comment by KristofferC** [comment]
> Possibly related: https://github.com/JuliaLang/julia/issues/49241

Could check if the offending commit bisected in that PR (https://github.com/JuliaLang/julia/pull/47371) is the cause by looking at the results one commit before it. Could also try to bisect this but I suspect it will be a bit difficult since it might not be one commit that is to blame for the whole allocation increase.

**Comment by BioTurboNick** [comment]
I boiled it down to a simple demonstration:
```
const s = Set()
@time s.dict # 0.000003 seconds (1 allocation: 16 bytes)
```

Bisect pinpointed #47371 as you thought.

**Comment by KristofferC** [comment]
Putting that in a function makes it not appear anymore

```julia
julia> s = Set();

julia> f(s) = s.dict;

julia> @time f(s);
  0.000004 seconds
```

So how does this manifest itself within plots? Is it because `s` is not inferred proerly where the `getproperty` is called or something like that?

**Comment by BioTurboNick** [comment]
Current master (e204e200df) still has it

**Comment by BioTurboNick** [comment]
Via https://github.com/JuliaLang/julia/blob/e204e200df8f57e516920c056b6ec2eb37d34079/base/set.jl#LL124C1-L124C60

https://github.com/JuliaLang/julia/blob/8e630552924eac54c809aa7bc30871c7df1582d3/base/dict.jl#L700

and

https://github.com/JuliaLang/julia/blob/8e630552924eac54c809aa7bc30871c7df1582d3/base/dict.jl#L702

**Comment by BioTurboNick** [comment]
The constant is a `Set{Symbol}`

**Comment by BioTurboNick** [comment]
Yeah, the cases responsible are all iterating over global constant sets of symbols, or over `keys()` of a global constant `Dict{Symbol, Any}`,

**Comment by 3f6a** [comment]
Milestone 1.10 means no chance this gets fixed on a 1.9.x ?

**Comment by KristofferC** [comment]
No that's not what it means. It means that it is a release blocker for 1.10. That's all.

**Comment by 3f6a** [comment]
Ok thanks, sorry for the noise.

**Comment by KristofferC** [comment]
@BioTurboNick, could you check how the situation is on the https://github.com/JuliaLang/julia/pull/50507 branch?

**Comment by BioTurboNick** [comment]
@KristofferC Yes it appears to be fixed!

The OP example on the backports-release-1.9 branch:
```
(393150 allocations: 32.11 MiB)
```
