### ISSUE TITLE
invalid instruction on 1.9.3 when `using LLVM`

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#49705]
i have an on-premise cluster with a shared filesystem.  on julia 1.8, `using CUDA` works just fine when i switch back and forth between a machine with a Nvidia V100 and a separate machine with an A100.  but on 1.9-rc3, while it properly recompiles if i first do it on the A100 machine, and then switch to the V100, if i do it the other way around (first V100 where it compiles, and then switch to A100) i get the error below instead of a nice message that it is precompiling.  seemingly julia doesn't understand that it needs to recompile.

```
julia> using CUDA
Invalid instruction at 0x14bd6b8e32f8: 0x62, 0xf1, 0x7d, 0x08, 0x76, 0xc1, 0xc5, 0xf8, 0x44, 0xc0, 0xc5, 0xfb, 0x93, 0xc0, 0xa8

[2060742] signal (4.2): Illegal instruction
in expression starting at REPL[1]:1
__init__ at /groups/scicompsoft/home/arthurb/.julia/packages/LLVM/TLGyi/src/LLVM.jl:103
jfptr___init___863 at /groups/scicompsoft/home/arthurb/.julia/compiled/v1.9/LLVM/e8NBy_sTSrY.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
jl_module_run_initializer at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:75
ijl_init_restored_modules at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/module.c:982
register_restored_modules at ./loading.jl:1074
_include_from_serialized at ./loading.jl:1020
_tryrequire_from_serialized at ./loading.jl:1356
_require_search_from_serialized at ./loading.jl:1459
_require at ./loading.jl:1748
_require_prelocked at ./loading.jl:1625
macro expansion at ./loading.jl:1613 [inlined]
macro expansion at ./lock.jl:267 [inlined]
require at ./loading.jl:1576
jfptr_require_51256.clone_1 at /groups/scicompsoft/home/arthurb/.julia/juliaup/julia-1.9.0-rc3+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
call_require at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:466 [inlined]
eval_import_path at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:503
jl_toplevel_eval_flex at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:731
jl_toplevel_eval_flex at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:856
ijl_toplevel_eval_in at /cache/build/default-amdci4-4/julialang/julia-release-1-dot-9/src/toplevel.c:971
<SNIP>
```

**Comment by maleadt** [comment]
Can you reproduce this when just loading LLVM.jl, which seems like what's failing here?
Also, since I can't reproduce, maybe you could record an `rr` trace using `julia --bug-report=rr` (again, preferably when only loading LLVM.jl, not all of CUDA.jl).

**Comment by Keno** [comment]
> between a machine with a Nvidia V100 and a separate machine with an A100

What are the CPU models of these two machines?

**Comment by bjarthur** [comment]
the V100 is Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz, the A100 AMD EPYC 7413 24-Core Processor.  i can provide the full output of `cat /proc/cpuinfo` if you need more details.

**Comment by bjarthur** [comment]
am having trouble recording an rr trace.  after adding BugReporting (v0.3.2), i envoke julia with `JULIA_RR_RECORD_ARGS=-n julia --bug-report=rr`.  it reports "Saving execution to trace directory /tmp/jl_csVrsA/julia-0".  i ctrl-Z out and see a bunch of stuff there.  then i `using LLVM` (instead of CUDA) and get the same error as above.  immediately after that error is this one:

```
### IMPORTANT =============================================================
You are about to upload a trace directory to a publicly accessible location.
Such traces contain any information that was accessed by the traced
executable during its execution. This includes any code loaded, any
secrets entered, the contents of any configuration files, etc.

DO NOT proceed, if you do not wish to make this information publicly available.
By proceeding you explicitly agree to waive any privacy interest in the
uploaded information.
### =======================================================================

WARNING: both Exceptions and ConcurrentUtilities export "try_with_timeout"; uses of it in module Connections must be qualified
ERROR: TaskFailedException
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:920
  [2] wait()
    @ Base ./task.jl:984
  [3] wait(c::Base.GenericCondition{ReentrantLock}; first::Bool)
    @ Base ./condition.jl:130
  [4] wait
    @ ./condition.jl:125 [inlined]
  [5] take_unbuffered(c::Channel{Any})
    @ Base ./channels.jl:473
  [6] take!
    @ ./channels.jl:450 [inlined]
  [7] get_upload_params()
    @ BugReporting ~/.julia/packages/BugReporting/Qj6TJ/src/BugReporting.jl:618
  [8] (::BugReporting.var"#33#35"{Vector{String}})(trace_dir::String)
    @ BugReporting ~/.julia/packages/BugReporting/Qj6TJ/src/BugReporting.jl:549
  [9] mktempdir(fn::BugReporting.var"#33#35"{Vector{String}}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:760
 [10] mktempdir (repeats 2 times)
    @ ./file.jl:756 [inlined]
 [11] make_interactive_report(report_arg::String, ARGS::Vector{String})
    @ BugReporting ~/.julia/packages/BugReporting/Qj6TJ/src/BugReporting.jl:545
<SNIP>
```

julia then exits, and i try to look in the "/tmp/jl_csVrsA/julia-0" again and it does not exist.

**Comment by giordano** [comment]
Feels like the problem is that you're attempting to load native code compiled for an ISA (skylake) on a CPU with a smaller ISA (zen3), and the fact that this happens only on v1.9 is because only on this version packages cache native code.

@vchuravy is the compiled cache indexed by the CPU target?

**Comment by giordano** [comment]
> It's supposed to be, yes

Where exactly? Skimming through the code I could only find 
https://github.com/JuliaLang/julia/blob/b9b8b38ec09b4e91b46fa833c609e0cf2b9eba45/base/loading.jl#L2175-L2178
but if I remember correctly the default `unsafe_string(JLOptions().cpu_target)` is just `native`.

**Comment by vchuravy** [comment]
What is `JULIA_DEBUG=loading`. We should be writing out the target features we used... And discard anything that can't be loaded.

**Comment by bjarthur** [comment]
maybe a 1.9 milestone tag for this?  would be nice to see it fixed in a point release.  thx.

**Comment by KristofferC** [comment]
How would a 1.9 milestone tag help with anything here? 1.9 is already released.

**Comment by bjarthur** [comment]
@mkitti

**Comment by ViralBShah** [comment]
Please reopen if still an issue with the latest 1.9.x

**Comment by bjarthur** [comment]
@ViralBShah sadly, it's still a problem.  can you please re-open this issue?  i can't seem to.

the work around is to use `--pkgimages=no`.  or just stick with v1.8.

**Comment by vchuravy** [comment]
One helpful thing would be to break in GDB and use `disassemble` to show what the instruction is that is illegal.

Could you also print `/proc/cpuinfo`.

**Comment by bjarthur** [comment]
procinfo is easy.  will get back to you with gdb...

<details>
<summary>A100</summary>

vendor_id	: AuthenticAMD
cpu family	: 25
model		: 1
model name	: AMD EPYC 7413 24-Core Processor
stepping	: 1
microcode	: 0xa0011ce
cpu MHz		: 2650.000
cache size	: 512 KB
physical id	: 1
siblings	: 48
core id		: 29
cpu cores	: 24
apicid		: 123
initial apicid	: 123
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5283.84
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

</details>

<details>
<summary>V100</summary>

vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz
stepping	: 4
microcode	: 0x2006e05
cpu MHz		: 3700.000
cache size	: 33792 KB
physical id	: 1
siblings	: 48
core id		: 29
cpu cores	: 24
apicid		: 123
initial apicid	: 123
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple shadow_vmcs pml ept_mode_based_exec tsc_scaling
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit mmio_stale_data retbleed
bogomips	: 4207.92
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

</details>

**Comment by bjarthur** [comment]
i'm getting "ERROR: Unable to find compatible target in system image." after building with `make debug` on the A100 box and executing `usr/bin/julia-debug` on the V100 box.  i think that means i need to set `ARCH` or `MARCH` in "Make.user".  what should they be?  here's what's in there now:

```
OPENBLAS_TARGET_ARCH=NEHALEM
OPENBLAS_DYNAMIC_ARCH = 0
CMAKE = /groups/scicompsoft/home/arthurb/src/julia/deps/scratch/cmake-3.7.1-Linux-x86_64/bin/cmake
```

**Comment by mkitti** [comment]
I have access to the same cluster as @bjarthur . I think we need some combination of the following in `JULIA_CPU_TARGET`
* znver3 (AMD Milan)
* skylake-avx512 (Intel(R) Xeon(R) Platinum 8160,)
* cascadelake (Intel Gold Xeon 6248R)
* sapphirerapids

**Comment by ViralBShah** [comment]
So is this not just on 1.9-rc3, and still an issue on 1.9? Asking so that we can update the issue title.

**Comment by bjarthur** [comment]
indeed, switching back and forth between two architectures on julia 1.9.3 causes an "invalid instruction" error.  i had thought the native code was supposed to be cached in an architecture specific way.  i've changed the title of this issue to reflect that it's not just in the beta release of 1.9, and occurs with LLVM.jl too and not just CUDA.jl.

julia 1.10-beta3 is a bit better, but still not useable on my heterogeneous cluster.  it does NOT throw an "invalid instruction" (great!) but rather recompiles *everytime* when switching to a different architecture. so if i try to distribute jobs simultaneously, the cached code gets overwritten and processes fail.  the same workaround as with 1.9 must hence be used:  either restrict my distributed jobs to a subset of the cluster which all has the same architecture (using `-R"select[...]"` on our LSF cluster), or use julia's `--pkgimages=no`.  should i file a separate issue re. 1.10?

**Comment by vchuravy** [comment]
So if you can please attach gdb and print out the disassembly of the instruction.

I don't have access to a Cascade lake machine

**Comment by Octogonapus** [comment]
I am having a nearly identical issue.
- Julia v1.9.3
- Julia code is built into a Docker container on `Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz`
- The container is ran on `13th Gen Intel(R) Core(TM) i9-13900K`

Error is:
```
Invalid instruction at 0x7efc33613a48: 0x62, 0xf1, 0x7d, 0x08, 0x76, 0xc1, 0xc5, 0xf8, 0x44, 0xc0, 0xc5, 0xfb, 0x93, 0xc0, 0xa8

[33358] signal (4.2): Illegal instruction
in expression starting at REPL[1]:1
__init__ at /root/.julia/packages/LLVM/QadjB/src/LLVM.jl:102
jfptr___init___670 at /root/.julia/compiled/v1.9/LLVM/e8NBy_AujAU.so (unknown line)
_jl_invoke at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/julia.h:1880 [inlined]
jl_module_run_initializer at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/toplevel.c:75
ijl_init_restored_modules at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/module.c:982
register_restored_modules at ./loading.jl:1115
```

Relevant assembly:
```asm
   0x00007f8f69c139ea <+890>:	mov    %r12,0x38(%rsp)
   0x00007f8f69c139ef <+895>:	mov    %r15,0x40(%rsp)
   0x00007f8f69c139f4 <+900>:	mov    0x70(%rsp),%rax
   0x00007f8f69c139f9 <+905>:	mov    %rax,0x48(%rsp)
   0x00007f8f69c139fe <+910>:	mov    %r13,0x50(%rsp)
   0x00007f8f69c13a03 <+915>:	mov    %rcx,0x58(%rsp)
   0x00007f8f69c13a08 <+920>:	xor    %eax,%eax
   0x00007f8f69c13a0a <+922>:	mov    %eax,%edi
   0x00007f8f69c13a0c <+924>:	mov    $0x9,%edx
   0x00007f8f69c13a11 <+929>:	lea    0x18(%rsp),%rsi
   0x00007f8f69c13a16 <+934>:	call   0x7f8f69c15a50 <jl_f__call_latest@plt>
   0x00007f8f69c13a1b <+939>:	lea    0x100(%rsp),%rsi
   0x00007f8f69c13a23 <+947>:	lea    0x180(%rsp),%rdi
   0x00007f8f69c13a2b <+955>:	vzeroupper 
   0x00007f8f69c13a2e <+958>:	call   0x7f8f69c11fe0 <julia_runtime_version_655>
   0x00007f8f69c13a33 <+963>:	mov    0x549d2e(%rip),%r14        # 0x7f8f6a15d768 <jl_globalYY.147>
   0x00007f8f69c13a3a <+970>:	vmovq  (%r14),%xmm0
   0x00007f8f69c13a3f <+975>:	vmovq  0x180(%rsp),%xmm1
=> 0x00007f8f69c13a48 <+984>:	vpcmpeqd %xmm1,%xmm0,%k0
   0x00007f8f69c13a4e <+990>:	knotw  %k0,%k0
   0x00007f8f69c13a52 <+994>:	kmovd  %k0,%eax
   0x00007f8f69c13a56 <+998>:	test   $0x3,%al
   0x00007f8f69c13a58 <+1000>:	sete   %r12b
   0x00007f8f69c13a5c <+1004>:	mov    0x8(%r14),%eax
   0x00007f8f69c13a60 <+1008>:	cmp    0x188(%rsp),%eax
   0x00007f8f69c13a67 <+1015>:	sete   %r13b
   0x00007f8f69c13a6b <+1019>:	mov    0x10(%r14),%rdi
   0x00007f8f69c13a6f <+1023>:	mov    0x190(%rsp),%rsi
   0x00007f8f69c13a77 <+1031>:	mov    $0x1,%bl
   0x00007f8f69c13a79 <+1033>:	mov    %ebx,%r15d
   0x00007f8f69c13a7c <+1036>:	cmp    %rsi,%rdi
   0x00007f8f69c13a7f <+1039>:	je     0x7f8f69c13a9b <julia___init___669+1067>
   0x00007f8f69c13a81 <+1041>:	mov    -0x8(%rdi),%rdx
   0x00007f8f69c13a85 <+1045>:	and    $0xfffffffffffffff0,%rdx
   0x00007f8f69c13a89 <+1049>:	mov    -0x8(%rsi),%rax
   0x00007f8f69c13a8d <+1053>:	and    $0xfffffffffffffff0,%rax
   0x00007f8f69c13a91 <+1057>:	cmp    %rax,%rdx
```

Relevant source listing (we are on line 102):
```julia
97	        # this checks that the precompilation image isn't being used
98	        # after having upgraded Julia and the contained LLVM library.
99	        @error """LLVM.jl was precompiled for LLVM $libllvm_version, whereas you are now using LLVM $(Base.libllvm_version).
100	                  Please re-compile LLVM.jl."""
101	    end
102	    if version() !== runtime_version()
103	        # this is probably caused by a combination of USE_SYSTEM_LLVM
104	        # and an LLVM upgrade without recompiling Julia.
105	        @error """Julia was compiled for LLVM $(version()), whereas you are now using LLVM $(runtime_version()).
106	                  Please re-compile Julia and LLVM.jl (but note that USE_SYSTEM_LLVM is not a supported configuration)."""
```

**Comment by vchuravy** [comment]
Does this reproduce on 1.10 as well?

**Comment by vchuravy** [comment]
Ok so:

```
=> 0x00007f8f69c13a48 <+984>:	vpcmpeqd %xmm1,%xmm0,%k0
```

is the AVX-512 variant of this instruction. Note the use of the `k0` mask register.

So the question is why are we not rejecting this cache file?
Can you run with `JULIA_DEBUG=loading`

**Comment by Octogonapus** [comment]
> Did you try setting `JULIA_CPU_TARGET` as suggested in #49705 (comment)?

On 1.9.3, setting `JULIA_CPU_TARGET` to `generic;skylake-avx512,clone_all;znver2,clone_all` when building the container is an effective workaround.

> Can you run with JULIA_DEBUG=loading

The original 1.9.3 container without `JULIA_CPU_TARGET` set:
```julia
┌ Debug: Loading object cache file /root/.julia/compiled/v1.9/LLVMExtra_jll/R9OeX_AujAU.so for LLVMExtra_jll [dad2f222-ce93-54a1-a47d-0025e8a3acab]
└ @ Base loading.jl:1051
┌ Debug: Loading object cache file /root/.julia/compiled/v1.9/LLVM/e8NBy_AujAU.so for LLVM [929cbde3-209d-540e-8aea-75f648917ca0]
└ @ Base loading.jl:1051
Invalid instruction at 0x7f3363a13a48: 0x62, 0xf1, 0x7d, 0x08, 0x76, 0xc1, 0xc5, 0xf8, 0x44, 0xc0, 0xc5, 0xfb, 0x93, 0xc0, 0xa8

[33376] signal (4.2): Illegal instruction
in expression starting at REPL[1]:1
__init__ at /root/.julia/packages/LLVM/QadjB/src/LLVM.jl:102
jfptr___init___670 at /root/.julia/compiled/v1.9/LLVM/e8NBy_AujAU.so (unknown line)
```

> Does this reproduce on 1.10 as well?

I rebuild the container (without `JULIA_CPU_TARGET` set) on 1.10.1. There is no crash on 1.10.1, however precompilation is triggered instead. It seems that env var is still needed to avoid precompilation.

**Comment by vchuravy** [comment]
> There is no crash on 1.10.1, however precompilation is triggered instead.

That is the correct behavior. We successfully detect that the cache file is not compatible with the current system and reject it.

**Comment by vchuravy** [comment]
The native image generation has seen quite a few changes in 1.10, and I think at this point we don't expect another 1.9 release.

If someone is really interested in fixing this I would recommend backporting https://github.com/JuliaLang/julia/pull/50172 and then debugging the rejection mechanism.
