### ISSUE TITLE
slow type definition with repeated Unions

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#49731]
Reduced from RRTMGP.jl (except there, this has even more parameters and fields, and thus takes a few minutes longer)
```julia
julia> @time @eval struct S{FT<:AbstractFloat, A<:Union{Nothing, Val{FT}}, B<:Union{Nothing, Val{FT}}, C<:Union{Nothing, Val{FT}}, D<:Union{Nothing, Val{FT}}, E<:Union{Nothing, Val{FT}}, F<:Union{Nothing, Val{FT}}, G<:Union{Nothing, Val{FT}}}
    a::A; b::B; c::C; d::D; e::E; f::F; g::G;
end

  4.398847 seconds (5.38 M allocations: 2.002 GiB, 3.56% gc time)
```
Not certain there is anything we can do here, but opening this to record it, since it can be a bit of a surprising gotcha, although regardless of this, the runtime will still punish you pretty hard with bad performance everywhere because of those unions (e.g. https://github.com/JuliaLang/julia/pull/49725).

**Comment by Tortar** [comment]
Does this somehow depends on the OS? Can't reproduce on Linux, tried with Julia >=1.6, the MWE takes <0.01s everywhere

**Comment by oscardssmith** [comment]
I think Julia 1.10 fixed a lot of these sorts of cases.
