### ISSUE TITLE
`trunc` with `Float16` is broken on FreeBSD with LLVM 15

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#49768]
After #48700, we're getting this and similar errors during testing on FreeBSD:
```
Error During Test at /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-2/julialang/julia-master/julia-6618d4416d/share/julia/test/rounding.jl:225
  Test threw exception
  Expression: round(Ti, Tf(-0.0)) == 0
  InexactError: trunc(UInt64, -0.0)
  Stacktrace:
   [1] trunc(::Type{UInt64}, x::Float16)
     @ Base ./float.jl:874 [inlined]
   [2] round(::Type{UInt64}, x::Float16)
     @ Base ./float.jl:385
   [3] macro expansion
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-2/julialang/julia-master/julia-6618d4416d/share/julia/stdlib/v1.10/Test/src/Test.jl:512 [inlined]
   [4] macro expansion
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-2/julialang/julia-master/julia-6618d4416d/share/julia/test/rounding.jl:225 [inlined]
   [5] macro expansion
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-2/julialang/julia-master/julia-6618d4416d/share/julia/stdlib/v1.10/Test/src/Test.jl:1546 [inlined]
   [6] top-level scope
     @ /usr/home/julia/.buildkite-agent/builds/freebsd12-amdci6-2/julialang/julia-master/julia-6618d4416d/share/julia/test/rounding.jl:146
```
@gbaraldi has looked into this a bit and found the following oddity.

Linux:
```
julia> @code_lowered trunc(UInt64, Float16(-0.0))
CodeInfo(
1 ─ %1  = Float16(-1.0) < x
└──       goto #3 if not %1
2 ─       @_4 = x < Inf16
└──       goto #4
3 ─       @_4 = false
4 ┄       goto #6 if not @_4
5 ─ %7  = Base.unsafe_trunc(UInt64, x)
└──       return %7
6 ─ %9  = Base.InexactError(:trunc, UInt64, x)
│   %10 = Base.throw(%9)
└──       return %10
)
```
FreeBSD:
```
julia> @code_lowered trunc(UInt64, Float16(-0.0))
CodeInfo(
1 ─ %1  = Float16(-1.0) < x
└──       goto #3 if not %1
2 ─       @_4 = x < -Inf16
└──       goto #4
3 ─       @_4 = false
4 ┄       goto #6 if not @_4
5 ─ %7  = Base.unsafe_trunc(UInt64, x)
└──       return %7
6 ─ %9  = Base.InexactError(:trunc, UInt64, x)
│   %10 = Base.throw(%9)
└──       return %10
)
```
Note the flipped sign on `Inf16`.

**Comment by ararslan** [comment]
The oldest FreeBSD version supported by Julia is 12.2, which is the basis for our CI and Yggdrasil toolchain. FreeBSD 12.2 uses LLVM 10 for clang, compiler-rt, libc++, etc. The issue noted here occurs on FreeBSD 12.2 as well as on later FreeBSD versions using binaries built on 12.2. Notably, 12.2 (and the 12 series as a whole) is EOL and has been for quite some time, so while some FreeBSD developers are active contributors to LLVM, there's likely been limited if any effort toward ensuring support for 12. (Note however that this is speculation.)

FreeBSD 13.2, a current production release, updated the system's LLVM-based tools to LLVM 14. This issue is not reproducible on FreeBSD 13.2, which lead @gbaraldi to hypothesize that compiler-rt ABI breakage between LLVM 10 and 15 may be the culprit.

I think the resolution here will likely need to be updating all things FreeBSD to 13.2. This includes the CI images as well as the Yggdrasil sysroot. We've done this once before when transitioning from FreeBSD 11 to 12; it's annoying but not too bad. The downside is that binaries built on later FreeBSD versions are incompatible with earlier systems, so moving CI to 13.2 means that future patch releases for any currently supported Julia versions will effectively drop support for FreeBSD 12.

**Comment by ararslan** [comment]
cc @staticfloat and @giordano, as the above affects infrastructure with which you're both heavily involved

**Comment by vchuravy** [comment]
Random thought what is the assembly on 1.9 vs master?

**Comment by ararslan** [comment]
As of https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/60, CI now runs on FreeBSD 13.2, which does not have this issue.
