### ISSUE TITLE
Usage of C Macros

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#4983]
`julia.h` contains various C macros. For instance the length of an array is retrieved by calling `jl_array_len`. Unfortunately no symbols are generated for these macros so that they are not accessible in non-C languages (e.g. Python). I presume that this lead to things like

```c
DLLEXPORT int jl_array_rank(jl_value_t *a)
{
    return jl_array_ndims(a);
}
```

in `jlapi.c`

From my point of view, we should find a general solution for this.

Solution a) 
Use upper case for macros, i.e. `JL_ARRAY_LEN`, and define regular functions (lower case) that call the macro

Solution b)
Use inline functions and try to export these into the shared library. I have tried to find out if this is somehow possible but still do not have an answer to that question.

Solution c)
Use regular functions everywhere, which will probably reduce performance in some cases.

Thoughts?

P.S.: Is it ok to use Issues for these kind of questions or is the mailing list a better place for this?

**Comment by yuyichao** [comment]
Making the macro and the exported function having the same name works and we already have many of them. Whether something is worth exporting should be decided on a case-by-case basis and should have their own issue/pr if a exported c-api is needed.

**Comment by tknopp** [comment]
@yuyichao Could you point me to an example where the macro and the exported function have the same name? I am curious which technical solution has been chosen for that now.
The example discussed in the OP is still not solved:
https://github.com/JuliaLang/julia/blob/master/src/jlapi.c#L98

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/blob/a48f45845cd1d5b0e5e5f511291b4f534c267b99/src/jlapi.c#L340

**Comment by tknopp** [comment]
Thanks, so the trick are the braces that prevent the preprocessor to apply the macro definition? Clever.

**Comment by yuyichao** [comment]
Right. Using a different name for the real implementation and undef the macro before defining the function also works (what we used for `jl_typeof` and `jl_astaggedvalue` before).

See https://github.com/JuliaLang/julia/commit/63f3edf300e9fea39a1932ee2e8f1655c845361f#diff-67021262df1246d0b5756f73b92eb69fL176 and https://github.com/JuliaLang/julia/commit/63f3edf300e9fea39a1932ee2e8f1655c845361f#diff-5e2d04b4124ef7886414ec928b84f90bL313

**Comment by tkelman** [comment]
That's pretty confusing and not immediately clear on reading the code. Despite the shoutiness, I think being consistent about upper case for macros is better.
