### ISSUE TITLE
Add `LazilyLoadedLibrary` type to `Libdl`

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#49843]
I was mulling over [the latest issue regarding JLLs eagerly loading libraries](https://github.com/JuliaSparse/Pardiso.jl/issues/90) in their `__init__()` functions (in this case, MKL gets broken if CSL_jll loads `libgomp` first, since it conflicts with symbols loaded from `libiomp5`) and I think I might have a solution.  The way I want to fix that is to have BB analyze libraries for their dependencies, and then instead of eagerly loading them at `__init__()` time, load them at first `ccall` or `dlsym()` time.  The issue is that the code that exists in the wild right now is:

```
using libfoo_jll

ccall((libfoo, :fooify), ...)
```

If I could change the `libfoo` in there to `libfoo()`, I could run a function that JIT loads all the dependent libraries (on a library-by-library basis, no longer eargerly loading all libraries within a single JLL because I don't know which bindings the user is going to want to use) and then returns the SONAME.  Unfortunately, that breaks basically every user code ever.

However, I had an idea; what if we created a `LazilyLoadedLibrary` type that contained within it a list of other `LazilyLoadedLibrary` types which were its dependencies, and the `ccall()` lowering (as well as `dlsym()` and other methods) was taught to load those?  Then the work that the JLLs have to do is just to export these objects for use.  I think it might be possible to maintain pretty good compatibility with the ecosystem if we change a type under their noses, rather than changing all of their syntax.

This would eliminate the vast majority of JLL `__init__()` methods, should speed up launch time, will fix some behavioral bugs, and moves us closer to JLLs being inert pieces of data, rather than code.

**Comment by KristofferC** [comment]
>  and I think I might have a solution. 

I'll just mention that maybe this is not really a 100% solution. Even with libraries lazily loaded you still can't escape the fact that `libgomp` and `libiomp5` cannot coexist in the same process (I think). So even with the laziness proposed here you will still not be able to call someting from CSL_jll and expect having MKL to work.

**Comment by staticfloat** [comment]
Yes, that's true, this just gets us back to v1.8 levels of compatibility where you have to load MKL first and refrain from using anything that requires the libgomp-specific bits.  There's really no solution there as far as I can tell. :(

**Comment by vtjnash** [comment]
The problem isn't calling dlopen either, it is doing it with custom special code in every unique special JLL file. If there were simply an array of things in a magic variable and Base did the actual loading, this would be much less of a problem. Then we could even transition to making them read as a TOML file, instead of executing a Julia file and building a whole Julia module for each one, and apply our existing work towards caching TOML to make that very efficient.

**Comment by KristofferC** [comment]
> The problem isn't calling dlopen either, it is doing it with custom special code in every unique special JLL file. If there were simply an array of things in a magic variable and Base did the actual loading, this would be much less of a problem. 

Most JLLS do kind of the same thing in their `__init__`  so replacing that with some magic variable that contains a list of libraries to dlopen which then that triggers Julia itself to actually open them just after it has loaded that jll seems like it would not be too hard?

**Comment by vtjnash** [comment]
> `__init__()` methods to do things like set environment variables

This is likely unsafe, in that the libc standard defines this to be unsafe, and might cause other libraries (esp. openblas which starts threads) to segfault. This is not advisable.

**Comment by staticfloat** [comment]
> Even that could be done by Base, no? You only really need an init if you need truly arbitrary code execution.

With enough special syntax, yes.  But the question is, what is enough special syntax?  To give some concrete examples, in order of increasing complexity:

* [PMIx](https://github.com/JuliaPackaging/Yggdrasil/blob/806bbbf2cc4882aa3dc3de98fc2924953b1e72f2/P/PMIx/build_tarballs.jl#L67-L69): sets an environment variable to `artifact_dir`.  This is probably the simplest thing, just add an environment mapping that points to the prefix of the artifact.  This could be easily implemented by having a set of environment variables that get mapped to the artifact, e.g. `artifact_envs = Set(["PMIX_PREFIX"])`, and those get set to the artifact directory.
* [Fontconfig](https://github.com/JuliaPackaging/Yggdrasil/blob/806bbbf2cc4882aa3dc3de98fc2924953b1e72f2/F/Fontconfig/build_tarballs.jl#L84): Sets a few environment variables to point to resolved paths within the artifact, but also supports being overridden by environment variables passed in from above.  So extending the above, we could instead store a dictionary and have tokens we can replace, e.g. `envs = Dict("FONTCONFIG_FILE" => "${artifact_dir}/etc/fonts/fonts.conf")`.  We can then have `overrideable_envs = Set(["FONTCONFIG_FILE"])` too, I suppose.  Note that I simplified things a bit here compared to what the `__init__()` is actually doing, but this is sufficient for this discussion.
* [FLINT](https://github.com/JuliaPackaging/Yggdrasil/blob/806bbbf2cc4882aa3dc3de98fc2924953b1e72f2/F/FLINT/build_tarballs.jl#L85): has to make a `ccall()` to register runtime functions with FLINT after opening.  True code execution.
* [CUDA](https://github.com/JuliaPackaging/Yggdrasil/blob/806bbbf2cc4882aa3dc3de98fc2924953b1e72f2/C/CUDA/CUDA_Driver/init.jl): Tim suffers no imitators, all who stare upon the visage of CUDA's `__init__()` method surrender to uncontrollable awe and despair.

**Comment by staticfloat** [comment]
> This is likely unsafe, in that the libc standard defines this to be unsafe, and might cause other libraries (esp. openblas which starts threads) to segfault. This is not advisable.

I'm not really sure we have an alternative.  Some libraries require environment variables to be set before you can call their initialization functions.  For executables we can indeed come up with a better API that applies the environment variables to `Cmd` objects (which is what [`Git.jl` does](https://github.com/JuliaVersionControl/Git.jl/blob/259dc047e11ee326b7d2cac63cb09ceeb8f4711b/src/git_function.jl#L35-L38)) but for poorly-written libraries, I think setting the environment variables in `__init__()` is actually the best choice, as it sets them as early as possible, before user code has a chance to start up more threads and calling other code.
