### ISSUE TITLE
Segmentation Fault During Update

### ISSUE THREAD

**Issue by gideonsimpson** [JuliaLang/julia#49855]
I'm getting the following error:
```
(@v1.9) pkg> up
    Updating registry at `~/.julia/registries/General.toml`
    Updating git-repo `https://github.com/gideonsimpson/StringMethod.jl`
   Installed Accessors ────── v0.1.31
   Installed ArrayInterface ─ v7.4.5
   Installed DiffEqBase ───── v6.125.0
   Installed Distributions ── v0.25.93

[76815] signal (11.1): Segmentation fault: 11
in expression starting at none:0
```
it then otherwise finishes without incident.  I'm running
```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 8 × Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = /Users/grs53/.julia/conda/3/lib:
  JULIA_NUM_THREADS = 4
  JULIA_IMAGE_THREADS = 1

```

**Comment by KristofferC** [comment]
> `  LD_LIBRARY_PATH = /Users/grs53/.julia/conda/3/lib:`

Unset that variable.

**Comment by giordano** [comment]
> Unset that variable.

That doesn't have effect on macOS.

**Comment by gbaraldi** [comment]
It actually should have https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html#//apple_ref/doc/uid/TP40001928-SW12
But apparently doesn't https://medium.com/macos-is-not-linux-and-other-nix-reflections/d-o-y-ou-ld-library-path-you-6ab0a6135a33g does
