### ISSUE TITLE
Huge allocation during precompilation and loading of packages in Julia 1.9.0

### ISSUE THREAD

**Issue by sl-solution** [JuliaLang/julia#49871]
**I installed Julia from official website.**

I encountered the following issue with precompiling and loading of `InMemoryDatasets.jl`.

In Julia 1.9.0 the precompiling and loading cause huge amount of allocation. The precompiling takes about 254 seconds on my mac (the same on Linux) with more than 200 millions allocations. Loading of the package causes the same amount of allocation and it took about 30 seconds.

> Due to this issue I disabled precompiling for the package in Julia 1.9.0

I checked and this is not an issue in Julia 1.10 (4 millions allocation - 66 second prcompilation - less than a second loading time), and this was not an issue in Julia 1.8.5

> I may add one observation here. When I disabled precompilation in 1.9.0, I noticed a huge amount of allocations + 70 seconds time to run `using InMemoryDatasets; t1=now(); @time flatten(Dataset(x=[[1,2],[2]]), 1); t2=now(); t2-t1`. `flatten` and `flatten!` are the only functions with this issue!

**Comment by ufechner7** [comment]
Did you install the package in a fresh environment?
```
mkdir In
cd In
ufechner@tuxedi:~/repos/In$ julia --project="."
```
I get:
```
julia> @time using InMemoryDatasets
┌ Warning: Julia started with single thread, to enable multithreaded functionalities in InMemoryDatasets.jl start Julia with multiple threads.
└ @ InMemoryDatasets ~/.julia/packages/InMemoryDatasets/bvOtK/src/InMemoryDatasets.jl:206
  0.582799 seconds (452.79 k allocations: 31.047 MiB, 38.26% compilation time: 89% of which was recompilation)
```
My environment:
```
(In) pkg> st
Status `~/repos/In/Project.toml`
  [5c01b14b] InMemoryDatasets v0.7.16
```
That precompilation takes longer on 1.9 than on 1.8 is to be expected because 1.9 compiles to binary code while 1.8 does not.

My system:
```
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
```

**Comment by ufechner7** [comment]
If I start Julia with multiple threads it loads even faster:
```
ufechner@tuxedi:~/repos/In$ julia --project -t auto
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0 (2023-05-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time using InMemoryDatasets
  0.378544 seconds (299.49 k allocations: 21.109 MiB, 5.13% compilation time)
```

**Comment by sl-solution** [comment]
In master branch I mitigated the issue by removing anything related to precompiling. You should check out the [J1.9_prec_debug](https://github.com/sl-solution/InMemoryDatasets.jl/tree/J1.9_prec_debug) branch.

Even in the master branch the `flatten` function is weirdly slow.

**Comment by timholy** [comment]
It sounds like there's something busted in your system. Are you using LD_LIBRARY_PATH?

**Comment by ufechner7** [comment]
And why is it fast with Julia 1.9 on my system? I also use Ubuntu 22.04. How much RAM do you have? Which CPU? Do you have only Julia REPL open and no other programs running?
Don't do timing tests in vscode.

**Comment by KristofferC** [comment]
Here is what I get on mac 1.9:

```
# 1 thread
julia> @time using InMemoryDatasets
┌ Warning: Julia started with single thread, to enable multithreaded functionalities in InMemoryDatasets.jl start Julia with multiple threads.
└ @ InMemoryDatasets ~/.julia/packages/InMemoryDatasets/bvOtK/src/InMemoryDatasets.jl:206
  0.599442 seconds (422.12 k allocations: 27.977 MiB, 12.53% compilation time: 92% of which was recompilation)

# 4 threads
julia> @time using InMemoryDatasets
  0.171744 seconds (261.32 k allocations: 16.999 MiB, 4.75% gc time, 4.55% compilation time)
```

**Comment by sl-solution** [comment]
> It sounds like there's something busted in your system. Are you using LD_LIBRARY_PATH?

No LD_LIBRAYR_PATH

**Comment by sl-solution** [comment]
> Here is what I get on mac with julia 1.9.0:

I disabled every thing in the released version (for better user experience), however, as I mentioned it will be weirdly slow to compile some functions, e.g. `flatten(Dataset(x=[[2,3],[2]]))`. 

To reproduce the main issue, please checkout the `J1.9_prec_debug` branch.

```
using Pkg
Pkg.add(url="https://github.com/sl-solution/InMemoryDatasets.jl", rev="J1.9_prec_debug")
```

**Comment by timholy** [comment]
I don't think we should spend a lot of time digging into a branch just disables a huge chunk of functionality that is very useful to almost everyone except, mysteriously, for you. The more relevant question is, what's different about your system that prevents you from getting the benefits that other people are seeing? We're not doubting what you're seeing, but you shouldn't doubt what other people are seeing, either. The problems you're describing are not replicated for anyone else (so far).

Can you try other machines that differ from the one you're testing on?

**Comment by sl-solution** [comment]
It seems Julia 1.9.1 fixed the issue. thanks.
