### ISSUE TITLE
BigFloat regression on macOS between 1.8.5 and 1.9.0

### ISSUE THREAD

**Issue by zbuc** [JuliaLang/julia#49895]
```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292* (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
2.0
```

compare to:

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
1.5
```

`1.9.0` was installed via `homebrew` (i.e. `brew install julia`) and `1.8.5` via `juliaup` (`brew install juliaup; juliaup add 1.8.5`).

I then tried installing `1.9.0` via `juliaup` (`juliaup add 1.9.0; juliaup default 1.9.0`) and now it works as expected (but the `versioninfo()` string is _slightly_ different in the way it prints the commit hash? The `OS` string also mismatches, perhaps there's a library issue going on: `OS: macOS (arm64-apple-darwin21.5.0)` vs `OS: macOS (arm64-apple-darwin22.4.0)`)

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

julia> x = BigFloat(1.5)
1.5
```

So there seems to be something going on with the `1.9.0` builds being published to homebrew.

**Comment by giordano** [comment]
Sounds like a problem in the homebrew distribution of Julia, which isn't maintained in this repository. Can you please open an issue in homebrew? CC @fxcoudert.

**Comment by zbuc** [comment]
Opened https://github.com/Homebrew/homebrew-core/issues/131422

**Comment by fxcoudert** [comment]
The issue is that Julia is relying on a wrong behaviour in old MPFR versions, which was fixed recently. This one-line change https://github.com/JuliaLang/julia/commit/1e5fdb29f8858f3244f6aff116ee12e4c8247f3a#diff-5367a24cd5303d6218f61148f2db355c3f3c682ec003630cf9730fa02b8d8429L1056-R1084 should be backported to all open Julia branches.
