### ISSUE TITLE
Windows 10 shuts down when using matplotlib savefig() with Julia 1.8.2

### ISSUE THREAD

**Issue by qcazenave** [JuliaLang/julia#49950]
Hi,
I have an issue when saving figures with matplotlib on Julia 1.8.2 : the PC shuts down with a message saying that an error has occured and the computer needs a restart.
I noticed the problem was solved when I modified the filename of the output figure. I thought maybe the problem was the length of the filename: maybe the maximum threshold of accepted bytes was exceeded, which made the computer crash (although I find this reaction a little extreme...)
However, when I have a look at the result of `varinfo()`, I notice that the computer crashes when the filename is 159 bytes but it does not crash when the filename is 165 bytes...
So I am wondering what is happening here...

`versioninfo()`
`Julia Version 1.8.2
Commit 36034abf26 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 12th Gen Intel(R) Core(TM) i7-1270P
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 16 virtual cores`

PC configuration: HP EliteBook 640 G9 - Processor Intel Core i7-1270P (12th Gen) - RAM 32 Go - Windows 10 Pro

**Comment by Seelengrab** [comment]
Hello!

Please provide a minimal reproducible example for the error - this is quite minimal information to go on. Since matplotlib is doing the plotting here and changing the filename solved the issue, it sounds to me like an issue with matplotlib rather than julia. Also, how are you calling `matplotlib` from Julia?

**Comment by vtjnash** [comment]
Since your kernel is crashing, it sounds like you either have a bad hard drive or bad memory. Those are both quite common hardware problems have have been reported here before.

**Comment by qcazenave** [comment]
Hi,
Unfortunately, since I found a solution, I stupidely erased the case that didn't work so I don't have tracks of the piece of code that caused the PC to crash (and it seems I can't get it back...).
My statement was incorrect, I am using Pyplot (`using Pyplot` at the beginning of the code) and not the entire matplotlib package.
With the IT team, we first decided to change the PC, but the problem remained. I then found that changing the name of the .png file could solve it. But the IT guy was surprised that the new PC still crashed so I thought I would ask here. But I understand the lack of information is a problem. I guess I will leave it as is (it is not as if I was stuck, anyway).
Thank you very much for taking the time to answer me.

**Comment by mgkuhn** [comment]
Without knowing the exact full pathname (including that of the current working directory in case of a relative path) that triggered this, it is very difficult to guess the cause.

Keep in mind that [Windows by default still limits pathnames to 260 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation). You can remove that restriction in the registry field `LongPathsEnabled`.

There have in the past been Windows bugs causing crashes related to long path names. Make sure you use a currently supported and up-to-date operating-system version. If the operating system crashes, include the full build number displayed by `winver` in your bug report. (Perhaps `versioninfo()` should include that information?)

**Comment by vtjnash** [comment]
That is strange it would follow you between computers, but still, it sounds like there is some sort of hardware issue, or you have found a bug in the Windows kernel.

**Comment by qcazenave** [comment]
Thank you all for your advice, I will keep them in mind in the future, if the problem arises again.
