### ISSUE TITLE
close() on an mmapped io / iostream does not actually fully close the file on Windows

### ISSUE THREAD

**Issue by Tobriand** [JuliaLang/julia#49961]
If you attempt to follow the example of:

```
s = open("some_file.bin", "r")
m = Mmap.mmap(s)
close(s)
rm("some_file.bin")
```

on Windows, you get a file access error.

I _suspect_ this is because of the requirement on windows to release `file_desc` generated via `file_desc = gethandle(io)` on line 210 of mmap.jl - this is not handled in the finalizer.

Notable from [MSDN](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-170):

> To close a file whose operating system (OS) file handle is obtained by _get_osfhandle, call [_close](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=msvc-170) on the file descriptor fd. Never call CloseHandle on the return value of this function. The underlying OS file handle is owned by the fd file descriptor, and is closed when [_close](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=msvc-170) is called on fd. If the file descriptor is owned by a FILE * stream, then calling [fclose](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fclose-fcloseall?view=msvc-170) on that FILE * stream closes both the file descriptor and the underlying OS file handle. In this case, don't call [_close](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=msvc-170) on the file descriptor.

> 
> By default, this function's global state is scoped to the application. To change this behavior, see [Global state in the CRT](https://learn.microsoft.com/en-us/cpp/c-runtime-library/global-state?view=msvc-170).

Currently this is obtained by a discarded reference obtained via `gethandle` defined on line 112:

```
function gethandle(io::IO)
    handle = Libc._get_osfhandle(RawFD(fd(io)))
    Base.windowserror(:mmap, handle == INVALID_OS_HANDLE)
    return handle
end
```

Intuitively, the outcome of calling `RawFD` may need to be captured, and subsequently closed via [_close](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=msvc-170). It is possible this is expected to take place when the stream is closed (I have not verified or refuted this as yet), but notably it does not seem to, or at any rate doesn't have the expected impact of releasing Julia's lock on the file.

Please note I am a long way from an expert on the OS-specific calls involved, so I'm not going to attempt to propose a patch myself, but hopefully the above helps someone pick this up in due course.

**Comment by vtjnash** [comment]
This is a design feature of Windows. You can't remove a file that is currently being used as a MMap target (unless you rename it first).

**Comment by Tobriand** [comment]
I guess the expectation would be that there a mechanism to release the mmap
via soldering like a close() call. As best as I can tell, at present, there
isn't....

**Comment by Tobriand** [comment]
For others struggling with this, on the assumption that this issue is not picked up downstream, there does exist a workaround: distributed processing.

In particular, if you jump through a rather sizable number of hoops, you can use the `@everywhere` macro, along with `addprocs` and `rmprocs` to coerce your mmapped context onto a separate process. Once you `rmprocs` the process(es) that you're doing mmapping on, you'll be able to modify the files themselves in the parent processes, because the file handle or mmap view that isn't released is coupled to the process in which it's running.

This might be a fair amount of overhead in some scenarios, but it's possible to plan around at least.

I.e. something to the effect of:


```
function f(file_path, jsonpath)
        procs = addprocs(1)
        @everywhere procs file_path=$file_path
        @everywhere procs json_path=$json_path
        @everywhere procs begin
            eval(:(import Pkg))
            Pkg.activate(".")
            eval(:(using test))
            test.do_mmap_related_work(file_path, json_path)
        end
        rmprocs(procs)
end
```
