### ISSUE TITLE
Alternative to copying part of a recent Xcode `libSystem.tbd` to `src/mach_dyld_atfork.tbd`

### ISSUE THREAD

**Issue by benz0li** [JuliaLang/julia#49976]
I find copying part of a recent Xcode `libSystem.tbd` file into the Julia source code rather odd.

It also prevents MacPorts from building current Julia versions (≥ 1.8.0) on 'OS X'/macOS 10.10 - 10.14 (Yosemite - Mojave).  

---

@quentinmit was able to get Julia to build on macOS 10.14 (Mojave)

> [...] with a simple Makefile patch; I replaced
> 
> ```
> OSLIBS += $(SRCDIR)/mach_dyld_atfork.tbd
> ```
> 
> with
> 
> ```
> CLANG_LDFLAGS += -Wl,-U,__dyld_atfork_prepare -Wl,-U,__dyld_atfork_parent
> ```
> 
> and added `$(CLANG_LDFLAGS)` to the rules building libjulia-internal and libjulia-internal-debug. The latter is probably safe on every platform but the former needs a guard for older OS versions, of course.
> 
> It's possible that the additional `-U` flags are unnecessary, but I didn't test that (the previous line sets a different flag that theoretically should allow unknown symbols as well).

– [#65550 (julia: link fails for 10.14 and earlier: ld: unsupported tapi file type '!tapi-tbd' in YAML file) – MacPorts](https://trac.macports.org/ticket/65550#comment:16)

---

Cross references:

* https://github.com/JuliaLang/julia/pull/43701
  * Fixed https://github.com/JuliaLang/julia/issues/43578
* https://github.com/JuliaLang/julia/pull/49740
  * Fixed https://github.com/JuliaLang/julia/issues/49733

**Comment by benz0li** [comment]
@quentinmit Could you please provide a full diff of your changes [that got Julia to build on macOS 10.14 (Mojave)] so @vtjnash may look into those?

I myself am not familiar enough with Xcode and Clang to help any further. Modifying Clang command line argument instead of file `src/mach_dyld_atfork.tbd` makes more sense to me, though.

**Comment by quentinmit** [comment]
Unfortunately, I can't for the life of me find the patched source tree I used to build my julia :(

It looks like MacPorts has more or less applied my diff here, though: https://github.com/macports/macports-ports/commit/56bf1a482dc03faffd6dc7e5b3bd3f9858851ce9#diff-ca423e7f15760e3e098d84955b5b68cc727d53538b6d50aa95d6a1fee7f49818

Basically, it's just telling the linker that it's okay if `__dyld_atfork_prepare` and `__dyld_atfork_parent` are undefined.

**Comment by vtjnash** [comment]
I reviewed it at https://github.com/JuliaLang/julia/pull/50017. Currently that is breaking for most platforms, but if you remove the unnecessary Makefile changes and just add the `-Wl,-U`, we can merge that.

**Comment by benz0li** [comment]
@vtjnash Thank you for looking into this and for your feedback.

Very much appreciated.
