### ISSUE TITLE
Encountered a build break while building gmp.mk in v1.9.0

### ISSUE THREAD

**Issue by hlsong89** [JuliaLang/julia#49977]
I'm Encountered a build break while building  in v1.9.0
env: ubuntu20.04, gcc-x86_64

The issue report at deps/gmp.mk around line 79:
```
$(eval $(call staged-install, \
    gmp,gmp-$(GMP_VER), \
    MAKE_INSTALL,,, \
    $$(WIN_MAKE_HARD_LINK) $(build_bindir)/libgmp-*.dll $(build_bindir)/libgmp.dll && \
         $$(INSTALL_NAME_CMD)libgmp.$$(SHLIB_EXT) $$(build_shlibdir)/libgmp.$$(SHLIB_EXT)))
```
I think the forth line must be placed in "ifeq ($(BUILD_OS),WINNT)" block
same issue encountered in deps/mpfr.mk line 56

**Comment by Seelengrab** [comment]
What error messge do you see? What's your `Make.user`?
