### ISSUE TITLE
signal (6): Abort trap: 6 using Julia with ResistanceGA on Mac

### ISSUE THREAD

**Issue by marafmuller** [JuliaLang/julia#49995]
I'm trying to create a resistance surface using Julia with the resistanceGA package in R, but the program always stops. I'm using macOS Ventura and Julia version 1.9.

I first run the GA.prep() and jl.prep() functions, and they both work fine (Circuitscape from Julia test passed). The issue comes when I try running the SS_optim() function and get the following info (never finishes running): 

[ Info: 2023-05-30 11:51:52 : Precision used: None

[4673] signal (6): Abort trap: 6
in expression starting at none:0
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

[4673] signal (11.1): Segmentation fault: 11
in expression starting at none:0
[ Info: 2023-05-30 11:51:54 : Precision used: None

[4679] signal (6): Abort trap: 6
in expression starting at none:0
[ Info: 2023-05-30 11:51:54 : Precision used: None

[4682] signal (6): Abort trap: 6
in expression starting at none:0
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

[4679] signal (11.1): Segmentation fault: 11
in expression starting at none:0
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

[4682] signal (11.1): Segmentation fault: 11
in expression starting at none:0
[ Info: 2023-05-30 11:51:54 : Precision used: None

[4676] signal (6): Abort trap: 6
in expression starting at none:0
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

[4676] signal (11.1): Segmentation fault: 11
in expression starting at none:0_

I have not been able to figure out what the issue is.

Any help or advice will be much appreciated.

**Comment by vtjnash** [comment]
It sounds like something in your program is calling `fork`, but that introduces a data race into all code and thus is not allowed in multithreaded code.

**Comment by marafmuller** [comment]
Hi Jameson,

Thank you very much for your response. Do you have any advice on how to fix
the issue?

Kind regards,

Mara Müller

**Comment by ViralBShah** [comment]
Best to not run multi-threaded Circuitscape when calling from ResistanceGA. I suggest filing in Circuitscape.jl.
