### ISSUE TITLE
Performance regression for recursive fib

### ISSUE THREAD

**Issue by gitboy16** [JuliaLang/julia#50068]
Hi,
I raised this on discourse but did not get a feedback. Thought I would raise it here. Maybe I am doing something wrong? (Fyi I am on windows)

Code:
```julia
fib(n::Int)::Int = begin
    if n == 0 || n == 1
        return n
    elseif n == 2 
        return 1
    else
        return fib(n - 1) + fib(n - 2)
    end
end
```

In Julia 1.9
`@btime fib(40) # 380.588ms`

In Master commit f407a4cac3
`@btime fib(40) # 1.034s`

Thank you

**Comment by oscardssmith** [comment]
I'm guessing llvm15, but a bisect will be needed here

**Comment by gitboy16** [comment]
I also constantly get the following:
In Julia 1.8.5
`@btime fib(40) # 370.934ms`
In Julia 1.7.3
`@btime fib(40) # 308.597ms`

**Comment by vchuravy** [comment]
Gabriel notes that this is OS (MacOS) specific regression

**Comment by gbaraldi** [comment]
At least I couldn't reproduce anything to the same level from 1.9 to master

**Comment by gbaraldi** [comment]
Interestingly I do see a regression from 1.7 to 1.8

**Comment by ararslan** [comment]
> Gabriel notes that this is OS (MacOS) specific regression

🤔 The OP says

> Fyi I am on windows

**Comment by vchuravy** [comment]
AH my eyes flew over that. Should have said non-Linux then xD

**Comment by gitboy16** [comment]
Thanks for fixing this. I was wondering if the Julia code can be further improved?
With Rust 1.67.1, I get a time of 186.68 ms.
Both Rust and Julia use LLVM, so I am wondering why we have such a difference?
```rust
fn fib(n: i64) -> i64 {
    if n == 0 || n == 1 {
        return n
    } else if n == 2 {
        return 1
    } else {
        return fib(n - 1) + fib(n - 2)
    }
}
```
Do you see such a difference as well?
