### ISSUE TITLE
Move Atomics manifesto to Julia docs

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#50088]
Currently https://docs.julialang.org/en/v1/manual/multi-threading/#man-atomics  reads:

> Specific details of the memory model and other details of the design are written in the [Julia Atomics Manifesto](https://gist.github.com/vtjnash/11b0031f2e2a66c9c24d33e810b34ec0), which will later be published formally.

It might be time to move that into the Julia docs since we had several versions of Julia with field-atomics supported?

**Comment by Seelengrab** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/46739ac
