### ISSUE TITLE
Add Troubleshooting section to manual

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#5010]
It would be great to gather common configuration or other issues that people run into when installing or running Julia.  Some thoughts which come to mind
- IPython issues
- Homebrew issues on OSX
- User environment variables (e.g., https://github.com/kmsquire/GZip.jl/issues/10)
- Julia Studio -> http://forio.com/julia/support

Others?

**Comment by ViralBShah** [comment]
I think these are all adequately covered in various places as well as on discourse.
