### ISSUE TITLE
Should `Base.notnothing` be exported?

### ISSUE THREAD

**Issue by Tokazama** [JuliaLang/julia#50143]
This is in the docs and all other methods around it seem to be exported as well. Any specific reason we haven't exported `notnothing`?

**Comment by Seelengrab** [comment]
We do have the shorthand of `!isnothing`, which seems a bit more idiomatic - predicates usually check something affirmative.

**Comment by Tokazama** [comment]
Actually, `notnothing` throws an error if something is `nothing` so it's not equivalent.

**Comment by jakobnissen** [comment]
I think most use cases of notnothing is better covered by something. something unwraps any Some arguments, which means that callers need not worry about whether the nullable value is encoded using Some, which is done haphazardly in Julia.

**Comment by Tokazama** [comment]
I find the entire "some.jl" code full of odd choices. It seems much more helpful to have `isnothing(x, field::Union{Int, Symbol})` than add an additional wrapper.

**Comment by Tokazama** [comment]
I'm going to close this for now since it's not actually causing any problems and I'm not sure their's any real benefit to exporting this at the moment.
