### ISSUE TITLE
Update processor_x86 with Zen4 and newer Intel

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#50178]
There are a bunch of new Intel chips and Zen4.

Zen4 was added in LLVM 16, but no reason to not detect it and fallback to Zen3 for the time being.

If anyone wants to try this. The relevant file is https://github.com/JuliaLang/julia/blob/0a05a5b05d382bdf38da7fdd0c069dff8bdc072c/src/processor_x86.cpp and I use https://github.com/llvm/llvm-project/blob/b163efae3312abe1227cff1d7704325138b4e538/llvm/lib/Target/X86/X86.td#L1749 as reference.

x-ref: https://github.com/JuliaCI/julia-buildkite/issues/298

**Comment by gbaraldi** [comment]
https://github.com/JuliaLang/julia/pull/44696 reference PR that added alder lake.

**Comment by varun-r-mallya** [comment]
Is this solved, can I work on it ?

**Comment by giordano** [comment]
Fixed by #52944.
