### ISSUE TITLE
Display of `Vector{SparseMatrixCSC}` prints data without abbreviating

### ISSUE THREAD

**Issue by adomasbaliuka** [JuliaLang/julia#50189]
The standard display (REPL output) of a single `SparseMatrixCSC` is nice. However, the display of `Vector{SparseMatrixCSC}` prints out their entire contents for each matrix without abbreviating anything. For large vectors and/or matrices, this behavior can be a problem, especially in combination with other packages, where the output cannot be simply aborted via interrupt (e.g. https://github.com/JuliaData/DataFrames.jl/issues/3343#event-9549576610).

### Example:
```julia
julia> using SparseArrays
julia> m = sprand(100000, 100000, 0.001)
#  ... nice output fitting in one screen ... # 
julia> [m, m]   # this prints out the full contents of each matrix (`colptr, nzval, rowval` arrays without omissions)
```

### Desired behavior
The output should omit most elements of a large vector, as well as most data of a large matrix. Also, it should probably print some information (maybe shape, maybe default single-sparse-matrix-display, etc.) for relevant matrices, rather than dump all the data.

### Versioninfo
```julia
julia> versioninfo()
Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
```

**Comment by ViralBShah** [comment]
Probably should be filed in SparseArrays.jl

**Comment by adomasbaliuka** [comment]
Related to https://github.com/JuliaSparse/SparseArrays.jl/issues/400 and https://github.com/JuliaSparse/SparseArrays.jl/issues/399. It seems the problem will be addressed in SparseArrays.jl.
