### ISSUE TITLE
LLVM OOMs on various PRs

### ISSUE THREAD

**Issue by d-netto** [JuliaLang/julia#50205]
Examples:

https://buildkite.com/julialang/julia-master/builds/24911#0188c9b6-072f-4715-bc2b-b0a313fca2c7
https://buildkite.com/julialang/julia-master/builds/24923#0188cb45-154b-4c11-973b-d75a99b9e7c1
https://buildkite.com/julialang/julia-master/builds/24839#0188bdab-e78b-4978-b6c5-691e8f60f79d

**Comment by maleadt** [comment]
Only i686 builds, right? x-ref https://github.com/JuliaLang/julia/issues/47938, debug builds have been failing for a while already.

**Comment by c42f** [comment]
In #46372 I saw this on the i686 windows build several times, though it seemed to be intermittent. I couldn't reproduce locally when running the i686 build under cygwin.

**Comment by d-netto** [comment]
Just saw it on win64: https://buildkite.com/julialang/julia-master/builds/24929#0188cef1-b49c-4ec2-be40-f58be2a6df1b

**Comment by maleadt** [comment]
> Just saw it on win64: https://buildkite.com/julialang/julia-master/builds/24929#0188cef1-b49c-4ec2-be40-f58be2a6df1b

That's during testing, though. I think the build issue is separate, because we may legitimately require 4GB of memory to build the sysimg.
