### ISSUE TITLE
More fine-grained coverage output control

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#50215]
The VS Code test framework is going to get coverage support at some point, and I'd love to use that in the [test item framework](https://discourse.julialang.org/t/prerelease-of-new-testing-framework-and-test-run-ui-in-vs-code/86355). For that to work, I would need a much more fine-grained control over coverage output in Julia base, though :)

In particular, Julia processes are re-used across multiple test runs in the test item framework, and I would need to get individual coverage results per test-run. So the model of having just one global coverage output per Julia instance doesn't really work.

I could think of various different ways to solve this.

One could be an API that deletes all accumulated coverage data in the current process and starts writing new coverage data into a new file (a bit like `Profile.clear()`):
```julia
restart_coverage_collection(new_output_filename)
```
Or maybe even more elegant would be a scoped coverage collection a la:
```julia
collect_coverage(output_filename) do
   # Code for which coverage should be collected goes here
end
```
Or maybe it would even be possible to _not_ write coverage data to disk at all but rather collect in-memory?
```julia
coverage_data = collect_coverage() do
     # Code for which coverage should be collected goes here
end
```
Not sure how big coverage data gets and whether that is a good idea or not.

I think for my purposes any of these would work well, so maybe the first one would be the simplest?

**Comment by MilesCranmer** [comment]
Reading through the code after your post on the discourse thread ([here](https://discourse.julialang.org/t/workflow-for-faster-testing-of-julia-packages/113836/6)).

It looks like the coverage data is stored in: https://github.com/JuliaLang/julia/blob/da6892ffc9fbb9a7ae272f570f3fd6002439de6c/src/coverage.cpp#L46

And this gets written to disk here: https://github.com/JuliaLang/julia/blob/da6892ffc9fbb9a7ae272f570f3fd6002439de6c/src/coverage.cpp#L205

which gets called only when Julia is exiting, here: https://github.com/JuliaLang/julia/blob/da6892ffc9fbb9a7ae272f570f3fd6002439de6c/src/init.c#L289

So the first order mechanism for live monitoring would be to have some hook so this coverage variable is accessible to the Julia runtime?

**Comment by davidanthoff** [comment]
Very cool!

Two other thoughts:
- it would be amazing if there was something like a flag that one could flip at runtime to pause and resume coverage collection.
- look at the code that @MilesCranmer identified, it also suggests that one could add an API to get access to the coverage information without going through a file on disc, which would also be nice for the VS Code use case.

**Comment by Seelengrab** [comment]
Related https://github.com/JuliaLang/julia/issues/50834

**Comment by davidanthoff** [comment]
For now it looks like https://github.com/JuliaLang/julia/pull/54358 solved this for the VS Code extension, thanks @MilesCranmer :)
