### ISSUE TITLE
Inline constant arrays

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#5024]
I just ran across a comment on Wes McKinney's [old blog post on Julia](http://wesmckinney.com/blog/?p=475#comment-519291477), where the following function was posted:

``` julia
julia> function f()
          ans = [1.0 2.0]
          for i=1:1000^2
             ans += [1.0 2.0]
          end
          return ans
       end
f (generic function with 1 method)

julia> f(); @time f();
elapsed time: 0.458983303 seconds (176000112 bytes allocated)
```

Ignoring the known issue that `+=` allocates memory, the constant expression also seems to be reallocated for each loop; moving this outside the loop cuts the time by 1/3:

``` julia
function f()
          p = [1.0 2.0]
          ans = [1.0 2.0]
          for i=1:1000^2
             ans += p
          end
          return ans
       end
f (generic function with 1 method)

julia> f(); @time f();
elapsed time: 0.292015111 seconds (128000176 bytes allocated)
```

I'll also note that removing `+=` but leaving assignment of `p` inside the loop still allocates `p` every iteration:

``` julia
julia> function f()
          ans = [1.0 2.0]
          for i=1:1000^2
             p = [1.0 2.0]
             for j = 1:length(ans)
                ans[j] += p[j]
             end
          end
          return ans
       end
f (generic function with 1 method)

julia> f(); @time f();
elapsed time: 0.15613266 seconds (64000112 bytes allocated)
```

Moving `p` outside drops the time to .005 sec, since almost no memory is allocated.

(Almost all of this is also obvious using the `code_*` functions.)

**Comment by oscardssmith** [comment]
I just ran timings on my machine (v 0.5.0) and it looks like this difference in timing is now gone. (although there still is lots of memory allocation, and tknpp's version is still 10x faster). Should this be closed?

**Comment by KristofferC** [comment]
I believe the current thinking is that cases like this are handled by https://github.com/JuliaArrays/StaticArrays.jl.
