### ISSUE TITLE
Tricking JuliaParser with the ============= operator

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#50268]
This is a really weird corner case I just invented to see how the new parser does on it. It does a nice job of identifying the problem, but then does it twice, and should probably complain about the whole operator. Just filing it in case we should do something better - but also ok not to do anything and close.

On master:
```
julia> a ============= 1
ERROR: ParseError:
# Error @ REPL[3]:1:6
a ============= 1
#    └─┘ ── not a unary operator
# Error @ REPL[3]:1:9
a ============= 1
#       └─┘ ── not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1
```

On 1.9:
```
julia> a ============= 1
ERROR: syntax: "===" is not a unary operator
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by KristofferC** [comment]
Almost dup of https://github.com/JuliaLang/julia/issues/50223

**Comment by ViralBShah** [comment]
Closing as dup of #50223
