### ISSUE TITLE
`collect(f, xs)`

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#50279]
`collect(Float64, xs)` works often but why not allow `collect(float, xs)`?

**Comment by Seelengrab** [comment]
Isn't that the same as `map(float, xs)`? In cases where `xs` is some lazy object, that ought to be preferred anyway.

**Comment by jariji** [comment]
I guess, but then what's the point of `collect(::Type, xs)`?

**Comment by giordano** [comment]
To be honest I didn't even know that method existed.

**Comment by Seelengrab** [comment]
As the docstring says, it guarantees to give an `Array{T}` for the requested `T` (though I must admit, that seems a bit superfluous). Expanding `collect` more doesn't sound too appealing to me though.

**Comment by fingolfin** [comment]
Also, isn't that what `Array{T}(iter)` resp. `Vector{T}` is already doing? E.g.
```
julia> collect(Float64, 1:2:5)
3-element Vector{Float64}:
 1.0
 3.0
 5.0

julia> Vector{Float64}(1:2:5)
3-element Vector{Float64}:
 1.0
 3.0
 5.0
```

**Comment by Seelengrab** [comment]
No - you can't do e.g. `Vector{sin}`, but you can `map(sin, xs)`.

**Comment by fingolfin** [comment]
There seems to be a misunderstanding here? My comment was that I also don't see why we have `collect(Float64, xs)` because it seems to do the same thing as `Vector{Float64}(xs)`. I.e. from my POV I'd rather deprecate `collect(T, xs)` than expand on it.

After all, as you yourself pointed out, the `collect(f, xs)` requested here seems to just do the same `map(f, xs)`. 

(I am not sure what you mean with `Vector{sin}`?)

**Comment by Seelengrab** [comment]
What I took the OP to mean was to have `collect(f, xs)` to map `f` over `xs` - that's not the same as what `Vector{T}` is doing, because that's not mapping the function, but calling `convert(T, x)`. I.e., `T` is expected to be a type, not a function like `sin`.

**Comment by fingolfin** [comment]
Once more: my comments were not about the original request. It was about this:
> what's the point of `collect(::Type, xs)`

**Comment by brenhinkeller** [comment]
To get back to the original question, because `Float64` is a type, while `float` is not. The method being called is:
```
help?> collect
search: collect ColumnSlices

  collect(element_type, collection)

  Return an Array with the given element type of all items in a collection or iterable.
  The result has the same shape and number of dimensions as collection.
```
