### ISSUE TITLE
Proposal: function to verify if a type is inside a Union

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#50283]
Hi!

I think Julia lacks a function to check if some type is inside a `Union`. For example, in DataFrames.jl, we want to check if a column has a specific type to fine-tune how it is printed to the console. However, sometimes we can have some complicated columns like `Union{Nothing, Missing, String, Base.UUID}`. Julia exports `nonmissingtype` to remove the `Missing`. However, there is no method AFAIK to check if, for example, the `Union` has `Base.UUID`.

So, I am proposing a method called `hastype(u::Union, d::DataType)` that returns `true` if `d` is inside the `u`.

If this proposal is accepted, I can submit a PR.

P.S.: I just saw that Julia also has `nonnothingtype` but it is not exported! I think it should!

**Comment by Seelengrab** [comment]
You can always do `d <: Union{...}`:

```
julia> Int <: Union{Int, String}
true
```

**Comment by ronisbr** [comment]
Yes, Thanks! It did not work in my first try because I was trying to check something like `Union{Union{String, Nothing}, Missing}`. However, it really seems a corner case.

**Comment by Seelengrab** [comment]
Even with that, nested unions collapse to only one layer of `Union`:

```
julia> Union{Union{String, Nothing}, Missing}
Union{Missing, Nothing, String}
```

**Comment by ronisbr** [comment]
Oh, so I might have caught a bug, let me see if I can make a MWE inside the function I am trying it.

**Comment by ronisbr** [comment]
The problem is that I want to check using an abstract type:

```julia
julia> Integer <: Union{Union{Int, String, Base.UUID}, Missing}
false
```

Anyway, it seems a corner case, I can circumvent this problem here. Thanks for the help @Seelengrab !

**Comment by vtjnash** [comment]
You just want typeintersect not <: (which is actually almost always the case for most uses of types)

**Comment by ronisbr** [comment]
Got it! Nice! Thanks @vtjnash. It is not that user friendly, but works perfectly:

```julia
julia> typeintersect(Integer, Union{Union{Int, String, Base.UUID}, Missing})
Int64

julia> typeintersect(Float64, Union{Union{Int, String, Base.UUID}, Missing})
Union{}
```
