### ISSUE TITLE
`shuffle` works differently on `Base.OneTo` than others

### ISSUE THREAD

**Issue by ctarn** [JuliaLang/julia#50304]
Hi, I am trying to shuffle many arrays in parallel, and I found the two ways to generate the shuffled indexes work differently.

```
julia> using Random

julia> eachindex(zeros(4)) == collect(eachindex(zeros(4)))
true

julia> shuffle(MersenneTwister(1), eachindex(zeros(4)))
4-element Vector{Int64}:
 1
 3
 4
 2

julia> shuffle(MersenneTwister(1), collect(eachindex(zeros(4))))
4-element Vector{Int64}:
 1
 2
 4
 3

julia> shuffle(MersenneTwister(1), 1:4)
4-element Vector{Int64}:
 1
 2
 4
 3

julia> shuffle(MersenneTwister(1), [1, 2, 3, 4])
4-element Vector{Int64}:
 1
 2
 4
 3
```

Is it a bug?

I am using:
```
julia> versioninfo()
Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by rfourquet** [comment]
I wouldn't qualify this as a bug, calling `rand`-related functions on objects of different types is not documented to be "consistent". In this case, I would guess there was a tiny optimization to be had by specializing `shuffle` on `Base.OneTo`.

**Comment by LilithHafner** [comment]
This is somewhat related to the warning near the top of the [Random page of the manual](https://docs.julialang.org/en/v1/stdlib/Random/):

> Because the precise way in which random numbers are generated is considered an implementation detail, bug fixes and speed improvements may change the stream of numbers that are generated after a version change. Relying on a specific seed or generated stream of numbers during unit testing is thus discouraged - consider testing properties of the methods in question instead.
