### ISSUE TITLE
Population count for UInt8

### ISSUE THREAD

**Issue by alexfreudenberg** [JuliaLang/julia#50322]
I think in most use cases it is detrimental that the `count_ones(::UInt8)` and  `count_ones(::Int8)` methods return an `Int` instead of an `UInt8`. This inflates memory requirements unnecessarily and I assume users of this function generally would prioritize performance over usability.

Below is a simple implementation using StaticArrays.jl that requires less memory. On my system, it is also more efficient; however, I assume this depends on how LLVM lowers the `ctpop` instruction? I didn't get any smarter by reading [the docs](https://releases.llvm.org/1.5/docs/LangRef.html#int_ctpop).

```julia
using Test, Base, BenchmarkTools, StaticArrays;

n = typemax(UInt8);
pop_counts = UInt8.(count_ones.(range(0,n)));
const POPCOUNT_TABLE = SVector{n+1}(pop_counts);

@inline @inbounds count_ones_new(entry::UInt8)::UInt8 = return POPCOUNT_TABLE[entry + 1];

M = rand(UInt8, (1_000_000, 1_000));
``` 
Performance:
```julia
julia> @btime count_ones_new.($M);
  319.723 ms (2 allocations: 953.67 MiB)

julia> @btime Base.count_ones.($M);
  729.437 ms (2 allocations: 7.45 GiB)

julia> @test all(Int.(count_ones_new.(M)) .== count_ones.(M))
Test Passed
```

If there is a solution that does not need StaticArrays.jl, I think this would be a valuable addition to Base.

**Comment by KristofferC** [comment]
```julia
julia> count_ones_uint8(x::UInt8) = count_ones(x) % UInt8

julia> @btime count_ones_new.($M);
  426.209 ms (2 allocations: 953.67 MiB)

julia> @btime Base.count_ones.($M);
  1.670 s (2 allocations: 7.45 GiB)

julia> @btime count_ones_uint8.($M);
  242.314 ms (2 allocations: 953.67 MiB)
```

But really, how often do you store a huge array of counts like this?

**Comment by jakobnissen** [comment]
It doesn't use extra memory to convert to `Int`. This happens inside a register, so all it takes is one extra `movl` instruction. If you convert back to `UInt8`, then there is zero cost and it is equivalent to using the LLVM instrinsic.
There are more advantages to using an intrinsic. For example, on my computer, it autovectorizes to use `vpopcntb` instructions. It also doesn't need to load from memory.

You could implement your lookup table with a Tuple, but the raw CPU instruction is still superior.

**Comment by alexfreudenberg** [comment]
> ```julia
> julia> count_ones_uint8(x::UInt8) = count_ones(x) % UInt8
> ```
Thanks!!

> But really, how often do you store a huge array of counts like this?
Well, in my application it is 800,000 x 50,000, for which `Int` is quite costly... I don't see in which case it would be worse to have `UInt8` as the default return type.

**Comment by jakobnissen** [comment]
Julia almost always returns `Int` where possible, instead of other integer types.

**Comment by KristofferC** [comment]
> Well, in my application it is 800,000 x 50,000, for which Int is quite costly... 

Feels like recomputing it when needed is maybe cheaper than storing and retrieving it.

**Comment by alexfreudenberg** [comment]
> For example, on my computer, it autovectorizes to use `vpopcntb` instructions. It also doesn't need to load from memory.

Wouldn't this require AVX512 instructions? 

> Julia almost always returns `Int` where possible, instead of other integer types.

Do you know the reasons for that? I assume people dealing with non-standard integer formats would almost always prefer performance over convenience

**Comment by giordano** [comment]
For what is worth, in https://github.com/haampie/FastPrimeSieve.jl/pull/5 I found more practical packing UInt8s into UInt64s because counting ones in UInt8s is fairly useless as it overflows very quickly. Performance was comparable, while packing into UInt64s would give more meaningful results.
