### ISSUE TITLE
Indexing with `n:1` in a for-loop

### ISSUE THREAD

**Issue by rmorsomme** [JuliaLang/julia#50336]
It'd be useful to have `n:1` as a legal index set for for-loops, instead of having to use `n:-1:1`.

This for-loop works
```
for i in 5:-1:1
    println(i)
end
```
but the following unfortunately does not work (with no warning provided)
```
for i in 5:1
    println(i)
end
```

Version info:

Julia Version 1.9.1
Commit 147bdf428c (2023-06-07 08:27 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
versioninfo() = nothing

**Comment by vchuravy** [comment]
This would be breaking behavior. I have seen `1:0` in places where the user needed an empty range.
