### ISSUE TITLE
The scale-change of "cgrad" is invalidated when colorschemes are jointed

### ISSUE THREAD

**Issue by Fluorite-Erbite** [JuliaLang/julia#50344]
Julia 1.9.0 downloaded from the official

(Sorry for my poor English)

I want to join 2 colorschemes, before which each scale is change (:log).
Example, 

```
cs1 = reverse( cgrad( palette( [:red, :orange, :yellow, :lawngreen], 100 ), scale=:log ) )
cs2 = cgrad( palette( [:navyblue, :deepskybkue2, :lime, :lawngreen], 100 ), scale=:log )

cs_com = zeros(RGBA{Float64}, 200)
cs_com[1:100] .= cs1
cs_com[101:end] .= cs2
```

But, outputted colorscheme is invalidated scale-change (`scale=:log`), it means that, `cs_com` is JUST equal to
`palette( [:navyblue, :deepskybkue2, :lime, :lawngreen, :lawngreen, :yellow, :orange, :red], 200 )`

Why? and, please let me know how to combine colorschemes.

**Comment by fredrikekre** [comment]
This seems like a question for the forum: https://discourse.julialang.org/.

**Comment by Fluorite-Erbite** [comment]
@fredrikekre 
Oh, really? I didn't find it but thank you. I search again.

**Comment by oscardssmith** [comment]
fredrik wasn't saying that this question has already been asked on discourse, he means that github is for bugs, not usage questions and usage questions should be asked on discourse (or stackoverflow or slack)

**Comment by Fluorite-Erbite** [comment]
@oscardssmith 
Ah, I see. I forgot that Github is not a so-called community for consultation.
Thank you.
