### ISSUE TITLE
no lts  in /base/version.jl

### ISSUE THREAD

**Issue by themantra108** [JuliaLang/julia#50346]
how to know Long term support version
it provides major , minor , prerelease, but no LTS version info

**Comment by themantra108** [comment]
how to know Long term support version
it provides major , minor , prerelease, but no LTS version info

**Comment by jakobnissen** [comment]
The `VersionNumber` provided in `base/version.jl` implements [semantic versions](https://semver.org/). Long term support (LTS) is not a semantic version, it is a versioning policy that Julia and other projects. This policy is not (and cannot be) encoded in the version number itself.
