### ISSUE TITLE
Memory leak in Base - combining Tasks with eval

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#50363]
Hi there

First time I am trying to use Julia for infinite jobs (streaming). It is horrible I have to admit unfortunately. Lost 1 full week to track down memory leaks. Here another one:

```julia
for _ in 1:50
    @eval fetch(schedule(Task(() -> ())))
    GC.gc(true); GC.gc(false)
    Core.println(Base.gc_live_bytes() / 2^20)
end
```

running this will output something like
```
1.36197
1.36372
1.36546
1.36721
1.36896
1.3707
1.37245
1.3742
1.37595
1.37769
1.37944
1.38119
1.38293
1.38468
1.38643
1.38818
1.38992
1.39167
```

**Comment by KristofferC** [comment]
Aren't you generating infinite amount of code here with generating new closures?

For example, something like

```

const clos = () -> ()
for _ in 1:50
    @eval fetch(schedule(Task(clos)))
    GC.gc(true); GC.gc(false)
    Core.println(Base.gc_live_bytes() / 2^20)
end
```

seems to be stable. 

Probably, dup of https://github.com/JuliaLang/julia/issues/14495

**Comment by schlichtanders** [comment]
indeed, I may create new closures repeatedly (this is running as part of Pluto.jl).

if a closure is not cleaned up automatically when nothing references it, how can it be deleted manually?

**Comment by schlichtanders** [comment]
I tried naming the inner function but this also does not work
```
for _ in 1:50
    @eval function myfunc() end
    GC.gc(true); GC.gc(false)
    Core.println(Base.gc_live_bytes() / 2^20)
end
```

**Comment by schlichtanders** [comment]
Realized this is a complete duplicate :smile: 

The original issue already creates a named function and still experiences these problems.
The Task wrapper is not really needed, but yeah, it is a common context where this occurs.

I guess the greatest value I can add is to mention that this memory bug also happens when using Pluto.
