### ISSUE TITLE
Error message provides wrong code locationn

### ISSUE THREAD

**Issue by orenbenkiki** [JuliaLang/julia#50378]
Compiling

```
struct Foo
    bar::Int
    baz::Vector{String, String}
end
```

Gives the error message:

```
ERROR: LoadError: too many parameters for type
Stacktrace:
 [1] top-level scope
   @ .../bug.jl:1
in expression starting at .../bug.jl:1
```

This should mention line 3 somewhere in the error message.

It is easy enough to see for a small `struct` like here, but for a large structure, it is far from obvious which line it is actually complaining about.

**Comment by nsajko** [comment]
Dup: #38531
