### ISSUE TITLE
Docstring and function signature of `Base.BinaryPlatforms.triplet` differ

### ISSUE THREAD

**Issue by marcom** [JuliaLang/julia#50389]
```
Julia Version 1.10.0-DEV.1619
Commit 27e21c8865 (2023-07-01 12:01 UTC)
```

The docstring of `triplet` mentions the kwarg `exclude_tags`, whereas this kwarg does not exist in the actual code.

**Comment by Jay-sanjay** [comment]
sir can you please elaborate a bit I will be happy to contribute
it would be my pleasure if you provide links as well
