### ISSUE TITLE
CTRL + W keyboard shortcut very eager

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaLang/julia#50409]
The `CTRL + W` shortcut in the REPL is very eager when removing text. For example, in both following cases, CTRL + W will clean the full line whereas it might make more sense to separate special characters since they split words:
```julia
julia> sum_one(1
```

```julia
julia> data.field
```

**Comment by rfourquet** [comment]
This was implemented in #6368, `Ctrl-w` defines word boundaries as spaces on purpose, and `meta-backspace` is an alternative which defines word boundaries as usual like most other REPL functions. So there doesn't seem to be anything to do here, in particular as it's possible to remap keyboard shortcuts. I will close, but feel free to re-open if you still want to suggest changing the current behavior.
