### ISSUE TITLE
allocation with v.*=x on SparseArrays

### ISSUE THREAD

**Issue by dpinol** [JuliaLang/julia#50439]
The following code allocates 128 bytes in julia 1.9 & 1.10. However, when using dense vectors, it doesn't allocate
```julia
using SparseArrays

const v=spzeros(10)
v[1]=4
f(v) = v.*=4
@allocated f(v)
```

Currently the workaround is using `map!(f, v,v)`

**Comment by dkarrasch** [comment]
Seems like it has always been allocating? On v1.6 it's 192 bytes. You may wish to actually post the issue over at SparseArrays.jl.

**Comment by dpinol** [comment]
@dkarrasch thanks, moved to SparseArrays.jl. https://github.com/JuliaSparse/SparseArrays.jl/issues/404
