### ISSUE TITLE
Assertion `!ctx.ssavalue_assigned.at(ssaidx_0based)' failed.` when testing some packages

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#50449]
When testing the packages

 "LsqFit"
 "Polyhedra"
 "PowerModelsRestoration"
 "SinusoidalRegressions"
 "EasyFit

with an assert build they error with:

```
julia: /source/src/codegen.cpp:5042: void emit_ssaval_assign(jl_codectx_t&, ssize_t, jl_value_t*): Assertion `!ctx.ssavalue_assigned.at(ssaidx_0based)' failed.
```

Example PkgEval log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c9a32f4_vs_e4ee485/LsqFit.primary.log

**Comment by maleadt** [comment]
That's the same as https://github.com/JuliaLang/julia/issues/50379.
