### ISSUE TITLE
Assertion `newobj == (jl_method_instance_t*)obj` is hit when testing ITensorsVisualization

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#50454]
When testing ITensorsVisualization an assertion that looks like

```
WARNING: Method definition sort(Tuple) in module Sort at sort.jl:1418 overwritten in module NDTensors at /home/pkgeval/.julia/packages/NDTensors/b7X2X/src/tupletools.jl:154.
  ** incremental compilation may be fatally broken for this module **

julia: /source/src/staticdata.c:3224: jl_restore_system_image_from_stream_: Assertion `newobj == (jl_method_instance_t*)obj' failed.

[158] signal (6.-6): Aborted
in expression starting at /home/pkgeval/.julia/packages/ITensorsVisualization/RtaL7/src/ITensorsVisualization.jl:4
```

is hit.

PkgEval log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c9a32f4_vs_e4ee485/ITensorsVisualization.primary.log

cc @timholy, @vchuravy since this looks to be in the package image loading code.

**Comment by vchuravy** [comment]
This is @vtjnash, but note that this is consistent with the warning. Without assertion we "carry on", but the warning on creation is fatal.

**Comment by vchuravy** [comment]
This particular error is a grayzone. IIRC Jameson made the error fatal once and folks revolted. So we made it print a scary message, but carry one as if nothing happened.

In assertion mode we are stricter (and arguably should have asserted on the error).

So I don't know what the "right" answer is here...

**Comment by KristofferC** [comment]
An assertion should imo only trigger from straight-up bugs or invariant breaks in the surrounding code. So either this needs to be made into a hard error or the assertion removed. Otherwise, you get e.g. completely different PkgEval results depending on if assertions are enabled etc.

**Comment by vchuravy** [comment]
Yeah this particular assertion is a hard check that makes sure an invariance is met.

But the question is can we reach this assertion from code that doesn't hit:

```
WARNING: Method definition sort(Tuple) in module Sort at sort.jl:1418 overwritten in module NDTensors at /home/pkgeval/.julia/packages/NDTensors/b7X2X/src/tupletools.jl:154.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by gbaraldi** [comment]
Is this "fixed" since we made the method overwriting an error?

**Comment by KristofferC** [comment]
I guess so :p.
