### ISSUE TITLE
Many packages asserts with: `Assertion oldentry->max_world == ~(size_t)0 && "method cannot be added at the same time as method deleted"' failed.`

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#50451]
Many packages now assert with something similar to:

```
WARNING: Method definition constructorof(Type{var"#s1"} where var"#s1"<:(IntervalSets.Interval{L, R, T} where T)) where {L, R} in module ConstructionBaseIntervalSetsExt at /home/pkgeval/.julia/packages/ConstructionBase/pAlst/ext/ConstructionBaseIntervalSetsExt.jl:6 overwritten in module ConstructionBaseExtras at /home/pkgeval/.julia/packages/ConstructionBaseExtras/cy4E1/src/intervalsets.jl:3.
julia: /source/src/gf.c:1486: get_intersect_visitor: Assertion `oldentry->max_world == ~(size_t)0 && "method cannot be added at the same time as method deleted"' failed.
```

Example PkgEval log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/c9a32f4_vs_e4ee485/ConstructionBaseExtras.primary.log

I think this happens when a method is overwritten but I didn't check all cases.

**Comment by maleadt** [comment]
MWE, requiring actual packages and extensions, and running with assertions enabled:

`ConstructionBase.jl`, defining the `constructorof` method
```julia
module ConstructionBase
constructorof() = nothing
end
```

`StaticArrays.jl`, an empty package to trigger a package extension
```julia
module StaticArrays
end
```

`ConstructionBaseStaticArraysExt.jl`, the extension that defines `constructorof(::Type{<:Integer})`:
```julia
module ConstructionBaseStaticArraysExt
using ConstructionBase
ConstructionBase.constructorof(::Type) = nothing
ConstructionBase.constructorof(::Type{<:Integer}) = nothing
end
```

Finally, `main.jl`, also defining `constructorof(::Type{<:Integer})` and crashing when loading StaticArrays -> ConstructionBaseStaticArraysExt
```julia
using ConstructionBase
ConstructionBase.constructorof(::Type{<:Integer}) = nothing
using StaticArrays
```

**Comment by maleadt** [comment]
Not fixed; the assertion has now just changed to:

```
Failed to precompile EasyJobsBase [db8ca866-b61f-4bd1-a9b9-75c107d645d4] to "/home/pkgeval/.julia/compiled/v1.11/EasyJobsBase/jl_mX2s9D".
julia: /source/src/gf.c:1486: get_intersect_visitor: Assertion `oldentry->max_world != closure->newentry->min_world && "method cannot be added at the same time as method deleted"' failed.
```

e.g. https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-07/14/SimpleWorkflows.primary.log

**Comment by vtjnash** [comment]
The Pkg.precompile code now intentionally suppresses a lot of essential information, which seems to be a severe regression to me, but the PR to fix it is sitting idle (https://github.com/JuliaLang/Pkg.jl/pull/3536). Running this manually results in:
```
  1 dependency had warnings during precompilation:
┌ Thinkers [6d80a3f9-a943-41fa-97b3-3004c0daf7a3]
│  WARNING: Method definition (::Type{Thinkers.TimeLimitedThunk})(Any, Any) in module Thinkers at /home/vtjnash/.julia/packages/Thinkers/AFzBt/src/TimeLimitedThunk.jl:9 overwritten at /home/vtjnash/.julia/packages/Thinkers/AFzBt/src/TimeLimitedThunk.jl:15.
│    ** incremental compilation may be fatally broken for this module **
└  
```
And this is exactly (half of) the reason it prints this error. I can push a fix to make that error more clear though.
