### ISSUE TITLE
get! on EnvDict does not convert Int to String anymore on 1.10.0-alpha1

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#50472]
On Julia 1.9.2 both of these work
```
get!(ENV, "foo", 0)
ENV["bar"] = 1
```
but on Julia 1.10.0-alpha1 I get
```
julia> get!(ENV, "foo", 0)
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type String

Closest candidates are:
  convert(::Type{String}, ::Base.JuliaSyntax.Kind)
   @ Base C:\workdir\base\JuliaSyntax\src\kinds.jl:974
  convert(::Type{String}, ::String)
   @ Base essentials.jl:321
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84
  ...

Stacktrace:
 [1] get!(default::Base.var"#233#234"{Int64}, t::Base.EnvDict, key::String)
   @ Base .\abstractdict.jl:558
 [2] get!(t::Base.EnvDict, key::String, default::Int64)
   @ Base .\abstractdict.jl:552
 [3] top-level scope
   @ REPL[1]:1
```

Background: on https://pkgdocs.julialang.org/v1/environments/#Automatic-Precompilation documentation suggests that one can set environment variable to an integer `ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0`.

**Comment by DilumAluthge** [comment]
> Background: on https://pkgdocs.julialang.org/v1/environments/#Automatic-Precompilation documentation suggests that one can set environment variable to an integer `ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0`.

Probably the easiest approach is for us to fix the docs to instead say `ENV["JULIA_PKG_PRECOMPILE_AUTO"]="0"`.

**Comment by Krastanov** [comment]
Isn't this a breaking change in public API?

**Comment by maleadt** [comment]
#48128
