### ISSUE TITLE
Rename the ENV variable `JULIA_USE_NEW_PARSER` to something more verbose and less time-sensitive

### ISSUE THREAD

**Issue by navidcy** [JuliaLang/julia#50470]
I find the `JULIA_USE_NEW_PARSER` environment variable name ambiguous.

https://github.com/JuliaLang/julia/blob/d60f9b3b47ee585cc1d8a836bb0d7acab81a9b6e/base/Base.jl#L607

What is new now it won't be new in a few months... So the variable name is doomed to become obsolete.

Why not something like `JULIA_USE_PRE_v1p10_PARSER` or something along those lines: more verbose, and less time-sensitive.

**Comment by PallHaraldsson** [comment]
I think this is overkill. I believe the new parser is off by default, and in the future there will be just this parser, and no other. NEWS.md is actually currently wrong, it states it's on by default, which is our hope for when 1.10 will eventually get released. When it will get enabled by default, we don't really want to go back. Maybe the ENV will actually just be dropped by then.

**Comment by maleadt** [comment]
Maybe `JULIA_USE_JULIASYNTAX` (cfr. `USE_BINARYBUILDER`)?

> I believe the new parser is off by default

It is used by default.

**Comment by navidcy** [comment]
That's better. Anything that is not time-sensitive is better. That's my 2 cents. :)

**Comment by KristofferC** [comment]
Or maybe delete it completely?

**Comment by PallHaraldsson** [comment]
>Maybe JULIA_USE_JULIASYNTAX

That's actually worse, since the syntax is supposedly the same, just a new parser, and not all familiar with JuliaSyntax.jl, which is just an implementation detail. Since it is actually on by default (I thought it was meant to be off), then JULIA_USE_OLD_PARSER could also work.

**Comment by navidcy** [comment]
But that has the same problem as above. In 3 years what will "old" mean?

**Comment by LilithHafner** [comment]
+1 for deleting it entirely. If we never touch the flisp parser again then as the language syntax evolves it will soon be obsolete. During 1.10 we can (and IMO should) keep the flag (possibly with a rename), but by 1.11, I doubt it will be viable to opt out of JuliaSyntax.

**Comment by DilumAluthge** [comment]
Won't we always need to keep the flisp parser around for bootstrapping JuliaSyntax?

**Comment by LilithHafner** [comment]
@c42f suggested on slack that we might be able to remove it using separate compilation

**Comment by c42f** [comment]
We will definitely remove the old parser at some point (maybe 1-3 1.x releases? Depends on who decides to do that work, and the readiness of runtime facilities like separate compilation which would make this a lot easier.)

At that point the `JULIA_USE_NEW_PARSER` environment variable will become obsolete and will be deleted.  So I really don't think it's worth worrying about how this environment variable is named. So much so, that I'm ok with pretty much anything vaguely sensible. `JULIA_USE_FLISP_PARSER` seems fine.

*However* I do think we should keep some mechanism to opt into the old parser for at least one release. This is to accommodate compatibility. JuliaSyntax.jl is highly compatible, but it's only been tested against `General` which is far from all the Julia code which exists. If you've ever run a production system, you'll know how valuable it is to be able to flip the switch back to the old behavior, and it costs us very little to allow this for the short term.
