### ISSUE TITLE
Random.randcycle(1) should throw?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#50479]
Currently, we define:
```jl
julia> Random.randcycle(1)
1-element Vector{Int64}:
 1
```
which seems wrong to me — as I understand it, the [identity permutation is not cyclic](https://math.stackexchange.com/questions/1151548/is-identity-permutation-cyclic).  Indeed, for `n > 1` we never generate the identity permuation:
```jl
julia> [Random.randcycle(2) for i = 1:10]
10-element Vector{Vector{Int64}}:
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
 [2, 1]
```
Note that this behavior was introduced in a *very* early version of Julia, way back in 2010 when files still ended in `.j`, by @ViralBShah (https://github.com/JuliaLang/julia/commit/18b72d1c565dca19696ef5ad0d07060cf7b7620a), and appears to have been copied down through the versions ever since.

**Comment by ctarn** [comment]
similar case:
```julia
julia> Random.randcycle(0)
Int64[]
```

`randperm(0)` doesn't throw either.

**Comment by LilithHafner** [comment]
I think Julia is right and Wikipedia is wrong here. I've [updated](https://en.wikipedia.org/w/index.php?title=Cyclic_permutation&diff=1164510878&oldid=1149158632) Wikapeda's definition.

Feel free to continue this conversation here or on Wikipedia if you disagree.

**Comment by LilithHafner** [comment]
Oops, I missed the second half of your report, "Indeed, for n > 1 we never generate the identity permuation", which is a bug.

**Comment by LilithHafner** [comment]
This function returns a cycle of the requested length, for length = 1, this is the identity, for length > 1, this is not the identity. Julia's current implementation gets it right.

**Comment by stevengj** [comment]
If the definition of a cyclic permutation is "at most one nontrivial cycle", then why isn't the identity permutation (which has no nontrivial cycles) allowed for all `n`?  In this case, our `randcycle` is wrong for `n > 1` because it never returns the identity.

Furthermore, the [analysis by Wilson](https://algo.inria.fr/seminars/summary/Wilson2004b.pdf) of the correctness of [Sattolo's algorithm](https://sci-hub.se/https://doi.org/10.1016/0020-0190(86)90073-6) (which is essentially our algorithm, it looks like),  seems to implicitly assume that `n > 1`.  In particular, see the line: "As σ is cyclic, q(σ) = σ(n) ∈ {1,…,n−1}".  This is not true if `n=1` allows the identity permutation.

**Comment by stevengj** [comment]
I found [another paper on Sattolo's algorithm](https://sci-hub.se/https://doi.org/10.1007/BF01941134) that defines cyclic permutations in a different way, which allows the identity permutation *only* for n=1:

<img width="955" alt="image" src="https://github.com/JuliaLang/julia/assets/2913679/0ed6cc39-1ffb-4c58-8ab6-c77918d35b32">

It cites C. Berge, Principles of Combinatorics, Academic Press, New York and London, 197t.  

In contrast, it seems like the definition you wrote into Wikipedia is inconsistent (your proposed definition appears to allow identity permutations for all `n`).

**Comment by stevengj** [comment]
Berge's book (p. 120), however, seems to define a circular permutation as having "just one" (= exactly one?) cycle of length > 1:

<img width="325" alt="image" src="https://github.com/JuliaLang/julia/assets/2913679/7e4ce6a5-415a-43ea-a554-67a4ee94a4b7">

which doesn't seem to allow the n=1 case.  However, this language seems a bit informal.

**Comment by stevengj** [comment]
As far as I can tell, we are using the more restrictive definition mentioned on Wikipedia: "Some authors restrict the definition to only those permutations which consist of one nontrivial cycle" — i.e. we don't allow *any* fixed points.  We wouldn't allow the permutation of `1:6` listed as an example by Berge, above.

 However, the Wikipedia text would still disallow the identity for length 1.   On the other hand, [Knuth fascicle 2b](https://www-cs-faculty.stanford.edu/~knuth/fasc2b.ps.gz) *would* allow the identity permutation, but only for length 1:

<img width="641" alt="image" src="https://github.com/JuliaLang/julia/assets/2913679/6d6140d6-12fc-4b3a-a873-7690295e072e">

It seems like this is the definition we are using: all of the elements are in a cycle of length n?

**Comment by ctarn** [comment]
> We never generate permutation of 1:6 listed as an example by Berge, above, as far as I can tell.

Any permutation is cyclic if we include such permutation? The statement is limited to "on the elements 1, 2, 3" I think.

Actually, in the [another paper on Sattolo's algorithm](https://doi.org/10.1007/BF01941134) you mentioned, I find the following definition, which sounds better to me:

> A permutation Π of a set S is a one-to-one function Π: S → S. The values of S can be partitioned into cycles: for each value j ∈ S, the values {j, Π.j, Π2.j, Π3.j...} form a cycle. (We use the period "." for function application.) **A permutation is cyclic if it consists of a single cycle.**

Based on the definition, any identity permutation of length `n` consists of `n` cycle(s), and thus only the identity permutation of length `1` is cyclic. An empty permutation (of length `0`) can also be defined as cyclic.

**Comment by martinholters** [comment]
Before looking at the wikipedia article, I understood a "cyclic permutation" to be a permutation with exactly one cycle. (For n=1 this is the identity permutation with one trivial cycle.) After looking at the wikipedia article, I'm confused. So let's just document "cyclic permutation" = "permutation consisting of a single cycle" to keep others from looking at the wikipedia article trying to figure out what a cyclic permutation is :smile:

**Comment by stevengj** [comment]
Yes, that's what #50487 does.

**Comment by adienes** [comment]
what's the difference between this function and `shuffle(1:n)` ?

**Comment by stevengj** [comment]
`shuffle(1:n)` is equivalent to `randperm(n)` — it produces an arbitrary permutation, not necessarily cyclic.

**Comment by adienes** [comment]
well, yeah, but isn't `randcycle` pretty straightforward to implement using `randperm` ? might be easier to maintain that way than having a completely separate sampling process

```
function randcycle2(n)
    r = randperm(n)
    z = zeros(Int, n)
    for i ∈ r
        z[r[i]] = r[i % n + 1]
    end
    return z
end
```

**Comment by stevengj** [comment]
> well, yeah, but isn't randcycle pretty straightforward to implement using randperm ?

I don't think this issue is a good place to debate this, but I would point out that your `randcycle2` isn't that much shorter than `randcycle!` and is much less efficient (allocating two arrays rather than one).
