### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#505]
Debugging code is currently print() based. This isn't a particularly great solution.

Spun this issue off of #502 so maybe we can put that one back on topic. (My fault for bringing it up)

**Comment by malmaud** [comment]
And again at this year's JuliaCon.

**Comment by ViralBShah** [comment]
@keno Did you mean to close this?

**Comment by Keno** [comment]
Once the METADATA PR is merged.

**Comment by ViralBShah** [comment]
The PR is green. Anything holding it?

**Comment by dhoegh** [comment]
How far is Windows support?

**Comment by timholy** [comment]
Whoa.

**Comment by StefanKarpinski** [comment]
![giphy](https://cloud.githubusercontent.com/assets/153596/14233631/19696da6-f99c-11e5-82fd-fdb2d27277e4.gif)

Bravo, @Keno.

**Comment by ViralBShah** [comment]
I believe Windows support is coming soon, but needs some non-trivial work.
