### ISSUE TITLE
Cannot build julia using exFAT drive on Windows 10

### ISSUE THREAD

**Issue by Zentrik** [JuliaLang/julia#50515]
exFAT drives on Windows 10 don't seem to support symlinks and building julia uses symlinks in two places
https://github.com/JuliaLang/julia/blob/4995d3f5c0b234561d3b5b516adb5cb6ab1e5bd7/deps/JuliaSyntax.mk#L7 https://github.com/JuliaLang/julia/blob/4995d3f5c0b234561d3b5b516adb5cb6ab1e5bd7/deps/tools/stdlib-external.mk#L19

I think to fix this the following needs to copy if building on Windows and on an exFAT  drive
https://github.com/JuliaLang/julia/blob/4995d3f5c0b234561d3b5b516adb5cb6ab1e5bd7/deps/tools/common.mk#L222-L225

**Comment by PallHaraldsson** [comment]
Is it important to build Julia on exFAT? I'm just curious, yes, I think we should and do support exFAT, as much as possible, for normal use of Julia (and all common filesystems Windows and other platforms use), up to exFAT's inherent limitations.

exFAT does likely not support symlinks on any Windows version (nor Linux?), and probably never will. So I think we can't wait for it to be fixed, and Julia building automatically working, but neither do I see it terribly important to work around that.

**Comment by vtjnash** [comment]
Sorry Zentrik. We only support building on filesystems which meet the posix requirements (regardless of whether the host OS is windows or not, this would be a problem with exFAT)
