### ISSUE TITLE
read(io, Char) doesn't match collect(string) for malformed UTF-8

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#50532]
The following mismatch seems undesirable to me: the same data `"\xfc\xa8"` is treated as 2 (malformed) characters for `collect` but as only 1 character for `read`:
```jl
julia> s = "\xfc\xa8"
"\xfc\xa8"

julia> io = IOBuffer(s);

julia> read(io, Char)
'\xfc\xa8': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> collect(s)
2-element Vector{Char}:
 '\xfc': Malformed UTF-8 (category Ma: Malformed, bad data)
 '\xa8': Malformed UTF-8 (category Ma: Malformed, bad data)
```
cc @StefanKarpinski, the guru of malformed `Char`, who wrote this `read` code and the string iteration in #24999 — is this intentional?

**Comment by StefanKarpinski** [comment]
This definitely seems wrong—we should be consistent about what we consider to be a character, even for invalid data. I can dig into why there's a discrepancy...

**Comment by StefanKarpinski** [comment]
Yeah, ok, `read(io, Char)` is just buggy when there's a lead byte with too many leading ones, so I'll fix that.
