### ISSUE TITLE
Adding a mutable to a `Base.Set` does not use `isequal` for comparison

### ISSUE THREAD

**Issue by Clemapfel** [JuliaLang/julia#50543]
According to the [`Base.Set` documentation](https://docs.julialang.org/en/v1/base/collections/#Base.Set), `isequal` is used to determine whether two objects in a set are the same object. This is not true for mutable types:

MWE:

```julia
julia> mutable struct Test 
           value
       end

julia> Base.isequal(a::Test, b::Test) = a.value == b.value
julia> set = Set{Test}()

julia> push!(set, Test(1))
Set{Test} with 1 element:
  Test(1)

julia> push!(set, Test(1))
Set{Test} with 2 elements:
  Test(1)
  Test(1)

julia> isequal([set...][1], [set...][2])
true
```
Expected Behavior:

```julia
julia> push!(set, Test(1))
Set{Test} with 1 element:
  Test(1)

julia> push!(set, Test(1)) 
Set{Test} with 1 elements:
  Test(1)
  
  # new push rejected because is_equal(Test(1), Test(1)) == true
  ```
  
 I assume this is the intended behavior, but the documentation should be updated to reflect this by stating that for mutable objects, `===` is used instead of `isequal`.
 
 (Tested in v1.9.0, on Fedora Linux)

**Comment by gbaraldi** [comment]
What it uses for it's set behaviour is a dict, that uses `hash` and hash for mutables isn't only dependent on their value.

**Comment by jakobnissen** [comment]
This buggy behaviour only happens if you define a buggy implementation of isequal. According to the isequal docs, isequal(a, b) must imply hash(a) == hash(b). If you define isequal correctly, Set will indeed use isequal to determine set membership.
