### ISSUE TITLE
Feature request: Base.FixN?

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#50553]
Hello,

I was just wondering why `Base.Fix$(N)` only exists for `N ∈ [1, 2]`? It seems fairly arbitrary.

Could we perhaps add a `Base.FixN` which can take a `::Val{N::Integer}` as an argument, and uses that to index the argument?

Best,
Miles

**Comment by Seelengrab** [comment]
See also https://github.com/JuliaLang/julia/issues/554 for related discussion on currying.

**Comment by nsajko** [comment]
fixed by #54653
