### ISSUE TITLE
No error, no constructor defined when struct has unused type parameter

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#50558]
```
struct Foo{T, S}
    x::T
end

methods(Foo)
# 0 methods for type constructor
```

Present in (at least) 1.8.5, 1.9.2, and master as of 7/9/23

**Comment by vtjnash** [comment]
It isn't an error to define extra parameters, the lowering code is just aware not to generate an outer constructor for it

**Comment by BioTurboNick** [comment]
Okay but... Shouldn't it? Why is it valid to create a struct without a constructor?

**Comment by martinholters** [comment]
It does have contructors, just not ones without specifying the type parameters. But e.g. this works:
```julia
julia> Foo{Int,String}(3)
Foo{Int64, String}(3)
```

**Comment by BioTurboNick** [comment]
Oh. Hmm...

Well in that case, perhaps what needs to happen is that the MethodError should suggest the correct constructor.

```
julia> Foo(3)
ERROR: MethodError: no method matching Foo(::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

julia> Foo{Int}(3)
ERROR: MethodError: no method matching (Foo{Int64})(::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```
