### ISSUE TITLE
RoundNearest produces incorrect results

### ISSUE THREAD

**Issue by EdsterG** [JuliaLang/julia#50560]
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores

Installed via Homebrew

```
julia> round(1.225, digits=2)
1.23
```

The result should be 1.22. If I add/subtract 1 from the input, the output ends up correct, but is wrong for 1.225

**Comment by Seelengrab** [comment]
`1.225` is not exactly representable in floating point - the rounding is correct:

```
julia> big"1.225"
1.225000000000000000000000000000000000000000000000000000000000000000000000000003

julia> big"0.225"
0.2249999999999999999999999999999999999999999999999999999999999999999999999999991

julia> big"2.225"
2.224999999999999999999999999999999999999999999999999999999999999999999999999986
```

**Comment by oscardssmith** [comment]
while this isn't a bug, I recommend installing Julia via juliaup or the official downloads. homebrew does some weird things
