### ISSUE TITLE
Invalid struct definition fails to error

### ISSUE THREAD

**Issue by Octogonapus** [JuliaLang/julia#50573]
This struct definition does not error when ran in the REPL:
```julia
julia> struct Foo{T} <: T where {T}
           x::T
       end
```

This definition is invalid, so I would expect it to error.
(separately, it would be great to have something like this in the language)

I tested this on 1.9.1, 1.10 alpha, and the latest master ffe1a0789a

**Comment by vtjnash** [comment]
`T where T` is just an expression that evaluates to `Any`. That is permitted (valid) as a definition for a supertype.

**Comment by Octogonapus** [comment]
Fair point, I guess that also explains why cases like this work
```julia
julia> abstract type I end

julia> struct Foo{T} <: T where {T<:I}
           x::T
       end

julia> Foo(1)
Foo{Int64}(1)
```
