### ISSUE TITLE
Range performance regression

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#50613]
`run(BaseBenchmarks.SUITE[["array", "index", ("sumelt_boundscheck", "100000:-1:1")]])` regressed in https://github.com/JuliaLang/julia/pull/50118 @LilithHafner

**Comment by LilithHafner** [comment]
Yep. I traded a bug for a performance regression. It'd be great to get the performance back where possible.

**Comment by vtjnash** [comment]
Seems like an acceptable trade for this
