### ISSUE TITLE
Extra allocation in sparse array benchmark

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#50614]
`run(BaseBenchmarks.SUITE[["sparse", "matmul", ("A_mul_B!", "sparse 4000x40, dense 40x40 -> dense 4000x40")]])`
got an extra allocation in https://github.com/JuliaLang/julia/pull/48977 @ViralBShah @Wimmerer

**Comment by Wimmerer** [comment]
Matmul did?

That is... Highly unexpected

**Comment by gbaraldi** [comment]
The performance is the same, but it went from 0 to 1 allocation.

**Comment by KristofferC** [comment]
Is it anything to care about?

**Comment by gbaraldi** [comment]
Extra allocations where we had 0 before are kind of annoying. I think it deserves a look, if it turns out it's unavoidable then fine, but I wouldn't want it going through without a look at least.

**Comment by vtjnash** [comment]
Allocations are not really a problem. And should be opened on SparseArrays repo it is is
