### ISSUE TITLE
Wrong hashes for some `Rational`s

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#50628]
On Julia v1.10.0-alpha1 and master, some `Rational`s which are equal have different hashes:
```julia
julia> hash(5//2) # same hash as on older Julia versions (≥ v1.6)
0x16b7f40fdbb2c57d

julia> hash(Int128(5)//2) # the same hash is also obtained for UInt128(5)//2 and BigInt(5)//2
0xb795033f6f2a0674
```

**Comment by oscardssmith** [comment]
caused by https://github.com/JuliaLang/julia/pull/50041. The change in hash is intentional but the inconsistency isn't. There are a few bugs that were added that I just found. Thanks for the test!

**Comment by oscardssmith** [comment]
My initial guess was partially wrong. The actual problem was caused by both #50041 missing hashing odd denominators combined with the fact that  https://github.com/JuliaLang/julia/pull/49996 was incorrectly computing the position of the right most bit. PR incoming.
