### ISSUE TITLE
OOM despite `--heap-size-hint`

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/julia#50658]
```
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_CONDAPKG_OFFLINE = yes
```
I often see that my code is killed due to out-of-memory. This happens when using pmap, but also when running single threaded single process code that allocates a lot repeatedly from the repl. I tried to add --heap-size-hint, but it did not help.

My workaround: I added the following code to all functions that allocate a lot:
```julia
if Sys.free_memory()/2^30 < 6.0
    GC.gc()
end
```
This should not be needed, the garbage collector should do a full collection before the system runs out of memory on its own.

**Comment by jishnub** [comment]
Could you post a small example that leads to the error? This would help a lot in narrowing the issue down

**Comment by elextr** [comment]
Possibly duplicate of #42566, see from [here](https://github.com/JuliaLang/julia/issues/42566#issuecomment-941335436) on.

**Comment by ufechner7** [comment]
> Could you post a small example that leads to the error? This would help a lot in narrowing the issue down

I happens reproducible with my production code, but I am not allowed to share it... So far it did not happen with the smaller code examples I tried, I will continue to try to create an MWE...

**Comment by ufechner7** [comment]
> Possibly duplicate of #42566, see from [here](https://github.com/JuliaLang/julia/issues/42566#issuecomment-941335436) on.

But in #42566 they say that "`GC.gc(true); GC.gc()` Does not fix it."

But for me `GC.gc()` frees the unreleased memory. So it might be a different issue.

**Comment by elextr** [comment]
> But for me GC.gc() frees the unreleased memory. So it might be a different issue.

Indeed, if manually running GC stops the OOM killer bumping your process off, then the problem is likely not failing to return freed memory to the system, but how GC knows that OOM is approaching and so can work harder to collect unreferenced memory.  IIRC there are several Julia issues about that, but of course my search for them is failing just now.

**Comment by vchuravy** [comment]
What is `--heap-size-hint` you set?

**Comment by oscardssmith** [comment]
It would be good to see if this is happening on recent julia nightlies. @gbaraldi's recent GC logic changes should have fixed this.

**Comment by elextr** [comment]
Just a note that the OOM killer is activated by the total memory of your cgroup IIUC, not just the parent, so would likely include any worker process memory usage as well as the parent process.  

Does `--heap-size-hint` propagate to the workers?

**Comment by vchuravy** [comment]
How big is `bin/kps-image-1.9.so`? Or after just starting Julia how much memory does `ps aux` say you are using?

`--heap-size-hint` is currently not strict, and only measures the live heap and not sysimage/shared libraries etc.

**Comment by MilesCranmer** [comment]
> @elextr Does `--heap-size-hint` propagate to the workers?

I also noticed this in a different context. It seems like the interaction between processes and heap-size-hint is not yet defined (?). I posted an issue here: https://github.com/JuliaLang/julia/issues/50673.

**Comment by MilesCranmer** [comment]
@oscardssmith can you link the PRs you mentioned?

**Comment by oscardssmith** [comment]
https://github.com/JuliaLang/julia/pull/50144

**Comment by ufechner7** [comment]
> How big is `bin/kps-image-1.9.so`? Or after just starting Julia how much memory does `ps aux` say you are using?
> 
> `--heap-size-hint` is currently not strict, and only measures the live heap and not sysimage/shared libraries etc.

```
ufechner@ufryzen:~$ free -h
               total        used        free      shared  buff/cache   available
Mem:            30Gi        11Gi        12Gi        74Mi       6,7Gi        18Gi
Swap:          1,9Gi          0B       1,9Gi
```
and in ps aux 16 times:
```
ufechner   10971  3.5  3.5 2397148 1143096 ?     Ssl  08:18   0:07 /home/ufechner/packages/julias/julia-1.9/bin/julia -Cnative -J/home/ufechner/repos/WindTurbines/bin/kps-image-1.9.so -g1 --bind-to 127.0.0.1 --worker
``
```

**Comment by vtjnash** [comment]
We have updated the heuristics more, so the GC should try harder to avoid exceeding this memory limit. We, however, don't control how much memory is required by external libraries (e.g. LLVM) so we expect precompile to take substantial amounts of memory and only possible to do on large build machines as a requirement for building (but not running).

**Comment by Rkiefe** [comment]
As of Dec 2025, following this thread [https://discourse.julialang.org/t/understanding-memory-usage-in-julia/101647/20]([https://discourse.julialang.org/t/understanding-memory-usage-in-julia/101647/20), I stumbled on the same issue. If I do not place the `GC.gc()` call at the end of a while loop, there is substantial memory build up, as in 100Gb instead of 10-15 Gb after a few dozen iterations.

here is the code snippet
```julia
# using SparseArrays, LinearAlgebra
# RHS::Vector{Float64}
# mu::Vector{Float64}
# u::Vector{Float64}
# Hfield::Matrix{Float64} , 3 by large value
# H::Vector{Float64}
# Hold::Vector{Float64}
# Acsc::Vector{Float64}

att::Int32 = 0
div::Float64 = Inf
while div > picardDeviation && att < maxAtt 

    att += 1
    Hold .= H

    # Updated the compressed stiffness matrix
    n = 0
    for n in 1:16
        for k in 1:mesh.nt
            Acsc[(n-1)*mesh.nt + k] = Ak[n, k] * mu[k]
        end
    end # Acsc

    # Update the global stiffness matrix
    A = sparse(rowIDs, colIDs, Acsc, mesh.nv, mesh.nv)

    # Magnetic scalar potential
    u = [A Lag;Lag' 0]\[-RHS;0] # The augmented matrix is still of the type SparseMatrixCSC
    
    # Check solution
    if any(x -> !isfinite(x), u)
        error("Nans/Infs in the scalar potential")
    end

    # Magnetic field
    Hfield .= 0.0
    for k in 1:mesh.nt
        nds = mesh.t[:,k];

        # Sum the contributions
        for nd in nds
            # obtain the element parameters
            _, b, c, d = abcd(mesh.p,nds,nd)

            Hfield[1, k] -= u[nd]*b;
            Hfield[2, k] -= u[nd]*c;
            Hfield[3, k] -= u[nd]*d;
        end
    end

    # Magnetic field intensity
    for k in 1:mesh.nt
        H[k] = norm(Hfield[:, k])
    end

    # Update magnetic permeability            
    mu[mesh.InsideElements] .= spl(H[mesh.InsideElements])

    # Check deviation from previous result
    div = mu0*maximum(abs.(H[mesh.InsideElements].-Hold[mesh.InsideElements]))
    verbose ? println(att, " | mu0 |H(n)-H(n-1)| = ", div) : nothing

    # Ask for garbage collection because otherwise there is a memory build up
    # GC.gc()

end
```

**Comment by oscardssmith** [comment]
Is this leading to an OOM? If not, this may be correct behavior depending on how much ram your system has.

**Comment by Rkiefe** [comment]
Yes, that's the source of my comment. My workstation has 128 Gb and it runs out of memory even though each iteration should take less than 15 Gb. Only by calling GC.gc() do I avoid an OOM.
Edit: I get 'Killed' on the terminal (Linux Ubuntu 24.04 LTS), the OS is killing the process because of this memory issue.

**Comment by oscardssmith** [comment]
can you make a version of this that is runable? (something that can be copied and pasted and which will run)

**Comment by Rkiefe** [comment]
I made a repo with a lean code that replicates this issue. It needed to be a repo because to run it requires some input data. If you go here: [https://github.com/Rkiefe/julia_GC_issue.git](https://github.com/Rkiefe/julia_GC_issue.git), and clone the repo and run the main.jl you get an OOM.

**Comment by gbaraldi** [comment]
So after some deep digging I found a couple possible improvements to do. But the big issue is that umfpack is allocating huge buffers, that while Julia does keep track of, it's heuristics of when to run a full GC were only applying to actual Julia objects.
I'm writing a PR that adds a new heuristic that's based only on heap size changes since the last GC.
