### ISSUE TITLE
More GC regressions in nightly and 1.10 resulting in OOM crashes and weird stats, possibly related to gcext

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#50705]
Our test suite has started to crash more and more frequently, and now almost constantly, with the latest Julia nightly and 1.10 updates.

It seems we get OOM crashes (but it's hard to say because there are no stacktraces, just messages like this (if there is a way to get a backtrace here, that would be super helpful)
```
[2046] signal (15): Terminated
in expression starting at /home/runner/work/_actions/julia-actions/julia-runtest/latest/test_harness.jl:7
Error: The operation was canceled.
```
We have collect a ton of more data on https://github.com/oscar-system/Oscar.jl/issues/2441 but no MWE as it is difficult to trigger this locally -- it "helps" that the CI runners on GitHub have only a few GB of RAM.

There is also something weird going on some of the statistics; note the crazy `heap_target`
```
Heap stats: bytes_mapped 1728.42 MB, bytes_resident 1286.89 MB, heap_size 1832.69 MB, heap_target 2357.69 MB, live_bytes 1761.48 MB
, Fragmentation 0.961GC: pause 898.46ms. collected 30.505936MB. incr 
Heap stats: bytes_mapped 1728.42 MB, bytes_resident 1286.89 MB, heap_size 1832.31 MB, heap_target 2357.31 MB, live_bytes 1778.76 MB
, Fragmentation 0.971GC: pause 320.62ms. collected 552.570595MB. incr 
Heap stats: bytes_mapped 1728.42 MB, bytes_resident 1317.08 MB, heap_size 2221.08 MB, heap_target 869387521.08 MB, live_bytes 1748.25 MB
, Fragmentation 0.787   39156 ms (1847 ms GC) and 392MB allocated for alnuth/polynome.tst
```

**Comment by gbaraldi** [comment]
This looks like the same thing reported in https://github.com/JuliaLang/julia/issues/40644#issuecomment-1650877903

**Comment by lgoettgens** [comment]
https://github.com/JuliaLang/julia/pull/50682 unfortunately did not help.

**Comment by JeffBezanson** [comment]
We would like to fix this and will continue to work on it with you but I believe it is not a release blocker. @gbaraldi is still looking into it.

**Comment by thofma** [comment]
Note that this also happens for https://github.com/Nemocas/AbstractAlgebra.jl and 1.10-beta2. This is a pure julia package, with no GC shenanigans or C libraries. Github actions CI used to work flawlessly so far, but with 1.10-beta2 the job is often killed because of memory consumption. Here is an example: https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/5867762282/job/16017400384?pr=1405.

**Comment by lgoettgens** [comment]
> Note that this also happens for https://github.com/Nemocas/AbstractAlgebra.jl and 1.10-beta2. This is a pure julia package, with no GC shenanigans or C libraries. Github actions CI used to work flawlessly so far, but with 1.10-beta2 the job is often killed because of memory consumption. Here is an example: https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/5867762282/job/16017400384?pr=1405.

Is this only a 1.10 thing or have you seen any nightly failures for AbstractAlgebra.jl as well ?

**Comment by thofma** [comment]
> Is this only a 1.10 thing or have you seen any nightly failures for AbstractAlgebra.jl as well ?

Only on 1.10 so far, but CI has not run very often in meantime. I just noticed it recently.

**Comment by fingolfin** [comment]
Just to say, currently the AbstractAlgebra CI tests consistently fail with Julia nightly (but pass with 1.10 and older versions), and it really looks like GC is involved. Let me stress again that this is a pure Julia package.

I've written more detailed observations at https://github.com/Nemocas/AbstractAlgebra.jl/pull/1432 but in a nutshell it looks as if it grows the heap target exponentially, but never shrinks it. My conjecture is that the crash happens when it tries to grow the heap from 8 to 16 GB which is too much for those little GitHub CIs -- but since it crashes without a stack trace, and obviously before GC stats can be printed, I am not sure (if someone has a hint how to figure that out, I am all ears).

Of course all of this does not change the fact that for Oscar we heave similar crashes consistently with both Julia nightly *and* 1.10

**Comment by d-netto** [comment]
What's the status of this?

**Comment by thofma** [comment]
I have not encountered any GC problems for a while now. Both 1.10 and nightly are looking good.
