### ISSUE TITLE
Parser regression in 1.10beta1

### ISSUE THREAD

**Issue by nilshg** [JuliaLang/julia#50703]
Fredrik suggested that I link this JuliaSyntax issue here for consideration on the 1.10 milestone:

https://github.com/JuliaLang/JuliaSyntax.jl/issues/332

In short, `using Markdown; md"""$)"""` errors in JuliaSyntax but used to parse fine in the old parser (i.e. works on 1.9 and earlier).

**Comment by fingolfin** [comment]
This also affects us: https://github.com/oscar-system/Oscar.jl/issues/2596

**Comment by JeffBezanson** [comment]
Reduced:
```
julia> Meta.parse(")", 1, greedy=false, raise=true)
```
Should give an error of course, but gives an unexpected internal error. @c42f

**Comment by matthias314** [comment]
Just a comment: As far as I can tell, one also runs into this error when building the Julia documentation.
