### ISSUE TITLE
Unresolved symbol `small_typeof` when `jl_typeof` is used on Windows with 1.10.0-beta1

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaLang/julia#50714]
If I try to compile code on Windows that uses `jl_typeof` compilation fails because `small_typeof`  can't be resolved.

Reproducer:

```C
#include <julia.h>

int main(int argc, char* argv[])
{
    jl_init();
    jl_value_t *v = jl_eval_string("print(sqrt(2.0))");
    jl_value_t *t = jl_typeof(v);
    jl_atexit_hook(0);
    return 0;
}
```

**Comment by gbaraldi** [comment]
@vtjnash do we need to annotate `small_typeof` in `jl_exported_data.inc` or should it just work?

**Comment by topolarity** [comment]
Yep, reproduces for me with MSVC via `cl.exe main.c /I %JULIA_PATH%\include\julia /TP /link /LIBPATH:%JULIA_PATH%\lib libjulia.dll.a /nologo`:
```console
main.c
C:\Users\cody\.julia\juliaup\julia-1.10.0-beta1+0.x64.w64.mingw32\include\julia\julia_assert.h(13): warning C4068: unknown pragma 'GCC'
C:\Users\cody\.julia\juliaup\julia-1.10.0-beta1+0.x64.w64.mingw32\include\julia\julia_assert.h(32): warning C4068: unknown pragma 'GCC'
main.obj : error LNK2019: unresolved external symbol small_typeof referenced in function jl_to_typeof
main.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by giordano** [comment]
> is it possible to view old build logs for Yggdrasil? 

https://buildkite.com/julialang/yggdrasil/builds/4371#01899da4-2877-4b36-af5a-851595227d91

**Comment by Taaitaaiger** [comment]
Thanks! I think I might know why it failed in Yggdrasil but @topolarity couldn't reproduce it: the build script doesn't link julia when the yggdrasil feature is enabled. That feature was originally added because linkjulia.dll.a was absent in the build environment, IIRC.

**Comment by vtjnash** [comment]
Yeah, when you explicitly instructed it not to link against libjulia, we can't really expect that to work: https://github.com/Taaitaaiger/jlrs/blob/f77241a18d93f16242356eae621b5656aaa9afe0/jl_sys/build.rs#L177-L180
Seems like that is a quick fix for your build script though.

**Comment by topolarity** [comment]
This reproduces with our standard build instructions for MSVC (and with the `cl.exe` invocation given above).
