### ISSUE TITLE
Incorrect subtyping result for `Ref{Vector{Tuple{K}} where K} <: Ref{<:Vector{K}} where K`

### ISSUE THREAD

**Issue by topolarity** [JuliaLang/julia#50716]
I might be reasoning about this incorrectly, but Julia declares:
```julia
julia> Ref{Vector{Tuple{K}} where K} <: Ref{<:Vector{K}} where K
true
```

I think this is incorrect because it requires proving that `∃K'. (Vector{Tuple{K}} where K) <: Vector{K'}` which is false.

For comparison:
```julia
julia> Ref{Vector{K} where K} <: Ref{<:Vector{K}} where K
false
```

**Comment by N5N3** [comment]
Another comparison:
```julia
julia> Ref{Vector{Tuple{K}} where K} <: Ref{<:Vector{K}} where K
true

julia> Ref{Vector{Val{K}} where K} <: Ref{<:Vector{K}} where K
false
```

Fixing should be simple, just replace `var_occurs_invariant(t, v)` with `var_occurs_inside(t, v, 0, 0)`
https://github.com/JuliaLang/julia/blob/9f9e989f241fad1ae03c3920c20a93d8017a5b8f/src/subtype.c#L937-L950

Perhaps a typo in #24104?

**Comment by vtjnash** [comment]
Seems to have been intentional, but simply was wrong. Perhaps at the time it was avoiding some other bug. Did you want to make a PR and we can try PkgEval on it?

**Comment by topolarity** [comment]
Thanks @N5N3 !
