### ISSUE TITLE
`circshift(::Tuple, ::Int)` not defined 

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#50732]
`circshift` is not defined on `Tuple`s, only `Array`s. Any reason it shouldn't be?

**Comment by oscardssmith** [comment]
Presumably because we expect the simple splice and concat with splatting to be efficient for tuples. That said, we totally could add it.

**Comment by aravindh-krishnamoorthy** [comment]
Hello @oscardssmith, you mean something like this:

```julia
circshift(x::Tuple, i::Int) = (j = mod(i-1,length(x))+1; (x[j+1:end]..., x[1:j]...))
```

**Comment by adienes** [comment]
I believe
```circshift(x::Tuple, i::Int) = ntuple(j -> x[mod1(j-i, length(x))], Val(length(x)))```
may be a bit more performant

**Comment by oscardssmith** [comment]
@aravindh-krishnamoorthy that is what I meant but it would be worth benchmarking against the other solution.

**Comment by jishnub** [comment]
The first solution is not type-stable, whereas the second one is

**Comment by stevengj** [comment]
Ideally, if the `i::Int` argument is a constant, then the `mod1` calculations will be eliminated by constant folding.   However, `mod1(::Int,::Int)` doesn't currently seem to constant-fold.

**Comment by oscardssmith** [comment]
It should... `mod1` has the right effects.

**Comment by aravindh-krishnamoorthy** [comment]
Hello, this has been sitting around for quite a while now with a known solution. If you guys and @adienes agree, I will create a PR for this. I know this is marked as a "good first issue" and I've solved a few, but I'd be happy to learn more about constant propagation while testing this solution.

**Comment by arhik** [comment]
As an implementation is already merged, this should be closed, I think.
