### ISSUE TITLE
Precompiling problem with PyPlot on 1.10-beta 1

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/julia#50757]
I have an application that I’m using for a paper. The repo is at

https://github.com/ctkelley/N3Presults

I have an MWE (see below). This is breaking the collection of notebooks for a book. Everything works in 1.9.2 but on
1.10 beta 1 I get a infinirte loop of

```
[pid 13413] waiting for IO to finish:
 TYPE[FD/PID]       @UV_HANDLE_T->DATA
 timer              @0x6000037d4080->0x1051e9210
```

Is there a way to stop this? I have no idea why this started to happen today, but it did. MWE below

**Comment by ctkelley** [comment]
I have an mwe. 
```
module mwe


using PyPlot


export xyzzy


function xyzzy()
println("hello")
end

end
```
With Julia 1.9.2 no problem. With 1.10beta1 complete failure.
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.2 (2023-07-05)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using mwe

julia> xyzzy()
hello
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0-beta1 (2023-07-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using mwe
[ Info: Precompiling mwe [top-level]

[pid 18751] waiting for IO to finish:
 TYPE[FD/PID]       @UV_HANDLE_T->DATA
 timer              @0x6000002a3980->0x1035f43d0
```
and it goes on forever.

If I take out ```using PyPlot``` it works.

**Comment by ufechner7** [comment]
Did you try to use PythonPlot instead?

**Comment by giordano** [comment]
Reported already at https://github.com/JuliaPy/PyPlot.jl/issues/572. Ww discussed with Jameson about this at JuliaCon last week, it's likely a package bug.

**Comment by ctkelley** [comment]
The complaints went on forever and the compile never finished. PyPlot and PythonPlot behaved identically.

**Comment by ctkelley** [comment]
I just tried, taking @visr 's advice from [#50706](https://github.com/JuliaLang/julia/issues/50706), but 

```
julia> ENV["JULIA_NUM_PRECOMPILE_TASKS"]=1
```
did not solve the problem for me.

**Comment by giordano** [comment]
https://github.com/JuliaPy/PyPlot.jl/issues/572#issuecomment-1677486953
