### ISSUE TITLE
`@assume_effects !:foldable` is ignored

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#50773]
I wanted to create a pseudo-intrinsic for later matching in a custom compiler pass.

In the past I used to do this with a `@noinline` and `Base.inferrencebarrier`

```
julia> @noinline intrinsic(args...) = Base.inferencebarrier(nothing)
intrinsic (generic function with 1 method)

julia> g(x) = (intrinsic(x); nothing)
g (generic function with 1 method)

julia> @code_typed g(1)
CodeInfo(
1 ─     return Main.nothing
) => Nothing
```

But this seems to no longer work. (I assume due to effects?)

So I decided to add `!:foldable`

```
julia> @noinline Base.@assume_effects !:foldable intrinsic(args...) = Base.inferencebarrier(nothing)
intrinsic (generic function with 1 method)

julia> g(x) = (intrinsic(x); nothing)
g (generic function with 1 method)

julia> @code_typed g(1)
CodeInfo(
1 ─     return Main.nothing
) => Nothing

julia> Base.infer_effects(intrinsic, (Int,))
(!c,+e,+n,+t,+s,+m,+i)
```

Same for `!:removable`:

```
julia> @noinline Base.@assume_effects !:removable intrinsic(args...) = Base.inferencebarrier(nothing)
intrinsic (generic function with 1 method)

julia> g(x) = (intrinsic(x); nothing)
g (generic function with 1 method)

julia> @code_typed g(1)
CodeInfo(
1 ─     return Main.nothing
) => Nothing

julia> Base.infer_effects(intrinsic, (Int,))
(!c,+e,+n,+t,+s,+m,+i)
```

Even the simple `!:effect_free` doesn't seem to apply:

```
julia> @noinline Base.@assume_effects !:effect_free intrinsic(args...) = Base.inferencebarrier(nothing)
intrinsic (generic function with 1 method)

julia> Base.infer_effects(intrinsic, (Int,))
(!c,+e,+n,+t,+s,+m,+i)
```

The docstring mentions `!:nothrow`

```
julia> function intrinsic(args...)
          Base.@assume_effects !:nothrow
          Base.inferencebarrier(nothing)
       end
intrinsic (generic function with 1 method)

julia> Base.infer_effects(intrinsic, (Int,))
(!c,+e,+n,+t,+s,+m,+i)
```

**Comment by Keno** [comment]
That's not what the semantics of the negated effects annotations are. They're supposed to be used like `:foldable !:nothrow`, i.e. they unset previous assertions on the same line. If the compiler can independently prove the effects, that trumps the annotation. To make pseudo-intrinsics, `@noinline` and `Base.inferrencebarrier` is still the correct way to go.

**Comment by vchuravy** [comment]
Okay that makes sense, but probably needs to be better explained in the docs.

My issue then is that m pseduo-intrinsics are now DCE'd.
So I need to add a fake effect.

**Comment by oscardssmith** [comment]
The problem appears to be that Base.infererencebarrier is only tainting consistency and it needs to also taint effect free or terminates. any opinions on which should be tainted?

**Comment by vtjnash** [comment]
I think you are looking for GC.statepoint instead? That taints everything throughout the pipeline at low cost. The inference barrier is not really expected to taint all effects, since it is removed in optimization.

**Comment by gbaraldi** [comment]
Though I'm not sure it does anything special, because it's just a ccall. In fact we should probably add some `@assume_effects` for it because it might pessimize optimizations even though it's technically `total`.

**Comment by vchuravy** [comment]
Yeah I would prefer not having to rely on the semantics of an unrelated intrinsic. `inferencebarrier/compilebarrier` are options, but both are more about type-inference then the effects system, so I don't know if it makes sense to imbue additional information.

**Comment by Keno** [comment]
> My issue then is that m pseduo-intrinsics are now DCE'd. So I need to add a fake effect.

`Base.donotdelete`?

**Comment by vchuravy** [comment]
I knew I was forgetting something. We are getting quite a Zoo of magic functions xD

```
julia> @noinline intrinsic(args...) = Base.donotdelete(nothing)
intrinsic (generic function with 1 method)

julia> g(x) = (intrinsic(x); nothing)
g (generic function with 1 method)

julia> @code_typed g(1)
CodeInfo(
1 ─     invoke Main.intrinsic(x::Int64)::Any
└──     return Main.nothing
) => Nothing
```
