### ISSUE TITLE
`trunc(Bool, 0.6)` is documented to throw but does not

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#50776]
```julia
help?> trunc(Bool, .6)
...
  trunc(T, x) converts the result to type T, throwing an InexactError if the value is not representable.
...

julia> trunc(Bool, .6)
false
```

**Comment by oscardssmith** [comment]
I think this is unclear documentation rather than a bug.`trunc(Int, 0.6)` is meant to return 0. I think what this is meant to be documented as is "if the truncated value is not representable (i.e. `trunc(Bool, 2.5)`))
