### ISSUE TITLE
1.9.2 Base.map!(|,a,a,b) yields wrong answer on BitVector

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#50780]
The  testset for the DataStructures.jl package are now failing in 1.9.2.  In particular, IntSet is not working.  I have traced the error to a bug with the Base.map! function applied to BitVector.  See below for the incorrect output from map!:

EDIT: I did not report this bug correctly in my first post.  The bug is actually with `map!(|,a,a,b)` not with `map!(|,a,b)`.  Please refer to my follow-up post below.

```julia
julia> a = BitVector([1,1,0,0,1,1,0,0]);

julia> b = BitVector([1,0,1,0,1,0,1,0]);

julia> map!(|, a, b);

julia> a
8-element BitVector:
 1
 0
 1
 0
 1
 0
 1
 0
```

**Comment by adienes** [comment]
that looks correct to me, what output were you expecting?

note that `map!` here is doing something equivalent to `a .= .|(b)`,  not `a .= .|(a, b)`

**Comment by StephenVavasis** [comment]
You are right, sorry.  I will close this issue.  But I am now confused how union of two IntSets is supposed to work since it seems to rely on `map!(|,a,b)` replacing `a` with the bitwise OR of `a` and `b` in line 94 of int_set.jl in the DataStructures package.  And apparently this statement worked fine in pre-1.9 versions of Julia.

**Comment by oscardssmith** [comment]
well that doesn't work in 1.8.5 at least...
```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.5 (2023-01-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> map!(|, [false, true], [true, false])
2-element Vector{Bool}:
 1
 0

julia> map!(|, BitVector([false, true]), BitVector([true, false]))
2-element BitVector:
 1
 0
 ```

**Comment by StephenVavasis** [comment]
Wait!  There is a new bug in Base.map!  I am reopening this issue.  Here is the bug.  It is with `map!(a,a,b)`, not `map!(a,b)` as I said earlier.  Sorry for the confusion.   I have confirmed that this behavior has changed since 1.6.7.

```julia
julia> a = BitVector([1,1,0,0,1,1,0,0]);

julia> b = BitVector([1,0,1,0,1,0,1,0]);

julia> map!(|,a,a,b);

julia> a
8-element BitVector:
 1
 0
 1
 0
 1
 0
 1
 0
```

**Comment by oscardssmith** [comment]
Specifically the problem is new in 1.9 and affects the last chunk of the array and is caused by https://github.com/JuliaLang/julia/pull/47013.

**Comment by oscardssmith** [comment]
For another related bug:
```
julia> a = BitVector([1,0])
2-element BitVector:
 1
 0

julia> map!(!, a, a)
2-element BitVector:
 1
 1
```

**Comment by oscardssmith** [comment]
luckily it's easy to fix. Thanks for the report!
