### ISSUE TITLE
New parser does not fail early for large files

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#50799]
I accidentally typed `julia large_file.txt`, forgetting the name of the script. This causes the new JuliaSyntax parser to hang, presumably trying to parse a 1.4 GiB file (or trying to display millions of syntax errors)

The old flisp parser errors immediately, as there is a syntax error on line 1.

**Comment by c42f** [comment]
One of the premises of the new parser is to always provide a syntax tree back to the caller which covers the whole source file. If errors are present, that tree will contain error markers. This is very useful for editor tooling.

But in this particular case it results in a bad user experience to have Julia hang or appear to hang.  Perhaps there's something we could do about this. For example just have JuliaSyntax bail out on extremely large files and encapsulate the tail of the file in one big error token. Or something.

Could you provide a sample of the type of content in "large_file.txt"? I'd be curious as to the exact failure mode here.

**Comment by oscardssmith** [comment]
You can probably just use any large text file. https://www.gutenberg.org/cache/epub/1727/pg1727.txt should do nicely.

**Comment by c42f** [comment]
Parsing 700 MB of malformed text from a repeated version pg1727.txt takes ~50 seconds:

```julia
julia> using JuliaSyntax

julia> str = read("pg1727.txt", String);

julia> @time try parseall(Expr, str^1000) catch ; end
 46.374221 seconds (25.20 M allocations: 4.515 GiB, 0.50% gc time, 0.06% compilation time)

julia> length(str^1000)/1e6
710.502
```

This isn't great, but neither is it a complete disaster. I think it'd probably make sense to detect "parsing this file is a complete disaster, it's probably not even valid Julia syntax" somehow and bail out if we can.

**Comment by jakobnissen** [comment]
Large files with lots of non-text symbols is likely slower, since it generates more errors per MB. Bailing early definitely sounds like the right thing to do

**Comment by KristofferC** [comment]
FWIW, I think the current behavior is fine. You try parse a huge file, it might take some time. Not strange.

**Comment by jakobnissen** [comment]
I didn't try to parse it, I tried to execute it. There is no value spending three minutes producing 10 million parser errors when it's already clear on line 1 that the file can't run.

Sure this is not a release blocking bug or a big usability concern, but it is a user experience regression, and it can almost certainly be fixed.

**Comment by nsajko** [comment]
Yeah, it's not a big issue for experienced users, but it seems like something embarrassing enough to hurt the uptake of Julia a bit.

**Comment by KristofferC** [comment]
>  but it seems like something embarrassing enough to hurt the uptake of Julia a bit.

Please. Let's tone down the hyperbole a bit.

**Comment by c42f** [comment]
I've moved this to an upstream issue https://github.com/JuliaLang/JuliaSyntax.jl/issues/345 because I find that easier to keep track of. Thanks for reporting!
