### ISSUE TITLE
Performance regression makes function unusable on 1.10.0-beta1

### ISSUE THREAD

**Issue by nathanrboyer** [JuliaLang/julia#50859]
Sample code for testing is at the following repository: https://github.com/nathanrboyer/JuliaNightlyTestCode

`polyfit` function takes 5 minutes on 1.9 and over 1 day on 1.10. I get similar performance to 1.10.0-beta1 using the Nightly build from August 8th, 2023.

**Comment by nathanrboyer** [comment]
My timings using the trimmed data are below.

```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.239
Commit c40ecd3f03 (2023-08-08 03:06 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

julia> include("test.jl")
  0.565770 seconds (2.06 M allocations: 1.490 GiB, 18.18% gc time)
  0.420606 seconds (2.06 M allocations: 1.490 GiB, 20.03% gc time)
1102.520814 seconds (663.43 M allocations: 50.455 GiB, 0.37% gc time, 0.02% compilation time)
```

```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e90 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code.cmd
  JULIA_NUM_THREADS =

julia> include("test.jl")
  2.359726 seconds (6.76 M allocations: 3.041 GiB, 16.36% gc time, 72.71% compilation time)
  0.601131 seconds (2.38 M allocations: 2.750 GiB, 32.01% gc time)
  2.536775 seconds (8.09 M allocations: 5.714 GiB, 17.44% gc time, 54.94% compilation time)
```

**Comment by gbaraldi** [comment]
So this seems to have regressed a couple of times actually. 
I'm doing the bisec right now, but one big regression happened in
35e4a1f9689f4b98f301884e0683e4f07db7514b @vtjnash

**Comment by Seelengrab** [comment]
That's a 288x regression :open_mouth:

**Comment by gbaraldi** [comment]
It actually has exponential behaviour here which is very fun.

**Comment by Seelengrab** [comment]
Seems like a good candidate for GC benchmarks then!

**Comment by gbaraldi** [comment]
It's not a GC regression at all, https://github.com/JuliaLang/julia/commit/35e4a1f9689f4b98f301884e0683e4f07db7514b made it super bad and fbbe9edf768970ee6b711f3c271e42b0cf828818 made it superbad 2x

**Comment by brenhinkeller** [comment]
Is there an intuitive explanation for why making `Tuple{Union{}}` "unconstructable" caused this?

**Comment by gbaraldi** [comment]
I believe it's the change to the broadcasting code that caused this.

**Comment by gbaraldi** [comment]
So what I think is going on here is that this code is somewhat unstable but `return_type` moved from a compile time thing to a runtime one.

**Comment by brenhinkeller** [comment]
ahh, interesting

**Comment by nathanrboyer** [comment]
I'm open to just making my code more type-stable if you have suggestions for that and think it unlikely that others will run into this issue. I thought that I had defined types well enough for the compiler but apparently not.

**Comment by vtjnash** [comment]
Sounds probably the same as https://github.com/JuliaLang/julia/issues/51129
