### ISSUE TITLE
REPL does not understand `\Mu` and `\Nu`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#50911]
The REPL does not complete the upper case greek letters `\Mu` and `\Nu`. The auto-generated tables call these letters `\upMu` and `\upNu` instead. This is counter-intuitive since all other upper case letters are available without an `up` prefix, e.g. `\Alpha`.

```
julia> versioninfo()
Julia Version 1.11.0-DEV.278
Commit 71570298a4 (2023-08-14 12:53 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin22.6.0)
  CPU: 16 × Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
```

**Comment by i9e1** [comment]
Input greek / sequence -> Output latin seems ok, but the other way around?
I'm unsure which latex packages defines `\Alpha`, as I'm used to the latin uppercase letters if they coincide with greeks.
Isn't the problem that that something like `\Alpha` works?


Lines 2677-2679 in #50913 :
Do you really want to reverse map latin `M` to greek `\Mu`?

**Comment by i9e1** [comment]
`unicode.xml` also defines capital Mu, Nu. They all look like the latin versions, but have different unicodes. Same for the working ones, e.g. `\Alpha, \Beta`.
I would expect that Mu, Nu, Omikron are excluded in all of ("AMS", "IEEE", "mathlatex", "latex"). (for some reason or by incident?)

IMHO your approach is not the best to tackle this inconsistency.

```
julia> a = 'Α' # \Alpha tab
'Α': Unicode U+0391 (category Lu: Letter, uppercase)

julia> b = 'A'
'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)
```

**Comment by stevengj** [comment]
I tentatively agree that we should rationalize `\upMu` and `\upNu` to `\Mu` and `\Nu`, although these symbols have limited utility because of their resemblance to Latin symbols.   These abbreviations happened in the initial automated import, which had some odd choices.

This should be an easy PR.

**Comment by stevengj** [comment]
Indeed, as far as I can tell the `\up` here stands for "upright" (ala the [upgreek package](https://ctan.org/pkg/upgreek?lang=en)) and not "uppercase".   Which is silly for us to keep because our other Greek completions are upright by default.)
