### ISSUE TITLE
`JULIA_NUM_THREADS` doc should mention about interactive threads number configuration

### ISSUE THREAD

**Issue by AtsushiSakai** [JuliaLang/julia#50936]
This is a small doc improvement idea.
From v1.9, interactive thread number can be configurable with JULIA_NUM_THREADS env
> export JULIA_NUM_THREADS=3,1

Ref: https://docs.julialang.org/en/v1/manual/multi-threading/#man-threadpools

However, [the latest doc about JULIA_NUM_THREADS](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_NUM_THREADS) does not mention it:
![image](https://github.com/JuliaLang/julia/assets/3813847/52914a39-065f-42b7-9b57-7e295457901a)

I think it should do it.

**Comment by nickrobinson251** [comment]
related https://github.com/JuliaLang/julia/issues/48960
