### ISSUE TITLE
Broadcast.result_style(x::S, y::S) does not work unless S() is a constructor

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#50937]
[This line](https://github.com/JuliaLang/julia/blame/90b4eedbf4b2beae0b12e6b8317e15ef0bb91126/base/broadcast.jl#L460) does not work with broadcast styles that have fields, eg

```julia
import Broadcast: BroadcastStyle

struct MyStyle <: BroadcastStyle
    some_info
end

BroadcastStyle(x::MyStyle, y::MyStyle) = MyStyle(compute_field(x.some_info, y.some_info))
```

A possible fix (in user code) is defining
```julia
Broadcast.result_style(::MyStyle, ::MyStyle)
```
but that function does not seem to be part of the API.

A possible fix (in Julia) would be 
```julia
result_join(::Any, ::Any, x::S, y::S) where S<:BroadcastStyle = x # just pick the first
```

I wanted to ask if this matches the intention of #20740 before making a PR.

**Comment by vtjnash** [comment]
Yes, that matches the intent of https://github.com/JuliaLang/julia/pull/49395 also, if you could make a PR

**Comment by vtjnash** [comment]
I think it might be `x === y ? x : error("custom rule needed")` though?
