### ISSUE TITLE
`mean(::UnitRange)` overflows

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#50982]
```jl
using Statistics
julia> mean(1:typemax(Int64))
-4.611686018427388e18
```

```
  mean(itr)

  Compute the mean of all elements in a collection.
```

From the documentation one might expect a number between the two endpoints, but I got a number outside that range. I think this is a bug.

**Comment by oscardssmith** [comment]
Good catch. Right now this is implemented as `(first(r) + last(r)) / 2`. It should probably be `first(r)/2 + last(r)/2`.

**Comment by petvana** [comment]
Seems to be already reported in https://github.com/JuliaStats/Statistics.jl/issues/120 and there is even an unmerged PR for that https://github.com/JuliaStats/Statistics.jl/pull/115.

**Comment by chunjiw** [comment]
> Good catch. Right now this is implemented as `(first(r) + last(r)) / 2`. It should probably be `first(r)/2 + last(r)/2`.

Or perhaps `first(r) + (last(r) - first(r)) / 2`

**Comment by jariji** [comment]
I like @chunjiw 's proposal because it works better on affine spaces like dates or Fahrenheits where you can't divide positions by numbers (you can only divide displacements).

**Comment by chunjiw** [comment]
I'm wondering is the performance gain of "one less float point division" significant enough? When I started programming I was taught `x + (y-x) / 2` is the best way to calculate mean.

**Comment by oscardssmith** [comment]
llvm should be able to get rid of the floating point division since it's by a constant power of 2
