### ISSUE TITLE
You can't call findfirst on Zip.

### ISSUE THREAD

**Issue by JoaoAparicio** [JuliaLang/julia#50983]
** Describe the bug
You can't call `findfirst` on `Zip`.

** To Reproduce

```julia
x = [1,2,3]
y = [10,2,30]
findfirst(z -> z[1] == z[2], zip(x, y))
ERROR: MethodError: no method matching keys(::Base.Iterators.Zip{Tuple{Vector{Int64}, Vector{Int64}}})
```

** Expected behavior
The above should return `2`.

** Desktop (please complete the following information):

```
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 0
```

** Additional context
The above happens because `findfirst`'s default implementation in `array.jl` calls `pairs` on the input, and `pairs` default implementation in `abstractdict.jl` calls `keys` and `values` on the input, and `Zip` doesn't have those methods defined.

I suggest that a solution is to provide an implementation for `pairs(::Zip)` which should be just `enumerate`.

```julia
Base.pairs(x::Base.Iterators.Zip) = enumerate(x)
x = [1,2,3]
y = [10,2,30]
findfirst(z -> z[1] == z[2], zip(x, y))  # 2
```

**Comment by Seelengrab** [comment]
See the discussion in the linked PR #50984 - `Zip` is not indexable, and `findfirst` returns an index.
