### ISSUE TITLE
Escaped characters in documentation

### ISSUE THREAD

**Issue by carolfs** [JuliaLang/julia#50996]
This is a tiny issue. On this documentation page, the string `&hArr;` is escaped and displayed exactly like that instead of '⇔' as it does on GitHub. I believe just using '⇔' in the Markdown document would work on both sites.

https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Julia-and-hArr;-C/C:-Namespaces

**Comment by 1j01** [comment]
This issue is a duplicate of https://github.com/JuliaLang/julia/issues/49991
