### ISSUE TITLE
delateat! does not handle views

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#51006]
`deleteat!` throws an error when given a view.
"The meaning seems straightforward: `deleteat!(view) = deleteat!(view indices)`."

This issue follows up on this [item on slack](https://julialang.slack.com/archives/C6GHSTN4T/p1691776298017049) .
@StefanKarpinski added "Definitely just a missing method that should be added"

**Comment by mbauman** [comment]
I don't think this is so straightforward.  In fact, many views cannot be mutated like this: all ranges and `SubArray` itself are immutable so the only views that could theoretically support `deleteat!` would be those that use a mutable array of indices.

We do also document that you shouldn't mutate the size of the parent array after taking a view of it — and so while this could be done in a way that's internally consistent for some view types, it feels like it's leading folks to murky waters.

**Comment by JeffreySarnoff** [comment]
Makes sense .. I have never used `deleteat!`.  
> We do also document that you shouldn't mutate the size of the parent array after taking a view of it ...
_yes, that is murky_

**Comment by mbauman** [comment]
> How mutating the parent array is related to deleteat! on views? It would only touch indices, not parent - so this restriction stays.

Oh man, I had a completely different impression of what this would do! In my mind, views are "just" a transparent re-shuffling/subsetting of the parent array.  Assigning into a view mutates the parent array.  In addition, I think of `deleteat!` as removing _the item_ at a given index, and not just removing that index.  And conversely, if we were to support `insertat!`, we'd definitionally have to modify the parent array to place the value somewhere.

So all these things together meant I was thinking we'd mutate _both_ the parent and the list of indices.

The fact that we had different ideas of what this would do seems like pretty good evidence that we shouldn't do either.

**Comment by mbauman** [comment]
All other `!` functions mutate the parent, though.  For example `sort!` and `Random.shuffle!` don't change a view's indices, even when they could.

You're right that the two of us having different mental models is not in and of itself insurmountable, but it is another red flag to me.

I would find this pretty hard to reason about and use.

**Comment by adienes** [comment]
seems pretty impossible to support

```
julia> x = collect(1:6);

julia> @views y = reshape(x, (3,2));

julia> deleteat!(x, 1) # what should happen to y?
```

currently the above gives `ERROR: cannot resize array with shared data` which I very much appreciate

"borrow-checker lite"

**Comment by adienes** [comment]
I think this is more about needing a better error message than about missing functionality

```
julia> x = collect(1:6);

julia> @views y = reshape(x, (2,3));

julia> @views z = y[1:3];

julia> deleteat!(z, 1)
ERROR: MethodError: no method matching deleteat!(::SubArray{Int64, 1, Vector{Int64}, Tuple{UnitRange{Int64}}, true}, ::Int64)

Closest candidates are:
  deleteat!(::Vector, ::Integer)
   @ Base array.jl:1519
  deleteat!(::Vector, ::Any)
   @ Base array.jl:1566
  deleteat!(::BitVector, ::Integer)
   @ Base bitarray.jl:953
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[55]:1

julia> deleteat!(x, 1)
ERROR: cannot resize array with shared data
```

I very much appreciate the "borrow-checker lite" with the error when trying to `deleteat!` or `insert!` on the original array, and it would make sense to me to extend that to array views

**Comment by adienes** [comment]
I can kind of understand how `deleteat!` might work that way on a view, but `insert!` can't make sense that way otherwise after adding data that doesn't exist in the parent it's not really a `SubArray` anymore --- just an independent array that happens to share some memory

**Comment by adienes** [comment]
right, understood. it just feels funky that
1. `insert!` and `deleteat!` are kind of paired, in that most things supporting deletion also support insertion
2. other operations mutating the view also mutate the underlying array
3. afaik there are no other operations available to views that are not available to the underlying array

so adding a `deleteat!` for a view seems inconsistent in three distinct ways, and I would instead recommend this error with the `cannot resize array with shared data` message

**Comment by LilithHafner** [comment]
Here are a few possible implementations
```julia
deleteat_1!(view, ind) = (delete_at!(view.parent, ind); resize!(view.inds, length(view.inds)-length(ind)); view) # @mbauman's interpretation
deleteat_2!(view, ind) = (deleteat!(view.inds, ind); view) # Proposed on slack, @aplavin's interpretation
deleteat_3!(view, ind) = (deleteat!(view.parent, ind); view) # the only version that works on `view([1,2,3], 1:2)`
```

My order of preference is `nothing >> deleteat_1! ≈ deleteat_2! >> deleteat_3!`.

One reason I prefer `deleteat_1!` over `deleteat_2!` is that I think this generic fallback for `deleteat_generic!(::AbstractArray, ::Int)` in terms of `deleteatend!(::AbstractArray)` should work:

```julia
function deleteat_generic!(v::AbstractArray, ind::Int)
	for i in ind:lastindex(v)-1
        v[i] = v[i+1]
    end
    deleteatend!(v)
end
```

And it is consistent with `deleteat_1!`.

I think `deleteat_2!` is more useful but `deleteat_1!` is more sensible/consistent with other methods, so I prefer to have neither.

**Comment by ToucheSir** [comment]
One fly in the ointment of any approach which tries to mutate the view indices is that many views are constructed with immutable index types:
```julia
julia> view(ones(5), 1:3).indices |> typeof
Tuple{UnitRange{Int64}}
```
This could lead to confusion when some views can support `deleteat!` etc, some can't and it's not obvious what the difference is. Whether that potential confusion is sufficiently offset by the potential utility of supporting such functions on views is something I'll leave to the previous discussants.

**Comment by ToucheSir** [comment]
Mutability of arrays and array wrappers tends to fall into one of two categories:
1. The array itself can be mutated
2. The `parent` of the array can be mutated

Making `deleteat!` work as proposed would introduce a third possible criterion:
3. The indices of the view can be mutated

Whether the added complexity is worth the benefit I cannot say, but it is objectively adding complexity to the way people currently think about array mutability.

**Comment by mbauman** [comment]
Views are themselves first-class arrays that explicitly say they lazily reference (and re-index into) the original array.  All other mutating functions on a view mutate that original array.  Adding something that behaves differently is certainly cause for confusion.

Views are also intended to be highly performant — and structured such that you can create many at low (or no) cost. In a use-case like what I'm imagining you may be doing, I think I'd just explicitly work with a set of indices — popping elements directly from them — and re-creating views as needed to work with the whole object.
