### ISSUE TITLE
immutable cannot be the key of dictionary，but why this code can be runned？

### ISSUE THREAD

**Issue by A-Pai** [JuliaLang/julia#51018]
immutable cannot be the key of dictionary，but why this code can be runned？
Dict([1] => "Li Ming", [2] => 18)

![QQ截图20230823170729](https://github.com/JuliaLang/julia/assets/5112397/34a94832-d6cd-48c6-93b2-398212c93db1)

**Comment by KristofferC** [comment]
Please use https://discourse.julialang.org/for questions.

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  Li Gang
