### ISSUE TITLE
Incorrect conversion to unisigned integer

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#51063]
```julia
julia> convert(UInt32, 4.2949673f9)
0xffffffff
```

`4.2949673f9` is one greater than the maximum value of a `UInt32` (`4.2949673f9 == typemax(UInt32)+1`) so an inexact error should be thrown here:

```julia
function (::Type{$Ti})(x::$Tf)
    if ($(Tf(typemin(Ti))) <= x <= $(Tf(typemax(Ti)))) && isinteger(x)
        return unsafe_trunc($Ti,x)
    else
        throw(InexactError($(Expr(:quote,Ti.name.name)), $Ti, x))
    end
end
```

However, the comparison that happens is `4.2949673f9 <= Float32(typemax(UInt32))` which is true even though `4.2949673f9 > typemax(UInt32)`.

**Comment by LilithHafner** [comment]
unsafe_trunc calls [llvm's fptoui](https://llvm.org/docs/LangRef.html#fptoui-to-instruction) under the hood so this result is a [poison value](https://llvm.org/docs/LangRef.html#poisonvalues)

**Comment by gbaraldi** [comment]
The issue is that at this value the `eps` of Float32 is `512` so 
```julia
julia> Float32(typemax(UInt32))
4.2949673f9

julia> ans + 1 
4.2949673f9
```

**Comment by LilithHafner** [comment]
Here's a full list of failures:
```julia
julia> UInt128(3.402823669209385e38)
0x00000000000000000000000000000000

julia> UInt64(1.8446744073709552e19)
0xffffffffffffffff

julia> UInt64(1.8446744f19)
0xffffffffffffffff

julia> UInt32(4.2949673f9)
0xffffffff

julia> UInt128(1.8446744073709552e19)
0x00000000000000010000000000000000
```
for reference about what those float values are actually:
```julia
julia> UInt128.((1.8446744073709552e19, 1.8446744f19, 4.2949673f9))
(0x00000000000000010000000000000000, 0x00000000000000010000000000000000, 0x00000000000000000000000100000000)
```
