### ISSUE TITLE
InexactError shows `Inf16` as `Inf`

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#51087]
This is slightly misleading:
```julia
julia> UInt128(Inf16)
ERROR: InexactError: UInt128(Inf)
Stacktrace:
 [1] UInt128(x::Float16)
   @ Base ./float.jl:888
 [2] top-level scope
   @ REPL[1]:1
```

The 16 is lost is here:
https://github.com/JuliaLang/julia/blob/b4052a5fa5af2c006612c962d6cf26808575c01b/base/errorshow.jl#L177C5-L177C27

**Comment by Jay-sanjay** [comment]
Hello , sir I will like to help for this issue , will you please provide with some hints for how to resolve this error message

**Comment by LilithHafner** [comment]
Thanks!

I think the error is in the function
```julia
function showerror(io::IO, ex::InexactError)
    print(io, "InexactError: ", ex.func, '(')
    nameof(ex.T) === ex.func || print(io, ex.T, ", ")
    print(io, ex.val, ')')
    Experimental.show_error_hints(io, ex)
end
```
defined in base/errorshow.jl

So if you can find a different implementation of the function that shows Inf16 as Inf16, that would fix it.

You could try redefining the function in a repl with
```julia
julia> function Base.showerror(io::IO, ex::InexactError)
    print(io, "something new")
end

julia> UInt128(Inf16)
ERROR: something new
[...]
```

to get it to preserve the type information. I suspect calling a different show method (e.g. show instead of print) might work.

**Comment by Jay-sanjay** [comment]
Thank you sir !
Yes I will start on it .

**Comment by longemen3000** [comment]
you could replace `print(io, ex.val, ')')` for `print(io, repr(ex.val), ')')`, that should fix the error, as:
```julia> repr(Inf16)
"Inf16"
```

**Comment by Jay-sanjay** [comment]
@LilithHafner @longemen3000  Sir I guess the code provided above got changed a bit , so what next can be done
https://github.com/JuliaLang/julia/blob/8d4d641507d860038982e977e14eea1789a78e47/base/errorshow.jl#L178

**Comment by persinammon** [comment]
Hi, if this is still open, I can attempt it too

**Comment by LilithHafner** [comment]
This has not yet been resolved. In general, we try to mark all resolved issues as closed and all unresolved issues as open.
