### ISSUE TITLE
Add merge(a::Tuple, b::Tuple)

### ISSUE THREAD

**Issue by freemin7** [JuliaLang/julia#51100]
As per https://github.com/JuliaLang/julia/issues/2754 the official way to merge two `Tuple`s is `tuple(a...,b...)` this solution is elegant and it teaches people things about the language. However this syntax is not supported for `NamedTuple`s which why the `merge` method exists for those.

I propose adding `merge` for Tuples to the core language.

Open questions:
`merge` does de-duplication for `NamedTuple`s. There are three modes of de-duplication possible

- none: `merge((4,2,2,3),(3,2,1)) == (4,2,2,3,3,2,1)`
- right side de-duplication `merge((4,2,2,3),(3,2,1)) == (4,2,2,3,1)`
- total de-deduplication: `merge((4,2,2,3),(3,2,1)) == (4,2,3,1)`

I don't care which is chosen. I only care about making it easier to discover that you can `merge` `NamedTuple`s. This would be accomplished by adding a line to `tuple` which mentions the merge method for tuples. Should one of the de-duplication modes not have an idiomatic "for loop free" way yet making this the meaning of `merge(a::Tuple, b::Tuple)` would be beneficial to Tuples.

I would accept `NamedTuple`s  are dict-like and `Tuple`s are array-like and merge is for dict-like things and one doesn't want to blend those concepts as a refutation.

**Comment by mikmoore** [comment]
If this were added, I think the only way this would make sense is with "no de-duplication" i.e. `merge((1,2,3),(1,2,3)) == (1,2,3,1,2,3)`. The other modes are not type stable. Tuples are keyed by index, not value. If one wants to merge sets of *values*, we have the `Set` container.

But this is redundant with `(a...,b...)`, so it would just be an alternate syntax.

**Comment by Seelengrab** [comment]
I think adding a new meaning to `merge` (the non-deduplicated one) is a bit confusing, and leads to less generic code due to the difference in behavior.

**Comment by freemin7** [comment]
> > However this syntax is not supported for `NamedTuple`s which why the `merge` method exists for those.
> 
> ```
> julia> a = (;x=1, y=2)
> (x = 1, y = 2)
> 
> julia> b = (;y=3, z=4)
> (y = 3, z = 4)
> 
> julia> (;a..., b...)
> (x = 1, y = 3, z = 4)
> ```
> 
> ?

I took longer then i would like to admit to find merge. I tried many things like this and just didn't get it working. I guess my problem can be entirely solved by better documentation. No need to change the language.
