### ISSUE TITLE
`Plots` precompilation broken on future `1.10`

### ISSUE THREAD

**Issue by t-bltg** [JuliaLang/julia#51117]
Example of [failing CI](https://github.com/JuliaPlots/Plots.jl/actions/runs/6022695141/job/16337972326) on `1.10-beta2`.

CI passes on `1.6 -> 1.9`.

Looks like https://github.com/JuliaLang/julia/pull/50541 ?

cc @BeastyBlacksmith.

**Comment by vtjnash** [comment]
Looks like several package bugs similar to this
```

Failed to precompile InspectDR [d0351b0e-4b05-5898-87b3-e2a8edfddd1d] to "/home/runner/.julia/compiled/v1.10/InspectDR/jl_zzmLrF".
ERROR: LoadError: Creating a new global in closed module `__toplevel__` (`_devmode`) breaks incremental compilation because the side effects will not be permanent.
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/InspectDR/cYUMk/src/InspectDR.jl:8
```

**Comment by BeastyBlacksmith** [comment]
As far as I understand it is only broken if you change the default backend, since then it is trying to load a package at precompile time that is not a direct dependency of Plots

**Comment by BioTurboNick** [comment]
So, evaluating into Main during backend initialization has been something Plots has been doing for 6 years, and selecting a default initial backend during precompilation has been around for 1 year (https://github.com/JuliaPlots/Plots.jl/pull/4566), but Julia 1.10 has broken it.

**Comment by vtjnash** [comment]
Sounds like it is implemented wrong for the current loading system. When first written, there probably wasn't PkgId yet and such. But eventually needed to be fixed to reference dependencies correctly in their manifest
