### ISSUE TITLE
Remove wrong "Used by" section

### ISSUE THREAD

**Issue by Tortar** [JuliaLang/julia#51137]
I know that Julia currently doesn't have many users compared to other languages while it would deserve it but this is a bit too much :-)

![image](https://github.com/JuliaLang/julia/assets/68152031/a5c4de0e-eddc-4563-8695-30158ea3bab5)

Seriously, even if I think this info wouldn't be trusted by anyone, it is annoying, can it be disabled? Or is there a reason for it? I think a member could do it by disabling the dependency graph: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exploring-the-dependencies-of-a-repository#changing-the-used-by-package

**Comment by ViralBShah** [comment]
Not sure how to:

<img width="783" alt="Screenshot 2023-08-31 at 7 14 59 PM" src="https://github.com/JuliaLang/julia/assets/744411/1be6e5e6-f4d4-4792-984b-b7730e24cf54">

**Comment by giordano** [comment]
@ViralBShah if you click on the :gear: icon in the top right corner of the main page of the repository, you should be able to edit the details of the repository and deselect the "packages" option, which I believe is what's shown there.

**Comment by Tortar** [comment]
It took me sometime to find it because that icon is also shown next to "Settings" and then I finally found it in one of the repo where I'm admin, so this is where that icon is

![image](https://github.com/JuliaLang/julia/assets/68152031/57085c61-dcd5-4668-ac14-35b7548ee11d)

indeed seems like the correct "fix"

**Comment by ViralBShah** [comment]
Packages was never selected. This is what we have:

<img width="632" alt="Screenshot 2023-08-31 at 9 07 26 PM" src="https://github.com/JuliaLang/julia/assets/744411/4975def9-c26e-4950-9305-05dd753534e5">

**Comment by Tortar** [comment]
Indeed looking around they seem like independent sections, I looked around and I saw that the CPython repo doesn't have a Used By section, the dependency graph has more than 1 package and the default is @buckpkg/python

![image](https://github.com/JuliaLang/julia/assets/68152031/afa7effc-2548-4aca-be19-8fc8008693a1)

but the main page doesn't show anything on the enabled packages section.

Anyway seems like a general problem with Github since even the Rust repo suffer from the same problem: 

![image](https://github.com/JuliaLang/julia/assets/68152031/10a59b0a-e1e7-46f1-b94a-6ba653ed4522)

**Comment by Keno** [comment]
I don't think there's anything we can do to change this. FWIW, I also don't have the "Used By" section, so GitHub may be A/B testing this. Perhaps worth raising this feedback with them directly: https://github.com/orgs/community/discussions

**Comment by ViralBShah** [comment]
I spoke with a contact at GitHub who kindly disabled that section for us and has raised an issue internally
