### ISSUE TITLE
Undocumented exported names not detected

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#51167]
Exported names should be documented

```jl

julia> using Markdown

julia> md""


help?> md""
  No documentation found.

  Markdown.@md_str is a macro.
```

The Documenter config https://github.com/JuliaLang/julia/blob/fe2eeadc0b382508bef7e77ab517789ea844e708/doc/make.jl#L303 has `strict=true` so I'm not sure why this isn't being detected and failing CI.

**Comment by mortenpi** [comment]
I think the actionable item here is to add a docstring to the `@md_str` macro.

**Comment by jariji** [comment]
That's https://github.com/JuliaLang/julia/issues/51168. This one is for
