### ISSUE TITLE
Markdown documentation should explain the md string macro.

### ISSUE THREAD

**Issue by DrEntropy** [JuliaLang/julia#51168]
[Markdown] (https://github.com/JuliaLang/julia/blob/master/stdlib/Markdown/docs/src/index.md) documentation should have a section on the existence and use of the `md"##Markdown Here"`  string macro.  As a newbie I ran into this syntax and could not figure out what it was! I suppose it is obvious what it does from experimentation, but I could not find any documentation.   

PS: I ran into it when I was toying around with Pluto.js  where this macro is used extensively.

**Comment by krishjoshi7** [comment]
can you please explain what string macro does

**Comment by DrEntropy** [comment]
Perhaps that is not the right terminology.... the [documentation](https://docs.julialang.org/en/v1/manual/metaprogramming/#meta-non-standard-string-literals) calls them "Nonstandard string literals". But it is syntactic sugar for a macro call:  `md"Blah"`  turns into `@md_str("blah")`.

**Comment by stevengj** [comment]
Closed by #52606
