### ISSUE TITLE
REPL.helpmode has a strange API

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#51179]
The output seems to be split between its return value and the explicitly passed `buf`.
```julia
julia> using REPL

julia> buf = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> eval(REPL.helpmode(buf, "Int"))
  Int64 <: Signed

  64-bit signed integer type.

julia> String(take!(buf))
"search: Int Int8 Int64 Int32 Int16 Int128 Integer intersect intersect!\n\n"
```

**Comment by LilithHafner** [comment]
Update: this is not as bad as I thought it was. It'd still be nice to clean up, but feel free to close if I'm off base.

**Comment by KristofferC** [comment]
Seems to be an internal function and it isn't really clear what needs fixing. So I don't think it needs an open issue, someone can improve it if they feel it is worth it.
