### ISSUE TITLE
Export `Base.tail` and `Base.front`

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#51239]
There are several unexported Base functions that I find very useful, and keep using in my code, with the associated uneasiness of them not being official API. Among these `Base.tail` and `Base.front` are among the most frequent.

This is a suggestion to export `Base.front` and `Base.tail`. The rationale is that they are core to many tuple tasks, for example interation-by-recursion, to avoid the potential type instability of looping over tuples.

Additionally, it would perhaps be good to extend both functions to work also on any collections with the `Base.HasLength()` trait.

**Comment by jishnub** [comment]
These [are documented](https://docs.julialang.org/en/v1/base/collections/#Base.tail), and [should be considered as a part of the API](https://docs.julialang.org/en/v1/manual/faq/#How-does-Julia-define-its-public-API?) even if they aren't exported. Also, an operation like `(t::Tuple)[2:end]` is lowered to `tail(t)` internally for slightly longer tuples, which provides an exported alternative to `tail`.

**Comment by brenhinkeller** [comment]
I guess we can close this as completed given that they are API, but feel free to reopen if the more critical part of the request is the export rather than the API component
