### ISSUE TITLE
`Illegal inttoptr` when using PrecompileTools on HPC

### ISSUE THREAD

**Issue by pat-alt** [JuliaLang/julia#51240]
*This is related to https://github.com/timholy/SnoopCompile.jl/issues/368#issue-1885809139.*

When trying to load a package using `PrecompileTools` on our university's HPC, I get the following error:

```julia
(v1.8) pkg> add "https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl.git"#302-add-precompiletools

[...]

Precompiling project...
  ✗ CounterfactualExplanations
  0 dependencies successfully precompiled in 217 seconds. 379 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

julia> using CounterfactualExplanations
[ Info: Precompiling CounterfactualExplanations [2f13d31b-18db-44c1-bc43-ebaf2cff0be0]
┌ Warning: Package artifacts have been serialized on a different Julia version and may not be compatible with your version.
└ @ CounterfactualExplanations ~/.julia/packages/CounterfactualExplanations/zmii4/src/artifacts_setup.jl:9
Illegal inttoptr
	  %magicptr = ptrtoint {} addrspace(10)* %129 to i64, !dbg !14

signal (6): Aborted
in expression starting at /home/paltmeyer/.julia/packages/CounterfactualExplanations/zmii4/src/precompile.jl:3
```

This happens when trying to use the branch linked to https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/pull/303. Using a version of the same package that doesn't use `PrecompileTools` works without issues. 

@timholy is this right place to open this issue or should I move to `JuliaLang/julia`?

**Comment by KristofferC** [comment]
> is this right place to open this issue or should I move to JuliaLang/julia?

This is more a Julia issue so I moved it.

**Comment by vchuravy** [comment]
What is `versioninfo()` and how did the Julia version get built/installed?

**Comment by pat-alt** [comment]
We are running `1.8.2` on the cluster. It's installed as part of a software stack:

```
02:26:15 paltmeyer@login01 julia-hpc-for-dummies ±|main|→ module spider julia/1.8.2

------------------------------------------------------------------------------------------------------------------------------------------------------
  julia: julia/1.8.2
------------------------------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "julia/1.8.2" module is available to load.

      2023r1
      2023r1-gcc11
      2023rc1
      2023rc1-gcc11
 
    Help:
      The Julia Language: A fresh approach to technical computing
```

I'm not familiar with the details but I could ask our cluster administrator.

Do you need the full stack trace? I didn't post that because I wasn't sure if I might be accidentally sharing sensitive stuff.

**Comment by vtjnash** [comment]
The cluster might be using a non-supported build of Julia, since this bug should be fixed in llvm-13.0.1+3 (https://github.com/JuliaLang/julia/commit/6ba1d23fca0144d937f356af65e945709a98cd8f) in the 1.8 release. Although it looks somewhat like the correct binary name for libLLVM in that stacktrace: llvm-13.0.1-luuedcob23h45ategu2xuvx4frzgch7u/lib/libLLVM-13jl.so

Duplicate of https://github.com/JuliaLang/julia/issues/45702

**Comment by vtjnash** [comment]
looking closer, I see that this was fixed in [Backports for Julia 1.8.6](https://github.com/JuliaLang/julia/pull/48556), and you are only using 1.8.2

**Comment by pat-alt** [comment]
OK, thanks for looking into this!

**Comment by timholy** [comment]
@pat-alt, can you close this when you've verified it's working?

**Comment by pat-alt** [comment]
@timholy yes, will do that as soon as I've had a chance to try in on a newer Julia version on our cluster

**Comment by pat-alt** [comment]
I've installed version `1.9.3` on our cluster and can confirm this works now.
