### ISSUE TITLE
REPL display output bug

### ISSUE THREAD

**Issue by ojwoodford** [JuliaLang/julia#51276]
Using Julia 1.9.3, if you put the following code in an otherwise empty file:
```
x::Int = 1;
# This trailing comment causes a display bug
```
and run that file in the REPL (using your IDE or an include() statement), it will output `1`, the value of `x`. However, since the first line has a semi-colon after it, this shouldn't happen. Removing the comment (and repeating) causes the `1` not to appear, as expected. So there is some bug whereby trailing comments cause the last value to be displayed, irrespective of the semi-colon.

**Comment by vtjnash** [comment]
The `;` suppressing output is only a REPL interactive feature. The `include` function always returns the value of the last statement. If you didn't suppress that, at the REPL, then it shows it.

**Comment by vtjnash** [comment]
Note that the [Discourse forum](http://discourse.julialang.org) may be a better place for getting help on usage questions. It'll be easier to answer your question over there, where there are better controls for message formatting and threading.

**Comment by ojwoodford** [comment]
> The `;` suppressing output is only a REPL interactive feature. The `include` function always returns the value of the last statement. If you didn't suppress that, at the REPL, then it shows it.

This doesn't explain the difference in behaviour with and without the comment. The last value *is* suppressed, without using a semi-colon in the REPL, when there is no comment.

**Comment by ojwoodford** [comment]
> Note that the [Discourse forum](http://discourse.julialang.org) may be a better place for getting help on usage questions. It'll be easier to answer your question over there, where there are better controls for message formatting and threading.

Thanks. I'm aware of the forum, and use it often. I wasn't after help here. I was reporting a bug.

You haven't provided a reason why the comment should change the behaviour. So I still assert it's a bug.

**Comment by rfourquet** [comment]
> Removing the comment (and repeating) causes the 1 not to appear, as expected.

I cannot reproduce this:
```julia
shell> cat /tmp/file.jl
x::Int = 1;

julia> include("/tmp/file.jl")
1
```

**Comment by ojwoodford** [comment]
> I cannot reproduce this

I hadn't tried before, but I can't see the issue in Julia running in a terminal - I see that the output is consistently printed, regardless of the trailing comment (what I now understand is the expected behaviour). Previously I was running the code within VS Code, so this suggests it's not a bug in core Julia, but perhaps in the VS Code Julia extension.

Also, I'm now seeing very weird behaviour where it sometimes happens and sometimes doesn't. So it's like it's a stateful issue. Anyway, I'll close this, and report elsewhere, if I get a reliable MWE. Thanks.
