### ISSUE TITLE
Left-to-right function composition

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaLang/julia#51302]
Hi lovely folks

So, I am thinking about a left to right function composition operator. 
I know, the \circ operator is used in Julia, because it resembles the math operator. 

That's all fine and dandy, and in order to enable other people to use the language just as much, I do think the opposite character could have more of a literal aspect to it. 

FSharp uses >>, which is, sadly, already used for bit shift. 
I personally prefer ligatures to Unicode, again, because I have no math background. 

Ligatures can be typed by about everyone, and they need no fancy \something<tab> completion. 
Which is still a neat thing to have, obviously. 

So drumroll, this is currently what I think could fit fine:

![Screenshot_20230913_175807](https://github.com/JuliaLang/julia/assets/6344099/a8960c90-835f-4fe0-aae3-335fadf1c061)

![Screenshot_20230913_175531](https://github.com/JuliaLang/julia/assets/6344099/8a98d11c-8ac7-4561-b14b-7c3f04f429bb)

It looks like a pipe, and that's a good thing, since they are [very similar](https://spin.atomicobject.com/2021/08/26/fsharp-operators-pipeline-composition/#summary-1).

**Comment by timholy** [comment]
Are you aware of `0.8 |> sin`?

**Comment by ShalokShalom** [comment]
Of the pipe? 
Yes, my last sentence kinda gives it away. :)

**Comment by adienes** [comment]
by the way, you can implement this as your own operator. using, e.g. `⭌` (\rightarrowbsimilar)

```
julia> ⭌(x, y) = y ∘ x
⭌ (generic function with 1 method)

julia> x = [1,2,3,4,5,6,7];

julia> (sum ⭌ sqrt ⭌ inv)(x)
0.1889822365046136

julia> inv(sqrt(sum(x)))
0.1889822365046136
```

**Comment by timholy** [comment]
I guess my question is, are you aware that we already have this?

```julia
help?> |>
search: |>

  |>(x, f)

  Infix operator which applies function f to the argument x. This allows f(g(x)) to be written x |> g |> f. When used
  with anonymous functions, parentheses are typically required around the definition to get the intended chain.

  Examples
  ≡≡≡≡≡≡≡≡

  julia> 4 |> inv
  0.25

  julia> [2, 3, 5] |> sum |> inv
  0.1

  julia> [0 1; 2 3] .|> (x -> x^2) |> sum
  14
```

**Comment by ShalokShalom** [comment]
> I guess my question is, are you aware that we already have this?
> 
> ```julia
> help?> |>
> search: |>
> 
>   |>(x, f)
> 
>   Infix operator which applies function f to the argument x. This allows f(g(x)) to be written x |> g |> f. When used
>   with anonymous functions, parentheses are typically required around the definition to get the intended chain.
> 
>   Examples
>   ≡≡≡≡≡≡≡≡
> 
>   julia> 4 |> inv
>   0.25
> 
>   julia> [2, 3, 5] |> sum |> inv
>   0.1
> 
>   julia> [0 1; 2 3] .|> (x -> x^2) |> sum
>   14
> ```

So there is no difference between a forward pipe operator and a forward function composition?
Isn't the type signature of them different?

Like, I am new to Julia, and programming in general. 

But the pipe takes a value and a function, and returns a function, while composition takes two functions and returns another functions.

**Comment by ShalokShalom** [comment]
I will close this. I would still like to understand, if the pipe and the forward composition have the same semantic value, as suggested. Thanks

**Comment by timholy** [comment]
Ah, I see your point. No, they aren't the same.
