### ISSUE TITLE
Heap snapshots have nonexistent indices

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaLang/julia#51312]
Here's a snippet from a heap snapshot I took using the new `Profile.take_heap_snapshot`.

```
"edges":[0,2,7
,0,3,14
,0,5,21
,0,10242,11104268
,0,10242,11104275
,3,44,5863347
,3,1058,5863340
```

The third number in each row is supposed to be the `to_node` field of an edge (according to https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshot-schema), so it's an index into the nodes array. The number of nodes in this snapshot was

```
"node_count":1586469
```

So `5863347` and `5863340` are invalid indices.
I've also had bounds errors when reading the `strings` array with indices from the `edges` array, in this case that would be the second entry per row. So something seems to be wrong. Chrome viewer doesn't complain but maybe it just hides invalid edges.

**Comment by vchuravy** [comment]
Hm we should always lookup the index https://github.com/JuliaLang/julia/blob/87e31a5d5e054dd2e48fab0c8ce4f7e8f7facce7/src/gc-heap-snapshot.cpp#L454

**Comment by vtjnash** [comment]
The last value is 7*to_node, which seems fine?

**Comment by vtjnash** [comment]
https://github.com/nodejs/node/blob/5fd7a72e1c4fbaf37d3723c4c81dce35c149dc84/deps/v8/src/profiler/heap-snapshot-generator-inl.h#L66-L68

**Comment by jkrumbiegel** [comment]
> The last value is 7*to_node, which seems fine?

Aha so you're saying the index is not that of the node, but really that of the first entry in the raw nodes array. Maybe I just misunderstood this point in the docs. Feel free to close if that's the correct behavior.

**Comment by vtjnash** [comment]
Yes, it is in the index in the raw nodes array, not the index of the node (which differ by a factor of 7)
