### ISSUE TITLE
repl tab complete hints hide existing text

### ISSUE THREAD

**Issue by adienes** [JuliaLang/julia#51323]
I noticed some weird new behavior, presumably caused by https://github.com/JuliaLang/julia/pull/51229, although strictly speaking I did not bisect it.

basically, some existing text is getting hidden when the autocomplete hint tries to go on top of it. MWE:

```
julia> AbstractFloat<ctrl-a>Complex
```

where the `ctrl-a` is only to move the cursor to the front of the input, upon typing `Complex`, the text `AbstractFloat` is hidden

**Comment by mbauman** [comment]
Duplicate of #51320, to be fixed by #51321
