### ISSUE TITLE
The "inv" function returns incorrect inversion on Intel Sapphire Rapids with Julia 1.8.5

### ISSUE THREAD

**Issue by wei3li** [JuliaLang/julia#51330]
Hi Julia team,

I found that the `inv` function returns an incorrect inversion of a square matrix (size >= $10^2$) when running on Intel Sapphire Rapids with Julia 1.8.5. 
```julia
julia> import LinearAlgebra: I

julia> X = rand(10, 10); IX = inv(X);

julia> X * IX ≈ Matrix{eltype(X)}(I, size(X))
false

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e* (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: 208 × Intel(R) Xeon(R) Platinum 8470Q
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, sapphirerapids)
  Threads: 1 on 208 virtual cores
```
If the size of the square matrix is less than $10^2$, then the `inv` returns correct results. The julia I am using was downloaded from julia lang web.
Thanks for investigating this issue!

**Comment by jaakkor2** [comment]
Is it the same with `using MKL`?

**Comment by Seelengrab** [comment]
Does this also happen in the latest release, 1.9.3 or the current nightly?

**Comment by wei3li** [comment]
> Does this also happen in the latest release (1.9.3), one of the 1.10 betas or the current nightly?

No. I also tested on 1.9.3 and 1.10.0-beta2, and these two versions are good.

**Comment by Seelengrab** [comment]
> No. I also tested on 1.9.3 and 1.10.0-beta2, and these two versions are good.

Then it seems there's nothing to do here, as it's already fixed on a newer version.

**Comment by oscardssmith** [comment]
Would probably be good to figure out why this happens to make sure that it won't happen again for new architectures.
