### ISSUE TITLE
Inconsistent `*` for `AbstractMatrix` with `AbstractMatrix`, and `AbstractMatrix` with `Diagonal`, etc.?

### ISSUE THREAD

**Issue by singularitti** [JuliaLang/julia#51354]
In the current `LinearAlgebra` module, [`*` for `AbstractMatrix` with `AbstractMatrix`](https://github.com/JuliaLang/julia/blob/v1.10.0-beta1/stdlib/LinearAlgebra/src/matmul.jl#L104-L107), and [`AbstractMatrix` with `Diagonal`](https://github.com/JuliaLang/julia/blob/v1.10.0-beta1/stdlib/LinearAlgebra/src/diagonal.jl#L288-L289) use different container types:

```julia
function (*)(A::AbstractMatrix, B::AbstractMatrix)
    TS = promote_op(matprod, eltype(A), eltype(B))
    mul!(similar(B, TS, (size(A, 1), size(B, 2))), A, B)
end

(*)(A::AbstractMatrix, D::Diagonal) =
    mul!(similar(A, promote_op(*, eltype(A), eltype(D.diag))), A, D)
```

As you see, the first method uses `B` in `similar`, while the second method uses `A` in `similar`. I could assume that usually with you multiply a diagonal matrix, you want to expand the first matrix, so `A` is used in `similar`. But why is `B` used in the first method? It caused me some problems in [the code I wrote](https://github.com/MineralsCloud/CrystallographyCore.jl):

```julia
julia> using CrystallographyCore

julia> lattice = Lattice(2, 1, 5, 90, 90, 90)
3×3 Lattice{Float64}
 2.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  5.0

julia> b = rand(1:2, 3, 3)
3×3 Matrix{Int64}:
 1  2  2
 2  2  2
 2  1  1

julia> lattice * b
3×3 Matrix{Float64}:
  2.0  4.0  4.0
  2.0  2.0  2.0
 10.0  5.0  5.0

julia> b * lattice
3×3 Lattice{Float64}
 2.0  2.0  10.0
 4.0  2.0  10.0
 4.0  1.0  5.0
```

Where `Lattice` is a subtype of `AbstractMatrix`. As you can see, the left and right multiplications of `Lattice` with another matrix produced different types. Is there a cleverer way to guess the container type of `*`?

**Comment by dkarrasch** [comment]
I'm just guessing, but I think the rationale for choosing the second argument for `similar` was as follows: we think of the first factor as some linear map/operator, that transforms vectors into vectors, hence the transformation of `B` into something `similar` to `B`. Now, when we apply it to a matrix, then that's just like a collection of vectors (the columns). Whenever that choice doesn't work well, we overload `*` and ask it to create a similar array to the first factor `A`. Examples for when the choice doesn't work well include when `similar(B)` would give a dense or sparse array, but we actually want the respective other for the output.
