### ISSUE TITLE
Automatic dedent FTW

### ISSUE THREAD

**Issue by gitfoxi** [JuliaLang/julia#5135]
```
object = 
"""    {
    "hi" : "I'm an object",
    }
"""
println(object)

object = 
"""{
    "hi" : "I'm an object",
    }"""
println(object)
```

```
    {
    "hi" : "I'm an object",
    }

{
"hi" : "I'm an object",
}
```

This seems like a feature I could be friends with if it just introduced itself rather than jumping me in the park while I was walking home drunk.

The rule seems obscure: If you endquote on a line containing something then you get auto-dedent. If you endquote at the beginning of a newline then you don't dedent. Is that it?

To be clear, maybe you want a dedent quote `d"""` and the regular `"""` doesn't dedent. Dedent. It's kind of fun to say. Dedent.

**Comment by ihnorton** [comment]
Comment/re-open if there is a need to revisit this.

**Comment by nolta** [comment]
Why was this closed? AFAICT, this is still undocumented.

**Comment by ihnorton** [comment]
Ok. Can we just document it then and tell people to define their own R_str
macro if they want something else? (I thought there was broad support for
bringing that macro back...)

**Comment by stevengj** [comment]
Certainly we should document it.  Introducing other macros seems like an orthogonal issue that should be debated elsewhere.

**Comment by nolta** [comment]
#13246
