### ISSUE TITLE
Make it easy to manually add workers

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#5136]
When debugging parallel bugs, it's very useful to be able to manually add a worker. 
This kinda works
```
Base.add_workers(PGRP,{Base.Worker("127.0.0.1",9009)})
```
but that is obviously not ideal. Plus, it throws an undefined reference error. A nice  function that abstracts this away would be good.

**Comment by vtjnash** [comment]
I'm pretty sure `addprocs` is doing a good job of this now, since we even essentially use this for our tests (https://github.com/JuliaLang/julia/blob/master/test/runtests.jl#L53)

**Comment by Keno** [comment]
Plus, I'd just use `rr` now ;)

**Comment by amitmurthy** [comment]
I am working on a PR for this anyway. There is a requirement to be able to launch workers independently and just add the launched workers to an already running cluster without calling `addprocs` - comes up when we want the compute resources to be elastic.

**Comment by amitmurthy** [comment]
Ref : An implementation with the cluster manager interface we have today - https://github.com/JuliaParallel/ClusterManagers.jl/pull/40
