### ISSUE TITLE
Typo in `Random.default_rng` doc

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#51373]
There is a typo in [ `Random.default_rng`](https://docs.julialang.org/en/v1/stdlib/Random/#Random.default_rng) doc.

Search for " is is"

**Comment by giordano** [comment]
Not really a typo, "What the default RNG is" is the subject of the "is" verb. If you have any concrete suggestion about how to reword the docstring feel free to open a pull request.

**Comment by prbzrg** [comment]
I just gave the paragraph to [LanguageTool](https://languagetool.org/) and one of the suggestions is:

"The nature of the default RNG is an aspect of the implementation. It is not expected that the default RNG will consistently produce the same stream of random numbers for a given seed across various versions of Julia."
