### ISSUE TITLE
"Edit on GitHub" button on Standard Library pages are broken

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#51372]
It looks like every "Edit on GitHub" button on Standard Library pages are broken.
For example:
on `https://docs.julialang.org/en/v1/stdlib/Logging/`, it goes to `https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.9/Logging/docs/src/index.md`

**Comment by LilithHafner** [comment]
Duplicate of #50035
