### ISSUE TITLE
Julia (segmentation fault) after lu decomposition

### ISSUE THREAD

**Issue by jcbritobr** [JuliaLang/julia#51390]
Got a core dump after reproducing this exercise using lu decomposition

![image](https://github.com/JuliaLang/julia/assets/6579862/0013b006-e49e-4bab-9ff7-e93ec13c2c6b)

julia version - 1.9.3
os = linux fedora 38, x64, 6.4.15-200.fc38.x86_64

**Comment by jcbritobr** [comment]
could not find the dump file. If anyone help to find, I can upload.

**Comment by gbaraldi** [comment]
How did you install julia? and can you post the manifest so we know what packages are you using?

**Comment by jcbritobr** [comment]
Hello. 
Downloaded from julia page and created a symlink to julia executable.
Unfortunatelly, I'm not able to reproduce anymore. Tryed a lot and it doesn't happens.
```
  [6e4b80f9] BenchmarkTools v1.3.2
  [336ed68f] CSV v0.10.11
  [a93c6f00] DataFrames v1.6.1
  [587475ba] Flux v0.14.5
  [7073ff75] IJulia v1.24.2
  [442fdcdd] Measures v0.3.2
  [91a5bcdd] Plots v1.39.0
  [c3e4b0f8] Pluto v0.19.27
  [37e2e46d] LinearAlgebra
```

**Comment by jcbritobr** [comment]
maybe an Issue in Plots.jl?
