### ISSUE TITLE
`LinearAlgebra.QRCompactWYQ` from `qr` has incomplete support for matrix division

### ISSUE THREAD

**Issue by mikmoore** [JuliaLang/julia#51407]
Julia `v1.9.1`.

The Q factor from `qr` has some flexibility in the size of matrix it is multiplied with. Nominally if `Q,R = qr(X)` with `size(X) == (m,n)` then it is permitted to multiply `Q` with a matrix/vector with dimension  `m` *or* `n`.

However, this support breaks down very quickly. Errors currently result from attempts ~~to multiply `Q` by an `Adjoint` or~~ (EDIT: fixed in v1.10) to "divide" it by another matrix when the other matrix has adjoining dimension `!=(m)` (i.e., the "full" dimension of `Q`), even though dimension `n` should be accepted.
```julia
julia> using LinearAlgebra

julia> X = Float64[1;2;3;; 4; 5; 6;]
3×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
 3.0  6.0

julia> Q,R = qr(X)
LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.267261   0.872872   0.408248
 -0.534522   0.218218  -0.816497
 -0.801784  -0.436436   0.408248
R factor:
2×2 Matrix{Float64}:
 -3.74166  -8.55236
  0.0       1.96396

julia> Q*X
3×2 Matrix{Float64}:
  2.70323   5.7448
 -2.54758  -5.94598
 -0.44991  -2.93982

julia> Q*collect(X')
3×3 Matrix{Float64}:
  3.22423    3.82984     4.43545
  0.338349   0.0220445  -0.29426
 -2.54753   -3.78575    -5.02397

julia> Q*X' # worked when Adjoint was collected, but not raw -- EDIT: fixed v1.10
ERROR: DimensionMismatch: first dimensions of C, 2, and V, 3 must match
Stacktrace:
 [1] gemqrt!(side::Char, trans::Char, V::Matrix{Float64}, T::Matrix{Float64}, C::Matrix{Float64})
   @ LinearAlgebra.LAPACK ~/julia-1.9.1/share/julia/stdlib/v1.9/LinearAlgebra/src/lapack.jl:2916
 [2] lmul!
   @ ~/julia-1.9.1/share/julia/stdlib/v1.9/LinearAlgebra/src/qr.jl:626 [inlined]
 [3] *(Q::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, adjB::Adjoint{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/julia-1.9.1/share/julia/stdlib/v1.9/LinearAlgebra/src/qr.jl:735
 [4] top-level scope
   @ REPL[157]:1

julia> Q/R # but Q*R works (obviously), as does Q*inv(R)
ERROR: DimensionMismatch: Both inputs should have the same number of columns
Stacktrace:
 [1] /(A::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, B::Matrix{Float64})
   @ LinearAlgebra ~/julia-1.9.1/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:1146
 [2] top-level scope
   @ REPL[158]:1
```
A current workaround is to slice `Q` to the appropriate dimension (manually) prior to the unsupported operation. It seems that this fix could be applied generally, although I have not yet explored how many methods may require fixing.

This came up when I was attempting to use `R\Q'` to compute `pinv(X)` for `m>n==rank(X)`, since `pinv` uses `svd` which has poor support for general element types (such as `ForwardDiff.Dual`).

**Comment by dkarrasch** [comment]
This is what I get on v1.10.0-beta2, which includes the `AbstractQ` overhaul:

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.0-beta2 (2023-08-17)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using LinearAlgebra

julia> X = Float64[1;2;3;; 4; 5; 6;]
3×2 Matrix{Float64}:
 1.0  4.0
 2.0  5.0
 3.0  6.0

julia> Q,R = qr(X)
LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
2×2 Matrix{Float64}:
 -3.74166  -8.55236
  0.0       1.96396

julia> Q*X
3×2 Matrix{Float64}:
  2.70323   5.7448
 -2.54758  -5.94598
 -0.44991  -2.93982

julia> Q*collect(X')
3×3 Matrix{Float64}:
  3.22423    3.82984     4.43545
  0.338349   0.0220445  -0.29426
 -2.54753   -3.78575    -5.02397

julia> Q*X' # worked when Adjoint was collected, but not raw
3×3 Matrix{Float64}:
  3.22423    3.82984     4.43545
  0.338349   0.0220445  -0.29426
 -2.54753   -3.78575    -5.02397

julia> Q/R # but Q*R works (obviously), as does Q*inv(R)
ERROR: MethodError: no method matching /(::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}, ::Matrix{Float64})

Closest candidates are:
  /(::Adjoint{T, <:AbstractVector} where T, ::AbstractMatrix)
   @ LinearAlgebra /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/adjtrans.jl:491
  /(::Transpose{T, <:AbstractVector} where T, ::AbstractMatrix)
   @ LinearAlgebra /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/adjtrans.jl:492
  /(::AbstractVecOrMat, ::AbstractVecOrMat)
   @ LinearAlgebra /Applications/Julia-1.10.app/Contents/Resources/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/generic.jl:1154
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

Arguably, the last call is problematic, because you want to solve (from the right) some linear operator that is not given in its matrix representation. This, however, works

```julia
julia> Matrix(Q)/R # but Q*R works (obviously), as does Q*inv(R)
3×2 Matrix{Float64}:
 0.0714286  0.755491
 0.142857   0.733204
 0.214286   0.710917
```

**Comment by mikmoore** [comment]
I would contend that the representation of `Q` is an implementation detail. It prints as a matrix and even subtypes `AbstractMatrix`. The arcane type signature is the only hint most users have that it isn't a literal matrix. Further,
```julia
help?> /

search: / //

/(x, y)

Right division operator: multiplication of x by the inverse of y on the right. Gives floating-point results for
integer arguments.       
```
so it would seem bizarre that `Q/R` would error when `Q*inv(R)` is totally acceptable. The fact that is algorithmically necessary (or at least convenient) to collect `Q` before running it through the "numerator" of `/` isn't relevant to the syntactical use.

I'll also add that the choice of `Matrix(Q)` to return the rectangular version is an interesting one. I won't say it's the wrong choice, and obviously it works out in this example, but it means that operations like `inv(Matrix(Q))` fails.


One last check for `v1.10`: does the following work? This is what I get on `v1.7` (sorry, I've got an old setup in front of me)
```julia
julia> R/Q
ERROR: DimensionMismatch("Both inputs should have the same number of columns")
Stacktrace:
 [1] /(A::Matrix{Float64}, B::LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}})
   @ LinearAlgebra ~/julia-1.7.0/share/julia/stdlib/v1.7/LinearAlgebra/src/generic.jl:1149
 [2] top-level scope
   @ REPL[26]:1
```

**Comment by dkarrasch** [comment]
> It prints as a matrix and even subtypes `AbstractMatrix`.

That is no longer true on v1.10. The subtyping was removed in the `AbstractQ` overhaul I mentioned.

> does the following work?

Yes, any solve with `Q` is translated to multiplication with `Q'`. That was added in v1.10 in the same PR.

```julia
julia> R/Q
2×3 Matrix{Float64}:
 -6.46511  0.133722   6.73256
  1.71429  0.428571  -0.857143
```

> but it means that operations like `inv(Matrix(Q))` fails.

That's right, however,

```julia
julia> Matrix(inv(Q))
3×3 Matrix{Float64}:
 -0.267261  -0.534522  -0.801784
  0.872872   0.218218  -0.436436
  0.408248  -0.816497   0.408248
```

works, and is presumably much faster than `inv(Matrix(Q))` even when `Matrix(Q)` is square since the `inv` translates to `Q'` for which we have a direct matrix represenation creation routine (basically `Q' * I`).

As for `Q/R`, we could make it work by checking dimensions and then picking the right one if possible, materialize as a matrix and then solve, if we wanted to. That would be a new feature.

**Comment by mikmoore** [comment]
Oh. I had assumed that changing `AbstractQ`'s place in the type hierarchy would be breaking so didn't imagine it happened. But I guess it was considered minor enough they let it through?

Anyway, it seems the issues I raised are addressed except for `AbstractQ` in the "numerator" position of `/` and `\`. As you say, all this would require would be to materialize `Q` to the appropriate size  and then call the matrix version.

**Comment by dkarrasch** [comment]
Well, it's technically breaking, of course. But as you see, there's now even more of "reasonable" functionality (by that I mean functionality that doesn't treat a `Q` like a table of numbers). What is gone are many fallbacks for functionality that is (a) probably not used anywhere and/or (b) prohibitively slow. Think of "silly" things like

```julia
julia> using LinearAlgebra

julia> Q = qr(randn(5,5)).Q
5×5 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}}:
 -0.52493   -0.636115   0.302211    0.219059    0.424838
  0.602485  -0.50832    0.0394299   0.52641    -0.316166
 -0.56528   -0.140444  -0.229299    0.0616136  -0.777406
  0.120749  -0.13923    0.761411   -0.527289   -0.329021
  0.165345  -0.545764  -0.524203   -0.626957    0.0832943

julia> tril(Q)
5×5 Matrix{Float64}:
 -0.52493    0.0        0.0        0.0       0.0
  0.602485  -0.50832    0.0        0.0       0.0
 -0.56528   -0.140444  -0.229299   0.0       0.0
  0.120749  -0.13923    0.761411  -0.527289  0.0
  0.165345  -0.545764  -0.524203  -0.626957  0.0832943
```

That used to be possible (the above is v1.6.7), but very very slow due to elementwise access, where each `getindex` runs a nontrivial program in the background.

Back to the original issue: do you think the division issue requires a generic fix in LinearAlgebra, or could you replace it in your code with `Matrix(Q)` (potentially thin) or `collect(Q)` (always square)?

**Comment by mikmoore** [comment]
Obviously, in my code I can (and did) make the requisite intermediate call. 

But I still don't see how
> Arguably, the last call is problematic, because you want to solve (from the right) some linear operator that is not given in its matrix representation.

It doesn't seem problematic from any perspective but a literal implementation perspective. It's not in a `Matrix` representation, but it does represent a matrix. We support `UniformScaling(1)/R` but `UniformScaling` is not a matrix representation either. The fact that `qr` returns a `QRCompactWYQ` is an implementation detail (which would be breaking to change and the alternatives would be inferior, but that's irrelevant to this discussion). For example, MATLAB has an identical syntax but returns an actual matrix for `Q` meaning that all of these solve would work (assuming compatible dimensions).

In my assessment, the operation is not ambiguous or a pun, nor is it esoteric. The reasons to take a `qr` decomposition are to either use it directly to "solve" a rectangular system (which does not require accessing `Q` at all - the factorization object is sufficient) or to extract the factors for further algebra (like `R\Q'` to compute the pseudoinverse of a matrix with full column rank).

**Comment by dkarrasch** [comment]
My personal view is that there is a distinction between matrices and linear maps/operators. For me, the latter are meant to act on vectors and matrices, but are not supposed to be acted on by matrices. For instance, suppose your `Q` was an FFT or any other linear transform(ation), which has a matrix representation. Would you argue as well that we should have `FFT / R` or `A \ FFT`? Is it just an implementation detail that the FFT is actually an algorithm which happens to be representable as a matrix? Personally, I believe that `AbstractQ`s are closer to FFTs than to matrices, and that the fact that they can be represented by matrices is something that should be put on the user, like "if you want to treat it as a matrix, turn it into a matrix yourself explicitly". But as I said above, we may still decide to take it on us/`LinearAlgebra` to do that for the user.
