### ISSUE TITLE
code_warntype is wrong if Julia chooses to not specialize

### ISSUE THREAD

**Issue by abraemer** [JuliaLang/julia#51415]
There was just a discussion on [discourse](https://discourse.julialang.org/t/performance-issue-due-to-function-as-an-argument/104093) where performance of a function was very bad because the user hit a special case where Julia [does not specialize on function arguments](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing). The user tried using `@code_warntype` but it showed no problems.

The issue here is that `@code_warntype` apparently forces specialization and thus is plainly wrong when you hit such a specialization special case. I think at least, we should add a short warning with reference to the [relevant section of the Performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing) to the docstring of `code_warntype` to give users a better chance of discovering this themselves. Even better would be of course to make `code_warntype`/`@code_warntype` smarter but that's probably not easy.

Here is a minimal working example showcasing the problem:
```julia
# Julia version 1.9.3
using BenchmarkTools

# the test function to be used as argument, return a Vector{Float64} of length 10
f(x) = rand(10) .* x

# won't specialize on f since f is not called directly
function g(f, N)
    # expects f to return a vector of fixed length
    values = map(f, 1:N)
    # now we need to do some operations on values to show the type instability
    cnt = zero(eltype(values[1]))
    for v1 in values
        for v2 in values
            for j in eachindex(v2)
                cnt += v1[j]*v2[j]
            end
        end
    end
    return cnt
end

# will specialize on f
function g_specialized(f::F, N) where F
    values = map(f, 1:N)
    cnt = zero(eltype(values[1]))
    for v1 in values
        for v2 in values
            for j in eachindex(v2)
                cnt += v1[j]*v2[j]
            end
        end
    end
    return cnt
end

@btime g($f, 10) # 100.016 μs (5024 allocations: 95.22 KiB)
@btime g_specialized($f, 10) # 2.918 μs (21 allocations: 2.94 KiB)
# @code_warntype g(f,10) is identical to @code_warntype g_specialized(f, 10)
```
I think this example is not too far off from actual code that users might write (see discourse thread above) and there are no good tools to diagnose. I also tried `Cthulhu.jl`'s `@descend` but this also did not show differences between the functions for me. The underlying issue for me here is that the rules when Julia chooses to *not* specialize are quite obscure and the workaround is very hacky: 
> Julia usually specializes on all arguments *except* for Function, Type and VarArg, *except* if that argument is used directly. If you don’t want that then you need to put a type-declaration, which is otherwise only used for dispatch reasons and never for performance reasons.

Conceptually it would be much simpler to have a clear:
> Julia always specializes. If you don't want that, use `@nospecialize`. This is only an advanced optimization.

Or does `@nospecialize` something subtly different then Julia deciding to not specialize? I suppose it is too late to change this specialization behavior so we should aim at improving the diagnostic tools. Perhaps starting with more explicite warnings in the docstrings. What do you think?

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/32834
