### ISSUE TITLE
Incorrect sentence in "Function composition and piping" section of manual

### ISSUE THREAD

**Issue by gareth-j** [JuliaLang/julia#51442]
In the "[Function composition and piping](https://docs.julialang.org/en/v1/manual/functions/#Function-composition-and-piping)" section of the manual the sentence:

"When combining pipes with anonymous functions, parentheses must be used if subsequent pipes are not to parsed as part of the anonymous function's body." doesn't read correctly. Should it be either

"When combining pipes with anonymous functions, parentheses must be used if subsequent pipes are not to be parsed as part of the anonymous function's body."

or 

"When combining pipes with anonymous functions, parentheses must be used if subsequent pipes are not parsed as part of the anonymous function's body."

**Comment by Arka2708** [comment]
hey @ViralBShah can you assign me this issue under hacktoberfest? I want to solve it...

**Comment by christiangnrd** [comment]
This was fixed in #47875. It'll show up in the docs once 1.10 is released.
