### ISSUE TITLE
Crash on windows when calling out to juliaup

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaLang/julia#51461]
~I'm not sure whether to blame this crash on julia or juliaup or a combination, but let's start here.~
This seems likely to be a Windows bug with programs installed from Windows store but it would be good if Julia can work around it.

# Reproducer

This assumes juliaup, from Windows store, and git (not from Windows store) are installed. As discussed later neither juliaup nor git are critical.

1. Start a Cmd window.
2. In the Cmd, start julia.
3. In julia, run
```julia
run(`juliaup --version`)
run(`git --version`)
```

## Crash

```
julia> run(`juliaup --version`)
Juliaup 1.8.16
Process(`juliaup --version`, ProcessExited(0))

julia> run(`git --version`)
AssignProcessToJobObject: (87) The parameter is incorrect.

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_BREAKPOINT at 0x7ff8adf3b502 -- DebugBreak at C:\WINDOWS\System32\KERNELBASE.dll (unknown line)
in expression starting at REPL[2]:1
DebugBreak at C:\WINDOWS\System32\KERNELBASE.dll (unknown line)
Allocations: 2998 (Pool: 2986; Big: 12); GC: 0

C:\Users\GunnarF>git version 2.14.3.windows.1

C:\Users\GunnarF>
```

# Analysis
1. Replacing the call to `git` with e.g. `cmd /c dir` or `ping` also crashes.
2. Replacing juliaup with another program installed from Windows store, e.g. `winget`, also crashes.
3. If juliaup is installed with a non-store installer, it doesn't crash.
4. Different versions of Julia all crash. Tested with Julia 1.6 and 1.9 installed from juliaup and 1.9 from a binary download.
5. Replacing Cmd with Powershell also crashes.
6. Replacing Cmd with Git Bash or starting Julia directly from Windows do *not* crash.
7. Running this via a bat file does crash (this is the case that really matters to me).
8. Calling juliaup multiple times, followed by git, crashes, but not until calling git.
9. Effective workaround: This sequence does *not* crash:
```julia
run(`git --version`)
run(`juliaup --version`)
run(`git --version`)
```
10. Calling out from a Python started in a Cmd does *not* crash:
```python
import subprocess
subprocess.run(["juliaup", "--version"])
subprocess.run(["git", "--version"])
```

**Comment by vtjnash** [comment]
Seems to be a problem other people have reported, but not gotten any response on such as https://github.com/microsoft/pylance-release/issues/1118. The first object here is a Windows Store app, and it seems like that corrupts the Job object in the kernel in some way so that it fails on future uses.

**Comment by GunnarFarneback** [comment]
Good point. I've tried with a non-store install of juliaup and then it doesn't crash while it does crash if I replace juliaup with another store app (`winget --version`). I'll update the description to include this.

Anyhow, even if this is a Windows bug, it seems likely that people will run into it again from time to time, so it would be good to work around the bug. Somehow Python avoids the crash but maybe `subprocess.run` isn't quite as equivalent as it naively looks.

**Comment by vtjnash** [comment]
Most programs don't set up job control to match the unix behavior. The reason might be this restriction in the documentation:

> Terminal Services:  All processes within a job must run within the same session as the job.

But anyways, despite probably being a kernel bug of some sort, we can work around it: https://github.com/libuv/libuv/pull/4152
