### ISSUE TITLE
Errorshow tests fail on latest master

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#51465]
~https://github.com/JuliaLang/julia/pull/49235 seems to have broken the errorshow tests~

https://buildkite.com/julialang/julia-master/builds/28093#018ad03b-da9f-45cd-aa05-47b5f15a0d20 

@aviatesk mentioned that it might be https://github.com/JuliaLang/julia/commit/32205658a5366a4e3e08f66f4e73402f4ebb323f

**Comment by JeffBezanson** [comment]
I don't see how that could cause it. After some careful bisecting (you have to rebuild everything and retry a couple times, because it's a bit variable) I think it's 6bb9111589e79c3d7c12ee4749add7142c0c6d8e, a libunwind upgrade. That definitely matches the symptom. Looks like they broke something...

**Comment by vtjnash** [comment]
There is an rr trace for it linked from https://github.com/JuliaLang/julia/issues/51521

**Comment by maleadt** [comment]
> After some careful bisecting (you have to rebuild everything and retry a couple times, because it's a bit variable) I think it's [6bb9111](https://github.com/JuliaLang/julia/commit/6bb9111589e79c3d7c12ee4749add7142c0c6d8e), a libunwind upgrade.

What's the exact reproducer you used, just the `errorshow` tests? I can try to figure out which libunwind change caused the regression, as I did for https://github.com/JuliaLang/julia/issues/51467.

**Comment by JeffBezanson** [comment]
I ran
```
julia> let
           f28442(c) = g28442(c + 1)
           g28442(c) = c > 10000 ? (return backtrace()) : f28442(c+1)
           bt = f28442(1)
           io = IOBuffer()
           Base.show_backtrace(io, bt)
           output = split(String(take!(io)), '\n')
           display(output)
       end
```
If that has more than 10000 frames it's good.

**Comment by maleadt** [comment]
Also bisected to https://github.com/libunwind/libunwind/pull/203, looks like that PR broke more platforms than just FreeBSD.

I'll extend the patch revert we already do for FreeBSD to all platforms.
