### ISSUE TITLE
Progress output while precompiling is flickering badly

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#51462]
With the development version of Julia (built on macOS, using iTerm as terminal), the progress output flickers badly. This used to be much better.

Here is some example output:
```
[2913bbd2] ↑ StatsBase v0.34.0 ⇒ v0.34.2
Precompiling project...
  Progress [========================================>]  317/321
  ✗ MakieCore
  ✗ Polynomials → PolynomialsMakieCoreExt
  ✓ Netpbm
  ◐ ImageIO
```

It seems that the list of packages is output repeatedly, maybe once or a few times per second, and the screen is cleared in between. This flickers a lot on my screen.

I don't know what changed in the mean time. Maybe the output algorithm was change from "write a line, then clear to the end of the line" to "clear to the end of the screen, then output all packages anew"?

**Comment by vchuravy** [comment]
@IanButterworth is this the same issue you showed me the other day?

The likely change is that Pkg is no longer in the sysimg #51189

**Comment by KristofferC** [comment]
Should be fixed by https://github.com/JuliaLang/Pkg.jl/pull/3631
