### ISSUE TITLE
factorial(big(-1)) falsely evaluates to 0 instead of raising error

### ISSUE THREAD

**Issue by mauricelanghinrichs** [JuliaLang/julia#51488]
I noticed the following behaviour when computing the ```factorial``` of negative integers (e.g., ```-1```): While ```factorial(-1)``` raises a domain error (as also python would do), computing this in high precision by ```factorial(big(-1))``` evaluates to ```0```. 

I previously posted this as a question on discourse; please see [there](https://discourse.julialang.org/t/factorial-big-1-0-bug-or-expected-behaviour/104298) for more. The current implementation seems intentional, but it seems like a bug and ```factorial(big(x))``` for negative integer ```x``` should instead raise the same domain error.

```
julia> factorial(-1)
ERROR: DomainError with -1:
`n` must not be negative.
Stacktrace:
 [1] factorial_lookup
   @ ./combinatorics.jl:18 [inlined]
 [2] factorial(n::Int64)
   @ Base ./combinatorics.jl:27
 [3] top-level scope
   @ REPL[4]:1

julia> factorial(big(-1))
0

julia> factorial(big(-5))
0
```

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 20 × Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 10 on 20 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 10
  DYLD_FALLBACK_LIBRARY_PATH = [...]
```

**Comment by roflmaostc** [comment]
The factorial function for various Ints is defined [here](https://github.com/JuliaLang/julia/blob/50146b2dd27e8f3bc54367427a70cd96f74ada45/base/combinatorics.jl#L18).

So I think the problematic line for `BigInt` is [that](https://github.com/JuliaLang/julia/blob/50146b2dd27e8f3bc54367427a70cd96f74ada45/base/gmp.jl#L708).

We would need to add another branch, am I correct?

**Comment by albheim** [comment]
Wouldn't it be to simply skip the `BigInt(0)` branch for negative values and instead do `throw(DomainError(x, "argument must not be negative."))` there?

I tried to trace it back, and the first occurrence in Julia code I could find was from https://github.com/JuliaLang/julia/commit/f8ba2141c8889d619e57b92e3978d90ebc69d168, but didn't really find a motivation for the zero. Though it seems to have existed before that but maybe through external libraries then? I assume that GMP/MFPR does not return zero for negative values, so something introduced by julia?

**Comment by stevengj** [comment]
It looks like this is a bug introduced by the notorious @JeffBezanson in https://github.com/JuliaLang/julia/commit/5f7529b57393be470da2303b96b752f407e49560 — in that commit (way back in 2014), the `factorial(::Integer)` function was changed to throw a `DomainError` for negative arguments, but need to also change the `::BigInt` method was apparently overlooked.
