### ISSUE TITLE
Inner functions allocate

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#51511]
I had an inner helper function (for factorial) that allocates, even in tail position. I'm not sure why, since the code worked function when moved out to no longer be nested.

Is it a bug in Julia? I fail to see the need for allocation (except on the stack, and even not needed then with TCO macro). Is it maybe needed when not in tail position?

Fixing this might help against Mojo... though I think it's winning there because it has TCO my default.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/15276? Anyway, needs some kind of reproducer to do anything about.
