### ISSUE TITLE
Is there a policy about backporting new functions to LTS?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#51534]
I did see for new Libc.mkfifo for 1.11, not 1.10:

https://github.com/JuliaLang/julia/pull/34587/files

>* The new `Libc.mkfifo` function wraps the `mkfifo` C function on Unix platforms ([#34587]).
>* `hardlink(src, dst)` can be used to create hard links. ([#41639])
>* `diskstat(path=pwd())` can be used to return statistics about the disk. ([#42248])

hardlink would also be helpful for 1.10 (or 1.6) LTS. I'm not sure why it was there in the NEWS, since it was seemingly added in 1.8.

People have done without Libc.mkfifo for a long time, so maybe it doesn't need to be backported, but it's still useful, and I don't see a reason to now backport it to 1.10. It's very localized and shouldn't accidentally break previous stuff.

1.10 is not yet LTS, I'm just thinking, in case if were so already about if allowed. Is there a (documented) policy (for or) against, forbidding backporting?

**Comment by oscardssmith** [comment]
In general, we don't backport features unless we have a really good reason to.

**Comment by PallHaraldsson** [comment]
Yes, I thought so. Why I think backporting Libc.mkfifo soon to 1.10 would be wise before it gets to be an LTS. I however don't see a huge reason to not allow backporting selectively after LTS. I'm asking to know how urgent backporting is, in case we have a policy against backporting to LTSes.
