### ISSUE TITLE
fix: Language Errors in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Agnik7** [JuliaLang/julia#51556]
There are various typographical and grammatical mistakes in the CONTRIBUTING.md file, which can be fixed for better engagement and communication.

Attaching some screenshots:

![Julia1](https://github.com/JuliaLang/julia/assets/77234005/3a8983b6-4be6-4df6-8d06-5639873295dd)
![Julia2](https://github.com/JuliaLang/julia/assets/77234005/e7f1ed2c-9de4-4816-8285-8f1f3260ac4d)

**Comment by Agnik7** [comment]
Requesting the maintainers of the repository to assign me this issue and kindly add the required labels to it. Apologies for any inconvenience caused.

**Comment by jishnub** [comment]
Hi, you may open a PR with the issues fixed, there's no need to assign it to you. Thanks for looking into this!

**Comment by Agnik7** [comment]
Alright, working on it right away!
