### ISSUE TITLE
`lstrip` could be more efficient: `enumerate` vs `pairs`

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/julia#51624]
If I replace `pairs` here
https://github.com/JuliaLang/julia/blob/6fc6a97d1dbc7b7c6172b26afb28e845c8888c8e/base/strings/util.jl#L363-L369

with enumerate, I find `lstrip` is almost twice as fast for some `String` and `SubString`.

This should probably be investigated more broadly. That is for other uses of `pairs` at least in `Base`. Maybe another method just for `String` and `Substring` (or a trait to be more thorough, but complicated)

Or try to fix whatever is slowing down `pairs`.

In retrospect (too late now) `pairs` could still call `keys` and `values`, but just construct `Tuple`s. Or was `struct Pair` really needed?

### Example

```julia
julia> a = lpad("March", 20);

julia> @btime lstrip2($a)  #  use `enumerate`
  24.901 ns (0 allocations: 0 bytes)
"March"

julia> @btime lstrip($a)
  51.897 ns (0 allocations: 0 bytes)
"March"
```

### Version
Versions v1.6, v1.9, v1.11

**Comment by jakobnissen** [comment]
```julia
julia> lstrip2(==('α'), "αβ")
ERROR: StringIndexError: invalid index [2], valid nearby indices [1]=>'α', [3]=>'β'
```
You need `pairs` and not `enumerate`, because you need to find valid indices.
That being said, it looks like `pairs` is not specialized for `AbstractString`, meaning that both the key and the value iterator will find the valid indices. So, there is room for optimization.

**Comment by jlapeyre** [comment]
This is still almost twice as fast:
```julia
function lstrip2(f, s::AbstractString)
    f === identity && isascii(s) && return lstrip(f, s)
    e = lastindex(s)
    for (i::Int, c::AbstractChar) in enumerate(s)
        !f(c) && return @inbounds SubString(s, i, e)
    end
    SubString(s, e+1, e)
end
```

**Comment by jakobnissen** [comment]
That implementation is O(N), which I don't think is a good idea.
I think the real solution here is to implement a specialized `StringPairs{T <: AbstractString}`. This likely won't be any better for generic `AbstractString`, but for the built-in string type, it could use string iteration internals to be significantly faster.
I'll try to see if I can pitch an implementation the next few days.

**Comment by jlapeyre** [comment]
> That implementation is `O(N)`

Right, that's no good.
