### ISSUE TITLE
The function one(Irrational) returns true instead of 1.0

### ISSUE THREAD

**Issue by mohamed-180** [JuliaLang/julia#51634]
```
julia> one(Real)
# 1

julia> one(AbstractFloat)
# 1.0

julia> one(Irrational)
# true

julia> one(AbstractIrrational)
# true
```

**Comment by jakobnissen** [comment]
This is correct behavior - true is an integer that represents 1, and can be promoted to all other number types. It's thus the most basic  and universal representation of 1.
