### ISSUE TITLE
Disable startup.jl (for non-interactive use)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#51649]
I've brought this up before, and then @KristofferC objected, with this a breaking change. I'm not sure if his PackageCompiler.jl defaults to run the file, the same as Julia's (current) default, but IMHO it shouldn't for reproducability, neither should Julia's scripts.

Now with the new `@main` macro it seems to me nothing is changed, but it seeming could be in a non-breaking way.

Python sensibly doesn't have a startupfile (or seemingly, its PYTHONSTARTUP ENV is only for running a file when interactive).

There doesn't seem much upside to run the file (except for interactive), and those who want it (for scripts too) could opt into it with the CLI option.

I would be perfectly fine with changing, and documenting the change, for all scripts, not just if using `@main`.

https://github.com/JuliaLang/julia/blame/ecaf457f883abb1fd83697551c119af7a570cd18/base/client.jl#L275

https://github.com/JuliaLang/julia/pull/51435#issuecomment-1754785645

People are already hesitant to change from Julia's default here: https://github.com/JuliaPy/PythonCall.jl/issues/376#issuecomment-1754694203

**Comment by jakobnissen** [comment]
See also: https://github.com/JuliaLang/julia/issues/42205

**Comment by PallHaraldsson** [comment]
About @Keno's comment:
>The startup.jl thing will need to be an option to the compiler. It doesn't make sense on the @main macro which needs to have semantics for both interactive and compiled uses cases and for the interactive one, it comes too late to load startup.jl.

[Actually the macro can be the same for interactive or not(?). It would just have to generate unconditional call to code, that is then conditional to if used in the REPL/interactively. See also on this below.]

If it's an (non-default) option to the PackageCompiler.jlm you mean (what I assume Keno meant by "compiler") then that is problematic, since many will not read docs and think of it, so may miss it. I argue it's not useful for anyone to get an app from the web that works, until someone installs Julia, and maybe messes with the file, possibly makes a typo, then "obvious" error to some, or not a typo and changes the behaviour of their app, maybe even worse of a possibility. Even a security issue (also for scripts, really).

If the default for compiled apps is do not respect the file, then a script run from the shell has different behaviour after it's compiled into an app, bad, even many possible different. So I argue for the default for script be changed (too), people can always opt into the old default of running the file with CLI option.

In what situations is the file useful (for non-interactive)? I know of e.g. abbreviated stack-traces package, non-essential (and Revise.jl), useful for the REPL. If better stack-traces are needed, then they should be the default Julia and/or controlable with an ENV var.

It occurred to me after asking Keno, that if you start with and run the file, then it's too late by the time the macro is seen, you can undo running code (not strictly always true, there's rr...).

It seems very ugly, and not needed, but could the startup.jl file be run after reading and _parsing_ the first file, i.e. the script (if it doesn't contain the macro) ? Then you would lose out on the logic of it, e.g. if it adds abbreviated stack-traces, hopefully not needed for the first file, but at least enabled a little later...

**Comment by Keno** [comment]
I think I agree it would probably be better if startup.jl was interactive only, but I also agree that we can't change it at this point. However, we could certainly add a `repl_startup.jl` file and encourage people to use that instead.

**Comment by IanButterworth** [comment]
Or put things you only want in the repl behind `isinteractive()`

**Comment by IanButterworth** [comment]
Btw, duplicate of https://github.com/JuliaLang/julia/issues/35932
