### ISSUE TITLE
pwd() error on call in REPL, WSL Ubuntu

### ISSUE THREAD

**Issue by OscarRoussel** [JuliaLang/julia#51663]
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores

My install : 
Fresh windows install.
Enabled WSL + Ubuntu 22.04.2.
Downloaded the tar.gz through https://julialang.org/downloads/
Uncompressed the tar in a folder on the virtual ubuntu.
Added julia to path.

Getting error `MethodError: objects of type String are not callable` when calling pwd() in the first instance of WSL opened and the first REPL opened.
Error goes away when opening a new ubuntu terminal.

MWE : WSL+Ubuntu, julia in that Ubuntu, call pwd() in REPL

**Comment by Seelengrab** [comment]
Have you assigned the variable `pwd` before trying to call the function?

**Comment by OscarRoussel** [comment]
Might have! That makes sense now!
