### ISSUE TITLE
Packages should never load one of their own extensions "into themselves".

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#51662]
If a package (possibly by accident) has all of the triggers for an extension in its set of transitive dependencies the extension will be loaded when the package precompiles.

This is effectively a cyclic graph since the extension depends on the parent and the parent now "depends" on the extension.

To solve this a package should never load one of its own extensions while it is getting precompiled.

**Comment by IanButterworth** [comment]
My understanding is that this would cause a precompilation process to hang but not create the timer warnings. Is that right?

**Comment by KristofferC** [comment]
I think I slightly misdiagnosed this based on some other issue where two extensions where blocking each other from continuing. What I wrote in the OP cannot really be true since "extension triggers" (the thing that loads the extension once all its triggers are loaded) are not inserted for the package getting precompiled.

Looking at the code, the extension triggers are inserted as part of `require`:

https://github.com/JuliaLang/julia/blob/4d36da7768ea403284cb7364366a941cfba40642/base/loading.jl#L1860-L1868

but when precompiling a package, we never call `require` on it. Instead we just `include` it:

https://github.com/JuliaLang/julia/blob/4d36da7768ea403284cb7364366a941cfba40642/base/loading.jl#L2302

**Comment by KristofferC** [comment]
I am going to close this since the whole issue seems to be faulty. There seems to still be an issue where to extension can block each others progress but it isn't due to this.

@vtjnash
