### ISSUE TITLE
Loader fails to build on MSYS2 (mingw-w64-x86_64) due to compiler-generated memset

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#51680]
In our loader, we have an array initialization that the compiler likes to perform using `memset`: https://github.com/JuliaLang/julia/blob/e949236f29347f3e57a1a3a7d5ec656872ad8347/cli/loader_lib.c#L63

That's not OK, as our loader is compiled without the C standard library. IIUC, that's why we compile with `-ffreestanding`: https://github.com/JuliaLang/julia/blob/e949236f29347f3e57a1a3a7d5ec656872ad8347/cli/Makefile#L10-L11

However, it looks like MSYS2's mingw compiler (GCC 13.2) ignores this:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./loader_lib.o: in function `load_library':
C:/Users/Tim/Julia/src/julia/cli/loader_lib.c:63:(.text.startup+0x25): undefined reference to `memset'
collect2.exe: error: ld returned 1 exit status
make: *** [/c/Users/Tim/Julia/src/julia/cli/Makefile:118: /c/Users/Tim/Julia/src/julia/build/usr/bin/libjulia.dll] Error 1
```

I tried a variety of other flags I got from https://github.com/riscv-collab/riscv-gnu-toolchain/issues/758, e.g., `-fno-lto` and `-fno-builtin`, to no avail.

EDIT: looks like `memset` etc are expected to be available, even with `-ffreestanding`:

> GCC requires the freestanding environment provide memcpy, memmove, memset and memcmp.

Workaround:

```c
char path[2*JL_PATH_MAX + 1] /*= {0}*/;
for (int i = 0; i < 2*JL_PATH_MAX + 1; i++)
    path[i] = 0;
```

**Comment by gbaraldi** [comment]
This is not unexpected, we define our own memcpy in https://github.com/julialang/julia/blob/62e57f70e0932b569a930a8110db6306f1dd85c3/cli/loader_win_utils.c#L174-L179, so I imagine we have to do the same thing. GCC and Clang both assume that mem* routines are always available.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/pull/51138
