### ISSUE TITLE
Single-argument `getindex` only works for some types

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#51712]
Single argument `getindex`, that is `x[]`, works for arrays and some other types – but not for all types where it makes sense:
```julia
julia> [1][]
1

julia> [1;;][]
1

julia> Ref(1)[]
1

julia> (1,)[]
ERROR: MethodError: no method matching getindex(::Tuple{Int64})

julia> (a=1,)[]
ERROR: MethodError: no method matching getindex(::@NamedTuple{a::Int64})
```
Seems inconsistent, presumably it's just an omission – right?

**Comment by laborg** [comment]
I don't think it "works for arrays" :
```
julia> [1,1][]
ERROR: BoundsError: attempt to access 2-element Vector{Int64} at index []
```

**Comment by adienes** [comment]
anywhere `x[]` works probably "should" have been `only(x)`

**Comment by mbauman** [comment]
In my view, using the ["wrong number" of indices](https://docs.julialang.org/en/v1/manual/arrays/#Number-of-indices) to access an element is a pretty idiosyncratic array-specific thing.  For example, arrays also pretend to support "trailing singleton dimensions" like `[1][1,1,1]`.  I don't think these semantics should necessarily apply to non-array types.

Dictionaries and tuples, for example, don't — and probably shouldn't — support those trailing indices.  I'm not really convinced they should support missing indices.

**Comment by brenhinkeller** [comment]
Looks like this is currently "not planned", but others feel free to undo
