### ISSUE TITLE
Huge coredumps in `/var/lib/systemd/coredump`

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/julia#51722]
I just discovered that inside `/var/lib/systemd/coredump` I have 3 entries starting with `core.julia.1000`. They take up 68, 143 and 449 MB. That is a lot for files that end up as trash lying around on my system.

They all come from the same day, and I believe they were created at a point when I got mad at the amount of RAM and SWAP memory hogged by background Julia processes started by VSCode, and i force-closed them.

My issue is that these potentially huge dumps should not be produced in a hidden place, cluttering the disk of users.

This issue may be more appropriately aimed at the VSCode extension, in which case I will copy the issue-text  in a new issue over there.

**Comment by vtjnash** [comment]
This is a user configuration of your computer (specifically, of `ulimit -c`) that we have no control over. They are produced when you kill programs with SIGQUIT (e.g. ctrl-\).

**Comment by PallHaraldsson** [comment]
It seems you should do a normal kill (i.e. SIGTERM; or maybe SIGINT, CTRL-C and this would not happen), not SIGQUIT (did you for sure do that?):

https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by KronosTheLate** [comment]
I opened the Gnome system monitor, highligted the Julia process, and pressed "end". But alright, it seems like this is a Linux-controlled event, and that it is not something Julia or VSCode can do much about. Thanks for your replies.
