### ISSUE TITLE
Julia cannot handle a computationally fine division due to implementation details

### ISSUE THREAD

**Issue by mbarbar** [JuliaLang/julia#51731]
```
Rational{Int8}(-128) / Rational{Int8}(-128)
```
should give back `Rational{Int8}(1)`, however it produces an error in the implementation
```
ERROR: OverflowError: gcd(-128, -128) overflows
Stacktrace:
 [1] __throw_gcd_overflow(a::Int8, b::Int8)
   @ Base ./intfuncs.jl:57
 [2] gcd(a::Int8, b::Int8)
   @ Base ./intfuncs.jl:54
 [3] divgcd
   @ ./rational.jl:44 [inlined]
 [4] //(x::Rational{Int8}, y::Rational{Int8})
   @ Base ./rational.jl:73
 [5] /(x::Rational{Int8}, y::Rational{Int8})
   @ Base ./rational.jl:360
 [6] top-level scope
   @ REPL[3]:1
```

and this is not inherent to the computation.

Julia installed from the dmg, versioninfo:
```
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by inkydragon** [comment]
When `T <: Signed`:
https://github.com/JuliaLang/julia/blob/bbcbac9752ad54faf960fa26d2f105fc8ae7771e/test/intfuncs.jl#L52
It looks like it was done on purpose.

```
julia> gcd(typemin(Int8), typemin(Int8))
ERROR: OverflowError: gcd(-128, -128) overflows
Stacktrace:
 [1] __throw_gcd_overflow(a::Int8, b::Int8)
   @ Base .\intfuncs.jl:57
 [2] gcd(a::Int8, b::Int8)
   @ Base .\intfuncs.jl:54
 [3] top-level scope
   @ REPL[4]:1

julia> versioninfo()
Julia Version 1.8.5
```

**Comment by mbarbar** [comment]
While this seems acceptable for `gcd`, it doesn't seem, to me, reasonable for division to expose this error. For example, if division wasn't implemented using `gcd`, we wouldn't see this error and either have a result or a division-specific error.

**Comment by Jay-sanjay** [comment]
@inkydragon  Hello would happy to help, with this issue. I guess this bug could be fixed just by defining `gcd( )` for equal Rational numbers too. Am I correct...?
