### ISSUE TITLE
Generic Linux on ARM (AArch64) build, stable (v1.9.3) and LTS (v1.6.7) broken

### ISSUE THREAD

**Issue by dondy** [JuliaLang/julia#51768]
The script `print(10)` results in a uncaught Exception:

```
fatal: error thrown and no exception handler available.
ReadOnlyMemoryError()
__aarch64_sync_cache_range at /workspace/srcdir/gcc-7.1.0/libgcc/config/aarch64/sync-cache.c:54
_ZN4llvm3sys6Memory26InvalidateInstructionCacheEPKvm at /home/dondy/julia-1.6.7/bin/../lib/julia/libLLVM-11jl.so (unknown line)
```

That breaks other stuff too, f.e. the help in the REPL or the LSP similarly don't work.
tested on: Linux  6.1.55-06866-g0ae6faaa0d86 #1 SMP PREEMPT Fri Sep 29 19:51:21 PDT 2023 aarch64 GNU/Linux

**Comment by maleadt** [comment]
https://github.com/JuliaLang/julia/issues/41852; should be fixed on 1.10.
