### ISSUE TITLE
Option for "Standard" shortcuts

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#51784]
Inspired by accidentally clicking "^C" (thinking I was in the text editor) and cancelling a long in-progress calculation: most people are much more familiar with the standard set of text-editor/browser shortcuts (ctrl+c for copy, ctrl+v for paste, ctrl+backspace to delete a word) than they are with bash; it would be great to have an option to enable this scheme instead of bash's.

**Comment by simeonschaub** [comment]
This depends on your terminal emulator and is not Julia specific. See https://unix.stackexchange.com/questions/114392/copy-paste-in-a-terminal-without-shift

**Comment by ParadaCarleton** [comment]
> This depends on your terminal emulator and is not Julia specific. See https://unix.stackexchange.com/questions/114392/copy-paste-in-a-terminal-without-shift

What's up with [this section in the docs](https://docs.julialang.org/en/v1/stdlib/REPL/#Key-bindings), then?
