### ISSUE TITLE
Empty range has first element

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#51793]
I found the following behavoir, which is IMO a bug, but not sure:

```julia
julia> isempty(1:0)
true

julia> first(1:0)
1
```
I would have expected an error. https://discourse.julialang.org/t/empty-range-has-first-element-bug-or-feature/105236

**Comment by jw3126** [comment]
I can provide a PR later, if desired.

**Comment by giordano** [comment]
```
help?> first(1:0)
  first(coll)

  Get the first element of an iterable collection. Return the start point of an AbstractRange even if it is empty.
```

**Comment by oscardssmith** [comment]
yuck. That's really our definition? I hate that.

**Comment by stevengj** [comment]
It's pretty important because it allows you to return useful information from searches where the result is an empty range with a location.  For example:
```jl
julia> findnext(r"\b", "foo bar", 2)
4:3
```

**Comment by Moelf** [comment]
I think if we have a function called `start()` that has:
>Return the start point of an AbstractRange even if it is empty.

I would be much more comfortable.

**Comment by jariji** [comment]
Can we reopen this with a 2.0 label? This API is terrible.

**Comment by jw3126** [comment]
> It's pretty important because it allows you to return useful information from searches where the result is an empty range with a location. For example:
> 
> ```julia
> julia> findnext(r"\b", "foo bar", 2)
> 4:3
> ```

That looks like an argument, why it is good to have a way to access the start of an empty range. But is it also an argument, why that must happen via the `first` function?
