### ISSUE TITLE
`inc<TAB>` now completes to `include_` even though `include` exists

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#51823]
With a Tab after `inc`:

```
julia> include_

julia> include
include (generic function with 2 methods)
```

**Comment by simeonschaub** [comment]
I'm guessing this is https://github.com/JuliaLang/julia/pull/51411 as well. @JeffBezanson Can we revert that? I don't really see the benefit and it's breaking other things

**Comment by PallHaraldsson** [comment]
Should it tab-complete to `includet(`? Possibly only if Revise is loaded? I believe there's talk to include Revise in Base, should includet be added there as a synonym for include (until such happens)?

https://timholy.github.io/Revise.jl/stable/user_reference/#Revise.includet

**Comment by KristofferC** [comment]
What? That's a function from a different package. I'll mark this as off-topic.
