### ISSUE TITLE
`read!(::IO, ::ReinterpretArray)` performance

### ISSUE THREAD

**Issue by chrstphrbrns** [JuliaLang/julia#51838]
```julia
julia> a=Vector{UInt8}(undef,1_000_000_000);

julia> b=reinterpret(UInt16, a);

julia> f=open("data", "r"); # 1 GB

julia> @time read!(f,a);
  0.307432 seconds (5.56 k allocations: 407.016 KiB, 6.52% compilation time)

julia> f=open("data", "r");

julia> @time read!(f,b);
  8.080147 seconds (15.09 k allocations: 1.029 MiB, 0.33% compilation time)

julia> function Base.read!(s::IO, a::Base.ReinterpretArray{T}) where T
           GC.@preserve a unsafe_read(s, pointer(a), length(a) * sizeof(T))
       end

julia> f=open("data", "r");

julia> @time read!(f,b);
  0.149527 seconds (6.76 k allocations: 456.250 KiB, 5.54% compilation time)
```
This poor performance is easily explained, since the fallback in `read!` is a for-loop that reads T-by-T, but it's a surprising limitation

Not sure if `pointer(::ReinterpretArray)` is legitimate here, but it does seem to work

(views have the same issue)

**Comment by N5N3** [comment]
We have a stale PR for this issue (#42593).
It only covers "dense" array known at compile time.
We can fuse the code from `strides(::ReshapedArray)` to extend the acceleration to more `StridedArrays`

**Comment by N5N3** [comment]
close by #42593
