### ISSUE TITLE
should `ntoh(x::Bool) = x`?

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#51841]
This seems sensible?

**Comment by stevengj** [comment]
This is already the definition, no?

https://github.com/JuliaLang/julia/blob/df39cee3d8723d04b8ba73b13e59d45d195e8f0b/base/int.jl#L397

**Comment by Moelf** [comment]
https://github.com/JuliaLang/julia/pull/45265#issuecomment-1273645507 I even commented before. Thanks again!
