### ISSUE TITLE
`exit()` inferred to return `nothing`, not `Union{}`

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#51856]
```julia
julia> only(Base.return_types(exit, (Int,)))
Nothing
```
This has the following consequence for inference:
```julia
julia> function parse_plus_one(s::String)
           n = tryparse(Int, s)
           if isnothing(n)
               println(stderr, "Could not parse as `Int`: \"$(s)\"")
               exit(1)
           end
           n + 1
       end

julia> @report_call parse_plus_one("15")
═════ 1 possible error found ═════
┌ parse_plus_one(s::String) @ Main ./REPL[13]:7
│ no matching method found `+(::Nothing, ::Int64)` (1/2 union split): (n::Union{Nothing, Int64} + 1)
```
I think Julia ought to infer that `exit()` never returns, and thus be able to refine the type of `n` to `Int`.

**Comment by giordano** [comment]
`exit` is defined as https://github.com/JuliaLang/julia/blob/3b1ba62bd27e0dabbd2ec0a6c000edb8138c5915/base/initdefs.jl#L28 and the return type of a `ccall(..., Cvoid, ...)` is necessarily `Cvoid` (==`Nothing`), julia doesn't know what happens inside the ccall.

**Comment by jakobnissen** [comment]
We could easily fix this by defining it to return `exit(n) = (ccall(:jl_exit, Cvoid, (Int32,), n); error())`, but I would hope there is some better fix at the compiler level to signal that something never returns.

**Comment by KristofferC** [comment]
I was just typing out the `error` suggestion myself. Feels fine to me?

**Comment by giordano** [comment]
But am I missing something or the
```
│ no matching method found `+(::Nothing, ::Int64)` (1/2 union split): (n::Union{Nothing, Int64} + 1)
```
comes from the fact `tryparse` can be `nothing`?  I don't see how the return type of `exit` is any relevant here.

**Comment by jakobnissen** [comment]
If the compiler knows that `exit` returns `Union{}` (i.e. it never returns), then it knows for sure that if it reaches the line `n + 1`, then `n` can't be `nothing`, and thus must be an `Int`.
The compiler is able to make this inference if you replace `exit` with `error`, because `error` is inferred to return `Union{}`. Really, the inferred return type of `exit` to be `Nothing` is simply poor inference. It's correct, because `Nothing` is a supertype of `Union{}`, but the correct return type is `Union{}`.

**Comment by giordano** [comment]
```
julia> function parse_plus_one(s::String)
           n = tryparse(Int, s)
           if isnothing(n)
               println(stderr, "Could not parse as `Int`: \"$(s)\"")
               error()
           end
           n + 1
       end
parse_plus_one (generic function with 1 method)

julia> @code_warntype parse_plus_one("")
MethodInstance for parse_plus_one(::String)
  from parse_plus_one(s::String) @ Main REPL[19]:1
Arguments
  #self#::Core.Const(parse_plus_one)
  s::String
Locals
  n::Union{Nothing, Int64}
Body::Int64
1 ─      (n = Main.tryparse(Main.Int, s))
│   %2 = Main.isnothing(n)::Bool
└──      goto #3 if not %2
2 ─ %4 = Main.stderr::IO
│   %5 = Base.string("Could not parse as `Int`: \"", s, "\"")::String
│        Main.println(%4, %5)
└──      Main.error()
3 ┄ %8 = (n + 1)::Int64
└──      return %8
```
looks exactly the same to me as with `exit`.  Again, I don't see how `exit` is any special here, you have the same problem with `error`.

**Comment by jakobnissen** [comment]
Not quite. In that example, with `exit`, the compiler is able to infer that `(n + 1)::Int`, since if `n` was `nothing`, the `+` would throw. However, with `error`, it knows that `n` is an `Int` already before the `+` happens. You can verify this by having the function return `n` instead of `n + 1`.
