### ISSUE TITLE
You really should rethink the following aspect of the type system: Currently Vector{Float64} is not recognized as a subtype of Vector{Real}.}

### ISSUE THREAD

**Issue by RaimundK2** [JuliaLang/julia#51868]

**Comment by RaimundK2** [comment]
This is a strange decision, because one would expect that any container of a subtype is a subtype of the same  container of the related supertype. This feature forces you - unnecessarily - to add some type casting code ...

**Comment by gbaraldi** [comment]
It's not recognized as a subtype because it isn't a subtype. You are looking for
```julia
julia> Vector{Float64} <: Vector{<:Real}
true
```

**Comment by RaimundK2** [comment]
Ok. I take back my issue ... Was not aware of this possibility
