### ISSUE TITLE
Document that isequal implementation requires hash implementation

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#51876]
`hash` [says](https://docs.julialang.org/en/v1/base/base/#Base.hash) 

> Compute an integer hash code such that `isequal(x,y)` implies `hash(x)==hash(y)`.

which is right but

> Typically, any type that implements `hash` should also implement its own [`==`](https://docs.julialang.org/en/v1/base/math/#Base.:==) (hence [isequal](https://docs.julialang.org/en/v1/base/base/#Base.isequal)) to guarantee the property mentioned above.

is backwards. Typically, any type that implements `==` should also implement `hash`, to match the required property above.

**Comment by oscardssmith** [comment]
I think this is correct. (especially since in the `isequal` docs we also have
```
This typically means that types for which a custom == or isequal method exists must implement a corresponding [hash](https://docs.julialang.org/en/v1/base/base/#Base.hash) method (and vice versa). Collections typically implement isequal by calling isequal recursively on all contents.
```

**Comment by JeffBezanson** [comment]
Yes, the docs for isequal already say this AFAICT.
