### ISSUE TITLE
Operator precedence of & and | is surprising as element-wise boolean operators

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#5187]
I just got bit by the python-like operator precedence for the operators `|` and `&`.  As bitor and bitand, it's a wonderful choice (making checking for bit flags much simpler — a common gotcha in C).  

But when behaving as their element-wise boolean counterparts to `||` and `&&`, it is surprising.  `A < 1 || A > 2` must be written differently if A is an array: `(A .< 1) | (A .> 2)`.  Perhaps all that's needed here is a bit more documentation (i.e., putting https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm#L1-L19 into the Mathematical Operators page, or as something to mention to users coming from Matlab).

But as I look at the source for `|(::StridedArray,::StridedArray)`, I see that it's actually applying the bitwise operator to all elements.  As a radical alternative, what about adding `.&&` and `.||` with similar precedence to `&&` and `||` that ensures boolean elements?  Functionally, `&` and `.&&` would behave the same on logical arrays, but they'd each have the precedence one would expect in each context.  (Of course, there'd still be some cognitive dissonance here as the elementwise boolean operators couldn't short-circuit like their scalar equivalents).

**Comment by JeffBezanson** [comment]
I propose keeping this as-is. I agree `&` is `*`-like and `|` is `+`-like.

**Comment by johnmyleswhite** [comment]
So I guess we bailed on @mbauman's point: "I think it's very important to allow syntax such as `B[A .< 1 | A .> 2]` without parentheses."?

**Comment by StefanKarpinski** [comment]
What about making a new precedence level for dot-comparisons between [these two](https://github.com/JuliaLang/julia/blob/d99c23758ca8a20f9b5b1f969e41cd5e0bd32bd5/src/julia-parser.scm#L18-L19)?

**Comment by JeffBezanson** [comment]
I don't think we can give `.<` higher precedence than `.+`.

**Comment by StefanKarpinski** [comment]
Perhaps `.+` should be higher as well?

**Comment by mbauman** [comment]
If `.<` is higher than `*`, then I think `5A .< 5` would be even more surprising than this issue is.

There are two distinct uses of `&`, bitwise and broadcasting, and I'm afraid neither will ever be happy with the other's precedence level.  :-\

**Comment by nalimilan** [comment]
> There are two distinct uses of &, bitwise and boolean-like broadcasting, and I'm afraid neither use will ever be happy with the other's precedence level. :-\

Fully agreed. And what about changing the bitwise operators? I think it's been discussed several times before. That would have the advantage of reducing the confusion, as bitwise operators and element-wise boolean operators are used in very different contexts.

**Comment by ScottPJones** [comment]
Why would anything affect `5A .< 5`?   Shouldn't the juxtaposition multiplication be treated as having the highest of all precedence?  (It can be rewritten as `(5 * A)` by the compiler, right?)
If that's not what is currently happening, I would suggest that it should be changed.

**Comment by JeffBezanson** [comment]
Juxtaposition multiplication has the precedence of unary operators I believe, which is indeed higher than most operators.

**Comment by ScottPJones** [comment]
So something like -5A would be parsed as (-5) * A or -(5 * A)? (not that it probably matters in that example, but just wondering, if somebody had some unary operator that really needed to work on (5 * A),
say if A is an array, if that would work without having to put parenthesis.

**Comment by yuyichao** [comment]
```julia
julia> Meta.show_sexpr(:(-5A))
(:call, :*, -5, :A)
```

**Comment by mbauman** [comment]
Ah, good catch.  Right you are.

I think that changing the precedence of `.<` might have been a valid solution if https://github.com/JuliaLang/julia/pull/5810 had stuck.

I really like the idea of deprecating the bitwise arithmetic meaning here, and restricting `&` and `|` to `Bool` and `AbstractArray{Bool}`.  Matlab uses the names `bitand` and `bitor`, which seem sensible.

**Comment by ScottPJones** [comment]
Ah, I should have used a different example, because -5 is being parsed as a number, and *then* the juxtaposition takes place... it looks like unary operators, it actually is the other way around... (which I think is correct), i.e.:
```julia
julia> Meta.show_sexpr(:(~5A))
(:call, :~, (:call, :*, 5, :A))
```

**Comment by johnmyleswhite** [comment]
> I really like the idea of deprecating the bitwise arithmetic meaning here, and restricting & and | to Bool and AbstractArray{Bool}. Matlab uses the names bitand and bitor for bitwise arithmetic, which seem sensible.

+100 for this change

**Comment by tkelman** [comment]
> I really like the idea of deprecating the bitwise arithmetic meaning here, and restricting & and | to Bool and AbstractArray{Bool}. Matlab uses the names bitand and bitor for bitwise arithmetic, which seem sensible.

-1, that seems backwards to me. `|=` and `&=` are really useful syntax for doing masking operations, would be a bummer to lose those. Can someone explain why the elementwise versions of these operators aren't spelled `.|` and `.&` ?

**Comment by StefanKarpinski** [comment]
I feel like we're really reaching the limits of what sticking dots in front of things can do for us. #8450 

![homer rectal probing](https://cloud.githubusercontent.com/assets/153596/8308025/51d82110-1990-11e5-8e65-fd8c70e0a89a.png)

**Comment by ScottPJones** [comment]
`&`, `|`, and `$` (as well as `&=`, `|=`, and `$=` are very heavily used in the sorts of bit twiddling programming that I frequently do...  It would be very bad if they didn't work on `unsigned` and `integer`.

**Comment by Sacha0** [comment]
> |= and &= are really useful syntax for doing masking operations, would be a bummer to lose those. Can someone explain why the elementwise versions of these operators aren't spelled .| and .& ?

+1

**Comment by tkelman** [comment]
This is probably worth its own issue for 0.6 (or 1.0), but listening to Guy Steele's JuliaCon talk https://www.youtube.com/watch?v=EZD3Scuv02g the main takeaway that stuck with me as far things that would be realistic to do in Julia would be non-transitive operator precedence.

**Comment by StefanKarpinski** [comment]
I'm all for non-transitive operator precedence. I believe @JeffBezanson is pretty sold on the idea too (and as the "syntax czar" of the project, his opinion on the matter is significantly significant). Seem a little tricky to implement though.

**Comment by StefanKarpinski** [comment]
I wonder if that could allow `=` and `&&` or `=` and `||` to be on the same level and be right associative so that `a = b && c` parses as `a = (b && c)` while `a && b = c` parses as `a && (b = c)`.

**Comment by eschnett** [comment]
I believe the main point of "non-transitive precedence" was to make ambiguous cases an error that requires parentheses to clarify the code, not adding special cases that let people use even fewer parentheses.

**Comment by StefanKarpinski** [comment]
It's both – otherwise you would just require parens all the time, problem
solved. Non-transitive precedence allows omitted parens in cases where
there's an obvious precedence between certain operators, even if that
relation can't be extended to global ordering.

**Comment by musm** [comment]
> I wonder if that could allow = and && or = and || to be on the same level and be right associative so that a = b && c parses as a = (b && c) while a && b = c parses as a && (b = c).
 
I really like this idea, IMO I find it really ugly to always write `condition(a) && (x = 2)`  it would be a lot more clear as `condition(a) && x = 2` .

**Comment by mbauman** [comment]
Could we allow `&&` and `||` to participate in dot-fusion now?  Especially if the `@.` macro applied to them, this seems like it could be a nice solution.  As I noted in the first post:

> `A < 1 || A > 2` must be written differently if A is an array: `(A .< 1) | (A .> 2)`

Why not allow `@. A < 1 || A > 2` to fuse into `broadcast(x->x < 1 || x > 2, A)`?

**Comment by JeffBezanson** [comment]
Coming back to this, it seems pretty clear to me that `(a < b) & (c < d)` is way more useful than `a < (b & c) < d`. Reopening and marking for triage.

**Comment by nalimilan** [comment]
For anecdotal evidence, the current precedence of `&` prompts [some people](https://cbrownley.wordpress.com/2017/11/29/data-wrangling-in-julia-based-on-dplyr-flights-tutorials/) to write things like this:
```julia
 hflights[.&(hflights[:Month] .== 1, hflights[:DayofMonth] .== 1), :]
```

**Comment by Sacha0** [comment]
(Perhaps I should note that I have WIP on this front. I am prioritizing things A_mul_B though, so not certain whether I will post that work on a short timescale. Best!)

**Comment by robsmith11** [comment]
Has the plan for precedence change of `&` and `|` to allow for the expected behavior of `B[A .< 1 | A .> 2]` been changed?

I haven't seen any update in the 2.5 years since the deprecation.
