### ISSUE TITLE
`write(::AbstractVector{Char}` changed semantics

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#51911]
It looks like `write` of `Char`arrays used to produce the UTF8-encoding of the string of those chars.
It now behaves differently, while the writing of a single `Char` didn't change.

```
julia> VERSION
v"1.10.0-beta3"
julia> function writechars(ch)
           io = IOBuffer()
           write(io, ch)
           take!(io)
       end

julia> writechars('a')
1-element Vector{UInt8}:
 0x61
julia> writechars('a':'b')
2-element Vector{UInt8}:
 0x61
 0x62
```
```
julia> VERSION
v"1.11.0-DEV.754"

julia> writechars('a')
1-element Vector{UInt8}:
 0x61
julia> writechars('a':'b')
8-element Vector{UInt8}:
 0x00
 0x00
 0x00
 0x61
 0x00
 0x00
 0x00
 0x62
```

**Comment by jakobnissen** [comment]
Introduced in #42593. I think that the optimisation in `write(::IO, ::AbstractArray)` is incorrect - you can't assume that writing any isbits value `x` can be done using `unsafe_write(::IO, x, sizeof(x))`.
CC @N5N3

**Comment by N5N3** [comment]
That's @vtjnash's concern about [API difference](https://github.com/JuliaLang/julia/pull/42593#pullrequestreview-1695086995).
> There is also the question of padding, since read is usually not-implemented for most T, so whether this does unsafe_read or read is a different API.

The fastpath for `Array` always use `unsafe_write`, thus `writechars(collect('a':'b'))` always returns a `8-element Vector{UInt8}`.
In this sense, #42593 just makes `AbstractArray` behaving like an `Array`.

**Comment by N5N3** [comment]
Make sense to me, perhaps we should limits the optimization to bits type with no padding ambiguity.
Once we find `Base.packedsize(T) != Base.aligned_sizeof(T)` then always use the slow `read/write(io, T)` based loop.
If user want speed and don't care about the bit layout, `reinterpret` the strided src/dest into `UInt8` is always a option.

But `Char` is somehow special. Not padding, but it's "varying size" in "String" introduce the ambiguity, which can't be checked just by size.

**Comment by KlausC** [comment]
I would like to propose to use the optimization only for element types `Int8, Int16, Int32, Int64, Int128` and the unsigned counterparts, and leave the generic implementation as it was for all other bit types.

**Comment by jakobnissen** [comment]
I guess the underlying dilemma is: Following the definition of `write`, must `write(::IO, x::MyType)` always write exactly the binary representation of `x` as it is stored in memory?
If so, then the implementation of `write(::IO, ::Char)` is buggy, because `'A'` is stored stored in memory as `0x41`.
If not, then the implementation of `write(::IO, ::AbstractArray)` is buggy, since `'A':'Z'` is not stored in memory as 26 elements.
A third option is to define that `write(::IO, my_collection)` writes the binary representation of the _elements_ of the collection, not the collection itself. If so, then the implementation of `write(::IO, ::Array)` is buggy, since it does not respect the `write` method of its elements.

**Comment by vtjnash** [comment]
write is specified as writing the "canonical representation" for the type to the IO. For any AbstractArrays, the canonical representation seems to be copying what Array does. For Char alone, it is the utf8 variable-width encoding.

**Comment by KlausC** [comment]
> the canonical representation seems to be copying what Array does

that is unclear to me. I would define the canonical representation of any `AbstractArray` to be the juxtaposition of the elements of the array. And that is what it used to be up to now.
Copying the representation of `'a':'c'` would look much different from that of  `['a', 'b', 'c'].
In the case of `Char` a sequence of chars would be represented like a `String`, which is also what a user like me would expect.

**Comment by KlausC** [comment]
I have to revise my understanding, I was wrong, sorry for that. There has always been a difference between the implementation of `Array`and `AbstractArray`; I ignored that.  They should produce the same output. So `write(io, ['a','b']) should be the same as `write(io, 'a':'b').
For me the question remains now, if `Char` should be special-cased, also considering the writing of a single `Char`.
It would be consequent to have the loop `for c in array; write(io, c); end` result in the same output as `write(io, array)` for all types of `AbstractArray`, also with element type of `Char`.

**Comment by vtjnash** [comment]
I think the canonical bytes for an array would have to be something with `O(1)` access, as that seems to me to be the canonical feature of a standard array (yes, I realize some arrays are slower than that, such as immutable ones in functional collections are usually `O(log(n))` to access). If I was to propose a special-case for Char, it would probably be to make it the same as converting to Cwchar_t (an Int32), not converting to String
```
julia> reinterpret(UInt32, convert(Vector{Char}, 'a':'f'))
6-element reinterpret(UInt32, ::Vector{Char}):
 0x61000000
 0x62000000
 0x63000000
 0x64000000
 0x65000000
 0x66000000

julia> convert(Vector{UInt32}, 'a':'f')
6-element Vector{UInt32}:
 0x00000061
 0x00000062
 0x00000063
 0x00000064
 0x00000065
 0x00000066

julia> convert(String, 'a':'f')
ERROR: MethodError: Cannot `convert` an object of type StepRange{Char, Int64} to an object of type String
```

**Comment by KlausC** [comment]
While `convert(String...` is not supported, there is a corresponding constructor:

```
julia> String('a':'f')
"abcdef"
```

I am not sure, how the semantics of `write` is strictly defined (that should be done somewhere). Actually it is a simple kind of serialization. I fear changing `write(io, ::Char)` or `write(io, ::String)` is not a good idea, because user expectation is probably, that a UTF8-encoded stream of UInt8 characters is produced (for example many `show` methods use this assumption).
The internal representation of a `Char` seems to be 1-4 bytes of the UTF8-encoding in a UInt32 frame, probably chosen for performance.
It would be necessary to know, how the data written by `write(io, ::Array{Char})` can be retrieved using a corresponding `read`. In `1.10`and `1.11`we have now:

```
julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, ['a', '€'])
8

julia> seek(io, 0)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=8, maxsize=Inf, ptr=1, mark=-1)

julia> read(io, Char)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> read(io, Char)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> read(io, Char)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> read(io, Char)
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> read(io, Char)
'\0': ASCII/Unicode U+0000 (category Cc: Other, control)

julia> read(io, Char)
'\xac': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> read(io, Char)
'\x82': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> read(io, Char)
'\xe2': Malformed UTF-8 (category Ma: Malformed, bad data)

julia> read(io, Char)
ERROR: EOFError: read end of file
```
(note the reverse order of bytes and the padding zero bytes)

Meaning: there is no canonical way of retrieving the data, written as `Vector{Char}`, while `read(io, ::Char)` is designed to accept the next UTF8-encoded character.

```
julia> read(io, String)
"\0\0\0a\0\xac\x82\xe2"
```

The follow works - looking not so nice
```
julia> seek(io, 0)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=8, maxsize=Inf, ptr=1, mark=-1)

julia> reinterpret(Char, read(io, UInt32))
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> reinterpret(Char, read(io, UInt32))
'€': Unicode U+20AC (category Sc: Symbol, currency
```

**Comment by vtjnash** [comment]
The canonical way would seem to be calling `read!` back into a `similar` array that was originally written, or perhaps another alike solution such as `read!(io, Ref{Char}())[]` for one-at-a-time reads
