### ISSUE TITLE
@showtime prints internal details when macros are present

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#51915]
Docstring for `@showtime` says:
```
help?> @showtime
  Like @time but also prints the expression being evaluated for reference.
```
But in practice this is only the case for expressions without macros in them. With macros, it prints some extra details that I understand as internals:
```julia
julia> @showtime @eval @inbounds 123
#= REPL[9]:1 =# @eval(#= REPL[9]:1 =# @inbounds(123)): 0.005701 seconds (7.39 k allocations: 446.130 KiB, 0.00% compilation time)
```
Can these `#= REPL =#` things be removed?

**Comment by PallHaraldsson** [comment]
I suppose comments starting with "#= REPL", could be easily stripped, since seemingly not too helpful. About macros, which you asked for, and they are evaluated from right to left, you kind of asked for everything they give you? I.e. you want to see at least e.g. "@eval" there? Or just 123 wanted? I think in some cases you would get something useful in the comments, so can't just strip out all comments.

**Comment by mcabbott** [comment]
This isn't just `@showtime`, any expression printing shows a `LineNumberNode` which is part of the macro call.
```julia
julia> @show @inbounds 32[1]
#= REPL[91]:1 =# @inbounds((32)[1]) = 32
32

julia> ex = :(@inbounds 32[1])
:(#= REPL[92]:1 =# @inbounds (32)[1])

julia> dump(ex)
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: Symbol @inbounds
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[92]
    3: Expr
      head: Symbol ref
      args: Array{Any}((2,))
        1: Int64 32
        2: Int64 1

julia> ex2 = quote @inbounds 32[1] end  # begin/end block has another LineNumberNode
quote
    #= REPL[94]:1 =#
    #= REPL[94]:1 =# @inbounds (32)[1]
end

julia> Base.remove_linenums!(ex2)  # does not act within macrocall
quote
    #= REPL[94]:3 =# @inbounds (32)[1]
end
```
MacroTools.jl has a function which removes these where `remove_linenums!` doesn't. I don't know whether `nothing` is strictly legal in this position, but it seems to work:
```julia
julia> MacroTools.striplines(ex2)
quote
    @inbounds (32)[1]
end

julia> dump(ans)
Expr
  head: Symbol block
  args: Array{Any}((1,))
    1: Expr
      head: Symbol macrocall
      args: Array{Any}((3,))
        1: Symbol @inbounds
        2: Nothing nothing
        3: Expr
          head: Symbol ref
          args: Array{Any}((2,))
            1: Int64 32
            2: Int64 1
```

**Comment by vtjnash** [comment]
It is incorrect to strip them, but not strictly illegal either. The file and line number are semantically important, not just an internal detail. Although since they are injected by the parser, they cannot be round-trip printed and parsed to the same expression.
