### ISSUE TITLE
Bug in `pointer(::Memory, ::Int)`

### ISSUE THREAD

**Issue by Drvi** [JuliaLang/julia#51954]
As noted by @MasonProtter on slack:
```julia
julia> x = Memory{Int}(undef, 4)
4-element Memory{Int64}:
 16
  0
  0
  0

julia> typeof(pointer(x))
Ptr{Int64}

julia> typeof(pointer(x, 1))
Ptr{Nothing}
```
versus
```julia
julia> y = Vector{Int}(undef, 4)
4-element Vector{Int64}:
 0
 0
 0
 0

julia> pointer(y)
Ptr{Int64} @0x00007f4ce499b1e0

julia> pointer(y, 1)
Ptr{Int64} @0x00007f4ce499b1e0
```

**Comment by Moelf** [comment]
```julia
pointer(x)
```

this is hitting `AbstractArray` fallback, which shouldn't be the intended behavior, I think both should be `Ptr{Nothing}`

**Comment by Drvi** [comment]
The fact that `unsafe_load(pointer(x, 1))` didn't return an integer broke our nighly CI, I'd expect both to return `Ptr{Int}` in this case

**Comment by oscardssmith** [comment]
I'm pretty sure the explicit definition for Memory is wrong. @vtjnash why is it a `Ptr{Nothing}`?

**Comment by nickrobinson251** [comment]
https://github.com/JuliaLang/julia/pull/51963
