### ISSUE TITLE
effect inference bug on v1.10 beta 3

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#51969]
On v1.10 (but not on the v1.11 nightlies) a type assertion on the return value seems to affect the effect inference for the *consistency* effect.

Here `f` and `g` differ only in that `g` misses the type assertion in the end, somehow resulting in better consistency effect inference for `g`:

```julia-repl
julia> z(i::Int) = NTuple{i - 1, Any}
z (generic function with 1 method)

julia> f(::Val{n}) where {n} = Union{ntuple(z, Val(n + 1))...}::Type{<:Tuple}
f (generic function with 1 method)

julia> g(::Val{n}) where {n} = Union{ntuple(z, Val(n + 1))...}
g (generic function with 1 method)

julia> Base.infer_effects(f, Tuple{Val{0}})
(?c,+e,+n,+t,+s,+m,+i)

julia> Base.infer_effects(g, Tuple{Val{0}})
(+c,+e,+n,+t,+s,+m,+i)

julia> versioninfo()
Julia Version 1.10.0-beta3
Commit 404750f8586 (2023-10-03 12:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 3
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

I don't know if this is considered as worthy of backporting, but there you go.

**Comment by nsajko** [comment]
Inference is perfect for `x(::Type{T}, ::Val{n}) where {T, n} = T <: f(Val(n))`, though. So I guess the above inference flaw may not matter?

**Comment by Keno** [comment]
We generally don't backport inference precision improvements, so since this is fixed on master, I don't think this is actionable.
