### ISSUE TITLE
`sortslices` does not infer

### ISSUE THREAD

**Issue by elbert5770** [JuliaLang/julia#52019]
This is the recommended way to sort by rows with arrays according to the docs.  There really needs to be a way to do this that is type stable.  This is an old issue but was never resolved.

```
function main()
    array_to_sort = rand(2,3)
    sorted = sortslices(array_to_sort; dims=1)
end

@code_warntype main() 
 ```

```
MethodInstance for main()
  from main() @ Main Untitled-1:2
Arguments
  #self#::Core.Const(main)
Locals
  sorted::Any
  array_to_sort::Matrix{Float64}
Body::Any
1 ─      (array_to_sort = Main.rand(2, 3))
│   %2 = (:dims,)::Core.Const((:dims,))
│   %3 = Core.apply_type(Core.NamedTuple, %2)::Core.Const(NamedTuple{(:dims,)})
│   %4 = Core.tuple(1)::Core.Const((1,))
│   %5 = (%3)(%4)::Core.Const((dims = 1,))
│   %6 = Core.kwcall(%5, Main.sortslices, array_to_sort)::Any
│        (sorted = %6)
└──      return %6
```

**Comment by LilithHafner** [comment]
Yipes. See also #49394.

**Comment by elbert5770** [comment]
Changing line 1907 of multidimensional.jl to:
```
1907 p::Vector{Int64} = sortperm(vecs; kws...)
```
seems to help?  It seems that the type instability is from 1912 return dims == 1 ? A[p, :] : A[:, p] because p can be anything.  Seems to work with a local copy of the code.  I have not tested ndims > 2

**Comment by Zentrik** [comment]
The problem seems to be that we're calling this which tries to convert the `dims` argument to a `Val`
```jl
function sortslices(A::AbstractArray; dims::Union{Integer, Tuple{Vararg{Integer}}}, kws...)
    _sortslices(A, Val{dims}(); kws...)
end
```
This causes `@code_warntype` and Cthulhu to the type of `Val{dims}` is unknown which causes all the type instabilities.
E.g. 
```jl
function main_val()
    array_to_sort = rand(2,3)
    sorted = Base._sortslices(array_to_sort, Val{1}())
end

@code_warntype main_val() 
```
```jl
julia> @code_warntype main_val() 
MethodInstance for main_val()
  from main_val() @ Main REPL[32]:1
Arguments
  #self#::Core.Const(main_val)
Locals
  sorted::Matrix{Float64}
  array_to_sort::Matrix{Float64}
Body::Matrix{Float64}
1 ─      (array_to_sort = Main.rand(2, 3))
│   %2 = Base._sortslices::Core.Const(Base._sortslices)
│   %3 = array_to_sort::Matrix{Float64}
│   %4 = Core.apply_type(Main.Val, 1)::Core.Const(Val{1})
│   %5 = (%4)()::Core.Const(Val{1}())
│   %6 = (%2)(%3, %5)::Matrix{Float64}
│        (sorted = %6)
└──      return %6
```
Benchmarking shows a 20% performance improvement
```jl
julia> @btime main();
  595.972 ns (19 allocations: 896 bytes)

julia> @btime main_val();
  474.015 ns (19 allocations: 896 bytes)
```

**Comment by LilithHafner** [comment]
@elbert5770, I imagine that would work, provided `p` always really is a `Vector` (which it probably should be). However, the existing code is uglier and more complicated than necessary so rather than trying to tweak the special cases, I rewrote it all.

The `Val` thing is a bit ugly and could, theoretically, be removed. However, it makes the implementation a lot easier to optimize. Constructing a `Val` like that is not type stable and forces a dynamic dispatch, as @Zentrik observed. However, we can help the compiler infer this function's return type reliably by using a syntactic construction that isolates the return type from the dynamic dispatch.

```julia
function sorslices(A, dims; kw...)
    B = similar(A)
    dynamic_dispatch!(B, A, Val{dims}(); kw...) # this can't possibly change the type of B
    B
end
```
