### ISSUE TITLE
Separate bound checks for reads and writes

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#52012]
Currently people may think if you do not do `@inbounds` you are safe, but you are not, in case you used `undef`.

It's never correct to read an undef value, but it's correct to write over it.

This change shouldn't need 2.0, since it's broken code anyway that does this... but there could be a global setting to allow reading, or unifying the bounds.

[Unrelated to this issue I think @inbounds should be changed to a no-op (at least for non-1-based arrays), it's not faster always anyway, and the ecosystem is also broken; too many packages incorrect, since `OffsetArray`s were introduced. Adding some `@unsafe_inbounds` might help, and really discourage its use, or limit its effect to 1-based arrays.]

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/52011.
