### ISSUE TITLE
The allocation profiler records an allocation even when `@allocated` reports zero allocation

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#52022]
```julia-repl
julia> using Profile

julia> const x = 0.3;

julia> sin(x);

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 sin(x);

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 sin(x);

julia> ((x -> x.size) ∘ only ∘ (x -> x.allocs) ∘ Profile.Allocs.fetch)()
16

julia> @allocated sin(x)
0

julia> versioninfo()
Julia Version 1.11.0-DEV.831
Commit 4462257017b (2023-11-03 19:09 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_NUM_PRECOMPILE_TASKS = 3
  JULIA_PKG_PRECOMPILE_AUTO = 0
```

The above results are the same on v1.9.3, v1.10.0-rc1, v1.11 (nightly).

When the argument (of some other but similar function) is a `Tuple`, instead of just a single `Float64`, the allocation reported by the profiler is bigger, and it scales with tuple length.

Like #50187, this is an inconsistency between the allocation profiler and `@allocated`, but here the profiler is the one with the greater allocation size.

**Comment by vtjnash** [comment]
Since the code is measuring different things, I don't see why it shouldn't get different answers. In one case, you discard the return value so it skips the allocation. In the other case, you return the value, so it allocates it

**Comment by nsajko** [comment]
OK, reduced this further, it got even weirder:

```julia-repl
julia> using Profile

julia> const f = Returns(0.3)
Returns{Float64}(0.3)

julia> const i = Returns(3)
Returns{Int64}(3)

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 f();

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 f();

julia> (length ∘ (x -> x.allocs) ∘ Profile.Allocs.fetch)()
1

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 i();

julia> Profile.Allocs.clear()

julia> Profile.Allocs.@profile sample_rate=1 i();

julia> (length ∘ (x -> x.allocs) ∘ Profile.Allocs.fetch)()
0
```

So it seems that profiling any function that returns a `Float64` value will report at least a single 16-byte allocation. But if the function returns `Int` (instead of `Float64`), no allocation is reported!

**Comment by nsajko** [comment]
> In the other case, you return the value, so it allocates it

It's just a single isbits primitive value. Why would it need to be allocated, be it integer or float?

**Comment by topolarity** [comment]
Hmm, in a function context, the allocation does not occur:
```julia
julia> foo() = Profile.Allocs.@profile sample_rate=1 sin(1.5)
foo (generic function with 1 method)

julia> foo()
0.9974949866040544

julia> Profile.Allocs.clear()

julia> foo()
0.9974949866040544

julia> length(Profile.Allocs.fetch().allocs)
0
```

Also wrapping the `Profile.Allocs.@profile` call in `@allocated` or vice-versa is enough to avoid the issue:
```julia
julia> Profile.Allocs.clear()

julia> @allocated Profile.Allocs.@profile sample_rate=1 sin(1.5)
0

julia> Profile.Allocs.@profile sample_rate=1 @allocated sin(1.5)
0

julia> length(Profile.Allocs.fetch().allocs)
0
```

Wrapping in `@timed` has the same effect.

Perhaps the `Expr(:meta, :force_compile)` in those macros is changing how these are evaluated?

**Comment by nsajko** [comment]
Why close??

**Comment by vtjnash** [comment]
As I mentioned above, these measure different things, so it is expected they come to different answers

**Comment by topolarity** [comment]
> As I mentioned above, these measure different things, so it is expected they come to different answers

I don't see how that's true from a user's perspective. If this code does different things, that seems like a flaw in the macro implementation?

At the very least, it sounds like some documentation is in order?

**Comment by nsajko** [comment]
There are three separate inconsistencies reported in this discussion:

1. allocation profiler vs `@allocated`
2. `Float64` vs `Int`
3. calling `@profile` from global scope vs from a function

I guess that if the first one is somehow not-a-bug, separate issues should be opened for (2) and (3)?

**Comment by vtjnash** [comment]
None of those sound like bugs, but if you must, allocation is a feature not a bug. If anything though, they all undercount drastically, since they only count realized, new allocations on a particular heap, and fail to account for utilization of registers or stack for memory

**Comment by topolarity** [comment]
Is there any reason we shouldn't simply add `@force_compile` to the `Profile.Allocs.@profile` macro?

```julia
julia> begin
           Base.Experimental.@force_compile()
           Profile.Allocs.@profile sample_rate=1 sin(1.5)
       end
0.9974949866040544

julia> length(Profile.Allocs.fetch().allocs)
0
```

This seems to be the primary difference in the implementation of `@timed` / `@allocated`.

**Comment by vtjnash** [comment]
It makes it a bit more magical, which may make them a bit less accurate
