### ISSUE TITLE
CalledProcessError when installing diffeqtorch 

### ISSUE THREAD

**Issue by Silentmoonlight** [JuliaLang/julia#52044]
Using
julia version 1.7.2
Python 3.8.0
when I try to install diffeqtorch by using python -c "from diffeqtorch.install import install_and_test; install_and_test()",something is wrong
Test Julia dependencies
Traceback (most recent call last):
File "", line 1, in
File "/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/install.py", line 25, in install_and_test
test_julia_deps()
File "/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/install.py", line 45, in test_julia_deps
output = subprocess.run(
File "/home/zjh/anaconda/envs/py38/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'export JULIA_PROJECT=/home/zjh/anaconda/envs/py38/lib/python3.8/site-packages/diffeqtorch/julia; julia -E 'using DifferentialEquations'' returned non-zero exit status 1.

I wonder how can I fix it.

and here is the output of versioninfo()
versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, icelake-server)
Environment:
  JULIA_SYSIMAGE_DIFFEQTORCH = /home/zjh/.julia_sysimage_diffeqtorch.so
```[tasklist]
### Tasks
```

**Comment by PallHaraldsson** [comment]
This seems to belong in Julia discourse, if not even some Python (project) discussion forum.

Note there's official SciML:
https://github.com/SciML/diffeqpy

that may work for your. I'm not sure if diffeqtorch is to do same or similar, but it seems like an unofficial project, and possibly harder to set up.

Also you should be using a supported version of Julia e.g. 1.9, though likely older should work. But I'm not sure about that.
