### ISSUE TITLE
QA with a large csv dataset

### ISSUE THREAD

**Issue by Akshat111111** [JuliaLang/julia#52057]
Hey there, I was using a sizable CSV dataset for my QA job.
I'm using create_csv_agent in conjunction with a local llm model (llama2). 

Furthermore, in response to my question, "count the total number of rows in the dataset." It also produced an incorrect output.

How can this be resolved?

**Comment by jishnub** [comment]
Is this an issue with a specific package, or with Julia? In the former case, please file an issue with the package. In the latter, please provide a minimal code example and the incorrect output that you obtain.

**Comment by Akshat111111** [comment]
Thankyou so much for your response,As I am facing the issue with the specific package, and will file the issue with the package accordingly.
