### ISSUE TITLE
Can we skip writing the key into a `Dict` if we know it's already present?

### ISSUE THREAD

**Issue by Zentrik** [JuliaLang/julia#52066]
https://github.com/JuliaLang/julia/blob/e7345b89fd4eb15e8f395395701e19be705d7b06/base/dict.jl#L404-L417

ht_keyindex2_shorthash!` only returns `index > 0` if
https://github.com/JuliaLang/julia/blob/e7345b89fd4eb15e8f395395701e19be705d7b06/base/dict.jl#L326

As `isequal(x,y)` implies `hash(x) == hash(y)` and the `Dict` docs say 'Keys are compared with isequal and hashed with hash', seems like it should be fine to skip the `h.keys[index] = key`.

**Comment by Zentrik** [comment]
The `dict` testsuite passes if I remove this write and a couple of similar ones.

**Comment by vtjnash** [comment]
we should add a test though, if that is lacking
```
julia> d = Dict(); d[1] = 'a'; d[1.0] = 'b'; only(d) === Pair{Any,Any}(1.0, 'b')
true
```
