### ISSUE TITLE
Using `include_dependency` with a non-existent file triggers precompilation at every startup

### ISSUE THREAD

**Issue by longqian95** [JuliaLang/julia#52063]
found this issue after v1.9. no problems at v1.4

**Comment by vchuravy** [comment]
`include_dependency` should probably error if the file doesn't exist.

**Comment by KristofferC** [comment]
Unless you want to recompile something if a file start to existing I guess... But feels kind of strange. At least it shouldn't recompile if the file continues to not exist heh.
