### ISSUE TITLE
Revolutionizing Julia Debugging: Unlocking Entry Points Efficiency

### ISSUE THREAD

**Issue by AndyAndDevid** [JuliaLang/julia#52126]
Debugging in Julia can be significantly enhanced, particularly in dealing with large codebases, through the introduction of entry points.

When debugging extensive Julia code, the compiled mode proves to be practically useful due to its speed and freedom from conflicts with libraries. In contrast, the non-compiled mode easily becomes impractical due to its slow performance or potential library conflicts.

However, a notable drawback of the compiled mode is that it ignores breakpoints within sub-functions. Consequently, users are required to manually navigate through the code until the relevant subfunction is reached.

When repeatedly debugging functions at a deep level, the current approach involves placing breakpoints at all calling functions, necessitating multiple manual step-ins and step-outs to reach the desired section of code. This significantly disrupts the debugging flow and makes it challenging to maintain focus on the specific problem at hand.

Consider this idea: instead of manually stepping in and out at every level, why not let the Julia Debugger handle it automatically? If, instead of setting red breakpoints at all calling functions, users could designate orange entrance points, the debugger could identify these entry points and execute step-ins and step-outs automatically until the first red breakpoint is encountered.

Introducing this feature would greatly enhance the debugging experience, providing a more streamlined and focused approach to identifying and resolving issues in the code.

**Comment by vtjnash** [comment]
This seems like gpt spam

**Comment by vchuravy** [comment]
@AndyAndDevid if this was a well-intentioned issue, the correct issue tracker for Debugger.jl is https://github.com/JuliaDebug/Debugger.jl

**Comment by AndyAndDevid** [comment]
Thank you for reconsidering my issue. Yes this is a well-intentioned issue
and I see in it a really important step for the improvement of Julia. Maybe
you have recognized it as gpt spam, because I let gpt correct and put my
english in an easily understandable form, since I'm not native and I valued
clear communication to be very important.

Best regards
Andrea Deflorio

Am Sa., 11. Nov. 2023 um 17:12 Uhr schrieb Valentin Churavy <
***@***.***>:
