### ISSUE TITLE
could not download https://pkg.julialang.org/registries

### ISSUE THREAD

**Issue by raman-maker** [JuliaLang/julia#52142]
```julia
begin
    import Pkg
    # activate a temporary environment
    Pkg.activate(mktempdir())
    Pkg.add([
        Pkg.PackageSpec(name="SimpleWeightedGraphs", rev="master"),
		Pkg.PackageSpec(name="GraphRecipes"),Pkg.PackageSpec(name="NetworkLayout"),Pkg.PackageSpec(name="HypertextLiteral")])
    using Graphs,GraphRecipes ,SimpleWeightedGraphs,NetworkLayout,Colors, HypertextLiteral,PlutoUI
end
```

### **When i run above script in Julia-1.10 , i get following error :**

```
could not download https://pkg.julialang.org/registries

exception
Downloads.RequestError
url

"https://pkg.julialang.org/registries"

code

28

message

"SSL connection timeout"

response
Downloads.Response
proto

"https"

url

"https://pkg.julialang.org/registries"

status

0

message

""

headers
Pair{String, String}
```

**Comment by fredrikekre** [comment]
The discourse forum is probably better suited to debug this, see https://discourse.julialang.org/.

Can you visit https://pkg.julialang.org/registries in your browser? Does it work in the Julia REPL (instead of Pluto environment)?

**Comment by raman-maker** [comment]
Now last error get solved automatically , it is fine . but saying that :- UndefVarError: `@drawsvg` not defined for next part of code.

**Comment by StefanKarpinski** [comment]
Sounds like you have a permission issue with your `~/.ssh` directory. 
Please ask questions on the [Julia discourse](https://discourse.julialang.org/) discussion forum.
