### ISSUE TITLE
ci: allunique test failure in Random

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#52156]
```


Random                                          (11) \|         failed at 2023-11-13T09:34:58.235
--
  | Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-grannysmith-C07ZQ07RJYVY.0/build/default-grannysmith-C07ZQ07RJYVY-0/julialang/julia-master/julia-edf60945ae/share/julia/stdlib/v1.11/Random/test/runtests.jl:20
  | Expression: allunique(xs)

```

https://buildkite.com/julialang/julia-master/builds/30035#018bc95a-3428-4b6a-9b16-3e8304a89514

**Comment by Keno** [comment]
I think the easiest explanation is that we underestimated the birthday probability for this test. It's pretty easy to get this test to fail:
```
function foo()
           mt = MersenneTwister(rand(UInt128))
           B = Vector{Float32}(undef, 31)
           while true; global i; i += 1
               rand!(mt, B)
               test_uniform(B)
           end
       end
```
Fails on average about once every 20k steps. Our buildkite CI so far has round about 30k jobs, each with 14 testers, so about  420k total executions of this test (plus the other one that has the same pattern, but a shorter buffer, so a lower birthday probability), so we'd expect to see this failure about ~21 times in all our logs if that's the explanation. Let me see if that checks out.

**Comment by rfourquet** [comment]
Yes I confirm your analysis; it would be great to design better tests for uniform distributions, but in the meantime, #52165 ~might be good enough (allow one collision)~ might end up being good enough with another fix
