### ISSUE TITLE
some Julia packages are not updating to the latest versions in Julia 1.9.3.

### ISSUE THREAD

**Issue by ay111** [JuliaLang/julia#52155]
After updating packages in Julia 1.9.3 (Juliaup for windows), some packages do not update to the latest version. For instance the latest SymPy version is 1.20 whereas the version on my laptop is 1.1.8 as shown below. Please how can I upgrade it.

 [24249f21] SymPy v1.1.8
Info Packages marked with ⌃ have new versions available and may be upgradable.

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.
