### ISSUE TITLE
Invalid precompile statement referencing `GenericMemory`

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#52175]
I'm not sure which function this was actually coming from, but our service in production running with `--trace-compile` produces the following two precompile statements referencing "GenericMemory," which is of course undefined in Main:
```julia
precompile(Tuple{Type{GenericMemory{:not_atomic, String, Core.AddrSpace{Core}(0x00)}}, UndefInitializer, Int64})
precompile(Tuple{Base.var"#119#120"{Array{Type, 1}, Int64, Int64, Int64, Int64, GenericMemory{:not_atomic, Type, Core.AddrSpace{Core}(0x00)}}})
```

Any ideas what this is coming from? We're running Julia v1.9.2. I don't see any reference to `GenericMemory` in the julia codebase on either v1.9 or master.

Related:
- https://github.com/JuliaLang/julia/issues/38902
- https://github.com/JuliaLang/julia/issues/28808

**Comment by NHDaly** [comment]
Could it be related to this somehow?:
https://github.com/JuliaLang/julia/blob/651aef941efedd2efbc816ca277832ca75ea81f6/src/llvm-codegen-shared.h#L17

**Comment by oscardssmith** [comment]
`GenericMemory` is from https://github.com/JuliaLang/julia/pull/51319 It's not in 1.9 but it is in master.

**Comment by vchuravy** [comment]
Yeah double check your `versioninfo` that looks like nightly xD

**Comment by NHDaly** [comment]
Closing this as can't reproduce; maybe i was doing something wrong in my setup - i don't remember now. Thanks all
