### ISSUE TITLE
InteractiveUtils test sometimes causes CI failure

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#52216]
[Recent CI failure](https://buildkite.com/julialang/julia-master/builds/30216#018bde1b-33ce-4c8f-a638-9053fe977bcb/780-1280)
```
Error in testset InteractiveUtils:
--
  | Test Failed at /cache/build/tester-amdci4-13/julialang/julia-master/julia-234a7586c3/share/julia/stdlib/v1.11/InteractiveUtils/test/runtests.jl:232
  | Expression: #= /cache/build/tester-amdci4-13/julialang/julia-master/julia-234a7586c3/share/julia/stdlib/v1.11/InteractiveUtils/test/runtests.jl:232 =# @allocated(varinfo(Tmp14173)) < if MEMDEBUG
  | 300000
  | else
  | 100000
  | end
  | Evaluated: 100352 < 100000
```

Test added in [#36107](https://github.com/JuliaLang/julia/pull/36107) cc @vtjnash

Fails intermittently and only on `x86_64-linux-gnuassertrr`

**Comment by vtjnash** [comment]
I thought I just increased the allowable allocs there, but anyways, we should just increase it by 50% again

**Comment by Zentrik** [comment]
This test behaves in a weird way as the reported number of allocations seems to depends on whether the test uses a `<` or a `==`.

**Comment by LilithHafner** [comment]
If the response to a test failure is to increase the limit, should we just remove the limit?

**Comment by vtjnash** [comment]
The limit is to measure that it is not significantly unbounded memory relative to the thing it is measuring. As the measured thing grows, sometimes we need to increase the test
