### ISSUE TITLE
Add more precisely named methods for obtaining elements of Pair

### ISSUE THREAD

**Issue by KeithWM** [JuliaLang/julia#52231]
Not sure how this suggestion will be received, but I too am greedy.

I often find that legibility of Julia code (both my own and that of others) is not helped by the fact that the two elements of a `Pair` struct are obtained using the `first` and `last` methods as if `Pair` were just a short `Tuple` or `Vector`. Especially in the common situation of having a `Vector{Pair}` this can lead to an unnecessary burden on the reader. 

As an example, I would say that 
````julia
julia> pairvec = ["a"=>2, "b"=>4, "c"=>3]
3-element Vector{Pair{String, Int64}}:
 "a" => 2
 "b" => 4
 "c" => 3

julia> ordered = sort(pairvec, by=last)
3-element Vector{Pair{String, Int64}}:
 "a" => 2
 "c" => 3
 "b" => 4

julia> best = ordered |> last |> first
"b"
````
would be much much easier to read if it were
````julia
julia> pairvec = ["a"=>2, "b"=>4, "c"=>3]
3-element Vector{Pair{String, Int64}}:
 "a" => 2
 "b" => 4
 "c" => 3

julia> ordered = sort(pairvec, by=right)
3-element Vector{Pair{String, Int64}}:
 "a" => 2
 "c" => 3
 "b" => 4

julia> best = ordered |> last |> left
"b"
````
or some other choice of words that reflected that a pair has only two sides, e.g. from & to, source & target, or the terrible ab & ad.

**Comment by LilithHafner** [comment]
This reminds me of `only`, but is useful significantly less frequently. This seems like a design decision that triage might have something to say about. I lean toward not implementing this because folks can write `first(x::Pair)` or `last(x::Pair)` if they know and want to clarify that `x` is a `Pair`.

**Comment by KeithWM** [comment]
> This reminds me of `only`, but is useful significantly less frequently. This seems like a design decision that triage might have something to say about. I lean toward not implementing this because folks can write `first(x::Pair)` or `last(x::Pair)` if they know and want to clarify that `x` is a `Pair`.

That is at least a nice tip to improve readability.

**Comment by mbauman** [comment]
What about `keys` and `values`?  It is, of course, the singular case but we do that sort of thing in many places.  Only wrinkle is that `values(::Pair)` currently falls back to `values(itr) = itr`.

**Comment by LilithHafner** [comment]
IMO this is definitely not worth making a breaking change for.

**Comment by KeithWM** [comment]
> IMO this is definitely not worth making a breaking change for.

Of course not, but couldn't this be done with a non-breaking change?

**Comment by StefanKarpinski** [comment]
Thank you for summarizing, @LilithHafner! The less terse version is this:

- Everyone agrees that `first` and `last` aren't the most obvious names for the key and value of a pair
- There don't seem to be obviously correct names, however
- Nobody's crazy about "left" and "right"
- Using "key" and "value" was discussed but seem like very common names to use just for this
- Someone suggested "car" and "cdr" 😄 

Ultimately, even though `first` and `last` are a little awkward, they work, they're general and they already exist. It seems like too much to add new exported generic functions that are *just* for pairs when there already exist more general functions that do exactly what's needed.

**Comment by KeithWM** [comment]
Thanks for this reponse. Understandable decision. I'm very glad it got such a serious consideration.
