### ISSUE TITLE
[REPL] Confusing completion when using up arrow and TAB

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#52264]
Imagine this REPL session with Julia `master`, `|` represents the position of the cursor
```julia
using Linea|
# Now press up arrow to recall previous item in the history starting with `using Linea`
# This is completed to...
using Linea|rAlgebra
# Now press TAB
using LinearAlgebra|
# Now press TAB again
using LinearAlgebra|rAlgebra
```
Ideally last TAB shouldn't do anything, as the cursor is already at the end of the line and there's nothing to complete there.

In Julia v1.9, after pressing the up arrow the TAB key completes
```julia
using Linea|rAlgebra
```
to
```julia
using LinearAlgebra|rAlgebra
```
which makes sense because you're basically completing `using Linea`, but the behaviour on `master` is much more counterintuitive because pressing TAB the first time moves the cursor at the end of the line, so another TAB shouldn't do anything at that point.

**Comment by AshlinHarris** [comment]
Replacing that final TAB press with almost any keypress (left or right arrow, ENTER, any number or letter) produces a similar bug.

**Comment by AshlinHarris** [comment]
This could be an effect of the Tab completion hints. Resetting [that commit](https://github.com/JuliaLang/julia/commit/ce5fa71cc14ad6df5e7906ba376e50b03814b302) restored the previous behavior.

**Comment by Liozou** [comment]
Instead of reverting the entire commit, it is sufficient to remove the following line:
```diff
diff --git a/stdlib/REPL/src/LineEdit.jl b/stdlib/REPL/src/LineEdit.jl
index 709eeaa285..c20d90e7c5 100644
--- a/stdlib/REPL/src/LineEdit.jl
+++ b/stdlib/REPL/src/LineEdit.jl
@@ -482,7 +482,6 @@ function maybe_show_hint(s::PromptState)
     # The hint being "" then nothing is used to first clear a previous hint, then skip printing the hint
     # the clear line cannot be printed each time because it breaks column movement
     if isempty(s.hint)
-        print(terminal(s), "\e[0K") # clear remainder of line which had a hint
         s.hint = nothing
     else
         Base.printstyled(terminal(s), s.hint, color=:light_black)
```
However, I don't have a clear idea what was the intent behind that line originally, so removing it may not be a good idea... And I can't manage to add a proper test that works after the fix but not before. @IanButterworth, sorry for the second ping on that issue but do you have any hint regarding this?

**Comment by IanButterworth** [comment]
I think all of this would be fixed from a UX perspective by turning off tab completion when you're in the middle of an entry..

Like, it doesn't make any sense to me that pressing tab here
```
using Linea|rAlgebra
```
turns into
```
using LinearAlgebra|rAlgebra
```

So just disable tab completion when not at the end of an entry? Or is there some valid reason to keep it?

**Comment by KristofferC** [comment]
I guess one possible improvement is if you are at

```
"foo|bar
```

and pressing tab would complete to `"foobarxxx` then "absorbing the `bar` in that tab complete would feel natural so after that tab you have `"foobarxxx|` (instead of `foobarxxx|bar`.

**Comment by iagobaapellaniz** [comment]
I think if one presses UP to recall used entries, the cursor should be placed at the end of the prompts.

Would that fix the bug?

**Comment by IanButterworth** [comment]
That makes sense for one up press but doesn't for more than that because it would need to then complete the full entry from the first up

**Comment by iagobaapellaniz** [comment]
When the prompt is empty, and one presses the key up several times, it does place the cursor at the end of the prompt always. Maybe partial entries and empty ones should behave similarly. The REPL could place the cursor at the end remembering which part has been inserted by hand.
