### ISSUE TITLE
No `Base.Checked.checked_pow` function

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#52262]
There are a bunch of checked arithmetic functions that throw an OverflowError on overflow.

There isn't currently a `checked_pow` which implements `^` with the OverflowError check. Can we add one?

I think it would delegate to `Base.checked_mul` in its while-loop, rather than how `power_by_squaring` currently calls `*`. Something like:
```julia
function checked_power_by_squaring(x_, p::Integer)
...
    elseif p == 2
        return Base.checked_mul(x, x)
...
    while (t -= 1) > 0
        x = Base.checked_mul(x, x)
    end
...
end
```
etc

**Comment by PallHaraldsson** [comment]
Your Base.Checked.checked_pow should exist, at least under some name, but I'm thinking, could it replace ^ (and pow) at some point? And the old definition go to Base.unchecked_pow

Before the PR is merged and committing to that name, could a PkgEval be done to simply see if any know code relies on modular current definition, if your definition replaces it?

It would be tempting to add unchecked for those that want (could be done right now, to ease migration, if needed), I'm just thinking even it might not be needed.
