### ISSUE TITLE
Redundant suggestion printed on an `UndefVarError` on nightly

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#52273]
```julia
julia> a
ERROR: UndefVarError: `a` not defined in `Main`
Suggestion: check for spelling errors or missing imports. No global of this name exists in this module.
```
The suggestion text "No global of this name exists in this module" appears to repeat the error message "`a` not defined in `Main`", and in less-obvious language. It's also not a suggestion, but an observation.

Versioninfo:
```julia
julia> versioninfo()
Julia Version 1.11.0-DEV.958
Commit a6c656e6c47 (2023-11-21 21:06 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/lib/x86_64-linux-gnu/gtk-3.0/modules
  JULIA_EDITOR = subl
```

**Comment by vtjnash** [comment]
Formally speaking, the message is telling you that there is also no `global a` declaration anywhere, as opposed to the first text that is just telling you `!isdefined(Main, :a)`, so it is the error message that is the repeat of the suggestion, not the reverse.

**Comment by jishnub** [comment]
This distinction seems quite technical, and wasn't obvious to me despite being relatively familiar with Julia. I wonder if the framing might be improved? Also, perhaps the observation should precede the suggestion to avoid it being seen as a part of the solution. As a non-native speaker, "No global of this name exists in the module. Suggestion: check for spelling errors or missing imports" sounds clearer.
