### ISSUE TITLE
1.10.0-rc1: cannot build packages with `using InteractiveUtils` in `startup.jl`

### ISSUE THREAD

**Issue by matthias314** [JuliaLang/julia#52283]
This came up in the context of [IJulia](https://github.com/JuliaLang/IJulia.jl/issues/1097). @stevengj suggested to post it on [Discourse](https://discourse.julialang.org/t/cannot-build-packages-with-julia-1-10-0-rc1-without-disabling-startup-jl/105878), where I didn't get any replies. I have the feeling that this is a regression in 1.10.0-rc1. Maybe I'm wrong, but I want to mention it to be on the safe side.

Take a fresh install of 1.10.0-rc1 with no `~/.julia`. Then create `~/.julia/config/startup.jl` with the line
```
using InteractiveUtils
```
Now start `julia`, switch to the package manager and try to add any package that has a build script. I get:
```
(@v1.10) pkg> st
  Installing known registries into `~/.julia`
Status `~/.julia/environments/v1.10/Project.toml` (empty project)
(@v1.10) pkg> add IJulia
[... lines omitted ...]
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/51cab8e982c5b598eea9c8ceaced4b58d9dd37c9/build.log`
ERROR: Error building `Conda`: 
ERROR: LoadError: ArgumentError: Package InteractiveUtils not found in current path.
- Run `import Pkg; Pkg.add("InteractiveUtils")` to install the InteractiveUtils package.
Stacktrace:
 [1] macro expansion
   @ Base ./loading.jl:1766 [inlined]
 [2] macro expansion
   @ Base ./lock.jl:267 [inlined]
 [3] __require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1747
 [4] #invoke_in_world#3
   @ Base ./essentials.jl:921 [inlined]
 [5] invoke_in_world
   @ Base ./essentials.jl:918 [inlined]
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1740
in expression starting at ~/.julia/config/startup.jl:1
```
Same for Gurobi.jl. The problem disappears if I start Julia with `--startup-file=no`. With master (nightly 2023-11-22) I get the same error. With 1.9.3 the building completes without problems, regardless of whether the startup file is read or not.

**Comment by giordano** [comment]
I'm just guessing this line https://github.com/JuliaLang/Pkg.jl/blob/7013c105f4d539d0a618c25e05e67674369c8502/src/Operations.jl#L1031 should include `--startup-file=no`, which is enforced at https://github.com/JuliaLang/Pkg.jl/blob/7013c105f4d539d0a618c25e05e67674369c8502/src/Operations.jl#L716 but not at https://github.com/JuliaLang/Pkg.jl/blob/7013c105f4d539d0a618c25e05e67674369c8502/src/Operations.jl#L1139.

**Comment by fredrikekre** [comment]
Fixed by https://github.com/JuliaLang/Pkg.jl/pull/3699 I think?
