### ISSUE TITLE
Iterative construction of lazy Iterators leads to excessive compilation time

### ISSUE THREAD

**Issue by cao-** [JuliaLang/julia#52295]
I'm not sure if what I'm going to show is an issue to be addressed, or something that I should expect to happen, but for sure I didn't expect it.
I wanted to write an iterator that lazily traverses a graph in breadth first search order, where the graph is defined implicitly by a function giving for each vertex an iterable over the adjacent vertices.  This is what I wrote:
```julia
struct ImplicitGraph
        adj::Function
end

struct TraversalBFS{T}
        graph::ImplicitGraph
        start::T
end

G = ImplicitGraph(v -> (v - 1, v + 1))

t = TraversalBFS(G, 0)

function Base.iterate(t::TraversalBFS{T}, state=((t.start,), Set{T}())) where {T}
        queue, visited = state                                                         
        p = Iterators.dropwhile(w -> w ∈ visited, queue) |> Iterators.peel
        p === nothing && return nothing
        v, to_visit = p
        push!(visited, v)                                                                   
        return v, (Iterators.flatten((to_visit, t.graph.adj(v))), visited)
end

for v in t
        print(v)
end
```
The problem is that this code runs at a ridiculous speed:  it seems like the code is constantly being compiled.
Even if the above shown algorithm may not be the best way to achieve what I wanted, it is a perfectly reasonable algorithm.  As a comparison, I wrote an analogous version using Python.
```python
import itertools

t = { 'adj': lambda v: (v-1, v+1), 'start': 0 }

initial_state = ((t['start'],), set())

def iterate(t, state):
    queue, visited = state
    to_visit = itertools.dropwhile(lambda w: w in visited, queue)
    v = next(to_visit, None)
    if v is None:
        return None
    visited.add(v)
    return v, (itertools.chain.from_iterable((to_visit, t['adj'](v))), visited)

v, state = iterate(t, initial_state)
print(v)
while True:
    v, state = iterate(t, state)
    print(v)
```
As you can see, this code runs fast.

So, what is going on with the Julia code?  Why is it behaving like this?  Is it possible to avoid the constant compilation and let the code run like it does in Python?

**Comment by vchuravy** [comment]
So the core problem here is that `Iterators` uses lazy data-structures that become ever more complex:

```
julia> iterate(t)
(0, (Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}, Tuple{Int64, Int64}}}((Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}(Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}(var"#7#8"{Set{Int64}}(Set([0])), (0,)), 2), (-1, 1))), Set([0])))

julia> iterate(t, ans[2])
(-1, (Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}, Tuple{Int64, Int64}}}, var"#7#8"{Set{Int64}}}, Tuple{Int64, Tuple{Int64, Int64}, Int64}}, Tuple{Int64, Int64}}}((Base.Iterators.Rest{Base.Iterators.DropWhile{Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}, Tuple{Int64, Int64}}}, var"#7#8"{Set{Int64}}}, Tuple{Int64, Tuple{Int64, Int64}, Int64}}(Base.Iterators.DropWhile{Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}, Tuple{Int64, Int64}}}, var"#7#8"{Set{Int64}}}(var"#7#8"{Set{Int64}}(Set([0, -1])), Base.Iterators.Flatten{Tuple{Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}, Tuple{Int64, Int64}}}((Base.Iterators.Rest{Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}, Int64}(Base.Iterators.DropWhile{Tuple{Int64}, var"#7#8"{Set{Int64}}}(var"#7#8"{Set{Int64}}(Set([0, -1])), (0,)), 2), (-1, 1)))), (3, (-1, 1), 2)), (-2, 0))), Set([0, -1])))
```

So every iteration the type-tree grows and grows and Julia overspecializes on these data-structures.

We can stop this kind of growth:

```
function Base.iterate(t::TraversalBFS{T}, state=((t.start,), Set{T}())) where {T}
        queue, visited = state                                                         
        p = Iterators.dropwhile(w -> w ∈ visited, queue) |> Iterators.peel
        p === nothing && return nothing
        v, to_visit = p
        to_visit = collect(to_visit)
        push!(visited, v)                                                                   
        return v, (Iterators.flatten((to_visit, t.graph.adj(v))), visited)
end
```

For this kind of usage question please consider using `https://discourse.julialang.org` first.

**Comment by cao-** [comment]
Ok, thanks for the answer, and sorry but I didn't know about `https://discourse.julialang.org`.
Anyhow, your proposed solution doesn't solve the problem, because the algorithm is not lazy anymore when you collect the nodes to visit (for instance if a vertex has an infinite number of neighbours this modified algorithm stops trying to collect all neighbours).
In Python I can do that, while in Julia I cannot.  It seems to mean that in Julia we cannot implement such kind of algorithms, which according to me is an issue to be addressed, if there is not already a solution.  For instance, is it possible to avoid building up the more and more complex type?  Is it possible to avoid compilation and run it like in interpreted mode?  If, anyhow, this needs to be continued on `https://discourse.julialang.org`, please let me know.

**Comment by vchuravy** [comment]
Yes please open a conversation on discourse. This is not quite a bug, but rather a design limitation of Base.Iterators and one could implement an iterator library with different design tradeoffs. It would be slower in other circumstances
