### ISSUE TITLE
Use libdivide

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#52301]
It claims to be much faster than the assembly division instructions.

I think it's only for integer division (and could apply for mod etc. too.)

https://github.com/ridiculousfish/libdivide

Currently I see rather large code, and three conditional jumps before idiv (or div):
```
@code_native div(1, 2)
```

The code IS shorter for `@code_native div(UInt32(1), UInt32(2))` thus the gain maybe not as large. In both cases I'm not sure if all this code is inlined or should be. For libdivide maybe it should NOT be, by default. Could be up to the compiler to inline or not (or a keyword argument?). If NOT inlined might also help surrounding code indirectly be faster.

**Comment by Keno** [comment]
The re-used divisor case is implemented in Base.MultiplicativeInverses for explicit use. LLVM also knows about this and will optimize appropriately.

**Comment by StefanKarpinski** [comment]
Tangentially related, we just added `invmod(n)` functionality for very efficiently computing modular inverses in native integer rings: https://github.com/JuliaLang/julia/pull/52180.
