### ISSUE TITLE
Threads.@threads doesn't play nicely with Iterators.product

### ISSUE THREAD

**Issue by RJDennis** [JuliaLang/julia#52343]
Should we expect the following to error?

```
Threads.@threads for i in Iterators.product(1:3,1:2)
  println(i)
end
```

**Comment by mcabbott** [comment]
While a normal for loop just iterates over the set, the threaded one has to be able to index it. At present that's not defined for `ProductIterator`, but it wouldn't be crazy to enable it.

See e.g.  https://github.com/JuliaLang/julia/issues/48745 for discussion about indexing `Generator` (where there's a concern about side-effects).

**Comment by Seelengrab** [comment]
I think this could be solved with https://github.com/JuliaLang/julia/pull/52096

**Comment by Seelengrab** [comment]
With 1.11/#52096, the `:greedy` scheduler option can now handle this:

```
julia> Threads.@threads :greedy for i in Iterators.product(1:3,1:2)
         println(i)
       end
(2, 1)
(3, 1)
(1, 2)
(3, 2)
(1, 1)
(2, 2)
```

Does this solve the issue?

**Comment by RJDennis** [comment]
Yes it does, thanks.
