### ISSUE TITLE
Axes for transposed OffsetArray vector incorrect due to LinearAlgebra method

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#52373]
Incorrect axes returned for a transposed OffsetArray vector. This causes incorrect image filtering results for kernels passed as vector components.

See: https://github.com/JuliaImages/ImageFiltering.jl/issues/269

```
using ImageFiltering
using OffsetArrays

a = centered(zeros(3))'
b = centered(zeros(3)')

axes(a)
# (Base.OneTo(1), OffsetArrays.IdOffsetRange(values=-1:1, indices=-1:1))
# axes(v::Union{LinearAlgebra.Adjoint{T, var"#s972"}, LinearAlgebra.Transpose{T, var"#s972"}} where {T, var"#s972"<:(AbstractVector)}) in LinearAlgebra at src/adjtrans.jl:298

axes(b)
# (OffsetArrays.IdOffsetRange(values=0:0, indices=0:0), OffsetArrays.IdOffsetRange(values=-1:1, indices=-1:1))
# axes(A::OffsetArrays.OffsetArray) in OffsetArrays at src/OffsetArrays.jl:295
```

(lines based on 1.9 but still present in 1.10)

https://github.com/JuliaLang/julia/blame/8e5136fa2979885081cd502d2210633dff1d2a1a/stdlib/LinearAlgebra/src/adjtrans.jl#L298

**Comment by jishnub** [comment]
Looks ok to me? What was the result that you were expecting?
```julia
julia> axes(zeros(3))
(Base.OneTo(3),)

julia> axes(centered(zeros(3))) # shift midpoint to zero
(OffsetArrays.IdOffsetRange(values=-1:1, indices=-1:1),)

julia> axes(centered(zeros(3))') # new axis added by the transpose is not centered about zero
(Base.OneTo(1), OffsetArrays.IdOffsetRange(values=-1:1, indices=-1:1))

julia> axes(zeros(3)')
(Base.OneTo(1), Base.OneTo(3))

julia> axes(centered(zeros(3)')) # both axes are not centered about zero
(OffsetArrays.IdOffsetRange(values=0:0, indices=0:0), OffsetArrays.IdOffsetRange(values=-1:1, indices=-1:1))
```

**Comment by BioTurboNick** [comment]
With respect, I think my post is clear in what I expected: The new first dimension should inherit the offset of the parent.

The error in Base though is assuming that the first axis of a transposed vector should always be 1-indexed.

However, I see this is a multi-level issue. Because OffsetArrays assumes all later dimensions start at 1, and would just provide `OffsetArrays.IdOffsetRange(values=1:1, indices=1:1)` as the axis when asked. I'll take up the matter of that default though with OffsetArrays.

**Comment by jishnub** [comment]
I apologize for my brusque tone, but this was not what I had intended. I'll make a PR to change the hard-coded axis to use that of the parent instead.

**Comment by BioTurboNick** [comment]
No worries, and thanks!
