### ISSUE TITLE
mul! performance regression for sparse matrices in v1.11.0-DEV.1035

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#52429]
We have noticed that one of the tests in [MixedModels.jl](https://github.com/JuliaStats/MixedModels.jl) has had a dramatic increase in execution time in recent DEV versions (locally compiled on an Mac M1 but the same performance regression is seen on Intel-based computers.)   The test is called `grouseticks`.

A big part of the problem seems to be a performance regression in `mul!` when C is a sparse matrix, A is a sparse matrix and B is the transpose of a sparse matrix.   A MWE is

```julia
using BenchmarkTools, LinearAlgebra, SparseArrays

Is = repeat(1:10; inner=200);
Js = repeat(1:100; inner=20);
Ks = repeat(1:1000; inner=2);
V = ones(2000);
A = sparse(Is, Ks, V);
B = sparse(Js, Ks, V);
C = sparse(Is, Js, V);

@benchmark mul!(c, a, b', -0.001, 1.0) seconds=1 setup=(a=A; b=B; c=C))
```

Under 1.10.0-rc2 the benchmark on my M1 laptop runs in around 0.5 ms and under 1.11.0-DEV.1035 it takes about 8 ms

**Comment by giordano** [comment]
Probably due to the excision of SparseArrays from the sysimage?

**Comment by dmbates** [comment]
I believe it is due to a change in algorithm for the function `_generic_matmatmul!` defined in `LinearAlgebra/src/matmul.jl`.  When profiling a similar calculation the majority of the time under 1.11.0-DEV is spent in that function and the time spent in this function is much greater than that under 1.10.0-rc2 and earlier versions.

**Comment by dkarrasch** [comment]
The major refactoring (for significantly reduced load times of SparseArrays.jl) happened in v1.10, I'm not even sure we've had any major merged PRs in SparseArrays.jl in the v1.11 cycle. In that mentioned refactoring, the underlying multiplication algorithms have remained untouched, it's only the dispatch that might have changed, but if it has, that was clearly not the intention.

**Comment by dkarrasch** [comment]
Perhaps we should move the tiling-based algorithm to SparseArrays.jl? It performed worse than what we have now for strided arrays with generic and/or mixed eltypes. So the real benefit of it seems to be in locally densifying sparse arrays.
