### ISSUE TITLE
Heapsnapshot has some unrooted objects

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#52432]
The heapsnapshots seem to be missing either some edges or maybe some roots, or maybe both, but somehow many objects end up not retained by any roots, which is of course nonsense, since they couldn't have been exported if they're not reachable from a root (since unrooted things are garbage).

You can see that in this simple repro:
```julia
julia> using Profile

julia> Profile.take_heap_snapshot("1.11.0-DEV.638.heapsnapshot")
"1.11.0-DEV.638.heapsnapshot"
```
[1.11.0-DEV.638.heapsnapshot.zip](https://github.com/JuliaLang/julia/files/13592248/1.11.0-DEV.638.heapsnapshot.zip)

You can see in the screenshot that the roots are only retaining 87% of the heap snapshot. (in another attempt, i got only 5,000 bytes out of 120 MB!)
<img width="1220" alt="Screenshot 2023-12-06 at 3 25 50 PM" src="https://github.com/JuliaLang/julia/assets/1582097/634cb6db-d865-4026-ab3f-1769a68505c7">

And you can see here that one random object has retainers that don't terminate in a root:

<img width="1213" alt="Screenshot 2023-12-06 at 3 27 57 PM" src="https://github.com/JuliaLang/julia/assets/1582097/d5653d65-6dcc-497e-9b80-a8290643ee10">

From randomly clicking around so far, it seems to often be Arrays that aren't parented, and so i wonder if we're missing some edge somewhere for arrays?

**Comment by NHDaly** [comment]
(@JianFangAtRai from RAI is going to look into this this month.)

**Comment by IanButterworth** [comment]
vscode [just added](https://code.visualstudio.com/updates/v1_85#_javascript-debugger) a built-in `.heapsnapshot` viewer which looks to have an interesting graph viewer. However open julia-generated `.heapsnapshot` files just spins without any indication why (while I confirmed that chrome generated ones loaded).

Perhaps this issue is related?

**Comment by JianFangAtRai** [comment]
> vscode [just added](https://code.visualstudio.com/updates/v1_85#_javascript-debugger) a built-in `.heapsnapshot` viewer which looks to have an interesting graph viewer. However trying to open a julia-generated `.heapsnapshot` file just spins without any indication why (I found that chrome generated ones load immediately).
> 
> Perhaps this issue is related?

Are the sizes of the two files equal or close? Could the file size be an issue here?

**Comment by IanButterworth** [comment]
https://github.com/JuliaLang/julia/pull/52618 didn't fix the vscode viewer hang unfortnately

File sizes:
- from a fresh julia session: 175 MB (hangs indefinitely)
- from a chrome webpage: 5 MB (renders instantly)

**Comment by NHDaly** [comment]
Seems worth looking into. Thanks for the report, Ian! Can you please move
this into a separate ticket so we can track it even after Jian's PR closes
this issue?

Maybe we should also open a ticket on the VSCode repo with one of the
snapshot files, since Chrome can load it just fine?

Thanks!

**Comment by IanButterworth** [comment]
Will do. So https://github.com/JuliaLang/julia/pull/52618 should have closed this issue?

**Comment by NHDaly** [comment]
I think so, yeah! 👍 Lemme add that to the PR description.

**Comment by NHDaly** [comment]
Ah, @JianFangAtRai even already had it in PR description already:

> This PR is to fix the issue: https://github.com/JuliaLang/julia/issues/52432

I think it just didn't get picked up by GitHub's automations. Closing this ticket now. Thanks again Jian!
