### ISSUE TITLE
`include()`'ing nonexistant file now gives misleading "can only hash files" error

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#52462]
If a package has an incorrect `include()`, it used to throw an error like this:

```
$ cat src/Example.jl | head
module Example
export hello, domath

include("this_is_nonexistant.jl")

"""
    hello(who::String)

Return "Hello, `who`".
"""
$ julia +1.9 --project -e 'using Example' 2>&1 | head -1
ERROR: LoadError: SystemError: opening file "/Users/sabae/.julia/dev/Example/src/this_is_nonexistant.jl": No such file or directory
```

Whereas:
```
$ julia +master --project -e 'using Example' 2>&1 | head -1
ERROR: LoadError: AssertionError: can only hash files
```

This appears to have changed as of https://github.com/JuliaLang/julia/commit/f2df1b41b85843120a9715449eb5ff555a4a172d

**Comment by staticfloat** [comment]
@fatteneder pinging you since you were the author of the linked commit.

**Comment by fatteneder** [comment]
This PR https://github.com/JuliaLang/julia/pull/51798/files already contains a fix.
If needed one can extract the fix into a separate PR. Let me know.

**Comment by fatteneder** [comment]
Although, that fix would now throw an error when including a non-existent directory, e.g.
```
julia> include("/asdf")
ERROR: IOError: readdir("/asdf"): no such file or directory (ENOENT)
```

Previously, one could just include non-existent directories and julia would not do anything.
I guess this behavior should be preserved.

**Comment by staticfloat** [comment]
Okay, sounds good! I am content to wait until that PR is merged!
