### ISSUE TITLE
Method ambiguity error shows irrelevant methods

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#52469]
This example was originally reported in https://github.com/JuliaLang/julia/issues/52386: some methods shown in the MethodError are clearly less specific than others and are irrelevant for the error itself.

Can/should it only show methods that actually constitute the ambiguity?

```julia
julia> using AxisKeys

julia> vcat(KeyedArray([1,2], x=[:a,:b]), KeyedArray([3], x=[:c]))
# 1.10-rc result (current release 1.9 works without errors):
ERROR: MethodError: vcat(::KeyedArray{Int64, 1, NamedDimsArray{(:x,), Int64, 1, Vector{Int64}}, Base.RefValue{Vector{Symbol}}}, ::KeyedArray{Int64, 1, NamedDimsArray{(:x,), Int64, 1, Vector{Int64}}, Base.RefValue{Vector{Symbol}}}) is ambiguous.

Candidates:
  vcat(A::Union{KeyedArray{T, 1, AT, RT}, KeyedArray{T, 2, AT, RT}} where {T, AT, RT}, B::Union{KeyedArray{T, 1, AT, RT}, KeyedArray{T, 2, AT, RT}} where {T, AT, RT}, Cs::AbstractVecOrMat...)
    @ AxisKeys ~/.julia/packages/AxisKeys/QsNqy/src/functions.jl:147
  vcat(X1::Union{Number, AbstractVecOrMat{<:Number}}, X::Union{Number, AbstractVecOrMat{<:Number}}...)
    @ SparseArrays ~/.julia/juliaup/julia-1.10.0-rc2+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:1235
  vcat(A::Union{KeyedArray{T, 1, AT, RT}, KeyedArray{T, 2, AT, RT}} where {T, AT, RT}, B::AbstractVecOrMat, Cs::AbstractVecOrMat...)
    @ AxisKeys ~/.julia/packages/AxisKeys/QsNqy/src/functions.jl:147
  vcat(A::AbstractVecOrMat, B::Union{KeyedArray{T, 1, AT, RT}, KeyedArray{T, 2, AT, RT}} where {T, AT, RT}, Cs::AbstractVecOrMat...)
    @ AxisKeys ~/.julia/packages/AxisKeys/QsNqy/src/functions.jl:147
  vcat(V::AbstractVector...)
    @ Base abstractarray.jl:1620
  vcat(A::AbstractVecOrMat{T}...) where T
    @ Base abstractarray.jl:1691
  vcat(V::AbstractVector{T}...) where T
    @ Base abstractarray.jl:1621

Possible fix, define
  vcat(::KeyedArray{T, 1}, ::KeyedArray{T, 1}, ::Vararg{AbstractVector{T}}) where T<:Number
```

**Comment by vtjnash** [comment]
I think this code calls `methods` and then does some similarity scoring. But calling `methods_including_ambiguous` first would probably be a better list to use for this (if that list is non-empty)

**Comment by lgoettgens** [comment]
> I think this code calls `methods` and then does some similarity scoring. But calling `methods_including_ambiguous` first would probably be a better list to use for this (if that list is non-empty)

This is already called and the result is passed to `showerror_ambiguous`, see
https://github.com/JuliaLang/julia/blob/456951fbbb0d47e45f49dd7942d5f7571831c049/base/errorshow.jl#L252-L255
Furthermore, there is a test that checks the existence of these "irrelevant" methods in the error message, see the third line in
https://github.com/JuliaLang/julia/blob/456951fbbb0d47e45f49dd7942d5f7571831c049/test/ambiguous.jl#L43-L46

**Comment by vtjnash** [comment]
That one is not unrelated though, since even if you deleted the second one, the first and third would still be ambiguous

**Comment by lgoettgens** [comment]
Just as a note: The current printing has been introduced in https://github.com/JuliaLang/julia/pull/32776.

So you would define an "irrelevant method" as one that does not constitute any ambiguities with all of the other methods?

**Comment by vtjnash** [comment]
That is what OP asked for as relevant:

> Can/should it only show methods that actually constitute the ambiguity?

**Comment by lgoettgens** [comment]
As `methods_including_ambiguous` returns these irrelevant methods, I would consider this a bug in `methods_including_ambiguous`, right?

**Comment by vtjnash** [comment]
Well, they are indeed ambiguous, so it is a bit ambiguous what it would mean to call them irrelevant to include when explicitly asked to return a list of ambiguities

**Comment by vtjnash** [comment]
It may be worth noting that "less specific than the others" implies the OP thinks of this as a total order predicate. It is not a total ordering predicate, so such a statement is not as clearly defined in such a situation.

**Comment by vtjnash** [comment]
> there's a "pareto front"

Again, this is a notion that is from your assumption of total order, and does not hold here. Such a "pareto front" is not present in a partial order, such as is being printed here. Your example indeed shows this, as the methods are sorted (in the absence of ambiguities) from most specific to least--and yet as you pointed out, the method you thought should the most specific is the last one among the ambiguities detected. You can almost recover a total ordering from subtyping, but not entirely and there are counter-examples in the tests.

**Comment by vtjnash** [comment]
Sorry, yes, I meant to write it is not a partial order either. Just a general cyclic graph.

**Comment by vtjnash** [comment]
Yes, your provided example itself appears to such a cycle. You can tell because the possible fix would have had to be different if those were not included--thus not irrelevant. You may want to try building the n*n matrix of `morespecific` for those entries above to see for yourself

**Comment by vtjnash** [comment]
It looks like #1 is ambiguous with 2,3,4, so they are all in the same SCC cycle. There is no transitive order to morespecific, so having 2 be morespecific than 4 is not relevant to computing the list of ambiguities
