### ISSUE TITLE
Increased allocation count in `sort(rand(1000))`

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#52493]
1.10-rc2

```julia
julia> @btime sort(x) setup=(x=rand(1000));
  10.250 μs (3 allocations: 18.06 KiB)
```

master (067e02e5775b8588e753489a19786e7a3bee447c)

```julia
julia> @btime sort(x) setup=(x=rand(1000));
  10.542 μs (9 allocations: 17.88 KiB)
```

This example alone isn't a big deal, but 3=>9 allocations should be easily bistable and maybe there's an actual performance regression nearby. I'm writing this down so we don't forget about it.

**Comment by oscardssmith** [comment]
My guess is that this is the `Memory` PR.

**Comment by vtjnash** [comment]
Yes, `sort` probably wants to take advantage now of the option to use fixed size Memory instead of the more powerful Array for its internal buffer
