### ISSUE TITLE
Do less for non-interactive; e.g. not run startup.jl or OpenBLAS

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#52532]
I've brought up this issue about startup.jl before but @KristofferC objected.

With @mkitti's idea and PR for a separate interactive sysimage, I think this could be done, and if people prefer that startup.jl is run then they could make such a sysimage.

Or just use a julia alias.

I think parsing it may be a security threat, or even if not, then very unnatural, and confusing to get different (or same!) behavior when you compile to an app.

Plan B could be a local startup.jl file in your current directory, or same as where your .jl file is located, or something? That's looked for first, then the global one? Maybe it only look for for non-interactive.

Also I thought can OpenBLAS NOT be loaded by default (generic matmul would work, is already implemented)? It would not break API. If we start having different <s>behavior</s> performance for interactive then it could be loaded then, or Julia could provide a default startup.jl file that does it for you.

Not loading it would be very helpful for smaller compiled apps (and smaller RAM use), and if you want it you could do `using OpenBLAS` or maybe have it implied with `using LinearAlgebra`.

**Comment by mkitti** [comment]
I'm a bit confused on the objective here.

1) We should not rely on a default startup.jl. If there is a need for user configuration here, it probably should be in a declarative configuration or via a command line switch.
2) If we wanted to load Pkg.jl eagerly in interactive mode, then we should just do that in client.jl right after we load the REPL. My current recommendation there involves `Threads.@thread @eval using Pkg`, but I find this a bit unreliable.
3) Localized configuration could be arranged by the user via startup.jl perhaps with the assistance of a package.
4) It's already possible to unload OpenBLAS by buliding a custom system image and perhaps a few additional stepps.

The main thrust of #52482 is porting the code that determines if we are running interactively from Julia (after the system image is loaded) to C (before the system image is loaded) so we might abe able to use the `isinteractive` state to choose which system image to load.

**Comment by PallHaraldsson** [comment]
I didn't mention Pkg, and I'm focusing on the default for non-interactive (what can be done without your PR, so I guess I confused you). I know your PR is mainly for Pkg loading, I meant what the title says, do less, but if you want to do more, when interactive, then it could be done with a different system image (assuming your PR gets merged).

**Comment by PallHaraldsson** [comment]
At least there precedent here, in Pluto to NOT run the startup file (by default):
https://github.com/kirill-kondrashov/Pluto.jl/blob/b8a58fe0ae4f0d9bddbe87dec4e242cfae8b73b2/src/Configuration.jl#L238

**Comment by vtjnash** [comment]
There is not a specific actionable item here. We generally do, over time, delete `__init__` methods and remove packages from the stdlib, so that less unnecessary work is deferred until required.

**Comment by PallHaraldsson** [comment]
>There is not a specific actionable item here.

Sure there is. Not read the startup.jl file; unless for non-interactive. That simple change alone would be great! Those that want it (I doubt most do) e.g. @KristofferC could run with a non-default interactive sysimage, and it could load it by default.

>We generally do, over time, delete __init__ methods and remove packages

I'm not sure what that refers to, I guess e.g. not load OpenBLAS (I actually don't want it loaded interactive or not, until `using LinearAlgebra`), ok that could be a separate issue, I think you mean will not be done, at least before the feature freeze.
