### ISSUE TITLE
Print a warning after `using Foo: bar` if `bar` is not public API

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaLang/julia#52553]
Now that #50105 has been merged, can we print a warning after `using Foo: bar` if `bar` is not marked with either `export` or `public`? Is adding a warning where there was none before considered a breaking change?

Having a warning would address one of the concerns in #42080, which is that encouraging `using Foo: bar` is likely to lead to folks bringing internal names into scope.

**Comment by KristofferC** [comment]
Discussion here can probably be folded into https://github.com/JuliaLang/julia/issues/52314.
