### ISSUE TITLE
Error in NEWS.md of Julia 1.10-rc2

### ISSUE THREAD

**Issue by ufechner7** [JuliaLang/julia#52563]
In the file https://github.com/JuliaLang/julia/blob/backports-release-1.10/NEWS.md the following information is wrong:

```
Updated GC heuristics to count allocated pages instead of object sizes (https://github.com/JuliaLang/julia/issues/50144). This should help some programs that consumed excessive memory before.
```
To the best of my knowledge this patch was reverted.

**Comment by KristofferC** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/52622/commits/3fd8baea1e39db58654f29a784b1ecbc3c3f6c50

**Comment by ufechner7** [comment]
Thank you!
