### ISSUE TITLE
2.0: Reconsider `Pairs` iteration/getindex API?

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#52576]
In 1.9,

```jl
julia> first(pairs([10,20,30]))
1 => 10

julia> pairs([10,20,30])[1]
10
```

apparently because `first` makes an iterator of pairs and `getindex` makes a dictlike of pairs. I find this complicated. Maybe there is another design possible, perhaps inspired by Dictionaries.jl.

**Comment by mbauman** [comment]
I think this is a specific case of the more wholistic https://github.com/JuliaLang/julia/issues/24019.
