### ISSUE TITLE
Wrongly named inner constructor doesn't error

### ISSUE THREAD

**Issue by Tortar** [JuliaLang/julia#52580]
This doesn't error in 1.9.4 and 1.10rc-2:

```julia
julia> struct A
           x::Int
           B(x) = new(x)
       end
```

but it should, right?

**Comment by nsajko** [comment]
This is as expected. `B` is a function internal to `A`, if `A` had an inner constructor, `B` could be used (as a helper) from the constructor.

Perhaps there should be a warning when a type with no constructors is created?

**Comment by StefanKarpinski** [comment]
Some kind of linter could check if there's no way to construct a type, but it's valid to make a type that can't be constructed and there are cases where a type isn't constructed through the type object but through some global function declared inside of the type block instead.

**Comment by Keno** [comment]
As mentioned, not a bug, but yeah, there could be some sort of linter pass for `new` that are is reachable from publicly namable methods. Not a trivial analysis though.
