### ISSUE TITLE
`digits!` in reverse order

### ISSUE THREAD

**Issue by jamblejoe** [JuliaLang/julia#52628]
I'd like a version of `digits!` which returns the digits in reverse order. Consider the following example:
```
julia> i = 10^6
1000000
julia> v = zeros(Int, ndigits(i))
julia> @btime digits!($v, $i, base=2)
  14.654 ns (0 allocations: 0 bytes)
7-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 1

julia> @btime reverse!(digits!($v, $i, base=2))
  19.349 ns (0 allocations: 0 bytes)
7-element Vector{Int64}:
 1
 0
 0
 0
 0
 0
 0
```

Instead of `reverse!(digits!(...))` why not have an additional argument `reverse=true` for `digits!`. I am mainly interested in this feature to avoid the additional overhead of calling `reverse!` after `digits!`.

**Comment by StefanKarpinski** [comment]
You can create a reversed view of the original array to do this.

**Comment by jamblejoe** [comment]
@StefanKarpinski thank you very much! How do I do this? Thank you in advance!

**Comment by nsajko** [comment]
@jamblejoe you can ask on the Julia Discourse. Create a topic here: https://discourse.julialang.org/

**Comment by oscardssmith** [comment]
Note that if you want to efficiently operate on the base 2 digits of an `Int`, you can just operate on the bits directly. This will generally be much more efficient, so I don't think there is much point in hyper-optimizing `digits` related functions as they should pretty much never be needed/wanted in performance sensitive applications.

**Comment by itseffi** [comment]
using BenchmarkTools: 

```
# Assuming i and v are already defined as in the example:
i = 10^6  # 1000000
v = zeros(Int, ndigits(i))
```

```
# Modify the digits! function to return the digits in reverse order
@btime reverse!(view(digits!($v, $i, base=2), :))
```

**Comment by StefanKarpinski** [comment]
Ah I don’t even notice the base 2 part. Yeah, the answer then is don’t use digits! at all.
