### ISSUE TITLE
pathological cases for partialsort are untested

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#52642]
Can be reproduced with:
```julia
for _ in 1:10000
    for i in [223:227, 632:635, 614:620, 658:665, 500:501]
        x = rand(1:5, 1000)
        partialsort(x, i, lt=(<=)) == sort(x)[i] || error()
    end
end
```

These incorrect answers are allowed by the documentation. However I didn't expect them so they may or may not reflect a correctness bug when passed valid pathological inputs and warrants further investigation.

**Comment by KristofferC** [comment]
It's a bit unclear here so for posterity, what has to he done in order to close this issue?

**Comment by LilithHafner** [comment]
When I added this test, I expected it to pass reliably. I was wrong. Perhaps I was wrong in thinking the test would pass despite invalid lt, perhaps I was wrong in that I implemented a bug in the algorithm this tests. To close this issue we should identify my error.

So it turns out that in the presence of this invalid lt ordering, when both signpost values are equal, we end up with a situation where elements are both less than the lower sign post and greater than the higher signpost (because of the violation of areflexivity). These elements are counted both as a part of the middle and as below the middle, leading to incorrect answers (though not segfaults, as far as I can tell, because those incorrect answers, when out of bounds, result in marking the bracketing attempt as a failure so the results are discarded).

Removing the tests as written is appropriate. However, this will leave the pathological input case untested. Constructing a fully pathological input is designed to be extremely difficult, but I'll try.

**Comment by LilithHafner** [comment]
I went ahead and removed the flakey test. However we should still add a new test that passes reliably and tests pathological input handling. I have no reason to suspect that the algorithm is buggy at this time as there is a satisfactory explanation for why the tests were flakey but it should still be tested. Leaving this issue open until we add tests that pass in pathological inputs.
