### ISSUE TITLE
Scoped values segfault in StyledStrings.jl CI

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/julia#52672]
The StyledStrings.jl CI has started failing (ref: https://github.com/JuliaLang/StyledStrings.jl/actions/runs/7347912158/job/20039095028), with a segfault that seems to come from scoped values (julia nightly).

```
[1866] signal 11 (1): Segmentation fault
in expression starting at /home/runner/work/StyledStrings.jl/StyledStrings.jl/src/precompile.jl:39
get at ./scopedvalues.jl:112 [inlined]
getindex at ./scopedvalues.jl:128 [inlined]
mergedface at /home/runner/work/StyledStrings.jl/StyledStrings.jl/src/faces.jl:495
MappingRF at ./reduce.jl:100 [inlined]
```

I am unable to reproduce this error locally, but re-running CI this error persists.

Taking a peek at the lines involved, `Core.current_scope()` seems like the likely source of the segfault, but I don't know this part of the code base well enough to say more. I'm guessing this could have arisen in some of the scoped values optimisations that have been happening recently?

**Comment by Keno** [comment]
I'm also having trouble reproducing this locally. Does anybody have any sense what's different on that particular CI?

**Comment by Keno** [comment]
Ok, I can reproduce this if I check out the github actions repo locally and delete my `~/.julia/compiled`:

```
COVERAGE=true ANNOTATE=false CHECK_BOUNDS=yes GITHUB_ACTIONS=true FORCE_LATEST_COMPATIBLE_VERSION=auto ~/julia/julia --color=yes --depwarn=yes --inline=yes --project=@. -e 'include(joinpath("/home/keno/julia-runtest", "test_harness.jl"))'
```

**Comment by Keno** [comment]
```
_foldl_impl(Base.FilteringRF{StyledStrings.var"#8#10", Base.MappingRF{StyledStrings.var"#7#9", Base.MappingRF{StyledStrings.var"#mergedface#6", Base.BottomRF{typeof(Base.merge)}}}}, Base._InitialValue, Array{Pair{Symbol, Any}, 1}) from _foldl_impl(OP, Any, Any) where {OP}
```
Is the miscompiled function

**Comment by Keno** [comment]
```
#0  0x00007f446ac69c6a in julia_withfaces_5626 (f=..., keyvals...=...) at /home/keno/.julia/dev/StyledStrings/src/faces.jl:433
433	    @with(FACES.current => newfaces, f())
(rr) p $rdx
$22 = 0
```

current_scope is being set to NULL for some reason

**Comment by Keno** [comment]
```
  store {} addrspace(10)* undef, {} addrspace(10)** %current_scope, align 8, !dbg !154, !tbaa !47, !alias.scope !172, !noalias !173
```
