### ISSUE TITLE
StackOverflow for `dot(::Float64, ::Char)`

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#52673]
```jl
julia> dot(1.1, 'a')
ERROR: StackOverflowError:
Stacktrace:
 [1] dot(x::Float64, y::Char) (repeats 79984 times)
```

Julia 1.10 official

**Comment by jishnub** [comment]
Possibly duplicate of #35654, and the solution proposed in
https://github.com/JuliaLang/julia/issues/35654#issuecomment-621930856
may be the best fix
