### ISSUE TITLE
Artifacts stdlib manual does not document all exported functions

### ISSUE THREAD

**Issue by SamuraiAku** [JuliaLang/julia#52688]
The Artifacts stdlib exports the following functions:

- artifact_exists
- artifact_path
- artifact_meta
- artifact_hash
- select_downloadable_artifacts
- find_artifacts_toml
- @artifact_str

But there is only [documentation](https://docs.julialang.org/en/v1.10/stdlib/Artifacts/) for
- artifact_meta
- artifact_hash
- find_artifacts_toml
- @artifact_str

Since the other functions are exported, they are presumably part of the public API. In the Pkg documentation there is [example code](https://pkgdocs.julialang.org/v1/artifacts/) that uses all of these functions but the function documentation is missing.

I would request that the missing functions be added to the Artifacts documentation page.

**Comment by inkydragon** [comment]
> Since the other functions are exported

Artifacts.jl came from Pkg.Artifacts. (#37320)
It used to be a submodule.
So maybe the functions should not be exported? @staticfloat 

https://github.com/JuliaLang/Pkg.jl/blob/3c86ba27e904807e13beb8cb0466ed70365b0b2d/src/Artifacts.jl#L16-L19

**Comment by SamuraiAku** [comment]
The Pkg documentation uses these functions in example code in such a way that it implies these functions are part of the API. 

FYI, I am using select_downloadable_artifacts in a recent release of PkgToSoftwareBOM.jl and I would anticipate using artifacts_exists and artifact_path in the future.

**Comment by nsajko** [comment]
Seems to duplicate issue #31202. Also related: #19529, #51335.

**Comment by stevengj** [comment]
To be clear, these functions have docstrings, they are just not included in the manual (#19529).

The only public symbol in Artifacts that is currently missing a docstring is the `Artifacts` module itself.
