### ISSUE TITLE
IO information statement after successful precompilation

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#52685]
I updated to 1.10 and noticed that a warning(?) is printed after precompiling a package extension: With a fresh depot, I see the following:
```julia
julia> import Pkg; Pkg.add(["Polymake", "Hecke"]); using Polymake, Hecke;
[...]
Precompiling project...
  71 dependencies successfully precompiled in 113 seconds
  1 dependency had output during precompilation:
┌ Hecke → PolymakeExt
│  [pid 43163] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x600002616c00->0x10d7cc5e0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 43163] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   timer              0x600002616c00->0x10d7cc5e0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└
```
Everything works fine afterwards, but why do I get this scary looking warning if everything was successfully precompiled? I am also not sure what to do with this warning. I believe I am not doing any fancy IO stuff in `Hecke → PolymakeExt`, just some ordinary method overloading.

This is a regression, since on 1.9 everything is working as expected (no warning).

Version:
```julia
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_DEPOT_PATH = /var/folders/vw/fn8vgctd5bv0llw3_fnmrdz00000gn/T/tmp.HUocLdw3Y0
```

**Comment by IanButterworth** [comment]
>  I am also not sure what to do with this warning

Note "See the developer documentation on fixing precompilation hangs for more help" which is directing you to https://docs.julialang.org/en/v1/devdocs/precompile_hang/

This messaging is definitely more internal looking/scary than it needs to be. There's been a lot of discussion about that

**Comment by thofma** [comment]
Yes, I saw that hint after everything "succesfully precompiled" (as printed in the terminal). Sorry for my naive question, but why print the warning if everything was successful?

**Comment by thofma** [comment]
I identified the dependency which causes this (https://github.com/oscar-system/Polymake.jl/). But the dependency runs the recommended [Aqua](https://juliatesting.github.io/Aqua.jl/dev/#Aqua.test_persistent_tasks-Tuple{Base.PkgId}) check and it passes:
```
  Persistent tasks                           |    1      1   6.4s
```
(https://github.com/oscar-system/Polymake.jl/actions/runs/7379376449/job/20075564999?pr=466#step:7:217)

"Fixing" it with `call(:jl_generating_output, Cint, ()) == 1 && return nothing` is not an option because of https://github.com/JuliaLang/julia/pull/50914#issuecomment-1714559096.

I am happy to hear that we are doing something wrong, but I am not sure where to look for the problem.

**Comment by vtjnash** [comment]
The warning here is that Downloads sleeps for 30 seconds after finishing, so precompile takes 30 seconds longer than it should

**Comment by thofma** [comment]
dup

**Comment by IanButterworth** [comment]
Looks like it isn't fixed https://github.com/JuliaLang/Downloads.jl/issues/223

**Comment by IanButterworth** [comment]
This will be fixed on master once Downloads.jl is bumped here https://github.com/JuliaLang/julia/pull/52885

But the warning still shows on 1.10 because https://github.com/JuliaLang/julia/pull/52445 hasn't been backported

**Comment by newptcai** [comment]
I got this warning when I installed Makie.
