### ISSUE TITLE
Error showing value of type `StepRangeLen{ComplexF64, Base.TwicePrecision{ComplexF64}, Base.TwicePrecision{Float64}, Int64}`

### ISSUE THREAD

**Issue by olof3** [JuliaLang/julia#52713]
On nightly,

```
julia> v = 0.1*(1:5) .+ im
Error showing value of type StepRangeLen{ComplexF64, Base.TwicePrecision{ComplexF64}, Base.TwicePrecision{Float64}, Int64}:        
ERROR: MethodError: no method matching zero(::Base.TwicePrecision{Float64})
```

Edit: an almost identical :) `StepRangeLen` is mentioned here https://github.com/JuliaLang/julia/issues/49589#issuecomment-1533132727, but no mention about problems with `show`.

**Comment by lgoettgens** [comment]
As mentioned by @pablosanjose in https://github.com/JuliaLang/julia/issues/53588, this worked in 1.9.0, but fails in 1.9.1
