### ISSUE TITLE
Show more of the type where arguments don't match in `MethodError`

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#52740]
The new type simplification is great but it isn't really "context aware"

In this example the key information about what causes the method error is lost due to type symplification with `...`.

I really want to know what is in `Val{...}`:

```julia
julia> DynamicGrids.descendable(sd)
ERROR: MethodError: no method matching _demo(::DynamicGrids.Descend, ::DynamicGrids.RuleData{…}, ::SetNeighbors{…}, ::Val{…})

Closest candidates are:
  _demo(::DynamicGrids.DemoMode, ::DynamicGrids.RuleData{<:Any, N}, ::Any, ::Val{<:CellRule}) where N
   @ DynamicGrids ~/.julia/dev/DynamicGrids/src/utils.jl:72
  _demo(::DynamicGrids.DemoMode, ::DynamicGrids.RuleData{<:Any, N}, ::Any, ::Val{<:SetCellRule}) where N
   @ DynamicGrids ~/.julia/dev/DynamicGrids/src/utils.jl:87
  _demo(::DynamicGrids.DemoMode, ::DynamicGrids.RuleData{<:Any, N}, ::Any, ::Val{<:Union{var"#s106", var"#s105"} where {var"#s106"<:NeighborhoodRule, var"#s105"<:(Chain{<:Any, <:Any, <:Tuple{var"#s101", Vara
rg} where var"#s101"<:NeighborhoodRule})}}) where N
   @ DynamicGrids ~/.julia/dev/DynamicGrids/src/utils.jl:54
```

The problem is a little clearer in screenshot where the red highlighting of arguments is visible:

![2024-01-04-153537_1210x225](https://github.com/JuliaLang/julia/assets/2534009/392a0138-162d-49f4-84d9-9293b21df345)

Here we can't see why our arguments don't match the existing methods. We may be able to be a little smarter about this - showing more information to the point where the reason for the MethodError is clear.

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaLang/julia/issues/52113?

**Comment by rafaqz** [comment]
Yeah, couldn't find it searching issues
