### ISSUE TITLE
Make `push!=false` a syntax error

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#52753]
`push!=false` could be `push! = false` or `push != false`. Ambiguity is bad so this should potentially be an error.

```jl

julia> Meta.@dump push!=false
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol !=
    2: Symbol push
    3: Bool false
```

Julia 1.10

**Comment by kuljeet234** [comment]
In your Meta.@dump output, you can see that the expression is parsed as a function call with three arguments: the inequality operator (!=), the symbol push, and the boolean false. Therefore, it is not considered a syntax error in Julia

**Comment by mikmoore** [comment]
There is precedent for this type of restriction:
```julia-repl
julia> 1.+2
ERROR: ParseError:
1.+2
└┘ ── ambiguous `.` syntax; add whitespace to clarify (eg `1.+2` might be `1.0+2` or `1 .+ 2`)
```
Although it would still be an uphill battle to justify a breaking change like this in v1. I'm definitely a proponent of this in a breaking release, if we ever get one.

**Comment by nsajko** [comment]
Before Julia v2, perhaps it'd be nice if editors like VS code could warn against this pattern.

**Comment by nsajko** [comment]
dup of #46411
