### ISSUE TITLE
LLVM assertion failure caused by exct modeling 

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#52808]
As seen on PkgEval during testing of SLEEFPirates.jl: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-01/07/SLEEFPirates.primary.log

```
julia: /source/src/codegen.cpp:8808: jl_llvm_functions_t emit_function(llvm::orc::ThreadSafeModule&, jl_method_instance_t*, jl_code_info_t*, jl_value_t*, jl_codegen_params_t&): Assertion `jl_egal_((value), (jl_array_ptr_ref(values, j)))' failed.

[2958221] signal 6 (-6): Aborted
in expression starting at /home/maleadt/julia/wip.jl:29
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fe693e9771a)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
emit_function at /source/src/codegen.cpp:8808
jl_emit_code at /source/src/codegen.cpp:9090
jl_emit_codeinst at /source/src/codegen.cpp:9173
_jl_compile_codeinst at /source/src/jitlayers.cpp:220
jl_generate_fptr_impl at /source/src/jitlayers.cpp:525
jl_compile_method_internal at /source/src/gf.c:2493 [inlined]
jl_compile_method_internal at /source/src/gf.c:2381
_jl_invoke at /source/src/gf.c:2896 [inlined]
ijl_apply_generic at /source/src/gf.c:3086
```

MWE:

```julia
struct Double{T}
  hi::T
  lo
end
@inline function bar(::Double{V}, x::Double{V}) where V
  T = s = x.hi
  t = x
  if T <: Float64
    t = ifelse(s < 0, s, t)
  end
  0 * t
end
function foo()
  bar(Double(0,0), wat)
end
foo()
```

Bisected to #51754; cc @keno.

**Comment by oscardssmith** [comment]
I can't reproduce this on 5 day old master. Is it possibly already fixed?

**Comment by maleadt** [comment]
Are you using an assertions build?

**Comment by oscardssmith** [comment]
that would be the reason.

**Comment by gbaraldi** [comment]
So weirdly, if I do a debug `assert+llvm_assert` I get 
> Internal error: during type inference of
foo()
Encountered unexpected error in runtime:
ErrorException("")
error at ./error.jl:35
verify_ir at ./compiler/ssair/verify.jl:277
run_passes_ipo_safe at ./compiler/optimize.jl:938
run_passes_ipo_safe at ./compiler/optimize.jl:923 [inlined]
optimize at ./compiler/optimize.jl:897
jfptr_optimize_38647 at /home/gabrielbaraldi/julia5/usr/lib/julia/sys-debug.so (unknown line)
_jl_invoke at /home/gabrielbaraldi/julia5/src/gf.c:2902
ijl_apply_generic at /home/gabrielbaraldi/julia5/src/gf.c:3098
_typeinf at ./compiler/typeinfer.jl:264
typeinf at ./compiler/typeinfer.jl:216
typeinf_edge at ./compiler/typeinfer.jl:870
abstract_call_method at ./compiler/abstractinterpretation.jl:654
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:102
abstract_call_known at ./compiler/abstractinterpretation.jl:2168
abstract_call at ./compiler/abstractinterpretation.jl:2250
abstract_call at ./compiler/abstractinterpretation.jl:2243
abstract_call at ./compiler/abstractinterpretation.jl:2388
abstract_eval_call at ./compiler/abstractinterpretation.jl:2403
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2419
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2724
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3035
typeinf_local at ./compiler/abstractinterpretation.jl:3289
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3365
_typeinf at ./compiler/typeinfer.jl:246
typeinf at ./compiler/typeinfer.jl:216
typeinf_ext at ./compiler/typeinfer.jl:1042
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1080
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1076
...

**Comment by maleadt** [comment]
> So weirdly, if I do a debug `assert+llvm_assert` I get

That's not weird; IR verification is only enabled on a debug build (which defaults to `-g2`): https://github.com/JuliaLang/julia/blob/4b642035f4b3099bf26984c2914a35604c02647d/base/compiler/optimize.jl#L937-L939

**Comment by maleadt** [comment]
Fixed on master; probably by https://github.com/JuliaLang/julia/pull/52853
