### ISSUE TITLE
suboptimal subtyping for `UnionAll` and `Union`

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#52818]
```julia-repl
julia> Vector{<:Int} <: Union{Vector{Int},Vector{Union{}}}
false

julia> versioninfo()
Julia Version 1.11.0-DEV.1208
Commit b6825924aef (2024-01-06 08:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
Threads: 5 default, 0 interactive, 2 GC (on 8 virtual cores)
```

Pretty sure the above should be `true`, because the missing type parameter in the `UnionAll` may be only `Union{}` or `Int` due to the `<:Int` type constraint. Is it possible to fix it?

**Comment by nsajko** [comment]
If we have `x isa Vector{<:Int}`, it follows that either `x isa Vector{Union{}}` or `x isa Vector{Int}`, no?

**Comment by adienes** [comment]
`Vector` is not covariant so not sure that `Vector{Union{}} <: Vector{Int}` should be true (and indeed it currently evaluates to false)

**Comment by nsajko** [comment]
@adienes What you say is clearly true, but in what way does it apply here?

@vtjnash you're not being very clear. Do you mean to say that this should be labelled as a feature request?

This is my complete reasoning, in detail:

We have the `<:` doc string:

> `<:(T1, T2)`
>
> Subtype operator: returns `true` if and only if all values of type `T1` are also of type `T2`.

So, to prove `T1 <: T2`, it is enough to prove that an arbitrary value of type `T1` also belongs to `T2`. In this case, we want to prove that `x isa Vector{<:Int}` implies `x isa Union{Vector{Int},Vector{Union{}}}`. Assume there exists `x` such that `x isa Vector{<:Int}`, which [is equivalent](https://docs.julialang.org/en/v1/manual/types/#UnionAll-Types) to `x isa (Vector{T} where {T<:Int})`:

> The syntax `Array{<:Integer}` is a convenient shorthand for `Array{T} where T<:Integer`.

The REPL agrees:

```julia-repl
julia> Vector{<:Int} == (Vector{T} where {T<:Int})
true
```

There are only two types `T` which satisfy `T<:Int`: `Int` and `Union{}`, thus we have either `x isa Vector{Int}` or `x isa Vector{Union{}}`. We have both `Vector{Int} <: Union{Vector{Int},Vector{Union{}}}` and `Vector{Union{}} <: Union{Vector{Int},Vector{Union{}}}`:

```julia-repl
julia> Vector{Int} <: Union{Vector{Int},Vector{Union{}}}
true

julia> Vector{Union{}} <: Union{Vector{Int},Vector{Union{}}}
true
```

QED

**Comment by nsajko** [comment]
If there's a flaw in my reasoning, presumably a counterexample should be easy to provide?

Apart from the reasoning laid out above, I'm also looking into the *Julia Subtyping: a rational reconstruction* paper from 2018, and both subtyping implementations.

**Comment by adienes** [comment]
yeah I mean I see the logic you're going for, but it only works here since `Int` is concrete and the `Union` can be exhaustive. In the general case, `Vector{<:Integer} <: Union{Vector{Union{}}, ...}` can never be unconditionally true since there are potentially an unbounded number of subtypes `<: Integer`

so I guess the subtyping logic just isn't special-cased for the edge case of concrete types (apparently intentionally), to which I have previously encountered something similar in https://github.com/JuliaLang/julia/issues/33137

**Comment by nsajko** [comment]
If my logic above is correct, `<:` is inconsistent with its doc string, so either the docs are buggy or the behavior is buggy. If false positives and/or false negatives are unavoidable, the documentation should at least say something about that, point to rough edges, give examples, give guarantees, etc.

> I see the logic you're going for, but it only works here since `Int` is concrete and the `Union` can be exhaustive.

Well, `Int` is not the only concrete type in Julia.

**Comment by vtjnash** [comment]
> So, to prove T1 <: T2, it is enough to prove that an arbitrary value 

That is the proof of the converse, and your desired result does not follow. The type system is generally permitted to return false whenever it wants to, provided only that it preserves transitivity. None of your examples appear to violate any rules of the type system or show a bug in either the docs or implementation.

**Comment by vtjnash** [comment]
> There are only two types T which satisfy T<:Int

There is also `Int<:T<:Int` and `Union{}<:T<:Union{}` and perhaps other combinations of those. Just because you didn't know about them, or don't care about them, doesn't mean the type system is required to also ignore them existing.

**Comment by nsajko** [comment]
> That is the proof of the converse, and your desired result does not follow.

I updated the wording, but please provide a counterexample (an `x` such that `x isa Vector{<:Int}`, but not `x isa Union{Vector{Int},Vector{Union{}}}`, as per the `<:` doc string) if my proof is wrong.

> The type system is generally permitted to return false whenever it wants to, provided only that it preserves transitivity.

This is not mentioned in the `<:` doc string, provided above.

> There is also `Int<:T<:Int` and `Union{}<:T<:Union{}`

Those are already accounted for, if I understand you right, because they're identically the same as the `Union{}` and `Int`, which are considered in the above proof:

```julia-repl
julia> Union{} === (T where {T<:Union{}})
true

julia> Int === (T where {T<:Int}) === (T where {Int<:T<:Int})
true
```

> Just because you didn't know about them, or don't care about them, doesn't mean the type system is required to also ignore them existing.

Please don't take this offensively/personally/whatever, I'm just trying to help the project and understand it better.

**Comment by nsajko** [comment]
> The type system is generally permitted to return false whenever it wants to, provided only that it preserves transitivity.

Updated the issue title given this comment.

**Comment by vtjnash** [comment]
> but please provide a counterexample

The type-system doesn't care if the counterexample can't be simplified away. It only cares that there is no violation of the logic constraints mentioned. This is generally where it can return `false` when a more careful analysis seems like there are no counter-examples to stop it from returning `true`

If you poke at this more, you may also notice that the system can only consider linear combinations of `Union` matches, while a correct subtyping system would need to consider at least the full (non-finite) list of permutations of all of those Union elements. The julia subtyping paper hints at this with some of its non-terminating Union examples where they prove equivalence to system F sub.
