### ISSUE TITLE
Marking a symbol as public de-exports it

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#52812]
```julia
julia> module Foo
           export a, b
           public a
       end
Main.Foo

julia> Base.isexported(Foo, :a)
false

julia> Base.isexported(Foo, :b)
true
```

**Comment by LilithHafner** [comment]
Maybe this should error instead of being a no-op

From @fredrikekre [here](https://github.com/JuliaLang/julia/pull/52814#issuecomment-1881857527)

**Comment by JeffBezanson** [comment]
:+1: to making this an error; contradictory declarations should be cleaned up. I think we can allow duplicate declarations though, no real harm there, and it might make metaprogramming easier (you don't have to be careful to check for existing declarations before emitting something).

**Comment by IanButterworth** [comment]
Prior to seeing #53664 I thought it was valid to mark something as `public` and `export` it. I went to the docs to see if I could clarify and the [public](https://docs.julialang.org/en/v1.12-dev/base/base/#public) entry didn't mention restriction on usage in conjunction with `export`. I might be missing an explanation somewhere, but that at least seems a good place to put it/link to it.

**Comment by IanButterworth** [comment]
That's great, thanks
