### ISSUE TITLE
doc: the `UnionAll` doc string should point to the relevant Manual section

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#52822]
[This](https://docs.julialang.org/en/v1.11-dev/base/base/#Core.UnionAll) doc string should point to [this](https://docs.julialang.org/en/v1.11-dev/manual/types/#UnionAll-Types) section of the Manual.

**Comment by ViralBShah** [comment]
@nsajko Unrelated to this issue, but I have invited you to have triage permissions on julialang/julia to be able to add labels to issues/PRs etc.

**Comment by jam-khan** [comment]
@nsajko I have made a PR request that should fix the issue. I am a beginner, so would be grateful if someone points out problems in my PR, if any, as it will help me learn!

Thanks!

**Comment by nsajko** [comment]
@ViralBShah Nice, thank you. It seems I'll have to enable multi-factor authentication before I can accept, though.
