### ISSUE TITLE
Different kwargs for `code_native` shows different instructions

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#52827]
In particular, setting `debuginfo=:none, dump_module=false` shows _more_ instructions than the default options. Is this a bug?

MWE:
```julia
julia> code_native(+, Tuple{Int, Int})
        .text
        .file   "+"
        .globl  "julia_+_490"                   # -- Begin function julia_+_490
        .p2align        4, 0x90
        .type   "julia_+_490",@function
"julia_+_490":                          # @"julia_+_490"
; ┌ @ int.jl:87 within `+`
# %bb.0:                                # %top
        push    rbp
        mov     rbp, rsp
        lea     rax, [rdi + rsi]
        pop     rbp
        ret
.Lfunc_end0:
        .size   "julia_+_490", .Lfunc_end0-"julia_+_490"
; └
                                        # -- End function
        .section        ".note.GNU-stack","",@progbits

julia> code_native(+, Tuple{Int, Int}; debuginfo=:none, dump_module=false)
        .text
        push    rbp
        mov     rbp, rsp
        mov     rax, qword ptr [r13 + 16]
        mov     rax, qword ptr [rax + 16]
        mov     rax, qword ptr [rax]
        lea     rax, [rdi + rsi]
        pop     rbp
        ret
        nop     word ptr cs:[rax + rax]
```

**Comment by gbaraldi** [comment]
One is hiding the safepoint while the other isn't, though I haven't looked as to why that behaviour is like that.

**Comment by vtjnash** [comment]
dump_module=false shows the exact function being run, while dump_module=true annotates it (and removes some extraneous details like safepoints)

**Comment by jakobnissen** [comment]
This is not documented in `code_native` - it states:
> If dump_module is false, do not print metadata such as rodata or directives.

It does not state anything about `dump_module` also removing instructions. Also, it looks like `raw` has no effect - the documentation states that :
> If raw is false, uninteresting instructions (like the safepoint function prologue) are
       elided.

However, this is not the case
```julia
julia> code_native(+, Tuple{Int, Int}, dump_module=false, raw=false)
	.text
; ┌ @ int.jl:87 within `+`
	push	rbp
	mov	rbp, rsp
	mov	rax, qword ptr [r13 + 16]
	mov	rax, qword ptr [rax + 16]
	mov	rax, qword ptr [rax]
	lea	rax, [rdi + rsi]
	pop	rbp
	ret
; └
; ┌ @ int.jl:87 within `<invalid>`
	nop	word ptr cs:[rax + rax]
; └

julia> code_native(+, Tuple{Int, Int}, dump_module=false, raw=true)
	.text
; ┌ @ int.jl:87 within `+`
	push	rbp
	mov	rbp, rsp
	mov	rax, qword ptr [r13 + 16]
	mov	rax, qword ptr [rax + 16]
	mov	rax, qword ptr [rax]
	lea	rax, [rdi + rsi]
	pop	rbp
	ret
; └
; ┌ @ int.jl:87 within `<invalid>`
	nop	word ptr cs:[rax + rax]
```

**Comment by vtjnash** [comment]
True, the docs should mention that `raw=false` is only applicable to `dump_module=true`. The instructions were (optionally) removed in #49948 and the ability to further configure the output of `dump_module=true` was added in #51109. Looks like neither updated the documentation
