### ISSUE TITLE
MethodError: Cannot `convert` an object of type Dates.Time to an object of type Dates.Second

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#52839]
In Dates it would be nice if the following would work
```julia
convert(Dates.Second, Time("12:34:10", dateformat"HH:MM:SS"))
```

Currently it throws the MethodError
```
MethodError: Cannot `convert` an object of type Dates.Time to an object of type Dates.Second
```

EDIT: I couldn't find a single way how to get the Time in total amount of seconds... any help for a workaround is appreciated.

**Comment by schlichtanders** [comment]
I found at least a workaround:
```julia
julia> using Dates

julia> convert(Second, Time("12:34:10", dateformat"HH:MM:SS").instant)
45250 seconds
```
Now I am even more convinced, that Time itself should also support these convertions.

**Comment by jariji** [comment]
`Time` is a point in time; `Second` is a duration. You can add durations together but not times, so I don't want to implictly convert between these types. To get the difference from the zero point you can subtract:

```jl
julia> Time("12:34:10", dateformat"HH:MM:SS") - Time(0)
45250000000000 nanoseconds
```
