### ISSUE TITLE
Failure to properly fold foldable function calls

### ISSUE THREAD

**Issue by Dichloromethane** [JuliaLang/julia#52888]
Repeated function calls with the same argument to a pure function are not properly folded (the output is shortened a bit for readability, notice the two call instructions):

```julia
julia> f(x) = sin(x) * sin(x)
f (generic function with 1 method)

julia> @code_native f(10.)
<...snip...>
julia_f_1810:                           # @julia_f_1810
	push	rbp
	mov	rbp, rsp
	push	rbx
	sub	rsp, 24
	vmovsd	qword ptr [rbp - 16], xmm0      # 8-byte Spill
	movabs	rbx, offset j_sin_1812
	call	rbx # The first call
	vmovsd	qword ptr [rbp - 24], xmm0      # 8-byte Spill
	vmovsd	xmm0, qword ptr [rbp - 16]      # 8-byte Reload
                                        # xmm0 = mem[0],zero
	call	rbx # ...and the second
	vmulsd	xmm0, xmm0, qword ptr [rbp - 24] # 8-byte Folded Reload
	add	rsp, 24
	pop	rbx
	pop	rbp
	ret
<...snip...>
```

As repeated calls to `sin()` and `cos()` with the same arguments happen quite often in not-so-carefully written or autogenerated numerical code, optimising this seems quite important.

It also does not appear to be a problem with the definition of the `sin()` function, as the following example has the same problems:

```julia
julia> @noinline Base.@assume_effects :foldable id(x) = x
id (generic function with 1 method)

julia> f(x) = id(x) * id(x)
f (generic function with 1 method)

julia> @code_native f(1.0)
<...snip...>
julia_f_1813:                           # @julia_f_1813
	push	rbp
	mov	rbp, rsp
	push	rbx
	sub	rsp, 24
	vmovsd	qword ptr [rbp - 16], xmm0      # 8-byte Spill
	movabs	rbx, offset j_id_1815
	call	rbx # Again, the first call
	vmovsd	qword ptr [rbp - 24], xmm0      # 8-byte Spill
	vmovsd	xmm0, qword ptr [rbp - 16]      # 8-byte Reload
                                        # xmm0 = mem[0],zero
	call	rbx # ...and the second
; │┌ @ float.jl:411 within `*`
	vmulsd	xmm0, xmm0, qword ptr [rbp - 24] # 8-byte Folded Reload
; │└
	add	rsp, 24
	pop	rbx
	pop	rbp
	ret
<...snip...>
```
LLVM itself is capable of handling this, as the following small C-example proofs:

```c
__attribute__((pure)) double id(double x);

double idsq(double x) { return id(x) * id(x); }
```
is compiled to 
```
idsq:                                   # @idsq
	pushq	%rax
	callq	id@PLT
	mulsd	%xmm0, %xmm0
	popq	%rax
	retq
```

As a totally unqualified guess, might this have something to do with the failure of the constant propagation for the address of the function, which also seems to cause the more generally speaking horrible code gen in the above examples?

Information on the julia version:
```
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
Environment:
  LD_LIBRARY_PATH = :/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server:/home/dcm/lib:/usr/lib/inkscape/
```

**Comment by oscardssmith** [comment]
what you're asking for is slightly different than folding for some technical reasons. it's actually called common subexpression elimination. this should be fixed by https://github.com/JuliaLang/julia/pull/51120 and I believe is a duplicate of https://github.com/JuliaLang/julia/issues/50887

**Comment by Dichloromethane** [comment]
This appears to indeed be a duplicate. Let's hope the linked PR makes it in, because that assembly actively hurts to look at :D
