### ISSUE TITLE
Add `Lockable` to Base?

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/julia#52897]
e.g. like
```julia
struct Lockable{T, L <: Base.AbstractLock}
    value::T
    lock::L
end
Lockable(value) = Lockable(value, ReentrantLock())
Base.getindex(l::Lockable) = l.value
```
as in https://github.com/JuliaServices/ConcurrentUtilities.jl/blob/main/src/lockable.jl.

I think this could be ergonomic for use in Base since there's various bits of global state that each need a lock (e.g. https://github.com/JuliaLang/julia/issues/49778), many of which are of the form
```julia
const RESOURCE = ...
const RESOURCE_LOCK = ReentrantLock()
```
and one does `@lock(RESOURCE_LOCK, ...access RESOURCE...)`. With `Lockable`, they could be
```julia
const RESOURCE = Lockable(...)
```
and used by `@lock(RESOURCE, ...access RESOURCE[]...)`.

By grouping the resource and it's lock into a struct, it makes it slightly harder to accidentally use the resource without the lock (since one needs to index into it), and it makes it crystal clear what lock is for what resource.

**Comment by DilumAluthge** [comment]
Kind of similar to https://github.com/JuliaLang/julia/pull/34400

I don't remember why we ended up closing that one.

**Comment by ericphanson** [comment]
Ah yes, identical! 😄. I can only find one place to use this in base currently (`TEMP_CLEANUP`), although I suspect there should be more somewhere
