### ISSUE TITLE
remove lexless and lexcmp (was: behavior of cmp() on NaNs?)

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#5290]
## 1. Inconsistent logic between `lexcmp` and `nextfloat`

``` julia
julia> nextfloat(Inf)
NaN

julia> lexcmp(Inf,NaN)
ERROR: InexactError()
 in lexcmp at operators.jl:32

julia> lexcmp(Inf,Inf)
ERROR: InexactError()
 in lexcmp at operators.jl:32
```

Given the definition of `lexcmp` according to the help text, throwing an error is the right thing to do given that `>`, `==` and `<` are all supposed to be false when either operand is a `NaN` and so none of the standard return values (1, 0, -1) can be correct. However, it probably shouldn't throw an `InexactError`, but something else instead (probably `DomainError`).

In contrast, I don't see a meaningful sense in which `NaN` is the "next" number after `Inf`. The standard rule for computing with floating-point `Inf`s is to interpret it as a limit, in which case the correct result of `nextfloat(Inf)` should be `Inf` and not `NaN` (and similarly `prevfloat(-Inf)` returning `-Inf`. (Going by this rule, `lexcmp(Inf,Inf)` does correctly fail since there is a coalescence of `x<x+eps()`, `x==x+0` and `x>x-eps()` as x->`Inf`, so that there is no single limiting value.)
## 2. Inconsistent behavior of `nextfloat` and `prevfloat` at different precisions

If we take the argument in the preceding paragraph to be correct, then in the following, only `nextfloat(Inf16)` is correct:

``` julia
 julia> nextfloat(Inf) #should be Inf
NaN

julia> nextfloat(Inf32) #should be Inf32
NaN32

julia> nextfloat(Inf16) #should be Inf16
Inf16

julia> prevfloat(-Inf) #should be -Inf
NaN

julia> prevfloat(-Inf32) #should be -Inf32
NaN32

julia> prevfloat(-Inf16) #should be -Inf16
Inf16
```

**Comment by StefanKarpinski** [comment]
The `nextfloat` and `prevfloat` behavior seems to have been fixed already.

Here's one option for the comparison functions:

- `cmp` and should match `isless` behavior for floats
- `lexcmp` should match `lexless` which should use `isless` for floats

**Comment by simonbyrne** [comment]
Crazy idea
```
@enum Cmp lessthan=-1 equal=0 greaterthan=1 incomparable=7

cmp(x,y,lt=isless) = isnan(x) ||isnan(y) ? incomparable : lt(x,y) ? lessthan : lt(y,x) ? greaterthan : equal
```

**Comment by StefanKarpinski** [comment]
My premise is that this is used for sorting things, not numerical algorithms, so the `isless` behavior is the same one to use.

**Comment by vtjnash** [comment]
related? https://github.com/JuliaLang/julia/issues/9381

**Comment by simonbyrne** [comment]
Can we deprecate `cmp` in favour of `lexcmp`? Basically, is `cmp` ever used when `lexcmp` wouldn't be suitable?

**Comment by JeffBezanson** [comment]
We could also remove `lexless` and `lexcmp` completely. `lexless` has one method that calls `lexcmp`. `lexcmp` has:

- Methods for arrays. These could be `isless` instead.
- Method for `real` that's the same as the default `cmp` definition.
- Method for Complex --- this is the only one that we probably wouldn't combine with `isless` or `cmp`. We can just deprecated it; I doubt it's used much.

**Comment by StefanKarpinski** [comment]
Let's go the other direction:

- Define `isless` for arrays lexicographically (i.e. what `lexless` does), similar to tuples – there's no other sensible ordering for arrays.
- Deprecate `lexless` and `lexcmp` for arrays to `isless` and `cmp`.
- Remove `lexless` and `lexcmp` for complex numbers. Sorting is the main issue here, which can be easily expressed with `sort!(complexes, by=z->(real(z), real(im))`.
- Add a three-arg `cmp` methods taking a comparison function first, i.e. `cmp(<, x, y) = x < y ? -1 : y < x ? +1 : 0`.

**Comment by ViralBShah** [comment]
Are we doing this by feature freeze? Seems like the design is ready, but there hasn't been much work since.

**Comment by JeffBezanson** [comment]
Deprecating lexcmp and lexless is straightforward enough; do we also still want to change `cmp` to use `isless` for floats?

**Comment by JeffBezanson** [comment]
And should we also remove `LexicographicOrdering`?
