### ISSUE TITLE
Occasional GC-related assertion failures on PkgEval

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#52917]
Over the past couple of weeks, I've occasionally seen (slight variants of) the following assertion failure on PkgEval:

```
julia: /source/src/gc.c:1335: jl_gc_pool_alloc_inner: Assertion `pg->osize == p->osize' failed.

[100] signal 6 (-6): Aborted
in expression starting at /home/pkgeval/.julia/packages/PowerSpectra/uyAlC/test/test_mcm.jl:29
unknown function (ip: 0x7f570ef96d3c)
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f570ef32394)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
jl_gc_pool_alloc_inner at /source/src/gc.c:1335
jl_gc_pool_alloc_noinline at /source/src/gc.c:1386 [inlined]
jl_gc_alloc_ at /source/src/julia_internal.h:504 [inlined]
jl_gc_alloc at /source/src/gc.c:3867
_new_genericmemory_ at /source/src/genericmemory.c:80
```

Example: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-01/14/PowerSpectra.primary.log

@d-netto @gbaraldi Is this indicative of a generic memory corruption, or does this ring a bell? I haven't been able to catch it in rr.

**Comment by d-netto** [comment]
Hard to tell without a reproducer since multiple issues can lead to this (corrupted page metadata, fishy object size passed at the call-site, etc.).

**Comment by maleadt** [comment]
Yeah, I figured. I've seen it a couple of times though, so it's probably good to have an issue to link future logs on (if any).
