### ISSUE TITLE
Subscript underscore in REPL

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#52972]
I would like to request a keymap for `˱` to help indicate subscript algebra, such as `α˱ᵢ` to indicate all values of `α` with index less than `i`. The obvious choice is `\_<` and `\_>` or if those mess with the parser, then `\_lt` and `\_gt`.

If someone points me to how to add such a thing I can add it.

Best,
Miles

**Comment by inkydragon** [comment]
https://docs.julialang.org/en/v1/stdlib/REPL/#Customizing-keybindings

Or you may want to add new Unicode input completion.
https://github.com/JuliaLang/julia/blob/fb2d946b885af5d09902dd2eb3175792644730ba/stdlib/REPL/src/latex_symbols.jl#L6
