### ISSUE TITLE
Unexpected dispatch behaviour

### ISSUE THREAD

**Issue by jonschumacher** [JuliaLang/julia#52978]
As discussed in [Slack](https://julialang.slack.com/archives/C6A044SQH/p1705671677642239) I am experiencing an unexpected behaviour:

```
julia> test(x::Vector{Tc}, λ::T) where {T <: Real, Tc <: Union{T, Complex{T}}} = T
test (generic function with 1 method)

julia> test([4,5,6.0], 4.5)
Float64

julia> test([4,5,6], 4.5)
ERROR: UndefVarError: `T` not defined
Stacktrace:
 [1] test(x::Vector{Int64}, λ::Float64)
   @ Main ./REPL[1]:1
 [2] top-level scope
   @ REPL[3]:1
```

My expectation is a MethodError since the type of λ be equal to the type in the Union. My goal is to have the same type for both λ and x (or the complex counterpart). Is this intended or a bug?

```
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 256 × AMD EPYC 7763 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 383 on 256 virtual cores`
```
Installed via juliaup.

**Comment by vtjnash** [comment]
It isn't a bug, the value of `T` is `Float64<:T<:Real`. Then the value of `Tc` is constrained as `Tc <: Union{Real, Complex{Real}}}` which can be satisfied with `T=Int`. This is per the triangular rule.

**Comment by jakobnissen** [comment]
But if `T=Int`, then `Float64<:T<:Real` is incorrect. We know `T >: Float64` from the second argument.

**Comment by BioTurboNick** [comment]
And why is it possible for a method to be generated where the type parameter is undefined in the body? Surely something is wrong.

**Comment by jakobnissen** [comment]
That kind of makes sense. You could have:
```julia
julia> my_eltype(x::Union{Int, Set{T}}) where T = x isa Int ? nothing : T

julia> my_eltype(1), my_eltype(Set(1))
(nothing, Int64)
```
But then you could change it a bit to
```julia
julia> my_eltype(x::Union{Int, Set{T}}) where T = T

julia> my_eltype(Set(1))
Int64

julia> my_eltype(1)
ERROR: UndefVarError: `T` not defined
```
I.e. `T` is defined when it's passed a set, but not if it's passed an int. It would be nice if Julia was able to throw an error already on method definition, but I don't know if it's possible to know T is not defined before the method is compiled with a specific type.

**Comment by BioTurboNick** [comment]
Okay that case seems fair. Seems much more surprising to occur here, where a concrete type can be assigned to `T`.

**Comment by vtjnash** [comment]
Oh sorry, I mistyped and meant `Tc` (fixed now above). If you run `Aqua` for your test suite, this will generate a error over your code. But since it is a subtype, there is no reason to disallow calling the method, as method selection is defined only by subtyping, and not by the subsequent parameter matching. There is no concrete type that can be assigned to `T` (there is a constraint that it must be `Union{Float64,Int}<:T<:Real` in the final stage of the subtyping computation, so it needs to be any of those values in a Union, up to Real, but which one is undefined for that variable (hence the UndefVarError for that variable))
