### ISSUE TITLE
`Base.@doc` in macro doesn't work on master

### ISSUE THREAD

**Issue by Tortar** [JuliaLang/julia#52986]
As the title says this seems to be the case because in a PR on SumTypes.jl (https://github.com/MasonProtter/SumTypes.jl/pull/63/files) the doctest failing is only on nightly, while all the other works well, as you can see at https://github.com/MasonProtter/SumTypes.jl/actions/runs/7595253256/job/20687608559 the test fails with

```julia
Basics  : Test Failed at /home/runner/work/SumTypes.jl/SumTypes.jl/test/runtests.jl:40
  Expression: string(#= /home/runner/work/SumTypes.jl/SumTypes.jl/test/runtests.jl:40 =# @doc(Foo)) == "This is a Foo.\n"
   Evaluated: "nothing" == "This is a Foo.\n"
```

while for all other Julia versions it returns `"This is a Foo.\n"`.  Same is happening also on the CI of ProtoStructs.jl e.g. here https://github.com/BeastyBlacksmith/ProtoStructs.jl/actions/runs/7500520539/job/20419369109

Unfortunately I wasn't able to find a MWE when I searched for it

**Comment by vtjnash** [comment]
This is a REPL-only feature. Packages should normally be using `@ref` links, not copying the text from elsewhere. E.g.:

````
$ ./julia -E '@doc Base'
nothing
$ ./julia -E 'using REPL; @doc Base'
```
Base
```

The base library of Julia. `Base` is a module that contains basic functionality (the contents of `base/`). All modules implicitly contain `using Base`, since this is needed in the vast majority of cases.
````

**Comment by KristofferC** [comment]
This doesn't make sense to me... Why would the dkcsystem work differently if the REPL is loaded? Seems something should be moved back to Base.

**Comment by jmert** [comment]
See also #52141.

**Comment by JamesWrigley** [comment]
This also hit the Clang.jl tests. Here's a MWE:
```julia
doc_expr = (@macroexpand @doc throw)
docstring = string(@doc throw)

@show Base.hasdoc(Main, :throw)
@show doc_expr
@show docstring
```

And the output on v1.11 alpha
```bash
$ julia +1.11 --startup-file=no fake_binding.jl
Base.hasdoc(Main, :throw) = true
doc_expr = nothing
docstring = "nothing"
```

Vs 1.10.2 (without `Base.hasdoc()`):
```bash
$ julia --startup-file=no fake_binding.jl
doc_expr = :((Base.Docs.doc)((Base.Docs.Binding)(Main, :throw)))
docstring = "```\nthrow(e)\n```\n\nThrow an object as an exception.\n\nSee also: [`rethrow`](@ref), [`error`](@ref).\n"
```

It looks like the macro is returning a `nothing` value instead of an `Expr`?

**Comment by KristofferC** [comment]
One issue with this is that `@doc` gives you are markdown object, which is defined in another stdlib.

**Comment by JeffBezanson** [comment]
I think we should have `@doc x` return the un-rendered doc object, so it can still be used to duplicate doc strings without the REPL being loaded. It doesn't really matter what `@doc x` does in the REPL since most people use `?` to look up docs anyway.

**Comment by ztangent** [comment]
Noticed this a while back as well! See https://github.com/JuliaLang/Pkg.jl/issues/3650.

**Comment by ztangent** [comment]
Could I ask what the intended return value of `@doc x` is before the `REPL` module is loaded, and whether it should be equal to the value of `@doc x` after `REPL` is loaded? After testing out the nightly, I'm seeing that different values get returned. Here's a MWE:

```julia
using Test

"my function"
function foo()
    return 0
end

io = IOBuffer()
print(io, @doc foo)
docstr1 = String(take!(io))

using REPL

io = IOBuffer()
print(io, @doc foo)
docstr2 = String(take!(io))

println("docstr1 = ")
println(docstr1)

println("docstr2 = ")
println(docstr2)

@test docstr1 == docstr2
```

The resulting output is below:

```
docstr1 =
Base.Docs.DocStr(svec("my function"), nothing, Dict{Symbol, Any}(:typesig => Tuple{}, :module => Main, :linenumber => 3, :binding => foo, :path => "C:\\Users\\...\\test.jl"))
docstr2 =
my function

Test Failed at C:\Users\...\test.jl:24
  Expression: docstr1 == docstr2
   Evaluated: "Base.Docs.DocStr(svec(\"my function\"), nothing, Dict{Symbol, Any}(:typesig => Tuple{}, :module => Main, :linenumber => 3, :binding => foo, :path => \"C:\\\\Users\\\\...\\\\test.jl\"))" == "my function\n"
```

As a result, docstring tests like the one in [Gen.jl#3](https://github.com/probcomp/Gen.jl/issues/523) are still failing, and will behave differently depending on whether the test suite is run in the REPL vs. during CI (when `REPL` isn't loaded).

**Comment by KristofferC** [comment]
Having the return type change like this just because REPL is loaded or not doesn't seem great. Couldn't `@doc` always return the raw string form?

**Comment by lgoettgens** [comment]
> Having the return type change like this just because REPL is loaded or not doesn't seem great. Couldn't `@doc` always return the raw string form?

I agree and thus created https://github.com/JuliaLang/julia/issues/54664 to discuss further.

**Comment by JamesWrigley** [comment]
I don't think this is fully fixed, it's still not possible to get macro docstrings for some reason:
````shell-session
$ julia --version                                                                                                                                                                                         
julia version 1.11.0-rc2                                                                                                                                                                                                                       

$ julia --startup-file=no -E '@doc time'                                                                                                                                                                  
Base.Docs.DocStr(svec("    time(t::TmStruct) -> Float64\n\nConverts a `TmStruct` struct to a number of seconds since the epoch.\n"), nothing, Dict{Symbol, Any}(:typesig => Tuple{Base.Libc.TmStruct}, :module => Base.Libc, :linenumber => 273
, :binding => Base.Libc.time, :path => "libc.jl"))                                                                                                                                                                                             

$ julia --startup-file=no -E '@doc @time'                                                                                                                                                                 
nothing                                                                                                                                                                                                                                        

$ julia --startup-file=no -E 'using REPL; @doc @time'                                                                                                                                                                                   
```                                                                                                                                                                                                                                            
@time expr
@time "description" expr
```

A macro to execute an expression, printing the time it took to execute, the number of allocations, and the total number of bytes its execution caused to be allocated, before returning the value of the expression. Any time spent garbage collecting (gc), compiling new code, or recompiling invalidated code is shown
....
````

**Comment by Roger-luo** [comment]
It's because formatdoc is defined in Base.Docs (so you can refer the function). But the method is implemented in REPL, so you only get the render after loading REPL. This basically type piracy but I don't know what's the best way to fix it. There was a note leaving there about this when moving REPL out of Base.

**Comment by JamesWrigley** [comment]
I don't think I follow, how does that cause `@docs` to work for functions/modules etc but not for macros?

**Comment by JamesWrigley** [comment]
Bump, I think this should be re-opened.

**Comment by JamesWrigley** [comment]
(bump)

**Comment by JamesWrigley** [comment]
@KristofferC, @JeffBezanson, apologies for the direct ping but I think this isn't fully fixed yet. Could it be reopened?

**Comment by JeffBezanson** [comment]
I have a fix.

The docsystem design really has problems. For example in this case `@time` can take either one or two arguments, so those are its valid "signatures" according to the docsystem. And `@doc @time` is asking about zero arguments, so there are no matches. BUT that's the syntax for asking for help for *any* arguments, so there's a rule that you have to return all of the matches if there aren't any. I mean it kind of makes sense in terms of "helpfulness", but the way it's implemented we can't distinguish between asking for all the docs for something, and asking for something that doesn't exist like `sin` with 7 arguments.

**Comment by lgoettgens** [comment]
Does your fix, by any chance, also fix https://github.com/JuliaLang/julia/issues/52986#issuecomment-2134552358 and thus https://github.com/JuliaLang/julia/issues/54664 as well?

**Comment by JeffBezanson** [comment]
No it does not. We can think about what to do about that separately.

**Comment by KristofferC** [comment]
I think we discussed `@doc` always returning a `String` which the REPL then parses into Markdown to display.
