### ISSUE TITLE
DCE bug: unsafe elimination of dead statement, which might not terminate

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#52991]
Upon further investigation, it appears that modifying this single line is enough to remove the call to the dead `PersistentDict` constructor. But, this seems to stem from an inference bug, where we're deleting statements without actually proving `terminates`. 
```julia
julia> @noinline Base.@assume_effects :effect_free :nothrow function foo(n)
           s = 0
           while true
               if n - rand(1:10) > 0
                   s += 1
               else
                   break
               end
           end
           return s
       end^C

julia> code_typed((Int,)) do n
           foo(n)
           nothing
       end
1-element Vector{Any}:
 CodeInfo(
1 ─     return Main.nothing
) => Nothing
```
So, I'd like to address this bug first and then revisit this PR.

_Originally posted by @aviatesk in https://github.com/JuliaLang/julia/pull/52954#discussion_r1460833749_

**Comment by Keno** [comment]
Technically this is not a bug, because we currently still have forward progress guarantees, since we didn't decide on https://github.com/JuliaLang/julia/issues/40009, but I agree, it'd be good to fix this anyway.

**Comment by oscardssmith** [comment]
I added #40009 to the triage label so we can agree that this is a bug.

**Comment by Keno** [comment]
Sure. The termination modeling was added specifically to be able to make that change, so we might as well take an official call on it. We'll have to see if we need to improve it though once @aviatesk puts together the change.

**Comment by aviatesk** [comment]
Submitted a PR: #52999.
