### ISSUE TITLE
equality for iterators

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#53046]
Maybe the iterator [interface](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-iteration) should specify the behavior of [`==`](https://docs.julialang.org/en/v1/base/math/#Base.:==)? And of [`isequal`](https://docs.julialang.org/en/v1/base/base/#Base.isequal) and of [`hash`](https://docs.julialang.org/en/v1/base/base/#Base.hash), I think?

Iterator equality could be decided by [`Base.IteratorSize`](https://docs.julialang.org/en/v1/base/collections/#Base.IteratorSize) (shape, etc.), and, when appropriate, according to `length`, `size` and the values of the elements. For infinite iterators (`Base.IsInfinite()`), `==` should throw, except when the two iterators are identically equal according to `===`.

Currently some iterators, like arrays, overload `==` to provide nice behavior, while others, like `Base.Generator`, fall back to `===`.

So, I think this is nice:

```julia-repl
julia> using FlexiMaps

julia> vr = 1:3
1:3

julia> va = collect(vr)
3-element Vector{Int64}:
 1
 2
 3

julia> vf = mapview((x -> x + 1), 0:2)
3-element FlexiMaps.MappedArray{Int64, 1, var"#1#2", UnitRange{Int64}}:
 1
 2
 3

julia> vr == va
true

julia> vf == va
true
```

While this isn't:

```julia-repl
julia> a = (i for i=1:2, j=1:3);

julia> b = Iterators.map(first, Iterators.product(1:2, 1:3));

julia> c = [i for i=1:2, j=1:3];

julia> collect(a) == collect(b) == c
true

julia> a == b  # Shouldn't this be `true`? They're both `Base.Generator`, I think this is just a bug.
false

julia> c == b  # Should this be `true`?
false
```

Maybe there should be a new trait, specifying whether the new semantics for == would apply strictly?

Making the change could potentially be breaking, though I think it could be fine, depending on what PkgEval says and how the new trait (if any) gets defined.

**Comment by nsajko** [comment]
Maybe there should be a new trait, specifying whether the new semantics for `==` would apply strictly?

**Comment by Seelengrab** [comment]
This is difficult to define in general because of stateful iterators or ones with sideeffects. You really don't want to consume those.
