### ISSUE TITLE
List JuliaPackageComparisons on https://julialang.org/packages/

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaLang/julia#53068]
The resources listed under https://julialang.org/packages/ are great. Me and @hyrodium are currently working towards building up juliapackagecomparisons.github.io/, as a resource that focuses on comparisons of packages with overlapping functionality, written by humans, for humans, in more than a single sentence.

The content on the website is still a work in progress. But once all current pages have some minimum of content, would it be possible to get the resource listed on https://julialang.org/packages/? Just for reference, this would close [#2 in the JPC repo](https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/issues/2).

**Comment by nsajko** [comment]
Presumably this issue should be moved to the https://github.com/JuliaLang/www.julialang.org repo, I don't think I'm able to do that.

**Comment by KronosTheLate** [comment]
Thanks! I will just manually move it there.
