### ISSUE TITLE
Option to pin GC threads

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/julia#53073]
I would like to add the ability to pin GC threads to ThreadPinning.jl. AFAICS, we (a user) can't run Julia code on GC threads. Hence, I think we need to add something like https://github.com/OpenMathLib/OpenBLAS/blob/4d0b7fbec04c95c90291938a5974f00673e10e68/driver/others/blas_server.c#L341-L369 to the C runtime.

Would it be possible/accepted to add such functions?

(cc @vchuravy)

PS: IIUC, we can't add this retrospectively to 1.10 but it would be great to get it into 1.11.

**Comment by carstenbauer** [comment]
Because I'm giving a Julia course at UCL this week, I couldn't implement the before 1.11 feature freeze (today), which is a bit sad. If I implement this next week, is there any chance that we can still get this into 1.11?

**Comment by gbaraldi** [comment]
I believe so, if the code isn't super complex (I don't believe it would be)

**Comment by carstenbauer** [comment]
I'm trying to implement this but I have a problem. [AFAICS](https://github.com/JuliaLang/julia/blob/02699bb6cd83d16b1e51e2fb127241e18df7c56b/src/threading.c#L795), we don't seem to store the thread handles (`uv_thread_t uvtid`) of any of the threads, which I'd like to use for `uv_thread_setaffinity` and `uv_thread_getaffinity` calls later on.

Note that [OpenBLAS stores these handles](https://github.com/OpenMathLib/OpenBLAS/blob/30473b6a9d2179606ad4eff2861418b6b6e7e9f0/driver/others/blas_server.c#L128) and it was thus pretty easy to add affinity functions, e.g. https://github.com/OpenMathLib/OpenBLAS/pull/3702/files#diff-2b77a530a65c94d60feb21d4ce2093df0a2bd3cb710d2dc82bab32f18e1c963a.

Should I add a new storage for them or is there a different/better way to get the handles?

**Comment by carstenbauer** [comment]
Ok, seems like we are [storing](https://github.com/JuliaLang/julia/blob/02699bb6cd83d16b1e51e2fb127241e18df7c56b/src/threading.c#L353) the information in the TLS (specifically, [in the field `system_id`](https://github.com/JuliaLang/julia/blob/02699bb6cd83d16b1e51e2fb127241e18df7c56b/src/julia_threads.h#L245)). Guess I have to figure out now how to query the information from [`jl_all_tls_states`](https://github.com/JuliaLang/julia/blob/02699bb6cd83d16b1e51e2fb127241e18df7c56b/src/threading.c#L314) somehow.
