### ISSUE TITLE
`jl_array_data` returns a null pointer when called with an array of bits unions

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaLang/julia#53072]
`jl_array_data` returns a pointer to the data of the array for arrays of bits or pointers, but a null pointer for bits union arrays since `jl_genericmemory_t` was introduced:

```C
#include <julia.h>
JULIA_DEFINE_FAST_TLS

int main(int argc, char *argv[])
{
    jl_init();

    {
        jl_value_t *arr = jl_eval_string("Int[1]");
        void *arr_data = jl_array_data(arr, void);
        assert(arr_data != NULL);
    }

    {
        jl_value_t *arr = jl_eval_string("Any[1]");
        void *arr_data = jl_array_data(arr, void);
        assert(arr_data != NULL);
    }

    {
        jl_value_t *arr = jl_eval_string("Union{Int32, Int64}[1]");
        void *arr_data = jl_array_data(arr, void);
        // This assert currently fails
        assert(arr_data != NULL);
    }

    jl_atexit_hook(0);
    return 0;
}
```

**Comment by oscardssmith** [comment]
the problem is that for non bitsunions the memoryref stores the pointer to the first element of the array, but for bitsunion memories, it stores the offset from the first element. So it's technically not true that it returns a null pointer. If you `pushfirst!` to the array, you would see that it returned a small but nonzero number. This should be pretty easy to fix.

**Comment by vtjnash** [comment]
You probably wanted `jl_array_ptr` from the rtutils code. The type in `jl_array_data` is now required to be a type with the correct TBAA and element size properties, which `void` does not have.

**Comment by vtjnash** [comment]
(This cannot be a regression, since this is a new macro)

**Comment by oscardssmith** [comment]
`jl_array_data` is new?

**Comment by vtjnash** [comment]
`jl_array_data(x, t)` is new

**Comment by Taaitaaiger** [comment]
> You probably wanted jl_array_ptr from the rtutils code. The type in jl_array_data is now required to be a type with the correct TBAA and element size properties, which void does not have.

@vtjnash thanks, I'll give jl_array_ptr a try. I'm afraid I probably won't have time for that until March, though.
