### ISSUE TITLE
some `Union` constructors don't throw

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#53120]
It's my understanding that type unions should not be callable, i.e., they shouldn't have constructors, i.e., trying to call such a constructor should throw. The `Union` doc string says something that might be interpreted in such a way:

> Like other abstract types, it cannot be instantiated, even if all of its arguments are non abstract.

Would it be good to make these throw, then:

```julia-repl
julia> Union{Int8,Int}(4)
4

julia> Union{Tuple{},Tuple{Int}}(())
()

julia> Union{Tuple{},Tuple{Int}}((4,))
(4,)
```

Otherwise (if `Union` constructors are desirable), I guess that the documentation should mention that newly defined types should support `Union` constructors somehow.

**Comment by vtjnash** [comment]
It is unlikely we are going to add a breaking rule against defining some methods. Users should be able to define any methods they want.

**Comment by jakobnissen** [comment]
There are also abstract constructors several places in Julia. We've never had a rule against those. I don't think it's bad to use a nob-concrete type as a constructor, as long as the result is an instance of the constructor type.
