### ISSUE TITLE
julia 1.6.7: union type issue on Windows

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaLang/julia#53136]
I am trying to support the LTS version of julia for my packages, but I get this strange result on Windows for julia 1.6.7:

```
julia> _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S
_nonuniontype (generic function with 1 method)

julia> _nonuniontype(Missing,Union{Missing,Float64})
Union{Missing, Float64}

# expected Float64
```

while on julia 1.10 (windows) or julia 1.6.2 (linux) I get the expected result:

```
_nonuniontype(Float64,Union{Missing,Float64})
Float64
```

Is this a known issue? 

I need a function that is similar to `Base.nonmissingtype` but works also for other singleton types (like Nothing).

(Thank you for your feedback :-) )

julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)

Julia from https://julialang-s3.julialang.org/bin/winnt/x64/1.6/julia-1.6.7-win64.exe

**Comment by nsajko** [comment]
Indeed this seems to work fine on Linux:

```julia-repl
julia> _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S
_nonuniontype (generic function with 1 method)

julia> _nonuniontype(Missing,Union{Missing,Float64})
Float64

julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

```julia-repl
julia> _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S
_nonuniontype (generic function with 1 method)

julia> _nonuniontype(Missing,Union{Missing,Float64})
Float64

julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (i686-pc-linux-gnu)
  CPU: AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

**Comment by Alexander-Barth** [comment]
For information, it seems to be fixed since julia 1.8 (and only affects windows):

https://github.com/Alexander-Barth/NCDatasets.jl/actions/runs/7714333502

**Comment by inkydragon** [comment]
Starting at 1.0, affects 1.6~1.7, fixed after 1.8

```
PS T:\> julia +1.10 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
true
PS T:\> julia +1.9 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
true
PS T:\> julia +1.8 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
true
PS T:\> julia +1.7 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
false
PS T:\> julia +1.6 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
false
PS T:\> julia +1.0 -E ' _nonuniontype(::Type{T},::Type{Union{T,S}}) where {T,S} = S; _nonuniontype(Missing,Union{Missing,Float64}) == Float64'
false
```

**Comment by vtjnash** [comment]
FWIW, this is supposed to throw an `UndefVarError` on all versions, but that failure is the real bug here.

You might be looking for either `Base.nonnothingtype` or `Base.typesplit`, which implement this correctly for you (you may need to backport a copy of the implementation to v1.6 however)

**Comment by Alexander-Barth** [comment]
It is not clear to me why this function should return a `UndefVarError`, but I will use the approach from `Base.typesplit`.
Thanks a lot for looking into this!
