### ISSUE TITLE
more source-build problems, with openblas now on CI

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#53172]
```
In file included from ../kernel/x86_64/sbgemm_kernel_16x16_spr.c:31:
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c: In function 'sbgemm_kernel_spr_alpha_one':
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:67:2: warning: implicit declaration of function '_tile_loadconfig' [-Wimplicit-function-declaration]
   67 |  _tile_loadconfig(&cfg);
      |  ^~~~~~~~~~~~~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:201:4: note: in expansion of macro 'TCONF'
  201 |    TCONF(cfg, 16, 16, 32);
      |    ^~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:137:22: warning: implicit declaration of function '_tile_loadd' [-Wimplicit-function-declaration]
  137 | #define LOAD_C(M, N) _tile_loadd(T_C##M##N, ptr_c##M##N, ldc * 4)
      |                      ^~~~~~~~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:212:5: note: in expansion of macro 'LOAD_C'
  212 |     LOAD_C(0, 0); LOAD_C(0, 1);
      |     ^~~~~~
```
https://buildkite.com/julialang/julia-master-scheduled/builds/643#018d6e03-2129-477c-9c41-22a940ea5492

**Comment by inkydragon** [comment]
These two functions are Intel® AMX (Advanced Matrix Extensions) Intrinsics Functions
- [`_tile_loadconfig`](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-10/tile-loadconfig.html)
- [`_tile_loadd`](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-10/tile-loadd.html)

Looks like a legacy issue, most recent modifications were 3 years ago:
https://github.com/OpenMathLib/OpenBLAS/blame/e5d2725e5a29981cab4068233ab97b6daa25b540/kernel/x86_64/sbgemm_oncopy_16_spr.c#L63

Maybe it's not a regression?

**Comment by giordano** [comment]
Those reported above are warnings, not errors?

**Comment by inkydragon** [comment]
errors in build openblas
```
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:116:16: error: incompatible types when initializing type '__m256i' using type 'int'
  116 |  __m256i ymm = _mm256_loadu_epi16(ptr_b##N); \
      |                ^~~~~~~~~~~~~~~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:359:21: note: in expansion of macro 'LOAD_B_TAIL'
  359 |       LOAD_B(x, 0); LOAD_B_TAIL(x, 1);
      |                     ^~~~~~~~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:116:16: error: incompatible types when initializing type '__m256i' using type 'int'
  116 |  __m256i ymm = _mm256_loadu_epi16(ptr_b##N); \
      |                ^~~~~~~~~~~~~~~~~~
../kernel/x86_64/sbgemm_kernel_16x16_spr_tmpl.c:435:7: note: in expansion of macro 'LOAD_B_TAIL'
```

**Comment by inkydragon** [comment]
[`_mm256_loadu_epi16`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm256_loadu_epi16&expand=3365)
Need CPU flag: `AVX512BW + AVX512VL`

Maybe our CPU doesn't support this?

**Comment by giordano** [comment]
We do a dynamic arch build https://github.com/JuliaLang/julia/blob/28db6c7a1159bba9e1745416df0f2917c5e9324c/deps/openblas.mk#L32 the host CPU shouldn't matter. But it's quite possible a newer compiler is needed, in Yggdrasil we're now using gcc 11 for openblas, I don't know what's used in CI

**Comment by inkydragon** [comment]
Compare with [old build (19th Dec 2023)](https://buildkite.com/julialang/julia-master-scheduled/builds/595#018c8117-be61-4d1f-aa3f-5987e32f4876) which openblas build successfully. 
(Search "OpenBLAS build complete")

A new flag has been added: `BUILD_BFLOAT16=1`.

<img width="1056" alt="image" src="https://github.com/JuliaLang/julia/assets/5158738/eaed15b8-27fb-4799-a5e1-f422e30a8bf6">

**Comment by giordano** [comment]
> But it's quite possible a newer compiler is needed, in Yggdrasil we're now using gcc 11 for openblas, I don't know what's used in CI here for the source build.

It's hard to read to raw log, I see a line containing
```
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
```
if that's the compiler used for the build, according to https://github.com/JuliaPackaging/Yggdrasil/pull/7202#issuecomment-1678166341 gcc 10 should be sufficient to build the bfloat16 kernels.

**Comment by imciner2** [comment]
Well, based on the comment here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95483#c4, many of these intrinsics were missing and then added in GCC 11, e.g. the intrinisic `_mm256_loadu_epi16` is referenced in that bug report as being added for GCC 11.

I'm not entirely sure what would make it seem like it worked on Yggdrasil when I built it before and not work here, but I may have just skipped to GCC 11 and not fully dived into anything for GCC 10 when I was doing the builds.

**Comment by imciner2** [comment]
(and as it stands, building from source on Windows also needs our own patched GCC for BFloat16 to get the optimized kernels, unless the user has GCC 12.3 or 13+ and is using that), so for now, BFloat16 support is probably not something to expose in pure from-source builds due to its somewhat complex compiler support history.
