### ISSUE TITLE
Add population sampling function

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#5317]
Sampling from a given population is a very common operation which I think deserve a place in the Julia base. I think it is much more frequently used (even out of the statistics community) than say `randperm` and `randcycle`. 

There are a lot of non-statistics-related applications that want this function to randomize things (e.g. randomly pick several elements from a collection). Now they have to either reinvent the wheel (in a possibly less efficient way) or import the entire Distributions package (which takes quite a few seconds to load).

The interface is currently as follows:

``` julia
# draw an element from an array a
sample(a)             

# draw n elements with or without replacements
sample(a, n[; replace=true])   

# draw n elements and put them to a pre-allocated array
sample!(dst, a, n[; replace=true])
```

Of course, the design of the interface is open to discussion.

**Comment by kshyatt** [comment]
Since we moved a bunch of statistics stuff out into the package ecosystem, it seems unlikely we'll put this into `base`.
