### ISSUE TITLE
REPL does not have StyledStrings in its dependencies

### ISSUE THREAD

**Issue by fatteneder** [JuliaLang/julia#53176]
From https://discourse.julialang.org/t/error-while-running-julia-executable/109699

I can reproduce this on 3d8b10770a7a7317dde13ae36881991db356326c. Likely caused by [6e7db14712efbacca0569b1ac25e5fd7484d8906.](https://github.com/JuliaLang/julia/pull/51869).

**Comment by fatteneder** [comment]
It works when using the locally built repo:
```sh
JULIA_DEPOT_PATH=<git-repo>/usr/share/julia ./julia
```

**Comment by KristofferC** [comment]
This is an annoying issue which comes from the combination of REPL not being in the sysimage and the active project being used to look up the dependencies. You can either use a temp depot like that, activate the v1.11 environment and do a resolve or delete it or we have to figure out a better solution.

**Comment by KristofferC** [comment]
> This does not work, because REPL throws the same error when attempting using Pkg.

You need to load Pkg in this "empty" env as well.

**Comment by tecosaur** [comment]
`rm ~/.julia/environments/v1.11/Manifest.toml && ./julia --startup-file=no` should do it, no?

**Comment by ShrutiRDalvi** [comment]
> `rm ~/.julia/environments/v1.11/Manifest.toml && ./julia --startup-file=no` should do it, no?

This worked for me, thanks a lot

**Comment by KristofferC** [comment]
> ...  should do it, no?

well yes, but then you get rid of all your package versions which you might not want

**Comment by nsajko** [comment]
This seems to break VS Code on nightly Julia: https://discourse.julialang.org/t/cant-start-language-server-with-nightly-julia-package-repl-does-not-have-styledstrings-in-its-dependencies/110071

**Comment by staticfloat** [comment]
I think we should have a special mode for loading `REPL` and `Pkg` that attempts to do so with the given environment stack, and if it is unable to it prints a warning and uses only `@stdlib`.  This way we still allow users to override their `REPL` and `Pkg` versions as needed, but if things are broken, you still get a functional Julia.

**Comment by inkydragon** [comment]
The nightly CI for `SHA.jl` also ran into this problem.

https://github.com/JuliaCrypto/SHA.jl/actions/runs/7967342891/job/21749961409?pr=105#step:5:47
