### ISSUE TITLE
`resize!(x,...)` not working after `y = x * A[1:1, :]`

### ISSUE THREAD

**Issue by SteffenPL** [JuliaLang/julia#53191]
The following raises an error
```julia
x = zeros(2)
A = rand(2, 2)
l = x * A[1:1, :]
resize!(x, 3)
```
with error message
```
ERROR: cannot resize array with shared data
Stacktrace:
 [1] _growend!
   @ ./array.jl:1070 [inlined]
 [2] resize!
   @ ./array.jl:1313 [inlined]
 [3] top-level scope
 ```

It's related to #43507 and #33143. 

The difference between the existing issues is that from a user perspective, there is no in-place operation done on `x`. Therefore, it was surprising for me that `x` loses it's data. 

(One can avoid the error by using `view(x,:) * A[1:1, :]` or `x * A[1,:]'`.)

The code was run on `Julia 1.10`. (I can provide version info etc, but it seems not that relevant.)

**Comment by oscardssmith** [comment]
Note that on 1.11, this no longer occurs (thanks to the memory PR)

**Comment by christiangnrd** [comment]
This seems fixed on master.
