### ISSUE TITLE
CI test output `results.json` contains a lot of duplicate entries

### ISSUE THREAD

**Issue by inkydragon** [JuliaLang/julia#53198]
1. Open https://buildkite.com/julialang/julia-master/builds/33133#018d7b6a-ce86-45be-800e-8f0498598629
2. Locate the "Artifacts" tab
3. Download [julia-28db6c7a11/share/julia/test/results.json](https://buildkite.com/organizations/julialang/pipelines/julia-master/builds/33133/jobs/018d7b6a-ce86-45be-800e-8f0498598629/artifacts/018d7bde-8ccc-42f8-8c42-db326f13771f)
4. Open `results.json`
5. `LinearAlgebra/addmul` repeated 4000+ times

<img width="512" alt="image" src="https://github.com/JuliaLang/julia/assets/5158738/ce544c09-8609-48c4-98ef-10550ac4006d">

JSON Output code:
https://github.com/JuliaLang/julia/blob/28db6c7a1159bba9e1745416df0f2917c5e9324c/test/runtests.jl#L431-L435
https://github.com/JuliaLang/julia/blob/28db6c7a1159bba9e1745416df0f2917c5e9324c/test/buildkitetestjson.jl#L11

cc: @tecosaur

**Comment by IanButterworth** [comment]
It has entries for all non-Pass results, and some tests do `@test_broken` in loops. 

This isn't a bug, but arguably it could de-duplicate test failures in the reporting itself.

**Comment by tecosaur** [comment]
This is a bit of a tangent, but for cases where there's a test run in a loop, I wonder if we could somehow do better than
```julia
for i in [...]
     @test f(i)
end
```
with something like
```julia
@bulktest for i in [...]
    @test f(i)
end # Combine into a single test result somehow
```
or similar

**Comment by tecosaur** [comment]
> This isn't a bug, but arguably it could de-duplicate test failures in the reporting itself.

Yea, I think that would be good. I'll see about implementing that.

**Comment by vtjnash** [comment]
We do have `@testset for` already, so maybe that can somehow combine them? Or just automatically match up all tests with the same line number, and combine them into a single report? I don't know if that needs to be done before generating, or if the later UI tools are capable of merging those already.

**Comment by tecosaur** [comment]
#53333 now exists (hey, that's a surprisingly memorable PR number), which should let us confirm (or disprove) my suspicion :crossed_fingers:

**Comment by tecosaur** [comment]
Wait, wrong tab. Ooops, please ignore this :see_no_evil:

**Comment by IanButterworth** [comment]
@tecosaur on slack I proposed that we just make the results.json contain testset objects.
If the testset has any failures, then group them into the testset somehow.

Recording Results objects seems too tricky because Test.jl doesn't retain Pass info for memory reasons (that seem hard to avoid) and recording testsets are good because they always exist, pass or fail or otherwise, which seems better for the way buildkite analytics is set up.

**Comment by tecosaur** [comment]
Ah right, I see the sense in that. From a "tracking test results over time" I still think there's value to be had in test-level granularity, but am not sure what's the best balance of concerns.

One PR I'm most of the way through spinning up is just merging duplicate entries, which seems like a completely clear improvement.
