### ISSUE TITLE
Scheduled build `*-NoGPL` all failed

### ISSUE THREAD

**Issue by inkydragon** [JuliaLang/julia#53211]
Currently, `NoGPL ≈ No SparseArrays = No SuiteSparse ` 
SuiteSparse contains a lot of modules, we just need to exclude the GPL ones..

<details>
<summary>SuiteSparse Licenses</summary>

BSD
- `libamd`: [BSD 3-clause](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/AMD/Doc/License.txt)
- `libcamd`: [BSD 3-clause](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/CAMD/Doc/License.txt)
- `libccolamd`: [BSD 3-clause](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/CCOLAMD/Doc/License.txt)
- `libcolamd`: [BSD 3-clause](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/COLAMD/Doc/License.txt)
- `libsuitesparseconfig`: [BSD-3-clause](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SuiteSparse_config/README.txt)

LGPL
- `libbtf`: [LGPL-2.1+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/BTF/Doc/License.txt)
- `libklu`: [LGPL-2.1+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/KLU/Doc/License.txt)
- `libldl`: [LGPL-2.1+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/LDL/Doc/License.txt)

GPL
- `libcholmod`: [LGPL-2.1+ and GPL-2.0+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/CHOLMOD/Doc/License.txt)
	CHOLMOD/Check: [LGPL-2.1+]
	CHOLMOD/Cholesky: [LGPL-2.1+]
	CHOLMOD/Utility: [LGPL-2.1+]
	CHOLMOD/Demo: [GPL-2.0+]
	CHOLMOD/MATLAB: [GPL-2.0+]
	CHOLMOD/MatrixOps: [GPL-2.0+]
	CHOLMOD/Modify: [GPL-2.0+]
	CHOLMOD/Partition: [LGPL-2.1+]
	CHOLMOD/Supernodal: [GPL-2.0+]
	CHOLMOD/Tcov: [GPL-2.0+]
- `librbio`: [GPL-2.0+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/RBio/Doc/License.txt)
- `libspqr`: [GPL-2.0+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/SPQR/Doc/License.txt)
- `libumfpack`: [GPL-2.0+](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/dev/UMFPACK/Doc/License.txt)

</details>

- https://github.com/JuliaSparse/SparseArrays.jl/pull/535
- https://github.com/JuliaCI/julia-buildkite/pull/350

**Comment by rayegun** [comment]
Just the solvers should be removed, not the entirety of SA I think.

**Comment by inkydragon** [comment]
> the solvers should be removed

Do you mean keep the type and function prototype, but with an empty implementation?

Ideally, SparseArrays will continue to work fine if MKL.jl is loaded when compiling with NO-GPL.

**Comment by imciner2** [comment]
> > the solvers should be removed
> 
> Do you mean keep the type and function prototype, but with an empty implementation?
> 
> Ideally, SparseArrays will continue to work fine if MKL.jl is loaded when compiling with NO-GPL.
> 

Only the SuiteSparse wrappers in SparseArrays needs to be removed to make it no GPL. The rest of the stdlib should still remain, because it can be used with other backends and libraries.

**Comment by rayegun** [comment]
https://github.com/JuliaSparse/SparseArrays.jl/blob/a5e95ec23649bd8cb75d2923861c74061016d1dd/src/SparseArrays.jl#L81

See here. Only these files need to remain unloaded. SparseArrays.jl itself should work just fine without them, you just won't have access to fast factorizations (LinearAlgebra generic factorizations *might* work? But incredibly slowly if they exist).
