### ISSUE TITLE
rank(::QRPivoted) method?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#53214]
Since pivoted QR is a rank-revealing calculation, it seems like we should have a `LinearAlgebra.rank` method that works directly on it.  Something like:
```jl
function rank(F::QRPivoted; atol::Real=0, rtol::Real=min(size(F)...)*eps(real(float(one(eltype(F)))))*iszero(atol))
    m = min(size(F)...)
    m == 0 && return 0
    tol = max(atol, rtol*abs(F.R[1,1]))
    return something(findfirst(i -> abs(F.R[i,i]) <= tol, 1:m), m+1) - 1
end
```
should do it, no?

Of course, this won't necessarily return the same thing as the SVD-based rank (and is less reliable than SVD — it shouldn't be the default method for `::AbstractMatrix`), but inconsistency is the fate of all numerical rank computations.  In typical cases it should be close, one hopes, and if you have the QR you should be able to explicitly ask what numerical rank it reveals.

**Comment by jefftrojan** [comment]
Hi, I am trying to make an attempt on this, I have a question tho... Could you explain the motivation behind introducing a rank calculation based on the pivoted QR decomposition?

**Comment by stevengj** [comment]
It's way faster than the SVD (used by default for `rank(A)`), although it is somewhat less reliable.  Moreover, if you already have the QR factorization, you might want to re-use it for the rank.

See, for example, [this discussion](https://discourse.julialang.org/t/how-to-find-the-linearly-independent-columns-rows-of-a-matrix/109772/14?u=stevengj).

**Comment by aravindh-krishnamoorthy** [comment]
> Hi, I am trying to make an attempt on this, I have a question tho... Could you explain the motivation behind introducing a rank calculation based on the pivoted QR decomposition?

This $2021$ blog post should also give you some insight into the rank-revealing property of some matrix factorizations: [What Is a Rank-Revealing Factorization?](https://nhigham.com/2021/05/19/what-is-a-rank-revealing-factorization/)

**Comment by stevengj** [comment]
Similarly, it might be nice to have a `nullspace(::QRPivoted)` method.
