### ISSUE TITLE
Waiting multiple tasks simultaneously

### ISSUE THREAD

**Issue by mrkn** [JuliaLang/julia#53226]
I wrote two methods that can wait for multiple tasks like Python’s `asyncio.wait`.

The two methods, `waitany` and `waitall`, have the following features:

* The `waitany` function waits at least one of the given tasks.
* The `waitall` function normally waits for all the given tasks. This function has an optional keyword argument `failfast`. If `failfast` is `true`, the function returns at least one of the given tasks stops by exception.
* Both functions return a 2-tuple of vectors. The first vector consists of finished tasks. The second vector consists of tasks that have not been done at the time of finish detection.

The implementation and tests for `waitany` and `waitall` methods are hosted in my repository.  You can find the implementation of these methods [here](https://github.com/mrkn/julia/blob/ae8b0cbfc05bec54da2a433afd7b0c6deb5bd792/base/task.jl#L368-L400).  The associated tests are available [here](https://github.com/mrkn/julia/blob/ae8b0cbfc05bec54da2a433afd7b0c6deb5bd792/test/threads_exec.jl#L1190-L1260).

These methods can be provided in Julia’s base library because the features should have common needs, IMO. I want to submit a pull request to add these two methods, but I have some questions about these methods.

## Questions

1. `waitany` and `waitall` can be combined into one method like `asyncio.wait` but I have chosen not to do so. The reason is that I think `waitany` and `waitall` are more readable and clearer than `asyncio.wait` because these names explicitly convey their functionality, making it easier for developers to understand they wait multiple tasks without checking the arguments. I want to know which interface is more suitable for Julia’s standard library design convention.
2. Julia has other waitable objects than a task, such as a channel and an IO. I think we can make `waitall` and `waitany` be able to wait for all kinds of waitables. Which task-specific or more universal is suitable for Julia’s standard feature?
3. Both functions return a 2-tuple of `Vector{Task}` whereas `asyncio.wait` returns a 2-tuple of sets of tasks.  Which return type is better?
4. It is my first challenge of working on Julia’s core. If there are any other considerations, I want to know them.

**Comment by MasonProtter** [comment]
Very cool @mrkn, I was actually just wanting something very similar, where I wanted basically something like
```
wait_or(::Event, ::Vector{Task})
```
which would either wait for **all** the elements of the `Vector` to finish **or** for the `Event` to be notified.

I asked about it [on Slack](https://julialang.slack.com/archives/C6SMTHQ3T/p1707266458613779) yesterday and @vtjnash mentioned that doing a `while` loop with `yield` "may cause you a lot of performance issues and grief", so I'd be very interested to know how the performance looks here, since this is also essentially a `yield`ing while loop.

**Comment by mrkn** [comment]
@MassonProtter Thank you for your comment. I believe your `wait_or` function could be implemented using my `waitall` function as shown below:

```
function wait_or(event::Event, tasks::Vector{Task})
    waitall_task = Threads.@spawn begin
        waitall(tasks)
        notify(event)
    end
    wait(event)
    if istaskdone(waitall_task)
        true  # This means all the tasks has been done
    else
        Base.throwto(waitall_task, InterruptException())
        false  # This means the event has been notified first
    end
end
```

Regarding the "performance issues" mentioned by @vtjnash, if the concern is that a while-loop with `yield` might lead to a busy loop, I share the same awareness. To mitigate this, considering the insertion of a `jl_cpu_pause` function call either before or after the `yield` could be beneficial to reduce CPU usage during the while-loop.

**Comment by vtjnash** [comment]
`throwto` may cause problems where the program crashes, so is fairly strongly discouraged. A `jl_cpu_pause` call will not help with fixing the design problem there. Take a look at the implementation of `Experimental.@sync` if you want to see how to implement a `waitany` call correctly.

**Comment by mrkn** [comment]
@vtjnash Thank you for your advice. I’ve checked the implementation of `Experimentals.@sync`  and I’ve understood it’s a `Channel`-base implementation. I immediately rewrote `waitany`  and `waitall`  functions using `Channel`. The new implementation can be found at https://github.com/mrkn/julia/blob/a70c1bdf214a043834c567edd108d56f643ba039/base/task.jl#L368-L420.

Actually, `waitany`  and `waitall`  were originally implemented using `Channel`. In that version, tasks waiting for the completion of the given tasks were left unattended without cleanup when `waitany`  or `waitall`  with `failfast` option. I thought it would be better to avoid such task leaks, so I rewrote it using a while-loop and `yield`, and then posted this issue. `Experimentals.@sync` also leaves tasks that wait for the given tasks unattended when exiting `@sync` due to an exception. Should I not worry about such task leaks?

**Comment by mrkn** [comment]
Thank you everyone for your comments and reactions. Big thanks to @vtjnash for your comment, it helped fix a major issue in the implementation. I've made a pull request with the current implementation. If there's anything else, please leave comments on the pull request.

**Comment by mind6** [comment]
> `throwto` may cause problems where the program crashes, so is fairly strongly discouraged. A `jl_cpu_pause` call will not help with fixing the design problem there. Take a look at the implementation of `Experimental.@sync` if you want to see how to implement a `waitany`/`waitall` call correctly (it implements waitall with failfast).

Can you explain more about the issue with `throwto`? It sounds like the choice is between this or task leaking. If `throwto` is acceptable then we're saying tasks that hang on `wait(...)` can be reliably terminated. If not acceptable then tasks leaks are responsibility of user; she must choose to close the Channel at some point, or to reset the Event object.
